### ISSUE TITLE
Support @HostListener on observable fields

### ISSUE THREAD

**Issue by Airblader** [angular/angular#31220] opened 2019-06-23 19:32 UTC
# 🚀 feature request

### Relevant Package
This feature request is for @angular/core.

### Description
Support `@HostListener` not only on functions which are then called, but also on fields of type `Subject`. Note that this should not only call `next`, but also `complete` when the listener is removed.

```
// A: No arguments
@HostListener('click')
public readonly clickA$ = new Subject<void>();

// B: With a (typed) argument
@HostListener('click', ['$event'])
public readonly clickB$ = new Subject<Event>();

// C: Also support other types of Subject
@HostListener('click', ['$event'])
public readonly clickB$ = new ReplaySubject<Event>(1);
```

This is somewhat related to #4511, but it's a different proposal which basically would remove boilerplate from applications without introducing any kind of new API surface; it would just "start to work". This seems like a good compromise between making the API a bit more reactive while not bloating the framework. Thoughts?

**Comment by pkozlowski-opensource** [comment] 2020-03-05 16:40
Duplicate of #19483. Closing in favour of #19483 as it has more discussion. Please add your input in there if you've got additional ideas / solutions / proposals. Thnx!

**Closed by pkozlowski-opensource** 2020-03-05 16:40 UTC
Labels: comp: core, type: feature
