### ISSUE TITLE
In the component template the parent element USES display:inline block the child element without gaps

### ISSUE THREAD

**Issue by liangshen001** [angular/angular#35517] opened 2020-02-18 07:36 UTC
### Description

In the component template the parent element USES display:inline block the child element without gaps

## 🔬 Minimal Reproduction

[https://angular-tegpl9.stackblitz.io](https://angular-tegpl9.stackblitz.io)

## 🌍   Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 8.3.23
Node: 12.14.0
OS: darwin x64
Angular: 
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.803.23
@angular-devkit/core         8.3.23
@angular-devkit/schematics   8.3.23
@schematics/angular          8.3.23
@schematics/update           0.803.23
rxjs                         6.4.0

</code></pre>

Thank you in advance!!!

**Comment by liangshen001** [comment] 2020-02-18 07:38
I expect the display effect to be:

test test

**Comment by pkozlowski-opensource** [comment] 2020-02-18 10:07
This is because, by default, Angular removes white-spaces between HTML tags (`<span>`s in your example). You can opt out of this behaviour as described in https://angular.io/api/core/Component#preserving-whitespace

Closing as a duplicate of #21049

**Closed by pkozlowski-opensource** 2020-02-18 10:07 UTC
