### ISSUE TITLE
Angular2 DI - class inheritance breaks DI

### ISSUE THREAD

**Issue by draconisNoctis** [angular/angular#11830] opened 2016-09-22 14:46 UTC
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 
Multiple inheritance from one class leads to multiple/shared metadata when the base class has an annotation.

```
import 'reflect-metadata';
import { Injectable, Inject } from '@angular/core';

class A {}
class B {}
class C {}

// Enabling this decorator leads to same log output for booth classes
//@Injectable()
class BaseClass {
  constructor(protected a : A) {}
}

@Injectable()
class Cls1 extends BaseClass {
  constructor(@Inject(B) protected b : B, @Inject(A) a : A) {
    super(a);
  }
}

@Injectable()
class Cls2 extends BaseClass {
  constructor(@Inject(C) protected c : C, @Inject(A) a : A) {
    super(a);
  }
}

console.log(Reflect.getMetadata('parameters', Cls1))
console.log(Reflect.getMetadata('parameters', Cls2))
```

**Expected behavior**
The DI/Typescript-Metadata should affect only the classes where they are present.

**Reproduction of the problem**
Simple example project: https://github.com/draconisNoctis/angular2_di_issue

**What is the motivation / use case for changing the behavior?**
Any larger project needs inheritance of components/services etc. 

* **Angular version:** 2.0.0-final

* **Browser:** all & nodejs

* **Language:** all | ES5

**Comment by vicb** [comment] 2016-09-22 15:29
describe what you expect and what you have in your repro. thanks.

**Comment by draconisNoctis** [comment] 2016-09-23 06:28
Updated the issue. 
I hope, I could clarify my concern.

**Comment by manklu** [comment] 2016-09-23 06:31
Seems to be a duplicate of #8700.

**Comment by draconisNoctis** [comment] 2016-09-23 06:54
My usecase worked at least till RC5, so I believe it is a similar but not identical problem.

I could trace the problem to a behavior of reflect-metadata. 
When you try to read the metadata of a class, but this class has no metadata, reflect-metadata is looking up for it in the parent class. So Angular DI edits the metadata of the parent and writes it to the childclass.

My current workaround is to remove all class decorators on all abstract classes.

**Comment by vicb** [comment] 2016-10-10 00:05
Will be treated as part of #11606

**Closed by vicb** 2016-10-10 00:05 UTC
Labels: flag: can be closed?
