### ISSUE TITLE
ngOnInit not firing when clicking browser's back button.

### ISSUE THREAD

**Issue by jordankittle** [angular/angular#43412] opened 2021-09-10 02:06 UTC
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

No

### Description

When I click the back button on my browser, Angular is not loading the component again when Angular is deployed on a  subdomain. It works as expected locally and when not deployed on a subdomain.  As an example. If I set a boolean with default of false to true, then navigate away from the page, when I click the back button on the browser the boolean would still be true.  When running locally it will always be the default of false because the component loads again after clicking back. This is very frustrating. This issue has been opened before, but it was closed and never addressed even though tons of people were saying they had the same problem.

**Comment by atscott** [comment] 2021-09-10 19:49
@jordankittle What is the issue number of the previous one that was closed?

Also, please provide a sample project.

**Comment by atscott** [comment] 2021-09-14 18:00
Closing due to lack of reproduction. From looking back at previous similar reports, this was due to expected and documented behavior of `onSameUrlNavigation`/`RouteReuseStrategy`

**Closed by atscott** 2021-09-14 18:00 UTC
Labels: needs reproduction, comp: router, comp: core
