### ISSUE TITLE
File '...' is missing from the TypeScript compilation

### ISSUE THREAD

**Issue by KevTale** [angular/angular#52815] opened 2023-11-11 11:32 UTC
### Which @angular/* package(s) are the source of the bug?

compiler

### Is this a regression?

Yes

### Description

From time to time when Angular recompiles the app (when I hit CTLR+S in VSCode) I got an error saying the current file I'm saving is missing from the typescript compilation.

If I'm saving on a component route I got the following error.

```ts
✘ [ERROR] File 'src\app\first.route.ts' is missing from the TypeScript compilation. [plugin angular-compiler]

    src/app/app.routes.ts:7:30:
      7 │   loadComponent: () => import('./first.route').then(m => m.FirstRoute)
        ╵                               ~~~~~~~~~~~~~~~

  Ensure the file is part of the TypeScript program via the 'files' or 'include' property.
```

This is a simple component used as a route.

```ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-first-route',
  standalone: true,
  template: `
    <h1>My route</h1>
  `,
})
export class FirstRoute {}
```

```ts
export const routes: Routes = [
  {
    path: '',
    redirectTo: 'first',
    pathMatch: 'full',
  },
  {
    path: 'first',
    loadComponent: () => import('./first.route').then((m) => m.FirstRoute),
  },
];
```

If I'm saving on the AppComponent I got this one:

```ts
✘ [ERROR] File 'src\app\app.component.ts' is missing from the TypeScript compilation. [plugin angular-compiler]

    src/main.server.ts:2:29:
      2 │ import { AppComponent } from './app/app.component';
        ╵                              ~~~~~~~~~~~~~~~~~~~~~

  Ensure the file is part of the TypeScript program via the 'files' or 'include' property.
```

- It happens randomly when the app recompiles even though I didnt change anything in the file, I'll bash CTLR+S and from time to time (maybe once every 7-15 saves) it will pop up that error
- This is a fresh Angular 17 app, I literally did nothing expect created the new route component and add it to the routes files

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.0.0
Node: 20.9.0
Package Manager: npm 9.4.2
OS: win32 x64

Angular: 17.0.2
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.0
@angular-devkit/build-angular   17.0.0
@angular-devkit/core            17.0.0
@angular-devkit/schematics      17.0.0
@angular/cli                    17.0.0
@angular/ssr                    17.0.0
@schematics/angular             17.0.0
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.2
```

**Comment by JeanMeche** [comment] 2023-11-11 11:38
Hi, this looks like a dupe of angular/angular-cli#26284 could try to provide a repro there ?

**Closed by JeanMeche** 2023-11-11 11:38 UTC
