### ISSUE TITLE
angular 11 - rebuild with ng serve (auto) is not reliable

### ISSUE THREAD

**Issue by pete0959** [angular/angular#39870] opened 2020-11-27 23:57 UTC
Using **ng serve** the compiler will detect any changes and auto-recompile/build.
During development making minor changes sometimes causes an error. The compiler correctly shows the error, I remove the offending code, then it recompiles but still shows the  error!

If I stop and restart  '**ng serve**' then it recompiles with no errors!

**Angular CLI**: 11.0.2
**Node**: 14.4.0

**Package**                                  **Version**
---------------------------------------------------------
@angular-devkit/architect           0.1100.2
@angular-devkit/build-angular   0.1100.2
@angular-devkit/core                   11.0.2
@angular-devkit/schematics       11.0.2
@angular/cdk                                11.0.1
@angular/material                         11.0.1
@schematics/angular                   11.0.2
@schematics/update                    0.1100.2

**OS:** MacOs Big Sur V11.01

Only happened since the upgrade to **Angular 11**
Happens on all browsers

This appears to be a similar issue to  [https://github.com/angular/angular-cli/issues/5404] (issue 5404 closed)

**Comment by spock123** [comment] 2020-11-29 11:06
Yes have been having this happen a lot after upgrading to ng11

**Comment by bobskigit** [comment] 2020-11-29 16:44
Same problem, in all my Angular 11 projects it only seems to happen for HTML templates , ts and scss file updates trigger recompile successfully.

**Comment by rekna1** [comment] 2020-11-29 18:07
I have the same problem with Angular 10 & ng build --watch:
some error in html template, compiler show suddenly lengthy errors (part of compiler errors down below)
correct html error , but compilation still fails
**restart build --watch and all errors are gone**

`
  
    ERROR in src/app/______________/___________/_______-__-_________.module.ts:68:5 - error NG6001: The class '________________Component' is listed in the declarations of the NgModule '__________________Module', but is not a directive, a component, or a pipe. Either remove it from the NgModule's declarations, or add an appropriate Angular decorator.
    
    68     ________________Component],
           ~~~~~~~~~~~~~~~~~~~~~~~~~
    
      src/app/______________/___________/______-__________/______-__________.component.ts:43:14
        43 export class ________________Component implements OnInit {
                        ~~~~~~~~~~~~~~~~~~~~~~~~~
        '___________Component' is declared here.
    src/app/______________/___________/______-__________/______-__________.component.html:18:44 - error NG8002: Can't bind to 'ngModel' since it isn't a known property of 'div'.
    
    18       <div class="btn-group" btnRadioGroup [(ngModel)]="vm._______________" name="_______________">
                                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    
      src/app/______________/___________/______-__________/______-__________.component.ts:39:16
        39   templateUrl: './______-__________._________.html',
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        Error occurs in the template of component ________________Component.
    src/app/______________/___________/______-__________/______-__________.component.html:20:82 - error NG8002: Can't bind to 'btnRadio' since it isn't a known property of 'label'.
    
    20           *ngFor="let waarde of vm.________________" class="btn btn-info btn-sm" [btnRadio]="______" btnRadio="Left"
                                                                                        ~~~~~~~~~~~~~~~~~~~
    
      src/app/______________/___________/______-__________/______-__________.component.ts:39:16

.......
`

**Comment by alan-agius4** [comment] 2020-11-30 10:00
Duplicate of #39147

**Closed by alan-agius4** 2020-11-30 10:00 UTC
