### ISSUE TITLE
Need Simplified Explanation  | Services and Dependency Injection | Explanation

### ISSUE THREAD

**Issue by ChaitanyaBabar** [angular/angular#54880] opened 2024-03-15 14:57 UTC
### Describe the problem that you experienced

I guess below related to documentation of  **Services and dependency injection**, can be more simplified, to avoid confusion.

**Currently Docs Says as Follows** :- 

> Dependency injection (DI) lets you keep your component classes lean and efficient. They **don't** fetch data from the server, validate user input, or log directly to the console; they delegate such tasks to services.

**It Should Have Been** :- 

> Dependency injection (DI) lets you keep your component classes lean and efficient. They delegate tasks like fetching data from the server, validating user input, or log directly to the console to services.

### Enter the URL of the topic with the problem

https://angular.io/guide/architecture#services-and-dependency-injection

### Services and dependency injection

I was having quick look at brief Introduction to Angular Concepts, and I got confused by below wording, 

> Dependency injection (DI) lets you keep your component classes lean and efficient. They **don't** fetch data from the server, validate user input, or log directly to the console; they delegate such tasks to services.

(i.e. especially " **don't** fetch data from the server,")

Since I have been working on angular for quite a long , I got the gist of it but I still feel it can be put in more simpler words to
avoid confusion for new bees.

### Add a screenshot if that helps illustrate the problem

![image](https://github.com/angular/angular/assets/6712223/a806f5cd-2123-4d71-9306-48836ae3224f)

**Comment by JeanMeche** [comment] 2024-03-15 16:10
Hi, angular.io in now in maintenance mode and won't recieve major content updates. 
Can you have a look at the new doc site https://angular.dev and tell us if the docs are seem more correct to you ? Thank you.

**Comment by twerske** [comment] 2024-03-27 19:35
Closing as this is not a part of adev and AIO is being removed! Please reopen against Angular.dev if you feel the issue is present there too!

**Closed by twerske** 2024-03-27 19:35 UTC
Labels: area: docs
