### ISSUE TITLE
control flow migration left behind a #named ng-template

### ISSUE THREAD

**Issue by rtpHarry** [angular/angular#58850] opened 2024-11-24 06:45 UTC
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

This was mentioned and claimed to be fixed in https://github.com/angular/angular/issues/52518 but it seems to have happened to me the other month.

I've just spotted it now when I was confused why there was two blocks.

I'm not a massive expert so I can't really share much more than what my experience was. I was updating a very old app, so i went through all the versions of angular and ionic one by one to bring it up to date.

At some point when I ran the control flow schematic it turned this:

```html
<ion-header [translucent]="true">
  <ion-toolbar>
    <ion-avatar slot="start" class="logo">
      <img [src]="'/assets/images/app-logo.svg'" />
    </ion-avatar>
    <ion-title class="logo">
      <ion-label>The Weighter</ion-label>
    </ion-title>
    <app-user-account-info slot="end"></app-user-account-info>
    <ion-buttons slot="end">
      <ion-menu-button></ion-menu-button>
    </ion-buttons>
  </ion-toolbar>
</ion-header>

<ion-content [fullscreen]="true">
  <ng-container *ngIf="user$ | async as user; else login">
    <ion-grid fixed>
      <ion-row>
        <ion-col size="12" size-md="6">
          <div class="intro-container ion-margin">
            <div class="app-logo-header">
              <app-logo-heading></app-logo-heading>
            </div>
            <div class="app-invocation">
              <app-invocation (addWeightClick)="addWeight()"></app-invocation>
            </div>
            <div
              class="weight-graph-container"
              *ngIf="weights$ | async as weights"
            >
              <div class="ion-margin-vertical" *ngIf="weights?.length">
                <app-weight-graph [weights]="weights"></app-weight-graph>
              </div>
            </div>
          </div>
        </ion-col>
        <ion-col size="12" size-md="6">
          <div class="weight-container" *ngIf="weights$ | async as weights">
            <div
              class="weight-container-inner ion-margin-vertical ion-text-center"
            >
              <app-weight-list
                [weights]="weights"
                [allTimeLowRecord]="user.allTimeLowRecord"
              ></app-weight-list>
            </div>
          </div>
        </ion-col>
      </ion-row>
    </ion-grid>
  </ng-container>
  <ng-template #login>
    <div class="login-container ion-text-center">
      <div class="ion-margin-vertical">
        <app-logo-heading></app-logo-heading>
        <app-login></app-login>
      </div>
    </div>
  </ng-template>
</ion-content>
```

into this:

```html
<ion-header [translucent]="true">
  <ion-toolbar>
    <ion-avatar slot="start" class="logo">
      <img [src]="'/assets/images/app-logo.svg'" />
    </ion-avatar>
    <ion-title class="logo">
      <ion-label>The Weighter</ion-label>
    </ion-title>
    <app-user-account-info slot="end"></app-user-account-info>
    <ion-buttons slot="end">
      <ion-menu-button></ion-menu-button>
    </ion-buttons>
  </ion-toolbar>
</ion-header>

<ion-content [fullscreen]="true">
  @if (user$ | async; as user) {
  <ion-grid fixed>
    <ion-row>
      <ion-col size="12" size-md="6">
        <div class="intro-container ion-margin">
          <div class="app-logo-header">
            <app-logo-heading></app-logo-heading>
          </div>
          <div class="app-invocation">
            <app-invocation (addWeightClick)="addWeight()"></app-invocation>
          </div>
          @if (weights$ | async; as weights) {
          <div class="weight-graph-container">
            @if (weights?.length) {
            <div class="ion-margin-vertical">
              <app-weight-graph [weights]="weights"></app-weight-graph>
            </div>
            }
          </div>
          }
        </div>
      </ion-col>
      <ion-col size="12" size-md="6">
        @if (weights$ | async; as weights) {
        <div class="weight-container">
          <div
            class="weight-container-inner ion-margin-vertical ion-text-center"
          >
            <app-weight-list
              [weights]="weights"
              [allTimeLowRecord]="user.allTimeLowRecord"
            ></app-weight-list>
          </div>
        </div>
        }
      </ion-col>
    </ion-row>
  </ion-grid>
  } @else {
  <div class="login-container ion-text-center">
    <div class="ion-margin-vertical">
      <app-logo-heading></app-logo-heading>
      <app-login></app-login>
    </div>
  </div>
  }
  <ng-template #login>
    <div class="login-container ion-text-center">
      <div class="ion-margin-vertical">
        <app-logo-heading></app-logo-heading>
        <app-login></app-login>
      </div>
    </div>
  </ng-template>
</ion-content>
```

So it left the `ng-template` behind at the end of the snippet, despite correctly duplicating it into the new control-flow structure.

There is no other mention of it in the code class, so it wasn't triggered to be left behind due to a viewchild reference.

I've pasted in `ng version` as it stands today but I'm not sure what it was when I ran the migration last month.

Hopefully this is enough to help you figure out the bug.

### Please provide the exception or error you saw

```true

```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 18.2.9
Node: 20.12.1
Package Manager: npm 10.8.3
OS: darwin x64

Angular: 18.2.8
... common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1802.9
@angular-devkit/build-angular   18.2.9
@angular-devkit/core            18.2.9
@angular-devkit/schematics      18.2.9
@angular/cli                    18.2.9
@angular/fire                   18.0.1
@schematics/angular             18.2.9
rxjs                            7.8.1
typescript                      5.4.5
zone.js                         0.14.10
```

**Comment by JoostK** [comment] 2024-11-24 07:02
This seems like a duplicate of #55985.

**Closed** 2024-11-24 07:32 UTC
