### ISSUE TITLE
Use `fixture.componentRef.setInput('input1', input1)` not works doing Unit Test

### ISSUE THREAD

**Issue by oidacra** [angular/angular#54062] opened 2024-01-24 23:30 UTC
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

I have a 
```
Error: NG0303: Can't set value of the 'input1' input on the 'ChildComponent' component. Make sure that the 'input1' property is annotated with @Input() or a mapped @Input('input1') exists.
```

When I do a Unit test with input signals.

### Please provide a link to a minimal reproduction of the bug

https://github.com/oidacra/unit-test-input-signals/tree/main

### Please provide the exception or error you saw

```true
When I try use `fixture.componentRef.setInput('input1', input1)`
And show a `Error: NG0303: Can't set value of the 'input1' input on the 'ChildComponent' component. Make sure that the 'input1' property is annotated with @Input() or a mapped @Input('input1') exists`
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.1.1
Node: 18.18.2
Package Manager: yarn 1.22.19
OS: darwin arm64

Angular: 17.1.1
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1701.1
@angular-devkit/build-angular   17.1.1
@angular-devkit/core            17.1.1
@angular-devkit/schematics      17.1.1
@schematics/angular             17.1.1
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.3
```

### Anything else?

Get ` NG0303: Can't bind to 'input1' since it isn't a known property of 'unit-test-child' (used in the 'AppComponent' component template).` too when you try a use the child component inside the parent
```
 app.component.html
<unit-test-child [input1]="input1" [input2]="input2"></unit-test-child>
```

Running works all perfectly. The problem is doing Unit Test.

**Comment by JeanMeche** [comment] 2024-01-24 23:39
This is due to Jest, I'm closing this as a dupe of #54013

**Closed by JeanMeche** 2024-01-24 23:39 UTC
Labels: area: testing

**Comment by oidacra** [comment] 2024-01-24 23:59
Interesting, thanks.
