### ISSUE TITLE
await / async (props) of Observables | Promises etc

### ISSUE THREAD

**Issue by muhamedkarajic** [angular/angular#46948] opened 2022-07-23 01:15 UTC
### Description

Angular allows us to use async pipe but when using multiple streams there isn't really a great way to ngIf them. 

Imagine the scenario I have observables a$ and b$ and I want to wait for both of them. Of course I could make another observable in my TS file and combineLatest them but this means I would need to that for every scenario in my HTML and it dosent make much sence to combine them in the TS if all I want is to display a loading animation.

I went trough a few possible solutions and think this could be a standard Angular feature. I'm open for discussions and suggestions but as far as the testing / working of the idea goes it seems to work fine. 

### Proposed solution

I propose we have a similar async pipe but it would work only for keys of observables, this way you can keep your HTML clean and robust. The following code will recreate an object based on the current one but with the catch that it will map all observables to another object with the returned values from the stream.

```typescript
<ng-container *ngIf="{ myData$, selectedItems$, myPromise$ } | await as props; else loading">
  <my-multi-selector
    [selectedItems]="props.selectedItems$.value"
    [data]="props.myData$.value"></my-multi-selector>
</ng-container>

<ng-template #loading>
  <div>Loading...</div>
</ng-template>
```

### Alternatives considered

Regarding the implementation I made a sample app which I tested and it seems to work fine. There is a catch to my code and that is that I catch the object and compare references - this is completely fine if you use the code as above written but there is an issue if you e.g. create your object in TS and then dynamically change the keys (adding / removing keys will cause issues without creating a new instance of the object itself).

This can be avoided by removing the comparison of the references of the new and old object but since this isn't a pure pipe I considered the performance impact and since this would be used only in HTML anyway I think this is the best possible solution - again I'm open for discussion.

Link of example: https://github.com/muhamedkarajic/angular-playground/blob/main/apps/playground/src/app/shared/pipes/await.pipe.ts

**Comment by spock123** [comment] 2022-08-01 08:24
Yes this is a scenario we all are familiar with: waiting for a number of observables to resolve. Nesting ng-containers quickly becomes quite messy when you are dealing with 4+ observables.

**Comment by dario-piotrowicz** [comment] 2022-08-06 10:48
Yeah this is quite a common scenario, having a built-in way to handle it would be nice :slightly_smiling_face:

But regarding the proposed solution I am curious, would the `await` pipe have any practical use outside the use case described? Because the `async` pipe is generic and usable in various different scenarios, I think that if the `await` pipe would only serve this single purpose that it should probably not be a generic pipe, maybe a new structural directive would be more appropriate instead?

**Comment by mlc-mlapis** [comment] 2022-08-06 10:58
A similar syntax could be used then, as with RxJS operators, i.e., `*ngIf="{ myData$, selectedItems$, myPromise$ } | combineLatest as props; else loading"`. 😄

**Comment by muhamedkarajic** [comment] 2022-08-09 22:39
> A similar syntax could be used then, as with RxJS operators, i.e., `*ngIf="{ myData$, selectedItems$, myPromise$ } | combineLatest as props; else loading"`. 😄

I have looked into that point of view already this is resonable name but I wanted to point out that this isn't like combineLatest. I have optimized the pipe for Angulars CLI and it's an object which contains observables. Also if we call it combineLatest and this becomes a angular feature it will be hard to find blog posts etc about it cause other websites have the terms pipe + combineLatest.

**Comment by muhamedkarajic** [comment] 2022-08-09 22:47
> Yeah this is quite a common scenario, having a built-in way to handle it would be nice 🙂
> 
> But regarding the proposed solution I am curious, would the `await` pipe have any practical use outside the use case described? Because the `async` pipe is generic and usable in various different scenarios, I think that if the `await` pipe would only serve this single purpose that it should probably not be a generic pipe, maybe a new structural directive would be more appropriate instead?

I don't want to introduce a new ngIf I just want to await my observables. Somestimes if I have multiple components inside 1 view I want the properties to extract per component and then to foward them. 

If you have observable a$ and b$ and you await them you have multiple issues, there is a workaround but then you have to use 2 ngIfs to do it properly like:

```typescript
<ng-container *ngIf="{ a: a$ | async, b: b$ | async} as props">
    <ng-container *ngIf="props.a && props.b"
//Pass them to your component
```

I don't see a reason why to introduce a new directive the pipe works fine and it will be more performante then the async pipe or better said then multiple async pipes.

**Comment by pkozlowski-opensource** [comment] 2022-08-17 07:25
I believe that this issue is a duplicate of #15280 - while it suggest a different approach the underlying problem is the same: consuming observables in templates is not ideal and ergonomics of the `async` pipe could be improved.

**Comment by muhamedkarajic** [comment] 2022-08-21 00:35
> I believe that this issue is a duplicate of #15280 - while it suggest a different approach the underlying problem is the same: consuming observables in templates is not ideal and ergonomics of the `async` pipe could be improved.

Sorry but if you really think this is a duplicate you didn't have had a proper look at my code. It unpacks multiple observables and combines them as one stream, which is mainly wanted behavior when you have lots of observbales.

How do you expect that to work with async which returns null instantly and then awaits the observbale to start passing data. 

I have looked into the async pipe and its not extendable cause my syntax in HTML requires you to create an object {a$, b$, c$} the async pipe bahavior would return {a$: null, b$: null, c$: null} and you can't just make it behave differently cause the type my 'await' pipe returns and the type whcih async pipe returns is completly different - unless you can somehow manage to make that in typescript or using the angular CLI.

**Comment by hakimio** [comment] 2022-09-21 20:28
@muhamedkarajic try [*ngrxLet](https://ngrx.io/guide/component/let). It doesn't have the problems you described.

**Comment by muhamedkarajic** [comment] 2022-11-15 04:08
> @muhamedkarajic try [*ngrxLet](https://ngrx.io/guide/component/let). It doesn't have the problems you described.

I apprichiate the suggestion, however this is a proposal to add an additional pipe beside 'async'. The solution which the ngrx team came about is to have a new directive and I kind of personally am very against it. Having multiple 'if' directives is kind of a bit much. 

I think having an additional pipe which you can use and will solve the problems is a far better choice.

**Comment by muhamedkarajic** [comment] 2022-12-23 10:09
Any updates on this topic?

**Comment by Michael-Ziluck** [comment] 2023-09-28 19:03
@muhamedkarajic 
> There is also a workaround that you can inside your typescript introduce a variable which combineLatests all, in that case the async pipe would work fine with ngIf. However I don't like the solution to add everytime a prop$ to my ts file and if I have different scenarios its not going to make my life easier, handeling multiple ngIfs is also tedious.

I wouldn't necessarily call this a "workaround". To recap, you have three Observables and you want to wait for all of them to complete and then emit them together as a map, correct? Angular is very strongly integrated around using RxJS and their official guidance is typically to just use a built-in RxJS operator. There's no reason for the already very busy Angular team to implement a brand new pipe simply because you don't feel like adding a single line of code...

Also per what you said about the `AsyncPipe` not being easily adaptable, that is definitely incorrect. All you'd need to do is change the `transform` input parameter type to be `Record<string, Observable<T>|Subscribable<T>|Promise<T>>` and then in there add the `combineLatest` call right before the call to `this._subscribe(obj)`;

This definitely does not seem like something that needs to be added. Anything solvable by a design change or a single line of code is never going to be prioritized. Here's the code in case you wanted to try it out:

```typescript
ngOnInit(): void {
  this.props$ = combineLatest({
    myData$,
    selectedItems$
    myPromise$
  });
}
```

Based on your example, in your template you'd then have:
```html
<ng-container *ngIf="props$ | async as props; else loading">
  <my-multi-selector
    [selectedItems]="props.selectedItems$.value"
    [data]="props.myData$.value"></my-multi-selector>
</ng-container>

<ng-template #loading>
  <div>Loading...</div>
</ng-template>
```

There's no need to have the Angular team create a brand new pipe for your fairly niche use-case that can be solved with one line of code.

**Comment by muhamedkarajic** [comment] 2023-10-10 22:08
> There's no need to have the Angular team create a brand new pipe for your fairly niche use-case that can be solved with one line of code.

I think the HTML can do better. Responsibility of how to handle Observables as well as Signals is a responsibility of the ngIf beside combining streams isnt what you always want and denepding on how complex it is you have to add more and more things.

I think Angular should target to make things better, efficient and dev friendly.

**Comment by alxhub** [comment] 2023-12-15 16:53
I'm going to close this issue as a duplicate of #15280 - fundamentally this is asking for template local variables (as evidenced by the suggestions of `*ngrxLet` above.

**Closed by alxhub** 2023-12-15 16:53 UTC
Labels: area: core, cross-cutting: observables, P3
