### ISSUE TITLE
ngClass from component method restores original classes

### ISSUE THREAD

**Issue by clabough** [angular/angular#29739] opened 2019-04-06 00:34 UTC
# 🐞 bug report

### Description

I'm using Bootstrap tabs and ngClass to append additional classes. I found that when using a component method for ngClass that it seems the original classes are getting restored when a component within the tab container changes.

This does not happen when using an object directly within ngClass or by using [class.] syntax.

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-bypyy7

Notice that the 'active' class gets restored in the first example in the project, but not the others.

## 🌍  Your Environment

**Angular Version:**
<pre><code>
    "@angular/common": "^7.2.5",
    "@angular/compiler": "^7.2.5",
    "@angular/core": "^7.2.5",
    "@angular/forms": "^7.2.5",
    "@angular/platform-browser": "^7.2.5",
    "@angular/platform-browser-dynamic": "^7.2.5",
    "@angular/router": "^7.2.5",
    "core-js": "^2.6.5",
    "rxjs": "^6.4.0",
    "zone.js": "^0.8.29"

</code></pre>

**Comment by pkozlowski-opensource** [comment] 2019-04-06 08:05
This is a duplicate of an existing issue #25518

Side note - you are bumping into those problems since mixing Bootstrap JS and Angular like this results in 2 sources of DOM manipulation (Bootstrap's JS and Angular) and it is _really_ easy to get into a situation where both "fight" for the control over DOM. I would suggest looking into https://ng-bootstrap.github.io (or similar libraries) that add Bootstrap support to Angular applications.

Anyway, closing as a duplicate of  #25518

**Closed by pkozlowski-opensource** 2019-04-06 08:05 UTC
