### ISSUE TITLE
Host directive input mapping not working in test environment

### ISSUE THREAD

**Issue by jonathanwilke** [angular/angular#51118] opened 2023-07-20 06:58 UTC
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

We have the following component in our component library: 

```typescript
@Component({
  selector: 'button[edsUserMenuTrigger]',
  standalone: true,
  imports: [SlicePipe, NgIf, NgClass, MatIconModule, LetDirective],
  templateUrl: './user-menu-trigger.component.html',
  hostDirectives: [
    {
      directive: CdkMenuTrigger,
      inputs: ['cdkMenuTriggerFor:forMenu'],
    },
  ],
})
```

This is how we use it in our application:

```html
<button edsUserMenuTrigger [forMenu]="menu"></button>
<ng-template #menu>
  ...
</ng-template>
```

In the application it works totally fine.

The unit tests for the component that uses this look like this: 

```typescript
describe('UserMenuComponent', () => {
  let spectator: Spectator<UserMenuComponent>;
  let component: UserMenuComponent;

  const createComponent = createComponentFactory({
    imports: [],
    component: UserMenuComponent,
  });
  beforeEach(() => {
    spectator = createComponent();
    component = spectator.component;
  });
  it('should be created', () => {
    expect(component).toBeTruthy();
  });
});
```

Starting the unit tests always throws the following error immediately:

<img width="827" alt="Bildschirmfoto 2023-07-20 um 08 57 55" src="https://github.com/angular/angular/assets/1453455/190c1edc-86e1-46f1-93dd-64406472834a">

Any idea what could be the cause or how to fix this?

**Comment by JoostK** [comment] 2023-07-20 07:40
This seems like a distinction between JIT and AOT at first glance, although I haven't looked too deeply into it since there isn't a runnable reproduction.

**Comment by JeanMeche** [comment] 2023-07-20 08:34
I could not reproduce this issue with your code. You can fork this stackblitz : https://stackblitz.com/edit/angular-16-jest-preset-vcpoug?file=package.json,src%2Fapp%2Fapp.component.spec.ts to help us investigate. 

Also which version of Angular are you running ?

**Comment by JeanMeche** [comment] 2023-09-16 19:32
Without a repro this isn't actionable so I'll close this.

Feel free to reopen if you are able to provide a repro 👍

**Closed by JeanMeche** 2023-09-16 19:32 UTC
Labels: area: testing, needs reproduction, area: core, core: host directives
