### ISSUE TITLE
docs: QuickStart Tutorial out of sync

### ISSUE THREAD

**Issue by fwd079** [angular/angular#17720] opened 2017-06-23 06:18 UTC
## I'm submitting a ...

<pre><code>
[*] Regression (behavior that used to work and stopped working in a new release)
[ ] Bug report 
[ ] Feature request
[*] Documentation issue or request 
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Before angular-cli the tutorial was in sync, but it is not in sync with angular-cli.

## Expected behavior

I walked through the tutorial a few months ago and it went fine. Life got in the way and now I am back learning angular from scratch. 
This time set-up section walked me through creating an Angular app via cli to create a blank app. I walked through tutorial with that blank app, it worked fine. But on [HTTP Section](https://angular.io/tutorial/toh-pt6) the walkthrough broke a bit.

## Minimal reproduction of the problem with instructions
Create new app via ng `new angular-tour-of-heroes`

## What is the motivation / use case for changing the behavior?
Anyone creating app via angular-cli will be strongly discouraged, it took me two days to even get back to Angular after facing this issue. I tried similar thing [here](https://github.com/angular/in-memory-web-api/issues/118) so please see if it is related.

## Please tell us about your environment
N / A

Thanks for reading and looking into it.

**Comment by Toxicable** [comment] 2017-06-23 06:57
Im confused, what is the actual issue here?
Recent a new version of angular.io was released and with it a lot of the docs have been updated to use the CLI.
Your reproduction says 
>Create new app via ng new angular-tour-of-heroes

But doing this dosen't produce any errors

**Comment by Foxandxss** [comment] 2017-06-23 09:45
The tutorial is meant to be used with the the [quickstart](https://github.com/angular/quickstart) repo and not the CLI.

I haven't try it yet with the CLI. I don't think it should fail, it is just that some steps are different.

**Comment by fwd079** [comment] 2017-06-23 12:35
@Foxandxss Yes, I know that as mentioned in opening post:

> #Expected behavior
> 
> I walked through the tutorial a few months ago and it went fine. Life got in the way and now I am back learning angular from scratch.
> This time set-up section walked me through creating an Angular app via cli to create a blank app. I walked through tutorial with that blank app, it worked fine. But on HTTP Section the walkthrough broke a bit.

So yes, I created It doesn't fail till HTTP section, as I said. But since HTTP section uses the api I linked in opening post, that fails. However this morning I git cloned to above web-api simulator in the app folder created via cli. And then removed
`import { InMemoryWebApiModule } from 'angular-in-memory-web-api';`
with
`import { InMemoryWebApiModule } from 'in-memory-web-api';`
and everything seemingly is working.

Will check your created project as well. Thank you :)

**Comment by codepj** [comment] 2017-07-06 22:46
You can make it though fine but I did run into three things while using `ng new` and skipping the quick start setup:

1. `ng new` has the main app.component selector set to "app-root" instead of "my-app".  
2. Part 6 tells you to add `style.css` to index.html when the cli handles that for you.  Adding it will lead to a 404 in the console due to routing.
3. Part 7 makes use of `angular-in-memory-web-api` but you are never told to install it.

**Comment by kapunahelewong** [comment] 2018-01-04 22:17
@fwd079 Since you filed this issue, the doc has been changed to use the CLI, which should mitigate the above issues. I'll close this issue, but if you have outstanding issues, please let me know.

**Closed by kapunahelewong** 2018-01-04 22:17 UTC
Labels: comp: docs, effort2: medium (days), freq3: high, severity1: confusing

**Comment by fwd079** [comment] 2018-01-05 19:08
Cool mate, cheers.
