### ISSUE TITLE
Error message is lacking in details:  Supplied parameters do not match any signature of call target

### ISSUE THREAD

**Issue by xnnkmd** [angular/angular#15663] opened 2017-03-31 12:06 UTC
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I have an angular 2 app that gives a number of errors like the one below when the app is build using angular cli 1.0

ERROR in C:/Source/xxx/MemberUI/src/$$_gendir/app/journal/journal-component.ngfactory.ts (232,79): Supplied parameters do not match any signature of call target.

Unfortunately, this is to little information for me to fix the bug and I am unable to see the generated ngfactory file to learn more.

* **Angular version:** 2.4.10

(unfortunately, the app does not work yet with 4.0.1)
 
* **Language:** TS 2.1.5

* **Node (for AoT issues):** `node --version` =   
7.7.1

**Comment by DzmitryShylovich** [comment] 2017-03-31 12:18
@xnnkmd it's a cli issue. see https://github.com/angular/angular-cli/issues/5619

**Comment by pkozlowski-opensource** [comment] 2017-03-31 18:13
Closing as a duplicate of angular/angular-cli#5619. Thnx @DzmitryShylovich

**Closed by pkozlowski-opensource** 2017-03-31 18:13 UTC
