### ISSUE TITLE
Expose more events from service worker update cycle

### ISSUE THREAD

**Issue by marcinowski** [angular/angular#39840] opened 2020-11-25 11:26 UTC
# 🚀 feature request

### Relevant Package
This feature request is for @angular/service-worker

### Description
We are currently experiencing an issue with a significant percentage of our users using outdated versions of our application. We're not really sure whether they're taking a very long time to update their applications or is it more of a problem with detection of the new version or something else. We don't have enough data to determine whether there is an issue with our service worker implementation, an issue with our application or maybe some edge case in the framework. [Currently](https://angular.io/guide/service-worker-communications) the service worker exposes only the `available` and `activated` events. This gives only a bit of an insight on how does the service worker perform updates on the client side. 

### Describe the solution you'd like
As mentioned before the service worker currently exposes only two events
 - a new version is available to be activated
 - a new version has been activated

Ideally the service would expose some additional events like
 - a new version has been detected to exist (but is not available to use yet)
 - a new version starts downloading
 - a new version finishes downloading

This would allow us to track those events, figure out why is it that some users are taking very long time to get the new version and/or maybe optimise some parts of the flow.

##
_**EDIT(gkalpak)**_
_Related issue: #34397_

**Comment by gkalpak** [comment] 2020-11-25 13:35
This sounds reasonable. The current update notification workflow is indeed less than ideal.

##
FWIW, you can have a little more control by calling [SwUpdate#checkForUpdate()][1] explicitly (instead of relying on the SW to check for updates automatically). While `checkForUpdate()` does not report whether an update was found or not (this is another area we can improve) it allows you to know when a check happened.

Then by subscribing to `SwUpdate#available` you can know whether a new version has been detected. If a new version is detected, it will be downloaded and emitted on `SwUpdate#available` before the promise returned by `checkForUpdate()` resolves. So, that could be used to emulate your "a new version finishes downloading" event.

If the promise returned by `checkForUpdate()` resolves without a value being emitted on `SwUpdate#available`, this can mean two things:
1. There is no update available.
2. There was an error while checking or downloading the update.

There is no straight-forward way to distinguish the two, but if an error occurred the SW would have entered a degraded mode. So, you can determine what happened by requesting `ngsw/state` parsing it manually for the SW state with somthing like:

```js
fetch('ngsw/state').
  then(res => res.text()).
  then(res => /Driver state: (\w+)/.exec(res)[1])
```

You can read more about the available debug options [here][2].

---
I am going to leave it open as a feature request, but it is not a high priority. If anyone wants to take it on, I would be happy to help/review.

[1]: https://angular.io/api/service-worker/SwUpdate#checkForUpdate
[2]: https://angular.io/guide/service-worker-devops#locating-and-analyzing-debugging-information

**Comment by marcinowski** [comment] 2020-11-25 14:26
Thanks for a very helpful comment @gkalpak. What you're saying makes a lot of sense and it's definitely something that we're going to try. I'm also glad you find the feature request reasonable, I'll try to find some time and produce a PR

**Comment by TheParad0X** [comment] 2021-01-18 19:40
Hello,

I was asked to post my ideas here :)

This feature request is for @angular/service-worker

The current API is not very user-friendly. **So far, in order to check for updates, I have to do the following:**

- Call checkForUpdate() every N minutes. When it returns, **I don't know if the check was successful and if there is an update**
- I have to subscribe to SwUpdate.available(), and I can act accordingly, for example prompt the user
- SwUpdate.available() **seems to fire only once**, I need to save (or remember) that an UpdateAvailableEvent is available (if the user clicks "No" in my "Would-you-like-to-reload-prompt". Also, SwUpdate.available() seems to be firing twice in a row from time to time, I have not been able to reproduce it consistently.
- SwUpdate.activateUpdate() also does not give my anything useful in return.

**How I would like the API to be:**
- checkForUpdate() returns Observable<UpdateAvailableEvent> if there is an update, or undefined if not. And an error if the check failed (no connection?)
- activateUpdate() returns Observable<boolean> with true if it was successful, or false if not
- available() would not be needed anymore

Does this make sense?

Cheers

**Comment by spike-rabbit** [comment] 2021-07-23 13:55
@gkalpak Is it possible to provide a PR although the Issue got insufficient votes? 
I am interested in `a new version has been detected to exist (but is not available to use yet)` event, but I can do some of the other stuff as well.

If your answer is yes, do you have a suggestion for the API or should I provide an Idea?

**Comment by gkalpak** [comment] 2021-07-23 17:22
While this got insufficient votes, I do believe it is a useful addition (esp. since the current implementation is a little unintuitive).
We'll discuss this with the team and decide if there is still merit in moving it forward (although I don't have a timeline - there are dozens of issues to go through 😅).

I don't have any concrete API suggestions, but feel free to go ahead a make one (and provide a PR) :wink:

**Comment by spike-rabbit** [comment] 2021-08-16 13:24
Sorry for my long response time. Here is my suggestion for the API modifications:

I would add a new field to NgUpdate: 

`potentialUpdateAvailalbe: Observable<PotentialUpdateAvailableEvent>` .

This should meet the `a new version has been detected to exist (but is not available to use yet)` and `a new version starts downloading` event. At least for me it looks there is no need to differentiate as downloading starts immediately after the potential update was detected.

Same is for `a new version finishes downloading` which is basically the same as `a new version is available to be activated`.

**Regarding @TheParad0X  comment:**

I guess sticking to Promises is fine here as Observables would require a call to `.subscribe()`. But I can agree on adding a meaningful return value. I would prefer a signature like this:
`checkForUpdate(): Promise<UpdateAvailableEvent | NoUpdateAvailableEvent  | UpdateFailedEvent>`. Throwing an error in case of failure would force applications to catch it which would be definitely a breaking change.

And for `activateUpdate` it could look like this: `activateUpdate(): Promise<UpdateActivatedEvent | ActivationFailedEvent>`.

TBH I am not sure if returning the events is the best way here. If an error is thrown in case of failure, returning a `boolean` value would be possible as well.

@gkalpak WDYT?

**Comment by gkalpak** [comment] 2021-08-18 14:21
Thx for putting this together, @spike-rabbit.

##
I took some time to (briefly) think about the API today, so here are my thoughts.

First of all, as a point of reference, here is what the `SwUpdate` public API looks like today:

```ts
class SwUpdate {
  available: Observable<UpdateAvailableEvent>;
  activated: Observable<UpdateActivatedEvent>;
  unrecoverable: Observable<UnrecoverableStateEvent>;
  isEnabled: boolean;
  checkForUpdate(): Promise<void>;
  activateUpdate(): Promise<void>;
}
```

> NOTE:
> One limitation of the mechanism currently used under the hood to communicate between the Angular SW and the app is that it only reports whether an operation has been completed, without a way to convey the result of the operation (such as whether checking for an update yielded an update or not).
> I think we should enhance that mechanism to be able to report richer information about an operation.

Trying to stay as backwards compatible as possible, I might propose the following changes to the `SwUpdate` public API (off the top of my head - this is not really thought through). These are similar to your suggestions, @spike-rabbit, just a little more concrete (and a little more backwards compatible).

- Keep `isEnabled` and `unrecoverable` as is.
- Update `checkForUpdate()` to return a promise resolving to `true`/`false` on successful completion (indicating whether an update was found (and successfully downloaded) or not) and rejecting on failure.
  I.e. resolving to `true` means an update was found and downloaded and is ready to use, resolving to `false` means no update was found and rejecting means an error happened while either checking for an update or downloading it.
- Update `activateUpdate()` to return a promise resolving to `true`/`false` on successful completion (indicating whether an update was activated or not (because the client was already on the latest version)) and rejecting on failure.
- Introduce a new `versionUpdates` observable (name TBD :grin:) that emits the following types of events:
  - `VersionDetectedEvent` (implies that a new version is detected on the server and is being downloaded):
    ```ts
    {
      type: 'VERSION_DETECTED';
      version: {
        hash: string;
        appData?: object;
      };
    }
    ```
  - `VersionInstallationFailedEvent` (implies that there was an error preparing the version (i.e. downloading or updating local SW state)):
    ```ts
    {
      type: 'VERSION_INSTALLATION_FAILED';
      version: {
        hash: string;
        appData?: object;
      };
      error: string;
    }
    ```
  - `VersionReadyEvent` (implies that a new version has been installed and is ready to be activated for the client):
    ```ts
    {
      type: 'VERSION_READY';
      currentVersion: {
        hash: string;
        appData?: object;
      };
      latestVersion: {
        hash: string;
        appData?: object;
      };
    }
    ```
  > Not a big fan of the name, but `VersionAvailableEvent` sounded confusingly similar to `VersionDetectedEvent` (i.e. people might easily interpret it as "a new version is available on the server") and `VersionInstalledEvent` could be easily interpreted as "the version has been activated and is in effect for this client").
- Consider deprecating (and eventually removing) the `available` observable, since it could now be constructed from `versionUpdates`. For example:
  ```ts
  available = swUpdate.versionUpdates.pipe(
    filter(evt => evt.type === 'VERSION_READY'),
    map(evt => ({
      type: 'UPDATE_AVAILABLE',
      current: evt.currentVersion,
      available: evt.latestVersion,
    })),
  );
  ```
- Consider deprecating (and eventually removing) the `activated` observable, since (in practice) it only really emits in response to calling `activateUpdate()`.

With that, the `SwUpdate` public API surface would look like:

```ts
class SwUpdate {
  /** @deprecated */
  available: Observable<UpdateAvailableEvent>;
  /** @deprecated */
  activated: Observable<UpdateActivatedEvent>;
  versionUpdates: Observable<VersionDetectedEvent | VersionInstallationFailedEvent | VersionReadyEvent>;
  unrecoverable: Observable<UnrecoverableStateEvent>;
  isEnabled: boolean;
  checkForUpdate(): Promise<boolean>;
  activateUpdate(): Promise<boolean>;
}
```

**Comment by gkalpak** [comment] 2021-08-30 21:41
I certainly won't get to it any time soon, so feel free to submit a PR :wink:
I'll be happy to review and help with questions.

**Closed** 2021-10-05 18:00 UTC
Labels: feature, comp: service-worker, insufficient votes, under consideration, in backlog, votes required
