### ISSUE TITLE
Add extended diagnostic to warn when an attribute is not interpreted as a binding

### ISSUE THREAD

**Issue by antch** [angular/angular#46137] opened 2022-05-25 15:46 UTC
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

Angular does not properly bind an attribute when using `attr.foo` syntax if there is no interpolation present in the value.

For example, this does not work:

`<div attr.foo="bar"></div> <!-- erroneously keeps the attribute as "attr.foo" -->`

This DOES work:

`<div attr.foo="{{myProp}}"></div>`

This also works:

`<div [attr.foo]="'bar'"></div>`

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-ybks1w?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.module.ts

### Please provide the exception or error you saw

```true
The attribute is not set properly on the element using `attr.foo` syntax when no interpolation is present.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
The reproduction link is using Angular 13, but I also encountered this in my project which produces the following output for `ng version`:


Angular CLI: 12.2.16
Node: 14.19.3
Package Manager: npm 6.14.17
OS: darwin x64

Angular: 12.2.16
... animations, cli, common, compiler, compiler-cli, core
... elements, forms, language-service, localize
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.16
@angular-devkit/build-angular   12.2.16
@angular-devkit/core            12.2.16
@angular-devkit/schematics      12.2.16
@angular/cdk                    12.2.13
@schematics/angular             12.2.16
ng-packagr                      12.2.7
rxjs                            6.6.3
typescript                      4.3.5
webpack                         5.50.0
```
```


### Anything else?

I encountered this in my project previously on Angular 11 as well.

**Comment by atscott** [comment] 2022-05-26 19:42
This is working as expected. There's nothing in the attribute assignment that indicates it's a binding. A binding in the value of an attribute makes the attribute assignment a binding. `[attr.foo]` is also an attribute binding. 

I've updated the title to make this a feature request for the extended diagnostics feature to warn when `attr.x` is not interpreted as a binding. This could also include `style.` and `class.`

**Comment by pkozlowski-opensource** [comment] 2022-05-26 20:13
@atscott yeh, I didn't close this one as I can totally see how it could be confusing. For a user it is not at all clear why `attr.x="{{exp}}"` sets `x` attribute and `attr.x="static"` sets `attr.x`. In a sense the left-hand side of the assignment (target) changes based on the rhs and I would consider this surprising. So it "works as designed" but probably not "as expected".

As an alternative to warning we could just set the `x` attribute for the `attr.x="static"` case.

**Comment by atscott** [comment] 2022-05-26 20:29
> It also requires use of the more verbose `[attr.foo]="'bar'"` in all of the templates

You're actually being _more_ verbose already than you need to be for static attributes. This should really just be `foo="bar"` rather than `attr.foo="bar"`.

**Comment by antch** [comment] 2022-05-26 20:40
@atscott Maybe I'm doing something wrong, but if I try `foo="bar"` the Angular compiler throws the error:
`Can't bind to 'foo' since it isn't a known property of 'a'.` which is why I opted for the `attr.` syntax.

**Comment by atscott** [comment] 2022-05-26 21:55
> @atscott Maybe I'm doing something wrong, but if I try `foo="bar"` the Angular compiler throws the error: `Can't bind to 'foo' since it isn't a known property of 'div'.` which is why I opted for the `attr.` syntax.

I'm not able to reproduce this. Can you share a reproduction?

**Comment by antch** [comment] 2022-05-26 22:02
> > @atscott Maybe I'm doing something wrong, but if I try `foo="bar"` the Angular compiler throws the error: `Can't bind to 'foo' since it isn't a known property of 'div'.` which is why I opted for the `attr.` syntax.
> 
> I'm not able to reproduce this. Can you share a reproduction?

I have `fullTemplateTypeCheck` on, maybe that's it? If not I can get you something soon.

**Comment by antch** [comment] 2022-06-02 00:17
> I'm not able to reproduce this. Can you share a reproduction?

@atscott Looking at my file history, I believe that my mistake was that my reproduction actually included interpolation, for example: `<div foo="{{bar}}" />` which is what was throwing an error. Without the interpolation it works fine. Thanks!

**Closed** 2022-06-30 21:05 UTC
Labels: feature, hotlist: error messages, state: has PR, comp: compiler, core: binding & interpolation, in backlog, compiler: extended diagnostics
