### ISSUE TITLE
Input `transform` does not work if typing is complex

### ISSUE THREAD

**Issue by gmfun** [angular/angular#50574] opened 2023-06-05 12:49 UTC
### Description

Following transform usecase does not work currently

```
function newTransform() {
  return (value: string | number): string => {
      return value.toString()
  }
}

@Input({trasnform: newTrasnform()}) someInput //this does not work
```

## Why this usecase should be supported

Allowing above kind of way of adding trasnform function will make this feature very powerful. We can leverage closure to have internal variable. Example. below transform function can be used to create observable input

```
function newTransform() {
  const subject = new ReplaySubject()
  return (value: string): Observable<string> => {
      subject.next(value)
      return subject
  }
}

@Input({trasnform: newTrasnform()}) someObservableInput //this does not work
```

Without this support input transform will be used for a very limited usecase. As more developers start using input transform they might expect these usecases to work.

### Proposed solution

Support transform function with complex typing

### Alternatives considered

Maybe allow only few preset transform function like coerceToBoolean. So that developer know inout transform has only limited application and should not experimented with to support more complex usecase

**Comment by crisbeto** [comment] 2023-06-05 20:25
The problem is that the compiler needs to be able to statically analyze the type of the transform function parameter and to reference it inside of Angular's generated code. This becomes tricky once factory functions like the example above are involved.

**Comment by nartc** [comment] 2023-06-16 15:14
I also ran into this problem while testing [Signal Input Transform](https://itnext.io/how-to-enjoy-signal-based-input-right-now-56efecaeee98) by @gmfun. 

Would it make sense to adjust `transform` signature also to accept the component instance as well as the name of the input?

```ts
// instead of
// value = inputTransforms[privateName].call(instance, value);
// we could have
value = inputTransforms[privateName].call(instance, value, instance, privateName);
```

Here's a sample implementation of `signalTransform` if `transform` is called with `instance` and `privateName`

```ts
const cache = new Map();

export function signalTransform(value: unknown, ctx: any, property: string) {
    let cachedSignal = cache.get(ctx)?.get(property);
    if (!cachedSignal) {
        if (!cache.has(ctx)) {
            cache.set(ctx, new Map());
        }
        cache.get(ctx)!.set(
            property, 
            (cachedSignal = ctx[property] && isSignal(ctx[property]) ? ctx[property] : signal())
        );
    }
    
    cachedSignal.set(value);
    return cachedSignal.asReadonly();
}
```

Usage:

```ts
@Input({ transform: signalTransform }) isAwesome = signal(false); // typings for "isAwesome" is tricky on the template for the consumers but that would be solved with the official signal "input()"
```

**Comment by rosostolato** [comment] 2024-01-07 16:18
Any update on this?

**Comment by JeanMeche** [comment] 2024-01-11 15:43
I'll close this as "fixed" by using the Signal inputs which don't suffer the same limitations as decorator inputs !

**Closed by JeanMeche** 2024-01-11 15:43 UTC
Labels: area: core, core: inputs / outputs

**Comment by craiggoldstone** [comment] 2024-01-11 15:52
My favourite kind of bug: user error! Thank you, all working excellently using `disabled = input<boolean, string | boolean>(false, { transform: booleanAttribute })`
