### ISSUE TITLE
Runtime i18n translation support

### ISSUE THREAD

**Issue by timothyBrake** [angular/angular#45467] opened 2022-03-29 16:15 UTC
### Which @angular/* package(s) are relevant/related to the feature request?

localize

### Description

Angular has a $localize feature that seems to be used only at built time and there is no way to get an actual translation at runtime using a dynamic generated id in a TypeScript file. Use case would be a backend call that returns translation ids that are used to get the Angular i18n translation and display that translated message in the UI.

### Proposed solution

- Create a basic service LocalizeService that has a single method  
`get(id:string):string` that returns the exact translated message of the current selected locale.

- Create a more advanced version that takes in all the features $localize would do but then at runtime like parameters etc...

### Alternatives considered

We are using Angular localise feature so there is no alternative to use. This should be a basic feature in Angular.

**Comment by kedevked** [comment] 2022-07-08 14:35
I think that runtime translation should be added to the core of angular instead of having to rely on 3rd parties like transloco

**Comment by AsmisAlan** [comment] 2023-04-25 18:43
Hi! any update about this feature ?

**Comment by alan-agius4** [comment] 2024-01-16 08:39
Duplicate of https://github.com/angular/angular/issues/38953

**Closed by alan-agius4** 2024-01-16 08:39 UTC
Labels: feature, area: i18n, feature: under consideration, canonical
