### ISSUE TITLE
Pure Pipes not detecting argument-change when the argument is an object

### ISSUE THREAD

**Issue by zyarnold** [angular/angular#16595] opened 2017-05-06 02:05 UTC
```
import { Pipe, PipeTransform } from '@angular/core';

@Pipe({
  name: 'pagerPipe'
})
export class PagerPipe implements PipeTransform {

  transform(array: any[], pager: Pager): any {
    var start = (pager.activePage-1)*pager.pageSize;
    var end = pager.activePage*pager.pageSize;
    console.log(start,end);
    return array.slice(start,end);
  }

};
//--------------------------------------------------------------------------
export class Pager {
  pageSize:number;
  activePage:number;
};
```
It works just fine when I set the arguments to have individual pageSize and activePage,
But when I pass a class that has both pageSize and pageNumber, the pipe doesnt detect argument changes

**Comment by alexzuza** [comment] 2017-05-06 04:20
Please create plunker to reproduce it. Do you pass new object reference?

**Comment by zyarnold** [comment] 2017-05-06 17:34
> Please create plunker to reproduce it. Do you pass new object reference?

Unfortunately Im using angular-cli via ng build and "plunker" wont let me upload vendor.bundle.js saying "save failed"

And No. I am not passing new object reference but rather same object but changing its properties via [(ngModel)]="myPager.activePage" and in my list via *ngFor="let item of Items|pagerPipe:myPager"

**Comment by tytskyi** [comment] 2017-05-06 22:13
>  I am not passing new object reference but rather same object but changing its properties via [(ngModel)]="myPager.activePage" 

That's why you can't use `pure` pipe. Just use impure, or reconsider implementation

**Comment by zoechi** [comment] 2017-05-07 16:43
Angular change detection doesn't check object or array content, therefore it's behaving "as designed".
The issue template contains a link to an Angular Plunker template (http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5)

**Comment by zyarnold** [comment] 2017-05-08 13:21
As an alternative..would it be considered a bad a practice to call *ngFor with a function that returns an array? *ngFor="let item of getArray()"

**Comment by zoechi** [comment] 2017-05-08 15:06
@zyarnold Depends on how `getArray()` is implemented. `getArray()` should not return a new array instance when the content didn't actually change, otherwise you'll get a error (value has changed since it was last checked)

**Comment by tytskyi** [comment] 2017-05-08 20:50
@zyarnold 

I see few potential solutions:

1. Implement pipe with `pure: false`. 
++ just works
++ high reusability
-- poor performance

2. Break references manually. 
As for array it is obvious - if you get it from http - each time you get new reference. 
As for `Pager` you need to do it manually - using separate `(ngModelChange)` instead of `[(ngModel)]`. OR use reactive form and retrieve `Pager` model from `form.valueChanges` observable - then you get new reference every time.
++ good performance 
-- low reusability
-- a bit of manual work

3. Change signature `transform(array: any[], activePage: number, pageSize: number = 10)`
*Note: you still need to break reference to `array`
++ good performance
++ good reusability
-- not possible when you need a lot of parameters 

4. Ember pagination logic into component (This promoted by Angular docs).
> The Angular team and many experienced Angular developers strongly recommend moving filtering and sorting logic into the component itself. The component can expose a `filteredHeroes` or `sortedHeroes` property and take control over when and how often to execute the supporting logic. Any capabilities that you would have put in a pipe and shared across the app can be written in a filtering/sorting service and injected into the component.
from https://angular.io/docs/ts/latest/guide/pipes.html#!#no-filter-pipe

++ you have full control over performance
++ unlocks aggressive minification
-- can be a lot of manual work
-- poor reusability

In my personal opinion i would not choose one of those approaches as only one correct, but rather choose which one works better in in particular situation.

@zyarnold  if you could create stackoverflow issue, then we could move that answer there. Issue tracker is not a good place for "usage questions". And this particular issue is not a bug report, because it works as designed and documented. Would be cool if you could close this issue.

**Comment by mhevery** [comment] 2017-05-08 23:43
Angular change detection only looks at object reference and not deep watches the object for mutation since that would be expensive. This works as intended.

**Closed by mhevery** 2017-05-08 23:43 UTC

**Comment by ng-ankit-bhardwaj** [comment] 2018-03-19 15:02
https://medium.com/@ankitbhardwaj_49963/impure-pipes-in-angular-94ba7f112e4a
