### ISSUE TITLE
 Ivy does not report errors

### ISSUE THREAD

**Issue by benjamingb** [angular/angular#31598] opened 2019-07-16 21:25 UTC
# 🐞 bug report

### Affected Package

 compiler 

### Is this a regression?

 Yes, 

### Description
 
Generate a project with Yvy Enabled and by mistake call directly to a component and not to the module that contains the component with all the directives, angular never alerts me.

When I disable Yvy and put AOT:false I just showed the error
<pre><code>
architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "aot": false, <-- CHANGE TO FALSE 
</code></pre>
## 🔥 Exception or Error
<pre><code>

core.js:9110 ERROR Error: Uncaught (in promise): 
Error: Component ProyectListUiComponent is not part of any NgModule or the module has not been imported into your module.
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 8.1.1
Node: 10.15.3
OS: linux x64
Angular: 8.1.1
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.801.1
@angular-devkit/build-angular      0.801.1
@angular-devkit/build-ng-packagr   0.801.1
@angular-devkit/build-optimizer    0.801.1
@angular-devkit/build-webpack      0.801.1
@angular-devkit/core               8.1.1
@angular-devkit/schematics         8.1.1
@angular/cdk                       8.1.0
@ngtools/json-schema               1.1.0
@ngtools/webpack                   8.1.1
@schematics/angular                8.1.1
@schematics/update                 0.801.1
ng-packagr                         5.3.0
rxjs                               6.5.2
typescript                         3.4.5
webpack                            4.35.2
</code></pre>

**Anything else relevant?**

**Comment by alxhub** [comment] 2019-07-16 22:06
Yes, this is a known issue - the diagnostics reported by the compiler are in general not 100% feature complete. It's on our roadmap to finish this soon.

**Comment by alxhub** [comment] 2019-07-16 22:11
This is actually sort of WAI! Ivy allows `NgModule`-less components.

What's actually missing here is the template type-checking experience that would tell you if certain elements/bindings in the template were not matched. In this case, our compiler should also know that the component is not part of a module, and let you know that this might be one reason why.

**Comment by alxhub** [comment] 2019-07-16 22:38
Closing as a duplicate of #31108.

**Closed by alxhub** 2019-07-16 22:38 UTC
Labels: comp: compiler, comp: ivy, freq1: low, freq3: high, severity2: inconvenient, type: bug/fix
