### ISSUE TITLE
ability to use/change environment files after build

### ISSUE THREAD

**Issue by DimitriTsikaridze** [angular/angular#52994] opened 2023-11-17 11:21 UTC
### Description

environment files always felt bit weird to me, they are  only used at build time and cannot be modified at runtime. there are couple of tedious options like creating json file then having app initializer to read contents of that file to set env values.

there have been many [blog posts](https://mokkapps.de/blog/how-to-build-an-angular-app-once-and-deploy-it-to-multiple-environments) on this and I think there should be lot easier way built into the framework.

would be nice if environment  files were in separate json file after building the app, so we could change values for different pipelines and environments. 

### Proposed solution

running ng build produces environment.json file, which we can modify, then application automatically looks into that file for correct values.

### Alternatives considered

alternatives would be solutions we have now, using app initializer and local json file and so on.

**Comment by alan-agius4** [comment] 2023-11-17 12:07
Duplicate of https://github.com/angular/angular-cli/issues/4318

**Closed by alan-agius4** 2023-11-17 12:07 UTC
