### ISSUE TITLE
Youtube embed links is not working in firefox for the new angular documentation website

### ISSUE THREAD

**Issue by Rajendran-Balaji** [angular/angular#53184] opened 2023-11-27 07:51 UTC
### Describe the problem that you experienced

It looks like all the youtube embed links in the new angular docs are not working in the firefox browser
I see an error 
![image](https://github.com/angular/angular/assets/88931771/c5ad164d-ee76-4b90-bc1d-b2945160157a)

But in the old documentation website, youtube embed works for the same browser
![image](https://github.com/angular/angular/assets/88931771/007e230f-6dba-4033-b076-a76f396bece5)

I checked the browser console and I see no errors. 
But in the network tab I noticed the following
![image](https://github.com/angular/angular/assets/88931771/88a28332-3e98-4c26-bc6b-0accfe911f73)

### If the problem is browser-specific, please specify the device, OS, browser, and version

```true
OS Ubuntu 22.04
browser Mozilla firfox snap 120 (64bit) for Ubuntu
```

**Comment by twerske** [comment] 2023-11-29 17:57
This is a duplicate of https://github.com/angular/angular/issues/52640

**Closed by twerske** 2023-11-29 17:57 UTC
Labels: area: adev
