### ISSUE TITLE
Signals Effect don't run inside asynchronous or condition.

### ISSUE THREAD

**Issue by rdlabo** [angular/angular#56773] opened 2024-06-30 06:23 UTC
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

Effect don't run if there is an asynchronous or conditional statement.

```ts
 constructor() {
    effect(() => {
      if (this.insideSimpleEffect === 5) {
        this.insideCondition = this.count();
      }
    });
    effect(() => {
      requestAnimationFrame(() => {
        this.insideRequestAnimationFrame = this.count();
      });
    });
    effect(() => {
      setTimeout(() => {
        this.insideSetTimeout = this.count();
      }, 100);
    });
  }
```

However, it will run if you simply add console.log etc:

```ts
 constructor() {
    effect(() => {
      console.log(this.count());
      if (this.insideSimpleEffect === 5) {
        this.insideCondition = this.count();
      }
    });
}
```

Expect to run in such cases. Thanks.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-unvngn?file=src%2Fmain.ts

### Please provide the exception or error you saw

```true
None.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 18.0.4
Node: 18.20.3
Package Manager: npm 10.2.3
OS: linux x64

Angular: 18.0.3
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1800.4
@angular-devkit/build-angular   18.0.4
@angular-devkit/core            18.0.4
@angular-devkit/schematics      18.0.4
@angular/cli                    18.0.4
@schematics/angular             18.0.4
rxjs                            7.8.1
typescript                      5.4.5
zone.js                         0.14.7
```

**Comment by JoostK** [comment] 2024-06-30 08:23
This is working as designed. Only when a signal is actually read will the `effect` register a dependency on its value, so if it's hidden behind a falsy conditional (that isn't itself derived from a signal) or the work happens in a new stack frame (such as with `requestAnimationFrame`) then the effect also won't be able to track the signal read.

Closing as duplicate of #55647 with #56155 as related issue.

**Closed by JoostK** 2024-06-30 08:23 UTC

**Comment by rdlabo** [comment] 2024-07-02 04:16
> Only when a signal is actually read will the effect register a dependency on its value, so if it's hidden behind a falsy conditional (that isn't itself derived from a signal) or the work happens in a new stack frame (such as with requestAnimationFrame) then the effect also won't be able to track the signal read.

Thanks for the excellent findings. I have decided to use the immediate function in all Effects to table the Signal to be tracked.

```ts
    effect(() => ((count: number) => {
      if (this.insideSimpleEffect === 5) {
        this.insideCondition = count;
      }
    })(this.count()));

    effect(() => ((count: number) => {
      requestAnimationFrame(() => {
        this.insideRequestAnimationFrame = count;
      });
    })(this.count()));

    effect(() => ((count: number) => {
      setTimeout(() => {
        this.insideSetTimeout = count();
      }, 100);
    })(this.count()));
```

This worked fine!
