### ISSUE TITLE
Add experimental package exports @angular/*/experiments

### ISSUE THREAD

**Issue by yjaaidi** [angular/angular#46400] opened 2022-06-17 00:12 UTC
### Which @angular/* package(s) are relevant/related to the feature request?

all

### Description

Currently, Angular's API doesn't have an intermediate between the internal API & the public API.

Most researchers & library authors end up either hacking into the internals to experiment with new things or waiting for public APIs to appear. Some public APIs might never appear if there is no experimental phase to prove their usefulness.

### Proposed solution

Provide `@angular/*/experimental` package exports with experimental APIs and with the following conditions:
- minor versions can include breaking changes
- related issues have a lower priority to avoid producing too much noise

**These experimental APIs could be a great enabler for community initiatives.** 
Researchers & library authors would need less internal knowledge and hacks to experiment with the new APIs and explore new possibilities.

Here are some examples:

```ts
import { FormGroup } from '@angular/forms/experimental'; // typed reactive forms

import { bootstrapApplication } from '@angular/platform-browser/experimental';

import { getComponentMetadata } from '@angular/core/experimental'
const isStandalone = getComponentMetadata(MyCmp).standalone  === true;
```

### Alternatives considered

1. infiltrating the core team
2. keep hacking the internals

**Comment by pkozlowski-opensource** [comment] 2022-06-17 08:53
We had multiple discussion around this topic in the team and have various ideas in progress. Also in the past we had the "labs" packages. But we still didn't settle on the exact guarantees for those packages.

So yes, see the the value of it and it is on our radar but didn't work out the details.

I'm going to close this issue as it is not a bug report / future request and there is nothing actionable for us here in the immediate future.

**Closed by pkozlowski-opensource** 2022-06-17 08:53 UTC

**Comment by yjaaidi** [comment] 2022-06-17 10:53
👌
