### ISSUE TITLE
FormControl changes to status not being emitted to statusChanges observable

### ISSUE THREAD

**Issue by maddockst** [angular/angular#41992] opened 2021-05-07 16:06 UTC
# Bug Report

### Affected Package
@angular/forms

### Is this a regression?
Don't believe so

### Description
When a reactive form control is rendered, any underlying validators are run. With an async validator, the `statusChanges` observable receives no emissions even though `status` changes. In the below example, you will see that toggling the control visibility causes the validator to run, the `status` to change but the `statusChanges` observable seeing no new emissions. When changing the value of the input, it all works as expected with the validator running as well as the `statusChanges` seeing the new `status` values

Without this behaviour, I am unable to respond to the `status` of a `FormControl` or `FormGroup` changing.

## Minimal Reproduction
https://stackblitz.com/edit/angular-ivy-idcnym

**Comment by dylhunn** [comment] 2021-06-08 23:59
We think this might be related to and/or a duplicate of #39588. I am writing some unit tests, and I'll determine whether it's the same problem.

**Comment by dylhunn** [comment] 2021-06-10 00:37
I just spent some time looking at this with Andrew, and it's not actually the same issue as #39588.

Here's a minimal unit test that exposes the problem:
```
it('should fire statusChanges events for async validators from PENDING to VALID ', fakeAsync(() => {
  let statuses: string[] = [];
  
  // Create a form control with an async validator
  const asynccontrol = new FormControl('defaultval', {
   asyncValidators: [(control) => {
     return Promise.resolve(null);
   }]
  });
  
  // Subscribe to status changes.
  asynccontrol.statusChanges.subscribe({
   next: (status: any) => {
     statuses.push(status);
   }
  });
  
  // After a tick, the async validator should change status PENDING -> VALID.
  tick();
  expect(statuses.length).toBeGreaterThan(0);
}));
```

The culprit is here:

https://github.com/angular/angular/blob/665b986896d744890693f192c48a1e2d6d4175e7/packages/forms/src/model.ts#L1164-L1171

We are ignoring async validators provided as part of `validatorOrOpts`.

This will be a breaking change because fixing it will cause `statusChanges` subscribers to be called an extra time for many clients. I will run a TGP to assess the scope of the breakage, at least within google3.

**Closed** 2021-06-15 18:23 UTC
Labels: P3, comp: forms
