### ISSUE TITLE
select element's ngModel is incorrect for options added as viewchildren 

### ISSUE THREAD

**Issue by mmorgansancsoft** [angular/angular#35344] opened 2020-02-11 20:17 UTC
When setting up a select html element with options added as view children, the select element outputs the option text instead of the options ngValue.

Follow this stackblitz for an example.  Notice how 0 outputs its option's ngValue, while 1,2,3 output their option's text.

https://stackblitz.com/edit/ngvalue-bug?embed=1&file=src/app/app.component.html

**Comment by AndrewKushnir** [comment] 2020-05-29 23:56
Hi @mmorgansancsoft, thanks for reporting the issue and providing a repro. This issue is related to #26273. As a possible workaround you can try to create a wrapper component that would have the `<select>` tag inside it and use content projection. Another option might be providing options information as an input to that component and create `<option>` elements inside that component's template. Thank you.

**Comment by eddietisma** [comment] 2020-06-26 13:41
I would consider not having a hard-coded type injections and utilize `InjectionToken` instead. This would enable others to build custom select components, which would provide the token when needed.

[select_control_value_accessor.ts:SelectControlValueAccessor](https://github.com/angular/angular/blob/eee2fd22e0a41d1df8e504a96501d83bb8e6f4cb/packages/forms/src/directives/select_control_value_accessor.ts#L90)
`providers: [SELECT_VALUE_ACCESSOR]`

[select_control_value_accessor.ts:NgSelectOption](https://github.com/angular/angular/blob/eee2fd22e0a41d1df8e504a96501d83bb8e6f4cb/packages/forms/src/directives/select_control_value_accessor.ts#L215)

```
constructor(
   private _element: ElementRef, private _renderer: Renderer2,
   @Optional() @Host() private _select: SelectControlValueAccessor) { /* Hard-coded type SelectControlValueAccessor */
   if (this._select) this.id = this._select._registerOption();
}
```



Please take a look at a the material design component library, it has a simular approach in its handling of `mat-select` and `mat-option`.

[select.ts](https://github.com/angular/components/blob/286fd99015ea27426bd88a375e68b5377b8e5764/src/material/select/select.ts#L245)
```
providers: [
    {provide: MatFormFieldControl, useExisting: MatSelect},
    {provide: MAT_OPTION_PARENT_COMPONENT, useExisting: MatSelect}
],
```

[option.ts](https://github.com/angular/components/blob/286fd99015ea27426bd88a375e68b5377b8e5764/src/material/core/option/option.ts#L123)
```
constructor(
   private _element: ElementRef<HTMLElement>,
   private _changeDetectorRef: ChangeDetectorRef,
   @Optional() @Inject(MAT_OPTION_PARENT_COMPONENT) private _parent: MatOptionParentComponent,
  @Optional() readonly group: MatOptgroup) {}
`
```

**Comment by AndrewKushnir** [comment] 2020-10-22 23:22
Closing as a duplicate of #26273.

**Closed by AndrewKushnir** 2020-10-22 23:22 UTC
Labels: comp: forms, forms: ControlValueAccessor, forms: ngModel, state: confirmed, triage #1, type: bug/fix, workaround1: obvious
