### ISSUE TITLE
v5 Service-Worker not updating the app

### ISSUE THREAD

**Issue by jvitor83** [angular/angular#25307] opened 2018-08-04 16:36 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
I am using `@angular/service-worker` at production. It was fine, until i notice it was not updating the app.
Here is the ngsw/state page content:
```
NGSW Debug Info:

Driver state: EXISTING_CLIENTS_ONLY (Degraded due to failed initialization: Hash mismatch (cacheBustedFetchFromNetwork): https://m.tjmt.jus.br/styles.5ecb9ce6514526e5a01b.bundle.css: expected 052d5aa8f15b2210e884e83476758c05da55a6d3, got 915c346213ef4c4255154c319ef58b3f364ac08e (after cache busting)
Error: Hash mismatch (cacheBustedFetchFromNetwork): https://m.tjmt.jus.br/styles.5ecb9ce6514526e5a01b.bundle.css: expected 052d5aa8f15b2210e884e83476758c05da55a6d3, got 915c346213ef4c4255154c319ef58b3f364ac08e (after cache busting)
    at PrefetchAssetGroup.cacheBustedFetchFromNetwork (https://m.tjmt.jus.br/ngsw-worker.js:672:27))
Latest manifest hash: 5fadf83299a479206a3521b215aa168291e79d09
Last update check: 8m39s408u

=== Version 5fadf83299a479206a3521b215aa168291e79d09 ===

Clients: 74293baa-dcb4-4881-a813-63b214813c4c

=== Idle Task Queue ===
Last update tick: 8m44s466u
Last update run: 8m39s464u
Task queue:


Debug log:

[1h12m57s946u] Error(Hash mismatch (cacheBustedFetchFromNetwork): https://m.tjmt.jus.br/styles.5ecb9ce6514526e5a01b.bundle.css: expected 052d5aa8f15b2210e884e83476758c05da55a6d3, got 915c346213ef4c4255154c319ef58b3f364ac08e (after cache busting), Error: Hash mismatch (cacheBustedFetchFromNetwork): https://m.tjmt.jus.br/styles.5ecb9ce6514526e5a01b.bundle.css: expected 052d5aa8f15b2210e884e83476758c05da55a6d3, got 915c346213ef4c4255154c319ef58b3f364ac08e (after cache busting)
    at PrefetchAssetGroup.cacheBustedFetchFromNetwork (https://m.tjmt.jus.br/ngsw-worker.js:672:27)) Error occurred while updating to manifest 716d18ed3c29699acff5ab0c4453b8cad6bea984
[1h2m45s755u] Ignoring invalid request: 'only-if-cached' can be set only with 'same-origin' mode Driver.fetch(https://m.tjmt.jus.br/home?homescreen=1, cache: only-if-cached, mode: no-cors)
[1h2m25s875u] Error(Hash mismatch (cacheBustedFetchFromNetwork): https://m.tjmt.jus.br/styles.5ecb9ce6514526e5a01b.bundle.css: expected 052d5aa8f15b2210e884e83476758c05da55a6d3, got 915c346213ef4c4255154c319ef58b3f364ac08e (after cache busting), Error: Hash mismatch (cacheBustedFetchFromNetwork): https://m.tjmt.jus.br/styles.5ecb9ce6514526e5a01b.bundle.css: expected 052d5aa8f15b2210e884e83476758c05da55a6d3, got 915c346213ef4c4255154c319ef58b3f364ac08e (after cache busting)
    at PrefetchAssetGroup.cacheBustedFetchFromNetwork (https://m.tjmt.jus.br/ngsw-worker.js:672:27)) Error occurred while updating to manifest 716d18ed3c29699acff5ab0c4453b8cad6bea984
[1h1m29s576u] Error(Hash mismatch (cacheBustedFetchFromNetwork): https://m.tjmt.jus.br/styles.5ecb9ce6514526e5a01b.bundle.css: expected 052d5aa8f15b2210e884e83476758c05da55a6d3, got 915c346213ef4c4255154c319ef58b3f364ac08e (after cache busting), Error: Hash mismatch (cacheBustedFetchFromNetwork): https://m.tjmt.jus.br/styles.5ecb9ce6514526e5a01b.bundle.css: expected 052d5aa8f15b2210e884e83476758c05da55a6d3, got 915c346213ef4c4255154c319ef58b3f364ac08e (after cache busting)
    at PrefetchAssetGroup.cacheBustedFetchFromNetwork (https://m.tjmt.jus.br/ngsw-worker.js:672:27)) Error occurred while updating to manifest 716d18ed3c29699acff5ab0c4453b8cad6bea984
[59m54s739u] Error(Hash mismatch (cacheBustedFetchFromNetwork): https://m.tjmt.jus.br/styles.5ecb9ce6514526e5a01b.bundle.css: expected 052d5aa8f15b2210e884e83476758c05da55a6d3, got 915c346213ef4c4255154c319ef58b3f364ac08e (after cache busting), Error: Hash mismatch (cacheBustedFetchFromNetwork): https://m.tjmt.jus.br/styles.5ecb9ce6514526e5a01b.bundle.css: expected 052d5aa8f15b2210e884e83476758c05da55a6d3, got 915c346213ef4c4255154c319ef58b3f364ac08e (after cache busting)
    at PrefetchAssetGroup.cacheBustedFetchFromNetwork (https://m.tjmt.jus.br/ngsw-worker.js:672:27)) Error occurred while updating to manifest 716d18ed3c29699acff5ab0c4453b8cad6bea984
[57m28s969u] Error(Hash mismatch (cacheBustedFetchFromNetwork): https://m.tjmt.jus.br/styles.5ecb9ce6514526e5a01b.bundle.css: expected 052d5aa8f15b2210e884e83476758c05da55a6d3, got 915c346213ef4c4255154c319ef58b3f364ac08e (after cache busting), Error: Hash mismatch (cacheBustedFetchFromNetwork): https://m.tjmt.jus.br/styles.5ecb9ce6514526e5a01b.bundle.css: expected 052d5aa8f15b2210e884e83476758c05da55a6d3, got 915c346213ef4c4255154c319ef58b3f364ac08e (after cache busting)
    at PrefetchAssetGroup.cacheBustedFetchFromNetwork (https://m.tjmt.jus.br/ngsw-worker.js:672:27)) Error occurred while updating to manifest 716d18ed3c29699acff5ab0c4453b8cad6bea984
[55m32s291u] Error(Hash mismatch (cacheBustedFetchFromNetwork): https://m.tjmt.jus.br/styles.5ecb9ce6514526e5a01b.bundle.css: expected 052d5aa8f15b2210e884e83476758c05da55a6d3, got 915c346213ef4c4255154c319ef58b3f364ac08e (after cache busting), Error: Hash mismatch (cacheBustedFetchFromNetwork): https://m.tjmt.jus.br/styles.5ecb9ce6514526e5a01b.bundle.css: expected 052d5aa8f15b2210e884e83476758c05da55a6d3, got 915c346213ef4c4255154c319ef58b3f364ac08e (after cache busting)
    at PrefetchAssetGroup.cacheBustedFetchFromNetwork (https://m.tjmt.jus.br/ngsw-worker.js:672:27)) Error occurred while updating to manifest 716d18ed3c29699acff5ab0c4453b8cad6bea984
[41m1s713u] Error(Hash mismatch (cacheBustedFetchFromNetwork): https://m.tjmt.jus.br/styles.5ecb9ce6514526e5a01b.bundle.css: expected 052d5aa8f15b2210e884e83476758c05da55a6d3, got 915c346213ef4c4255154c319ef58b3f364ac08e (after cache busting), Error: Hash mismatch (cacheBustedFetchFromNetwork): https://m.tjmt.jus.br/styles.5ecb9ce6514526e5a01b.bundle.css: expected 052d5aa8f15b2210e884e83476758c05da55a6d3, got 915c346213ef4c4255154c319ef58b3f364ac08e (after cache busting)
    at PrefetchAssetGroup.cacheBustedFetchFromNetwork (https://m.tjmt.jus.br/ngsw-worker.js:672:27)) Error occurred while updating to manifest 716d18ed3c29699acff5ab0c4453b8cad6bea984
[20m48s237u] Error(Hash mismatch (cacheBustedFetchFromNetwork): https://m.tjmt.jus.br/styles.5ecb9ce6514526e5a01b.bundle.css: expected 052d5aa8f15b2210e884e83476758c05da55a6d3, got 915c346213ef4c4255154c319ef58b3f364ac08e (after cache busting), Error: Hash mismatch (cacheBustedFetchFromNetwork): https://m.tjmt.jus.br/styles.5ecb9ce6514526e5a01b.bundle.css: expected 052d5aa8f15b2210e884e83476758c05da55a6d3, got 915c346213ef4c4255154c319ef58b3f364ac08e (after cache busting)
    at PrefetchAssetGroup.cacheBustedFetchFromNetwork (https://m.tjmt.jus.br/ngsw-worker.js:672:27)) Error occurred while updating to manifest 716d18ed3c29699acff5ab0c4453b8cad6bea984
[18m45s891u] Error(Hash mismatch (cacheBustedFetchFromNetwork): https://m.tjmt.jus.br/styles.5ecb9ce6514526e5a01b.bundle.css: expected 052d5aa8f15b2210e884e83476758c05da55a6d3, got 915c346213ef4c4255154c319ef58b3f364ac08e (after cache busting), Error: Hash mismatch (cacheBustedFetchFromNetwork): https://m.tjmt.jus.br/styles.5ecb9ce6514526e5a01b.bundle.css: expected 052d5aa8f15b2210e884e83476758c05da55a6d3, got 915c346213ef4c4255154c319ef58b3f364ac08e (after cache busting)
    at PrefetchAssetGroup.cacheBustedFetchFromNetwork (https://m.tjmt.jus.br/ngsw-worker.js:672:27)) Error occurred while updating to manifest 716d18ed3c29699acff5ab0c4453b8cad6bea984
[18m12s286u] Error(Hash mismatch (cacheBustedFetchFromNetwork): https://m.tjmt.jus.br/styles.5ecb9ce6514526e5a01b.bundle.css: expected 052d5aa8f15b2210e884e83476758c05da55a6d3, got 915c346213ef4c4255154c319ef58b3f364ac08e (after cache busting), Error: Hash mismatch (cacheBustedFetchFromNetwork): https://m.tjmt.jus.br/styles.5ecb9ce6514526e5a01b.bundle.css: expected 052d5aa8f15b2210e884e83476758c05da55a6d3, got 915c346213ef4c4255154c319ef58b3f364ac08e (after cache busting)
    at PrefetchAssetGroup.cacheBustedFetchFromNetwork (https://m.tjmt.jus.br/ngsw-worker.js:672:27)) Error occurred while updating to manifest 716d18ed3c29699acff5ab0c4453b8cad6bea984
[16m789u] Error(Hash mismatch (cacheBustedFetchFromNetwork): https://m.tjmt.jus.br/styles.5ecb9ce6514526e5a01b.bundle.css: expected 052d5aa8f15b2210e884e83476758c05da55a6d3, got 915c346213ef4c4255154c319ef58b3f364ac08e (after cache busting), Error: Hash mismatch (cacheBustedFetchFromNetwork): https://m.tjmt.jus.br/styles.5ecb9ce6514526e5a01b.bundle.css: expected 052d5aa8f15b2210e884e83476758c05da55a6d3, got 915c346213ef4c4255154c319ef58b3f364ac08e (after cache busting)
    at PrefetchAssetGroup.cacheBustedFetchFromNetwork (https://m.tjmt.jus.br/ngsw-worker.js:672:27)) Error occurred while updating to manifest 716d18ed3c29699acff5ab0c4453b8cad6bea984
[15m3s735u] Error(Hash mismatch (cacheBustedFetchFromNetwork): https://m.tjmt.jus.br/styles.5ecb9ce6514526e5a01b.bundle.css: expected 052d5aa8f15b2210e884e83476758c05da55a6d3, got 915c346213ef4c4255154c319ef58b3f364ac08e (after cache busting), Error: Hash mismatch (cacheBustedFetchFromNetwork): https://m.tjmt.jus.br/styles.5ecb9ce6514526e5a01b.bundle.css: expected 052d5aa8f15b2210e884e83476758c05da55a6d3, got 915c346213ef4c4255154c319ef58b3f364ac08e (after cache busting)
    at PrefetchAssetGroup.cacheBustedFetchFromNetwork (https://m.tjmt.jus.br/ngsw-worker.js:672:27)) Error occurred while updating to manifest 716d18ed3c29699acff5ab0c4453b8cad6bea984
[10m22s237u] Error(Hash mismatch (cacheBustedFetchFromNetwork): https://m.tjmt.jus.br/styles.5ecb9ce6514526e5a01b.bundle.css: expected 052d5aa8f15b2210e884e83476758c05da55a6d3, got 915c346213ef4c4255154c319ef58b3f364ac08e (after cache busting), Error: Hash mismatch (cacheBustedFetchFromNetwork): https://m.tjmt.jus.br/styles.5ecb9ce6514526e5a01b.bundle.css: expected 052d5aa8f15b2210e884e83476758c05da55a6d3, got 915c346213ef4c4255154c319ef58b3f364ac08e (after cache busting)
    at PrefetchAssetGroup.cacheBustedFetchFromNetwork (https://m.tjmt.jus.br/ngsw-worker.js:672:27)) Error occurred while updating to manifest 716d18ed3c29699acff5ab0c4453b8cad6bea984
[9m48s935u] Error(Hash mismatch (cacheBustedFetchFromNetwork): https://m.tjmt.jus.br/styles.5ecb9ce6514526e5a01b.bundle.css: expected 052d5aa8f15b2210e884e83476758c05da55a6d3, got 915c346213ef4c4255154c319ef58b3f364ac08e (after cache busting), Error: Hash mismatch (cacheBustedFetchFromNetwork): https://m.tjmt.jus.br/styles.5ecb9ce6514526e5a01b.bundle.css: expected 052d5aa8f15b2210e884e83476758c05da55a6d3, got 915c346213ef4c4255154c319ef58b3f364ac08e (after cache busting)
    at PrefetchAssetGroup.cacheBustedFetchFromNetwork (https://m.tjmt.jus.br/ngsw-worker.js:672:27)) Error occurred while updating to manifest 716d18ed3c29699acff5ab0c4453b8cad6bea984
[9m11s730u] Error(Hash mismatch (cacheBustedFetchFromNetwork): https://m.tjmt.jus.br/styles.5ecb9ce6514526e5a01b.bundle.css: expected 052d5aa8f15b2210e884e83476758c05da55a6d3, got 915c346213ef4c4255154c319ef58b3f364ac08e (after cache busting), Error: Hash mismatch (cacheBustedFetchFromNetwork): https://m.tjmt.jus.br/styles.5ecb9ce6514526e5a01b.bundle.css: expected 052d5aa8f15b2210e884e83476758c05da55a6d3, got 915c346213ef4c4255154c319ef58b3f364ac08e (after cache busting)
    at PrefetchAssetGroup.cacheBustedFetchFromNetwork (https://m.tjmt.jus.br/ngsw-worker.js:672:27)) Error occurred while updating to manifest 716d18ed3c29699acff5ab0c4453b8cad6bea984
[8m25s254u] Error(Hash mismatch (cacheBustedFetchFromNetwork): https://m.tjmt.jus.br/styles.5ecb9ce6514526e5a01b.bundle.css: expected 052d5aa8f15b2210e884e83476758c05da55a6d3, got 915c346213ef4c4255154c319ef58b3f364ac08e (after cache busting), Error: Hash mismatch (cacheBustedFetchFromNetwork): https://m.tjmt.jus.br/styles.5ecb9ce6514526e5a01b.bundle.css: expected 052d5aa8f15b2210e884e83476758c05da55a6d3, got 915c346213ef4c4255154c319ef58b3f364ac08e (after cache busting)
    at PrefetchAssetGroup.cacheBustedFetchFromNetwork (https://m.tjmt.jus.br/ngsw-worker.js:672:27)) Error occurred while updating to manifest 716d18ed3c29699acff5ab0c4453b8cad6bea984
```

## Expected behavior
To update the app to the new version.

## Minimal reproduction of the problem with instructions
No idea, because it was working before.

## Environment

<pre><code>
"dependencies": {
    "@angular/animations": "~5.2.11",
    "@angular/common": "~5.2.11",
    "@angular/compiler": "~5.2.11",
    "@angular/core": "~5.2.11",
    "@angular/forms": "~5.2.11",
    "@angular/http": "~5.2.11",
    "@angular/platform-browser": "~5.2.11",
    "@angular/platform-browser-dynamic": "~5.2.11",
    "@angular/platform-server": "~5.2.11",
    "@angular/router": "~5.2.11",
    "@angular/service-worker": "~5.2.11",

  "devDependencies": {
    "@angular/cli": "^1.7.3",
    "@angular/compiler-cli": "^5.2.5",
    "@angular/language-service": "^5.2.5",
    "@angular/tsc-wrapped": "^4.4.6",

Browser:
- [ ] Chrome (desktop) version XX
- [x] Chrome (Android) version 69
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
</code></pre>

**Comment by gkalpak** [comment] 2018-08-05 13:10
The error implies that the hash of the received `styles` file is different than the hash that was computed at build time (basically the contents are different).

It is impossible to tell what causes this (could be something modifying the file after the hash has been computed, or the server or a proxy modifying the file on the fly, or using an outdated `ngsw.json` file (less likely)).

In any case, this is an issue with your setup/app/build process and we can't investigate this further without a minimal reproduction.

Closing as non-actionable.
(If you still think this is a bug in `@angular/service-worker`, feel free to open a new issue, providing all the necessary info, including a minimal reproduction.)

**Closed by gkalpak** 2018-08-05 13:10 UTC
Labels: comp: service-worker

**Comment by jvitor83** [comment] 2018-08-05 20:14
@gkalpak 
Ok. I will try to investigate this.
Just one question: Is this a All or None situation? I mean, if one file can't be updated (whatever the situation it is), the app don't update _(the cache don't get updated)_? My guess is that it doesn't update. Is this correct?

**Comment by gkalpak** [comment] 2018-08-06 08:41
Yes, that is correct. If there is a hash mismatch (even if it is in one file only), the whole manifest (aka `ngsw.json`) is considered invalid and the SW enters a degraded mode where it only serves existing clients (with the previous (good) version of the app). New clients will not be served by the SW at all, until a good manifest (aka `ngsw.json`) is detected, that doesn't result in hash mismatch or other errors.

**Comment by shabbir-dhangot** [comment] 2019-01-21 04:08
Hi @gkalpak , We are facing related issue some what described earlier. App is not updating. Its loading previous version of application. Now problem is website is not at all loading because we deleted older files. How can we fix that? Any Idea

**Comment by gkalpak** [comment] 2019-01-21 10:45
Sounds like the same as #28114 (which we are still trying to figure out).
