### ISSUE TITLE
speed up ssr ideas

### ISSUE THREAD

**Issue by sod** [angular/angular#46719] opened 2022-07-06 10:55 UTC
On hackernews right now is a thread about a new javascript runtime bun (https://news.ycombinator.com/item?id=31993429 / https://bun.sh).

This issue is in no way meant to look into bun. But instead look at what interesting ideas jarred sumner brings to the table. As expected there are a few low hanging fruits that could speed up @angular/cli or ssr a hole lot.

Like doing request to json natively instead of by the javascript framework:
> `Bun` has optimized functions for reading data from a ReadableStream. Using these will be faster than doing it manually.

see https://twitter.com/jarredsumner/status/1544614190417006592

Or a new api to incrementally generate a giant string faster
> ArrayBufferSink is a fast API for incrementally writing strings, ArrayBuffer, or Uint8Array into a new ArrayBuffer. This is part of what makes React SSR faster in Bun.

see https://twitter.com/jarredsumner/status/1544614183840276484

Would just be nice to know that you and the V8 are inspired by new ideas, that is all :). Just the timing feels perfect as you said you wanna look into angular/universal in Q3/Q4 2022.

Feel free to close this issue.

**Comment by muhamedkarajic** [comment] 2022-07-16 13:54
Please make this a thing :)

**Comment by rip222** [comment] 2022-10-12 14:39
imagine webpack replaced by bun in angular

**Comment by jastraberg** [comment] 2023-01-07 23:52
I made a duplicate but its great to know there are others who think Angular should look into Bun.

**Comment by derSoerrn95** [comment] 2023-09-04 19:09
+1

**Comment by Yberion** [comment] 2023-09-06 17:57
(Sorry for the ping)

@dgp1130 On https://github.com/angular/angular-cli/issues/24490 you were wondering about metrics, @arturovt made an article regarding this subject, Bun and Angular SSR, this could interest you as there's a benchmark.

- https://dev.to/arturovt/bootstrapping-angular-server-side-rendering-in-bun-579l
- https://github.com/arturovt/bun-angular-universal

cc @alan-agius4 @pkozlowski-opensource

**Comment by dgp1130** [comment] 2023-09-06 18:43
This is an interesting article for sure. Definitely seems like Zone.js is the main challenge. I'm not sure what the root problem is, but if Bun doesn't support patching `setImmediate`, then I'm not sure how much Zone can really do to work around that. A goal of signals work is to better support Zoneless applications, which might help a bit there.

One thing we are hoping to move towards in Angular is making the framework less "weird" with respect to cloud providers, edge workers, JS runtimes, etc. We've already started this with improvements like native ESM on the server, bundle size improvements, and `fetch` support in `HttpClient` (which [I recently talked](https://www.youtube.com/live/0Y9SWsDd1IQ?si=F22YWeFOe1WffY4u&t=1692) about on a livestream). There will probably be more fixes like these in the future to smooth over rough edges like this. It should be possible to run Angular SSR just like any other JavaScript application on Bun, Deno, or any other JS runtime without any special hacks or caveats for Angular.

Regarding the original comment, where we can take advantage of performance improvements in specific environments we definitely should, though I don't think we're quite at that point for Bun when users need to turn off Zones entirely :sweat_smile:. The main challenge is that we'd likely want to avoid any hard dependencies on APIs from alternative runtimes.

I'm going to close this issue for now just since it isn't really actionable in the short term. We definitely do keep an eye on the rest of the JavaScript ecosystem and want to do what we can to make Angular as broadly compatible and fast as possible.

**Closed by dgp1130** 2023-09-06 18:43 UTC
Labels: area: server, needs: discussion

**Comment by sod** [comment] 2023-09-07 13:01
I tried bun for our ssr, but it's not that much faster. After all, 95% of time spent is running angular javascript. We already don't use zone.js, so that was not a deal breaker.

We managed to cut ssr rendering by 70% though by bootstrapping individual routes ahead of time with mocked data. So for the real request it only does a single `update ngrx with new data` + `applicationRef.tick()` to update the app. Kinda like angular also would if you navigate from page 1 to page 2 via pagination. So ssr now responds in ~25ms. This technique needs loots of memory if you keep a few applications warmed up and rdy. But it's a good tradeoff to make.

**Comment by CMiksche** [comment] 2023-09-08 23:16
> This is an interesting article for sure. Definitely seems like Zone.js is the main challenge. I'm not sure what the root problem is, but if Bun doesn't support patching `setImmediate`, then I'm not sure how much Zone can really do to work around that. A goal of signals work is to better support Zoneless applications, which might help a bit there.

Bun supports `setImmediate`. See https://bun.sh/docs/runtime/nodejs-apis#setimmediate

Just today the first stable was released which fixed a lot of issues, keeping in mind that the article we are talking about was made with a old version, this decision to close the issue is too early in my opinion - we should try out if this issue persists with the new stable version.

Jarred Sumner really seems to move fast, so referencing a older article from the time before v1.0 was released isn't wise when making a decision...

**Comment by arturovt** [comment] 2023-09-09 07:10
@CMiksche no one said that Bun doesn't support `setImmediate`. The mentioned thing is that Bun doesn't support _patching_.

**Comment by eteruel-paymefy** [comment] 2023-09-19 23:46
Please make this a thing :)

**Comment by chakrachi** [comment] 2023-09-22 13:36
yes please!!

looking forward to this
all optimizations a-go!

**Comment by davidroth** [comment] 2023-09-28 14:46
> I tried bun for our ssr, but it's not that much faster. After all, 95% of time spent is running angular javascript. We already don't use zone.js, so that was not a deal breaker.
> 
> We managed to cut ssr rendering by 70% by bootstrapping individual routes ahead of time with mocked data. So for the real request it only does a single `update ngrx with new data` + `applicationRef.tick()` to update the app. Kinda like angular also would if you navigate from page 1 to page 2 via pagination. So ssr now responds in ~25ms. This technique needs loots of memory if you keep a few applications warmed up and rdy. But it's a good tradeoff to make.

@sod Could you please give some details on how this can be implemented?

**Comment by sod** [comment] 2023-09-28 15:05
> @sod Could you please give some details on how this can be implemented?

Step 1: We treat ssr as a synchronous, deterministic template engine. It is not allowed to do any requests. The data it needs to render the view is given to it as a giant object. The same object the app in the browser will use as well for the initial request. Like you may do in a traditional ssr setup `BrowserModule.withServerTransition(...)` where ssr sends the initial data it collected to the client. In our setup we do this data collection in our own business logic layer.

Step 2: The entire application treats `window` as an observable. Even though it under normal circumstances never changes. 

Step 3: Now Step 1, feeding the app the initial state via `window` and Step 2, the initial state being updatable, you can see how you could store this initial state object somewhere on disk. Now rewrite your SSR to bootstrap an application ahead of time and feed it the initial state you stored to disk. When a request comes along you use this already rendered application and update it with the new global object and trigger a single `applicationRef.tick()` for angular to update everything to the new content. 

Given that not much changes if you are on the same page (e.g. header and footer are identical, all the services and ngrx effects are dependency injected and ready, all the required components and styles are in the DOM). So in best case what `applicationRef.tick()` does is replace some product names, prices and pictures and the page is done.
