### ISSUE TITLE
QueryList

### ISSUE THREAD

**Issue by sante85** [angular/angular#15728] opened 2017-04-03 15:00 UTC
**I'm submitting a ...**  (check one with "x")
```
[ X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
QueryList<UsersWizardComponent>

this.userWizardQuery.changes
            .subscribe((comps: QueryList<UsersWizardComponent>) => {
                if (comps.first) { //elementRef 

**Expected behavior**
this.userWizardQuery.changes
            .subscribe((comps: QueryList<UsersWizardComponent>) => {
                if (comps.first) { //UsersWizardComponent

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**
I expect that comps.first return class instance instead of elementRef (as in angular 2.4.10 )

**Please tell us about your environment:**

* **Angular version:**
4.0.1

* **Browser:** 
all 
* **Language:** 
typescript 2.2.2
* **Node (for AoT issues):** `node --version` =   
6.9.1

**Comment by sante85** [comment] 2017-04-03 15:19
plunker is complex. i have

 @ViewChildren("dataTable")
    public dataTableQuery: QueryList<GenericTableComponent>;

    @ViewChild(GenericTableComponent)
    protected _dataTable: GenericTableComponent;

and in html
<generic-table #dataTable [gtSettings]="configObject.settings"
                                           [gtFields]="configObject.fields" [gtData]="sessions"></generic-table>

in ngAfterViewInit(){
 this.dataTableQuery.changes.subscribe((comps: QueryList<GenericTableComponent>) => {
         if (comps.first) {
           ........
         }
});

}

**Comment by DzmitryShylovich** [comment] 2017-04-03 15:29
> plunker is complex

Try to isolate the root cause. We don't need your real code. We have a lot of issues to look at, the easier you make it for us the more likely we will be able to get to the bottom and have a fix for you.

**Comment by sante85** [comment] 2017-04-03 15:39
Ok, but problem is simply:
dataTableQuery.changes.subscribe((comps: QueryList<GenericTableComponent>) => {

**return elementRef instead GenericTableComponent instance**.

if you could see it right away as it is a simple problem

**Best Regards**

**Comment by Toxicable** [comment] 2017-04-03 15:42
@sante85 could you make a small plunkr demonstrating the above code in isolation?

**Comment by sante85** [comment] 2017-04-03 15:47
plunkr support angular4?

**Comment by Toxicable** [comment] 2017-04-03 15:50
Yes. Here is a template: https://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5

**Comment by sante85** [comment] 2017-04-03 16:00
https://plnkr.co/edit/jUt4TAr0TSf9Xmv6pHsY?p=preview

**Comment by Toxicable** [comment] 2017-04-03 16:03
@sante85 your plunkr is throwing errors unrelated to this issue, please correct them then post it again

**Comment by sante85** [comment] 2017-04-03 16:09
problem in plunker is not clear. code it's ok....

**Comment by Toxicable** [comment] 2017-04-03 16:12
@sante85 open up your console, it says that `ReferenceError: ViewChildren is not defined`

**Comment by sante85** [comment] 2017-04-03 16:20
ok... to go

**Comment by Toxicable** [comment] 2017-04-03 16:24
@sante85 huh? can you give me a link? did you hit save on your old one?

**Comment by sante85** [comment] 2017-04-03 16:28
yes
https://plnkr.co/edit/jUt4TAr0TSf9Xmv6pHsY

**Comment by Toxicable** [comment] 2017-04-03 16:28
@sante85 it's still throwing the same error

**Comment by sante85** [comment] 2017-04-03 16:31
no errors for me re-check

**Comment by DzmitryShylovich** [comment] 2017-04-03 16:32
@sante85 you didn't save your changes

**Comment by sante85** [comment] 2017-04-03 16:33
ok. i not save

**Comment by mhevery** [comment] 2018-04-10 22:59
closing as no clear repro steps

**Closed by mhevery** 2018-04-10 22:59 UTC
Labels: comp: core & compiler, state: Need repro
