### ISSUE TITLE
[Doc feature request] Availability of PDF and HTML to download for Documentation

### ISSUE THREAD

**Issue by PingPongSet** [angular/angular#41558] opened 2021-04-10 21:36 UTC
# 📚 Docs or angular.io bug report

### Description

 A clear and concise description of the problem...
Is it possible to provide PDF and HTML to download for the Documentation section?

### What's the affected URL?**
 https://angular.io/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by petebacondarwin** [comment] 2021-04-11 14:26
This is a duplicate of #19459, which I will reopen since it has some interest. Although I still think that we will not implement this.

**Closed** 2021-04-11 14:27 UTC
Labels: comp: docs-infra

**Comment by PingPongSet** [comment] 2021-04-11 14:34
@petebacondarwin
Thanks.
One reason is that it tells me how long it will take to learn each section based on a PDF. 

This is easier to use on other scenarios.

I cannot commnet on the link below because it is locked.
https://github.com/angular/angular/issues/19459#event-4578604697

**Comment by petebacondarwin** [comment] 2021-04-11 14:44
Sorry I forgot to unlock it when I re-opened it!
