### ISSUE TITLE
Angular 4 app broken in IE 11 and Edge

### ISSUE THREAD

**Issue by anilchinnu21** [angular/angular#17843] opened 2017-06-29 14:39 UTC
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[X] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Angular 4 application broken on IE 11 and Edge. app-root is not getting replaced and I get the below error in console.
"Uncaught (in promise): Error: Invalid pointer

Error: Invalid pointer

   at nrWrapper (http://localhost:4200/authcallback:19:17804)
   at BrowserPlatformLocation.prototype.replaceState (http://localhost:4200/vendor.bundle.js:143464:13)
   at PathLocationStrategy.prototype.replaceState (http://localhost:4200/vendor.bundle.js:89385:9)
   at Location.prototype.replaceState (http://localhost:4200/vendor.bundle.js:89071:9)
   at Anonymous function (http://localhost:4200/vendor.bundle.js:150607:25)
   at Anonymous function (http://localhost:4200/vendor.bundle.js:58271:25)
   at SafeSubscriber.prototype.__tryOrUnsub (http://localhost:4200/vendor.bundle.js:59237:13)
   at SafeSubscriber.prototype.next (http://localhost:4200/vendor.bundle.js:59184:17)
   at Subscriber.prototype._next (http://localhost:4200/vendor.bundle.js:59124:9)
   at Subscriber.prototype.next (http://localhost:4200/vendor.bundle.js:59088:13)"

## Expected behavior

Application should run fine on IE11/Edge as it works perfectly fine in Chrome and Firefox.

## Please tell us about your environment

<pre><code>
Angular version: 4.0.0

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ X] IE version 11
- [X ] Edge version 38.14393.1066.0
 
For Tooling issues:
- Node version: XX 
- Platform: 

Others:

</code></pre>

**Comment by veke** [comment] 2017-07-03 18:08
Do you have polyfills in place?

**Comment by anilchinnu21** [comment] 2017-07-04 08:19
This is what I have in polyfills.ts file
`import 'core-js/es6/symbol';
import 'core-js/es6/object';
import 'core-js/es6/function';
import 'core-js/es6/parse-int';
import 'core-js/es6/parse-float';
import 'core-js/es6/number';
import 'core-js/es6/math';
import 'core-js/es6/string';
import 'core-js/es6/date';
import 'core-js/es6/array';
import 'core-js/es6/regexp';
import 'core-js/es6/map';
import 'core-js/es6/set';
import 'core-js/es6/reflect';

import 'core-js/es7/reflect';
import 'zone.js/dist/zone';`

**Comment by edoc-dokopp** [comment] 2017-07-07 17:30
Got the same problem, but not in normal IE11, but in an embedded version of IE11.
I got all the polyfills activated, and every npm is up to date.

![image](https://user-images.githubusercontent.com/29098040/27969221-539d870a-634a-11e7-9c96-1313c339aacc.png)

Since fighting it for days I tried different solutions and one guides me to the suggestion that it's a timing problem of loading the polyfills.

**Error reproduction -> Tour of Heroes**
I used the tour of hereos app for testing and debugging because routing seems to be the problem.
There is no problem with a blank new "ng new app".
Because my app runs in an embedded version of ie11 i can't use any console.

So I implemented an error handler:

![image](https://user-images.githubusercontent.com/29098040/27969237-66df8e76-634a-11e7-9210-9bac8b4e78ae.png)

When I just do the alert, the error pops up twice every time i load the script.
When I do the document.write, the page just shows the error **and on next load the error is gone and everything works just fine.** _After resetting the cache, the problem is there again so it's reproducable._

Hope that helps in any way.

**Comment by bastienlemaitre** [comment] 2017-07-19 15:14
Same problem but after IdentityServer authentication with this package : [angular-oauth2-oidc ](https://github.com/manfredsteyer/angular-oauth2-oidc)

![error - internet explorer](https://user-images.githubusercontent.com/11610748/28374611-9652f742-6ca5-11e7-9399-3050eec6d84f.png)

Any idea to solve this issue ?

**Comment by edoc-dokopp** [comment] 2017-07-20 09:11
After long hours of searching I found a workaround for the problem at our specific environment (embedded IE).
The problem was a registry key in this folder:

`HKLM\SOFTWARE\Wow6432Node\Microsoft\Internet Explorer\MAIN\FeatureControl\FEATURE_BROWSER_EMULATION`

There is a key for every application which uses the embedded browser - for example:

![image](https://user-images.githubusercontent.com/29098040/28409295-8536af04-6d3a-11e7-83e5-9f1e5c50ecd4.png)

Here I found some information about the specific values:
[web-browser-control-specifying-the-ie-version](https://weblog.west-wind.com/posts/2011/may/21/web-browser-control-specifying-the-ie-version)

The setting to 11001 means:

> **11001 (0x2AF9)**
> Internet Explorer 11. 
> Webpages are displayed in IE11 Standards mode, regardless of the !DOCTYPE directive.

In our case I had to lower the value to 10000 => IE - Version 10 and use the meta-tag to activate the edge mode and everything works fine.

Registry-Command:
`[HKLM\SOFTWARE\Wow6432Node\Microsoft\Internet Explorer\MAIN\FeatureControl\FEATURE_BROWSER_EMULATION] XYAPPLICATION.EXE=int:10000`

My suggestion: 
The IE has a problem with any doctype / meta-tag / polyfill or whatever and jumps into "quirks mode".
As I pointed out before - if you block the page with document.write after the error, reload, everything works fine with the exact same settings (11001).

Hope that helps anyone or gets the team closer to a solution.

**Comment by augustbend** [comment] 2017-11-14 15:02
Having the same problem here. We had to reduce the number properties in the object that is passed to the router and it seems to do the trick just fine.

**Comment by kchiragowni** [comment] 2018-01-16 12:23
@augustbend  can you elaborate what is the number property to reduce?
Thanks

**Comment by jonnyaeast** [comment] 2018-10-03 09:49
As a 

> Same problem but after IdentityServer authentication with this package : [angular-oauth2-oidc ](https://github.com/manfredsteyer/angular-oauth2-oidc)
> 
> ![error - internet explorer](https://user-images.githubusercontent.com/11610748/28374611-9652f742-6ca5-11e7-9399-3050eec6d84f.png)
> 
> Any idea to solve this issue ?

We had this exact problem, as someone said it is caused by the URL being too long because of the JWT token, which breaks in IE when the router attempts to handle it.

As a workaround we created an auth guard and handled all of the auth callback inside of it. This way it occurs before the router attempts to redirect and therefore IE has no awareness of the long URL, assuming your post-auth redirect is to a shorter URL.

**Comment by deding** [comment] 2018-10-03 22:06
@jonnyaeast I’ve run into the same problem.  Can you share the details of your auth guard workaround?

**Comment by jonnyaeast** [comment] 2018-10-04 08:30
> 
> 
> @jonnyaeast I’ve run into the same problem. Can you share the details of your auth guard workaround?

So assuming you have a route "/authCallback?token=somereallylongjwtstringofhundrededsofcharacters"

Router:

`{ path: 'authCallback', canActivate:[AuthCallbackGuard], component: HomePage }`

Guard:

```
export class AuthCallbackGuard implements CanActivate {
canActivate(
    next: ActivatedRouteSnapshot,
    state: RouterStateSnapshot): Observable<boolean> | Promise<boolean> | boolean {
        this.handleLogin();     
        return false;
  }

  handleLogin(): void {
  //Parse out the token, do something with it and redirect to the logged in page
}}
```

**Comment by joel-kr** [comment] 2018-10-18 07:44
> Same problem but after IdentityServer authentication with this package : [angular-oauth2-oidc ](https://github.com/manfredsteyer/angular-oauth2-oidc)
> ![error - internet explorer](https://user-images.githubusercontent.com/11610748/28374611-9652f742-6ca5-11e7-9399-3050eec6d84f.png)
> Any idea to solve this issue ?

I ran into the same Issue. But after a lot of researches i found this Issue with another Workaround: https://github.com/angular/angular/issues/22709#issue-304204666

> Workaround
Adding the following line in the index.html of the Angular app helps to avoid throwing the exception.
window.history.replaceState = function (){ console.log('Empty stub for history.replaceState()') };

As @AKlaus described i just edited my index.html File like this and this solved my Issue.
```html
<meta http-equiv="x-ua-compatible" content="ie=edge">
  <script>
    window.history.replaceState = function (){ console.log('Empty stub for history.replaceState()') };
  </script>
```

**Comment by pkozlowski-opensource** [comment] 2019-03-07 14:38
Sounds like cases reported were related to angular-oauth2-oidc  so closing it here.

**Closed by pkozlowski-opensource** 2019-03-07 14:38 UTC
Labels: comp: core & compiler, freq2: medium, severity3: broken, type: bug/fix
