### ISSUE TITLE
ActivatedRoute documentation does not mention data, params fields as of 4.2.5. 

### ISSUE THREAD

**Issue by ggranum** [angular/angular#17952] opened 2017-07-06 09:50 UTC
## I'm submitting a ...
<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[ ] Bug report 
[ ] Feature request
[X] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
https://angular.io/api/router/ActivatedRoute (as of version 4.2.5): No mention of data and params observables. 

## Expected behavior
the 'data' and 'params' fields should be documented, but are only mentioned in the summary example code. 

Interestingly enough, the fields are documented in the route_state.d.ts file.

<pre><code>
Angular version: 4.2.5
</code></pre>

**Comment by gkalpak** [comment] 2017-07-06 10:22
Duplicate of #17669 (in spirit). Will be fixed by #17857: https://pr17857-9b44880.ngbuilds.io/api/router/ActivatedRoute

**Closed by gkalpak** 2017-07-06 10:22 UTC
