### ISSUE TITLE
when you run `ng test --code-coverage`, angular cli tool will depend on `istanbul-instrumenter-loader` loader, which cannot recognize decorator syntax。From your code：

### ISSUE THREAD

**Issue by argelj289** [angular/angular#39417] opened 2020-10-25 07:30 UTC
this fix did not work for me:

when you run `ng test --code-coverage`, angular cli tool will depend on `istanbul-instrumenter-loader` loader, which cannot recognize decorator syntax。From your code：
```
constructor(protected injector : Injector)
	{
		this.http = injector.get<HttpClient>(HttpClient);
	}
```
Because the loader cannot recognize decorator syntax, the inject `injector` will be `undefined`.
That's why you will see errors:

> Cannot read property 'get' of undefined

I think it is a bug of angular cli not angular, but if you want to make it work now, you can add one line code in tsconfig.spec.json:
```
"compilerOptions":
	{
		"outDir": "./out-tsc/spec",
		"target": "es5",    --- add this line
	},
```
Let me know if i misunderstand this question.

_Originally posted by @Zuckjet in https://github.com/angular/angular/issues/34959#issuecomment-578837981_

**Comment by JoostK** [comment] 2020-10-25 09:42
Duplicate of #31337.

**Closed by JoostK** 2020-10-25 09:42 UTC
