### ISSUE TITLE
Undefined can't be used as ngValue for select option without extra treatment

### ISSUE THREAD

**Issue by mexx** [angular/angular#8852] opened 2016-05-26 06:48 UTC
**I'm submitting a ...**
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

**Current behavior**
`undefined` or `null` value can't be used as `ngValue` for a select option.

**Expected/desired behavior**
Ability to use `undefined` or `null` value as `ngValue` for a select option without workaround shown in the reproduction below.

[Steps to reproduce and a minimal demo of the problem](http://plnkr.co/59brW0sOKSfUduojBUpm).

***My investigations***
Currently in [`_getOptionValue`](https://github.com/angular/angular/blob/6da79673c207b41b117737dcfcb302d17a0fb8ab/modules/%40angular/common/src/forms/directives/select_control_value_accessor.ts#L90-L93) function the fact that the key is not present in the map of options and the fact that the value for an existing key is undefined are treated the same. But only the former case should be treated like it's done currently, when the key is present in the map of options the corresponding value should be returned regardless of what it is.

**Comment by kara** [comment] 2016-10-12 20:14
Thanks for reporting! Looks like a dupe of https://github.com/angular/angular/issues/10349. Will keep that one open since there is more activity.

**Closed by kara** 2016-10-12 20:14 UTC
Labels: comp: forms
