### ISSUE TITLE
9.0.0-rc.8 build failed

### ISSUE THREAD

**Issue by sysmat** [angular/angular#34720] opened 2020-01-10 09:33 UTC
# 🐞 bug report

### Affected Package
@angular/compiler": "9.0.0-rc.8

### Is this a regression?
Yes, the previous version(9.0.0-rc.7) in which this bug was not present was: ....

### Description
Not building anymore

## 🔬 Minimal Reproduction
Issues that don't have enough info and can't be reproduced will be closed.

You can read more about issue submission guidelines here: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue
-->

## 🔥 Exception or Error
<pre><code>
WARNING in Entry point 'ng-ace-editor' contains deep imports into 'node_modules/brace/theme/monokai'. This is probably not a problem, but may cause the compilation of entry points to be out of order.

ERROR in The target entry-point "ng-ace-editor" has missing dependencies:
 - brace/theme/monokai

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
@angular-devkit/architect         0.900.0-rc.8
@angular-devkit/build-angular     0.900.0-rc.8
@angular-devkit/build-optimizer   0.900.0-rc.8
@angular-devkit/build-webpack     0.900.0-rc.8
@angular-devkit/core              9.0.0-rc.8
@angular-devkit/schematics        9.0.0-rc.8
@ngtools/webpack                  9.0.0-rc.8
@schematics/angular               9.0.0-rc.8
@schematics/update                0.900.0-rc.8
rxjs                              6.5.4
typescript                        3.6.4
webpack                           4.41.2
</code></pre>

**Anything else relevant?**

**Comment by gkalpak** [comment] 2020-01-10 10:09
Could you please check whether the error happens with the build artifacts from [here][1] (to see if #34695 will fix the issue)? If the error still happens, could you create a minimal reproduction?

[1]: https://circleci.com/gh/angular/angular/579375#artifacts/containers/0

**Comment by benelliott** [comment] 2020-01-10 16:13
@gkalpak Not the OP but I still encounter this error when I use the artifacts you mentioned.

For me, the issue is as follows:

- App A imports internal library B
- B bundles up the libraries `cleave.js` and `@types/cleave.js` as private dependencies (whitelisted in the NgPackagr config)
- a module in B transitively exposes an import of `cleave.js/options`, which is an entrypoint that is only provided by `@types/cleave.js` and not by the "real" `cleave.js` 

This results in the following error when trying to compile App A with Ivy:

```
The target entry-point "[library-B]/[secondary-entrypoint]" has missing dependencies:
 - cleave.js/options
```

I will try to provide a reproduction soon if I have time.

**Comment by petebacondarwin** [comment] 2020-01-13 22:00
@benelliott - did you manage to get round to creating a reproduction of this issue?

**Comment by petebacondarwin** [comment] 2020-01-13 22:59
I looked into this... the cause of the problem is that the `DtsDependencyHost` does not find paths that are in the `@types` folder as "deep" imports. This can be resolved by enhancing the `ModuleResolver` to be able to accept "prefixes" (on top of the "postfixes" that it can already accept). The `DtsDependencyHost` could then provide `@types` as a potential prefix to consider when looking for deep imports.

I'll update my PR tomorrow.

**Comment by sanjeevprasad** [comment] 2020-01-14 05:35
I can confirm this bug... i am getting the same error..
i also tried installing `brace` using `yarn add brace` but no luck.
 issue still exist.
is there any workaround for now?

**Comment by benelliott** [comment] 2020-01-14 09:59
@petebacondarwin I hadn't yet, would that still be useful to you?

**Comment by petebacondarwin** [comment] 2020-01-14 10:42
Don't worry @benelliott - I managed to reproduce your problem locally.
@sanjeevprasad - did you try using the artifacts from my PR? See https://app.circleci.com/jobs/github/angular/angular/579375/artifacts

**Comment by petebacondarwin** [comment] 2020-01-14 13:45
@benelliott - I have updated my PR to fix this issue.

**Comment by benelliott** [comment] 2020-01-14 13:52
@petebacondarwin Thanks, is there an easy way for me to download the shippable artifacts and give it a spin?

**Comment by petebacondarwin** [comment] 2020-01-14 14:00
Yep - try these https://app.circleci.com/jobs/github/angular/angular/585697/artifacts

**Comment by benelliott** [comment] 2020-01-14 14:49
Sorry - both of your links give me a 404

**Comment by gkalpak** [comment] 2020-01-14 14:55
Try https://circleci.com/gh/angular/angular/585697#artifacts/containers/0.
<sub>(Pete has different URLs, because he has opted into the new CircleCI UI, so if you haven't opted in, you get 404s 😞)</sub>

**Comment by petebacondarwin** [comment] 2020-01-14 15:23
Sorry both :-)

**Closed** 2020-01-15 18:25 UTC
Labels: comp: ngcc, state: Needs repro, type: bug/fix

**Comment by benelliott** [comment] 2020-01-15 19:08
Thanks @petebacondarwin, I just tried your artifacts and can confirm they fixed my build issues.

**Comment by luthor77** [comment] 2020-01-29 17:02
I'm getting the same error as the creator of the issue, since rc.8, first with mobiscroll. So I created this issue: https://github.com/acidb/mobiscroll/issues/475
Now that the issue is resolved I'm getting with @fullcalendar.

So I don't know if I should create an issue @fullcalendar too, and all other librarys that eventually can get the same error, or here.

> ERROR in The target entry-point "@fullcalendar/angular" has missing dependencies:
>  - @fullcalendar/core/types/input-types
>  - @fullcalendar/core/datelib/env
>  - @fullcalendar/core/datelib/duration
>  - @fullcalendar/core/datelib/formatting
>  - @fullcalendar/core/datelib/date-range
>  - @fullcalendar/core/datelib/locale
>  - @fullcalendar/core/validation
>  - @fullcalendar/core/structs/event-source

With me, this error only occurs if Ivy is enabled, or, always with ng test.

**Comment by petebacondarwin** [comment] 2020-01-30 10:02
@luthor77  - would you be able to create a minimal repository that reproduces this error and share it in a new issue here?

**Comment by luthor77** [comment] 2020-01-30 13:11
@petebacondarwin https://github.com/angular/angular/issues/35054
