### ISSUE TITLE
Resolver not called when upstream params change

### ISSUE THREAD

**Issue by slubowsky** [angular/angular#12942] opened 2016-11-17 15:28 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Resolvers are not called when an upstream route param changes. This is wrong as the parent route param may obviously have significance. e.g
company/1/employee/2
company/2/employee/2
Employee 2 is not the same employee even though the param is 2 in both cases.

**Expected behavior**

The resolver would be called and could fetch the proper data which would then be made available to component as route data

**Minimal reproduction of the problem with instructions**

See https://github.com/slubowsky/resolve-issue
Run the app (ng serve). Click on the links to navigate. Going to / from "1 and 1" to / from either of the others results in resolver being called and message being logged to the console. Going between "1 and 2" and "2 and 2" does not. Resolver is never called. Component would not be updated.

**What is the motivation / use case for changing the behavior?**

Its currently broken. Cant keep component current with route using a resolver and route.data.

Thinking about this a bit more, can it be that the design is such that resolvers are only meant to be called before a component is shown for the first time (to prevent "blank" component), but once a component is showing, the resolver and route.data are never meant to be called and updated even if the route changes?
If this is the case, then I need to handle the exact same thing, getting route params and fetching the appropriate data, in two places. First get the params and fetch the data in the resolver and subscribe to ActivatedRoute.data for the first update, and then do the same thing again whenever the route changes.

Bigger problem is that I have no way of knowing the route changed (ActivatedRoute.params is not updated either). I suppose we could subscribe to router events and get snapshot or something on NavigationEnd but things are getting very messy, multiple paths instead of one, cut and pasted code, etc... I hope this is just a bug...

Plus it does seem to be called when this route segments parameters change so things are really getting strange. Lots of different scenarios that all should be exactly the same but instead are all different...

**Please tell us about your environment:**

Windows 10, Visual Studio Code, Angular-cli 1.0.0-beta.20-4

* **Angular version:** 2.0.X

2.2.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 Only tried Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 2.0.10

* **Node (for AoT issues):** `node --version` =

**Comment by vicb** [comment] 2016-12-01 22:35
The current behavior is by design.

Both strategies are reasonable in some use cases - it just happen that we have implemented the one that does not make sense in your use case.

What you can do is to inject the activatedRoute and load the Employee in your component.

**Comment by slubowsky** [comment] 2016-12-01 23:02
I don't understand. How can this not be a bug? What is the "other strategy" that has the resolver not being called to resolve on a radically changed route?
On some route changes the resolver is called, on others it isn't. This is inconsistent and definitely not documented anywhere that I have seen.
I'm also not sure what you mean by injecting the activated route, I'm pretty sure that route.params behaves the same as route.data and is not called in this case either. Other then listening for navigation end - which is definitely a hack, I don't see how this can be made to work.
It is almost impossible to use the router in a sophisticated way currently (at least with resolvers). As soon as you think you have it working, you discover that in some cases the router behaves differently and your carefully crafted design falls apart.

**Comment by klinki** [comment] 2016-12-02 14:07
@vicb I'm sorry but I'm really tired of hearing "The current behavior is by design" and similar sentences. Could you please provide us The Design, so we would know how are we supposed to use router?

Currently there are so many pitfalls and I think there are quite a lot of people experiencing them. And surprisingly, most of them are by design.

**Comment by slubowsky** [comment] 2016-12-02 15:21
You guys are doing a great job giving me great software for free and don't owe me anything but I'm really struggling here.
I am constantly amazed by how the router behaves. I never know if its a router bug (they seem to be multiplying lately) or some strange design that I'm not privy to.
If the router supports resolvers to resolve data before the component is activated then it should support them. I shouldn't have to guess as to whether a particular routing change will result in my resolver being called.
Between this and several other still open bugs I have wasted lots of time trying to get relatively simple workflows to work efficiently in all cases.
https://en.wikipedia.org/wiki/Principle_of_least_astonishment

**Comment by montella1507** [comment] 2016-12-05 17:36
I am sorry i have to say, but that is really terrible design. 

Really guys.. 

detail?id=5  -> detail?id=6 are totally different "routes" so it should call ALL resolvers again.. If it won't call the resolvers again, it is totally USELESS.

**Comment by montella1507** [comment] 2016-12-05 17:51
The same for RouteGuards...... I want to check if someone can open some user detail and route guard is not called.. again not usable at all...

**Comment by montella1507** [comment] 2016-12-05 18:02
I think the behavior is defined here:
https://github.com/angular/angular/blob/master/modules/%40angular/router/src/url_handling_strategy.ts#L43
https://github.com/angular/angular/blob/master/modules/%40angular/router/src/router.ts#L634

So maybe it is possible to use another one? Another urlhandling strategy

**Comment by montella1507** [comment] 2016-12-05 18:21
I have found this code in Router:
  if (!shallowEqual(future.params, curr.params)) 

in my older version of angular.. it is changed in the latest one

**Comment by slubowsky** [comment] 2016-12-05 19:04
Really strange. I saw some comments here suggesting that perhaps a  custom  UrlHandlingStrategy  could be used to work around this design / bug but those comments are no longer here. Really curious to know what the recommended approach is to make the router usable in this common use case. (Also still curious as to what the use case is where this is not the desired implementation)

**Comment by vicb** [comment] 2016-12-07 18:53
@slubowsky I actually discussed this more with @vsavkin last week and it sounds reasonable to re-run the resolver when the parent parameters change. Do you want to take a stab at a PR ?

**Comment by slubowsky** [comment] 2016-12-07 19:41
@vicb I'd like to try that but probably wouldn't be able to even start to look at it for at least a week or two (out of office part time and covering for others the rest). Ill check back when I get freed up and if it hasn't yet been addressed I'll make an attempt. Thanks!

**Comment by vicb** [comment] 2016-12-08 00:29
>  Ill check back when I get freed up and if it hasn't yet been addressed I'll make an attempt

Great thanks !

**Comment by matsko** [comment] 2017-01-11 18:16
Closed by https://github.com/angular/angular/commit/d4d3782d455a484e8aa26ec9a57ee2b4727bc1da

**Closed by matsko** 2017-01-11 18:16 UTC
Labels: comp: docs, comp: router, type: feature

**Comment by slubowsky** [comment] 2017-03-31 18:01
Never tested this fix as by the time it landed I had moved on to another implementation but now finding fix was not sufficient to actually be useful. Rather then reopening this old issue, created another as a continuation addressing the still broken parts.
See https://github.com/angular/angular/issues/15677
