### ISSUE TITLE
Broken link in angular.io

### ISSUE THREAD

**Issue by ljharb** [angular/angular#38393] opened 2020-08-10 03:12 UTC
# 📚 Docs or angular.io bug report

### Description

https://angular.io/guide/template-syntax#safe-navigation-operator / https://github.com/angular/angular.io/blob/281efb9ca0d278b36e2e7fa0850a807d7005e50b/public/docs/ts/latest/guide/template-syntax.jade#L1773 used to work.

Now, it's https://angular.io/guide/template-expression-operators#the-safe-navigation-operator----and-null-property-paths / https://github.com/angular/angular/blob/5b31a0a2942c50059cac4c7ccb92047a50473347/aio/content/guide/template-expression-operators.md#the-safe-navigation-operator----and-null-property-paths

## 🔬 Minimal Reproduction

Visit the old URL, see the 404.

### What's the affected URL?**
https://angular.io/guide/template-syntax#safe-navigation-operator

### Reproduction Steps**
Visit https://angular.io/guide/template-syntax#safe-navigation-operator.

### Expected vs Actual Behavior**
Expected behavior: [cool URLs don't change](https://www.w3.org/Provider/Style/URI), and any URL that has ever worked should work forever.

### Anything else relevant?
This prompted https://github.com/tc39/proposal-optional-chaining/pull/140, which will fix the issue for new visitors to the docs, but the old URL should 301 redirect indefinitely.

**Comment by JoostK** [comment] 2020-08-10 07:04
Thanks for reporting! [There are some redirect rules](https://github.com/angular/angular/blob/445ac15a785121cd7de099a33a3fded0c8b9ab83/aio/firebase.json), but this change has not been listed as a redirect.

**Comment by JoostK** [comment] 2020-08-10 18:42
After looking at #38399 (thank you @Nishikoh!) I don't think we can actually address this issue, see https://github.com/angular/angular/pull/38399#pullrequestreview-464475899 for details.

A safer reference to the docs would have been to use the versioned URL of `https://v10.angular.io/`, such that refactoring of docs content would have a smaller impact on the URLs. I realize this situation is exactly point 1 of https://www.w3.org/Provider/Style/URI; the versioned URL would reduce the chance of inaccurate links in the future.

**Comment by ljharb** [comment] 2020-08-10 19:00
@JoostK it seems like it could still be somewhat addressed (albeit not properly with a 301/302) with a clientside JS redirect, or, the old page statically just containing a link, so that users at least don't get a 404 and only have one extra click to get to the new content?

**Comment by JoostK** [comment] 2020-08-10 19:04
@ljharb Yeah I was thinking of a JS redirect as well, however I don't think that's very common practice? I am confused by the 404 you mention, as I do end up at a page where "Template expression operators" is present as a link. Are you seeing something different? Could it be a stale response from a service worker?

**Comment by ljharb** [comment] 2020-08-10 19:29
oops, you're right; i think i was just misremembering :-/ since there's a page there with a link, and a JS redirect would indeed be odd, i think that the only real actionable thing here would be to add an explicit section for `#safe-navigation-operator` that says "this page has moved" or something - if not something like that, I guess this can be closed.

**Comment by gkalpak** [comment] 2020-08-13 13:36
I too feel that a JS redirect would be a little far-fetched. I am generally all for not breaking URLs, but sometimes it is hard to improve the docs layout without breaking some URLs (especially those containing hash-fragments). Hopefully the benefits of the simplified layout outweight the invonvenience of broken links in this case.

As mentioned above, either https://v9.angular.io/guide/template-syntax#safe-navigation-operator or https://v10.angular.io/guide/template-expression-operators#safe-navigation-operator should work (and are more futue-proof).
<sub>
I just noticed that `v10.angular.io` redirects to `next.angular.io` instead of `angular.io`. This is a bug and should be fixed soon.
</sub>

**Closed by gkalpak** 2020-08-13 13:36 UTC
Labels: comp: docs-infra

**Comment by Splaktar** [comment] 2020-08-13 23:18
@gkalpak and @aikidave you don't think that a section with "this page has moved" at the bottom of the page, matching the hash-fragment is an approach that we should take here?

**Comment by sonukapoor** [comment] 2020-08-14 01:50
I agree. I think it would be useful to have that a section with a link to the new page on the broken page.

**Comment by aikidave** [comment] 2020-08-14 04:31
I am a little confused about what the issue is. We had a topic that we separated into smaller topics. Now we have a link that isn't broken, per se (it doesn't return a 404 as I can see), it just leads you to the wrong topic.

The ideal situation would be to fix the broken link so it points to the right topic, but I'm not sure where this broken link exists. The next best option would be a redirect, but it seems that isn't a valid option.

Adding a section to an existing topic only to say: "If you are looking for this other topic, you should go here" is not a good idea. At the very least, it would be a nightmare to maintain. And, as George points out, we have to be able to move topics around, or our documentation experience will never improve.

Sorry if I am coming across a little strong here, but I really don't think a section that points people to another topic makes sense. Happy to consider other options, however!

**Comment by gkalpak** [comment] 2020-08-20 16:07
> @gkalpak and @aikidave you don't think that a section with "this page has moved" at the bottom of the page, matching the hash-fragment is an approach that we should take here?

We are not talking about one link here. OP mentioned one particular link, but there are basically many links (one for each of the ~70 sub-section headers) that got broken. I doubt that having a section with all potentially broken links will be of much help for readers, not to mention maintaining it will be unwieldy.

I am a proponent of keeping URLs unchanged (and often argue for it internally), but as mentioned above sometimes we just have to bite the bullet :grin:

**Comment by aikidave** [comment] 2020-08-20 17:01
> I am a proponent of keeping URLs unchanged (and often argue for it internally), but as mentioned above sometimes we just have to bite the bullet 😁

To me, the priority is creating a documentation experience that is intuitive, discoverable, and accurate. That usually necessitates rewriting sections--if not entire topics!

That said, I'm not advocating that we should change the documentation around all the time--that's also not a great experience. :)

There are ways we could solve this, if we deem it important enough. For example, I've worked at companies where every link was a pointer. Something like this: `nglink.com/id=12345`. When a user clicked on that link, a service routed them to the appropriate destination. There was a separate interface where you could create or update those links as needed. That's one solution. Another would be to update the URL for all documentation links to use the version-specific address (v10.angular.io instead of just angular.io, for example). That way, when people copied a link, they'd be relevant to that specific version, which (probably?) wouldn't change all that much.

In the end though, bookmarks to specific topic sections are always a bit tricky. Content changes all the time, and it's hard to keep links as current as possible. Most of the teams I've worked with have accepted that, as long as the link didn't result in a 404 error, it was fine/good enough.

Just a few thoughts!

**Comment by ljharb** [comment] 2020-08-20 17:09
I'd say if you don't want to ensure a topic link works forever, it'd be best not to make it linkable in the first place.

**Comment by Splaktar** [comment] 2020-09-09 00:25
> Content changes all the time

This has been somewhat true in the past, but so far we've been able to mostly keep the links stable so that people's books and training material don't break too badly. There has never been a policy that `as long as the link didn't result in a 404 error, it was fine/good enough` in the past.

If we're going to have a new policy where these are breaking in minor releases and not only on majors, then we may want to communicate that more widely. We may also want to recommend to GDEs and authors to use version specific links so that their content doesn't get broken (assuming we are only going to break links in majors).

Another concern is that we use redirects for the current release i.e. `https://v10.angular.io/docs` goes to `https://angular.io/docs`. So it would take some careful effort (and advanced knowledge) for an author to specifically add `v10.` in front of all of their links (when speaking about new content).

**Comment by ljharb** [comment] 2020-09-09 00:26
Unless you jettisoned the concept of canonical unversioned URLs entirely and make the versioned one the canonical source?

**Comment by aikidave** [comment] 2020-09-09 03:13
It is, in the end, up to the person who linked to a given topic (or topic section) to make sure that those links remain current. I hold angular.io accountable to that standard as well. If I were to write a topic that linked to a wikipedia article, a README for a different open source project--even a link to our own content--it's up to me (or the people responsible for the documentation) to ensure that those links stay up to date.

Documentation for content for Microsoft, Amazon, Google, and many others, is constantly evolved. If that evolution involves removing or renaming a topic, it's expected that you create a redirect for that topic. But that doesn't apply to sections within that content. Why? I am not sure. But, as far as I've seen, it's rarely been an issue.

Some additional thoughts: 

- When Angular releases a new version, I would expect that anyone who wrote a book or created a course would want to check to see if their material is still up to date. Checking for any broken links in your content seems a reasonable act of due diligence.

- Recall an early situation that I brought up. What if I rewrite a section to make it more relevant or easier to understand. But, as a side effect of that change, the content doesn't match original. Now the link still works, but the content isn't relevant. That's not something that anyone can predict, unless we don't update the documentation ever again.

It seems like the best course of action for anyone who wants to link to any documentation set is to make sure the link points to a specific version. We could convey this to the community at large, perhaps like this:

> If you plan on linking to angular.io content, be sure to use a link that is specific to an Angular version. For example, link to v10.angular.io/guide/routing instead of angular.io/guide/routing. This practice helps avoid broken links in your content that can occur as the Angular documentation improves.

Do you have any suggestions about where this content might live?

**Comment by ljharb** [comment] 2020-09-09 06:38
@aikidave that's not accurate; the principles of the web itself is that it is up to every content provide to ensure that *every URL, without exception* works for eternity: https://www.w3.org/Provider/Style/URI

You can abandon that ethical/moral obligation as you like, but it is *never* on the linker, it is always and only on the provider.

**Comment by Splaktar** [comment] 2020-09-29 23:03
> It is, in the end, up to the person who linked to a given topic (or topic section) to make sure that those links remain current. 

This isn't possible for content authors who publish written content. I also don't think that this follows the general spirit of the web, community expectations, or past precedent. This approach also calls into question all of the work that has been done and continues to be done to write redirects, write tests for those redirects, etc.

That said, I think that it's perfectly valid to break these kinds of links in new major releases. I think one of the main concerns here was breaking the link in a minor/patch release.

> It seems like the best course of action for anyone who wants to link to any documentation set is to make sure the link points to a specific version. We could convey this to the community at large, perhaps like this:
> 
> > If you plan on linking to angular.io content, be sure to use a link that is specific to an Angular version. For example, link to v10.angular.io/guide/routing instead of angular.io/guide/routing. This practice helps avoid broken links in your content that can occur as the Angular documentation improves.
> 
> Do you have any suggestions about where this content might live?

![Screen Shot 2020-09-29 at 18 51 47](https://user-images.githubusercontent.com/3506071/94624615-d8baee00-0284-11eb-9e0a-b03dbccbfd53.png)

I would suggest that it would be appropriate to be listed under "Angular Style and Usage" in the "Reference" section. It might be helpful to have a nav section on "Referencing and Using the Docs" including a section for content authors on referencing for published material, referencing for digital material, and a section for docs users with info on how to access the docs offline, and links to the docs translated in other languages.
