### ISSUE TITLE
ci/circleci: integration_test flake: fails with "No usable sandbox! Update your kernel"

### ISSUE THREAD

**Issue by pkozlowski-opensource** [angular/angular#29132] opened 2019-03-06 13:45 UTC
Example of failing job: https://circleci.com/gh/angular/angular/232545?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

Started to happen on 05/03/2019, initially spotted by @alxhub in https://circleci.com/gh/angular/angular/231317?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by alan-agius4** [comment] 2019-03-06 14:08
Note: this is also happening in the CLI repo

Example of failing job: https://circleci.com/gh/angular/angular-cli/42868#tests/containers/2

**Comment by devversion** [comment] 2019-03-11 19:53
My stance is that this was related to some issues within CircleCI. Since we run our jobs using Docker images and therefore don't have control of the underlying kernel, we might have hit an outdated/misconfigured kernel. e.g. linux user namespacing not enabled (needed for sandbox).

The log implies that this is related to the user namespacing as Chromium's `Zygote` seems to throw the exception. e.g.

```
[0306/133123.725257:FATAL:zygote_host_impl_linux.cc(116)] No usable sandbox!
```

I also wasn't able to reproduce the issue today after running at least 10 re-runs with SSH (with the hope of hitting the issue). I think we should wait and see if we hit new instances of the issue. My guess is that the affected CircleCI host node has been either updated/reconfigured or just removed and we no longer run into the issue.

**Comment by kara** [comment] 2019-03-11 22:29
OK, let's close this for now and re-open if we see new instances. cc @pkozlowski-opensource

**Comment by gkalpak** [comment] 2019-03-12 09:38
I just saw one: [239444][1]

Not sure if it should be taken "seriously", since both GitHub and CircleCI are experiencing issues.
- GitHub is reporting issues with Notifications/Webhooks and I am also experiencing instability in the webapp.
- CircleCI is affected by the GitHub issue and I am also getting intermittent "Server is overloaded, try later" errors (which might indicate a broader issue).

I am not reopening for now, but will keep an eye on it 👁 

[1]: https://circleci.com/gh/angular/angular/239444

**Comment by devversion** [comment] 2019-03-12 10:08
Thanks @gkalpak. Please keep an eye one it!

I'm thinking about checking with the CircleCI support team in the meanwhile. They should have more insight into the available host nodes.

**Comment by devversion** [comment] 2019-03-12 18:42
Here is another instance I just spotted on `master`: https://circleci.com/gh/angular/angular/240239. Will have another look.

**Closed** 2019-03-21 16:09 UTC
Labels: comp: build & ci, severity5: regression
