### ISSUE TITLE
Memory Leak/Detached Objects

### ISSUE THREAD

**Issue by mdraganza** [angular/angular#47748] opened 2022-10-12 16:59 UTC
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

Recently we discovered a browser memory leak in our Angular application. It is large enough that it will crash the browser after about 10 minutes of navigating between screens. It is particularly bad on grids. The more rows, the larger the leak. It seems to be triggered by Material attributes like matSort and mat-menu. I have tried the latest version of Edge and Chrome. Please use Edge, since you can see the leak by the Detached Elements tab in DevTools. You can also use More Tools/Browser task manager to monitor the memory and watch it slowly rise as you click back and forth between the links on the page.

I have provided a small sample application that reproduces the leak. The description in the repo explains how to run the app and reproduce the leak. Thanks.

### Please provide a link to a minimal reproduction of the bug

https://bitbucket.org/insightinvestments/open-repo/src/master/

### Please provide the exception or error you saw

```true
The application crashes and an Out of Memory error is displayed on the browser.

Note: The sample app provided does not produce a large enough leak to crash the browser, unless you were to click back and forth thousands of times.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 14.2.5
Node: 16.17.1
Package Manager: npm 8.15.0
OS: win32 x64

Angular: 14.2.5
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1402.5
@angular-devkit/build-angular   14.2.5
@angular-devkit/core            14.2.5
@angular-devkit/schematics      14.2.5
@angular/cdk                    14.2.4
@angular/material               14.2.4
@schematics/angular             14.2.5
typescript                      4.7.4
```

**Comment by JoostK** [comment] 2022-10-22 19:30
I do observe one short-lived memory leak in `@angular/animations`, but it resolves itself during the first change detection cycle so I don't think it's actually the cause of your issue.

Other than that, I do not see a persistent leak of DOM nodes between many navigations:

<img width="628" alt="image" src="https://user-images.githubusercontent.com/123679/197359052-49ca1f16-abda-4787-938a-35bafd5e2b91.png">

(JS heap in blue, DOM nodes in green)

The number of DOM nodes increases until a garbage collection cycle is able to release the DOM nodes, resulting in the two drops above.

**Comment by mdraganza** [comment] 2022-10-24 21:54
Here is the initial memory reading from Browser Task Manager with my test app started:

![image](https://user-images.githubusercontent.com/14850094/197636018-231ec006-f9ff-4ba9-afd0-b45098a58250.png)

I clicked back & forth on the links 10 times and waited 5 minutes:

![image](https://user-images.githubusercontent.com/14850094/197636262-a01aa9d9-3e08-40d8-8a5a-75dec0020552.png)

As you can see, there is a 700K increase.

This is the Detached Elements tab in Edge. After performing the X10 action, I clicked on the Get Detached Elements icon (highlighted circle) and the trash. There is a detached node.

![image](https://user-images.githubusercontent.com/14850094/197636917-dfe27d6b-d584-4c9c-ad28-6a2538e4138e.png)

**Comment by JoostK** [comment] 2022-10-24 22:08
That single element might be from the leak I observed. You can check by clicking on the leases link when that page is already open, as it triggers a change detection run that enables GC of the leaked element.

**Comment by JoostK** [comment] 2022-10-25 16:58
The retainer path shown in that screenshot is the same as the one I observed, but I am certain that this one _does_ disappear after a change detection cycle.

**Comment by JoostK** [comment] 2022-10-25 17:10
A minimal change you could try that should get rid of this particular retainer is to edit `node_modules/@angular/animations/fesm202/browser.mjs` to change

```diff
- if (this._whenQuietFns.length) {
+ while (this._whenQuietFns.length) {
```

This isn't a complete fix as some more changes would be needed to cover all scenarios, but that should resolve this particular retainer path in the reproduction.

I don't expect this to be sufficient to actually address the memory leak entirely though, as I can't reproduce a long-term leak that you describe you're observing.

**Comment by jessicajaniuk** [comment] 2023-01-06 00:45
Closing this as we haven't seen any other reports and haven't been able to reproduce this issue persistently outside of a single CD cycle.

**Closed by jessicajaniuk** 2023-01-06 00:45 UTC
Labels: area: animations, memory leak, P3, needs: clarification
