### ISSUE TITLE
Error: Cannot resolve type entity i1.CdkConnectedOverlay to symbol

### ISSUE THREAD

**Issue by ohabash** [angular/angular#47945] opened 2022-11-02 20:26 UTC
### Which @angular/* package(s) are the source of the bug?

animations, compiler-cli, core, Don't known / other

### Is this a regression?

Yes

### Description

All the sudden without any major dependency changes my app has a bug in the dev server. All devs on my team have the same problem. (build seems to be fine)

1. Start dev server with `ng serve`
2. Note that local host works and app compiled successfully 
3. Make any change to any file (for example app.component.html)
4. an error occurs on the server logs (see pic)

![Screenshot 2022-11-02 at 3 20 32 PM](https://user-images.githubusercontent.com/15847500/199594640-0e292af4-fefb-471d-8c2f-44828e6b8186.png)

### Please provide a link to a minimal reproduction of the bug

f

### Please provide the exception or error you saw

```true
./apps/fornida-dash/src/app/app.component.ts - Error: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
Error: Cannot resolve type entity i1.CdkConnectedOverlay to symbol
    at /Users/omar/Sites/nx-fornida/node_modules/@ngtools/webpack/src/ivy/loader.js:81:18



✖ Failed to compile.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.0.3
Node: 14.19.3
Package Manager: npm 6.14.17
OS: darwin x64

Angular: 13.0.2
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, material, platform-browser
... platform-browser-dynamic, router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.18
@angular-devkit/build-angular   13.3.9
@angular-devkit/core            13.3.9
@angular-devkit/schematics      13.3.9
@angular/cli                    13.0.3
@angular/fire                   6.1.5
@angular/pwa                    13.3.9
@schematics/angular             13.3.9
ng-packagr                      13.3.1
rxjs                            7.4.0
typescript                      4.4.4
```

**Comment by JoostK** [comment] 2022-11-02 21:52
This error is likely due to module hoisting in your setup, or the lack therefore. A probably cause is that some packages are incomplete in their `dependencies`/`peerDependencies` configuration, resulting in a module layout that does not provide the necessary dependencies for all packages.

This error occurs when a `.d.ts` file is included into your program for which on of the imports does not resolve to a module, resulting in the symbol information to be unavailable.

Your best approach to finding the file that is causing the error would be to search file `i1.CdkConnectedOverlay` in your project directory (including `node_modules`), or to search for the location in `node_modules/@angular/compiler-cli` where that error is reported and inserting `console.log(type.getSourceFile().fileName);` directly before it, such that running the compiler again will then output which file causes the error. You'll then find which import fails the resolve, likely a line such as

```ts
import * as i1 from `@angular/cdk/overlay`;
```

That particular module specifier fails to resolve from that file, likely because `@angular/cdk` is not specified as dependency of the package where the file is part of.

**Comment by alxhub** [comment] 2022-12-09 00:43
Closing as no reproduction has been provided.

**Closed by alxhub** 2022-12-09 00:43 UTC
Labels: hotlist: error messages, needs reproduction, area: compiler, P4
