### ISSUE TITLE
HTML element remains disabled if FormControl is enabled

### ISSUE THREAD

**Issue by kuceraf** [angular/angular#44997] opened 2022-02-07 15:27 UTC
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

No

### Description

Angular does not remove HTML disabled Attribute from input element when:

- input element is linked to formControl in disabled state
- user action causes that new instance of formControl is created (and replace the old one) in enabled state
- input element remains disabled (disabled attribure is not removed from HTML element)
(changing input element from enabled to disabled in this way works well)

Example:
For HTML template
`
<input [formControl]="testControl">
{{testControl.disabled}}
<button (click)="toggleDisable()">Toggle</button>

`

this toggle function cause the issue (after button click input remain disabled event if new form control is enabled):
`
 toggleDisable() {
    const newForm = new FormControl()
    newForm.setValue(this.testControl.value)
    if(this.testControl.disabled) {
      newForm.enable()
    } else  {
      newForm.disable()
    }
    this.testControl = newForm
  }
`

If I do not creaate new instance of form control (only modify the existing) - it work:
`
 toggleDisable() {
    if(this.testControl.disabled) {
      this.testControl.enable()
    } else  {
      this.testControl.disable()
    }
  }
`

### Please provide the exception or error you saw

```true
textarea (or any other input element) keeps disabled atribute when the associate FormControl is enabled
`
<textarea _ngcontent-cyo-c120="" ng-reflect-form="[object Object]" disabled class="ng-untouched ng-dirty ng-valid"></textarea>
`
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular 12.2.2
```

**Comment by AndrewKushnir** [comment] 2022-02-08 05:51
Closing as a duplicate of #35309. Please subscribe to #35309 for further updates. Thank you.

**Closed by AndrewKushnir** 2022-02-08 05:51 UTC
Labels: comp: forms
