### ISSUE TITLE
Decimal Pipe not working with big numbers

### ISSUE THREAD

**Issue by aryanisml** [angular/angular#27049] opened 2018-11-11 03:10 UTC
# 🐞 bug report

### Affected Package
Currently using "@angular/core": "~6.0.8"

### Is this a regression?
NA

### Description
Decimal pipe is not working with big numbers. If I applied decimal pipe on number  919228.9014151045 with precision formatting  '1.0-2'  
it will show the 919 output.  Require the output 919228.90

## 🔬 Minimal Reproduction
https://issuedecimalpipe-zdvvlw.stackblitz.io

## 🔥 Exception or Error
NA

## 🌍  Your Environment

**Angular Version:**

Angular CLI: 6.0.8
Node: 8.12.0
OS: win32 x64
Angular: 6.0.9
... common, compiler, compiler-cli, core, forms, http
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.6.8
@angular-devkit/build-angular      0.6.8
@angular-devkit/build-ng-packagr   0.6.8
@angular-devkit/build-optimizer    0.6.8
@angular-devkit/core               0.6.8
@angular-devkit/schematics         0.6.8
@angular/animations                6.1.10
@angular/cdk                       6.4.7
@angular/cli                       6.0.8
@angular/material                  6.4.7
@ngtools/json-schema               1.1.0
@ngtools/webpack                   6.0.8
@schematics/angular                0.6.8
@schematics/update                 0.6.8
ng-packagr                         3.0.6
rxjs                               6.0.0
typescript                         2.7.2
webpack                            4.8.3

**Comment by trotyl** [comment] 2018-11-11 03:35
Duplicate of https://github.com/angular/angular/issues/23893

**Comment by aryanisml** [comment] 2018-11-11 03:38
> Duplicate of #23893

That defect or issue mostly describe the currency pipe. Newly logged defect talking only decimal pipe rather than any other pipe and it clearly reproduce.

**Comment by sliceofbytes** [comment] 2018-11-11 03:53
The issue in the reproduction is related to the parseFloat not the decimal pipe.

Without the parseFloat it is formatting correctly. https://stackblitz.com/edit/issuedecimalpipe-dd2zob?file=src/app/app.component.ts

**Comment by aryanisml** [comment] 2018-11-11 04:08
> The issue in the reproduction is related to the parseFloat not the decimal pipe.
> 
> Without the parseFloat it is formatting correctly. https://stackblitz.com/edit/issuedecimalpipe-dd2zob?file=src/app/app.component.ts

Yes right. clossing this issue.

**Closed** 2018-11-11 04:09 UTC
