### ISSUE TITLE
Dependency injection with multiple instance of the dependency

### ISSUE THREAD

**Issue by Doublebock** [angular/angular#25074] opened 2018-07-24 17:54 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[X ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
In order for the application to inject a dedicated instance (non-singleton) of a dependency to each component through its constructor the component has to define what the implementation of the dependency is as a provider. This completely removes the ability to have actual dependency injection.

## Expected behavior
(I have researched this and saw the related issue, but if I missed the way to implement the injection non-singleton dependencies, I apologize.)

When a dependency is defined through a provider, the type of resolution, singleton or multiple instances, should be a property of the provider. Such as:

	providers: [
		{ provide: ApiService, useClass: NgHttpApiService, type: 'transient' },
		UserService,     // has ApiService injected for the user management api
		AuthService     // has ApiService injected for the authentication api
		...
	]

Note: 'transient' came from https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-2.1 which seems to have a good implementation of the concept which I use on the API side of my current Angular app.

The goal would be for my UserService, AuthService and others to have a different ApiService implementation for, say, an app that uses jQuery ajax or other http service than Angular's HttpClient.

I think my workaround will not be to define the implementation in the component but have a "provider" service that is injected as a singleton and can then provide dependencies to the components. (I can even use interfaces instead of abstract classes. Plus enables services to work in non-angular apps by eliminating the @Injectable() requirement.)

Side question - when HttpClient is injected into my http api service, is it a singleton? If not, this backs up my need to have that ability too.

I appreciate your consideration of this feature.

**Comment by jotatoledo** [comment] 2018-07-24 19:42
I dont see how adding transient services would help you archive your goal. If you want to simply create a new instance whenever a service is injected, independent of the scope, the first that comes to my mind is to use a `FactoryProvider`:

```
export function apiServiceFactory(...): ApiService {
  return new ApiService(...);
}

providers: [
	{ provide: ApiService, useFactory: apiServiceFactory, deps: [...] }
]
```

> This completely removes the ability to have actual dependency injection.

Hmm? Thats entirely wrong. When you do that, you are just resolving dependencies and binding their lifetime to the component existence. Furthermore clients/consumers of those dependencies in the (hierarchical) scope of the component are provided with the previously named instances.

> Side question - when HttpClient is injected into my http api service, is it a singleton? 

Depends on how you provide it. If you stick to the standard way (importing HttpClientModule) then yes, you inject the same instance of `HttpClient` into every consumer of it.

**Comment by trotyl** [comment] 2018-07-25 02:09
Duplicate of https://github.com/angular/angular/issues/18015

**Comment by vicb** [comment] 2018-07-25 03:56
closing as duplicate

**Closed by vicb** 2018-07-25 03:56 UTC
