### ISSUE TITLE
FormGroup validator has wrong type because type ValidatorFn is not generic

### ISSUE THREAD

**Issue by yelhouti** [angular/angular#47973] opened 2022-11-04 05:04 UTC
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

No

### Description

When creating a validator for a (typed) formGroup, one would expect the validator to have a signature `FormGroup<T> => ValidationErrors | null` and not `AbstractControl => ValidationErrors | null`
Because of the way it s coded now, we need to add a (formGroup as MyFormGroup).controls

### Please provide the exception or error you saw

```true
Property 'controls' does not exist on type 'AbstractControl '.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular: 14.2.3
```

**Comment by Olster** [comment] 2022-11-04 12:10
Seems to be the duplicate of https://github.com/angular/angular/issues/47911

**Comment by dylhunn** [comment] 2022-11-18 00:32
Indeed, this is a dupe of #47911. Thanks for reporting though!

**Closed by dylhunn** 2022-11-18 00:32 UTC
Labels: area: forms, P3, forms: strictly typed
