### ISSUE TITLE
Http clinet response with empty body

### ISSUE THREAD

**Issue by HarelM** [angular/angular#20879] opened 2017-12-08 01:01 UTC
## I'm submitting a...
<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
When a server returns an empty body and no responseType is set promise is rejected.

## Expected behavior
This should be the equivalent of void returning method - it should not fail and should not force me to write `{ responseType: "text" }`.

## Minimal reproduction of the problem with instructions
When server return empty body the following code fails:
httpClient.delete("some url").toPromise()
While this code succeeds:
httpClient.delete("some url", { responseType: "text" }).toPromise()

## What is the motivation / use case for changing the behavior?
Everyone who writes angular would need to know this and write more unneeded boilerplate code.

## Environment

<pre><code>
Angular version:5.0.3

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.9.2
- Platform:  Windows 10

</code></pre>

Keep up the good work!

**Comment by rdzidziguri** [comment] 2017-12-08 01:40
I do not think this is something client-side framework should handle. Imagine situation when consumer of your service is other application or even kind of device which perfectly understands HTTP protocol. What u described is a situation when u return nothing from API and still want it to be handled. I would recommend following more HTTP response code standards rather than relaying on this kind of solution from client-side framework.

**Comment by lukaszsamson** [comment] 2017-12-09 18:32
One of the allowed responses to DELETE is 204 [https://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html](https://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html) which should have an empty body [https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html](https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html). It is highly unexpected that a successful delete should return a rejected Promise in this case.

**Comment by alxhub** [comment] 2017-12-12 23:14
Closing as a duplicate of #19438.

**Comment by alxhub** [comment] 2017-12-12 23:16
Whoops, it's not actually a duplicate.

**Comment by unspike** [comment] 2017-12-13 20:03
@lukaszsamson 
Basically it doesn't matter is that 'delete' or 'post' request.
empty response with status code 200 would fall (Unexpected end of JSON input at JSON.parse) without '{ responseType: "text" }'

**Comment by HarelM** [comment] 2017-12-13 22:04
The bottom line is that I now need to search my entire server communication layer to find all the places where I return an empty body from the server and add this piece of code (`{ responseType: "text" }`).
The migration from `http` to `httpclient` introduced this hazard and I'm still fighting bugs ever since I made this migration... :-/

**Comment by unspike** [comment] 2017-12-13 22:07
@HarelM
Same as i;)

**Comment by isametal88** [comment] 2017-12-14 15:55
Hi guys,
I'm facing the exact same problem. My (huge) application was designed isolating the base http communication in a service, so I may consider myself lucky. Anyway, after this upgrade (from 2.4 to 5.1) there's no way to read the http response in the delete. The actual delete http request works correctly, the server returns no response body but has status 204. What I need is to access to this status and I can't figure out how. Could someone help me out?

**Comment by HarelM** [comment] 2017-12-14 16:44
Have you tried google?
https://angular.io/guide/http#reading-the-full-response
https://stackoverflow.com/questions/46639154/how-can-get-httpclient-status-code-in-angular-4

**Comment by isametal88** [comment] 2017-12-14 20:18
Of course I did. Http Get, Post and Put work perfectly fine like they did before. My trouble is only with delete. I tried to subscribe both as an observable and a promise, but both return null as response.

**Comment by HarelM** [comment] 2017-12-15 14:13
In that case I think you should open a different issue for delete not working with `{observe: 'response'}`.

**Comment by trotyl** [comment] 2018-02-19 12:30
Fixed by #19958?

**Comment by usarskyy** [comment] 2019-06-12 14:54
Hi!

This looks like a serious bug because it breaks communication when client and API are on different domains (in this case browser sends preflight OPTIONS request that returns no content). I created an issue in RxJs repo (see the reference above) but it looks like this is Angular fault.

**Comment by alxhub** [comment] 2020-05-29 20:29
I believe @trotyl is correct, and this was fixed a while back in 503be69af. Closing!

**Closed by alxhub** 2020-05-29 20:29 UTC
Labels: comp: common/http, freq3: high, severity2: inconvenient, type: bug/fix

**Comment by HarelM** [comment] 2020-06-02 11:56
Thanks for the update! I'm using angular version 8 and this issue is fixed there. :-)
