### ISSUE TITLE
Angular Service worker not sending file in 'body' in POST request sometimes

### ISSUE THREAD

**Issue by blackblood19** [angular/angular#29629] opened 2019-04-01 11:39 UTC
# 🐞 bug report
Angular Service worker is not sending file in 'body' in POST request sometimes. It works almost all the time, but, once in a while, I see that the POST request is sent with no file in body. When this happens, it continues to not send the body even after refreshing and disabling the cache. To resolve the issue, I open Application tab in dev tools, and stop and start the service worker, and it starts working, it starts sending file in 'body' for POST request.

### Affected Package
"@angular/service-worker": "^6.1.0"

## 🔬 Minimal Reproduction
I made a simple reproduction, but as I mentioned earlier, it is not reproducible everytime. So, please take some time for me and follow the steps below.

I observed that the problem happens when sending a file (not sure if it happens with any request.'body')

Open https://reproduction.stackbox.xyz/ and select any file. If the backend receives file, browser will display that. If backend does not receive the file, it will display that and this is the issue that we are trying to make it happen. The backend just checks if the file has come and throws if the file is not received.

Reproduction Steps:

- Open the above link, upload any file, you will most probably see that "File was sent successfully".

- Close the tab.

- Now comes the tricky part, Open the link again after an hour, and try uploading a file again. The issue will most probably happen. (It should say 'File not received'. If the issue happens, open the network tab and try uploading a file again, and the issue will happen again. We can see that the request sent by service worker has no body/file. Now, restart the service worker in Application tab, and the issue disappears.)

## 🌍  Your Environment
"@angular/service-worker": "^6.1.0"
"@angular/core": "^6.1.0"

**Comment by gkalpak** [comment] 2019-04-02 19:39
@blackblood19, I've been uploading files for the last couple of days, but everything works fine 😞

**Comment by blackblood19** [comment] 2019-04-03 06:05
Attached the pictures below. The issue is happening continuously to me. The two things that can matter is, 
1) I am not refreshing the website. Service worker is providing the cached files.
2) I am using Google Chrome. 

![reproduction0](https://user-images.githubusercontent.com/10388211/55456106-c7e3da80-5603-11e9-8be6-7b4e55c4e599.JPG)

![reproduction1](https://user-images.githubusercontent.com/10388211/55456115-cfa37f00-5603-11e9-8b05-054b633942c9.JPG)

![reproduction2](https://user-images.githubusercontent.com/10388211/55456119-d4683300-5603-11e9-9c9e-6e0016b95e48.JPG)

**Comment by blackblood19** [comment] 2019-04-03 12:24
I found a more consistent case when the issue is happening. 

1. Open reproduction.stackbox.xyz. Upload a file. It will be uploaded successfully.
2. Close the tab (Window should not close).
3. Reopen the closed tab (Ctrl + Shift + T in windows)
4. Try uploading the file again.

**Comment by gkalpak** [comment] 2019-04-03 15:48
Thx, @blackblood19! With these steps, I can reproduce the issue on Chrome (although not on Firefox - possibly because I didn't try too hard 😇).
It seems that the request reaches the SW without the body, so it is not the SW's doing.

It is either something else in the app (it is hard to investigate with  minified sources) or most likely the browser.
@blackblood19, could you try to create a minimal reproduction and submit a bug report to [Chromium][1]?

[1]: https://www.chromium.org/for-testers/bug-reporting-guidelines

**Comment by blackblood19** [comment] 2019-04-22 05:40
@gkalpak  Thanks for looking into it. Before I go and submit a bug report to Chromium, I do have one question. 

When we are able to reproduce the issue, the issue disappears if we restart the Service Worker in Application tab of Dev tools. If the problem does not exist in Service Worker, do you have any idea why the issue gets resolved after restarting the service worker?

I can use any help that I can get on this issue. I am stuck on this issue for months now.

**Comment by gkalpak** [comment] 2019-04-23 12:22
@blackblood19, I have no idea why restarting the SW fixes it. Another indication that it might be a browser bug.
(Maybe something related to restoring the state of a closed tab, including its SW container 🤷‍♂️)

**Comment by Karnaukhov-kh** [comment] 2019-04-25 18:48
Reproduced this issue on Android in PWA running in standalone mode (installed from Chrome).

Steps: 
- Remove installed https://reproduction.stackbox.xyz/ PWA if you have it and clear cache in Chrome.
- Go to https://reproduction.stackbox.xyz/ in Chrome.
- Pin to home screen on Android.
- Keep Chrome in the background.
- Open pinned app.
- Upload file from FS or Camera.

Not in 100% of the cases but pretty often you can get the error described above.

Chrome version 73.0.3683.90

Also at my work, we have an app with upload functionality and first upload after PWA was added to home screen fails almost all the time. it's usually enough to re-launch PWA to make this issue disappear for some time.

**Comment by RobARichardson** [comment] 2019-05-08 19:02
We've been seeing this exact same problem for several months too.  Can confirm that the same troubleshooting steps mentioned by @blackblood19 resolve the issue, albeit temporarily until it resurfaces again.

**Comment by gkalpak** [comment] 2019-05-11 13:40
What would be interesting is trying to reproduce this with a "hand-made" service worker script (without `@angular/service-worker`), because I don't think this is Angular-specific.

**Comment by Karnaukhov-kh** [comment] 2019-05-22 11:27
My team just tested it with "hand-made" service worker. Same issue - request body is empty when you try to upload file right after the installation of PWA from Chrome but everything is fine is you install from Samsung Internet.

sw.js
`self.addEventListener('install', function(event) {
    console.log('[Service Worker] Installing Service Worker ...', event);
    event.waitUntil(
        caches.open('start_url').then(function(cache) {
            cache.addAll(['/']);
        })
    );
});

self.addEventListener('activate', function(event) {
    console.log('[Service Worker] Activating Service Worker ...', event);
    return self.clients.claim();
});

self.addEventListener('fetch', function(event) {
    event.respondWith(fetch(event.request));
});
`

Registration code
`platformBrowserDynamic()
    .bootstrapModule(AppModule)
    .then(() => {
        if ('serviceWorker' in navigator) {
            navigator.serviceWorker.register('/sw.js').then(function() {
                console.log('Service worker registered!');
            });
        }
    })
    .catch(err => console.log(err));
`

Browsers - Google Chrome 74.0.3729.157, Samsung Internet 9.2.00.70

`"@angular/service-worker": "^7.2.8",
"@angular/core": "^7.2.8",`

**Comment by gkalpak** [comment] 2019-05-22 17:15
Thx, @Karnaukhov-kh ❤️ I am going to close this issue, since it doesn't seem to be Angular-specific.
(If someone reports it to [Chromium][1], please post the link to the bug report here for future reference.)

[1]: https://www.chromium.org/for-testers/bug-reporting-guidelines

**Closed by gkalpak** 2019-05-22 17:15 UTC
Labels: comp: service-worker, freq1: low, severity3: broken, type: bug/fix

**Comment by Karnaukhov-kh** [comment] 2019-06-12 19:40
You can now bypass Service Worker if you are using `@angular/service-worker: 8+` by adding `{ headers: { 'ngsw-bypass': true }` or query param (haven't tried) to your request. Looks like it fixes the issue.

**Comment by epelc** [comment] 2019-08-07 16:19
I've had this come up where if you upload say a string and a js `File` object through a service worker PUT request it will omit the file field when the service worker generates it's fetch request. Also had it just not send any body at all like everyone else. Restarting the service worker like suggested above seems to fix.

**Comment by benjaminrau** [comment] 2019-08-27 10:31
Altough this seems not to be an Angular issue still people may get here while looking for a solution.
We use Angular 6 and thus cant make use of ngsw-bypass header which is available only in Angular Service Worker 8+.

We solved the issue by modifying the angular service workers onFetch method to not handle requests going to our upload api.

`onFetch(event) {
  if (event.request.url.indexOf('upload') !== -1) {
      return;
  }
  ...
}`

Found this approach here: https://jun711.github.io/web/how-to-listen-for-upload-progress-in-service-worker-and-progressive-web-app/

**Comment by marwesfur** [comment] 2019-09-20 16:08
For the records: Bug report for Chromium can be found here https://bugs.chromium.org/p/chromium/issues/detail?id=988468
