### ISSUE TITLE
Mat-icon gets displayed as text when you click on it or on later versions from the start

### ISSUE THREAD

**Issue by munchkindev** [angular/angular#39364] opened 2020-10-21 12:37 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/material/icon

### Is this a regression?

 Not sure whether this a regression, sorry..

### Description

 
When I implemented my code on Angular 10.0.0.2 the following problem appeared: 
When I clicked on the mat-icon which is inside a span, which is inside a div I get a router redirect event fired and it completes but then the icon just turns into text saying feedback. While trying to reproduce this issue on newest Angular the icon is not displayed in the first place as an icon but rather as text...

## 🔬 Minimal Reproduction

 https://stackblitz.com/edit/angular-ivy-budgg7

## 🔥 Exception or Error
<pre><code>

The icon gets displayed as text.
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

   _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 10.0.0
Node: 12.13.1
OS: win32 x64

Angular: 10.0.2
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1000.0
@angular-devkit/build-angular      0.1000.0
@angular-devkit/build-optimizer    0.1000.0
@angular-devkit/build-webpack      0.1000.0
@angular-devkit/core               10.0.0
@angular-devkit/schematics         10.0.0
@angular/cli                       10.0.0
@angular/material                  10.0.1
@angular/material-moment-adapter   10.2.1
@ngtools/webpack                   10.0.0
@schematics/angular                10.0.0
@schematics/update                 0.1000.0
rxjs                               6.5.5
typescript                         3.9.6
webpack                            4.43.0
</code></pre>

**Anything else relevant?**

I used Chrome Version 86.0.4240.75 for testing the older Angular version and Firefox Developer Edition 82.0b9 for StackBlitz example.

You can see the package version in the StackBlitz.

**Comment by gkalpak** [comment] 2020-10-21 12:57
AFAICT, the problem is that you need to include the Material Icons in your page. For example, add the following in your `index.html`:

```html
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons&display=block" />
```

##
Closing, since everything seems to work as expected (but feel free to continue the discussion below).

**Closed by gkalpak** 2020-10-21 12:57 UTC

**Comment by munchkindev** [comment] 2020-10-21 13:32
Thank you that solved this and a Bug with a search icon as well. Why did it semi-work without the line though?

**Comment by gkalpak** [comment] 2020-10-21 13:54
What do you mean "semi-work"? Also, what does not work on StackBlitz?

**Comment by munchkindev** [comment] 2020-10-21 13:55
By semi-work I mean it kind of works. On the StackBlitz my code with the icon simply does not work.

**Comment by gkalpak** [comment] 2020-10-21 14:13
Sorry, I can't help more without more info. It works for me on StackBlitz.

**Comment by munchkindev** [comment] 2020-10-21 14:15
I mean it got displayed at first as far as you would not click on it which then got transformed to text. 
For me on StackBlitz it doesn't work, but it doesn't matter since in my project it does.
