### ISSUE TITLE
facing less error in angular 12 

### ISSUE THREAD

**Issue by bxdadwhal** [angular/angular#44797] opened 2022-01-23 18:17 UTC
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

i am able to compile the code successfully only facing less-loader error during unit test from npm run test

### Please provide a link to a minimal reproduction of the bug

https://github.com/bxdadwhal/angular12

### Please provide the exception or error you saw

```true
./src/styles.less - Error: Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/less-loader/dist/cjs.js):


Chunk.split is not a function

    at processResult (C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\webpack\lib\NormalModule.js:713:19)
    at C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\webpack\lib\NormalModule.js:819:5
    at C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\loader-runner\lib\LoaderRunner.js:399:11
    at C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\loader-runner\lib\LoaderRunner.js:251:18
    at context.callback (C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\loader-runner\lib\LoaderRunner.js:124:13)
    at Object.lessLoader (C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\less-loader\dist\index.js:54:5)
```

### Please provide the environment you discovered this bug in (run `ng version`)

Angular CLI: 12.2.15
Node: 14.17.3
Package Manager: npm 8.3.0
OS: win32 x64

Angular: 12.2.15
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.15
@angular-devkit/build-angular   12.2.15
@angular-devkit/core            12.2.15
@angular-devkit/schematics      12.2.15
@angular/http                   7.2.16
@angular/material               12.2.13
@schematics/angular             12.2.15
rxjs                            6.6.0
typescript                      4.3.5

**Comment by JoostK** [comment] 2022-01-23 19:38
Duplicate of angular/angular-cli#22548

**Closed by JoostK** 2022-01-23 19:38 UTC
