### ISSUE TITLE
docs(aio): AOT Caveats on the Guide

### ISSUE THREAD

**Issue by snewell92** [angular/angular#18508] opened 2017-08-03 16:19 UTC
## I'm submitting a...
<pre><code>
[ ] Regression
[ ] Bug report
[ ] Feature request
[x] Documentation issue or request
</code></pre>

## Current behavior
[AOT guide](https://angular.io/guide/aot-compiler) in the docs don't mention caveats like the ones [rangle lists](https://github.com/rangle/angular-2-aot-sandbox).

## Expected behavior
The guide should link to the rangle aot caveats, or list them, or link to another resource. *If another resource doesn't exist currently, just link to the rangle repo* since it already exists and covers most cases. Then when an internal document comes into being, link that one.

## Minimal reproduction of the problem with instructions
After reading the [AOT guide](https://angular.io/guide/aot-compiler), I developed with JIT (as the guide suggested), and then ran into errors with my pipeline because of the AOT compile errors on private and protected properties.

## What is the motivation / use case for changing the behavior?
Better educated user base on AOT compilation.

**Comment by dherges** [comment] 2017-08-04 06:02
See also #17533 (dupe?)

Or see also mystory on [writing AoT-friendly apps](https://medium.com/spektrakel-blog/angular-writing-aot-friendly-applications-7b64c8afbe3f)

**Comment by snewell92** [comment] 2017-08-04 13:16
Hmm, I searched for AOT but that didn't come up, my bad. This is totally a dupe of the aformentioned issue, and that one is of higher quality. Thanks for the extra link though!

Maybe consider this the quick fix to the other issue's main request of full fledged walk through.

**Comment by gkalpak** [comment] 2017-08-04 14:31
Closing as a duplicate of #17533.

**Closed by gkalpak** 2017-08-04 14:31 UTC
Labels: comp: aio, comp: docs
