### ISSUE TITLE
EventEmitter.subscribe() typings don't match with Subject.subscribe()

### ISSUE THREAD

**Issue by JeanMeche** [angular/angular#48621] opened 2023-01-02 11:15 UTC
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

`EventEmitter` provides its own typings for the `subscribe` method.  ([source](https://github.com/angular/angular/blob/27da7338ea8f3bf5336d77ed1877cfa6a1974d52/packages/core/src/event_emitter.ts#L92))

This particularly bothering when passing a `PartialObserver` (`{next: ..., error: ...}`) because it infers `any` for the parameter of the `next` callback.

Maybe @petebacondarwin has more insights on why this has been done so. 

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-2rhpaf?file=src%2Fapp%2Fapp.component.ts

**Comment by pkozlowski-opensource** [comment] 2023-01-02 11:23
This topic was discussed in the past (ex.: https://github.com/angular/angular/issues/6934.) and we've got #29016 to track typings of subscribe. But generally speaking we do _not_ want to advertise EventEmitter as being `Subject` - this is an internal implementation detail.

Closing as a duplicate of #29016

**Closed by pkozlowski-opensource** 2023-01-02 11:23 UTC
