### ISSUE TITLE
Lazy Loaded routes should load child when redirectTo is applied to the parent/ container route.

### ISSUE THREAD

**Issue by ndcunningham** [angular/angular#14692] opened 2017-02-24 04:23 UTC
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

https://plnkr.co/edit/0CVaxhqRY3DILSVVtZjd?p=preview

**What is the motivation / use case for changing the behavior?**

Container components loading it's children within it's own context after being lazily loaded.

if route `/foo` is served to the browser the router should redirect to `/foo/bar` and load bar inside it's parent named foo

**Please tell us about your environment:**

Win 10 x64, 
VSCode

* **Angular version:** 2.0.X

2.4.x

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 2.0.10

**Comment by tmeneau** [comment] 2017-03-10 21:33
If I'm understanding the original issue correctly, I've just encountered the same issue. I thought I'd add some additional context (let me know if I'm describing something different, @ndcunningham).

#### Repro

I built a separate reproduction case here since I've found debugging router issues easier to debug from local projects than from plunkers: (https://github.com/tmeneau/angular2-router-lazy-loaded-default-route). The reproduction project includes instructions for reproducing the behavior.

#### Use Case

Just to add to @ndcunningham's use case, we have a protected lazy-loaded dashboard that acts as the default route *if* the user has an authenticated session (checked against a server on initial page load). The dashboard itself has a route that should be activated by default, but we can't seem to get any of the dashboard's child routes to activate by default on initial page load without making the default child route's empty ('').

#### Details

Just to include the details here:

* this is only reproducible on application initialization (the first router navigation);
* this issue is reproducible when trying to use `redirectTo` for the lazy-loaded component's default child, but not if the lazy-loaded component's child is explicitly mapped to the blank path ('').

Example lazy-loaded child configuration (copied from the [reproduction project's lazy-routing.module.ts](https://github.com/tmeneau/angular2-router-lazy-loaded-default-route/blob/fe855dbb223814825a9ff6b8fca528e1a1e1f813/src/client/app/components/lazy/lazy-routing.module.ts):

```typescript
const lazyRoutes: Routes = [
  { 
    path: '', 
    component: LazyComponent,
    children: [
      { path: '', pathMatch: 'full', redirectTo: 'default-child' },
      { path: 'default-child', component: DefaultChildComponent },
      { path: 'other-child', component: OtherChildComponent }
    ] 
  }
]
```
###### Expected Behavior

1. user opens a browser page for /
2. router redirects to /lazy/default-child

###### Actual Behavior

1. user opens a browser page for /
2. router redirects to /lazy (no child activated)

**Comment by ndcunningham** [comment] 2017-03-11 14:06
@tmeneau Thanks for your contextual details. I solved my issue but removing the `pathMatch: 'full'` on the parent level and adding prefix.

Like this:
```
const routes: Routes = [
  {
    path: '', component: LazyParentComponent, pathMatch: 'prefix',
    children: [
      {
        path: '', pathMatch: 'full', redirectTo: 'child'
      },
      {
        path: 'child', component: LazyChildComponent
      }
      ]
  }
];
```
See full version here: http://plnkr.co/edit/Pw0YT39ZKWvV2nCr3Vit?p=preview

**Comment by shinde-prasad** [comment] 2017-07-25 13:38
@ndcunningham Nice solution. thnx :)

**Comment by jasonaden** [comment] 2017-12-19 19:11
Closing as resolved.

**Closed by jasonaden** 2017-12-19 19:11 UTC
Labels: comp: router, type: bug

**Comment by riturajratan** [comment] 2018-03-21 09:50
what should i do if i want to load module at the place of component.
for more see https://stackoverflow.com/questions/41716883/how-to-load-child-route-by-default-in-angular-2

**Comment by riturajratan** [comment] 2018-03-21 09:51
https://stackoverflow.com/questions/48878754/how-to-load-child-route-by-default-with-lazy-loading-in-angular-2    if we do it from module then its not working
