### ISSUE TITLE
Environment based routes at build

### ISSUE THREAD

**Issue by phillipzada** [angular/angular#26807] opened 2018-10-28 21:25 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[X] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
Is it possible to have static environment based configuration for lazy loaded modules? This will help with prototyping and A/B testing

e.g.

```
  {
    path: 'person/:key',
    component: ModuleWrapperComponent,
    loadChildren: environment.beta ? '@libs/person-v2/src#PersonModule' : '@libs/person/src#PersonModule'
  },
```

I've tried:

- using the replace configuration in angular.json but i was really complex
- using environment variable in the import statement

```
@NgModule({
  imports: [RouterModule.forChild(environment.beta  ? betaRoutes : routes)],
  exports: [RouterModule]
})
export class RoutingModule {}
```

**Comment by trotyl** [comment] 2018-11-01 03:04
Duplicate of https://github.com/angular/angular/issues/15305

**Comment by jasonaden** [comment] 2018-11-27 23:49
Closing as duplicate

**Closed by jasonaden** 2018-11-27 23:49 UTC
Labels: comp: router
