### ISSUE TITLE
ngIf on upgraded and transcluded element

### ISSUE THREAD

**Issue by willyboy** [angular/angular#18529] opened 2017-08-04 17:38 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When I use *ngIf on an ngUpgraded transcluded component, the component doesn't render (regardless of the value of the ngIf expression). 

## Expected behavior

*ngIf should remove the transcluded component when its expression is falsey and do nothing when it's truthy.

## Minimal reproduction of the problem with instructions

```
<my-angularjs-component>
    <my-transcluded-component *ngIf="true">Stuffity stuff</my-transcluded-component>
</my-angularjs-component>
```
```

.component('myAngularjsComponent', {
            template: '<div ng-transclude="myTranscludedComponent"></div>',
            transclude: {
                myTranscludedComponent: 'myTranscludedComponent'
            }
        });
```

## What is the motivation / use case for changing the behavior?

Should be able to use ngIf on transcluded elements.

## Environment

<pre><code>
Angular version: 4.3.3

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

I have a hypothesis... *ngIf wraps the code in a <template> tag. Would that template tag hide <my-transcluded-content> from the code that looks for content to transclude?

**Comment by vicb** [comment] 2017-08-04 20:20
Please add a plunker reproducing the issue.

**Comment by gkalpak** [comment] 2017-08-05 07:57
@willyboy, (if you are using `@angular/upgrade/static`) you can use [this plnkr][1] as a starting point.

[1]: http://plnkr.co/edit/BXA3Onj8CkbmfuDKXu1N?p=preview

**Comment by willyboy** [comment] 2017-08-08 18:12
@gkalpak Thanks for the starter! Saved a ton of time.
@vicb  Sorry for the delay. Been swamped. Here's the reproduction: http://plnkr.co/edit/KmDTyJBMJjPJTIag8Qnz?p=preview

You'll notice that if you remove the ngIf=true from the transcluded element, the text shows up.
<thing *ngIf="true">My banana has a first name</thing>

**Comment by gkalpak** [comment] 2017-08-08 20:19
Interestingly, [we have a test][1] for this exact scenario 😕 
Looking into it.

[1]: https://github.com/angular/angular/blob/6f2038cc852fb31e5cdbab2f15cd3ab80bf3dac7/packages/upgrade/test/static/integration/upgrade_component_spec.ts#L2499-L2572

**Comment by gkalpak** [comment] 2017-08-08 23:37
Looking closer, our test does not put the `ngIf` on the transcluded element, but on its child. Unfortunately, there doesn't seem to be a way for ngUpgrade to retrieve the information about transcluded content, if structural directives (such as `ngIf`) have removed the content. (Happy to be proven wrong :smiley:)

As a work-around, you can use the structural directive on a child node, like this:

```html
<thing><span *ngIf="true">My banana does this and that.</span></thing>
```

**Comment by willyboy** [comment] 2017-08-25 19:51
@gkalpak Yup! That's the workaround I was using (sorry for the delayed reply, I'm not getting notifications for some reason).

**Comment by gkalpak** [comment] 2017-08-26 14:12
Closing this, since there doesn't seem to be a way to solve this. It is not possible for ngUpgrade to access the necessary info.

**Closed by gkalpak** 2017-08-26 14:12 UTC
Labels: comp: upgrade/static, severity2: inconvenient, type: bug, workaround2: non-obvious
