### ISSUE TITLE
Boolean Input Properties should accept true/false strings

### ISSUE THREAD

**Issue by valentingavran** [angular/angular#47521] opened 2022-09-22 13:47 UTC
### Which @angular/* package(s) are relevant/related to the feature request?

common

### Description

Let's assume we have a component with a few boolean input properties. At the moment we need to use square brackets to pass static `true` or `false` values to it.

```html
<my-component [ripple]="true" [state]="false" [block]="true" [titleVisible]="true"></my-component>
```

### Proposed solution

Instead, it would be much more convenient if a string to boolean conversion is performed by default for boolean input properties:

```html
<my-component ripple="true" state="false" block="true" titleVisible="true"></my-component>
```

And it would be even better if existent boolean input properties without a value were assumed to be `true` by default:

```html
<my-component ripple state="false" block titleVisible></my-component>
```

### Alternatives considered

I tried to do this myself on a larger project. I created a `BooleanLike` type and used a pipe to convert it to boolean. However, this is not maintainable. New developers in the project are not aware that this type exists. It is only project specific. Because of that, the pipe is often forgotten and strange behavior occurs.

`my-component.component.ts`
```typescript
@Input() public titleVisible: BooleanLike = false;
```

`my-component.component.html`
```html
<div *ngIf="titleVisible | booleanLikeToBoolean" class="title">My title</div>
```

`boolean-like-to-boolean.pipe.ts`
```typescript
import { Pipe, PipeTransform } from '@angular/core';
import { BooleanLike } from '../../../../utils/interfaces';

@Pipe({
  name: 'booleanLikeToBoolean',
})
export class BooleanLikeToBooleanPipe implements PipeTransform {
  public transform(value: BooleanLike) {
    return value === true || value === 'true' || value === '';
  }
}
```

**Comment by pkozlowski-opensource** [comment] 2022-09-22 13:59
Duplicate of #8968

**Closed by pkozlowski-opensource** 2022-09-22 13:59 UTC
