### ISSUE TITLE
Enhance templating functionality - add break to switch statement

### ISSUE THREAD

**Issue by rehfeldchris** [angular/angular#21226] opened 2017-12-30 22:47 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ X] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

I request a enhancement to the `switch` template functionality (or maybe to add an `elseif` construct). I want something that behaves like the `break` statement, so that I can easily make a set of exclusive logical cases.

My use case:
I often embed form validation error messages into the html, and then display the messages as needed using conditions in the template. Eg, the following seems to be very common for developers from what I've seen:

```
<input #title="ngModel" required minlength="5">
<div *ngIf="title.errors && (title.dirty || title.touched)">
    <div [hidden]="!(title.errors.required && !title.errors.minlength && !title.errors.myCustomError)">
        Title is required
    </div>
    <div [hidden]="!(!title.errors.required && title.errors.minlength && !title.errors.myCustomError)">
        Title must be at least 5 characters long.
    </div>
    <div [hidden]="!(!title.errors.required && !title.errors.minlength && title.errors.myCustomError)">
        You violated the custom error.
    </div>
</div>
```

Often, I only want to display a **single error message at a time** to the user. But, as demonstrated above, to accomplish this I need write logic that checks for the error case, and then checks for the lack of ALL other cases, to make sure only 1 gets displayed at a time. As the number of cases grows, this quickly gets unwieldy.

Furthermore, often there will be cases where multiple errors will occur at the same time, in which case the above logic wouldn't work because it wont show any error message in such a case. So, I tend to resort to writing code in my component to make a synthetic `customTitleErrors` error object, using either a `switch` or `else if` in js to construct it, making sure only 1 property is true at a time, which allows my template code to stay simple:

```
<input #title="ngModel" required minlength="5">
<div *ngIf="title.errors && (title.dirty || title.touched)">
    <div [hidden]="!customTitleErrors.required">
        Title is required
    </div>
    <div [hidden]="!customTitleErrors.minlength">
        Title must be at least 5 characters long.
    </div>
    <div [hidden]="customTitleErrors.myCustomError">
        You violated the custom error.
    </div>
</div>
```

I've also resorted to writing a helper method which performs the said logic, which works well enough:
```<div [hidden]="shouldShowError(title, 'myCustomError')">```
But it hurts IDE's ability to do static analysis/refactoring, as it can't trace the usage of the `myCustomError` property anymore.

All of this would be so much easier if I just had an easy way to do exclusive cases in the template. Some ideas I've had:

Maybe add a new variant of `ngSwitchCase` called `ngSwitchCaseBreak` that works the same, except if the condition is true, it will be the last case evaluated.

```
<input #title="ngModel" required minlength="5">
<div *ngIf="title.errors && (title.dirty || title.touched)">
    <div [ngSwitch]="true">
        <div *ngSwitchCaseBreak="title.errors.required">
            Title is required
        </div>
        <div *ngSwitchCaseBreak="title.errors.minlength">
            Title must be at least 5 characters long.
        </div>
        <div *ngSwitchCaseBreak="title.errors.myCustomError">
            You violated the custom error.
        </div>
    </div>
</div>
```

Or maybe a more powerful way would be to add something like `ngBreakIf` allowing an arbitrary expression to control if you break.

```
<input #title="ngModel" required minlength="5">
<div *ngIf="title.errors && (title.dirty || title.touched)">
    <div [ngSwitch]="true">
        <div *ngSwitchCase="title.errors.required" *ngBreakIf="true">
            Title is required
        </div>
        <div *ngSwitchCase="title.errors.minlength" *ngBreakIf="true">
            Title must be at least 5 characters long.
        </div>
        <div *ngSwitchCase="title.errors.myCustomError" *ngBreakIf="true">
            You violated the custom error.
        </div>
    </div>
</div>
```

Or, maybe adding an `*elseIf` directive might be a good way to solve this use case (and others). I've seen the new if-else template functionality, but I can't say that I feel the resulting template code is very readable when you try to do else-if logic with `ng-container` and `ng-template`. 

I'm just throwing out ideas. Hopefully you agree there's opportunity to add a feature that will simplify many code bases.

Thanks, and great job on angular so far :)

**Comment by trotyl** [comment] 2018-01-01 08:28
Duplicate of #19824

**Comment by pkozlowski-opensource** [comment] 2018-01-01 09:58
It is duplicate of #19824 indeed. Thnx @trotyl

**Closed by pkozlowski-opensource** 2018-01-01 09:58 UTC
