### ISSUE TITLE
Disabled Attribute on Control in Groups with One FormControl Still Output Value in `form.value` Call

### ISSUE THREAD

**Issue by mgmarlow** [angular/angular#18684] opened 2017-08-14 18:19 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Setting up a form that contains a form group with one control will output that control in the `form.value` property even if said control is disabled. As soon as another control is added to the form, the disabled control will not output its value.

## Expected behavior
The call to `form.value` should not contain the disabled control's value.

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-h1iuml

* Create a form group with a single form control initialized with `{value:'', disabled: true}`
* Attach form group to a form HTML element, providing a radio button control for the form control above
* Observe that even though the control is disabled, `form.value` still outputs the value of the control

## What is the motivation / use case for changing the behavior?
The expected behavior for disabled form controls is that their value will not be outputted by calls to `form.value`, only `form.getRawVaue`.

## Environment

<pre><code>
Angular version: 4.3.0 & 4.3.4

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
</code></pre>

**Comment by elliotaplant** [comment] 2017-09-22 19:27
I've run into the same bug. There is a test in [form_control_spec.ts](https://github.com/angular/angular/blob/ff5c58be6b843bc8f79613dbefc5e4951c125f3d/packages/forms/test/form_control_spec.ts) that reads:
```
    it('should update the parent group value when child control status changes', () => {
      const c = new FormControl('one');
      const c2 = new FormControl('two');
      const g = new FormGroup({ 'one': c, 'two': c2 });
      expect(g.value).toEqual({ 'one': 'one', 'two': 'two' });

      c.disable();
      expect(g.value).toEqual({ 'two': 'two' });

      c2.disable();
      expect(g.value).toEqual({ 'one': 'one', 'two': 'two' });

      c.enable();
      expect(g.value).toEqual({ 'one': 'one' });
    });
```
This shows that the `myFormGroup.value` calculation respects the `valid` status when there are multiple children. If we use this as a base to make a new test that tests a group with only one child, we see the bug:
```
    it('should ignore value of a child control that are disabled', () => {
      const c = new FormControl('one');
      const g = new FormGroup({ 'one': c});
      expect(g.value).toEqual({ 'one': 'one' });

      c.disable();
      expect(g.value).toEqual({ }); // FAILS

      c.enable();
      expect(g.value).toEqual({ 'one': 'one' });
    });
```
I'll work on a PR for this when I get a chance

**Comment by elliotaplant** [comment] 2017-09-22 20:10
Here's an interesting caveat: It looks like the ignoring of disabled definitely depends on whether the parent group is disabled. Be careful with `.disable()` vs `.disable({ onlySelf: true })`!
```
    it('should include values of all child control in a form group if all child controls are disabled', () => {
      const c = new FormControl('one');
      const c2 = new FormControl('two');
      const g = new FormGroup({ 'one': c, 'two': c2 });
      expect(g.value).toEqual({ 'one': 'one', 'two': 'two' });

      c.disable();
      expect(g.value).toEqual({ 'two': 'two' });

      c2.disable();
      expect(g.value).toEqual({ 'one': 'one', 'two': 'two' });
    });

    it('should include all child controls regardless of disabled status if parent is enabled', () => {
      const c = new FormControl('one');
      const c2 = new FormControl('two');
      const g = new FormGroup({ 'one': c, 'two': c2 });
      expect(g.value).toEqual({ 'one': 'one', 'two': 'two' });

      c.disable({ onlySelf: true });
      expect(g.value).toEqual({ 'one': 'one', 'two': 'two' });

      c2.disable({ onlySelf: true });
      expect(g.value).toEqual({ 'one': 'one', 'two': 'two' });
    });
```

**Comment by elliotaplant** [comment] 2017-09-22 20:12
Here's a workaround too:
```
function valueWithoutDisabledChildControls(control: AbstractControl) {
  // If the control is disabled itself, throw an error, as this should not happen.
  // Consider replacing this with your own desired behavior
  if (control.disabled) {
    throw new Error('Attemting to get value of disabled control');
  }
  // The value of an enabled FormControl is just the .value property
  if (control instanceof FormControl) {
    return control.value;
  }

  if (control instanceof FormGroup) {
    const valueToReturn: any = {};
    // Iterate over keys form group, looking for child controls that are not disabled
    for (const childControlKey in control.controls) {
      if (control.controls.hasOwnProperty(childControlKey)) {
        const childControl = control.controls[childControlKey];
        if (!childControl.disabled) {
          // Recursively calculate values of child controls that are not disabled
          valueToReturn[childControlKey] = valueWithoutDisabledChildControls(childControl);
        }
      }
    }
    return valueToReturn;
  }

  if (control instanceof FormArray) {
    const valueToReturn: any[] = [];
    // Iterate over array of child control, looking for child controls that are not disabled
    control.controls.forEach(childControl => {
      if (!childControl.disabled) {
        // Recursively calculate values of child controls that are not disabled
        valueToReturn.push(IndexFormUtils.valueWithoutDisabledChildControls(childControl));
      }
    });
    return valueToReturn;
  }
}
```
And here are some tests to verify:
```
fdescribe('valueWithoutDisabledChildControls tests', () => {
  it('should not include value of a child control in a form group if that child control is disabled', () => {
    const c = new FormControl('one');
    const g = new FormGroup({ 'one': c});
    expect(valueWithoutDisabledChildControls(g)).toEqual({ 'one': 'one' });

    c.disable({ onlySelf: true });
    expect(valueWithoutDisabledChildControls(g)).toEqual({ });
  });

  it('should include values of all child control in a form group if all child controls are disabled', () => {
    const c = new FormControl('one');
    const c2 = new FormControl('two');
    const g = new FormGroup({ 'one': c, 'two': c2 });
    expect(valueWithoutDisabledChildControls(g)).toEqual({ 'one': 'one', 'two': 'two' });

    c.disable({ onlySelf: true });
    expect(valueWithoutDisabledChildControls(g)).toEqual({ 'two': 'two' });

    c2.disable({ onlySelf: true });
    expect(valueWithoutDisabledChildControls(g)).toEqual({ });
  });

  it('should include value of a child control in a form array if that child control is disabled', () => {
    const c = new FormControl('one');
    const g = new FormArray([c]);
    expect(valueWithoutDisabledChildControls(g)).toEqual(['one']);

    c.disable({ onlySelf: true });
    expect(valueWithoutDisabledChildControls(g)).toEqual([]);
  });

  it('should include values of all child control in a form group if all child controls are disabled', () => {
    const c = new FormControl('one');
    const c2 = new FormControl('two');
    const g = new FormArray([c, c2]);
    expect(valueWithoutDisabledChildControls(g)).toEqual(['one', 'two']);

    c.disable({ onlySelf: true });
    expect(valueWithoutDisabledChildControls(g)).toEqual(['two']);

    c2.disable({ onlySelf: true });
    expect(valueWithoutDisabledChildControls(g)).toEqual([]);
  });
});
```

**Comment by elliotaplant** [comment] 2017-09-22 20:20
Here's another test showing that this works for nested groups:
```
it('should work for a nested form group', () => {
  const c1 = new FormControl('control one');
  const c2 = new FormControl('control two');
  const c3 = new FormControl('control three');
  const g2 = new FormGroup({ 'cTwo': c2, 'cThree': c3 });
  const g = new FormGroup({ 'cOne': c1, 'gTwo': g2 });

  expect(valueWithoutDisabledChildControls(g)).toEqual({
    'cOne': 'control one',
    'gTwo': {
      'cTwo': 'control two',
      'cThree': 'control three'
    }
  });

  c1.disable({ onlySelf: true });

  expect(valueWithoutDisabledChildControls(g)).toEqual({
    'gTwo': {
      'cTwo': 'control two',
      'cThree': 'control three'
    }
  });

  c1.enable({ onlySelf: true });
  g2.disable({ onlySelf: true });
  expect(valueWithoutDisabledChildControls(g)).toEqual({
    'cOne': 'control one',
  });

  g2.enable({ onlySelf: true });
  c2.disable({ onlySelf: true });

  expect(valueWithoutDisabledChildControls(g)).toEqual({
    'cOne': 'control one',
    'gTwo': {
      'cThree': 'control three'
    }
  });

  c3.disable({ onlySelf: true });
  expect(valueWithoutDisabledChildControls(g)).toEqual({
    'cOne': 'control one',
    'gTwo': {}
  });
});
```

**Comment by mgmarlow** [comment] 2017-09-22 21:19
@elliotaplant Thanks for finding that unit test that recreates the behavior. I agree with you that this is a bizarre intention for form controls, it seems counter-intuitive when compared to the default behavior of form groups.

**Comment by kara** [comment] 2017-10-19 01:57
Looks like a dupe of https://github.com/angular/angular/issues/15982.  See original explanatino here: https://github.com/angular/angular/issues/15982#issuecomment-327335108

**Closed by kara** 2017-10-19 01:57 UTC
Labels: comp: forms
