### ISSUE TITLE
MessageService being called before it is installed in tutorial

### ISSUE THREAD

**Issue by alexlais** [angular/angular#21844] opened 2018-01-28 21:33 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Under the TUTORIAL > Services > Provide the HeroService
(page https://angular.io/tutorial/toh-pt4#provide-the-heroservice)
the instruction is:

"Open the AppModule class, import the HeroService, and add it to the @NgModule.providers array."
src/app/app.module.ts (providers)
providers: [ HeroService, MessageService ],

But it should be:

providers: [ HeroService ],

Otherwise the application will not run at this stage because at this stage of tutorial the MessageService has not yet been installed.

Thanks!

**Comment by alexlais** [comment] 2018-01-29 04:24
To support my reported tutorial bug, I will explain again, the issue is that only when the MessageService is installed at a later stage down this same page of the tutorial,  that it will add the MessageService to the providers. And that is when the tutorial instructs you to run (ng generate service message --module=app) in the CLI. 

Therefore as I mentioned, during the section where only the HeroService is created, which is when the tutorial instructs to run (ng generate service hero) in the CLI, there should not me a call to the MessageService yet.

So, again, under "Provide the HeroService" section it needs to change FROM:

"Provide the HeroService
...Since you did not, you'll have to provide it yourself.
Open the AppModule class, import the HeroService, and add it to the @NgModule.providers array.
src/app/app.module.ts (providers)
providers: [ HeroService, MessageService ],"

TO:

"Provide the HeroService
...Since you did not, you'll have to provide it yourself.
Open the AppModule class, import the HeroService, and add it to the @NgModule.providers array.
src/app/app.module.ts (providers)
providers: [ HeroService ],"           <== NOTE: NO MessageService YET!


![screen shot 2018-01-28 at 11 20 30 pm](https://user-images.githubusercontent.com/13528749/35493520-0ca85c06-0482-11e8-81a0-db66fa03d9de.png)

**Comment by alexlais** [comment] 2018-01-29 04:28
![screen shot 2018-01-28 at 11 20 30 pm](https://user-images.githubusercontent.com/13528749/35493653-ffb4481a-0482-11e8-8e01-7472c90013be.png)

**Comment by trotyl** [comment] 2018-01-29 06:42
Duplicate of #20398

**Comment by jasonaden** [comment] 2018-01-29 19:06
Closing as duplicate.

**Closed by jasonaden** 2018-01-29 19:06 UTC
