### ISSUE TITLE
Routing works wrong with children and lazy loading (v11.x)

### ISSUE THREAD

**Issue by GabrielInTheWorld** [angular/angular#40641] opened 2021-01-30 15:51 UTC
# 🐞 bug report

### Affected Package
@angular/router

### Is this a regression?
Yes. In Angular v9.x works this fine... After I updated a repo to Angular v11.x it doesn't anymore...

### Description
I built an app using children and lazy loading. So, I have a 'dashboard'-component (url-prefix: ''), where several links navigating to sub-components are placed. Each sub-component is achieved by its own sub-route.  The sub-routes are nested under the dashboard-component in its 'children'-array. Furthermore, the sub-components are lazy loaded.
Like this:
```ts
const routes: Routes = [
  {
    path: '',
    pathMatch: 'full',
    component: OdersListComponent,
    children: [
      {
        path: 'detail',
        loadChildren: () =>
          import('./oders-detail/oders-detail.module').then(
            (m) => m.OdersDetailModule
          ),
      },
    ],
  },
];
```

But, if I then go to one sub-route, the following error appeared:
<pre><code>
ERROR Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'orders/detail'
Error: Cannot match any routes. URL Segment: 'orders/detail'
</code></pre>

## 🔬 Minimal Reproduction
I have made a github-repository to reproduce this bug: https://github.com/GabrielInTheWorld/example-angular-app

## 🔥 Exception or Error
<pre><code>
ERROR Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'orders/detail'
Error: Cannot match any routes. URL Segment: 'orders/detail'
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 11.0.7
Node: 14.7.0
OS: win32 x64

Angular: 11.0.9
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.7
@angular-devkit/build-angular   0.1100.7
@angular-devkit/core            11.0.7
@angular-devkit/schematics      11.0.7
@angular/cli                    11.0.7
@schematics/angular             11.0.7
@schematics/update              0.1100.7
rxjs                            6.6.3
typescript                      4.0.5
</code></pre>

**Anything else relevant?**

**Comment by Airblader** [comment] 2021-01-30 19:33
The problem is the `patchMath: 'full` in your route definition. You're saying that this route should only match if the entire rest of the route matches `''` (empty string), which of course isn't the case since `/detail` is yet to come. 

Removing this makes it work as expected.

**Comment by Airblader** [comment] 2021-01-30 19:39
I should say, this fixes the error and makes the navigation succeed. You still only see "orders-list works" and not "order-details works" because that's how this app is set up.

**Comment by atscott** [comment] 2021-02-02 18:53
Closing, as this appears to be working as expected. Please see the comments above by @Airblader. As far as not seeing 
"order details works", that's because you don't have a router-outlet to show the child routes of order list.

**Closed by atscott** 2021-02-02 18:53 UTC
Labels: comp: router, router: lazy loading
