### ISSUE TITLE
`ViewRef#onDestroy` throws an error in a ctor context

### ISSUE THREAD

**Issue by lacolaco** [angular/angular#46119] opened 2022-05-24 03:15 UTC
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

Already Chau said, `ViewRef#onDestroy` is untouchable if the app is **ONLY in dev mode**. 
https://twitter.com/Nartc1410/status/1527274445056126978

Repro: https://stackblitz.com/edit/angular-ivy-9mzqjg?file=src/main.ts

I'm not sure these are related, injecting `ViewRef` by `inject()` is impossible in the ctor context.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-9mzqjg?file=src/main.ts

### Please provide the exception or error you saw

```true
Error: Uncaught (in promise): TypeError: Cannot add property 0, object is not extensible
TypeError: Cannot add property 0, object is not extensible
at TCleanup.push (<anonymous>)
at listenerInternal (https://angular-ivy-9mzqjg.stackblitz.io/turbo_modules/@angular/core@14.0.0-rc.1/fesm2015/core.mjs:15439:38)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular v14.0.0-rc1
```

**Comment by AndrewKushnir** [comment] 2022-05-24 05:47
@lacolaco thanks for reporting the issue and providing a repro.

I was able to simplify the repro further and found out that the issue is not related to the `inject` function, but related to the timing of the `onDestroy` call. Here is a minimal repro:

https://stackblitz.com/edit/angular-ivy-jd7sx8?file=src%2Fapp%2Fapp.component.ts

The runtime code assumes that when the `ViewRef.onDestroy` function is invoked (typically in users code), the template is already processed and an internal data structure (responsible for storing the cleanup functions) becomes frozen as a way to avoid any accidental modifications (to retain the same shape of the structure, which is important for runtime performance):

https://github.com/angular/angular/blob/c3205d0962f1ff0d2dd4fa26c70372f6fe80f5e3/packages/core/src/render3/instructions/shared.ts#L820-L826

However, this assumption is incorrect when the `ViewRef.onDestroy` is called from within a constructor (which happens in my repro) or during a class property initialization (which happens in the repro that you provided). I think that `Object.freeze` operation should have an additional check (possibly the `tView.firstCreatePass` check).

As a possible solution, you can try to delay the `onDestroy` call (for example, by wrapping it into `Promise.resolve().then(() => ref.onDestroy( ... ))`) - that'd allow component's template to be fully processed before the `Object.freeze` is invoked.

**Comment by AndrewKushnir** [comment] 2022-05-24 05:51
Related PR where this logic was added: #39876.

**Comment by crisbeto** [comment] 2022-06-02 08:20
I had some time so I looked into this. I think that the `Object.freeze` as it is written right now prevents a legitimate issue. If we take the following test:

```ts
it('', () => {
  const calls: string[] = [];

  @Component({template: '<button (click)="countUp()">Count up</button>'})
  class App {
    constructor(public cdr: ChangeDetectorRef) {
      this.addDestroyCallback('constructor');
    }

    addDestroyCallback(message: string) {
      (this.cdr as ViewRef).onDestroy(() => calls.push(message));
    }

    countUp() {}
  }

  TestBed.configureTestingModule({declarations: [App]});
  const fixture = TestBed.createComponent(App);
  fixture.detectChanges();

  fixture.componentInstance.addDestroyCallback('after init');
  fixture.detectChanges();

  fixture.destroy();
  expect(calls).toEqual(['constructor', 'after init']); // this fails because it's `['after init']`
});
```

Without the `Object.freeze` the error obviously won't be thrown, but the `onDestroy` callback from the constructor won't be invoked either due to how the cleanup functions are registered. I think that our options are:
1. Rework our data structure so that instance destroy callbacks can be registered before the template-level ones (maybe split it up into two `cleanup` arrays?). This will be a larger refactor.
2. Somehow delay the callback being registered by `ViewRef.onDestroy` to after the first create pass. I don't think that we have a good way of doing this at the moment.
3. Throw a better error if a case like this is detected. This is trivial to do and at least it'll give users some more actionable recommendations instead of the vague error we have now.

**Comment by AndrewKushnir** [comment] 2022-06-03 20:09
@crisbeto thanks for additional investigation 👍 

I really like the idea of adding an error message as a quick change to improve the DX.

Regarding possible fixes, here is a couple additional thoughts:
1. We can think of allocating the first element of the `lCleanup` array to store instance-specific callbacks (as an array), so we always know where to find that list. This would probably not require a massive refactoring, but I'm not 100% if there are some perf implications of this + we'd always need to allocate that first position even if there are no instance-specific cleanups.
2. As another possible option, can we rely on the length of the tCleanup data structure to calculate the correct position for the location in lCleanup?
```
    if (tView.firstCreatePass) {
      const tCleanup = getOrCreateTViewCleanup(tView);
      const lastTCleanupIdx = tCleanup.length / 2; // for each cleanup fn we allocate 2 slots
      tCleanup.push(cleanupFn, lCleanup.length - 1);
      if (lastTCleanupIdx === lCleanup.length - 1) {
        // Fast path: no instance-specific callbacks, just add a context to the very end
        lCleanup.push(context);
      } else {
        // Slower path: insert a context in front of instance-specific callbacks
        lCleanup.splice(lastTCleanupIdx, 0, context);
      }
    }
```

**Comment by lacolaco** [comment] 2022-06-04 00:51
It's just an idea, how difficult or complex is adding a mechanism to forward resolving the view reference like forwardRef()?

**Comment by AndrewKushnir** [comment] 2022-06-06 23:48
@lacolaco we had a conversation about this issue with the team. The `ChangeDetectorRef` class doesn't provide the `onDestroy` method as a public API, so in your example code you are using private APIs (by casting the `ChangeDetectorRef` to `ViewRef`). Since there is no public API to trigger the problem, I'm closing the ticket.

**Closed by AndrewKushnir** 2022-06-06 23:48 UTC
Labels: comp: core, P3, bug

**Comment by avchugaev** [comment] 2022-06-24 12:17
@AndrewKushnir I agree that providing `onDestroy` hook via `ChangeDetectorRef` is not the best option as its responsibility is a change detection works. (I think exposing `ChangeDetectorRef` is a doubtful design choice).

On the other hand, having a similar API would be nice to reduce the boilerplate `OnDestroy` implementation.

Here's how a typical implementation of `OnDestroy` looks like:

```ts
export class DemoComponent implements OnDestroy {
  private readonly destroy$ = new Subject<void>();
  
  // use it like `takeUntil(this.destroy$)`...
  
  ngOnDestroy() {
    this.destroy$.next();
    this.destroy$.complete();
  }
}
```

But folks want to type fewer lines of code, and the new `inject()` API allows them to do it by implementing a shorthand function once...

```ts
export function useDestroy() {
  const viewRef = inject(ChangeDetectorRef) as ViewRef;
  const destroy$ = new Subject<void>();
  
  viewRef.onDestroy(() => {
    destroy$.next();
    destroy$.complete();
  });
  
  return destroy$.asObservable();
}
```

... and use it as a one-liner everywhere:

```ts
export class DemoComponent {
  private readonly destroy$ = useDestroy(); // less boilerplate
  
  // use it like `takeUntil(this.destroy$)`...
}
```

Could you consider adding an API to make it possible?

**Comment by avchugaev** [comment] 2022-06-24 12:55
@pkozlowski-opensource Thanks for referring me to the appropriate issues. I commented it here - https://github.com/angular/angular/issues/10185#issuecomment-1165545544
