### ISSUE TITLE
NotYetImplemented error related to ZoneAwarePromise2 after Angular 15 -> 16 upgrade

### ISSUE THREAD

**Issue by SebastianKohler** [angular/angular#51319] opened 2023-08-10 12:34 UTC
### Which @angular/* package(s) are the source of the bug?

zone.js, Don't known / other

### Is this a regression?

Yes

### Description

After upgrading an Ionic 7/Angular 15 website to Angular 16 I get the following "NotYetImplemented" error in the server side console during runtime:

```
Error: NotYetImplemented
    at exports2.nyi (C:\Users\sebkoh\Documents\GitHub\digital_edition_web_ng\dist\app\server\sv\main.js:3:3370136)
    at hydrateApp (C:\Users\sebkoh\Documents\GitHub\digital_edition_web_ng\dist\app\server\sv\main.js:3:680282)
    at hydrateAppClosure (C:\Users\sebkoh\Documents\GitHub\digital_edition_web_ng\dist\app\server\sv\main.js:3:2002927)
    at hydrateFactory (C:\Users\sebkoh\Documents\GitHub\digital_edition_web_ng\dist\app\server\sv\main.js:3:2003034)
    at render (C:\Users\sebkoh\Documents\GitHub\digital_edition_web_ng\dist\app\server\sv\main.js:3:2009415)
    at C:\Users\sebkoh\Documents\GitHub\digital_edition_web_ng\dist\app\server\sv\main.js:3:2024287
    at new ZoneAwarePromise2 (C:\Users\sebkoh\Documents\GitHub\digital_edition_web_ng\dist\app\server\fi\main.js:3:2853780)
    at hydrateDocument (C:\Users\sebkoh\Documents\GitHub\digital_edition_web_ng\dist\app\server\sv\main.js:3:2023935)
    at C:\Users\sebkoh\Documents\GitHub\digital_edition_web_ng\dist\app\server\sv\main.js:3:253084
    at C:\Users\sebkoh\Documents\GitHub\digital_edition_web_ng\dist\app\server\sv\main.js:3:3670726
```

The error doesn't appear to affect the functionality of the website, but is annoying.

I believe the error has something to do with **zone.js 0.13.x**, because before upgrading zone.js from 0.13.0 to 0.13.1, the NotYetImplemented error was a bit different, and there was also an "unhandledRejection RuntimeError: NG04002" error. The NG04002 error went away after upgrading zone.js 0.13.0 -> 0.13.1.

Previously, with zone.js 0.13.0, the errors were:

```
Error: NotYetImplemented
    at exports2.nyi (C:\Users\sebkoh\Documents\GitHub\digital_edition_web_ng\dist\app\server\sv\main.js:3:3359744)
    at hydrateApp (C:\Users\sebkoh\Documents\GitHub\digital_edition_web_ng\dist\app\server\sv\main.js:3:680053)
    at hydrateAppClosure (C:\Users\sebkoh\Documents\GitHub\digital_edition_web_ng\dist\app\server\sv\main.js:3:2002698)
    at hydrateFactory (C:\Users\sebkoh\Documents\GitHub\digital_edition_web_ng\dist\app\server\sv\main.js:3:2002805)
    at render (C:\Users\sebkoh\Documents\GitHub\digital_edition_web_ng\dist\app\server\sv\main.js:3:2009186)
    at C:\Users\sebkoh\Documents\GitHub\digital_edition_web_ng\dist\app\server\sv\main.js:3:2024058
    at new Promise (<anonymous>)
    at hydrateDocument (C:\Users\sebkoh\Documents\GitHub\digital_edition_web_ng\dist\app\server\sv\main.js:3:2023706)
    at C:\Users\sebkoh\Documents\GitHub\digital_edition_web_ng\dist\app\server\sv\main.js:3:252855
    at C:\Users\sebkoh\Documents\GitHub\digital_edition_web_ng\dist\app\server\sv\main.js:3:3660334
unhandledRejection RuntimeError: NG04002
    at Recognizer.noMatchError (C:\Users\sebkoh\Documents\GitHub\digital_edition_web_ng\dist\app\server\sv\main.js:3:3721082)
    at C:\Users\sebkoh\Documents\GitHub\digital_edition_web_ng\dist\app\server\sv\main.js:3:3721524
    at C:\Users\sebkoh\Documents\GitHub\digital_edition_web_ng\dist\app\server\sv\main.js:3:2630818
    at OperatorSubscriber2._this._error (C:\Users\sebkoh\Documents\GitHub\digital_edition_web_ng\dist\app\server\sv\main.js:3:2619470)
    at Subscriber2.error (C:\Users\sebkoh\Documents\GitHub\digital_edition_web_ng\dist\app\server\sv\main.js:3:2573122)
    at Subscriber2._error (C:\Users\sebkoh\Documents\GitHub\digital_edition_web_ng\dist\app\server\sv\main.js:3:2573588)
    at Subscriber2.error (C:\Users\sebkoh\Documents\GitHub\digital_edition_web_ng\dist\app\server\sv\main.js:3:2573122)
    at Subscriber2._error (C:\Users\sebkoh\Documents\GitHub\digital_edition_web_ng\dist\app\server\sv\main.js:3:2573588)
    at Subscriber2.error (C:\Users\sebkoh\Documents\GitHub\digital_edition_web_ng\dist\app\server\sv\main.js:3:2573122)
    at Subscriber2._error (C:\Users\sebkoh\Documents\GitHub\digital_edition_web_ng\dist\app\server\sv\main.js:3:2573588) {
  code: 4002
}
Error: NotYetImplemented
    at exports2.nyi (C:\Users\sebkoh\Documents\GitHub\digital_edition_web_ng\dist\app\server\sv\main.js:3:3359744)
    at hydrateApp (C:\Users\sebkoh\Documents\GitHub\digital_edition_web_ng\dist\app\server\sv\main.js:3:680053)
    at hydrateAppClosure (C:\Users\sebkoh\Documents\GitHub\digital_edition_web_ng\dist\app\server\sv\main.js:3:2002698)
    at hydrateFactory (C:\Users\sebkoh\Documents\GitHub\digital_edition_web_ng\dist\app\server\sv\main.js:3:2002805)
    at render (C:\Users\sebkoh\Documents\GitHub\digital_edition_web_ng\dist\app\server\sv\main.js:3:2009186)
    at C:\Users\sebkoh\Documents\GitHub\digital_edition_web_ng\dist\app\server\sv\main.js:3:2024058
    at new Promise (<anonymous>)
    at hydrateDocument (C:\Users\sebkoh\Documents\GitHub\digital_edition_web_ng\dist\app\server\sv\main.js:3:2023706)
    at C:\Users\sebkoh\Documents\GitHub\digital_edition_web_ng\dist\app\server\sv\main.js:3:252855
    at C:\Users\sebkoh\Documents\GitHub\digital_edition_web_ng\dist\app\server\sv\main.js:3:3660334
```

I don't know how to produce a minimal reproduction of the bug, but to see it in action:

1. Clone this repository: https://github.com/slsfi/digital_edition_web_ng/tree/angular-16
2. Run `npm install`
3. Run `npm run build:ssr`
4. Run `npm run serve:ssr`
5. Go to http://localhost:4201 in the browser

The error will appear in the terminal immediately when the first page loads, and also on subsequent page loads.

I'm guessing this might have something to do with issue https://github.com/angular/angular/issues/50327, but I really have no idea.

Thankful for any help with this!

### Please provide the exception or error you saw

```true
Error: NotYetImplemented
    at exports2.nyi (C:\Users\sebkoh\Documents\GitHub\digital_edition_web_ng\dist\app\server\sv\main.js:3:3370136)
    at hydrateApp (C:\Users\sebkoh\Documents\GitHub\digital_edition_web_ng\dist\app\server\sv\main.js:3:680282)
    at hydrateAppClosure (C:\Users\sebkoh\Documents\GitHub\digital_edition_web_ng\dist\app\server\sv\main.js:3:2002927)
    at hydrateFactory (C:\Users\sebkoh\Documents\GitHub\digital_edition_web_ng\dist\app\server\sv\main.js:3:2003034)
    at render (C:\Users\sebkoh\Documents\GitHub\digital_edition_web_ng\dist\app\server\sv\main.js:3:2009415)
    at C:\Users\sebkoh\Documents\GitHub\digital_edition_web_ng\dist\app\server\sv\main.js:3:2024287
    at new ZoneAwarePromise2 (C:\Users\sebkoh\Documents\GitHub\digital_edition_web_ng\dist\app\server\fi\main.js:3:2853780)
    at hydrateDocument (C:\Users\sebkoh\Documents\GitHub\digital_edition_web_ng\dist\app\server\sv\main.js:3:2023935)
    at C:\Users\sebkoh\Documents\GitHub\digital_edition_web_ng\dist\app\server\sv\main.js:3:253084
    at C:\Users\sebkoh\Documents\GitHub\digital_edition_web_ng\dist\app\server\sv\main.js:3:3670726
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 16.2.0
Node: 18.14.2
Package Manager: npm 9.8.1
OS: win32 x64

Angular: 16.2.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, platform-server, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1600.5
@angular-devkit/build-angular   16.2.0
@angular-devkit/core            15.2.3
@angular-devkit/schematics      15.2.3
@nguniversal/builders           16.1.3
@nguniversal/express-engine     16.1.3
@schematics/angular             15.2.3
rxjs                            7.8.1
typescript                      5.0.4
zone.js                         0.13.1
```

**Comment by JeanMeche** [comment] 2023-08-10 13:22
The ionic code is calling `baseURI` with throws : 

https://github.com/angular/domino/blob/aa8de3486307f57a518b4b0d9e5e16d9fbd998d1/lib/Node.js#L48

**Comment by SebastianKohler** [comment] 2023-08-14 05:57
It seems to be the hydration in IonicServerModule from '@ionic/angular-server' which is causing the error: https://github.com/ionic-team/ionic-framework/blob/main/packages/angular-server/src/ionic-server-module.ts

Is this something the Ionic team should take a look at or is it a problem with the changes between Angular 15 and 16? @ionic/angular-server 7 works fine on Angular 15.

**Comment by pkozlowski-opensource** [comment] 2023-09-13 15:20
Duplicate of https://github.com/ionic-team/ionic-framework/issues/28077

**Closed by pkozlowski-opensource** 2023-09-13 15:20 UTC
Labels: area: core, area: server, core: hydration
