### ISSUE TITLE
if *ngIf is working the same element with *ngFor ,it desn't work?

### ISSUE THREAD

**Issue by cjd6568358** [angular/angular#9025] opened 2016-06-05 06:16 UTC
my demo is like it:
`<div class="cart" *ngFor="let mealInfo of mealInfoList;let mealInfoIndex = index" *ngIf="mealInfo?.selectedCount > 0">`
the *ngIf desn't work.

`<div *ngFor="let a of [11,12,13]" *ngIf="a == 11"></div>`
the *ngFor desn't work.

* **Angular version:** 2.0.0-rc1

**Comment by ericmartinezr** [comment] 2016-06-05 06:17
See https://github.com/angular/angular/issues/4792, actually this should throw https://github.com/angular/angular/issues/7315

**Comment by cjd6568358** [comment] 2016-06-05 07:44
@ericmartinezr thanks. it's usefully for me

**Comment by pkozlowski-opensource** [comment] 2016-06-05 08:10
Yeh, we should throw so going to close this one as a duplicate of #7315

**Comment by pkozlowski-opensource** [comment] 2016-06-05 08:10
Oh, @robwormald was 10s faster :-)

**Closed by pkozlowski-opensource** 2016-06-05 08:10 UTC

**Comment by calidion** [comment] 2017-01-15 18:05
should be working regardless of how many directives are used.
