### ISSUE TITLE
Unit test should fail if an element is not known

### ISSUE THREAD

**Issue by sebastianhaeni** [angular/angular#36430] opened 2020-04-04 16:52 UTC
# 🚀 Unit test should fail if an element is not known

### Relevant Package
This feature request is for @angular/core.
And I think this is a kinda a regression since this behavior changed with Ivy.

### Description
When executing unit tests with Karma and my test module has not been setup correctly, to contain all the relevant components, I get a  warning like this:
```
WARN: ''app-my-element' is not a known element:
1. If 'app-my-element' is an Angular component, then verify that it is part of this module.
2. If 'app-my-element' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.'
```

The test is still successful in that case. In my opinion it should fail, since the test module clearly is missing this component.

I saw that there have been efforts to make it appear as an error: 00f3c58.
This has been reverted in this commit: 00f3c58.

But that wouldn't change the fact, that the test still passes.

### Describe the solution you'd like
I would like one of these options:
* tests with unknown elements fail (as they did pre Ivy)
* an option to enable this behavior to make the tests fail
  * i.e. a CLI argument or a property in angular.json

If the default is "fail", then a user could add `CUSTOM_ELEMENTS_SCHEMA` or `NO_ERRORS_SCHEMA` to their test module if they want to suppress the errors.

**Comment by x87** [comment] 2020-04-06 14:00
This is probably related to #36171

**Comment by danmana** [comment] 2020-04-09 07:24
This has been driving me nuts for a few weeks.

On my local machine, tests with unknown elements pass without even showing a warning.
On the build server, the tests fail.

Other types of failing tests behave the same on both machines (wrong expect statements fail on both)

Test command: `npm run test -- --watch false --progress false`

My machine:
Windows 10 Pro, version 10.0.18363 Build 18363
```
Angular CLI: 9.0.5
Node: 12.16.0
OS: win32 x64

Angular: 9.0.5
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.5
@angular-devkit/build-angular     0.900.5
@angular-devkit/build-optimizer   0.900.5
@angular-devkit/build-webpack     0.900.5
@angular-devkit/core              9.0.5
@angular-devkit/schematics        9.0.5
@angular/cdk                      9.1.1
@angular/flex-layout              9.0.0-beta.29
@angular/material                 9.1.1
@ngtools/webpack                  9.0.5
@schematics/angular               9.0.5
@schematics/update                0.900.5
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
```

Build server:
Gitlab-CI using image `circleci/node:12-browsers`

I even tried running the tests locally in the same docker container that the build server uses, but to no avail, it still passes locally but fails once I push it to gitlab.

**Comment by sebastianhaeni** [comment] 2020-04-22 21:24
In case anybody is interested, I have the following workaround in place until this is fixed:

Executing the following function before creating the component with `TestBed.createComponent()` will ensure tests fail if there are unknown elements. 

Since we use a util function in every component test to setup our test bed, it was easy to add there.

```ts
/**
 * Monkey patch console warn and error to fail if a test makes calls to console.warn or console.error.
 */
function patchConsole(): void {
    console.warn = function(message?: any, ...optionalParams: any[]): void {
        const params = optionalParams ? `\nParams: ${optionalParams}` : '';
        fail(`Test contained console warning:\n${message}${params}`);
    };
    console.error = function(message?: any, ...optionalParams: any[]): void {
        const params = optionalParams ? `\nParams: ${optionalParams}` : '';
        fail(`Test contained console error:\n${message}${params}`);
    };
}
```

**Comment by kara** [comment] 2020-05-27 18:30
We originally moved away from throwing an error because Ivy's direct property introspection is stricter than View Engine's old property validation using element schemas. Throwing causes issues if you bind to a property that is supported in one browser, but not another. In VE, the browser that didn't have support would just not have the binding so it would still work, but in Ivy the browser that didn't have support would throw.  Hence, logging an error as a compromise.

That said, I agree that logging is not sufficient when it comes to tests. It's super confusing that your tests would pass with a logged error. We should probably re-evaluate whether we should throw in that case. I think it makes more sense to have a breaking change for apps that bind to properties that only work in some browsers than to have everyone's tests potentially affected.

**Comment by f-loris** [comment] 2020-09-03 13:19
> circleci/node

I can confirm this, I experienced the same issue. Actually the root cause on my end was s permission problem on the CI system. I could fix this by building my own docker image without specifying a `USER` in Dockerfile. This SO post also came to the same conclusion: https://stackoverflow.com/a/63554302/9999800

It looks like Ivy is not working correctly when it doesn't have write permission while executing tests and somehow the old view engine is used, but I'm not really sure what is going on. From my point of view Ivy should fail in such a case and not silently do some weird things.

**Comment by f-loris** [comment] 2020-09-03 13:20
> This has been driving me nuts for a few weeks.
> 
> On my local machine, tests with unknown elements pass without even showing a warning.
> On the build server, the tests fail.
> 
> Other types of failing tests behave the same on both machines (wrong expect statements fail on both)
> 
> Test command: `npm run test -- --watch false --progress false`
> 
> My machine:
> Windows 10 Pro, version 10.0.18363 Build 18363
> 
> ```
> Angular CLI: 9.0.5
> Node: 12.16.0
> OS: win32 x64
> 
> Angular: 9.0.5
> ... animations, cli, common, compiler, compiler-cli, core, forms
> ... language-service, platform-browser, platform-browser-dynamic
> ... router
> Ivy Workspace: Yes
> 
> Package                           Version
> -----------------------------------------------------------
> @angular-devkit/architect         0.900.5
> @angular-devkit/build-angular     0.900.5
> @angular-devkit/build-optimizer   0.900.5
> @angular-devkit/build-webpack     0.900.5
> @angular-devkit/core              9.0.5
> @angular-devkit/schematics        9.0.5
> @angular/cdk                      9.1.1
> @angular/flex-layout              9.0.0-beta.29
> @angular/material                 9.1.1
> @ngtools/webpack                  9.0.5
> @schematics/angular               9.0.5
> @schematics/update                0.900.5
> rxjs                              6.5.4
> typescript                        3.7.5
> webpack                           4.41.2
> ```
> 
> Build server:
> Gitlab-CI using image `circleci/node:12-browsers`
> 
> I even tried running the tests locally in the same docker container that the build server uses, but to no avail, it still passes locally but fails once I push it to gitlab.
> 
> Locally it's behaving like I have some global setting of `schemas: [NO_ERRORS_SCHEMA]` ...

I can confirm this, I experienced the same issue. Actually the root cause on my end was s permission problem on the CI system. I could fix this by building my own docker image without specifying a USER in Dockerfile. This SO post also came to the same conclusion: https://stackoverflow.com/a/63554302/9999800

It looks like Ivy is not working correctly when it doesn't have write permission while executing tests and somehow the old view engine is used, but I'm not really sure what is going on. From my point of view Ivy should fail in such a case and not silently do some weird things.

**Comment by nthornton2010** [comment] 2020-10-16 15:05
I'd love to see this fixed! Many devs don't read the logged errors and just see SUCCESS and move on. Our test suite is now full of blue error messages that need cleaning up.

**Comment by FDIM** [comment] 2020-11-10 12:30
I'd like this to do the same as it did in angular 8 - fail the test. 

Once more of these warning/errors pile up it becomes quite an endeavor to fix them.

All you get is:
`ERROR: 'Can't bind to 'routerLink' since it isn't a known property of 'a'.'` 

No stack trace is available even in chrome console window, which basically wishes you good luck to find them. We have 6500 specs... Looks like I'll be monkey patching console error to fail

**Comment by themizzi** [comment] 2020-12-05 17:26
We uncovered this same problem and now have a bunch of tests that should fail but are not.

**Comment by youqing-voyager** [comment] 2020-12-09 23:35
Please at least give an option, let that error fails unit test! Thank you.

**Comment by FDIM** [comment] 2020-12-09 23:48
Since angular 10 it became a console.error, so what I ended up doing is monkey patching this method in test.ts to throw an error and log stack trace to pin point exactly which place has an issue. Seems to work ok for now.

**Comment by youqing-voyager** [comment] 2020-12-09 23:53
> Since angular 10 it became a console.error, so what I ended up doing is monkey patching this method in test.ts to throw an error and log stack trace to pin point exactly which place has an issue. Seems to work ok for now.

Hi @FDIM , do you mind share a code snippet of how to do it? Thanks.

**Comment by FDIM** [comment] 2020-12-10 08:17
Here is mine, somewhere in a file in testing utils:
````
const orgConsoleError = window.console.error;

export function patchConsoleToFailOnError() {
    window.console.error = function (...args: any[]) {
        orgConsoleError.apply(this, args);
        try { throw new Error('console.error'); } catch (err) { console.info('console.error', args, err); }
        fail('console.error was called, this is not allowed in a unit test run');
    };
}
````

And in test.ts:

```
beforeEach(() => patchConsoleToFailOnError());
```

So far seems to work nicely

**Comment by rkorebrits** [comment] 2021-02-15 08:45
> ```
> beforeEach(() => patchConsoleToFailOnError());
> ```

Instead of adding it into individual tests, you can also add it to `test.scripts` in `angular.json` for your project to catch all

**Comment by inorganik** [comment] 2021-04-08 22:08
I'm experiencing similar, where I just see a console error but the tests pass; however on our build server the tests fail as they should. Can anyone explain why they would only properly fail on a build server?

I have verified that the build server is using the same node version (14.15).

Failure on build server:
```
FAIL src/app/some-module/some.component.spec.ts (9.462 s)
  ● SomeComponent › should create

    Template parse errors:
    Can't bind to 'useCompactLayout' since it isn't a known property of 'app-xyz'.
    1. If 'app-xyz' is an Angular component and it has 'useCompactLayout' input, then verify that it is part of this module.
    2. If 'app-xyz' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
    3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
 
```

The same test locally:
```
 PASS  src/app/some-module/some.component.spec.ts
  ● Console

    console.error
      Can't bind to 'useCompactLayout' since it isn't a known property of 'app-xyz'.

      at logUnknownPropertyError (../packages/core/src/render3/instructions/shared.ts:1123:11)
      at elementPropertyInternal (../packages/core/src/render3/instructions/shared.ts:1006:9)
      at ɵɵproperty (../packages/core/src/render3/instructions/property.ts:42:5)
      at SomeComponent_Template (ng:/SomeComponent.js:483:49)
      at executeTemplate (../packages/core/src/render3/instructions/shared.ts:537:5)
      at refreshView (../packages/core/src/render3/instructions/shared.ts:395:7)
      at refreshComponent (../packages/core/src/render3/instructions/shared.ts:1714:7)
      at refreshChildComponents (../packages/core/src/render3/instructions/shared.ts:148:5)
```

**Comment by inorganik** [comment] 2021-04-09 15:27
I was able to get the test to properly fail by clearing untracked files, reinstalling packages, and testing. I haven't looked into why untracked files would affect the test passing, could be a jest issue. But this worked for me.
```
git clean -xfd
npm i
npm t
```

**Comment by monutam91** [comment] 2021-07-06 12:40
Is there any update on this? I'm experiencing the same issue, running jest tests in an NX monorepo. On our CI, I've got a bunch of errors logged out about missing components, but locally, I don't get anything. Even if I run it on a completely clean state, like @inorganik mentioned, I still don't get the errors locally.
Is there a workaround for this maybe?

**Comment by eegeeZA** [comment] 2021-07-06 13:42
For a workaround, I have added the code below to our `src/test.ts` file.

```ts
// https://github.com/angular/angular/issues/36430
// eslint-disable-next-line @typescript-eslint/no-explicit-any
console.error = (data: any) => fail(data);
```

**Comment by eegeeZA** [comment] 2021-07-06 13:43
For a workaround, I have added the code below to the end of our `src/test.ts` file.

```ts
// https://github.com/angular/angular/issues/36430
// eslint-disable-next-line @typescript-eslint/no-explicit-any
console.error = (data: any) => fail(data);
```

**Comment by monutam91** [comment] 2021-07-07 08:58
We are currently migrating to jest and I experience this issue only in jest tests. I tried to add something similar to one of my failing component test's beforeEach like this:
```ts
beforeEach(() => {
  const orgConsoleError = console.error;

  console.error = function (...args: any[]) {
    orgConsoleError.apply(this, args);

    console.info('console.error', args);

    throw new Error('console.error was called, this is not allowed in a unit test run');
  };
});
```

But it did not helped. The compileComponents haven't throw an error, as far as I can check it out. I've put a .catch on it, but so far, I couldn't get the error on my local environment.
I'm not entirely sure, that my problem is related to this issue, but it is very similar.

**Comment by brmc** [comment] 2021-08-11 03:21
Is there any update on this? In addition to these errors not preventing tests from failing, they hide other problems. once an unknown element is encountered the rest of the tests do not run but the test is marked as a success. that's incredibly frustrating and dangerous

**Comment by mnickla** [comment] 2021-08-16 06:04
same problem here using jest :(

**Comment by mnickla** [comment] 2021-08-16 07:44
> Is there any update on this? I'm experiencing the same issue, running jest tests in an NX monorepo. On our CI, I've got a bunch of errors logged out about missing components, but locally, I don't get anything. Even if I run it on a completely clean state, like @inorganik mentioned, I still don't get the errors locally.
> Is there a workaround for this maybe?

have you found a solution for this using nx ?

**Comment by distante** [comment] 2021-09-01 07:57
Monkey patching `console.error` does not work always. No idea why.

**Comment by gagle** [comment] 2021-10-05 11:30
I have this:

```
const originalConsoleError = window.console.error;

console.error = (...args: unknown[]): void => {
  const message = args[0].toString();
  if (message.startsWith('NG0304')) {
    const err = new Error(message);
    Error.captureStackTrace(err, console.error);
    throw err;
  }

  originalConsoleError(...args);
};
```

**Comment by KissBalazs** [comment] 2021-10-21 08:50
It would be nice if this feature could be a flag option to fail the test run upon any `console.error`. This way compatibility wouldn't be hurt.

**Comment by kevinmerckx** [comment] 2022-01-04 14:12
Isn't it a bug that is a breaking change introduced recently? Therefore, fixing this issue shouldn't be considered a breaking change, but rather a fixing change.

**Comment by cexbrayat** [comment] 2022-05-04 19:51
We landed two PRs that introduce new options for the `TestBed` in Angular v14 and that should fix this issue. 

You can now enable `errorOnUnknownElements` and/or `errorOnUnknownProperties` when setting up the `TestBed` globally or in a specific test to throw an error on unknown elements or unknown properties encountered in templates (instead of just logging the NG303/NG304 error).

These new options are opt-in for now.

If you're using the CLI, you can enable them globally in `test.ts`
```ts
getTestBed().initTestEnvironment(
  BrowserDynamicTestingModule,
  platformBrowserDynamicTesting(),
  { 
    errorOnUnknownElements: true,
    errorOnUnknownProperties: true
  }
);
```

Or you can enable/disable them in a specific test:
```ts
TestBed.configureTestingModule({
  declarations: [AppComponent],
  errorOnUnknownElements: true, 
  errorOnUnknownProperties: false
})
```

See https://next.angular.io/api/core/testing/TestModuleMetadata

**Closed by cexbrayat** 2022-05-04 19:51 UTC
Labels: type: bug/fix, comp: testing, freq3: high, regression, comp: core, engine: ivy, state: confirmed, core: directive matching, P4
