### ISSUE TITLE
New TestBed.get shows deprecation warning for abstract types and everywhere if using a strict tsconfig

### ISSUE THREAD

**Issue by cexbrayat** [angular/angular#29905] opened 2019-04-15 13:30 UTC
# 🐞 bug report

### Affected Package

The issue is caused by package @angular/core/testing

### Is this a regression?

Yes, the previous version in which this bug was not present was: `8.0.0-beta.11`

### Description

`8.0.0-beta.12` introduced a new `TestBed.get` method and deprecated the existing one (see 
https://github.com/angular/angular/commit/609024f93dc2df038ca5c3d8bfc2406ca5a2a6ac):

https://github.com/angular/angular/blob/609024f93dc2df038ca5c3d8bfc2406ca5a2a6ac/packages/core/testing/src/test_bed.ts#L246-L256

The new signature should be transparent for users as `const service = TestBed.get(UserService);` works.

But the new signature does not work with abstract types, like for example `HttpTestingController` (see https://github.com/angular/angular/blob/master/packages/common/http/testing/src/api.ts#L29) which leads to confusing deprecation warnings.

Update: this is even happening on every `TestBed.get` calls if you have a strict tsconfig, see https://github.com/angular/angular/issues/29905#issuecomment-483651602

## 🔬 Minimal Reproduction

```typescript
import { TestBed } from '@angular/core/testing';
import { HttpClientTestingModule, HttpTestingController } from '@angular/common/http/testing';

describe('UserService', () => {
  beforeEach(() => TestBed.configureTestingModule({
    imports: [HttpClientTestingModule]
  }));

  it('should be created', () => {
    const http: HttpTestingController = TestBed.get(HttpTestingController);
    expect(http).toBeTruthy();
  });
});
```

## 🔥 Exception or Error

`ng lint` shows:

```
/src/app/user.service.spec.ts:10:49 - get is deprecated: from v8.0.0 use Type<T> or InjectionToken<T>
```

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.0.0-beta.13
Node: 11.11.0
OS: darwin x64
Angular: 8.0.0-beta.12
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.0-beta.13
@angular-devkit/build-angular     0.800.0-beta.13
@angular-devkit/build-optimizer   0.800.0-beta.13
@angular-devkit/build-webpack     0.800.0-beta.13
@angular-devkit/core              8.0.0-beta.13
@angular-devkit/schematics        8.0.0-beta.13
@angular/cli                      8.0.0-beta.13
@ngtools/webpack                  8.0.0-beta.13
@schematics/angular               8.0.0-beta.13
@schematics/update                0.800.0-beta.13
rxjs                              6.4.0
typescript                        3.4.3
webpack                           4.29.6
</code></pre>

cc @Goodwine who wrote it and @mhevery who reviewed: I have not followed closely but couldn't `get<T>(token: T | InjectionToken<T>, notFoundValue?: T, flags?: InjectFlags): any;` be enough?

**Comment by Goodwine** [comment] 2019-04-15 17:30
For abstract types you should cast to `Type<MyAbstract>`

> couldn't `get<T>(token: T | InjectionToken<T>, notFoundValue?: T, flags?: InjectFlags): any;` be enough?

No because `MyClass` as an argument is type `typeof MyClass`

**Comment by Goodwine** [comment] 2019-04-15 17:33
For example: if you were using `Injector.get` to get `ChangeDetectorRef`, you'd get the same warning because `ChangeDetectorRef` is an abstract class and you'd need to cast to `Type<ChangeDetectorRef>`.

The change in `TestBed.get` was to make the function signature slightly similar to `Injector.get`, but having it return `any` for now, My plan is to send a PR for review where `TestBed.get<T>` would return a type `T` instead of `any`.

More info on Issue #26491

**Comment by cexbrayat** [comment] 2019-04-16 09:30
@Goodwine Thank you for your answer. Yeah I knew this was the goal and I very much look forward to it ;) 

My point is:
- can we have a better signature to not have to explicitely cast to `Type<MyAbstract>`?  (looks like no)
- if no, maybe the deprecation message and the changelog message should be more explicit about this use-case. `Injector.get` is not used that often in an application, whereas `TestBed.get` is used in pretty much every service unit test. So the deprecation message is showing up a lot after upgrading and other developers are going to wonder if this is normal or not.

**Comment by cexbrayat** [comment] 2019-04-16 13:07
I realize the new signature has another issue. I had many warnings with abstract classes but I also had others that looked weird and I figured it out.

If you have a strict TS config, more specifically if you have `strictFunctionTypes` turned on (which is the case if you activate the `strict` option), the deprecation warning shows up even for a simple case:

```typescript
@Injectable({
  providedIn: 'root'
})
export class UserService {

  constructor(private http: HttpClient) {}

}
```

```typescript
const service: UserService = TestBed.get(UserService); // tslint is unhappy
```

I guess this is because the `Type` signature in `core.d.ts` is:

```typescript
export declare const Type: FunctionConstructor;

export declare interface Type<T> extends Function {
    new (...args: any[]): T;
}
```

(which is OK for bivariance check but not for contravariance check like `strictFunctionCheck` does).

This is going to be confusing for developers that activated the `strict` option in their TS config.

**Comment by Goodwine** [comment] 2019-04-16 15:56
Re: better type for abstract class
Yes, there will be a better signature for `get` where you don't have to cast the abstract class

Re: `strictFunctionCheck`
Let me ask a coworker

**Comment by Goodwine** [comment] 2019-04-16 18:38
@cexbrayat I tried reproducing the issue and couldn't, I guess that's because the error comes from a tslint check and not from the compiler `strict` option, what rule is the one failing?
I looked at https://palantir.github.io/tslint/rules/ and the only one that looked similar was [strict-type-predicates](https://palantir.github.io/tslint/rules/strict-type-predicates/), is that the one that failed for you? Or do you have your own `strictFunctionCheck` tslint rule?

repro attempt: (in options enable `strictFunctionTypes`) [playground](https://www.typescriptlang.org/play/#src=const%20Type%20%3D%20Function%3B%0D%0Ainterface%20AbstractType%3CT%3E%20extends%20Function%20%7B%20prototype%3A%20T%3B%20%7D%0D%0Ainterface%20Type%3CT%3E%20extends%20Function%20%7B%20new(...args%3A%20any%5B%5D)%3A%20T%3B%20%7D%0D%0Aclass%20InjectionToken%3CT%3E%20%7B%0D%0A%20%20%20%20readonly%20_typerino!%3A%20T%3B%0D%0A%7D%0D%0A%0D%0Aclass%20TestBed%20%7B%20%0D%0A%20%20static%20get%3CT%3E(token%3A%20Type%3CT%3E%20%7C%20InjectionToken%3CT%3E%2C%20notFoundValue%3F%3A%20T%2C%20x%3F%3Astring)%3A%20any%3B%0D%0A%20%20%2F**%0D%0A%20%20%20*%20%40deprecated%20from%20v8.0.0%20use%20Type%3CT%3E%20or%20InjectionToken%3CT%3E%0D%0A%20%20%20*%2F%0D%0A%20%20%20%20static%20get(token%3A%20any%2C%20notFoundValue%3F%3A%20any)%3A%20any%3B%0D%0A%20%20%20%20static%20get(token%3A%20any%2C%20notFoundValue%3F%3A%20any)%3A%20any%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20%7B%7D%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Aclass%20Foo%20%7B%0D%0A%20%20%20%20c%20%3D%20'c'%0D%0A%7D%0D%0A%0D%0Aabstract%20class%20Bar%20%7B%0D%0A%20%20%20%20abstract%20x()%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Adeclare%20const%20fooToken%3A%20InjectionToken%3CFoo%3E%3B%0D%0A%0D%0Aconst%20foo%3A%20Foo%20%3D%20TestBed.get(Foo)%3B%0D%0Aconst%20bar%3A%20Bar%20%3D%20TestBed.get(Bar%20as%20Type%3CBar%3E)%3B%20%2F%2F%20Expected%20failure%20%3A%2F%0D%0Aconst%20fooTokenValue%3A%20Foo%20%3D%20TestBed.get(fooToken)%3B%0D%0A%0D%0A)

**Comment by cexbrayat** [comment] 2019-04-17 07:45
@Goodwine Sorry if I wasn't clear.

The TS rule failing is still the `deprecated` one. 
Because when `strict` or `strictFunctionCheck` option is enabled, `TestBed.get` doesn't match the new signature but the deprecated one. 

See repo for a reproduction: https://github.com/cexbrayat/test-bed-get

Or you can manually reproduce with:
```
ng new test-bed-get --defaults // using CLI 8.0.0-beta.15
cd test-bed-get
ng g s user
```

Replace user.service.ts by:
```
import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';

@Injectable({
  providedIn: 'root'
})
export class UserService {

  constructor(private http: HttpClient) {}
}
```

Change the `tsconfig.json` file to have the `strict` option enabled:
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "module": "esnext",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "strict": true,
    "importHelpers": true,
    "target": "es2015",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2018",
      "dom"
    ]
  }
}
```
Then run `ng lint`, you should get:

```
WARNING: test-bed-get/src/app/user.service.spec.ts:9:42 - get is deprecated: from v8.0.0 use Type<T> or InjectionToken<T>
```

**Comment by Goodwine** [comment] 2019-04-18 17:34
Thanks for the detailed repro steps, I'll take a look tomorrow and will try to come up with a PR to fix this issue.

**Comment by Goodwine** [comment] 2019-04-19 21:14
This is - https://github.com/Microsoft/TypeScript/issues/24428

I'll see whether I can update `Type<T>` as suggested over there

**Comment by cexbrayat** [comment] 2019-05-16 16:14
After talking to the team it was decided to temporarily remove the `@deprecated` annotation to avoid too much noise in v8, until we properly fix it. See #30514

**Comment by Goodwine** [comment] 2019-05-16 16:26
Thanks, can you look at my 2 PRs that would fix this?

**Comment by cexbrayat** [comment] 2019-05-16 16:33
@Goodwine I pinged the team about that, and someone that knows more than me will review (but v8 is keeping everyone pretty busy so we decided to remove the deprecation annotation as a first easy fix). 👍 Thanks for your help @Goodwine

**Comment by kara** [comment] 2019-05-24 02:12
Closed by https://github.com/angular/angular/commit/561e01ddfd4ddb3481641ac9d95b1938391ec370

**Comment by cexbrayat** [comment] 2019-05-24 05:21
@kara I think we should keep this open until we properly fix it. The commit removing the `@depecated` tag was just a quick fix to avoid too much noise in v8 and only partially address the issue.

For example the new signature still forces us to write:

```typescript
import { Type } from '@angular/core';

const http = TestBed.get(HttpTestingController as Type<HttpTestingController>);
```

which is not ideal.

**Comment by jkyoutsey** [comment] 2019-06-13 18:51
How did this get overlooked on the upgrade guides and breaking changes? Unit tests are not second class code.  I'm seeing this in the latest release version 8.0.0.  Are we awaiting a quick bug-fix release that will allow this to work? Or for 8.0.0 do I just have to use the new `get<T>`?

**Comment by Splaktar** [comment] 2019-06-30 09:29
@jkyoutsey this wasn't meant to be a breaking change, but due to a TSLint bug it ended up being one. `@angular/core@8.0.2` should resolve this temporarily.

https://github.com/angular/angular/blob/a73b8a62c86da396ce602215241d7eef8ffd40ae/packages/core/testing/src/test_bed_common.ts#L117-L126

**Closed** 2019-08-29 04:26 UTC
Labels: comp: testing
