### ISSUE TITLE
bug(forms) Initial select option set to null not working on IE/Edge

### ISSUE THREAD

**Issue by patrickracicot** [angular/angular#10010] opened 2016-07-12 18:23 UTC
**I'm submitting a ...**

```
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When setting the initial value of a `<select>` control to either null or undefined, the rendered `<select>` element displays the first `<option>`.

**Expected/desired behavior**
If the value of the Control is set to null, undefined or to a value not found in the list of options, the rendered element should displays an empty select.

**Reproduction of the problem**
Here is a plnkr: 
[http://plnkr.co/edit/7aHyWPt41YdvQH09MH8x?p=preview](http://plnkr.co/edit/7aHyWPt41YdvQH09MH8x?p=preview)

**What is the expected behavior?**
The current behavior found on Chrome and Firefox are the expected behavior.

**What is the motivation / use case for changing the behavior?**
The `<select>` element that is rendered should not display a selected option if the model backing it is not set to the value of that option.

**Please tell us about your environment:**
- **Angular version:** 2.0.0-rc.4
- **Browser:** IE 11 & Edge 25
- **Language:** TypeScript 1.8.10

**Comment by gstgusts** [comment] 2016-07-25 14:24
We have the same issue in IE
![ie11_problem](https://cloud.githubusercontent.com/assets/19387973/17104673/90a31004-528c-11e6-85f6-9afd9720b9d5.png)

**Comment by MrHOY** [comment] 2016-07-26 02:52
I have same issue too... I set ngModel is null and it work good on chrome
![chrome](https://cloud.githubusercontent.com/assets/20653706/17124560/3551cfbc-5316-11e6-92d7-462839d2800f.jpg)
but on IE/Edge always selected the first value so I can't handling event ngModelChange if user not change new value. 
![ie](https://cloud.githubusercontent.com/assets/20653706/17124623/ab5d631a-5316-11e6-8e55-5cd08e634bb7.jpg)

**Comment by gnujeremie** [comment] 2016-08-12 12:48
I have the same issue. The current fix woud be to add an empty option as the first options list of the select tag.

**Comment by patrickracicot** [comment] 2016-08-12 12:50
@gnujeremie Unfortunately this option is not always viable.  In a case where you don't want to permit a user the selection of an empty value once he has actually chosen one in the first place.

**Comment by gnujeremie** [comment] 2016-08-12 12:53
@patrickracicot then let's hope it will be fixed in RC6 !

**Comment by MartinMa** [comment] 2016-09-14 12:31
I have a workaround for this. Put `[disabled]="selectFixBool"` on your `<select>` element. `selectFixBool` is a boolean declared at the top of your component. Then assign `true` to it in the constructor of your component.
```
constructor () {
  // Other stuff.
  this.selectFixBool = true;
}
```
During `ngOnInit` you immediately switch it to `false` using `setTimeout()` (which enables the select control). Like this:
```
public ngOnInit() {
  // Small hack to fix select option bug for IE/Edge (see #10010)
  setTimeout(
    () => {
      this.selectFixBool = false;
    }
  );
}
```
I don't know why, but it works for me. I'm using angular `2.0.0-rc.6` right now.

**Comment by MrHOY** [comment] 2016-10-20 04:47
Now, this problem with safari and IE with angular2 2.0.1 final release.
Any solution for this ?

**Comment by MartinMa** [comment] 2016-10-24 12:33
This also affects the current Extended Support Release (ESR) of Mozilla Firefox (version 45)!

**angular: 2.1.0**

> Mozilla will offer an Extended Support Release (ESR) based on an official release of Firefox for desktop for use by organizations including schools, universities, businesses and others who need extended support for mass deployments.

As a workaround I hook into the `ngAfterViewInit` lifecycle event and call 
```
$('#my-select').prop('selectedIndex', -1); // Using jQuery to unset the selected index.
```

Repeat, when changing the model for the select options afterwards
```
setTimeout(
  () => {
    $('#job-title-select').prop('selectedIndex', -1);
  }
);
```
This temporarily fixes the issue for me on FF ESR 45, Edge 14, IE 11.

**Comment by ClementParis016** [comment] 2016-11-04 18:19
This one is related to #10349, the bug appears in IE, Edge & Safari.
PR #12026 seems to be addressing the issue.

**Comment by DzmitryShylovich** [comment] 2016-12-11 00:28
https://github.com/angular/angular/issues/10349 was fixed. can this be closed?

**Comment by DzmitryShylovich** [comment] 2016-12-26 15:23
@patrickracicot can u reproduce the issue using the latest version?

**Comment by patrickracicot** [comment] 2016-12-26 17:28
I will try next week (currently out of town)

**Comment by MrHOY** [comment] 2016-12-27 10:34
Now, I used angular 2.4.0 but issue not fix. Initial select option set to null not working on IE/Edge and Safari

**Comment by DzmitryShylovich** [comment] 2016-12-27 10:35
@MrHOY can u add a small repro in plunkr?

**Comment by MrHOY** [comment] 2016-12-27 11:05
@DzmitryShylovich You can try [https://plnkr.co/edit/wxAhioTFYDSB4vTb0zGY?p=preview](url) with IE/Edge or Safari

**Comment by DzmitryShylovich** [comment] 2016-12-27 11:09
@MrHOY I see, thx

**Comment by andreroggeri** [comment] 2017-01-04 02:14
The same happens on Samsung Browser.

The worst part is that if you have form validation and there is only one option on the select, the form will never be valid. :(

**Comment by Gordievich** [comment] 2017-01-12 09:26
As a quick hack, i did this.
In my case when [ngModel] sets to "undefined", i have as first option 
<option value="undefined" disabled selected></option>
and it worked well for me.

Tested on Edge/IE11
Using Angular 2.2.1

**Comment by MrHOY** [comment] 2017-01-12 11:50
@Gordievich , I tried with your solution, with Edge/IE 11 look good, but with Chrome it has null space on the list and look so bad. Did you try with Chrome ?

**Comment by DzmitryShylovich** [comment] 2017-01-12 11:59
This is appears to be a edge/ie bug https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/10332080/

**Comment by patrickracicot** [comment] 2017-01-12 12:22
Did anybody try and reproduce it with Firefox and Safari (since the original bug was always on those two browsers)?  If the bug is only IE related, I guess it means we won't make any fixes in Angular and wait for the fix from microsoft.

**Comment by andreroggeri** [comment] 2017-01-12 12:24
@DzmitryShylovich @patrickracicot The same happens with Samsung Internet browser for android devices.

**Comment by MrHOY** [comment] 2017-01-12 12:26
@patrickracicot I had tried and I see with Chrome and Firefox work good, Edge/IE and Safari have problem

**Comment by Gordievich** [comment] 2017-01-14 10:19
@MrHOY what do you mean "it has null space on the list and look so bad"
Yes I've tried with Chrome and it looks good there too.

I'm also using Materializecss framework. which interpret `<select>` to `<input> <ul>`

**Comment by MrHOY** [comment] 2017-01-14 10:25
@Gordievich  Can you add a small repro in plunkr ? Maybe I wrong.

**Closed** 2017-01-29 19:01 UTC
Labels: comp: forms, freq3: high, severity3: broken, type: bug

**Comment by JohannesRudolph** [comment] 2017-02-13 21:45
I'm on 2.4.7 and still experience this issue in Safari + MS Edge. Anybody have set up a plunkr for repro already? 

I'm currently using the following workaround `<option *ngIf="!model.address.continent" value="undefined" disabled selected></option>` as a compromise, but I'd prefer if it wasn't required. Using this workaround I can set my model property bound to the `<select>` control to undefined and get reasonable behavior across all browsers.

**Comment by DzmitryShylovich** [comment] 2017-02-13 21:52
@JohannesRudolph https://plnkr.co/edit/CX6nTuMDj5d3YbpvI4Yp?p=preview
don't have Safari but it's not reproducible in ie/edge

**Comment by chen39636** [comment] 2017-02-25 17:58
I updated to 2.4.8 and using ReactiveForm and having the same issue in ie.

**Comment by DzmitryShylovich** [comment] 2017-02-25 18:02
@chen39636 yeah, it still doesn't work with reactive forms https://github.com/angular/angular/issues/14505

**Comment by ceyon** [comment] 2017-04-13 17:51
using IE 11 , angular 4
![2017_04_13_13_48_29](https://cloud.githubusercontent.com/assets/27440748/25017004/1d56af06-2050-11e7-976e-464b8b0601ca.png)
![2017_04_13_13_49_12-1](https://cloud.githubusercontent.com/assets/27440748/25017005/1d595080-2050-11e7-997c-8b3dbba5f9f4.png)

 . `	
					<select class="form-control" id="SHospital" formControlName="SelectHospital">
						<optgroup label="Choose...">
							<option value="All Hospitals">All Hospitals</option>
							<option value="2">Two</option>
							<option value="3">Three</option>
							</optgroup>
					</select>`

initial option group label doesn't automatically load.  If I remove "formControlName " it will load.

**Comment by wiredprogrammer** [comment] 2017-07-10 19:26
As of 4.1.3 this is still broken in reactive forms on IE11.  This also causes issues in the rare cases where a select tag only has one option.  You can't select the only option in the select tag.

**Comment by danishin** [comment] 2017-07-26 11:09
I can confirm that this issue still exists in all of IE, Edge and Safari. Works as expected in Chrome and Firefox. Our clients were confused because of this.

Currently using Angular 4.1.3. 

Can we re-open this issue please?

**Comment by Chyngyz** [comment] 2017-08-21 11:36
Experiencing same issue in Safari. Angular 4.2.5.

**Comment by mixrich** [comment] 2017-09-21 11:38
The probles still exists with ReactiveForms
In Edge and Safari the first item of select is shows as selected, but the form value for select is actually empty. In Chrome everythink is ok.
https://plnkr.co/edit/Zmz7NNRgV7oYUXkHf2m8?p=preview

**Comment by MartinMa** [comment] 2017-09-21 14:30
I can confirm the problem for Edge 15 using @mixrich's plunker with Angular v4.4.3.

**Comment by nicam** [comment] 2017-10-09 08:23
Same issue on IE 11 and Edge

**Comment by karthikv-26** [comment] 2017-10-17 18:50
Facing same issue with IE11 for reactive forms, Dont have Edge. Any update on this?

**Comment by vrudikov** [comment] 2017-10-25 22:18
Facing same issue with IE11 & Safari for reactive forms. In Safari first element is selected and disabled.

**Comment by nicam** [comment] 2017-10-26 06:25
We worked around the issue by executing a selectedIndex = '-1' on ngOnInit()

**Comment by monica7l** [comment] 2017-11-10 14:21
I made it work by adding as default value <option value="-1" disabled>-- selected --</option>

**Comment by mixrich** [comment] 2017-11-11 10:04
@monica7l Yes, I did the same way to get my APP working well in Edge and Safari, but adding the default disabled option is not what Ireally want, because I prefer placeholder, but no one more option

**Comment by rtaft** [comment] 2018-04-30 13:46
Why was this closed?  I see it on chrome.  Adding a disabled option first does not help and the form group is not valid even though something is selected by default.

**Comment by timby** [comment] 2018-12-04 22:31
This issue was reported over 2 years ago and it has yet to be fixed. I think it should be given some priority to have it fixed. Personally, I would appreciate it if fixing existing issues was given higher priority than adding new features.

**Comment by wbartosz** [comment] 2019-03-15 16:19
Any progress on this? I still experience this issue in IE11.

**Comment by TakeshiDaveau** [comment] 2019-04-02 15:47
Same for me on IE11

**Comment by cjablonski76** [comment] 2019-04-04 15:40
Please reopen this issue, and let us know if there is any way to fix the problem.

**Comment by solanaprojordan** [comment] 2019-07-29 14:30
I face the same issue on IE and Safari.

**Comment by marcellkiss** [comment] 2019-08-10 19:51
The problem exists in Safari.
