### ISSUE TITLE
when using router.navigate(…) with relative url, angular should warn if {relativeTo} is not set

### ISSUE THREAD

**Issue by iuliust** [angular/angular#26027] opened 2018-09-20 00:59 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
When I use router.navigate with a relative route with no relativeTo option, Angular doesn't log any warn message.

## Expected behavior
I should get a warning about how to use relativeTo option

## Minimal reproduction of the problem with instructions
navigate with a relative url with no options

## What is the motivation
I just spent half an hour scratching my head because I couldn't figure out why I wouldn't get redirected to the correct route. See, when I write <a routerLink="../.."> in the HTML template of the component, I'm navigated to the correct route. But when I use the very same relative route in my component, I'm not redirected to the correct route.

It would be better if a warning was printed in the console about this option.

## Environment

<pre><code>
Angular version: 7.0.0-beta.5

Others:

</code></pre>

**Comment by jasonaden** [comment] 2018-11-20 23:34
Thanks. This sounds like a very reasonable idea.

It would be great if a community member could grab this one. Should be relatively straightforward to implement.

**Comment by atscott** [comment] 2020-12-04 18:47
I'm actually going to close this as working as intended. An undefined `relativeTo` equivalent to navigating relative to the root. We should avoid producing new warning messages for situations that are valid use-cases. Applications which use `router.navigate` in this way would get new warning messages. Warning messages are also more likely to be ignored the more that they're produced.

**Closed by atscott** 2020-12-04 18:47 UTC
Labels: comp: router, feature, freq3: high, hotlist: community-help
