### ISSUE TITLE
Custom form control couldn't get the right value from onPush parent component.

### ISSUE THREAD

**Issue by deart1mer** [angular/angular#21780] opened 2018-01-25 15:56 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Custom form control couldn't get the right value from `onPush` parent component.
I wrote a simple custom counter.
```ts
@Component({
  selector: 'counter',
  template: `
    Child Component
    <button (click)="increase($event)">+</button>
    {{counter}}
    <button (click)="decrease($event)">-</button>
  `,
  providers: [{
    provide: NG_VALUE_ACCESSOR,
    useExisting: forwardRef(() => CounterComponent),
    multi: true
  }]
})
export class CounterComponent implements ControlValueAccessor {
  private counter = 0;
  private onChange: (_: any) => void;
  private onTouched: () => void;

  writeValue(value) {
    console.log(`Write value`, value);
    this.counter = value;
  }
  registerOnChange(fn: (_: any) => void): void { this.onChange = fn; }
  registerOnTouched(fn: () => void): void { this.onTouched = fn; }
}
```
Then I use it in a component with `ChangeDetectionStrategy.onPush`.
```ts
@Component({
  selector: 'ngmodel-demo',
  template: `
    <h3>Parent Component with onPush</h3>
    <p>Parent's Count: {{count}}</p>
    <counter [(ngModel)]="count"></counter>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class NgmodelDemoComponent {
  public count = 1;
  constructor(private _cdRef: ChangeDetectorRef) {}
}
```
When I run the app, I found that the counter component have got the value 1, but its view didn't update.
Then I try to set a timer to update the `ngModel` and mark for check.
```
ngOnInit() {
  setInterval(() => {
    this.count = ++this.count;
    this._cdRef.markForCheck();
  }, 3000);
}
```
The result is that each time the value that counter component's view shows is the value of the last ngModel's.

## Expected behavior

The child component's view show the same value as parent's.

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/angular-cfc-writevalue

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by deart1mer** [comment] 2018-01-31 08:51
https://github.com/angular/angular/blob/master/packages/forms/src/directives/ng_model.ts#L254-L257

```ts
private _updateValue(value: any): void {
  resolvedPromise.then(
      () => { this.control.setValue(value, {emitViewToModelChange: false}); });
}
```

In ngmodel directive, `setValue` is called in next micro-task queue. So the parent component and the ngmodel component are not in one dirty check! And the ngmodel component would be checked later then the parent component. When the later dirty check running, because of the `OnPush` strategy, the parent component will stop the ngmodel component's check.

**Comment by deart1mer** [comment] 2018-02-01 02:34
```ts
private _updateValue(value: any): void {
  resolvedPromise.then(() => {
    this.changeDetectorRef.markForCheck();
    this.control.setValue(value, {emitViewToModelChange: false});
  });
}
```
Call `markForCheck` in the NgModel Directive would make this case works. 
https://stackblitz.com/edit/angular-3eus2q?file=app%2Fmodel.directive.ts

**Comment by admosity** [comment] 2018-02-26 21:56
This seems related to #22461. Basically your custom form control is behaving like it is using `OnPush` because of a parent component.  Here's a fix:

https://stackblitz.com/edit/angular-cfc-writevalue-mccr8b?file=app%2Fcounter%2Fcounter.component.ts

**Comment by deart1mer** [comment] 2018-02-27 03:44
@admosity 
I think angular should fix this rather than we do.
When the child component was from third part ui vendors, they don't know if you are using the `onPush` strategy. They won't do any fix that triggering cd in writeValue.

**Comment by delashum** [comment] 2019-07-09 19:45
Was anyone able to find a workaround for this? Calling `cd.detectChanges()` on my parent component didn't seem to help anything.

**Comment by deart1mer** [comment] 2019-07-10 02:06
> Was anyone able to find a workaround for this? Calling `cd.detectChanges()` on my parent component didn't seem to help anything.

You should call `cd.markForCheck` on `writeValue` method of form control component which implements `ControlValueAccessor`.

**Comment by AndrewKushnir** [comment] 2020-09-04 01:03
Hi, it looks like this issue has a root cause described in #10816. I'm closing this ticket as a duplicate, please subscribe to #10816 for further discussion/updates. Thank you.

**Closed by AndrewKushnir** 2020-09-04 01:03 UTC
Labels: comp: forms, forms: change detection, freq2: medium, severity3: broken, state: needs more investigation, triage #1, type: bug/fix
