### ISSUE TITLE
Library build fails silently with circular dependency

### ISSUE THREAD

**Issue by SebastianPodgajny** [angular/angular#35978] opened 2020-03-10 00:34 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/*@9.0.5

### Is this a regression?

It was working without Ivy

### Description

 
Component_A has Component_B inside template, Component_B imports some types from Component_A  
`ng build lib` succeeds without any error
Component_A definition lacks `directives` field with leads to unrelated errors hard to debug

## 🔬 Minimal Reproduction

 https://stackblitz.com/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.0.5
Node: 12.10.0
OS: darwin x64

Angular: 9.0.5
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.900.5
@angular-devkit/build-angular      0.900.5
@angular-devkit/build-ng-packagr   0.900.5
@angular-devkit/build-optimizer    0.900.5
@angular-devkit/build-webpack      0.900.5
@angular-devkit/core               9.0.5
@angular-devkit/schematics         9.0.5
@angular/cdk                       9.0.0
@ngtools/webpack                   9.0.5
@schematics/angular                9.0.5
@schematics/update                 0.900.5
ng-packagr                         9.0.2
rxjs                               6.5.4
typescript                         3.7.5
webpack                            4.41.2
</code></pre>

**Anything else relevant?**

**Comment by pkozlowski-opensource** [comment] 2020-03-10 07:47
@SebastianPodgajny could you please provide a minimal reproduce scenario (GitHub repo) illustrating this issue?

**Comment by SebastianPodgajny** [comment] 2020-03-10 10:23
@pkozlowski-opensource 
Repository https://github.com/SebastianPodgajny/ivy-lib-circular-dependency
This component should have `directives: [ComponentB, ComponentC]`
https://github.com/SebastianPodgajny/ivy-lib-circular-dependency/blob/master/dist/repro/fesm2015/repro.js#L20-L32

**Comment by JoostK** [comment] 2020-03-10 19:26
The component's scope information is patched onto it using this call (you can find it in the ES2015 bundle you linked):

```js
ɵɵsetComponentScope(ComponentA, [ComponentA, ComponentB, ComponentC], []);
```

This is done to resolve the circular dependency, but this call may be dropped by optimizers as libraries have `sideEffects: false` by default. Please find more information in #35602 as it describes the same situation and a workaround for this issue.

Closing as duplicate of #35602.

**Closed by JoostK** 2020-03-10 19:26 UTC
Labels: comp: compiler, severity5: regression
