### ISSUE TITLE
routerLink directive does not respect `event.preventDefault()` to prevent navigation

### ISSUE THREAD

**Issue by josephperrott** [angular/angular#21457] opened 2018-01-10 23:57 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Attempting to prevent navigation for an anchor with a routerLink by calling `event.preventDefault()` on the click event has no effect.

## Expected behavior

When `event.preventDefault()` is called on the click event, navigation should be prevented.

## Minimal reproduction of the problem with instructions

[Link to Repro](https://stackblitz.com/edit/router-prevent-default-repro?file=app%2Fapp.component.ts)

Clicking on "catalog" still navigates to the catalog view, event though the `<a>` tag contains `(click)="$event.preventDefault()`

## Environment
Angular version: `5.2.0`

**Comment by adrienboulle** [comment] 2018-01-30 22:36
related to this https://github.com/angular/angular/issues/10431

**Comment by hansih91** [comment] 2018-02-06 15:17
i updated from 5.0.2 to 5.3.2 and now its working:
`(click)="partcipate();$event.preventDefault();$event.stopPropagation()"`

**Comment by maximelafarie** [comment] 2018-02-21 15:54
@hansih91 Angular _**5.3.2**_ ?? RLY ? 🤔

**Comment by hansih91** [comment] 2018-02-25 19:14
@maximelafarie yes

**Comment by trotyl** [comment] 2018-02-26 08:13
So what's the expected semantics here?

Imaging that you have a directive called `disableClick`, it does only listen to `click` event and call `preventDefault` in its handler, can be used like:

```html
<button disableClick (click)="foo = $event"></button>
```

So in this case `foo` should not be changed to `42`, right?

Then question comes, both `routerLink` and `disableClick` are normal directive with normal `HostListener`s, why should the handler in `disableClick` runs before the handler in parent template, but opposite result (after) for `routerLink`?

Do you suggest that the execution order should depend on literal attribute order? What if a directive have a complex selector of multiple attributes?

**Comment by briancodes** [comment] 2018-03-02 12:56
@hansih91 Is it the update to Angular that solved the problem, or the addition of `event.stopPropogation()`? 
In the problem description you mentioned `event.preventDefault()` only, so wondering if the `stopPropogation()` is what solved it

**Comment by hansih91** [comment] 2018-03-03 11:49
@briancodes with version 5.0.2 not worked for me. after upgrade to 5.3.2 it worked.

**Comment by briancodes** [comment] 2018-03-03 12:22
@hansih91 I would just be concerned that unless there was a specific fix applied to the update to solve this issue, that it might just be the ordering of the event handling that is making it work now. So maybe this will change again in the future - and the current preventDefault and stopPropogation would no longer work

**Comment by Yura13** [comment] 2018-03-27 11:58
@hansih91 5.3.2 version doesn't exist

**Comment by hansih91** [comment] 2018-03-27 12:17
Sorry. It was a typo. I use version 5.2.3
 

Gesendet: Dienstag, 27. März 2018 um 13:59 Uhr
Von: "Yurii Dutchak" <notifications@github.com>
An: angular/angular <angular@noreply.github.com>
Cc: hansih91 <hansbauerz@web.de>, Mention <mention@noreply.github.com>
Betreff: Re: [angular/angular] routerLink directive does not respect `event.preventDefault()` to prevent navigation (#21457)


@hansih91 5.3.2 version doesn't exist

**Comment by bostondevin** [comment] 2018-07-20 16:18
Here's a trick - Just do this to keep it from navigating when you click:
<a [routerLink]="">My Unclickable Link</a>

**Comment by muniom** [comment] 2018-09-10 05:36
I've just had some success with a similar issue: having an array of nav links in an ngFor, some required [routerLink], while others required (click) - my issue was that all links relied on [routerLink] for [routerLinkActive], so I had to stop routerLink, without touching it's value.

`<a [routerLink]="item.link" routerLinkActive="isActive">`
`        <span (click)="item.click ? item.click($event) : void>`
`</a>`

with:

`click: ($event) => {`
`        $event.stopPropagation(); // Only seems to`
`        $event.preventDefault(); // work with both`
`        // Custom onClick logic`
`}`
As the span is inside, you can be sure the cancelling of the event happens before it bubbles up to [routerLink], while routerLinkActive will still apply.

**Comment by waterplea** [comment] 2018-10-03 09:28
I don't see how it is too hard for Angular team to add event.defaultPrevented to check for in HostListener of RouterLink. There could be other cases where you do want to prevent navigation from nested listener and still want the click to propagate. I, for example, have the case where I have a button 'X' to remove the link from the tab list of my app, I do not want to navigate to it when I click it, but I also have some other logic bound to bubbled click event (my links are in a dropdown and I want to close it on click).

**Comment by trotyl** [comment] 2018-10-04 07:38
@waterplea Please do consider have a look of the thread first, the problem is event handler for `RouterLink` being executed first than the handler in your component template, how can you prevent a already handled event?

```javascript
if (('click' === en)) {
  var pd_0 = (jit_nodeValue_4(_v,11).onClick($event.button,$event.ctrlKey,$event.metaKey,
      $event.shiftKey) !== false);
  ad = (pd_0 && ad);
}
if (('click' === en)) {
  var pd_1 = ($event.preventDefault() !== false);
  ad = (pd_1 && ad);
}
```

It's not related to any check, just the ordering. But the general idea is always NOT depend on event handlers in same elements running in specific order, so that the right fix is for `RouterLink` to expose a switch for user control.

**Comment by waterplea** [comment] 2018-10-04 10:42
I have read the thread. The real problem is that RouterLink click listener does not care about the event and its `defaultPrevented` value. An issue with order can REALLY EASILY be overcome by wrapping text into `span` inside the routerLink element and preventing default on click handler inside that `span`. Real links respect preventDefault and routerLink should too. **How** you prevent default is another story.

**Comment by trotyl** [comment] 2018-10-04 10:59
@waterplea Then you're free to use `stopPropagation()` besides `preventDefault()` if you can change the HTML structure.

**Comment by waterplea** [comment] 2018-10-04 11:22
stopPropagation is totally not the same as preventDefault. I explained in my original comment that I have a click listener higher in the DOM that does things. Overall stopPropagation should be the last resort because you can never know what else might depend on it. I believe it is rather pointless to discuss workarounds when a single:
```
if (event.defaultPrevented) {
    return;
}
```
is all it takes for RouterLink to behave closer to the native link and fix this issue which is reported not the first time already.

**Comment by trotyl** [comment] 2018-10-04 11:58
@waterplea All you suggested are workarounds, most people (including the reproduction of this issue) have the `(click)` event listener on the `<a>` element, not an internal `<span>`.

Also, [`preventDefault()` simply won't work in IE](https://stackoverflow.com/questions/1000597/event-preventdefault-function-not-working-in-ie), which is still a browser many people need to care about.

**Comment by waterplea** [comment] 2018-10-04 12:35
I didn't mean to sound hostile, sorry if I did. It would work in IE9+ which is the lowest version Angular supports. As of workarouds — my thesis was: native links ignore clicks with default behavior prevented, while routerLinks don't.

**Comment by trotyl** [comment] 2018-10-04 13:08
@waterplea Have had another look and `preventDefault()` on IE9+ seems only [broken for custom events](https://stackoverflow.com/questions/23349191/event-preventdefault-is-not-working-in-ie-11-for-custom-events), so likely could work for real `click`.

> native links ignore clicks with default behavior prevented, while routerLinks don't.

The problem is Angular is not browser, but a normal user same as you. Library code is actually just user code, the difference is only about dependency direction, once you extract something from your app it'll become the library, the point here it's about whether users' event handler should respect each other. And from my knowledge no one checks that in their event handler, or you should always write `(some-event)="$event.defaultPrevented && onSomeEvent()"`.

**Comment by gotwig** [comment] 2019-10-30 08:39
its pointless to talk about this when angular devs dont even listen.

**Comment by yasammez** [comment] 2019-11-26 16:37
Any update on this issue? I just ran into it and google let me here.

**Comment by filipelinhares** [comment] 2019-12-10 18:23
@yasammez, the [solution](https://github.com/angular/angular/issues/21457#issuecomment-363453982) from @hansih91 worked for me.

**Comment by pburgmer** [comment] 2020-02-28 14:28
I also have this problem.

**Comment by gentunian** [comment] 2020-02-29 16:21
From my perspective, you should handle your use case differently. If you won't allow navigation you may ask yourself then why you are setting an anchor link with `routerLink`. So, from my point of view, this is not a bug but a desired behaviour.

This proposal of preventing `routerLink` to navigate in a supposed element that should navigate won't allow you to prevent bubbling up the event while you desire the navigation to occur.

A simple example of state above may be a table that manages the click event for each row that and a column that has an anchor set with a `routerLink`. If you click in the anchor without stopping propagation, the click event will bubble up into the row. Stop propagation means that, stops bubbling up the event but handle the event in that DOM element. And, as `routerLink` is set in that element, then the action should not be cancelled.

I think you need to workaround your way for your use case as it sounds not to be expected behaviour.

**Comment by djmarquette** [comment] 2020-03-04 15:00
We have a need to allow an HTML page to open a routerLink in a new tab via right-click context menu.  However, when user clicks in a normal case we have a component click event that builds an object and passes it up a couple parent levels to open in a side-panel.  I am trying to intercept the default behavior of the routerLink using preventDefault() in an 'anchor-tag-directive' we rolled but am not having success.  Currently the link still opens in the current page, the default behavior for the routerLink tag.

I hope this helps explain why one might want to have a preventDefault() for a routerLink on a clickable element.

**Comment by adover** [comment] 2020-03-31 03:16
I did this differently @djmarquette and came up with the following solution. It seems to work well

`
@Directive({
	selector: 'a[maybeExternal], a[cdxMaybeExternal]',
})
export class MaybeExternalLinkDirective implements AfterViewInit {
	@HostBinding('attr.target') targetAttr = '';
	@HostBinding('attr.href') hrefAttr = '';
	@Input() href: string;

	constructor(@Inject(PLATFORM_ID) private platformId: string, private router: Router) {}

	ngAfterViewInit(): void {
		this.hrefAttr = this.href;

		setTimeout(() => {
			if (this.isLinkExternal()) {
				this.targetAttr = '_blank';
			}
		});
	}

	@HostListener('click', ['$event'])
	clicked(event: Event) {
		if (!this.isExternalLink(this.href)) {
			this.router.navigateByUrl(this.href);

			event.preventDefault();
		}

		this.targetAttr = '_blank';
	}

	isExternalLink(url: string) {
		return url.startsWith('https') || url.startsWith('http');
	}

	isLinkExternal() {
		return isPlatformBrowser(this.platformId) && !this.href.includes(location.hostname);
	}
}
`

**Comment by atscott** [comment] 2020-05-27 17:10
Regardless of the outcome of the debate over whether `routerLink` should respect `defaultPrevented`, it's clear there is a need for the ability to disable the `routerLink` navigation. This would be addressed in #35393/#31154. If/when that PR is merged, maybe this issue can be closed as well.

**Comment by digeomel** [comment] 2021-05-21 09:33
@atscott the related PR is closed due to inactivity and I just ran into the same issue. Any suggestions?

**Comment by gotwig** [comment] 2021-05-21 09:41
@digeomel 
Well I think you have to do 2 seperate Ng If Conditions because its not possible to do it with one directive, like you described...
or change framework because Angular is not that well maintained anymore (was it ever? IMHO)

**Comment by digeomel** [comment] 2021-05-21 11:34
I found a solution for our use case. I implemented a custom directive listening to the click handler, and a `canActiveChild` guard on all routes. The directive and guard use a common service to determine whether to cancel the default navigation or not.

@gotwig you could say a lot about Angular, but "not well maintained" is not apropriate for a framework that releases new versions more than twice per year 😄

**Comment by atscott** [comment] 2021-05-21 12:56
As discussed in https://github.com/angular/angular/issues/21457#issuecomment-361758239 and other places, `preventDefault` will not be respected. This issue is mainly kept open for discoverability as there are others that also track the need for disabling links.  
I was looking these for v12 but as you can probably tell from the release notes, there was a lot of other stuff going on. The components TL and I will be meeting soon and will come up with an answer that considers accessibility as well.

**Closed** 2021-08-20 19:51 UTC
Labels: freq2: medium, comp: router, type: use-case, triage #1, router: directives, P3
