### ISSUE TITLE
NPM readme: Add usage for bundle

### ISSUE THREAD

**Issue by Pro** [angular/angular#3930] opened 2015-09-01 07:08 UTC
The description for the NPM package (https://www.npmjs.com/package/angular2) should include instructions how to use ng2 directly in JS for a new webpage.

As a beginner you may tend to use the `node_modules/angular2/angular2.js` in the root folder, instead of `node_modules/angular2/bundles/angular2.js`
Including the first in your script tag doesn't cause any error message and some of the ng2 functionalities are available, but e.g. data binding doesn't work (again without any error).

Therefore the line `1. The files located in the root folder can be consumed using CommonJS` is misleading.
There should be added a line stating something like:
`The files in the bundles folder can be used in the script tag of your page`

**Comment by rolandjitsu** [comment] 2015-09-03 08:20
@mhevery probably a duplicate of [#3082](https://github.com/angular/angular/issues/3082) and [#3458](https://github.com/angular/angular/issues/3458)

**Comment by mhevery** [comment] 2015-09-28 21:25
dup

**Closed by mhevery** 2015-09-28 21:25 UTC
