### ISSUE TITLE
Verify that SEO works well with differential loading

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#30203] opened 2019-04-30 00:44 UTC
I tried to quickly test next.angular.io with https://search.google.com/test/mobile-friendly to ensure that SEO was not being broken, but that didn't work because of the robots.txt on next.angular.io.

So I deployed the version with 8.0.0-rc.2 (#30202) updates to https://angular-io-v42.firebaseapp.com/ and tested it and got an odd error ([results link](https://search.google.com/test/mobile-friendly?id=OaQNErp9LMuHLqOvGWDvmg)): 

<img width="444" alt="Screen Shot 2019-04-29 at 6 40 31 PM" src="https://user-images.githubusercontent.com/216296/56935435-4ec68e80-6aae-11e9-81c9-56c1d36f46c9.png">

Which seems to be due to some issue with how we transpile the code or load polyfills:

<img width="707" alt="Screen Shot 2019-04-29 at 6 41 59 PM" src="https://user-images.githubusercontent.com/216296/56935481-8d5c4900-6aae-11e9-92af-4028685e1b93.png">

Can someone check what's up with this and ensure that the SEO works, and ideally works OOB for any `ng new` project created with 8.0.0 - I think that now that we have the polyfills differentialy loaded there should be no reason for `ng new` not to be SEO-compatible out of the box (no advanced stuff, just not blow up).

// @petebacondarwin @filipesilva

**Comment by petebacondarwin** [comment] 2019-04-30 12:40
It looks like the problem is caused by Zone.js 0.9.0. 
This issue is almost identical... https://github.com/angular/zone.js/issues/1223#issuecomment-486110447

**Comment by JiaLiPassion** [comment] 2019-04-30 15:09
@petebacondarwin, I think this may related to https://github.com/angular/zone.js/pull/1214, and I made a branch to contain the latest version of `zone.js`, could you try to use this branch of `zone.js`, 
```
"zone.js": "git+https://github.com/JiaLiPassion/zone.js#latest-dist"
```

And if there is a way to test it, please tell me, I can also test it.

**Comment by JiaLiPassion** [comment] 2019-04-30 15:27
@petebacondarwin, I think this may related to https://github.com/angular/zone.js/pull/1214, and I made a branch to contain the latest version of `zone.js`, could you try to use this branch of `zone.js`, 
```
"zone.js": "git+https://github.com/JiaLiPassion/zone.js#latest-dist"
```

And if there is a way to test it, please tell me, I can also test it.

**Comment by petebacondarwin** [comment] 2019-04-30 16:15
It is quite straightforward to deploy AIO to Firebase

1. Create a project  at https://console.firebase.google.com/
2. Clone angular/angular
3. cd angular
4. yarn
5. cd aio
6. yarn setup
7. yarn build
8. yarn global add firebase-tools
9. firebase use <name-of-firebase-project>
10. firebase deploy

**Comment by petebacondarwin** [comment] 2019-04-30 16:16
Then head to https://search.google.com/test/mobile-friendly

**Comment by JiaLiPassion** [comment] 2019-04-30 16:27
@petebacondarwin, thank you, and I tested it here, https://aio-test-27ab8.firebaseapp.com/, everything works fine. So I will reach @vikerman to make a new release of `zone.js`.

**Comment by filipesilva** [comment] 2019-05-13 18:45
https://github.com/angular/angular-cli/pull/14415 will update new and upgrade CLI 8 projects to use zone.js 0.9.1 too.

**Comment by filipesilva** [comment] 2019-05-13 18:46
@petebacondarwin is there anything else left to do after CLI is also updated?

**Comment by petebacondarwin** [comment] 2019-05-16 09:36
I think that should be enough @filipesilva

**Comment by filipesilva** [comment] 2019-05-16 10:14
Closing as both AIO (https://github.com/angular/angular-cli/pull/14415) and CLI (https://github.com/angular/angular-cli/pull/14415) are now updated. CLI projects updating to 8 will automatically be migrated to this version of zone.js too.

**Closed by filipesilva** 2019-05-16 10:14 UTC
Labels: comp: docs-infra, severity5: regression, type: bug/fix

**Comment by Splaktar** [comment] 2019-05-16 23:54
I can't tell from the tags on those commits, but looking at history shows that this should be resolved in rc4 of both Angular and CLI.

**Comment by IgorMinar** [comment] 2019-05-25 06:51
Thank you @JiaLiPassion @filipesilva and @petebacondarwin !
