### ISSUE TITLE
Examples for NgTemplateOutlet is missing on new site

### ISSUE THREAD

**Issue by csvn** [angular/angular#56068] opened 2024-05-24 15:50 UTC
### Describe the problem that you experienced

When reading docs on `NgTemplateOutlet` on Angular.dev, I found that examples are missing [compared to Angular.io](https://v17.angular.io/api/common/NgTemplateOutlet). I'm not sure if this issue is specific to docs generated for only `NgTemplateOutlet`, or if it affects other directives/components/etc for generated docs.

### Enter the URL of the topic with the problem

https://angular.dev/api/common/NgTemplateOutlet?tab=usage-notes

### Describe what you were looking for in the documentation

Examples for how to use `NgTemplateOutlet`

### Describe the actions that led you to experience the problem

Opened "Usage notes" and found examples missing.

### Describe what you want to experience that would fix the problem

Make the example section look similar to Angular.io.

### Add a screenshot if that helps illustrate the problem

**Missing example:**
![image](https://github.com/angular/angular/assets/8770194/bf10254a-f476-47b5-8226-954522ad04e3)
**Example working:**
![image](https://github.com/angular/angular/assets/8770194/bda6a8e1-9884-4d64-b994-6010b797330f)

**Comment by JeanMeche** [comment] 2024-07-06 20:25
The issue is with the non-inlined examples : 

https://github.com/angular/angular/blob/229dd8355e91388f97523fc085197cf06d2fda65/packages/core/src/metadata/di.ts#L264-L271

**Comment by ashishnd** [comment] 2024-07-10 10:26
I would like to give this issue a shot if it's still open. @JeanMeche

**Comment by JeanMeche** [comment] 2024-11-24 22:48
Closing as dupe of #56321

**Closed by JeanMeche** 2024-11-24 22:48 UTC
Labels: P3, area: adev
