### ISSUE TITLE
form.disable() does not work in constructor and OnInit

### ISSUE THREAD

**Issue by n-pafitis** [angular/angular#31506] opened 2019-07-11 07:01 UTC
# 🐞 bug report
Issue is related to https://github.com/angular/angular/issues/23677 but since it hasn't been resolved yet i have put the effort into creating a stackblitz example

### Affected Package

 The issue is caused by package @angular/forms

### Description

 A clear and concise description of the problem...
Trying to call this.form.disable() in parent component's constructor or ngOnInit does not disable the form. Calling this.form.disable() in ngAfterViewInit **DOES** disable the form but 
throws error.

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-jfdvxj-rcle6r
You can reproduce this by uncommmenting the this.form.disable() calls in the above stackblitz sandbox

## 🔥 Exception or Error
<pre><code>
ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'ng-valid: true'. Current value: 'ng-valid: false'.
    at viewDebugError (errors.ts:35)
    at expressionChangedAfterItHasBeenCheckedError (errors.ts:21)
    at checkBindingNoChanges (util.ts:102)
    at checkNoChangesNodeInline (view.ts:477)
    at checkNoChangesNode (view.ts:461)
    at debugCheckNoChangesNode (services.ts:464)
    at debugCheckRenderNodeFn (services.ts:416)
    at Object.eval [as updateRenderer] (VM369 AppComponent.ngfactory.js:56)
    at Object.debugUpdateRenderer [as updateRenderer] (services.ts:408)
    at checkNoChangesView (view.ts:343)
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 8.0.6
Node: 10.15.3
OS: win32 x64
Angular: 8.0.3
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.800.6
@angular-devkit/build-angular      0.800.6
@angular-devkit/build-ng-packagr   0.800.6
@angular-devkit/build-optimizer    0.800.6
@angular-devkit/build-webpack      0.800.6
@angular-devkit/core               8.0.6
@angular-devkit/schematics         8.0.6
@angular/cdk                       8.0.1
@angular/cli                       8.0.6
@angular/flex-layout               8.0.0-beta.26
@angular/material                  8.0.1
@ngtools/json-schema               1.1.0
@ngtools/webpack                   8.0.6
@schematics/angular                8.0.6
@schematics/update                 0.800.6
ng-packagr                         5.3.0
rxjs                               6.4.0
typescript                         3.4.5
webpack                            4.30.0
</code></pre>

**Comment by santoshyadav198613** [comment] 2019-07-11 07:17
This error is common in dev mode to avoid this error add below code :

  ngAfterViewInit(){
    setTimeout(()=> {
      this.form.disable();
    },0);  
  }

and for why you get this error read this blog https://blog.angularindepth.com/everything-you-need-to-know-about-the-expressionchangedafterithasbeencheckederror-error-e3fd9ce7dbb4

**Comment by trotyl** [comment] 2019-07-11 07:42
Duplicate of https://github.com/angular/angular/issues/22556

**Closed** 2019-07-11 07:52 UTC
