### ISSUE TITLE
Radio-Buttons not working for Model-Driven-Forms

### ISSUE THREAD

**Issue by choeller** [angular/angular#8107] opened 2016-04-16 17:53 UTC
**Steps to reproduce and a minimal demo of the problem**
I'm trying to use Radio Buttons in the following way:
```ts
    this.taskForm = fb.group({
      ...
      priority: ["LOW"]
    });
```

```html
<input name="priority" ngControl="priority" type="radio" value="LOW" >
<input name="priority" ngControl="priority" type="radio" value="MEDIUM" >
<input name="priority" ngControl="priority" type="radio" value="HIGH" >
```

but when submitting the form the value of "priority" is always 
```ts
priority: RadioButtonState
  checked: false
  value: undefined
```

Here is a plnkr: http://plnkr.co/edit/EODqlxuoFRNXSsBH7cqz?p=preview

_What steps should we try in your demo to see the problem?_

Just click one Radio-Button and check console log.

**Current behavior**

Form is not using the value of the selected Radio-Button

**Expected/desired behavior**

Form should use the value of the selected Radio-Button ;)

**Comment by onlyann** [comment] 2016-04-30 14:58
Here's another Plunker : http://embed.plnkr.co/YYHUIx/  for beta 16. 

The behaviour is different but still incorrect when multiple radio groups are in the same control group.

On the topic of radio button value, what is the reason it has been decided to emit  ```{ checked: true, value: "foo"}``` /  ```{ checked: false}```  as opposed to ```"foo"``` / ```null```?
Returning the value would make it easier to work with in my opinion.

**Comment by shoespray** [comment] 2016-05-28 10:05
Same error!

**Comment by kara** [comment] 2016-06-28 23:06
Radio buttons have been revamped in the new forms module (RC.2 and onward). See new usage here: #9228. Closing, as the issue is no longer applicable. Please feel free to re-open if you see problems with the new module.

**Closed by kara** 2016-06-28 23:06 UTC
Labels: comp: core/forms

**Comment by bezigon** [comment] 2016-08-23 11:50
Needs to be reopened, because #9228 is for template-driven forms.

**Comment by kara** [comment] 2016-08-24 15:49
`#9228 is actually for both.  Just switch to using `formControlName` instead of `ngModel` in the current example.
