### ISSUE TITLE
Templates disallow unescaped braces even after changing interpolation delimiters

### ISSUE THREAD

**Issue by lazarljubenovic** [angular/angular#14019] opened 2017-01-19 20:19 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When interpolation delimiters are changed to `[[` and `]]`, having an unescaped `{` in template still throws an error (including `{{`).

**Expected behavior**

`{` should be allowed in templates if interpolation delimiters are changed. 

**Minimal reproduction of the problem with instructions**

http://plnkr.co/edit/5Kl9w2Mpct9z7ljEgogS?p=preview

**What is the motivation / use case for changing the behavior?**

One would normally change interpolation string because one needs `{{` for something else (eg. LaTeX syntax uses `{` heavily).

**Please tell us about your environment:**

* **Angular version:** 2.4.x

* **Browser:** all
 
* **Language:** TypeScript

**Comment by lazarljubenovic** [comment] 2017-01-19 20:47
Upon further investigation, I realize that [escaping `{` was introduced because of ICU messages](https://github.com/angular/angular/blob/master/CHANGELOG.md#breaking-changes-5). This was in 2.0.0-rc5 and interpolation was enabled in 2.0.0-rc3.

> "{" is used a a delimiter for ICU messages then it could not be used in text nodes. "{" should be escaped as "{{ '{' }}"
>
> Before:
>
>     <span>some { valid } text</span>
>
> After:
>
>     <span>some { invalid } text<span> 
>     <span>some {{ '{' }} valid } text</span>

The original reason for allowing making interpolation strings configurable was to be able to type `{{` without problems, but that's gone now too. It was mentioned that stuff might break with i18n in https://github.com/angular/angular/issues/8865, but looks like it was for other reasons (hardcoded braces).

**Comment by trotyl** [comment] 2017-01-20 04:37
A simple work-around is to not override interpolation delimiters while add a `ngNonBindable` attribute:

```typescript
@Component({
  selector: 'my-app',
  template: `
    <div>
      <h2 ngNonBindable>Hello {{name}}</h2>
    </div>
  `,
  // interpolation: ['[[', ']]'],
})
export class App { }
```

An updated plunker could be found in http://plnkr.co/edit/zAqMSXKJCrzxRRci90wT?p=preview

Does that meet your case?

**Comment by vicb** [comment] 2017-11-28 23:43
We should update the error message to display the active delimiters instead of having `{{` hardcoded

**Comment by trotyl** [comment] 2018-08-02 13:05
Duplicate of https://github.com/angular/angular/issues/11859

**Comment by Zefling** [comment] 2018-11-12 16:08
Other strange case with braces. I want to escape double braces for show an example, 

`&#123;&#123; -50 | math:'min':50 &#125;&#125;` show `-50` and not `{{ -50 | math:'min':50 }}`

Currently, my solution, add a zero-width joiner (`&#8205;`):

`&#123;&#8205;&#123; -50 | math:'min':50 &#125;&#125;`

**Comment by lazarljubenovic** [comment] 2018-11-12 17:00
I've long given up trying to fit a `{` in a template. I just bind the string from the class now. :smile:

**Comment by petebacondarwin** [comment] 2020-05-24 20:47
Yes @trotyl is right here - duplicate of #11859

**Closed** 2020-05-24 20:47 UTC
Labels: comp: i18n, freq1: low, severity1: confusing, type: bug/fix
