### ISSUE TITLE
Form statusChanges with async validators doesn't leave PENDING state

### ISSUE THREAD

**Issue by saramcicchi** [angular/angular#41519] opened 2021-04-08 20:43 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/forms

### Is this a regression?

 No this has been around since early 2017 but version 11 claims to have fixed this, and yet the bug is still present.

### Description

 FormGroup and FormControl do not emit first statusChanges when async validators are present, leaving the form in the PENDING state. Issues #14542 and #20424 reported this problem and were closed by #38354, which is available in Angular 11. However, running both of the stackblitz examples from these issues in Angular 11 demonstrates the original problem still exists.

## 🔬 Minimal Reproduction

 https://stackblitz.com/edit/angular-async-status-change

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 11.2.8
Node: 14.15.4
OS: darwin x64

Angular: 11.2.9
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.8
@angular-devkit/build-angular   0.1102.8
@angular-devkit/core            11.2.8
@angular-devkit/schematics      11.2.8
@angular/cli                    11.2.8
@schematics/angular             11.2.8
@schematics/update              0.1102.8
rxjs                            6.6.7
typescript                      4.1.5
</code></pre>

**Anything else relevant?**

**Comment by va-stefanek** [comment] 2021-04-11 17:20
@AndrewKushnir I think it's due to call of `_updateTreeValidity` with `emitEvent` parameter as `false` within `_updateDomValue`. Maybe `_updateTreeValidity` should evaluate `emitEvent` property for each control by look whether it, has an asyncValidator, as it's done in constructor of FormControl?

**Comment by AndrewKushnir** [comment] 2021-04-14 01:43
@saramcicchi thanks for reporting the issue.

@va-stefanek thanks for the investigation and the comment. It looks like you've found the root cause 👍

The fix would be very tricky and potentially require a breaking change, since the `emitEvent` config option affects both `statusChanges` and `valueChanges` observables. So the `statusChanges` would be expected in this case (since async validators will be triggered), but the `valueChanges` would not, but some apps code might rely on specific sequence and timing of events in `valueChanges`. This issue also reminds me of a similar problem described in https://github.com/angular/angular/issues/39588#issuecomment-723279307, which should also be considered during further investigation.

**Comment by DmitryEfimenko** [comment] 2021-12-09 03:52
did anybody come up with a workaround?

**Comment by UserGalileo** [comment] 2021-12-11 03:27
@DmitryEfimenko My particular issue is that I'm trying to reuse `statusChanges` of an inner form where I have async validators when using the Composite ControlValueAccessor pattern, so that I don't have to pass down the errors to the children (very cumbersome).

So, I'm stuck with this code which doesn't work in my CVA:

```ts
validate(_: FormControl) {
  // Doesn't work, initially the form stays PENDING.
  return this.form.statusChanges.pipe(
    startWith(this.form.status),
    first(status => status !== 'PENDING'),
    map(status => status === 'INVALID' ? { ... } : null)
  );
}
```

The only solution which came to mind was to do some sort of "polling" via `timeout` / `retry` or `switchMap`/`timer`, which works but the code is pretty ugly either way, eg:

```ts
validate(_: FormControl) {
  return defer(() => this.form.statusChanges.pipe(
    startWith(this.form.status),
    first(status => status !== 'PENDING'),
    map(status => status === 'INVALID' ? 'error' : null)
  )).pipe(
    timeout(500),
    retry(),
  )
}
```

But it could be abstracted:

```ts
// Always returns a status, if pending it checks every X milliseconds
function statusOf(
  control: AbstractControl,
  pollingRate: number = 500
): Observable<string> {
  return control.statusChanges.pipe(
    startWith(control.status),
    switchMap(status => {
      if (status !== 'PENDING') {
        return of(status);
      }
      return timer(0, pollingRate).pipe(
        map(() => control.status),
        takeWhile(status => status === 'PENDING', true),
      )
    }),
    distinctUntilChanged()
  )
}

...

validate(_: FormControl) {
  return statusOf(this.form).pipe(
    first(status => status !== 'PENDING'),
    map(status => status === 'INVALID' ? { ... } : null)
  )
}

```

Hope this is helpful! (test that code cause I wrote it in 10 minutes, but it seems to be working)

**Comment by fomenkogregory** [comment] 2022-01-15 11:26
I think I faced something like that, I created Stackblitz with the example https://stackoverflow.com/q/70708799/12006158

**Comment by spock123** [comment] 2022-03-18 14:20
This is a big issue for us, any thoughts of having this potentially resolved? thanks

**Comment by jmroon** [comment] 2022-07-04 18:49
As a hacky workaround you can manually trigger the validation after form initialization:

``` ngOnInit() {
  this.formGroup = new FormGroup(...etc);
  ...
  setTimeout( () => { 
    this.formGroup['myAsyncValidatedControl'].updateValueAndValidity();
  });
}

**Comment by Yogu** [comment] 2022-09-14 09:39
I had this probleml because `FomrControlDirective`s `ngOnChanges` sets `emitEvent` to `false` regardless of async validators.

https://github.com/angular/angular/blob/69ecbd5bcc89c9164a52fbf3198777624423f640/packages/forms/src/directives/reactive_directives/form_control_directive.ts#L126

Is this related to this issue here or should I create a new one?

**Comment by JimmyRowland** [comment] 2022-09-21 21:26
Had the exact same issue.
I am currently using `take(1)` as a workaround
https://stackoverflow.com/questions/46796642/angular-custom-async-validator-stays-in-pending-state

**Comment by ApplY3D** [comment] 2023-01-17 09:22
Still

**Comment by tomercohen1210** [comment] 2023-08-03 13:59
Solve it like this
```
  ngOnInit() {
    this.form.statusChanges.pipe(takeUntil(this.destroyed), pairwise())
        .subscribe(([prev, next]) => {
          if (prev === 'PENDING' && next !== 'PENDING') {
            this.form.updateValueAndValidity();
          }
        });
  }
```

**Comment by DibyodyutiMondal** [comment] 2023-08-04 07:03
> Solve it like this
> 
> ```js
>   ngOnInit() {
>     this.form.statusChanges.pipe(takeUntil(this.destroyed), pairwise())
>         .subscribe(([prev, next]) => {
>           if (prev === 'PENDING' && next !== 'PENDING') {
>             this.form.updateValueAndValidity();
>           }
>         });
>   }
> ```


Hang on a minute. I'm a bit confused. This issue was created exactly because the statusChanges observable was not emitting after async validation.
If this workaround works, doesn't it mean that the original issue itself is resolved?

**Comment by tomercohen1210** [comment] 2023-08-05 17:17
> > Solve it like this
> > ```js
> >   ngOnInit() {
> >     this.form.statusChanges.pipe(takeUntil(this.destroyed), pairwise())
> >         .subscribe(([prev, next]) => {
> >           if (prev === 'PENDING' && next !== 'PENDING') {
> >             this.form.updateValueAndValidity();
> >           }
> >         });
> >   }
> > ```
> 
> Hang on a minute. I'm a bit confused. This issue was created exactly because the statusChanges observable was not emitting after async validation. If this workaround works, doesn't it mean that the original issue itself is resolved?

My problem was that one of the form control had is own async validation and the `validate` function in the CVA did not run after the form status changed from "pending" to "valid", is it not your problem?

**Comment by DibyodyutiMondal** [comment] 2023-08-06 15:56
yes, that's exactly the problem. At the point in time I ran into the issue, that problem was being caused by the `form.statusChanges` not emitting at all after the async validators had run. So even your pairwise observable would never emit a situation where `prev === 'PENDING' && next !== 'PENDING'`.

I have been deliberately avoiding async validation like the plague since then. It's probably years at this point.

If I understand correctly, after recent changes, `form.statusChanges` does emit after async validation but doesn't update the validity of the form.

 Since I've stayed away from async validation for a while, hence the confusion.

**Comment by tomercohen1210** [comment] 2023-08-09 15:21
> yes, that's exactly the problem. At the point in time I ran into the issue, that problem was being caused by the `form.statusChanges` not emitting at all after the async validators had run. So even your pairwise observable would never emit a situation where `prev === 'PENDING' && next !== 'PENDING'`.
> 
> I have been deliberately avoiding async validation like the plague since then. It's probably years at this point.
> 
> If I understand correctly, after recent changes, `form.statusChanges` does emit after async validation but doesn't update the validity of the form. So only half of the problem is solved.
> 
> Since I've stayed away from async validation for a while, hence the confusion.

So my problem was that the `verify` function on the CVA component didn't run after async validation but the `form.statusChanges` did run on the change

**Comment by albanx** [comment] 2023-08-09 20:01
I am on angular 16 and the forms with Async Validator stay in pending state, never going to valid. This is still an issue

**Comment by DibyodyutiMondal** [comment] 2023-08-09 21:40
I'm a bit confused. Different people are reporting different behaviour, so created a repro. 

https://stackblitz.com/edit/stackblitz-starters-6uicqd

It looks ok to me. 
The only missing piece of this puzzle is, when 'updateOn' is set to 'submit', the form status becomes 'pending'.  This means that inside the `onSubmit` handler, form is actually not valid.
You can see this by checking the console.log in the repro. Submission is aborted immediately because form is not valid.

Workaround 1: we the status to become either 'VALID' or 'INVALID' again. and then call `onSubmit()` again.

Workaround 2: disable the submit button if the form is not valid. For example.
```disableSubmit$ = computed(() => status$() !== 'VALID')```

Would be nice if the FormGroupDirective took care of this tiny snag for us automatically.

**Comment by 9883684131** [comment] 2023-09-02 15:35
#  ngOnInit() {
    this.form.statusChanges.pipe(takeUntil(this.destroyed), pairwise())
        .subscribe(([prev, next]) => {
          if (prev === 'PENDING' && next !== 'PENDING') {
            this.form.updateValueAndValidity();
          }
        });
  }

**Comment by 9883684131** [comment] 2023-09-02 15:36
`Sonu` Bhukta    private barWordValidator(): AsyncValidatorFn {
    const webWorker = AddPropertyComponent.createBadWordWorker();
    return (control: AbstractControl) => {
      return timer(500).pipe(
        switchMap(() => {
          return new Observable((observer) => {
            webWorker.onmessage = (e) => {
              const foundWords = e.data;
              if (foundWords && foundWords.length) {
                observer.next({ InvalidWordsFound: true, foundWords });
              } else {
                observer.next(null);
              }
              observer.complete();
              console.log('barWordValidator::finished', control.status, this.descriptionForm.status, this.mainForm.status);
            };
            webWorker.postMessage({ text: control.value, badWords });
          });
        })
      );
    };
  }

**Comment by 9883684131** [comment] 2023-09-02 15:37
/
Duplicate of #

**Comment by 9883684131** [comment] 2023-09-02 15:39
@DmitryEfimenko #51145

**Comment by 9883684131** [comment] 2023-09-02 15:40
@spock123

**Comment by 9883684131** [comment] 2023-09-02 15:42
-

**Comment by 9883684131** [comment] 2023-09-02 15:42
Angular CLI: 11.2.8
Node: 14.15.4
OS: darwin x64

Angular: 11.2.9
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.8
@angular-devkit/build-angular   0.1102.8
@angular-devkit/core            11.2.8
@angular-devkit/schematics      11.2.8
@angular/cli                    11.2.8
@schematics/angular             11.2.8
@schematics/update              0.1102.8
rxjs                            6.6.7
typescript                      4.1.5

**Comment by 9883684131** [comment] 2023-09-02 15:43
webWorker.onmessage

**Comment by 9883684131** [comment] 2023-09-02 15:44
ngOnInit() {
    this.form.statusChanges.pipe(takeUntil(this.destroyed), pairwise())
        .subscribe(([prev, next]) => {
          if (prev === 'PENDING' && next !== 'PENDING') {
            this.form.updateValueAndValidity();
          }
        });
  }

**Comment by 9883684131** [comment] 2023-09-02 15:44
// Always returns a status, if pending it checks every X milliseconds
function statusOf(
  control: AbstractControl,
  pollingRate: number = 500
): Observable<FormControlStatus> {
  return control.statusChanges.pipe(
    startWith(control.status),
    switchMap(status => {
      if (status !== 'PENDING') {
        return of(status);
      }
      return timer(0, pollingRate).pipe(
        map(() => control.status),
        takeWhile(status => status === 'PENDING', true),
      )
    }),
    distinctUntilChanged()
  )
}

...

validate(_: FormControl) {
  return statusOf(this.form).pipe(
    first(status => status !== 'PENDING'),
    map(status => status === 'INVALID' ? { ... } : null)
  )
}
Son

**Comment by 9883684131** [comment] 2023-09-02 15:46
descriptionForm::statusChanges PENDING
barWordValidator::finished VALID VALID

**Comment by 9883684131** [comment] 2023-09-02 15:46
validate(_: FormControl) {
  // Doesn't work, initially the form stays PENDING.
  return this.form.statusChanges.pipe(
    startWith(this.form.status),
    first(status => status !== 'PENDING'),
    map(status => status === 'INVALID' ? { ... } : null)
  );
}

**Comment by Yberion** [comment] 2023-09-11 12:28
Hello, we're still facing this issue as well in our project.
As Angular 17 will come "soon", isn't it the good time trying to fix this issue ?

cc @JeanMeche @AndrewKushnir

**Comment by colinscz** [comment] 2023-09-12 16:21
Hi @AndrewKushnir 

In my case I am validating a FormGroup with an AsyncValidator against a backend endpoint. The form unfortunately stays in pending state, which makes the `form.valid` check unusable.  

There have been several people posting potential workarounds, as for my case none of these seems to be working. I guess the release of Angular 17 is too close for such a breaking change to come in. However there are several issues reported and from what I could find one that should have fixed this. 

Could you guys at least provide an official way to work around this issue until it lands in a major release? 

That would help very much. Thanks!

**Comment by tadamczak** [comment] 2023-12-11 01:02
As someone stated people are describing different issues with AsyncValidators. I will try to summarize the issues i found in the thread and share solutions for some of them.

**1. CVA validate not triggered after AsyncValidator finished.**

> > yes, that's exactly the problem. At the point in time I ran into the issue, that problem was being caused by the `form.statusChanges` not emitting at all after the async validators had run. So even your pairwise observable would never emit a situation where `prev === 'PENDING' && next !== 'PENDING'`.
> > I have been deliberately avoiding async validation like the plague since then. It's probably years at this point.
> > If I understand correctly, after recent changes, `form.statusChanges` does emit after async validation but doesn't update the validity of the form. So only half of the problem is solved.
> > Since I've stayed away from async validation for a while, hence the confusion.
> 
> So my problem was that the `verify` function on the CVA component didn't run after async validation but the `form.statusChanges` did run on the change

Issue is described here in section II with more details https://dev.to/musatov/angular-forms-validation-part-iii-async-validators-gotchas-5c0o
**Solution**: when you use AsyncValidator in CVA you have to implement AsyncValidator interface and provide validate method like (remember to add NG_ASYNC_VALIDATORS in providers aswell). This is especially important when you have more than one AsyncValidator.
``` 
validate(): Observable<ValidationErrors | null> {
    return this.yourControlName.statusChanges.pipe(
        first((status) => status !== 'PENDING'),
        map(() => {
            if (this.yourControlName.invalid) {
                return this.yourControlName.errors;
            }
            return null;
        }),
        takeUntill(this.unsubscribe$$) // this.unsubscribe is to make sure that it's completed. It's completion is called in NgOnDestroy
    );
}

```

This makes sure that validation is not finished untill your CVA is in 'PENDING' state.

**2. Status stuck in 'PENDING' state after AsyncValidator.**
Reason for that is most likely because the observable returned by AsyncValidator is not completed. 
**Solution**: To not copy answers here is link to the thread how to make sure observable is completed. https://github.com/angular/angular/issues/13200#issuecomment-371440273

**3. TOPIC ISSUE FormGroup and FormControl do not emit first statusChanges when async validators are present**
@saramcicchi you posted stackblitz with two issues. 

I managed to fix CopyOf14542Component. There was an issue with Promise not being 'completed'. I made it with Observable since i'm not the best with Promises. Additionally in AsyncValidator i piped control value changes and added startWith to make sure it takes initial value into consideration.

Second issue CopyOf20424Component i didn't manage to fix but all i can tell is that AsyncValidator has some issues with delay() operator itself. I believe it would work if it would be normal service call and observable would be completed but this is just my assumption.

Here is blitz with first issue fixed: https://stackblitz.com/edit/angular-async-status-change-1ngt5f?file=src%2Fapp%2Fcopy-of-14542%2Fcopy-of-14542.component.ts

**Summary**
My general tips for you would be to implement AsyncValidator interface when you are working with CVA. Then make sure that observables you return from AsyncValidators are completed. AVOID using delay/timer/debounce or any form of artificial timeOuts, they simply doesn't work and require wierd workarounds. 
Remember that AsyncValidators are always fired AFTER sync Validators finish plus only when Validators return VALID. If Validators return INVALID then AsyncValidators are not fired.

I hope it will help some of you :)

**Comment by anme98** [comment] 2023-12-12 18:53
> Hi @AndrewKushnir
> 
> In my case I am validating a FormGroup with an AsyncValidator against a backend endpoint. The form unfortunately stays in pending state, which makes the `form.valid` check unusable.
> 
> There have been several people posting potential workarounds, as for my case none of these seems to be working. I guess the release of Angular 17 is too close for such a breaking change to come in. However there are several issues reported and from what I could find one that should have fixed this but didn't, in an early major release of Angular (I think v11).
> 
> Could you guys at least provide an official way to work around this issue until it lands in a major release?
> 
> That would help very much. Thanks!

I can only agree with @colinscz. When I try to add an async cross-field validation to my FormGroup, the status always remains in PENDING. 

```
new FormGroup({
          preName: new FormControl(null, [Validators.required]),
          surName: new FormControl(null),
        }, {
          updateOn: 'blur',
          asyncValidators: userAlreadyExists(this.userService),
        },
      ),
```

And in the Chrome Dev Tools I see an infinite number of calls to the backend which are not prevented even by using `.first` in the AsyncValidatorFn. I already use Angular v17 and this problem persists.

**Comment by tadamczak** [comment] 2023-12-12 20:06
Can you provide stackblitz with the issue? In my project we are using asyncValidators without major issues. The only issues we have are missing initial status emission and delay/debounce.

**Comment by anme98** [comment] 2023-12-13 08:56
> Can you provide stackblitz with the issue? In my project we are using asyncValidators without major issues. The only issues we have are missing initial status emission and delay/debounce.

Okay sorry you are right @tadamczak. Seems like I'm having another problem in my project. Here in my [stackblitz](https://stackblitz.com/edit/angular-tskhhs?file=src%2Fvalidators%2Fuser-already-exists.ts) the async validation works like a charm.

**Comment by AliF50** [comment] 2024-02-14 19:51
Hello, 

I too am facing a situation similar to this issue where the `statusChanges` observable is stuck on `PENDING` but the `status` property gets updated accordingly with `VALID` or `INVALID` when an asynchronous validator is applied to a `FormArray`.

Here is an Angular 15 Stackblitz (https://stackblitz.com/edit/angular-15-starter-pack-df57bh?file=src%2Fapp%2Fapp.component.ts) where my expectation is that after adding 4 or more inputs, the `statusChanges` property should emit `VALID`. We can see that the `status` property is `valid` but the `statusChanges` last emission is `PENDING`.

<img width="921" alt="image" src="https://github.com/angular/angular/assets/22825890/6457d858-fbb7-4a1c-9aa6-9d14c7386ab7">

The situation is the same with Angular 14. Here is the Stackblitz: https://stackblitz.com/edit/angular-14-playground-ygez7e?file=src%2Fapp%2Fapp.component.ts.

It seems to only apply if the validator is applied to a FormArray and not a FormControl as shown by here: https://stackblitz.com/edit/angular-15-starter-pack-dfv3az?file=src%2Fapp%2Fapp.component.ts

where the statusChanges observable emits VALID | INVALID if the input value typed is < 4 in length.

I was able to fix it by doing something like:

`
interval(1000).pipe(
  takeUntil(this.destroyed),
).subscribe(() => this.form.updateValueAndValidity());
`
as outlined by some commenters in this thread.

**Comment by montella1507** [comment] 2024-02-14 20:45
I have been able to workaround all of the issues with our custom form control component like this:

validate method:

```
  validate() {
    return this.form.statusChanges.pipe(
     shareReplay(1),
     startWith(this.form.status),
     filter(status => status !== 'PENDING'),
     first(),
     map(status => {
       if (status === 'VALID') {
         return null;
       }
       return this.form.errors;
     }),
    );
  }
```


write value - check that updateValueAndValidity()  postponed with asapScheduler.. it is super important, or it will be pending when value is set to form

```
  writeValue(
   value: PhoneInputValue | null,
  ): void {
     .......
    asapScheduler.schedule(()=> {
      this.form.updateValueAndValidity();
    });
  }
```

**Comment by JeanMeche** [comment] 2024-03-30 05:34
Currently looking at this issue. Here a minimal repro : https://stackblitz.com/edit/angular-pending-async-validator?file=src%2Fmain.ts&template=node

The issue occurs when there is a `FormControlName` directive in the template. The parent formGroup fires `ctrl.updateValueAndValidity({emitEvent: false});` (which fires the async validator  a 2nd time) which for some reason is responsible for not emitting the new status. 

More to come...

**Comment by JeanMeche** [comment] 2024-03-30 06:51
I'm eyeing at a fix with #55134. We'll need to run some tests to see how breaking that change would be. 
If it's too breaking, it might be available only via the number observable that will land with #54579.

**Comment by alcaidio** [comment] 2024-05-01 22:31
I have the same issue i think, form.pending dont update. 
But with this it's works `pending = toSignal(this.form.statusChanges.pipe(map(s => s === 'PENDING')), { initialValue: false });`

**Comment by DibyodyutiMondal** [comment] 2024-05-02 00:02
> I have the same issue i think, form.pending dont update. 
> But with this it's works `pending = toSignal(this.form.statusChanges.pipe(map(s => s === 'PENDING')), { initialValue: false });`
> 

I use this same pattern, with a slight change.

It'd be better to not provide 'initialValue' as false. Depending on when you create the observable, the initial value of 'false' may not match the actual form status

Instead used the actual current value of the status for the initial value.

Therefore,
`{ initialValue: this.form.status === 'PENDING' }`

Basically, use the same predicate as in the map operator.

**Closed** 2024-05-15 15:56 UTC
Labels: breaking changes, area: forms, state: has PR, state: confirmed, forms: validators, P3

**Comment by JeanMeche** [comment] 2024-05-15 16:09
So, we landed a fix in v18 for this issue.
The fix was deemed too breaking for the `statusChanges`  Observable, so we only landed that change on the unified state change observable : `AbstractControl.events`.

**Comment by spock123** [comment] 2024-05-23 14:06
@reichemn  I guess you need to use the new **events** stream

**Comment by reichemn** [comment] 2024-05-23 14:23
@spock123 I know. But this fact is not reflected in the documentation.
