### ISSUE TITLE
Template parser error with SVG

### ISSUE THREAD

**Issue by dpineiden** [angular/angular#19385] opened 2017-09-25 20:24 UTC
Hello.

I'm developing an application that uses SVG D3. Because is in real time i'm implementing now the Webworker layer over the app.

I followed some tutorials and the work fine with a simple project but with my ngcharts fails to recognize the ngIf ngFor   bindings::

```compiler.es5.js:1694 Uncaught Error: Template parse errors:
Can't bind to 'ngIf' since it isn't a known property of ':svg:g'. ("

    <svg:g *ngFor="let tick of y_tick_list">
      <svg:g [ERROR ->]*ngIf="showTicks">
        <g tick-axis-y
          [label]="tick.label"
"): ng:///D3_TimeserieChartModule/D3TimeSerieComponent.html@62:13
Property binding ngIf not used by any directive on an embedded template. Make sure that the property name is spelled correctly and all directives are listed in the "@NgModule.declarations". ("

    <svg:g *ngFor="let tick of y_tick_list">
      [ERROR ->]<svg:g *ngIf="showTicks">
        <g tick-axis-y
          [label]="tick.label"
"): ng:///D3_TimeserieChartModule/D3TimeSerieComponent.html@62:6
Can't bind to 'ngForOf' since it isn't a known property of ':svg:g'. ("
    </svg:g>
```

The project is that: https://gitlab.com/pineiden/ngcharts/tree/master and without the webworkers configurations works fine

So, my question is about what i have to configure more with the webworkers to recognize the bindings....

Thanks!

**Comment by vicb** [comment] 2017-09-26 16:42
I don't think this has anything to do with Web Workers, changing the title.

**Comment by ocombe** [comment] 2017-09-26 16:55
*ngFor and *ngIf should definitively work on svg elements, as long as you import the CommonModule (which seems to be the case)
ie: they are used in https://github.com/swimlane/ngx-charts/

It might have to do with web workers after all

**Comment by dpineiden** [comment] 2017-09-28 16:57
Yep.

With CommonModule added to the modules works fine. Without webworkers it's ok.

With Webworkers, and CommonModule raise this error:

```
Unhandled Promise rejection: No provider for PlatformLocation! ; Zone: <root> ; Task: Promise.then ; Value: Error: No provider for PlatformLocation! injectionError@http://localhost:4200/webworker.bundle.js:34867:90
noProviderError@http://localhost:4200/webworker.bundle.js:34905:1
["./node_modules/@angular/core/@angular/core.es5.js"]/</ReflectiveInjector_.prototype._throwOrNull@http://localhost:4200/webworker.bundle.js:36347:19
```

So, i deactivate the CommonModule on the webworker layer, and the first error appeard again:

```
    <svg:g *ngFor="let tick of y_tick_list">
      <svg:g [ERROR ->]*ngIf="showTicks">
        <g tick-axis-y

```

So, maybe, i think there some conflict betwen Webworkers and CommonModule and SVG features....

I reorderer that on this project:

https://gitlab.com/pineiden/ng-webworkers-charts/tree/timeserie

Thanks!!

**Comment by dpineiden** [comment] 2017-09-28 21:05
And, help to understand the problem, i also tested a simple svg control with ngIf.... and works fine:

https://gitlab.com/pineiden/test_webworker/tree/master

So there something more there that cause the problem.... :(

**Comment by dpineiden** [comment] 2017-09-29 12:08
I read the doc and BrowserModule calls CommonModule, so could be something like a problem whit svg group:
<svg:g

**Comment by dpineiden** [comment] 2017-09-29 13:54
And now, i created another simple test, same as test:_webworker
On the ng-webworkers-charts:
https://gitlab.com/pineiden/ng-webworkers-charts/tree/test2
The same, but the code in another module inside other folder

 and the error is the same:

```
Unhandled Promise rejection: No provider for PlatformLocation! ; Zone: <root> ; Task: Promise.then ; Value: Error: No provider for PlatformLocation! injectionError@http://localhost:4200/webworker.bundle.js:33544:90
noProviderError@http://localhost:4200/webworker.bundle.js:33582:1
["./node_modules/@angular/core/@angular/core.es5.js"]/</ReflectiveInjector_.prototype._throwOrNull@http://localhost:4200
```

**Comment by dpineiden** [comment] 2017-11-07 13:07
there are some news about that issue?
thanks!

**Comment by pkozlowski-opensource** [comment] 2020-03-05 17:28
I just had a look at the linked https://gitlab.com/pineiden/ngcharts/tree/master and there is a _lot_ going on there so next to impossible to investigate. Also, at this point we are moving away from web workers.

I'm going to close this issue given the above but if anyone can provide a simple reproduce scenario for SVGs _without_ web-workers, I'm happy to investigate.

**Closed by pkozlowski-opensource** 2020-03-05 17:28 UTC
Labels: comp: core, freq1: low, severity3: broken, type: bug/fix
