### ISSUE TITLE
ng build --watch may fail rebuilding if dependency contains moment or lodash

### ISSUE THREAD

**Issue by Oleksandr-Zatuleyev** [angular/angular#37109] opened 2020-05-14 16:15 UTC
# 🐞 bug report

### Description

 
ng build --watch will fail rebuild with a type error if following conditions are met
1. Project A depends on Project B
2. Project B imports momentjs and exposes a model that contains a momentjs field
3. Projects A and B are built with ivy disabled

## 🔬 Minimal Reproduction

https://github.com/Oleksandr-Zatuleyev/build-watch-repro
1) npm install && npm run run-repro
2) The projects builds successfully
3) Save app.module.ts

## 🔥 Exception or Error
<pre><code>
ERROR in Error: Could not resolve moment/ts3.1-typings/moment from E:/Projects/build-watch-repro/dist/build-watch-repro-lib/build-watch-repro-lib.d.ts
Cannot determine the module for class AppComponent in E:/Projects/build-watch-repro/projects/build-watch-repro-app/src/app/app.component.ts! Add AppComponent to the NgModule to fix it.
</code></pre>

## 🌍  Your Environment

<pre><code>
@angular-devkit/architect          0.901.6
@angular-devkit/build-angular      0.901.6
@angular-devkit/build-ng-packagr   0.901.6
@angular-devkit/build-optimizer    0.901.6
@angular-devkit/build-webpack      0.901.6
@angular-devkit/core               9.1.6
@angular-devkit/schematics         9.1.6
@angular/cli                       9.1.6
@ngtools/webpack                   9.1.6
@schematics/angular                9.1.6
@schematics/update                 0.901.6
ng-packagr                         9.1.3
rxjs                               6.5.5
typescript                         3.8.3
webpack                            4.42.0
</code></pre>

**Comment by JoostK** [comment] 2020-05-14 19:45
I can only reproduce when the app is compiled using the previous compiler (ViewEngine), the issue does not occur for me when using Ivy.

**Comment by Oleksandr-Zatuleyev** [comment] 2020-05-15 07:29
It was actually written on top that this happens when Ivy is disabled.
Does it mean that ViewEngine is no longer supported??
There are some big projects using Angular and they cannot move that fast.

**Comment by JoostK** [comment] 2020-05-15 16:51
I know that you mentioned it was with Ivy disabled, it's just that I wanted to mention that this bug doesn't exist in Ivy while acknowledging the problem in View Engine.

Although View Engine is still available to use, bugs aren't actively being fixed. Instead, using Ivy _is_ the bug fix. Are there specific issues in Ivy that prevent you from using it?

**Comment by Oleksandr-Zatuleyev** [comment] 2020-05-17 13:28
I would like to avoid using Ivy for the time being for a few reasons:
1) ngcc takes a large amount of time to convert projects, and it may have impact depending on the CI setup
2) I have had cases where an "ivy-incompatible" library was used, ngcc failed to do something, but did not report it and then the application failed in runtime with obscure errors.
3) "ivy-compatible" build is not clearly defined. The documentation just says that the library should be built using ng cli.
4) Ivy format has not been finalized, so it may change in future and bring more errors.

**Comment by JoostK** [comment] 2020-05-19 14:46
Hi @Oleksandr-Zatuleyev,

bugs that are specific to View Engine are triaged and prioritized like any other bug. As Ivy is available which does not have this issue, fixing this bug in the old compiler is not of high priority. There is no statement on _not_ fixing ViewEngine-specific bugs, it's just that they aren't actively being fixed as Ivy is available as replacement.

If you do have specific issues with Ivy, please do open issues with your use-cases and concerns. We are aware of issues where ngcc is unable to process some libraries, typically because it does not follow Angular Package Format. That is a [well defined format](https://docs.google.com/document/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-NtkJglDaBVs/mobilebasic) that is indeed followed by the CLI through the usage of ng-packagr. Packages that do not follow APF, especially some older libraries, can indeed be hit-and-miss which can give obscure errors as you mention. Detecting such problems at build time is challenging, exactly because the library isn't according to a set of standards. If you have ideas on how this can be improved, please do let us know!

**Comment by Vangi** [comment] 2020-05-20 09:29
Any workarounds to avoid this error? It is really annoying because we have to rebuild the entire project and it takes additional time. And we can not switch to Ivy because we have to rewrite the most of the project.

**Comment by alxhub** [comment] 2020-05-26 18:55
This is a confirmed bug in Angular's View Engine compiler. However, as the issue is already fixed in the new Ivy compiler, as @JoostK says this is not a high priority.

> We can not switch to Ivy because we have to rewrite the most of the project.

This really should not be the case for projects. If you're encountering other problems that are making it difficult to migrate to Ivy, please open additional issues for them and we'll do our best to resolve them.

**Comment by alxhub** [comment] 2021-04-15 16:24
Closing this issue as obsolete - Ivy is soon to be the only option for application builds in v12.

**Closed by alxhub** 2021-04-15 16:24 UTC
Labels: P5, comp: compiler, engine: ve, fixed by Ivy, freq1: low, state: confirmed, triage #1, type: bug/fix, workaround1: obvious
