### ISSUE TITLE
ngFor duplicate HTML elements

### ISSUE THREAD

**Issue by digaus** [angular/angular#29052] opened 2019-03-01 10:32 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/commons

### Is this a regression?

 No

### Description

 
Using *ngFor to iterate over an array to display the values wokrs fine. However when I change the reference of the array (new data), the values get displayed twice for a fraction of a second (barely noticeable). This results in directives which I use on these elements, to not work correctly anymore.

![image](https://user-images.githubusercontent.com/15358538/53632560-9d25f100-3c15-11e9-8fcd-41437c8938fb.png)

## 🔬 Minimal Reproduction

 https://stackblitz.com/...

Just iterate with ngFor and set a breakpoint. Then change the reference of ngFor.

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by mlc-mlapis** [comment] 2019-03-01 10:36
@digaus ... remember to use `trackBy` for unique ids to eliminate repeated destroying and instantiating.

**Comment by digaus** [comment] 2019-03-01 11:16
> @digaus ... remember to use `trackBy` for unique ids to eliminate repeated destroying and instantiating.

This seems to work in most cases. But I have to always implement the trackBy function for each *ngFor...

Currently my workarround was to add
```
.ngForElement:not(.ng-star-inserted) {
    display: none;
}
```
For now I will replace that with trackBy where I am able to do that,

**Comment by mlc-mlapis** [comment] 2019-03-01 11:23
@digaus ... you should do it everywhere ... it's the key point. The logic is to have always a static unique id for each iterable item and not relative index id.

**Comment by digaus** [comment] 2019-03-01 13:15
I cannot if the ngFor is in an external library. But thats another issue. 
Nevertheless, is it intended that duplicate elements are present in the DOM at the same time when not using trackBy?

**Comment by mlc-mlapis** [comment] 2019-03-01 14:15
@digaus ... so it's a lib which you should not use or contact the owner to correct the problem. Don't keep as it is now.

**Comment by mlc-mlapis** [comment] 2019-03-01 14:17
@digaus ... I am not sure how the algorithm works in details ... but can look at https://github.com/angular/angular/blob/master/packages/core/src/change_detection/differs/iterable_differs.ts

**Comment by petebacondarwin** [comment] 2020-05-28 13:35
@digaus - could you please provide a bit more detail for reproducing this error? Is the data being iterated over a collection of objects? Or pass-by-value items like string or numbers? How are you changing the collection to trigger the re-rendering?

**Comment by petebacondarwin** [comment] 2020-05-28 13:55
Also could you confirm whether you are using animations and whether this is under the ViewEngine or Ivy rendering engine?

I can't reproduce the issue.

**Comment by digaus** [comment] 2020-05-31 11:04
> @digaus - could you please provide a bit more detail for reproducing this error? Is the data being iterated over a collection of objects? Or pass-by-value items like string or numbers? How are you changing the collection to trigger the re-rendering?

Will try to reproduce. It was with ViewEngine.

I triggered the rerender bei setting `array =[...array]` for example

**Comment by petebacondarwin** [comment] 2020-10-26 21:09
From the comments, it looks like this was not working in ViewEngine which is deprecated. Closing due to a lack of reproduction in Ivy. If you can reproduce this bug in Ivy, please create a new issue with steps (or a stackblitz etc) on how to reproduce.

**Closed by petebacondarwin** 2020-10-26 21:09 UTC
Labels: P3, comp: common, freq3: high, needs clarification, needs reproduction, triage #1, type: bug/fix
