### ISSUE TITLE
Routing works wrong with included routes

### ISSUE THREAD

**Issue by launcelot66** [angular/angular#40625] opened 2021-01-29 06:52 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/router

### Is this a regression?

 Yes, the previous version in which this bug was not present was: v9 (big application worked in prod)

### Description

 go to http://localhost:4200/login and it works (but must render NotFoundComponent)
if add "auth/" at begin of "login" and/or "restore" path - will works correct, but this isn't normal

## 🔬 Minimal Reproduction

 
package.json:
<pre><code>
{
  "dependencies": {
    "@angular/animations": "~11.1.1",
    "@angular/cdk": "^11.1.1",
    "@angular/common": "~11.1.1",
    "@angular/compiler": "~11.1.1",
    "@angular/core": "~11.1.1",
    "@angular/forms": "~11.1.1",
    "@angular/material": "^11.1.1",
    "@angular/platform-browser": "~11.1.1",
    "@angular/platform-browser-dynamic": "~11.1.1",
    "@angular/router": "~11.1.1",
    "jwt-decode": "^3.1.2",
    "rxjs": "~6.6.0",
    "tslib": "^2.0.0",
    "zone.js": "~0.10.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1101.1",
    "@angular/cli": "~11.1.1",
    "@angular/compiler-cli": "~11.1.1",
    "@types/jasmine": "~3.6.0",
    "@types/node": "^14.14.20",
    "codelyzer": "^6.0.0",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~5.2.3",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.0.3",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "protractor": "~7.0.0",
    "ts-node": "~9.1.1",
    "tslint": "~6.1.0",
    "typescript": "~4.0.2"
  }
}
</code></pre>

main routes (app.routing.ts):
<pre><code>
import {RouterModule, Routes} from '@angular/router';
import {NotFoundComponent} from './components/not-found/not-found.component';

const routes: Routes = [{
  path: '',
  redirectTo: 'auth',
  pathMatch: 'full'
}, {
  path: 'auth',
  loadChildren: () => import('./modules/auth/auth.module').then(m => m.AuthModule)
}, {
  path: '**',
  component: NotFoundComponent
}];

export const ROUTING = RouterModule.forRoot(routes);
</code></pre>

auth.module.ts:
<pre><code>
import {NgModule} from '@angular/core';
import {RouterModule, Routes} from '@angular/router';
import {AuthLayoutComponent} from './layout/auth-layout.component';
import {AuthLayoutModule} from './layout/auth-layout.module';

const routes: Routes = [{
  path: '',
  redirectTo: '/auth/login',
  pathMatch: 'full'
}, {
  path: 'login',
  component: AuthLayoutComponent,
  loadChildren: () => import('./login/login.module').then(m => m.LoginModule)
}, {
  path: 'restore',
  component: AuthLayoutComponent,
  loadChildren: () => import('./restore/restore.module').then(m => m.RestoreModule)
}];

const ROUTING = RouterModule.forChild(routes);

@NgModule({
  imports: [
    ROUTING,
    AuthLayoutModule
  ]
})
export class AuthModule {}
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 11.1.1
Node: 14.3.0
OS: linux x64

Angular: 11.1.1
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, material, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1101.1
@angular-devkit/build-angular   0.1101.1
@angular-devkit/core            11.1.1
@angular-devkit/schematics      11.1.1
@schematics/angular             11.1.1
@schematics/update              0.1101.1
rxjs                            6.6.3
typescript                      4.0.5
</code></pre>

**Comment by atscott** [comment] 2021-01-29 21:01
@launcelot66 Could you please provide a minimal reproduction of the issue in either stackblitz or a github repository with steps to reproduce?

**Comment by atscott** [comment] 2021-02-04 21:03
Closing due to lack of reproduction. If you're still experiencing an issue, please submit a new report and include a minimal reproduction in either stackblitz or a github repo.

**Closed by atscott** 2021-02-04 21:03 UTC
Labels: comp: router, needs reproduction
