### ISSUE TITLE
FormControl valueChanges is triggered on blur

### ISSUE THREAD

**Issue by Daddelbob** [angular/angular#26054] opened 2018-09-21 10:32 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Subscribing a `FormControl.valueChanges` is not only triggerting as expected on changing the value of the control, but also when it loses the focus. 

## Expected behavior

The valueChanges should only trigger when the value is changed. It should not trigger onBlur.

## Minimal reproduction of the problem with instructions

Use a FormControl and subscribe on its valueChanges. 

## What is the motivation / use case for changing the behavior?

A search request to the server shall be triggered if the Input-FormControls value have changed.
With the current valueChanges behaviour, the serverrequest is triggered a second time after the user leaves the inputcontrols focus.

## Environment

<pre><code>
Angular version: 6.1.6

Browser:
- [x] Chrome (desktop) version 69
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 9.11.1  
- Platform: Windows  

Others:

</code></pre>

**Comment by pkozlowski-opensource** [comment] 2018-09-21 11:37
Related: https://github.com/angular/angular/issues/25749#issuecomment-417492746

**Comment by Daddelbob** [comment] 2018-09-24 10:54
I think I should add my current solution:
Adding the "distinctUntilChanged" rxjs-operator simply solves this unexpected behaviour.
I'd still like to know if this behavior is desired - since it isn't documented in the Angular docs.

**Comment by kara** [comment] 2018-10-09 22:45
Since we don't have enough info to reproduce, I'm closing this issue. Please open a new issue with a reproduction if you'd like to look into this.

**Closed by kara** 2018-10-09 22:45 UTC
Labels: comp: forms, state: Need repro

**Comment by Daddelbob** [comment] 2018-10-10 07:11
This issue was closed justifiably. I tried to reproduce it as a simple Stackblitz, but turns out it just works fine.
This isn't a bug but some dependency we created in our specific project.
Thanks for your time, kara.
