### ISSUE TITLE
APP_INITIALIZER with HttpClient provoke memory leak in SSR projects

### ISSUE THREAD

**Issue by dancornilov** [angular/angular#55396] opened 2024-04-18 14:22 UTC
### Which @angular/* package(s) are the source of the bug?

common, core

### Is this a regression?

Yes

### Description

In my Angular 17 SSR project, I encountered a problem with memory consumption. Typically, this issue can arise due to **unsubscription** or **intervals**, but not this time.

After several weeks of debugging and refactoring everything that came to mind and could potentially cause this problem, I sought help from other friends, colleagues, and developers. Ultimately, after a full day of debugging, the bug was identified: the memory leak was caused by the `HttpClient` used in `APP_INITIALIZER`.

Right now, I've found a workaround to avoid this issue by creating a WrapperComponent which wraps all my routes, and I use a resolver to prevent HTTP requests in APP_INITIALIZER.

### Please provide a link to a minimal reproduction of the bug

https://github.com/dancornilov/initializer-memory-leak

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.3.4
Node: 20.9.0
Package Manager: npm 10.1.0
OS: darwin arm64

Angular: 17.3.4
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, google-maps, material, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker, ssr

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1703.4
@angular-devkit/build-angular   17.3.4
@angular-devkit/core            17.3.4
@angular-devkit/schematics      17.3.4
@schematics/angular             17.3.4
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.4
```

### Anything else?

Please take a look in provided repository for minimal reproduction of the bug, in README is describe the full flow how to reproduce this issue.

**Comment by JeanMeche** [comment] 2024-04-18 15:19
By any chance could you run the same tests without the fetch implementation ? (remove `withFetch()` to rely on the default XHR implementation)

**Comment by dancornilov** [comment] 2024-04-19 09:50
Hey @JeanMeche, I removed `withFetch()` but anyway problem still persist.

<img width="858" alt="Screenshot 2024-04-19 at 12 46 13" src="https://github.com/angular/angular/assets/24212761/7a3203bd-0f92-4085-b358-69a57421d5e6">

- **green**: Initial snapshot when app is only served
- **red**: Snapshot when artillery finished his work
- **orange**: Snapshot when I triggered manually GC

**Comment by JeanMeche** [comment] 2024-04-19 21:02
I gave it a look an can provide 2 minimal repro : 

* Webpack : https://github.com/JeanMeche/ssr/tree/ssr-leak-webpack-builder
* Application builder : https://github.com/JeanMeche/ssr/tree/transfer-cache-application-builder-no-leak

This is linked to the `TransferCache` not being trashed by the GC. 
What make this issue interesting is that the application builder repro does not reproduce the leak.

**Comment by dancornilov** [comment] 2024-04-19 21:34
I am not sure that I fully understand you, just to confirm:
In first repository you can reproduce it but in second this issue is not reproducible, am I right?

I retried my tests with `optimization: true` , yes this one helps to avoid this memory leak.

**Comment by JeanMeche** [comment] 2024-04-19 21:36
I was mislead initially because the webpack builder didn't have the optimization enabled.

**Comment by dancornilov** [comment] 2024-04-19 21:41
I understand that this issue is most dev-only mode, but this is mistake or trade-of?

**Comment by JeanMeche** [comment] 2024-04-20 16:50
Its likely due to some debug/devtools related code. Those are only shipped on devbuilds. This why the Angular devtools only works on devbuilds for example.

**Comment by alan-agius4** [comment] 2024-04-21 17:33
@alxhub, suspects that the Injector Profiler is causing the leak.

https://github.com/angular/angular/blob/b1dffa4abe8321a47d79b2ea29ee32a81acfe031/packages/core/src/render3/debug/framework_injector_profiler.ts#L56

**Comment by alan-agius4** [comment] 2024-05-02 12:18
Closed via https://github.com/angular/angular/pull/55530

**Closed by alan-agius4** 2024-05-02 12:18 UTC
Labels: memory leak, area: core, state: has PR, P4
