### ISSUE TITLE
Page Not Found for Router API

### ISSUE THREAD

**Issue by AdityaK60** [angular/angular#53415] opened 2023-12-07 05:48 UTC
### Describe the problem that you experienced

The "Router API" link present on the Page https://angular.dev/guide/routing/router-tutorial leads to a Page Not Found Error

### Enter the URL of the topic with the problem

https://angular.dev/api/router

**Comment by JoostK** [comment] 2023-12-07 07:59
I thought this was a duplicate of #53382, but it's not actually. Thanks for reporting!

**Closed** 2024-01-26 00:30 UTC
Labels: state: has PR, P3, area: adev
