### ISSUE TITLE
Always open new tab, when updating in Plunker

### ISSUE THREAD

**Issue by DineshChopra** [angular/angular#11630] opened 2016-09-15 13:17 UTC
Hi,

When I am going to update anything in Plunker then new tab will opens and updates shown in new tab.

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 

**Expected behavior**

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
 
* **Node (for AoT issues):** `node --version` =

**Comment by pkozlowski-opensource** [comment] 2016-09-15 13:20
Huh? Sounds like sth plunker-related... or not clear what you are asking... Going to close this one as it doesn't sound like the angular-specific issue...

**Closed by pkozlowski-opensource** 2016-09-15 13:20 UTC

**Comment by DzmitryShylovich** [comment] 2016-09-15 13:21
You can "fix" it by disabling auto refresh http://prntscr.com/ciazer

**Comment by DineshChopra** [comment] 2016-09-15 13:28
Open angular docs QuickStart (https://angular.io/docs/ts/latest/quickstart.html)
Click on live example, When we are going to update anything here it always opens a new tab. I think there is some problem, but not sure what is the exact problem. So may be needs someone help to fix it.

**Comment by zoechi** [comment] 2016-09-15 13:32
I also have this and had it already occasionally a few months ago. No idea what causes it though.

**Comment by neeklamy** [comment] 2016-12-29 10:55
I just came across the same problem with an Angular tutorial hosted on Plunker, this was caused by angular/zone.js#456.

I can confirm switching to a more recent Zone.js works:

>The bug has since been fixed in more recent zone.js releases but the Angular team still needs to reflect those new versions in their docs and plunk seeds. 
>
>To fix this locally, just change the version of zone.js referenced in your plunk to 0.6.24 or 0.6.25.

– [Geoff Goodman on the Plunker Google Group](https://groups.google.com/d/msg/plunker/cPEILSWfjS4/X9y_hHxMBwAJ)
