### ISSUE TITLE
Unable to get access to child elements from Webcomponent

### ISSUE THREAD

**Issue by chenthillrulz** [angular/angular#16645] opened 2017-05-09 05:33 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I have an angular app where am using a webcomponent based on custom elements V0 specification.
```
<custom-page>
    <p>This is child element inside my custom page</p>
    <step> 
      <custom-input-element></custom-input-element>
    </step>
    <step></step>
</custom-page>
```
Unable to get access to child elements of custom element "custom-page" in attachedCallBack (lifecylce callback of webcomponents custom element) in the webcomponent.

**Expected behavior**

Angular needs to provide a way for the webcomponent to access its child elements.

**Minimal reproduction of the problem with instructions**

https://plnkr.co/edit/SGndyIXp8alqaSP4Av5F?p=preview

Please look into the console message after -  "Accessing child Nodes".  
On the first preview, it might look like the node references are resolved, please stop and re-run the plunker preview to reproduce the issue

* **Angular version:** 2.0.X

**Comment by trotyl** [comment] 2017-05-09 08:58
Duplicate of https://github.com/angular/angular/issues/13699 or https://github.com/angular/angular/issues/15202?

**Comment by jasonaden** [comment] 2017-05-10 18:29
@tbosch Please close if this is a duplicate.

**Comment by tbosch** [comment] 2017-05-10 21:29
Closing as duplicate.

**Closed by tbosch** 2017-05-10 21:29 UTC
Labels: comp: core & compiler
