### ISSUE TITLE
Better error message when Typescript version isn't correct

### ISSUE THREAD

**Issue by bryantlikes** [angular/angular#39894] opened 2020-11-30 19:35 UTC
# 🚀 Feature request

### Command (mark with an `x`)

- [ ] new
- [X] build
- [X] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description
If the current Typescript version that is installed meets the required version but uses the caret and there is a version that exists that is beyond the required version you get an error:

The Angular Compiler requires TypeScript >=4.0.0 and <4.1.0 but 4.1.2 was found instead.

The current version that was installed is 4.0.5, but in package.json it is ^4.0.5 and 4.1.2 is available. Switching the package.json to ~4.0.5 fixes the issue. 

### Describe the solution you'd like
Add a more descriptive error. In this situation it would be nice if the message was more clear on what needs to change. Something like:

The Angular Compiler requires TypeScript >=4.0.0 and <4.1.0 but the current version in package.json doesn't does not apply this restriction. 

If the actual version does not meet the required version, then the current message is correct. 

### Describe alternatives you've considered
Fixing the version works, but the message is misleading.

**Comment by clydin** [comment] 2020-11-30 22:21
The check that generates that error message uses the installed version of TypeScript ([code](https://github.com/angular/angular/blob/288a0a668aa0831fba10b988db89761bb2c0f618/packages/compiler-cli/src/typescript_support.ts#L34)/[code](https://github.com/angular/angular/blob/288a0a668aa0831fba10b988db89761bb2c0f618/packages/compiler-cli/src/typescript_support.ts#L63)).  The value found in the project's `package.json` is not directly involved in the check.  Using the `package.json` value can lead to false positives or negatives as TypeScript could be installed without being present in the `package.json` (e.g., a monorepo) or could be manually installed to a differing version.  The reason that adjusting the `package.json` version to `~4.0.5` fixed the problem is that it forced the package manager to install a compatible version in the 4.0.x range.

**Comment by muuvmuuv** [comment] 2020-12-03 07:56
Can't this be solved by saying angular has TypeScript X as a [peerDependency](https://nodejs.org/en/blog/npm/peer-dependencies/)?

**Comment by clydin** [comment] 2020-12-03 12:12
TypeScript is currently also a peer dependency of the `@angular/compiler-cli` package ([code](https://github.com/angular/angular/blob/3680ad147b6d16d313e09cfba6e0953cb03cfb27/packages/compiler-cli/package.json#L32)).  Package managers will typically generate a warning at install time for a misaligned peer dependency.  However, these warnings can be easily missed.  A runtime check also provides a strong guarantee that a supported version is in use and changes a crash with a hard to diagnose stack trace to a more explicit error.

**Comment by alxhub** [comment] 2021-07-08 22:21
I'm going to close this, as I actually think the current error message is unambiguous and actionable. As @clydin points out, the peer dependency warning that one would get from the package manager if an incorrect version of TS is selected in the application's `package.json` is the first line of defense. If that warning is ignored, our runtime check will catch when the version of TS the user actually provided (via whatever mechanism) isn't supported by our compiler. It's not the compiler's job to know where the actual version of TS in use came from, only that it's outside of our supported range. That's what we report.

**Closed by alxhub** 2021-07-08 22:21 UTC
Labels: comp: compiler, feature, hotlist: error messages, insufficient votes, votes required
