### ISSUE TITLE
HttpClientModule: XSSI_PREFIX not working when responseType is 'json'

### ISSUE THREAD

**Issue by mattrenaud** [angular/angular#18555] opened 2017-08-06 16:05 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When the `XSSI_PREFIX` is present in the http response and `responseType` is 'json', the response fails to parse the response and you get `null` data. When `responseType` is 'text', the XSSI_PREFIX is properly removed.

## Expected behavior

I would expect the `XSSI_PREFIX` to work in the 'json' responseType case as per the documentation:
https://angular.io/guide/security

> Angular's HttpClient library recognizes this convention and automatically strips the string ")]}',\n" from all responses before further parsing.

I'll also note that this works fine in the old "@angular/http/Http" client.

## Minimal reproduction of the problem with instructions

Here is my example (I used _glitch_ because I needed a server request :): 
https://glitch.com/edit/#!/fixed-college?path=public/app/app.component.ts:18:32
( click "Show Live" in the top left or go to https://fixed-college.glitch.me/ to see it running )

You can toggle between types (json and text) quickly by adjusting the commenting.
## What is the motivation / use case for changing the behavior?

HttpClient should work as documented or the documentation should be changed.

## Environment

<pre><code>
Angular version: 4.3.3

Browser:
- [X] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [X] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.2.1 
- Platform:  Windows 

Others:

</code></pre>

**Comment by trotyl** [comment] 2017-08-06 16:57
Duplicate of https://github.com/angular/angular/issues/18453?

**Comment by mattrenaud** [comment] 2017-08-06 18:08
Yes looks like it. sorry for the dup. i thought i searched well enough :(

**Comment by trotyl** [comment] 2017-08-06 18:13
No worries, the PR is already in progress at https://github.com/angular/angular/pull/18466

**Closed** 2017-08-07 21:51 UTC
Labels: comp: http
