### ISSUE TITLE
Bundling angular 2 app with Webpack.UglifyJsPlugin results in errors

### ISSUE THREAD

**Issue by frederik** [angular/angular#6551] opened 2016-01-18 19:49 UTC
I've been trying to get a simple Angular 2 (beta 1) app running with a minified build (using webpack) - with no success. The cause seems to be the mangle option in the UglifyJSPlugin (with mangle: false it works fine but is 260k heavier).

To reproduce the issue, I have created a minimal version (clone, npm install and then webpack -p to reproduce) [here](https://github.com/frederik/angular2-webpack-uglify) and also included the logs and a sample of the uglyfied source.

I couldn't really see which variables are effected here since errors came up in multiple apps. When I remove ngModel from the view everything goes back to normal. The issues seem to be centered around change detection.

```
EXCEPTION: No value accessor for '' in [data.search in e@0:19]
EXCEPTION: No value accessor for '' in [data.search in e@0:19]
ORIGINAL EXCEPTION: No value accessor for ''
ORIGINAL STACKTRACE:
Error: No value accessor for ''
    at new t (http://127.0.0.1:56187/bundle.js:1:12197)
    at s (http://127.0.0.1:56187/bundle.js:1:26713)
    at Object.i [as setUpControl] (http://127.0.0.1:56187/bundle.js:1:25991)
    at t.ngOnChanges (http://127.0.0.1:56187/bundle.js:5:29716)
    at e.ChangeDetector_e_0.detectChangesInRecordsInternal (viewFactory_e:53:59)
    at e.detectChangesInRecords (http://127.0.0.1:56187/bundle.js:7:10658)
    at e.runDetectChanges (http://127.0.0.1:56187/bundle.js:7:10219)
    at e._detectChangesInViewChildren (http://127.0.0.1:56187/bundle.js:7:12475)
    at e.runDetectChanges (http://127.0.0.1:56187/bundle.js:7:10329)
    at e.detectChanges (http://127.0.0.1:56187/bundle.js:7:9902)
ERROR CONTEXT:
e
Live reload enabled.
```

**Comment by brandonroberts** [comment] 2016-01-18 20:01
There are issues with minified builds in beta.1. See https://github.com/angular/angular/issues/6380

**Comment by pkozlowski-opensource** [comment] 2016-01-18 20:02
Closing as duplicate of https://github.com/angular/angular/issues/6380

**Comment by frederik** [comment] 2016-01-18 20:03
Thanks, guys. Didn't see that one.

**Closed by pkozlowski-opensource** 2016-01-18 20:02 UTC
