### ISSUE TITLE
'select' attribute of <ng-content > is completely ignored in Hybrid Mode (UpgradeAdapter)

### ISSUE THREAD

**Issue by prasikumbhare** [angular/angular#9643] opened 2016-06-27 17:04 UTC
**I'm submitting a ...**  (check one with "x")
```
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
In Hybrid mode (when bootstrapped using upgradeAdatper.bootstrap()), the **`<ng-content select ='' >`** attribute on the downgraded ng2 component is not honored. it seems that select='' expression is ignored completely and all the light DOM child elements are included.

**Expected/desired behavior**
In Hybrid mode, the `<ng-content select=''>` attribute should be honored and should include only those DOM element matching the 'select' criteria.

**Reproduction of the problem**
Here is the plunker [https://plnkr.co/edit/L7Flah?p=preview](https://plnkr.co/edit/L7Flah?p=preview)

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

It breaks the desired ng2 component behavior in hybrid mode.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.1
 
* **Browser:** [Chrome XX ] 
 Tested in Chrome Version 51.0.2704.103 m

* **Language:** [all | TypeScript X.X | ES6/7 | ES5 | Dart] 
https://code.angularjs.org/tools/typescript.js

**Comment by youdz** [comment] 2016-06-28 15:52
Duplicate of #7727.
#9538 fixes this.

**Closed** 2016-06-28 18:40 UTC

**Comment by prasikumbhare** [comment] 2016-07-11 15:24
@vicb 

I can still reproduce this issue in RC4. Updated plunker to point to RC4 bundles.

**Comment by zoechi** [comment] 2016-07-18 10:59
The linked PR #9538 isn't merged yet and therefore not yet shipped.
