### ISSUE TITLE
Not able to see the unit testing page in angular.io website

### ISSUE THREAD

**Issue by abhishekstl** [angular/angular#21887] opened 2018-01-30 08:46 UTC
The url https://angular.io/guide/testing is not accessible. Is it down for maintainance?

**Comment by trotyl** [comment] 2018-01-30 09:21
It's under rewrite at #20697

**Comment by gkalpak** [comment] 2018-01-30 12:55
The old page should still be visible (although @trotyl is right that a re-write is about to be merged).
Sounds like this issue is a duplicate of #21889.

**Closed by gkalpak** 2018-01-30 12:55 UTC

**Comment by trotyl** [comment] 2018-01-30 13:16
Ah, just found I misunderstood the question...
