### ISSUE TITLE
TestComponentBuilder/inject does not work, when component has templateUrl

### ISSUE THREAD

**Issue by goodfield** [angular/angular#5662] opened 2015-12-07 13:11 UTC
Following test fails as expected (http://plnkr.co/edit/61ByTt?p=preview):
```
@Component({
  selector: 'header',
  template: '<h1>Hello Welt!</h1>'
})
export class TestComponent2 {
 }

describe('TestComponent', () => {
  it('should fail', inject([TestComponentBuilder], (tcb) => {
    return tcb.createAsync(TestComponent2).then((fixture) => {
      fixture.detectChanges();
      expect(1).toEqual(2);
    });
  }));
)};
```
Moving the template to an external resource, the test passes without failing (the async part doesn't get executed) (http://plnkr.co/edit/ZOeFTO?p=preview):

```
@Component({
  selector: 'header',
  templateUrl: 'src/test.html'
})
export class TestComponent {
  
}

describe('TestComponent', () => {
  it('should fail', inject([TestComponentBuilder], (tcb) => {
    return tcb.createAsync(TestComponent).then((fixture) => {
      fixture.detectChanges();
      expect(1).toEqual(2);
    });
  }));
)};
```

**Comment by goodfield** [comment] 2015-12-10 11:53
Should/Could be related to:
*https://github.com/angular/angular/issues/5601
*https://github.com/angular/angular/issues/5731
*https://github.com/angular/angular/issues/5698

**Comment by goodfield** [comment] 2015-12-11 08:56
Can also be reproduced, by migrating https://github.com/juliemr/ng2-test-seed to the newest angular alpha ... thats what i did with https://github.com/goodfield/ng2-test-seed

**Comment by GaloisGirl** [comment] 2016-01-07 11:02
Also suffering from this.
When using the overrideTemplate workaround, tests pass or fail nondeterministically - an improvement over not being ran at all, but still incorrect.
I'm using 2.0.0-beta.0.

**Comment by frederikschubert** [comment] 2016-01-17 15:22
This problem still exists with 2.0.0-beta.1.

**Comment by JohanBeekers** [comment] 2016-02-02 12:03
I'm also having this problem currently with 2.0.0-beta.1. It seems to happen when using styleUrls as well.

**Comment by antonybudianto** [comment] 2016-02-02 12:13
try with beta.2 and use injectAsync (inject didn't work and test will always pass), mine works well, here is my [spec](https://github.com/antonybudianto/angular2-starter/blob/master/app/simplebind/simplebind.component.spec.ts) file for reference

**Comment by JohnVanNguyen** [comment] 2016-02-08 23:27
beta.3 and templateUrl doesn't work for me

**Comment by alexeagle** [comment] 2016-02-12 03:26
Julie, this looks like the issue you fixed in https://github.com/angular/angular/commit/c72ed991ada4bef1d822132a697e57e088a0b71f but reports here indicate it's still present as of beta.3 - what do you think?

**Comment by woppa684** [comment] 2016-03-03 10:43
From what I see now, this is still present in beta.8, should I use injectAsync for now?

**Comment by johnvnguyen** [comment] 2016-03-03 16:24
@woppa684 I'm currently on beta.6 and templateUrl works for me. I should update my comment. I'm a novice, so excuse me for my bundlers:

I'm using injectAsync because that's the only way that I see that would create a working component with a view to test. The only thing I had to change was to use the path from the root in the templateUrl. For example, I used to have it as:
`@Component({
    moduleId: module.id,
    selector: 'my-selector',
    templateUrl: './test.html',
})`
but that didn't work unless I used the full path from the root:
`@Component({
    moduleId: module.id,
    selector: 'my-selector',
    templateUrl: 'app/example/test.html',
})`

From what I know, it may be an issue with my karma configuration.

**Comment by choeller** [comment] 2016-03-05 18:00
For me the problem also still persists in Beta.8. Furthermore when using `injectAsync` instead of `inject` I get a timeout from Jasmine. Also the constructor of my Component does not get called:

` Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.`

```
describe('Form Component', () => {
  it('should show validation errors for invalid fields',
    injectAsync([TestComponentBuilder],
      fakeAsync((tcb:TestComponentBuilder) => {
        tick();
        return tcb
          .createAsync(FormComponent)
          .then((fixture: any) => {
            console.log("I do not get called when using templateUrl")
            let element = fixture.nativeElement;
            expect(element.textContent).toContain("Hello")
          });
      })));
});
```
```
@Component({
  selector: 'form-component',
  template: `Hello` // this works
  // templateUrl: 'app/form-component.html' => this causes timeouterror
})
export class FormComponent {
}
```

I used newest version of angular-cli to create the project, if this somehow helps to reproduce the problem

**Comment by basvandenheuvel** [comment] 2016-03-29 10:17
Any info on when this issue will be solved? To me, yes to me (personal opinion, don't kill me for it), this sounds like a rather important issue, since this makes it impossible for me to unit test components.

**Comment by GaloisGirl** [comment] 2016-03-29 11:40
@basvandenheuvel Technically, you can unit test components, by using "template" instead of "templateUrl" and copy-pasting all your views. It obviously sucks, but it's some workaround.

**Comment by antonybudianto** [comment] 2016-03-29 11:59
IMO it's easier to mock using `template` rather than directly pass the component to tcb, [for example](https://github.com/antonybudianto/angular2-starter/blob/master/app/simplebind/child.component.spec.ts#L15), because it's more straightforward than using overrideTemplate and other methods

**Comment by basvandenheuvel** [comment] 2016-03-29 12:00
@GaloisGirl Indeed that could be kind of a workaround (for some), though we have a lot of components with large html files which change a lot. It's not an option for us to copy the html file content to the 'templateUrl' for testing purposes.

**Comment by GaloisGirl** [comment] 2016-03-29 12:09
@basvandenheuvel That's exactly what I meant by "it obviously sucks". ;) Maybe you can lesser some of the pain with [gulp](https://www.npmjs.com/package/gulp-inject-file), but no need to tell anyone here why copy-paste sucks.

**Comment by johnvnguyen** [comment] 2016-03-29 15:42
It seems to work for me. NgBeta.9

Here's my setup.

```javascript
describe('hello', () => {  
  myComponent: AppComponent;  
  beforeEachProviders(() => {  
    //name of providers  
    MockBackend,
    BaseRequestOptions,
    provide(Http, {
      useFactory: (a: ConnectionBackend, b: BaseRequestOptions) => {
        return new Http(backend, defaultOptions);
      }, deps: [MockBackend, BaseRequestOptions]
    })
  });
  beforeEach(injectAsync(
    [TestComponentBuilder, MockBackend], (tcb, mockBackend) => {
       return tcb.createAsync(AppComponent)
         .then((fixture) => {
           myComponent = fixture;
          });
       }));
  it('I should have my component', () => {
    expect(myComponent).not.isEqual(null);
  });
});
```

**Comment by ericmartinezr** [comment] 2016-03-29 16:24
@johnvnguyen as far as I know the problem remains when using `fakeAsync`, in any other case works.

**Comment by johnvnguyen** [comment] 2016-03-29 17:08
@ericmartinezr I have one fakeAsync test actually plus it works, so I can' really vouch for how reliable it is yet. Maybe it's the way I have my test set up that makes it work. 

```javascript
describe('hello', () => {  
  myComponent: AppComponent;  
  beforeEachProviders(() => {  
    //name of providers  
    MockBackend,
    BaseRequestOptions,
    provide(Http, {
      useFactory: (a: ConnectionBackend, b: BaseRequestOptions) => {
        return new Http(backend, defaultOptions);
      }, deps: [MockBackend, BaseRequestOptions]
    })
  });
  beforeEach(injectAsync(
    [TestComponentBuilder, MockBackend], (tcb, mockBackend) => {
       return tcb.createAsync(AppComponent)
         .then((fixture) => {
           myComponent = fixture;
          });
       }));
  it('I should have my component', () => {
    expect(myComponent).not.isEqual(null);
  });
  it("sending text to input",
        inject([TestComponentBuilder], fakeAsync((tcb: TestComponentBuilder) => {
            tcb.createAsync(AppComponent).then(
                (fixture) => { myComponent = fixture; });
            tick();
            myComponent.debugElement.componentInstance.fullName = "John Nguyen";
            myComponent.detectChanges();

            var input = myComponent.debugElement.query(By.css("#full-name")).nativeElement;
            expect(input.value).toEqual("John Nguyen");

            input.value = "Matt Priest";
            dispatchEvent(input, "input");
            tick();
     expect(myComponent.debugElement.componentInstance.fullName).toEqual("Matt Priest");
        })));
});
```

**Comment by alexeagle** [comment] 2016-03-29 17:29
The eventual solution here is for the template compilation to occur in a build step, then the tests don't need to access an external resource at all.
We may have something available in the medium term, still working on design.
cc @vikerman

**Comment by choeller** [comment] 2016-03-29 18:02
So I can confirm that using `templateURL` now works for me in Beta.9. It's 100% reproducable:

Beta.8: When using templateURL all tests are green, even if some should not
Beta.9: Testing works as expected. 

I'm using angular-cli for creating the project

**Comment by basvandenheuvel** [comment] 2016-03-30 06:25
Any reason why this issue is still open if it is resolved?

**Comment by choeller** [comment] 2016-03-30 09:43
@basvandenheuvel AFAIK it always worked for some people but failed for others. Maybe @goodfield should check if his problems are also solved with Beta.9 or if certain configurations still lead to the 	erroneous behaviour.

**Comment by alexeagle** [comment] 2016-03-30 16:38
I believe this was fixed by https://github.com/angular/angular/pull/6601

**Comment by alexeagle** [comment] 2016-03-30 16:39
If you still have issues, please try to reproduce with beta.9 or later as @choeller suggests.

**Comment by markthethomas** [comment] 2016-06-14 17:43
I'm seeing this w/ rc1 — I get 404s for any components that are using a templateUrl and created using TestComponentBuilder

**Comment by batchu** [comment] 2016-06-14 21:53
@markthethomas  I'm facing the same problem. 

Chrome 51.0.2704 (Windows 7 0.0.0): Executed 0 of 3 SUCCESS (0 secs / 0 secs)
Chrome 51.0.2704 (Windows 7 0.0.0): Executed 2 of 3 SUCCESS (0 secs / 0.02 secs)
ERROR: 'Potentially unhandled rejection [2] Failed to load /app/app.component.html (WARNING: non-Error used)'

**Comment by raguilera82** [comment] 2016-07-20 06:41
Why this issue is marked like closed? I have the same problem (404) in RC.1 version when I am trying to test a component with templateUrl.

Are you sure issue is closed?

**Comment by zoechi** [comment] 2016-07-20 09:30
@raguilera82 current is RC.4

**Comment by anselmhou** [comment] 2016-07-22 23:19
Using RC4 and hit the same issue.  Anybody able to solve or work around on this issue?  Thank you in advance.....

**Comment by markthethomas** [comment] 2016-07-23 00:52
Same here; happy to help fix if possible :) new to the angular internals though 

Mark

Sent from my iPhone

@markthethomas everywhere

**Comment by Dekeyras** [comment] 2016-07-26 09:45
Hey, just ran into this issue in my project. 
Why is this marked as closed when it is obviously still happening.

**Comment by Spittal** [comment] 2016-07-26 16:53
I also have this issue, I've made a related issue in the webpack-starter kit here https://github.com/AngularClass/angular2-webpack-starter/issues/796

**Comment by avalinasab** [comment] 2016-08-09 06:54
This is not actually an Angular TestComponentBuilder issue, we were able to get it to work by configuring proxies in Karma.
Once you have the path for your dist directory Karma should be able to find the template.

i.e.
karma.conf.js
proxies: {
      '/assets/': '/base/dist/dev/assets'
    },

**Comment by joeSaad** [comment] 2016-08-18 21:36
@avalinasab can you please clarify on the proxies? I'm having everything run under app folder which contains components folder where component.spec.ts files reside alongside the actual components. i.e. 
app/components/componentA/
         compA.componentA.ts and compA.componentA.spec.ts 
also i have other places which contain unit testing other than components folder, all of which have templateUrl in them..

**Comment by avalinasab** [comment] 2016-08-20 00:05
@joeSaad how do you bundle the files? I assume you move everything under dist folder.

For example if you "/dist/app/...."

This configuration in the karma.conf.js file should work:

proxies: {
      '/app/': '/dist/app'
    },

Take a look here to see more examples.
http://karma-runner.github.io/1.0/config/configuration-file.html

**Comment by marinho** [comment] 2016-09-22 13:06
still happens to me with **2.0.0 Final** version, bundling with **Webpack 2.1.0-beta.21**

**Comment by vicb** [comment] 2016-09-22 15:40
Closing this as the initial issue is outdated.

If you have any issue with the current Angular version, please open a new issue

**Closed by vicb** 2016-09-22 15:40 UTC
Labels: comp: testing, hotlist: material2

**Comment by marinho** [comment] 2016-09-27 07:09
just in case anyone has the same issue as described in this ticket, the solution for me was to have this entry in my `webpack.test.js` config module, `loaders` section:

```
{
    test: /\.ts$/,
    loaders: [
        'awesome-typescript-loader?sourceMap=false,inlineSourceMap=true,compilerOptions{}=removeComments:false',
        'angular2-template-loader'
    ],
    exclude: [/\.e2e\.ts$/]
},
{
    test: /\.(html|css)$/,
    loader: 'raw-loader',
    exclude: [helpers.root('src/index.html')]
}
```
