### ISSUE TITLE
Zone.js throwing an exception for clearTimeout(undefined)

### ISSUE THREAD

**Issue by pavanpodila** [angular/angular#7680] opened 2016-03-20 20:46 UTC
I am using the Chart.js library which does auto-sizing of the chart on window resize. It does that by using setTimeout() and clearTimeout() when the event is triggered.

The `clearTimeout` is tripping zone.js

Plunkr: http://plnkr.co/edit/JZMytm59PPlYq3bdSoHy

Not sure if this is an issue with Angular or Zone or Chart.js. I tested chart.js independently and it works fine for window resize, when not inside an Angular component.

**Comment by pavanpodila** [comment] 2016-03-20 20:52
Could be a dupe of https://github.com/angular/angular/issues/7666

**Comment by ericmartinezr** [comment] 2016-03-20 20:54
Yes, actually they mentioned it in the website https://angular.io/docs/ts/latest/

**Comment by gdi2290** [comment] 2016-03-20 21:03
if you build from source you can apply this workaround
https://github.com/AngularClass/angular2-webpack-starter/commit/1661e4ce847f90547e7bc875c57e8ebdfb3fef98

**Comment by pavanpodila** [comment] 2016-03-20 22:17
@ericmartinezr @gdi2290 Thanks for the speedy responses. Hope to see **beta.12** come out soon

**Comment by Queatz** [comment] 2016-03-21 07:46
This is breaking things.  Needs to be fixed!!

**Comment by igorzg** [comment] 2016-03-21 08:04
+1 Same issue

**Comment by bianchessi** [comment] 2016-03-21 11:17
+ 1

**Comment by pkozlowski-opensource** [comment] 2016-03-24 16:31
Duplicate of #7666, fixed in beta.12.

**Closed by pkozlowski-opensource** 2016-03-24 16:31 UTC
