### ISSUE TITLE
Update package.json in angular webpack tutorial (please add "karma-jasmine-html-reporter" dependency)

### ISSUE THREAD

**Issue by FelipeMG** [angular/angular#20011] opened 2017-10-30 02:19 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When following the webpack tutorial in https://angular.io/guide/webpack#what-is-webpack and running the test the terminal threw this message:
Can not load reporter "kjhtml", it is not registered!   Perhaps you are missing some plugin?

## Expected behavior

The tests should run without errors. The solution is to update the package.json archive in the Configuring Webpack section of the tutorial. You just have to add
"karma-jasmine-html-reporter": "^0.2.2",   after the "karma-jasmine": "^1.0.2" dependency.
This will avoid the error.

## What is the motivation / use case for changing the behavior?

To avoid the error for programmers new to webpack and angular.

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by jenniferfell** [comment] 2018-01-23 23:15
Issue is with example in https://angular.io/guide/webpack#what-is-webpack. Not sure which comp webpack falls under. Build?

**Comment by gkalpak** [comment] 2018-01-24 12:05
It doesn't fall under any other component. It is a guide about how to set up webpack for an Angular app. So, it falls under `docs` :grin:
<sub>(The issue is with the underlying example, so it would fall under `docs-infrastructure` if we had such a label 😄)</sub>

##
That being said, the webpack guide is "deprecated" and removed from the sidenav. Only accessible through direct URL (or search 😒).

There are PRs in progress to remove it altogether (e.g. #20213 or #20706).
See [here][1] for the reasoning.

##
So, for the reasons mentioned above, I am going to close this as `won't fix`.

[1]: https://github.com/angular/angular/pull/20199#issuecomment-342113293

**Closed by gkalpak** 2018-01-24 12:05 UTC
Labels: comp: build & ci, comp: examples
