### ISSUE TITLE
ExpressionChangedAfterItHasBeenCheckedError from RouterOutlet#isActivated

### ISSUE THREAD

**Issue by pgeyman** [angular/angular#48721] opened 2023-01-12 18:47 UTC
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

Yes

### Description

I recently migrated to Angular 15 and I am now getting an `ExpressionChangedAfterItHasBeenCheckedError` in my view when accessing the router outlet's `isActivated` property. This was working before the migration.

It happens when a child route is activated.

View Template code (`configuration-dashboard.component.html`):
```
<div class="dashboard-button-grid" *ngIf="!outlet.isActivated">

    <ng-container *ngFor="let configurationModule of configurationModules">
        <dashboard-button [icon]="configurationModule.icon"
                          [label]="configurationModule.name"
                          (click)="onNavigateToModule( configurationModule.path )">
        </dashboard-button>
    </ng-container>
</div>

<router-outlet #outlet="outlet">
</router-outlet>
```

### Please provide the exception or error you saw

```true
ERROR Error: NG0100: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'true'. Current value: 'false'. Find more at https://angular.io/errors/NG0100
    at throwErrorIfNoChangesMode (core.mjs:9231:11)
    at bindingUpdated (core.mjs:13744:17)
    at Module.ɵɵproperty (core.mjs:14461:9)
    at ConfigurationDashboardComponent_Template (configuration-dashboard.component.html:1:37)
    at executeTemplate (core.mjs:11242:9)
    at refreshView (core.mjs:11127:13)
    at refreshComponent (core.mjs:12188:13)
    at refreshChildComponents (core.mjs:10918:9)
    at refreshView (core.mjs:11177:13)
    at refreshEmbeddedViews (core.mjs:12142:17)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.0.4
Node: 18.12.1
Package Manager: npm 8.19.2
OS: darwin arm64

Angular: 15.0.4
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, material, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1500.4
@angular-devkit/build-angular   15.0.4
@angular-devkit/core            15.0.4
@angular-devkit/schematics      15.0.4
@schematics/angular             15.0.4
rxjs                            6.5.4
typescript                      4.8.4
```

**Comment by atscott** [comment] 2023-01-13 14:45
Please provide a reproduction. I wasn't able to reproduce the issue in https://stackblitz.com/edit/angular-jho3yy?file=src%2Fmain.ts. That said, this is likely due to https://github.com/angular/angular/pull/46569 which changed the exact timing of the outlet being activated and was documented as a breaking change in v15. 
This issue is covered under the numerous other issues for the ExpressionChangedAfterItHasBeenCheckedError and the unfortunate truth is that it's just "how it works" at the moment. The algorithm requires a single flow of data and the reference to the outlet above where it's defined breaks that. We're looking at addressing this problem in the framework as a whole this year.

Your current options to avoid this might be (just guesses since I don't have a reproduction):
* If your actual template is similar to what's shown in this report, try moving router-outlet above where you're accessing it
* Keep a local variable for `isActivated` and update it in a `Promise` if the value is different in the outlet
* Create your own router outlet which reverts the change in #46569

Closing based on the assumption that this is due to #46569.

**Closed by atscott** 2023-01-13 14:45 UTC
