### ISSUE TITLE
provide method to multiple copies of ng-content

### ISSUE THREAD

**Issue by vthinkxie** [angular/angular#21462] opened 2018-01-11 04:04 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Is there any way to multiple copies of `ng-content`?
I try to copy it with the demo below, but not work.

Only `ContentChild` can be copied, but it will bring much trouble when I want to build a [lib](https://github.com/NG-ZORRO/ng-zorro-antd) for users that they have to wrap all the content with `ng-template` everywhere.

Here is the mini reproduction link:

https://stackblitz.com/edit/angular-mofgqd?file=app%2Fchild.component.ts

There is similar code in `Material Design` [here](https://github.com/angular/material2/blob/master/src/lib/tabs/tab.html), but they only need to move the `ng-content` to right place other than copy it.

Have I missed something, or is there any way to hack this?

## Expected behavior

provide some methods to copy `ng-content` like add `copy` method like `insert`
or some other way to implement this.
https://github.com/angular/angular/blob/6be9c0466cfe60d6555b0430285c1ae983f977b3/packages/core/src/linker/view_container_ref.ts#L96

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/angular-mofgqd?file=app%2Fchild.component.ts

## What is the motivation / use case for changing the behavior?

We are building the components that support fixed columns in the table like the [ant design react version](https://ant.design/components/table/#components-table-demo-fixed-columns), we have to copy the content in `td` and `th` to the left and right in order to fix them.

If there is no way to copy `ng-content`, users will have to code like
```html
<tr>
 <td><ng-template></ng-template></td>
 <td><ng-template></ng-template></td>
</tr>
```
which is quick complex

## Environment

<pre><code>
Angular version: latest

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by trotyl** [comment] 2018-01-11 04:11
Duplicate of #13894

**Comment by Toxicable** [comment] 2018-01-11 08:35
Take a look at https://angular.io/guide/structural-directives it's a bit of sugar for using templates

**Comment by vthinkxie** [comment] 2018-01-11 08:44
@Toxicable thanks for the tips, but the sugar can only be implement in `Directive`, I have to use `Component` to write some external template in the element.
Thanks for your advice anyway.

**Comment by Toxicable** [comment] 2018-01-11 08:46
Yes that was the point. Use a Directive along with a Component to solve your problem

**Comment by pkozlowski-opensource** [comment] 2018-01-11 11:21
Yep, this is duplicate of #13894

**Closed by pkozlowski-opensource** 2018-01-11 11:21 UTC
