### ISSUE TITLE
AOT form.controls compile error

### ISSUE THREAD

**Issue by Prepd-Root** [angular/angular#11406] opened 2016-09-07 09:03 UTC
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
AOT compilation error for form controls in the template when accessing the controls like form.controls.first ( check plunkr example ).

Error encountered : Property 'first' does not exist on type '{ \[key: string\]: AbstractControl; }'.

NOTE : this works fine if accessed like  form.controls\['first'\] ( check plunkr example )

**Expected/desired behavior**
Compilation without error. Unless it's behavior is meant to be like this, and disallow accessing controls like specified above.

**Reproduction of the problem**
[Plunkr Example](https://plnkr.co/edit/M3tljJm2Pt3iVLqmfUhZ)

**Please tell us about your environment:**
Windows 

* **Angular version:** 2.0.0-rc.X
 2.0.0-rc6

* **Language:** [all | TypeScript X.X | ES6/7 | ES5] 
TypeScript 2.0.2

**Comment by vicb** [comment] 2016-09-07 11:49
from your comment, the issue is most probably related to minifying the code, not angular.
closing as:
- not related to ng,
- missing envirnonment info

**Closed by vicb** 2016-09-07 11:49 UTC
