### ISSUE TITLE
Link type inference in TypeScript page not found in tutorial

### ISSUE THREAD

**Issue by letronghieu4897** [angular/angular#53480] opened 2023-12-10 13:45 UTC
### Describe the problem that you experienced

On page **Updating the Component Class** https://angular.dev/tutorials/learn-angular/updating-the-component-class. At the section 1 [Add a property called city](https://angular.dev/tutorials/learn-angular/updating-the-component-class#add-a-property-called-city) when I try to click into the link [type inference in TypeScript](https://angular.dev/typescript.org/type-inference) it redirect me into page not found.

### Enter the URL of the topic with the problem

https://angular.dev/tutorials/learn-angular/updating-the-component-class

**Comment by JoostK** [comment] 2023-12-10 14:43
Thanks for the report, this is a duplicate of https://github.com/angular/angular/issues/52553 for which the fix is pending deployment.

**Closed by JoostK** 2023-12-10 14:43 UTC
