### ISSUE TITLE
Missing documentation on cli config for universal app

### ISSUE THREAD

**Issue by jcampbell05** [angular/angular#22349] opened 2018-02-21 16:03 UTC
In the example code at https://angular.io/guide/universal#universal-in-action there is an entry for the server app which is lacking in the tutorial itself.

It also misses an example  for the `main.server.ts` both in the tutorial and the file itself.

Without this, the code doesn't work.

**Comment by Yerkon** [comment] 2018-02-22 03:58
@jcampbell05,
Thanks for reporting this issue. However this issue is a duplicate of an existing issue #21983. Please subscribe to that issue for future updates.

**Comment by petebacondarwin** [comment] 2018-02-22 08:36
Thanks for spotting the duplicate @Yerkon

**Closed by petebacondarwin** 2018-02-22 08:36 UTC
Labels: comp: aio
