### ISSUE TITLE
ViewContainerRef.createComponent inside a structural directive adds the component as a SIBLING of the element the directive is called on

### ISSUE THREAD

**Issue by classicmike** [angular/angular#30743] opened 2019-05-30 05:19 UTC
### Description

I have a requirement of creating a structural directive that creates a child component inside inside the element where the directive is being called. If I use ```ViewConainerRef.createComponent``` component is injected as a SIBLING of the element where the directive is called. i.e:

If I write a directive called *fooDirective, Like this and want to inject ```<foo-component>```:
```
<div *fooDirective></div>
```

Here is what it currently outputs:
``` 
<div></div>
<foo-component></foo-component>
```
And what I was expecting was this:
```
// what I was expecting
<div>
    <foo-component></foo-component>
</div>
```

I know I've found some issues that indicate ViewContainerRef.createComponent injects new components as siblings by design, but I want to know for my specific instance it works this way by design as well. If it does is there a workaround we can do to get by?

Some clarification would go a very long way as I feel it kind-of is not well documented explicitly.

Thanks.

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-insert-component-in-structural-directive?file=app%2Fapp.component.ts

**Comment by trotyl** [comment] 2019-05-30 05:29
Duplicate of https://github.com/angular/angular/issues/8817, https://github.com/angular/angular/issues/29448

**Comment by pkozlowski-opensource** [comment] 2019-05-31 07:12
Yep, those are indeed duplicates, thnx @trotyl !

**Closed by pkozlowski-opensource** 2019-05-31 07:12 UTC
Labels: comp: core & compiler

**Comment by classicmike** [comment] 2019-06-02 23:56
Thanks for the clarification. Is there something in the documentation site that explains this particular mechanic. I'm sure there would be a few devs that would get caught in this gotcha...

**Comment by trotyl** [comment] 2019-06-03 02:51
> Anchor element that specifies the location of this container in the containing view. Each view container can have only one anchor element, and each anchor element can have only a single view container.
> 
> **Root elements of views attached to this container become siblings of the anchor element in the rendered view.**

It actually has already been covered in [the API doc](https://angular.io/api/core/ViewContainerRef).
