### ISSUE TITLE
Allow to change AbstractControl.updateOn after the component has been created

### ISSUE THREAD

**Issue by dwilches** [angular/angular#42480] opened 2021-06-04 17:29 UTC
# Feature Request

### Relevant Package
This feature request is for @angular/forms

### Description
We can specify when the `status` and `value` of FormControls are updated using the `updateOn` property like this:
```
    range = new FormGroup({
        start: new FormControl(this.timeService.now(), Validators.required),
        end: new FormControl(this.timeService.now(), Validators.required),
    }, { updateOn: "blur" });
```
This works well when we know the value of `updateOn` at compile time, but there is currently not a way to control `updatedOn` using an `@Input` in our component, so this is not valid:
```
export class DateRangePickerComponent implements OnInit {
    @Input() updateOn: "blur" | "change" | "submit";

    range = new FormGroup({
        start: new FormControl(this.timeService.now(), Validators.required),
        end: new FormControl(this.timeService.now(), Validators.required),
    }, { updateOn: "blur" });

    ngOnInit(changes: SimpleChanges) {
        if (changes.updatedOn) this.range.setUpdateOn(this.updatedOn);
    }
}
```

The only way to allow changing `updateOn` after the form control has been created is by replacing it with a new form control.

This feature request is asking you to provide a way to update the value of `updateOn` because there aare cases where this is useful.

For example, my case is I have a `mat-date-range-input` like this:
```
            <mat-date-range-input [formGroup]="range"
                                  [rangePicker]="picker"
                                  [max]="maxMoment">
                <input matStartDate type="text" formControlName="start"/>
                <input matEndDate type="text" formControlName="end"/>
            </mat-date-range-input>
            <mat-datepicker-toggle matSuffix [for]="picker"></mat-datepicker-toggle>
            <mat-date-range-picker #picker></mat-date-range-picker>
```
This component sometimes is used as part of a larger form (where I want to disable the "Save" button as soon as an invalid value is entered, hence I want `updateOn: "change"` as I cannot wait for a blur to happen before disabling the button (or the user could click it). 

But in some other usages, I use this to control the dates passed in an HTTP request, and I don't want every single edit to emit an event because then while writing `2021-05-15` it would emit `2021-05-1` as soon as I type that last `1 (because it's interpreted as `2021-05-01`, I'm using Angular's `MaterialMomentAdapter`).

For this reason, I would like to be able to control the value of `updateOn` at will.

Thanks.

### Describe the solution you'd like
Either add to AbstractFormControl:
* `setUpdateOn()`
* `set updateOn()`

### Describe alternatives you've considered
I'm currently creating the form controls on ngOnInit, which is ok as I always pass a literal string to `@Input() updateOn` in my component, but wouldn't work if I passed a variable that is set after ngOnInit has been called, as ngOnChanges is where this would have to be.

Another alternative would be to recreate the FormGroup inside of ngOnChanges.

**Comment by AndrewKushnir** [comment] 2021-06-05 02:07
Closing as a duplicate of #35005.

**Closed by AndrewKushnir** 2021-06-05 02:07 UTC
Labels: comp: forms, feature
