### ISSUE TITLE
Output not mapped to expression binding in upgraded component (@angular/upgrade)

### ISSUE THREAD

**Issue by psmyrdek** [angular/angular#21590] opened 2018-01-17 13:31 UTC
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I'd like to create a facade directive (... extends UpgradeComponent) for my component written in AngularJS. Based on https://angular.io/guide/upgrade#using-angularjs-component-directives-from-angular-code I see that it's possible to use `@Output()` in my Angular directive, which should be mapped to expression binding (`&`) in AngularJS.

So starting from AngularJS, there's my component which I would like to upgrade:

```
angular
    .module('my-app')
    .component('myDatepicker', {
        template: '...',
        binding: {
            dateChanged: '&'
        },
        controller: MyDatepickerController
    });
```

And there's also my directive written in Angular, which should work as a facade over this datepicker. It's content is as follows:

```
@Directive({
  selector: 'app-datepicker'
})
export class DatepickerDirective extends UpgradeComponent {

  @Output()
  dateChanged = new EventEmitter<any>();

  constructor(elementRef: ElementRef, injector: Injector) {
    super('myDatepicker', elementRef, injector);
  }

}
```

Now I want to subscribe for this Output in Angular template:
`<app-datepicker (dateChanged)="onDateChanged($event)"></app-datepicker>`

...but in AngularJS component's hook, `$onInit`, I see that this specific binding is undefined. There's no such thing as `dateChanged`, and I also cannot call it from inside of AngularJS controller.

(problem exists even when you don't create an instance of EventEmitter `= new...` in Angular)

In console: `ctrl.dateChanged is not a function`

Workaround for this is about changing expression binding to one-way binding in AngularJS `dateChanged: '&'` -> `dateChanged: '<'` and replacing Output with Input. Then it works.

## Expected behavior

(Based on docs) it should be possible to create dedicated Output in Angular directive, for each expression binding from upgraded component.

## Minimal reproduction of the problem with instructions
1. Create sample component in AngularJS, containing expression binding
2. Create facade directive for it in Angular, create Output inside of it
3. From Angular app, subscribe for newly created Output and see what happens after making some actions

## What is the motivation / use case for changing the behavior?

Either docs should be updated, or there's something wrong with mapping between Output and expression binding?

## Environment

<pre><code>
Angular version: 5.2.0, AngularJS 1.5.11

Browser:
- [x] Chrome (desktop) version 63.0.3239.132
- [x] Firefox version 57

**Comment by gkalpak** [comment] 2018-01-23 11:37
It should indeed work the way you described. And it does afaict. Here is a [short demo][1].
It is hard to tell what might be the problem in your case without an actual reproduction, but feel free to modify my example to reproduce your issue and post it back here.

<sub>Closing for now, since everything seems to work as expected.</sub>

[1]: https://stackblitz.com/edit/ngupgradestatic-playground-uskw49

**Closed by gkalpak** 2018-01-23 11:37 UTC
Labels: comp: upgrade/static

**Comment by gund** [comment] 2019-03-19 19:11
It also does not work for me.
The output is just `undefined` inside of angularjs component...

And the demo page does not work anymore.

I'm on Angular `v7.1.3` and AngularJs `v1.5.9`:
```
Angular CLI: 7.1.2
Node: 11.9.0
OS: darwin x64
Angular: 7.1.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, upgrade

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.11.2
@angular-devkit/build-angular     0.11.2
@angular-devkit/build-optimizer   0.11.2
@angular-devkit/build-webpack     0.11.2
@angular-devkit/core              7.1.2
@angular-devkit/schematics        7.1.2
@angular/cdk                      7.1.1
@angular/cli                      7.1.2
@angular/flex-layout              7.0.0-beta.19
@angular/material                 7.1.1
@ngtools/webpack                  7.1.2
@schematics/angular               7.1.2
@schematics/update                0.11.2
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.23.1
```

**Comment by gkalpak** [comment] 2019-03-20 10:00
@gund, I fixed the link. Thx for the heads-up.
