### ISSUE TITLE
template-driven forms: ngForm reset not work

### ISSUE THREAD

**Issue by moonlight824** [angular/angular#24946] opened 2018-07-18 02:33 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

According to the [doc](https://angular.io/guide/forms#show-and-hide-validation-error-messages), when I enter a name in the form and click the *New Hero* button with *reset*, the error message will not display. While it did not work.

## Expected behavior

The *reset* method of *ngForm* will clear both the form and its control flags.

## Minimal reproduction of the problem with instructions

https://angular.io/generated/live-examples/forms/stackblitz.html

## Environment

<pre><code>
Angular version: 6.0.9

Browser:
- [ x ] Chrome (desktop) version 67
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  Win10

Others:

</code></pre>

**Comment by kara** [comment] 2018-07-18 16:57
@lqm229026 The problem here is that the live example in the docs has an extra form below that is re-assigning the value of the `#heroForm` template variable (so the wrong form is being reset). This needs to be fixed in the docs.

If you try resetting a form normally, it works as intended. See simplified example here: https://stackblitz.com/edit/angular-3gzflm?file=src%2Fapp%2Fapp.component.html

**Comment by dylhunn** [comment] 2021-05-24 23:42
This appears to have been fixed at some point. Clicking "new hero with reset" in the live example _does_ reset the correct form, hiding the error messages.

**Closed by dylhunn** 2021-05-24 23:42 UTC
Labels: P3, comp: docs, comp: examples, comp: forms, forms: template-driven, freq3: high, type: bug/fix
