### ISSUE TITLE
Content projection with slot doesn't always work

### ISSUE THREAD

**Issue by Palapapaa** [angular/angular#36039] opened 2020-03-12 15:25 UTC
# 🐞 bug report

### Affected Package

Don't know :/

### Is this a regression?

I don't think so.

### Description

I have components that I want to use as Angular Elements.
In order to do that I use `slot` and `ViewEncapsulation.ShadowDom` for content projection.
The content projection works when using `ng serve` but not in storybook or as an Angular Elements.

I have no idea why it does not work.

## 🔬 Minimal Reproduction

I've made a repro with stackblitz.
When my component is used as root component it works :
https://stackblitz.com/edit/angular-srq66r

But not when it's not the root component
https://stackblitz.com/edit/angular-b8e9l4

## 🔥 Exception or Error
<pre><code>
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 7.0.7
Node: 10.15.3
OS: win32 x64
Angular: 9.0.6
... animations, common, compiler, core, forms, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.10.7
@angular-devkit/build-angular     0.10.7
@angular-devkit/build-optimizer   0.10.7
@angular-devkit/build-webpack     0.10.7
@angular-devkit/core              7.0.7
@angular-devkit/schematics        7.0.7
@angular/cli                      7.0.7
@angular/compiler-cli             7.0.4
@angular/language-service         7.0.4
@ngtools/webpack                  7.0.7
@schematics/angular               7.0.7
@schematics/update                0.10.7
rxjs                              6.5.4
typescript                        3.1.6
webpack                           4.19.1

</code></pre>
(not sure about version, I've just downloaded the stackblitz and did `ng version`)

**Comment by sod** [comment] 2020-03-20 17:15
Inside angular it's `<ng-content></ng-content>`, not slot.

I wonder why there are two different tags for content projects.

**Comment by Palapapaa** [comment] 2020-03-23 08:07
I thought that when creating Angular Elements it was better to use `slot` and `ViewEncapsulation.ShadowDom` for content projection.

Can someone confirm (or not) this ?

**Comment by jelbourn** [comment] 2020-10-19 21:06
Duplicate of #31242

**Closed by jelbourn** 2020-10-19 21:06 UTC
Labels: comp: core
