### ISSUE TITLE
On angular http client search title is wrong in results

### ISSUE THREAD

**Issue by ajitsinghkaler** [angular/angular#33858] opened 2019-11-15 18:10 UTC
# 📚 Docs or angular.io bug report

### Description 

Whenever I search angular http client it shows a search result with the title Here - Angular I don't know why this is happening the title tag is fine. This may be an issue because the crawler has not crawled angular.io for some time. 

## 🔬 Minimal Reproduction
Search angular http client

### What's the affected URL?**
 https://angular.io/guide/http

### Reproduction Steps**

Search angular http client on Google

### Expected vs Actual Behavior**

Actual
Search angular http client the title is Here -Aangular

Expected
Search angular http client the title should be Angular - HttpClient

## 📷Screenshot

![angular http client - Google Search](https://user-images.githubusercontent.com/39260684/68964720-14310300-0800-11ea-88f0-bf00e6e50d20.png)

## 🔥 Exception or Error
<pre><code>

</code></pre>

### Browser info

Chrome Version:Version 78.0.3904.87 (Official Build) (64-bit)
Device: Laptop with ubuntu OS

**Comment by gkalpak** [comment] 2019-11-18 12:09
I search `angular http client` in an incognito window and the result seemed correct to me:

![ng-http-search](https://user-images.githubusercontent.com/8604205/69050957-ba048d80-0a0b-11ea-8e4b-6860660ba91f.png)

Not sure there is anything to do here. Maybe it was caching issue or an outdated index.

I looked at the page in Google Search Console and it looked correct, but I requested re-indexing just in case. I am going to close this issue, since I don't think there is anything else we can do (given that I can't reproduce the error).

##
In any case, thx for bringing this up and feel free to open a new sisue if the problem persists after a few days.

**Comment by ajitsinghkaler** [comment] 2019-11-18 18:57
@gkalpak maybe this may be an internationalization problem because it is showing the same in all my devices and browsers even in incognito.

**Comment by ajitsinghkaler** [comment] 2019-11-21 16:42
![Desktop screenshot (8)](https://user-images.githubusercontent.com/39260684/69357766-b0995080-0cab-11ea-803f-b8bee6ffe1c6.png)

@gkalpak I am still getting the same issue it is because I'm in India that may be the problem

**Comment by IgorMinar** [comment] 2019-11-22 20:25
I can repro the issue:
![Screen Shot 2019-11-22 at 12 24 35 PM](https://user-images.githubusercontent.com/216296/69457970-255ba180-0d23-11ea-8fbb-34b7699b0133.png)

but I don't know what's causing it.

my localized url is: https://www.google.com/search?q=angular+http+client&rlz=1C5CHFA_enUS782US782&oq=angular+http+client&aqs=chrome..69i57j69i64j69i60l3.694j0j1&sourceid=chrome&ie=UTF-8

**Comment by gkalpak** [comment] 2019-11-22 23:18
FWIW, I get the correct `HttpClient - Angular` when navigating to your URL 🤷‍♂

**Comment by ajitsinghkaler** [comment] 2019-11-27 16:33
@gkalpak @IgorMinar can we do something about this

**Comment by Splaktar** [comment] 2019-12-02 20:57
I can reproduce this as well. [url](https://www.google.com/search?q=angular+http+client&oq=angular+http+client&aqs=chrome..69i57j0j69i65j69i60l3.2614j0j7&sourceid=chrome&ie=UTF-8)

**Comment by petebacondarwin** [comment] 2020-10-17 12:07
I cannot reproduce in UK (both normal and incognito). I am not sure there is much we can do...

<img width="624" alt="Screenshot 2020-10-17 at 13 06 40" src="https://user-images.githubusercontent.com/15655/96336711-a5949f00-1079-11eb-859d-19c15b737fe6.png">

**Comment by Splaktar** [comment] 2021-04-26 14:43
This is no longer reproducible for me via the [same url](https://www.google.com/search?q=angular+http+client&oq=angular+http+client&aqs=chrome..69i57j0j69i65j69i60l3.2614j0j7&sourceid=chrome&ie=UTF-8) as I saw it in 2019 or via [this new url](https://www.google.com/search?q=angular+http+client&oq=angular+http+client&aqs=chrome..69i57j0i20i263j0l2j0i10j0j69i60l2.416j0j9&sourceid=chrome&ie=UTF-8) or the URL that Igor posted.

![Screen Shot 2021-04-26 at 10 43 02](https://user-images.githubusercontent.com/3506071/116101855-3200c980-a67c-11eb-97f2-49f0c39ac5f4.png)

**Comment by petebacondarwin** [comment] 2021-04-26 14:57
That's to non-repros, so I am going to close. Thanks @Splaktar

**Closed by petebacondarwin** 2021-04-26 14:57 UTC
Labels: P5, comp: docs-infra
