### ISSUE TITLE
routerLink in child not working - due to defer Block - getting recursion error

### ISSUE THREAD

**Issue by dreamstar-enterprises** [angular/angular#55776] opened 2024-05-13 13:58 UTC
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

Yes

### Description

My activatedroute.snapshot.params['id'], keeps showing an old id, when I've navigate to an entity with a different id. 

The url address changes to reflect the new id, but activatedroute does not. So all my router links, on the page point to the wrong href address (since they are based on the content of activated route)

**My component code**

    ```
<div class="fadeIn">
          <!-- navigation menu -->
          <app-project-navigation></app-project-navigation> - activated route here doesn't match the id in the URL
          <!-- page router -->
          <router-outlet></router-outlet>
</div>
```

**Route paths**

Entity gets loaded at the following route

```
      {
        path: 'entity/:id',
        title: 'App | Entity Details',
        loadChildren: () => import('../entity-parent/entity-parent.routes').then((m) => m.ENTITY_ROUTES),
    
      },
```

**ActivatedRoute**

Running this in the parent works fine, it changes to match the address bar, as I'd expect.

`    console.log(this.activatedRoute.snapshot.params['id'])`

But the child template, inside the parent 

`    <app-project-navigation></app-project-navigation> `

, if I run the same code, I get the wrong result

Surely each time I naviate to a new entity/:id, when the entity component gets loaded, the activatedroute.snapshot.params would also change correct in the parent (as it does), but any child of the parent too?

Here is more proof the issue in the child (app-project-navigation):
<img width="689" alt="Screenshot 2024-05-13 at 14 54 06" src="https://github.com/angular/angular/assets/39380005/62b35dfb-c307-4809-946b-1ad6ae214b57">

```
      ngOnInit(){
        console.log(this.router.url)
        console.log(this.activatedRoute.snapshot.params['id']) --> the observable version of this returns the same result

      }
```

Are just returning different results, and routerLink looks like it references to activatedRoute it seems, so simple relative link referencing, like this doesn't work
```

    <li>
      <a routerLink="./contracts" routerLinkActive="active">
        CONTRACTS
      </a>
    </li>
```

### Please provide a link to a minimal reproduction of the bug

See screenshots above

### Please provide the exception or error you saw

```true
See above
```

**Comment by atscott** [comment] 2024-05-13 15:32
Please provide a runnable reproduction. There’s not enough information here to determine the issue but on the surface, the behavior seems likely correct as you’re using `snapshot`, which is exactly that: a snapshot of the state. The value will only update if you read a new snapshot and that depends on whether the bindings execute again.

**Comment by dreamstar-enterprises** [comment] 2024-05-14 22:41
Maybe this might help:

https://stackblitz.com/edit/stackblitz-starters-ki6sdw?file=src%2Fmain.ts

**Parent**

```
  protected ngOnInit(): void {

    // assign project ID
    this.activatedRoute.params.
    pipe(takeUntilDestroyed(this.destroyRef))
      .subscribe((params) => {
      this.projectID = params['id'];
      console.log(this.projectID)
    });

    // if project in store doesn't match, get it
    if (this.projectStore.project()._id != this.projectID) {
      // do something
    }
  }
```


**Child**

```
  ngOnInit(){
    console.log(this.router.url)
    this.activatedRoute.params.
    pipe(takeUntilDestroyed(this.destroyRef))
      .subscribe((params) => {
        console.log(params['id'])
      });
  }
```

**What my console shows:**
<img width="742" alt="Screenshot 2024-05-14 at 23 39 58" src="https://github.com/angular/angular/assets/39380005/d95b3539-6547-424f-bee3-8b9d1b59662d">

**Comment by atscott** [comment] 2024-05-15 00:58
The reproduction doesn’t have `provideRouter` with any routes. Is that intended?

**Comment by dreamstar-enterprises** [comment] 2024-05-15 07:21
Sorry, 
This ought to work, but I'm getting a compilation error that it cannot find App_Routes:

https://stackblitz.com/edit/stackblitz-starters-ki6sdw?file=src%2Fapp-routes.ts

**Comment by JeanMeche** [comment] 2024-05-15 07:34
Your `main.ts` should be outside the `src` directory.

**Comment by dreamstar-enterprises** [comment] 2024-05-15 11:10
Removed that bug... not sure if it works for you

https://stackblitz.com/edit/stackblitz-starters-ki6sdw?file=src%2Fmain.ts

(for me it says ...Loading still)

In JetBrains, I still get this:

![image](https://github.com/angular/angular/assets/39380005/db865ae7-1681-4e74-a2bf-9dc68f36140d)

**Comment by JeanMeche** [comment] 2024-05-15 11:12
Check the console for the errors. The selector on the bootstrapped component doesn't exist in the index.html.

**Comment by dreamstar-enterprises** [comment] 2024-05-15 11:18
Strange, my consol is clean, but the window to the right says '...Loading'

<img width="1053" alt="Screenshot 2024-05-15 at 12 18 20" src="https://github.com/angular/angular/assets/39380005/66835d65-63f1-4ba6-8fc2-f839fa2f65a0">

**Comment by JeanMeche** [comment] 2024-05-15 11:20
Check the browser's console, it's not a build error but a runtime error.

**Comment by dreamstar-enterprises** [comment] 2024-05-15 11:33
Looks fine on StackBlitz... maybe I need to upgrade Angular or JetBrains:

<img width="1165" alt="Screenshot 2024-05-15 at 12 33 09" src="https://github.com/angular/angular/assets/39380005/a94502c2-95f4-40df-8879-b108c018cf86">

**Comment by dreamstar-enterprises** [comment] 2024-05-15 11:35
Only difference is that I lazy load the project routes in app_routes:

```
export const APP_ROUTES: Routes = [
  {
    path: 'projects',
    title: 'App | Projects',
    loadChildren: () => import('../1. project-module/projects/projects.routes').then((m) => m.PROJECTS_ROUTES),
  },
  {
    path: 'projects/:id',
    title: 'App | Project Details',
    loadChildren: () => import('../1. project-module/project-container/project-container.routes').then((m) => m.PROJECT_ROUTES),

  },
```

![image](https://github.com/angular/angular/assets/39380005/9548e5e1-350d-481c-8a45-a374b929a154)

**Comment by dreamstar-enterprises** [comment] 2024-05-15 11:39
Ahh.. but the child in my code does sit inside a defer block, inside the parent! Maybe that is it

**Comment by JeanMeche** [comment] 2024-05-15 11:53
It was indeed fixed by #54864

**Comment by dreamstar-enterprises** [comment] 2024-05-15 12:06
Crumbs, but now I get the same re-cursion error as last time, after doing npm install @angular/core... : (

<img width="1387" alt="Screenshot 2024-05-15 at 13 04 56" src="https://github.com/angular/angular/assets/39380005/0fefcc9f-8283-4f7a-bab3-a50abe9af62f">

```
"dependencies": {
    "@angular/animations": "^17.3.2",
    "@angular/cdk": "^17.3.1",
    "@angular/common": "^17.3.2",
    "@angular/compiler": "^17.3.2",
    "@angular/core": "^17.3.8",
    "@angular/forms": "^17.3.2",
    "@angular/material": "^17.3.1",
    "@angular/material-experimental": "^17.3.5",
    "@angular/material-moment-adapter": "^17.3.5",
    "@angular/platform-browser": "^17.3.2",
    "@angular/platform-browser-dynamic": "^17.3.2",
    "@angular/router": "^17.3.2",
    "@material/web": "^1.4.1",
    "@ngrx/operators": "^17.2.0",
    "@ngrx/signals": "^17.2.0",
    "lodash": "^4.17.21",
    "material-components-web": "^14.0.0",
    "moment": "^2.30.1",
    "rfdc": "^1.3.1",
    "rxjs": "~7.8.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.14.2"
  },
```

**Comment by atscott** [comment] 2024-05-15 13:09
Closing as this issue has become more of a support request and requires a reproduction in order to debug. (Reproductions can be GitHub repositories). Please open a new issue with a reproduction if you are able to create one.

**Closed by atscott** 2024-05-15 13:09 UTC
Labels: needs reproduction
