### ISSUE TITLE
Not possible to override lifecycle hooks in decorators

### ISSUE THREAD

**Issue by felipeissa** [angular/angular#39057] opened 2020-09-30 11:24 UTC
# 🐞 bug report

After upgrading from angular 7 to angular 10 I noticed the lifecycle hooks cannot be overrided by decorators anymore. 

#30497 had a similar issue reported, but it was fixed on 10.0.5 and on 10.1.0 the issue I'm reporting still happening.

### Is this a regression?

Yes, worked just fine on 7.2 version

### Description

A decorator which changes some lifecycle hook of a angular component seems to have no effect on the original component. On the decorator it seems to override the method, but on execution only the old behavior is applied.

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-ivy-lifecycle-hooks-demo?file=src/app/app.component.ts

First add some item to the array, it will create a child component. 
Then clicks clear, the child will be destroyed (can check on console)
When the subject emitts, the child will print it's value because the decorator overriden onDestroy implementation wasn't called (no output on console)

## 🔥 Exception or Error

None

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 10.1.2
Node: 10.16.0
OS: win32 x64

Angular: 10.1.2
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1001.2
@angular-devkit/build-angular      0.1001.2
@angular-devkit/build-ng-packagr   0.1001.2
@angular-devkit/core               10.1.2
@angular-devkit/schematics         10.1.2
@angular/cdk                       10.2.1
@angular/material                  10.2.1
@angular/material-moment-adapter   10.2.1
@schematics/angular                10.1.2
@schematics/update                 0.1001.2
ng-packagr                         10.1.0
rxjs                               6.6.3
typescript                         4.0.3

</code></pre>

**Comment by AleksanderBodurri** [comment] 2020-09-30 22:24
Related (duplicate?) https://github.com/angular/angular/issues/38241

**Comment by atscott** [comment] 2020-10-19 17:55
Closing as duplicate of #39057. Also see https://github.com/angular/angular/issues/36776#issuecomment-618234193

> we take lifecycle methods from the class definition instead of an instance

**Closed by atscott** 2020-10-19 17:55 UTC
Labels: comp: core
