### ISSUE TITLE
Page Not Found: https://angular.dev/cli/commands

### ISSUE THREAD

**Issue by OszkarOlah** [angular/angular#53132] opened 2023-11-23 13:36 UTC
### Describe the problem that you experienced

Page Not Found
https://angular.dev/cli/commands

### Enter the URL of the topic with the problem

https://angular.dev/cli/commands

**Comment by saiprasad2595** [comment] 2023-11-23 14:04
Hi @OszkarOlah How did you get that URL? Did you click on any hyperlink which navigated to that URL?

I think the right URL is [](https://angular.dev/cli)

**Comment by JoostK** [comment] 2023-11-23 14:41
Thanks for the report, closing as duplicate of #52549.

**Closed by JoostK** 2023-11-23 14:41 UTC

**Comment by OszkarOlah** [comment] 2023-11-23 14:50
Hi,

From this page:
https://angular.dev/tools/cli

[image: image.png]
