### ISSUE TITLE
ngUpgrade guide is extremely outdated

### ISSUE THREAD

**Issue by Jeremydavisvt** [angular/angular#24975] opened 2018-07-18 22:38 UTC
## I'm submitting a...

<pre><code>

[x] Documentation issue or request

</code></pre>

## Current behavior

ngUpgrade guide relies on systemJS, and seemingly completely ignores the use of angular-cli. It instructs the user to insert <script> tags that call on node_modules. If using anguluar-cli, this will never work. 
https://github.com/angular/angular-cli/issues/2896

## Expected behavior

Expected behavior I guess would be how the hell to use SystemJS or Webpack or whatever else with angular-cli properly. How does one bootstrap an existing angularJS application with Angular-cli

## Environment

<pre><code>
Angular version: 6.0.9
AngularJS version: 1.7

**Comment by trotyl** [comment] 2018-07-19 03:05
Duplicate of https://github.com/angular/angular/issues/24867

**Comment by gkalpak** [comment] 2018-07-19 09:15
Let's use #24867 to track updating the `ngUpgrade` guides for now.

**Closed** 2018-07-19 09:15 UTC
