### ISSUE TITLE
Service worker continuously reloads app

### ISSUE THREAD

**Issue by Ottunger** [angular/angular#44752] opened 2022-01-19 09:22 UTC
### Which @angular/* package(s) are the source of the bug?

service-worker

### Is this a regression?

Yes

### Description

I have an application which continuously reloads because the service worker never manages to register, as the app is trying to download an old build. there is no reason for this build to be downloaded as it is no more referenced in the ngsw.json
![network](https://user-images.githubusercontent.com/3816312/150100478-423d0223-2b55-4240-b7ba-554a2e017d28.png)
![network2](https://user-images.githubusercontent.com/3816312/150100491-503fc91d-e9e8-4257-834b-0912525e1c0f.png)

### Please provide a link to a minimal reproduction of the bug

https://app-test.anotemusic.com

### Please provide the exception or error you saw

```true
main.47ab7967795dec49.js is the most up to date version of app. Service worker fails to download main.8663078ebcc02629.js (an old version no more accessible in CDN)


main.47ab7967795dec49.js:1 ERROR Error: Uncaught (in promise): NotAllowedError: Registration failed - permission denied
    at A (polyfills.cd3aac8f98f39e08.js:1:17395)
    at A (polyfills.cd3aac8f98f39e08.js:1:16930)
    at polyfills.cd3aac8f98f39e08.js:1:18237
    at h.invokeTask (polyfills.cd3aac8f98f39e08.js:1:8085)
    at Object.onInvokeTask (main.47ab7967795dec49.js:1:2136672)
    at h.invokeTask (polyfills.cd3aac8f98f39e08.js:1:8006)
    at h.runTask (polyfills.cd3aac8f98f39e08.js:1:3158)
    at m (polyfills.cd3aac8f98f39e08.js:1:10407)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.1.3
Node: 14.16.0
Package Manager: npm 8.1.3
OS: win32 x64

Angular: 13.1.2
... animations, cdk, common, compiler, compiler-cli, core, forms
... material, platform-browser, platform-browser-dynamic, router
... service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1301.3
@angular-devkit/build-angular   13.1.3
@angular-devkit/core            13.1.3
@angular-devkit/schematics      13.1.3
@angular/cli                    13.1.3
@angular/pwa                    13.1.3
@schematics/angular             13.1.3
rxjs                            7.5.2
typescript                      4.5.4
```

### Anything else?

Maybe a clean browser does not suffer from issue, as incognito mode seems ok for now? But strangely enough, https://app-dev.anotemusic.com is currently unaffected!

**Comment by gkalpak** [comment] 2022-01-19 19:18
https://app-test.anotemusic.com works fine for me 🤷
I'm afraid there is not much we can do without an actual reproduction. (I understand that it does not work for you, probably because your browser has gotten into a specific, broken state, but that doesn't help investigate unfortunately 😞)

Also, I can't think of situation, where failing to register the SW would result in the app's reloading 🤷
You could try cleaning up your browser's state (for example, in Chrome go to `DevTools` > `Application` > `Storage` > and click on <kbd>Clean site data</kbd>) and see if the error occurs again.

I am going to close this issue (since it is not actionable in its current state), but feel free to continue the discussion below.

**Closed by gkalpak** 2022-01-19 19:18 UTC
Labels: comp: service-worker
