### ISSUE TITLE
Jasmine 4.0.0 warning: An asynchronous function called its 'done' callback more than once.

### ISSUE THREAD

**Issue by studioromeo** [angular/angular#45476] opened 2022-03-30 11:25 UTC
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

Jasmine 4.0.0 has introduced a warning when running `ng test` on tests cases wrapped in `waitForAsync`. This is not the case for tests wrapped with `fakeAsync` or unwrapped test cases.

This happens on stable (13.x.x) but I've also tried next (14.0.0-next.6)

### Please provide a link to a minimal reproduction of the bug

https://github.com/studioromeo/angular-jasmine-4-waitforasync

### Please provide the exception or error you saw

```true
DEPRECATION: An asynchronous function called its 'done' callback more than once. This is a bug in the spec, beforeAll, beforeEach, afterAll, or afterEach function in question. This will be treated as an error in a future version. See<https://jasmine.github.io/tutorials/upgrading_to_Jasmine_4.0#deprecations-due-to-calling-done-multiple-times> for more information.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 14.0.0-next.6
Node: 16.14.0
Package Manager: npm 8.3.1
OS: darwin arm64

Angular: 14.0.0-next.9
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1400.0-next.6
@angular-devkit/build-angular   14.0.0-next.6
@angular-devkit/core            14.0.0-next.6
@angular-devkit/schematics      14.0.0-next.6
@angular/cli                    14.0.0-next.6
@schematics/angular             14.0.0-next.6
rxjs                            7.5.5
typescript                      4.6.3
```

### Anything else?

Tried looking for any other issues with this but couldn't find any. Maybe using the wrong search terms or maybe the tests are written incorrectly? Advice welcome!

**Comment by JoostK** [comment] 2022-03-30 11:44
Which version of zone.js are you using? There was a fix in [0.11.5](https://github.com/angular/angular/blob/master/packages/zone.js/CHANGELOG.md#0115-2022-03-03) to address this.

**Comment by studioromeo** [comment] 2022-03-30 12:01
Hey @JoostK I've just updated the repo to 0.11.5 but unfortunately the warning remains for me, is this the case for you too?

**Comment by JoostK** [comment] 2022-03-30 17:49
Yes, indeed, this scenario is still broken.

**Comment by KrakenTyio** [comment] 2022-06-01 14:31
Hi there, i got same errors after migrating from 12 -> 13
In my luck its happend only on 2 describes

Issue happens only when in `it` was used `waitForAsync` but `beforeEach` didnt use it
so i fix it by scoping also `beforeEach` with `waitForAsync`

**Comment by coyoteecd** [comment] 2022-06-30 11:40
@JiaLiPassion With latest zone.js v0.11.6, while most of the issues in our code base have been solved by #45025, there is still one specific case I ran into:
* component uses a pipe(delay(0)).subscribe(....)
* unit test is wrapped in a waitForAsync() block
* unit test uses fixture.detectChanges() + await fixture.whenStable() to ensure the subscribe handler executes

```ts
  beforeEach(async () => {
    await TestBed.configureTestingModule({
      imports: [
         ...
      ],
      declarations: [
        MyComponent,
        ...
      ]
    }).compileComponents();
  });

  beforeEach(waitForAsync(() => {
     // create the fixture and component instance
  }));

  it('test that fails', waitForAsync(async () => {
      // setup spies
      fixture.detectChanges();
      await fixture.whenStable();

     // expects
  }));
```

This works fine on jasmine 3.9.0 before they introduced the 'done' callback check and it breaks with the "done called more than once" error on jasmine 4.2 + latest angular 13 + zone.js 0.11.6.

What I tried:
* removing `waitForAsync()` from 2nd beforeEach and/or merging them into a single beforeEach => no effect, regardless of combination
* removing `waitForAsync()` from the test block => this works, but is not something I'm keen to do since we advised all devs to use it everywhere to make sure they don't leave async tasks/failures leak into other tests
* using `fakeAsync()` for the test block => this gives "1 periodic timer(s) still in the queue" error, likely because the implementation of delay RxJs operator [involves a timer](https://github.com/ReactiveX/rxjs/blob/c45e07cef887fded09473ce64ea59f54a77e8efc/src/internal/operators/delay.ts#L63)
* using `fakeAsync()` for the test block + `tick()` after `detectChanges()` to ensure the delay is processed => this works and is likely the best workaround for us right now.

Is it possible to fix this in zone.js so that components using `delay` work properly with waitForAsync as well?

**Comment by Reboog711** [comment] 2022-06-30 18:44
I'm having the same issue on Angular 14 with some tests which used waitForAsync().  

In this case I was able to rework the tests to use a done function to solve the issue.

**Comment by whyboris** [comment] 2022-07-25 19:49
✅ confirming that this error went away when I upgraded `zone.js` from `0.11.4` to `0.11.7` 🤝 
> An asynchronous spec, beforeEach, or afterEach function called its 'done' callback more than once.

**Comment by 11joselu** [comment] 2022-07-26 08:12
If help... I can confirm that this error went away from zone.js 0.11.6 to 0.11.7


@devversion Thanks you!!

**Comment by devversion** [comment] 2022-07-26 08:13
Thank you both for testing and confirming this is fixed on your end. @JiaLiPassion Sounds like we can close this?

**Comment by JiaLiPassion** [comment] 2022-07-26 11:29
@devversion , sure, I think we can close this one.

**Closed by JiaLiPassion** 2022-07-26 11:29 UTC
Labels: comp: testing, comp: zones, P4
