### ISSUE TITLE
Change Detection Silently Fails Running Outside of Zones

### ISSUE THREAD

**Issue by connor4312** [angular/angular#12397] opened 2016-10-19 22:57 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
```

**Current behavior**
Change detections running outside of zones have no effect.

**Expected behavior**
Either the change detection should succeed or an explicit error should be thrown.

**Minimal reproduction of the problem with instructions**

Demo: http://plnkr.co/edit/wtB971qbdZivPSyTkpvj

 - Cause an event to occur outside of Zone.js
 - Attempts to effect changes resulting from that event in an Angular component
 - (note: this also happens when the change detection strategy on `OnPush`)

**What is the motivation / use case for changing the behavior?**

In general, any events that happen outside of Zones. My situation came about as a result of listening to `paused` / `play` events on a video element, which apparently Zone.js does not wrap properly or did not wrap in this situation. It could also easily happen if a first or third-party module initializes some routine when it is first imported on which events can be fired.

This would have been substantially more difficult to debug if it happened deep in some such 3rd party dependency 😛 

**Please tell us about your environment:**

Irrelevant. OSX Sierra, VS Code.

* **Angular version:** 2.0.2

* **Browser:** all
 
* **Language:** all

**Comment by DzmitryShylovich** [comment] 2016-10-19 23:02
Duplicate of https://github.com/angular/angular/issues/12143

**Comment by connor4312** [comment] 2016-10-19 23:04
I think this is more of an issue with the change detector itself. It makes sense that when something is changed outside of a zone, it isn't picked up on by default. But when requesting the change detector to run, I think it should either run or throw an error saying that it's unable to.

**Comment by DzmitryShylovich** [comment] 2016-10-19 23:07
> this.cdr.markForCheck();

doesn't run change detection

**Comment by connor4312** [comment] 2016-10-19 23:13
Ah, I see, both need to be called when running outside of Zones. It might make sense to document those on the [ChangeDetectorRef](https://angular.io/docs/js/latest/api/core/index/ChangeDetectorRef-class.html) page, the `detectChanges` method is fairly sparse. Happy to put in a PR if that's something you folks are interested in?

**Closed** 2016-10-19 23:14 UTC

**Comment by DzmitryShylovich** [comment] 2016-10-19 23:16
http://blog.thoughtram.io/angular/2016/02/22/angular-2-change-detection-explained.html

**Comment by connor4312** [comment] 2016-10-19 23:19
That's a great article! Now that I know what to look for I see that you can infer from one of the code snippets what you would use `detectChanges` for, but having it clearly laid out in `ChangeDetectorRef`'s own docs would not hurt.
