### ISSUE TITLE
Attribute selector when running with Ivy

### ISSUE THREAD

**Issue by dartzki** [angular/angular#34349] opened 2019-12-11 14:43 UTC
# 🐞 bug report

### Affected Package
ivy renderer

### Is this a regression?

Yes, the behavior changed between 8.0 (no-ivy) and 9.0 (ivy)

### Description

When the bootstrap component uses an attribute selector  (e.g. '[app-component]') instead of an element selector, the first `<div>` on the page is used to render the component.

## 🔬 Minimal Reproduction

https://github.com/dartzki/angular9-ivy-atttribute-selector

clone, npm install, ng serve
=> the content of AppComponent is rendered inside the first `<div>` instead of the second `<div>` where the attribute is set.
If Ivy is disabled in tsconfig.json, AppComponent is rendered in the second `<div>` as expected.
It seems as if attribute selectors are completely ignored by Ivy.

## 🔥 Exception or Error
the content of AppComponent is rendered inside the first `<div>` instead of the second `<div>` where the attribute is set.

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.0.0-rc.5
Node: 12.12.0
OS: linux x64

Angular: 9.0.0-rc.5
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-rc.5
@angular-devkit/build-angular     0.900.0-rc.5
@angular-devkit/build-optimizer   0.900.0-rc.5
@angular-devkit/build-webpack     0.900.0-rc.5
@angular-devkit/core              9.0.0-rc.5
@angular-devkit/schematics        9.0.0-rc.5
@ngtools/webpack                  9.0.0-rc.5
@schematics/angular               9.0.0-rc.5
@schematics/update                0.900.0-rc.5
rxjs                              6.5.3
typescript                        3.6.4
webpack                           4.41.2

</code></pre>

**Anything else relevant?**

**Comment by rodolfojnn** [comment] 2019-12-11 16:21
Yes, this is really happening. Only on DIV elements.

**Comment by kara** [comment] 2019-12-11 21:45
Looks like this could be a dupe of https://github.com/angular/angular/issues/34256 (same root cause)

**Closed** 2020-01-14 17:45 UTC
Labels: comp: core, comp: ivy, severity5: ivy-compat, state: has PR, type: bug/fix
