### ISSUE TITLE
HMR fails with IVY: Type AppComponent is part of the declarations of 2 modules: AppModule and AppModule!

### ISSUE THREAD

**Issue by LanderBeeuwsaert** [angular/angular#35265] opened 2020-02-09 14:02 UTC
# 🐞 bug report

### Affected Package
HMR + IVY

### Is this a regression?

pre-IVY, it works

### Description

Seems IVY and HMR don't play well together? However I've seen tickets of them that are closed so I suppose it should be possible.
I have on re-load after code change:

nhandled Promise rejection: Type AppComponent is part of the declarations of 2 modules: AppModule and AppModule! Please consider moving AppComponent to a higher module that imports AppModule and AppModule. You can also create a new NgModule that exports and includes AppComponent then import that NgModule in AppModule and AppModule.
Type Background is part of the declarations of 2 modules: AppModule and AppModule! Please consider moving Background to a higher module that imports AppModule and AppModule. You can also create a new NgModule that exports and includes Background then import that NgModule in AppModule and AppModule.
...

and so on (for 5 components as far as I can see)

Seems somebody already did some more in-depth research on it than me:
https://www.gitmemory.com/issue/storybookjs/storybook/8494/551763214

## 🌍  Your Environment

**Angular Version:**
ng 9.0.0
cli 9.0.1

**Comment by JoostK** [comment] 2020-02-10 20:58
Looking into this, and it's not as trivial to solve this issue. In the HMR scenario, any previously compiled components need to be reset even if they didn't change, as a change in a selector/module imports could affect other components. So the issue is not only about avoiding the error.

**Comment by LanderBeeuwsaert** [comment] 2020-02-10 21:10
Is this then a general issue with the combination of IVY and HMR? Weird that this wasn't reported before if that's the case?

**Comment by 1antares1** [comment] 2020-02-12 22:30
Same error with **Ng 9.0.1** version! :/

**Comment by sharikovvladislav** [comment] 2020-02-20 14:37
@LanderBeeuwsaert 

> Weird that this wasn't reported before if that's the case?

Nope, this happened before the 9.0.0 release. Here is my issue to the storybook: https://github.com/storybookjs/storybook/issues/8494. Storybook has HMR under the hood.

Oops. I absolutely forget to report this to angular/angular.

**Comment by sharikovvladislav** [comment] 2020-02-20 14:39
Good news: HMR works in Ivy in Ahead-of-Time (AOT) mode.

Out of scope:
Bad news for our project: AOT rebuild time is still too long for our prject.

**Comment by LanderBeeuwsaert** [comment] 2020-02-20 14:41
better late then never

**Comment by sharikovvladislav** [comment] 2020-02-20 14:48
As @JoostK said, there are some information about previously compiled modules. There was no such check in pre-Ivy.

What I tried? I also tried to use `resetCompiledComponents` to clean up theese sttructures (https://github.com/angular/angular/blob/master/packages/core/src/render3/jit/module.ts#L355) , but got no luck. There is something else. `resetCompiledComponents` is used by `TestBed`. 

How? Error message from the first post comes from verifyDeclarationIsUnique function. Here is it: https://github.com/angular/angular/blob/master/packages/core/src/render3/jit/module.ts#L253. It is part of `verifySemanticsOfNgModuleDef` function. This verification is performed on compilation of the modules: https://github.com/angular/angular/blob/master/packages/core/src/render3/jit/module.ts#L144. It is getter, so when some code access `[NG_INJ_DEF]` (`ɵinj`) property of the module type, this code is executed.

**Comment by sharikovvladislav** [comment] 2020-02-20 15:06
@pkozlowski-opensource by they way, why Angular team do not want to create something like `@angular/hmr` package and describe this in docs? People use their own solutions or something like `@angularclass/hmr` package.

**Comment by uplink42** [comment] 2020-02-28 05:30
> Good news: HMR works in Ivy in Ahead-of-Time (AOT) mode.
> 
> Out of scope:
> Bad news for our project: AOT rebuild time is still too long for our prject.

I just tried running NG serve with - - aot and it does indeed fix the issue. But I thought ivy had aot working by default in development (as per release notes: https://blog.angular.io/version-9-of-angular-now-available-project-ivy-has-arrived-23c97b63cfa3)

**Comment by 1antares1** [comment] 2020-03-02 16:14
A response from our friend: Simon Dragsbæk on StackOverFlow helped me...
Toggle on AOT in your angular.json config file, that should do it

**Here is the structure of where:**

> {
>   "projects": {
>     "x": {
>       "architect": {
>         "build": {
>           "options": {
>             "aot": true,
>           },
>           "configurations": {
>              "hmr": {
>               "aot": true
>             },
>             "local": {
>               "aot": true
>             }

**And run like this:**
`ng serve --aot=true`

In my case, since I have an additional configuration for **'hrm',** I execute this:
`ng serve --configuration hmr --aot=true`

**Comment by igor-pavlichenko** [comment] 2020-03-11 15:12
Same issue here, and AOT solution doesn't suits my case.. I'm working with plenty of legacy code (typescript mixins used) and enabling AOT breaks that code.

To be honest losing hmr in an angular project isn't a big loss since it still reloads the whole app unlike react's hot reloading, but still :\

**Comment by sharikovvladislav** [comment] 2020-03-16 12:11
> To be honest losing hmr in an angular project isn't a big loss since it still reloads the whole app component tree unlike react's hot reloading, but still :\

Looks like it is not because of Angular or React. It is because how people store data in Angular and in React. Main thing: you can think about saving storage state anyway. Looks like react have this out of the box (if you store data properly). In Angular you usually store data in "local storages". Would not be very hard if you use something based on redux idea (ngrx, akita, ngxs and stuff).

Idea is described here in readme: https://github.com/PatrickJS/angular-hmr. More discussions here: https://github.com/PatrickJS/angular-hmr/pull/66.

About React: if you do stuff wrrong in React it would be pain to save storages between reloads by hmr

**Comment by sharikovvladislav** [comment] 2020-03-17 05:07
> Same issue here, and AOT solution doesn't suits my case.. I'm working with plenty of legacy code (typescript mixins used) and enabling AOT breaks that code.

What issues do you have with AOT? 

We have hybrid application with a lot of legacy code too. We have about 500k TypeScript and 350k JavaScript. Everything works fine.

**Comment by igor-pavlichenko** [comment] 2020-03-17 09:46
> What issues do you have with AOT?
It's weird.. the build doesn't break, no errors or warnings neither on build nor in the browser's console, but the components based on **mixins that use angular's lifecycle hooks** simply appear empty like whitespace

**Comment by JoostK** [comment] 2020-06-07 13:14
Hi folks, a quick update: HMR has not worked with Ivy because the compilation result is stored on a static property of the component's class, therefore allowing only a single compiled output at the same time. With HMR this becomes a problem, as parts of the NgModule graph can be replaced at any time which would have to invalidate earlier compilation results. In View Engine this was not an issue, as all compiled output was captured in separate ngfactory data structures which could coexist at any time.

The idea in #37474 is to introduce new API to signal that any prior compilation should be considered outdated, triggering recompilation where necessary. The current proposal adds `resetCompiledComponents` that needs to be called upon HMR, but this is definitely subject to bike-shedding or further changes. Unfortunately I can't give an ETA at the moment, I don't expect it to land very soon.

**Comment by hiepxanh** [comment] 2020-06-07 15:04
Good to know that, I understand that will be hard, but there is an PR will make us feeling more happy, you give all of us some hope, that is the most important

**Comment by IAMtheIAM** [comment] 2020-08-14 17:51
I would like to know how the Angular team decided to release a new compiler that doesn't work with webpack's HMR? Literally everybody who uses Angular, React Vue, or any modern front end framework uses HMR. To build a new compiler that breaks the most essential feature of UI developer productivity doesn't make any sense to me.

How did this not get built into IVY from the start? I've lost countless dozens and dozens of hours due to waiting for 60-90 second rebuilds constantly over the past several months. Why Angular Team?? Does the productivity of your users not sit as a top priority in the list of features to maintain support of?

I realize Angular is a complex framework and there are many moving parts. However, I think this IVY compiler shouldn't have been released without HMR support baked in from the beginning. Am I missing something?

**Comment by uplink42** [comment] 2020-08-14 18:03
HMR works for me with aot on since v9. Currently at version 10 and it's still working as usual. It doesn't persist state between reloads (never did, dunno why) but the reload is significantly faster than a full page refresh.

However I do agree that it's puzzling how such a high productivity feature isn't baked on the CLI by default.

**Comment by Waterstraal** [comment] 2020-08-14 18:31
> I would like to know how the Angular team decided to release a new compiler that doesn't work with webpack's HMR? Literally everybody who uses Angular, React Vue, or any modern front end framework uses HMR. To build a new compiler that breaks the most essential feature of UI developer productivity doesn't make any sense to me.
> 
> How did this not get built into IVY from the start? I've lost countless dozens and dozens of hours due to waiting for 60-90 second rebuilds constantly over the past several months. Why Angular Team?? Does the productivity of your users not sit as a top priority in the list of features to maintain support of?
> 
> I realize Angular is a complex framework and there are many moving parts. However, I think this IVY compiler shouldn't have been released without HMR support baked in from the beginning. Am I missing something?

If you have 60-90 second rebuild times, you might have a different issue. HMR is not going to solve that as it will only eliminate the need for a full page refresh. 

I agree on the fact that state-preserving hot reloading should be a part of Angular with official support, much like [react-refresh](https://github.com/facebook/react/tree/master/packages/react-refresh) or [vue-loader](https://github.com/vuejs/vue-loader) provide. Could someone from the Angular or Angular CLI team chip in on this. Will this ever be on the roadmap? I think a lot of developers can benefit from this in terms of productivity.

**Comment by LanderBeeuwsaert** [comment] 2020-08-15 08:34
I would also think that from a developer-experience standpoint HMR is an important functionality, which, suppose it would work seamlessly; certainly when preserving state; would add a lot of benefit for developers.

I would love to know the point of view of the angular team about this:
- do they agree it's important but are other items more priority for now and it will be added to the roadmap later;
- or is it deemed not important; maybe there is a workaround or we have like a bad project setup that it would only be useful in our workflow?

**Comment by sp90** [comment] 2020-08-26 08:10
@mhevery father of angular, can you come to the rescue of your child before this issue obliterates the community around it.

Alternatively some core team members: @petebacondarwin, @IgorMinar, @kara and more please can we get an ETA on this crucial part of the development with angular, and maybe fast track it? 🚀

**Comment by mhevery** [comment] 2020-08-26 19:10
[`verifySemanticsOfNgModuleDef`](https://github.com/angular/angular/blob/d1ea1f4c7f3358b730b0d94e65b00bc28cae279c/packages/core/src/render3/jit/module.ts#L170) was put in try to narrow the kinds of errors which are produced in AoT and JIT. As you have discovered the HMR does not play well with these checks as HMR by its very nature over-writes the class definition so that you end up with multiple versions of the same class. 

Has anyone tried to add `<script>window.ngDevMode = false</script>` to the index page to see if that makes the checks go away and HMR should work? I don't know if the runtime will have issues (in theory there are two versions of the same class so depending on the change which you are HMR it may or may not work). But I suspect that in many cases this should work.

We are aware that we would like to have a better HMR support, but with all of our priorities this one has not gotten on the list yet.

**Comment by Benno007** [comment] 2020-08-27 01:34
> Has anyone tried to add `<script>window.ngDevMode = false</script>` to the index page to see if that makes the checks go away and HMR should work? I don't know if the runtime will have issues (in theory there are two versions of the same class so depending on the change which you are HMR it may or may not work). But I suspect that in many cases this should work.

I just added this to our index.html and it has made a difference. I can't find any documentation about what specifically this variable does? 

 We no longer see the in 2 module errors whenever we modify a component (it was happening anytime we modified a component). We also used to lose CSS, and the page would end up looking like this:
<img width="1163" alt="Screen Shot 2020-08-27 at 11 32 40 am" src="https://user-images.githubusercontent.com/313195/91373175-06adac80-e859-11ea-94aa-128e3411b328.png">

**Comment by mtuzinskiy** [comment] 2020-08-27 13:02
> > Good news: HMR works in Ivy in Ahead-of-Time (AOT) mode.
> > Out of scope:
> > Bad news for our project: AOT rebuild time is still too long for our prject.
> 
> I just tried running NG serve with - - aot and it does indeed fix the issue. But I thought ivy had aot working by default in development (as per release notes: https://blog.angular.io/version-9-of-angular-now-available-project-ivy-has-arrived-23c97b63cfa3)

I second this question. Shouldn't AOT be enabled by default now?..

**Comment by LanderBeeuwsaert** [comment] 2020-08-27 17:28
@mtuzinskiy during development we still use JIT as it still compiles faster.

**Comment by mtuzinskiy** [comment] 2020-08-27 18:35
@LanderBeeuwsaert  Why then it's stated in the release notes?... I was waiting for this as one of the main features of Ivy and there is _nowhere_ stated that it's actually JIT again.  It's misleading, to put it mildly... :worried:

**Comment by LanderBeeuwsaert** [comment] 2020-08-27 18:38
@mtuzinskiy It would not be my interpretation that it's misleading. By default I think it's AoT and you certainly can use it. However for us; due to the size of our application JIT is still better.

**Comment by mtuzinskiy** [comment] 2020-08-27 18:41
@LanderBeeuwsaert   The thing is that on my project we don't use JIT, for sure. We use Ivy defaults.  And I can clearly see the difference in HMR when adding the --aot flag.  I'm guessing that same goes for @uplink42 ,  as they asked this question too

**Comment by jessicajaniuk** [comment] 2022-03-08 00:27
Closing this as we've made a number of improvements over the last several years that we think has addressed this. However, if this problem is still present, please open a new issue so we can track it there.

**Closed by jessicajaniuk** 2022-03-08 00:27 UTC
Labels: type: bug/fix, freq2: medium, engine: ivy, state: has PR, comp: compiler, state: confirmed, triage #1, design complexity: major, P3

**Comment by sp90** [comment] 2022-03-11 10:34
@jessicajaniuk it has been fixed after ng11 and are working as expected 👍
