### ISSUE TITLE
New directive ngRepeat.

### ISSUE THREAD

**Issue by fudom** [angular/angular#53881] opened 2024-01-11 16:25 UTC
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

Sometimes it would be great to quickly repeat elements without writing too much code or importing own directive for that solution. For example for prototyping, layout or whatever. It's a proposal for the build-in directive `ngRepeat`. It's like ngFor but only requires an integer to repeat the element, similar to String.prototype.repeat(n).

### Proposed solution

```html
<div *ngRepeat="3">Hello</div>
```

Output:

```html
<div>Hello</div>
<div>Hello</div>
<div>Hello</div>
```

### Alternatives considered

The existing `ngFor` could handle a number only as overload like:

```html
<div *ngFor="3">Hello</div>
```

Output:

```html
<div>Hello</div>
<div>Hello</div>
<div>Hello</div>
```

The idea is to achieve this quickly without having to write own code. For example, test how HTML handles tons of elements (scrolling, responsive, etc) whichout having real data. But this is just one use case.

**Comment by JoostK** [comment] 2024-01-11 18:09
Closing as duplicate of #38886, its discussion is still the case today. You can include a library for such things if desired.

**Closed by JoostK** 2024-01-11 18:09 UTC

**Comment by Celtian** [comment] 2024-01-11 20:34
I made this library https://www.npmjs.com/package/ngx-repeat ... But would like to see this in angular core...

**Comment by petebacondarwin** [comment] 2024-01-16 09:10
As @JoostK says, the discussion in #38886 is just as relevant today. It is not common enough to deserve being in the core framework, and it is trivial to create your own directive for this.
