### ISSUE TITLE
Support relative URLs for HTTPClient on platform server

### ISSUE THREAD

**Issue by vikerman** [angular/angular#19224] opened 2017-09-15 21:14 UTC
Currently the server HTTPClient only accepts absolute URLs. It should accept relative URLs similar to the client and the server should use the current URL to figure out the absolute path.

This becomes more important as we use the URL as key to the HTTP cache that is transferred from the server to the client.

**Comment by denisyilmaz** [comment] 2017-10-24 07:30
In another issue it was mentioned that this will be fixed in HttpClient module.

Will the fix be part of the next Angular (^5.0.0) release?

**Comment by vikerman** [comment] 2017-10-31 19:02
This didn't make it into 5.0. Should be part of very next release - 5.0.1

**Comment by cyrilletuzi** [comment] 2017-11-11 08:55
Any news on this ?

It's now two major versions with platform-server, and more than 2 years the Universal project began, and it's still not usable by common folks because of lack of support in the CLI and blocking issues like this one (which requires difficult workarounds).

It should be a priority.

**Comment by cyrilletuzi** [comment] 2018-03-13 17:33
I'm worried about the fact v6 rc has been announced as close and this issue is still open.

If it misses v6, it would mean a fourth major release with very painful server-side rendering.

@IgorMinar Could this be added to the v6 milestone ?

**Comment by danwulff** [comment] 2018-09-21 00:28
@CaerusKaru Any possibility of this getting revived?

**Comment by CaerusKaru** [comment] 2020-05-22 00:10
FYI if you use one of the NgUniversal engines (e.g. express, hapi), this should now work with Angular v10 RC. Please test it out and let us know!

**Comment by alan-agius4** [comment] 2020-05-22 08:30
Hi all, as per @CaerusKaru comment, this should have been addressed in Angular v10 RC-0 via the following PR https://github.com/angular/angular/pull/37071

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.

**Closed by alan-agius4** 2020-05-22 08:30 UTC
Labels: comp: server, freq4: critical, severity3: broken, type: bug/fix
