### ISSUE TITLE
isString implementation is faulty

### ISSUE THREAD

**Issue by anilanar** [angular/angular#7709] opened 2016-03-22 01:00 UTC
* **I'm submitting a ... **
[x] bug report
[ ] feature request
[ ] support request

* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
```
import { isString } from 'angular2/src/facade/lang';
isString(new String('str')); // returns false
```

This implementation breaks many things in angular application.
For example using `lowercase` pipe with `new String()` throws an error because `isString` returns false.

Reproduce: http://plnkr.co/edit/nT5hAiEO18mmKYqRXTZd

* **What is the expected behavior?**
`isString(new String('str'))` should return true.

* **What is the motivation / use case for changing the behavior?**
It's an important bug.

**Comment by matthieubulte** [comment] 2016-03-22 08:16
It seems that the implementation is the same as in angular 1, namely:
```javascript
function isString(value) {
    return typeof value === 'string';
}
```

it would be pretty easy to fix it just by checking if the value is an instance of `String` as follow:
```javascript
function isString(value) {
    return typeof value === 'string' || value instanceof String;
}
```

now I won't create a PR before someone confirms that the behaviour you describe is the intended behaviour.

**Comment by robwormald** [comment] 2016-03-27 23:24
We'd probably accept a PR for this, but in what use case are you actually creating a `new String()` ?

**Comment by gdi2290** [comment] 2016-03-28 00:29
you're not meant to rely on or use `facade`

**Comment by robwormald** [comment] 2016-03-28 00:30
also true ^

**Comment by anilanar** [comment] 2016-03-28 03:08
I don't have a use case, just for the sake of completeness. Considering differences between primitive type `string` and object type `String`, I presume someone might be interested in putting properties into a `String` instance, or modifying its prototype etc.

**Comment by wesleycho** [comment] 2016-06-01 13:32
Checking whether it is an instance of the String class has perf implications, virtually all JS utility libraries check in this manner - I would vote against that modification as a result.

**Comment by anilanar** [comment] 2016-06-01 13:54
@wesleycho 

```
lodash: _.isString(new String()) // true
101   :   isString(new String()) // true
jquery: $.type(new String('abc')) === $.type('abc') === 'string'
```

**Comment by wesleycho** [comment] 2016-06-01 14:02
Not clue what 101 or is are, but I guess lodash must have changed the implementation at some point. I stand corrected.

**Comment by mhevery** [comment] 2016-06-01 22:48
Sorry, this is not a public API and we don't use `new String` only `string` so it is not an issue. 

Closing as working as intended

**Closed by mhevery** 2016-06-01 22:48 UTC

**Comment by anilanar** [comment] 2016-06-01 23:13
You don't use new String, but if Angular2 users use it with pipes (filters in Angular1), then this check fails. Cheers.

**Comment by mburger81** [comment] 2016-11-14 13:22
Hi @anilanar, isString was removed with RC.6 because it is not public. Are there other libraries we can use for isString, isBlank, is Array and so on?
