### ISSUE TITLE
Angular.io website blocked by CORS

### ISSUE THREAD

**Issue by Mathieu-Coupe** [angular/angular#46266] opened 2022-06-06 07:34 UTC
### Description

Some parts of the Angular.io website is not accessible with Firefox (version 101.0)

The requests to load content are blocked by CORS (strict-origin-when-cross-origin)

### What is the affected URL?

https://angular.io/guide/forms-overview

### Please provide the steps to reproduce the issue

Open the affected url

### Please provide a screenshot if possible

![image](https://user-images.githubusercontent.com/1534517/172116469-aaad3c37-f427-4f37-8876-c1668c3befd2.png)

**Comment by gkalpak** [comment] 2022-06-06 19:54
Thx for reporting this, @Mathieu-Coupe!

However, I cannot reproduce the issue. I can see the content fine using Firefox v101 (on Windows).
Also, the requests that show as blocked are not cross-origin requests, so I don't see how CORS could affect them.

Could it be that something else (for example, one of your Firefox add-ons) interferes with the website/requests?

**Comment by jessicajaniuk** [comment] 2022-06-06 23:08
I was also not able to reproduce this on Firefox v101 on Mac. I'm going to close this as not reproducible.

**Closed by jessicajaniuk** 2022-06-06 23:08 UTC
Labels: needs reproduction, comp: docs-infra

**Comment by Mathieu-Coupe** [comment] 2022-06-07 06:52
> Could it be that something else (for example, one of your Firefox add-ons) interferes with the website/requests?

You are right, I tested disabling the add-ons and it was Ghostery that were blocking theses requests.
Sorry the trouble !
