### ISSUE TITLE
link not redirecting correctly in tutorial section

### ISSUE THREAD

**Issue by Vikas-AppliedSystems** [angular/angular#52830] opened 2023-11-12 04:57 UTC
### Describe the problem that you experienced

link to type inference in angular tutorial section is not redirecting correctly.

### Enter the URL of the topic with the problem

https://angular.dev/tutorials/learn-angular/updating-the-component-class

### Describe the actions that led you to experience the problem

was just going through the tutorial.

### Describe what you want to experience that would fix the problem

redirect to the correct url.

### Add a screenshot if that helps illustrate the problem

![Screenshot 2023-11-12 102519](https://github.com/angular/angular/assets/145420896/624eb4b4-4b77-43b6-8c36-02beac04a3ad)
![Screenshot 2023-11-12 102703](https://github.com/angular/angular/assets/145420896/27a88f9f-42f8-4df7-8a8d-9f0562a5f39b)

**Comment by sasidharansd** [comment] 2023-11-12 05:07
Duplicate of https://github.com/angular/angular/issues/52553 , pr has been merged https://github.com/angular/angular/pull/52714

**Comment by JoostK** [comment] 2023-11-12 06:25
Thanks for the report! This has indeed already been addressed but awaiting deployment.

**Closed** 2023-11-12 06:26 UTC
