### ISSUE TITLE
Angular universal  not working with service workers 

### ISSUE THREAD

**Issue by walid-hajhussien** [angular/angular#37131] opened 2020-05-15 08:58 UTC
# 🐞 bug report

### Description

Angular Universal  (SSR) not working with the service workers, I didn't get any error but the  index.html page not renders in the server as before :

1) before adding the service workers :
https://drive.google.com/open?id=1V7PFlBLD995_HlxLYBrO9IuZ-K0qW33Q

2) after adding the service workers:
https://drive.google.com/open?id=160-k6yVyMNwTkvDeDu4-BlmZkN6k9jf6

## 🔬 Minimal Reproduction
GitHub repository: https://github.com/walid-hajhussien/Recipe-books
Branch: master

## 🌍  Your Environment
`"@angular/animations": "~9.0.3",
    "@angular/common": "~9.0.3",
    "@angular/compiler": "~9.0.3",
    "@angular/core": "~9.0.3",
    "@angular/forms": "~9.0.3",
    "@angular/platform-browser": "~9.0.3",
    "@angular/platform-browser-dynamic": "~9.0.3",
    "@angular/platform-server": "~9.0.3",
    "@angular/router": "~9.0.3",
    "@angular/service-worker": "~9.0.3",
    "@ngrx/effects": "^9.1.0",
    "@ngrx/store": "^9.1.0",
    "@ngrx/store-devtools": "^9.1.0",
    "@nguniversal/express-engine": "^9.0.1",
    "angular-user-idle": "^2.2.2",
    "bootstrap": "^3.4.1",
    "express": "^4.15.2",
    "ng-connection-service": "^1.0.4",
    "rxjs": "~6.5.4",
    "tslib": "^1.10.0",
    "zone.js": "~0.10.2"`

**Anything else relevant?**
the issue happens when you tried to combine both Angular Universal  (SSR) & service workers

**Comment by gkalpak** [comment] 2020-05-17 20:49
@walid-hajhussien, can you please provide instructions on how to reproduce the issues you are seeing.

If I had to guess, I would say that what happens is this:
- Before the SW has been installed/activated, the `index.html` file is served from the server, where it is rendered before being sent to the client.
- Once the SW has been installed and activated, `index.html` is served from the SW (so no SSR, since the request never hits the server).

This is generally working as intended.  Generally, the idea of prerendering is that it kicks in on the first load (to speed up the first rendering) and on subsequent loads the SW takes over and speeds up the rendering by serving the HTML and other resources from the local cache (and only fetching the necessary data). Prerendering is also useful for other context (such as SEO, link previews, etc.) where the clients are not using ServiceWorkers.

**Comment by walid-hajhussien** [comment] 2020-05-18 15:47
@gkalpak, once I set up the SW on my project the SSR no longer works as you mention above on the second point, so that's mean SW & SSR can't working together.

what did I note that the server still rendered the `index.html` but no longer send it to the client once the SW is activated.

what I would say that the server should render and serve the `index.html `once you hit the server in the first time then the SW should take over and serving the HTML and other resources from the local cache

**Comment by gkalpak** [comment] 2020-05-18 15:54
Sorry, I am not sure what you are saying, @walid-hajhussien 😅
Can you provide detailed instructions on how to reproduce the issue (e.g. commands to run to set up, build and run a project or a repo we can check out and build and also what actions to perform to see the issue including what is the expected and what is the actual behavior)?

**Comment by walid-hajhussien** [comment] 2020-05-21 13:44
@gkalpak, sorry for confusing you, please check the below instructions:

**GitHub repository**: https://github.com/walid-hajhussien/Recipe-books

**Step 1 (activate the  SSR ) :**
-  checkout branch **ngUniversalExpress**
-  npm run build:ssr
-  npm start 
-  Right-click the page and look at the menu that appears. From that menu, click **View page 
    source**, you will get the below result :
    https://drive.google.com/open?id=1V7PFlBLD995_HlxLYBrO9IuZ-K0qW33Q

**Step 2 (activate the SW ):**
- in this branch(master), we activate the SW after we activated the SSR in the ngUniversalExpress Branch
-  checkout branch master 
-  npm run build:ssr
-  npm start 
- Right-click the page and look at the menu that appears. From that menu, click **View page 
    source**, you will get the below result :
    https://drive.google.com/open?id=160-k6yVyMNwTkvDeDu4-BlmZkN6k9jf6

** it seems that SSR no longer work once we activate the SW, that will be going to affect the startup performance of the application & Search Engine Optimization

Thanks for your support

**Comment by gkalpak** [comment] 2020-05-26 19:53
Basically, it happens what I explained in https://github.com/angular/angular/issues/37131#issuecomment-629858597. Before the SW is registered, SSR speeds up the first load. Once the SW has been activated, it takes over a speeds up the page loading by serving the necessary resources from the local cache. This is working as intended.

Also note that the SW will not affect things like SEO and link preview generation, because the SW is not in effect in these contexts.

##
Closing the issue, since everything works as intended, but feel free to comment below if you need further explanation or info.

**Closed by gkalpak** 2020-05-26 19:53 UTC
Labels: comp: server, comp: service-worker, triage #1
