### ISSUE TITLE
Matrix parameters are not inherited when paths contain slashes

### ISSUE THREAD

**Issue by ChrisMondok** [angular/angular#25140] opened 2018-07-25 21:54 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

When routes are defined that contain slashes, matrix parameters added to any part of the route other than the final part are not available in the ActivatedRoute, regardless of `paramsInheritanceStrategy`. That is, given the route "foo/bar", navigating to "foo;message=hello/bar", the ActivatedRoute for the component at "foo/bar" has no matrix parameters.

If the routes are instead configured as a route with "foo" and a child route called "bar", these parameters are then available.

## Expected behavior

Paths defined with slashes in them behave in the same way as paths added as children.

## Minimal reproduction of the problem with instructions

```typescript
import {Component} from '@angular/core';
import {ComponentFixture, fakeAsync, flush, TestBed} from '@angular/core/testing';
import {By} from '@angular/platform-browser';
import {ActivatedRoute, Router} from '@angular/router';
import {RouterTestingModule} from '@angular/router/testing';

describe('url param test with router', () => {
  let fixture: ComponentFixture<OutletComponent>;

  beforeEach(() => {
    TestBed.configureTestingModule({
      declarations: [OutletComponent, TestComponent],
      imports: [
        RouterTestingModule.withRoutes([
          {path: 'test', component: TestComponent, pathMatch: 'full'},
          {path: 'test/child', component: TestComponent, pathMatch: 'full'}
          // The test passes if the above routes are replaced with the below.{
          // {
          //   path: 'test',
          //   children: [{
          //     path: 'child',
          //     component: TestComponent,
          //   }]
          // },
        ]),
      ],
    });

    fixture = TestBed.createComponent(OutletComponent);
    fixture.detectChanges();
  });

  it('should inherit parameters', fakeAsync(() => {
       TestBed.get(Router).navigateByUrl('test;message=hello/child');
       flush();
       const testComponent =
           fixture.debugElement.query(By.directive(TestComponent));
       expect(testComponent.componentInstance.message).toBe('hello');
     }));
});

@Component({
  template: '<router-outlet></router-outlet>',
})
class OutletComponent {
}

@Component({
  selector: 'test-component',
  template: 'Parent test component',
})
class TestComponent {
  readonly message: string;
  constructor(activatedRoute: ActivatedRoute) {
    this.message = activatedRoute.snapshot.params.message;
  }
}
```

## What is the motivation / use case for changing the behavior?

To provide consistency when passing parameters to routes.

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [x] Chrome (desktop) version 67.0.3396.99
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by jasonaden** [comment] 2018-11-20 23:14
Thanks for the bug. I'm not sure this is necessarily a bug. I think it would take quite a bit more discovery to determine if this is really a bug, or if it's something that needs to be addressed with a custom `UrlSerializer`. Also, the issue needs a running reproduction.

For these reasons, I'll close this issue. But if you want to create a new issue detailing why this makes sense, please do so.

One of the reasons I think it might not be a bug is the fact that slashes are used is simply part of the `UrlSerializer` implementation. Other implementations could use another symbol completely.

**Closed by jasonaden** 2018-11-20 23:14 UTC
Labels: comp: router

**Comment by ukrukarg** [comment] 2018-11-21 14:57
I do believe it's a bug. In the unit test above, I do expect that when I go to `test;message=hello/child` I should know there is a param called `message` with value `hello`. That's why I specified `paramsInheritanceStrategy = 'always'`. The fact that it's not available is surprising, 

It also is inconsistent with documentation: 
paramsInheritanceStrategy defines how the router merges params, data and resolved data from parent to child routes. Available options are:
- 'emptyOnly', the default, only inherits parent params for path-less or component-less routes.
- 'always', enables unconditional inheritance of parent params.

**Comment by ukrukarg** [comment] 2018-11-21 14:58
Also, what do you mean by running reproduction? Is the unit test above not enough?

**Comment by jasonaden** [comment] 2019-02-05 22:35
The path for the route is `test/child`. If there's matrix parameters inserted after `test` (e.g. `test;message=hello/child), they don't logically belong to any route. My first reaction would be to say this should throw an error as it can't match a route. However, matrix params are optional so the fact that we seem to just parse them out and ignore them in terms of URL matching makes sense.

If we were to look at this with path params, it seems like it would make more sense. A config like `test/child/:message` should never work if you pass a URL such as `test/hello/child`. It would simply error as it can't find a match.

Also, I can see a world where this could make for very confusing behavior in an application. Let's say an app configured `test/message` to render `MessageComponent` and supported `test;message=hello/child` such that the `message` param made it to the `MessageComponent`. Later, the same application changes the configuration to support more URLs under `test`:

```
path: 'test', component: TestDashboard, children: [
  {path: 'child', component: MessageComponent},  
  {path: 'users', component: UsersComponent}
]
```

Now if the `TestDashboard` looks for a `message` matrix param, it's going to get it from all the bookmarked URLs that went to `test;message=hello/child` prior to the config change (when this might not actually be the intended behavior).

For those reasons, I think the matrix params need to match against the entire URL segment that's been configured.
