### ISSUE TITLE
angular2-polyfills.js: Uncaught TypeError: Cannot read property 'split' of undefined in 

### ISSUE THREAD

**Issue by tmundt** [angular/angular#5999] opened 2015-12-18 09:42 UTC
I am working through the Angular2 tutorial at https://angular.io/docs/ts/latest/quickstart.html and I am getting this error after starting the example with "npm start"

       angular2-polyfills.js:143 Uncaught TypeError: Cannot read property 'split' of undefined

The console shows no error. What is that?

**Comment by pkozlowski-opensource** [comment] 2015-12-18 10:35
What is a browser that you are using?

**Comment by tmundt** [comment] 2015-12-18 11:10
Chrome newest version.
Am 18.12.2015 11:36 schrieb "Pawel Kozlowski" <notifications@github.com>:

**Comment by pkozlowski-opensource** [comment] 2015-12-18 11:19
Thnx for the info @tmundt . Could you please try to reproduce the problem in plunker (or a similar tool)? Here is a plunker I've forked from the quick start page: http://plnkr.co/edit/6MQ5sv6gR7nrhajiMgPU?p=preview

It works perfectly fine in Chrome / FFox, so it would be interesting to compare your setup with the one in the plunker I've linked.

**Comment by ahitchen** [comment] 2015-12-18 16:05
Hello, I am also having this problem using visual studio 2015 update 1. I don't know if this is proper form, but I have this stackoverflow question where I list a bunch of my file configurations.

http://stackoverflow.com/questions/34323219/angular-2-systemjs-import

It feels like visual studio and this angular 2 setup are trying to do some of the same things when it comes to the typescript. Are there any resources that you know of that are specifically for getting angular 2.0.0-beta.0 to work in visual studio? I am trying to update from alpha-45, which used to workreally well for me. 

If I change the script imports from local files to the hosted ones in your plunker, I still get errors. I see it in chrome 47 and edge. In firefox, I get the require error as elsewhere, but instead of the
    Cannot read property 'split' of undefined

I get:
    TypeError: p is undefined system.src... : 1456:6

Thank you! I hope I was clear, if there is anything else you need to know, just let me know.

**Comment by pkozlowski-opensource** [comment] 2015-12-18 16:23
@ahitchen VisualStudio or not, it would help us to have a reproduction scenario that we can run in a browser - this is why I've asked for a plunk. We don't have access to your environment so figuring out the root of the pb is not trivial.

Could you please try to reproduce it in a plunker? You can modify the one I've linked.

I _presume_ that what is going on here is that there is some HTTP request trigged for a JS file that doesn't exist and your server responds with HTML (error page or index.html configured for HTML5 routing).

Please try to open your dev tools network tab and check if there is no such request being triggered (I mean, a request for a JS file that results in a HTML response from a server)

**Comment by gdi2290** [comment] 2015-12-18 17:08
could you include `es6-shim` before the polyfills
```html
<script src="node_modules/es6-shim/es6-shim.js"></script>
<script src="node_modules/angular2/bundles/angular2-polyfills.js"></script>
```

**Comment by ahitchen** [comment] 2015-12-18 17:10
![network](https://cloud.githubusercontent.com/assets/4141827/11901965/3022faac-a574-11e5-80bc-0e0a203d41ff.JPG)
this plunker seems to get the errors I'm seeing:
I tried to reproduce the quickstart: https://angular.io/docs/ts/latest/quickstart.html

http://plnkr.co/edit/8INv4O4gwWQUIrn1Pry0?p=preview

**Comment by ahitchen** [comment] 2015-12-18 17:33
I think it might have been caused by a build error when I switched between commonJS and System.
System says it cannot find the angular modules, but it still builds. That's annoying, but having it work is the top priority. I made sure to clean my solution and I no longer get the require and Cannot read property 'split' of undefined error. Instead, I get: 
```
angular2-polyfills.js:138 Error: router_1.RouteConfig is not a function(…)
run @ angular2-polyfills.js:138
zoneBoundFn @ angular2-polyfills.js:111
lib$es6$promise$$internal$$tryCatch @ angular2-polyfills.js:1511
lib$es6$promise$$internal$$invokeCallback @ angular2-polyfills.js:1523
lib$es6$promise$$internal$$publish @ angular2-polyfills.js:1494
lib$es6$promise$$internal$$publishRejection @ angular2-polyfills.js:1444
(anonymous function) @ angular2-polyfills.js:243
run @ angular2-polyfills.js:138
zoneBoundFn @ angular2-polyfills.js:111
lib$es6$promise$asap$$flush @ angular2-polyfills.js:1305
```

which I am hoping is an actual error with my RouteConfig?

**Comment by gdi2290** [comment] 2015-12-18 17:35
@ahitchen do you mind sharing your code where you use RouteConfig

**Comment by ahitchen** [comment] 2015-12-18 17:40
```
@RouteConfig([
	{ path: '/', component: Gallery, name: 'Gallery' },
	{ path: '/search', component: SearchComponent, name: 'Search' },
	{ path: '/login', component: LoginComponent, name: 'Login' },
	{ path: '/account', component: AccountComponent, name: 'Account' },
	{ path: '/ForgotPassword', component: ForgotPasswordComponent, name: 'ForgotPassword' },
	{ path: '/ForgotPassword/ResetPassword', component: ResetPasswordComponent, name: 'ResetPassword' },
	{ path: '/media/:id', component: MediaComponent, name: 'Media' },
	{ path: '/user/:id', component: UserComponent, name: 'User' },
	{ path: '/team/:id', component: TeamComponent, name: 'Team' },
	{ path: '/notifications', component: NotificationComponent, name: 'Notifications' },
	{ path: '/register', component: Register, name: 'Register' },
	{ path: '/upload', component: UploadComponent, name: 'Upload' },
	{ path: '/myteams', component: MyTeamsComponent, name: 'MyTeams'}
])
```
here you go (I need to update the register component name)

**Comment by gdi2290** [comment] 2015-12-18 17:45
how are you importing it

**Comment by ahitchen** [comment] 2015-12-18 17:51
```
import {ROUTER_DIRECTIVES, RouteConfig, Router, ROUTER_PROVIDERS, Location, LocationStrategy, HashLocationStrategy} from 'angular2/router';

**Comment by nousacademy** [comment] 2015-12-21 19:47
yep demo doesnt work, I get this error 
![screen shot 2015-12-21 at 2 50 04 pm](https://cloud.githubusercontent.com/assets/7450944/11939671/9938eb44-a7f1-11e5-9a90-d2350df1510a.png)

![screen shot 2015-12-21 at 2 50 49 pm](https://cloud.githubusercontent.com/assets/7450944/11939680/b206c222-a7f1-11e5-9046-14dd5bb1e769.png)
The only thing that shows is "Loading..."

**Comment by gupei515** [comment] 2015-12-24 17:29
I got the same error with the live example.

**Comment by gintsgints** [comment] 2015-12-25 20:37
This function fn.apply got called lot of times. But when first it get's argument on applyTo, it fails. When I power up debugger on that, I get applyTo value equal to:
```
<script async="" src="http://localhost:3000/app/app.component.js"></script>
```

**Comment by gintsgints** [comment] 2015-12-26 10:29
And when you add 
```
<script src="node_modules/es6-shim/es6-shim.js"</script>
```

to your index, you get kind of same error in code part:
```
function readMemberExpression(p, value) {
  var pParts = p.split('.');
  while (pParts.length)
    value = value[pParts.shift()];
  return value;
}
```
because p was not defined.

**Comment by gintsgints** [comment] 2015-12-26 10:33
Could it be it try to load app.component.js and it's contains only:
```
//# sourceMappingURL=app.component.js.map
```

**Comment by pkozlowski-opensource** [comment] 2015-12-26 12:43
Guys, could someone reproduce this problem in plunker? There are many reports of the problem but the only reproduce I've seen so far is http://plnkr.co/edit/8INv4O4gwWQUIrn1Pry0?p=preview but this one is really messed up (JS files transpiled to CJS etc.)

Please, if you see this problem on your side just put together a plunker that shows the exact error. Otherwise it is not actionable really....

**Comment by gintsgints** [comment] 2015-12-28 19:25
Coming trought example today. I got it working. :)

Only change in source I could found which breake my code was:

```
    "target": "ES5",
```

(With experiments I did set it to ES6.)

**Comment by pkozlowski-opensource** [comment] 2015-12-28 19:34
@gintsgints thnx for reporting back! Glad that you've got it working.

I'm going to close this issue for now since we don't have a single reproduce scenario that we could use to actually figure out what is going on. I would be more than happy to re-open / investigate when such reproduce scenario surfaces.

**Closed by pkozlowski-opensource** 2015-12-28 19:34 UTC

**Comment by matthewharwood** [comment] 2015-12-30 17:10
@pkozlowski-opensource I also had the same problem as I forgot to export the class for app.component.

```
/**
 * Created by mharwood on 12/30/15.
 */
import {Component} from 'angular2/core';

@Component({
  selector: 'my-app',
  template: '<h1>My First Angular 2 App</h1>'
})
export class AppComponent { }
```
I just glanced over that small step.

**Comment by samimw** [comment] 2016-01-05 17:08
@pkozlowski-opensource I did 2 things in .html file to fix the problem on my local machine.

1. Include typescript.js 

```javascript
    <script src="node_modules/angular2/bundles/angular2-polyfills.js"></script>
    <script src="node_modules/systemjs/dist/system.src.js"></script>
    <script src="node_modules/typescript/lib/typescript.js"></script>
    <script src="node_modules/rxjs/bundles/Rx.js"></script>
    <script src="node_modules/angular2/bundles/angular2.dev.js"></script>
```

2. instead of script in the tutorial I added the one from plunker - I think to replace the file names from .ts 

```javascript
	<script>
      System.config({
        transpiler: 'typescript', 
        typescriptOptions: { emitDecoratorMetadata: true }, 
        packages: {'app': {defaultExtension: 'ts'}} 
      });
      System.import('app/boot')
            .then(null, console.error.bind(console));
    </script>
```

**Comment by gintsgints** [comment] 2016-01-06 14:47
That way you transpile typescript right in your browser. Transpiling in browser takes rendering time.

**Comment by fripp0971** [comment] 2016-01-20 14:02
I got it to work in the plunker with some reordering and a slight change:

For the system.config call, just use this
 <script>
            System.config({defaultJSExtensions:true});
    </script>

Here is my final version  - you can use this as index and it will work.

Nowhere in the quick start for visual studio have a i read that ordering matters, but it seems the system config has to come in right after the system include script and before the calls to the angular and other scripts. Also the typescript include isn't needed either:



  <html>

  <head>
    <title>Angular 2 QuickStart</title>

    
    <script src="https://code.angularjs.org/tools/system.js"></script>
    
    <script>
      System.config({defaultJSExtensions:true});
      System.import('app/boot')
            .then(null, console.error.bind(console));
    </script>
    
    <script src="https://code.angularjs.org/2.0.0-beta.0/angular2-polyfills.js"></script>
    <script src="https://code.angularjs.org/2.0.0-beta.0/Rx.js"></script>
    <script src="https://code.angularjs.org/2.0.0-beta.0/angular2.dev.js"></script>
   
</head>

  
  <body>
    <my-app>Loading...</my-app>
  </body>
</html>

**Comment by GustavSt** [comment] 2016-02-07 15:11
I get this error by simply changing in the tsconfig.json. Changing the "module":"system" to "commonjs". Does that make sense?

**Comment by headwinds** [comment] 2016-02-09 14:39
I just successfully built the tutorial and would like to offer 2 points which messed me up

like @matthewharwood I also copy and pasted the wrong code for app.components.ts. When you introduce it, you could add the complete code - all 5 lines ;-D - like you do at the end of tutorial.

Also, for me, tsd failed and I had to install that separately - beyond that - it was a reasonable quick start; exciting stuff.

**Comment by kisdaniel** [comment] 2016-03-13 23:40
I have a same error after upgrading angular2 from beta.0 to beta.9:

`angular2-polyfills.js:138 Error: Cannot read property 'getOptional' of undefined(…)run @ angular2-polyfills.js:138zoneBoundFn @ angular2-polyfills.js:111lib$es6$promise$$internal$$tryCatch @ angular2-polyfills.js:1511lib$es6$promise$$internal$$invokeCallback @ angular2-polyfills.js:1523lib$es6$promise$$internal$$publish @ angular2-polyfills.js:1494lib$es6$promise$$internal$$publishRejection @ angular2-polyfills.js:1444(anonymous function) @ angular2-polyfills.js:243run @ angular2-polyfills.js:138zoneBoundFn @ angular2-polyfills.js:111lib$es6$promise$asap$$flush @ angular2-polyfills.js:1305`

I have debugged it and I found that it caused by: that a injector.getOptional throws this error if the injector is undefined:


```
function _runAppInitializers(injector) {
    var inits = injector.getOptional(application_tokens_1.APP_INITIALIZER);
    if (lang_1.isPresent(inits))
      inits.forEach(function(init) {
        return init();
      });
  }
```

I found that injector is created (declared) here:

```
PlatformRef_.prototype._initApp = function(zone, providers) {
      var _this = this;
      var injector;
      var app;
      zone.run(function() {
        providers = collection_1.ListWrapper.concat(providers, [di_1.provide(ng_zone_1.NgZone, {useValue: zone}), di_1.provide(ApplicationRef, {
          useFactory: function() {
            return app;
          },
          deps: []
        })]);
        var exceptionHandler;
        try {
          injector = _this.injector.resolveAndCreateChild(providers);
          exceptionHandler = injector.get(exceptions_1.ExceptionHandler);
          zone.overrideOnErrorHandler(function(e, s) {
            return exceptionHandler.call(e, s);
          });
        } catch (e) {
          if (lang_1.isPresent(exceptionHandler)) {
            exceptionHandler.call(e, e.stack);
          } else {
            lang_1.print(e.toString());
          }
        }
      });
      app = new ApplicationRef_(this, zone, injector);
      this._applications.push(app);
      _runAppInitializers(injector);
      return app;
    };
```

**Comment by oliverschenk** [comment] 2016-03-19 13:57
+1

**Comment by cgmartin** [comment] 2016-03-19 15:07
Also seeing error in browser console, with Angular 2 beta 11 on Ubuntu 14.04 using latest https://github.com/angular/quickstart
```
angular2-polyfills.js:258 Uncaught TypeError: Cannot read property 'zone' of undefined
```

Repo steps with Docker/Ubuntu 14.04:
```
# Dockerfile
FROM ubuntu:14.04

EXPOSE 3000 3001

RUN apt-get update && \
    apt-get install -y curl build-essential python git && \
    (curl -sL https://deb.nodesource.com/setup_5.x | sudo -E bash -) && \
    apt-get install -y nodejs && \
    mkdir -p /html && \
    git clone  https://github.com/angular/quickstart /html && \
    cd /html && \
    git reset --hard 0fb8db4de578b41300dfde84f7fbb06a3f563b11 && \
    rm -rf .git && \
    npm i

WORKDIR /html
VOLUME /html

CMD npm run postinstall && npm start
```

Build/Run commands:
```
$ docker build -t ng2-ubuntu .
$ docker run -it --rm -p 3000:3000 -p 3001:3001 ng2-ubuntu
# open browser http://$(docker-machine ip):3000
```

**Comment by johnpapa** [comment] 2016-03-19 15:12
@wardbell ^^ see this issue from Chris Martin. To get around it he had to run the postinstall afterwards separately

**Comment by cgmartin** [comment] 2016-03-19 15:18
btw, if I downgrade to an earlier angular quickstart commit (with angular2 beta-9), the polyfills/zone error goes away:

```
    ...
    git clone  https://github.com/angular/quickstart /html && \
    cd /html && \
    git reset --hard cd290d9558a4e4932a5c3f0521650eb2df2f9354 && \
    ...
```

**Comment by ericmartinezr** [comment] 2016-03-19 15:22
@cgmartin the zone error is being tracked here https://github.com/angular/angular/issues/7652

**Comment by Floryzzz** [comment] 2016-04-01 09:59
@GustavSt 
I tried this:
"I get this error by simply changing in the tsconfig.json. Changing the "module":"system" to "commonjs". Does that make sense?"

I tried changing this but then it wouldnt build so i changed it back.
But then
out of the magic of thin air it worked
thanks lads

**Comment by kiflay** [comment] 2017-10-26 20:21
Error: declare.call is not a function
  Instantiating http://localhost:62571/angular2/platform/browser
  Loading http://localhost:62571/app/main.js
  Loading app/main
    at registerDeclarative (register-loader.js:327)
    at register-loader.js:236
    at ZoneDelegate.invoke (angular2-polyfills.js:349)
    at Zone.run (angular2-polyfills.js:242)
    at angular2-polyfills.js:597
    at ZoneDelegate.invokeTask (angular2-polyfills.js:382)
    at Zone.runTask (angular2-polyfills.js:282)
    at drainMicroTaskQueue (angular2-polyfills.js:500)
    at <anonymous>

My app/main.ts ;
import { bootstrap } from 'angular2/platform/browser';
import { AppComponent } from './app.component';
import { enableProdMode } from 'angular2/core';

enableProdMode();
bootstrap(AppComponent);  

index.html
<core-min>
    <div><p>Please wait ;;;;;;;;;;</p></div>
</core-min>

    <script>
        System.config({
            packages: {
                'app': {
                    defaultExtension: 'js'
                }
            },
        });
        System.import('app/main').then(null, console.error.bind(console));
    </script>

app.component.ts
import { Component } from 'angular2/core';

@Component({
    selector: 'core-min',
    template: '<h3>Welcome to .NET Core 1.0 + MVC6 + Angular 2</h3>'
})
export class AppComponent {
    title = "here you are";
    hero = "heroooo";
} 
any help would be appreciated
