### ISSUE TITLE
Server-side rendering warning when using innerHTML

### ISSUE THREAD

**Issue by m98** [angular/angular#23741] opened 2018-05-07 09:18 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report 
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

I just updated Angular from version 5 to 6, and I just needed to change some Webpack configuration which I used for server-side rendering the web application.

I use `innerHTML` to insert HTML content into a `div` which used to work well both on the server, and browser on the previous version, but with the update, it's returning an error on Node server:

> ERROR ReferenceError: Node is not defined
>     at `isTemplateElement` ...

I opened the line of code the error was poining in ([this file](https://github.com/angular/angular/blob/3f70aba2722805b979984874248fa060e704d3e9/packages/core/src/sanitization/html_sanitizer.ts#L263)) and this probloem can be resolved by checking if it's browser _(or even something like `typeof window === "object"`)_

## Expected behavior
No error on server side when we use innerHTML on server, or a method to use instead of innerHTML :thinking: 

## Minimal reproduction of the problem with instructions
Making a server-rendered application on stackblitz is not avalable (as far as I know!); but here is how I used innerHTML:
```
    <article [innerHTML]="news.body"
                   itemprop="articleBody">
          </article>
```

## Environment

<pre><code>
Angular CLI: 6.0.0
Node: 8.9.3
OS: linux x64
Angular: 6.0.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, http, language-service, material, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.0
@angular-devkit/build-angular     0.6.0
@angular-devkit/build-optimizer   0.6.0
@angular-devkit/core              0.6.0
@angular-devkit/schematics        0.6.0
@ngtools/webpack                  6.0.0
@schematics/angular               0.6.0
@schematics/update                0.6.0
rxjs                              6.1.0
typescript                        2.7.2
webpack                           4.6.0

Browser:
- [x] Chrome (desktop) version 65.0.3325.181 (Official Build) (64-bit)
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version:  8.9.3
- Platform:  Linux (Fedora  27)

**Comment by trotyl** [comment] 2018-05-14 09:59
Duplicate of https://github.com/angular/angular/issues/23280

**Comment by IgorMinar** [comment] 2018-05-22 22:54
Closing in favor of #23280

**Closed by IgorMinar** 2018-05-22 22:54 UTC
Labels: comp: server
