### ISSUE TITLE
Can't reset a ControlGroup

### ISSUE THREAD

**Issue by ajtowf** [angular/angular#6169] opened 2015-12-29 16:35 UTC
After submitting a form it would be nice if I could somehow reset the ControlGroups state. **Perhaps a .reset() method on the ControlGroup?** The current way I accomplish this is by rebuilding the entire form, using the formbuilder.

I've tried several approaches, e.g. two-way-binding to a property on the component and clearing its value or updating the controls value with .updateValue(''). The problem with this is obviously that the internal state isn't reset, i.e. the controls are dirty and touched.

So, even if I reset the values the form will look differently since I probably bind the error divs by checking !field.dirty or !field.touched.

Please see my [video](https://youtu.be/T__VppOCk04) or check out my [ng2_play repo](https://github.com/ajtowf/ng2_play), it's always easier to show the problem.

It would also be nice to be able to **explicitly call validate**, i.e. form isn't validated/invalid by default, but [I created a separate issue](https://github.com/angular/angular/issues/6170) for that.

**Comment by jlmagee** [comment] 2015-12-29 20:48
It appears that none of the methods for ngModel from Angular1 have been implemented in Angular2. Implementation of the methods still appropriate for Angular2 would solve the reset requirement.

**Comment by antonmoiseev** [comment] 2015-12-29 23:52
Dups: #4933, #5568

**Comment by ajtowf** [comment] 2016-01-14 12:50
Concider the solution from the angular material team, they introduced

$setUntouched() and
$setPristine()

on the form.

**Comment by weizlini** [comment] 2016-01-15 14:58
yes i agree, to be able to set as pristine

OR make the the properties _pristine, _touched, etc PROTECTED instead of private so we can derive our own classes to perform such operations without angry transpilers

**Comment by arozwalak** [comment] 2016-01-25 11:13
+1

**Comment by OsoianMarcel** [comment] 2016-02-04 22:49
+1

**Comment by robwormald** [comment] 2016-02-05 00:44
closing as a dupe of #4933

**Closed by robwormald** 2016-02-05 00:44 UTC
