### ISSUE TITLE
Package Style with Directives

### ISSUE THREAD

**Issue by fireflysemantics** [angular/angular#51275] opened 2023-08-04 19:19 UTC
### Which @angular/* package(s) are relevant/related to the feature request?

core, elements

### Description

It would be nice to have the ability to package style with `@Directives` as well as with `@Components`.

We can create directives that alter the structure of components and sometimes we use CSS as part of the alteration ...

### Proposed solution

Add something to `@Directives` that allows the style to be packaged with the directive ...

### Alternatives considered

Currently I just put styles associated with directives in the structure mixin for the theme...like this....

```
@mixin structure($theme) {
    .el-RoundedSelect
        .mat-mdc-form-field-flex
        .mdc-notched-outline
        .mdc-notched-outline__notch
        label.mdc-floating-label--float-above {
        top: 28px !important;
    }    
}
```

As you can see it does not really depend on the theme, but it just ended up being a logical place to put it since directives can't include the style directly ...

**Comment by pkozlowski-opensource** [comment] 2023-08-05 11:57
This is a duplicate of #17766

**Closed by pkozlowski-opensource** 2023-08-05 11:57 UTC
