### ISSUE TITLE
docs: ng new not easy to find as a learner on angular.dev

### ISSUE THREAD

**Issue by geromegrignon** [angular/angular#55222] opened 2024-04-05 04:51 UTC
### Describe the problem that you experienced

With the new tutorial experience on angular.dev, people do not longer discover Angular by using `ng new`.
The **easiest** way to discover it is to :

- land on angular.dev
- click on 'Learn Angular'
- end all tutorial steps to land on the last 'Next Steps' tutorial step
- click on 'What is Angular link'
- Find out the next step is the 'Angular CLI' link
- click on Getting Started link

The other way is to explore the documentation and, as a beginner, to find out it's in Angular CLI/Local set-up.
As Angular CLI is not part of the **essentials**, that's not easy to know that's the proper page to look at.

The Algolia search does not help as a beginner because the closest search term to find the local setup page is by typing `create workspace`. At this point, beginners still do not know what is a workspace in Angular, and might more commonly refer to Angular workspaces as `applications`.

### Enter the URL of the topic with the problem

https://angular.dev/tools/cli/setup-local

### Describe what you were looking for in the documentation

There should be an easiest way to find how to create a new Angular app with Angular CLI as a beginner.

### Describe what you want to experience that would fix the problem

Adding a `create Angular workspace` section to the **Essentials** one (https://angular.dev/essentials) would be easier for everyone. It would also add an introduction to Angular CLI in this **Essentials** section.

**Comment by aiuoe** [comment] 2024-04-05 14:45
You can still consult it using ng new --help from the cli

**Comment by geromegrignon** [comment] 2024-04-05 14:47
> You can still consult it using ng new --help from the cli

It implies you know `ng new` exists. That's the real point here.

**Comment by JeanMeche** [comment] 2024-04-26 00:14
I'll close this as a dupe of #53241. 
I've raise the issue in the team to know which direction we want to take with https://github.com/angular/angular/blob/main/adev/src/content/cli/index.md#L15 which is currently orphan on ADEV.

**Closed by JeanMeche** 2024-04-26 00:14 UTC
Labels: P3, area: docs
