### ISSUE TITLE
Mandatory inputs, missing attributes vs undefined values

### ISSUE THREAD

**Issue by ratoi-crysty** [angular/angular#40390] opened 2021-01-11 13:28 UTC
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/compiler

### Description
 While using strict mode, if we have a component which has an mandatory input `@Input() value!: string` and we do not provide any value in the template, the compiler does not complain. But, if we do provide `undefined` as a value, the compiler complains, as the value couldn't be `undefined`, even though at runtime, they are both the same. 
Having that many components have inputs that are technically mandatory, as the components could not properly run without them, having this kind of type checking should provide allot of value.

I know that this was discussed in the past, but having that now, Angular started promoting strict mode, maybe we should address this again.

### Describe the solution you'd like
 Treat the missing attributes as if `undefined` was provided as value. As there is no runtime difference between them.

### Describe alternatives you've considered
 I've considered the workarounds that were recommended in other places, but none of them were satisfactory:
- using the selector to make it mandatory 'prefix-component[value]' -- But the errors received here, are misleading, as it complains that the component does not exist, instead of complaining about the attribute type. 
- throwing errors at runtime -- Again, this is wrong, as this should be a compilation error, because it's not different than a function with parameters or class constructor with parameters. Why should the component be any different? Besides this, pushing typing errors at runtime isn't a good practice, as it defeats the purpose of TypeScript and also increases the change that the issue will go unnoticed, if this is an edge case.

**Comment by atscott** [comment] 2021-01-11 18:18
Duplicate of #37706

**Closed by atscott** 2021-01-11 18:18 UTC

**Comment by ratoi-crysty** [comment] 2021-01-11 23:10
I've missed that one
