### ISSUE TITLE
NgClass with Id element not working

### ISSUE THREAD

**Issue by Polaris-BS** [angular/angular#15109] opened 2017-03-13 12:00 UTC
Hello, I have two lines of code :

```
<ul id="menu-slide"  [ngClass]="{'in' : toggleClass }" > <!--ngClass not work-->
<ul class="menu-slide"  [ngClass]="{'in' : toggleClass }" >  <!--ngClass work ! -->
```

Can you explain this magie ? Why a the first line not work ? 

Sorry for my simple english.

**Comment by DzmitryShylovich** [comment] 2017-03-13 12:04
Can't reproduce http://plnkr.co/edit/QuMoVidIurVY2ovVChO9?p=preview

**Comment by pkozlowski-opensource** [comment] 2017-03-13 16:19
@Polaris-BS please follow the issue template and attach a minimal reproduction in a plunker when reporting issues. 

I'm closing this one based on @DzmitryShylovich comment.

**Closed by pkozlowski-opensource** 2017-03-13 16:19 UTC
