### ISSUE TITLE
date pipe documentation is misleading, the date pipe is a pure pipe

### ISSUE THREAD

**Issue by sysmat** [angular/angular#33897] opened 2019-11-18 15:56 UTC
Update: See https://github.com/angular/angular/issues/33897#issuecomment-555440953 for info about the docs issue.

Original issue:
-----

# 🐞 bug report

### Affected Package

@angular/core

### Is this a regression?

 Yes, the previous versions work fine 

### Description
I have two properties in TS which I render in html for the first time with ok, then with function(TS) I change values but in html there is no change.  

## 🔬 Minimal Reproduction

 https://stackblitz.com/edit/angular-7gifwf

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by JoostK** [comment] 2019-11-18 17:35
Hey, what are we supposed to see? I see the exact same result in your StackBlitz under 9.0-rc.2 and 8.3.14, both running View Engine. Also this seems like the expected behavior to me, as the `Date` value is mutated which the `date` pipe doesn't consider, given that it's pure (which means it requires a new `Date` reference for a change to be picked up)

**Comment by pkozlowski-opensource** [comment] 2019-11-18 18:46
I'm with @JoostK here - the way I understand things is that mutating an internal state of the `Date` object should _not_ trigger change detection.

Note: the stackblitz doesn't run ivy so it actually _confirms_ that view engine is _not_ updating values... 

I'm going to close this issue now based on the above. @sysmat  happy to re-open if you can demonstrate a regression. Thank you!

**Comment by sysmat** [comment] 2019-11-19 06:13
Thx for answer, yes in VER 8 change detection not working, I didn't realize that for Date is not change detection, a little  disappointment, comming from strong type landscape.

Date is Interface so if I do some simple Interface:

```typescript
export interface ObI {
  title: string;
  showDays: number;
}
...
changeDay(event: string): void {
    if (event === 'today') {
      this.obI.title = 'today';
    } else if (event === 'previous') {     
      this.obI.title = 'previous';
    } else if (event === 'next') {
      this.obI.title = 'next';
    }
```

```html
<h1>
    Welcome to {{ obI.title }}!
  </h1>
```
Then change detection is working so where is from language point difference?

**Comment by sysmat** [comment] 2019-11-19 07:25
Ok in doc for date pipe I find:

> To avoid the need to reformat the date on every change-detection cycle, treat the date as an immutable object and change the reference when the pipe needs to run again.

**Comment by pkozlowski-opensource** [comment] 2019-11-19 10:28
Hmm, I think that docs are misleading in this case as the `date` pipe [is pure](https://github.com/angular/angular/blob/c68200cf426a8cd0bc9ff95b4d0140133c28f661/packages/common/src/pipes/date_pipe.ts#L153) and won't deep-check an object when a reference to it isn't change.

**Comment by ajitsinghkaler** [comment] 2019-11-23 03:05
@jbogarthyde can I help you on this

**Comment by kapunahelewong** [comment] 2020-05-27 16:38
Thank you, @ajitsinghkaler. @rockument69 is already doing a rewrite of Pipes in https://github.com/angular/angular/pull/36820. Fyi, @rockument69, see https://github.com/angular/angular/issues/33897#issuecomment-555440953

**Comment by rockument69** [comment] 2020-06-08 22:00
@kapunahelewong @jbogarthyde @ajitsinghkaler @sysmat : The pipes.md doc in my PR  #[36820](https://github.com/angular/angular/pull/36820) does not change because it already describes DatePipe as a pure pipe.

However, the API doc should change, and I defer to @jbogarthyde who might already be in the process of changing it -- if not, Judy, let me know and I can do it.

The API doc for DatePipe has this sentence: "To avoid the need to reformat the date on every change-detection cycle, treat the date as an immutable object and change the reference when the pipe needs to run again." This may be accurate but it is confusing. I propose replacing it with this sentence:

> DatePipe is executed only when it detects a pure change to the input value.
> A pure change is either a change to a primitive input value (such as `String`, `Number`, `Boolean`, or `Symbol`), or a changed object reference (such as `Date`, `Array`, `Function`, or `Object`).
>

**Comment by jbogarthyde** [comment] 2020-06-09 19:14
Addressing this issue in https://github.com/angular/angular/pull/37099

**Closed** 2021-05-25 22:10 UTC
Labels: P4, comp: docs, freq1: low, triage #1, type: bug/fix
