### ISSUE TITLE
Observable typing is lost in templates

### ISSUE THREAD

**Issue by jrista** [angular/angular#43797] opened 2021-10-11 16:43 UTC
### Which @angular/* package(s) are the source of the bug?

common, compiler, core

### Is this a regression?

Yes

### Description

With Angular 12 and stricter TypeScript type checks, it appears that templates lose the typing on observables. Within the component class, observables (say selected from the NgRx Store) properly attain an inferred type from the `store.select(selector)` call. 

![Screen Shot 2021-10-11 at 10 30 47 AM](https://user-images.githubusercontent.com/238441/136825524-78217887-5b33-4de8-857b-424a34c22c78.png)

However in the template of that component, observables are vert frequently (but, oddly, not always ... ???) typed as `unknown`:

![Screen Shot 2021-10-11 at 10 36 27 AM](https://user-images.githubusercontent.com/238441/136825504-1eaec90a-d796-4ac9-8cfd-e6655d04aece.png)

It does not seem to matter if the observable is used within an `*ngFor`, or just a simple input binding, the type of the observables can end up `unknown` either way. This does not cause strict build errors, however it does mean that type information is lost within the template, and that all of the benefits of TS strong typing, IDE intellisense, etc. are unable to be realized or used. 

### Please provide a link to a minimal reproduction of the bug

This is more of an IDE type thing, so no real way to "reproduce" outside of VSCode, WebStorm, etc.

### Please provide the exception or error you saw

See images above. 

### Please provide the environment you discovered this bug in

WebStorm (latest version) in my case, although we have encountered the issue with VSCode as well.

### Anything else?

It is possible to work around the issue by explicitly typing each and every observable within each component class. Explicitly typing seems to somehow ensure that the template gets the right types, not really sure how. This can add a decent amount of additional typing, and if for any reason the types of the streams ever need to change, it increases the effort to make those type changes. Ideally, type inferrence would work through the component/template boundary without issue, as it has in past versions of Angular.

**Comment by atscott** [comment] 2021-11-02 17:08
Closing due to lack of reproduction. Please do submit a new issue if you can create a minimal repro.

**Closed by atscott** 2021-11-02 17:08 UTC
Labels: needs reproduction, comp: compiler

**Comment by jrista** [comment] 2021-11-03 15:43
Hi Andrew, apologies here. Got caught up in other things. I am not sure exactly what is causing the issue, but it doesn't seem to occur all the time with VSCode, while it does with webstorm. So it may indeed be different issues, and the webstorm one seems like it may indeed be a webstorm issue. I'll be opening a ticket with JetBrains for that, but if we can figure out how to reproduce in VSCode I'll drop a repro in a new issue.
