### ISSUE TITLE
Angular challenge: can you do it?

### ISSUE THREAD

**Issue by hiepxanh** [angular/angular#24240] opened 2018-06-01 04:42 UTC
## I'm submitting a...
[x] Performance issue

## Current behavior
angular 6 with Ivy is struggling with this example performance: "Sierpinski Triangle". React Fiber done this very good but angular won't. Can you explain why ? and how many strategy we can do to improve the performance?

## Expected behavior
make it smoooth like react fiber

## Minimal reproduction of the problem with instructions
[github repository](https://github.com/hiepxanh/Ng6-Sierpinski-triangle/tree/gh-pages)
[ng6 demo website: nope](https://hiepxanh.github.io/Ng6-Sierpinski-triangle/)
[ng4 demo website: nope!](https://gund.github.io/ng-s-triangle-demo/)
[react demo website: smooth](https://claudiopro.github.io/react-fiber-vs-stack-demo/)
[stencil by ionic demo website: smooth ](https://stencil-fiber-demo.firebaseapp.com/)
## What is the motivation / use case for changing the behavior?
Well, people moving to React because it have big community and it's performance is so sweet. can we beat them?

## Environment
Angular version: 6.0.3 with Ivy or not

Browser:
- [x ] Chrome (desktop) version 66 ( not update the number)
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [x] Safari (desktop) version 11.1 (very smooth)
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.11.1
- Platform:  Mac

**Comment by trotyl** [comment] 2018-06-01 05:00
Duplicate of https://github.com/angular/angular/issues/19030

**Closed** 2018-06-07 03:36 UTC
Labels: comp: performance

**Comment by MattiJarvinen-BA** [comment] 2018-12-03 13:43
See https://github.com/angular/angular/issues/19030#issuecomment-412417871

https://stackblitz.com/edit/angular6-store
