### ISSUE TITLE
@firebase/database: FIREBASE WARNING: Exception was thrown by user callback. TypeError: Cannot read property 'myID' of undefined (Production build only)

### ISSUE THREAD

**Issue by gate3** [angular/angular#23776] opened 2018-05-08 18:50 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

I am using angularfire with geofire for a location based app for fetching locations around my user. It works perfectly on my dev machine, but as soon as i build and deploy to firebase hosting, I get a very strange error. 

> @firebase/database: FIREBASE WARNING: Exception was thrown by user callback. TypeError: Cannot read property 'myID' of undefined

This error happens when the app is trying to retrieve the locations from firebase. And the error only happens after i've run ng build --prod.

## Expected behavior

I expect the app to fetch locations from firebase and display the locations.

## Minimal reproduction of the problem with instructions

I uploaded the app to a github repo. You can find it here [https://github.com/gate3/Sample-Code](https://github.com/gate3/Sample-Code)

## Environment

<pre><code>
Angular version: ^5.2.0

Browser:
- [ x] Chrome (desktop) version XX
- [x ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

Firebase: ^4.13.1

AngularFire: ^5.0.0-rc.6.0

**Comment by paulootavio** [comment] 2018-05-08 21:18
hi, your sample code give a 404, can you repair?

**Comment by gate3** [comment] 2018-05-08 21:41
Hi, its been updated. Kindly check again. thanks

**Comment by mhevery** [comment] 2018-05-08 22:58
Thank you for submitting the issue. All issues require a [plunker](https://plnkr.co/) which demonstrates the problem and how to reproduce it. Please re-open the issue or create a new issue once you have a reproducible use case.

We are sorry that we are so aggressive on closing the issues. We are overwhelmed with the number of issues we get, and so we only have time to look at the ones which are easy for us to reproduce.

**Comment by Luckygirlllll** [comment] 2018-05-11 08:14
I have the same error, why is it appear?

**Comment by mhevery** [comment] 2018-05-22 22:30
Hi @gate3, I see your stacklitz link. When I click on it I see a red box. I don't know what I should do next. 

A great reproduction steps would say: 1) click here, notice that you get X, but I expect Y because Z.

**Comment by mhevery** [comment] 2018-06-14 22:51
This issue seems abandoned without any reproducible instruction.  We are closing the issue. If you have reproducible instructions please file a new issue.

**Closed by mhevery** 2018-06-14 22:51 UTC
Labels: comp: core & compiler, state: Need repro
