### ISSUE TITLE
Error: Angular JIT compilation failed: '@angular/compiler' not loaded!

### ISSUE THREAD

**Issue by no-more** [angular/angular#38460] opened 2020-08-14 07:47 UTC
# 🐞 bug report

### Affected Package
Not sure, but maybe `@angular/compiler` or `@angular/cli`

### Is this a regression?

Yes it was working with angular 8 and I think angular 9. (I've migrated both in a row after doing some test in V9 to check it was working. But maybe I've missed something in my tests) 
I'm trying to complete migration, no compilation error, apps run in browser as long as I don't set `optimization` build option in `angular.json`

### Description
If I set `"optimization": true` in angular.json I have the following error in my browser (no compilation error even with AOT)
```
main-es2015.83cd1a7f2902ea042a79.js:1 Error: Angular JIT compilation failed: '@angular/compiler' not loaded!
  - JIT compilation is discouraged for production use-cases! Consider AOT mode instead.
  - Did you bootstrap using '@angular/platform-browser-dynamic' or '@angular/platform-server'?
  - Alternatively provide the compiler with 'import "@angular/compiler";' before bootstrapping.
```

## 🔬 Minimal Reproduction

Currently don't manage to isolate where the issue comes from so I'm not able to create a reproduction sample repo.
I know I have some custom bootstraping pre-process, but I don't think that's the issue
Ivy is on (wasn't in V8 and V9), OAT is and was on, optimization was on too when I was in V8

## 🔥 Exception or Error
<pre><code>
main-es2015.83cd1a7f2902ea042a79.js:1 Error: Angular JIT compilation failed: '@angular/compiler' not loaded!
  - JIT compilation is discouraged for production use-cases! Consider AOT mode instead.
  - Did you bootstrap using '@angular/platform-browser-dynamic' or '@angular/platform-server'?
  - Alternatively provide the compiler with 'import "@angular/compiler";' before bootstrapping.
    at z (main-es2015.83cd1a7f2902ea042a79.js:1)
    at Function.get (main-es2015.83cd1a7f2902ea042a79.js:1)
    at We (main-es2015.83cd1a7f2902ea042a79.js:1)
    at cs (main-es2015.83cd1a7f2902ea042a79.js:1)
    at main-es2015.83cd1a7f2902ea042a79.js:1
    at os.processProvider (main-es2015.83cd1a7f2902ea042a79.js:1)
    at main-es2015.83cd1a7f2902ea042a79.js:1
    at main-es2015.83cd1a7f2902ea042a79.js:1
    at Array.forEach (<anonymous>)
    at we (main-es2015.83cd1a7f2902ea042a79.js:1)
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 10.0.5
Node: 14.8.0
OS: win32 x64

Angular: 10.0.8
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1000.5
@angular-devkit/build-angular      0.1000.5
@angular-devkit/build-ng-packagr   0.1000.5
@angular-devkit/build-optimizer    0.1000.5
@angular-devkit/build-webpack      0.1000.5
@angular-devkit/core               10.0.5
@angular-devkit/schematics         10.0.5
@angular-devkit/schematics-cli     0.1000.5
@angular/cdk                       10.1.3
@angular/cli                       10.0.5
@angular/flex-layout               10.0.0-beta.32
@angular/http                      7.2.16
@angular/material                  10.1.3
@angular/material-moment-adapter   10.1.3
@angular/pwa                       0.1000.5
@ngtools/webpack                   10.0.5
@schematics/angular                10.0.5
@schematics/schematics             0.1000.5
@schematics/update                 0.1000.5
ng-packagr                         10.0.3
rxjs                               6.6.2
typescript                         3.9.7
webpack                            4.43.0
</code></pre>

**Anything else relevant?**

**Comment by petebacondarwin** [comment] 2020-08-17 14:34
@no-more - could you provide a runnable reproduction of this issue? It is very hard to debug just from the error message.

**Comment by no-more** [comment] 2020-08-17 17:24
@petebacondarwin I'd really like to but as said before I have not idea of what create this error so I'm not able to create a minimum reproduction case.
The best I could do currently is to deploy the code on a server or send you the transpiled code (with or without optimization if that could help)
But the project is quite big and even with optimization on the main.js file is over 12Mo...

Maybe if you have some clue to give me I could dig further and try to isolate the source of the error, but currently I really don't know where to look and have already spend days trying to find something.

Thanks for your help

**Comment by emondora** [comment] 2020-08-19 01:18
same problem.

**Comment by no-more** [comment] 2020-08-19 14:58
I think I've found the source of the error I had.
It seems it was related to an old package (angular2-logger) I wasn't really using any more (but still importing some declaration).
I'm still not sure why this happens but removing it solved my issue.
I don't know if you want to keep the issue open to investigate the source of the error, but as it was an old unmaintained package I don't think important.

**Comment by petebacondarwin** [comment] 2020-08-19 15:05
@no-more - glad you worked it out. The reason is probably that `angular2-logger` is not compatible with ivy/ngcc and so it was failing to be processed (or causing a failure that stopped other packages from being processed correctly).
Closing as the problem is unlikely to be a bug in ngcc. Thanks!

**Closed by petebacondarwin** 2020-08-19 15:05 UTC
Labels: comp: compiler, state: Needs repro, type: bug/fix
