### ISSUE TITLE
Empty style tag when one or more components don't have styles

### ISSUE THREAD

**Issue by borjapazr** [angular/angular#31191] opened 2019-06-21 16:22 UTC
# Empty style tag when one or more components don't have styles

### Affected Package
The issue is caused by package @angular/angular

### Is this a regression?
This happens in all versions of Angular

### Description
When several components are added to a template and one or more of them do not have defined styles, an empty style tag appears in the header.
The desired result would be that this empty label was not added.

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-jpfxql
https://angular-jpfxql.stackblitz.io

In the second URL, if we inspect the page we can see an empty style tag in the header corresponding to app.component.css

## 🌍  Your Environment

**Angular Version:**
Angular CLI: 8.0.3
Node: 10.15.0
OS: win32 x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.800.3
@angular-devkit/core         8.0.3
@angular-devkit/schematics   8.0.3
@schematics/angular          8.0.3
@schematics/update           0.800.3
rxjs                         6.4.0

**Comment by MrNocTV** [comment] 2020-05-12 03:13
I'm having problem with this, please fix it. Our project using CSP to prevent inline style so having an empty `<style>` tag in `<head>` will cause browser to spit out annoying CSP error logs. I also have one question for this on [stackoverflow](https://stackoverflow.com/questions/61730637/how-to-remove-angular-empty-style-tag-in-header?noredirect=1#comment109196823_61730637) in hope for getting a workaround but it seems to be impossible for the moment. 

However, I've managed to upgrade to Angular 9 and I'm not sure if this is fixed in Angular 9 or not (it seems to be), the empty `<style>` tags are gone.

**Comment by MrNocTV** [comment] 2020-05-13 04:47
Hi, I've checked the code and the root cause is in `shared_styles_host.ts`. The `addStyles` method of `SharedStyleHost` class and `_addStylesToHost` of `DomSharedStylesHost` do not check for empty style. I think it will make more sense if we exclude those empty styles and prevent them from being injected into the DOM.

However, my company is using Angular 8. Can I make a PR to one of these three branches `8.0.x` `8.1.x` or `8.2.x`?

**Comment by Splaktar** [comment] 2021-07-12 18:58
@MrNocTV I don't think that it would be possible to get this fixed in Angular v8, but many thanks for investigating the root cause and posting info here.

**Comment by Splaktar** [comment] 2021-07-12 19:04
# Angular v8 with empty component styles
![Screen Shot 2021-07-12 at 15 00 18](https://user-images.githubusercontent.com/3506071/125341972-3efb9380-e322-11eb-80bf-15a11c53c6e3.png)


# Angular v8 without component styles
![Screen Shot 2021-07-12 at 15 02 20](https://user-images.githubusercontent.com/3506071/125341991-43c04780-e322-11eb-8c67-2141235d8bef.png)

StackBlitz: https://stackblitz.com/edit/no-component-styles-no-empty-style-tag?file=src%2Fstyles.css
Whole page Preview: https://no-component-styles-no-empty-style-tag.stackblitz.io/

**Comment by Splaktar** [comment] 2021-07-12 19:07
This is still reproducible in Angular v12.1.1:

Angular v12 StackBlitz: https://empty-component-styles-empty-style-tag.stackblitz.io
Whole page Preview: https://empty-component-styles-empty-style-tag.stackblitz.io/

**Comment by borjapazr** [comment] 2021-12-14 22:26
Any progress on this issue?

**Closed** 2022-05-03 16:38 UTC
Labels: type: bug/fix, freq1: low, comp: core, state: has PR, core: stylesheets, cross-cutting: CSP, P4
