### ISSUE TITLE
Promise.prototype.then called on incompatible receiver in Chrome 77.0.3865.90

### ISSUE THREAD

**Issue by zaenk** [angular/angular#32802] opened 2019-09-21 18:19 UTC
# 🐞 bug report

### Affected Package

The issue is caused by package zone.js

Maybe.

### Is this a regression?

Actually angular is not broken, but a browser update broke the frameworks behavior.

It's still working in all other browsers except Chrome 77.0.3865.90

### Description

In Chrome 77.0.3865.90 in some case the following error is thrown for Promises around ReadableStream, WritableStream or TransformStream, but I couldn't come up with a simple reproduction.

It was working fine until the most recent Chrome patch.

```
TypeError: Method Promise.prototype.then called on incompatible receiver [object Object]
    at ZoneAwarePromise.then (<anonymous>)
```

## 🔬 Minimal Reproduction

https://github.com/zaenk/chrome77-zonejs-promise-bug

Prereq: node 10 or 12, npm 3.11+, ng cli 8.3.5

* Clone the repo
* npm install
* ng serve
* Open localhost:4200 in an updated Chrome Stable channel (77.0.3865.90)
* F12 for console, observe the error message
* If it not breaks for the first time, give the dev server and the browser some restart

## 🔥 Exception or Error

<pre><code>
TypeError: Method Promise.prototype.then called on incompatible receiver [object Object]
    at ZoneAwarePromise.then (<anonymous>)
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.5
@angular-devkit/build-angular     0.803.5
@angular-devkit/build-optimizer   0.803.5
@angular-devkit/build-webpack     0.803.5
@angular-devkit/core              8.3.5
@angular-devkit/schematics        8.3.5
@angular/cli                      8.3.5
@ngtools/webpack                  8.3.5
@schematics/angular               8.3.5
@schematics/update                0.803.5
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2
</code></pre>

**Anything else relevant?**

### Browser version

Code that throwing this error is working in:

* Chrome 76
* Chrome 78 (Beta)
* Chrome 79 (Canary)
* Firefox 68
* Firefox 69
* Edge 18
* Edge 78 (Dev)
* Also might have worked in 77.0.3865.75, but I cannot tell this for sure

### Other

* webpack package was not installed at top level node_modules with npm 6.8.x, installing 6.11.3 of npm fixed that

Edit:
* Here's a fiddle with the working code without angular https://jsfiddle.net/by15stqh/4/
* I tried to debug this for hours, every place where this library uses `await` it returns a Promise, which always have the `then` override from zone. Every object being wrapped is a Promise
https://github.com/angular/angular/blob/2e84f4e0cda5ee4d1c9dae0c5789c7225d7c94e5/packages/zone.js/lib/common/promise.ts#L474-L478
* Tried NgZone `runOutsideAngular` but the global promise is still modified by zone, so the result is the same
* Tried with zone.js 0.9.1 and 0.10.2, no difference

**Comment by SlyverGR** [comment] 2019-09-23 03:59
Same here, using openpgp plugin for encryption , now after Chrome update, getting the same error.

**Comment by Diegoivanc** [comment] 2019-09-23 18:34
I have the same error with ionic 3, when I close the app and open it again that error comes up when consulting an xmlrpc.
It only works when I turn off chrome

**Comment by lynxerious** [comment] 2019-09-24 10:17
I also have this exact problem. Broken on every promise I call, still trying to fix. All other angular projects of mine except one aren't affected by this issue. :(

**Comment by andydemeulemeester** [comment] 2019-09-24 12:04
It looks like its only with Chrome 77, try installing the beta v78 or downgrade chrome

**Comment by jeremyclark** [comment] 2019-09-24 15:15
As a temporary workaround you can set TransformStream, ReadableStream, and Writable stream to null so they are set by polyfills. They need to be set before your app is loaded.

```
<script>
  window.TransformStream = null;
  window.WritableStream = null;
  window.ReadableStream = null;
</script>
```

I am not sure of any issues this temporary fix may cause but it did get my application working again.

**Comment by SlyverGR** [comment] 2019-09-24 23:03
> 
> 
> As a temporary workaround you can set TransformStream, ReadableStream, and Writable stream to null so they are set by polyfills. They need to be set before your app is loaded.
> 
> ```
> <script>
>   window.TransformStream = null;
>   window.WritableStream = null;
>   window.ReadableStream = null;
> </script>
> ```
> 
> I am not sure of any issues this temporary fix may cause but it did get my application working again.

Using on Ionic Android app, i put the code at the star of my index, but now im getting this error:

> Uncaught (in promise): TypeError: TransformStream is not a constructor
TypeError: TransformStream is not a constructor

**Comment by JiaLiPassion** [comment] 2019-09-25 11:54
Yeah, the reason seems to related to `ReadableStream.pipeTo` method, I am still researching it.

**Comment by slyfalcon** [comment] 2019-09-25 15:05
> As a temporary workaround you can set TransformStream, ReadableStream, and Writable stream to null so they are set by polyfills. They need to be set before your app is loaded.
> 
> ```
> <script>
>   window.TransformStream = null;
>   window.WritableStream = null;
>   window.ReadableStream = null;
> </script>
> ```
> 
> I am not sure of any issues this temporary fix may cause but it did get my application working again.

thanks, it saved my day! My chrome version is: 77.0.3865.90, the old one works fine. The brand new chrome seems have little problems

**Comment by JiaLiPassion** [comment] 2019-09-25 21:21
maybe related to this commit, https://chromium.googlesource.com/chromium/src/+/2c47467c5f28a93d77349492683e6994cd96ef33%5E%21/#F0, 
I am sending mail to check the reason.

**Comment by lynxerious** [comment] 2019-09-26 04:36
I found out why some of my projects still work while some does not. All the projects that are using the package 'request-promise' get the error, the newer ones I had switched to 'axios' which doesn't get the problem at all. 

I planned on migrating from 'request-promise' to 'axios' anyway due to package size, now there is another reason to go for it.

**Comment by codesandnotes** [comment] 2019-09-26 06:05
> > As a temporary workaround you can set TransformStream, ReadableStream, and Writable stream to null so they are set by polyfills. They need to be set before your app is loaded.
> > ```
> > <script>
> >   window.TransformStream = null;
> >   window.WritableStream = null;
> >   window.ReadableStream = null;
> > </script>
> > ```
> > 
> > 
> > I am not sure of any issues this temporary fix may cause but it did get my application working again.
> 
> Using on Ionic Android app, i put the code at the start of my index, but now im getting this error:
> 
> > Uncaught (in promise): TypeError: TransformStream is not a constructor
> > TypeError: TransformStream is not a constructor

I encounter the exact same problem (Ionic 3 app using openpgp.js, which is where the issue occurs in my case). 
I had to specifically add a polyfill for the web streams right after I nullified the browser ones: after the "null setting" code, just add:
`<script src="https://unpkg.com/web-streams-polyfill/dist/polyfill.min.js"></script>`
You should be ok now...

**Comment by JiaLiPassion** [comment] 2019-09-27 02:20
I have confirmed with Chrome team, this issue will be fixed from Chrome side in chrome 78, so I will test it and close this issue after chrome 78 stable is out.

**Comment by Oceania2018** [comment] 2019-10-04 20:55
I encounter the issue for Open API viewer **Redoc**, keep loading. Other browsers work fine.

**Comment by hidemo** [comment] 2019-10-06 09:56
I got this error and fixed by the code sentence I catch error if you call another received function something like get{...},**(err => {})** after **then** {brackets}

**Comment by amhtech** [comment] 2019-10-08 06:58
> Same here, using openpgp plugin for encryption , now after Chrome update, getting the same error.

@SlyverGR Exact same problem I am also facing, May I know if you have found a valid fix for this?! Thanks!

**Comment by amhtech** [comment] 2019-10-08 08:43
> > > As a temporary workaround you can set TransformStream, ReadableStream, and Writable stream to null so they are set by polyfills. They need to be set before your app is loaded.
> > > ```
> > > <script>
> > >   window.TransformStream = null;
> > >   window.WritableStream = null;
> > >   window.ReadableStream = null;
> > > </script>
> > > ```
> > > 
> > > 
> > > I am not sure of any issues this temporary fix may cause but it did get my application working again.
> > 
> > 
> > Using on Ionic Android app, i put the code at the start of my index, but now im getting this error:
> > > Uncaught (in promise): TypeError: TransformStream is not a constructor
> > > TypeError: TransformStream is not a constructor
> 
> @SlyverGR I encounter the exact same problem (Ionic 3 app using openpgp.js, which is where the issue occurs in my case).
> I had to specifically add a polyfill for the web streams right after I nullified the browser ones: after the "null setting" code, just add:
> `<script src="https://unpkg.com/web-streams-polyfill/dist/polyfill.min.js"></script>`
> You should be ok now...

@codesandnotes Thanks! it worked.

**Comment by amhtech** [comment] 2019-10-08 08:44
> > As a temporary workaround you can set TransformStream, ReadableStream, and Writable stream to null so they are set by polyfills. They need to be set before your app is loaded.
> > ```
> > <script>
> >   window.TransformStream = null;
> >   window.WritableStream = null;
> >   window.ReadableStream = null;
> > </script>
> > ```
> > 
> > 
> > I am not sure of any issues this temporary fix may cause but it did get my application working again.
> 
> Using on Ionic Android app, i put the code at the start of my index, but now im getting this error:
> 
> > Uncaught (in promise): TypeError: TransformStream is not a constructor
> > TypeError: TransformStream is not a constructor

@SlyverGR Thanks, workaround solution solved the issue, saved a lot of time.

**Comment by BeatriceThalo** [comment] 2019-10-08 14:18
@jeremyclark's workaround fixes the incompatible receiver error for me in chrome stable 76/stable 77/beta 78/dev 79, but when testing through browserstack on dev chrome v79 (future proof testing) my ionic project prints to the client console "Dev server logger closed   ion-dev.js?v=3.2.4:121" which is in a socket onclose function. I suppose removing the workaround once chrome desktop stable is released would fix that, unless anyone understands the logical link between those.

**Comment by sertal70** [comment] 2019-10-09 07:51
I run in this error on my Ionic 3 project, thanks @jeremyclark for the workaround, it worked fine.

@BeatriceThalo did you get the error in v78 beta also? I'm asking because the closing comment in [chromium issue](https://bugs.chromium.org/p/chromium/issues/detail?id=1008376) states that the issue will be fixed in v78.

**Comment by BeatriceThalo** [comment] 2019-10-09 12:36
@sertal70 With no workaround present, works in 76/78/79 and errors in 77. With workaround present, works in 76/77/78/79.

**Comment by JiaLiPassion** [comment] 2019-10-09 12:37
@BeatriceThalo , thanks for the confirmation.

**Comment by sertal70** [comment] 2019-10-09 12:43
@BeatriceThalo crystal clear, thanks so much.

**Comment by JiaLiPassion** [comment] 2019-11-05 15:51
Confirmed in `Chrome Version 78.0.3904.87 (Official Build) (64-bit)`, the issue is gone.

**Closed by JiaLiPassion** 2019-11-05 15:51 UTC
Labels: comp: zones
