### ISSUE TITLE
Manual shutdown support in Angular2

### ISSUE THREAD

**Issue by mirikle** [angular/angular#5715] opened 2015-12-08 21:56 UTC
A typical use case is instead of letting angular framework takes over the whole app, only certain parts of the app uses angular. So it would be nice if angular is self-contained, or at least have a clear boundary when it interacts with global component like `location` and how to dis-entangle them. See here for a discussion in Angular 1 tracking https://github.com/angular/angular.js/issues/1537

**Comment by pkozlowski-opensource** [comment] 2015-12-12 11:13
Duplicate of https://github.com/angular/angular/issues/2312

**Closed by pkozlowski-opensource** 2015-12-12 11:13 UTC
