### ISSUE TITLE
aio: Animations Guide

### ISSUE THREAD

**Issue by dherges** [angular/angular#17931] opened 2017-07-05 05:26 UTC
## I'm submitting a request for enhancing documentation

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[ ] Bug report 
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Actually, I wanted to report that we need an Animations guide, since there isn't any. However, it turns out that just the aio search is fluky:

![2017-07-05 07_23_50-angular - animations](https://user-images.githubusercontent.com/901354/27850189-0faa82b2-6153-11e7-95af-29049279775f.png)

## Expected behavior

[Animations Guide](https://angular.io/guide/animations#animations) should be easier to find.

## Minimal reproduction of the problem with instructions

Search term "animations"

## What is the motivation / use case for changing the behavior?

Improve "findability" :sunflower:

**Comment by gkalpak** [comment] 2017-07-05 10:53
This is kind of a duplicate of #17545 and #17889 (in that they both refer to search-results problems). It should be fixed (or at least considerably improved) by #17574.

**Closed by gkalpak** 2017-07-05 10:53 UTC

**Comment by petebacondarwin** [comment] 2017-07-06 08:35
Once #17574 and https://github.com/olivernn/lunr.js/pull/281 land then we will get results like this:

![screen shot 2017-07-06 at 09 35 06](https://user-images.githubusercontent.com/15655/27902667-6d4c4ef6-622e-11e7-9aeb-d8565b890ed6.png)
