### ISSUE TITLE
Angular 9 PWA Service Worker doesn't works offline when loaded first time without internet.

### ISSUE THREAD

**Issue by ashish-sharma4u** [angular/angular#43547] opened 2021-09-23 09:56 UTC
I am using Angular 9 for creating PWA, I am facing a problem when I try to load the application without internet (After loading it once before,  understand that it requires cache). I am able to use the offline functionality properly if I launch the application and cut off the internet and navigate to different pages. but when I try to load or refresh the page it doesn't load anything and throws a 504  error.

Thank you!

**Comment by gkalpak** [comment] 2021-09-23 14:03
It sounds like the ServiceWorker is getting into a degraded mode where it only serves existing clients. You need to figure out why this happens and fix the root cause. You can find some helpful info on debugging the Angular SW [here][1].

##
That said, this issue doesn't fall into the bug report or feature request category, so I am going to close it. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](https://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question).

[1]: https://angular.io/guide/service-worker-devops#debugging-the-angular-service-worker

**Closed by gkalpak** 2021-09-23 14:03 UTC

**Comment by ashish-sharma4u** [comment] 2021-09-23 14:28
@gkalpak thank you soo much for the reply, I have fixed my problem by configuring my Nginx with the following lines  

# Force all paths to load either itself (js files) or go through index.html.
      location /index.html {
          try_files $uri /index.html;

          add_header Cache-Control "no-store, no-cache, must-revalidate";
      }

      location / {

          expires 1y;
          add_header Cache-Control "public";
      }
I have got the hint from 
https://stackoverflow.com/questions/62213355/angular-service-worker-with-angular-pwa-package-showing-http-error-504-when-o
and 
https://rhazn.com/posts/build-a-progressive-web-app-in-docker-with-nginx-to-deploy-to-kubernetes-or-docker-swarm/

I hope this would be helpful for someone else , if this doesn't comply any guidelines feel free to delete this comment 
Thank you!
