### ISSUE TITLE
ControlValueAccessor: use types for the function passed to registerOnChange an registerOnTouched instead of any

### ISSUE THREAD

**Issue by rehdie** [angular/angular#47719] opened 2022-10-10 17:55 UTC
### Which @angular/* package(s) are relevant/related to the feature request?

forms

### Description

The parameters of the methods registerOnChange and registerOnTouched of the interface ControlValueAccessor have type any.

IMHO specific types would be better.

### Proposed solution

```
registerOnChange(fn: (arg: any) => void)
registerOnTouched(fn: () => void)
```

This shouldn‘t break existing code…

### Alternatives considered

none

**Comment by dylhunn** [comment] 2022-11-18 00:41
Closing as dupe of #45968.

(We're aware that ControlValueAccessor doesn't use the types. However, this is actually a really big breaking change to fix -- it will result in a lot of incorrect code that relied on the `any` becoming broken.)

**Closed by dylhunn** 2022-11-18 00:41 UTC
Labels: area: forms, P3
