### ISSUE TITLE
Angular Injects ParentService instead of ChildService

### ISSUE THREAD

**Issue by shavipathania** [angular/angular#25026] opened 2018-07-22 12:11 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

When ChildService ( which is extended from ParentService) is being passed to Component for DI. Then, it is being resolved to ParentService instead of ChildService. 

## Expected behavior

ChildService should be resolved to ChildService NOT ParentService

## Minimal reproduction of the problem with instructions

Steps:
1) Create ParentService (providedIn: root)
2) Create ChildService (providedIn: root)
3) Inject in AppComponent
4) console.log(childService instance of ChildService) // false which should be true

https://stackblitz.com/edit/angular-ypq7ag

## Environment
<pre><code>
Angular version: 6.0.9

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

</code></pre>

**Comment by trotyl** [comment] 2018-07-22 12:34
Bug confirmed, caused by:

https://github.com/angular/angular/blob/7960d1879d87f1d9e4f7f202423960d874a6a08f/packages/core/src/di/injectable.ts#L108

Because static properties also got inherited.

Which is technically a regression (only for RC) caused by https://github.com/angular/angular/pull/22943.

**Comment by kemsky** [comment] 2018-07-23 15:38
@trotyl , which versions are affected?

**Comment by trotyl** [comment] 2018-07-23 16:38
@kemsky From 6.0.0-rc.1, but only for `providedIn`.

**Comment by trotyl** [comment] 2018-08-29 02:06
Duplicate of https://github.com/angular/angular/issues/24011

**Closed** 2018-09-11 14:10 UTC
Labels: comp: core & compiler, freq2: medium, jira-sync, severity5: regression, type: bug/fix
