### ISSUE TITLE
ng build -aot -prod    JavaScript heap out of memory

### ISSUE THREAD

**Issue by gofreddo** [angular/angular#20162] opened 2017-11-03 17:19 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

ng build -aot -prod                                                                 11.2s  Fri Nov  3 11:11:59 2017

<--- Last few GCs --->

[9896:0x103000000]   151354 ms: Mark-sweep 1399.6 (1625.7) -> 1399.6 (1625.7) MB, 379.7 / 0.0 ms  allocation failure GC in old space requested
[9896:0x103000000]   151834 ms: Mark-sweep 1399.6 (1625.7) -> 1399.5 (1560.7) MB, 480.4 / 0.0 ms  last resort GC in old space requested
[9896:0x103000000]   152295 ms: Mark-sweep 1399.5 (1560.7) -> 1399.5 (1537.2) MB, 460.2 / 0.0 ms  last resort GC in old space requested

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x1dfeb40a5ec1 <JSObject>
    1: SparseJoinWithSeparatorJS(aka SparseJoinWithSeparatorJS) [native array.js:~44] [pc=0x2709e7322689](this=0x1dfe01e02311 <undefined>,p=0x1dfeb8aff7c9 <JSArray[1585]>,w=0x1dfeb8aff7e9 <JSArray[1585]>,q=1585,z=0x1dfe01e02421 <false>,A=0x1dfeb40ef1b9 <String[1]:  >)
    2: DoJoin(aka DoJoin) [native array.js:~95] [pc=0x2709e72a13bb](this=0x1dfe01e02311 <undefined>,p=0x1dfeb8aff7c9 <JSArray[158...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/usr/local/bin/node]
 2: node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [/usr/local/bin/node]
 3: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/usr/local/bin/node]
 4: v8::internal::Factory::NewRawTwoByteString(int, v8::internal::PretenureFlag) [/usr/local/bin/node]
 5: v8::internal::Runtime_SparseJoinWithSeparator(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/local/bin/node]
 6: 0x2709e5f0463d
fish: 'ng build -aot -prod' terminated by signal SIGABRT (Abort)

## Expected behavior

A build

## Minimal reproduction of the problem with instructions

1. ng build -aot -prod

## Environment

<pre><code>
Angular version: 5.0.0

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.9.0  
- Platform:  Mac 

Others:

</code></pre>

**Comment by ericmartinezr** [comment] 2017-11-03 17:22
https://github.com/angular/angular-cli/issues/5618

**Comment by gkalpak** [comment] 2017-11-03 17:32
Thx @ericmartinezr. Closing as duplicate of angular/angular-cli#5618.

**Closed by gkalpak** 2017-11-03 17:32 UTC

**Comment by gofreddo** [comment] 2017-11-03 17:37
The difference with angular/angular-cli#5618 is that angular/angular-cli#5618 is on Angular 4 and this is Angular 5.
