### ISSUE TITLE
Scroll position restoration does not work when route initialy does not have a scrollbar.

### ISSUE THREAD

**Issue by robindijkhof** [angular/angular#36774] opened 2020-04-22 21:25 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/router

### Is this a regression?

 No.

### Description

Consider route A which navigates to route B.

Case A:
- The component on Route A fetches some data, therefore initially there is no scrollbar.
- The component has fetched the data and displays it in a list. There is a scrollbar present now.
- The user scrolls to the bottom and selects an item which brings the user to Route B.
- The user clicks on the back button and returns to Route A.
- The user is now at the top of the page instead of the bottom.

I'd expect the user to be at the bottom of the page where he left.
Now consider case B:
- The component on Route A fetches some data. In contradiction to case A, there is a scrollbar present because the content does not fit for some reason.
- The component has fetched the data and displays it in a list. The scrollbar is still present but smaller now because there is more content.
- The user scrolls to the bottom and selects an item which brings the user to Route B.
- The user clicks on the back button and returns to Route A.
- The user is now at the bottom of the page as expected.

These two cases do not produce the same result. I'd expect they do.

## 🔬 Minimal Reproduction

 https://stackblitz.com/edit/angular-6stgdl
For case A:
- Select the heroes tab.
- Notice there is no scrollbar
- Wait for the heroes to load.
- Scroll to the bottom and select a hero
- Press the "go back" button
- Wait for the heroes to load.
- You are at the top of the heroes list now

Case B:
- Select the heroes tab.
- Decrease your window size so a scrollbar is visible BEFORE the heroes are loaded. (See my screenshot)
- Scroll to the bottom
- Wait for the heroes to load.
- Scroll to the bottom and select a hero
- Press the "go back" button
- Wait for the heroes to load.
- You are at the bottom of the heroes list now

<img width="414" alt="scroll" src="https://user-images.githubusercontent.com/22224763/80035157-d98a6f80-84ef-11ea-8e41-a7ceb9c5fad5.png">

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Lastest 9.0.7

</code></pre>

**Anything else relevant?**

This happens on both chrome and firefox

**Comment by atscott** [comment] 2020-05-27 22:13
duplicate of #30139

**Closed by atscott** 2020-05-27 22:13 UTC
Labels: comp: router, freq1: low, severity3: broken, triage #1, type: bug/fix
