### ISSUE TITLE
bug(router): View Encapsulation attribute not applied to routed component

### ISSUE THREAD

**Issue by Karasuni** [angular/angular#20558] opened 2017-11-21 12:44 UTC
## I'm submitting a...
<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior
The default [View Encapsulation](https://angular.io/guide/component-styles#view-encapsulation) behavior is set to `Emulated`. The preprocessor will attach custom attributes to the DOM elements. The following component definition:
```html
  <!-- src/app/app.component.html -->
  <app-header></app-header>
  <app-navbar></app-navbar>
  <router-outlet></router-outlet>
  <app-footer></app-footer>
```
Results in this generated code:
```html
  <!-- dist/index.html -->
  <app-root _nghost-c0 ng-version="5.0.2">
    <app-header _ngcontent-c0 _nghost-c1>...</app-header>
    <app-navbar _ngcontent-c0 _nghost-c2>...</app-navbar>
    <router-outlet _ngcontent-c0></router-outlet>
    <app-home _nghost-c6>...</app-home>
    <app-footer _ngcontent-c0 _nghost-c3>...</app-footer>
  </app-root>
```
Router dynamically injected the component `app-home` right after `router-outlet` but did not apply the host's reference attribute `_ngcontent-c0`.

The view encapsulated CSS for this component `app.component.scss` will append the host's reference attribute `[_ngcontent-c0]` to all selectors. As a result none of the CSS defined in `app.component.scss` will apply to the routed component:
```scss
  app-home[_ngcontent-c0] { /* selector after processing will never select routed element */
    background: greenyellow;
  }
```
It is impossible to select a routed component in the host's css using the default view encapsulation behavior.

## Expected behavior
Router should apply the host's component reference (`_ngcontent-c0`) to routed components as the routed component for consistency.

## Minimal reproduction of the problem with instructions
A full example of the issue can be found in [this application](https://stackblitz.com/edit/angular-css-grid-holy-grail).

## Context
Using CSS grid you can layout using `grid-area` definitions to assign a 'function' to each component in a page (e.g.: `grid-area: content;`). This requires being able to select each component. You could suggest to apply the definition in each of the routed component's `:host` but that would break other parts of the application and not be proper separation of concerns. ([See question on StackOverflow](https://stackoverflow.com/questions/47356648/apply-css-to-routed-components))

## Environment
<pre><code>Angular version: 5.0.2</code></pre>

**Comment by Karasuni** [comment] 2018-02-12 21:16
Can I ask how the backlog is curated?

**Comment by trotyl** [comment] 2018-07-06 10:35
Duplicate of https://github.com/angular/angular/issues/12215

**Comment by pkozlowski-opensource** [comment] 2020-05-26 08:58
It is indeed duplicate of  #12215, thank you @trotyl !

**Closed by pkozlowski-opensource** 2020-05-26 08:58 UTC
Labels: comp: core, comp: router, core: CSS encapsulation, freq2: medium, severity3: broken, type: bug/fix
