### ISSUE TITLE
Dynamic Components does not inject @Host parent

### ISSUE THREAD

**Issue by fkolar** [angular/angular#41635] opened 2021-04-15 07:26 UTC
# 🐞 bug report

### Description

In dynamic env. where we try to pre-instantiate components and add them to view, we try to also rely on some basic Angular functionality and ability to maintain all the injection.

Having this sample The child `inject` parent `@Host component  `- there is no issue here
```
<app-parent>
  <app-child></app-child>
</app-parent>
```
but in this second case it is not happening. There is not relation. Even it should as Angular needs to figure this out from current context.
```
<app-parent>
  <ng-container #vc></ng-container>
</app-parent>
```
Should  we `Injector.create` ourself for such cases to make it somehow work with `@Host` or there are some other ways ?

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-ivy-t3xq4p?file=src/index.html

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular: 11.2.9
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: <error>

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.8
@angular-devkit/build-angular   0.1102.8
@angular-devkit/core            11.2.8
@angular-devkit/schematics      11.2.8
@angular/cdk                    11.2.8
@angular/cli                    11.2.8
@angular/material               11.2.8
@schematics/angular             10.1.7
@schematics/update              0.1102.8
ng-packagr                      11.2.4
rxjs                            6.6.7
typescript                      4.1.5

</code></pre>

**Comment by destus90** [comment] 2021-04-15 09:10
You could create `ChildCmp` with `ViewContainerRef.injector`

https://stackblitz.com/edit/angular-ivy-rw8tdx?file=src%2Fapp%2Fapp.component.ts

**Comment by fkolar** [comment] 2021-04-16 11:13
I though that we have a solution already and for this simple case it works but it looks like it is failing with:

Assuming we need to work with modules, which is the case most of the time in realistic scenarios

```
const module = this.compiler.compileModuleAndAllComponentsSync(ChildModule);
    const moduleNgModuleRef = module.ngModuleFactory.create(this.vc.injector);
    console.log(module.componentFactories[0]);
    const cmdFactory = module.componentFactories[0];
    const component: ComponentRef<ChildModule> = this.viewContainer.createComponent(cmdFactory, null,
      this.vc.injector, [[]], moduleNgModuleRef);

```

**Comment by jelbourn** [comment] 2021-04-16 20:40
@fkolar what are you attempting to accomplish by using `@Host`? I think the behavior you want would be achieved by not specifying `@Host` and also not passing the `AppComponent` injector when creating the child component: https://stackblitz.com/edit/angular-ivy-7tpbl6?file=src%2Fapp%2Fapp.component.ts

**Comment by fkolar** [comment] 2021-04-17 15:39
The thing is I am working with existing components that has this relation. 

`FormGroupComponent`
     `FormFieldComponent`   -> FormField inject Its parent FormGroup and register it self. 
          `FormControl` (Inputs components ). -> FormControls inject its host which is FormField and register itself   

_(We had to get away from ViewChildren, but its different story ;-( )_   

Here we are using `@Host` to get hold of host component. Now, we instantiate all this dynamically using above code (that works with modules), and when I inject e.g. formControl into FormField it does not inject properly its host parent. 

Even if I use injector from viewcontainer.  In dynamic environment it does not work correctly. 
```

const module = this.compiler.compileModuleAndAllComponentsSync(ChildModule);
    const moduleNgModuleRef = module.ngModuleFactory.create(this.vc.injector);
    console.log(module.componentFactories[0]);
    const cmdFactory = module.componentFactories[0];
    const component: ComponentRef<ChildModule> = this.viewContainer.createComponent(cmdFactory, null,
      this.vc.injector, [[]], moduleNgModuleRef);

```

So the issue is:  In simple scenario using directly `ComponentFactoryResolv`. as @destus90 showed me it works, but with Modules it does not. 

But let me give it a try not passing injector at all.

**Comment by alxhub** [comment] 2022-03-28 23:33
I'm going to close this as the reproduction given is not indicative of the actual problem (since its use of `@Host` and overriding of the injector is incorrect - injecting the parent works without those). If the actual issue arises in a dynamic form scenario, please open a new issue with a reproduction that illustrates the specific problem.

**Closed by alxhub** 2022-03-28 23:33 UTC
Labels: comp: core, core: di, core: dynamic view creation, needs clarification
