### ISSUE TITLE
Injector in Dynamic Component Loader doesn't respect Interface

### ISSUE THREAD

**Issue by jrelink** [angular/angular#33024] opened 2019-10-07 10:03 UTC
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/core

### Is this a regression?
No. I detected this bug in angular 7.2.15, but it is still present.

### Description
The implementation of Injector used in Dynamic Component Loader doesn't respect de the new interface of Injector.

This cause the imposibility of use flags in retrieving an instance from the injector. 

You can see the code referenced here:
https://github.com/angular/angular/blob/master/packages/core/src/view/refs.ts#L337
https://github.com/angular/angular/blob/master/packages/core/src/di/injector.ts#L59-L60

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-yd2tpn

## 🔥 Exception or Error
<pre><code>AppComponent_Host.ngfactory.js? [sm]:1 ERROR NullInjectorError: StaticInjectorError(AppModule)[InjectionToken TEST]: 
  StaticInjectorError(Platform: core)[InjectionToken TEST]: 
    NullInjectorError: No provider for InjectionToken TEST!
    at NullInjector.get (https://angular-yd2tpn.stackblitz.io/turbo_modules/@angular/core@8.0.0/bundles/core.umd.js:1310:29)
    at resolveToken (https://angular-yd2tpn.stackblitz.io/turbo_modules/@angular/core@8.0.0/bundles/core.umd.js:1548:28)
    at tryResolveToken (https://angular-yd2tpn.stackblitz.io/turbo_modules/@angular/core@8.0.0/bundles/core.umd.js:1492:20)
    at StaticInjector.get (https://angular-yd2tpn.stackblitz.io/turbo_modules/@angular/core@8.0.0/bundles/core.umd.js:1396:24)
    at resolveToken (https://angular-yd2tpn.stackblitz.io/turbo_modules/@angular/core@8.0.0/bundles/core.umd.js:1548:28)
    at tryResolveToken (https://angular-yd2tpn.stackblitz.io/turbo_modules/@angular/core@8.0.0/bundles/core.umd.js:1492:20)
    at StaticInjector.get (https://angular-yd2tpn.stackblitz.io/turbo_modules/@angular/core@8.0.0/bundles/core.umd.js:1396:24)
    at resolveNgModuleDep (https://angular-yd2tpn.stackblitz.io/turbo_modules/@angular/core@8.0.0/bundles/core.umd.js:18491:33)
    at NgModuleRef_.get (https://angular-yd2tpn.stackblitz.io/turbo_modules/@angular/core@8.0.0/bundles/core.umd.js:19180:20)
    at Object.resolveDep (https://angular-yd2tpn.stackblitz.io/turbo_modules/@angular/core@8.0.0/bundles/core.umd.js:19551:49)</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>Angular CLI: 7.3.9
Node: 10.16.1
OS: win32 x64
Angular: 7.2.15
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.10.7
@angular-devkit/build-angular      0.10.7
@angular-devkit/build-ng-packagr   0.8.9
@angular-devkit/build-optimizer    0.10.7
@angular-devkit/build-webpack      0.10.7
@angular-devkit/core               7.0.7
@angular-devkit/schematics         7.3.9
@angular/cdk                       7.0.0
@angular/cli                       7.3.9
@ngtools/json-schema               1.1.0
@ngtools/webpack                   7.0.7
@schematics/angular                7.3.9
@schematics/update                 0.13.9
ng-packagr                         4.7.1
rxjs                               6.5.2
typescript                         3.2.4
webpack                            4.19.1</code></pre>

**Comment by trotyl** [comment] 2019-10-07 10:15
Duplicate of https://github.com/angular/angular/issues/31776

**Comment by AndrewKushnir** [comment] 2019-10-08 01:02
@jrelink thanks for creating a ticket. As @trotyl mentioned, it looks like a duplicate of existing issue #31776. I'm closing this ticket, please subscribe to receive further updates in #31776. Thank you.

**Closed by AndrewKushnir** 2019-10-08 01:02 UTC
