### ISSUE TITLE
Need a way to resetConfig of routes managed by a lazyloaded module

### ISSUE THREAD

**Issue by gilsdav** [angular/angular#52416] opened 2023-10-27 13:45 UTC
### Which @angular/* package(s) are relevant/related to the feature request?

@angular/router@>=16.2.5

### Description

Hello,

My library to make routes translatable doesn't work anymore from 16.2.5.
I can see now `_loadedRoutes` is populate on lazyloading. Before it was populated on Initializer.

I totally understand the change but this change will create a feature request:
We can use `router.resetConfig(routes)` in "root" Router but can you make this function run for child routes ?
So `router.resetConfig(lazyloadedRoutes)` into lazyloaded module has to update only its routes not global routes.
In the same way `router.config` need to return only routes from lazyloaded module and not the entire config.

## State
Module 1 contains routes:
```
[
  {
      path: '',
      component: HomeComponent
  },
  {
     path: 'two',
     loadChildren: import(./my.module.ts).then(m => m.MyModule)
  }
]
```
Module 2 contains routes:
```
[
  {
      path: '',
      component: ComponentTwo
  },
  {
     path: 'three',
     component: ComponentThree
  }
]
```
### config
Expected return of `router.config` into AppModule:
```
[
  {
      path: '',
      component: HomeComponent
  },
  {
     path: 'two',
     loadChildren: import(./my.module.ts).then(m => m.MyModule)
  }
]
```
Expected return of `router.config` into MyModule
```
[
  {
      path: '',
      component: ComponentTwo
  },
  {
     path: 'three',
     component: ComponentThree
  }
]
```
### config
Reset config into AppModule:
```
router.resetConfig([
  {
      path: '',
      component: HomeComponent
  },
  {
     path: 'two',
     loadChildren: import(./my.module.ts).then(m => m.MyModule)
  }
])
```
Reset config into MyModule:
```
router.resetConfig([
  {
      path: '',
      component: ComponentTwo
  },
  {
     path: 'three',
     component: ComponentThree
  }
])
```

### Alternatives considered

Create an other way to resetConfig of routes managed by a lazyloaded module

**Comment by atscott** [comment] 2023-10-27 20:01
> I can see now _loadedRoutes is populate on lazyloading. Before it was populated on Initializer.

I don't quite understand what you mean here. Could you explain this more? 

I would like to understand this request more in general. I'm not understanding why you need to reset the config for loaded routes or what behavior changed in 16.2.5. Can you show an example?

If the issue is that you need to be able to provide routes dynamically, you can do this by providing the `ROUTES` token in your lazy loading module:

```
@NgModule({
  providers: [{provide: ROUTES, useFactory: () => ...}]
})
export class MyModule {}
```

If the issue is that you need to provide the routes asynchronously and need to be able to inject services to do so, I believe that would be covered in this request: #51532.

In general, the proposed expectation isn't possible so I'd like to understand the problem more so we can find a more suitable solution.

**Comment by gilsdav** [comment] 2023-10-27 21:17
I don't realy know what changed in this version but this is a behavior result observed.

So for context we are talking about https://github.com/gilsdav/ngx-translate-router.
I'm debugging why it stopped working since this version of Angular

This library translate routes in runtime (not like angular/localise). The "why" of runtime change is needed is an other point but it's because some countries has multiple official languages and need to switch without loose inprogress work.

This feature request comes from a question "why can WE only change Root module routes using resetConfig ?".

Using a Factory will not allow me to change routes at runtime.

How it works now in the library ? It uses _loadedRoutes when there is a loadChildren but it seems to be populated later than in previous angular version.

**Comment by atscott** [comment] 2023-10-27 21:57
> Using a Factory will not allow me to change routes at runtime.

It might not allow you to change them in the way you want but factories _are_ executed at runtime. Because I'm still not understanding the technical reasons for what you're doing and why you're doing them, it's hard for me to help find alternatives.

> The "why" of runtime change is needed is an other point but it's because some countries has multiple official languages and need to switch without loose inprogress work.

> This feature request comes from a question "why can WE only change Root module routes using resetConfig ?".

I understand that this is a request based on the current design and business requirements of the library. I'm unfortunately not following the technical details of the current implement. Can you describe this more? What happens in the application that causes you to reset the config? Why does the config need to be reset in specific lazy loaded modules? Why is it not sufficient to locate and modify those routes as part of the larger `router.config`? 

How does making `resetConfig` work for at a lazy loaded module injector level solve the issue? I'm not following how this would help.


> It uses _loadedRoutes when there is a loadChildren but it seems to be populated later than in previous angular version.

I see that `ngx-translate-router` is already using `resetConfig`, traversing routes in the `init`, and directly modifying `Route` configs.  If the issue is that lazy loaded children aren't available yet, is it not enough to just reprocess the whole route tree once they _are_ available and update any routes that don't have the translation transform and call `resetConfig` again? 

On another note, I'm not seeing any commits between 16.2.4 and 16.2.5 that might have caused any difference in behavior. Are you sure you've identified the correct version? https://github.com/angular/angular/compare/16.2.4...16.2.5

**Comment by gilsdav** [comment] 2023-11-06 07:48
Ok so why and when do I need this resetConfig ?

I got lazy-loaded language files (en.json, fr.json...) and I need a translated route.

Default angular route: **/home**
Expected EN route: **/en/home**
Expected FR route: **/fr/accueil**

When I call `translate.use('fr')` for example,  /en/home become /fr/accueil without any reload.

So, I use resetConfig before initial route navigation (because "/home" must not be usable, each time I call `translate.use(...)` and when a `navigationStart` is called and the language into the route is different.

Steps:

- ngx-translate load the language file
- ngx-translate-router use these translations to translate routes config
- ngx-translate-router cancel current navigation if one is started (but keep destination in memory)
- ngx-translate-router resetConfig with translated routes
- ngx-translate-router restart a previous navigation with new url translate (for example it know how to translate `/en/home` to `/fr/accueil`

How I translate lazy-loaded route ? I translate _loadedRoutes.

I tried to translate and resetConfig on lazy-loaded module constructor and it works with a setTimeout(..., 1000). `_loadedRoutes` doesn't exist without the setTimeout so it can't works for first navigation to this module.

**Comment by atscott** [comment] 2023-11-06 16:53
> I tried to translate and resetConfig on lazy-loaded module constructor and it works with a setTimeout(..., 1000). _loadedRoutes doesn't exist without the setTimeout so it can't works for first navigation to this module.

Lazy loading for a route will be complete when the `RoutesRecognized` event emits: https://github.com/angular/angular/blob/63777d20d99ca6206420d545182a754b8f2dc2d8/packages/router/src/navigation_transition.ts#L448-L452
So in your module constructor, you could subscribe to the router events and wait for that instead of using a `setTimeout`.

> Why am I asking for other resetConfig ? Because I don't think it's a good think I need to translate _loadedRoutes private element. If resetConfig was scoped, it will be possible change route config of a lazyloaded module. I currently consider them incompatible.

Just to confirm, you do have everything working, but need to access the internal `_loadedRoutes` to achieve it, right? So another way of solving this would be to provide a way to access the loaded routes in the public API? That request is tracked in https://github.com/angular/angular/issues/40010


----
Scoping `resetConfig` to an injector isn't possible without passing in the injector. So an API _could_ be `resetConfig(routes, environmentInjector)` and the reset could look for the route with that injector and reset the children under that. That's probably the easiest option for this specific use-case, but I'm not sure how generally useful it is. 

Another option might be `resetConfig(routes, route)` where this would find the given route in the existing config and reset its children. This seems better in that it's easier to explain and more intuitive, but I think it might actually be harder for you to achieve what you want with that since you don't know what route your loaded config is a child of.

**Comment by atscott** [comment] 2023-11-30 20:06
Based on my understanding of what's been discussed, closing as a duplicate of https://github.com/angular/angular/issues/40010

**Closed by atscott** 2023-11-30 20:06 UTC
Labels: feature, area: router, feature: votes required
