### ISSUE TITLE
Can log activity of Change Detection sub-system?

### ISSUE THREAD

**Issue by rhedin** [angular/angular#21167] opened 2017-12-25 20:28 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I have some code that someone else wrote.  Immutable objects have not been used, so Angular checks the whole subtree of thousands of rows.  (It's a table.)  There are quite a few data-communications between master components and sub components. 

It's hard to get a handle on.  It would be nice if Angular told me "Here's why I went lower in the tree."

## Expected behavior

For each property of each component, Angular would say "I compared old and new, and found them to be the same (or different)."  Then "I went down to the next lower component."

With that information, I could quickly identify why Angular wants to reconstruct everything, and change only that part, leaving the rest of the forest untouched. 

## What is the motivation / use case for changing the behavior?

One of the complaints about Angular (and about all the "magic" frameworks) is that you can't tell what it's doing, and sometimes it matters.  This would move Angular up in the competition.  And help me be a successful developer.

## Environment

Any, but mine is Windows and Macintosh, using Internet Explorer and Chrome. 

<pre><code>
Angular version: X.Y.Z

Browser:
- [x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [x ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by Toxicable** [comment] 2017-12-26 01:14
I like this idea.
Thinking about API I think enabling it on a per component level would be the best, application wide would clutter things up a lot.
So maybe in the @Component() decorator such as 
```
@Component({
  selector: 'my-comp',
  template: ` ... template`,
  enableChangeDetectionTracing: true
})
```
In this scenario it would be enabled during dev but internally it still have to pass the `isDev` check so that the tracing code can be tree shaken for prod builds

Another way could be to have a service injected such as 
```
constructor(
  private readonly cdLogger: ChangeDetectionLogger
) {
  this.cdLogger.logs$.subscribe(console.log)
}
```
then during a prod build a noop version could be provided

**Comment by pkozlowski-opensource** [comment] 2019-03-17 08:25
This is a duplicate of #24612, already implemented in ivy. Closing as a duplicate (#24612 will be closed when ivy is switched on by default)

**Comment by pkozlowski-opensource** [comment] 2019-03-17 08:28
Hmm, scratch this, it is _not_ a duplicate... sorry for the confusion.

**Comment by alxhub** [comment] 2021-07-17 01:30
I believe this is addressed by Ivy though, in the sense that stepping through the actual change detection code in a debugger is a feasible and useful way to follow data flow in an application.

**Closed by alxhub** 2021-07-17 01:30 UTC
Labels: comp: core, core: change detection, core: debug tools, feature, insufficient votes, votes required
