### ISSUE TITLE
strictNullChecks still not supported in 4.1

### ISSUE THREAD

**Issue by sebek64** [angular/angular#16357] opened 2017-04-26 19:43 UTC
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Compilation produces the following with strictNullChecks enabled:

node_modules/@angular/forms/src/model.d.ts(374,27): error TS2459: Type '{ onlySelf?: boolean | undefined; emitEvent?: boolean | undefined; emitModelToViewChange?: boolea...' has no property 'onlySelf' and no string index signature.
node_modules/@angular/forms/src/model.d.ts(374,37): error TS2459: Type '{ onlySelf?: boolean | undefined; emitEvent?: boolean | undefined; emitModelToViewChange?: boolea...' has no property 'emitEvent' and no string index signature.
node_modules/@angular/forms/src/model.d.ts(374,48): error TS2459: Type '{ onlySelf?: boolean | undefined; emitEvent?: boolean | undefined; emitModelToViewChange?: boolea...' has no property 'emitModelToViewChange' and no string index signature.
node_modules/@angular/forms/src/model.d.ts(374,71): error TS2459: Type '{ onlySelf?: boolean | undefined; emitEvent?: boolean | undefined; emitModelToViewChange?: boolea...' has no property 'emitViewToModelChange' and no string index signature.
node_modules/@angular/forms/src/model.d.ts(421,29): error TS2459: Type '{ onlySelf?: boolean | undefined; emitEvent?: boolean | undefined; } | undefined' has no property 'onlySelf' and no string index signature.
node_modules/@angular/forms/src/model.d.ts(421,39): error TS2459: Type '{ onlySelf?: boolean | undefined; emitEvent?: boolean | undefined; } | undefined' has no property 'emitEvent' and no string index signature.
node_modules/@angular/forms/src/model.d.ts(544,9): error TS2459: Type '{ onlySelf?: boolean | undefined; emitEvent?: boolean | undefined; } | undefined' has no property 'onlySelf' and no string index signature.
node_modules/@angular/forms/src/model.d.ts(544,19): error TS2459: Type '{ onlySelf?: boolean | undefined; emitEvent?: boolean | undefined; } | undefined' has no property 'emitEvent' and no string index signature.
node_modules/@angular/forms/src/model.d.ts(571,9): error TS2459: Type '{ onlySelf?: boolean | undefined; emitEvent?: boolean | undefined; } | undefined' has no property 'onlySelf' and no string index signature.
node_modules/@angular/forms/src/model.d.ts(571,19): error TS2459: Type '{ onlySelf?: boolean | undefined; emitEvent?: boolean | undefined; } | undefined' has no property 'emitEvent' and no string index signature.
node_modules/@angular/forms/src/model.d.ts(607,25): error TS2459: Type '{ onlySelf?: boolean | undefined; emitEvent?: boolean | undefined; } | undefined' has no property 'onlySelf' and no string index signature.
node_modules/@angular/forms/src/model.d.ts(607,35): error TS2459: Type '{ onlySelf?: boolean | undefined; emitEvent?: boolean | undefined; } | undefined' has no property 'emitEvent' and no string index signature.
node_modules/@angular/forms/src/model.d.ts(711,29): error TS2459: Type '{ onlySelf?: boolean | undefined; emitEvent?: boolean | undefined; } | undefined' has no property 'onlySelf' and no string index signature.
node_modules/@angular/forms/src/model.d.ts(711,39): error TS2459: Type '{ onlySelf?: boolean | undefined; emitEvent?: boolean | undefined; } | undefined' has no property 'emitEvent' and no string index signature.
node_modules/@angular/forms/src/model.d.ts(735,31): error TS2459: Type '{ onlySelf?: boolean | undefined; emitEvent?: boolean | undefined; } | undefined' has no property 'onlySelf' and no string index signature.
node_modules/@angular/forms/src/model.d.ts(735,41): error TS2459: Type '{ onlySelf?: boolean | undefined; emitEvent?: boolean | undefined; } | undefined' has no property 'emitEvent' and no string index signature.
node_modules/@angular/forms/src/model.d.ts(770,25): error TS2459: Type '{ onlySelf?: boolean | undefined; emitEvent?: boolean | undefined; } | undefined' has no property 'onlySelf' and no string index signature.
node_modules/@angular/forms/src/model.d.ts(770,35): error TS2459: Type '{ onlySelf?: boolean | undefined; emitEvent?: boolean | undefined; } | undefined' has no property 'emitEvent' and no string index signature.

**Expected behavior**

Compilation should not produce any errors.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 4.1.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** TypeScript 2.2.2

* **Node (for AoT issues):** `node --version` =   6.10.2

**Comment by amitport** [comment] 2017-04-27 05:49
duplicate of https://github.com/angular/angular/issues/15432

**Comment by vicb** [comment] 2017-04-27 09:26
Could you attach a minimal repro. Thanks.

/cc @mhevery

**Comment by sebek64** [comment] 2017-04-27 09:53
I'll try to prepare a repro case today.

**Comment by cyrilletuzi** [comment] 2017-04-27 13:29
I confirm this issue, repro is very simple, quite strange it hasn't been spot before release : 
- create a new project with Angular CLI
- just add `"strictNullChecks": true` in tsconfig.json
- `ng serve`

**Comment by mhevery** [comment] 2017-04-27 19:36
This is an issue with TypeScript. Looking for a workaround: https://github.com/Microsoft/TypeScript/issues/10078

**Closed** 2017-04-28 14:16 UTC
Labels: comp: core & compiler

**Comment by afnpires** [comment] 2017-05-10 10:32
As an fyi, the workaround in #16389 PR did not work for me.
Using Typescript 2.3.2 and Angular 4.1.1 still throws the following

```
ERROR in [at-loader] ./node_modules/@angular/forms/src/model.d.ts:166:20 
    TS2459: Type '{ onlySelf?: boolean | undefined; } | undefined' has no property 'onlySelf' and no string index signature.

ERROR in [at-loader] ./node_modules/@angular/forms/src/model.d.ts:176:22 
    TS2459: Type '{ onlySelf?: boolean | undefined; } | undefined' has no property 'onlySelf' and no string index signature.

ERROR in [at-loader] ./node_modules/@angular/forms/src/model.d.ts:185:18 
    TS2459: Type '{ onlySelf?: boolean | undefined; } | undefined' has no property 'onlySelf' and no string index signature.

ERROR in [at-loader] ./node_modules/@angular/forms/src/model.d.ts:195:21 
    TS2459: Type '{ onlySelf?: boolean | undefined; } | undefined' has no property 'onlySelf' and no string index signature.

ERROR in [at-loader] ./node_modules/@angular/forms/src/model.d.ts:201:20 
    TS2459: Type '{ onlySelf?: boolean | undefined; } | undefined' has no property 'onlySelf' and no string index signature.

ERROR in [at-loader] ./node_modules/@angular/forms/src/model.d.ts:210:14 
    TS2459: Type '{ onlySelf?: boolean | undefined; emitEvent?: boolean | undefined; } | undefined' has no property 'onlySelf' and no string index signatur
e.

ERROR in [at-loader] ./node_modules/@angular/forms/src/model.d.ts:210:24 
    TS2459: Type '{ onlySelf?: boolean | undefined; emitEvent?: boolean | undefined; } | undefined' has no property 'emitEvent' and no string index signatu
re.

ERROR in [at-loader] ./node_modules/@angular/forms/src/model.d.ts:221:13 
    TS2459: Type '{ onlySelf?: boolean | undefined; emitEvent?: boolean | undefined; } | undefined' has no property 'onlySelf' and no string index signatur
e.

ERROR in [at-loader] ./node_modules/@angular/forms/src/model.d.ts:221:23 
    TS2459: Type '{ onlySelf?: boolean | undefined; emitEvent?: boolean | undefined; } | undefined' has no property 'emitEvent' and no string index signatu
re.

ERROR in [at-loader] ./node_modules/@angular/forms/src/model.d.ts:244:29 
    TS2459: Type '{ onlySelf?: boolean | undefined; emitEvent?: boolean | undefined; } | undefined' has no property 'onlySelf' and no string index signatur
e.

ERROR in [at-loader] ./node_modules/@angular/forms/src/model.d.ts:244:39 
    TS2459: Type '{ onlySelf?: boolean | undefined; emitEvent?: boolean | undefined; } | undefined' has no property 'emitEvent' and no string index signatu
re.

ERROR in [at-loader] ./node_modules/@angular/forms/src/model.d.ts:275:49 
    TS2459: Type '{ emitEvent?: boolean | undefined; } | undefined' has no property 'emitEvent' and no string index signature.
```
