### ISSUE TITLE
ES2015 object assign doesn't work from template

### ISSUE THREAD

**Issue by jackiegit** [angular/angular#21093] opened 2017-12-19 14:56 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[X] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Angular doesn't work well with ES2015's object assign within function from template to component.
e.g:

<button (click)="clickMe({ data })"></button>
Doesn't work. An error with "Missing :" is pop up in console.

## Expected behavior
Instead of writing explicitly:
<button (click)="clickMe({ data : data })"></button>

Should work with:
<button (click)="clickMe({ data })"></button>

<pre><code>
Angular version: 5.1.0

Browser:
- [X] Chrome (desktop) version 60
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by ericmartinezr** [comment] 2017-12-19 15:04
https://github.com/angular/angular/issues/10277

**Comment by alxhub** [comment] 2017-12-19 17:59
Thanks for reporting this issue. However this issue is a duplicate of an existing issue #10277. Please subscribe to that issue for future updates.

**Closed by alxhub** 2017-12-19 17:59 UTC
