### ISSUE TITLE
HttpClient.action<T> should call T's constructor if class

### ISSUE THREAD

**Issue by steven-rothwell** [angular/angular#42102] opened 2021-05-14 18:40 UTC
I have an example of what I'm talking about here:  https://stackblitz.com/edit/angular-httpget-constructor?file=src/app/balls.component.ts

When I make the call httpClient.get<Volleyball[]>(url), the like named properties are filled with the data returned, but the Volleyball constructor is never called.  So, the readonly property is never set and ball.type is undefined.  Also, if tried calling a method sayBranch() on one of the balls returned, it get the error: "this.balls[0].sayBrand is not a function".

I've seen workarounds to pipe and map shallow or deep copies, but it doesn't seem right to have to do this manually.  It's such an odd thing to request an array of objects from an API, but not have the constructor called nor get to utilize the methods on that object.

**Comment by Airblader** [comment] 2021-05-14 21:18
This is impossible, because types don't exist at runtime. There is no constructor to be called.

**Comment by Airblader** [comment] 2021-05-14 21:27
Duplicate of #24456

**Comment by DaSchTour** [comment] 2021-05-15 12:46
@steven-rothwell it's maybe a bit off-topic, but from my experience with years of angular development, this architecture looks nice at first glance, but comes with a lot of issues in the long term. With large collections of Classes with getters and setters for additional properties you run into performance issues. You might discover issues with serialization and when using a state management you also get issues with mutability.

I would strongly recommend only using Interfaces in the HTTP layer and instead of functions inside the classes implement pipes that include the small computation or transformation. For larger stuff you might use services that put your data together. When using a state management you can use selectors that collect and transform data.

**Comment by steven-rothwell** [comment] 2021-05-15 23:28
@Airblader To me, I would think it would just use an empty constructor of the type that I give the http.get<T>.  It just seems incredibly odd to give it the type and for it to return something that isn't really an instance of that type.

@DaSchTour Now that I know of the shortcomings, I think I will start using interfaces in the http layer, like you said.  It will remind me that what is returned really isn't an instance of the type.

**Comment by Airblader** [comment] 2021-05-16 05:45
> I would think it would just use an empty constructor of the type

The type parameter currently isn't even required to _be_ callable at all, so introducing this would break virtually every single Angular app in existence.

But that's not the point. Even if you restrict the type parameter to be callable, types are erased at compile time. You cannot call a constructor of a generic type argument unless you explicitly pass a constructor function as an argument. 

If you don't understand what this means, try and implement the following method:

```
function create<T>(/* no arguments! */): T {
    // Implement this to create an instance of T
    // by actually calling a constructor
}
```

> It just seems incredibly odd to give it the type and for it to return something that isn't really an instance of that type.

The generic argument is a convenience type assertion. You're fetching data remotely, there isn't and can't ever be type safety for that: you're just assuming you know what the API will return.

Angular could simply type this `unknown`, and it would be entirely correct. However, that's not practical for applications to work with, and they'd just end up type asserting the response anyway. So Angular provides a generic which makes this type assertion a bit easier to use. As with any type assertion, the compiler cannot tell you whether the type is correct or not: you're telling it that you know it to be correct.

**Comment by alxhub** [comment] 2021-06-07 22:20
@Airblader is 100% correct. 

If we were designing `@angular/common/http` today, we would not use generics as a type assertion like this at all. Instead, we'd probably have the API accept a type guard, something like:


```typescript

function isUser(data: unknown): data is User {
  // Do something that checks whether `data` conforms to the `User` interface.
  return true;
}

httpClient.get('/user/123', {assertType: isUser}).subscribe(data => {
  // here, `data` would be of type `User` by virtue of the `assertType` function passed in.
});
```

This API is superior, since the user is promising that they've validated the return type as opposed to just declaring it (although in practice the difference can be minimal if needed). We might add this functionality at some point. It wasn't done that way originally because TypeScript didn't have this feature back when we first did the API.

**Closed by alxhub** 2021-06-07 22:20 UTC
Labels: comp: common/http

**Comment by Airblader** [comment] 2021-06-08 04:25
@alxhub Not import here, but if you were going to go for that, I'd rather not have any such feature on the API at all. Just return `unknown` and let the user narrow the type afterwards in the pipe.
