### ISSUE TITLE
Sequential CanDeactivate checks chain is not interrupted when one of the guards fails.

### ISSUE THREAD

**Issue by miguelleite** [angular/angular#25086] opened 2018-07-25 14:05 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Considering the following scenario, where we have a CanDeactivate guard per route:
- Root Route
    - Child Route A (w/ CanDeactivate)
        - Grandchild Route (w/ CanDeactivate)
    - Child Route B

Imagine that we have a call to a service in the Child Route A's canDeactivate. We are on the Grandchild Route. When trying to navigate to ChildRoute B, and Grandchild Route's CanDeactivate returns false, Child Route A's CanDeactivate is still executed.

## Expected behavior

When Grandchild Route's CanDeactivate returns false, Child Route A's CanDeactive is **not executed**.

I think the problem is on usage of `mergeMap` on [pre_activation.ts](https://github.com/angular/angular/blob/4648597d14e843f75c5e9dd761af740c1c27b5c0/packages/router/src/pre_activation.ts#L191).

## What is the motivation / use case for changing the behavior?

Improve performance and avoid code from upper route's canDeactivate to run when child route's canDeactivate returns false.

## Environment

<pre><code>Angular version: 6.0.9</code></pre>

**Comment by miguelleite** [comment] 2018-07-25 16:48
## Proposed Solution
Replacing approach for `runCanDeactivateChecks()` with:

<pre><code>private runCanDeactivateChecks(): Observable<boolean> {
    return from(this.canDeactivateChecks)
        .pipe(
            concatMap((check: CanDeactivate) => this.runCanDeactivate(check.component, check.route)),
            takeWhile((result: boolean) => result === true),
            reduce((acc: number) => ++acc, 0),
            map((canDeactivateCmpCount: number) => canDeactivateCmpCount === this.canDeactivateChecks.length),
        );
}</pre></code>

**Comment by jasonaden** [comment] 2018-09-20 23:08
@miguelleite Thanks for this issue. However, the current behavior is intended. The reason `mergeMap` is used is specifically so the guards are run async. We don't currently have any APIs that allow you to create guards that depend on each other. Therefore generally the most efficient way is to run them all at once.

Think about a scenario where you have routes such as `root -> child -> grandchild` and each has a `CanDeactivate` guard that takes 1 second to run. Under the current implementation the total time to resolve the guards would be 1 second. With a change to `concatMap` it would be 3 seconds.

There may be some APIs we could add in the future to help with this. If you want to file a feature request to allow configuration of the operator used for guards, that might be something we could do. And it would be relatively simple to implement.

But since it's currently working as intended, I'll close this bug report.

**Closed by jasonaden** 2018-09-20 23:08 UTC
Labels: comp: router
