### ISSUE TITLE
Link to PipeApi  documention is not working on Pipes document Page

### ISSUE THREAD

**Issue by AnuragS202** [angular/angular#53468] opened 2023-12-09 10:38 UTC
### Describe the problem that you experienced

![image](https://github.com/angular/angular/assets/46848931/eb51c552-64f7-44dd-a07c-6b37c2f5ff72)
 
![image](https://github.com/angular/angular/assets/46848931/f62c9e8c-5c64-4850-9c67-4043c393203c)

Redirection  is not working

### Describe what you were looking for in the documentation

Pipe Api Documentation

### Describe the actions that led you to experience the problem

Clicking on the PipeApi documentation on Pipes document Page

### Add a screenshot if that helps illustrate the problem

![image](https://github.com/angular/angular/assets/46848931/3b705c22-839e-4b73-a3bc-6102dbc0e2a0)
![image](https://github.com/angular/angular/assets/46848931/a123414d-2bde-4b29-8ab8-55b1d81a9456)

**Comment by JoostK** [comment] 2023-12-09 11:22
Thanks for the report, closing as duplicate of https://github.com/angular/angular/issues/52968.

**Closed by JoostK** 2023-12-09 11:22 UTC
