### ISSUE TITLE
Link does not work.

### ISSUE THREAD

**Issue by AlekseiBud** [angular/angular#56238] opened 2024-06-03 15:28 UTC
### Describe the problem that you experienced

I follow the link 'https://angular.dev/api/localize/init/$localize' and I see the note 'Page Not Found 🙃'.

**Comment by moniuch** [comment] 2024-06-03 19:17
Same when following the banner link "Your watching archived 17..." for RouterLinkActive. It tries to land me at `https://angular.devhttps//angular.dev/api/router/RouterLinkActive` (https concatenated)

**Comment by JeanMeche** [comment] 2024-06-10 00:35
Dupe of #54388

**Closed by JeanMeche** 2024-06-10 00:35 UTC
Labels: P2, area: adev
