### ISSUE TITLE
SVG's viewBox attribute is converted to lower-case in templates

### ISSUE THREAD

**Issue by Tragetaschen** [angular/angular#5004] opened 2015-10-29 16:48 UTC
A component in 2.0.0-alpha.45 with
```
template: `<svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"></svg>`
```
arrives in the DOM as
```
<svg xmlns="http://www.w3.org/2000/svg" viewbox="0 0 100 100" version="1.1"></svg>
```

Note the lower-case `b` of `viewbox`. That way, the SVG doesn't render correctly.

As a workaround, I'm using an `ElementRef` in the constructor to manually set the correct property.

**Comment by pkozlowski-opensource** [comment] 2015-10-30 14:36
This is duplicate of https://github.com/angular/angular/issues/4506

**Closed by pkozlowski-opensource** 2015-10-30 14:36 UTC
