### ISSUE TITLE
MinLength Validator treats zero value as zero length

### ISSUE THREAD

**Issue by gtranter** [angular/angular#23749] opened 2018-05-07 15:14 UTC
https://github.com/angular/angular/blob/0cb4f12a7a57087ec4e8329a04d5dfc430764b45/packages/forms/src/validators.ts#L140

The statement `const length: number = control.value ? control.value.length : 0;` clearly returns zero for length if the value is zero. For numeric inputs, this is a problem.

**Comment by EmaGht** [comment] 2018-05-07 15:52
Why would you need a min length of 0? Isn't it the same as not having a MinLength Validator in the first place?

**Comment by gtranter** [comment] 2018-05-07 16:03
It's the value that is 0, not the min length. If the min length is 1, and the value is 0, the length is reported as 0 when it should be 1, and validation fails.

Its not really a big problem since min length 1 is the same as required. But the logic is wrong.

**Comment by ShaneMcGowan** [comment] 2018-07-29 17:54
Having this issue with reactive forms in Angular 5

If passing the value 0 to a form control with a validator of Validators.minLength(1), the form is invalid even though the value 0 should satisfy this minimum length as it is a character

**Comment by gtranter** [comment] 2018-07-30 19:00
@ShaneMcGowan I recommend you use Validators.required instead of Validators.minLength(1) as it is functionally equivalent and works properly.

**Comment by ShaneMcGowan** [comment] 2018-07-31 08:54
@gtranter Thanks, realised that after a short while and felt a bit silly, but still feel this issue should be fixed as it is quite odd behavior

**Comment by peterblazejewicz** [comment] 2018-08-04 12:06
I'm not sure if that should be managed by the framework 'autofocus' discovery(?) or feature detection(?) in SPAs.
See take on similar issue in React in DWB's article: 
[React and autofocus](https://davidwalsh.name/react-autofocus)
in summary:
```ts
@Component({
  selector: 'foo',
  template: `<input autofocus #backref>`,
  styles: [`h1 { font-family: Lato; }`]
})
export class FooComponent implements AfterViewInit {
  
  @ViewChild('backref') input: ElementRef;

  ngAfterViewInit() {
    this.input.nativeElement.focus();
  }
 }
```
Thanks!

**Comment by AndrewKushnir** [comment] 2020-04-22 00:19
Thanks for reporting this issue @gtranter. This issue is also discussed in #35591, so I'm closing this ticket as a duplicate of #35591. Please subscribe to the #35591 to receive further updates. Thank you.

**Closed by AndrewKushnir** 2020-04-22 00:19 UTC
Labels: comp: forms, freq1: low, hotlist: community-help, severity1: confusing, type: bug/fix
