### ISSUE TITLE
reflection-capabilities: parameters not inherited in es2015 for delegate constructors.

### ISSUE THREAD

**Issue by devversion** [angular/angular#27267] opened 2018-11-26 10:51 UTC
# 🐞 bug report

### Affected Package

@angular/core, ES2015 application; ReflectionCapabilities

### Is this a regression?

Nope, I think it's an issue that has been there for a long time.

### Description

Consider you have the following TypeScript file. Component _A_ extends another component _B_, but
does have a _public property_ defined in _A_.

Problem is that TypeScript in ES2015 mode creates a pass-through constructor _just in order to initialize the public property_ that causes the compiler to not inherit metadata from _B_.

Here is the code (below some more details about the issue)

```ts
@Component({
   ...
})
export class CdkBaseComponent {
   constructor (myService: SomeService) { ... }
}

@Component({
   ...
})
export class EnhancedComponent extends CdkBaseComponent {
   somePublicProperty = "my_default_value"
}
```

This TypeScript code turns into:

```js
// ...

export class EnhancedComponent extends CdkBaseComponent {
    constructor() {
        super(...arguments);
        this.somePublicProperty = "my_default_value";
    }
}
EnhancedComponent.decorators = [
    { type: Component, args: [{
                template: 'Enhanced Component Template',
            },] },
];
```

As you can see, TypeScript generated a pass-through constructor that just passes `...arguments` to the superclass. This means that `@angular/core` detects a constructor for the class and doesn't bother checking the superclass metadata.

Maybe there should be a ES2015 variant for delegate constructors?

https://github.com/angular/angular/blob/dc300c5c4172e1f8a6f3f84da6797e427e3626c0/packages/core/src/reflection/reflection_capabilities.ts#L20

## 🔬 Minimal Reproduction

Code above; or some easy to check-out TypeScript file with `tsconfig`.

https://gist.github.com/DevVersion/c84f196d68a549e3cbbaacdfccd3aab5

Run `ngc -p tsconfig-test.json` and inspect output.

## 🌍  Your Environment

**Angular Version:**

<pre>7.1.0</pre>

**Anything else relevant?**

This is an issue we run into with Angular Material and the CDK.

Potential abandoned fix or related issues: 

* https://github.com/angular/angular/pull/22642
* https://github.com/angular/angular/issues/13211

A workaround would be to explicitly create a constructor with parameters, but in the long-term, this makes the source-code unnecessarily large.

cc. @jelbourn

**Comment by trotyl** [comment] 2018-11-26 10:57
The direct fix for this issue is https://github.com/angular/angular/pull/24156.

**Comment by DevVersion** [comment] 2018-11-26 10:58
Thanks for sharing that. Unfortunately the "fix" seems to be full of merge conflicts.

**Comment by epelc** [comment] 2018-12-10 20:45
Is the realistic fix for this to wait until ivy is stable/usable? Totally understand and think it's a good idea to just wait. But I'd just like to confirm if that is the plan given how pesky this bug and related issues have been.

I assume you'd get smaller more efficient code from lack of polyfills. Also evergreen browsers are pretty common these days unless you are supporting ie11 for some reason I don't see why es2015 wouldn't be the default target.

**Comment by knoefel** [comment] 2018-12-12 17:30
I totally support @epelc 's further inquiry, because this bug affects many components from the angular material library (not just the ones referenced in this issue). So is waiting here the only option or could the direct fix #24156 mentioned by @trotyl be a possible, alternative solution?

**Comment by mokeev1995** [comment] 2019-02-25 22:43
Still waiting for fix...

**Comment by PodgeHeavin** [comment] 2019-02-26 19:13
+1 for this issue

**Comment by jheinnic** [comment] 2019-02-27 18:30
Just wasted at least twelve hours stumbling over this problem, convinced I must have somehow broken the injector load order.

**Comment by codeepic** [comment] 2019-02-28 14:29
I am getting this issue trying to use Angular Material Sidenav. 
I added MatSidenavModule to app.module imports and took the most basic example from Angular Material website and the error pops up.

**Comment by KensingtonTech** [comment] 2019-03-13 23:17
It would be super duper awesome if the team could provide an update on this, as it's potentially the last thing blocking adopting a es2015 target for quite a few people.  Apologies if this is above my station, but I see a fix was submitted in May of last year with a merge conflict - is there a reason that can't be worked through?  In any case, some confirmation that this has not slipped the minds of Angular devs would be great.

**Comment by petebacondarwin** [comment] 2019-05-09 19:52
Was this fixed by https://github.com/angular/angular/pull/29232?

**Closed** 2019-05-10 16:19 UTC
Labels: comp: core & compiler, fixed by Ivy, freq1: low, hotlist: material2, severity3: broken, type: bug/fix

**Comment by akvaliya** [comment] 2019-09-04 12:32
Is this resolved? Why this is closed? I am getting this error in my stepper page
 ```
main-es2015.4431906871944ba6f031.js:1 ERROR TypeError: Cannot read property 'markForCheck' of undefined
    at O._stateChanged (5-es2015.0794125b4a13565b3d57.js:1)
    at I.ngOnChanges (5-es2015.0794125b4a13565b3d57.js:1)
    at main-es2015.4431906871944ba6f031.js:1
    at main-es2015.4431906871944ba6f031.js:1
    at uw (main-es2015.4431906871944ba6f031.js:1)
    at jw (main-es2015.4431906871944ba6f031.js:1)
    at Object.eval [as updateDirectives] (_.ngfactory.js:310)
    at Object.updateDirectives (main-es2015.4431906871944ba6f031.js:1)
    at cw (main-es2015.4431906871944ba6f031.js:1)
    at yw (main-es2015.4431906871944ba6f031.js:1)
```

**Comment by petebacondarwin** [comment] 2019-09-04 12:51
@akvaliya - perhaps you have a new issue? Please can you create a new issue with steps on how to reproduce the error.
