### ISSUE TITLE
Malformed structure in component testing scenarios page

### ISSUE THREAD

**Issue by daiscog** [angular/angular#57433] opened 2024-08-17 13:02 UTC
### Describe the problem that you experienced

Incorrect looking "Query for the" heading and page navigation entry:

<img width="1689" alt="image" src="https://github.com/user-attachments/assets/a0705845-ad0d-4aad-83e8-5651c9adb752">

### Enter the URL of the topic with the problem

https://angular.dev/guide/testing/components-scenarios#query-for-the-h1

**Comment by JeanMeche** [comment] 2024-08-17 14:14
Hi, this is a dupe of #57384 !

**Closed by JeanMeche** 2024-08-17 14:14 UTC
