### ISSUE TITLE
Router.navigate Promise resolves to null. Why? When? Documentation?

### ISSUE THREAD

**Issue by benneq** [angular/angular#13745] opened 2017-01-02 11:57 UTC
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ x ] feature request
[ x ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I'm using `Router.navigate([], {queryParams:{foo:'bar'}})` for updating Query Params for the current Route (couldn't find any other way to do this). 
When I call `navigate` twice with the same queryParams the returned Promise resolves to `null`. Documentation only tell's about `true` and `false`.

**Expected behavior**

This should be part of the official docs, because this seems to be the only way to see if the queryParams have changed. `ActivatedRoute.queryParams` will not get triggered on `Router.navigate` if the queryParams don't change. Or is there any other way?

**Minimal reproduction of the problem with instructions**

```
constructor(route: ActivatedRoute, router: Router) {
  route.queryParams.subscribe(val => console.log("Query Params: ", val));
  router.navigate([], {queryParams:{foo:'bar'}}).then(val => console.log("Navigate: " + val));
  router.navigate([], {queryParams:{foo:'bar'}}).then(val => console.log("Navigate: " + val));
}
```

**What is the motivation / use case for changing the behavior?**

I want to call a method each time the queryParams change (either because of `Router.navigate` or because the user edited the URL manually). And each queryParams change will update a form. And each form update will set the new queryParams and trigger the method call. And there's also a button inside the form that will re-execute the method.
Though I need a reliable way to find out if queryParams changed.

**Please tell us about your environment:**

macOS Sierra, VS Code, npm, webpack, webpack-dev-server

* **Angular version:** 2.4.1 and 4.0.0-beta.1

Tested with 2.4.1 and 4.0.0-beta.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome 55 

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 2.0.10

* **Node (for AoT issues):** `node --version` =   
7.3.0

**Comment by zoechi** [comment] 2017-01-02 12:01
Please provide a Plunker for reproduction.

**Comment by DzmitryShylovich** [comment] 2017-01-02 12:15
Duplicate of https://github.com/angular/angular/issues/13340

**Comment by jasonaden** [comment] 2017-12-19 19:56
Closing as duplicate

**Closed by jasonaden** 2017-12-19 19:56 UTC
Labels: comp: router
