### ISSUE TITLE
[@angular/animations] ViewEncapsulation.ShadowDom breaks Angular Animations

### ISSUE THREAD

**Issue by nartc** [angular/angular#25672] opened 2018-08-25 21:47 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

As title mentioned, setting `ViewEncapsulation.ShadowDom` will cause the Animations not being able to run at all. Use-case: I'm building an Angular Element in conjunction with Angular Animations to see if the two play well together.

## Expected behavior

Setting `ShadowDom` Encapsulation strategy should work with Angular Animations.

## Environment

<pre><code>
Angular version: 6.1.4

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 10.x  
- Platform:  Mac

Others:

</code></pre>

**Comment by robwormald** [comment] 2018-09-05 21:49
triaged this with @matsko today, turns out this has never worked (!), even with the previous implementation of Shadow DOM. Definitely a bug.

**Comment by sandeepsuvit** [comment] 2019-05-23 07:31
Any fixes for this?

**Comment by bjornharvold** [comment] 2019-05-24 06:50
Yes, confirming. I have shadowdom on my web components and hammerjs specified in main.ts. Animations not working. If I remove shadowdom, animations work again.

**Comment by quekqh** [comment] 2019-07-31 09:54
I was using primeng sidebar and there was a sliding animation to open but the sliding animation to close broke. I restored the closing animation by inserting -webkit-transition: all 0.2s ease-in-out; hope it helps someone!

**Comment by toish** [comment] 2019-08-01 16:21
Can confirm we're seeing this as well, and our instance relies on a staggered animation so the work around is going to be messier than using the animations modules sadly :(

**Comment by rudolfolah** [comment] 2019-08-03 14:46
This is still an issue; I was using the shadowdom when trying to use Angular Elements and then realized that this was breaking it:

```ts
  encapsulation: ViewEncapsulation.ShadowDom,
```

It took quite a while to track that down, at this point if there isn't a fix there should be a console log error or something because it is something that can be detected within the component declaration 

```ts
if (encapsulation != emulated && animations.length > 0) {
  console.log('animations may not work properly');
}
```

**Comment by bjornharvold** [comment] 2019-08-13 07:41
Any update on this?

**Comment by pigeonvictor** [comment] 2019-08-29 07:57
Same for me, animations not working on a `ncapsulation: ViewEncapsulation.ShadowDom,`

**Comment by sinedoOo** [comment] 2019-09-16 11:14
Same for my project. ShadowDom disables "transition" property. I've added manually in CSS transition filed and it's started working, but it's ugly and it's working only for very primitive animations. Any update for this issue?

**Comment by alexeykostevich** [comment] 2019-09-30 08:10
Our team faced the same issue while building encapsulated Web Components for a browser extension.

Please, let me share some our findings — probably, this could be helpful to get this tricky issue fixed one day.

*Angular Animations* uses different mechanisms depending on a browser:
- *Web Animations* is used for browsers that support [Web Animations API](https://developer.mozilla.org/en-US/docs/Web/API/Element/animate).
- *CSS Keyframes* is used as a fallback for other browsers.

### Web Animations

When *Web Animations* is used, the issue is caused by the `WebAnimationsDriver` module. The module does not take into account shadow DOM in the implementation of the `containsElement` method.

As a result, *Angular* thinks that elements inside shadow DOM are not presented on a page (but just in memory) and skips animation.

https://github.com/angular/angular/blob/877f9ad7b9151324c4a94d3c80e7d37691bb9fd5/packages/animations/browser/src/render/transition_animation_engine.ts#L973

### CSS Keyframes
When *CSS Keyframes* is used, *Angular* inherits the same issue as with *Web Animations* (through some shared modules).

In addition to this, *Angular* adds generated CSS with keyframes to the `<head>` but not inside shadow DOM. As a result, these styles [are not visible](https://developers.google.com/web/fundamentals/web-components/shadowdom#host) for Web Component elements.

https://github.com/angular/angular/blob/877f9ad7b9151324c4a94d3c80e7d37691bb9fd5/packages/animations/browser/src/render/css_keyframes/css_keyframes_driver.ts#L107

**Comment by Schibum** [comment] 2019-12-02 14:13
@alexeykostevich thx. This monkey-patch fixes it for the web animations case:

```
import { ɵWebAnimationsDriver } from '@angular/animations/browser';
ɵWebAnimationsDriver.prototype.containsElement = (el1: any, el2: any) => {
  // Travel up the tree to the root node.
  let elem = el2;
  while (elem && elem !== document.documentElement) {
    if (elem === el1)
      return true;
    elem = elem.parentNode || elem.host;
  }
  return false;
};
```

**Comment by pianetarosso** [comment] 2020-02-05 13:58
Somebody knows how to apply the same solution for CSS Keyframes?

**Comment by nrwinner** [comment] 2020-04-12 23:53
Can confirm this is still an issue in Angular 9

**Comment by ray-kay** [comment] 2020-05-11 15:28
> _Angular Animations_ uses different mechanisms depending on a browser:
> 
> * _Web Animations_ is used for browsers that support [Web Animations API](https://developer.mozilla.org/en-US/docs/Web/API/Element/animate).
> * _CSS Keyframes_ is used as a fallback for other browsers.

Is there a way to force Angular to use Keyframes instead of Web Animations?

**Comment by OssprO** [comment] 2020-08-14 00:11
Still an issue in Angular 10

**Comment by Seshirantha** [comment] 2020-12-10 03:38
Still an issue in Angular with the following versions.
`"@angular/animations": "~10.0.2",`
`"@angular/cdk": "~10.1.3",`
`"@angular/common": "~10.0.2",`
`"@angular/compiler": "~10.0.2",`
`"@angular/core": "~10.0.2",`

**Comment by fbcarpinato** [comment] 2021-02-22 17:33
Still an issue on Angular 11

**Comment by JustDoItSascha** [comment] 2021-03-23 10:11
Any updates on this?

**Comment by petebacondarwin** [comment] 2021-03-23 13:34
I'm afraid there is no update on fixing this at the moment. I am at full capacity with getting the new linker stuff ready - but I will take a look at the linked PR when I get a chance. Perhaps early next week.

**Comment by jezmaghuyop** [comment] 2021-04-05 14:39
just encountered the same issue on Angular 11, we are currently utilizing Angular elements which needed to be in a ShadowDom View Encapsulation. I've been trying to make a simple animation work for two days now only to find out that having our components in a ShadowDom is what breaking the animation. 

this are my current versions

`"@angular/animations": "^11.2.8",
    "@angular/cdk": "^11.2.3",
    "@angular/common": "~11.2.3",
    "@angular/compiler": "~11.2.3",
    "@angular/core": "~11.2.3",
    "@angular/elements": "^11.2.3",`

**Closed** 2021-04-15 19:46 UTC
Labels: P3, comp: animations, freq3: high, type: bug/fix
