### ISSUE TITLE
Allow Route Params to be Passed into Component @Inputs

### ISSUE THREAD

**Issue by robertdempsey** [angular/angular#18967] opened 2017-08-31 01:16 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
When routing to a component, one must inject the ActivatedRoute service to retrieve route data for use inside the component. 

## Expected behavior
When defining routes, specific params could be used to provide values for @Inputs within the component. For example:

```
const routes:Routes = [
  {path: '', redirectTo: 'home', pathMatch: 'full'},
  {path: 'home', component: HomeComponent},
  {path: 'search:searchTerm', component: SearchComponent, inputs: { searchTerm: searchTerm }}, // bind the @Input searchTerm from SearchComponent to the searchTerm route parameter
  {path: '**', component: HomeComponent}
];
```

## Minimal reproduction of the problem with instructions

Configure the above routes; specifying data to be passed to component @Inputs is not possible.

## What is the motivation / use case for changing the behavior?
My team and I are creating completely modular components and publishing them on our private npm repo so that they may be used in any Angular application. We are achieving this modularity through the use of @Inputs, however now we are finding that these are not adequate if wanting to provide data through route/URL parameters.

What we are finding is that now we will have to use either @Inputs **or** route/URL parameters to provide dynamic data, or use them **both in combination** but this presents the problem of having to decide which takes precedence if both are present. 

This in my opinion breaks the modularity and reusability provided by the @Input functionality that is inherent to components. 

## Environment

<pre><code>
Angular version: 4.3.5

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by markwiggles** [comment] 2017-08-31 01:22
Great Idea! - this would be very helpful when building modular components

**Comment by elliotjr** [comment] 2017-08-31 01:36
+1

**Comment by ericmartinezr** [comment] 2017-08-31 08:57
https://github.com/angular/angular/issues/4452

**Comment by jasonaden** [comment] 2017-12-05 23:41
We are looking at something similar, but for now I'll close as a duplicate of #4452. Something like this will be coming (ability to bind to @Input properties), but we're not sure what form that will take at the moment.

**Comment by robertdempsey** [comment] 2017-12-06 09:52
Thanks for the update @jasonaden. Looking forward to this being implemented so that we can do away with superfluous wrapper components.

Cheers,
Rob

**Comment by daniel-upzzle** [comment] 2018-02-27 11:49
Any update on this? Thanks!

**Comment by spottedmahn** [comment] 2018-05-24 19:30
Hi @jasonaden - #4452 is closed.  Is there an open item that can be tracked?  Or maybe this we implemented?  Thanks 🙏!

**Comment by ShadowOfLies** [comment] 2018-07-06 08:14
Could we have this issue reopened or linked to an open issue providing the requested functionality, since it is expected to be in the pipeline as per @jasonaden ?

**Comment by Reeska** [comment] 2018-07-11 09:11
It's a real need, this will allow to separate component and routing concerns.
This feature exists in vue router : https://router.vuejs.org/guide/essentials/passing-props.html#boolean-mode

**Comment by Reeska** [comment] 2018-07-11 10:30
This feature exists in UI Router as well : 
- AngularJS : https://ui-router.github.io/guide/ng1/route-to-component#resolve-bindings
- Angular : https://ui-router.github.io/ng2/docs/latest/interfaces/state.statedeclaration.html

**Comment by HMubaireek** [comment] 2018-07-25 09:03
I'm trying to do the same but I got into this issue. This is really needed for creating modular components.

**Comment by IsharaMS** [comment] 2018-10-25 09:56
+1

**Comment by drewpayment** [comment] 2018-11-05 14:53
+1

**Comment by liyokuna** [comment] 2018-11-06 15:48
+1

**Comment by debonil** [comment] 2018-11-21 08:54
Need this feature.. please consider....

**Comment by sky10p** [comment] 2018-12-10 16:29
Why has this request been closed? It was very necessary.

**Comment by jasonaden** [comment] 2018-12-12 00:01
This was earlier closed as a duplicate, but it looks like that early issue was closed as well. I'll re-open this issue so we can track it here.

We *do* want to implement something like this. It's unfortunately not the highest priority right now. The earliest we can get to it would be some time in February.

**Comment by drewpayment** [comment] 2019-01-15 22:32
The route data is already accessible via the ActivatedRoute, but the requestor is proposing that route parameters have the ability to inject through a component's inputs instead.

**Comment by jasonaden** [comment] 2019-01-16 00:00
Quick update: Looks like anything along this type of functionality would be some time after version 8. That being said, providing better APIs such as this is something we want to get to soon after version 8 lands so they can come in later releases such as `8.1` or `8.x` releases.

**Comment by robertdempsey** [comment] 2019-01-16 05:19
Thanks a lot for the update @jasonaden

**Comment by leonardovff** [comment] 2019-07-09 15:17
I am waiting. This will be perfect to use.

**Comment by msmani** [comment] 2019-08-06 05:27
any update, as 8.2 doesn't seem to have this feature

**Comment by essaidim** [comment] 2019-08-26 15:30
any update on this ?

**Comment by suppadeliux** [comment] 2019-09-18 16:11
I thought this was already resolved? :(
Is this feature still up to date?

**Comment by garg10may** [comment] 2019-12-18 15:04
What's the progress on this, 9.0 is already in beta, it was said to be done in 8+ :(

**Comment by AvrahamYBock** [comment] 2020-02-09 22:21
Would love to see this feature implemented soon. Any progress?

**Comment by petriadrian** [comment] 2020-02-15 12:06
Any progress?

**Comment by jbjhjm** [comment] 2020-02-19 10:39
Pretty please? Hope to see this on the close future roadmap. Would make it alot easier handle data input. Merely for avoiding injecting Route/RouteSnapshot and searching for data it would be worth it.

**Comment by deefactorial** [comment] 2020-03-09 16:47
Over a year since this issue has had any serious attention. Is there a workaround for this feature?

**Comment by robertdempsey** [comment] 2020-03-09 21:16
We've actually outgrown this feature request, as we now use Resolvers to set data on a common service and then input the data into our components via a wrapper component. 

It's a 'workaround' if you will but it took the core of a custom framework to achieve and ended up being a lot more than simply passing static string values from route params into components.

I still think it would be a nice feature though, that and passing route and resolved data directly into component inputs.

**Comment by suppadeliux** [comment] 2020-04-16 15:31
Sad to hear that :(. Me and my team were waiting so bad to implement this. Our project is continuing to grow up, and for us, this feature is clearly the best choice. Specially when trying to do component tests and keep the modularity of each part of our application.

Can you provide/ or someone else a proper example using a resolver, and wrapper component to get around this issue?

Thank you for your help!

**Comment by robertdempsey** [comment] 2020-04-16 18:52
Hi @suppadeliux,

I'm currently writing up an article which details our journey from before asking for ths feature, to needing this feature, to creating the wrapper component etc. 

It'll include a link to the source code and an interactive example using stackblitz. I should have it done in a few days and I'll link it here for you when it's finished.

**Comment by ndr** [comment] 2020-04-19 14:29
Hi everyone.
I wanted this feature for a long time and decided to write it my own npm package for it.
It can be not perfect and this is one of my first npm packages, but for my project it is working ok (by now). Currently working only with angular 9
I will appreciate your opinion and any comments:
stackblitz:
https://stackblitz.com/edit/angular-v8hdug?embed=1&file=src/app/user/user-routing.module.ts
npm lib:
https://www.npmjs.com/package/ngx-route-params-input

**Comment by suppadeliux** [comment] 2020-04-20 08:02
> Hi @suppadeliux,
> 
> I'm currently writing up an article which details our journey from before asking for ths feature, to needing this feature, to creating the wrapper component etc.
> 
> It'll include a link to the source code and an interactive example using stackblitz. I should have it done in a few days and I'll link it here for you when it's finished.

Thanks for answering. That would be awesome! Looking forward for it.

**Comment by robertdempsey** [comment] 2020-04-20 10:42
@suppadeliux no worries. I'm working on it. But for now, it's quite similar to @ndr 's solution. so you may want to check that out. https://github.com/ndr/ngx-route-params-input

Nice work @ndr :)

**Comment by ndr** [comment] 2020-04-20 11:44
@robertdempsey 
I have never used keyof before, but seems we cannot link it to "this" property inside of interface (since interface is not js construction) and I am getting such error:
```
A 'this' type is available only in a non-static member of a class or interface
```
Or maybe I haven't understood your point correctly.
In additional or instead, I am thinking of adding the warning (or error) message in case user are trying to pass the property which not exists in the component

**Comment by robertdempsey** [comment] 2020-04-20 11:51
Yeah, that was just pseudo-code that I wrote. I was struggling with the
proper real code, but I've just figured out how to do it with generics.
I'll show it to you when I finish my article.

Basically what I meant was that it would be good for a compile time error
to be thrown if the property doesn't exist on the component.

**Comment by suppadeliux** [comment] 2020-04-21 08:11
Hey @ndr , nice work! and thanks for sharing :).

**Comment by robertdempsey** [comment] 2020-04-28 10:22
Hi @suppadeliux, @ndr ,

Sorry it took a little longer than I expected, but here it is:

https://medium.com/swlh/a-better-way-to-pass-data-to-your-angular-components-e8b5ef6a642a?source=friends_link&sk=57aa462301a88273e78442fb06d653a1

It's not exactly what you were after @suppadeliux, but it might give you some ideas.

**Comment by Alcantara6** [comment] 2020-06-13 05:14
it's necessary, hope for it！

**Comment by GaetanoPiazzolla** [comment] 2020-09-18 09:42
I was also searching for this functionality!
UP.

**Comment by jbjhjm** [comment] 2020-09-21 08:20
It's annoying this is still required.
I took a look at the angular source in search of possible "attack points" to use to implement this without help of the official team.

Custom decorators are powerful but I do not see a solution to get the ActivatedRoute if it was not injected in the component (and so it does again require configuration overhead).

Other idea is to modify the logic which creates a routed component.
The RouterOutlet component is responsible for resolving and creating the routed Component. It has an injected ComponentFactoryResolver, finds the responsible ComponentFactory and passes the data to Location.createComponent.
As almost everything is private in there, there's hardly a solution to modify anything in there.
If I find some time, I'll do some experimentation based on custom RouterOutlet and ComponentFactory.

**Comment by Remco75** [comment] 2020-11-19 11:36
@jbjhjm Are you working on this? I a willing to help out if needed.

**Comment by Remco75** [comment] 2020-11-20 08:15
is there ANY update from the team?  Is there an expected start of development? This is an extremely useful request. It decouples components from the router. No need to inject the activated route , but simply using inputs. Keeps the components simple and testable, a practice promoted by the angular team. 

Also the feature exists in uiRouter where it maps resolves to inputs.
I'm Using that in several other projects, but would like to use angular router since that is more actively maintained.

**Comment by jbjhjm** [comment] 2020-11-24 18:21
@Remco75 unfortunately I am not as I need to prioritize other tasks. Would involve lots of experimental work while it shouldn't be too difficult to add the feature to the router source.
I'm not sure what're the current priorities of the angular team, there are lots of important issues and improvements open for long time without much reactions. I hope they will soon begin to focus on such things again.

**Comment by Maximaximum** [comment] 2021-04-06 10:43
I should not be writing this, but. It's so frustrating that the official angular team does not pay any attention to features that are so obvious, so desired, (seemingly) easy to implement, but yet waited for for 3.5 years.

**Comment by L96Github** [comment] 2021-07-02 14:58
I also need this... Any updates?

**Comment by suppadeliux** [comment] 2021-07-02 14:59
Still nothing... 😭😭😭

**Comment by Samoji** [comment] 2021-07-19 11:03
Any updates? We really need this in our project 😢

**Comment by Nas3nmann** [comment] 2021-07-25 16:44
Hi guys, 
I finally had time to write a small Angular library that overcomes these downsides of the Angular router.
It allows you to pass route params (path and query params) to component inputs by simple configuration.
Optionally it can do even more:
It lets you adjust these url params on component output changes.
So basically you can "two-way databind" your component fields to router path/query params.

![demo](https://raw.githubusercontent.com/Nas3nmann/ngx-input-deep-linking/main/apps/demo-book-list/src/assets/demo.gif)

![demo](https://raw.githubusercontent.com/Nas3nmann/ngx-input-deep-linking/main/apps/demo-form/src/assets/demo.gif)

npm: [https://www.npmjs.com/package/@jdrks/ngx-deep-linking](https://www.npmjs.com/package/@jdrks/ngx-deep-linking)
github project: [https://github.com/Nas3nmann/ngx-input-deep-linking](https://github.com/Nas3nmann/ngx-input-deep-linking)

**Comment by Ferranteg-dev** [comment] 2022-02-15 12:02
So...any updates on this one? :D

**Comment by ajlif** [comment] 2022-05-25 15:13
any updates here ?

**Comment by RandAldurayhim** [comment] 2022-08-03 11:21
It will be a real help.. i am waiting.
i am new to Angular, and i thought there is a feature like this.

**Comment by eneajaho** [comment] 2022-08-03 16:32
With the new component creation apis, this feature would be easier to implement.

**Comment by atscott** [comment] 2022-08-03 17:06
> With the new component creation apis, this feature would be easier to implement.

This is correct, but more specifically this PR in particular: [feat(core): add ability to set inputs on ComponentRef](https://github.com/angular/angular/pull/46641). We plan on revisiting this feature in the near future.

**Comment by vigouredelaruse** [comment] 2022-08-21 00:53
wrote a dual use routeable component that when running in a self hosted environment (:4200) requires a config @Input as per
```
<tag [property]='computedvalue'/>
```

after discovering this thread and noting its longevity i am inclined to say the following
- binding @Inputs from http route parameters should include the nice to have of providing a custom binder extensibility point

this is to service the need to handle @Inputs that the <parentTag> passes to <childComponents> after some computation step
thanks

**Comment by spyro2000** [comment] 2023-03-02 09:33
Reading all this is just sad. Several years now, and it's still not possible to bind an `@Input()` to a route parameter without writing a lot of error-prone boilerplate code each time with lots of magic strings. That's exactly what I would expect from a web framework.

**Comment by Den-dp** [comment] 2023-03-02 13:48
@spyro2000 I see that Angular folks made a lot of router-related changes in order to make such features be possible in the future

![image](https://user-images.githubusercontent.com/1770529/222445809-ddf6b9f1-384d-40ec-8ea2-8a4123418675.png)

**Comment by spyro2000** [comment] 2023-03-02 15:04
@Den-dp Thank you, but now it's been 5 years, I stopped believing. Refactored now everything by hand like all the others.

**Comment by eneajaho** [comment] 2023-03-29 17:42
> @Den-dp Thank you, but now it's been 5 years, I stopped believing. Refactored now everything by hand like all the others.

It looks like you'll have to revert and start believing 😅

**Closed** 2023-03-30 23:11 UTC
Labels: feature, freq2: medium, area: router, feature: under consideration
