### ISSUE TITLE
Large Angular App is very slow in IE11, runs fine in Chrome or Firefox

### ISSUE THREAD

**Issue by mg-arrow** [angular/angular#14041] opened 2017-01-20 18:54 UTC
**Current behavior**
App is very slow in IE11. The initial app load takes up to 40 seconds.

**Expected behavior**
We should have speed closer to Chrome or Firefox, not 2-3 times slower.

**Minimal reproduction of the problem with instructions**

Windows 7, Webstorm, gulp build, no lazy routing

* **Angular version:** 2.0.X
2.0.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
IE11
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript

* **Node (for AoT issues):** `node --version` =   
Node 4.2.4

### EDIT: (@benlesh)

A reproduction was provided in [this comment](https://github.com/angular/angular/issues/14041#issuecomment-291878425).

**Comment by DzmitryShylovich** [comment] 2017-01-20 18:58
See https://github.com/angular/angular/issues/8112

Plus we need a demo app otherwise it's not actionable.

**Comment by tytskyi** [comment] 2017-01-20 21:49
@mg-arrow in fact you need to apply various technics to make your Angular application fast.
Including: `ChangeDetectionStrategy.OnPush`, using `trackBy` in `*ngFor`, using manual manipulations with `ChangeDetectorRef` debouncing your Rx streams, using `enableProdMode` in production, using manual chande detection in `ngDoCheck` to reduce heavy calculation, and of course bundle your app to single file.

You could check this guide as the starting point https://github.com/mgechev/angular-performance-checklist

**Comment by mg-arrow** [comment] 2017-01-20 22:03
Thanks for your comment. 

This is true but still does not explain why the same app works fine in Chrome.

We are actually trying lazy loading on the app right now and it works locally but not when we load it to server.

The error  is

<img width="649" alt="error" src="https://cloud.githubusercontent.com/assets/8698512/22167105/96227b06-df21-11e6-81ef-a7fc30bd6262.png">

**Comment by kemsky** [comment] 2017-01-21 20:54
Do you use AOT?

**Comment by DzmitryShylovich** [comment] 2017-02-01 11:20
@mg-arrow can you provide a demo or something? Otherwise we will close it

**Comment by DzmitryShylovich** [comment] 2017-03-10 08:54
@pkozlowski-opensource no repro. can be closed

**Comment by hawthorner** [comment] 2017-04-05 09:26
Getting same issue.  Find on Chrome, Firefox but crawls on IE 11.  My 3 year old mobile renders in 4 seconds what takes 30+ seconds on a beast of a desktop using IE 11.

Will try creating a basic sample project and seeing if I can reproduce or narrow it down.

**Comment by hawthorner** [comment] 2017-04-05 14:26
[TEST.zip](https://github.com/angular/angular/files/896538/TEST.zip)

Built a test app using CLI.  Very basic.  Takes 5k bits of data and generates a basic inputs or checkbox question for each using ngif.  I added some very primitive, inline styling.
(avoid opening app.component.ts if you use a linter, I just pasted the data straight into there)

Took a few seconds to render on chrome and around 30 to render on IE11.  I have taken no steps to optimise things so that render time could be reduced a lot, but ten times slower than chrome is clearly not a good sign regardless.

Hope I've attached this thing correctly.

**Comment by wiredprogrammer** [comment] 2017-09-23 17:39
Where I work we are having similar issues with IE11 being slower on the initial application load.  Having dev tools open speeds the page load up quite a bit.  We have a support call started with Microsoft so hopefully they can give some insight into the difference in behavior with and without dev tools open.  Initial load speed is fine in other browsers.  

A bare bones component  that doesn't pull in as many of the angular libraries seems to not slow down as badly on the initial load.  Need to do more research to see at what complexity the slow down significantly increases.  This feels like a IE issue since the having dev tools open shouldn't change the behavior of a web page.  Especially if you are using the dev tools to trouble shoot performance issues.

**Comment by will-l-h** [comment] 2017-10-02 19:23
@wiredprogrammer I've noticed the same behavior as you (slow initial load that is somehow sped up by dev tools running). Did you find out anything from your support call?

Also, do you see this same behavior on your work computer when you go to the angular material site?
https://material.angular.io/ 

I get the slow loading on material with my work computer, but not on my personal computer running Windows 10 build 1703

**Comment by wiredprogrammer** [comment] 2017-10-02 19:53
@will-l-h We didn't learn anything from the support call but the slow down disappeared when our support department rolled out a few windows updates last week.  I'm not sure what all was in that update bundle but the initial slow load has gone away.  Getting a fast load now.

**Comment by sctse999** [comment] 2017-10-19 17:00
We have an react-based app also running very slow in IE11 but once the dev tools is opened it runs much faster. We observed that when not using dev tools, IE11 memory consumption is confined to a level and frequent garbage collection is happening. It turns out that symantec endpoint protection is limiting the memory that could be used by IE11(without dev tool opened) and therefore our app is so slow. Once the endpoint protection is switched off, everything works fine again. Thank you Symantec.

**Comment by alvinj01** [comment] 2017-10-31 22:38
@sctse999 Did you manage to find out what configuration in the Symantec Endpoint Projection is limiting the IE11 memory?

**Comment by alvinj01** [comment] 2017-11-23 22:39
If your problem is also caused by Symantec Endpoint Projection, Symantec confirm it's an issue from them and they have a fix https://support.symantec.com/en_US/article.TECH247990.html.

**Comment by sgentile** [comment] 2018-05-30 14:57
Sad that the Angular2 devs act like this isn't a problem - and it doesn't take a 'test app' to see - it's obvious.

I would agree as well that I shouldn't need to totally alter the application just to make it perform at same level as other browsers

ie.  if this is needed on every single component then maybe Angular2 needs to rethink it's default behavior when it comes to components

"in fact you need to apply various techniques to make your Angular application fast.
Including: ChangeDetectionStrategy.OnPush, using trackBy in *ngFor, using manual manipulations with ChangeDetectorRef, debouncing your Rx streams, using enableProdMode in production, using manual chande detection in ngDoCheck to reduce heavy calculation, and of course bundle your app to single file."

I'm using OnPush, I have enabledProdMode - and the app is dreadfully slow in IE11 but fast in Chrome/Firefox (even Edge).

**Comment by mlc-mlapis** [comment] 2018-05-30 15:11
@sgentile ... so why are you still using IE? Everyone who uses IE (and it doesn't matter if it is a corporation or a person) and says he must do so, is doing it at the expense of everyone else because it prolongs required IE support and increases the cost of everyone else.

**Comment by sgentile** [comment] 2018-05-30 15:49
@mlc-mlapis I don't have any control what billion/million dollar corporations decide what browser they use.  As far as I'm concerned if these businesses decide to use whatever browser than that is their decision not mine, my job is to provide a solution.  We can't just stick our heads in the sand and ignore something that is there.

We all probably think electric cars are better than gasoline, we all probably think US should use metric units of measure, etc... but the reality of the world is it's not that simple.   

My response here isn't to debate the merits of not using IE, I certainly prefer Chrome and Firefox.   I applied all the features as described above in my application (onPush, trackby, etc...) and it's still at least 10x slower with IE11.

**Comment by mlc-mlapis** [comment] 2018-05-30 15:58
@sgentile ... sure, I understand your words very well in fact, but you are also saying the important fact `everybody can make a small step ahead ... even you can buys an electric car and force the change a bit`. 💪

**Comment by Goldflow** [comment] 2018-06-13 08:35
@mlc-mlapis I think everyone would love to stop using IE ... but in a lot of (ancient) corporate environments like telecom or banking, IE isn't going away any time soon and we need to make our applications compatible.

I am hopeful for companies migrating to Windows 10 where Edge with it's superior rendering engine is also there by default

**Comment by mtpultz** [comment] 2018-06-28 06:35
@mlc-mlapis, @Goldflow is absolutely right.  Also, don't forget government where change occurs very slowly, you're forced to use IE 11, and you're restricted from installing software that isn't already provided through a predefined image.

**Comment by mlc-mlapis** [comment] 2018-06-28 06:49
@mtpultz ... yep, I know all of that. I just wanted to say that they behave in the long run by transferring their costs to others and even claiming that to be okay.

**Comment by dannychase2004** [comment] 2018-09-08 21:26
Ok so I see this actual issue eroded into an idealistic debate about browsers.. I'm having this same issue under Edge, does anyone know the fix as of yet?

**Comment by dannychase2004** [comment] 2018-09-08 21:33
According to the profiler in Edge, the majority of the time is being taken in mousemove and mouseup, in globalZoneAwareCallback.. took about 10 seconds when I clicked the dropdown to see the options, then another 5 when I clicked on the option.. only thing I'm doing is a [(ngModel)] on the <select>, and I have my own options <option [value]="1">woop</option>..

**Comment by neerajsingh16** [comment] 2018-09-11 04:04
Did you guys look in change detect strategy for your components inside the
page? Default binding via [ngModel] will re-render whole page (even if
there is no change in data) for any change in any field or user
interaction.

**Comment by gkernen** [comment] 2018-09-18 22:27
While arguing the merits of a single-browser world (I remember a time when IE was rad and everything else was lamented) nobody answered the god damn question.

**Comment by kamlekar** [comment] 2018-10-29 11:48
As mentioned by [tytskyi](https://github.com/angular/angular/issues/14041#issuecomment-274188981), doing those performance changes after the project is done is real PIA. I wish these were considered by default in this framework.. WHY DIDN'T THEY???

**Comment by mlc-mlapis** [comment] 2018-10-29 12:13
@kamlekar ... it really depends on a concrete case. Both sides have their pros & cons. The question is why a developer doesn't know them. Especially `OnPush` and immutable patterns ... because if it would be the default ... always `OnPush` enabled ... then many people wouldn't understand why it's not working at all ... without the knowledge, what immutable principle is.

**Comment by nekkon** [comment] 2019-02-05 15:42
Hey guys. Had a similar experience with IE11 and Edge. By using trackBy in my ngFor I had much faster update of changes. From 4-5 seconds -> less than a second. Things run almost the same as with Chrome. I also use aot and onPush change detection.

**Comment by RonjaKnudtsen** [comment] 2019-02-27 20:53
Same results! trackBy solved everything

**Comment by Goldflow** [comment] 2019-02-28 11:37
ok that's great!
does anyone have best practices / guides for when having multiple nested ngFor, because implementing trackBy becomes more complex in that case

**Comment by mlc-mlapis** [comment] 2019-02-28 11:47
@Goldflow ... hmm, I think it's still the same. Each `*ngFor` creates its own scope and the unique key which `trackBy` returns is the same as a unique id in a standard relational table.

**Comment by arunkumarpal161** [comment] 2019-10-07 11:02
@tcoz We are also facing same issue in IE with version 11. We have also tried with all steps that you have mentioned as above. Our application is not big application ,it is simple 5-6 pages and still working very slow. We have also checked with server as well as local and sometime it's getting hangs the browsers.  We are getting error "IE is not responding due to long run  script". We are using the Firebase real time database for back-end. Please help me  and our polyfill.ts file looks like this:


import 'web-animations-js';
import 'core-js';
import 'classlist.js';
import 'core-js/es7/array';
import 'core-js/es7/reflect';
// import "core-js/es/array";
// import 'core-js/proposals/reflect-metadata';
import 'core-js/es7/object';
import 'core-js/es6/symbol';
import 'core-js/es6/object';
import 'core-js/es6/function';
import 'core-js/es6/parse-int';
import 'core-js/es6/parse-float';
import 'core-js/es6/number';
import 'core-js/es6/math';
import 'core-js/es6/string';
import 'core-js/es6/date';
import 'core-js/es6/array';
import 'core-js/es6/regexp';
import 'core-js/es6/map';
import 'core-js/es6/set';
import 'core-js/es6/weak-map';
import 'core-js/es6/reflect';
import 'core-js/client/shim';

/** Material Table */
import 'hammerjs';




/** ALL Firefox browsers require the following to support `@angular/animation`. **/
// import 'web-animations-js';  // Run `npm install --save web-animations-js`.

if (document['documentMode'] || /Edge/.test(navigator.userAgent)) {
  (window as any).__Zone_enable_cross_context_check = true;
}
/***************************************************************************************************
 * Zone JS is required by Angular itself.
 */
import 'zone.js/dist/zone';  // Included with Angular CLI.


/***************************************************************************************************
 * APPLICATION IMPORTS
 */

/**
 * Date, currency, decimal and percent pipes.
 * Needed for: All but Chrome, Firefox, Edge, IE11 and Safari 10
 */
//import 'intl';  // Run `npm install --save intl`.
//import 'intl/locale-data/jsonp/en';


if (typeof SVGElement.prototype.contains === 'undefined') {
  SVGElement.prototype.contains = HTMLDivElement.prototype.contains;
}

**Comment by tomo-at-e-sign** [comment] 2019-10-28 12:53
Hi, Commenters,

Di you ever resolve this problem, especially with the lazy loading as we are having a very similar problem with IE11 and the loading of a lot of JavaScript on the page from the Angular framework? ('Moving drag and drop items' etc.)

**Comment by danchaseCTS** [comment] 2019-10-29 20:24
All, I had resolved my issue, basically I had a very deep tree due to a recursive view loop using variables with ngDoCheck et al.

**Comment by tomo-at-e-sign** [comment] 2019-10-29 20:41
Our tree be shallow so maybe doesnt parse us. Dont use the doCheck. We're
stuck in angular where vue does 1 pg pwa's better. Thinking i can just
rework the js to prevent stackoverflow? Lazy load would be a nightmare.
Bundled with grunt so maybe webpack will code split better?

**Comment by danchaseCTS** [comment] 2019-11-09 19:14
Hi @tomo-at-e-sign 
In Chrome, if you Hit F12 to go to dev tools, then click the button to select an element on the screen, and select one of the elements that reside within your angular component (like a div or button or something), then go to the console tab and type: ng.profiler.timeChangeDetection()

You can record and review this in the "Javascript Profiler" tab of the browser, it has helped me IMMENSELY in the past, where I realized that most of the change detection time was being taken up by date/time conversions, for example. I recommend this for anyone developing in angular.

Here is the link where I originally got the info:
https://medium.com/@vamsivempati/a-guide-to-debugging-angular-applications-5a36bd88b4cf

Hope it helps!!

**Comment by PritiMaurya** [comment] 2019-12-07 05:29
> Do you use AOT?

yes

**Comment by pkozlowski-opensource** [comment] 2020-02-25 14:03
I reviewed this issue but I don't think there is anything actionable for us at the moment. Sadly, IE tends to be slower than Chrome and we can't do much about it in the framework...

Still, if you believe that Angular is using patterns / generating code that is _particularly_ slow in IE, please open a new issue with a minimal reproduce scenario. Thnx!

**Closed by pkozlowski-opensource** 2020-02-25 14:03 UTC
Labels: comp: core, comp: performance, freq1: low, risk: low, severity2: inconvenient, type: bug/fix
