### ISSUE TITLE
HttpClient is parsing a response to JSON ignoring the content-type

### ISSUE THREAD

**Issue by PeterBalzli** [angular/angular#22794] opened 2018-03-15 11:31 UTC
## I'm submitting a...

<pre><code>
[ ] Regression 
[ ] Bug report 
[x] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior
Responses from HttpClient are parsed like it's json even if Content-Type in Response Header is set to text/plain

## Expected behavior
HttpClient should respect content type from response header, if no responseType is provided.

## Minimal reproduction of the problem with instructions
this._httpClient.get('url') fails with message...

Unexpected token xy in JSON at position 0 at JSON.parse

... if the result is plain text and content type from response header set to text/plain

I know if I could manually set the responseType to text/plain, but I don't think that this should be necessary when the server correctly sets content type in response header.

## Environment
Angular version: 5.2.6

**Comment by flakolefluk** [comment] 2018-03-15 20:32
HttpClient is supposed to work like that: Expect a JSON response, unless you add a responseType option. In this example : { responseType:'text' } . Sounds like a feature request instead of a bug.

**Comment by dusk0r** [comment] 2018-03-16 08:39
Content-Type is part of the HTTP response. The client can't know the response type in advance.
Parsing 'text/plain' as JSON sounds like a bug to me.

**Comment by trotyl** [comment] 2018-03-16 09:22
Duplicate of https://github.com/angular/angular/issues/20000

**Comment by trotyl** [comment] 2018-03-16 09:23
The title is misleading, it's not about `parsing a request` but `parsing a response`.

**Comment by flakolefluk** [comment] 2018-03-16 13:14
If JSON is expected => HttpClient.get<T>(url) // returns Observable<T>
If other type is expected(i.e. text) =>HttpClient.get(url, {responseType:'text'}) // returns Observable<string>
If you don't know the type => HttpClient.get<T>(url, {observe:response}) //returns Observable<HttpResponse<T>>. You'll get the headers as well so you can parse your data properly.

**Comment by robwormald** [comment] 2018-03-18 01:42
The vast majority of use cases for the HttpClient involve fetching JSON, and so we're optimizing for that case here - there's no way to dynamically read the response type AND make it type-safe, so we make the common case simple, and require extra effort for the less common cases.

**Closed by robwormald** 2018-03-18 01:42 UTC

**Comment by akivamu** [comment] 2019-06-10 13:00
@robwormald 
In ExpressJS: `res.sendStatus(200) // equivalent to res.status(200).send('OK')`
So the response body contains the text "OK", will cause the Angular HttpClient parsing error.

Using `res.sendStatus(200)` is popular. And it's annoy when having to add `{responseType:'text'}` to many places while I just want to know the status is 200 and ignore the body.

Any other solution?

**Comment by mlc-mlapis** [comment] 2019-06-10 14:41
@akivamu ... this is the default behavior. So what you would suggest as default then?

**Comment by hei-pa** [comment] 2019-08-05 12:16
Yes as @akivamu said this would be my preferred solution
