### ISSUE TITLE
bug(ServiceWorker): multiple apps with ServiceWorker on one domain

### ISSUE THREAD

**Issue by skydever** [angular/angular#21388] opened 2018-01-08 15:28 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

The installation of a 2nd App/ServiceWorker (with different *baseHref*) purges the *Cache Storage* entries for a previously installed App/ServiceWorker, if they are on the same domain. This breaks the 1st installed App. It is not reachable anymore - you will always be redirected to the latest installed App.

## Expected behavior

The installation of multiple Apps/ServiceWorkers (with different *baseHref*) on one domain should be possible.

## Minimal reproduction of the problem with instructions

I created the following repo to reproduce the issue: [https://github.com/skydever/repro-multiple-ng-apps-one-domain-serviceworker](https://github.com/skydever/repro-multiple-ng-apps-one-domain-serviceworker). Follow the steps of the README there.

## What is the motivation / use case for changing the behavior?

I have to deploy multiple Angular Apps on one domain.

## Environment

<pre><code>
Angular version: 5.1.3

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v8.9.1  
- Platform: Windows 

Others:

</code></pre>
- [http-server](https://www.npmjs.com/package/http-server) version 0.10.0

**Comment by skydever** [comment] 2018-01-12 23:41
@alxhub Could this be a valid solution at [db-cache.ts](https://github.com/angular/angular/blob/master/packages/service-worker/worker/src/db-cache.ts)?

```typescript
export class CacheDatabase implements Database {
  private cacheScope: String; // to distinct between multiple scopes
  private tables = new Map<string, Promise<CacheTable>>();

  constructor(
    private scope: ServiceWorkerGlobalScope,
    private adapter: Adapter
  ) {
    this.cacheScope = this.scope.scope !== './' ? `:${this.scope.scope}` : '';
  }

  delete(name: string): Promise<boolean> {
    if (this.tables.has(name)) {
      this.tables.delete(name);
    }
    return this.scope.caches.delete(`ngsw:db${this.cacheScope}:${name}`);
  }

  list(): Promise<string[]> {
    return this.scope.caches
      .keys()
      .then(keys =>
        keys.filter(key => key.startsWith(`ngsw:db${this.cacheScope}:`))
      );
  }

  open(name: string): Promise<Table> {
    if (!this.tables.has(name)) {
      const table = this.scope.caches
        .open(`ngsw:db${this.cacheScope}:${name}`)
        .then(cache => new CacheTable(name, cache, this.adapter));
      this.tables.set(name, table);
    }
    return this.tables.get(name)!;
  }
}
```

... but I have to provide different scopes, and the scope will always be `./` by default (and wanted so to intercept all requests down the url path where the service worker script is located) ... maybe get the *baseHref* somehow? but how can I obtain it safely not doing something like `document.getElementsByTagName('base')[0].href`?

**Comment by skydever** [comment] 2018-01-13 00:01
found this at [browser_adapter.ts](https://github.com/angular/angular/blob/master/packages/platform-browser/src/browser/browser_adapter.ts):

```typescript
let baseElement: HTMLElement|null = null;
function getBaseElementHref(): string|null {
  if (!baseElement) {
    baseElement = document.querySelector('base') !;
    if (!baseElement) {
      return null;
    }
  }
  return baseElement.getAttribute('href');
}
```

it is related to the platform that is used and I don't know how to wire this up ...

**Comment by skydever** [comment] 2018-01-13 00:06
just get it in a safe way using document if available, sw are only available in the platform browser ...

**Comment by skydever** [comment] 2018-01-14 23:03
the `CacheDatabase` is service worker code, so no dom access there ... I can manipulate the `ngsw-worker.js` after the build process to include the app/baseHref info in `CacheDatabase`, by replacing the 3 `ngsw:db:` entries with `ngsw:db:[app-base-href]:` ...

**Comment by skydever** [comment] 2018-01-17 22:51
I created an [issue](https://github.com/angular/angular-cli/issues/9260) at the Angular CLI repo too. both are involved somehow, the baseHref option of the CLI needs to be passed to the service worker. I don't think that the service worker is able to do that without information from the CLI?

**Comment by skydever** [comment] 2018-01-24 08:26
replacing the `ngsw:db:` key seems not to work (even replacing the 6 occurences of `ngsw:` with a unique key does not work, but the distinction is better if you look at the `Cache Storage` at the dev tools - there are some entries without the `ngsw:db` prefix if you just replace the 3 occurences of `ngsw:db`) - the content of the `control` entry in the `CacheDatabase` still gets overwritten from another app ...

**Comment by skydever** [comment] 2018-01-26 23:16
did some more research, maybe this is helpful somehow. after renaming `ngsw:` (6 entries in `ngsw-worker.js`) to `ngsw:swAppOne` and `ngsw:swAppTwo` it seems to work, but the *Cache Storage* seems like to be in an invalid state ... I created a [branch](https://github.com/skydever/repro-multiple-ng-apps-one-domain-serviceworker/tree/wrong-manifests) in my repo for that, just `npm install` in *sw-app-one* and run `npm run start-sw` and open the pages at [sw-app-one](http://localhost:8090/sw-app-one/) and [sw-app-two](http://localhost:8090/sw-app-two/), then have a look into the *Cache Storage* in the dev tools - the entries *ngsw:sw-app-two:db:control* and *ngsw:sw-app-one:db:control* have the same values for *assignments*, *latest* and *manifests* - an image of it [here](https://github.com/skydever/repro-multiple-ng-apps-one-domain-serviceworker/blob/master/images/control-wrong-content.png).

Afterwards I also renamed the entries `assigments` to `assigmentsSwAppOne` and [so on](https://github.com/skydever/repro-multiple-ng-apps-one-domain-serviceworker/commit/55d44e24751e12904100807147965a5032f88d59) (the other way round in the commit, was to create a reproduction of the weird state). The result looks [clean](https://github.com/skydever/repro-multiple-ng-apps-one-domain-serviceworker/blob/master/images/control-renaming.png) now, with all the renaming. but still weird somehow, I also refreshed the cache in the dev tools ...

**Comment by gaurav2887** [comment] 2018-03-05 23:53
@skydever - Did you find any solution for this?

**Comment by skydever** [comment] 2018-03-06 10:11
hi @gaurav2887

my solution was a bit hacky and I don't use it in production at the moment, but it seemed to be working - maybe you can give it a try and report your results with the current version?

I created a post-build script that does some replacing in the `dist/ngsw-worker.js` file. The *Cache Storage* entries somehow got mixed up between multiple apps, one app is overriding entries from another app. I replace the following for each app that will be deployed on the same domain (eg. `app-one`):

* `ngsw:` -> `ngsw:app-one:` (6 occurences)
* `'manifests'` -> `'manifestsAppOne'` (3 occurences)
* `'assignments'` -> `'assignmentsAppOne'` (3 occurences)
* `'latest'` -> `'latestAppOne'` (3 occurences)

This way each app has unique keys for the *Cache Storage* and one app will not override entries from another app. I am not sure about any side effects, but the last time I tried it seemed to be working.

**Comment by gaurav2887** [comment] 2018-03-06 18:42
@skydever - Thanks for the reply. I need something for prod as we are serving multiple apps under one domain and service worker is not working that way.

**Comment by skydever** [comment] 2018-03-06 21:15
@gaurav2887 what are the problems you are facing? do the service worker of the apps register? do you get the redirect error (always to the latest installed app)? did you try the hack I provided? maybe also relevant: #20970 #20405, AngularCLI: [#8515](https://github.com/angular/angular-cli/issues/8515) [#8516](https://github.com/angular/angular-cli/issues/8516)

a possible solution could be the usage of sub domains (app1.domain.com, app2.domain.com) because then you have different [origins](https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy) and one app should not be able to manipulate the *CacheStorage* of another app...

I am looking forward to production ready ServieWorker support as well ...

**Comment by gaurav2887** [comment] 2018-03-07 21:01
@skydever - Service worker works fine for one app but does not get loaded for other app as it does not have baseHref while loading the ngsw.json for other app. So the first default root app works fine with service worker and I have to add dataGroups to ask for fresh copy of other app. We would like to use one domain and allow multiple apps loading based on the route (/app1,/app2). Making manual changes ngsw-worker.js will not be good for prod so I will probably wait for fix for this which will allow to us to have ngsw.json loaded per app.

**Comment by dcatoday** [comment] 2018-04-12 21:57
I am also seeing problems with registering multiple service workers on one domain.  As it stands I'm not able to successfully register one service worker that isn't located in the root folder.  I am trying to add --base-href and --deploy-url and run a node server with the app in a specified folder.  The ngsw seems to configure but it doesn't cache any of the application files.

**Comment by Splaktar** [comment] 2018-05-01 06:10
This has more information, but it seems like a duplicate of https://github.com/angular/angular/issues/20405.

**Comment by rjwijnen** [comment] 2018-06-26 08:05
Any news on this issue? This is blocking the enabling of service worker for our apps.

**Comment by gkalpak** [comment] 2018-06-26 09:49
Nobody is actively working on this afaict (there are other higher priority stuff going on).
If anyone wants to investigate this further, I'd be happy to review (but it won't be a trivial undertaking 😱).

**Comment by petersalomonsen** [comment] 2018-10-19 14:12
I had success with a workaround of editing the ngsw-worker.js after the build, and then replace every occurence of `ngsw:` with `ngsw-your_unique_app_id:`

Then the caches prefix will be unique per app, and I'm able to switch apps without being redirected to the latest installed app.

Anyone working on a pull request for this - or has it become better in Angular 7?

**Comment by gkalpak** [comment] 2018-10-19 16:51
I don't think anyone is working on it and neither have things changed in Angular 7 (afaik).
If you want to take a stub at it, I'd be happy to review.

**Comment by canhamd** [comment] 2018-12-03 14:42
Solution proposed by @petersalomonsen  also worked for me. I would suggest adding a namespace field to ngsw-config.json, which if is present when generating ngsw-worker.js is used as a postfix to all occurences of ngsw: in that file. 

i.e. if a namespace field is provided in ngsw-config.json with a value of "my-app", then perform a find/replace on ngsw-worker.js post generation (or during) replacing all occurences of ngsw: with ngsw-my-app:

allowing this namespace value to be provided in tooling would also be useful. e.g. as a question when performing ng add @angular/pwa

**Comment by gkalpak** [comment] 2018-12-03 16:14
I don't think adding a value to `ngsw-config.json` is a good idea, as it does not guarantee uniqueness across subpaths.
Nor is hashing `ngsw.json`, since this will ignore the previous caches and always download all assets from the server.

The SW scope should be used instead. In case anyone has missed it, there is a PR in progress for that: #27080

**Comment by petersalomonsen** [comment] 2018-12-03 16:19
@gkalpak Correcting myself - I meant the `index` property value of the `ngsw.json` file. But very good that there's an official solution in progress for this.

**Closed** 2019-03-21 16:09 UTC
Labels: comp: service-worker, freq1: low, severity2: inconvenient, type: bug/fix

**Comment by skydever** [comment] 2019-03-24 00:09
🎉 awesome!! thx a lot to everybody involved in this 👍

**Comment by Kush5900** [comment] 2019-04-08 12:08
it still don't work!

**Comment by tplk** [comment] 2019-04-08 20:54
@Kush5900 what version have you tried it on?
Looks like it'll be released in 8.0.0 but you can already try it out in the latest beta.

**Comment by Kush5900** [comment] 2019-04-09 08:15
@tplk Yeah i'm on 7.2 and i'am working on a serious project can't update to beta versions! i'm currently using @petersalomonsen work around but it seems unstable somehow. any alternative?

**Comment by petersalomonsen** [comment] 2019-04-09 08:22
@Kush5900 Are you using my workaround as in the script below? 

I'm running this using the dist folder as argument after building the bundles.

```
const fs = require('fs');
var crypto = require('crypto');
const distfolder = process.argv[2];
const appindex = JSON.parse(fs.readFileSync(`${distfolder}/ngsw.json`)).index;
const hash = crypto.createHash('sha1');
hash.update(appindex);
const uniqueappid = hash.digest('hex').substr(0,8);

const workerfilecontents = new String(fs.readFileSync(`${distfolder}/ngsw-worker.js`));
console.log(`Replacing in ${distfolder}/ngsw-worker.js 'ngsw:' with 'ngsw:${uniqueappid}:'`);
fs.writeFileSync(`${distfolder}/ngsw-worker.js`, workerfilecontents.replace(/ngsw\:/g,`ngsw:${uniqueappid}:`));

console.log(`Replacing scope and start-url in manifest`);
const manifest = JSON.parse(fs.readFileSync(`${distfolder}/manifest.json`));
const starturl = appindex.replace("index.html", "");
manifest.scope = starturl;
manifest.start_url = starturl;
fs.writeFileSync(`${distfolder}/manifest.json`, JSON.stringify(manifest, null, 1));
```

**Comment by Kush5900** [comment] 2019-04-09 08:35
@pedroclayman Yeah i copied the whole script and it works and i'm able to switch between languages but since then my serviceWorker stopped working in offline mode! How are you registering the service worker in app.module.ts ?

**Comment by petersalomonsen** [comment] 2019-04-09 08:41
I register my serviceworker like this:

`ServiceWorkerModule.register('ngsw-worker.js', { enabled: environment.production })`

No absolute path. My apps work fine in offline mode.

**Comment by Kush5900** [comment] 2019-04-09 09:42
@petersalomonsen  that it is how i register my serviceworker too, sometimes it works and sometimes it produce these error: 
```
An unknown error occurred when fetching the script.
Failed to load resource: net::ERR_INTERNET_DISCONNECTED
```

**Comment by petersalomonsen** [comment] 2019-04-09 16:02
hmmm, I'm not experiencing that @Kush5900 but will let you know if I do.
