### ISSUE TITLE
Generic track by functionality for property binding

### ISSUE THREAD

**Issue by Aaron-Pool** [angular/angular#14211] opened 2017-01-31 20:28 UTC
**I'm submitting a ...**

[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see 

**Current behavior**

Property bindings check for changes by comparing object reference. And there is no way of having the change check compare a subproperty object reference instead of the root object reference.

**Expected behavior**

I can specify either a subproperty object reference to check instead, or a subproperty primitive to check by value.

**What is the motivation / use case for changing the behavior?**

The `doCheck` hook is often times more complex than is necessary for simply specifying a more specific field to check in the change tracking process.

I would think it would be _very_ useful, and not entirely outside of the spirit of the framework, to be able to do something such as `[hero]="hero track by hero.stats"`. So that, in the parent component, I can overwrite the hero objects `stats` field and have the new object propagate down to the child without having to rewrite all other properties on the hero. Ones that don't really change, like maybe `id` or `name`.

I'm primarily an angular 1 developer, and I made this feature request over there, but they basically said they would only consider it if they knew there would be a comparable feature in ng2.

Reference: https://github.com/angular/angular.js/issues/15647

**Comment by pkozlowski-opensource** [comment] 2019-03-23 13:20
This is the same feature request as in #18527 - closing this one as a duplicate of #18527

**Closed by pkozlowski-opensource** 2019-03-23 13:20 UTC
Labels: comp: core & compiler, type: feature
