### ISSUE TITLE
No details in error message while build prod version if there is expression in template which is not instance of ReadPropExpr

### ISSUE THREAD

**Issue by mohaxspb** [angular/angular#32759] opened 2019-09-18 21:42 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/compiler

### Is this a regression?
 No

### Description

If there is expression in template that is not instance of `ReadPropExpr` error without any details thrown while execute `ng build --prod`

## 🔬 Minimal Reproduction

Repository with example: https://github.com/mohaxspb/ng-var-directive-issue

To get error without any details just run `ng build --prod`

## 🔥 Exception or Error
<pre><code>
ERROR in Cannot assign to a reference or variable!
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.3.4
Node: 10.15.3
OS: win32 x64
Angular: 9.0.0-next.6+80.sha-df1c456.with-local-changes
... animations, bazel, common, compiler, compiler-cli, core
... elements, forms, language-service, localize
... platform-browser, platform-browser-dynamic, platform-server
... platform-webworker, platform-webworker-dynamic, router
... service-worker, upgrade

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.4
@angular-devkit/build-angular     0.803.4
@angular-devkit/build-optimizer   0.803.4
@angular-devkit/build-webpack     0.803.4
@angular-devkit/core              8.3.4
@angular-devkit/schematics        8.3.4
@angular/cli                      8.3.4
@ngtools/webpack                  8.3.4
@schematics/angular               8.3.4
@schematics/update                0.803.4
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2
</code></pre>

**Anything else relevant?**

I'm in progress with PRs to add details to error message, which will show variables names in template expression which causes error and one more with fix for it. I'll edit this issue after I submit this PRs.

**Comment by alxhub** [comment] 2019-10-08 22:40
Closing this as a duplicate of #32695.

**Closed by alxhub** 2019-10-08 22:40 UTC
Labels: comp: compiler
