### ISSUE TITLE
SCSS imports error upgrading from 8.3.1 to Ivy

### ISSUE THREAD

**Issue by uplink42** [angular/angular#32913] opened 2019-09-30 14:19 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/core

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 8.3.1

### Description

Running the below command produces an error when attempting to upgrade to Ivy
`ng update @angular/cli@next @angular/core@next --force`

## 🔥 Exception or Error

> ** Executing migrations for version 9.0.0-beta of package '@angular/core' **
>     ------ Missing @Injectable migration ------
>     Successfully migrated all undecorated providers.
>     -------------------------------------------
> ** Executing migrations for version 9.0.0-beta of package '@angular/core' **
>     ------ Renderer to Renderer2 Migration ------
>     As of Angular 9, the Renderer class is no longer available.
>     Renderer2 should be used instead.
> ** Executing migrations for version 9.0.0-beta of package '@angular/core' **
>     ------ Undecorated classes with decorated fields migration ------
>     As of Angular 9, it is no longer supported to have Angular field decorators on a class that does not have an Angular decorator.
> ** Executing migrations for version 9.0.0-beta of package '@angular/core' **
>     ------ Undecorated classes with DI migration ------
>     
>     This migration uses the Angular compiler internally and therefore projects that no longer build successfully after the update cannot run the migration. Please ensure there are no AOT compilation errors and rerun the migration.. The following project failed: src/tsconfig.app.json
>     
>     Error: error TS100: Couldn't resolve resource modules/breakpoints from [removed for privacy reasons]/real-estate-client/src/app/public-core/nav/nav.component.scss
>     
>     
>     Migration can be rerun with: "ng update @angular/core --from 8.0.0 --to 9.0.0 --migrate-only"
>     Successfully migrated all found undecorated classes
>     that use dependency injection.

## 🔬 Minimal Reproduction
I believe this is because of my angular.json configuration. It's currently using **include paths** for SCSS file imports (so I don't have to type the entire path from the project root whenever I want to import scss files from component styles)

```
"stylePreprocessorOptions": {
        "includePaths": [
              "src/assets/scss"
         ]
  },
```
For some reason the migration can't seem to find the imported files and just crashes as shown.

To reproduce it, simply create a new angular project with SCSS preset, change the **stylePreprocessorOptions** in angular.json as shown above and try to run `ng update @angular/cli@next @angular/core@next --force`

## 🌍  Your Environment (after attempting to run the migration command)

**Angular Version:**
<pre><code>

Angular CLI: 9.0.0-next.6
Node: 12.3.1
OS: win32 x64
Angular: 9.0.0-next.8
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.900.0-next.6
@angular-devkit/build-angular      0.900.0-next.6
@angular-devkit/build-optimizer    0.900.0-next.6
@angular-devkit/build-webpack      0.900.0-next.6
@angular-devkit/core               9.0.0-next.6
@angular-devkit/schematics         9.0.0-next.6
@angular/cdk                       8.2.0
@angular/cli                       9.0.0-next.6
@angular/material                  8.2.0
@angular/material-moment-adapter   8.2.0
@angular/pwa                       0.900.0-next.6
@ngtools/webpack                   9.0.0-next.6
@schematics/angular                9.0.0-next.6
@schematics/update                 0.900.0-next.6
rxjs                               6.5.3
typescript                         3.5.3
webpack                            4.41.0
</code></pre>

**Anything else relevant?**
OS: Windows 8 64bits

**Comment by mstawick** [comment] 2019-10-02 18:14
@uplink42 Did you come up with a workaround? I thought of changing imports to relative paths, but it's really not a feasible solution.

**Comment by uplink42** [comment] 2019-10-04 08:43
@mstawick 

Unfortunately not, changing every import is not really feasible at this point.

Hopefully this gets fixed when ivy comes out.

**Comment by Splaktar** [comment] 2019-10-06 01:03
The title is misleading. This is really about the upgrade to Angular `9.0.0-next.x` and not Ivy specifically. The schematic that is throwing this error can be found [here](https://github.com/angular/angular/tree/master/packages/core/schematics/migrations/undecorated-classes-with-di). That said, the schematic is making updates to application code to be compatible with Ivy.

It would be helpful (to ensure this is triaged as quickly as possible) to change the issue's title to something like:
`migration(undecorated-classes-with-di): Couldn't resolve SCSS resource`

**Comment by Splaktar** [comment] 2019-10-06 01:38
I don't believe that `includePaths` is the cause of this issue.

Since no reproduction was provided for this issue, I'll provide mine here.

## Steps to reproduce
1. Clone the repo and switch to this branch: https://github.com/angular/material.angular.io/tree/stackblitz-ivy
1. Run `ng update --next @angular/cli @angular/core @angular/material @angular/material-experimental @angular/cdk-experimental`

## Result
```sh
------ Undecorated classes with DI migration ------

  This migration uses the Angular compiler internally and therefore projects that no longer build successfully after the update cannot run the migration. Please ensure there are no AOT compilation errors and rerun the migration.. The following project failed: tsconfig.app.json

Error: error TS100: Couldn't resolve resource ../../../styles/constants from /Users/splaktar/Git/angular/material.angular.io/src/app/pages/component-category-list/component-category-list.scss


Migration can be rerun with: "ng update @angular/core --from 8.0.0 --to 9.0.0 --migrate-only"
Successfully migrated all found undecorated classes
that use dependency injection.
----------------------------------------------
```

## Analysis
Looking at the [file in question](https://github.com/angular/material.angular.io/blob/d15b77f611a4c1a0095c5c8abca86357e26711a7/src/app/pages/component-category-list/component-category-list.scss#L1), the resource resolves just fine in local builds (AOT and JIT) and in WebStorm.

It's hard to tell if this is something due to the number of `../` involved or not since the OP doesn't show the full path.

Immediately after this, running `ng build --aot` gives:
```sh
Generating ES5 bundles for differential loading...
An unhandled exception occurred: Call retries were exceeded
See "/private/var/folders/3w/d8jpfpm16xs1ktpq20zprl880000gn/T/ng-ec7f3b/angular-errors.log" for further details.
```
`angular-errors.log` contains:
```ts
[error] Error: Call retries were exceeded
    at ChildProcessWorker.initialize (/Users/splaktar/Git/angular/material.angular.io/node_modules/jest-worker/build/workers/ChildProcessWorker.js:193:21)
    at ChildProcessWorker.onExit (/Users/splaktar/Git/angular/material.angular.io/node_modules/jest-worker/build/workers/ChildProcessWorker.js:263:12)
    at ChildProcess.emit (events.js:198:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
```
This causes a throw of [MIGRATION_AOT_FAILURE](https://github.com/angular/angular/blob/01677b21b6ae057f8987b5d17c862286a3763615/packages/core/schematics/migrations/undecorated-classes-with-di/index.ts#L174).

Why is `jest-worker` involved here at all?
```sh
npm ls jest-worker
material-angular-io@0.0.0 /Users/splaktar/Git/angular/material.angular.io
└─┬ @angular-devkit/build-angular@0.900.0-next.8
  ├── jest-worker@24.9.0 
  └─┬ terser-webpack-plugin@2.1.0
    └── jest-worker@24.9.0  deduped
```
If I run `ng build --prod` after this, it succeeds. 
But if I run `ng build` after this (which has `"aot": true,` in the target default options), then it fails again with the same error and at the same lines of `jest-worker`.

It's not clear why this migration would be resolving SCSS files anyhow since this is a TypeScript-only migration AFAIK. `TS100` seems to be a generic TypeScript build failure as far as I can tell.

**Comment by devversion** [comment] 2019-10-06 12:45
This is actually solved by https://github.com/angular/angular/commit/6f5f481fdae03f1d8db36284b64c7b82d9519d85. It's not yet released, but will be soon as part of the upcoming `next` version.

Please open up a new issue if you still see issues in the upcoming _next_ version (e.g. `9.0.0-next.10`). Also these issues should be submitted on the `angular/angular` repository as the migration code is there.

**Closed by devversion** 2019-10-06 12:45 UTC
Labels: comp: compiler

**Comment by Splaktar** [comment] 2019-10-06 17:46
Related PR https://github.com/angular/angular/pull/32953. Thank you @devversion!
