### ISSUE TITLE
Change detection should run automatically after router navigation in unit tests

### ISSUE THREAD

**Issue by antischematic** [angular/angular#48608] opened 2022-12-29 03:43 UTC
### Which @angular/* package(s) are the source of the bug?

core, router

### Is this a regression?

No

### Description

Given a component fixture is set to `autoDetectChanges` and I call `router.navigate`, router outlets should emit `activate` events and render the outlet component, but they don't. As a result of https://github.com/angular/angular/pull/46554 I must manually call `detectChanges` after every navigation to ensure the view is up to date.

When serving the app everything works fine without needing to perform manual change detection. It only happens in unit tests.

### Please provide a link to a minimal reproduction of the bug

https://github.com/antischematic/angular-15-router-event-defect/blob/master/src/app/route-extension.spec.ts

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.0.4
Node: 16.13.0
Package Manager: npm 8.1.0
OS: darwin x64

Angular: 15.0.4
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1500.4
@angular-devkit/build-angular   15.0.4
@angular-devkit/core            15.0.4
@angular-devkit/schematics      15.0.4
@schematics/angular             15.0.4
rxjs                            7.5.7
typescript                      4.8.4
```

### Anything else?

~~These tests were passing in Angular 14 without calling `fixture.detectChanges`.~~

**Comment by atscott** [comment] 2022-12-29 18:37
> These tests were passing in Angular 14 without calling fixture.detectChanges.

Some tests might have passed but your reproduction actually shows that it was _always_ the case that change detection must run for the routed components to be fully rendered. Because your tests are reading bindings, those values won't show up in the HTML until after change detection runs. So even before #46554, those tests would still fail without manually calling `detectChanges`

> Given a component fixture is set to `autoDetectChanges` and I call `router.navigate`, router outlets should emit activate events and render the outlet component, but they don't

Again, this isn't a regression in v15. In order for a component to fully render, change detection must always run. That said, I do sympathize with the feeling that it would be nice for change detection to run automatically after a navigation. This is effectively being addressed in #48552 by adding a test navigation helper which includes a call to `detectChanges`. Beyond that, there won't be any special handling put into the `Router` to detect navigations inside `TestBed`, nor will there be any special logic put into `TestBed` to handle navigations.

**Comment by antischematic** [comment] 2022-12-29 23:08
Thank you @atscott. You're right, these tests do fail in ng14 without explicit change detection. I have always thought that `autoDetectChanges`makes change detection in the test environment identical to serving the app. Now I just realised that tests run outside of the Angular zone, so the promise from `router.navigate` never triggers change detection when it resolves.

Changing my test to run inside the Angular zone makes it so I don't have to call `detectChanges`

```ts
const router = TestBed.inject(Router)
const ngZone = TestBed.inject(NgZone)
const fixture = TestBed.createComponent(TestComponent)
fixture.autoDetectChanges()

ngZone.run(() => router.navigate(["/root/test/nested"]))
flush()

expect(fixture.nativeElement.textContent).toContain("root") // now it passes
```

I can understand why it works this way, but it's very confusing and feels like a bug. Furthermore I don't think the `navigateForTest` utility as it is currently designed would work well with existing test code, it doesn't appear to have the same API or behaviour as `router.navigate`.

This should at least be clarified in the documention for `autoDetectChanges` and route testing.

**Comment by JoostK** [comment] 2022-12-30 11:06
This seems related to #47236.

**Comment by atscott** [comment] 2022-12-30 16:35
@JoostK I would say #25837 and #47236 is yet another issue about developers _not_ wanting the warning. I feel like the request here is the opposite of #25837 and #47236 and would like to add the warning back, which we used to have and developers overwhelmingly don't like. The tests in this reproduction do 
```
const router = TestBed.inject(Router)
const fixture = TestBed.createComponent(AppComponent)
```
This results in the Router being created outside the Angular zone so the warning doesn't show up. If the test instead did 
```
const fixture = TestBed.createComponent(AppComponent)
const router = TestBed.inject(Router)
```
Then `Router` would be created _inside_ the zone, the warning would show, and it would satisfy the request here to document that `navigate` has to be called in `ngZone.run`. I don't think there's a great "solution" to this problem at the moment. We'll have to see what happens with `TestBed` and `ZoneJS` in the coming years.

**Closed** 2023-01-25 19:31 UTC
Labels: feature, area: testing, state: has PR, feature: votes required
