### ISSUE TITLE
Animations getAnimationStyle return undefined in angular 7.x with old browsers

### ISSUE THREAD

**Issue by Serginho** [angular/angular#29278] opened 2019-03-13 15:51 UTC
# 🐞 bug report

### Affected Package
@angular/animations

### Is this a regression?
No

### Description
Since I've updated from angular 5.2 to 7.2 I'm getting the following errors related with animations:
>Cannot read property 'split' of undefined
https://github.com/angular/angular/blob/f8096d499324cf0961f092944bbaedd05364eea1/packages/animations/browser/src/render/css_keyframes/element_animation_style_handler.ts#L91

>Cannot call method 'trim' of undefined
https://github.com/angular/angular/blob/f8096d499324cf0961f092944bbaedd05364eea1/packages/animations/browser/src/render/css_keyframes/element_animation_style_handler.ts#L79

This error is happens at least in the following browsers:
```
Chrome (28.0.1500.94) running over Android (4.2.2)
Chrome (34.0.1847.114) running over Android (4.4.2)
Chrome (42.0.2311.111) running over Android (4.2.2)
Mobile Safari (8.0) running over iOS (8.4)
Android Browser (4.0) running over Android (8.1)
```

**This is not happening in last versions of these browsers.**

## 🔬 Minimal Reproduction
Running animations in any of this browsers

## 🔥 Exception or Error
```
TypeError: Cannot read property 'split' of undefined
    at t.push.NSYL.t.destroy (/vendor.6687942ea70b4222b345.js:1:436607)
    at t.push.NSYL.t.destroy (/vendor.6687942ea70b4222b345.js:1:437754)
    at /vendor.6687942ea70b4222b345.js:1:1559085
    at Array.forEach (native)
    at t.push.ihYY.t._onDestroy (/vendor.6687942ea70b4222b345.js:1:1559056)
    at t.push.ihYY.t.destroy (/vendor.6687942ea70b4222b345.js:1:1558941)
    at t.push.NSYL.t.destroy (/vendor.6687942ea70b4222b345.js:1:430640)
    at /vendor.6687942ea70b4222b345.js:1:415603
    at Array.forEach (native)
    at t.push.NSYL.t.destroy (/vendor.6687942ea70b4222b345.js:1:415574)
```

```
TypeError: Cannot call method 'trim' of undefined
    at t.apply (/vendor.6687942ea70b4222b345.js:1:435597)
    at t.init (/vendor.6687942ea70b4222b345.js:1:438603)
    at /vendor.6687942ea70b4222b345.js:1:1558126
    at Array.forEach (native)
    at t.init (/vendor.6687942ea70b4222b345.js:1:1558097)
    at t.play (/vendor.6687942ea70b4222b345.js:1:1558561)
    at t.play (/vendor.6687942ea70b4222b345.js:1:430383)
    at /vendor.6687942ea70b4222b345.js:1:426198
    at Array.forEach (native)
    at t._flushAnimations (/vendor.6687942ea70b4222b345.js:1:426075)
```
## 🌍  Your Environment

**Angular Version:**
Angular: 7.2.8

**Comment by pedep** [comment] 2019-03-20 10:49
Duplicate of #24094

**Closed** 2019-03-20 10:56 UTC
Labels: comp: animations
