### ISSUE TITLE
NG UPDATE NOT WORKING going from angular 17 to angular 18 

### ISSUE THREAD

**Issue by harpreetsinghravi** [angular/angular#56943] opened 2024-07-11 00:11 UTC
### Which @angular/* package(s) are the source of the bug?

upgrade

### Is this a regression?

Yes

### Description

I have been migrating my projects from angular 17 to angular 18 using the update guide this week. Ever since v18.1.0 was released, the ng update command started to fail. 2 of my projects migrated just fine to version 18.0.6. 

The reason for the failure is because of the temporary cli version 18.1.0 that is installed. The error messages is - "No matching version found for @angular-devkit/architect@0.1801.0."

Seems like this package is missing. Can this be addressed as I can no longer migrate any project to version 18 ? Is there a way to specify which temporary cli version to use? If yes, then I can use this as a workaround for now. Please advise.

### Please provide the exception or error you saw

```true
The error messages is - "No matching version found for @angular-devkit/architect@0.1801.0."
```

**Comment by JeanMeche** [comment] 2024-07-11 00:14
The package was successfully published : https://www.npmjs.com/package/@angular-devkit/architect/v/0.1801.0

You likely have an issue with your registry. Do you use a custom registry ?

**Comment by alan-agius4** [comment] 2024-07-11 06:08
Duplicate of #28030

**Closed by alan-agius4** 2024-07-11 06:08 UTC
