### ISSUE TITLE
Angular Animations not work in ViewEncapsulation.ShadowDom env

### ISSUE THREAD

**Issue by stecapra** [angular/angular#47523] opened 2022-09-22 15:40 UTC
### Which @angular/* package(s) are the source of the bug?

animations, elements

### Is this a regression?

No

### Description

Expected behavior
Setting ShadowDom Encapsulation strategy should work with Angular Animations.

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

### Please provide the exception or error you saw

```true
As the title mentioned, setting ViewEncapsulation.ShadowDom will cause the Animations not been able to run at all. Use-case: I'm building an Angular Element with Angular Animations to see if the two play well together.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 11.2.19
Node: 14.17.3
OS: darwin x64

Angular: 11.2.14
... animations, common, compiler, compiler-cli, core, elements
... forms, language-service, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: No

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.901.15
@angular-devkit/build-angular   0.1102.10
@angular-devkit/core            11.2.19
@angular-devkit/schematics      11.2.19
@angular/cdk                    11.2.13
@angular/cli                    11.2.19
@schematics/angular             11.2.19
@schematics/update              0.1102.19
ng-packagr                      11.2.4
rxjs                            6.6.7
typescript                      4.0.8
```

### Anything else?

What is the motivation/use case for changing the behavior?

**Comment by JoostK** [comment] 2022-09-22 15:55
This is an _exact_ duplicate of #25672, for which there has been a fix in 12.1.0.

**Closed by JoostK** 2022-09-22 15:55 UTC
