### ISSUE TITLE
InnerHTML property not working on HTML select tag

### ISSUE THREAD

**Issue by Balakumar777** [angular/angular#45214] opened 2022-02-28 13:20 UTC
### Which @angular/* package(s) are the source of the bug?

core, elements, forms

### Is this a regression?

Yes

### Description

The innerHTML property not appending the option into the select tag in HTML.
`public option = '<option value="1">Test</option>'`
`<select [innerHTML]="option"></select>`

Angular version is 13.2.0

**Comment by pkozlowski-opensource** [comment] 2022-02-28 14:22
It is due to the sanitization process: https://angular.io/guide/security#sanitization-and-security-contexts (you should see warning in your browser).

While you can bypass this mechanism most of the time binding to `innerHTML` should be avoided. Maybe consider a different approach. In any case Angular is trying to do the "right" thing here.

Going to close this one as the framework behaves as designed.

**Closed by pkozlowski-opensource** 2022-02-28 14:22 UTC

**Comment by Balakumar777** [comment] 2022-03-01 05:47
> It is due to the sanitization process: https://angular.io/guide/security#sanitization-and-security-contexts (you should see warning in your browser).
> 
> While you can bypass this mechanism most of the time binding to `innerHTML` should be avoided. Maybe consider a different approach. In any case Angular is trying to do the "right" thing here.
> 
> Going to close this one as the framework behaves as designed.

Oh I didn't aware of that thanks for your quick reply @pkozlowski-opensource
