### ISSUE TITLE
Angular example for Template-Driven form validator for name=Bob not working

### ISSUE THREAD

**Issue by msmithmis** [angular/angular#20234] opened 2017-11-07 03:33 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

In Angular.io example for Form Validations, the validator for the template driven form does not work when name = Bob.  The error does not show.  It does work for the reactive form.
Here is the fix:
Change this line in hero-form-template.component.html:
        <input id="name" name="name" class="form-control"
               required minlength="4" forbiddenName="bob"
               [(ngModel)]="hero.name" #name="ngModel" >
to
        <input id="name" name="name" class="form-control"
               required minlength="4" **appForbiddenName** forbiddenName="bob"
               [(ngModel)]="hero.name" #name="ngModel" >

## Expected behavior

Validator should display "Name cannot be Bob."  

## Minimal reproduction of the problem with instructions
Go to https://angular.io/generated/live-examples/form-validation/eplnkr.html
Type name as "Bob"
Notice the red error message does not say name cannot be Bob.

## What is the motivation / use case for changing the behavior?

The angular.io docs say it should work, but there is a bug.

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by kapunahelewong** [comment] 2017-11-09 19:59
This is a great find. Would you be willing to submit a PR for it? If so, feel free to tag me in it.

**Comment by gkalpak** [comment] 2017-11-10 10:54
Closing as duplicate of #20206.

**Closed by gkalpak** 2017-11-10 10:54 UTC
Labels: comp: docs, type: bug
