### ISSUE TITLE
macroTask 'requestAnimationFrame': can not transition to 'running'

### ISSUE THREAD

**Issue by Wallethub** [angular/angular#42486] opened 2021-06-05 01:36 UTC
Hello,

We just did an upgrade to our angular from 10 to 12 recently and right after it went live we started seeing this sentry coming:

macroTask 'requestAnimationFrame': can not transition to 'running', expecting state 'scheduled', was 'scheduling'.

We are not able to determine where it's coming from, none of our tests revealed the error on local or on our dev machines, and the only clues we have so far is that it's happening on Windows, only in Chrome (88 mostly) and, as stated, since the upgrade to 12.  It's also rare but when it comes it tends to come multiple times per user.
Now we use requestAnimationFrame in various places in our code, but if you can help us out with what changed regarding this so we can make the proper adjustments, it would be greatly appreciated.

**Comment by JiaLiPassion** [comment] 2021-06-07 14:58
@Wallethub , could you post a reproduce repo? Thank you.

**Comment by Wallethub** [comment] 2021-06-08 12:47
@JiaLiPassion we can't reproduce it, as mentioned earlier. Could you tell us what the impact can be? Is it that the call inside the requestAnimationFrame will not execute or that should if that setter, say `component.var = 1`, that would fail?

**Comment by JiaLiPassion** [comment] 2021-06-08 13:00
@Wallethub , it is very difficult to find the root cause without reproduction environment, I totally understand the case is rare and the possible reason is sometimes on `Windows` OS, the `callback` of the `requestAnimationFrame` may `re-entry` in some edge cases. Or some error occurs when calling `requestAnimationFrame` in some special `ZoneSpec`. I can try to create some debug version of zone.js but still need reproduce environment to verify whether it works or not.

**Comment by Wallethub** [comment] 2021-06-08 14:25
@JiaLiPassion well it has not happened since I reported. Thing is, I updated to zone 11.3 before angular 12. So I don't think it's something in the zone.js that did it unless it's in 11.4. We will see if it happens again and try to find a pattern to reproduce it.

**Comment by AndrewKushnir** [comment] 2021-06-08 17:56
Closing this ticket for now since there is no repro. Please reopen once more info is available. Thank you.

**Closed by AndrewKushnir** 2021-06-08 17:56 UTC
Labels: comp: zones, needs reproduction
