### ISSUE TITLE
Modules imported for side effects are not included in optimized bundle

### ISSUE THREAD

**Issue by amitbeck** [angular/angular#46178] opened 2022-05-29 12:27 UTC
### Which @angular/* package(s) are the source of the bug?

compiler

### Is this a regression?

No

### Description

I have a `index.ts` which imports 2 modules (`abstract-control.ts` and `abstract-control.directive.ts`) for side effects, and exports another module (`custom-control-status.directive.ts`) therefore also acting as a barrel file. `custom-control-status.directive.ts` is imported through the barrel file (`index.ts`), therefore I thought `index.ts` and the 2 modules imported for side effects would be included in the bundle, but they're removed in the tree shaking process.
I tried both of the following:
* specifying `"sideEffects"` in `package.json`'s:
    1. `"sideEffects": ["<path>/index.ts", "<path>/abstract-control.ts" and "<path>/abstract-control.directive.ts"]` in the app's `package.json`
    2. Add a `package.json` to the directory and set `"sideEffects": ["./index.ts", "./abstract-control.ts" and "./abstract-control.directive.ts"]` in it
    3. Add a `package.json` to the directory and set `"sideEffects": true` in it
* specifying a rule in Webpack's `module.rules` that matches every TS file in the directory and set `sideEffects: true`

Despite that, they are all excluded from the bundle. Could this be an issue with [Angular's webpack config](https://github.com/angular/angular-cli/blob/13.2.x/packages/angular_devkit/build_angular/src/webpack/configs/common.ts) or [`@angular-builders/custom-webpack`](https://github.com/just-jeb/angular-builders/tree/master/packages/custom-webpack)?

### Please provide a link to a minimal reproduction of the bug

https://github.com/amitbeck/ng-webpack-sideEffects-repro

### Please provide the exception or error you saw

```true
TypeError: this.formGroup.controls.text.setWarnings is not a function
```

(meaning `abstract-control.ts`, `abstract-control.directive.ts` and `index.ts` in `src/app/utils/forms/` are not included in the bundle)

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.2.6
Node: 16.13.1
Package Manager: npm 8.1.2
OS: darwin x64

Angular: 13.2.7
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router, service-worker, upgrade

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1303.1
@angular-devkit/build-angular   13.2.6
@angular-devkit/core            13.3.1
@angular-devkit/schematics      13.2.6
@angular/cdk                    13.2.6
@angular/cdk-experimental       13.2.6
@angular/cli                    13.2.6
@angular/material               13.2.6
@schematics/angular             13.2.6
rxjs                            7.5.5
typescript                      4.5.5
```

### Anything else?

Possibly related to https://github.com/angular/angular-cli/issues/12912 and https://github.com/webpack/webpack/issues/15610.
Also asked [a question in SO](https://stackoverflow.com/questions/72390897/why-are-these-modules-imported-for-side-effects-not-included-in-webpack-bundle) and asked a Webpack team member for help in https://github.com/webpack/webpack/issues/15610#issuecomment-1138473225.
Not sure if this issue is most relevant to Angular CLI or Angular itself, so I also opened https://github.com/angular/angular-cli/issues/23246.

**Comment by alan-agius4** [comment] 2022-05-29 12:57
Duplicate of https://github.com/angular/angular-cli/issues/23246#issuecomment-1140439299

**Closed by alan-agius4** 2022-05-29 12:57 UTC

**Comment by amitbeck** [comment] 2022-05-29 14:38
> Duplicate of [angular/angular-cli#23246 (comment)](https://github.com/angular/angular-cli/issues/23246#issuecomment-1140439299)

So Angular CLI was indeed the correct repo in which to open this issue? Thanks and sorry for the noise 👍🏻
