### ISSUE TITLE
URLSearchParams plus sign bug

### ISSUE THREAD

**Issue by laserus** [angular/angular#12043] opened 2016-10-03 14:46 UTC
**I'm submitting a
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

When doind urlSeachParams append with object containing "+" sign the toString() function replaces it with spaces. E.g. in such code, where obj['timestamp'] = "2016-10-03T13:27:25+00:00": 
```
import { URLSearchParams } from 'angular2/http';

export function urlEncode(obj: Object): string {
    let urlSearchParams = new URLSearchParams();
    for (let key in obj) {
        urlSearchParams.append(key, obj[key]);
    }
    return urlSearchParams.toString();
}
```

Consider looking at https://github.com/angular/http/issues/96. It was here for some time.

Is there work a around for now? Except, avoiding plus sign for ISO8601 in params.

**Comment by ericmartinezr** [comment] 2016-10-03 14:49
The issue is being tracked here https://github.com/angular/angular/issues/11058

**Comment by laserus** [comment] 2016-10-03 14:49
@ericcarraway Ok, thanks. Can be closed

**Comment by DzmitryShylovich** [comment] 2016-10-03 14:54
You can close it yourself.

**Closed** 2016-10-03 14:54 UTC
