### ISSUE TITLE
HttpInterceptor behavior changed from 4.3.0 to 4.3.3

### ISSUE THREAD

**Issue by rekna1** [angular/angular#19596] opened 2017-10-06 15:16 UTC
## I'm submitting a...

<pre><code>
[ x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
When implementing a catch on next() in intercept method of custom interceptor ,  the err.error property now contains json string
```

@Injectable()
export class CustomHttpInterceptor implements HttpInterceptor {

  constructor(private loadingData: LoadingData, private errorDialogService: ErrordialogService) { }

  private outstandingCalls = 0;
  intercept(req: HttpRequest<any>, next: HttpHandler): Observable<HttpSentEvent | HttpHeaderResponse | HttpProgressEvent | HttpResponse<any> | HttpUserEvent<any>> {

return next.handle(req)
      .catch(err => {
        if (err instanceof HttpErrorResponse) {
          if (err.status === 500) {
            this.errorDialogService.setErrorData(<IErrorData>err.error); // err.error changed
            return Observable.empty<HttpResponse<any>>();
          }
        }
      }).finally(()=>
        this.decreaseOutstandingCalls()
      );
```

## Expected behavior
Previously the err.error was an parsed json object

## Minimal reproduction of the problem with instructions
We are using an interceptor to handle status 500 errors from the server. When the server application encounters an exception we return a response with status 500 and an json string containing information about the error. (see the catch statement of the next method in the interceptor example above)
The response is of type application/json.

## What is the motivation / use case for changing the behavior?
Global error handling on all http requests on HttpClient. When server returns status 500 a json string is send with the response containing information to be displayed in the browser.

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 6.10.3
- Platform:  Windows

**Comment by ocombe** [comment] 2017-10-06 16:05
Hello, what version of Angular are you using? And what version used to work previously?

**Comment by rafaelss95** [comment] 2017-10-06 22:22
Duplicate of an issue that I created. #19103

**Comment by ernitishkumar** [comment] 2017-10-09 19:36
I am also facing the same issue even with GET request which fails with error.
Only the body of Error response is parsed to Json not the successful requests. Successful request are working as expected returning Json Object in the response body. But the failed request are returning Json object as a string in the Error Response body.
It was working fine till the version 4.3.6. All Error Handling code went haywire after updating my project to Angular version 4.4.3 !

Don't want to apply patch, I hope Team Angular will fix this in coming builds. Till the downgrading to working 4.3.6

**Comment by alxhub** [comment] 2017-10-19 16:28
Closed as this is a duplicate of the original bug (which is fixed).

**Closed by alxhub** 2017-10-19 16:28 UTC
Labels: comp: common/http, severity5: regression
