### ISSUE TITLE
Please improve the test double documentation

### ISSUE THREAD

**Issue by dgroh** [angular/angular#18933] opened 2017-08-29 16:24 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
The current test double documentation is IMO kind of trivial. For instance if we have to mock `queryParameters` or in case we have a `parent` route, this won't help very much.

## Expected behavior
I wish to test `queryParameters` and `parent` route with test double and understand them from the documentation. 

## Minimal reproduction of the problem with instructions
There is a post of mine on stackoverflow where I try to test parent route subscription:

https://stackoverflow.com/questions/45942899/angular-4-writing-test-properly-for-a-parent-route-subscription

I also created a plunker for that: 

https://plnkr.co/edit/2SXzvSDe3OiwvvRJYXfN?p=preview

## What is the motivation / use case for changing the behavior?
When tests involve routing, they might get very difficult to test because of mocks and observables, so I wish a better documentation with a few more examples.

## Environment

<pre><code>
Angular version: 4.3.6

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by dgroh** [comment] 2017-09-06 13:38
It would also be nice to specify how to get `ActivatedRoute` changed.

Thing is if I mock `ActivatedRoute`, when I call `router.navigate` in my test, the `ActivatedRoute` won't get the changes made by `router.navigate`. 

This is very useful for Acceptance and Integration tests.

**Comment by atscott** [comment] 2021-05-24 17:59
Closing as duplicate of #15779

**Closed by atscott** 2021-05-24 17:59 UTC
Labels: comp: docs, comp: router, comp: testing, effort3: weeks, feature, freq2: medium, subtype: docs-completeness
