### ISSUE TITLE
regression(compiler-cli): different code output between ngc and tsc v5

### ISSUE THREAD

**Issue by Toxicable** [angular/angular#19339] opened 2017-09-22 20:34 UTC
## I'm submitting a...
<pre><code>[x] Regression</code></pre>
**v5.0.0-beta.7**
Minimal Repo: https://github.com/Toxicable/ngc-outputchange
Instructions: https://github.com/Toxicable/ngc-outputchange/blob/master/modules/module-name/index.ts

This has caused a regression for how we use `ngc` over on `angular/universal` see: https://github.com/angular/universal/issues/805 (partially out fault since we don't have testing)

When you have nested submodules that have their own tsconfig's and you run `ngc` it will output node_modules(just metadata) along with the full directory path, rather than just the sub module

Input:
`/modules/module-name/index.ts`
`/modules/module-name/tsconfig`

Output:
ngc:`/dist/module-name/modules/module-name/index.js`
tsc: `/dist/module-name/index.js`

**Comment by vikerman** [comment] 2017-09-22 22:13
Could work around it in angular/universal by setting "skipTemplateCodegen": true in "angularCompilerOptions" in tsconfig.json. But this is a regression in ngc that should be fixed.

**Comment by chuckjaz** [comment] 2017-09-27 18:06
This is a side-effect of our now ignoring `"genDir"`.

We should consider paying attention to `"genDir"` to avoid breaking builds that used `"genDir"` instead of `"skipTemplateCodegen"` to work around this issue.

**Details**

The reason the location moves is because TypeScript infers the base directory from the common root directory of all files included in the project. Without "genDir" the factory files are produced in the corresponding directory in `node_modules`. This makes the inferred `baseDir` to be the project root directory instead of the directory containing the `tsconfig.json` file.

Supplying `"genDir"` in 4.0 caused the files to be generated as a subdirectory of the directory containing the `tsconfig.json` file avoiding this issue.

Supplying `"skipTemplateCodegen"` in both 4.0 and 5.0 avoids this issue because the factory files are not generated and are not added to the project avoiding this issue.

**Comment by tbosch** [comment] 2017-10-03 20:34
Closing as works as intended, but we need to document this different behavior.

**Closed by tbosch** 2017-10-03 20:34 UTC
Labels: comp: core & compiler, severity5: regression, type: bug

**Comment by vforv** [comment] 2017-11-18 16:55
Not working for me....

`src/main.client-closure.ts(2,42): error TS2307: Cannot find module '../built/src/app/app.client.module.ngfactory'.`

Compiler not generading files...
