### ISSUE TITLE
APP_INITIALIZER should block BASE_PATH_HREF provider

### ISSUE THREAD

**Issue by Modellium** [angular/angular#20383] opened 2017-11-13 00:16 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ X ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
useFactory for BASE_PATH_HREF is fired before useFactory for APP_INITIALIZER

## Expected behavior
useFactory for APP_INITIALIZER should fire before BASE_PATH_HREF

## What is the motivation / use case for changing the behavior?
I wan't to get a set of allowed basepath from the server before the app loads.

**Comment by wKoza** [comment] 2017-11-13 19:51
same problem #19448 ?

**Comment by mhevery** [comment] 2017-11-30 23:19
duplicate of  #19448

**Closed by mhevery** 2017-11-30 23:19 UTC
Labels: comp: core & compiler, type: feature
