### ISSUE TITLE
Determine which Observable operators and extensions to include in angular core

### ISSUE THREAD

**Issue by robwormald** [angular/angular#4390] opened 2015-09-28 04:33 UTC
Now that https://github.com/angular/angular/pull/2974 has landed, we're exposing the "bare" RxNext Observable without any operators included. This is partially because including the main Rx import caused everything to explode (as it has a large amount of files) and partially to avoid bloating the core codebase with another ~125k of operators.

The list of currently implemented operators is here: https://github.com/ReactiveX/RxJS/tree/master/src/operators

A core set of of them should be included, things like `map`, `flatMap`, `flatMapLatest`, `take`, `filter`, `reduce`, `scan`, `merge`, and `toPromise`. Additionally specific operators can be exposed for specific APIs - for example, Http should add `retry` and `retryWhen` (or some equivalent)

Also, a set of specific Observable utility implementations are available - things like `Observable.from`, `Observable.fromArray`, `Observable.interval`, etc. The list of these is here: https://github.com/ReactiveX/RxJS/tree/master/src/observables

Alternately we could fix the build issue and simply bring in the entire `Rx` module for now, and pare it down as we move closer to production and begin to optimize.

cc @jeffbcross @vsavkin 

edit: the ES6 version is ~250k for the complete unminiified Rx, roughly ~half of which is operators. For CJS, its ~350k with again roughly half being operators.

**Comment by gdi2290** [comment] 2015-09-28 04:42
can you also include `Observable.of` and `Observable.defer`?

**Comment by jeffbcross** [comment] 2015-09-28 05:58
It would be nice to provide a minimum set of operators, as you've described, by default from Angular APIs that export `Observables`. And to allow users who'd like a different set of operators, they should be able to override an `ObservableFactory` binding with DI (name not important right now). So when overriding that binding, calling `http.get()` would return an observable with the operators I need.

**Comment by jeffbcross** [comment] 2015-09-28 06:05
If we include an `Observable` factory in DI, it's worth considering whether the same should be done for `Promise`.

**Comment by gkalpak** [comment] 2015-09-28 06:32
:+1: and :+1: (1 for `Observable` and 1 for `Promise` factory).

**Comment by mhevery** [comment] 2015-09-29 22:43
I would vote to not include any in Angular2.

**Comment by robwormald** [comment] 2015-09-29 23:03
Problem with that is at the moment there's not really a good way to add them after the fact to Observables returned from the core, at least in TS:
```js
//without operators:
http.get('foos.json').subscribe(res => {
  this.foos = res.json();
});

//with .map included, connected to an async pipe
this.foos = http.get('foos.json').map(res => res.json());

//with .retry() included
this.foos = http.get('foos.json').retry(3).map(res => res.json());
```

The ES7 functionBind proposal gives us a nice solution, but its not currently supported in TS:
```js
import {map, retry} from './myoperators'

this.foos = http.get('foos.json')::retry(3)::map(res => res.json());
```

Dart has a distinct advantage here as they provide a similar set in the language itself on Streams:
https://api.dartlang.org/1.12.1/dart-async/Stream-class.html#instance-methods

**Comment by blesh** [comment] 2015-09-30 21:22
Without es7 function bind support in TypeScript, I'd recommend just including the current RxJS 5 Core Operators. There are a lot, but frankly they're a subset, and they're things that people want.

If you really don't want to include those, you could just mirror the Rx.ts file and create your own "lite" version... But then you'll be stuck supporting requests for the other operators.

... So my recommendation is use Rx as-is. And come make arguments to have ones removed you don't think are "core" enough.

**Comment by blesh** [comment] 2015-09-30 21:25
FWIW, the ones in RxJS 5 Core are ones that are non-trivial to reproduce with any combination of other operators. That's the goal at least.

Most of them were chosen because of their usage within Netflix apps.

**Comment by jeffbcross** [comment] 2015-10-05 22:36
We had a meeting with @IgorMinar, @blesh and @robwormald today to discuss this issue. We wanted to come to a solution that would allow us to keep the byte size of angular2 core small, and make it easy for Rx power-users to easily get useful operators.

My proposal was to use a "lite" Observable with only a `subscribe` method, and use DI and provide an ObservableFactory token that could be overwritten:

```typescript
import {Observable} from '@reactivex/rxjs/Rx';
// Bind the included factory to a full-featured Observable with default set of operators
bootstrap(MyComponent, [bind(ObservableFactory).toValue(Observable)]);
```

@mhevery brings up the point that by requiring an injector, users could not take advantage of field assignment shorthand provided by TypeScript.

```typescript
class MyComponent {
  someEvent = new EventEmitter(); // EventEmitter couldn't use DI in this case, unless refactored to accept an Observable argument.
}
```

My counter-argument to that is that if users wanted to instantiate their own Subjects/Observables, they could just import the one the same one they've already bound to `ObservableFactory` token, and just instantiate it themselves without DI. It's up to whomever is consuming the component's events to know the shape of the `Observable` being provided. The benefit of the DI binding should only be for the angular framework itself to produce the shape of `Observable` that the consumer would like.

However, there are still issues with type information with the DI approach. For angular APIs that say they return an Observable from Angular (Observable lite), any code that consumes such an Observable would not automatically know that the binding had been replaced with a new shape of `Observable`.

Another discussion topic that came up was strategies for composing operators. Right now it's possible to compose operators onto an `Observable` instance using the `lift` method. The current RxJS design is  prototype-based, so monkey-patching or extending are the way to add default operators.

Random notes, I know, but wanted to get them out there before I forget. 

Did I miss or misrepresent anything @blesh @robwormald @IgorMinar?

**Comment by blesh** [comment] 2015-10-05 23:35
So to be clear, the `lift` method allows you to use an `Operator` from RxJS, which is a `Subscriber` factory to chain operators, but it's *very* unergonomic to do so.

One could either: 

1. Decorate the prototype
2. Subclass Observable, overriding `lift` to return the Subclass, and add whatever operators you care about to that.
3. Use ES7 function bind, which is available in Babel, but not TypeScript.

I think if you had an ObservableFactory create your Observable class for you, you could have that be responsible for decorating the Observable.prototype. I don't know enough about Angular's current DI, but I presume it can dynamically create classes to be injected, and not just object instances?

**Comment by jeffbcross** [comment] 2015-10-05 23:39
> I don't know enough about Angular's current DI, but I presume it can dynamically create classes to be injected, and not just object instances?

Yes, `toValue` wouldn't necessarily be the strategy used. There is also `toClass`, `toFactory`, `toAlias`...maybe others.

**Comment by jeffbcross** [comment] 2015-10-06 17:53
I just I just uglified and gzipped the dist/global/Rx.min.js bundle, and it is 37KB.

**Comment by jeffbcross** [comment] 2015-10-06 17:56
I browserified, uglified, and gzipped just the Observable using dist/cjs/Observable.js, and it is 4KB.

**Comment by jeffbcross** [comment] 2015-10-06 19:01
In the short-term, this essentially comes down to a decision between a user experience trade-off between two competing priorities:

 * Option 1: Include Observable + core operators that are included in [Rx.js](https://github.com/ReactiveX/RxJS/blob/master/src/Rx.ts). 
   * Benefit: User automatically gets all the operators they'll likely want
   * Cost: 
     * 33KB extra in the core
     * For users who really don't want those bytes, they would need to rewrite import paths as part of a build process or loader configuration. Though, users who care this much are probably the types of users who are comfortable writing custom build processes and loader configurations.
 * Option 2: Include only Observable, only with absolute minimum operators (subscribe/foreach)
   * Benefit: 33K fewer bytes
   * Cost: 
     * If a consumer wants to use Observable+core operators, they would have to re-cast any angular-exported observable to the the standard Rx observable using `Rx.from(someAngularObservable);`
     * We could use DI to allow overriding an `ObservableFactory` binding, so that users could bring-their-own-observable for Angular to use. But this would require a user to _know_ about this binding, and require them to add the binding when bootstrapping their application
     * We could suggest that users simply mutate the "global" Observable prototype to include the operators they'd like. I believe this behavior already occurs by merely importing Rx.js, according to @vsavkin. This is generally considered a Bad Idea™, and goes against the ethos of Angular 2.
     * Typing information would be lost when replacing the plain Observable with a different-shaped Observable. The user would have to explicitly re-cast every Observable exported by Angular every place an Angular Observable is being consumed.

I personally favor Option 1, but I don't have as much context as @IgorMinar or @mhevery as to byte budgets.

The _longer term_ approach is to focus on simplifying distribution and composition of operators, as well as helping to move forward standards that make this nicer (i.e. [function bind](https://github.com/zenparsing/es-function-bind)).

**Comment by blesh** [comment] 2015-10-06 19:20
> I believe this behavior already occurs by merely importing Rx.js, according to @vsavkin. This is generally considered a Bad Idea™, and goes against the ethos of Angular 2.

PRs welcome™

I'm in favor of Option 1, as well. And I'm willing to work with the community of RxJS and Angular to determine which operators should and should not be "core".

Also that would enable RxJS to put all "Core" operators directly on Observable, which helps a few other issues.

**Comment by jeffbcross** [comment] 2015-10-06 20:08
> PRs welcome™

@blesh sorry, that wasn't meant to be a dig on RxJS, I was referring to the idea of mutating some shared global object not being an approach we should recommend.

**Comment by mhevery** [comment] 2015-10-06 21:28
I think we should thing more about Option #2:

* Adding (mutating) global state for the purposes of code loading is OK (data is bad)
* I believe there is a way to extend the `.d.ts` file with another file so that the typings are preserved. So no casting should be necessary.

**Comment by blesh** [comment] 2015-10-06 21:34
@mhevery what is "not a lot"? 20K? 15K? 10K?

**Comment by pkozlowski-opensource** [comment] 2015-10-06 21:39
to put bytes / size in context: ng1 is around 50k (min + gzip), react weights around 30k. I'm not sure if we are talking about 33k min + gzip here but if so it would be a lot in my books as well :-)

**Comment by gkalpak** [comment] 2015-10-06 21:45
Based on @jeffbcross's comments (e.g. https://github.com/angular/angular/issues/4390#issuecomment-145945321), it is indeed minified + gzipped.
But equally important is how much does ng2 "weight" (minified + gzipped).

**Comment by blesh** [comment] 2015-10-06 21:53
One thing to know, the current "minified" version of RxJS 5 is *not* very minified. I don't think it's even mangling variable names. Could probably cut that down quite a bit.

**Comment by blesh** [comment] 2015-10-06 21:54
What is Angular 2 min & gzipped?

**Comment by blesh** [comment] 2015-10-06 22:01
FWIW, if I run the current output Rx.js file through Closure Compiler it's `23.44KB gzipped`

**Comment by blesh** [comment] 2015-10-06 22:01
FWIW, if I run the current output Rx.js file through Closure Compiler it's `23.44KB gzipped`

... I'm sure we can probably cut another ~3-5K out of that here or there.

**Comment by blesh** [comment] 2015-10-06 22:03
... In fact, I bet a lot of that is just repetitious cruft from transpiling classes and modules.

**Comment by pkozlowski-opensource** [comment] 2015-10-07 06:08
ng2 core bundle is currently ~110K, including Rx. But my understanding is that the goal is to get this number down to < 70K (and still keeping current size of ng1 as the number we should aim for)

**Comment by blesh** [comment] 2015-10-07 06:49
You couldn't get there if you completely removed Rx. It's only 23k right now. I suspect we could get it to 18k or so... But still.

**Comment by robwormald** [comment] 2015-10-07 07:01
Seems like maybe bytes isn't a great thing to base this decision off anyway, as the ideal case is some-tool (a la rollup) stripping out unused code / modules anyway in the not-too-distant future, so its hard to quantify what "Rx" or "Angular2" actually weighs?

**Comment by jeffbcross** [comment] 2015-10-08 17:33
@robwormald AFAIK rollup only works to tree-shake never-imported exports from ES6 modules. It would require some refactoring for Rx to take advantage of this (and angular, too, I'm sure) since operators are on the prototype.

**Comment by blesh** [comment] 2015-10-08 19:35
We'd be better off getting ES7 function bind into TypeScript.

... although using ES7 function is likely a hit to operator performance I would guess. But probably nothing most people care about.

**Comment by jeffbcross** [comment] 2015-10-13 00:38
Moving this into 41, working on a simple solution to manually add the combinators we need to EventEmitter without changing anything about its inheritance.

**Closed** 2015-10-30 20:57 UTC
Labels: comp: data-access, effort2: medium (day), P1: urgent, type: RFC / discussion / question
