### ISSUE TITLE
Removing components with ngIf creates detached DOM Elements causing Memory Leak

### ISSUE THREAD

**Issue by aavelyn** [angular/angular#43275] opened 2021-08-27 09:08 UTC
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

Removing components with ngIf creates detached DOM Elements causing Memory Leak

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-6gtybe

### Please provide the exception or error you saw

```true
1. Toggle the table component a couple of times
2. Do a memory heap snapshot
3. Search `detached` and you will find Detached Table DOM Elements, which won't go away
4. The performance monitor also shows an increase of DOM nodes
```

### Please provide the environment you discovered this bug in

see Stackblitz package.json (I was able to reproduce the bug in Angular 11 and 12)

**Comment by gkalpak** [comment] 2021-08-30 19:07
Closing as a duplicate of #42848.

**Closed by gkalpak** 2021-08-30 19:07 UTC
Labels: comp: core

**Comment by aavelyn** [comment] 2021-08-31 08:31
@gkalpak I've read through #42848, there wasn't a single notion on detached DOM nodes, could you elaborate a bit why?
Thanks!

**Comment by gkalpak** [comment] 2021-09-01 13:34
Ooops, you are right, @aavelyn. It might not be the same issue, because in your example the event listener is outside the embedded view (i.e. outside the `ngIf` template).

However, looking at your example more closely, I can't see any detached nodes. Could you give more detailed instructions on how to reproduce the issue. (Also make sure you run garbage collection before taking snapshots (just in case).)
