### ISSUE TITLE
Incorrect link to docs in tutorial "Updating the component"

### ISSUE THREAD

**Issue by Melkye** [angular/angular#52822] opened 2023-11-11 17:20 UTC
### Describe the problem that you experienced

Page not found when trying to open `type inference in TypeScript` in tutorial "Updating the component". The link is https://angular.dev/typescript.org/type-inference

### Enter the URL of the topic with the problem

https://angular.dev/tutorials/learn-angular/updating-the-component-class

### Describe what you were looking for in the documentation

Type inference in TypeScript

### Add a screenshot if that helps illustrate the problem

![image](https://github.com/angular/angular/assets/60851956/1da86fc0-b629-4edc-804e-89ae6ce6bbde)

### Provide any additional information here in as much as detail as you can

```true
I guess this link was supposed to be there
https://www.typescriptlang.org/docs/handbook/type-inference.html
```

**Comment by JoostK** [comment] 2023-11-11 17:24
Thanks for the report! This is a duplicate of #52553.

**Closed by JoostK** 2023-11-11 17:24 UTC
