### ISSUE TITLE
Diagram does not match description

### ISSUE THREAD

**Issue by Rajendran-Balaji** [angular/angular#56345] opened 2024-06-09 10:04 UTC
### Describe the problem that you experienced

In the documentation 
> Angular will check all the green components from the diagram below 

But in the Diagram there are no green components marked

![image](https://github.com/angular/angular/assets/88931771/609d6255-7f4b-491c-b106-0e4f46d942b3)

In the old website [Angular V17](https://v17.angular.io/guide/change-detection-skipping-subtrees)
![image](https://github.com/angular/angular/assets/88931771/e1b8e76f-df9d-46a0-8dcd-d8ea2941a137)

### Enter the URL of the topic with the problem

https://angular.dev/best-practices/skipping-subtrees

**Comment by sasidharansd** [comment] 2024-06-09 14:10
Looks like duplicate of the issue: https://github.com/angular/angular/issues/56314

**Comment by JoostK** [comment] 2024-06-09 14:35
Closing as duplicate of #56314 (thanks @sasidharansd)

**Closed by JoostK** 2024-06-09 14:35 UTC
