### ISSUE TITLE
Can't bind to 'ngPluralCase' since it isn't a known property of 'ng-container'.

### ISSUE THREAD

**Issue by n00dl3** [angular/angular#12363] opened 2016-10-18 11:47 UTC
**I'm submitting a ...**  (check one with "x")

```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Using the ngPluralCase directive throw an exception:

> Can't bind to 'ngPluralCase' since it isn't a known property of 'ng-container'.

**Expected behavior**
It should just work

**Minimal reproduction of the problem with instructions**
I used the [documentation](https://angular.io/docs/ts/latest/api/common/index/NgPlural-directive.html) as base to build this (I didn't try with AOT, but it fails in the browser):

_main.ts_ [check in plnkr](https://embed.plnkr.co/LzhoDs/):

``` typescript
import { platformBrowserDynamic } from "@angular/platform-browser-dynamic";
import { Component, NgModule } from "@angular/core";
import { BrowserModule } from "@angular/platform-browser";

@Component({
  selector: "my-app",
  template:`
  <div [ngPlural]="1">
      <ng-container *ngPluralCase="'=0'">...</ng-container>
      <ng-container *ngPluralCase="'other'">...</ng-container>
  </div>
  `,
  styles: []
})
class AppComponent {

}

@NgModule({
  imports: [
    BrowserModule
  ],
  declarations: [AppComponent],
  exports: [AppComponent],
  bootstrap: [AppComponent]
})
class AppModule { }


platformBrowserDynamic().bootstrapModule(AppModule);
```

**Please tell us about your environment:**
- **Angular version:** 2.1.0
  
  
- **Browser:** Chromium 53 (didn't test others)
  
  
- **Language:** TypeScript 2.0.3

**Comment by DzmitryShylovich** [comment] 2016-10-18 12:25
Can u please provide a working reproduction in plunkr?

**Comment by n00dl3** [comment] 2016-10-18 13:50
https://plnkr.co/edit/LzhoDs?p=preview

**Comment by rodneyjoyce** [comment] 2016-11-29 01:39
+1 for a fix please

**Comment by vicb** [comment] 2017-01-10 17:38
The problem here is actually that the `NgPluralCase` directive uses an `@Attribute` injection and because `ng-container` are virtual nodes, attributes can not be retrieved on them.

You have to use a `<template>` tag in this case, the docs will be fixed as part of a pending PR.

**Closed by vicb** 2017-01-10 17:38 UTC
Labels: comp: i18n

**Comment by amaschas** [comment] 2017-01-18 22:40
Using `<template>` generates the same error: `Can't bind to 'ngPluralCase' since it isn't a known property of 'template'.`

**Comment by DzmitryShylovich** [comment] 2017-01-18 22:46
@amaschas reproduce on Plunkr and file a new issue
