### ISSUE TITLE
large bundle size when i use Angular 5

### ISSUE THREAD

**Issue by teabagp** [angular/angular#20414] opened 2017-11-14 06:37 UTC
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When I build the project in Angular 5 the size of the bundle turns out to be very large

## Expected behavior

In Angular 4 the size of the bundle is smaller

## Minimal reproduction of the problem with instructions

You can reproduce the problems using [my example](https://github.com/teabagp/testapp). Use command ng build --prod

## Environment

<pre><code>
Angular version: 5.0.1

</code></pre>

**Comment by fxck** [comment] 2017-11-14 06:57
Dupe of https://github.com/angular/angular/issues/20387

**Comment by Toxicable** [comment] 2017-11-14 07:04
looks like your specific case has an issues with the lib you're using
if you analyze the bundle then you'll notice that the entire of that lib is included in your bundle

**Comment by teabagp** [comment] 2017-11-14 07:53
@Toxicable why it worked with Angular 2 and 4 versions?

**Comment by filipesilva** [comment] 2017-11-14 16:51
Heya, I can reproduce this issue but will open it on the Angualr CLI issue tracker instead as I don't think it's a core Angular issue (it is a problem with Angular CLI instead).

**Comment by filipesilva** [comment] 2017-11-14 16:55
The Angular CLI issue for this problem is https://github.com/angular/angular-cli/issues/8457.

**Comment by jasonaden** [comment] 2017-11-14 17:34
Closing as duplicate. Please track the CLI issue above.

**Closed by jasonaden** 2017-11-14 17:34 UTC
