### ISSUE TITLE
ngFor. Can't use const with ngFor ?

### ISSUE THREAD

**Issue by vanluke** [angular/angular#9209] opened 2016-06-15 09:31 UTC
* **I'm submitting a ...**
- [ X ] feature request

**Current behavior**
for example <li *ngFor="const hero of heroes">
When use const with ngFor get an error 

Uncaught (in promise): Template parse errors:
Can't bind to 'ngFor' since it isn't a known native property ("

**Expected/desired behavior**
be able to use const with ngFor
** Live example on plnkr http://plnkr.co/edit/O6HhvfIzHAJx4w2kzbVv?p=preview

* **Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.1
 
* **Browser:** [Chrome  51.0.2704.84] 
 
* **Language:** [TypeScript 1.8 | ES6/7 ]

**Comment by pkozlowski-opensource** [comment] 2016-06-15 09:34
Please provide more info / live reproduce in plunker as requested here: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue

Without a plunk with a reproduction scenario we will have no choice but to close this one as not actionable.

**Comment by zoechi** [comment] 2016-06-15 10:02
Works fine when you change `const` to `let`. Why would you need `const` here?
I think this is just "as designed"
http://plnkr.co/edit/bJ6TpQxM4gFEBgCIfxWU?p=preview

**Comment by vanluke** [comment] 2016-06-15 10:06
because it is not correct. let means you can mutate data. I do not wont that. By using const i am teling that this variable is readonly

**Comment by mahpah** [comment] 2016-06-15 10:13
> because it is not correct.

Really? It's your taste, I don't think something is right or wrong here.

FYI,
https://blog.getify.com/constantly-confusing-const/

**Comment by kemsky** [comment] 2016-06-15 11:38
most probably we should consider more general case:
to be able to define template variables as constants, in other words prevent/detect their modification/override/redefinition.

sometimes you could define two variables with the same name (#var and #var) by mistake and there is no warning and no error message that could help to trace this problem.

**Comment by pkozlowski-opensource** [comment] 2016-06-15 19:46
@vanluke what you write in "ngFor" is not JS but a ng2-specific syntax. We are not aiming at replicating the _whole_ JS syntax in templates.

@kemsky with rc.2 exceptions are thrown for multiple declarations of the same variable, see: https://github.com/angular/angular/commit/9036f78b743f788085145c91b080b58f3a0984df

**Closed by pkozlowski-opensource** 2016-06-15 19:46 UTC

**Comment by bentaly** [comment] 2017-09-15 10:51
@mahpah it's not taste it's telling the engine that it wont be manipulated and therefore free to enable optimisations, it should be included

**Comment by ShinDarth** [comment] 2017-09-26 16:21
+1

**Comment by trotyl** [comment] 2017-09-27 01:39
@bentaly All template context "variables" are properties, not variables, it's nothing to do with JavaScript `let/const` semantics, just a design choice.

**Comment by bentaly** [comment] 2017-09-27 12:27
seems a confusing choice to use a micro syntax here that's very close to the ES6 implementation of for of, one of the gotchas which people seem to push people to React

**Comment by jasonwr** [comment] 2018-08-03 22:31
Yeah this is odd. Not sure why the call was made to apply a micro-syntax. Seems like overkill. I don't see the logic here. Also why change the semantics of the ng. For example in AngularJS you could simply do this **ng-for** but now it's ***ngFor** Not sure what the reasoning was there.
