### ISSUE TITLE
Autocomplete demo on stackbliz not working

### ISSUE THREAD

**Issue by IsaacSomething** [angular/angular#43076] opened 2021-08-08 10:17 UTC
### Description

The demo for autocomplete on stackbliz seems to be broken

### What is the affected URL?

https://material.angular.io/components/autocomplete/examples

### Please provide the steps to reproduce the issue

Click to open one of the examples on which should redirect you to stackbliz

### Please provide the expected behavior vs the actual behavior you encountered

The demo in stackbliz should be working

### Please provide a screenshot if possible

![error](https://user-images.githubusercontent.com/25283027/128628617-8b002c83-2091-452c-b475-366c030272d3.PNG)

### Please provide the exception or error you saw

```true
Error in turbo_modules/@angular/material@12.2.0/table/table-module.d.ts (8:22)
Appears in the NgModule.exports of DemoMaterialModule, but could not be resolved to an NgModule, Component, Directive, or Pipe class.

This likely means that the dependency (@angular/material/table) which declares MatTableModule has not been processed correctly by ngcc.
```

### Is this a browser-specific issue? If so, please specify the device, browser, and version.

```true
Getting this error in Brave and chrome, i dont think it is browser specific. Maybe something wrong with stackbliz
```

**Comment by indraraj26** [comment] 2021-08-08 10:49
Same error for all the angular material demo

**Comment by JoostK** [comment] 2021-08-08 11:06
Duplicate of #43069, angular/components#23270.

**Closed by JoostK** 2021-08-08 11:06 UTC
