### ISSUE TITLE
Strict mode not working in a new Angular app.

### ISSUE THREAD

**Issue by Trent-Matthias** [angular/angular#34838] opened 2020-01-17 20:12 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....

### Is this a regression?

Yes, this works in Angular 8.

### Description

 A clear and concise description of the problem...
If strict mode is on, the app will fail to compile.

## 🔬 Minimal Reproduction

Generate a new project with the latest version of the CLI and add strict: true to the tsconfig.json.

## 🔥 Exception or Error
<pre><code>

ERROR in node_modules/@angular/compiler/src/output/abstract_emitter.d.ts:23:17 - error TS7033: Property '_currentLine' implicitly has type 'any', because its get accessor lacks a return type annotation.

23     private get _currentLine();
                   ~~~~~~~~~~~~
node_modules/@angular/compiler/src/output/abstract_emitter.d.ts:42:17 - error TS7033: Property 'sourceLines' implicitly has type 'any', because its get accessor lacks a return type annotation.

42     private get sourceLines();
                   ~~~~~~~~~~~
node_modules/@angular/compiler/src/output/source_map.d.ts:26:17 - error TS7033: Property 'currentLine' implicitly has type 'any', because its get accessor lacks a return type annotation.

26     private get currentLine();
                   ~~~~~~~~~~~

</code></pre>


## 🌍  Your Environment

**Angular Version:**
<pre><code>
<!-- run `ng version` and paste output below -->
<!-- ✍️-->
@angular-devkit/architect         0.900.0-rc.9
@angular-devkit/build-angular     0.900.0-rc.9
@angular-devkit/build-optimizer   0.900.0-rc.9
@angular-devkit/build-webpack     0.900.0-rc.9
@angular-devkit/core              9.0.0-rc.9
@angular-devkit/schematics        9.0.0-rc.9
@ngtools/webpack                  9.0.0-rc.9
@schematics/angular               9.0.0-rc.9
@schematics/update                0.900.0-rc.9
rxjs                              6.5.4
typescript                        3.6.4
webpack                           4.41.2
</code></pre>

**Anything else relevant?**
<!-- ✍️Is this a browser specific issue? If so, please specify the browser and version. -->
This is with the default tsconfig with just strict: true added.

tsconfig:
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist",
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "module": "esnext",
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "es2015",
    "typeRoots": ["node_modules/@types"],
    "lib": ["es2018", "dom"],
    "strict": true
  },
  "angularCompilerOptions": {
    "fullTemplateTypeCheck": true,
    "strictInjectionParameters": true
  }
}

**Comment by JoostK** [comment] 2020-01-17 20:16
Duplicate of #34807, please find more info there.

**Closed by JoostK** 2020-01-17 20:16 UTC
