### ISSUE TITLE
Documentation for Tour of Heroes, Hero Editor environment

### ISSUE THREAD

**Issue by ink-su** [angular/angular#18878] opened 2017-08-25 14:34 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

There seems to be a continuity error for the Tour of Heroes Tutorial.

In Step 2: The Hero Editor, the setup instructions do not result in the base hero app.
Instructions for setting up angular-tour-of-heroes are not provided in the tutorial, rather only setting up quickstart.

## Expected behavior

Following setup instructions in https://angular.io/tutorial/toh-pt1 should result in the plinkr example page.

## Minimal reproduction of the problem with instructions

Setup the environment for local development: https://angular.io/tutorial/toh-pt1
Compare to the plinkr example: https://angular.io/generated/live-examples/toh-pt1/eplnkr.html

## What is the motivation / use case for changing the behavior?

Tutorial should be clear and easy to follow for new users.

## Environment

<pre><code>
Live Documentation

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 

</code></pre>

**Comment by Foxandxss** [comment] 2017-09-01 16:30
There are changes coming for the tutorial and the way it is setup. Stay tuned.

**Comment by rushter777** [comment] 2017-09-04 13:08
https://angular.io/tutorial/toh-pt1#the-road-youve-travelled 
specifically the code stating it should read as follows:
@Component({
  selector: 'my-app', 

but if you change it to that from all of the previous instructions - 
@Component({
  selector: 'app-root',

it breaks.

**Comment by Foxandxss** [comment] 2017-09-04 13:12
If you change that, you need to change the index.html as well, which is looking for that selector.

**Comment by rushter777** [comment] 2017-09-04 14:28
Thanks.
Now found more errors on second page of tutorial.
Frustrating.

**Comment by Foxandxss** [comment] 2017-09-04 14:31
That is actually not an error. You need to follow the tutorial using the [quickstart project](https://github.com/angular/quickstart) and not the CLI.

That will change in this month where we are going to revamp the tutorial to use the CLI.

**Comment by Nicolas-Bouteille** [comment] 2017-11-03 00:00
New to Angular, noticed this too! I already have my-app project created with CLI and I did not understand why I should clone a Quickstart install instead...
Glad to read that the doc will be updated soon. I can read on the quickstart project's page that as of November 1st 2017 the doc will rely on CLI. I guess I did not choose the best timing to start learning Angular :) 
But it's a sign that things are moving on so a good sign !

**Comment by Foxandxss** [comment] 2017-11-03 00:04
The update should be in the next few hours, the doc is written already. Wait a bit my friend.

**Comment by Nicolas-Bouteille** [comment] 2017-11-03 00:17
Awesome! It's actually bed time in France so I guess I'm like a kid at Christmas that can't wait to open its presents first thing in the morning ^^
Thanks for the feedback, I can already feel the great support from the Angular community! Can't wait to discover the power behind the tool.

**Comment by Nicolas-Bouteille** [comment] 2017-11-03 10:09
And now I feel like a kid that just learnt that Santa does not exists ^^ :p

**Comment by Foxandxss** [comment] 2017-11-03 10:13
But then your parents surprise you with a gift in the last minute.

https://pr19811-6121ce0.ngbuilds.io/tutorial

You can read it there, it is the final version that will be in hopefully soon.

**Comment by Nicolas-Bouteille** [comment] 2017-11-03 10:16
Greeeeaaaat! :D 
I was actually starting to have a look at the commit here
https://github.com/angular/angular/commit/6121ce0328214db874079bec7dfc082a71d611b9
but I definitely prefer the link you gave me!!
Really cool my friend! Thanks again :)

**Comment by gkalpak** [comment] 2017-11-03 10:17
> And now I feel like a kid that just learnt that Santa does not exist ^^ :p

Please, refrain from such inaccurate and misleading comments 😛

**Comment by Nicolas-Bouteille** [comment] 2017-11-03 10:21
You're right, you never know how old will be some of Angular's youngest learners in the next few years. Maybe I just broke someone's dream four years from now ^^ :O

**Comment by Nicolas-Bouteille** [comment] 2017-11-03 14:07
Looks like something is missing from the Hero Tour doc:
When adding the hero property, we get the error: Can't bind to 'ngModel' since it isn't a known property of 'input'
Looks like we need to add the import of FormsModule in app.module.ts first
See https://stackoverflow.com/questions/38892771/cant-bind-to-ngmodel-since-it-isnt-a-known-property-of-input

By the way, TSLint also tells me that 
`import {FormsModule} from "@angular/forms";`
should be
`import {FormsModule} from '@angular/forms';`
But I guess this needs to be changed in the CLI component generator... so might need a separate issue?

**Comment by Foxandxss** [comment] 2017-11-03 14:10
What is the difference between those two?

And are you saying that the updated docs is not specifying that you need to add FormsModule?

**Comment by Nicolas-Bouteille** [comment] 2017-11-03 14:13
![capture d ecran 2017-11-03 a 15 12 42](https://user-images.githubusercontent.com/4194095/32377923-84f6f676-c0a9-11e7-98d4-884863e1c996.jpg)

**Comment by Nicolas-Bouteille** [comment] 2017-11-03 14:14
Yes the updated doc does not specify that we need to add FormsModule in app.module.ts

**Comment by Foxandxss** [comment] 2017-11-03 14:16
Ok, I will take a look. If there is any more error other than that, report them at https://github.com/angular/angular/pull/19811 which is the PR with the changes

**Comment by Nicolas-Bouteille** [comment] 2017-11-03 16:19
Ok will do!

**Comment by Nicolas-Bouteille** [comment] 2017-11-03 17:24
About the FormsModule, the problem is not that the documentation does not specify that we need to import it. It does say it, later. The problem is that the piece of code of the section "Show the hero" is not what it should be at that step.

**Comment by jenniferfell** [comment] 2018-05-25 00:37
It looks like this has been addressed: 
https://angular.io/tutorial/toh-pt1#the-missing-formsmodule

We recently worked through the tutorial for v6, and everything seemed to work correctly at that time. 

If we overlooked something and this is still a problem, please open a new issue. Thanks!

**Closed by jenniferfell** 2018-05-25 00:37 UTC
Labels: comp: docs, effort3: weeks, freq2: medium, severity1: confusing
