### ISSUE TITLE
HttpErrorResponse isn't instance of Error

### ISSUE THREAD

**Issue by nin-jin** [angular/angular#22762] opened 2018-03-14 12:02 UTC
## I'm submitting a...
<pre><code>
[x] Bug report
</code></pre>

## Current behavior

HttpErrorResponse isn't Error and I have exceptions in my code on http errors.

## Expected behavior

HttpErrorResponse should be instanceof Error.

## Workaround

```
Object.setPrototypeOf( HttpError.response.prototype , Error.prototype )
```

## Minimal reproduction of the problem with instructions

```
console.assert( new HttpErrorResponse({}) instanceof Error )
```

## What is the motivation / use case for changing the behavior?

Because RxJS destroys streams on errors, I tried to send errors as values, and check if received value is `Error` by this code:

```
if( value instanceof Error ) {
    // ...
} else {
    // ... 
}
```

## Environment

<pre><code>
Angular version: 5.2.7
</code></pre>

**Comment by sandangel** [comment] 2018-03-14 12:20
I think you should use instanceof HttpErrorResponse

**Comment by kemsky** [comment] 2018-03-14 12:48
Error handling in angular http module is far from being perfect even in its second version. Was it timeout, 500 status, error or exception thrown somewhere in your observable chain? How to pick recover strategy for all this errors? Is there description of all possible types of arguments for error handler (`Observable<any>`)?  Go figure...

**Comment by jotatoledo** [comment] 2018-03-14 15:47
The `HttpErrorResponse` class doesn't inherit from the `Error` class.
https://github.com/angular/angular/blob/master/packages/common/http/src/response.ts#L302

So for now this is part of the expected behavior.

@kemsky why is that clumsy? care to explain?

**Comment by nin-jin** [comment] 2018-03-14 15:57
@sandangel I don't like to check for two classes everywere in my code.

@kemsky indifferent on reason of error, I should show error message in UI on opposite side of dataflow.

@jotatoledo i isn't a bug, it is a feature? :-D

**Comment by kemsky** [comment] 2018-03-14 17:07
@nin-jin, https://angular.io/guide/http#getting-error-details there is example of handler function, you can create global function or wrap this code into a class.

@jotatoledo, official doc states:

> Or something could go wrong on the client-side such as a network error that prevents the request from completing successfully or an exception thrown in an RxJS operator. These errors produce JavaScript ErrorEvent objects.

Network error and rxjs error or probably your own error in the same event?? How could somebody get exact exception cause and take appropriate action? Exception thrown in an RxJS operator? Which are errors that can be thrown from rxjs operators and why http client throws them? How can someone be sure that particular ErrorEvent is not a bug in his own program or decide to submit crash report otherwise?

Another example, 401 status code (actually not an error in some cases) will result in error response and in this case you will have to use rxjs operators to recover and send meaningful event down the rxjs stream. So you have to handle response twice in two different places in a completely different way (and be sure to handle it correctly).

Lets say, you want to display offline spinner (timeout, server goes down, internet connection lost) and start pinging server or something similar, how do you detect this case using current API?

<details>
  <summary>A long time ago in a galaxy far, far away....</summary>
There should be 'raw' http client, simple observable, that emits all XHR events (progress, loading, loaded, aborted, timeout etc) without throwing any errors (except fatal errors like null pointer). There should be configurable abstraction of higher level, that allows to use this client with interceptors (not to mention that currently interceptors are global, no way set custom order or custom set for each client), transformers, configurable, with options to set valid status codes, desired events etc. And probably even one more layer to build rest clients.
</details>

**Comment by petebacondarwin** [comment] 2021-07-01 15:33
Closing as this has insufficient community support.

**Closed by petebacondarwin** 2021-07-01 15:33 UTC
Labels: comp: common/http, feature, insufficient votes, votes required
