### ISSUE TITLE
CSSClass directive issue

### ISSUE THREAD

**Issue by DawidMyslak** [angular/angular#2888] opened 2015-07-06 09:37 UTC
I've been playing around with latest build (2.0.0-alpha.29) and I noticed small issue with CSSClass directive.

Here is my application (please use latest Chrome/Firefox/Opera, not working in Safari):
http://dawid.myslak.me/demos/ng2

Step to reproduce:
1. Navigate to "Others";
2. Using tab component switch tab from 1 to 3 (or 2);
3. Navigate to "Todo" and again to "Others";
4. Last selected tab keeps "active" CSS class;

You can check console logs as well, all constructors are called so component should be recreated and CSS classes removed.

Source code for my tabs components is available here:
https://github.com/DawidMyslak/angular2-examples/blob/master/src/components/others/tabs.ts

**Comment by pkozlowski-opensource** [comment] 2015-07-06 10:36
@DawidMyslak - without looking into the details too much (will do later on) I really don't like how you hard-code CSS class name in the widget class. IMO you should do `[class.active]="tab.isActive"` (preferred) or `[class]="{active: tab.isActive}"`

**Comment by DawidMyslak** [comment] 2015-07-06 10:53
@pkozlowski-opensource thanks for that, I couldn't find any examples with conditional syntax for CSSClass, so I managed to create that ugly workaround, documentation is still quite empty:
https://angular.io/docs/js/latest/api/directives/CSSClass-class.html

**Comment by DawidMyslak** [comment] 2015-07-06 11:58
@pkozlowski-opensource thanks again Pawel, looks like ```[class.active]="tab.isActive"``` fixed the issue, can be closed.

**Comment by pkozlowski-opensource** [comment] 2015-07-06 11:59
@DawidMyslak I will add a test for this particular use-case to the `CSSClass` and will close. Thnx for getting back to me.

**Comment by pkozlowski-opensource** [comment] 2015-07-08 15:45
@DawidMyslak I can't reproduce the exact issue you were having, but I've submitted the #2934 PR just to make sure that we don't bump into it in the future. 

Going to close this one as I can't reproduce it anymore and you've solved the pb differently anyways.

**Closed by pkozlowski-opensource** 2015-07-08 15:45 UTC
