### ISSUE TITLE
on recompile/reload the base route is duplicated

### ISSUE THREAD

**Issue by webmandman** [angular/angular#42827] opened 2021-07-12 17:34 UTC
### Which @angular/* package(s) are the source of the bug?

compiler-cli, compiler, router

### Is this a regression?

No

## Current Behavior
When I make changes to my angular ts files the browser to reloads my app adding my base route after the existing base route. 
URI: /profile ----> code change/save ----> recompile ----> browser reloads app, and URI is now: /profile/profile

## Expected Behavior
When I make changes to my angular ts files I expect the browser to reload once its done recompiling without the URI to change. 

## Steps to Reproduce
I can't reproduce the issue in a new NX workspace angular app, nor in a standalone angular app. Believe me I tried. I want to provide a reproduceable issue with a repo you can try but I can't for the life of me figure it out. I have compared and reviewed all my code to see what would cause such a thing and I don't see anything. 

My routes configuration in my base app.module.ts is:
`const routes: Routes = [
  { path: 'profile',
    loadChildren: () =>
      import(`./profile/profile.module`).then(m => m.ProfileModule)
  },
  { path: '**', redirectTo: 'profile', pathMatch: 'full' }
];
`

My profile (lazy loaded)module routes is:
`const profileRoutes: Routes = [
  { path: '', component: ProfileComponent },
  { path: 'address', component: AddressComponent },
  { path: 'phone', component: PhoneComponent },
  { path: 'photo', component: PhotoComponent },
  { path: 'password', component: PasswordComponent }
];
`

### Please provide the environment you discovered this bug in

```true
Angular CLI: 11.2.0
Node: 14.15.0
OS: win32 x64

Angular: 11.2.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: <error>

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.9
@angular-devkit/build-angular   0.1102.9
@angular-devkit/core            11.2.14
@angular-devkit/schematics      11.2.14
@angular/cdk                    11.2.13
@angular/flex-layout            11.0.0-beta.33
@angular/localize               11.2.14
@angular/material               11.2.13
@schematics/angular             11.2.14
@schematics/update              0.1102.0
ng-packagr                      11.2.0
rxjs                            6.6.7
typescript                      4.1.4
```

**Comment by JoostK** [comment] 2021-07-12 18:08
> I can't reproduce the issue in a new NX workspace angular app, nor in a standalone angular app. Believe me I tried. I want to provide a reproduceable issue with a repo you can try but I can't for the life of me figure it out. I have compared and reviewed all my code to see what would cause such a thing and I don't see anything.

Yeah, those are the nicest of bugs!

Do you get similar behavior when just refreshing the browser, without a recompile trigger?

**Comment by JoostK** [comment] 2021-07-12 18:10
What might be helpful is to share the network activity and enable the router's tracing mode, together with log preservation turned on.

**Comment by webmandman** [comment] 2021-07-12 18:19
Oooh nice. I didn't even know about router's tracing mode. I'll get back to you on that...

Yes refreshing the browser without recompiling affectively does the same - it loads the base route and view is rendered successfully but URI base route is duplicated. A follow up browser refresh (with/out recompile) does not triple the base route URI but app does not load because assets like runtime.js are now being requested from "localhost:4200/profile/runtime.js" instead of "localhost:4200/runtime.js"

**Comment by webmandman** [comment] 2021-07-12 18:46
@JoostK here is the HAR network log. I did two http reqquests: 1. http://localhost:4200 ---> which reroutes to http://localhost:4200/profile.  2. I hit browser refresh and http://localhost:4200/profile ---> rerouted to http://localhost:4200/profile/profile. 

https://drive.google.com/file/d/1rdbO7SHAqBZp9Sdc_8ZoaxI752AcOiY9/view?usp=sharing

**Comment by webmandman** [comment] 2021-07-12 18:47
I've never shared console logs is there a meaningful way of exporting it? or does the HAR log also have console logs?

**Comment by JoostK** [comment] 2021-07-12 18:54
Not that I know of; copy-pasting is hopefully readable enough.

Looking at the HAR (which you may want to remove from Drive) I don't see a network request for the `/profile` -> `/profile/profile` redirect, indicating that it happens entirely client side.

**Comment by webmandman** [comment] 2021-07-12 19:00
console log:
platform-browser.js:71 Router Event: NavigationStart
instrument.js:109 NavigationStart(id: 1, url: '/')
instrument.js:109 NavigationStart {id: 1, url: "/", navigationTrigger: "imperative", restoredState: null}
instrument.js:109 Angular is running in development mode. Call enableProdMode() to enable production mode.
platform-browser.js:71 Router Event: RouteConfigLoadStart
instrument.js:109 RouteConfigLoadStart(path: profile)
instrument.js:109 RouteConfigLoadStart {route: {…}}
client:52 [WDS] Live Reloading enabled.
platform-browser.js:71 Router Event: RouteConfigLoadEnd
instrument.js:109 RouteConfigLoadEnd(path: profile)
instrument.js:109 RouteConfigLoadEnd {route: {…}}
platform-browser.js:71 Router Event: RoutesRecognized
instrument.js:109 RoutesRecognized(id: 1, url: '/', urlAfterRedirects: '/profile', state: Route(url:'', path:'') { Route(url:'profile', path:'profile') { Route(url:'', path:'') }  } )
instrument.js:109 RoutesRecognized {id: 1, url: "/", urlAfterRedirects: "/profile", state: RouterStateSnapshot}
platform-browser.js:71 Router Event: GuardsCheckStart
instrument.js:109 GuardsCheckStart(id: 1, url: '/', urlAfterRedirects: '/profile', state: Route(url:'', path:'') { Route(url:'profile', path:'profile') { Route(url:'', path:'') }  } )
instrument.js:109 GuardsCheckStart {id: 1, url: "/", urlAfterRedirects: "/profile", state: RouterStateSnapshot}
platform-browser.js:71 Router Event: ChildActivationStart
instrument.js:109 ChildActivationStart(path: '')
instrument.js:109 ChildActivationStart {snapshot: ActivatedRouteSnapshot}
platform-browser.js:71 Router Event: ActivationStart
instrument.js:109 ActivationStart(path: 'profile')
instrument.js:109 ActivationStart {snapshot: ActivatedRouteSnapshot}
platform-browser.js:71 Router Event: ChildActivationStart
instrument.js:109 ChildActivationStart(path: 'profile')
instrument.js:109 ChildActivationStart {snapshot: ActivatedRouteSnapshot}
platform-browser.js:71 Router Event: ActivationStart
instrument.js:109 ActivationStart(path: '')
instrument.js:109 ActivationStart {snapshot: ActivatedRouteSnapshot}
platform-browser.js:71 Router Event: GuardsCheckEnd
instrument.js:109 GuardsCheckEnd(id: 1, url: '/', urlAfterRedirects: '/profile', state: Route(url:'', path:'') { Route(url:'profile', path:'profile') { Route(url:'', path:'') }  } , shouldActivate: true)
instrument.js:109 GuardsCheckEnd {id: 1, url: "/", urlAfterRedirects: "/profile", state: RouterStateSnapshot, shouldActivate: true}
platform-browser.js:71 Router Event: ResolveStart
instrument.js:109 ResolveStart(id: 1, url: '/', urlAfterRedirects: '/profile', state: Route(url:'', path:'') { Route(url:'profile', path:'profile') { Route(url:'', path:'') }  } )
instrument.js:109 ResolveStart {id: 1, url: "/", urlAfterRedirects: "/profile", state: RouterStateSnapshot}
platform-browser.js:71 Router Event: ResolveEnd
instrument.js:109 ResolveEnd(id: 1, url: '/', urlAfterRedirects: '/profile', state: Route(url:'', path:'') { Route(url:'profile', path:'profile') { Route(url:'', path:'') }  } )
instrument.js:109 ResolveEnd {id: 1, url: "/", urlAfterRedirects: "/profile", state: RouterStateSnapshot}
platform-browser.js:71 Router Event: ActivationEnd
instrument.js:109 ActivationEnd(path: '')
instrument.js:109 ActivationEnd {snapshot: ActivatedRouteSnapshot}
platform-browser.js:71 Router Event: ChildActivationEnd
instrument.js:109 ChildActivationEnd(path: 'profile')
instrument.js:109 ChildActivationEnd {snapshot: ActivatedRouteSnapshot}
platform-browser.js:71 Router Event: ActivationEnd
instrument.js:109 ActivationEnd(path: 'profile')
instrument.js:109 ActivationEnd {snapshot: ActivatedRouteSnapshot}
platform-browser.js:71 Router Event: ChildActivationEnd
instrument.js:109 ChildActivationEnd(path: '')
instrument.js:109 ChildActivationEnd {snapshot: ActivatedRouteSnapshot}
platform-browser.js:71 Router Event: NavigationEnd
instrument.js:109 NavigationEnd(id: 1, url: '/', urlAfterRedirects: '/profile')
instrument.js:109 NavigationEnd {id: 1, url: "/", urlAfterRedirects: "/profile"}
platform-browser.js:71 Router Event: Scroll
instrument.js:109 Scroll(anchor: 'null', position: 'null')
instrument.js:109 Scroll {routerEvent: NavigationEnd, position: null, anchor: null}
instrument.js:109 false

**Comment by JoostK** [comment] 2021-07-12 19:08
Hmm, that does not reveal anything useful I'm afraid. I'm a bit out of ideas but you may want to try adding `pathMatch: 'full'` to the empty route in the lazy module.

**Comment by webmandman** [comment] 2021-07-12 22:04
I added that and re-served the app but still having the same issue.

**Comment by webmandman** [comment] 2021-07-12 22:07
I created a new workspace which is in version 12 with the initial angular 12 app that it creates for me, copied my app src to this new workspace, added my libs and required npm packages and it works just fine.

**Comment by atscott** [comment] 2021-07-22 19:24
While I don't doubt this could have been due to an issue in the router I'm going to close this now since there's nothing really actionable for us without being able to reproduce the issue. If you do experience this again and are able to reproduce it, please do file a new issue so we can investigate it. Thank you!

**Closed by atscott** 2021-07-22 19:24 UTC
Labels: comp: router, needs clarification
