### ISSUE TITLE
Constants for AbstractControl.status not part of public API

### ISSUE THREAD

**Issue by akloeber** [angular/angular#28047] opened 2019-01-10 16:49 UTC
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/forms

### Description
 A clear and concise description of the problem or missing capability...
The status of an `AbstractControl` appears in different places of the API:
- `AbstractControl.value`
- `AbstractControl.statusChanges`

Right now the status is not typed at all (type is `any`) and beyond that the constants that are defined in `forms/src/model.ts` (`VALID, INVALID, PENDING, DISABLED`) are not exported in the public API. This makes it impossible to check/observe the status in a type-safe / compile-time-checked manor.

### Describe the solution you'd like
 If you have a solution in mind, please describe it.
Status should be typed and made available in the public API, e.g.:
```ts
export declare type FormControlStatus = 'VALID' | 'INVALID' | 'PENDING' | 'DISABLED';
```

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?
Alternatively at least the constants defined in `forms/src/model.ts` should be made accessible.

**Comment by kara** [comment] 2019-01-10 23:25
Thanks for filing, @akloeber, but as @ChrisDahmCS, this looks like a duplicate of #27389. Let's continue to track on the existing issue.

**Closed by kara** 2019-01-10 23:25 UTC
Labels: comp: forms

**Comment by akloeber** [comment] 2019-01-11 07:50
@kara You are right, the second alternative I provided exactly duplicates #27389. Still, the suggestion of introducing a dedicated type is not mentioned there. I will add a comment there to present this idea.
