### ISSUE TITLE
routerLinkActive isActive value is not correct in LazyLoad Module

### ISSUE THREAD

**Issue by DanielYKPan** [angular/angular#25535] opened 2018-08-17 08:16 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ X ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

When the ladzyloade module loaded into view, the routerLinkActive.isActive value is not correct.
Here is the [Demo](https://stackblitz.com/edit/angular-sftlrs).

As you can see on the demo, when the page loaded first time.
Link 'Message' on root component has  routeLinkActive.isActive = true.
Link 'Message' on test component(lazy-load module) has routeLinkActive.isActive = false. It should be the same as it on the root component.

But if you click on any link, the routeLinkActive.isActive values are correct on both components.
## Environment

<pre><code>
Angular version: 6.1.2

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by geromegrignon** [comment] 2018-08-22 14:06
#19934

**Comment by atscott** [comment] 2020-05-27 17:14
This appears to be a duplicate of #19934.

**Closed by atscott** 2020-05-27 17:14 UTC
Labels: comp: router, freq2: medium, severity3: broken, triage #1, type: bug/fix
