### ISSUE TITLE
Form required validation ExpressionChangedAfterItHasBeenCheckedError

### ISSUE THREAD

**Issue by camilogiraldo** [angular/angular#34456] opened 2019-12-17 21:13 UTC
# 🐞 bug report

### Affected Package

The issue is caused by package @angular/forms. maybe?

### Is this a regression?

 Yes, the previous version in which this bug was not present was:  8.2.14

### Description

 A clear and concise description of the problem...

Our app is a dynamically generated form, with custom inputs using the `ControlValueAccessor` interface in order to bind those custom input changes to the main form.

![image](https://user-images.githubusercontent.com/3651787/71014994-d9e9a880-20c0-11ea-9803-33a4d4c76a0e.png)

After some testing I found something interesting, if I remove the following snippet `[required]="kapInput.required"` the error is gone. I also tried harcoding the required property to _true_ or _false_ but the error was still present. 

![image](https://user-images.githubusercontent.com/3651787/71015147-21703480-20c1-11ea-8833-7b809e268624.png)

So I'm not sure if this is related to the forms package (due to the validations), a _False-positive_ error check due that the validation is working, or anything related to IVY.

## 🔬 Minimal Reproduction

I managed to create repo, reproducing the error. Here's the link
_9-update_ branch
https://github.com/camilogiraldo/dynamic-forms/tree/9-update

## 🔥 Exception or Error
<pre><code>

 core.js:4046 ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'false'. Current value: 'true'.
    at throwErrorIfNoChangesMode (core.js:5549)
    at stylingProp (core.js:15410)
    at Module.ɵɵclassProp (core.js:15379)
    at KapInputComponent_Template (kap-input.component.html:6)
    at executeTemplate (core.js:8857)
    at refreshView (core.js:8746)
    at refreshComponent (core.js:9803)
    at refreshChildComponents (core.js:8550)
    at refreshView (core.js:8793)
    at refreshDynamicEmbeddedViews (core.js:9740)

  | defaultErrorLogger | @ | core.js:4046
-- | -- | -- | --
  | push../node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js.ErrorHandler.handleError | @ | core.js:4094
  | push../src/app/core/services/monitoring/monitoring-error.service.ts.MonitoringErrorService.handleError | @ | monitoring-error.service.ts:15
  | (anonymous) | @ | core.js:28258
  | ZoneDelegate.invoke | @ | zone.js:396
  | Zone.run | @ | zone.js:153
  | push../node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js.NgZone.runOutsideAngular | @ | core.js:27280
  | push../node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js.ApplicationRef.tick | @ | core.js:28258
  | (anonymous) | @ | core.js:28121
  | ZoneDelegate.invoke | @ | zone.js:396
  | onInvoke | @ | core.js:27338
  | ZoneDelegate.invoke | @ | zone.js:395
  | Zone.run | @ | zone.js:153
  | push../node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js.NgZone.run | @ | core.js:27235
  | next | @ | core.js:28121
  | schedulerFn | @ | core.js:24876
  | push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.__tryOrUnsub | @ | Subscriber.js:192
  | push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.next | @ | Subscriber.js:130
  | push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber._next | @ | Subscriber.js:76
  | push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next | @ | Subscriber.js:53
  | push../node_modules/rxjs/_esm5/internal/Subject.js.Subject.next | @ | Subject.js:47
  | push../node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js.EventEmitter.emit | @ | core.js:24860
  | checkStable | @ | core.js:27290
  | onHasTask | @ | core.js:27352
  | ZoneDelegate.hasTask | @ | zone.js:451
  | ZoneDelegate._updateTaskCount | @ | zone.js:472
  | Zone._updateTaskCount | @ | zone.js:294
  | Zone.runTask | @ | zone.js:215
  | drainMicroTaskQueue | @ | zone.js:611
  | ZoneTask.invokeTask | @ | zone.js:517
  | invokeTask | @ | zone.js:1671
  | globalZoneAwareCallback | @ | zone.js:1708
  | load (async) |   |  
  | customScheduleGlobal | @ | zone.js:1810
  | ZoneDelegate.scheduleTask | @ | zone.js:417
  | onScheduleTask | @ | zone.js:304
  | ZoneDelegate.scheduleTask | @ | zone.js:410
  | Zone.scheduleTask | @ | zone.js:241
  | Zone.scheduleEventTask | @ | zone.js:267
  | (anonymous) | @ | zone.js:1984
  | (anonymous) | @ | http.js:1798
  | push../node_modules/rxjs/_esm5/internal/Observable.js.Observable._trySubscribe | @ | Observable.js:43
  | push../node_modules/rxjs/_esm5/internal/Observable.js.Observable.subscribe | @ | Observable.js:29
  | subscribeToResult | @ | subscribeToResult.js:13
  | push../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapSubscriber._innerSub | @ | mergeMap.js:74
  | push../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapSubscriber._tryNext | @ | mergeMap.js:68
  | push../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapSubscriber._next | @ | mergeMap.js:51
  | push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next | @ | Subscriber.js:53
  | push../node_modules/rxjs/_esm5/internal/operators/map.js.MapSubscriber._next | @ | map.js:41
  | push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next | @ | Subscriber.js:53
  | push../node_modules/rxjs/_esm5/internal/AsyncSubject.js.AsyncSubject._subscribe | @ | AsyncSubject.js:20
  | push../node_modules/rxjs/_esm5/internal/Observable.js.Observable._trySubscribe | @ | Observable.js:43
  | push../node_modules/rxjs/_esm5/internal/Subject.js.Subject._trySubscribe | @ | Subject.js:89
  | push../node_modules/rxjs/_esm5/internal/Observable.js.Observable.subscribe | @ | Observable.js:29
  | (anonymous) | @ | bindCallback.js:60
  | push../node_modules/rxjs/_esm5/internal/Observable.js.Observable._trySubscribe | @ | Observable.js:43
  | push../node_modules/rxjs/_esm5/internal/Observable.js.Observable.subscribe | @ | Observable.js:29
  | push../node_modules/rxjs/_esm5/internal/operators/map.js.MapOperator.call | @ | map.js:18
  | push../node_modules/rxjs/_esm5/internal/Observable.js.Observable.subscribe | @ | Observable.js:24
  | push../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapOperator.call | @ | mergeMap.js:29
  | push../node_modules/rxjs/_esm5/internal/Observable.js.Observable.subscribe | @ | Observable.js:24
  | subscribeToResult | @ | subscribeToResult.js:13
  | push../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapSubscriber._innerSub | @ | mergeMap.js:74
  | push../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapSubscriber._tryNext | @ | mergeMap.js:68
  | push../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapSubscriber._next | @ | mergeMap.js:51
  | push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next | @ | Subscriber.js:53
  | (anonymous) | @ | subscribeToArray.js:5
  | push../node_modules/rxjs/_esm5/internal/Observable.js.Observable._trySubscribe | @ | Observable.js:43
  | push../node_modules/rxjs/_esm5/internal/Observable.js.Observable.subscribe | @ | Observable.js:29
  | push../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapOperator.call | @ | mergeMap.js:29
  | push../node_modules/rxjs/_esm5/internal/Observable.js.Observable.subscribe | @ | Observable.js:24
  | push../node_modules/rxjs/_esm5/internal/operators/filter.js.FilterOperator.call | @ | filter.js:15
  | push../node_modules/rxjs/_esm5/internal/Observable.js.Observable.subscribe | @ | Observable.js:24
  | push../node_modules/rxjs/_esm5/internal/operators/map.js.MapOperator.call | @ | map.js:18
  | push../node_modules/rxjs/_esm5/internal/Observable.js.Observable.subscribe | @ | Observable.js:24
  | push../node_modules/rxjs/_esm5/internal/operators/take.js.TakeOperator.call | @ | take.js:24
  | push../node_modules/rxjs/_esm5/internal/Observable.js.Observable.subscribe | @ | Observable.js:24
  | push../node_modules/rxjs/_esm5/internal/operators/map.js.MapOperator.call | @ | map.js:18
  | push../node_modules/rxjs/_esm5/internal/Observable.js.Observable.subscribe | @ | Observable.js:24
  | push../node_modules/rxjs/_esm5/internal/operators/catchError.js.CatchOperator.call | @ | catchError.js:18
  | push../node_modules/rxjs/_esm5/internal/Observable.js.Observable.subscribe | @ | Observable.js:24
  | push../node_modules/rxjs/_esm5/internal/operators/map.js.MapOperator.call | @ | map.js:18
  | push../node_modules/rxjs/_esm5/internal/Observable.js.Observable.subscribe | @ | Observable.js:24
  | push../node_modules/rxjs/_esm5/internal/operators/map.js.MapOperator.call | @ | map.js:18
  | push../node_modules/rxjs/_esm5/internal/Observable.js.Observable.subscribe | @ | Observable.js:24
  | subscribeToResult | @ | subscribeToResult.js:13
  | push../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapSubscriber._innerSub | @ | mergeMap.js:74
  | push../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapSubscriber._tryNext | @ | mergeMap.js:68
  | push../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapSubscriber._next | @ | mergeMap.js:51
  | push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next | @ | Subscriber.js:53
  | (anonymous) | @ | subscribeToArray.js:5
  | push../node_modules/rxjs/_esm5/internal/Observable.js.Observable._trySubscribe | @ | Observable.js:43
  | push../node_modules/rxjs/_esm5/internal/Observable.js.Observable.subscribe | @ | Observable.js:29
  | push../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapOperator.call | @ | mergeMap.js:29
  | push../node_modules/rxjs/_esm5/internal/Observable.js.Observable.subscribe | @ | Observable.js:24
  | push../node_modules/rxjs/_esm5/internal/operators/scan.js.ScanOperator.call | @ | scan.js:23
  | push../node_modules/rxjs/_esm5/internal/Observable.js.Observable.subscribe | @ | Observable.js:24
  | push../node_modules/rxjs/_esm5/internal/operators/takeLast.js.TakeLastOperator.call | @ | takeLast.js:24
  | push../node_modules/rxjs/_esm5/internal/Observable.js.Observable.subscribe | @ | Observable.js:24
  | push../node_modules/rxjs/_esm5/internal/operators/map.js.MapOperator.call | @ | map.js:18
  | push../node_modules/rxjs/_esm5/internal/Observable.js.Observable.subscribe | @ | Observable.js:24
  | subscribeToResult | @ | subscribeToResult.js:13
  | push../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapSubscriber._innerSub | @ | mergeMap.js:74
  | push../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapSubscriber._tryNext | @ | mergeMap.js:68
  | push../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapSubscriber._next | @ | mergeMap.js:51
  | push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next | @ | Subscriber.js:53
  | push../node_modules/rxjs/_esm5/internal/operators/tap.js.TapSubscriber._next | @ | tap.js:51
  | push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next | @ | Subscriber.js:53
  | (anonymous) | @ | subscribeToArray.js:5
  | push../node_modules/rxjs/_esm5/internal/Observable.js.Observable._trySubscribe | @ | Observable.js:43
  | push../node_modules/rxjs/_esm5/internal/Observable.js.Observable.subscribe | @ | Observable.js:29
  | push../node_modules/rxjs/_esm5/internal/operators/tap.js.DoOperator.call | @ | tap.js:18
  | push../node_modules/rxjs/_esm5/internal/Observable.js.Observable.subscribe | @ | Observable.js:24
  | push../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapOperator.call | @ | mergeMap.js:29
  | push../node_modules/rxjs/_esm5/internal/Observable.js.Observable.subscribe | @ | Observable.js:24
  | push../node_modules/rxjs/_esm5/internal/operators/tap.js.DoOperator.call | @ | tap.js:18
  | push../node_modules/rxjs/_esm5/internal/Observable.js.Observable.subscribe | @ | Observable.js:24
  | push../node_modules/rxjs/_esm5/internal/operators/map.js.MapOperator.call | @ | map.js:18
  | push../node_modules/rxjs/_esm5/internal/Observable.js.Observable.subscribe | @ | Observable.js:24
  | subscribeToResult | @ | subscribeToResult.js:13
  | push../node_modules/rxjs/_esm5/internal/operators/switchMap.js.SwitchMapSubscriber._innerSub | @ | switchMap.js:51
  | push../node_modules/rxjs/_esm5/internal/operators/switchMap.js.SwitchMapSubscriber._next | @ | switchMap.js:41
  | push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next | @ | Subscriber.js:53
  | push../node_modules/rxjs/_esm5/internal/operators/filter.js.FilterSubscriber._next | @ | filter.js:38
  | push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next | @ | Subscriber.js:53
  | push../node_modules/rxjs/_esm5/internal/operators/tap.js.TapSubscriber._next | @ | tap.js:51
  | push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next | @ | Subscriber.js:53
  | push../node_modules/rxjs/_esm5/internal/operators/tap.js.TapSubscriber._next | @ | tap.js:51
  | push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next | @ | Subscriber.js:53
  | push../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapSubscriber.notifyNext | @ | mergeMap.js:84
  | push../node_modules/rxjs/_esm5/internal/InnerSubscriber.js.InnerSubscriber._next | @ | InnerSubscriber.js:15
  | push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next | @ | Subscriber.js:53
  | push../node_modules/rxjs/_esm5/internal/operators/map.js.MapSubscriber._next | @ | map.js:41
  | push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next | @ | Subscriber.js:53
  | push../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapSubscriber.notifyNext | @ | mergeMap.js:84
  | push../node_modules/rxjs/_esm5/internal/InnerSubscriber.js.InnerSubscriber._next | @ | InnerSubscriber.js:15
  | push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next | @ | Subscriber.js:53
  | push../node_modules/rxjs/_esm5/internal/operators/defaultIfEmpty.js.DefaultIfEmptySubscriber._complete | @ | defaultIfEmpty.js:33
  | push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.complete | @ | Subscriber.js:65
  | push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber._complete | @ | Subscriber.js:83
  | push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.complete | @ | Subscriber.js:65
  | push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber._complete | @ | Subscriber.js:83
  | push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.complete | @ | Subscriber.js:65
  | push../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapSubscriber._complete | @ | mergeMap.js:79
  | push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.complete | @ | Subscriber.js:65
  | (anonymous) | @ | subscribeToArray.js:7
  | push../node_modules/rxjs/_esm5/internal/Observable.js.Observable._trySubscribe | @ | Observable.js:43
  | push../node_modules/rxjs/_esm5/internal/Observable.js.Observable.subscribe | @ | Observable.js:29
  | push../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapOperator.call | @ | mergeMap.js:29
  | push../node_modules/rxjs/_esm5/internal/Observable.js.Observable.subscribe | @ | Observable.js:24
  | push../node_modules/rxjs/_esm5/internal/operators/filter.js.FilterOperator.call | @ | filter.js:15
  | push../node_modules/rxjs/_esm5/internal/Observable.js.Observable.subscribe | @ | Observable.js:24
  | push../node_modules/rxjs/_esm5/internal/operators/take.js.TakeOperator.call | @ | take.js:24
  | push../node_modules/rxjs/_esm5/internal/Observable.js.Observable.subscribe | @ | Observable.js:24
  | push../node_modules/rxjs/_esm5/internal/operators/defaultIfEmpty.js.DefaultIfEmptyOperator.call | @ | defaultIfEmpty.js:15
  | push../node_modules/rxjs/_esm5/internal/Observable.js.Observable.subscribe | @ | Observable.js:24
  | subscribeToResult | @ | subscribeToResult.js:13
  | push../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapSubscriber._innerSub | @ | mergeMap.js:74
  | push../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapSubscriber._tryNext | @ | mergeMap.js:68
  | push../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapSubscriber._next | @ | mergeMap.js:51
  | push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next | @ | Subscriber.js:53
  | push../node_modules/rxjs/_esm5/internal/operators/defaultIfEmpty.js.DefaultIfEmptySubscriber._complete | @ | defaultIfEmpty.js:33
  | push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.complete | @ | Subscriber.js:65
  | push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber._complete | @ | Subscriber.js:83
  | push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.complete | @ | Subscriber.js:65
  | push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber._complete | @ | Subscriber.js:83
  | push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.complete | @ | Subscriber.js:65
  | push../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapSubscriber._complete | @ | mergeMap.js:79
  | push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.complete | @ | Subscriber.js:65
  | (anonymous) | @ | subscribeToArray.js:7
  | push../node_modules/rxjs/_esm5/internal/Observable.js.Observable._trySubscribe | @ | Observable.js:43
  | push../node_modules/rxjs/_esm5/internal/Observable.js.Observable.subscribe | @ | Observable.js:29
  | push../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapOperator.call | @ | mergeMap.js:29
  | push../node_modules/rxjs/_esm5/internal/Observable.js.Observable.subscribe | @ | Observable.js:24
  | push../node_modules/rxjs/_esm5/internal/operators/filter.js.FilterOperator.call | @ | filter.js:15
  | push../node_modules/rxjs/_esm5/internal/Observable.js.Observable.subscribe | @ | Observable.js:24
  | push../node_modules/rxjs/_esm5/internal/operators/take.js.TakeOperator.call | @ | take.js:24
  | push../node_modules/rxjs/_esm5/internal/Observable.js.Observable.subscribe | @ | Observable.js:24
  | push../node_modules/rxjs/_esm5/internal/operators/defaultIfEmpty.js.DefaultIfEmptyOperator.call | @ | defaultIfEmpty.js:15
  | push../node_modules/rxjs/_esm5/internal/Observable.js.Observable.subscribe | @ | Observable.js:24
  | push../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapOperator.call | @ | mergeMap.js:29
  | push../node_modules/rxjs/_esm5/internal/Observable.js.Observable.subscribe | @ | Observable.js:24
  | push../node_modules/rxjs/_esm5/internal/operators/map.js.MapOperator.call | @ | map.js:18
  | push../node_modules/rxjs/_esm5/internal/Observable.js.Observable.subscribe | @ | Observable.js:24
  | subscribeToResult | @ | subscribeToResult.js:13
  | push../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapSubscriber._innerSub | @ | mergeMap.js:74
  | push../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapSubscriber._tryNext | @ | mergeMap.js:68
  | push../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapSubscriber._next | @ | mergeMap.js:51
  | push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next | @ | Subscriber.js:53
  | push../node_modules/rxjs/_esm5/internal/operators/map.js.MapSubscriber._next | @ | map.js:41
  | push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next | @ | Subscriber.js:53
  | push../node_modules/rxjs/_esm5/internal/operators/tap.js.TapSubscriber._next | @ | tap.js:51
  | push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next | @ | Subscriber.js:53
  | push../node_modules/rxjs/_esm5/internal/operators/switchMap.js.SwitchMapSubscriber.notifyNext | @ | switchMap.js:72
  | push../node_modules/rxjs/_esm5/internal/InnerSubscriber.js.InnerSubscriber._next | @ | InnerSubscriber.js:15
  | push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next | @ | Subscriber.js:53
  | push../node_modules/rxjs/_esm5/internal/operators/map.js.MapSubscriber._next | @ | map.js:41
  | push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next | @ | Subscriber.js:53
  | (anonymous) | @ | subscribeToArray.js:5
  | push../node_modules/rxjs/_esm5/internal/Observable.js.Observable._trySubscribe | @ | Observable.js:43
  | push../node_modules/rxjs/_esm5/internal/Observable.js.Observable.subscribe | @ | Observable.js:29
  | push../node_modules/rxjs/_esm5/internal/operators/map.js.MapOperator.call | @ | map.js:18
  | push../node_modules/rxjs/_esm5/internal/Observable.js.Observable.subscribe | @ | Observable.js:24
  | subscribeToResult | @ | subscribeToResult.js:13
  | push../node_modules/rxjs/_esm5/internal/operators/switchMap.js.SwitchMapSubscriber._innerSub | @ | switchMap.js:51
  | push../node_modules/rxjs/_esm5/internal/operators/switchMap.js.SwitchMapSubscriber._next | @ | switchMap.js:41
  | push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next | @ | Subscriber.js:53
  | push../node_modules/rxjs/_esm5/internal/operators/switchMap.js.SwitchMapSubscriber.notifyNext | @ | switchMap.js:72
  | push../node_modules/rxjs/_esm5/internal/InnerSubscriber.js.InnerSubscriber._next | @ | InnerSubscriber.js:15
  | push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next | @ | Subscriber.js:53
  | push../node_modules/rxjs/_esm5/internal/operators/tap.js.TapSubscriber._next | @ | tap.js:51
  | push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next | @ | Subscriber.js:53
  | push../node_modules/rxjs/_esm5/internal/operators/tap.js.TapSubscriber._next | @ | tap.js:51
  | push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next | @ | Subscriber.js:53
  | push../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapSubscriber.notifyNext | @ | mergeMap.js:84
  | push../node_modules/rxjs/_esm5/internal/InnerSubscriber.js.InnerSubscriber._next | @ | InnerSubscriber.js:15
  | push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next | @ | Subscriber.js:53
  | push../node_modules/rxjs/_esm5/internal/operators/map.js.MapSubscriber._next | @ | map.js:41
  | push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next | @ | Subscriber.js:53
  | (anonymous) | @ | subscribeToArray.js:5
  | push../node_modules/rxjs/_esm5/internal/Observable.js.Observable._trySubscribe | @ | Observable.js:43
  | push../node_modules/rxjs/_esm5/internal/Observable.js.Observable.subscribe | @ | Observable.js:29
  | push../node_modules/rxjs/_esm5/internal/operators/map.js.MapOperator.call | @ | map.js:18
  | push../node_modules/rxjs/_esm5/internal/Observable.js.Observable.subscribe | @ | Observable.js:24
  | subscribeToResult | @ | subscribeToResult.js:13
  | push../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapSubscriber._innerSub | @ | mergeMap.js:74
  | push../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapSubscriber._tryNext | @ | mergeMap.js:68
  | push../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapSubscriber._next | @ | mergeMap.js:51
  | push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next | @ | Subscriber.js:53
  | push../node_modules/rxjs/_esm5/internal/operators/tap.js.TapSubscriber._next | @ | tap.js:51
  | push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next | @ | Subscriber.js:53
  | push../node_modules/rxjs/_esm5/internal/operators/switchMap.js.SwitchMapSubscriber.notifyNext | @ | switchMap.js:72
  | push../node_modules/rxjs/_esm5/internal/InnerSubscriber.js.InnerSubscriber._next | @ | InnerSubscriber.js:15
  | Promise.then (async) |   |  
  | scheduleMicroTask | @ | zone.js:594
  | ZoneDelegate.scheduleTask | @ | zone.js:420
  | onScheduleTask | @ | zone.js:304
  | ZoneDelegate.scheduleTask | @ | zone.js:410
  | Zone.scheduleTask | @ | zone.js:241
  | Zone.scheduleMicroTask | @ | zone.js:261
  | scheduleResolveOrReject | @ | zone.js:884
  | resolvePromise | @ | zone.js:830
  | (anonymous) | @ | zone.js:750
  | webpackJsonpCallback | @ | bootstrap:25
  | (anonymous)

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.0.0-rc.6
Node: 12.3.1
OS: win32 x64

Angular: 9.0.0-rc.6
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-rc.6
@angular-devkit/build-angular     0.900.0-rc.6
@angular-devkit/build-optimizer   0.900.0-rc.6
@angular-devkit/build-webpack     0.900.0-rc.6
@angular-devkit/core              0.5.13
@angular-devkit/schematics        0.5.13
@angular/http                     7.2.15
@angular/localize                 9.0.0-rc.0
@ngtools/webpack                  9.0.0-rc.6
@schematics/angular               9.0.0-rc.6
@schematics/update                0.900.0-rc.6
rxjs                              6.5.3
typescript                        3.6.4
webpack                           4.41.2
</code></pre>

**Anything else relevant?**

**Comment by camilogiraldo** [comment] 2020-02-06 13:55
@AndrewKushnir @kara any update on this or related to this ?

**Comment by AndrewKushnir** [comment] 2020-02-06 22:22
Hi @camilogiraldo, based on the error message that you provided, it looks like it's coming from the `ɵɵclassProp` instruction. Styling subsystem was updated and some parts of it were rewritten, so it'd be great if you could test the same behavior again with `9.0.0` version (that was released a couple hours ago) and let us know if the problem still exists. Thank you.

**Comment by AndrewKushnir** [comment] 2020-05-28 18:55
Hi @camilogiraldo,

I've performed additional investigation and it looks like the problem was caused by the fact that template-driven and reactive forms approaches were mixed. The proposal is to avoid adding `[required]` binding in a template, but instead add the `Validators.required` (and other validators) to a `FormControl` instance inside `DynamicFormComponent` component. I did a quick test and that helps avoid the `ExpressionChangedAfterItHasBeenCheckedError` error. 

I will close this ticket (since there are no action items for framework), feel free to reopen if the problem still exists.

Thank you.

**Closed by AndrewKushnir** 2020-05-28 18:55 UTC
Labels: comp: forms, engine: ivy
