### ISSUE TITLE
Form is invalid when all fields are disabled

### ISSUE THREAD

**Issue by CobusKruger** [angular/angular#39287] opened 2020-10-15 15:13 UTC
# 🐞 bug report

### Affected Package
@angular/forms

### Is this a regression?

Not as far as I know. I know it happens on 9.1.11 and on 10.0.9

### Description

According to the [documentation](https://angular.io/api/forms/AbstractControl#disabled):

> Disabled controls are exempt from validation checks and are not included in the aggregate value of their ancestor controls.

But when all the controls in a group is disabled, the disabled fields appear in the aggregate value, and the group is invalid.

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-ivy-2gpcd4?file=src/app/app.component.ts

In this example, I have three forms, with no validators specified:

- form1 has no fields at all. Its value is an empty object and the form is valid. This is as expected.
- form2 has one enabled field and one disabled one (added in `ngOnInit`). It works exactly as documented, e.g. the form value does not contain the disabled field, and the form is valid.
- form3 contains only the disabled field (added in `ngOnInit`). Its value contains the disabled field and the form is invalid. This is the opposite of the documented behavior.

## 🔥 Exception or Error

No exception

## 🌍  Your Environment

**Angular Version:**

The Stackblitz uses Angular 10.0.9. Below is my local environment where I first noticed it.

<pre><code>
Angular: 9.1.11
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router, service-worker
Ivy Workspace: No

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.901.9
@angular-devkit/build-angular      0.901.9
@angular-devkit/build-ng-packagr   0.901.9
@angular-devkit/build-optimizer    0.901.9
@angular-devkit/build-webpack      0.901.9
@angular-devkit/core               9.1.9
@angular-devkit/schematics         9.1.9
@angular/cli                       9.1.9
@ngtools/webpack                   9.1.9
@schematics/angular                9.1.9
@schematics/update                 0.901.9
ng-packagr                         9.1.5
rxjs                               6.5.5
typescript                         3.8.3
webpack                            4.42.0
</code></pre>

**Anything else relevant?**
Nope

**Comment by Mewster** [comment] 2020-10-23 13:25
Seems related to https://github.com/angular/angular/issues/35184, only with valid/invalid instead of enabled/disabled

**Comment by AndrewKushnir** [comment] 2020-10-23 23:35
Hi @CobusKruger, thanks for creating a ticket and providing a repro.

The behavior is related to the fact that the `status` field of a `FormControl` is responsible for both valid/invalid as well as enabled/disabled states. So if a control is disabled, calling the `valid` field getter would return `false` (see [model.ts](https://github.com/angular/angular/blob/master/packages/forms/src/model.ts#L297)). I think a possible solution might be to split the enabled/disabled and valid/invalid states into 2 separate fields in Forms, but that would require design work and it'd be a major breaking change.

As a possible solution for now you can set the form back to the "enabled" status by calling the `form.enable()` function.

Thank you.

**Comment by Totati** [comment] 2020-10-24 11:35
Hi, when a form is disabled, it's neither valid or invalid, it's disabled [Example](https://stackblitz.com/edit/angular-ivy-yhcwvm?file=src%2Fapp%2Fapp.component.html)

**Comment by CobusKruger** [comment] 2020-10-25 21:09
@AndrewKushnir Setting the form status back to "enabled" won't work, because that enables all the controls. Your answer explains why the form is suddenly no longer valid. It does not explain why the value is included in the aggregate.

I investigated it further and saw that the form itself is [disabled](https://github.com/angular/angular/blob/90c0772743fda18e6b4bab6feaa731038b872cbc/packages/forms/src/model.ts#L759)  when the last of its controls is disabled. This causes the symptom I'm seeing, because in `FormGroup._reduceValue`, the form's `disabled` is checked and [vetos the control's state](https://github.com/angular/angular/blob/90c0772743fda18e6b4bab6feaa731038b872cbc/packages/forms/src/model.ts#L1716):

```typescript
  _reduceValue() {
    return this._reduceChildren(
        {}, (acc: {[k: string]: AbstractControl}, control: AbstractControl, name: string) => {
          if (control.enabled || this.disabled) {
            acc[name] = control.value;
          }
          return acc;
        });
  }
```

So if a form is disabled, its value suddenly contains the value of every contained control, valid or not. That is not correct according to the documentation, which (again) clearly states: 

> Disabled controls are exempt from validation checks and are not included in the aggregate value of their ancestor controls.

I can't find it documented anywhere that a disabled form contains the aggreagate values of all its contained control. Not only is the behavior counter the documentation, but it's also unintuitive.

**Comment by Mewster** [comment] 2020-10-26 10:27
@CobusKruger Sadly, for the disabled control that has every control value, it's documented in the source code ("For a disabled `FormGroup`, [value is] the values of all controls as an object with a key-value pair for each member of the group.")

**Comment by Michael-Ziluck** [comment] 2020-10-29 00:31
@CobusKruger @Mewster I think you two are misunderstanding what some of these things refer to.

Taken from the code for AbstractControl:
```typescript
private _calculateStatus(): string {
    if (this._allControlsDisabled()) return DISABLED;
    if (this.errors) return INVALID;
    if (this._hasOwnPendingAsyncValidator || this._anyControlsHaveStatus(PENDING)) return PENDING;
    if (this._anyControlsHaveStatus(INVALID)) return INVALID;
    return VALID;
}
```
One fundamental issue I'm seeing in your description of the issue is when you said the following:

> "Its value contains the disabled field and the form is invalid"

That's not actually correct. What is correct is that the form is not valid. It is not, however, invalid. That is one thing that is confusing with the Angular framework: `invalid` is not the same as `!valid`.

Lastly, on the [documentation for AbstractControl](https://angular.io/api/forms/AbstractControl#value), it has this information in regards to what `value` represents:
>  - For a FormControl, the current value.
>  - For an enabled FormGroup, the values of enabled controls as an object with a key-value pair for each member of the group.
>  - For a disabled FormGroup, the values of all controls as an object with a key-value pair for each member of the group.
 > - For a FormArray, the values of enabled controls as an array.

So to summarize the issues you are facing:
- Form is invalid when all fields are disabled
  - That is not correct. It is correct to say that the form is not valid, but it is not correct to say it is invalid.
  - If you go to your StackBlitz, add an additional line in the template code that prints out the value for `invalid` on form3. You'll find that it _also_ returns false, exactly as described in the documentation.
- The value for your "form3" contains the disabled field
  - This is working as intended. As I noted above for what `value` actually means, it clearly says that for a disabled `FormGroup`, the values of all controls are included, regardless of if they are disabled.

My suggestion to the Angular team is to update the documentation for the `disabled` to accurately mention that there is a very notable exception. It would also probably be helpful to expand on the documentation currently listed in `valid` and `invalid` to explain that `invalid` does not mean `!valid` and vice versa.

Hope this helps! @AndrewKushnir, beat ya to it!

Side note:
> I can't find it documented anywhere...

Before opening issues and digging through the source code, try to read the documentation for the property you're actually debugging. Will save you and others a bit of time.

Side note to the side note: I tried rewording that last paragraph several times so it wouldn't come off as passive-aggressive. Just know that it was not intended to be.

**Comment by AndrewKushnir** [comment] 2020-10-29 06:22
@Michael-Ziluck thanks for the detailed answer, it makes sense 👍 

I believe the confusion comes from to the fact that the enabled/disabled and valid/invalid/pending are all grouped into one field (status). We should probably consider doing a research on whether separating them at some point in the future would give benefits.

> My suggestion to the Angular team is to update the documentation for the disabled to accurately mention that there is a very notable exception. It would also probably be helpful to expand on the documentation currently listed in valid and invalid to explain that invalid does not mean !valid and vice versa.

Please let us know if you have a proposal on how to improve the docs and/or you can create a PR with the proposed change - that'd be very helpful!

Thank you.

**Comment by AndrewKushnir** [comment] 2021-05-26 23:05
Closing this ticket for now. @Michael-Ziluck please let me know if you have a proposal on how to improve docs.

**Closed by AndrewKushnir** 2021-05-26 23:05 UTC
Labels: P5, comp: docs, comp: forms, forms: disabling controls
