### ISSUE TITLE
AOT errors when going from RC.4 to RC5/6 and 4.0.0 final

### ISSUE THREAD

**Issue by spock123** [angular/angular#15473] opened 2017-03-24 22:23 UTC
Hey guys,
- I'm having a weird issue that I don't know is a bug or something I've done to deserve the wrath of the Angular Gods.

I have 3 different projects, all on RC.4 
Everything works great.
I can upgrade to Angular RC5, RC6 og Angular 4.0.0 final, and I can run the projects in development mode.

But as soon as I start an AOT compilation, it breaks on all versions RC5, 6 and Final with errors like these:

```
@angular/core/src/di/reflective_provider.d.ts:87:123: Cannot find name 'Map'.
@angular/core/src/di/reflective_provider.d.ts:87:165: Cannot find name 'Map'.

Error at /Users/spock/project/dba/dba-frontend/node_modules/rxjs/Observable.d.ts:69:60: 'Promise' only refers to a type, but is being used as a value here.
@angular/core/src/change_detection/differs/iterable_differs.d.ts:15:48: Cannot find name 'Iterable'.
@angular/core/src/change_detection/differs/keyvalue_differs.d.ts:23:18: Cannot find name 'Map'.
@angular/core/src/change_detection/differs/default_keyvalue_differ.d.ts:23:15: Cannot find name 'Map'.
@angular/core/src/change_detection/differs/default_keyvalue_differ.d.ts:27:16: Cannot find name 'Map'.
@angular/compiler/src/compile_metadata.d.ts:369:20: Cannot find name 'Set'.
/@angular/compiler/src/compile_metadata.d.ts:371:28: Cannot find name 'Set'.
@angular/compiler/src/compile_metadata.d.ts:373:15: Cannot find name 'Set'.
@angular/compiler/src/compile_metadata.d.ts:375:23: Cannot find name 'Set'.
@angular/compiler/src/compile_metadata.d.ts:377:17: Cannot find name 'Set'.
@angular/compiler/src/compile_metadata.d.ts:379:25: Cannot find name 'Set'.
@angular/compiler/src/output/output_ast.d.ts:444:63: Cannot find name 'Set'.
```

I've tried most things - clearing npm cache, checking out clean projects from my repositories - to no avail. Does any of you guys have any clue what might be wrong?

My deps for one of the projects (similar to the others, except for other UI libraries like Material):

```
    "angular2-notifications": "^0.4.53",
    "@angular-redux/router": "6.0.1",
    "@angular-redux/store": "6.0.1",
    "@angular/common": "4.0.0-rc.5",
    "@angular/animations": "4.0.0-rc.5",
    "@angular/compiler": "4.0.0-rc.5",
    "@angular/compiler-cli": "4.0.0-rc.5",
    "@angular/core": "4.0.0-rc.5",
    "@angular/forms": "4.0.0-rc.5",
    "@angular/http": "4.0.0-rc.5",
    "@angular/platform-browser": "4.0.0-rc.5",
    "@angular/platform-browser-dynamic": "4.0.0-rc.5",
    "@angular/platform-server": "4.0.0-rc.5",
    "@angular/router": "4.0.0-rc.5",
    "@ng-bootstrap/ng-bootstrap": "^1.0.0-alpha.22",
    "@types/core-js": "0.9.35",
    "@types/filesaver": "0.0.30",
    "@types/hammerjs": "2.0.34",
    "@types/moment": "^2.13.0",
    "@types/node": "6.0.45",
    "@types/source-map": "0.1.28",
    "@types/uglify-js": "2.6.28",
    "@types/webpack": "1.12.35",
    "angular2-infinite-scroll": "^0.3.0",
    "angular2-router-loader": "0.3.5",
    "angular2-template-loader": "0.6.0",
    "angular2-virtual-scroll": "^0.1.0",
    "awesome-typescript-loader": "3.0.3",
    "bootstrap": "4.0.0-alpha.5",
    "brotli-webpack-plugin": "^0.2.0",
    "codelyzer": "2.0.0-beta.4",
    "compression-webpack-plugin": "0.3.2",
    "copy-webpack-plugin": "2.1.6",
    "core-js": "2.4.1",
    "css-loader": "0.25.0",
    "es6-promise": "3.3.1",
    "es6-promise-loader": "1.0.2",
    "es7-reflect-metadata": "1.6.0",
    "exports-loader": "0.6.3",
    "expose-loader": "0.7.1",
    "file-loader": "^0.8.4",
    "filesaver.js": "0.2.0",
    "font-awesome": "^4.7.0",
    "hammerjs": "2.0.8",
    "html-compression-webpack-plugin": "^0.2.3",
    "html-webpack-inline-source-plugin": "0.0.6",
    "html-webpack-plugin": "2.28.0",
    "http-server": "^0.9.0",
    "ie-shim": "0.1.0",
    "ignore-loader": "0.1.2",
    "image-webpack-loader": "2.0.0",
    "immutable": "3.8.1",
    "imports-loader": "0.6.5",
    "json-loader": "0.5.4",
    "less": "2.5.3",
    "less-loader": "2.2.2",
    "moment": "^2.16.0",
    "ng2-file-upload": "^1.2.0",
    "ng2-translate": "3.1.3",
    "node-sass": "3.10.1",
    "nodemon": "1.10.2",
    "normalize.css": "4.1.1",
    "offline-plugin": "3.4.0",
    "parse5": "~1.3.2",
    "raw-loader": "0.5.1",
    "redux": "3.6.0",
    "redux-batched-actions": "^0.1.5",
    "redux-localstorage": "0.4.1",
    "redux-logger": "2.8.1",
    "redux-thunk": "^2.2.0",
    "reflect-metadata": "0.1.8",
    "rimraf": "2.5.4",
    "rxjs": "^5.2.0",
    "sass-loader": "4.0.2",
    "shrinkwrap": "^0.4.0",
    "source-map-loader": "0.1.5",
    "string-replace-loader": "1.0.3",
    "style-loader": "0.13.1",
    "svg-inline-loader": "0.4.0",
    "sw-toolbox": "3.4.0",
    "ts-helpers": "1.1.1",
    "ts-loader": "0.9.5",
    "ts-node": "0.8.0",
    "tsconfig-lint": "0.12.0",
    "tslint": "3.15.1",
    "tslint-loader": "2.1.5",
    "typescript": "2.2.1",
    "url-loader": "0.5.7",
    "webpack": "2.2.1",
    "webpack-dev-server": "2.4.1",
    "webpack-md5-hash": "0.0.5",
    "webpack-merge": "0.14.1",
    "webpack-notifier": "1.5.0",
    "zone.js": "0.8.4"
```

I'm using Webpack 2.2.1 if that matters.
I'm not using the angular-cli

Is this a bug or what did I do to deserve this? :)

Thanks guys

**Comment by DzmitryShylovich** [comment] 2017-03-24 22:35
show tsconfig.ts file

**Comment by spock123** [comment] 2017-03-24 23:56
Here's my tsconfig used for AOT: (and thanx)

`{
  "compilerOptions": {
    "target": "es5",
    "module": "es2015",
    "moduleResolution": "node",
    "sourceMap": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": true,
    "noImplicitAny": false,
    "suppressImplicitAnyIndexErrors": true,
    "baseUrl": "./src",
    "outDir": "./compiled",
    "paths": {
        "modules/*": ["app/modules/*"],
        "services": ["app/services"],
        "services/*": ["app/services/*"],
        "shared/*": ["app/modules/shared/*"],
        "actions/*": ["app/actions/*"],
        "actions": ["app/actions"],
        "store/*": ["app/store/*"],
        "store": ["app/store"]
    }
  },

  "files": [
    "src/app/index.ts",
     "src/app/modules/signup/signup.module.ts",
     "src/app/modules/dashboard/dashboard.module.ts",
     "src/app/modules/profile/profile.module.ts",
     "src/app/modules/reset/reset.module.ts",
     "src/app/modules/items/items.module.ts",
     "src/app/modules/sell/sell.module.ts",
     "src/app/custom_typings.d.ts"
  ],

   "angularCompilerOptions": {
    "genDir": "./compiled",
    "skipMetadataEmit" : true
    },
 "exclude": [
    "node_modules"
  ]
}
`

**Comment by vicb** [comment] 2017-03-25 00:14
Please provide a small repro

**Comment by spock123** [comment] 2017-03-26 11:53
I'm in the process of creating a repo - I'll write my findings here - then we can close it. Just in case other people run into the same issue..

**Comment by spock123** [comment] 2017-03-26 15:20
Hi again,
- I've now produced a minimal application which gives me the AOT errors.

Reproduction:

- clone https://github.com/spock123/angular4-bugfix
- yarn && yarn serve (open localhost:8080)
- yarn aot (breaks)

If I change dependencies from angular 4.0.0 final to RC.4 it works.
Anybody has an idea what's wrong?

I've tried to simplify the code as much I could. 

Cheers

**Comment by DzmitryShylovich** [comment] 2017-03-26 18:31
try to add `"skipLibCheck": true`

**Comment by lennartquerter** [comment] 2017-03-26 18:59
Hi, 

Im also getting the 

> @angular/core/src/change_detection/differs/iterable_differs.d.ts:15:48: Cannot find name 'Iterable'. 

Error message when on angular 4.0.0

Added "skipLibCheck": true and it worked (but I don't think this is the right way to do it?)

tsconfig:


```
{
  "compilerOptions": {
    "target": "es5",
    "exclude" : "node_modules",
    "module": "commonjs",
    "moduleResolution": "commonjs",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": true,
    "skipLibCheck": true,
    "suppressImplicitAnyIndexErrors": true,
    "typingOptions": {
      "exclude" : "node_modules"
    }
  }
}
```

Using webpack ^1.13.0

Could this be a typings problem ?
If I look in the node_modules my IDE can not find Iterables.

**Comment by DzmitryShylovich** [comment] 2017-03-26 19:09
You can use `skipDefaultLibCheck` instead of `skipLibCheck` to only skip type checking of default library declaration files.

**Comment by spock123** [comment] 2017-03-26 19:40
@DzmitryShylovich  Adding "skipLibCheck": true works!

Awesome stuff!!! I would never ever in my entire life have figured this out.
I'm just not sure why this happened from RC4 to RC5 and onwards.. really weird.

**Comment by spock123** [comment] 2017-03-26 20:25
@DzmitryShylovich 

It works! thank you so so much! I'm forever grateful!
We can close the issue now - hope it can help other people who run into a similar problem later... 

Cheers

**Comment by DzmitryShylovich** [comment] 2017-03-26 20:25
@spock123 👍 
you can close it yourself

**Closed** 2017-03-26 20:26 UTC
Labels: flag: can be closed?, state: Need repro

**Comment by BenRacicot** [comment] 2017-03-26 23:36
@DzmitryShylovich just wanted to get opinions on this... I think I found the cause (lots of people online having this issue.

Webpack 2.2.0-rc4 changed: `webpack now exits with non-zero exit code when configuration Promise is rejected.`
I updated my package file and updated my deps which brought me to webpack 2.2.1  →  2.3.2 

Therefore I cannot get anything to compile without changing my tsconfig from `"target": "es5"` to `"target": "es6"`. This doesnt feel right at all but webpack looks like the cause. Can you confirm?
