### ISSUE TITLE
Angular compiler - custom decorators with ngOnDestroy does not work with AOT build

### ISSUE THREAD

**Issue by ArielGueta** [angular/angular#16023] opened 2017-04-15 20:01 UTC
### Versions
4.0.0

### Repro steps
1. Create a class decorator with debugger statement 
```js
export function Test() {
  return function ( constructor ) {
     debugger;
  }
}
```
2. Use the class on a component
```js
@Component({...})
@Test()
export class TestComponent {}

```
3. Run the command `ng build --aot --prod`

### The log given by the failure.
The debugger statement never called. The decorator **doesn't** work. 

I also tried to create the decorator as npm package and compile the source file with the angular compiler `ngc -p tsconfig.json` but with no luck. 

### Desired functionality.
Custom decorators should be support out of the box by AOT.

### Note:
It's not an angular-cli problem, the problem was also the same with angular2-webpack-starter.

**Comment by tbosch** [comment] 2017-04-17 17:43
Hello,
could you create a reproduction for this, e.g. a branch on Github?

**Comment by ArielGueta** [comment] 2017-04-17 22:18
After investigating, I found the real problem, and it's interesting. 

In my custom decorator I'm trying to override the `ngOnDestroy` method, for example:

```ts
export function Test() {
  return function ( constructor ) {
   constructor.prototype.ngOnDestroy = function () {
     console.log("ngOnDestroy");
   };
 }
}
```
### But - 

1. When working with JIT mode, everything is working fine. 

2. When working with AOT - only when I add the `ngOnDestroy` **explicitly**, Angular will call my decorated method. 

```ts
@Component({
  ...
})
@Test()
export class TodoComponent {
  // When I am in AOT mode, and I don't define this method my decorated method will not run  
  ngOnDestroy() {
  }

}

```

Any ideas why this is happening?

**Comment by robisim74** [comment] 2017-04-30 20:49
Same problem here using _ngOnInit_: I'm creating a class decorator that uses `apply` to modify the _ngOnInit_ method:
```
export function Test(): ClassDecorator {
    return function (target: Function): void {
        let targetNgOnInit: Function = target.prototype.ngOnInit;
        target.prototype.ngOnInit = function () {

            console.log("test");
            
            if (targetNgOnInit) {
                targetNgOnInit.apply(this);
            }
        }
    }
}
```
It works fine in JiT mode, but in AoT it works only if _ngOnInit_ method already exists in the component.

**Comment by robisim74** [comment] 2017-05-01 12:36
@tbosch I created a repository: https://github.com/robisim74/angular-decorators

JiT mode: `npm start`
AoT mode: `npm run build`

The problem doesn't seem to relate only to lifecycle hooks methods: AoT mode doesn't work also if you try to create a custom property or a custom method into the decorator.

**Comment by NetanelBasal** [comment] 2017-05-01 15:24
Hey @tbosch ,

The same problem is here. 
https://github.com/NetanelBasal/ngx-auto-unsubscribe
https://github.com/NetanelBasal/angular2-take-until-destroy

Both modify the `ngOnDestroy` hook.

**Comment by robisim74** [comment] 2017-05-09 22:39
@tbosch @vicb Any updates about this issue? Is it a bug? Or are there other solutions? Thanks.

**Comment by tbosch** [comment] 2017-05-10 21:38
This is a general "problem" with AOT: It relies on being able to statically analyze things like lifecycle hooks, properties with `@Input` on them, constructor arguments, ...
As soon as there is dynamic logic that adds new methods / properties, our AOT compiler does not know about this.

**Comment by tbosch** [comment] 2017-05-10 21:39
As we are moving to AOT by default in the future, this won't go away.

Sorry, but closing as infeasible.

**Closed by tbosch** 2017-05-10 21:39 UTC
Labels: comp: core & compiler, severity2: inconvenient

**Comment by robisim74** [comment] 2017-05-10 23:32
@tbosch Thanks for the answer

**Comment by NetanelBasal** [comment] 2017-05-11 04:42
I'm sorry, but it's very disappointing. If that's how it is, we do not have the ability to take advantage of the ability of Decorators. ( And Angular it's all about decorators )

I wrote and created things that rely on this ability and now I understand that it will not work with AOT.

I do not come to complain, I know you work very hard, but it's just frustrating. 

Thanks for the answer.

**Comment by lucato** [comment] 2017-05-11 15:33
Since the problem appears because Angular cant find the ngOnDestroy/ngOnChanges functions in class statically one only needs to help Angular out with that.
Here is how I managed to fix the problem:
```
export class ObserveInputsBase implements OnChanges, OnDestroy {
  ngOnChanges(changes: SimpleChanges): void {}
  ngOnDestroy(): void {}
}

@Component({
  ...
})
@Test()
export class TodoComponent extends ObserveInputsBase  {
 constructor(){
   super();
  }
}
```
where Test is the decorator overwriting OnDestroy/ngOnChanges and ObserveInputsBase gives Angular what needed to later overwrite the corresponding functions. Also note the  needed super() call of base class in the constructor.  
Hope this helps.

**Comment by lucato** [comment] 2017-05-11 15:38
Since the problem appears because Angular cant find the ngOnDestroy/ngOnChanges functions in class statically one only needs to help Angular out with that.
Here is how I managed to fix the problem:
```
export class ObserveInputsBase implements OnChanges, OnDestroy {
  ngOnChanges(changes: SimpleChanges): void {}
  ngOnDestroy(): void {}
}

@Component({
  ...
})
@Test()
export class TodoComponent extends ObserveInputsBase  {
 constructor(){
   super();
  }
}
```
where Test is the decorator overwriting OnDestroy/ngOnChanges and ObserveInputsBase gives Angular what needed to later overwrite the corresponding functions. Also note the  needed super() call of base class in the constructor.  
Hope this helps.

**Comment by robisim74** [comment] 2017-05-11 20:12
@NetanelBasal I think that for now we have to accept things as they are: basically when constructing a component of Angular, it should always be implementing OnInit, and OnDestroy if there are subscriptions. If you are building third-party libraries, I do not think it's an aggravation that some hooks methods are required.

@lucato Thanks for sharing your idea. Just a suggestion: if you add `Injectable` or `Component` to your superclass, you can avoid to implement the constructor with a `super` call.

But this is exactly the point: since Angular has made his own compiler, and as Tobias says, they are thinking of _moving to  AoT by default_, meaning that Angular will no longer be just a framework, but a _language_ to all effects. Think that you can eliminate the costrunctor and `super` call: this is really an anti-pattern for the OOP. If you also think that you can not prototype a function or a property like in the case of decorators it is an anti-pattern for TypeScript and JavaScript, that is, the languages on which it is based.
I disagree that it is _dynamic_ creation because it is not based on runtime objects, but is well known at the time of compilation. Is it difficult? Of course. But _tsc_ compiler succeeds, _ngc_ compiler yet no. Anyway, I think we have to trust the work they are doing.

**Comment by robisim74** [comment] 2017-05-13 13:42
It seems that _ngc_ compiler fails because it does not really test decorators: 
```
        if (depth === 0) {
          // If depth is 0 we are evaluating the top level expression that is describing element
          // decorator. In this case, it is a decorator we don't understand, such as a custom
          // non-angular decorator, and we should just ignore it.
          return IGNORE;
        }
```
https://github.com/angular/angular/blob/38a7e0d1c77399f3fa9db5883eb2447e41e2641a/packages/compiler/src/aot/static_reflector.ts#L407-L412

So _custom non-angular decorators_ are ignored: and this explains why the functions in them only work if they work on objects already evaluated by the compiler.

**Comment by oliverjanik** [comment] 2017-07-07 05:44
This would be acceptable ONLY IF JIT was decent. As it stands JIT is atrociously slow. This whole AOT is turning into a giant mess.

**Comment by kmathy** [comment] 2017-07-24 13:55
Any news here? One of my projects use a custom decorator (AutoUnsubscribe) wrote by @NetanelBasal, and it's still impossible to use it in AoT.

**Comment by NetanelBasal** [comment] 2017-07-24 13:59
@kmathy If you work with AOT the `ngOnDestroy` method must be present, even if empty! Otherwise `ng build --prod` will optimize away any calls to `ngOnDestroy`, even if the method is added by the @AutoUnsubscribe decorator.

**Comment by kmathy** [comment] 2017-07-24 14:29
So we can use your custom decorator only if we add the method ngOnDestroy explicitly? Great! 👍

**Comment by istiti** [comment] 2017-08-21 18:59
Still not understand why in JIT it wirks but with AOT it doesn't without add them explicitly even if empty, can't we go without this explicit add? Thanks

**Comment by raysuelzer** [comment] 2017-11-09 08:49
@NetanelBasal  can you confirm that we can use the custom decorator as long as we provide some noop implementation of ngOnDestroy?

**Comment by NetanelBasal** [comment] 2017-11-09 08:55
@raysuelzer  Yes, you can.

**Comment by alshdavid** [comment] 2017-11-15 04:38
Is there a solution to this?

Would be nice to not need the inclusion of `ngOnDestroy(){}` on the components using my decorator

**Comment by james-schwartzkopf** [comment] 2017-11-16 05:59
Could this at least generate an error?  I had no idea AOT was causing my app to leak observables due to this.

**Comment by ratoaq2** [comment] 2018-02-26 12:53
AOT should be smarter and always consider ngOnInit/ngOnDestroy/ngEtc..., even if the method is not explicitly defined.

**Comment by amcdnl** [comment] 2018-04-16 18:45
Related to - https://github.com/angular/angular/issues/23038#issuecomment-381670075

**Comment by SoEasy** [comment] 2018-09-20 09:47
Hello! I also wanted to use custom decorators and came up with following solution:
`
// custom decorator
function JsonRpcService(url){
  return function(target){ /**/ }
}

// custom decorator applyer
function DecorateBy(decorator): { new(): any } {
  console.log('decorate hack works fine, welcome to realize many decorators');
  const resultClass = class {
    constructor() {}
  };
  const decoratedTarget = decorator(resultClass);
  return decoratedTarget ? decoratedTarget : resultClass;
}

@Injectable()
export class VedContractCheckService extends DecorateBy(JsonRpcService('/ved-outsider/jsonrpc')) {
  constructor() {
    // Single restriction - we must call super
    super();
  }
}
`

As we know - decorators is only functions witch called with target constructor as argument. We can trust inheritance and call the decorators manually.

Hope that solution helps you.

**Comment by nasreddineskandrani** [comment] 2018-09-29 07:12
@tbosch `Sorry, but closing as infeasible.`  
=> `Sorry, but closing this until someone find a good idea.` 
https://github.com/angular/angular/issues/23038

**Comment by trotyl** [comment] 2018-09-29 07:28
This is already supported in Ivy, no need for any more idea.

**Comment by nasreddineskandrani** [comment] 2018-09-29 07:32
I highlighted his statement :) since i didn't like it 
@trotyl Yep that's what i wrote here https://github.com/angular/angular/issues/20941
for now it's delayed, no? o O or i missed something

**Comment by trotyl** [comment] 2018-09-29 07:50
@nasreddineskandrani I don’t know what you mean delayed, that’s a different proposal which being much easier to implement in Ivy, the design and work should only be started after Ivy becoming stable.

**Comment by nasreddineskandrani** [comment] 2018-09-29 08:05
the first proposal was not on ivy and they closed it https://github.com/angular/angular/pull/20682
> The bad news is that we don't want to add it to ViewEngine and than have to reimplement in Ivy because the API will be different in Ivy. So for now I am going to close this PR and we will add this feature to Ivy.

**Comment by alshdavid** [comment] 2019-02-15 13:37
Why not allow us to use comments to tell the static analysis tool to add certain hooks to classes if not already present?

Say we decorate the decorator
```
/// @angular-aot keep:onInit,onDestroy
function myDecorator(target, key) {
    ...
}
```

**Comment by dinohorvat** [comment] 2019-03-27 10:45
Are there any plans for this? Or it will be ignored completely.

**Comment by stupidawesome** [comment] 2019-05-26 04:06
I'm working on a library called [NgObservable](https://github.com/zodiac-team/zodiac-ui/tree/master/libs/ng-observable) that implements custom lifecycle decorators that are AoT cross-compatible with ViewEngine and Ivy. The tradeoff is that each component must extend the `NgObservable` base class to get around the AoT limitations, which in turn implements every angular lifecycle hook leading to slightly larger component factories.

It's still in the works but I'm keen to get feedback. You can [grab it on NPM](https://www.npmjs.com/package/@zodiac-ui/ng-observable).

**Comment by therepo90** [comment] 2019-07-09 13:42
Lack of custom decorators is one of the most annoying things in angular...

There is "jit" flag in module thought that could help but that's not cool.

**Comment by mtuzinskiy** [comment] 2019-08-17 14:48
_Any_ custom decorators don't work with AOT, not only method decorators.  
And yes, I agree with @therepo90 that it's very annoying.

**Comment by gotik** [comment] 2019-08-23 16:46
This a solution we found to prevent us from leaving decorators that depend on `ngOnDestroy` without the hook. We make sure the target of the decorator has the `OnDestroy` type, that way compiling will error if you don't implement `OnDestroy`.

example:

```
function SomeDecorator(target: OnDestroy) {
    ...
}

```

if you use it without correctly implement `OnDestroy` you'll see something like
`error TS2345: Argument of type 'SomeComponent' is not assignable to parameter of type 'OnDestroy'.` With that type validation, it won't let you forget about the `ngOnDestroy` hook by mistake.

If your decorator adds properties  to the target you can use a custom type that extends `OnDestroy`

```
interface SomeDecoratorTarget extends OnDestroy {
  someExtraPropertyThatIsAddedInTheDecorator?: any;
}

function SomeDecorator(target: SomeDecoratorTarget) {
    ...

  if (!target.someExtraPropertyThatIsAddedInTheDecorator) {
    Object.defineProperty(target, 'someExtraPropertyThatIsAddedInTheDecorator', {
      value: 'some value',
    });
 }

}

```

**Comment by Cole-Beckwith-SP** [comment] 2019-09-16 22:01
The existing workaround sounds like it's adding an empty lifecycle hook to the component. Will this continue to work while using Ivy?

**Comment by robisim74** [comment] 2019-09-17 06:52
@Cole-Beckwith-SP See here: https://github.com/angular/angular/issues/31495
