### ISSUE TITLE
[src] attribute the first time it calls to an undefined endpoint

### ISSUE THREAD

**Issue by danicomas** [angular/angular#3765] opened 2015-08-21 08:20 UTC
GET http://localhost:8080/undefined 404 (Not Found)

```html
<img [src]="data.avatar_url" width="100" height="100"/>
```

```js
this.data = {};
http.get('https://api.github.com/users/danicomas').toRx().map(res => res.json()).subscribe(response => this.data = response);
```

**Comment by PascalPrecht** [comment] 2015-08-21 08:22
Sounds like your expression really evaluates to `undefined` because it is undefined. Can you give some more information on what exactly you're doing?

**Comment by danicomas** [comment] 2015-08-21 08:22
@PascalPrecht I have updated the first comment :D

**Comment by danicomas** [comment] 2015-08-21 08:31
@PascalPrecht I have tried [href] attribute and it doesn't happen.

```js
<a [href]="data.blog">{{data.blog}}</a>
```

**Comment by pkozlowski-opensource** [comment] 2015-08-21 08:44
So, I've just tested how this behaves in Chrome without Angular. Executing this code in the console:

```javascript
var imgEl = document.createElement('img');

imgEl.src; // outputs ""

imgEl.src = undefined; //triggers https://developer.mozilla.org/en-US/docs/Web/API/undefined 
imgEl.src = null; //triggers https://developer.mozilla.org/en-US/docs/Web/API/null

imgEl.src = ""; //no request triggered
```

So, looking at the above it seems like browsers (or at least Chrome) will do "to string" conversion for `null` \ `undefined`. Now, I find this behavior debatable, maybe it makes sense to file an issue for this?

In any case the work-around is simple: initialize data with an empty string (`this.data = {avatar_url: ''};`) or write a custom pipe to do null / undefined to string conversion (`<img [src]="data.avatar_url | tostring"`) or just use a conditional exp: `<img [src]="data.avatar_url ? data.avatar_url : ''">`

**Comment by danicomas** [comment] 2015-08-21 08:54
In angular1 we had ng-src directive that it controlled the empty strings for this reason we had this problem now we have directly a html attribute (we could make an img directive or ng-src too). However, for me these workarounds are ok. Thanks @pkozlowski-opensource

**Comment by PascalPrecht** [comment] 2015-08-21 09:00
We don't want to have something like ng-src anymore because we're binding
to properties in A2 which should also ensure escaping.

Pawel, I would actually also expect this to end up as an empty string.
Predefining an object with dedicated properties doesn't sound like the
right solution to me. Using pipes is kinda okay, but still I'd expect this
to just work without me doing anything additional than providing that
expression.

How do we want to handle that case? I vote for opening an issue for it.

**Comment by pkozlowski-opensource** [comment] 2015-08-21 09:06
@PascalPrecht currently we don't have any mechanism in the framework to have special setters that could have "escape" logic. Adding this would allow us to have special casing but it is not ideal as it introduces new concepts, code etc.

Honestly I must say that I find Chrome's behavior surprising here - I would expect it to interpret null / undefined as an empty string.

It would be great if someone could check what DOM / HTML spec has to say here (I'm not sure if this is specified, actually) and check what is behavior in other browsers.

**Comment by PascalPrecht** [comment] 2015-08-21 09:14
Oh, with the escaping I actually meant that the value of the expression is going to be assigned once evaluated, but not before.w

**Comment by pkozlowski-opensource** [comment] 2015-08-21 09:18
@PascalPrecht not sure I got what you are trying to say in your last comment... The situation here is that the expression evaluates to undefined and we are setting this as a property of the img element. But the prop setter on the img element seems to be converting this value to string. You can observe the same without angular being involved at all.

**Comment by PascalPrecht** [comment] 2015-08-21 09:21
Yea gotcha. My point was just that in A1 we have ng-src which basically "escapes" by evaluating an interpolation, and once done, assigning it to it's `src` attribute. That's why we don't have broken requests. 

A2 binds to properties as you know, and yes there's no real "escaping" but also, the evaluated value gets only assigned to the property, once evaluated. So we also don't get broken requests (despite the fact that  a request to 'undefined' might of course be a broken url, but that's a different issue).

**Comment by SebastianM** [comment] 2015-08-21 09:23
@pkozlowski-opensource The spec says it has to be a string:
>
When the user agent is to update the image data of an img element, it must run the following steps:
...
>Otherwise, if the element has a src attribute specified and **its value is not the empty string, let selected source be the value of the element's src attribute**, and selected pixel density be 1.0. Otherwise, let selected source be null and selected pixel density be undefined.

http://www.w3.org/TR/2012/WD-html5-20121025/the-img-element.html#attr-img-src

**Comment by pkozlowski-opensource** [comment] 2015-08-21 09:25
@SebastianM this is sepc for the src _attribute_, not property, right?

**Comment by PascalPrecht** [comment] 2015-08-21 09:28
Yes this is the spec for `src` attribute.

**Comment by SebastianM** [comment] 2015-08-21 09:53
@pkozlowski-opensource yes. I found nothing that describes the behavior of the property explicitly (but the description fits to your code example: it's not an empty string so the browser starts fetching the src).

As you said:
> Honestly I must say that I find Chrome's behavior surprising here - I would expect it to interpret null / undefined as an empty string.
I also think that the current browser behavior is useless and someone should file a bug to discuss this.

**Comment by danicomas** [comment] 2015-08-21 10:17
I have tried your code @pkozlowski-opensource with the following browsers:
- chrome 44.X: undefined request 
- firefox 38.X: undefined request
- microsoft edge: undefined request
- opera classic 12.X: undefined request

Good way would be apply this in consideration for the browser but by now we should looking for a solution inside the framework in this case angular2 as angular1 is doing. What do you think? @pkozlowski-opensource @PascalPrecht  @SebastianM

**Comment by gdi2290** [comment] 2015-08-21 13:06
I mentioned this subtlety in this issue https://github.com/angular/angular/issues/3007 (for me it was making `/null` requests)
the current workaround is `|| ''` so 
```html
<img [src]="data.avatar_url || '' " width="100" height="100">
```
or default the initial `avatar_url` value to empty string (probably a good idea anyways). 


I would say if interpolation gets to have a default case of empty string then `[src]` should as well. 
Here's my code
```html
<div>
  <img [src]="(model?.getValue('boxshot') | async) || '' ">
</div>
```

**Comment by jpsfs** [comment] 2015-08-21 14:05
My 2cents on this matter:

I understand the browser's behavior. I actually can have a "null" or "undefined" resource to get and the browser should not be too picky about it. Now, the null or undefined value being translated to _"null"_ or _"undefined"_, that is another issue.

On the very beginning of angular 2, correct me if I'm wrong, the interpolation translated _null_ and _undefined_ to _""_ (empty string). Since alpha 27/28 translates to _"null"_ or _"undefined"_ respectively. Maybe it's something that can be revisited (sooner the better because it can have a breaking effect).

Cheers!

**Comment by pkozlowski-opensource** [comment] 2015-08-21 14:10
@jpsfs @gdi2290 I've got the impression that we are mixing 2 separate problems and I don't think we should have the same behavior for interpolation and property binding! Let me explain, assuming that `exp` evaluates to null:
* `<div>{{exp}}</div>` - this should evaluate to empty string (so `<div></div>`)
* `<my-component my-property="exp"></my-component>` should bind `null` to `my-property`, not an empty string

**Comment by gdi2290** [comment] 2015-08-21 23:27
@pkozlowski-opensource  yeah sorry, I meant that the two problems has the same value type requirement (`string`). The spec for `img.src` suggests the value should be type `string` and if someone wanted a `/null` or `/undefined` endpoint then you would simply provide a string value of `"null"` or `"undefined"` rather than relying on the img tag to do the type corhorsion. For the `<div>{{ exp }} </div>` if you wanted `"null"` then you would provide a string version of `null` so I think the same logic should apply for `[src]`. I don't know where this change should go DomCompiler, DomRenderer, or Change Detection (if it's not in CD then I can understand why you think it's not the same problem). 

Perhaps the actual problem is ensuring the correct types for DOM properties. If the problem is being too DOM specific then maybe a DOM version ChangeDetection in order to keep the separation? We can always go back to Angular 1 with `[ng-src]`, as we did with `(ng-submit)`, since that would solve everyone's problem

**Comment by mhevery** [comment] 2016-07-01 20:44
closing as working as intended `[]` does not provide `null` => (empty string), only `{{ null }}` provides this. Use `<imp [src]=" expression || '' ">` to get your behavior.

**Closed by mhevery** 2016-07-01 20:44 UTC
Labels: comp: core/view, effort2: medium (day), P2: required, type: bug

**Comment by maziarrezaei** [comment] 2016-11-14 22:19
The solutions above did not work for me for this situation:

`[src]='getImageUrl() | async'`

before the promise is resolved, I have a momentarily null value that causes the request to be triggered anyway. The solution that worked for me and can easily cover the above scenarios too is:

`[attr.src]='getImageUrl() | async'`

**Comment by wangta69** [comment] 2019-05-31 02:22
How about adding ngIf
<img *ngIf="data.avatar_url"  [src]="data.avatar_url" width="100" height="100"/>
