### ISSUE TITLE
Allow capturing event handlers in HTML template as Observables (equivalent of .fromEvent)

### ISSUE THREAD

**Issue by moniuch** [angular/angular#20965] opened 2017-12-12 19:50 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Currently the callbacks `(click)="doSomething($event)"` are imperative. In `doSomething`, if you want to combine the $event with another stream or streams (such as ngrx store), you have to use special techniques that allow you to combine the event with other data, for example, using

`of(null).withLatestFrom(fromRoot.mySelector)...`
This feels more like a workaround rather than modern way of initiating an action.

## Expected behavior
My vote would be to have a more *reactive* approach, in that an event is captured to an observable defined as a public property of a container, and is in effect an equivalent of `.fromEvent($event)`.
Instead of `(click)="doSomething($event)" I would rather:
- define `myClickStream$: Observable<MouseEvent>`
- capture the stream of events in HTML template as is: `(click$)="myClickStream$"`
- define reactive behavior, as in:

```
this.myClickStream$  // this being an equivalent of .fromEvent
.pipe(
 withLatestFrom(fromRoot.mySelector, ($event, mySelector) => ({...}) )
)
// no subscribe needed - it would be automatically subscribed just as with the async pipe
```

Others:
The pattern of `[eventname]` suffixed by a dollar sign (`(click$)`, `(keydown$)` etc) could be introduced as angular-reserved naming scheme so to enable consistency.

**Comment by vicb** [comment] 2017-12-12 23:32
Closing as a duplicate of https://github.com/angular/angular/issues/13248

The issue has been opened for a long time but we are still thinking about the best way to do it. It will come at some point.

**Closed by vicb** 2017-12-12 23:32 UTC
Labels: comp: common
