### ISSUE TITLE
Values emitted from the “changes” of QueryList are of type “any”

### ISSUE THREAD

**Issue by lazarljubenovic** [angular/angular#38458] opened 2020-08-14 05:52 UTC
# 🚀 feature request

### Relevant Package
This feature request is for `@angular/core`.

### Description
`QueryList<T>` emits changes as `Observable<any>` instead of `Observable<QueryList<T>>`.

https://github.com/angular/angular/blob/25f79ba73e19bcf7c0925283a2dfdf2d9186eb49/packages/core/src/linker/query_list.ts#L48

### Describe the solution you'd like
```
public readonly changes: Observable<QueryList<T>> = new EventEmitter();
```

### Describe alternatives you've considered
Manual casting. 

### Breaking change
Kinda?

**Comment by jotatoledo** [comment] 2020-08-14 09:43
I wonder what was the reasoning behind this manual-casting approach instead of splitting that into 2 props., one for the subject (emitter) and other for the stream (changes). I wonder how many people already depend on the fact that casting `changes `to `EventEmitter `works....

**Comment by JoostK** [comment] 2020-08-14 09:53
There is already a PR for this: #30375

**Comment by lazarljubenovic** [comment] 2020-08-14 14:00
> I wonder what was the reasoning behind this manual-casting approach instead of splitting that into 2 props., one for the subject (emitter) and other for the stream (changes). Most likely a lot of ppl already depend on the fact that casting `changes `to `EventEmitter `works....

Probably the same reasoning as [here](https://github.com/angular/angular/pull/19188#discussion_r139217537). Personally, I think the rationale of 84 bytes is laughable, but oh well.

**Comment by pkozlowski-opensource** [comment] 2020-08-14 14:33
> There is already a PR for this: #30375

And this is a duplicate of the existing issue #30296
Closing as a duplicate of #30296

**Closed by pkozlowski-opensource** 2020-08-14 14:33 UTC
Labels: comp: core, core: queries, cross-cutting: types, state: has PR, type: feature
