### ISSUE TITLE
SafeResourceUrl not working with href in Angular 15

### ISSUE THREAD

**Issue by mcalmus** [angular/angular#48487] opened 2022-12-14 15:12 UTC
### Which @angular/* package(s) are the source of the bug?

core, platform-browser

### Is this a regression?

Yes

### Description

After upgrading to Angular 15 a SafeResourceUrl can no longer be assigned to an HREF:

`this.data = this.sanitizer.bypassSecurityTrustResourceUrl(<someurl>);`

`<a [href]="data">My Link</data>`

### Please provide the exception or error you saw

```true
error TS2322: Type 'SafeResourceUrl' is not assignable to type 'string'.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.0.2
Node: 16.16.0
Package Manager: npm 9.1.2
OS: win32 x64

Angular: 15.0.2
```

**Comment by JoostK** [comment] 2022-12-14 15:43
This is indeed a known issue with template-type checking, as reported in #33028. The simplest workaround would be to change the assignment to use `[href]="$any(data)"`.

Closing as duplicate of #33028.

**Closed by JoostK** 2022-12-14 15:43 UTC
Labels: area: core, core: sanitization, compiler: template type-checking
