### ISSUE TITLE
Injecting multi provider in lazyloading

### ISSUE THREAD

**Issue by belchevgb** [angular/angular#25699] opened 2018-08-28 13:39 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
There are 2 providers: NumberProvider and StringProvider. They are registered as multi provider. When you navigate to /lazy the result from the both providers should be displayed, instead only the provider that is not lazy loaded is being injected in CompositeProvider which is injected in LazyComponent. If I use this.injector.get(PROVIDER_TOKEN) in CompositeProvider.get() the behavior is the same. Is there a way both providers to be injected ?

## Expected behavior
StringProvider and NumberProvider should be injected in CompositeProvider.

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-phschi

## Environment

<pre><code>
Angular version: 6.1.0

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.9.4
- Platform:  Windows

</code></pre>

**Comment by trotyl** [comment] 2018-08-29 02:07
Duplicate of https://github.com/angular/angular/issues/18894

**Closed** 2018-09-04 18:58 UTC
