### ISSUE TITLE
Input elements inside *ngFor is damn slow in Safari (Performance issue)

### ISSUE THREAD

**Issue by raghles** [angular/angular#19688] opened 2017-10-12 15:03 UTC
http://plnkr.co/edit/qv0d403ykShKueeyWSxx?p=preview

## Current behavior
Create an array(sampleArray) with the length of 1000. Do *ngFor for sampleArray and create input element inside it.
```
<div *ngFor="let da of sampleArray; let i=index;">
     <input type="text" />
</div>

```
Run this, and enter something in textbox. In chrome it works fine. But in Safari it takes minimum one second for each character appears in textbox. If you type fast 10 characters in textbox, it will take 10 seconds to appear.

## Expected behavior
Text needs to appear immediately after typing in Safari.

## Minimal reproduction of the problem with instructions
I have created a plunker. Please open this in Safari & Chrome to see the difference.
[http://plnkr.co/edit/qv0d403ykShKueeyWSxx?p=preview](http://plnkr.co/edit/qv0d403ykShKueeyWSxx?p=preview)

MacOs:  Sierra
Browser: Safari (desktop) version 11.
AngularJS: Version 4.0.0

~~From my investigation, *ngFor is re-rendering on every keypress in textbox, even focusing textbox. Can we prevent run digest cycle for textboxes. Eventhough I didn't attach any model to textbox, why digest cycle or ngDoCheck is running for every key press.~~

Can anyone please help me? Thanks in advance.

**Comment by Wykks** [comment] 2017-10-12 18:10
I don't see any *ngFor re-rendering when typing in chrome : 
![image](https://user-images.githubusercontent.com/1236069/31511822-30eb153e-af89-11e7-95c2-efa5abe095d2.png)
Does safari have this kind of tool ?

**Comment by raghles** [comment] 2017-10-13 10:52
@Wykks Sorry. I used hostlistner and that was the cause for digest cycle. *ngFor is not re-rendering. I don't know the root cause.

**Comment by tbosch** [comment] 2017-10-13 15:01
This seems to be a safari bug. I can reproduce this with a plain html page that contain 1000 inputs.
See here: http://plnkr.co/edit/y5Jq35XNYySYhvYEKCZI?p=preview

Closing as not angular related.

**Closed by tbosch** 2017-10-13 15:01 UTC
Labels: comp: core & compiler

**Comment by chandarsunderraj** [comment] 2017-10-19 14:02
I tried the same in Safari - Version 10.1.2 (12603.3.8)   with 3000 inputs & checkboxes it works fine. Please check this plunkr
http://plnkr.co/edit/Ry3hW6ZXjjf8nCtzJlgf?p=preview

This seems like a Angular2 Issue.

**Comment by tbosch** [comment] 2017-10-19 15:23
I think this is related to safari thinking these inputs are actually username / password combinations. I.e. the layout of the original template was 
```
<div>
<p>
  <label>Name:</label>
  <input type="text">
</p>
</div>
```

That's what I saw in the Safari profiler (if I interpret the results correctly). This would also explain why the example of @chandarsunderraj works fine as it does not look like a repeated username / password form

**Comment by chandarsunderraj** [comment] 2017-10-19 17:15
What might be the other possible problems  that might cause an issue like this ?
