### ISSUE TITLE
whenStable does not resolve within async test when using an async validator

### ISSUE THREAD

**Issue by giniedp** [angular/angular#16817] opened 2017-05-16 11:46 UTC
```
[x] bug report
```

**Current behavior**
The promise of `whenStable` does resolve in time when used in an `async` test with a reactive form and async validators. Code and unit tests within the `whenStable` block do not run.
However when using jasmines `done` callback instead of `async` the behavior is correct

**Expected behavior**
same as when using jasmines `done` callback

**Minimal reproduction of the problem**
http://embed.plnkr.co/OKNpXpeBBlQLUXJZidlS/

**Comment by giniedp** [comment] 2017-05-16 11:53
probably related to https://github.com/angular/angular/issues/15486

**Comment by jasonaden** [comment] 2017-05-18 00:52
Thanks for reporting this issue. However this issue is a duplicate of an existing issue #15486. Please subscribe to that issue for future updates.

**Closed by jasonaden** 2017-05-18 00:52 UTC
