### ISSUE TITLE
Build optimizer leads to uncaught runtime exceptions from monaco editor

### ISSUE THREAD

**Issue by petermikitsh** [angular/angular#29614] opened 2019-03-30 18:32 UTC
# 🐞 bug report

### Affected Package

I am using: **Angular 7**

Full versions listed in **Environment** section at bottom of issue.

⚠️ Update: Affected package appears to be `@angular-devkit/build-optimizer`.

### Is this a regression?

It's unclear if so.

### Description

When building and serving my application with buildOptimization enabled, runtime exceptions are thrown by the monaco editor.

With `"buildOptimization": false` (running in development mode):

<img width="1041" alt="Screen Shot 2019-03-30 at 11 27 42 AM" src="https://user-images.githubusercontent.com/1571918/55280177-08c7b080-52df-11e9-857c-9f54962b4b09.png">

With `"buildOptimization": true` (running a production build):

<img width="1049" alt="Screen Shot 2019-03-30 at 11 28 33 AM" src="https://user-images.githubusercontent.com/1571918/55280180-0f562800-52df-11e9-8214-6577dd359a3b.png">

## 🔬 Minimal Reproduction

~https://github.com/petermikitsh/angular-buildoptimization-bug~
Simpler reproduction: https://github.com/petermikitsh/buildoptimizer-error

```
git clone https://github.com/petermikitsh/buildoptimizer-error.git
cd buildoptimizer-error
npm install
npm start
```

Then navigate to http://0.0.0.0:8080/.

## 🔥 Exception or Error
<pre><code>ERROR Error: Cannot read property 'createKey' of undefined

TypeError: Cannot read property 'createKey' of undefined
    at t.bindTo (contextkey.js.pre-build-optimizer.js:439)
    at new t (messageController.js.pre-build-optimizer.js:43)
    at types.js.pre-build-optimizer.js:138
    at e._createInstance (instantiationService.js.pre-build-optimizer.js:110)
    at e.createInstance (instantiationService.js.pre-build-optimizer.js:79)
    at t [as constructor] (codeEditorWidget.js.pre-build-optimizer.js:194)
    at t [as constructor] (standaloneCodeEditor.js.pre-build-optimizer.js:69)
    at new t (standaloneCodeEditor.js.pre-build-optimizer.js:167)
    at standaloneEditor.js.pre-build-optimizer.js:57
    at GR (standaloneEditor.js.pre-build-optimizer.js:44)
    at errors.js.pre-build-optimizer.js:12
    at e.invokeTask (zone.js.pre-build-optimizer.js:423)
    at Object.onInvokeTask (ng_zone.ts:262)
    at e.invokeTask (zone.js.pre-build-optimizer.js:422)
    at t.runTask (zone.js.pre-build-optimizer.js:195)
    at t.invokeTask (zone.js.pre-build-optimizer.js:498)
    at invoke (zone.js.pre-build-optimizer.js:487)
    at n.args.(:8080/anonymous function) (http://localhost:8080/polyfills.577ede6d2053947c8714.js:1:26878)
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>Angular CLI: 7.3.7
Node: 10.15.0
OS: darwin x64
Angular: 7.2.11
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.7
@angular-devkit/build-angular     0.13.7
@angular-devkit/build-optimizer   0.13.7
@angular-devkit/build-webpack     0.13.7
@angular-devkit/core              7.3.7
@angular-devkit/schematics        7.3.7
@angular/cli                      7.3.7
@ngtools/webpack                  7.3.7
@schematics/angular               7.3.7
@schematics/update                0.13.7
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.29.0
</code></pre>

**Anything else relevant?**

**Comment by petermikitsh** [comment] 2019-03-30 20:15
Update: a much simpler demo repo => https://github.com/petermikitsh/buildoptimizer-error

The error seems to be in `@angular-devkit/build-optimizer`

**Comment by petermikitsh** [comment] 2019-03-30 20:33
I've also reported this bug here => https://github.com/angular/angular-cli/issues/14033

This issue (#29614) may be considered a duplicate.

**Comment by alan-agius4** [comment] 2019-03-31 11:47
Duplicate of https://github.com/angular/angular-cli/issues/14033

**Closed by alan-agius4** 2019-03-31 11:47 UTC
