### ISSUE TITLE
HtmlInputElement holds all component tree memory leak

### ISSUE THREAD

**Issue by beniaminp** [angular/angular#40614] opened 2021-01-28 13:57 UTC
# 🐞 bug report

### Affected Package
`"@angular/core": "11.1.0"`

### Is this a regression?
Not sure, possibly.

### Description

HtmlInputElement is holding in heap memory the component if I interact with it.
If I do not interact with HtmlInputElement, the component that has the `<input type="text" />` inside it, is destoryed.
Tested in Chrome Incognito, without extensions.

## 🔬 Minimal Reproduction
StackBlitz project: https://stackblitz.com/github/beniaminp/angular-htmlinput-memory-leak
Github project: https://github.com/beniaminp/angular-htmlinput-memory-leak
In the project, I also added 2 MemoryHeapSnapshots at `/heap_snapshots` and 2 screenshots with the memory difference at `/screenshots`

Start the project and:

1. Insert text in input
2. Press button to switch to next component
3. Insert text in input
4. Press button again to switch to previous component
5. Repeat steps 1-4 as many time as you wish

## 🔥 Exception or Error
I attached images with heap memory.
First time I start the project:
![start_of_the_project](https://user-images.githubusercontent.com/12147873/106147791-f475c880-6180-11eb-87e3-0a3e3e7b1600.png)

After 6 iterations, FirstComponent
![first_component_10_iterations](https://user-images.githubusercontent.com/12147873/106147709-e031cb80-6180-11eb-911c-95f54907b629.png)

After 6 iterations, SecondComponent
![second_component_10_iterations](https://user-images.githubusercontent.com/12147873/106147900-15d6b480-6181-11eb-99bc-fc9966556c77.png)

## 🌍  Your Environment
"dependencies": {
    "@angular/animations": "11.1.0",
    "@angular/common": "11.1.0",
    "@angular/compiler": "11.1.0",
    "@angular/core": "11.1.0",
    "@angular/forms": "11.1.0",
    "@angular/platform-browser": "11.1.0",
    "@angular/platform-browser-dynamic": "11.1.0",
    "@angular/router": "11.1.0",
    "rxjs": "~6.5.4",
    "tslib": "^1.10.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "0.1101.1",
    "@angular/cli": "11.1.0",
    "@angular/compiler-cli": "11.1.0",
    "@angular/language-service": "11.1.0",
    "@types/node": "^12.11.1",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "^5.1.2",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.4.1",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~2.1.0",
    "karma-jasmine": "~3.0.1",
    "karma-jasmine-html-reporter": "^1.4.2",
    "protractor": "~5.4.3",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "4.1.3"
  }

**Comment by mmpadina** [comment] 2021-02-09 12:59
@petebacondarwin any updates on this issue? Thanks in advance!

**Comment by petebacondarwin** [comment] 2021-02-09 14:59
No update from me, I'm afraid. We need someone to triage this, to confirm the memory-leak and identify the source of the problem.

**Comment by VladRM** [comment] 2021-02-10 07:44
Hi everyone,

I would like to point out that this issue has a big impact on front-end performance and is a really big pain.
From what I can tell, it impacts a lot of applications - it's not some random edge case that only occurs in very rare or specific situations.

If this is correct, is there any way to prioritize the issue? It looks like it would benefit a lot of people.
If my take on it is not correct or I'm missing something, please let me know.

**Comment by gkalpak** [comment] 2021-02-10 16:04
FYI, I took a brief look and I couldn't identify what is causing the leak. The shortest retainer for the `FirstComponent` instance seems to go through a `ShadowRoot` object and then through some `InternalNode`s to the `Window`:

![first-component-snapshot](https://user-images.githubusercontent.com/8604205/107523676-a9ff3d80-6bbd-11eb-968d-15af341ef87e.png)

I wonder if this is a browser bug 🤔

FWIW, I tried with Angular v10.2.4 and v9.1.14 (in addition to v11.1.0) and the problem is still there.

**Comment by gkalpak** [comment] 2021-02-10 16:14
Actually, I was able to reproduce it without Angular, just using the HTML shown below:

```html
<button id="toggleButton">Toggle foo/bar</button>
<div id="outlet"></div>

<script>
  let cnt = 0;
  toggleButton.onclick = () => (++cnt % 2) ? new FooComponent() : new BarComponent();

  // Classes
  class BaseComponent {
    constructor(inputId) {
      this.input = Object.assign(document.createElement('input'), {
        comp: this,
        id: inputId,
        type: 'text',
      })

      outlet.innerHTML = `${inputId}: `;
      outlet.appendChild(this.input);
    }
  }

  class FooComponent extends BaseComponent {
    constructor() { super('fooInput'); }
  }

  class BarComponent extends BaseComponent {
    constructor() { super('barInput'); }
  }
</script>
```

As described by @beniaminp, as soon as you interact with the `<input>` element, it is retained (again via an `InternalNode` object attached to the document):

![bar-component-snapshot](https://user-images.githubusercontent.com/8604205/107536827-e38a7580-6bca-11eb-8522-d161aa777818.png)

##
Given the above, I am going to close this issue, since it doesn't seem to be caused by Angular.
@beniaminp, could you open an issue on the [Chromium bug-tracker][1]? (If you do, please post the link here for reference.)

[1]: https://bugs.chromium.org/p/chromium/issues

**Closed by gkalpak** 2021-02-10 16:14 UTC
Labels: comp: core, memory leak

**Comment by VladRM** [comment] 2021-02-10 17:03
@gkalpak, thank you for looking into this, I appreciate your help!

**Comment by beniaminp** [comment] 2021-02-11 07:16
@gkalpak , thank you! I really appreciate. I will open an issue on Chomium bug-tracker and I will be back with the link.
Thanks!

**Comment by beniaminp** [comment] 2021-02-17 11:09
Hi!
I created a bug report on chromium bug tracker.
Here is the link: 
https://bugs.chromium.org/p/chromium/issues/detail?id=1179199
Thanks!
