### ISSUE TITLE
build optimization problem in prod mode after project migration from NX 13 (Angular 13) to NX 14 (Angular 14)

### ISSUE THREAD

**Issue by eugenephilipov7** [angular/angular#47592] opened 2022-09-30 10:48 UTC
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

We have problem with build optimization in prod mode after project migration from NX 13 (Angular 13) to NX 14 (Angular 14).
In NX 13 we did not have issues.
While running npx nx run my-mf:serve, we don't have any problem.
Running npx nx run my-mf:serve:production, we have error in browser console and not working web app.
The same error in browser console after deployment of  build created with nx run my-mf:build --skip-nx-cache.
in browser console:
ERROR NullInjectorError: R3InjectorError[yu -> yu -> undefined -> undefined -> undefined]: 
  NullInjectorError: No provider for undefined!
    at au.get (537.167380f1e67f7b44.js:1:44933)
    at pu.get (537.167380f1e67f7b44.js:1:47603)
    at pu.get (537.167380f1e67f7b44.js:1:47603)
    at pu.get (537.167380f1e67f7b44.js:1:47603)
    at qm (537.167380f1e67f7b44.js:1:34022)
    at K (537.167380f1e67f7b44.js:1:34120)
    at Di (537.167380f1e67f7b44.js:1:34552)
    at Object.r [as factory] (537.167380f1e67f7b44.js:1:50241)
    at pu.hydrate (537.167380f1e67f7b44.js:1:48980)
    at pu.get (537.167380f1e67f7b44.js:1:47556) 

If change production.optimization to false in project.json, there is no error in browser console while running nx run my-mf:serve:production or nx run my-mf:build.

How to reproduce:
git clone https://github.com/eugenephilipov7/migration_problem
npm i
npx nx run my-mf:serve:production
http://localhost:4300/
in browser console (Edge,FF): 
ERROR NullInjectorError: R3InjectorError[yu -> yu -> undefined -> undefined -> undefined]:
npx nx run my-mf:serve
no error in browser console (Edge,FF) 

### Please provide a link to a minimal reproduction of the bug

https://github.com/eugenephilipov7/migration_problem

### Please provide the exception or error you saw

```true
ERROR NullInjectorError: R3InjectorError[yu -> yu -> undefined -> undefined -> undefined]: 
  NullInjectorError: No provider for undefined!
    at au.get (537.167380f1e67f7b44.js:1:44933)
    at pu.get (537.167380f1e67f7b44.js:1:47603)
    at pu.get (537.167380f1e67f7b44.js:1:47603)
    at pu.get (537.167380f1e67f7b44.js:1:47603)
    at qm (537.167380f1e67f7b44.js:1:34022)
    at K (537.167380f1e67f7b44.js:1:34120)
    at Di (537.167380f1e67f7b44.js:1:34552)
    at Object.r [as factory] (537.167380f1e67f7b44.js:1:50241)
    at pu.hydrate (537.167380f1e67f7b44.js:1:48980)
    at pu.get (537.167380f1e67f7b44.js:1:47556)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
@angular-devkit/architect          0.1402.3
@angular-devkit/build-angular      14.2.3
@angular-devkit/core               14.2.3
@angular-devkit/schematics         14.2.4
@angular/cdk                       14.2.2
@angular/cli                       14.2.4
@angular/material                  14.2.2
@angular/material-moment-adapter   14.2.2
@schematics/angular                14.2.4
ng-packagr                         14.2.1
rxjs                               6.6.7
typescript                         4.7.4
webpack                            5.74.0
node                               16.17.1
```

### Anything else?

Initially https://github.com/webpack/webpack/issues/16311.
Asked to reopen here.
Additional tools: NX,
    "@angular-architects/module-federation": "14.3.10",
    "@angular-architects/module-federation-tools": "14.3.10",

**Comment by JoostK** [comment] 2022-10-22 13:47
The project is using the Nx builder `@nrwl/angular:webpack-browser` with custom Webpack configuration, resulting in configuration that the Angular team does not support.

That said, the problem occurs in the factory for `RendererFactory2`, where its dependency `DomRendererFactory2` from `@angular/platform-browser` is `undefined`. This symbol is referenced using `fe.se`, with `fe` being the namespace import for module "5998", but there's two such modules in chunks `966.js` and `998.js`. The one from `966.js` is used, whereas `998.js` is the expected one.

The problem is avoided if you declare `@angular/platform-browser` as shared in your MF setup.

Closing as this is a configuration issue in an unsupported setup.

**Closed by JoostK** 2022-10-22 13:47 UTC
Labels: area: compiler
