### ISSUE TITLE
ng test spits binary data to terminal

### ISSUE THREAD

**Issue by erietz** [angular/angular#44675] opened 2022-01-10 17:45 UTC
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

Running `npx ng test` on a fresh project is broken and displays binary data to the terminal.

### Please provide a link to a minimal reproduction of the bug

https://github.com/erietz/angular-bug

### Please provide the exception or error you saw

```true
Binary text on terminal
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.1.2
Node: 16.13.1
Package Manager: npm 8.1.2
OS: linux x64

Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1301.2 (cli-only)
@angular-devkit/core         13.1.2 (cli-only)
@angular-devkit/schematics   13.1.2 (cli-only)
@schematics/angular          13.1.2 (cli-only)
```

**Comment by JoostK** [comment] 2022-01-10 17:49
Duplicate of angular/angular-cli#22462. Unfortunately there has been a rogue update to `color.js` which breaks tooling.

**Closed by JoostK** 2022-01-10 17:49 UTC
