### ISSUE TITLE
Binding to routerLinkActive.isActive in template throws exception.

### ISSUE THREAD

**Issue by paulussup** [angular/angular#13374] opened 2016-12-11 02:05 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

```
  <a routerLink="/team" routerLinkActive #rla="routerLinkActive"></a>
  <p *ngIf="rla.isActive">{{rla.isActive}}</p>
  <router-outlet></router-outlet>
```
Throws an exception because the QueryList isn't set when the isActive method is checked [here](https://github.com/angular/angular/blob/c9f58cf78cce420762c7f8c51172a10a497468ea/modules/%40angular/router/src/directives/router_link_active.ts#L140).

**Expected behavior**

Should be able to bind to isActive property

**Minimal reproduction of the problem with instructions**

Refer to above code snippet
**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.3.0

* **Browser:** [all]

 
* **Language:** [all]

**Comment by vicb** [comment] 2016-12-11 02:18
Duplicate of #13270

**Closed by vicb** 2016-12-11 02:18 UTC
