### ISSUE TITLE
[Service Worker] Offline mode reload doesn't work - Error 404

### ISSUE THREAD

**Issue by KGALLET** [angular/angular#22023] opened 2018-02-05 15:15 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When I refresh my app on a specific url route, (for example, "/dashboard") I directly get a 404 even if I'm online or offline.

## Expected behavior

I should get to the specific page.

## Minimal reproduction of the problem with instructions
`ng build --prod && http-server dist -p 4100`
-> Go on Chrome on 127.0.0.1:4100, everything works fine until I refresh on a specific url

## Environment

<pre><code>
Angular version: 5.0.0
"@angular/service-worker": "^5.2.2"

Browser:
- [X] Chrome (desktop) version 63.0.3239.132
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 6.11.0
- Platform:  Win10 x64

Others:
http-server: 0.11.1

</code></pre>

## Notes
I googled the problem and he appears to be something in link with the service worker routing. Everytime they speak about a `ngsw-manifest.json` file that I don't have on `dist` after the build.
Is there a way to done it properly in `ngsw-config.json` ?

Here is mine : 
```
{
  "index": "/index.html",
  "dataGroups": [{
    "name": "tasks-users-api",
    "urls": [
      "/collaborateurs",
      "/suivis/",
      "/webService/ordresMissions/*"
    ],
    "cacheConfig": {
      "strategy": "freshness",
      "maxSize": 100,
      "maxAge": "1h",
      "timeout": "10s"
    }
  }],
  "assetGroups": [{
    "name": "app",
    "installMode": "prefetch",
    "resources": {
      "files": [
        "/index.html"
      ],
      "versionedFiles": [
        "/*.bundle.css",
        "/*.bundle.js",
        "/*.chunk.js"
      ]
    }
  }, {
    "name": "assets",
    "installMode": "lazy",
    "updateMode": "prefetch",
    "resources": {
      "files": [
        "/assets/**"
      ]
    }
  }]
}
```

Thank's in advance

**Comment by SteffenJahr** [comment] 2018-02-05 20:27
The `ngsw-manifest.json` is a file that was used in an older version of the Angular Service Worker. This is no longer needed.

**Comment by KGALLET** [comment] 2018-02-06 10:56
So, that may be not a problem with routing... But that's strange that using `ng serve` I don't have the issue.
Maybe it's a problem with http-server ? 
Any thoughts about it ?

**Comment by Yerkon** [comment] 2018-02-06 11:37
> Maybe it's a problem with http-server ?

Maybe. [Server configuration](https://angular.io/guide/deployment#server-configuration) 

> If the app uses the Angular router, you must configure the server to return the application's host page (index.html) when asked for a file that it does not have.

**Comment by alxhub** [comment] 2018-02-06 23:31
`ng serve` doesn't have Service Worker enabled.

**Comment by gkalpak** [comment] 2018-03-20 13:46
`http-server` does not support rewriting requests to `index.html` (which is needed in order for the PathLocationStrategy to work). This means that if you land on a specific URL (other than `/` or `/index.html`) and the ServiceWorker isn't activated yet (because the SW knows to rewrite navigation requests to `/index.html`), then the request is passed through to the server (in this case `http-server`), which doesn't know what to return (it is looking for a `/dashboard` file).

Either go to `/` and then navigate to `/dashboard` (from within the app, so that routing happens client-side) or use a server that supports rewriting URLs to `/index.html`.

##
I am going to close this, since it sounds like everything works as intended.

**Closed by gkalpak** 2018-03-20 13:46 UTC
Labels: comp: service-worker, freq1: low, severity2: inconvenient, type: bug/fix
