### ISSUE TITLE
[QUESTION] About reactive forms validators, I'm totally confused!

### ISSUE THREAD

**Issue by dietergeerts** [angular/angular#14406] opened 2017-02-10 18:51 UTC
Hi,

I have a question about using validators with reactive forms: Where should we add them? Through the HTML? or through the FormControls models? I thought that the point of (or part of) reactive forms was that you specify all properties, so also validators, on the model in JS/TS, like we can now give them while creating a FormControl or FormGroup, BUT all directives which put validators on the control are also included in the reactive forms.

The point is that it's really confusing and it looks to me like the current status of the reactive forms is a mix between the two forms of forms (pun intended). Those validator-attribute directives should be gone, and the validators we give the FormControl/FormGroup should be used to add the element attributes instead.

I started to extend the FormControl class to add extra info to my model, and added extra directives to build out the tag it's placed on with all the attributes, so the html is somewhat auto-generated.

So a clear explanation would be very appreciated and helpful, before going further on this adventure and to be able to work out a correct workflow. thx.

**Comment by DzmitryShylovich** [comment] 2017-02-10 18:59
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by kara** [comment] 2017-02-11 00:35
@dietergeerts The short answer: the best practice for reactive forms is to add validators in the component class (e.g. the `FormGroup` or `FormControl`). This is consistent with the module's paradigm, but more importantly, will help prevent 'changed after checked' errors that sometimes happen when you mix. Currently we do allow validator directives to be used with reactive forms for flexibility, but we do have [longer term plans](https://github.com/angular/angular/issues/9121) to add parallel attributes based on validators as well that may make that unnecessary. 

Given that this is not a bug or a feature request, closing the issue.

**Closed by kara** 2017-02-11 00:35 UTC
