### ISSUE TITLE
Upgrade 9 => 10 ERROR in Cannot read property 'flags' of undefined

### ISSUE THREAD

**Issue by richardsengers** [angular/angular#37731] opened 2020-06-25 10:39 UTC
# 🐞 bug report

### Affected Package
Unknown，Just upgrade form 9.1.6 to 10.0.0

### Is this a regression?
Yes, the previous version in which this bug was not present was: 9.1.6

### Description

ERROR in Cannot read property 'flags' of undefined

## 🔥 Exception or Error
<pre><code>
> ng serve

chunk {main} main.js, main.js.map (main) 2.07 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 674 bytes [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.15 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 1.18 MB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 341 kB [initial] [rendered]
Date: 2020-06-25T10:32:48.714Z - Hash: c0617ed7df66b5217380 - Time: 5297ms

ERROR in Cannot read property 'flags' of undefined
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 10.0.0
Node: 12.15.0
OS: win32 x64

Angular: 10.0.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, material, platform-browser
... platform-browser-dynamic, router, service-worker
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1000.0
@angular-devkit/build-angular      0.1000.0
@angular-devkit/build-ng-packagr   0.1000.0
@angular-devkit/build-optimizer    0.1000.0
@angular-devkit/build-webpack      0.1000.0
@angular-devkit/core               10.0.0
@angular-devkit/schematics         10.0.0
@ngtools/webpack                   10.0.0
@schematics/angular                10.0.0
@schematics/update                 0.1000.0
ng-packagr                         10.0.0
rxjs                               6.5.5
typescript                         3.9.5
webpack                            4.43.0

</code></pre>

**Anything else relevant?**
It looks like the bug mentioned here https://github.com/angular/angular/issues/36993 is back

**Comment by JoostK** [comment] 2020-06-25 10:55
Uh oh. This was diagnosed in depth in #36993 and the root causes should have been resolved, so it's unexpected that this is showing up again. Could have a different cause, though, so we'd need some more info.

Does this happen using just `ng new test-app` and then building the default app?

**Comment by richardsengers** [comment] 2020-06-25 11:49
It doesn't happen with a new default app.
I will add my packages one by one to see if maybe a package is causing this error

**Comment by richardsengers** [comment] 2020-06-25 12:49
There is something wrong with my dependencies

```
"devDependencies": {
    "@angular-builders/custom-webpack": "^9.2.0",
    "@angular-devkit/build-angular": "~0.1000.0",
    "@angular-devkit/build-ng-packagr": "~0.1000.0",
    "@angular/cli": "^10.0.0",
    "@angular/compiler-cli": "~10.0.0",
    "@angular/language-service": "~10.0.0",
    "@types/applicationinsights-js": "^1.0.9",
    "@types/jasmine": "~3.5.11",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^14.0.14",
    "codelyzer": "^6.0.0-next.1",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~5.0.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~3.3.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "ng-packagr": "^10.0.0",
    "npm-run-all": "^4.1.5",
    "pa11y-ci": "^2.3.0",
    "pa11y-reporter-html": "^2.0.0",
    "protractor": "~7.0.0",
    "raw-loader": "^4.0.1",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "tslint-lines-between-class-members": "^1.3.6",
    "typescript": "~3.9.5"
  }
```

I'm still narrowing it down, but if its a dependency, is it then still an Angular bug or should the dependencie be updated?

**Comment by JoostK** [comment] 2020-06-25 14:17
Thanks for the additional info. I noticed also that `@angular-builders/custom-webpack` has an explicit dependency on Angular devkit `>=0.900.0 < 0.1000.0`, not just a peer dependency, so you may actually have an incompatible set of dependencies.

**Comment by jnizet** [comment] 2020-06-25 15:51
I had the same problem, indeed caused by custom-webpack, and using the version 10.0.0-beta.0 fixes the issue for me.

**Comment by JoostK** [comment] 2020-06-25 19:05
I'll be closing this as the issue originates in `@angular-builders/custom-webpack`. Thanks @richardsengers for finding the root cause so quickly, that's been really helpful!

**Closed by JoostK** 2020-06-25 19:05 UTC
Labels: comp: compiler, state: Needs repro
