### ISSUE TITLE
ng build --prod allows use of private functions from templates within structural directives

### ISSUE THREAD

**Issue by adjcmh** [angular/angular#26460] opened 2018-10-15 20:35 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
If you write a template that uses a private function inside of a structural directive, ng build --prod successfully compiles.  E.g. when foo is a private function on the corresponding component to the following template, the following code fails on line 2:

<pre>
&lt;div *ngIf="true" (click)=foo()/&gt;
&lt;div (click)=foo()/&gt;
</pre>

## Expected behavior

The build should fail on line 1.

## Minimal reproduction of the problem with instructions

Plunkr example: https://plnkr.co/edit/8cH7g9fdUadFXrvW
Downloadable zip: http://misc.quintillus.warpmail.net/bug-test.zip

To reproduce, after downloading/extracting the zip, run:
npm install
ng build --prod

## What is the motivation / use case for changing the behavior?

We encountered this issue after writing some code within structural directives, where that code called private functions.  After removing those structural directives, our build started failing.  It would have been preferable to have known about the issue when it first occurred.

## Environment

<pre><code>
Angular version: 7.0.0-rc0, and also verified on 5.2.6

Browser: not applicable
 
For Tooling issues:
- Node version: v10.7.0 (with Angular 5), 9.7.1 (with Angular 7)  
- Platform: Mac (not tested elsewhere yet) 

Others:

</code></pre>

**Comment by alexzuza** [comment] 2018-10-16 04:05
Angular doesn't typecheck embedded views by default since the old view compiler used to use an `any` type for the context in any embedded view. 

I think you want to enable `fullTemplateTypeCheck` option which [will tell Angular](https://github.com/angular/angular/blob/1c9b06504b45280a30df937b99bc26256732b55e/packages/compiler/src/view_compiler/type_check_compiler.ts#L216) to check bindings in embedded view:

For example, in angular/cli **src/ts.config.app.json**
```
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc/app",
    "types": []
  },
  "exclude": [
    "test.ts",
    "**/*.spec.ts"
  ],
  "angularCompilerOptions": {
    "fullTemplateTypeCheck": true
  }
}
```

**Comment by alxhub** [comment] 2018-10-25 22:31
Even that will not type-check the embedded view. This is an issue with the way `fullTemplateTypeCheck` is implemented.

**Comment by trotyl** [comment] 2018-11-17 16:11
Duplicate of https://github.com/angular/angular/issues/15801

**Comment by JoostK** [comment] 2021-09-30 20:48
Closing as obsolete; Ivy checks embedded views (assuming that `fullTemplateTypeCheck` or `strictTemplates` is enabled).

**Closed by JoostK** 2021-09-30 20:48 UTC
Labels: type: bug/fix, freq3: high, fixed by Ivy, comp: compiler, state: confirmed, engine: ve, triage #1, P5
