### ISSUE TITLE
ActivatedRoute queryParamMap is updated before paramMap when navigating

### ISSUE THREAD

**Issue by theodorejb** [angular/angular#26764] opened 2018-10-25 20:15 UTC
## I'm submitting a...
- [x] Bug report

## Current behavior
I'm using `combineLatest` to subscribe to both the route paramMap and queryParamMap so that I can use values from both in an API request.

However, this doesn't work as expected when navigating to the same component with different params. Instead of the observable emitting one new value with the new paramMap and queryParamMap, it emits two values. The first has the old paramMap and new queryParamMap, and the second has both the new paramMap and new queryParamMap.

## Expected behavior
When navigating to the component with different params, the observable should emit a single value with the new params and query params.

## Minimal reproduction of the problem with instructions
[https://stackblitz.com/edit/angular-route-param-issue](https://stackblitz.com/edit/angular-route-param-issue?file=src%2Fapp%2Fhello.component.ts)

In the StackBlitz example, click the link in the component and note how multiple route param values are being unexpectedly emitted from the observable.

## What is the motivation / use case for changing the behavior?
I need a way to subscribe to the new route params and query params (and sometimes the fragment too), so I can use values from more than one of these observables in a single API request when the user navigates.

## Environment
Angular version: 7.0.1
RxJS version: 6.3.3

Browser:
- [x] Chrome (desktop) version 70
- [x] Firefox version 63
- [x] IE version 11
- [x] Edge version 18

**Comment by michaeljota** [comment] 2018-10-25 23:38
I think you want to use [merge](https://www.learnrxjs.io/operators/combination/merge.html) if you want just one value, as [combineLatest](https://www.learnrxjs.io/operators/combination/combinelatest.html) works as expected.

**Comment by theodorejb** [comment] 2018-10-26 00:02
@michaeljota Thanks for the reply. Unfortunately `merge` doesn't do what I need. It still results in my callback being invoked twice: first with the queryParamMap and second with the paramMap. I need to get the latest paramMap and queryParamMap at the same time in order to use data from both in an API request.

It seems like the issue is that Angular updates query params before route params instead of at the same time. This causes `combineLatest` to emit once with the new query params but old route params, and again with the expected value for both.

**Comment by alexkunin** [comment] 2018-10-26 09:35
I agree with @michaeljota, combineLatest works as expected -- you have two separate (though correlated) sources of events, and you basically do something if either changes.

Not sure if the following is the perfect solution, but it seems to do what you want (don't forget to import withLatestFrom from rxjs/operators):

    this.route.paramMap.pipe(
        withLatestFrom(this.route.queryParamMap)
    ).subscribe(
        // the rest is the same

So, instead of subscribing to every change in either stream of events, you subscribe to one of them and just peek latest value from the other one. This have downside, though: if query parameter changes and route does not change, you'll skip that event. Not sure if this situation possible.

Also, if you're sure that queryParamMap and paramMap always emit 1-to-1 events, you can zip them (i.e. rxjs/zip), but I would not rely on that.

Finally, I think you have a problem because you're mixing state saving with reactive streams (not that you have choice here...). You could do combineLatest as you do now, then produce some combined value of name and age, then filter it through distinctUntilChanged, and only after that update properties of your component.

Hope that helps.

**Comment by theodorejb** [comment] 2018-10-26 14:17
@alexkunin Thank you for the detailed reply.

> I agree with @michaeljota, combineLatest works as expected -- you have two separate (though correlated) sources of events, and you basically do something if either changes.

Correct. The problem is not with `combineLatest`, but with Angular updating the `queryParamMap` observable before `paramMap`. I edited the title to make this clearer.

> Not sure if the following is the perfect solution, but it seems to do what you want (don't forget to import withLatestFrom from rxjs/operators):
>...This have downside, though: if query parameter changes and route does not change, you'll skip that event. Not sure if this situation possible.

In my real-world app, it is possible for query params to change independent of route params, so this solution doesn't work. This also prevents me from using the RxJS `zip` function.

> You could do combineLatest as you do now, then produce some combined value of name and age, then filter it through distinctUntilChanged, and only after that update properties of your component.

This wouldn't filter out anything, since the combined name and age is distinct for both values emitted from `combineLatest` (in the first value the age query param changed, and in the second the name param changed).

It seems wrong that `paramMap`, `queryParamMap`, and `fragment` are separate observables, since all three can change simultaneously when a user navigates. Surely my need to get updated values from more than one of these observables when a user navigates isn't unique!

**Comment by michaeljota** [comment] 2018-10-26 15:42
> It seems wrong that paramMap, queryParamMap, and fragment are separate observables, since all three can change simultaneously when a user navigates.

I don't what are you expectations about this, but I don't see how this could be a problem. The all the three of the observables are emitting as expected, and the pipe operators are working as expected. Maybe if you can elaborate better of your expectations, this would fit then in a feature request, but is definitely not a bug.

**Comment by michaeljota** [comment] 2018-10-26 15:49
> I need a way to subscribe to the new route params and query params (and sometimes the fragment too), so I can get all the updated values together when a user navigates.

Are you expecting a single source observable that emits only one object that contains all the route params, query params and fragments? If it is so, there are plenty of ways of doing it by using `rxjs` constructors and pipes operators. 

But it wouldn't expect this to be considered neither a bug report or a feature request as this looks like a very specific behavior.

**Comment by theodorejb** [comment] 2018-10-26 16:01
> Are you expecting a single source observable that emits only one object that contains all the route params, query params and fragments? If it is so, there are plenty of ways of doing it by using `rxjs` constructors and pipes operators.

Yes, that's exactly what I need. What constructors and pipe operators should I use to do this?

**Comment by michaeljota** [comment] 2018-10-26 16:32
@theodorejb

First you would need to look for a strategy to merge the observables into a single source. Every option here have it's ups and downs, so you would need to see what fits you.

- [combineLatest](https://rxjs-dev.firebaseapp.com/api/index/function/combineLatest)
- [merge](https://rxjs-dev.firebaseapp.com/api/index/function/merge)
- [withLatestFrom](https://rxjs-dev.firebaseapp.com/api/operators/withLatestFrom)
- [switchMap](https://rxjs-dev.firebaseapp.com/api/operators/switchMap)

After you got yourself a single source observable, you should then use [`map`](https://rxjs-dev.firebaseapp.com/api/operators/map) pipe operator to create a single object.

By using `combineLatest`, you get the array of values and then you can return a single object by using the spread operator. However, the "_issue_" you were having, would remain, as both of the observables would emit independently, but I think you could use some operators as [`debounceTime`](https://rxjs-dev.firebaseapp.com/api/operators/debounceTime) to control the multiple emits 

If you want to emit just once for all of them, you would need to use `withLatestFrom` and decide what is the "single source of true", meaning, the observable that would always change last, and appends the observable that change first. With this the first to change will have the desired value when the latter emits.

**Comment by theodorejb** [comment] 2018-10-26 19:41
@michaeljota and @alexkunin

Thank you for the helpful responses. I was indeed able to work around the issue by piping the `combineLatest` observable through `debounceTime(0)`. However, this feels like an ugly hack to ignore the first emitted value(s) which don't have the updated paramMap and fragment. I'm also worried that a longer `debouceTime` interval might be required for slower browsers.

Is `combineLatest` with `debounceTime(someDelay)` considered the idiomatic Angular way to subscribe to changes to a route's params, query params, and fragment? If so, I think at the very least this should be documented in the official [Routing & Navigation guide](https://angular.io/guide/router), so that other developers won't be tripped up by the same issue.

The current API just feels wrong to me, though. I agree with @alexkunin that it would be ideal to have an observable built into `ActivatedRoute` that emits a single object with the latest params, query params, and fragment when the user navigates.

**Comment by michaeljota** [comment] 2018-10-26 20:04
I agree this is a little big strange, but I think this is more powerful than a single source. 

> Is `combineLatest` with `debounceTime(someDelay)` considered the idiomatic Angular way to subscribe to changes to a route's params, query params, and fragment?

This is not part of Angular, is just plain old `rxjs` here. But, yes, if you want to merge multiple sources with `rxjs` (of anything) this is the way. Again, not an _Angular way_. Angular just gives you the power to do what you want to do, in this case, merging this. 


Really happy to see this worked. I'm glad to help you.

**Comment by jasonaden** [comment] 2018-11-27 23:49
Closing as this appears resolved. Thanks @michaeljota and @alexkunin for your help on this.

I also agree, there is probably a *feature request* that could be made to publish something better. Maybe something like @alexkunin's suggestion, maybe something else. If you would like to submit a feature request and pose some possible ways this could be constructed, I'll take a look.

Closing this issue as resolved.

**Closed by jasonaden** 2018-11-27 23:49 UTC
Labels: comp: router

**Comment by jared-christensen** [comment] 2019-07-19 15:04
I'm struggling with this too. I don't feel like it should have been closed.

**Comment by jinsts** [comment] 2019-07-23 05:59
This issue is still there in Angular 8. I also feel this shouldn't have been closed without a proper solution instead of workaround.
I think the problem is, change in query params emits before change in router's params emits. Ideally it should emit change in route params first and then query params. Please correct me if I'm wrong.

**Comment by michaeljota** [comment] 2019-07-23 13:24
I don't think we should expect an consistent behavior from this. Both are observables and both are being given to us in a way we need to shape them as we need. As I see it now, through it may seem like a bug, is a feature an we should leverage on rxjs to achieve exactly what we want.
