### ISSUE TITLE
Allow embedding a link to original source files into the generated messages

### ISSUE THREAD

**Issue by mprobst** [angular/angular#12513] opened 2016-10-25 11:51 UTC
We should generate something like:

``` xml
<msg id="..." meaning="..."><source>path/to/file.ts:123</source>This is a message</msg>
```

`extractor.ts` should take a callback to generated the exact file path from e.g. a `ts.SourceFile` object or similar, so users can adjust the path to their particular repository format.

**Comment by gnoack** [comment] 2016-10-25 12:22
You can also specify line number ranges like `path/to/file:123,125`.  (yes, comma-separated)
Line numbers are one-based (as in grep).

**Comment by vicb** [comment] 2016-10-25 21:46
@gnoack could you please confirm that we can list multiple `<source>`s ?

**Comment by gnoack** [comment] 2016-10-26 10:14
Yes, multiple `<source>` tags are supported.

**Comment by ocombe** [comment] 2017-03-13 13:48
Isn't this a duplicate of #14190 ?

**Comment by gnoack** [comment] 2017-03-16 10:48
Almost.  The other bug forgets to mention that we also would like line numbers for each message.

**Comment by ocombe** [comment] 2017-03-16 10:50
Ok, the feature request contains line numbers anyway: https://github.com/angular/angular/pull/14705

**Comment by gnoack** [comment] 2017-03-16 11:12
It's almost the same, yes.  The line number format that we need is ":123,125" where 123 is the first and 125 the last line where the message appears, 1-based indexing.  I'm sorry to notice this so late, and I hope that our XMB-reading tools are somewhat compatible in that respect. :-/

**Comment by ocombe** [comment] 2017-03-20 08:54
This is the format that we're adding (":123,125").

**Comment by gnoack** [comment] 2017-03-20 14:13
Awesome, thanks!

**Comment by ocombe** [comment] 2017-06-27 13:42
This has been fixed and merged in master

**Closed by ocombe** 2017-06-27 13:42 UTC
Labels: comp: i18n, freq1: low, type: feature
