### ISSUE TITLE
titlecase pipe : Converting 'COVID-19 News' to  'Covid-19 News' 

### ISSUE THREAD

**Issue by Manishemblebi** [angular/angular#41420] opened 2021-04-01 22:03 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...

## 🔬 Minimal Reproduction

 https://stackblitz.com/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by cacothi** [comment] 2021-04-02 00:06
The right name is COVID, not Covid as it's a technical name

**Comment by indraraj26** [comment] 2021-04-02 03:34
I think it should be consider as bug this is not working as text-transform: capitalize. It should not lower the rest character.

**Comment by Airblader** [comment] 2021-04-02 05:25
"Capitalize" isn't the same as "title case". As written in the docs, title case is defined as uppercasing the first letter of each word and lowercasing all others. There is no specific knowledge that some words should or shouldn't be treated that way: for every word you apply it to, that is what happens (and should happen).

This is working as intended.

**Comment by petebacondarwin** [comment] 2021-04-02 06:30
This is interesting... initially I thought this issue was a mistake but having looked around I see that there can be multiple subtle rules about "title" capitalization. For example see https://capitalizemytitle.com/#capitalizationrules.

So I think that the current `title` pipe could really be considered a "upper first letter" converter. And in fact this is exactly how it is described in the [docs](https://angular.io/api/common/TitleCasePipe):

> Capitalizes the first letter of each word and transforms the rest of the word to lower case. 

Changing its behaviour now would be a breaking change.

Since it is such a simple pipe to implement differently, as shown by @indraraj26, I would rather not change it in the core framework but allow others to provide other more sophisticated alternative approaches in 3rd party libraries. One approach would be to just wrap one of the many title case libraries on npm into a pipe:

* https://github.com/ianstormtaylor/to-title-case
* https://github.com/idimetrix/text-case/tree/master/packages/title-case
* https://github.com/gouch/to-title-case
* https://github.com/words/ap-style-title-case
* https://github.com/rvagg/titlecase

**Comment by aryanisml** [comment] 2021-04-07 10:36
I feel this is not bug, in doc its clearly mention  'Transforms text to title case. Capitalizes the first letter of each word and transforms the rest of the word to lower case'  - https://angular.io/api/common/TitleCasePipe .

'COVID-19 News' become 'Covid-19 News' . This the correct behavior.

**Comment by petebacondarwin** [comment] 2021-04-07 15:23
Yes, I agree it is definitely not a bug. Moreover, it is a feature request that we are very unlikely (never) going to implement. It is easy to implement it in your own projects. So I am going to close this. Thanks for the input everyone.

**Closed by petebacondarwin** 2021-04-07 15:23 UTC
Labels: comp: common, feature
