### ISSUE TITLE
[Bug]  angular/elements: Failed to run server side rendering, ReferenceError: Element is not defined

### ISSUE THREAD

**Issue by joestartreck** [angular/angular#27732] opened 2018-12-18 16:56 UTC
# 🐞 Bug 

### Affected Package
"@angular/elements": "^7.1.3",

## I'm submitting 
[] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:

### Current behavior
We would like to create webcomponents by using @angular/elements and run server side rendering. However now it is not possible due to the error "ReferenceError: Element is not defined"

## 🔬 Minimal Reproduction

1. Git clone https://github.com/joestartreck/universal-starter
2. yarn install && npm run build:ssr && npm run serve:ssr

## 🔥 Exception or Error
<pre><code>
/sandbox/universal-starter/node_modules/@angular/elements/bundles/elements.umd.js:72
    var elProto = Element.prototype;
                  ^
ReferenceError: Element is not defined
    at /sandbox/universal-starter/node_modules/@angular/elements/bundles/elements.umd.js:72:19
    at extendStatics (/sandbox/universal-starter/node_modules/@angular/elements/bundles/elements.umd.js:8:68)
    at Object.<anonymous> (/sandbox/universal-starter/node_modules/@angular/elements/bundles/elements.umd.js:11:2)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 7.1.3
Node: 10.13.0
OS: linux x64
Angular: 7.1.3
... animations, cli, common, compiler, compiler-cli, core
... elements, forms, http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.11.3
@angular-devkit/build-angular     0.11.3
@angular-devkit/build-optimizer   0.11.3
@angular-devkit/build-webpack     0.11.3
@angular-devkit/core              7.1.3
@angular-devkit/schematics        7.1.3
@ngtools/webpack                  7.1.3
@schematics/angular               7.1.3
@schematics/update                0.11.3
rxjs                              6.2.2
typescript                        3.1.6
webpack                           4.23.1</code></pre>

**Comment by trotyl** [comment] 2018-12-19 03:00
Duplicate of https://github.com/angular/angular/issues/24345

---

If it's a regression please provide concrete minimal reproduction.

**Comment by trotyl** [comment] 2018-12-19 05:37
Relates to https://github.com/angular/angular/issues/24345, this is actually an edge case hasn't been fixed by https://github.com/angular/angular/pull/24116, because `Element` is used eagerly in the top-module-level code. 

To fix it either `@angular/elements` should postpone the reference to `Element` in the real function call, or `@angular/platform-server` should lift the patch eagerly rather than in DI init. (The latter one would still be tricky as user need to ensure the import order)

**Comment by joestartreck** [comment] 2018-12-19 10:47
Hi @trotyl 

Does it exist any way to make this working under angular  7.1.3?

**Comment by trotyl** [comment] 2018-12-19 11:41
> Does it exist any way to make https://github.com/joestartreck/universal-starter working now ?

Manually apply `Object.assign(global, domino.impl);` eagerly.

**Comment by vikerman** [comment] 2018-12-26 21:11
Hi - Angular Elements is not yet officially supported on platform-server.

The above error is because of 'use strict' emitted by TypeScript and Domino HTMLElement constructor being marked read-only.

This will require a patch to Domino to fix properly.

**Closed** 2018-12-27 05:46 UTC
Labels: comp: elements, comp: server, effort2: days, freq1: low, severity3: broken, type: feature
