### ISSUE TITLE
Angular allow inncorect attribute names

### ISSUE THREAD

**Issue by kbrilla** [angular/angular#56571] opened 2024-06-24 11:52 UTC
### Which @angular/* package(s) are the source of the bug?

compiler

### Is this a regression?

Yes

### Description

While refactoring some code to signal we made small typo which resulted in such code:
```
 ([disabled]="loading)"
```
instead of
```
[disabled]="loading()"
```
This results in runtime error.

It would be great if this was catched in compile time.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-yvq4ry?file=src%2Fmain.ts

### Please provide the exception or error you saw

```
chunk-MVMP4A3Y.js?v=9665549d:8207 ERROR 
InvalidCharacterError: Failed to execute 'setAttribute' on 'Element': '([disabled]' is not a valid attribute name.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```
Angular CLI: 18.0.5
Node: 18.20.3
Package Manager: npm 10.2.3
OS: linux x64

Angular: 18.0.4
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1800.5
@angular-devkit/build-angular   18.0.5
@angular-devkit/core            18.0.5
@angular-devkit/schematics      18.0.5
@angular/cli                    18.0.5
@schematics/angular             18.0.5
rxjs                            7.8.1
typescript                      5.4.5
zone.js                         0.14.7
```

**Comment by JeanMeche** [comment] 2024-06-24 11:59
We could check this but I would expect that the extended diagnostic introduced by #56295 to take care of that.

**Comment by JoostK** [comment] 2024-06-24 12:22
Duplicate of https://github.com/angular/angular/issues/39781

**Closed** 2024-06-24 12:22 UTC

**Comment by kbrilla** [comment] 2024-06-24 12:25
> Duplicate of #39781

original posts are form 2020 so I'm looking forward to see if https://github.com/angular/angular/pull/56295 will fix it
