### ISSUE TITLE
Exception: Call to Node module failed with error: TypeError: Cannot read property 'SelectorMatcher' of undefined

### ISSUE THREAD

**Issue by stanbe** [angular/angular#12431] opened 2016-10-21 09:32 UTC
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
With the recent update to 2.1.1 I am getting an error when bundling the packages with webpack.

Exception: Call to Node module failed with error: TypeError: Cannot read property 'SelectorMatcher' of undefined at Object. (C:\Users\john\...\node_modules\angular2-platform-node__private_imports__.js:21:54)

**Expected behavior**
I don't expect an error when bundling the packages.

**Minimal reproduction of the problem with instructions**

 It is reproducable with the following dependencies (package.json) and the .NET Core Angular2 starter template (can be downloaded here: https://visualstudiogallery.msdn.microsoft.com/31a3eab5-e62b-4030-9226-b5e4c9e1ffb5).

{
  "name": "Angular2",
  "version": "0.1.0",
  "dependencies": {
    "@angular/common": "^2.0.0",
    "@angular/compiler": "^2.0.0",
    "@angular/core": "^2.0.0",
    "@angular/forms": "^2.0.0",
    "@angular/http": "^2.0.0",
    "@angular/platform-browser": "^2.0.0",
    "@angular/platform-browser-dynamic": "^2.0.0",
    "@angular/platform-server": "^2.0.0",
    "@angular/router": "^3.0.0",
    "@types/node": "^6.0.38",
    "angular2-platform-node": "~2.0.10",
    "angular2-universal": "~2.0.10",
    "angular2-universal-polyfills": "~2.0.10",
    "aspnet-prerendering": "^1.0.6",
    "aspnet-webpack": "^1.0.11",
    "bootstrap": "^3.3.7",
    "css": "^2.2.1",
    "css-loader": "^0.25.0",
    "es6-shim": "^0.35.1",
    "es7-reflect-metadata": "^1.4.0",
    "expose-loader": "^0.7.1",
    "extract-text-webpack-plugin": "^1.0.1",
    "file-loader": "^0.9.0",
    "isomorphic-fetch": "^2.2.1",
    "jquery": "^2.2.1",
    "preboot": "^4.5.2",
    "raw-loader": "^0.5.1",
    "rxjs": "5.0.0-beta.12",
    "style-loader": "^0.13.0",
    "to-string-loader": "^1.1.5",
    "ts-loader": "^0.8.2",
    "typescript": "^2.0.0",
    "url-loader": "^0.5.7",
    "webpack": "^1.12.14",
    "webpack-externals-plugin": "^1.0.0",
    "webpack-hot-middleware": "^2.10.0",
    "webpack-merge": "^0.14.1",
    "webpack-node-externals": "^1.5.4",
    "zone.js": "^0.6.21"
  },
  "devDependencies": {
    "@types/jasmine": "^2.5.35",
    "copy-webpack-plugin": "^0.3.3",
    "css-loader": "^0.23.0",
    "exports-loader": "0.6.2",
    "expose-loader": "^0.7.1",
    "file-loader": "^0.8.4",
    "html-webpack-plugin": "^1.7.0",
    "http-server": "^0.8.5",
    "imports-loader": "^0.6.4",
    "istanbul-instrumenter-loader": "^0.1.3",
    "json-loader": "^0.5.3",
    "karma": "^0.13.15",
    "karma-chrome-launcher": "^0.2.1",
    "karma-coverage": "^0.5.3",
    "karma-jasmine": "^0.3.6",
    "karma-phantomjs-launcher": "^0.2.1",
    "karma-sourcemap-loader": "^0.3.6",
    "karma-webpack": "1.7.0",
    "phantomjs": "^1.9.18",
    "phantomjs-polyfill": "0.0.1",
    "protractor": "^3.0.0",
    "raw-loader": "0.5.1",
    "reflect-metadata": "0.1.2",
    "remap-istanbul": "^0.5.1",
    "rimraf": "^2.4.4",
    "style-loader": "^0.13.0",
    "ts-helper": "0.0.1",
    "ts-loader": "^0.7.2",
    "tsconfig-lint": "^0.4.3",
    "tslint": "^3.2.0",
    "tslint-loader": "^2.1.0",
    "typedoc": "^0.3.12",
    "typescript": "^1.7.3",
    "typings": "^1.4.0",
    "url-loader": "^0.5.6",
    "webpack": "^1.12.9",
    "webpack-dev-server": "^1.12.1",
    "webpack-md5-hash": "0.0.4"
  }
}

**Comment by DzmitryShylovich** [comment] 2016-10-21 09:34
Can u pls provide a minimal repository with reproduction?

**Comment by stanbe** [comment] 2016-10-21 09:48
Sure: https://github.com/stanbe/Angular2Issue

Just try to start it in Visual Studio 2015 (Prerequisites:  VS2015 Update 3, .NET Core 1.0.1, Typescript 2.0 for Visual Studio)

**Comment by Hongbo-Miao** [comment] 2016-10-21 22:12
Got same error, it is due to **@angular/compiler** 2.1.1, works well in 2.1.0

**Comment by MarkPieszak** [comment] 2016-10-24 23:23
This issue is from Universal (see the Universal issue [here #606](https://github.com/angular/universal/issues/606)) because we were previously using:

 `SelectorMatcher` & `CssSelector` from `__compiler_private__`
 Also `ViewUtils` from `__core_private__` (which looks like it got renamed to **`view_utils`**?

I have a work in progress [PR here](https://github.com/angular/universal/pull/607) where I'm selectively taking either the new public values or importing the older private ones (for backwards compatibility).

Take a look and let me know what you think. @IgorMinar

**Comment by tbosch** [comment] 2016-10-26 17:30
Closing as this is a bug in unversal.

**Closed by tbosch** 2016-10-26 17:30 UTC
Labels: comp: core & compiler
