### ISSUE TITLE
dynamic object key in html

### ISSUE THREAD

**Issue by kernyden** [angular/angular#37906] opened 2020-07-03 12:17 UTC
Is there a way or plans to make smth like this:
```Javascript
<app-some-component
     [perms]="{
         [customEnums.create]: (([
              'ADMIN', 
              'MANAGER'
         ]   | hasPermissions: 
                  project.name 
             | async
         )
    }">
   Look at me
</app-some-component>
```

Seems like now it itsn't..

**Comment by pkozlowski-opensource** [comment] 2020-07-03 12:23
This is a duplicate of #13855 - generally speaking we want to work towards alleging Angular expression syntax with JS expressions syntax but for now there are still some discrepancies (you've just bumped into one of them).

Closing as a duplicate of #13855

**Closed by pkozlowski-opensource** 2020-07-03 12:23 UTC

**Comment by kernyden** [comment] 2020-07-03 13:58
Oh, thx for supplying.
