### ISSUE TITLE
When using flex-layout QueryList empty on ngAfterContentInit

### ISSUE THREAD

**Issue by phmello** [angular/angular#14072] opened 2017-01-24 08:26 UTC
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When using flex-layout inside a component the ContentChildren QueryList is empty on ngAfterContentInit

**Expected behavior**
The QueryLit should contain the elements inside it's content

**Minimal reproduction of the problem with instructions**
https://plnkr.co/edit/8E3PGNJW7s9als2gCAuQ?p=preview

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by dejour** [comment] 2017-01-24 08:55
I think ContentChildren means direct content children.

**Comment by DzmitryShylovich** [comment] 2017-01-24 08:59
https://plnkr.co/edit/G2RlcU9vMgkNVoTRSfUO?p=preview

**Comment by phmello** [comment] 2017-01-24 09:22
thanks @DzmitryShylovich !!!!

**Comment by DzmitryShylovich** [comment] 2017-01-31 23:40
@phmello can you close this as it works as intended? thx

**Closed** 2017-02-01 06:52 UTC
