### ISSUE TITLE
Root named outlet cannot be target in nested named outlet 

### ISSUE THREAD

**Issue by sashagrunge** [angular/angular#23791] opened 2018-05-09 10:13 UTC
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[x] Other... Please describe:
</code></pre>

## Current behavior

app-routing.module.ts

`{ path: 'product', loadChildren: './product#ProductModule' },`

product-routing.module.ts

```
{ path: '',
    component: ProductPageComponent,
    children: [
      {
        path: 'discount',
        children: [
          { path: '', loadChildren: './product-discount-view#ProductDiscountViewModule' },
          { path: 'details', component: ProductDiscountDetailsComponent, outlet: 'panel' },
        ]
      }
}
```

app.component.html

```
<router-outlet></router-outlet>
<router-outlet name="panel"></router-outlet>
```

product-page.component.html

```
<router-outlet></router-outlet>
```
Cannot display ProductDiscountDetailsComponent in  <router-outlet name="panel"> by 
this.router.navigate([{outlets: {panel: 'details'}}], {relativeTo: this.route.parent});

Customers link doesn't work.

## Expected behavior

Can target to root level named outlet from child route.

## Minimal reproduction of the problem with instructions

A quick example:
https://stackblitz.com/edit/angular-iikvfp

## What is the motivation / use case for changing the behavior?

In order to have the sidenav structure worked, it's better to be able to have <router-outlet name="panel"></router-outlet>  in app.component.html. 

Move <router-outlet name="panel"></router-outlet> to product-page.component.html works, but cannot make use of the sidenav well defineded.

## Environment

<pre><code>
Angular version: 5.2.x
</code></pre>

**Comment by dawidgarus** [comment] 2018-05-15 07:10
Just remove relativeTo

**Comment by jasonaden** [comment] 2018-05-15 22:31
Based on the reproduction stackblitz, this looks like a duplicate of https://github.com/angular/angular/issues/10981. I'll close this issue and you should track #10981 for updates.

If there's something different about what you're reporting, please create a new issue with clear reproduction instructions, and reference this issue.

**Closed by jasonaden** 2018-05-15 22:31 UTC
Labels: comp: router
