### ISSUE TITLE
Error: Argument at index 2 of UMD factory call is not a `require` call with a single string argument

### ISSUE THREAD

**Issue by NareshSmith** [angular/angular#44380] opened 2021-12-05 17:14 UTC
### Which @angular/* package(s) are the source of the bug?

compiler, upgrade

### Is this a regression?

Yes

### Description

Hi Team, After upgrade our existing project from  angular 12 to 13, It starting throwing error and stucked at generating browser application bundle phase. Please find the error below:

```
Error: Argument at index 2 of UMD factory call is not a `require` call with a single string argument:
factory(require('@angular/core'),require('@angular/common'),exports, require('@angular/core'), require('perfect-scrollbar'), require('rxjs'), require('rxjs/operators'), require('@angular/common'))
    at getRequiredModulePath (file:///***/node_modules/@angular/compiler-cli/bundles/ngcc/main-ngcc.js:3627:11)
    at getImportsOfUmdModule (file:///***/node_modules/@angular/compiler-cli/bundles/ngcc/main-ngcc.js:3618:15)
    at UmdDependencyHost.extractImports (file:///***/node_modules/@angular/compiler-cli/bundles/ngcc/main-ngcc.js:4085:37)
    at UmdDependencyHost.recursivelyCollectDependencies (file:///***/node_modules/@angular/compiler-cli/bundles/ngcc/main-ngcc.js:1459:26)
    at UmdDependencyHost.collectDependencies (file:///***/node_modules/@angular/compiler-cli/bundles/ngcc/main-ngcc.js:1445:12)
    at DependencyResolver.getEntryPointWithDependencies (file:///***/node_modules/@angular/compiler-cli/bundles/ngcc/main-ngcc.js:3833:12)
    at EntryPointCollector.walkDirectoryForPackages (file:///***/node_modules/@angular/compiler-cli/bundles/ngcc/main-ngcc.js:4403:40)
    at EntryPointCollector.walkDirectoryForPackages (file:///***/node_modules/@angular/compiler-cli/bundles/ngcc/main-ngcc.js:4423:32)
    at file:///***/node_modules/@angular/compiler-cli/bundles/ngcc/main-ngcc.js:4557:70
    at trackDuration (file:///***/node_modules/@angular/compiler-cli/bundles/ngcc/main-ngcc.js:4154:18)
(node:12620) UnhandledPromiseRejectionWarning: Error: NGCC failed.
    at NgccProcessor.process (***\node_modules\@ngtools\webpack\src\ngcc_processor.js:146:19)
    at ***\node_modules\@ngtools\webpack\src\ivy\plugin.js:141:27
    at Hook.eval [as call] (eval at create (***\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:24:1)
    at Hook.CALL_DELEGATE [as _call] (***\node_modules\tapable\lib\Hook.js:14:14)
    at Compiler.newCompilation (***\node_modules\webpack\lib\Compiler.js:1054:30)
    at ***\node_modules\webpack\lib\Compiler.js:1099:29
    at eval (eval at create (***\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:31:1)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:12620) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:12620) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by JoostK** [comment] 2021-12-05 18:35
@gkalpak It looks like we're now crashing during dependency collection _after_ ngcc has added new imports in an earlier invocation.

**Comment by gkalpak** [comment] 2021-12-05 19:20
Yeah, this has been accidentally broken in https://github.com/angular/angular/pull/44245/commits/2bc3522e167fef7dc695d0807243b1c4fa1f596d 😇
I'll work on a fix.

**Comment by mruknowme** [comment] 2021-12-06 05:20
I am having a similar issue, thank you for working on resolution @gkalpak .
Am I right that the only temporary 'fix' is to downgrade to 13.0.2?
Is there any ETA on fix being merged and shipped in 13.0.4?

Thanks!

**Comment by ShilpaMore-27** [comment] 2021-12-06 07:31
I too have a similar issue.
Angular cli version -  12.2.13
From the checkin I can see that it is targeted to Angular 12.2.X version. 
Issue : After upgrading to angular 12, while doing npm install the compiler throws above error for a custom package "angular2-query-builder".
Kindly let me know when will the fix be available in version 12.2.X?

**Comment by JoostK** [comment] 2021-12-06 07:48
@ShilpaMore-27 yes, this will be fixed in v12 as well.

**Comment by ShilpaMore-27** [comment] 2021-12-06 07:56
Thanks.

Can I know ETA of this fix into release?

**Comment by JoostK** [comment] 2021-12-06 07:59
Likely in this week's release, on Wednesday/Thursday.

**Comment by yoan-asdrubal** [comment] 2021-12-06 12:56
Same issue after add several dependencies to nx workspaces. 
When I create nx workspace its works perfect, but if I add several dependencies to third libs, any build process broken with this issue.

**Comment by lukewoodard** [comment] 2021-12-06 19:26
I have rolled back to 13.0.2 and still have this same issue. Is this fix looking like Wednesday?

**Comment by gkalpak** [comment] 2021-12-06 20:08
@lukewoodard: If you rolled back to v13.0.2 and still have the issue, then the fix might not help you :grin:
(The fix is specifically for a regression introduced in 13.0.3.)

**Comment by JoostK** [comment] 2021-12-06 20:16
It might be that wiping all of `node_modules` is needed to ensure there are no artifacts from 13.0.3 (or 12.2.13)

**Comment by StevRoger** [comment] 2021-12-07 10:49
Happened to me as well when I tried to upgrade from Angular 11 to Angular 12. Is there any solution for Angular 12?

**Comment by innoveltec** [comment] 2021-12-07 11:28
Here also having the same error. Having an nx repo which is using angular v12.2.14

**Closed** 2021-12-07 13:33 UTC
Labels: type: bug/fix, regression, comp: ngcc, P3

**Comment by gkalpak** [comment] 2021-12-07 16:18
> Happened to me as well when I tried to upgrade from Angular 11 to Angular 12. Is there any solution for Angular 12?

@StevRoger: The fix has been backported to the v12.2.x branch and will be included in the next v12 release, but I am not sure when the release will be.

In the meantime, you could try downgrading to 12.2.13.

**Comment by NareshSmith** [comment] 2021-12-07 17:43
Will it get resolved by updating it to latest version of angular (>13.0.xxx).

**Comment by gkalpak** [comment] 2021-12-07 17:45
Not until 13.0.4 is out (most probably later this week).

**Comment by innoveltec** [comment] 2021-12-07 19:12
So @gkalpak if I understand it correctly if I revert back to angular v12.2.13 as a fixed version for the moment in my package.Json file of my nx repo which was using v12.2.14, I will not have this issue anymore while building?

**Comment by ShilpaMore-27** [comment] 2021-12-08 06:39
> Likely in this week's release, on Wednesday/Thursday.

Hey, is this fix now available?

**Comment by helgetan** [comment] 2021-12-08 09:12
any updates on release?

**Comment by innoveltec** [comment] 2021-12-08 12:54
I tried to revert my angular packages from v12.2.14 back to v12.2.13 in my nx repo and can confirm that the error is gone.

**Comment by hc3** [comment] 2021-12-08 13:19
I managed to make the project work in another version [ 12.2.13 ]

I'm using this version for some angular packages, I'll leave my package.json as an example.

````
"dependencies": {
  "@angular/animations": "12.2.13",
  "@angular/cdk": "12.2.13",
  "@angular/common": "12.2.13",
  "@angular/compiler": "12.2.13",
  "@angular/core": "12.2.13",
  "@angular/forms": "12.2.13",
  ... other dependencies 
},
"devDependencies": {
  "@angular-devkit/build-angular": "12.2.13",
  "@angular/cli": "12.2.13",
  "@angular/compiler-cli": "12.2.13",
  "@angular/language-service": "12.2.13",
  ... other dependencies 
}

````

**Comment by ShilpaMore-27** [comment] 2021-12-09 04:10
For me it is not working by downgrading to 12.2.13. while npm install at "angular2-query-builder" gives an error.
Any suggestions here? or could you please let me know when this fix will be available in release?

**Comment by gkalpak** [comment] 2021-12-09 20:16
@ShilpaMore-27: The stack trace implies you are using `@angular/compiler-cli@12.2.14` (not `12.2.13`).
Make sure you also downgrade `@angular/compiler-cli` (which is usually in `devDependencies` - not in `dependencies` as most other `@angular/*` packages) to v12.2.13.

**Comment by ShilpaMore-27** [comment] 2021-12-10 07:03
> [gkalpak](/gkalpak)

In package.json  I had  "@angular/compiler-cli": "^12.2.13". When I removed "^" it worked. npm install and ng build was successfull. But I am facing one more issue when I do "npm start", below are the details of error (not sure if this is due to the downgrade to 12.2.13)

![err](https://user-images.githubusercontent.com/81629986/145531448-5f5b386e-e7ab-4faf-adfc-b7ed78068010.png)

**Comment by ShilpaMore-27** [comment] 2021-12-12 15:15
> Hello gkalpak
Do you have any suggestions on above?

**Comment by ShilpaMore-27** [comment] 2021-12-12 15:15
> > [gkalpak](/gkalpak)
> 
> In package.json I had "@angular/compiler-cli": "^12.2.13". When I removed "^" it worked :) . npm install and ng build was successfull. But I am facing one more issue when I do "npm start", below are the details of error (not sure if this is due to the downgrade to 12.2.13)
> 
> ![err](https://user-images.githubusercontent.com/81629986/145531448-5f5b386e-e7ab-4faf-adfc-b7ed78068010.png)

Hello gkalpak
Do you have any suggestions on above?

**Comment by MaximeBerduck** [comment] 2021-12-13 09:31
> > [gkalpak](/gkalpak)
> 
> In package.json I had "@angular/compiler-cli": "^12.2.13". When I removed "^" it worked :) . npm install and ng build was successfull. But I am facing one more issue when I do "npm start", below are the details of error (not sure if this is due to the downgrade to 12.2.13)
> 
> ![err](https://user-images.githubusercontent.com/81629986/145531448-5f5b386e-e7ab-4faf-adfc-b7ed78068010.png)

Hi @ShilpaMore-27,
The firt warning between '****' is because your angular.json file isn't complete. You need to check it with the new organisation of it. Maybe your error is because of it. (https://stackoverflow.com/questions/68774226/an-unhandled-exception-occurred-the-buildoptimizer-option-cannot-be-used-with)

**Comment by ShilpaMore-27** [comment] 2021-12-14 04:39
> > > [gkalpak](/gkalpak)
> > 
> > 
> > In package.json I had "@angular/compiler-cli": "^12.2.13". When I removed "^" it worked :) . npm install and ng build was successfull. But I am facing one more issue when I do "npm start", below are the details of error (not sure if this is due to the downgrade to 12.2.13)
> > ![err](https://user-images.githubusercontent.com/81629986/145531448-5f5b386e-e7ab-4faf-adfc-b7ed78068010.png)
> 
> Hi @ShilpaMore-27, The firt warning between '****' is because your angular.json file isn't complete. You need to check it with the new organisation of it. Maybe your error is because of it. (https://stackoverflow.com/questions/68774226/an-unhandled-exception-occurred-the-buildoptimizer-option-cannot-be-used-with)

Hi @gkalpak 
Yes I have gone through that link before, We havenot enabled aot in our environment for few reasons. but seems that v12 upgrade is going to make aot compulsory.

**Comment by gkalpak** [comment] 2021-12-14 19:30
@ShilpaMore-27, I don't know is it is compulsory, but maybe it is required for `buildOptimizer`. In any case, this is unrelated to the issue discussed here and is more of an Angular CLI question, so I can't help much. You might want to ask on the Angular CLI repo (where people are more likely to know about `aot` + `buildOptimizer` 😅).
