### ISSUE TITLE
AsyncPipe not showing Observable in view after upgrade to 4.0.2

### ISSUE THREAD

**Issue by jakehockey10** [angular/angular#15910] opened 2017-04-12 01:29 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

`AsyncPipe` does not display `Observable`.  I am getting a collection from firebase I am receiving the collection just fine, but in the view, the collection never shows up.  This was working before I upgraded to Angular versions 4.0.2.  I've since reverted my package.json file and the problem still persists.  There is no error coming from Angular.

**Expected behavior**

I would expect that an Observable would "resolve" itself with the use of the `AsyncPipe` and show in the view as it did previously knowing that the Observable can be subscribed to and the Observable is "resolved" for that subscription.

**Minimal reproduction of the problem with instructions**

```html
<div id="messages">
  <div *ngFor="let message of messages | async">
    {{message.message}} <!-- simplified -->
  </div>
</div>
```
```typescript
@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css']
})
export class HomeComponent implements AfterViewChecked {
  ...
  public newMessage: string;
  public messages: FirebaseListObservable<any>;

  constructor(
    public authService: AuthenticationService
  ) {
    this.messages = this.authService.messages;
    this.authService.messages.subscribe(response => console.log(response));
  }

...
}
```
```typescript
@Injectable()
export class AuthenticationService {
  public messages: FirebaseListObservable<any>;
  ...

  constructor(public angularfire: AngularFire) {
    this.messages = this.angularfire.database.list('messages');
  }
...
}
```
The view never shows the messages stored in Firebase, but the additional subscription made above shows the messages retrieved successful in the console.  Therefore, I conclude that this isn't an issue with talking to firebase.
![screenshot from 2017-04-11 19-12-22](https://cloud.githubusercontent.com/assets/1821383/24937001/d2b1cf00-1eea-11e7-8cae-c92a1ff377c4.png)

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

```
$ ng version
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.0.0
node: 6.9.1
os: linux x64
@angular/animations: 4.0.2
@angular/common: 4.0.0
@angular/compiler: 4.0.0
@angular/core: 4.0.0
@angular/forms: 4.0.0
@angular/http: 4.0.0
@angular/material: 2.0.0-beta.3
@angular/platform-browser: 4.0.0
@angular/platform-browser-dynamic: 4.0.0
@angular/router: 4.0.0
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.0
```

* **Angular version:** 2.0.X

I had it working at one point with version 4.0.0.  I had it working with 4.0.1 as well.  I upgraded to 4.0.2 and it stopped working and I've been trying to revert back to 4.0.0 and 4.0.1.  Reverting was successful, but restoring previous functionality remained unsuccessful.

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome and Firefox.
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

TypeScript 2.2.2

* **Node (for AoT issues):** `node --version` =   
```
$ node --version
v6.9.1
```

**Comment by vicb** [comment] 2017-04-12 02:29
Please attach a plunker with a minimal repro. Thanks.

**Comment by jakehockey10** [comment] 2017-04-12 04:35
I apologize, but that's embarrassingly a daunting task for me.  I have no idea how to install Angular the way I've been relying on `@angular/cli` to provide me in terms of abstraction.  Could I get pointed in the right direction on how I can get such a recent Angular 4 configuration working in a plnkr?  I googled around for a while and I couldn't find anything remote close.  I doubt I will be able to reproduce the issue in a version before 4.0.0 at the very oldest.  I believe the recent version is at the root of the cause of my issue.

I will continue diagnosing and try to update with more actionable information.  Thanks for your reply.

**Comment by kylecannon** [comment] 2017-04-12 04:45
@jakehockey10 here is a plunkr to get you started with Angular 4.0.2: https://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=preview

**Comment by jakehockey10** [comment] 2017-04-12 22:52
@kylecannon Thank you for the headstart.  I'm still having trouble getting the rest of my dependencies in there, but I'll update this as soon as I possibly can.

**Comment by MvS-IT** [comment] 2017-04-21 12:55
Hello, I'm facing the same sort of issue. I've upgraded this week from Angular2.x to Angular4.0.2. In my project I have a Header-, Content- and FooterComponent. The Header- and ContentComponent subscribe to Observables in a couple of services in their ngOnInit methods. The returning data is not shown/resolved in the html view, whereas it did in Angular2.x version for the last 5/6 months. 
It becomes even more wierd after I've setup a TestComponent; this component has a ngOnInit method as well in which a subscription is done to one of the services I use in the forementioned ContentComponent. The view of this single component does show the data to which has been subscribed. Of course the code is identical in both ngOnInit methods.
I don't have clue anymore. Anybody's got a suggestion?

**Comment by kylecannon** [comment] 2017-04-25 05:04
@MvS-IT - Please create a plunker using the template https://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=preview

**Comment by MvS-IT** [comment] 2017-04-25 08:27
Hello Kyle, my issue was caused by incorrect use of the BsDropDownModule (ngx-bootstrap) in the headercomponent. This blocked the view to be updated. So it appears not having to do anything with this issue #15910.
Cheers

**Comment by jrwpatterson** [comment] 2017-05-09 15:26
@MvS-IT What did you do I'm having the same thing and am using ngx-bootstrap

**Comment by MvS-IT** [comment] 2017-05-10 08:44
@jrwpatterson, I had to add a star to the dropDownMenu to get an embedded template:
<ul class="dropdown-menu" dropdownMenu role="menu" aria-labelledby="zzz_menu">
had to be:
<ul class="dropdown-menu" *dropdownMenu role="menu" aria-labelledby="zzz_menu">

**Comment by vicb** [comment] 2018-05-31 22:39
Closing as no repro has been provided

**Closed by vicb** 2018-05-31 22:39 UTC
Labels: comp: core & compiler, freq1: low, severity3: broken, state: Need repro, type: bug/fix
