### ISSUE TITLE
routerlinkactive doesn't work in lazy loaded modules

### ISSUE THREAD

**Issue by Gnorro** [angular/angular#38760] opened 2020-09-09 15:01 UTC
# 🐞 bug report

### Description
I have an app with lots of lazy loaded modules.
I have added another module that have 2 components. Inside one of these components I have a routerLinkActive
But it seems routerLinkActive is not recognized because I see the following inside html
`<span class="ng-tns-c338-10" tabindex="0" ng-reflect-router-link-active="active" ng-reflect-router-link="/info">Info</span>`

There is no error in console, but I see that it doesn't work also because there is no class "active" addded (as described beneath).

If I don't use lazy loading everything works and the final html is:
`
<span class="ng-tns-c347-11 active" tabindex="0">Info</span>
`

In my module.routing I have
<pre><code>
import { NgModule } from "@angular/core";
import { RouterModule, Routes } from "@angular/router";

const appRoutes: Routes = [

    {
        ...
    }
];

@NgModule({
    imports: [RouterModule.forChild(appRoutes)],
    exports: [RouterModule]
})
export class InfoRoutingModule { }
</code></pre>

And in my info.module:
<pre><code>
import { NgModule } from "@angular/core";
import { RouterModule, Routes } from "@angular/router";
import { MyComponent } from 'app/...';
import { MyChildComponent } from 'app/...';
import { CommonModule } from '@angular/common';
import { NgModule, LOCALE_ID } from '@angular/core';
import { HttpClientModule } from '@angular/common/http';
import { ResponsiveModule } from 'ngx-responsive';
import { RouterModule } from '@angular/router';

@NgModule({
  declarations: [
    MyComponent,
    MyChildComponent
  ],
  imports: [
    CommonModule,
    HttpClientModule,
    ResponsiveModule.forRoot(),
    InfoRoutingModule,
    RouterModule
  ],
  exports: [
    RouterModule
  ]
})
export class InfoModule { }
</code></pre>

This is parent component:
```
<div class="text-page">
  <div class="container">
    <div class="mainpage-content">
      <div class="navigation-col" app-child></div>
    </div>
  </div>
</div>
```

This is child component:
```
<div class="help-menu">
    <span [routerLinkActive]="['active']" [routerLink]="'/info'">Info</span>
</div>
```

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.1.1
Node: 12.18.1
OS: win32 x64

Angular: 9.1.1
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.12
@angular-devkit/build-angular     0.901.12
@angular-devkit/build-optimizer   0.901.12
@angular-devkit/build-webpack     0.901.12
@angular-devkit/core              9.1.1
@angular-devkit/schematics        9.1.1
@angular/cdk                      9.2.0
@angular/material                 9.2.0
@ngtools/webpack                  9.1.12
@schematics/angular               9.1.1
@schematics/update                0.901.1
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0
</code></pre>

Thanks

**Comment by atscott** [comment] 2020-09-09 18:59
Hi @Gnorro, could you please create a stackblitz reproduction of this issue?

**Comment by Gnorro** [comment] 2020-09-10 06:42
Hi atscott
I know that a stackblitz reproduction would be useful, but this project is hube an would take me hours to extract only what is needed. sorry

**Comment by geromegrignon** [comment] 2020-09-10 12:20
@Gnorro here is working stackblitz example with routerLinkActive, try to use it a base to reproduce the issue as it works fine in isolation : https://stackblitz.com/edit/angular-ivy-xao8c5?file=src%2Fapp%2Fapp.component.html

**Comment by atscott** [comment] 2020-09-10 16:45
Hi @Gnorro, we really do need a reproduction in order to investigate issues. Could you try using the example from @geromegrignon as a starting point for your reproduction? I'll leave this open for now to give you a chance to get a reproduction up.

**Comment by Gnorro** [comment] 2020-09-11 13:54
It's exactly like that, I don't know why it's not working. 

Thanks anyway

**Comment by atscott** [comment] 2020-09-14 16:40
Closing this since there's not a reproduction we can use to investigate the issue. Please do open a new ticket if you're able to get an example of this failure!

**Closed by atscott** 2020-09-14 16:40 UTC
Labels: comp: router, router: directives, state: Needs repro

**Comment by nutza249949** [comment] 2020-09-14 16:45
n

**Comment by nutza249949** [comment] 2020-09-14 16:45
> 
> 
> 
> # 🐞 bug report
> 
> ### Description
> I have an app with lots of lazy loaded modules.
> I have added another module that have 2 components. Inside one of these components I have a routerLinkActive
> But it seems routerLinkActive is not recognized because I see the following inside html
> `<span class="ng-tns-c338-10" tabindex="0" ng-reflect-router-link-active="active" ng-reflect-router-link="/info">Info</span>`
> 
> There is no error in console, but I see that it doesn't work also because there is no class "active" addded (as described beneath).
> 
> If I don't use lazy loading everything works and the final html is:
> `
> <span class="ng-tns-c347-11 active" tabindex="0">Info</span>
> `
> 
> In my module.routing I have
> <pre><code>
> import { NgModule } from "@angular/core";
> import { RouterModule, Routes } from "@angular/router";
> 
> const appRoutes: Routes = [
> 
>     {
>         ...
>     }
> ];
> 
> @NgModule({
>     imports: [RouterModule.forChild(appRoutes)],
>     exports: [RouterModule]
> })
> export class InfoRoutingModule { }
> </code></pre>
> 
> And in my info.module:
> <pre><code>
> import { NgModule } from "@angular/core";
> import { RouterModule, Routes } from "@angular/router";
> import { MyComponent } from 'app/...';
> import { MyChildComponent } from 'app/...';
> import { CommonModule } from '@angular/common';
> import { NgModule, LOCALE_ID } from '@angular/core';
> import { HttpClientModule } from '@angular/common/http';
> import { ResponsiveModule } from 'ngx-responsive';
> import { RouterModule } from '@angular/router';
> 
> 
> @NgModule({
>   declarations: [
>     MyComponent,
>     MyChildComponent
>   ],
>   imports: [
>     CommonModule,
>     HttpClientModule,
>     ResponsiveModule.forRoot(),
>     InfoRoutingModule,
>     RouterModule
>   ],
>   exports: [
>     RouterModule
>   ]
> })
> export class InfoModule { }
> </code></pre>
> 
> This is parent component:
> ```
> <div class="text-page">
>   <div class="container">
>     <div class="mainpage-content">
>       <div class="navigation-col" app-child></div>
>     </div>
>   </div>
> </div>
> ```
> 
> This is child component:
> ```
> <div class="help-menu">
>     <span [routerLinkActive]="['active']" [routerLink]="'/info'">Info</span>
> </div>
> ```
> 
> ## 🌍  Your Environment
> 
> **Angular Version:**
> <pre><code>
> Angular CLI: 9.1.1
> Node: 12.18.1
> OS: win32 x64
> 
> Angular: 9.1.1
> ... animations, cli, common, compiler, compiler-cli, core, forms
> ... language-service, platform-browser, platform-browser-dynamic
> ... platform-server, router, service-worker
> Ivy Workspace: Yes
> 
> Package                           Version
> -----------------------------------------------------------
> @angular-devkit/architect         0.901.12
> @angular-devkit/build-angular     0.901.12
> @angular-devkit/build-optimizer   0.901.12
> @angular-devkit/build-webpack     0.901.12
> @angular-devkit/core              9.1.1
> @angular-devkit/schematics        9.1.1
> @angular/cdk                      9.2.0
> @angular/material                 9.2.0
> @ngtools/webpack                  9.1.12
> @schematics/angular               9.1.1
> @schematics/update                0.901.1
> rxjs                              6.5.5
> typescript                        3.8.3
> webpack                           4.42.0
> </code></pre>
> 
> Thanks
