### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by roweldeguzman** [angular/angular#19998] opened 2017-10-28 04:24 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

![screenshot from 2017-10-28 12-21-05](https://user-images.githubusercontent.com/8720937/32131206-adc91328-bbda-11e7-97c9-c38015018c0a.png)

## Minimal reproduction of the problem with instructions
Just create a new app using CLI ang then run ng build

## Environment

<pre>Production<code>
Angular version: 4.2.4

Browser:
- [ ] Chrome (desktop) version XX
- [x ] Chrome (Android) version 39.0.2171.93
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

For Tooling issues:
- Node version: 6.11.3
- Platform:  Linux

**Comment by alexzuza** [comment] 2017-10-28 05:28
Hello!

I create new app using CLI every day and it works for me. If it doesn't work for you you should at least provide us reproduction. Your screenshot doesn't help us

**Comment by 92161898515** [comment] 2017-10-28 05:34
tá tudo bem

**Comment by roweldeguzman** [comment] 2017-10-28 06:28
Hi @alexzuza, did you use the environment I provided?

**Comment by roweldeguzman** [comment] 2017-10-28 11:49
@alexzuza it actually working from chrome version 45-latest in android, lower than version 45 then it produce error. sorry for not mentioning earlier.

**Comment by trotyl** [comment] 2017-10-28 11:59
Line 3084 is:

```typescript
return options.reduce(function (merged, opt) { return (Object.assign({}, merged, opt)); }, {});
```

Please have a look of https://angular.io/guide/browser-support first and have a search of `Object.assign` in this repo.

<sub>Can be closed as duplicate of more than dozens of other issues.</sub>

**Closed** 2017-10-28 12:04 UTC
