### ISSUE TITLE
Angular Compiler compileModuleAndAllComponentsAsync declaration of null

### ISSUE THREAD

**Issue by Razgort** [angular/angular#36056] opened 2020-03-13 14:09 UTC
# 🐞 bug report

### Affected Package
@angular/core
the function compileModuleAndAllComponentsAsync in angular/core compiler is not loading module anymore:

### Is this a regression?
Yes, we were totally using this with angular 8 compiler
Hello there,
I'm sorry to bother you here guys.
But we are trying to upgrade our angular application to your new patch angular 9 ivy with AOT compilation.
We have a main feature that is to load stand alone angular module precompiled to .umd.js file.
And we load them in our main angular application at runtime.
For this we were using this at the moment . 
Our url is our own application and the file is located in our assets folder which is publicly served from our app
```
`      return SystemJS.import(url)
        .then((module: any) => {
          return module[moduleInfo.moduleName]
        })
        .then(
          module => {
            console.log(module)
            return this.compiler
              .compileModuleAndAllComponentsAsync(module)
              .then(_compiled => {
                return module
              })
              .catch(error => {
                console.error('ERROR in SystemJS compile with module', {
                  error,
                  module
                })

                // tslint:disable-next-line: rxjs-throw-error
                throw { error, module }
              })
          }
          // console.error.bind(console))
        )`
```
### Description

I put in this file an example umd.js file that we were loading at runtime

## 🔥 Exception or Error
<pre><code>
core.js:3872 ERROR TypeError: Cannot read property 'declarations' of null
    at Compiler_compileModuleAndAllComponentsSync__POST_R3__ (core.js:27418)
    at Compiler_compileModuleAndAllComponentsAsync__POST_R3__ [as compileModuleAndAllComponentsAsync] (core.js:27429)
    at module.service.ts:182
    at ZoneDelegate.invoke (zone.js:396)
    at Object.onInvoke (core.js:27800)
    at ZoneDelegate.invoke (zone.js:395)
    at Zone.run (zone.js:153)
    at zone.js:894
    at ZoneDelegate.invokeTask (zone.js:431)
    at Object.onInvokeTask (core.js:27788)
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.0.6
Node: 12.16.1
OS: win32 x64

Angular: 9.0.6
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker
Ivy Workspace: Yes

Package                                    Version
--------------------------------------------------------------------
@angular-devkit/architect                  0.900.6
@angular-devkit/build-angular              0.900.6
@angular-devkit/build-ng-packagr           0.900.6
@angular-devkit/build-optimizer            0.900.6
@angular-devkit/build-webpack              0.900.6
@angular-devkit/core                       8.1.3
@angular-devkit/schematics                 8.1.3
@angular/cdk                               9.1.1
@angular/http                              8.0.0-beta.10
@angular/material                          9.1.1
@angular/material-moment-adapter           9.1.1
@angular/pwa                               0.801.3
@ngtools/webpack                           9.0.6
@nguniversal/common                        9.0.1
@nguniversal/express-engine                9.0.1
@nguniversal/module-map-ngfactory-loader   8.2.6
@schematics/angular                        8.1.3
@schematics/update                         0.900.6
ng-packagr                                 9.0.0
rxjs                                       6.5.4
typescript                                 3.6.5
webpack                                    4.41.2
</code></pre>

**Anything else relevant?**

modula.umd.js renamed for pasting to modulea.umd.js.txt

[modulea.umd.js.txt](https://github.com/angular/angular/files/4329952/modulea.umd.js.txt)

**Comment by alxhub** [comment] 2020-03-17 22:44
It looks like the `modulea.umd.js` file is being compiled with `tsickle`, which is the preprocessor for JS code to be compiled with Closure Compiler. This type of code is incompatible with JIT mode entirely in Ivy.

You should remove tsickle from your build (remove the `annotateForClosureCompiler` setting from your tsconfig entirely), and uninstall tsickle itself.

**Comment by Razgort** [comment] 2020-03-18 12:16
Thanks for pointed this out !!
We thought that was what we missed, but when we removed it ng-packagr failed during library compilation with :

> An unhandled exception occurred: Cannot find module './lib/clean'

**Comment by Borsi92** [comment] 2020-04-17 12:12
@Razgort Have you found any solution for this? I am getting the same error. Any help would be much appreciated!

**Comment by raberana** [comment] 2020-05-18 12:51
Most likely there's something wrong in the module but is hidden as an inner exception.
If you run npm run dev:ssr, you should be able to see the error.

In my case, it is because windows is not defined.

So in my server.ts, I added these lines:

>   const domino = require('domino');
>   const win = domino.createWindow(indexHtml);
>   // mock
>   (global as any).window = win;
>   (global as any).document = win.document;
>   (global as any).navigator = win.navigator;
> 
>   // Our Universal express-engine (found @ https://github.com/angular/universal/tree/master/modules/express-engine)
>   server.engine('html', ngExpressEngine({
>     bootstrap: AppServerModule,
>   }));

**Comment by Razgort** [comment] 2020-05-19 08:37
@Boris92 no didnt find any clue to solve this ...

**Comment by victory-oki** [comment] 2020-05-20 11:38
@Borsi92 I had the same issue but I eventually found out that my lazy loading script was wrong
this was what I had
`path:'modulePath', loadChildren:()=>import('../some-module/some-module.module').then(m=>{m.some-module})`
this is what it should have been
`path:'modulePath', loadChildren:()=>import('../some-module/some-module.module').then(m=>m.some-module)`
turns out i didn't return the module in the arrow function.
I don't know if this helps, but this is the issue I had and how I solved it

**Comment by alxhub** [comment] 2020-05-26 23:22
Hi @Razgort,

Without a working reproduction that we can dig into, it'll be hard for us to make any more progress on this issue. Can you provide a minimal reproduction with instructions for us?

Thanks,
Alex

**Comment by rainbowland302** [comment] 2020-06-03 10:45
Same issues here. Actually this worked in Angular 8.x. But it failed after updating to Angular 9.x.
Just as @alxhub mentioned, I used rollup with rollup-angular to build the external angular module, which aims to import it into the application at runtime so as to deploy them separately. And rollup-angular uses tsickle.

**Comment by velmurugan707** [comment] 2020-08-01 19:39
I simply saved my app.module.js file. The issue is solved for me.

**Comment by petebacondarwin** [comment] 2020-10-19 15:15
Closing as we have no reproduction to work with. If you still have this problem in your project then please open a new issue with a runnable reproduction that we can debug.

**Closed by petebacondarwin** 2020-10-19 15:15 UTC
Labels: comp: compiler, engine: ivy, needs clarification, needs reproduction, state: needs eng input, triage #1, type: bug/fix
