### ISSUE TITLE
Clicking header anchors results in full navigation

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#16293] opened 2017-04-25 00:10 UTC
Steps to repro:

1. go to https://aio-staging.firebaseapp.com/tutorial/toh-pt3
2. click on the icon next to "Where you left off" header
3. observe network tab / console

Expected: viewport scrolls down to the header, no network activity or rerendering of the page.
Actual: the current document json is redownloaded and rerendered.

**Comment by gkalpak** [comment] 2017-04-25 11:17
I can't reproduce fetching the document again. Are you still seeing that?
What I do see, is a Google Analytics request (which seems intentional), but we can change that if desired and some favicon requests (and I have no idea where they come from) :confused:

**Comment by IgorMinar** [comment] 2017-04-28 14:45
I no longer see the json files being redownloaded but I see two requests to google analytics + several icon downloads:
<img width="1383" alt="screen shot 2017-04-28 at 4 44 15 pm" src="https://cloud.githubusercontent.com/assets/216296/25533774/0459ac86-2c32-11e7-8960-6aceb3a6e780.png">

**Comment by gkalpak** [comment] 2017-04-28 18:13
I believe the GA requests are actually one (one from the app that is "captured" and handled by the SW and one from the SW to the internet). According to my understanding, the little gear icon or the left of a request means it comes from the SW.

Currently, this is how the GA service is set up. There is a note on the TODO column of [aio][1] about changing it to ignore query-/hash-only changes. If that is indeed what we want, it is trivial to implement.

##
I have also seen the favicon requests and I have no idea where they come from. They are listed under the files cached by the SW. I have no idea why they are not served by the SW and what triggers them :confused:

[1]: https://github.com/angular/angular/projects/7

**Comment by wardbell** [comment] 2017-04-30 02:09
@gkalpak I confirmed the GA behavior for in-page # frag clicks. I had arbitrarily decided to track those too and have no instructions to stop doing so. 

I just added PR #16441 which states this explicitly and confirms with a test. That would be the vehicle to change this decision if we choose to do so.

**Comment by petebacondarwin** [comment] 2017-04-30 19:29
@IgorMinar  can you make a call here?

**Comment by wardbell** [comment] 2017-05-03 19:10
The remaining issue is whether to track in-page navigations.  Extracted that to #16521.

Closing this one.

**Closed by wardbell** 2017-05-03 19:10 UTC
Labels: comp: aio, type: bug
