### ISSUE TITLE
Chained `redirectTo` does not work as expected.

### ISSUE THREAD

**Issue by bennadel** [angular/angular#10120] opened 2016-07-17 13:43 UTC
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

If you have chained `redirectTo` route configurations, like this:

```js
provideRouter([
  {
  	path: "home",
  	component: HomeComponent
  },
  // Handle the "no route" case.
  {
  	path: "",
  	pathMatch: "full", // <-- NO ROUTE.
  	redirectTo: "/home"
  },
  // Try to handle the "catch all" case.
  {
  	path: "",
  	pathMatch: "prefix", // <-- CATCH ALL.
  	redirectTo: "/"
  }
])
```

... and you attempt to navigate to `/foo/bar/baz`, you get the following error:

```
Error: Uncaught (in promise): Error: Cannot match any routes: ''
```

**Expected/desired behavior**

The expected behavior is that you would get the following navigational redirections:

`/foo/bar/baz` --> `/` --> `/home`

The "catch all" should redirect to `/` and then the "no route" should subsequently redirect to `/home`. 

**Reproduction of the problem**

http://plnkr.co/edit/p5LVHeXdq6cxk4wdBIhc?p=preview

**What is the expected behavior?**

Chained `redirectTo` configuraitons should work. This way, you can better decouple features. It allows any component to redirect to some generic root, `/`, while allowing a higher-up route to then handle a more focused redirect to a default page.

**What is the motivation / use case for changing the behavior?**

I think it just makes sense. Consider a `Location` header in an HTTP request - you can follow several of those chained together. Routing is just the "client-side" version of this, so to speak.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** all
 
* **Language:** all

**Comment by hollanddd** [comment] 2016-07-18 17:11
I've been dealing with this recently and I'm not sure that this is a bug. With the way it is you are expressing intent. In your case the root is '/home' and as such your catch all should redirect there. Ideally we would be pointing it to a 404 of sorts.

**Comment by bennadel** [comment] 2016-07-18 17:23
Thank you for the kind words :)

Perhaps this is just a limitation of the routing system then (I mean in a literal way, not a judgemental way). Personally, I think the chaining would be nice as it means that modules can remain more decoupled. For example, what happens when the "core" route changes from `/home` to `/default`. Now, _every route_ that has logic for handling 404 or other use-cases has to change their code. It seems like it would be cleaner to be able to chain the redirects.

Of, what if there was a 404 case and everyone routed to `/404-not-found`. But, let's say the engineering team didn't have to implement it. So, they try something like:

```js
{
    // We didn't have time to implement this pre-release. For the time being, just let the root handle it.
    path: "404-not-found",
    redirectTo: "/"
}
```

This wouldn't be possible in the current mechanics. 

Anyway, just making a case for the feature.

**Comment by vsavkin** [comment] 2016-07-20 23:09
@bennadel 

This is not a bug.  The router does support cascading redirects: it will apply at most one redirect at any level. So in your case the last route will be matched and the router will redirect the URL to '/'. 

Imo supporting cascading or chained redirects creates router configurations that are not trivial to understand and can result in "confusing" behavior. I experimented with this option and decided against it because I think in practice there are few reasons to use them. And usually you can achieve the same result without them. For example, the configuration you probably want for your case should look like this:

```
{
    path: "home",
    component: HomeComponent
 },
{
    path: "**",
    redirectTo: "/home"
  },
```

Could you provide real-world examples where it would be necessary to use cascading redirects? If there are a lot of use cases where they might be useful, we can revisit this decision.

**Comment by bennadel** [comment] 2016-07-21 13:02
@vsavkin when you say that redirects will apply `one direct at any level`, do mean that something like this would work:

```js
{
	path: "",
	pathMatch: "full",
	redirectTo: "/home" // <--- When no route, redirect to Home.
},
{
	path: "home",
	children: [
		{
			path: "",
			pathMatch: "full",
			redirectTo: "alerts", // <--- Use "alerts" as default Home view.
		},
		{
			path: "alerts"
		}
	]
}
```

This includes a chained-redirect; but, at different levels:

* `/` -->
* `/home` -->
* `/home/alerts`

Is that what you mean (sorry I have not actually tested this).

**Comment by vsavkin** [comment] 2016-07-21 18:49
@bennadel yup, it works.

**Comment by bennadel** [comment] 2016-07-21 19:48
@vsavkin Ah, gotcha. Ok, I should be able to avoid multiple redirects at a single level.

**Comment by bennadel** [comment] 2016-07-21 19:49
@vsavkin Just to be clear then, the redirect chain in my original example doesn't work because `/` and `/home` are both at the same level, right?

**Comment by vsavkin** [comment] 2016-07-21 23:07
@bennadel yup, you are correct. 

We might revisit this behavior in the future, but only if we have real-world use cases justifying it. So closing the issue.

**Closed by vsavkin** 2016-07-21 23:07 UTC
Labels: comp: router, type: feature

**Comment by joshSummerhays** [comment] 2017-09-01 16:49
I know this has been closed but +1 for the ability to have multiple redirects at single level. I have a fairly simple app that I would like to do this with, without dealing with child routes. (i dont need child routes, just multiple redirects at the same level, but looks like I have to look into working with child routes)
