### ISSUE TITLE
Feature: ViewEncapsulation option to inherit style rules from parent

### ISSUE THREAD

**Issue by pcroc** [angular/angular#26298] opened 2018-10-08 15:05 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ x ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
A component cannot inherit styles from its parent unless the parent uses `ViewEncapsulation.None` or defines style rules using `::ng-deep`. This makes it difficult to create simple general purpose components for things like links, buttons, icons, etc. that look correct wherever they are placed.

## Expected behavior
Child component should be able to specify that it will adopt the styles of its container, as if the contents of the component were part of the parent's template.

Maybe something like `ViewEncapsulation.Inherit`.

## Minimal reproduction of the problem with instructions
```
@Component({
  selector: 'mb-parent-thing',
  template: `
    <a>This is bold</a><br/>
    <mb-special-link></mb-special-link>
  `,
  styles: ['a { font-weight: bold }']
})
export class ParentThingComponent {
}

@Component({
  selector: 'mb-special-link',
  template: '<a>This should also be bold, but isn't</a>'
})
export class SpecialLinkComponent {
}
```

Here, I want the anchors within `<mb-special-link>` to inherit the anchor styling defined in the parent, without requiring the parent to change its encapsulation or use ::ng-deep.

## What is the motivation / use case for changing the behavior?
Creating simple component such as this link which automatically adopt the style of their container. Note that I have drastically simplified the 'special link' component, in practice it does much more than just wrap a single anchor tag!

## Environment
<pre><code>
Angular CLI: 6.1.2
Node: 8.11.1
OS: linux x64
Angular: 6.1.1
</code></pre>

**Comment by trotyl** [comment] 2018-10-08 15:40
Duplicate of 
https://github.com/angular/angular/issues/23761

**Comment by pcroc** [comment] 2018-10-08 16:02
@trotyl It looks similar to #23761 but is not exactly the same.

#23761 is requesting a new kind of view encapsulation for the container/parent component, such that style rules propagate to all children. This would be similar to applying `:host ::ng-deep` in front of every style rule in the parent.

What I am suggesting here is slightly different. I want to be able to create a _child_ component that inherits the styles of a view-encapsulated parent, without needing to modify the parent. Essentially, I would like the contents of the child component template to inherit the generated `_ngcontent-XX` attributes from their container, so elements within the child look exactly as they would if included in the parent template.

**Comment by pcroc** [comment] 2018-10-08 16:13
Maybe this is a bug?

If the parent is defined as `ViewEncapsulation.Native`, style rules do propagate down to children. For `ViewEncapsulation.Emulated` they do not.

**Comment by simeyla** [comment] 2019-07-19 00:39
@pcroc that's not the behavior I see with `Native`. If anything I see the opposite behavior! No styles at all.

I get (in Chrome) a new `#shadow-root` with a bunch of styles and my component code inside. But the `ng-content` projected into it has no styles at all. I haven't delved into this but definitely not seeing propagation from the parent.

**Comment by simeyla** [comment] 2019-07-19 00:42
This functionality would be invaluable for 'helper' components that are 'children' of a main component but used only for repeated layout. For example I have a shopping cart checkout and there are several sections with a header - I want to make this `app-checkout-section` a 'peer' component to the checkout page just to clean up the code and aid with responsive design logic. 

Without being able to inherit styles easily I just end up using a bunch of `ng-template` defined locally - and that quickly becomes a mess.

**Comment by mloffer** [comment] 2019-10-23 00:07
This really is critical to using 3rd party libraries. I make use of DevExtreme components extensively, which provide event handlers as hooks to allow me to add and remove classes to control presentation based on the data being displayed. I can no longer control the presentation of these components without turning off view encapsulation entirely and making sure my CSS classes are namespaced properly to prevent collisions.

**Comment by nthornton2010** [comment] 2020-10-13 17:38
This would be a great replacement for ::ng-deep! --- The deprecated combinator that currently has no replacement.

**Comment by petebacondarwin** [comment] 2021-01-23 20:48
The solution to this is to implement `::parts`...

**Closed** 2021-01-23 20:49 UTC
Labels: comp: core, core: CSS encapsulation, feature
