### ISSUE TITLE
Using *ng-if on an element is placing it in the wrong ng-content

### ISSUE THREAD

**Issue by brandyscarney** [angular/angular#5363] opened 2015-11-18 19:38 UTC
We have a Component template that looks like this:

```
<ng-content select="item-left"></ng-content> 
<ion-item-content> 
  <ng-content></ng-content>
</ion-item-content> 
```

But if you add `*ng-if="true"` on the `item-left` element it places this element inside of the `ion-item-content` like this:

```
<ion-item-content>
  <script></script>
  <item-left></item-left>
</ion-item-content>
```

Removing the `*ng-if` places it in the proper place

```
<item-left></item-left>
<ion-item-content></ion-item-content>
```

Is there something we need to improve for this? 

cc @IgorMinar @adamdbradley

**Comment by IgorMinar** [comment] 2015-11-18 20:36
@brandyscarney what version of Angular is this in? Can you share a plunker with repro?
@tbosch / @rkirov can you please help determine if this is a bug in our projection algorithm?

**Comment by brandyscarney** [comment] 2015-11-18 20:57
Angular version - 2.0.0-alpha.46

Yep here is a [Plunker](http://plnkr.co/edit/CSMs81lnUZMJFaWw79Ki?p=preview) of this. I tried to make it easy to see visually. :smile:

**Comment by tbosch** [comment] 2015-11-23 17:08
This is intended behavior so far, but I agree it is not optimal. Here is how content projection works right now:

```
<item-left *ng-if="true">item-left with ng-if</item-left>
```
desugars to
```
<template [ng-if]="true">
<item-left>item-left with ng-if</item-left>
</template>
```

Now Angular uses a simplified algorithm for content projection, called [static content projection](https://docs.google.com/document/d/1BXUFVpImyWN7ynyPKehAesctP0UJTaDYbDTNVkarSeQ/edit). One restriction is that Angular can't project only parts of a template. Therefore, Angular applies the css selector of `<ng-content>` to the `<template>` element itself, and not to its content, as a `<template>` element can have more than one direct child. E.g.
```
<template [ng-if]="...">
  <item-left>...</item-left>
  <item-right>...</item-right>
</template>
```

I understand that in the case of `<item-left *ng-if>` there is no way to add attributes to the implicitly created `<template>` element, and Angular also does use the information that this implicit template only contains one child element. However, we should not add additional semantics to using `*...` over `<template>...` as a user can use either or. 

A workaround for you could be to tell users if they want to use `item-left` inside of `ion-item`, they have to use an explicit `<template>` element with an attribute `item-left`, and you also change your `ng-content` to select elements with an `item-left` attribute.

E.g.
```
<ion-item>
  <template item-left>
      <item-left>item-left with ng-if</item-left>
  <template>
</ion-item>
```

And in `ion-item`:
```
<ng-content select="item-left,[item-left]"></ng-content>
```

I am leaving this issue open as we need a design proposal how to solve this in the best way.

**Comment by justindujardin** [comment] 2016-01-17 19:30
I'm experiencing a similar issue using ngFor. Here's a plunkr: http://plnkr.co/edit/0TfaloiCmVPCDkzHnNXB?p=preview

Your workaround does help, but it's pretty inelegant. My component becomes simpler from using ng-content select, but the users of it now have to expand out ngFor and ngIf usages manually.

This
```html
<md-tab-title *ngFor="#t of tabs">{{t.title}}</md-tab-title>
```

Becomes this
```html
<template md-tab-title ngFor [ngForOf]="tabs" #t="$implicit">
  <md-tab-title>{{t.title}}</md-tab-title>
</template>
```

I don't have a solution to suggest, but would be eager to see this fixed.  Thanks for all your hard work. :+1:

**Comment by hitmanmcc** [comment] 2016-02-15 17:08
I too am experiencing this issue, I have a couple of different examples of how this is affecting my app in this plunkr: https://plnkr.co/edit/8yfJvF8EFIknhaYD8BC8
Just in case you guys want to take a look at it for inspiration.

**Comment by zoechi** [comment] 2016-02-16 07:49
That behavior is compatible with the shadow DOM `<content>` tag behavior. I guess that was the intention. 
Shadow DOM is switching to `<slot>` https://webkit.org/blog/4096/introducing-shadow-dom-api/. AFAIK the behavior is the same except selectors are reduced to a slot name.

**Comment by zoechi** [comment] 2016-02-16 07:56
dup of #3397

**Comment by tbosch** [comment] 2016-03-02 21:12
Not actually a dupe.

**Comment by tbosch** [comment] 2016-03-02 21:12
See https://github.com/angular/angular/issues/6303 for a solution.

**Comment by naomiblack** [comment] 2016-03-02 23:22
closing - will track work on https://github.com/angular/angular/issues/6303 instead

**Closed by naomiblack** 2016-03-02 23:22 UTC
Labels: hotlist: Ionic, hotlist: sugar, type: bug
