### ISSUE TITLE
Data binding not work with Chinese property name?

### ISSUE THREAD

**Issue by xiexin36** [angular/angular#13265] opened 2016-12-06 06:34 UTC
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Here is my code: the template is: 
   `<div> 时间: {{DataContext.时间}} </div>`

Here '时间' is Chinese char which means time, and in the typescript file. I define a DataContext property.

    export class TestClass{
     @Input()
     DataContext:any;  }

But it not work, I got a error. Here is the error message, "Template parse errors: Parser Error: Unexpected token Lexer Error: Unexpected character {{时间}}......"

**Expected behavior**

I hope the data binding can work with Chinese property name.
**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

I really need it support Chinese char, because the json data from a old system, and all the data's properties use Chinese char. Without this,  I will have to convert all the json files.

**Please tell us about your environment:**

* **Angular version:** 2.0.X

Angular version: 2.1.1
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 Chrome version: 54.0.2840.99
* **Language:** [all |TypeScript X.X | ES6/7 | ES5]
TypeScript  2.1.0, ES5, I have tried 2.0.6.
* **Node (for AoT issues):** `node --version` =   
node --version=v6.9.1

**Comment by xiexin36** [comment] 2016-12-06 09:45
And also I hope [(ngModel)]="DataContext.时间" can support.

**Comment by vicb** [comment] 2016-12-06 19:21
Duplicate of https://github.com/angular/angular/issues/517

**Closed by vicb** 2016-12-06 19:21 UTC
Labels: comp: core & compiler, severity3: broken
