### ISSUE TITLE
[Request] Allow to use services in custom validators.

### ISSUE THREAD

**Issue by piernik** [angular/angular#25281] opened 2018-08-03 11:11 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
When defining validators with `new FormControl()` we can use only plain functions as validators. But very often in async validators we need to use services (like `ApiService`). Right now we have to use `bind` or define validator in component, which are very difficult in reactive form building.

But there is `Validator` interface which is very similar to `ValidatorFn` and could be used. Why not make it possible to use service with that (or new one) interface and pass service as `validationFn`.

## Expected behavior

```
@Injectable()
export class MyCustomValidatorService implements Validator {
   constructor(private apiService: ApiService) {}

   validate(c: AbstractControl): ValidationErrors | null;
}
```

`new FormControl(null, [MyCustomValidatorService])`

**Comment by mlc-mlapis** [comment] 2018-08-03 12:42
@piernik ... normally you have many custom validators + wrapped default ones (because of some additional functionality or just because you need your own data structures on returned errors) ... so have one or more services with those validators ... so call them `new FormControl(null, [this.myValidatorsService.customValidator(..., ..., ...)])`.

**Comment by kara** [comment] 2018-08-03 16:59
Closing as duplicate of #24981, please track on the existing issue

**Closed by kara** 2018-08-03 16:59 UTC
