### ISSUE TITLE
Cannot read property 'ngModuleDef' of undefined

### ISSUE THREAD

**Issue by Dig-Doug** [angular/angular#33373] opened 2019-10-24 15:28 UTC
#  bug report
### Affected Package
Not sure, possible the compiler.

### Is this a regression?
Yes, version `8.2.11` doesn't have this issue.

### Description
I'm running into an issue with `@ngrx/effects` that I haven't been able to solve. The project builds properly, however at runtime the module fails to load.

##  Minimal Reproduction
I've created a reproduction of the problem here with the `rules_nodejs` angular example:

```shell
cd /tmp
git clone git@github.com:Dig-Doug/rules_nodejs.git
cd rules_nodejs
git checkout ngrx-effects2
cd examples/angular
bazel run //src:devserver

# Open webpage, throws error

git checkout ngrx-effects-working
bazel run //src:devserver

# Page should load
```

##  Exception or Error
It seems like the module `EffectsModule.forRoot([])` is becoming undefined, though I can't figure out why.

```

Uncaught TypeError: Cannot read property 'ngModuleDef' of undefined
    at registerNgModuleType (core.umd.js:23236)
    at eval (core.umd.js:23247)
    at Array.forEach ()
    at registerNgModuleType (core.umd.js:23247)
    at new NgModuleFactory (core.umd.js:23360)
    at compileNgModuleFactory__POST_R3__ (core.umd.js:26791)
    at PlatformRef.bootstrapModule (core.umd.js:27013)
    at Object.eval (main.dev.ts:7)
    at Object.execCb (ts_scripts.js?v=1571446462766:1698)
    at Module.check (ts_scripts.js?v=1571446462766:885)
```

##  Your Environment
**Operating System:**

```

Ubuntu 19.10
  
```

**Output of `bazel version`:**

```

Build label: 1.0.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Oct 10 10:16:08 2019 (1570702568)
Build timestamp: 1570702568
Build timestamp as int: 1570702568
  
```

**Rules version (SHA):**

```

ad4be2c6f40f5af70c7edf294955f9d9a0222c8e2756109731b25f79ea2ccea0
  
```

** Angular version **

```
8.2.11 vs 9.0.0-next.10
```

**Anything else relevant?**

I originally filed this issue [here](https://github.com/bazelbuild/rules_nodejs/issues/1283) but after downgrading to an older angular version the issue went away (with the same rules_nodejs version) so I'm opening here.

Thanks,

Doug

**Comment by aflalves** [comment] 2019-11-06 13:11
@Dig-Doug I had this issue 2 weeks ago, but now it's gone after updating to the latest version.

**Comment by mhevery** [comment] 2019-11-20 22:23
@alxhub Not sure what the correct resolution is for this issue.

# Analisys

The `AppModule` is defined like so:

https://github.com/Dig-Doug/rules_nodejs/blob/0f8517702218862bf12f738a828a23cbc7ea388d/examples/angular/src/app/app.module.ts#L14-L24

**Comment by brandonroberts** [comment] 2019-11-21 14:17
This issue has been fixed with https://github.com/ngrx/platform/pull/2273, and the fix has been released in `8.5.2` . I verified the fix against the reproduction using the latest release.

**Comment by mhevery** [comment] 2019-11-21 17:43
Thank you @brandonroberts

**Comment by mhevery** [comment] 2019-11-21 17:46
Closing as resolved, @alxhub it may be a good idea ta have a separate issue for any compiler changes.

**Closed by mhevery** 2019-11-21 17:46 UTC
Labels: comp: bazel, comp: compiler, freq2: medium, severity3: broken, state: Root Cause Identified, type: bug/fix

**Comment by petebacondarwin** [comment] 2019-11-23 11:01
I looked into this, and it seems that since the original issue was posted we have fixed this problem. Probably via https://github.com/angular/angular/commit/002a97d8529b183bde37ac02eb93dd2866fa5740.

So there should be no problem with other similar libraries going forward.
