### ISSUE TITLE
_isNgModuleMetadata returning false for decorator factory

### ISSUE THREAD

**Issue by jshthornton** [angular/angular#12559] opened 2016-10-27 09:34 UTC
**I'm submitting a ...**  (check one with "x")

```
[ X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I have built an external angular 2 module which is compiled with typescript and imported into the app module. Currently I get this error `metadata_resolver.js:227 Uncaught Error: Unexpected value 'MyModule' imported by the module 'AppModule'``. This is caused by the fact that`_isNgModuleMetadata` is returning false due to:

```
DecoratorFactory
-----------------------
bootstrap: undefined
declarations: Array[3]
entryComponents: undefined
exports: undefined
id: undefined
imports: Array[1]
providers: undefined
schemas: undefined
__proto__: Object
```

Is not equating to an instance of NgModule.

**Expected behavior**
For the decorator factory to equal an instance of NgModule

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
- **Angular version:** 2.0.X
  @angular/core: 2.0.1
- **Browser:** 
  Chrome 54
- **Language:**
  Typescript compiled to ES6 with core-js shims
- **Node (for AoT issues):** `node --version` =  
  v6.6.0

**Comment by DzmitryShylovich** [comment] 2016-10-27 09:38
Aot/Jit? Pls provide working reproduction.

**Comment by gforceg** [comment] 2016-10-28 22:02
I'm getting a very similar error with a lib I created. I compiled it w/ ngc (for every .js file I have a .d.ts, .js.map, and .metadata.json). There were no compile errors.

When I bring the lib into angular-2-seed or angular-cli, and do an AoT build I get:
`Error: Unexpected value 'FontAwesomeModule' imported by the module 'SharedModule'`

The lib lives @ [https://github.com/gforceg/ng2-font-awesome](https://github.com/gforceg/ng2-font-awesome).

I've spent the past 3 days trying to get this to work and I know I'm doing something wrong I just don't know what... pulling my hair out hasn't helped.

**Comment by vicb** [comment] 2016-10-30 06:04
please try with 2.1.2 and report

**Comment by gforceg** [comment] 2016-10-31 16:02
The lib uses 2.1.2. I updated the angular-2-seed project ([specifically mgechev's angular-2-seed project](https://github.com/mgechev/angular-seed)) to use 2.1.2. AoT works if I leave my lib out. AoT also works when I import the ng2-bootstrap lib into my shared module so I think this is something that I am doing wrong or maybe an issue w/ tsc-wrapper.  It's only when I bring in my own reusable lib that I get errors.

I've even done a 'helloworld' lib (a module and a simple component) and I get the same error. I don't understand what I'm doing wrong because ngc doesn't show any output and the metadata.json files are being created. Here's my `tsconfig-aot-.json`

`
{
	"compilerOptions": {
		"declaration": true,
		"stripInternal": true,
		"emitDecoratorMetadata": true,
		"experimentalDecorators": true,
		"module": "commonjs",
		"moduleResolution": "node",
		"noEmitOnError": false,
		"noImplicitAny": true,
		"suppressImplicitAnyIndexErrors": true,
		"noImplicitReturns": true,
		"sourceMap": true,
		"target": "es5"
	},
	"exclude": [
		"node_modules"
	],
	"files": [
		"ng2-font-awesome.ts"
	],
	"angularCompilerOptions": {
		"genDir": "ngfactory"
	}
}
`

**Comment by vicb** [comment] 2016-10-31 16:24
Please adda minimal repro. Otherwise we will have to close the issue. Thanks.

**Comment by gforceg** [comment] 2016-10-31 16:37
I have a working helloworld lib. I didn't do anything differently in my build process so I guess I overlooked some code in my lib that is not statically analyzable.

Please close this one out.
I think issue #12645 is directly related to the problems that I am having.

Thanks.

**Comment by gforceg** [comment] 2016-10-31 17:16
FYI, when I used "npm link" to test the hello-world lib in my app, AoT failed w/ the same error 'Unexpected value `Error: Unexpected value 'FontAwesomeModule' imported by the module 'SharedModule'`.

But when I published the ng2-hello-world lib to npm and installed it in my app. AoT compilation worked.

It seems like I have to publish my libs to npm before they are ready if i want to test them out...

**Comment by gforceg** [comment] 2016-10-31 17:22
Nevermind, running `npm pack` worked. Should have thought about that before commenting further.

**Comment by gforceg** [comment] 2016-10-31 18:09
Everything works. I had an incomplete 'files' array in my package.json. Don't I feel silly!

**Closed** 2016-10-31 20:25 UTC
Labels: comp: core & compiler, flag: can be closed?, state: Need repro
