### ISSUE TITLE
Fragment routing is not working

### ISSUE THREAD

**Issue by vlavellauruit** [angular/angular#13636] opened 2016-12-22 13:43 UTC
I'm trying to add an anchor link on my current angular2 app. 
I've made the navigation first using the fragment attribute and because It didn't work I've referenced the fragment by using the router navigation. I couldn't make it work in both scenarios. 

I've been playing with https://angular.io/resources/live-examples/router/ts/eplnkr.html and doesn't seem to be working too. 

I followed step by step the tutorial on the routing documentation...

Can you provide any help?

**Comment by DzmitryShylovich** [comment] 2016-12-22 13:43
Duplicate of?

**Comment by Tragetaschen** [comment] 2017-03-07 12:44
`type: bug`? Feature?

**Comment by HauntedSmores** [comment] 2017-03-28 17:54
Any update on this? I also cant get fragments to work at all

**Comment by lizjulien** [comment] 2017-04-25 16:16
You must scratch the browser :

```
<a (click)="goTo('destination')">Go TO DIV</a>

<div id='destination'>
    <h2>Destination</h2>
</div>
```

Then in your component:

```
goTo(location: string): void {
    window.location.hash = location;
}
```

Tada !

**Comment by bjornharvold** [comment] 2017-05-02 07:47
I'm getting this too with v2.4.10. I would prefer not to have to "scratch the browser" if I can avoid it ;-)

**Comment by lizjulien** [comment] 2017-05-02 08:08
For now, it's the only one workaround, hope too it will be fixed, maybe with a *Service

**Comment by play-nirvik** [comment] 2017-05-19 12:42
@lizjulien This works on locally but, what if wanted to goto a particular section in a totally different page?

**Comment by bjornharvold** [comment] 2017-05-30 08:30
Also not working on latest version of Angular 4. What is the Angular team doing about this?

**Comment by play-nirvik** [comment] 2017-05-30 09:36
@bjornharvold : You can paste the below work around inside the `constructor `of the target component to make it work for now.

```
constructor( private router: Router ) {
    router.events.subscribe(event => {
        if (event instanceof NavigationEnd) {
            const tree = router.parseUrl(router.url);
            if (tree.fragment) {
	        const element = document.querySelector("#" + tree.fragment);
	        if (element) { element.scrollIntoView(element); }
            }
         }
    });
}
```

**Comment by bjornharvold** [comment] 2017-05-30 11:03
Thank you @play-nirvik . I've seen a few options but it should really be looked at by the Angular team. Anchor links not working on an html page is a pretty big [but small] thing.

**Comment by deantoni** [comment] 2017-07-04 00:45
any updates on this?

**Comment by jeanpaulattard** [comment] 2017-07-24 09:05
This problem is still present in version 4.3.1.

Here's a small plunker to demonstrate it. (Suggest to run the plunk in a separate window to see the url changes).

https://plnkr.co/edit/oX7QjaF40lfB2rW653bn?p=preview

**Comment by bjornharvold** [comment] 2017-07-24 09:07
Bump

**Comment by Nexeuz** [comment] 2017-09-05 23:14
Any Update for this?

**Comment by iuliust** [comment] 2017-09-11 00:16
Is there any workaround ? It doesn't seem to work for me either… It only works when I directly use an href attribute to navigate to an element that is declared within the same template 😞 …

Did it ever work for anyone ?

**Comment by louisl** [comment] 2017-09-27 19:48
Ran into this issue, using the answers here I came up with this for now. In my case I also had to give a little time for an element to show before I could scroll to it hence the little setTimeout hack.

```
  /**
   * Scroll to anchor
   *
   * @param {string} location Element id
   * @param {string} wait     Wait time milliseconds
   */
  public scrollToAnchor(location: string, wait: number): void {
    const element = document.querySelector('#' + location)
    if (element) {
      setTimeout(() => {
        element.scrollIntoView({behavior: 'smooth', block: 'start', inline: 'nearest'})
      }, wait);
    }
  }

this.scrollToAnchor('some-anchor', 100)
```

**Comment by micronyks** [comment] 2017-09-30 14:40
@louisl this hack is good. I liked it and working fine. 

This issue is not assigned to anyone so its been open since very long. 
I wish to get an official solution as soon as possible. 
Been waiting since long. 
Please guys do something for it.

**Comment by bjornharvold** [comment] 2017-10-22 08:16
Can someone on the Angular team please confirm that this is an issue and assign it a bug status? There has been no forward movement on this for months. Another ticket with the same issue. https://github.com/angular/angular/issues/12197

**Comment by vorotech** [comment] 2017-10-27 16:13
I think the issue https://github.com/angular/angular/issues/6595 is the one where the progress is tracked.

**Comment by tommyc38** [comment] 2018-05-22 17:43
Can someone please help me understand how fragments work with the RouterLinkDirective?  The Docs say they can be used for jumping around different areas of a page (https://angular.io/guide/router#routeroutlet) but it doesn't show an implementation.  Doesn't this solve this very issue?  Any help would be greatly appreciated, thanks!

**Closed** 2018-06-08 22:32 UTC
Labels: comp: router, freq3: high, severity3: broken, type: bug/fix

**Comment by kvimalkr55** [comment] 2019-01-31 07:45
its working but lading is problem

**Comment by prakash7755** [comment] 2019-02-01 06:52
> Ran into this issue, using the answers here I came up with this for now. In my case I also had to give a little time for an element to show before I could scroll to it hence the little setTimeout hack.
> 
> ```
>   /**
>    * Scroll to anchor
>    *
>    * @param {string} location Element id
>    * @param {string} wait     Wait time in milliseconds
>    */
>   public scrollToAnchor(location: string, wait: number): void {
>     const element = document.querySelector('#' + location)
>     if (element) {
>       setTimeout(() => {
>         element.scrollIntoView({behavior: 'smooth', block: 'start', inline: 'nearest'})
>       }, wait)
>     }
>   }
> 
> this.scrollToAnchor('some-anchor', 100)
> ```

Thanks lot you saved my job
