### ISSUE TITLE
Service Worker not registered

### ISSUE THREAD

**Issue by spock123** [angular/angular#31125] opened 2019-06-19 06:04 UTC
# 🐞 bug report
After upgrading to 8.0.1, Service Worker doesn't seem to register any longer. If I register it manually it works. Please note I'm NOT using IVY.

```
In Main Module
# This does NOT work any longer (used to, haven't changed anything)
ServiceWorkerModule.register('/ngsw-worker.js', { enabled: true })

```

But if I register manually during app bootstrap it works:

```
platformBrowserDynamic().bootstrapModule(AppModule).then(() => {
  if ('serviceWorker' in navigator && environment.production) {
    navigator.serviceWorker.register('/ngsw-worker.js');
  }
}).catch(err => console.log(err));

```

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 8.0.3
Node: 12.2.0
OS: darwin x64
Angular: 8.0.1
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, material, platform-browser
... platform-browser-dynamic, router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.3
@angular-devkit/build-angular     0.800.3
@angular-devkit/build-optimizer   0.800.3
@angular-devkit/build-webpack     0.800.3
@angular-devkit/core              8.0.3
@angular-devkit/schematics        8.0.3
@angular/cli                      8.0.3
@angular/pwa                      0.800.3
@ngtools/webpack                  8.0.3
@schematics/angular               8.0.3
@schematics/update                0.800.3
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.30.0

</code></pre>

**Comment by naturalfreak** [comment] 2019-06-19 06:57
#31061

**Comment by gkalpak** [comment] 2019-06-19 15:21
I assume this is a duplicate of #31061. (If not, please, open a new issue with more details (e.g. what browsers are affected, whether there are any error messages, a minimal reproduction, etc.).)

**Closed by gkalpak** 2019-06-19 15:21 UTC
Labels: comp: service-worker

**Comment by spock123** [comment] 2019-06-19 15:27
@gkalpak
 No that issue is about Safari.

Chrome is affected as well. Tested on Chrome/MacOS + Chrome/Android9
