### ISSUE TITLE
Service worker doesn't run until script execution finished

### ISSUE THREAD

**Issue by nasserghiasi** [angular/angular#21190] opened 2017-12-27 21:08 UTC
I spent whole a day to find this problem in my project.
The angular service worker doesn't start until all scripts including timeouts and intervals running finished, I need an interval works infinitely for regenerate hands positions in the clock but it's against angular service worker.

## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Expected behavior
I think service worker module should have config for this situation, like _waitForExcuteComplete_

## Environment

<pre><code>
Angular version: 5.1
Cli: 1.6

Browser:
- [ X] Chrome (desktop) version XX
- [ X] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ X] Firefox version XX
- [X ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 7
- Platform:  Mac

Others:

</code></pre>

**Comment by trotyl** [comment] 2017-12-28 04:43
Duplicate of #21186

**Comment by Splaktar** [comment] 2017-12-30 08:45
This does look like a duplicate of https://github.com/angular/angular/issues/20970 which has some good discussion and is being investigated.

**Closed** 2018-01-04 15:11 UTC
Labels: comp: service-worker, freq3: high, severity2: inconvenient, type: bug
