### ISSUE TITLE
form.value returns values of all form controls if form is disabled

### ISSUE THREAD

**Issue by exsoflowe** [angular/angular#25890] opened 2018-09-10 15:30 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

If I create disabled form and get form.value, I will got values of all form controls (entire/whole form model) like form is enabled.
If I have as minimus one enabled form control, form.value will return me only this enabled form control.

## Expected behavior

Before this case I supposed form.value always returns only enabled form controls.
(I mean form.value, not formControl.value)

## Minimal reproduction of the problem with instructions

Demo: https://stackblitz.com/edit/angular-all-form-is-disabled-but-can-get-value?file=src%2Fapp%2Fapp.component.ts

1. Create reactive form with one and more form controls.
2. Disable entire form: you can disabled each formControl or entire form (via `form.disable()`).
3. Get form.value: object contains all values of form controls.

## What is the motivation / use case for changing the behavior?

I can't find description of this behavior in official documentation.
Is it by design?

## Environment

<pre><code>
Angular version: 5.2.9, 6.0.0

</code></pre>

**Comment by kara** [comment] 2018-09-13 22:09
@exsoflowe This is actually by design. See [explanation here](https://github.com/angular/angular/issues/15982#issuecomment-327335108). Closing, as this currently works as intended.

**Closed by kara** 2018-09-13 22:09 UTC
Labels: comp: forms
