### ISSUE TITLE
 Bytecode generation has syntax issue and UTF-8 file encoding error

### ISSUE THREAD

**Issue by soorireddy** [angular/angular#30767] opened 2019-05-31 07:00 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "charset": "utf8",
    "sourceMap": true,
    **"alwaysStrict": true,
    "strict": true,**
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    **"moduleResolution": "Node",
    "module": "CommonJS",
    "target": "es5",**
    "typeRoots": [
      "node_modules/@types"
    ],
    **"lib": [
      "es5",
      "dom",
      "es2018"
    ]**
  }
}

tried with many permutations and combinations but no luck.

compiled code is failed  by  Microsoft  Windows App Certification Kit
runtime.741402d1d47331ce975c.js has JavaScript syntax or other problems.
main.554865c11d7a5138ceaf.js is not properly UTF-8 encoded. Re-save the file as UTF-8 (including Byte Order Mark).

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...

## 🔬 Minimal Reproduction

 https://stackblitz.com/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by trotyl** [comment] 2019-05-31 07:29
BOM should **NEVER** be used in Web application, if you're not targeting Web, please consider using own builder implementation or post-precessing.

**Comment by soorireddy** [comment] 2019-06-02 09:04
I use emitBOM to make it work but no luck.

{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "incremental":true,
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "module": "esnext",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "target": "es2015",
    **"emitBOM": true,
    "charset": "utf8",
    "alwaysStrict": true,
    "strict": true,**
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2018",
      "dom"
    ]
  }
}

**Comment by trotyl** [comment] 2019-06-02 13:33
It doesn't relates to TypeScript output, but Webpack output.

**Comment by trotyl** [comment] 2019-07-20 08:52
Duplicate of https://github.com/angular/angular-cli/issues/2077

---

Support question.

**Comment by pkozlowski-opensource** [comment] 2020-02-08 10:29
Closing as a duplicate of  angular/angular-cli#2077

**Closed by pkozlowski-opensource** 2020-02-08 10:29 UTC
Labels: comp: core, freq1: low, severity2: inconvenient, state: Needs repro, type: bug/fix
