### ISSUE TITLE
Add support for reloading routes

### ISSUE THREAD

**Issue by hartjus** [angular/angular#9105] opened 2016-06-09 00:07 UTC
* **I'm submitting a ...**
- [ ] bug report
- [X ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

**Current behavior**
Currently, there is no way to 'reload' an active route.

**Expected/desired behavior**
In Angular1, there exists a reload() method on the $route object, which would reload the route even if the location has not changed.  I think something like this in NG2 would be very helpful!

My scenario is that I have environment configuration in a JSON file that I need to load at runtime.  Specifically, after the application loads, but before the routes are rendered.  What I would like to happen is that the application is loaded, then I load my config, and then I **reload** the current route once my config is available.

http://stackoverflow.com/questions/37713711/angular2-rc1-load-route-router-outlet-after-data-has-loaded

Another option is to add another lifecycle hook.  Perhaps a `routerBeforeActivate` annotation?

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

* **Angular version:** 2.0.0-RC1
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
All
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5 | Dart] 
Typescript

**Comment by vsavkin** [comment] 2016-10-04 22:45
It seems the issue was opened before the last router rewrite. And it doesn't look like the issue still makes sense. I'm closing it. Please reopen it if you think it still makes sense.

**Closed by vsavkin** 2016-10-04 22:45 UTC
Labels: comp: router

**Comment by bisubus** [comment] 2016-10-05 03:56
@vsavkin Actually, the issue still makes sense with 3.x router, I would suggest to re-open it.

 I'm not sure that OP illustrates the valid case for route reloading.  But there were reasons to reload routes in AngularJS, they are still there in 2.0.

One of the beauty of resolvers that was inherited from A1 is that they are unwrapped on route component init and available on `ActivatedRoute` (e.g. `route.snapshot.data['resolved']`), no need to unwrap promises and observables manually. It works for alternating routes.  but when the same route is fired twice (even with different params), route resolvers fire but route component is not refreshed.

There are circumstances under which route component view needs to be refreshed (resetting forms, destructive non-Angular DOM code, etc). Currently [the manual](https://angular.io/docs/ts/latest/guide/forms.html#!#add-a-hero-and-reset-the-form) suggests a hacky way to do this for a regular component, `*ngIf="active"` and `this.active = false; setTimeout(() => this.active = true)`. It becomes even messier when packed into `router.events...`.

So yes, `reload` option for `routerLink` and `navigate*` methods is necessary and has its cases.

Empirically I've found that the route is considered 'dirty' if it gets a new object as relevant route object. The workaround I have to use for now is

```
const config = router.config.map((route) => Object.assign({}, route));
router.resetConfig(config);
router.navigate([`/reloaded`, { id }]);
```

It's ugly but it works.

**Comment by danishin** [comment] 2016-10-13 04:27
I, too, am having this issue (more specifically with an ability to refresh `resolve`s)

My scenario is the following: 
Let's say there is `/companies/:company_id/employees` route, where`CompaniesComponent` (`/companies`) shows all the companies associated with this account (thus, requires `resolve` that fetches companies) and `EmployeesComponent` (`/companies/:company_id/employees`) shows all employees under selected company (thus, requires `resolve` that fetches employees under selected company).

Now the problem is to route from `EmployeesComponent` to `CompaniesComponent`. If user navigated to`CompaniesComponent` first and then select company, then go to `EmployeesComponent`, all is good as `CompaniesComponent` correctly resolved all companies and when you navigate back to it, it still has them. The problem arises when, say, user goes to, say, `/companies/1/employees` page directly, without going through `/companies` page.

`resolve` for `CompaniesComponent` has been resolved correctly (as it is the parent route of `EmployeesComponent`), but `CompaniesComponent` never actually was instantiated so angular didn't have chance to inject `ActivatedRoute`, so `route.snapshot.data["companies"]` returns `undefined` when the user finally navigates back from `EmployeesComponent` to `CompaniesComponent`.

The same problem occurs, when, say, user switches company from `/companies/1/employees` to `/companies/2/employees`, the `resolve` for, say, `companyProfile` has already been resolved for `EmployeesComponent` (with company_id of 1) so it doesn't bother trying to re-resolve it, so end up having wrong data injected.

These issues, I think, have to do with an ability to purge `resolve` caches (?) or, more largely, reset route configs.

@bisubus 's workaround works but it'd be nice to support this as built-in feature.
