### ISSUE TITLE
routerLinkActive does not updates on router.navigate to the same route

### ISSUE THREAD

**Issue by andreyjamer** [angular/angular#42273] opened 2021-05-24 15:29 UTC
# Bug Report

### Description
If we have some components that use `router.navigate` for the same route but with empty object or null for `queryParams`, then `routerLinkActive` directive does mark links as active.
The use case to pass empty object is to pass some filters through query parameters to be able to share the link to the page.

## Minimal Reproduction
https://stackblitz.com/edit/angular-ivy-brrc3a
Here we have 2 components with service provided for each component. Service performs the navigation using:
```
this.router.navigate(['.'], {
      queryParams: {},
      relativeTo: this.route
});
```
After this any link will not be marked as active. If reload the page with preset url (ex: /one), then the link will be marked. But navigation to another route will not remove active state from the link.

## Your Environment

**Angular Version:**
<pre><code>
Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1002.0
@angular-devkit/build-angular   0.1002.0
@angular-devkit/core            10.2.0
@angular-devkit/schematics      10.2.0
@angular/cdk                    10.2.7
@angular/cli                    10.2.0
@angular/material               10.2.7
@schematics/angular             10.2.0
@schematics/update              0.1002.0
rxjs                            6.5.4
typescript                      4.0.3
</code></pre>

**Comment by atscott** [comment] 2021-05-24 23:36
Duplicate of #34795. As a workaround, you can change your service to navigate inside a `setTimeout` or `Promise.resolve.then(...)`: https://stackblitz.com/edit/angular-ivy-um7fof?file=src%2Fapp%2Fpage.service.ts

**Closed by atscott** 2021-05-24 23:36 UTC
Labels: comp: router

**Comment by Airblader** [comment] 2021-05-25 04:26
@atscott Are you sure about this? Without having looked into it, this issue sounds more like a problem of CD not triggering in this case.

**Comment by atscott** [comment] 2021-05-25 04:57
@Airblader yep, pretty sure. The navigation from the service is triggered before the previous one completes.

**Comment by andreyjamer** [comment] 2021-05-25 05:09
@atscott Yes, this issue a duplicate - the problem is the same. I didn't find it yesterday.
Workaround with `Promise.resolve` works fine. Thank you!
