### ISSUE TITLE
[angular-cli]: ngc generate invalid system/amd ngfactory modules

### ISSUE THREAD

**Issue by luboid** [angular/angular#20438] opened 2017-11-15 08:16 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

file:/aot/src/app/app.module.ngfactory.js
```javascript
System.register(["@angular/core", "./app.module", "./app.component", "./heroes/hero-list.component.ngfactory", "./heroes/hero-detail.component.ngfactory", "./login.component.ngfactory", "./compose-message.component.ngfactory", "./not-found.component.ngfactory", "./app.component.ngfactory", "@angular/common", "@angular/platform-browser", "@angular/animations/browser", "@angular/platform-browser/animations", "@angular/forms", "./heroes/hero.service", "./auth.service", "./auth-guard.service", "@angular/router", "./selective-preloading-strategy", "./can-deactivate-guard.service", "@angular/animations", "./dialog.service", "./heroes/hero-list.component", "./heroes/hero-detail.component", "./login.component", "./compose-message.component", "./app-routing.module", "./not-found.component", "./heroes/heroes-routing.module", "./heroes/heroes.module", "./login-routing.module"], function (exports_1, context_1) {
    "use strict";
    /**
    * @fileoverview This file is generated by the Angular template compiler.
    * Do not edit.
    * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
    * tslint:disable
    */ 
    var __moduleName = context_1 && context_1.id;
    var , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , AppModuleNgFactory;
    return {
        setters: [
            function (_1) {
                 = _1;
            },
            function (_2) {
                 = _2;
            },
            function (_3) {
                 = _3;
            },
            function (_4) {
                 = _4;
            },
            function (_5) {
                 = _5;
            },
            function (_6) {
                 = _6;
            },
            function (_7) {
                 = _7;
            },
            function (_8) {
                 = _8;
            },
            function (_9) {
                 = _9;
            },
            function (_10) {
                 = _10;
            },
            function (_11) {
                 = _11;
            },
```

## Expected behavior

valid modules

## Minimal reproduction of the problem with instructions

https://github.com/luboid/angular-ngc-tests

```cmd
"node_modules/.bin/ngc" -p tsconfig-aot.json
```

## What is the motivation / use case for changing the behavior?

valid modules

## Environment

<pre><code>
Angular version: 5.0.1

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v6.11.3
- Platform:  Win 10

Others:

</code></pre>

**Comment by ericmartinezr** [comment] 2017-11-15 10:33
What TS version are you using?

**Comment by luboid** [comment] 2017-11-15 10:43
2.4.2

**Comment by trotyl** [comment] 2017-11-16 12:04
Duplicate of #20057

**Comment by luboid** [comment] 2017-11-16 13:06
One possible workaround is to compile with ngc  to module:es2015 and next step is to compile with tsc  es2015 code to system/amd (tsconfig:allowJs=true), this work for me for now

**Comment by luboid** [comment] 2018-01-29 10:39
Is there plans to fix this, some people working with SystemJS

**Comment by JoostK** [comment] 2020-03-15 23:06
This was caused [by a TypeScript bug](https://github.com/angular/angular/issues/20057#issuecomment-340901695) that has since been resolved.

**Closed by JoostK** 2020-03-15 23:06 UTC
Labels: comp: compiler, freq1: low, severity3: broken, type: bug/fix
