### ISSUE TITLE
More dynamic i18n lookups

### ISSUE THREAD

**Issue by thelgevold** [angular/angular#13990] opened 2017-01-18 16:29 UTC
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```
I am logging a feature request to support more dynamic i18n lookups. 

**Current behavior**
From what I can tell the current i18n approach can only target elements with a static reference in the markup.
(e.g. `<div i18n="meaning|description">English Text</div>`)

**Expected behavior**
One of the challenges I see with this is building a data driven ui with translations. If you come from the `ng-translate` world it's not uncommon to loop over a list of language keys and do lookups to resolve translated values.

It's not clear to me how to replicate this behavior using i18n in angular.
It would be nice if i18n allowed us to specify the keys based on data binding instead of hard coded references in the markup.

Example:
```
<div *ngFor="let key of keys">
    <div i18n="@@{{key}}"></div>
</div>
```

It looks like the ability to set your own @@keys was added in 4.0. Thinking this key is perfect for the lookup, but it would need to be generated based on bindings.

This would also assume that we are allowed to manually create the xlf file instead of relying on the i18n compiler cli tool to generate it. The list of keys could potentially come from an api and would not be a fixed list. There would be no way for the generator to know the set until runtime. 

I still think this can be made compatible with AoT. It would require one more level of indirection in the translation lookup though.

Instead of 
`var currVal_2 = inlineInterpolate(1, ‘Welcome ', this.parentView.context.firstNameName, '');`

You could maybe have
`var currVal_2 = inlineInterpolate(1, lookupKey('@@Welcome'), this.parentView.context.firstNameName, '');`

**What is the motivation / use case for changing the behavior?**
The motivation is a more flexible translation experience.

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by thelgevold** [comment] 2017-01-24 19:31
Here's a more practical scenario where this applies:

Imagine an error message banner where you potentially want to display a number of different error messages.

Given a potentially large set of messages it's important that the content of the banner is data driven. In ng-translate implementations I would simply pass a resource key to the component and do a lookup against the current resource bundle. 

In Angular's i18n implementation I am not sure how to achieve this. The only way I can think of is defining markup for every error message combination and `ngIf` against some condition.

```
<div *ngIf="statusCode="404">Error Message-1</div>
<div *ngIf="statusCode="500">Error Message-2</div>
......
......
<div *ngIf="statusCode="123">Error Message-n</div>
```

Does this seem like a reasonable request? I apologize in advance if I am missing something obvious here. 

cc: @vicb @mhevery @robwormald

**Comment by vicb** [comment] 2017-01-24 21:46
The plan is to have `__()` available in the TS code so that you can translate your TS files

```ts
const errors = {
  '404': __('not found'),
  '500': __('server error'),
  // ...
}

```

Not ETA yet.

If this answer your q, please close this issue, there is already one opened (don't have the ref handy)

**Comment by thelgevold** [comment] 2017-01-24 22:05
@vicb Ok, thanks. I think this looks very promising.
One final question before closing: Will this support variable expressions in strings as well? Similar to how you can use interpolation expressions in template i18n?

**Comment by thelgevold** [comment] 2017-01-24 22:08
`{404': __('${myVar} not found')}`

**Comment by thelgevold** [comment] 2017-03-03 15:57
@vicb Do you have an update on when the `__()` might be supported in i18n?

**Comment by ocombe** [comment] 2017-03-20 14:19
Hello, I'm closing this because it's a duplicate of https://github.com/angular/angular/issues/11405 (continue the discussion there if you need).

I've started working on this and you can expect it for angular 4.1 or 4.2.

The variable expressions in strings is under consideration and it is something that I'm pushing for. We will definitively add it since it is something that is needed for Google as well, but we are not sure yet if it will be in the first implementation or if we'll add it later.

**Closed by ocombe** 2017-03-20 14:19 UTC
