### ISSUE TITLE
Validator executes several times on initial component load

### ISSUE THREAD

**Issue by cknightdevelopment** [angular/angular#27938] opened 2019-01-04 21:18 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/forms

### Is this a regression?

  I don't think so.

### Description

 The first time a form group is loaded for reactive forms, the validators run multiple times (3 times for me).

## 🔬 Minimal Reproduction

 
[StackBlitz example](https://stackblitz.com/edit/angular-cfyhde?embed=1&file=src/app/app.component.ts)

See the console log to see how many times the validator is run.

## 🔥 Exception or Error
n/a

## 🌍  Your Environment

**Angular Version:**
see StackBlitz
<pre><code>7.0.1</code></pre>

**Anything else relevant?**

**Comment by ChrisDahmCS** [comment] 2019-01-08 22:43
This is happening because the validator checks itself when added to the FormControl, and when the associated directives run their ngOnChanges methods.

1) [Docs for adding Validator during FormControl constructor](https://github.com/angular/angular/blob/master/packages/forms/src/model.ts#L951) - run it's updateValueAndValidity method.

2) [Link for when the formGroupDirective calls _updateTreeValidity via ngOnChanges](https://github.com/angular/angular/blob/master/packages/forms/src/directives/reactive_directives/form_group_directive.ts#L250-L261) - ultimately calls each child's updateValueAndValidity method.

3) [Docs for when the formControlName directive runs _setupControl from it's ngOnChanges](https://github.com/angular/angular/blob/master/packages/forms/src/directives/reactive_directives/form_control_name.ts#L276-L283) - with this one, the addControl method ultimately runs the named control's updateValueAndValidity method.

Disclaimer: I found these partially by rooting through the source code, but stopped after a couple minutes and just did `console.trace('trace-me');` in the validator to follow the stack trace (ezpz way).


As a side wonder; I believe I saw an issue for this in the past, but couldn't quite find it. I remember it resolving as something with how the lifecycle has to run etc etc. Does anyone else remember this (or know what issue it was), or am I crazy?

**Comment by kara** [comment] 2019-01-08 23:48
@ChrisDahmCS You're not crazy. I think you're talking about this comment in this issue: 

https://github.com/angular/angular/issues/21500#issuecomment-358833667

@cknightdevelopment Three times is expected, but we have an open ticket to see if we can reduce this. So I'm going to close this as a dupe of #21500.

**Closed by kara** 2019-01-08 23:48 UTC
Labels: comp: forms

**Comment by ChrisDahmCS** [comment] 2019-01-08 23:58
Wow, great find @kara, thank you!
