### ISSUE TITLE
Angular2 router : Changing route doesn't load the component for first time

### ISSUE THREAD

**Issue by devin6391** [angular/angular#8166] opened 2016-04-21 11:22 UTC
I am changing the route of angular2 application from '/' to '/xyz'. For 'xyz' I have made a component named XYZComponent. This XYZComponent implements a hook for router lifecycle named "CanActivate". In this hook I am changing the title of the page for new route.
@CanActivate((next, prev) => { 
   document.title = "mysite | xyz" 
   return true; 
})
Then I implement OnInit for this component and call the method "ngOnInit()". In this method I am calling the server to give me some data. This data is stored in a variable named xyzData, which is binded to the template. My template is:

```
<div class="xyzComp">
 <p>{{xyzData.msg}}</p>
</div>
```
OnInit is:
```
ngOnInit(){
    console.log("xyz component init");
    this._myRestfulService.getXyz()
        .subscribe(data => {
            console.log("success",data);
            this.xyzData = data;
        }, err => {
            this.xyzData = {msg:"cannot get data"};
            console.log("error", err);
        });
}
```
Changing the route is done by calling _route.navigate(["XYZ"]) from the click of a button named xyzBtn, which is present in the header of my app. The header is constant for all the routes.
Problem is that when I click on xyzBtn for first time it calls only whatever written in @CanActivate decorator of XYZComponent. Next time when I click xyzBtn,@CanActivate is not called but this time ngOnInit() is called.
Please help me on this. This problem occurs only when I deploy my code on server. The deployment server is NGINX server. On nginx server we have configured to ignore frontend routes.
However my code works perfectly well on development server which is a npm module named lite-server.

**Comment by zoechi** [comment] 2016-04-21 11:30
> call the method "ngOnInit()".

sounds weird. I think this requires at least a Plunker that allows to reproduce.

GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by devin6391** [comment] 2016-04-21 11:59
I think its a bug of Angular2. It might be crashing while deciding which lifecycle hook to address first - router or component. The documentation of CanActivate lifecycle hook of router is also not very clear on how it interacts with lifecycle of a component.

**Comment by zoechi** [comment] 2016-04-21 12:22
Would probably be easy to know if you would provide a Plunker that demonstrates what you're doing.

**Comment by vaudy** [comment] 2016-04-21 12:58
I think ngOnInit is called for components only

**Comment by devin6391** [comment] 2016-04-21 12:58
Plunker : https://plnkr.co/edit/E4HNXEjaIP7th77UE4dK?p=preview

**Comment by brandonroberts** [comment] 2016-04-21 13:23
@devin6391 that plunker doesn't work: http://plnkr.co/edit/oZzjAH34WJ1R14z0Xtbl?p=preview

**Comment by devin6391** [comment] 2016-04-21 13:28
One more thing, I am making a bundle file from systemjs builder before deploying. Could that raise issue?

**Comment by brandonroberts** [comment] 2016-04-21 13:30
It shouldn't. Usually if your lifecycle hooks aren't being called until you manually trigger some action, your polyfills aren't setup correctly. Are you including the angular2 polyfills in a script tag in your index.html on deployment?

**Comment by zoechi** [comment] 2016-04-21 14:42
See also http://stackoverflow.com/questions/36767520/angular2-router-changing-route-doesnt-load-the-component-for-first-time (I updated the Plunker to make it work https://plnkr.co/edit/YwPXR5YyIy3OFkOnBlZo?p=preview)

**Comment by devin6391** [comment] 2016-04-22 11:10
Hi, I have also done some debugging. The areas where I find Angular2 incompatible are:
1) Cannot do minification. We have to use .dev version. This need to be fixed.
2) The doc of Angular2 doesn't explain how routing lifecycle affect component lifecycle and vice versa.

Few problems are there with system js also. Although this is not the place to post SystemJs issues but there is some kind of problem when system js bundles up the angular files in module.

I think with time these problems will get resolved, and we are definitely waiting for a stable version-1 of angular2

**Comment by zoechi** [comment] 2016-04-22 11:16
For 1) see https://github.com/angular/angular/search?q=minified&state=open&type=Issues&utf8=%E2%9C%93

**Comment by ribizli** [comment] 2016-05-06 09:59
I had the same problem, and after ca. 4 hours investigation I've found that the problem was caused by systemjs/dist/system-polyfills.js. I removed this dependency and it works now at least in Chrome (didn't try others)

**Comment by jpleclerc** [comment] 2016-05-06 14:39
@ribizli I remove system-polyfills.js and it solved the problem for me too. ty!

**Comment by JSMike** [comment] 2016-05-11 23:08
Thx, I couldn't figure out why my component lifecycle wasn't starting, removing the polyfill worked for me as well.

**Comment by remohy1** [comment] 2016-06-24 17:17
Removing system-polyfills.js worked for me

**Comment by azjkjensen** [comment] 2016-08-05 18:04
I am having this same issue, but using webpack and angular2-universal. Any ideas of what could be happening?

**Comment by kwgainey** [comment] 2016-08-09 19:21
+1 for removing system-polyfills.js. Was driving me crazy for a while. Anyone experience side-effects of removing system-polyfills.js?

**Comment by vsavkin** [comment] 2016-10-04 22:57
It seems the issue was opened before the router rewrite. And it doesn't look like the issue still makes sense. I'm closing it. Please reopen it if you think it still makes sense.

**Closed by vsavkin** 2016-10-04 22:57 UTC
Labels: comp: router

**Comment by hari30OJ** [comment] 2018-01-31 11:23
@azjkjensen Can you share your solution if you found one. I am using webpack for building. 
Any help would be appreciated. Thanks!!

**Comment by azjkjensen** [comment] 2018-01-31 16:40
@hari30OJ unfortunately I'm no longer a part of the project and I can't remember what the fix was. I'm sorry.

**Comment by Velunce** [comment] 2018-07-08 09:48
Cut it to another folder and then cut back to src folder......
It will works.
