### ISSUE TITLE
DatePipe filter is giving hours greater than 24 - angular 2

### ISSUE THREAD

**Issue by ThirupathRao** [angular/angular#37403] opened 2020-06-02 20:25 UTC
Below snippet is giving the hours value greater than 24 (Jun 02, 2020 24:17)
`                <label class="label-value">{{1591037256657 | date:'MMM dd, y HH:mm'}}</label>
`
I have even tried passing Date() instead of milliseconds, that also did not help. Please find the anuglar dependencies which I am using.

<pre>"dependencies": {
"@angular/common": "2.0.0",
"@angular/compiler": "2.0.0",
"@angular/core": "2.0.0",
"@angular/forms": "2.0.0",
"@angular/http": "2.0.0",
"@angular/platform-browser": "2.0.0",
"@angular/platform-browser-dynamic": "2.0.0",
"@angular/router": "3.0.0",
"bootstrap": "3.3.6",
"core-js": "2.4.1",
"font-awesome": "4.7.0",
"paysafe-admin-shell-commons": "1.3.3",
"primeng": "1.1.4",
"ng2-ckeditor": "1.2.2",
"rxjs": "5.0.0-beta.12",
"systemjs": "0.19.37",
"zone.js": "0.6.21"
}</pre>
I did google lot of time for the issue before asking here, but nothing helped. I have tried applying datePipe for same milliseconds in online for other angular version, it worked. Currently I am working on a big project and upgrading the version wont be feasible solution. Is there any way we can make this work as it suppose to ?

Thank you for your time.

**Comment by ThirupathRao** [comment] 2020-06-02 20:39
@ericmartinezr is this the known issue in angular2 or am I doing something wrong? could you please suggest?

**Comment by pkozlowski-opensource** [comment] 2020-06-02 20:48
> is this the known issue in angular2 or am I doing something wrong?

Angular 2 was using _very_ different APIs to format dates / time (Intl API) and this was changed years ago. I can't reproduce in a recent version: https://stackblitz.com/edit/angular-ivy-7m8wbz

I'm sorry but we are not patching old versions (and Angular 2 is several years old).

**Comment by ThirupathRao** [comment] 2020-06-02 20:57
Thank you @pkozlowski-opensource for the quick reply.  But is this really an existing issue in anuglar2 now also? can I update any of the dependencies to get rid of this?

**Comment by LukeFarrawell** [comment] 2020-06-03 03:35
Without diving into the source code of Angular 2.0, this might be a browser based bug.

Are you seeing the 24:17 in all browsers or just chromium based browsers?

I discovered chromium has a bug in its date formatting a while ago, I went to submit a bug report but it already existed. When using `date.toLocalTimeString` and passing in the options of { hour12: false }, the output shows 24:XX instead of the expected 00:XX.

See the below example.
```JavaScript
let date = new Date();
date.setHours( 0, 15, 15 );
date.toLocaleTimeString( "en", { hour12: false } );
// output: "24:15:15"
```

You can track this bug [here](https://bugs.chromium.org/p/chromium/issues/detail?id=1084504&q=hour12&can=2)

**Comment by ThirupathRao** [comment] 2020-06-03 04:47
It is working fine in Firefox. 
Do we have any workaround for this issue in chrome?

**Comment by LukeFarrawell** [comment] 2020-06-03 05:42
I don't think there is an easy workaround, I think you will either need to switch to 12 hour time temporarily, wait for chromium to fix the bug, update to a more recent angular version or write your own date / time formatter.

Lets hope the chromium bug gets fixed soon.

Newer versions of angular don't have this issue.

I think this issue can be closed as its not a problem with angular.

**Comment by pkozlowski-opensource** [comment] 2020-06-03 07:30
Thnx for the summary @LukeFarrawell - I agree with your assessment.

**Closed by pkozlowski-opensource** 2020-06-03 07:30 UTC
