### ISSUE TITLE
Angular 2 and mathjax

### ISSUE THREAD

**Issue by kokosakyi** [angular/angular#17416] opened 2017-06-12 10:11 UTC
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I run mathjax code in my component html file such as $$ 2^{x + 2 } $$. and I get

Template parse errors:
Unexpected character "EOF" (Do you have an unescaped "{" in your template? Use "{{ '{' }}") to escape it.) ("
</div>[ERROR ->]"): ng:///AppModule/ConcreteDesignComponent.html@165:6
Invalid ICU message. Missing '}'. ("

I try escaping the single curly braces with {{ "{" }} but don't get the math equations rendered.

**Expected behavior**

The code $$ 2^{x + 2 } $$ should just render the latex equation in the browser.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by pkozlowski-opensource** [comment] 2019-03-09 15:13
This is a duplicate of #11859 - the long story short that currently you can't have un-escaped curly (`{`) as it has a meaning for i18n. Unfortunately escaping  `{` is not trivial today and an easier escape is tracked in #11859. Closing as a duplicate.

**Closed by pkozlowski-opensource** 2019-03-09 15:13 UTC
Labels: comp: core & compiler, type: feature
