### ISSUE TITLE
$localize followed by longish `-delimited concatenated string leads to concatenated part being duplicated & non-localized

### ISSUE THREAD

**Issue by haqer1** [angular/angular#41127] opened 2021-03-09 04:23 UTC
# 🐞 bug report

### Affected Package

 The issue is in $localize

### Description

 $localize followed by longish `-delimited concatenated string leads to concatenated part being appended (in non-translated wording) to the string rendered

## 🔬 Minimal Reproduction
<pre><code>
let note = $localize`:@@note:There was a something or other`
                    + ` (link_start)(link_text)(link_end) (something).`;
</code></pre>

## 🔥 Exception or Error
For instance for tr this is compiled to:
<pre><code>
let note = "(link_start)(link_text)(link_end) (bir şey) bir ya da başka bir şey oldu."
+ ` (link_start)(link_text)(link_end) (something).`; // The part after + is duplicated & non-localized
</code></pre>

While for English this is compiled to:
<pre><code>
let note = "There was a something or other" // this part is wrong, but the end result ends up being right
                    + ` (link_start)(link_text)(link_end) (something).`;
</code></pre>

## 🔬 Work-around currently used
<pre><code>
let note = $localize`:@@note:There was a something or other
(link_start)(link_text)(link_end) (something).`;
</code></pre>

I.e., since concatenation isn't (yet) supported, and parameterized method invocation as in https://github.com/angular/angular/issues/36937 doesn't work out, just keep everything within 1 non-concatenated `-delimited string, & replace ' ' with '\n' to keep line length reasonable where needed (given that they are equivalent in HTML).

Drawback: additional lines start without indentation, negatively affecting legibility.

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.1.0
</code></pre>

**Anything else relevant?**
This matters for strings causing the line to go past 100 characters, while a developer tries to comply with a 100-character max line length, for instance.

**Comment by petebacondarwin** [comment] 2021-03-09 08:06
Duplicate of #41128 36937

**Closed by petebacondarwin** 2021-03-09 08:06 UTC

**Comment by haqer1** [comment] 2021-03-09 11:38
> Duplicate of #41128 36937

For the record: the first 1 of the aforementioned seems irrelevant, whereas #36937 is related, although the details & nuances vary.

**Comment by petebacondarwin** [comment] 2021-03-09 12:05
Yes, sorry, not sure how that other issue number appeared there. I think it was some autocomplete in the GitHub API!

**Comment by petebacondarwin** [comment] 2021-03-09 12:09
And just to be clear. The example provided here would never work given the design of `$localize`. 

```ts
let note = $localize`:@@note:There was a something or other`
                    + ` (link_start)(link_text)(link_end) (something).`;
```

Note that `$localize` is being used as a [template literal tag handler](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals#tagged_templates). The syntax is that the handler only applies to the backtick string which it prefixes. So this example is equivalent to:

```ts
const part1 = $localize`:@@note:There was a something or other`;
const part2 = ` (link_start)(link_text)(link_end) (something).`;
let note = part1 + part2;
```

Here one can see that the value of `part2` is not tagged with `$localize`.
