### ISSUE TITLE
I can't create dynamic FormGroup manually

### ISSUE THREAD

**Issue by MuhammadAbdelsalam** [angular/angular#35190] opened 2020-02-06 16:49 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

this code not work fine at first time page load and fire exception

## 🔬 Minimal Reproduction

component.ts
<pre><code>

    this.contactForm = new FormGroup({
      name: new FormControl(),
       phones: new FormArray([new FormGroup({Phone: new FormControl('')})])
         });

</code></pre>

component.html

```html
<div formArrayName="phones">
            <div *ngFor="let item of phones.controls; let phoneIndex = index" [formGroupName]="phoneIndex">
                <label>
                    Phone: <input formControlName="phone" />
                </label>
                <button type="button" (click)="deletePhone(phoneIndex)">Delete Phone</button>
            </div>
            <button type="button" (click)="addPhone()">Add Phone</button>
        </div>
```
## 🔥 Exception or Error
<pre><code>

Cannot find control with path: 'phones -> 0 -> phone'
</code></pre>

## 🌍  Your Environment
Angular CLI: 8.3.23
Node: 12.14.1
OS: win32 x64

**Anything else relevant?**
if I used formbuilder, it will work fine 

<pre><code>
 this.contactForm = this.fb.group({
      name: '',
      address: '',
      note: '',
      phones: this.fb.array([this.fb.group({phone:''})])
    });
</code></pre>

**Comment by Airblader** [comment] 2020-02-06 16:52
Duplicate of #38159

**Comment by MuhammadAbdelsalam** [comment] 2020-02-06 17:09
I opened old one by mistake, so I closed it thanks AirBlader

**Comment by rmeans** [comment] 2020-02-06 19:54
We totally have this same issue. We were alerted to it when testing in Chrome 80 Beta. The issue appears to be within the the _find function on the AbstractControl that is called withing the get(path: Array<string | number> | string) function. In that _find function it appears to break down in the .reduce.

```
function _find(control: AbstractControl, path: Array<string|number>| string, delimiter: string) {
  if (path == null) return null;

  if (!(path instanceof Array)) {
    path = (<string>path).split(delimiter);
  }
  if (path instanceof Array && (path.length === 0)) return null;

  return (<Array<string|number>>path).reduce((v: AbstractControl | null, name) => {
    if (v instanceof FormGroup) {
      return v.controls.hasOwnProperty(name as string) ? v.controls[name] : null;
    }

    if (v instanceof FormArray) {
      return v.at(<number>name) || null;
    }

    return null;
  }, control);
}
```
Through some other testing I could prove that using this.form.get('xcontrol') would return null, but if we called this.form.controls['xcontrol'] it is present.

Unfortunately from the html it is not possible to control how the directives get the controls. We were able to work around it creating an explicit formGroup instead of relying on formGroupName to create the formGroup. An example with your code would be:

```
<div formArrayName="phones">
            <div *ngFor="let item of phones.controls; let phoneIndex = index" [formGroup]="phones.controls[phoneIndex]">
                <label>
                    Phone: <input formControlName="phone" />
                </label>
                <button type="button" (click)="deletePhone(phoneIndex)">Delete Phone</button>
            </div>
            <button type="button" (click)="addPhone()">Add Phone</button>
        </div>
```

Honestly, I feel like the issue is really a Chrome 80 issue, almost like a rendering problem. However, our app is too complicated to use to submit a bug to the chromium team, and I can't reproduce it out of the context of our app. I am glad to see others are experiencing this also.

**Comment by cur3n4** [comment] 2020-02-06 21:11
We are experiencing the same issue since Chrome 80. We have seen that it is a sporadic behaviour, it doesn't always return null. Our temporary fix is traversing all the controls in the form group and do a form.get on each of them, afterwards the get method will work as expected.

**Comment by wenrick** [comment] 2020-02-06 21:28
We are having the same issue with Chrome 80 when trying to load several of our Reactive forms.

> Error: Cannot find control with name: '_nameOfControl_'

 where _nameOfControl_ is the first formControl on the form or the first to be referenced in TypeScript after creating the FormGroup. Chrome 79 and earlier, IE, Edge, and Firefox all work as expected.

I tried upgrading angular to the latest, 8.2.14 from an earlier 8.2.x revision and that made no difference.

**Comment by swftvsn** [comment] 2020-02-07 04:34
We're having this also, only on chrome 80.

It's quite a mystery as this fails:
```
this.form = new FormGroup({
  'name': new FormControl('', [])
})
this.form.get('name').valueChanges.pipe(.....
```
with error `Cannot read property 'valueChanges' of null`
Could someone from angular team chime in what we could do about it?

We're going to upgrade one of our apps to angular 9 to see if that fixes it.

**Comment by so-oki** [comment] 2020-02-07 04:57
We have similar issue with Chrome 80.
> Error: formGroup expects a FormGroup instance. Please pass one in.

The error message is different but I think root cause is same.
This is the code link.
https://stackblitz.com/edit/angular-8exdsq

When we update angular to 9, the problem less likely to occur.
But if we increase FormGroup, the problem occurs again.

**Comment by xdevnull** [comment] 2020-02-07 09:15
This should be marked as critical.

**Comment by mix5003** [comment] 2020-02-07 10:57
@MuhammadAbdelsalam i think it becuase you use incorrect name
when you use in template you use `<input formControlName="phone" />` (it `phone` in all small case)
but in component you use `new FormGroup({Phone: new FormControl('')})` (it `Phone` with capital letter)
that is why you can use form builder and it work fine. becuase in form builder you use `phone`

**Comment by adam-marshall** [comment] 2020-02-07 11:01
See related bug report for Chrome 80 https://bugs.chromium.org/p/chromium/issues/detail?id=1049982 - _find method in forms.js uses Array.reduce

**Comment by swftvsn** [comment] 2020-02-07 11:20
so a quick fix would be to release a version of angular that does not use `Array.reduce()`. 

How long will it take for the chromium fix to trickle down for end users?

**Comment by shravan20084312** [comment] 2020-02-07 14:25
Has anyone found a workaround to the reported issue? We tried switching the chrome flags (from a user standpoint), to make the version of chrome look like 78 or 79. This did not solve the issue.

**Comment by xdevnull** [comment] 2020-02-07 17:42
Since the core issue comes from Array.reduce. I tried to override the function in chrome 80. I can't see the issue occurs again.

``
//https://stackoverflow.com/questions/4900436/how-to-detect-the-installed-chrome-version
function getChromeVersion () {     
  var raw = navigator.userAgent.match(/Chrom(e|ium)\/([0-9]+)\./);
  return raw ? parseInt(raw[2], 10) : false;
}


//https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/reduce
// reduce pollyfill
if(getChromeVersion() === 80) {
  Object.defineProperty(Array.prototype, 'reduce', {
    value: function(callback /*, initialValue*/) {
      if (this === null) {
        throw new TypeError( 'Array.prototype.reduce ' + 
          'called on null or undefined' );
      }
      if (typeof callback !== 'function') {
        throw new TypeError( callback +
          ' is not a function');
      }
      var o = Object(this);
      var len = o.length >>> 0;      
      var k = 0; 
      var value;

      if (arguments.length >= 2) {
        value = arguments[1];
      } else {
        while (k < len && !(k in o)) {
          k++; 
        }
        if (k >= len) {
          throw new TypeError( 'Reduce of empty array ' +
            'with no initial value' );
        }
        value = o[k++];
      }
      while (k < len) {
        if (k in o) {
          value = callback(value, o[k], k, o);
        }  
        k++;
      }
      return value;
    }
  });
}

**Comment by xdevnull** [comment] 2020-02-07 17:45
As a workaround i tried to pollyfill Array.reduce in Chrome 80 only. The issue no longer occurs. 
Used the same code posted by @so-oki 

Changes were made in ```main.ts``` file

https://stackblitz.com/edit/angular-u8dcza?file=src%2Fmain.ts

**Comment by chimurai** [comment] 2020-02-07 22:43
Linking to workaround: https://github.com/angular/angular/issues/35219#issuecomment-583425191

**Comment by MuhammadAbdelsalam** [comment] 2020-02-08 02:45
Thanks @mix5003, its true.

**Comment by rmeans** [comment] 2020-02-11 14:50
The bug report @adam-marshall pointed out does appear to be the root cause of the issue. The chromium team found the issue and has reverted change. Not quite sure when and how they will push out the fix. For the time being, there is a polyfill in the bug report https://bugs.chromium.org/p/chromium/issues/detail?id=1049982 that can be used.

**Comment by cexbrayat** [comment] 2020-02-12 08:01
https://github.com/angular/angular/pull/35349 landed, so we'll have a new Angular patch version that we can use that does not rely on `Array.reduce` (while we are waitin for the next Chrome version that should fix the underlying issue).

**Comment by cexbrayat** [comment] 2020-02-14 08:01
Closing, as v9.0.1 includes a fix, and the latest Chrome release does not have the underlying issue anymore.

**Closed by cexbrayat** 2020-02-14 08:01 UTC
Labels: comp: forms
