### ISSUE TITLE
data attributes with interpolation are treated as inputs?

### ISSUE THREAD

**Issue by ArielGueta** [angular/angular#49779] opened 2023-04-11 10:58 UTC
### Which @angular/* package(s) are the source of the bug?

compiler

### Is this a regression?

No

### Description

The following code compiles well and adds the `data-foo` attribute:

```html
<app-bar data-foo="1">
```

The following code throws a compiler error:

```html
<app-bar data-foo="{{ value }}">
```

It seems like Angular treated the second variation as an `Input`. I know that we can do `[attr.data-foo]="value"` but this behaviour is very confusing. From what I can understand, if you have an interpolation it will be treated as an input?

**Comment by pkozlowski-opensource** [comment] 2023-04-11 11:03
Duplicate of #26406

**Closed by pkozlowski-opensource** 2023-04-11 11:03 UTC
