### ISSUE TITLE
Evalution of *ngIf-Directive is not synced to template code inside of that *ngIf-block

### ISSUE THREAD

**Issue by zetti-caletti** [angular/angular#47780] opened 2022-10-16 01:53 UTC
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

I don't know why I'm only noticing this now and not earlier after having worked with Angular for some time.
Maybe it's also some configuration (strict, angular-setting) that I am doing wrong, but I think not.

It seems to me that the evalution of *ngIf-Directive is not synced to template code inside of that *ngIf-block.
If I have an ngIf-Directive then all the html template code inside of that if-block only gets executed when the if-statement evaluates to true. So if I check in the *ngIf-Directive a variable and the if-statement evaluates to true then it should be save to use that variable inside the *ngIf-block without checking it again (in this example with optional chaining). Don't know how to describe it more precise so I added a stackblitz demo where everything is shown and commented.

Note:
It appears to me that Angular interprets each statement in a template file separately instead of one nested block (AST) like in every programming language. Maybe that's the reason why I have to do the null check inside that if-block again.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-hfvnpa

### Please provide the exception or error you saw

```true
Object is possibly 'null'.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 14.2.1
Node: 16.16.0
Package Manager: npm 8.11.0 
OS: linux x64

Angular: 14.2.0
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1402.1
@angular-devkit/build-angular   14.2.1
@angular-devkit/core            14.2.1
@angular-devkit/schematics      14.2.1
@angular/cdk                    14.2.4
@angular/cli                    14.2.1
@angular/material               14.2.4
@schematics/angular             14.2.1
rxjs                            7.4.0
typescript                      4.8.3
```

**Comment by kbrilla** [comment] 2022-10-16 11:27
I already brought it up in #47077 but it seems it comes from TS [issue](https://github.com/microsoft/TypeScript/issues/34974)

**Comment by JoostK** [comment] 2022-10-16 13:04
This is indeed a duplicate of #47077, but it's _not_ a TS issue; it's a limitation to how Angular generates its template type checking code behind the scenes.

**Closed by JoostK** 2022-10-16 13:04 UTC

**Comment by kbrilla** [comment] 2022-10-16 13:47
@JoostK  Does this limitation not come from 
```
  static ngTemplateContextGuard<T>(dir: NgIf<T>, ctx: any):
      ctx is NgIfContext<Exclude<T, false|0|''|null|undefined>> {
    return true;
  }
```
where according to mentioned issue TS is not able to properly 'remember' that `collectionResponse` and `items` in `<div *ngIf="collectionResponse?.items?.length">` cannot be `null` or `undefined` and thus `  {{ collectionResponse.items.length }}` does not work as describeb in [this comment uner my issue](https://github.com/angular/angular/issues/47077#issuecomment-1260158020)

![image](https://user-images.githubusercontent.com/22288449/196038870-70a16c20-ed11-489f-b2e3-1e96867bf56b.png)
![image](https://user-images.githubusercontent.com/22288449/196038908-8538d815-40a2-4722-a135-b4e74836d29e.png)

[playground](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgEoQM4AcD2IMoDeAUMssJALYBcyACjhmANzEC+xxoksiKAwjgA2QiAjDA86bHgLISZChEoZaDJgG0Auqw5dw0eEnqMw80skgAPMLSZRQAc12diEK7ihmEQuBgzIAHKOAJIwggY2ADwAKsgAvMgAriAA1iA4AO4gAHzmZFhJAEZCwAjIACTAlFilCBS0cYkgSSIAhKwFxXXIIKEwjQm9rUId7Jzunt6+-kH9sUMp6Vm5+chYDgBucJDIAPoIeNa2c2ERx7F5zRCZp+FH7mCXABQAlKwWTDtlvY4xyrUdhBzo8AOJJOBQAAmLyhwCgtGCYUuABpkOIrLQ4CAAJ6vagWMhkDHkAJI+6RJ4AUSsPiSUIgsTR8CEBAAPgAGNkAcm5bJaIjZKQZMFAEChOTyCiJUAgYCSUBAligSQgnWQHD0MBS4kkSsgTGespk+AgAH5aIIRGIJFJMLhTa8SMRDvgzAawGEhiAbncotIHQQcm8PsAYMhnuSAHR9f41XyQEE2cGQqHPD1hNHGwPmqNKFRmqOiPpgAAWr1exGdrkJyGzsggeaoGCLEBLpZcXHDRvtDcL+YwheLjjLrzWZHrpqbyhbw7LnY4QA)

**Comment by JoostK** [comment] 2022-10-16 15:24
No; `ngTemplateContextGuard` is irrelevant here because the expression `response.items.length` within the `if`-block does not refer to any context variables of the template.

This issue concerns `ngTemplateGuard_ngIf: 'binding'`, as a binding expression with optional chain is _not_ emitted into that very same optional chain in the type-checking code, but rather using the same expression that is emitted for the Angular runtime (where the optional chain has been explicitly unrolled into ternaries with `!= null` conditions). This causes TS to no longer consider any usages of the optional chaining path to be non-nullable, as it never saw a conditional for the optional chain in the first place.
