### ISSUE TITLE
ng-xi18n Cannot determine the module for class...

### ISSUE THREAD

**Issue by born2net** [angular/angular#13938] opened 2017-01-15 17:50 UTC
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
getting lots of errors from unused components:

**Expected behavior**
if I don't declare a component in my declarations, i18 should not look at it

I run the following:

```
$ ./node_modules/.bin/ng-xi18n
Error: Cannot determine the module for class DividerPanel in C:/msweb/ng-skeleton/src/comps/dividerpanel/DividerPanel.ts!
Cannot determine the module for class Dropbox in C:/msweb/ng-skeleton/src/comps/dropbox/Dropbox.ts!
Cannot determine the module for class EntryPanel in C:/msweb/ng-skeleton/src/comps/entry/EntryPanel.ts!
Cannot determine the module for class ForgotPass in C:/msweb/ng-skeleton/src/comps/entry/ForgotPass.ts!
Cannot determine the module for class Footer in C:/msweb/ng-skeleton/src/comps/footer/Footer.ts!
Cannot determine the module for class Infobox in C:/msweb/ng-skeleton/src/comps/infobox/Infobox.ts!
Cannot determine the module for class InputNumeric in C:/msweb/ng-skeleton/src/comps/inputnumeric/InputNumeric.ts!
Cannot determine the module for class InputString in C:/msweb/ng-skeleton/src/comps/inputstring/InputString.ts!
Cannot determine the module for class Loading in C:/msweb/ng-skeleton/src/comps/loading/Loading.ts!
Cannot determine the module for class MapAddress in C:/msweb/ng-skeleton/src/comps/mapaddress/MapAddress.ts!
Cannot determine the module for class Minitab in C:/msweb/ng-skeleton/src/comps/minitabs/MiniTab.ts!
Cannot determine the module for class Minitabs in C:/msweb/ng-skeleton/src/comps/minitabs/MiniTabs.ts!
Cannot determine the module for class ModalDialog in C:/msweb/ng-skeleton/src/comps/modaldialog/ModalDialog.ts!
Cannot determine the module for class Ng2Highcharts in C:/msweb/ng-skeleton/src/comps/ng2-highcharts/src/directives/ng2-highcharts.ts!

Cannot determine the module for class Ng2Highstocks in C:/msweb/ng-skeleton/src/comps/ng2-highcharts/src/directives/ng2-highstocks.ts!

Cannot determine the module for class Ng2Highmaps in C:/msweb/ng-skeleton/src/comps/ng2-highcharts/src/directives/ng2-highmaps.ts!
Cannot determine the module for class simplelistEditable in C:/msweb/ng-skeleton/src/comps/simplelist/simplelistEditable.ts!
Cannot determine the module for class simplelist in C:/msweb/ng-skeleton/src/comps/simplelist/simplelist.ts!
Cannot determine the module for class FilterPipe in C:/msweb/ng-skeleton/src/pipes/FilterPipe.ts!
Cannot determine the module for class FilterPipeEqual in C:/msweb/ng-skeleton/src/pipes/FilterPipeNot.ts!
Cannot determine the module for class OrderBy in C:/msweb/ng-skeleton/src/pipes/OrderBy.ts!
Cannot determine the module for class ReplacePipe in C:/msweb/ng-skeleton/src/pipes/ReplacePipe.ts!
Cannot determine the module for class SortBy in C:/msweb/ng-skeleton/src/pipes/SortBy.ts!
    at analyzeAndValidateNgModules (C:\msweb\ng-skeleton\node_modules\@angular\compiler\bundles\compiler.umd.js:24878:17)
    at Extractor.extract (C:\msweb\ng-skeleton\node_modules\@angular\compiler\bundles\compiler.umd.js:27727:20)
    at Extractor.extractBundle (C:\msweb\ng-skeleton\node_modules\@angular\compiler-cli\src\extractor.js:40:33)
    at Extractor.extract (C:\msweb\ng-skeleton\node_modules\@angular\compiler-cli\src\extractor.js:30:34)
    at extract (C:\msweb\ng-skeleton\node_modules\@angular\compiler-cli\src\extract_i18n.js:7:67)
    at Object.main (C:\msweb\ng-skeleton\node_modules\@angular\tsc-wrapped\src\main.js:47:16)
    at Object.<anonymous> (C:\msweb\ng-skeleton\node_modules\@angular\compiler-cli\src\extract_i18n.js:14:9)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
Extraction failed
```

versions:
```
angular-cli: 1.0.0-beta.25.5
node: 6.5.0
os: win32 x64
@angular/common: 2.4.3
@angular/compiler: 2.4.3
@angular/compiler-cli: 2.4.3
@angular/core: 2.4.3
@angular/forms: 2.4.3
@angular/http: 2.4.3
@angular/platform-browser: 2.4.3
@angular/platform-browser-dynamic: 2.4.3
@angular/platform-server: 2.4.3
@angular/router: 3.2.1
@angular/language-service: 2.4.3

```

Angular 2 Kitchen sink: http://ng2.javascriptninja.io
and source@ https://github.com/born2net/Angular-kitchen-sink
Regards,

Sean

**Comment by DzmitryShylovich** [comment] 2017-01-15 17:54
Duplicate of https://github.com/angular/angular/issues/13590

**Comment by born2net** [comment] 2017-01-15 18:01
ok will continue on that thread

**Comment by born2net** [comment] 2017-01-16 15:32
reopening issue as this is specific to i18 translation

**Comment by born2net** [comment] 2017-01-16 15:35
I am happy to assist in any testing needed...

**Comment by born2net** [comment] 2017-01-16 16:07
let me add that even if I created a clean project with cli: ```ng new myProject```
and run
``` ./node_modules/.bin/ng-xi18n```
I would get:

```
root@DESKTOP-VEUHFOL /cygdrive/c/msweb/ng-i18n
$ ./node_modules/.bin/ng-xi18n
Error: Error encountered resolving symbol values statically. Calling function 'NoOpAnimationDriver', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AnimationDriver.NOOP in C:/msweb/ng-i18n/node_modules/@angular/platform-browser/src/dom/animation_driver.d.ts, resolving symbol BrowserTestingModule in C:/msweb/ng-i18n/node_modules/@angular/platform-browser/testing/browser.d.ts, resolving symbol BrowserTestingModule in C:/msweb/ng-i18n/node_modules/@angular/platform-browser/testing/browser.d.ts
    at simplifyInContext (C:\msweb\ng-i18n\node_modules\@angular\compiler\bundles\compiler.umd.js:25709:25)
    at StaticReflector.simplify (C:\msweb\ng-i18n\node_modules\@angular\compiler\bundles\compiler.umd.js:25721:15)
    at StaticReflector.annotations (C:\msweb\ng-i18n\node_modules\@angular\compiler\bundles\compiler.umd.js:25218:62)
    at NgModuleResolver.resolve (C:\msweb\ng-i18n\node_modules\@angular\compiler\bundles\compiler.umd.js:17564:84)
    at CompileMetadataResolver.getNgModuleMetadata (C:\msweb\ng-i18n\node_modules\@angular\compiler\bundles\compiler.umd.js:18072:62)
    at CompileMetadataResolver.getNgModuleSummary (C:\msweb\ng-i18n\node_modules\@angular\compiler\bundles\compiler.umd.js:18028:54)
    at C:\msweb\ng-i18n\node_modules\@angular\compiler\bundles\compiler.umd.js:18118:70
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (C:\msweb\ng-i18n\node_modules\@angular\compiler\bundles\compiler.umd.js:18113:51)
    at addNgModule (C:\msweb\ng-i18n\node_modules\@angular\compiler\bundles\compiler.umd.js:24980:60)
Extraction failed

```

**Comment by Luftzig** [comment] 2017-01-18 08:08
I also see the same behaviour described by @born2net. Same error message, using version 2.4.3

**Comment by ocombe** [comment] 2017-03-20 14:22
It is a duplicate of #13590 because ng-xi18n uses the same compilation process. Fixing it there will fix it for i18n.
If you need to add more details, continue the discussion in #13590, thanks!

**Closed by ocombe** 2017-03-20 14:22 UTC
