### ISSUE TITLE
WS_CHARS is invalid

### ISSUE THREAD

**Issue by jpike88** [angular/angular#36121] opened 2020-03-18 10:18 UTC
https://github.com/angular/angular/blob/9e70bcb34f91d439f5203dc22a44f323d02c4648/packages/compiler/src/ml_parser/html_whitespaces.ts#L19

This line is both invalid, and mix of both whitespace and line terminators.

See relevant comment:
https://github.com/meriyah/meriyah/issues/70#issuecomment-595882084

**Comment by petebacondarwin** [comment] 2020-03-18 11:26
I looked at the comment you linked to, and while I am sympathetic to the problems that are faced in that issue, I am not clear what the action is in this issue here.

Are you suggesting that the `WS_CHARS` should not include line terminators? What is the error that is being caused by those being part of this particular constant?
Or are you implying that our HTML parser needs to be significantly reworked to deal with some issue to do with whitespace (or non-whitespace) characters?

Please provide some more information to help us act on this issue.

**Comment by jpike88** [comment] 2020-03-18 11:39
@JLHwung @KFlash can you help me explain lol

**Comment by JLHwung** [comment] 2020-03-18 13:23
`WS_CHARS` should not include `\u180e` as discussed at https://github.com/meriyah/meriyah/issues/70#issuecomment-594955742.

I think both line separator and paragraph separator should be included to align with `\s`.

**Comment by KFlash** [comment] 2020-03-18 14:16
@JLHwung line separator and paragraph separator shouldn't be included. They are LineTerminators, and not part of the whtitespace Z category (*unicode*) as listed in that code snippet.

`\n` and `\r` are also classified as LineTerminators.

**Comment by petebacondarwin** [comment] 2020-03-18 14:26
Can you please provide an example of how this is breaking something in an Angular application?

**Comment by jpike88** [comment] 2020-03-19 02:14
@petebacondarwin why? This issue isn't related to breaking behavior in angular as far as I know. Does it have to be?

**Comment by petebacondarwin** [comment] 2020-03-19 09:09
It is not enough to say that `WS_CHARS` is wrong without giving a scenario in which it causes problems.

**Line terminators**
From looking at the code `WS_CHARS` is only used to manage whitespace collapsing, in which case line terminators are perfectly legitimate characters that should be collapsed.

**Mongolian vowel separator MVS**
Here is some background about this code-point: https://linguistics.stackexchange.com/questions/12712/what-is-the-mongolian-vowel-separator-for.

It appears from https://www.unicode.org/L2/L2013/13004-vowel-sep-change.pdf that `\u180e` is no longer regarded as a whitespace character so I believe that this could indeed be removed from `WS_CHARS`. The "required breaking example" for this, as I requested earlier, would be to show that in some Angular template this character is being used but we are removing it and replacing it with a single space character, which is breaking the meaning of the text in the template. For example, in a template you might have

```
<div>someXword</div>
```

where X is the MVS, being rendered as:

```
<div>some word</div>
```

---

Regarding the original issue on [Meriyah](https://github.com/meriyah/meriyah/issues/70), I don't believe that it has anything to do with the Angular. We are should be able include any Unicode characters inside string literals in our source code - that is perfectly valid TypeScript/JavaScript. How Meriyah chooses to express these string literals in its generated ASTs is completely independent of the original valid source code.

**Comment by pkozlowski-opensource** [comment] 2020-05-25 14:08
As @petebacondarwin pointed out the set of characters discussed here should capture _both_ whitespaces and new lines. I agree that the variable name is not ideal and could be confusing but I'm not sure if there is any practical value in splitting whitespaces and new lines given the intended purpose.

I'm going to close this issue based on the above comment. Having said this we would accept PRs from anyone that would like to improve naming etc.

**Closed by pkozlowski-opensource** 2020-05-25 14:08 UTC
Labels: comp: compiler, comp: core, core: basic template syntax, state: Needs repro

**Comment by JLHwung** [comment] 2020-05-25 19:25
@pkozlowski-opensource  Shouldn't `\u180e` be removed from `WS_CHARS`? It is no longer a whitespace by definition.
