### ISSUE TITLE
Enable strict template in `tsconfig.json`  causing `Type 'AbstractControl' is not assignable to type 'FormControl'.`

### ISSUE THREAD

**Issue by hiepxanh** [angular/angular#43250] opened 2021-08-25 08:23 UTC
### Which @angular/* package(s) are the source of the bug?

dont know

### Is this a regression?

No

### Description

Enable strict template in `tsconfig.json`  causing `Type 'AbstractControl' is not assignable to type 'FormControl'.`

I have this problem which cannot solve:
`Type 'AbstractControl' is missing the following properties from type 'FormControl': registerOnChange, registerOnDisabledChange, _applyFormState`

![image](https://user-images.githubusercontent.com/16970990/130754194-276c6366-2168-4eb0-9800-b856358b68ce.png)

![image](https://user-images.githubusercontent.com/16970990/130755353-af313195-6358-44fe-a25e-18841d2d0092.png)

### Please provide the exception or error you saw

```true
Type 'AbstractControl' is missing the following properties from type 'FormControl': registerOnChange, registerOnDisabledChange, _applyFormState

Type 'AbstractControl' is not assignable to type 'FormControl'.
```

### Please provide the environment you discovered this bug in

```true
Angular CLI: 12.2.2
Node: 14.17.0
Package Manager: pnpm 6.11.5
OS: win32 x64

Angular: 12.2.2
... animations, cdk, cli, common, compiler, compiler-cli, core      
... forms, language-service, material, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.2 (cli-only)
@angular-devkit/build-angular   12.2.2
@angular-devkit/core            12.2.2
@angular-devkit/schematics      12.2.2
@angular/fire                   6.1.5
@schematics/angular             12.2.2
rxjs                            7.3.0
typescript                      4.3.5
webpack                         5.51.1
```

**Comment by JoostK** [comment] 2021-08-25 09:52
This would fall under the realm of #13721. Using `bookForm.get('title')` you get an `AbstractControl`, which is not assignable into the `inputControl` input that requires `FormControl`. The fact that `bookForm.get('title')` is really a `FormControl` is not currently reflected by the return type of `FormGroup.get` due to #13721.

A workaround could be to move the logic to a method on the component class and cast to the appropriate type there.

Closing as duplicate of #13721.

**Closed by JoostK** 2021-08-25 09:52 UTC
