### ISSUE TITLE
@angular/pwa leads to routes being handled by angular where they should've been handled by the reverse proxy instead

### ISSUE THREAD

**Issue by dalu** [angular/angular#36095] opened 2020-03-16 20:24 UTC
# 🐞 Bug report

### Command (mark with an `x`)
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

I don't think so.

### Description

nginx is the reverse proxy in the front

before:

- keycloak IDP was on a separate subdomain and domain (https://connect.otherdomain.tld/)
- https://github.com/manfredsteyer/angular-oauth2-oidc is used as an oidc client.
- local api accessible under local domain `/api/v1/*`

when I write local domain, I mean domain.tld (e.g. example.com)

no issues

now:

- keycloak IDP is on the same local domain mounted under `/auth/` (https://domain.tld/auth/)
- http api is also mounted, as before under `/api/v1/*`

When the ngsw... service worker is registered and active, the mentioned error appears after clicking on the login button/link.

When I press unregister and try that button/link again there are no issues.

This does NOT happen in dev, only prod, which makes sense, since I'm using the remote connect.domain.tld IDP.

SameSite cookies are coming soonTM.

ngsw-config.json
```json
{
  "$schema": "./node_modules/@angular/service-worker/config/schema.json",
  "index": "/index.html",
  "assetGroups": [
    {
      "name": "app",
      "installMode": "prefetch",
      "resources": {
        "files": [
          "/favicon.ico",
          "/index.html",
          "/manifest.webmanifest",
          "/*.css",
          "/*.js"
        ]
      }
    }, {
      "name": "assets",
      "installMode": "lazy",
      "updateMode": "prefetch",
      "resources": {
        "files": [
          "/assets/**",
          "/*.(eot|svg|cur|jpg|png|webp|gif|otf|ttf|woff|woff2|ani)"
        ]
      }
    }
  ]
}
```

## 🔬 Minimal Reproduction

Almost Impossible.
Would require a live domain with a configured IDP for that domain which is mounted locally under the /auth/ URL prefix, then configuring that oauth/oidc client to use that, add a button to login, ng add @angular/pwa, publish to some web host to then try and login twice while the service worker is active

## 🔥 Exception or Error
<pre><code>
Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'auth/realms/some.realm/protocol/openid-connect/auth'
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 9.0.6
Node: 12.16.1
OS: linux x64

Angular: 9.0.6
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.6
@angular-devkit/build-angular     0.900.6
@angular-devkit/build-optimizer   0.900.6
@angular-devkit/build-webpack     0.900.6
@angular-devkit/core              9.0.6
@angular-devkit/schematics        9.0.6
@angular/cdk                      9.1.2
@angular/flex-layout              9.0.0-beta.29
@angular/material                 9.1.2
@ngtools/webpack                  9.0.6
@schematics/angular               9.0.6
@schematics/update                0.900.6
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
</code></pre>

**Anything else relevant?**
This happens on chromium linux
does not happen on chrome linux and it does happen on chrome linux
happens on chrome android
happens on firefox android
does not happen on firefox linux

I've also opened an issue https://github.com/manfredsteyer/angular-oauth2-oidc/issues/750

**Comment by gkalpak** [comment] 2020-03-17 09:02
@dalu, based on the info you provided it sounds like your app makes some requests that are identified as navigation requests by the ServiceWorker (based on its default configuration).

For context, when the ServiceWorker identifies a request (that is not matched by an asset-/data-group) as a "navigation" request, it responds with the `index.html` file. (This is needed  to handle client-side routing with the [PathLocationStrategy][1], which is the default.)

The ServiceWorker has some criteria (see [here][2] for more details) to determine whether a request is a "navigation" request (i.e. a request navigating to a page vs a request to fetch data or assets). The fix for you case would be specify appropriate `navigationUrls` in `ngsw-config.json`. The default ones are:

https://github.com/angular/angular/blob/168a393589f80bd2fa6fb3fb6235754c5e75a384/packages/service-worker/config/src/generator.ts#L14-L19

So, you do something like:

```json
// ngsw-config.json
{
  ...
  "navigationUrls": [
    "/**",           // Include all URLs.
    "!/**/*.*",      // Exclude URLs to files (containing a file extension in the last segment).
    "!/**/*__*",     // Exclude URLs containing `__` in the last segment.
    "!/**/*__*/**",  // Exclude URLs containing `__` in any other segment.
    "!/auth/**       // Exclude URLs to `/auth/...` that need to go through to the IDP.
  ]
}
```

##
I hope this solves it for you. Closing the issue, since everything seems to work as intended, but feel free to continue the discussion below.

[1]: https://angular.io/api/common/PathLocationStrategy
[2]: https://angular.io/guide/service-worker-config#navigationurls

**Closed by gkalpak** 2020-03-17 09:02 UTC
Labels: comp: service-worker

**Comment by dalu** [comment] 2020-03-17 15:09
I understand. Thank you very much for your detailed response.
