### ISSUE TITLE
ngIf works differently than if with regards to optional chaining

### ISSUE THREAD

**Issue by Christoph142** [angular/angular#43318] opened 2021-09-02 11:54 UTC
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

1. add *ngIf="foo?.bar <= 0" to a template and assign the same code to a variable in code
2. pass in foo = null

In code, due to optional chaining, the comparison will return **false**, because it's the same as "foo && foo.bar <= 0".
*ngIf returns **true** - looks like foo?.bar gets evaluated as falsy, but doesn't return immediately. Instead it gets compared to 0, which is also falsy and hence returns true.

### Please provide the environment you discovered this bug in

```true
Angular 12.2.3
```

**Comment by petebacondarwin** [comment] 2021-09-02 12:03
As far as I can tell this is working as expected: https://stackblitz.com/edit/angular-ivy-n3rlru?file=src%2Fapp%2Fapp.component.html

Both the native code and the template syntax result in `true`.

**Comment by petebacondarwin** [comment] 2021-09-02 16:37
This is basically a duplicate of https://github.com/angular/angular/issues/34385#issuecomment-625935575
It might be worth adding your use case to that issue, so that we keep the discussion in a single place.

**Closed by petebacondarwin** 2021-09-02 16:37 UTC
Labels: comp: core, core: basic template syntax, P3, compiler: parser
