### ISSUE TITLE
HashLocationStrategy causes query parameters to be removed upon application load

### ISSUE THREAD

**Issue by nkerr** [angular/angular#37302] opened 2020-05-27 03:52 UTC
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/common
Specifically: HashLocationStrategy

### Is this a regression?
Unsure.

### Description
This is essentially a request to re-open the following issue since the problem still exists and is easily reproduced: https://github.com/angular/angular/issues/23423

When using the **HashLocationStrategy**, any initial url parameters included in the URL are immediately erased when the application loads.

## 🔬 Minimal Reproduction

See an example of the **problem** here:
https://stackblitz.com/edit/angular-kc474f
Run the program:
https://angular-kc474f.stackblitz.io/?code=123

If you switch back to the default location strategy, you will see that the **problem does not occur:**
Code: https://stackblitz.com/edit/angular-ab8kvt
Run: https://angular-ab8kvt.stackblitz.io/?code=123

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.1.0
Node: 10.16.0
OS: darwin x64

Angular: 9.0.7
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.0
@angular-devkit/build-angular     0.901.0
@angular-devkit/build-optimizer   0.901.0
@angular-devkit/build-webpack     0.901.0
@angular-devkit/core              9.1.0
@angular-devkit/schematics        9.1.0
@angular/cdk                      9.2.0
@angular/cli                      9.1.0
@angular/material                 9.2.0
@ngtools/webpack                  9.1.0
@schematics/angular               9.1.0
@schematics/update                0.901.0
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.42.0
</code></pre>

**Comment by atscott** [comment] 2020-06-15 20:04
Duplicate of #36688 / #14307

**Closed by atscott** 2020-06-15 20:04 UTC
Labels: comp: router
