### ISSUE TITLE
How to use Captured phase of @HostListener

### ISSUE THREAD

**Issue by ofirrifo** [angular/angular#42788] opened 2021-07-07 13:14 UTC
# Feature Request
It would be nice if we could pass to @HostListener capture: true

### Relevant Package
@angular/core

### Description
Add the ability to use the capturing phase with  HostListener

### Describe the solution you'd like
I would think to pass the `captured:true` as below:

```
 @HostListener('document:keydown.escape, captured:true ', ['$event'])
  onEscape(event: KeyboardEvent) {
    if (this.menuTrigger.menuOpen) {
      event.stopPropagation();
      this.menuTrigger.closeMenu();
    }
  }
```

**Comment by petebacondarwin** [comment] 2021-07-07 13:17
Duplicate of https://github.com/angular/angular/issues/11200

**Closed by petebacondarwin** 2021-07-07 13:17 UTC
Labels: comp: core, feature
