### ISSUE TITLE
Http interceptor cannot be tested in context of not parsable response body

### ISSUE THREAD

**Issue by jepetko** [angular/angular#46221] opened 2022-06-02 15:50 UTC
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

No

### Description

# What is the tested behavior

When using HttpClient in conjunction with HttpTestingController, it is not possible to test for proper processing of the content type and response body, respectively. 

Let's take the regular example when parsing of the response body fails. In this case HTTP code is 200 and body contains non json content such as `<html>...</html>`. JSON.parse fails parsing the response and hits the `catchError` operator.

The error in HttpErrorResponse sounds like this:

```
 HttpErrorResponse {headers: HttpHeaders, status: 200, ...}
         error:
           error: SyntaxError: Unexpected end of JSON input at ..
....
         ok: false
```

# How I want to test it

Now, I want to test this case by flushing html response (instead of JSON). So, my expectation would look like this:

* I expect json to be returned from the tested endpoint (`responseType: json`)
* I flush html content with `Content-type: text/html`

```
    it('maps it to 200 although it fails parsing JSON response', done => {
      httpClient.get<Data>(testUrl, { responseType: 'json' }).subscribe(res => {
        expect(res).toEqual({});
        done();
      });

      const req = httpMock.expectOne(testUrl);
      const headers = new HttpHeaders();
      headers.append('content-type', 'text/html');

      req.flush('<html></html>', { headers, statusText: 'OK', status: 200 });

      httpMock.verify();
    });
```

... and the according implementation could look like this:

```
export class MyInterceptor implements HttpInterceptor {
  intercept(req: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
    return next.handle(req).pipe(
      catchError(err => {
       // Note: ok is set to false in XHR implementation when parsing fails
        if (err.status === 200 && err.ok === false) {
          return of(new HttpResponse({ body: {}, status: err.status, headers: err.headers, statusText: err.statusText }));
        }
        return throwError(err);
      }),
    );
  }
}
```

# What is the actual issue

However, testing infrastructure does not properly handle the content type (as real XHR implementation does). Thus, it does not reach `catchError` block. This is because `_toJsonBody` does not try to parse the response. 

https://github.com/angular/angular/blob/025903566edaf3615d12a348dcf7813b298ed4f1/packages/common/http/testing/src/request.ts#L163
```
    function _toJsonBody(body, format) {
        if (format === void 0) { format = 'JSON'; }
        if (typeof ArrayBuffer !== 'undefined' && body instanceof ArrayBuffer) {
            throw new Error("Automatic conversion to " + format + " is not supported for ArrayBuffers.");
        }
        if (typeof Blob !== 'undefined' && body instanceof Blob) {
            throw new Error("Automatic conversion to " + format + " is not supported for Blobs.");
        }

// -------------------- NO JSON.parse here -----------------------------
        if (typeof body === 'string' || typeof body === 'number' || typeof body === 'object' ||
            typeof body === 'boolean' || Array.isArray(body)) {
            return body;
        }
        throw new Error("Automatic conversion to " + format + " is not supported for response type.");
    }
```

Thus, the test fails as it never reaches `catchError`.

```
Error: expect(received).toEqual(expected) // deep equality

Expected: {}
Received: "<html></html>"
```

As an alternative solution, I tried to flush `HttpErrorResponse` using `.error` method, however this does not accept status = 200:

https://github.com/angular/angular/blob/025903566edaf3615d12a348dcf7813b298ed4f1/packages/common/http/testing/src/request.ts#L98
```
            if (opts.status && opts.status >= 200 && opts.status < 300) {
                throw new Error("error() called with a successful status.");
            }
```

# What could the solution look like

A possible solution could be (quickly scripted within the bundle):

## _toJsonBody:
```
    function _toJsonBody(body, format) {
        if (format === void 0) { format = 'JSON'; }
        if (typeof ArrayBuffer !== 'undefined' && body instanceof ArrayBuffer) {
            throw new Error("Automatic conversion to " + format + " is not supported for ArrayBuffers.");
        }
        if (typeof Blob !== 'undefined' && body instanceof Blob) {
            throw new Error("Automatic conversion to " + format + " is not supported for Blobs.");
        }
//-------------------------
// try to parse it as it is expected to be JSON
//-------------------------
        if (format === 'JSON' && (typeof body === 'string' || typeof body === 'number' || typeof body === 'object' ||
            typeof body === 'boolean' || Array.isArray(body))) {
            return JSON.parse(body);
        }
        throw new Error("Automatic conversion to " + format + " is not supported for response type.");
    }
```

## flush
```
        TestRequest.prototype.flush = function (body, opts) {
            if (opts === void 0) { opts = {}; }
            if (this.cancelled) {
                throw new Error("Cannot flush a cancelled request.");
            }
            var url = this.request.urlWithParams;
            var headers = (opts.headers instanceof http.HttpHeaders) ? opts.headers : new http.HttpHeaders(opts.headers);

//-------------------------
// parse the body
//-------------------------
            var ok = true;
            var parseError;
            try {
              body = _maybeConvertBody(this.request.responseType, body);
            } catch (e) {
              ok = false;
              parseError = e;
            }

            var statusText = opts.statusText;
            var status = opts.status !== undefined ? opts.status : 200 /* Ok */;
            if (opts.status === undefined) {
                if (body === null) {
                    status = 204 /* NoContent */;
                    statusText = statusText || 'No Content';
                }
                else {
                    statusText = statusText || 'OK';
                }
            }
            if (statusText === undefined) {
                throw new Error('statusText is required when setting a custom status.');
            }
            if (status >= 200 && status < 300) {
              if (ok === true) {
                this.observer.next(new http.HttpResponse({ body: body, headers: headers, status: status, statusText: statusText, url: url }));
                this.observer.complete();
              } else {

//-------------------------
// in case of parse error, next the modified response (containing the original 200 response, but also the error and ok = false)

                this.observer.error(new http.HttpErrorResponse({ body: body, headers: headers, status: status, statusText: statusText, url: url, ok: false, error: parseError }));
//-------------------------

              }
            } else {
                this.observer.error(new http.HttpErrorResponse({ error: body, headers: headers, status: status, statusText: statusText, url: url }));
            }
        };
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 12.2.12
Node: 14.17.0
Package Manager: yarn 1.22.10
OS: win32 x64

Angular: 12.2.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, material, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.12
@angular-devkit/build-angular   12.2.12
@angular-devkit/core            12.2.12
@angular-devkit/schematics      12.2.12
@angular/cli                    12.2.12
@schematics/angular             12.2.12
rxjs                            6.6.7
typescript                      4.3.5
```

**Comment by JoostK** [comment] 2022-06-02 16:59
This seems like a duplicate of #19289, or at least is related to it.

**Comment by jessicajaniuk** [comment] 2022-06-06 23:17
Thanks for reporting this issue. However this issue is a duplicate of an existing issue #19289. Please subscribe to that issue for future updates.

**Closed by jessicajaniuk** 2022-06-06 23:17 UTC
Labels: comp: common/http
