### ISSUE TITLE
The fragment and queryParams of NavigationExtra doesn't work for navigateByUrl()

### ISSUE THREAD

**Issue by wellwind** [angular/angular#38751] opened 2020-09-09 06:33 UTC
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/router

### Description

The `fragment` and `queryParams` of [NavigationExtra](https://angular.io/api/router/NavigationExtras) should be worked both in `navigate()` and `navigateByUrl()` of Router. But doesn't work in `navigateByUrl()` now. ex:

```typescript
this.router.navigateByUrl('target', { fragment: 'test' });
```

Just pass the whole url with fragment or query string works.

```typescript
this.router.navigateByUrl('target#test');
```

but I think it should also work when using `fragment` and `queryParams`.

## 🔬 Minimal Reproduction

The minimal GitHub repository:

https://github.com/wellwind/reproduction-fragment-of-navigate-by-url

Just created a simple lazy loading module, then use `navigate` and `navigateByUrl` of `Router` in `AppComponent`

```typescript
export class AppComponent {
  constructor(private router: Router) {

  }

  // it works
  navigate(): void {
    this.router.navigate(['target'], { fragment: 'test' });
  }

  navigateByUrl(): void {
    // also works
    // this.router.navigateByUrl('target', { fragment: 'test' });

    // it doesn't work
    this.router.navigateByUrl('target', { fragment: 'test' });
  }
}
```

## 🌍  Your Environment

**Angular Version:**
<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 10.1.0
Node: 12.13.0
OS: win32 x64

Angular: 10.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1001.0
@angular-devkit/build-angular     0.1001.0
@angular-devkit/build-optimizer   0.1001.0
@angular-devkit/build-webpack     0.1001.0
@angular-devkit/core              10.1.0
@angular-devkit/schematics        10.1.0
@ngtools/webpack                  10.1.0
@schematics/angular               10.1.0
@schematics/update                0.1001.0
rxjs                              6.6.3
typescript                        4.0.2
webpack                           4.44.1
</code></pre>

**Comment by Airblader** [comment] 2020-09-09 06:55
An alternative would be to throw an error in these cases. If it should be made to work there are some questions to answer, eg if the URL already contains a query parameter that is also specified in the second argument, does it override it or does it merge it into a repeated parameter (array behavior)?

**Comment by Airblader** [comment] 2020-09-09 07:07
Also, this isn't mentioned here but related, how should this work for queryParamsHandling? I can't test right now whether this is ignored or works in some way.

**Comment by wellwind** [comment] 2020-09-09 07:57
Or, if let `navigateByUrl` not support `fragment` because of the conflict between URL and NavigationExtra settings.
But NavigationExtra should be split into two interfaces for `navigate` and `navigateByUrl`

**Comment by atscott** [comment] 2020-09-09 21:06
Duplicate of #18798

**Closed by atscott** 2020-09-09 21:06 UTC
Labels: comp: router
