### ISSUE TITLE
Pipes are broken in Safari 

### ISSUE THREAD

**Issue by yfain** [angular/angular#6736] opened 2016-01-28 03:38 UTC
#I have a component the has the following in the template:

Last bid: {{newBid?.amount | number:'1.1-2'}} 
Bid time: {{newBid?.bidTime | date: 'medium'}}

This code works fine in Chrome and Firefox. But in Safari 9 I got an error "Can't find variable: Intl" and then my date pipe. Removed the date pipe and got the same error for my number pipe. Removed both pipes and the code started working fine.

I believe this error has the same cause as #6009   

I use Angular 2.0.0-beta.1 on MAC OS.

**Comment by pkozlowski-opensource** [comment] 2016-01-28 09:40
Duplicate of #3333

**Closed by pkozlowski-opensource** 2016-01-28 09:40 UTC

**Comment by AmitVirpara** [comment] 2016-12-03 08:07
if i remove pipe sign, i need some help 
like : i show date with proper format , in that case i set date format  in server side and give well set data. or i stored with needed formed data, or compulsory format in client side.
