### ISSUE TITLE
Ability to provide default values for host directive @Input properties

### ISSUE THREAD

**Issue by chriswoodie** [angular/angular#51691] opened 2023-09-07 11:45 UTC
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

Consider the following host directive:

```
@Directive({
  standalone: true
})
export class SDKControlMixin {
  ...
  @Input() iconSide: 'left' | 'right' = 'left';
}
```

Which is then used as a host directive:

```
@Component({
  standalone: true,
  ...
  hostDirectives: [
    {
      directive: SDKControlMixin,
      inputs: [
        ...
        'iconSide'
      ]
    }
  ]
})
export class LibInputSearchComponent {

  constructor(private controlMixin: SDKControlMixin) {
    super();
    
    this.controlMixin.iconSide = 'right';
  }
}
```

The problem with this approach is that it doesn't seem possible to assign default values to a host directive like this. Even if I use the `LibInputSearchComponent` component like this:

```
<lib-input-search iconSide="left"></lib-input-search>
```

The value of `iconSide` will always be `'right'`, since that's what's being set in the constructor.

Since passing values to a host directive's constructor isn't supported, this provides a major stumbling block when it comes to using a host directive in different scenarios where default values need to be set.

### Proposed solution

I think the best solution would be to add another field to the hostDirectives declarations where you can specify default values:

```
{
  directive: SDKControlMixin,
  inputs: ['iconSide'],
  defaultValues: { input: 'iconSide', value: 'right' },
}
```

Or even:

```
{
  directive: SDKControlMixin,
  inputs: [{ name: 'iconSide', defaultValue: 'right' }],
}
```

These values would override any values set for the @Input. If we take my example given:

```
@Input() iconSide: 'left' | 'right' = 'left';
```

The `iconSide` would only receive a default value of `'left'` if no default value was provided in the host directive declaration.

### Alternatives considered

Using an extendable class. However, this is less than ideal since you can't extend multiple classes and it would lead to @Input declarations being available for a component even if they're not actually implemented. This leads to confusion and friction for those consuming the components.

**Comment by pkozlowski-opensource** [comment] 2023-09-11 09:58
It is duplicate of #50510

**Closed by pkozlowski-opensource** 2023-09-11 09:58 UTC
Labels: core: host directives
