### ISSUE TITLE
Do something with `yarn add` removing __ivy_ngcc__ folders

### ISSUE THREAD

**Issue by earshinov** [angular/angular#39140] opened 2020-10-06 20:27 UTC
# 🚀 feature request

### Relevant Package

Probably @angular/compiler

### Description

When `ngcc` precompiles npm packages in `node_modules`, it puts compilation results into the `__ivy_ngcc__` folder next to package contents.

When `yarn add` is run, it cleans npm packages in `node_modules` of files not belonging to the package, removing `__ivy_ngcc__` folders as well.

So, when using `yarn`, adding a package results in compilation of all `node_modules`, which is awfully annoying, especially in real-world Angular projects where `ngcc` takes minutes.

Demo repo: https://github.com/earshinov/angular-yarn-sample. Repro steps are in the README.

### Describe the solution you'd like

I would prefer if `ngcc` put its compilation sources somewhere outside of `node_modules` or, alternatively, into `node_modules/.cache` which yarn seems to recognize as a cache folder and leave intact.

### Describe alternatives you've considered

Yarn could have an option to leave files in node_modules intact, but I guess it would run counter its inclination to keep content inside `node_modules` consistent for all users.

**Comment by earshinov** [comment] 2020-10-06 20:28
This feature request looks similar to https://github.com/angular/angular/issues/36076, but the latter is not about `yarn add`, but about `yarn install` that works well enough for me.

**Comment by petebacondarwin** [comment] 2020-10-06 20:30
I'm afraid that this how yarn works - that node_modules are cleaned out on whenever dependencies change - and nothing in ngcc can change that.

**Comment by earshinov** [comment] 2020-10-06 20:31
But what prevents ngcc from putting its files into a different place? That's what I suggest.

**Comment by petebacondarwin** [comment] 2020-10-06 20:33
Regarding ngcc not touching `node_modules`: we have discussed this in the past. The problem is that many of the build tools would need to be aware of this place and it is not a viable design. Instead we are working on a replacement for ngcc (known as the ng-linker) which will not need to touch `node_modules`. See https://github.com/angular/angular/issues/38366.

**Comment by petebacondarwin** [comment] 2020-10-06 20:34
Given that all efforts are going into the linker approach we will not be attempting to change the underlying design of how ngcc works, since there is no capacity to do so, and it will be unnecessary in the not-too-distant future.

**Comment by earshinov** [comment] 2020-10-06 20:36
OK, got it. I guess this issue can then be closed with some kind of a "Won't Fix" resolution.

**Comment by petebacondarwin** [comment] 2020-10-06 20:41
Cool. Thanks @earshinov. If you want you can follow along with the development of the linker here: https://github.com/orgs/angular/projects/2

Closing as this particular approach will not be implemented.

**Closed by petebacondarwin** 2020-10-06 20:41 UTC

**Comment by earshinov** [comment] 2020-10-06 20:43
Good. @petebacondarwin , thanks for the clear explanation and the prompt reply.
