### ISSUE TITLE
Angular directives do not properly modify Polymer's local DOM

### ISSUE THREAD

**Issue by antonmoiseev** [angular/angular#5531] opened 2015-12-01 20:38 UTC
I'm trying to use Polymer elements within Angular components. One of the issues I ran into - Polymer elements are not aware about DOM modifications performed by Angular directives. Here is a plunk that demos this issue - http://plnkr.co/BKveHkkmr1xWwiOvmsgK?p=preview (please read the text on the demo page that explains how the sample app is expected to work).

AFAIU this happens because Angular directives modify DOM using browser's API directly, but Polymer requires all Local DOM modifications to be done using its [DOM API](https://www.polymer-project.org/1.0/docs/devguide/local-dom.html#dom-api). After a quick investigation I have the impression that the right way to fix it is to create a custom `DomAdapter` by extending the `BrowserDomAdapter` that will use `Polymer.dom` API for local DOM modifications.

I realize Angular + Polymer integration isn't a top priority task for the Angular team right now :wink:, but could you advise what's the right way to make them work together? What's the status of integration with Polymer? Are you already looking into this or it's out of your radar at the moment?

**Comment by danieleds** [comment] 2016-02-13 11:16
Any feedback on this? Suggested workarounds?

**Comment by zoechi** [comment] 2016-02-13 11:29
Enable shadow DOM and load full polyfills. It seems to solve most issues. I still run into issues when I tried to pass a `<template>` to for example `<iron-list>` but that seems to be a different issue.

**Comment by Delagen** [comment] 2016-05-24 04:57
paper-drawel-panel still hang all application on route change without any errors in console

**Comment by vicb** [comment] 2016-09-25 17:21
Is this still applicable to 2.0.1 ?

**Comment by zoechi** [comment] 2016-09-25 18:21
I haven't seen any PR that would address this issue. Polymer shady DOM (default) requires specific Polymer API functions to be called for certain DOM changes.

**Comment by vicb** [comment] 2016-09-25 18:25
Marking as "community-help"

Should probably be considered for polymer v2+

**Comment by zoechi** [comment] 2016-09-25 18:35
I didn't investigate a lot about changes in V2 but from what I read, they are building on top of native shadow DOM support and therefore won't require the Polymer DOM API anymore. 
I assume this issue is therefore only relevant for Polymer 1.x

**Comment by fokusferit** [comment] 2017-01-17 17:01
@zoechi until ShadowDOM v1 is supported on all major browsers (Chrome, Firefox, Edge...) it will need a polyfill which is already in development here https://github.com/webcomponents/shadydom .  We are currently investigating our polymer components with angular v2.2.x. 

And for using webcomponents polyfill for shadowDom v0, Custom Elements etc. -> try to use it with Firefox. The current painpoint is that the polyfill is really slow, it takes at least a second to get a couple of native webcomponents integrated besides the fact that there are rendering issue using it with angular2. 

details are described in the angular-polymer loader here https://github.com/vaadin/angular2-polymer/issues/104 .

**Comment by zoechi** [comment] 2017-01-17 17:15
@fokusferit #11994 is also a serious blocker for me for using Polymer with Angular
Yes, V1 shadow DOM polyfills are slow and shady DOM needs special Angular support (this issue). I guess that won't happen anymore with V2 shadow DOM on its way.

**Comment by fokusferit** [comment] 2017-01-18 11:22
The question for me would be what kind of classes / modules / patterns someone needs to look into to "solve" this issue. As this topic will be around for a while and I'd like to try to solve this issue maybe in a bigger effort with others :)

**Comment by DzmitryShylovich** [comment] 2017-01-18 11:34
have your tried to provide your own impl of `DomRenderer`? I don't think it should be a part of angular by default

**Comment by fokusferit** [comment] 2017-01-18 14:31
@DzmitryShylovich this is what the angular2-polymer Project does / is doing currently. See https://github.com/vaadin/angular2-polymer/issues/104 for further details on that.

**Comment by DzmitryShylovich** [comment] 2017-01-18 14:35
ok https://github.com/vaadin/angular2-polymer/issues/104#issuecomment-273237944

so what do you expect from us on angular side?

**Comment by splincode** [comment] 2018-07-26 15:39
@antonmoiseev Is the issue relevant?

**Comment by pkozlowski-opensource** [comment] 2018-10-29 14:47
Sounds like it was solved via https://github.com/platosha/angular-polymer/issues/104. If anyone is still facing issues please open a new issue with a minimal reproduce scenario.

**Closed by pkozlowski-opensource** 2018-10-29 14:47 UTC
Labels: comp: core & compiler, hotlist: community-help, type: feature
