### ISSUE TITLE
Several binding names to the same property

### ISSUE THREAD

**Issue by rupebac** [angular/angular#11663] opened 2016-09-16 12:45 UTC
**I'm submitting a ...**  (check one with "x")

```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 
Right now it is possible to create a Directive using several selectors, but it is not possible to assign several binding property names to the same property. Consider the following example:

```
@Directive({
    selector: 'my-group,[group]',
})
export class MyGroup {
    @Input('group') instance;
    .....
}
```

As I have got an additional attribute selector, I am kind of forced to use the same property name for "instance", but I am not free to choose another name in case I am using `<my-group>` selector. `<my-group group="myInstance">` looks ugly and redundant.

**Expected behavior**
It should be possible to have something like:
`@Input("group", "instance") instance;`

**Comment by pkozlowski-opensource** [comment] 2016-09-16 14:25
You can work-around this by having a setter pointing to the same field. While this would be simple to implement I'm not sure this case is common enough to warrant additional code / complexity.

The main issue is that you are proposing multiple ways of doing the same thing with your API and I'm not sure we want to promote this as part of the framework.  Going to mark it a feature request but don't hold your breath. Let's see what others got to say.

**Comment by zoechi** [comment] 2016-09-16 15:48
Did you try
```
export class MyGroup {
    @Input('instance')
    @Input('group') 
    instance;
    .....
}
```

I also think using several getters/setters that use the same backing field would be the way to go.

**Comment by lqbweb** [comment] 2016-09-16 16:23
@zoechi yes, I tried, it does not work.

**Comment by vicb** [comment] 2016-09-16 19:10
Does the following work ? (remove the `@Input` decorators)
 
```ts
@Directive({
    directives: ['name1:prop', 'name2:prop'],
})
```

**Comment by lqbweb** [comment] 2016-09-18 17:21
@vicb directives now it is moved to the module, and I guess it does not make much sense to specify component properties in the module.

**Comment by DzmitryShylovich** [comment] 2016-12-10 17:08
Duplicate of https://github.com/angular/angular/issues/13303

**Comment by mhevery** [comment] 2020-12-02 21:36
This many to one complicates the mental model and the runtime. Given that there is a relatively simple work around of using setters, I don't think we should take this on.

**Closed by mhevery** 2020-12-02 21:36 UTC
Labels: comp: core, core: inputs / outputs, feature, freq1: low, workaround1: obvious
