### ISSUE TITLE
HttpModule request method doesn't handle observe:response.

### ISSUE THREAD

**Issue by zzj0402** [angular/angular#32019] opened 2019-08-06 07:05 UTC
Similar to #29732 but should be closed with responsible reply.

# 🐞 bug report

### Affected Package
@angular/common/http
### Is this a regression?
Not sure.

### Description
Cannot set observe: 'response' for request method.
## 🔬 Minimal Reproduction
https://stackblitz.com/angular/qlnlvogjldn?file=src%2Fapp%2Fuploader%2Fuploader.service.ts

Modify the upload method to:
```typescript
upload(file: File) {
    if (!file) { return; }
    const formData: FormData = new FormData();
    formData.append('dataset', file, file.name);
    const req = new HttpRequest('POST', 'http://localhost:666/', formData, {
      reportProgress: true, observe: 'response'
    });

    return this.http.request(req).pipe(
      map(event => this.getEventMessage(event, file)),
      tap(message => this.showProgress(message)),
      last(), // return last (completed) message to caller
      catchError(this.handleError(file))
    );
  }
```

## 🔥 Exception or Error
```
    ERROR in src/app/uploader/uploader.service.ts(36,7): error TS2345: Argument of type '{ reportProgress: true; observe: string;
}' is not assignable to parameter of type '{ headers?: HttpHeaders; reportProgress?: boolean; params?: HttpParams; responseType?:
"text" | "blob" | "arraybuffer" | "json"; withCredentials?: boolean; }'.
      Object literal may only specify known properties, and 'observe' does not exist in type '{ headers?: HttpHeaders; reportProgress?: boolean; params?: HttpParams; responseType?: "text" | "blob" | "arraybuffer" | "json"; withCredentials?: boolean; }'.
```

## 🌍  Your Environment
```
Angular CLI: 8.0.3
Node: 10.15.3
OS: win32 x64
Angular: 8.0.1
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.3
@angular-devkit/build-angular     0.800.3
@angular-devkit/build-optimizer   0.800.3
@angular-devkit/build-webpack     0.800.3
@angular-devkit/core              8.0.3
@angular-devkit/schematics        8.0.3
@angular/cdk                      8.1.1
@angular/cli                      8.0.3
@angular/flex-layout              8.0.0-beta.26
@angular/material                 8.1.1
@ngtools/webpack                  8.0.3
@schematics/angular               8.0.3
@schematics/update                0.800.3
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.30.0
```

**Anything else relevant?**
Switching to post method solves the issue:
```typescript
  upload(file: File) {
    if (!file) { return; }
    const formData: FormData = new FormData();
    formData.append('dataset', file, file.name);

    return this.http.post('URL', formData, {
      reportProgress: true, observe: 'response'
    }).pipe(
      map(event => this.getEventMessage(event, file)),
      tap(message => this.showProgress(message)),
      last(), // return last (completed) message to caller
      catchError(this.handleError(file))
    );
  }
```
To capture response message:
```typescript
/** Return distinct message for sent, upload progress, & response events */
  private getEventMessage(event: HttpEvent<any>, file: File) {
    switch (event.type) {
      case HttpEventType.Sent:
        return `Uploading file "${file.name}" of size ${file.size}.`;

      case HttpEventType.UploadProgress:
        // Compute and show the % done:
        const percentDone = Math.round(100 * event.loaded / event.total);
        return `File "${file.name}" is ${percentDone}% uploaded.`;

      case HttpEventType.Response:
        return `File "${file.name}" was completely uploaded! Your user ID is: "${event.body.userID}"`;

      default:
        return `File "${file.name}" surprising upload event: ${event.type}.`;
    }
  }
```

**Comment by alxhub** [comment] 2019-08-08 23:02
This is correct and (somewhat) by design. When calling the `HttpClient.request(req: HttpRequest<any>)` signature, you get the event stream directly. `HttpClient` will not do any `observe` narrowing.

**Comment by alxhub** [comment] 2019-08-08 23:03
Closing as we don't plan on supporting this any time soon - the signatures of `HttpClient` are complicated enough as is.

**Closed by alxhub** 2019-08-08 23:03 UTC
Labels: comp: common/http
