### ISSUE TITLE
SSR HttpClient include cookies

### ISSUE THREAD

**Issue by NerminKarapandzic** [angular/angular#53173] opened 2023-11-26 11:08 UTC
### Which @angular/* package(s) are relevant/related to the feature request?

probably @angular/ssr. I'm working with V17

### Description

Currently cookies are attached with HttpClient only if the request is coming from the browser. 
This means if we want to make some request from the server side and that request relies on a cookie to be passed on, then the request would fail because no cookies will automatically be added to the request from the server side.

### Proposed solution

I don't know exactly what would be the best way to deal with this, but I think there should be a way...
If angular isn't going to provide any out of the box solution, then there should at least be a section about how to do this properly in the documentation.
This is a very common scenario in my opinion, I'm not sure how am I not seeing more questions about this... 

### Alternatives considered

As I said, having at least a section in the docs that would explain how this can be achieved would be helpful.

**Comment by alan-agius4** [comment] 2023-11-27 10:08
This should work, when using fetch HTTP backend. Are you using `withFetch`?

**Comment by NerminKarapandzic** [comment] 2023-11-27 10:11
Yes, I'm using withFetch. Do you have an example where it works, maybe I can compare to see if I'm doing something wrong.

**Comment by NerminKarapandzic** [comment] 2023-11-27 18:36
I think you might have misunderstood me.

Here's a scenario:

http request sent from angular, browser (afterNextRender)
`this.http.get("http://localhost:4000/api/foo").toPromise();
`
Server returns: 
```
headers: {
...
Set-Cookie: "foo=bar"
}
```
We make the next request from angular, browser (afterNextRender), and if the http client has allowCredentials, then the cookie will be included. This is working fine, as expected.

But, I want to include this cookie in the request when I send the next request from angular server (ngOnInit).

And if I my initial request was from the server and I received a "Set-Cookie" header, I want this cookie to be passed down to the browser, so that in case I make the next request from the browser it will also include that cookie.

**Comment by JoostK** [comment] 2023-11-27 18:53
This can be achieved using interceptors with help from e.g. `tough-cookies` and `set-cookie-parser`, possibly abstracting it into a library.

**Comment by nkarapandzic** [comment] 2023-11-28 14:51
@JoostK so you don't think this is something that the framework should handle, we need a third party library for this?

And I've already tried hacking this up with interceptors but it's not that easy, I didn't even make it work...

**Comment by alan-agius4** [comment] 2023-11-28 17:35
Duplicate of https://github.com/angular/angular/issues/15730

**Closed** 2023-11-28 18:24 UTC
Labels: area: server, area: common/http, needs: clarification
