### ISSUE TITLE
Upgrading from Angular 8.2.7 to Ivy 9.0.0.next-7 returns Exception

### ISSUE THREAD

**Issue by sureshdotariya** [angular/angular#32809] opened 2019-09-22 18:07 UTC
# 🐞 bug report

### Is this a regression?
No

### Description

Looks like one issue is similar to https://github.com/angular/angular/issues/31314
Currently our application contains 70 screens using angular v8.2.7. Tried upgrading to V9.0.0-next-7. Here is my ng --version

<img width="567" alt="Screen Shot 2019-09-22 at 11 32 02 PM" src="https://user-images.githubusercontent.com/6160893/65392324-40487e80-dd91-11e9-9a08-5c678ba9ba20.png">

 **ng serve -0** return success. But when i launch the application in chrome, getting the below error

## 🔥 Exception or Error

<img width="758" alt="Screen Shot 2019-09-22 at 11 35 41 PM" src="https://user-images.githubusercontent.com/6160893/65392363-ba790300-dd91-11e9-8ae2-c171f662378d.png">

## 🌍  Your Environment

**Angular Version:**

V8.2.7

**Anything else relevant?**

No

**Comment by Dj-jom2x** [comment] 2019-09-23 15:41
is your project ready for ivy?

**Comment by sureshdotariya** [comment] 2019-09-23 17:54
i hope so, if not 'ng serve' should have failed right?

**Comment by gkalpak** [comment] 2019-09-25 19:34
@sureshdotariya, it is really hard to tell what might be the issue with so little info. Any chance you could share a reproduction?

Also, how did you update to V9.0.0-next-7? Via `ng update`? What do your `tsconfig`s look like after the update?

**Comment by gkalpak** [comment] 2019-09-25 19:38
Actually, this looks indeed very similar to #31314.
I am going to close this as a duplicate of #31314. If you have amy more info, please add it there.
(If this turns out to be a different problem, feel free to open a new issue.)

**Closed by gkalpak** 2019-09-25 19:38 UTC
Labels: comp: compiler, comp: ivy
