### ISSUE TITLE
propery in class('xx' in this) retrun false

### ISSUE THREAD

**Issue by wszgrcy** [angular/angular#31887] opened 2019-07-29 09:53 UTC
# 🐞 bug report

### Affected Package
none

### Is this a regression?
unknown
### Description
```ts
export class AppComponent {
  a
  constructor() {
    console.log('in chrome-console return true,but in angular-project return false', 'a' in this)
  }

}
new AppComponent()
```
output false.
But In chrome-console ,output true
## 🔬 Minimal Reproduction
[link](https://stackblitz.com/github/wszgrcy/bug-demo/tree/property-in-class)
## 🔥 Exception or Error
return true

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.0.6
Node: 10.15.3
OS: win32 x64
Angular: 8.0.3
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.6
@angular-devkit/build-angular     0.800.6
@angular-devkit/build-optimizer   0.800.6
@angular-devkit/build-webpack     0.800.6
@angular-devkit/core              8.0.6
@angular-devkit/schematics        8.0.6
@angular/cli                      8.0.6
@ngtools/webpack                  8.0.6
@schematics/angular               8.0.6
@schematics/update                0.800.6
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.30.0
</code></pre>

**Anything else relevant?**

**Comment by trotyl** [comment] 2019-07-29 10:10
Duplicate of https://github.com/microsoft/TypeScript/issues/27644

---

Not an Angular issue.

**Closed** 2019-07-29 10:54 UTC
