### ISSUE TITLE
NG_ASYNC_VALIDATORS on disabled control

### ISSUE THREAD

**Issue by Delagen** [angular/angular#11287] opened 2016-09-02 15:53 UTC
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
NG_ASYNC_VALIDATORS not called if control is disabled

**Expected/desired behavior**
NG_ASYNC_VALIDATORS called even if control is disabled.

* **Angular version:** 2.0.0-rc.6
 
* **Browser:** all
 
* **Language:** TypeScript 2.0

**Comment by pkozlowski-opensource** [comment] 2016-09-02 15:56
Hmm, not sure I see why this should be the case. If a control gets disabled a user can't change its value so in this case validation of the _user input_ doesn't make much sense, no?

I'm sure I'm missing sth here so if you could elaborate / provide a plunker it would help clarifying.

**Comment by Delagen** [comment] 2016-09-02 16:06
I agree that validation of disabled control isn't needed, but sometime value of this control can be changed in other way (i.e. by changing other control)
And Sync Validators works as expected, case only in Async validators

**Comment by Delagen** [comment] 2016-09-02 16:36
http://plnkr.co/edit/1HvbnWu03mC95E0Lh5bs?p=preview

See console output, click on button `change` then disable control by click on button `enable/disable`, and again click button `change`

**Comment by Delagen** [comment] 2016-09-02 17:39
`AbstractControl.prototype.updateValueAndValidity`
```
this._errors = this._runValidator();
```
without any condition
but for Async
```
 if (this._status == VALID || this._status == PENDING) {
            this._runAsyncValidator(emitEvent);
        }
```

**Comment by kara** [comment] 2016-09-09 00:54
Disabled controls are exempt from validation by design to match how native HTML5 forms work.  So it's expected that async validators wouldn't run in that case.  The bug here is that sync validators are still running.  Though it won't currently affect the calculation of the status, it's unnecessary and we shouldn't be calling them at all.   I'm working on a PR to ensure sync validators won't run on disabled controls either.

**Comment by Delagen** [comment] 2016-09-09 05:41
@kara I think it must be tunable

**Comment by kara** [comment] 2016-09-09 18:45
@Delagen Validators and async validators should not run on controls that are by definition exempt from validation. This would then make them subject to validation, and thus, not disabled.  What you're suggesting would both corrupt the model and diverge from the HTML5 forms spec.  For these reasons, we are closing this issue.

If you could tell me more about your specific use case, perhaps I can help with an alternative solution.

**Closed by kara** 2016-09-09 18:45 UTC
Labels: comp: forms

**Comment by Delagen** [comment] 2016-09-09 18:56
I validate value through ajax request, but set this through dialog, so user input in field is didabled

**Comment by kara** [comment] 2016-09-09 19:00
So to be clear, you want the field to be validated, but you don't want it to be editable?  Have you considered using the `readonly` property instead?  That way, the field won't be editable, but it will still be run through both sync and async validation.

**Comment by Delagen** [comment] 2016-09-09 21:59
Yes, but styling disable and readonly is different,

**Comment by sergey-malykh** [comment] 2017-12-19 08:40
@kara , Could you explain me? How I can use readonly with Reactive Form, when I dynamically change control state? I easily can manage from controller enable/disable state of control, but not readonly. Readonly property is only html
