### ISSUE TITLE
Proposal: Global template variables/constants/enums

### ISSUE THREAD

**Issue by michaeljota** [angular/angular#28658] opened 2019-02-12 16:45 UTC
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/core

### Description

There has been some requests about declaring an using global variables in Angular templates, but is currently no possible. We need to declare in the component all the variables we are going to use, but sometimes we need to use the same variables in several components making us repeat code. 

### Describe the solution you'd like
 

I was thinking about one special token that could be injected in the `NgModule` description object, or maybe a special property added to the same object. 

Using a special token: 
```ts
@NgModule({
  declarations: [
    AwesomeComponent 
  ],
  providers: [
    {
      provide: HTML_TEMPLATE_GLOBALS,
      multi: true,
      useValue: ENUM
    }
  ]
})
export class AwesomeModule {}
```

Using a new property:

```ts
@NgModule({
  declarations: [
    AwesomeComponent 
  ],
  templateProviders: [
    ENUM
  ]
}
export class AwesomeModule {}
```

In either case, the expected behavior would allow to access ENUM in every component template declared in the module. 

```ts
import { Component } from '@angular/core';

@Component({
  selector: 'awesome-component',
  template: `{{ ENUM.VALUE_ONE }}` 
})
export class AwesomeComponent {}
```

##### Using services

By the first case scenario, you may declare the ENUM as an injectable and use it as a service. However, you would still need to declare all the variables that you use, making this solution useless as just assign a property in the components.

##### Scoped variables exposed in the template
Another proposal as explained in #25963

```ts
import { someConstant } from './somewhere';
import { UserStatus } from './somewhere';
import { isDevMode } from '@angular/core';

@Component({
  selector: 'awesome-component',
  template: `
  Constant: {{ someConstant }}
  User Status: {{ UserStatus }}
  isDevMode: {{ isDevMode }}
  `,
  templateImports: { someConstant, UserStatus, isDevMode } // Per @trotyl suggestion 
})
export class AwesomeComponent {}
```

This is almost the same, but the property is named differently, is declared as an object per @trotyl suggestion, and is scoped into the component directly.

### Related issues:

- #25963 - Allow constants, enums, functions to be used in templates without having to add component members
- #12743 - Import other modules on template level (i.e. enums, static variables etc.)
- #1552 - Will angular2 support Dart enums in templates?

**Comment by pkozlowski-opensource** [comment] 2019-02-12 18:53
@michaeljota I believe that what you want to achieve is already described in #25963 so we've got a ticket to track it (and I very much agree with the need).

Regarding your proposed solution - we are pondering making `NgModule` optional (not immediately and not sure when / how, but this is a general direction). As such we don't want to add more stuff to `NgModule` and while your proposal is interesting it is unlikely to be implemented.

Do you think we can / should close this as a duplicate of  #25963 ? Or is it any new information here that warrants keeping 2 separate issues?

**Comment by michaeljota** [comment] 2019-02-12 19:16
I read #25963, and also was added for reference. I would like for this to be apply in a app wide way, but if you think is against the roadmap, then I guess that the implementation describe in there should be enough. Feel free to close this if it is the case. 

Thanks. 👍

**Comment by mhevery** [comment] 2019-02-12 23:52
closing as dupe and will not implement in a global way.

**Closed by mhevery** 2019-02-12 23:52 UTC
Labels: comp: core & compiler
