### ISSUE TITLE
Uncaught issue in compiler: TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))

### ISSUE THREAD

**Issue by shmatt** [angular/angular#36341] opened 2020-03-31 04:31 UTC
# 🐞 bug report

### Affected Package
 The issue is caused by package @angular/compiler

### Is this a regression?

It compiles with Ivy, but not for production.
If I disable Ivy, it fails to compile.

### Description

I am trying to compile my library, but angular is throwing an exception.
No doubt, something with my code is triggering it, but the compiler gives no clue what it might be.

## 🔬 Minimal Reproduction

As this issue is likely triggered specifically by my code, I can't produce a repro, but can be shared with an individual on request.

## 🔥 Exception or Error

</code>
[error] TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at __read (C:\Develop\Intellis\Clients\Ecp\Intellis.Common\intellis-angular\node_modules\@angular\compiler\bundles\compiler.umd.js:133:50)
    at __spread (C:\Develop\Intellis\Clients\Ecp\Intellis.Common\intellis-angular\node_modules\@angular\compiler\bundles\compiler.umd.js:151:28)
    at C:\Develop\Intellis\Clients\Ecp\Intellis.Common\intellis-angular\node_modules\@angular\compiler\bundles\compiler.umd.js:27133:59
    at Array.forEach (<anonymous>)
    at StaticReflector.propMetadata (C:\Develop\Intellis\Clients\Ecp\Intellis.Common\intellis-angular\node_modules\@angular\compiler\bundles\compiler.umd.js:27123:40)
    at DirectiveResolver.resolve (C:\Develop\Intellis\Clients\Ecp\Intellis.Common\intellis-angular\node_modules\@angular\compiler\bundles\compiler.umd.js:20073:60)
    at CompileMetadataResolver.isAbstractDirective (C:\Develop\Intellis\Clients\Ecp\Intellis.Common\intellis-angular\node_modules\@angular\compiler\bundles\compiler.umd.js:22281:48)
    at C:\Develop\Intellis\Clients\Ecp\Intellis.Common\intellis-angular\node_modules\@angular\compiler\bundles\compiler.umd.js:26761:47
    at Array.forEach (<anonymous>)
    at analyzeFile (C:\Develop\Intellis\Clients\Ecp\Intellis.Common\intellis-angular\node_modules\@angular\compiler\bundles\compiler.umd.js:26746:57)

</pre>

## 🌍  Your Environment

**Angular Version:**
<pre>9.1.0<code>

**Comment by alxhub** [comment] 2020-05-26 20:55
Hello @shmatt,

Without a reproduction or access to your application, I'm not sure I can be of much help. I have seen issues like this in the past with View Engine when users have method names that shadow JS builtins (e.g. defining a `hasOwnProperty` method in a class somewhere), but I have no idea if that's what's going on here.

I'll be honest - it's unlikely this bug will be a priority to fix, as it's quite rare and also not present in the Ivy compiler which is the replacement for View Engine.

**Comment by petebacondarwin** [comment] 2020-11-02 20:08
Closing due to a lack of reproduction and it only affects the deprecated ViewEngine mode of compilation.

**Closed by petebacondarwin** 2020-11-02 20:08 UTC
Labels: P5, comp: compiler, engine: ve, freq1: low, hotlist: error messages, needs clarification, needs reproduction, triage #1, type: bug/fix
