### ISSUE TITLE
Bound CSSClass not replaced after router navigation

### ISSUE THREAD

**Issue by thelgevold** [angular/angular#3168] opened 2015-07-21 01:22 UTC
I have noticed that a bound CssClass value is not updated after router navigation. The old value is not replaced by the new value during data binding. Instead it leaves the existing one behind and adds the new one next to it when it's rebound.

I am updating the class via a function which works ok on click, but for some reason the class is not replaced when navigating using the new router.

Element:
```<a (click)="selectComponent('grid')"  [class]="getActiveClass('grid')" class="list-group-item">Link</a>```
//Class is updated correctly when initiated via click, but not via router navigation.

You can see the behavior here: http://www.syntaxsuccess.com/angular-2-samples

Repro steps:

Successful:
Click the left nav and see the active link update correctly (bootstrap blue active clas). 

Failure:
Select any of the left nav links other than the first element
Click the 'About' link in the top navigation
Click the 'Demo' link in the top navigation
Observe that there are two highlighted links in the left nav.
After debugging it I noticed that the correct functions fire, but the class property is not overwritten by the binding.

Source code can be found here: https://github.com/thelgevold/angular-2-samples

**Comment by matanlurey** [comment] 2015-07-21 04:32
I'm not sure this has anything to do with CSS class, but rather `location.path()` not updating.

**Comment by thelgevold** [comment] 2015-07-21 13:03
Yeah it might not be an issue with the css property itself. Seems to be an issue with updating the class when routing is the trigger that caused the bindings to be re-evaluated. What I am seeing is that the new bound value doesn't replace the old value. Instead you are left with both values - both new and old.
Works ok on button click though.

**Comment by tbosch** [comment] 2015-07-23 23:55
Duplicate of #3249.

**Closed by tbosch** 2015-07-23 23:55 UTC
Labels: comp: router, effort2: medium (day), P2: required, type: bug

**Comment by thelgevold** [comment] 2015-07-24 01:51
Which alpha version fixes this problem?

**Comment by tbosch** [comment] 2015-07-24 03:11
It's fixed on master, so it will be accessible on npm as of alpha34

**Comment by thelgevold** [comment] 2015-07-24 11:10
Thanks!

**Comment by thelgevold** [comment] 2015-07-31 21:27
This issue is fixed as of alpha.33.
Upgraded the samples: http://www.syntaxsuccess.com/angular-2-samples
