### ISSUE TITLE
flickering of elements with fixed or absolute positioning. After updating to Angular 19.

### ISSUE THREAD

**Issue by AndSokolov** [angular/angular#59129] opened 2024-12-10 09:44 UTC
### Which @angular/* package(s) are the source of the bug?

compiler-cli

### Is this a regression?

Yes

### Description

After upgrading from 17 Angular to 19 Angular. Components with “fixed” or “absoulute” positioning began to work poorly.
For example, when you click on the filter button, a window with filters with absolute positioning appears. At the beginning, it seems to shift elements for milliseconds, which are with static positioning, and then it is displayed normally.
Unpleasant flickering appeared on the page.

I use "builder": "@angular-devkit/build-angular:application"

### Please provide a link to a minimal reproduction of the bug

https://github.com/AndSokolov/angular19

### Please provide the exception or error you saw

```true

```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 19.0.2
Node: 20.11.1
Package Manager: yarn 1.22.22
OS: win32 x64

Angular: 19.0.1
... animations, cdk, common, compiler, compiler-cli, core, forms
... material, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1900.2
@angular-devkit/build-angular   19.0.2
@angular-devkit/core            19.0.2
@angular-devkit/schematics      19.0.2
@angular/cli                    19.0.2
@schematics/angular             19.0.2
rxjs                            7.8.1
typescript                      5.6.2
zone.js                         0.15.0
```

### Anything else?

After pressing the button, a flickering occurs.
The problem disappears if you change the builder in angular.json to "builder": "@angular-devkit/build-angular:browser"

**Comment by joewIST** [comment] 2024-12-10 10:41
This might be linked to #59058

**Comment by clydin** [comment] 2024-12-10 11:55
Duplicate of #59058

**Closed by clydin** 2024-12-10 11:55 UTC
