### ISSUE TITLE
DI: new Provider(Foo, () => '') should work, instead throws

### ISSUE THREAD

**Issue by matanlurey** [angular/angular#5384] opened 2015-11-19 19:14 UTC
The following provider does not actually work:

```dart
const fooToken = const OpaqueToken('fooToken');

Injector.resolveAndCreate([
  new Provider(fooToken, useFactory: () => 'Bar')
]);
```

Instead, it only works if you change the signature to

```dart
new Provider(fooToken, useFactory: () => 'Bar', deps: const [])
```

Can the default be `deps: const []` instead of failing?

**Comment by PascalPrecht** [comment] 2015-11-19 19:21
But this is a Dart-only problem, righ?

**Comment by vsavkin** [comment] 2015-11-24 23:31
Closing because it is a duplicate of https://github.com/angular/angular/issues/4866

**Closed by vsavkin** 2015-11-24 23:31 UTC
Labels: comp: core/di, effort1: easy (hour), P1: urgent, type: bug
