### ISSUE TITLE
Missing directives should cause Template Error

### ISSUE THREAD

**Issue by Ristaaf** [angular/angular#20588] opened 2017-11-22 15:11 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When trying to use a directive that is not included in the module, the angular-compiler fails silently, this is not the case for when trying to use a pipe or component not included, then the compiler fails with warnings.

## Expected behavior

Similar to the warnings for components and pipes I would like to see "Uncaught Error: Template parse errors: The directive 'xxx' could not be found.

## Minimal reproduction of the problem with instructions

https://plnkr.co/edit/R4SWqUxjwEYYE3VidR5h

## What is the motivation / use case for changing the behavior?

When creating new modules, or as in my case refactoring big modules into smaller ones, it is easy to use the errors to find which other modules you need to import to make your module work, however since missing directives don't throw errors, it is easy to miss including them in modules.

We have had some bugs because of this, that were really hard to figure out.

## Environment

<pre><code>
Angular version: 5.0.1

Browser:
- [x] Chrome (desktop) version 62
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.9.1  
- Platform:  Windows

Others:

</code></pre>

**Comment by pkozlowski-opensource** [comment] 2017-11-22 16:53
This is a duplicate of #3425

**Closed by pkozlowski-opensource** 2017-11-22 16:53 UTC
