### ISSUE TITLE
Child Component DOM Removal kills TouchEvents in Parent

### ISSUE THREAD

**Issue by dharders** [angular/angular#8035] opened 2016-04-13 06:12 UTC
**Steps to reproduce**  - see Plnkr demo below (**_touchscreen required_**)

I have a Parent Component with an array (of Child Components) that is rendered using **\*ngFor**.

`<my-child-cmp *ngFor="#child of children" [info]="child" ... ></my-child-cmp>`

Within MyChildCmp I have an event listener to detect which child is being dragged

```
@HostListener('mousedown', ['$event'])
@HostListener('touchstart', ['$event'])
onDragStart(event) {
    this.selected.emit(this.info.id);
}
```

The Parent Component enables each Child Component to be '_Dragged_' about the screen by

 ```
@HostListener('mousemove', ['$event'])
@HostListener('touchmove', ['$event'])
onDragMove(event) { 
  ...
}
 
@HostListener('mouseup', ['$event'])
@HostListener('touchend', ['$event'])
@HostListener('touchcancel', ['$event'])
onDragEnd(event) { 
   ...
}
```

**However**, if an event causes the _children_ array to be updated **during a drag**, it causes the TouchEvents (i.e. touchmove, touchend, touchcancel) to **stop firing** if the Child component was removed from the DOM. Using a mouse instead of touchscreen **has no issues whatsoever!**

**Use case**: Appointment bookings system. Child Component is a booking, you drag the booking to the 'Next Day' button, which updates the children array to the next day's bookings. Angular 2 removes the previous days bookings from the DOM (even when touchstart is stiil bound to removed element)

See my Plnkr demo below, where I update the _children_ array **_after 2 seconds of dragging_**.

_Plnkr Demo: https://plnkr.co/edit/1RzYpEgCI0y60pCauvGp?p=preview_

**Expected/desired behavior**: If the mouse behaviour works, I'd expect the touch equivalent to work the same.

Angular2 should give the user programmatic ability to keep a single component from being removed from the DOM (i.e. the component being dragged) OR first check if there is an active **_touchstart_** event on a Component it is about to remove from the DOM. It'd be great if it wasn't removed until _touchend_ or _touchcancel_ was fired (maybe setting display: none?)

**Other information**
Tested in: Chrome 49.0.2623.87 m (Win7 Touchscreen) and iOS Safari 9.2.1
Angular2 Beta14

**Comment by dharders** [comment] 2016-04-13 06:26
Note: This seems to be a Browser implementation detail of the w3 spec on TouchEvents

i.e. this isn't strictly an Angular2 issue (I can reproduce the same behaviour without Angular2 - see my jsFiddle https://jsfiddle.net/hjvz63gt/6/)

However, I could normally code around these shortcomings by keeping the element reference in memory myself until touchend, touchcancel. With Angular 2 handling DOM manipulations for me, I don't have the luxury.

So the issue still stands, if you **touchstart a child element** (even if you haven't subscribed to the event) and it is removed from the DOM, subsequent touch events never fire until you lift your finger and start again.

I'm surprised I haven't seen more touch event issues by other devs... unless they're not testing on touch screens... or I'm doing something fundamentally wrong!

**Comment by dharders** [comment] 2016-04-27 06:38
If feature request #5275 gets implemented, I could simply flag my _dragged_ component with a `preventDestruction = true` during the drag and reset it back to `preventDestruction = false` on touchend/touchcancel.

Angular could then destroy the component as usual. I like this approach...

**Comment by dharders** [comment] 2016-07-20 02:43
Issue still present in RC4. 

Hoping this gets resolved before final. Or at least some guidance from the Angular team to work around the limitation.

**Comment by dharders** [comment] 2016-08-11 01:02
Issue still present in RC5.

Moved this issue to #9864     (closing this one)

**Comment by dharders** [comment] 2016-08-15 01:31
Found a workaround:

TouchEvents do actually continue to fire after DOM removal **BUT** they are only targeted at the node/element that the original `touchstart` occurred on and don't bubble (unlike MouseEvents, which is confusing!).

So, we cant perform a simple `@HostListener('touchmove', ['$event'])` and expect it to work with DOM removal (as the event listener is attached to the outer component element). We have to dynamically add event listeners to the **target element** of the **touchstart** event as they occur. Then perform cleanup on `touchend` or `touchcancel` (or `ngOnDestroy()`).

Soln:
```typescript
@HostListener('touchstart', ['$event'])
@HostListener('mousedown', ['$event'])
  dragStart(event) {
    if (event.touches) {    // avoid touch event loss issue
      this.removePreviousTouchListeners();    // avoid mem leaks      
      this.touchmoveListenFunc = this.renderer.listen(event.target, 'touchmove', (e) => { this.onDragMove(e); });
      this.touchendListenFunc = this.renderer.listen(event.target, 'touchend', (e) => { this.removePreviousTouchListeners(); this.onDragEnd(e); });
      this.touchcancelListenFunc = this.renderer.listen(event.target, 'touchcancel', (e) => { this.removePreviousTouchListeners(); this.onDragEnd(e); });
    }
   ...
}

removePreviousTouchListeners() {
    if (this.touchmoveListenFunc !== null)
      this.touchmoveListenFunc();             // remove previous listener
    if (this.touchendListenFunc !== null)
      this.touchendListenFunc();              // remove previous listener
    if (this.touchcancelListenFunc !== null)
      this.touchcancelListenFunc();           // remove previous listener
    
    this.touchmoveListenFunc = null;
    this.touchendListenFunc = null;
    this.touchcancelListenFunc = null;
  }

 @HostListener('mousemove', ['$event'])
  // @HostListener('touchmove', ['$event'])    // don't declare this, as it is added dynamically
  onDragMove(event) {
    ...   // do stuff with event
  }

@HostListener('mouseup', ['$event'])
  // @HostListener('touchend', ['$event'])     // don't use these as they are added dynamically
  // @HostListener('touchcancel', ['$event']) // don't use these as they are added dynamically
  onDragEnd(event) {
    ...  // do stuff
  }

 ngOnDestroy() {
   this.removePreviousTouchListeners();
```

Don't forget to inject `Renderer` in the constructor (import from `@angular/core`

Source [https://plus.google.com/+RickByers/posts/GHwpqnAFATf](https://plus.google.com/+RickByers/posts/GHwpqnAFATf)

**Comment by vicb** [comment] 2016-10-06 23:03
duplicate of https://github.com/angular/angular/issues/9864

**Closed by vicb** 2016-10-06 23:03 UTC
Labels: comp: core & compiler
