### ISSUE TITLE
Safari 10.1.2, localhost:4200 results in ReferenceError: Can't find variable: SockJS

### ISSUE THREAD

**Issue by 6zz** [angular/angular#20247] opened 2017-11-07 17:57 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

> ng serve
visit http://localhost:4200 with Safari 10.1.2 (on Mac) -- blank page, console error "ReferenceError: Can't find variable: SockJS"

## Expected behavior

page loads successfully without any error

## Minimal reproduction of the problem with instructions

1. ng new safari
2. cd safari
3. ng serve -o

## What is the motivation / use case for changing the behavior?

A bug needs to be fixed

## Environment

<pre><code>
Angular CLI: 1.5.0
Node: 6.10.3
OS: darwin x64
Angular: 5.0.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.5.0
@angular-devkit/build-optimizer: 0.0.32
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.35
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.0
@schematics/angular: 0.1.1
typescript: 2.4.2
webpack: 3.8.1

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [x] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v6.10.3  
- Platform:  Mac 

Others:

In addition, if we run the prod version with *ng serve --prod*, then the error becomes:

> main.5dae63aa89ca364c42ad.bundle.js:1SyntaxError: Cannot declare a let variable twice: 'e'.

</code></pre>

**Comment by Toxicable** [comment] 2017-11-07 19:11
I'm sorry but we can't reproduce the problem following the instructions you provided.

If the problem still exists please open a new issue following [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue).

**Comment by 6zz** [comment] 2017-11-07 21:56
could you double check if you had the same packages?  cli, node, and browser version?

safari-10.1.2
Angular CLI: 1.5.0
Node: 6.10.3
OS: darwin x64
Angular: 5.0.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.5.0
@angular-devkit/build-optimizer: 0.0.32
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.35
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.0
@schematics/angular: 0.1.1
typescript: 2.4.2
webpack: 3.8.1

**Comment by 6zz** [comment] 2017-11-07 22:05
basically, it appears safari-10.1.2 does not like or understand the `const` definition.  
![screen shot 2017-11-07 at 2 04 45 pm](https://user-images.githubusercontent.com/9967532/32520381-a7689cd2-c3c4-11e7-989e-4757ddfdb1b0.png)

**Comment by alfredobialo** [comment] 2017-11-08 02:31
I also got thesame error message in Firefox 27, 47 with Angular 5, but when
i updated Firefox to 56, the error was gone. Pls try and fix the bug 🐛

**Comment by trotyl** [comment] 2017-11-08 03:20
@6zz @alfredobialo No matter what is causing the problem it's not an Angular issue, `SockJS` is used by [Angular CLI](https://github.com/angular/angular-cli) in [webpack-dev-server](https://github.com/webpack/webpack-dev-server) for live-reloading, there is nothing to do with it in this repo.

**Comment by Timmaex** [comment] 2017-11-08 08:47
+1 got the Same Issue reproduced with identical Packages installed.
Additional Info: If you serve as --prod --aot Safari shows additional Errors:

`[Error] SyntaxError: Cannot declare a let variable twice: 't'.
[Error] TypeError: undefined is not an object (evaluating 'e[r].call')`

All referred Functions are from Webpack

**Comment by meiordac** [comment] 2017-11-08 12:56
I got the same error using same CLI, Angular version.

**Comment by remisture** [comment] 2017-11-08 14:23
The same happens in iOS 9.3.

**Comment by 6zz** [comment] 2017-11-08 19:26
@trotyl nonetheless, the fix needs to come from the cli because the users of the cli do not bring in web-dev-server manually.  It's part of the install from cli.  If there is a patch/workaround in web-dev-server that fixes the situation the cli needs to pull in the correct version/patch/workaround.

**Comment by trotyl** [comment] 2017-11-09 05:50
@6zz The problem is, you're not supposed to raise [Angular CLI](https://github.com/angular/angular-cli) issue here, that's a different project and repo.

**Comment by trotyl** [comment] 2017-11-09 05:57
Make it simple: duplicate of https://github.com/angular/angular-cli/issues/8400

**Comment by jasonaden** [comment] 2017-11-09 21:04
Thanks for reporting this issue. However this issue is a duplicate of an existing issue angular/angular-cli#8400. Please subscribe to that issue for future updates.

**Closed by jasonaden** 2017-11-09 21:04 UTC

**Comment by 6zz** [comment] 2017-11-13 18:59
apologies, I didn't realize a separate repo for cli.  thank you
