### ISSUE TITLE
Cannot combine @Input decorators with query decorators

### ISSUE THREAD

**Issue by hukaixuan2017** [angular/angular#31396] opened 2019-07-03 04:49 UTC
<!--🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅

Oh hi there! 😄

I installed angular 8 and ran a project developed on angular 7 with the following error ：

Cannot combine @Input decorators with query decorators

 I didn't indicate which line was wrong. Is this a bug?
![image](https://user-images.githubusercontent.com/29294119/60564079-f0a97680-9d90-11e9-9a17-c5ef5b472079.png)

**Comment by pkozlowski-opensource** [comment] 2019-07-03 11:56
Looks like you've opened 2 issues with the same title, closing as a duplicate of #31398

**Closed by pkozlowski-opensource** 2019-07-03 11:56 UTC
