### ISSUE TITLE
After update to version 19, child views do not return a correct offset width in any component initialization phases!

### ISSUE THREAD

**Issue by xaroxhoan** [angular/angular#58739] opened 2024-11-19 15:15 UTC
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

I'm using the `viewChild` function to query a div element. I needed to get its offset width in the initialization phase. But it does not work properly. I tried decorator-based syntax, but the issue was still standing!

### Please provide the exception or error you saw

```true

```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 19.0.0-rc.3
Node: 20.15.0
Package Manager: yarn 1.22.22
OS: win32 x64

Angular: 19.0.0
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1900.0-rc.3
@angular-devkit/build-angular   19.0.0-rc.3
@angular-devkit/core            19.0.0-rc.3
@angular-devkit/schematics      19.0.0-rc.3
@angular/cli                    19.0.0-rc.3
@schematics/angular             19.0.0-rc.3
rxjs                            7.8.1
typescript                      5.6.3
zone.js                         0.15.0
```

**Comment by JeanMeche** [comment] 2024-11-19 15:24
Hi, could you provide a stackblitz reproduction of this issue ? Without this is isn't really actionnable to us. 

One guess whould be that you're accessing the offset too early and should probably do it in an `afterRenderEffect()` or in `afterNextRender()` to make sur that the DOM is correctly rendered when you access it.

**Comment by JoostK** [comment] 2024-11-19 15:31
I suspect this may be because of HMR support, duplicating #58629.

**Comment by xaroxhoan** [comment] 2024-11-19 15:32
Hi, its simple code block
```
wrapper = viewChild<ElementRef<HTMLDivElement>>('wrapper');

  render = afterRender(() => {
    console.log('width: ', this.wrapper()?.nativeElement?.offsetWidth);
  });

  afterRender = afterRender(() => {
    console.log('width: ', this.wrapper()?.nativeElement?.offsetWidth);
  });

  nextRender = afterNextRender(() => {
    console.log('width: ', this.wrapper()?.nativeElement?.offsetWidth);
  });

  renderEffect = afterRenderEffect(() => {
      console.log('width: ', this.wrapper()?.nativeElement?.offsetWidth);
  });
```
The `#wrapper` element width fixed to 500px, but in all mentioned phases it logged as windows width!

**Comment by JeanMeche** [comment] 2024-11-26 19:17
Closing as we didn't get any feedback from OP.

**Closed** 2024-11-26 19:38 UTC
Labels: needs reproduction, area: core
