### ISSUE TITLE
local variables in templates don't accept uppercase characters

### ISSUE THREAD

**Issue by nkvenom** [angular/angular#5224] opened 2015-11-10 20:39 UTC
When creating a local variable in a template with the pound symbol works only with lowercase names.

Example that works:
```
<input type="text" #varf (keyup)="$event"> {{varf.value}}
```
Example that doesn't works (note the uppecase F):
```
<input type="text" #varF (keyup)="$event"> {{varF.value}}
```

[Plunker example](http://plnkr.co/edit/kPCYkVwMRz3HEIcnffUt?p=preview)

**Comment by pkozlowski-opensource** [comment] 2015-11-10 20:41
See https://github.com/angular/angular/issues/3398 and https://github.com/angular/angular/issues/4923

Closing as a duplicate of #4923

**Closed by pkozlowski-opensource** 2015-11-10 20:41 UTC

**Comment by nkvenom** [comment] 2015-11-11 21:59
Sorry, I didn't see those others before
