### ISSUE TITLE
NgComponentOutlet documentation link is not correct.

### ISSUE THREAD

**Issue by dionis-d** [angular/angular#53656] opened 2023-12-20 17:30 UTC
### Describe the problem that you experienced

While reading the documentation:
https://angular.dev/guide/components/programmatic-rendering#using-ngcomponentoutlet
I clicked `NgComponentOutlet API reference` link. 
It redirects the page here:
https://angular.dev/api/core/NgComponentOutlet
![image](https://github.com/angular/angular/assets/31817527/cebdc151-2d60-47b5-8beb-221879dfb163)

### Enter the URL of the topic with the problem

https://angular.dev/guide/components/programmatic-rendering#using-ngcomponentoutlet

### Add a screenshot if that helps illustrate the problem

![image](https://github.com/angular/angular/assets/31817527/2cb00d81-7417-4a4e-a2ec-0a83d9c29341)

**Comment by JoostK** [comment] 2023-12-20 18:13
Thanks for the report, closing as a duplicate of https://github.com/angular/angular/issues/52828

**Closed by JoostK** 2023-12-20 18:13 UTC
