### ISSUE TITLE
Angular build is not working with bazel

### ISSUE THREAD

**Issue by ronakpandya7** [angular/angular#30350] opened 2019-05-09 10:28 UTC
Hello,
## 🌍  Your Environment
`We are using Windows 2010`

**Angular Version:**
<pre><code>
   _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 8.0.0-rc.3
Node: 10.15.3
OS: win32 x64
Angular: 8.0.0-rc.3
... animations, bazel, cli, common, compiler, compiler-cli, core
... forms, language-service, platform-browser
... platform-browser-dynamic, router, upgrade

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.0-rc.3
@angular-devkit/build-angular     0.800.0-rc.3
@angular-devkit/build-optimizer   0.800.0-rc.3
@angular-devkit/build-webpack     0.800.0-rc.3
@angular-devkit/core              8.0.0-rc.3
@angular-devkit/schematics        8.0.0-rc.3
@ngtools/webpack                  8.0.0-rc.3
@schematics/angular               8.0.0-rc.3
@schematics/update                0.800.0-rc.3
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.30.0

</code></pre>

# 🐞 bug report

We want to test bazel building functionality for our angular application.
So for that we installed `@angular/cli` with version `8.0.0-rc.3` which have inbuilt bazel support.

and then create our application using following command:

`ng new bzl-test --collection=@angular/bazel`

So it creates one angular application with bazel building functionality.

Now when we try to build the application using `ng build --leaveBazelFilesOnDisk` command it gives the following error:

```
 *** WARNING
    The Bazel binary is being run from a global install.

    This means the version may not match the one used in your project.
    We recommend installing the @bazel/bazel package locally in your project.
  ***
  
WARNING: Ignoring JAVA_HOME, because it must point to a JDK, not a JRE.
Starting local Bazel server and connecting to it...
ERROR: error loading package '': Encountered error while reading extension file 'install_bazel_dependencies.bzl': no such package '@npm//': Traceback (most recent call last):
	File "/home/ravishah/.cache/bazel/_bazel_ravishah/776b63375a85e7ea8afb469078e08664/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 240
		repository_ctx.template("yarn.lock", repository_ctx.path(r...), {})
	File "/home/ravishah/.cache/bazel/_bazel_ravishah/776b63375a85e7ea8afb469078e08664/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 242, in repository_ctx.template
		repository_ctx.path(repository_ctx.attr.yarn_lock)
Not a regular file: /home/ravishah/workspace/Ravi/Demo/Bazel/test-bazel/yarn.lock
ERROR: error loading package '': Encountered error while reading extension file 'install_bazel_dependencies.bzl': no such package '@npm//': Traceback (most recent call last):
	File "/home/ravishah/.cache/bazel/_bazel_ravishah/776b63375a85e7ea8afb469078e08664/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 240
		repository_ctx.template("yarn.lock", repository_ctx.path(r...), {})
	File "/home/ravishah/.cache/bazel/_bazel_ravishah/776b63375a85e7ea8afb469078e08664/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 242, in repository_ctx.template
		repository_ctx.path(repository_ctx.attr.yarn_lock)
Not a regular file: /home/ravishah/workspace/Ravi/Demo/Bazel/test-bazel/yarn.lock
INFO: Elapsed time: 6.844s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
```
So what is the issue here?
Are we missing something here?

Thanks in advance,
Ronak Pandya

**Comment by alexeagle** [comment] 2019-05-10 18:30
Sorry this is a duplicate of https://github.com/angular/angular/issues/30164

the fix is to change `yarn_install` to `npm_install` in the `/WORKSPACE` file, and change `yarn_lock_json` to `package_lock_json`

**Closed by alexeagle** 2019-05-10 18:30 UTC
Labels: comp: bazel
