### ISSUE TITLE
tutorial: Instructed to link styles.css despite it being included in styles.bundle.js

### ISSUE THREAD

**Issue by Mortichar** [angular/angular#17904] opened 2017-07-03 02:24 UTC
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[ ] Bug report 
[ ] Feature request
[X] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Tutorial in routing https://angular.io/tutorial/toh-pt5#global-application-styles instructs to create a styles.css and then \<link\> it in the index.html. This issue is that the styles.css is already included in the "styles" of .angular-cli.json using ng new <project-name>, and are compiled into dist/styles.bundle.js. The "styles.css" is not in the "assets": [] of .angular-cli.json so it will not be included in the build and people going through the tutorial will get a 404 in their console when requesting the stylesheet on pageload.

## Expected behavior

Remove the instructions stating to \<link\> the stylesheet, as it is unnecessary because it is included in styles.bundle.js and causes 404s

## Minimal reproduction of the problem with instructions
ng new \<project\>
cd \<project\>
ng serve
Add to head contents of src/index.html \<link rel="stylesheet" href="styles.css"\>
Proceed to get 404s at localhost:4200 because styles.css isn't copied as an asset but is compiled into styles.bundle.js

## What is the motivation / use case for changing the behavior?
Remove conflicting advice from tutorial.

## Please tell us about your environment

<pre><code>
Angular: 4.2.5
angular-cli v 1.2.0

Browser:
- [X] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX 
- Platform: 

Others:
N/A
</code></pre>

**Comment by Foxandxss** [comment] 2017-07-03 10:57
The problem is that the tutorial is not meant to be used with the angular-cli but the [quickstart](https://github.com/angular/quickstart).

That doesn't mean that you can't really do it with the CLI but the instructions are not meant for that, hence your styles conflict in here.

Sorry for the inconvenience, we are planning the migration of the docs to use the CLI.

**Comment by Mortichar** [comment] 2017-07-03 19:27
Alright, makes sense.

While the setup of the tutorial instructs you on how to start an angular project without the cli, there is a link at the bottom of the Getting Start page (that uses the cli) that takes the user to the tutorial stating that they are ready. Anyone following that link will assume that the instructions *are* for use with the cli, because it immediately follows the cli quickstart.

**Comment by kapunahelewong** [comment] 2018-01-04 21:07
Closing because this has been corrected in the update to CLI-based docs. @Mortichar if you have any outstanding questions, please let me know.

**Closed by kapunahelewong** 2018-01-04 21:07 UTC
Labels: comp: docs
