### ISSUE TITLE
Create an on-the-fly test component wrapper for testing components

### ISSUE THREAD

**Issue by dpurp** [angular/angular#10743] opened 2016-08-12 18:12 UTC
**I'm submitting a feature request**  (check one with "x")

```
[ x ] feature request
```

**Current behavior**
Currently when testing a component we need to manually create a new component for testing inputs set on the template which is pretty verbose and difficult to test templates with optional bindings and various input parameters.

For example:

``` typescript
// Component used to setup our test.
@Component({
  selector: 'my-comp',
  template: '<my-component [someInput]="foo" [otherInput]="bar"></my-component>',
  directives: [MyComponent],
})
class MyTestComponent {
  foo = 'abc';
  bar = 123;
}
```

**Expected/desired behavior**
Instead, it would be nice to have TestBed create an on-the-fly test wrapper for our component so that we can pass in the component, the template using the component, and a set of bindings for the template.  

Consider something along the lines of:

``` typescript
const foo = 'abc';
const bar = 123;
const fixture = TestBed.compile(MyComponent, 
    '<my-component [someData]="foo" [otherData]="bar"></my-component>', {foo, bar});
```

**What is the motivation / use case for changing the behavior?**
- More concise testing
- Easier to test different template bindings

**Please tell us about your environment:**
- **Angular version:** 2.0.0-rc.5
- **Browser:** [ all ] 
- **Language:** [ all ]

**Comment by juliemr** [comment] 2016-08-13 00:33
I agree that making a whole new component can feel kind of verbose. I want to think about the API here carefully - the risk is that if we keep adding options, it becomes as complex as the initial and then we've got two duplicate syntaxes :)

My first inclination: don't support input/output. Just a template.

```
let fixture = TestBed.createComponentFromTemplate('<whatever>');
```

**Comment by dpurp** [comment] 2016-08-15 18:01
I would actually argue that this really needs to support inputs, but, I agree that outputs may be a bit too much.

We rarely have any components that don't have any inputs, and supporting such an API doesn't add much incremental value over TestBed.createComponent(MyComponent)`.

**Comment by ErinCoughlan** [comment] 2016-08-15 18:36
+1 for supporting inputs as well. This makes it a lot easier to see all test input within the same test.

`let fixture = TestBed.createComponentFromTemplate('<whatever my-attr="input1">', {input1: inputVal};`

**Comment by dpurp** [comment] 2016-08-17 18:18
Here's an example of implementing this directly in client code.

```typescript
beforeEach(async(() => {
    TestBed.configureTestingModule({
      declarations: [MyComponent, TestWrapperComponent],
    });
  }));

@Component({
  selector: 'test-wrapper',
  template: '',
})
class TestWrapperComponent {}

function buildComponent(
    template: string,
    bindings: {[binding: string]: any} = {}): Promise<ComponentFixture<TestWrapper>> {
  TestBed.overrideComponent(
      TestComponent, {set: {template, inputs: Object.keys(bindings)}});
  return TestBed.compileComponents().then(() => {
    // Note: we can also use TestWrapperComponent.prototype[binding] instead of
    // Object.assign; however, using Object.assign more closely matches
    // Angular, wherein the inputs are not available on construction.
    const fixture = TestBed.createComponent(TestWrapperComponent);
    (Object as any).assign(fixture.componentInstance, bindings);
    return fixture;
  });
```

**Comment by huygaa11** [comment] 2016-08-31 00:51
What should be done in the situation when there are 2 components, template 1 (T1) has templateURL, and template 2 (T2) does not. And the goal is to override T2 in the fly.

Problem is:
T1 requires `TestBed.compileComponents()` to be called, which would also compile T2. However, after being compiled, T2 cannot be overridden. 

Is there a way to only compile T1, and not compile T2? Thanks

**Comment by huygaa11** [comment] 2016-08-31 18:07
Let's say I have 2 tests, both builds wrapper components. And MyComponent has templateURL.

`test1: 
buildComponent('template1');`
`test2: buildComponent('template2');`

This gives an error:
`Failed: This test module uses the component MyComponent which is using a "templateUrl", but they were never compiled. Please call "TestBed.compileComponents" before your test.`

It seems like compileComponents require all components with tempateURL to be compiled before tests. However, each test has to override the template of the component, therefore, requires the component to be not compiled. What is the best way to approach this?

Thanks.

**Comment by juliemr** [comment] 2016-08-31 18:16
If you are overriding, you need to do that before calling `TestBed.compileComponents`. So you'd need to call `compileComponents` inside your `it` block if each individual test is overriding.

**Comment by vicb** [comment] 2016-08-31 18:17
> If you are overriding, you need to do that before calling TestBed.compileComponents

Do we have a check in place ?

**Comment by juliemr** [comment] 2016-08-31 18:19
See https://github.com/angular/angular/issues/10712

**Comment by huygaa11** [comment] 2016-08-31 18:21
When the component has `templateURL` and I put `compileComponents` inside the `it` block, error message shows up:
`Failed: This test module uses the component MyComponent which is using a "templateUrl", but they were never compiled. Please call "TestBed.compileComponents" before your test.`

Therefore, it requires me to put `compileComponents` outside of the `it` block.

**Comment by juliemr** [comment] 2016-08-31 18:25
@huygaa11 remember that `compileComponents` is asynchronous, so you'll have to do future work (like creating components) after its promise has resolved.

**Comment by alxhub** [comment] 2022-04-14 23:20
Closing as a spiritual duplicate of #12313. In general, we want to rethink interactions with inputs/outputs/change detection of the component under test in `TestBed`.

**Closed by alxhub** 2022-04-14 23:20 UTC
Labels: feature, comp: testing, insufficient votes, votes required
