### ISSUE TITLE
Sidenav/mat-drawer not animating until toggled once

### ISSUE THREAD

**Issue by jacobsorme** [angular/angular#44394] opened 2021-12-07 18:25 UTC
### Which @angular/* package(s) are the source of the bug?

animations

### Is this a regression?

No

### Description

I am using this example in Angular Docs:  tosize, an autosizing sidenav. 
https://material.angular.io/components/sidenav/overview#sidenav-autosize

The sidenav is not animating its width until the sidenav is toggled once. See attached GIF. 

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/xoupcp--run?file=src/app/sidenav-autosize-example.html

### Please provide the exception or error you saw

```true
N/A
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
13.0.2 (Can't run `ng version` inside the StackBlitz example)
```

### Anything else?

![screen-capture](https://user-images.githubusercontent.com/18684167/145085326-bfe78f3e-a665-45c6-86f5-fa2c0d2bf1c1.gif)

**Comment by AndrewKushnir** [comment] 2021-12-08 05:41
@jacobsorme it looks like the Stackblitz project that you've mentioned doesn't work (I see the "The page you requested couldn't be found." error). Could you please re-create the repro? Thank you.

**Comment by jacobsorme** [comment] 2021-12-08 07:04
I see, sorry about that. It it the same example as on the Angular Docs (https://material.angular.io/components/sidenav/overview#sidenav-autosize), but changed so that the sidenav/drawer is open by default. Will try to get a link working.

**Comment by alxhub** [comment] 2022-03-04 00:10
Closing as no reproduction was provided - @jacobsorme feel free to reopen with a new stackblitz if you're still encountering this issue.

**Closed by alxhub** 2022-03-04 00:10 UTC
Labels: comp: animations, needs reproduction
