### ISSUE TITLE
Don't make `track` keyword mandatory in `for` statements

### ISSUE THREAD

**Issue by jpike88** [angular/angular#52316] opened 2023-10-23 02:19 UTC
### Which @angular/* package(s) are relevant/related to the feature request?

`17.0.0-rc.0`

### Description

I understand that the `track` keyword is useful for performance reasons, and was using angular from the 1.x days where `track by` could make a big difference in heavy loops. It saved me in a couple of components at the time which without it would have been major UX problems so I totally understand its purpose and benefits.

However I don't think it should be mandatory, because:

- the most common use case has no performance implications, but the developer would still have to specify the tracking property
- is unable to fully align with JS convention, where `for...of` doesn't have such a `track` property
- it's simple to assume that if no `track` is specified, then the item being iterated is what is being tracked, no need to explicitly say it each time
- Allow for when it IS being explicitly defined, it's defining a performance-sensitive part of the code which should be treated with extra caution, which allows for a semantically richer template

I could go on, but you see where I'm coming from.

Thoughts?

### Proposed solution

Make it optional, or perhaps if a loop takes longer than x time to run per item, suggest to use track in a warning (which can be disabled if the developer desires... I don't know)

### Alternatives considered

n/a

**Comment by crisbeto** [comment] 2023-10-23 05:40
Duplicate of https://github.com/angular/angular/issues/52050.

**Closed by crisbeto** 2023-10-23 05:40 UTC
