### ISSUE TITLE
Allow programmatic setting of an elements pseudo css-class, like :before

### ISSUE THREAD

**Issue by imnickvaughn** [angular/angular#35863] opened 2020-03-04 22:42 UTC
# 🚀 feature request

### Relevant Package
angular/common
[NgStyle](https://angular.io/api/common/NgStyle)

### Description.
The feature would allow programmatic SETting of an elements pseudo-css-class, like :before.

component:
```@Input fontSize = 20px ```

template:
```<div  [ngStyle:before]="['font-size.px': fontSize}]">```

### Alternatives
I've considered data attributes but they arent allowed in Angular...

Component:
```  dataMagIconSize = "100px;"```

Template:
```<i class="dx-icon-search" data-mag-icon-size="{{dataMagIcon}}"></i>```

Css
```i[data-mag-icon-size] {
    font-size: attr(data-tool-tip);
}
.dx-icon-search:before {
    opacity: .5;
    font-size: 20px;
}```

**Comment by pkozlowski-opensource** [comment] 2020-03-05 15:41
This is a duplicate of the existing feature request #19234

**Comment by pkozlowski-opensource** [comment] 2020-03-05 15:42
Duplicate of  #19234

**Closed by pkozlowski-opensource** 2020-03-05 15:41 UTC
Labels: comp: common, type: feature
