### ISSUE TITLE
ngc includes commented-out imports

### ISSUE THREAD

**Issue by 18steps** [angular/angular#17061] opened 2017-05-26 23:50 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
With either line comments or block comments, `ngc` includes `@imports` that are commented out in `.scss` files

**Expected behavior**
Don't do imports if they are commented out

**Minimal reproduction of the problem with instructions**
1. Write a commented-out `@import` in e.g. an ng-cli-created `/src/styles.scss`, pointing to something that does not exist.
2. Run something like `ng build --prod && ngc && webpack`

`ng build --prod` and `webpack` will ignore the commented-out lines, but `ngc` will follow the imports and err.

**What is the motivation / use case for changing the behavior?**
Behave like the other sass build tools which ignore commented-out lines.

**Please tell us about your environment:**
> @angular/cli: 1.1.0-beta.0
node: 7.10.0
os: win32 x64
@angular/animations: 4.1.3
@angular/common: 4.1.3
@angular/compiler: 4.1.3
@angular/core: 4.1.3
@angular/forms: 4.1.3
@angular/http: 4.1.3
@angular/platform-browser: 4.1.3
@angular/platform-browser-dynamic: 4.1.3
@angular/platform-server: 4.1.3
@angular/router: 4.1.3
@angular/cli: 1.1.0-beta.0
@angular/compiler-cli: 4.1.3

**Comment by pkozlowski-opensource** [comment] 2020-03-18 09:19
Duplicate of #15255

**Closed by pkozlowski-opensource** 2020-03-18 09:19 UTC
Labels: comp: core, core: stylesheets, freq1: low, severity3: broken, type: bug/fix
