### ISSUE TITLE
@angular/pwa navigationUrls for simulated offline fetch request from Chrome not working

### ISSUE THREAD

**Issue by leonelvsc** [angular/angular#41365] opened 2021-03-29 17:37 UTC
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/pwa

### Is this a regression?
No

### Description
Starting in Chrome 89 if you don't return a successful response in simulated offline mode you won't be allowed to install the app from the manifest

## 🔬 Minimal Reproduction

Adding `/` to `navigationUrls` in the `ngsw-config.json` should return the index.html page but it fails detecting the simulated offline request as the request doesn't have the `Accept: text/html `header

## 🔥 Exception or Error
Site cannot be installed: Page does not work offline. Starting in Chrome 93, the installability criteria is changing, and this site will not be installable. See https://goo.gle/improved-pwa-offline-detection for more information.

Maybe we could use the `request.referrerPolicy` property checking for a value of `unsafe-url`

## 🌍  Your Environment

**Angular Version:**
<pre><code>
11.2.7
</code></pre>

**Comment by gkalpak** [comment] 2021-03-29 17:51
Thx for reporting this, @leonelvsc. This is being tracked in #41085. (We are looking into it and will provide a fix soon.)
Closing this as a duplicate of #41085.

**Closed by gkalpak** 2021-03-29 17:51 UTC
