### ISSUE TITLE
Select with [multipe],formControl fail set value.

### ISSUE THREAD

**Issue by maranqz** [angular/angular#14141] opened 2017-01-27 15:01 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```
[Link with bug](http://plnkr.co/edit/X6IBwTyZKY8UItr5iXpw?p=preview)

**Current behavior**
Set last value of list values.

**Expected behavior**
Set all values of list value.

**Minimal reproduction of the problem with instructions**
If i use multiple with [] then I have this bug. Without [], all okey.

**Comment by DzmitryShylovich** [comment] 2017-01-27 15:06
It works as intended.
`<select [multiple]="true"` is not supported.

**Comment by maranqz** [comment] 2017-01-27 15:18
Strangely, [multiple]="false" views as a single select.

**Comment by DzmitryShylovich** [comment] 2017-01-27 15:21
because `[multiple]="true"` is completely ignored when used with []. in this case i will always be as a single select.

**Comment by DzmitryShylovich** [comment] 2017-02-01 07:58
@pkozlowski-opensource it's duplicate of https://github.com/angular/angular/issues/12585

**Closed** 2017-02-01 08:38 UTC
