### ISSUE TITLE
Can't include static json content as part of template html

### ISSUE THREAD

**Issue by mlakmal** [angular/angular#10886] opened 2016-08-17 15:02 UTC
When we include json content as part of template html, we are getting template parsing errors like below. we use json content heavily in our current Angular v1 application to inject locale content to be used in directive html text labels.

_Template parse errors:
Unexpected character "EOF" (Do you have an unescaped "{" in your template? Use "{{ '{' }}") to escape it.) ("
       }_

Ex: page template html (use custom directive transcluded with json content)
`<div custom-directive>
{ "lblFName": "xyz" }
</div>`

custom directive template html (we internally get the transcluded json content to vm.content variable and use it in the directive template)
`<span>{{::vm.content.lblFName}}</span>`

we are trying to research on upgrading our application to Angular2 with RC5 version but getting template parsing errors when trying to include json content like above. Do we have any other options to support this feature in Angular2 or allow us to override or add support to Angular2 template parser to ignore json content like above ...
 
Error message specifies, that we need to escape { char with '{', having to escape complex json content structure would be time consuming and we are looking for any other options are available in Angular2 for this...

**Comment by ericmartinezr** [comment] 2016-08-17 15:10
Your besr option is to use ngNonBindablr ( https://github.com/angular/angular/blob/231ed695075b494d892c16e8c98765955b9d8868/modules/%40angular/common/test/directives/non_bindable_spec.ts ), although it sounds like a pita if you have to put that everywhere.

**Comment by mlakmal** [comment] 2016-08-17 15:23
@ericmartinezr i already tried ngNonBindable, it doesn't ignore template parsing still throws same error.

**Comment by lukiffer** [comment] 2016-08-17 19:02
+1, ran into the same issue where we're providing code examples. ngNonBindable was what we were using before, but it no longer works with >=RC5. Ended up just escaping as described, but it would be nice to have a simpler solution.

**Comment by zoechi** [comment] 2016-08-18 08:34
Plunker to reproduce?

**Comment by mlakmal** [comment] 2016-08-18 14:21
@zoechi plunker url below

[https://embed.plnkr.co/48KhM48Ru7lyxxob7LUw/](url)

**Comment by pkozlowski-opensource** [comment] 2016-10-12 13:25
Duplicate of #11859. With #12178 you will be able to use `ngNonBindable`. There is more discussion on making it easier on people in #11859

**Closed by pkozlowski-opensource** 2016-10-12 13:25 UTC
Labels: comp: core & compiler
