### ISSUE TITLE
Directive mixins do not inherit `@Input`/`@Output` metadata properly.

### ISSUE THREAD

**Issue by mmuscat** [angular/angular#42594] opened 2021-06-17 13:56 UTC
# Bug Report

### Affected Package

@angular/core
@angular/compiler

### Is this a regression?

Don't know. Asking for clarification if this behavior is intended or not.

### Description

If a component or directive extends a mixin class, the `@Input()` and `@Output()` directive metadata are not properly inherited
which causes a compiler error during template type check.

## Minimal Reproduction

https://stackblitz.com/edit/angular-12-mixin-inputs-bug?file=src%2Fapp%2Fhello.component.ts

## Exception or Error
<pre><code>Error in src/app/app.component.html (1:8)
Can't bind to 'name' since it isn't a known property of 'hello'.
</code></pre>

## Your Environment

**Angular Version:**
<pre><code>
@angular/core: 12.0.5
@angular/compiler: 12.0.5
</code></pre>

**Anything else relevant?**

Reproduction includes a mixin "workaround", so it seems like this should be possible, but this workaround breaks when exported from a library. Another workaround is to include "inputs" and "outputs" in the component/directive metadata arrays, but then you lose type information in templates. Other decorators such as host binding, host listener and queries work normally.

**Comment by alxhub** [comment] 2021-06-25 00:21
Hello @mmuscat,

This is unfortunately indeed the intended behavior. Template type-checking works through static analysis of components and templates. If Angular is able to resolve the base class of a directive or component statically, it's able to understand the full set of inputs and outputs available, and type-check them accordingly.

The point of a mixin, however, is to generate a base class _dynamically_ - almost by definition, the base class is not able to be known statically. As a result, Angular isn't able to determine the full set of inputs and outputs available. Arguably we should throw an error in this case, but for compatibility reasons we currently assume that the base class isn't a component or directive and doesn't affect template type-checking. When this assumption is false, it can result in binding errors, like the ones you observe.

Your `HackyWorkaround` does work around the problem locally, because Angular _can_ in fact statically understand simple functions that only consist of a single `return` statement. In this case, Angular is able to determine that `HackyWorkaround(Props)` really just refers to the `Props` class itself, so it statically understands the inheritance of `HelloComponent`. Actually, Angular gets this wrong, because `HackyWorkaround` is abusing a default property initializer to hide a side effect from Angular's static analysis. This is arguably a bug in the Angular compiler, since we _should_ recognize that this function isn't statically understandable due to the side effectful property initializer. Clearly we weren't expecting someone to depend on this 😉. If you're curious, this only works locally and not when shipped as part of a library since the Angular compiler can only statically understand this function if it can see the function body. Once this function is compiled to a `.d.ts` file, it no longer has a function body to analyze.

My advice would be to look at how `@angular/material` uses mixins, and follow that pattern - I believe they define constants for`inputs` and `outputs` and repeat them in the final components. It's a bit awkward and repetitive, but it definitely solves this problem.

I'm going to close this issue as our compiler is working as intended here, and so unfortunately there's nothing actionable for us. I'm happy to continue discussing this though!

**Closed by alxhub** 2021-06-25 00:21 UTC
Labels: comp: compiler, comp: core

**Comment by mmuscat** [comment] 2021-06-25 10:41
Thanks @alxhub for the great explanation. For further context I'll [link the project](https://github.com/mmuscat/angular-composition-api) this issue is blocking. The workaround you mentioned does fix the issue, with the side effects you mentioned.

The mixin approach is just a hack to get the behavior I want from the compiler. What I really want is a more dynamic way of declaring components, with a factory instead of a class, so I guess I'll open a feature request if there isn't one already 🤷
