### ISSUE TITLE
Runtime error during after AoT build: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by yfain** [angular/angular#12287] opened 2016-10-13 23:42 UTC
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
The app works fine if built with ng build --prod.
The build with ng build --prod --aot completes successfully, but the app won't start with the following exception:

main.7c16020….bundle.js:694 EXCEPTION: Cannot read property 'replace' of undefinedt.handleError @ main.7c16020….bundle.js:694(anonymous function) @ main.7c16020….bundle.js:428t.invoke @ main.7c16020….bundle.js:1486onInvoke @ main.7c16020….bundle.js:512t.invoke @ main.7c16020….bundle.js:1486n.run @ main.7c16020….bundle.js:1486(anonymous function) @ main.7c16020….bundle.js:1486t.invokeTask @ main.7c16020….bundle.js:1486onInvokeTask @ main.7c16020….bundle.js:512t.invokeTask @ main.7c16020….bundle.js:1486n.runTask @ main.7c16020….bundle.js:1486o @ main.7c16020….bundle.js:1486
main.7c16020….bundle.js:694 ORIGINAL STACKTRACE:t.handleError @ main.7c16020….bundle.js:694(anonymous function) @ main.7c16020….bundle.js:428t.invoke @ main.7c16020….bundle.js:1486onInvoke @ main.7c16020….bundle.js:512t.invoke @ main.7c16020….bundle.js:1486n.run @ main.7c16020….bundle.js:1486(anonymous function) @ main.7c16020….bundle.js:1486t.invokeTask @ main.7c16020….bundle.js:1486onInvokeTask @ main.7c16020….bundle.js:512t.invokeTask @ main.7c16020….bundle.js:1486n.runTask @ main.7c16020….bundle.js:1486o @ main.7c16020….bundle.js:1486
main.7c16020….bundle.js:694 TypeError: Cannot read property 'replace' of undefined
    at a (main.7c16020….bundle.js:610)
    at new t (main.7c16020….bundle.js:617)
    at e.t.renderComponent (main.7c16020….bundle.js:617)
    at t.renderComponent (main.7c16020….bundle.js:71)
    at e.t (main.7c16020….bundle.js:120)
    at new e (main.7c16020….bundle.js:1472)
    at i (main.7c16020….bundle.js:1472)
    at e.createInternal (main.7c16020….bundle.js:1472)
    at e.t.create (main.7c16020….bundle.js:120)
    at t.create (main.7c16020….bundle.js:92)

**Expected behavior**
The app should start  

**Minimal reproduction of the problem with instructions**

Get the code (2 projects) at https://github.com/Farata/angular2typescript/tree/master/chapter10/extras

1. Start the standalone node server, 
2. In the auction_cli npm run build
3. Open the browser at localhost:8000. The app works
4. Add --aot to the build script
5.  In the auction_cli npm run build
6. Open the browser at localhost:8000. The app gives the above exception

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
 OS X, NodeJS server 

* **Angular version:** 2.1.0

* **Browser:** [all ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =   6.7

**Comment by brandonroberts** [comment] 2016-10-14 00:09
See https://github.com/angular/angular/issues/11408. There is a bug with AoT and `ViewEncapsulation.None`

**Comment by yfain** [comment] 2016-10-14 09:15
@brandonroberts Thank you, Brandon. After commenting out ViewEncasulation.None the app built with --aot works, but the styles are screwed up :(

**Comment by pkozlowski-opensource** [comment] 2016-10-14 14:10
Closing as a duplicate of  #11408, thnx @brandonroberts !

**Closed by pkozlowski-opensource** 2016-10-14 14:10 UTC
