### ISSUE TITLE
change detection wrong order on child components

### ISSUE THREAD

**Issue by e-davidson** [angular/angular#32180] opened 2019-08-18 18:30 UTC
# 🐞 bug report

### Affected Package

Life cycle and Change detection not running in the correct order for 2 sibling components.

### Is this a regression?

 Not that I'm aware of.

### Description

I have 2 sibling components.
The first hosts a template via ngTemplateOutlet
The 2nd has the template as part of its view to be used by its sibling.
The parent gets the template from the 2nd child and passes it to the first child.

It works fine if the template that we're getting from the 2nd child gets passed to the 1st child in the first cycle.

However, if we need a 2nd cycle to get the template like the following code it doesn't work.
<pre><code>
  ngAfterViewInit() {
    setTimeout(() => {
      this.templates = this.templateQuery.map( c => c.template );
      this.cdr.markForCheck();
    }, 0);
  }
</code></pre>

Doing it in the set timeout is necessary otherwise you may get a ExpressionChangedAfterItHasBeenCheckedError.

The input bindings on the inner template are always one cycle behind the parent component.

The issue appears to be that the order that angular runs the life cycle hooks is not the same in the 1st case as in the 2nd.

In the first case.
The content is checked on the template component before the host component.
So the change is detected and passed through to the host component.

However in the 2nd case
Change detection first runs on the host component and nothing changed yet so the view doesn't update. Then it's run on the template component, but it's already too late for the host component. So it's not picked up till the next cycle.

## 🔬 Minimal Reproduction

click the button and notice the inner template in the broken section is one step behind.

https://stackblitz.com/edit/angular-djxc1a

## 🔥 Exception or Error

The view isn't updated correctly.
The child is one cycle behind the parent.

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 8.2.2
Node: 12.6.0
OS: win32 x64
Angular: 8.2.2
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.802.2
@angular-devkit/build-angular     0.802.2
@angular-devkit/build-optimizer   0.802.2
@angular-devkit/build-webpack     0.802.2
@angular-devkit/core              8.2.2
@angular-devkit/schematics        8.2.2
@angular/cdk                      8.1.3
@angular/material                 8.1.3
@ngtools/webpack                  8.2.2
@schematics/angular               8.2.2
@schematics/update                0.802.2
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.38.0
</code></pre>

**Anything else relevant?**

It's possible this is by design.
If that's the case it should be documented how the life cycle behaves for these edge cases.

**Comment by mhevery** [comment] 2019-08-22 22:36
the order of change detection is the order of declaration, and so when you got templates it may get confusing. I think this works as intended, an so we are unlikely to change this.  Sorry closing as we will not work on this.

**Comment by e-davidson** [comment] 2019-08-23 00:12
@mhevery  Agreed that would be the intended behavior, but it looks like that's not always the case.
I was able to produce a case where the order of the change detection lifecycle isn't the order of declaration.
The order only seems to matter in the latter broken case.
I revised the stackblitz to show both orders of declaration.

https://stackblitz.com/edit/angular-djxc1a?file=src%2Fapp%2Fparent.ts

Also, the documentation isn't clear about the intended order of running the lifecycle hooks for children and templates that are passed to other components.

**Comment by e-davidson** [comment] 2019-08-23 02:18
After reviewing once again in depth I'm getting a better understanding of the issue.

The change detection is in fact running in the correct order. The issue appears to be that the entire lifecycle of the host completes before the sibling template begins.  This causes weird and unexpected behavior, as shown in my example above.

The expected order is:

child 1 on changes
child 2 on changes
child 1 content checked
child 2 content checked
child 1 view checked
child 2 view checked

And that's in fact what's happening in the first 2 examples in the stack blitz.

But in the last 2 examples the order is: 

child 1 changes
child 1 content checked
child 1 view checked
child 2 changes
child 2 content checked
child 2 view checked

I added logging to the console so you can see what's happening.

https://stackblitz.com/edit/angular-djxc1a

The difference in the 2 examples is due to the fact that while the children appear in the parent template they are really grandchildren, and not siblings of each other.
 
It would be helpful to have official documentation and guidance from the Angular team on how this works, to help avoid confusion in the future.

**Comment by pkozlowski-opensource** [comment] 2019-08-23 03:39
@e-davidson agree that it probably requires more docs / mental model explanations. I will re-open it as a doc issue and assign to myself to dig into it. Don't expect it to be top priority, though.

**Comment by kapunahelewong** [comment] 2020-05-27 19:39
Status: Docs team can help when @pkozlowski-opensource is ready.

**Comment by atscott** [comment] 2021-05-25 17:09
duplicate of #33731

**Closed by atscott** 2021-05-25 17:09 UTC
Labels: P4, comp: core, comp: docs, core: change detection, freq1: low, state: confirmed, state: needs eng input, triage #1, type: bug/fix
