### ISSUE TITLE
Reactive forms: add validators to the existing ones without overwriting all

### ISSUE THREAD

**Issue by pierfreeman** [angular/angular#20728] opened 2017-12-01 11:07 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

Currently, it's possible to set a validator dynamically using setValidators. But this method overwrites all the previous validators that have been set on the FormControl. It would be nice having a method for adding/removing validators to the existing ones.

A possible workaround would be to set a validator array with the new one (e.g. using the spread operator), but I can't get the existing validator array (using FormControl.validator doesn't seem to help)

**Comment by Toxicable** [comment] 2017-12-01 19:18
duplicate of https://github.com/angular/angular/issues/10567

**Comment by pkozlowski-opensource** [comment] 2017-12-02 09:12
It is a duplicate of #10567 indeed, thnx @Toxicable

**Closed by pkozlowski-opensource** 2017-12-02 09:12 UTC
Labels: comp: forms
