### ISSUE TITLE
angular route with fragment does not scroll element into view

### ISSUE THREAD

**Issue by rekna1** [angular/angular#22778] opened 2018-03-14 21:36 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

routerLink or router.navigate with fragment does not scroll anchor into view

## Expected behavior
page should scroll element defined by fragment into view

## Minimal reproduction of the problem with instructions
https://angular-uiur64.stackblitz.io/#/list
(make sure browser window height small enough so page scrollbar is shown)
* click on any element in the list (element text navigates in code, link navigates with routerLink)
* navigates to detail component with fragment 'bottom' in url
* both routerLink and router.navigate show same problem
* shows detail component but should scroll to bottom to text 'this it the bottom'
## What is the motivation / use case for changing the behavior?
ability to jumping to part of page is required behaviour for an HTML5 web app

## Environment

<pre><code>
Angular version: 5.2.8

Browser:
- [x ] Chrome (desktop) version 
but probably in all browsers
 
For Tooling issues:
- stackblitz 
- Platform:  any

**Comment by trotyl** [comment] 2018-03-15 02:11
Duplicate of #6595, #13636

**Comment by rekna1** [comment] 2018-03-15 08:43
Since these are issues from 2016, will it be fixed any time soon ? 
If not , maybe it would be better to mention in docs that fragments are not yet available in 5.2.8 ?

**Comment by jasonaden** [comment] 2018-03-16 21:09
Closing as a duplicate, plus there's an existing PR for this behavior. While there have been delays on landing the PR, it should be available soon:

https://github.com/angular/angular/pull/20030

**Closed by jasonaden** 2018-03-16 21:09 UTC
Labels: comp: router
