### ISSUE TITLE
Navigation ID 2 is not equal to the current navigation id 3

### ISSUE THREAD

**Issue by indraraj26** [angular/angular#34051] opened 2019-11-26 10:43 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/router

### Is this a regression?

I never had this problem in previous version of angular.

### Description
After auth login i have one button which will redirect me to dashboard but i am getting navigation is not matched.
On component i have only one time router.navigate(['/dashboard']);
With **routerlink** it is working  routerLink="/dashboard"

## 🔬 Minimal Reproduction
Click on image to see properly.
Log:
![image](https://user-images.githubusercontent.com/23274631/69622712-835ff000-1067-11ea-94b4-88973e026635.png)

![image](https://user-images.githubusercontent.com/23274631/69622665-6fb48980-1067-11ea-81b6-777e2ca3d8db.png)

```

```

 https://stackblitz.com/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

ng --version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 8.3.0
Node: 10.16.0
OS: win32 x64
Angular: 8.2.3
... common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.801.3
@angular-devkit/build-angular     0.801.3
@angular-devkit/build-optimizer   0.801.3
@angular-devkit/build-webpack     0.801.3
@angular-devkit/core              8.1.3
@angular-devkit/schematics        8.3.0
@angular/animations               8.2.5
@angular/cdk                      8.1.4
@angular/cli                      8.3.0
@angular/material                 8.1.4
@ngtools/webpack                  8.1.3
@schematics/angular               8.3.0
@schematics/update                0.803.0
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.35.2

</code></pre>

**Anything else relevant?**

**Comment by santoshyadav198613** [comment] 2019-11-26 10:57
Can you please provide an reproduction, also I have seen similar question on stackoverflow you can check that as well.

**Comment by indraraj26** [comment] 2019-11-26 11:02
Hi, 
I have already checked that no idea why it is causing, I can navigate with routerLink but not with router.navigate or router.navigateByUrl.

It is not possible for me to provide original source code but i may try to replicate same routing in new project please wait...

**Comment by indraraj26** [comment] 2019-11-26 12:38
Hi, 

Repo:  https://github.com/indraraj26/navigation-bug

Step to reproduce:

Step 1: ng serve -o
Step 2: put email and password anything hit login btn
step 3: click on dashboard btn
step 4: check console you will get this error
```
NavigationCancel {id: 3, url: "/dashboard", reason: "Navigation ID 3 is not equal to the current navigation id 4"}
id: 3
reason: "Navigation ID 3 is not equal to the current navigation id 4"
url: "/dashboard"
```
the code which is responsible for redirect
login.component.ts
```
 takeToDestination(destination: string) {
    console.log(destination, this.obj);
    if (destination === "party") {
      window.open(this.obj.url, "_blank");
      /*  setTimeout(() => {
        this._router.navigateByUrl("/auth/login");
      }, 100); */
    } else {
      console.log("redirect to dashboard");
      this._userData.setUserData = this.obj.data;
      this._router.navigate(["/dashboard"]);
    }
  }
```

**Comment by LanderBeeuwsaert** [comment] 2019-12-01 16:37
I have the same issue (ng8.2.13) and can shed more light on the reason why:
The reason is the same as described here:
https://stackoverflow.com/questions/41937115/angular-2-navigationcancel-navigation-id-2-is-not-equal-to-the-current-naviga/42802182#42802182

I do the following:
this.router.navigate(['/introduction/generating_starting_orders/top']);

but when this code is triggered, it calls 2 different ngOnDestroy functions that have the following code:

  ngOnDestroy() {
    this.router.navigate(['.'], {
      relativeTo: this.activatedRoute,
      queryParams: {comptab: null},
      queryParamsHandling: 'merge'
    });
  }

  ngOnDestroy() {
    this.router.navigate(['.'], {
      relativeTo: this.activatedRoute,
      queryParams: {comp: null},
      queryParamsHandling: 'merge'
    });
  }

this to clean up the queryparams so they are not in the URL anymore when leaving these components.
Seems the router doesn't like this and it cancels the route change:
![image](https://user-images.githubusercontent.com/1098243/69916925-31510d00-1461-11ea-83bb-eaf0e1e73f50.png)

**Comment by UmutAkkaya** [comment] 2020-02-21 20:17
I have the same issue :( any update on this?

**Comment by LanderBeeuwsaert** [comment] 2020-02-21 20:30
my workaround: do a setTimeout to not trigger 2 times at the same time

**Comment by ghernandezr** [comment] 2020-03-21 04:46
> my workaround: do a setTimeout to not trigger 2 times at the same time
Thanks!  @LanderBeeuwsaert 
I solve with this:

 setTimeout(() => {
       this.router.navigate(['/my/route']);
}, 0);

**Comment by Wilt** [comment] 2020-03-22 17:23
As I understood most of the cases related to this is issue are caused [by navigation being called twice in quick succession](https://stackoverflow.com/a/42802182/1697459). Most cases I have seen is because of calling `navigateTo` for redirecting from a `RouteGuard` (instead of returnin a `UrlTree` with the desired redirection), `routeParams` being set during navigation, or simply navigating twice. 

I am not sure, but I guess navigating twice is not correctly handled, because your not supposed to do that in Angular, hence the erroneous behavior of the Application. People waste a lot of time debugging these issues and finally end up in this "reason" of the `NavigationCancel` event to realize that they did something wrong.

Would it be possible to introduce a more descriptive `Error` message during development (in development environment)? Something similar like the `ExpressionChangedAfterItHasBeenCheckedError` for development issues with change detection.

I could imagine a `RouteChangedAfterRouterStartedNavigatingError`. It would be very useful in my opinion and it will help many people considering the amount of posts on this topic.

**Comment by LanderBeeuwsaert** [comment] 2020-03-22 17:27
"because your not supposed to do that in Angular" => I think I have a legitimate use-case for wanting to navigate twice in the same "frame/tick". Possibly there are other solutions for solving what I want to do, if so, I have not found them.

**Comment by Wilt** [comment] 2020-03-22 17:53
If you are supposed to, then something is broken because `NavigationEnd` is not even fired when making the mistake of navigating twice in rapid succession.
From a `RouteGuard` you can redirect, but then the correct thing to do is return a `UrlTree` as far as I understood. 

But to be honest I would not mind hearing that it is legitimate and that it will work correctly, the problem seems to be that it doesn't,

**Comment by LanderBeeuwsaert** [comment] 2020-03-22 18:03
See above: we use the URL to pass parameters to be able to deep link.
So each time you change to another component the URL parameters get updated.
If you have 3 nested components, it means you have 3 URL parameters.

If you then go to another component, where the 3 nested components are destroyed, it should clean up the URL parameters in the ngOnDestroy of the components.

You could of course start to get fancy and create a specific service to do this, and let that service do the clean sequentually with setTimeouts, but that is complicating things unneccesarily and should not be necessary in my opinion.

**Comment by Rennanxp2** [comment] 2020-04-01 21:10
i had the same problem, and i got stuck for a week, till i just clean my browsing data, and everything works just fine.

**Comment by atscott** [comment] 2020-05-28 17:15
Duplicate of #34795 (the guard triggered a new navigation, which caused the NavigationCancel of the original and the new navigation goes to /auth/login, the URL of the start of the navigation)

**Closed by atscott** 2020-05-28 17:15 UTC
Labels: comp: router, freq1: low, severity1: confusing, triage #1, type: bug/fix
