### ISSUE TITLE
loadChildren in Angular 14 causes Maximum call stack size exceeded error

### ISSUE THREAD

**Issue by shadow1349** [angular/angular#46346] opened 2022-06-12 15:57 UTC
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

No

### Description

I had created a brand new repo with Angular 14. I installed angular material using `ng add`. I created a module with routing as well as a component. When I tried to use loadChildren to lazy-load the route I got a maximum call stack size exceeded error.

I tried using `component: MyComponent` in place of loadChildren and that worked, but I'd really like to be able to lazy load modules. I tried removing the RoutingModule created by angular and putting `RouterModule.forRoot(routes)` inside the module itself, which whittled the error down to the main.ts which I never touched. 

### Please provide a link to a minimal reproduction of the bug

https://github.com/shadow1349/Angular-14-Demo/tree/master

### Please provide the exception or error you saw

```true
./src/main.ts - Error: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
Error: Maximum call stack size exceeded
    at /Users/sam/Documents/Code/Articles/angular14-demo/node_modules/@ngtools/webpack/src/ivy/loader.js:81:18
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 14.0.1
Node: 16.15.0
Package Manager: npm 8.5.5 
OS: darwin arm64

Angular: 
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1400.1 (cli-only)
@angular-devkit/core         14.0.1 (cli-only)
@angular-devkit/schematics   14.0.1 (cli-only)
@schematics/angular          14.0.1 (cli-only)
```

**Comment by crisbeto** [comment] 2022-06-12 20:19
It looks like the `FormsModule` is importing itself which is probably what's triggering the infinite loop. See: https://github.com/shadow1349/Angular-14-Demo/blob/master/src/app/forms/forms.module.ts#L17

**Comment by JoostK** [comment] 2022-06-13 06:31
Good spot @crisbeto :-) That makes this a duplicate of #14649.

**Closed by JoostK** 2022-06-13 06:31 UTC

**Comment by shadow1349** [comment] 2022-06-13 20:14
omg I can't believe I missed that 🤦 . Thanks @crisbeto
