### ISSUE TITLE
dynamic component with compiler, ng build --prod giving error

### ISSUE THREAD

**Issue by gns088** [angular/angular#23119] opened 2018-04-02 06:27 UTC
### Issue
we want to develop application in which the requirement need to create component dynamically.
so we used ComponentFactoryResolver, Compiler, NgModuleFactoryLoader, compiler's method "compileModuleAndAllComponentsAsync" for creating dynamic component.

### followed instruction from this article :
https://blog.angularindepth.com/here-is-what-you-need-to-know-about-dynamic-components-in-angular-ac1e96167f9e

- ng build have no issue while building application
- ng build --prod is giving error. first it was giving error like run time compiler not found. then we searched about this is found solution like provide compiler in app module's provider. so we did that. now it is giving another error which is not resolving.
-  syntax we have used to provide compiler is like below.
```
import {Compiler, CompilerFactory, NgModule} from '@angular/core';

export function createCompiler(compilerFactory: CompilerFactory) {
  return compilerFactory.createCompiler();
}
 providers:[{provide: Compiler, useFactory: createCompiler, deps: [CompilerFactory]}]
```

### Versions
```
Angular CLI: 1.6.5
Node: 9.3.0
OS: linux x64
Angular: 5.0.4
... common, compiler, compiler-cli, core, forms, http
... platform-browser, platform-browser-dynamic, router

@angular/animations: 5.2.1
@angular/cdk: 5.0.2
@angular/cli: 1.6.5
@angular/flex-layout: 2.0.0-beta.10-4905443
@angular/material: 5.0.2
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.29
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.5
@schematics/angular: 0.1.17
typescript: 2.7.2
webpack: 3.10.0

```

### Repro steps
##function that we written for creating component dynamically is like below,
```
constructor(private resolver: ComponentFactoryResolver,
              private compiler: Compiler, private loader: NgModuleFactoryLoader) {
  }
loadComponentWithLazyLoading(modulePath, componentName, viewRef) {
    this.loader.load(modulePath).then((module) => {
      this.compiler.compileModuleAndAllComponentsAsync<any>(module.moduleType)
        .then((factory: ModuleWithComponentFactories<any>) => {
          return factory.componentFactories.find((component) => component.componentType.name === componentName);
        }).then((factory) => {
        const modRef = module.create(viewRef.parentInjector);
        const componentRef = viewRef.createComponent(factory, 0, modRef.injector);
      });
    });
  }
```
## to use this function 
```
@ViewChild('DynamicComponentContainer', {read: ViewContainerRef}) container;


this.service.loadComponentWithLazyLoading(this.moduleData.modulePath, this.moduleData.componentName, this.container)
```
### Observed behavior
now, while doing ng build only component creating dynamically and running with not issue. but when we do ng build --prod the issue is like below:
```
Uncaught Error: StaticInjectorError[pe]: 
  StaticInjectorError[pe]: 
    NullInjectorError: No provider for pe!
    at t.get (main.20c6d2cd5cc49589b6f1.bundle.js:1)
    at main.20c6d2cd5cc49589b6f1.bundle.js:1
    at t (main.20c6d2cd5cc49589b6f1.bundle.js:1)
    at t.get (main.20c6d2cd5cc49589b6f1.bundle.js:1)
    at main.20c6d2cd5cc49589b6f1.bundle.js:1
    at t (main.20c6d2cd5cc49589b6f1.bundle.js:1)
    at t.get (main.20c6d2cd5cc49589b6f1.bundle.js:1)
    at kr (main.20c6d2cd5cc49589b6f1.bundle.js:1)
    at main.20c6d2cd5cc49589b6f1.bundle.js:1
    at Sr (main.20c6d2cd5cc49589b6f1.bundle.js:1)
```
### Desired behavior
when we create build for production application should run same as ng build.

**Comment by mlc-mlapis** [comment] 2018-04-02 07:51
gns088 ... https://github.com/angular/angular-cli/issues/9306#issuecomment-375717585

**Comment by alexeagle** [comment] 2018-04-03 21:17
Sorry, can't tell if there is actually a bug in Angular here. Looks like just a support request. If there's actually a bug, please give repro.
Looks like a dupe of the issue @mlc-mlapis pointed to.

**Closed by alexeagle** 2018-04-03 21:17 UTC
