### ISSUE TITLE
ngOnchange not get triggerd when passing input dynamically in angular 9 with IVY?

### ISSUE THREAD

**Issue by kumaresan-subramani** [angular/angular#35570] opened 2020-02-20 04:08 UTC
# 🐞 bug report

ngOnchange hook for for complex directive not get triggered while i pass inputs dynamically,

### Affected Package
no ides

### Is this a regression?

yes, in angular 8 it is working fine

### Description

i have directive for my component and i initialize inputs for my directive as below but ngonchange hook not get triggeres in angular 9 IVY

### component structure

```
 * <my-tab>
 *  <my-tabitems>
 *   <my-tabitem [header]='Header 1' [content]='Content 1'></e-tabitem>
 *   <my-tabitem [header]='Header 2' [content]='Content 2'></e-tabitem>
 *  <my-tabitems> 
 * </my-tab>
```

### item-directive.ts
```

let input: string[] = ['content', 'cssClass', 'disabled', 'header', 'headerTemplate', 'visible'];
let outputs: string[] = [];

/**
 * TabItem complex Directive
 * @private
 */

@Directive({
    selector: 'e-tabitems>e-tabitem',
    inputs: input,
    outputs: outputs,    
    queries: {

    }
})
export class TabItemDirective extends ComplexBase<TabItemDirective> {

    public cssClass: any;
    public disabled: any;
    public header: any;
    public visible: any;

    @ContentChild('content')
    @Template()
    public content: any;
    @ContentChild('headerText')
    @Template()
    public header_text: any;

    @ContentChild('headerTemplate')
    @Template()
    public headerTemplate: any;

    constructor(private viewContainerRef:ViewContainerRef) {
        super();
        setValue('currentInstance', this, this.viewContainerRef);
        this.registerEvents(outputs);
    }
}

/**
 * TabItem Array Directive
 * @private
 */
@Directive({
    selector: 'my-tab>e-tabitems',
    queries: {
        children: new ContentChildren(TabItemDirective)
    },
})
export class TabItemsDirective extends ArrayBase<TabItemsDirective> {
    constructor() {
        super('items');
    }
}
```

hooks for my complex and array directive has been exected in complexbase and arraybase class which i extended here

here i have set input properties in different way and i got some info from [here](https://www.bennadel.com/blog/3541-ngonchanges-life-cycle-hook-only-gets-invoked-if-calling-context-actually-provides-input-bindings-in-angular-7-1-1.htm)

But in this way of setting input properties working fine in angular 8 but not working in anglar 9

## 🔬 Minimal Reproduction

1. download below sample
[checkone.zip](https://github.com/angular/angular/files/4228726/checkone.zip)

2. give `npm i`
3. then `ng serve`

i have generated my coomponent package using ng-packagr which will get downloaded while giving `npm i`

## 🔥 Exception or Error
control not get rendered

## 🌍  Your Environment

**Angular Version:**
<pre><code>
"dependencies": {
    "@angular/animations": "~9.0.1",
    "@angular/common": "~9.0.1",
    "@angular/compiler": "~9.0.1",
    "@angular/core": "~9.0.1",
    "@angular/forms": "~9.0.1",
    "@angular/platform-browser": "~9.0.1",
    "@angular/platform-browser-dynamic": "~9.0.1",
    "@angular/router": "~9.0.1",
    "rxjs": "~6.5.4",
    "tslib": "^1.10.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.900.2",
    "@angular/cli": "~9.0.2",
    "@angular/compiler-cli": "~9.0.1",
    "@angular/language-service": "~9.0.1",
    "@types/node": "^12.11.1",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "^5.1.2",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.3.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~2.1.0",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.2",
    "protractor": "~5.4.3",
    "ts-node": "~8.3.0",
    "tslint": "~5.18.0",
    "typescript": "~3.7.5"
  }

</code></pre>

**Anything else relevant?**
nope

**Comment by kumaresan-subramani** [comment] 2020-02-20 04:14
HI,

I think below sample explains my issue, i found those while searching this issue

**Onchange not get triggered** - https://stackblitz.com/edit/angular-elements-test-input-bindings-decorator-ryatrx?file=app/test-input-bindings/test-input-bindings.component.ts

**Onchange get triggered** - 
https://stackblitz.com/edit/angular-elements-test-input-bindings-decorator-dhgmzf?file=index.html

**Comment by pkozlowski-opensource** [comment] 2020-02-20 20:36
@kumaresan-subramani I've tried to have a look at the reproduce scenario but it is not easy to navigate (at least for me). Could you please prepare a _minimal_, runnable (stackblitz / ng-run) example, without the use of 3rd party packages, to illustrate the problems.

Currently it is a lot going on and it is not clear where to look....

**Comment by pkozlowski-opensource** [comment] 2020-03-03 17:07
We haven't heard back and the only thing I can say based on the info we've got is this: currently setting inputs on instances of dynamically created components doesn't work in Angular as of today (ivy or not). Relevant issues / feature requests: #22567 and #25962.

Closing as a duplicate of the above issues.

**Comment by pkozlowski-opensource** [comment] 2020-03-03 17:08
Duplicate of #22567

**Closed by pkozlowski-opensource** 2020-03-03 17:07 UTC
Labels: comp: ivy, state: Needs repro

**Comment by kumaresan-subramani** [comment] 2020-03-03 17:19
@pkozlowski-opensource , But it works fine without IVY and ngOnchange get triggered properly . i am not able describe my issue more than this
