### ISSUE TITLE
FormControl does not reflect the new disabled value

### ISSUE THREAD

**Issue by dzonatan** [angular/angular#17806] opened 2017-06-28 11:21 UTC
## I'm submitting a ...
<pre><code>[X] Bug report</code></pre>

## Current behavior
When setting new `FormControl` instance to `[formControl]`/`formControlName` directive the **disabled** property/attribute of control DOM element **does not update** to the newest value.

## Expected behavior
When setting new `FormControl` instance to `[formControl]`/`formControlName` directive the **disabled** property/attribute of control DOM element **should reflect** the newest value.

## Minimal reproduction of the problem with instructions
http://plnkr.co/edit/g5yxZRs8PvJWPAIag7wj?p=preview

## Please tell us about your environment
<pre><code>Angular version: 4.2.4

Browser:
- [X] Chrome (desktop) version 58.0
</code></pre>

**Comment by alantreadway** [comment] 2018-08-16 15:51
Since this issue and PR don't seem to be going anywhere, here's a workaround that seems to be working for me which can be easily removed if/when an actual fix is released:
https://gist.github.com/alantreadway/773c4880585bc9eb27703b3073c7fcd2

Caveats (YMMV):
- Not sure if there is a race/conflict between the update of the `disabled` state on the host element, although all update sources should be setting identical values if they are based on `FormControl.disabled` anyway, even after the proper fix.
- Guessing this is sub-optimal in terms of change-detection due to the use of a method call on every change-detector pass.

**Comment by rzvjerkovic** [comment] 2019-07-23 12:49
Any updates? I just wasted a day trying to debug this.
I replaced `formControlName` with `[formControl]`, but I don't think that's the solution.

**Comment by chandrasagarjain** [comment] 2020-01-27 12:11
Is there any update on this bug?

**Comment by pavankjadda** [comment] 2020-03-11 16:40
I just wasted couple of hours on this, Any update?

**Comment by etay2000** [comment] 2020-04-25 12:41
Figured I'd add a comment here just to prevent the conversation from being ignored and then automatically locked as per usual. How is it possible to have 587 pending pull requests? Is Google unwilling to pay more employees to work on Angular? I realize it is open source, but seriously wtf?

**Comment by AndrewKushnir** [comment] 2020-11-17 21:09
Hi, it looks like this issue has the same root cause as #35309, so I'm closing this PR in favor of #35309. Thank you.

**Closed by AndrewKushnir** 2020-11-17 21:09 UTC
Labels: P3, comp: forms, freq2: medium, state: confirmed, triage #1, type: bug/fix
