### ISSUE TITLE
Set ViewEncapsulation per module

### ISSUE THREAD

**Issue by JPtenBerge** [angular/angular#18346] opened 2017-07-26 09:37 UTC
## I'm submitting a...
<pre><code>[x] Feature request</code></pre>

## Current behavior
Currently, we set the view encapsulation at the component level.

	@Component({
		selector: 'song-track',
		encapsulation: ViewEncapsulation.Native
	})

Meaning that if I want to use native Shadow DOM throughout my app, I have to add that bit of configuration to every single component.

## Expected behavior
It would be great if I could set it at the module level.

	@NgModule({
		imports: [...],
		declarations: [...],
		providers: [
			...
			{ provide: ViewEncapsulationMode, useValue: ViewEncapsulation.Native },
			...
		],
		bootstrap: [AppComponent]
	})
	export class AppModule { }

## What is the motivation / use case for changing the behavior?
Simply to make my life easier and make the framework a bit more friendly to use.

**Comment by trotyl** [comment] 2018-02-17 06:27
Duplicate of #13819

**Comment by JoostK** [comment] 2021-07-15 22:38
Heya, we're generally moving towards a model where components are more self-contained, so introducing NgModule configuration that influences how its declared components get compiled is not something we'd want to do. Please see https://github.com/angular/angular/issues/12251#issuecomment-872613835 for a more detailed answer.

**Closed by JoostK** 2021-07-15 22:38 UTC
Labels: comp: core, core: CSS encapsulation, core: NgModule, feature, insufficient votes, votes required
