### ISSUE TITLE
Define click property as @Output() emits two events: DOM/JS event and defined event

### ISSUE THREAD

**Issue by eldadcohen1** [angular/angular#14619] opened 2017-02-21 14:03 UTC
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request 

**Current behavior**

Define property named "click" as an @Output().
`@Output()
public click: EventEmitter<any> = new EventEmitter();

public foo(item){
   this.click.emit(item);
}`
use the component and bind the click property to handler
`<myComponent (click) = "myClickHandler($event)"/>`

When you debug all works fine.
When you work without debugging for some reason the  DOM/JS click event is emitting. 

**Expected behavior**

Override the DOM/JS click event and emit only the custom click. 

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/vaKukOWH55Q8RTB4nZQD 
The plunker doesnt run.

**What is the motivation / use case for changing the behavior?**

I want that the one that going to use my component will use it intuitively.  

* **Angular version:** 2.4.4

* **Browser:** Chrome 46
 
* **Language:** TypeScript

**Comment by DzmitryShylovich** [comment] 2017-02-21 14:15
Use [stopPropagation](https://developer.mozilla.org/en/docs/Web/API/Event/stopPropagation) on native click event.
Also see https://github.com/angular/angular.io/issues/3117

**Comment by ericmartinezr** [comment] 2017-02-21 14:23
dup of https://github.com/angular/angular/issues/4059

Don't use native event names as your custom event names ;)

**Comment by eldadcohen1** [comment] 2017-02-21 14:47
@DzmitryShylovich 
It doesn't work.
I want to override the native event name.

**Comment by pkozlowski-opensource** [comment] 2017-07-26 09:38
I agree with @ericmartinezr that this is a duplicate of #4059 so closing this one.

**Closed by pkozlowski-opensource** 2017-07-26 09:38 UTC
Labels: comp: core & compiler, freq1: low, severity3: broken, type: bug
