### ISSUE TITLE
Error: Module build failed: [object Object]

### ISSUE THREAD

**Issue by crutchcorn** [angular/angular#53678] opened 2023-12-21 17:48 UTC
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

When passing a number in a component:

```typescript
import "zone.js";
import { bootstrapApplication } from "@angular/platform-browser";

import { Component, Input } from "@angular/core";

@Component({
	selector: "display-size",
	standalone: true,
	template: `<p>Test</p>`,
})
class DisplaySizeComponent {
	@Input() bytes!: number;
}

@Component({
	selector: "app-root",
	standalone: true,
	imports: [DisplaySizeComponent],
	template: `
		<display-size [bytes]="123" />
	`,
})
export class AppComponent {}

bootstrapApplication(AppComponent);
```

It seems to throw an `[object Object]` error

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/github/crutchcorn/angular-object-object-bug?file=src%2Fmain.ts&template=node

### Please provide the exception or error you saw

```true
Build at: 2023-12-21T17:46:12.035Z - Hash: cc1a53dd72abbe97 - Time: 3228ms

./src/main.ts - Error: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
Error: [object Object]
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.0.7
Node: 18.18.0
Package Manager: npm 9.4.2
OS: linux x64

Angular: 17.0.8
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.7
@angular-devkit/build-angular   17.0.7
@angular-devkit/core            17.0.7
@angular-devkit/schematics      17.0.7
@angular/cli                    17.0.7
@schematics/angular             17.0.7
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.2
```

### Anything else?

I sincerely apologize if I'm doing something wrong. I'm working with a lot of frameworks at the moment so it's possible I'm using a wrong syntax or something. I promise I double and triple checked

**Comment by JoostK** [comment] 2023-12-21 19:04
This is _super_ weird.

With the `application` builder (using vite/esbuild) I see the following:

```ts
✘ [ERROR] function setExternalModuleIndicator(sourceFile) {
    sourceFile.externalModuleIndicator = isFileProbablyExternalModule(sourceFile);
  } could not be cloned. [plugin angular-compiler]

  This error came from the "onStart" callback registered here:

    node_modules/@angular-devkit/build-angular/src/tools/esbuild/angular/compiler-plugin.js:94:18:
      94 │             build.onStart(async () => {
         ╵                   ~~~~~~~

    at setup (/home/projects/node-4ksdju/test/node_modules/@angular-devkit/build-angular/src/tools/esbuild/angular/compiler-plugin.js:94:19)
    at async handlePlugins (/home/projects/node-4ksdju/test/node_modules/esbuild/lib/main.js:1330:9)
```

with `browser` (using webpack) it's indeed only
```
<e> [webpack-dev-middleware] Error: [object Object]
<e>     at  (<anonymous>)
```

In one incremental rebuild (using webpack) I got the following, revealing the root cause:

```
./src/main.ts - Error: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
Error: [object Object]

Error: src/main2.ngtypecheck.ts:1:1 - error NG3004: Unable to import symbol DisplaySizeComponent.
  The symbol is not exported from /home/projects/github-hkszdx/src/main2.ts.
```

That is still buggy though, as errors should never be reported in `.ngtypecheck.ts` files. I can't easily reproduce the above behavior.

Exporting the component does avoid the issues, both in webpack as well as vite.

**Comment by ilirbeqirii** [comment] 2023-12-22 01:32
This issue will go away the moment you export DisplaySizeComponent too.

**Comment by crutchcorn** [comment] 2023-12-25 00:33
Interestingly, _removing_ `export` from `AppComponent` also appears to solve this. I'm not sure I understand why in either case.

**Comment by devversion** [comment] 2024-02-07 18:02
This should be fixed now with https://github.com/angular/angular/pull/54309

**Closed by devversion** 2024-02-07 18:02 UTC
Labels: area: core, state: needs more investigation
