### ISSUE TITLE
zone.js breaks jest tests

### ISSUE THREAD

**Issue by ipelovski** [angular/angular#45675] opened 2022-04-19 08:42 UTC
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

Hello, I'm working of migrating jest tests to be run with `ng test`. The problem is that in zone.js there is a line of code that breaks most of the tests. On line https://github.com/angular/angular/blob/master/packages/zone.js/lib/jest/jest.ts#L78:
`return proxyZone.run(testBody, null, arguments as any);`
the test context is lost by passing `null` instead of `this`. In other places in the same file `this` is kept but on this line `null` is passed instead. Changing the mentioned line to:
`return proxyZone.run(testBody, this, arguments);`
fixes all tests.

### Please provide the exception or error you saw

```true
TypeError: Cannot read properties of null (reading '$injector')

      at Function.Object.<anonymous>.module.$$cleanup (node_modules/angular-mocks/angular-mocks.js:3279:32)
      at Object.<anonymous>.module.$$afterEach (node_modules/angular-mocks/angular-mocks.js:3274:14)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/bundles/zone-testing-bundle.umd.js:407:30)
      at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvoke (node_modules/zone.js/bundles/zone-testing-bundle.umd.js:3765:43)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/bundles/zone-testing-bundle.umd.js:406:56)
      at Zone.Object.<anonymous>.Zone.run (node_modules/zone.js/bundles/zone-testing-bundle.umd.js:167:47)
      at Object.wrappedFunc (node_modules/zone.js/bundles/zone-testing-bundle.umd.js:4250:34)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 12.2.15
Node: 16.14.0 (Unsupported)
Package Manager: npm 8.3.1
OS: darwin x64

Angular: 12.2.15
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router, upgrade

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.15
@angular-devkit/build-angular   12.2.15
@angular-devkit/core            12.2.15
@angular-devkit/schematics      12.2.15
@angular/cdk                    12.2.13
@schematics/angular             12.2.15
typescript                      4.2.4
```

**Comment by jessicajaniuk** [comment] 2022-05-16 23:57
@ipelovski Could you create a reproduction for us? It would be great if you could do it in latest, as well. Thanks!

**Comment by AndrewKushnir** [comment] 2022-06-07 00:02
Closing this ticket, since there is no repro.

**Closed by AndrewKushnir** 2022-06-07 00:02 UTC
Labels: comp: testing, needs reproduction, comp: zones
