### ISSUE TITLE
[beta.1] Error bundling using SystemJS Builder in Beta.1

### ISSUE THREAD

**Issue by antonybudianto** [angular/angular#6366] opened 2016-01-08 23:52 UTC
Hi, I just updated my starter project to **angular2.0.0@beta.1** and when running in development, it was okay, but when I run production build and serve it, it showed error as follows:
<img width="1280" alt="screen shot 2016-01-09 at 6 46 17 am" src="https://cloud.githubusercontent.com/assets/7658554/12212459/3275147c-b69d-11e5-9540-f7123cbeb031.png">
**It's not happening in angular2.0.0@beta.0**

you can reproduce it by cloning my [repo](https://github.com/antonybudianto/angular2-starter) using `repro-mangle-error` branch, then run `gulp serve-build`

I'm using [SystemJS builder](https://github.com/systemjs/builder) for bundling, thanks!

**Comment by antonybudianto** [comment] 2016-01-09 00:28
Finally getting it to work, I had to set `mangle: false` in SystemJS Builder options. But then the `boot.js` size becomes `~957 KB`, which in beta.0 (that works without mangle) size `~650 KB`...

**Comment by ocombe** [comment] 2016-01-10 06:18
I have a similar error on my ng2-webpack starter: https://github.com/ocombe/ng2-webpack/issues/7
The message is `No provider for t! (t -> t)` and adding `mangle: false` to the UglifyJS plugin fixes the problem (but the files are much bigger, so that's only temporary).

**Comment by antonybudianto** [comment] 2016-01-10 08:17
<img width="618" alt="screen shot 2016-01-10 at 3 14 34 pm" src="https://cloud.githubusercontent.com/assets/7658554/12220669/fae5c86a-b7ac-11e5-933f-bfdcae0fc252.png">

Looks like there's a bug in the viewFactory, this didn't happen in beta.0 (dev & build), and only didn't happen in beta.1 when dev, but broken when build.

**Comment by pkozlowski-opensource** [comment] 2016-01-18 20:03
Duplicate of https://github.com/angular/angular/issues/6380

**Closed by pkozlowski-opensource** 2016-01-18 20:03 UTC

**Comment by antonybudianto** [comment] 2016-01-18 23:15
but the 2nd picture is no duplicate issue I think
