### ISSUE TITLE
Instances of custom control on same FormControl doesn't get notified of model change

### ISSUE THREAD

**Issue by eshcharc** [angular/angular#17685] opened 2017-06-22 06:53 UTC
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[x] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
writeValue of every other instance of custom control does not being called upon change in control value.

## Expected behavior
writeValue should be called when the value of the control changes from outside the custom control.

## Minimal reproduction of the problem with instructions
1. Create a custom control that implements ControlValueAccessor interface.
2. Create a reactive form group with one control.
3. Add several instances of the same custom control attached to the same reactive form control.
4. Perform a change from one of the instances.
5. Wait for a response in writeValue method inside the other instances.

Reproduction plnkr: https://plnkr.co/edit/4WSchPZFCymdDIJFWyP8

## What is the motivation / use case for changing the behavior?
Custom Radio button control

## Please tell us about your environment

<pre><code>
Angular version: 4.2.3

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

</code></pre>

**Comment by eshcharc** [comment] 2017-06-22 07:28
## Optional workaround
use `<input type="hidden">` inside your custom control and attach FormControl to the hidden input.
Any view-to-model changes can be done with control.setValue.

**Comment by cagataycivici** [comment] 2017-10-02 11:08
This also causes problems for us in PrimeNG like;

https://github.com/primefaces/primeng/issues/2906

writeValue is called when used with template driven ngModel but not with reactive forms causing difference in behaviors. Would have been great if the reactive and regular forms behave same so component authors don't need to deal with differences.

**Comment by eshcharc** [comment] 2017-10-11 20:32
@cagataycivici It's not a valid workaround for library's reactive-form components. I'm talking about a wrapper component above input with type hidden. You still need to pass-in both FormGroup and formControlName and it's not A real custom control. Sorry.

**Comment by eshcharc** [comment] 2017-10-31 14:57
@IgorMinar Why doesn't this issue get a higher priority?
It involves any case in which there are **multiple usages of same form-control**.
In a very intense reactive form based application this happens quite often.

**Comment by chuckjaz** [comment] 2017-11-01 00:15
@eshcharc `writeValue()` is working as expected. It is documented to only write back to the control when propagating `model->view` changes as documented here: https://github.com/angular/angular/blob/master/packages/forms/src/directives/control_value_accessor.ts#L25. The `writeValue()` notifications are specifically excluded by the options provided here https://github.com/angular/angular/blob/master/packages/forms/src/directives/shared.ts#L103. The example provided calls the registered on change and expects that to trigger a `writeValue()` which is specifically what is we are trying to communicate, by design, will not happen.

Implementors of `writeValue()` can now unconditionally write the value into the view as it is guaranteed not to have come from view itself. If we modified this to write back when the view changes the model then we could introduce a cycle or cause redundant writes.

One way around this is to implement something like the `RadioControlRegistry` like the used by the `RadioControlValueAccessor`.

Alternately you can also consider implementing a composite control that orchestrates the radio buttons as content instead of relying on the `FormGroup` to orchestrate changes.

The current control value accessor model was not designed to help orchestrate view changes that compose into a single value.

As you point out, this makes writing such control laborious, so we would also entertain a feature request to make such orchestration easier.

I am closing this issue but feel free to open a new issue that contains a feature request.

**Closed by chuckjaz** 2017-11-01 00:15 UTC
Labels: comp: forms
