### ISSUE TITLE
ContentChildren and ContentChild don't work for 2 levels nested descendants

### ISSUE THREAD

**Issue by kkuriata** [angular/angular#33770] opened 2019-11-12 19:09 UTC
# 🐞 bug report

### Affected Package
@angular/core

### Is this a regression?

Yes, I have also checked 7.x version.

### Description

ContentChildren/ContentChild decorators don't work for nested descendants. Once you try to get the ElementRef for at least 2 levels-nested element, you only get the undefined.

## 🔬 Minimal Reproduction

1. Go to [Stackblitz](https://stackblitz.com/edit/angular-vzdphe)
2. Check the console

## 🔥 Exception or Error

No error, just undefined instead of correct ElementRef.

## 🌍  Your Environment

<pre><code>
Angular CLI: 8.3.18
Node: 10.16.2
OS: win32 x64
Angular: 8.2.13
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.3
@angular-devkit/build-angular     0.803.18
@angular-devkit/build-optimizer   0.803.18
@angular-devkit/build-webpack     0.803.3
@angular-devkit/core              8.3.3
@angular-devkit/schematics        8.3.3
@angular/cdk                      8.2.3
@angular/cli                      8.3.18
@angular/flex-layout              8.0.0-beta.27
@angular/material                 8.2.3
@ngtools/webpack                  8.3.18
@schematics/angular               8.3.3
@schematics/update                0.803.18
rxjs                              6.5.3
typescript                        3.5.3
webpack                           4.39.2

</code></pre>

**Anything else relevant?**

**Comment by Airblader** [comment] 2019-11-12 19:23
https://angular.io/guide/template-syntax#ref-vars

>The scope of a reference variable is the entire template.

Template reference variables are only valid within their template, therefore trying to search for them from outside the template doesn't work. IMHO this is intended behavior. 

You can use different selectors such as the component itself or some directive etc.

**Comment by pkozlowski-opensource** [comment] 2019-11-12 19:57
@Airblader is correct - `@ContentChildren` are supposed to pick up _only_ children (as written in a template) of a component (everything written between `<app-parent>...only picks-up stuff here...</app-parent>` in your case).

> Yes, I have also checked 7.x version.

Are you sure? I don't think this logic changed... ever... 

> ContentChildren/ContentChild decorators don't work for nested descendants. Once you try to get the ElementRef for at least 2 levels-nested element, you only get the undefined.

I think that there is confusion here about what `descendants` mean. Given your example:

```
<app-parent>
   <div> // query will pick up this with descendants = false
       <span></span> // query will NOT pick up this with descendants = false
   </div>
<app-parent>
```

So, it is all about component's _content_.

I'm going to close this one as I believe that it works as intended. Happy to re-open as regression if you can demonstrate that it used to work in earlier versions of Angular.

**Closed by pkozlowski-opensource** 2019-11-12 19:57 UTC
