### ISSUE TITLE
request| feat: Warn devs when two versions of Angular2 are bundled

### ISSUE THREAD

**Issue by gdi2290** [angular/angular#6619] opened 2016-01-21 16:01 UTC
With the beta releases 3rd party modules either needs always to be updated otherwise developer will end up with obscure errors when instanceof doesn't work. For example, the `angular2-jwt` had this problem when it's dependency was beta.0 and devs would use beta.1 so two versions of angular2 would bundle together when using browserify or webpack. Developers will also have this problem if they revert to beta.0 for the minification problems and these 3rd party modules didn't specify compatibility correctly in package.json 

### proposal 
* Provide a way to determine the angular2 version
* Warn developers if there are two versions bundled (only during the beta releases and in development)

**Comment by alexpods** [comment] 2016-01-21 19:39
+1 
Also, please, replace all:
```js
a instanceof Array`
```
 on 
```js
Array.isArray(a);
// or
Object.prototype.toString.call(a) === '[object Array]'
```
It's already a pain:

* in a browser `angular2` doesn't work if you have multiple frames 
* in nodejs `angular2` doesn't work if you're using `vm.runInNewContext`

**Comment by born2net** [comment] 2016-02-12 06:08
+1 please provide a way to show current running version

**Comment by curlyfro** [comment] 2016-02-13 14:59
+1

**Comment by laco0416** [comment] 2016-02-13 15:06
+1

**Comment by gdi2290** [comment] 2016-08-18 05:41
this could also be handled during build-time

**Comment by IgorMinar** [comment] 2016-10-08 00:18
Thanks for reporting this issue. However this issue is a duplicate of an existing issue #1357. Please subscribe to that issue for future updates.

**Closed by IgorMinar** 2016-10-08 00:18 UTC
Labels: comp: build & ci, comp: packaging

**Comment by fmorriso** [comment] 2016-10-16 18:43
+1
for both a command-line as well as a run-time API to get major, minor and full "version" information.
