### ISSUE TITLE
Computed signal does not recalculate when the input signal is inside an observable pipe

### ISSUE THREAD

**Issue by Ionaru** [angular/angular#54050] opened 2024-01-24 14:21 UTC
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

Given this component:

```ts
@Component({
  selector: 'app-my-component',
  standalone: true,
  template: ''
})
export class MyComponent {

  readonly #dataService = inject(DataService);
  dataFilter = input.required<string>();

  data$ = computed(() => this.#dataService.data.pipe(
    map((data) => data.filter((item) => item.id === this.dataFilter())),
  ));
}
```

The computed signal runs once, but does not recalculate when `dataFilter` changes.
My guess is that this is caused by `this.dataFilter()` being deep inside nested functions and only runs when the observable is subscribed to, but the behaviour is confusing.

As a current workaround, the function can be changed to this:
```ts
data$ = computed(() => {
  const dataFilter = this.dataFilter();
  return this.#dataService.data.pipe(
    map((data) => data.filter((item) => item.id === dataFilter)),
  );
});
```

The above function will work, and change the observable correctly when the input changes. But the extra variable assignment (and required braces and `return` statment), makes this function less elegant.

Is it possible to make inputs/signals within Observable pipes work?

### Please provide a link to a minimal reproduction of the bug

See above

### Please provide the exception or error you saw

```true
N/A
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 17.1.0
Node: 20.10.0
Package Manager: npm 10.2.5
OS: win32 x64

Angular: 17.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, platform-server, router, ssr

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1701.0
@angular-devkit/build-angular   17.1.0
@angular-devkit/core            17.1.0
@angular-devkit/schematics      17.1.0
@schematics/angular             17.1.0
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.3
```

### Anything else?

Loving the new `InputFunction` 😁

**Comment by Ionaru** [comment] 2024-01-24 14:24
Related to https://github.com/angular/angular/issues/54032

**Comment by TarsisDragomir** [comment] 2024-01-24 14:34
You're basically making an Signal<Observable<Item>> in this way, which is not what it is meant for as far as my understanding goes. It will still require an | async in your template to get anything out of it via a subscription, whereas the aim should be to be able to do just {{ data$() }} iso {{ data$() | async }}
But how to get anything in a signal in an asynchronous way (in a correct angular way) is also something which I am struggling with (see [54047](https://github.com/angular/angular/issues/54047)). I have shown 3 ways of doing it in the stackblitz mentioned in the same thread, but not sure which of those we are supposed to use (and still follow angular best practices).

**Comment by Ionaru** [comment] 2024-01-24 14:58
Thank you for the extensive experimentation on the issue!

I like your `toSignal(Stream)` solution the best out of the three.

```ts
export class MyComponent {

  readonly #dataService = inject(DataService);
  dataFilter = input.required<string>();

  dataSignal = toSignal(this.#dataService.data, { initialValue: [] });
  data = computed(() => this.dataSignal().filter((item) => item.id === this.dataFilter()));
}
```

However, the need to use 2 signals (3 if you count the input), where 1 is only used to transform the observable is unfortunate. Webstorm also seems to lose track of the type of `data` in the template, but that is probably an issue on JetBrains' side.

**Comment by TarsisDragomir** [comment] 2024-01-24 15:11
You're welcome.
In your case (your data is only dependent on 1 signal), you could go for:
```
data$ = toSignal(
    toObservable(this.dataFilter).pipe(
      switchMap((filter) => this.#dataService.data.pipe(map((data) => data.filter((item) => item.id === filter))))
    )
  );
```

But then you probably start to see why I'm asking about the usage of effects for this; as switching between signals (toSignal()) and observables (toObservable()) all the time don't feel the way to go imho.

**Comment by alxhub** [comment] 2024-01-24 16:44
I would 100% favor @Ionaru's approach - convert the RxJS data stream into a signal, and use `computed` to synchronously filter. For me, this is clear and readable, and that wins over "fewer characters" any day.

I'm going to close this issue as `computed` is working as intended here.

**Closed by alxhub** 2024-01-24 16:44 UTC
Labels: area: core, core: reactivity

**Comment by TarsisDragomir** [comment] 2024-01-26 07:23
@alxhub Super, glad to read that. I was merely playing the advocate of the devil in that last proposal to show the possible ping-pong of toSignal - toObservable we can get into.
In the example above I follow you completely, since the filtering is done in a synchronous way a `computed` is perfect but what happens when the filter should be send to the backend as well and the filtering happens at server side. Would you then go for a toSignal - toObservable stream or make an effect for it? That's a topic I like to be discussed in [54047](https://github.com/angular/angular/issues/54047) and would love to get your inputs there as well. Sorry for abusing this issue to promote mine, but I really feel they are interlinked and clear statements/examples on this could benefit a lot of people that are now confused/building all kind of utilities to go around the problem.
