### ISSUE TITLE
Question: Formatter and Parser-Equivalent in Angular 2

### ISSUE THREAD

**Issue by manfredsteyer** [angular/angular#6174] opened 2015-12-30 01:46 UTC
Hi,

I've searched the sources to find an equivalent to the Parser and Formatter-concept in AngularJS 1.x. As it looks like, we can use custom Value-Accessors to format and parse bindings. 

- Is this a good idea?
- If yes, is the following implementation (that works and parses/formats a German Date in the format Day.Month.Year) ok?
- We are using multi-bindings here. How does Angular 2 behave, when there is more then one Accessor for one component?

Wishes,
Manfred

```
import {Directive, Renderer, ElementRef, Self, forwardRef, Provider} from 'angular2/core';

import {NG_VALUE_ACCESSOR, DefaultValueAccessor } from 'angular2/common';
import {CONST_EXPR} from 'angular2/src/facade/lang';

const PROVIDER = CONST_EXPR(new Provider(
    NG_VALUE_ACCESSOR, {useExisting: forwardRef(() => DateValueAccessor), multi: true}));
    
@Directive({
  selector:
      'input[date]',
  host: {'(input)': 'input($event.target.value)', '(blur)': 'blur()'},
  bindings: [PROVIDER]
})
export class DateValueAccessor extends DefaultValueAccessor {
   
    constructor(_renderer: Renderer, _elementRef: ElementRef) {
       super(_renderer, _elementRef);
    }
    
    blur() {
        this.onTouched();
    }
    
    input(value) {
    
        // Write back to model   
        if (value) {
            value = value.split(/\./);
            value = value[2] + "-" + value[1] + "-" + value[0];
        }
        
        this.onChange(value);
    }
    
    writeValue(value: any): void {
        
        // Write to view
        if (value) {
            var date = new Date(value);
            value = date.getDate() + "." + (date.getMonth()+1) + "." + date.getFullYear(); 
        }
        
        super.writeValue(value);
        
    }

} 
```

**Comment by martinoppitz** [comment] 2016-01-05 07:38
:pushpin: I 'm interested in this solution.

**Comment by lukepfeiffer10** [comment] 2016-01-05 14:24
+1

**Comment by patrickrupp** [comment] 2016-01-07 05:30
:pushpin: :+1: I'm also intrested in a solution for formatters and parsers.
 
There is an issue addressing this topic: https://github.com/angular/angular/issues/3009

**Comment by jakemoves** [comment] 2016-03-02 20:03
See also http://stackoverflow.com/questions/34948961/angular-2-custom-form-input

**Comment by saskodh** [comment] 2016-04-29 10:24
+1

**Comment by daniel-a-melo** [comment] 2016-06-13 18:57
This implementation no longer works on RC1. I based one implementation on this code and confirmed that it fails on RC1 whereas it works correctly on beta 17.

I opened an issue : https://github.com/angular/angular/issues/9146

**Comment by pkozlowski-opensource** [comment] 2016-08-20 09:58
Duplicate of #3009

**Closed by pkozlowski-opensource** 2016-08-20 09:58 UTC

**Comment by istiti** [comment] 2017-01-13 13:12
does this good approach ?
