### ISSUE TITLE
router-link/router-outlet refresh

### ISSUE THREAD

**Issue by john-schulz** [angular/angular#3113] opened 2015-07-17 16:07 UTC
When you use `<a router-link="foo">Link</a>` with an accompanying `<router-outlet></router-outlet>`, the proper component's template appears in the outlet. The issue is when the user refreshes (on the proper URL extension, i.e., `localhost:8080/foo`), no templates are loaded (including the original app's template), leaving the page blank. As far as I can tell, what's happening is that as that URL only is marked to use the template of `foo`, so there is no outlet for it to show up in. There is the chance I am doing this wrong, but everything else is working properly.

**Comment by btford** [comment] 2015-07-17 18:02
What version of Angular? And can you please steps to reproduce?

**Comment by john-schulz** [comment] 2015-07-17 19:29
Alpha-28, as Alpha-31 and Alpha-30 was not working properly for the `<a router-link='foo'>Link</a>`. 

```typescript
@RouteConfig([
    { path: '/', component: Base, as: 'base' },
    { path: '/home', component: Trombone, as: "trombone" },
    { path: '/about', component: About, as: "about"}
])
```
and
```html
<a router-link="trombone">TromboneLink</a>
<a router-link="base">BaseLink</a>
<a router-link="about">AboutLink</a>
```

index.html
```html
<html>
    <head>
        <title>Angular 2 Quickstart</title>
        <script src="https://github.jspm.io/jmcriffey/bower-traceur-runtime@0.0.87/traceur-runtime.js"></script>
        <script src="https://jspm.io/system@0.16.js"></script>
        <script src="https://code.angularjs.org/2.0.0-alpha.27/angular2.dev.js"></script>
        <script src="https://code.angularjs.org/2.0.0-alpha.27/router.dev.js"></script>
    </head>
    <body>
        <my-app></my-app>
        <script>System.import('app')</script>
    </body>
</html>
```

When I would select the link for `AboutLink`, it would display everything in the `<router-outlet>` area fine as well as make the URL `localhost:8080/about`. That's all fine and dandy.

When I would refresh the page at that URL, the page would appear blank. Upon inspection of the page in the Developer Console, the `<my-app></my-app>` element (the component which contains the `@RouteConfig`) was not even in the DOM - The DOM ended up looking like this: 
```html
<html>
    <head>
    </head>
    <body>
        <pre style="word-wrap: break-word; white-space: pre-wrap;"></pre>
    </body>
</html>
```

Like I said earlier (and I'd like to reiterate, __I AM NOT AN EXPERT__), I feel as though the problem is that upon refresh, the page requests the template from the About Component, but has no outlet to display it inside. This may very well be wrong, but it's just what I feel like may be the issue

**Comment by btford** [comment] 2015-07-17 21:13
You're missing a base href tag in your HTML.

Until now, the router didn't give a good error message about this, so it was definitely a confusing point. I just landed 011fab37af626535c1d5af7091d72e27d93f4391 which gives a more prescriptive error message.

This issue is a duplicate of #3096 – see the discussion there for more.

**Closed by btford** 2015-07-17 21:13 UTC
Labels: comp: router, effort2: medium (day), P2: required, type: bug

**Comment by john-schulz** [comment] 2015-07-17 21:49
My sincerest apologies. I should have looked more in depth at the issues. Thank you for pointing out my problem. Good luck with the rest of development!

**Comment by chenyingyin** [comment] 2016-12-01 05:31
![default](https://cloud.githubusercontent.com/assets/24284270/20782714/60f05eaa-b7c9-11e6-9006-f7beb8bef322.png)
