### ISSUE TITLE
Query params overwrite each other when set at the same time via this.router.navigate()

### ISSUE THREAD

**Issue by jaworek** [angular/angular#37042] opened 2020-05-11 08:53 UTC
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/router

### Is this a regression?
I have not tested it on older versions of Angular. I'm currently using Angular 9.

### Description

I'm building an application that sets up a couple of values that I would like to keep in query params for users to easily share.

I tried to find a good solution on how to properly manage and keep them in sync with values set in services, but it seems that there aren't many solutions available, so I came up with custom one.

I came up with service that hides implementation details from consumers, so they do not know that additional data handling is done, so they can use these values as normal:

```
export class ValueService {
  private value: number;
  private valueSource: BehaviorSubject<number>;
  value$: Observable<number>;

  constructor(private route: ActivatedRoute, private router: Router) {
    const valueParam = this.route.snapshot.queryParams?.value;

    if (valueParam) {
      this.value = valueParam;
    } else {
      this.value = 5;
      this.router.navigate([window.location.pathname], {
        queryParamsHandling: 'merge',
        queryParams: { value: this.value },
        replaceUrl: true,
      })
    }

    this.valueSource = new BehaviorSubject<number>(this.value);
    this.value$ = this.valueSource.asObservable();
  }

updateValue(value: number) {
    this.valueSource.next(value);
    this.value = value;
    this.router.navigate([window.location.pathname], {
      queryParamsHandling: 'merge',
      queryParams: { value: this.value },
    })
  }

  getValue(): number {
    return this.value;
  }
}
```

Main problem with this solution is that when I use multiple services with similar implementation, only one value is set in query params and other seem to be cancelled out.

E.g. I have ```value = 5``` and ```value2 = 7```. In query params my output will be ?value=5 and not ```?value=5&value=7```

I was able to fix it by wrapping ```this.router.navigate()``` with ```setTimeout()``, but I don't think it is a good solution for the long run.

I think that the problem is that they all fire at the same time instead of sequentially, which causes one of them to be cancelled. I have not found solution to fix this issue. I suspect this may be a bug in Angular.

## 🔬 Minimal Reproduction
https://codesandbox.io/s/determined-field-2t9pl?file=/src/app/services/value.service.ts

## 🌍  Your Environment

**Angular Version:**
<pre><code>
@angular-devkit/architect         0.901.0
@angular-devkit/build-angular     0.901.0
@angular-devkit/build-optimizer   0.901.0
@angular-devkit/build-webpack     0.901.0
@angular-devkit/core              9.1.0
@angular-devkit/schematics        9.1.0
@angular/cdk                      9.2.0
@ngtools/webpack                  9.1.0
@schematics/angular               9.1.0
@schematics/update                0.901.0
rxjs                              6.5.4
typescript                        3.8.3
webpack                           4.42.0
</code></pre>

**Anything else relevant?**
This issue is present both on Firefox and Chrome based browsers.

**Comment by atscott** [comment] 2020-05-12 22:07
While this is working as intended (please see #11374, #11373, and #11662), I understand that most backends support repeating the same key several times so I'll keep this open as a feature request.

Related discussion on stackoverflow: https://stackoverflow.com/a/24728298

**Comment by jaworek** [comment] 2020-05-13 08:55
Hi, thanks for the answer. Unfortunately, my solution does not involve repeating the same key several times.
What I'm trying to achieve is to set query params from different services.

<img width="1183" alt="image" src="https://user-images.githubusercontent.com/22678765/81792006-be67ba00-9507-11ea-9d8f-d3a711fec8e9.png">

In this image I have two query params that I want to set if user accesses website without setting them. E.g. ```http://localhost:4200/routes-overview/margin```. With my current solution if I do not wrap one of the navigation calls in ```setTimeout()```, I end up with ```http://localhost:4200/routes-overview/margin?date=2020-05-01``` instead of ```http://localhost:4200/routes-overview/margin?date=2020-05-01&zoom=week```

**Comment by atscott** [comment] 2020-05-13 17:22
@jaworek - Ah, I see. Sorry, I misunderstood the issue from the description. What's happening here is that the navigation transitions are implemented with a `switchMap`. If you call `router.navigate` while a navigation is still in progress, it will cancel the previous navigation.This is working as intended as well. Only one of your navigations goes to completion, and you can't merge params with in-flight navigations. 

To solve your issue, you'll need another service that coordinates the queryParams for you, like https://codesandbox.io/s/dazzling-taussig-s4lfk?file=/src/app/services/param-coordination.service.ts. Managing global state in apps can be difficult. If you're not already familiar with NgRx/Redux, I'd recommend taking a it: https://ngrx.io/.

Hope that helps! Closing this now as working as intended.

**Closed by atscott** 2020-05-13 17:22 UTC
Labels: comp: router, freq1: low, type: feature

**Comment by jaworek** [comment] 2020-05-13 17:29
Thank you for the suggestions. I will try it out.
