### ISSUE TITLE
Metadata being output in the wrong location w/ Angular 5

### ISSUE THREAD

**Issue by jelbourn** [angular/angular#19832] opened 2017-10-20 17:03 UTC
### Steps to reproduce
* Clone https://github.com/jelbourn/metadata-out-repro
* `npm i`
* `./node_modules/.bin/ngc -p ./src/cdk/tsconfig.json`

### Expected behavior
Metadata is output to `dist/packages/cdk`

### Actual behavior
Metadata is output to `dist/packages/cdk/cdk`

The reproduction captures an issue affecting Angular Material when using Angular 5.
cc @tbosch @chuckjaz, originally reported by @crisbeto and @DevVersion

**Comment by Toxicable** [comment] 2017-10-20 18:08
Without investigating your case specifically (so I could be wrong) it looks like a dupe of this?
https://github.com/angular/angular/issues/19718

**Comment by tbosch** [comment] 2017-10-20 18:08
Yes, agree.

**Comment by IgorMinar** [comment] 2017-10-25 17:42
fixed by #19772

**Closed by IgorMinar** 2017-10-25 17:42 UTC
Labels: comp: core & compiler, hotlist: angular-core-team, hotlist: material2, severity5: regression, type: bug
