### ISSUE TITLE
AOT compilation there is no ngFactory file generated

### ISSUE THREAD

**Issue by petermezei** [angular/angular#13397] opened 2016-12-12 16:13 UTC
Hi guys,

I have been trying to solve this issue for 64 hours and nothing. I am a bit tired. Could you help me please?

Here is the project: https://github.com/slamby/slamby-website

Right now I do not use the aot compilation for production, everything is ready to start it, but I have the same issue, generating ngFactory fiels: there are no ngFactory files generated, just js files.

My tsconfig.aot.json

```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "es2015",
    "moduleResolution": "node",
    "outDir": "./aot",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": ["es2015", "dom"],
    "noImplicitAny": true,
    "suppressImplicitAnyIndexErrors": true,
    "typeRoots": [ "./node_modules/@types" ],
    "types": [
      "node"
    ]
  },
  "files": [
    "./src/app/app.module.ts"
  ],
  "angularCompilerOptions": {
   "genDir": "./aot",
   "skipMetadataEmit" : true
 }
}
```

Command to execute ngc:
> node_modules/.bin/ngc -p tsconfig.aot.json

Output files print screen:

![image](https://cloud.githubusercontent.com/assets/18461114/21105702/801c0868-c08b-11e6-85fb-3cbdd99c5f61.png)

Angular pacakages:

```json
    "@angular/common": "~2.3.0",
    "@angular/compiler": "~2.3.0",
    "@angular/compiler-cli": "^2.3.0",
    "@angular/core": "~2.3.0",
    "@angular/forms": "~2.3.0",
    "@angular/http": "~2.3.0",
    "@angular/platform-browser": "~2.3.0",
    "@angular/platform-browser-dynamic": "~2.3.0",
    "@angular/platform-server": "^2.3.0",
    "@angular/router": "~3.3.0",
```
Typescript:
```json
"typescript": "^2.0.2",
```

Could you please help me?

**Comment by mdsauer** [comment] 2016-12-13 01:01
You might want to see what version of typescript you really have. (npm ls typescript) Other issues have indicated that versions greater than 2.0.10 will not work.  I went back to 2.0.2 and got it working again.  I have not tried 2.0.10.

**Comment by laco0416** [comment] 2016-12-13 02:29
probably duplicate of #13204

**Comment by petermezei** [comment] 2016-12-13 09:27
Hi thanks @robisim74 . Sure, i am trying with different package versions but still does not work.
I will remove each of my thir party packages, and try it out.

In the files section i have already provided my app.module.ts. That should not be enough for AOT compilation? In main.aot.ts I need to provide the app.module.ngfactory.ts file but its not generated yet.

Thank you in advance,
Best wishes,
Peter.

**Comment by robisim74** [comment] 2016-12-13 09:54
You don't need to create first _NgFactory_ files and then change the application's bootstrap (which in any case should be the _main_, not only the _app.module_).
I suggest you follow all the example of the guide (https://angular.io/docs/ts/latest/cookbook/aot-compiler.html), to understand how it works.
Then if you get specific errors, you can find many answers on this repo and on StackOverflow.

Greetings,
Roberto

**Comment by petermezei** [comment] 2016-12-13 10:24
Hi @robisim74, thanks, based on that tutorial I created a very minimal project, and tried it out, but nothing. ngFactory files are not generated.

https://github.com/petermezei/angular2-aot-webpack-website-seed

Even the tsconfig.aot.json is the same like in the tutorial.

When i run `node_modules/.bin/ngc -p tsconfig.aot.json` then js files are created, but ngfactory files are not.

The project is very super minimal, but still does not work and there is no error.

Thank you,
Peter.

**Comment by robisim74** [comment] 2016-12-13 10:44
As said, the problem is the `main.ts` file. Change it so:

```
import { platformBrowser }    from '@angular/platform-browser';
import { AppModuleNgFactory } from '../../aot/src/app/app.module.ngfactory';

platformBrowser().bootstrapModuleFactory(AppModuleNgFactory);
```

and it will work. Kindly, see all the differences with your main.

**Comment by petermezei** [comment] 2016-12-13 10:57
Thank You @robisim74 , now it works after a few version update and downgrade.
Once I installed all the requred packages with the default npm version, it did not work.

I downgraded the packages, now the versions that work:
```json
    "@angular/common": "2.2.3",
    "@angular/compiler": "2.2.3",
    "@angular/compiler-cli": "2.2.3",
    "@angular/core": "2.2.3",
    "@angular/platform-browser": "2.2.3",
    "@angular/platform-browser-dynamic": "2.2.3",
    "@angular/platform-server": "2.2.3",
    "core-js": "^2.4.1",
    "rxjs": "^5.0.1",
    "zone.js": "^0.7.2"
```

plus, typescript

```json
"typescript": "2.0.2"
```

I changed my main.ts as you adviced and now it works nicely.

Thank you,
you made my day.

Have a nice day,
Peter.

**Comment by robisim74** [comment] 2016-12-13 12:37
To be precise: AoT compilation works fine with the latest Angular version & these settings:

```
  "dependencies": {
    "@angular/common": "2.3.0",
    "@angular/compiler": "2.3.0",
    "@angular/compiler-cli": "2.3.0",
    "@angular/core": "2.3.0",
    "@angular/platform-browser": "2.3.0",
    "@angular/platform-browser-dynamic": "2.3.0",    
    "@angular/platform-server": "2.3.0",
    "core-js": "2.4.1",
    "rxjs": "5.0.0-rc.4",
    "zone.js": "0.7.2"
  },
  "devDependencies": {
    "typescript": "2.0.10"
  }
```
If these settings don't work, try to remove `node_modules` and to update your npm: `npm install -g npm@latest`.

**Comment by marcalj** [comment] 2016-12-24 18:15
Same problem with latest version (Angular 4.0.0-beta.1 and TypeScript 2.1). No ```*.ngfactory.js``` files generated. Using ngUpgrade.

```json
{
    "compilerOptions": {
        "target": "es5",
        "module": "es2015",
        "moduleResolution": "node",
        "sourceMap": true,
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "lib": ["es2015", "dom"],
//        "noImplicitAny": true,
        "suppressImplicitAnyIndexErrors": true,

        "outDir": ".tmp/scripts/"
    },

    "files": [
        "typings/index.d.ts",
        "app/scripts/app.ts"
    ],

    "angularCompilerOptions": {
        "genDir": ".tmp/scripts/",
        "skipMetadataEmit" : true
    }
}
```

**Comment by robwormald** [comment] 2016-12-24 19:29
typescript 2.1 is currently not supported (and manifests itself exactly this way) - 2.1 support should land shortly after the holidays in the 4.0 betas

**Comment by mlc-mlapis** [comment] 2016-12-24 19:42
Yes sir, we have to wait :)

**Comment by tbosch** [comment] 2016-12-28 19:55
Closing as issue was typescript 2.1 which we don't support yet.

**Closed by tbosch** 2016-12-28 19:55 UTC
Labels: comp: core & compiler
