### ISSUE TITLE
TypeScript Type inference  page url is linked from tutorial but the url is broken/no such page exists

### ISSUE THREAD

**Issue by SantoshNayak** [angular/angular#53377] opened 2023-12-06 04:18 UTC
### Describe the problem that you experienced

**How to reproduce**
1. Go to https://angular.dev/tutorials/learn-angular/updating-the-component-class 
2. On the first bullet point 's description click on the hyper link  [type inference in TypeScript](https://angular.dev/typescript.org/type-inference).

![image](https://github.com/angular/angular/assets/26774073/3eca59a6-db65-4e74-8717-d6ec1e33a280)

3. it will take you to a broken page

![image](https://github.com/angular/angular/assets/26774073/6efc4cae-34bf-4407-bd63-c0a290063f7f)

### Enter the URL of the topic with the problem

https://angular.dev/typescript.org/type-inference

### Describe what you were looking for in the documentation

I was exploring whats new in Angular 17

**Comment by JoostK** [comment] 2023-12-06 06:49
Thanks for the report, this is a duplicate of #52553 for which the fix is pending deployment.

**Closed by JoostK** 2023-12-06 06:49 UTC
