### ISSUE TITLE
Uncaught ReferenceError: Must call super constructor

### ISSUE THREAD

**Issue by slanden** [angular/angular#24072] opened 2018-05-23 16:46 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Running app in the browser throws the following error when built with `ng build --prod`.

#### Error
Uncaught ReferenceError: Must call super constructor in derived class before accessing 'this' or returning from derived constructor
    at new <anonymous> (main.2b27b27881f08e65d5b0.js:1)
    at main.2b27b27881f08e65d5b0.js:1
    at Object.zUnb (main.2b27b27881f08e65d5b0.js:1)
    at p (runtime.a66f828dca56eeb90e02.js:1)
    at Object.3 (main.2b27b27881f08e65d5b0.js:1)
    at p (runtime.a66f828dca56eeb90e02.js:1)
    at n (runtime.a66f828dca56eeb90e02.js:1)
    at Array.e [as push] (runtime.a66f828dca56eeb90e02.js:1)
    at main.2b27b27881f08e65d5b0.js:1

## Expected behavior

App should start up and run without error when built with `--prod` flag if no compile error was thrown during build and no custom code violates the condition described in the error.

## Minimal reproduction of the problem with instructions

```
npm install -g @angular/cli

ng new PROJECT-NAME
cd PROJECT-NAME
ng build --prod
```

Upload app to server
OR
If PHP installed, start local PHP server by:
1) Open terminal at  "/dist/PROJECT-NAME"
2) Run command `php -S localhost:8080`

Run app.

## What is the motivation / use case for changing the behavior?

Optimization techniques within the production build process seem to be broken.

## Environment

<pre><code>
Angular version: 6.0.2

Browser:
- [x] Chrome (desktop) version 66.0.3359.181
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.11.1  
- Platform:  Linux (Ubuntu) 

Others:

</code></pre>
Server: PHP's built-in web server

**Comment by trotyl** [comment] 2018-05-23 17:44
Duplicate of https://github.com/angular/angular-cli/issues/10193. Not an Angular issue. Fixed.

**Comment by IgorMinar** [comment] 2018-05-24 22:38
thanks @trotyl

**Closed by IgorMinar** 2018-05-24 22:38 UTC

**Comment by slanden** [comment] 2018-05-25 15:11
thank you @trotyl
