### ISSUE TITLE
Exception inside Template is swallowed if triggered by a promise

### ISSUE THREAD

**Issue by happyherp** [angular/angular#15702] opened 2017-04-01 21:08 UTC
**I'm submitting a ...**  (check one with "x")
```
[ X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

An error inside a template is swallowed if the template was rendered as a response to a promise resolution. 

In other cases the same exception is properly logged. Exception in .then() is OK. Exception in template that was not rendered in response to a promise is OK

**Expected behavior**

The exception should either be passed to the .catch-function or logged. 

**Minimal reproduction of the problem with instructions**

http://plnkr.co/edit/ilqlcUUnrRpvFEFuzQc6?p=preview&open=app%2Fapp.component.ts

Run the plunkr and see that there is no exeption. 

Comment out Mark2 and put back in Mark1 or Mark3 and see that the error is handled properly. 

**What is the motivation / use case for changing the behavior?**

When the error inside templates silently fails It makes it much harder for me to figure out why the template does not finish rendering. 

* **Angular version:** 4.0.0

* **Browser:** Chrome, bot probably all.

**Comment by DzmitryShylovich** [comment] 2017-04-01 21:48
Looks like zone.js issue.

There's a similar issue https://github.com/angular/zone.js/issues/706
Could you please re-open this issue on https://github.com/angular/zone.js/issues ?

**Comment by DzmitryShylovich** [comment] 2017-04-01 22:17
Yes, it's a duplicate of angular/zone.js#706

I tried the fix https://github.com/angular/zone.js/pull/709 and it did the trick

**Comment by happyherp** [comment] 2017-04-02 06:51
@DzmitryShylovich Thanks for looking it up. That seems to be the problem. If you don't need this issue, I would close it.

**Comment by DzmitryShylovich** [comment] 2017-04-02 06:53
close it please. we can't fix it in this repo anyway. thanks

**Closed** 2017-04-02 07:08 UTC
