### ISSUE TITLE
Router does not handle question mark (?) and ampersand (&) in query strings as per URI syntax

### ISSUE THREAD

**Issue by preethamvishy** [angular/angular#32847] opened 2019-09-25 02:52 UTC
# 🐞 bug report

### Affected Package
@angular/router

### Is this a regression?
No

### Description
Per the [URI specification](https://tools.ietf.org/html/rfc3986#section-3.3), query is allowed to have the following syntax

> `query  = *( pchar / "/" / "?" )` 
> pchar         = unreserved / pct-encoded / sub-delims / ":" / "@"
> unreserved    = ALPHA / DIGIT / "-" / "." / "_" / "~"
> sub-delims    = "!" / "$" / "&" / "'" / "(" / ")" / "*" / "+" / "," / ";" / "="

Angular router currently only parses a path like `https://angular-site.com/route?foo=https://foobar.com/home?param1=123` to get the query params as `{ foo: 'https://foobar.com/home }`

Even further, a url like `https://angular-site.com/route?foo='https://foobar.com/home?param1=123&param2=2'&bar=test` requires more than just adding a question mark in the regex at [url tree parser](https://github.com/angular/angular/blob/master/packages/router/src/url_tree.ts#L428).

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-router-url-segment-66tqza

## 🔥 Exception or Error
None

## 🌍  Your Environment
Angular 6

**Comment by tcd** [comment] 2020-05-20 15:08
Any word on this?

**Comment by atscott** [comment] 2020-07-13 18:10
duplicate of #28154

**Closed by atscott** 2020-07-13 18:10 UTC
Labels: comp: router, freq2: medium, router: URL parsing/generation, severity2: inconvenient, state: confirmed, type: bug/fix
