### ISSUE TITLE
canDeactivate should not change the url when returns false and skipLocationChange has been set to true

### ISSUE THREAD

**Issue by vijaylokhande** [angular/angular#20271] opened 2017-11-08 11:54 UTC
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ "x"] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behaviorin 
canDeactivate  change the url when returns false and skipLocationChange has been set to true
## Expected behavior
canDeactivate should not change the url when returns false 

## Environment

<pre><code>
Angular version: 5.0

Browser:
- [x] Chrome (desktop) version XX
- [x] Chrome (Android) version XX
- [x] Chrome (iOS) version XX
- [x] Firefox version XX

 
For Tooling issues:
- Node version: 4.2 
- Platform:  Windows

**Comment by trotyl** [comment] 2017-11-09 06:14
Duplicate of #16314

**Comment by jasonaden** [comment] 2017-11-30 23:38
Closing as duplicate.

**Closed by jasonaden** 2017-11-30 23:38 UTC
Labels: comp: router
