### ISSUE TITLE
Service worker data-sync and periodic-data-sync features not support Angular 6.1.0

### ISSUE THREAD

**Issue by AsodariyaP** [angular/angular#27613] opened 2018-12-12 01:20 UTC
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

In Progressive web app service worker sync data and periodic sync data not supported with angular V6.1.0. 

Thank you!

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by gkalpak** [comment] 2018-12-12 11:49
I am not sure what exactly you are referring to. It sounds like you are requesting some kind of data syncing mechanism to be built into `@angular/service-worker`. We don't have immediate plans to implement such a feature, but it is being tracked in #22145.

Closing this as a duplicate of #22145.

**Closed by gkalpak** 2018-12-12 11:49 UTC
