### ISSUE TITLE
Using <!--googleoff: all--> <!--googleon: all--> in the html templates

### ISSUE THREAD

**Issue by kolkov** [angular/angular#45146] opened 2022-02-20 08:41 UTC
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

I try to add HTML comments for Google crawlers to my layout template, but Angular compiler strip all comments from HTML templates.
Is a way to prevent stripping this tags?
![image](https://user-images.githubusercontent.com/3740898/154835013-5046c2b8-1359-4507-828d-b0ff33adb786.png)
![image](https://user-images.githubusercontent.com/3740898/154835032-acbe74d9-10ba-4d1e-a855-e47d0893e454.png)

https://stackoverflow.com/questions/65118260/how-do-i-stop-angular-from-removing-html-comments

**Comment by pkozlowski-opensource** [comment] 2022-02-22 07:08
This is a duplicate of the existing issue #28814 - let's continue the discussion in there.

**Comment by pkozlowski-opensource** [comment] 2022-02-22 07:08
Duplicate of #28814

**Closed by pkozlowski-opensource** 2022-02-22 07:08 UTC
