### ISSUE TITLE
ng build run twice ? (angular 8.1.1)

### ISSUE THREAD

**Issue by callmeblessed** [angular/angular#31579] opened 2019-07-16 03:47 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....

Ng Build run twice ? 
is it normal ?

![angular-build-twice](https://user-images.githubusercontent.com/81192/61264405-af648e00-a7b6-11e9-83b7-de78696b22fe.png)

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....
just upgraded to v 8. v7 just compiled and build once.

### Description

 A clear and concise description of the problem...
I just make a build.bat and run it. build.bat contains 
ng b --prod --output-path ../crsappbuild/dest --base-href /

## 🔬 Minimal Reproduction

 https://stackblitz.com/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

</code>
Angular CLI: 8.1.1
Node: 10.13.0
OS: win32 x64
Angular: 8.1.0
... common, compiler, core, forms, language-service
... platform-browser, platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.801.1
@angular-devkit/build-angular     0.801.1
@angular-devkit/build-optimizer   0.801.1
@angular-devkit/build-webpack     0.801.1
@angular-devkit/core              8.1.1
@angular-devkit/schematics        8.1.1
@angular/animations               8.1.1
@angular/cdk                      7.3.7
@angular/cli                      8.1.1
@angular/compiler-cli             8.1.1
@angular/material                 7.3.7
@ngtools/webpack                  8.1.1
@schematics/angular               8.1.1
@schematics/update                0.801.1
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.35.2
</pre>

**Anything else relevant?**

**Comment by santoshyadav198613** [comment] 2019-07-16 03:51
This is a feature called differential loading.
Now we generate 2 bundles for es5 and es2015 respectively to serve smalled bundles on new browsers.

**Comment by gkalpak** [comment] 2019-07-16 06:22
Duplicate of angular/angular#30849.
Basically, it is intentional. See https://github.com/angular/angular/issues/30849#issuecomment-498715137 for more info.

**Closed by gkalpak** 2019-07-16 06:22 UTC

**Comment by callmeblessed** [comment] 2019-07-16 08:47
just knew this. 
should it be a text saying compiling for es5 and esxxxx while ng build prod so we are not freaking out about this ;) [our mistakes for not reading new features in angular 8]

**Comment by gkalpak** [comment] 2019-07-16 09:23
@callmeblessed, that sounds like a good idea. Can you create a [feature request for the cli][1]?

[1]: https://github.com/angular/angular-cli/issues/new

**Comment by petercunha** [comment] 2019-07-16 17:59
@gkalpak this should only be done for `ng build --prod` because it's a minor optimization that doubles the compile time for development.

Is there a command line flag we can use to disable this?

**Comment by gkalpak** [comment] 2019-07-17 15:18
This is not done for `ng serve` (which is what is most commonly used during development). Not sure about `ng build` without `--prod`. In any case, this discussion/request belongs to the [cli repo][1].

[1]: https://github.com/angular/angular-cli
