### ISSUE TITLE
Component private properties still accessible within template - v4.2.5

### ISSUE THREAD

**Issue by toniopelo** [angular/angular#17871] opened 2017-06-30 09:54 UTC
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[x] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Actually, I'm not sure if this is a bug or if I don't understand how it's supposed to work.
Since offcial release of the @angular/cli, the aot compilations errors are supposed to be reported correctly, so now the private component properties should not be accessed within the component template.
It does report some errors correctly BUT some private properties are still accessible in the template within ngFor/ngIf (not every time, I can't see the pattern) or ngModel or event into directives binding sometimes. I can’t reproduce with plunker because I think it’s only JiT compilation so there is no error issued.
I'm trying to figure out: What is the pattern ?

## Expected behavior
I don't really know. It should throw errors every times or maybe I just didn't understand well the machanism.

## Please tell us about your environment

<pre><code>
Angular version: 4.2.5

For Tooling issues:
- Node version: v8.1.3
- Platform: Linux
</code></pre>

**Comment by Foxandxss** [comment] 2017-07-03 11:31
with JIT, it should still work, now, if you run it on AOT it should fail.

**Comment by toniopelo** [comment] 2017-07-12 04:48
@Foxandxss Thanks for the answer.
That's what I thought, so I think this is a compiler bug then..
Or maybe @angular/cli still doesn't repport all the errors correctly?
I see this is labelled already, I assume you figured it out :)
Thanks for your time!

**Comment by trotyl** [comment] 2019-05-10 12:31
> It does report some errors correctly BUT some private properties are still accessible in the template within ngFor/ngIf 

Duplicate of https://github.com/angular/angular/issues/15801, this is general issue in type-checking `<ng-template>`, not specific to property accessor.

**Comment by pkozlowski-opensource** [comment] 2020-03-12 14:39
I believe that one is fixed, see https://github.com/angular/angular/issues/14739#issuecomment-597602255

**Closed by pkozlowski-opensource** 2020-03-12 14:39 UTC
Labels: comp: core, freq2: medium, severity3: broken, type: bug/fix
