### ISSUE TITLE
System.import does not load my js file, but try to load it from jspm.io and failed

### ISSUE THREAD

**Issue by wildtang** [angular/angular#3602] opened 2015-08-12 09:25 UTC
I'm following the 5 minutes Quick Start
https://angular.io/docs/js/latest/quickstart.html

But, I got the error below from Browser:
Failed to load resource: the server responded with a status of 404 (Not Found)
es6-module-loader@0.16.6.js:1 Potentially unhandled rejection [3] Error loading "appone" at https://registry.jspm.io/appone.js
Not Found: https://registry.jspm.io/appone.js (WARNING: non-Error used)

[file appone.html]
```
<!doctype html>

<html>
<head>
    <title>Angular 2 Quickstart</title>
    <script src="https://github.jspm.io/jmcriffey/bower-traceur-runtime@0.0.91/traceur-runtime.js"></script>
    <script src="https://jspm.io/system@0.16.js"></script>
    <script src="https://code.angularjs.org/2.0.0-alpha.34/angular2.js"></script>
</head>
<body>
    <!-- The app component created in appone.ts -->
    <my-app></my-app>

    <script>
        System.config({
        baseURL: '/app'
        });

        System.import('appone');
    </script>

</body>
</html>
```

[My Enviroment Information]
TypeScript 1.5.3
Browsers: IE 11 and Chrome 44 (Both has this problem)

**Comment by wildtang** [comment] 2015-08-12 09:31
I am use WebStorm, and the Command line setting for *.ts is:
--module commonjs --target ES6 --experimentalDecorators

**Comment by Zyzle** [comment] 2015-08-12 10:01
I noticed this too when attempting to use the angular2.js from code.angularjs.org.  Doesn't seem to happen when I use a local version of the script compiled from the alpha 34 tag though

**Comment by pkozlowski-opensource** [comment] 2015-08-12 10:07
@Zyzle @wildtang could one of you guys put together a plunk showing this? You can start with http://plnkr.co/edit/sAkqXkt5eubJs1ynPyWo?p=preview

**Comment by pkozlowski-opensource** [comment] 2015-08-12 10:09
@hat looks suspicious here is:

```
System.config({
        baseURL: '/app'
        });
```

**Comment by Zyzle** [comment] 2015-08-12 10:10
@pkozlowski-opensource I was editing that as you posted ;-) 

it seems to be an issue with an older version of system.js or traceur:

this plunkr works fine:

http://plnkr.co/edit/T2MxnEdRlCqkfU1jNqVm

this one shows the error above:

http://plnkr.co/edit/QKG3VVoCaCBY790i8JZD

only difference I can see is:

**Bad**
```
<script src="https://github.jspm.io/jmcriffey/bower-traceur-runtime@0.0.87/traceur-runtime.js"></script>
<script src="https://jspm.io/system@0.16.js"></script>
```

**Good**
```
<script src="http://cdn.rawgit.com/google/traceur-compiler/90da568c7aa8e53ea362db1fc211fbb4f65b5e94/bin/traceur-runtime.js"></script>
<script src="http://cdnjs.cloudflare.com/ajax/libs/systemjs/0.18.4/system.src.js"></script>
```

**Comment by wildtang** [comment] 2015-08-12 10:42
@pkozlowski-opensource 
Thanks for your response：）

I have upload codes to the the url below:
http://plnkr.co/edit/VQ1Zf0EeQNDQReATKIBR?p=preview

**Comment by pkozlowski-opensource** [comment] 2015-08-12 14:43
Hm, OK, @wildtang I got your plunk working by changing from src="https://code.angularjs.org/2.0.0-alpha.34/angular2.js to src="https://code.angularjs.org/2.0.0-alpha.34/angular2.dev.js see: http://plnkr.co/edit/PakUR2DrnY1tukHMolA4?p=preview

Not sure which difference makes SystemJS fail, more investigation is needed.

**Comment by pkozlowski-opensource** [comment] 2015-08-12 15:11
Hmm, switching to a newer version of SystemJS also fixes it, both for a dev and prod versions: http://plnkr.co/edit/f5jOPOwz5L0B5UtXOsOw?p=preview

**Comment by pkozlowski-opensource** [comment] 2015-08-12 15:13
I'm not sure what is going on with older SystemJS and prod version but we are planning to update to the latest SystemJS anyway: https://github.com/angular/angular/issues/3562

**Comment by wildtang** [comment] 2015-08-13 01:42
@pkozlowski-opensource Thanks!
Use the code below, it finally worked on the Chrome of my computer.
```
<!DOCTYPE html>
<html>

  <head>
    <!-- needed because angular bundle is traceur compiled -->
    <script src="https://github.jspm.io/jmcriffey/bower-traceur-runtime@0.0.91/traceur-runtime.js"></script>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/systemjs/0.18.4/system.src.js"></script>
    <script>
      System.config({
        defaultJSExtensions: true 
      });
    </script>
    <script src="https://code.angularjs.org/2.0.0-alpha.34/angular2.js"></script>
  </head>
 
  <body>
    <my-app></my-app>
    <script>
      System.import('appone');
    </script>
  </body>

</html>
 
```

But my IE 11 reported an exception
"SCRIPT5022: Expecting function got: [object FunctionWrapper]"

This exception was thrown from angular2.js Line:86

**Comment by pkozlowski-opensource** [comment] 2015-08-13 11:41
@wildtang glad that you've made it work! 

Your IE11-related problem looks like a duplicate of https://github.com/angular/zone.js/issues/150.

**Comment by wildtang** [comment] 2015-08-13 16:00
Yes, It was as @matthewjh said in that post:
On IE 11, it only occurs when the developer tools are opened.

**Comment by mhevery** [comment] 2015-08-20 03:10
Closing as the issue seems to be rosolved.

**Closed** 2015-08-24 18:32 UTC
Labels: state: Periodic Review
