### ISSUE TITLE
combine regular form with dynamic reactive form

### ISSUE THREAD

**Issue by infofromca** [angular/angular#13615] opened 2016-12-21 16:40 UTC
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
these are seperated

**Expected behavior**
become one

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**
it made confusion for my colleagues to refer them.  and it is strange to deal with the same element (form) in different places in the same core.

**Please tell us about your environment:**

* **Angular version:** 2.3

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment] 2016-12-21 22:39
Duplicate of https://github.com/angular/angular/issues/11531

**Comment by Toxicable** [comment] 2017-03-03 08:45
Can close since duplicate?

**Comment by jasonaden** [comment] 2017-12-19 23:45
Duplicate as above.

**Closed by jasonaden** 2017-12-19 23:45 UTC
Labels: comp: forms
