### ISSUE TITLE
Angular One-Time Binding

### ISSUE THREAD

**Issue by maxisacoder** [angular/angular#16777] opened 2017-05-15 03:23 UTC
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
We can use `ChangeDetectionStrategy`  `onPush` to set components to  `checkOnce`, but there is no way to set one `@Input` to `checkOnce` without changing others.

**Expected behavior**
Could we add a way to set one `@Input` to `checkOnce` without changing others?

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

There is no angularjs double colon expression equivalent in current angular version. It will be more convenient for the developer to have this feature in angular.

```
In a angularjs, when we declare a value such as `{{ ::foo }}` inside the DOM, once this value 

becomes defined, Angularjs will render it, unbind it from the watchers and thus reduce the 

volume of bindings inside the $digest loop. 
```
**Please tell us about your environment:**
null

* **Angular version:** 2.0.X
4.1.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

* **Node (for AoT issues):** `node --version` =   
7

**Comment by tytskyi** [comment] 2017-05-15 08:47
@CNaiko you can use smaller component with single `@Input` and `OnPush` strategy

**Comment by CNaiko** [comment] 2017-05-15 10:03
@tytskyi I met this issue when using Material 2 `mdInput`. It seems like very hard to put `@Input` to a smaller component.  (Eg. `placeholder` for this directive)

**Comment by tbosch** [comment] 2017-05-16 22:46
Adding a fine grained control makes it more complex to use and to explain.
We would need a very strong (performance) argument that using `OnPush` or using `ChangeDetectorRef.detach / attach` is not enough...

**Comment by pkozlowski-opensource** [comment] 2019-03-12 13:25
Duplicate of #14033

**Closed by pkozlowski-opensource** 2019-03-12 13:25 UTC
Labels: comp: core & compiler, state: Follow Up, type: feature
