### ISSUE TITLE
docs: missing link to sources on git.

### ISSUE THREAD

**Issue by SanderElias** [angular/angular#17627] opened 2017-06-20 09:17 UTC
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[ ] Bug report 
[ ] Feature request
[x ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
The links that were found in the 2.0 docs that point to the source on GitHub are not there anymore
talking about those:
![image](https://user-images.githubusercontent.com/1249083/27325654-6b84805c-55a9-11e7-9b77-f3a07d77408f.png)

## Expected behavior
Would like to get those links back. Sometimes it's easier to determine how something works from source!

## Minimal reproduction of the problem with instructions
[sample](https://v2.angular.io/docs/ts/latest/api/common/index/NgIf-directive.html) "old" docs: 
[sample](https://angular.io/api/common/NgIf) "new" docs: 

Other:
@petebacondarwin I was told to mention you in the issue ;)

**Comment by petebacondarwin** [comment] 2017-06-20 09:21
Yes, we completely agree. We temporarily removed them while we worked out the best positioning and style for the links (@igorminar).

**Comment by ocombe** [comment] 2017-06-20 09:45
duplicate of https://github.com/angular/angular/issues/17372 ?

**Comment by gkalpak** [comment] 2017-06-20 10:11
Yes, this is tracked in #17372. (We have some things and workflows to figure out first, but it is on my todo list for the next couple of days.)

**Closed** 2017-06-20 10:11 UTC
Labels: comp: aio
