### ISSUE TITLE
The path from Angular CLI Overview section, to Command Reference is broken

### ISSUE THREAD

**Issue by arturlicks** [angular/angular#53933] opened 2024-01-16 03:24 UTC
### Describe the problem that you experienced

Browsing the docs in angular.dev in the section https://angular.dev/tools/cli, in the overview going into Command Reference, the page is not found.

### Enter the URL of the topic with the problem

https://angular.dev/cli/commands

### Describe what you were looking for in the documentation

Command Reference for Angular CLI

### Describe the actions that led you to experience the problem

Open the URL and click on **Command Reference** it will lead to a Page Not found error

### Add a screenshot if that helps illustrate the problem

![Screen Shot 2024-01-15 at 23 23 32](https://github.com/angular/angular/assets/23739769/bd5fbab2-b73a-49ca-8959-277d44911bac)

**Comment by JoostK** [comment] 2024-01-16 08:48
Thanks for the report, closing as duplicate of https://github.com/angular/angular/issues/52549 for which the fix is pending deployment.

**Closed by JoostK** 2024-01-16 08:48 UTC
