### ISSUE TITLE
Guards and Resolvers are not called when queryParams changes(ActivatedRouteSnapshot.url empty in  equalParamsAndUrlSegments)

### ISSUE THREAD

**Issue by montella1507** [angular/angular#13244] opened 2016-12-05 18:54 UTC
Hi, 

i have serious problem with Routing. 

In this commit:
https://github.com/angular/angular/commit/fe47e6b#diff-593b97ea7059dbf0d0030ac323889498R454

The behavior of resolvers / guards was changed to respect NOT ONLY params. I did hope it would fix my problem with query params from v. 2.0.0. Unfortunately, the url in function is empty array for both of snapshots. 

My route has path: 'employee-detail' and it works with query params for links:

A)   .../employee-detail?id=4
B)  .../employee-detail?id=151

Unfortunately, the resolvers and guards are not called, when i change with navigateByUrl from route
A to B, because route segments (URLs) are empty arrays so they are actually the same.

**Comment by vicb** [comment] 2016-12-05 23:16
Please add a repro in a plunker

**Comment by montella1507** [comment] 2016-12-06 12:29
https://plnkr.co/edit/LOJWgfDGvtKQzhxuD8Wa?p=preview

Here.

**Comment by DzmitryShylovich** [comment] 2016-12-06 12:37
> Route has not been changed by router = no navigation happens. = no resolve, no route guards called again = useless.

https://angular.io/docs/ts/latest/guide/router.html#!#reuse

**Comment by montella1507** [comment] 2016-12-06 12:41
I think this is bad approach. Resolvers, and route guards exist because you want 

A) Protect a route - for example you wanna protect to navigate to Editation of some item = route GUARDS have to be called and checked before the navigation and NOT in component 

B) Resolve the data before the navigation happens - like in angular 1

So usage of observable params and resolving the data in component (or checking the access rights) is not good or usable.

**Comment by montella1507** [comment] 2016-12-06 12:54
If you wanna do that in your way, then the resolvers and route guards and ALMOST everything in route is not far from being useless.. 

Because in most scenarios it depends on route params / query params, route data...

So if there is not a way how to re-run guards, resolvers, "can deactivators",... for every change of param, it is not usable. 

Example how it should logically behave:

/goods?id=5
1) Check if user has access to goods with id=5 -> yes/no (redirect, or popup, or something)
2) Resolve data for goods with id=5 - (you can show overlay with usage of Router events navigation start / end)
3) Navigate 
NAVIGATE to /goods?id=6  (different URL)

4) Check if user has access to goods with id=6 -> yes/no (redirect, or popup, or something)
5) Resolve data for goods with id=6 - (you can show overlay with usage of Router events navigation start / end)
6) Navigate 

= i have got what did u want to make with observable route params and so on..  
But resolvers and route guards should be run everytime when URL has been changed

**Comment by montella1507** [comment] 2016-12-06 13:10
I HAVE UPDATED PLUNKER TO SHOW THE CORRECT PROBLEM:
https://plnkr.co/edit/LOJWgfDGvtKQzhxuD8Wa?p=preview

= query params have been changed correctly, but resolver has not been called.. That is what this issue is about.

**Comment by montella1507** [comment] 2016-12-07 10:13
https://plnkr.co/edit/f0ecdrMBUGCG8jkxp14f?p=preview

it works correctly for params, resolvers/guard are runed everytime params change.. so  it is only bug with missing shallowEqual of query params.

**Comment by DzmitryShylovich** [comment] 2016-12-07 10:16
It's not a bug. It's intentional. You can see it in the docs https://github.com/angular/angular/issues/13244#issuecomment-265139838

**Comment by DzmitryShylovich** [comment] 2016-12-07 10:18
https://github.com/angular/angular/issues/9811#issuecomment-264627620

**Comment by montella1507** [comment] 2016-12-07 13:39
Great!! You win. So go to google and tell them, if you put:

https://www.google.cz/#safe=off&q=car
and 
https://www.google.cz/#safe=off&q=boat

in the browser, you should get the same result, becase they RESOLVED their data before the routing happend. The same thing, the Resolvers were implemented for. 

If it is by design, then enjoy your design. But our views of "logic" is strictly different so we will switch to react. 

Thanks for your answer.

**Comment by DzmitryShylovich** [comment] 2016-12-07 13:46
good luck

**Comment by olegdunkan** [comment] 2016-12-10 21:15
@montella1507 angular router gets you great way to utilize params in all ways. You can embed params in utr (route path), you can use matrix notation implementing your query **for each component and resolver, guard**, flexibility of the angular 2 router is awesome.

I advise you to look closer at angular router. In angular url is not a path to one leaf like we suppose for first time. In angular router url can present a tree (when we use outlets). And each node of that tree can be a component, or query for data via resolvers and each of that can have any params. And it is good and consistent logic to update node's owner (resolver or <and> component, or guard) when its params are changed. We can't relate last `query string ?x=1&y=1` you talking about to any of the owners of the node of the tree. You suggest that if query params are changed we have to update all the tree. It is not good point. The good point is when params that belongs to specific node in tree are changed then update specific node's owners (resolvers, components or guards).

**Comment by klinki** [comment] 2016-12-12 08:08
@olegdunkan As you pointed out, 

> We can't relate last query string ?x=1&y=1 you talking about to any of the owners of the node of the tree. 

so in that case, if we cannot relate query string into any node of tree, IMHO it would be good idea to update all nodes in tree. We don't know for which node those information are relevant to. But we can assume there is at least one node, which will use them. If we update all of them, then the one which needs these information will use them, and the remaining nodes will ignore it. But if we don't update any node, we miss important information in node which needs them.

**Comment by montella1507** [comment] 2016-12-12 11:54
Im afraid i dont have any energy to convince you... 

In EVERY OF YOUR tutorial in angular.io and blogs of your colleagues Like here (http://blog.thoughtram.io/angular/2016/10/10/resolving-route-data-in-angular-2.html) the Resolver will PRELOAD data for CONCRETE parameter.  for concrete Detail (by his ID). 

So the only one difference between 
/edit/5 
/edit/6 

where the guards and resolvers are called again correctly with every change.. and:
/edit?id=5
/edit?id=6

Is only about "semantic URL". If You DONT believe me, check it on the WIKI:
https://en.wikipedia.org/wiki/Semantic_URL

Where:
http://example.com/profiles?id=193	
has the same meaning like:
http://example.com/profiles/193

So if the router will call Resolvers and Guards again for 
/edit/2 
/edit/3

it should call Resolvers and Guards for
/edit?id=2
/edit?id=3
as well.

**Comment by olegdunkan** [comment] 2016-12-12 13:00
@klinki yes, we can update all nodes of the tree only for that case and maybe that strategy will be implemented. But the question is why do we use sophisticated router in simply cases like `edit/?id=1`?Angular team made us the router for spa applications and we try to treat it in old fashion IMHO. 
One more time, angular router gets us flexible methods to update only that part or parts of tree that we concerned in, while changing a router state. But we try to use it in a way that all I have said is nothing. 
But of course If implementing that strategy will be cost nothing in performance then it is ok)))

**Comment by klinki** [comment] 2016-12-12 13:57
@olegdunkan I'm sorry, but I don't think Angular Router is as flexible as you think. There are quite a lot of issues with it. 

I think the biggest issue is, it hasn't been designed as universal, as we assume. But unfortunately we don't know for which use cases it has been designed. And here comes the problem. Router documentation is absolutely not sufficient. I think it would be really great if Angular team explained us design of the Router and use cases for which it has been created.

**Comment by robwormald** [comment] 2016-12-12 16:26
@montella1507 your attitude in this thread is unacceptable, and throwing around words like "useless" and "terrible idea" will win you no support from the core team for your ideas. Please keep your comments constructive per our [Code of Conduct](https://github.com/angular/code-of-conduct/blob/master/CODE_OF_CONDUCT.md)

@olegdunkan is absolutely correct that query params are *global* - they are not associated with any specific segment of the URL, and so implementing this behavior would necessarily require re-running every resolver in a deeply nested routing tree. This behavior is generally undesired.

Your simple example of `/goods?id=6` is fine, but the same basic idea does not follow in a nested structure like `/sections/admin/vendor/acmecorp/goods?id=6` - retraversing the entire tree could become significantly more expensive. 

That said, I monkey patched the modules to give this a go - see https://plnkr.co/edit/Qv5C3IyUIGpbX8dizDWZ?p=preview

It would be reasonably straightforward to implement this check via an injectable service, like we do for many of the other portions of the router (ReuseStrategy, UrlSerializer, etc), which would let a user provide their own implementation. This would have to be done in a way that did not break the existing behavior of the API, so it would be up to an end user to implement their own check, leaving the default behavior intact.

If you'd like to put together a PR, we'd be happy to review it. There's no guarantee that such a feature would be merged, but if it can be done in a non-invasive or breaking way, it would probably be OK.

**Comment by olegdunkan** [comment] 2016-12-12 16:58
@robwormald 
> Your simple example of /goods?id=6 is fine, but the same basic idea does not follow in a nested structure like /sections/admin/vendor/acmecorp/goods?id=6 - retraversing the entire tree could become significantly more expensive.

That is I am trying to say in this thread. I absolutely agree with that. When I used `edit/?id=1` I considered example from above message. It was question to folks (
rhetorical). 
More then this I can provide example where this strategy will be destructive.

Let say we have the route `building\:office`
and we use query string like that  `?absent=yes`
we type in browser `building\first`, browser will render `building` component and summary of a `first` office using `office` component, then we change url to `building\first?absent=yes`, all we want is to update `office` component(summary of absent workers) but if the strategy would be implemented that we suffer from re-rendering `building` component. 
Therefore if we suppose that `params` and `global query` are coupled then we lose in performance.
In angular router I consider global params as a slice (additional dimension) for main dimensions (params).

**Comment by robwormald** [comment] 2016-12-12 17:28
@olegdunkan i know, i'm agreeing with you :)

**Comment by chpasha** [comment] 2016-12-16 15:04
I'm sorry guys, but I don't get it either. Yes I do understand that there are some performance penalties but...if resolvers are not run when query params change, they are difficult to use for any routes that need query params, because they run first time (having some logic that reads those params and translates them to some rest calls) and then after changing let's say dateFrom and dateTo I have to run the very same logic again in the component itself because the resolvers are not run any more. So why bother then with having resolvers and not subscribing to params changes in component itself? I was very excited learning resolvers concept but unfortunately after figuring out that they run only once, I had to retreat to the old school component approach. Maybe it is possible to somehow customize such behaviour so we can have a choice how to react to url changes?

**Comment by DzmitryShylovich** [comment] 2016-12-16 15:11
@chpasha u can implement custom reuse strategy https://github.com/angular/angular/issues/13244#issuecomment-265409375

**Comment by chpasha** [comment] 2016-12-16 15:27
I'm not sure I understand how it solves the problem. I'm not leaving the route but rather re-navigate to the same component with different query params, so the component is not destroyed and re-created again. Its the same like having some /route/:id but the difference is that with /route/5 I do have the resolver/canLoad/canActivate machinery running again and with /route?id=x not.

**Comment by olegdunkan** [comment] 2016-12-16 16:31
@chpasha resolvers are executed every time you change matrix params, you can use matrix params for your needs

**Comment by chpasha** [comment] 2016-12-17 17:19
hmm...not a bad idea, thanks. I'll check if I can switch to use them

**Comment by chpasha** [comment] 2016-12-17 19:16
the direction is good, but still no luck because of this https://github.com/angular/angular/issues/10252

**Comment by DzmitryShylovich** [comment] 2017-03-10 09:40
@montella1507 fixed by https://github.com/angular/angular/pull/14567
close the issue please. thanks

**Closed** 2017-03-13 17:02 UTC
Labels: comp: router, type: bug

**Comment by montella1507** [comment] 2017-03-13 17:05
@DzmitryShylovich  so that "by design" behavior has been changed to respect changed query params, right = all guards and resolvers are called again when qparams are changed. Is that correct, Dzmitry?

**Comment by DzmitryShylovich** [comment] 2017-03-13 17:11
@montella1507 it's configurable for every route. You can find an example [here](https://github.com/angular/angular/pull/14567/files#diff-f48b128ef12ddeb072207e5ba88d04eeR1585)
This feature is only available in ng4

**Comment by montella1507** [comment] 2017-03-13 18:06
Ok thank you very much.
