### ISSUE TITLE
Paste output is not triggered when input is not empty (at least in Firefox)

### ISSUE THREAD

**Issue by martin-yumsto** [angular/angular#54701] opened 2024-03-05 10:55 UTC
### Which @angular/* package(s) are the source of the bug?

common, core

### Is this a regression?

Yes

### Description

`(paste)` output on the input element is not triggered if there is already a content inside the element. It seems it works fine if you paste by right clicking and selecting paste from context menu. It doesn't work when using keyboard shortcuts - ctrl/cmd + v

A great folk named Frederik, prepared this small sandbox with pure js: https://jsfiddle.net/zuxwqakg/ and this one with minimal Angular to reproduce: https://stackblitz.com/edit/stackblitz-starters-sz8ifv 

You can see pure js works perfectly fine, but Angular one works in Chrome, but not (at least) in the Firefox

Steps to reproduce:
- copy something in clipboard
- paste it inside an empty input -> it triggers `paste` function
- paste it again in the same input -> it's appended but `paste` function is not triggered

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-sz8ifv 

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.2.0
Node: 20.10.0
Package Manager: pnpm 8.14.1
OS: darwin arm64

Angular: 17.2.1
... animations, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1702.0 (cli-only)
@angular-devkit/build-angular   17.2.0
@angular-devkit/core            17.2.0 (cli-only)
@angular-devkit/schematics      17.2.0 (cli-only)
@angular/cdk                    17.2.0
@angular/cli                    17.2.0
@angular/ssr                    17.2.0
@schematics/angular             17.2.0 (cli-only)
rxjs                            7.5.7
typescript                      5.3.3
zone.js                         0.14.3
```

### Anything else?

Firefox details:
Name     Firefox
Version     123.0
Build ID     20240213221259

**Comment by alxhub** [comment] 2024-03-05 18:32
I cannot reproduce this in Firefox 123.0.1 with the given StackBlitz. The paste log triggers every time. (note that the Firefox dev console deduplicates logging statements)

**Comment by martin-yumsto** [comment] 2024-03-05 20:20
@alxhub what platform did you try it on? I remember, there was another guy with Mac saying he was able to reproduce it. As well as different dev with linux saying it's not reproducible for them.

**Comment by alxhub** [comment] 2024-03-05 21:43
I'm on Mac, using the latest Firefox.

**Comment by pkozlowski-opensource** [comment] 2024-03-06 08:02
Also one should verify if a problematic browser is not running any extensions that could interfere.

**Comment by Totati** [comment] 2024-03-06 08:52
I could not reproduce it on Windows 10, Firefox 123.0.1

**Comment by alxhub** [comment] 2024-03-22 19:07
Closing as a few of us have tried and we've been unable to reproduce the issue. Feel free to reopen the issue if a reproduction can be narrowed down.

**Closed by alxhub** 2024-03-22 19:07 UTC
Labels: needs reproduction, area: core
