### ISSUE TITLE
[beta.16 regression] ngFor + ChangeDetectionStrategy.OnPush = event handler not working

### ISSUE THREAD

**Issue by pkozlowski-opensource** [angular/angular#8242] opened 2016-04-26 12:36 UTC
**Steps to reproduce and a minimal demo of the problem**

http://plnkr.co/edit/hDagJbhXpwI8213PmCva?p=preview

Click on a page number (1..10) and observe that a highlighted page doesn't change

**Expected/desired behavior**

Click on a page number (1..10) should change active page.

**Other information**

* used to work in beta.15
* observe that clicking on prev / next _changes_ an active page
* the only difference between page no links and prev / next links is that page no links are generated using ngFor
* problem doesn't show up if we remove `changeDetection: ChangeDetectionStrategy.OnPush,`
* switching dev / prod mode doesn't make any difference

**Comment by mdudek** [comment] 2016-04-26 19:23
I also have found issues with Beta 16 related to ChangeDetectionStrategy.OnPush. I'm using this strategy in my app and it seems that it's buggy in B16.

**Comment by r-park** [comment] 2016-04-27 01:56
Some additional examples using observables:

- [beta.15 - with ngFor, with OnPush](http://plnkr.co/edit/RNBHHZs3e81oOZOJ1XQb) (works)
- [beta.16 - with ngFor, with OnPush](http://plnkr.co/edit/rqr1GoF1vZl3lgXzxlTL) (broken)
- [beta.16 - no ngFor, with OnPush](http://plnkr.co/edit/jIbXSeZ9ya7KWm9ztIYX)  (works)
- [beta.16 - with ngFor, no OnPush on parent components](http://plnkr.co/edit/k0qldKaA1zvqzU9Xx42O) (works)

**Comment by radoslavpetranov** [comment] 2016-04-27 08:15
I noticed this as well but I was wondering if this is indeed a regression or a fix for incorrect previous behavior. The idea of the OnPush strategy is for you to manually control when to update your UI, right? In that case shouldn't you be responsible for requesting an update like so:

http://plnkr.co/edit/jXEEiehtcxoKHAdMc2x7?p=preview

I wasn't sure about this myself but I think this is indeed a fix from the previously incorrect behavior.

**Comment by pkozlowski-opensource** [comment] 2016-04-27 08:23
> I noticed this as well but I was wondering if this is indeed a regression or a fix for incorrect previous behavior.

Well, if this is a desired behavior than it should behave consistently regardless of the ngFor usage. 

> The idea of the OnPush strategy is for you to manually control when to update your UI, right?

Nope, this is not my understanding. With OnPush used a component should be dirty checked when:
* its input changes
* an event is fired

**Comment by radoslavpetranov** [comment] 2016-04-27 08:24
Both good points - I forecast a beta17 in the not so distant future :)

**Comment by mdudek** [comment] 2016-04-27 08:28
I think you are right @radoslavpetranov. Your fix is correct from my point of view how OnPush strategy should work. But, with Beta 16, I'm facing situation when calling changeDetectorRef.markForCheck() does not update the view. The plain example works, but it stopped working in my app in some components. It would be great to know, what was changed in change detection mechanism (if it's desired behavior and not a bug).

**Comment by born2net** [comment] 2016-04-27 20:54
For what it's worth my entire application is broken in 0.16. I use heavily on onPush detection and nothing it updating even when my underline redux store changes... To me 0.16 is an unusable build, I hope the team is aware of this.

**Comment by schippie** [comment] 2016-04-28 11:46
I am also experiencing problems related to changeDetection OnPush when it comes to updates triggering within my async pipes. Though it seems really inconsistent as i cannot easily reproduce it using a plunkr https://plnkr.co/edit/sIWJdCs00zhK3mw1FY5

My situation i have multiple async pipes who all work but just one who fails horribly. And does not up date while the value is changed (i debugged through the async pipe) and the ` latestValue` is updated with the correct one this is only never reflected after the digest cycle that happens.

**Comment by born2net** [comment] 2016-04-28 22:53
was this fixed in 0.17?

**Comment by schippie** [comment] 2016-04-28 23:38
@born2net  Changelog / commits do not indicate this issue has been worked on for the beta 17 release so I am guessing no. Went back actually looking through the commits between beta 15 and 16 but its not really clear to me which of those could have changed the ChangeDetection system.

**Closed** 2016-04-30 02:49 UTC
