### ISSUE TITLE
click events propagation's problem with buttons wrapped into <label> 

### ISSUE THREAD

**Issue by ottopic** [angular/angular#53824] opened 2024-01-08 00:21 UTC
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

I have to preface this by saying that I am not an expert in Angular, but the problem is strange even for the most experienced.
In the linked example clicking "edit" changes the UI but clicking the buttons in the new UI triggers me back to the edit function after the others. You can tell by the alerts that are shown
Everything is solved by removing the <label> container or adding new <input> field inside the @ if .

Surely it could be an html error to initially have a <label> without an input field, but the fact is that there are no warnings or errors but still this behavior seems strange to me.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/ya5w29-cn45qg?file=src%2Fapp%2Fapp.component.ts

### Please provide the exception or error you saw

```true
No error / exception
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.0.9
Node: 18.18.0
Package Manager: npm 10.2.5
OS: darwin x64

Angular: 17.0.8
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.9
@angular-devkit/build-angular   17.0.9
@angular-devkit/core            17.0.9
@angular-devkit/schematics      17.0.9
@angular/cdk                    17.0.4
@angular/cli                    17.0.9
@schematics/angular             17.0.9
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.2
```

**Comment by JeanMeche** [comment] 2024-01-08 01:02
Interesting ! 

I'm noting :
* `event.preventDefault()` does prevent the issue when called in `confirmHandler()`. 
* Going zoneless and call `detectChanges()` does not fix the issue.
* If `detectChanges` isn't called in `confirmHandler()`, the issue doesn't occur : the edit button being rendered plays a part here. 

It definitly looks like an HTML relatedissue.

**Comment by maequise** [comment] 2024-01-08 05:10
I agree with @JeanMeche , the construction of the HTML is a bit strange. 
Normal code should be something like this : 
`<label for="input_id" >my label</label>> 
<input id="input_id" type="text" name="my_input" />`

Referring to the [MDN documentation - label](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label#interactive_content), what is actually did with the HTML code is not compliant and could lead to issues, or accessibility problems.

**Comment by ottopic** [comment] 2024-01-08 08:47
@maequise thanks for your reply but If you look [Accessibility Concerns ](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label) input into label is normal and allowed. 
In any case, in my opinion, good practices and accessibility should not be confused with the fact that the whole application "crashes" by doing this. In fact only now did I notice that the rest of the app also suffers from reactivity problems after issue.
It is as if the <label> captures the event of the edit button and that then remains even when we click on the others.
In my opinion this malfunction is abnormal

**Comment by JeanMeche** [comment] 2024-01-08 08:51
> Don't place interactive elements such as [anchors](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a) or [buttons](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button) inside a label. Doing so makes it difficult for people to activate the form input associated with the label.

I think the text is pretty clear. This is **not** recommanded.

**Comment by ottopic** [comment] 2024-01-08 08:55
Yes it is, but it is accessibility concerns it is not technical prohibition. In fact documentation immediately shows the best practice to use the input inside label.

**Comment by JeanMeche** [comment] 2024-01-08 09:10
Please have a look at this pure JS repro : https://stackblitz.com/edit/typescript-vint5d?file=index.html,index.ts

**Comment by JeanMeche** [comment] 2024-01-10 16:16
I'll close it for 2 reasons : 

* Button in labels are not recommended
* Since this is reproducible with bare js, this isn't an Angular issue but more likely a browser issue.

**Closed by JeanMeche** 2024-01-10 16:16 UTC
Labels: area: core

**Comment by JoostK** [comment] 2024-01-10 16:38
I was playing with this more to see if it reproduces in Safari, which it does, so sharing some more findings:

the `cancel`/`confirm` click event for the button is handled, resulting in a rerender of the template. The `edit` button reappears as edit mode was ended. Then, the `label` processes the event as it's associated with the button, but it re-initiates the event likely because it determines that the event's target is not its associated button (as the associated button has since been replaced with the `edit` button during the rerender). Hence, a new event is triggered on the `edit` button, immediately entering edit mode again. The toggling happens without paint operation so is invisible to users.

You can avoid this by using `event.preventDefault()` to stop the label's default processing of the event.
