### ISSUE TITLE
Custom pipe not found when saving only certain files in dev mode.

### ISSUE THREAD

**Issue by elliotwesoff** [angular/angular#41463] opened 2021-04-06 02:07 UTC
# 🐞 bug report

### Affected Package

I believe the issue is coming from @angular-devkit/build-angular, but I'm not sure.

### Is this a regression?

Unsure, this is my first time using Angular since v8.x.x.

### Description
I am defining a custom pipe in my app, and then importing it into a component via dependency injection. When running `ng serve` and loading the app in the browser, everything initially works fine. If I edit some code in user.component.ts, the page will refresh as expected, and continue to work normally. However, if I press ctrl+s on the items-count.pipe.ts file or the user.model.ts file, the page will refresh as expected, and then crash and throw the provided error. While reproducing the error, I've actually figured out that the issue disappears when changing the export definition of the pipe from:

`export default class ItemsCountPipe ...`

to:

`export class ItemsCountPipe ...`

and then modifying the import statements in the relevant files from:

`import ItemsCountPipe from ...`

to:

`import { ItemsCountPipe } from ...`

## 🔬 Minimal Reproduction
https://github.com/elliotwesoff/angular-pipe-import-bug

## 🔥 Exception or Error
<pre><code>
core.js:6162 ERROR ReferenceError: ItemsCountPipe is not defined
    at NodeInjectorFactory.UserComponent_Factory [as factory] (user.component.ts:3)
    at getNodeInjectable (core.js:3548)
    at instantiateAllDirectives (core.js:10227)
    at createDirectivesInstances (core.js:9576)
    at ɵɵelementStart (core.js:14778)
    at Module.ɵɵelement (core.js:14829)
    at AppComponent_Template (app.component.html:2)
    at executeTemplate (core.js:9549)
    at renderView (core.js:9356)
    at renderComponent (core.js:10631)

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 11.2.7
Node: 14.10.1
OS: win32 x64

Angular: 11.2.8
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.7
@angular-devkit/build-angular   0.1102.7
@angular-devkit/core            11.2.7
@angular-devkit/schematics      11.2.7
@angular/cli                    11.2.7
@schematics/angular             11.2.7
@schematics/update              0.1102.7
rxjs                            6.6.7
typescript                      4.1.5

</code></pre>

**Anything else relevant?**

It may also be helpful to note that I'm running `ng serve` inside my integrated VSCode powershell terminal. You should be able to clone my linked repo, do `npm i` and see the issue right away. Please let me know if you need any more details from me.

**Comment by RA80533** [comment] 2021-04-06 02:27
You had the right idea to change the `import`/`export` pattern. While it does sound like the behavior you encountered is indicative of a bug somewhere, start adopting the named `import`/`export` pattern in the code you write. Aside from the technical benefits it might bring, it’s the pattern that Angular uses in its code.

**Comment by JoostK** [comment] 2021-04-06 07:57
Thanks for reporting. This is a duplicate of #41377 so I'll close this one.

**Closed by JoostK** 2021-04-06 07:57 UTC

**Comment by elliotwesoff** [comment] 2021-04-06 19:25
@RA80533 could you please explain why the named pattern is preferable over the default pattern? What are the technical benefits it might bring?

**Comment by RA80533** [comment] 2021-04-07 13:52
There's quite a bit of nuance with how TypeScript handles non-ECMAScript modules (e.g., React, the built-in Node.js modules, etc.) to the point that additional complexity may arise depending on how TypeScript is configured (see [`allowSyntheticDefaultImports `](https://www.typescriptlang.org/tsconfig#allowSyntheticDefaultImports) and [`esModuleInterop`](https://www.typescriptlang.org/tsconfig#esModuleInterop)).
