### ISSUE TITLE
bigint: Failed to load bindings, pure JS will be used (try npm run rebuild?)

### ISSUE THREAD

**Issue by Jacky-Young1123** [angular/angular#56266] opened 2024-06-05 02:59 UTC
### Describe the problem that you experienced

When using the SSR (Server-Side Rendering) service in Angular version 17, the project exhibits a warning. After refreshing the page, an error is thrown and the CMD (Command Prompt) terminates execution.

### Add a screenshot if that helps illustrate the problem

![image](https://github.com/angular/angular/assets/171530490/20eb1562-4951-437a-9a11-5b2e3ffa9b17)

**Comment by JeanMeche** [comment] 2024-06-05 07:33
Duplicate of angular/angular-cli#27777

**Closed by JeanMeche** 2024-06-05 07:33 UTC
