### ISSUE TITLE
aio: Search issues

### ISSUE THREAD

**Issue by DeborahK** [angular/angular#17889] opened 2017-06-30 20:19 UTC
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[x] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Searching does not work as expected.

Searched: "routing" and all it found was the style guide.

Searched: "base tag" and it seemed to find every occurrence of "base" instead of locating the discussion of the base href.

Searched: "template reference variable" and it seemed to find every occurrence of "template". Trying putting the value in quotes and then it found nothing.

## Expected behavior

Expect the search results to list appropriate topics, especially when using common key words such as "routing".

Expect the search results to handle multi-word searches.

## Minimal reproduction of the problem with instructions
Type in any of the aforementioned search strings.

## What is the motivation / use case for changing the behavior?
It is important to provide assistance to our customers via our documentation. And many of those customers will first experience our documentation using the search feature.

## Please tell us about your environment

<pre><code>
Angular version: X.Y.Z
n/a

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX 
- Platform: 

Others:

</code></pre>

**Comment by jasonaden** [comment] 2017-07-10 18:33
@petebacondarwin This one seems pretty bad actually. I was just going to file a bug as well, but it looks like it's a duplicate of this one.

Try searching for "Resolve", for instance. You will not get the Resolve page, but if you drop the last character and search for "Resolv", you will find what you're looking for.

It appears to be some sort of bug with stemming. Anything ending in e, y, ies, etc. can't be found with suffixes. So you can find "Comonent" or "ComponentRef", but not "ComponentFactory" or "AbstractControlDirective" without dropping the last few characters.

**Comment by gkalpak** [comment] 2017-07-10 19:02
#17574 will improve things considerably :smiley:

**Comment by petebacondarwin** [comment] 2017-07-11 14:10
@jasonaden See https://pr17574-6d8fe54.ngbuilds.io/?search=Resolve

**Closed by petebacondarwin** 2017-07-11 14:10 UTC
Labels: comp: aio
