### ISSUE TITLE
[FEATURE] callback pipe to help make logic in template more performant

### ISSUE THREAD

**Issue by nayfin** [angular/angular#26089] opened 2018-09-24 19:42 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

NA

## Expected behavior

A pipe would expect a callback function as the first argument, then run that function on the value
e.g. 
### component
```javascript
@Component(...)
export class SomeComponent {
    addWorld(value) {
        return value + ' world';
    }
}
```
### template
`{{ 'hello' | callback : addWorld }}`

## Minimal reproduction of the problem with instructions

Super duper easy to implement. I am happy to add if approved.
```javascript
import { Pipe, PipeTransform } from '@angular/core';

/**
 * pipe allows clean component specific transformation of value without having to create a seperate pipe
 * for each set of transformation logic to improve performance. also useful for when same logic needed in template and component.ts
 * @param value the value to transform
 * @param callback the transformation function to run on value
 * @example
 * // if we were to run this callback directly in the template performance would suffer. YAY pipes!!!
 * {{ 'hello' | callback : (value) => value + ' world' }}
 */
@Pipe({
  name: 'callback'
})
export class CallbackPipe implements PipeTransform {

  transform(value: any, callback: (val: any) => {} ): any {
    return callback(value);
  }

}
```

## What is the motivation / use case for changing the behavior?

Get the performance benefits of pipes while allowing user to make use of component logic. Which would mitigate the duplication of code across component and pipe when logic is needed in both the template and component.ts file.

This could be taught as best practice to help new users avoid putting logic directly in template e.g. 
### template
`{{addWorld('hello')}}`

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by manklu** [comment] 2018-09-24 21:31
Your pipe breaks if the callback tries to access component attributes.

https://stackblitz.com/edit/angular-vmueum?file=src%2Fapp%2Fapp.component.html

**Comment by nayfin** [comment] 2018-09-24 22:04
@manklu the template was empty in your stackblitz demo. This pipe is designed to transform values not augment component  attribute, maybe I am misunderstanding your usage though. It can easily be used in a structural directive as demonstrated [here](https://stackblitz.com/edit/angular-ucdjeq?file=src%2Fapp%2Fapp.component.html). Can you try another demo of what broke please? 

@kara If this is something that you would consider useful I will start the PR tonight. I would be super excited to get code into `@angular/core` but I don't want to waste time if the team doesn't want it. I have found it very helpful in my projects. Thanks!!!

**Comment by mlc-mlapis** [comment] 2018-09-24 22:36
... very close to:
```
import { Pipe, PipeTransform } from '@angular/core';
@Pipe({
	name: 'fn',
	pure: true
})
export class FnPipe implements PipeTransform {

	// A template syntax: {{ templateValue | fn:componentMethodRef:fnArgument }}
	// ... should be transformed to: null.componentMethodRef(templateValue, fnArgument)
	transform(
		templateValue: any,
		fnReference: Function,
		...fnArguments: Array<any>
	): any {

		fnArguments.unshift(templateValue);

		// The function reference will NOT BE INVOKED IN THE COMPONENT CONTEXT.
		// This means that the function reference won't have a "this" context
		// during execution, unless the function is pre-bound to the component.
		return(fnReference.apply(null, fnArguments));
	}
}
```
... and we discussed the theme recently starting from here: https://gitter.im/angular/angular?at=5ba1148c1ee2ca650234db94

**Comment by nayfin** [comment] 2018-09-24 23:55
@mlc-mlapis yes the goals and implementation are similar. I had used a config object in place of an arguments array. I got the idea from end of this [article](https://codeburst.io/angular-bad-practices-eab0e594ce92#389b) and kept abstracting until I had the callback pipe. Have you started a PR or any other work towards getting this into `@angular/core`? I want to get this in as soon as possible and clean it out of my library.

**Comment by mlc-mlapis** [comment] 2018-09-25 06:14
@nayfin ... till now we only discussed it. No PR yet. But it's evident that there is an unused potential of pipes for such cases ... generally `computed properties` ... or introducing `@Pure` decorator directly.

**Comment by ericmartinezr** [comment] 2018-09-25 11:49
Wouldn't this also be _partially_ solved by https://github.com/angular/angular/issues/25976 ?

**Comment by pkozlowski-opensource** [comment] 2019-02-10 14:53
I think that this is duplicate of #25976 (maybe not in the proposed impl details, but in the need to address). Let's move the discussion to #25976 (I've just provided some input in there).

**Closed by pkozlowski-opensource** 2019-02-10 14:53 UTC
Labels: comp: common
