### ISSUE TITLE
Angular library test code-coverage flag debugging problem

### ISSUE THREAD

**Issue by mertyilmazx** [angular/angular#41035] opened 2021-03-01 07:44 UTC
Dear contributers,

We are using Angular 11. And we have angular libraries.
When we use code coverage flag on the library tests, we cannot add breakpoint to correct lines.
If we removes this flag, we can debug.

**Comment by alan-agius4** [comment] 2021-03-01 07:51
Duplicate of https://github.com/angular/angular-cli/issues/19084

**Closed by alan-agius4** 2021-03-01 07:51 UTC
