### ISSUE TITLE
UpgradeModule $rootScope.$digest error even though we are not triggering a digest manually.

### ISSUE THREAD

**Issue by andrewl-telnyx** [angular/angular#19426] opened 2017-09-26 23:12 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

This issue relates to this [stackOverflow issue](https://stackoverflow.com/questions/46436306/angular-upgrademodule-rootscope-digest-error-even-though-we-are-not-triggerin)
and [this conversation](https://gitter.im/angular/angular?at=59cacac0614889d47541dacc) and [this conversation](https://gitter.im/angular/angular.js?at=59cad2967b7d98d30d3d8637) in gitter

We authorize a user with Google SignIn, and then use ui-router to send them to the landing page, doing this causes a $rootScope digest already in process error. 

We do not trigger a $digest / $apply explicitly. We don't route a user with $location, location, or anything. We use ui-router, but it's not ui-router that triggers the $digest within the $digest. As far as I can tell, it appears to be [this line](https://github.com/angular/angular/blob/master/packages/upgrade/src/static/upgrade_module.ts#L249) in NgUpgrade. 

## Expected behavior

No $rootScope.$digest error

## Minimal reproduction of the problem with instructions

- Go here: https://portal.telnyx.com/index-nomin.html#/
- Create an account. 
- Log out.
- Open dev tools (so you can "clear cache and hard reload")
- "clear cache and hard reload"
- Sign in with Google Sign In.

If you do not see a digest error in console, repeat the above process up to 5 times and you will eventually see the error. Here is a short snippet of the code:

https://pastebin.com/1h7AvuJt

## What is the motivation / use case for changing the behavior?

If it's a bug it's a bug. 

## Environment

<pre><code>
Angular version: X.Y.Z

4.2.4

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by gkalpak** [comment] 2017-09-27 09:08
For whatever reason I can't sign up at telnyx (using Google Sign In) and the snippet shows too little to investigate. Using email/password log-in seems to work without issues, so this seems related to signing in with an identity provider.

I am afraid there is not much we can do without a reproduction.

As already mentioned, the reason we don't "play it safe" with `$rootScope.$$phase` check, is that it tends to hide other issue and performance problems with the app.
See https://github.com/angular/angular/pull/17692#issuecomment-312947461 (and the references issues) for more details.

Happy to look more into it as soon as I can get my hands on a reproduction (ideally minimal with non-minified code, but I know that might be a lot to ask :smiley:).

**Comment by petebacondarwin** [comment] 2017-09-27 10:26
It would help if you had a version where the source files were not mangled.
From the look of the stack when the exception is thrown:

![screen shot 2017-09-27 at 11 16 19](https://user-images.githubusercontent.com/15655/30908459-847f749e-a375-11e7-9710-1f4fb2d6e429.png)

it appears that something (ui-router?) is calling `$location` to do the redirect to the new path. Then it looks like you are using bugsnag which has monkeypatched and wrapped a call to **something** (possible `popState`?), which appears to be also monkeypatched by Zones, which in turn is then triggering the `microTaskEmpty` hook, and so triggering another `$digest`.

Can you try removing the bugsnag library?

Also can you provide a version where the source files have not been minified?

**Comment by petebacondarwin** [comment] 2017-09-27 13:59
I'm pretty sure from stepping through the code that bugsnag is causing some problem here.

**Comment by andrewl-telnyx** [comment] 2017-09-27 15:11
We'll disable bugsnag in our staging environment to see if that will fix the problem and if it doesn't we'll turn off minification temporarily (but that's kind of complicated). I'll get back to you here in a few hours. Thank you so much for your help here.

**Comment by andrewl-telnyx** [comment] 2017-09-27 16:51
@petebacondarwin we turned off bugsnag and commented it out in code, and the problem still occurs. we're going to get you a non minified version here in a bit.

**Comment by andrewl-telnyx** [comment] 2017-09-27 18:41
if there's anything else i can do to assist you with this let me know on here or andrewl@telnyx.com and i'll get back to you as fast as humanly possible
thank you so much again for helping with this y'all are my heros.

**Comment by petebacondarwin** [comment] 2017-09-27 21:04
So... the underlying process looks like this:

1) the url is changed from outside `$location` (maybe the Google Auth library or maybe ui-router - the latter I think)
2) On the next digest, this change to the URL triggers `$location`'s watcher, which tries to resynchronise itself with the browser URL
3) in doing so it writes to `window.location.hash`
4) this triggers a `PopState` event
5) The Angular `PlatformLocation` is being used, which sets up a handler for `PopState` events.
6) the Zone library wraps this handler as a `ZoneAwareCallback`
7) For some reason, and only when the logging in for the first time, after the cache has been cleared, the Zone library decides that there is a need to run the `MicroTaskEmpty` hook
8) This hook is handled by ngUpgrade, which triggers a new digest and BAM there is the error

The question I am having trouble answering is what is it about this first login that causes the Zone library to trigger the hook.

I think we might need to pull in the big guns (@mhevery perhaps) to help dig through what is happening in Zones.

**Comment by andrewl-telnyx** [comment] 2017-09-27 21:22
@petebacondarwin you're a champion.
at some point I need to figure out how it is that you know all of that information, and which type of angular/devtools witchcraft i need to learn in order to be able to do what you just did.

but i have some exciting news on my end.
in the gitter channel, a mysterious person by the name of @derekkite noticed my bug was a similar bug to the one he had, and he suggested running it in a zone.
That solution worked.
Here's what it looked like:


```
function googleAuth() {
    // "postmessage" as the redirect_uri is the flag to Google that you want to get the code to exchange for
    // a token here in the browser, but you will have a server redeem the code later. (This is an official
    // API feature in auth2 and not just a hack.) prompt of "select_account" causes the prompt for selection
    // to be shown no matter whether a user is signed in to a Google account already or not.
    var rootZone = window.Zone.current;
    var zoneA = rootZone.fork({name: 'googlezone'});
    $window.auth2.grantOfflineAccess({redirect_uri: 'postmessage', prompt: 'select_account'}).then(function(resp){
      zoneA.run(
        function(){
          handleAuth2Result(resp);
        });
    });
    return false;
  }
```

So, at least on my end, that solution appears to have worked. I do not know why it worked. I watched the Zone.js NgConf talk that one dude did and now I understand on some level what Zone.js does and I now have an appreciation of it. 

However, I'm super interested in what, if anything, you all change in order to solve that issue, if it is in fact, an issue. At minimum it seems like a good idea to add the solution in documentation somewhere.

**Comment by petebacondarwin** [comment] 2017-09-27 21:34
The reason your solution works is that you are no longer running the `handleAuth2Result` function inside the "Angular" zone, which means that when the popstate event is triggered our ngUpgrade `onMicroTaskEmpty` handler is not called, which in turn does not trigger the digest.

Normally this is a dangerous thing to do, because anything that follows in that zone (all async tasks that are triggered via that original call to `handleAuth2Result`) will not trigger change detection between the AngularJS and Angular parts of the app.

But in this case I imagine that it is not going to impact your app too much. I guess it depends on what is in that handler.

**Comment by petebacondarwin** [comment] 2017-09-27 21:35
Glad you have a workaround. If you find that you start missing change detections then you'll know where to look.

**Comment by andrewl-telnyx** [comment] 2017-09-27 22:18
@petebacondarwin In my experience a strength of angular is that there is an "angular way" of doing things;
the obvious problem with that, however, is that deviating from what is explicitly the "angular way" of doing things leads to a lot of pain and confusion.
I very much prefer to do things the angular way when working with angular, and if this is not that, then I really want to know what I can do to align what I'm doing with how it's typically done.

Is there a different, more angular way that you can think of fixing the problem? or a direction you can point me? If not, no worries- you've already done so much to help me understand this problem. You rule.

**Comment by JiaLiPassion** [comment] 2017-09-28 00:21
@andrewl-telnyx , @petebacondarwin,  I would like to help to debug about the `Zone` issue, I will try to debug why `zone` not trigger `onMicroTaskEmpty`

**Comment by gkalpak** [comment] 2017-09-28 08:24
@andrewl-telnyx: BTW, something I noticed while looking at the code is that the `DSCache#setRecycleFreq()` is using `setInterval()` to schedule an operation once per second for each cache (I saw 3 of them iirc). Since `setInterval` is called from inside AngularJS, which is bootstraped inside the Angular zone, it means that 3 times per second you get a new `onMicrotaskEmpty` emission, i.e. 3x Angular change detection and 3x `$digest` per second (for no change).
<sub>I took a quick look, so take it with a grain of salt. But worth looking into.</sub>

(This is probably not related to this issue - just mentioning it as a heads-up.)

##
You might also be interested in a new API that will be introduced in 5.x, which will allow you to bootstrap AngularJS outside the Angular zone and avoid the `$digest` on each `onMicrotaskEmpty` emission.
The docs are still in progress, but you can get a preview [here][1].

It is more suited for architectures that try to keep the two parts decoupled, so not sure if it works for you.
Not that interleaving Angular/AngularJS components won't work, but you might have to manually trigger change detections too often (e.g. if you rely on "global" app state through services, instead of propagating it via component inputs).

[1]: https://pr18487-aedf0aa.ngbuilds.io/api/upgrade/static/downgradeModule

**Comment by marioagarcia** [comment] 2017-10-18 19:02
@petebacondarwin I have the same issue in my app. I have created a mini version of my app with the hopes to reproduce it there but no luck yet so I'm still in the middle of debugging and finding out what the issue is. I know it has to do with the popstate event. My question to you is, if we were to change this line [line](https://github.com/angular/angular/blob/81173b0d29852828768773fc1a366eeea824689a/packages/upgrade/src/static/upgrade_module.ts#L249) in the Upgrade Module
from:
`_this.ngZone.onMicrotaskEmpty.subscribe(function () { return $rootScope.$digest(); });`
to:
`_this.ngZone.onMicrotaskEmpty.subscribe(function () { return $rootScope.$evalAsync(); });`
could that still do the trick but be resilient to issues like this where maybe the zone thinks it's done but there is a $phase still going on?

**Comment by petebacondarwin** [comment] 2017-10-20 07:51
We did use `$evalAsync` at some point instead. But that caused its own set of issues for other apps. :-(

**Comment by marioagarcia** [comment] 2017-10-25 23:02
@petebacondarwin as I'm debugging this, I found out that this error happens because a task is invoked in an angular zone after another event is evoked in the root zone. What I need help with is understanding why something like a click event is handled in the root zone instead of the angular zone. If you take a look at the call stack before the error happens, you can see that the first task is in the root zone and the other one is in the angular zone.

![screen shot 2017-10-25 at 4 49 47 pm](https://user-images.githubusercontent.com/2449806/32027264-595b2c86-b9a5-11e7-8266-ac265e87e5b4.png)

![screen shot 2017-10-25 at 4 58 36 pm](https://user-images.githubusercontent.com/2449806/32027363-d6dfdea4-b9a5-11e7-890d-6f1495446ac7.png)

![screen shot 2017-10-25 at 5 00 42 pm](https://user-images.githubusercontent.com/2449806/32027433-4524a818-b9a6-11e7-8b84-995da46a774e.png)


I still haven't been able to reproduce it in a separate app. In the second app I built the click event is handled in the angular zone and everything works just fine...

Any ideas? Thanks for taking the time to look at this

**Comment by gkalpak** [comment] 2017-10-26 19:32
If an event listener is invoked outside the Angular zone, it means that it was _registered_ outside the Angular zone. I would try to track down where that listener is registered and see if that gices any clues.

**Comment by gkalpak** [comment] 2017-12-15 12:42
This can be closed afaict.

**Closed by gkalpak** 2017-12-15 12:42 UTC
Labels: comp: upgrade/static
