### ISSUE TITLE
Unable to dynamically  load lazyload Modules

### ISSUE THREAD

**Issue by tatvaaksh** [angular/angular#30617] opened 2019-05-22 16:43 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package  
@angular/router

### Is this a regression?
Not sure

### Description

  

I have a lazy-loaded module in an angular app. I am adding it dynamically to the route using <pre>     this.router.config.unshift( this.theOletObj );</pre>
It errors out and the module and its component doesn't get dynamically loaded  : 

## 🔬 Minimal Reproduction 
https://stackblitz.com/edit/angular-raaom9 
 https://stackblitz.com/...

## 🔥 Exception or Error
<pre><code> preview-4adb70f742b91f09679fb.js:1 ERROR Error: Uncaught (in promise): Error: Cannot find 'BaseModule' in './modules/base/base.module'
Error: Cannot find 'BaseModule' in './modules/base/base.module'
    at checkNotEmpty (system_js_ng_module_factory_loader.ts:91)
    at eval (system_js_ng_module_factory_loader.ts:71)
    at ZoneDelegate.invoke (zone.js:391)
    at Object.onInvoke (ng_zone.ts:273)
    at ZoneDelegate.invoke (zone.js:390)
    at Zone.run (zone.js:150)
    at eval (zone.js:889)
    at ZoneDelegate.invokeTask (zone.js:423)

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code> 
Angular CLI: 7.3.9
Node: 10.15.3
OS: linux x64
Angular: 7.2.15
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.13.9
@angular-devkit/build-angular      0.13.9
@angular-devkit/build-optimizer    0.13.9
@angular-devkit/build-webpack      0.13.9
@angular-devkit/core               7.3.9
@angular-devkit/schematics         7.3.9
@angular/cdk                       <error>
@angular/cli                       7.3.9
@angular/fire                      <error>
@angular/flex-layout               <error>
@angular/http                      <error>
@angular/material                  <error>
@angular/material-moment-adapter   <error>
@angular/platform-server           <error>
@ngtools/webpack                   7.3.9
@schematics/angular                7.3.9
@schematics/update                 0.13.9
rxjs                               6.3.3
typescript                         3.2.4
webpack                            4.29.0

</code></pre>

**Anything else relevant?** 
I have observed that when we configure lazy-loaded modules using `loadChildren` and the directly string pointing to the module that we want to lazy load. internally in the router-config 
as below code: 
<pre><code>
 this.router.config.unshift( {path:'base',loadChildren:'./modules/base/base.module#BaseModule'} );
</code></pre>
then at runtime :this is replaced by a "function"-related to the Module (probably a NgFactory implementation of the module)
<pre><code>this.router.config is:
 0:
loadChildren: ƒ ()
path: "base"
_loadedConfig: LoadedRouterConfig {routes: Array(1), module: NgModuleRef_}
__proto__: Object
length: 1
__proto__: Array(0) </code></pre>
 and that is returned in reference to the final router config which is being set. 

However when we try to load it dynamically, that is when the string defining my module that is to be dynamically loaded is being passed as a variable and the Route is built using it, when we use this route in the final routing config as below code: 

<pre><code>
let theOletObj: Route;
let  str='./modules/base/base.module#BaseModule';
    this.theOletObj={path:'base',loadChildren:str};

     this.router.config.unshift( this.theOletObj );
</code>
</pre>
 it leaves the value of "loadChildren" as a "string " 
<pre><code>0: {path: "base", loadChildren: "./modules/base/base.module#BaseModule"}
length: 1
__proto__: Array(0)</code></pre>

and dosent replace it with a "function"

**Comment by fmalcher** [comment] 2019-07-09 18:35
Unfortunately you can't define lazy-loaded modules at runtime. This is because at build time Angular needs to extract lazy-loaded modules and bake them into separate bundles. Thus, those modules need to be determined at build time.

**Comment by fmalcher** [comment] 2019-07-11 22:40
@tatvaaksh I was probably wrong assuming it won't work. I forgot there is a `lazyModules` section in the `angular.json` file where you can declare modules that will be lazy-loaded at runtime. Can you try putting those together – the `lazyModules` option and your solution of determining the lazy module at runtime?

**Comment by atscott** [comment] 2020-07-14 21:52
I was actually able to get this to work using the non-deprecated `LoadChildrenCallback`, `lazyModules` in the `angular.json` and adding the `base.module` to the `files` in `tsconfig.app.json`. The project is uploaded here: https://github.com/atscott/angularbugrepros/tree/dynamiclazyroute/src/app

Closing, as this seems to be working with the current version and available options in the framework.

**Closed by atscott** 2020-07-14 21:52 UTC
Labels: comp: router

**Comment by zunwebs** [comment] 2020-07-17 14:51
> @tatvaaksh I was probably wrong assuming it won't work. I forgot there is a `lazyModules` section in the `angular.json` file where you can declare modules that will be lazy-loaded at runtime. Can you try putting those together – the `lazyModules` option and your solution of determining the lazy module at runtime?

I did Try it and it doesn't work . I am trying to load the module name through a string variable , as below: 
`      let  str='./modules/base/base.module#BaseModule';
     this.router.config.unshift( {path:'base',loadChildren:str} );

   console.log(this.router.config );
   let cfg=this.router.config[0];
   console.log('this.cfg is')
  console.log(   cfg.loadChildren);`

 however with the latest angular-router the format of lazy-loaded module config is through the loadChildrenCallback as below: 
`     this.router.config.unshift( {path:'base',loadChildren: () => import('./modules/base/base.module').then(m => m.BaseModule)} );
` 
With this new pattern i have dependency to have the BaseModule reference in the code (and is not passed dynamically through a string) . 
hence I cannot you this pattern. I was to pass the module loading information as a string and expect thy angular-router to resolve it at runtime.

**Comment by zunwebs** [comment] 2020-07-17 14:53
> I was actually able to get this to work using the non-deprecated `LoadChildrenCallback`, `lazyModules` in the `angular.json` and adding the `base.module` to the `files` in `tsconfig.app.json`. The project is uploaded here: https://github.com/atscott/angularbugrepros/tree/dynamiclazyroute/src/app
> 
> Closing, as this seems to be working with the current version and available options in the framework.

I am not sure why the issue is closed. the sample provided above uses the standard `LoadChildrenCallback` as below `this.router.config.unshift( {path:'base',loadChildren: () => import('./modules/base/base.module').then(m => m.BaseModule)} );
`
With this  pattern i still have dependency to have the `BaseModule` reference in the code (and is not passed dynamically through a string) .
