### ISSUE TITLE
Add `enableDebugTools` and `disableDebugTools` to the global `ng` object

### ISSUE THREAD

**Issue by maxkoretskyi** [angular/angular#19775] opened 2017-10-18 06:50 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ x ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior && Expected behavior

Currently if I want to profile Angular change detection I have to add a call to `enableDebugTools` into my code base and then pass `ComponentRef` at the moment of calling the component. However, it would be very convenient to expose  `enableDebugTools` and `disableDebugTools` as part of global `ng` object so that I can run the profiler from the console without modifying my code (for example, on production environment):

```
const rootComponent = ng.probe($0).injector.get(ng.coreTokens.ApplicationRef).components[0];
ng.enableDebugTools(rootComponent );
ng.profiler.timeChangeDetection();
ng.disableDebugTools();
```

As I understand it's a simple change that requires two calls to `exportNgVar` with the function `enableDebugTools` and `disableDebugTools` functions as parameters. I'm willing to make a PR if there are no blocking issues.

**Comment by vinayakpatil** [comment] 2019-08-29 15:22
This would be super useful for profiling prod environments

**Comment by JoostK** [comment] 2021-07-14 11:43
Hi Max, this is basically a duplicate of #12667 (let's say I'm doing spring cleanup)

**Closed by JoostK** 2021-07-14 11:43 UTC
Labels: comp: core, core: debug tools, feature, insufficient votes, votes required

**Comment by Lonli-Lokli** [comment] 2021-07-14 12:02
@JoostK so soon 2nd will be closed as I see as well? As no-one voted for it?

**Comment by JoostK** [comment] 2021-07-14 12:13
@Lonli-Lokli in this case the voting situation doesn't change much between the two issues. FYI issues are never automatically closed based on vote counts.
