### ISSUE TITLE
cannot use Object.defineProperty on window.angular (causes a TypeError)

### ISSUE THREAD

**Issue by ldellorto** [angular/angular#6165] opened 2015-12-29 16:15 UTC
In upgrade.js (Line 284 in 2.0.0-beta.0), there is a _hasOwnProperty_ check that alone, causes a TypeError if you use Object.defineProperty to define a setter function on window.angular:

``` javascript
var angular = {
    bootstrap: noNg,
    module: noNg,
    element: noNg,
    version: noNg
  };
  try {
    if (window.hasOwnProperty('angular')) {
      angular = window.angular;
    }
  } catch (e) {}
  exports.bootstrap = angular.bootstrap;
  exports.module = angular.module;
  exports.element = angular.element;
  exports.version = angular.version;
```

Because of this, window.hasOwnProperty returns true even if angular is actually 'undefined' and the local angular object is now also undefined when it really should be the local copy declared just above.

Here is a jsfiddle to demonstrate an example: https://jsfiddle.net/uko7uuvL/

I propose that this actually just be a null & undefined check instead: 

``` javascript
if (window.angular) {
   angular = window.angular;
}
```

This would make it safe to use Object.defineProperty to add a setter function to listen for when angular is initialized.

**Comment by wesleycho** [comment] 2015-12-31 12:00
This should be posted in https://github.com/angular/angular.js/issues , not here - this repository is for ng2.

**Comment by ldellorto** [comment] 2015-12-31 14:22
@wesleycho this is a bug caused from source code in this repository. upgrade.js is an angular 2.0 code piece.

The error is due to the if statement I mentioned that is in this repo checking if window.hasOwnProperty('angular')

**Comment by ldellorto** [comment] 2016-01-12 16:27
angular/modules/angular2/src/upgrade/angular_js.ts:113

**Comment by marcalj** [comment] 2016-05-31 15:15
Related problem here:
![image](https://cloud.githubusercontent.com/assets/63667/15679720/2c3992dc-2753-11e6-9885-a23d739129b7.png)

Cannot play with upgradeAdapter, it doesn't detect angular definition :/

**Comment by petebacondarwin** [comment] 2016-12-23 11:48
@ldellorto and @marcalj - Please can you provide a live reproduction of this problem?

Here is a plunker showing that the if statement can work: http://plnkr.co/edit/LBbjJrvUYh2ee2p5FRhR?p=preview

**Comment by ldellorto** [comment] 2016-12-27 12:25
The issue is with trying to listen for the initialization of angular, not of a property on angular, like so:
`Object.defineProperty(window, "angular", {set: function(newValue) {/*...*/},configurable: true});`
In addition to this, this needs to be set before you load angular, so move the script.js above the angular.js file.

I demonstrate the issue in the fiddle I posted above, but here is a plunker modifying the one you posted:
http://plnkr.co/edit/XJGJLVOkq4wmhAQm8co8?p=preview

The hasOwnProperty check is problematic in the source code, because it returns true when my code had a setter defined on window.angular, which is not accounted for here. As I suggested, this would be a sufficient fix, I believe: 
`if (window.angular) {
   angular = window.angular;
}`

**Comment by petebacondarwin** [comment] 2016-12-28 09:05
OK, I understand your problem now @ldellorto. Can you give some background as to why do you need this notification of when the angular global has been set?

**Comment by petebacondarwin** [comment] 2016-12-28 09:20
For anyone else looking at this the line that is a problem is https://github.com/angular/angular/blob/master/modules/%40angular/upgrade/src/angular_js.ts#L186

I think that the change that you suggest is reasonable.

**Comment by ldellorto** [comment] 2016-12-28 13:34
Thanks so much!

I work for a company that automatically hooks into javascript frameworks such as this, in order to collect timing information starting with user clicks/page loads, through the end of XHR callback functions. We need to essentially create wrapper functions for http, and it must be early enough before any customer code can make any calls, which is why we listen for the initialization of the framework in question so we are in as early as possible.

**Comment by petebacondarwin** [comment] 2016-12-28 13:38
@ldellorto - are you aware of the "deferred bootstrap" feature of Angular 1?
See https://docs.angularjs.org/guide/bootstrap#deferred-bootstrap
This is the standard way to override Angular fundamentals before the application begins as used by Batarang and Protractor.

**Comment by ldellorto** [comment] 2016-12-28 13:46
No I have not. This sounds pretty great, considering right now we have to listen for and wrap the 'module' function to insert our own module for Angular 1. Do you know if there is anything like this for Angular 2 though? Or at least in the works for it?

**Comment by petebacondarwin** [comment] 2016-12-28 14:01
I don't know of a similar mechanism in Angular 2+.  Perhaps @juliemr knows what they do in Protractor for this?

**Comment by petebacondarwin** [comment] 2016-12-28 14:08
Looks like it is not implemented in Protractor for Angular 2+ yet: https://github.com/angular/protractor/blob/master/lib/browser.ts#L783-L789

**Comment by gkalpak** [comment] 2017-12-13 11:45
TBH, I don't see how this is a problem. The code would fail anyway. The only difference is the error message you get, but given this is a very unusual usecase I am not too concerned about that. (Also note that both mesages are roughly equally descriptive imo.)

I am going to close the issue, but if someone feels strongly about this, please do submit a PR with a fix - it should be pretty trivial :smiley:

**Closed by gkalpak** 2017-12-13 11:46 UTC
Labels: comp: upgrade/dynamic, comp: upgrade/static, effort1: easy (hours), freq1: low, severity2: inconvenient, type: bug, workaround2: non-obvious
