### ISSUE TITLE
Application screen gets blank if there is an error in `ngOnDestroy`

### ISSUE THREAD

**Issue by peterbakonyi05** [angular/angular#20359] opened 2017-11-11 15:20 UTC
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
When there is an error in `ngOnDestroy` of the page that gets destroyed upon navigation, it stops loading of the new page and the screen will be blank.

```ts
// when navigating from profile to any other pages, screen will be blank
const routes: Routes = [
  { path: '', pathMatch: 'full', component: HomeComponent },
  { path: 'profile', component: ProfileComponent },
  { path: '**', component: NotFoundComponent }
];

export class ProfileComponent implements OnDestroy {
   ngOnDestroy() {
     throw new Error('Kill the app');
   }
  }
```

## Expected behavior
Error in `ngOnDestroy` does not stop angular from loading the new route.

## Minimal reproduction of the problem with instructions
https://github.com/peterbakonyi05/ngx.router-navigation-error-issue

## What is the motivation / use case for changing the behavior?
If you are using a third-party library and it throws an error during clean up, the screen will be blank. Ideally an error in ngOnDestroy should not stop the router from loading the new page. Of course you can add a `try-catch` block to that specific call but it is still quite fragile.

## Environment

<pre><code>
Angular version: ^5.0.0

Browser:
- [ X] Chrome (desktop) version 62
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.9.0
- Platform:  Windows 10
</code></pre>

**Comment by trotyl** [comment] 2017-11-11 15:33
Duplicate of https://github.com/angular/angular/issues/15946?

**Comment by peterbakonyi05** [comment] 2017-11-13 16:48
I think so, thanks for the reply

**Comment by jasonaden** [comment] 2017-11-14 00:02
Closing as duplicate of #15946

**Closed by jasonaden** 2017-11-14 00:02 UTC
