### ISSUE TITLE
Unable to select default value for more than one drop down rendering in primeng datatable as a column

### ISSUE THREAD

**Issue by srivatsavap** [angular/angular#13966] opened 2017-01-17 17:16 UTC
`app.component.html:-
--------------------------
<div>
    <p-dataTable [value]="cars" selectionMode="single" [(selection)]="selectedCar" (onRowSelect)="onRowSelect($event)" [paginator]="true" [rows]="10" [responsive]="true">
        <header>CRUD for Cars</header>
        <p-column field="vin" header="Vin" [sortable]="true"></p-column>
        <p-column field="year" header="Year" [sortable]="true"></p-column>
        <p-column field="brand" header="Brand" [sortable]="true"></p-column>
        <p-column field="color" header="Color" [sortable]="true"></p-column>
		<p-column field="brand" header="Brand (Custom)" [filter]="true" [style]="{'overflow':'visible'}" filterMatchMode="equals">
        <template pTemplate="body" let-col>
            <select (ngModelChange)="onChange($event)">			   
				<option [value]="i" *ngFor="let i of brands;let j=index;" [selected]="j==heroes[0]">{{i.value}}{{j==3&&countnum<12 ? callme() : ''}}</option>
			</select>
        </template>
       </p-column>
        <footer><div class="ui-helper-clearfix" style="width:100%"><button type="button" pButton icon="fa-plus" style="float:left" (click)="showDialogToAdd()" label="Add"></button></div></footer>
    </p-dataTable>

    <p-dialog header="Car Details" [(visible)]="displayDialog" [responsive]="true" showEffect="fade" [modal]="true">
        <div class="ui-grid ui-grid-responsive ui-fluid ui-grid-pad" *ngIf="car">
            <div class="ui-grid-row">
                <div class="ui-grid-col-4"><label for="vin">Vin</label></div>
                <div class="ui-grid-col-8"><input pInputText id="vin" [(ngModel)]="car.vin" /></div>
            </div>
            <div class="ui-grid-row">
                <div class="ui-grid-col-4"><label for="brand">Year</label></div>
                <div class="ui-grid-col-8"><input pInputText id="brand" [(ngModel)]="car.year" /></div>
            </div>
            <div class="ui-grid-row">
                <div class="ui-grid-col-4"><label for="brand">Brand</label></div>
                <div class="ui-grid-col-8"><input pInputText id="brand" [(ngModel)]="car.brand" /></div>
            </div>
            <div class="ui-grid-row">
                <div class="ui-grid-col-4"><label for="color">Color</label></div>
                <div class="ui-grid-col-8"><input pInputText id="color" [(ngModel)]="car.color" /></div>
            </div>
        </div>
        <footer>
            <div class="ui-dialog-buttonpane ui-widget-content ui-helper-clearfix">
                <button type="button" pButton icon="fa-close" (click)="delete()" label="Delete"></button>
                <button type="button" pButton icon="fa-check" (click)="save()" label="Save"></button>
            </div>
        </footer>
    </p-dialog>
</div>`
`app.component.ts:-
-------------------
import {Component,Input} from '@angular/core';
import {Car} from './cars/car';
import {CarService} from './cars/carservice';
import {SelectItem} from 'primeng/primeng';
class PrimeCar implements Car {
    constructor(public vin?, public year?, public brand?, public color?) {}
}

@Component({
	templateUrl: 'app/app.component.html',
	selector: 'my-app'
})
export class AppComponent {

	displayDialog: boolean;

    car: Car = new PrimeCar();

    selectedCar: Car;

    newCar: boolean;
    brands: SelectItem[];
	bra:SelectItem[];
    cars: Car[];
    cities: SelectItem[];
	heroes: any[];
	selectedCity: string;
	countnum:number;
    constructor(private carService: CarService) {
       this.countnum=0;
	this.numbers = Array(5).fill().map((x,i)=>i); // [0,1,2]
	//this.num = Array(5).fill().map((x,i)=>i); // [1,2,0]
      this.brands = [];
        this.brands.push({label: '1', value: 'fuck',selectit:2});
        this.brands.push({label: '2', value: 'Audi',selectit:2});
       this.brands.push({label: '0', value: 'BMW',selectit:1});
	   this.bra=[];
	   this.bra.push({label: '1', value: 'fuck',selectit:2});
		this.heroes=[1,2,3,3,2,1,2,2,3,1];
		
		
	}

    ngOnInit() {
	
		
        this.carService.getCarsMedium().then(cars => this.cars = cars);
    }
    @Input()
  set ready(isReady: boolean) 
  {
    if (isReady) 
	{
	console.log('hello');
	}
  }
    showDialogToAdd() {
        this.newCar = true;
        this.car = new PrimeCar();
        this.displayDialog = true;
    }

    save() {
        if(this.newCar)
            this.cars.push(this.car);
        else
            this.cars[this.findSelectedCarIndex()] = this.car;

        this.car = null;
        this.displayDialog = false;
    }

    delete() {
        this.cars.splice(this.findSelectedCarIndex(), 1);
        this.car = null;
        this.displayDialog = false;
    }

    onRowSelect(event) {
        this.newCar = false;
        this.car = this.cloneCar(event.data);
        this.displayDialog = true;
    }

    cloneCar(c: Car): Car {
        let car = new PrimeCar();
        for(let prop in c) {
            car[prop] = c[prop];
        }
        return car;
    }

    findSelectedCarIndex(): number {
        return this.cars.indexOf(this.selectedCar);
    }
	callme()
	{
	  this.countnum=this.countnum+1;
	  this.heroes[0]=this.heroes[this.countnum];
	}
}`
 I have rendered a primeng datatable and a column of drop downs if you observe my code I am trying to select default value for each drop down as 
drop down 1 - default selected value is "Audi"
drop down 2 - default selected value is "BMW" but I am not successful please help 

![1-16-2017 10-43-31 pm](https://cloud.githubusercontent.com/assets/12388920/22031470/b5362adc-dd06-11e6-8ed9-5bb7220a7ee5.png)

https://plnkr.co/edit/IWluMiywDBwZVIhCWOKn?p=preview

**Comment by DzmitryShylovich** [comment] 2017-01-17 17:20
Sounds like duplicate of https://github.com/angular/angular/issues/13268

**Comment by srivatsavap** [comment] 2017-01-17 17:25
My problem is not with single drop down but I have more than one drop down and they need to have their own selected default values.

**Comment by srivatsavap** [comment] 2017-01-17 17:26
<p-dataTable [value]="cars" selectionMode="single" [(selection)]="selectedCar" (onRowSelect)="onRowSelect($event)" [paginator]="true" [rows]="10" [responsive]="true">
        <header>CRUD for Cars</header>
        <p-column field="vin" header="Vin" [sortable]="true"></p-column>
        <p-column field="year" header="Year" [sortable]="true"></p-column>
        <p-column field="brand" header="Brand" [sortable]="true"></p-column>
        <p-column field="color" header="Color" [sortable]="true"></p-column>
		<p-column field="brand" header="Brand (Custom)" [filter]="true" [style]="{'overflow':'visible'}" filterMatchMode="equals">
        <template pTemplate="body" let-col>
            <select (ngModelChange)="onChange($event)">			   
				<option [value]="i" *ngFor="let i of brands;let j=index;" [selected]="j==heroes[0]">{{i.value}}{{j==3&&countnum<12 ? callme() : ''}}</option>
			</select>
        </template>
       </p-column>
        <footer><div class="ui-helper-clearfix" style="width:100%"><button type="button" pButton icon="fa-plus" style="float:left" (click)="showDialogToAdd()" label="Add"></button></div></footer>
    </p-dataTable>

**Comment by DzmitryShylovich** [comment] 2017-01-17 17:43
As far as I can tell from the impl, angular is complete ignore `select` property. So I don't see a bug here.

**Comment by srivatsavap** [comment] 2017-01-17 19:09
What might be causing the issue showing in the browser?

**Comment by srivatsavap** [comment] 2017-01-17 19:10
Why it is throwing error after loading default values?

**Comment by DzmitryShylovich** [comment] 2017-02-01 12:09
@srivatsavap angular ignores `selected` property. You can find the explanation here https://github.com/angular/material2/issues/2250#issuecomment-274904991

@pkozlowski-opensource can be closed

**Closed** 2017-02-01 14:04 UTC
