### ISSUE TITLE
Untyped compilation (transpileModule equivalent)

### ISSUE THREAD

**Issue by pauldraper** [angular/angular#39678] opened 2020-11-13 16:41 UTC
# 🚀 feature request

### Relevant Package

@angular/core

### Description

Angular compilation is slow. Make it faster.

### Describe the solution you'd like

Both TypeScript and React (TSX) can compile much, much faster (like 10x) with ts.transpileModule.

This just transpiles, without loading other modules or running type verification.

AFAIK, no similar feature exists for Angular.

### Describe alternatives you've considered

Waiting for the compiler to finish.

**Comment by JoostK** [comment] 2020-11-13 16:58
This is a duplicate of #37585 and related to #38732.

**Closed by JoostK** 2020-11-13 16:58 UTC
