### ISSUE TITLE
Protractor errors when bootstrapping the @angular/upgrade demo app

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#9407] opened 2016-06-21 18:10 UTC
With the latest protractor and selenium-webdriver I get:

```
 Failed: Cannot assign to read only property 'stack' of Error while waiting for Protractor to sync with the page: "window.getAllAngularTestabilities is not a function"

```

**Comment by juliemr** [comment] 2016-06-22 01:03
I've confirmed that Protractor's tests against RC3 still work: quick and dirty change is at https://github.com/juliemr/protractor/commit/c2c7b1708e857527e7525114b91e1bfc68b39be3

From Protractor's perspective, the app looks like an angular 1 application because it exposes `window.angular` to the page instead of `window.getAllAngularTestabilities`. So, it will fail if the protractor configuration file has `useAllAngular2AppRoots`. But it should work if instead a `rootElement` is provided.

@IgorMinar let's take another look at this tomorrow so I can see your setup.

(side note, the actual error is being partially obscured by the 'stack' red herring - this has been fixed in the latest protractor and will be out in the next release)

**Comment by juliemr** [comment] 2016-06-22 01:49
Ahah, found part of the issue. When a hybrid app is tested, it should correctly be able to load when `window.name == NG_DEFER_BOOTSTRAP!` - but this is not true for playground/upgrade. It does work correctly for Protractor's ng1/ng2 hybrid app. I'll dig into it more.

**Comment by juliemr** [comment] 2016-06-22 02:10
The issue has to do with using an upgraded angular 1 directive which has a binding. I can reproduce this in Protractor's simple test app with this change: https://github.com/juliemr/protractor/commit/b59abab4124bd78a74119ff6624f0c29014b0d01

I don't know why this is interacting badly - will have to look into ngUpgrade code more. I suspect that pausing bootstrap is causing some bad timing where angular 2 tries to compile the template before the upgraded app gets a go at it. The error message looks like "Template parse errors:
Can't bind to 'puppies' since it isn't a known native property"

**Comment by juliemr** [comment] 2016-06-22 02:13
We try to compile ng2 components in parallel with waiting for ng1 bootstrap. This is probably the issue? https://github.com/angular/angular/blob/f39c9c9e75671a7e235734b6b8aef263f6dff254/modules/%40angular/upgrade/src/upgrade_adapter.ts#L374

@sjelin you're the bootstrap/upgrade expert, could you take a look at this?

**Comment by juliemr** [comment] 2016-07-13 04:03
I'm bumping this to final, since it's not blocking for RC5.

**Comment by JT-Bruch** [comment] 2016-07-13 14:59
@juliemr - just out of curiosity why is this not a blocker for RC5?

**Comment by juliemr** [comment] 2016-07-13 16:46
@JT-Bruch there is nothing after rc4 that would become "more broken" with regards to this issue, and so there's no reason to hold up the other fixes and features that could go out while we try to resolve this.

**Comment by JT-Bruch** [comment] 2016-07-13 17:23
@juliemr ahh okay cool that makes sense.  It's a bit of a blocker for us as we are getting protractor spun up.  With that said, is there anything I can do to help resolve this? Or some resources to look at to see about making a PR?

I appreciate your prompt response! :+1:

**Comment by sjelin** [comment] 2016-07-14 23:47
#10084 should deal with this problem.  Sorry for the delay, I got caught up in other stuff.

**Closed** 2016-07-26 04:14 UTC
Labels: comp: core/testbed

**Comment by dopry** [comment] 2016-08-09 23:35
This doesn't just apply to hybrid apps, I'm getting it with a pure angular2 app. I'm working with a modified version of https://github.com/NathanWalker/angular2-seed-advanced. 
I am getting this error with a pure angular 2 app when running protractor on circle ci, after all my tests pass. 

```
11 specs, 0 failures
Finished in 0.196 seconds
[23:26:36] E/launcher - Error while waiting for Protractor to sync with the page: "window.getAllAngularTestabilities is not a function"
```

using 
```
 "protractor": "^4.0.0",
 "@angular/common": "^2.0.0-rc.4",
 "@angular/compiler": "^2.0.0-rc.4",
 "@angular/core": "^2.0.0-rc.4",
 "@angular/forms": "^0.2.0",
 "@angular/http": "2.0.0-rc.4",
 "@angular/platform-browser": "^2.0.0-rc.4",
 "@angular/platform-browser-dynamic": "^2.0.0-rc.4",
 "@angular/router": "^3.0.0-beta.2",
```

**Comment by vascofernandes** [comment] 2016-09-08 08:45
I am getting with issue with RC 6.

**Comment by paulsouche** [comment] 2016-12-28 15:48
I had the same issue with an electron app. I figured out that window was not my app window because devtools were opened via

```javascript
let mainWindow = new BrowserWindow({width: 800, height: 600});
mainWindow.webContents.openDevTools();
```

in the app index

Here the conf that worked for me once I deleted the line

```javascript
exports.config = (function () {
  return {
    capabilities: {
      browserName: 'chrome',
      chromeOptions: {
        binary: electronBinary, // relative path to your packaged app binary
      },
    },

    directConnect: true,

    useAllAngular2AppRoots: true,

    //...
  };
}());
```

Hope it helps...
