### ISSUE TITLE
Missing Angular Transclusion in the docs

### ISSUE THREAD

**Issue by rebelchris** [angular/angular#40260] opened 2020-12-24 12:26 UTC
# 📚 Docs or angular.io bug report

### Description

In the docs there is no mention of Transclusion which to me seems quite a nifty feature that could be used by people.
I wrote a separate blog post on this topic, which I would be happy to also convert to a docs page if applicable.

Could you let me know if this is something that can be added, or is it not mentioned for specific reasons?

### Anything else relevant?

you can see the article mentioned written by me here: [angular transclusion](https://daily-dev-tips.com/posts/angular-10-transclusion-when-and-why-youll-need-it/)

**Comment by Airblader** [comment] 2020-12-24 14:35
Duplicate of #17983

**Closed** 2020-12-28 16:09 UTC
Labels: comp: docs
