### ISSUE TITLE
NG0912: Component ID generation collision detected error thrown for 2 components without a selector

### ISSUE THREAD

**Issue by ahelmel** [angular/angular#53282] opened 2023-11-30 15:02 UTC
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

I have two components which do not have a selector. These components are Dialogs and are displayed by a DialogService on the fly (dynamically). So there is no need to create selectors for them as they are never used inside any templates. After some investigation I found out, that two components should not have the same selector, and it is fine, but these components does not have any selectors at all and do not need them.

In the Angular documentation the selector is optional: https://angular.io/api/core/Component#inherited-from-directive-decorator, so multiple components without a selector should be fine.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-9vzcj1?file=src%2Fmain.ts

### Please provide the exception or error you saw

```true
NG0912: Component ID generation collision detected. Components 'AdminComponent' and 'UserComponent' with selector 'ng-component' generated the same component ID. To fix this, you can change the selector of one of those components or add an extra host attribute to force a different ID. Find more at https://angular.io/errors/NG0912
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
"@angular/animations": "^17.0.5",
"@angular/common": "^17.0.5",
"@angular/compiler": "^17.0.5",
"@angular/core": "^17.0.5",
"@angular/forms": "^17.0.5",
"@angular/platform-browser": "^17.0.5",
"@angular/router": "^17.0.5",
```

**Comment by jessicajaniuk** [comment] 2023-11-30 15:28
@ahelmel Thanks for reporting this. Looks like this is a duplicate of #50158.

**Closed by jessicajaniuk** 2023-11-30 15:28 UTC
