### ISSUE TITLE
How to Apply Angular Universal for Multi-project workspace

### ISSUE THREAD

**Issue by LarozeMultiservices** [angular/angular#35028] opened 2020-01-29 09:03 UTC
Hello!
We are working on a **Multi-project / Workspace** based _Angular Application_ in which I want to use **Angular Universal** for SEO purpose.Where I can't able to find any kind of document or reference to use **Universal** in **Multi-Project** Applications.Any Support/Help would be appreciated.

**Comment by ericmartinezr** [comment] 2020-01-29 11:52
Buddy, this is the 3rd time you open the same issue. Have you tried StackOverflow as suggested the previous two times?

https://github.com/angular/angular/issues/34947, https://github.com/angular/angular/issues/34895
<hr>

Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by AndrewKushnir** [comment] 2020-01-29 21:07
Closing as a duplicate of #34947 and #34895.

**Closed by AndrewKushnir** 2020-01-29 21:07 UTC
