### ISSUE TITLE
Clarify OnInit interface in Getting Started guide

### ISSUE THREAD

**Issue by bampakoa** [angular/angular#32755] opened 2019-09-18 20:56 UTC
# 📚 Docs or angular.io bug report

### Description

The **Getting Started guide** mentions the `ngOnInit` method early on in the **Your First App** section but it is not clear what does this method actually doing. On the contrary, it is mentioned in the tutorial tour of heroes in the **Hero Editor** section.

> The ngOnInit() is a lifecycle hook. Angular calls ngOnInit() shortly after creating a component. It's a good place to put initialization logic.

From a beginner's point of view, it would make more sense to include this information in the Getting Started guide. What do you think?

### What's the affected URL?**
https://angular.io/start
https://angular.io/tutorial/toh-pt1

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by kapunahelewong** [comment] 2019-09-20 20:37
Agreed. I've noted in a comment in https://github.com/angular/angular/pull/32789 to request an edit of that last sentence, since we're trying to move toward encouraging that the logic be outside of the `ngOnInit()` throughout the docs (there are however examples of the opposite, such as that sentence).

**Comment by bampakoa** [comment] 2019-10-03 12:19
@kapunahelewong I was expecting that this should be closed automatically when merging #32789 🤔 . Is that correct?

**Comment by gkalpak** [comment] 2019-10-03 14:15
Fixed by #32789.

##
@bampakoa: Based on [this][1], in order for an issue to be closed automatically we either need a commit mentioning `Fixes #<ISSUE_NUMBER>` (or equivalent) to be merged into the main branch (which was not the case for the commit in #32789) or a PR mentioning the same in its description to be _merged_ into the main branch.

I suspect "merged" is the key here: Due to our rebase-based workflow, GitHub cannot detect that a PR was effectively merged and instead sees it as "closed with unmerged commits". My guess is that that is why the issue is not closed.
(And that's why it is always a good idea to include references to fixed issues in the commit message, as per our [commit message guidelines][2] :wink:)

[1]: https://help.github.com/en/articles/closing-issues-using-keywords#closing-an-issue-in-the-same-repository
[2]: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit

**Closed by gkalpak** 2019-10-03 14:15 UTC
Labels: comp: docs, freq3: high, severity1: confusing, state: has PR, type: feature
