### ISSUE TITLE
LifeCycle methods not called on asynchronous navigating

### ISSUE THREAD

**Issue by lexon0011** [angular/angular#8109] opened 2016-04-17 08:19 UTC
If I navigate in an asynchronous function to a component, the LifeCycle methode `ngOnInit` is not called.

Let me explain the issue with the following example:

```
export class SampleComponent {
    constructor(private router: Router) {
        setTimeout(() => {
            router.navigate(['OtherComponent', {}]);
        }, 1000);
    }
}
export class OtherComponent implements OnInit, OnDestroy {
    constructor() {
        console.log("OtherComponent - constructor");
    }
    ngOnInit() {
        console.log("OtherComponent - ngOnInit");
    }    
    ngOnDestroy() {
        console.log("OtherComponent - ngOnDestroy");
    }
}
```

- the routing to the component works, but  only the `constructor` is called (not `ngOnInit`)
- If I remove the asynchronous part, everything works:
```
constructor(private router: Router) {
    router.navigate(['OtherComponent', {}]);
}
```

I use the `setTimeout(...)` only to simulate an asynchronous execution. In the real world applicaton I have this problem on asynchronous functions like HTTP requests: `http.get(...)`

Is that a bug or is there an other way for navigating in asynchronous functions??

**Comment by zoechi** [comment] 2016-04-17 09:24
Sounds similar to #8012
Could you provide a Plunker to reproduce?

**Comment by lexon0011** [comment] 2016-04-18 11:44
I found out that the issues has nothing to do with asynchronous navigating. If the application register an class which use ES6-promise (`new Promise((resolve,reject) => { ... });`), than the LifeCycle method ngOnInit will not called.

I create this simple [repository](https://github.com/lexon0011/IssueDemonstrator), where I describe how the problem could be reproduced.

Please let me know, if you could reproduce it. Thanks!

**Comment by brandonroberts** [comment] 2016-04-18 16:12
Try using the Promise without importing it from `es6-promise`. If you include a module that provides a promise that hasn't been patched by `zone.js`, it will not trigger change detection which would explain why the lifecycle hooks aren't being called.

**Comment by lexon0011** [comment] 2016-04-18 18:00
Thanks!! It looks good, I will test it tomorrow in real project.

**Comment by number213** [comment] 2016-04-27 14:44
Can you please elaborate how you fixed this issue? I'm having it too (but it only occurs when async task takes some time to finish, API calls on the same domain work just fine).
I don't use promises, I just pass function as a callback in third-party lib's methods.

**Comment by number213** [comment] 2016-04-28 10:57
I wrapped the code from the callback in _zone.run_ and now routing works as intended!

**Comment by vsavkin** [comment] 2016-10-04 22:58
It seems the issue was opened before the router rewrite. And it doesn't look like the issue still makes sense. I'm closing it. Please reopen it if you think it still makes sense.

**Closed by vsavkin** 2016-10-04 22:58 UTC
Labels: comp: router
