### ISSUE TITLE
Angular webapp not loading sometimes (randomly) when using Service Worker

### ISSUE THREAD

**Issue by MainaWycliffe** [angular/angular#22657] opened 2018-03-08 17:54 UTC
![capture](https://user-images.githubusercontent.com/12270550/37167459-0f4c6150-2313-11e8-9513-fc6ff9697ecb.PNG)
## I'm submitting a...

[ ] Regression (a behavior that used to work and stopped working in a new release)
[ * ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
When i load my angular webapp (I am using Service Worker), sometimed it loads fine while other times it is just stuck at the start screen. I get the following console messages: 

```
inline.cdc86a5b142808840bf4.bundle.js:1 Uncaught SyntaxError: Unexpected token <
20:40:25.114 polyfills.b663698a884475cdb2a5.bundle.js:1 Uncaught ReferenceError: webpackJsonp is not defined
    at polyfills.b663698a884475cdb2a5.bundle.js:1
20:40:25.115 main.d137c8933e2975d1b7fd.bundle.js:1 Uncaught SyntaxError: Unexpected token <
20:40:29.428 activate Failed to load resource: the server responded with a status of 504 (Gateway Timeout)
```
If i get this error message and then reload the web page, it will reload correctly and work as expect. It is very random and can't seem to nail a pattern.

## Expected behavior
It should load the website every time without having the errors. It works well without service worker. 

## Minimal reproduction of the problem with instructions
The web app is a public web app accessible at [here](https://essaygrid.com)

## What is the motivation / use case for changing the behavior?
I want to use Angular Service worker to improve performance and ability for the web app work offline
and as a Progressive Web App

## Environment
```
Angular CLI: 1.6.8
Node: 9.0.0
OS: win32 x64
Angular: 5.2.7
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker

@angular/cdk: 5.2.3
@angular/cli: 1.6.8
@angular/flex-layout: 5.0.0-beta.13
@angular/material: 5.2.3
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.29
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.8
@schematics/angular: 0.1.17
typescript: 2.6.2
webpack: 3.10.0
```

Browser:
- [ * ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 9.0.0
- Platform:   Windows

**Comment by about-code** [comment] 2018-03-11 09:30
You've provided a link to essaygrid.com for reproduction. Is that the website where the error happens?

**Comment by MainaWycliffe** [comment] 2018-03-11 12:57
Yes, it is. I thought, since its only happening when the site is in production and with an SSL certificate (Only time serviceworker is loaded), then it's better to give you the place where am getting the error as it is a publicly accessible site.

**Comment by about-code** [comment] 2018-03-11 14:05
@MainaWycliffe I am sorry, I can't reproduce the issue. Is the site a personal project such that you may provide a repo with the unbundled sources and setup or is it a work for a customer where you are limited in the technical details you can give?

**Comment by MainaWycliffe** [comment] 2018-03-11 14:22
@about-code It's a customers project so I may not be able to provide every technical details but I can try and provide as much as possible.

**Comment by alxhub** [comment] 2018-04-24 22:49
This looks more like your server occasionally serves an error page. I agree, a standalone reproduction is needed.

**Comment by vicb** [comment] 2018-05-31 22:52
Closing as no repro has been provided

**Closed by vicb** 2018-05-31 22:52 UTC
Labels: comp: service-worker, freq1: low, severity3: broken, state: Need repro, type: bug/fix
