### ISSUE TITLE
Problems with animations when viewContainerRef change Ivy Angular9

### ISSUE THREAD

**Issue by temaisgod** [angular/angular#38871] opened 2020-09-16 15:32 UTC
# 🐞 Problems with animations when viewContainerRef change

### Affected Package
@angular 

### Is this a regression?
works without ivy compilation in Angular v8.
actually **not working with Angular 9.2 and ivy compilation.**

### Description

In a proyect with [DinamicLoaderComponents with AdDirective](https://angular.io/guide/dynamic-component-loader), load a component in container that have a material-sidenav or angular-animations declarations, after deteach this view for save the componentRef to after restore in the same container .

When restore the view the sidenav Animation or animationAngular failed and block it, its necessary change the value of trigger to reset status animation.

## 🔬 Minimal Reproduction
In the stackblitz explample I use one class (ClientComponent) to instance two components with FactoryResolver, save the componentRef, deteach view in container and after restore in the container with .insert() (comment in code).

Reproduction:

1. Load component 1 (click "Load Client 1" Button). 
2. Open sidenav and animation (click "TOOGLE SIDENAV" and animationText).
3. With sidenav open and animation text visible change the view to client2 (click "Load Client 2" Button).
4. Now restore view Client 1 (click "Load Client 1" Button).
    **ERROR ->** Failer animation and sidenav styles its necessary toogle sidenav or animation two times for to working.

Only failed with EnablyIvy option, if disable enableIvy in settings of stackblitz working fine.

https://stackblitz.com/edit/angular-9-bugsanimations?file=src/app/app.component.ts

NOTE:

if i remove alls animations decorators [@---] works too.

## 🔥 Exception or Error
The animations of angular not working correctly.

## 🌍  Your Environment

nodeJs v12

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 9.1.12
Node: 12.18.4
OS: win32 x64

Angular: 9.1.12
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.900.7
@angular-devkit/build-angular      0.900.7
@angular-devkit/build-optimizer    0.900.7
@angular-devkit/build-webpack      0.900.7
@angular-devkit/core               9.0.7
@angular-devkit/schematics         9.1.12
@angular/cdk                       9.2.4
@angular/language-service          9.0.7
@angular/material                  9.2.4
@angular/material-moment-adapter   9.2.4
@ngtools/webpack                   9.0.7
@schematics/angular                9.1.12
@schematics/update                 0.901.12
rxjs                               6.6.3
typescript                         3.7.5
webpack                            4.41.2
</code></pre>

**Comment by jelbourn** [comment] 2020-10-26 21:33
Duplicate of #35270

**Closed by jelbourn** 2020-10-26 21:33 UTC
Labels: comp: animations
