### ISSUE TITLE
Alternative for `ngOnDestroy` to clean up resources

### ISSUE THREAD

**Issue by nikita-starostin** [angular/angular#35903] opened 2020-03-06 10:38 UTC
I like the paradigm to declare variables as close to place of their usage as possible. Often in the `ngOnInit` we set up a subscription, f.e. for fetching data, or maybe some other tasks, that should be cleaned in the `ngOnDestroy`. Following the paradigm, mentioned earlier, it can looks like this

```
ngOnInit() {
    this.subscription = createSubscription();
    return () => cleanUp(this.subscription);
}
```

As you can see that now not need to search for `ngOnDestroy`, I see the clean up code in the place where resources have been created. 

The alternative is to create special builder function, which clean up would be called on destroy
```
// in component
ngOnInit() {
    // createSubscription - callback that creates resource(s), that should me cleaned on component destroy
    // cleanUpSubscription - callback that should be triggered automatically, when component destroyed
    this.subscription = getResource(createSubscription, cleanUpSubscription);
}

// getResource pseudo code
function getResource(init, cleanUp) {
    this._onInitCleanUp = [...(this._onInitCleanUp || []), cleanUp)];
    return init();
}

// in base component constructor
constructor() {
    const cleanUp = () => this._onInitCleanUp && this._onInitCleanUp.forEach(cleanUp => cleanUp());
    const onDestroy = this.ngOnDestroy;
    this.ngOnDestroy = () => (onDestroy && onDestoy()) || cleanUp();
}
```

I like the variant with `getResource`, as I can call `getResource` at any method of the component, and can easily map one-to-one, resource and it is clean up function. Is it make sense to add such function as built in to `@angular/core`?

**Comment by IsaacSomething** [comment] 2020-03-06 11:22
you should look into the `take(1)` https://medium.com/angular-in-depth/the-best-way-to-unsubscribe-rxjs-observable-in-the-angular-applications-d8f9aa42f6a0

**Comment by pkozlowski-opensource** [comment] 2020-03-06 11:35
This sounds very much like a duplicate of the existing issues #23038 and #10185. Closing as duplicate of #23038.

**Closed by pkozlowski-opensource** 2020-03-06 11:35 UTC
