### ISSUE TITLE
Create a ResponseType enum for the HttpClient?

### ISSUE THREAD

**Issue by fireflysemantics** [angular/angular#34318] opened 2019-12-09 21:37 UTC
I changed the name of the issue title.  See design suggestion at end of thread.

https://stackoverflow.com/questions/59256797/replacement-for-responsecontenttype-in-angular-8?noredirect=1#comment104723377_59256797

Something like `HttpClient.ReponseTypeBlob`?

**Comment by Airblader** [comment] 2019-12-09 23:09
As noted on SO: since TypeScript understands string literals and type unions, you have full auto completion support and protection against typos. There's no benefit to exposing constants for this, it just introduces an indirection.

**Comment by fireflysemantics** [comment] 2019-12-09 23:43
Generally I think static constants complement the enumerated type shown above ... so we could do const responseType: 'json' | 'arraybuffer' | 'blob' | 'text' = HttpClient.ResponseTypeJson;  If we want to change json to array buffer we get autocomplete assist which is nice.

**Comment by Airblader** [comment] 2019-12-09 23:45
Again, you don't need constants to get auto completion. String literals can already do that.

**Comment by fireflysemantics** [comment] 2019-12-09 23:48
I tried getting auto completion for responseType in this demo:

https://stackblitz.com/edit/angular-downloading-images-cross-url?file=src/app/post.component.ts

Deleted 'text' in 

```
responseType: 'text'

```

Then hit `ctrl+space` .  I don't see auto complete option that will render 'text' for example ... Can you show me ?

**Comment by mstawick** [comment] 2019-12-11 10:51
@fireflysemantics 
Just use a decent IDE:

![Screenshot_20191211_115111](https://user-images.githubusercontent.com/1216844/70615360-8a146880-1c0c-11ea-86d4-6c46dfd14f72.png)

**Comment by fireflysemantics** [comment] 2019-12-13 14:21
Looks like VSCode.  The thing is it also looks like you have to know that you need to put the cursor inside the quote.  That's one more learning step on top of the 10,000 concepts we need to master in order to get comfortable in VSCode, Angular, RxJS, CSS, html, ... building, deploying, unit testing, integration testing, designing, and refactoring code.

**Comment by Airblader** [comment] 2019-12-13 14:26
I don't know for VSCode but in IntelliJ you don't need to put the cursor inside quotes. Either way that's something to be fixed in the IDE then. The point stands that from TS perspective all the information is there and bad tooling doesn't justify useless APIs.

**Comment by fireflysemantics** [comment] 2019-12-13 14:31
As developers we are used to grabbing constants off of relevant API classes or instances.  It's a very common pattern.  That's what makes having these constants available as static members useful.

**Comment by Airblader** [comment] 2019-12-13 14:42
That's only true for developers who haven't worked with languages that support string literal types, which TS does.

**Comment by fireflysemantics** [comment] 2019-12-13 14:49
Angular had `ResponseContentType`.  That was fine.  It worked in almost all environments and fit the symmetry that most developers are used to.

Personally I agree with you that the current implementation is slightly more lightweight and elegant, but given the poor support that most tooling has for it I think it should have been introduced in version 20 of Angular.

**Comment by Airblader** [comment] 2019-12-13 14:50
"But Java does this" isn't a good argument because 1) Java doesn't have string literal types and 2) TS isn't Java. We could start throwing languages at each other for comparison, but ultimately TS isn't any of them. Literal types exist, they are discoverable and they are statically checked.

**Comment by Airblader** [comment] 2019-12-13 14:50
"But Java does this" isn't a good argument because 1) Java doesn't have string literal types and 2) TS isn't Java. We could start throwing languages at each other for comparison, but ultimately TS isn't any of them. Literal types exist, they are discoverable and they are statically checked.

**Comment by fireflysemantics** [comment] 2019-12-13 14:59
It's not that Java does it ... it's that its a common pattern in every language.  For example here's an article where the author creates date time constants:

https://loiane.com/2017/08/angular-tips-formatting-dates-with-a-custom-date-pipe-dd-mm-yyyy/

```
‘medium’: equivalent to ‘yMMMdjms’ (e.g. Sep 3, 2010, 12:05:08 PM for en-US)
‘short’: equivalent to ‘yMdjm’ (e.g. 9/3/2010, 12:05 PM for en-US)
‘fullDate’: equivalent to ‘yMMMMEEEEd’ (e.g. Friday, September 3, 2010 for en-US)
‘longDate’: equivalent to ‘yMMMMd’ (e.g. September 3, 2010 for en-US)
‘mediumDate’: equivalent to ‘yMMMd’ (e.g. Sep 3, 2010 for en-US)
‘shortDate’: equivalent to ‘yMd’ (e.g. 9/3/2010 for en-US)
‘mediumTime’: equivalent to ‘jms’ (e.g. 12:05:08 PM for en-US)
‘shortTime’: equivalent to ‘jm’ (e.g. 12:05 PM for en-US)

```
We are used to looking for these types of things on a context class.  Javascript Numbers does the same thing:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Numbers_and_dates

It's what we look for and work with 95% of the time.  Breaking this symmetry in a few edge cases is not worth it.


```

Number.POSITIVE_INFINITY | Special positive infinite value; returned on overflow
-- | --
Number.EPSILON | Difference between 1 and the smallest value greater than 1 that can be represented as a Number (2.220446049250313e-16)
Number.MIN_SAFE_INTEGER | Minimum safe integer in JavaScript (−253 + 1, or −9007199254740991)
Number.MAX_SAFE_INTEGER | Maximum safe integer in JavaScript (+253 − 1, or +9007199254740991)


```

**Comment by fireflysemantics** [comment] 2019-12-13 14:59
Constants are also a good place to put documentation.

**Comment by Airblader** [comment] 2019-12-13 15:10
IMHO you are trapped in the idea that the function accepts any string and that string constants can help avoid invalid input. But that isn't the case — it's a string literal union type and any invalid argument is immediately rejected by the compiler.

(!) This is *stronger* than any of the examples you have mentioned. 

> it's that its a common pattern in every language

No, it is common in languages where the type system doesn't support a better way. 

Also the closest thing would be enums, not string constants, and in such languages enums would usually be the best practice over accepting arbitrary strings which leads only to runtime errors. 

> Javascript Numbers does the same thing:

These constants are fundamentally different because they encapsulate a specific value in a broad type. They actually add value to the user because using a "wrong" value for, say, INFINITY would go unnoticed by the type system. 

But this simply isn't true in this situation. The type system already knows the exact allowed values. It's a "lightweight enum".

---

A novice user will usually look at the function signature. The signature currently lists exactly the allowed values (it isn't an enum or string!), so why wouldn't the user just type in of those values? Where would they learn about string constants representing the very same value and why should they go through this indirection? 

If the signature accepted "string", I'd agree with you. But it doesn't. It's already fully typed and discoverable.

Finally, your argument of symmetry / consistency reminds me of a quote of a Google Guava engineer, Kevin Bourrillion:

> Also, your notion of consistency is deeply misguided. We use consistency in how we present important functionality, but we never use it to justify adding worthless functionality, and you shouldn't in your own libraries either!

— http://code.google.com/p/google-collections/issues/detail?id=217

**Comment by Airblader** [comment] 2019-12-13 15:15
(The direct equivalent to JS numbers would be that you want a constant for every single number in existence, which is obviously nonsense. We're dealing with a discrete, finite and small set of values here)

**Comment by fireflysemantics** [comment] 2019-12-13 15:26
@Airblader .... dude ... Just look at the MDN API documentation ...

Or `Math.PI` ..

Not every number needs a constant.  Just the special ones.

**Comment by Airblader** [comment] 2019-12-13 15:28
Here's another example using numeric literals:

```
function setHour(timestamp: Date, hour: 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12): void {
    // ... 
} 
```

Would it really be useful to have `Hour.ZERO`, `Hour.ONE`, ...? I don't think so.

> Not every number needs a constant. Just the special ones.

Exactly my point. And in a discrete finite set of five values type checked by the compiler no value is special and needs a constant.

**Comment by fireflysemantics** [comment] 2019-12-13 15:33
It's a fair point.

Now we just have to get used to typing ` ''` and then putting the cursor between the `''` and then doing autocomplete, in addition to using constants in most cases like with `Math.PI`.

One more thing to learn that could easily not be learned, because in most cases we'll still want the constants, as in the `Math.PI` case.

**Comment by Airblader** [comment] 2019-12-13 15:36
1. No, you don't need to out the cursor between quotes. If you do, open a bug against the IDE.
2. You can just look at the documentation of the method signature. It tells you all possible values. 
3. Having constants for each value wouldn't help at all. How would a user even know that these exist? 
4.  Even if somehow they did know about their existence, they'd still first have to type out all of "HttpClient.ResponseType." to get auto completion. How is this better than typing `''` even if it was necessary?

**Comment by fireflysemantics** [comment] 2019-12-13 15:39
I would have kept `ReponseContentTypes`.

I agree with you that the implementation is "Slightly" more optimal in this one case, but it breaks the Symmetry with `Math.PI`.

**Comment by Airblader** [comment] 2019-12-13 15:43
Would you mind answering my questions above? I hope it would help make you understand what I mean.

**Comment by fireflysemantics** [comment] 2019-12-13 15:47
I've already answered them.

All of us are used to looking for things like `Numbers.MAX_VALUE` or `Math.PI`.  We do this all the time in our programming.  We naturally reach for it.  

Most programmers want to stick with what's natural for them.  A lot of people prefer React because they "Feel" like it's a lesser learning curve.  Anything that can be done to lessen the Angular learning curve helps.

I you got in your car tomorrow and found out that I moved the start button to the left side and that you can press it, but you have to wait for an update from the manufacturer software update before it actually works you'ed be upset.  

Of coarse I have a simple solution.  Just rent a car meanwhile.

**Comment by Airblader** [comment] 2019-12-13 15:49
But how would you go about finding where these constants live in the first place? The auto completion of the method signature wouldn't tell you since it's not an enum. So where would you find where these constants are defined?

**Comment by fireflysemantics** [comment] 2019-12-13 15:50
They were defined on `ReponseContentTypes`.  That's could have easily been an Enum.

**Comment by fireflysemantics** [comment] 2019-12-13 15:51
If we want to define a variable with with 2*PI we just do:

```
2*Math.PI.
```

**Comment by Airblader** [comment] 2019-12-13 15:51
But that still doesn't explain how the user would find out that this exists or what it is called. Imagine a novice developer sitting in front of their computer and typing out the method call, stumbling across the problem of not knowing what to enter. What are they going to do next?

**Comment by fireflysemantics** [comment] 2019-12-13 16:01
Go back to the old signature for `HttpClient.get()`.

Thus we have:

```
this.http.get(`https://thestuff`, { responseType: ResponseType.TEXT})}
```
or 

```
this.http.get(`https://thestuff`,ResponseType.TEXT)}
```

Latter better.

**Comment by Airblader** [comment] 2019-12-13 16:14
Again, though, how does the user know that "ResponseType" exists and what it is called?

**Comment by fireflysemantics** [comment] 2019-12-13 16:15
Because the second argument to `get` is `ReponseType`:

```
export enum ReponseType {
....
}

```

**Comment by Airblader** [comment] 2019-12-13 16:17
So the user looks at the signature of the method? But then why is it better than if the signature tells them the list of string literals they can use? It's the same thing.

**Comment by fireflysemantics** [comment] 2019-12-13 16:18
No.

It's shorter and more efficient.  We no longer have to type `{reponseType}` and worry about the tooling issue.

**Comment by fireflysemantics** [comment] 2019-12-13 16:18
It also has symmetry with `Math.PI`.

**Comment by Airblader** [comment] 2019-12-13 16:19
How is `ResponseType.JSON` shorter than `'json'`? And by which metric do you measure "more efficient"? It's more characters to type.

**Comment by fireflysemantics** [comment] 2019-12-13 16:20
You're leaving out the `{responseType}` part ...

**Comment by fireflysemantics** [comment] 2019-12-13 16:20
Just type `Re` ... autocomplete ... select `JSON`.

**Comment by Airblader** [comment] 2019-12-13 16:21
But suggesting to change that has nothing to do with constants for string literals (which is what this issue is about). That's just the entire signature of the method and you're suggesting a breaking change on it.

**Comment by fireflysemantics** [comment] 2019-12-13 16:24
And then stick with that pattern through out Angular.

**Comment by Airblader** [comment] 2019-12-13 16:24
But this has nothing to do with what this issue is about. Making the second argument am object vs the response type is a whole other topic.

**Comment by fireflysemantics** [comment] 2019-12-13 16:26
It's a better design.  Lets just fix it and make it a common pattern.

**Comment by Airblader** [comment] 2019-12-13 16:45
What about all the other options apart from response type? You'd have a method with ten or so arguments. Passing option objects is a totally typical pattern and more intuitive because it's more descriptive and easier to write. 

In any case it still has nothing to do with this issue so I won't further discuss that here. You should raise a separate issue for that, but I doubt that this will be changed.

**Comment by fireflysemantics** [comment] 2019-12-13 16:54
I just changed the title of the issue.  At least now the full context of the discussion is available.

**Comment by Airblader** [comment] 2019-12-13 16:55
Not really, the issue is about exposing some type of constants for the values, not about changing the signature of all HttpClient methods. But I think I'll sign off here since everything I have to say has been said.

**Comment by fireflysemantics** [comment] 2019-12-13 16:57
Great conversation.  Thanks for engaging!

**Comment by fireflysemantics** [comment] 2019-12-17 00:54
The suggestion will also make the feature symmetric with:
```
  changeDetection: ChangeDetectionStrategy.OnPush

```

**Comment by alxhub** [comment] 2020-01-31 01:13
FWIW, I was the one who made this decision when designing the `HttpClient` API. At the time, the goal was to have an API which allowed good type inference of the return type, and didn't require too much boilerplate. The type signatures of `HttpClient` methods were already pretty complex, so adding additional requirements to import enums in order to use them seemed unnecessary.

As it is, neither string constants nor enums offer _great_ code completion experiences in VSCode today.

String constants suffer from the problem that the IDE only offers candidates from the first matching signature, and doesn't offer all options as a result.

Enums suffer from a much worse problem: the IDE will actually offer to complete with the enum's _value_, which doesn't actually satisfy the required type and will produce a type error. This is the case whether string or numeric enums are used.

Neither string constants nor enums automatically infer narrowed types when used in an object literal, either, which is unfortunate:

```typescript
const options = {
  responseType: 'json',
};
http.get('/url', options); // type error - options.responseType is `string`, not `'json'`.
```

Doing something like this requires using `'json' as const`. Enums have the same problem.

I don't believe we're going to change this in the foreseeable future, for a few reasons. 

1) it would be a big migration, if not a breaking change, for existing code.
2) the enum completion experience is worse than the string constant experience in Language Service IDEs today.
3) it's possible for users who want to use enums to define their own enum constants to use.
4) there are other design possibilities which could have even more impact if a breaking change is to be adopted.

**Closed by alxhub** 2020-01-31 01:13 UTC
Labels: comp: common/http, type: feature
