### ISSUE TITLE
directive with "[on-*]" selector

### ISSUE THREAD

**Issue by cexbrayat** [angular/angular#3883] opened 2015-08-28 09:30 UTC
Upgrading my app from alpha34 to alpha35, one directive I had with a selector `[on-init]` was not working anymore. I realize it must be conflicting in the parser with the canonical syntax for events, but it was working until alpha35 and the error we have now is not really explicit:

    TypeError: Cannot set property 'lastInBinding' of undefined
    at Function._ConvertAstIntoProtoRecords.create (http://me:8080/jspm_packages/npm/angular2@2.0.0-alpha.35/src/change_detection/proto_change_detector.js:97:39)
    at http://me:8080/jspm_packages/npm/angular2@2.0.0-alpha.35/src/change_detection/proto_change_detector.js:35:47

Maybe the error could be more explicit and the doc warns about not using these prefixes (`on`, `var`, `bind`) in attribute selectors?

**Comment by pkozlowski-opensource** [comment] 2015-08-28 10:24
@cexbrayat could you please share a plunker with a minimal reproduce scenario? I can't reproduce it with a simple scenario: http://plnkr.co/edit/pNU1ZgP5LBY346RNsfI9?p=preview

**Comment by cexbrayat** [comment] 2015-08-28 10:31
If you check the console, you should see the error (I see it with your plunk).
My use case was even minimal http://plnkr.co/edit/HSHL9oiGk2C5U3MzOW3Z?p=preview
Check the console, see the error, change the selector to `[init]`, the error disappeared.

**Comment by pkozlowski-opensource** [comment] 2015-08-28 12:15
In fact this has nothing to do with directives / selectors. The error you are seeing comes from from using an event handler with an empty event handling expression. Minimal reproduction here: http://plnkr.co/edit/CyRqhNiUGceEhn9jU4fu?p=preview

I believe that we've got an issue for this already, let me find one.

**Comment by pkozlowski-opensource** [comment] 2015-08-28 12:18
OK, so this is duplicate of https://github.com/angular/angular/issues/3754

**Closed by pkozlowski-opensource** 2015-08-28 12:18 UTC
