### ISSUE TITLE
Bug in firefox

### ISSUE THREAD

**Issue by AdamTeodoro** [angular/angular#39874] opened 2020-11-28 20:58 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....
I dont know

### Is this a regression?
Yes, in angular 9 i NOT have encountry the bug;
In the angular 10, i don't know!
I have updated the project of angular 9 directly for  angular 11

 Yes, the previous version in which this bug was not present was: ....

### Description
The bug has ocurred in the firefox, if you use the configuration for never armazenate the history or enter in private mode!

 A clear and concise description of the problem...

## 🔬 Minimal Reproduction

 https://stackblitz.com/...

Requirements:
Use angular version:
---------------------------------------------------------
@angular-devkit/architect       0.1100.2
@angular/cdk                    11.0.1
@angular/fire                   6.1.2
@angular/material               11.0.1
@schematics/angular             11.0.2
@schematics/update              0.1100.2
rxjs                            6.6.3
typescript                      4.0.5

Use firefox version: latest

How to reproduce:
1 - Open the firefox;
2 - Go to menu lateral in top and right;
3 - Select the options;
4 - In left select privacity and security;
5 - Use an configuration for not armazenate historic and cookies;
5.1 - Scroll to history and select option for never armazenate the historic;
5.2 - Use Private mode Ctrl + shift + P;
6 - Open your angular project and execute ng serve;
7 - Go to console and look error

## 🔥 Exception or Error

<pre><code>

ERROR:
" Uncaught Error: InvalidStateError: A mutation operation was attempted on a database that did not allow mutations.
"

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___ 
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | | 
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | | 
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 11.0.2
Node: 14.15.1
OS: win32 x64

Angular: 11.0.2
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.2
@angular/cdk                    11.0.1
@angular/fire                   6.1.2
@angular/material               11.0.1
@schematics/angular             11.0.2
@schematics/update              0.1100.2
rxjs                            6.6.3
typescript                      4.0.5

And firefox version latest

</code></pre>

**Anything else relevant?**

**Comment by lazarljubenovic** [comment] 2020-11-30 09:19
What does “armazenate” mean?

> InvalidStateError: A mutation operation was attempted on a database that did not allow mutations.

This looks like an IndexedDB error. I don't think Angular uses that internally. Can you post a reproduction?

**Comment by AndrewKushnir** [comment] 2020-11-30 18:17
Based on the original description it looks like the problem was not caused by Angular (there is no code that produces the mentioned error) and having no reproduction makes this report non-actionable (i.e. we can not perform an investigation). I'm closing this ticket for now, feel free to create a new one if the problem still exists and there is a repro that demonstrates the issue (and describe how it's related to Angular and doesn't happen in plain JS/HTML). Thank you.

**Closed by AndrewKushnir** 2020-11-30 18:17 UTC
