### ISSUE TITLE
`ng build --prod` Failure: Cannot read property 'type' of undefined (NgOnChangesFeature)

### ISSUE THREAD

**Issue by kennytrytek-wf** [angular/angular#36042] opened 2020-03-12 19:11 UTC
# 🐞 bug report

### Affected Package
Unknown

### Is this a regression?
Yes, it works in Angular 9.0.5.

### Description
An error is encountered doing `yes N | npm install && ng build --prod` on our project.

## 🔬 Minimal Reproduction
Unknown. The component referenced in the stack trace looks similar to this:
```
import { Component, Input, OnChanges, OnDestroy } from '@angular/core';
import { Subscription, timer } from 'rxjs';

@Component({
  selector: 'wdev-duration',
  templateUrl: './component.html',
  styleUrls: ['./component.scss']
})
export class DurationComponent implements OnChanges, OnDestroy {
  @Input() start: string;
  @Input() end: string;
  duration = 0;
  timerSub: Subscription;

  ngOnChanges() {
    console.log('change');
  }

  ngOnDestroy() {
    this.stopTimer();
  }

  stopTimer() {
    if (this.timerSub) {
      this.timerSub.unsubscribe();
    }
  }
}
```
It is packaged as part of a library called `wdev-components` and consumed by other projects by requiring it in the consuming projects' `package.json`.

## 🔥 Exception or Error
```
An error was thrown in afterAll
TypeError: Cannot read property 'type' of undefined
b'at \xc9\xb5\xc9\xb5NgOnChangesFeature (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:26829:1)'
at Module../node_modules/wdev-components/fesm2015/wdev-components.js (http://localhost:9876/_karma_webpack_/node_modules/wdev-components/fesm2015/wdev-components.js:372:174)
at __webpack_require__ (http://localhost:9876/_karma_webpack_/webpack/bootstrap:79:1)
at Module../src/app/app.component.spec.ts (http://localhost:9876/_karma_webpack_/main.js:825:73)
at __webpack_require__ (http://localhost:9876/_karma_webpack_/webpack/bootstrap:79:1)
at webpackContext (http://localhost:9876/_karma_webpack_/src sync \.spec\.ts$:40:1)
at Array.map (<anonymous>)
at Module../src/test.ts (http://localhost:9876/_karma_webpack_/main.js:24329:16)
at __webpack_require__ (http://localhost:9876/_karma_webpack_/webpack/bootstrap:79:1)
at checkDeferredModules (http://localhost:9876/_karma_webpack_/webpack/bootstrap:45:1)
```

Looking at the generated `.js` file referenced in the stack trace, this is the line that is failing at column 174:
```
DurationComponent.ɵcmp = ɵɵdefineComponent({ type: DurationComponent, selectors: [["wdev-duration"]], inputs: { start: "start", end: "end" }, features: [ɵɵNgOnChangesFeature()], decls: 3, vars: 3, template: function DurationComponent_Template(rf, ctx) { if (rf & 1) {
```

## 🌍  Your Environment

**Angular Version:**
```
Angular CLI: 9.0.6
Node: 10.16.3
OS: linux x64
Angular: 9.0.6
Ivy Workspace: Yes
Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.6
@angular-devkit/build-angular     0.900.6
@angular-devkit/build-optimizer   0.900.6
@angular-devkit/build-webpack     0.900.6
@angular-devkit/core              9.0.6
@angular-devkit/schematics        9.0.6
@angular/cdk                      9.1.2
@angular/material                 9.1.2
@ngtools/webpack                  9.0.6
@schematics/angular               9.0.6
@schematics/update                0.900.6
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
```

**Comment by JoostK** [comment] 2020-03-12 19:18
Duplicate of #36020, please find more info there.

**Closed by JoostK** 2020-03-12 19:18 UTC

**Comment by kennytrytek-wf** [comment] 2020-03-12 20:08
Confirmed that rebuilding the library using `ng build --prod` and Angular 9.0.6 resolved the issue.
