### ISSUE TITLE
data-attr is not used if you specify in @Input('data-attr')

### ISSUE THREAD

**Issue by splincode** [angular/angular#24924] opened 2018-07-17 12:00 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior

```ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'hello',
  template: `
    <h2> name = {{name}} </h2>
    <h2> data-id = {{dataId}} </h2>
  `,
  styles: [`h1 { font-family: Lato; }`]
})
export class HelloComponent  {
  @Input('name') name: string;
  @Input('data-id') dataId: string;
}
```

If I use the name attribute, then everything works, but if I usage data-id he does not throw on template

```html
---------------------------------
              |                 |
          it's work        does not work
<hello name="name-value" data-id="data-id-value"></hello>
```

## Expected behavior

I want the angular to use all the props which we use

```ts
@Input('my-attribute-name') myAttributeName;
```

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-auy8hm?file=src%2Fapp%2Fapp.component.html

**Comment by trotyl** [comment] 2018-07-17 13:03
Duplicate of https://github.com/angular/angular/issues/19054, https://github.com/angular/angular/issues/24726. `data-` prefix will be stripped just like in AngularJS.

**Comment by vicb** [comment] 2018-07-17 14:48
Closing as work as expected - thanks @trotyl for the details

**Closed by vicb** 2018-07-17 14:48 UTC
