### ISSUE TITLE
routerLink with absolute path and round brackets parsed incorrectly

### ISSUE THREAD

**Issue by DmitriyIvanko** [angular/angular#32718] opened 2019-09-17 15:47 UTC
# 🐞 bug report

### Affected Package

 @angular/router

### Description
 
1) I have routerLInk (absolute path with secondary routes):

`<a routerLink="/user/project/01/scenario-type/gfa/scenario/27/data/layout/open/(main:panel/map//footer:data-table/CustomerData_GFA_NO_SIM_TO_FULL//validation:validation-table/error)">LINK</a>`

2) but routerLink direcive parsed round brackets to '%28' and '%29' respectively: 
http://prntscr.com/p7cejg
3) BUT if i write:
`<a href="/user/project/01/scenario-type/gfa/scenario/27/data/layout/open/(main:panel/map//footer:data-table/CustomerData_GFA_NO_SIM_TO_FULL//validation:validation-table/error)">LINK</a>`
Everything works fine.

 https://stackblitz.com/...

## 🌍  Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 8.2.2
Node: 10.16.3
OS: win32 x64
Angular: 8.2.6
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.4
@angular-devkit/build-angular     0.803.4
@angular-devkit/build-optimizer   0.803.4
@angular-devkit/build-webpack     0.803.4
@angular-devkit/core              8.0.0
@angular-devkit/schematics        8.0.0
@angular/cli                      8.2.2
@ngtools/webpack                  8.3.4
@schematics/angular               8.0.0
@schematics/update                0.802.2
rxjs                              6.5.3
typescript                        3.4.5
webpack                           4.39.2

</code></pre>

**Anything else relevant?**

I try use routerLink relative navigation but FROM secondary route and can't configurate it:
routerLink with multiple routerLink=['../../../', { outlets: { foobar: ['table', '25']  } } is not worked.
That is why i try use absolute navigation;

Thank you for any help.

**Comment by HalitTalha** [comment] 2019-10-18 13:45
I believe it is the expected behavior. Seems like Angular is encoding the URL as per the URL specifications before resolving the targeted resource. Since it is a special character it is correctly being encoded.

**Comment by DmitriyIvanko** [comment] 2019-10-18 14:47
@HalitTalha  can your tell me how to fix it?

**Comment by HalitTalha** [comment] 2019-10-21 06:15
@DmitriyIvanko could you provide a stackblitz?

**Comment by atscott** [comment] 2019-12-05 23:59
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template, including a reproduction.

**Closed by atscott** 2019-12-05 23:59 UTC
Labels: comp: router
