### ISSUE TITLE
Bug: custom value accessor is not beign provided

### ISSUE THREAD

**Issue by vagarenko** [angular/angular#9568] opened 2016-06-24 11:56 UTC
With new forms (0.1.1) this code stoped working:
https://plnkr.co/edit/QB1rsCUTbjc9Dh76iVgz?p=preview

it fails with:

    Error in ./App class App - inline template:9:18
    ORIGINAL EXCEPTION: No value accessor for ''

This code worked fine with old forms, see previous versions on plunker.

Update:
Debugging shows that constructor of NgModel directive is not recieving valueAccessors parameter:
App.template.js:79:

     self._NgModel_14_4 = new jit_NgModel5(null,null,null);

**Comment by zihel** [comment] 2016-06-24 14:53
Looks like it's working to me. The problem is that you need to bootstrap your app properly to use the forms as per the deprecation strategy.
```ts
import { disableDeprecatedForms, provideForms } from '@angular/forms';

bootstrap(App, [
  disableDeprecatedForms(),
  provideForms()
])
```

**Comment by kara** [comment] 2016-06-24 15:46
Yes, you do need to add the extra code to your bootstrapping to use the new forms module.   If you update your bootstrap file with the code @zihel provided above, it should work: 

https://plnkr.co/edit/9XogrULe6atg4WMOCiqS?p=preview

Closing, as this doesn't seem to be a bug.  Please re-open if I'm missing something!

**Closed by kara** 2016-06-24 15:46 UTC
Labels: comp: forms
