### ISSUE TITLE
Error thrown in ngOnInit() results in two separate component templates to be shown

### ISSUE THREAD

**Issue by Zoomink** [angular/angular#19218] opened 2017-09-15 12:50 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Throw an error in a <code>ngOnInit()</code> method, catch in a custom <code>ErrorHandler</code>, and navigate to an other route will show dual <code>ng-component</code>. It will show both the template for the component the error was thrown in, and also the template for the component that the error handler navigated to.

This happens when either BrowserAnimationsModule or NoopAnimationsModule is imported. Leaving them out will not cause the problem.

## Expected behavior
Show only the template for the component that the error handler navigated to when using either BrowserAnimationsModule or NoopAnimationsModule.

## Minimal reproduction of the problem with instructions

Plnkr: http://plnkr.co/edit/2MupmzIEqaAsbaRsyNLy?p=preview

## Environment

<pre><code>
Angular version: 4.3.6

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v8.4.0  
- Platform:  Linux

Others:

</code></pre>

**Comment by zoubarevm** [comment] 2017-09-19 18:34
I've also had something similar happen. In my case navigating to other routes still works (after the **ngOnInit** error) but it would always load the additional components in the **router-outlet** without disposing the old ones.

**Comment by Agrumas** [comment] 2017-09-21 09:25
This is such annoying bug, I couldn't believe that BrowserAnimationsModule module causes this. 
Here is the example without router: https://plnkr.co/edit/DUW1tDdeRZgKaBdLu1nN?p=preview

**Comment by Agrumas** [comment] 2017-09-21 09:30
This is such annoying bug, I couldn't believe that BrowserAnimationsModule module causes this. 
Here is the example without router: https://plnkr.co/edit/DUW1tDdeRZgKaBdLu1nN?p=preview

Btw, this is duplicate of #19218

**Comment by Tonio31** [comment] 2017-10-24 09:31
Did anyone found a solution, I experienced exactly the same issue.

I throw an exception during ngOninit() of a component because of missing component Input
I have a custom errorHandler that redirect the user to the error Page.

Both template form the original component and the error page are rendered


I'm using Angular version 4.4.5

**Comment by jasonaden** [comment] 2017-11-30 21:17
This might be fixed by #20719.

**Comment by chuckjaz** [comment] 2017-12-12 23:36
@Zoomink Can you verify this is still and issue in 5.1?

**Comment by Zoomink** [comment] 2017-12-13 10:12
Hi, we're upgrading to 5.x on Monday next week. Will check it out then and come back.

**Comment by vicb** [comment] 2018-01-11 23:24
Closing as no update. Please open a new issue if you still see the pb.

**Closed by vicb** 2018-01-11 23:24 UTC
Labels: comp: core & compiler, flag: can be closed?, type: bug
