### ISSUE TITLE
Angular 8 request from authority reply causes redirect to root

### ISSUE THREAD

**Issue by alvipeo** [angular/angular#33610] opened 2019-11-06 02:51 UTC
I'm sorry but I think this is a bug as I've been trying to fix this for days now.

This is Angular 8.2.13. The repo is here - [https://github.com/alvipeo/ng8-callback](https://github.com/alvipeo/ng8-callback).

In two words - I need Oauth 2.0 implicit flow auth and I use Azure B2C for that. When user logs in he's redirected to azure and then redirected back to my app with this request:

>> https://localhost:4200/run#state=dc81c410-4cbd-4218-bc78-9c5b5e9bebe5&client_info={...}

Since `/run#state` doesn't work I rewrite it to `/run/state` using router events subscription. And then I have the `:state` defined in my routes. So it should just work.

I can open the page successfully with the rewritten Url in a browser:
>> https://localhost:4200/run/state=f5f2c20f-ed72-4631-b834-80bf60aa6cd7&client_info={...}

But when this same request comes from authority angular router redirects user to the root (`/`)!
And it does seem to me as a bug. If not, no one could tell me what's wrong with my code.

More details on the problem - https://stackoverflow.com/q/58716466/2896495.

**Comment by IgorMinar** [comment] 2019-11-06 16:51
Have you considered setting up a `/run` route and extracting the auth values from the url fragment?

Your current attempt at rewriting the url to reformat it in a way that the router can easily match it seems unnecessary.

I looked at your repro, but there is still way too much stuff going on in there for us to be able to pinpoint the root cause.

**Comment by alvipeo** [comment] 2019-11-06 19:56
@IgorMinar thank you for the reply!

I tried having just `/run` route but it never lands there with `#state=...` (it seems). So either I don't know how to do it or it doesn't work. But I'd be glad to try, please give me a hint or a link on how to do this.

I removes all the unnecessary code, there's nothing else to remove. Please [see the repo](https://github.com/alvipeo/ng8-callback).

**Comment by IgorMinar** [comment] 2019-11-08 19:54
have you tried removing all the custom rewriting and redirection (e.g. https://github.com/alvipeo/ng8-callback/blob/e73ff4f2214e7e4acdbd8c78a08e19c8a613f289/src/app/app.component.ts#L15-L20) and in the `/run` component access the fragment via [`Location#path(true)`](https://angular.io/api/common/Location#path )?

**Comment by alvipeo** [comment] 2019-11-12 20:15
Not sure what should I do here. I removed all the rewriting. So I have the only `/run` route with no children. When the callback request issued by authority Angular handles this `/route` route but it almost instantly starts redirecting to root.

One idea is since I have to register a redirect callback with **MSAL**:
`this.msalObj.handleRedirectCallback(this.authProcessed);`

the redirect to root might be caused by this handler. But I have no idea of how valid this is. @jasonnutter, can you help maybe?

**Comment by jasonnutter** [comment] 2019-12-05 23:01
@alvipeo Sorry for the delay in responding. I don't think `msal.handleRedirectCallback` would cause that.

**Comment by alvipeo** [comment] 2019-12-09 23:14
ok, as a temporary workaround I just do `navigate(['run'])` in the AppComponent when user is already authenticated. This redirects authenticated user to the guarded pages.

But here's how network requests look anyway (notice it gets cancelled first time for some reason):
![network requests](https://inus.azureedge.net/pub/angular%20callback%20trace.png)

**Comment by atscott** [comment] 2020-04-23 22:47
Thanks for reporting this issue. It looks like the reproduction is no longer available so I'm going to close this issue as there's no way to investigate it at this point.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template, including a minimal reproduction using StackBlitz or GitHub.

**Closed by atscott** 2020-04-23 22:47 UTC
Labels: comp: router, state: Needs repro
