### ISSUE TITLE
ng 11 & lib build withy Ivy

### ISSUE THREAD

**Issue by sysmat** [angular/angular#39649] opened 2020-11-12 13:15 UTC
Is there any progress on that or some  docs?

**Comment by petebacondarwin** [comment] 2020-11-12 13:16
I assume you are referring to being able to publish libraries that are not compiled via ViewEngine?

**Comment by sysmat** [comment] 2020-11-12 13:18
In general, if I publish lib with ng and then use it in ng projcet

**Comment by petebacondarwin** [comment] 2020-11-12 13:23
I am still not entirely sure what you are asking.

Consuming libraries in ivy applications is already working - and has been since v9.

Regarding publishing libraries. We do not support Ivy compiled libraries published to npm. Instead they should be compiled via ViewEngine before publishing - `ng build --prod`.

The CLI will automatically transform ViewEngine libraries to Ivy when consuming them in an application project.

**Comment by meriturva** [comment] 2020-11-13 09:38
We use library since angular 2 (custom build pipeline based on gulp and rollup) and after angular 9 we have removed it in favour of angular cli one.

**Comment by nayfin** [comment] 2020-11-13 18:41
@petebacondarwin is there an ETA on when we can expect to be able to publish Ivy compiled libs to package repo?

**Comment by petebacondarwin** [comment] 2020-11-13 19:06
We are tentatively aiming for 11.1.0... :-)

**Comment by diminutivesloop** [comment] 2021-02-19 14:33
@petebacondarwin Any updates? From the changelog it looks like this didn't ship in 11.1.0.

**Comment by petebacondarwin** [comment] 2021-02-19 14:40
The partial compilation mode and linker have been implemented and there is an alpha release available in 11.2.0.

You can create a partially compiled ivy library simply by changing `tsconfig.prod.json`: replace `"ivyEnabled": false` with `"compilationMode": "partial"`.

When you then build an application that depends upon this library, using the CLI, the library will be automatically "linked" (compiling the partial compiled code to fully compiled code) at the point when the application is being bundled.

**We are tweaking the partial compilation output right now so things will change. But you are welcome to go and give it a try - just don't actually publish anything to npm yet.** We hope that we can encourage people to start publishing using this format in v12 - but don't hold us to that :-)

**Comment by sahilbabbar** [comment] 2021-03-02 09:06
@petebacondarwin I am using Angular v11.0.6 and trying to build an internal enterprise library project with `enableIvy: true` and getting the following error, which looks like an **internal Angular** error:
```
------------------------------------------------------------------------------
Building entry point '@ericsson/multimediation'
------------------------------------------------------------------------------
- Compiling TypeScript sources through NGC
× Compiling TypeScript sources through NGC
ERROR: Cannot read property 'visit' of undefined
An unhandled exception occurred: Cannot read property 'visit' of undefined
```

After reading your this reply, above: 
>Regarding publishing libraries. We do not support Ivy compiled libraries published to npm. Instead they should be compiled via ViewEngine before publishing - ng build --prod.


-------------


Should I conclude that I need to wait a little before Angular **fully supports and stablises** building and publishing libraries built with Ivy?

*OR*

Angular v11 library projects can be successfully built with Ivy enabled?

**Comment by petebacondarwin** [comment] 2021-03-02 11:33
If you are building with `"enableIvy": true` and not setting partial compilation mode then this has nothing to do with the linker.
Please feel free to put together a reproduction and create a new issue that we can then track and investigate your problem.

**Comment by JoostK** [comment] 2021-03-02 12:27
@sahilbabbar are you using the exact same version for both `@angular/compiler` and `@angular/compiler-cli`?

**Comment by sahilbabbar** [comment] 2021-03-02 12:37
@JoostK both are at `v11.0.6`.

**Comment by sahilbabbar** [comment] 2021-03-02 12:53
@petebacondarwin opened a separate issue at https://github.com/angular/angular/issues/41048.

**Comment by mlc-mlapis** [comment] 2021-03-02 13:36
@sahilbabbar 

Maybe this article can help you: https://dev.to/angular/understanding-angular-ivy-library-compilation-246n

**Comment by eestein** [comment] 2021-04-01 10:58
@petebacondarwin I'm on 11.2.7 and using:

```
"enableIvy": "true",
"compilationMode": "partial"
```

I still get the error below when trying to publish to NPM:

> ERROR: Trying to publish a package that has been compiled by Ivy. This is not allowed.

Package versions:

```
"@angular/cli": "~11.2.6",
"@angular/compiler-cli": "~11.2.7",
"@angular/compiler": "~11.2.7",
"@angular/core": "^11.2.7",
```

Am I doing something wrong here?

**Comment by petebacondarwin** [comment] 2021-04-01 11:13
No, that is just a message that the CLI adds to your package.json file to stop you from publishing full-ivy built libraries to npm. You can remove it from the `"scripts"` property to allow you to publish.
That being said, the API for partial-ivy is not yet complete - it will be ready for 12.0.0, hopefully - so I do not recommend actually using this for real libraries on npm just yet.

**Comment by eestein** [comment] 2021-04-01 11:15
@petebacondarwin Thanks for you quick reply. I understood that from your comments above. But I also thought that since 11.2 it was ready to be used (even if at my own risk). I even read an article talking about it here https://blog.ninja-squad.com/2021/01/27/angular-linker/

So apart from hacking the json file, even if I'm using partial mode, it will still throw the error no matter what?

**Comment by petebacondarwin** [comment] 2021-04-01 11:35
If you modify the package.json it will not throw the error. But the content you publish to npm is not guaranteed to work with v12 projects.

**Comment by eestein** [comment] 2021-04-01 11:40
@petebacondarwin I understand and believe me, I do not want to do that! The problem is (I'm not trying to deviate from the issue, just explaining how I got here) my lib is not building using `enableIvy: false`. It throws some errors regarding modules not being properly setup. I even posted on SO here with no answers so far https://stackoverflow.com/questions/66889266/unexpected-value-module-in-file-imported-by-the-module-anothermodule-in-anoth

Since my modules seem to be properly set and I can't build I'm kinda stuck. That's when I read about partial mode and decided to try it. If you think you could help me on my SO question, it'd be much appreciated. I'd love to stick to enableIvy false until partial mode is stable!

Thanks again.

**Comment by alxhub** [comment] 2021-04-15 13:40
I'm going to close this issue as I don't think there's anything actionable for us at this time. StackOverflow is a good forum for continued support if you still have trouble getting libraries and an application build to work together.

**Closed by alxhub** 2021-04-15 13:40 UTC
Labels: comp: compiler, needs clarification
