### ISSUE TITLE
Two way binding broke after data was set by the web component attributes

### ISSUE THREAD

**Issue by alexdarc** [angular/angular#35182] opened 2020-02-06 10:51 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/elements

### Is this a regression?

 No

### Description
We found very strange behavior of WebElements(see the gif below).
If you set data by the attribute of web component it seems like data processed well and binding did his job, but if you try change data in Angular application for example through ngmodel on input tag then you will see that model freezed in the component and change only if another event happened in Angular application.

We found that event ngDoCheck has not been emitted for the component which was rendered by the data received by the webcomponent attribute.

We attached a small application and steps to reproduce the problem.

## 🔬 Minimal Reproduction

https://github.com/alexdarc/angular-webcomponents-test
(stackblitz: https://stackblitz.com/edit/angular-by2cwu)
1. install and run
1. Add a name using the component's inside form
1. Add a name using the component's outside form
1. Change the name that is added using the component's inside form
1. Make sure two-way binding works with this name.
1. Change the name that is added using the component's outside form
1. Make sure two-way binding does **not** work with this name

![reproduction-gif](https://user-images.githubusercontent.com/5403703/73925049-7d478480-48de-11ea-946d-f10a1db0e3cf.gif)

## 🌍  Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 8.3.24
Node: 10.16.3
OS: win32 x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, elements
... forms, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.24
@angular-devkit/build-angular     0.803.24
@angular-devkit/build-optimizer   0.803.24
@angular-devkit/build-webpack     0.803.24
@angular-devkit/core              8.3.24
@angular-devkit/schematics        8.3.24
@angular/cli                      8.3.24
@ngtools/webpack                  8.3.24
@schematics/angular               8.3.24
@schematics/update                0.803.24
rxjs                              6.4.0
typescript                        3.5.3
webpack                            #4.39.2
</code></pre>

**Comment by Tidiane0843** [comment] 2020-02-09 12:56
Hello @alexdarc. Wasn't able to reproduce and understand well this issue because this repo https://github.com/alexdarc/angular-webcomponents-test is different from your gif above. Can you update your repo or give a stackblitz link please?

**Comment by alexdarc** [comment] 2020-02-10 12:20
Hello @TidianeRol. Thank you for your answer. Here is https://stackblitz.com/edit/angular-by2cwu

**Comment by gkalpak** [comment] 2020-07-11 17:40
Thank you for the clear reproduction, @alexdarc.

This has the same root cause as #24181 (running operations outside the Angular zone).
It will be fixed by #37814. Here is a demo using `@angular/elements` from #37814: [StackBlitz][1]

##
Closing as a duplicate of #24181.

[1]: https://stackblitz.com/edit/ngelements-issue-35182

**Closed by gkalpak** 2020-07-11 17:40 UTC
Labels: comp: elements
