### ISSUE TITLE
ng-content throwing a "The component <app> has 1 <ng-content> elements, but only 0 slots were provided."

### ISSUE THREAD

**Issue by chrissheppard41** [angular/angular#6968] opened 2016-02-09 11:00 UTC
Hi all.

I've asked this question here: http://stackoverflow.com/questions/35274885/can-you-have-a-stand-alone-directive-in-angular-2

It came down to using <ng-content> within a component, but it's throwing an error:

> The component Slider has 1 <ng-content> elements, but only 0 slots were provided.

Slider.ts

```
import {Component, View, ElementRef} from 'angular2/core';
@Component({
	selector: 'Slider',
	template: '<ng-content></ng-content>'
})
export class Slider {
    constructor(private element: ElementRef) {
        console.log('Slider');
    }
}
```

index.html
`<Slider><div>hello world</div></Slider>`

Is this a bug with the system or am I writing this out wrong? The code itself within the index HTML disappears from the DOM at run time.

Here is a plnkr: https://plnkr.co/UH42bVv93Fedrre7GKFI Hopefully that works for you

**Comment by zoechi** [comment] 2016-02-09 11:45
dup of #1858 (#4946)

**Comment by pkozlowski-opensource** [comment] 2016-06-16 08:16
This is duplicate of #1858, see the discussion in there why it is not supported.

**Closed by pkozlowski-opensource** 2016-06-16 08:16 UTC
