### ISSUE TITLE
*ngIf not reacting to change in decodeAudioData callback

### ISSUE THREAD

**Issue by Torwori** [angular/angular#11136] opened 2016-08-29 09:15 UTC
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
```ts
// service.ts
apiUrl: string = "...";
token: string = "...";

getDataItem(urlPart: string, id: string, callback: any): void {
        let oReq = new XMLHttpRequest();
        oReq.open("GET", `${this.apiUrl}api/${urlPart}/data/${id}`, true);
        oReq.responseType = "arraybuffer";
        oReq.setRequestHeader("Authorization", `Bearer ${this.token}`);

        oReq.onload = (oEvent) => {
            let arrayBuffer = oReq.response;
            callback(arrayBuffer);
        };

        oReq.send();
}
```
```ts
// audio.component.ts
import { Component, Input, OnInit, OnDestroy, Output } from "@angular/core";
import { Service } from "./service";

@Component({
    selector: "audio-item",
    templateUrl: "audio.component.html"
})
export class AudioItem implements OnInit, OnDestroy {
    @Input() itemId: string;
    @Input() type: string;

    audioCtx: AudioContext = new AudioContext();
    audioSource: AudioBufferSourceNode;

    loading: boolean = true;

    constructor(private _service: Service) {}

    ngOnInit() {
        this._service.getDataItem(`${this.type}Data`, this.itemId, this.parseResult);
    }

    ngOnDestroy() {
        this.audioCtx.close();
    }

    parseResult = (result: ArrayBuffer) => {
        this.audioSource = this.audioCtx.createBufferSource();
        this.audioCtx.decodeAudioData(result, (buffer) => {
            this.audioSource.buffer = buffer;
            this.audioSource.connect(this.audioCtx.destination);
            this.loading = false;
        });
    }

    playAudio() {
        this.audioSource.start(0);
    }
}
```
```html
<i class="fa fa-play" *ngIf="!loading" (click)="playAudio()"></i>
<i class="fa fa-spinner spin" *ngIf="loading"></i>
```

I'm loading a .wav file into an arraybuffer and then decoding it. While the file hasn't loaded, I want to display a spinner.

The issue is that the `fa-play` icon never appears. I placed a breakpoint on the `this.loading = false` line and it does get called correctly.

**Expected/desired behavior**
Spinner disappears, play icon appears.

**Reproduction of the problem**
Can't provide one since I can't find a source for a .wav file that will allow me to make a request from plunkr.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** [Chrome 52.0.2743.116 (64-bit) | Firefox 47] 
 
* **Language:** [TypeScript 1.8.10]

**Comment by Torwori** [comment] 2016-08-29 09:36
**Workarounds:**
```ts
this.audioCtx.decodeAudioData(result, (buffer) => {
    this.audioSource.buffer = buffer;
    this.audioSource.connect(this.audioCtx.destination);
});
this.loading = false;
```
```ts
this.audioCtx.decodeAudioData(result).then((buffer) => {
    this.audioSource.buffer = buffer;
    this.audioSource.connect(this.audioCtx.destination);
    this.loading = false;
});
```

Not sure why the original code doesn't work.

**Comment by skreborn** [comment] 2016-08-29 09:56
This is working as intended. Callbacks don't automatically run in [Angular's zone](https://angular.io/docs/ts/latest/api/core/index/NgZone-class.html), while promises do. Code that changes the internal variables of a component has to be run inside this zone for Angular to run change-detection.

**Comment by vicb** [comment] 2016-08-30 01:20
no repro + @skreborn comment -> closing

**Closed by vicb** 2016-08-30 01:20 UTC
