### ISSUE TITLE
Language Service reports an unknown component selector

### ISSUE THREAD

**Issue by mlc-mlapis** [angular/angular#21066] opened 2017-12-16 23:47 UTC
## I'm submitting a...
<pre><code>[x] Bug report</code></pre>

## Current behavior
If a new package / lib is developed (using `ng-packagr`) and the package wasn't installed yet from `npmjs` (doesn't exist in `node_packages`) ... and the following config is used in `tsconfig.json` instead:

```
"compilerOptions": {
	"baseUrl": ".",
	...
	"paths": {
		"packagename": ["./packages/packagename/src/index.ts"]
	}
}
```

then it is possible to compile the app (wrapper during the development phase of the package) as usual but VS Code shows an error message that a selector of a component (from `packagename`) is an unknown element in a template like `... <component-selector></component-selector> ...`:

```
[Angular]
'component-selector' is not a known element:
1. If 'component-selector' is an Angular component, then verify that it is part of this module.
2. To allow any element add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.
```

If the package is installed (`npm install packagename`) without any changes in the code then the package is correctly recognized and there is no error message.

## Expected behavior
Be able to understand that the package is correctly installed and usable even on the base of the correct configuration of `"paths"` in `tsconfig.json`. The main point is that during development process of such a package there is nothing to install.

## Environment
<pre><code>- Angular version: 5.1.1
- Angular Language Service VS Code Extension: 0.1.7
- TypeScript: 2.4.2
- Browser: all
- Node version: 8.9.1
- Platform:  all
</code></pre>

**Comment by mlc-mlapis** [comment] 2017-12-26 17:33
... related to https://github.com/angular/angular/issues/16382

**Comment by JoostK** [comment] 2021-05-13 20:15
I cannot reproduce in the latest language service (both View Engine and Ivy) so closing as resolved at some time.

**Closed by JoostK** 2021-05-13 20:15 UTC
Labels: P3, comp: language-service, freq1: low, type: bug/fix
