### ISSUE TITLE
RC.1 not working in IE (Working in Chrome/Edge)

### ISSUE THREAD

**Issue by marvinvperez** [angular/angular#8583] opened 2016-05-11 05:33 UTC
Hi,
Using the "QuickStart" as an example, I create a ASP.NT 5 Empty project and put in the QuickStart files. I ran it and working fine in Chrome and in MS Edge but not in IE (v11).

**Steps to reproduce and a minimal demo of the problem**
**Index.html**
```
<!DOCTYPE html>
<html>
<head>
    <base href="/" />
    <title>Angular 2 QuickStart</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--<link rel="stylesheet" href="styles.css">-->
    <!-- 1. Load libraries -->
    <!-- Polyfill(s) for older browsers -->
    <script src="/libs/es6-promise/dist/es6-promise.js"></script> 
    <script src="/libs/es6-shim/es6-shim.js"></script>  
    <script src="/libs/reflect-metadata/Reflect.js"></script>
    <script src="/libs/zone.js/dist/zone.js"></script>
    <script src="/libs/systemjs/dist/system.js"></script>

    <!-- 2. Configure SystemJS -->
    <script src="systemjs.config.js"></script>
    <script>
      System.import('app').catch(function(err){ console.error(err);  });
    </script>
</head>
<!-- 3. Display the application -->
<body>
    <my-app>Loading...</my-app>
</body>
</html>
```

**systemjs.config.js**

```
(function (global) {

    // map tells the System loader where to look for things
    var map = {
        'app': 'app/typescripts/compiledscripts', // 'dist',
        'rxjs': 'libs/rxjs',
        '@angular': 'libs/@angular',
        'angular2-in-memory-web-api': 'libs/angular2-in-memory-web-api'
    };

    // packages tells the System loader how to load when no filename and/or no extension
    var packages = {
        'app': { main: 'main.js', defaultExtension: 'js' },
        'rxjs': { defaultExtension: 'js' },
        'angular2-in-memory-web-api': { defaultExtension: 'js' },
    };

    var packageNames = [
      '@angular/common',
      '@angular/compiler',
      '@angular/core',
      '@angular/http',
      '@angular/platform-browser',
      '@angular/platform-browser-dynamic',
      '@angular/router',
      '@angular/router-deprecated',
      '@angular/testing',
      '@angular/upgrade',
    ];

    // add package entries for angular packages in the form '@angular/common': { main: 'index.js', defaultExtension: 'js' }
    packageNames.forEach(function (pkgName) {
        packages[pkgName] = { main: 'index.js', defaultExtension: 'js' };
    });

    var config = {
        map: map,
        packages: packages
    }

    // filterSystemConfig - index.html's chance to modify config before we register it.
    if (global.filterSystemConfig) { global.filterSystemConfig(config); }

    System.config(config);

})(this);
```

**F12 Error**
![image](https://cloud.githubusercontent.com/assets/17961526/15170895/9e0044c4-177c-11e6-909d-8643d0b1edb0.png)

Please let me know if you need more details.

Cheers,
Marvin

**Comment by zoechi** [comment] 2016-05-11 07:14
Can you please fix the code formatting, larger parts of the code are not shown. Please wrap code blocks in triple backticks ```

**Comment by marvinvperez** [comment] 2016-05-11 07:24
Hi @zoechi , sorry about that! the code parts are updated to show all.
Thanks

**Comment by renehamburger** [comment] 2016-05-11 09:24
@marvinvperez, did you try out the IE-shim referenced in #7144? It really is only a temporary workaround for now until the underlying libraries are fixed to include those polyfills. You can download the shim from https://npmcdn.com/angular2/es6/dev/src/testing/shims_for_IE.js. The following order works for me, though I've only tested on IE9 so far:
```
    <!-- Polyfills for IE (cf. https://git.io/vrJxK) -->
    <script src="node_modules/es6-shim/es6-shim.min.js"></script>
    <script src="node_modules/systemjs/dist/system-polyfills.js"></script>
    <script src="shims_for_IE.js"></script>
```
Some of these polyfills are available in other libraries, so https://github.com/rangle/angular2-redux-starter/commit/ca444cf882f0265b913d9cf9941c45d2cbc173b0 would be another way of including everything that's needed.

**Comment by marvinvperez** [comment] 2016-05-11 09:38
@renehamburger, thanks pointing me to shims for ie reference I'm actually searching for that. however, this doesn't help. Here's the updated scripts so far. I also put the source here in git, appreciate if you can take a look at it.

https://github.com/marvinvperez/angular2quickstart_aspnetcore.git

    
    <script src="libs/es6-shim/es6-shim.min.js"></script>
    <script src="libs/systemjs/dist/system-polyfills.js"></script>
    <script src="https://npmcdn.com/angular2/es6/dev/src/testing/shims_for_IE.js"></script>
    <script src="libs/zone.js/dist/zone.js"></script>
    <script src="libs/reflect-metadata/Reflect.js"></script>
    <script src="libs/systemjs/dist/system.src.js"></script>

    <script src="systemjs.config.js"></script>
    <script>
      System.import('app').catch(function(err){ console.error(err); });
    </script>

**Comment by renehamburger** [comment] 2016-05-12 09:06
Unfortunately, I haven't got the time right now to test your setup, but here's what is working for me:

```html
    <!-- Polyfills for IE; cf. https://git.io/vrJxK -->
    <script src="node_modules/es6-shim/es6-shim.min.js"></script>
    <script src="node_modules/systemjs/dist/system-polyfills.js"></script>
    <script src="shims_for_IE.js"></script>

    <script src="node_modules/zone.js/dist/zone.js"></script>
    <script src="node_modules/reflect-metadata/Reflect.js"></script>
    <script src="node_modules/systemjs/dist/system.src.js"></script>
```

with the following npm package versions:
```js
    "es6-shim": "0.35.0",
    "reflect-metadata": "0.1.3",
    "systemjs": "0.19.27",
    "zone.js": "0.6.12"
```

**Comment by marvinvperez** [comment] 2016-05-12 09:12
If I just clone exactly the Quickstart, it is working. However, as I’ve mentioned I’ve put it in the asp.net 5 blank project. With this, it has a little difference on setting.
Yeah, you could probably understand it better if you have check on my setup.

**Comment by wardbell** [comment] 2016-05-21 06:11
I'm sorry but this is a mash-up of old and new that doesn't look much like the QuickStart we have now.

ASP.NET 5 is now ASP.NET Core. I've lost track of what else is going on in that space.

I can report that the current QuickStart does work in IE11.

I think we should close this. If there is still a problem with the current version, the submitter should open a new issue with specific environment and reproduction.

Thanks for your patience.

**Closed** 2016-05-21 14:18 UTC
Labels: comp: docs

**Comment by TomChen214** [comment] 2016-07-12 06:47
Hi,
This one works for me, just import the script for shim.min.js in the index page   
<script src="node_modules/es6-shim/es6-shim.min.js"></script>

my package.json file just add this es6-shim:
"es6-shim": "0.35.0"

now it's working well for me on IE 11
