### ISSUE TITLE
Angular 2 Error when trying to use a single file to import

### ISSUE THREAD

**Issue by Sharpiro** [angular/angular#8337] opened 2016-04-29 15:34 UTC
**Steps to reproduce and a minimal demo of the problem**

I am trying to use my own "appCore" file as the sole location of imports within my application, but I receive errors when trying to import from it at certain times.

[Here is a plunker of the problem](http://plnkr.co/edit/Z7QdR0Fq0NKJl55qmHZh?p=preview): Look at app/characters/character-list.component.ts line 5 & 6. The plunk will not work, but if you uncomment line 6 and remove "CharacterService" from line 5, it will work.

**Other information**
More information @ [Stackoverflow](http://stackoverflow.com/questions/36899633/angular-2-error-when-trying-to-use-a-single-file-to-import-ts-classes)

**EDIT**
I have another example of the import/export issue, this time it involves the use of OpaqueToken.
http://plnkr.co/edit/OteqJg7VwyTk8vQ0BMhD?p=preview

In the above plunker if you click on any of the vehicles under the "My Vehicles" header, you will receive a dependency injection error saying that there was an undefined variable.

If you replace the IVehicleServiceToken OpaqueToken variable with the string "IVehicleServiceToken" in the following places, the application will run:

- app/app.component.ts: line 19
- app/vehicles/vehicle-list-component.ts: line 18
- app/vehicles/vehicle.component.ts: line 16

**Comment by Ristaaf** [comment] 2016-05-02 13:02
You have got some circular references there. You have a dependency towards appCore in your character-list.component, but your appCore has a dependency on character-list.component!

I've tried doing what you do, and gave up because of all these circular references, somehow when just using imports TypeScript can handle it, but is seems like as soon as you start using exports you get into trouble.

**Comment by Sharpiro** [comment] 2016-05-02 13:17
@Ristaaf I think you might be on to something with that 1st plunker i linked.  However, I'm starting to think the OpaqueToken DI might be a seperate issue as seen in the 2nd plunker.

**Comment by pkozlowski-opensource** [comment] 2016-08-06 14:10
@Sharpiro could you please streamline your plunker (please, trim it down to the essential bits - the current one is way too big to see what is going on) and update it to rc.4? Thnx!

**Comment by pkozlowski-opensource** [comment] 2016-08-08 09:51
Closing as we don't have any reproduce scenario.

**Closed by pkozlowski-opensource** 2016-08-08 09:51 UTC
Labels: flag: can be closed?, need: repro
