### ISSUE TITLE
Routing Guide lacks of Partial Project Zip

### ISSUE THREAD

**Issue by oliveirafilipe** [angular/angular#27871] opened 2018-12-30 18:37 UTC
# 📚 Docs or angular.io bug report

### Description

 
The guides do not have a result zip for each milestone/step, which would be ideal to check if your local code conforms to what this would be

This improvement would be ideal as well, for anyone who would like to start from any milestone without having to start all over from scratch

In my case, I'm following the [Routing & Navigation Guide](https://angular.io/guide/router) and some changes that I made, causes the application not to have the behavior expected. Since I am learning, I do not know in which milestone I diverged nor in which part of the code. I only have access to the final version, where the project structure is already very different from the milestone I am (Milestone 4: Crisis center feature)

### What's the affected URL?**
I'm facing this issue in:
 https://angular.io/guide/router

### Reproduction Steps**

Not applicable

### Expected vs Actual Behavior**

It was expected that at the end of each milestone there would be a zip to download with all progress up to that point so I can know if I'm on the right track

Currently I only have access to the final version of the example

## 📷Screenshot
Not applicable

## 🔥 Exception or Error
Not applicable

### Browser info

This is not a browser specific issue

**Comment by atscott** [comment] 2021-05-24 21:27
Closing as duplicate of #17794

**Closed by atscott** 2021-05-24 21:27 UTC
Labels: comp: docs, comp: examples, comp: router, feature
