### ISSUE TITLE
There's no explanation in the Angular Docs on how to register a different locale.

### ISSUE THREAD

**Issue by Chudroy** [angular/angular#55460] opened 2024-04-22 10:14 UTC
### Describe the problem that you experienced

I wanted to add a different locale to my angular app so that the date pipe could format dates correctly according to the locale i wanted. Looking at different pages in the docs:

https://angular.io/api/core/LOCALE_ID
https://angular.io/guide/i18n-overview
https://angular.io/guide/i18n-common-add-package

I failed to find the information i wanted, and had to use ChatGPT, which told me that I had to add the locale I wanted from the `@angular/common/locales/es`package using the function `registerLocaleData`.

```ts
import { registerLocaleData } from '@angular/common';
import localeEs from '@angular/common/locales/es';


registerLocaleData(localeEs);

export const appConfig: ApplicationConfig = {
  providers: [
    [{ provide: LOCALE_ID, useValue: 'es-ES' }],
...
```

### Enter the URL of the topic with the problem

https://angular.io/guide/i18n-overview

### Describe what you were looking for in the documentation

How to add custom locale to my angular app in the app configuration

### Describe the actions that led you to experience the problem

customizing the datepipe formatting when passing {{ value | date:short }}

### Describe what you want to experience that would fix the problem

better documentation of how to customize localization of application

### Add a screenshot if that helps illustrate the problem

![image](https://github.com/angular/angular/assets/73020686/b52a16b5-8971-4f0f-8e8b-b2b844c8f0bd)
![image](https://github.com/angular/angular/assets/73020686/d02f1466-f118-46c2-8033-73093d45ca71)

**Comment by nicolaric** [comment] 2024-04-22 11:09
try to import like:
```import es from '@angular/common/locales/es';```

register like:
```registerLocaleData(es);```

and provide it like:
```
        {
            provide: LOCALE_ID,
            useValue: () => 'es'
        },
```

everything is nicely documented here: https://angular.io/guide/i18n-overview

**Comment by alan-agius4** [comment] 2024-04-22 13:48
Duplicate of https://github.com/angular/angular/issues/46851

**Closed by alan-agius4** 2024-04-22 13:48 UTC
