### ISSUE TITLE
CanActivate Issue?

### ISSUE THREAD

**Issue by el-peregrino** [angular/angular#32819] opened 2019-09-23 19:30 UTC
I do not see why, but the guard below causes reload of the whole page.
```
canActivate(
    route: ActivatedRouteSnapshot,
    state: RouterStateSnapshot
  ): Observable<boolean> {
    return of(true)
      .pipe(delay(5000))
      .pipe(
        map(response => {
          return response;
        })
      );
  }
```
If I remove the delay the guard works as expected. In the real scenario, I have an API call there. What I do not see? Is it a bug, my mistake?

**Comment by djleonskennedy** [comment] 2019-09-24 06:48
Same problem I have encountered, I have resolver for data request, and in child routes I need this resolved data inside a guard, but canAcrivate seem doesn’t wait for resolver at all! I will prepare reproduction later, but it seems a bug

**Comment by jotatoledo** [comment] 2019-09-24 07:25
@el-peregrino provide a small reproduction of the issue.

**Comment by djleonskennedy** [comment] 2019-09-24 12:52
@jotatoledo Here you can check here

https://stackblitz.com/edit/angular-activate-route-bug?file=src/app/customers/lower/lower/lower.component.ts

Here i've made simple example with lazy routes, you can see that resolver works and in component you can get data, however there is no data in can activate guard

Looks like this child route's guard doesn't wait for resolver

NOTE: if you try use data as stream, it will never be resolved

**Comment by jotatoledo** [comment] 2019-09-27 08:15
@djleonskennedy IMO your issue and OPs are at most related, but are definetly not the same. Yours is basically #24187

**Comment by kusumasai** [comment] 2019-10-02 03:06
@el-peregrino try take(1). It might work

**Comment by el-peregrino** [comment] 2019-10-04 16:14
@kusumasai take(1) has no effect.

**Comment by el-peregrino** [comment] 2019-10-04 16:17
@djleonskennedy I tried to implement a resolver the same way. I came to the same issue.

**Comment by atscott** [comment] 2019-10-08 22:56
@el-peregrino can you please provide a stackblitz reproduction of the issue?

**Comment by alxhub** [comment] 2019-11-19 23:53
Closing this issue as without a reproduction it's impossible for us to debug. Please feel free to open a new issue with a working reproduction if you're still encountering this problem.

**Closed by alxhub** 2019-11-19 23:53 UTC
Labels: comp: router, state: Needs repro
