### ISSUE TITLE
Add @Required(message: string) like decorator for required injection points and friendly developer messages

### ISSUE THREAD

**Issue by robmv** [angular/angular#47235] opened 2022-08-23 19:56 UTC
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

The most common way to give friendly error messages when an injection point isn't fulfilled is to declare them `@Optional()` and check if null on the component constructor. This defeat the use of `@Optional` because in the end the injection isn't optional.

### Proposed solution

Implement a new `@Required(message: string)` decorator, the framework should be able to print the friendly message instead of the not friendly _"ERROR NullInjectorError ... No provider for <token>!"_.

If Angular is unable to do the injection, use the friendly message. The use of `@Optional()` is a [common pattern](https://github.com/angular/components/blob/2f9a59a24c0464cbed7f54cbeb5cba73e6007715/src/material/sort/sort-header.ts#L202).

Another advantage of using the proposed decorator is that the production compiling phase could be able to remove these message strings and use the generic message, in order to not add extra messages to the output. Currently all that code used to give friendly messages on development is being packaged for production.

Injection points without the `@Required()` decorator should still be required, but no friendly message is available for them in case of not being found.

### Alternatives considered

The use of `@Optional` is al already used solution.

**Comment by jessicajaniuk** [comment] 2022-08-23 22:40
This looks to be a duplicate of #47235. We'd like to improve the error messages for the No Provider for message. Since omitting @Optional is essentially Required by default, the proper fix here is to focus on making these error messages much more friendly. We'll track this work on the referenced issue. Thanks for the additional signal! We'll have this for reference as we improve those messages.

**Closed by jessicajaniuk** 2022-08-23 22:40 UTC
Labels: comp: core

**Comment by robmv** [comment] 2022-08-24 00:54
I am not sure framework generated messages will be as helpful as _"MatSortHeader must be placed within a parent element with the MatSort directive"_. @jessicajaniuk Can you provide to the duplicate issue to follow it? By mistake you copied this issue id.

**Comment by jessicajaniuk** [comment] 2022-08-24 15:54
🤦🏻‍♀️ Thanks for letting me know. I've updated it in the comment above.

**Comment by robmv** [comment] 2022-08-24 15:58
Sorry again, I think that isn't either, that one is about `@Input()` being marked as required, not about dependency injection.

**Comment by muhamedkarajic** [comment] 2022-08-25 21:18
Guess finally I'm in the right issue: maybe someone cna check https://github.com/angular/angular/issues/46949 have a working prototype.

**Comment by muhamedkarajic** [comment] 2022-09-16 12:54
@jessicajaniuk just wonder why it isn't planned?
