### ISSUE TITLE
Support for component creation to external DOM element

### ISSUE THREAD

**Issue by pwilkowski** [angular/angular#45512] opened 2022-04-03 15:22 UTC
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

Before version 13 it was possible to "render" a component in external dom element using this code:

```ts
        const app = this.injector.get(ApplicationRef);
        const resolver = this.injector.get(ComponentFactoryResolver);
        const componentFactory = resolver.resolveComponentFactory(CustomComponent);
        const component = componentFactory.create(this.injector, [], externalDomElement);

        app.attachView(component.hostView);
```

Now with deprecation of `ComponentFactoryResolver` I do not see a way to put a component inside dom element. This is especially useful when dealing with 3rd party libs that give you raw dom elements.

### Proposed solution

Either add flag to function

```ts
		const vcRef = this.injector.get(ViewContainerRef);
		vcRef.createComponent(OptmodBadge, {
			rootSelectorOrNode // to allow adding to custom dom element
		})
```

or create another function to project a component to external DOM element

### Alternatives considered

I have seen no alternatives as of now so I am using ComponentFactoryResolver

**Comment by pkozlowski-opensource** [comment] 2022-04-03 19:02
Duplicate of #45263. See the [update](https://github.com/angular/angular/issues/45263#issuecomment-1082530357)

**Closed by pkozlowski-opensource** 2022-04-03 19:02 UTC
