### ISSUE TITLE
1.5 component() templateUrl fails to trigger $routerOnActivate

### ISSUE THREAD

**Issue by ArniDzhan** [angular/angular#6952] opened 2016-02-08 16:46 UTC
Hi,
I am a bit stuck with this problem, I want to use $routerOnActivate to get route params and make an api call using them, but $routerOnActivate seems to only work with template but not templateUrl.

Please see example below

The code below is used to declare a component, all works fine as long as you use template, but if switching to templateUrl (which has the same content as template `<div>home</div>`) all $router actions in controller stop being triggered. $canActivate works in both cases though and html also loads in both cases.

````javascript
let home = {
  //templateUrl: '/app/layouts/home/home.html',
  template: '<div>home</div>',
  controllerAs: 'home',
  controller: function() {
    this.$routerOnActivate = function() {
      console.log('home on activate');
      return true;
    };
    this.$routerCanReuse = () => {
      console.log('home can reuse');
      return true;
    };
    this.$routerOnReuse = () => {
      console.log('home on reuse');
      return true;
    };
  },
  $canActivate: ($nextInstruction, $prevInstruction, MetaDataService) => {
    'ngInject';
    console.log('home can activate?', $nextInstruction, $prevInstruction, MetaDataService);
    return true;
  }
};


export default {
  name: 'home',
  options: home
};

````

**Comment by brandonroberts** [comment] 2016-02-08 20:21
Dupe of https://github.com/angular/angular/issues/4633

**Closed** 2016-02-08 21:18 UTC
