### ISSUE TITLE
bug(upgrade): infinite digests with setTimeout (repro inside)

### ISSUE THREAD

**Issue by andreialecu** [angular/angular#6385] opened 2016-01-10 16:30 UTC
angular2/upgrade has a bug that occurs when an angular1 watcher calls `setTimeout`, as is the case with many angular1 components.

Repro: http://plnkr.co/edit/5iCEQOSOer5c630FStXv?p=preview

This results in infinite angular1 digests because of this line:

https://github.com/angular/angular/blob/master/modules/angular2/src/upgrade/upgrade_adapter.ts#L341

Changing `ngZone.run` to `ngZone.runOutsideAngular` there seems to fix it or make it more manageable.

**Comment by dbpieter** [comment] 2017-02-16 10:04
@petebacondarwin  Shouldn't this bug be reopened after #13812 ?

**Comment by petebacondarwin** [comment] 2017-02-16 10:43
Yes. If you are experiencing a problem can you provide a reproduction to aid our work to find a best solution.

**Comment by petebacondarwin** [comment] 2017-02-16 10:44
We have some ideas that might help but key people are unavailable this wek and next. I'll update in a couple of weeks

**Comment by louwie17** [comment] 2017-03-02 20:31
+1

**Comment by kempcarlos** [comment] 2017-04-18 11:10
@petebacondarwin any update? Will this be fixed in the near future?

**Comment by KirillMetrik** [comment] 2017-06-21 12:44
+1 Any update on this please?

**Comment by dreef3** [comment] 2017-08-26 07:37
Hi,
This issue effectively prevents us from upgrading a hybrid ng1/ng2 app to Angular 2.4.6+. Do you have any thoughts on how this could be resolved? I'd submit a PR then.

What about the comment [here](https://github.com/angular/angular/pull/13812#issuecomment-318492887) that states that #13812 also reverted the line which replaced `$digest` with `$evalAsync`?

This was originally introduced in #9054.

**Comment by andreialecu** [comment] 2017-08-26 08:30
I'm also blocked by this. Haven't been able to upgrade to new versions since this was reverted.

I'm not sure the frequency of this issue is low either. It's hard to track because infinite digests still allow the app run properly but it's just that the performance is very bad. I was only able to realize what was happening via a chrome extension that was showing me angular 1 digest frequency.

**Comment by gkalpak** [comment] 2017-08-26 14:27
We are generally not keen on changing `$digest` to `$evalAsync` for the digest that is run when the microtask queue is empty, because this tends to cover programming errors (which often have hard-to-track-down performance implications).

This unfortunately means that running `setTimeout` in a watcher will lead to infinite digest errors, unless you change it to run outside of the Angular zone.
<sub>
To be clear, you can still use `setTimeout` in the watch listener function:

```ts
scope.$watch(
  () => {
    // Watch function.
    // Do NOT use `setTimeout()` here (unless you explicitly run it outside the Angular zone).
  },
  () => {
    // Watch listener function.
    // You can use `setTimeout()` here.
  }
)
```
</sub>

##
The new [downgradeModule()][1], which decouples the change detections of the two frameworks, could possibly help in such situations. (Docs will be added with #18487.)

[1]: https://next.angular.io/api/upgrade/static/downgradeModule

**Comment by KirillMetrik** [comment] 2018-03-22 14:50
Have you please got any update on this? The bug really prevents us from upgrading to latest Angular and we're quite stuck with AngularJS 1.

**Comment by splincode** [comment] 2018-07-30 10:57
@mhevery Is the issue relevant?

It seems to me that the problem is connected with calling setTimeout
https://github.com/angular/angular/issues/24133

**Comment by mhevery** [comment] 2018-08-07 18:34
Will not fix: not feasible.

**Closed by mhevery** 2018-08-07 18:34 UTC
Labels: comp: upgrade/dynamic, comp: upgrade/static, comp: zones, effort2: days, freq1: low, severity2: inconvenient, state: Needs Design, type: bug/fix, workaround2: non-obvious

**Comment by KirillMetrik** [comment] 2018-10-05 11:48
How should we address upgrading our app from Angular 1 if this is not feasible? We're having a big enterprise project and have chosen AngularJS (1) because it was well supported and promoted by Google. One of the reasons was that we were hoping the project will stay maintanable in time. Instead, Angular 2-6 is a completely new framework, practically incompatible with AngularJS and there is no way to upgrade because of this issue.
@mhevery do you please have any idea what to do in our case? Or should we just throw away all our code and write everything from scratch?
If that's the only option it might make sense for us to switch to React.

**Comment by gkalpak** [comment] 2018-10-05 14:27
@KirillMetrik, the thing that is not feasible is using `setTimeout()` in a watch function, unless you either explicitly run it outside the Angular zone or use `downgradeModule()` (see https://github.com/angular/angular/issues/6385#issuecomment-325132677).

All this means is that (if you choose not to use `downgradeModule()`) you have to modify your code to either not use `setTimeout()` inside a watch function (which is weird anyway) or modify your code to run it outside the Angular zone. I don't see how this is preventing your from upgrading. You will have to change that code anyway sooner or later (i.e. you will have to get rid of `scope.$watch()` at some point).
