### ISSUE TITLE
ROUTES provider registered in ModuleWithProviders is ignored

### ISSUE THREAD

**Issue by ak99372** [angular/angular#43171] opened 2021-08-15 21:42 UTC
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

No

### Description

Two identical modules A and B with the only difference that A registers ROUTES directly in Module providers while B adds it in providers under ModuleWithProviders definition.

```   
import { RouterModule, ROUTES } from '@angular/router';

@NgModule({
imports: [RouterModule],
  providers: [
    { provide: ROUTES, multi: true, useValue: HelloRoutes }
  ]
})
export class ModuleA {
  static forChild(): ModuleWithProviders<ModuleB> {
    return { ngModule: ModuleA, providers: [] };
  }
}

@NgModule({
  imports: [RouterModule],
  providers: []
})
export class ModuleB {
  static forChild(): ModuleWithProviders<ModuleB> {
    return { ngModule: ModuleB, providers: [ {provide: ROUTES,multi: true,useValue: HelloRoutes}]
    };
  }
}
```

When loading these modules in app module I would expect these to behave the same while A routes work correctly, B routes are never even configured (and are ignored). It seems like the Routing service that injects ROUTES never gets this token(?)

Here is also the router configuration showing module B doesn't have any config loaded:
![image](https://user-images.githubusercontent.com/9924769/129493566-6007d3fa-9e0a-427a-9ee0-e31b862ac82a.png)

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-az6m5p?file=src%2Fapp%2Fmodules.ts

### Please provide the environment you discovered this bug in

```true
Agular CLI:11.0.4
Node:14.17.0
OS: Win10 x64
Angular 12.1.0
```

**Comment by JoostK** [comment] 2021-08-16 05:18
What you're seeing is the effect of `multi` providers not being merged across injectors, as in #18894. `ChildModuleFactory` creates a parent injector for the `NgModuleRef` it creates, but the routes in that parent injector are overridden by the NgModule's injector.

The `ModuleWithProviders` type is used to import an NgModule in the `@NgModule.imports` and they way you're using it steps out of the intended usage pattern. If you want a single injector then the `ModuleWithProviders` needs to become part of an `@NgModule.imports` and then that NgModule should be passed to `ChildModuleFactory`; only then do you get Angular's special treatment for `ModuleWithProviders`.

Closing as the root cause is tracked in #18894.

**Closed by JoostK** 2021-08-16 05:18 UTC
