### ISSUE TITLE
Date Pipe with custom time format in IE11

### ISSUE THREAD

**Issue by xwendotnet** [angular/angular#11054] opened 2016-08-25 04:55 UTC
I used date pipe to format timestamp, with custom format.

Like  `{{ticket?.createAt | date:'yyyy-MM-dd hh:ss:mm' }}`

It's work right on Chrome, but has wrong result in IE11, and HTML rendered is 

`‎2016-‎08-‎22 ‎06‎:‎8‎/‎22‎/‎2016‎ ‎6‎:‎40‎:‎23‎ ‎AM:‎8‎/‎22‎/‎2016‎ ‎6‎:‎40‎:‎23‎ ‎AM`

When I removed time part,  `{{ticket?.createAt | date:'yyyy-MM-dd' }}`, IE11 has right result `‎2016-‎08-‎22`

**Comment by asnowwolf** [comment] 2016-08-25 06:03
It's caused by Intl.DateTimeFormat on IE.

see https://msdn.microsoft.com/en-us/library/dn342822(v=vs.94).aspx

```
Each locale must support, at minimum, the following formats:
- weekday, year, month, day, hour, minute, second
- weekday, year, month, day
- year, month, day
- year, month
- month, day
- hour, minute, second
- hour, minute
```

So, if we past in {second: '2-digit'}(without hour/minute) as options parameter, it will be rejected, BUT IE won't throw an error and return the full date format.

I think it need a big change to `common/src/facade/intl.ts`. It's better to assign it to the original author.

**Comment by asnowwolf** [comment] 2016-09-09 08:50
@vicb 
I think it's already gone in RC6. I've verified it just now. It was properly formatted.

**Comment by vicb** [comment] 2016-09-09 13:48
Great, thanks for the feedback

**Closed by vicb** 2016-09-09 13:48 UTC
Labels: comp: i18n, type: bug

**Comment by ckuetbach** [comment] 2017-03-09 13:44
@vicb 
This Bug still exists in 2.4.1 (release) for at least this pattern:

`myDate | date: 'dd.MM.yyyy HH:mm:ss'`

**Comment by anderaus** [comment] 2017-08-01 11:47
@ckuetbach I used this workaround

`<p>{{myDate | date:'dd.MM.yyyy'}} {{myDate | date:'mediumTime'}}</p>`

**Comment by ckuetbach** [comment] 2017-08-01 18:12
Me, too. 

But the bug is still present.

**Comment by 5im5im** [comment] 2017-08-15 07:29
Does not even work with angular 4.1.3 (!) when using `{{ myDatem | date: 'hh:mm' }}`

**Comment by 5im5im** [comment] 2017-08-15 07:34
Does not even work with angular 4.1.3 (!) under IE 11 when using `{{ myDatem | date: 'hh:mm' }}` problem seems to be with 'mm'-String.
