### ISSUE TITLE
"this" binding in template causes massive lag

### ISSUE THREAD

**Issue by cole21771** [angular/angular#29425] opened 2019-03-20 17:28 UTC
# 🐞 bug report

### Affected Package
Maybe @angular/angular?

### Is this a regression?
No idea.

### Description
If you need to to pass a function to an angular component and the function has a this in it, then you need to "functionName.bind(this)" to it so that it will bind to the correct context and you can use the this in your function. However, this seems to cause massive lag issues in some cases. 

A temporary workaround I have found is to change the functions to arrow function variables since they don't have a separate this context and therefore do not need to be bound to this since it is handled automatically. However, I believe this to be just that, a workaround. It seems to indicate a bigger issue within Angular possibly having to do with change detection. 

Here is a link to a video showing the two stackblitz's below using @swimlane/ngx-charts library as the components that need the functions passed to them: https://youtu.be/oFjfBCJ9gpA

## 🔬 Minimal Reproduction
**Buggy version:** https://stackblitz.com/edit/ngx-charts-axistickformatting-buggy-version
**Workaround version:** https://stackblitz.com/edit/ngx-charts-axistickformatting-fixed?file=src%2Fapp%2Fapp.component.ts

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 7.3.6
Node: 10.15.3
OS: win32 x64
Angular: 7.2.9
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.12.2
@angular-devkit/build-angular     0.12.2
@angular-devkit/build-optimizer   0.12.2
@angular-devkit/build-webpack     0.12.2
@angular-devkit/core              7.2.2
@angular-devkit/schematics        7.3.6
@angular/cdk                      7.3.4
@angular/cli                      7.3.6
@angular/material                 7.3.4
@ngtools/webpack                  7.2.2
@schematics/angular               7.3.6
@schematics/update                0.13.6
rxjs                              6.4.0
typescript                        3.2.4
webpack                           4.28.4
</code></pre>

**Anything else relevant?**
There is an issues on the @swimlane/ngx-charts github which shows this happening to other people as well along with the temporary workaround, but I figured this might indicate a larger Angular issue and that I should submit it here. Issue/comment link: https://github.com/swimlane/ngx-charts/issues/261#issuecomment-392046199

**Comment by JoostK** [comment] 2019-03-20 20:36
Hi there! What is going on here is that using `[xAxisTickFormatting]="xAxisTickFormatting.bind(this)"` in the template results in creating a new bound function from `xAxisTickFormatting` during each change detection run. This introduces performance problems as you are experiencing, because it results in continuously rebinding a new value into the `xAxisTickFormatting` input of `trending-custom-line-chart`. 

Instead, we need to create the bound function only once so that each change detection cycle evaluates to the very same function, avoiding any changed inputs. How this can be achieved is mentioned in https://github.com/swimlane/ngx-charts/issues/261#issuecomment-392379861, such alternative approach does not suffer from this problem.

**Comment by pkozlowski-opensource** [comment] 2019-03-21 09:41
@JoostK explanation are spot on. Angular's change detection operates according to some rules and having a call in template that returns a new value on every change detection loop is one of the pitfalls to watch out for. "Fixing" this on the Angular side would require pretty much re-design of the entire change detection system - something not to be taken lightly. 

I'm going to close this issue as we've got already opened issues for the same root cause so this one here doesn't add more information.

**Closed by pkozlowski-opensource** 2019-03-21 09:41 UTC
