### ISSUE TITLE
Angular Service worker incorrectly intercepting http redirects (302)

### ISSUE THREAD

**Issue by Aubry-a** [angular/angular#38194] opened 2020-07-23 12:34 UTC
Hello, 

i work on with angular pwa project with spring-boot back end.

In my project, i am using Angular and Spring boot. My service worker is generating by Angular when i build my project.

I use external service (auth2) and my back-end redirecting to login page when session times out. This works perfectly fine without the service worker enabled, however with the service worker this fails.

To my observation, the mode of the Request is changed from navigate to cors. i see that in request headers

Without SW:

Sec-Fetch-Dest: document
Sec-Fetch-Mode: navigate

With SW:

Sec-Fetch-Dest: empty 
Sec-Fetch-Mode: cors

When active service worker, i have this exception :

_`Access to fetch at 'https://authentication-url.com/...' (redirected from 'https://my-w ebsite.com/file-request.json') from origin 'https://my-website.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`_

I tried adding ngsw-bypass=true query param to the redirect, but that did not help.

Can you help me ? I search on web but i found nothing on this problem with Angular service worker.

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by gkalpak** [comment] 2020-07-23 13:33
Thx for reporting this, @Aubry-a. It is hard to investigate the problem without a reproduction.
Would you be able to share a minimal reproduction. Ideally a sample project we can run locally, but (given that this is likely too complex in this situation) maybe a publicly accessible sample app that demonstrates the problem?

**Comment by Aubry-a** [comment] 2020-07-23 16:07
thx for you answer and to take time for read my problem.


Sorry, I can't give you project because is company project but if you want, i can give you image capture of my configuration or error ? 
I use  external authentication auth2 (Open ID Connect), i use Spring boot  for my back-end i implement Spring boot Security 5 in my project. My configuration is the same that Spring doc. [documentation](https://docs.spring.io/spring-security/site/docs/4.2.x/reference/html/cors.html).

My authentication is working perfectly when the service worker enabled but i don't have access off-line. 
When activate service worker, the first time to connect to my application is working nice because my service is not install for this time. After i come back on my site my back-end must be redirect me on external login page of my external authenticate service but has blocked by CORS but is redirection mustn't be blocked my redirection.
 
I can specify redirection to login page with another origin.

thanks

**Comment by klemenoslaj** [comment] 2020-07-23 18:45
This is the exact problem I was facing as well before and opened two issues:
- https://github.com/angular/angular/issues/36068
- https://github.com/angular/angular/issues/36099

Hope this can help us moving this forward.

---

I think the reproduction should be possible with the minimal setup just creating a dummy redirect with any server while having Angular Service Worker enabled.

---

@gkalpak your initial thoughts on the matter were the following:

> I feel like this is too specific a usecase (and one that doesn't fit very well with SW caching) to be worth supporting in @angular/service-worker.
>
> Personally, I would consider redirecting to login from the client (subject to whether the browser is online or not).

If your stance on this issue has changed that would be really great. If not we do have a client redirect as a workaround.
I am slightly surprised that only a handful of people hit this problem, considering http redirect is an valid approach to the wide range of problems.

**Comment by gkalpak** [comment] 2020-07-24 12:43
Thx for the exta info, @klemenoslaj!

By looking at this, I can't think of a good way to handle this (but maybe it is because I don't fully understand this scenario). For example, f we implemented the suggestion from #36099 (going to to the network first, then to cache for `navigation` requests), how would the SW know that the response should be cached (i.e. that it is not the login page)? Because if you cache the login page, then offline would be essentially broken.

In any case, it would greatly help if someone could create a minimal reproduction/demo to make sure we are all on the same page and trying to tackle the same issue.

**Comment by klemenoslaj** [comment] 2020-07-24 13:22
> i.e. that it is not the login page

The use case here is that the Angular application actually doesn't handle the authentication at all. The authentication is done by something like keycloak and the login page is then a keycloak login page. So the redirect that happens is from Angular index.html to keycloak login.

> how would the SW know that the response should be cached

My idea was, that the `index.html` is always put to cache, but never read from it, unless SW is offline.
I do think this is a bit exotic behavior, so it should be hidden behind the flag.

> Because if you cache the login page, then offline would be essentially broken.

Login page is under a different url, so the SW will not even be activated. Probably not a risk in this scenario.

---

I'll see how much time I will have this weekend, hopefully will manage to give you the very simple reproduction.

**Comment by Aubry-a** [comment] 2020-07-24 15:34
Thanks @klemenoslaj 👍 . I'll see how much time I have this week end too. 

@gkalpak Sorry, my english is so bad. I found it difficult to express what I think in English.

**Comment by gkalpak** [comment] 2020-07-24 16:52
No worries, @Aubry-a. Your English is fine (I am not a native speaker myself either).
This kind of things are better expressed in code anyway 😛

**Comment by klemenoslaj** [comment] 2020-07-24 17:17
@gkalpak funny enough, just stumbled over this blog post: https://medium.com/@adactio/handling-redirects-with-a-service-worker-514a310863cf

Seems like I didn't invent the warm water after all 😂

**Comment by klemenoslaj** [comment] 2020-07-25 19:05
@gkalpak I created one repository with a very stupid express server: https://github.com/klemenoslaj/ng-pwa-redirect

To describe the problem from the beginning, keycloak and other similar solutions are using a http redirect to bring user back to their login page when the session is lost.

So the expected flow is something like:
- browser refresh
- request for index.html
- not authenticated - redirect using `navigate` 302
- user lands on keycloak login page

What happens with SW enabled:
- browser refresh
- **no request** for index.html
- not authenticated - first arbitrary http request is redirected (e.g. rest call or anything else)
- user is not redirected page is loaded with broken session

The error looks something along these lines:
```
Access to fetch at 'https://www.google.com/' (redirected from 'http://localhost:3000/ngsw.json?ngsw-cache-bust=0.3744734012346962') from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

To reproduce, please clone the repo mentioned above and follow the steps:
- execute `yarn` 
- execute `yarn server:build`
- execute `yarn app:build`
- execute `yarn server:start`
- open browser with http://localhost:3000
  - application will load, all files will be requested and cached by the SW
- terminate server (`cmd+c` or `ctrl+c`)
- execute `yarn server:start-redirect`
  - server will redirect the first request (without SW you'd land on Google, with SW error is thrown)

Please let me know if you have any questions.

**Comment by gkalpak** [comment] 2020-07-29 10:57
FYI, I am still trying to wrap my head around this issue and how to best address it.

@klemenoslaj, have you verified that the fix you proposed in https://github.com/angular/angular/issues/36099 (which is similar to what is shown in the [blog post][2] you mentioned above) works for this usecase? AFAICT, it would only work if the redirection target allows cross-origin requests, which is not necessarily the case. What did I miss?

[2]: https://medium.com/@adactio/handling-redirects-with-a-service-worker-514a310863cf

**Comment by klemenoslaj** [comment] 2020-07-29 11:35
> have you verified that the fix you proposed in #36099 (which is similar to what is shown in the blog post you mentioned above) works for this usecase?

I did not directly patch `@angular/pwa` to verify it that way, however I did exclude `index.html` from caching and after that it worked fine - but it makes the offline mode impossible.

This kind of proofs that the solution from #36099 would solve this problem. As long as application is online, index.html request would always happen (exactly how I described in previous paragraph), if offline it would use the cached resource.

> AFAICT, it would only work if the redirection target allows cross-origin requests, which is not necessarily the case

Hmm, maybe I miss something now. Why do you think so?
I think the redirect in the same origin would resulted in the exact same problem. Index.html `navigate` request never happens, next request is incorrectly redirected - the same scenario.

**Comment by gkalpak** [comment] 2020-07-29 14:07
Could you try patching `dist/<project-name>/ngsw-worker.js` and verify whether it works or not?

I might have done something wrong, but trying to make a `more: 'cors'` request from the SW to `/index.html` and have the server redirect it to `google.com` failed with a CORS error:

> Access to fetch at 'https://www.google.com/' (redirected from 'http://localhost:3000/index.html') from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by klemenoslaj** [comment] 2020-07-29 18:02
Ok, I hacked it in and it resolved that issue.

I replaced

```ts
// Next, check if this is a navigation request for a route. Detect circular
// navigations by checking if the request URL is the same as the index URL.
if (this.adapter.normalizeUrl(req.url) !== this.indexUrl && this.isNavigationRequest(req)) {
    // This was a navigation request. Re-enter `handleFetch` with a request for
    // the URL.
    return this.handleFetch(this.adapter.newRequest(this.indexUrl), context);
}
```

with

```ts
if (
    this.adapter.normalizeUrl(req.url) !== this.indexUrl &&
    this.isNavigationRequest(req)
) {
    return this.scope
        .fetch(req)
        .then((res) => {
            // Application is online - caching the result
            return this.scope.caches
                .open(`${this.prefix}:app:cache`)
                .then((cache) => cache.put(req, res.clone()))
                .then(() => res);
        })
        .catch(() => {
            // Application is offline - try returning the matching result from cache
            return this.scope.caches
                .open(`${this.prefix}:app:cache`)
                .then((cache) => cache.match(req));
        });
}
```

Now the Document is requested all the time, despite the SW cache, when that fails due to being offline the cached version is matched and used. Redirect when online works fine.

https://gist.github.com/klemenoslaj/7b7f0db11c163f53294c1bd72f1c397d#file-modified-ngsw-worker-js-L1731

**Comment by gkalpak** [comment] 2020-07-30 10:42
Aha! What you do here is different from what you suggested in #36099. Here, you pass the request through, which maintains its `mode: 'navigate'`. This allows the ServiceWorker to handle the redirect correctly (while with `mode: 'cors'`, as shown in #36099, it would fail).

So, what you are suggesting is having a config option (to be set in `ngsw-config.json`) that says: "Always try to fetch `indexUrl` from the server first and fall back to cache if that fails."
Right?

Question:
What happens if the user's session expires (or similarly they sign out on a different tab) while they are on your page? What if they make an action that triggers a (non-navigate) request?

**Comment by klemenoslaj** [comment] 2020-07-30 13:04
> Aha! What you do here is different from what you suggested in #36099. Here, you pass the request through, which maintains its mode: 'navigate'. This allows the ServiceWorker to handle the redirect correctly (while with mode: 'cors', as shown in #36099, it would fail).

Indeed, I actually changed it half way trough, realized it's in fact not needed. :+1:

> So, what you are suggesting is having a config option (to be set in ngsw-config.json) that says: "Always try to fetch indexUrl from the server first and fall back to cache if that fails."
Right?

Correct, yes :+1:

> Question:
What happens if the user's session expires (or similarly they sign out on a different tab) while they are on your page? What if they make an action that triggers a (non-navigate) request?

I see where you go with this - why not using this mechanism to redirect the client in all cases, right? 🤔 
Good point! I will have to double check on keycloak side how that is handled and will come back to you.
I however don't expect anything is built in, so that would mean a custom implementation.

Do you think there would be no sense supporting the redirect despite the outcome of keycloak?

**Comment by gkalpak** [comment] 2020-07-30 16:12
I am just trying to fully understand the usecase/requirements in order to determine if/how it should be addressed :smiley:
(Basically, I am trying to avoid implementing a fix only to find out one month later that it doesn't cover other similar scenarios and a different fix is needed :grin:)

Thinking about it again, I guess that an app would break anyway (i.e. even without the SW) if the server returned a redirect to a non-navigate request, right? So, the SW shouldn't need to handle the non-navigate requests specially anyway.

**Comment by klemenoslaj** [comment] 2020-07-30 17:24
> I am just trying to fully understand the usecase/requirements in order to determine if/how it should be addressed

Understandable, no objections 😄 

> Thinking about it again, I guess that an app would break anyway (i.e. even without the SW) if the server returned a redirect to a non-navigate request, right? So, the SW shouldn't need to handle the non-navigate requests specially anyway.

Indeed, but this I think is a design flaw of Keycloak that tries to redirect any request. It should be limited to the `navigate` request only I guess.

This flag wound enable any other use case relying on a redirect too.
Furthermore, the flag could probably be kept as experimental at first, until you're confident edge cases are somewhat covered.

**Comment by gkalpak** [comment] 2020-07-31 09:46
:+1:

I am thinking about the following options:

1. Add new boolean config option next to [navigationUrls][1]; something like `networkFirstOnNavigationUrls` that specifies whether navigation requests (that are not matched by an asset- or data-group) should go the network first (and fall back to cache on error).

2. Deprecate [navigationUrls][1] in favor of a new config property:
  ```ts
  navigationRequests: {
    urls?: string[];         // Default: <current default for `navigationUrls`>
    networkFirst?: boolean;  // Default: false
    // or
    // strategy?: 'performance' | 'fresheness';  // Default: 'performance'
  };
  ```

3. Introduce [strategies][2] to asset-groups instead? The default would be `performance`, which keeps the current behavior, but you could put `/index.html` in its own asset-group using `strategy: freshness`.
  (I haven't thought this through. We should make sure its does what we want.)


Open questions:
- Should we pass (non-matched) navigation requests to the server as is (and on error fall back to serving `index`) or immediately fall back to index (in a network-first strategy)?
  (NOTE: This decision might affect the config option name.)
- Is it worth extend the config option to accept either a boolean or a list of URLs (similar to [navigationUrls][1]). This could be useful if you only wanted this behavior for a subset of navigation URLs, but it complicates things (both maintenance and DX).

##
@klemenoslaj or @Aubry-a (or anyone else):
WDYT?
Also, would you be interested in getting a stub at implementing this?

[1]: https://angular.io/guide/service-worker-config#navigationurls
[2]: https://angular.io/guide/service-worker-config#strategy

**Comment by klemenoslaj** [comment] 2020-07-31 10:40
1. **Option 1**:
If you'd like to keep this experimental, I think that's the way to go to avoid breaking changes before you're sure it's fine with your overall SW design.

2. **Option 2**:
I quite like this option with `strategy`. `strategy` enum is better than `networkFirst` boolean, because it would allow you to add additional functionality later as required, while `networkFirst` would require another breaking change or a set of boolean statements that might have conflicts multiple flags are on?

3. **Option 3**:
Sounds great. it would allow this behavior on more than just navigation requests, right? But since you're not sure yourself I prefer `Option 2` 😉

---

I'd be interested contributing here, sure, if it's good "first contribution" issue :+1:

**Comment by gkalpak** [comment] 2020-07-31 12:51
So, it sounds you like all three options :grin:

What I like about the 3rd oprion is that it is more generic. I would like to try that first (unless we find out it has shortcomings while working on it). (This is also likely the most straight forward to implement, because the association between the requested resources and their cache is clearly defined.)

##
> if it's good "first contribution" issue

SW issues are generally not good first issues, because SW is quite different than other front-end code people are used working on. (It's a little like a server and is very powerful (i.e. even a small change in behavior can significantly impact apps).

But you already seems to have a good grasp of SWs (and `@angular/service-worker` in particular), so you might want to give it a go :smiley:

<sub>(Truth be told, this is probably going to be somewhat more complicated than expected.)</sub>

**Comment by klemenoslaj** [comment] 2020-07-31 14:09
Haha right 🤣

Nah, I just wrote down my thoughts on all of them in different scenarios.

I do absolutely prefer Option 3 too for the very same reason, it does sound like the most complex one tho.

I'll try to submit a PR but I expect quite some corrections to follow up before merging.

**Comment by gkalpak** [comment] 2020-07-31 17:46
Awesome! LMK if you need any help.

**Comment by Aubry-a** [comment] 2020-08-03 07:30
Hi, 

I choose option 2. This solution opens up other possibilities in the future, which is very interesting. On the other hand, ease of maintenance is essential so I'll let you see what is the easiest to implement and maintain.
I will adapt in any case.

Sorry I don't think I have the level to contribute, I am a junior in development (less than a year in business)
When I was more comfortable I would contribute to the open source project.

**Comment by gkalpak** [comment] 2020-08-03 22:10
No worries, @Aubry-a. Thank you for your input!

**Comment by klemenoslaj** [comment] 2020-08-07 13:59
I tried to implement `Option 3`, but that will not work.

Asset groups functionality relies on the fetching of files/assets resources. The `navigate` request is not fit that description.
The difference between `/index.html` request and `/` request:

| Request | cache | destination | mode |
|-----| -------------- | --------- | ---|
| `/` | `no-cache` |`document`| `navigate` |
| `/index.html` | `default` |`empty`| `cors` |

So with the asset groups we can only catch the `/index.html` request, which is already too late for the redirect.

---

@gkalpak should I try the `Option 2` or do you think the `Option 3` should still work, despite the `/` request not being an asset?

**Comment by Aubry-a** [comment] 2020-09-21 09:40
hi,

@klemenoslaj have you succeed to implements solution ?

It's possible to change state of issues.

**Comment by klemenoslaj** [comment] 2020-09-21 10:25
@Aubry-a PR is done, waiting for the approval: https://github.com/angular/angular/pull/38565

When will it be released I cannot say.

**Closed** 2020-09-22 16:29 UTC
Labels: comp: service-worker, state: Needs repro, type: bug/fix
