### ISSUE TITLE
@Input and @Output bound to the same signal can produce an error

### ISSUE THREAD

**Issue by e-oz** [angular/angular#51025] opened 2023-07-12 19:56 UTC
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

Please take a look at this: https://stackblitz.com/edit/angular-srfuv9?file=src%2Fmain.ts

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-srfuv9?file=src%2Fmain.ts

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular 16.1
```

**Comment by JoostK** [comment] 2023-07-12 20:54
This _should_ report an error. Emitting into an `@Output` as a side-effect from setting an `@Input` is generally an anti-pattern as it breaks unidirectional dataflow.

The change detection story around signals may change (also see [the RFC](https://github.com/angular/angular/discussions/49685)) and we might revisit some of these restrictions or introduce actual error codes for these situations to have better failure modes, but for now this is working as designed.

**Comment by e-oz** [comment] 2023-07-12 21:13
While I agree with you, this repro is a simplification of a case, where you can not see that a signal will be updated by reading the template - in my real case it happens a few layers deeper, caused by nested fn calls.

**Comment by e-oz** [comment] 2023-07-12 21:48
Also, I wonder how your [model] will work, because it's basically the same shit.

**Comment by e-oz** [comment] 2023-07-13 03:48
Closing issues without any discussion is an anti-pattern.

> Emitting into an @Output as a side-effect from setting an @Input is generally an anti-pattern


It's called “two-way binding”, you can read more here: https://angular.io/guide/two-way-binding

In actual code, the “child” component was mat-expansion-panel, so maybe you should talk to your colleagues and ask them to avoid this “anti-pattern”.

**Comment by JoostK** [comment] 2023-07-13 07:46
Could you share where `mat-expansion-panel` is doing that, I couldn't immediately identity it by looking at the source code.

**Comment by e-oz** [comment] 2023-07-13 07:51
Take your time. I can give a hint: there are multiple components doing this “anti-pattern”, and there is nothing wrong with it. I could spend some of my time finding examples for you, but you already demonstrated that you don’t value my time, so it's on you.

**Comment by JoostK** [comment] 2023-07-13 08:28
The reproduction in particular is problematic because the value that is emitted into the output is different from the value that was bound to the input. If the value is identical or an appropriate equality function was configured for the signal, then the signal would detect that its value didn't actually change and you wouldn't see this error.

I am legitimately asking for insight into places where `mat-expansion-panel` is doing this, since as I said I didn't identify such inputs at first glance.

**Comment by e-oz** [comment] 2023-07-13 08:58
>  appropriate equality function was configured for the signal

For immutable data, it doesn't matter. And at least once it will happen even with an appropriate equality function (I've checked).

> since as I said I didn't identify such inputs at first glance

Try another time. Try another component from Angular Material. Next time maybe don't close the issue instantly if you expect a discussion or even a respectful tone.

It doesn't even matter what component does it - every pagination component (not from Angular Material) will do this, as an example. I've created this repro with a custom component specifically to don't blame Angular Material and to don't try to represent it as their bug. It's a legitimate behavior.

And, of course, I do not blindly update the signal I use in the input binding - input reads a computed signal, and output modifies one of the signals that are being read in that computation.

Still, it's just implementation details - doesn't matter.

You said it works as expected - okay.

**Comment by pkozlowski-opensource** [comment] 2023-07-13 09:10
@e-oz it looks like you are trying to implement a 2-way data binding on top of the signals prototype we've released in v16. This is tricky and the final solution will come with signal based components.

I'm saying that it is tricky since, as @JoostK pointed out, we are trying to _discourage_  data model changes _while_ change detection is running. This is exactly the case in your example - the change component raises an event from input binding, the tricky part is here:

```typescript
export class Child {
  private val = new BehaviorSubject<any>(0);
  @Input() set binding(binding: any) {
    this.val.next({ binding });
  }

  @Output() bindingChange = this.val.asObservable();
}
```

We probably don't talk about it enough, but raising events (emitting to outputs) from input setters makes the data flow really tricky to reason about. Hence the _discourage bit_ and the error to warn people early about this pattern. 

The crux of the issue is writing to an output from an input setter. While I fully recognize that this happens in the existing code bases I would also _love_ to see an example of it in a popular libraries - if you could share a link I could take a look and see if signal-based components with the `model` primitive offers a better solution.

But yeh, long story short - we want to higlight that writing to outputs from input setters makes code flow really tricky to reason about.

**Comment by e-oz** [comment] 2023-07-13 16:23
Not sure what is more funny here, but let's have some fun.

Let's ask @crisbeto if he thinks that two-way binding is an anti-pattern and popular libraries should never have side-effects in setters, that could cause (directly or indirectly) some `Output` to emit a value.

@pkozlowski-opensource link that you asked: https://github.com/angular/components/blame/main/src/cdk/accordion/accordion-item.ts#L51

**Comment by JoostK** [comment] 2023-07-13 16:42
Notice how there won't be any errors if the emitted value is identical to what was set in the input, by changing

```ts
this.val.next({ binding });
```

to

```ts
this.val.next(binding);
```

If it wasn't the signal that would report the error it would be an `ExpressionChangedAfterItHasBeenChecked`, which is why emitting into an output from an input is generally considered an anti-pattern. If the value is _identical_ then it won't typically result in an error (unless the output listener _does_ make other changes to the data model) and you'd get away with this pattern.

**Comment by alxhub** [comment] 2023-07-14 14:41
It should not be strictly prohibited to set signals in response to inputs changing (any more than it is to push to a subject in RxJS), and I wonder if our assertion is overly strict here.

**Comment by pkozlowski-opensource** [comment] 2023-09-21 11:28
Here is a slightly simpler reproduce scenario: https://stackblitz.com/edit/angular-j6m2yc?file=src%2Fmain.ts

As noted before, the crux of the issue is emitting synchronously in a setter:

```typescript
export class Child {
  @Input() set binding(binding: any) {
    this.bindingChange.emit(binding);
  }

  @Output() bindingChange = new EventEmitter();
}
```

The obvious (and actually "correct") work-around here is to mark the EventEmitter as async - this is exactly the same situation as with NgModel and the same "solution" applies. We are, fundamentally, reaching the limits of the uni-directional data flow here.

Generally speaking this is a 2-way data binding pattern that we _should_ support, in this form or another. For now the reported error acts as "expression changed after it was checked" error for signals, really.

I'm going to keep this issue for now so anyone bumping into this issue can follow the discussion. But the likely solution will come from the `model` input implementation.

**Comment by mgechev** [comment] 2023-09-21 16:14
@e-oz a reminder that our GitHub issue tracker is under the [Angular code of conduct](https://github.com/angular/angular/blob/0a4f18a419ba68a7c8a2d22da85a7f88bd217840/CODE_OF_CONDUCT.md). We appreciate your opinions and thoughts, but personal attacks are not acceptable. I recommend you stick to more constructive communication. Alternatively, we'll ban you from this channel.

**Comment by alxhub** [comment] 2023-10-18 15:18
Closing as the bug here was well explained above. In general, this kind of case will be supported in one of three ways:
* By passing the `async` flag to the output
* By using a `model` input instead
* With upcoming work to support signals making views dirty in a backwards direction

**Closed by alxhub** 2023-10-18 15:18 UTC
Labels: area: core, cross-cutting: signals
