### ISSUE TITLE
ngSwitchCase directive does not work with multiple values

### ISSUE THREAD

**Issue by ogix** [angular/angular#12174] opened 2016-10-08 21:23 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Using multiple values as an expression in the ngSwitchCase directive only works with the first value and does not give any errors.

**Expected behavior**

Show view when `ngSwitch` matches second value of the `ngSwitchCase` expression.

**Minimal reproduction of the problem with instructions**

```
<div [ngSwitch]="status">
  <div *ngSwitchCase="statusEnum.Loaded || statusEnum.Selected">
    <p>I should show up when status is either Loaded or Selected!
  </div>
</div>
```

**What is the motivation / use case for changing the behavior?**

Make everyone happy who need to use multiple values.

**Please tell us about your environment:**

Windows 10

* **Angular version:** 2.0.1

* **Browser:** [all]

 
* **Language:** [all]

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment] 2016-10-08 21:25
Can you provide a plunkr with reproduction?

**Comment by vicb** [comment] 2016-10-08 21:31
It should work.

However `statusEnum.Loaded` is probably undefined at runtime time (if statusEnum is a TS enum).

One way to solve this would be `<div *ngSwitchCase="loadedOrSelected()">`

and that method would basically `return statusEnum.Loaded || statusEnum.Selected;` on your component.

Closing as:
- work as expected,
- no repro.

**Closed by vicb** 2016-10-08 21:31 UTC

**Comment by ogix** [comment] 2016-10-08 21:33
It also does not work with string values. See plunkr: https://plnkr.co/edit/myTqMqYFTAVDQ1b1JiEH?p=preview

**Comment by pkozlowski-opensource** [comment] 2016-10-08 21:39
Looking at the plunk it works as expected. Your expression (`'loaded' || 'selected'`) will always evaluate to `'loaded'` and since the switch var value is `'selected'` it never matches.

**Comment by ogix** [comment] 2016-10-08 21:45
Yep, you are right..
AFAIK Angular1 recently added support for multiple values: https://docs.angularjs.org/api/ng/directive/ngSwitch
Maybe this issue should be changed to feature request then?

**Comment by pkozlowski-opensource** [comment] 2016-10-08 21:52
> Maybe this issue should be changed to feature request then?

Maybe. Feel free to open a new issue with clear description if you feel like this would be valuable addition to the framework.

**Comment by coli** [comment] 2016-12-05 15:09
Can we just convert this issue to a feature request? It's pretty basic functionality that's missing. Or back to ngIf I guess...

**Comment by vicb** [comment] 2016-12-05 17:02
Once again it's probably better to have the logic in methods on your component and rely on them.

Easier to read as the logic is all on your cmp and also easier to test

**Comment by kanlidy** [comment] 2017-02-23 09:38
@ogix [http://stackoverflow.com/a/40177408/5497460](http://stackoverflow.com/a/40177408/5497460) There is a solution.

**Comment by itsnotvalid** [comment] 2017-03-12 11:27
Needa quote string is pretty dumb...

**Comment by JavierFuentes** [comment] 2018-04-13 23:28
@vicb , I tested to have the logic in methods on my component and rely on them but a simple console.log() trace shows how Angular calls indefinitely to this methods when there isn't user interaction... with ngIf I have the same results...

**Comment by DaniilPalii** [comment] 2018-11-22 13:37
You can use ngTemplateOutlet for implementing this
`<ng-container [ngSwitch]="variable">
          <ng-container *ngSwitchCase="1">
            <ng-container *ngTemplateOutlet="firstAndSecond"></ng-container>
          </ng-container>
          <ng-container *ngSwitchCase="2">
              <ng-container *ngTemplateOutlet="firstAndSecond"></ng-container>
          </ng-container>
          <ng-container *ngSwitchCase="3">
              some html
          </ng-container>
          <ng-container *ngSwitchDefault>
                another html
          </ng-container>
        </ng-container>
        <ng-template #firstAndSecond>
          html
        </ng-template>
      </ng-template>`
