### ISSUE TITLE
Non-null assertion operator changes template behaviour

### ISSUE THREAD

**Issue by SebastianPodgajny** [angular/angular#41482] opened 2021-04-07 10:30 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/compiler I guess

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...
```
{{ abc?.def.ghi }} is translated into (tmp = abc) == null ? null : tmp.def.ghi
{{ abc?.def!.ghi }} is translated into (abc == null ? null : abc.def).ghi
```
This is different from TS behaviour because in TS non-null assertion operator doesn't change generated code.
Is this behaviour expected in Angular?
https://www.typescriptlang.org/play?target=1&jsx=0&module=1&ts=4.1.5#code/MYewdgzgLgBFCm0BcMCGYCeMC8MwFcAbQgbgCgFoB+AOlQCNgaATeAMwEYLEpaHgAhC3YAmIA
![image](https://user-images.githubusercontent.com/21180501/113852897-55cba080-979d-11eb-8e0b-70090ea832e9.png)
![image](https://user-images.githubusercontent.com/21180501/113852492-e3f35700-979c-11eb-9e27-71ad1b10d2a2.png)

## 🔬 Minimal Reproduction

 
https://stackblitz.com/edit/angular-ivy-bdk613?file=src%2Fapp%2Fapp.component.html

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 11.2.6
Node: 14.16.0
OS: darwin x64

Angular: 11.2.7
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1102.6
@angular-devkit/build-angular     0.1102.6
@angular-devkit/build-optimizer   0.1102.6
@angular-devkit/build-webpack     0.1102.6
@angular-devkit/core              11.2.6
@angular-devkit/schematics        11.2.6
@angular/cdk                      11.2.6
@angular/cli                      11.2.6
@ngtools/webpack                  11.2.4
@schematics/angular               11.2.6
@schematics/update                0.1102.6
ng-packagr                        11.2.4
rxjs                              6.6.3
typescript                        4.1.5
</code></pre>

**Anything else relevant?**

**Comment by JoostK** [comment] 2021-04-07 10:32
This used to be the case in TypeScript 3.8 as well:

https://www.typescriptlang.org/play?target=1&jsx=0&module=1&ts=3.8.3#code/MYewdgzgLgBFCm0BcMCGYCeMC8MwFcAbQgbgCgFoB+AOlQCNgaATeAMwEYLEpaHgAhC3YAmIA

They have changed the precedence in 3.9 to behave as you mention.

**Comment by jelbourn** [comment] 2021-04-09 21:00
Duplicate of #34385

**Closed by jelbourn** 2021-04-09 21:00 UTC
Labels: comp: compiler
