### ISSUE TITLE
Angular 10 canLoad guard seems to not working properly

### ISSUE THREAD

**Issue by wojtek1150** [angular/angular#39808] opened 2020-11-23 08:38 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/router

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 9.1.12 (v9-lts)

### Description

 After update Angular to v10 `canLoad` guard seems to not working as expected. In previous version works normally. On `canActivate` guard works as expected.

## 🔬 Minimal Reproduction
Code below with logs in JsDoc
```
@Injectable({ providedIn: 'root' })
export class GuardName implements CanActivate, CanLoad {

  constructor(private store: Store<ProjectState>) {}

  canActivate(): Observable<boolean> {
    return this.canEnter();
  }

  canLoad(): Observable<boolean> {
    return this.canEnter();
  }

  private canEnter(): Observable<boolean> {
    return this.checkStore().pipe(
      switchMap(() => of(true)),
      catchError(err => {
        console.log('err', err)
        throw err;
      })
    );
  }

  /**
   * Flow (can activate):
   * 1. loaded - boolean (not important)
   * 2. user log (null)
   * 3. user log (object)
   * 4. user loaded (object)
   * 5. withLatestFrom
   * 
   * Flow (can load):
   * 1. loaded - boolean (not important)
   * 2. user log (null)
   * 3. user log (object)
   * 4. user loaded (object)
   * 5. withLatestFrom NOT REACHED, stuck on previous log
   *
   */
  private checkStore(): Observable<any> {
    return this.store.pipe(
      select(dictionaryLoaded),
      tap(r => console.log('loaded', r)),
      withLatestFrom(this.store.pipe(
        select(currentUser),
        tap(r => console.log('user log', r)),
        filter(user => !!user),
        tap(r => console.log('user loaded', r)),
        catchError(err => {
          console.log('err', err)
          throw err;
        })
      )),
      tap(r => console.log('withLatestFrom', r)),
      catchError(err => {
        console.log('err', err)
        throw err;
      }),
      // rest of stuff, not important in that bug
      take(1)
    );
  }

}
```

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 10.2.0
Node: 12.18.1
OS: darwin x64

Angular: 10.2.3
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1001.7
@angular-devkit/build-angular      0.1002.0
@angular-devkit/build-ng-packagr   0.1002.0
@angular-devkit/core               10.1.7
@angular-devkit/schematics         10.1.7
@angular/cdk                       10.2.7
@angular/cli                       10.2.0
@schematics/angular                10.1.7
@schematics/update                 0.1002.0
ng-packagr                         10.1.2
rxjs                               6.6.3
typescript                         4.0.5

</code></pre>

**Anything else relevant?**

Let me know it needed 😉

**Comment by criskrzysiu** [comment] 2020-11-24 07:30
I think router configuration is relevant here.  Also how NgRx is configured, is user state maybe and feature state registered inside the lazy loaded module maybe? Without stack blitz it will be hard to find reason why it is failing.

**Comment by atscott** [comment] 2020-11-25 16:54
Hi @wojtek1150, could you please provide a minimal reproduction in either stackblitz or a github repo so we can investigate further?

**Comment by wojtek1150** [comment] 2020-11-26 09:12
Hi, I'll prepare some stackblitz in few days

**Comment by AndrewKushnir** [comment] 2021-01-12 19:29
Closing this ticket due to the lack of repro, feel free to reopen or create a new ticket once repro is available. Thank you.

**Closed by AndrewKushnir** 2021-01-12 19:29 UTC
Labels: comp: router, needs reproduction
