### ISSUE TITLE
Private router property exposed via route.snapshot

### ISSUE THREAD

**Issue by jzabinski-dolios** [angular/angular#44254] opened 2021-11-23 21:18 UTC
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

No

### Description

Route snapshots apparently expose properties private to the router. These can be manipulated by apps, which can break the router.

### Please provide a link to a minimal reproduction of the bug

https://angular-ivy-c9ixc5.stackblitz.io/

### Please provide the exception or error you saw

```true
No exception, but the router fails to operate correctly.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Discovered in 12.2.13, but reproduces in Angular 13.

Angular CLI: 13.0.3
Node: 16.13.0
Package Manager: npm 8.1.0
OS: darwin x64

Angular: 13.0.2
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1300.3
@angular-devkit/build-angular   13.0.3
@angular-devkit/core            13.0.3
@angular-devkit/schematics      13.0.3
@angular/cli                    13.0.3
@schematics/angular             13.0.3
rxjs                            7.4.0
typescript                      4.4.4
```

### Anything else?

The attached Stackblitz has a few different levels of `router-outlet` and a button. When the button is clicked, the router state should go from ./child1/child2 to ./child1/child2;newParam=123. Instead it remains ./child1/child2.

The core issue is that when `route.snapshot` is used, `route.snapshot.url` seems to refer directly to the `UrlTree` object stored in `router.browserUrlTree`. If properties from the `UrlTree` are manipulated in the app, they are changed on the private instance of the router.

The attached Stackblitz uses this code:

```
getChildSegments(route: ActivatedRoute): Array<string | Params> {
    const childSegments: Array<string | Params> = [];
    while (route.firstChild) {
      const snpsht = route.snapshot;
      childSegments.push(
        ...snpsht.url.map(segment => [segment.path, segment.parameters]).flat()
    );
      route = route.firstChild;
    }
    return childSegments;
  }
```

The basic idea is to collect segments for route children so that they can be defined in a later call to `router.navigate`. The overall use case is to be able to define a matrix parameter for a child segment.

But with a reference to the private router state, code like this becomes a problem:
```
const [childPath, childParams] = this.getChildSegments(this.route);
Object.defineProperty(childParams, 'newParam', {
      value: '123',
      enumerable: true,
    });
this.router
      .navigate(['./', anyMatrixParams, childPath, childParams],
      { queryParams: this.route.snapshot.queryParams })
      .catch((err) => console.error(err));
```

In the above code, `childParams` is part of the definition of the private router state. So when a new property is added, the router can no longer detect that the URL has changed. The detection is attempted [here](https://github.com/angular/angular/blob/master/packages/router/src/router.ts#L659) but since the app was allowed to alter `router.browserUrlTree` directly, `t.extractedUrl.toString()` and `browserUrlTree` are prematurely equal. The router thus incorrectly assumes that this is a duplicate route.

The suggested fix is to provide a copy of anything private to the router in any references accessed through the `ActivatedRoute`.

**Comment by jzabinski-dolios** [comment] 2021-11-23 21:22
[Here](https://drive.google.com/file/d/1ztY3HiQMFWi0U7VNKAw56269hofWsOYZ/view?usp=sharing) is an Angular 13 project reproducing the bug. The Stackblitz in the original description used Angular 12, and I had trouble convincing Stackblitz to use Angular 13 instead.

**Comment by atscott** [comment] 2021-11-24 22:10
Duplicate of #27528

**Closed by atscott** 2021-11-24 22:10 UTC
Labels: comp: router
