### ISSUE TITLE
changeDedection issue after upgrading to angular 7

### ISSUE THREAD

**Issue by neo-xy** [angular/angular#26789] opened 2018-10-26 19:48 UTC
Just want to say that I hae hard time to repreduce the issue on stackBlitz but scenario is simple so hopefully explanation/code will be enaugh.

using angularFireAuth to see the state of Auth and depending on what state it will show one or the other element in the DOM with help of *ngIf 

AppComponent.ts

    `export class AppComponent implements OnInit {

            authSuccessful = true;
            number = 0;

             constructor(private auth: AngularFireAuth) {
                    this.auth.auth.onAuthStateChanged(user => {
                          this.authSuccessful= user!=null;
                     });
             }

             clickMe() {
                  this.number = 3;
             }
      }`

    ` <div *ngIf="authSuccessful;else login">
          <div> {{number}}</div>
          <button (click)="clickMe()">ok</button>
     </div>

      <ng-template #login>
         <app-login></app-login>
     </ng-template>`

so first of all change of "authSuccessful" is not detected and I have to use "ChangeDetectorRef" to detect change when I do that  and I click on the button the "nummer" does not change and have to use "detectChanges()" again in "clickMe" methode for it to work.

Tryed to start the same project from the scratch it works at the begining but then from no where it just stops (done it twice to try find a point in when it stops working- but no success):/

I may as well add that if *ngIf condition is taken out of dom then "clickMe()" deduction works as it suposted to

any ideas ? (sitting 2nd day with that) :(

**Comment by Destreyf** [comment] 2018-10-26 21:58
I just want to chime in here, i'm noticing a similar issue, however mine only occurs when i've compiled for AoT.

my code is setup with a central service UserService (injected as `userService`) that has a variable `isMasqueraded` that's a `BehaviorSubject`, in my header i subscribe to `userService.isMasqueraded` and map a class to this variable it does not seem to change the class, but the `isMasqueraded` subscribe emits a console log showing the value changed, yet the dom did not.

If i reload my page, the isMasqueraded variable is loaded from local storage (setting it to true) before the header is rendered, the header then has the appropriate class on it.  I am going to try to throw a reproduction together this weekend.

Here's my `ng version` just in case i missed something myself when going through stuff.
```
Angular CLI: 7.0.3
Node: 10.12.0
OS: win32 x64
Angular: 7.0.1
... animations, cdk, common, compiler, compiler-cli, core
... elements, forms, language-service, material
... platform-browser, platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.10.3
@angular-devkit/build-angular     0.10.3
@angular-devkit/build-optimizer   0.10.3
@angular-devkit/build-webpack     0.10.3
@angular-devkit/core              7.0.3
@angular-devkit/schematics        7.0.3
@angular/cli                      7.0.3
@ngtools/webpack                  7.0.3
@schematics/angular               7.0.3
@schematics/update                0.10.3
rxjs                              6.3.3
typescript                        3.1.3
webpack                           4.19.1
```

**Comment by chaosmonster** [comment] 2018-10-27 09:33
Regarding @neo-xy issue. First I think this belongs on Stackoverflow with an Angular tag, but as you are already here.
You could use the async pipe on your observable to solve it. This way you don't have to check for unsubscribing to your observable as well.
More general:This behaviour is as intended, the change detection would be triggered if a component's Inputs changed (by reference). So in your case Angular doesn't know about the change of the property and you would have to tell it programmatically with the [ChangeDetectionRef](https://angular.io/api/core/ChangeDetectionStrategy). Hope this helps and you can close the issue

**Comment by neo-xy** [comment] 2018-10-27 12:13
@chaosmonster sorry for that and ty for information, helps alot (y)

**Comment by pkozlowski-opensource** [comment] 2018-10-31 08:35
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Closed by pkozlowski-opensource** 2018-10-31 08:35 UTC
Labels: comp: core & compiler
