### ISSUE TITLE
[Dart] Transformer url resolver should handle @import statements in stylesheets

### ISSUE THREAD

**Issue by andresaraujo** [angular/angular#4559] opened 2015-10-06 22:48 UTC
The Dart transformer fails if a stylesheet contains a `@import` statement. (alpha 39)

**Project layout**
```
.
├── lib
│   ├── app.dart
│   └── app.html
├── packages
└── web
    ├── index.html
    ├── main.dart
    └── styles
        └── main.css
```

**main.css**
```
@import url(https://fonts.googleapis.com/css?family=Roboto);

...
```

**Error:**
```
Build error:
Transform StylesheetCompiler on ng2_dart_quickstart|web/styles/main.css threw error: Invalid argument (absoluteUri): Unsupported URI scheme encountered: Instance of 'Uri'
package:angular2/src/transform/common/url_resolver.dart 42            TransformerUrlResolver.toAssetScheme
package:angular2/src/transform/common/url_resolver.dart 16            TransformerUrlResolver.resolve
package:angular2/src/core/compiler/style_url_resolver.dart 32         extractUrls.<fn>

```

**Comment by vicb** [comment] 2015-10-06 22:57
would `@import url("https://fonts.googleapis.com/css?family=Roboto");` work ?

**Comment by andresaraujo** [comment] 2015-10-06 23:00
Nope, It still fails @vicb

**Comment by yjbanov** [comment] 2015-10-06 23:00
This is a bug in template pre-compiler. Will fix.

**Comment by yjbanov** [comment] 2015-10-08 17:47
@andresaraujo: we should be able to handle absolute `@import` URIs properly. Could you give it a try and report if the issue is fixed?

**Comment by yjbanov** [comment] 2015-10-08 17:47
Closing for now. Please reopen if the issue is still there.

**Closed by yjbanov** 2015-10-08 17:47 UTC
Labels: comp: dart-transformer, effort2: medium (day), P1: urgent, state: PR, type: bug
