### ISSUE TITLE
Pipe not found in watch mode

### ISSUE THREAD

**Issue by mgechev** [angular/angular#34582] opened 2019-12-28 00:44 UTC
# 🐞 bug report

### Affected Package

`@angular/compiler`

### Is this a regression?

It's probably not a regression in 9 & ngtsc, but definitely a regression compared to ngcc.

### Description

After I define a pipe and add it in the module declarations, once I used it in a template of a component in the same module, I get the error:

>The pipe ' ' could not be found

Once I restart the compiler everything works as expected.

## 🔬 Minimal Reproduction

1. Create a new CLI project
2. Define a pipe
3. Add it to the list of declarations of the `AppModule`
4. Use it in the template of `AppComponent`

## 🔥 Exception or Error

>The pipe ' ' could not be found

## 🌍  Your Environment

**Angular Version:**

9.0.0-rc.7

**Comment by muhammedMoussa** [comment] 2019-12-28 09:13
Always happens in general not only pipe but components also.

**Comment by JoostK** [comment] 2020-01-01 21:56
Hey Minko,

I can't reproduce using the steps you provided. Could there be some specific setup required for this to start failing?

My reproduction attempt was roughly as follows:

```sh
npx @angular/cli@next new ng34582
cd ng34582
yarn ng g p my-pipe
yarn ng serve
# change template, pipe still works
```

Also removing the declaration from `AppModule` and then refreshing causing a compilation error ("No pipe found with name 'mypipe'.") that is resolved once again after reinserting the declaration.

**Comment by mgechev** [comment] 2020-01-04 20:33
I couldn't find steps with which I was able to reproduce the issue consistently. I experienced the same error multiple times with missing `async` pipe, although I had `CommonModule` imported in the right module.

After I terminated `ng serve` and restarted the dev server, the error was gone.

**Comment by mgechev** [comment] 2020-01-04 20:37
After several more attempts, I was able to reproduce the issue (again, not consistently) with:

1. Create a new pipe manually, without using the CLI's generator and without importing it in a `NgModule` yet
2. Use the pipe in a template and observe the compile-time error which is expected
3. Add the pipe to the list of declarations in the `AppModule`

After that, I keep seeing the compile-time error for the missing pipe, although it's already been declared.

**Comment by mgechev** [comment] 2020-01-04 23:10
One more update, having the following module definition:

```ts
import { NgModule } from '@angular/core';
import { HomeComponent } from './home.component';
import { RouterModule } from '@angular/router';
import { CommonModule } from '@angular/common';
import { EpisodeSummaryComponent } from './episode-summary.component';

@NgModule({
  declarations: [HomeComponent, EpisodeSummaryComponent],
  imports: [
    CommonModule,
    RouterModule.forChild([
      {
        path: '',
        component: HomeComponent
      }
    ])
  ]
})
export class HomeModule {}
```

I hit the error in the template of `HomeComponent` that the `async` pipe is missing right after I renamed `EpisodeSummaryComponent`. I had to restart the dev server to resolve it.

**Comment by alxhub** [comment] 2020-01-23 22:00
I think this was related to #34912. I'm going to optimistically close this issue; let me know if it's still a problem.

**Closed by alxhub** 2020-01-23 22:00 UTC
Labels: comp: compiler, freq2: medium, severity5: regression, state: Needs repro, type: bug/fix

**Comment by mgechev** [comment] 2020-02-21 22:05
Haven't experienced the issue in the last few releases, looks like #34912 fixed the problem.
