### ISSUE TITLE
In Ivy, @Input setting order no longer matches the order of their corresponding properties in the class

### ISSUE THREAD

**Issue by Shijir** [angular/angular#34322] opened 2019-12-10 03:00 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package "@angular/core": "9.0.0-rc.5" with Ivy

### Description

__Before Ivy__:
 it was possible to receive `@input` values in a certain order. For example: I have a following component:

```ts
@Component({
  selector: 'hello',
  template: `<h1>Hello {{name}}!</h1>`
})
export class HelloComponent  {
  public name: string = "";

  @Input() set firstName(value: string) {
    this.name += value;
  }

  @Input() set lastName(value: string) {
    this.name += value;
  }
}
```

In this case, the`firstName` input setter used to run before the `lastName` input setter as their order is defined in the component class. So no matter in what order users provide values to input properties, it was possible to receive them in our desired order:

```html
<!--displays Hello JohnDoe-->
<hello firstName="John" lastName="Doe"></hello> 

<!-- still displays Hello JohnDoe as it should-->
<hello lastName="Doe" firstName="John"></hello>
```

__After Ivy__:

I realized that input values are set as they are provided in the template, not by the order of their corresponding properties in the class. For example, using the exact same component in Ivy, we get the following result:

```html
<!--displays Hello JohnDoe-->
<hello firstName="John" lastName="Doe"></hello> 

<!-- displays Hello DoeJohn-->
<hello lastName="Doe" firstName="John"></hello>
```

## 🔬 Minimal Reproduction

Angular 8: https://stackblitz.com/edit/angular-input-order

In Ivy: https://ivy.ng-run.com/edit/cOAOZzmer5154DINiEZT?open=app%2Fapp.component.ts

## 🌍  Your Environment

**Angular Version:**
<pre><code>

"@angular/core": "9.0.0-rc.5" with Ivy

</code></pre>

**Anything else relevant?**

**Comment by Airblader** [comment] 2019-12-10 03:16
I doubt that this was ever intentional, by-design behavior. This sounds like xkcd 1127 to me.

**Comment by Shijir** [comment] 2019-12-10 04:50
Lol, maybe or maybe not. That's why this issue is filed to dispel our doubts.

**Comment by zessu** [comment] 2019-12-10 08:57
> Lol, maybe or maybe not. That's why this issue is filed to dispel our doubts.

yeah that's a good catch. I'll look at the calling order after the lifecycle methods to see in which order they are accessed because they seem reversed now. Is this behaviour consistent?

**Comment by djleonskennedy** [comment] 2019-12-11 11:59
Hmmm... hopefully I won’t see same code in my life:)

**Comment by lucipacurar** [comment] 2019-12-12 11:04
https://stackoverflow.com/questions/5525795/does-javascript-guarantee-object-property-order

**Comment by djhojd** [comment] 2019-12-12 11:04
Please share with us, or just me, a use case in which the order your inputs get called SHOULD matter...

**Comment by kara** [comment] 2020-01-07 23:32
@Shijir To answer your question, we don't consider input setting order within directives to be public API. If you want to react to a directive's inputs in a certain order, using the `ngOnChanges` lifecycle hook tends to be a better place. As such, I'm closing this issue as working as intended.

**Closed by kara** 2020-01-07 23:32 UTC
Labels: comp: core, comp: ivy
