### ISSUE TITLE
reflect-metadata 0.1.2 prevents shims from being concatenated

### ISSUE THREAD

**Issue by doxavore** [angular/angular#6940] opened 2016-02-07 18:19 UTC
Currently pinned to reflect-metadata@0.1.2, which has a Reflect.js with `"use strict"` outside of its IIFE. This prevents the reflect-metadata shim from being concatenated with the other shims (es6 and angular), as I get this error in angular-2.0.0-beta.3 from angular2-polyfills.js:
```
Uncaught TypeError: Cannot read property 'navigator' of undefined
```

The angular2-polyfill appropriately places its `use strict` directive, and reflect-metadata has this fixed in 0.1.3: https://github.com/rbuckton/ReflectDecorators/commit/239e7d7

The workaround for now is obviously to include Reflect.js in a separate request, but it would be great if we could pull in this change.

**Comment by amb-it-ion** [comment] 2016-02-09 16:50
+1

**Comment by danmarshall** [comment] 2016-02-10 23:04
possible dupe of https://github.com/angular/angular/issues/6706

**Closed** 2016-09-26 20:39 UTC
