### ISSUE TITLE
Attribute decorator should allow attribute name as optional

### ISSUE THREAD

**Issue by Serginho** [angular/angular#32658] opened 2019-09-13 10:06 UTC
# 🐞 bug report

### Affected Package
@angular/core
@angular/compiler

### Is this a regression?
Not sure, but I think not.

### Description
Attribute decorator is defined in `@angular/core` with `attributeName` as optional, but compiler throws an error when attributeName is missing.

I consider this a bug cause compiler doesn't meet the core specification.

## 🔬 Minimal Reproduction

This works

```typescript
constructor(@Attribute('customAttr') customAttr: string){}
```

This doesn't work

```typescript
constructor(@Attribute() customAttr: string) {}
```

## 🔥 Exception or Error

![3428681797-image](https://user-images.githubusercontent.com/315972/64854660-72820f80-d61e-11e9-9a6a-21198a93811d.png)

## 🌍  Your Environment

**Angular Version:**
Angular 7.2.8

**Comment by trotyl** [comment] 2019-09-13 12:03
Duplicate of https://github.com/angular/angular/issues/4607

**Comment by Serginho** [comment] 2019-09-13 12:12
But the other is closed.

After reading the old issue, I think it'd be better to change the core API and make required attributeName if there are problems with normalizations.

https://github.com/angular/angular/blob/bbb2798d416edffa5435792ee98ce16029e22682/packages/core/src/di/metadata.ts#L268-L278

**Comment by trotyl** [comment] 2019-09-13 12:22
> After reading the old issue, I think it'd be better to change the core API and make required attributeName if there are problems with normalizations.

Agreed, seems the type signature is incorrect.

**Comment by Airblader** [comment] 2019-09-13 13:03
I'd raise the question of why for attributes it has to be mandatory, but not for inputs. I believe these should be handled consistently.

**Comment by Serginho** [comment] 2019-09-13 13:09
@Airblader You have to read related issue https://github.com/angular/angular/issues/4607

**Comment by kara** [comment] 2020-05-29 22:22
Yeah, this is weird. We should make the attribute name required in the type to make it clear how we expect folks to use it.

**Closed** 2020-07-28 18:17 UTC
Labels: comp: core, core: di, cross-cutting: types, design complexity: low-hanging, freq1: low, severity1: confusing, state: confirmed, triage #1, type: bug/fix
