### ISSUE TITLE
Module Initialization not in a constructor?

### ISSUE THREAD

**Issue by clavecoder** [angular/angular#18032] opened 2017-07-10 13:36 UTC
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[ ] Bug report 
[X] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

The last comment of #1530 recommends initializing a module in it's constructor. 

## Expected behavior

Provide a way to initialize a module without having to do it in the constructor. Also consider error handling/logging concerns so that any initialization errors can be quickly recognized by the developer. Finally consider how it will work for the main module.

## What is the motivation / use case for changing the behavior?

Initializing in a constructor is considered an antipattern, as [explained by Misko Hevery](http://misko.hevery.com/code-reviewers-guide/flaw-constructor-does-real-work/).

## Please tell us about your environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX 
- Platform: 

Others:

</code></pre>

**Comment by tytskyi** [comment] 2017-07-10 14:11
Last comment is also by Misko Hevery :)

**Comment by trotyl** [comment] 2017-07-11 05:17
Would `ngDoBootstrap` fit this?

**Comment by clavecoder** [comment] 2017-07-11 10:58
Trotyl Yu commented via email that `ngDoBootstrap` might do the trick. Here's more on **ngDoBootstrap**

- [What is an *entry component*?](https://angular.io/guide/ngmodule-faq#what-is-an-entry-component)
- [Dependency injection in nested modules doesn't seem to work#comment](https://github.com/angular/angular/issues/10808#issuecomment-239823985) by @gdi2290

However, I would like to hear from the team on the best approach.

**Comment by trotyl** [comment] 2017-07-11 11:26
@clavecoder I have removed that comment since it's still app level, not module level, sorry for the disturbance.

**Comment by clavecoder** [comment] 2017-07-15 20:09
Consider a pattern similar to the one for app initialization, [APP_INITIALIZER](https://github.com/angular/angular/issues/9047#issuecomment-224075188) (comment by @captaincodeman) (See also [docs](https://angular.io/api/core/APP_INITIALIZER)).

**Comment by pkozlowski-opensource** [comment] 2021-08-04 09:50
This is a duplicate of #17606

**Closed by pkozlowski-opensource** 2021-08-04 09:50 UTC
Labels: comp: core, core: NgModule, feature, insufficient votes, votes required
