### ISSUE TITLE
Unsent Http Requests return invalid Status Code

### ISSUE THREAD

**Issue by danielrasmuson** [angular/angular#8297] opened 2016-04-27 20:25 UTC
**Current behavior**
Currently if a request fails to send the returned response code in the error handler is 200. This might happen when the user goes offline.

**Expected/desired behavior**
I would expect the status code to be 0.

Plunker Example
http://plnkr.co/edit/6MlCleNSNRh2GM5F3aPB?p=preview

**Comment by PeterOrneholm** [comment] 2016-05-10 13:27
I can confirm this is an issue. The problem seems to be at line 58-60 in https://github.com/angular/angular/blob/master/modules/%40angular/http/src/backends/xhr_backend.ts .
![image](https://cloud.githubusercontent.com/assets/1662918/15147959/91447110-16c3-11e6-88cd-00d47b7cd2be.png)

Those lines seems to solve an issue with Android, but they break other stuff when building an app supporting offline scenarios.

**Comment by awerlang** [comment] 2016-07-09 18:10
Fixed in rc.3 with #9355

**Closed** 2016-09-27 03:56 UTC
