### ISSUE TITLE
ContentChildren changed behavior in angular 9

### ISSUE THREAD

**Issue by matiskiba** [angular/angular#35199] opened 2020-02-06 22:49 UTC
### Affected Package
Can't tell

### Is this a regression?
yes. working well in angular 8

### Description
ContentChildren does not work well if content is passed under an ngIf (very common method to pass conditional content)

## 🔬 Minimal Reproduction
plunker: https://embed.plnkr.co/GXwlqpi2UPOVKaFvHBG7/

code:
```
import {ContentChildren,Component, NgModule, VERSION, ViewChild,QueryList} from '@angular/core'
import {BrowserModule} from '@angular/platform-browser'

@Component({
  selector: 'content-receiver',
  template: `
  contents:{{contents.length}}
  `,
})
export class ContentReceiver {
@ContentChildren("grouped") contents:QueryList<any>;
}


@Component({
  selector: 'my-app',
  template: `
<content-receiver>
<ng-container *ngIf="true">
<div #grouped>wow</div>
</ng-container>
</content-receiver>
  `,
})
export class App {}

@NgModule({
  imports: [ BrowserModule ],
  declarations: [ App, ContentReceiver ],
  bootstrap: [ App ]
})
export class AppModule {}

```

## 🔥 Exception or Error

> In angular 8 the output is:
> contents:1
> In angular 9 the output is
> contents:0
> 

The ContentChildren does not detect the content passed since it is under an *ngIf
using descendants:true or removing the <ng-container) resolves the issue - but they are not a solution for this case, as it is a common practice.

## 🌍  Your Environment

**Angular Version:**
Angular 9 vs Angular 8

**Anything else relevant?**
This completely broke my application
It also breaks Angular Material. See the following example (only 2 tabs appear)

> import {ContentChildren,Component, NgModule, VERSION, ViewChild,QueryList} from '@angular/core'
> import {BrowserModule} from '@angular/platform-browser'
> import {MatTabsModule} from "@angular/material/tabs";
> import {NoopAnimationsModule} from '@angular/platform-browser/animations';
> 
> @Component({
>   selector: 'my-app',
>   template: `
>   <mat-tab-group>
>     <mat-tab label="First"> Content 1 </mat-tab>
>     <ng-container *ngIf="show">
>     <mat-tab label="Second"> Content 2 </mat-tab>
>     </ng-container>
>     <mat-tab label="Third"> Content 3 </mat-tab>
>   </mat-tab-group>
>   `,
> })
> export class App {
> show=true;
> }
> 
> @NgModule({
>   imports: [ BrowserModule,MatTabsModule,NoopAnimationsModule ],
>   declarations: [ App ],
>   bootstrap: [ App ]
> })
> export class AppModule {}
>

**Comment by alexzuza** [comment] 2020-02-07 04:07
Angular 9 Ivy https://ng-run.com/edit/kQmM6THCMe9vqj27Feoa?aot=true
Angular 9 ViewEngine https://ng-run.com/edit/PQ8IFHMlq1ScQfW5Wej1

**Comment by thaoula** [comment] 2020-02-07 07:41
Hi All,

It seems we now need to specify {descendants: true} on ContentChildren to get the items nested items. 

```
@ContentChildren("directive", {descendants: true} ) contents:QueryList<any>;

<ng-container *ngIf='condition'>
 <div directive></div>
</ng-container>
```
In V8 we did not need to do this and I am not sure if this is a documented upgrade step. 

Regards,
Tarek

**Comment by pkozlowski-opensource** [comment] 2020-02-07 15:10
This is a duplicate / same issue as reported in #34768

We are still debating "the right thing to do" but for now there are 2 work-arrounds:
* use de-sugared version of `ngIf`:

```html
<content-receiver>
  <ng-template [ngIf]="true">
    <div #grouped>wow</div>
  </ng-template>
</content-receiver>
```

*  specify {descendants: true} on ContentChildren as suggested by @thaoula

**Comment by pkozlowski-opensource** [comment] 2020-02-12 15:28
I can confirm that this is a duplicate of #34768 - we are working on a solution for #34768

**Closed by pkozlowski-opensource** 2020-02-12 15:28 UTC
Labels: comp: ivy, state: needs eng review, type: bug/fix
