### ISSUE TITLE
Lifecycle hooks are not called when extends a class

### ISSUE THREAD

**Issue by tinayuangao** [angular/angular#23091] opened 2018-03-30 18:16 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

In material tree, the `MatTreeNestedNode` extends a mixin of `CdkTreeNestedNode`. `CdkTreeNestedNode` has `ngAfterContentInit` and `ngOnDestroy` https://github.com/angular/material2/blob/master/src/lib/tree/node.ts#L89
But the `ngAfterContentInit` and `ngOnDestroy` functions are not called in  `MatTreeNestedNode`. 
https://github.com/angular/material2/blob/master/src/cdk/tree/nested-node.ts#L71
This only happen in aot mode (in new angular-cli, the `--prod` mode)

We have the issue in material: https://github.com/angular/material2/issues/10437

## Expected behavior

The lifecycle hooks in `MatTreeNestedNode` should be called when it extends from `CdkTreeNestedNode`.

## Minimal reproduction of the problem with instructions

Same reproduction in https://github.com/angular/material2/issues/10437

`git clone https://github.com/DocLM/nested-tree-example`
`npm i -g @angular/cli@6.0.0-beta.8`

Then run
`ng serve --prod`        <--- This case the nested nodes are not expandable, because the lifecycle hooks are not called
`ng serve`  <-- This case the nested nodes are expandable and working properly

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [x ] Chrome (desktop) version 64.0.3282.186 
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v8.9.4  
- Platform:  Linux 

Others:

</code></pre>

**Comment by CaerusKaru** [comment] 2018-03-30 18:37
Ditto for Flex Layout

**Comment by trotyl** [comment] 2018-03-31 01:48
Duplicate of #19145, known issue when using mixins.

**Comment by mhevery** [comment] 2018-04-03 22:27
closing as dup

**Closed by mhevery** 2018-04-03 22:27 UTC
Labels: comp: core & compiler
