### ISSUE TITLE
<select [attr.multiple]="true"> does not behave the same as <select multiple>

### ISSUE THREAD

**Issue by rolandjitsu** [angular/angular#11737] opened 2016-09-19 23:32 UTC
**I'm submitting a ...**
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 

When using `<select>` with `<select [attr.multiple]="true">` the value for the select is not an array of values but only a single value.

**Expected behavior**

`<select [attr.multiple]>` should populate the value of the select control with an array of values.
But if I use `<select multiple>`, it would work.

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.0

* **Browser:** [Chrome 54] 

 
* **Language:** [TypeScript 2.0]
 
* **Node (for AoT issues):** `node --version` =   6.4

**Comment by vicb** [comment] 2016-09-19 23:38
Duplicate of https://github.com/angular/angular/issues/11716

**Closed by vicb** 2016-09-19 23:38 UTC
Labels: comp: forms
