### ISSUE TITLE
Angular Doesn't Work in IE11

### ISSUE THREAD

**Issue by montella1507** [angular/angular#13285] opened 2016-12-07 14:45 UTC
Angular doesn't work in IE11. This plunker is minimal reproduction:

Check this plunker please in IE11. 
https://plnkr.co/edit/LOJWgfDGvtKQzhxuD8Wa?p=preview

It doesn't work with webpack as well.

**Comment by DzmitryShylovich** [comment] 2016-12-07 14:48
welcome back :)

Duplicate of https://github.com/angular/angular/issues/13152

plnkr is missing the core-js

**Comment by mlaval** [comment] 2016-12-07 15:43
Thanks @DzmitryShylovich :)

**Closed by mlaval** 2016-12-07 15:43 UTC
