### ISSUE TITLE
fesm5::core.js::System.import() is deprecated and will be removed soon. Use import() instead.

### ISSUE THREAD

**Issue by isopen** [angular/angular#24307] opened 2018-06-05 16:24 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
![image](https://user-images.githubusercontent.com/7373292/40988844-55223cba-6916-11e8-90de-447926681de8.png)
```
WARNING in ./node_modules/@angular/core/fesm5/core.js
System.import() is deprecated and will be removed soon. Use import() instead.
The assembly was done via webpack.
```

## Expected behavior
Probably worth fixing in the core.
I locally put `import()` in core and the warning was gone.
Probably worth doing the same thing.

## Minimal reproduction of the problem with instructions
`npm start`

## What is the motivation / use case for changing the behavior?
Warning in the console about obsolete code in the kernel :(

## Environment

<pre><code>
Angular version: 6.0.3
 
For Tooling issues:
- Node version: 8.9.4
- Platform:  Debian

**Comment by trotyl** [comment] 2018-06-05 16:29
Duplicate of https://github.com/angular/angular/issues/21560

**Comment by isopen** [comment] 2018-06-05 16:41
@troryl The fact is that it moved to Angular 6. Past report to 5.

**Comment by sarunint** [comment] 2018-06-05 16:51
That issue still applies to Angular v6 though.

**Comment by isopen** [comment] 2018-06-05 17:18
![image](https://user-images.githubusercontent.com/7373292/40991763-ff539956-691e-11e8-84cb-3048087ecdc5.png)

**Comment by robwormald** [comment] 2018-06-05 18:20
closing as duplicate of https://github.com/angular/angular/issues/21560

**Closed by robwormald** 2018-06-05 18:20 UTC

**Comment by isopen** [comment] 2018-06-06 01:11
The question is not whether the duplicate is or not.
In which version will it be corrected?
