### ISSUE TITLE
Angular io. Fetching document error

### ISSUE THREAD

**Issue by Yerkon** [angular/angular#23357] opened 2018-04-13 04:43 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

![2018-04-13_10-42-42](https://user-images.githubusercontent.com/4002847/38717226-71d94e72-3f07-11e8-8d67-6eb7d3c924b9.png)

## Minimal reproduction of the problem with instructions

[Example](https://angular.io/guide/http#reading-the-full-response)

Others:
In Kazakhstan, Almaty

**Comment by santoshyadav198613** [comment] 2018-04-13 05:39
Works for me.

**Comment by ericmartinezr** [comment] 2018-04-13 07:56
Try cleaning your browser's cache. This happened a time ago to a lot of people (not the same error message though).

**Comment by gkalpak** [comment] 2018-04-13 07:56
This looks very similar to #22242. In that case, it turned out a Proxy was the problem (see https://github.com/angular/angular/issues/22242#issuecomment-367183189), but all the discussion (starting at https://github.com/angular/angular/issues/22242#issuecomment-366046033) is relevant.

My best guess is that the issue is caused by the Proxy doing some redirection that the SW does not expect. Since this is either an issue with the Proxy or (if it is the SW) it will be fixed by upgrading to the latest `@angular/service-worker` (tracked in #19795), I don't think there is much we can/should do.

**Comment by Yerkon** [comment] 2018-04-14 04:32
Yeaa, @ericmartinezr, @gkalpak. It's probably problem with **Proxy**.  Something happen with internet in our city maybe

**Comment by gkalpak** [comment] 2018-04-15 11:59
Thx for following up. I am going to close this then, since there isn't something we can do (afaict).

**Closed by gkalpak** 2018-04-15 11:59 UTC
Labels: comp: aio
