### ISSUE TITLE
CanDeactivate angular infinity look when I return a URLTREE instance

### ISSUE THREAD

**Issue by valterbarros** [angular/angular#41304] opened 2021-03-21 18:13 UTC
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/router

### Is this a regression?

not sure

### Description

I'm working on an app where I need to redirect the user from whatever page to a specific page when the user tries to back button on the browser or on the navigation back programmatic button.

## 🔬 Minimal Reproduction
https://github.com/valterbarros/angular-route-error-reproduce
ng serve
go to browser localhost:4200/screen1
open the inspector
go to browser localhost:4200/screen2
click go back on browser or click on screen 1 link that I put on the screen header

## 🔥 Exception or Error
It causes an infinity loop you can see the multiple console logs on the inspector

## 🌍  Your Environment

**Angular Version:**

```

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 10.1.7
Node: 14.12.0
OS: linux x64

Angular: 10.1.6
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1001.7
@angular-devkit/build-angular   0.1001.7
@angular-devkit/core            10.1.7
@angular-devkit/schematics      10.1.7
@angular/cli                    10.1.7
@schematics/angular             10.1.7
@schematics/update              0.1001.7
rxjs                            6.6.6
typescript                      4.0.7
```

**Comment by vugar005** [comment] 2021-03-21 21:03
Hi, I am not from core team but I checked the source and see that you redirect to in canDeactivate guard which you should NOT do. You should implement this logic in component where this guard applies to. See more here [example](https://www.tektutorialshub.com/angular/angular-candeactivate-guard/)

**Comment by atscott** [comment] 2021-03-22 16:58
Duplicate of #31385

**Closed by atscott** 2021-03-22 16:58 UTC

**Comment by valterbarros** [comment] 2021-03-22 17:59
hey man, thanks for your answer. Actually, it is not the case following the `CanDeactivate` interface who implement this is able to return `UrlTree` instance as the documentation says: https://angular.io/api/router/CanDeactivate
```
If any guard returns a UrlTree, the current navigation is cancelled and new navigation begins to the UrlTree returned from the guard.
```

it is exactly what I'm doing on the code returning a `UrlTree` instance as you can see here https://github.com/valterbarros/angular-route-error-reproduce/blob/e9fcfe4f6d517b79c0eb729f5e2a4e08c3be69fe/src/app/can-deactive.guard.ts#L20

`this.router.parseUrl('outdoor');` is able turn the url fragment on a UrlTree. reference: https://angular.io/api/router/Router#parseurl

methods like `canExit` inside the component is only in charge of return a boolean value to we be able to take a decision based on its return

**Comment by valterbarros** [comment] 2021-03-22 18:00
@atscott Uh thanks, I searched through the issue and didn't notice this #31385 issue
