### ISSUE TITLE
service-worker: ngsw-config.json timeout not evaluated for POST requests

### ISSUE THREAD

**Issue by ObeyYourMaster** [angular/angular#42830] opened 2021-07-12 23:09 UTC
### Which @angular/* package(s) are the source of the bug?

service-worker

### Is this a regression?

No

### Description

I'm not sure if this is a bug or intended behaviour.

When I'm setting a timeout for a datagroup for a POST request, then the timeout is not evaluated. While I understand that POST requests will not be cached, I'd still expect that the request will be intercepted by the ServiceWorker and aborted after the specified timeout. You can observe this behaviour in the browser DevTools for POST requests.

ngsw-config.json:
```
{
  "$schema": "./node_modules/@angular/service-worker/config/schema.json",
  "index": "/index.html",
  "assetGroups": [
    {
      "name": "app",
      "installMode": "prefetch",
      "resources": {
        "files": [
          "/index.html",
          "/manifest.webmanifest",
          "/*.css",
          "/*.js"
        ]
      }
    },
    {
      "name": "assets",
      "installMode": "lazy",
      "updateMode": "prefetch",
      "resources": {
        "files": [
          "/favicon.*",
          "/assets/**",
          "/*.(eot|svg|cur|jpg|png|webp|gif|otf|ttf|woff|woff2|ani)"
        ]
      }
    }
  ],
  "dataGroups": [
    {
      "name": "dummy",
      "urls": [
        "/dummy"
      ],
      "cacheConfig": {
        "strategy": "freshness",
        "maxSize": 1500,
        "maxAge": "365d",
        "timeout": "500u" // <- this is not evaluated :(
      }
    }
  ]
}
```

Reproduction: Follow the README in the repo

### Please provide a link to a minimal reproduction of the bug

https://github.com/ObeyYourMaster/angular-pwa-post-timeout

### Please provide the environment you discovered this bug in

```true
Angular CLI: 12.1.0-next.6
Node: 14.17.3
Package Manager: npm 6.14.13
OS: linux x64

Angular: 12.1.0-next.6
... animations, cli, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router
... service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1201.0-next.6
@angular-devkit/build-angular   12.1.0-next.6
@angular-devkit/core            12.1.0-next.6
@angular-devkit/schematics      12.1.0-next.6
@schematics/angular             12.1.0-next.6
rxjs                            6.6.7
typescript                      4.3.4
```

**Comment by gkalpak** [comment] 2021-07-13 14:07
This works as intended. The ServiceWorker does not really handle POST requests (it forwards them to the network). Also, the SW does not abort requests even for GET requests. All it does (if configured to do so) is decide to serve a GET request from the cache while waiting for a response from the server. Even in that case, it will not abort the request - it will wait for the response from the server and update the cache in the background.

Since there is nothing for the SW to serve for POST requests, the `timeout` option does not have any effect on them.

I hope that makes sense. Closing the issue, but feel free to continue the discussion below.

**Closed by gkalpak** 2021-07-13 14:07 UTC
Labels: comp: service-worker
