### ISSUE TITLE
Dynamic component for <select> options without template logic *ngIfs

### ISSUE THREAD

**Issue by leonelvsc** [angular/angular#35795] opened 2020-03-02 13:31 UTC
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/core

### Description
 There are cases where one needs to instantiate a component based on a user preference ie: 

```
<select [(ngModel)]="type" name="type">
    <option value="a">Type A</option>
    <option value="b">Type B</option>
</select>

<div *ngIf="type === 'a'">
    logic...
</div>

<div *ngIf="type === 'b'">
    logic...
</div>
```

### Describe the solution you'd like
 It would be great if angular provides a component that instantiates another component based on a component class decorator ie:

```
<select [(ngModel)]="type" name="type" #someRef>
    <option value="a">Type A</option>
    <option value="b">Type B</option>
</select>

<components-for #someRef [ngModel]="type"></components-for>
```

manager-for-type-a.component.ts
```
@ComponentsFor('a', someRefToTemplateOrComponent)
@Component({
    selector: 'app-manager-for-type-a',
    templateUrl: './manager-for-type-a.component.html',
    styleUrls: ['./manager-for-type-a.component.css'],
    viewProviders: [
        {
            provide: ControlContainer,
            useExisting: NgForm
        }
    ]
})
export class ManagerForTypeAComponent implements OnInit {

    constructor() {
    }

    ngOnInit() {
    };

    someMethod() {
    };
}
```

manager-for-type-b.component.ts
```
@ComponentsFor('b', someRefToTemplateOrComponent)
@Component({
    selector: 'app-manager-for-type-b',
    templateUrl: './manager-for-type-b.component.html',
    styleUrls: ['./manager-for-type-b.component.css'],
    viewProviders: [
        {
            provide: ControlContainer,
            useExisting: NgForm
        }
    ]
})
export class ManagerForTypeBComponent implements OnInit {

    constructor() {
    }

    ngOnInit() {
    };

    someMethod() {
    };
}
```

With this aproach we avoid template logic and re-evaluating all the time the *ngIfs conditions and have direct access to the component that needs to be instantiated

my current solution to this problem is:

some-service.ts

```
export const TYPE_MAP = {};

export class SomeService {
    typeMap = TYPE_MAP;

    constructor() {
    }
}
```

type-manager.interface.ts

```
export interface TypeManager {
    someMethod();
}

```

type-manager.decorator.ts

```
export function TypeManagerDecorator(aType: string) {
    return function _TypeManagerDecorator<T extends { new(...args: any[]): TypeManager}>(constr: T) {
        TYPE_MAP[aType] = constr;
    };
}
```

manager-for-type-a.component.ts
```
@TypeManagerDecorator('a')
@Component({
    selector: 'app-manager-for-type-a',
    templateUrl: './manager-for-type-a.component.html',
    styleUrls: ['./manager-for-type-a.component.css'],
    viewProviders: [
        {
            provide: ControlContainer,
            useExisting: NgForm
        }
    ]
})
export class ManagerForTypeAComponent implements OnInit, TypeManager {

    constructor() {
    }

    ngOnInit() {
    };

    someMethod() {
    };
}
```

manager-for-type-b.component.ts
```
@TypeManagerDecorator('b')
@Component({
    selector: 'app-manager-for-type-b',
    templateUrl: './manager-for-type-b.component.html',
    styleUrls: ['./manager-for-type-b.component.css'],
    viewProviders: [
        {
            provide: ControlContainer,
            useExisting: NgForm
        }
    ]
})
export class ManagerForTypeBComponent implements OnInit, TypeManager {

    constructor() {
    }

    ngOnInit() {
    };

    someMethod() {
    };
}
```

main.component.html
```

<form #form="ngForm" (ngSubmit)="form.valid" autocomplete="off">

    <select [(ngModel)]="type" name="type" (ngModelChange)="changeTypeManager($event)">
        <option value="a">Type A</option>
        <option value="b">Type B</option>
    </select>


    <ng-container #container></ng-container>

</form>
```

main.component.ts

```
@Component({
    selector: 'app-main',
    templateUrl: './main.component.html',
    styleUrls: ['./main.component.css']
})
export class MainComponent implements OnInit, OnDestroy {

    @ViewChild('container', {read: ViewContainerRef, static: true})
    private mainContainer: ViewContainerRef;
    private componentReference: ComponentRef<any>;

    constructor(
        private aService: SomeService,
        private resolver: ComponentFactoryResolver
    ) {

    }

    ngOnInit() {
    }

    ngOnDestroy() {
        if(this.componentReference) {
            this.componentReference.destroy();
        }
    }

    private changeTypeManager(aType: string) {
        if(this.componentReference) {
            this.componentReference.destroy();
        }

        if(!this.aService.typeMap[aType]) {
            throw new Error(`No class exists with the decorator @TypeManagerDecorator('${aType}')`);
        }

        const componentFactory = this.resolver.resolveComponentFactory(this.aService.typeMap[aType]);
        this.componentReference = this.mainContainer.createComponent(componentFactory);
    }

}
```

**Comment by paresh-bhave** [comment] 2020-03-02 16:11
Hi @leonelvsc 

Is your goal just to **avoid angular re-evaluating all the time the *ngIfs conditions***

Have you considered using change detection strategy ? Basically, you can define change detection strategy for a component to avoid the re-evaluation. A simple example is given below:

_app.component.html_

```html
<select [(ngModel)]="type" name="type" (change)="updateComponent()">
  <option value="a">Type A</option>
  <option value="b">Type B</option>
</select>

<div *ngIf="type === 'a'">
  logic a...
</div>

<div *ngIf="type === 'b'">
  logic b...
</div>
```
_app.component.ts_
```javascript
import {
  Component,
  ChangeDetectionStrategy,
  ChangeDetectorRef
} from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class AppComponent {
  type: string;

  constructor(private cdf: ChangeDetectorRef) {
    this.type = 'a';
    this.cdf.markForCheck();
  }

  updateComponent() {
    this.cdf.markForCheck();
  }
}
```

Read about more about it [here](https://angular.io/api/core/ChangeDetectorRef)

I hope this helps. If this doesn't satisfy your request or query, please ignore.

**Comment by leonelvsc** [comment] 2020-03-02 16:44
> Hi @leonelvsc
> 
> Is your goal just to **avoid angular re-evaluating all the time the _ngIfs conditions_**
> 
> Have you considered using change detection strategy ? Basically, you can define change detection strategy for a component to avoid the re-evaluation. A simple example is given below:
> 
> _app.component.html_
> 
> ```
> <select [(ngModel)]="type" name="type" (change)="updateComponent()">
>   <option value="a">Type A</option>
>   <option value="b">Type B</option>
> </select>
> 
> <div *ngIf="type === 'a'">
>   logic a...
> </div>
> 
> <div *ngIf="type === 'b'">
>   logic b...
> </div>
> ```
> 
> _app.component.ts_
> 
> ```js
> import {
>   Component,
>   ChangeDetectionStrategy,
>   ChangeDetectorRef
> } from '@angular/core';
> 
> @Component({
>   selector: 'app-root',
>   templateUrl: './app.component.html',
>   styleUrls: ['./app.component.scss'],
>   changeDetection: ChangeDetectionStrategy.OnPush
> })
> export class AppComponent {
>   type: string;
> 
>   constructor(private cdf: ChangeDetectorRef) {
>     this.type = 'a';
>     this.cdf.markForCheck();
>   }
> 
>   updateComponent() {
>     this.cdf.markForCheck();
>   }
> }
> ```
> 
> Read about more about it [here](https://angular.io/api/core/ChangeDetectorRef)
> 
> I hope this helps. If this doesn't satisfy your request or query, please ignore.

Hi @paresh-bhave , my bad i haven't explained my self correctly

what i mean is that we don't need any more template logic "*ngIfs" because we could build a map "hash" of the types and the components that needs to be instatiated witht direct access and no query at all

I have updated the issue to be more clear ( my english is basic ) so i hope it clarifies the feature request

**Comment by paresh-bhave** [comment] 2020-03-02 16:55
@leonelvsc thanks for the clarification. Perhaps I misunderstood the request. Probably, someone from core members can update about this. :)

**Comment by Achilles1515** [comment] 2020-03-02 21:25
I am doing something similar in a library I am working on, but using a 'multi' injection token instead of decorators.
```ts
providers: [
    {
      provide: TAB_MAP,
      useValue: { 'chrome-tab-component': ChromeTabComponent },
      multi: true,
    },
  ],
```
Other modules can continue to add to the TAB_MAP with new values.
Then I use dependency injection with Angular objects to get a reference to the mapping.
```ts
constructor(
    private _componentFactoryResolver: ComponentFactoryResolver,
    private _injector: Injector,
    @Inject(TAB_MAP) tabMapArray: Array<{ [key: string]: Type<ChromeTabComponent> }>
  ) {}
```

Just posting an alternative solution - nothing much else to add. But essentially you're asking for a simple way to associate a class with and/or generate a component from a string.

**Comment by leonelvsc** [comment] 2020-03-02 22:28
Yes that's what i'm talking about. Great solution by te way.

I just think that it will be nice if we could take away that "selection of a component" logic from the template in a generic, efficient and clean way

**Comment by pkozlowski-opensource** [comment] 2020-03-03 15:21
The topic of having a map of some arbitrary string to a class name (for the purpose of dynamic component instantiation) was raised several times in the past, ex.: #24360 or #33715. 

This issue here suggest a technical solution for a general problem of "maintain a string -> component class mapping" but as others commented - there are multiple ways of solving this. At this point I'm not clear if this belongs to the framework or, rather, should be solved in the user-land.

I'm going to close this one as a duplicate of #33715 since this is where we track a functional use-case. Feel free to add your proposed solutions in there.

**Closed by pkozlowski-opensource** 2020-03-03 15:21 UTC
Labels: comp: core

**Comment by pkozlowski-opensource** [comment] 2020-03-03 15:25
Duplicate of #33715
