### ISSUE TITLE
How to persist data when switching tabs/routes?

### ISSUE THREAD

**Issue by KalpeshChheda** [angular/angular#4350] opened 2015-09-24 09:04 UTC
When switching routes. How to keep state of the application as it is? I observed that Angular2 class is reinitialize every time I switch tabs but view is not reinitializing. 

Can we make class to initialize once when route is accessed first time only?

Eg.
http://plnkr.co/edit/Mw9OdOyHQZYt9KyyAS9d?p=preview

**Comment by kasperpeulen** [comment] 2015-09-24 13:19
I had the same problem while implementing routing for the standard TodoMVC application:
https://github.com/ng2-dart-samples/todomvc

The application uses routing to filter todos.I had to store the todos to local storage, otherwise the todos would be deleted by routing.

**Comment by KalpeshChheda** [comment] 2015-09-24 16:19
Ya but wouldn't it be good if my object does not dispose on route change?

**Comment by zoechi** [comment] 2015-09-24 18:22
Registering a service that holds the data in main() in DI and requesting it where ever you need to access the  data should work. I don't know how to achieve this in Ng2 DI

**Comment by KalpeshChheda** [comment] 2015-09-25 09:25
@zoechi Ya it can be done, but the point is angular 2 is still in alpha and if we get control of disposing component object would be nice to keep the state of the application with out any extra effort. I even don't know this would be possible or not. Can some one from angular team comment on this?

**Comment by robwormald** [comment] 2015-09-27 09:32
IMHO, like in Angular1, data/state/"Model" should live in a service. Whether or not components are disposed is a different issue, and a valid concern, but your data should probably live in a service.

**Comment by kasperpeulen** [comment] 2015-09-27 10:36
@robwormald my data does live in a service class, that I inject into my component class. But everytime I change the param of my component, my service class is disposed as well.

To fix that I had to save the the service class to local storage.

**Comment by robwormald** [comment] 2015-09-27 18:27
@kasperpeulen i extended @KalpeshChheda plunker to show how it works: http://plnkr.co/edit/twCC5Tpb8goX7NV0Cl6f?p=preview

Note that i'm using bindings the in *parent* component, and simply injecting into the children. If you add another binding in the children, that will force the injector to create another instance.

**Comment by robwormald** [comment] 2015-09-27 18:29
closing this as it works as intended. feel free to carry on the discussion.

**Closed by robwormald** 2015-09-27 18:29 UTC

**Comment by kasperpeulen** [comment] 2015-09-27 19:54
@robwormald 

not sure if it works as intended with *router parameters*. If I do the routing in my todomvc app without parameters, like this:

```
@RouteConfig(const [
  const Route(path: '/', component: TodoComponent, as: 'all'),
  const Route(path: '/active', component: TodoComponent, as: 'active'),
  const Route(path: '/completed', component: TodoComponent, as: 'completed'),
])
```

Then I don't loose the data. But if I do it with parameters, which looks cleaner:

```
@View(
    template: '''
    <section class="todoapp">
      <router-outlet></router-outlet>
    </section>
    ''',
    directives: const [ROUTER_DIRECTIVES])
@RouteConfig(const [const Route(path: '/:filter', component: TodoComponent)])

...

@Component(selector: 'todo-cmp', viewBindings: const [TodoStore])
@View(templateUrl: 'todo_cmp.html', directives: const [CORE_DIRECTIVES])
class TodoComponent {
  TodoStore todoStore;

  TodoComponent(this.todoStore, RouteParams routeParams) {
    todoStore.filter = routeParams.get('filter');
  }
```

Then I loose the data:

![](http://i.imgur.com/EqhpDSl.gif)

Here is my repo: https://github.com/kasperpeulen/todomvc-1 where I commented out the local storage logic, to make it more obvious that the model is lost while routing.

**Comment by robwormald** [comment] 2015-09-27 22:56
@kasperpeulen I had a quick look at your repo - I'll pull it down later this afternoon and have a proper look. Still pretty sure your issue is related to you defining the bindings in the child. 

Assuming you want a singleton todoStore (probably) - you should bind that in the root/app component, and not in the child. That way, each time a new todo component is instantiated, it'll look "up" to the parent component and grab the already instantiated store. 

Pascal's article here is a great read on the mechanics of this http://blog.thoughtram.io/angular/2015/08/20/host-and-visibility-in-angular-2-dependency-injection.html

**Comment by robwormald** [comment] 2015-09-27 22:59
The other thing to check, just to clarify what's going on, would be that your filter is working as you're expecting it to - that is, is the todoStore being reinstantiated, or is there another issue with the filtering logic perhaps?

**Comment by robwormald** [comment] 2015-09-28 04:01
@kasperpeulen so i pulled down your repo - you're definitely having the issue as described

if you remove the viewBindings option from your TodoComp, and add:
```dart
@Component(selector: 'app', bindings: const [TodoStore])

```
to your root component, it works as expected. hope that helps.

**Comment by kasperpeulen** [comment] 2015-09-28 17:10
@robwormald thanks a lot :) it is working now, will read the article you linked
