### ISSUE TITLE
feat(forms): addValidators 

### ISSUE THREAD

**Issue by indraraj26** [angular/angular#37412] opened 2020-06-03 06:46 UTC
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/forms

### Description
It will append validation to current validation that are in formControl.

### Problem
Suppose in ngOnInit You have Validators.required on control, later you want to add Validators.min(0)
So you will use setValidators(Validators.min(0)) then required is removed.
So now you will have to append both 
setValidators([Validators.required, Validators.min(0)]);

### Describe the solution you'd like
addValidators(newValidator: ValidatorFn | ValidatorFn[] | null): void;
This will be like Array.push()

**Comment by frederikprijck** [comment] 2020-06-03 06:58
Looks like a duplicate of https://github.com/angular/angular/issues/21410, https://github.com/angular/angular/issues/13461, https://github.com/angular/angular/issues/10567.

The main issue to follow for this feature is https://github.com/angular/angular/issues/13461

I think I also saw something about the idea of reworking the current Forms API, which might allow for an easier way to implement addValidators.

**Comment by petebacondarwin** [comment] 2020-06-03 14:54
Closing as a duplicate.

**Closed by petebacondarwin** 2020-06-03 14:54 UTC
Labels: comp: forms, type: feature
