### ISSUE TITLE
@Output emitter doesn't propagate events fired from ngOnDestroy hook

### ISSUE THREAD

**Issue by Katy91** [angular/angular#8727] opened 2016-05-19 14:51 UTC
Hello,

i want to send an event from ngOnDestroy but that is not possible.

The Problem is shown in the following demo.

https://plnkr.co/edit/4XVaVWJ97SYnpIjwQG82?p=preview

Is it possible to send an event from "ngOnDestroy" in context with the dynamic component loader?

Thanks

**Comment by zoechi** [comment] 2016-05-23 08:08
The Plunker seems to do what you want. `buttonIsDestroyed()` in `Buttons` is called (with Chrome). What issue exactly is the Plunker supposed to demonstrate?
I guess the request should be for `ngOnDestroy()` to wait for a Promise to resolve or similar.

**Comment by IgorMinar** [comment] 2016-10-04 16:13
ngOnDestroy is a hook that notifies the component that it is being destroyed. The decision about destruction has already been made and can't be changed. However the question remains if it should be possible to emit events via `@Output` emitter of this component. At first sight this doesn't look unreasonable but we need make sure that we can provide the guarantee that the events will always fire and will fire at the right time. This needs more investigation.

**Comment by mlaval** [comment] 2016-10-04 16:54
Duplicate of #5436

**Closed by mlaval** 2016-10-04 16:54 UTC
Labels: comp: core/compiler
