### ISSUE TITLE
UMD bundles in 6.0 now have dependency on tslib

### ISSUE THREAD

**Issue by uparlange** [angular/angular#22971] opened 2018-03-24 08:06 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

common-http bundle does not load properly... tslib import + fix required

## Expected behavior

Bundle should load properly without errors

## Minimal reproduction of the problem with instructions

https://plnkr.co/edit/evKCNS3ehGwhIt25S13X?p=preview
If you remove the two lines that correct the problem you'll see an error in Chrome console

## What is the motivation / use case for changing the behavior?

common-http bundle should load properly like all others angular bundles

## Environment

<pre><code>
Angular version: 6.0.0-rc.0

Problem exists since migration from http to common-http

Browser: ALL
 
For Tooling issues:
- Node version: N/A
- Platform:  Windows

Others:

</code></pre>

**Comment by trotyl** [comment] 2018-03-24 08:41
Duplicate of #22949, but better to keep this one.

**Closed** 2018-04-13 07:15 UTC
