### ISSUE TITLE
Angular Package Format 4.0 cannot be bundled with Rollup

### ISSUE THREAD

**Issue by steveblue** [angular/angular#17389] opened 2017-06-09 22:07 UTC
**I'm submitting a ...**  (check one with "x")
```
[ X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

 Packages that conform to Angular Package Format 4.0 cannot be imported into a project and then bundled with Rollup. The `index.ngfactory.js` file that is created for Angular Material, for example attempts to import itself.

```
import * as i0 from '@angular/core';
import * as i1 from '@angular/material';
import * as i2 from '@angular/common';
import * as i3 from '@angular/platform-browser';
import * as i4 from './index.ngfactory';
import * as i5 from '@angular/forms';
import * as i6 from '@angular/http';
export const MdCoreModuleNgFactory = i0.ɵcmf(i1.MdCoreModule, (([])), (_l) => {
```

This causes an error with Rollup, since now there is a circular import.

```
[14:44:43] LOG Rollup started bundling ngfactory
Error: A module cannot import itself
ngfactory/node_modules/@angular/material/typings/index.ngfactory.js (5:0)
3: import * as i2 from '@angular/common';
4: import * as i3 from '@angular/platform-browser';
5: import * as i4 from './index.ngfactory';
   ^
6: import * as i5 from '@angular/forms';
7: import * as i6 from '@angular/http';
```

**Expected behavior**

Rollup should be able to interpret ngfactory files, which is already setup to do, however this circular import breaks the build.

**Minimal reproduction of the problem with instructions**

Steps to reproduce are here: https://github.com/steveblue/angular2-rollup/issues/18

**What is the motivation / use case for changing the behavior?**

Rollup should be able to bundle packages that conform to the spec cleanly and without modification of `ngfactory` files.

**Please tell us about your environment:**

MacOS Sierra, VS Code, npm, Express

* **Angular version:** 2.0.X

4.2.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

This is a problem with the build, 
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5] Typescript 2.2.2

* **Node (for AoT issues):** `node --version` =  I tried both 6.5.0, 6.9.0

**Comment by sash-ua** [comment] 2017-06-10 05:30
Win10, node v.8, npm, Angular 4.2.1. The same issue.

**Comment by Karasuni** [comment] 2017-06-13 12:42
I'm also experiencing this issue.

The issue is probably related to https://github.com/angular/angular/commit/573b8611bc4ab85a7436ee110526678a0ecf6c76 (angular 4.2) and presumed to be fixed in https://github.com/angular/angular/commit/ed73d4f3ac6b542bf5ea3eb73fbe91e2ceabcdb4 (angular 4.2.2). It's been reported in cases where angular 4.2 is used with [`ng-lightning`](https://stackoverflow.com/questions/44520044/rollup-aot-error-a-module-cannot-import-itself/) or [`angular/material`](https://github.com/angular/material2/issues/5081) and prevents performing AoT compilation with rollup.

**Comment by karlhaas** [comment] 2017-06-13 13:18
Not fixed in 4.2.2:

```
{ Error: A module cannot import itself
    at error (/var/lib/jenkins/workspace/cies-UEYRTW7635K3HMG/Frontend/node_modules/rollup/src/utils/error.js:2:14)
    at Module.error$1 [as error] (/var/lib/jenkins/workspace/cies-UEYRTW7635K3HMG/Frontend/node_modules/rollup/src/Module.js:303:2)
    at /var/lib/jenkins/workspace/cies-UEYRTW7635K3HMG/Frontend/node_modules/rollup/src/Bundle.js:415:15
  code: 'CANNOT_IMPORT_SELF',
  pos: 166,
  loc: 
   { file: '/var/lib/jenkins/workspace/cies-UEYRTW7635K3HMG/Frontend/dist/tmp/node_modules/@angular/material/typings/index.ngfactory.js',
     line: 5,
     column: 0 },
  frame: '3: import * as i2 from \'@angular/common\';\n4: import * as i3 from \'@angular/platform-browser\';\n5: import * as i4 from \'./index.ngfactory\';\n   ^\n6: import * as i5 from \'@angular/forms\';\n7: import * as i6 from \'@angular/http\';' }
```

**Comment by rcferegrino** [comment] 2017-06-13 22:44
I'm having the same issue with progress Kendo modules:

`Error: A module cannot import itself (dist\node_modules\@progress\kendo-angular-dialog\dist\es\dialog-titlebar.component.ngfactory.js)
    at \node_modules\rollup\src\Bundle.js:335:14`

**Comment by sebek64** [comment] 2017-06-14 12:15
The same problem is with ngx-bootstrap and angular 4.2.0 to 4.2.2. This is quite a huge regression in 4.2 release, affecting many people and being reported in many projects as an issue.

**Comment by mlaval** [comment] 2017-06-14 15:35
Same issue as above with an Angular 4.2.2 project that uses https://github.com/ng-bootstrap/ng-bootstrap

**Comment by Eddman** [comment] 2017-06-15 14:25
Happens in all my projects that are using https://github.com/angular/material2. This is a huge regression. Please have a look ASAP!

**Comment by ettoredn** [comment] 2017-06-17 15:22
Same problem but using angular2-recaptcha.

```
> ngc -p tsconfig-aot.json && rollup -c

🚨   A module cannot import itself
aot/node_modules/angular2-recaptcha/lib/captcha.component.ngfactory.js (8:0)
 6: /* tslint:disable */
 7: import * as i0 from '@angular/core';
 8: import * as i1 from './captcha.component.ngfactory';
    ^
 9: import * as i2 from '@angular/forms';
10: import * as i3 from 'angular2-recaptcha/lib/captcha.component';
```

**Comment by huynhquocmy** [comment] 2017-06-18 02:47
Same here for my project, why everything so troublesome, should we revert back to angular 4.1 version ?

**Comment by hansl** [comment] 2017-06-20 23:33
@chuckjaz I have a reproduction setup here: https://github.com/hansl/angular-17389-repro

Steps:
1. `git clone https://github.com/hansl/angular-17389-repro`
1. `cd angular-17389-repro`
1. `npm install`
1. `$(npm bin)/ngc -p src/tsconfig.app.json`

The file `src/gendir/node_modules/angular2-recaptcha/lib/captcha.component.ngfactory.ts` will look like this:

```typescript
/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './captcha.component.ngfactory';
import * as i2 from '@angular/forms';
import * as i3 from 'angular2-recaptcha/lib/captcha.component';
import * as i4 from 'angular2-recaptcha/lib/captcha.service';
const styles_ReCaptchaComponent:any[] = ([] as any[]);
export const RenderType_ReCaptchaComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_ReCaptchaComponent,data:{}});
export function View_ReCaptchaComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[i0.ɵqud(402653184,1,{targetRef:0}),(_l()(),i0.ɵeld(0,[[1,0],['target',
      1]],(null as any),0,'div',([] as any[]),(null as any),(null as any),(null as any),
      (null as any),(null as any)))],(null as any),(null as any));
}
export function View_ReCaptchaComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),2,'re-captcha',([] as any[]),
      (null as any),(null as any),(null as any),i1.View_ReCaptchaComponent_0,i1.RenderType_ReCaptchaComponent)),
      i0.ɵprd(5120,(null as any),i2.NG_VALUE_ACCESSOR,(p0_0:any) => {
        return [p0_0];
      },[i3.ReCaptchaComponent]),i0.ɵdid(114688,(null as any),0,i3.ReCaptchaComponent,
          [i0.NgZone,i4.ReCaptchaService],(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,2,0);
  },(null as any));
}
export const ReCaptchaComponentNgFactory:i0.ComponentFactory<i3.ReCaptchaComponent> = i0.ɵccf('re-captcha',
    i3.ReCaptchaComponent,View_ReCaptchaComponent_Host_0,{site_key:'site_key',theme:'theme',
        type:'type',size:'size',tabindex:'tabindex',badge:'badge',language:'language'},
    {captchaResponse:'captchaResponse',captchaExpired:'captchaExpired'},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2hhbnNsL1NvdXJjZXMvX1RlbXAvYW5ndWxhci1pc3N1ZTE3Mzg5LXJlcHJvL25vZGVfbW9kdWxlcy9hbmd1bGFyMi1yZWNhcHRjaGEvbGliL2NhcHRjaGEuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL2hhbnNsL1NvdXJjZXMvX1RlbXAvYW5ndWxhci1pc3N1ZTE3Mzg5LXJlcHJvL25vZGVfbW9kdWxlcy9hbmd1bGFyMi1yZWNhcHRjaGEvbGliL2NhcHRjaGEuY29tcG9uZW50LmQudHMiLCJuZzovLy9Vc2Vycy9oYW5zbC9Tb3VyY2VzL19UZW1wL2FuZ3VsYXItaXNzdWUxNzM4OS1yZXByby9ub2RlX21vZHVsZXMvYW5ndWxhcjItcmVjYXB0Y2hhL2xpYi9jYXB0Y2hhLmNvbXBvbmVudC5kLnRzLlJlQ2FwdGNoYUNvbXBvbmVudC5odG1sIiwibmc6Ly8vVXNlcnMvaGFuc2wvU291cmNlcy9fVGVtcC9hbmd1bGFyLWlzc3VlMTczODktcmVwcm8vbm9kZV9tb2R1bGVzL2FuZ3VsYXIyLXJlY2FwdGNoYS9saWIvY2FwdGNoYS5jb21wb25lbnQuZC50cy5SZUNhcHRjaGFDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8ZGl2ICN0YXJnZXQ+PC9kaXY+IiwiPHJlLWNhcHRjaGE+PC9yZS1jYXB0Y2hhPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7O3VEQ0FBO01BQUE7TUFBQTs7O29CQ0FBO01BQUE7YUFBQTtRQUFBO01BQUEsa0NBQUE7VUFBQTtJQUFBOzs7Ozs7In0=```

Notice the import `i1` is the same file as the ngfactory outputted.

**Closed** 2017-06-21 23:19 UTC
Labels: comp: core & compiler, severity5: regression, type: bug

**Comment by steveblue** [comment] 2017-06-23 22:18
Verified fixed in `4.3.0-beta.0`

**Comment by ali-habibzadeh** [comment] 2017-08-13 12:40
Getting the same issues on Angular 4.3.4,  TS 2.4.2, ng-bootstrap 1.0.0-beta.1

**Comment by loicsalou** [comment] 2017-08-21 14:24
same problem here @angular-4.2.4 + @ng-bootstrap 1.0.0-beta.1 ts 2.4.2

**Comment by chuckjaz** [comment] 2017-08-21 16:47
@ali-habibzadeh @loicsalou This does not appear to be the same issue. Can one of you submit a new bug with steps attached that reproduce it (such as a link to a git repo).
