### ISSUE TITLE
Bug in Lifecycle Hooks Tutorial

### ISSUE THREAD

**Issue by jamercee** [angular/angular#22847] opened 2018-03-17 17:25 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[X] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
There is a bug in the lifecycle-hooks demonstration code https://angular.io/guide/lifecycle-hooks#peek-a-boo-all-hooks.  The `peek-a-boo-parent-component.ts` does not display log content. 

## Minimal reproduction of the problem with instructions

If you visit the live site, you can see that all actions taken on the Peek-A-Boo component display no log entries https://angular.io/generated/live-examples/lifecycle-hooks/stackblitz.html.

I am new to Angular, but I believe the source of the problem is how the `app/peek-a-boo-parent-component.ts` attempts to pull the log entries from the `LoggerService` through assigning the `hookLog` variable to `logger.logs`. It then attempts to display the log using the following code:

`        <div *ngFor="let msg of hookLog">{{msg}}</div>`

I was able to get the log output by changing the code to:

`        <div *ngFor="let msg of logger.logs">{{msg}}</div>`

**Comment by trotyl** [comment] 2018-03-17 18:05
Can be confirmed, it was broken by #20395.

**Comment by jamercee** [comment] 2018-03-17 19:27
Interesting. Isn't the correct approach with `peek-a-boo-parent` the same taken with `spy`  #20369 ?

**Comment by jenniferfell** [comment] 2018-05-15 23:12
Thanks @jamercee for submitting and @trotyl for identifying the PR with the fix. Closing.

If the issue isn't resolved to your satisfaction, please confirm with v6 and open a new issue. Thank you!

**Closed by jenniferfell** 2018-05-15 23:12 UTC
Labels: comp: docs
