### ISSUE TITLE
Cannot import language locales

### ISSUE THREAD

**Issue by johnholub1987** [angular/angular#20961] opened 2017-12-12 14:56 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Recently, my team has updates to angular 5.0.0 and we went to implement locale code to handle different numeric representation by region.  We read up on issues in 5.0.0 and updated to 5.1.  The problem is that every time we try to import the locales to register them we get an error thrown.

`import { registerLocaleData } from '@angular/common';
import localeFr from '@angular/common/locales/fr';
import localeFrExtra from '@angular/common/locales/extra/fr';`

The weird thing about the error is that it is saying it is an issue with reading the json metadata and it is saying the angular language service is 5.0.0 even though we just updated to 5.1.0.

> Search path: c:/Users/DevAdmin/Documents/GitHub/v15-a2/st-site/src/app
Failed to read JSON file c:/Users/DevAdmin/Documents/GitHub/v15-a2/st-site/node_modules/@angular/common/locales/fr.metadata.json
Config file name: c:/Users/DevAdmin/Documents/GitHub/v15-a2/st-site/tsconfig.json
Angular Language Service: 5.0.0-beta.5
TypeScript: 2.4.2
Error for getTemplateRefrences:
    TypeError: Cannot read property 'version' of null
    at C:\Users\DevAdmin\.vscode\extensions\Angular.ng-template-0.1.7\server\node_modules\@angular\language-service\bundles\language-service.umd.js:21442:70
    at Array.find (native)
    at ReflectorHost.BaseAotCompilerHost.readMetadata (C:\Users\DevAdmin\.vscode\extensions\Angular.ng-template-0.1.7\server\node_modules\@angular\language-service\bundles\language-service.umd.js:21442:42)
    at ReflectorHost.BaseAotCompilerHost.getMetadataFor (C:\Users\DevAdmin\.vscode\extensions\Angular.ng-template-0.1.7\server\node_modules\@angular\language-service\bundles\language-service.umd.js:21419:29)
    at StaticSymbolResolver.getModuleMetadata (C:\Users\DevAdmin\.vscode\extensions\Angular.ng-template-0.1.7\server\node_modules\@angular\language-service\bundles\language-service.umd.js:17910:45)
    at StaticSymbolResolver._createSymbolsOf (C:\Users\DevAdmin\.vscode\extensions\Angular.ng-template-0.1.7\server\node_modules\@angular\language-service\bundles\language-service.umd.js:17740:29)
    at StaticSymbolResolver.getSymbolsOf (C:\Users\DevAdmin\.vscode\extensions\Angular.ng-template-0.1.7\server\node_modules\@angular\language-service\bundles\language-service.umd.js:17725:14)
    at C:\Users\DevAdmin\.vscode\extensions\Angular.ng-template-0.1.7\server\node_modules\@angular\language-service\bundles\language-service.umd.js:16800:30
    at Array.forEach (native)
    at extractProgramSymbols (C:\Users\DevAdmin\.vscode\extensions\Angular.ng-template-0.1.7\server\node_modules\@angular\language-service\bundles\language-service.umd.js:16799:79)
getTemplateRefrences: 1154ms
SERVER ERROR: Cannot read property 'length' of null
TypeError: Cannot read property 'length' of null
    at Project.updateFileMap (C:\Users\DevAdmin\.vscode\extensions\Angular.ng-template-0.1.7\server\editorServices.js:797:94)
    at Project.updateGraph (C:\Users\DevAdmin\.vscode\extensions\Angular.ng-template-0.1.7\server\editorServices.js:815:14)
    at Project.finishGraph (C:\Users\DevAdmin\.vscode\extensions\Angular.ng-template-0.1.7\server\editorServices.js:807:14)
    at ProjectService.openConfigFile (C:\Users\DevAdmin\.vscode\extensions\Angular.ng-template-0.1.7\server\editorServices.js:1634:17)
    at ProjectService.openOrUpdateConfiguredProjectForFile (C:\Users\DevAdmin\.vscode\extensions\Angular.ng-template-0.1.7\server\editorServices.js:1486:41)
    at ProjectService.openClientFile (C:\Users\DevAdmin\.vscode\extensions\Angular.ng-template-0.1.7\server\editorServices.js:1404:23)
    at C:\Users\DevAdmin\.vscode\extensions\Angular.ng-template-0.1.7\server\documents.js:135:47
    at TextDocuments.logErrors (C:\Users\DevAdmin\.vscode\extensions\Angular.ng-template-0.1.7\server\documents.js:235:13)
    at C:\Users\DevAdmin\.vscode\extensions\Angular.ng-template-0.1.7\server\documents.js:131:74
    at handleNotification (C:\Users\DevAdmin\.vscode\extensions\Angular.ng-template-0.1.7\server\node_modules\vscode-jsonrpc\lib\main.js:353:21)
[Error - 9:42:43 AM] Notification handler 'textDocument/didOpen' failed with message: Cannot read property 'length' of null

If we run ng -v, it tells us that 5.1.0 is running but for some reason when importing it is using the 5.0.0 Angular language service.

> Angular CLI: 1.6.0 (e)
Node: 6.11.1
OS: win32 x64
Angular: 5.1.0

Also, this issue seems to persist until we remove the lines of code from our app.module, then close visual code, and force kill node.js.

## Expected behavior

This should simply just import the locale information to be able to register.

## Environment
Angular CLI: 1.6.0 (e)
Node: 6.11.1
OS: win32 x64
Angular: 5.1.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.0
@angular-devkit/build-optimizer: 0.0.35
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.41
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.7.4
@schematics/angular: 0.1.10
@schematics/schematics: 0.0.10
typescript: 2.4.2
webpack-dev-server: 2.9.7
webpack: 3.10.0
<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by vicb** [comment] 2017-12-12 23:25
I am sorry but I don't understand your issue.

Please:
- add a small repro case (github repo) - it should have a minimal amount of code,
- describe what you do to run the app,
- describe what you expect vs what you observe.

**Comment by trotyl** [comment] 2017-12-13 04:39
Duplicate of #20207, #20260, #20502, relates to #20880

**Comment by ocombe** [comment] 2017-12-14 16:45
Fixed with #20938

**Closed by ocombe** 2017-12-14 16:45 UTC
Labels: comp: i18n, flag: can be closed?
