### ISSUE TITLE
FormControl doesn't accept undefined as initial value

### ISSUE THREAD

**Issue by simhnna** [angular/angular#40978] opened 2021-02-24 11:27 UTC
# 🐞 bug report

### Affected Package

The issue is caused by package @angular/forms

### Is this a regression?

No

### Description

You can't initialize a FormControl with a value of undefined

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-ivy-bhpgjh?file=src/app/app.component.html

**Anything else relevant?**
Fixing the issue is breaking. But if forms have breaking changes at some point, it would be nice to have this as well. The Code is a little confusing if I need to set the value after creating the FormControl.

**Comment by AndrewKushnir** [comment] 2021-02-24 16:33
Hi @simhnna, it looks like this is a duplicate of #40608, so I'm closing this ticket. Please refer to issue #40608 to find additional information. Thank you.

**Closed by AndrewKushnir** 2021-02-24 16:33 UTC
Labels: comp: forms
