### ISSUE TITLE
Angular 11 - Documentation - Tutorial: Tour of Heroes  property not initialized error from typescript

### ISSUE THREAD

**Issue by DaveSharman** [angular/angular#39966] opened 2020-12-03 23:52 UTC
# 📚 Docs or angular.io bug report

### Description

Tour of heroes tutorial in Angular 11 (typescript version ~4.0.2), when instructed to add "selectedHero": Hero to the heroes.component, typescript now complains:

Property 'selectedHero' has no initializer and is not definitely assigned in the constructor.ts(2564)

## 🔬 Minimal Reproduction

Follow Tour of heroes documentation

### What's the affected URL?**
https://angular.io/tutorial/toh-pt2

### Reproduction Steps**
Follow Tutorial instructions

### Expected vs Actual Behavior**
Should not produce error

This can be worked around by changing the line of code to:
selectedHero!: Hero;     // Note the exclamation mark.

## 🔥 Exception or Error
<pre><code>

import { Component, OnInit } from '@angular/core';

import { Hero } from '../hero';
import { HEROES } from '../mock-heroes';

@Component({
  selector: 'app-heroes',
  templateUrl: './heroes.component.html',
  styleUrls: ['./heroes.component.scss'],
})
export class HeroesComponent implements OnInit {
  heroes = HEROES;
  selectedHero: Hero;                                     <--   ERROR occurs here.   fix by changing to selectedHero!: Hero;

  constructor() {}

  ngOnInit(): void {}

  onSelect(hero: Hero) {
    this.selectedHero = hero;
  }
}

</code></pre>

## 🌍  Your Environment
Windows 10 x64  

    _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 11.0.3
Node: 14.4.0
OS: win32 x64

Angular: 11.0.3
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.3
@angular-devkit/build-angular   0.1100.3
@angular-devkit/core            11.0.3
@angular-devkit/schematics      11.0.3
@schematics/angular             11.0.3
@schematics/update              0.1100.3
rxjs                            6.6.3
typescript                      4.0.5

### Browser info
No.

### Anything else relevant?
No

**Comment by DaveSharman** [comment] 2020-12-04 19:43
This appears to be caused by settings by default in the ts.json file


 "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "forceConsistentCasingInFileNames": true,
    "strict": true,                                                << Strict causes this.
    "noFallthroughCasesInSwitch": true,
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "es2015",
    "module": "es2020",
    "lib": [
      "es2018",
      "dom"
    ]
  },
  "angularCompilerOptions": {
    "strictInjectionParameters": true,
    "strictInputAccessModifiers": true,
    "strictTemplates": true
  }



vs the tsconfib.json  from the demo project downloaded from the Tour of heroes Tutorial.   Note the comments around fixing the code, and then enable these options.

`
/* To learn more about this file see: https://angular.io/config/tsconfig. */
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "forceConsistentCasingInFileNames": true,
    // TODO(gkalpak): Fix the code and enable this.
    // "strict": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "es2015",
    "module": "es2020",
    "lib": [
      "es2018",
      "dom"
    ]
  },
  "angularCompilerOptions": {
    "strictInjectionParameters": true,
    "strictInputAccessModifiers": true,
    // TODO(gkalpak): Fix the code and enable this (i.e. switch from `fullTemplateTypeCheck` to `strictTemplates`).
    "fullTemplateTypeCheck": true,// "strictTemplates": true
  }
}

`

**Comment by ippeiukai** [comment] 2021-02-18 10:34
I'm guessing beginners are led to choosing strict mode when starting a new project from angular CLI 11:
https://github.com/angular/angular-cli/pull/18983

Perhaps adding a warning not to choose strict mode in toh-pt0 would be desired for now?
(That is, of course, a temporary measure until the entire tutorial is rewritten with strict style.)

**Comment by petebacondarwin** [comment] 2021-02-18 10:40
I think that we should resolve the tutorial as soon as possible. We are going to be switching to --strict by default in v12.

**Comment by numberonepikey** [comment] 2021-03-05 11:15
Thank you this worked for me!

**Comment by GordonNomatter** [comment] 2021-03-14 23:10
In ch. 5 https://angular.io/tutorial/toh-pt5#add-heroservicegethero I have the same issue. I don't want to turn of strict mode. I want  a method to give a 404 when the id cannot be found in

HeroService
`getHero(id: number): Observable<Hero> {
  // TODO: send the message _after_ fetching the hero
  this.messageService.add(`HeroService: fetched hero id=${id}`);
  return of(HEROES.find(hero => hero.id === id));
}`
getHero(id: number): Observable<Hero | undefined> leads to errors in

HeroDetailComponent
`  getHero(): void { 
    const id = +this.route.snapshot.paramMap.get('id');
    this.heroService.getHero(id)
      .subscribe(hero => this.hero = hero)
  }`

again, const id = +this.route.snapshot.paramMap.get('id')!; would not help, since users could write anythin into the URL. Furthermore, undefined is not assignable to hero.

How can I prevent undefined states here?
Thanks for help.

Gordon

**Comment by nirmal-mobiquity** [comment] 2021-05-03 05:29
we can close this right ?

**Comment by petebacondarwin** [comment] 2021-05-03 11:12
Yes this is a duplicate of #39344

**Closed by petebacondarwin** 2021-05-03 11:12 UTC
Labels: P2, comp: docs
