### ISSUE TITLE
Angular issue while extending a subject class in Angular 10 in production mode

### ISSUE THREAD

**Issue by praveenkumargspr** [angular/angular#40866] opened 2021-02-16 11:57 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package "@angular/animations": "~10.0.5",
    "@angular/common": "~10.0.5",
    "@angular/compiler": "~10.0.5",
    "@angular/core": "~10.0.5",
    "@angular/forms": "~10.0.5",
    "@angular/platform-browser": "~10.0.5",
    "@angular/platform-browser-dynamic": "~10.0.5",
    "@angular/router": "~10.0.5",

### Is this a regression?

 Yes, the previous version(Angular 9) in which this bug was not present and this issue did not exist in Angular 11 also.
This issue only exists in Angular 10 only

### Description

 
we have a subject class in our project: **"export class OrdersService extends Subject <DataSource_1>"**

while extending that subject class in Angular 10 in Production mode.

We have been getting null value while extending and the following error:

**"Uncaught TypeError: Class extends value undefined is not a constructor or null".**

## 🔬 Minimal Reproduction

 This issue occurred due to extends the “Subject” class in Angular 10 in production mode.

**"export class OrdersService extends Subject <DataSource_1>"**

## 🔥 Exception or Error
<pre><code>

**"Uncaught TypeError: Class extends value undefined is not a constructor or null".**

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

"@angular/animations": "~10.0.5",
    "@angular/common": "~10.0.5",
    "@angular/compiler": "~10.0.5",
    "@angular/core": "~10.0.5",
    "@angular/forms": "~10.0.5",
    "@angular/platform-browser": "~10.0.5",
    "@angular/platform-browser-dynamic": "~10.0.5",
    "@angular/router": "~10.0.5",

</code></pre>

**Anything else relevant?**

**Comment by petebacondarwin** [comment] 2021-02-16 12:05
Please can you provide a reproduction of this problem that we can view?

**Comment by mlc-mlapis** [comment] 2021-02-16 12:06
@praveenkumargspr As in many other cases, here, without a simple reproduction demo, it's unrealistic that anybody can help with it.

**Comment by praveenkumargspr** [comment] 2021-02-16 12:29
Please check the below sample,
Sample:[MY-APP_1-1876156910.zip](https://github.com/angular/angular/files/5988521/MY-APP_1-1876156910.zip)

Replication Procedure: 
·         npm install. 
·         then run the above sample with command- “ng serve –prod”

**Comment by petebacondarwin** [comment] 2021-02-16 15:36
It looks like the import of `Subject` is being tree-shaken away during the production build. Turning off `optimisation`, which does tree-shaking (I believe) and minification, leads to a build that does not have the problem.

**Comment by petebacondarwin** [comment] 2021-02-16 21:01
@alan-agius4  pointed out that you are using the old-style rxjs imports which fall back onto the `rxjs-compat` library.
If you avoid this and use the newer import entry-points then these appear to work correctly.

You can apply the following diff to the reproduction to find it works again in production mode.

```diff
diff --git a/src/app/app.component.ts b/src/app/app.component.ts
index 6737fb4..61eecd0 100644
--- a/src/app/app.component.ts
+++ b/src/app/app.component.ts
@@ -5,7 +5,7 @@ import { EditService,GridComponent,FilterService, SortService, PageService, Dial
 import {   ToolbarService, ExcelExportService, PdfExportService,
   GroupService } from '@syncfusion/ej2-angular-grids';
 
-import { Observable } from 'rxjs/Observable';
+import { Observable } from 'rxjs';
 import { ClickEventArgs } from '@syncfusion/ej2-navigations'
 import { OrdersService } from "./order.service";
 import { DataStateChangeEventArgs } from "@syncfusion/ej2-grids";
@@ -45,6 +45,6 @@ export class AppComponent implements OnInit {
     let state = { skip: 0, take: 30 };
     this.service.execute(state);
   }
-    
+
 }
 
diff --git a/src/app/order.service.ts b/src/app/order.service.ts
index 61b66b5..9bdc4ca 100644
--- a/src/app/order.service.ts
+++ b/src/app/order.service.ts
@@ -1,9 +1,8 @@
 import { Injectable } from '@angular/core';
 import { Http } from '@angular/http';
 import { DataStateChangeEventArgs, Sorts, DataResult } from '@syncfusion/ej2-angular-grids'
-import { Observable } from 'rxjs/Observable';
-import { Subject } from 'rxjs/Subject';
-import { map } from 'rxjs/operators/map';
+import { Subject, Observable } from 'rxjs';^M
+import { map } from 'rxjs/operators';^M
 import { Predicate } from '@syncfusion/ej2-data';
 
 
@@ -47,15 +46,12 @@ export class OrdersService extends Subject<DataStateChangeEventArgs> {
     }
 
 
-    return this.http
-      .get(`${this.BASE_URL}?${pageQuery}${sortQuery}${filterQuery}&$count=true`)
-      .pipe(map((response: any) => response.json()))
-      .pipe(map((response: any) => {
-        return state.dataSource === undefined ? (<DataResult>{
+    return this.http.get(`${this.BASE_URL}?${pageQuery}${sortQuery}${filterQuery}&$count=true`).pipe(^M
+      map(response => response.json()),^M
+      map(response => state.dataSource === undefined ? (<DataResult>{^M
           result: response['value'],
           count: parseInt(response['@odata.count'], 10),
-        }) : response['value'];
-      }))
-      .pipe(map((data: any) => data));
+        }) : response['value']),^M
+      map((data: any) => data));^M
   }
 }
```

**Comment by petebacondarwin** [comment] 2021-02-16 21:01
Closing as this is working as expected with the correct rxjs imports.

**Closed by petebacondarwin** 2021-02-16 21:01 UTC
Labels: comp: animations, comp: core, needs reproduction
