### ISSUE TITLE
Input elements missing 'name' attribute inside the output of ngFor

### ISSUE THREAD

**Issue by NickLindahl** [angular/angular#19320] opened 2017-09-21 16:38 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
When using ngFor to render form controls in a template driven form, the name HTML attribute is not in the output that the browser renders

## Expected behavior
Input elements should have the name attribute

## Minimal reproduction of the problem with instructions

https://plnkr.co/edit/j9oGyeZdWloewNFBL8KD?p=preview
Inspect the rendered input elements in the preview.  The input outside the ngFor loop has a name attribute. None of the others do.

## What is the motivation / use case for changing the behavior?

We want to be able to reference elements by name via jQuery to glean custom information (stored in custom attributes) during validation

## Environment

<pre><code>
Angular version: 4.4.3

Browser:
- all browsers

</code></pre>

**Comment by AndrewKushnir** [comment] 2020-10-28 04:08
Closing this ticket as a duplicate of #11757. Please subscribe to #11757 for further discussion and updates.

**Closed by AndrewKushnir** 2020-10-28 04:08 UTC
Labels: P4, comp: forms, forms: DOM, freq2: medium, state: confirmed, triage #1, type: bug/fix
