### ISSUE TITLE
@angular/pwa: Angular Service Worker (ngsw-worker.js) does not install if there's a timer active.

### ISSUE THREAD

**Issue by mdarefull** [angular/angular#41223] opened 2021-03-15 23:00 UTC
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/pwa

### Is this a regression?
I don't know.

### Description
If during the initialization of the application, a setTimeout (or related) call is performed, the browser won't request ngsw-worker.js from the server (and register it as consequence) until the scheduled task executes.

## 🔬 Minimal Reproduction
https://github.com/mdarefull/pwa-appinsights-tests

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 11.2.4
Node: 14.9.0
OS: win32 x64

Angular: 11.2.5
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
... service-worker
Ivy Workspace: Yes
Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.4
@angular-devkit/build-angular   0.1102.4
@angular-devkit/core            11.2.4
@angular-devkit/schematics      11.2.4
@angular/cli                    11.2.4
@schematics/angular             11.2.4
@schematics/update              0.1102.4
rxjs                            6.6.6
typescript                      4.1.5
</code></pre>

**Anything else relevant?**

1. The easiest way to test the issue is to use http-server. I included it as a dev-dependency and added an npm script.
Just do `npm run server`
2. To test it, open a new blank tab, open developer tools, and ensure the application has been cleared and no service worker is registered. You can also simply use Incognito Mode.
3. Browse to http://localhost:8080
4. Keep an eye on the network tab, the service worker will be requested and registered immediately:
![image](https://user-images.githubusercontent.com/22510674/111231661-663a9200-85c8-11eb-85db-683838332e16.png)
5. Go to the app.component.ts and uncomment line 12. It is an On Init statement, that creates a timeout that prints a console msg after 30 seconds.
6. Repeat steps 2-4. This time, the service worker will be requested exactly after 30 seconds. You can put whatever number in the timeout for further testing.
![image](https://user-images.githubusercontent.com/22510674/111231909-d2b59100-85c8-11eb-8232-168dea1c021a.png)

The issue not only occurs with trivial timeouts as this one. I use NGRX and added a delay to an effect that executes when the app starts, and the result was the same.

What's worst, is that any 3rd party library could use something similar and break service workers. 

I originally found the issue on a production application, hosted in Azure App Service. It happened if I simply instantiate and load an Azure App Insights instance.
I tried to defer app insights initialization with a timeout/delay to 'give the browser time' to install the worker, and that's how I found the timer was an issue.

I tested the problem with the latest version of Chrome and Edge.

**Comment by mdarefull** [comment] 2021-03-15 23:06
BTW, while this issue is active, the Lighthouse reports for PWA fail with this message:
![image](https://user-images.githubusercontent.com/22510674/111232445-e281a500-85c9-11eb-8b22-6304df75b232.png)

**Comment by mdarefull** [comment] 2021-03-15 23:26
I've been doing some research and it seems that the framework waits for the app to stabilize before requesting the service worker. I deferred the initialization of my production app's App Insights library to after https://angular.io/api/core/ApplicationRef isStable emits true and it worked perfectly 👯 ...

But again, I wonder how someone would know about that and whether it will always be possible to defer initializations or required activities.

**Comment by gkalpak** [comment] 2021-03-16 17:20
Thx for reporting this and providing a minimal reproduction, @mdarefull 👍

The current behavior (which is intentional) is to wait for the app to stabilize (i.e. wait until there are no pending micro- and macro-tasks) before registering the ServiceWorker. This is in our opinion a good compromise between registering the SW as soon as possible but without affecting the application's first time load.

For reference, this is documented in the [ServiceWorker communication][1] guide and in the [SwRegistrationOptions][2] API docs (with references to [ApplicationRef#isStable][3]).

PWAs (and by extension SW) take a progressive enhancement approach, so failing to register the SW the first time (e.g. on first short (less than 30s) visit) is not catastrophic to the app's functionality. Of course, if you have specific requirements wrt to registering the SW, you can define a different [registrationStrategy][2].

##
> If this is a design decision, is it possible at least to make it more evident? Logging a warning when the 'wait until stabilizes' timeout expires explaining what happened.

Not sure what you mean by that. What would the warning say and how would that help?

##
Finally, regarding https://github.com/angular/angular/issues/41223#issuecomment-799813484, the installability issue is tracked in #41085, which has more context and work-arounds (until it is fixed properly).

##
I am going to close this issue, since everything works as expected (afaict), but happy to continue the discussion below.

[1]: https://angular.io/guide/service-worker-communications
[2]: https://angular.io/api/service-worker/SwRegistrationOptions#registrationStrategy
[3]: https://angular.io/api/core/ApplicationRef#is-stable-examples

**Closed by gkalpak** 2021-03-16 17:20 UTC
Labels: comp: service-worker

**Comment by mdarefull** [comment] 2021-03-16 17:52
Regarding my comment, the #41085 has nothing to do with it. #41085 is fine, I was able to apply the workaround and it worked fine.

I fully understand this is a design decision and it makes sense. My point now is that the reason might not be trivial. Yes, I read that very same huge yellow warning box and I was like: "Nah, I don't use polling or timers..." and then it wasn't installing because a 3rd party app that I use, presumably (I haven't seen the code) does it.

My point is that there might be tools out there that make the assumption that a worker will install immediately (or after a short amount of time) and then such tool won't behave as expected and we wouldn't know why...
Let's say that I want to run a Lighthouse or PWABuilder report to get suggestions, the report tells me there's no service worker available and that my web app is not a PWA... how would I know this was the reason? 

At least, the service worker should emit a console warning saying that it couldn't register because the app wasn't stable. I wouldn't have spent a whole day trying to figure out why was the service not installing, and yes, I feel bad I read the warning and completely removed it from my mind... but I don't think anybody would have done it much differently.

**Comment by gkalpak** [comment] 2021-03-16 19:24
> Regarding my comment, the #41085 has nothing to do with it. #41085 is fine, I was able to apply the workaround and it worked fine.

Not sure what you mean by "has nothing to do with it" 😕
Just to be clear, what I said above is that the issue you mentioned in https://github.com/angular/angular/issues/41223#issuecomment-799813484 is a totally different problem and it is being tracked in #41085.

##
> At least, the service worker should emit a console warning saying that it couldn't register because the app wasn't stable.

But the SW does not know whether it will be registered in a moment or never (i.e. if the pending micro-/macro-tasks will be completed in a second or never). Nor do I think it is reasonable to print a message immediately as that would confuse people (because the app will almost never be stable at once).

One solution could be to print a warning if it hasn't been registered after some time (say 10s), but then we should also print a message once it does register (say after another 20s), because otherwise it would seem as if it never registered by looking at the logs. But then again, I don't think it is a good DX adding logs to people's apps :grin:

##
> I wouldn't have spent a whole day trying to figure out why was the service not installing

That's definitely not an experience we want for our users 😅

How about this:
We could change the [SW schematic][1] (used to import `ServiceWorkerModule` into the app to explicitly list the `registrationStrategy` (potentially with a comment explaining what it means). I.e. change the generated code to something like:

```diff
-ServiceWorkerModule.register('ngsw-worker.js', { enabled: environment.production })
+ServiceWorkerModule.register('ngsw-worker.js', {
+  enabled: environment.production,
+  // Register the ServiceWorker as soon as the app is stable
+  // or after 30 seconds (which ever comes first).
+  registrationStrategy: 'registerWhenStable:30000',
+})
```

WDYT, @mdarefull?
[1]: https://github.com/angular/angular-cli/blob/f815e08000af2cb008716b5849bb55ff67b63b00/packages/schematics/angular/service-worker/index.ts#L94

**Comment by mdarefull** [comment] 2021-03-16 20:01
> Not sure what you mean by "has nothing to do with it" 😕
> Just to be clear, what I said above is that the issue you mentioned in #41223 (comment) is a totally different problem and it is being tracked in #41085.

You mixed feedbacks ;). If you use Lighthouse to run a report and the service worker doesn't install "immediately", Lighthouse doesn't detect a PWA at all! Same for other tools, they just say there's no service worker or manifest available... like if it were a normal web app.
The issue with #41085, which I've been contributing too as well, Lighthouse shows a warning instead.
Compare:
![image](https://user-images.githubusercontent.com/22510674/111232445-e281a500-85c9-11eb-8b22-6304df75b232.png)
(Service worker doesn't install immediately)
Vs.
![image](https://user-images.githubusercontent.com/22510674/111310107-7770b680-863b-11eb-8c3b-08d64736ce33.png)
(Service worker installs, but doesn't have offline access to index.htm.

> One solution could be to print a warning if it hasn't been registered after some time (say 10s), but then we should also print a message once it does register (say after another 20s), because otherwise it would seem as if it never registered by looking at the logs. But then again, I don't think it is a good DX adding logs to people's apps 😁
What I meant here is: The default approach is to wait until the app stabilizes with a timeout (30s default). Well, if the timeout runs out, log a warning stating: "App never stabilized, installing service worker manually".

> We could change the [SW schematic][1] (used to import ServiceWorkerModule into the app to explicitly list the registrationStrategy (potentially with a comment explaining what it means). I.e. change the generated code to something like:
Ok, let me better clarify the use-case. I don't think this is an up-front problem. If you were normally adding service workers, you would run the schematics and read through the docs and then you would learn about the 'stabilization thing'... that's acceptable... but what if the 'stabilization thing' occurs **after**? What if you had a PWA for months, then suddenly install a 3rd party app, or another developer adds a delay or a timer on an initialization task?

Again, you could argue that waiting for the 30s will do no harm... but to my point, there might be other apps that rely on the SW to be installed quickly (like Lighthouse or PWA)... imagine that 2 weeks after the 3rd party library was added I want to run Lighthouse to check the quality of my app and suddenly it is not a PWA anymore 👎 

That's why I think the warning is a more reactive approach... From my perspective, I was looking at the app and couldn't figure out why it was taking so long for the SW to be requested... And I had no idea the app wasn't stable either or that AppInsights would use a timer...

**Comment by gkalpak** [comment] 2021-03-18 15:10
> You mixed feedbacks ;). If you use Lighthouse to run a report and the service worker doesn't install "immediately", Lighthouse doesn't detect a PWA at all!

Ooops! My bad 😅
Sorry about that 😇

##
> Well, if the timeout runs out, log a warning stating: "App never stabilized, installing service worker manually".

I see what you mean now 🤔

I believe we agree that there should be a better way to make developers aware of what is causing the SW to not register immediately.

TBH, I am not sold on logging a warning when the timeout triggers (i.e. after 30s) :grin:
My main concerns are:
1. I don't like polluting people's logs (esp. in production) with messages that might give the impression something is not working as intended, while that might not be the case. In some cases, we are able to print warnings in development mode to make developers aware of potential issues, but omit these messages in production mode. Unfortunately, the SW will only work in production mode anyway, so there is no way to do that.
2. Usually I don't wait for 30s when trying to debug something that I expect to be happening on page load. So whether the developers get to see the warning is a matter of chance to some extent.

The reason I suggested adding an explicit `registrationStrategy` option (and a comment explaining the default behavior) is that the first place I look when things do not work with my SW is the registration (i.e. `ServiceWorkerModule.register()` in Angular apps). Either looking in the source code or adding a break-point in the running app.

So, by adding the option there (and the comment in the source code), I hope that people will be made aware of the existence of different registration strategies (and what the default one does) fairly early in their debugging process. Also, by having the property in the code, they will have an easy way to find out more through TS intellisense in their IDE.

Does that make sense?
Do you think it would it have saved you time if there was an explicit mention of the registration strategy in the `ServiceWorkerModule.register()` call?

**Comment by mdarefull** [comment] 2021-03-18 15:37
> Do you think it would it have saved you time if there was an explicit mention of the registration strategy in the ServiceWorkerModule.register() call?

I cannot be sure...

Let's try to put ourselves into a developer's head... One developer runs the PWA schematics, reads about everything, configures it as expected, and runs all the tests and reports... weeks later, another developer imports a library, validates the library is OK, story closed. A couple of monhts later, we run the Lighthouse report to check how we're doing and suddenly Lighthouse says we are not a PWA anymore... the developers would be really confused... at that moment, I doubt they will remember that PWA warning and would be like: "Oh yes, 3 weeks ago we installed this library that probably is making the app unstable and that's why..."

Also, it might be worth noticing, that while I was trying to figure out what was happening, I was looking at the application tab in chrome, and it was showing the web manifest, and then saying it couldn't find a service worker associated, etc...
I fear a failing Lighthouse report is not the worst that could happen... I fear some systems, apps, etc. expect the service worker to be installed within a couple of seconds after page load and behave in awkward ways if it doesn't do it.

I proposed a console warning because I send those logs to my server and analyze each one of them aiming for a 0 error 0 warning app. If I had received this warning, I would certainly try to fix or ignore it... You could receive a property that specifies log level that could also be useful for other things.

I might be overthinking this... but I'm smelling something funny... IMHO just importing a 3rd party library shouldn't so easily break something else with no-one knowing about it, no warning anywhere...

**Comment by gkalpak** [comment] 2021-03-19 15:14
Thx for sharing your thoughts, @mdarefull!

I understand that a warning would have worked in your case (having log monitoring and aiming for 0 warnings), but that is not necessarily what everyone does :grin:

From a framework perspective, it is 100% certain that you cannot make everyone happy. So, instead we choose to include paradigms and practices that would work/be useful for the majority of people. In this case, printing a warning might work for some people, annoy some people and not make much difference to others.

(For reference, there was a similar discussion around how the SW registration error is reported. Some users didn't like using `console.error()` and would prefer `ErrorHandler#handleError()`, which sounded reasonable. After making this innocent-looking change in #39990, several people reported that it didn't work for them, so we ended up reverting it in #40236.)

Hence, I am reluctant to introduce more logging when it is not certain that all or most users will benefit from it and that it will come in the way of their workflows.

##
For better or worse, I don't think we could prevent what you describe in your last comment (running Lighthouse some time after having installed the breaking dependency and finding out it is "broken"). I mean the only way to prevent it would be to install the SW immediately, which could affect the initial page load and thus offer a worse UX. It is a SW design decision to delay the registration in order to ensure the page load is not affected 🤷‍♂️

And again, it is not that the SW is never registrered and the functionality is broken. It's just that it may happen 30s later. In most cases, users keep tabs open for more than 30s (esp. for apps that they intend to interact with offline). And in any case, if one's app relies on having the SW installed immediately, they better have checks in place to ensure that that remains the case after every commit, so they are able to catch it asap 😛

##
Given that it is not possible (without sacrificing other benefits) to avoid the situation where introducing a recurring task (directly or indirectly) delays the SW registration, my reasoning for suggesting to explicitly specify the registration strategy in the `register()` call is that in most scenarios - regardless if you have log monitoring or not, regardless if you find about the breakage immediately or weeks later - it is very likely that you will look at the SW registration code early on in the debugging process ("Waaat? No SW? Let me check we are registering it.").

Therefore, I still believe it is a good first step at least. If we see more complains, we could consider taking more drastic measures.
Does that sound reasonable to you?

**Comment by mdarefull** [comment] 2021-03-19 15:40
Yup! Perfectly clear!

**Comment by gkalpak** [comment] 2021-03-26 16:22
FYI, I am working on explicitly specifying the SW registration strategy (As discussed above) in angular/angular-cli#20384 (still wip).
