### ISSUE TITLE
AoT compiling error when there is a service defined within some namespace

### ISSUE THREAD

**Issue by stepanmracek** [angular/angular#15613] opened 2017-03-30 11:06 UTC
Hello,
I'm submitting a bug report.

**Current behavior**
When I'm compiling my app with `ng build -prod` I got a following error:

```
ERROR in Illegal state: symbol without members expected, but got {"filePath":"/home/stepo/tmp/service-test/src/app/dummy.service.ts","name":"SomeNamespace","members":["DummyService"]}.

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in '/home/stepo/git/service-test/src'
 @ ./src/main.ts 4:0-74
 @ multi ./src/main.ts
```

**Expected behavior**
I expect the application compiles with no problems. If I use`ng build` or older Angular 2.x and angular-cli there is no problem.

**Minimal reproduction of the problem with instructions**
dummy.service.ts:
```
import { Injectable } from '@angular/core';
export namespace SomeNamespace {
  @Injectable()
  export class DummyService {
    getData() {
      return { 'hello': 'world' };
    }
  }
}
```
app.module.ts:
```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { HttpModule } from '@angular/http';
import { AppComponent } from './app.component';
import { SomeNamespace } from './dummy.service'
@NgModule({
  declarations: [AppComponent],
  imports: [BrowserModule, FormsModule, HttpModule],
  providers: [SomeNamespace.DummyService],
  bootstrap: [AppComponent]
})
export class AppModule { }
```
app.component.ts:
```
import { Component, OnInit } from '@angular/core';
import { SomeNamespace } from './dummy.service';

@Component({
  selector: 'app-root',
  template: `<pre>{{response}}</pre>`
})
export class AppComponent {
  response: string = 'waiting for response...';

  constructor(private s: SomeNamespace.DummyService) { }

  ngOnInit() {
    this.response = JSON.stringify(this.s.getData());
  }
}
```
**Environment:**
* **Angular version:** 4.0.0
```
{
  "name": "service-test",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/forms": "^4.0.0",
    "@angular/http": "^4.0.0",
    "@angular/platform-browser": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",
    "@angular/router": "^4.0.0",
    "core-js": "^2.4.1",
    "rxjs": "^5.1.0",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@angular/cli": "1.0.0",
    "@angular/compiler-cli": "^4.0.0",
    "@types/jasmine": "2.5.38",
    "@types/node": "~6.0.60",
    "codelyzer": "~2.0.0",
    "jasmine-core": "~2.5.2",
    "jasmine-spec-reporter": "~3.2.0",
    "karma": "~1.4.1",
    "karma-chrome-launcher": "~2.0.0",
    "karma-cli": "~1.0.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "karma-coverage-istanbul-reporter": "^0.2.0",
    "protractor": "~5.1.0",
    "ts-node": "~2.0.0",
    "tslint": "~4.5.0",
    "typescript": "~2.2.0"
  }
}
```
* **Browser:** all
* **Language:** TypeScript 2.2
* **Node (for AoT issues):** `node --version` =   v7.4.0, v7.8.0

**Comment by CaselIT** [comment] 2017-03-31 09:49
I've the same problem with angular 4.0.0
The error is thrown [here](https://github.com/angular/angular/blob/bebedfed24d6fbfa492e97f071e1d1b41e411280/packages/compiler/src/aot/static_symbol.ts)
From what I can understand this is thrown if there are any members inside a namespace.

In my case I have a configuration file with inner namespaces with constants, without any class or other objects, similar to the example shown below.
```ts

export namespace SomePart{
  export namespace Category1{
    export const Conf1= 7;
    // ...
  }
  export namespace Category2{
    export const Conf2= 7;
    // ...
  }
}
```

I have not tried aot on previous angular version.

**Comment by ashishmulaye** [comment] 2017-04-03 07:13
Hello,

I am also facing the same issue as mentioned by @stepanmracek.

**Comment by NicolasBoyer** [comment] 2017-06-06 16:21
Is there a workaround ? Or a solution ?

**Comment by Raoniw** [comment] 2017-11-08 16:13
I temporarily fixed this by exporting a class with the same name as the namespace. Now the application compiles again.

**Comment by j-langlois** [comment] 2018-03-31 05:28
Does not compile AOT though!

**Comment by j-langlois** [comment] 2018-03-31 19:45
Using a factory function for listing my provider did the trick to fix an AOT runtime error

**Comment by aberasarte** [comment] 2018-05-22 07:38
@j-langlois could you share an example showing how you did it?

**Comment by j-langlois** [comment] 2018-05-23 20:28
*clients-http.service.ts*
```javascript
export class ClientsServiceAgent {}
export namespace ClientsServiceAgent {
    @Injectable()
    export class HttpService implements IHttpService {
        getClient(id) {
        // ...
        }
    }
}
```

*clients-http-sender.module.ts*
```javascript
// create the service instance yourself
export function clientsHttpServiceFactory(httpClient: HttpClient, baseUrl?: string) {
  return new ClientsServiceAgent.HttpService(httpClient, baseUrl);
}
@NgModule({
  providers: [
    {
      provide: ClientsServiceAgent.HttpService,
      useFactory: clientsHttpServiceFactory,
      deps: [HttpClient, ClientsServiceAgent.CLIENTS_BASE_URL]
    },
  ]
})
export class ClientsHttpSenderModule { }
```

- Angular: 5.2.4
- Angular-CLI: 1.7.4**

Builds AOT through the CLI and is usable packaged on a npm repository through ng-packagr@^2.0.0

**Comment by aberasarte** [comment] 2018-05-24 09:38
@j-langlois thanks for the example, it works like a charm. I wasn't able to make it work for nested namespaces though. I tried exporting the "fake clasess" like this:

`
export class A {}
export namespace A{
    export class B {}
}
export namespace A.B{
	@Injectable()
	export class Service {
`
I guess that exporting the inner classes inside a namespace takes me to the original problem.

**Comment by simeyla** [comment] 2018-10-15 03:45
Is there ever going to be a better solution for this? 

Would Angular 7 for instance do anything different to offer an alternative way to do this?

**Comment by maurei** [comment] 2018-11-18 16:42
This just hit me

**Comment by zverbeta** [comment] 2019-02-21 12:08
any update?

**Comment by richardsengers** [comment] 2019-05-08 14:47
Took me quite some time before I debugged this.
Quite anoying there is still no response. Hopefully things will get better in version 8

**Comment by stepanmracek** [comment] 2019-05-09 13:38
There probably won't be any progress regarding fixing this bug. Using namespace is nowadays discouraged https://palantir.github.io/tslint/rules/no-namespace/

**Comment by simeyla** [comment] 2019-05-09 20:34
@stepanmracek I'm getting this issue with generated code by **nswag** (for swagger API) even though there isn't a `namespace` keyword in sight.

Obviously with generated code you'll get naming conflicts if you're not careful - so I like to import the generated code so that it's always qualified - (and I won't confuse `Customer` with `API.Customer`) :

    import { API } from "../../api/rr.api";

Then inject my generated client like this - (which fails under AOT unless I use the factory pattern for every client type).
 
                public customerClient: API.CustomersClient,

The beginning of the generated code is shown below - using `export module API` and no `namespace` keywords. 

Is this just two sides of the same coin (also discouraged) or is there any better way to fix this in future? Thanks

```

export module API {
export const API_BASE_URL = new InjectionToken<string>('API_BASE_URL');

export class ClientBase {
    
...

```

**Comment by simeyla** [comment] 2020-02-10 08:07
With Ivy compiler I get error messages like this when using my original 

    vendor.js:37405 ERROR NullInjectorError: R3InjectorError(AppModule)[InitializationService -> PricemodelService -> [object Object] -> [object Object] -> [object Object]]: 
    NullInjectorError: No provider for [object Object]!

I had to switch to using an injection token for each service client where I name the token `API_`.

In constructor:

    @Inject(API_PriceModelClient) private priceModelClient: API.PriceModelClient) 

In module provider:

     export const API_PriceModelClient = new InjectionToken<API.PriceModelClient>('API.PriceModelClient');

and

    {
        provide: API_PriceModelClient,
        useFactory: priceModelClientClassFactory,
        deps: [HttpClient, API.API_BASE_URL]
    },


Better ideas welcome! This is getting out of control!

**Comment by JoostK** [comment] 2020-03-19 12:00
@simeyla You are correct, it is indeed still broken in Ivy today! I opened PR #36106 that addresses this issue.

**Comment by JoostK** [comment] 2020-05-28 18:29
Confirmed in View Engine, but working correctly in Ivy since #36106.

**Comment by JoostK** [comment] 2021-05-14 11:50
Closing as resolved in Ivy as a DI token can now refer to a namespaced symbol.

**Closed by JoostK** 2021-05-14 11:50 UTC
Labels: P5, comp: compiler, engine: ve, freq1: low, state: confirmed, triage #1, type: bug/fix
