### ISSUE TITLE
How to only to enable when injected the directive

### ISSUE THREAD

**Issue by webnobushi** [angular/angular#7353] opened 2016-03-01 15:18 UTC
Here Place the sample.
https://plnkr.co/edit/lYNPii2BHNyeoWlMOXFb?p=preview

I want to enable the only when the directive injection.
However, when @Input attribute is present in the directive exception occurs.
the case of not inject a directive , I thought so as not to run the compilation of the template.

I've prepared a directive NoDebug As a workaround reluctantly.

I think a good way to the other ?

**Comment by pkozlowski-opensource** [comment] 2016-03-01 15:43
@webnobushi it is very hard to understand what you are trying to achieve based on your plunker and description.... As such it is next to impossible to help here....

You are getting an error as expected here since you are trying to bind to a property `value` that doesn't exist on unknown HTML elements. If you don't declare directives than there is no directive sitting on this unknown element and hence the error. This error is by design since we want to catch early on all the invalid bindings (ones that target non-existing properties).

**Comment by webnobushi** [comment] 2016-03-01 16:10
I had thought that only HtmlElement that matches the selector of the directive , which was injected is compiled .

The error is I understand that it is a specification .

I wanted to control the behavior of the component by the directive to be inserted without changing the structure of the template metadata.

**Comment by zoechi** [comment] 2016-03-01 16:20
Maybe you want to configure which directive to use using `PLATFORM_DIRECTIVES` http://blog.thoughtram.io/angular2/2015/11/23/multi-providers-in-angular-2.html ?

**Comment by naomiblack** [comment] 2016-03-02 20:02
Closing. Please move questions about how to use Angular to the discussion forum.

**Closed by naomiblack** 2016-03-02 20:02 UTC
