### ISSUE TITLE
Feature: Add Type To FormControl

### ISSUE THREAD

**Issue by ewaschen** [angular/angular#20642] opened 2017-11-27 15:58 UTC
## I'm submitting a...
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report
[X] Feature request
[ ] Documentation issue or request
[ ] Support request

## Current behavior
When creating a `FormControl` currently there is no way to specify the type within the FormControl or Group. (ie string, number, boolean, etc).

`accountName: new FormControl("", []),` This should be a string
'chequeNumber:  new FormControl(0, []),' This should be a number, however it can change later to a string by a simple assignment.

The only way I know how to set the type is to set the HTML input type
`<input matInput placeholder="Cheque Number" formControlName="chequeNumber" type="number" min="0" (blur)="formatNumber()" required>`

Or use a class with the values and their types

```
export class Cheque{
      chequeNumber: number;
}

this.depositForm= this.fb.group({
  cheque: this.fb.group(new Cheque())
});
```

## Expected behavior

It would be nice to be able to set the Types for each `FormControl `individually,

`chequeNumber: new FormControl(number, 0, [])`

## Minimal reproduction of the problem with instructions
N/A

## What is the motivation / use case for changing the behavior?
With specifying the type for a `FormControl`, the control will now know its type and offer it's associated functions, validation etc

Since Reactive Forms focus on explicit management, the type of each FormControl should be explicit as well and not rely on the initial value or the type specified in the HTML

## Environment
N/A

Browser:
N/A
 
For Tooling issues:
N/A

Others:

**Comment by Toxicable** [comment] 2017-11-27 17:46
duplicate of https://github.com/angular/angular/issues/13721

**Comment by kara** [comment] 2017-11-28 23:08
Looks related to #13721, so let's track it there.

**Closed by kara** 2017-11-28 23:08 UTC
Labels: comp: forms
