### ISSUE TITLE
Partial outage of angular.io in certain regions

### ISSUE THREAD

**Issue by jnizet** [angular/angular#21889] opened 2018-01-30 09:08 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Going to https://angular.io/guide/reactive-forms (directly, or by clicking on the entry in the sidebar), leads to 

> REQUEST FOR DOCUMENT FAILED.
> We are unable to retrieve the "guide/reactive-forms" page at this time. Please check your connection and try again later.

## Expected behavior

It should display the reactive forms page

## Environment

Browser:
- [x] Chrome (desktop) version 63.0.3239.132
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version 57.0.4
- [x] Safari (desktop) version 11.0.3
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
</code></pre>

**Comment by sarunint** [comment] 2018-01-30 11:24
I can access the mentioned page. Could you try from a different computer/network?

**Comment by jitmatz** [comment] 2018-01-30 11:41
Not working `Style Guid` Page also <https://angular.io/guide/styleguide>
Showing "REQUEST FOR DOCUMENT FAILED."

**Comment by jnizet** [comment] 2018-01-30 11:41
I tested from 3 different browsers on my desktop, including one which, I think, I never used to browse angular.io. I also tested on my cell phone (4G network, different from my wifi network). Same result.

**Comment by ericmartinezr** [comment] 2018-01-30 11:55
I'm seeing the same @jitmatz mentions. I see this in the console 

```js
Error fetching document ErrorcolumnNumber: 157325fileName: "https://angular.io/main.579e733255738eda4ef4.bundle.js"lineNumber: 1message: "Invalid data"stack: "MfbB/c</t.prototype.fetchDocument/<@https://angular.io/main.579e733255738eda4ef4.bundle.js:1:157325\nE9/g/l</e.prototype.__tryOrSetError@https://angular.io/main.579e733255738eda4ef4.bundle.js:1:52229\nE9/g/l</e.prototype.next@https://angular.io/main.579e733255738eda4ef4.bundle.js:1:51337\nE9/g/u</e.prototype._next@https://angular.io/main.579e733255738eda4ef4.bundle.js:1:50459\nE9/g/u</e.prototype.next@https://angular.io/main.579e733255738eda4ef4.bundle.js:1:50142\nnihM/s</e.prototype._next@https://angular.io/main.579e733255738eda4ef4.bundle.js:1:439244\nE9/g/u</e.prototype.next@https://angular.io/main.579e733255738eda4ef4.bundle.js:1:50142\nqqDE/s</e.prototype._next@https://angular.io/main.579e733255738eda4ef4.bundle.js:1:446887\nE9/g/u</e.prototype.next@https://angular.io/main.579e733255738eda4ef4.bundle.js:1:50142\nLaOa/s</e.prototype._next@https://angular.io/main.579e733255738eda4ef4.bundle.js:1:156362\nE9/g/u</e.prototype.next@https://angular.io/main.579e733255738eda4ef4.bundle.js:1:50142\nwP3s/a</e.prototype.notifyNext@https://angular.io/main.579e733255738eda4ef4.bundle.js:1:458514\nqgI0/c</e.prototype._next@https://angular.io/main.579e733255738eda4ef4.bundle.js:1:444962\nE9/g/u</e.prototype.next@https://angular.io/main.579e733255738eda4ef4.bundle.js:1:50142\nl@https://angular.io/main.579e733255738eda4ef4.bundle.js:1:39201\neFQL/</</s</e.prototype.invokeTask@https://angular.io/polyfills.4c154c76af75c37320fb.bundle.js:1:7900\nonInvokeTask@https://angular.io/main.579e733255738eda4ef4.bundle.js:1:73402\neFQL/</</s</e.prototype.invokeTask@https://angular.io/polyfills.4c154c76af75c37320fb.bundle.js:1:7813\neFQL/</</o</t.prototype.runTask@https://angular.io/polyfills.4c154c76af75c37320fb.bundle.js:1:3070\neFQL/</</c</t.invokeTask@https://angular.io/polyfills.4c154c76af75c37320fb.bundle.js:1:9014\nf@https://angular.io/polyfills.4c154c76af75c37320fb.bundle.js:1:20182\nh@https://angular.io/polyfills.4c154c76af75c37320fb.bundle.js:1:20417\n"__proto__: Object { … } logger.service.ts:15:4
```

Here's an image for better visualization ![image](https://user-images.githubusercontent.com/13039652/35565161-24bf5ee2-059b-11e8-9e1b-c3cbc1dca816.png). 

There's nothing special on network tab.

**Comment by rasca** [comment] 2018-01-30 12:42
Not working for me neither

**Comment by petebacondarwin** [comment] 2018-01-30 13:14
Can you try posting what is the response for this URL: https://angular.io/generated/docs/guide/reactive-forms.json

**Comment by petebacondarwin** [comment] 2018-01-30 13:14
Also, do you get the same problem with `https://next.angular.io/guide/reactive-forms`?

**Comment by jnizet** [comment] 2018-01-30 13:20
> Can you try posting what is the response for this URL: https://angular.io/generated/docs/guide/reactive-forms.json

Sure. According to Chrome's dev tools network pane, the response is empty, end the response's content-length header value is 10.

> Also, do you get the same problem with https://next.angular.io/guide/reactive-forms?

No, I don't get the same problem. This one works fine.

**Comment by petebacondarwin** [comment] 2018-01-30 14:01
I believe that Firebase (who hosts our docs) might be having a caching issue. Although their status page suggests otherwise: https://status.firebase.google.com/

**Comment by jitmatz** [comment] 2018-01-30 14:07
Adding more pages
https://angular.io/guide/testing
https://angular.io/guide/aot-compiler
Error: `REQUEST FOR DOCUMENT FAILED.`

**Comment by IgorMinar** [comment] 2018-01-30 17:35
I just escalated to Firebase and asked @jasonaden (the current caretaker) to be the incident manager.

**Comment by IgorMinar** [comment] 2018-01-30 17:58
We were asked to redeploy the app. That already happened. Can someone confirm that the issue is now resolved in the affected regions?

**Comment by jasonaden** [comment] 2018-01-30 18:02
@jnizet @jitmatz Are you able to check again?

**Comment by jnizet** [comment] 2018-01-30 18:05
I managed to view all the pages mentioned in this issue (reactive forms, testing, aot, style guide). But I had to deactivate/clear the cache to not have the "REQUEST FOR DOCUMENT FAILED." page.

**Comment by davidsavagejr** [comment] 2018-01-30 18:19
I too had this issue, can confirm resetting cache and refreshing fixed it

**Comment by jasonaden** [comment] 2018-01-30 18:32
It appears there was an upstream caching issue. This cache has been cleared, and we are following up to work out how to detect a similar issue in the future.

Thanks for reporting!

**Closed by jasonaden** 2018-01-30 18:32 UTC
Labels: comp: aio, type: bug

**Comment by jitmatz** [comment] 2018-01-30 18:52
Issue solved after clearing the cache.

**Comment by IgorMinar** [comment] 2018-01-30 19:30
We got a confirmation that there was an intermittent firebase issue yesterday that caused certain edge caches to cache bad content. Once we redeployed the project today, the caches were purged all around the world and that resolved the problem. We are following up with the firebase team internally to ensure that the same issue doesn't occur again.

Sorry about the troubles.

**Comment by Seymur** [comment] 2018-01-31 20:15
I can't access angular.io,  material.angular.io, cli.angular.io

**Comment by gkalpak** [comment] 2018-01-31 22:10
@Seymur, have you cleared the cache?

**Comment by Seymur** [comment] 2018-01-31 23:07
@gkalpak yeap. Even I have tried different devices and browsers. Same result. Site hangs on loading.

**Comment by gkalpak** [comment] 2018-02-01 09:15
Do you get any errors in the console?
