### ISSUE TITLE
Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "add-to-cart-button" has already been used with this registry

### ISSUE THREAD

**Issue by KrunalC28** [angular/angular#33619] opened 2019-11-06 09:45 UTC
**Description**

When I use angular-element in another angular application and deploy it on PCF, I get above error.

In localhost it's not an issue. It's working as expected. But when i do staticfile push on PCF,  I get same error. After analyzing i found that ngDoBootStrap of angular element called twice.

**Package.json**

{
  "name": "custom-element-app",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build --prod --output-hashing none && gulp element_bundle",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~8.2.11",
    "@angular/common": "~8.2.11",
    "@angular/compiler": "~8.2.11",
    "@angular/core": "~8.2.11",
    "@angular/elements": "^8.2.13",
    "@angular/forms": "~8.2.11",
    "@angular/platform-browser": "~8.2.11",
    "@angular/platform-browser-dynamic": "~8.2.11",
    "@angular/router": "~8.2.11",
    "@webcomponents/custom-elements": "^1.3.0",
    "custom-event-polyfill": "^1.0.7",
    "document-register-element": "^1.7.2",
    "gulp": "^4.0.2",
    "gulp-concat": "^2.6.1",
    "gulp-minify": "^3.1.0",
    "rxjs": "~6.4.0",
    "tslib": "^1.10.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.803.14",
    "@angular/cli": "~8.3.14",
    "@angular/compiler-cli": "~8.2.11",
    "@angular/language-service": "~8.2.11",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "@webcomponents/webcomponentsjs": "^2.3.0",
    "codelyzer": "^5.0.0",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.5.3"
  }
}

**Gulpfile For Concatenation**

var gulp = require('gulp');
var concat = require('gulp-concat');
var dir = './dist/custom-element-app';

gulp.task('element_bundle', function () {
  return gulp
    .src([
      `${dir}/runtime-es2015.js`,
      `${dir}/styles.css`,
      `${dir}/scripts.js`,
      `${dir}/main-es2015.js`,
      `${dir}/polyfills-es2015.js`])
    .pipe(concat('element.min.js'))
    .pipe(gulp.dest(`${dir}/`));
});

**Angular Element app.module.ts**
import { BrowserModule } from '@angular/platform-browser';
import { NgModule, Injector, DoBootstrap } from '@angular/core';
import { createCustomElement } from '@angular/elements';
import { AppComponent } from './app.component';
import { AddToCartComponent } from './addToCart/addToCart.component';

@NgModule({
  declarations: [
    AddToCartComponent,
    AppComponent
  ],
  imports: [
    BrowserModule
  ],
  providers: [],
  bootstrap: [],
  entryComponents: [ AddToCartComponent ]
})
export class AppModule implements DoBootstrap { 
  constructor(private injector: Injector) {
    const el = createCustomElement(AddToCartComponent, {
      injector: this.injector
    });
    customElements.define(`add-to-cart-button`, el);
  }

  ngDoBootstrap() {  
  }
}

**Parent Angular App - angular.json**

{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "newProjectRoot": "projects",
  "projects": {
    "parent-ang-app": {
      "projectType": "application",
      "schematics": {
        "@schematics/angular:component": {
          "style": "scss"
        }
      },
      "root": "",
      "sourceRoot": "src",
      "prefix": "app",
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "dist/parent-ang-app",
            "index": "src/index.html",
            "main": "src/main.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "tsconfig.app.json",
            "aot": false,
            "assets": [
              "src/favicon.ico",
              "src/assets",
              "src/manifest.yml",
              "src/Staticfile"
            ],
            "styles": [
              "src/styles.scss"
            ],
            "scripts": [ 
              "src/scripts/element.min.js"
            ]
          },
          "configurations": {
            "production": {
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true,
              "budgets": [
                {
                  "type": "initial",
                  "maximumWarning": "2mb",
                  "maximumError": "5mb"
                },
                {
                  "type": "anyComponentStyle",
                  "maximumWarning": "6kb",
                  "maximumError": "10kb"
                }
              ]
            }
          }
        },
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "browserTarget": "parent-ang-app:build"
          },
          "configurations": {
            "production": {
              "browserTarget": "parent-ang-app:build:production"
            }
          }
        },
        "extract-i18n": {
          "builder": "@angular-devkit/build-angular:extract-i18n",
          "options": {
            "browserTarget": "parent-ang-app:build"
          }
        },
        "test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "main": "src/test.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "tsconfig.spec.json",
            "karmaConfig": "karma.conf.js",
            "assets": [
              "src/favicon.ico",
              "src/assets"
            ],
            "styles": [
              "src/styles.scss"
            ],
            "scripts": []
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": [
              "tsconfig.app.json",
              "tsconfig.spec.json",
              "e2e/tsconfig.json"
            ],
            "exclude": [
              "**/node_modules/**"
            ]
          }
        },
        "e2e": {
          "builder": "@angular-devkit/build-angular:protractor",
          "options": {
            "protractorConfig": "e2e/protractor.conf.js",
            "devServerTarget": "parent-ang-app:serve"
          },
          "configurations": {
            "production": {
              "devServerTarget": "parent-ang-app:serve:production"
            }
          }
        }
      }
    }},
  "defaultProject": "parent-ang-app"
}

**Comment by KrunalC28** [comment] 2019-11-06 09:47
I have tried with removing polyfills.js, but get the same error

**Comment by SantiagoIlli** [comment] 2019-11-06 15:15
Hi!
I had a similar issue with angular elements, this may be related with it.
https://github.com/angular/angular/issues/32726

**Comment by IgorMinar** [comment] 2019-11-06 23:27
(This does seem to be a dupe of #32726.)

It seems that you are calling `customElements.define('add-to-cart-button', ...)` multiple times within the same `window` context.

I suggest you search through the loaded code and find the duplicates, and then ensure that the registration happens just once.

alternatively you can guard the `customeElements.define` call with an `if` check that verifies that a custom element with that selector has not been registered yet.

**Closed by IgorMinar** 2019-11-06 23:27 UTC

**Comment by KrunalC28** [comment] 2019-11-07 03:46
@IgorMinar 

This is not a duplicate. I am not using multiple elements. 

I have created one consumer angular 8 app. I have created another angular 8 element. I am using that element in consumer app. I am not facing issue on localhost.

When I run production build and deploy dist folder on PCF using staticfile buildpack, I am getting this issue.

When I debugged it, then I found that ngDoBootStrap of angular element called twice. 
1. From minifiedJs of angular-element
2. From runtime.js of consumer-app

I have already tried with below approaches
- Passing the consumer zone to angular-element
- Providing if condition - in this case angular-element does not render on PCF. It's content is invisible
- I have removed polyfills of angular-element. But the issue persist.

Please don't close this issue. It's not duplicate.
