### ISSUE TITLE
Angular can't disable Ivy

### ISSUE THREAD

**Issue by hamzahamidi** [angular/angular#39297] opened 2020-10-15 21:54 UTC
# 🐞 bug report

### Affected Package

The issue is caused by package @angular/compiler-cli

### Is this a regression?

I don't know

### Description

 A clear and concise description of the problem...

I can't seem to disable Ivy in Angular v9 although my production config is 
```
  "angularCompilerOptions": {
    "enableIvy": false
  }
```
I though build my library using ng build --prod but even so it still uses Ivy

## 🔬 Minimal Reproduction

 https://stackblitz.com/...

## 🔥 Exception or Error
<pre><code>

> node --eval "console.error('ERROR: Trying to publish a package that has been compiled by NGCC. This is not allowed.\nPlease delete and rebuild the package, without compiling with NGCC, before attempting to publish.\nNote that NGCC may have been run by importing this package into another project that is being built with Ivy enabled.\n')" && exit 1

ERROR: Trying to publish a package that has been compiled by NGCC. This is not allowed.
Please delete and rebuild the package, without compiling with NGCC, before attempting to publish.
Note that NGCC may have been run by importing this package into another project that is being built with Ivy enabled.

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.0.7
Node: 12.18.1
OS: linux x64

Angular: 9.1.12
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.900.7
@angular-devkit/build-angular      0.900.7
@angular-devkit/build-ng-packagr   0.900.7
@angular-devkit/build-optimizer    0.900.7
@angular-devkit/build-webpack      0.900.7
@angular-devkit/core               9.0.7
@angular-devkit/schematics         9.0.7
@angular/cdk                       9.2.4
@angular/cli                       9.0.7
@angular/flex-layout               9.0.0-beta.31
@angular/material                  9.2.4
@ngtools/webpack                   9.0.7
@schematics/angular                9.0.7
@schematics/update                 0.900.7
ng-packagr                         9.1.5
rxjs                               6.6.3
typescript                         3.6.5
webpack                            4.41.2

</code></pre>

**Anything else relevant?**

**Comment by hamzahamidi** [comment] 2020-10-15 23:18
Same happens with Angular v10 too:

Env:
<pre>
<code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 10.1.7
Node: 12.18.1
OS: linux x64

Angular: 10.1.6
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1001.7
@angular-devkit/build-angular      0.1001.7
@angular-devkit/build-ng-packagr   0.1001.7
@angular-devkit/core               10.1.7
@angular-devkit/schematics         10.1.7
@angular/cdk                       10.2.5
@angular/cli                       10.1.7
@angular/flex-layout               9.0.0-beta.31
@angular/material                  10.2.5
@schematics/angular                10.1.7
@schematics/update                 0.1001.7
ng-packagr                         10.1.2
rxjs                               6.6.3
typescript                         4.0.3
</code>
</pre>

**Comment by petebacondarwin** [comment] 2020-10-17 12:00
@hamzahamidi I would guess that what is happening, is that you are indeed building your library in ViewEngine mode (i.e. Ivy disabled) but then you are using that local library in a test application, which is running ngcc over the generated library code, which converts it to Ivy. You are then trying to public the package to npm, but this is disallowed, since you should not be pushing ivy code to npm. Can you check if this is the case? If so, then the solution is to either rebuild the library (without running the tests) before you publish it, or to run `npm pack` on the library when you build it before you run the tests, and then to publish the packed file instead of the folder.

**Comment by hamzahamidi** [comment] 2020-10-17 23:57
Here's the project https://github.com/hamzahamidi/ajsf, but in my case I published the library by removing the pre-deployment script.

**Comment by petebacondarwin** [comment] 2020-10-18 19:50
I just cloned the repo and ran:

```
yarn ng build --prod @ajsf/core
```

The output in `dist/@ajsf/core` has been compiled using ViewEngine as expected.

Please can you provide steps to reproduce your problem?

**Comment by hamzahamidi** [comment] 2020-10-18 20:28
I build all the libs and the demo using `yarn build:demo`

**Comment by petebacondarwin** [comment] 2020-10-19 06:53
Right, I think it is as I described above. Running `yarn build:libs` produces the correct ViewEngine output that can be published to npm. Running `yarn build:demo-only` builds the demo app that causes all your locally built libs to be converted to Ivy (by ngcc). You can see this in the output:

```
$ ng build demo --prod --base-href ./
...
Compiling @angular/core : es2015 as esm2015
Compiling @angular/cdk/keycodes : es2015 as esm2015
Compiling @angular/animations : es2015 as esm2015
...
Compiling @ajsf/core : es2015 as esm2015
...
Compiling @angular/platform-browser-dynamic : es2015 as esm2015
Compiling @angular/router : es2015 as esm2015
Compiling @ajsf/bootstrap4 : es2015 as esm2015
Compiling @ajsf/bootstrap3 : es2015 as esm2015
Compiling @ajsf/material : es2015 as esm2015
Generating ES5 bundles for differential loading...
ES5 bundle generation complete.
```

All of these "Compiling..." lines are ngcc converting libraries from ViewEngine to Ivy.

Once the have been processed by ngcc, the library cannot be published to npm. Instead you should do one of these two things:

1. In a post-build step for each library run `npm pack` on its dist directory to generate a `.tgz` file that can be published directly to npm. This `.tgz` file is not modified by ngcc when you build the demo project.
2.Re-build the libraries from scratch (without building the demo app) before you publish them to npm.

I hope that helps. Closing as this works as expected.

**Closed by petebacondarwin** 2020-10-19 06:53 UTC
Labels: comp: ngcc, needs clarification, needs reproduction

**Comment by hamzahamidi** [comment] 2020-10-19 07:26
Thanks @petebacondarwin
