### ISSUE TITLE
Angular's version compatibility  = page not found

### ISSUE THREAD

**Issue by MarcelBariakGrenzebach** [angular/angular#53196] opened 2023-11-27 11:35 UTC
### Describe the problem that you experienced

Navigate to https://angular.dev/tools/cli/setup-local#dependencies
Click Angular's version compatibility
Result
page not found

### Enter the URL of the topic with the problem

https://angular.dev/tools/cli/setup-local#dependencies

### Describe what you were looking for in the documentation

Angular's version compatibility - node js vs angular

**Comment by JoostK** [comment] 2023-11-27 12:09
Thanks for the report, this is a duplicate of https://github.com/angular/angular/issues/52562 and has since been addressed, but is pending a deployment.

**Closed by JoostK** 2023-11-27 12:09 UTC
