### ISSUE TITLE
Angular 10 - Importing Parent Component in Child Component leads to child component not rendered

### ISSUE THREAD

**Issue by parasharsh** [angular/angular#39075] opened 2020-10-01 11:59 UTC
# 🐞 bug report
Yes this is regression. This works with Angular 8.x

I have a library project (my-lib). I am importing the parent component in the nested component. The import leads to nested component not rendered at all in the production mode. The nested component renders fine if the import is not done.
The component hierarchy is as below
ParentComponent(Prints Parent Works) --> Child1Component (Prints Child 1 Works)-->Child2Component (Prints Child 2 Works) . (These are in my-lib)

Child2Component imports ParentComponent.

Parent component is used in AppComponent.

The issue can be reproduced here. https://github.com/tarangkhandelwal/dynamic-components-ng10 

Reproduction steps:
1. Build the library project 
    ng build my-lib 
2. Start the application in production mode 
   ng serve --prod
3. We should see Parent Works - Child 1 Works - Child 2 works in the UI.
4. We just see  Parent Works - Child 1 Works . If you import parent component in the Child 1 then even child 1 is not rendered.

No error is seen in the terminal or browser console

Angular CLI: 10.1.3
Node: 10.16.0
OS: darwin x64

Angular: 10.1.3
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1001.3
@angular-devkit/build-angular   0.1001.3
@angular-devkit/core            10.1.3
@angular-devkit/schematics      10.1.3
@schematics/angular             10.1.3
@schematics/update              0.1001.3
ng-packagr                      10.1.2
rxjs                            6.6.3
typescript                      4.0.3

This is a major blocker for us as it's impacting the most commonly used library component.

**Comment by mlc-mlapis** [comment] 2020-10-01 12:23
[**@parasharsh**](https://github.com/parasharsh) You should construct the logic a bit differently. Something like:

```
@Component({
	selector: 'app-root',
	...,
	providers: [{provide: RootParent, useExisting: forwardRef(() => AppComponent)}]
})
export class AppComponent implements RootParent {}
```

where

```
export abstract class RootParent {
	...
}
```

and then

```
@Component({
...})
export class AnyComponent {
	constructor(
		@Optional() private _rootParent: RootParent
	) {}
}
```

**Comment by parasharsh** [comment] 2020-10-01 13:01
Thanks @mlc-mlapis for the quick response. 
The suggested solution does work in the sample repo provided above. Let me try this out in my main project. Will keep posted here
But is this expected to be changed with Angular Upgrade and also this is working in development mode.

**Comment by JoostK** [comment] 2020-10-01 13:38
Hi @parasharsh,

this is a duplicate of #35602 and a workaround is described in https://github.com/angular/angular/issues/35602#issuecomment-591133414. No code changes are necessary, only setting a configuration flag in `package.json`.

I'll go ahead and close this, if you continue to experience problems please let me know.

**Closed by JoostK** 2020-10-01 13:38 UTC
