### ISSUE TITLE
one component in ng-template cannot query by @ViewChild whenever set static true or false in ng8

### ISSUE THREAD

**Issue by hpyou** [angular/angular#31226] opened 2019-06-24 08:49 UTC
# 🐞 bug report

### Affected Package

The issue is caused by package @angular/core 

### Is this a regression?

this behavior is only in ng8

### Description

one component in ng-template cannot query by @ViewChild whenever set static true or false in ng8

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-j3besy

## 🔥 Exception or Error

html:

```
<ng-template>
  <hello name="{{ name }}"></hello>
</ng-template>
```

<pre><code>
ts:
  @ViewChild(HelloComponent, {static: false}) hello: HelloComponent;
  ngOnInit() {
    console.log(this.hello)
  }
  ngAfterViewInit() {
    console.log(this.hello)
  }
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
 _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 8.0.3
Node: 10.16.0
OS: win32 x64
Angular: 8.0.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.3
@angular-devkit/build-angular     0.800.3
@angular-devkit/build-optimizer   0.800.3
@angular-devkit/build-webpack     0.800.3
@angular-devkit/core              8.0.3
@angular-devkit/schematics        8.0.3
@angular/cli                      8.0.3
@ngtools/webpack                  8.0.3
@schematics/angular               8.0.3
@schematics/update                0.800.3
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.30.0
</code></pre>

**Comment by mlc-mlapis** [comment] 2019-06-24 09:15
@hpyou ... you misunderstood how templates work. The concept of `@ViewChild` and others lookups the instance of a component and not as you tried the tag of that component inside the `<ng-template>`.

**Comment by hpyou** [comment] 2019-06-24 10:28
this `ng-template` is another component's content child,whitch render by `ViewContainerRef` as `TemplateRef`, now i want the instance of  the component inner `ng-template`  to  call some function...

code like this:

comp-a.html
```
<comp-b>
   <ng-template>
      <comp-c></comp-c>
   </ng-template>
</comp-b>

```
I want get the instance of comp-c in comp-a. And it works before ng8.

**Comment by mlc-mlapis** [comment] 2019-06-24 10:45
@hpyou ... can you show the working demo, how it wort?

**Comment by hpyou** [comment] 2019-06-24 10:53
this is select-component https://github.com/rdkmaster/jigsaw/blob/master/src/jigsaw/pc-components/select/select.html
this is combo-select-component https://github.com/rdkmaster/jigsaw/tree/master/src/jigsaw/pc-components/combo-select

**Comment by mlc-mlapis** [comment] 2019-06-24 14:01
@hpyou ... Do you an answer or not. I mentioned working online demo and you linked 2 links to some foreign code sources which are hard to understand from the first point of view.

Even if tried to find out something relevant and can see just `@ViewChild(JigsawFloat)` line and it's not clear what is the context in the template.

So use https://stackblitz.com to prepare a really simple demo, which abstracts the problem to a general form understandable quickly to anybody.

**Comment by kara** [comment] 2019-06-24 14:54
@hpyou The query result isn't found in the example because the ng-template hasn't been instantiated. This does not work in Angular 7.x either (confirmed by downgrading your original Stackblitz).

Since we can't reproduce this behavior, I'm going to close this issue. If you still think something is broken, please open a new issue with a repro in 7 and 8 so we have the information we need to investigate.

**Closed by kara** 2019-06-24 14:54 UTC

**Comment by hpyou** [comment] 2019-06-25 08:27
@mlc-mlapis @kara I rewrite my demo, https://stackblitz.com/edit/angular-j3besy , i find if the component in `ng-template` was not rendered, it will not be queried by @ViewChild, but in ng5 this can be queried.Anyway i find my probleam now, and i told you this behavior, thank you.

**Comment by mlc-mlapis** [comment] 2019-06-25 11:02
@hpyou ... OK. But I still don't think that it works as you described even in Angular 5, 4, 2.

**Comment by hpyou** [comment] 2019-06-26 01:33
@mlc-mlapis you can see my demo:
![image](https://user-images.githubusercontent.com/15992591/60144479-1c5ab880-97f5-11e9-86ce-f4954237d61c.png)
if you first click 'click me' button,the console will print error,but if you clicked 'click to render' button, then to click the 'click me' button, it will not print error

**Comment by mlc-mlapis** [comment] 2019-06-26 08:29
@hpyou … OK. But this is not the component defined in the template definition. It is the instance created via `this.body.createEmbeddedView(this.contentTemplateRef);` which append on the same level as `<comp-foo>` is instantiated. That's why `@ViewChild(GooComponent, {static: false}) goo: GooComponent;` can see it.

**Comment by hpyou** [comment] 2019-06-26 09:07
@mlc-mlapis yes,i got it,  thank you
