### ISSUE TITLE
IS THIS OK? WARNING in ./~/@angular/core/src/linker/system_js_ng_module_factory_loader.js

### ISSUE THREAD

**Issue by patrikx3** [angular/angular#15148] opened 2017-03-14 19:08 UTC
```bash
WARNING in ./~/@angular/core/src/linker/system_js_ng_module_factory_loader.js
87:15-102 Critical dependency: the request of a dependency is an expression
    at ImportContextDependency.getWarnings (/home/patrikx3/Projects/patrikx3/corifeus/corifeus-web-api/node_modules/webpack/lib/dependencies/ImportContextDependency.js:28:4)
    at Compilation.reportDependencyErrorsAndWarnings (/home/patrikx3/Projects/patrikx3/corifeus/corifeus-web-api/node_modules/webpack/lib/Compilation.js:663:24)
    at Compilation.finish (/home/patrikx3/Projects/patrikx3/corifeus/corifeus-web-api/node_modules/webpack/lib/Compilation.js:526:9)
    at /home/patrikx3/Projects/patrikx3/corifeus/corifeus-web-api/node_modules/webpack/lib/Compiler.js:472:16
    at /home/patrikx3/Projects/patrikx3/corifeus/corifeus-web-api/node_modules/tapable/lib/Tapable.js:225:11
    at /home/patrikx3/Projects/patrikx3/corifeus/corifeus-builder/node_modules/html-webpack-plugin/index.js:60:9
    at tryCatcher (/home/patrikx3/Projects/patrikx3/corifeus/corifeus-builder/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/patrikx3/Projects/patrikx3/corifeus/corifeus-builder/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/home/patrikx3/Projects/patrikx3/corifeus/corifeus-builder/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/home/patrikx3/Projects/patrikx3/corifeus/corifeus-builder/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/home/patrikx3/Projects/patrikx3/corifeus/corifeus-builder/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/home/patrikx3/Projects/patrikx3/corifeus/corifeus-builder/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/patrikx3/Projects/patrikx3/corifeus/corifeus-builder/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/patrikx3/Projects/patrikx3/corifeus/corifeus-builder/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)

```

**Comment by DzmitryShylovich** [comment] 2017-03-14 19:10
Duplicate of https://github.com/angular/angular/issues/11580

**Comment by IgorMinar** [comment] 2017-03-14 21:55
Thanks for reporting this issue. However this issue is a duplicate of an existing issue #11580. Please subscribe to that issue for future updates.

**Closed by IgorMinar** 2017-03-14 21:55 UTC
