### ISSUE TITLE
Some unpredictable behavior 

### ISSUE THREAD

**Issue by olegdunkan** [angular/angular#10327] opened 2016-07-27 16:12 UTC
All works fine but there are errors in console, maybe I am not properly use ngSwitchDefault directive, but there is nothing about the right location of ngSwitchDefault  in docs. For example, if ngSwitchDefault must be in the same level of nesting like all ngSwitchCase or not.  

```typescript
import { Component } from '@angular/core';

@Component({
    selector:'my-app',
    template:`
    <input type="text" [(ngModel)]="box"/>
    <div [ngSwitch]="box">
        <div *ngFor="let j of ['1','2','3']">
            <div *ngSwitchCase="j">Case {{j}}</div>
        </div>
        <h2 *ngSwitchDefault>Default</h2>
    </div>
`})
export class App {
    box:string = '1';
}
```
**I'm submitting a ...**
[x] bug report

**Reproduction of the problem**
http://plnkr.co/edit/KWEExfmHYtmKs7FpR00d?p=preview

**Comment by micronyks** [comment] 2016-07-27 16:47
It must be within the scope of `ngSwitch`.

**Comment by vicb** [comment] 2016-07-27 18:17
Probably linked to `Case {{j}}` actually, see https://github.com/angular/angular/pull/9883

**Comment by olegdunkan** [comment] 2016-07-28 08:49
First, what does it mean unroll the loop?
Make it like this
```typescript
@Component({
    selector:'my-app',
    template:`
    <input type="text" [(ngModel)]="box"/>
    <div [ngSwitch]="box">
        <div *ngSwitchCase="1">Case 1</div>
        <div *ngSwitchCase="2">Case 2</div>
        <div *ngSwitchCase="3">Case 3</div>
        <h2 *ngSwitchDefault>Default</h2>
    </div>
`})

```
If so, then we have trivial form of using ngSwitch.

Second, I need dynamic nature of ngSwitch. ['1', '2', '3'] is an example of dynamic entity but in static form for simplicity. In real apps I can use arbitrary component variable of array type.  

By the way,  if we remove  *ngSwitchDefault from my previous message snippet, all works fine without errors, no need to unroll the loop.  
And the problem is one of:
- it is not appropriate using of ngSwitch.
- it is not appropriate using of ngSwitchDefault 
- it is a bug.

**Comment by awerlang** [comment] 2016-08-02 14:22
The errors on the console represent a check to verify if any changes have happened that wouldn't be updated on the view, because of the single pass model in Angular 2.

Usually it represents a programming mistake, but I don't think that's the case. There are two ways to avoid that, one calling `enableProdMode()` to disable this verification step, but I'd prefer using ChangeDetectionStrategy.OnPush on the component. This strategy brings some restrictions but I'd say take a look at it.

http://plnkr.co/edit/P9RV5YCGUuJvKFj7BcrQ?p=preview

**Comment by pkozlowski-opensource** [comment] 2016-10-10 13:27
Still valid: https://plnkr.co/edit/Wrer61WrcTwcBWVsfPQ8?p=preview

**Comment by pkozlowski-opensource** [comment] 2016-10-10 15:42
Actually this is duplicate of #11938 . Based on https://github.com/angular/angular/issues/11938#issuecomment-252657939 we should throw when ngSwitchCase / ngSwitchDefault are not direct children of ngSwitch. 

Closing as a duplicate of #11938

**Closed by pkozlowski-opensource** 2016-10-10 15:42 UTC
Labels: comp: common, freq1: low, severity1: confusing, type: bug
