### ISSUE TITLE
Missing JitCompilerFactory constructor in compiler_factory.d.ts?

### ISSUE THREAD

**Issue by evelbulgroz** [angular/angular#21105] opened 2017-12-20 10:37 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

`const factory = new JitCompilerFactory([{useJit: true}])` throws compiler error because compiler expects zero constructor params.

## Expected behavior

Code should compile as is.

## Minimal reproduction of the problem with instructions

In a `Component`, this should compile w/o error but won't:

`public constructor() {
	const factory = new JitCompilerFactory([{useJit: true}]);
	this.compiler = factory.createCompiler([{useJit: true}]);
}`

If JitCompilerFactory constructor options are left `undefined`, then subsequent call to `factory.createCompiler()` causes `Array.prototype.map` to choke on `undefined` item when merging options internally.

Adding `constructor(options?: CompilerOptions[]);` to `JitCompilerFactory` class  in `@angular/platform-browser-dynamic/src/compiler_factory.d.ts` resolves the issue and matches how `JitCompilerFactory` constructor is coded.

Seems like a simple oversight updating the typings?

## What is the motivation / use case for changing the behavior?

Typings should match actual code behavior.

## Environment

<pre><code>
Angular version: 5.2.0-beta.0

Browser:
- [x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 6.10.0
- Platform: Windows 

Others:

</code></pre>

**Comment by mlc-mlapis** [comment] 2017-12-20 10:46
@evelbulgroz ... look at ... https://github.com/angular/angular/issues/20875#issuecomment-351448877

**Comment by evelbulgroz** [comment] 2017-12-20 13:11
Thanks for the pointer. I'm not eager to sink even more time into what I have already invested heavily into getting to work. But I'll give it a try.

I do, however, still think the `compiler_factory.d.ts` file may need a minor update, as suggested.

**Comment by chuckjaz** [comment] 2017-12-21 00:06
Thanks for reporting this issue. However this issue is a duplicate of an existing issue #20875. Please subscribe to that issue for future updates.

**Closed by chuckjaz** 2017-12-21 00:06 UTC
Labels: comp: core & compiler
