### ISSUE TITLE
https://angular.dev/guide/releases#developer-preview - Page Not Found 🙃

### ISSUE THREAD

**Issue by rafaelnl84** [angular/angular#52728] opened 2023-11-09 10:43 UTC
### Describe the problem that you experienced

Link to https://angular.dev/guide/releases#developer-preview is not working for me.

### Enter the URL of the topic with the problem

https://angular.dev/guide/releases#developer-preview

**Comment by alan-agius4** [comment] 2023-11-09 11:16
Duplicate of https://github.com/angular/angular/issues/52692

**Closed by alan-agius4** 2023-11-09 11:16 UTC
