### ISSUE TITLE
NgControl.control is undefined when injected

### ISSUE THREAD

**Issue by george43g** [angular/angular#36197] opened 2020-03-23 06:23 UTC
This is the exact same issue as #32522. The issue has been locked and it said to repost if it was still causing problems.

Find here: https://github.com/angular/angular/issues/32522

**Comment by george43g** [comment] 2020-03-23 06:32
Nevermind, I fixed it. I might leave this here in case anyone else comes across this same bug - mine was slightly different.

Used for providing a directive to disable a reactive form:

*Reproduction:*
```ts
import { Directive, Input } from '@angular/core';
import { NgControl } from '@angular/forms';

@Directive({
  selector: '[disableForm]',
})
export class DisableFormDirective {
  @Input() set disableForm(condition: boolean) {
    const action = condition ? 'disable' : 'enable';
    this.ngControl.control[action]();
  }

  constructor(private ngControl: NgControl) {}
}
```

This used to work, but will fail in Ivy. Has something to do with the order of hooks/injectors (pardon my ignorance).

*Solution:*
This has already been fixed. In order to access an injected ngControl in Ivy, it must be accessed after some things happen. Which is where the OnInit `interface` comes in handy. So refactoring the code like so fixes the issue:

```ts
export class DisableFormDirective implements OnInit {
  @Input() disableForm: boolean;

  constructor(private ngControl: NgControl) {}

  ngOnInit() {
    // console.log(`[disable-form-directive] condition: ${condition}`);
    // console.log(`[disable-form-directive]`, this.ngControl, this.ngControl.control);
    const action = this.disableForm ? 'disable' : 'enable';
    this.ngControl.control[action]();
  }
}
```

**Comment by indraraj26** [comment] 2020-03-24 16:32
It is working fine for me.
```
import { Directive, Input, SimpleChanges  } from '@angular/core';
import { NgControl } from '@angular/forms';

@Directive({
  selector: '[appToggle]'
})
export class ToggleDirective {
  @Input() set appToggle(action) {
    this.ngControl.control[action]();
  }

  constructor(private ngControl: NgControl) {
  }
} 
```
Demo :  https://stackblitz.com/edit/angular-wp6jvh?file=src%2Fapp%2Fapp.component.html

**Comment by SteffenSchwaiger** [comment] 2020-04-06 07:26
Duplicate of #35330

**Comment by AndrewKushnir** [comment] 2020-05-27 05:40
Hi @george43g, thanks for reporting the issue. As @SteffenSchwaiger mentioned, it looks like.a duplicate of #35330. I'm closing this ticket (as a duplicate), please subscribe to further updates/discussion in #35330. Thank you.

**Closed by AndrewKushnir** 2020-05-27 05:40 UTC
Labels: comp: forms
