### ISSUE TITLE
@Inject not working for extended class when target > es5

### ISSUE THREAD

**Issue by no-more** [angular/angular#25924] opened 2018-09-12 06:07 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

I didn't find any issue that is exactly the same as this one.

## Current behavior

When I set tsconfig target to es2015 or es2017 I can't retrieve injected Injector in my service class if it depends on another parent class which code is in another file (it works if the parent code is in the same file)

here is the browser console output with target es2017: 
```
main.ts:9 pre-test
09:52:07.143 test.1.ts:46 step 1
09:52:07.145 test.1.ts:53 step 2
09:52:07.145 test.1.ts:10 LocalBaseClass _injector ReflectiveInjector_ {_constructionCounter: 1, _providers: Array(4), parent: null, keyIds: Array(4), objs: Array(4)}
09:52:07.147 test.1.ts:11 LocalBaseClass this._injector ReflectiveInjector_ {_constructionCounter: 1, _providers: Array(4), parent: null, keyIds: Array(4), objs: Array(4)}
09:52:07.148 test.1.ts:55 step 3
09:52:07.148 test2.ts:11 ExternalBaseClass _injector undefined
09:52:07.148 test2.ts:12 ExternalBaseClass this._injector undefined
09:52:07.149 core.js:2086 Uncaught Error: Cannot read property 'get' of undefined: Error during instantiation of Custom2Provider!. caused by: Cannot read property 'get' of undefined
```

## Expected behavior

I would expect no difference between defining parent class in a local file and importing parent class from another file.

here is the browser console output with target es5: 
```
main.ts:9 pre-test
10:06:19.748 test.1.ts:46 step 1
10:06:19.750 test.1.ts:53 step 2
10:06:19.750 test.1.ts:10 LocalBaseClass _injector ReflectiveInjector_ {_constructionCounter: 1, _providers: Array(4), parent: null, keyIds: Array(4), objs: Array(4)}
10:06:19.752 test.1.ts:11 LocalBaseClass this._injector ReflectiveInjector_ {_constructionCounter: 1, _providers: Array(4), parent: null, keyIds: Array(4), objs: Array(4)}
10:06:19.753 test.1.ts:55 step 3
10:06:19.754 test2.ts:11 ExternalBaseClass _injector ReflectiveInjector_ {_constructionCounter: 3, _providers: Array(4), parent: null, keyIds: Array(4), objs: Array(4)}
10:06:19.754 test2.ts:12 ExternalBaseClass this._injector ReflectiveInjector_ {_constructionCounter: 3, _providers: Array(4), parent: null, keyIds: Array(4), objs: Array(4)}
10:06:19.755 test.1.ts:57 step 4
10:06:19.755 main.ts:11 post-test
10:06:19.845 core.js:3123 Angular is running in the development mode. Call enableProdMode() to enable the production mode.
```
## Minimal reproduction of the problem with instructions

I have included a small demo project.
just change target in `tsconfig` and run `ng serve` -> then open in the browser.

[test3.zip](https://github.com/angular/angular/files/2373741/test3.zip)

## Environment

<pre><code>
Angular version: ^6.1.0

Browser:
- [X] Chrome (desktop) version 68.0.3440.106
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.9  
- Platform:  Windows 10

Others:

</code></pre>

**Comment by mhevery** [comment] 2020-02-19 01:21
Unable to reproduce the issue. Closing as Ivy has been released.

**Closed by mhevery** 2020-02-19 01:21 UTC
Labels: comp: core, fixed by Ivy, freq1: low, severity1: confusing, type: bug/fix
