### ISSUE TITLE
Sanitize removes inline style

### ISSUE THREAD

**Issue by sosharma1403** [angular/angular#26567] opened 2018-10-19 07:31 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

sanitize removes inline style

## Expected behavior

sanitize should not remove style

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-t44mwq

## What is the motivation / use case for changing the behavior?

I need to show text from Rich Text Editor in a div

## Environment

<pre><code>
Angular version: latest

**Comment by trotyl** [comment] 2018-10-19 12:52
Duplicate of https://github.com/angular/angular/issues/17284, https://github.com/angular/angular/issues/19645

**Closed** 2018-10-19 17:06 UTC
