### ISSUE TITLE
httpclient factory with httpinterceptors rather than global interceptors

### ISSUE THREAD

**Issue by ashgibson** [angular/angular#22340] opened 2018-02-21 06:59 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

Would it be possible to create some sort of HttpClientFactory which can be used to generate contained HttpClient classes with their own HttpInterceptor rather than creating global interceptors. This seems like it would be a better solution for projects which have multiple data sources and would allow better packaging of code. The ngx-restangular library does it this way as a reference - https://github.com/2muchcoffeecom/ngx-restangular. The reason I don't use this library is because it doesn't make use of httpClient and this type of thing seems like it might be a core feature rather than a 3rd party library.

**Comment by trotyl** [comment] 2018-02-21 09:10
Duplicate of #18155, #20203

**Comment by vicb** [comment] 2018-02-21 19:08
Closing as duplicate (thanks @trotyl)

**Closed by vicb** 2018-02-21 19:08 UTC
