### ISSUE TITLE
Form required validator uses length attribute on object also

### ISSUE THREAD

**Issue by fabianmarquart** [angular/angular#30718] opened 2019-05-29 09:03 UTC
# 🐞 bug report

### Affected Package
@angular/forms

### Description

We use require form validators to check whether an object is assigned inside a form.
Because our object has a field called "length", the required validators fail.

```typescript
function isEmptyInputValue(value: any): boolean {
  // we don't check for string here so it also works with arrays
  return value == null || value.length === 0;
}
```

The function should check if value is string or array before using the "length" attribute,
for example:

```typescript
function isEmptyInputValue(value: any): boolean {
  !(Array.isArray(value) && value.length === 0 || !value ) 
}
```

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/primeng-template-qgayjf

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 7.3.3
Node: 8.16.0
OS: win32 x64
Angular: 7.2.4
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.10.6
@angular-devkit/build-angular     0.10.6
@angular-devkit/build-optimizer   0.10.6
@angular-devkit/build-webpack     0.10.6
@angular-devkit/core              7.0.6
@angular-devkit/schematics        7.3.3
@angular/cdk                      7.3.6
@angular/cli                      7.3.3
@ngtools/webpack                  7.0.6
@schematics/angular               7.3.3
@schematics/update                0.13.3
rxjs                              6.4.0
typescript                        3.2.4
webpack                           4.19.1
</code></pre>

**Comment by s-gbz** [comment] 2019-06-03 11:25
I'll take a look at it!

**Comment by AndrewKushnir** [comment] 2020-05-30 22:39
HI @fabianmarquart, thanks for creating this ticket. It looks like it's a duplicate of #36858. I will close this one, please subscribe to #36858 for further discussion/updates. Thank you.

**Closed by AndrewKushnir** 2020-05-30 22:39 UTC
Labels: comp: forms, forms: validators, freq1: low, severity3: broken, triage #1, type: confusing
