### ISSUE TITLE
Component loaded via lazy module is not rendering inside named outlet, but outlet is activated correctly

### ISSUE THREAD

**Issue by johngrimsey** [angular/angular#47012] opened 2022-08-01 21:43 UTC
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

Yes

### Description

I swear this used to work in Angular 13.2.2

See README.md in repo 

No Router errors when tracing enabled

### Please provide a link to a minimal reproduction of the bug

https://github.com/johngrimsey/router-debug

### Anything else?

Haven't been able to check in Angular 13.2.2 - but my expectation is that the component should be rendered

**Comment by atscott** [comment] 2022-08-01 22:35
Similar to https://github.com/angular/angular/issues/46500, your application has broken the parent/child relationship of the router outlets. The `RouterOutlet` in the dialog needs to be a logical child in the element injector tree of the parent.

Closing as an issue outside of Angular.

**Closed by atscott** 2022-08-01 22:35 UTC

**Comment by johngrimsey** [comment] 2022-08-02 07:18
@atscott Thank you, appreciate you taking the time to look 🙏

**Comment by johngrimsey** [comment] 2022-08-03 21:25
Setting the `viewContainerRef` property of `MatDialogConfig` hasn't made any difference for me.

Refreshing the page after the modal-related URL has been set, and the modal not rendered - refreshing the browser makes it work. 

Like the author of #46500 wrote, this did actually used to work flawlessly, but has stopped working. I've trawled through the changelog for any changes to the `Router` that read like they may be the cause but no luck.

Is there a change that would now prevent this usage from working? 

Lastly, is the break due to nesting the leaf `<router-outlet>` inside an `ng-template` element, is that the breakage?

I thought I understood the `Router` very well but this has me stumped, it doesn't work during normal navigation, but refreshing the browser makes it work. I haven't the skills to debug what the difference is.

**Comment by atscott** [comment] 2022-08-03 23:37
@johngrimsey Just to clarify - your example is using `ngneat` for the dialog but you mention using `MatDialogConfig`. It looks like the change that probably caused this was https://github.com/angular/components/commit/1199b39ac05a2a7abea64fad50e279bb07227d4c / https://github.com/angular/components/commit/f91b98fff3beff70b2537f8b3da635518ef403ef. 

Previously what was happening was that the dialog was being created without an injector so when the `RouterOutlet` in the dialog template got created and tried to inject `ChildrenOutletContexts`, it got the answer from the `OutletInjector` created by the parent outlet. Now it's getting the answer from the embedded view injector instead. 

// cc @crisbeto. Could you help debug this if you have time today (for you)? The more minimal reproduction is in #46500. I was able to track things down by running a `13.2.2` version alongside the `14.0.0` version.

**Comment by johngrimsey** [comment] 2022-08-04 13:12
Hey @atscott, thanks ma. Apologies yes I rather unscientifically supplied a reproduction example using `ngneat` but am infact using `@angular/material`. I was pretty satisfied there is consistency between my repro example and what I'm seeing here in my working context.

**Comment by johngrimsey** [comment] 2022-08-09 11:08
@atscott Do you think anything will come of this or do I need to completely re-think my old approach?

**Comment by atscott** [comment] 2022-08-09 16:14
@johngrimsey @crisbeto has a fix for this in the `MatDialog`: https://github.com/angular/components/pull/25406

This is aimed at fixing the issue we could reproduce in https://github.com/angular/angular/issues/46500. Since your reproduction didn't use `MatDialog`, I'm not 100% confident it's the same.

**Comment by johngrimsey** [comment] 2022-08-09 16:30
Thanks man that's great, appreciate it.
