### ISSUE TITLE
InputSignals are not evaluated when using SSR old @Input's are

### ISSUE THREAD

**Issue by sp90** [angular/angular#54384] opened 2024-02-11 19:47 UTC
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

The old `@Input` works

<img width="656" alt="Screenshot 2024-02-11 at 20 30 42" src="https://github.com/angular/angular/assets/3041602/ea43d75c-e158-4cc0-b5b0-12b9b60ca2f8">

The new `input.required()` does not

<img width="644" alt="Screenshot 2024-02-11 at 20 30 53" src="https://github.com/angular/angular/assets/3041602/fcf50a92-d409-4543-a31b-f6d9eab55107">

A bit more context:

So it's an SSR app running the new dev preview Zoneless configuration, the input signal works when it's in the client, but it does not work when the server is trying to prerender it.

Worth noting is the server does get the data it tries to fetch, but its not passed to the component before render, unless we use the old `@Input`

### Please provide a link to a minimal reproduction of the bug

https://github.com/sp90/treaty

### Please provide the exception or error you saw

```true
So we have 1 error present NG05000, but this is shown no matter which input type we put on
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.2.0-rc.0
Node: 20.11.0
Package Manager: bun 1.0.26
OS: darwin arm64

Angular: 17.2.0-rc.1
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1702.0-rc.0
@angular-devkit/build-angular   17.2.0-rc.0
@angular-devkit/core            17.2.0-rc.0
@angular-devkit/schematics      17.2.0-rc.0
@angular/cli                    17.2.0-rc.0
@angular/ssr                    17.2.0-rc.0
@schematics/angular             17.2.0-rc.0
rxjs                            7.8.1
typescript                      5.3.3
```

### Anything else?

It requires bun to be installed to run it:

https://bun.sh/docs/installation

**Comment by atscott** [comment] 2024-02-11 19:52
> running the new dev preview Zoneless configuration

There is _no_ SSR support yet for this. In fact, it is not developer preview, it is a private export, not meant to even be used anywhere except for internal testing. 

Closing as unsupported at the moment.

**Closed by atscott** 2024-02-11 19:52 UTC

**Comment by Jordan-Hall** [comment] 2024-02-12 14:28
@atscott  Looking at the code I enabled zonejs and get the same issue. The old style will use SSR while the new signal will actually use transfer state and client side to add it in. Can this be reopened

**Comment by atscott** [comment] 2024-02-16 03:38
@Jordan-Hall would you mind opening a new issue with a reproduction that’s more minimal (ng new, without bun, without Elysia, etc.)? I know the example app is pretty small already but there’s plenty in there that’s not needed. It would be much easier to evaluate a more focused issue report and reproduction.

**Comment by Jordan-Hall** [comment] 2024-02-16 03:40
@atscott as its ssr would you prefer expressjs?   The issue is input signals are not providing SSR like decorator inputs.
