### ISSUE TITLE
Lack of src link to angular2-polyfill errors silently

### ISSUE THREAD

**Issue by MaxBlaushild** [angular/angular#6156] opened 2015-12-28 18:49 UTC
Hello,

I was working on a personal project, and I could not figure out why my expressions were not getting rebound in my views after new data. I was not getting any compile or console errors. Eventually I found out that I was not linking to angular2-polyfills in my index.html.

I know that the quickstart tutorial tells you to include the link, but I think it would be helpful to raise some sort of error if angular2-polyfills is not imported.

**Comment by pkozlowski-opensource** [comment] 2015-12-28 18:53
You are right. We are already tracking this issue in https://github.com/angular/angular/issues/2683 (this is actually zone.js, contained within angular2-polyfills that was making your app "not working").

Closing as a duplicate of #2683

**Closed by pkozlowski-opensource** 2015-12-28 18:53 UTC
