### ISSUE TITLE
Service worker does not work in Firefox or Edge

### ISSUE THREAD

**Issue by prp1** [angular/angular#34627] opened 2020-01-03 10:22 UTC
# 🐞 bug report

### Affected Package
@angular/cli
@angular/pwa

### Description
Angular service worker works only in Chrome. In Firefox and Edge it does not work (I did not test on other browsers).

After creating a minimal angular app with angular cli and adding a service worker, app can be installed and works offline only in Chrome.

## 🔬 Minimal Reproduction

1. ng new pwa (choose to use router and stylus as css files)
2. ng add @angular/pwa
3. ng build --prod
4. http-server -p 8080 -c-1 dist/pwa
5. Open https://localhost:8080 in Firefox or Edge. Refresh several times and wait to make sure all assets are cached by service worker
6. Stop http-server and refresh the page

**Expected behaviour:**
App is still loaded

**Actual behaviour:**
App fails to load

Note: in Chrome everything works as expected.

I also published the app on github pages. The same problems can be reproduced there (turn of internet connection to test the app running offline in firefox):
https://prp1.github.io/test-angular-service-worker-in-firefox/

## 🌍  Your Environment

**Angular Version:**
@angular/cli version 8.3.21

**Comment by gkalpak** [comment] 2020-01-03 13:24
Sorry, I could not reproduce the problem. https://prp1.github.io/test-angular-service-worker-in-firefox works on both Firefox and Edge (in addition to Chrome).

It could be something in your browser settings or local environment. It is really hard to tell without a reproduction. I am going to close this issue, since it is not actionable for us in its current state, but feel free to continue the discussion below (e.g. add more info, such as whether you get any error messages in the console of either browser).

**Closed by gkalpak** 2020-01-03 13:24 UTC

**Comment by prp1** [comment] 2020-01-06 08:24
I find out that it in Firefox and Edge it does not work when I open app in private window. In Chrome, however, it works even in private window. Is this expected behaviour?

**Comment by gkalpak** [comment] 2020-01-07 13:51
It depends on how the browser implements private browsing and what operations/features it disables.
This is not specific to Angular, though. It should affect all ServiceWorkers the same.
