### ISSUE TITLE
strictTemplates: does not allow coercion of string to number

### ISSUE THREAD

**Issue by kevinphelps** [angular/angular#36440] opened 2020-04-05 20:28 UTC
# 🐞 bug report

### Affected Package
Unsure, probably `@angular/compiler`.

### Is this a regression?
Not that I am aware.

### Description
Say you have an expression in your template that you know represents a number but it's typed as a `string` (e.g. a `select` value). If you want to pass that value to an event handler method or bind it as input, 1) the method parameter/input must be typed as a `string` or 2) you must use `+$any(theExpression)` in the template to coerce the value to a number so the method/input property gets a number value.

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-issue-36440

## 🔥 Exception or Error
Having to use `$any` here is a bit of pain point to me. I think we should be able to coerce the value directly (i.e. `+theExpression`), but doing that results in this error:

```
Error in src/app/app.component.html (6:46)
The left-hand side of an arithmetic operation must be of type 'any', 'number', 'bigint' or an enum type.
```

That's odd because there is no left-hand side here.

**Comment by JoostK** [comment] 2020-04-05 20:48
Closing as duplicate of #36178.

**Closed by JoostK** 2020-04-05 20:48 UTC

**Comment by kevinphelps** [comment] 2020-04-05 20:49
Sorry about that! I searched the issue for "coerce" and other thing and didn't find that. I didn't have the right search terms. Sorry again!

**Comment by JoostK** [comment] 2020-04-05 21:01
Oh no worries! It's actually appreciated you taking the time to report these kinds of issues, otherwise they would get unnoticed.
