### ISSUE TITLE
Http/Jsonp: better ergonomics for setting URLSearchParams

### ISSUE THREAD

**Issue by wardbell** [angular/angular#6835] opened 2016-02-02 05:03 UTC
This is what it takes to set three query parameters as of beta.2:

```
    var params = new URLSearchParams();
    params.set('search', term);
    params.set('action', 'opensearch');
    params.set('format', 'json');
```

That's tedious even if it does slavishly follow the [standard](https://url.spec.whatwg.org/#urlsearchparams) for this class. 

It should be possible to write the following far more natural statement:

```
    var params = new URLSearchParams({
      search: term,
      action: 'opensearch',
      format: 'json'
    });
```

_Every_ method that accepts a `URLSearchParams` object should also accept this representation.

If a parameter value is multi-variate, the syntax should allow for array values instead of just strings.

Every other reasonable HTTP api accepts this syntax. See, for example, the "data" property in [jQuery ajax](http://api.jquery.com/jQuery.ajax/). The Angular 1 `$http` does it too as I recall.

**Comment by gdi2290** [comment] 2016-02-02 05:52
:+1: `URLSearchParams` should also implement toJSON

**Comment by cburgdorf** [comment] 2016-02-03 07:37
Duplicate of  https://github.com/angular/angular/issues/5516

**Comment by scttcper** [comment] 2017-08-21 23:12
Chrome is supporting this in v61 https://github.com/whatwg/url/pull/175

**Comment by alxhub** [comment] 2017-11-28 23:37
`URLSearchParams` is deprecated in Angular, please use `HttpClient` and `HttpParams` instead.

**Closed by alxhub** 2017-11-28 23:37 UTC
Labels: comp: http
