### ISSUE TITLE
bug(routing): forget to put components in declaration

### ISSUE THREAD

**Issue by indraraj26** [angular/angular#36360] opened 2020-04-01 04:24 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/router

### Is this a regression?

 Yes, the previous version in which this bug was not present was: no idea

### Description
Suppose you forget to declare ChildComponent in declaration of parent.module.ts and will try to use *ngFor you will get this error : Can't bind to 'ngForOf' since it isn't a known property of 'p'. Basically i forget to declare ChildComponent in parent.module.ts. Still i am able to visit /parent/children and see content.

Expected: It should throw an error that ChildComponent is not a part of any module declaration.

Issue: Sometime it is really hard to debug for newbie what went wrong.

code : 
```
<p *ngFor="let item of [1,2,3]">
  children works!
</p>
<!--you will able to see children works even 
it is not a part of any module -->
<p>
  children works!
</p>
```
## 🔬 Minimal Reproduction

 
https://ng-run.com/edit/wiaLgud669oJ3gX4hMFP?open=app%2Fparent%2Fparent.component.html

## 🔥 Exception or Error
<pre><code>

Can't bind to 'ngForOf' since it isn't a known property of 'p'.
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

  9.0.2
</code></pre>

**Anything else relevant?**

**Comment by atscott** [comment] 2022-03-02 00:43
Duplicate of https://github.com/angular/angular/issues/17446. I've discussed this several times with @alxhub and there's really not a good way to do this in the NgModule world. This will be resolved by the standalone components project though (since you don't declare standalone components in a module at all).

**Closed by atscott** 2022-03-02 00:43 UTC
Labels: type: bug/fix, hotlist: error messages, freq2: medium, comp: router, comp: core, state: confirmed, core: directive matching, core: NgModule, type: confusing, triage #1, P4
