### ISSUE TITLE
cant seem to run the angular.dev example https://angular.dev/api/core/ContentChild?tab=usage-notes

### ISSUE THREAD

**Issue by sanket-bhalerao** [angular/angular#54231] opened 2024-02-03 13:36 UTC
### Describe the problem that you experienced

How to run this example that is part of the angular.dev documentation https://angular.dev/api/core/ContentChild?tab=usage-notes
```
/**
 * @license
 * Copyright Google LLC All Rights Reserved.
 *
 * Use of this source code is governed by an MIT-style license that can be
 * found in the LICENSE file at https://angular.io/license
 */
import {Component, ContentChild, Directive, Input} from '@angular/core';
@Directive({selector: 'pane'})
export class Pane {
  @Input() id!: string;
}
@Component({
  selector: 'tab',
  template: `
    <div>pane: {{ pane?.id }}</div>
  `,
})
export class Tab {
  @ContentChild(Pane) pane!: Pane;
}
@Component({
  selector: 'example-app',
  template: `
    <tab>
      <pane id="1" *ngIf="shouldShow"></pane>
      <pane id="2" *ngIf="!shouldShow"></pane>
    </tab>
    <button (click)="toggle()">Toggle</button>
  `,
})
export class ContentChildComp {
  shouldShow = true;
  toggle() {
    this.shouldShow = !this.shouldShow;
  }
}
```

### Enter the URL of the topic with the problem

https://angular.dev/api/core/ContentChild?tab=usage-notes

### Describe what you were looking for in the documentation

i am under the impression that the example given here needs to be runnable as developers who are new to the angular framework could also be visiting these pages and try to run the code.
i am able to run the code as 
```
import { CommonModule } from '@angular/common';
import { Component, ContentChild, Directive, Input } from '@angular/core';

@Directive({ selector: '[billiPane]', standalone: true })
export class PaneDirective {
  @Input() id!: string;
}

@Component({
  selector: 'billi-tab',
  template: `
    <div>
      pane: {{ pane.id }}
      <ng-content />
    </div>
  `,
  standalone: true,
})
export class TabComponent {
  @ContentChild(PaneDirective) pane!: PaneDirective;
}

@Component({
  selector: 'billi-example-app',
  standalone: true,
  template: `
    <billi-tab>
      <div
        billiPane
        id="1"
        *ngIf="shouldShow"
        height="500"
        style="background: red;">
        some content
      </div>

      <div billiPane id="2" *ngIf="!shouldShow"></div>
    </billi-tab>
    <button (click)="toggle()">Toggle</button>
  `,
  imports: [PaneDirective, TabComponent, CommonModule],
})
export class ContentChildComponent {
  shouldShow = true;
  toggle() {
    this.shouldShow = !this.shouldShow;
  }
}

@Component({
  selector: 'billi-for-demo',
  standalone: true,
  imports: [CommonModule, ContentChildComponent],
  template: `<billi-example-app></billi-example-app>`,
  styleUrl: './ForDemo.component.scss',
})
export class ForDemoComponent {}
```

**Comment by JeanMeche** [comment] 2024-11-24 22:52
Closing as dupe of #56321

**Closed by JeanMeche** 2024-11-24 22:52 UTC
Labels: P3, area: adev
