### ISSUE TITLE
Form status is not correctly propagated in the nested CVA forms

### ISSUE THREAD

**Issue by enestoro** [angular/angular#38991] opened 2020-09-25 10:45 UTC
# 🐞 bug report

### Affected Package
```
"@angular/animations": "^10.0.9",
"@angular/common": "^10.0.9",
"@angular/compiler": "^10.0.9",
"@angular/core": "^10.0.9",
"@angular/forms": "^10.0.9",
"@angular/platform-browser": "^10.0.9",
"@angular/platform-browser-dynamic": "^10.0.9",
"@angular/router": "^10.0.9",
```

### Is this a regression?
No, I don't think so, it's also reproducible in Angular 9.

### Description

I'm not sure if it's a bug but I find this behavior strange and I cannot find any information in the documentation about that. 
This is about the nested forms, CVA and validation. 

I have a nested form structure:
- form container (not CVA, it contains CVA form controls)
- parent form (CVA) appended to the form container ☝️ 
- child form (CVA) appended to the parent form ☝️ 

Only the child form has a _required_ validator attached. I have also a button attached to the form container which should be disabled if the form (in the form container) is invalid. The problem is that the form container is valid, although the parent form and its child are invalid. 

Once I attach any validator to the parent form, the invalid event will be propagated to the form container. I'm not sure if it's a bug but I would expect that if the both forms are invalid (parent and child), the status should be also propagated to the form container and it's not. It's only propagated once the parent form has a validator attached. 

I prepared a stackblitz so that you can reproduce the issue. I would be very grateful if you could comment on that.

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-ivy-hhfydn

**Comment by AndrewKushnir** [comment] 2020-10-24 00:28
Hi @enestoro,

I've looked at the repro that you provided and added extra debug info ([see here](https://stackblitz.com/edit/angular-ivy-76xdhc?file=src%2Fapp%2Fparent-form.component.ts)). It turned out that the `validate` function of the `ParentFormComponent` returns `null` (which means that it is valid) when control is being initialized, so this status is propagated to the container form. The use-case is quite complex and I can't provide a detailed solution, but it looks like the problem is somewhere around the custom logic in validators that are not in sync with each other.

Since this looks like an issue on the app side and there are no action items for framework, I will close this ticket.

Thank you.

**Closed by AndrewKushnir** 2020-10-24 00:28 UTC
Labels: comp: forms, forms: ControlValueAccessor

**Comment by enestoro** [comment] 2020-10-26 07:16
@AndrewKushnir thank you for the analysis
