### ISSUE TITLE
canMatch called twice

### ISSUE THREAD

**Issue by RahulKate** [angular/angular#48761] opened 2023-01-18 05:52 UTC
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

No

### Description

@atscott 

canMatch called twice, check below screen shot with logs, called twice

OR Please let me know how to avoid one of call from canMatch if it is called twice or How to detect  "Route Recognizing" and "Applying Redirects" steps?

![image](https://user-images.githubusercontent.com/13742253/213094954-20dac6da-1f41-4dfa-b373-39c75d4299e4.png)

**Comment by JeanMeche** [comment] 2023-01-18 09:03
Hi, after a quick repro, I'd say it's linked to #26081 !

**Comment by atscott** [comment] 2023-01-18 09:14
Yes, this is a duplicate of https://github.com/angular/angular/issues/26081

**Closed by atscott** 2023-01-18 09:14 UTC
