### ISSUE TITLE
Bind to inputs of hostDirectives

### ISSUE THREAD

**Issue by alirezamirian** [angular/angular#51003] opened 2023-07-11 13:35 UTC
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

Using Angular 15+ [hostDirectives](https://angular.io/guide/directive-composition-api#adding-directives-to-a-component), one can make directive inputs available as component inputs, which is useful. But in some cases, directive's input should not be an input on the component, but passing the value of the input is necessary. Value being either static or an expression.

```ts
@Directive({
  standalone: true,
})
class MyDirective {
  @Input()
  directiveInput?: string;
}


@Component({
  hostDirectives: [ MyDirective ],
  host: {
    '[directiveInput]': 'inputValue' // This won't work, even if `directiveInput` is defined in the inputs of host directive definition object.
  }
})
class MyComponent {

  inputValue: string;
}
```

There shouldn't be a difference between using a directive in the view of the component, or on host, in terms of being able to declaratively bind to the directive inputs.

Related link: https://stackoverflow.com/questions/76662327/directive-input-binding-when-using-angular-hostdirectives

### Proposed solution

Allow for binding to input values of host directives. 

A couple of not-thought-through suggestions off the top of mind:

## Proposal 1:

Make directive inputs available in host binding (either by [host](https://angular.io/api/core/Directive#host), or [HostBinding](https://angular.io/api/core/HostBinding)). Similar to the example above.

## Proposal 2:

In `hostDirectives`'s `input`, allow for not only mapping directive inputs to component, but to bind as well:

A couple of backward compatible APIs could be:
```
@Component({
  hostDirectives: { directive: MyDirective, inputs: ['directiveInput: "inputValue"'] } // Look at the quotes. If present, it defines an expression that should be bound to `directiveInput`
})
```

```
@Component({
  hostDirectives: { directive: MyDirective, inputs: [{input: 'directiveInput', value: 'inputValue'}] } // Look at the quotes. If present, it defines an expression that should be bound to `directiveInput`
})
```

### Alternatives considered

Inject the directive, and assign the input manually in ngOnInit, and whenever it needs to be updated. But:
- It would be nicer to avoid imperative assignment of the input, and have the same declarative way of binding to inputs, regardless of directive being used in template or in hostDirectives
- If the value is not static but an expression, one needs to update the directive input every time the result of the expression is changed.

**Comment by JeanMeche** [comment] 2023-07-11 13:42
Hi, this issue is being discussed at #50510.

**Comment by pkozlowski-opensource** [comment] 2023-07-11 14:34
Duplicate of #50510

**Closed by pkozlowski-opensource** 2023-07-11 14:34 UTC
