### ISSUE TITLE
github bot should not notify me about merge conflicts repeatedly

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#21632] opened 2018-01-18 16:23 UTC
If I have a pending PR, and this PR gets into a merge-conflict state, then bot comments on the PR to notify me.

That's great.

If I don't get to resolve the merge conflict, and more merge conflicts are introduced then I should not get any more notifications. Today I do and that creates a lot of noise.

The desired behavior is that I get **one notification** about a merge conflict every time a PR was previously in a non-conflicting state, but a recently merged PR caused it to now have a conflict.

To do this we might need to remember the current state of the PR. Which might be simpler to do if we store the state as a label, which would also help to highlight PR state in the https://github.com/angular/angular/pulls view.

**Comment by ocombe** [comment] 2018-01-18 16:33
It's a duplicate of #21512, and it should have been fixed 2 days ago.
Have you noticed that behavior in the last 2 days?

**Comment by vicb** [comment] 2018-01-30 23:28
Closing as I think this has been fixed.

**Closed by vicb** 2018-01-30 23:28 UTC
Labels: comp: build & ci, flag: can be closed?, freq3: high, severity2: inconvenient, type: bug
