### ISSUE TITLE
strictTemplates and *ngIf produces strange result

### ISSUE THREAD

**Issue by dilame** [angular/angular#35486] opened 2020-02-17 05:45 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/core

### Description

If i write `*ngIf="user as u"` then user data type (which is nullable) not narrowed. But if i write just `*ngIf="user"` then everything works as expected

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-issue-repro2-awscdm

Not sure if stackblitz respects `tsconfig.json`

## 🔥 Exception or Error
<pre><code>

ERROR in src/app/app.component.ts:14:11 - error TS2531: Object is possibly 'null'.

14         {{u.firstName}}
             ~~~~~~~~~~~
</code></pre>


## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 9.0.2
Node: 13.6.0
OS: darwin x64

Angular: 9.0.1
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.2
@angular-devkit/build-angular     0.900.2
@angular-devkit/build-optimizer   0.900.2
@angular-devkit/build-webpack     0.900.2
@angular-devkit/core              9.0.2
@angular-devkit/schematics        9.0.2
@angular/cli                      9.0.2
@ngtools/webpack                  9.0.2
@schematics/angular               9.0.2
@schematics/update                0.900.2
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
    


</code></pre>

**Anything else relevant?**
<!-- ✍️Is this a browser specific issue? If so, please specify the browser and version. -->

<!-- ✍️Do any of these matter: operating system, IDE, package manager, HTTP server, ...? If so, please mention it below. -->

**Comment by JoostK** [comment] 2020-02-17 06:08
Closing as duplicate of #34572, pending PR in #35125

**Closed by JoostK** 2020-02-17 06:08 UTC
