### ISSUE TITLE
Cannot use pathMatch without redirect or component, etc anymore regression 

### ISSUE THREAD

**Issue by egonknapen** [angular/angular#46325] opened 2022-06-10 09:47 UTC
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

Yes

### Description

After updating to Angular 14, I cannot run my project anymore because of missing element in my routing.

```
{ path: 'message', component: MessagePageComponent, children: [
   { path: '', pathMatch: 'full', canActivate: [AutoSelectGuard] },
   { path: 'settings', component: MessageSettingsComponent, canActivate: [GroupSelectGuard], children: [
      . . .
    ])
   { path: 'summary', component: MessageSummaryComponent, canActivate: [GroupSelectGuard],
```

Where on the second line the [AutoSelectGuard], redirects to any sub page, depending on the last time you visited that sub page. 

### Please provide the exception or error you saw

```true
core.mjs:6412 ERROR Error: Invalid configuration of route 'infotainment//message/'. One of the following must be provided: component, loadComponent, redirectTo, children or loadChildren
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 14.0.1
Node: 16.13.0
Package Manager: npm 8.3.0
OS: win32 x64
```

### Anything else?

After adding "redirectTo:'settings'" to that second line I got following exception:

core.mjs:6412 ERROR Error: Invalid configuration of route 'infotainment//message/': redirectTo and canActivate cannot be used together. Redirects happen before activation so canActivate will never be executed.

So Angular knows I'm using an canActivate guard and it's mutual exclusive too.

**Comment by egonknapen** [comment] 2022-06-10 11:35
It can be fixed by using adding children:[] like @[dzonatan] pointed out:
https://github.com/angular/angular/issues/13373

We now need 2 so called hacks [canActivate] + 'children:[]', to get dynamic routing working. I would suggest angular comes up with their own solution or add the preferred way to their documentation.

**Comment by atscott** [comment] 2022-06-10 15:03
Duplicate of https://github.com/angular/angular/issues/13373

**Closed by atscott** 2022-06-10 15:03 UTC
Labels: comp: router

**Comment by egonknapen** [comment] 2022-06-10 18:51
So no documentation update?

**Comment by atscott** [comment] 2022-06-10 19:28
The configuration was never intended to be allowed. Before v14, Lazy loaded configs we’re not validated but now they are. This change is listed in the v14 breaking changes.

The use case you’re describing is a feature gap in the API, which is a duplicate of https://github.com/angular/angular/issues/13373
