### ISSUE TITLE
Angular.dev guide for http client testing does not include httpClient in the provider, resulting in exception when running test

### ISSUE THREAD

**Issue by jbcbezerra** [angular/angular#54369] opened 2024-02-09 20:16 UTC
### Describe the problem that you experienced

In the new Guide for Angular 17 on [Setup Http Client Testing](https://angular.dev/guide/http/testing#setup-for-testing), the following two examples are problematic to replicate. When following this example  and running some Tests this results in a `NullInjectorError: No provider for HttpClient!` Exception for the following code:

```
TestBed.configureTestingModule({
  providers: [
    ConfigService,
    provideHttpClientTesting(),
  ],
});
const httpTesting = TestBed.inject(HttpTestingController);
// Load `ConfigService` and request the current configuration.
const service = TestBed.inject(ConfigService);
```

Maybe the code examples can be modified such that on can replicate the test properly to fix the exception.

### Enter the URL of the topic with the problem

https://angular.dev/guide/http/testing#setup-for-testing

### Describe what you were looking for in the documentation

A Guide which shows me how to test Services containing http operations.

### Describe the actions that led you to experience the problem

Following the guide

### Describe what you want to experience that would fix the problem

Modified documentation

**Comment by Segdo** [comment] 2024-02-09 20:39
I think this is a duplicate of #53390 ?

**Comment by JeanMeche** [comment] 2024-02-09 20:43
Yes, we'll close this in favor of #53390.

**Closed by JeanMeche** 2024-02-09 20:43 UTC
