### ISSUE TITLE
BUG:  elements from previous route are still in the DOM when ngOnInit and ngAfterViewInit are executed

### ISSUE THREAD

**Issue by DanielHabenicht** [angular/angular#35879] opened 2020-03-05 21:50 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by Angular version 9 (Maybe @angular/core)
In Angular 8 everything was working fine. 

### Is this a regression?
No, I don't think so.

But somebody reported it before: https://github.com/angular/angular/issues/34139 but it was closed because they found a good workaround.

### Description

While switching between routes the component from the previous route stays in the DOM tree until after `AfterViewInit` in the component from the new routes is called. 
Thus something like `htmlElement.scrollIntoView()` in the new component does not work, because it is offset by the height of the component from the previous routes. 

## 🔬 Minimal Reproduction
I am currently not really able to reproduce with stackblitz: 
Working Version in Angular 8: 
https://stackblitz.com/edit/angular-router-basic-example-17yonh

Bug reproduction:
https://stackblitz.com/edit/ivy-kdzngy

But if you run:
https://github.com/T-Systems-MMS/phonebook/commit/80fb7f11790391b41428871d41d2ddad4c768080 the navigation from a user to an organigram works fine. 

With Angular 9: 
https://github.com/T-Systems-MMS/phonebook/pull/509/commits/d48aecb3fe446a8adfb5a40999341e9920fe9010
The component from the previous route (`/user/{id}`) is still attached to the DOM while the next component (`/organigram/{id}/{id}/{id}`) `AfterViewInit` is called. 
![image](https://user-images.githubusercontent.com/13590797/76027033-37f39280-5f30-11ea-9f31-d501d9c1b6df.png)

## 🔥 Exception or Error
No Error but if you call `htmlElement.scrollIntoView()` in a component on a new route it is offset by the height of the component from the previous route.

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
     _                      _                 ____ _     ___ 
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | | 
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | | 
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.0.4
Node: 12.14.0
OS: win32 x64

Angular: 9.0.4
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router, service-worker
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.4
@angular-devkit/build-angular     0.900.4
@angular-devkit/build-optimizer   0.900.4
@angular-devkit/build-webpack     0.900.4
@angular-devkit/core              9.0.4
@angular-devkit/schematics        9.0.4
@angular/cdk                      9.1.0
@angular/material                 9.1.0
@ngtools/webpack                  9.0.4
@schematics/angular               9.0.4
@schematics/update                0.900.4
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2

</code></pre>

**Anything else relevant?**
Workaround is to defer the `scollIntoView()`-Function.
```
  setTimeout(() => {
          (this.thisNode.nativeElement as HTMLElement).scrollIntoView();
        }, 100);
```

**Comment by DanielHabenicht** [comment] 2020-03-05 22:02
Might be a duplicate of https://github.com/angular/angular/issues/19742 
But this issue only occurred with Angular Version 9.

**Comment by codecoster** [comment] 2021-01-10 17:23
Bumping up this issue, since I still can reproduce this with an angular 11.0.3 app.

```
Angular CLI: 11.0.3
Node: 14.15.4
OS: linux x64

Angular: 11.0.3
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.3
@angular-devkit/build-angular   0.1100.3
@angular-devkit/core            11.0.3
@angular-devkit/schematics      11.0.3
@angular/cdk                    11.0.1
@angular/material               11.0.1
@schematics/angular             11.0.3
@schematics/update              0.1100.3
ng-packagr                      11.0.2
rxjs                            6.6.3
typescript                      4.0.5
```

Seems to be related to Animations, as this only occurs if `BrowserAnimationsModule` is imported.
https://stackblitz.com/edit/angular-ivy-mporyg?file=src%2Fapp%2Fapp.module.ts

**Comment by atscott** [comment] 2021-07-21 22:36
Closing as duplicate of #20290

The difference between Ivy and VE here would be around the change to the insertion order for embedded views in Ivy, which are inserted _in front_ of the comment node rather than _after_. The observable difference in `ngOnInit` would be that the new node appears below the old node until the animation engine flushes the removal of the old node.

Note also that the lifecycle hooks are related to Angular events, not DOM stability. See related issue and comment: https://github.com/angular/angular/issues/36054#issuecomment-716813314

**Closed by atscott** 2021-07-21 22:36 UTC
Labels: P2, comp: core, engine: ivy, freq1: low, regression, type: bug/fix
