### ISSUE TITLE
feature(router): Route configuration generic data

### ISSUE THREAD

**Issue by MunMunMiao** [angular/angular#57470] opened 2024-08-21 07:21 UTC
### Which @angular/* package(s) are relevant/related to the feature request?

router

### Description

Often we need to customize the data type of route parameters. Please provide a generic type that allows us to constrain this.

### Proposed solution

```ts
const route: Route<{breadcrumb: string, role: string}>{
  path: 'dashboard',
  data: {
    breadcrumb: 'User Dashboard',
    roleIn: 'USER_INFO'
  },
  loadComponent: () => import('./dashboard/dashboard.component')
}
```

### Alternatives considered

no

**Comment by atscott** [comment] 2024-08-26 17:28
Duplicate of canonical issue https://github.com/angular/angular/issues/38559

**Closed by atscott** 2024-08-26 17:28 UTC
Labels: area: router
