### ISSUE TITLE
FormControl bound to multiple inputs does not update the view of the other inputs after one of them is edited

### ISSUE THREAD

**Issue by JiriPelnar** [angular/angular#13859] opened 2017-01-10 11:57 UTC
I'm submitting a

[x] bug report
[ ] feature request
[ ] support request

**Current behavior**
When using angular model driven form and binding one Form Control to multiple inputs, then after editing one of these inputs, the value in Form Control is properly updated, but the other inputs views do not get updated

**Expected behavior**
The expected behavior in my point of view should be, that all the inputs bound to one Form Control should show the same value, when one of the inputs gets edited

**Minimal reproduction of the problem with instructions**
The behaviour can be observed in the following [plunk](http://plnkr.co/edit/o2r9WGhHRLc8uZAgeROK?p=preview)
There can be seen, that editing one text box does not update the other text box, but updates (as expected) the following interpolated text, which is also bound to the value of the Form Control.

**What is the motivation / use case for changing the behavior?**
Sometimes it can be useful to have two or more inputs bound to one Form Control at the same time. In my use case, I would like to have a table, which allows for editing records both inline inside a row and in a detail that can be expanded below every such row. In this case, two inputs come into existence. But other use cases come to mind and are in use in various web or desktop applications. 

* **Angular version:** 2.4.2

* **Browser:** [all]
 
* **Language:** [all]

**Comment by DzmitryShylovich** [comment] 2017-01-10 12:01
Duplicate of https://github.com/angular/angular/issues/13792

**Comment by jasonaden** [comment] 2017-12-19 23:32
Closing as duplicate of #13792

**Closed by jasonaden** 2017-12-19 23:32 UTC
Labels: comp: forms
