### ISSUE TITLE
Tracking: Better Error Messages

### ISSUE THREAD

**Issue by mhevery** [angular/angular#7481] opened 2016-03-08 05:09 UTC
**Issues**

**Other Links**
- https://daveceddia.com/angular-2-errors/
- http://www.bennadel.com/blog/3040-i-have-a-fundamental-misunderstanding-of-change-detection-in-angular-2-beta-8.htm

**Comment by btford** [comment] 2016-03-08 22:12
Some general questions:

- How do we want to address type errors at runtime for non-TS users? For instance, several of the issues raised in these blog posts are caused by passing a string when an array was expected, or vice-versa. Should we throw an exception? should we be forgiving and coerce to an array? Is there a way to mark these extra checks as not needed in production mode and strip them out?

**Comment by mhevery** [comment] 2016-03-08 22:56
Good question. @IgorMinar may have an opinion.

In AngularJS we had a utility function which could verify a type of an argument and then provide a useful error message. I think something like that may be needed here as well.

```
function someAPI(name, age) {
  assertString('name', name');
  assertNumber('age', age);
  // do the actual work. 
}
```

In prod build we could then just make these noops and inline them.

What do you think?

**Comment by btford** [comment] 2016-03-09 00:22
Seems reasonable

**Comment by dceddia** [comment] 2016-03-09 02:12
I like the `propTypes` warnings that React issues:

> React.PropTypes exports a range of validators that can be used to make sure the data you receive is valid. When an invalid value is provided for a prop, a warning will be shown in the JavaScript console. Note that for performance reasons propTypes is only checked in development mode.

I don't know which of "print a warning" or "throw an error" makes the most sense.

Some example errors:
>Warning: Failed propType: Required prop `message` was not specified in `CommentBox`.

>Warning: Failed propType: Invalid prop `message` of type `number` supplied to `CommentBox`, expected `string`.

**Comment by btford** [comment] 2016-03-09 22:29
WRT: http://www.bennadel.com/blog/3040-i-have-a-fundamental-misunderstanding-of-change-detection-in-angular-2-beta-8.htm

I think the best course of action would be to add some dev mode checks in the template compiler.

Using component metadata and the template AST, we could check for cases where a query is used in a template:

```
@Component({
  selector: "my-app",
  directives: [ Item ],
  queries: {
    itemList: new ng.core.ViewChildren( Item )
  },
  template: `
    <h2>Item Count: {{ itemList?.length }}</h2>
    <item></item>
    <item></item>`
})
class WhateverApp {}
```

Here we can give a slightly better error: `Using query 'itemList' in component 'WhateverApp' is likely to cause cycles in change detection. Consider doing Foo instead.`

I need some time with @tbosch to be sure that we can do this with his latest compiler changes.

I suspect we can expand these sort of errors to other common cases to provide better feedback than the generic change detection error.

**Comment by mhevery** [comment] 2016-03-11 04:08
So it sounds like this one will have to wait until @tbosch lands his change? Sounds reasonable.

**Comment by IgorMinar** [comment] 2016-03-11 08:04
wrt assertString  it sounds like we are reinventing AtScript all over again
:-)

if only Typescript had runtime (type) assertions...

**Comment by btford** [comment] 2016-03-11 20:32
I'd like that too. But for now I think we get good bang for our buck adding the assertions ourselves for high traffic areas where we currently throw errors like `someVar.map is not a function` for bad invocations.

**Comment by IgorMinar** [comment] 2016-03-11 20:41
I agree.

**Comment by robwormald** [comment] 2016-03-22 22:53
Error Message: `VM409 angular2.dev.js:23501EXCEPTION: TypeError: Cannot set property 'lastInBinding' of undefined`

Cause: I forgot to add a method to be called from a click event: `(click)=""`

**Comment by ericmartinezr** [comment] 2016-03-22 23:05
May I add to make this error better `EXCEPTION: Token must be defined!` ? The reason : no idea...

See this [SO question](http://stackoverflow.com/questions/36159606/how-to-get-a-better-error-message-than-token-must-be-defined-in-angular2).

**Comment by zoechi** [comment] 2016-03-23 07:43
`Invalid argument(s)` when a test component doesn't have a selector (Dart)

**Comment by zoechi** [comment] 2016-03-24 10:13
@robwormald there is an issue for that error #3754 mentioned in https://github.com/angular/angular/issues/7481#issuecomment-200068434

**Comment by zoechi** [comment] 2016-04-08 06:04
> TypeError: Cannot set property 'endSourceSpan' of null

for missing closing tag `</div>`

**Comment by zoechi** [comment] 2016-04-14 14:08
>   EXCEPTION: Error during instantiation of Router! (RouterLink -> Router).

when 2 routes have the same path

**Comment by zoechi** [comment] 2016-05-04 09:15
multiple structural directives on the same element should produce an error message #8438

**Comment by mhevery** [comment] 2016-05-13 04:58
While there are more work to be done on better error messages, we will be closing this issue in favor of other issues.

**Comment by FriOne** [comment] 2016-09-10 13:57
How about to give the errors a code?
It would nice to search needed information by it. And we even may have a doc page for it (on io like Angular 1.x errors or stackoverflow). But I guess stackoverflow would be better because of examples.

**Comment by chrisnicola** [comment] 2016-09-21 16:20
@mhevery I noticed this wasn't closed but it seems the interest in improving A2's error messages has waned. I feel like that would be a mistake. Right now error messages are pretty much my biggest complaint about this framework.

First, even something as simple as an error thrown from the constructor of a Component logs 8 different messages to the console. Most of them redundant or unimportant information. If this is supposed to be used for debugging the framework, then they should at a minimum be disabled by default.

Second, there is no way to see original source locations with Angular 2 error messages at the moment. See #11722 for more details and my attempts to debug the issue. While this is possibly an issue for the Chrome devtools team, since this primarily affects the Angular 2 development experience I feel it is relevant here.

Finally, error message handling is inconsistent depending on circumstances and where errors happen. For example, you will get different results handled by different mechanisms if the error is thrown during the construction of the module during bootstrapping vs construction of a component. Another result if an error is thrown by a downgraded angular 2 component. Different handler levels all fire and in some cases rethrow to other handler levels which appears to be the cause of all the redundant logging as well.

I'd like to know what, if anything, the Angular team has planned around improving errors and the debugging experience overall, because at the moment it seems to be very hard to work with. Perhaps I'm the only one experiencing these problems, or perhaps I'm just doing it wrong, in which case I'd like to hear what is the right way forward.

**Comment by pkozlowski-opensource** [comment] 2016-09-21 17:06
> I'd like to know what, if anything, the Angular team has planned around improving errors and the debugging experience overall, because at the moment it seems to be very hard to work with. Perhaps I'm the only one experiencing these problems, or perhaps I'm just doing it wrong, in which case I'd like to hear what is the right way forward.

@chrisnicola error messages are still _very_ important. The right / best way forward is to open small / focused issues with a minimal reproduce scenario each time you encounter a confusing error message. Unfortunately there are way to many issues that are either lacking reproduce scenario or  are taken from large apps where many different factors might be at play.

In short: we want and would fix cases we can see. Once again, let's have a small, separate issue for each case.

**Comment by chrisnicola** [comment] 2016-09-21 17:43
@pkozlowski-opensource of course, completely makes sense. So should this issue be closed then?

I've opened #11722 to address the specific issue of original source locations not working with stack traces, which seems to have been prematurely closed.

I'm also happy to open another to address the issue of multiple redundant error messages and/or more flexibility for developers to customize/control error reporting behaviour.

**Comment by pkozlowski-opensource** [comment] 2016-09-21 17:48
> I've opened #11722 to address the specific issue of original source locations not working with stack traces, which seems to have been prematurely closed.

Reopened.

> I'm also happy to open another to address the issue of multiple redundant error messages and/or more flexibility for developers to customize/control error reporting behaviour.

Sure, but please, search for duplicates first.

**Comment by b264** [comment] 2017-03-22 21:34
Opened https://github.com/angular/angular/issues/5564 for `Error trying to diff` message

**Comment by jelbourn** [comment] 2021-04-06 20:57
Closing as obsolete. Recent versions of Angular has more descriptive error messages and codes

**Closed by jelbourn** 2021-04-06 20:57 UTC
Labels: comp: core, feature
