### ISSUE TITLE
export type definitions for test_lib

### ISSUE THREAD

**Issue by rolandjitsu** [angular/angular#3423] opened 2015-07-31 08:55 UTC
Has it been considered exposing the typings for the `angular2/test_lib` module? Maybe even have it as top level module? Because I use some of the exposed methods in unit tests for the components I write, and I think that might be the case for many others, unless there is a plan for some other lib for unit tests.

**Comment by jeffbcross** [comment] 2015-08-11 23:28
Taking care of this today

**Comment by jeffbcross** [comment] 2015-08-13 20:23
Moved it to next milestone because of some complications with cross-module dependencies that I need to figure out.

**Comment by mhevery** [comment] 2015-08-21 00:12
Duplicate of #3714

**Closed by mhevery** 2015-08-21 00:12 UTC
Labels: comp: core/testbed, effort2: medium (day), P2: required, state: Periodic Review, type: feature
