### ISSUE TITLE
Bundling an angular application(pretty big) in a single custom-element

### ISSUE THREAD

**Issue by mittalsaurab** [angular/angular#37414] opened 2020-06-03 07:14 UTC
# 🐞 bug report
I am bundling an angular application(Tour Of Heroes that has multiple routes) using a custom-element feature. and then trying to run that application using the only custom-element tag in a separate folder. 
So I have three files in my newFolder 
- index.html which contains only the custom-element tag in the body.
- bundle.js which is the concatenation of main-es5.js, main-es2015.js, runtime-es5.js,runtime-es2015.js, polyfills-es5.js, polyfills-es2015.js files
- styles.css which is generated during the production build of the original project.

### Affected Package

The issue is probably caused by the package @angular/elements

### Is this a regression?
No

### Description

I am getting the following problems when I run newFolder project on a local server. The application loads the home page('/' route) properly.

1. When I go to any chid route and then refresh the browser then this application throws a 404 error.
"This application has no explicit mapping for /error, so you are seeing this as a fallback. There was an unexpected error (type=Not Found, status=404)."

2. It allows me to go other routes only using the home page anchor tags or buttons, I mean, If I type a child route path in the browser directly and hit enter then the page does not automatically refresh. Similarly, If I am on one route and then try to go back using the chrome back button(top left corner) then the only URL gets updated but the page remains the same.

3. Home page route in the browser is localserver:PORT_NUMBER/index.html but When I click on any link tag or fragment then this index.html part disappears and the route becomes localserver:PORT_NUMBER/<new_route>    So is there any way such that I can stop index.html disappearance. 
The above behavior is necessary because later this custom-element tag will be inserted in some other applications specific route page and we don't our application to modify their URL when user interacts with our application.

## 🔬 Minimal Reproduction

 https://stackblitz.com/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
Angular CLI: 9.1.7
Node: 12.16.3
OS: win32 x64

Angular:
...
Ivy Workspace:

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.901.7
@angular-devkit/core         9.1.7
@angular-devkit/schematics   9.1.7
@schematics/angular          9.1.7
@schematics/update           0.901.7
rxjs

<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by gkalpak** [comment] 2020-06-03 15:02
First of all, you should not concatenate `*-es2015.js` and `*-es5.js` scripts together. They are not supposed to be used side-by-side (some browsers will load the `*-es2015.js` ones and others the `*-es5.js` ones). See the [Differential Loading][1] section of the `Deployment` guide for more info.

Regarding the problems you mentioned, it is hard to tell what the actual cause is without a reproduction, but I will take some guesses based on the info you provided:

- The first two problems seem to be caused by the server not being configured correctly for serving an SPA. See the [relevant section][2] of the `Deployment` guide for more info.

- For the third problem, I am afraid there is not much that can be done. The functionality of the router is tied to the browser URL to some extent and I am not sure you can take advantage of the full functionality without affecting the URL.

  You could avoid the [routerLink][3] directive and use [Router#navigateByUrl()][4] with `skipLocationChange: true` for navigations. See this in action [here][5]. But I can't tell for sure whether all other functionality of Router-related APIs will work as expected.

  Alternatively, you could ditch the Router and just manually dynamically load the components into the view.

##
I am going to close this issue, because everything seems to be working as intended.
Feel free to continue the discussion below or open new issues for specific problems if you think there is something that can be fixed in the framework.

[1]: https://v9.angular.io/guide/deployment#differential-loading
[2]: https://v9.angular.io/guide/deployment#routed-apps-must-fallback-to-indexhtml
[3]: https://angular.io/api/router/RouterLink
[4]: https://angular.io/api/router/Router#navigateByUrl
[5]: https://stackblitz.com/edit/ng-issue-37414

**Closed by gkalpak** 2020-06-03 15:02 UTC
Labels: comp: elements, state: Needs repro
