### ISSUE TITLE
Ivy regression: fullTemplateTypeCheck, ngIf and null checks

### ISSUE THREAD

**Issue by mstawick** [angular/angular#33312] opened 2019-10-22 07:12 UTC
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/language-service

### Is this a regression?
Yes.
It worked fine in 9.0.0-next.10

### Description
TS2531: Object is possibly 'null' error is reported, even though object has been checked to be non-null

## 🔬 Minimal Reproduction
enable fullTemplateTypeCheck

```
export interface Bar {
  bar: string;
}
foo: Bar|null = null;
```

and in template:

```
<div *ngIf="foo != null>
    {{ foo.bar }}
</div>
```

## 🔥 Exception or Error
<pre><code>
TS2531: Object is possibly 'null'
</code></pre>

## 🌍  Your Environment
**Angular Version:**
<pre><code>
Angular CLI: 9.0.0-next.13
Node: 10.15.3
OS: linux x64
Angular: 9.0.0-next.12
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.900.0-next.13
@angular-devkit/build-angular      0.900.0-next.13
@angular-devkit/build-optimizer    0.900.0-next.13
@angular-devkit/build-webpack      0.900.0-next.13
@angular-devkit/core               9.0.0-next.13
@angular-devkit/schematics         9.0.0-next.13
@angular/cdk                       8.2.3
@angular/cli                       9.0.0-next.13
@angular/localize                  9.0.0-next.5
@angular/material                  8.2.3
@angular/material-moment-adapter   8.2.3
@ngtools/webpack                   9.0.0-next.13
@schematics/angular                9.0.0-next.13
@schematics/update                 0.900.0-next.13
rxjs                               6.5.3
typescript                         3.6.4
webpack                            4.41.2
</code></pre>

**Comment by merobal** [comment] 2019-12-19 11:55
Additional thoughts:
- After I switched off `fullTemplateTypeCheck` it compiles well.
- Before Angular 9 the `fullTemplateTypeCheck` only checked types (interfaces), now it checks null-s, however I would expect to set it independently in tsconfig (or maybe I experience our issues due to the same bug, I'll double check after it's fixed).

**Comment by timo-haas** [comment] 2020-02-09 07:32
still an issue in Angular 9.0.0

**Comment by alxhub** [comment] 2020-05-27 20:38
Closing, as I was unable to reproduce this in https://stackblitz.com/edit/angular-ivy-cvf5kl?file=src%2Fapp%2Fapp.component.ts. We've made a lot of improvements in template type-checking, and this seems to have been fixed along the way. Please feel free to open a new issue with a repro if not!

**Closed by alxhub** 2020-05-27 20:38 UTC
Labels: comp: compiler, engine: ivy, freq2: medium, severity5: regression, type: bug/fix
