### ISSUE TITLE
Router : undefined component throws Cannot read property annotations of undefined

### ISSUE THREAD

**Issue by ericmartinezr** [angular/angular#9414] opened 2016-06-21 21:31 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
```

**Current behavior**
When defining an undefined component for a router route this error will be thrown

```
Error: Uncaught (in promise): TypeError: Cannot read property 'annotations' of undefined
```

**Expected/desired behavior**
It should throw a clear message indicating where the undefned component is. Considering that this is the router, we can use the path of the route to point exactly where the problem is (I guess)

**Reproduction of the problem**
Check this plnkr http://plnkr.co/edit/UJFH44?p=preview, see the file `app/crisis-center/crisis-center.routes.ts` and this config

```
export const CrisisCenterRoutes = [
  {
    path: '/crisis-center',
    component: undefined, <<< HERE!!
    children: [
      { path: '', component: CrisisListComponent },
      { path: '/:id', component: CrisisDetailComponent, canDeactivate: [CrisisDetailGuard] }
    ]
  }
];

```

I had a PR for this issue with the beta router, but it never landed and we all know the story of the router https://github.com/angular/angular/pull/7745

I'm not sure if this can be reproduced outside the router world, so I can't say if this should be fixed in the router itself or before the router acts.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.X
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5 | Dart]

**Comment by andrui** [comment] 2016-06-22 13:04
Hi!

According to the validateNode() https://github.com/angular/angular/blob/2.0.0-rc.3/modules/%40angular/router/src/config.ts Route configuration should have one of the properties (redirectTo, component, children):

```typescript  
if (route.redirectTo === undefined && !route.component && !route.children) {
    throw new Error(
        `Invalid configuration of route '${route.path}': component, redirectTo, children must be provided`
    );
}
```

So, for nested routing configuration like below should work:
```typescript
export const routes: RouterConfig = [
    {
        path: '',
        children: [
            {
                path: '',
                component: Comp1
            },
            {
                path: 'comp2',
                children: [
                    {
                        path: '',
                        component: Comp2
                    },
                    {
                        path: 'comp3',
                        component: Comp3
                    }
                ]
            }
        ]
    }
];
```
But I face the error: "TypeError: Cannot read property 'annotations' of undefined"

In my case App component and components Comp1, Comp2 have rouer outles inside their templates. The goal is: by accessing url like mydomain.com/comp2/comp3 see all components on page. Similar problem was in beta router with "useAsDefault" for child routes (path: '' in v3 router looks like analog of "default" route). As a workaround (for beta and v3 routers) I use dummy component (with empty template) to achieve my goal:

```typescript
export const routes: RouterConfig = [
    {
        path: '',
        component: Comp1,
        children: [
            {
                path: '',
                component: DummyComponent
            },
            {
                path: 'comp2',
                component: Comp2,
                children: [
                    {
                        path: '',
                        component: DummyComponent
                    },
                    {
                        path: 'comp3',
                        component: Comp3
                    }
                ]
            }
        ]
    }
];
```

Here is plunker with working solution for rc1 router (without any workarounds) https://plnkr.co/edit/8QP1BBI3qGgwedKrJB6W?p=preview

Here is plunker with working solution for v3 router (with "DummyComponent" workaround) http://plnkr.co/edit/wNEBSHAfS9C2OncfgHYH?p=preview

Here is plunker with initial issue reproduce (route with "path: 'page1'" with undefined component, click "Page 1") for v3 router (without "DummyComponent" in child routing) http://plnkr.co/edit/yqTmdtn9dj3HsgkjfDoy?p=preview

And here is plunker with configuration which looks naturally (like for rc1 router) but doesn't work (because of "Error: Cannot match any routes: ''" error) http://plnkr.co/edit/NR14SMHW97mBBMUmLvNm?p=preview

**Comment by vsavkin** [comment] 2016-06-29 01:02
We recently landed a feature called 'componentless' routes (see here https://github.com/angular/angular/blob/master/modules/@angular/router/src/config.ts#L188), which fixed the issue.

**Closed by vsavkin** 2016-06-29 01:02 UTC
Labels: comp: router, type: feature

**Comment by ericmartinezr** [comment] 2016-06-29 02:08
@vsavkin that's not really the point. If I'm using a component for a route, and for any reason I make a mistake (e.g I pass an interface, etc) that will be undefined. It's not really that important since most people use IDEs and compilers (TS) that help with imports, but if you consider it's not a big deal I'm ok with it.

**Comment by vsavkin** [comment] 2016-07-22 20:52
@ericmartinezr 

Sorry, let me clarify what I meant.

1. Because of componentless routes, the following is a correct route: `{path: 'a', children: [...]}.
2. We cannot distinguish between the following two cases at runtime

```
{path: 'a', component: MyComponent, children: [...]} // where MyComponent is undefined
{path: 'a', children: [...]}
```

So the router itself cannot do anything about it. If MyComponent is undefined, it will treat the first route as componentless.

3. We can have a linter checking that everything passed-in is a component, but it is out of scope for now.

**Comment by ericmartinezr** [comment] 2016-07-22 21:00
@vsavkin thanks for your answer. Let me ask you one last thing : could the router use hasOwnProperty to check if the "component" property exists and its value is undefined to distinguish between those cases? That's whar I did in my PR for the beta router.

**Comment by andrui** [comment] 2016-07-25 08:20
@vsavkin in scope of your example I have one question. With componentless route all is clear. But if I have defined "component" and  "children", why is it mandatory to define one empty route '' in "children" routes?

e.g. configuration below will not work: when I try to go mydomain.com/a I receive error that there is no route for ''. It is obvious for componentless route (we need to define endpoint which is going to be loaded). But in my case I have defined component "MyComponent" to load by url mydomain.com/a

```typescript
{path: 'a', component: MyComponent, children: [
    {
        path: 'b',
        component: SubComponent2
    },
    {
         path: 'c',
         component: SubComponent2
    }
]}
```

Maybe it has been already fixed for master branch?

Thank you in advance!
