### ISSUE TITLE
Keyvalue Pipe does not work on string/number enum, showing duplicates

### ISSUE THREAD

**Issue by dancoltonart** [angular/angular#41024] opened 2021-02-27 04:29 UTC
# 🐞 bug report

### Affected Package
@angular/common

### Is this a regression?

no

### Description
Angular keyvalue pipe is not working on enum below. Its showing this in my Angular dropdown, both Key and Value twice. I only want to see Honda Accord text.

```
export enum test{
  "Honda Accord" = 2
};

<div *ngFor="let testItem of test | keyvalue">
    {{test.key}}

```
![image](https://user-images.githubusercontent.com/68444172/109375238-32ddd080-7870-11eb-915f-b41ec476f001.png)

When I make 2 with string quote, it will work. I want it working both ways. They claim it is the expected behavior,  If that is expected behavior, a New pipe maybe needed for real customer usability.

https://stackoverflow.com/questions/66395350/angular-keyvalue-pipe-not-working-on-string-number-enum-showing-duplicates?noredirect=1#comment117380113_66395350
```
export enum test {
  "Honda Accord" = "2"
};

```
This relegates all enums to being worthless for the keyvalue pipe;  enum values can be numbers, not only for string.
If so, does Angular have an alternative solution without writing another custom keyvalue pipe?

## 🔬 Minimal Reproduction

 https://stackblitz.com/edit/angular-key-value-pipe-demo-cdch7f?file=src/app/app.component.html

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**  11.07
<pre><code>

</code></pre>

**Anything else relevant?**
  no

**Comment by Airblader** [comment] 2021-02-27 07:42
They keyvalue pipe is doing exactly what it is supposed to do here. It doesn't have any knowledge that the object is an enum, at runtime this information doesn't exist. Someone linked another SO issue on your question that shows what the object generated by TS looks like, and for such an object this is what the keyvalue pipe does.

**Comment by dancoltonart** [comment] 2021-02-27 09:36
hi @Airblader we aren't talking about technical reasons, talking about a strictly usability purpose, getting from point A to B,  no point of having a keyvalue  if it doesn't work with actual values, the stack article actually referred to another custom keyvalue mapper from third party coder

I guess my question is,  what is your Solution? rather than talking about bugs. Should I just create a keyvalue mapper that is better than Angular official team is supposed to be? 

export enum test{
  "Honda Accord" = 2
};

**Comment by Airblader** [comment] 2021-02-27 09:47
> no point of having a keyvalue if it doesn't work with actual values

But it does work, and it does exactly what it says it does: it maps the keys and values of an object.

Again, TS emits a specific object structure for this enum. At runtime, when the keyvalue pipe is called, there simply is no enum anymore since enums do not exist in JS. The pipe cannot possibly know that you're feeding it an object that used to be an enum.

They keyvalue pipe is also not meant to be a "enum keys pipe", and isn't advertised as such anywhere. The intent of this pipe is to map all key value pairs of an object and that is what it does. The issue is not the pipe, it's what you're putting into the pipe.

> the stack article actually referred to another custom keyvalue mapper from third party coder

The solution provided there basically just ignores half the keys of the object. That happens to work for these objects, but it certainly doesn't work for arbitrary objects and thus makes for a poor general solution.

**Comment by Airblader** [comment] 2021-02-27 09:52
Just to illustrate the point, execute the following snippet:

```
enum Foo {
  A = 1,
  B = 2,
}

console.log(Object.keys(Foo)); // ["1", "2", "A", "B"]
```

Would you argue that `Object.keys` is broken in all browsers and JS implementations?

**Comment by gkalpak** [comment] 2021-02-27 13:27
To re-iterate what @Airblader said above, TypeScript Enums are compile-time constructs (since JavaScript does not support Enums). At runtime, Enums are compiled down to plain JavaScript objects. TypeScripts compiles numeric Enums (i.e. Enums with numeric values) to objects with a reverse mapping (from values to keys) in addition to the direct mapping (from keys to values).

So, for example:

```ts
enum Foo {
  Bar = 2,
};

enum Baz {
  Qux = '2',
}
```

...will be compiled by TypeScript to something like:

```js
var Foo = {
  Bar: 2,
  2: 'Bar',
};

var Baz = {
  Qux: '2',
};
```

You can read more about TypeScript Enums [here][1].

##
Based on the above, the `keyvalue` pipe has no way to know whether the object it receives at runtime is a result of compiling an Enum or if it was a regular object. As mentioned in the comments above, the `keyvalue` pipe receives an object with two properties and iterates over them as it is supposed to.

In this case, once you are aware of what code is emitted by TypeScript, you can decide how to handle this. For example, (depending on your usecase) you could use a non-numeric Enum or use a plain JavaScript object or create a custom pipe that suits your needs.

##
I am going to close this, since everything works as expected, but feel free to continue the discussion below.

[1]: https://www.typescriptlang.org/docs/handbook/enums.html

**Closed by gkalpak** 2021-02-27 13:27 UTC

**Comment by dancoltonart** [comment] 2021-02-27 18:32
Okay, this is definitely good insight,  so in my example, of string/number enum,
How would you iterate through the whole list, and just get keys for the dropdown?

I don't necessary have to use the keyvalue pipe,  is there another alternative? or should I use this pipe https://stackoverflow.com/questions/38554562/how-can-i-use-ngfor-to-iterate-over-typescript-enum-as-an-array-of-strings/38554683#38554683 ? or do you recommend anything else? 

My last solution, is having to convert my 50 enums to object models, which I'm reluctant to do for right now,

export enum test{
  "Honda Accord" = 2,
  "Toyota Camry" = 3
   ....
};

Thanks for the info,

**Comment by gkalpak** [comment] 2021-03-01 14:28
As mentioned above, it depends on your exact requirements/needs.

Obviously, TypeScript Enums is not a good structure if you plan on iterating over the keys, but if I had to do it (because I didn't want to change my many Enums to Objects, for example :wink:) I would probably create a custom pipe similar to that from [StackOverflow answer #38554683][1] (see below).

The problem I see with the one from [StackOverflow answer #38554683][1], which discards the half first keys is that it is not very robust against TypeScript changing their emitted code (for example, reversing the order of keys). So, I would make a modification to only discard keys that look like numbers and only if there is a nother key equal to their value.

Sample code:

```ts
@Pipe({name: 'enumKeyValue'})
export class EnumKeyValue implements PipeTransform {
  transform(obj: object) {
    return Object.entries(obj).
      filter(([key, value]) =>
        !/^\d+$/.test(key) ||         // Include keys that don't look like integers or...
        !obj.hasOwnProperty(value)).  // ...include keys whose values do not appear as keys also.
      map(([key, value]) => ({key, value}));
  }
}
```

[1]: https://stackoverflow.com/questions/38554562/how-can-i-use-ngfor-to-iterate-over-typescript-enum-as-an-array-of-strings#38554683

**Comment by petebacondarwin** [comment] 2021-03-01 15:16
👍 what @gkalpak says. Another option is to filter by converting the key to a number and comparing with the original string:

```
parseInt(key, 10).toString() === key
```
