### ISSUE TITLE
Input type="date" [(ngModel)]="obj.DOB" not displaying the date

### ISSUE THREAD

**Issue by selvamsubramani** [angular/angular#31875] opened 2019-07-28 16:59 UTC
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

Please help us process issues more efficiently by filing an
issue using one of the following templates:

https://github.com/angular/angular/issues/new/choose

Thank you!

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

student.ts:
Obj: Student = new Student { Id: 1, FirstName:'Selvam', DOB:new Date(1990, 2, 1) };
student.html
<form #f="ngForm">
<input type="text" [(ngModel)]="Obj.FirstName">
<input type="date" [(ngModel)]="Obj.DOB">
</form>

Problem: Not displaying the value in DOB.

Please share the solution to the problem.

Regards,
Selvam S

**Comment by santoshyadav198613** [comment] 2019-07-28 17:04
Hi @selvamsubramani ,

Please raise this issue on stackoverflow with Angular tag, as this is not an issue with framework.

**Comment by Airblader** [comment] 2019-07-29 05:12
As per specification, date inputs do not take Date objects but string values.

This is a duplicate of https://github.com/angular/angular/issues/8203

**Comment by atscott** [comment] 2019-08-13 22:25
Duplicate of #8203

**Closed by atscott** 2019-08-13 22:25 UTC
Labels: comp: forms
