### ISSUE TITLE
[attr.name] binding on radio inputs not working with [formControl]

### ISSUE THREAD

**Issue by cheneyd-mhr** [angular/angular#29922] opened 2019-04-16 10:32 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/forms

### Is this a regression?

 No.

### Description

 When using multiple radio sets within the same form angular does not respect the [attr.name] binding to group the radio sets. This means that when the value is changed in one group it updates all radio sets without a name to the same value.

## 🔬 Minimal Reproduction

 
[https://stackblitz.com/edit/angular-qsfjba](https://stackblitz.com/edit/angular-qsfjba)

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 7.0.7
Node: 10.15.0
OS: win32 x64
Angular: 7.2.13
... common, compiler, core, forms, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.10.7
@angular-devkit/build-angular     0.10.7
@angular-devkit/build-optimizer   0.10.7
@angular-devkit/build-webpack     0.10.7
@angular-devkit/core              7.0.7
@angular-devkit/schematics        7.0.7
@angular/cli                      7.0.7
@angular/compiler-cli             7.0.4
@angular/language-service         7.0.4
@ngtools/webpack                  7.0.7
@schematics/angular               7.0.7
@schematics/update                0.10.7
rxjs                              6.4.0
typescript                        3.1.6
webpack                           4.19.1
</code></pre>

**Anything else relevant?**

**Comment by alexzuza** [comment] 2019-04-16 12:12
Hey!

I agree that it's a bit weird but as soon as you apply formControl directive on your `input[type=radio]` elements they are controlled by [RadioControlValueAccessor](https://github.com/angular/angular/blob/f8096d499324cf0961f092944bbaedd05364eea1/packages/forms/src/directives/radio_control_value_accessor.ts#L96) directive. 
This directive ties radio inputs through [RadioControlRegistry](https://github.com/angular/angular/blob/f8096d499324cf0961f092944bbaedd05364eea1/packages/forms/src/directives/radio_control_value_accessor.ts#L25) depending on the provided **Input** name.
Since you didn't provide that input property Angular thinks that all those controls belong to the same group.

So try adding name property for your inputs and see if it helps.

```
<input ... [name]="radioName0"
```

https://stackblitz.com/edit/angular-fdrtvt?file=src/app/app.component.html

**Comment by cheneyd-mhr** [comment] 2019-04-16 12:32
Thanks for your reply, yea we are using this approach at the moment to get around the issue but it seems like something which shouldn't be necessary.

**Comment by cheneyd-mhr** [comment] 2019-04-16 13:03
Also one thing I didn't mention was that if you do the attribute binding as `name="{{radioName0}}"` then the radio set works as expected, which is still binding to the attribute as I understand it unless it works in a different way.

**Comment by alexzuza** [comment] 2019-04-16 14:06
When you use the syntax `name="{{radioName0}}"` then Angular adds `name` attribute to element and also treats it as a property binding(@Input name)

**Comment by sod** [comment] 2019-04-23 13:26
Had the same issue. Hard to debug, because in html its syntactically correct, but angular groups them all together with the group name `null` and overrides the html behavior.

Reproduction: https://stackblitz.com/edit/angular-k6f2qj

The issue is this method `_isSameGroup`:

https://github.com/angular/angular/blob/f8096d499324cf0961f092944bbaedd05364eea1/packages/forms/src/directives/radio_control_value_accessor.ts#L61-L67

As name is `null` for all radios with `<input type="radio" [attr.name]="..."`, they are all treated as being one group.

**Comment by kara** [comment] 2019-04-23 22:23
The way radio buttons work with `attr.name` and `[name]` is not ideal, and it's on the list to fix. This issue is currently being tracked [here](https://github.com/angular/angular/issues/11757) though, so closing this one as a duplicate.

**Closed by kara** 2019-04-23 22:23 UTC
Labels: comp: forms
