### ISSUE TITLE
@HostListener() combined with a global hammer.js event throws exception

### ISSUE THREAD

**Issue by JohnKis** [angular/angular#12566] opened 2016-10-27 15:06 UTC
**I'm submitting a ...**  (check one with "x")

```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Declaring a HostListener for a global hammer.js event throws an exception.
Example:

```
@HostListener('window:pan') onPan() { }
```

Exception:

```
error_handler.js:46EXCEPTION: Uncaught (in promise): Error: Error in ./LauncherComponent class LauncherComponent - inline template:3:8 caused by: not implemented
Error: Error in ./LauncherComponent class LauncherComponent - inline template:3:8 caused by: not implemented
    at ViewWrappedError.BaseError [as constructor] (http://localhost:4200/main.bundle.js:6492:34)
    at ViewWrappedError.WrappedError [as constructor] (http://localhost:4200/main.bundle.js:6521:16)
    at new ViewWrappedError (http://localhost:4200/main.bundle.js:42330:16)
    at _View_LauncherComponent0.DebugAppView._rethrowWithContext (http://localhost:4200/main.bundle.js:60130:23)
    at _View_LauncherComponent0.DebugAppView.create (http://localhost:4200/main.bundle.js:60076:18)
    at _View_OutsideRoomComponent0.createInternal (OutsideRoomComponent.ngfactory.js:104:15)
    at _View_OutsideRoomComponent0.AppView.create (http://localhost:4200/main.bundle.js:59861:21)
    at _View_OutsideRoomComponent0.DebugAppView.create (http://localhost:4200/main.bundle.js:60073:44)
    at _View_OutsideRoomComponent_Host0.createInternal (OutsideRoomComponent_Host.ngfactory.js:18:14)
    at _View_OutsideRoomComponent_Host0.AppView.create (http://localhost:4200/main.bundle.js:59861:21)
```

**Expected behavior**
I'd expect this to work, just as it's working with any non-hammer.js events

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/QpH2LUGFigSW2Jo67I3d

**What is the motivation / use case for changing the behavior?**
I'm building a slide-out side menu which only renders it's contents when it's active. To be able to slide it out, I need to listen on pan events on the window 

**Please tell us about your environment:**
macOS Sierra, Visual Studio Code, NPM
- **Angular version:** 2.0.0
  It is
- **Browser:**
  all
- **Language:**
  Possibly all, although I only tested using TypeScript 2.0.3 
- **Node (for AoT issues):** `node --version` =   6.3.0

**Comment by DzmitryShylovich** [comment] 2016-10-27 15:26
It's not a bug but a feature request.

**Comment by JohnKis** [comment] 2016-10-27 15:31
I'm happy to modify it, though I still think that it's a bug, since global listeners are working with literally any events but hammer.js defined ones.

E.g.:
```
@HostListener('window:somedummyevent') onEvent() { }
```
works just fine without throwing any exceptions.

**Comment by tbosch** [comment] 2016-11-04 18:13
You probably know, but using global events for gestures can lead to jank...
Anyways, yes, this is a feature request.

**Comment by JohnKis** [comment] 2016-11-05 08:37
Yeah, I'm aware.
Changed the issue to be a feature request.

Thanks

**Comment by DzmitryShylovich** [comment] 2016-11-15 20:23
@vicb this was fixed and can be closed

**Comment by DzmitryShylovich** [comment] 2016-12-10 07:45
@pkozlowski-opensource can u close this one?

**Closed** 2016-12-10 08:44 UTC
Labels: comp: core & compiler, freq1: low, type: feature
