### ISSUE TITLE
Importing EventEmitter order

### ISSUE THREAD

**Issue by denkomanceski** [angular/angular#6831] opened 2016-02-02 01:05 UTC
I have this very weird problem that I solved by luck. When I try to import my class AFTER importing EventEmitter from angular/core it shows an error `TypeError: core_2.EventEmitter is not a function`, when I change the line and import the class BEFORE the EventEmitter Import the app works perfectly fine. Here is gif from that 
![orderbug](https://cloud.githubusercontent.com/assets/10501247/12736537/57d7be38-c951-11e5-8ad1-0e17edc6dd06.gif)

Am I missing something or what is the problem ? 
I almost gave up on this one :(

**Comment by zoechi** [comment] 2016-02-02 08:34
Can you provide a repo Plunker?

**Comment by pkozlowski-opensource** [comment] 2016-06-19 05:47
Closing as we don't have reproduce scenario.

**Closed by pkozlowski-opensource** 2016-06-19 05:47 UTC

**Comment by zoechi** [comment] 2016-06-19 06:36
I guess this was because of mixing `'` and `"` in imports. That's not an Angular2 issue. I don't know if the root cause was fixed already. AFAIR it's a TypeScript issue.

**Comment by gdi2290** [comment] 2016-06-20 00:04
this problem might be due to having two `angular2/core` imports rather than one. I've had that problem in the past
