### ISSUE TITLE
Feature Request: Compiler verification of event binding names similar to property binding

### ISSUE THREAD

**Issue by stringham** [angular/angular#17483] opened 2017-06-13 22:16 UTC
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[ ] Bug report 
[X] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
When parsing templates, Angular will complain if you attempt to bind to a property that isn't a known property:

```typescript
`Can't bind to '${boundProp.name}' since it isn't a known property of '${elementName}'.`;
```
(https://github.com/angular/angular/blob/5af143e8e43cb1c0d0560c558271f9d3b7201da9/packages/compiler/src/template_parser/template_parser.ts#L740-L751)

This is really helpful when changing `@Input()` names on existing components. Is it possible to have similar verification for `@Output()` names?

cc: @tbosch

**Comment by intellix** [comment] 2018-01-18 14:14
Getting runtime errors here as they're not caught by AOT. When we don't import a module containing an event binding directive, it just causes nothing to happen in production:

Example: https://stackblitz.com/edit/angular-ccug8k?file=app%2Fapp.component.html

**Confirm directive:**
```ts
import { Directive, HostListener, Output, EventEmitter } from '@angular/core';

@Directive({
  selector: '[appConfirm]'
})
export class ConfirmDirective {

  @Output() appConfirm = new EventEmitter<boolean>();

  constructor() { }

  @HostListener('click')
  onClick() {
    const result = confirm('Are you sure?');
    this.appConfirm.next(result);
  }

}
```

**Usage:** 
```html
<button (appConfirm)="$event && hello()">Confirm greeting</button>
```

**Comment by trotyl** [comment] 2018-02-17 06:29
Relates to #3426

**Comment by devauxbr** [comment] 2018-10-10 18:34
Isn't this related to https://github.com/angular/angular/issues/24625 ?

**Comment by pkozlowski-opensource** [comment] 2018-10-29 16:15
This is a duplicate of #3426

**Closed by pkozlowski-opensource** 2018-10-29 16:15 UTC
Labels: comp: core & compiler, type: feature
