### ISSUE TITLE
Attribtue-Directive with Selector only, doesn't work

### ISSUE THREAD

**Issue by GreenToast** [angular/angular#6453] opened 2016-01-13 10:58 UTC
This issue  is a bit related to #6394. I have created a small plunker which describes the problem 

http://plnkr.co/edit/xFJuCyYaRexnbn0nk5zX

The Input "@Input() mydraggable: string;" is not really necessary because the directive needs no input. But the selector alone isn't sufficient. If I uncomment the @Input the directive stops to work.

**Comment by ericmartinezr** [comment] 2016-01-13 11:04
Fix your plnkr please

**Comment by GreenToast** [comment] 2016-01-13 11:46
Sorry my Plunkr didn't save correctly. Works now again.

**Comment by ericmartinezr** [comment] 2016-01-13 12:21
@GreenToast I don't really see the problem. Everything is working fine. Could you reproduce the issue and the steps to trigger it? Also you should move your questions to [gitter's chatroom](https://gitter.im/angular/angular), StackOverflow and such, you'll get more help. Github is for bugs and that kind of issues.

**Comment by GreenToast** [comment] 2016-01-13 12:37
I updated the Plunkr link. Its now in the failure-case. 

The @Input myDragable is uncommented, because it is never really used in the code. But it's working only when I have it the Input as dummy there. The selectorattribute alone is not sufficient alone to load the Directive in the Component.

**Comment by ericmartinezr** [comment] 2016-01-13 14:13
When you have this

```
<h1 [myDraggable]>...
```
It's expecting to be an input, something that goes inside your component, that's why it works when you add `@Input`.

This is working like it should. If you want it to be a selector and an input you can't, you have to do

```
<h1 myDraggable [myDraggable]="someValueThatGoesToYourComponent">...
```

**Comment by pkozlowski-opensource** [comment] 2016-01-13 14:39
@ericmartinezr is right when saying:

> When you have `<h1 [myDraggable]>...` it's expecting to be an input, something that goes inside your component, that's why it works when you add `@Input`. This is working like it should.

But 

> If you want it to be a selector and an input you can't

raises my eyebrows as you _can_ have selectors matching inputs of other directives: http://plnkr.co/edit/MSx0B1G2qeK6wqvSB1W5?p=preview

In any case it works as expected so closing this one.

**Closed by pkozlowski-opensource** 2016-01-13 14:39 UTC

**Comment by ericmartinezr** [comment] 2016-01-13 16:22
@pkozlowski-opensource 

I said that because of this PR https://github.com/angular/angular/pull/5914, probably I misunderstood what it does :P

**Comment by GreenToast** [comment] 2016-01-13 16:50
I understood now that I could write myDraggable as attribute without the brackets to get the plunkr above working http://plnkr.co/edit/xFJuCyYaRexnbn0nk5zX?p=preview. But what is now little bit strange the Directive still needs the brackets in the selector, when no Input is there. In my opinion this is confusing.

**Comment by pkozlowski-opensource** [comment] 2016-01-13 16:53
> But what is now little bit strange the Directive still needs the brackets in the selector, when no Input is there. In my opinion this is confusing.

It is a CSS selector and brackets in CSS selectors mean "attribute". So even if you use the same brackets symbols in 2 places (HTML of a template and CSS selector) the actual meaning of this symbol is very different....

**Comment by GreenToast** [comment] 2016-01-13 16:57
@pkozlowski-opensource:

Thanks for the explanation, I get the technical differenation now. The overlapping of html and css-syntax is a bit unlucky there.
