### ISSUE TITLE
Leading comma in canActivate list is not reported during build time but crashes out in run time. Error logged is also not helpful in debugging.

### ISSUE THREAD

**Issue by irojgurung** [angular/angular#57976] opened 2024-09-26 14:03 UTC
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

Adding a leading comma by mistake in canActivate list of guards is not caught duuring build time and crashes out during run time with error that is not helpful.
Sample Code:
{ 
  path:'',
 canActivate: [, AuthGuard],
}

No Error in build time.

Run time error:
![image](https://github.com/user-attachments/assets/4ef698de-e013-4597-ac79-7fe143ac4a41)

**Comment by JeanMeche** [comment] 2024-09-26 14:07
This is due to the typing of `canActivate` that accepts `any[]|undefined`. This makes it a duplicate of #38559.

**Closed by JeanMeche** 2024-09-26 14:07 UTC
