### ISSUE TITLE
The link to the complete list of built-in pipes does not function

### ISSUE THREAD

**Issue by it-illyria** [angular/angular#53685] opened 2023-12-22 11:42 UTC
### Describe the problem that you experienced

I am working with some build-in pipes for a project in Angular and i opened the [angular.dev](https://angular.dev/guide/pipes) documentation for pipes and the link for going to [pipes API documentation](https://angular.dev/api/common#pipes) that has the list of the Pipes does not function and opens to error 404.

### Enter the URL of the topic with the problem

https://angular.dev/api/common#pipes

### Describe what you were looking for in the documentation

I want to go to the list of the API-s that holds Pipes.

### Describe the actions that led you to experience the problem

I tried to open the link that is in the documentation

### Describe what you want to experience that would fix the problem

f possible to redirect to the specific link.

### Add a screenshot if that helps illustrate the problem

![image](https://github.com/angular/angular/assets/140395550/0d573bf1-8a7c-4a2e-a884-54d1c0f8fc52)

### If the problem is browser-specific, please specify the device, OS, browser, and version

```true
The browser is mozilla, Chrome, Edge
```

**Comment by JoostK** [comment] 2023-12-22 11:56
Thanks for the report, closing as duplicate of https://github.com/angular/angular/issues/52968.

**Closed by JoostK** 2023-12-22 11:56 UTC
