### ISSUE TITLE
Some of the datepipes stopped working with RC2

### ISSUE THREAD

**Issue by quiringk** [angular/angular#9378] opened 2016-06-20 23:21 UTC
**I'm submitting a ...**  (check one with "x")

```
[ X ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

( dateVariable | date:'yMMMMdjm') is producing '2016May1311 AM0'

**Expected/desired behavior**

should produce May 13, 2016 11:00 AM like it was before updating

**Please tell us about your environment:**
- **Angular version:** 2.0.0-rc.2
- **Browser:** [Chrome 51.0.2704.103 m] 
- **Language:** [TypeScript 1.8.10]

**Comment by vicb** [comment] 2016-06-21 00:33
@laskoviymishka could you please take a look at this ? Seems like it has been introduced in https://github.com/angular/angular/commit/324f0147f672b5f341d978910c6e64453cbe89e6#diff-59c005d76b788f67bc098f67b659d862

**Comment by laskoviymishka** [comment] 2016-06-21 05:16
Does it really bug? This pattern is not alias pattern, so it combined part by part. Like a regular date pattern.

There is no way to handle this scenario, beside to introducing new alias. I not sure that this is best option. May be it better to extend API for pipe a little bit, by adding ability to pass pure Intl formatter options object? And if such object passed use it.

**Comment by laskoviymishka** [comment] 2016-06-21 06:17
I not sure how it should better orgonized, but if we will handle all not aliases pattern (such as `yMMMdjm` and `yMMMMdjm`) then customize date formatting wil not be possible at all. 

There is probably should be a way to handle such requirement in more natural way. 
I propose to add ability for passing already defined `Intl.DateTimeFormatOptions` object to date pipe for such scenarios. Api remain almost same:
```
export class CompA {
  format: Intl.DateTimeFormatOptions;
  constructor(){
    this.date = new Date();
    this.format =  { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' };
  }
}
```

And in template:
```
<h1>Date: {{date | date : formate}}</h1>
```

**Comment by pkozlowski-opensource** [comment] 2016-12-19 19:33
This is duplicate of #11661

**Closed by pkozlowski-opensource** 2016-12-19 19:33 UTC
Labels: comp: common, type: bug
