### ISSUE TITLE
Page not found 

### ISSUE THREAD

**Issue by dagarint** [angular/angular#52576] opened 2023-11-07 11:14 UTC
### Describe the problem that you experienced

Hello,

when I click on the "Making HTTP requests" button on the page at "https://angular.dev/guide/http", I expect it to open content about that topic. However, I encounter a "Page Not Found" error. 

 Tomaž

### Enter the URL of the topic with the problem

https://angular.dev/guide/http

**Comment by JoostK** [comment] 2023-11-07 11:30
Thanks for the report! This is a duplicate of #52542.

**Closed by JoostK** 2023-11-07 11:30 UTC
