### ISSUE TITLE
Unhandled Promise rejection: undefined is not a function

### ISSUE THREAD

**Issue by Daminoushka** [angular/angular#18062] opened 2017-07-11 16:02 UTC
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[x ] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When I deploy my project into my servers I got some errors when I test on old browsers (Chrome 38)
I need this browser because my angular 2 project has to be deployed on custom screens with embed browser, no way to upgrade it.
If I test it with my local source with this old Chrome 38 it works. But after a ng-build command and the deployement of the package it's not working anymore.
I uncomment all the imports in polyfills.js and i still got this error :

`ZoneAwareError: Uncaught (in promise): TypeError: undefined is not a function
TypeError: undefined is not a function
    at BindingParser.parsePropertyBinding

Unhandled Promise rejection: undefined is not a function ; Zone: <root> ; Task: Promise.then ; Value: TypeError: undefined is not a function TypeError: undefined is not a function
    at BindingParser.parsePropertyBinding (http://satisfaction.preprod.decathlon.com/vendor.bundle.js:56003:18)
    at http://satisfaction.preprod.decathlon.com/vendor.bundle.js:55872:27
    at Array.forEach (native)
    at BindingParser.createDirectiveHostPropertyAsts (http://satisfaction.preprod.decathlon.com/vendor.bundle.js:55869:49)
    at parseHostBindings (http://satisfaction.preprod.decathlon.com/vendor.bundle.js:13001:51)
    at DirectiveWrapperCompiler.compile (http://satisfaction.preprod.decathlon.com/vendor.bundle.js:12682:48)
    at JitCompiler._compileDirectiveWrapper (http://satisfaction.preprod.decathlon.com/vendor.bundle.js:54669:77)
    at http://satisfaction.preprod.decathlon.com/vendor.bundle.js:54553:23
    at Array.forEach (native)
    at http://satisfaction.preprod.decathlon.com/vendor.bundle.js:54550:48
    at Array.forEach (native)
    at JitCompiler._compileComponents (http://satisfaction.preprod.decathlon.com/vendor.bundle.js:54548:43)
    at createResult (http://satisfaction.preprod.decathlon.com/vendor.bundle.js:54462:19)
    at ZoneDelegate.invoke (http://satisfaction.preprod.decathlon.com/polyfills.bundle.js:8539:26)
    at Zone.run (http://satisfaction.preprod.decathlon.com/polyfills.bundle.js:8331:43)`

On a recent browser, it works like a charm.

## Please tell us about your environment

<pre><code>
Angular version: 2.3.1

Browser:
- [ x] Chrome (desktop) version 38
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Platform: Any

Others:

</code></pre>

**Comment by IgorMinar** [comment] 2017-07-11 16:44
Sounds like you need a polyfill. You can set your debugger to break on the exception and then figure out what polyfill is needed and add it to your app. This is not a problem caused by Angular, so I'm going to close this issue.

**Closed by IgorMinar** 2017-07-11 16:44 UTC
