### ISSUE TITLE
(forms) Add types for "OnChangeCallback" and "OnTouchedCallback"

### ISSUE THREAD

**Issue by dherges** [angular/angular#19329] opened 2017-09-22 08:40 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

```ts
export interface ControlValueAccessor {
  registerOnChange(fn: any): void;
  registerOnTouched(fn: any): void;
}
```

## Expected behavior

```ts
export type OnChangeCallback<T> = (_: T) => void;
export type OnTouchedCallback = () => void;

export interface ControlValueAccessor<T> {
  writeValue(obj: T): void;
  registerOnChange(fn: OnChangeCallback<T>): void;
  registerOnTouched(fn: OnTouchedCallback): void;
}
```

## Minimal reproduction of the problem with instructions

see above

## What is the motivation / use case for changing the behavior?

Syntax sugar.

Provide type assistance when implementing custom `ControlValueAccessor`

Explicit declaration of the type / data structure of the `ControlValueAccessor`.

Example:

`class DatePickerComponent implements ControlValueAccessor<Date>`

`class PasswordComponent implements ControlValueAccessor<string>`

`class IdentityCardComponent implements ControlValueAccessor<{ id: string, issuedSince: Date }>`

Full usage example:

```ts
@Component({
    selector: 'my-password',
    template: `<input type="password" (change)="eventBindingToInputField($event.target.value)">`,
    styleUrls: [],
    changeDetection: ChangeDetectionStrategy.OnPush,
    providers: [
        {
            provide: NG_VALUE_ACCESSOR,
            useExisting: forwardRef(() => PasswordComponent ),
            multi: true
        }
    ]
})
class PasswordComponent implements ControlValueAccessor<string> {

  _value: string = '';
  onChanged: OnChangeCallback<string>;
  onTouched: OnTouchedCallback;

  writeValue(obj: string): void {
    this._value = obj;
  }

  registerOnChange(fn: OnChangeCallback<string>): void {
    this.onChanged = fn;
  }

  registerOnTouched(fn: OnTouchedCallback): void {
    this.onTouched = fn;
  }

  eventBindingToInputField(value: string) {
    this._value = value;
    this.onChanged(value);
  }

}
```

## Environment

<pre><code>
Angular version: 5.x.y
</code></pre>

**Comment by dherges** [comment] 2017-09-22 09:16
#### "... implements ControlValueAccessor<string>"

![typed-control-value-accessor](https://user-images.githubusercontent.com/901354/30737425-d926ac44-9f86-11e7-9c53-6a0ec02a53e3.gif)


#### "this.onChange();"

![typed-control-value-accesor2](https://user-images.githubusercontent.com/901354/30737517-38c57f22-9f87-11e7-87fa-1b4c6ad6e3ce.gif)

**Comment by Toxicable** [comment] 2017-09-22 20:23
This will come after https://github.com/angular/angular/issues/13721

**Comment by jelbourn** [comment] 2020-10-12 22:12
Duplicate of #13721

**Closed by jelbourn** 2020-10-12 22:12 UTC
Labels: comp: forms, cross-cutting: types, feature, freq2: medium
