### ISSUE TITLE
Failed to compile entry-point @angular/platform-browser due to compilation errors

### ISSUE THREAD

**Issue by splincode** [angular/angular#34411] opened 2019-12-14 18:02 UTC
# 🐞 bug report

### Affected Package

The issue is caused by NGCC

![image](https://user-images.githubusercontent.com/12021443/70852612-7b4fdf00-1eb4-11ea-8df6-8b0d6aed07aa.png)

### Description

If use `ngcc --async false` then no problem

Related: https://github.com/angular/angular/issues/34191, https://github.com/angular/angular/pull/34254

## 🔬 Minimal Reproduction

```
$ git clone https://github.com/ngxs/store
$ yarn install
$ cd integrations/ivy
$ npx ngcc
```

## 🌍  Your Environment

**Angular Version:**

Angular 9-rc.6

**Comment by JoostK** [comment] 2019-12-15 00:29
Thanks for reporting, @splincode!

I have found the root cause of this issue, it is indeed due to parallelization. It's because there's a filesystem cache involved that does not see file writes from other workers.

**Comment by petebacondarwin** [comment] 2019-12-19 14:44
Should be fixed by https://github.com/angular/angular/pull/34494

**Closed** 2020-01-07 18:35 UTC
Labels: comp: ngcc
