### ISSUE TITLE
RC 3. Router. Browser Back doesn't work on iOS

### ISSUE THREAD

**Issue by kamarouski** [angular/angular#9565] opened 2016-06-24 07:52 UTC
iOS Safari and Chrome back button doesn't work correctly with the new router.

It looks like ngOnInit is not called when using back button.

Steps to reproduce:
- load some data during ngOnInit
- go to another route
- click browser back button

Result: data is not loaded.

Exprected result: ngOnInit is called and data is loaded

Environment: Angular2 RC3, latest iOS, Safari & Chrome

**Comment by DanielMcAssey** [comment] 2016-06-24 08:16
What Router version?

**Comment by kamarouski** [comment] 2016-06-24 08:19
alpha7

**Comment by MartinMa** [comment] 2016-06-24 08:24
Chrome works for me.

But for Safari and IE this is still a problem. The old router has the same issue. See #7722.

It can be reproduced with the official Tour of Heroes Demo.

**Comment by robwormald** [comment] 2016-06-25 02:19
this appears to be zone related (!?) 

repro: https://plnkr.co/edit/JpLOPMrtpq4ZnhlNCExC?p=preview  - works fine on Chrome / FF, Safari logs <root> for the current Zone.

**Comment by kamarouski** [comment] 2016-06-25 04:52
@robwormald It works fine on desktop. The issue is only with mobile browsers.

**Comment by MartinMa** [comment] 2016-06-27 08:05
@vsavkin Hi, what do you think is the problem here? Don't you think this issue stems from the router code (I guess so, because you removed your assignment).

But what is the problem then? Has it something to do with the browser implementation of the History API in the affected browsers? Can this (or is it expected to) be fixed with a pollyfill? Should this issue be referenced on the zone.js project?

**Comment by sicaner** [comment] 2016-07-01 07:02
add following code in your root component
```typescript
constructor(private _applicationRef: ApplicationRef, private _router: Router) {
		if(this.isMac()) {
			_router.events.subscribe(ev => {
				if(ev instanceof NavigationEnd) {
					setTimeout(() => {
						_applicationRef.zone.run(() => _applicationRef.tick())
					}, 500)
				}
			})
		}
		
	}

	isMac() {
		if(navigator.userAgent.indexOf('Mac') > -1) {
			return true
		}
		return false
	}
```

**Comment by kamarouski** [comment] 2016-07-05 02:06
thanks @sicaner. This workaround works.

It'd be good to have it as part of router.

**Closed** 2016-07-15 22:30 UTC
Labels: comp: router, type: bug

**Comment by kpturner** [comment] 2017-01-19 12:16
It is good to see a typescript workaround, but what about a workaround for those of us not using TypeScript. I have a simple Angular v1.4.1 JavaScript based node application that needs the same issue fixed.
