### ISSUE TITLE
Angular 16 @HostListener('window:beforeunload', ['$event']) is not working

### ISSUE THREAD

**Issue by oleh-kazban-gl** [angular/angular#52256] opened 2023-10-18 11:58 UTC
### Which @angular/* package(s) are the source of the bug?

Zone.js

### Is this a regression?

No

### Description

After migration from 15.2.10 to 16.2.* (tried 16.2.3 and 16.2.9) the working approach with showing the default browser preventing reload popup is not working any more.
![image](https://github.com/angular/angular/assets/12762343/9f19298b-538c-4a39-bc7c-42a7ba62c366)

Working minimalistic solution (Angular 15) https://stackblitz.com/edit/angular-15-starter-pack-iuvmnk
The same solution with Angular 16 (not working) https://stackblitz.com/edit/stackblitz-starters-qhmmsm

### Step to reproduce
-  open https://stackblitz.com/edit/stackblitz-starters-qhmmsm with Chromium based browser (Chrome/Edge)
- wait until the app is built
- open console
- click between the header and the link (you will see 'Changed!' output in the console)
- try to reload the page (either the embedded in stackblitz or the browser page - it doesn't matter, should work the same in both cases)

ER: the default browser preventing reload popup should appear
AR: the default browser preventing reload popup doesn't appear

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-qhmmsm

### Please provide the exception or error you saw

```true
The browser doesn't show the default preventing reload popup.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
@angular/core@16.2.9
@angular/common@16.2.9
@angular/animations@16.2.9
@angular/compiler@16.2.9
@angular/forms@16.2.9
@angular/platform-browser@16.2.9
@angular/platform-browser-dynamic@16.2.9

Chrome 118.0.5993.89 64-bit / Chrome 118.0.5993.71 64-bit / Chrome 117.0.5938.132 64-bit / Edge 117.0.2045.60 64-bit
```

### Anything else?

As you can see from the component code if I click on the layout and change it to the changed state I shoud see the default browser popup asking "Reload the site?", but in Chrome 118.0.5993.89 64-bit / Chrome 118.0.5993.71 64-bit / Chrome 117.0.5938.132 64-bit / Edge 117.0.2045.60 64-bit it doesn't appear (meanwhile it works in Firefox 118.0.2 64-bit or 15.2.10 version), Win 10.
One more mention about the same problem here: https://github.com/angular/angular/issues/50935

**Comment by JoostK** [comment] 2023-10-18 21:12
I haven't tested it (the Stackblitz links don't reproduce for me, or at least I don't know what to do in that repro to reproduce it) but this might potentially be due to zone.js changes; you could try downgrading that and see if it makes a change.

**Comment by JeanMeche** [comment] 2023-10-18 21:25
On Chrome 118 I can't reproduce your issue.  If I click (logged) + try to reload the page I do get that modal.

**Comment by oleh-kazban-gl** [comment] 2023-10-19 07:47
> I haven't tested it (the Stackblitz links don't reproduce for me, or at least I don't know what to do in that repro to reproduce it) but this might potentially be due to zone.js changes; you could try downgrading that and see if it makes a change.

Will try, thanks

**Comment by oleh-kazban-gl** [comment] 2023-10-19 07:49
> On Chrome 118 I can't reproduce your issue. If I click (logged) + try to reload the page I do get that modal.

Strange situation, because none of my collegues are able to use this feature anymore. And moreover - there was the same issue before https://github.com/angular/angular/issues/50935

**Comment by oleh-kazban-gl** [comment] 2023-10-19 08:01
> I haven't tested it (the Stackblitz links don't reproduce for me, or at least I don't know what to do in that repro to reproduce it) but this might potentially be due to zone.js changes; you could try downgrading that and see if it makes a change.

Tried to downgrade zone.js to 0.11.8 - no luck, I don't see the default preventing reload browser popup - page just reloads and thats all.

**Comment by pkozlowski-opensource** [comment] 2023-10-19 08:45
@oleh-kazban-gl you might have browser extensions installed that interfere. Try disable extensions / test in the incognito mode.

**Comment by oleh-kazban-gl** [comment] 2023-10-19 09:09
> @oleh-kazban-gl you might have browser extensions installed that interfere. Try disable extensions / test in the incognito mode.

I have disabled all extension, tried in incognito mode - the same result
![image](https://github.com/angular/angular/assets/12762343/c427f4fb-69d7-47be-911a-96c9de132576) (incognito)
![image](https://github.com/angular/angular/assets/12762343/e2be671a-e100-4066-b1ad-2d178f7ebc02) (usual)

As I can see that @HostListener works (there is the output in the console) but without browser popup.

**Comment by JoostK** [comment] 2023-10-29 16:57
This looks like a duplicate of #47579

**Comment by Choupa-web** [comment] 2023-10-31 07:34
I have the same issue:

     "@angular/animations": "16.2.11",
    "@angular/cdk": "16.2.10",
    "@angular/common": "16.2.11",
    "@angular/compiler": "16.2.11",
    "@angular/core": "16.2.11",
    "@angular/flex-layout": "15.0.0-beta.42",
    "@angular/forms": "16.2.11",
    "@angular/material": "16.2.10",
    "@angular/platform-browser": "16.2.11",
    "@angular/platform-browser-dynamic": "16.2.11",

`Chrome : Version 118.0.5993.88 (Build officiel) (64 bits)`

**Comment by oleh-kazban-gl** [comment] 2023-12-01 12:06
Seems is fixed in 17th version

**Comment by aparzi** [comment] 2024-01-24 16:22
Hi I have same problem in Angular 16. This code is not printed in Angular 16, but in Angular 15 it is. Are there currently fixes in progress, otherwise could I try to solve the problem? But I could use some help, thanks.

```
@HostListener('window:unload', ['$event'])
    beforeunload($event) {
    console.log("clear session");
}
```

**Comment by aparzi** [comment] 2024-01-24 16:34
Thanks, for Angular 16 for angular 16 is it not possible to do this? like with a patch?

**Comment by oleh-kazban-gl** [comment] 2024-01-24 16:40
> Thanks, for Angular 16 for angular 16 is it not possible to do this? like with a patch?

As I know there is some fix (you have already commented there), but the core team hasn't reacted so far :(

**Comment by iannonoss** [comment] 2024-01-24 16:40
Given the need, my temporary solution was this: 

`ngOnInit(): void {
        this.subscriptions?.push(sb);
        window.addEventListener('beforeunload', this.beforeUnloadHandler);
        this.cdr.detectChanges();
    }

    ngOnDestroy() {
        window.removeEventListener('beforeunload', this.beforeUnloadHandler);
    }

private beforeUnloadHandler(e) {
        const confirmationMessage = '\o/';
        console.log('cond');
        e.returnValue = confirmationMessage;
        return confirmationMessage;
    }`
I hope it can help you. :)

**Comment by testpushhydra** [comment] 2024-02-15 03:36
I see the interface, but I don't even find the directive in the compiled Angular code in 16.2.  No wonder Google is losing market share to React with these boneheaded mistakes

**Closed** 2024-10-04 17:55 UTC
Labels: area: core, core: host and host bindings
