### ISSUE TITLE
Unable to use Angular DevTools for inspecting components

### ISSUE THREAD

**Issue by Vbuddies** [angular/angular#52933] opened 2023-11-15 14:29 UTC
### Is this a bug report or a feature request?

- [X] Bug Report
- [ ] Feature Request

### Please provide the steps to reproduce the issue [Bug Report only]

Browser: Firefox
Angular v16.2.8
Angular DevTools v16.2.9

Noticed this started happening after the DevTools extension was updated, right around the time when v17 of angular came out.

Open the devTools, and you should see that although the components are loaded on the left in the components tab, the element inspection area is completely empty and says, "No Selected Element"
No matter which elements/components are selected I am unable to inspect them.

Navigation back to the console shows an error.

### Please provide the expected behavior vs the actual behavior you encountered [Bug Report only]

Expected behavior:
To be able to open and view the components and their related information including current input and variable values.

Actual Behavior:
While I am able to see the components in the component tree, I am unable to inspect any of the components, whether they are custom components or angular components.

### Please provide a screenshot if possible [Bug Report only]

![image](https://github.com/angular/angular/assets/47540778/f815f86d-32bd-4399-8d2c-89a6060985c8)
![image](https://github.com/angular/angular/assets/47540778/1b9e6e15-c4ba-4d17-9ee1-ed904c6b37bd)

### Please provide the exception or error you saw [Bug Report only]

```true
Uncaught TypeError: F().\u0275getInjectorMetadata is not a function
    rt component-tree.ts:61
    Jo component-tree.ts:436
    De component-tree.ts:234
    i component-tree.ts:105
    nn component-tree.ts:104
    bi client-event-subscribers.ts:102
    n same-page-message-bus.ts:41
    invokeTask zone.umd.js:445
    runTask zone.umd.js:210
    invokeTask zone.umd.js:527
    invokeTask zone.umd.js:1705
    globalCallback zone.umd.js:1748
    globalZoneAwareCallback zone.umd.js:1772
    customScheduleGlobal zone.umd.js:1856
    scheduleTask zone.umd.js:432
    scheduleTask zone.umd.js:253
    scheduleEventTask zone.umd.js:279
    makeAddListener zone.umd.js:2013
    on same-page-message-bus.ts:44
    <anonymous> backend.ts:20
    <anonymous> backend.ts:44
7 component-tree.ts:61:19
```

### Is this a browser-specific issue? If so, please specify the device, browser, and version. [Bug Report only]

```true
Received same issue from both Firefox and Edge.
```

**Comment by AleksanderBodurri** [comment] 2023-11-15 16:52
Duplicate of https://github.com/angular/angular/issues/52786. Will be resolved after the DevTools release today 🙏

**Comment by AleksanderBodurri** [comment] 2023-11-20 23:09
This should be resolved https://github.com/angular/angular/pull/52791. Let me know if you still have any issues

**Closed by AleksanderBodurri** 2023-11-20 23:09 UTC
Labels: area: devtools
