### ISSUE TITLE
Server side not rendering only half of the data

### ISSUE THREAD

**Issue by maphi88** [angular/angular#17840] opened 2017-06-29 13:17 UTC
My package.json is

<details>
{
  "name": "maphisha",
  "version": "0.0.0",
  "license": "MIT",
  "angular-cli": {},
  "scripts": {
    "start": "ung serve",
    "lint": "tslint \"src/**/*.ts\"",
    "test": "ung test",
    "pree2e": "webdriver-manager update --standalone false --gecko false",
    "e2e": "protractor"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "2.2.3",
    "@angular/compiler": "2.2.3",
    "@angular/core": "2.2.3",
    "@angular/forms": "2.2.3",
    "@angular/http": "2.2.3",
    "@angular/platform-browser": "2.2.3",
    "@angular/platform-browser-dynamic": "2.2.3",
    "@angular/platform-server": "2.2.3",
    "@angular/router": "3.2.3",
    "@angularclass/idle-preload": "^1.0.4",
    "@ngui/datetime-picker": "^0.16.2",
    "@types/chart.js": "^2.4.4",
    "@types/chartjs": "0.0.29",
    "angular-2-local-storage": "^1.0.1",
    "angular2-cookie": "^1.2.6",
    "angular2-express-engine": "2.1.0-rc.1",
    "angular2-image-gallery": "^1.0.1",
    "angular2-platform-node": "2.1.0-rc.1",
    "angular2-tinymce": "^2.1.2",
    "angular2-universal": "2.1.0-rc.1",
    "angular2-universal-polyfills": "2.1.0-rc.1",
    "chart-library": "^1.1.0",
    "chart.js": "^2.6.0",
    "compression": "1.6.2",
    "core-js": "^2.4.1",
    "d3-ng2-service": "^1.15.0",
    "express": "^4.14.0",
    "ng-lazyload-image": "^3.1.1",
    "ng2-charts": "^1.6.0",
    "ng2-filter-pipe": "^0.1.10",
    "ng2-flatpickr": "^0.1.14",
    "ng2-img-cropper": "^0.8.8",
    "rxjs": "5.0.0-beta.12",
    "ts-helpers": "^1.1.1",
    "ts-md5": "^1.2.0",
    "zone.js": "^0.6.25"
  },
  "devDependencies": {
    "@angular/compiler-cli": "2.2.3",
    "@types/body-parser": "0.0.29",
    "@types/compression": "0.0.29",
    "@types/cookie-parser": "^1.3.29",
    "@types/express": "^4.0.29",
    "@types/express-serve-static-core": "^4.0.29",
    "@types/jasmine": "2.5.38",
    "@types/mime": "0.0.28",
    "@types/node": "^6.0.78",
    "@types/serve-static": "^1.7.27",
    "angular-router-loader": "^0.6.0",
    "codelyzer": "~2.0.0-beta.1",
    "jasmine-core": "2.5.2",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "1.2.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-remap-istanbul": "^0.2.1",
    "protractor": "~4.0.13",
    "ts-loader": "^2.1.0",
    "ts-node": "1.2.1",
    "tslint": "^4.0.2",
    "typescript": "~2.0.3",
    "universal-cli": "1.0.0-alpha.universal.3"
  }
}
</details>

I have a component 

<details>
import { Component, OnInit, Renderer, NgZone, ViewChild, ViewEncapsulation, ChangeDetectorRef,Input } from '@angular/core';
import {Router, ActivatedRoute, Params} from '@angular/router';
import { environment } from '../../../environments/environment';
import { WindowRef } from '../../additional/WindowRef';
import { ArticleComponent } from './article.component';
import { MetaComponent } from './../common/meta.component';
import { StorageService } from './../storage.service';
import { ApiService } from './../api.service';
declare var $:any;
declare var sliderHome:any;
declare var ga:any;

@Component({
  encapsulation:ViewEncapsulation.None, 
  providers:[ApiService],
  selector: 'mc4k-all-article',
  templateUrl: '../../views/viewDesktop/body/article.html',
  styleUrls: ['../../css/common.css','../../css/reset.css','../../css/article-detail.css','../../css/coach-marks.css'],
})
export class ArticlesComponent implements OnInit {
  @ViewChild(MetaComponent) private metaComp: MetaComponent;
  @ViewChild(ArticleComponent) private articleComp:ArticleComponent;
 articleArr:any;any;
constructor(private _storage:StorageService,private ApiService:ApiService,private zone:NgZone,private router:Router,private activatedRoute:ActivatedRoute,private winRef:WindowRef, private renderer:Renderer, private ref:ChangeDetectorRef) {
   this.articleComp.getSlug();
  this.metaComp.setMetaData()
}
updateArticleParent(arr){
  this. articleArr = arr;
}
}
</details>

Child Component

<details>
import { Component, OnInit, Renderer, ViewChild, ViewEncapsulation, Output, EventEmitter } from '@angular/core';
import {Router, ActivatedRoute, Params} from '@angular/router';
import { ApiService } from './../api.service';
import { environment } from '../../../environments/environment';
import { StorageService } from './../storage.service';
import { WindowRef } from '../../additional/WindowRef';
import { CommentComponent } from '../comment/comment.component';
import { ArticleListComponent } from './article-list.component';
declare var $:any;
declare var getarticleStyle:any;
declare var coach:any;
import { MetaComponent } from './../common/meta.component';
import { AdComponent } from './../common/ad.component';
@Component({
  selector: 'mc4k-article',
  template: '<app-ad></app-ad><mc4k-meta></mc4k-meta><mc4k-user-article (articleListings)="articleListingsParent($event)"></mc4k-user-article><mc4k-comment (articleComments)="articleCommentsParent($event)"></mc4k-comment>',
  providers:[ApiService],
})
export class ArticleComponent implements OnInit {
  @ViewChild(MetaComponent) private metaComp: MetaComponent;

getSlug(){
   //get data
callfunc();
cutomise();
this.articleArr['dasdsa'] = 'dsadsad';
this.updateArticle.emit(this.articleArr);
}
callfunc(){
//do something
this.articleArr['abc'] = 'abc';
this.updateArticle.emit(this.articleArr);

cutomise(){
//do something
this.updateArticle.emit(this.articleArr);
}
}

declare var ga:any;
declare var gaScript:any;
declare var userPrint:any;
import { Component, OnInit , ViewEncapsulation } from '@angular/core';
import { environment } from './../../../environments/environment';
import { Meta,MetaDefinition } from './../meta.service'; --->>angular2-meta code

import { Router, ActivatedRoute, NavigationEnd } from '@angular/router';
@Component({
  encapsulation:ViewEncapsulation.None,
  styles: [],
  template: ``,
  providers:[Meta],
  selector: 'mc4k-meta',
})

export class MetaComponent implements OnInit {
metaTags : any; type:string;title:string;description:string;keyword:string;image:string;environment:any;

    constructor(private activeRoute:ActivatedRoute, private meta:Meta) {
       this.description = "ddsa";
        this.environment = environment;
        this.environment.random.pageName = this.activeRoute.snapshot.data['name'];
        this.environment.random.screenName = this.activeRoute.snapshot.data['name']+' '+this.activeRoute.snapshot.data['type'];
        this.image = 'https://abcd.png';
        this.title = "ddsa";
        this.keyword ="ddsa";
        
    }
    ngOnInit() {}

    setMetaData(val){
        let description = val['metaDescription']?val['metaDescription']:this.description;
        let desc1: MetaDefinition = { name: 'og:description', content: description };
        let desc2: MetaDefinition = { name: 'twitter:description', content: description };
        let desc: MetaDefinition = { name: 'description', content: description };
        
        let img = val['image']?val['image']:this.image;
        let img1: MetaDefinition = { name: 'twitter:image', content: img };
        let img2: MetaDefinition = { name: 'og:image', content: img };
        // let keyword = val['metaKeyWord']?val['metaKeyWord']:this.keyword;
        let titl = val['metaTitle']?val['metaTitle']:this.title;
        let title = val['pageTitle']?val['pageTitle']:this.title;
        let title1: MetaDefinition = { name: 'twitter:title', content: titl };
        let title2: MetaDefinition = { name: 'og:title', content: titl };
        let type = val['type']?val['type']:this.type;
        let type1: MetaDefinition = { name: 'og:type', content: type };
        this.meta.addTags([desc, desc1, desc2,img1,img2,title1,title2,type1]);
        this.meta.setTitle(title);
        let url = $(document).baseURL;
    }

    callGA(dimesions){
      let url = $(document).baseURL;
      let userId = this.environment.userInfo.id?this.environment.userInfo.id:'userP-'+userPrint;  
      if(!this.environment.random.gaFirstCall){
        gaScript('userId',dimesions);
        this.environment.random.gaFirstCall = true;
      }else{
         this.customGA(dimesions,'');
      }
      
    }

    customGA(dimesions,url){
      let userId = this.environment.userInfo.id?this.environment.userInfo.id:'userP-'+userPrint;  
      for(var i in dimesions){
        ga(i,dimesions[i]);
      }
      ga("set", "location", url);
      ga('set', 'userId', userId);
      ga('send', 'pageview',url);

    }
}
</details>

If I call any function in MetaComponent the the whole server side rendering on router-outlet stop

If I call only ArticleComponent function then only half of the data is being render on view source

Note: edited by vicb to hide un-relevant info.

**Comment by julienR2** [comment] 2017-06-29 15:47
Please take advantage of the markdown styling to make your request clearer.. code without code tag is simply unreadable.

Can you provide the error on the server ?

**Comment by julienR2** [comment] 2017-06-29 15:47
and also duplicate of #17837

**Comment by maphi88** [comment] 2017-06-29 15:54
There is no error just that on view source <router-outlet></router-outlet> is empty

**Comment by maphi88** [comment] 2017-06-30 11:17
I can't see ssr on my local but on production router outlet is empty.

**Comment by maphi88** [comment] 2017-06-30 11:39
Sorry I mean I can see ssr on my local happening but fails on production

**Comment by vicb** [comment] 2017-07-01 02:11
Please attach a small repro otherwise there is nothing we can do

**Comment by IgorMinar** [comment] 2017-07-11 00:33
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Closed by IgorMinar** 2017-07-11 00:33 UTC
Labels: flag: can be closed?
