### ISSUE TITLE
Try out Inject link navigates to 404

### ISSUE THREAD

**Issue by mikimaine** [angular/angular#52555] opened 2023-11-06 23:23 UTC
### Describe the problem that you experienced

When clicking  Try out Inject it 404's

### Enter the URL of the topic with the problem

https://angular.dev/roadmap

**Comment by atscott** [comment] 2023-11-07 01:28
Duplicate of https://github.com/angular/angular/issues/52539

**Closed by atscott** 2023-11-07 01:28 UTC
