### ISSUE TITLE
Angular 12 regression: Error: inject() must be called from an injection context

### ISSUE THREAD

**Issue by thomaspeugeot** [angular/angular#42710] opened 2021-06-30 07:17 UTC
# Bug Report

### Affected Package

The issue is caused by package @angular/core

### Is this a regression?

Yes, the previous version in which this bug was not present was version 11

### Description

The client fails starting the application

```
ERROR Error: inject() must be called from an injection context
    Angular 3
    SvgComponent_Factory svg.component.ts:11
```

## Minimal Reproduction

Problem arises when the gonggant stack import the gongsvg stack

~~Nota : go is required to compile/run the back end (version 1.16 minimum, because it uses `embed` to run the server)~~

- in a directory X, create the gongsvg stack
  - checkout repo gongsvg `git clone https://github.com/fullstack-lang/gongsvg.git`
  - checkout on branch `issue_ng12_inject`
  - in `gongsvg/ng`, `npm i`

- in the same directory X, create the gonggant stack  
  - checkout repo gongsvg `git clone https://github.com/fullstack-lang/gonggantt.git`
  -  checkout on branch `issue_ng12_inject`
  - in `gonggantt/ng`, `npm i` then `ng build`

- run the server of the second stack
  - in `gonggantt`, ~~`go run main.go`~~, `ng serve`
  - launch the client on ~~localhost:8080~~ localhost:4200

## Exception or Error

<pre><code>
ERROR Error: inject() must be called from an injection context
</code></pre>

## Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 11.2.7
Node: 12.22.1
OS: darwin x64

Angular: 
... 
Ivy Workspace: 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1102.7 (cli-only)
@angular-devkit/core         11.2.7 (cli-only)
@angular-devkit/schematics   11.2.7 (cli-only)
@schematics/angular          11.2.7 (cli-only)
@schematics/update           0.1102.7 (cli-only)

</code></pre>

**Anything else relevant?**
Issue occurs with  FX & Chrome
Issue occurs with macos and windows

**Comment by JoostK** [comment] 2021-06-30 08:56
I'm afraid we can't process a full repo which requires a backend, could you please extract a _minimum_ reproduction.

**Comment by thomaspeugeot** [comment] 2021-06-30 11:50
> 
> 
> I'm afraid we can't process a full repo with lots of components which requires a backend, could you please extract a _minimum_ reproduction.

Two points
1/ My initial investigation of the issue was to slim down the context it down to a *minimum* context (even without a backend).

I developped a repo with a much simpler setting (https://github.com/fullstack-lang/injectissue) with the intention of slimming it down further. Unfortunatly, The bug was not reproduced in this slimmed down version. 

2/ *gongsvg* and *gonggant* are two *gong* repos where 99% of the code is generated by a *gongc* compiler (https://github.com/fullstack-lang/gong). The bug context can be set up in 5 commands that take 5 minutes in all (if go 1.16 is installed). The exception is then easily caught by the debugger.

**Comment by thomaspeugeot** [comment] 2021-07-01 06:12
The post have been edited. go is not necessary, `ng serve`is enough

**Comment by JoostK** [comment] 2021-07-01 09:45
Thank your for narrowing it down. I haven't run the repro yet, but I can see from your path mapping setup that you're referencing the gongsvg library in its own workspace directory. Without `preserveSymlinks: true`  this causes the `node_modules` directory of that secondary workspace to be mixed into your build, resulting in multiple copies of `@angular/core` which confuses the runtime as state from one copy is not available to the other.

I haven't looked into why/how this worked for you in v11. This particular setup has always been prone to errors like this.

**Comment by thomaspeugeot** [comment] 2021-07-02 06:47
Thank you for your answer.

> Without `preserveSymlinks: true` this causes the `node_modules` directory of that secondary workspace to be mixed into your build, resulting in multiple copies of `@angular/core` which confuses the runtime as state from one copy is not available to the other.

1. When I put this option (and I tried before if I am not mistaken), *I still have the same error* (see branch `slimmed_down_version_with_preserve_symlink`, perhaps did I not set up the option at the right place in the right file ?)

1. Just for my information, where can I see that there are 2 `@angular/core` modules in the directory tree ? How can I check that ?

1. I noticed the `ng build` command is faster now.

**Comment by JoostK** [comment] 2021-07-03 17:14
This seems to be working as expected with this particular setup. `preserveSymlinks` doesn't have an effect as there are no symlinks in this case, which I missed previously.

There is [a note on angular.io](https://angular.io/guide/creating-libraries#use-typescript-path-mapping-for-peer-dependencies) that suggests to use a path mapping for `@angular/*`. That does work in your reproduction but may not be sufficient for other packages and you may still end up with duplicate dependencies, increasing your bundle size (and possibly resulting in other runtime incompatibilities).

This behavior is not new in v12, it's how Node module resolution works. If you can adjust your reproduction to work with v11 then I'm happy to take a look at it once more, but for now I'm closing this as working as expected.

**Closed by JoostK** 2021-07-03 17:14 UTC
Labels: comp: core, core: di, needs reproduction

**Comment by thomaspeugeot** [comment] 2021-07-04 09:18
Hi @JoostK ,

thks for the answer.

1. it is good suggestion, when I added the path mapping, see branch `typescript_path`, w/o `"preserveSymlinks": true,`, *the error is not there anymore*.
2. There is still the question of *why it worked in v11?* but I understand we were in uncharted territories. As said in the note: 
> If a library lists @angular/core in dependencies instead of peerDependencies, it might get a different Angular module instead, which would cause your application to break.`
3. In my humble opinion, Angular is about developping reusable components. Therefore, it is about importing existing angular libraries. Then, I do not understand why the

**Comment by JoostK** [comment] 2021-07-04 09:39
> Then, I do not understand why the below configuration is not (by default) in the generated tsconfig.json file when using ng generate <project>?

That path mapping will only help avoid multiple copies of `@angular/*` packages, not any other third-party packages that end up being resolved from the other workspace.

Angular libraries are not special in this regard. They follow Node module resolution and NPM dependency rules, just like any JS library. The reference into a different workspace causes that workspace's dependencies to be included in the build; not doing so would have its own set of problem when a dependency is only available in the linked workspace.

In your case, I'd recommend to reference the packages in the other workspace using symlinks, together with `"preserveSymlinks": true` in `angular.json`. That may show problems with ngcc, in which case you may want to switch the libraries over to Ivy partial compilation that is available since v12 to avoid the need for ngcc.

**Comment by JoostK** [comment] 2021-07-04 09:39
Alternatively, a true monorepo would also get you a long way of avoiding issues like these.
