### ISSUE TITLE
Component lifecycle hooks not firing if detectChanges called by other component

### ISSUE THREAD

**Issue by trevorade** [angular/angular#20394] opened 2017-11-13 14:50 UTC
## I'm submitting a...

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [X] Bug report  
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

## Current behavior

If two components displayed at the same time (the first existing, the second being added to the page) and code run during the second component's `ngOnChanges` results in the first component calling `ChangeDetectorRef.detectChanges`, the second component will not receive `ngOnInit`, `ngAfterContentInit`, nor `ngAfterViewInit`.

## Expected behavior

Even if the first component calls `detectChanges`, the second component should continue to receive lifecycle hooks.

## Minimal reproduction of the problem with instructions

Please see repro and steps here: http://plnkr.co/edit/N9k8TTvKOUpDEVul03pK?p=preview

This is probably not as minimal as it could be.  I boiled down a larger example I was working on.

## What is the motivation / use case for changing the behavior?

This is just an undesirable bug.  This particular repro is slightly convoluted (though I'm actively working on a larger version of this for use with configuring a single application toolbar).  In general, I believe this sort of issue could arise in many more instances.

## Environment

Angular version: 2.5.1

Browser:
- [X] Chrome (desktop) version 62
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by kara** [comment] 2020-05-27 00:31
Sorry for the long wait. When I ported this issue to Stackblitz with Angular 9.x, I can no longer reproduce the issue:

https://stackblitz.com/edit/angular-ivy-nezcpa?file=src%2Fapp%2Fapp.component.ts

It looks like this was fixed in one of the intervening versions, since it's fixed in both Ivy and VE. Closing as fixed.

**Closed by kara** 2020-05-27 00:31 UTC
Labels: comp: core, core: change detection, core: lifecycle hooks, freq1: low, severity3: broken, triage #1, type: bug/fix
