### ISSUE TITLE
NgZone: Emit onError event outside the zone

### ISSUE THREAD

**Issue by vikerman** [angular/angular#7774] opened 2016-03-25 20:24 UTC
Currently we emit the onError event from NgZone within the zone itself.

This causes a problem when there is an exception in the error handler itself and that exceptions tries to trigger the onError event again. In Dart this would result in an unhelpful exception message like 

"Caught Bad state: Cannot fire new event. Controller is already firing an event"

instead of surfacing the exception in the error handler.

The fix is to just emit the onError even outside of the NgZone.

**Comment by bryanrideshark** [comment] 2017-08-22 21:34
To confirm, should this be closed? Seems that it was intended to be closed by #18269, but this is still open.

**Comment by tytskyi** [comment] 2017-12-07 13:40
This can be closed, angular runs handler outside zone `4.3.2`

**Comment by trotyl** [comment] 2017-12-07 13:46
@tytskyi Actually not, still remains some parts.

**Comment by JiaLiPassion** [comment] 2020-05-28 15:23
Now onError will be emitted outside ngZone, @trotyl, could you post more information about which parts are not fixed yet? thanks.

**Closed by JiaLiPassion** 2020-05-28 15:23 UTC
Labels: comp: core, comp: zones, core: error handling, effort2: days, freq2: medium, severity3: broken, type: bug/fix
