### ISSUE TITLE
The function parameter index and item in the 'TrackByFunction' interface be swapped. `index` is optional

### ISSUE THREAD

**Issue by jellyzhai** [angular/angular#48637] opened 2023-01-04 07:20 UTC
### Which @angular/* package(s) are relevant/related to the feature request?

common

### Description

```
interface TrackByFunction<T> {
  <U extends T>(index: number, item: T & U): any
}
```
In practical applications, the 'index' parameter is not commonly used, but also occupies the first parameter position, resulting in forced writing. 

### Proposed solution

It is recommended that the 'index' and 'item' parameters be interchanged and changed to optional parameters

### Alternatives considered

No

**Comment by pkozlowski-opensource** [comment] 2023-01-04 08:08
We are already tracking this in #48503. Duplicate of #48503

**Closed by pkozlowski-opensource** 2023-01-04 08:08 UTC
