### ISSUE TITLE
Component styles are ignored in IE9 after 31 style tags

### ISSUE THREAD

**Issue by kgurkan** [angular/angular#14970] opened 2017-03-06 22:03 UTC
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When the application grows a certain point and component styles could not be shared in the same `<style>` tag, Angular creates a new style tag to host CSS definitions and attaches that to document head. 

There is a [limitation](https://support.microsoft.com/en-us/help/262161/a-webpage-that-uses-css-styles-does-not-render-correctly-in-internet-explorer) in Internet Explorer 9 which prevents `<style>` tags after the first 31 are ignored by the browser. This limitation makes Angular applications "randomly" miss out the styles for components. I say random, because it seems style tags are created and appended to document head in component load order and user's navigation story throughout the app may have a significant effect on which styles will load and which ones will be ignored.

**Expected behavior**

Given the number of style tags allowed in Internet Explorer is very low, any sufficiently large application will hit this barrier very quickly. Because this limitation cannot be extended to a more reasonable limit, I think Angular should provide a way to put a hard limit on number of style tags to a level to keep support for this browser.

**Minimal reproduction of the problem with instructions**

An application under test should have enough components to have the framework create more than 31 stylesheets. See https://plnkr.co/JeJ9uT for an example plunkr. On IE9, styles for component-29 and later are not applied (one style tag is inlined in index.html and one is created for root component, leaving 29 slots for generated components).

**What is the motivation / use case for changing the behavior?**

Most obvious workaround for this problem is to move all component styles out of a separate CSS file and leave the `styles` and `styleUrls` properties blank for component metadata. But this removes the encapsulation feature of the framework. Even then, this may not be suitable for all application configurations especially when they depend on third party component libraries such as material2 or ng-bootstrap.

**Please tell us about your environment:**

Environment irrelevant.

* **Angular version:** 2.4.9

* **Browser:** [IE 9]

 
* **Language:** [all]

* **Node (for AoT issues):** `node --version` = NA

**Comment by DzmitryShylovich** [comment] 2017-03-06 22:06
There's already an issue for this https://github.com/angular/angular/issues/11682

**Comment by IgorMinar** [comment] 2017-03-13 21:30
Thanks for reporting this issue. However this issue is a duplicate of an existing issue #14970. Please subscribe to that issue for future updates.

**Closed** 2017-03-13 21:31 UTC
Labels: comp: core & compiler, type: bug
