### ISSUE TITLE
Interacting with @Inputs and @Outputs of dynamically loaded components

### ISSUE THREAD

**Issue by pkozlowski-opensource** [angular/angular#8164] opened 2016-04-21 09:46 UTC
As of today interacting with input and outputs of dynamically loaded components requires access to potentially "private" fields of a component. To illustrate it with a concrete example let's say that I want to load, using `DynamicComponentLoader`, a following component:

``` javascript
@Component({
    selector: 'my-modal-content'
    template: `...`
})
export class MyModalContent {
    @Output() close = new EventEmitter();    
    ..    
}
```

After loading, I would like to subscribe to the **close** event which sounds like an easy task:

``` javascript
dcl.loadIntoLocation(content, this._elRef, 'content').then((componentRef) => {
    componentRef.instance.close.subscribe((closeEvent) => {
        ...
    });
});
```

Unfortunately **this method requires me to use `EventEmmiter`’s instance name instead of event name**. Why this could be a problem? Well, nothing stops people from implementing `MyModalContent` like so:

``` javascript
@Component({
    selector: 'my-modal-content'
    template: `...`
})
export class MyModalContent {
    @Output('close') _close = new EventEmitter();    
    ..    
}
```

**In this case the contract is broken as the only thing I should be knowing of is event name.**. Instead I need to subscribe using a private field name (`_close`).

cc: @mhevery @adamdbradley as discussed yesterday

**Comment by DzmitryShylovich** [comment] 2017-02-05 21:15
@pkozlowski-opensource ok so what is the proposed solution? :)

**Comment by jcomputer** [comment] 2017-02-14 00:41
Would it be possible to modify ngComponentOutlet (or similar) to be extendable? Specifically, an extension would define all desired Inputs/Outputs, then any dynamic class assigned to it at runtime would be expected to extend that extended class so it can use the same Inputs/Outputs. Then Inputs/Outputs could be bound in the template as normal.

**Comment by kavi87** [comment] 2017-02-17 16:50
I think it would be useful for starter if a ComponentRef offer an api to its inputs/outputs, something like componentRef.instance.inputs['close'] which will call whatever decorated method or field of the component.

**Comment by vicb** [comment] 2017-04-06 17:07
duplicate of https://github.com/angular/angular/issues/15360

**Closed by vicb** 2017-04-06 17:07 UTC
Labels: comp: core & compiler, type: feature

**Comment by pkozlowski-opensource** [comment] 2017-04-06 17:10
@vicb I don't think it is a duplicate - #15360 is specific to ngComponentOutlet while this issue is about the ViewContainerRef and friends programmatic APIs.

**Comment by manuchadha1979** [comment] 2018-08-18 09:36
Is there an update on this issue? I have created a component dynamically and then am setting the Inputs using instance of the component. But that seem to give me error on console `ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'id: undefined'. Current value: 'id: errorDialog'. It seems like the view has been created after its parent and its children have been dirty checked. Has it been created in a change detection hook ?`

**Comment by dima716** [comment] 2018-09-06 13:40
@manuchadha1979 Try to use ```ngAfterContentInit``` instead of ```ngAfterViewInit```
