### ISSUE TITLE
Projected content inside an Angular element appears in the incorrect place

### ISSUE THREAD

**Issue by HazzMan2409** [angular/angular#47994] opened 2022-11-08 18:23 UTC
### Which @angular/* package(s) are the source of the bug?

core, elements

### Is this a regression?

No

### Description

In a spec, when we project content inside of an Angular element it appears in the incorrect place in the DOM.

### Please provide a link to a minimal reproduction of the bug

https://github.com/HazzMan2409/ng-content-issue

### Please provide the exception or error you saw

```true
The content is projected but appended to the Angular element instead of appearing where the <ng-content> is.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 14.2.8
Node: 14.17.4
Package Manager: npm 6.14.14 
OS: darwin x64

Angular: 14.2.9
... animations, common, compiler, compiler-cli, core, elements
... forms, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1402.8
@angular-devkit/build-angular   14.2.8
@angular-devkit/core            14.2.8
@angular-devkit/schematics      14.2.8
@angular/cli                    14.2.8
@schematics/angular             14.2.8
rxjs                            7.5.7
typescript                      4.7.4
```

**Comment by JoostK** [comment] 2022-11-08 19:56
Closing as duplicate of #42247.

**Closed by JoostK** 2022-11-08 19:56 UTC
