### ISSUE TITLE
:host-context() Improperly Emulated in Pre-Built Library

### ISSUE THREAD

**Issue by brianmtreese** [angular/angular#36063] opened 2020-03-13 20:22 UTC
When a component in a library that is pre-built separately from the rest of the application, using: `ng build lib-sample`, the styles for the `:host-context` selector are not correctly emulated.

When it's not pre-built and complied along with the rest of the Angular application, the emulation works correctly.

Please see this example: [https://github.com/brianmtreese/angular-lib-build-host-context](https://github.com/brianmtreese/angular-lib-build-host-context)

**Comment by jelbourn** [comment] 2020-10-19 21:18
Looks like this was fixed in a later version of Angular (reproduction is v8)

**Closed by jelbourn** 2020-10-19 21:18 UTC
Labels: comp: core, core: CSS encapsulation
