### ISSUE TITLE
Forms: validators not run when importing extended FormControl class from NPM

### ISSUE THREAD

**Issue by dirkluijk** [angular/angular#40327] opened 2021-01-06 20:45 UTC
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/forms

### Is this a regression?

Yes, the previous version in which this bug was not present was: 10.0.14

### Description

I have a custom `FormControl` class, e.g.:

```ts
class CustomControl extends FormControl {}
```

When I import it from NPM, Angular 11 no longer runs validation. However, when I move the code to my own project, it works. I have no clue why?

## 🔬 Minimal Reproduction

Working example: https://stackblitz.com/edit/angular-ivy-b4nv5s
Broken example: https://stackblitz.com/edit/angular-ivy-wojhqw

Source of `FormControl`:
https://github.com/dirkluijk/ngx-typesafe-forms/blob/master/projects/ngx-typesafe-forms/src/lib/form-control.ts

When you clone the project above, and you run the demo application, above example works as expected.

## 🔥 Exception or Error
Form validators is not run when the class is imported from NPM.

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 11.0.5
Node: 12.15.0
OS: darwin x64

Angular: 11.0.5
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.5
@angular-devkit/build-angular   0.1100.5
@angular-devkit/core            11.0.5
@angular-devkit/schematics      11.0.5
@schematics/angular             11.0.5
@schematics/update              0.1100.5
rxjs                            6.6.3
typescript                      4.0.5
</code></pre>

**Comment by AndrewKushnir** [comment] 2021-01-07 01:09
Hi @dirkluijk,

I performed investigation and found out that the problem was caused by the fact that the library code was downleveled to es5 and `validator` (and similarly the `asyncValidator`) setter and getter functions started to look like this:

```
    /**
     * Provides a type safe FormControl class which accepts a generic type T.
     */
    var FormControl = /** @class */ (function (_super) {    // <-- this class extends native FormControl class
        __extends(FormControl, _super);
        function FormControl(formState, validatorOrOpts, asyncValidator) {
            return _super.call(this, formState, validatorOrOpts, asyncValidator) || this;
        }
        Object.defineProperty(FormControl.prototype, "validator", {
            get: function () {
                return _super.prototype.validator;
            },
            set: function (value) {
                _super.prototype.validator = value;
            },
            enumerable: false,
            configurable: true
        });
```

as a result, when the `validator` getter is being called, it tries to retrieve the value from the parent class, however in the constructor function (in the `_super` call) all validator information was stored on the current instance (i.e. `this`).

This was not a problem in the previous versions of the Forms package since the `validator` and `asyncValidator` were just regular fields and at some point in v10 they were converted to getter and setter pairs (which contain some additional logic). Also when you copy custom classes over locally, they are (most likely) built with es2015 (or later) target, thus avoiding downleveling to es5, that's the reason you see the describe differences.

As possible solutions you can either try publishing the package with es2015 target or update the getter/setter logic in your child class to take es5 behavior into account.

Since there are no action items for the framework, I'm going to close this ticket for now.

Thank you.

**Closed by AndrewKushnir** 2021-01-07 01:09 UTC
Labels: comp: forms

**Comment by dirkluijk** [comment] 2021-01-07 08:38
Awesome, thank you very much for this quick and elaborate explanation! I will take actions on my side to fix it. 😄
