### ISSUE TITLE
Injector API docs does not show deprecated GET method

### ISSUE THREAD

**Issue by ben-coble-sp** [angular/angular#17647] opened 2017-06-20 20:48 UTC
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[ ] Bug report 
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

See https://angular.io/api/core/Injector#overview. The documentation for the new GET method is documented twice and the old GET method is not displayed or marked deprecated. The source code at https://github.com/angular/angular/blob/master/packages/core/src/di/injector.ts#L46 looks good, so I think the issue is in your documentation generator somewhere. I apologize that I don't have time to review more closely.

## Expected behavior

https://angular.io/api/core/Injector#overview should correctly display current and deprecated GET methods.

## Minimal reproduction of the problem with instructions

See https://angular.io/api/core/Injector#overview. Selected API version is 4.2.3

## What is the motivation / use case for changing the behavior?

Accurate docs

## Please tell us about your environment
Confirmed on both Chrome 58 and Firefox 53

<pre><code>
Angular version: X.Y.Z

4.2.3

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 Chrome 58, Firefox 53

For Tooling issues:
- Node version: XX 
- Platform: 
n/a

Others:

n/a
</code></pre>

**Comment by gkalpak** [comment] 2017-06-21 05:19
Thx for reporting. This is a duplicate of #17041.

**Closed by gkalpak** 2017-06-21 05:19 UTC
