### ISSUE TITLE
Ivy no longer report invalid structural directives / schema errors on NgTemplate

### ISSUE THREAD

**Issue by laurentgoudet** [angular/angular#40388] opened 2021-01-11 10:16 UTC
# 🐞 bug report

### Affected Package

I believe the issue is caused by package `@angular/compiler`

### Is this a regression?

Yes, it used to throw an error with ViewEngine, and no longer does with Ivy.

### Description

The Angular compiler used to throw errors an invalid structural directives, e.g.:

```
<!-- ngTemplateOutlet is mispelled below -->
<ng-container *ngTemplateOutle="myTemplate"></ng-container>
<ng-template #myTemplate>
  My template is here
</ng-template>
```

```
Error: Can't bind to 'ngTemplateOutle' since it isn't a known property of 'ng-container'.
1. If 'ngTemplateOutle' is an Angular directive, then add 'CommonModule' to the '@NgModule.imports' of this component.
2. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
    <!-- ngTemplateOutlet is mispelled below -->
    <ng-container [ERROR ->]*ngTemplateOutle="myTemplate"></ng-container>
    <ng-template #myTemplate>
      My template is here")
Property binding ngTemplateOutle not used by any directive on an embedded template. Make sure that the property name is spelled correctly and all directives are listed in the "@NgModule.declarations". ("
    <!-- ngTemplateOutlet is mispelled below -->
    [ERROR ->]<ng-container *ngTemplateOutle="myTemplate"></ng-container>
    <ng-template #myTemplate>
      My te")
```

With Ivy & AOT with all the strict Angular template flags enabled the above code compiles fine, i.e. no error is thrown, which I've learned the hard way. Not throwing any compile or runtime error on invalid Angular templates makes working with them more dangerous than it should be.

## 🔬 Minimal Reproduction

Minimal reproduction in https://github.com/laurentgoudet/angular-ivy-no-error-invalid-structural-directive. https://github.com/laurentgoudet/angular-ivy-no-error-invalid-structural-directive/blob/master/src/app/app.component.ts contains the broken code, which by default compiles with no error.

Swapping `enableIvy` to `false` in https://github.com/laurentgoudet/angular-ivy-no-error-invalid-structural-directive/blob/master/tsconfig.json makes the compiler throw an error.

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 11.0.6
Node: 12.4.0
OS: darwin x64

Angular: 11.0.7
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.6
@angular-devkit/build-angular   0.1100.6
@angular-devkit/core            11.0.6
@angular-devkit/schematics      11.0.6
@angular/cli                    11.0.6
@schematics/angular             11.0.6
@schematics/update              0.1100.6
rxjs                            6.6.3
typescript                      4.0.5
</code></pre>

**Comment by petebacondarwin** [comment] 2021-01-11 10:33
The error is now shown at runtime: https://stackblitz.com/edit/angular-ivy-st6oms?devtoolsheight=33&file=src/app/app.component.html

**Comment by laurentgoudet** [comment] 2021-01-11 10:54
Right, I've missed that but `logUnknownPropertyError` just prints with `console.error`, bypassing the `ErrorHandler`, which explains why we didn't have anything in our production error logs either.

Is there any reason why this can no longer be enforced at compile time though? If yes, could we at least pass the error to the `ErrorHandler` so that it can then be logged / alerted on?

**Comment by petebacondarwin** [comment] 2021-01-11 11:09
Duplicate of #37322.

**Comment by jelbourn** [comment] 2021-01-13 16:11
Closing this as a duplicate of #37322.

**Closed by jelbourn** 2021-01-13 16:11 UTC
Labels: comp: compiler
