### ISSUE TITLE
FormGroup reset dont work and dont work SetValue 

### ISSUE THREAD

**Issue by ar53n** [angular/angular#16578] opened 2017-05-05 10:51 UTC
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.4.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =   

Hello, i have problem with reset method().

I create my form this.raceEntryForm = this.fb.group({ competitor: ['', [Validators.required]], boat: ['', [Validators.required]], device: [''] })
then form invalid
2. i have form raceEntry and have formControlName="boat". this component return object in my form
<boat-select [data]="boats" formControlName="boat"></boat-select>
3. when i invoke method reset() or reset({boat:''}) me returned empty object but form stay valid. And i cant `this.raceEntryForm.setValue({boat:null})` or `this.raceEntryForm.setValue({boat:null})`
4. I have solution. create form again, but need correct way

**Comment by ar53n** [comment] 2017-05-11 11:14
Also in value have empty object and control is an valid

**Comment by kara** [comment] 2017-08-11 21:08
@ar53n Can you add a plunker repro? It's hard to know what's going on just from that description.

**Comment by kara** [comment] 2017-09-01 23:46
Closing this, as we can't reproduce.

**Closed by kara** 2017-09-01 23:46 UTC
Labels: comp: forms, state: Need repro
