### ISSUE TITLE
Parent animation cannot query :enter or :leave when a child animation exists

### ISSUE THREAD

**Issue by timstoddard** [angular/angular#23977] opened 2018-05-17 22:37 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

When a parent and child element both have animation triggers, the parent element cannot query `:enter` or `:leave` elements; removing the child trigger allows the parent to query those elements successfully.
An example of the scenario that is not working is as follows:
```
<div class="outer" [@outerAnim]="getAnimState(routerOutlet)">
  <div class="inner" @innerAnim>
    <router-outlet #routerOutlet="outlet"></router-outlet>
  </div>
</div>
```

## Expected behavior

The parent animation should be able to query `:enter` and `:leave` normally, regardless of if there is an animation trigger on a child element.

## Minimal reproduction of the problem with instructions

See the demo stackblitz here: https://stackblitz.com/edit/oc-app-animation-issue
It is currently broken, removing the `@innerAnim` prop on the child div allows the parent animation to query `:enter` and `:leave` elements.

Note: My example uses route changes to trigger animations, but I tested my example without routing (using buttons with change listeners to change the animation state) and it still did not work so I do not think this issue is related to using the router outlet data to trigger animations.

## What is the motivation / use case for changing the behavior?

Child animation triggers should not block a parent animation trigger from querying `:enter` or `:leave`.

## Environment

<pre><code>
Angular version: 6.0.0

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by jelbourn** [comment] 2021-02-12 21:43
Duplicate of #35825

**Closed by jelbourn** 2021-02-12 21:43 UTC
Labels: P3, comp: animations, freq2: medium, type: bug/fix
