### ISSUE TITLE
Infinity loop because of MutationObserver

### ISSUE THREAD

**Issue by tamtakoe** [angular/angular#31483] opened 2019-07-10 05:22 UTC
# 🐞 bug report

### Affected Package
@angular/core, zone.js

### Is this a regression?
Not, I think

### Description
If we use:
- MutationObserver added after Angular started (I use third party non-angular plugin in my original case)
- some difficult Angular code like showing object in the *ngIf-area

we make browser slow down or kill it (especially Firefox)

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-mutationobserver-bug?file=src%2Fapp%2Fapp.component.html

Profiler:
![FF_profiler](https://user-images.githubusercontent.com/2244675/60942358-08ca4a00-a2eb-11e9-9487-ef72c69a0d89.png)

Function Call is zone.js:143
![zone_wrap](https://user-images.githubusercontent.com/2244675/60942446-5050d600-a2eb-11e9-8dbf-9e83ade5d252.png)

## 🔥 Exception or Error
No errors, just browser stuck

## 🌍  Your Environment
**Angular Version:**
<pre><code>Angular CLI: 8.1.0
Node: 10.14.0
OS: darwin x64
Angular: 8.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.801.0
@angular-devkit/build-angular     0.801.0
@angular-devkit/build-optimizer   0.801.0
@angular-devkit/build-webpack     0.801.0
@angular-devkit/core              8.1.0
@angular-devkit/schematics        8.1.0
@angular/cdk                      8.0.2
@angular/material                 8.0.2
@ngtools/webpack                  8.1.0
@schematics/angular               8.1.0
@schematics/update                0.801.0
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.35.2

zone.js 0.9.1
</code></pre>

**Anything else relevant?**
Any operating systems, any last versions of browsers

**Comment by trotyl** [comment] 2019-07-10 05:30
Duplicate of https://github.com/angular/angular/issues/26948

**Closed** 2019-08-22 22:50 UTC
Labels: comp: core
