### ISSUE TITLE
Not able to build simple Angular12 project following Angular.io

### ISSUE THREAD

**Issue by MussaratAziz** [angular/angular#42376] opened 2021-05-27 00:38 UTC
I am trying to build Angular 12 project i am using **ng build** command i am getting following errors. 
**C:\Angular_ENT\App>ng build**  
⠋ Generating browser application bundles...(node:25612) UnhandledPromiseRejectionWarning: TypeError: The 'compilation' argument must be an instance of Compilation
    at getCompilationHooks (C:\Angular_ENT\App\node_modules\webpack\lib\javascript\JavascriptModulesPlugin.js:125:10)
    at C:\Angular_ENT\App\node_modules\webpack\lib\javascript\CommonJsChunkFormatPlugin.js:43:19
    at Hook.eval [as call] (eval at create (C:\Angular_ENT\App\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:7:1)
    at Hook.CALL_DELEGATE [as _call] (C:\Angular_ENT\App\node_modules\tapable\lib\Hook.js:14:14)
    at Compiler.newCompilation (C:\Angular_ENT\App\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\Compiler.js:1030:30)    
    at C:\Angular_ENT\App\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\Compiler.js:1073:29
    at Hook.eval [as callAsync] (eval at create (C:\Angular_ENT\App\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)      
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (C:\Angular_ENT\App\node_modules\tapable\lib\Hook.js:18:14)
    at Compiler.compile (C:\Angular_ENT\App\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\Compiler.js:1068:28)
    at Compiler.runAsChild (C:\Angular_ENT\App\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\Compiler.js:520:8)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:25612) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:25612) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
✔ Browser application bundle generation complete.

Warning: C:/Angular_ENT/App/src/app/app-routing.module.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.

Warning: C:/Angular_ENT/App/src/app/app.component.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.

Warning: C:/Angular_ENT/App/src/app/app.module.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.

Warning: C:/Angular_ENT/App/src/environments/environment.prod.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.

Warning: C:/Angular_ENT/App/src/main.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.

Warning: C:/Angular_ENT/App/src/polyfills.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.

../Angular_ENT/App/src/main.ts - Error: Module build failed: Error: Cannot find module 'C:\Angular_ENT\App\node_modules\@angular-devkit\build-angular\src\babel\webpack-loader.js'
Require stack:
- C:\Angular_ENT\App\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\ProgressPlugin.js
- C:\Angular_ENT\App\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\index.js
- C:\Angular_ENT\App\node_modules\@angular-devkit\build-angular\src\webpack\utils\helpers.js
- C:\Angular_ENT\App\node_modules\@angular-devkit\build-angular\src\utils\package-chunk-sort.js
- C:\Angular_ENT\App\node_modules\@angular-devkit\build-angular\src\browser\index.js
- C:\Angular_ENT\App\node_modules\@angular-devkit\architect\node\node-modules-architect-host.js
- C:\Angular_ENT\App\node_modules\@angular-devkit\architect\node\index.js
- C:\Angular_ENT\App\node_modules\@angular\cli\models\architect-command.js
- C:\Angular_ENT\App\node_modules\@angular\cli\commands\build-impl.js
- C:\Angular_ENT\App\node_modules\@angular-devkit\schematics\tools\export-ref.js
- C:\Angular_ENT\App\node_modules\@angular-devkit\schematics\tools\index.js
- C:\Angular_ENT\App\node_modules\@angular\cli\utilities\json-schema.js
- C:\Angular_ENT\App\node_modules\@angular\cli\models\command-runner.js
- C:\Angular_ENT\App\node_modules\@angular\cli\lib\cli\index.js
- C:\Users\m\AppData\Roaming\npm\node_modules\@angular\cli\lib\init.js
- C:\Users\m\AppData\Roaming\npm\node_modules\@angular\cli\bin\ng
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at C:\Angular_ENT\App\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\ProgressPlugin.js:412:9
    at Hook.eval [as call] (eval at create (C:\Angular_ENT\App\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:7:1)
    at NormalModule.doBuild (C:\Angular_ENT\App\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\NormalModule.js:724:24)
    at NormalModule.build (C:\Angular_ENT\App\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\NormalModule.js:878:15)
    at C:\Angular_ENT\App\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\Compilation.js:1311:12
    at NormalModule.needBuild (C:\Angular_ENT\App\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\NormalModule.js:1143:32)

../Angular_ENT/App/src/polyfills.ts - Error: Module build failed: Error: Cannot find module 'C:\Angular_ENT\App\node_modules\@angular-devkit\build-optimizer\src\build-optimizer\webpack-loader.js'
Require stack:
- C:\Angular_ENT\App\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\ProgressPlugin.js
- C:\Angular_ENT\App\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\index.js
- C:\Angular_ENT\App\node_modules\@angular-devkit\build-angular\src\webpack\utils\helpers.js
- C:\Angular_ENT\App\node_modules\@angular-devkit\build-angular\src\utils\package-chunk-sort.js
- C:\Angular_ENT\App\node_modules\@angular-devkit\build-angular\src\browser\index.js
- C:\Angular_ENT\App\node_modules\@angular-devkit\architect\node\node-modules-architect-host.js
- C:\Angular_ENT\App\node_modules\@angular-devkit\architect\node\index.js
- C:\Angular_ENT\App\node_modules\@angular\cli\models\architect-command.js
- C:\Angular_ENT\App\node_modules\@angular\cli\commands\build-impl.js
- C:\Angular_ENT\App\node_modules\@angular-devkit\schematics\tools\export-ref.js
- C:\Angular_ENT\App\node_modules\@angular-devkit\schematics\tools\index.js
- C:\Angular_ENT\App\node_modules\@angular\cli\utilities\json-schema.js
- C:\Angular_ENT\App\node_modules\@angular\cli\models\command-runner.js
- C:\Angular_ENT\App\node_modules\@angular\cli\lib\cli\index.js
- C:\Users\m\AppData\Roaming\npm\node_modules\@angular\cli\lib\init.js
- C:\Users\m\AppData\Roaming\npm\node_modules\@angular\cli\bin\ng
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at C:\Angular_ENT\App\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\ProgressPlugin.js:412:9
    at Hook.eval [as call] (eval at create (C:\Angular_ENT\App\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:7:1)
    at NormalModule.doBuild (C:\Angular_ENT\App\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\NormalModule.js:724:24)
    at NormalModule.build (C:\Angular_ENT\App\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\NormalModule.js:878:15)
    at C:\Angular_ENT\App\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\Compilation.js:1311:12
    at NormalModule.needBuild (C:\Angular_ENT\App\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\NormalModule.js:1143:32)
../Angular_ENT/App/src/styles.css - Error: Module build failed: Error: Cannot find module 'C:\Angular_ENT\App\node_modules\mini-css-extract-plugin\dist\loader.js'
Require stack:
- C:\Angular_ENT\App\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\ProgressPlugin.js
- C:\Angular_ENT\App\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\index.js
- C:\Angular_ENT\App\node_modules\@angular-devkit\build-angular\src\webpack\utils\helpers.js
- C:\Angular_ENT\App\node_modules\@angular-devkit\build-angular\src\utils\package-chunk-sort.js
- C:\Angular_ENT\App\node_modules\@angular-devkit\build-angular\src\browser\index.js
- C:\Angular_ENT\App\node_modules\@angular-devkit\architect\node\node-modules-architect-host.js
- C:\Angular_ENT\App\node_modules\@angular-devkit\architect\node\index.js
- C:\Angular_ENT\App\node_modules\@angular\cli\models\architect-command.js
- C:\Angular_ENT\App\node_modules\@angular\cli\commands\build-impl.js
- C:\Angular_ENT\App\node_modules\@angular-devkit\schematics\tools\export-ref.js
- C:\Angular_ENT\App\node_modules\@angular-devkit\schematics\tools\index.js
- C:\Angular_ENT\App\node_modules\@angular\cli\utilities\json-schema.js
- C:\Angular_ENT\App\node_modules\@angular\cli\models\command-runner.js
- C:\Angular_ENT\App\node_modules\@angular\cli\lib\cli\index.js
- C:\Users\m\AppData\Roaming\npm\node_modules\@angular\cli\lib\init.js
- C:\Users\m\AppData\Roaming\npm\node_modules\@angular\cli\bin\ng
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at C:\Angular_ENT\App\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\ProgressPlugin.js:412:9
    at Hook.eval [as call] (eval at create (C:\Angular_ENT\App\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:7:1)
    at Hook.CALL_DELEGATE [as _call] (C:\Angular_ENT\App\node_modules\tapable\lib\Hook.js:14:14)
    at NormalModule.doBuild (C:\Angular_ENT\App\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\NormalModule.js:724:24)
    at NormalModule.build (C:\Angular_ENT\App\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\NormalModule.js:878:15)
    at C:\Angular_ENT\App\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\Compilation.js:1311:12

**ng --version**

**Angular CLI: 12.0.2**
Node: 14.17.0
Package Manager: npm 6.14.13
OS: win32 x64

Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1200.2 (cli-only)
@angular-devkit/core         12.0.2 (cli-only)
@angular-devkit/schematics   12.0.2 (cli-only)
@schematics/angular          12.0.2 (cli-only)

**node --version
v14.17.0**

**npm --v
6.14.13**

Am i missing any thing?

**Comment by petebacondarwin** [comment] 2021-05-27 06:29
Duplicate of https://github.com/angular/angular-cli/issues/20961

**Closed by petebacondarwin** 2021-05-27 06:29 UTC

**Comment by MussaratAziz** [comment] 2021-05-28 02:56
@petebacondarwin Thanks for your reply. But after creating brand new Angular 12 project i am still unable to build. Please have a look. I havent changed any thing in the project. Just followed the steps mentioned https://angular.io/guide/setup-local 

**C:>cd myFirstAngular12**

**C:\myFirstAngular12>npm ls webpack
my-first-angular12@0.0.0 C:\myFirstAngular12
`-- @angular-devkit/build-angular@12.0.2
  `-- webpack@5.36.2**


**C:\myFirstAngular12>ng build
√ Browser application bundle generation complete.**

Warning: C:/myFirstAngular12/src/app/app.component.css exceeded maximum budget. Budget 2.00 kB was not met by 1.98 kB with a total of 3.98 kB.



**../myFirstAngular12/src/main.ts - Error: Module build failed: Error: Cannot find module** 'C:\myFirstAngular12\node_modules\@angular-devkit\build-angular\src\babel\webpack-loader.js'
Require stack:
- C:\myFirstAngular12\node_modules\webpack\lib\ProgressPlugin.js
- C:\myFirstAngular12\node_modules\webpack\lib\index.js
- C:\myFirstAngular12\node_modules\@angular-devkit\build-webpack\src\webpack\index.js
- C:\myFirstAngular12\node_modules\@angular-devkit\build-webpack\src\index.js
- C:\myFirstAngular12\node_modules\@angular-devkit\build-angular\src\browser\index.js
- C:\myFirstAngular12\node_modules\@angular-devkit\architect\node\node-modules-architect-host.js
- C:\myFirstAngular12\node_modules\@angular-devkit\architect\node\index.js
- C:\myFirstAngular12\node_modules\@angular\cli\models\architect-command.js
- C:\myFirstAngular12\node_modules\@angular\cli\commands\build-impl.js
- C:\myFirstAngular12\node_modules\@angular-devkit\schematics\tools\export-ref.js
- C:\myFirstAngular12\node_modules\@angular-devkit\schematics\tools\index.js
- C:\myFirstAngular12\node_modules\@angular\cli\utilities\json-schema.js
- C:\myFirstAngular12\node_modules\@angular\cli\models\command-runner.js
- C:\myFirstAngular12\node_modules\@angular\cli\lib\cli\index.js
- C:\Users\m\AppData\Roaming\npm\node_modules\@angular\cli\lib\init.js
- C:\Users\m\AppData\Roaming\npm\node_modules\@angular\cli\bin\ng
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at C:\myFirstAngular12\node_modules\webpack\lib\ProgressPlugin.js:412:9
    at Hook.eval [as call] (eval at create (C:\myFirstAngular12\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:7:1)
    at NormalModule.doBuild (C:\myFirstAngular12\node_modules\webpack\lib\NormalModule.js:724:24)
    at NormalModule.build (C:\myFirstAngular12\node_modules\webpack\lib\NormalModule.js:878:15)
    at C:\myFirstAngular12\node_modules\webpack\lib\Compilation.js:1311:12
    at NormalModule.needBuild (C:\myFirstAngular12\node_modules\webpack\lib\NormalModule.js:1143:32)

**../myFirstAngular12/src/polyfills.ts - Error: Module build failed: Error: Cannot find module** 'C:\myFirstAngular12\node_modules\@angular-devkit\build-optimizer\src\build-optimizer\webpack-loader.js'
Require stack:
- C:\myFirstAngular12\node_modules\webpack\lib\ProgressPlugin.js
- C:\myFirstAngular12\node_modules\webpack\lib\index.js
- C:\myFirstAngular12\node_modules\@angular-devkit\build-webpack\src\webpack\index.js
- C:\myFirstAngular12\node_modules\@angular-devkit\build-webpack\src\index.js
- C:\myFirstAngular12\node_modules\@angular-devkit\build-angular\src\browser\index.js
- C:\myFirstAngular12\node_modules\@angular-devkit\architect\node\node-modules-architect-host.js
- C:\myFirstAngular12\node_modules\@angular-devkit\architect\node\index.js
- C:\myFirstAngular12\node_modules\@angular\cli\models\architect-command.js
- C:\myFirstAngular12\node_modules\@angular\cli\commands\build-impl.js
- C:\myFirstAngular12\node_modules\@angular-devkit\schematics\tools\export-ref.js
- C:\myFirstAngular12\node_modules\@angular-devkit\schematics\tools\index.js
- C:\myFirstAngular12\node_modules\@angular\cli\utilities\json-schema.js
- C:\myFirstAngular12\node_modules\@angular\cli\models\command-runner.js
- C:\myFirstAngular12\node_modules\@angular\cli\lib\cli\index.js
- C:\Users\m\AppData\Roaming\npm\node_modules\@angular\cli\lib\init.js
- C:\Users\m\AppData\Roaming\npm\node_modules\@angular\cli\bin\ng
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at C:\myFirstAngular12\node_modules\webpack\lib\ProgressPlugin.js:412:9
    at Hook.eval [as call] (eval at create (C:\myFirstAngular12\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:7:1)
    at NormalModule.doBuild (C:\myFirstAngular12\node_modules\webpack\lib\NormalModule.js:724:24)
    at NormalModule.build (C:\myFirstAngular12\node_modules\webpack\lib\NormalModule.js:878:15)
    at C:\myFirstAngular12\node_modules\webpack\lib\Compilation.js:1311:12
    at NormalModule.needBuild (C:\myFirstAngular12\node_modules\webpack\lib\NormalModule.js:1143:32)

**../myFirstAngular12/src/styles.css - Error: Module build failed: Error: Cannot find module** 'C:\myFirstAngular12\node_modules\mini-css-extract-plugin\dist\loader.js'
Require stack:
- C:\myFirstAngular12\node_modules\webpack\lib\ProgressPlugin.js
- C:\myFirstAngular12\node_modules\webpack\lib\index.js
- C:\myFirstAngular12\node_modules\@angular-devkit\build-webpack\src\webpack\index.js
- C:\myFirstAngular12\node_modules\@angular-devkit\build-webpack\src\index.js
- C:\myFirstAngular12\node_modules\@angular-devkit\build-angular\src\browser\index.js
- C:\myFirstAngular12\node_modules\@angular-devkit\architect\node\node-modules-architect-host.js
- C:\myFirstAngular12\node_modules\@angular-devkit\architect\node\index.js
- C:\myFirstAngular12\node_modules\@angular\cli\models\architect-command.js
- C:\myFirstAngular12\node_modules\@angular\cli\commands\build-impl.js
- C:\myFirstAngular12\node_modules\@angular-devkit\schematics\tools\export-ref.js
- C:\myFirstAngular12\node_modules\@angular-devkit\schematics\tools\index.js
- C:\myFirstAngular12\node_modules\@angular\cli\utilities\json-schema.js
- C:\myFirstAngular12\node_modules\@angular\cli\models\command-runner.js
- C:\myFirstAngular12\node_modules\@angular\cli\lib\cli\index.js
- C:\Users\m\AppData\Roaming\npm\node_modules\@angular\cli\lib\init.js
- C:\Users\m\AppData\Roaming\npm\node_modules\@angular\cli\bin\ng
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at C:\myFirstAngular12\node_modules\webpack\lib\ProgressPlugin.js:412:9
    at Hook.eval [as call] (eval at create (C:\myFirstAngular12\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:7:1)
    at Hook.CALL_DELEGATE [as _call] (C:\myFirstAngular12\node_modules\tapable\lib\Hook.js:14:14)
    at NormalModule.doBuild (C:\myFirstAngular12\node_modules\webpack\lib\NormalModule.js:724:24)
    at NormalModule.build (C:\myFirstAngular12\node_modules\webpack\lib\NormalModule.js:878:15)
    at C:\myFirstAngular12\node_modules\webpack\lib\Compilation.js:1311:12

**../myFirstAngular12/src/app/app.component.css - Error: Module build failed (from ../../../myFirstAngular12/node_modules/raw-loader/dist/cjs.js):
Error: Cannot find module 'C:\myFirstAngular12\node_modules\raw-loader\dist\cjs.js'**
Require stack:
- C:\myFirstAngular12\node_modules\loader-runner\lib\loadLoader.js
- C:\myFirstAngular12\node_modules\loader-runner\lib\LoaderRunner.js
- C:\myFirstAngular12\node_modules\webpack\lib\NormalModule.js
- C:\myFirstAngular12\node_modules\webpack\lib\NormalModuleFactory.js
- C:\myFirstAngular12\node_modules\webpack\lib\Compiler.js
- C:\myFirstAngular12\node_modules\webpack\lib\ProgressPlugin.js
- C:\myFirstAngular12\node_modules\webpack\lib\index.js
- C:\myFirstAngular12\node_modules\@angular-devkit\build-webpack\src\webpack\index.js
- C:\myFirstAngular12\node_modules\@angular-devkit\build-webpack\src\index.js
- C:\myFirstAngular12\node_modules\@angular-devkit\build-angular\src\browser\index.js
- C:\myFirstAngular12\node_modules\@angular-devkit\architect\node\node-modules-architect-host.js
- C:\myFirstAngular12\node_modules\@angular-devkit\architect\node\index.js
- C:\myFirstAngular12\node_modules\@angular\cli\models\architect-command.js
- C:\myFirstAngular12\node_modules\@angular\cli\commands\build-impl.js
- C:\myFirstAngular12\node_modules\@angular-devkit\schematics\tools\export-ref.js
- C:\myFirstAngular12\node_modules\@angular-devkit\schematics\tools\index.js
- C:\myFirstAngular12\node_modules\@angular\cli\utilities\json-schema.js
- C:\myFirstAngular12\node_modules\@angular\cli\models\command-runner.js
- C:\myFirstAngular12\node_modules\@angular\cli\lib\cli\index.js
- C:\Users\m\AppData\Roaming\npm\node_modules\@angular\cli\lib\init.js
- C:\Users\m\AppData\Roaming\npm\node_modules\@angular\cli\bin\ng
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at loadLoader (C:\myFirstAngular12\node_modules\loader-runner\lib\loadLoader.js:19:17)
    at iteratePitchingLoaders (C:\myFirstAngular12\node_modules\loader-runner\lib\LoaderRunner.js:182:2)
    at runLoaders (C:\myFirstAngular12\node_modules\loader-runner\lib\LoaderRunner.js:397:2)
    at NormalModule.doBuild (C:\myFirstAngular12\node_modules\webpack\lib\NormalModule.js:729:3)
    at NormalModule.build (C:\myFirstAngular12\node_modules\webpack\lib\NormalModule.js:878:15)
    at C:\myFirstAngular12\node_modules\webpack\lib\Compilation.js:1311:12

**Error: src/app/app-routing.module.ts:10:14 - error NG6002: Appears in the NgModule.imports of AppModule, but itself has errors**

10 export class AppRoutingModule { }
                ~~~~~~~~~~~~~~~~


**C:/myFirstAngular12/src/app/app.component.css - Error: C:/myFirstAngular12/src/app/app.component.css from Css Minimizer**
C:/myFirstAngular12/src/app/app.component.css:1:1: Unknown word [C:/myFirstAngular12/src/app/app.component.css:1,1]
    at Input.error (C:\myFirstAngular12\node_modules\postcss\lib\input.js:123:16)
    at Parser.unknownWord (C:\myFirstAngular12\node_modules\postcss\lib\parser.js:518:22)
    at Parser.other (C:\myFirstAngular12\node_modules\postcss\lib\parser.js:149:12)
    at Parser.parse (C:\myFirstAngular12\node_modules\postcss\lib\parser.js:59:16)
    at parse (C:\myFirstAngular12\node_modules\postcss\lib\parse.js:11:12)
    at new LazyResult (C:\myFirstAngular12\node_modules\postcss\lib\lazy-result.js:132:16)
    at Processor.process (C:\myFirstAngular12\node_modules\postcss\lib\processor.js:34:12)
    at cssnanoMinify (C:\myFirstAngular12\node_modules\css-minimizer-webpack-plugin\dist\utils.js:58:61)
    at minify (C:\myFirstAngular12\node_modules\css-minimizer-webpack-plugin\dist\minify.js:15:32)
    at C:\myFirstAngular12\node_modules\css-minimizer-webpack-plugin\dist\index.js:262:128


**ng --version**

Angular CLI: 12.0.2
Node: 14.17.0
Package Manager: npm 6.14.13
OS: win32 x64

Angular:
...

Package Version
@angular-devkit/architect 0.1200.2 (cli-only)
@angular-devkit/core 12.0.2 (cli-only)
@angular-devkit/schematics 12.0.2 (cli-only)
@schematics/angular 12.0.2 (cli-only)

**node --version**
v14.17.0

**npm --v**
6.14.13

**Comment by MussaratAziz** [comment] 2021-05-28 22:55
@petebacondarwin  OK Thanks.
