### ISSUE TITLE
@ContentChildren doesn't work with component loaded by router

### ISSUE THREAD

**Issue by andrui** [angular/angular#9136] opened 2016-06-10 12:29 UTC
Hi!

**Short description:**
If components are loaded into parent component by router ContentChildren doesn't track them.

Here is [plunker](https://plnkr.co/edit/MHKTnwdA2r8My9buca6d?p=preview) 
**Preconditions:**
1) There are container component and panel component (container component queries panel component)
2) App has one one container component and 3 panel components:
    a) panel1 present statically from the scratch
    b) panel2 is showed conditionally inside "div"
    c) panel3 is loaded via router outlet

**STR:**
1) Open plunker and console
2) There will be the log in console like '>>>>>>>> ngAfterContentInit ...' with array with one panel component of panel1
3) Click button to show panel2. Chages are detected and there will record like '>>>>>>>> panels changed ...' in console with array of two panels 
4) Finally click link to load panel3 via router => panel appears in DOM, but changes are not detected and we still have two panels in "panels" property

If this is an expected behaviour of ContentChildren with dynamic component loading then maybe there is some workaround to achieve my goal?

**Comment by zoechi** [comment] 2016-06-10 12:57
Looks similar to #5241

**Comment by pkozlowski-opensource** [comment] 2016-06-15 19:50
Yes, this is duplicate of #5241, thnx @zoechi !

**Closed by pkozlowski-opensource** 2016-06-15 19:50 UTC
