### ISSUE TITLE
Cached routes with RouteReuseStrategy call resolvers.

### ISSUE THREAD

**Issue by SC-JC** [angular/angular#34882] opened 2020-01-21 14:31 UTC
# 🐞 bug report

### Affected Package
@angular/router

### Is this a regression?

Not entirely sure

### Description

When I cache a route with a custom RouteReuseStrategy and load the cached route/component, the resolver for the route get's called again, resulting in wrong data being displayed.

## 🌍  Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___ 
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | | 
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | | 
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 8.3.22
Node: 11.13.0
OS: win32 x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.803.22
@angular-devkit/build-angular      0.803.22
@angular-devkit/build-optimizer    0.803.22
@angular-devkit/build-webpack      0.803.22
@angular-devkit/core               8.3.22
@angular-devkit/schematics         8.3.22
@angular/cdk                       8.2.2
@angular/cli                       8.3.22
@angular/flex-layout               8.0.0-beta.27
@angular/material                  8.2.2
@angular/material-moment-adapter   8.2.3
@ngtools/webpack                   8.3.22
@schematics/angular                8.3.22
@schematics/update                 0.803.22
rxjs                               6.5.4
typescript                         3.5.3
webpack                            4.39.2
</code></pre>

**Comment by atscott** [comment] 2020-07-06 18:49
Hi @SC-JC, can you provide a minimal reproduction for this, either in stackblitz or a small project on GitHub?

**Comment by SC-JC** [comment] 2020-07-07 09:17
@atscott Here is a stackblitz: https://stackblitz.com/edit/angular-upbnpo

As you can see, the DashboardComponent only gets initialized once and then gets stored and retrieved via custom RouteReuseStrategy, but the DashboardResolver gets called everytime the route gets called.
This can cause unneccessary backend-calls/loading times and if you use resolvers to write data into subjects, it can result in wrong data being displayed.

I'd say resolvers should only be called after shouldAttach returns false.

**Comment by atscott** [comment] 2020-07-07 17:01
Hmm, I see what you mean. I can definitely see why in most cases you wouldn't want resolvers to run if the route is reused. I think this change would have to be developed as an opt-in feature. There could be good arguments the other way as well and changing the default behavior is something we can't do when people may already rely on how it works now.

**Comment by SC-JC** [comment] 2020-07-08 11:06
I agree on not changing default behaviour, adding a new function to RouteReuseStrategy e.g. shouldResolve, that gets called if shouldAttach returns true to determine if resolvers for a cached route should be called or not, would be a decent solution.
(So if you want to keep your current behaviour, you just need to add shouldResolve(){return true} to your custom RouteReuseStrategy)
Though right now the resolvers get called before shouldAttach returns a value.

**Comment by SC-JC** [comment] 2021-06-25 14:41
This bug cannot be fixed outside of the angular scope.

It's a bug when using resolvers and a custom RouteReuseStrategy in their intended way:
To load data on route change, then change the route and then load the resolved data in one of the components lifecycle hooks (Usually ngOnInit).

It will make unneccessary requests when using a custom RouteReuseStrategy. This is a bug in 99% of usecases. If I want to load a cached route/component, it should use the cached data.
There also is no lifecycle hook in components that could get called whenever a component is loaded from cache with a RouteReuseStrategy. 
So the only usecase for calling the resolvers when loading a cached route with a RouteReuseStrategy is if you read data from the ActivatedRouteSnapshot in a function call outside of the angular lifecycle hooks.

**Comment by xzneozx96** [comment] 2021-08-19 13:11
> This bug cannot be fixed outside of the angular scope.
> 
> It's a bug when using resolvers and a custom RouteReuseStrategy in their intended way:
> To load data on route change, then change the route and then load the resolved data in one of the components lifecycle hooks (Usually ngOnInit).
> 
> It will make unneccessary requests when using a custom RouteReuseStrategy. This is a bug in 99% of usecases. If I want to load a cached route/component, it should use the cached data.
> There also is no lifecycle hook in components that could get called whenever a component is loaded from cache with a RouteReuseStrategy.
> So the only usecase for calling the resolvers when loading a cached route with a RouteReuseStrategy is if you read data from the ActivatedRouteSnapshot in a function call outside of the angular lifecycle hooks.

I run into the same issue, have you figured out a workaround ?

**Comment by atscott** [comment] 2021-08-22 18:22
@xzneozx96 The workaround could be to save the resolved data to the component in `ngOnInit`. Because `ngOnInit` will not be called again if the route is re-used, it will not grab new info from the resolved data.
```
  testString: string;
  ngOnInit() {
    console.log('init');
    this.testString = this.route.snapshot.data.testString;
  }
```
Resolvers that you don't want to run again can be modified to check if the route is going to be re-attached by the `RouteReuseStrategy`:
```
  constructor(private reuser: RouteReuseStrategy) {}

  resolve(route: ActivatedRouteSnapshot) {
    if (this.reuser.shouldAttach(route)) {
      return;
    }
```

https://stackblitz.com/edit/angular-szfkxg?file=src%2Fapp%2Fresolvers%2Fdashboard-resolver.ts

**Comment by atscott** [comment] 2021-09-15 16:38
Closing, as a workaround is available and there are not enough votes to integrate this as a feature in the router

**Closed by atscott** 2021-09-15 16:38 UTC
Labels: feature, freq1: low, comp: router, insufficient votes, votes required
