### ISSUE TITLE
Routes of Manually loaded modules are not working

### ISSUE THREAD

**Issue by illeb** [angular/angular#35822] opened 2020-03-03 10:29 UTC
# 🐞 bug report

### Affected Package
@angular/core and @angular/router, i guess?

### Is this a regression?
unsure

### Description
I have a large application with some angular modules that are manually loaded with `moduleFactory.create()`.
All the modules works as intended, except for the child routes configurations: all the child routes specified in the lazy loaded modules are not loaded by the router and does not work.

All the child routes are specified via 
```
RouterModule.forChild([{
     //routes
}]),
```
so for example 
```
@NgModule({
    declarations: [
      LazyComponent
    ],
    imports: [
        CommonModule,
        RouterModule.forChild([{
          path: 'lazy', component: LazyComponent
        }]),
    ],
    providers: [ ],
    entryComponents: [],
})
export default class LazyModule {
    constructor() { }
}
```

The lazy module are manually loaded this way:
```
import { Compiler, Injectable, Injector, NgModuleFactory } from '@angular/core';

@Injectable()
export class ModuleLoaderService {
    constructor(private compiler: Compiler, private injector: Injector) {}

    loadModule() {
        const lazyModuleInjector = Injector.create({
            providers: [],
            parent: this.injector,
            name: 'lazyModule'
        });
        return import('./lazy/lazy.module')
            .then(
                m => m.default,
                () => {}
            )
            .then(elementModuleOrFactory => {
                try {
                    return this.compiler.compileModuleAsync(elementModuleOrFactory);
                } catch (err) {}
            })
            .then(moduleFactory => {
                try {
                    const elementModuleRef = moduleFactory.create(lazyModuleInjector);
                    return Promise.resolve(elementModuleRef.instance);
                } catch (err) {
                    console.log(err);
                }
            });
    }
}
```
(the code is based on this guide https://juristr.com/blog/2019/10/lazyload-module-ivy-viewengine/)

Based on this code, the issue is that i can't navigate to `/lazy`, so for example 
`this.router.navigate(['lazy'])` will throw an ` Error: Cannot match any routes` exception.

What i am doing wrong?
## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-nhh9eg
Simply click on the buttons for reproduction of the issue.

## 🔥 Exception or Error
The routes of angular lazy loaded modules are not loaded in the Router, so the exception occurs at every attempt to navigate to those routes, for example:
<pre>
  <code>
ERROR
Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'lazy'
Error: Cannot match any routes. URL Segment: 'lazy'
at ApplyRedirects.noMatchError (https://angular-nhh9eg.stackblitz.io/turbo_modules/@angular/router@9.0.4/bundles/router.umd.js:2668:20)
at CatchSubscriber.eval [as selector] (https://angular-nhh9eg.stackblitz.io/turbo_modules/@angular/router@9.0.4/bundles/router.umd.js:2649:33)
at CatchSubscriber.error (https://angular-nhh9eg.stackblitz.io/turbo_modules/rxjs@6.5.4/internal/operators/catchError.js:48:31)
at MapSubscriber.Subscriber._error (https://angular-nhh9eg.stackblitz.io/turbo_modules/rxjs@6.5.4/internal/Subscriber.js:92:26)
at MapSubscriber.Subscriber.error (https://angular-nhh9eg.stackblitz.io/turbo_modules/rxjs@6.5.4/internal/Subscriber.js:72:18)
at MapSubscriber.Subscriber._error (https://angular-nhh9eg.stackblitz.io/turbo_modules/rxjs@6.5.4/internal/Subscriber.js:92:26)
at MapSubscriber.Subscriber.error (https://angular-nhh9eg.stackblitz.io/turbo_modules/rxjs@6.5.4/internal/Subscriber.js:72:18)
at MapSubscriber.Subscriber._error (https://angular-nhh9eg.stackblitz.io/turbo_modules/rxjs@6.5.4/internal/Subscriber.js:92:26)
at MapSubscriber.Subscriber.error (https://angular-nhh9eg.stackblitz.io/turbo_modules/rxjs@6.5.4/internal/Subscriber.js:72:18)
at ThrowIfEmptySubscriber.Subscriber._error (https://angular-nhh9eg.stackblitz.io/turbo_modules/rxjs@6.5.4/internal/Subscriber.js:92:26)
  </code>
</pre>

## 🌍  Your Environment

**Angular Version:**
I can confirm the issue is reproducible locally with those packages version.
<pre>
  <code>
@angular-devkit/architect         0.900.4
@angular-devkit/build-angular     0.900.4
@angular-devkit/build-optimizer   0.900.4
@angular-devkit/build-webpack     0.900.4
@angular-devkit/core              9.0.4
@angular-devkit/schematics        9.0.4
@angular/cdk                      9.1.0
@angular/material                 9.1.0
@ngtools/webpack                  9.0.4
@schematics/angular               9.0.4
@schematics/update                0.900.4
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
  </code>
</pre>

**Comment by Luxor001** [comment] 2020-03-06 08:34
As sidenote, i am currently using this workaround:

```
@NgModule({
    declarations: [
      LazyComponent
    ],
    imports: [
        CommonModule,
        RouterModule.forChild([{
          path: 'lazy', component: LazyComponent
        }]),
    ],
    providers: [ ],
    entryComponents: [],
})
export default class LazyModule {
    constructor(private router: Router) {
      //workaround: manually add the path to the router config
      router.config.push({
          path: 'lazy', component: LazyComponent
        });
    }
}
```
https://stackblitz.com/edit/angular-tf5j6j

**Comment by atscott** [comment] 2020-07-08 23:50
I don't think the Router was exactly designed to support manually loading child modules with routes like this and expects them to be loaded through `loadChildren`. Child configurations are matched in the earliest stage "applyRedirects"

https://github.com/angular/angular/blob/e50c7dcc4c11a61a63b8234cc9649cad7584ee76/packages/router/src/router.ts#L500
https://github.com/angular/angular/blob/e50c7dcc4c11a61a63b8234cc9649cad7584ee76/packages/router/src/apply_redirects.ts#L298-L315

In this way, you can think of the route configuration as one stream that's already "set up" rather than something that's fragmented and gets built up as the lazy modules load and return routes. 

I'm changing this from a bug to a feature request and also adding the docs label to indicate that there could be some documentation around this expectation.

**Comment by atscott** [comment] 2021-05-24 21:16
Closing as working as intended. The documentation explains how to set up lazy routes and adding documentation about the various ways to _not_ do it would be more confusing than anything else.

**Closed by atscott** 2021-05-24 21:16 UTC
Labels: comp: docs, comp: router, feature, freq1: low, router: lazy loading
