### ISSUE TITLE
gulp test.unit.js shows output twice

### ISSUE THREAD

**Issue by mhevery** [angular/angular#1926] opened 2015-05-15 20:41 UTC
```
[13:40:18] Finished '!broccoli.js.dev' after 1.06 s
[13:40:18] Starting '!test.unit.js/karma-run'...
...............................................................................................................................................................
.
...............................................................................................................................................................
.
...............................................................................................................................................................
.
...............................................................................................................................................................
.
...............................................................................................................................................................
.
...............................................................................................................................................................
.
......................................................................................................................
Chrome 44.0.2402 (Mac OS X 10.10.3) forwardRef should wrap and unwrap the reference FAILED
	ReferenceError: unwrapRef is not defined
	    at /Users/misko/Dropbox/work/angular/dist/js/dev/es5/angular2/test/di/forward_ref_spec.js:22:16
	    at Function.$__export.apply (/Users/misko/Dropbox/work/angular/dist/js/dev/es5/angular2/src/facade/lang.js:289:23)
	    at FunctionWithParamTokens.$__export.execute (/Users/misko/Dropbox/work/angular/dist/js/dev/es5/angular2/src/test_lib/test_injector.js:170:29)
	    at Object.<anonymous> (/Users/misko/Dropbox/work/angular/dist/js/dev/es5/angular2/src/test_lib/test_lib.js:91:10)

Chrome 44.0.2402 (Mac OS X 10.10.3) forwardRef should wrap and unwrap the reference FAILED
	ReferenceError: unwrapRef is not defined
	    at /Users/misko/Dropbox/work/angular/dist/js/dev/es5/angular2/test/di/forward_ref_spec.js:22:16
	    at Function.$__export.apply (/Users/misko/Dropbox/work/angular/dist/js/dev/es5/angular2/src/facade/lang.js:289:23)
	    at FunctionWithParamTokens.$__export.execute (/Users/misko/Dropbox/work/angular/dist/js/dev/es5/angular2/src/test_lib/test_injector.js:170:29)
	    at Object.<anonymous> (/Users/misko/Dropbox/work/angular/dist/js/dev/es5/angular2/src/test_lib/test_lib.js:91:10)
...............................................................................................................................................................
.
...............................................................................................................................................................
.
...............................................................................................................................................................
.
...............................................................................................................................................................
.
...............................................................................................................................................................
.
...............................................................................................................................................................
.
...............................................................................................................................................................
.
..................................................................
Chrome 44.0.2402 (Mac OS X 10.10.3): Executed 1133 of 1136 (1 FAILED) (skipped 3) (2.143 secs / 1.983 secs)

Chrome 44.0.2402 (Mac OS X 10.10.3): Executed 1133 of 1136 (1 FAILED) (skipped 3) (2.143 secs / 1.983 secs)
[13:40:21] Finished '!test.unit.js/karma-run' after 3.37 s
```

**Comment by IgorMinar** [comment] 2015-05-20 05:32
dupe of #1813

**Closed by IgorMinar** 2015-05-20 05:32 UTC
