### ISSUE TITLE
Router: App base and root routes not working properly

### ISSUE THREAD

**Issue by ludohenin** [angular/angular#5782] opened 2015-12-10 10:38 UTC
Considering this scenario:

```es6
// APP_BASE_HREF set to '/my-app/';
// Use Hash location startegy
// ng2 version = alpha50

@Component({
  selector: 'app',
  template: '<router-outlet></router-outlet>',
  directives: [ROUTER_DIRECTIVES]
})
@RouteConfig([
  { path: '/...', component: SomeCmp, as: 'Some' }
])
export class AppCmp {}


@Component({
  selector: 'some',
  template: '<h1>Yo</h1>',
  directives: [ROUTER_DIRECTIVES]
})
@RouteConfig([
  { path: '/', component: OtherCmp, as: 'Other' },
  { path: '/smthg/:id', component: SomeOtherCmp, as: 'SomeOther' }
])
export class SomeCmp {}
```

Loading  http://.../my-app/ leads to
`/my-app/#/my-app/`  => fine
Then navigating http://.../my-app/smthg/1 leads to
`/my-app/#/my-app//smthg/1` => the extra / does not match any routes, so load fine the first time but page reload and forward button nav are broken.

Am I doing something wrong or is this a bug ?

**Comment by btford** [comment] 2015-12-11 18:52
Looks like a bug. I'll take a look when I can. Thanks!

**Comment by vsavkin** [comment] 2016-07-07 00:36
We are no longer maintaining the deprecated router to focus our efforts on making the new router solid.

Could you reproduce the problem using the new router and submit a separate issue?

Closing this issue.

**Closed by vsavkin** 2016-07-07 00:36 UTC
Labels: comp: router-deprecated, effort2: medium (day), P2: required, type: bug
