### ISSUE TITLE
event.cancelBubble is not respected by (click) event handlers

### ISSUE THREAD

**Issue by jhertz123** [angular/angular#15069] opened 2017-03-10 18:52 UTC
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When implementing a directive that listens to  @HostListener('click', ['$event'])  and event.cancelBubble = true and a (click) is set to the same element as the directive the (click) does not respect the event.cancelBubble but still processes even though the event is first fired in the directive. 

**Expected behavior**

Event should be canceled and not fired in the (click) event.

**Minimal reproduction of the problem with instructions**

1. Create a directive 
2. Implement 
    @HostListener('click', ['$event']) 
    private onClick(event:MouseEvent):void
    {
        console.log("here 1");
        event.cancelBubble = true;
    }
3. Add directive to component
4. Add (click)="console.log('here 2')"
5. Output: 
here 1
here 2

**What is the motivation / use case for changing the behavior?**

You want to stop the standard behavior on for example a long click. 

**Please tell us about your environment:**

Windows 10, Visual Studio Code, Angular CLI 

* **Angular version:** 2.0.X

2.4.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 Chrome 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 2.X
* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment] 2017-03-10 18:57
Duplicate of https://github.com/angular/angular/issues/9587

**Comment by pkozlowski-opensource** [comment] 2017-07-26 09:59
Agree that this is a duplicate of  #9587

**Closed by pkozlowski-opensource** 2017-07-26 09:59 UTC
Labels: comp: core & compiler, type: bug
