### ISSUE TITLE
ngAfterViewChecked endless loop

### ISSUE THREAD

**Issue by jamilalisgandarov** [angular/angular#18332] opened 2017-07-25 21:18 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
ngAfterViewChecked execute function endlessly, I check if img is portrait or landscape and give style for handling it. Tried ngAfterViewInit but did not work as expected so I tried this.  ngAfterViewInit did not work because I use preloader and not showing content till items data is loaded. 
![cdgxpwu3jd](https://user-images.githubusercontent.com/19148254/28594165-0a7cdbc0-71a0-11e7-9d25-c264634e5323.gif)
![bnpor2luvc](https://user-images.githubusercontent.com/19148254/28594448-0e7365ea-71a1-11e7-8026-47802b6b418f.gif)

## Expected behavior
Not to execute endlessly

## Minimal reproduction of the problem with instructions
use ngAfterViewChecked and console.log in it or execute function

## Environment

<pre><code>
Angular version: X.Y.Z
@angular/cli: 1.0.2
node: 6.10.3
os: darwin x64
@angular/common: 4.3.1
@angular/compiler: 4.3.1
@angular/core: 4.3.1
@angular/forms: 4.3.1
@angular/http: 4.3.1
@angular/platform-browser: 4.3.1
@angular/platform-browser-dynamic: 4.3.1
@angular/router: 4.3.1
@angular/cli: 1.0.2
@angular/compiler-cli: 4.3.1
Browser:
- [X ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by robwormald** [comment] 2017-07-25 21:38
It's very difficult to debug images! Please provide a plunker reproduction - template here : plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5

**Comment by jamilalisgandarov** [comment] 2017-07-25 22:01
It is full project that s why I am not able to provide a plunker.

**Comment by vicb** [comment] 2017-07-26 16:51
I'll close the issue as non actionable then.

Please open a new issue if you can create a minimal reproduction of the issue. Thanks.

**Closed by vicb** 2017-07-26 16:51 UTC
Labels: state: Need repro

**Comment by jamilalisgandarov** [comment] 2017-07-26 16:56
Almost same issue here:
[https://github.com/angular/angular/issues/17180](url)

**Comment by gdi2290** [comment] 2017-07-26 23:06
```
    const curr = Zone.current;
    const root = (curr.parent || curr);
    root.run(() => console.log('checked'));
```
the problem is that doing anything async within `ngAfterViewChecked` will cause another render with would run `ngAfterViewChecked` again. to get around this is by making sure you don't cause another render until you need to.
```typescript
ngAfterViewChecked() {
   const currentZone = Zone.current;
   const rootZone = (rootZone.parent || currentZone);
  if (!this.alreadyDidAsyncWork) {
      // don't trigger change-detection
      rootZone.run(() => {
        // do async work
        /*
        xhr.get().then((data) => {
           // make sure to trigger change-detection if you need to
           currentZone.run(() => {
             this.data = data;
             this.alreadyDidAsyncWork = true;
           })

        })
        */
      })
  }
}
```

It's also really important to know that you most likely want to use `ngAfterViewInit` rather than `ngAfterViewChecked`. Anything you do within `ngAfterViewChecked` will most likely be a hacky side-effect and should be avoided. If you do use this you need to be aware of everything that's going on and will likely have a lot of if-statements

**Comment by jamilalisgandarov** [comment] 2017-07-27 09:43
@gdi2290 I am trying to get imgs and do something on them, but when I use ngAfterViewInit elements array comes totally empty. 
P.S I get data from @Input
