### ISSUE TITLE
space added between components when border added to all elements

### ISSUE THREAD

**Issue by kpayson** [angular/angular#37039] opened 2020-05-10 12:19 UTC
This is strange but I can reproduce it.
I added a style * {border:1px solid red} to my page to help in debugging;
This caused margin space to be added between components.

See 
https://codesandbox.io/s/github/kpayson/WeirdSpaceInAngular/tree/master/
https://6puzo.csb.app/

**Comment by pkozlowski-opensource** [comment] 2020-05-10 16:35
Oh, I can see how this could be confusing! Let's decipher what is going on here!

First of all, the issue at hand is pure HTML/CSS one and Angular only plays a limited role here (more on this below). What I mean is that the same issue can be reproduced with just HTML / CSS without Angular at all: https://stackblitz.com/edit/typescript-votpck?file=index.html

The root cause here is that Angular components create _inline_ elements (`<app-foo>`, `<app-bar>`) and you are putting a clock element (`<div>`) inside an inline element which isn't great: "Generally, inline elements may contain only data and other inline elements. You can't put block elements inside inline elements." (source: https://developer.mozilla.org/en-US/docs/Web/HTML/Inline_elements)

You can see that this is the root cause by marking Angular component elements as block ones: https://stackblitz.com/edit/typescript-hlwwnr?file=index.html

So, what is the Angular role in it all? The fact that it uses inline elements for component host nodes! In the past we were discussing display block by default for component elements (ex. #25856). I think that cli now has an opt-in option for this, see: https://github.com/angular/angular-cli/issues/12244

I'm going to close this issue here since an option exists in the CLI - but I definitively see how things can get confusing!

**Closed by pkozlowski-opensource** 2020-05-10 16:35 UTC
