### ISSUE TITLE
Add @AsyncInput decorator to mark input properties as observables

### ISSUE THREAD

**Issue by Malvolio** [angular/angular#20078] opened 2017-11-01 21:00 UTC
# I'm submitting a...

<pre><code>
[ ] Regression 
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

We prefer to use the ON_PUSH change-detection strategy, so we maintain most state in readonly observables rather than mutable properties.  The pattern we currently are considering is

<pre><code>
someInput = new Subject<SomeType>();
@Input('someInput') 
set someInputSetter(value: SomeType) {
  this.someInput.next(value);
};
</code></pre>

and then the component can use it directly as 

<pre><code>
{{someInput | async}}
</code></pre>

## Expected behavior

We could greatly reduce our boilerplate if there were a decorator that encapsulated that pattern, e.g.

<pre><code>
@AsyncInput('someInput') 
someInput = new Subject<SomeType>();
</code></pre>

## Minimal reproduction of the problem with instructions
Here is a silly example:

<pre><code>
@Component({
selector: 'multiply',
template: '{{product | async}}'}
export class Multiply {
  @AsyncInput multiplier = new Subject&lt;number>();
  @AsyncInput multiplicand = new Subject&lt;number>();
  private product: Observable&lt;number>;
  constructor() {
    this.product = Rx.Observable
        .combineLatest(this.multiplier, this.multiplicand,
             (x, y) => x * y);
  }
}
</code></pre>

So
<pre><code>
&lt;multiply 
  [multiplier]="6"
  [multiplicand]="9"
/>
</code></pre>
would render as 
<pre><code>
42
</code></pre>

## What is the motivation / use case for changing the behavior?

Using observables instead of mutable properties increases the efficiency of rendering greatly.  Adding this new decorator will ease using observables and reduce duplicated code.  It also reduces use of lifecycle functions (especially ngOnChange) for most components.

## Environment

<pre><code>
Angular version: 4.2
</code></pre>

**Comment by ericmartinezr** [comment] 2017-11-01 21:19
See https://github.com/angular/angular/issues/5689

**Comment by Malvolio** [comment] 2017-11-01 21:31
@ericmartinezr  -- yes, the suggestion made in [the Plnkr](http://plnkr.co/edit/Nvyd9IPBZp9OE2widOcW?p=preview) was exactly what I had in mind.

The alternative suggestions -- using ngOnChange and writing out a custom setter for each input -- are not nearly as strong.

**Comment by ohjames** [comment] 2017-11-27 21:35
@Malvolio the code in that plunkr only works in certain limited cases, I wouldn't advise using it in a project. A few of the other suggestions are also buggy in that thread, be careful ;)

**Comment by pkozlowski-opensource** [comment] 2019-03-12 14:11
I believe that this is a duplicate of #5689

**Closed by pkozlowski-opensource** 2019-03-12 14:11 UTC
Labels: comp: core & compiler, type: feature
