### ISSUE TITLE
Custom Validator Directive won't fire when signal changes

### ISSUE THREAD

**Issue by acalvomanxa** [angular/angular#55730] opened 2024-05-08 11:31 UTC
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

Yes

### Description

As you can see in the image, I have an input with a custom validator and I send a signal into it.
Inside the validator, I get that value and use it in my validate function. 

The validate function is only called when the input value that has the validator changes, but doesn't when the "entregaName" value changes. I understand that maybe this is not the correct way of doing it, however it's what seems common sense.

My use case is I want to validate an input whenever the users click a button. I can't use async validators because they would fire each time.

In the past I've used the hack of adding a space to the input and then deleting the space with a settimeout, thus activating the validation function, aswell as adding or removing errors from the control programatically, but it doesn't seem like the proper way of doing it.

![image](https://github.com/angular/angular/assets/123938331/951abd8c-160b-4f5f-bda3-8a6b041e8d8a)

![image](https://github.com/angular/angular/assets/123938331/70989be9-79c9-459b-9b8e-864e5b332390)

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.3.5
Node: 18.16.0
Package Manager: npm 9.5.1
OS: win32 x64

Angular: 17.3.5
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, google-maps, material, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1703.5
@angular-devkit/build-angular   17.3.5
@angular-devkit/core            17.3.5
@angular-devkit/schematics      17.3.5
@schematics/angular             17.3.5
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.2
```

**Comment by acalvomanxa** [comment] 2024-05-08 11:35
Another hack I found is the following

![image](https://github.com/angular/angular/assets/123938331/267b5543-cbcf-4e4c-a440-6273da960bb4)

**Comment by alxhub** [comment] 2024-05-08 17:59
Validators are not integrated at all with signals and not expected to be reactive.

**Comment by pkozlowski-opensource** [comment] 2024-08-14 10:53
Signal support in forms is tracked in #53485 

Duplicate of #53485

**Closed by pkozlowski-opensource** 2024-08-14 10:53 UTC
Labels: feature, area: forms, cross-cutting: signals
