### ISSUE TITLE
Wrong error type in httpclient doc

### ISSUE THREAD

**Issue by wildsalarian** [angular/angular#34748] opened 2020-01-12 19:31 UTC
# 📚 Docs or angular.io bug report

### Description
A type was changed in a recent commit in angular which is not yet represented in the docs.

### What's the affected URL?**
https://angular.io/guide/http#getting-error-details

### Reproduction Steps**
In the code snippet app/config/config.service.ts there is this line:

`if (error.error instanceof ErrorEvent) `

In case of a network error (or similar like a CORS error) the error property of the HttpErrorResponse  is should be according to the docs an ErrorEvent. But in my tests always seems to be a ProgressEvent.

In this recent commit 
https://github.com/angular/angular/commit/0139b11227fdd93983a8c6bd870d579d798fa244#diff-26683cfb34fa97883213282055aef1e7
in the file
packages/common/http/src/xhr.ts
the type of the error property of the returned HttpErrorResponse was changed from ErrorEvent to ProgressEvent.

Unfortunately unlike ErrorEvent the ProgressEvent has no message property. It is only usable as a indicator for a network error. The message property of the HttpErrorResponse itself has to be queried to retrieve a human readable error message.

The behaviour can be tested in
https://stackblitz.com/edit/error-handling-httpclient?file=src%2Fapp%2Fuser.service.ts

I am using Angular 8.2.14

**Comment by devversion** [comment] 2020-03-16 11:01
@wildsalarian Thanks for this issue. I think this has always been an issue because the `HttpClient` never emitted an `ErrorEvent`, but instead always used `ProgressEvent`. It was just incorrectly assumed that `ErrorEvent` will be returned (which has been flagged as incorrect by TypeScript in 0139b11)

https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/error_event describes `error` is of type `ProgressEvent`, so I think we should change:

1. Documentation to use `ProgressEvent` in the `instanceof` check (seen in [this guide](https://angular.io/guide/http#getting-error-details))
2. Change `TestRequest` to return `ProgressEvent` instead of `ErrorEvent` (which is incorrect).

This is an interesting question: https://stackoverflow.com/questions/51451508/why-is-a-progressevent-object-passed-to-a-javascript-ajax-error-event-handler.

**Comment by kapunahelewong** [comment] 2020-05-27 18:23
Status: When https://github.com/angular/angular/pull/36082 merges, this will be resolved.

**Comment by HarelM** [comment] 2021-12-09 11:08
I just found out the the problem is not only in the docs.
When I do `err.error instanceof ProgressEvent` I get `false` although when printing to the console I get:
![image](https://user-images.githubusercontent.com/3269297/145385406-d7c92bff-7788-40c1-b9e7-3bb24810896d.png)
The only thing that worked for me was to use (instance of 3):
`err.error.constructor.name === "ProgressEvent"`.
Is anyone else facing this?
Chrome, android, using Cordova webview.

**Comment by cexbrayat** [comment] 2021-12-13 08:57
@devversion Now that #36082 was merged, this can probably be closed?

**Closed** 2021-12-13 12:07 UTC
Labels: type: bug/fix, comp: docs, freq2: medium, state: has PR, triage #1, P3
