### ISSUE TITLE
IE11 form is initially dirty when binding [placeholder] and scrollPositionRestoration is enabled

### ISSUE THREAD

**Issue by k-schneider** [angular/angular#36395] opened 2020-04-02 15:32 UTC
# 🐞 bug report

### Affected Package

The issue is caused by package @angular/forms

### Is this a regression?

Yes, the previous version in which this bug was not present was: v8.x

### Description

When using IE11 forms within `<router-outlet>`'s get marked "dirty" immediately after being intialized when "scrollPositionRestoration" is enabled.  This only occurs when the form contains an `<input>` using `[placeholder]="value"` binding.

## 🔬 Minimal Reproduction

https://github.com/k-schneider/ng9-ie11-bug

## 🔥 Exception or Error
N/A

## 🌍  Your Environment

**Angular Version:**
<pre><code>Angular CLI: 9.1.0
Node: 12.16.1
OS: win32 x64

Angular: 9.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.0
@angular-devkit/build-angular     0.901.0
@angular-devkit/build-optimizer   0.901.0
@angular-devkit/build-webpack     0.901.0
@angular-devkit/core              9.1.0
@angular-devkit/schematics        9.1.0
@ngtools/webpack                  9.1.0
@schematics/angular               9.1.0
@schematics/update                0.901.0
rxjs                              6.5.4
typescript                        3.8.3
webpack                           4.42.0
</code></pre>

**Anything else relevant?**
Only affects IE11.

**Comment by AndrewKushnir** [comment] 2020-04-24 01:13
Hi @k-schneider, thanks for reporting the issue. It looks like it's a duplicate of #15299, so I'll close this one. Please subscribe to the #15299 to receive further updates. Thank you.

**Closed by AndrewKushnir** 2020-04-24 01:13 UTC
Labels: comp: forms
