### ISSUE TITLE
Multiple Ng-container return 'Invalid Argument' on IE 11

### ISSUE THREAD

**Issue by meyer20** [angular/angular#27297] opened 2018-11-27 18:40 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

I'm processing two containers with different data, in Chrome and Firefox works fine, but in IE 11 only the first container work, the second shows does not display the inserted texts, only the declared html elements. In the browser console, the invalid argument error is displayed. Is there any contour measure for this situation?

https://imgur.com/a/vBRcxLx

## 🔬 Minimal Reproduction
https://angular-ednchp.stackblitz.io 
Open in IE 11 and see the console. In my case, the first container is rendered, but the second one is not displayed and returns the error. PS: By Stackblitz both containers are rendered, but the error is displayed. In my case only one error is displayed and the second container is not displayed correctly.

## 🔥 Exception or Error
<pre><code>
ERROR Error: Argumento inválido.
ERROR CONTEXT [object Object]

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
"@angular/common": "~5.2.1",
"@angular/compiler": "~5.2.1",
"@angular/core": "~5.2.1",
--------------------------------
"@angular/cli": "^1.6.8",
"@angular/compiler-cli": "^5.2.1",
</code></pre>

**Comment by okeefem2** [comment] 2018-11-28 18:30
Hi there @meyer20! 

I was able to get your code to work by changing how you were binding the `customMessage` value to your textarea.

The error is occurring because you are binding to the value property on the textarea and interpolating the variable value in between the tags. the [content between the tags of a textarea is also the value](https://www.w3schools.com/jsref/prop_textarea_value.asp) so you are only able to bind through one of these methods, using both is causing the issue.

I don't believe this is an issue with Angular itself,  but is the expected behavior of a textarea.

**Comment by pkozlowski-opensource** [comment] 2018-11-28 18:44
Oh, thnx so much @okeefem2 for the detailed investigation! Totally agree with your assessment - one should manipulate texarea's content on one place only. I guess the issue is more visible in IE as it gets more "upset" about it.

Closing as invalid / browser specific behaviour.

**Comment by meyer20** [comment] 2018-11-28 18:45
@okeefem2 thank you for your reply.
His answer fixed the problem.

Thanks :)

**Closed by pkozlowski-opensource** 2018-11-28 18:44 UTC
Labels: comp: common
