### ISSUE TITLE
Custom Http not working with SSR

### ISSUE THREAD

**Issue by kukjevov** [angular/angular#15278] opened 2017-03-18 15:04 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When you create custom `Http` it is working in browser, but when you use it in NodeJs environment while rendering on server it never performs `HttpRequest`. 

**Expected behavior**
Custom `Http` should work on browser or server side.

**Minimal reproduction of the problem with instructions**
https://github.com/kukjevov/ng-universal-demo You can see it in master branch. There is a custom `Http` which works on client, but not on server. 

There are console logs, but log in `subscribe` method which prints result is only called on browser side if used with custom `Http`. If you use original `Http` log is also called on server and data are rendered to html. 

From logs you can see that custom `GET` method is called but that is all. You cant even see 
`GET: /data: 3.005ms` on server side if custom `Http` is used. So that means url was never called. 
-->

**Please tell us about your environment:**
Win 10, VSCode, Express Server

* **Angular version:** 4.0.0-rc.5

* **Browser:** [all]
 
* **Language:** [TypeScript 2.2.1]

* **Node (for AoT issues):** `node --version` =   7.7.1

**Comment by kukjevov** [comment] 2017-03-19 17:46
Well i did some deeper investigation and it looks like different problem. 

Actually Http calls runs as expected, but this code:
```
const applicationRef: ApplicationRef = moduleRef.injector.get(ApplicationRef);
    return toPromise
        .call(first.call(filter.call(applicationRef.isStable, (isStable: boolean) => isStable)))
        .then(() => {
          const output = platform.injector.get(PlatformState).renderToString();
          platform.destroy();
          return output;
});
```
which renders html runs before async http operation finish. It simply does not wait for this operation to finish. Interesting is that this is not problem with original HTTP, but with custom HTTP it happens in wrong order. That is reason why you dont see results of http requests rendered from server side.

**Comment by kukjevov** [comment] 2017-03-19 17:57
I have updated repository https://github.com/kukjevov/ng-universal-demo, last commit in master branch illustrates this problem better. Before i was using `AsyncPipe` which never called subscribe, because bootstraping was finished and therefore http was never called. 

But now in example i`m using explicit subscribe and now you can see, that angular does not wait for xhr requests to finish if used with custom `Http`.

I hope this helps. This bug kind of disables using custom http on server, or you will not have data from server.

**Comment by kukjevov** [comment] 2017-03-20 14:31
Hi,

i have found problem and solution is quite easy. Can you please make `ZoneMacroTaskBackend` public api. I figured out that it cant automatically know that something is running asynchronously. I looked at your factory and i can see that you created `XhrBackend` which is tracked by zone using special backend class `ZoneMacroTaskBackend`. When i copied all your code that is in `@angular/platform-server/src/http` and used it for creating my custom `Http` it works like a charm.

Can you make that class `ZoneMacroTaskBackend` part of public api for `@angular/platform-server`. It will solve this issue. It would be great if it make it into next version.

Thank you very much

**Comment by alxhub** [comment] 2017-03-20 21:27
Hello @kukjevov,

Unfortunately we cannot make `ZoneMacroTaskBackend` public, as it is an implementation detail and not a class we plan to support as part of our public API.

However, as you've found, the technique `ZoneMacroTaskBackend` uses - wrapping outgoing requests in a Zone macrotask - is how to delay rendering until they complete. Having your own version of the logic in `ZoneMacroTaskBackend` is the correct solution.

**Comment by kukjevov** [comment] 2017-03-21 07:40
Hello :).

Well i dont see any reason why you cant make `ZoneMacroTaskBackend` public, but ok :). I think it is reinventing wheel since everybody will just copy your code. 

If you dont want to make it public, maybe other solution can be done.

But in the meantime, where can i get (types) d.ts for types that are used in that code. I am missing two types like `Task` and `Zone.current`. To make it compilable i had to change `Task` to `any` and create `declare var Zone: any;`.

Any solution that does not include duplicating of code will be welcomed :).
Anyway thank you for great job

**Comment by vikerman** [comment] 2017-03-31 03:01
Closing this issue. Please re-open if there is still an issue.

**Closed by vikerman** 2017-03-31 03:01 UTC
Labels: comp: server, type: bug

**Comment by kukjevov** [comment] 2017-03-31 05:13
Hello.

I cant say it was solved, because solution is "borrow" code from your code, so it is more like workaround, but it is working. Since i see, that you dont want to do anything about it we can keep it closed. 

But problem with this "solution" is if you change your code it will not reflect changes in our code, so updating zone.js, or angular can break code without knowing that.

**Comment by alxhub** [comment] 2017-04-01 03:45
@kukjevov, making something public means we commit to maintaining it over time and not ever breaking consumers of it. It's a maintenance burden that we carefully evaluate. In this case, `ZoneMacroTaskBackend` is a utility that really has nothing to do with `@angular/platform-server`, so it doesn't really belong as part of its public API.

**Comment by mahmood-sajjadi** [comment] 2017-04-18 21:59
@alxhub is there any other method to communicate with platform server? I have the same issue and but I want to have a full control over my Http calls on platform server.(some of them should be resolved on the server and some of them should be ignored). and the @kukjevov solution is not clear for me! is there any event that we can fire like AsyncFinished? or some sort of notation like required or optional on top of Async functions?

**Comment by alirezamirian** [comment] 2017-08-30 15:18
I think the root of the problem is that we need to explicitly pass a certain type of `ConnectionBackend` to be able to extend http service. I don't expect to get **no provider for ConnectionBackend** when I'm just using a class provider which has `ConnectionBackend` in its argument list. 
I'm not sure if I'm right or not because I've not read the code, but I think `HttpModule` provides `XHRBackend` and `ServerModule` provides `ZoneMacroTaskBackend` and I expect to be able to just ask for a `ConnectionBackend` and the correct one get passed to me.

**Comment by alirezamirian** [comment] 2017-08-30 15:49
`Http` provider in `HttpModule`:
```
export function httpFactory(xhrBackend: XHRBackend, requestOptions: RequestOptions): Http {
  return new Http(xhrBackend, requestOptions);
}
```
`Http` provider in `HttpModule`:
```
export function httpFactory(xhrBackend: XHRBackend, options: RequestOptions) {
  const macroBackend = new ZoneMacroTaskBackend(xhrBackend);
  return new Http(macroBackend, options);
}
```
`HttpModule` provides `XHRBackend` while `ServerModule` doesn't provide `ZoneMacroTaskBackend` as `XHRBackend`,

**Comment by alirezamirian** [comment] 2017-08-30 21:08
I think `ServerModule` should not use `new` to instantiate a `ZoneMacroTaskBackend`, and instead it should provide it under `XHRBackend` DI token, to enable others to create services that extend `Http` just by asking for `XHRBackend`.
However, I'm using a workaround for now to solve the problem while avoiding [copying `ServerModule` codes](https://github.com/angular/angular/issues/15278#issuecomment-287776755):
In my factory function for custom http service, instead of asking for `XHRBackend`, I ask for `Http` service which is instantiated with correct `ConnectionBackend` both in browser and server. Then I'm using it's protected member `_backend`, to get a hold of correct `ConnectionBackend`:
```ts
export function httpFactory(http: Http, defaultOptions: RequestOptions)
{
    return new MyCustomHttp( (<any>http)._backend, defaultOptions);
}
```
Of course it's far from ideal, but at least it has less footprint than the previous solution.

**Comment by alxhub** [comment] 2017-08-30 21:19
@alirezamirian you're on the right track with regards to why it's not working. Unfortunately custom `Http` implementations are not a supported use case in Angular - the instantiation of `Http` is highly fragile and you can't override internal pieces via DI and have it continue working, you have to do what you're doing and provide it via a factory that instantiates it directly.

Alternatively, you could switch to `HttpClient` (as `Http` will be deprecated in 5.0) and take advantage of interceptors instead of wrapping the interface yourself.

**Comment by asgerjensen** [comment] 2017-09-27 21:27
@alirezamirian so how do you inject this in place of the regular Http service?  If i use
```
    {
      provide: Http,
      useFactory: createTraceableHttpService,
      deps: [Http, RequestOptions]
    }
```
I get a cyclic dependency error.

or did you create a new token
```
    {
      provide: MyHttp,
      useFactory: createTraceableHttpService,
      deps: [Http, RequestOptions]
    }
```
which you then DI instead of Http?

**Comment by alirezamirian** [comment] 2017-09-28 14:52
@asgerjensen 
I created a new token. In my use case, I didn't want my custom extended http service to be served as `Http` DI token. I wanted to have an `ApiClient` service which extends `Http`.
