### ISSUE TITLE
ContentChildren doesn't support recursive usage of ng-template

### ISSUE THREAD

**Issue by mjswensen** [angular/angular#26061] opened 2018-09-21 17:12 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

`@ContentChildren` does not support the recursive use of `<ng-template>`.

## Expected behavior

`@ContentChildren` should provide a `QueryList` that access *all* the descendants matching the given selector, even when some of those children come from the recursive stamping-outs of an `<ng-template>`.

## Minimal reproduction of the problem with instructions

Full reproduction of the problem can be found at https://codesandbox.io/s/y733q4q31v. Here is a screenshot below. Notice how on the first two examples the numbers of descendants (listed in dark red text above each list and sub-list) are not accurate.

![y733q4q31v codesandbox io_](https://user-images.githubusercontent.com/1591879/45895591-d583f200-bd8e-11e8-9bc1-f65c68224835.png)

## What is the motivation / use case for changing the behavior?

I am recursively building a tree structure of checkboxes where each parent node should be able to access the state of all descendent nodes. Something like this:

<img width="461" alt="screen shot 2018-09-21 at 10 58 52 am" src="https://user-images.githubusercontent.com/1591879/45895041-62c64700-bd8d-11e8-90ec-076f264c4ee6.png">

## Environment

<pre><code>
Angular version: reproduced on both 5.2 and 6.03

Browser:
- [x] Chrome (desktop) version XX
- [x] Chrome (Android) version XX
- [x] Chrome (iOS) version XX
- [x] Firefox version XX
- [x] Safari (desktop) version XX
- [x] Safari (iOS) version XX
- [x] IE version XX
- [x] Edge version XX
 
For Tooling issues:
- Node version: All
- Platform: All

</code></pre>

Thank you for your time!

**Comment by mlc-mlapis** [comment] 2018-09-22 09:04
@mjswensen ... known problem ... read https://github.com/angular/angular/issues/14769#issuecomment-356609267 first.

**Comment by pkozlowski-opensource** [comment] 2020-05-29 09:25
@mjswensen thnx sooooo much for opening this issue and sharing your use-case. I can definitively see how we are lacking good support for what you are trying to do :-(   At the end of a day it all boils down to the fact that we don't descend (grab content from) templates inserted dynamically (ex. via `ngTemplateOutlet`. This issue is really another manifestation of #14842 so I'm going to close this one as a duplicate of #14842

**Closed by pkozlowski-opensource** 2020-05-29 09:25 UTC
Labels: comp: core, core: queries, freq1: low, severity2: inconvenient, type: use-case
