### ISSUE TITLE
Update Guide (5.2->7.0) `preserveWhitespaces` step breaks RxJS upgrade step

### ISSUE THREAD

**Issue by gempain** [angular/angular#27265] opened 2018-11-26 08:42 UTC
# 📚 Docs or angular.io bug report

### Description

Upgrade guide from 5.2 -> 7.0 tells to set `preserveWhitespaces` to `off` in `tsconfig.json`, which breaks the step for updating RxJS with the following command `rxjs-5-to-6-migrate -p src/tsconfig.app.json`.

### What's the affected URL?
https://update.angular.io

### Reproduction Steps
1. `preserveWhitespaces` to `off` in `tsconfig.json`
2. Run `npm install -g rxjs-tslint`
3. Run `rxjs-5-to-6-migrate -p src/tsconfig.app.json`

### Expected vs Actual Behavior
**Expected:**
The migration should run smoothly and output the following to the console:
```
Running the automatic migrations. Please, be patient and wait until the execution completes.
Found and fixed the following deprecations:

Fixed 1 error(s) in /Users/geoffroy/dev/git/qos3/web-app/src/app/core/helpers.ts
...
```
**Actual:**
The migration throws an error.

## 🔥 Exception or Error
<pre><code>Running the automatic migrations. Please, be patient and wait until the execution completes.
child_process.js:645
    throw err;
    ^

Error: Command failed: "~/my-app/node_modules/rxjs-tslint/node_modules/.bin/tslint" -c "~/my-app/node_modules/rxjs-tslint/rxjs-5-to-6-migrate.json" -p "src/tsconfig.app.json" --fix
    at checkExecSyncError (child_process.js:602:13)
    at Object.execSync (child_process.js:642:13)
    at migrate (~/my-app/node_modules/rxjs-tslint/rxjs-5-to-6-migrate.js:18:34)
    at Object.<anonymous> (~/my-app/node_modules/rxjs-tslint/rxjs-5-to-6-migrate.js:25:14)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)</code></pre>

**Comment by jenniferfell** [comment] 2018-11-27 23:14
@jasonaden @benlesh FYI... ^ This content is owned by @StephenFluin, so I assigned the issue to him, but if you have any advice or comments feel free to chime in. Thx.

**Comment by manughub** [comment] 2018-11-27 23:29
@mgechev - could you pls take a look at this ? You wrote the tslint I think.

**Comment by mgechev** [comment] 2018-11-28 00:00
Since I cannot reproduce the issue locally, I published `rxjs-tslint@0.1.6` which will let us inspect the error message thrown by the child process.

@gempain would you try the latest published version and share the output.

**Comment by gempain** [comment] 2018-11-28 08:51
@mgechev thanks for diving in. Here is the output (which confirms the issue I guess):

```
$ npm install -g rxjs-tslint
/usr/local/bin/rxjs-5-to-6-migrate -> /usr/local/lib/node_modules/rxjs-tslint/bin/rxjs-5-to-6-migrate
npm WARN rxjs-tslint@0.1.6 requires a peer of tslint@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN rxjs-tslint@0.1.6 requires a peer of typescript@>=2.1.0 || >=2.1.0-dev || >=2.2.0-dev || >=2.3.0-dev || >=2.4.0-dev || >=2.5.0-dev || >=2.6.0-dev || >=2.7.0-dev || >=2.8.0-dev || >=2.9.0-dev but none is installed. You must install peer dependencies yourself.

+ rxjs-tslint@0.1.6
added 1 package from 1 contributor and updated 1 package in 2.39s
$ rxjs-5-to-6-migrate -p src/tsconfig.app.json
Running the automatic migrations. Please, be patient and wait until the execution completes.
Error whilee running the migration: ,tsconfig.json(18,5): error TS5023: Unknown compiler option 'preserveWhitespaces'.

,
```

**Comment by gempain** [comment] 2018-11-28 08:53
@mgechev thanks for diving in. Here is the output (which confirms the issue I guess):

```
$ npm install -g rxjs-tslint
/usr/local/bin/rxjs-5-to-6-migrate -> /usr/local/lib/node_modules/rxjs-tslint/bin/rxjs-5-to-6-migrate
npm WARN rxjs-tslint@0.1.6 requires a peer of tslint@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN rxjs-tslint@0.1.6 requires a peer of typescript@>=2.1.0 || >=2.1.0-dev || >=2.2.0-dev || >=2.3.0-dev || >=2.4.0-dev || >=2.5.0-dev || >=2.6.0-dev || >=2.7.0-dev || >=2.8.0-dev || >=2.9.0-dev but none is installed. You must install peer dependencies yourself.

+ rxjs-tslint@0.1.6
added 1 package from 1 contributor and updated 1 package in 2.39s
$ rxjs-5-to-6-migrate -p src/tsconfig.app.json
Running the automatic migrations. Please, be patient and wait until the execution completes.
Error whilee running the migration: ,tsconfig.json(18,5): error TS5023: Unknown compiler option 'preserveWhitespaces'.

,
```

If I remove the `preserveWhitespaces` in my `tsconfig.json` everything works fine. May be I added the property at the wrong place ?

```
{
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2017",
      "dom"
    ],
    "preserveWhitespaces": "off"
  }
}
```

**Comment by mgechev** [comment] 2018-11-28 14:12
`preserveWhitespaces` should be under the top-level property `angularCompilerOptions`.

Would you double check with this configuration. If everything works as expected, I'll update the migration docs.

**Comment by gempain** [comment] 2018-11-28 15:16
@mgechev yup, that was it ! Thanks for the help :) I would definitely suggest updating the docs and mentioning that the property needs to be placed at the top level. I assumed it should be placed under `compilerOptions` but was wrong.

By the way, just wanted to say that this upgrade guide is, IMHO, the most helpful tool I have seen in any framework since started programming. Keep up the great work.

**Comment by mgechev** [comment] 2018-11-28 18:12
I'll assign this issue to @StephenFluin, he'll be the right person to update https://update.angular.io.

**Closed** 2018-11-30 04:44 UTC
Labels: comp: docs, comp: misc, freq4: critical, severity3: broken, state: needs devrel input, subtype: docs-versioncompat, type: bug/fix

**Comment by mtpultz** [comment] 2019-03-13 18:31
@gempain can you post the final placement of `preserveWhitespace` and value?  @mgechev the steps haven't been updated yet, and during my research to find a solution I read that it should be set to a boolean not `off` - https://github.com/angular/angular-cli/issues/10859#issuecomment-390808375.  Also, which tsconfig file since that issue also says it should be set in `tsconfig.app.json`?

**Comment by charliebravodev** [comment] 2019-03-14 08:35
@mtpultz I don't know whether the PR was merged in yet, but you can [preview it](https://github.com/StephenFluin/angular-update-guide/pull/23/commits/3774a2db73154017d20de7de906591a2ceca655b). Here's how you set the property:

**tsconfig.json**
```
{
  "compilerOptions": {
    ...
  },
  "angularCompilerOptions": {
    "preserveWhitespaces": "off"
  }
}

```
