### ISSUE TITLE
/rxjs/observable/PromiseObservable.d.ts(10,26): error TS2304: Cannot find name 'Promise'.

### ISSUE THREAD

**Issue by RunningV** [angular/angular#7622] opened 2016-03-16 09:05 UTC
* **What is the expected behavior?**
1、node_modules/rxjs/Observable.d.ts(201,66): error TS2304: Cannot find name 'Promise'.
2、node_modules/rxjs/observable/FromObservable.d.ts(7,51): error TS2304: Cannot find name 'Iterator'.

* **Please tell us about your environment:**

- Angular version: 2.0.0-beta.9
- Browser: [Chrome 48.8
- Language: [TypeScript 1.8.7]

**Comment by laco0416** [comment] 2016-03-16 10:37
Your RxJS version is 5.0.0-beta.2? Please check dependencies.

**Comment by RunningV** [comment] 2016-03-18 03:26
yes , RxJS version is 5.0.0-beta.2 ;and in angular2.0.0-beta-9 when i add "node_modules/angular2/typings/browser.d.ts" to the bootstrap file, thing seems to be resolved; but when a use inoic start xxx to build a ionic2 project,it's angular2beta6, i add the "node_modules/angular2/typings/browser.d.ts", it became worse like this 

<code>
ERROR in [default] E:/Running/angular2.0/ionic2/tutorial-ionic2/node_modules/ang              ular2/src/facade/promise.d.ts:1:9
Cannot re-export name that is not defined in the module.

ERROR in [default] node_modules/angular2/typings/es6-collections/es6-collections              .d.ts:22:4
Duplicate identifier 'done'.

ERROR in [default] node_modules/angular2/typings/es6-collections/es6-collections              .d.ts:23:4
Duplicate identifier 'value'.

ERROR in [default] node_modules/angular2/typings/es6-collections/es6-collections              .d.ts:46:4
Duplicate identifier 'size'.

</code>

it's alse the "promise" question ,how shoule i do?

**Comment by laco0416** [comment] 2016-03-18 03:40
It's a type definition collision problem. ng2 beta.9 depends on rxjs beta.2, but ng2 beta.6 depends on rxjs beta.0. 
I don't know about ionic2 well. but I think you have to install ng2 beta.6 explicitly into your project if ionic2 depends on ng2 beta.6.

**Comment by scastaldi** [comment] 2016-04-29 02:51
Just need to add, this line in  main.ts

/// <reference path="../node_modules/angular2/typings/browser.d.ts" />

**Comment by Raziaar** [comment] 2016-06-26 10:59
I'm still getting these errors with every version of Angular I install. RC1, RC2, RC3. I've been dealing with this issue since early beta and I don't know how I can resolve it.

It's fine when I initially run gulp, but if I make any change to any of my typescript files it gives me hundreds of errors. If I save again, it's fine. It doesn't impact anything but I'm tired of seeing these errors flood my screen.

**Comment by vicb** [comment] 2016-06-26 15:05
Please provide a repro case

**Comment by vicb** [comment] 2016-07-22 16:21
Closing, no repro case

**Closed by vicb** 2016-07-22 16:21 UTC
Labels: flag: can be closed?

**Comment by moshmage** [comment] 2016-12-17 18:57
@vicb I have a repor with a branch reproducing the same error https://gitlab.com/moshmage/rxjs-socket.io/tree/creating-tests
