### ISSUE TITLE
i18n docs does not provide solution for working with text in code

### ISSUE THREAD

**Issue by born2net** [angular/angular#14147] opened 2017-01-27 16:38 UTC
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

**Current behavior**
docs:  https://angular.io/docs/ts/latest/cookbook/i18n.html
show only how to work with template via
```<p i18n>foo</p>```

would like the recommended way to work with strings when eval in code:

```var foo = 'Hello world' ```

**Expected behavior**
so maybe
```var foo = '<i18n>Hello world' ``` ?

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

Angular 2 Kitchen sink: http://ng2.javascriptninja.io
and source@ https://github.com/born2net/Angular-kitchen-sink
Regards,

Sean

**Comment by mlaval** [comment] 2017-01-27 17:34
Thanks for reporting this issue. However this issue is a duplicate of an existing issue: https://github.com/angular/angular/issues/11405. Please subscribe to that issue for future updates.

**Closed by mlaval** 2017-01-27 17:34 UTC
