### ISSUE TITLE
angular2 Chinese input 

### ISSUE THREAD

**Issue by hanxinimm** [angular/angular#3352] opened 2015-07-29 10:25 UTC
Here is the plunker : http://plnkr.co/edit/K7ZW4e?p=preview
I Think The Input Value Change After a KeyPress Event.
![bug1](https://cloud.githubusercontent.com/assets/13499426/8955418/1ff0db82-361f-11e5-9150-47c6e15f7f5f.png)
![bug2](https://cloud.githubusercontent.com/assets/13499426/8955421/27530558-361f-11e5-97fc-4922c54bb972.png)

**Comment by mhevery** [comment] 2015-08-05 16:20
I don't see anything wrong. Can you describe steps to reproduce, and what is the expected vs actual behavior?

**Comment by mhevery** [comment] 2015-08-19 17:51
Lack of reproducible steps, closing.

**Closed by mhevery** 2015-08-19 17:51 UTC

**Comment by tapopov** [comment] 2017-03-14 14:09
@mhevery, this is still an issue and is reproduced easily using the example @hanxinimm provided. 
Simply switch the input language to Simplified Chinese and start typing. In [this](https://www.screencast.com/t/eUVWAM3dL) screencast you can see the behavior in action. Also, selecting the entire text and pressing backspace does not delete all characters as expected.

**Comment by mhevery** [comment] 2017-03-22 17:09
What are the exact steps to reproduce it? What is expected and actual at each step. 

/cc @kara

**Comment by kara** [comment] 2017-03-22 17:33
@tapopov Hmm I'm not able to reproduce this with a Chinese keyboard. In the screencast, it looks like selecting the Chinese character fills the text field with repeating English characters. I'm not seeing this behavior when I use my Chinese keyboard with any of the form directives. Can you provide some sample code? Also, are you using a particular platform or keyboard?
