### ISSUE TITLE
Type Parameter is not rendered in the docs

### ISSUE THREAD

**Issue by destus90** [angular/angular#41711] opened 2021-04-20 04:56 UTC
# 📚 Docs or angular.io bug report

### Description

There is an issue with viewing the docs as a generic`s type parameter is not visible.

### What's the affected URL?**

https://angular.io/guide/structural-directives#making-in-template-type-requirements-more-specific-with-template-guards

### Reproduction Steps**

Look at `IfLoadedDirective` code example.

### Expected vs Actual Behavior**
Type parameter is visible.

## 📷Screenshot

![image](https://user-images.githubusercontent.com/17944366/115339609-8e687280-a1be-11eb-9a9b-d7b6b6c51d9d.png)

### Browser info
Chrome v.89

**Comment by JoostK** [comment] 2021-04-20 07:33
Duplicate of #40739.

**Closed by JoostK** 2021-04-20 07:33 UTC
