### ISSUE TITLE
Contradictory guidelines in Style 05-18 (strictPropertyInitialization)

### ISSUE THREAD

**Issue by amakhrov** [angular/angular#46420] opened 2022-06-17 20:10 UTC
### Description

It says
> You may want to have a required @Input field, meaning all your component users are required to pass that attribute. In such cases, use a default value

But if we can define a reasonable default value - doesn't it automatically mean we have made the input optional? And if a component user doesn't pass this input, our component still works just fine.

I'm aware that a concept of "required" inputs has been discussed in the past (https://github.com/angular/angular/issues/11904, https://github.com/angular/angular/issues/18156, https://github.com/angular/angular/issues/24879, https://github.com/angular/angular/issues/28403, https://github.com/angular/angular/issues/30974).

Yet the recommendation in the styleguide doesn't seem to properly describe it and provide a path forward.

### What is the affected URL?

https://angular.io/guide/styleguide#style-05-18

**Comment by Yogu** [comment] 2022-07-06 16:33
The closes thing to an official guideline on how to do required properties is [this comment](https://github.com/angular/angular/issues/18156#issuecomment-316233637) by @alxhub from five years ago

> @trotyl's example is a recommended way to have a required `@Input`

referencing this example:

> ```typescript
> @Component({
>    selector: 'app-username[id]'
>})
> ```

However, I am really reluctant do do this in my framework components because if the input is omitted, users will get the error "... is not a known element", with no indication of what is really wrong. So if this is still the officially recommended way, I will open an issue to improve this error message. There are complex possible cases with multiple directives matching, or directives without element selector. But if there is exactly one component that matches the element selector, but needs more inputs, the error message should just be "Element ... is missing attribute ..." or something similar.

The five-year-old comment also included

>  If the @Input is properly typed we should be able to enforce strict null checks against it (not sure if we do currently, but we should be able to).

I do not know exactly what he meant. The selector does not affect type checking within the component. You can use the non-null-assertion-operator to fix it, but the styleguide discourages it. It also is not validated against the selector, and it is technically still incorrect because the input will not be assigned until `ngOnInit` is called (so it's undefined in the constructor).

The second option would be to allow `undefined` in the input type (e.g. with `?` or by adding `| undefined` to the type) - but then the user is allowed to pass `undefined` for the input, which is not desirable (and automatically generated documentation would also include `undefined` as a valid option).

The third option is to specify a default value (the suggestion from the styleguide), but as you rightly point out this does not make sense for a mandatory input, because after all, a mandatory input is one where there is no default value.

I'm not sure if there even is a good solution to this, the problem is kind of baked into the Angular fundamentals. But I think the recommendation could indeed be to add the required inputs to the selector if the error message was improved (see above) and use the non-null-assertion-operator on these inputs. This would at least allow a library author to write good components.

**Comment by Yogu** [comment] 2023-03-16 20:06
I just noticed [required inputs landed in angular 16](https://github.com/angular/angular/pull/49304). This is great! Should we update the part about required inputs in [the styleguide](https://next.angular.io/guide/styleguide#style-05-18) then?

**Comment by JeanMeche** [comment] 2024-02-06 17:45
Hi, we will track this under the #54284 umbrella issues, thank you for your suggestions !

**Closed by JeanMeche** 2024-02-06 17:45 UTC
Labels: area: core, core: inputs / outputs, P3
