### ISSUE TITLE
replaceUrl doesn't works when using relativeTo

### ISSUE THREAD

**Issue by gilsdav** [angular/angular#30695] opened 2019-05-28 09:25 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/router

### Is this a regression?

 Don't know but doesn't works in any minor version of 7

### Description
New state is pushed in history.

When this works fine:
<pre><code>
this.router.navigate(['/login'], { queryParams: {}, replaceUrl: true});
</code></pre>
This doesn't work as expected:
<pre><code>
this.router.navigate(['.'], { relativeTo: this.route, queryParams: {}, replaceUrl: true});
or
this.router.navigate([''], { relativeTo: this.route, queryParams: {}, replaceUrl: true});
</code></pre>

Workaround:
<pre><code>
this.router.navigate([this.router.url.split('?')[0]], { queryParams: {}, replaceUrl: true });
</code></pre>

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-wshy3c
Test url https://angular-wshy3c.stackblitz.io/login?bob=coucou

In stackblitz there is an other error: `replaceUrl` works but not `relativeTo`

## 🔥 Exception or Error
<pre><code>
No errors in console
</code></pre>

## 🌍  Your Environment

**Angular Version:**
Also tried in 7.2.15 
<pre><code>
Angular CLI: 7.1.4
Node: 10.7.0
OS: darwin x64
Angular: 7.1.4
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.11.4
@angular-devkit/build-angular     0.11.4
@angular-devkit/build-optimizer   0.11.4
@angular-devkit/build-webpack     0.11.4
@angular-devkit/core              7.1.4
@angular-devkit/schematics        7.1.4
@angular/router                   7.1.4
@ngtools/webpack                  7.1.4
@schematics/angular               7.1.4
@schematics/update                0.11.4
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.23.1

</code></pre>

**Anything else relevant?**

**Comment by artem-galas** [comment] 2019-06-12 19:34
I guess issue somewhere into [createUrlTree](https://github.com/angular/angular/blob/master/packages/router/src/create_url_tree.ts#L14) method I guess it's `computeNavigation` or `findStartingPosition` calls.

I'm thinking one of these methods should change `['.']` to `activatedRoute.snapshot.url`. 

For instance (`['.']` -> `['/a']`):

Am I on the right direction?

**Comment by frankadrian** [comment] 2019-10-22 20:17
Hi @gilsdav,
It looks like you want to get the queryParam (bob) from the initial route to your application and remove it afterward. 
The way I'm seeing it, at the time of your subscription, the activeRoute is still set to the AppComponent. So you tell it to navigate to '' route of AppComponent, which in your case resolves to /.

Please see the updated Stackblitz:
I added 'login' as the path and it redirects you to the login page with no queryParams.
This is because at the stage your Route's Params Subscriber (in AppComponent) runs the HelloComponent was not yet resolved by the router. 

If you set `replaceUrl` it will result in /login beeing the only route in your history.

Updated Stackblitz:
https://stackblitz.com/edit/angular-xawgew?file=src/app/app.component.ts
Test url:
https://angular-xawgew.stackblitz.io/login?bob=yay

**Comment by jkossis** [comment] 2020-04-21 10:59
Any movement on this?

**Comment by atscott** [comment] 2020-07-08 20:22
Based on the description, this seems to be working as intended. As explained by @frankadrian, the navigation is triggered relative to the root activated route and the URL is getting replaced with that root `/`.
If you still feel there is an issue, please provide further details in a new issue.

**Closed by atscott** 2020-07-08 20:22 UTC
Labels: comp: router, freq3: high, hotlist: community-help, severity3: broken, type: bug/fix

**Comment by gilsdav** [comment] 2020-07-08 20:29
@atscott 
The problem is that I don't know to where I need to redirect (the same url). I only need to clear queryParams.
So why ['.'] doesn't work ?

**Comment by atscott** [comment] 2020-07-08 21:53
@gilsdav - Note that you can use `this.router.navigate([], { queryParams: {}, replaceUrl: true});` for your case. When the commands array is empty, the router will use the `currentUrlTree` as the basis for navigation
https://stackblitz.com/edit/angular-vxxtul
https://github.com/angular/angular/blob/1237d9cbea39da36dfedc884ae36c12a04addd85/packages/router/src/create_url_tree.ts#L17-L18

**Comment by gilsdav** [comment] 2020-07-08 22:02
Oh that's the information I needed ! Thank's so to do this we don't have to set the `relativeTo` option.
Thank you for you investigation 😄
