### ISSUE TITLE
Add support for typescript 2.7.1

### ISSUE THREAD

**Issue by dhniels** [angular/angular#21972] opened 2018-02-01 19:14 UTC
## I'm submitting a...
<pre><code>
[x] Bug report
[x] Feature request
</code></pre>

### Versions
```
<!--
Angular CLI: 1.6.7
Node: 9.3.0
OS: darwin x64
Angular: 5.2.3
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

@angular/cli: 1.6.7
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.29
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.7
@schematics/angular: 0.1.17
typescript: 2.7.1
webpack: 3.10.0
-->
```

### Error Mesage:
Updated all my npm packages yesterday which updated typescript to 2.7.1. Angular CLI now produces this warning:

```
@angular/compiler-cli@5.2.3 requires typescript@'>=2.4.2 <2.7.0' but 2.7.1 was found instead.
Using this version can result in undefined behaviour and difficult to debug problems.

Please run the following command to install a compatible version of TypeScript.


    npm install typescript@'>=2.4.2 <2.7.0'

To disable this warning run "ng set warnings.typescriptMismatch=false".
```

### Repro steps
Found when running `ng build --watch` on latest typescript version 2.7.1

### Desired behavior
Update Angular to support typescript 2.7.1 should resolve the issue?

**Comment by sandangel** [comment] 2018-02-01 19:35
duplicate of #21571

**Comment by IgorMinar** [comment] 2018-02-05 04:21
please follow #21571 (thanks @sandangel)

**Closed by IgorMinar** 2018-02-05 04:21 UTC
Labels: comp: core & compiler
