### ISSUE TITLE
HttpClient not supporting in memory web api

### ISSUE THREAD

**Issue by mmc41** [angular/angular#18150] opened 2017-07-15 15:12 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
The old http module supported an in memory web api using "angular-in-memory-web-api" which is extremely useful for testing and development. 

## Expected behavior
The new HttpClient does not support an in memory web api. This is blocking it's use.

## Environment

<pre><code>
Angular version: 4.3.0

**Comment by notsonotso** [comment] 2017-07-17 00:55
Duplicate of https://github.com/angular/in-memory-web-api/issues/122

**Comment by Foxandxss** [comment] 2017-07-17 09:16
Closing as duplicate and not belonging to this repo.

**Closed by Foxandxss** 2017-07-17 09:16 UTC

**Comment by wardbell** [comment] 2017-08-18 00:30
To be fair, it **is an Angular issue** in as much as the Angular documentation makes extensive use of it.

I have [pledged to fix this problem soon](https://github.com/angular/in-memory-web-api/issues/122#issuecomment-323227776).
