### ISSUE TITLE
Anchor Scrolling does not work with fragment in conditional template even when condition is always true

### ISSUE THREAD

**Issue by bufke** [angular/angular#33240] opened 2019-10-17 22:30 UTC
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/router

### Is this a regression?

I'm not aware of this ever working as I'd expect

### Description

Anchor scrolling does not work as expected with anchor tags in conditional templates, even when the condition is always true.

Works:
```
<a id="fragment">Fragment is here</a>
````

Does not work:
```
<div *ngIf="true">
  <a id="fragment">Fragment is here</a>
</div>
```

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-issue-repro2-bnqswx

## 🌍  Your Environment

Tested in Angular 6 and 8

**Anything else relevant?**

A common use case is to load in dynamic data, perhaps from a CMS, and then show that data on a routed component. If the data contains a fragment, we'd expect to be able to scroll to it. However it does not work on initial navigation. A [common](https://stackoverflow.com/questions/48141804/angular-2-routing-with-fragments-async-data), but wrong, idea is to use a Resolver for async data shown on a page. However if the data is asynchronous then it is also conditional. Thus there is no way to implement functional anchor scrolling from Angular Router with any type of dynamic data in a component.

Also of note, once the component fully loads, anchor scrolling does work. For example if you had an anchor tag with a router link to a fragment on the same page, it will work. It will also work when navigating back to a page that is already loaded.

Tested in Chrome and Firefox

**Comment by bufke** [comment] 2019-10-18 16:14
As a workaround, I found this module to work well as a replacement. https://www.bennadel.com/blog/3402-creating-a-jump-to-anchor-fragment-polyfill-in-angular-5-2-0.htm

**Comment by atscott** [comment] 2020-05-27 22:19
Related to #30139. It might be good to combine these scrolling issues into one.

**Comment by atscott** [comment] 2022-06-27 23:09
Closing as duplicate of https://github.com/angular/angular/issues/30139 / https://github.com/angular/angular/issues/24547

**Closed by atscott** 2022-06-27 23:09 UTC
Labels: type: bug/fix, freq1: low, comp: router, state: confirmed, P4
