### ISSUE TITLE
Object doesn't support this action, angular 9 - IE11 in dev mode

### ISSUE THREAD

**Issue by Vikki123** [angular/angular#36701] opened 2020-04-18 04:34 UTC
# 🐞 bug report

### Affected Package
Angular dev server - ng serve

### Is this a regression?

No

### Description

 A clear and concise description of the problem...

I have an angular 9  application . I use the application as an iframe inside another parent using the following mock code

< !DOCTYPE html>
    <html>

    <body>

        <button id="add" onclick="add()">Add</button>
        <button id="remove" onclick="remove()">Remove</button>
        <div id="iframe">

        </div>

    </body>
    <script>
        function add() {
            var ifrm = document.createElement("iframe");
            ifrm.setAttribute("src", "http://localhost:4200");
            ifrm.style.width = "640px";
            ifrm.style.height = "480px";
            document.getElementById('iframe').appendChild(ifrm);
        }

        function remove() {
            let element = document.getElementsByTagName('iframe')[0];
            document.getElementById('iframe').removeChild(element);
        }
    </script>

    </html> 

When  the dev server is running and when clicked on remove frame i see the following error  in the IE console. 

![image](https://user-images.githubusercontent.com/8450434/79628074-684b6500-815b-11ea-969a-a7d7d55071f7.png)

## 🔬 Minimal Reproduction

1) Create a new application
2) ng serve
3) Open it as an iframe
4) Remove the iframe.

Error is  reproduced.

## 🌍  Your Environment

**Angular Version:**
```
Angular CLI: 9.0.4
Node: 10.19.0
OS: win32 x64

Angular:
...
Ivy Workspace:

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.900.4
@angular-devkit/core         9.0.4
@angular-devkit/schematics   9.0.4
@schematics/angular          9.0.4
@schematics/update           0.900.4
rxjs                         6.5.3
```

**Comment by pkozlowski-opensource** [comment] 2020-05-15 13:25
@Vikki123 could you please provide a minimal reproduce scenario (a github repo) with just Angular code as described in your reproduction steps? Looking at the attached screenshoot it looks like a lot is going on and there are definitively code outside of Angular being executed (I see `ockJS.prototype` for example).

In short - we will need a minimal reproduce scenario to make sure that the issue has indeed its root cause in Angular.

**Comment by atscott** [comment] 2020-09-23 18:06
Closing due to lack of reproduction after several months. 

If the problem still exists in your application and you can create a reproduction, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.

**Closed by atscott** 2020-09-23 18:06 UTC
Labels: browser: ie 11, browser: ie 9 or 10, comp: core, freq1: low, severity3: broken, state: Needs repro, type: bug/fix
