### ISSUE TITLE
HttpParams get and getAll methods return type does not support number neither boolean

### ISSUE THREAD

**Issue by aanaya-deltacom** [angular/angular#42637] opened 2021-06-24 07:56 UTC
# Bug Report

### Affected Package

The issue is caused by package @angular/common/http

### Is this a regression?

No. 

### Description

From Angular version 12, the `HttpParamsOptions` allows `number` and `boolean` types in `fromObject`, introduced with commit https://github.com/angular/angular/pull/40663

But, the return type for `get` and `getAll` methods in `HttpParams` is `string | null` and `string[] | null` respectively.

This causes type errors and tests failing.

## Minimal Reproduction

```
const params = new HttpParams({ fromObject: { numericParam: 5 } });
console.log(
  typeof params.get('numericParam') === 'number', // true
  params.get('numericParam') === '5', // false
  // params.get('numericParam') === 5, // does not compile
);
```

## Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 12.0.3
Node: 14.15.4
Package Manager: npm 6.14.10
OS: linux x64

Angular: 12.0.4
... animations, cdk, common, compiler, compiler-cli, core, forms
... localize, material, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.3
@angular-devkit/build-angular   12.0.3
@angular-devkit/core            12.0.3
@angular-devkit/schematics      12.0.3
@angular/cli                    12.0.3
@angular/flex-layout            12.0.0-beta.34
@schematics/angular             12.0.3
rxjs                            6.6.7
typescript                      4.2.4
</code></pre>

**Comment by petebacondarwin** [comment] 2021-06-24 10:01
I don't think this is actually a regression, since in v11 not only can you not pass a number into the HttpParamsOptions, the return type was also always string.

**Comment by destus90** [comment] 2021-06-24 10:12
@petebacondarwin https://stackblitz.com/edit/angular-ivy-f5vglj

**Comment by petebacondarwin** [comment] 2021-06-24 10:12
Actually, moreover, this is by design. The `HttpParams` is a map of keys to string values. It just happens that you can pass in non-string values when adding to the map, but these values get converted to and stored as strings.

If you want to compare non-string parameters, I think you would need to use an object or hash `Map`.

Closing as working as expected.

**Closed** 2021-06-24 10:13 UTC
Labels: comp: common/http

**Comment by aanaya-deltacom** [comment] 2021-06-24 10:15
> Actually, moreover, this is by design. The `HttpParams` is a map of keys to string values. It just happens that you can pass in non-string values when adding to the map, but these values get converted to and stored as strings.
> 
> If you want to compare non-string parameters, I think you would need to use an object or hash `Map`.
> 
> Closing as working as expected.

@petebacondarwin it does not work as expected

```
const params = new HttpParams({ fromObject: { numericParam: 5 } });
console.log(
  typeof params.get('numericParam') === 'number', // true
  params.get('numericParam') === '5', // false
  // params.get('numericParam') === 5, // does not compile
);
```

If the parameter was stored as string in the map, then `typeof params.get('numericParam') === 'number', // true` should be false, isn't it?

**Comment by petebacondarwin** [comment] 2021-06-24 10:20
You are right! There is a bug. But not the one reported here.

We have this code in our constructor:

```ts
      Object.keys(options.fromObject).forEach(key => {
        const value = (options.fromObject as any)[key];
        this.map!.set(key, Array.isArray(value) ? value : [value]);
      });
```

This should actually be:

```ts
      Object.keys(options.fromObject).forEach(key => {
        const value = (options.fromObject as any)[key];
        this.map!.set(key, Array.isArray(value) ? value.map(valueToString) : [valueToString(value)]);
      });
```

When adding items subsequently, outside of the constructor, this is what happens to values.
