### ISSUE TITLE
[ivy] QueryList#changes not triggered

### ISSUE THREAD

**Issue by cexbrayat** [angular/angular#33402] opened 2019-10-25 12:53 UTC
# 🐞 bug report

### Is this a regression?

It works as expected in `9.0.0-next.13` with VE but fails with Ivy 

### Description

The following component display a list of users, and has a query list on the divs created.
In `ngAfterViewInit`, we subscribe to the changes and log an `updates` counter every time there is a change. We also trigger a change by replacing the first element in the users array.

```typescript
@Component({
  selector: 'app-root',
  template: '<div *ngFor="let user of users">{{ user.name }}</div>'
})
export class AppComponent implements AfterViewInit {

  updates = 0;
  @ViewChildren('div') divs: QueryList<HTMLDivElement>;

  users = [
    { name: 'Bob' },
    { name: 'Alice' }
  ];

  ngAfterViewInit() {
    this.divs.changes.subscribe(_ => {
      this.updates++;
      console.log(this.updates);
    });
    setTimeout(() => this.users[0] = {name: 'Jen'}, 3000);
  }
}
```

In VE, we can see the counter be logged with a value of 1.
In Ivy, we have no trace: the subscribe is not executed.

## 🔬 Minimal Reproduction

Here is a repro https://github.com/cexbrayat/view-children-changes

A unit test checks it:

```typescript
it('should update 1 time', () => {
  const fixture = TestBed.createComponent(AppComponent);
  const app = fixture.componentInstance;
  fixture.detectChanges();

  expect(app.updates).toBe(0);

  // update a user
  app.users[0] = { name: 'Jen' };
  fixture.detectChanges();

  expect(fixture.nativeElement.querySelector('div').textContent).toContain('Jen');
  expect(app.updates).toBe(1);
});
```
This tests runs fine in VE (enableIvy: false in angular.json), but fails with Ivy. To repro:

```
npm i
ng test
# test succeeds
# switch enableIvy to true
ng test
# test fails with Expected 0 to be 1.
```

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.0.0-next.15
Node: 12.12.0
OS: darwin x64
Angular: 9.0.0-next.13
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-next.15
@angular-devkit/build-angular     0.900.0-next.15
@angular-devkit/build-optimizer   0.900.0-next.15
@angular-devkit/build-webpack     0.900.0-next.15
@angular-devkit/core              9.0.0-next.15
@angular-devkit/schematics        9.0.0-next.15
@angular/cli                      9.0.0-next.15
@ngtools/webpack                  9.0.0-next.15
@schematics/angular               9.0.0-next.15
@schematics/update                0.900.0-next.15
rxjs                              6.5.3
typescript                        3.6.4
webpack                           4.41.2
</code></pre>

**Comment by pkozlowski-opensource** [comment] 2019-10-25 15:32
I _suspect_ that I know what is going on here - we've changed the timing of the first `changes` event (it happens before the `QueryList` instance is assigned... I will have to debug to confirm but if I'm correct the fix would require changes to the generated code...

**Comment by Splaktar** [comment] 2019-10-25 17:43
I am driving, so can't check, but does this effect other APIs or just `@ViewChildren`? I don't remember all the places that `QueryList` is used.

**Comment by kara** [comment] 2019-11-15 00:01
@cexbrayat I cloned down the repo, but I can't reproduce the failure.

- If I run "ng test" with no changes (View Engine mode), the test fails
- If I enable Ivy and re-run "ng test" (Ivy mode), the test still fails

Then I looked at the component in the repo and it looks like there's a typo. The `@ViewChildren` query looks for `'div'`, but there is no local ref in the template called `'div'`. If you add the local ref, the test passes in both View Engine and Ivy.

I'm going to close this because I can't reproduce the issue. If there's something else that's broken, please feel free to open a new issue with an updated repro.

**Closed by kara** 2019-11-15 00:01 UTC
Labels: comp: ivy, freq2: medium, severity5: ivy-compat, type: bug/fix
