### ISSUE TITLE
FormArray insert and setControl insert items on wrong index

### ISSUE THREAD

**Issue by rusev** [angular/angular#13128] opened 2016-11-29 14:56 UTC
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Documentation for [insert](https://angular.io/docs/ts/latest/api/forms/index/FormArray-class.html#!#insert-anchor) says that item is inserted on the given index.

>Insert a new AbstractControl at the given index in the array.

However if the `controls` collection is empty the item is always inserted on first position. The issue is due to inappropriate [usage of splice here](https://github.com/angular/angular/blob/master/modules/%40angular/forms/src/model.ts#L1177).

**Expected behavior**
To always insert the item at the given index.

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/zS5RlQhRVWpviWWK99JO?p=preview

**What is the motivation / use case for changing the behavior?**
We need to add FormGroups dynamically in FormArray based on relative index and later retrieve it back from that index.

* **Angular version:** 2.2.3

**Comment by DzmitryShylovich** [comment] 2016-11-29 15:31
> The issue is due to inappropriate usage of splice here.

what is an appropriate usage?

what should be the value at index 0 in your example, undefined?

**Comment by rusev** [comment] 2016-11-29 16:12
`undefined` is valid, but there should be a FormGroup on index 1.

**Comment by DzmitryShylovich** [comment] 2016-11-29 16:20
I don't think it's a bug. `splice` is a standard method to insert items at a specific index. If index is greater than array length then it will insert it at the `length` position. It's your responsibility to ensure that array has appropriate length.

**Comment by rusev** [comment] 2016-11-29 16:29
Indeed `splice` is a standard method. However there is a discrepancy of what is written in the documentation and what is the actual behavior. The documentation is very explicit in what is the intended behavior. 

My expectation is that if I insert item at position **X**, I should be able to get it from that position **X** later and that is what this means: _Insert a new AbstractControl at the given index in the array._

**Comment by rusev** [comment] 2016-11-29 16:33
Here is what I expect - https://www.typescriptlang.org/play/index.html#src=const%20arr%20%3D%20%5B%5D%0D%0A%0D%0Aarr%5B1%5D%20%3D%20'foo'%0D%0A%0D%0Aconsole.log(arr%5B0%5D)%0D%0A%0D%0Aconsole.log(arr%5B1%5D)

**Comment by DzmitryShylovich** [comment] 2016-11-29 16:40
Ok, I got it. What do u expect to happen when we already have a control at that index, overwrite it?
```
const arr = ['aa, 'bb'];

arr[1] = 'foo';

```

**Comment by DzmitryShylovich** [comment] 2016-11-29 18:13
It's pretty easy to implement but there's a difference between `arr[index] = value;` and `arr.splice(index, 0, value)`. In the former case it will override the value at index and in latter case it will insert value in between. And if we change it it will be a breaking change. So I think it's a docs issue.

**Comment by rusev** [comment] 2016-11-30 06:51
It should replace an existing control, same as [setControl](https://angular.io/docs/ts/latest/api/forms/index/FormArray-class.html#!#setControl-anchor).

Does it make sense to you?

**Comment by xban1x** [comment] 2016-12-14 05:30
This is a docs issue. It cannot magically insert it at an Index of an Array if array is not populated.

**Comment by rusev** [comment] 2016-12-16 12:23
@xban1x  I don't think this is documentation issue. What's the purpose of the `index` in API then? In JavaScript and TypeScript you can have sparse arrays. Nothing fancy here.

**Comment by kara** [comment] 2017-02-17 23:57
If you want to replace an existing control, there is already a `setControl()` method that will do that for you. `insert()` is intended to splice a control in without overwriting the existing control in that position.  If you think the API reference could be clarified, happy to look at a PR that adds more info.

Closing, as it works as intended.

**Closed by kara** 2017-02-17 23:57 UTC
Labels: comp: forms

**Comment by rusev** [comment] 2017-02-20 07:35
@kara Please re-open this issue! `insert` documentation claims that items is inserted at position. I'm not willing to use `setControl`. `setControl` will not work if there isn't item at the given position, while `insert` should work. 
What is the purpose of the index parameter then? It is pointless unless the array is already populated.
