### ISSUE TITLE
using core-js with Angular 2

### ISSUE THREAD

**Issue by rolandjitsu** [angular/angular#5614] opened 2015-12-04 19:04 UTC
I was trying to compile my project directly to ES6 and use [core-js](https://github.com/zloirock/core-js) for shims (they seem to cover a lot more than es6-shim), but it looks like I get a an error:
```js
TypeError: Cannot convert undefined or null to object
angular2.min.js:26Uncaught TypeError: Cannot read property 'getOptional' of undefinedu @ angular2.min.js:26t._initApp @ angular2.min.js:26t.application @ angular2.min.js:26n @ angular2.min.js:26(anonymous function) @ bootstrap.ts:37(anonymous function) @ bootstrap.ts:37U @ system.src.js:4597c.execute @ system.src.js:4597i @ system.src.js:4597n @ system.src.js:4597execute @ system.src.js:4597y @ system.src.js:4597w @ system.src.js:4597p @ system.src.js:4597h @ system.src.js:4597(anonymous function) @ system.src.js:4597n.run @ angular2.min.js:1(anonymous function) @ angular2.min.js:1I @ angular2.min.js:1A @ angular2.min.js:1R @ angular2.min.js:1(anonymous function) @ angular2.min.js:1n.run @ angular2.min.js:1(anonymous function) @ angular2.min.js:1h @ angular2.min.js:1h @ core.js:3055(anonymous function) @ core.js:3066e @ core.js:3310
core.js:3055 Uncaught TypeError: Cannot read property 'getOptional' of undefined
	Evaluating http://localhost:3000/app/bootstrap.js
	Error loading http://localhost:3000/app/bootstrap.jsh @ core.js:3055(anonymous function) @ core.js:3066e @ core.js:3310
```
Not sure why though. If I compile to ES5, it works perfectly fine.

Here is my `tsconfig.json` for reference:
```js
{
	"compilerOptions": {
		"emitDecoratorMetadata": true,
		"experimentalDecorators": true,
		"module": "commonjs",
		"moduleResolution": "node",
		"noImplicitAny": false,
		"sourceMap": true,
		"target": "es5"
	}
}
```

**Comment by caffinatedmonkey** [comment] 2015-12-18 19:53
Try switching your script from `angular2.min.js` to `angular2.dev.js` and you should get more information about the problem.

**Comment by wesleycho** [comment] 2015-12-29 01:16
Looks like this is related to the other open issue #5755, referencing for convenience.

**Comment by pkozlowski-opensource** [comment] 2015-12-29 12:07
Closing as duplicate of #5755

**Closed by pkozlowski-opensource** 2015-12-29 12:07 UTC
