### ISSUE TITLE
Hi i found this problem when i use HttpParams.append

### ISSUE THREAD

**Issue by luocongqiu** [angular/angular#28227] opened 2019-01-18 09:23 UTC
# 🐞 bug report

### Affected Package
Unfortunately, I cannot tell precisely, which package of @angular is causing the behavior.

### Is this a regression?

 the previous version also had the same problem

### Description

<pre><code>
        let params = new HttpParams();
        params = params.append('status', '1');
        params = params.append('status', '2');
        console.info(params.get('status'));
        params = params.set('name', 'test');
        params = params.append('status', '3');
        console.info(params.toString());
</code></pre>

log 

<pre><code>
1
status=1&status=2&status=1&status=2&status=3&name=test
</code></pre>

status=1&status=2 will repeat 

## 🔥 Exception or Error

See Description

## 🌍  Your Environment

**Angular Version:**
<pre><code>
     "@angular/common": "~7.2.0",
    "@angular/compiler": "~7.2.0",
    "@angular/core": "~7.2.0",
    "@angular/forms": "~7.2.0",
    "@angular/platform-browser": "~7.2.0",
    "@angular/platform-browser-dynamic": "~7.2.0",
    "@angular/router": "~7.2.0",
</code></pre>

**Anything else relevant?**
no

**Comment by trotyl** [comment] 2019-01-18 10:06
Duplicate of https://github.com/angular/angular/issues/20430

**Comment by AndrewKushnir** [comment] 2019-01-20 23:09
Hi @luocongqiu, I'm closing this ticket as a duplicate of #20430 (thanks @trotyl for the link). Please refer to issue #20430 for additional information and updates. Thank you.

**Closed by AndrewKushnir** 2019-01-20 23:09 UTC
