### ISSUE TITLE
"data-id" gets converted to "id" when used with {{ }}

### ISSUE THREAD

**Issue by StefanKern** [angular/angular#41345] opened 2021-03-25 12:25 UTC
### Description

When adding a `data-id` to an element, which just uses static text, it gets output as `data-id` attribute. However when adding a dynamic variable to the data-id attribute (e.g.: `data-id="test-{{name}}"`) and id property gets rendered to the html element.

![grafik](https://user-images.githubusercontent.com/2032760/112471832-ad651780-8d6c-11eb-92b2-a673423d8fb2.png)

## 🔬 Minimal Reproduction
```
<div data-id="test-1">This div has a data-id</div>
<br/>
<div data-id="test-{{name}}">This div has an id but should have a data-id too.</div>
```
https://stackblitz.com/edit/angular-ivy-kib5sx?file=src%2Fapp%2Fapp.component.html

## 🔥 Exception or Error
data-id with a dynamic attribute gets rendered as data-id too

**Anything else relevant?**
A workaround is to use `[attr.data-id]="'test-'+name"`.
![grafik](https://user-images.githubusercontent.com/2032760/112472110-092fa080-8d6d-11eb-9f0b-3f3ee6beac67.png)
This however makes the code longer and harder to read.

Note 2: these `data-id`s are used by our TA team and therefore we have a lot of them. AFAIK using these attr syntax is generates a bigger code and to be consitent with one syntax we use `[attr.data-id]` if when it is not needed.

**Comment by StefanKern** [comment] 2021-03-25 12:30
Note: duplicates https://github.com/angular/angular/issues/26406

**Comment by AndrewKushnir** [comment] 2021-03-25 16:47
Closing this ticket as a duplicate of #26406.

**Closed by AndrewKushnir** 2021-03-25 16:47 UTC
