### ISSUE TITLE
Hydration not works with html tag Footer on Safari 17 

### ISSUE THREAD

**Issue by manduriomane** [angular/angular#54259] opened 2024-02-05 15:05 UTC
### Which @angular/* package(s) are the source of the bug?

platform-browser

### Is this a regression?

Yes

### Description

Hi,

I have a problem on Safari 17.0

In my angular app I use a component that has this code:

```
<footer class="page-footer font-small pt-2">
...
</footer>
```

If I enable hydration on app.module

`provideClientHydration(withNoHttpTransferCache())`

I get thi error on Safari 17.0

![image](https://github.com/angular/angular/assets/25469100/8885a269-1567-4592-ac3d-9601cfbffb60)

On Chrome it works

If I rename html tag from footer to div

```
<div class="page-footer font-small pt-2">
...
</div>
```
 
it works also on Safari

### Please provide the exception or error you saw

```true
[Error] Error: NG0500: During hydration Angular expected <div> but the node was not found.

Angular expected this DOM:

<footer _ngcontent-serverapp-c2266436350="" class="page-footerfont-smallpt-2">
  <div>…</div>  <-- AT THIS LOCATION
  …
</footer>

Note: attributes are only displayed to better represent the DOM but have no effect on hydration mismatches.

To fix this problem:
  * check the "FooterComponent" component for hydration-related issues
  * check to see if your template has valid HTML structure
  * or skip hydration by adding the `ngSkipHydration` attribute to its host node in a template

 Find more at https://angular.io/errors/NG0500 — core.mjs:42
	(anonymous function) (main.js:1160)
	asyncGeneratorStep (vendor.js:67800)
	_next (vendor.js:67819)
	(anonymous function) (vendor.js:67824)
	ZoneAwarePromise (polyfills.js:1372)
	(anonymous function) (vendor.js:67816)
	run (polyfills.js:131)
	(anonymous function) (vendor.js:52746)
	onInvoke (vendor.js:36074)
	run (polyfills.js:131)
	(anonymous function) (polyfills.js:1209)
	onInvokeTask (vendor.js:35751)
	onInvokeTask (vendor.js:36063)
	runTask (polyfills.js:177)
	drainMicroTaskQueue (polyfills.js:547)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.1.2
Node: 20.11.0
Package Manager: npm 10.2.4
OS: win32 x64

Angular: 17.1.2
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, localize, material
... platform-browser, platform-browser-dynamic, platform-server
... router, service-worker, ssr

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1701.2
@angular-devkit/build-angular   17.1.2
@angular-devkit/core            17.1.2
@angular-devkit/schematics      17.1.2
@schematics/angular             17.1.2
rxjs                            7.8.1
typescript                      5.3.3
zone.js                         0.14.3
```

**Comment by jessicajaniuk** [comment] 2024-02-05 16:39
@manduriomane This is a DOM mismatch error. So there's something in that footer component that's manipulating the DOM causing a mismatch between server and client. Direct DOM manipulation in a component would cause this error.

Can you share a minimal repro on stackblitz? Without that this isn't actionable for us.

**Comment by manduriomane** [comment] 2024-02-05 17:50
hi @jessicajaniuk thank's  for your reply.
The issue occurs even if the footer tag is empty (always only on Safari 17)

**Comment by jessicajaniuk** [comment] 2024-02-05 17:55
@manduriomane It's entirely possible there's something else in your application modifying the footer code, like a third party script. Without a minimal reproduction we can look at, it's not clear what is happening.

**Comment by AndrewKushnir** [comment] 2024-02-09 18:45
Closing this ticket for now, since there is no repro available. Please reopen or create a new ticket once there is a repro that we can use for further investigation.

**Closed by AndrewKushnir** 2024-02-09 18:45 UTC
Labels: needs reproduction, area: core, core: hydration
