### ISSUE TITLE
'ERROR TypeError: Cannot redefine property: ɵfac' in angular 9 with 'optimization:true'

### ISSUE THREAD

**Issue by slavoroi** [angular/angular#35993] opened 2020-03-10 16:52 UTC
# 🐞 bug report

### Affected Package
@angular/core

### Is this a regression?
It is reproducible since angular 9+,
It worked in angular 8 without ivy.

### Description

When creating components dynamically with angular compiler, and rebuilding them 
for the second time (going back and forth), and
 setting `optimization:true` and running ```ng serve --prod``` throws an error.
angular.json: 
``` "configurations": {
            "production": {
              "outputHashing": "all",
              "sourceMap": false,
              "optimization": true,
              "extractCss": true,
              "namedChunks": true,
              "aot": false,
              "extractLicenses": false,
              "vendorChunk": true,
              "buildOptimizer": false
            }
          }
```
```
compileStory(story: any) {
    const factory = this.createComponentFactorySync(story.storyClass, story.storyInstance);

    // Destroy previous component reference
    if (this.componentRef) {
      this.componentRef.destroy();
      this.componentRef = null;
    }
    this.componentRef = this.container.createComponent(factory);
  }

  /**
   * Create an on-the-fly component
   */
  private createComponentFactorySync(storyClass: any, storyInstance: StoryBase): 
  ComponentFactory<any> {
    // Create a new decorator
    const metadata = {
      selector: 'runtime-component',
      template: storyInstance.template,
      styles: storyInstance.styles,
      encapsulation: ViewEncapsulation.None
    };
    const decoratedCmp = Component(metadata)(storyClass);

    const moduleClass = class RuntimeComponentModule {
    };
    const decoratedNgModule = NgModule({
      imports: [
        CommonModule,
        ...storyInstance.imports
      ], declarations: [decoratedCmp],
      schemas: [CUSTOM_ELEMENTS_SCHEMA, NO_ERRORS_SCHEMA]
    })(moduleClass);

    this.compiler.clearCacheFor(decoratedCmp);
    this.compiler.clearCacheFor(decoratedNgModule);
    const module: ModuleWithComponentFactories<any> = 
    this.compiler.compileModuleAndAllComponentsSync(decoratedNgModule);
    return module.componentFactories.find(f => f.componentType === decoratedCmp);
  }
```

## 🔥 Exception or Error
```
ERROR TypeError: Cannot redefine property: ɵfac
    at Function.defineProperty (<anonymous>)
    at Xm (vendor.e2a70c8703f8a0512308.js:formatted:122992)
    at gg (vendor.e2a70c8703f8a0512308.js:formatted:123141)
    at vendor.e2a70c8703f8a0512308.js:formatted:123118
    at vendor.e2a70c8703f8a0512308.js:formatted:113282
    at Ha.createComponentFactorySync (main.6d102aa2fa8951aba260.js:1)
    at Ha.compileStory (main.6d102aa2fa8951aba260.js:1)
    at Ha.ngOnChanges (main.6d102aa2fa8951aba260.js:1)
    at Ha.Zu.t.type.ngOnChanges.t.onChanges (vendor.e2a70c8703f8a0512308.js:formatted:119354)
    at sn (vendor.e2a70c8703f8a0512308.js:formatted:114211)
```

which is called in angular core:
```
function Xm(t, e) {
            let n = null;
            Object.defineProperty(t, ct, {
                get: ()=>{
                    if (null === n) {
                        const i = Ym(t, e)
                          , r = it();
                        n = r.compileFactory(Vm, `ng:///${t.name}/\u0275fac.js`, 
                           Object.assign(Object.assign({}, i.metadata), {
                            injectFn: "directiveInject",
                            target: r.R3FactoryTarget.Directive
                        }))
                    }
                    return n
                },
                configurable: !1
            })
        }
```

**Anything else relevant?**
Setting ```optimization:false``` in angular.json fixes the issue though it doesn't minify the code.

## 🌍  Your Environment
```json
Angular CLI: 9.0.5
Node: 12.13.0
OS: linux x64

Angular: 9.0.5
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.5
@angular-devkit/build-angular     0.900.5
@angular-devkit/build-optimizer   0.900.5
@angular-devkit/build-webpack     0.900.5
@angular-devkit/core              9.0.5
@angular-devkit/schematics        9.0.5
@angular/cdk                      9.1.1
@angular/material                 9.1.1
@ngtools/webpack                  9.0.5
@schematics/angular               9.0.5
@schematics/update                0.900.5
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
```

**Comment by pkozlowski-opensource** [comment] 2020-03-10 17:21
A simpler reproduce scenario: https://ng-run.com/edit/klKBOX1JNrET1nlYADik?open=app%2Fapp.component.ts

I can confirm that this is a bug and the crux of it that if we've got a directive with a host binding writing to an attribute _and_ we put this directive on `<ng-template>` (and probably `<ng-container>`!) it will throw.

In VE such errors would be silently ignored since since host bindings were part of the usage template so VE _knew_ if it makes sense at all to have a binding on `<ng-template>` / `<ng-container>`.

We could "fix" it ivy by ignoring bindings on  `<ng-template>` / `<ng-container>` but one could also argue that this is invalid directive usage - here `[kendoGridSelectAllCheckbox]` expects to be put on a regular element (since it wants to set attributes) but it is used on `<ng-template>`. I don't know enough abut Kendo impl but the example given puts the mentioned directive on an `<input>` element: https://www.telerik.com/kendo-angular-ui/components/grid/selection/#toc-select-all-feature

@slavoroi do you think that usage of `[kendoGridSelectAllCheckbox]` on `<ng-template>` is a valid one?

**Comment by rymsha** [comment] 2020-05-24 18:54
Angular 9.1.7 - same error

**Comment by alxhub** [comment] 2020-05-26 23:26
Hi @slavoroi,

In order to investigate this issue, we're going to need a reproduction, either in the form of a stackblitz or a Github repository, with the build steps required to illustrate the problem. If you could provide that, it would be super helpful!

Thanks,
Alex

**Comment by slavoroi** [comment] 2020-05-29 21:47
I will try to create this kind of repo.

**Comment by slavoroi** [comment] 2020-06-23 12:37
Here is a reproduction:
https://github.com/slavoroi/angular-dynamic-components 
@alxhub

**Comment by rymsha** [comment] 2020-07-11 11:01
Angular 10.0 Issue remains.

**Comment by petebacondarwin** [comment] 2020-07-11 14:22
OK, so I have found the cause of the error...

Calling `createComponentFactorySync()` with a class (i.e. `storyClass`) cuases the class (e.g. `Button`) gets "compiled" by the Angular compiler as a component; this happens due to the call to `Component(metadata)(storyClass)`.

When Angular compiles a class it attaches static properties to the class (not the instance) that tell Angular how to render this component. In particular, in this case the `ɵfac` property (amongst others).

But you are calling this function every time you want to display a "dynamic" component, which means that the class is being compiled over and over again, even though it has already been compiled and does not need to be compiled again. Each time this compilation happens, Angular writes these properties (e.g. `ɵfac`) again and again.

This only fails in production mode because when Angular defines the property it sets `configurable`  on the property to `!!ngDevMode`. See https://github.com/angular/angular/blob/d1ea1f4c7f3358b730b0d94e65b00bc28cae279c/packages/core/src/render3/jit/directive.ts#L201

...

The question is what is the correct way to do this?

I am not sure if there is an official way to compile components dynamically like this that gets around this issue. Perhaps @alxhub has some ideas. But if this is the correct approach, then you could:

* check for the `ɵfac` and/or `ɵcmp` properties on the class before compiling it - although this would be relying upon a private API of Angular.
* or perhaps create a `WeakSet` of classes that you have already compiled and do not compile them again.

**Comment by slavoroi** [comment] 2020-07-11 14:29
interesting... 
thanks!
the thing is that its an example i found in one of the angular lib q&a's.
I really wonder what is the best practice here.

**Comment by petebacondarwin** [comment] 2020-07-11 14:51
To be honest, I am not even sure if single component compilation, with potentially different metadata on each instance is even supported by Angular. Could you share the article that suggested this approach?

**Comment by slavoroi** [comment] 2020-07-11 15:17
I can't find it right now.
So you think I should look into https://angular.io/guide/dynamic-component-loader this ?

**Comment by petebacondarwin** [comment] 2020-07-11 15:20
That guide does not allow new metadata to be associated with a class, which is what you are doing. It assumes that each component has already been compiled. It just allows you to dynamically choose a component to instantiate and render.

**Comment by slavoroi** [comment] 2020-07-11 15:22
i actually do not need new meta data in our simple storybook implementation, if it was a real we probably would of needed it.

**Comment by petebacondarwin** [comment] 2020-10-19 15:08
Closing as the original issue author solved their problem.

**Closed by petebacondarwin** 2020-10-19 15:08 UTC
Labels: comp: compiler, engine: ivy, needs clarification, needs reproduction, triage #1, type: bug/fix
