### ISSUE TITLE
Angular Elements loses the Change Detector ability

### ISSUE THREAD

**Issue by wizardnet972** [angular/angular#24061] opened 2018-05-23 09:05 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
I create custom element from a Component. On changing the Input(), I execute ajax call. In the subscibe function I change local variable. but the change ditection is not reflect the changes in the tempalte.
only when I using `this.cd.detectChanges();` it does.

## Expected behavior
Angular Elements should watching local variables when they changed. like Angular App does because it is part of it.

## Minimal reproduction of the problem with instructions
[I create some User Component](https://gist.github.com/wizardnet972/4c6a1ab184d30d387ef5e13205f3de57)

Compile with the last version of `@angular/elements`, with `@ngtools/webpack`.

**In javascript**
* I change by `$0.userId = 4`.
* The events cycle are working.
* the user is not change inside the template.

## What is the motivation / use case for changing the behavior?
Helping and find bugs.

## Environment

<pre><code>
Angular version: 6.0.2

For Tooling issues:
- Node version: 9.5.0
- Platform:  Windows 

Others:

</code></pre>

**Comment by Aggelost1** [comment] 2018-08-11 17:46
why is this closed? I have an almost identical issue and the only way to solve it was to manually detect changes... It would be nice to know if there is a better answer

**Comment by xblaster** [comment] 2018-08-24 13:43
I have exactly the same issue, please reopen the ticket.

**Comment by mathpaquette** [comment] 2018-11-07 13:32
@xblaster, @Aggelost1, @wizardnet972  Wow, any thoughts here? Having the same issue but not clear to me if its supposed to work or not..

**Comment by qkhanhpro** [comment] 2019-03-08 09:11
Hello everyone, this fix worked for me, try it and tell if it works

https://github.com/angular/angular/issues/26158

**Comment by cdarken** [comment] 2019-07-10 19:58
Yes that fix worked for me too. But if the pull request with the fix was merged in zone.js in september 2018 why is this still an issue in Angular 7?

**Comment by ilchenkob** [comment] 2020-01-31 14:14
I have the same issue using Angular 8

**Comment by ilchenkob** [comment] 2020-02-03 10:09
I tried to use `elements-zone-strategy` package to fix the issue, but it didn't help me.
Then I removed `elements-zone-strategy` from dependencies, deleted `node_modules` folder, reinstalled packages, rebuilt my project. And now it works fine.
I have no idea what was that, but now bug is gone.

**Comment by gkalpak** [comment] 2020-06-02 11:14
We don't have a clear reproduction to get to the root cause of this, but (based on the symptoms) it seems to be the same as #24181 (if not already fixed by angular/zone.js#1133).

I am going to close this as a duplicate of #24181. If it turns out this is different (and still an issue with the latest versions of Angular and Zone.js), please open a new GitHub issue providing the necessary details (including a (minimal 🙏) reproduction). Thank you!

**Closed by gkalpak** 2020-06-02 11:14 UTC
Labels: comp: elements, freq2: medium, severity2: inconvenient, type: bug/fix
