### ISSUE TITLE
ngModel <select> binding is incorrect when options are reloaded

### ISSUE THREAD

**Issue by wardbell** [angular/angular#13578] opened 2016-12-19 21:49 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request 
```

**Current behavior**
When a `<select>` is bound with `[ngModel])` the binding is not refreshed when the options are reloaded as can happen when the options are loaded from the server asynchronously.

In the repro provided below, given this HTML template,
```
    State:
    <select [(ngModel)]="address.state">
      <option *ngFor="let state of states">{{state}}</option>
    </select>
```
the state selection for the address "Chicaco, Illinois" is shown as "California" rather than "Illinois"

**Expected behavior**
Should be "Illinois" as shown in the workaround

**Minimal reproduction of the problem with instructions**
https://plnkr.co/edit/NnnXJWz1oJuSgJLFtZWw?p=preview

**Please tell us about your environment:**
Windows, Chrome

* **Angular version:** 2.3.0
 
* **Language:** [all]

**Comment by DzmitryShylovich** [comment] 2016-12-19 21:52
Duplicate of https://github.com/angular/angular/issues/13274?

**Comment by DzmitryShylovich** [comment] 2016-12-23 19:47
@wardbell u just forgot to add `[value]="state"`

https://plnkr.co/edit/aeBBB0B27Ylz546N60zB?p=preview

**Comment by wardbell** [comment] 2017-01-03 01:13
@DzmitryShylovich The `[value]` binding is an interesting workaround. It should not be necessary and I don't want it to throw ... ever. This is a bug. It should work as I wrote it.

**Comment by DzmitryShylovich** [comment] 2017-01-03 06:52
Then it's a duplicate of https://github.com/angular/angular/issues/8549#issuecomment-253323964

**Comment by wardbell** [comment] 2017-01-03 23:31
@DzmitryShylovich Indeed it is ... although I would not have know to look for it there.  So while I don't mind marking as a duplicate, I'd like to see it remain open as long as _that_ issue is open so that folks like me can find out about it.

**Comment by DzmitryShylovich** [comment] 2017-01-03 23:32
I think we should write a warning about it in dev mode

**Comment by wardbell** [comment] 2017-01-03 23:36
Ha ... there would be no end to such warning.  But I agree we need to call attention to this somewhere until it is fixed ... or encourage Angular team to just fix it.

**Comment by DzmitryShylovich** [comment] 2017-01-04 00:07
I agreed with Kara here. Benefit are not overweight against the actual work. Plus a trivial workaround.

**Comment by wardbell** [comment] 2017-01-04 00:36
And I disagree because 
* setting the `value` is optional in HTML, 
* a great many people don't set it or don't even remember it exists, 
* things usually work until they suddenly don't at which point you have no idea what's wrong (I didn't)
* Angular should handle the extremely common patterns with grace

**Comment by kara** [comment] 2017-02-14 02:57
Closing as a dupe of #8549

**Closed by kara** 2017-02-14 02:57 UTC
Labels: comp: forms
