### ISSUE TITLE
RouterLinkActive not handling routerLink change

### ISSUE THREAD

**Issue by rsauget** [angular/angular#9825] opened 2016-07-05 18:41 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I have a routerLink ['/accounts', currentAccount, 'account-statement'], with currentAccount an attribute of the component.
On initial load of route /accounts/1/account-statement, the routerLinkActive class is correctly set. But when I do : this.router.navigate(['/accounts', 2, 'account-statement']), the active class is not set, although currentAccount is correctly set to 2.
currentAccount is set in ngOnInit like this (route is ActivatedRoute):
this.route.params.map(params => params['id'])
            .subscribe((id: number) => {
                console.log(id);
                this.currentAccount = id;
            });

**Expected/desired behavior**
RouterLinkActive class should be properly set.

**Reproduction of the problem**
Code available here : [http://pastebin.com/RwCRpCXP](http://pastebin.com/RwCRpCXP)

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4 (router 3.0.0-beta.2)
 
* **Browser:** [ all ] 
 
* **Language:** [ TypeScript 1.9 ]

**Comment by bennadel** [comment] 2016-07-11 19:12
I also see this when I manually change the browser URL (instead of navigating via an anchor tag). The `routerLinkActive` never seems to take manual changes into account.

**Comment by zoechi** [comment] 2016-07-18 10:44
Please provide a Plunker that allows to reproduce.

**Comment by bennadel** [comment] 2016-07-23 10:57
@zoechi @brandonroberts Here is a Plunkr that reproduces this problem:

http://plnkr.co/edit/P33DgGaQCk5vquCDNBar?p=preview

In the demo, you click on the `Detail N` links to change the detail route. Then, in the detail, you can click on the `Foo` and `Bar` links to change the sub-page:

```html
<p>
<a [routerLink]="[ 'foo' ]">Foo</a> &mdash;
<a [routerLink]="[ 'bar' ]">Bar</a> 
</p>
```

What you'll notice is that as you move from *Detail to Detail* page the `id` of the `Foo` and `Bar` links never updates. As such, the `Foo` and `Bar` links always go back to `id: 1`. Notice, also, that the `Foo` and `Bar` `[routerLink]` contain no reference to the `id`.

**Comment by bennadel** [comment] 2016-07-23 10:59
@zoechi @brandonroberts sorry, deleted last comment. Realized I was in the wrong issue -- too early in the morning :)

**Comment by bennadel** [comment] 2016-07-23 11:05
@zoechi @brandonroberts Ok, here's a plunker for the `routerLinkActive` problem:

http://plnkr.co/edit/P33DgGaQCk5vquCDNBar?p=preview

The layout is basically List --> Detail --> Sub-section. However, the list-navigation does deep-linking to the sub-section. Notice, however, that as you move from Link to Link, the sub-section navigation loses its active state (as denoted by the `text-transform:uppercase`.

**Comment by bennadel** [comment] 2016-07-23 11:07
The primary-nav also gets messed up, but I believe that is a different issue ( https://github.com/angular/angular/issues/10207 ).

**Comment by vsavkin** [comment] 2016-08-08 23:24
@bennadel I don't see your using routerLinkActive in the plunker.

Could you provide a plunker using the latest nightly build of angular and router?

**Comment by bennadel** [comment] 2016-08-08 23:48
@vsavkin sorry, I don't know what happened there. I just deleted the comments; for some reason, I must have posted the wrong Plunker.

**Comment by vsavkin** [comment] 2016-08-12 17:48
Closing this issue. 

If the issue is still present in Router RC1, please reopen it with a plunker reproducing it.

**Closed by vsavkin** 2016-08-12 17:48 UTC
Labels: comp: router, need: repro, type: bug

**Comment by techno199** [comment] 2016-09-08 10:00
I met the same behavior in my app and the tricky workaround was to redraw that refs via *ngIf, hiding old ones and then populating new links after arguments (i.e.  .currentAccount) has changed.

**Comment by mharris7190** [comment] 2016-09-20 17:12
Also having this issue with router@3.0.0-rc.1. routerLink changes to accommodate :id param when route changes but routerLinkActive does not update. It seems to be running too late maybe?

**Comment by brandonroberts** [comment] 2016-09-20 18:04
This issue should be fixed in `3.0.0-rc.2` and later

**Comment by grungondola** [comment] 2017-08-14 01:06
I'm still hitting this issue in my project.

I do not run into this issue on initial load or when the user navigates with the navbar, but when I manually navigate in the code, it doesn't update what is active. I change the links based on a drop-down and then navigate to the "Home" link of whatever the selection is, and it doesn't mark that as active in the DOM. I think this may be because of how the lifecycle hits, trying to mark the active link before updating the links in the ngFor that I have in the navbar.

**Comment by grungondola** [comment] 2017-08-14 01:10
Quick update, I figured out a way to make this work for me, in case others are creating dynamic navigation links. You should wrap it in a quick timeout, like so:
`    this.setupLinks();

    setTimeout(() => {
      this.router.navigate(this.Links[0].routeCommands(this.locationDetails));
    }, 10);`

**Comment by trichetriche** [comment] 2017-12-06 14:01
Thank you @grungondola, I have been struggling with this for a couple of hours and you resolved my issue. Altough I don't know why people are downvoting your answer, it totally resolved my issue ...
