### ISSUE TITLE
Compiler generates conflicting exports `ɵ0`

### ISSUE THREAD

**Issue by jeripeierSBB** [angular/angular#42451] opened 2021-06-02 13:14 UTC
# Bug Report

### Is this a regression?

Yes, the previous version in which this bug was not present was: before 12.0.0

### Description
Consider a library project with following public-api.ts files:

moduleA/public-api.ts
```
export * from './classA'; 
```

moduleB/public-api.ts
```
export * from './classB';
```

public-api.ts (top level)
```
export * from 'packageA/moduleA; 
export * from 'packageA/moduleB;
```

moduleA/classA.ts (and moduleB/classB similar)
```
@Component({
  providers: [
    {
      provide: SOMETHING,
      useValue: undefined,
    },
  ],
})
export class ClassA {}
```

**Now we build the packages and can see the following outputs:**

dist/packageA/fesm2015/moduleA.js
```
...
const ɵ0 = undefined;
...
export { ClassA,  ɵ0}; // Compiler adds `ɵ0` to exports
```

dist/packageA/fesm2015/moduleB.js
```
...
const ɵ0 = undefined;
...
export { ClassB,  ɵ0}; // Compiler adds `ɵ0` to exports
```

**If a library consumer imports any module as a primary import like `import { ModuleB } from 'packageA', the following exception happens:**

```
./node_modules/packageA/fesm2015/packageA.js - Error: The requested module 'packageA/moduleB' contains conflicting star exports for the name 'ɵ0' with the previous requested module 'packageA/moduleA'
```

## Workaround

If replacing the star (*) export by specific class name, the compiler does not anymore add `ɵ0` to the exports.

public-api.ts moduleA
```
export { ClassA } from './classA';
```

## Other Findings

There are also other reasons, that the compiler produces `ɵ0` symbols and adds it to the exports, the above code is only an example.

## Reproduction

https://github.com/sbb-design-systems/sbb-angular/tree/12.0.1

`yarn && yarn -s build packages` and check `dist/releases/angular-public/fesm2015/accordion.js` or `dist/releases/angular-public/fesm2015/pagination.js`

## Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 12.0.2
Node: 12.16.3
Package Manager: yarn 1.22.4
OS: darwin x64

Angular: 12.0.2
... animations, bazel, cdk, cli, common, compiler, compiler-cli
... core, forms, language-service, localize, platform-browser
... platform-browser-dynamic, router

Package                          Version
----------------------------------------------------------
@angular-devkit/architect        0.1200.2
@angular-devkit/build-angular    12.0.2
@angular-devkit/core             12.0.2
@angular-devkit/schematics       12.0.2
@angular-devkit/schematics-cli   12.0.0
@angular/dev-infra-private       0.0.0
@bazel/bazelisk                  1.7.5
@bazel/buildifier                4.0.1
@bazel/concatjs                  3.5.0
@bazel/esbuild                   3.5.0
@bazel/ibazel                    v0.15.8
@bazel/jasmine                   3.5.0
@bazel/protractor                3.5.0
@bazel/rollup                    3.5.0
@bazel/runfiles                  3.5.0
@bazel/typescript                3.5.0
@schematics/angular              12.0.2
rxjs                             6.5.5
typescript                       4.2.4
</code></pre>

**Comment by JoostK** [comment] 2021-06-02 15:10
This is working as intended for the View Engine compiler. The compiler allocates private export names per compilation unit, and since each entry-point is its own compilation unit you'll get duplicate private names among those entry-points. As a consequence, re-exporting all symbols from all these entry-points through another entry-point introduces conflicts.

The Ivy compiler no longer generates private exports and does not have this problem. If you are targeting v12 applications and up, you may want to consider switching to Ivy's partial compilation format that is available since v12. That would be the way forward, given that the View Engine compiler is deprecated.

Alternatively, there's the non-documented `flatModulePrivateSymbolPrefix` compiler option that may help here. Each entry-point can set this to its own unique prefix, such that private symbols no longer conflict when bundled together. AFAICS the `ng_module` Bazel rule should set this automatically when `module_name` is set.

I'll go ahead and close this issue as not otherwise actionable for us, but feel free to continue the discussion below.

**Closed by JoostK** 2021-06-02 15:10 UTC

**Comment by jeripeierSBB** [comment] 2021-06-02 16:02
Hi @JoostK
Thanks a lot for your detailed answer. 

Meanwhile I found out that this is not regression of Angular but a change of Webpack 5.0.0 which introduced an error for conflicting exports (https://github.com/webpack/webpack/commit/163e7674a05bbb95722c6ed01dec5bee761537e9). As Angular 12 uses Webpack 5, we started to receive these errors. Sorry for my wrong statement about Angular regression.

As we have planned to compile our library with Ivy starting with Angular 13, we are currently happy with our workaround and won't spend more time on this issue.
