### ISSUE TITLE
Mat autocomplete input change event bleeds 'event' object

### ISSUE THREAD

**Issue by KissBalazs** [angular/angular#36035] opened 2020-03-12 13:09 UTC
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/material 9.1.2

### Is this a regression?
not sure. 

### Description
The event `(change)` will pass down an "event" object to the handler, even if it's not specified as a parameter. 

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-x78zg6

see the `autocomplete-overview-example.html` lines 6-7, and their correspoding hander on `autocomplete-verview-example.ts`  lines 65-72. 

## 🔥 Exception or Error
console.log shows that we have an "event" object, although it is not defined in the function parameter list. 

## 🌍  Your Environment

**Angular Version:**
see stackblitz dependencies.

**Comment by pkozlowski-opensource** [comment] 2020-03-12 14:21
After a quick scan it looks like a duplicate of #4059 where we've got a conflict between the `(change)` event on an `<input>` and the `change` event raised by a directive. Needs more investigation.

**Comment by KissBalazs** [comment] 2020-03-27 14:24
`<button (click)=handle()>...</button>`

Also bleeds an "event" variable in handler:
```
public handle(){
   console.log(event); //"most of the time" this exists here.
}
```

See this[ Stackblitz example](https://stackblitz.com/edit/angular-zkn1ux). Should I open a new ticket, ir this is the same issue?

**Comment by pkozlowski-opensource** [comment] 2020-03-27 14:28
@KissBalazs I'm sorry but it is not clear from your stackblitz what is the issue that you are trying to illustrate... Is it about "most of the time" this exists here."??? If you are unsure if your issue is different from the one discussed here, please open a new issue but follow the issue template when doing so (most importantly we need a reproduce scenario that shows broken / non-working scenario).

**Comment by KissBalazs** [comment] 2020-03-27 14:38
@pkozlowski-opensource  sorry for the confusion, I have cleared up my comment.

**Comment by pkozlowski-opensource** [comment] 2020-05-06 13:10
@KissBalazs thnx for the additional clarifications! You are totally right to be confused as to why one can access `event`! It turns out, though, that it is not Angular specific but you are bumping into https://developer.mozilla.org/en-US/docs/Web/API/Window/event

The long story short that browsers will expose `event` (for the event being processed) on the window. Since window [acts as a global in the browser environment](https://exploringjs.com/deep-js/ch_global-scope.html), you can access it in your event handler. You would observe the same effect Angular or not.

Going to close this one as it is not specific to Angular but rather to how browsers work. But hey, totally see how this could be confusing!

**Closed by pkozlowski-opensource** 2020-05-06 13:10 UTC
Labels: comp: core, core: event listeners, freq2: medium, severity3: broken, type: bug/fix
