### ISSUE TITLE
Syntax proposal for binding to property of a child component whose name has the same name as the parent component

### ISSUE THREAD

**Issue by OwenKelvin** [angular/angular#36269] opened 2020-03-27 05:53 UTC
# 🚀 feature request

### Relevant Package

This feature request is for @angular/core , @angular/compiler

### Description

Consider a parent and a child component `app-parent` and `app-child` for which we pass property `property1`, `property2` , `property3` that exists in both the parent and the child components

To pass this properties currently we would do the following
```
  <app-parent>
    <app-child 
      [property1]='propery1'
      [property2]='propery2'
      [property3]='propery3' >
    </app-child>
  </app-parent>
```
This can be made shorter

### Proposed Solution

Using of `{ }` to indicate that the property and value is the same
```
  <app-parent>
    <app-child {property1} {property2} {property3}> </app-child>
  </app-parent>
```

OR

using `*` after the property name
```
  <app-parent
    <app-child [property1*] [property2*] [property3*]> </app-child>
  </app-parent>
```

**Comment by pkozlowski-opensource** [comment] 2020-03-27 07:19
This is duplicate of #21136 - please up-vote the mentioned issues and add your proposed syntax in there. Closing as a duplicate of #21136 - let's centralise the discussion in one place.

**Closed by pkozlowski-opensource** 2020-03-27 07:19 UTC
