### ISSUE TITLE
Form's issue - frm.valid fails to update (ControlValueAccessor, NG_VALUE_ACCESSOR, NG_VALIDATORS, NG_ASYNC_VALIDATORS)

### ISSUE THREAD

**Issue by binarydigits** [angular/angular#20458] opened 2017-11-15 17:29 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Form's validation state (ex: myform.valid) does not update when the Custom Form Input Component's state is invalid.

## Expected behavior

Custom Form Input Component's validation state should update the form's state (f.valid) that implements it.
ex: 
<form #f="ngForm">
                    <app-zip-input [(ngModel)]='serviceZip'  name="postcode"></app-zip-input>        </form>
f.valid must be set to false if app-zip-input is invalid

## Minimal reproduction of the problem with instructions
just change the zip/postal code here or remove it completely
https://plnkr.co/edit/KoeQwolcc8UVqfuxBpwu?p=preview

## What is the motivation / use case for changing the behavior?

I think its a problem with ControlValueAccessor or NG_VALIDATORS

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [x] Chrome (desktop) version XX
- [x] Chrome (Android) version XX
- [x] Chrome (iOS) version XX
- [x] Firefox version XX
- [x] Safari (desktop) version XX
- [x] Safari (iOS) version XX
- [x] IE version XX
- [x] Edge version XX
 
For Tooling issues:
- Node version: v8.2.1
- Platform:  Mac, Windows 
- angular: 4.4.6

Others:

</code></pre>

**Comment by tytskyi** [comment] 2017-11-15 21:22
@binarydigits inapropriate usage:
Your form knows nothing about inner `<input>`. 
But actually `ZipInputComponent` is registered **as the input**, and only because you provide `NG_VALUE_ACCESSOR`.

You need to use validators right on the `zip`:

```
    <form #myForm="ngForm">
        <app-zip-input
          [(ngModel)]='serviceZip' 
          name="postcode" 
          required
          pattern="^[ABCEGHJKLMNPRSTVXYabceghjklmnprstvxy][0-9][ABCEGHJKLMNPRSTVWXYZabceghjklmnprstvwxyz]\s?[0-9][ABCEGHJKLMNPRSTVWXYZabceghjklmnprstvwxyz][0-9]$"
        >
        </app-zip-input>
    </form>
    <br>
    myForm.valid = <b> {{ myForm.valid}} <- PROBLEM</b>
```

**Comment by binarydigits** [comment] 2017-11-15 23:31
@tytskyi Hi Oleksandr, thank you for your reply.
No offence, but **you simply re-stated my problem that I have in plnkr**.

> You need to use validators right on the zip
> 

In larger (forms) we have many different components that validate against **data or regular expressions that comes from different services**. To put all of that into parent/host component is an overkill. I believe Angular introduced NG_VALIDATORS to provide custom validation and notify host form about the state of controls that are valid/invalid/etc.

So, I need to move validation to the input components and make sure that the host form knows about the state of the control(s) and reflects that in the form's validation state.

Do you have any other thoughts/ideas about the issue at hand.

Thank you for your time.

**Comment by mlc-mlapis** [comment] 2017-11-16 07:20
@binarydigits ... you can get Injector through `constructor(private _injector: Injector) {}` in your custom component and then get `FormControlName` in `ngAfterViewInit` hook like:
```
ngAfterViewInit() {
	this._formControlName = this._injector.get(FormControlName);
	this.name = this._formControlName.name;
	this.errors = this._formControlName.errors;
```
where you have an access to `name` or `errors`, ...

**Comment by binarydigits** [comment] 2017-11-16 14:27
Hi @mlc-mlapis , I am still not sure how the access to form control name (zip/postal code input) will affect the state of the host form. Could you clarify, or fork my plnkr code please?
The component has access and functions properly when it comes to validation state. **The problem is with the host form**, that does not react to the state of the form control in the custom input component.

**Comment by binarydigits** [comment] 2017-11-16 14:49
@slavafomin Hi, you had a similar issue here ( https://github.com/angular/angular/issues/17736 ) and I wonder if you could take a look at my plnkr and point out why my form's state does not react to the validation state of the custom input component. Thank you

**Comment by kara** [comment] 2017-11-22 00:29
@binarydigits If you want your custom form control to always come with validation, the `NG_VALIDATORS` route is the way to go. The problem in your example is that you're providing the component without actually implementing the `Validator` interface. In other words, you need the `validate` method in your component so the forms API knows *how* to validate your control. 

Updated your example here: https://plnkr.co/edit/MCNkjAslQmL4dEppwt0I?p=preview 

The alternative is validating on the top level as @tytskyi mentioned.

Closing, as this works as intended.

**Closed by kara** 2017-11-22 00:29 UTC
Labels: comp: forms

**Comment by binarydigits** [comment] 2017-12-15 15:35
@kara Hi Kara - sorry for a late reply, I was away.
Your explanation exactly solved my issue - THANK YOU!!!
COULD YOU recommend/share your angular resources such as books/forums?
Best wishes
