### ISSUE TITLE
Using jasmine.clock().install() in unit tests with builderMode set to application throw an error

### ISSUE THREAD

**Issue by MikaStark** [angular/angular#58899] opened 2024-11-26 14:54 UTC
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

Hello everyone !

I started using the new `builderMode` option by setting it to `application` to leverage the power of esbuild for my tests (angular.json). But since all my thousands tests passed before, now I get dozens of random errors across my apps but the common point seems to be the use of `jasmine.clock()` at some key points. I get multiple times this cryptic error : 

`Error: Jasmine Clock was unable to install over custom global timer functions. Is the clock already installed?`

Since I never got this error before setting `builderMode` to `application` I don't see what I'm doing wrong.

So I started a fresh project (just a plain `ng new` hello world app) and just tried to install a clock on the existing unit test. Nothing more. An boom, I got the error I mentionned earlier.
Sorry I can't provide you much more informations as I just don't understand what's going on but I hope someone will find a way to solve this problem which seems to be the source of all my trouble in unit tests with esbuild.

Thank you for your efforts :)

### Please provide the exception or error you saw

```true
Error: Jasmine Clock was unable to install over custom global timer functions. Is the clock already installed?
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 19.0.2
Node: 22.11.0
Package Manager: npm 10.9.1
OS: linux x64

Angular: 19.0.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... material, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1900.2
@angular-devkit/build-angular   19.0.2
@angular-devkit/core            19.0.2
@angular-devkit/schematics      19.0.2
@angular/cli                    19.0.2
@schematics/angular             19.0.2
rxjs                            7.8.1
typescript                      5.6.3
zone.js                         0.15.0
```

### Anything else?

To reproduce : 
- Run `ng new` and keep the default options
- add `"builderMode": "application"` in `angular.json` "test" builder options
- add `jasmine.clock().install();` to `it('should create the app')` unit test (app.component.spec.ts)
- run `ng test`

**Comment by alan-agius4** [comment] 2024-11-27 15:02
Duplicate of https://github.com/angular/angular-cli/issues/28813

**Closed by alan-agius4** 2024-11-27 15:02 UTC
Labels: area: testing
