### ISSUE TITLE
Angular 4 Datefromat Pipe IE error

### ISSUE THREAD

**Issue by StefanKern** [angular/angular#19743] opened 2017-10-16 13:44 UTC
I need to format a date in  `'dd.MM.yyyy, hh:mm'` (standard German format). This works fine in Chrome, FF but doesn't work in IE 11!

Example:

    import { Component }          from '@angular/core';
    
    @Component({
      selector: 'my-app',
      template: `
        <p>{{today | date: 'dd.MM.yyyy, hh:mm' }}</p>
      `
    })
    export class AppComponent {
      today: number = Date.now();
      title = 'Tour of Heroes';
    }

In Chrome, etc it outputs: `16.10.2017, 03:32`

In IE 11: `03:10/16/2017 3:36:51 PM`

What works is `dd.MM.yyyy, HH` which outputs `16.10.2017, 15:00`across all browsers, but why the mintues?

Which makes no sense to me. Accordiong to the documenation `mm` shoud output the minutes.

Demo App:
https://plnkr.co/edit/evzPXttejISsuoEDJHH5?p=preview

Dokumentation:
https://angular.io/api/common/DatePipe

PS: this is a copy of https://stackoverflow.com/questions/46771762/angular-4-datefromat-pipe-ie-error because after writing it, I realized it is a bug

**Comment by trotyl** [comment] 2017-10-16 13:53
Duplicate of https://github.com/angular/angular/issues/9524, https://github.com/angular/angular/issues/10147, https://github.com/angular/angular/issues/16625.

**Comment by tbosch** [comment] 2017-10-16 15:59
Closing as a duplicate. Thanks @trotyl

**Closed by tbosch** 2017-10-16 15:59 UTC
