### ISSUE TITLE
The Custom Element doesn't renderer inside app running in production

### ISSUE THREAD

**Issue by richardlnnr** [angular/angular#30028] opened 2019-04-22 12:41 UTC
# 🐞 bug report

### Affected Package

The issue is caused by package @angular/elements and optimization config

### Is this a regression?

Yes, the previous version in which this bug was not present was: 6

### Description

When the application `main-app` is built using production mode, and the application `custom-element-a` is built using production mode (optimization=true).
The custom-element doesn't renderer inside a router.

## 🔬 Minimal Reproduction

https://github.com/richardlnnr/angular-compiler-issue

Steps to reproduce the error:
For building this project it's necessary running the following steps:

Prepare the static server

* `cd static`
* `npm install`
* `npm start`

Prepare application

* `cd compiler-issue`
* `npm install`
* `npm run package:custom-element-a`
* `npm run start-prod`

When accessing the route `http://localhost:4200/normal-strategy`.
The custom element `<custom-element-a></custom-element-a>` inside this route doesn't render.
Also if you put the custom element in app,component.html the custom element still doesn't rendering.
None error has thrown, just custom element doesn't render.

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 7.3.8
Node: 10.15.1
OS: win32 x64
Angular: 7.2.13
... animations, common, compiler, compiler-cli, core, elements
... forms, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.8
@angular-devkit/build-angular     0.13.8
@angular-devkit/build-optimizer   0.13.8
@angular-devkit/build-webpack     0.13.8
@angular-devkit/core              7.3.8
@angular-devkit/schematics        7.3.8
@angular/cli                      7.3.8
@ngtools/webpack                  7.3.8
@schematics/angular               7.3.8
@schematics/update                0.13.8
rxjs                              6.4.0
typescript                        3.2.4
webpack                           4.29.0
</code></pre>

**Anything else relevant?**

When you build the `custom-element-a` with `--optimization=false` the `main-app` works in production mode, but doesn't work in dev-mode. (`npm run package-prod:custom-element-a`).

When you build the `custom-element-a` with `--optimization=true` the `main-app` doesn't work in production mode, but works in dev-mode. (`npm run package:custom-element-a`)

[Related issue](https://github.com/angular/angular/issues/30027) - I've opened separeted issues because the steps to reproduce the errors and the result are different errors.

**Comment by benoitjchevalier** [comment] 2019-05-06 20:09
We had the same problem, it's actually a webpack config issue. See explanation here: https://github.com/angular/angular/issues/23732#issuecomment-388670907

On our project we took the approach of renaming our `webpackjsonp` for the components bundle using `@angular-builders/custom-webpack`

**Comment by robwormald** [comment] 2019-05-29 20:51
@benoitjchevalier is correct here - closing as a duplicate of #23732

**Closed by robwormald** 2019-05-29 20:51 UTC
Labels: comp: elements
