### ISSUE TITLE
Give access to a component's view index in the parent container

### ISSUE THREAD

**Issue by youdz** [angular/angular#15126] opened 2017-03-13 21:55 UTC
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Right now, there are two ways to get a component's "index":
- Using `*ngFor` and getting the index from the context.
- Using `@ContentChildren` or `@ViewChildren` on a parent component and moving the whatever logic uses the index to said parent component (only works when we are only interested in the index _among components of the same class_).

In cases where both of these are not possible, we have no way of getting a component's index. For instance, if you have a `TemplateRef` that contains several of your component statically:
```html
<template>
  <my-component>AAA<my-component>
  <my-component>BBB<my-component>
  <my-component>CCC<my-component>
</template>
```
The parents that could query for `my-component` are the ones from the original template's location, not the ones from where the template is instantiated.

**Expected behavior**

I do not know if it is possible, but I understand that each component has its own view, which is inserted inside a view container. Having access to the index of that view within its view container would be very useful. 
If this is not possible for some reason, I'd be very interested in knowing why, so I can understand more about the structure of the runtime app.

**Minimal reproduction of the problem with instructions**

This is a feature request, nothing to reproduce.

**What is the motivation / use case for changing the behavior?**

Write "ordered" reusable components, or components that care about the number of siblings before them, that would work in any context (with or without `*ngFor`, inside a template embedded in another part of the app, ...).

* **Angular version:** 2.4.X

* **Browser:** all

 
* **Language:** all

**Comment by DzmitryShylovich** [comment] 2017-03-13 21:59
`ViewContainerRef` has `indexOf` method

**Comment by youdz** [comment] 2017-03-13 22:08
@DzmitryShylovich: I know, but in my example with 
```html
<template>
  <my-component>AAA<my-component>
  <my-component>BBB<my-component>
  <my-component>CCC<my-component>
</template>
```
I do now have access to each component's ViewRef, so I have nothing to pass as the argument to `ViewContainerRef.indexOf(viewRef: ViewRef)`. If I were to dynamically use `ViewContainerRef.createComponent()` or `ViewContainerRef.createEmbeddedView()` to create each instance of `<my-component>` in there, that would work, but here I have a single static template given to me.

**Comment by pkozlowski-opensource** [comment] 2018-06-28 08:01
@youdz I'm having hard time understanding what you are trying to do exactly. It _seems_ like an obvious solution in your case is to use local refs on each component:

 ```html
<template>
  <my-component #first>AAA<my-component>
  <my-component #second>BBB<my-component>
  <my-component #third>CCC<my-component>
</template>
```

Having more info about your _exact_ use case would help us to understand what is missing if the framework and / or suggest an alternative solution.

Could you please elaborate on what you are trying to do, exactly?

**Comment by youdz** [comment] 2018-06-28 12:52
Sure, I can give you a simple but concrete example. For the sake of simplicity I'll ignore the `<ng-template>` part right now (which means `@ContentChildren` becomes a workaround again, but really dirty) but I can make the example more complex in the future if you want me to.

Let's say I want to implement the native ordered list element in Angular. I want this component to be reusable and open source it/publish it on npm. The list component contains any number of items, and each item should automatically be prefixed by it's index in the ordered list. Long story short, the app writes this:
```html
<my-list>
  <my-list-item>foo</my-list-item>
  <my-list-item>bar</my-list-item>
  <my-list-item>baz</my-list-item>
</my-list>
```
and it displays:
```
1. foo
2. bar
3. baz
```

Since the point is to write a reusable component, the `{{index}}` binding or however we generate these numbers has to be either in the template of the `my-list` or the `my-list-item` component, not in the component using them.
Sure if I receive a list of items and a template, I can do it easily. But since developer experience matters, I need to support the case where items are just statically written directly in the HTML template just like above, to make it work as simply as a native ordered list.
And because the list can contain any number of items, I obviously cannot use template reference variable (which you would never want to use as part of a reusable component's API anyway).
Because instantiation order is not the same as DOM order, I cannot do shenanigans in the constructor or `ngOnInit` of my list items.

So all in all, the only way to implement something like this right would be to use `@ContentChildren` in the `my-list` and manually pass the index of each item to the corresponding component instance, something like this:
```typescript
@ContentChildren(MyListItemComponent) items: QueryList<MyListItemComponent>;

items.foreach((item, index) => item.index = index);
```
Not only would this require a subscription to the `QueryList` changes to handle dynamic cases, it would *instantly trigger an "Expression has changed after it was checked" error*.

Since the list items are all siblings inside of the same parent view, and Angular obviously knows about their index since the `QueryList` from `@ContentChildren` has them, I would like to be able to access this index from the list item component directly, probably through injection.

I hope this clarifies the request, if not I'll be happy to discuss it more. 🙂

**Comment by pkozlowski-opensource** [comment] 2018-06-28 14:31
@youdz thnx for more details, I _think_ I know where it is gong to end up but let me entertain you (and myself) just a bit more. How about this one: https://stackblitz.com/edit/angular-otci3v?file=src%2Fapp%2Fapp.component.ts

**Comment by youdz** [comment] 2018-06-28 16:35
As I said in my previous post, instantiation order is different from DOM order. For instance the list items are dynamic and change over time.

But even simpler than that, the way structural directives work change the instantiation order, so even just using `*ngIf="true"` in your example breaks it: https://stackblitz.com/edit/angular-u9zc9b?file=src/app/app.component.ts

**Comment by pkozlowski-opensource** [comment] 2018-06-28 17:11
> But even simpler than that, the way structural directives work change the instantiation order, so even just using *ngIf="true" in your example breaks it

Exactly! I was hoping that you will bring it up :-) 

So, now, the best you can do in the current view engine is this:

```html
 <my-list>
    <ng-template my-list-item>foo</ng-template>
    <ng-template my-list-item>bar</ng-template>
    <ng-template *ngIf="true" my-list-item>bar2</ng-template>
    <ng-template my-list-item>baz</ng-template>
  </my-list>
```

See: https://stackblitz.com/edit/angular-kaligq?file=src/app/app.component.ts

I can _almost_ hear you saying - but this is not the API I / my users want! And you would be right and this is what we are planing on solving via #8563. I _know_ it is an old issue but your use-case is _classical_ example of what we want to support _easily_.

I'm afraid that the best you can do for now is shown above, we will work towards better API via #8563.

**Comment by pkozlowski-opensource** [comment] 2018-06-28 20:09
>  I apologize for not having the time to create StackBlitz examples for every one of these use cases right now, hopefully I can find some time at some point to write one of the more complex ones.

@youdz no worries, I understand _perfectly_ what are the issues you are hitting and what you miss - I've been banging my head against those things for some time now. So here is the plan:
* we want to finish ngIvy rewrite as the new algorithm will enable new APIs and new constructs;
* we want to design more dynamic content projection system for which your use-case is a classic / model one.

> I've been following #8563 since its creation and I can't wait until it's up, but I'm trying to be realistic and I know it is not happening anytime soon

This is hard stuff so it will naturally take time. But to be honest your 2 options for now, realistically speaking, are:
* stick with the `<ng-template>`-based API I've proposed above;
* wait for the resolution of  #8563 for better APIs.

There are hacks in between but if you want to have something that is in-line with the spirit of the framework than there are just 2 options above.

I'm going to close this as a duplicate of #8563 as I believe that only resolution of that issue can bring APIs that are flexible and feel natural. It will take time but we will get there.

**Closed by pkozlowski-opensource** 2018-06-28 20:09 UTC
Labels: comp: core & compiler, flag: can be closed?, type: feature
