### ISSUE TITLE
Support innert script tags in templates / JSON-LD support

### ISSUE THREAD

**Issue by ianbelcher** [angular/angular#9695] opened 2016-06-29 06:30 UTC
**I'm submitting a ...**  (check one with "x")

```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Due to script tags being stripped from component templates, there is no way to implement JSON-LD tags.
Further discussion on this topic can be found [here](http://stackoverflow.com/questions/38088996/adding-script-tags-in-angular2-component-template) and #2766

**Expected/desired behavior**
Using angular-universal and on sites implementing pure client side rendering, there needs to be a way for users of angular2 to implement JSON-LD tags for SEO purposes. At the moment this is not possible.

**What is the motivation / use case for changing the behavior?**
Google recommend JSON-LD for structured data. The alternative of using micro data is also not a very good idea as this data would be disseminated throughout the templates of many, if not all components.

**Comment by pxwise** [comment] 2016-09-30 20:41
Beyond the JSON-LD use case, it is necessary for script tags to be available for server side rendering when using angular to generate the entire HTML document. Ideally I would like our team to only need to know one templating language instead of needing something like mustache for a dynamic server rendered html structure, capable of generating the `<script src="/index.js"></script>` tag.

An example of my Body template that worked previously with RC4 looked like this:

```
    <app>Loading...</app>

  <template ngFor let-item [ngForOf]="config?.scripts" let-i="index">
    <script [attr.src]="sanitizeHref(item)"></script>
  </template>

    <script src="/index.js"></script>
```
Neither script tag renders in 2.0 final.

Perhaps an escape hatch in DomSanitizer could allow script tags?

**Comment by mlakmal** [comment] 2016-10-05 11:06
We use same mechanism to inject locale content to components, with templates served from server side CMS. It would be nice to override this at sanitizer level...

**Comment by kblestarge** [comment] 2017-03-30 18:29
+1 for this feature request.
Also, I would greatly appreciate some insight into my question [here](http://stackoverflow.com/questions/43125653/will-google-recognize-index-microdata-or-rdfa-markup-in-template-of-angular-spa).

**Comment by nicky-lenaers** [comment] 2017-04-21 15:07
I'd like to see support for JSON-LD too, since it's the recommended way by Google. Any news on this?

**Comment by nicky-lenaers** [comment] 2017-04-22 13:17
My current workaround. Works **in both server and browser context**:

**Component Implementation**
```sh
import { Renderer2, OnInit, Inject } from '@angular/core';
import { DOCUMENT } from '@angular/platform-browser';

class MyComponent implements OnInit {

    constructor(private _renderer2: Renderer2, @Inject(DOCUMENT) private _document) {

    }

    public ngOnInit() {

        let s = this._renderer2.createElement('script');
        s.type = `application/ld+json`;
        s.text = `
            {
                "@context": "https://schema.org"
                /* your schema.org microdata goes here */
            }
        `;

        this._renderer2.appendChild(this._document.body, s);
    }
}
```

**Service Implementation**
```sh
import { Renderer2, Inject } from '@angular/core';
import { DOCUMENT } from '@angular/platform-browser';

class MyService {

    constructor(@Inject(DOCUMENT) private _document) {

    }

    /**
     * Set JSON-LD Microdata on the Document Body.
     *
     * @param renderer2             The Angular Renderer
     * @param data                  The data for the JSON-LD script
     * @returns void
     */
    public setJsonLd(renderer2: Renderer2, data: any): void {

        let s = renderer2.createElement('script');
        s.type = `application/ld+json`;
        s.text = `${JSON.stringify(data)}`;

        renderer2.appendChild(this._document.body, s);
    }
}
```

**Comment by esistgut** [comment] 2017-08-11 15:52
@nicky-lenaers this currently appear to work only in browser context. I'm on 4.3.4. Can you confirm it please?

**Comment by nicky-lenaers** [comment] 2017-08-11 15:58
Yes, that is correct. It merely prevents errors that occur when nog using the Renderer2 to add script tags. I've come across solutions using unsafe html templates which at least work server-side, but it's all hacky. There should be better ways to handle this I guess.

**Comment by esistgut** [comment] 2017-08-11 16:02
Please share your solution, I need to render jsonLD metadata and I can't wait for an official update on this.

**Comment by Moenomi** [comment] 2017-08-29 08:52
@nicky-lenaers what is the purpose of your workaround? The jason-ld in browser context does not help for SEO, so it has to work on SSR as well, right? Or am I wrong and it is enough to have the data after the Angular app has bootsrapped in the browser.

**Comment by naveedahmed1** [comment] 2017-09-26 11:03
Is there any update on this?

**Comment by coryrylan** [comment] 2017-11-05 16:40
For anyone who still needs json-ld support in their Angular app I made this super small component that makes it easy to use. This also works with Universal SSR. https://github.com/coryrylan/ngx-json-ld

**Comment by pkozlowski-opensource** [comment] 2019-03-09 14:54
This is a duplicate of #26293 - let's centralise the discussion in there. Closing as a duplicate.

**Closed by pkozlowski-opensource** 2019-03-09 14:54 UTC
Labels: comp: core & compiler, freq2: medium, hotlist: community-help, type: feature
