### ISSUE TITLE
ngClass removes the classes set on the second digest cycle (dev mode)

### ISSUE THREAD

**Issue by koblass** [angular/angular#8008] opened 2016-04-11 10:23 UTC
If I set something like this:

    <red>This component should have the 'red' css class</red>

    @Component({
        selector: 'red',
        template : `<div [ngClass]="getClasses()"><ng-content></ng-content></div>`
    })
    export class RedComponent {
        getClasses() {
            return {
                'red' : true
            };
        }
    }

This is working during the first "digest", but the second (Dev mode) is removing the class.

If I do something like this, this is working.

    @Component({
        selector: 'red',
        template : `<div [ngClass]="getClasses()"><ng-content></ng-content></div>`
    })
    export class RedComponent {
        classes: {
            'red' : true
        };

        getClasses() {
            return classes;
        }
    }

I think this is a bug, because dev mode shouldn't impact the resulting output.

**Comment by pkozlowski-opensource** [comment] 2016-04-11 10:33
Duplicate of #7426

**Closed by pkozlowski-opensource** 2016-04-11 10:33 UTC

**Comment by koblass** [comment] 2016-04-11 10:49
Oups, you're right, sorry about this.
