### ISSUE TITLE
RC.5 not rendering children components when minified with webpack -p (1.13.1)

### ISSUE THREAD

**Issue by KamelJabber** [angular/angular#10682] opened 2016-08-11 13:02 UTC
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When executing "webpack -p" against existing project w/o any changes other than upgrading the version number from rc.4 -> rc.5 (aka, not converting code to use NgModule), child components do not get rendered.

"webpack -p" works when the version is rc.4 and also works  with rc.5 with "webpack -d"

**Expected/desired behavior**
Expected for the minified code via "webpack -p" would render all components like it does with rc.4

**Angular version** 2.0.0-rc.5
 
**Browser** latest Chrome
 
**Language** TypeScript 1.8.7 | ES6; generated from VS 2015

**Comment by kylecordes** [comment] 2016-08-11 13:07
I think this is the same problem as #10618. See discussion there, with simple example that reproduces the problem.

**Comment by KamelJabber** [comment] 2016-08-11 13:50
Oh, I searched for "webpack" before posting a bug.  I should have looked for "minified" or similar.

Thanks!

I'll check out that discussion, a quick review does appear to be the same or similar to my issue.

**Comment by pkozlowski-opensource** [comment] 2016-08-11 13:54
Closing as a duplicate of #10618. Thnx @kylecordes

**Closed by pkozlowski-opensource** 2016-08-11 13:54 UTC
