### ISSUE TITLE
docs: failed: error executing command

### ISSUE THREAD

**Issue by fendypurnomo** [angular/angular#55877] opened 2024-05-19 16:10 UTC
### Describe the problem that you experienced

i am cloning `angular repo` and i build and running on `Windows 10 - WSL Ubuntu`, but got an error in below:

```
ubuntu@DESKTOP-762MEHV:~/angular$ yarn docs
yarn run v1.22.19
$ [[ -n $CI ]] && echo 'Cannot run this yarn script on CI' && exit 1 || yarn bazel run //adev:serve --fast_adev
/bin/sh: 1: [[: not found
$ /home/ubuntu/angular/node_modules/.bin/bazel run //adev:serve --fast_adev
INFO: Analyzed target //adev:serve (1 packages loaded, 2632 targets configured).
INFO: Found 1 target...
ERROR: /home/ubuntu/angular/adev/src/content/guide/components/BUILD.bazel:3:16: Action adev/src/content/guide/components/advanced-configuration.md.html failed: (Exit 1): markdown.sh failed: error executing command bazel-out/k8-opt-exec-2B5CBBC6/bin/external/npm/@angular/docs/pipeline/markdown.sh bazel-out/k8-fastbuild/bin/adev/src/content/guide/components/advanced-configuration.md.html-0.params ... (remaining 1 argument skipped)

Use --sandbox_debug to see verbose messages from the sandbox

/home/ubuntu/.cache/bazel/_bazel_ubuntu/d3c6983be73d8c916ce88d5800bb1c6f/sandbox/processwrapper-sandbox/426/execroot/angular/external/npm/@angular/docs/pipeline/guides.mjs:48704
  const browser = await chromium.launch({
                                 ^
browserType.launch: Target page, context or browser has been closed
Browser logs:

<launching> /home/ubuntu/.cache/bazel/_bazel_ubuntu/d3c6983be73d8c916ce88d5800bb1c6f/sandbox/processwrapper-sandbox/426/execroot/angular/bazel-out/k8-opt-exec-2B5CBBC6/bin/external/npm/@angular/docs/pipeline/markdown.sh.runfiles/org_chromium_chromium_linux_x64/chrome-linux/chrome --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate,HttpsUpgrades,PaintHolding --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --disable-search-engine-choice-screen --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --no-sandbox --user-data-dir=/tmp/playwright_chromiumdev_profile-Fs1trd --remote-debugging-pipe --no-startup-window
<launched> pid=11102
[pid=11102][err] /home/ubuntu/.cache/bazel/_bazel_ubuntu/d3c6983be73d8c916ce88d5800bb1c6f/sandbox/processwrapper-sandbox/426/execroot/angular/bazel-out/k8-opt-exec-2B5CBBC6/bin/external/npm/@angular/docs/pipeline/markdown.sh.runfiles/org_chromium_chromium_linux_x64/chrome-linux/chrome: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory
Call log:
  - <launching> /home/ubuntu/.cache/bazel/_bazel_ubuntu/d3c6983be73d8c916ce88d5800bb1c6f/sandbox/processwrapper-sandbox/426/execroot/angular/bazel-out/k8-opt-exec-2B5CBBC6/bin/external/npm/@angular/docs/pipeline/markdown.sh.runfiles/org_chromium_chromium_linux_x64/chrome-linux/chrome --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate,HttpsUpgrades,PaintHolding --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --disable-search-engine-choice-screen --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --no-sandbox --user-data-dir=/tmp/playwright_chromiumdev_profile-Fs1trd --remote-debugging-pipe --no-startup-window
  - <launched> pid=11102
  - [pid=11102][err] /home/ubuntu/.cache/bazel/_bazel_ubuntu/d3c6983be73d8c916ce88d5800bb1c6f/sandbox/processwrapper-sandbox/426/execroot/angular/bazel-out/k8-opt-exec-2B5CBBC6/bin/external/npm/@angular/docs/pipeline/markdown.sh.runfiles/org_chromium_chromium_linux_x64/chrome-linux/chrome: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory

    at Object.processMermaidCodeBlock (/home/ubuntu/.cache/bazel/_bazel_ubuntu/d3c6983be73d8c916ce88d5800bb1c6f/sandbox/processwrapper-sandbox/426/execroot/angular/external/npm/@angular/docs/pipeline/guides.mjs:48704:34)
    at Marked.walkTokens2 (/home/ubuntu/.cache/bazel/_bazel_ubuntu/d3c6983be73d8c916ce88d5800bb1c6f/sandbox/processwrapper-sandbox/426/execroot/angular/external/npm/@angular/docs/pipeline/guides.mjs:52199:84)
    at main (/home/ubuntu/.cache/bazel/_bazel_ubuntu/d3c6983be73d8c916ce88d5800bb1c6f/sandbox/processwrapper-sandbox/426/execroot/angular/external/npm/@angular/docs/pipeline/guides.mjs:52240:31)
Target //adev:serve failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /home/ubuntu/angular/adev/src/assets/BUILD.bazel:5:18 Copying files to directory failed: (Exit 1): markdown.sh failed: error executing command bazel-out/k8-opt-exec-2B5CBBC6/bin/external/npm/@angular/docs/pipeline/markdown.sh bazel-out/k8-fastbuild/bin/adev/src/content/guide/components/advanced-configuration.md.html-0.params ... (remaining 1 argument skipped)

Use --sandbox_debug to see verbose messages from the sandbox
INFO: Elapsed time: 123.746s, Critical Path: 81.17s
INFO: 5 processes: 5 internal.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by JeanMeche** [comment] 2024-05-19 17:47
Duplicate of #55856

**Closed by JeanMeche** 2024-05-19 17:47 UTC
