### ISSUE TITLE
Dart Output In Quickstart Is Massive

### ISSUE THREAD

**Issue by rightisleft** [angular/angular#1836] opened 2015-05-12 12:26 UTC
I just ran through the demo for Dart here:

https://angular.io/docs/dart/latest/quickstart.html

* Running through the built in Dart2JS transformer via pub serve results in a 5.2 MB main.dart.js file
* Running through pub build results in a 2.5 MB main.dart.js file

**Comment by matanlurey** [comment] 2015-05-12 14:26
Right now Dart only (formally) supports operation using reflection (mirrors), which disables tree-shaking code that is unused (including core libraries, etc). Angular 2 includes a (in development) transformer that removes reflection and replaces with statically generated code that makes the size more normal.

You can try this in your `pubspec.yaml`:
```yaml
transformers:
- angular2
```

**Comment by jbdeboer** [comment] 2015-05-12 17:35
Since transformers are mostly transparent; this bug should be fixed by added that ```transformers``` line to the quickstart pubspec.yaml

@rightisleft If you have success with @matanlurey's suggestion, could you send a PR?

**Comment by rightisleft** [comment] 2015-05-12 22:18
I'm not seeing any change:

$  angular2  cat pubspec.yaml 
name: hello_world
version: 0.0.1
dependencies:
  angular2: any
  browser: any
transformers:
-  angular2

Results from pub build : 2.5MB

**Comment by matanlurey** [comment] 2015-05-13 03:27
Ah I think you need to tell the transformer which file is your entrypoint. See Angular's (own example)[https://github.com/angular/angular/blob/master/modules/examples/pubspec.yaml]). @kegluneq, shouldn't the transformer warn you if it's missing an entrypoint, or what is the default expected behavior?

**Comment by rightisleft** [comment] 2015-05-13 14:08
This worked for me: 403KB - this is less terrifying. Should I open a bug on angular.io? 

name: 'angular_2_quickstart'
environment:
  sdk: '>=1.10.0-dev.1.10 <2.0.0'
dependencies:
  angular2: any
  browser: '^0.10.0'
transformers:
- angular2:
    entry_points:
        - web/main.dart
    reflection_entry_points:
        - web/main.dart
- $dart2js:
    minify: true
    commandLineOptions:
    - --dump-info
    - --show-package-warnings
    - --trust-type-annotations
    - --trust-primitives

**Comment by kegluneq** [comment] 2015-05-13 16:04
This is a rough edge - there are situations where we need to run the angular transformer without entry points which is why there are no warnings, but there are ways to make this work.

Just opened https://github.com/angular/angular/issues/1872 to track

**Comment by mhevery** [comment] 2015-06-01 01:22
Duplicate, since we are tracking it elsewhere.

**Closed by mhevery** 2015-06-01 01:22 UTC

**Comment by stevenroose** [comment] 2016-10-13 15:51
The `build/` folder after the Quickstart is still 8.5 MB, which is crazy large.

**Comment by zoechi** [comment] 2016-11-05 11:02
Have you checked if everything is loaded into the browser?
There are some limitations with `pub` that prevent of getting rid of some files but they are never loaded by the browser.
At the Dart Summit and Angular2 Dart release they mentioned that they notably reduced the build output size and are still working to further improve.
Anyway the repo for Angular2 Dart is https://github.com/dart-lang/angular2
