### ISSUE TITLE
host-context selector combined with html element issue

### ISSUE THREAD

**Issue by brianmtreese** [angular/angular#31478] opened 2019-07-09 21:08 UTC
# 🐞 Bug report

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 7.x

### Description

The :host-context pseudo class emulation appears to have changed from version 7.x to 8.x. In 7.x versions the following code:
```
:host-context(.test)my-app {
    color: purple;
}
```

would result in the following after compiling:
```
.testmy-app[_nghost-xti-c0], .test my-app[_nghost-xti-c0] {
    color: purple;
}
```

The first would not match anything but the second would.

In 8.x this now results in the following after compiling:
```
.test[_nghost-xti-c0] my-app[_ngcontent-xti-c0], .test [_nghost-xti-c0] my-app[_ngcontent-xti-c0] {
    color: purple;
}
```
In this case, niether match. However, in both versions, if changed to a class instead of an element it works correctly. So in both 7.x and 8.x versions the following:

```
:host-context(.test).my-class {
    color: purple;
}
```

would result in the following after compiling:
```
.test.my-class[_nghost-xti-c0], .test .my-class[_nghost-xti-c0] {
    color: purple;
}
```
So it appears as if the :host-context selector is now only properly emulated when using a class selector but not when using an element selector.

## 🔬 Minimal Reproduction
7.x working correctly: https://github.com/brianmtreese/host-context-element-selector-issue-7-x

8.x working differently: https://github.com/brianmtreese/host-context-element-selector-issue-8-x

## 🌍 Your Environment
<pre><code>Angular CLI: 8.0.6
Node: 11.9.0
OS: win32 x64
Angular: 8.1.0
... common, compiler, core, forms, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.6
@angular-devkit/build-angular     0.800.6
@angular-devkit/build-optimizer   0.800.6
@angular-devkit/build-webpack     0.800.6
@angular-devkit/core              8.0.6
@angular-devkit/schematics        8.0.6
@angular/cli                      8.0.6
@angular/compiler-cli             8.0.3
@angular/language-service         7.0.4
@ngtools/webpack                  8.0.6
@schematics/angular               8.0.6
@schematics/update                0.800.6
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.30.0
</code></pre>

**Comment by JoostK** [comment] 2020-10-25 20:21
I can't reproduce the difference between 7 and 8. I'm seeing the same output for 7, 8 and 11. Also, there haven't been any changes to the emulation transform between 7 and 8.

Regardless of the above, the emulation transform seems to be incorrect with the creation of `.testmy-app`; I'm not sure if `:host-context(.test)my-app` even makes sense, so I can't tell what needs to happen here.

**Comment by petebacondarwin** [comment] 2021-01-23 21:21
This combination is not valid. Instead you need to do:

```
:host-context(my-app.test) { ... }
```

I don't know about this being a regression but given that we are on v11 now and this is not actually valid I am going to close this.

**Closed by petebacondarwin** 2021-01-23 21:21 UTC
Labels: P4, comp: core, core: CSS encapsulation, freq1: low, type: bug/fix
