### ISSUE TITLE
For the benefit of new users, please emit an error for `*ngFor="let b in a"` instead of `*ngFor="let b of a"`

### ISSUE THREAD

**Issue by otac0n** [angular/angular#37869] opened 2020-07-01 08:51 UTC
# 🚀 feature request

### Description
I've repeatedly experienced inconvenience with the expression format `*ngFor="let ... in ..."`. Each time, I have had to take the penalty of a full build of my whole project folder before I noticed the issue.  Please fail the build sooner; I have to imagine this impacts new users even more often.

### Describe the solution you'd like
In AOT, emit an error.  In my project, no error is emitted before runtime.

### Describe alternatives you've considered
This is a request for new users.

**Comment by JoostK** [comment] 2020-07-02 19:28
Related to #37322 (same situation basically)

**Comment by alxhub** [comment] 2021-07-09 23:43
Closing as a duplicate of #37322.

**Closed by alxhub** 2021-07-09 23:43 UTC
Labels: comp: compiler, compiler: parser, feature, hotlist: error messages, insufficient votes, votes required
