### ISSUE TITLE
route resolvers are invoked before APP_INITIALIZER promise(s) have been resolved

### ISSUE THREAD

**Issue by nelisbijl** [angular/angular#14759] opened 2017-02-27 11:37 UTC
**I'm submitting a ...**  (check one with "x")
[x ] bug report => search github for a similar issue or PR before submitting

**Current behavior**
Related to #9047. AppConfig is loaded using APP_INITIALIZER. Before the returned promise has been resolved, the initializer for the requested route is already invoked. The initializer will fail if it requires settings from AppConfig

**Expected behavior**

The route resolvers should be invoked after the APP_INITIALIZER promise(s) have been resolved

**Minimal reproduction of the problem with instructions**
https://plnkr.co/edit/PbTGxQ2X1aKUVfUvJdcO?p=preview

**What is the motivation / use case for changing the behavior?**
Use API url from AppConfig in a resolver

**Please tell us about your environment:**
Not relevant

* **Angular version:** 2.0.X
2.4.8 (I have not tried downgrading but I thought is was working properly in 2.4.7)

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome but does not seem relevant
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript

**Comment by DzmitryShylovich** [comment] 2017-02-27 12:13
duplicate of https://github.com/angular/angular/issues/14588 ?

**Comment by nelisbijl** [comment] 2017-02-27 13:38
You are probably right

**Comment by DzmitryShylovich** [comment] 2017-02-27 13:42
>  I thought is was working properly in 2.4.7

yeah, it's a duplicate. the commit will be reverted in the next release so I think you can sloe this.

**Closed** 2017-02-27 17:18 UTC
