### ISSUE TITLE
Angular Elements doesn't works when use document.createElement after page load

### ISSUE THREAD

**Issue by KonstantinAlexeevich** [angular/angular#25387] opened 2018-08-08 15:03 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[*] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
Angular Elements doesn't works when use <code>document.createElement('app-root')</code> after page load.

## Expected behavior
components works

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-gitter-tkxb19

see index.html

## What is the motivation / use case for changing the behavior?
this is bug.

## Environment

<pre><code>
Angular version: 6.0.0
Latest version of Angular too. I Check it.

Browser:
- [*] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 9.11.1
- Platform:  Windows

Others:
VS Code 
Stackblitz.com

**Comment by trotyl** [comment] 2018-08-08 15:28
Duplicate of https://github.com/angular/angular/issues/24181

**Comment by KonstantinAlexeevich** [comment] 2018-08-08 15:56
Thanks!

**Closed** 2018-08-08 16:02 UTC

**Comment by trotyl** [comment] 2018-08-08 16:04
No worries, making a minimal production helps a lot in identifying the problem. 😃
