### ISSUE TITLE
Form not changing to dirty after updating the Group using Form Builder

### ISSUE THREAD

**Issue by mohammedzamakhan** [angular/angular#7907] opened 2016-04-04 16:07 UTC
***Demo***: http://plnkr.co/edit/qyP9Gba7vzCx6EhEqgmp?p=preview

**Expected Behavior**: Form Validation should work properly even after resetting the form

**Current Behavior**: The form is not changing to dirty after you click on the update button which is basically re instantiating the form.

**Comment by kara** [comment] 2016-09-09 02:29
@mohammedzamakhan We model the "touched" and "dirty" properties based on direct user interaction with the form control, not on change in value. Only when **a user** changes a value in the UI does it become dirty.   The utility of these properties is based on insight into how the user has interacted with your form.   It's trivial to detect when your application has dirtied a form programmatically because that is code you've called yourself.  

So when you change the value of your form control programmatically, it is actually by design that the these properties are not updated.  This way, it is simple to distinguish between effects that the user has had as opposed to effects the application code might have had.

In the case that some controls do need to be marked as dirty once your app updates a value, you can deliberately choose to call `markAsDirty()`, and that should work.

**Closed by kara** 2016-09-09 02:29 UTC
Labels: comp: forms
