### ISSUE TITLE
ReferenceError after update to 11.2.6 when using default exports

### ISSUE THREAD

**Issue by Eldelshell** [angular/angular#41377] opened 2021-03-30 10:45 UTC
# 🐞 bug report

### Affected Package

The issue is caused by package @angular/core and `ng serve`

### Is this a regression?

Yes, the previous version in which this bug was not present was: 11.0.9

### Description

After updating to 11.2.6 any Injectable which is modified while the `ng serve` is running, will throw an error.

A very simple example:

<pre><code>
@Injectable({
    providedIn: 'root'
})
export default class ViewsCommonService {
  ...
}
</code></pre>

## 🔥 Exception or Error
<pre><code>
ReferenceError: ViewsCommonService is not defined
    at NodeInjectorFactory.AppComponent_Factory [as factory] (app.component.ts:5)
    at getNodeInjectable (core.js:3548)
    at instantiateRootComponent (core.js:10088)
    at createRootComponent (core.js:12395)
    at ComponentFactory$1.create (core.js:25038)
    at ApplicationRef.bootstrap (core.js:29451)
    at core.js:29164
    at Array.forEach (<anonymous>)
    at PlatformRef._moduleDoBootstrap (core.js:29164)
    at core.js:29134
</code></pre>

## 🌍  Your Environment

<pre><code>
Angular CLI: 11.2.6
Node: 15.11.0
OS: linux x64

Angular: 11.2.7
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.6
@angular-devkit/build-angular   0.1102.6
@angular-devkit/core            11.2.6
@angular-devkit/schematics      11.2.6
@angular/cli                    11.2.6
@schematics/angular             11.2.6
@schematics/update              0.1102.6
rxjs                            6.6.7
typescript                      4.0.7
</code></pre>

## Workaround

The only workaround is to restart `ng serve`

**Comment by JoostK** [comment] 2021-03-30 11:23
I cannot reproduce using a new CLI project and an injectable declared in `test.ts` which is then injected into a component constructor.

Could you please share a Github repo and reproduction steps so we can investigate further?

**Comment by Eldelshell** [comment] 2021-03-30 11:25
@JoostK here:

https://github.com/Eldelshell/angular-41377

**Comment by Eldelshell** [comment] 2021-03-30 11:25
More information about the environment:

```
$ npm --version
7.6.0

$ node --version
v15.11.0
```

**Comment by JoostK** [comment] 2021-03-30 11:40
Ok, it's a `default export` thing. I can workaround by reverting to the legacy CLI pipeline using the environment variable `NG_BUILD_IVY_LEGACY=1`. More investigation is needed what the exact cause is here.

**Comment by Eldelshell** [comment] 2021-03-30 11:44
@JoostK confirmed. Removing the `default` from the class declaration and modifying the imports is a workaround.

**Comment by JoostK** [comment] 2021-03-30 16:27
So our current hypothesis is that this has always been broken in the Angular compiler, but it didn't surface as the CLI wasn't requesting all files that needed to be updated during an incremental rebuild. That has been fixed in the new pipeline since 11.1, which now causes the default export issue to appear.

**Comment by RA80533** [comment] 2021-04-06 02:30
Related #41463

**Comment by JoostK** [comment] 2021-04-10 21:05
While working on a fix I realized this can also be worked around by making the DI token explicit:

```ts
@Injectable()
export default class DefaultService {}
```

```ts
@Injectable()
import DefaultService from './default';

export class Example {
  constructor(@Inject(DefaultService) private defaultService: DefaultService) {}
}
```

**Comment by RA80533** [comment] 2021-04-10 22:49
I can't seem to reproduce the issue after cloning the repository. How were you able to get it, @JoostK?

**Comment by JoostK** [comment] 2021-04-11 12:38
> I can't seem to reproduce the issue after cloning the repository. How were you able to get it, @JoostK?

I cloned https://github.com/Eldelshell/angular-41377, ran `yarn ng serve`/`npm run ng serve` and opened the site to see it work, then changed something in `src/app/my.service.ts`. After the browser has refreshed you should get the error.

You can also check the testcase that reproduces the bug [in #41557](https://github.com/angular/angular/pull/41557/commits/a828e85d4cf4526f1738b0a865e2ebe7befd5a4d#diff-412639ceb2878836a42f63778639172c8c20d2c9a02d664f6e904964fdfefbce).

**Closed** 2021-04-13 00:05 UTC
Labels: P3, comp: compiler, state: has PR
