### ISSUE TITLE
typescript use i18n

### ISSUE THREAD

**Issue by Jin-wei** [angular/angular#31775] opened 2019-07-22 07:14 UTC
Oh hi there! 😄 

I was doing Internationalization (i18n) recently. 
In the HTML,it is work. But,in the typescript, I don't know how to do it.
If you know, please tell me！

**Comment by trotyl** [comment] 2019-07-22 08:13
Duplicate of https://github.com/angular/angular/issues/11405

**Closed** 2019-07-22 09:02 UTC
