### ISSUE TITLE
A required checkbox should always be invalid if unchecked

### ISSUE THREAD

**Issue by mirkonasato** [angular/angular#11459] opened 2016-09-08 20:55 UTC
**I'm submitting a ...**  (check one with "x")

```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Given an `<input type="checkbox">` with the `required` attribute, `ngModel` correctly considers it invalid to start with. Checking it correctly makes it valid, but after unchecking it it's still valid.

**Expected behavior**

A required checkbox should always be invalid if it's not checked.

**Reproduction of the problem**

http://plnkr.co/edit/GZI2fiZ65qtJQIjJbZLh?p=preview

**What is the motivation / use case for changing the behavior?**

HTML5 Form Validation doesn't allow submitting a form if a required checkbox is unchecked. (Or at least that's how Chrome and Firefox work.)
- **Angular version:** 2.0.0-rc.6
- **Browser:** [all] 
- **Language:** [all]

**Comment by gerardbrunoquantion** [comment] 2016-09-09 11:10
Not yet documented

**Comment by mirkonasato** [comment] 2016-09-09 11:17
To clarify the use case, suppose you have a typical registration form with a checkbox at the end saying something like "I accept the Terms & Conditions". How do you ensure the checkbox must be ticked if not by declaring it as required?

**Comment by pkozlowski-opensource** [comment] 2016-09-09 13:54
Yeh, this looks like a valid bug. 

There are 2 ways of fixing it I can think of:
* quick & dirty: make the `CheckboxControlValueAccessor` write `null` instead of `false` when unchecked - not ideal as it is going to change model value assigned 
* have a separate `RequiredValidator` for checkboxes (we should probably also think of radios)

@kara I can PR this one if you could confirm that a checkbox-specific `RequiredValidator` is the way to go.

**Comment by mirkonasato** [comment] 2016-09-09 14:34
The "quick & dirty" fix wouldn't work if the model itself is initialised to `false` I guess? I.e. this case: http://plnkr.co/edit/fHpNhAQD2ZUvq5xpYL3R?p=preview

**Comment by joaquinloustau** [comment] 2016-09-27 17:40
Hi, I just ran into the same issue and was wondering if a fix has been pushed. 

Thanks!

**Comment by AKApumkin** [comment] 2016-10-04 03:46
For thoes using the reactive forms method and needing a quick hacked fix, 
```
//part of the constructor 
    this.registerForm = fb.group({
        'answer': ['someAnser', Validators.required],
         'confirmCheckbox':  ['', Validators.required]
	 },
     {validator: checkPasswords, checkCheckbox}) //checkPassword is another custom validator

//the function
function checkCheckbox(c: AbstractControl){
    if(c.get('confirmCheckbox').value == false){
        return false;
    }else return true;
} 

// In the template
	<button type="submit" id="btnSubmitRegister" class="pwFeildButton" 
	[disabled]="!registerForm.valid || registerForm.get('confirmCheckbox').value != true">
       1337 buttonz
       </button>
```

**Comment by kara** [comment] 2016-10-12 17:31
@pkozlowski-opensource  The second solution with the validator seems reasonable if you have time to take it on.

**Comment by asotog** [comment] 2016-10-20 13:53
This was "working" on Angular 1

**Comment by paynoattn** [comment] 2016-11-03 18:36
Further updates for this bug.

@mirkonasato the reason why this is happening is because after you uncheck a checkbox when assigned with ngModel it does not change the value. 

Additionally, as of ```2.1.0``` any checkbox in a form with a value of false, even if it's not required, renders the entire form invalid.

To get proper checkbox functionality you must remove it from your formgroup, and use the following code:

html:
```
<input type="checkbox"  id="my-check"  (change)="onChange($event)" [checked]="checkModel" />
<label for="my-check">Is Checked?</label>
```

ts:
```
onChange($event) {
  this.checkModel = $event.target.checked;
}
```

The desired behavior is that ngModel should handle this by sending either a true/false value to the model, and then a form should only accept a true/false value to be valid.

**Closed** 2016-12-14 16:53 UTC
Labels: comp: forms, freq3: high, severity3: broken, type: bug

**Comment by asotog** [comment] 2016-12-14 17:22
hi, which version will provide this fix ?

**Comment by vicb** [comment] 2016-12-14 17:37
from 2.3.1 & 4.x

**Comment by igghera** [comment] 2017-11-16 17:00
How do I reproduce this behaviour in html-driven forms?

**Comment by PeterSisovsky** [comment] 2018-02-07 13:58
you can you Validators.requiredTrue instead of Validators.required

**Comment by GuitooStephan** [comment] 2019-05-30 11:00
Still observing the same issue in Angular version :7. Even with requiredTrue Validator, the experience is still the same. I tried writing a custom validator but the value once changed, remains the same. In my case I keep getting "on" as the value. It is killing me.
Am I doing something wrong ?

**Comment by kendistiller** [comment] 2019-06-12 19:11
> Still observing the same issue in Angular version :7. Even with requiredTrue Validator, the experience is still the same. I tried writing a custom validator but the value once changed, remains the same. In my case I keep getting "on" as the value. It is killing me.
> Am I doing something wrong ?

I am also getting this issue still. Checking a checkbox makes it validate the form for submit, but unchecking it does not revert this state. Anyone else still experiencing this?

**Comment by kkaabbaa** [comment] 2019-09-03 12:13
> Still observing the same issue in Angular version :7. Even with requiredTrue Validator, the experience is still the same. I tried writing a custom validator but the value once changed, remains the same. In my case I keep getting "on" as the value. It is killing me.
> Am I doing something wrong ?

works on angular 7 - Validators.requiredTrue
