### ISSUE TITLE
Hostbinded getter is not triggered

### ISSUE THREAD

**Issue by waterplea** [angular/angular#21547] opened 2018-01-16 08:05 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I am working on a "spoiler" component, one that would expand and collapse to show hidden content. I need to calculate its height but it can change due to various reasons — text can wrap to an extra line if component size has changed, if image is lazy loaded somehow, if CSS animation makes the available space smaller etc. Basically I need a component resize event. So I have put an iframe inside it which in turn fires this resize event for me. I have a getter to calculate height and I use HostBinding to set this height to my component. I also have OnPush change detection strategy. For some reason, when I trigger change detection — my HostBinding style does not update. **However when I use this getter variable in template I can see it change.** Please take a look at this demo:
https://stackblitz.com/edit/angular-gitter-saudym
Click "Show/Hide" to show spoiler content. You will see height calculated correctly — all content is visible and exact height value is shown on the page. Now try making the demo part of stackblitz smaller to get text to wrap to more lines. You will see correct height calculated on the page, but the HostBinding style is not updated.

## Expected behavior

HostBinding is updated just like the value on the page.

## Minimal reproduction of the problem with instructions

Here's the small demo I have made to reproduce the issue (also linked above):
https://stackblitz.com/edit/angular-gitter-saudym

## What is the motivation / use case for changing the behavior?

This is clearly an issue because the value is actually updated and change detection is triggered, but HostBinding link does not update the styles.

## Environment

<pre><code>
Angular: v5.0.0

Browser:
Doesn't seem to be browser dependant

**Comment by waterplea** [comment] 2018-01-16 08:34
Just when I reported this, a friend of mine suggested this approach which works:
```
  detectChanges() {
    this.ngZone.run(() => {
      this.changeDetectorRef.markForCheck();
    });
  }
```
However it's still a mystery to me, which template is updated with recalculated getter and host binding is not.

**Comment by JiaLiPassion** [comment] 2018-01-16 13:36
@waterplea , could you provide more information about how to reproduce ? I change the browser size, but I can't reproduce.

**Comment by benelliott** [comment] 2018-09-12 09:51
@waterplea Have you linked to the right demo? I'm interested in this issue as I'm facing a similar problem but the demo you linked to doesn't seem to have any of the features you mentioned.

**Comment by waterplea** [comment] 2019-01-21 11:50
@benelliott looks like I accidentally edited that gitter. I just faced this issue again and with better understanding I do not think it's a bug now. Basically, these events are coming from a different document and by default do not seem to be covered by Zone. So the workaround I mentioned is probably not a workaround but rather a valid way this should be done.

**Comment by pkozlowski-opensource** [comment] 2019-02-14 13:15
Closing based on the latest comments.

**Closed by pkozlowski-opensource** 2019-02-14 13:15 UTC
Labels: comp: core & compiler, freq1: low, severity3: broken, type: bug/fix
