### ISSUE TITLE
DatePipe displaying hours incorrectly

### ISSUE THREAD

**Issue by renannobile** [angular/angular#13967] opened 2017-01-17 17:37 UTC
Hello, I got a bug when formatting a date object with DatePipe. The format is correct but the hours are displayed incorrectly, actually it display with 2 hours less.

Ex.: 17/01/2017 14:45:26 is displayed as 17/01/2017 12:45:26

First image is from Ionic 2 app demo
![ionic](https://cloud.githubusercontent.com/assets/15070719/22032102/2fa4845e-dcca-11e6-9d57-3502c70dcc96.png)

Second one is from Sql table showing the data
![sql](https://cloud.githubusercontent.com/assets/15070719/22032103/2fa6ec80-dcca-11e6-9159-0af158db7115.png)

**Comment by DzmitryShylovich** [comment] 2017-01-17 17:39
what is your timezone?

**Comment by renannobile** [comment] 2017-01-17 17:46
America/Sao_Paulo

**Comment by devoto13** [comment] 2017-01-17 23:12
It seems that your date strings are parsed in UTC timezone, but formatted in local (GMT-02:00). Are you sure, that you're not creating `Date` objects yourself before passing date string to the pipe?

**Comment by renannobile** [comment] 2017-01-17 23:19
I don't create any objects, I simply retrieve data with http.get. If I don't use the pipe it display the correct hour, although the format is incorrect.

**Comment by devoto13** [comment] 2017-01-17 23:27
Works for me in Plunker: http://plnkr.co/edit/1nGfPtm1pX15qwtxLx2O?p=preview

So it's either Ionic issue or you're doing something wrong.

**Comment by renannobile** [comment] 2017-01-17 23:32
The date comes from the database as an DateTime object (something like 2015-03-25T12:00:00-06:30), maybe that's the issue?

**Comment by DzmitryShylovich** [comment] 2017-01-17 23:34
Angular will create a date from that string in the local timezone (js default)
```
new Date('2015-03-25T12:00:00-06:30')
```
For example in my timezone the result is `Wed Mar 25 2015 21:30:00 GMT+0300`
So I'm not sure what we can do on angular side.

**Comment by renannobile** [comment] 2017-01-17 23:36
Is it possible to change the timezone?

**Comment by DzmitryShylovich** [comment] 2017-01-17 23:44
https://github.com/angular/angular/issues/9324

**Comment by pkozlowski-opensource** [comment] 2017-01-18 08:44
Closing as a duplicate of #9324

**Closed by pkozlowski-opensource** 2017-01-18 08:44 UTC
Labels: comp: common, type: bug
