### ISSUE TITLE
Add Dependency Support to effect Function in Angular

### ISSUE THREAD

**Issue by omtagline** [angular/angular#56957] opened 2024-07-12 05:49 UTC
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

When using the effect function in Angular, it's currently not possible to pass dependencies. As a result, all effects run regardless of specific event changes. This limitation reduces the efficiency and control over effect executions, particularly in complex applications.

**Steps to Reproduce**

1. Create an Angular component that uses the effect function.
2. Attempt to pass dependencies to control when the effect should run.
3. Observe that the effect runs on every change, not respecting the intended dependencies.

```
export class ExampleComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
    effect(() => {
      console.log('Effect running');
    }, [/* dependencies */]);
  }
}
```

**Expected Behavior**
The effect function should accept a dependencies array to control when the effect should re-run. This would enable the effect to run only when specified dependencies change, similar to the behavior of React's useEffect hook.

**Actual Behavior**
The effect function runs on every change, ignoring the lack of dependency support. This leads to unnecessary executions and potential performance issues.

### Proposed solution

`export class ExampleComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
    effect(() => {
      console.log('Effect running');
    }, [/* dependencies */]);
  }
}`

**Suggested Solution**
_Enhance the theEffect function to accept a second parameter, which is an array of dependencies. The effect should re-run only when one or more of these dependencies change._

### Alternatives considered

```
export class ExampleComponent implements OnChanges {

  @Input() dependency1: any;
  @Input() dependency2: any;

  constructor() { }

  ngOnChanges(changes: SimpleChanges): void {
    if (changes['dependency1'] || changes['dependency2']) {
      this.runEffect();
    }
  }

  runEffect(): void {
    console.log('Effect running');
    // Your effect logic here
  }
}
```

- can Use This But It Not Working With Input Signal

**Comment by ms-dosx86** [comment] 2024-07-12 06:41
You can `untrack` a specific dependency inside the `effect` function. This might be what you're looking for https://angular.dev/guide/signals#reading-without-tracking-dependencies

**Comment by pkozlowski-opensource** [comment] 2024-07-12 06:52
Duplicate of #56155

**Closed by pkozlowski-opensource** 2024-07-12 06:52 UTC
