### ISSUE TITLE
angular 7 universal to workspace

### ISSUE THREAD

**Issue by LarozeMultiservices** [angular/angular#34947] opened 2020-01-24 09:33 UTC
My angular 7.1.4 project structure is like this:

MyMulti
----node_modules
----projects
-------projA
-------projA-e2e
-------projB
-------projB-e2e
angular.json
package.json

I am able to apply Universal successfully to a single project. How to apply universal to all the projects in "MyMulti"? Is there any website reference which has an example or any tutorial? I could not get the configuration right. Any help would be appreciated.

**Comment by ericmartinezr** [comment] 2020-01-24 11:43
Dup of https://github.com/angular/angular/issues/34895

**Comment by AndrewKushnir** [comment] 2020-01-24 18:18
Closing as a duplicate of #34895.

**Closed by AndrewKushnir** 2020-01-24 18:18 UTC
