### ISSUE TITLE
Tags on style tags are removed when scoped/transformed.

### ISSUE THREAD

**Issue by thso** [angular/angular#6513] opened 2016-01-15 16:38 UTC
I have the following in a component template:

```
<style is='custom-style'>...</style>
```

which is transformed and inserted under the 'head' tag:

```
<style>...</style>
```

losing the "is='custom-style'" during the process.

This marker is needed by polymer.

**Comment by zoechi** [comment] 2016-01-15 17:14
... and moving it into the `<head>` tag would also break it. I'm not sure if it would even work if Angular didn't manipulate `<style is="custom-style">`, but I also would like to be able to use Polymer DOM modules.
I'm pretty sure it can't work when `ViewEncapsulation.Emulated` is involved, because Angular and Polymer use different emulation.
I guess it would require `ViewEncapsulation.Native` and for Polymer full shadow DOM being enabled (instead of shady DOM).

**Comment by mhevery** [comment] 2016-01-20 20:45
Could you create a reproduction case in Plunker?

**Comment by norbertes** [comment] 2016-09-01 19:00
I think I've made that: https://plnkr.co/edit/gx5rSP7VHYDCykOujzHw?p=preview
The thing is, if you'll inspect with dev-tools preview window, you can see a `style` tag without any attributes.

![image](https://cloud.githubusercontent.com/assets/2737422/18180413/122c4ba0-7087-11e6-8081-2a0a25c0831c.png)

**Comment by vicb** [comment] 2016-09-01 22:56
what about the media attr ?

**Comment by norbertes** [comment] 2016-09-02 07:55
As I can see all attrs are omitted (updated plnkr).

If this issue is still important, I can try to fix it (would be my 1st opensource contribute)

**Comment by vicb** [comment] 2016-09-02 15:27
every issue is important !

@norbertes if you want to take this one please comment here when you start working on this so that the work isn't duplicated. Thanks.

/cc @matsko

**Comment by DzmitryShylovich** [comment] 2017-03-11 22:00
Duplicate of https://github.com/angular/angular/issues/4884

**Comment by splincode** [comment] 2018-07-30 10:59
@thso What do you think relation problem with AOT?

**Comment by AndrewKushnir** [comment] 2022-02-01 00:22
Closing as a duplicate of #26293.

**Closed by AndrewKushnir** 2022-02-01 00:22 UTC
Labels: type: bug/fix, feature, effort1: hours, freq1: low, comp: core, core: stylesheets, P3, insufficient votes, votes required
