### ISSUE TITLE
Link url dead in new docs

### ISSUE THREAD

**Issue by NirajD10** [angular/angular#52564] opened 2023-11-07 04:45 UTC
### Describe the problem that you experienced

When I was in tutorial section in new angular dev, I was trying to learn more about topics "Updating the Component Class" on below there was link  'type interface in Typescript'. Unfortunately, The link seems isn't working anymore. 

### Enter the URL of the topic with the problem

https://angular.dev/tutorials/learn-angular/updating-the-component-class

### Describe what you were looking for in the documentation

 I was trying to learn more about topics "Updating the Component Class" on below first step (add a property called city) there was link  'type interface in Typescript'. They seem doesn't work

### Describe the actions that led you to experience the problem

after clicking link this is URL where the error came - https://angular.dev/typescript.org/type-inference

### Add a screenshot if that helps illustrate the problem

![image](https://github.com/angular/angular/assets/66014487/17ed25e8-14db-4c5a-ab0f-b006416ecba5)

**Comment by atscott** [comment] 2023-11-07 13:08
Duplicate of https://github.com/angular/angular/issues/52553

**Closed by atscott** 2023-11-07 13:08 UTC
