### ISSUE TITLE
i18n translation duplicated

### ISSUE THREAD

**Issue by elvisbegovic** [angular/angular#15573] opened 2017-03-29 07:45 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
```

**Current behavior**
Actually I have 
```
<span class="slds-form-element__help" *ngIf="form.get('sapNumber').errors?.maxlength" i18n>Maximum de {{max8}} caractères autorisé.</span>
<span class="slds-form-element__help" *ngIf="form.get('interfaceAccountNumber').errors?.maxlength"  i18n>Maximum de {{max15}} caractères autorisé.</span>
<span class="slds-form-element__help" *ngIf="form.get('formDesignation').errors?.maxlength" i18n>Maximum de {{max20}} caractères autorisé.</span>
<span class="slds-form-element__help" *ngIf="form.get('shortDesignation').errors?.maxlength" i18n>Maximum de {{max35}} caractères autorisé.</span>
```
and when I extract with `"./node_modules/.bin/ng-xi18n" --i18nFormat=xmb` I get 4 times same strings to translate with different ID in my `messages.xmb` file. All others strings aren't duplicated but this one is, why ?

```
<msg id="4591664065864994257">Maximum de <ph name="INTERPOLATION"><ex>INTERPOLATION</ex></ph> caractères autorisé.</msg>
<msg id="3596670943450897156">Maximum de <ph name="INTERPOLATION"><ex>INTERPOLATION</ex></ph> caractères autorisé.</msg>
<msg id="27126914192147611">Maximum de <ph name="INTERPOLATION"><ex>INTERPOLATION</ex></ph> caractères autorisé.</msg>
<msg id="8495459888526831686">Maximum de <ph name="INTERPOLATION"><ex>INTERPOLATION</ex></ph> caractères autorisé.</msg>
```
N.B. I tried with `{{15}}` interpolation, I tried with `max15 : string = "15"` I tried with `max15 : number = 15` and same behavior !

**Expected behavior**
Extract only one time this i18n string.

**Please tell us about your environment:** webstorm 2017.1 

* **Angular version:** 4.0.0

* **Language:** [ts 2.2.1]

* **Node (for AoT issues):** `node --version` =  v7.7.2

**Comment by ocombe** [comment] 2017-03-30 07:34
Hmm definitely a bug, even those 2 tags will generate two different ids just because of the extra spaces inside the interpolation:

```html
<span i18n>Maximum de {{max}} caractères autorisé.</span>
<span i18n>Maximum de {{ max }} caractères autorisé.</span>
```

--> working on it

**Comment by istiti** [comment] 2017-03-30 07:51
just wonder how this is possible, what am I doing here different from others tags? I use this syntax in many others components and it works. 

cc @ocombe

**Comment by ocombe** [comment] 2017-03-30 07:54
It's just that the digest function will take the name of the placeholder (and the content of the placeholder) into account when generating the id, which it obviously shouldn't because we only care about its position and the text around it

**Comment by alfaproject** [comment] 2018-03-19 08:07
I realize this is a breaking change, but it is a welcomed one. Angular 6 is coming soon so the time for these kinds of changes is basically now. Any hope for this one?

**Comment by tatsujb** [comment] 2018-10-31 16:13
also you get multiple of the same tag when using fixed id instead of uuid : 

```
<div *ngIf="warn1" [@phaseAnimation] i18n="logout">Déconnexion</div>
<div *ngIf="warn2" [@phaseAnimation] i18n="logout">Déconnexion</div>
```

will generate 

```
      <trans-unit id="55a57e6165759f4c48fd86a29d674304066044e9" datatype="html">
        <source>Déconnexion</source>
        <context-group purpose="location">
          <context context-type="sourcefile">app/logged.in/login/login.component.html</context>
          <context context-type="linenumber">2</context>
        </context-group>
        <target state="new">Logout</target>
        <note priority="1" from="description">logout</note>
      </trans-unit>
      <trans-unit id="534bac27369eefeed4c40f38914f068c0c1cb323" datatype="html">
        <source>Déconnexion</source>
        <context-group purpose="location">
          <context context-type="sourcefile">app/logged.in/login/login.component.html</context>
          <context context-type="linenumber">3</context>
        </context-group>
        <target state="new">Logout</target>
        <note priority="1" from="description">logout</note>
      </trans-unit>
```

when obviously the point of using human-made ids would be to weed out duplicates pre-generation of xlf

**Comment by petebacondarwin** [comment] 2020-10-24 16:10
I believe this is fixed by the new ivy extraction. I will create some tests to check.

**Comment by PowerKiKi** [comment] 2020-10-25 07:27
I can confirm that I used to see duplicates in my project, but since my migration to Angular 10.1, this is no longer the case :tada:

**Comment by petebacondarwin** [comment] 2020-10-25 10:27
Thanks for the update @PowerKiKi

**Closed by petebacondarwin** 2020-10-25 10:27 UTC
Labels: P4, comp: i18n, engine: ve, fixed by Ivy, flag: breaking change, freq1: low, state: confirmed, triage #1, type: bug/fix, workaround4: none
