### ISSUE TITLE
Named routes 

### ISSUE THREAD

**Issue by teddywest32** [angular/angular#13416] opened 2016-12-13 06:49 UTC
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x ] support request => Please do not submit support request here, instead see 
```

**Current behavior**
I have gone through the documentation for routes
https://angular.io/docs/ts/latest/api/router/index/Route-interface.html

I couldn't see any name interface for the routes. 

**Expected behavior**
_**It would be great if there is any feature that would name the route and we would not need to use the full url for the http request inside the same application.**_
OR 
_**If we want to point the route from the application it could help when we change it's url to something other.  Like: Laravel Routes**_

**What is the motivation / use case for changing the behavior?**
To help everyone to ease the development and easy when refactoring the routes codes.

**Please tell us about your environment:**

Operating System : all,
IDE : all,

* **Angular version:** 
2.X.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
All
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
All

* **Node (for AoT issues):** `node --version` =   4.6.0

**Comment by DzmitryShylovich** [comment] 2016-12-13 06:55
It'a by design https://youtu.be/QLns6s02O48?t=656

**Comment by klinki** [comment] 2016-12-13 09:07
@teddywest32 I also had similar problem with routes. I created service which maps routes to components and you pass just component class and it returns its route. You could do pretty much the same thing for names.

There is just one problem - this service doesn't work for lazy loaded routes. At least I never managed to get it working.

**Comment by teddywest32** [comment] 2016-12-13 11:40
@DzmitryShylovich So, there is no way they will implement the named routes in future since it hampers the lazy loading??

@klinki  Could you give me small implementations though i might not implement your method?? Also why are you calling components to return the routes? As component class names might also be changed?? What do you think about that??

**Comment by DzmitryShylovich** [comment] 2016-12-13 11:40
> So, there is no way they will implement the named routes in future since it hampers the lazy loading??

yeap

**Comment by klinki** [comment] 2016-12-13 13:45
@teddywest32 I'm not calling components, I'm just using them as identifier for route. Basically each final route leads to some component. If you change component class name, you usually do that with some IDE refactoring tool, which will change names everywhere in the code.

Here is example usage of my service: 

```javascript
let url = this._routeLinkProviderService.getRouteForComponent(GroupListComponent, {
    projectId: this.applicationGroup.migrationProject.id
}),
```

I do multiple things in that service - I have also my custom-made parameter resolution and so on... Basically it finds provided parameters in route and if it finds them, it replaces them with given value. If it doesn't, it adds them as query param. 

Basic idea behind this is: 
1) You need to pass routes to that service.
2) In service you go through routes tree and create HashMap. 
Your use case is little bit different than mine, so you could add field `name` to your routes and create HashMap with `name` as a key and some object representing route as a value.

3) You would need to identify also all parent routes. I have recursive algorithm which finds also all parents for current route. When resolving URL, you need to go from root to route matching given name.

For example:

```javascript
{
    name: 'project-top-route',
    path: 'projects',
    children: [
        { name: 'project-layout-route', path: '', component: DefaultLayoutComponent, children: [
            { name: 'project-list-route', path: '', component: ProjectListComponent, data: {displayName: "Project List"}},
            { name: 'project-create-route', path: 'create', component: MigrationProjectFormComponent, data: {displayName: 'Create Project'}},
          ]
        },
        {
            name: 'single-project-route',
            path: ':projectId',
            resolve: {
                project: ProjectResolve
            },
            children: [
                { name: 'project-edit-route', path: 'edit', component: ProjectEditComponent }
            ]
        }
    ]
};
```
URL for `project-edit-route` must traverse tree up to the root. So result must be `/projects/:projectId/edit` (and you must replace corresponding parameter).


I feel I didn't describe it very clearly, sorry for that. If you have any questions, just ask. Here is source code of my service: https://gist.github.com/klinki/8bb6b1f80585cebdaa66552301356d4c


Unfortunately as @DzmitryShylovich mentioned, there is currently no way how to make it work with lazy loading.

**Comment by vicb** [comment] 2016-12-13 16:20
> I couldn't see any name interface for the routes.

As sais above there is no way we can get the name of lazy loaded routes (because they might not be loaded at the time you want to render a link/navigate to this route).

**Closed by vicb** 2016-12-13 16:20 UTC
