### ISSUE TITLE
Events being swallowed when using an ngTemplateOutlet with context surrounded by an element with a click listener

### ISSUE THREAD

**Issue by joeattardi** [angular/angular#19882] opened 2017-10-23 21:19 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Sorry for the long confusing title. 

I have a `div` with a `(click)` listener on it. The handler function does nothing.

Inside that `div`, I have a `ng-container` which is a template outlet for a simple template. The template is nothing but a single `<input type="checkbox">`. A `context` is provided (in this case, it's just an empty object since the template references no variables).

With this setup, clicking on the checkbox does not mark it as checked.

If I remove the `context` from the `ngTemplateOutlet`, it works.
If I remove the `(click)` listener from the surrounding `div`, it works.

## Expected behavior
The checkbox should be toggled on and off

## Minimal reproduction of the problem with instructions

https://plnkr.co/edit/LHxdP3XBifuYbgmo3ptm

Try to click the checkbox. It won't work. If you remove the `context: {}` or the `(click)` listener, the checkbox works.

## Environment

Angular version: 4.4.4

Browser:
- [X] Chrome (desktop) version 61.0.3163.79
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [X] Safari (desktop) version 11.0
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by trotyl** [comment] 2017-10-24 03:12
This is a duplicate of #13407 and has already been fixed in 5.x branch in #18277, you can change angular version to `next` to observe that.

**Comment by joeattardi** [comment] 2017-10-24 23:38
Is there any way to prevent it from recreating the view when the context changes? I need the context to be dynamic, but need to keep state in the checkbox.

**Comment by trotyl** [comment] 2017-10-25 01:36
1. Upgrade to 5.x version;
2. Mutate the context without providing a new object.

**Closed** 2017-11-10 22:22 UTC
