### ISSUE TITLE
ExpressionChangedAfterItHasBeenCheckedError on async call in EntryComponent

### ISSUE THREAD

**Issue by gillerr** [angular/angular#28801] opened 2019-02-18 15:44 UTC
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/core

### Is this a regression?
No

### Description
A component listen to events from a service and updates its view accordingly. Then, if such an event is trigger by an `EntryComponent` added to the body with `ApplicationRef` (as done by ng-bootstrap to show a modal), then an `ExpressionChangedAfterItHasBeenCheckedError` is triggered.

The use case is an HTTP call form a ng-bootstrap's modal with an interceptor showing a spinner on rest calls.

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-dzvlrd

## 🔥 Exception or Error
<pre><code>
ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'null: Angular'. Current value: 'null: ExpressionChangedAfterItHasBeenCheckedError'.
    at viewDebugError (errors.ts:35)
    at expressionChangedAfterItHasBeenCheckedError (errors.ts:21)
    at checkBindingNoChanges (util.ts:102)
    at checkNoChangesNodeInline (view.ts:473)
    at checkNoChangesNode (view.ts:461)
    at debugCheckNoChangesNode (services.ts:465)
    at debugCheckRenderNodeFn (services.ts:417)
    at Object.eval [as updateRenderer] (HelloComponent.html:1)
    at Object.debugUpdateRenderer [as updateRenderer] (services.ts:409)
    at checkNoChangesView (view.ts:343)

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 7.1.0
Node: 8.15.0
OS: linux x64
Angular: 7.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.11.0
@angular-devkit/build-angular      0.11.0
@angular-devkit/build-ng-packagr   0.11.0
@angular-devkit/build-optimizer    0.11.0
@angular-devkit/build-webpack      0.11.0
@angular-devkit/core               7.1.0
@angular-devkit/schematics         7.1.0
@ngtools/json-schema               1.1.0
@ngtools/webpack                   7.1.0
@schematics/angular                7.1.0
@schematics/update                 0.11.0
ng-packagr                         4.4.0
rxjs                               6.3.3
typescript                         3.1.6
webpack                            4.23.1

</code></pre>

**Anything else relevant?**
The errors shows on each life cycle hooks, but not when the service is called from the constructor.

**Comment by pkozlowski-opensource** [comment] 2019-02-18 16:45
Thnx for reporting but we are already tracking it here: #15634

**Comment by gillerr** [comment] 2019-02-19 05:44
Thanks for the quick analysis, but I though they were different issues.
#15634 is about creating a dynamic view during a life cycle hook. 
I create the view outside of life cycle hooks in reaction to a user action. An event emission causes the error on another component.

**Comment by pkozlowski-opensource** [comment] 2019-02-19 17:46
@gillerr indeed, this is different issue

**Comment by JoostK** [comment] 2021-07-14 19:37
I looked at the Stackblitz and it's not clear to me why this would be considered a bug (admittedly, the scenario is a bit subtle).

In `EntryComponent`'s `ngOnInit` lifecycle hook, the service is "activated" which sends out an event that causes the state of `HelloComponent` to be changed. When the created `EntryComponent` is attached to the application ref it will be change detected in the same cycle as `HelloComponent`. This introduces an ordering-dependent relation between `EntryComponent` and `HelloComponent`. In particular, `EntryComponent` is change detected _after_ `HelloComponent`, therefore `EntryComponent.ngOnInit` is invoked _after_ `HelloComponent` has finished its change detection cycle. This is why changing its state based on the event from `EntryComponent.ngOnInit` introduces `ExpressionChangedAfterItHasBeenCheckedError`.

I think the primary confusion comes from the fact that creating `EntryComponent` dynamically using `ComponentFactory.create` only runs its creation phase. It does _not_ run change detection; that has to be done manually either through `ComponentRef.changeDetectorRef.detectChanges()` or by attaching it to an `ApplicationRef` (which then follows ticks from `NgZone` to run change detection on the app).

You can more clearly see this is the case by changing `EntryComponent`'s template to contain a dynamic binding in the text (e.g. `<div>entry component {{dynamic}}</div>`). In that case, it becomes more apparent that change detection is only run when the component is attached to the `ApplicationRef`, as without attaching it you'll not see anything. Alternatively to attaching it to `ApplicationRef`, you could run manual change detection using `componentRef.changeDetectorRef.detectChanges();`. That avoids the `ExpressionChangedAfterItHasBeenCheckedError` as in that case there is no relationship with `HelloComponent`, which means that `HelloComponent` won't have been change detected _before_ `EntryComponent` was change detected; avoiding the error.

Here's [an updated StackBlitz using Angular 12.1](https://stackblitz.com/edit/angular-ivy-x82bq7?file=src%2Fapp%2Fapp.component.ts). You can play with the commented out lines in `app.component.ts` to see how the various options behave.

I am closing this as not a bug, but feel free to follow up with questions.

**Closed by JoostK** 2021-07-14 19:37 UTC
Labels: P4, comp: core, core: change detection, freq1: low, type: bug/fix
