### ISSUE TITLE
`test.unit.dart` does not work for incremental builds

### ISSUE THREAD

**Issue by tbosch** [angular/angular#2386] opened 2015-06-05 23:30 UTC
First run is good, but after changing a file the build breaks:

```
Error: ENOENT, no such file or directory '/Users/tbosch/projects/angular2/tmp/diffing_plugin_wrapper-cache_path-WRS7pHuE.tmp/angular2_material/src/components/button/button.html'
    at Error (native)
    at Object.fs.statSync (fs.js:797:18)
    at Object.realpathSync (fs.js:1400:12)
    at symlink (/Users/tbosch/projects/angular2/node_modules/symlink-or-copy/index.js:71:26)
    at Function.symlinkOrCopySync (/Users/tbosch/projects/angular2/node_modules/symlink-or-copy/index.js:58:5)
```

There is a symlink at this place that points to an invalid path `/Users/tbosch/projects/angular2/tmp/mapper-tmp_dest_dir-019nNEvP.tmp/angular2_material/src/components/button/button.html`.

**Comment by caitp** [comment] 2015-06-05 23:41
Might be worth filling this on symlink-or-copy, looks like they're missing a try/catch

**Comment by caitp** [comment] 2015-06-06 20:32
I'm not sure exactly where the problem is coming from. It shouldn't affect Windows machines, and can be fixed on unix by replacing the `symlinkOrCopySync()` with `fse.outputFileSync()`, but there are performance implications.

However, I'm not convinced that it's a TreeStabilizer bug. I am expecting this to be multi_copy or the Funnel plugin itself, and possibly just the design of the dart treebuilder, which could be unsafely reusing a tree

**Comment by caitp** [comment] 2015-06-07 21:48
Oh, another thing that seems to fix this is re-implementing stew.map (and broccoli-filter) on the new rebuild-api. I guess it's another symptom of broccoli-filter doing crazy things, and the tree-stabilizer not fixing it properly.

Any votes for the approach taken to fix this? It's a one-liner vs several-hundred-lines

**Comment by pkozlowski-opensource** [comment] 2015-06-09 00:34
Oh, bumping into this one as well :-( This issue makes it _very_ hard to test on Dart, as we need to re-start test.unit.dart after each file change, and this is now looongish (~20 - 30s) after migration to Brocolli...

**Closed** 2015-06-09 06:35 UTC
Labels: comp: build/dev-productivity, effort1: easy (hour), P1: urgent, type: bug
