### ISSUE TITLE
validate required or optional `@Input` on html template

### ISSUE THREAD

**Issue by xiaoxiangmoe** [angular/angular#30974] opened 2019-06-11 11:12 UTC
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/language-service @angular/compiler

### Description 

validate required or optional `@Input` on html template.

see also:
* [Angular 2 make @Input on directive required](https://stackoverflow.com/questions/35528395/angular-2-make-input-on-directive-required)
* [Support for defaultProps in JSX](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-0.html#support-for-defaultprops-in-jsx)

**Comment by trotyl** [comment] 2019-06-11 14:05
Relates to https://github.com/angular/angular/issues/18156

**Comment by alxhub** [comment] 2019-06-18 22:52
Closing as a duplicate of the four issues above, which contain a lot of rich discussion.

One day I hope we'll be able to do this. That day is not today :(

**Closed by alxhub** 2019-06-18 22:52 UTC
Labels: comp: core
