### ISSUE TITLE
Impossible to generate the correct route for an auxiliary route.

### ISSUE THREAD

**Issue by jpleclerc** [angular/angular#13589] opened 2016-12-20 16:14 UTC
**I'm submitting a ...** (check one with "x")

```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
Generating a correct URL from a route containing an auxiliary route seems to be impossible in some cases. For example, in my use case, the correct route would be /Test/(List//details:/Details/1) but the router generates /Test/List(details:Details/1).

**Expected behavior**
The router should generate the correct route.

**Minimal reproduction of the problem with instructions**
Here is the plunker: [https://plnkr.co/edit/2xo6WFI2JzGbIcAzio04](https://plnkr.co/edit/2xo6WFI2JzGbIcAzio04)

**What is the motivation/use case for changing the behavior?**
In my plunker, I want to generate the **details** below the **list** in an auxiliary route.

**Please tell us about your environment:**

Windows/ASP.NET

* **Angular version:** 2.0.X
Angular 2.3
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TS 2.1, ES5

**Comment by vicb** [comment] 2016-12-20 17:58
What makes you think `/Test/(List//details:/Details/1)` is the correct route ?
Because `List` is the primary outlet I think `/Test/List(details:Details/1)` is correct.

May be a docs issue ?

**Comment by jpleclerc** [comment] 2016-12-20 18:21
@vicb Because `/Level/(List//details:Details/1)` works and `/Level/List(details:Details/1)` doesn't work. See my updated plunker: [https://plnkr.co/edit/2xo6WFI2JzGbIcAzio04](url)

I get the following error when clicking on the "Doesn't work" button:
`EXCEPTION: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'Details/1'`

**Comment by vicb** [comment] 2016-12-20 18:23
> Because /Level/(List//details:Details/1) works and /Level/List(details:Details/1) doesn't work

That's a pb !

**Comment by Prepd-Root** [comment] 2017-03-10 14:05
We encountered an issue and noticed this ticket. We believe it might be the same thing.

The first time you use the auxiliary route (click on the `details` button), it works fine but the route looks exactly like the one in this ticket.
After you close the auxiliary route (click on the `close details` button), the route does not return to the previous state, and consequent calls to the auxiliary route fail.

To avoid duplicates, we'd like to let you know that this issue is a big problem for us and we created an example  to showcase the issue.

Here's the example: https://plnkr.co/edit/dxpS7CqHw69W5hDIpTmh

PS. If it's not a big problem, can you tell us when would you like to release a fix for this issue?

**Comment by atscott** [comment] 2020-05-26 19:38
confirmed in v9 as well: https://stackblitz.com/edit/angular-ivy-4s6yj8?file=src%2Fapp%2Fapp.module.ts

**Comment by atscott** [comment] 2020-11-03 17:59
I believe this was fixed by 3af585c.

**Closed by atscott** 2020-11-03 17:59 UTC
Labels: P3, comp: router, freq2: medium, router: URL parsing/generation, router: aux routes, state: confirmed, triage #1, type: bug/fix
