### ISSUE TITLE
Vague error message NgFor

### ISSUE THREAD

**Issue by j3ddesign** [angular/angular#6313] opened 2016-01-07 03:02 UTC
I just came across an error message that, in my opinion didn't really tell me what the problem was.

I was setting up a simple *ngFor ` *ngFor="#mode in modes" `

Yet, obviously I got an error because I put "in" instead of "of", however the error was 
`Can't bind to 'ngForIn' since it isn't a known native property (template info)`

It's clearly a stupid mistake, and now that I've seen it once, I understand the error. However first looking at it, I was stumped. I don't personally have suggestions as to what It should be, though perhaps the community does. (If it's deemed worthy of a rewrite)

**Comment by chuckjaz** [comment] 2016-01-29 19:14
We should consider changing this error to something like `Unknown identifier "in", expected "of"` or, if there is more than one expected, `Unknown identifier "in", expected one of "zip", "do", "dah"`. The expected list can be calculated from the set of properties in scope that have the prefix, in this case `ngFor`.

**Comment by pkozlowski-opensource** [comment] 2016-08-30 12:56
Duplicate of #4244

**Closed by pkozlowski-opensource** 2016-08-30 12:56 UTC
Labels: hotlist: error messages
