### ISSUE TITLE
rc.10  brake [ngClass]

### ISSUE THREAD

**Issue by sysmat** [angular/angular#34948] opened 2020-01-24 11:16 UTC
# 🐞 bug report

### Affected Package
 I think  @angular/core

### Is this a regression?
 Yes, it work with rc.9

### Description
 When evaluating expression in tamplate form

## 🔬 Minimal Reproduction

```html
<form (ngSubmit)="onSubmit3Months(f1)"
          novalidate
          #f1="ngForm">

<input [(ngModel)]="fromDate"
            #fd="ngModel"
            [ngClass]="{'is-invalid':fd.errors?.required && fd.touched || fd.errors && f1.submitted}"
            class="form-control form-control-sm"
            name="fromDate"
            id="fromDate3Month"
            type="date">
  <div *ngIf="fd?.errors?.required && fd.touched"
           class="invalid-feedback">
       Obvezno
   </div>
</form>

```
## 🔥 Exception or Error
There is no error in compile phase nor in dev console

## 🌍  Your Environment

**Angular Version:**
<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by martinpirlot** [comment] 2020-01-24 12:39
Hi,

I have the same issue on rc10. It was working with rc8 (didn't try with rc9).

`[ngClass]="{top_arrow: item.children && firstLevel, left_arrow: item.children && !firstLevel }"`

--> Always have classes "top_arrow" and "left_arrow" even if "item" has no "children".

Weirdly, it's behaving correctly when "item" has "children" and "firstLevel" is true (I only gave "top_arrow" classes), but not if "firstLevel" is false. Then I have again both classes.

Best regards,
Martin

**Comment by pkozlowski-opensource** [comment] 2020-01-24 14:54
@martinpirlot this indeed sound very strange. Would you mind distilling your use-case in a stackblitz (so I can turn it into a non-regression test). I _think_ I know what might be going on (we've temporally changed `null` / `undefined` behaviour) but want to make sure that we are fixing the right thing...

**Comment by pkozlowski-opensource** [comment] 2020-01-24 15:09
@sysmat could you give us more info besides "rc.10 brake [ngClass]"? What gets broken, exactly (ex.: classes not added when they should, or removed when they should not)? Could you try to distill your use-case in a stackblitz? Thnx!

**Comment by martinpirlot** [comment] 2020-01-24 17:16
@pkozlowski-opensource I tried to do a stackblitz but I can't reproduce the issue, it's really weird. I tried to replicate my component as much as I could, but it's still working correctly ( https://stackblitz.com/edit/angular-z1cfsr )

It's my first use of stackblitz so maybe I missed something with the angular version or something. I will continue to investigate this week-end.

**Comment by pkozlowski-opensource** [comment] 2020-01-24 17:20
@martinpirlot thnx for the stackblitz - it gives me the use-case! You probably can't reproduce it with stackblitz since, AFAIK, it doesn't run on ivy by default. In any case, the scenario is valuable.

I don't want you to spend time tracking those things over the weekend - I think that I've got enough context here and I _believe_ that I know what is going on here (plus, I think that it is fixed in master already).

I will poke around and ping you if I need more info. Thnx so much for getting back to us with more details!

**Comment by ericmartinezr** [comment] 2020-01-24 18:14
@martinpirlot  fwiw you can use https://ng-run.com/ to reproduce if you need ivy

**Comment by Splaktar** [comment] 2020-01-24 19:47
To enable Ivy in StackBlitz, you need to do the following

> You need to set `enableIvy` to `true` in `angularCompilerOptions` inside `tsconfig.json`, and the project needs to be using Angular version `9.x`.

**Comment by alexzuza** [comment] 2020-01-25 19:15
@sysmat 
I had a chance to reproduce your issue

9.0.0-rc.10 => https://ng-run.com/edit/8TUHc0s6K2oJ2NyIQjU3?aot=true&open=app%2Fapp.component.ts

`is-invalid` class is always added because your condition is evaluated to `null`.

For workaround you can make sure your condition is evaluated to boolean value, that is:

```
[ngClass]="{'is-invalid':fd.errors?.required && fd.touched || !!fd.errors && f1.submitted}"
                                                              /\
                                                          add this  

```

@pkozlowski-opensource looks like you were right

**Comment by martinpirlot** [comment] 2020-01-27 08:45
@alexzuza I confirm that your solution is fixing my issue too :) Thank you 👍

**Comment by pkozlowski-opensource** [comment] 2020-01-27 13:34
@martinpirlot glad that you've got a work-around for rc.10 but the good news is that it was fixed in rc.11. Closing this issue.

**Closed by pkozlowski-opensource** 2020-01-27 13:34 UTC
Labels: comp: core, comp: ivy, severity5: ivy-compat, severity5: regression
