### ISSUE TITLE
camelCase Component properties with downgradeNg2Component

### ISSUE THREAD

**Issue by Blackbaud-PatrickOFriel** [angular/angular#8622] opened 2016-05-12 20:38 UTC
**Steps to reproduce and a minimal demo of the problem**

  - create a Component with a camelCase input property
  - use the upgrade adapter to downgrade the component for use in angular1
  - observe that the property must be referenced as `[my-property]` instead of `[myProperty]` in the html.
  - plunker for reference: http://plnkr.co/edit/w14TnEnziKkUBAk0EDmU?p=preview
  - plunker of the same component without upgrade adapter: http://plnkr.co/edit/gijSaa9VqwPv0s6N3Yl4?p=preview 

**Current behavior**
  - Angular 2 components with camelCase input properties are referenced using `[my-property]` when downgraded to use in an Angular 1 App.

**Expected/desired behavior**
   - Angular 2 components with camelCase input properties are referenced using `[myProperty]` when downgraded to use in an Angular 1 App.

**Other information**
Apologies if this is already an existing issue or a non-issue. I didn't see anything about it in the documentation or a search through the open and closed issues. Thanks a bunch for your help

**Comment by hannahhoward** [comment] 2016-05-16 20:47
I'm not sure there's a better solution other than to document this.  Currently, the downgrade adapter is reading the attributes from the NG1 Link function's $attrs, which are normalized so a camelCased name in $attrs is a kebob case attribute in html. Since the HTML is already processed by the time the directive is created, it seems like the best you could do would be to support camelCase but also then the lowercase version of the property name -- since HTML is case insensitive (you could do this by simply looking for a lowercased version of the property in $attrs). But I'm not sure this is an improvement since that introduces a whole category of unexpected behavior. Since property normalization is used throughout Angular 1, it seems to me if you're going to use an ng2 directive in an ng1 template, you ought to follow ng1's conventions of using kebob-case attributes that get normalized. In which case, the only addon here is to document the behavior.

**Comment by mhevery** [comment] 2016-05-16 22:16
@wardbell Could you add this to our documentation?

@hannahhoward thank you fro your analysis of the problem. I will go ahead and close the issue.

**Closed by mhevery** 2016-05-16 22:16 UTC
Labels: comp: upgrade, effort1: easy (hour), freq4: high, severity4: broken, type: bug, workaround1: obvious

**Comment by Blackbaud-PatrickOFriel** [comment] 2016-05-17 12:55
Makes sense to me as long as it's known/expected behavior

**Comment by wardbell** [comment] 2016-05-21 06:01
Forwarded on to @teropa, the author of our upgrade chapter
