### ISSUE TITLE
Exposed Components Communication Channels

### ISSUE THREAD

**Issue by KamilPieronczyk** [angular/angular#49320] opened 2023-03-04 23:49 UTC
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

Writing wrapper comopnents for 3rd party libraries is tedious because of neccessity to expose all inputs and outputs of 3rd party component to parent component. Each 3rd party component update requires to recheck all wrappers. My proposal is to create an API to expose all inputs and outputs in seperate arrays.
If someone has better API design please update.

### Proposed solution

```ts
@Component({
  selector: 'app-wrapper',
  template: `<app-child [title]="title" [{propsInputs}] ({propsOutputs})></app-child>`,
  propsInputs: [...Inputs(ChildComponent)],
  propsOutputs: [...Outputs(ChildComponent)],
})
export class WrapperComponent {
  @ViewChild(ChildComponent, { static: true }) child: ChildComponent;
  @Input() title = 'Overridden title input';
  @PropsInputs() propsInputs;
  @PropsOutputs() propsOutputs;
}

@Component({
  selector: 'app-child',
  template: '<p>{{ title }} {{ description }}</p>',
})
export class ChildComponent {
  @Input() title = '';
  @Input() description = '';
}
```

Usage
```html
<app-wrapper [description]="Exposed Description"></app-wrapper>
```

### Alternatives considered

No idea

**Comment by vneogi199** [comment] 2023-03-07 17:32
Quite similar to [https://github.com/angular/angular/issues/14545](https://github.com/angular/angular/issues/14545). Though it's a must have for library developers.

**Comment by pkozlowski-opensource** [comment] 2023-03-31 10:58
Also related discussion in #41993

**Comment by alxhub** [comment] 2024-05-29 15:06
Closing as a duplicate of #14545.

**Closed by alxhub** 2024-05-29 15:06 UTC
Labels: area: core, core: inputs / outputs
