### ISSUE TITLE
bug(service-worker) does not work offline on chrome (at least)

### ISSUE THREAD

**Issue by Ploppy3** [angular/angular#24794] opened 2018-07-08 22:04 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Service-worker does not work offline.

## Expected behavior

Service-worker should work offline.

## Minimal reproduction of the problem with instructions
**_Before we start, I would like to explain that this is hard to debug, much harder than it is on first thought, it requires a lot of testing to identify properly what's going on, please read the following explanation carefully._**

_Being a novice at this, and this issue being extremely hard to test (at least for me), don't take for granted what I will try to explain. Any help is appreciated. Consider that the error could be on my side!_

To begin, there are 2 main problems related to chrome:

- Chrome pretends to have only 1 cache, which can be disabled using the 'Disable cache' checkbox. By experience, this is wrong, Chrome uses another cache that last for 1h which we can't control at all, this result in fake offline behaviors, we will call it 'hidden cache' for now until someone give it a proper name, I tested this on both Android and Windows. 
- A service worker in offline mode will bypass chrome's 'offline mode' and do its requests on the web.

Why it is a problem? Let's say we want to test our service-worker app. Of course, you have to install the service worker so you need to start your app while online. You check the service worker on chrome, everything is installed, your reload the page, every files are loaded from the service-worker according to chrome network tab. Then you go offline, here start the problems, according to bug n°2, you are not really offline, so it will work. You can try going really offline by turning off Wifi, but according to bug n°1, chrome will use its hidden cache, so it will work nonetheless for at least 1h.

Conclusion: the only way to really test the service worker is to physically disconnect from internet and wait at least 1h for the cache to be discarded. In this case, the service worker will simply fail.

Now that the problem is set, I have a few questions: Firebase's cache-control is set to 1h, could this be the 'hidden cache'? If this is true, why does the 'disable cache' checkbox does not disable this cache? Why does 'offline mode' does not block request from the service worker?

Let's test this, I will test this on a firebase app (could it be related to firebase?):

Using the default sw configuration.
```
{
  "index": "/index.html",
  "assetGroups": [{
    "name": "app",
    "installMode": "prefetch",
    "resources": {
      "files": [
        "/index.html",
        "/*.css",
        "/*.js"
      ]
    }
  }, {
    "name": "assets",
    "installMode": "lazy",
    "updateMode": "prefetch",
    "resources": {
      "files": [
        "/assets/**"
      ]
    }
  }]
}
````

This is the produced ngsw.json:
![image](https://user-images.githubusercontent.com/7990765/42424782-4f778cb4-8312-11e8-896e-2bb06a553982.png)

After waiting for 1 hour, being **physically** disconnected from internet, the app won't load due to 504 errors on vital files: 
![really_offline](https://user-images.githubusercontent.com/7990765/42424120-919fda30-8306-11e8-9979-4068bde84e94.JPG)

After waiting for 1 hour, being "disconnected" from internet in chrome dev tools, the app, which was dead 10 seconds ago, magically start again (bug n°2):
![offline_fake](https://user-images.githubusercontent.com/7990765/42424125-a42b9ba8-8306-11e8-881f-d1c51aab03ce.JPG)

With internet, of course, it works, no screenshot needed.

Lets test bug n°1, note that their is an other bug, the 'hidden cache' of chrome is now broken (maybe the 504 errors are now cached in the hidden cache?) so I need to switch platform in order to test the first bug otherwise I would have to wait 1 more hour, so I start the app on my phone, the app is successfully installed and working, if I go really offline (turn off data and wifi), it will work, though, in one hour, it won't start anymore since the 'hidden cache' will be discarded, which should confirm bug n°1.

There could be a problem in any of these:
- My implementation of service worker
- The fact that service workers bypass Chrome's offline mode
- Angular's service-worker
- Chrome's 'hidden cache' that last for 1 hour which can't be disabled
- Cache-Control?
- Firebase?

## Environment

<pre><code>
Angular version: 6.0.7

Browser:
- [x] Chrome (desktop) version 67
- [x] Chrome (Android) version 67
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version:  8.11.2
- Platform:  Windows

</code></pre>

**Comment by Ploppy3** [comment] 2018-07-09 08:10
To begin with, thank you for not throwing the idea out the window!

> BTW, did you know Disable cache only takes effect as long as the DevTools are open?
Yes!

> SW will send a request and Chrome will pretend it is offline (and fail the request).
That's how I conceive it too! Though, not how it seems to work. Because there shouldn't be any difference between being in offline mode and being physically offline. Though, the test above (see dev tools screenshots) clearly shows a complete different behavior.

My point is, that those 2 Chrome bugs let you think that the service worker works offline while it does not, at least not the way I implemented it. Maybe it's just me who does not implement it properly.

What I need is someone to test carefully while considering those 2 eventual bugs because if the service worker is really broken, either on Chrome or Angular or whatever breaks it, we don't want chrome to let you think that it works while it's not really the case... It's realy of tricky and tedious to test.

**Comment by gkalpak** [comment] 2018-07-09 08:14
> What I need is someone to test carefully while considering those 2 eventual bugs [...]

If you provide a minimal reproduction (and exact steps to follow), I can test this and verify if it is indeed broken and where the issue lies (Chrome, `@angular/service-worker`, your code, etc) :smiley:

**Comment by Ploppy3** [comment] 2018-07-09 08:30
@gkalpak the steps to reproduce are pretty much explained in the original post. The installation steps are missing, but it's pretty simple, create a project with the cli, use the `ng add` command to install the pwa package and setup service worker and you are good to go, this installation is automatic and should work out of the box. Though, if really needed, I can try to write a complete guide to reproduce... But it would mean I would have to test again, which means several hours of waiting to make sure the cache is cleared... And to be honest I spent already way too many hours on this.

BTW, I just did another quick physically offline test, the app started once, then the sw just uninstalled itself (thanks to the safety-worker script) probably due to an error. I just hope it's not another bug to test...

**Comment by Ploppy3** [comment] 2018-07-09 14:15
I tested again on an empty app, on both firebase and http-server localhost on Windows only yet. It seems to work, though, both of my real apps using the service workers are broken.

I catched this error after a clean install of one of my app (cleared cache), this is what I get on my phone.

![image](https://user-images.githubusercontent.com/7990765/42455076-89e2b3c2-8391-11e8-8502-846f765e0649.png)

The worker-basic.min.js script is used to unregister the old service worker (when it was a side project):
```
self.addEventListener('install', event => { self.skipWaiting(); });

self.addEventListener('activate', event => {
  event.waitUntil(self.clients.claim());
  self.registration.unregister().then(
      () => { console.log('NGSW Safety Worker - unregistered old service worker'); });
});
```
Could this cause an issue? This code was given to me by the people working on the project.

This script is defined in the angular.json file
```
"assets": [
  "src/assets",
  "src/manifest.webmanifest",
  "src/worker-basic.min.js"
],
```

So this might end up being an error on my side, any idea @gkalpak ?

**Comment by gkalpak** [comment] 2018-07-09 18:16
It is hard to tell without an actual repro or access to the code. Is there a redirect or rewrite rule regarding `worker-basic.min.js` in your `firebase.json`?

**Comment by gkalpak** [comment] 2018-07-09 18:17
I am going to close this, since this is not an `@angular/service-worker` issue, but feel free to continue the discussion below.

**Closed by gkalpak** 2018-07-09 18:17 UTC
Labels: comp: service-worker, state: Need repro, type: bug/fix

**Comment by gkalpak** [comment] 2018-07-10 09:46
Again, it is hard to tell what is going on without looking at an actual reproduction. If I had to guess, I would say that you are creating and hashing your version of `worker-basic.min.js` (something you are not supposed to be doing :grin:), then cli generates its own version which overwrites yours (but does not update the hash in `ngsw.json`. When the SW requests `worker-basic.min.js`, it gets the cli-generated one and compares it with the hash in the manifest (which corresponds to yours and does not match the cli-generated one), causing a conflict and making the SW to enter "safe mode".

AFAICT, you don't need to do anything special when using the latest versions of `@angular/cli` and `@angular/service-worker`. The cli will autogenerate a `worker-basic.min.js` file that unregisters the old SW. Clients that have the old SW installed, will request the new file, which will unregister the old SW. On the next request, they will get the fresh files, which register the new SW and everything will be fine.

**Comment by Ploppy3** [comment] 2018-07-10 09:55
@gkalpak Yeah that's it, but when they first released the new version, there was no auto generated worker-basic.min.js that's why I had to implement it myself. Unless I missed it there was no word on this breaking changes. Anyway thank you very much for the time spent to understand this with me.
