### ISSUE TITLE
docs: "Add HTTP communication to your app" - db.json file issues: broken "photo" and "id" fields

### ISSUE THREAD

**Issue by rafaello7** [angular/angular#53856] opened 2024-01-09 18:56 UTC
### Describe the problem that you experienced

The _db.json_ file shown on the page has two issues.

First one: the "photo" field contains the _baseUrl_ variable reference. The variable is never expanded. As a result, the "photo" link is broken and the photos are no longer displayed by app.

Second issue is associated with the "id" format expected by _json-server_ . Namely, the id value should be in quotes, e.g. _"id": "0"_; otherwise the locations link with id does not work.

### Enter the URL of the topic with the problem

https://angular.dev/tutorials/first-app/http

### Describe the actions that led you to experience the problem

1. complete the app changes described in this lesson
2. while the _ng serve_ and _json-server_ is running, open _http://localhost:4200/_
3. the photos are not displayed; also, after clicking on any _Learn More_ link the details aren't displayed correctly.

### If this problem caused an exception or error, please paste it here

```true
Sample exception in the browser's console:
...
GET http://localhost:4200/$%7Bthis.baseUrl%7D/i-do-nothing-but-love-lAyXdl1-Wmc-unsplash.jpg 404 (Not Found)
...
After clicking on a _Learn More_ link:
...
GET http://localhost:3000/locations/4 404 (Not Found)
...
```

**Comment by louaymeskini** [comment] 2024-01-17 21:14
Well I think the issue here is that images must be added under assets folder and images url must be updated but the problem here is how can I upload the updated app lesson source code ! I guess we don't have access for uploading !
@dylhunn appreciate your guidance and thanks.

**Comment by JeanMeche** [comment] 2024-04-07 10:10
Closing as a dupe of #52794

**Closed by JeanMeche** 2024-04-07 10:10 UTC
Labels: state: has PR, P3, area: adev, area: docs
