### ISSUE TITLE
Example with NgFor,NgIf directives fails on Dart version >=2.0.0-alpha.28

### ISSUE THREAD

**Issue by mark1010** [angular/angular#2935] opened 2015-07-08 16:47 UTC
The code below is taken from the examples and works correctly with angular Dart version 2.0.0-alpha.27  (after updating the injector).

	@View(template: '''
	<p>My name: {{ myName }}</p>
	<p>Friends:</p>
	<ul>
	   <li *ng-for="#name of friendNames">
	      {{ name }}
	   </li>
	</ul>
	<p *ng-if="friendNames.length > 3">You have many friends!</p>
	''',
	directives: const [NgFor,NgIf]
	)
	
Using angular2: '>= 2.0.0-alpha.28' or '2.0.0-alpha.29' the code fails at NgFor, NgIf with:

	Unsupported directive record
  
Using angular2: '2.0.0-alpha.30' the code fails with

	Unsupported directive record in [friendNames in <li *ng-for="#name of friendNames">]

**Comment by andresaraujo** [comment] 2015-07-09 00:59
Same here, this only happens if you add the Dart transformer.

**Comment by naomiblack** [comment] 2015-07-14 03:50
@jakemac53 can you have a look into this one please?

**Comment by jakemac53** [comment] 2015-07-14 15:23
pretty sure this is a duplicate of https://github.com/angular/angular/issues/2984#issuecomment-121257708

**Closed** 2015-07-14 15:24 UTC
Labels: comp: dart-transformer, effort1: easy (hour), P2: required, type: bug
