### ISSUE TITLE
Quick Start Fail to Start Server

### ISSUE THREAD

**Issue by tranquilodf** [angular/angular#18249] opened 2017-07-20 12:06 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request 
</code></pre>

## Current behavior

I'm trying to use step-by-step install in quickstart, but, when i try to start the server i take a error. Its says 
> node_modules appears empty, you may need to run `npm install`

## Expected behavior

I'm just following the step-by-step in quickstart (step 3)

## Minimal reproduction of the problem with instructions

1 - I have install Node.js
2 - Install Angular Cli "npm install -g @angular/cli"
3 - Created new Project "ng new my-app"
4 - Goes to the directory with "cd my-app" then try to start the server "ng serve --open"

## What is the motivation / use case for changing the behavior?

Start to Learn Angular

## Environment
<pre><code>
Angular version: 4.3.1

Browser:
- [X] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [X] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [X] IE version XX
- [X] Edge version XX
 
For Tooling issues:
- Node version: 6.11.1  
- Platform:  Windows 10 Pro 

Others:

- Wamp
- Visual Studio
- PHPStorm 2017.2

</code></pre>

**Comment by gkalpak** [comment] 2017-07-20 13:08
Sounds like a duplicate of #18099.

**Closed by gkalpak** 2017-07-20 13:08 UTC
