### ISSUE TITLE
Reactive forms directives should be standalone

### ISSUE THREAD

**Issue by jermowery** [angular/angular#55320] opened 2024-04-12 18:06 UTC
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

No

### Description

Reactive forms directives should be standalone

**Comment by JeanMeche** [comment] 2024-04-12 20:29
Hi, this is closely related to #49720 and I think we can close it as a duplicate of #48607.

**Closed** 2024-04-25 23:31 UTC
Labels: area: forms
