### ISSUE TITLE
State changes not reflected in Safari + IE11

### ISSUE THREAD

**Issue by johannes-weber** [angular/angular#10199] opened 2016-07-21 09:08 UTC
**I'm submitting a ...** 
```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
I'm subscribing to queryParam changes in a component in order to update and save the app state based on it. Clicking on links, which points to the different states works fine. Using the browsers back button for getting the prev. state does not work in IE11 and Safari.

When I'm using the browser back button in IE 11 or Safari the code in my component get's executed, but not reflected in the DOM. When I run the changes inside the NgZone.run(callback) callback function, it get's reflected.

**Expected/desired behavior**
Changes should get reflected in the DOM as happening in all the other browsers.

**Reproduction of the problem**
- Open your DevTools console
- Click through the list randomly and take a look at the URL (?selectedIndex=1)
- Use the browser's back button to get back to the prev. state and monitor the logging in the console. 
- The code gets executed but not reflected in the browsers DOM

[http://plnkr.co/edit/2sTW28Ql6Vq8GxtT22ne?p=preview](http://plnkr.co/edit/2sTW28Ql6Vq8GxtT22ne?p=preview)

**What is the motivation / use case for changing the behavior?**
A consistent behaviour through all the 'modern' browsers

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** [  IE 11 | Safari 9.1.1 ] 
 
* **Language:** [ TypeScript 1.8.10 / ES5 ]

**Comment by zoechi** [comment] 2016-07-21 09:38
Might be fixed by #10096 (with next release)

**Comment by pkozlowski-opensource** [comment] 2016-07-22 10:13
Yup, duplicate of #10096

**Closed by pkozlowski-opensource** 2016-07-22 10:13 UTC
