### ISSUE TITLE
Extra spaces after compilation of the interpolation expression.

### ISSUE THREAD

**Issue by HarryBurns** [angular/angular#39927] opened 2020-12-02 08:27 UTC
# 🐞 bug report

### Description
At compile time, Angular adds extra spaces around the interpolated value for formatted HTML. Even with `preserveWhitespaces: false`.

For example, we have two elements with interpolation expression inside:
``` HTML
<div>{{ label }}</div>
<div>
  {{ label }}
</div>
```

The first one will be compiled to
``` javascript
_angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵɵtextInterpolate1"](ctx.label); // Corrent
```

And the second one will be compiled to
``` javascript
_angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵɵtextInterpolate1"](" ", ctx.label, " ");  // <--- Extra spaces here!
```

So the resulting HTML will be (assuming that `label="Hello"`)
``` HTML
<div>Hello</div>
<div> Hello </div>
```

Using a `preserveWhitespaces: false` parameter doesn't help.

This is not a big problem in itself, because [the browser will remove unnecessary spaces and line breaks when showing the page to the user](https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model/Whitespace). But for automated tests, problems arise. Especially when the presence/absence of spaces in the tag content is critical.

These spaces also increase the size of the resulting bundle. What is contrary to the purpose of the `preserveWhitespaces` parameter.

My code goes through an automatic formatting process, so it is very difficult to ensure that we do not move interpolation expressions to a new line.

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-playground-kdplir?file=app%2Fapp.component.html

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 10.0.7
Node: 14.8.0
OS: win32 x64

Angular: 10.0.11
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker
Ivy Workspace: <error>

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.7
@angular-devkit/build-angular     0.1000.7
@angular-devkit/build-optimizer   0.1000.7
@angular-devkit/build-webpack     0.1000.7
@angular-devkit/core              10.0.7
@angular-devkit/schematics        10.0.7
@angular/cdk                      10.1.3
@angular/cli                      10.0.7
@angular/material                 10.1.3
@ngtools/webpack                  10.0.7
@schematics/angular               10.0.7
@schematics/update                0.1000.7
rxjs                              6.6.2
typescript                        3.9.7
webpack                           4.43.0
</code></pre>

**Comment by petebacondarwin** [comment] 2020-12-02 09:55
The name of the option `preserveWhitespaces: false` is perhaps a bit misleading. What it actually means is that in this mode the compiler will "collapse" whitespace. In other words multiple whitespace (spaces, newlines, tabs, etc) will be collapsed into a single space.

There are various heuristic approaches to doing this. Admittedly, the Angular strategy is not the most sophisticated, since as you show it is probably acceptable to actually completely remove some whitespace, rather than collapsing it to a single space.

**Comment by petebacondarwin** [comment] 2020-12-02 10:18
Closing as a duplicate of https://github.com/angular/angular/issues/37635

**Closed by petebacondarwin** 2020-12-02 10:18 UTC
