### ISSUE TITLE
RouterLink's href is sometimes incorrect when used within a component activated using an empty-path

### ISSUE THREAD

**Issue by kasiditi** [angular/angular#23346] opened 2018-04-12 20:10 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

The `href` of the `routerLink` specified using matrix URL notation is sometimes broken.

For example, using the `<a [routerLink]="['bar']">Go to bar</a>` (as in the reproduction below), the computed `href`'s URL sometimes becomes `//(bar)`, which points to an URL outside the website's origin. When clicking on the link, it logs something like this to the browser's console:

```
SecurityError: Failed to execute 'pushState' on 'History': A history state object with URL 'https://%28bar%29/' cannot be created in a document with origin 'https://angular-271g96.stackblitz.io' and URL 'https://angular-271g96.stackblitz.io/'.
```

It isn't always broken, and I'm not sure when it will be broken. The case that I found can be reproduced using instructions below.

## Expected behavior

The `href` value is always correctly computed.

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/angular-271g96

1. Visit the reproduction app. You should currently be on the Foo page. Note that the `href` of the "go to bar" link is what is expected (`/bar`).
3. Click on the "Go to bar" link. You should see the Bar page.
4. Click on the "Go Back" link. You should see the Foo page. Notice that the "go to bar" link's href is now incorrect (`//(bar)`).
5. Click on the "Go to bar" link again. There should be a console's error logged, similar to the one mentioned above.

## What is the motivation / use case for changing the behavior?

Using routerLink with matrix URL notation within an empty-path component that is on the root. For example:

```js
[
  {
    path: '',
    pathMatch: 'full',
    component: FooComponent
  },
  {
    path: 'bar',
    component: BarComponent
  }
]
```

## Environment

<pre><code>
Angular version: 5.2.8, 5.2.9, 7.1.4

Browser:
- [x] Chrome (desktop) version 66.0.3359.81
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version 60.0b4 (64-bit)
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
</code></pre>

**Comment by atscott** [comment] 2020-05-28 17:19
Duplicate of #13011

**Closed by atscott** 2020-05-28 17:19 UTC
Labels: comp: router, freq2: medium, severity3: broken, triage #1, type: bug/fix
