### ISSUE TITLE
Access to the object instance in Angular Elements

### ISSUE THREAD

**Issue by ardiadrianadri** [angular/angular#25019] opened 2018-07-22 05:44 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[X] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

If I want to access the object instance of an Angular Element, I can not supposedly do so because it is a private property. In addition, it is quite difficult to find. To use it I had to go through the ngElementStrategy, componentRef and _component objects:

```
const angularComponent = document.getElementsByTagName('my-table')[0].ngElementStrategy.componentRef._component;
```

## Expected behavior

I would like to have a easiest way to access at the instance of the component in Angular Elements

## Minimal reproduction of the problem with instructions

You can check my example in next github repository (branch table-element):
https://github.com/ardiadrianadri/table-elements/tree/table-element
## What is the motivation / use case for changing the behavior?

Imagine that I want to extend the functionality of an angular component by extending the class that creates this component. Something like this:
```
@Component{
  selector: 'my-component'
  template: 'whatever.html'
}
export class WhateverComponent extends ObjectA {}
```
It would be nice to be able to access at the properties and methods of ObjectA if the component "WhateverComponent" gets compile as Angular Element

## Environment

<pre><code>
Angular version: 6.0.9

Browser:
- [X] Chrome (desktop) version 67.0.3396.99
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.11.1  
- Platform:  Mac

Others:

</code></pre>

**Comment by trotyl** [comment] 2018-07-22 05:51
Practically duplicate of https://github.com/angular/angular/issues/22114, another different approach for same issue.

**Comment by gkalpak** [comment] 2021-07-02 14:29
Closing as a duplicate of #22114.

**Closed by gkalpak** 2021-07-02 14:29 UTC
Labels: comp: elements, feature, insufficient votes, votes required
