### ISSUE TITLE
AOT on case insensitive file systems fails

### ISSUE THREAD

**Issue by kukjevov** [angular/angular#15767] opened 2017-04-04 18:04 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When i run compilation with AOT enabled it fails with following error:

ERROR in Error encountered resolving symbol values statically. Calling function 'ɵmakeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol Injectable in f:/git/universal-demo/node_modules/@angular/core/core.d.ts, resolving symbol BaseAnimatedComponent in f:/git/universal-demo/app/misc/baseAnimatedComponent.ts, resolving symbol BaseAnimatedComponent in f:/git/universal-demo/app/misc/baseAnimatedComponent.ts

ERROR in Error encountered resolving symbol values statically. Calling function 'ɵmakeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol Component in f:/git/universal-demo/node_modules/@angular/core/core.d.ts, resolving symbol NotFoundComponent in f:/git/universal-demo/app/pages/notFound/notFound.component.ts, resolving symbol NotFoundComponent in f:/git/universal-demo/app/pages/notFound/notFound.component.ts

**Expected behavior**
AOT should work.

**Minimal reproduction of the problem with instructions**
Here are two branches which illustrates both of mentioned errors. 

https://github.com/kukjevov/ng-universal-demo/tree/emakeerror
Branch: `emakeerror`
run `npm install`
then `npm run build:aot`

https://github.com/kukjevov/ng-universal-demo/tree/emakeerror2
Branch: `emakeerror2`
run `npm install`
then `npm run build:aot`

Please can somebody at least look at this? It is making impossible to use AOT.

**Please tell us about your environment:**
Windows 10, VSCode

* **Angular version:** 4.0.1

* **Browser:** [all]
 
* **Language:** [TypeScript 2.2.1]

* **Node (for AoT issues):** `node --version` = v6.9.4

**Comment by kukjevov** [comment] 2017-04-04 18:16
What is even more interesting. If you remove `NotFoundComponent` files and removes routes pointing to it it can be compiled.
Here you can see same solution with 3 components instead of 4 components and can be compiled using AOT.

https://github.com/kukjevov/ng-universal-demo/tree/noemakeerror
Branch: `noemakeerror`
run `npm install`
then `npm run build:aot`

So far as i can see it is problem if there is certain amount of components (or some combination of them) or when you use base classes with decorators for components or services.

Thank you for any help

**Comment by metodribic** [comment] 2017-04-05 13:46
There is fairly long thread about this issue on angular/angular-cli#3707. Unfortunately there is no generic answer or solution for this, except following [these](https://medium.com/@isaacplmann/making-your-angular-2-library-statically-analyzable-for-aot-e1c6f3ebedd5) guidelines to make sure your code is AOT ready.

**Comment by kukjevov** [comment] 2017-04-05 15:02
Well only thing i can say is that I am going by those guidelines, but since when is adding component against guidelines? 

My build started failing when i added `NotFoundComponent` simple empty component. Nothing more nothing else, without that component it is working.

```typescript
import {Component} from '@angular/core';

/**
 * Page displayed when url was not found
 */
@Component(
{
    selector: 'not-found-view',
    templateUrl: 'notFound.component.html'
})
export class NotFoundComponent
{
    public static ngRoutes = [{path: '**', component: NotFoundComponent}];
}
```

What is wrong with this?

**Comment by kukjevov** [comment] 2017-04-05 15:03
At least if error message can give you any advice but error message is useless in this case.

**Comment by patrickhousley** [comment] 2017-04-05 16:33
@kukjevov I have battled this error messaging for the last few days. I have found that if I run `ngc`, I get better error messaging. Honestly, the error messaging is now dismal when using @ngtools/webpack and doing an AOT build. I am not sure if we can use this issue to maybe tackle the issue of error messaging being so terrible or if we should open a new issue. Below is another example of poor messaging.

```
10% building modules 5/9 modules 4 active ...aem-components/service-layer/index.tsModuleNotFoundError: Module not found: Error: Can't resolve './app/app.module.ngfactory' in '/Users/patrickhousley/Documents/projects/com/angular-upgrade/frontend-checkout/src'
    at factoryCallback (/Users/patrickhousley/Documents/projects/com/angular-upgrade/frontend-checkout/node_modules/webpack/lib/Compilation.js:260:39)
    at /Users/patrickhousley/Documents/projects/com/angular-upgrade/frontend-checkout/node_modules/webpack/lib/NormalModuleFactory.js:243:19
    at onDoneResolving (/Users/patrickhousley/Documents/projects/com/angular-upgrade/frontend-checkout/node_modules/webpack/lib/NormalModuleFactory.js:59:20)
    at /Users/patrickhousley/Documents/projects/com/angular-upgrade/frontend-checkout/node_modules/webpack/lib/NormalModuleFactory.js:132:20
    at /Users/patrickhousley/Documents/projects/com/angular-upgrade/frontend-checkout/node_modules/webpack/node_modules/async/dist/async.js:3824:9
    at /Users/patrickhousley/Documents/projects/com/angular-upgrade/frontend-checkout/node_modules/webpack/node_modules/async/dist/async.js:460:16
    at iteratorCallback (/Users/patrickhousley/Documents/projects/com/angular-upgrade/frontend-checkout/node_modules/webpack/node_modules/async/dist/async.js:1032:13)
    at /Users/patrickhousley/Documents/projects/com/angular-upgrade/frontend-checkout/node_modules/webpack/node_modules/async/dist/async.js:944:16
    at /Users/patrickhousley/Documents/projects/com/angular-upgrade/frontend-checkout/node_modules/webpack/node_modules/async/dist/async.js:3821:13
    at apply (/Users/patrickhousley/Documents/projects/com/angular-upgrade/frontend-checkout/node_modules/webpack/node_modules/async/dist/async.js:21:25)
    at /Users/patrickhousley/Documents/projects/com/angular-upgrade/frontend-checkout/node_modules/webpack/node_modules/async/dist/async.js:56:12
    at /Users/patrickhousley/Documents/projects/com/angular-upgrade/frontend-checkout/node_modules/webpack/lib/NormalModuleFactory.js:124:22
    at onResolved (/Users/patrickhousley/Documents/projects/com/angular-upgrade/frontend-checkout/node_modules/enhanced-resolve/lib/Resolver.js:70:11)
    at loggingCallbackWrapper (/Users/patrickhousley/Documents/projects/com/angular-upgrade/frontend-checkout/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at afterInnerCallback (/Users/patrickhousley/Documents/projects/com/angular-upgrade/frontend-checkout/node_modules/enhanced-resolve/lib/Resolver.js:138:10)
    at loggingCallbackWrapper (/Users/patrickhousley/Documents/projects/com/angular-upgrade/frontend-checkout/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at Resolver.applyPluginsAsyncSeriesBailResult1 (/Users/patrickhousley/Documents/projects/com/angular-upgrade/frontend-checkout/node_modules/tapable/lib/Tapable.js:181:46)
    at innerCallback (/Users/patrickhousley/Documents/projects/com/angular-upgrade/frontend-checkout/node_modules/enhanced-resolve/lib/Resolver.js:125:19)
    at loggingCallbackWrapper (/Users/patrickhousley/Documents/projects/com/angular-upgrade/frontend-checkout/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at /Users/patrickhousley/Documents/projects/com/angular-upgrade/frontend-checkout/node_modules/tapable/lib/Tapable.js:283:15
    at /Users/patrickhousley/Documents/projects/com/angular-upgrade/frontend-checkout/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:38:4
    at loggingCallbackWrapper (/Users/patrickhousley/Documents/projects/com/angular-upgrade/frontend-checkout/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at afterInnerCallback (/Users/patrickhousley/Documents/projects/com/angular-upgrade/frontend-checkout/node_modules/enhanced-resolve/lib/Resolver.js:138:10)
    at loggingCallbackWrapper (/Users/patrickhousley/Documents/projects/com/angular-upgrade/frontend-checkout/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at Resolver.applyPluginsAsyncSeriesBailResult1 (/Users/patrickhousley/Documents/projects/com/angular-upgrade/frontend-checkout/node_modules/tapable/lib/Tapable.js:181:46)
    at innerCallback (/Users/patrickhousley/Documents/projects/com/angular-upgrade/frontend-checkout/node_modules/enhanced-resolve/lib/Resolver.js:125:19)
    at loggingCallbackWrapper (/Users/patrickhousley/Documents/projects/com/angular-upgrade/frontend-checkout/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at /Users/patrickhousley/Documents/projects/com/angular-upgrade/frontend-checkout/node_modules/tapable/lib/Tapable.js:283:15
    at innerCallback (/Users/patrickhousley/Documents/projects/com/angular-upgrade/frontend-checkout/node_modules/enhanced-resolve/lib/Resolver.js:123:11)
    at loggingCallbackWrapper (/Users/patrickhousley/Documents/projects/com/angular-upgrade/frontend-checkout/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
resolve './app/app.module.ngfactory' in '/Users/patrickhousley/Documents/projects/com/angular-upgrade/frontend-checkout/src'
  using description file: /Users/patrickhousley/Documents/projects/com/angular-upgrade/frontend-checkout/package.json (relative path: ./src)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /Users/patrickhousley/Documents/projects/com/angular-upgrade/frontend-checkout/package.json (relative path: ./src)
    using description file: /Users/patrickhousley/Documents/projects/com/angular-upgrade/frontend-checkout/package.json (relative path: ./src/app/app.module.ngfactory)
      as directory
        /Users/patrickhousley/Documents/projects/com/angular-upgrade/frontend-checkout/src/app/app.module.ngfactory doesn't exist
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /Users/patrickhousley/Documents/projects/com/angular-upgrade/frontend-checkout/src/app/app.module.ngfactory doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        /Users/patrickhousley/Documents/projects/com/angular-upgrade/frontend-checkout/src/app/app.module.ngfactory.ts doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /Users/patrickhousley/Documents/projects/com/angular-upgrade/frontend-checkout/src/app/app.module.ngfactory.js doesn't exist
      .json
        Field 'browser' doesn't contain a valid alias configuration
        /Users/patrickhousley/Documents/projects/com/angular-upgrade/frontend-checkout/src/app/app.module.ngfactory.json doesn't exist
^C
```

**Comment by kukjevov** [comment] 2017-04-06 06:35
Please can someone from angular team look at this :) ?
@tbosch, @IgorMinar @matsko 

Thank you

**Comment by tbosch** [comment] 2017-04-08 19:32
Hi,
there are 2 bugs here:

1. angular-cli copies your files temporarily into an `app.aot` folder. However, your code has absolute imports form `app/...`. I.e. even if ngc succeeded, your bundle would contain your application 2x. To solve this, change the `import ... from 'app/...'` statements to be relative imports. This will also make the error that your are seeing go away.
2. the error originates as the angular compiler internally does not respect `ts.sys.useCaseSensitiveFileNames` / `CompilerHost.getCanonicalFileName` for caching internal symbols. During the module resolution via `ts.resolveModuleName` for `app/...` imports, typescript normalizes the paths with `toLowerCase` on a case insensitive filesystem (which it doesn't always do, e.g. when using relative paths). This results in our system getting a filePath with 2 different `StaticSymbol`s for the same underlying symbol in a typescript file, and especially for the symbols of the decorators in `@angular/core` (e.g. `Component` / ...). You can see this in the error message `resolving symbol Component in <somePath>` where `<somePath>` is the all lowercase version of the actual path (on my system, I use `/Users/...` and the error message contains `/users/...`

Note: macOS by default is case insensitive for accessing files, although it preserves the case when listing files in a directory.

**Comment by tbosch** [comment] 2017-04-08 19:32
I.e. workaround: Make sure you don't have imports like `app/...` in your application, and replace them with relative imports.

**Comment by kukjevov** [comment] 2017-04-09 18:18
@tbosch thank you very very much, you are awesome :), using relative paths works.

Funny thing is that those absolute paths are added automaticaly by vscode new feature (missing import feature) from previous release if you have in tscofng.json `"baseUrl": "."` and i never realized that this could be problem.

By the way, i think you tested it, but if i set all paths to `app.aot` it does not work either with absolute paths. Copy of app directory to app.aot are done by me in gulpfile.js because i need some transformations to be done for aot. So maybe 1. in your post is maybe not really bug. 

But those absolute paths would be nice if they work :).

Btw it looks like that absolute paths are also cause of this https://github.com/angular/angular/issues/15571. I am going to test it properly tomorrow, but it looks like same case.

Anyway thank you again :).

**Comment by patrickhousley** [comment] 2017-04-10 17:38
@tbosch Thanks for look at this. I use `"baseUrl": ""` and `"genDir": "."`. At this point, is the recommendation going to be to always use relative imports when using Angular? I just want to make sure the recommendation is clearly communicated. If this is the case, could be maybe get something added to the styleguide? And maybe a lint rule request put into the codelyzer team.

**Comment by DorianGrey** [comment] 2017-04-11 08:45
I'm currently facing a similar error message with my own [angular playground project](https://github.com/DorianGrey/ng-webpack-template) which does not use the cli, but only the ngtools/webpack plugin.
I'm not using any absolute path - at least none that I know of - so this does not seem to be the cause of the error in my case. However, it seems to be related to the second issue @tbosch mentioned, since the build only fails on Windows and macOS, but not on linux (tested with Ubuntu and Arch).

Running `yarn build:aot` on Windows or macOS fails with:
```
﻿Error: Error encountered resolving symbol values statically. Calling function 'ɵmakeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function
    at simplify (C:\Users\IEUser\ng-webpack-template\node_modules\@angular\compiler\bundles\compiler.umd.js:23308:54)
    at simplifyCall (C:\Users\IEUser\ng-webpack-template\node_modules\@angular\compiler\bundles\compiler.umd.js:23114:24)
    at simplify (C:\Users\IEUser\ng-webpack-template\node_modules\@angular\compiler\bundles\compiler.umd.js:23296:48)
    at simplifyInContext (C:\Users\IEUser\ng-webpack-template\node_modules\@angular\compiler\bundles\compiler.umd.js:23321:24)
    at simplify (C:\Users\IEUser\ng-webpack-template\node_modules\@angular\compiler\bundles\compiler.umd.js:23157:36)
    at simplifyInContext (C:\Users\IEUser\ng-webpack-template\node_modules\@angular\compiler\bundles\compiler.umd.js:23321:24)
    at simplify (C:\Users\IEUser\ng-webpack-template\node_modules\@angular\compiler\bundles\compiler.umd.js:23279:48)
    at simplify (C:\Users\IEUser\ng-webpack-template\node_modules\@angular\compiler\bundles\compiler.umd.js:23139:56)
    at simplifyInContext (C:\Users\IEUser\ng-webpack-template\node_modules\@angular\compiler\bundles\compiler.umd.js:23321:24)
    at recordedSimplifyInContext (C:\Users\IEUser\ng-webpack-template\node_modules\@angular\compiler\bundles\compiler.umd.js:23334:24) 'node_modules/@angular/core/core.d.ts'
```
Although the function mentioned in this error is a lambda (see [here](https://github.com/angular/angular/blob/09d9f5fe54e7108c47de61393e10712f8239d824/packages/compiler/src/aot/static_reflector.ts#L624), it's curious to see that this is not a problem on every OS.

**Comment by tbosch** [comment] 2017-04-11 15:43
@patrickhousley No, you should be able to use absolute imports. However, there is a bug on case insensitive file systems (see above)...

**Comment by diestrin** [comment] 2017-04-14 22:05
I was having the exact same issue, and after spending 2 days in the devtools, I came with this patch:
```ts
import { CompilerHost } from '@angular/compiler-cli';
import * as fs from 'fs';

CompilerHost.prototype.getCanonicalFileName =
  function mockGetCanonicalFileName(fileName: string, index: number = 0): string {
    const segments = fileName.replace(/^\//, '').split('/');

    if (!segments[index]) {
      return fileName;
    }

    const ls = fs.readdirSync(index ? '/' + segments.slice(0, index).join('/') : '/');

    segments[index] = ls.find(item => {
      return item.toLowerCase() === segments[index].toLowerCase();
    }) as string;

    return mockGetCanonicalFileName('/' + segments.join('/'), index + 1);
  };
```
Put that at the beginning of your webpack config

What is does is to override [getCanonicalFileName](https://github.com/angular/angular/blob/56c46d70f7b3cb308d658224682d739d4f9b5a2a/packages/compiler-cli/src/compiler_host.ts#L70) that now simply returns the same path given, with the corrected path (with the right case in filesystem)

So for example if the route in your disk is `/Users/test/Documents/project/file.ts` but typescript is returning `/users/test/documents/project/file.ts` (the cause of this issue), this function will go looking folder from folder in that path and building the url again with the correct case.

Tested in my project and it worked without a complain.

@tbosch, feel free to use this code, or a modification to patch this if you think it's the right solution.

**Comment by shumpei** [comment] 2017-04-17 08:55
@diestrin I want use your patch, very awesome!

But, how do I use this patch?
It seems the patch for AOT compiler and hacking prototype of CompilerHost, how do I apply this patch to compiler (or ngc command)?

**Comment by diestrin** [comment] 2017-04-17 13:54
I'm just writing that after the imports in my webpack.config.ts file, just make sure to include/write it before you instance the AotPlugin plugin.
You can even write it down to a file and import it in you webpack.config.ts, so when this bug is fixed you just remove the import.

**Comment by fernandoTorresan** [comment] 2017-06-14 15:55
A workaround that is worked for me, is add inside the file tsconfig.app.json a path *"@angular/*": ["../node_modules/@angular/*"]* 


```
"compilerOptions": {
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "lib": [
      "es2016",
      "dom"
    ],
    "outDir": "../out-tsc/app",
    "module": "es2015",
    "baseUrl": "",
    "types": [],
      "paths": {
      "@angular/*": ["../node_modules/@angular/*"] 
    }
  }
```

**Comment by alxhub** [comment] 2020-05-28 19:14
The View Engine compiler does have some issues with case insensitive file-systems, definitely. The good news is that we've tried to be more strict about this with Ivy, and support should be good in v10.

**Comment by JoostK** [comment] 2021-05-14 11:53
Closing as resolved in Ivy, since it no longer uses the `StaticSymbol` machinery that was prone to case sensitivity issues.

**Closed by JoostK** 2021-05-14 11:53 UTC
Labels: P5, comp: compiler, engine: ve, freq3: high, state: confirmed, triage #1, type: bug/fix
