### ISSUE TITLE
Improve error `The ngcc compiler has changed since the last ngcc build`

### ISSUE THREAD

**Issue by arobinson** [angular/angular#34567] opened 2019-12-20 17:08 UTC
# 🚀 Feature request

Sometimes, with pulling in multiple libraries, it is possible that one is using an older angular version and accidentally pulling in an older Ivy version. This results in the error `The ngcc compiler has changed since the last ngcc build`

The error is not helpful in these cases. Knowing what package.json file is causing the issue is vital to fixing the problem (deleting the `node_modules` doesn't work when the libraries are conflicting like this).

I temporarily changed the function:
```
    function hasBeenProcessed(packageJson, format, entryPointPath) {
        if (!packageJson.__processed_by_ivy_ngcc__) {
            return false;
        }
        if (Object.keys(packageJson.__processed_by_ivy_ngcc__)
            .some(function (property) { return packageJson.__processed_by_ivy_ngcc__[property] !== exports.NGCC_VERSION; })) {
            var nodeModulesFolderPath = entryPointPath;
            while (!file_system_1.isRoot(nodeModulesFolderPath) && file_system_1.basename(nodeModulesFolderPath) !== 'node_modules') {
                nodeModulesFolderPath = file_system_1.dirname(nodeModulesFolderPath);
            }
            console.log(packageJson);
            throw new Error("The ngcc compiler has changed since the last ngcc build.\n" +
                ("Please remove \"" + (file_system_1.isRoot(nodeModulesFolderPath) ? entryPointPath : nodeModulesFolderPath) + "\" and try again."));
        }
        return packageJson.__processed_by_ivy_ngcc__[format] === exports.NGCC_VERSION;
    }
```
I added the `console.log(packageJson);` and it was really helpful to track down what library had the wrong ngcc output.

Perhaps change this to log the failing `packageJson` when the log level is set to debug?

Thanks!

### Command (mark with an `x`)

```
- [ ] new
- [x] build
- [x] ngcc
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

**Comment by petebacondarwin** [comment] 2020-01-09 14:45
Please can you provide a minimal reproduction of this issue? It sounds like you have some complicated setup with symlinks that are causing the npm cache to be modified (rather than just the local node_modules folder).

**Comment by kara** [comment] 2020-02-06 22:27
Since we don't have an repro, there's nothing actionable to do here and I'm going to close the issue. @arobinson We would still like to investigate this, so if you're able to create a repro, please open a new issue with the repro info.

**Closed by kara** 2020-02-06 22:27 UTC
Labels: comp: ngcc, state: Needs repro, type: bug/fix

**Comment by gkalpak** [comment] 2020-02-06 22:47
Since #35079, ngcc knows how to clean up packages compiled by old ngcc version and this error should not be thrown any more.
