### ISSUE TITLE
[Router 3.0.0-beta.2] "data" parameter exists in Route and unable to pass data dynamically

### ISSUE THREAD

**Issue by ramana-chavakula** [angular/angular#9804] opened 2016-07-04 16:16 UTC
[Router 3.0.0-beta.2] "data" parameter exists in Route and we can pass static data through route definition, but unable to pass dynamic data through RouteLink or navigate method of Router.

**Comment by zoechi** [comment] 2016-07-04 16:18
What is "dynamic data"? How do you want to pass it? What is not working? 
Can you please provide a Plunker that demonstrates what you try to accomplish and what is not working?

**Comment by ramana-chavakula** [comment] 2016-07-04 17:15
hi zoechi, 
this is my plnkr link: http://plnkr.co/edit/5ATJapZqtV5ieLJx4f2o?p=preview
In the 'list' route i am just showing the titles of all items in the ListComponent and i want to view individual item in separate route say 'item'.
I just want to pass the selected item object to 'item' route, which i am not able to find in the documentation

Thanks in advance

**Comment by zoechi** [comment] 2016-07-04 17:43
I also wasn't able to pass data http://plnkr.co/edit/gIyMenTdIEkC4NajZu4M?p=preview
I don't know if this is supposed to work.

**Comment by fknop** [comment] 2016-07-04 19:35
Why not use a service for this kind of thing ?

**Comment by ramana-chavakula** [comment] 2016-07-05 05:53
hey zoechi,
[routerLink]="['/item', {data: item}] & this.router.navigate(['/item', {data: this.items[index]}]); 
will pass item in Params Object, I already tried that. I think there is no provision for passing data dynamically, so i created an issue

**Comment by ramana-chavakula** [comment] 2016-07-05 06:53
@fknop : Thanks for responding on this issue. 

It is one of way of solving the problem in setting params before route. this can be done using service as you mentioned in above thread.

But when we had a data provision to pass as an Object in ui.router where we were expecting similar behaviour in angular2 route which will helps us to communicate between 2 routes without adding data to URL.

please check the plunker which i drafted for zoechi reply, you will get clear picture on my issue.

**Comment by zoechi** [comment] 2016-07-05 08:34
similar to #5217

**Comment by cipriantarta** [comment] 2016-07-05 11:00
@zoechi, well it's rather a duplicate of #5217.
Using a service to pass RouteData should be seen as a workaround perhaps. I think that being able to add/merge/replace(with static data) RouteData using the .navigate() or .navigateByUrl() should be a feature that the routing should support. I can't think of a reason not to.

**Comment by LukeNZ** [comment] 2016-07-08 23:00
@fknop I'm also having this issue, and frankly creating an entire service just to pass data between two components which are navigatable to each other via `routerLink` seems like an expensive operation, when there could (should) be a way to pass through objects via `routerLink` anyway.

**Comment by lanocturne** [comment] 2016-09-02 15:36
At 3.0.0-rc.2 the data snapshot is always empty.
i.e.
```ts
 Route: {
    path: "test", 
    component: TestComp,
    **data**: {
      title: 'test title'
   }
}
```
At TestComp component or directive, log it from ActivatedRoute
```ts
this.route.data.subscribe(data=> console.log(data));
    console.log(this.route.snapshot.data["title"]);
```
The result would be {} and undefined

**Comment by vsavkin** [comment] 2016-10-10 23:34
As was pointed out, you can use a shared service to pass the data. After this is implemented https://github.com/angular/angular/issues/10248, you should be able to set arbitrary data while navigating.

**Closed by vsavkin** 2016-10-10 23:34 UTC
Labels: comp: router, type: feature

**Comment by arvstract** [comment] 2017-03-09 08:28
So ti'll now there is no way to pass data dynamically thru Router.Navigate?

**Comment by DzmitryShylovich** [comment] 2017-03-09 08:45
@arvstract nope

**Comment by arvstract** [comment] 2017-03-09 08:49
Can anyone please explain why they are not supporting it? Is it a bad idea? The problem is I cannot use a Shared service on sibling components unless they are bootstrapped via AppComponent, please correct me if I'm wrong.

**Comment by zoechi** [comment] 2017-03-09 08:54
If you provide the service on a common ancestor, then you get the same result.

**Comment by arvstract** [comment] 2017-03-09 08:59
But isn't it that the ancestor component who initialize the service must always be alive so that the service instance will continue existing?

**Comment by altinselimi** [comment] 2017-03-25 20:20
@arvstract No its not a bad idea. Its literally needed in very much any web app scenario when you have to navigate from a list view to a children of that list. Service for this kind of thing is so very stupid.

**Comment by earshinov** [comment] 2018-08-06 14:36
@vsavkin , #10248, as you should know as #10248's author, is about setting location state (in terms of browser's History API). In many cases you don't want the data you would pass with `router.navigate` to be persisted (what is done unconditionally by the History API). So #10248 does not really cover all cases. Please reopen this ticket.

**Comment by earshinov** [comment] 2018-08-06 14:45
List of tickets about passing data with router.navigate:
- #5217
- #8515
- #9804
- #10248 (this one is actually about location state)

Currently all the tickets are closed (except #10248 which addressed only a part of the problem), and the issue is still here.

**Comment by andreaslarssen** [comment] 2018-09-05 07:02
+1

**Comment by jasonaden** [comment] 2018-12-03 21:47
See #27198 for an implementation that supports this.
