### ISSUE TITLE
Dynamic Component Loader Example Doesn't Work

### ISSUE THREAD

**Issue by yanbu0** [angular/angular#19322] opened 2017-09-21 21:13 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Plunkr hangs on loading

## Expected behavior

Runs 

## Minimal reproduction of the problem with instructions

Go to https://angular.io/guide/dynamic-component-loader and click the live example link at the bottom of the page.

## What is the motivation / use case for changing the behavior?

Angular is pretty sweet, but extremely difficult to find up to date examples, use cases, and documentation on a lot of features.  Would be nice to have this work.

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by mlc-mlapis** [comment] 2017-09-21 21:25
@yanbu0 ... just change `ngAfterViewInit` hook to `ngOnInit` in `ad-banner.component.ts`.

**Comment by trotyl** [comment] 2017-09-22 01:43
Actually it's still working fine, `ExpressionChangedAfterItHasBeenCheckedError` won't break anything, just annoying.

**Comment by mlc-mlapis** [comment] 2017-09-22 07:52
@trotyl ... yes, it is true. The plunker was created before the moment when some other Angular changes later solved specific behaviors related to checking expression changes during one CD, and there wasn't any update on it to adapt all together.

**Comment by kapunahelewong** [comment] 2017-10-12 14:44
@yanbu0 Are you by chance running Ad Blocker (or any other pop up/ad blocker)? Mine didn't work at first, just like you described. Then I turned off ad blocker and it works fine. I always forget this when I go to that particular doc until at the bottom the unrendered banner reminds me.

**Comment by jenniferfell** [comment] 2018-04-25 09:35
Thank you, all. Link to plnkr has been replaced with link to stackblitz. A coding change was made to use OnInit, which resolved some errors.  Another issue has been opened to track the proposal to change the example to one that doesn't use "ad" in it (so ad blockers don't break this example), so I'm closing this as a duplicate of https://github.com/angular/angular/issues/18138. Thanks, again.

**Closed by jenniferfell** 2018-04-25 09:35 UTC
Labels: comp: core & compiler, comp: docs, freq2: medium, severity3: broken, type: bug/fix
