### ISSUE TITLE
fix(foreach): don't add initial iterator item

### ISSUE THREAD

**Issue by PascalPrecht** [angular/angular#809] opened 2015-02-26 13:00 UTC
When I've started to work on #729, it turned out that there's a bug in the `foreach` directive. When we pass it a collection of items, and the collection is empty, it still iterates over at least one (empty) item.

The bug is visualised right here: https://github.com/angular/angular/pull/729#discussion_r25237024

@vicb asked me to add a test for that and fix it.

I've created this issue to not forget to work on this. Gonna try to fix it after ng-conf.

**Comment by SekibOmazic** [comment] 2015-03-15 11:19
@PascalPrecht I've debugged through the code and couldn't reproduce the bug. Then I looked at you template and found that the closing element ist wrong. It should be `</li>` (it was missing `/`). Took me some time to realize it, but hey I learned more about `Foreach` directive.

**Comment by PascalPrecht** [comment] 2015-03-15 11:40
@SekibOmazic Sorry, I haven't had time to look into all that stuff myself yet. But it looks like you nailed it. Thank you so much!

**Comment by vicb** [comment] 2015-03-24 10:06
Seems like foreach works as expected

**Closed by vicb** 2015-03-24 10:06 UTC

**Comment by PascalPrecht** [comment] 2015-03-24 10:13
@vicb right, I thought this issue has already been closed. Hey would you mind taking a look at my latest snapshot in https://github.com/angular/angular/pull/729 ?

The code compiles, but I get an error at runtime due to `Function` annotations... Dunno what to do about it.
