### ISSUE TITLE
reactive form maxlength or maxLength

### ISSUE THREAD

**Issue by ChrisPanthera** [angular/angular#28721] opened 2019-02-14 01:55 UTC
# 🐞 bug report

### Affected Package
@angular/forms

### Is this a regression?

Not as far as I'm aware.

### Description

When building a form and using 'minLength' or 'maxLength' validation a captial 'L' is required in the typescript but a lower case 'l' is required in the HTML. This takes about 20 mins to work out every time I do this and have forgotten this quirk!

Is it 'minLength' and 'maxLength' or 'minlength' and 'maxlength' ??

## 🔬 Minimal Reproduction
In Typescript:

`			this.exampleForm = this.formBuilder.group({
				name: ['', Validators.required],
				number: ['', Validators.required],
				blah: ['', Validators.required],
				somethingValidated: ['', Validators.compose([
					Validators.required,
					Validators.minLength(2),
					Validators.maxLength(20)])
				],
			});`

In HTML:

`<mat-error *ngIf="gatewayForm.get('somethingValidated').hasError('minlength') || gatewayForm.get('somethingValidated').hasError('maxlength')">
				Maximum length is 20 characters.
			</mat-error>`

## 🌍  Your Environment

**Angular Version: 7**

**Comment by trotyl** [comment] 2019-02-14 05:44
Relates to or duplicate of https://github.com/angular/angular/issues/7407

**Comment by kara** [comment] 2019-02-19 23:16
@ChrisPanthera I hear ya. It can be confusing. As @trotyl points out, we discussed as a team and decided to keep it consistent with browser behavior when https://github.com/angular/angular/issues/7407 was filed (i.e. property names are camel-case, attributes are not).

**Closed by kara** 2019-02-19 23:16 UTC
Labels: comp: forms
