### ISSUE TITLE
Missing Steps on the Getting Started Page

### ISSUE THREAD

**Issue by erhanalankus** [angular/angular#43205] opened 2021-08-19 15:13 UTC
### Description

I was following the steps on the [getting started page](https://angular.io/start#pass-data-to-a-child-component) using stackblitz.

Adding the "ProductAlertsComponent" on stackblitz does not make the necessary changes to app.module.ts, so the user receives an error. And these necessary changes are not documented on the getting started page.

**Comment by gkalpak** [comment] 2021-08-19 16:12
I believe this is a duplicate of #43020.

**Closed by gkalpak** 2021-08-19 16:12 UTC
