### ISSUE TITLE
Error: inject() must be called from an injection context

### ISSUE THREAD

**Issue by dealloc** [angular/angular#25813] opened 2018-09-05 13:02 UTC
## I'm submitting a...

<pre><code>
[X] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

While creating a library I noticed that if you consume the library and try to inject a service that in turn has a dependency on either `NgModuleRef`, `Injector` or `ApplicationModule` it throws an error as shown below:
![2018-09-05 14_52_21-](https://user-images.githubusercontent.com/2164354/45094372-6023ea80-b11b-11e8-9949-462a724af7d6.png)

## Expected behavior

In Angular 5 we injected `NgModuleRef` without any problems, in Angular 6 one can still inject these classes, just not from anything that's in a library.

in other words, in Angular 5 this code worked fine, but breaks in Angular 6:
```typescript
public constructor(private readonly appModule: NgModuleRef<any>) {
	//
}
```

## Minimal reproduction of the problem with instructions
I've created a Github repository showcasing the issue [here](https://github.com/dealloc/Angular-25813-reproduction)

## What is the motivation / use case for changing the behavior?

We inject `NgModuleRef` in our company's internal libraries for on the fly reconfiguration of services, for this we need an injector that can resolve those services.

If there's a better way of accessing the injector from a service (in a library, from application itself it works!), that's a solution for me too.

## Environment

<pre><code>
Angular version: 6.1.6

Browser:
- [X] Chrome (desktop) version 68.0.3440.106
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [X] Firefox version 61.0.2
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [X] Edge version 42.17134.1.0
 
For Tooling issues:
- Node version: 9.11.1
- Platform:  Windows 10

Others:

</code></pre>

**Comment by mhevery** [comment] 2018-09-05 16:43
any reason why we can't have this reproduced as https://stackblitz.com/

**Comment by dealloc** [comment] 2018-09-05 16:53
Because the error only seems to occur when the service injecting `NgModuleRef` is in a library, at first glance Stackblitz didn't seem to support 2 projects (both library and app) in one project.
if I'm mistaken, I'm happy to make a reproduction of both on stackblitz

**Comment by alxhub** [comment] 2018-09-11 23:00
@dealloc do you have an example of such a library on NPM or a Git repo?

**Comment by dealloc** [comment] 2018-09-12 06:00
@alxhub unfortunately they're propriety libraries developed in house. I did provide a repository [here](https://github.com/dealloc/Angular-25813-reproduction) that demonstrates the functionality

**Comment by Vizalizer** [comment] 2018-10-01 19:29
Having the same problem, same context (Angular Library sharing Services to another App). In my case, once I import the 'HttpClient' from the '@angular/common/http' into the Service (calling it from the constructor like 'private http: HttoClient') triggers the problem. I tried with different Services, installing and uninstalling Angular packages.

**Comment by mhevery** [comment] 2018-10-25 22:53
So that error comes from Ivy injector which is not enabled yet, So it is very puzzling to me what you are doing which is causing Ivy to activate.

**Comment by dealloc** [comment] 2018-10-26 06:14
The problem seems to occur the moment we use `yarn link` to test the library in an application.
Does Angular treat linked packages differently and somehow enables Ivy then?

**Comment by ydomenjoud** [comment] 2018-11-20 13:58
> The problem seems to occur the moment we use `yarn link` to test the library in an application.
> Does Angular treat linked packages differently and somehow enables Ivy then?

same issue here : build an angular lib + npm link on build drectory = > same error

**Comment by wvdhaute** [comment] 2018-11-20 14:02
note: make sure to set preserveSymlinks to true, fixed our issue

**Comment by dealloc** [comment] 2018-11-20 14:06
Where do you set this property?

**Comment by wvdhaute** [comment] 2018-11-20 14:18
in angular.json of the project calling the angular lib via the link

projects.$name.architect.build.options.preserveSymlinks: true

**Comment by giggio** [comment] 2018-11-27 20:37
I had a related problem with the same error message `inject() must be called from an injection context`. It was solved after setting `preserveSymlinks` to `true` as @wvdhaute suggested. I also had warnings that were resolved after setting it: 
```
WARNING in <redacted>/node_modules/@angular/core/fesm5/core.js 15070:15-36
Critical dependency: the request of a dependency is an expression
WARNING in <redacted>/node_modules/@angular/core/fesm5/core.js 15082:15-102
Critical dependency: the request of a dependency is an expression
```

I am also working with a service from a library that is npm linked.

I am on Angular 7.

**Comment by dealloc** [comment] 2018-11-27 20:40
@mhevery is it safe to close the issue since it can trivially be resolved with `preserveSymlinks`?
Though it's not entirely clear to me what exactly causes the issue.

**Comment by trotyl** [comment] 2018-11-28 04:02
I have downloaded your repo today but cannot reproduce the issue:

![image](https://user-images.githubusercontent.com/6059170/49128219-4f8fa480-f305-11e8-9391-15797a9ac975.png)

If it can be solved by `preserveSymlinks`, most likely two different copies of `@angular/core` were bundled to the app.

**Comment by giggio** [comment] 2018-11-28 11:38
This is what I did: I created a project, then created a lib. Then I built the lib and npm linked the `dist` directory for the lib. Something like:

```
ng new
npm link /myapp/dist/mylib/
```

Then, when built I got the injection error and the warnings, unless I use `preserveSymlinks`.

Npm link will use symlinks. I am using it so I can test the lib with other Angular projects.

**Comment by Gerros** [comment] 2019-02-11 10:24
I am not using a own library which is in the same angular workspace like my app, but recently I added ngrx to my app and using a service in an effect lead to having this error. 
What it solved for me was to use the providedIn property in the Injectable decorator instead of registering the service in the app module in the providers .

```
@Injectable({
  providedIn: 'root'
})
export class HeroService {}
```

**Comment by maccurt** [comment] 2019-02-23 11:56
I am having this same problem in a jasmine test using Wallaby.js, my test run fine if run NG test. I will report back if I get it fixed. I did upgrade from 6 to 7 and I think it has something to do with Angular Material.. I will report back if I find something.

**Comment by pspkshah** [comment] 2019-03-01 10:02
I am also facing the same error

WARNING in ./src/node_modules/@angular/core/fesm5/core.js 4982:15-36
Critical dependency: the request of a dependency is an expression

WARNING in ./src/node_modules/@angular/core/fesm5/core.js 4994:15-102
Critical dependency: the request of a dependency is an expression

@wvdhaute  suggested solution does not worked to me.

**Comment by maccurt** [comment] 2019-03-01 13:40
I was only getting this when running WallabyJs. My issue was this: https://github.com/wallabyjs/public/issues/2007

I had to delete some folders to get it to work!

**Comment by DanielSuperSonic** [comment] 2019-05-20 12:42
`ng build` supports preserveSymlinks, but i'm having a problem with `ng serve`. preserveSymlinks are deprecated in angular 7 on `ng serve` but i still get that error.
there are any solution for that?

**Comment by alireza267** [comment] 2019-06-01 11:48
I have the same problem, my workspace includes 2 angular applications (version 8.0) and an angular library. I installed the library in the applications by 'npm link' command.  I also added **preserveSymlinks: true** to the angular.json of both applications. Now, one application works perfect and the other dont and below error is shown:
![image](https://user-images.githubusercontent.com/15701921/58747997-dd507600-8487-11e9-93f1-3885ded8dfe8.png)

**Comment by alireza267** [comment] 2019-06-08 04:05
Finally i solved it, 
I put this path in the  compilerOptions section of tsconfig.app.json of the angular application:
`"paths": {
      "@angular/*": [
        "../node_modules/@angular/*"
      ]
    }`

**Comment by chadbr** [comment] 2019-06-11 04:02
If it helps... 

The solution @wvdhaute suggested worked for me - Angular 8 & Angular 8 lib

**Comment by Vishwa17** [comment] 2019-06-12 09:39
I got this issue in Angular 8, I am using Ionic 4. Can someone help please to sort this issue?

**Comment by Muhammadinaam** [comment] 2019-07-18 01:55
> $name.a

not worked for me

**Comment by chakrachi** [comment] 2019-07-28 06:09
same issue here..

**Comment by MurhafSousli** [comment] 2019-07-29 04:16
I followed @wvdhaute comment, but I get `Schema validation failed with the following errors:
  Data path "" should NOT have additional properties(preserveSymlinks).` when I build the library!

**Comment by popsovy** [comment] 2019-08-13 13:56
Same issue here

**Comment by shabbir7252** [comment] 2019-09-26 16:18
In My Case 

> Same issue here

My Case:

```
  constructor(
    @Inject(MAT_DIALOG_DATA) public data: any,
    public matDialogRef: MatDialogRef<MatConfirmDialogComponent>) { }
```

**Comment by hiepxanh** [comment] 2019-10-22 13:27
```
            "preserveSymlinks": true,
```
Seem doesn't help. I got this problem when I import a library service that using some service in the constructor

**Comment by shabbir7252** [comment] 2019-10-22 13:32
> ```
>             "preserveSymlinks": true,
> ```
> 
> Seem doesn't help. I got this problem when I import a library service that using some service in the constructor

@hiepxanh  Send Screenshot

**Comment by hiepxanh** [comment] 2019-10-23 00:53
@shabbir7252  
![image](https://user-images.githubusercontent.com/16970990/67346772-02926d80-f56a-11e9-8854-46ab28422173.png)

```
 "dependencies": {
    "@angular/animations": "~8.2.5",
    "@angular/common": "~8.2.5",
    "@angular/compiler": "~8.2.5",
    "@angular/core": "~8.2.5",
    "@angular/forms": "~8.2.5",
    "@angular/platform-browser": "~8.2.5",
    "@angular/platform-browser-dynamic": "~8.2.5",
    "@angular/router": "~8.2.5",
    "@datorama/akita": "^4.10.8",
    "rxjs": "^6.5.3",
    "tslib": "^1.10.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.803.9",
    "@angular-devkit/build-ng-packagr": "~0.803.9",
    "@angular/cli": "~8.3.4",
    "@angular/compiler-cli": "~8.2.5",
    "@angular/language-service": "~8.2.5",
```
my info here sir

**Comment by pongells** [comment] 2019-11-08 12:38
> Finally i solved it,
> I put this path in the compilerOptions section of tsconfig.app.json of the angular application:
> `"paths": { "@angular/*": [ "../node_modules/@angular/*" ] }`

This solved the issue for me. However I am not using npm or yarn link, I am using the tsconfig paths to link directly to a library that sits on a different project.

**Comment by nagarjuna-immadi** [comment] 2019-11-24 07:14
> Finally i solved it,
> I put this path in the compilerOptions section of tsconfig.app.json of the angular application:
> `"paths": { "@angular/*": [ "../node_modules/@angular/*" ] }`

It solved my issue.

**Comment by lingberries** [comment] 2020-02-04 20:28
PreserveSymlinks and an **Inject decorator** have solved the issue for me. All of my services are in an external library. This is an example of one of them:

```
@Injectable({
    providedIn: 'root'
})
export class FirstService {

    constructor(
        @Inject(SecondService) private secondService: SecondService
    ) { }
...
```

Basically you shouldn't include other injectable services in your injectable service's constructor, but if you have to, put an @Inject decorator on it.

**Comment by rweads0520** [comment] 2020-02-11 21:38
> Finally i solved it,
> I put this path in the compilerOptions section of tsconfig.app.json of the angular application:
> `"paths": { "@angular/*": [ "../node_modules/@angular/*" ] }`

For me, `"@angular/*": [ "./node_modules/@angular/*" ]` (one dot, not two in the path) was what I needed, in addition to my own other mappings for my libraries. This only applies when using TypeScript path mapping instead of linking to the libraries, as documented [here](https://angular.io/guide/creating-libraries#use-typescript-path-mapping-for-peer-dependencies). Also, I put it in the tsconfig.json, not tsconfig.app.json. Either worked.

**Comment by mhevery** [comment] 2020-02-19 01:25
closing as Ivy is out and the original repro is no longer present.

**Closed by mhevery** 2020-02-19 01:25 UTC
Labels: comp: core, comp: ivy, fixed by Ivy, freq1: low, severity3: broken, type: bug/fix
