### ISSUE TITLE
ngcc compilation issue ERROR: Internal Error: Unexpected interpolation

### ISSUE THREAD

**Issue by AhsanAyaz** [angular/angular#33585] opened 2019-11-04 22:40 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....
`ngcc` while upgrading to Angular v9 RC 0 

### Is this a regression?

It seems like it. But I'm not sure

### Description
 A clear and concise description of the problem...
When upgrading an advanced web app that uses my library, ngcc fails and the whole update process is stuck.
I tried to update my [library](https://github.com/IOMechs/angular-tags-input) as well, but it got stuck at the same error, of course, during ngcc compilation.

## 🔬 Minimal Reproduction

 https://stackblitz.com/...

You can clone [https://github.com/IOMechs/angular-tags-input](https://github.com/IOMechs/angular-tags-input) and then follow the [guide](https://next.angular.io/guide/updating-to-version-9) for updating to V9. After migration succeeds, the error will appear during the `postinstall` script

## 🔥 Exception or Error
<pre><code>

[error] Error: Internal Error: Unexpected interpolation
    at error (/Users/ahsanayaz/Desktop/Personal/Contributions/angular-tags-input/node_modules/@angular/compiler/bundles/compiler.umd.js:2639:15)
    at _AstToIrVisitor.interpolationFunction (/Users/ahsanayaz/Desktop/Personal/Contributions/angular-tags-input/node_modules/@angular/compiler/bundles/compiler.umd.js:17529:179)
    at _AstToIrVisitor.visitInterpolation (/Users/ahsanayaz/Desktop/Personal/Contributions/angular-tags-input/node_modules/@angular/compiler/bundles/compiler.umd.js:10199:29)
    at Interpolation.visit (/Users/ahsanayaz/Desktop/Personal/Contributions/angular-tags-input/node_modules/@angular/compiler/bundles/compiler.umd.js:6481:28)
    at convertPropertyBinding (/Users/ahsanayaz/Desktop/Personal/Contributions/angular-tags-input/node_modules/@angular/compiler/bundles/compiler.umd.js:9975:52)
    at TemplateDefinitionBuilder.convertPropertyBinding (/Users/ahsanayaz/Desktop/Personal/Contributions/angular-tags-input/node_modules/@angular/compiler/bundles/compiler.umd.js:17529:44)
    at Object.value (/Users/ahsanayaz/Desktop/Personal/Contributions/angular-tags-input/node_modules/@angular/compiler/bundles/compiler.umd.js:17430:63)
    at /Users/ahsanayaz/Desktop/Personal/Contributions/angular-tags-input/node_modules/@angular/compiler/bundles/compiler.umd.js:17484:55
    at Array.map (<anonymous>)
    at /Users/ahsanayaz/Desktop/Personal/Contributions/angular-tags-input/node_modules/@angular/compiler/bundles/compiler.umd.js:17483:38
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 9.0.0-rc.0
Node: 10.14.2
OS: darwin x64
Angular: 9.0.0-rc.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.900.0-rc.0
@angular-devkit/build-angular      0.900.0-rc.0
@angular-devkit/build-ng-packagr   0.900.0-rc.0
@angular-devkit/build-optimizer    0.900.0-rc.0
@angular-devkit/build-webpack      0.900.0-rc.0
@angular-devkit/core               9.0.0-rc.0
@angular-devkit/schematics         9.0.0-rc.0
@angular/cdk                       8.2.3
@ngtools/webpack                   9.0.0-rc.0
@schematics/angular                9.0.0-rc.0
@schematics/update                 0.900.0-rc.0
ng-packagr                         9.0.0-rc.1
rxjs                               7.0.0-alpha.0
typescript                         3.6.4
webpack                            4.41.2
</code></pre>

**Anything else relevant?**

**Comment by EmaGht** [comment] 2019-11-05 06:46
Might be the same as https://github.com/angular/angular/issues/33575
I had the exact same error message... check if you are doing style interpolations in your components too

**Comment by IgorMinar** [comment] 2019-11-09 02:04
yeah, this is a dupe of #33575

**Closed by IgorMinar** 2019-11-09 02:04 UTC
Labels: comp: compiler, severity5: ivy-compat
