### ISSUE TITLE
Support for type of input and output

### ISSUE THREAD

**Issue by Springrbua** [angular/angular#25545] opened 2018-08-17 12:37 UTC
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[X] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
If I have an `Output` defined as `new EventEmitter<number>`, I can assign the corresponding `$event` to a variable of type `string` (or any other type), without getting an error or a warning.
The same goes for `Input`-bindings, I can assign a `number` to an `Input` of type `string`.
Also, I don't get any type informations for the `Input`, the `Output` or the `$event` inside the HTML.

## Expected behavior
It would be cool, if the language service is able to check the type of the `Input`s and `Output`s and show the same errors as TypeScript does.

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-gitter-mtojsc

`AppComponent` assigns a variable of type `string` to an `Input` of type `number`.
The component `OtherComponent` has an `Output` of type `object`, which is bound to the variable of type `string`.
Both should show an error.

## What is the motivation / use case for changing the behavior?
If you are using third-party-components, the code-completion shows you possible `Input`s and `Output`s. However, the types of them are missing and you have to use `go to definition` or search a documentation online. If the language service would provide type informations the API of those thrid-party-components would often be clear and no other documentaiton would be needed.

## Environment

<pre><code>
Angular version: 6.1.2
 
For Tooling issues:
- Node version: 8.10.0
- Platform:  Windows
- IDE/Editor: Visual Studio Code Insider (1.27.0)

Others:
I am using the vscode plugin `Angular Language Service` which is still using @angular/language-service@5.2.2. So I am not sure if the newer language service versions give type informations.
</code></pre>

**Comment by trotyl** [comment] 2018-10-04 16:13
Duplicate of https://github.com/angular/angular/issues/17483

**Comment by gkalpak** [comment] 2018-10-04 18:08
I don't think they are duplicates. #17483 is about the properties/property names. This one is about their values.
(Sure both issues could be merged into one, but as they stand they don't look like duplicates to me.)

**Comment by trotyl** [comment] 2018-10-05 03:49
@gkalpak My bad, wasn't accurate enough, this is exact duplicate of https://github.com/angular/angular/issues/21204, but which was closed.

Technically speaking, type-checking for inputs is a regression tracked by https://github.com/angular/angular/issues/20600, type-checking for outputs is a feature request at https://github.com/angular/angular/issues/16952, they're mostly unrelated (the former should be fixed in Ivy soon), so seems all the aspects has already been tracked somehow.

**Comment by Springrbua** [comment] 2018-10-05 06:35
@trotyl Isn't #20600 about AOT? This Issue is about the Language Service, which should give an error, if you are binding a wrong input type to an `@Input`.

Example:

<pre>
// test.component.ts (app-test)
@Input
num: number;

&lt;app-test [num]="<strike>'String is not valid'</strike>"&gt;&lt;/app-test&gt;

</pre>

Note the striked text, which should be the reported error (something like "`string` cannot be assigned to `number`").

For outputs I would like to get type informations of the `$event`. In vscode for example, I get `variable $event`, if I hover over it in the html. It would be cool, if it could show something like `variable $event: number` and again, it should show an error if I call a function which expects another type.
Example:

<pre>
// test.component.ts (app-test)
@Output
num: EventEmitter<number>;

// app.component.html
&lt;app-test (num)="printString(<strike>$event</strike>)"&gt;&lt;/app-test&gt;

// app.component.ts
public printString(value: string) {
}
</pre>
Again, the striked text is the reported error.

So, I don't think the Issues you referenced are the same, but they are probably related.
So if you think, this Issue can be closed, in favor of the others, then feel free to close it.

Thanks :)

**Comment by trotyl** [comment] 2018-10-05 06:43
> Isn't #20600 about AOT? This Issue is about the Language Service, which should give an error, if you are binding a wrong input type to an `@Input`.

It's only about type-checking, which is shared between compiler and language service.

> For outputs I would like to get type informations of the `$event`

It's only about the type of `$event` variable, which is currently `any` by design, so it's can always pass the type-checking and not being a BUG.

> In vscode for example, I get variable `$event`, if I hover over it in the html.

It's a orthogonal feature request at https://github.com/angular/angular/issues/26155 unrelated to the type-checking.

> So if you think, this Issue can be closed, in favor of the others, then feel free to close it.

I don't have right to do that, but can only help to link issues.

**Comment by gatimus** [comment] 2018-10-30 23:00
While type checking inputs and output would ultimately be nicer, if mistyped inputs become a design/build time error the should all existing components stop using [coercion](https://github.com/angular/material2/tree/master/src/cdk/coercion) on inputs? Basically if this feature gets fulfilled all of the existing components that gracefully handle mistypes will now have dead code.

**Comment by mohammedzamakhan** [comment] 2019-01-29 21:42
This is one thing that I love in using TypeScript with React. I think this will help lot of projects. Rather than checking types using if else, we can just get help from TypeScript. Here is an example for Types helping in the value of props

![types](https://user-images.githubusercontent.com/2327532/51942259-3c1fb900-23dc-11e9-8b88-0c36a4c1e7e5.gif)

**Comment by JoostK** [comment] 2021-05-13 20:33
With the Ivy language service now using the compiler type checking infrastructure, this now works for inputs and output events provided that `strictTemplates` is enabled.

**Closed by JoostK** 2021-05-13 20:33 UTC
Labels: P4, comp: language-service, feature, freq3: high
