### ISSUE TITLE
Some TypeScript syntax errors not detected during tests run

### ISSUE THREAD

**Issue by pkozlowski-opensource** [angular/angular#3457] opened 2015-08-03 14:46 UTC
Certain TypeScript errors are not detected / reported during unit tests run (test.unit.js). For example, create the following class (notice lack of the constructor’s body):

```js
class Foo {
  constructor(public bar);
}
```

There is no error / warning for such a case but weird things happen during time. TS playground correctly reports “Constructor implementation is missing”. It would be great if such errors were caught as early as possible.

I think I saw other cases where syntax errors were not reported properly, but can’t provide precise examples atm :-/

**Comment by alexeagle** [comment] 2015-08-04 18:48
Dupe of https://github.com/angular/angular/issues/3178

**Closed by alexeagle** 2015-08-04 18:48 UTC
Labels: comp: build/dev-productivity, hotlist: typescriptification
