### ISSUE TITLE
[Chrome 80] open mat-dialog reactive form error: Cannot find control with name

### ISSUE THREAD

**Issue by nminhduc** [angular/angular#35214] opened 2020-02-07 07:42 UTC
I check this bug not happen on chrome 79. but on chrome 80, the first time I open a popup  (after reloading the page). The error with occurs: ERROR Error: Cannot find control with name: 'file'. After that I close popup and re-open popup. The issue is resolved

Angular version: 8

![Capture](https://user-images.githubusercontent.com/18206570/74010401-fbc42500-49b7-11ea-8853-90a75b640764.PNG)

**Comment by michalma** [comment] 2020-02-07 09:35
I have similar problems with reactive forms after updating to Chrome 80. I didn't have these errors before chrome update.
Angular 8.2.3

Some of the errors i have:
`Cannot read property 'valueChanges' of null`
`Cannot find control with name: 'foo'`
`Cannot find control with unspecified name attribute`

**Comment by skyquartam** [comment] 2020-02-07 10:06
We have the same bug in Production site, it happens only on Chrome 80

**Comment by adam-marshall** [comment] 2020-02-07 11:14
May be this Chrome 80 bug report https://bugs.chromium.org/p/chromium/issues/detail?id=1049982, as the _find method which gets the control from the nested structure uses Array.reduce.

**Comment by MoxxiManagarm** [comment] 2020-02-07 13:57
Possible application-sided workaround: use `form.controls[name]` (https://stackoverflow.com/questions/49642926/formgroup-get-vs-formgroup-controls-in-reactive-form-angular)

**Comment by JulienB37** [comment] 2020-02-07 14:16
Same problème using ionic4/Angular.

**Comment by pkozlowski-opensource** [comment] 2020-02-07 14:25
Cross-referencing #35219 as it seems point to the same root cause.

**Comment by rodolfojnn** [comment] 2020-02-07 14:42
The same happening here with several formcontrols. The error seems random and does not always happen. It was happening in Chrome Canary a few weeks ago, but I thought it was something related to that version

**Comment by msorens** [comment] 2020-02-07 21:02
Same problem here; we were just beginning to investigate and found this issue.

**Comment by chimurai** [comment] 2020-02-07 22:12
RE: https://github.com/angular/angular/issues/35214#issuecomment-583346756

Monkey patching `Array.reduce` seems to resolve the issue.

Patch can be found in:
https://bugs.chromium.org/p/chromium/issues/detail?id=1049982#c7

**Comment by NicolasTicona** [comment] 2020-02-08 00:27
Yeah, I'm having the same problem in my project. @rodolfojnn  you´re right it's random.

**Comment by jecraig** [comment] 2020-02-08 01:45
I've gotten the same issue. Seems to be caused when a form re-renders for the first time. Also only seems to happen that first time. After it happens once, it appears to clear up for that tab.

**Comment by hiepxanh** [comment] 2020-02-08 14:36
having the same problem on first time render

**Comment by nminhduc** [comment] 2020-02-10 02:48
How to work around?

**Comment by oridark** [comment] 2020-02-10 06:11
same problem with angular 7.x
chrome updated two days ago and we found this problem ,hope someone can solve it quickly

**Comment by phoenix09208** [comment] 2020-02-10 09:05
i also receive these error
`Cannot find control with unspecified name attribute`
or
`Cannot read property 'valueChanges' of null`

I have tested same mat-dialog with same reactive form, it does not happen all the time, but only first time when application is loaded

**Comment by AleRob90** [comment] 2020-02-10 16:04
> The same happening here with several formcontrols. The error seems random and does not always happen. It was happening in Chrome Canary a few weeks ago, but I thought it was something related to that version

I had the same problem with Edge Chromium for a few weeks.

**Comment by ZetaPR** [comment] 2020-02-11 13:14
Same here, we started having problems in our production applications after the update to Chrome 80
All the time the error is the same 'Cannot find control with name: '

**Comment by denys5dev** [comment] 2020-02-12 06:43
Same problem with Crome 80.
Also in other project, there we are using not Mat open dialog just dx popup and reactive forms inside.

**Comment by pokermanx** [comment] 2020-02-12 07:54
Same here on production and dev, Angular 6, latest chrome eats up form controls. One time case for page reload. Cannot reproduce since its happens occasionally.

**Comment by adrienverge** [comment] 2020-02-12 08:18
Posting comments like "*same here, I also have the problem*" is probably not useful now.

The bug is [known](https://bugs.chromium.org/p/chromium/issues/detail?id=1049982), there is a fix, it has been merged, and will be released in the next Chrome version.
In the meantime, there are JS-side workarounds that fix the problem, see for example https://github.com/angular/angular/issues/35219#issuecomment-583425191.

**Comment by chimurai** [comment] 2020-02-12 09:13
Angular also landed a fix for this issue: https://github.com/angular/angular/pull/35349

**Comment by StephenFluin** [comment] 2020-02-12 22:07
The fix is in testing on Chrome Canary and we hope it will be available soon on Chrome 80. In the mean time we shipped an update for 9.0.1 to workaround this.

**Comment by manklu** [comment] 2020-02-13 23:34
Looks like it was fixed in 80.0.3987.106

**Closed** 2020-02-13 23:53 UTC
Labels: comp: forms
