### ISSUE TITLE
Feature: Ability to inject component of unknown type

### ISSUE THREAD

**Issue by dawidgarus** [angular/angular#26532] opened 2018-10-18 08:40 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
To inject component into directive you must specify type of injected component, either using class name or injection token which the component must provide, ex.:
```typescript
class MyDirective {
  constructor(@Host() component: MyComponent) {}
}
```

## Expected behavior
In some cases You might want to inject component of unknown type and use duck typing to determine what You want to do with the component, ex.:
```typescript
class MyDirective {
  constructor(@Host() @Optional() @Inject(ANY_COMPONENT) component: any) {
    if (hasDesiredBehavior(component)) {
      // do something
    }
  }
}
```

## Minimal reproduction of the problem with instructions
N/A

## What is the motivation / use case for changing the behavior?
Example 1.
Let's say you have InputComponent and 10 other components which derive from it, like: InputNumberComponent, InputTelephoneComponent etc.
All derived components must explicitly provide themselves as InputComponent if you want to inject them as InputComponent, which generates a lot of boiler plate code. Something like this could be much simpler:
```typescript
constructor(@Host() @Optional() @Inject(ANY_COMPONENT) component: any) {
  if (component instanceof InputComponent) {
    // do something
  }
}
```
Especially since the directive intended behavior is to be always used with InputComponent.

Example 2.
Injecting using class name creates dependency between two js modules and forces you to import angular module which has injected component event though it is optional dependency. This could be avoided using injection tokens but sometimes you don't want or can't add provider to every component.

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by pkozlowski-opensource** [comment] 2018-10-18 08:44
This is a duplicate of #8277, feel free to add your use-case in-there.

**Closed by pkozlowski-opensource** 2018-10-18 08:44 UTC
