### ISSUE TITLE
DebugElement Query By.directive returning the wrong directive when a component has same selector

### ISSUE THREAD

**Issue by gnomeontherun** [angular/angular#29014] opened 2019-02-27 22:23 UTC
# 🐞 bug report

### Affected Package
@angular/core -> DebugElement

### Is this a regression?
I'm not sure.

### Description
If you have a component and a directive with the same selector, using `debugElement.query(By.directive())` will always return the component and not the directive. This appears to be due to that DebugElement collects based on elements, so the component is registered with DebugElement but if there is a directive with the same selector it is lost.

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-1dxvad?file=src%2Fapp%2Fdashboard%2Fdashboard-overloaded.directive.spec.ts

If you view this reproduction, you'll see a test running. There are two directives, the DashboardComponent and DashboardOverloadedDirective (it does nothing except console.log). You can see both get instantiated in the test component because they share the same `app-dashboard` selector.

Now, when I write a test to query the debugElement by the two directives, both queries return the DashboardComponent instead of the actual directive. The test is below from the stackblitz demo.

```ts
it('should query for the directives separately', function() {
    const component = fixture.debugElement.query(By.directive(DashboardComponent));
    const overloaded = fixture.debugElement.query(By.directive(DashboardOverloadedDirective));
    expect(component.componentInstance.constructor.name).not.toEqual(overloaded.componentInstance.constructor.name);
})
```

I would expect that `debugElement.query(By.directive(DashboardOverloadedDirective))` would return an instance of the DashboardOverloadedDirective and not the DashboardComponent.

With some debugging I see that the test only creates a debugElement for the DashboardComponent (set a breakpoint on https://github.com/angular/angular/blob/master/packages/core/src/debug/debug_node.ts#L44), which makes sense in some ways because its one element. However, I have no way to access the controller for the directive on that element. 

## 🔥 Exception or Error

The error is that both queries above resolve to the same DashboardComponent.

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 7.0.3
Node: 10.12.0
OS: darwin x64
Angular: 7.0.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.10.3
@angular-devkit/build-angular      0.10.3
@angular-devkit/build-ng-packagr   0.10.3
@angular-devkit/build-optimizer    0.10.3
@angular-devkit/build-webpack      0.10.3
@angular-devkit/core               7.0.3
@angular-devkit/schematics         7.0.3
@angular/cli                       7.0.3
@ngtools/json-schema               1.1.0
@ngtools/webpack                   7.0.3
@schematics/angular                7.0.3
@schematics/update                 0.10.3
ng-packagr                         4.3.0
rxjs                               6.3.3
typescript                         3.1.3
webpack                            4.19.1
</code></pre>

**Anything else relevant?**

The workaround is to grab the directive `fixture.debugElement.query(By.directive(DashboardComponent)).injector.get(DashboardOverloadedDirective)` but is not obvious.

**Comment by pkozlowski-opensource** [comment] 2019-02-28 15:25
I feel like there is some confusion going on here WRT how `TestBed` / queries work.

The mental model is following: 
1)  `fixture.debugElement.query(By.directive(SomeDirective))` returns a (debug) _element_.
2) Any angular element can have multiple directives "attached" to it (multiple directives and _one_ component can match on a given element).

Given the above  this statement:

> Now, when I write a test to query the debugElement by the two directives, both queries return the DashboardComponent instead of the actual directive

is not accurate and we should rather say: 

Now, when I write a test to query the debugElement by the two directives, both queries return the same element (and this elements might have multiple directives matching on it).

Then `componentInstance` _on_ a debug element gives you a component instance (if this element happens to be a host for a component). As there can be only one component on a given element the  `componentInstance` will have always the same instance - no matter how the element was retrieved (queried). 

>  The workaround is to grab the directive `fixture.debugElement.query(By.directive(DashboardComponent)).injector.get(DashboardOverloadedDirective)` but is not obvious.

This is not a workaround, this is a proper way of doing things. 

I'm going to close this issue since it works as designed.

**Closed by pkozlowski-opensource** 2019-02-28 15:25 UTC
