### ISSUE TITLE
[plugin] @angular/language-service overrides but doesn't implement 'findRenameLocations' API

### ISSUE THREAD

**Issue by vrubezhny** [angular/angular#42715] opened 2021-06-30 14:44 UTC
# Bug Report

### Affected Package

 The issue is caused by package `@angular/language-service`

### Is this a regression?

 No.

### Description
 
Having  `@angular/language_service`  plugin loaded prevents  normal behavior of  `Refactoring -> Rename` operations. 

In turn out hat `@angular/language_service` plugin overrides the normal behavior of some methods of TS LanguageService interface implementation and `findRenameLocations` is one of those methods that is used to find the rename locations in `Refactorings -> Rename` operation, (see: https://github.com/angular/angular/blob/c7f9516ab920baee755d61ce0deea502e88a58ba/packages/language-service/src/ts_plugin.ts#L168):
```
  return {
    // First clone the original TS language service
    ...tsLS,
    // Then override the methods supported by Angular language service
    getCompletionsAtPosition,
    getQuickInfoAtPosition,
    getSemanticDiagnostics,
    getDefinitionAtPosition,
    getDefinitionAndBoundSpan,
    getTypeDefinitionAtPosition,
    getReferencesAtPosition,
    getSignatureHelpItems,
    findRenameLocations,    ///  <<<=== Line 168: Here the fileRemaneLocations method is overridden 
    getTcb,
    getComponentLocationsForTemplate,
  };
```

However `@angular/language_service` plugin doesn't provide its own implementation for this overridden method, instead it contains a default 'empty' stub-like method (see:
https://github.com/angular/angular/blob/c7f9516ab920baee755d61ce0deea502e88a58ba/packages/language-service/src/ts_plugin.ts#L132):
```
  function findRenameLocations(
     fileName: string, position: number, findInStrings: boolean, findInComments: boolean,
     providePrefixAndSuffixTextForRename?: boolean): readonly ts.RenameLocation[]|undefined {
   // not implemented in VE Language Service
   return undefined;
 }
```

... which always returns `undefined,` so the rename locations are never returned.

As far as I understand, NG LanguageService currently doesn't implement `findRenameLocations` method, so the simplest way to fix this issue is to exclude the method from being overridden (at line: https://github.com/angular/angular/blob/c7f9516ab920baee755d61ce0deea502e88a58ba/packages/language-service/src/ts_plugin.ts#L168) so the let default TS LanguageService implementation to take care of searching rename locations. 

## Minimal Reproduction

 
In WWD (https://projects.eclipse.org/proposals/eclipse-wild-web-developer):
- create a simple project and a JS-file.
- Add some function/variable definition and references to that function/variable. 
- Right click on the function/variable name and select `Refactorings -> Rename`. 
- Then follow the wizard steps (currently it couldn't fine any locations to rename while normally the rename operation should be finished successfully).
 

## Exception or Error
<pre><code>

None
</code></pre>

## Your Environment

**Angular Version:**
<pre><code>

@angular/language-server@11.1.1,

but also reproducible using the latest available:

@angular/language-server@12.1.0,
</code></pre>

**Anything else relevant?**

IDE: WildWebDeveloper (https://projects.eclipse.org/proposals/eclipse-wild-web-developer)

Original issue: https://github.com/eclipse/wildwebdeveloper/issues/680

**Comment by atscott** [comment] 2021-06-30 21:35
`findRenameLocations` is implemented in the Ivy-based language service here: https://github.com/angular/angular/blob/1445dba903552d457fe15cfa3a5a6c7860482805/packages/language-service/ivy/ts_plugin.ts#L67-L75. The View Engine implementation is stubbed in to return `undefined`. 

We share the downstream server code between both implementations so we had to stub out the View Engine one to avoid an error. Though we do have a check now to enable/disable the capability in the session code (https://github.com/angular/vscode-ng-language-service/blob/3ef2e9070b647b631ab7360bb4c2760f227163e2/server/src/session.ts#L588-L592), it's not clear to me why we need to update the View Engine implementation to not stub the method out. `undefined` is a valid return value for the method so I'm not sure what the issue is here. Shouldn't this be handled by the downstream plugin?

**Comment by atscott** [comment] 2021-06-30 22:13
@vrubezhny I've read a little bit of the issue comments on the `wildwebdeveloper` repo and am a bit confused about how things are architected there. I'm not sure should rely on the Angular Language Service to give TypeScript answers. How does eclipse manage multiple rename providers for a given file extension?

**Comment by vrubezhny** [comment] 2021-06-30 23:57
WWD's JSTSLanguageServer, starts  `typescript-language-server` (which loads `tsserver`),  `@angular/language-service` and some other typescript plugins together  in Node.js and uses LSP4E/LSP4J in order to communicate with the the LS from Eclipse plugins.  
 
As far as I tried to debug it, in our case tsserver serves our requests if not overridden by some loaded typescript plugin. In our case `@angular/language-service` plugin overrides some requests, but in most cases it takes the answers from tsserver, but not in case of a `rename` request  - in this case `@angular/language-service` doesn't `reroute` the request neither to  TS nor to NG, it just returns 'undefined` result.

The mentioned Ivy-based language service isn't used (however,  probably it could solve the problem).  And currently I have no idea on if we can turn it on (and how to make it, if we can).

Every `textDocument/rename` request downs at https://github.com/angular/angular/blob/c7f9516ab920baee755d61ce0deea502e88a58ba/packages/language-service/src/ts_plugin.ts#L132, where `findRenameLocations` is just a stub returning `undefined` result.

Looking at the `@angular/language-service` installed to node_modules of WWD I  can see `@angular/language-service/bundles/ivy.js` script, but it's never being executed in our case. 

Rename ''capability  is `enabled` in out case and is defined by `typescript-language-server` capanilities, the `textDocument/rename` LSP request goes to `findRenameLocations` that is overridden by `@angular/language-service/bundles/language-services.js` (not by `ivy.js ` in our case) that returns 'undefined` - so no locations could be found == not working rename. 

I'm not saying that removing this override (to make a tsserver's implementation to return locations) is the only solution for us - implementing it in https://github.com/angular/angular/blob/c7f9516ab920baee755d61ce0deea502e88a58ba/packages/language-service/src/ts_plugin.ts#L132 like the following example 
```
        function findRenameLocations(fileName, position, findInStrings, findInComments, providePrefixAndSuffixTextForRename) {
            if (!angularOnly) {
                 const result = tsLS.findRenameLocations(fileName, position, findInStrings, findInComments, providePrefixAndSuffixTextForRename);
                if (result) {
                    // If TS could answer the query, then return results immediately.
                   return result;
                }
            }
            return ngLS.findRenameLocations(fileName, position);
        }
```
could also help us to get rename functionality back to work. Still not sure if we can switch it to  use Ivt implementation.

PS: Sorry if my explanation is too messy.

**Comment by atscott** [comment] 2021-07-01 00:13
@vrubezhny I created #42727 to resolve this because I don't think we ever really needed to add the override in the first place. This will resolve your issue, and will be included in the next release (on July 7).

That said, I still have a concern with how things work in the `JSTSLanguageServer`. It seems like the last registered plugin which provides an implementation for the function wins out. This seems like it could cause issues in the future similar to what happened here. It might be worth doing some more investigation into what's going on there and if you are able to configure which plugin answers the query or maybe combine the results from multiple plugins.

**Comment by vrubezhny** [comment] 2021-07-01 00:44
@atscott Thanks for fixing this!

**Closed** 2021-07-01 22:24 UTC
Labels: comp: language-service
