### ISSUE TITLE
ngOnDestroy not called for injectables created via factory providers

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#22466] opened 2018-02-27 02:08 UTC
## Current behavior

```
export class DestroyTest implements OnDestroy {
  ngOnDestroy() {  // <<<<< this method is NEVER called
    console.log('ngOnDestroy DestroyTest called');
  }
}

export class DestroyTest2 implements OnDestroy {
  ngOnDestroy() { // <<<<< this method IS called when the app ref is being destroyed
    console.log('ngOnDestroy DestroyTest2 called');
  }
}

export function createDestroyTest() {
  return new DestroyTest();
}

@NgModule({
  imports:      [ BrowserModule, FormsModule ],
  declarations: [ AppComponent, HelloComponent ],
  bootstrap:    [ AppComponent ],
  providers: [
    {provide: DestroyTest, useFactory: createDestroyTest},
    DestroyTest2
  ]
})
export class AppModule {
  constructor(
    destroyTest1: DestroyTest, destroyTest2: DestroyTest2) {}
}
```

## Expected behavior
the `ngOnDestroy` method, if present, should be called on all values provided via DI regardless of the provider type.

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-h15slp

## Environment

<pre><code>
Angular version: 6.0.0-beta.x
</code></pre>

// Note: reported by GX

**Comment by trotyl** [comment] 2018-02-27 02:17
Duplicate of #14818, #22240

**Comment by tmair** [comment] 2018-03-01 09:38
There are already bugs within the angular framework, that are caused by this issue (for example the Router is created via a factory function).

The associated bugs contain some comments, that it is currently not possible to do an analysis at compile time if the factory function returns an object that implements the ngOnDestroy hook and that currently this works as intended.

**Comment by swicken** [comment] 2018-03-22 15:06
We are encountering what appears to be this issue in our application as well. Any route changes with routerLink or router.navigate, ngOnDestroy is not called and the component becomes detached in memory. This is causing a pretty severe memory leak.

Does anyone have any workarounds for this?

**Closed** 2018-05-08 20:56 UTC
Labels: comp: core & compiler, freq2: medium, hotlist: google, severity4: memleak, type: bug/fix

**Comment by amitport** [comment] 2018-07-04 11:41
@IgorMinar this is not resolved for me after https://github.com/angular/angular/commit/fc034270ced8f17cf17a82d3f8382dcef435b9a6for me
(using angular `6.1.0-beta.3`)

**Comment by llorenspujol** [comment] 2019-02-14 15:35
Still happening on angular version 8.0.0-beta.3.

This MR [fc03427](https://github.com/angular/angular/commit/fc034270ced8f17cf17a82d3f8382dcef435b9a6) solved the issue for the services provided at Module level, not at Component level.

Is there something that privates to solve the issue also for services provided at Component level?
it is quite annoying that in some cases it works and in others it does not 😕 .

**Comment by pkozlowski-opensource** [comment] 2019-02-14 15:38
> Is there something that privates to solve the issue also for services provided at Component level?
it is quite annoying that in some cases it works and in others it does not

@llorenspujol could you please create a new issue with a minimal reproduce scenario in a Stackblitz? Module and component level providers go through a _slightly_ different path so we might have missed it.

**Comment by llorenspujol** [comment] 2019-02-14 18:47
@pkozlowski-opensource I have created an issue explaining the bug: https://github.com/angular/angular/issues/28738. I also have created a MR: https://github.com/angular/angular/pull/28737 that includes 2 test that covers the destroy functionality of the services provided at component level. One pass and one fails, and they both should pass.
