### ISSUE TITLE
Angular elements methods are not exposed

### ISSUE THREAD

**Issue by babloo04** [angular/angular#53565] opened 2023-12-14 06:52 UTC
### Which @angular/* package(s) are relevant/related to the feature request?

elements

### Description

While creating angular Elements using out-box APIs, methods of components are not exposed.

Example
```
@Component(
selector: "animal",
  templateUrl: "./animal.component.html",)
  export class Animal{
    call() {
      console.log("Animal call");
      return 'call complete'
    }
}
```

here call() method is not available when we use "Animal" component as Angular Elements(web-component).

```
const animal = document.querySelector("animal");
animal.call() // undefined or error
```

### Expected behaviour : 
In angular elements method must be exposed to outside

### Proposed solution

There must be some decorator similar to stenciljs

### Alternatives considered

a

**Comment by kukjevov** [comment] 2023-12-14 08:36
This is a duplicate of very old issue https://github.com/angular/angular/issues/22114

**Comment by JoostK** [comment] 2023-12-14 08:45
Closing as duplicate of #22114

**Closed by JoostK** 2023-12-14 08:45 UTC
