### ISSUE TITLE
JSON Parse error

### ISSUE THREAD

**Issue by liyanjie8712** [angular/angular#21244] opened 2018-01-02 05:53 UTC
When the server respond a json string value like '"abc"' with quotes, respnse.json() will get an error "Unexpected token a in JSON at position 0",response.text() get a incorrect string 'abc' without quotes.

**Comment by Toxicable** [comment] 2018-01-02 05:56
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).


---

assuming you're using HttpClient use `responseType: 'text'`
more here https://angular.io/guide/http

**Comment by liyanjie8712** [comment] 2018-01-02 06:14
Maybe I did not express clearly.

Server respond: {"id",1,"name":"test"}, parsed to js object:{id,1,name:"test"}, correct.
Server respond: 0, parsed to js object:0, correct.
Server respond: [1,2,3,4,5], parsed to js array [1,2,3,4,5], correct.
Server respond: "abc", will be parsed to js object "abc", but error.

in angualr response, "abc" changed to abc without quotes

**Comment by liyanjie8712** [comment] 2018-01-02 06:15
I already set {responseType: ResponseContentType.Json}

**Comment by LinBoLen** [comment] 2018-01-02 06:17
try `JSON.parse("abc")`

**Comment by liyanjie8712** [comment] 2018-01-02 06:22
In that case, JSON.parse('"abc"') is correct.Server respond "abc",it is string '"abc"'.

**Comment by trotyl** [comment] 2018-01-02 06:47
Duplicate of #18396, has been fixed in `5.0.0-beta.6` already.

<sub>Please note `@angular/http` is deprecated and out of maintenance, make sure you're using `@angular/common/http`.</sub>

**Comment by pkozlowski-opensource** [comment] 2018-01-02 10:27
Yep, this is a duplicate of #18396 indeed, thnx @trotyl

**Closed by pkozlowski-opensource** 2018-01-02 10:27 UTC
