### ISSUE TITLE
ngModel: Typing quickly causes cursor position reset

### ISSUE THREAD

**Issue by NiXXeD** [angular/angular#6918] opened 2016-02-05 17:33 UTC
Tested on OSX, in Chrome 47.0.2526.111 (64-bit), and Safari 9.0.3 (11601.4.4)

Example plunker: http://plnkr.co/edit/xnGVkNC1xlh958qQoJJ2?p=preview

Scenario: An input/textarea with `[(ngModel)]` has some pre-existing text. Put the cursor somewhere in the middle or beginning of the text. Type very quickly. It seems as if a certain number of input events will trigger the cursor position to reset to the very end of the input.

Before typing quickly:
![screen shot 2016-02-05 at 11 26 23 am](https://cloud.githubusercontent.com/assets/5414721/12853726/50003422-cbfb-11e5-924f-51ecbf314f64.png)

After typing `asdfjkl` quickly:
![screen shot 2016-02-05 at 11 27 08 am](https://cloud.githubusercontent.com/assets/5414721/12853755/6e180ade-cbfb-11e5-9da7-65b17ad4babf.png)

Note the cursor position, and the letters started appearing after the text.

An input without the `[(ngModel)]` works correctly.

**Comment by zoechi** [comment] 2016-02-05 17:55
dup of #6311

**Comment by robwormald** [comment] 2016-02-05 23:13
closing as dupe of #6311

**Closed by robwormald** 2016-02-05 23:13 UTC
