### ISSUE TITLE
TitleCasePipe incorrectly capitalizes norwegian letters in the middle of a word

### ISSUE THREAD

**Issue by eTallang** [angular/angular#20494] opened 2017-11-17 06:59 UTC
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior
Words containing norwegian (and probably other languages) letters are incorrectly titlecased in the middle of the word when using the titlecase pipe.

## Expected behavior
The the titlecase pipe should not capitalize norwegian letters in the middle of the word.

## Minimal reproduction of the problem with instructions
http://plnkr.co/edit/oZdT53L1g7J7G3Sl4VJs?p=preview
The example above illustrates how the word 'utgått' is titlecased into 'UtgÅTt'. The propper transformation would be 'Utgått'.

## Environment

<pre><code>
Angular version: 5.0.2
</code></pre>

Browser:
- [x] Chrome (desktop) version 61.0.3163.100
- [x] IE version 11.674
- [x] Edge version 40.15063.674.0

**Comment by gkalpak** [comment] 2017-11-17 09:03
Closing as duplicate of #16586. There is a PR in progress (#20123), but it is not as straight forward :grin:

**Closed by gkalpak** 2017-11-17 09:03 UTC
