### ISSUE TITLE
Expose interface type for HTTP request options parameters

### ISSUE THREAD

**Issue by tkutcher** [angular/angular#46392] opened 2022-06-16 13:51 UTC
### Which @angular/* package(s) are relevant/related to the feature request?

common

### Description

It would be nice for http requests if there was an exposed interface type for the options parameter rather than defining them in the method signatures directly. Example scenario is where I essentially want to decorate the base HttpClient service  - and I want to give it (almost) the full options API in general and forward that to the main client. It would be nicer if I could type it with something like `HttpRequestOptions` rather than copying the entire thing for each overload I want to potentially use. Simple scenario would be a service that decorates `HttpClient` to always use the same base/host when building the URL.

### Proposed solution

Ideally, define some interface along the lines of this:

```ts
type HttpRequestObserve = 'body' | 'events' | 'response';
type HttpRequestResponseType = 'arraybuffer' | 'blob' | 'json' | 'text';

export interface HttpRequestOptions<
  O extends HttpRequestObserve = HttpRequestObserve,
  R extends HttpRequestResponseType = HttpRequestResponseType
  > {
  headers?: HttpHeaders|{[header: string]: string | string[]},
  context?: HttpContext,
  observe?: O,
  params?: HttpParams|
    {[param: string]: string | number | boolean | ReadonlyArray<string|number|boolean>},
  reportProgress?: boolean,
  responseType?: R,
  withCredentials?: boolean,
}

```

Then signatures become as simple as:

```ts  
get<T>(url: string, options?: HttpRequestOptions<"body", "json">): Observable<T>;)
```

----

Added benefit is now client-code (clients of the angular/common library) can type anything they want to http options much easier.

I see the comment [here](https://github.com/angular/angular/blob/df1652e7d747a698a87a162f18717618422f4a43/packages/common/http/src/client.ts#L22) references a `HttpRequestOptions` type but I don't see any other references to that type in the source code.

I would be willing to submit a PR but wanted to post issue to see thoughts first.

### Alternatives considered

Right now I have that interface defined in my projects.

**Comment by alxhub** [comment] 2022-06-16 23:17
Duplicate of #18586 (which has a _lot_ more discussion on the pros/cons of the `HttpClient` overloads).

**Closed by alxhub** 2022-06-16 23:17 UTC
Labels: comp: common/http

**Comment by tkutcher** [comment] 2022-06-16 23:52
@alxhub thanks - thought it might have been a duplicate but couldn't find
