### ISSUE TITLE
ngAfterContentChecked() fires inconsistently for @Directive

### ISSUE THREAD

**Issue by pauldraper** [angular/angular#27877] opened 2018-12-31 19:02 UTC
# 🐞 bug report

### Affected Package

@angular/core

### Is this a regression?

Unknown.

### Description

The `ngAfterContentChecked()` hook sometimes fires for directives and sometimes does not.

The [documentation](https://angular.io/api/core/AfterContentChecked) says

> A callback method that is invoked immediately after the default change detector has completed checking all of the directive's content.

However, sometimes the content of a directive is checked and the hook is not invoked.

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-after-content

When toggling the button, the contents of `AfterContentDirective` changes. The `AfterContentDirective` in `Container2Component` (using `Default`) has the hook called, but the `AfterContentDirective` in `Container1Component` (using `OnPush`) does not have the hook called.

I expect that in both cases `ngAfterContentChecked()` is called.

```typescript
import { AfterContentChecked, ChangeDetectionStrategy, Component, Directive, EventEmitter, Injectable, Input, NgModule, OnDestroy, OnInit, VERSION } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { BehaviorSubject } from 'rxjs';

@Injectable()
export class LogService {
  private readonly _logs: string[] = [];

  readonly logs = new BehaviorSubject<string[]>(this.logs);

  clear() {
    this._logs.length = 0;
    this.logs.next(this._logs);
  }

  log(log: string) {
    this._logs.push(log);
    this.logs.next(this._logs);
  }
}

@Component({
  changeDetection: ChangeDetectionStrategy.OnPush,
  selector: 'app',
  template: `
    <p class="block">Angular {{ version }}</p>
    <button class="block" (click)="state = !state" type="button">Toggle</button>
    <container1>&lt;container1> {{ state ? 'True' : 'False' }}</container1>
    <container2>&lt;container2> {{ state ? 'True' : 'False' }}</container2>
    <log></log>
  `,
})
export class AppComponent {
  readonly version = VERSION.full;
  state = false;

  private n = 0;

  constructor(private readonly logService: LogService) {}

  ngAfterContentChecked() {
    this.logService.log(String(this.n));
    this.n++;
  }
}

@Component({
  changeDetection: ChangeDetectionStrategy.OnPush,
  selector: 'container1',
  template: `
    <div class="block" afterContent="container1"><ng-content></ng-content></div>
  `,
})
export class Container1Component implements AfterContentChecked {
  constructor(private readonly logService: LogService) {}

  ngAfterContentChecked() {
    this.logService.log('<container1> ngAfterContentChecked()')
  }
}

@Component({
  selector: 'container2',
  template: `
    <div class="block" afterContent="container2"><ng-content></ng-content></div>
  `,
})
export class Container2Component implements AfterContentChecked {
  constructor(private readonly logService: LogService) {}

  ngAfterContentChecked() {
    this.logService.log('<component2> ngAfterContentChecked()')
  }
}

@Directive({ selector: '[afterContent]' })
export class AfterContentDirective implements AfterContentChecked {
  constructor(private readonly logService: LogService) {}

  @Input()
  afterContent: string;

  ngAfterContentChecked() {
    this.logService.log(`[afterContent] (${this.afterContent}) ngAfterContentChecked()`);
  }
}

@Component({
  selector: 'log',
  styles: [`
    .log:not(:first-child) {
      margin-top: 2px;
    }
    .log:not(:last-child) {
      margin-bottom: 2px;
    }
  `],
  template: `
    <button class="block" (click)="logService.clear()" type="button">Reset logs</button>
    <div class="block log" *ngFor="let log of logService.logs | async">{{ log }}</div>
  `,
})
export class LogComponent {
  constructor(readonly logService: LogService) {}
}

@NgModule({
  declarations: [
    AfterContentDirective,
    AppComponent,
    Container1Component,
    Container2Component,
    LogComponent,
  ],
  imports: [
    BrowserModule,
  ],
  bootstrap: [AppComponent],
  providers: [
    LogService,
  ],
})
export class AppModule { }
```

After toggling, the output is

```
0
<container1> ngAfterContentChecked()
<component2> ngAfterContentChecked()
[afterContent] (container1) ngAfterContentChecked()
[afterContent] (container2) ngAfterContentChecked()
1
<container1> ngAfterContentChecked()
<component2> ngAfterContentChecked()
[afterContent] (container2) ngAfterContentChecked()
2
<container1> ngAfterContentChecked()
<component2> ngAfterContentChecked()
[afterContent] (container2) ngAfterContentChecked()
3
<container1> ngAfterContentChecked()
<component2> ngAfterContentChecked()
[afterContent] (container2) ngAfterContentChecked()
```

## 🌍  Your Environment

**Angular Version:**

7.1.2

---

EDIT: Actually, this goes for ngAfterViewChecked() too.

**Comment by pauldraper** [comment] 2019-01-01 23:04
Actually, this goes for `ngAfterViewChecked()` too.

**Comment by mhevery** [comment] 2020-02-15 00:21
Ivy version with the same behavior as can be seen here: https://ng-run.com/edit/xomzUVRIWGyhsoXokLcW

I assume that the issue is that when `Toggle content` is clicked one would expect to see `[afterContent] (container1) ngAfterContentChecked()` printed. This does not happen because the `Container1Component` is `OnPush` and as a result we don't enter the `Container1Component` CD and hence to child lifecycle hooks get called.

I would argue that this works as intended.

**Comment by atscott** [comment] 2020-10-19 17:06
Per Misko's comment, closing as working as intended. https://github.com/angular/angular/issues/27877#issuecomment-586529713

**Closed by atscott** 2020-10-19 17:06 UTC
Labels: comp: core, core: lifecycle hooks, triage #1, type: confusing
