### ISSUE TITLE
Service worker 6.x does not work correctly in Edge and Samsung Internet on Android

### ISSUE THREAD

**Issue by dmostert** [angular/angular#20756] opened 2017-12-03 09:04 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

App with service worker loads fine the first time in Chrome 56 (And Edge Android, Samsung Internet). If you reload the page, the app fails with:

ERR_FAILED

`Uncaught (in promise) DOMException: Failed to execute 'waitUntil' on 'ExtendableEvent': The event handler is already finished.
    at Driver.handleFetch (http://127.0.0.1:8887/ngsw-worker.js:1941:15)
handleFetch @ ngsw-worker.js:1941
`

## Expected behavior

Service worker enabled sites should work correctly on Chrome 56, Edge and Samsung Internet browsers

## Minimal reproduction of the problem with instructions

ng new repro --service-worker
ng build --prod
Use Web server for Chrome or related to browse the dist folder.

## What is the motivation / use case for changing the behavior?

Service worker should work correctly on all supported browsers.

## Environment

<pre><code>
Angular CLI: 1.6.0-rc.1
Node: 8.9.1
OS: win32 x64
Angular: 5.0.5
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, service-worker

@angular/cli: 1.6.0-rc.1
@angular-devkit/build-optimizer: 0.0.34
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.38
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.0-rc.1
@schematics/angular: 0.1.8
typescript: 2.4.2
webpack: 3.8.1

Browser:
- [x] Chrome (desktop) version 56
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [x] Edge version  ANDROID 
 
For Tooling issues:
- Node version: v8.9.1  
- Platform:  Windows 

Others:

`
`
</code></pre>

**Comment by mlc-mlapis** [comment] 2017-12-03 09:38
@dmostert ... Chrome (desktop) version 56? How is using it? What about status for 62?

**Comment by dmostert** [comment] 2017-12-03 09:46
Edge browser on Android uses v58 and Samsung Browser on Android uses v56.

**Comment by mlc-mlapis** [comment] 2017-12-03 10:08
@dmostert ... sure but you mentioned that it is also 56 on desktop.

**Comment by dmostert** [comment] 2017-12-03 10:13
Yes - I used 56 on desktop as an easy way to reproduce the problem. Latest version of CHROME desktop and ANDROID works fine.

**Comment by mlc-mlapis** [comment] 2017-12-03 10:18
@dmostert ... and are you sure that it is not a problem with 56 right on the desktop? I think that it was early implementation of service worker on it so it is probably actually not relevant.

**Comment by dmostert** [comment] 2017-12-03 12:07
@mlc-mlapis  it might be, but current versions of Android's Samsung Internet & Edge USE older versions of Chrome and both of these browsers DON'T work...

**Comment by DominicBoettger** [comment] 2017-12-13 12:26
Did you already investigate in this issue?

**Comment by mcamendola** [comment] 2018-01-16 19:28
We are facing the same problem. We have opened another issue about the same problem on https://github.com/angular/angular/issues/21292.

**Comment by juliencap** [comment] 2018-01-31 14:00
Hello, I found some problem on latest version of Samsung Internet (6.2.01.12) and Angular5 service worker as described here. I have a strange behavior:
1- first access ok
2- refresh: "website unvailable" message

If I... delete cookies (and only cookies) on the website, and I refresh: it's ok, the app work... untill the next refresh.

So maybe it's linked.

And I didnt have a bug on previous Samsuns Internet version.

**Comment by a2345sooted** [comment] 2018-02-12 19:40
@juliencap any progress on this?  I'm running into this today.

Using chrome browser on an LG phone and angular service worker 5.2.4

**Comment by juliencap** [comment] 2018-02-12 20:21
Looking on my .angular-cli.json, I only moved the call on the service worker:
"serviceWorker": true

was before "environments" details, I move it after and sounds a little better but I am not sure, that's The reason.

Now I have:

```
      "environmentSource": "environments/environment.ts",
      "environments": {
        "dev": "environments/environment.ts",
        "prod": "environments/environment.prod.ts"
      },
      "serviceWorker": true
    },
```

I also noticed having the pwa open on severals softwares (Samsung Internet, Google Chrome and Twitter for example) at the same time, create again that behavior we described here. If I kill the other softwares (for example, closing Google Chrome and Twitter and keep it only on Samsung Internet), it work's better.

But I am still confuse with that: service worker are not yet supported on iPhone but the Pwa works good, 

Finally, I also had a good news on Facebook App on the Samsung phone I am using for tests: before the latest update of F. A, I had err_failed page on the app when I tryed to open a link on my PWA, now it's... OK.

**Comment by dottodot** [comment] 2018-02-20 15:59
I having the same issue with angular service worker 5.2.5 on **Samsung Internet Browser** and get the following error...

> Uncaught (in promise) InvalidStateError: Failed to execute 'waitUntil' on 'ExtendableEvent': The event handler is already finished.

and the site doesn't load properly. If I delete the service worker it then loads ok but on the next page refresh it's broken again.

Chrome and Firefox on the same phone work fine.

**Comment by thunderburger** [comment] 2018-03-03 01:15
Same (similar) problem here.

Angular CLI: 1.7.2
Angular: 5.2.7
Browser: Chrome 64

Same steps to reproduce as stated.

Navigating to site (http://localhost:8080) in Chrome 64 with F12 open.

It seems random whether the service worker will run as expected. In most cases everything loads fine at first request and the service worker is beting activated without any errors. Then after stopping the webserver - at first reload the page loads fine (no errors occurs in the service worker). Second reload causes 504 Gateway Timeout on localhost and (failed) net:ERR_CONNECTION_REFUSED (at ngsw-worker.js:2464)

But sometimes it works several times (reloading more than twice). It seems like a timing issue?

**Comment by juliencap** [comment] 2018-03-03 18:19
So we are not alone, that's the main thing here :)
I had some improvments ont Angular CLI 1.7.0 but just for a few days: no problem on navigation on my pwa website after also a little clean on dependencys version.

I also installed PM2 since. I can see the same errors I had on the nohupt.out document is missing... errors like that.

@thunderburger  probably timing issues yes or somthing more special. When I delete the cookie on my samsung device I see important datas in Mo when other websites are on Ko.

My only options now are to:
- clean dependencies versions on my app
- wait

Wait new version of Samsung Internet for example. Last time, a recent update of facebook fix the problem on my side (cf last comment).

**Comment by lishichao1002** [comment] 2018-03-15 05:20
+1

**Comment by Blejwi** [comment] 2018-03-22 10:34
Any updates on this issue? Do we know when it's gonna be fixed? I am still experiencing it on Chrome 59 and angular cli 1.7.3.

**Comment by rjwijnen** [comment] 2018-04-23 06:32
Experiencing the same with angular-cli: 1.7.4 and angular/serviceworker: 5.2.0

**Comment by JancoBH** [comment] 2018-04-27 20:40
Experiencing the same with angular-cli: 1.7.4 and angular/serviceworker: 5.2.10 on:

Mobile Safari UIWebView 7.1.2
Mobile Facebook browser 86.0.0
Chrome Mobile 37.0.0 with Android 5.0.1
Chrome Mobile 30.0.0 with Android 4.4.2

In these tested browsers and device the page never loads, any solution?.

**Comment by vleput** [comment] 2018-05-02 14:24
I've been trying to investigate this issue, as I have found no workaround yet other than disabling service workers in my app (which I want to avoid as much as possible)

Bug is present on both current Samsung Internet browser (6.4.10.5) and their beta (7.2.10.28), which are based respectively on Chromium 56.0.2924.87 and 59.0.3071.125

I have not experienced the bug on Edge Android (1.0.0.1921) which seems based on a more recent Chromium version (65.0.3325.109)

An example anyone can reproduce with the Angular Material docs site: https://material.angular.io, which uses `@angular/service-worker: 6.0.0-rc.5`:

On page load the error displayed by the service worker is:
`Uncaught (in promise) InvalidStateError: Failed to execute 'waitUntil' on 'ExtendableEvent': The event handler is already finished.
(ngsw-worker.js:1981)`
which comes from https://github.com/angular/angular/blob/master/packages/service-worker/worker/src/driver.ts#L407

Future navigations in the app trigger the same error coming from https://github.com/angular/angular/blob/master/packages/service-worker/worker/src/driver.ts#L399 this time:
`Uncaught (in promise) InvalidStateError: Failed to execute 'waitUntil' on 'ExtendableEvent': The event handler is already finished.
(ngsw-worker.js:1974)`

At this point I'm not sure whether this is a `@angular/service-worker` or Chromium issue?
I'll follow up if I find anything new, after I learn more about the logic behind service workers

**Comment by vleput** [comment] 2018-05-03 09:16
This all seems related to this Chromium bug fixed in v60: https://bugs.chromium.org/p/chromium/issues/detail?id=621440: could mean that any Angular app using Service workers will not work on browsers based on Chromium <60

I've tried the `event.waitUntil` polyfill mentioned in that issue (https://github.com/jakearchibald/async-waituntil-polyfill) and it solved the problem (tested on Samsung Internet 6 & 7 based on Chromium 56 & 59).

It's pretty hacky, but you can simply take the `{{host}}/ngsw-worker.js` file, add the polyfill in it, rename it to `ngsw-worker-polyfill.js` and place this file in `src`.
Then in `.angular-cli.json` under `assets` add:
```
{
  "glob": "ngsw-worker-polyfill.js",
  "input": "./",
  "output": "./"
}
```
This will export your custom worker file in `dist` when building your app.
Then in `app.module.ts` change the ServiceWorkerModule import so that it registers your polyfilled worker file instead of the one from `@angular/service-worker` package:
`ServiceWorkerModule.register('/ngsw-worker-polyfill.js', {enabled: environment.production})`

This is just a temporary fix, and in case you upgrade package versions you'll have to manually update this worker file with the latest code.

@alxhub Is adding this polyfill to the `@angular/service-worker` package something the Angular team would consider?

**Comment by gkalpak** [comment] 2018-05-03 14:31
Thx @vleput for getting to the bottom of this ❤️
I am not sure there is much point in including the polyfill by default (since it only affects old versions of Chromium), but maybe we could:

a. Distribute two versions of the worker script (one with and one without the polyfill) or
b. Make it possible to include extra scripts in the worker script via the cli (e.g. there could be a config option in `angular.json` to specify an extra script file (similar to `polyfills.ts` but for `ngsw-worker.js`).
    Or it could be a list of JS scripts to be imported (using `importScripts(...)`) at the top of `ngsw-worker.js`.

@alxhub, wdyt?

**Comment by juliencap** [comment] 2018-05-03 16:30
Thanks guys! works for me with @vleput version.
Good points with your investigations too @gkalpak (b. woul be great)

so we "just" have to wait some improvments now, but with a fix now.

**Comment by TheAppField** [comment] 2018-05-16 15:04
Same problem here:
@angular/cli: 1.7.4
@angular/service-worker: ^5.2.10
Samsung Internet:  Version 7.0.10.46

I wouldn't mind if the service worker just doesn't work on Chromium < 60. But crashing the whole app is a real deal breaker.

**Comment by juliencap** [comment] 2018-05-17 10:28
Hello guys,
I am trying the @vleput solution but I missed something because I have errors on my console.

If I am right, the solution is to:
- duplicate the dist/ngs-worker.js file to src/ngs-worker-pollyfilll.js with the [async-waitunti](https://github.com/jakearchibald/async-waituntil-polyfill/blob/master/async-waituntil.js)l pollyfill
-update the app.module.ts calling the new ngs-worker-pollyfilll.js
- update the angular-cli.json with the"glob": "ngsw-worker-polyfill.js"

But I dont find how exactly add the pollyfill on the new ngs-worker-pollyfilll.js: does I have to cc it at the top before _(function ()_ { or at the bottom, or inside?

And on angular-cli.json, does I have to add the new lines on the first assets mentions?

`{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "project": {
    "name": "portfolio"
  },
  "apps": [
    {
      "root": "src",
      "outDir": "dist",
      "assets": [
        "assets",
        "favicon.ico",
        "manifest.json",
        { "glob": "ngsw-worker-polyfill.js", "input": "./", "output": "./" }
      ],
      "index": "index.html",
      "main": "main.ts",`

If anyone can help me here please :)

**Comment by vleput** [comment] 2018-05-17 21:43
@juliencap 
1. Create a new `ngsw-worker-polyfill.js` file in `src` folder
2. Take the content of your `ngsw-worker.js` file in the `dist` folder, and copy-paste the polyfill at the beginning of function(): see exemple [here in this gist](https://gist.github.com/vleput/265075388c85ae9fa5903b94c37fefa7) 
3. Make ServiceWorkerModule register your polyfill worker instead of the regular worker in `app.module.ts`: `ServiceWorkerModule.register('/ngsw-worker-polyfill.js', {enabled: environment.production})`
4. It seems like you're using Angular 6.0.0 and the new version of the angular-cli.json file. `assets` is the right place, but the paths for input and output need to be slightly modified compared to 5.x.x:
```              
{
       "glob": "ngsw-worker-polyfill.js",
        "input": "src",
        "output": "/"
}
```

**Comment by juliencap** [comment] 2018-05-17 23:25
Thanks, I will continue on that tomorow!
On this project (I am using 5.2.10 and Angular CLI 1.7.4).

I have an error when I try to build the app (An asset cannot be written to a location outside the project.) but I will look tomorow, thanks again Vincent :)

**Comment by CharlBest** [comment] 2018-07-04 15:37
I agree with @TheAppField won't mind if it doesn't work but breaking the whole site it's cool. Just don't activate the service worker and load the site as normal. Please. :)

**Comment by hanyu-natsu** [comment] 2018-08-21 08:02
The problem persists in @angular/service-worker 6.1.2
Should change the issue title.

**Comment by cyraid** [comment] 2018-10-08 04:36
I'm also running into this.

**Comment by tayambamwanza** [comment] 2018-10-10 20:16
@dmostert, @bop10 , @cyraid It seems that this problem us gone in the latest beta of Samsung internet, seems the problem was the version of Chromium that they used.

**Comment by cyraid** [comment] 2018-10-10 22:20
Oh, yes I knew the new beta works, but that doesn't help us wanting to support the other devices. Since I wanted firebase messaging support, just register it with your own file like so:

`    ServiceWorkerModule.register("/sw.js")`

Then in sw.js:

```
try {
  importScripts("/ngsw-worker.js");
} catch (ex) {
} // Try, Catch //

// Firebase stuff //
```

Normally I'd just include ngsw-worker, and if it's in debug mode, it'll just raise an exception when it can't include the file (so I just catch it), and in production it'll include it when it's there.. Well, normally. Right now I just have it commented out until this bug is sorted out.

**Comment by nadhir-falta** [comment] 2018-10-27 22:08
Any update on this one :( this is a kill for SW and PWA really.

**Comment by juliencap** [comment] 2018-10-28 09:36
> Any update on this one :( this is a kill for SW and PWA really.

Hello, did you try https://github.com/angular/angular/issues/20756#issuecomment-386236004 ?

**Comment by hanyu-natsu** [comment] 2018-10-30 12:29
> > Any update on this one :( this is a kill for SW and PWA really.
> 
> Hello, did you try [#20756 (comment)](https://github.com/angular/angular/issues/20756#issuecomment-386236004) ?

The workaround is working, but the "polyfill" must be updated manually whenever there is an update of ngsw.

**Comment by cyraid** [comment] 2018-10-30 15:16
You could just include it with importScripts() using the idea I put in a comment above ^

**Comment by mariummalik22** [comment] 2018-11-27 00:32
> @juliencap
> 
> 1. Create a new `ngsw-worker-polyfill.js` file in `src` folder
> 2. Take the content of your `ngsw-worker.js` file in the `dist` folder, and copy-paste the polyfill at the beginning of function(): see exemple [here in this gist](https://gist.github.com/vleput/265075388c85ae9fa5903b94c37fefa7)
> 3. Make ServiceWorkerModule register your polyfill worker instead of the regular worker in `app.module.ts`: `ServiceWorkerModule.register('/ngsw-worker-polyfill.js', {enabled: environment.production})`
> 4. It seems like you're using Angular 6.0.0 and the new version of the angular-cli.json file. `assets` is the right place, but the paths for input and output need to be slightly modified compared to 5.x.x:
> 
> ```
> {
>        "glob": "ngsw-worker-polyfill.js",
>         "input": "src",
>         "output": "/"
> }
> ```

After making all these changes, what needs to be done?

**Comment by Mallfurion** [comment] 2019-01-17 16:16
@alxhub any updates regarding this issue?

**Comment by dottodot** [comment] 2019-02-06 10:56
Is this likely to ever be fixed or do I need to find a different way to add a service worker, I'd like to be able to add a service worker to my site but it's not possible if it breaks the site on some browsers.

**Comment by shabbir-dhangot** [comment] 2019-02-23 10:27
Not working with latest UC browser

**Comment by werts** [comment] 2019-05-30 02:49
Anything new about this issue?

**Comment by LoucaIasoni** [comment] 2019-06-26 15:40
Any updates?

**Comment by alxhub** [comment] 2020-01-23 22:03
@gkalpak this looks like something we should take on. Maybe ship our own version of the polyfill?

**Comment by andreialecu** [comment] 2020-04-06 16:37
I can also confirm seeing this on LG TV WebOS models before 2020 which use Chromium 53.

Web pages using service worker are completely broken on the TV because of it.

**Comment by gkalpak** [comment] 2020-05-25 17:59
To recap (for future reference):

- This is caused by missing features in order versions of some browsers (e.g. older versions of Chrome, Edge, Samsung Internet, etc.).
- The workaround is to enhance the ServiceWorker script with some polyfill, but doing so is not very straight forward for `@angular/service-worker`.
- The problem and the workaround are explained in more detail in https://github.com/angular/angular/issues/20756#issuecomment-386236004.

If anyone wants to take it on, the possible fixes are:
- Make it possible/easy to include extra scripts in the worker script via the cli; e.g. there could be a config option in `angular.json` to specify an extra script file (similar to `polyfills.ts` but for `ngsw-worker.js`).
    Or it could be a list of JS scripts to be imported (using `importScripts(...)`) at the top of `ngsw-worker.js`.
  - **PROS:** Flexible. Only those who need it pay the extra size cost.
  - **CONS:** Still requires some work from the developer. Not very easy to discover the problem/fix.
- Embed our own version of the polyfill in the `ngsw-worker.js` script.
  - **PROS:** Works automatically.
  - **CONS:** Everyone pays the extra size cost (even if they don't need the polyfill).

**Comment by sebaherrera** [comment] 2020-07-16 01:32
Hi. Isn't the service worker regenerated at build time? If so, you might be able to add/remove the polyfill based on browserslist file.

**Comment by nutza249949** [comment] 2020-09-10 16:49
o

**Comment by jelbourn** [comment] 2021-04-06 20:48
Closing this since it's been long enough that newer versions of Edge and Samsung Internet are based on Chromium 60+ which shouldn't have the issue any longer

**Closed by jelbourn** 2021-04-06 20:48 UTC
Labels: P4, comp: service-worker, freq2: medium, help wanted, state: confirmed, triage #1, type: bug/fix, workaround2: non-obvious
