### ISSUE TITLE
Data bound value in radio button breaks in Chrome

### ISSUE THREAD

**Issue by Nalha** [angular/angular#10725] opened 2016-08-12 08:53 UTC
[ X ] bug report

**Current behavior**
When using radio buttons with a bound value with either [value]="myString" or value="{{myString}}" and click it multiple times in Chrome the ngModel switches between "on" and the actual bound value.

**Expected/desired behavior**
Clicking the same radio button multiple times shouldn't change value or change to same each time.

**Reproduction of the problem**
`<input type="radio" [value]="myString" [(ngModel)]="myModel" name="my-radio-button">`

* **Angular version:**
2.0.0-rc.5
 
* **Browser:** 
Only observed in Chrome 52.0.2743.116 (64-bit)
Works fine in Firefox 48.0
 
* **Language:** 
Typescript 1.8.10

**Comment by kara** [comment] 2016-08-12 17:45
Can you tell me a bit more about your use case?  It's not supported to bind to the `value` property directly if you're using `ngModel` because `ngModel` writes to the value internally and they will be in conflict.  If you want to initialize a value, why not just write to `myModel` in your component class?    A plunker with your use case would be helpful.

**Comment by Nalha** [comment] 2016-08-15 07:14
Then how are we supposed to create radio buttons through a ngFor?

`<div class="radio" *ngFor="let address of user.addresses">
                            <label>
                                <input type="radio" [value]="address" [(ngModel)]="selectedAddress" name="address-radio-buttons">
                                <span>{{ address }}</span>
                            </label>
                        </div>`

**Comment by kara** [comment] 2016-08-16 00:24
Ack, totally misread this (admittedly well-labeled) issue.  I was talking about text inputs.  For radio buttons, you should be able to bind both.  What exactly is happening when you click the radio button multiple times?  I created a plunker for you, but it seems to work as intended:

http://plnkr.co/edit/2KfCiQ5ecGtyZRSWY33R?p=preview

What are you doing differently?  An example plunker would expedite this.

**Comment by Nalha** [comment] 2016-08-16 07:39
Hmm running your example on plunkr it works fine but if i copy that exact same code into our project it breaks, I wonder if some other package is interfering with our code.

Are there any potential issues with any of these?

```
"dependencies": {
    "@angular/common": "2.0.0-rc.5",
    "@angular/compiler": "2.0.0-rc.5",
    "@angular/core": "2.0.0-rc.5",
    "@angular/forms": "0.3.0",
    "@angular/http": "2.0.0-rc.5",
    "@angular/platform-browser": "2.0.0-rc.5",
    "@angular/platform-browser-dynamic": "2.0.0-rc.5",
    "@angular/platform-server": "2.0.0-rc.5",
    "@angular/router": "3.0.0-rc.1",
    "angular2-datatable": "^0.4.2",
    "angular2-uuid": "^1.0.7",
    "aws-sdk": "^2.5.0",
    "bootstrap": "^3.3.6",
    "core-js": "^2.4.0",
    "ie-shim": "^0.1.0",
    "jwt-decode": "^2.0.1",
    "lodash": "^4.15.0",
    "ng2-bootstrap": "1.0.24",
    "ng2-file-upload": "^1.0.3",
    "ng2-radio-group": "0.0.6",
    "rxjs": "5.0.0-beta.6",
    "zone.js": "~0.6.12"
  },
  "devDependencies": {
    "@angularclass/angular2-beta-to-rc-alias": "~0.1.0",
    "angular2-hmr": "~0.8.0",
    "awesome-typescript-loader": "^1.1.1",
    "codelyzer": "^0.0.28",
    "copy-webpack-plugin": "^3.0.1",
    "css-loader": "^0.23.1",
    "es6-promise-loader": "^1.0.1",
    "exports-loader": "^0.6.3",
    "expose-loader": "^0.7.1",
    "file-loader": "^0.9.0",
    "gh-pages": "^0.11.0",
    "html-webpack-plugin": "^2.21.0",
    "http-server": "^0.9.0",
    "imports-loader": "^0.6.5",
    "istanbul-instrumenter-loader": "^0.2.0",
    "json-loader": "^0.5.4",
    "karma": "^1.2.0",
    "karma-chrome-launcher": "^1.0.1",
    "karma-cli": "^1.0.1",
    "karma-coverage": "^1.0.0",
    "karma-jasmine": "^1.0.2",
    "karma-mocha-reporter": "^2.0.0",
    "karma-phantomjs-launcher": "^1.0.0",
    "karma-sourcemap-loader": "^0.3.7",
    "karma-webpack": "^1.8.0",
    "node-sass": "^3.8.0",
    "pact-consumer-js-dsl": "0.2.2",
    "parse5": "^2.2.0",
    "phantomjs-polyfill": "0.0.2",
    "phantomjs-prebuilt": "^2.1.12",
    "protractor": "^4.0.3",
    "raw-loader": "0.5.1",
    "remap-istanbul": "^0.6.3",
    "rimraf": "^2.5.2",
    "sass-loader": "^4.0.0",
    "source-map-loader": "^0.1.5",
    "style-loader": "^0.13.1",
    "to-string-loader": "^1.1.4",
    "ts-helpers": "1.1.1",
    "ts-node": "^1.2.2",
    "tslint": "3.9.0",
    "tslint-loader": "^2.1.5",
    "typedoc": "^0.4.3",
    "typescript": "~1.8.10",
    "typings": "~1.3.0",
    "url-loader": "^0.5.7",
    "webpack": "^1.13.1",
    "webpack-dev-server": "^1.14.1",
    "webpack-md5-hash": "^0.0.5",
    "webpack-merge": "^0.14.0"
  },
```

**Comment by pkozlowski-opensource** [comment] 2016-08-17 21:10
> Are there any potential issues with any of these

Impossible to say just by looking at the list of projects. Try to take them out one by one till it works. 

Anyway, I don't think there is anything to fix on the Angular side so closing this one.

**Closed by pkozlowski-opensource** 2016-08-17 21:10 UTC
Labels: comp: forms, flag: can be closed?
