### ISSUE TITLE
LoadChildrenCallback Typescript Error when arrow function specifier async

### ISSUE THREAD

**Issue by Delagen** [angular/angular#46697] opened 2022-07-04 13:05 UTC
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

Yes

### Description

```
Type '() => Promise<Type<any> | Routes | NgModuleFactory<any> | Observable<Type<any> | Routes> | typeof LoginRouting>' is not assignable to type 'LoadChildrenCallback'.
  Type 'Promise<Type<any> | Routes | NgModuleFactory<any> | Observable<Type<any> | Routes> | typeof LoginRouting>' is not assignable to type 'Type<any> | Routes | NgModuleFactory<any> | Observable<Type<any> | Routes> | Promise<Type<any> | Routes | NgModuleFactory<...>>'.     
    Type 'Promise<Type<any> | Routes | NgModuleFactory<any> | Observable<Type<any> | Routes> | typeof LoginRouting>' is not assignable to type 'Promise<Type<any> | Routes | NgModuleFactory<any>>'.
      Type 'Type<any> | Routes | NgModuleFactory<any> | Observable<Type<any> | Routes> | typeof LoginRouting' is not assignable to type 'Type<any> | Routes | NgModuleFactory<any>'.
        Type 'Observable<Type<any> | Routes>' is not assignable to type 'Type<any> | Routes | NgModuleFactory<any>'.
```

### Please provide the exception or error you saw

```true
loadChildren: async () => import('./path/to/module')
                    .then(mod => mod.NgModule)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
AngularCli: 14.0.x
```

### Anything else?

Worked fine till 14 version

**Comment by JoostK** [comment] 2022-07-04 13:15
Your async function seems to return a value of type `Type<any> | Routes | NgModuleFactory<any> | Observable<Type<any> | Routes> | typeof LoginRouting`, which is indeed incompatible with `LoadChildrenCallback`, so the error seems legit. Please provide  a reproduction so it becomes more clear where the issue is.

**Comment by Delagen** [comment] 2022-07-04 13:27
@JoostK LoginRouting is NgModule so it looks normal typing resolve

**Comment by Delagen** [comment] 2022-07-04 13:46
@JoostK https://stackblitz.com/edit/angular-ivy-jefihz

**Comment by JoostK** [comment] 2022-07-04 14:13
This seems like a TypeScript bug to me:

1. removing the `async` modifier avoids the error
2. Assigning the arrow function to a variable and then assigning that variable to `loadChildren` avoids the error. So the contextual type from `loadChildren` affects the inferred return type of the arrow function, whereas I'd expect it to be inferred from the arrow's expression type.

Might be related to https://github.com/microsoft/TypeScript/pull/49748

**Comment by mlc-mlapis** [comment] 2022-07-04 14:27
@Delagen If using the `async` modifier, the shorter version also doesn't show the error.
```
loadChildren: async () => (await import('./route-module/route-module.module')).RouteModuleModule
```

**Comment by JoostK** [comment] 2022-07-04 19:04
This is indeed a known TypeScript bug: https://github.com/microsoft/TypeScript/issues/47682. Since there several ways to workaround this issue I'm going to close this, as it's not otherwise actionable for us.

**Closed by JoostK** 2022-07-04 19:04 UTC
Labels: comp: router, cross-cutting: types, state: needs more investigation
