### ISSUE TITLE
Respect locale in default pipes

### ISSUE THREAD

**Issue by mbeckenbach** [angular/angular#14055] opened 2017-01-22 16:34 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] feature request
```

**Current behavior**
Number, date and currency formats are incorrect for germany

**Expected behavior**
Number, date and currency pipes should respect browser locale by default

Examples:
German date format: dd.MM.yyyy hh:mm:ss
German number format: 1.000,00 (Dot separates thousends, comma for decimal places)
German curreny format: 1.000,00 € or EUR 1.000,00 (Note the number format and currency symbol placing)

**Minimal reproduction of the problem with instructions**
Use any of the pipes in a german application

**What is the motivation / use case for changing the behavior?**
The wrong format forces us to replace the pipes in every application

**Please tell us about your environment:**
ng 2.3.1
webstorm
ng cli

* **Angular version:** 2.0.X
2.3.1

* **Browser:** 
all
 
* **Language:**
typescript

* **Node (for AoT issues):** `node --version` =

**Comment by pkozlowski-opensource** [comment] 2017-01-22 17:34
Please add a minimal plunker reproducing problematic formats + inputs.

**Comment by pkozlowski-opensource** [comment] 2017-01-22 17:36
Note: most of the i18n logic comes from the Intl API built in into browsers so I would be really uneasy about the fact that it is broken across browsers for such fundamental use-cases. We really need a reproduce scenario to confirm and act here.

**Comment by mbeckenbach** [comment] 2017-01-23 08:45
As long as you don't specify a locale manually in the modules providers this issue is in every blank ng2 application. So there is no need for a plunker,

providers: [{provide: LOCALE_ID, useValue: 'de-DE'}]

The issue exists for every user in germany on every browser as ng2 simply does not use the browser locale to format numbers and dates. It uses the en-US locale by default.

**Comment by pkozlowski-opensource** [comment] 2017-02-01 10:29
> As long as you don't specify a locale manually in the modules providers this issue is in every blank ng2 application. So there is no need for a plunker,

Well, I would still argue that a plunker is useful for the reasons enumerated [here](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue)

> The issue exists for every user in germany on every browser 

What do you mean be "every user in germany"? Users accessing ng2 applications from Germany? Users having a browser in German language? 

I think there is a misunderstanding here - as of today Angular takes _default_ locale from the `LOCALE_ID` provider. It does _not_ switch locale based on users location (this would require Angular to try to second-guess it) nor browsers settings.

As of today you need to specify locale exactly as you've commented:

```javascript
providers: [{provide: LOCALE_ID, useValue: 'de-DE'}]
```

Angular can't (and should not) know from which country a user is accessing an application or which browse she is using. If you want to have more sophisticated locale resolution you can provide custom logic on the application side:

```javascript
providers: [{provide: LOCALE_ID, useFactory: () => {
  // return locale ISO code based on logic of your choice
}}]
```

I'm going to close this issue as I believe that there is misunderstanding here and hopefully the above explanation help clarify things. Feel free to provide more info in plunker if you still believe that there is a bug or a missing feature in Angular.

**Closed by pkozlowski-opensource** 2017-02-01 10:29 UTC
Labels: comp: common, comp: i18n, state: Need repro
