### ISSUE TITLE
Router navigation triggered twice after manual change in browser URL

### ISSUE THREAD

**Issue by etiennecrb** [angular/angular#18366] opened 2017-07-27 08:42 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Consider two routes with a master / detail pattern like `/crisis-center` and `/crisis-center/:id`.
```typescript
const crisisCenterRoutes: Routes = [
  {
    path: '',
    component: CrisisCenterComponent,
    children: [
      {
        path: '',
        component: CrisisListComponent,
        children: [
          {
            path: ':id',
            component: CrisisDetailComponent,
            canDeactivate: [CanDeactivateGuard],
            resolve: {
              crisis: CrisisDetailResolver
            }
          },
          {
            path: '',
            component: CrisisCenterHomeComponent
          }
        ]
      }
    ]
  }
];
```  
You might want to redirect the master path to a particular `id`. This can be done in `CrisisCenterHomeComponent`, like so:

```typescript
@Component({
  template: `
    <p>Welcome to the Crisis Center</p>
  `
})
export class CrisisCenterHomeComponent {
  constructor(private route: ActivatedRoute, private router: Router) {
    this.router.navigate([1], {relativeTo: this.route});
  }
}
```

Or with a `CanActivate` guard:

```typescript
@Injectable()
export class RedirectionGuard implements CanActivate {
  
  constructor(private router: Router) { }
  
  canActivate() {
    this.router.navigate(['/crisis-center', 1]);
    return false;
  }
}
```
Both solution work but **when changing the URL manually in the browser URL bar**, router triggers two navigation events:

![capture du 2017-07-27 09-49-46](https://user-images.githubusercontent.com/12871063/28661270-66dc9920-72b6-11e7-9f0c-bb494ae52646.png)

## Expected behavior

Router should trigger only one navigation event, as it does when navigating _programmatically_ (meaning not changing manually the URL).

## Minimal reproduction of the problem with instructions

[Demo with component redirection](https://plnkr.co/edit/GKZP1v30IUgQYfa41qZD?p=preview)
[Demo with guard redirection](https://plnkr.co/edit/cWlG7dYK8OpjU3IGT17X?p=preview)

Steps to reproduce:

- Open one of the plunker above
- Launch preview in a separated window to be able to change manually the URL
- Click on item 2 of crisis list
- Open console and clear its ouput
- Change URL directly in the browser bar to go '/crisis-center/'
- Check the console output and the multiple "Navigation start" event to '/crisis-center/' even after first redirection
- Repeat the test but instead of changing the URL, click on "Go To Crisis Center Home" link above the list to see that it's working when navigating programmatically

## What is the motivation / use case for changing the behavior?

I described a very simple example of the bug but I have currently a use case where this behaviour is very difficult to deal with, for a quite simple feature.

## Environment

<pre><code>
Angular version: 4.3.1

Browser:
- [x] Chrome (desktop) version 60
 
For Tooling issues:
- Node version: v6.11.1  
- Platform:  Linux
</code></pre>

**Comment by IAMtheIAM** [comment] 2017-10-12 19:48
No activity or solution in months? This bug still exists

**Comment by silentHoo** [comment] 2017-11-30 08:37
No progress here? Having the same problem.

**Comment by jasonaden** [comment] 2017-12-07 22:12
Closing this as a duplicate of #16710. Prioritizing that issue so it can be looked into ASAP.

**Closed by jasonaden** 2017-12-07 22:12 UTC
Labels: comp: router, type: bug
