### ISSUE TITLE
Angular 4 template can not access static property.

### ISSUE THREAD

**Issue by mmc41** [angular/angular#15487] opened 2017-03-25 18:44 UTC
**I'm submitting a ...**  (check one with "x")

[x ] bug report => search github for a similar issue or PR before submitting

**Current behavior**
A template that refers to a static property of the component class from formGroup as below fails with "formGroup expects a FormGroup instance. Please pass one in" in Angular 4. Works if the property is a non-static instance member.
 
```
<div [formGroup]="metaFormGroup">
          ...
</div>

export class TestHostComponent implements OnInit {
  public static readonly metaFormGroup: FormGroup = new FormGroup({
    ...
  });
 ...
};
```

**Expected behavior**
The template should be able to refer to static members of a component, just like it can refer to instance members.

**Please tell us about your environment:**

* **Angular version:** 4.0.0

* **Browser:**  Chrome
 
* **Language:** Typescript 2.2.1

* **Node (for AoT issues):** `node --version` =   7.6

**Comment by DzmitryShylovich** [comment] 2017-03-25 18:56
http://plnkr.co/edit/s89N1pjKtYbjjYBWYjPC?p=preview

**Comment by mmc41** [comment] 2017-03-25 19:49
Yes, I can see it works in your example but your example. Not sure why it does not in mine. Yours is slightly different. Mine uses formGroup.

**Comment by Toxicable** [comment] 2017-03-25 19:52
@mmc41 {{constructor.group.value | json}}

**Comment by mmc41** [comment] 2017-03-25 20:17
Not sure what is wrong then based on the examples. But the following workaround does work in my case, which is to add an instance property as alias to the static one:
```
  public get metaFormGroup(): FormGroup {
    return TestHostComponent.metaFormGroup;
  }
```

**Comment by trotyl** [comment] 2018-02-19 08:50
Duplicate of #9962

**Comment by wbhob** [comment] 2018-07-08 18:13
@mmc41 if this issue is a duplicate, can you close it please

**Comment by pkozlowski-opensource** [comment] 2018-07-08 19:46
Closing as a duplicate of #9962

**Closed by pkozlowski-opensource** 2018-07-08 19:46 UTC
Labels: comp: core & compiler, freq1: low, severity2: inconvenient, type: feature
