### ISSUE TITLE
Angular 11 and GoogleBot

### ISSUE THREAD

**Issue by davyvanlaere** [angular/angular#40283] opened 2020-12-30 21:30 UTC
Angular 11 is, out of the box, not indexable by GoogleBot ... 
I have few websites (on older angular versions) running that are perfectly indexed by GoogleBot, and that actually have good indexing and search performance. A new Angular 11 application will simply return 404 in the "Test live url" utility of Google Search Console. 

Result page in search console:
https://photos.app.goo.gl/eg2doJdMuhZioiMr8

The page at "/" IS indexable, but any other route fails ...

Could this be related to polyfills? 

Things i already tried: 
- static module loading instead of lazy loading for route
- removing pwa/service workers

I am now going to try and get client-side error logging in, to see if any errors are raised when googlebot visits.

**Comment by jnizet** [comment] 2020-12-31 09:32
The problem is on your server. A request to https://www.free-sudoku-puzzle.net/techniques/locked-candidate-claiming is responded by your server with a 301 response redirecting to https://www.free-sudoku-puzzle.net/techniques/locked-candidate-claiming/. And when sending a request to that URL, we do get a 404 response:

```
> http https://www.free-sudoku-puzzle.net/techniques/locked-candidate-claiming
HTTP/1.1 301 Moved Permanently
Connection: keep-alive
Content-Length: 0
Content-Type: application/xml
Date: Thu, 31 Dec 2020 09:29:18 GMT
Location: /techniques/locked-candidate-claiming/
Server: AmazonS3
Via: 1.1 32ceb5729c4d415c2eb5bbab5ff21b8f.cloudfront.net (CloudFront)
X-Amz-Cf-Id: LlJ1-vfkAzYv1ZyCxON-dx_O8wGbRRteiTUPlsQQgnpOvL8Z1RV6yg==
X-Amz-Cf-Pop: CDG3-C2
X-Cache: Miss from cloudfront

> http https://www.free-sudoku-puzzle.net/techniques/locked-candidate-claiming/
HTTP/1.1 404 Not Found
Connection: keep-alive
Content-Encoding: gzip
Content-Type: text/html
Date: Thu, 31 Dec 2020 09:29:21 GMT
Server: AmazonS3
Transfer-Encoding: chunked
Vary: Accept-Encoding
Via: 1.1 ef7ace463c0659c94b8e007b4dc9ae9b.cloudfront.net (CloudFront)
X-Amz-Cf-Id: W0W92AXu1fJbWRKMZSFqKqPSm7yp8z0-0Guw6R9ZXy4TnEB835FU8A==
X-Amz-Cf-Pop: CDG3-C2
X-Cache: Error from cloudfront


<!doctype html>
<html lang="en">
<head>
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async="" src="https://www.googletagmanager.com/gtag/js?id=UA-12791807-4"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
    gtag('config', 'UA-12791807-4');
    gtag('config', 'G-5YZP1HF0LX');
  </script>
  <meta charset="utf-8">
  <title>Free Sudoku Puzzle</title>
  <meta name="description" content="Play free sudoku puzzles from easy to expert. Use the help function will guide you in learning the more advanced techniques.">
  <meta name="keywords" content="sudoku puzzle easy medium hard expert help hidden naked single subsets locked candidates pointing claiming simple coloring x-wing y-wing">
  <meta property="og:url" content="https://www.free-sudoku-puzzle.net"/>
  <meta property="og:type" content="website"/>
  <meta property="og:title" content="Free Sudoku Puzzle"/>
  <meta property="og:description" content="Play free sudoku puzzles ranging from easy to expert. For beginners, the help function will help you become an expert!"/>
  <base href="/">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
  <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
  <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
  <link rel="manifest" href="manifest.webmanifest">
  <meta name="theme-color" content="#1976d2">
<link rel="stylesheet" href="styles.0409eca5853f1732f0ab.css"></head>
<body>
  <script>
    window.fbAsyncInit = function() {
      FB.init({
        appId      : '396714551468766',
        xfbml      : true,
        version    : 'v9.0'
      });
      FB.AppEvents.logPageView();
    };
  </script>
  <script async="" defer="" crossorigin="anonymous" src="https://connect.facebook.net/en_US/sdk.js"></script>
  <app-root></app-root>
  <noscript>Please enable JavaScript to continue using this application.</noscript>
<script src="runtime.2e034182f206cf65ad54.js" defer></script><script src="polyfills.c2ba9a12c1045e0d4814.js" defer></script><script src="main.2697f35f7e271bcf08ec.js" defer></script></body>
</html>

```

**Comment by davyvanlaere** [comment] 2020-12-31 09:40
This is really confusing ... when i do the call in postman, the call just fetches the proper index.html body, but the http code is 404.

Maybe i should be looking at the hosting side (AWS Amplify) instead of the angular code.

**Comment by davyvanlaere** [comment] 2020-12-31 09:44
Where did you see the 301 response? Not seeing this in postman ...

**Comment by jnizet** [comment] 2020-12-31 09:46
Using the [`http`](https://httpie.io/) command (HttpPie, which is an alternative to curl); or simply by opening the network tab of the browser dev tools.

**Comment by davyvanlaere** [comment] 2020-12-31 09:53
The network tab just shows 200, hence the confusion. Anyway, thank you for pointing this out, i was getting quite stuck here ;)

**Comment by jnizet** [comment] 2020-12-31 10:12
<img width="1014" alt="Capture d’écran 2020-12-31 à 11 11 27" src="https://user-images.githubusercontent.com/1608223/103405856-fbe18c00-4b58-11eb-8d82-3c3b69bdb4dc.png">

**Comment by davyvanlaere** [comment] 2020-12-31 10:46
Odd, i am unable to reproduce this behavior in chrome ...

Caffeine epiphany: i am used to running my angular apps on asp.net apps which have a catch-all route serving index.html. I can probably fix this using the rewrite rules in amplify.

**Comment by davyvanlaere** [comment] 2020-12-31 10:54
Fixed ...
![image](https://user-images.githubusercontent.com/11078317/103407444-fdae4e00-4b5e-11eb-9571-a1a919950542.png)

**Comment by petebacondarwin** [comment] 2020-12-31 11:08
I'm glad you have resolved your issue @davyvanlaere - I am going to close this issue as there is not a problem with Angular itself.

**Closed by petebacondarwin** 2020-12-31 11:08 UTC
