### ISSUE TITLE
Add native support to file input and multipart/form-data

### ISSUE THREAD

**Issue by apiweb** [angular/angular#15441] opened 2017-03-24 01:30 UTC
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Currently Angular does not have native support, so when we have a form that has an Input = File, we have to implement customizations so that when sending the form, the file is also sent via multipart/form-data.
There are some code examples, such as:
[angular2-multipartForm](https://github.com/wangzilong/angular2-multipartForm)
But these libraries do not integrate very well with the Angular.

**Expected behavior**
It would be very interesting if in future versions Angular had native support for "input=file"  and multipart/form-data.
Adding compatibility with [File API](http://www.w3.org/TR/FileAPI/).
This would make it much easier for developers who want to implement this type of field in their application forms.
There are some libraries for this, such as: [angular2-multipartForm](https://github.com/wangzilong/angular2-multipartForm), [ng2-file-upload](https://github.com/valor-software/ng2-file-upload)
However, they do not implement very well, or are not updated or break the good practices of the Angular.

**Please tell us about your environment:**

* **Angular version:** 4.0

* **Browser:** all 
 
* **Language:** all

* **Node (for AoT issues):** `node --version` =   6.10

**Comment by Toxicable** [comment] 2017-03-24 01:40
You can access a files through `nativeElement` like so https://plnkr.co/edit/eB1CiS87hSmxEnDKZMwv?p=preview
and upload them with `FormData`

**Comment by DzmitryShylovich** [comment] 2017-03-24 06:37
Duplicate of https://github.com/angular/angular/issues/7341

**Comment by kara** [comment] 2017-08-12 00:29
Closing as a duplicate of #7341

**Closed by kara** 2017-08-12 00:29 UTC
Labels: comp: forms, type: feature
