### ISSUE TITLE
Hyperlink in Angular.dev Tutorial - Page not found

### ISSUE THREAD

**Issue by itsmattwagner** [angular/angular#53738] opened 2024-01-01 14:28 UTC
### Describe the problem that you experienced

[type inference in TypeScript](https://angular.dev/typescript.org/type-inference) leads to "Page not found".

On the tutorial page: https://angular.dev/tutorials/learn-angular/updating-the-component-class in the first paragraph:
[Add a property called city](https://angular.dev/tutorials/learn-angular/updating-the-component-class#add-a-property-called-city)
Update the component class by adding a property called city to the AppComponent class.

export class AppComponent {
  city = 'San Francisco';
}
check
The city property is of type string but you can omit the type because of [type inference in TypeScript](https://angular.dev/typescript.org/type-inference). The city property can be used in the AppComponent class and can be referenced in the component template.

To use a class property in a template, you have to use the {{ }} syntax.

### Enter the URL of the topic with the problem

https://angular.dev/tutorials/learn-angular/updating-the-component-class

### Describe what you were looking for in the documentation

Working link for the explanation of type inference in TypeScript.

### Describe the actions that led you to experience the problem

Clicking on the provided link.

### Describe what you want to experience that would fix the problem

A link that leads to an explanation of type inference in TypeScript.

### Add a screenshot if that helps illustrate the problem

![image](https://github.com/angular/angular/assets/94354480/2e56413e-b679-4bfa-901d-53e5a9eef248)

### If the problem is browser-specific, please specify the device, OS, browser, and version

```true
I use Chrome.
```

**Comment by JoostK** [comment] 2024-01-01 14:44
Thanks for the report, this is a duplicate of https://github.com/angular/angular/issues/52553 for which the fix is pending deployment.

**Closed by JoostK** 2024-01-01 14:44 UTC
