### ISSUE TITLE
HttpClient - HttpErrorResponse not json but blob

### ISSUE THREAD

**Issue by codefactorydevelopment** [angular/angular#19888] opened 2017-10-24 07:26 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

Not sure if its a bug or intended behavior so can't check bug although it seems like one.

## Current behavior

I am sending http request like this:

```
return this.http.get(url, {
      observe:'response',
      headers: headers,
      responseType:'blob'
    })
```
Server responds by `400 Bad Request`, `application/json` `content-type` header and in body it returns json object:
```
{
  message: "some error message"
}
```

`error` property on `HttpErrorResponse` is of type `Blob`.

## Expected behavior

I would expect `HttpErrorResponse.error` property to be `json` according to `content-type` server returned since documentation says:

> The error property will contain either a wrapped Error object or the error response returned from the server.
ref: https://angular.io/api/common/http/HttpErrorResponse

So, if it puts server returned body into `HttpErrorResponse.error` then it feels like it should obey servers `content-type` header describing that same `body`.

## Minimal reproduction of the problem with instructions

Use request above.

## Environment

<pre><code>
@angular/cli: 1.4.2
node: 6.9.3
os: win32 x64
@angular/animations: 4.4.6
@angular/common: 4.4.6
@angular/compiler: 4.4.6
@angular/core: 4.4.6
@angular/forms: 4.4.6
@angular/http: 4.4.6
@angular/platform-browser: 4.4.6
@angular/platform-browser-dynamic: 4.4.6
@angular/router: 4.4.6
@angular/cli: 1.4.2
@angular/compiler-cli: 4.4.6
@angular/language-service: 4.4.6
typescript: 2.3.4

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by alxhub** [comment] 2017-10-25 20:08
> So, if it puts server returned body into `HttpErrorResponse.error` then it feels like it should obey servers `content-type` header describing that same `body`.

I really like this idea. Since `HttpErrorResponse.error` is typed as `any` already, it makes sense that it would depend on the server's `Content-Type` for the response.

I'll look into implementing this.

**Comment by JaapMosselman** [comment] 2017-12-05 13:55
Is there for now a simple workaround to get the json from the blob?

**Comment by codefactorydevelopment** [comment] 2017-12-05 17:55
You can read blob as text and then convert it to json.

**Comment by JaapMosselman** [comment] 2017-12-06 14:11
I created this interceptor as a temporary solution until this one is fixed:

```
@Injectable()
export class BlobErrorHttpInterceptor implements HttpInterceptor {
    public intercept(req: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
        return next.handle(req).pipe(
            catchError(err => {
                if (err instanceof HttpErrorResponse && err.error instanceof Blob && err.error.type === "application/json") {
                    // https://github.com/angular/angular/issues/19888
                    // When request of type Blob, the error is also in Blob instead of object of the json data
                    return new Promise<any>((resolve, reject) => {
                        let reader = new FileReader();
                        reader.onload = (e: Event) => {
                            try {
                                const errmsg = JSON.parse((<any>e.target).result);
                                reject(new HttpErrorResponse({
                                    error: errmsg,
                                    headers: err.headers,
                                    status: err.status,
                                    statusText: err.statusText,
                                    url: err.url
                                }));
                            } catch (e) {
                                console.log(e);
                                reject(err);
                            }
                        };
                        reader.onerror = (e) => {
                            console.log(e);
                            reject(err);
                        };
                        reader.readAsText(err.error);
                    });
                }
                return _throw(err);
            })
        );
    }
}
```

**Comment by edallagnol** [comment] 2017-12-07 20:33
I think this is a bug, not a feature. When you do a JSON request, and the server returns 400 with a "text/plain" content-type header, the HttpErrorResponse.error is a string, as expected. This behavior should not be different in a blob request.

**Comment by mattfors** [comment] 2018-01-10 22:03
Here's what I did to handle json errors with a blob response type:<br/>
```
  private handleError(err: HttpErrorResponse): void {
    if ('application/json' === err.headers.get('Content-Type')) {
      const reader = new FileReader();
      reader.addEventListener('loadend', (e) => {
        console.log(JSON.parse(e.srcElement['result']));
      });
      reader.readAsText(err.error);
    } else {
      console.log('not json');
    }
  }
```

**Comment by Bil0** [comment] 2018-02-24 09:24
Hello,

The same problem with all `responType !== 'json'` whether it is `text`, `blob` or `arraybuffer`.

For example: 
```taypescript
    return this.http
      .get(URL, { observe: 'response', responseType: 'arraybuffer', params })
      .pipe(
       ...
```
In my case I've a `401 Unthorized` as response status, the response body will be casted to the requested `responseType`  (an `ArrayBeffer`) so my `RefreshToken` interceptor is wating for an object (json) but got an `arrayBeffer` instead.

As a workaround in my interceptor:
```typescript
    let clonedError = { ...error };

    if (error.error instanceof ArrayBuffer) {
      const decodedString = String.fromCharCode.apply(null, new Uint8Array(error.error));
      clonedError.error = JSON.parse(decodedString);
    }

    const newError = new HttpErrorResponse(clonedError);
```
which is the same workaround proposed above but for an `arraybuffer`, and we shoud do the same for `text`.

I think in case of an error, angular should only try to parse it as a json regardless of the requested ` responseType`.

**Comment by trotyl** [comment] 2018-03-16 09:16
Duplicate of https://github.com/angular/angular/issues/19148

**Comment by marcosdimitrio** [comment] 2019-08-16 19:07
JaapMosselman [wrote](https://github.com/angular/angular/issues/19888#issuecomment-349650709):
> I created this interceptor as a temporary solution until this one is fixed:
> ...

I'm posting an updated version using rxjs v6.3.3 (`_throw` is now `throwError`), plus all the needed imports.

```typescript
import { Injectable } from '@angular/core';
import { HttpInterceptor, HttpHandler, HttpRequest, HttpEvent, HttpErrorResponse } from '@angular/common/http';
import { Observable, throwError } from 'rxjs';
import { catchError } from 'rxjs/operators';

@Injectable()
export class BlobErrorHttpInterceptor implements HttpInterceptor {
    public intercept(req: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
        return next.handle(req).pipe(
            catchError(err => {
                if (err instanceof HttpErrorResponse && err.error instanceof Blob && err.error.type === "application/json") {
                    // https://github.com/angular/angular/issues/19888
                    // When request of type Blob, the error is also in Blob instead of object of the json data
                    return new Promise<any>((resolve, reject) => {
                        let reader = new FileReader();
                        reader.onload = (e: Event) => {
                            try {
                                const errmsg = JSON.parse((<any>e.target).result);
                                reject(new HttpErrorResponse({
                                    error: errmsg,
                                    headers: err.headers,
                                    status: err.status,
                                    statusText: err.statusText,
                                    url: err.url
                                }));
                            } catch (e) {
                                reject(err);
                            }
                        };
                        reader.onerror = (e) => {
                            reject(err);
                        };
                        reader.readAsText(err.error);
                    });
                }
                return throwError(err);
            })
        );
    }
}
```

**Comment by MrNocTV** [comment] 2020-01-13 05:56
@marcosdimitrio do you have a synchronous version for this? I mean reading the Blob synchronously.

**Comment by frunjik** [comment] 2020-08-26 11:30
Is it correct that i'm still having difficulties receiving plain text using Angular 10 

using (something like):
    const options = {
      responseType: 'text' as 'json',     // !!!! ???
      headers
    };

    return this.http.get(url, options);

I have tried several combinations of get<type>
and responseType: 'text'

(I have not tried any of the workarounds mentioned above ...)

**Comment by walbag** [comment] 2021-02-25 01:42
I'm using angular 8.3.29, and the interceptor workaround mentioned above is not working. Specifically for unit testing with the HttpTestingController, when using the below, it attempts to parse the error as an ArrayBuffer (the responsetype). This happens in such a way that the exception is nowhere handled in an interceptor or observable flow, but instead when the 'request.flush' is called. Calling request.error will work, but request.error does not support what we are attempting to test, which is parsing the error message in the error response. 

I spent most of my day on this issue and it is rather frustrating. Is there going to be a fix? Because having to waste this much time on something simple, although 'par-for-the-course' is also rather ridiculous. :(

`const request = httpMock.expectOne(expectedUrl);
    request.flush(
      { type: "error", errorMessage: "Not found" },
      {
        status: 404,
        statusText: "Not found",
      }
    );`

**Comment by petebacondarwin** [comment] 2021-02-25 10:55
@walbag - I am sorry you are having problems with this. By the way there will not be another release of the Angular v8 branch, since we are now almost at 12.0.0. So any change that would resolve this would only be available if you upgrade to at least v11.

I realise also, that this is actually a subset of #19148, so closing as a duplicate so that we can keep the discussion in one place.

**Closed by petebacondarwin** 2021-02-25 10:55 UTC
Labels: comp: common/http, feature

**Comment by walbag** [comment] 2021-02-25 18:00
@petebacondarwin  thank you for the feedback. I understand about the versions which, as you may understand, is quite a bit out of my control for my workplace. My point is to report the testing issues. They should be addressed as well in HttpTestingController if they still exist in v11/v12. Unfortunately, I'm not able to easily verify if this is still a problem in those versions. I can understand if my comment is ignored for now, but hopefully it will help someone when they go to develop the fix.

**Comment by petebacondarwin** [comment] 2021-02-25 19:16
Thank you for the information. Posting further use cases, such as yours is helpful to prioritise what is worked on. Given that this issue and the linked one were still open, it is likely that it has not been resolved.
