### ISSUE TITLE
Multiple angular elements not working in IE edge browser

### ISSUE THREAD

**Issue by sri1980** [angular/angular#28390] opened 2019-01-26 20:18 UTC
I am trying to load two angular elements from one app. First element loading works fine. But second element It doesn’t detect as angular element in IE.

I am facing this issue only in IE. Chrome it is working fine.

Not seeing any errors in console. 

Can you please help me?

**Comment by ericmartinezr** [comment] 2019-01-26 22:03
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.

**Comment by timschwallie** [comment] 2019-01-29 16:29
See
https://github.com/angular/angular/issues/23732

**Comment by robwormald** [comment] 2019-01-29 22:59
Closing as a duplicate of #23732. In the future, please provide a reproduction or sample code.

**Closed by robwormald** 2019-01-29 22:59 UTC
Labels: comp: elements
