### ISSUE TITLE
Rename 'app' prefix to 'root'

### ISSUE THREAD

**Issue by RuslanBehun** [angular/angular#33529] opened 2019-11-01 11:16 UTC
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/core

### Description

Rename start up file names such as `app.component.ts` to `root.component.ts` and entities **'AppComponent'**  to **'RootComponent'** as they are root, and **app** prefix is blurred and leads to misunderstand according to [angular styleguide LIFT concept:](https://angular.io/guide/styleguide#lift)
 
> Do name the file such that you instantly know what it contains and represents.

### Describe the solution you'd like

**Rename file names:**
`app.component.ts` to `root.component.ts`
`app.component.html` to `root.component.html`
`app.component.css` to `root.component.css`
`app.component.spec.ts` to `root.component.spec.ts`

**Rename** **app** folder to **root**.

**Rename** **'AppComponent'** and **'AppModule'** to **'RootComponent'** and **'RootModule'**.

**Comment by trotyl** [comment] 2019-11-02 15:05
Duplicate of https://github.com/angular/angular-cli/issues/10359

**Closed** 2019-11-04 13:35 UTC
Labels: comp: docs-infra, type: feature
