### ISSUE TITLE
Attribute as component selector not recognized

### ISSUE THREAD

**Issue by SekibOmazic** [angular/angular#1802] opened 2015-05-11 09:10 UTC
After updating my plunk from alpha.20 to alpha.22 I've got following exception:

```Shell
Component 'A' can only have an element selector, but had '[a]'

Error
    at new BaseException (https://code.angularjs.org/2.0.0-alpha.22/angular2.dev.js:5938:25)
    at DirectiveParser._ensureComponentOnlyHasElementSelector (https://code.angularjs.org/2.0.0-alpha.22/angular2.dev.js:19095:21)
```
See console in plunk for detailed stack trace.

Plunk: http://plnkr.co/edit/yXqVIkJXG3OXsoouYTN2?p=preview

**Comment by pkozlowski-opensource** [comment] 2015-05-11 09:57
Was introduced in e3c11045bf335b141cc986be411ed7d71dd4ed5b and seems to be a concussion change: https://github.com/angular/angular/commit/e3c11045bf335b141cc986be411ed7d71dd4ed5b#diff-20dbf210147462b49d6b70e5186c7f2fR186

@vsavkin is the best person to confirm that this is new, required behavior (in this case we should probably add a note to the changelog).

**Comment by SekibOmazic** [comment] 2015-05-11 10:48
@pkozlowski-opensource What is/was the intention (mental model) for this behavior? Should Components be elements only and Directives attributes?

**Comment by pkozlowski-opensource** [comment] 2015-05-11 10:54
For me this change makes sense, if we take simple examples:
* Component -> element
* Directive -> attribute

As I would expect components with their own templates to reside on their own element. Then it is not fully  clear to me how this will play for the viewport directives. Let's see what @vsavkin has to say here.

**Comment by vsavkin** [comment] 2015-05-11 17:07
There are a few reasons to have enforce this constraint:

* We dynamically create components. Without this constraint, the creation is a bit weird. For instance, what element would we create for this selector `not([a=5])`, or for this one `[a],[b]`? It is possible to make it work, but the behavior may be confusing.
* You cannot have more than one component on the same element. 
* It aligns better with web components.

Regular directives can have any selector because none of the reasons apply to them. 

We can revisit it. This was the easiest thing to do, and imo it seems reasonable.

**Comment by pkozlowski-opensource** [comment] 2015-05-11 17:11
Personally I like the current behaviour and would keep it (unless we discover some use-cases further down the road). My vote goes to closing this one with the changelog update.

**Comment by SekibOmazic** [comment] 2015-05-11 17:58
@vsavkin That makes sense of course. 
@pkozlowski-opensource The documentation also needs an update:
Remove https://github.com/angular/angular/blob/master/modules/angular2/src/core/annotations_impl/annotations.js#L380
and add a description for `selector` in `Component` section

Will close this as everything is clear.

**Comment by adamdbradley** [comment] 2015-05-11 19:53
While I do fully agree and recommend this pattern:

- Component -> element
- Directive -> attribute

I think the forced constraint will have more negative impacts than positive. For example, I was able to use `<body my-app>` as the root component, and provide a template for it. Another that comes to mind is the button element, where for accessibility we'd still want to use the actual `<button>` element most times.

> For instance, what element would we create for this selector not([a=5]), or for this one [a],[b]? It is possible to make it work, but the behavior may be confusing.

If it created a `div` element, it would have made sense to me as the component author.

> You cannot have more than one component on the same element.

Like having multiple directives that needed isolate scope in Angular1, it'd give you an error message, I'd expect the same here.

So while I agree that best practice is to have a component be an element, and directive an attribute, the constraint may have some negative affects and require more work arounds for developers. Could it still be allowed, but documented you should always use elements for components?

And no this isn't the end of the world if it's not allowed, I just wanted to through out some discussion points. Thanks

**Comment by jamm** [comment] 2015-05-11 21:16
What will say @marcysutton (or other a11y experts) about replacing all <button>s by custom elements?
Also, some CSS frameworks expect exact names of elements to apply selectors/rules.
Also I think SVG will not be as flexible to be able use custom tags and nested elements everywhere without consequences (although not tested, maybe it's wrong assumption).

I like explicit limitation "1 template per element" but I don't think component should exist only as element.

**Comment by mhevery** [comment] 2015-05-13 17:31
I am re-opening this becouse it is not clear to me that we solve the `<button>` use case. Will chat with @vsavkin

**Comment by marcysutton** [comment] 2015-05-13 18:04
@jelbourn's comments on https://github.com/angular/angular/issues/1598#issuecomment-97599750 are great: developers should be encouraged to use semantic elements and reuse native behavior whenever possible. This isn't limited to just `button`–there are also the `details`/`summary` elements, headings, lists, links, and so many other semantic elements I could see people reinventing *just 'cause*. Attributes instead of custom tag names could be leveraged for keyboard and assistive technology support, and it is definitely worth it to do so.

I personally am a fan of `is=""` for extending native elements but I know there is a lot of discussion about whether this is the right way forward. I'm trying to dig up some recent info from Alice Boxhall about the current  of `is=""` situation.. if I find it I'll report back.

**Comment by jelbourn** [comment] 2015-05-13 18:30
This is a dupe of #1602

**Comment by masaeedu** [comment] 2015-07-17 16:12
One of the problems this creates is that it is no longer possible to create components that do not break styling rules such as `.navbar-nav>li`. If I'm creating a component that will output the `li` and all descendant content, the component will appear as a node in the DOM, and hence break the `.navbar-nav>li` rule.

The reasoning presented above is very convincing, but please provide us with some alternative workflow for templating the content of an attribute based directive, rather than having to accept a `ViewContainerRef` and generate the descendant DOM from whole cloth.

**Comment by mhevery** [comment] 2015-08-24 20:55
c20a5d65d86c57227a1f3d3cc0b0ca2b085eac48

**Closed by mhevery** 2015-08-24 20:55 UTC
Labels: comp: core/view/compiler, effort2: medium (day), P3: important, state: Periodic Review, type: bug
