### ISSUE TITLE
Not able to use transform function without initial value in non-required input

### ISSUE THREAD

**Issue by Eugeno** [angular/angular#54511] opened 2024-02-20 08:00 UTC
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

Old approach:
`@Input({ transform: numberAttribute }) width?: number;`

I can't use `input` without initial value, since only `input.required` can have only the options.

### Proposed solution

`width = input<number, number | string>({ transform: numberAttribute });`

### Alternatives considered

I can use this now:
`width = input<number | undefined, number | string | undefined>(undefined, { transform: numberAttribute });`

**Comment by JoostK** [comment] 2024-02-20 08:05
Closing as duplicate of https://github.com/angular/angular/issues/53909, which is discussing a different side of the same coin.

**Closed by JoostK** 2024-02-20 08:05 UTC

**Comment by JoostK** [comment] 2024-02-20 08:07
Also note that options cannot be lifted to just replace the initial value, since Angular won't be able to tell it apart from any possible initial value (and generics won't help since they're not available at runtime)
