### ISSUE TITLE
angular.io docs content not loading

### ISSUE THREAD

**Issue by SimonBrazell** [angular/angular#31301] opened 2019-06-27 01:14 UTC
# 📚 Docs or angular.io bug report

### Description

angular.io docs content not loading in Chrome 75, just loading the app shell with no content, see below console logs. This occurred for me when attempting to navigate to [https://angular.io/api/forms/Validators](https://angular.io/api/forms/Validators) from a Google search. The issue was rectified by a page reload with the content loading correctly after this.

## 🔬 Minimal Reproduction
Cannot reproduce after reloading the page, but I have seen this prior to today.

### What's the affected URL?**
https://angular.io/api/forms/Validators although it may occur on others, can't recall the URLs I experienced it on previously.

### Expected vs Actual Behavior**
Shouldn't require page reload to view the docs content.

## 📷Screenshot

Sorry didn't get one before reloading the page.

## 🔥 Exception or Error
<pre><code>
m @ polyfills.92ff7bd39a33b228eade.js:1
angular_whiteTransparent_withMargin.69f1fb57db78bb0b878f.png:1 Failed to load resource: the server responded with a status of 404 ()
/code-code-example-module-ngfactory.bf3e5eeb00a2b767c625.js:1 Failed to load resource: the server responded with a status of 404 ()
main.4202909235a02f3a24ae.js:1 ERROR Error: [DocViewer] Error preparing document 'api/forms/Validators': Error: Loading chunk 11 failed.
(error: https://angular.io/code-code-example-module-ngfactory.bf3e5eeb00a2b767c625.js)
    at HTMLScriptElement.c (runtime.3314cba9b60341afaef9.js:1)
    at HTMLScriptElement.D (polyfills.92ff7bd39a33b228eade.js:1)
    at e.invokeTask (polyfills.92ff7bd39a33b228eade.js:1)
    at Object.onInvokeTask (main.4202909235a02f3a24ae.js:1)
    at e.invokeTask (polyfills.92ff7bd39a33b228eade.js:1)
    at t.runTask (polyfills.92ff7bd39a33b228eade.js:1)
    at t.invokeTask [as invoke] (polyfills.92ff7bd39a33b228eade.js:1)
    at y (polyfills.92ff7bd39a33b228eade.js:1)
    at HTMLScriptElement._ (polyfills.92ff7bd39a33b228eade.js:1)
    at e.selector (main.4202909235a02f3a24ae.js:1)
    at e.error (main.4202909235a02f3a24ae.js:1)
    at e._error (main.4202909235a02f3a24ae.js:1)
    at e.error (main.4202909235a02f3a24ae.js:1)
    at e._error (main.4202909235a02f3a24ae.js:1)
    at e.error (main.4202909235a02f3a24ae.js:1)
    at e._error (main.4202909235a02f3a24ae.js:1)
    at e.error (main.4202909235a02f3a24ae.js:1)
    at e.notifyError (main.4202909235a02f3a24ae.js:1)
    at e._error (main.4202909235a02f3a24ae.js:1)
_r @ main.4202909235a02f3a24ae.js:1
/toc-toc-module-ngfactory.af5ec6fc598a8b5a66a9.js:1 Failed to load resource: the server responded with a status of 404 ()
/default~code-code-example-module-ngfactory~code-code-tabs-module-ngfactory.c49044a42b180eb8501f.js:1 Failed to load resource: the server responded with a status of 404 ()
/app/search/search-worker.js:1 Failed to load resource: the server responded with a status of 404 ()
styles.843e7149d29e4b6563f4.css:1 Failed to load resource: the server responded with a status of 404 ()
</code></pre>

### Browser info

Google Chrome Version 75.0.3770.100 (Official Build) (64-bit)
macOS 10.14.5

**Comment by ericmartinezr** [comment] 2019-06-27 01:55
See https://github.com/angular/angular/issues/28114

**Comment by gkalpak** [comment] 2019-06-27 20:25
Closing as duplicate of #28114 😞

**Closed by gkalpak** 2019-06-27 20:25 UTC
Labels: comp: docs-infra, freq2: medium, severity2: inconvenient, type: bug/fix

**Comment by gobi004** [comment] 2019-08-02 10:47
am also facing the same issues. page content are not loding whenever navigating to other topics or search
