### ISSUE TITLE
Standalone components - longer compilation time

### ISSUE THREAD

**Issue by Azbesciak** [angular/angular#48001] opened 2022-11-09 05:39 UTC
### Which @angular/* package(s) are the source of the bug?

compiler-cli, compiler, core

### Is this a regression?

Yes

### Description

Hello, I have just migrated my whole project to standalone components. In general, my project is designed as a single module - single component, but modules sometimes also provide services/other singleton dependencies. I also extensively use lazy modules (not router ones - loaded manually with `loadChildren`).

The compilation has the same output (files out, ~their size), but in total it is about 20-30% slower than earlier; I checked it a couple of times, also go back in the history before change and to the current state; it was reproductive. It is a production app.

The question is whether you noticed similar behavior, are some changes are expected or possible, to optimize it.
I am also using nrwl, but as mentioned - the difference is visible between migration to standalone components commits and multiple repetitions of builds.

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Node : 16.14.2
   OS   : win32 x64
   npm  : 8.5.0

   @angular/animations: 14.2.5
   @angular/cdk: 14.2.4
   @angular/common: 14.2.5
   @angular/compiler: 14.2.5
   @angular/core: 14.2.5
   @angular/elements: 14.2.5
   @angular/forms: 14.2.5
   @angular/material: 14.2.4
   @angular/platform-browser: 14.2.5
   @angular/platform-browser-dynamic: 14.2.5
   @angular/router: 14.2.5
   @angular/service-worker: 14.2.5
   @angular-devkit/build-angular: 14.2.5
   @angular/cli: 14.2.5
   @angular/compiler-cli: 14.2.5
   @angular/language-service: 14.2.5
   nx : 15.0.3
   @nrwl/angular : 15.0.3
   @nrwl/cypress : 15.0.3
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.0.3
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : Not Found
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.0.3
   @nrwl/js : 15.0.3
   @nrwl/linter : 15.0.3
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : 8.12.11
   @nrwl/storybook : 15.0.3
   @nrwl/web : Not Found
   @nrwl/webpack : 15.0.3
   @nrwl/workspace : 15.0.3
   typescript : 4.8.4
```

**Comment by pkozlowski-opensource** [comment] 2022-11-09 07:19
We haven't seen degraded compilation perf nor other reports of such degradation so far. Happy to investigate, but would need a reproduction scenario that we could profile.

**Comment by AndrewKushnir** [comment] 2022-11-18 00:37
Closing this ticket for now due to the lack of a repro. Please reopen or create a new one when a repro is available.

**Closed by AndrewKushnir** 2022-11-18 00:37 UTC
Labels: needs reproduction, area: core
