### ISSUE TITLE
regression(service-worker): 6.1.10. i13.ɵangular_packages_service_worker_service_worker_c is not a function 

### ISSUE THREAD

**Issue by levgaas** [angular/angular#26384] opened 2018-10-10 23:17 UTC
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
I'm using SSR, PWA, Service workers and lazy routing.
After updating to `6.1.10 ` from `6.1.9` I'm seeing this issue:
```
TypeError: i13.ɵangular_packages_service_worker_service_worker_c is not a function
    at C:\Users\vladi\Desktop\ang-t\angular-tuned\apps\angular-tuned\functions\dist-server\main.js:284:6492
    at _callFactory (C:\Users\vladi\Desktop\ang-t\angular-tuned\apps\angular-tuned\functions\node_modules\@angular\core\bundles\core.umd.js:8474:32)
    at _createProviderInstance (C:\Users\vladi\Desktop\ang-t\angular-tuned\apps\angular-tuned\functions\node_modules\@angular\core\bundles\core.umd.js:8420:30)
    at initNgModule (C:\Users\vladi\Desktop\ang-t\angular-tuned\apps\angular-tuned\functions\node_modules\@angular\core\bundles\core.umd.js:8350:36)
    at new NgModuleRef_ (C:\Users\vladi\Desktop\ang-t\angular-tuned\apps\angular-tuned\functions\node_modules\@angular\core\bundles\core.umd.js:9076:13)
    at Object.createNgModuleRef (C:\Users\vladi\Desktop\ang-t\angular-tuned\apps\angular-tuned\functions\node_modules\@angular\core\bundles\core.umd.js:9065:16)
    at NgModuleFactory_.create (C:\Users\vladi\Desktop\ang-t\angular-tuned\apps\angular-tuned\functions\node_modules\@angular\core\bundles\core.umd.js:11607:29)
    at C:\Users\vladi\Desktop\ang-t\angular-tuned\apps\angular-tuned\functions\node_modules\@angular\core\bundles\core.umd.js:4375:47
    at ZoneDelegate.invoke (C:\Users\vladi\Desktop\ang-t\angular-tuned\apps\angular-tuned\functions\node_modules\zone.js\dist\zone-node.js:388:26)
    at Object.onInvoke (C:\Users\vladi\Desktop\ang-t\angular-tuned\apps\angular-tuned\functions\node_modules\@angular\core\bundles\core.umd.js:3890:37)
```

Not sure is that helps. But here is some code this error refers to. Missing function at the very end:
```
i0.ɵmpd(1024, i0.APP_INITIALIZER, function (p0_0, p1_0, p2_0, p2_1, p2_2, p2_3, p3_0, p3_1, p3_2, p4_0) { return [i7.ɵangular_packages_platform_browser_platform_browser_j(p0_0), i11.ɵangular_packages_router_router_i(p1_0), i13.ɵangular_packages_service_worker_service_worker_c(p2_0, p2_1, p2_2, p2_3)
```
## Minimal reproduction of the problem with instructions

If you don't know what's the issue is from the top of your head I'll provide a repo for reproduction. But basically it's a minimal project with SSR, Service Workers and lazy routing.

## Environment
<pre><code>
Angular version: 6.1.10

Browser:
- [x] Chrome (desktop) version 69
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.11.3  
- Platform:  Windows

**Comment by gkalpak** [comment] 2018-10-11 07:14
Thanks for reporting this issue. I have no idea what might be causing this, so I need a reproduction in order to investigate 😅

**Comment by leo6104** [comment] 2018-10-11 07:40
I got same error in SSR. 
```
1|mapia-pc      | /board/video/9865?page=184 500 Error Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html) TypeError: bn.ɵangular_packages_service_worker_service_worker_c is not a function
1|mapia-pc      |     at /var/app/current/dist-pc/server.js:1088:19472
1|mapia-pc      |     at _callFactory (/var/app/current/node_modules/@angular/core/bundles/core.umd.js:8474:32)
1|mapia-pc      |     at _createProviderInstance (/var/app/current/node_modules/@angular/core/bundles/core.umd.js:8420:30)
1|mapia-pc      |     at initNgModule (/var/app/current/node_modules/@angular/core/bundles/core.umd.js:8350:36)
1|mapia-pc      |     at new NgModuleRef_ (/var/app/current/node_modules/@angular/core/bundles/core.umd.js:9076:13)
1|mapia-pc      |     at Object.createNgModuleRef (/var/app/current/node_modules/@angular/core/bundles/core.umd.js:9065:16)
1|mapia-pc      |     at NgModuleFactory_.create (/var/app/current/node_modules/@angular/core/bundles/core.umd.js:11607:29)
1|mapia-pc      |     at /var/app/current/node_modules/@angular/core/bundles/core.umd.js:4375:47
1|mapia-pc      |     at n.invoke (/var/app/current/dist-pc/server.js:106:7001)
1|mapia-pc      |     at Object.onInvoke (/var/app/current/node_modules/@angular/core/bundles/core.umd.js:3890:37)
```

**Comment by gkalpak** [comment] 2018-11-26 14:05
Can some of you, please, provide a minimal reproduction, so I can investigate this?

**Comment by Trojaner** [comment] 2018-11-26 20:12
I managed to fix this issue.
When upgrading to Angular 7 from Angular 6, the SSR build failed and ASP.NET Core used the outdated Angular 6 main.js (server) instead. After fixing the build errors, this problem was gone.

**Comment by gkalpak** [comment] 2018-11-26 20:31
Thx for getting back, @Trojaner. I am going to close this, since there is no indication this is actually an issue in Angular.
(Happy to re-open and investigate if there is a minimal reproduction showing it is an Angular issue.)

**Closed by gkalpak** 2018-11-26 20:31 UTC
Labels: comp: service-worker, state: Need repro, type: bug/fix
