### ISSUE TITLE
ng build <project> changes output of another project in the workspace

### ISSUE THREAD

**Issue by json-derulo** [angular/angular#37104] opened 2020-05-13 14:39 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?
No

### Description
When building a project in a workspace, the build output of other project are changed during build. Have a look at the reproduction below. After you followed the steps, inside the `dist` folder, you can see that `my-lib` is not built for production anymore, even though I previously built the library for production. It seems that the command `ng build my-application --prod` changes the output of `my-lib`. If I build `my-application`, the output of `my-lib` should not be changed in my opinion.

This is annoying, because what I need to do to prevent errors in the build pipeline, is to

1) build the library for production
2) build the application for production
3) build the library for production

The third step should not be necessary.

## 🔬 Minimal Reproduction
Create a workspace with a library and an application

```
ng new my-workspace --create-application=false
cd my-workspace
ng generate library my-lib
ng generate application my-application
```
Now build the library and the application with `production` configuration:
```bash
ng build my-lib --prod
# my-lib is now built for production
ng build my-application --prod
# my-lib is not anymore built for production
```

## 🔥 Exception or Error
Below is the output in the console. As you can see, one step of the application build is `Compiling my-lib : es2015 as esm2015`
<pre><code>> ng build my-lib --prod && ng build my-application --prod

Building Angular Package

------------------------------------------------------------------------------
Building entry point 'my-lib'
------------------------------------------------------------------------------
Compiling TypeScript sources through ngc
Bundling to FESM2015
Bundling to FESM5
Bundling to UMD
Minifying UMD bundle
Writing package metadata
Built my-lib

------------------------------------------------------------------------------
Built Angular Package
 - from: C:\Projects\example-library-workspace\projects\my-lib
 - to:   C:\Projects\example-library-workspace\dist\my-lib
------------------------------------------------------------------------------
Compiling my-lib : es2015 as esm2015
Generating ES5 bundles for differential loading...
ES5 bundle generation complete.

chunk {0} runtime-es2015.1eba213af0b233498d9d.js (runtime) 1.45 kB [entry] [rendered]
chunk {0} runtime-es5.1eba213af0b233498d9d.js (runtime) 1.45 kB [entry] [rendered]
chunk {2} polyfills-es2015.4265614f51b38bdc5abc.js (polyfills) 36.1 kB [initial] [rendered]
chunk {3} polyfills-es5.d7f438905a78995e41d5.js (polyfills-es5) 129 kB [initial] [rendered]
chunk {1} main-es2015.a8830bb6116aeecf10ff.js (main) 137 kB [initial] [rendered]
chunk {1} main-es5.a8830bb6116aeecf10ff.js (main) 160 kB [initial] [rendered]
chunk {4} styles.3ff695c00d717f2d2a11.css (styles) 0 bytes [initial] [rendered]
Date: 2020-05-13T14:18:05.269Z - Hash: b6f9baef21f8ce0ea869 - Time: 93640ms
</code></pre>

## 🌍 Your Environment
<pre><code>     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 9.1.5
Node: 12.16.3
OS: win32 x64

Angular: 9.1.6
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.901.5
@angular-devkit/build-angular      0.901.5
@angular-devkit/build-ng-packagr   0.901.5
@angular-devkit/build-optimizer    0.901.5
@angular-devkit/build-webpack      0.901.5
@angular-devkit/core               9.1.5
@angular-devkit/schematics         9.1.5
@angular/cli                       9.1.5
@ngtools/webpack                   9.1.5
@schematics/angular                9.1.5
@schematics/update                 0.901.5
ng-packagr                         9.1.3
rxjs                               6.5.5
typescript                         3.8.3
webpack                            4.42.0

</code></pre>

**Comment by petebacondarwin** [comment] 2020-05-14 10:48
At this time, I think the best we can do is to document this better.

**Comment by petebacondarwin** [comment] 2020-05-19 10:33
This is really just a duplicate of #33395

**Closed by petebacondarwin** 2020-05-19 10:33 UTC
Labels: comp: docs, comp: ngcc, docsarea: library-or-schematics, state: needs doc team review, type: bug/fix, type: needs investigation
