### ISSUE TITLE
RFE: a way to prevent two-way data binding echos

### ISSUE THREAD

**Issue by radek-holy** [angular/angular#6114] opened 2015-12-24 15:21 UTC
Hello,

currently, I'm trying to integrate a custom third-party input field (source code editor) written in JavaScript which is not based on Angular. Thus I need to wrap it to a component, use `EventEmitter` to report changes outside and use `ngOnChanges` to apply changes coming from outside.

The `Input` of the component is named `model` and the `Output` is named `modelChange` so that the other components _can_ take advantage of a two-way data binding.

I've noticed that if the parent component applies the two-way data binding and if the child emits an event, the change of the parent's data emits another event which is sent back to the child. If you imagine that the `ngOnChanges` calls an expensive method that handles the change, you probably agree with me that this effect is something I would like to avoid. Can you please provide a mechanism to achieve this?

Or am I doing something wrong? Can it be done better?

Here is a Plunk demonstrating the echo effect: http://plnkr.co/edit/drRlJRCsvnzcTqlR4UlX

PS - I am not sure if this is related to https://github.com/angular/angular/issues/4593
PS - Feel free to make the title more understandable.

**Comment by zoechi** [comment] 2015-12-24 15:54
I didn't investigate your Plunker very closely but AFAIK you don't need to set the value *AND* fire the event.

Instead of 
```
   this.model += "!";
   this.modelChange.next(this.model);
```
this should do
```ts
  this.modelChange.next(this.model + "!");
```

**Comment by radek-holy** [comment] 2015-12-24 19:47
Yes, you are right. I've updated the Plunk. Unfortunately it does not solve the issue.

**Comment by radek-holy** [comment] 2016-01-05 08:21
Maybe a real life example may attract some attention: http://plnkr.co/edit/6MtxvijX3LzQAkFHQ1Uq?p=preview . Try to type anything into the field and watch the cursor (a [side effect](https://github.com/codemirror/CodeMirror/issues/3734) of `setValue`).

**Comment by robwormald** [comment] 2016-01-05 09:24
this is a relatively straightforward fix: http://plnkr.co/edit/q7RtwUkOFzX9sAyHnxo0?p=preview

**Comment by radek-holy** [comment] 2016-01-05 10:03
There is a syntax error:
```
    this.editor.on("changes", () =>
    this._value = this.editor.getDoc().getValue();
//                                               ^  (error TS1005: ')' expected.)
      this.codemirrorChange.next(this._value);
    );
```

I apologize, I did not get the point of the fix. If I add curly brackets there (in order to fix the error), my issue is still not solved. It's just harder to reproduce. You need to press two keys simultaneously. Basically, you need to emit a change in the editor just before the echo returns to the `Cmp` component.

**Comment by radek-holy** [comment] 2016-01-05 13:46
OK, my attempts to work around this issue converged to an attempt to access the scope of the event emitter... So, I guess it's time to give up... :)

**Comment by radek-holy** [comment] 2016-01-06 08:24
I guess I need to find out why `ngModel` does not suffer for it...

**Comment by vicb** [comment] 2016-10-07 21:32
Is this still applicable to 2.0 ?
If yes, could you please:
-  update your plunker,
- describe the current behavior,
- describe the expected behavior.

Thanks

**Comment by radek-holy** [comment] 2016-10-08 16:30
Hello, I don't use Angular anymore so I don't know the current behavior but since [the condition](https://github.com/angular/angular/blob/master/modules/%40angular/forms/src/directives/ng_model.ts#L129) in the `ngModel` seems to be still there, I guess that this is still applicable.

The expected "behavior" is that in custom directives similar to `ngModel`, we wouldn't have to write the conditions above. In other words:
When you apply two-way data binding on a property of such a component and when the component emits a change event, the event returns back to the component. At least it's how it used to work and I assume that it did not change.
What I wish is that there would be a mechanism (maybe a flag assigned to the event or to the component or to the binding... I leave it up to you) to tell Angular not to deliver events emitted by a directive back to the same directive.

Sorry, it's not worth to update the plunker since I don't use Angular anymore and since it seems that you are about to close this RFE anyway.

**Comment by vicb** [comment] 2016-10-08 19:47
I'm only trying to understand the issue here - thanks for providing more information.

Probably linked to https://github.com/angular/angular/issues/4593

**Comment by splincode** [comment] 2018-07-26 15:30
@radek-holy Is the issue relevant?

**Comment by pkozlowski-opensource** [comment] 2018-10-05 15:11
I'm going to go ahead and close this one as a duplicate of #4593

**Closed by pkozlowski-opensource** 2018-10-05 15:11 UTC
Labels: comp: core & compiler, type: feature
