### ISSUE TITLE
🚀Support multiple Angular apps running in one page with ViewEncapsulation.Emulated

### ISSUE THREAD

**Issue by mleibman** [angular/angular#28596] opened 2019-02-07 16:09 UTC
# 🚀Support multiple Angular apps running in one window with ViewEncapsulation.Emulated.

### Description
I am working on a setup that will have multiple Angular apps (with separate instances of Angular itself) rendering into the same document. `_nghost-c*` and `_ngcontent-c*` attributes generated by Angular's `emulated` view encapsulation rely on an internal auto-incremented counter:

https://github.com/angular/angular/blob/885f1af509eb7d9ee049349a2fe5565282fbfefb/packages/core/src/view/util.ts#L59-L77

CSS rules produced by them can easily result in conflicts when there are multiple Angular apps running in that page.

For example, the following component:

```javascript
@Component({
selector: 'my-app',
styles: [`
  :host {
    display: block;
    border: 1px solid black;
  }
  div {
    color: blue;
  }
`],
})
class MyApp {
}
```

will generate

```html
<style>
[_nghost-c5] {
  display: block;
  border: 1px solid black;
}
div[_ngcontent-c5] {
  color: blue;
}
</style>
```

Since each Angular instance has its own copy of the auto-incremented ID, these rules will also unintentionally apply to components with the same generated ID rendered by the another instance of Angular running in the same window. 

### Describe the solution you'd like
Use a globally unique component ID.
Alternatively, allow the component ID generator function to be configurable as an injection token.

### Describe alternatives you've considered
The solution has to work for an existing large-scale Angular application, so migrating everything away from the default view encapsulation is a non-starter.

**Comment by trotyl** [comment] 2019-02-07 16:17
Duplicate of https://github.com/angular/angular/issues/16676

**Comment by mhevery** [comment] 2019-02-12 23:45
closing as duplicate

**Closed by mhevery** 2019-02-12 23:45 UTC
Labels: comp: core & compiler
