### ISSUE TITLE
Ergonomic component-level code splitting and lazy loading

### ISSUE THREAD

**Issue by aalbericio** [angular/angular#18093] opened 2017-07-13 11:12 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[X] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Router Module is optional and, depending on the nature of the app, it does not naturally fit.

If we don't use the RouterModule, I can't see an easy way to take advantage of the "lazy loading" feature for modules.

I'd like to, somehow, identify an NgModule to be "lazy loaded" at definition time (just like you define its providers, etc).

Once the module has been marked as "lazy loaded", the build should generate an independent chunk for it and that module becomes eligible for being lazy-loaded at some execution time.

Of course, If I have the choice of marking a module "lazy", I also need a mechanism to manually load those "lazy loaded" modules and start using them.

In summary, the feature request is: make the "lazy loading" feature available to developers outside the RouterModule since this module is optional but the feature should still be available.

Of course this should output AOT compatible chunks, etc, just like the RouterModule internally does.

## Expected behavior

In summary, the feature request is: make the "lazy loading" feature available to developers outside the RouterModule since this module is optional but the feature should still be available.

Of course this should output AOT compatible chunks, etc, just like the RouterModule internally does.

## What is the motivation / use case for changing the behavior?

Our application and functionally can not be Router driven thus we need some way to make use of the "lazy loading" strategy that is internally used by the Router.

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by Toxicable** [comment] 2017-07-13 21:25
You can already do this, here is a small example of how
```
System.import('./lazy.module.ngfactory.ts').then((moduleFactories: any) => {
   const moduleFactory: NgModuleFactory<any> = moduleFactories['LazyModuleNgFactory'];
   const moduleRef = moduleFactory.create(injector);
   const compFactory = moduleRef.componentFactoryResolver.resolveComponentFactory(COMP_TYPE_TOKEN);
   viewRef.createComponent(compFactory);
});
```
This is almost the exact same method the router uses to lazy load except it simply provides a nice API to use it, however, this only works for AOT, you'd need extra logic to support JIT.

**Comment by josephliccini** [comment] 2017-07-16 01:53
Hi!

I had left this idea a while ago but was making some progress on a solution.

(@Toxicable we chatted about this a while ago in the gitter.im angular room.)

I think it will require a new webpack loader to get it to work cleanly, but here's the basic idea.

1. create a `<dynamic-lazy-load>` component:
```ts
@Component({
  selector: 'dynamic-lazy-load',
  template: ''
})
export class DynamicLazyLoadComponent implements OnChanges {

  /** Entry Component desired */
  @Input() 
  public componentName: string;

  /** This is the same module callback one would pass to Angular Router loadChildren */
  @Input() 
  public loadChildrenCallbackObject: () => Promise<any>; 
  
  private loadingStarted: boolean = false;

  constructor(
    private injector: Injector,
    private viewRef: ViewContainerRef,
    @Optional() private compiler: Compiler // only available in JiT mode
  ) { }

   public async ngOnChanges(changes) {
        if (this.loadChildrenCallback && !this.loadingStarted) {
	    this.loadingStarted = true;

            const lazyModule = await this.loadChildrenCallback();
            if (lazyModule instanceof NgModuleFactory) {
                console.log('AoT Mode');
                this.createAndInsertComponent(lazyModule);
            } else {
                const compiledModule = await this.compiler.compileModuleAsync(lazyModule);
                console.log('JiT Mode');
                this.createAndInsertComponent(compiledModule);
            }
        }
    }

    public createAndInsertComponent(moduleFactory: NgModuleFactory<any>) {
        const moduleRef = moduleFactory.create(this.injector);
        if (!moduleRef.instance.dynamicLazyLoadComponents) {
            console.log('No Lazy Load Components Found...');
            return;
        }

        const componentType = moduleRef.instance.dynamicLazyLoadComponents[this.componentName];
        const componentFactoryResolver: ComponentFactoryResolver = moduleRef.componentFactoryResolver;
        const compFactory = componentFactoryResolver.resolveComponentFactory(componentType);
        this.viewRef.createComponent(compFactory);
    }
}
```

2. write a lazy-loaded `@NgModule()` in format:

```ts
interface DynamicLazyLoadModule {
	dynamicLazyLoadComponents: { [key: string]: any };
}

@NgModule({
	imports: [ MyLazyComponent ],
	exports: [ MyLazyComponent ],
	entryComponents: [ MyLazyComponent ]
})
export class MyLazyNgModule implements DynamicLazyLoadModule {
	public dynamicLazyLoadComponents = { 'MyLazyComponent': MyLazyComponent };
}
```

3. In the containing component's HTML:
```html
<dynamic-lazy-load *ngIf="shouldLoadLazyComponent" 
					componentName="MyLazyComponent" 
					[loadChildrenCallback]="loadLazyModuleCallback">
</dynamic-lazy-load>
```

I had a prototype working but abandoned as I had some other stuff to take care of and hit a blocker on AoT.

And the hackiest part was I had to trick the Webpack loader into thinking this was a loadChildren for the router, which is where I gave up because I couldn't get AoT working.
```ts
const loadLazyModuleCallback = '../my-lazy/my-lazy.module#MyLazyModule';
```
I did have it working when I hardcoded to JiT like this:
```ts
const loadLazyModuleCallback = () => new Promise((resolve) => {
	require.ensure([], (require) => {
		const module = require('../my-lazy/my-lazy.module');
		resolve(module);
	});
}, 'my-lazy.module');
```

I haven't tested this code in a while, but I can maybe update with a demo sometime when I have time.

This feature would be great to have as something easier and standardized, as I've been doing some React coding on the side and they can lazy load components within a view pretty easily.

Some problems I can foresee:
1. I am not sure what would happen if there was `providers`, `pipes`, etc. in the lazy module..
2. Dependency on an arbitrary string `'MyLazyComponent'` in the example.
3. Interactions with router

I just thought I'd post and share my exploration as I've seen this question a lot.  By no means am I posting above code as a solution (again, this was just a hacky prototype I tried)

**Comment by aalbericio** [comment] 2017-07-20 06:20
Hello guys,

I aprreciate the efforts of offering a workaround on this (I will more than probably use a custom hack on this following your instructions, but I still see the advantage of declaring a Module like:

@NgModule({
	imports: [ MyLazyComponent ],
	exports: [ MyLazyComponent ],
	entryComponents: [ MyLazyComponent ],
        **lazy: true**
})

... and, of course, having a programmatic API to load this/or any Module

ModuleManager.loadModule(....).then(...)

... and, of course, this should work with JiT/AOT, serve/build, etc

I know Ionic and others like you have implemented their custom solution but I can bet adding this feature makes Angular (and any other based solution) just better.

**Comment by Toxicable** [comment] 2017-07-20 06:26
I made another demo here https://plnkr.co/edit/ZGC82G9u10EQFYFvvRMB?p=preview
it uses `NgModuleFactoryLoader` which Angular already provides for you to handle lazy loading modules

**Comment by aalbericio** [comment] 2017-07-20 09:52
Hello,

Okay, that will load the module and instantiate its entry component but how does that solution play in conjunction with the DI/Injectors system and what about the build? Will the build generate a separate chunk for the LazyModule?

I would like not to lose any feature provided both by the DI/Injectors system (eager/lazy) and the build process. 

I still firmly believe that this feature should be provided by the framework and open to developers.

**Comment by Toxicable** [comment] 2017-07-20 09:55
@aalbericio It works the same as the Router. Seprate Chunk with child Injector.
Is the example I provided to concise enough?

**Comment by aalbericio** [comment] 2017-07-20 10:52
Ok. I'm going to test it under an isolated environment and tell you. I just wanted to confirm those points before testing it.

Thanks very much, Fabian.

**Comment by mlc-mlapis** [comment] 2017-07-20 11:10
@Toxicable ... not sure but the building could be a problem. You will need probably to define all routes with lazy module paths even if you don't use them directly to get right chunks.

**Comment by Toxicable** [comment] 2017-07-20 22:09
@mlc-mlapis You're right I was missing a few small components for it to work with the CLI and Webpack. I've updated the demo with this now working in plunkr, CLI and with AOT.
https://plnkr.co/edit/ZGC82G9u10EQFYFvvRMB?p=preview

**Comment by mlc-mlapis** [comment] 2017-07-20 22:20
@Toxicable ... great ... and now there will be always the right answer for every one who has a request for a new feature or API ... to allow programmatical way how to load and use lazy loaded modules.

It is so simple that it couldn't be more simpler.

**Comment by josephliccini** [comment] 2017-07-20 22:46
@Toxicable this is great!! Thanks for doing this!

**Comment by Toxicable** [comment] 2017-07-20 22:49
I made one more little update to it just to show how you can use the paths to the lazy modules without any duplication aswell as how you provide in a feature module aswell.
https://plnkr.co/edit/ZGC82G9u10EQFYFvvRMB?p=preview

@josephliccini No problem, hope it's helped

**Comment by josephliccini** [comment] 2017-07-20 22:53
Would something like this be able to be placed into a `ngx-lazy-load` or something? If I find time I'd like to make it easier for folks and our own engineers to use

**Comment by Toxicable** [comment] 2017-07-20 23:03
@josephliccini it would be possible to put this into a lib.
However since most of it is config you'd have to provide it would only contain`DynamicComponent` the rest of it you'd still have to provide yourself.

**Comment by josephliccini** [comment] 2017-07-20 23:33
got it. and this would work with webpack I assume? it may need some sort of loader to pick up the `provideRoutes` path `'./lazy/lazy.module#LazyModule'` and convert to a webpack module loading path (`require.ensure`, `import()`, etc.)? or would CLI do this automatically as it does for the router? (I don't use CLI right now)

**Comment by Toxicable** [comment] 2017-07-20 23:38
@josephliccini Yup it does require webpack config.
It does work fine with the CLI as i just tested it, although for it to work with a custom webpack config you need whatever plugin makes lazy loading with router config normally work(I only use the CLI so not familar with the webpack config for this), since it uses the exact same method the router uses.

**Comment by josephliccini** [comment] 2017-07-20 23:44
I think the `@ngtools/webpack` should work (that's what CLI uses internally), but we right now are not using that.  We plan on migrating to that soon though :)

Thanks again!!

If I find some free time I may publish your work above in a lib, and give you the credit for the work.  If anyone else wants to package this up into a lib just let me know so we don't duplicate work!

**Comment by alexzuza** [comment] 2017-07-21 04:34
https://stackoverflow.com/questions/40293240/how-to-manually-lazy-load-a-module/40293482#40293482
@josephliccini See example for angular-cli. It's the same what @Toxicable had offered

**Comment by josephliccini** [comment] 2017-07-21 21:22
@alexzuza sweet!  I actually have time to work on this next week so I will post back in here as the implementation is going along.

**Comment by bp117** [comment] 2017-07-22 17:14
@Toxicable does this solution works for shared modules as wellg

**Comment by josephliccini** [comment] 2017-07-22 17:41
I believe the primary goal of this is to load an HTML view lazily without the router. 

Do you mean to lazy load the shared module? This I don't exactly know how it would work because that means those components, pipes, and services would all be missing until the shared module was fetched and even then, I thought lazily loaded modules components, pipes, and services are scoped to that module and that modules imports.

Or are you asking can the lazy loaded module + view use components, pipes, and services from a shared module?
In this case I believe it's a yes since those components, pipes, and services are available at the root module, therefore available to all its children.

Correct me if I'm wrong though

**Comment by bp117** [comment] 2017-07-22 17:46
@josephliccini  i actually have requirement like i have to lazy load module of one application to another. the component in the lazy loaded module will be used at multiple places in the application. so i categorised it as shared module. is it doable?.

**Comment by bp117** [comment] 2017-07-22 17:49
@josephliccini i implemented the same in angularjs using ocLazyload . now we are migrating to angular 2/4 not sure how to implement the same.

**Comment by josephliccini** [comment] 2017-07-22 17:51
So <shared-component></shared-component> you want to be lazy, but in multiple places within the app? Meaning multiple views may have to lazy render this? It seems reasonable but I haven't given it a try yet.. Will investigate later this week

**Comment by bp117** [comment] 2017-07-22 17:52
yes

**Comment by mlc-mlapis** [comment] 2017-07-23 21:00
@bp117 ... the situation is a bit compilated than you think. It is necessary to see that each separate application can be tree skaked differently ... because each one can use different parts of Angular sources. And if it is true then you have to answer the question ... how to guarantee that all necessary parts of Angular will be already loaded when you will load the `module`? It probably leads to the situation when you have to load Angular modules separatelly ... not as parts of tree shaked apps.

**Comment by bp117** [comment] 2017-07-24 03:37
@mlc-mlapis Agree that this requirement is complicated, but want to understand if it is really doable. so lets take the scenario like i have two routes propertySummary, customerSummary, i have my shared module component used in these two routes like <app2loader></app2loader>. Now once the application 1  loads in the browser completely, and i go to either propertySummary or customerSummary then only load the app2 module component at the runtime. yes we have to take care of how skip this module at build  time / compile time. this all need to work with AOT as well. I am not sure if this can be achievable. Please share thoughts as our migration is highly dependent on this.

**Comment by mlc-mlapis** [comment] 2017-07-24 06:26
@bp117 ... if Angular necessary core modules will be loaded separatelly as UMD bundles you will have always all necessary things together and then you can theoretically use any number of parallel apps, dynamic libs ... modules and the only conditions would be the same Angular version cross all parts and the right build path how to extract Angular core things from apps' bundles.

Much more complicated situation would be if you want to build a module with some optimalization and cross tree shaking related to more apps ... for something like that there are not probably right tools today yet. They certainly will be there in future but it takes some time ...

**Comment by bp117** [comment] 2017-07-24 06:54
@mlc-mlapis does loading them as UMD bundles work with JIT and AOT and in lazy loaded way. I am don't have complete knowledge on this. appreciate if you can provide some references.

**Comment by josephliccini** [comment] 2017-07-25 01:02
https://github.com/josephliccini/ngx-lazy-view (WIP, needs lots of work, README updated, testing)

**Comment by bp117** [comment] 2017-07-25 04:28
@josephliccini is the above repo addresses lazy load of shared modules?

**Comment by aalbericio** [comment] 2017-07-27 15:31
Ok. I've made some PoC's and firt impressions are good, I have to admit.

As Fabian points, I don't see this workaround as a product cause it's mostly based in configuration.

In my PoC's, I have removed DynamicComponent (created an ModuleManager instead) and I have defined all Routes into AppModule, which makes it easier to maintain. 

I will make some futher review on the production build and comment my final thoughts.

Thanks

**Comment by josephliccini** [comment] 2017-07-31 18:35
I've updated my Repo (https://github.com/josephliccini/ngx-lazy-view), and we have a decent start of an API we would like to begin using and testing.  However, I don't know if this approach is dangerous / hacky to begin using in production, and then converting parts of our large enterprise app to this format. (since it is a non-standard way to lazy load Angular modules)  

Could someone from Angular team comment on this?  Also, I have seen this feature request a lot and if the pattern I've put together seems stable enough, Angular folks could divert feature requests for this  for this kind of Lazy Loading support towards the library instead.

**Comment by elliot-xu** [comment] 2017-08-01 11:00
Hi, i was thinking if i could know my lazy loaded module's path `'./lazy/lazy.module#LazyModule'` at run time and only at that time. And i don't want to put the path in any RouteModules or `provideRoutes`.
Could i get AOT version of the LazyModule ?

**Comment by aalbericio** [comment] 2017-08-01 11:05
I'm afraid, and as far as I know, you can't.

**Comment by jcludwig** [comment] 2018-01-06 01:10
It would be great if there was some way to do this that did not involve the router. We have some applications which do not use the router and I'd rather not pull in this dependency if not needed. Also, it seems a bit hacky to use the router as a general purpose lazy loading mechanism, in my case I just need to lazily load certain modules/components, not related to the current route.

The solution of just using import() does not appear to work with AOT.  Webpack produces a chunk for the lazily loaded module, but it does not appear that the AOT code has generated factories. This would be used for fairly large parts of the application, it would be nice to take advantage of AOT.

**Comment by Toxicable** [comment] 2018-01-06 01:36
@jcludwig You cant use `improt()` just yet, for now you can use `System.import()` which will do the same thing.
Here's an example that'll do what you want https://stackblitz.com/edit/angular-gitter-bdeyzm?file=app%2Fapp.component.ts

**Comment by jcludwig** [comment] 2018-01-08 18:48
@Toxicable, I'm not really clear on what this stackblitz.com site is doing behind the scenes. I tried exporting that project and it does not work locally for me. I get an error in the console like:
`ERROR Error: Uncaught (in promise): Error: Cannot find module 'app/lazy.ts'.
Error: Cannot find module 'app/lazy.ts'.
    at eval (eval at ../../../../../src/$$_lazy_route_resource lazy recursive (main.bundle.js:6), <anonymous>:5:9)`
The `ng build` command also does not seem to output any code with the lazy bundle. Any ideas?

This is my experience:
- Using `NgModuleLoaderFactory.load()` (or `SystemJsNgModuleLoaderFactory.load()`) does not cause Angular/Webpack to do anything special.
- Using `import()` (dynamic import expression, with `esnext` module type) or `System.import()` causes Webpack to generate a separate bundle for the lazily loaded module. However Angular AOT does not appear to "follow" this link, so the lazy code has no factories.

**Comment by mlc-mlapis** [comment] 2018-01-08 19:19
@jcludwig ... this certainly works ... where `constructor(..., private _loader: SystemJsNgModuleLoader)`:

```
this._loader.load(`${serverSetting.appDir}app/modules/dynamic/dynamic.module#DynamicModule`)
.then((_ngModuleFactory: NgModuleFactory<any>) => {
	const _ngModuleRef: NgModuleRef<any> = _ngModuleFactory.create(this._injector);
	const _cmpType: Type<any> = _ngModuleRef.instance.cmps.get('dynamic');
	const _cmpFactory: ComponentFactory<any> = _ngModuleRef
		.componentFactoryResolver
		.resolveComponentFactory(_cmpType);
	this._cmpRef = this.vc.createComponent(_cmpFactory, 0, this._injector, []);
});
```

**Comment by mattmcardle** [comment] 2018-01-15 14:43
@jcludwig changing @Toxicable's code in the AppComponent on line 16 to:
`this.loader.load('app/lazy#LazyModule')` seemed to fix it for me, i.e. remove the `.ts` in the path to the module.

**Comment by marcincichocki** [comment] 2018-01-15 17:04
@jcludwig On top of that what @mattmcardle mentioned, there is also need for adding dummy route for that module if you are using `@angular/cli` with default config(not ejected). This is because cli during compilation transform every `loadChildren` property of `ROUTES` token, to seperate chunk. Why it's working on stackblitz? I guess they ejected cli config and provided their own.

You can make it work with exported app from stackblitz with this code added to app.module:

```typescript
imports: [
  RouterModule.forRoot([
    {
      path: 'dummy-route',
      loadChildren: 'app/lazy.ts#LazyModule',
      // you can redirect users if they happen to go here
    }
  ])
]
```

One sad part is if your application is not using `@angular/router` then you will have useless dependency.

**Comment by jcludwig** [comment] 2018-01-18 06:17
@marcincichocki @mattmcardle, indeed I am trying to make this work without having to add a dummy route to the router (see my original comment). @mlc-mlapis, that does not work for me. Are you also using a dummy route? If not, can you provide a working repro?

I think I've been able to get a version of this working without using the router. Though so far it seems like I need to put components into the `bootstrap` section of the NgModule decorator in order for the factories to get included in the lazy module (rather than just specifying them in `declarations` or `exports`). My work in progress is [here](https://github.com/jcludwig/lazy-load-aot).

**Comment by mlc-mlapis** [comment] 2018-01-18 07:19
@jcludwig ... I am using just `ngc` to compile a lazy loaded module. With @marcincichocki we confirmed that `a dummy route` is certainly a way how to let CLI to compile it. I never heard or tried about `bootstrap` section way to get a lazy loaded module compiled. As I know CLI splits only by `loadChildren` routes.

**Comment by jcludwig** [comment] 2018-01-24 00:29
As the title of this issue is "Make lazy loading available outside the Router Module" I'd like to focus on developing a solution which does not require the router.

I have made some progress in getting this to work, which you can see in the github repo linked earlier.

**Comment by Toxicable** [comment] 2018-01-24 01:31
The issue isn't really around Angular itself, it's the tooling, meaning the CLI. The only way that the CLI and transitively Webpack can pickup lazy routes and therefore make chunks out of those modules is by looking at the `ROUTES` token, so we'll have to wait for them to change how it works there before we can make things better here.
As for right now the only solutions will be wrappers around the current methods

**Comment by marcincichocki** [comment] 2018-01-24 12:07
Related issue in cli repo: https://github.com/angular/angular-cli/issues/9343

**Comment by mnn** [comment] 2018-01-30 20:06
@Toxicable After almost verbatim copy of https://plnkr.co/edit/ZGC82G9u10EQFYFvvRMB?p=preview to our project, it crashes with `Cannot find module './lazy'.`.

I also tried [angular-dynamic](https://www.npmjs.com/package/@sharpangles/angular-dynamic) which failed with same error (tried a lot of possible paths [prefixing various amounts of `../`], just to be sure it's not a path issue).

We are not (yet) using AoT, we are using webpack with awesome-typescript-loader, angular2-template-loader and angular-router-loader. Ordinary lazy paths are working correctly.

Any idea what I am doing wrong?

**Comment by ismaproco** [comment] 2018-08-21 17:00
Thanks @Toxicable  your solution of in https://stackblitz.com/edit/angular-gitter-bdeyzm?file=app%2Fapp.component.ts 

Works great with Angular v6.1

**Comment by kirillgroshkov** [comment] 2019-06-11 18:23
So, what's the status as of now?

**Comment by josephliccini** [comment] 2019-06-11 19:04
I'd recommend checking out this package, it supports lazy loading outside of the router if you are keeping up to date with Angular / CLI updates (Should be supported in NG 7 and 8, not sure about 6)

https://www.npmjs.com/package/@herodevs/lazy-af

**Comment by infnada** [comment] 2019-06-25 15:07
But to load modules not known at compilling time we have to use `SystemJS.import()` which as my issue (https://stackoverflow.com/questions/56737261/lazyload-angular-module-from-url-with-singleton-services) even if a service is `providedIn: 'root'` they are not singletons. Some help will be appreciated.

**Comment by mlc-mlapis** [comment] 2019-06-25 15:40
@infnada … Do you have a working example where there is a service with `providedIn: 'root'` in such a lazy loaded module (and not mentioned in `providers`)? How does such a service instance look like? Is it still created under that lazy loaded module child injector?

**Comment by infnada** [comment] 2019-06-25 17:01
@mlc-mlapis sure https://github.com/infnada/angularLazyTest

`ModLazyA Service constructor` is called 2 times

```
mod-loader.service.ts:16 Loading Module ModLazyAModule
18:58:36.065 app.component.ts:40 Waiting before importing LazyModuleB
18:58:36.068 core.js:16829 Angular is running in the development mode. Call enableProdMode() to enable the production mode.
18:58:36.146 mod-lazy-a.service.ts:11 ModLazyA Service constructor
18:58:36.147 mod-lazy-a.module.ts:13 ModLazyA Module constructor
18:58:36.147 mod-lazy-a.module.ts:15 Pushing data from ModLazyA Module constructor
18:58:36.147 mod-lazy-a.module.ts:17 data ["some Data from ModLazyA Module constructor"]
18:58:36.148 mod-lazy-a.component.ts:16 ModLazyA Component constructor
18:58:36.150 mod-lazy-a.component.ts:20 Pushing data from ModLazyA Component ngOnInit
18:58:36.150 mod-lazy-a.component.ts:22 data (2) ["some Data from ModLazyA Module constructor", "some Data from ModLazyA Component ngOnInit"]
18:58:37.640 mod-loader.service.ts:16 Loading Module ModLazyBModule
18:58:37.664 mod-lazy-a.service.ts:11 ModLazyA Service constructor
18:58:37.665 mod-lazy-b.module.ts:15 ModLazyB Module constructor
18:58:37.665 mod-lazy-b.module.ts:17 Getting data from ModLazyB Module constructor
18:58:37.665 mod-lazy-b.module.ts:18 data []
18:58:37.666 mod-lazy-b.component.ts:16 ModLazyB Component constructor
18:58:37.667 mod-lazy-b.component.ts:20 Getting data from ModLazyB Component constructor
18:58:37.667 mod-lazy-b.component.ts:21 data []
```

**Comment by mlc-mlapis** [comment] 2019-06-25 17:26
@infnada ... what are those UMDs and how do you create them?

**Comment by infnada** [comment] 2019-06-25 17:41
> @infnada ... what are those UMDs and how do you create them? I can't see those services so ...

These umd files are angular libraries from inside the repo (https://github.com/infnada/angularLazyTest/tree/master/projects) generated by ng-packagr (https://github.com/infnada/angularLazyTest/tree/master/dist). Since i'm loading modules as "external" i'm just using loading these `dist/*.umd.js` files from github repo (https://github.com/infnada/angularLazyTest/blob/master/src/app/app.component.ts#L17). You can regenerate the `umd` files with `npm build-libs`

**Comment by mlc-mlapis** [comment] 2019-06-25 18:01
@infnada … OK. It looks strange then because in such case from where is `ModLazyAService` injected in `ModLazyBComponent` if it is not instantiated before. It should lead to an error. Also, you take a component factory, but I can't see where do you create that lazy module instance.

**Comment by doronsever** [comment] 2019-07-09 08:19
We have quite a large app and we have lots of inner modules (not only feature routable modules).
We have gotten to a point that our main.js file is around 20mb(!) (we are not working with AOT in dev) and it takes chrome around 10 seconds to load the page...

I've found this article: https://medium.com/wishtack/angular-lazy-loading-without-router-471166580c86

It actually works pretty well for me.
But I still have concerns...
The problem with 3rd parties that implements core logic is that no one can assure us that it will support future releases of Angular, especially Angular 9 which should ship Ivy and probably will change a lot in those areas.

IMO supporting lazy loading module is really important and should be in the core functionality.

**Comment by jayoungers** [comment] 2019-07-23 15:08
We have "Tool" and "Administration" like functionality available in a global menu that opens modals: most of the time users wouldn't access any of them, so having them always available locally is a waste.

I wouldn't be opposed to lazy-loading them through a named outlet, but I haven't had any luck lazy-loading modules that way (not sure if it's possible).

it would be nice if I could just do this:
```js
openMyAdminThingModal() {
  import('app/administration/my-admin-thing.module').then(m => m.AdminThingModule.magicOpenComponentLogic());
}
```

**Comment by filipesilva** [comment] 2019-07-23 16:56
@jayoungers if you're using Ivy you should be able to do that sort of thing as you expect, with no other complications on our side. You'll still have to hook it up somewhere (either in the router or manually) but it should just work without extra tooling. In Ivy this is easier because there are no .ngfactory files to work with. 

But if you're not using Ivy we need to find `import('app/administration/my-admin-thing.module').then(m => m.AdminThingModule)` and replace it with `import('app/administration/my-admin-thing.module.ngfactory').then(m => m.AdminThingModuleNgfactory)`. You can see the cases we cover in https://github.com/angular/angular-cli/blob/master/packages/ngtools/webpack/src/transformers/export_ngfactory_spec.ts.

**Comment by CSchulz** [comment] 2019-08-05 10:57
@filipesilva 
Thanks for your comment with the ngFactory, but this won't work if you are using your own library (mono repo style), right?
The default setup disables the generation of ngFactory in libraries. (Perhaps I haven't found it, but why is it the default setup?)
Can we reuse the generated ngFactory of a library to get it also working before Ivy?

**Comment by filipesilva** [comment] 2019-08-05 11:53
@CSchulz do you mean https://github.com/angular/angular-cli/issues/6373 but for local libraries? That has never worked with View Engine in the CLI, and it's not a problem with Ivy. Since we're making Ivy the default soon it feels like wasted effort to try and do it in View Engine. We looked at it once or twice but it always seemed like it would take a ton of work, and there was also a decent workaround in https://github.com/angular/angular-cli/issues/6373#issuecomment-453006158, so it was never a super high priority thing.

How ngfactories are generated, and what their content is, is tied into the compiler proper and might change between versions. It's not correct to ship the factories. Instead the compiler needs to generate them for the current full-program context.

**Comment by aaronmanela** [comment] 2020-02-07 16:39
are there any other ways of doing this in the future with ivy? supposedly it has some private methods that if they were public would allow it.

**Comment by connorlufei** [comment] 2020-03-13 08:58
It's really upset that lazy load of non-routable module is still unavailable officially. It's just on line in vue .

**Comment by filipesilva** [comment] 2020-03-13 09:12
@connorlufei that's been working for a while now. You can use `import()` directly since Angular 7 I think. The only snag was using it with `loadChildren`, but that's possible now too.

**Comment by KarlXOL** [comment] 2020-06-10 06:32
Lazy loading in Angular with Ivy is still a pain. Business application needs to be polluted with low-level code for loading, resolving factories, etc.
But even then a simple use case for using
- a directive(component) from a wishfully lazy loaded module 
- in a dialog is not working 
All samples I've found are just creating components to the current view which is not always needed or useful.

I can't understand why functionality which must be there (router) can't be be provided by angular.

I really hope Angular 10 (Ivy) fulfill some of the promises (or hopes) they have been made,

**Comment by KarlXOL** [comment] 2020-06-11 05:54
> 
> 
> I made another demo here https://plnkr.co/edit/ZGC82G9u10EQFYFvvRMB?p=preview
> it uses `NgModuleFactoryLoader` which Angular already provides for you to handle lazy loading modules
@Toxicable  
Actually this is the only solution for loading modules up to now (Angular 9/Ivy). The problem with this is as follows:
- a lot of overhead ( I'd say it pollutes an application with low-level code)
- application has to reflect module structure to some degree
- components always needs to be added to a view,
- this is not applicable when dynamic components/directes are loaded to provide features in a dialog (without routing)

Is there really no better solution and can we expect a fully baked loading feature in angular 10?

**Comment by nasreddineskandrani** [comment] 2020-06-25 22:21
@aaronmanela  @connorlufei
**check the solution 2 here, demonstrate how to do it with ivy.**
https://medium.com/front-end-tricks/dynamic-header-bars-and-or-contents-for-your-ivy-angular-app-56e1e7e3fc22

In this example i did it to lazy load a module for admin vs client header bars targeted but you can apply this to anything (in routing or not).

**Comment by jelbourn** [comment] 2020-10-09 21:18
Just closed a bunch of issues that @atscott and I believe are asking for the same general idea. Updated the title of this issue to reflect that underlying concept. #22243 and #13218 seem to be very similar, need to look into further whether they can be combined into this.

**Comment by KarlXOL** [comment] 2020-10-10 05:51
> **Solution 2 here, demonstrate how to do it with ivy.**
> https://medium.com/front-end-tricks/dynamic-header-bars-and-or-contents-for-your-ivy-angular-app-56e1e7e3fc22
> check: `headerbar-selector.component.ts` in the demo2
> 
Checked this approach a while ago.
This solution has its very pitfalls and limitations and is no solution for "feel-good" dynamic loading at runtime.
For example you have to care of component instantiation, parameter passing, etc...

**Comment by nasreddineskandrani** [comment] 2020-10-12 12:22
@KarlXOL it's only a solution and i do agree with you => Angular team should think about something more efficient and nice to achieve the desired result if possible.

**Comment by jstoppa** [comment] 2021-02-08 01:13
I'd just like to share s solution that worked for me for lazy loading components at runtime.  

My use case is that I've got an application that loads components programmatically using the Dynamics Component Loader, it was never architected to use the router and the number of components that can be loaded programmatically grew over time, they are loaded conditionally based on configuration/feature flags. The problem is that all these components are not lazy loaded and they ended up bloating the main bundle. 

I can’t really rearchitect the entire app to user the router which would require a lot of time effort so lazy load programmatically is key for my use case.

I initially tried loading these components like the below:
```typescript
ngAfterViewInit(): void {
    import("./path_to_my_component").then( c => {
      const componentFactory = this.componentFactoryResolver.resolveComponentFactory(
        c.SubComponent
      );
      this.lazyComponentRef.createComponent(componentFactory);
    });
  }
```
This works but it would bring other problems at runtime:
- Issues when using structural directives in my lazy loaded component (e.g. can't bind to 'ngIf' since it isn't a known property of ‘xyz') suggesting it needs the CommonModule
- Issues when referencing other components in my template saying it can’t find the component.

I searched and I found a few approaches like [this](https://github.com/angular/angular/issues/33654#issuecomment-663916022) or [this](https://github.com/angular/angular/issues/35759#issuecomment-601444856), which requires putting a module inside the component file and loading the module using the compiler. 

My approach was to reference the component and the module from the tsconfig.json’s paths via a proxy file that reference them…
```json
"paths": {
      "@SubComponent": [ "src/app/sub-component/public-api.ts"]
}
```
the public-api.ts would reference the component and the module 
```typescript
export * from "./sub.component";
export * from "./sub.module";
```

and then load the component using the reference in the tsconfig.json file.
```typescript
ngAfterViewInit(): void {
    import("@SubComponent").then( c => {
      const componentFactory = this.componentFactoryResolver.resolveComponentFactory(
        c.SubComponent
      );
      this.lazyComponentRef.createComponent(componentFactory);
    });
  }
```
The sub.module.ts file will contain the modules that I need to solve the errors I was getting. 

This approach worked really well for me, I had to do little refactoring of my application and managed to reduce the main bundle size by 25% 😊

I hope it helps someone else

**Comment by petebacondarwin** [comment] 2021-11-26 16:30
This should be made possible by the "standalone components" project.

**Comment by pkozlowski-opensource** [comment] 2022-06-30 06:12
Angular's standalone components implemented in Angular v14 and other changes we've been doing around `ComponentFactoryResolver` greatly improve the component-level, lazy-loading story. 

As an example, lazy-loading a standalone component and rendering it boils down to:

```typescript
@Component({...})
export class LazyLoadingComponent {
     constructor(private _vcRef: ViewContainerRef) {}
     
     someAction() {
         import('path/to/a/file').then((m) => this._vcRef.createComponent(m.MyLazyComponent));
     }
}
```

With the the  [RFC: Standalone components, directives and pipes - making Angular's NgModules optional](https://github.com/angular/angular/discussions/43784) implemented we can consider that the stated issue is solved!

> In summary, the feature request is: make the "lazy loading" feature available to developers outside the RouterModule since this module is optional but the feature should still be available.
Of course this should output AOT compatible chunks, etc, just like the RouterModule internally does.

**Closed by pkozlowski-opensource** 2022-06-30 06:12 UTC
Labels: feature, comp: core, under consideration
