### ISSUE TITLE
ng-content API docs are missing

### ISSUE THREAD

**Issue by adrianlafond** [angular/angular#38921] opened 2020-09-21 17:00 UTC
# 📚 Docs or angular.io bug report

### Description

No API page for `ng-content` exists. `ng-content` is mentioned on several pages, almost in passing (eg, https://angular.io/guide/lifecycle-hooks), but searching brings up no dedicated page with API info. I have found elsewhere online that "select" is a a valid and very useful attribute, but it's a bit concerning that I cannot find this info on angular.io itself. Are there any other attributes it accepts?

If it does exist and I missed it (I hope not), then the search results would be another issue.

++ @StephenFluin @aikidave 

btw, hi guys!

## 🔬 Minimal Reproduction

Visit https://angular.io/, search for "ng-content".

### What's the affected URL?**
All of https://angular.io/

**Comment by aikidave** [comment] 2020-09-22 20:43
Hiya, @adrianlafond! Thanks for filing this.

I've added it to our priority list so we can look into addressing this gap in our content!

**Comment by crutchcorn** [comment] 2020-09-24 07:33
Is this something that I can take on? I'd love to be able to make this my first contribution to Angular

**Comment by aikidave** [comment] 2021-05-25 21:44
Hey @crutchcorn! Thanks! I'm closing this issue because it's a duplicate of #41273 . But if you'd like to help as we resolve this issue, let me know!

**Closed by aikidave** 2021-05-25 21:44 UTC
Labels: P4, comp: docs, feature, freq2: medium, risk: low
