### ISSUE TITLE
Error triggered on unexpected situation

### ISSUE THREAD

**Issue by MatonAnthony** [angular/angular#16839] opened 2017-05-17 08:37 UTC
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

The following code 
```typescript
<input class="switch-input"
                                           type="checkbox"
                                           id="{{ arg.id }}"
                                           name="isActive"
                                           [(ngModel)]="p.active"
                                    >
```
triggers the following Error
```
ERROR Error: If ngModel is used within a form tag, either the name attribute must be set or the form
      control must be defined as 'standalone' in ngModelOptions.

      Example 1: <input [(ngModel)]="person.firstName" name="first">
      Example 2: <input [(ngModel)]="person.firstName" [ngModelOptions]="{standalone: true}">
```

**Expected behavior**

No error should be triggered.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

If this is abnormal behavior then it needs a patch and if it's normal the error message is unclear 
and would require to be more precise or more documented.

**Please tell us about your environment:**

OS : OS X Sierra
Package Manager : NPM
HTTP Server : ng serve

* **Angular version:** 
@angular/core": "^4.0.3"

* **Browser:** 
Chrome 57
Firefox 54

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =   v6.9.2

PS : I have no idea how to name this bug, I would happily change the name for a better one.

**Comment by tytskyi** [comment] 2017-05-17 08:51
@MatonAnthony but error message says you the problem that if you use `ngModel` inside form then you need to make one of two things: 1) add `name` attribute, 2) use `[ngModelOptions]="{standalone: true}"` to control

Could you point what do you think is "unclear and would require to be more precise or more documented"?

**Comment by MatonAnthony** [comment] 2017-05-17 08:53
In the example I put the name attribute and the error is still triggered.

So either, the message is incomplete or there is a bug somewhere.

**Comment by alexzuza** [comment] 2017-05-17 09:12
Please create a minimal working example to reproduce it

**Comment by godbasin** [comment] 2017-05-17 09:13
Maybe you miss another input with `ngModel` without `name` attribute?

**Comment by pkozlowski-opensource** [comment] 2017-05-17 09:29
Yes, we need a minimal and live reproduce scenario in a plunker, otherwise it is not actionable.

**Comment by kara** [comment] 2017-09-01 23:47
Since we haven't been able to reproduce for a few months, closing.

**Closed by kara** 2017-09-01 23:47 UTC
Labels: comp: forms, state: Need repro
