### ISSUE TITLE
FormGroup should have (optional) type checks on members

### ISSUE THREAD

**Issue by K0IN** [angular/angular#44661] opened 2022-01-07 22:50 UTC
### Which @angular/* package(s) are relevant/releated to the feature request?

forms

### Description

[FormBuilder.group](https://github.com/angular/angular/blob/13d5f64f3986c5ce98196114a5709c02ad3d6fd9/packages/forms/src/form_builder.ts#L81) returns `FormGroup` with no knowledge of the child controls (since they can be dynamically added). 

I find this bad since we cannot find out (statically), if a control is present on the group. 

We mostly (99% of the time) have forms with static amount of controls in a form.

So it would be really nice to have a generic formgroup to index the controls by name and have proper type checking.

imagine following code:

```
interface MySendData {
  a: string, 
  b: string
}

const form = new FormGroup({ a: "", b: "" } as MySendData); // imagine we would check the interface implementation 

[...]

form.controls.a.reset(); // works fine
form.controls.x.reset(); // ops we cant find this statically
```

Yes, you can of cause check if the property exists, but it would be really delightful to see where you need to change the code if you change the interface (see example).

Workaround: 

manually overwrite the controls property, and use keyof my interface to index the controls

### Proposed solution

Add a generic type to `FormGroup` (to indexes obj.controls), so we can statically see the available control names.

### Alternatives considered

Add a new `FormGroup` (like a frozen `FormGroup`) type that does not allow dynamic adding or removing of controls

**Comment by atscott** [comment] 2022-01-08 00:09
Duplicate of https://github.com/angular/angular/issues/13721. Typed forms are actively being developed. The RFC is here: https://github.com/angular/angular/discussions/44513

**Closed by atscott** 2022-01-08 00:09 UTC
