### ISSUE TITLE
Add "request.args: Record<string, any>" to HttpRequest as arbitrary context to enhance interceptor logic

### ISSUE THREAD

**Issue by alshdavid** [angular/angular#29208] opened 2019-03-10 02:36 UTC
I am working with the HttpClient and Angular's Http Interceptors and am having difficulty passing in custom context to aid in logic.

In the following example, I have a URL stored as a variable - presumably set in then environment.
I want to replace the `:id` with the correct id for the request

```typescript
const url = 'http://place.com/:id/thing'

doRequest() {
    const id = 'something'
    return this.http.get(url)
}
```

While, in this case the solution would be to simply modify the value beforehand using regex 

```typescript
doRequest() {
    const id = 'something'
    const newUrl = url.replace(/pattern/, id)
    return this.http.get(newUrl)
}
```

What would be cool is leveraging interceptors to do said task. EG

```typescript
const url = 'http://place.com/:id/thing'

...

doRequest() {
    const urlParams = {
        id: 'something'
    }

    return this.http.get(url, { args: { urlParams } })
}
```

```typescript
class AddParamsToUrlInterceptor implements HttpInterceptor {
    intercept(request: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
        if (request.args.urlParams !== undefined) {
            let newUrl = ''

            ... find and replace args in url

            request = request.clone({
                url: newUrl
            });

        }
        return next.handle(request);
    }
} 
```

This issue is, `HttpRequest` does not allow us to pass an arbitrary context.

**Comment by alxhub** [comment] 2019-04-23 22:49
Closing as a duplicate of #18155. I agree this is sorely needed in the API, and as soon as I have time to properly look at the design/implementation (specifically, whether such a context should be immutable or mutable), I'd love to see it done.

**Closed by alxhub** 2019-04-23 22:49 UTC
Labels: comp: common/http
