### ISSUE TITLE
NoOpAnimationDriver error with ng-xi18n

### ISSUE THREAD

**Issue by sumigoma** [angular/angular#13624] opened 2016-12-22 00:37 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
ng-xi18n with angular 2.4.0 fails with exception `Error: Error encountered resolving symbol values statically. Calling function 'NoOpAnimationDriver'`. Builds fine with ng build --prod or ng serve.

**Expected behavior**
Extract xlf without errors

**Please tell us about your environment:**
angular-cli: 1.0.0-beta.24
node: 6.2.2
os: win32 x64

* **Angular version:** 2.4.0

* **Browser:** n/a
 
* **Language:** TypeScript 2.0.3

* **Node (for AoT issues):** `node --version` =   node: 6.2.2

**Comment by matsko** [comment] 2016-12-22 04:35
@chuckjaz @tbosch wasn't this resolved last week?

cc @hansl

**Comment by intellix** [comment] 2016-12-22 10:03
I had this and a range of errors last night. I see that you're using the cli @sumigoma 
Try running the clean install instructions from angular-cli, that fixed it for me: https://github.com/angular/angular-cli#updating-angular-cli

Bizarrely there are a few node_module cache issues and nobody knows why :)

**Comment by timosalm** [comment] 2016-12-22 10:23
Same error here - I followed the angular-cli clean install instructions.

**Comment by Hyune-kel** [comment] 2016-12-22 10:31
Same error for me.

- **angular-cli:** 1.0.0-beta.24
- **node:** 5.9.0
- **os:** win32 x64
- **Angular:** 2.3.1
- **TypeScript:** 2.0.3

I'll try to update to node 6.9.2 and after the angular-cli clean install instructions.

**Comment by npx** [comment] 2016-12-22 15:43
Ran into this issue on beta.22 updated as follows which resolved the issue:
```
$ ng version
angular-cli: 1.0.0-beta.24
node: 4.2.4
os: darwin x64
@angular/common: 2.4.1
@angular/compiler: 2.4.1
@angular/core: 2.4.1
@angular/forms: 2.4.1
@angular/http: 2.4.1
@angular/material: 2.0.0-alpha.11-3
@angular/platform-browser: 2.4.1
@angular/platform-browser-dynamic: 2.4.1
@angular/router: 3.2.3
@angular/compiler-cli: 2.4.1
```

**Comment by chuckjaz** [comment] 2016-12-22 17:16
Can you make sure the `BrowserTestingModule` is *not* include in the project being compiled?

`BrowserTestingModule` is not intended to be used by AOT and will generate this error because it includes: ` {provide: AnimationDriver, useValue: AnimationDriver.NOOP}` for which`NOOP` is a reference to `new NoOpAnimationDriver();` which is the expression the error is referring to.

**Comment by tbosch** [comment] 2016-12-22 19:43
Note that the BrowserTestingModule will be compiled, leading to this error,
as soon at least one test that uses the TestBed is included in the AoT
compilation.

You can exclude files from the compilation by setting the `files` property
in the `tsconfig.json`, or using `exclude`.

**Comment by timosalm** [comment] 2016-12-22 20:36
Excluding the "test.ts" file in tsconfig.json resolved the issue for me.

`  
...
"exclude": [
    "test.ts"
  ],
"angularCompilerOptions": {
    "genDir": "../locale"
 }
...
`

**Comment by rexthk** [comment] 2016-12-23 07:01
@timosalm 
It doesn't work for me. It seems like my CLI completely ignore this line during running ng-xi18n.

**Comment by rexthk** [comment] 2016-12-23 07:32
Here is my solution:
I copied tsconfig.json to my root. And then include the lib.es6.d.ts:

"files": [
     "node_modules/typescript/lib/lib.es6.d.ts"
   ]

p.s. I am targeting es5.

**Comment by timosalm** [comment] 2016-12-23 08:15
@rexthk if the tsconfig.json TypeScript configuration file is located somewhere other than in the root folder, you must identify the path to it with the -p option:
`./node_modules/.bin/ng-xi18n -p src/tsconfig.json`

**Comment by rexthk** [comment] 2016-12-23 11:15
@timosalm You are right. By default Angular CLI puts tsconfig.ts inside src folder. 

Anyway, it seems simply excluding test.ts doesnt work in my case. Including es6 just solve all my dependency problem too :)

**Comment by sumigoma** [comment] 2016-12-23 18:08
@chuckjaz @tbosch excluding test.ts in tsconfig.json indeed appears to work. Will there be any repercussions, like on vscode intellisense in the spec files? (It looks like intellisense is working fine... but I thought vscode uses tsconfig.json)

@hansl will this be angular-cli's recommended approach?

**Comment by chuckjaz** [comment] 2017-01-03 18:11
@sumigoma Excluding test.ts will cause it to be in a separate project from the rest of the application. To avoid this I recommend creating a tsconfig-build.json that has the AOT options (specifically excluding test.ts) and leave tsconfig.json to be the configuration you want editors to use.

**Comment by sumigoma** [comment] 2017-01-04 20:52
@chuckjaz @hansl Makes sense to me, but if this is the recommended approach it seems like it should be adopted by angular-cli.

**Comment by hansl** [comment] 2017-01-04 21:17
Angular-CLI has its own way of dealing with `tsconfig.json`. We're still evaluating how we want to approach interop with other command line tools, since we don't want to have multiple tsconfig files in the same projects.

Closing this as solved for now. If you disagree let us know.

**Closed by hansl** 2017-01-04 21:17 UTC

**Comment by stephanrauh** [comment] 2017-01-06 14:11
Just for the reference: The workaround solving the problem consists of two steps:

- target ES6. ES5 won't work.
- exclude the file "tests.ts" in your ts-config.json:
```JavaScript
{
  "exclude": [ "test.ts" ],
  "compilerOptions": {
    "baseUrl": "",
    ...
```

**Comment by fx90** [comment] 2017-01-25 12:38
@hansl 
I am still having this problem even with the suggested workaraound of excluding "tests.ts". Please advise.

Command:
```
"./node_modules/.bin/ng-xi18n" -p tsconfig.json
```

Error message: 
```
Error: Error encountered resolving symbol values statically. Calling function 'NoOpAnimationDriver', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AnimationDriver.NOOP in C
:/Users/Fabian/Workspace/sportify/frontend/node_modules/@angular/platform-browser/src/dom/animation_driver.d.ts, resolving symbol BrowserTestingModule in C:/Users/Fabian/Workspace/sportify/frontend/node_modules/@angular/platform-browser/testing/browser.d.ts, re
solving symbol BrowserTestingModule in C:/Users/Fabian/Workspace/sportify/frontend/node_modules/@angular/platform-browser/testing/browser.d.ts
    at simplifyInContext (C:\Users\Fabian\Workspace\sportify\frontend\node_modules\@angular\compiler\bundles\compiler.umd.js:25569:27)
...
```

tsconfig.json:
```
{
  "compilerOptions": {
    "target": "es6",
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false
  },
  "exclude": [ "test.ts" ],
  "angularCompilerOptions": { "genDir": "i18n" }
}
```

* Angular 2.4.4
* angular-cli: 1.0.0-beta.26
* Typescript 2.0.10
* Windows 10 x64
* Node 6.9.1

**Comment by dalibor983** [comment] 2017-01-28 17:19
When you exclude __test.ts__ in __tsconfig.json__ `ng lint` does not work anymore :)

**Comment by rahul-winner** [comment] 2017-02-03 18:12
I was getting following error on running **ng-xi18n**
_Error encountered resolving symbol values statically. Calling function 'NoOpAnimationDriver', function calls are not supported._ 

The error has gone once I added **exclude": [ "test.ts" ]**, however now I am getting errors related to test cases likewise "Cannot find name 'expect'.", "Cannot find name 'describe'."...

Could anyone please help me resolving this problem.

**Comment by danielritter** [comment] 2017-02-06 13:40
I do have the same error.

**Comment by a3eric** [comment] 2017-02-08 23:22
Still getting this issue even with all the recommended changes.

**Comment by MeMeMax** [comment] 2017-02-09 14:51
Notice that you have to be in the root of your application folder and if needed pass -p src/tsconfig.json depending on where your tsconfig file is. That worked for me.

**Comment by MJuma** [comment] 2017-02-09 19:14
Was getting this error as well. I'm using Angular CLI and it turned out to be a wallabyjs config file of mine that was causing this NoOpAnimationDriver error to occur. I added it to my tsconfig excludes and Angular CLI started to build prod and aot builds just fine for me afterwards.

**Comment by yanyixing** [comment] 2017-02-20 07:40
when I exclude the test.ts file, it works
but don't know why.

**Comment by borislemke** [comment] 2017-02-20 15:08
I'm getting this error but as far as I can remember I'm not trying to use i18 in any part of my project. Is this coming from Material 2? Are there any commonly known modules that raise this issue? I can't start `ngc` nor `ng build --prod` or `ng build --aot`

**Comment by peteralbert** [comment] 2017-02-23 07:49
In case you're using wallabyJs, also exclude wallabyTest.ts in your tsconfig.json:

```
 "exclude": [ "test.ts", "wallabyTest.ts" ],
```

**Comment by mbrookson** [comment] 2017-02-24 11:36
Following people's recommendation I can confirm I was able to get around this issue by

1. Adding `"exclude": [ "test.ts" ]` to the `tsconfig.json` file

2. Specifying the `tsconfig.json` path in the command: `"./node_modules/.bin/ng-xi18n" -p src/tsconfig.json` as this is where the angular-cli added mine by default

3. Changing all scss imports to (for example) `@import "filename.scss"` WITH the filename extension

4. Fixing any errors as they came up, tended to be with `.spec.ts` files where I am have accidentally missed things. Can still run `ng-serve` but the `i18n` command needed everything fixed

**Comment by artdias90** [comment] 2017-04-04 13:36
I'm still having issues with `"@angular/compiler-cli": "^2.4.10"`. Tried all from above but no success.
