### ISSUE TITLE
MODULE_INITIALIZER when we do module federation

### ISSUE THREAD

**Issue by jean13360** [angular/angular#44717] opened 2022-01-14 13:06 UTC
### Which @angular/* package(s) are relevant/releated to the feature request?

core

### Description

Hi ,

 When i do Module Federation , and we need to load dynamic value at start.
But for angular, we have only APP_INITIALIZER when it's call at main application  init.

But when we load a remote module ( create by module federation), we can use APP_INITIALIZER, just the main application is initialized and the remote module no .

### Proposed solution

Have a MODULE_INITIALIZER when we load a remote module?
i do : 

export class RemoteEntryModule {  
  constructor() { 
    this.getSettings();    
  }
 
 
 
  public getSettings() {

    if (environment.production) {
      const oReq = new XMLHttpRequest();
      const configUrl = `assets/app.config.json`;
      oReq.open("get", configUrl, false);
      
      oReq.onreadystatechange = function() {
        if (oReq.readyState === 4) { 
          ConfigRemoteEntry.settings = oReq.response; 
        }
      }
      oReq.send();   
    }  
  }
}
 

But is not clean :'(

### Alternatives considered

don't know yet ...

**Comment by JoostK** [comment] 2022-01-14 15:43
I am going to close this as a duplicate of #17606.

I don't know how/where the NgModule is instantiated, but it should be reasonably easy to await a set of promises that are provided as a multi-provider.

**Closed by JoostK** 2022-01-14 15:43 UTC
