### ISSUE TITLE
Href missing in balise a when using RouterLink and ngIf

### ISSUE THREAD

**Issue by ludonoel1** [angular/angular#58475] opened 2024-11-01 20:48 UTC
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

Yes

### Description

Hello,
I have a simple standalone component, and I migrated my app from Angular 15 to Angular 16. 
But now, every RouterLink in balise <a> (rendered as text) has no click effect if it is inside ngIf, like this:

`<div>
        Listings provided by 
        <div class="bbs"></div> 
        Advertise 
        <a  *ngIf="true" routerLink='/app/sub_path'>here.</a>
    </div>`

However, this code is perfectly working 👍: 
` <a  routerLink='/biz/advertise'>here.</a>`

I have imported NgIf, CommonModule and routerModule.

When I use the Chrome debugger console, I see that the first one has no 'href' whereas the second has one..

Do you have an idea?

### Please provide the exception or error you saw

no error

### Please provide the environment you discovered this bug in (run `ng version`)

Angular CLI: 16.2.16
Node: 20.17.0 (Unsupported)
Package Manager: npm 10.8.2
OS: win32 x64

Angular: 16.2.12
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1602.16
@angular-devkit/build-angular   16.2.16
@angular-devkit/core            16.2.16
@angular-devkit/schematics      16.2.16
@angular/cdk                    16.2.14
@angular/cli                    16.2.16
@angular/google-maps            16.2.10
@angular/material               16.2.14
@nguniversal/builders           16.2.0
@nguniversal/express-engine     16.2.0
@schematics/angular             16.2.16
ng-packagr                      16.2.3
rxjs                            7.8.1
typescript                      5.1.6
zone.js                         0.13.3

**Comment by JeanMeche** [comment] 2024-11-01 22:31
Hi, could you provide a stackblitz reproduction  of your issue ? Thank you.

**Comment by JeanMeche** [comment] 2024-11-01 22:34
Hi, could you please provide a stacbklitz reproduction of your issue. Thank you.

**Comment by alxhub** [comment] 2024-11-02 17:24
(and note: please provide a reproduction using a supported version of Angular - v18 (current), v19 (next), or v17 (lts)

**Comment by JoostK** [comment] 2024-11-13 15:40
Closing due to missing reproduction.

**Closed by JoostK** 2024-11-13 15:40 UTC
Labels: needs reproduction, area: router
