### ISSUE TITLE
Cannot use arrow function for module lazy loading

### ISSUE THREAD

**Issue by joashmusyoka** [angular/angular#16923] opened 2017-05-22 11:57 UTC
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Consider the following minimal router set up

```const appRoutes: Routes = [
{
        path: '', component: Component1,
        children: [
            { path: 'route1', loadChildren:() =>  Module1  },
        ]
    }
]
```
The JIT compiler fails at **angular/core/bundles/core.umd.js line 2049** because arrow functions do not have the prototype property. 

Changing the lazy loading to use the es5 function syntax solves the problem

**Expected behavior**
Should be able to use es6 arrow function for lazy loading a module

**Minimal reproduction of the problem with instructions**

- Create an angular project using version 2.4.10
- Add a router config that includes loadChildren using arrow function
- Run ```npm start```

**What is the motivation / use case for changing the behavior?**
Since angular supports es6, we should be allowed to take advantage of arrow function definition for lazy loading

 **Please tell us about your environment:**
- OS - Windows 8
- IDE: Visual Stidio Code
- Package Manager: npm
- HTTP server: lite-sever(dev)

 **Angular version:** 2.4.10

**Browser:** [ Chrome Latest ]
 
**Language:** [TypeScript]

**Node (for AoT issues):** = 4.2.6

**Comment by chuckjaz** [comment] 2017-05-22 20:16
Thanks for reporting this issue. However this issue is a duplicate of an existing issue #13614. Please subscribe to that issue for future updates.

**Closed by chuckjaz** 2017-05-22 20:16 UTC
