### ISSUE TITLE
Bind to Observable/Promise directly in HostBinding

### ISSUE THREAD

**Issue by jzabinski-dolios** [angular/angular#46305] opened 2022-06-08 15:30 UTC
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

Sometimes, I want to bind an element attribute to the template for some reason. At least 90% of the time, this is so that I can describe CSS for mobile vs desktop differently. I can bind the element attribute to individual elements if necessary, but usually, multiple elements in a component need to react to changes in screen size, so I like to bind it at the `:host` level, and drill down to affected elements in CSS.

If I want to bind an element attribute to an Observable, I have to follow 3 steps:

1. Do the async work somewhere.
```
@Injectable()
export class SomeService {
  asyncProduct$ = new BehaviorSubject('foo');
}
```
2. Build access to the Observable in component logic.
```
@Component({selector: 'app-thing'})
export class SomeComponent {
productAccess$ = this.svc.asyncProduct$.asObservable();
constructor(private svc: SomeService) {
}
}
```
3. Bind the element attribute(s) to the access built in step 2.
```
<div [attr.product]="productAccess$ | async"></div>
```

Or an alternative, used more often:
1. Do the async work somewhere. (Same as above.)
```
@Injectable()
export class SomeService {
  asyncProduct$ = new BehaviorSubject('foo');
}
```

2. Build access to the Observable in component logic, this time by managing a Subscription.
```
@Component({selector: 'app-thing'})
export class SomeComponent implements OnInit, OnDestroy {
  subscriptions = new Subscription();
  productAccess: ProductAccess;
  constructor(private svc: SomeService) {}

  ngOnInit(): void {
    this.aubscriptions.add(
      this.svc.asyncProduct$.subscribe(prod => this.productAccess = prod)
    );
  }

  ngOnDestroy(): void {
    this.subscriptions.unsubscribe();
  }
}
```

3. Bind the attribute to the template using @HostBinding syntax. Same code as step 2, but just add:
`@HostBinding('attr.product') productAccess: ProductAccess`

### Proposed solution

It would be cleaner if `@HostBinding()` could manage subscription to an Observable. Then I wouldn't have to maintain logic in the template at all.
```
@Component({selector: 'app-thing'})
export class SomeComponent {
  @HostBinding('attr.prod' ) productAccess$: ProductAccess = this.svc.productAccess$.asObservable();
  constructor(private svc: SomeService) {}
}
```

### Alternatives considered

I know of no other alternatives.

**Comment by pkozlowski-opensource** [comment] 2022-06-08 16:03
Duplicate of #19483

**Closed by pkozlowski-opensource** 2022-06-08 16:03 UTC
