### ISSUE TITLE
Allow omitting `templateUrl` if your template file resides in the same directory

### ISSUE THREAD

**Issue by kegluneq** [angular/angular#5811] opened 2015-12-10 20:53 UTC
Suggested by @munificent
/cc @yjbanov , @tbosch, @vsavkin 

So in this situation `templateUrl` could be omitted:

button.dart
```dart
@Component(
  selector: '[my-button]',
  templateUrl: 'button.html'
)
MyButton {}
```

**Comment by yjbanov** [comment] 2015-12-11 04:57
This can be easily implemented in the transformer. Not sure about mirrors. Aren't we going to hit the same old problem with part files where we can't tell which file the class is defined in?

**Comment by munificent** [comment] 2015-12-14 17:47
> Aren't we going to hit the same old problem with part files where we can't tell which file the class is defined in?

Personally, I would be fine with this just not being supported in part files. Parts are lame anyway.

**Comment by nosachamos** [comment] 2015-12-15 22:18
+1 to this feature

**Comment by pkozlowski-opensource** [comment] 2016-07-30 07:28
Duplicate of #5183

**Closed by pkozlowski-opensource** 2016-07-30 07:28 UTC
Labels: state: Needs Design, type: feature
