### ISSUE TITLE
Sometimes errors don't disappear until you re-open the file html/ts files

### ISSUE THREAD

**Issue by waelkdouh** [angular/angular#22486] opened 2018-02-28 05:04 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

The extension requires closing html and ts files and reopening them to update the state of the errors in the file? This happens with Angular projects created with the CLI. Extremely counter productive.

## Expected behavior

When error is fixed the red squiggly should disappear. 

## Minimal reproduction of the problem with instructions

If I have an error in the app component ts file stating that it has not been including in any angular module then modifying the app module ts file should cause the red squiggly to disappear from the app component ts file. Right now it requires you to close the app component file and reopen it which is completely confusing and counter productive.  
## Environment

<pre><code>
Angular version: 5.2.5

Browser:
- [x] Chrome (desktop) version 64.0.3282.186
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

 
For Tooling issues:
- Node version: 5.6.0  
- Platform: Windows 

Gif that shows the error in action can be found here:
https://user-images.githubusercontent.com/10424576/36770925-396d1a14-1c1b-11e8-8e28-5da729c347c7.gif

**Comment by Yerkon** [comment] 2018-02-28 12:02
Hi @waelkdouh,
You mean template error? Looks like to this issue: #22236

**Comment by waelkdouh** [comment] 2018-03-01 16:05
@Yerkon The same issue happens inside .ts files as well. For example if I forget to add a newly created component under the @ngmodule I will get an error inside the component's file informing me that the component hasn't been included in any angular module. If I close the component's .ts file and reopen it then the error will dissappear. Its as if the extension fails to monitor changes without the step of closing and reopening the file which is confusing as users may think that the error still exists.

**Comment by Yerkon** [comment] 2018-03-02 06:22
@waelkdouh, It's definitely **Language Service** bug. I have tested your case with disabled/enabled LS.

**Comment by waelkdouh** [comment] 2018-03-02 16:32
@Yerkon Agreed. I hope the team is working on fixing this bug as its a major one if you ask me.

**Comment by JoostK** [comment] 2021-05-14 11:40
I can't reproduce this with the Ivy language service, so I'll go ahead and close this. If this continues to be a problem for someone, please open a new issue.

**Closed by JoostK** 2021-05-14 11:40 UTC
Labels: P3, comp: language-service, freq2: medium, type: bug/fix
