### ISSUE TITLE
feature : be able to use remotely hosted module 

### ISSUE THREAD

**Issue by sebastienminne** [angular/angular#19376] opened 2017-09-25 12:42 UTC
## I'm submitting a ...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[X] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

At the moment it seems impossible to use a remote module/component, by remote I mean an angular module compiled and deployed on a webserver as an UMD module for instance. 

## Expected behavior

To have a fully "modularized" angular app, I need to be able to use remote component not known at compile time. This would allow us to build a plugins system for apps and deploy only small parts of bigger app (as we would do for a micro-service architecture)

## Minimal reproduction of the problem with instructions

Create any simple component and try to get it and use it in a remote context.

## What is the motivation / use case for changing the behavior?

It is needed to build true plugins system and is one step forward module approach.

## Environment

<pre><code>
Angular version: 4.x.x

 </code></pre>

**Comment by trotyl** [comment] 2017-09-25 14:01
Duplicate of https://github.com/angular/angular/issues/19264, and it's a support request.

**Closed** 2017-09-28 17:08 UTC
