### ISSUE TITLE
Angular element's input bindings are not available until a queued task in ngAfterViewInit()

### ISSUE THREAD

**Issue by HazzMan2409** [angular/angular#49833] opened 2023-04-13 17:15 UTC
### Which @angular/* package(s) are the source of the bug?

elements

### Is this a regression?

No

### Description

Exactly what the title states... when rendering an Angular Element in a template the input bindings are not available until a queued task in ngAfterViewInit(). See the linked minimal reproduction.

Note that this does not happen if you render the Angular Element via a document.createElement().

I know that in this minimal reproduction you would be better off rendering the element as a component to get template type checking, but I have a scenario where the Angular Element is defined by another Angular app so this is not possible.

### Please provide a link to a minimal reproduction of the bug

https://github.com/HazzMan2409/ng-elements-input-issue

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.2.6
Node: 14.20.1
Package Manager: npm 6.14.17
OS: darwin x64

Angular: 15.2.7
... animations, common, compiler, compiler-cli, core, elements
... forms, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1502.6
@angular-devkit/build-angular   15.2.6
@angular-devkit/core            15.2.6
@angular-devkit/schematics      15.2.6
@angular/cli                    15.2.6
@schematics/angular             15.2.6
rxjs                            7.8.0
typescript                      4.9.5
```

**Comment by JeanMeche** [comment] 2023-04-13 22:41
Hi, I believe it''s a dupe of what was repported in #48303. 

Can you confirm ?

**Comment by alan-agius4** [comment] 2023-04-18 18:43
Duplicate of https://github.com/angular/angular/issues/48303

**Closed by alan-agius4** 2023-04-18 18:43 UTC
Labels: area: elements
