### ISSUE TITLE
css file is missing randomly (service worker reject promise)

### ISSUE THREAD

**Issue by alexthelion** [angular/angular#30778] opened 2019-05-31 10:14 UTC
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/service-worker

### Is this a regression?

Yes, the previous version in which I noticed this bug was present was: 7.1.4

### Description

My app is randomly not loading main css file.
I have clients saying this could happen on the first opening, even if they are online.

## 🔬 Minimal Reproduction
I created a project for the bug reproduction: https://github.com/alexthelion/pwa-demo

Steps for reproduction:
Link for the hosted demo app: https://fir-918f4.firebaseapp.com

1. Create a shortcut on your desktop.
2. Open the app once, and then go offline.
3. Close and open the app until you will get the error.

Not normal - css file is missing, loaded as "(index)"
![image](https://user-images.githubusercontent.com/6614196/58699157-7ce90800-83a5-11e9-9f58-75d52dcfda0e.png)

Normal (css file loaded):
![image](https://user-images.githubusercontent.com/6614196/58699210-9722e600-83a5-11e9-94e3-4b59f6c0390e.png)

## 🔥 Exception or Error

![image](https://user-images.githubusercontent.com/6614196/58699085-5aef8580-83a5-11e9-8ed4-5343e7bca0e8.png)

<pre><code>
The FetchEvent for "https://fir-918f4.firebaseapp.com/styles.14ad77ffc4bc34de71b8.css" resulted in a network error response: the promise was rejected.
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 7.3.9
Node: 8.11.3
OS: win32 x64
Angular: 7.2.15
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.9
@angular-devkit/build-angular     0.13.9
@angular-devkit/build-optimizer   0.13.9
@angular-devkit/build-webpack     0.13.9
@angular-devkit/core              7.3.9
@angular-devkit/schematics        7.3.9
@angular/cli                      7.3.9
@angular/pwa                      0.12.4
@ngtools/webpack                  7.3.9
@schematics/angular               7.3.9
@schematics/update                0.13.9
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.29.0
</code></pre>

**Anything else relevant?**
I opened a bug in chromium tracker, and they marked it as "won't fix" and claimed it's an angular issue: https://bugs.chromium.org/p/chromium/issues/detail?id=968444#c2

**Comment by gkalpak** [comment] 2019-05-31 10:33
This is a little strange given that there seems to be a [non-Angular reproduction][1] 😕

[1]: https://github.com/angular/angular/issues/27554#issuecomment-497238773

**Comment by gkalpak** [comment] 2019-05-31 10:59
I tried the reproduction steps ~50 times and I couldn't get a failure 😞
What browser/OS are you seeing this on?

**Comment by alexthelion** [comment] 2019-05-31 13:59
> I tried the reproduction steps ~50 times and I couldn't get a failure 😞
> What browser/OS are you seeing this on?

@gkalpak I just reproduced it again (after 10 times while staying online):
![image](https://user-images.githubusercontent.com/6614196/58710383-d7de2780-83c4-11e9-8f55-64ec597cffda.png)

I'm using windows 10 and chrome browser:
![image](https://user-images.githubusercontent.com/6614196/58710419-f512f600-83c4-11e9-8bf9-e9e90144effd.png)

![image](https://user-images.githubusercontent.com/6614196/58710532-2ee3fc80-83c5-11e9-8a27-48213716589e.png)

**Comment by aviadavretz** [comment] 2019-05-31 15:20
I am also having this problem using angular's service worker :(
@alexthelion After 4 times i managed to reproduce the problem with your site.
![image](https://user-images.githubusercontent.com/20873197/58715975-baaf5600-83d0-11e9-85b2-77c5612d3e76.png)

**Comment by gkalpak** [comment] 2019-05-31 18:09
That's weird. I am on exact same Chrome version and also on an HP Windows 10 Pro laptop (although I am on version 1903 instead of 1809) 😕

If you can reproduce it so often, maybe you could add some break points inside `ngsw-worker.js` to capture more info about the exact failure.

Also, what does https://fir-918f4.firebaseapp.com/ngsw/state show right after you get a failure?

**Comment by alexrubin73** [comment] 2019-06-01 05:47
Same with me.
After 4-5 times i was managed to reproduce the issue.

![image](https://user-images.githubusercontent.com/33232221/58744306-9c397100-8449-11e9-8d8b-7a0b69bda725.png)

My Chrome version: Version 74.0.3729.169 (Official Build) (64-bit)

My pc details are:

![image](https://user-images.githubusercontent.com/33232221/58744325-e884b100-8449-11e9-8f86-e90d25e0b05f.png)

**Comment by gkalpak** [comment] 2019-06-01 07:40
Same for you then: https://github.com/angular/angular/issues/30778#issuecomment-497808137 :grin:

> If you can reproduce it so often, maybe you could add some break points inside `ngsw-worker.js` to capture more info about the exact failure.
>
> Also, what does https://fir-918f4.firebaseapp.com/ngsw/state show right after you get a failure?

**Comment by alexthelion** [comment] 2019-06-01 09:17
> Same for you then: [#30778 (comment)](https://github.com/angular/angular/issues/30778#issuecomment-497808137) 😁
> 
> > If you can reproduce it so often, maybe you could add some break points inside `ngsw-worker.js` to capture more info about the exact failure.
> > Also, what does https://fir-918f4.firebaseapp.com/ngsw/state show right after you get a failure?

@gkalpak there is no errors in ngsw/state:
![image](https://user-images.githubusercontent.com/6614196/58746460-1c220400-8467-11e9-8bd1-585f63738a7f.png)

I'm not sure where to put breakpoints in ngsw-worker.js

**Comment by gkalpak** [comment] 2019-06-01 10:57
Based on [this comment][1] on the Chromium bug report, I would start by putting break-points (or `console.log` 😇) in side the `handeFetch()` method (whose result is [passed to `event.repondWith()`][2]) and then take it from there (depending on where exactly the rejection comes from).

[1]: https://bugs.chromium.org/p/chromium/issues/detail?id=968444#c1
[2]: https://github.com/angular/angular/blob/32886cf9ace539e14e2b387cd8afb10715c8d3de/packages/service-worker/worker/src/driver.ts#L236

**Comment by alexthelion** [comment] 2019-06-01 15:26
@gkalpak I did some console.log... :
![image](https://user-images.githubusercontent.com/6614196/58750401-91f39300-849a-11e9-8942-0f13b2173c6f.png)

Here is the full log:
Fetch event for: https://fir-918f4.firebaseapp.com/
ngsw-worker.js:432 Fetch event returns null for: https://fir-918f4.firebaseapp.com/
ngsw-worker.js:390 Fetch event for: https://fir-918f4.firebaseapp.com/
ngsw-worker.js:432 Fetch event returns null for: https://fir-918f4.firebaseapp.com/
ngsw-worker.js:390 Fetch event for: https://fir-918f4.firebaseapp.com/index.html
ngsw-worker.js:390 Fetch event for: https://fir-918f4.firebaseapp.com/runtime.26209474bfa8dc87a77c.js
ngsw-worker.js:390 Fetch event for: https://fir-918f4.firebaseapp.com/polyfills.8bbb231b43165d65d357.js
ngsw-worker.js:390 Fetch event for: https://fir-918f4.firebaseapp.com/main.69f109cdcf7a5d2cfd49.js
The FetchEvent for "https://fir-918f4.firebaseapp.com/styles.14ad77ffc4bc34de71b8.css" resulted in a network error response: the promise was rejected.
ngsw-worker.js:1 Uncaught (in promise) DOMException
styles.14ad77ffc4bc34de71b8.css:1 Failed to load resource: net::ERR_FAILED
ngsw-worker.js:390 Fetch event for: https://cdn.pixabay.com/photo/2017/10/12/03/03/view-2843338_1280.jpg
ngsw-worker.js:432 Fetch event returns null for: https://cdn.pixabay.com/photo/2017/10/12/03/03/view-2843338_1280.jpg
ngsw-worker.js:390 Fetch event for: https://cdn.pixabay.com/photo/2017/10/12/03/03/view-2843338_1280.jpg
ngsw-worker.js:432 Fetch event returns null for: https://cdn.pixabay.com/photo/2017/10/12/03/03/view-2843338_1280.jpg
ngsw-worker.js:390 Fetch event for: https://fir-918f4.firebaseapp.com/manifest.json
ngsw-worker.js:432 Fetch event returns null for: https://fir-918f4.firebaseapp.com/manifest.json
ngsw-worker.js:390 Fetch event for: https://fir-918f4.firebaseapp.com/manifest.json
ngsw-worker.js:432 Fetch event returns null for: https://fir-918f4.firebaseapp.com/manifest.json
ngsw-worker.js:390 Fetch event for: https://fir-918f4.firebaseapp.com/assets/icons/icon-144x144.png
ngsw-worker.js:432 Fetch event returns null for: https://fir-918f4.firebaseapp.com/assets/icons/icon-144x144.png
ngsw-worker.js:390 Fetch event for: https://fir-918f4.firebaseapp.com/assets/icons/icon-144x144.png
ngsw-worker.js:390 Fetch event for: https://fir-918f4.firebaseapp.com/
ngsw-worker.js:432 Fetch event returns null for: https://fir-918f4.firebaseapp.com/
ngsw-worker.js:390 Fetch event for: https://fir-918f4.firebaseapp.com/
ngsw-worker.js:432 Fetch event returns null for: https://fir-918f4.firebaseapp.com/
ngsw-worker.js:390 Fetch event for: https://fir-918f4.firebaseapp.com/styles.14ad77ffc4bc34de71b8.css
8main.69f109cdcf7a5d2cfd49.js:1 checking for updates
>

**Comment by alexthelion** [comment] 2019-06-02 12:18
@gkalpak I just created another demo, but now I replaced angular sw to workbox . I can't reproduce the bug now.
Repo: https://github.com/alexthelion/angular-8-demo/tree/workbox
Link: https://angular8-sw.firebaseapp.com

**Comment by gkalpak** [comment] 2019-06-02 21:22
@alexthelion, you need to try to "follow" the rejection to its source. Just logging the fetch events does not reveal much :disappointed:

Regarding the workbox, it doesn't prove anything unfortunately 🤷‍♂

**Comment by alexthelion** [comment] 2019-06-03 19:46
@gkalpak If there is no way to reproduce the bug with workbox, then it's proves that there is a problem with sw and ngsw

**Comment by gkalpak** [comment] 2019-06-03 20:31
Not really 😕 It can be that one implementation has a code path that triggers a browser bug and the other doesn't.
Basides, I thought there is already a non-Angular reproduction (see https://github.com/angular/angular/issues/30778#issuecomment-497662391).

**Comment by shabbir-dhangot** [comment] 2019-06-04 06:16
I confirm this issue is happening. Yesterday only it happened in one colleague system. System Win 10 + Chrome.
Promise got rejected for ngsw.
@gkalpak can you put retry if promise rejected? May be it try to load secod time and resolve issue.

**Comment by gkalpak** [comment] 2019-06-04 10:16
@shabbir-dhangot: I would like to understand what the problem is, before taking any actions.

**Comment by shabbir-dhangot** [comment] 2019-06-04 10:23
@gkalpak 
I am guessing this is happening when network is slow. This issue is happeing only sometime to some user so don't have any exact reproducible steps. 

It seems service worker failed to load css but cache reference got stored. Now trying to read its getting failed. When I did hard refresh CSS got loaded.

**Comment by gkalpak** [comment] 2019-06-04 10:43
The SW should not store failed responses, so I don't think this is what is happening (relevant code: [here][1] and [there][2]).

[1]: https://github.com/angular/angular/blob/815443313044e0ec0ec87af588d09eda6b88f0c8/packages/service-worker/worker/src/assets.ts#L530
[2]: https://github.com/angular/angular/blob/815443313044e0ec0ec87af588d09eda6b88f0c8/packages/service-worker/worker/src/assets.ts#L310-L323

**Comment by alexthelion** [comment] 2019-06-04 14:53
@gkalpak I can't debug it as when the dev tools is automatic opened I can't reproduce the error.
I added a "console.log..." before the rejection (maybe it will help you):
![image](https://user-images.githubusercontent.com/6614196/58889449-982f7c80-86f1-11e9-814a-8f56b61a376d.png)

**Comment by gkalpak** [comment] 2019-06-05 09:20
That's interesting, @alexthelion! The only results I guess for `InvalidAccessError: Entry already exists.` point to some Chromium's SW cache code: [Source/modules/serviceworkers/Cache.cpp][1]

It would be helpful, if we could get an (async) stack trace to find out where the promise was rejected (i.e. what were we trying to put into the cache).

[1]: https://chromium.googlesource.com/chromium/blink/+/4948fee5c2bbb90c65a193faa9d55634f70f63e0/Source/modules/serviceworkers/Cache.cpp

**Comment by gkalpak** [comment] 2019-06-05 09:22
It could be [this one][1]. If that's the case, could you find out what the cache name and key are?

[1]: https://github.com/angular/angular/blob/ef4a15bc0ba9109526c31473e0b6912cdaebe8ca/packages/service-worker/worker/src/assets.ts#L323

**Comment by alexthelion** [comment] 2019-06-05 10:23
@gkalpak  I'm not sure how to provide the stack trace as I can't debug it.
I'm hope this helps more:

![image](https://user-images.githubusercontent.com/6614196/58949376-f6616b80-8794-11e9-9fb5-cc11260e6c26.png)

The code:
![image](https://user-images.githubusercontent.com/6614196/58949409-0da05900-8795-11e9-9451-b3856855807e.png)

**Comment by gkalpak** [comment] 2019-06-05 10:46
Thx again, @alexthelion. Can you verify whether it is indeed that `cache.put()` call that errors (e.g. log before and after the call and see if you get a "before" log and then the error (without an "after" log))?

Also, what does `req.url` look like? (Maybe you could try to log the `Request` as is: `console.log(`key: ${req.url}`, req)`)

**Comment by gkalpak** [comment] 2019-06-05 10:57
BTW, this old Chromium issue might be relevant: [chromium#510002][1]

It mentions the same `InvalidAccessError: Entry already exists.` error and that it might be a [race condition with names of caches and cache entries][2]. According to [this comment][3], it _"looks like an internal error leaking out"_. But then [this other comment][4] says it might be a mislabelled error (and the actual issue is different) 🤷‍♂ 

In any case, based on the random appearance of the error, it seems likely to be caused by a race condition (probably affected by certain characteristics of the host machine, so appears with higher probability on some machines than others).

[1]: https://monorail-prod.appspot.com/p/chromium/issues/detail?id=510002
[2]: https://monorail-prod.appspot.com/p/chromium/issues/detail?id=510002#c3
[3]: https://monorail-prod.appspot.com/p/chromium/issues/detail?id=510002#c10
[4]: https://monorail-prod.appspot.com/p/chromium/issues/detail?id=510002#c11

**Comment by alexthelion** [comment] 2019-06-05 11:20
@gkalpak I'm not sure that `cache.put()` call the errors.

![image](https://user-images.githubusercontent.com/6614196/58952618-e64d8a00-879c-11e9-838a-6525a014f1a9.png)

![image](https://user-images.githubusercontent.com/6614196/58952662-01b89500-879d-11e9-91d9-8703547dde45.png)

**Comment by gkalpak** [comment] 2019-06-05 11:47
Hm...yeah, it might not be that. Here is a hack you could try maybe (put it somewhere at the top of the SW file):

```js
const originalPut = Cache.prototype.put;
Cache.prototype.put = async (...args) => {
  console.log('before put', ...args);
  const result = await put.apply(this, args);
  console.log('after put', ...args);
  return result;
};
```

**Comment by alexthelion** [comment] 2019-06-05 11:56
@gkalpak 

Cache put:
![image](https://user-images.githubusercontent.com/6614196/58954450-e9974480-87a1-11e9-9458-18c296ec9fda.png)

**Comment by gkalpak** [comment] 2019-06-05 13:15
Sorry, I messed up the code in my previous snippet. It should be `originalPut.apply(this, args)`, not `put.apply(this, args)`.
Fixed now. Can you try again? Also, does the issue happen on Chrome Canary?

**Comment by alexthelion** [comment] 2019-06-05 13:33
@gkalpak The hack:

```
  const originalPut = Cache.prototype.put;
  Cache.prototype.put = async (...args) => {
    console.log('before put', ...args);
    const result = await originalPut.apply(this, args);
    console.log('after put', ...args);
    return result;
  };
```

cause errors:
![image](https://user-images.githubusercontent.com/6614196/58960348-b22f9480-87af-11e9-8749-023e2045a7f6.png)

**Comment by gkalpak** [comment] 2019-06-05 15:12
Sorry, @alexthelion, I messed it up again (which is weird because I had tried the code and it worked (I think)).
It should be `async function (...args) {` instead of `async (...args) => {` (I updated https://github.com/angular/angular/issues/30778#issuecomment-499050372).

Weird about the Canary not recognizing the PWA 😕

**Comment by alexthelion** [comment] 2019-06-05 15:47
@gkalpak 
Updated log after the hack:
![image](https://user-images.githubusercontent.com/6614196/58970490-3be85d80-87c2-11e9-8555-5552eb7dd060.png)

**Comment by gkalpak** [comment] 2019-06-05 18:33
Hm...thx for getting back. Unfortunately, I can't draw any conclusions from that. Maybe the error happens elsewhere.
I'll post our findings in the Chromium issue to see if they mean something to someone more familiar with the inner workings.

**Comment by gkalpak** [comment] 2019-06-05 22:50
@alexthelion, @aviadavretz, @shabbir-dhangot: On the [Chromium issue][1], they asked whether the users hitting this error are on a particular Chrome version.

@alexthelion mentioned `Windows 10 + Chrome 74.0.3729.169` above. Do you have other OS/browser version combinations that hit the bug (either yours or your users')?

[1]: https://bugs.chromium.org/p/chromium/issues/detail?id=968444#c15

**Comment by alexthelion** [comment] 2019-06-06 05:26
@gkalpak 
It happens also on:
1. Windows 10 + Chrome 73.0.3683.103
2. Windows 10 + Chrome 75.0.3770.80
3. Windows 7 + Chrome 67 (I don't know the exact version)

**Comment by petersonnleitner** [comment] 2019-06-11 14:01
We are having the exact same problem... very frustrating.

Windows 10 + Chrome 74.0.3729.169
Windows 10 + Chrome 75.0.3770.80

In ~40% of all requests the css file is missing

**Comment by Spawnrad** [comment] 2019-07-24 18:36
I have exactly the same issue :(

**Comment by gkalpak** [comment] 2019-07-24 18:50
This seems like a Chrome issue. You can follow it [here] and maybe provide the additional info that is requested (see, for example, [this comment][2]).

[1]: https://bugs.chromium.org/p/chromium/issues/detail?id=968444
[2]: https://bugs.chromium.org/p/chromium/issues/detail?id=968444#c27

**Comment by Da13Harris** [comment] 2019-09-24 16:47
Same issue here, but I can't contribute much additional detail since I work on an internal app for a government agency.

Windows 10.0.17134
Chrome 77.0.3865.90

In case it helps, the issue (anecdotally) seems to happen with much greater frequency immediately after starting up the machine. This leads me to believe that there may be Windows processes on start-up that affect Chrome processes that affect service workers.

**Comment by jannispl** [comment] 2019-10-11 14:27
I am also experiencing this issue.
Windows 10 1803 17134.1006
Chrome 77.0.3865.120

**Comment by diepuc** [comment] 2019-10-14 12:48
I am also experiencing this issue.
Windows 10 1803 17134.1006
Chrome 77.0.3865.120

**Comment by gkalpak** [comment] 2019-10-14 13:06
I am going to close this, since there is no indication that this is an Angular-specific issue. It is likely a Chrome bug and is tracked [here][1]. If you run into similar problems, follow the thread on the Chromium issue tracker and consider adding any extra info you might have there.

[1]: https://bugs.chromium.org/p/chromium/issues/detail?id=968444

**Closed by gkalpak** 2019-10-14 13:06 UTC
Labels: comp: service-worker, freq3: high, severity2: inconvenient, type: bug/fix

**Comment by KurtGokhan** [comment] 2019-10-23 15:37
I had the same issue. The workaround I found is to add `extractCss: false` to `angular.json` so that CSS files are embedded in JS.

**Comment by fabioemoutinho** [comment] 2019-10-23 21:28
for me, it was related to https://github.com/angular/angular/pull/33165
For some reason, chrome would not allocate enough memory to the tab, then service worker would not have enough storage quota, thus failing at loading the .css.
If you can reproduce the error, I suggest you check the storage quota usage on "Application" tab in Chrome's DevTools, "Clear Storage" option.
