### ISSUE TITLE
Service Worker does not work for offline applications

### ISSUE THREAD

**Issue by matthew-a-thomas** [angular/angular#22976] opened 2018-03-25 03:16 UTC
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Since Angular's service worker self-destructs "[when the service worker's request for `ngsw.json` returns a `404`](https://angular.io/guide/service-worker-devops#fail-safe)", it always eventually self-destructs in all offline scenarios.

Taking the app offline and refreshing the page works as expected the first time: the app still runs because the service worker is serving a cached version. But refreshing the page again after it has failed to find `ngsw.json` results in a blank screen.

## Expected behavior

Angular's service worker should continue serving a cached version of the application in the face of multiple page refreshes in an offline scenario.

Perhaps the self-destruct feature could be preserved by only self-destructing when `ngsw.json` returns `4xx` status code **and** `index.html` returns `2xx` status code.

## Minimal reproduction of the problem with instructions

STEPS TO REPRODUCE:

1) Follow these steps: https://angular.io/guide/service-worker-getting-started
2) Serve your application and confirm that the service worker is working.
3) Take your application offline (or kill your web server).
4) Refresh the page once.
5) Wait for the service worker to fail to get `ngsw.json`.
6) Refresh the page again.
7) Observe the blank page.

## What is the motivation / use case for changing the behavior?

Building Angular applications for offline use using Angular's Service Workers.

## Environment

<pre><code>
Angular version: 5.2.9

Browser:
- [x] Chrome (desktop) version 64.0.3282.186
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [x] Edge version 41.16299.248.0
 
For Tooling issues:
- Node version: v8.10.0  
- Platform: Windows 

Others:

</code></pre>

**Comment by gkalpak** [comment] 2018-03-25 05:34
Essentially duplicate of #21636. Will be fixed by #22883.

**Closed by gkalpak** 2018-03-25 05:34 UTC
