### ISSUE TITLE
Router navigate and navigateByURL don't work properly

### ISSUE THREAD

**Issue by Javaman2** [angular/angular#38098] opened 2020-07-16 15:55 UTC
# 🐞 bug report
```
 //browser is already on /pathName/oldID, this means the angular routes are correct.
 let newLocation = `/pathName/${newID}`;
          // shouldn't need to do this
         this.router.routeReuseStrategy.shouldReuseRoute = function () {
            return false;
         };
         this.router
            .navigateByUrl(newLocation)
            .then(
               (worked) => {
                  //works only because we hooked the routeReuseStrategy.shouldReuseRoute above
               },
               (error) => {
                  debugger;
               }
            );
```
### Affected Package
 @angular/Router

### Is this a regression?

Not sure.

### Description

In everything but Angular, navigate and navigateByUrl does exactly that.
  
While the code above does work when navigating to a new URL, there should instead be an option in the navigate and navgateByURL functions. Which only apply to a single navigation. 

```
  let IReallyWantToDoIt = true;
  this.router.navigateByUrl(newLocation, IReallyWantToDoIt)
```

All code above is all that's needed to reproduce and this issue is well known.

## 🔥 Exception or Error
There is no exception, rather the url is replaced without navigating, that alone should be an error. 
If the address bar has a url in it which changes after the navigation, it should go there.
Having a program change it but not navigate is odd behavior. 

## 🌍  Your Environment

**Angular Version:**
<pre><code>
 
Angular CLI: 10.0.1
Node: 12.18.0
OS: win32 x64

Angular: 10.0.3
... core
Ivy Workspace: Yes

Package                             Version
-------------------------------------------------------------
@angular-devkit/architect           0.901.10
@angular-devkit/build-angular       0.1000.1
@angular-devkit/build-optimizer     0.901.11
@angular-devkit/build-webpack       0.1000.1
@angular-devkit/core                10.0.1
@angular-devkit/schematics          10.0.1
@angular/animations                 10.0.2
@angular/cdk                        10.0.1
@angular/cli                        10.0.1
@angular/common                     10.0.2
@angular/compiler                   10.0.2
@angular/compiler-cli               10.0.2
@angular/forms                      10.0.2
@angular/language-service           10.0.2
@angular/material                   10.0.1
@angular/platform-browser           10.0.2
@angular/platform-browser-dynamic   10.0.2
@angular/router                     10.0.2
@ngtools/webpack                    8.3.28
@schematics/angular                 10.0.1
@schematics/update                  0.1000.1
rxjs                                6.6.0
typescript                          3.9.6
webpack                             4.43.0
</code></pre>

**Anything else relevant?**
We shouldn't have to do this:
```
window.location.href = newURL;
```
Please advise.

**Comment by Airblader** [comment] 2020-07-16 18:55
It does navigate, it just reuses the component for performance reasons and that behavior can be configured. That's why the activated route is reactive. I don't understand what the issue here is supposed to be.

**Comment by Javaman2** [comment] 2020-07-17 10:41
Please advise on to change the configuration to navigate always.
Then how to change it back and navigate by exception.  

All I'm saying is that AFAIK, Angular is the only framework that doesn't navigate when asked by default.
Plus there is no value in Navigating where the url changes but no navigation happens.  (That's just a bad trait)

**Comment by Javaman2** [comment] 2020-07-17 10:43
> It does navigate, it just reuses the component for performance reasons and that behavior can be configured. That's why the activated route is reactive. I don't understand what the issue here is supposed to be.

It does not navigate per default behavior, rather it just changes the URL and does nothing.  A total waste of time and bad behavior.

Just re-read carefully what was said I think you should be able to understand what's being said.

**Comment by Airblader** [comment] 2020-07-17 10:57
> it just changes the URL and does nothing

This is simply and factually incorrect. Subscribe to the paramMap / queryParamMap, or router events, or navigate backwards. All of these will show you that it does navigate. It simply reuses the component rather than destroying and recreating it. This is intended, configurable behavior.

**Comment by Javaman2** [comment] 2020-07-17 15:50
> > it just changes the URL and does nothing
> 
> This is simply and factually incorrect. Subscribe to the paramMap / queryParamMap, or router events, or navigate backwards. All of these will show you that it does navigate. It simply reuses the component rather than destroying and recreating it. This is intended, configurable behavior.

You are so arrogant dude. Besides I'm not reporting this to you.  Everything I've reported behavior wise is absolutely true.  Buzz off.

**Comment by Airblader** [comment] 2020-07-17 16:24
> You are so arrogant dude. […] Buzz off.

I'd like to remind you of the [Code of Conduct](https://github.com/angular/angular/blob/master/CODE_OF_CONDUCT.md).

> Besides I'm not reporting this to you.

You're reporting it on an open-source project, out in the open, for everyone to discuss. You're not obligated to respond to me, of course.

> Everything I've reported behavior wise is absolutely true.

Maybe, but it's intended. At least as far as I can understand your description. You haven't given a clear, reproducible example to run, so there's a certain extent of guess work to be done. Perhaps if you responded to the things I said, better yet tried them out, you could see that. Either way, posting a Stackblitz and clearly describing what you want to see would be helpful, for the Angular team as well. 

My patience with you has clearly run out to further engage here now, though.

**Comment by Javaman2** [comment] 2020-07-17 17:04
>We promise to extend courtesy and respect to everyone involved in this project regardless of gender, gender identity, sexual orientation, disability, age, race, ethnicity, religion, or level of experience. We expect anyone contributing to the Angular project to do the same.

Your comments:
>This is simply and factually incorrect.
>It does navigate

Indicate I'm lying, that's not courteous or respectful...

I put up with all your other comments in other posts and asked specific questions, none of which you replied. 
You seem to enjoy challenging reports but don't engage or believe what's being said.
You seem to be a flamer.

**Comment by Airblader** [comment] 2020-07-17 17:31
> Indicate I'm lying

I didn't say any such thing; I'm sure you believe there to be an issue. Here's the example _you_ should've provided, but it works as expected and not as you described. Can you modify it (or make a new one) that shows the behavior you're describing? It's unlikely that your issue will be seriously looked at if you don't provide an example for it.

> I put up with all your other comments in another post and asked specific questions, none of which you replied.

You never actually responded to what I said and instead engaged in a discussion with someone else, so I lost interest and gave up after repeating myself multiple times.

**Comment by Airblader** [comment] 2020-07-17 17:34
And, of course, I forget to add the actual link: https://stackblitz.com/edit/angular-ivy-7tx5vt

**Comment by mgechev** [comment] 2020-07-17 17:39
@Javaman2, thank you for reporting the behavior and trying to make Angular better. @Airblader, thanks for looking into this so quickly and providing initial thoughts and feedback.

Let's keep the conversation constructive, please. As an owner of the router @atscott will look at it and share his thoughts as well.

**Comment by atscott** [comment] 2020-07-17 19:05
https://stackblitz.com/edit/angular-ivy-7tx5vt Demonstrates that this appears to be working as expected. 

Rather than keep this open, I'm closing this as working as expected based on the provided example. However, if you can provide a reproduction in StackBlitz or a minimal GitHub repo, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and we can go from there with a clean slate.

**Closed by atscott** 2020-07-17 19:05 UTC
Labels: comp: router
