### ISSUE TITLE
IE 11 Memory Leaking on Browser Reload

### ISSUE THREAD

**Issue by derrickh1980** [angular/angular#17637] opened 2017-06-20 16:45 UTC
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[x] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
When reloading an angular application, via the browser reload, in IE 11 the browser's memory continually builds until it crashes. 

## Expected behavior
On reload of the angular application in IE 11 the browser's memory will not build.

## Minimal reproduction of the problem with instructions
1. Run the demo plunker in IE11.
    http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5
2. Hit F12 and go to the memory tab and start the memory analyzer. Additionally you can open Task Manger in Windows and watch the Memory Usage.
3. Click the green reload button to manually trigger a refresh of the preview.
4. Continue to refresh and watch the memory increase on every refresh.

## What is the motivation / use case for changing the behavior?
I am building an enterprise level application. During testing, IE11 has crashed a few times due to this memory build up. The application I'm building is quite large and when I do the same steps as listed above I am getting jumps of 100+ MB per reload. The application should not build memory on reload so the browser won't crash.

## Please tell us about your environment
<pre><code>
Angular version: 4.0.2

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [x] IE version 11.0.9600.17691 
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 6.9.5 
- Platform: Windows 7

Others:

I have done extensive testing to track down the memory leak with no success. I have tested 
this against IE, Chrome, and FireFox. Chrome and Firefox do not show any signs of memory 
leakage. Here is a list of steps taken and environment setup. 

I use Visual Studio 2015.
The following three tests were done with the Visual Studio 2015 quick start guide.
https://angular.io/guide/visual-studio-2015

Setup 1:
https://github.com/derrickh1980/IEAngularMemoryTester
Used an MVC template when starting the project.
Set up to run on IIS.
Memory jumps between 30 - 50 MB per reload.

Setup 2:
https://github.com/derrickh1980/IEAngularMemoryTester2
Used an empty website template when starting the project.
Setup to run on IIS.
Memory jumps between 30 - 50 MB per reload.

Setup 3:
https://github.com/derrickh1980/IEAngularMemoryTester3
Used an empty website template when starting the project.
Setup to use lite-server
Memory jumps between 30 - 50 MB per reload.

I turned on prod mode on all three test environments with no change in results.

Before going to an empty angular application to test this I did a few things with my current 
application.
Here is my current application setup.
Built on top of an MVC framework. (MVC is not required anywhere so this will probably change 
very soon)
It is setup to run on IIS.

First, I implemented ChangeDetectionStrategy.OnPush in my application. That did not affect 
the memory leak.

Second, I tried unsubscribing to any subscribers I have setup on observables. That didn't 
affect the memory leak. I couldn't really be sure the ngOnDestroy() method was being hit 
on reload so there was no way for me to tell if this change was actually doing anything 
anyway.

Third, I upgraded my angular version to 4.2.3 which had no affect on the memory leak.

Finally, I decided to go down to the lowest level and start with a brand new sample 
application to see if I could replicate a memory leak which I was successful at doing. I 
know that I may be introducing some memory leakage due to some coding practices 
but I have to start with Angular because a simple sample application is causing 
memory leakage.

Thanks in advance for any assistance with this.

</code></pre>

**Comment by RobertTeisanu** [comment] 2017-06-22 18:37
I am also encountering the same issue.

**Comment by SusanHanson** [comment] 2017-06-23 14:03
I came across this GitHub issue as I am also experiencing IE memory issues in a similar environment as you describe. Below is a screenshot of the IE error I see in my application: 
![image](https://user-images.githubusercontent.com/23484346/27485414-386b895e-57f2-11e7-8674-9f3d94fb43dc.png)

I ran your Plunk on my environment using IE 11. Below is a screenshot of the memory diagnosis:
![image](https://user-images.githubusercontent.com/23484346/27485456-5fa1e5d6-57f2-11e7-8357-7add8afb80df.png)

In this simple application I hit refresh (as shown in the memory jumps) and it jumped from 88.2MB to 376.2MB.

Has anyone encountered this and found a fix?

**Comment by derrickh1980** [comment] 2017-07-12 20:58
It's been a couple weeks now with no communication. Is this issue being looked into?

**Comment by ladyleet** [comment] 2017-09-12 02:12
Hi @hansl just wondering your thoughts on this? 🥇

**Comment by hansl** [comment] 2017-09-12 22:43
Hi @ladyleet, thanks for pinging me but unfortunately I was only responsible for triaging this issue. This is a core issue which I have no knowledge of. Sorry :(

**Comment by ladyleet** [comment] 2017-09-13 00:35
Thx @hansl! @StephenFluin any idea of whether this matters or is a priority, or if you'd welcome a contribution to help fix the issue? 👯‍♂️

**Comment by gkalpak** [comment] 2017-09-13 09:54
This sounds like an IE problem tbh. (I mean, whatever a webapp does, it shouldn't be able to prevent the allocated RAM after a reload.)

FWIW, we had a similar issue reported for AngularJS some time ago: angular/angular.js#15546
This is what is boiled down to: [How to work around IE memory leaks in SPAs][1]

It doesn't seem to be the exact same issue, but they may have common roots in how IE manages the underlying processes.

[1]: https://medium.com/@garthw/how-to-work-around-ie-memory-leaks-in-spas-b2f6bc7c9ae9

**Comment by StephenFluin** [comment] 2017-09-13 16:51
To quote the article @gkalpak references, it looks like the solution to work around the IE Bug is: "To allow IE to apply its hack, we simply need to get the app to “reload” itself at key points. IE then detects that it’s getting close to the memory limit and transparently recycles the process.".

This doesn't seem to be a bug specific to Angular, or even one that we can do anything about. In Chrome the referenced plnkr uses about 68MB according to chrome tooling, compared to ~20MB of memory for a given Angular site (for comparison, the IE11 home page is about 40MB)

**Comment by ladyleet** [comment] 2017-09-13 16:54
@StephenFluin thanks for taking the time to respond. and thank you too @hansl!

**Comment by maxkisung** [comment] 2017-09-13 17:16
@gkalpak It's not clear to me what 'get the app to “reload” itself' means.  Do you mean refresh the page as an f5 would?  But isn't this the action that causes the leak?

**Comment by gkalpak** [comment] 2017-09-13 18:02
@maxkisung, I didn't say anything about reloading :grin:

As mentioned in https://github.com/angular/angular/issues/17637#issuecomment-329118542:

>It doesn't seem to be the exact same issue, but they may have common roots in how IE manages the underlying processes.

I also tried OP's plnkr in IE and my observation is that after refreshing several times the total memory increases considerably, while the heap snapshots (which show the un GC'ed objects) don't show any increase in retained memory.
(I only took a quick look, so I might have missed something. Take my concusions with a grain of salt.)

So, while I can't give a definitive answer, I suspect this is an IE issue; something Angular can't do much about.

**Comment by ladyleet** [comment] 2017-09-13 20:41
@derrickh1980 hope all this helps?

**Comment by ladyleet** [comment] 2017-09-13 20:42
@SusanHanson @RobertTeisanu ^^

**Comment by ladyleet** [comment] 2017-09-13 20:42
@gkalpak thanks for being amazing and responding to this thread. i greatly appreciate all of you! :)

**Comment by derrickh1980** [comment] 2017-10-04 01:53
@ladyleet Thanks, this does help!
@gkalpak Thanks for the references. Good information on understanding how IE handles memory with SPA applications. Reducing the size of the component with the issues and cleaning up a few memory leaks throughout the application helped considerably. Haven't received the Out of Memory error for a few weeks. Hopefully I've locked it down enough.

**Comment by maraist** [comment] 2017-10-25 12:18
Came across this issue and saw https://github.com/webcomponents/webcomponentsjs/issues/541 and https://github.com/Polymer/polymer/issues/3430 https://github.com/webcomponents/webcomponentsjs/issues/541

Would seem that a circular reference between DOM and javascript (e.g. event handlers, call backs, closures held by DOM) that is NOT disconnected via a shutdown hook (e.g. classic C++ destructor that nulls out references) leaks DOM or JS objects (not clear which) on refresh.  Seems chrome/firefox use crash-only code (window onunload callback never executed), but IE NEEDS it.  work-arounds was to capture all setTimer, setTimeout, addEventListener calls with an unregistry pool.. Then explicitly removeEventListener / cancelTimer in the onclose or preonclose; whatever it was... Problem is that I can't find a way to override this at the system level, so the framework ITSELF would have to do so.  Of course, if not careful, you could memory leak just holding those unregister closures.

**Comment by gkalpak** [comment] 2017-10-25 23:27
BTW, according to [this bug report][1], it seems that some leaks are related to DevTools being open. Has anyone tried reproducing the leaks with DevTools closed?

[1]: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/11106982/

**Comment by hspier** [comment] 2017-12-01 19:41
@gkalpak I can confirm leaks are happening even if the DevTools is closed. 

Tested with three different Angular applications. One is Angular4, SPA with many components and crashing after max 15-20 reload or navigation from-to. Another is Angular5 with many components and crashing after max 30-40 reload or navigation from-to and finally from a ng new application with the latest cli which takes around 200 reload to crash, less if the DevTools are opened.

**Comment by gkalpak** [comment] 2017-12-01 19:44
Things are improving. That's a good sign 😛

**Comment by hspier** [comment] 2017-12-01 19:49
That or it is to do with the amount of components that cannot be GC. Sad part in all of this is that the heap size is constant but I am wondering if IE is calculating the heap size of the current site only and not looking at left overs of a previous site.

**Comment by gkalpak** [comment] 2017-12-01 19:55
Hard to tell unfortunately (and that's the main issue with IE's memory management - it is hard to tell what
 is going on 😞).

**Comment by hspier** [comment] 2017-12-08 16:59
@derrickh1980 You mention having mostly corrected the issue, what did you do? Did you find out why the Plunker is leaking?

I am in a situation where two big Angular applications are leaking even though they do not relate to each other. In general, the leak is 50% of the memory footprint of the application. New application created with the Angular CLI are not leaking when the DevTools are closed but I only tested with a brand new application (1 module/component, no routing).

Also, I have noticed that ngOnDestroy is not called on reload except if I apply the hack pointed out in a related issue: https://github.com/mcgraphix/angular4-memory-hack

@gkalpak Is ngOnDestroy expected to be called on reload/navigating away?

**Comment by gkalpak** [comment] 2017-12-11 12:37
@hspier, no, I don't think `ngOnDestroy()` is supposed to be called on reload. Normally, anything on `window` should be cleared (and eventually garbage collected) by the browser.

**Comment by hspier** [comment] 2017-12-11 13:31
In that case, what is the recommended approach to release event listeners and infinite observable? I am asking for both singleton providers (forRoot) as well as standard components, directives and providers. Generally speaking our applications are using ngOnDestroy for that matter.

**Comment by gkalpak** [comment] 2017-12-11 13:35
Theoretically, you don't need to release those resources when reloading, because they are all bound to the pevious window context and should be cleared by the browser.

If the browser does not, then it is a bug and applying a work-around such as https://github.com/mcgraphix/angular4-memory-hack sounds reasonable to me.

**Comment by mlc-mlapis** [comment] 2017-12-12 16:25
@hspier ... good work. 👍 But still ... the sooner you eliminate IE at all ... the better!

**Comment by raysky9999** [comment] 2018-02-12 10:03
most importantly is Microsoft planning to do anything about this IE 11 bug?
Or developers world wide has to pick up the trash for them in each and every application's code base?

**Comment by mlc-mlapis** [comment] 2018-02-12 10:06
@raysky9999 ... IE is a dead SW for 4 years already.

**Comment by derrickh1980** [comment] 2018-03-08 20:56
@hspier Sorry for the delayed response to your question. No I have not been able to fix the plunker. What was done in our enterprise application was to go through and re-analyze the way we had structured our observable chains. We had a few infinite observable subscriptions that were not being cleaned up in the component ngOnDestroy. Once we figured out where those were and learned how to properly unsubscribe() from them our issues were mitigated. Since our refactor, our site hasn't crashed due to out of memory leaks. 
I agree that IE is old and "shouldn't" be around for too much longer but we have to support it since our customer base mainly uses IE to complete their work...

**Comment by jcjolley** [comment] 2018-04-20 19:02
For some of us, ditching IE11 isn't an option, as the embedded web browser that Excel uses for its Add-ins is IE11, and isn't expected to switch to edge any time soon. :(

**Comment by beesj** [comment] 2018-05-09 06:43
@hspier ,, Thank you very much for sharing this. I am working on large scale angular 4 project and experiencing the very same memory not releasing issue when reloading the application in IE. 

- I added the  [memory hack](https://github.com/mcgraphix/angular4-memory-hack)  but still it dose not work as expected in  IE. I used given demo project it self, and it releases some memory when destroying in Chrome but **not** in IE -    Please can you share anything useful that I might have missed. 

- Can you please share what were the added remaining cleanups of TestabilityRegistry.

**Comment by hspier** [comment] 2018-05-09 16:41
@beesj: this is the code that is executed when onbeforeunload is triggered:

```
const subject = new Subject();
window.destroySubject = subject;

const destroySubscription: Subscription = subject.subscribe({
  next: () => {
    const testabilityRegistry: TestabilityRegistry = platform.injector.get(TestabilityRegistry);
    (<any>testabilityRegistry)._applications.clear();

    platform.destroy();
    platform = null;

    delete window.webpackJsonp;
    delete window.frameworkStabilizers;
    delete window.getAngularTestability;
    delete window.getAllAngularTestabilities;
    delete window.getAllAngularRootElements;
    delete window.ng;

    destroySubscription.unsubscribe();

    // remove all the nodes from the body just to simulate a blank page
    document.body.innerHTML = "";
  }
});
```

For the destroy to work, you have to make sure that every RxJS subscription is destroyed in ngOnDestroy where there is one. Finite observables (such as subscribe on an HttpClient request) don't necessarily need to be garbage collected, but most others do. 

I used this as a reference: 
https://netbasal.com/when-to-unsubscribe-in-angular-d61c6b21bad3

**Comment by alexandremoore** [comment] 2018-05-09 18:35
@beesj, on top of what @hspier mentioned, make sure to also remove any custom event listeners that you might have added.

**Comment by beesj** [comment] 2018-05-11 03:47
@hspier and @alexandremoore ,, thank you very much for the quick response, 

When I am trying this inside the **main.ts** as in the hack it is not notifying when beforeunloading,
Then I moved it to app.component.ts and wrapped inside like below

@HostListener('window:beforeunload', ['$event'])
  reload($event) {

    console.log("reloading");

    const subject = new Subject();
    window.destroySubject = subject;
    let platform = platformBrowserDynamic();

    const destroySubscription: Subscription = subject.subscribe({
      next: () => {
        const testabilityRegistry: TestabilityRegistry = platform.injector.get(TestabilityRegistry);
        (<any>testabilityRegistry)._applications.clear();

        platform.destroy();
        platform = null;

        delete window.webpackJsonp;
        delete window.frameworkStabilizers;
        delete window.getAngularTestability;
        delete window.getAllAngularTestabilities;
        delete window.getAllAngularRootElements;
        delete window.ng;

        destroySubscription.unsubscribe();

        document.body.innerHTML = "";
        
      }
    });
  }

but then it throws 

ERROR Error: A platform with a different configuration has been created. Please destroy it first.
This is due to platform has been already initialized and bootstrapped at main.ts 

Can you please tell me where have you managed to apply the hack?

And thank you for the reference I have been referring this before and it gives good tips.

**Comment by alexandremoore** [comment] 2018-05-11 13:49
@beesj, it should be in main.ts not in app.component.ts.
Also, this is how the platform should be set:

```
let platform: PlatformRef;

platformBrowserDynamic().bootstrapModule(AppModule)
  .then((ref: NgModuleRef<AppModule>) => {
    platform = ref.injector.get(PlatformRef);
  })
  .catch(err => console.error(err));

**Comment by derrickh1980** [comment] 2018-05-14 14:58
@beesj 
For us properly unsubscribing from observables has been the most important step in remediating out of memory errors. I have an article in our private wiki with my rules of thumb developed from trial and error and a few other public wiki articles.

Here are my rules of thumb to unsubscribing.

Router or HTTP
No need to unsubscribe.

({someObservable} | async)
No need to unsubscribe.
Tying an observable to the html using the async pipe will bind that observable to angular and angular's garbage collector will unsubscribe from this observable automatically.

Single Emission
Use .first() or .take(1), no need to unsubscribe.
This case is used if you only want the subscription to execute one time.

Infinite Emission
Unsubscribe in the component's ngOnDestroy().
A good example is reactive forms form control .valueChanges() subscriptions. These are infinite and should be added to a subscriptions object. You are able to add multiple subscriptions to a single Subscriptions object, much cleaner than having a subscription object for every one. The single subscriptions object must be unsubscribed from in the ngOnDestroy() function of the component.

**Comment by GerardoSabetta** [comment] 2018-05-24 14:39
@derrickh1980 Subscriptions object? I've been using a ISubscription[] and I use ngOnDestroy() {this.subs.forEach(sub => sub.unsubscribe()) }

is there any difference? could you put an example of what the subscriptions object looks like? thanks

**Comment by derrickh1980** [comment] 2018-05-25 18:02
@GerardoSabetta 
We have a subscription object in each component that requires one.
`subscriptions: Subscription = new Subscription();`
Anytime we have an infinite subscription we add it to the subscriptions object.
`this.subscriptions.add(infinite subscription logic here);`
In the component's ngOnDestroy() we unsubscribe from the subscriptions object which unsubscribes from all subscriptions added to it.
`this.subscriptions.unsubscribe();`

I'd be willing to bet your logic does the same thing, just in a different way.

**Comment by AkhilNaidu09** [comment] 2018-11-19 07:41
Can we implement Garbage collector externally for IE11 using any libraries? I am not sure about this methodology !!!

**Comment by xalisys** [comment] 2019-01-07 14:01
IE11 GC can be triggered manually by using, 
`
  if (typeof CollectGarbage === "function")
 {
        CollectGarbage();
  }
`

**Comment by croeber** [comment] 2020-05-02 19:21
I know Angular doesn't support IE compatibility mode, but I found that turning on compatibility mode with this workaround fixes this issue. 

Add to head 
`<meta http-equiv="X-UA-Compatible" content="IE=Edge"/>`
Add these to pollyfills.ts
```
import 'web-animations-js'; 
import 'classlist.js'; 
```

**Comment by AndrewKushnir** [comment] 2022-03-01 00:27
Closing this ticket, since the reported problem was only present in IE11 and Angular no longer supports IE.

**Closed by AndrewKushnir** 2022-03-01 00:27 UTC
Labels: type: bug/fix, comp: performance, freq2: medium, memory leak, comp: core, browser: ie 11, state: needs more investigation, triage #1, P4
