### ISSUE TITLE
Router lifecycle interfaces not exported in builds

### ISSUE THREAD

**Issue by brandonroberts** [angular/angular#4361] opened 2015-09-25 03:09 UTC
The router lifecycle interfaces (CanReuse, CanDeactivate, OnActivate, etc) aren't being included in the builds. No error is thrown even when implementing interfaces that don't exist.

Example: http://plnkr.co/edit/GPpGROHzUJ6dlCibwFGE?p=preview

**Comment by btford** [comment] 2015-10-09 02:33
@alexeagle – how should our bundling work WRT interfaces? Should @brandonroberts see errors about these interfaces.

@brandonroberts – in your example, there's never a situation where `canReuse` would be called. You never reuse components of different type when navigating between routes. Also, the interfaces should be imported from `angular2/router` rather than their directory in `src/...`.

I'm going to close this, since I think it's working as expected. Please feel free to file another issue if you have a reproduction with an explanation of how the behavior differs from what you'd expect (TypeScript error, run-time error, wrong navigation behavior, etc.). Thanks!

**Closed by btford** 2015-10-09 02:33 UTC
Labels: comp: router, effort1: easy (hour), P1: urgent, type: bug

**Comment by alexeagle** [comment] 2015-10-09 18:39
I am working to re-implement our exported typings, so I suspect this particular issue will be obsolete. I have a preview at https://github.com/alexeagle/angular2-distro/blob/master/README.md
