### ISSUE TITLE
Component "before destroy" proposal

### ISSUE THREAD

**Issue by glebmachine** [angular/angular#20713] opened 2017-11-30 17:12 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Unable to defer component destruction (except declarative animations)

## Expected behavior
Able to do stuff before component be destroyed
```
...
ngDestroy() {
  return new Promise(resolve => {
   setTimeout(resolve, 1000);
  })
}
...
```

## What is the motivation / use case for changing the behavior?
That was open incredible opportunities to build modern composite animations, using `gsap` for example, not only declarative animation API.

Thank you guys!

**Comment by trotyl** [comment] 2017-12-01 01:37
Duplicate of #17404

**Comment by glebmachine** [comment] 2018-01-03 12:00
Any news, guys?

**Comment by splincode** [comment] 2018-05-12 07:37
Duplicate task number #17404
@glebmachine You want to close the task..

**Comment by glebmachine** [comment] 2018-05-12 08:10
@splincode It's related, but not the same.

**Comment by splincode** [comment] 2018-05-12 08:14
@glebmachine Okay)

**Comment by glebmachine** [comment] 2018-05-12 10:36
@splincode 
What you think, is it possible to escalate this issue right to "render team"?

This is most missed feature i ever seen. It's so bad, that the think of moving to Vue.js(
We had discuss it about half year ago with you)

**Comment by splincode** [comment] 2018-05-12 11:33
@glebmachine 

The Angular team still has more important and common tasks. There is no time for polishing. As a solution, I use metaprogramming and async/await.

```ts
import { Component, Input, OnDestroy } from '@angular/core';
import { timer } from 'rxjs';
import { timeInterval, pluck, take} from 'rxjs/operators';

interface BeforeOnDestroy {
  ngxBeforeOnDestroy();
}

type NgxInstance = BeforeOnDestroy & Object;
type Descriptor = TypedPropertyDescriptor<Function>;
type Key = string | symbol;

function BeforeOnDestroy(target: NgxInstance, key: Key, descriptor: Descriptor) {
    return {
        value: async function( ... args: any[]) {
            await target.ngxBeforeOnDestroy();
            return descriptor.value.apply(target, args);
        }
    }
}


@Component({
  selector: 'hello',
  template: `<h1>Hello {{name}}!</h1>`,
  styles: [`h1 { font-family: Lato; }`]
})
export class HelloComponent implements BeforeOnDestroy, OnDestroy {
  @Input() name: string;

  constructor() {
    console.log('ADD HELLO COMPONENT');
  }

  public ngxBeforeOnDestroy() {
    console.log('1. BEFORE ONDESTROY INVOKE METHOD (await 2 sec)');
    return new Promise((resolve) => {
      setTimeout(() => this.heavyFunction(resolve), 2000);
    });
  }


  @BeforeOnDestroy
  public ngOnDestroy() {
    console.log('3. COMPONENT REMOVED AFTER 5 SECONDS OF EXPECTATION');
  }

  private heavyFunction(resolve) {
    console.log('2. EXECUTE HEAVY FUNCTION (3 sec)');

    const sourcef = timer(3000)
    .pipe(take(1))
    .subscribe(() => {
      resolve();
    });
    
  }

}
```

![image](https://user-images.githubusercontent.com/12021443/39956853-2af51e22-55f1-11e8-96e0-6a4f597fd6bb.png)

Source: https://stackblitz.com/edit/angular-lggd2a?file=src%2Fapp%2Fhello.component.ts

**Comment by glebmachine** [comment] 2018-05-12 11:52
Nice) Thank you)

**Comment by glebmachine** [comment] 2018-05-12 13:07
@splincode unfortunately, it's not working as expected.

Component should be removed from DOM _after_ async operation(

**Comment by splincode** [comment] 2018-05-12 13:16
@glebmachine How is this implemented in Vue?

**Comment by splincode** [comment] 2018-05-12 13:17
Apparently a new hook will really need to be used so that Angular does not remove an element from the DOM before calling ngOnDestroy.

**Comment by glebmachine** [comment] 2018-05-12 14:00
Vue has beforeDestroy lifecycle method.

Check for Vue lifecycle diagram here: https://d33wubrfki0l68.cloudfront.net/435786c6cbd23e078c35c2b21f40e1756b2c3d30/2098f/images/vuejs/external/component-lifecycle.png

So, the idea of this proposal - to get same mechanism.

**Comment by Goldflow** [comment] 2019-01-14 16:19
I agree this feature should be there.  Not sure if it will be of help to anyone, but we are handling our navigation in a wrapper service (because apart from routing with Router, for the other half of pages we route to a page containing an iframe & change the src accordingly).

So there implemented a navigationIntent$ subject which will then inform any subscribers when the user is about to navigate to another page, effectively giving me a hook before onDestroy is called... but it's only useful in certain scenario's.

**Comment by msosa** [comment] 2019-02-01 21:33
@splincode's code worked for me.. I need some function that was running before the component was destroyed to keep on running until it was done. I had to slightly modify the async function though since it lost its context in the ngxBeforeOnDestroy function ...
```typescript
function BeforeOnDestroy(target: NgxInstance, key: Key, descriptor: Descriptor) {
    return {
        value: async function( ... args: any[]) {
            await target.ngxBeforeOnDestroy.apply(this);
            return descriptor.value.apply(target, args);
        }
    }
}
```

**Comment by pkozlowski-opensource** [comment] 2019-03-13 10:48
This is a duplicate of #17404 - let's track it in there

**Closed by pkozlowski-opensource** 2019-03-13 10:48 UTC
Labels: comp: core & compiler, type: feature

**Comment by Max101** [comment] 2019-07-11 10:30
thanks for the solution @msosa @splincode , everything seems to work as advertised, however I am using an `*ngIf` on the component element itself and I noticed that the component is removed straightway from the DOM even though the `ngxBeforeOnDestroy` and `ngOnDestroy` are fired after.

Any ideas how one might solve this? 🤔
