### ISSUE TITLE
Sibling components next to ViewEncapsulation.Native mode component are getting their styles put in Shadow DOM

### ISSUE THREAD

**Issue by jschwarty** [angular/angular#7887] opened 2016-04-02 17:45 UTC
**Steps to reproduce and a minimal demo of the problem**
- Create sibling components in the "component tree" (have a parent component that has multiple components within its template) and give each one of them at least one CSS class in the `styles` or `styleUrls` component metadata property.
- Set one of those sibling components `encapsulation` component metadata property to `ViewEncapsulation.Native`
- Make sure the other sibling components are not set to `ViewEncapsulation.Native` mode.
- Run the code in **Chrome** since it has Shadow DOM support.
- Inspect the DOM in the browser, expand the #shadow-root for the component that is set to `ViewEncapsulation.Native` mode.
- Notice that the _styles_ from the other sibling components are ending up inside of the shadow dom for the component that is set to `ViewEncapsulation.Native`:
  ![image](https://cloud.githubusercontent.com/assets/1243236/14227993/2595ca40-f8be-11e5-874a-f1519de4f726.png)
- Also notice that the _styles_ from the other sibling components are still ending up in the `head` tag as expected:
  ![image](https://cloud.githubusercontent.com/assets/1243236/14228026/e02d8348-f8be-11e5-8f41-798fe3fedf47.png)

Here is an [example on Plunker](http://plnkr.co/edit/CbARDYM1kL3duyo4JZpz?p=preview)

**Current behavior**
Looks like the CSS shim that is getting created into a `<style>` tag is getting inserted into sibling components in the component tree that are in `ViewEncapsulation.Native` mode. It also looks like they are put in there in the same order that the custom elements are found within the parent component template markup. So if two non-native mode sibling components are processed in the DOM tree before the native mode one, their `<style>` tags will come before the native one and the native one's markup in the shadow DOM:
![image](https://cloud.githubusercontent.com/assets/1243236/14228051/7a0a9690-f8bf-11e5-84b5-9c2982c75981.png)

**Expected/desired behavior**
I believe that this is not the desired behavior and that those other sibling component styles should not be ending up in the Shadow DOM of the native mode component.

**Comment by robwormald** [comment] 2016-04-02 18:16
cc @mhevery @tbosch

**Comment by vicb** [comment] 2016-09-28 17:20
still an issue with Angular 2.0.1

http://plnkr.co/edit/M785PCAb3Hc7WLD7EKyB

**Comment by tbosch** [comment] 2017-02-17 01:54
The fix in the PR is actually wrong and breaks the styling of components with emulated / no encapsulation inside of components that use native encapsulation.

Our strategy is as follows:
Copy all styles that are in the `<head>` into every shadow root. This is non optimal, but correct in terms of styling. Detecting which components are actually used inside of a shadow root tree is non trivial and requires overhead that we would also pay for users that don't use shadow dom.

I.e. we are waiting for a browser feature that allows to style elements inside of shadow roots via a `<style>` element in `<head>`. I am going to revert this change and adjust the test to reflect the problem (as we obviously had no test that actually tests the scenario that a component with shadow dom uses a component without).

**Comment by Hanfrey** [comment] 2017-03-09 07:52
Can this also be reverted in the next 2.x Version?

**Comment by DzmitryShylovich** [comment] 2017-03-09 08:03
yeah, it must be reverted in 2.x @tbosch

**Comment by tobi-or-not-tobi** [comment] 2018-06-05 09:46
I can confirm this is still the behaviour with angular 6. The shadow dom of a native encapsulated component receives multiple style elements with the css rules from other components.

**Comment by petebacondarwin** [comment] 2021-01-23 19:44
Duplicate of #5059 5059

**Closed by petebacondarwin** 2021-01-23 19:44 UTC
Labels: P3, comp: core, core: CSS encapsulation, freq1: low, type: bug/fix
