### ISSUE TITLE
Svg viewbox not working when using use inside of it

### ISSUE THREAD

**Issue by AloisH** [angular/angular#42947] opened 2021-07-23 14:57 UTC
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

Hello,

When I try to use svg viewbox with a use tag it is not working : 

```html
<style>
  .scaling-svg-container {
    position: relative;
    height: 32px;
    width: 32px;
    padding: 0;
  }

  .scaling-svg {
    border: 1px solid red;

    position: absolute;
    height: 32px;
    width: 32px;

    left: 0;
    top: 0;
  }
</style>

test

<div class="scaling-svg-container">
  <svg class="scaling-svg" viewbox="0 0 16 16">
    <use xlink:href="../assets/sun.svg#icon-sun"></use>
  </svg>
</div>
```
But If I try the same code in a live server it work prefectly fine.

Not working in angular :
![alt text](https://i.imgur.com/Hrw0Pnj.png)

Working outside :
![alt text](https://i.imgur.com/tO1jXRd.png)

### Please provide a link to a minimal reproduction of the bug

https://github.com/AloisH/bug_angular

### Please provide the exception or error you saw

```true
```

### Please provide the environment you discovered this bug in

```true
Angular CLI: 12.1.1
Node: 14.17.3
Package Manager: npm 6.14.13
OS: win32 x64

Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1201.1 (cli-only)
@angular-devkit/core         12.1.1 (cli-only)
@angular-devkit/schematics   12.1.1 (cli-only)
@schematics/angular          12.1.1 (cli-only)
```

**Comment by JoostK** [comment] 2021-07-23 16:48
Duplicate of #42345; SVG is case-sensitive and the property is named `viewBox`, not `viewbox`.

**Closed by JoostK** 2021-07-23 16:48 UTC
