### ISSUE TITLE
test(docs-infra): 404 for images during unit tests on Windows

### ISSUE THREAD

**Issue by gkalpak** [angular/angular#29775] opened 2019-04-09 00:03 UTC
Running the unit tests for aio on Windows, many 404s are logged for images, resulting in progress logs being spread over multiple lines:

```
Chrome 70.0.3538 (Linux 0.0.0): Executed 0 of 609 SUCCESS (0 secs / 0 secs)
Chrome 70.0.3538 (Linux 0.0.0): Executed 1 of 609 SUCCESS (0 secs / 0.304 secs)
Chrome 70.0.3538 (Linux 0.0.0): Executed 2 of 609 SUCCESS (0 secs / 0.355 secs)
Chrome 70.0.3538 (Linux 0.0.0): Executed 3 of 609 SUCCESS (0 secs / 0.395 secs)
Chrome 70.0.3538 (Linux 0.0.0): Executed 4 of 609 SUCCESS (0 secs / 0.438 secs)
Chrome 70.0.3538 (Linux 0.0.0): Executed 5 of 609 SUCCESS (0 secs / 0.471 secs)
Chrome 70.0.3538 (Linux 0.0.0): Executed 6 of 609 SUCCESS (0 secs / 0.504 secs)
Chrome 70.0.3538 (Linux 0.0.0): Executed 7 of 609 SUCCESS (0 secs / 0.542 secs)
Chrome 70.0.3538 (Linux 0.0.0): Executed 8 of 609 SUCCESS (0 secs / 0.578 secs)
Chrome 70.0.3538 (Linux 0.0.0): Executed 9 of 609 SUCCESS (0 secs / 0.621 secs)
...
```

For example, running [this test](https://github.com/angular/angular/blob/84be7c52dc431ab8621bc6231b8980a73072ae85/aio/src/app/app.component.spec.ts#L90-L92), I get:

```
WARN [web-server]: 404: /assets/images/logos/angular/logo-nav@2x.png
WARN [web-server]: 404: /assets/images/logos/angular/angular_whiteTransparent_withMargin.png
```

I was not able to reproduce it on a new project on Windows 🤷‍♂️ 
It also works fine on Linux and Windows Subsystem for Linux for `aio/` as well 😕

**Comment by sonukapoor** [comment] 2020-02-11 03:27
@gkalpak I am not able to reproduce this either on my Windows 10 Laptop:

![image](https://user-images.githubusercontent.com/59734/74209141-80cb6a80-4c54-11ea-90b8-5d4d53af23bd.png)

**Comment by gkalpak** [comment] 2020-02-12 19:53
Interesting. I can still reproduce i (although with much fewer occurrences, so only a couple of extra lines). Based on the screenshot, you seem to only have run 1 tests; maybe that's the reason you don't see the problem?

<sub>In any case, thanks for looking into this @sonukapoor ❤️</sub>

**Comment by sonukapoor** [comment] 2020-02-13 04:02
@gkalpak, I got the latest and re-ran all tests. I am still not able to reproduce this:

![image](https://user-images.githubusercontent.com/59734/74400386-beaec700-4deb-11ea-93c7-06146a48a0f4.png)

**Comment by gkalpak** [comment] 2020-02-13 18:27
Well, you actually did reproduce it :grin:
The reason you have three lines with "...Executed xyz of 621..." is because something was written to the terminal. It is definitely much better than before, so it seems that the main issue was fixed.

It would still be interesting to find out what is being printed and whether we can get rid of it (e.g. by using a different jasmine reporter).

**Comment by sonukapoor** [comment] 2020-02-13 18:32
You got it. I am on it

**Comment by sonukapoor** [comment] 2020-02-27 03:33
@gkalpak Please assign this one to me, so I can track it. Thanks

**Closed** 2020-03-02 16:16 UTC
Labels: comp: build & ci, comp: docs-infra, type: bug/fix
