### ISSUE TITLE
Attributes are not preserved on `<style>` 

### ISSUE THREAD

**Issue by vicb** [angular/angular#21738] opened 2018-01-23 23:35 UTC
Imported from b/26581405

I have the following in a component template:

    <style is='custom-style'>...</style>

which is transformed and inserted under the 'head' tag:

    <style>...</style>

losing the "is='custom-style'" during the process.

This marker is needed by polymer.

**Comment by trotyl** [comment] 2018-02-18 17:00
Duplicate of #6513 (is it copy & pasted? 😃 )

**Comment by pkozlowski-opensource** [comment] 2018-10-29 16:52
Duplicate of #6513

**Closed by pkozlowski-opensource** 2018-10-29 16:52 UTC
Labels: comp: core & compiler, freq1: low, severity3: broken, type: bug/fix
