### ISSUE TITLE
 Function calls are not supported in decorators but 'RouterModule' was called. (Ivy=false)

### ISSUE THREAD

**Issue by fkolar** [angular/angular#38609] opened 2020-08-27 08:21 UTC
# 🐞 bug report

### Description

I have simple usecase where I try to compile a library that imports RouteModule:

```
const APP_ROUTES: Routes = [
  {path: 'item-detail', component: ItemPageComponent}
];


@NgModule({
  imports: [
    RouterModule.forChild(APP_ROUTES)
  ],
  exports: [
    RouterModule
  ],
})
export class ItemPageRoutingModule {
}
```

When I call `ng build on it` with Ivy disabled I get this error:

<pre><code>
Compiling TypeScript sources through ngc
ERROR: Error during template compile of 'ItemPageRoutingModule'
  Function calls are not supported in decorators but 'RouterModule' was called.

An unhandled exception occurred: Error during template compile of 'ItemPageRoutingModule'
  Function calls are not supported in decorators but 'RouterModule' was called.

See "/private/var/folders/p8/z77781m16y17lgc2_z06xzt00000gn/T/ng-ZBvC14/angular-errors.log" for further details.

</pre></code>

log file:

```
[error] Error: Error during template compile of 'ItemPageRoutingModule'
  Function calls are not supported in decorators but 'RouterModule' was called.

    at Object.<anonymous> (~/projects/micro-frontend/microfrontend-st/microfrontend-apps/node_modules/ng-packagr/lib/ngc/compile-source-files.js:71:19)
    at Generator.next (<anonymous>)
    at fulfilled (~/micro-frontend/microfrontend-st/microfrontend-apps/node_modules/ng-packagr/lib/ngc/compile-source-files.js:5:58)



```

## 🔬 Minimal Reproduction

```
git clone https://github.com/fkolar/microfrontend-st.git 
cd to microfrontend-st.git
cd to subproject microfrontend-apps
npm install 
ng  build content-item-app

```

If I add `"fullTemplateTypeCheck": "false",` to the tsConfig then error is gone. 

## 🔥 Exception or Error
<pre><code>
Compiling TypeScript sources through ngc
ERROR: Error during template compile of 'ItemPageRoutingModule'
  Function calls are not supported in decorators but 'RouterModule' was called.

An unhandled exception occurred: Error during template compile of 'ItemPageRoutingModule'
  Function calls are not supported in decorators but 'RouterModule' was called.

See "/private/var/folders/p8/z77781m16y17lgc2_z06xzt00000gn/T/ng-qingqR/angular-errors.log" for further details.

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 10.0.7
Node: 12.0.0
OS: darwin x64

Angular: 10.0.12
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1000.7
@angular-devkit/build-angular      0.1000.7
@angular-devkit/build-ng-packagr   0.1000.7
@angular-devkit/build-optimizer    0.1000.7
@angular-devkit/build-webpack      0.1000.7
@angular-devkit/core               10.0.7
@angular-devkit/schematics         10.0.7
@angular/cdk                       10.1.3
@angular/cli                       10.0.7
@ngtools/webpack                   10.0.7
@schematics/angular                10.0.7
@schematics/update                 0.1000.7
ng-packagr                         10.0.4
rxjs                               6.5.5
typescript                         3.9.7
webpack                            4.43.0

</code></pre>

**Comment by alan-agius4** [comment] 2020-08-27 09:27
Duplicate of https://github.com/angular/angular/issues/23609

**Closed by alan-agius4** 2020-08-27 09:27 UTC
