### ISSUE TITLE
JSONP callback not invoked

### ISSUE THREAD

**Issue by HauntedSmores** [angular/angular#14409] opened 2017-02-10 21:49 UTC
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Response from jsonp requests is:

```
Uncaught ReferenceError: __ng_jsonp____req0_finished is not defined
    at VM4511 recent?access_token=12345…&callback=__ng_jsonp__…:1
(anonymous) @ VM4511 recent?access_token=12345…&callback=__ng_jsonp__…:1
```
Followed JSONP tutorial in the HTTP Client - ts docs for angular 2. Heres my code:

I have gotten a correct response and payload when using `callback="__ng_jsonp____req0.finished` so I know my url and auth is correct

Service
```
import { Injectable } from '@angular/core';
import { Jsonp } from '@angular/http';
import { Observable } from 'rxjs';
import 'rxjs/add/operator/map';

@Injectable()
export class LandingService {

    constructor(private jsonp: Jsonp, private http: Http) {}

    myFunction() {

        let request: string;
        let result: any;

        request = "https://api.instagram.com/v1/users/self/media/recent?callback=JSONP_CALLBACK";
        result = this.jsonp.get(request).map(response => response.json());
        return result;
    }

}
```

Component
```
import { Component } from '@angular/core';
import { LandingService } from '../../services/landing.service';

@Component({
  selector: 'app-landing',
  templateUrl: './landing.component.html',
  styleUrls: ['./landing.component.scss']
})
export class LandingComponent implements OnInit {

  constructor(private landing: LandingService) {

      this.landing.myFunction().subscribe(data => console.log(data));

  }
}
```
Module
```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { HttpModule, JsonpModule } from '@angular/http';
import { AppRoutingModule } from './app-routing.module';
import { LandingService } from './services/landing.service';

import { AppComponent } from './app.component';
import { LandingComponent } from './components/landing/landing.component';

@NgModule({
  declarations: [
    AppComponent,
    LandingComponent,
  ],
  imports: [
    BrowserModule,
    FormsModule,
    HttpModule,
    JsonpModule,
    AppRoutingModule
  ],
  providers: [ LandingService ],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

Angular version:
2.4.7

**Comment by DzmitryShylovich** [comment] 2017-02-10 21:51
> Uncaught ReferenceError: __ng_jsonp____req0_finished is not defined

duplicate of https://github.com/angular/angular/issues/14267 ...

**Comment by HauntedSmores** [comment] 2017-02-10 21:52
@DzmitryShylovich You can close this if you need to and I can follow the other thread

**Comment by DzmitryShylovich** [comment] 2017-02-10 21:55
you can close it yourself :)

**Closed** 2017-02-13 08:13 UTC
