### ISSUE TITLE
Serving an app with --prod which uses a lib that has a cyclic dependency and not built with --prod doesn't work

### ISSUE THREAD

**Issue by AndreiVajnaII** [angular/angular#36037] opened 2020-03-12 14:51 UTC
# 🐞 bug report

### Affected Package
Not really sure, I'm guessing it's something that reproduces when the build optimizer is activated. The problem might be there, or in the compiler.

### Is this a regression?

Yes, with 8.2.13 this wasn't a problem.

### Description

I generated a library project (`ng g lib cyclic`) in which I created two components with a cyclic dependency: ParentComponent includes ChildComponent in its template, while ChildComponent injects ParentComponent. In the app component, the ParentComponent is used in the template with the *ngIf directive bound to a flag that is set to true when a button is clicked.

If I build the library project (`ng build cyclic`) without the --prod flag, then serve the app with the --prod flag, when clicking the button, the component does not appear.

Debugging the problem, it seems that when creating  the TView of the ParentComponent, the directiveRegistry is null, and the flags are 0, so Angular does not see the associated node as a component. I noticed that if I serve the app without the --prod flag, after the module, a call to 
`ɵɵsetComponentScope` is inserted. This is done, as I understand it, in cases of cyclic dependencies.

However, when serving with the --prod flag, this call is not there, and that's why the flags are not set, and directiveRegistry is null.

## 🔬 Minimal Reproduction

https://github.com/AndreiVajnaII/ivy-cyclic-dependency-in-lib-production-bug

```
npm i
ng build cyclic
ng serve --prod
```

Click the "Show" button. The text "child" should appear, but nothing happens.

Workaround: `ng build cyclic --prod` instead.

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.0.6
Node: 10.15.3
OS: win32 x64

Angular: 9.0.6
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.900.6
@angular-devkit/build-angular      0.900.6
@angular-devkit/build-ng-packagr   0.900.6
@angular-devkit/build-optimizer    0.900.6
@angular-devkit/build-webpack      0.900.6
@angular-devkit/core               9.0.6
@angular-devkit/schematics         9.0.6
@ngtools/webpack                   9.0.6
@schematics/angular                9.0.6
@schematics/update                 0.900.6
ng-packagr                         9.0.3
rxjs                               6.5.4
typescript                         3.7.5
webpack                            4.41.2
</code></pre>

**Anything else relevant?**
Not sure how important these are, but I'm using the following:
- Windows 1909
- Node.JS v10.15.3
- npm v6.4.1

**Comment by JoostK** [comment] 2020-03-12 16:09
Closing as duplicate of #35602, please find more details and a workaround there.

**Closed by JoostK** 2020-03-12 16:09 UTC
