### ISSUE TITLE
Using module.id with component makes it not load

### ISSUE THREAD

**Issue by pdeva** [angular/angular#6131] opened 2015-12-27 00:17 UTC
I am trying the 'hero' example on angular.io and using JSPM to load my scripts (non-bundled).
To get relative urls for my templates, i tried the method in #2383 and added `moduleId: module.id` to my component.

```
import {Component} from 'angular2/core';
import {Hero} from "./hero";

@Component({
	selector: 'my-hero-detail',
	inputs: ['hero'],
	moduleId: module.id,
	templateUrl:'heroes.html'
})
```

However, doing so and then running the app, makes the html stuck at 'Loading...' with no errors in the console.

Screenshot:
<img width="232" alt="angular_2_quickstart" src="https://cloud.githubusercontent.com/assets/3190176/12008390/1caf5b36-abec-11e5-90df-f4b07bd1e39e.png">

**Comment by frederikschubert** [comment] 2015-12-29 12:10
`module.id` is provided by the commonjs module. So you have to set the `compilerOptions.module` in your *tsconfig.json* to `commonjs` in order to activate the relative paths feature.

**Comment by UWouldlLose** [comment] 2015-12-31 15:15
It seems like even the "module": "commonjs" option in place the issue still exists when bundling with systemjs-builder.

**Comment by frederikschubert** [comment] 2015-12-31 15:25
When using the systemjs-builder the module.id property is set to the location and name of the bundled file. Due to this the relative assets are all assumed to be in the same directory as the bundle. 
So the only option is to either set the component's `moduleId` property manually to the right directory during a build step or to copy all assets to the directory of the bundle.

**Comment by UWouldlLose** [comment] 2015-12-31 15:37
That would make sense, I was seeing runtime errors with module being undefined. I might have something configured wrong? 

I don't know if that would be it though, because if I strip out the moduleId: module.id from my @Component definitions everything runs fine.  

Config: 
    System.config({
        transpiler: 'typescript',
        baseURL: "/dist",
        typescriptOptions: {
            emitDecoratorMetadata: true,
            module: "commonjs",
            experimentalDecorators: true
        },
        map: {
            app: 'src',
            typescript: 'node_modules/typescript/lib/typescript.js',
            angular2: 'node_modules/angular2',
            rxjs: 'node_modules/rxjs'
        },
        packages: {
            app: {
                defaultExtension: 'ts',
                main: 'app.ts'
            },
            angular2: {
                defaultExtension: 'js'
            },
            rxjs: {
                defaultExtension: 'js'
            }
        }
    });

Build Command: 
    builder.bundle('app - vendor.js', 'dist/bundledapp.js', { minify: true });

**Comment by frederikschubert** [comment] 2015-12-31 15:43
I see. One thing I notice in your config is that you are using the [deprecated](https://github.com/systemjs/systemjs/commit/f8d6a6a85d7c4e93da486f04a9c2d5025c12c51b) internal transpiler of Systemjs. You should use this [plugin](https://github.com/frankwallis/plugin-typescript) for that.
You can see a configuration for using the plugin in my repository [here](https://github.com/frederikschubert/angular2-jspm/blob/master/config.js).

**Comment by UWouldlLose** [comment] 2015-12-31 18:18
@frederikschubert  That is a great idea, I didn't realize the transpile option was out of date. 

Do you know if I can point the "ts" mapping at a folder in my node_modules? I pulled down the library from npm but am not quite sure what .js file I'd map to. 

Updated Config: 
    System.config({
    transpiler: false,
    baseURL: "/dist",
    typescriptOptions: {
        emitDecoratorMetadata: true,
        module: "commonjs",
        experimentalDecorators: true
    },
    map: {
        app: 'src',
        typescript: 'node_modules/typescript/lib/typescript.js',
        angular2: 'node_modules/angular2',
        rxjs: 'node_modules/rxjs',
        ts: 'node_modules/plugin-typescript/lib/???'
    },
    packages: {
        app: {
            defaultExtension: 'ts',
            main: 'app.ts',
            "meta": {
                "*.ts": {
                    "loader": "ts"
                }
            }
        },
        angular2: {
            defaultExtension: 'js'
        },
        rxjs: {
            defaultExtension: 'js'
        }
    }
    });

**Comment by zoechi** [comment] 2015-12-31 20:01
@UWouldlLose Enclosing source blocks in triple backticks and inline code in single backticks make comments more readable.

**Comment by evanplaice** [comment] 2016-01-28 23:58
This is a duplicate of #6053

**Comment by otabekgb** [comment] 2016-02-02 13:48
+1

**Comment by vicb** [comment] 2016-09-25 17:22
obsolete.
angular.io has docs on module.id

**Closed by vicb** 2016-09-25 17:22 UTC

**Comment by nzcoward** [comment] 2016-09-30 09:53
@vicb Where is this documented? I am getting the issue still with 2.0.1

**Comment by vicb** [comment] 2016-09-30 16:25
https://angular.io/docs/ts/latest/cookbook/component-relative-paths.html

**Comment by ArturoGamRod** [comment] 2017-03-30 17:42
@vicb  The url is not  working

**Comment by madjake45** [comment] 2017-04-07 09:29
@ArturoGamRod This has now been removed for a systemjs plugin: [https://angular.io/docs/ts/latest/guide/change-log.html#!#all-mention-of-moduleid-removed-component-relative-paths-cookbook-deleted-2017-03-13-](https://angular.io/docs/ts/latest/guide/change-log.html#!#all-mention-of-moduleid-removed-component-relative-paths-cookbook-deleted-2017-03-13-)

**Comment by ArturoGamRod** [comment] 2017-04-07 13:58
@madjake45 Thank you! I did not know!

**Comment by silenceisgolden** [comment] 2017-07-05 16:32
@vicb It looks like the URL still is not working. Is there a new URL?

**Comment by tytskyi** [comment] 2017-07-05 17:48
@silenceisgolden this practice is no more used, see details https://angular.io/guide/change-log#all-mention-of-moduleid-removed-component-relative-paths-guide-deleted-2017-03-13

**Comment by silenceisgolden** [comment] 2017-07-05 20:26
@tytskyi Thank you very much!
