### ISSUE TITLE
routerCanReuse not implemented in 3.0 router ??

### ISSUE THREAD

**Issue by avastms** [angular/angular#9811] opened 2016-07-05 09:06 UTC
I don't see `routerCanReuse` in 3.0 router.
Router.renavigate is also gone in 3.0.

It used to be https://angular.io/docs/js/latest/api/router-deprecated/index/CanReuse-interface.html

I didn't find corresponding code in router 3.0. 
What's your plan about this  `CanReuse` ?

**Comment by noelmace** [comment] 2016-07-05 09:36
Hello there. Your question seems to be a support request. If so, the [Google Group](https://groups.google.com/forum/#!forum/angular) discussion list or [StackOverflow](http://stackoverflow.com/questions/tagged/angular) should be better place to answer it, as mentionned at [CONTRIBUTING.md#question](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question). Thank you.

**Comment by zoechi** [comment] 2016-07-05 10:00
See https://angular.io/docs/ts/latest/guide/router.html#!#guards

@avastms  Would you mind closing the issue?

**Comment by fknop** [comment] 2016-07-05 10:18
Actually, I have the same issue with reusing components. I'm not sure it's working properly. I have 3 routes, with the same component for each route but different `data`. The component is reinstantiated every time. I'll try to get a plunkr working.

**Comment by avastms** [comment] 2016-07-05 11:56
@zoechi This feature was not provided in router 3.0, neither not mentioned in the doc.
And I do believe providing this `routerCanReuse` option is very important.

**Comment by fknop** [comment] 2016-07-05 12:03
It is said that router are reused by default, but it does not seem to work.

**Comment by zoechi** [comment] 2016-07-05 12:05
@fknop this is only supposed to work when navigated to the same route while only route parameters change. But I remember seeing an issue a while ago about this not working yet.

**Comment by DavideViolante** [comment] 2016-07-05 21:06
I can confirm the component is re-used by default when you navigate to a route handled by the same component but with different route params (in url). Eg: .../users/1 ---> .../users/2.
I didn't try other cases.

**Comment by fxmontigny** [comment] 2016-07-06 09:18
@fknop I have the same problem as you.
This is my example 
https://plnkr.co/edit/t4tSxs?p=preview

**Comment by fknop** [comment] 2016-07-06 09:23
@fxmontigny It's actually working for the params only.

**Comment by zoechi** [comment] 2016-07-06 09:26
@fxmontigny what's the problem in your plunker? If you switch between `two - first` and `two - second` `ngOnInit()` is not called. This is the expected behavior because the component is reused.

**Comment by fknop** [comment] 2016-07-06 09:27
Here you go: https://plnkr.co/edit/7ZCEJP1mCrne196OKcJe?p=preview Same components, different data, not reused.

**Comment by zoechi** [comment] 2016-07-06 09:29
`ngOnInit()` is still only called the first time when I click `two - first` and `two - second` a few times.

**Comment by fxmontigny** [comment] 2016-07-06 09:41
@zoechi I try to use same component with different param. 
My constructor are not init again.
https://plnkr.co/edit/t4tSxs?p=preview

Exemple: 
step 1: click to "one" -> show "one"
step 2: click to "two -first" -> show "two param: 1" because my router like "cmp/:id" with :id = 1
step 3: click to "two - second" -> do not change renderer but the router id are know equal at 2
step 4: click to "one" -> show "one"
step 5: click to "two - second" -> show "two param: 2"

I think i have forgot something.

@fknop I do not know "data". I'll look in the doc.

**Comment by fknop** [comment] 2016-07-06 10:12
It's the all purpose of this to not recreate components. Use observable instead of snapshot.

**Comment by zoechi** [comment] 2016-07-06 10:13
@fxmontigny If you click "one" (different component) and than back to "two" then the component is **not** reused. This is "as designed". Only when you navigate to the same route while only the parameters change then the component is reused. If you navigate to a different route, the component is destroyed and re-created the next time you navigate back to it.

**Comment by fknop** [comment] 2016-07-06 10:29
It would be nice if we could specify an option to reuse it on route change too.

**Comment by zoechi** [comment] 2016-07-06 10:37
@fknop I'm sure this won't happen. Just store the state in a service and initialize the component from it when it is recreated.

**Comment by fknop** [comment] 2016-07-06 10:43
There is not really a state for my use case, only data config change. It works but I just feel it's not necessary to recreate something that's already there.

**Comment by avastms** [comment] 2016-07-09 16:25
@vsavkin Would you please implement routerCanReuse in 3.0 router?

**Comment by maku** [comment] 2016-07-18 16:15
It would be really important to have a routerCanReuse functionality. 
e.g. I have a use case where I embed a third party ui component (a picture slider) where I have to call API functions on creation. Now, with reusing, this does not work anymore....

**Comment by zoechi** [comment] 2016-07-18 17:41
@maku as an ugly **workaround** you could navigate away from the current route and then back again. AFAIR the `skipHistoryChange` (or similar) was re-added recently to spam the history with it.

**Comment by zoechi** [comment] 2016-07-18 17:42
An `*ngIf="doShow` on the outermost element in your template with setting `doShow` to `false`, run change detection and then set back to `true` might work as well if you just need to reinitialize the DOM.

**Comment by mustafasadikot** [comment] 2016-08-09 10:15
Can we make if configurable so that component can be re-initialized for parameterized routes as well? Or is there a better pattern that can be employed to avoid such situation?

**Comment by lverledens** [comment] 2016-08-19 13:29
What is the suggested way to detect route parameter changes when the component is reused (so ngOnInit() is not called)?

**Comment by ShadOoW** [comment] 2016-09-08 11:00
I have the exact opposite problem, i rely on component being receated to be fresh.
But since I've upgraded, if the pamas change, the component no longer get destroyed and recreated.

**Comment by avastms** [comment] 2016-09-15 09:39
You let router 3.0 published without `canReuse` implemented ?????
What is wrong with you!
Observables is not helpful on this, because most components relies `ngInit` to work. 
Especially when the component or some jQuery plugin stuff was provided by some third-party.

**Comment by kemsky** [comment] 2016-09-15 18:09
Lets be honest here, router was rewritten three(!) times. A lot of efforts were *lost* during migrations to the latest RCs, finally we did it. What do we have now? *Tons* of components that work using assumption that they wont be reused. It is not something that can be quick fixed on our side.

@vicb, could someone from the team comment this situation?

**Comment by vicb** [comment] 2016-09-15 20:53
@vsavkin could you shim in ?

**Comment by rpaschoal** [comment] 2016-09-19 04:56
I'm also very interested in a "canReuse" property since I am working on a project that started with Angular2 RC1 and most of our components rely heavily on "ngOnInit" for data fetching.

Thanks!

**Comment by zoechi** [comment] 2016-09-19 05:05
@rpaschoal an easy workaround is usually to subscribe to `this.route.params.subscribe(...)` and do the data fetching there.
`canReuse` is IMHO only crucical if there are external libraries that modify the DOM that needs to be reinitialized but `*ngIf` can usually be used as a workaround.

**Comment by rpaschoal** [comment] 2016-09-19 05:21
Thank you @zoechi, I will give it a try. I can tell you I am suffering a lot to move from RC4 to final release.

Our UI has a lot of particularities, we are implementing something very similar to the Azure Portal concept, we call them "Blades" here. :P

**Comment by jamesthurley** [comment] 2016-09-19 16:29
I've created the following two classes to work around the issue for the time being.  They aren't heavily tested (I literally just wrote them), but perhaps they'll help someone:

```typescript
import {Component, OnInit} from '@angular/core';
import {Router, ActivatedRoute, UrlSegment} from '@angular/router';

export class NoReusePageBase
{
  constructor(router: Router, route: ActivatedRoute)
  {
    route.url.skip(1).forEach((url: UrlSegment[]) => {
      router.navigate(
        ['/forward', { data: encodeURIComponent(JSON.stringify(url.map(v => v.path))) }], 
        { skipLocationChange: true });
    });
  }
}

@Component({
  template: ''
})
export class ForwardPage implements OnInit {
  constructor(private router: Router, private route: ActivatedRoute) {}

  ngOnInit(): void {
    this.router.navigate(
      JSON.parse(decodeURIComponent(this.route.snapshot.params['data'])), 
      { skipLocationChange: true });
  }
}
```

So if I derive my Angular component from `NoReusePageBase`, then if the `params` observable is updated `NoReusePageBase` will grab the new URL segments and navigate to `ForwardPage`.  `ForwardPage` takes the passed URL segments and navigates back to the original page.

I think having the ability to **never** reuse a component should be added back in, because to quote [the Angular 2 documentation](https://angular.io/docs/ts/latest/guide/router.html#!#snapshot): "The router offers a Snapshot alternative ... It's much simpler to write and read".  And why make things more complicated when the simpler way suffices?

**Comment by jon301** [comment] 2016-10-05 14:24
So right now there's not way for the router to "renavigate" to the active route ?

It's a very common UX use case that a user wants to reload the content of the page when clicking on the current active nav item
Will this feature be put back in Router v3 by any chance ?

Thanks for your help

**Comment by dmichael266** [comment] 2016-10-09 11:50
I love Angular... and here comes the but.  I can't believe a feature that many people were probably relying on would just be dropped like that.  I too really hope a future release of the Router will bring back the routerCanReuse feature.

**Comment by DzmitryShylovich** [comment] 2016-10-12 12:19
@dmichael266 
1. your code will not work in aot.
2. u can simplify your code. See https://github.com/ReactiveX/rxjs/blob/master/doc/subscription.md
> Subscriptions can also be put together, so that a call to an unsubscribe() of one Subscription may unsubscribe multiple Subscriptions. You can do this by "adding" one subscription into another:

**Comment by dmichael266** [comment] 2016-10-12 12:24
@DzmitryShylovich 
Thanks for the feedback.  I haven't started using aot yet.  Just curious what about the code wouldn't work in aot.  Thanks.

**Comment by DzmitryShylovich** [comment] 2016-10-12 12:27
Angular doesn't support inheritance (yet) https://github.com/angular/angular/issues/12175

**Comment by dmichael266** [comment] 2016-10-12 12:32
@DzmitryShylovich 
Ah.  Thank you for pointing that out.

**Comment by jamesmfriedman** [comment] 2016-10-21 14:18
After reading through the issue, I'm more confused :(

The docs say that routes mapping to the same component will reuse the same component by default without throwing away the existing DOM.

I can confirm in my own code with 2.0.0, that ngOnInit will re-run on every route change. This is extra confusing since route.params is an observable, but since it gets scrapped on every reload, you might as well just use snapshot.

So is this a bug, or are the docs just wrong? Either answer is fine, I just need to know whether to patch it locally until it gets fixed upstream, or if I should architect my app differently.

Thanks!

**Comment by zoechi** [comment] 2016-10-21 15:50
@jamesmfriedman That's not the expected behavior. If only parameter values change, the component should not be reloaded. Please provide a Plunker that allows to reproduce. Probably better to create a new issue because it's not exactly what this issue is about.

**Comment by JoniJnm** [comment] 2016-10-31 17:20
Why the router doesn't work like angular 1?

- A: /users (component A)
- B1: /users/1 (component B, parent: A)
- B2: /users/2 (component B, parent: A)
- C1: /users/1/contacts (component C, parent: B)
- C2: /users/2/contacts (component C, parent: B)
- D: /groups

So:

- Go to A
 - A init
- Go to B1
 - A no changes
 - B init (user 1)
- Go to A
 - A no changes
 - B destroy
- Go to C1
 - A no changes
 - B init (user 1)
 - C init
- Go to B2
 - A no changes
 - B destroy (can't reuse component because there are different params, new data must be fetched)
 - C destroy
 - B init (user 2)
- Go to B1
 - A no changes
 - B destroy (same component, but diferent data, angular has to call the contructor, ngOnInit...)
 - B init (user 1)

Why the component should be reused when change from B1 to B2? If the component uses `Resolve`, you can't use `snapshot`, you have to subscribe to router params changes (so, duplicate fetch code in `Resolve` and `ngOnInit`). And if you do that, you can't make a generic spinner that is showed before navigation start and hidden after navigation ends. That's because ngOnInit neither constructor returns a promise (to know when the data is fetched).

If you want the `routerCanReuse` feature, it should be disabled by default.

**Comment by DzmitryShylovich** [comment] 2016-10-31 17:20
Because it's not angular 1

**Comment by JoniJnm** [comment] 2016-10-31 17:23
all features must be changed even if they work fine xd

**Comment by zoechi** [comment] 2016-10-31 17:39
Angular2 is a complete rewrite and is quite different to Angular1. If 1.x works better for you nobody forces you to 2.0

**Comment by DzmitryShylovich** [comment] 2016-10-31 17:53
@JoniJnm if u don't like official router impl u can use ui router https://ui-router.github.io/docs/latest/modules/ng2.html

**Comment by rigoleto** [comment] 2016-10-31 18:08
The Angular2 is obviously a completely new framework, but the default Reuse behavior is extremely surprising (and bug prone) whether or not you've used older versions of Angular. I expect complaints and issue threads to continue here until the default is made more sensible.

**Comment by JoniJnm** [comment] 2016-11-01 12:16
Simplified version in plunker: http://plnkr.co/edit/dsfsdyANmea1FLLuRWL5?p=preview

**Comment by vinaysoni** [comment] 2016-11-08 03:38
Router has been designed a third time. But it is still a failure. Here is why:

It creates a new component every time navigating to a different component type. This is a very bad design decision. Here is an example: A user may be in the middle of filling a long form on a tab1, he needs to lookup or verify some other details in tab2, when he comes back to tab1, everything is wiped out (as the component is re-instantiated). This implies that every time a user makes a change on a part of the UI, the state if the UI should be preserved (in anticipation of his unexpected navigation to another component, which co-exists on the same UI. This is simply too much work and doesn't make sense. 

What kind of design gives the router the right to destroy a component - just because the user is navigating somewhere to perform part of the same work? 
In every UI framework, I have worked, including Swing, JSF, Angular1, component tree is always sacrosanct. The default method of developing the UI is to assume that the nodes of the component tree can only be changed when the developer explicitly replaces/ deletes them.

There could have been a simple life cycle hook, an interface that the developer implements on the Component, and if the developer returns a true (reuse == true) a new component MUST NOT be instantiated and the existing one reused. What is the big deal with this. In absence of this, we need to maintain a cache of UI state and content of every component. On a complex UI, say with graphics and  multiple open tree controls, one would have to unnecessarily preserve the state of every bit of various widgets or graphics on the component, which is otherwise available without any work. This idea of destroying the component every time someone navigates to a different type of component pushes me to not even consider Angular2 for projects in my company. 

Just because someone is a contributor, they feel that they have the right to ask others to leave, is disgusting. The default design methodology in the UI world has been the assumption that the component tree will be preserved. Every developer is going to ask for this to be respected. Just because developers are asking this, doesn't mean they are told to leave and use  "https://ui-router.github.io/docs/latest/modules/ng2.html". We know about this project and it does do what is needed, but then why is this router the official Angular2 router? Or, is Angular2 team just not capable of providing this simple option?

In the end, a developer is told to use something that is official - and the poor guy has to endure the silly design decision. But this is a design decision that places severe limitation on what can be developed on complex UI components if temporary navigation is involved. 

And at that point, this poor design of Router number 3 reflects badly of the whole Angular2 framework.

**Comment by DzmitryShylovich** [comment] 2016-12-03 09:13
@vinaysoni https://github.com/angular/angular/pull/13124
https://www.softwarearchitekt.at/post/2016/12/02/sticky-routes-in-angular-2-3-with-routereusestrategy.aspx

**Comment by michalboska** [comment] 2016-12-05 14:55
Sticky routes are great thing and solve many kinds of issues (such as @vinaysoni has) but i would also prefer the opposite to be possible - telling router to reload the state (up to certain parent level or even root) - such as {reload: true} or {reload: 'app.somefeature.parent'} option in ui-router for angular1.

For me, just subscribing to data changes in the component is not enough - i have plenty (2-3) resolvers attached to more complex states that are injected into components, retrieve data from backend and need to be refreshed as well. And router currently does not refresh them.

In this case, i would have to manually orchestrate refresh of those resolvers from my component's subscription on route data Observable, but that's what the framework is for and should handle for me. 

I am using a really ugly hack right now
```
selectedCountryChanged(country: ICountry) {
		this.router.navigate(['/chronic', country.code, 'patient-prevalence'])
			.then(() => window.location.reload()); //fixme: Implement cleaner solution when Angular's Router supports refreshing components and routes
	}
```

and am really thankful to God that "changing the country" in this app basically means reloading the whole UI from the business point of view. So the client doesn't care if the whole window is reloaded in this case. 
Had the use case been different/more complex component tree with need to only reload a specific subtree, i could as well shoot myself in the head.

**Comment by vicb** [comment] 2016-12-08 00:37
The initial issue has been fixed with https://github.com/angular/angular/pull/13124.

For further/distinct issues, please open a distinct ticket. Thanks.

**Closed by vicb** 2016-12-08 00:37 UTC
Labels: comp: router, freq2: medium, type: feature

**Comment by viruskst** [comment] 2017-03-10 18:15
Just subscripte to ActivetedRoute the service will be called on paramters changes without recreating DOM.

` ngOnInit() {

    this.route.params.subscribe(res => {
      this.param = res['route-params'];

      this._service.getData( this.param ).subscribe(response => {
        this.dataObjects = response;
      });

    });`

**Comment by dalu** [comment] 2017-10-17 09:03
Yeah but for how long?
https://angular.io/guide/router
```


Two older properties are still available. They are less capable than their replacements, discouraged, and may be deprecated in a future Angular version.

params — An Observable that contains the required and optional parameters specific to the route. Use paramMap instead.

queryParams — An Observable that contains the query parameters available to all routes. Use queryParamMap instead.
```

always the wrong choice with Angular

**Comment by chriszrc** [comment] 2018-01-09 23:34
@viruskst  huh, this is exactly what I am doing, and I can see that the subscribe function is being executed, but the {{ param }} in the view isn't being updated. Is this a known issue?
