### ISSUE TITLE
How to get status of current build, as beta.1 seems to be completely broken..

### ISSUE THREAD

**Issue by born2net** [angular/angular#6574] opened 2016-01-19 23:07 UTC
I have developed this pretty heavy Angular2 app: http://ng2.javascriptninja.io ( https://github.com/born2net/ng2Boilerplate )
which works great on beta.0, but on beta.1 it completely explodes due to DI errors, noModel binding issues and more.. What's the best way of finding out the current passing status of a beta build?

I would hate to spend hours and hours trying to get http://ng2.javascriptninja.io working just to find that beta.1 is broken on core functionality... I invite any of the ng2 team to take a look at http://ng2.javascriptninja.io and see if they can figure out why the app blows on current beta.1 (works great in beta.0).

I did go over the latest release notes for beta.1 and I don't see major changes that would cause the app to fail... basically what I am trying to say is that it's hard for me to gauge how good or bad the current beta.1 release is...

regards

Sean.

**Comment by ThiagoT1** [comment] 2016-01-20 02:33
beta.1's changelog states this:
```Component view is not yet created when component constructor is called. -> use onInit lifecycle callback to access the view of a component```

Yet you seem to be doing a lot of stuff inside constructors, including selecting DOM elements.
Could that be the culprit?

**Comment by zoechi** [comment] 2016-01-20 09:09
@born2net please add concrete information about concrete issues (minimal verifiable example). You can't expect the Angular team to debug your application.

**Comment by AerisG222** [comment] 2016-01-20 12:50
I had an issue when I had tried to upgrade to beta.1 as well.  I had found a note about the minification having troubles with this release on gitter, and after swapping out angular2.min.js with angular2.js my apps started working again.  Might be worth a try.

**Comment by ericmartinezr** [comment] 2016-01-20 12:52
Guys, this is pure spam, lol...

**Comment by pkozlowski-opensource** [comment] 2016-01-20 13:13
@born2net I just had a brief look at your starter kit and frankly, it is quite big and far from being trivial. You really can't reasonably expect anyone to do the debugging / investigation for you on a project of this size. I'm afraid that you will have to try to isolate an issue a bit more.

beta.1 should be as stable as it gets - the only things that might break and we know of are:
* listed in the changelog
* issues fixed in master since beta.1
* issues opened on GitHub since beta.1 (although there is low signal / noise ratio...)

I would suggest going over the above, trying to isolate the problem and opening a concrete issue with a minimal, live reproduce scenario (plunker or similar).

I'm going to close this one as this issue, as it stands, is not actionable on our side.

**Closed by pkozlowski-opensource** 2016-01-20 13:13 UTC

**Comment by born2net** [comment] 2016-01-20 14:13
tx, I will work on this today and report my findings....
regards
