### ISSUE TITLE
Ability to set default component Change detection strategy

### ISSUE THREAD

**Issue by spock123** [angular/angular#58480] opened 2024-11-02 19:23 UTC
### Description

A common scenario is to have an application where all components use `ChangeDetectionStrategy.OnPush`

This requires importing `ChangeDetectionStrategy` from `@angular/core`, and adding the line `changeDetection: ChangeDetectionStrategy.OnPush` in  component declarations.

This process is repeated in every component in the application.

### Proposed solution

Allow a configuration to set the default change detection strategy, for example by introducing a `withChangeDetectionStrategy(strategy)` function for the configuration.

This would remove a lot of boilerplate code in every component.

We can configure CLI to add this line when creating new components, but some of us do not use the CLI to generate components, and it would still generate boilerplate code, making component code more cluttered.

### Alternatives considered

Apologies if this is already possible, for example by setting the ChangeDetectionStrategy in the `Root` component. But it is my impression that currently we have to set it in every component.

**Comment by JeanMeche** [comment] 2024-11-03 00:35
Duplicate of #55023

**Closed by JeanMeche** 2024-11-03 00:35 UTC
