### ISSUE TITLE
Misleading error message "Cannot find a differ supporting object '[object Object]'"

### ISSUE THREAD

**Issue by wardbell** [angular/angular#6392] opened 2016-01-11 01:38 UTC
This error message gives us no clue as to what is wrong or what to do. 
### Repro

Misko and I experienced this while refactoring a Component from one using the async pipe to one using an array.

The async pipe version:

```
    heroes: any;

    // <li *ngFor="#hero of heroes | async">
    this.heroes = this._heroService.getHeroes();
```

The refactored version:

```
    // <li *ngFor="#hero of heroes">
    this.heroes = this._heroService.getHeroes()
                      .subscribe(heroes => this.heroes = heroes);
```

The exception was:

```
EXCEPTION: Cannot find a differ supporting object '[object Object]' in [heroes  in TohComponent@4:8]
```
### Discussion

Do you see our mistake ... the one that threw the error?  We didn't ... for about 5 head-scratching minutes (see [below](#answer)).

The developer has no idea what a "differ" is, what it is that the "differ" can't support, what might cause this, or what to do.

The "[heroes  in TohComponent@4:8]" didn't help because line 4 of that component file is an import statement in the TS and nowhere near the template or the function in the transpiled JS. Something called "heroes" appears all over the place. 

FWIW, I've received this error several times and I think the cause (bad list) was always the same.

<a id="answer"></a>
Our mistake: after refactoring we were still assigning an observable to `this.heroes`.
### Recommended solution

Improve error message. Link to problem/solutions page?

**Comment by brycepj** [comment] 2016-01-11 06:46
+1 - ran into this last week

**Comment by evanplaice** [comment] 2016-01-13 20:48
I just ran into the same issue. I'm not sure if the recommended solution will work for my case.

I'm using an observer to pull a more complicated data structure from an external source (ie an observer on a service that persists the result of a GET request).

The part I'm trying to iterate over is a subset of the external source.

**Data:**
```
{
  "location": {
    "address": "2445 Torrejon Pl",
    "city": "San Diego",
    "region": "CA",
    "code": "92009",
    "country": "US"
  },
  "social": [
    {
      "label": "",
      "network": "GitHub",
      "user": "evanplaice",
      "url": "https://github.com/evanplaice"
    },
    {
      "label": "",
      "network": "Twitter",
      "user": "@evanplaice",
      "url": "https://twitter.com/evanplaice"
    },
    {
      "label": "",
      "network": "StackOverflow",
      "user": "evanplaice",
      "url": "http://stackoverflow.com/users/290340/evan-plaice"
    },
    {
      "label": "",
      "network": "HackerNews",
      "user": "evanplaice",
      "url": "https://news.ycombinator.com/user?id=EvanPlaice"
    }
  ],
...
```
The source has more data but the point is, I want to extract the `social` array and iterate over it in my template.

```html
<ul *ngFor="#profile of vitae.social">
  <li>{{ profile.network }}: <a href="{{ profile.url }}">{{ profile.user }}</a></li>
</ul>
```

Angular can't seem to recognize that the incoming data data is nothing more than an array of objects. 
To workaround, I created a hack that just creates a new array from the incoming array.

```javascript
hack(val) {
  return Array.from(val);
}
```

```html
<ul *ngFor="#profile of hack(vitae.social)">
  <li>{{ profile.network }}: <a href="{{ profile.url }}">{{ profile.user }}</a></li>
</ul>
```
-----

The funny thing is, if I log the data before and after the hack it's virtually identical.

*Using:*
```javascript
hack(val) {
  console.log('Before:');
  console.log(val);
  val = Array.from(val);
  console.log('After:');
  console.log(val);
  return val;
}
```

*Result:*
![screen shot 2016-01-13 at 12 40 04 pm](https://cloud.githubusercontent.com/assets/303159/12307229/cf44bbd8-b9f2-11e5-9788-039666e807e6.png)

![imgres](https://cloud.githubusercontent.com/assets/303159/12307346/99279bb4-b9f3-11e5-8e7b-1f7366ee00a5.jpg)

**Comment by evanplaice** [comment] 2016-01-16 03:47
Here's the hack (endearingly named DerpPipe) that can be used to workaround the issue.

```
import { Pipe } from 'angular2/core';

/*
  # Description:

  Repackages an array subset as a new array.

  **Reasoning:**

  Angular2's change checker freaks out when you ngFor an array that's a subset
    of a larger data structure.

  # Usage:
  ``
  <div *ng-for="#value of arrayOfObjects | derp"> </div>
  ``
*/
@Pipe({ name: 'derp' })
export class DerpPipe {
  transform (value, args) {
    return Array.from(value);
  }
}
```

**Comment by PascalPrecht** [comment] 2016-01-17 23:11
So, I think that still assigning an observable to `this.heroes` after the refactor, is just one of those dumb things we developers sometimes run into. I don't think there's anything that Angular can help with here. 

I *DO* agree, that this error message is very unhelpful as @wardbell pointed out. It's not clear what a differ is, it's not clear what the differ can't support. We should definitely improve this error message with something more useful.

**Comment by webtrix** [comment] 2016-01-19 13:16
Maybe just a dumb question, but won't there be a final solution for this problem? Or is this a problem that I as a developer must fix?  I saw in an issue that the Angular team is going to add an extra pipe functionality to *ngFor, being mapToIterable - [see issue here](https://github.com/angular/angular/issues/2246#issuecomment-107212606)

**Comment by evanplaice** [comment] 2016-01-19 13:37
@webtrix I think this is a fundamental weakness of the Angular2 differ that needs to be identified. It doesn't just apply to iterating over object values. It applies to any case where a dev tries to iterate over a property of a larger object structure.

To illustrate, imagine I have my resume stored in a resume.json format and want to load the data directly into a web template.

*Example:*

```json
{
  "location": {},
  "employment": {},
  "projects": [],
  "skills": {},
}
```

So, I create a service that handles the resume data. Including a model, method to fetch the resume via HTTP, and an observable to provide access to components that inject the service.

-----

There are 2 different approaches to managing data.

**Approach 1 - Use one model to represent all data:**

This is by far the easier approach. Specifying a basic model that represents the data as well as the ability to initialize to empty values (ie to avoid variable uninitialized errors in the template) is pretty easy and straightforward.

```javascript
export class ResumeModel {
  location = {};
  employment = {};
  projects = [];
  skills = {};

  constructor (obj) {
    for (var prop in obj) this[prop] = obj[prop];
  }
}
```

The service only requires one observable to represent the structure, so wiring it up to a component is a piece of cake.

Unfortunately, when you write a `ngFor` to iterate over `resume.projects` the differ is going to throw the error described above. That's where the `DerpPipe

**Comment by webtrix** [comment] 2016-01-19 14:06
Thanks for the info @evanplaice! I have now created a custom pipe that solves the problem, based on this solution I found on [StackOverflow](stackoverflow.com/questions/31490713/iterate-over-typescript-dictionary-in-angular-2#answer-34074484)

Sorry to go off-topic, but what's a or the differ?

**Comment by zoechi** [comment] 2016-01-19 14:11
fixed StackOverflow link from @webtrix' comment https://github.com/angular/angular/issues/6392#issuecomment-172863571
https://stackoverflow.com/questions/31490713/iterate-over-typescript-dictionary-in-angular-2#answer-34074484

**Comment by evanplaice** [comment] 2016-01-19 14:29
@webtrix That'll work but you're still going to face the same problem. Piping the data into a new data structure breaks you ability to update the source data.

It's effectively breaking the link to the source data. Not a big deal if you only intend to use the data in a read-only manner. It may create a very hard-to-fix bug if you *do* plan to write the data back to the source object.

Unfortunately, this is the borderline where the Angular2 dirty checker abstraction leaks. Any dev that does a considerable amount of data manipulation will eventually run into this issue.

**Comment by webtrix** [comment] 2016-01-19 14:40
@evanplaice ... hmm OK. That sucks!!  So as I understand correctly, by creating this fix (pipe) I actually break the two way binding possibility on my object?  Hmm.. I don't see the logic behind not fixing this issue.

**Comment by evanplaice** [comment] 2016-01-19 15:29
@webtrix AFAIK, yes. I'm not sure if it *can* be fixed in your case.

Think about it for a second. Not only are you breaking the reference to the source object (ie by creating a new one) you're also trying to implicitly compare two fundamentally different data types, `object === array.` To make that work you would have to monkey patch both the `Array` and `Object` prototypes with special implicit comparators.

The comparator would have to:
- have implicit knowledge of the original data type
- convert the data back to the original type
- diff the data against the representation stored on the VDOM
- update the references if a change occurred
- convert the data back to the new type
- update the view

Databinding isn't magic. Underneath the covers, what it does is link the reference of the the data representation contained in the virtual DOM to the the view. Overwriting the reference in the view breaks the databinding.

Of course, there *may* be a solution. This is what I have inferred so far by using Angular2 to build an app. My understanding probably pales in comparison to that of one of the core devs.

Once they get caught up a bit on the backlog if issues (I don't pity them seeing the flood of new issues since the beta release) maybe one of them will be able to chime in with better info.

**Comment by NeuronQ** [comment] 2016-02-27 17:54
I'm sorry for a probably uninformed comment, I'm **very** new to Angular 2. And I just came over this error with the code from the [official Angular 2 tutorial](https://angular.io/docs/ts/latest/tutorial/toh-pt4.html) that threw me a wonderful `EXCEPTION: Cannot find a differ supporting object '[object Object]' in [heroes in AppComponent@4:16]` (!!).

...but aren't you talking about solving this at the wrong level? Should'n the actual mycrosyntax `#item of items` be made "smart enough" to just be able to iterate over "almost anything" (like be smart enough to handle `Array`, `Promise<Array>`, `Object`, `Promise<Object>` etc.). Should a developer actually need to care what he/she is iterating over when writing a *template?*

**Comment by jrisk** [comment] 2016-03-12 05:44
I came to this issue from the opposite end, having my Service class with a method of 
`getNewPlans() {
		return this.http.get('events.json').map(res => res.json());
	}`
my Component class with a method of
`ngOnInit() {
		Promise.resolve(this._newPlanService.getNewPlans()).then(newplans => this.newplans = newplans);
	}`
and then discovering I need to pipe async for it to stop giving that error about a differ supporting object
`<div *ngFor="#newplan of newplans">` to `<div *ngFor="#newplan of newplans | async">`

**Comment by robwormald** [comment] 2016-03-12 07:30
@wardbell in your example, you're assigning a *Subscription* to the this.heroes property, not an Observable. Typescript should catch this, though I agree the error message could be better. The only thing we can really say is "you're not iterating over an array, you should be"?

There's a lot of mixed information going on here, let me see if I can clear it up.

First, pretty much anything that is not a primitive value (string, boolean, number) in Javascript is an Object. This includes Promises, Observables, Arrays, etc - they all are subtypes of Object.

An *Iterable* in javascript is, in the simplest terms, a "collection" - it's a data structure that allows *iteration* in an ordered manner. Arrays are the most common example of this. All arrays are iterable, but  plain objects are *not* - importantly, the ecmascript specification does not guarantee the order of items in an Object - whereas an Array does guarantee order. 

The `IterableDiffer` you see in the error message is an angular mechanism that compares two collections (iterables) and returns:
- objects added to the collection
- objects removed from the collection
- objects that have changed their position in the collection

We do this to enable, for example - animations - we can tell when an item has moved from position 3 to position 0 in an array, so it can be appropriately animated:
```js
//psuedo code!
//given two arrays:
let a = [1,2,3];
let b = [3,2,4];
iterableDiffer.create(a).diff(b) // 1 is removed, 4 is added, 2 and 3 are moved

```

Part of the reason (the other is performance) we don't support objects in ngFor/differs is that this mechanism doesn't work for objects - consider:

```js
var foo = {};
foo.a = 1;
foo.b = 2;
Object.keys(foo) // [ 'a', 'b' ]
delete foo.a;
foo.a = 1;
Object.keys(foo) // [ 'b', 'a' ]
```
Objects have no concept of *order* - typically the keys are returned in insertion order (as above) - and so ngFor'ing over them doesn't make sense! 

You could, of course, implement your own objectToKeys pipe, but then you run into ordering problems, and thus you have to maintain the sort order yourself somehow - there are a lot of edge cases here that might impact performance so we leave it up to the developer. 

Regarding @evanplaice's example above - it's important to understand how javascript handles values and references:
```js
//imagine you have an object of objects:
this.foos = {
  a: { name: 'fooA'}
  b: { name: 'fooA'}
}
//turn this into an array
this.listOfFoos = Object.keys(this.foos).map(key => this.foos[key]) // [{name: 'fooA'}, {name: 'fooB'}];

//objects are copied by reference:
this.foos.a === this.listOfFoos[0] //true -> they are the same reference
this.foos.a.name = 'fooA!'
console.log(this.listOfFoos[0]) // { name: 'fooA!' }
```
So simply moving an object from one structure to another does not "break" the reference - they would continue to update. See plunker: https://plnkr.co/edit/34dPSfL0bIDfGkdySExX?p=preview

The same does *not* hold true for primitive values:
```js
//imagine you have an object of numbers:
this.foos = {
  a: 1
  b: 2
}
//turn this into an array
this.listOfFoos = Object.keys(this.foos).map(key => this.foos[key]) // [1, 2];

//values are simply copied
this.foos.a === this.listOfFoos[0] //true -> they are the same value
this.foos.a = 3 //change the value
console.log(this.listOfFoos[0]) //still 1
```
So with primitive values, they *are* "disconnected"

All of the above deals with simple synchronous values. The second round of confusion here has to do with Promises and Observables. You can deal with async values in Angular in the following ways:

By simply `.then()` or `.subscribe()` to a Promise or Observable, respectively, and assigning the output value:
```js
somePromiseThatGetsAnArrayOfFoos().then(foos => {
  this.foos = foos;
});

someObservableOfArrayOfBars.subscribe(bars => {
  this.bars = bars; 
});

```
To render these, you can simply ngFor over them:
```html
<ul>
  <li *ngFor="#foo of foos">{{foo.name}}</li>
</ul>
<ul>
  <li *ngFor="#bar of bars">{{bar.name}}</li>
</ul>
```
What you *cannot* do here is *ngFor over a sub-property of an async delivered value - because when the view is initially rendered, the parent property is undefined.
```js
//this.foo is undefined here!
somePromiseThatGetsAnObjectWithNestedBars().then(foo => {
 //  { bars: [ 1, 2, 3] }
  this.foo = foo;
});
```
So doing 
```html
<ul>
  <li *ngFor="#bar of foo.bars">{{bar}}</li>
</ul>
```
Will throw an error: `EXCEPTION: TypeError: Cannot read property 'bars' of undefined in [foo.bars]`
because foo is undefined on initial render.

This is *exactly* the same behavior you see in regular Javascript:
```
var foo;

somePromise.then(fooData => {
  foo = fooData;
});
console.log(foo.bars) //Uncaught TypeError: Cannot read property 'bars' of undefined(…)
```
The simple fix is to use the ? operator: 
```html
<ul>
  <li *ngFor="#bar of foo?.bars">{{bar}}</li>
</ul>
```

The other way of handing async values is to use the `async` pipe:
```js
this.foos = somePromiseThatReturnsFoos();
this.bars = someObservableOfBars;
```
```html
<ul>
  <li *ngFor="#foo of foos | async">{{foo.name}}</li>
</ul>
<ul>
  <li *ngFor="#bar of bars | async">{{bar.name}}</li>
</ul>
```
Note here that we're assigning the *Promise / Observable* to the class, *not* the result of `.then()` / `.subscribe()` 

To handle nested values, you can use the same ? operator:
```html
<ul>
  <li *ngFor="#bar of (foo | async)?.bars">{{bar}}</li>
</ul>
```

The same rules apply here with copy-by-value and copy-by-reference - so you could, in theory, store the returned objects in a service, return them in a promise, and two-way binding will work, as long as you maintain the references. 

Summary:
- collections of things should almost always be kept in arrays if order is important.
- be sure to understand the difference between assigning an array to `this` and assigning a Promise or Observable of values to `this`
- Databinding works fine as long as you aware of the semantics of javascript references.
- Don't attempt to access properties of undefined values that may be delivered at a later time.

**Comment by burkeholland** [comment] 2016-04-22 20:53
Whoa! Just lost 30 minutes on this one. In my case I was simply not assigning the loop to the right collection, and instead assigned it to a component class. Would the error be more accurate if we at least prefixed it with "Unable to execute for loop on [Object object]"? The differ stuff can stay, but the fundamental error is a goose chase as is.

**Comment by evanplaice** [comment] 2016-05-04 16:02
@robwormwald Thos os probably a dumb question.

What of an app pulls data from a remote API as a large nested data structure. Can nested list values be iterated without triggering an update on sibling values -- assuming the parent object reference isn't updated?

Is ngrx-store a better fit for such a use case?

**Comment by salibhai1** [comment] 2016-05-21 21:46
@evanplaice  I updated the code to work with latest angular:

```
//https://github.com/angular/angular/issues/6392#issuecomment-172152071
import { Pipe } from '@angular/core';

/*
  # Description:

  Repackages an array subset as a new array.

  **Reasoning:**

  Angular2's change checker freaks out when you ngFor an array that's a subset
    of a larger data structure.

  # Usage:
  ``
  <div *ng-for="#value of arrayOfObjects | derp"> </div>
  ``
*/
@Pipe({ name: 'derp' })
export class DerpPipe implements PipeTransform {
  transform (value, args) {
    return [value];
  }
}
```

**Comment by m1sh2** [comment] 2016-06-08 22:44
@salibhai1 update the `import` line please, from

`import { Pipe } from '@angular/core';`

to

`import { Pipe, PipeTransform } from '@angular/core';`

**Comment by m1sh2** [comment] 2016-06-08 23:09
@evanplaice @salibhai1 I updated it a little bit, for **async**:
```
//https://github.com/angular/angular/issues/6392
import { Pipe, PipeTransform } from '@angular/core'

/*
  # Description:

  Repackages an array subset as a new array.

  **Reasoning:**

  Angular2's change checker freaks out when you ngFor an array that's a subset
    of a larger data structure.

  # Usage:
  ``
  <div *ng-for="#value of arrayOfObjects | derp"> </div>
  ``
*/
@Pipe({
  name: 'derp',
  pure: false
})
export class DerpPipe implements PipeTransform {
  private result: Array<any>

  transform(value, args) {
    this.result = []
    value.subscribe(values => {
      if (Array.isArray(values))
        this.result = Array.from(values)
      else
        this.result = [values]
    })
    return this.result
  }
}
```

**Comment by m1sh2** [comment] 2016-06-09 22:49
@evanplaice 
Do you mean @robwormald 's solutions like this `*ngFor="#bar of foo?.bars"` and this `*ngFor="#bar of (foo | async)?.bars"`?

When I'm using `*ngFor="#bar of bars | async"` I have an exception about `diff [object Object]...`.
I have an array of objects is like this:
```
[
  {
    prop1: string,
    prop2: string,
    prop3: string,
    prop4: {
      prop1: string,
      prop2: string
    }
  },
  ...
]
```
and after some r&d I found that the exception is because of `prop4`, it can't be an `Object`. There must be an array with flat structure.

My solution maybe not very good for `http`, but I'm using `ngrx` and I didn't find better yet.
Maybe you know what could be better for it?

**Comment by evanplaice** [comment] 2016-06-09 23:23
@m1sh2 Yes. Sorry, I forgot to add the code block.

The ideal solution would to be to change prop4 to an array. If that's not possible then DerpPipe may be the only option.

The unnecessary change detection cycling will occur because DerpPipe creates a new Array object (and therefore a new reference) every time it's read. If all of the incoming data on your component (and it's subtree) is from observables you could modify the `ChangeDetectionStrategy` to avoid the unnecessary cycling.

I haven't used `ngrx` yet so I'm only remotely familiar with it. @robwormwald is the dev of `ngrx` so I'd follow his advice above.

**Comment by m1sh2** [comment] 2016-06-09 23:34
@evanplaice I see. Yes, I can't change the structure (I can, it is just an api response, I'll think about it).
Thank you.

P.S.: I think I need to play with `ChangeDetectionStrategy` restrictions

**Comment by pkozlowski-opensource** [comment] 2016-11-02 15:31
The error message is slightly improved now and reads as: `Error in ./App class App - inline template:2:10 caused by: Cannot find a differ supporting object '[object Object]' of type 'object'. NgFor only supports binding to Iterables such as Arrays.`: http://plnkr.co/edit/ONXPrD0ezmefiVIZpEYe?p=preview

I think that this is as far as we can get with simple error message changes. The next big improvement could come from having a dedicated pages for each error type - there we could list common issues and offer alternatives.

I'm going to close this issue since an error message is better now and having dedicated error pages is beyond the scope of this issue.

**Closed by pkozlowski-opensource** 2016-11-02 15:31 UTC
Labels: comp: common, hotlist: error messages

**Comment by pabx06** [comment] 2017-03-21 10:45
i have the folowing working but dont know i had put select:'search'

`<div *ngFor="let song of songs | async| select :'search'"`

`songs:` Observable<Song[]>;``

cant find the documentation of select pipe. search is class method that update songs

**Comment by DzmitryShylovich** [comment] 2017-03-21 10:52
> cant find the documentation of select pipe

there's no `select` pipe in angular

**Comment by pabx06** [comment] 2017-03-21 11:08
@DzmitryShylovich i am not sure however found that in fact songs is an object wrapping an array:

`{
  "search": [
    {
      "SNG_ID": "80460342",
      ...
    },
   ..
  ]
}
`

using select select the array

**Comment by osazemeu** [comment] 2017-04-13 13:37
Just felt I could point this out. I solved this issue from my backend (RubyonRails).
I made the following modifications

`render json: @whatever`
to
`render json: {:whatever => @whatever}`

**Comment by MikhaelGerbet** [comment] 2017-06-25 12:18
My participation ;) 

```ts
import { Pipe, PipeTransform } from '@angular/core';
/*
 # Description:

 Repackages an array subset as a new array.

 **Reasoning:**

 Angular2's change checker freaks out when you ngFor an array that's a subset
 of a larger data structure.

 # Usage:
 ``
 <div *ng-for="#value of arrayOfObjects | derp"> </div>
 ``
 */
@Pipe({
  name: 'derp'
})
export class DerpPipe implements PipeTransform {
  transform(value: any, args?: any): any {
    return Array.isArray(value) ? Array.from(value) : [value];
  }
}
```

**Comment by MikhaelGerbet** [comment] 2017-06-25 13:04
But in case, it's not perfect because i need display the key name. So, i use this : 

```
import { Pipe, PipeTransform } from '@angular/core';
/*
 # Description:

 Repackages an array subset as a new array.

 **Reasoning:**

 Angular2's change checker freaks out when you ngFor an array that's a subset
 of a larger data structure.

 # Usage:
 ``
 <div *ngFor="#entry of content | keys">
 Key: {{entry.key}}, value: {{entry.value}}
 </div>
 ``
 */
@Pipe({
  name: 'keys'
})
export class KeysPipe implements PipeTransform {
  transform(value, args:string[]) : any {
    let keys = [];
    for (let key in value) {
      keys.push({key: key, value: value[key]});
    }
    return keys;
  }
}
```

**Comment by jgfet** [comment] 2017-08-11 11:19
I received this error in my code because I'd not run JSON.parse(result). So my result was a string instead of an array of objects, ie I got "[{},{}]", instead of [{},{}].
import { Storage } from '@ionic/storage'; 
...
private static readonly SERVER = 'server';
...
 getStorage(): Promise<string> {
    console.log('getStorage()');
    return this.storage.get(LoginService.SERVER);
  }

  this.getStorage()
    .then((value) => {
                       let servers: Server[] = **JSON.parse(value)** as Server[];
                                }
    );

**Comment by polyglotinc** [comment] 2017-08-22 07:12
hmmm... I get this "Error: Cannot find a differ supporting object " error,
but only when running prod build code.
When I simply `ng serve` it works fine with no errors.

**Comment by mantchido** [comment] 2017-09-07 12:31
@evanplaice Thanks. It worked for me.

**Comment by EvanCarroll** [comment] 2017-09-08 23:55
I got this error going on a different however I do believe it is related. Essentially, all I did was send a text string to `ngStyle` that looked like an object. Rather than sending the object itself.

https://stackoverflow.com/q/46125853/124486

**Comment by helmutgranda** [comment] 2017-09-21 21:54
After reading the thread and looking for solutions online I ended up using ```JSON.stringify()``` before passing the element to the child and then ```JSON.parse```. It is working but I am sure it has something to do with the way I am passing the data.
Parent From:
```
<div *ngFor="let item of parentGroup">
<custom-component title="{{item.title}} elements={{item.arrayElements}}></custom-component>
</div>
```

Parent To:
```
<div *ngFor="let item of parentGroup">
<custom-component title="{{item.title}} elements={{utility(item.arrayElements)}}></custom-component>
</div>
```
utlility simple does the following
```
JSON.stringify(val);
```

Child From:
```
<div *ngFor="let child of elements">
<custom-component title="{{child.title}}></custom-component>
</div>
```

Parent To:
```
<div *ngFor="let child of childUtility(elements)">
<custom-component title="{{child.title}}></custom-component>
</div>
```
childUtility simply does the following
```
JSON.parse(val);
```

It works but I am sure there is an easy way and I am missing a key concept somewhere to avoid this horrendous hack.

**Comment by Trokal** [comment] 2017-11-10 18:37
facing the same problem! nothing have been done to fix this issue yet?

**Comment by Fallenstedt** [comment] 2017-11-13 23:39
Bumping as I am experiencing the same issue.

**Comment by PascalPrecht** [comment] 2017-11-14 09:30
@Trokal @Fallenstedt 

The issue has been closed with this comment: https://github.com/angular/angular/issues/6392#issuecomment-257900742

The error message has been improved.

**Comment by tayfoooooor** [comment] 2017-11-20 16:58
@jrisk thaaaaaaaaaaaaaanks It's work for me :+1: 
and then discovering I need to pipe async in my View template for it to stop giving that error about a differ supporting object
<div *ngFor="#newplan of newplans"> to <div *ngFor="#newplan of newplans | async">

**Comment by tatianajiselle** [comment] 2017-12-04 22:31
Is a hack really the best workaround for this currently?

Any potential resolutions at a lower level for such a problem as this?

**Comment by akashennn** [comment] 2017-12-26 06:38
**MY API Returns this,**

```
{
    "reports": [
        {
            "patientId": "5a3d2a717b88b525150a14e5", 
            "screening_report_status": "Screening", 
            "screening_urine_albumin_test": "nil", 
            "screening_creatinine_blood_test": "10", 
            "screening_estimated_glomerular_filtration_rate": "2", 
            "createdAt": "2017-12-22T15:53:30.653Z", 
            "updatedAt": "2017-12-22T15:53:30.653Z", 
            "id": "5a3d2a7a7b88b525150a14e6"
        }, 
        {
            "patientId": "5a3d2a717b88b525150a14e5", 
            "status": "Diagnose-Level-04", 
            "diagnosis_creatinine_blood_test": "1", 
            "diagnosis_uric_acid_test": "2", 
            "diagnosis_total_protein_test": "3", 
            "diagnosis_albumin_test": "4", 
            "diagnosis_globulin_test": "5", 
            "diagnosis_serum_cholesterol_test": "6", 
            "diagnosis_serum_calcium_test": "7", 
            "diagnosis_serum_phosphorous_test": "8", 
            "diagnosis_serum_electrolytes_test": "9", 
            "diagnosis_estimated_glomerular_filtration_rate": "10", 
            "diagnosis_u_protein_creatitine_ratio": "11", 
            "diagnosis_hb": "12", 
            "diagnosis_pcv": "13", 
            "diagnosis_wbc": "14", 
            "diagnosis_dc": "15", 
            "diagnosis_platelet_count_test": "16", 
            "diagnosis_additional_test": "17", 
            "diagnosis_additional_test_unit": "*", 
            "createdAt": "2017-12-22T16:24:02.622Z", 
            "updatedAt": "2017-12-22T16:24:02.622Z", 
            "id": "5a3d31a28c373d1400efb2af"
        }, 
        {
            "patientId": "5a3d2a717b88b525150a14e5", 
            "screening_report_status": "Screening", 
            "screening_urine_albumin_test": "+++", 
            "screening_creatinine_blood_test": "100", 
            "screening_estimated_glomerular_filtration_rate": "200000", 
            "createdAt": "2017-12-26T06:03:01.099Z", 
            "updatedAt": "2017-12-26T06:03:01.099Z", 
            "id": "5a41e61505bdd814007a841b"
        }
    ], 
    "feedbacks": [
        {
            "patientId": "5a3d2a717b88b525150a14e5", 
            "type": "CKD", 
            "notes": "Cool guy.", 
            "createdAt": "2017-12-22T15:53:37.454Z", 
            "updatedAt": "2017-12-22T15:53:37.454Z", 
            "id": "5a3d2a817b88b525150a14e7"
        }, 
        {
            "patientId": "5a3d2a717b88b525150a14e5", 
            "type": "Other", 
            "notes": "Not cool he's awesomeeee!", 
            "createdAt": "2017-12-26T06:18:00.474Z", 
            "updatedAt": "2017-12-26T06:18:00.474Z", 
            "id": "5a41e99805bdd814007a841c"
        }
    ], 
    "name": "Akash Perera", 
    "nic": "20000000V", 
    "family_members": "5", 
    "weight": "100", 
    "height": "180", 
    "moh": "Colombo", 
    "gs": "LK001", 
    "cholesterol": true, 
    "diabetes": true, 
    "createdAt": "2017-12-22T15:53:21.568Z", 
    "updatedAt": "2017-12-22T15:53:21.568Z", 
    "id": "5a3d2a717b88b525150a14e5"
}
```
**My Requirement was to show all the reports of my Patient.**

**PatientComponent.html**

```
<ul class="list-group list-group-flush" *ngFor="let data of patientData.feedbacks">
          <li class="list-group-item">
            {{ data.type }} | {{ data.notes }}
          </li>
 </ul>
```

This works without any issues. Hope this helps! :)

**Comment by ivanfretes** [comment] 2018-01-17 09:27
My Solution is create a Pipe for return the values array or propierties object
```

import { Pipe, PipeTransform } from '@angular/core';

@Pipe({
  name: 'valueArray',
})
export class ValueArrayPipe implements PipeTransform {

  // El parametro object representa, los valores de las propiedades o indice
  transform(objects : any = []) {
    return Object.values(objects);
  }
}


```

The template Implement

```
 <button ion-item *ngFor="let element of element_list | valueArray" >
      element.any_property
 </button> 
```

**Comment by M-S** [comment] 2018-02-05 10:48
For a nested object eg: details.firstName, on giving ngIf ="details" eliminates the error 
_ERROR TypeError: Cannot read property 'firstName' of undefined_

 `<div *ngIf = "details">
        <div class="row">
          <div class="col-xs-4">
            <small class="stats-label">First Name</small>
            <h4>{{details.firstName}}</h4>
          </div>
          <div class="col-xs-4">
            <small class="stats-label">Email</small>
            <h4>{{details.email}}</h4>
          </div>
        </div>
      </div>

**Comment by h-arora** [comment] 2018-05-13 19:43
Iterating a subset of data returned from an API is a very common scenario. There should be a cleaner way to address this when we have to not only read but also update the collection.

**Comment by Goldenflamer** [comment] 2018-05-13 21:14
This is not fixed still an issue

**Comment by h-arora** [comment] 2018-05-13 21:33
Not sure if it is still an issue coz i got it working with angular 5.2

**Comment by Goldenflamer** [comment] 2018-05-20 20:17
It was my own fault sorry.

**Comment by SwapnilSoni1999** [comment] 2018-12-22 21:19
i have made array of object and it works still it throws error in console but stuff is working lol

**Comment by s106667** [comment] 2019-02-20 10:08
> I just ran into the same issue. I'm not sure if the recommended solution will work for my case.
> 
> I'm using an observer to pull a more complicated data structure from an external source (ie an observer on a service that persists the result of a GET request).
> 
> The part I'm trying to iterate over is a subset of the external source.
> 
> **Data:**
> 
> ```
> "vitae": {
>   {
>     "location": {
>       "address": "2445 Torrejon Pl",
>       "city": "San Diego",
>       "region": "CA",
>       "code": "92009",
>       "country": "US"
>     },
>     "social": [
>       {
>         "label": "",
>         "network": "GitHub",
>         "user": "evanplaice",
>         "url": "https://github.com/evanplaice"
>       },
>       {
>         "label": "",
>         "network": "Twitter",
>         "user": "@evanplaice",
>         "url": "https://twitter.com/evanplaice"
>       },
>       {
>         "label": "",
>         "network": "StackOverflow",
>         "user": "evanplaice",
>         "url": "http://stackoverflow.com/users/290340/evan-plaice"
>       },
>       {
>         "label": "",
>         "network": "HackerNews",
>         "user": "evanplaice",
>         "url": "https://news.ycombinator.com/user?id=EvanPlaice"
>       }
>     ],
> ...
> ```
> The source has more data but the point is, I want to extract the `social` array and iterate over it in my template.
> 
> ```
> <ul *ngFor="#profile of vitae.social">
>   <li>{{ profile.network }}: <a href="{{ profile.url }}">{{ profile.user }}</a></li>
> </ul>
> ```
> 
> Angular can't seem to recognize that the incoming data is nothing more than an array of objects.
> To workaround, I created a hack that just creates a new array from the incoming array.
> 
> ```js
> hack(val) {
>   return Array.from(val);
> }
> ```
> 
> ```
> <ul *ngFor="#profile of hack(vitae.social)">
>   <li>{{ profile.network }}: <a href="{{ profile.url }}">{{ profile.user }}</a></li>
> </ul>
> ```
> 
> The funny thing is, if I log the data before and after the hack it's virtually identical.
> 
> _Using:_
> 
> ```js
> hack(val) {
>   console.log('Before:');
>   console.log(val);
>   val = Array.from(val);
>   console.log('After:');
>   console.log(val);
>   return val;
> }
> ```
> 
> _Result:_
> ![screen shot 2016-01-13 at 12 40 04 pm](https://cloud.githubusercontent.com/assets/303159/12307229/cf44bbd8-b9f2-11e5-9788-039666e807e6.png)
> 
> ![imgres](https://cloud.githubusercontent.com/assets/303159/12307346/99279bb4-b9f3-11e5-8e7b-1f7366ee00a5.jpg)

You solved my big problem. Thanks!!

**Comment by turbolego** [comment] 2019-03-28 11:11
I still get the error:

> Cannot find a differ supporting object '[object Object]' of type 'object'. NgFor only supports binding to Iterables such as Arrays.

I have tried both the "hack" and "DerpPipe" by @evanplaice , and other pipes by @MikhaelGerbet and @ivanfretes but there is no change in the error message or behaviour.

The code works fine tho, with or without any "hack" or pipes.
The error message is annoying.

**Comment by mlc-mlapis** [comment] 2019-03-28 11:21
@turbolego ... but you didn't show what data you use for `*ngFor`.
