### ISSUE TITLE
RC6 Forms: disabled attribute cannot be set dynamically anymore

### ISSUE THREAD

**Issue by Krisa** [angular/angular#11271] opened 2016-09-02 07:59 UTC
**I'm submitting a bug/feature request**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Have a look at that, (demo: http://plnkr.co/edit/P25dYPC5ChRxpyxpL0Lj?p=preview):
```
@Component({
  selector: 'my-app',
  providers: [],
  template: `
    <div [formGroup]="form">
      <input formControlName="first" [disabled]="isDisabled">
    </div>
  `,
  directives: []
})
export class App {
  isDisabled = true
  form = new FormGroup({
    'first': new FormControl('Hello')
  })
}
```

There is a warning message asking to refactor the code, but more importantly, the input is unfortunately not disabled. Refactoring the code to what is suggested is not helping either, i.e. doing this will not work, (demo: http://plnkr.co/edit/Gf7FGR42UXkBh6e75cm2?p=preview):
```
@Component({
  selector: 'my-app',
  providers: [],
  template: `
    <div [formGroup]="form">
      <input formControlName="first">
    </div>
  `,
  directives: []
})
export class App {
  isDisabled = false
  form = new FormGroup({
    'first': new FormControl({value: 'hello', disabled: this.isDisabled})
  })
  
  constructor() {
    setTimeout(() {
      this.isDisabled = true  
    }, 10)
  }
}
```

**Expected/desired behavior**
After the callback of the setTimeout is executed, the input should be disabled, but it is not.

**Reproduction of the problem**
Yes, please look here: http://plnkr.co/edit/P25dYPC5ChRxpyxpL0Lj?p=preview

**What is the motivation / use case for changing the behavior?**
To have the same behaviour, or similar one than in RC5. At least, we shall have a possibility, even if it's a breaking change, to set dynamically the `disabled` attribute. As of now, it does not seem possible anymore.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.6
 
* **Browser:** [ Chrome 52 ] 
 
* **Language:** [ TypeScript ]

**Comment by kara** [comment] 2016-09-02 23:13
@Krisa  If you want to set the disabled state programmatically, you'll need to call `disable()`.  Changing `this.isDisabled` will never have an effect because it is passed by value.

```ts
export class App {
  isDisabled = false
  form = new FormGroup({
    'first': new FormControl({value: 'hello', disabled: false})
  })
  
  constructor() {
    setTimeout(() => {
      this.form.get('first').disable();
    }, 10)
  }
}
```

See example here: http://plnkr.co/edit/UXNiM8Pz73Go27nDRD7M?p=preview

Re the first example, we deliberately haven't hooked up the template-driven entry point to reactive forms.   That's why we throw the warning.  If we did hook it up, users would immediately run into 'changed after checked' errors because the validation of reactive forms occurs synchronously.  We generally don't suggest mixing reactive and template-driven patterns for this reason.

We considered throwing an error instead, but we were concerned that if someone had a custom form component that used `disabled` as an input for something unrelated, their code would break.    Perhaps we can make the warning message a bit clearer. Let me know if you think the language could be changed.  In any case, closing this as it works as designed.

**Closed by kara** 2016-09-02 23:13 UTC
Labels: comp: forms

**Comment by Krisa** [comment] 2016-09-03 08:22
@kara - I was aware of the `disable` method, but it's not the same, at least not in my case. 

Let me take a bit more complicated example than what we can see above. I have a form composed of roughly 70 to 80 fields split across several components. Some part of the form is disabled/enabled, shown/hidden based on either some attributes of the record (on load, or on save), or depending on the user viewing this record, or even from where the record is being called (i.e. different route). I'm playing with the `disabled` and `ngIf` attribute / directive (`required` is so far always static in my case) but all are defined by, I would call that rules, at the attribute/directive level. This approach is quite consistent for me, ngIf like disabled are all in the html template.

Now, if I have to refactor this code based on what you suggest, I will probably need a central function in my class,  and call `disable()` or `enable()` for each field, based on the value of the form and from external property (user profile, route params, etc.). This function shall subscribe to `valueChanges`, and also be called when the component is loaded, or when the `save` method is called. Definitely doable, but it feels terribly awkward, at least compared to the current solution, don't you think?

Either way, I will have to live with what is implemented. I have so far downgraded the form module to 0.3.0, hoping for a PR resolving the situation above, but based on your comment, I fear this spec is not going to change, is it? Could you please (re)confirm one or the other?

Thanks
Chris

**Comment by udos86** [comment] 2016-09-04 18:35
@kara Thanks for your great work so far! Please reconsider `disabled` property binding as this is a essential feature to any [dynamic forms](https://angular.io/docs/ts/latest/cookbook/dynamic-form.html) approach. Otherwise it is not possible to directly change the enabled/disabled state of a control by simply setting an object property on the outside. It would need native ES6 Proxies to intercept the setter call of a business object model in order to call `disable()` or `enable()` on the `FormControl` as well. I myself building [ng2 Dynamic Forms](https://github.com/udos86/ng2-dynamic-forms) would really appreciate it!

**Comment by capi** [comment] 2016-09-05 14:52
If I call `this.myForm.controls["code"].disable();`, `this.myForm.valid` is always `false`:

    this.myForm.patchValue({code: 17});
    console.log(this.myForm.valid);
    this.myForm.controls["code"].disable();
    console.log(this.myForm.valid);

This outputs

    true
    false

Why is this the case? I want the control to be disabled, but the from itself to be still valid.

**Comment by Krisa** [comment] 2016-09-05 15:18
@capi Looks like a bug to my opinion, but it's also not related to the original issue I've reported, which is the ability to set the `disabled` attribute dynamically. 

Please open a new issue for that to not mix up things

**Comment by maku** [comment] 2016-09-06 13:13
@capi I have the same behaviour like you. For me this is wrong....

**Comment by capi** [comment] 2016-09-06 13:44
@maku I filed #11379 for this, we should not mix the two issues, @Krisa is entirely right about that.

**Comment by unsafecode** [comment] 2016-09-13 15:20
@udos86  @Krisa We are experiencing the same behavior, and it looks quite troublesome to solve: on one hand, we could code the dynamic enable/disable behavior by subscribing to `valueChanges `of `FormControl`, but it requires lot of code each time (and we have large forms with many fields).

On the other hand, I was thinking about a custom directive to replace `disable`, taking the `FormControl `and an `Observable`, in order to keep the reactive approach in templates, but I need to experiment with it.

**Comment by BrainCrumbz** [comment] 2016-09-15 10:23
Is there any update on this? I mean, now you have a view framework that lets you work with declarative, one-way binding code for a load of attributes and for whole content items, but then for *disabled* attribute you're stuck to imperative code?

**Comment by Krisa** [comment] 2016-09-16 12:19
@kara @pkozlowski-opensource
Positive or negative, it would be great to have a feedback, even very quick, on what's coming soon, to not let us in the dark, potentially refactoring unnecessarily our code. 

Thank you

**Comment by kemsky** [comment] 2016-09-22 15:58
@Krisa, i would recommend to avoid reactive forms. Reactive forms require a lot of coding if want interaction with other parts of template and offer very small benefits. You should be able to create configurable custom validator (or even validate your data model manually) and use it instead of `required`, also you could work with a set of forms instead of combining everything into one big form.

**Comment by unsafecode** [comment] 2016-09-22 16:04
@Krisa On our project, we quick-solved this by using two custom utility methods:

```typescript
import { FormGroup, FormControl, AbstractControl } from "@angular/forms";

export function includeInForm(form: FormGroup, controlName: string, includeChildren?: boolean) {
    const ctl = form.get(controlName);
    makeOptional(ctl, false, includeChildren);
}

export function excludeFromForm(form: FormGroup, controlName: string, excludeChildren?: boolean) {
    const ctl = form.get(controlName);
    makeOptional(ctl, true, excludeChildren);
}

function makeOptional(ctl: AbstractControl, isOptional: boolean, children?: boolean) {
    if (isOptional) {
        (<any>ctl).__validator = ctl.validator || (<any>ctl).__validator;
        ctl.clearValidators();
    } else {
        ctl.setValidators(ctl.validator || (<any>ctl).__validator);
    }

    if (children) {
        Object.keys((<FormGroup>ctl).controls).forEach((control) => {
            makeOptional(ctl.get(control), isOptional);
        });
    }

    ctl.updateValueAndValidity();
}
```

It might not be the most elegant - for sure - but it works and made the code work again with minimal changes.

**Comment by natcohen** [comment] 2016-09-25 11:49
I'm also looking for a simpler and less verbose solution to disable using form variables!

**Comment by andrevmatos** [comment] 2016-11-01 17:53
Why is this closed? There's still no clear way to declaratively disable a form control, nor workaround for it.

**Comment by natcohen** [comment] 2016-11-01 18:35
Seems that the angular team doesnt want to communicate on this...max be thés are still discussing alternatives

**Comment by andrevmatos** [comment] 2016-11-01 19:49
Ok, best workaround I could think of is to create a directive to do the dirty job, and "declaretively" test for a boolean condition and get a form/input/FormControl disabled without the need test for expressions that sometimes aren't observables where it's easy to know when something changed (i.e.: to depend on the change detection system).

You can even use it to disable other FormControl, or use another FormControl.value as a condition to disable itself.

```
@Directive({
  selector: '[disableFC][disableCond]'
})
export class DisableFCDirective {
  @Input() disableFC: FormControl;

  constructor() { }

  get disableCond(): boolean { // getter, not needed, but here only to completude
    return !!this.disableFC && this.disableFC.disabled;
  }

  @Input('disableCond') set disableCond(s: boolean) {
    if (!this.disableFC) return;
    else if (s) this.disableFC.disable();
    else this.disableFC.enable();
  }
}
```

And it can be used like:
```<input type="text" [formControl]="textFC" [disableFC]="textFC" [disableCond]="anotherElement.value < 10" />```

**Comment by raisindetre** [comment] 2016-11-10 04:25
@andrevmatos 
Hi there - have been grappling with this issue and tried to apply your suggested fix without success. Would you mind taking a look at [this Plunk](https://plnkr.co/edit/4TeykANDglSAZqjSFXeq?p=preview) and clarifying where its going wrong?

**Comment by andrevmatos** [comment] 2016-11-10 11:31
@raisindetre 
Before all, you need to set formControlName on the selects for it to use the controls inside the formGroup, or formControl to set the control directly. After that, you can use my directive to enable or disable dinamically the control. [I changed your example](https://plnkr.co/edit/8RP5r03TWWHDSzYiiAiG?p=preview) to demonstrate my directive disabling the first select based on a boolean variable (toggled by the button), and the second to disable dinamically

**Comment by raisindetre** [comment] 2016-11-11 00:55
Ah, got you - thanks! I was almost there at one point but I was wrapping the formControlName directive in square brackets. Still trying to get the hang of model/reactive driven forms.

**Comment by PTC-JoshuaMatthews** [comment] 2016-12-11 22:55
@andrevmatos 

I updated your directive to what I would consider a bit cleaner of an approach of sharing the formControl input passed from the html element that is the formConrol. 

```
@Directive({
    selector: '[formControl][disableCond]'
})
export class DisableFormControlDirective {
    @Input() formControl: FormControl;

    constructor() { }

    get disableCond(): boolean { // getter, not needed, but here only to completude
        return !!this.formControl && this.formControl.disabled;
    }

    @Input('disableCond') set disableCond(s: boolean) {
        if (!this.formControl) return;
        else if (s) this.formControl.disable();
        else this.formControl.enable();
    }
}
```


This allows us to remove the duplication from the template

`<input type="text" [formControl]="textFC" [disableCond]="anotherElement.value < 10" />`

**Comment by PTC-JoshuaMatthews** [comment] 2016-12-11 22:57
Although I would really appreciate it if the Angular team could update the reactive forms component to track the formControl disabled property correctly.

**Comment by BrainCrumbz** [comment] 2016-12-12 09:09
@andrevmatos @PTC-JoshuaMatthews we've found also the version at [this GH issue comment](https://github.com/angular/angular/issues/11379#issuecomment-246756547) by @unsafecode to be quite interesting.

**Comment by pmulac** [comment] 2016-12-15 19:29
I have been having the same issue - there isn't a clean way to disable portions of a reactive/model-driven form.  The use case is pretty common: Consider a group radio buttons that each display a child form when selected, and each subform that is not selected needs to be disabled in order to make the entire form valid.

I really like @PTC-JoshuaMatthews 's `DisableFormControlDirective`, but then I realized that it defeats the purpose of using reactive forms...  In other words, the disabling becomes template-driven (to test it, you need to parse the template).  As far as I can tell, the best way to stay model-driven/reactive is to subscribe to `valueChanges` on a control and then call `disable` on the corresponding subform (which is very verbose/ugly).  I'm really surprised there isn't a better way to achieve this.

**Comment by BrainCrumbz** [comment] 2016-12-16 08:48
@pmulac while @PTC-JoshuaMatthews directive can be definitely useful, I'd just like to point out that in our project in the end for many **single controls** (e.g. input, checkbox) that had to be disabled, we switched to binding on `[readonly]` in order to actually *disable* that input. If validation was somehow involved, e.g. a readonly field had to be ignored under some condition, we made custom validation that took condition into account. 
On the other hand, if it was a matter of disabling **whole forms** it looks to me that binding on `[disabled]` still works good, with no warning. 
Just our 2¢

**Comment by PTC-JoshuaMatthews** [comment] 2016-12-17 01:17
@BrainCrumbz

One issue with doing it with [readonly] or [disabled] is that the actual form control object will not be in a disabled state, and that will affect the functionality of the form. For instance and validations you have attached to the form control will still run, so if you have a required field that is disabled the form will be considered invalid. Using the directive I posted will properly disable the form control and skip validation on disabled fields.

**Comment by PTC-JoshuaMatthews** [comment] 2016-12-17 01:21
@BrainCrumbz

One issue with doing it with [readonly] or [disabled] is that the actual form control object will not be in a disabled state, and that will affect the functionality of the form. For instance any validations you have attached to the form control will still run, so if you have a required field that is disabled the form will be considered invalid. Using the directive I posted will properly disable the form control and skip validation on disabled fields.

**Comment by rmcsharry** [comment] 2016-12-19 17:59
I just saw this warning in the console, so I am trying to solve this the RxJS way as per the comment from @pmulac - subscribe to ValueChanges.

In my case I need to enable a control that is disabled on init.

SO [question here ](http://stackoverflow.com/questions/41228320/simple-angular2-reactive-form-control-enable-state-change)if anyone can shed some light on how to solve this, thanks.

**Comment by noamichael** [comment] 2016-12-22 13:51
@rmcsharry See #13570 for an alternate solution

**Comment by rmcsharry** [comment] 2016-12-22 21:20
@noamichael Thanks for the ref.

**Comment by cScarlson** [comment] 2017-01-27 22:08
@kemsky (kemsky commented on Sep 22, 2016),

This *actually* seems like the best approach, IMO. I first realized Microsoft had a hand in the Angular 2 project when I saw how much **Boilerplate** gets implemented into projects when they use ReactiveForms. For some things, I'm thrilled about Microsoft's influence on Angular2, but this is one area where I'll be rejecting the MS-Boilerplating -- assuming its their hand in it.

There's a *correct way* to do things, and there's a *right way*. If you're throttling the Engineer's productivity so much without much benefit -- not to mention adding more Coupling in the system -- then that's *not* the "right way". Why don't we just make it so your application blows up if an `input` is not wrapped in a `form`?

Why ReactiveForms???
What benefits do you really get? Seems like validation (etc) is better done using a Visitor Pattern, Decorator, Mediator, Service or something else anyway.

That said -- before I throw the ugly baby out with the bathwater -- could you gives us some insight to any caveats you've encountered on the 'no-reactive-forms-boilerplate' bandwagon?

Much Appreciated!

**Comment by xLama** [comment] 2017-01-27 22:29
You can solve it with a Directive. A directive named Canbedisabled and a poperty "blocked", for example.  Write a setter for blocked and set it to nativelement.disabled property.

**Comment by medeirosrich** [comment] 2017-02-06 15:23
I've been handling this scenario by tying into the ngDoCheck Lifecycle hook. 

>     ngDoCheck() {
>         if (this.childControl.disabled != this.isDisabled) {
>             this.isDisabled ? this.childControl.disable() : this.childControl.enable();
>         }
>     }

**Comment by kiwileaks78** [comment] 2017-03-22 14:48
Don't know why, but when I call .enable() or .disable() twice in a row, it works !

>       form.controls['partPerson'].enable();
>       form.controls['partPerson'].enable();

**Comment by wagner18** [comment] 2017-03-22 17:39
That kind of restrictive approach take down the advantage of using Angular Reactive forms since disable and enable an element is a pretty much a basic feature, specially if you are building a dynamic form.

So if you need to build a complex dynamic form, and need total control on that form, better use the template-driven approach, even though it can means more work, such as validation, down the road this approach will be bather then end up with a complex code full of workarounds to solve basic things like enable and disable a form element.

Btw, there is nothing that says you can not use both approaches, reactive and template-driven, in the same application, just be aware of the advantages and limitations of each one.


[https://angular.io/docs/ts/latest/guide/reactive-forms.html](url)

**Comment by Highspeed7** [comment] 2017-03-23 22:17
Erm... maybe I'm a bit off here, but I was able to get the disabled feature working with [attr.disabled]="isDisabled"

**Comment by kekeh** [comment] 2017-03-28 15:23
This worked:
```html
<input [attr.disabled]="disabled?'':null"/>
```
```javascript
private disabled: boolean = false;

// disable component
disableInput(): void {
   this.disabled = true;
}
```

**Comment by timaxapa** [comment] 2017-04-06 12:46
@kekeh Thanks, It works as expected

**Comment by joshua-schwartz** [comment] 2017-04-13 22:05
@Highspeed7 that's because you're using the attribute binding rather than the property binding. I'm sure there's some reason this is ineffective at some level, but it works for my needs, thanks for pointing it out!

**Comment by garysui** [comment] 2017-04-16 15:00
@kekeh It works

**Comment by steodor** [comment] 2017-04-21 07:22
@kekeh thanks! it works like a charm :)

**Comment by pantonis** [comment] 2017-07-19 14:37
does not work for me

**Comment by ar53n** [comment] 2017-08-02 13:34
You can use form.getRawValue()

**Comment by alex-che** [comment] 2017-12-13 11:04
The problem could be solved the 'reactive' way, if the FormControl constructor accepted a function for the disabled property of the first parameter. Currently it only accepts a boolean value.
E.g.
```
  form = new FormGroup({
    'first': new FormControl(),
    'second': new FormControl({value: '', disabled: formValue => formValue.first === 'something'})
  })

```

**Comment by cmelone** [comment] 2017-12-27 00:35
&nbsp;

**Comment by raysuelzer** [comment] 2018-01-09 03:11
Disabled, should definitely be allow to accept a function.  Disabled state will often change and it is a mess to have helper methods and watchers just to check a condition.

**Comment by kenji-1996** [comment] 2018-02-04 06:03
Really appreciate the current 'hack-y' solutions provided while we wait for this to get changed

**Comment by dlarr** [comment] 2018-02-12 09:58
@medeirosrich  : you are good buddy !

Best solution is your !

Works like a charm:
```
ngDoCheck() {
    if (this.childControl.disabled != this.isDisabled) {
        this.isDisabled ? this.childControl.disable() : this.childControl.enable();
    }
}
```

**Comment by billfranklin** [comment] 2018-02-13 13:40
Agree with the many others...disabled NEEDS to be dynamically controlled, otherwise it's fairly useless

**Comment by billfranklin** [comment] 2018-02-13 13:41
@kara why is this closed?

**Comment by centigrade-thomas-becker** [comment] 2018-03-08 09:24
@billfranklin The correct way is to bind to attr.disabled. Check the solution that kekeh posted.

**Comment by hk-skit** [comment] 2018-03-09 12:49
@kekeh 's solution is great but it does not work with custom form controls. I am trying to conditionally disable form fields in [angular2-json-form-schema](https://github.com/dschnelldavis/angular2-json-schema-form). I am planning to do it by using a directive the way @PTC-JoshuaMatthews has suggested. Is there any better way to achieve the same? I know I can implement ngDoCheck in custom controls  but it won't be an efficient solution.

**Comment by vehansayvazi** [comment] 2018-03-15 20:53
any news on this?

**Comment by centigrade-thomas-becker** [comment] 2018-03-21 07:32
@mkotsollaris Did you read the reply with the most thumbs up?

**Comment by PTC-JoshuaMatthews** [comment] 2018-03-21 22:56
I ended up abandoning this approach altogether in my applications. Instead of setting isDisabled property on my component and expecting the from to track it’s changes, I instead call this.form.controls[“mycontrol”].disable() in the ngAfterViewInit hook. If the status changes I explicitly call enable.

 This approach works fine as I’m already responding to some event to enable/disable the control so no problem doing it directly through the form api as opposed to attempting to bind the disabled status to a property. I suspect my desire to bind it comes from my angular 1 days.

**Comment by vishalbiradar** [comment] 2018-03-29 10:54
Is it good/correct way of using below code for disabling the forms ???
```html
<input [attr.disabled]="disabled?'':null"/>
```

**Comment by AndrewPa** [comment] 2018-07-03 19:33
@Highspeed7 That works "partially" in that the element's `disabled` attribute value is bound to the expected value, but for some arcane HTML standard reason, the `disabled` attribute need only exist for it to disable the element, even if `disabled="false"`. 

@kekeh Added to this solution by binding the ternary `isDisabled ? '' : null` instead of just `isDisabled`. This is basically a hack to get Angular to clear the attribute entirely when the form is re-enabled.

So on the template, this would be the workaround:
`[attr.disabled]="isDisabled ? '' : null"`

**Comment by sgronblo** [comment] 2018-08-20 10:05
What are the implications of setting `[attr.disabled]` vs `[disabled]`?

**Comment by dudewad** [comment] 2018-08-28 22:57
@sgronblo afaik there aren't any. I was under the impression that `[disabled]` is just shorthand for `[attr.disabled]` but I could be wrong.

**Comment by tinyweasel** [comment] 2018-09-27 15:33
> This worked:
> 
> ```
> <input [attr.disabled]="disabled?'':null"/>
> ```
> 
> ```js
> private disabled: boolean = false;
> 
> // disable input box
> disableInput(): void {
>    this.disabled = true;
> }
> 
> // enable input box
> enableInput(): void {
>    this.disabled = false;
> }
> ```

It worked for me even by just having  this.disabled = false; etc, wherever I needed it. The functions weren't necessary.

**Comment by Sangarlal** [comment] 2019-02-13 04:52
this.myForm.controls['id'].disable();

**Comment by danzrou** [comment] 2019-02-20 15:05
Is there a more proper solution for this case instead of binding to the disabled attribute (which is kept after the form is re-enabled) ?

**Comment by PTC-JoshuaMatthews** [comment] 2019-02-20 15:56
@danzrou  Does the answer directly above you not work for you? Just disable the form control that the input is tied to and the input will be dealt with automatically.

**Comment by dudewad** [comment] 2019-02-20 16:18
@danzrou yes, fwiw, afaik that is _the_ defacto way to enable/disable form controls:
`someFormGroup.controls['controlName'].disable()`
and
`someFormGroup.controls['controlName'].enable()`

Keep in mind that reactive forms are not the standard form set. They are _intended_ to be used programmatically, not through the dom, which is why (I suspect) they don't allow the bindings anymore.

**Comment by danzrou** [comment] 2019-02-20 17:12
My current situation is that I am passing a form control to a child component and the control is changing dynamically according to user selection. If I pass a control which has disabled=true, the input element is indeed disabled. Then I pass a a new control which has disabled=false (and I made sure it is not disabled) and yet the disabled attribute remains on the input field. This still happens in Angular 7.2.3

**Comment by PTC-JoshuaMatthews** [comment] 2019-02-20 17:43
@danzrou can you elaborate on how are you passing the form control into the child component? My guess is that the child component isn’t seeing the new form control.

**Comment by danzrou** [comment] 2019-02-21 10:12
@PTC-JoshuaMatthews it passes it using standard input. Some more details:
* Each time user clicks on some element, new form controls are generated for this request therefore the reference for them is not kept
* This means a new control instance is being pass each time (not the same one with property changes)

**Comment by Sangarlal** [comment] 2019-02-21 10:45
> Is there a more proper solution for this case instead of binding to the disabled attribute (which is kept after the form is re-enabled) ?

this.myForm.controls['id'].enable();

**Comment by PTC-JoshuaMatthews** [comment] 2019-02-21 13:21
@danzrou I could see why that wouldn’t work, you’re swapping out the form control but not changing disabled state while it is bound to the input. Form controls aren’t really meant to be swapped out like that, there’s no event taking place for it to react to. 

If you’re sure that you have to swap form controls, I would recommend using an input setter to detect when the form control changes and re-initializing the input when this happens.

As for how to reinitialize it a dirty solution would be by hiding it with an ngIf and then showing it in a timeout directly after. A cleaner solution might just be to call formControl.setDisabled(formControl.disabled). Just as long as you’re doing this while the form control is bound to the input. Might have to get creative with a timeout

**Comment by sgentile** [comment] 2019-08-30 21:28
please provide a flag in angular config to disable this warning

**Comment by dudewad** [comment] 2019-09-01 00:03
@sgentile I think the entire point of the warning is that you're using reactive forms, and therefore should not be using template-driven-form syntax to control form state. This could cause a lot of confusion when a developer sees reactive forms, tries to program in reactive forms, and unknowingly ends up fighting a template-driven form convention because it was implemented in conflict.

**Comment by sgentile** [comment] 2019-09-01 00:11
Quite a few assumptions here.

For example, I'm using Primeng and I need to pass disabled to their control
and this causes the console warning.

I think it's fine to show console warnings to developers, however they
should be able to decide if they want them.  Make a setting in the
angular.json file

It's over extending imo.

**Comment by sgentile** [comment] 2019-09-01 00:12
Furthermore when I did attempt to use disable it didn't work

**Comment by dudewad** [comment] 2019-09-01 00:16
@sgentile Yeah sorry - wasn't attempting to assume but without more info you sound like most developers who complain about a feature w/o a justification. Framework and language devs have to make the most generic choices possible and a lot of times that gets overlooked. I think your case is a valid point.

**Comment by sgentile** [comment] 2019-09-01 00:19
You have motivated me to see if I can get a ViewChild reference to the
control and see if I can set it programatically
