### ISSUE TITLE
Error trhow by router on related lazy load modules in routing array.

### ISSUE THREAD

**Issue by RafaelAngelRamirez** [angular/angular#38833] opened 2020-09-13 01:56 UTC
# 🐞 bug report

### Affected Package

The issue is caused by package @angular/router

### Is this a regression?

No. I found closed issues backward in time early 2017 to 2019 with out repro like this #17743

### Description

 A clear and concise description of the problem...

When a route containing the `outlet` parameter is called and in the same array a lazy loading is done with the ` path: ""` parameter, the error is triggered.

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/router-outlet-named?file=src/app/app.module.ts

## 🔥 Exception or Error
<pre><code>
ERROR
Error: Uncaught (in promise): TypeError: Cannot read property 'routes' of undefined
TypeError: Cannot read property 'routes' of undefined
at getChildConfig (https://router-outlet-named.stackblitz.io/turbo_modules/@angular/router@10.0.9/__ivy_ngcc__/bundles/router.umd.js:3550:40)
at Recognizer.processSegmentAgainstRoute (https://router-outlet-named.stackblitz.io/turbo_modules/@angular/router@10.0.9/__ivy_ngcc__/bundles/router.umd.js:3522:31)
at Recognizer.processSegment (https://router-outlet-named.stackblitz.io/turbo_modules/@angular/router@10.0.9/__ivy_ngcc__/bundles/router.umd.js:3481:37)
at Recognizer.processSegmentGroup (https://router-outlet-named.stackblitz.io/turbo_modules/@angular/router@10.0.9/__ivy_ngcc__/bundles/router.umd.js:3466:25)
at eval (https://router-outlet-named.stackblitz.io/turbo_modules/@angular/router@10.0.9/__ivy_ngcc__/bundles/router.umd.js:3470:108)
at eval (https://router-outlet-named.stackblitz.io/turbo_modules/@angular/router@10.0.9/__ivy_ngcc__/bundles/router.umd.js:1186:34)
at forEach (https://router-outlet-named.stackblitz.io/turbo_modules/@angular/router@10.0.9/__ivy_ngcc__/bundles/router.umd.js:912:17)
at mapChildrenIntoArray (https://router-outlet-named.stackblitz.io/turbo_modules/@angular/router@10.0.9/__ivy_ngcc__/bundles/router.umd.js:1184:9)
at Recognizer.processChildren (https://router-outlet-named.stackblitz.io/turbo_modules/@angular/router@10.0.9/__ivy_ngcc__/bundles/router.umd.js:3470:28)
at Recognizer.processSegmentGroup (https://router-outlet-named.stackblitz.io/turbo_modules/@angular/router@10.0.9/__ivy_ngcc__/bundles/router.umd.js:3464:29)

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
$ ng version

     _                      _                 ____ _     ___ 
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | | 
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | | 
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 10.1.0
Node: 14.4.0       
OS: win32 x64      

Angular: 10.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router, service-worker
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.8
@angular-devkit/build-angular     0.1000.8
@angular-devkit/build-optimizer   0.1000.8
@angular-devkit/build-webpack     0.1000.8
@angular-devkit/core              10.0.8
@angular-devkit/schematics        10.1.0
@angular/cdk                      10.2.0
@ngtools/webpack                  10.0.8
@schematics/angular               10.1.0
@schematics/update                0.1001.0
rxjs                              6.6.2
typescript                        3.9.6
webpack                           4.43.0

</code></pre>

**Anything else relevant?**
For the error to occur, it is necessary to navigate to the following url:

https://router-outlet-named.stackblitz.io/(print:print/invoice)

**Comment by atscott** [comment] 2020-09-17 21:11
This is a duplicate of #10981. The fix is available in the `11.0.0` release.

**Closed by atscott** 2020-09-17 21:11 UTC
Labels: comp: router, router: directives, router: lazy loading
