### ISSUE TITLE
DOM nodes duplicated / not removed ONLY in production configuration

### ISSUE THREAD

**Issue by nkosi23** [angular/angular#53797] opened 2024-01-04 19:28 UTC
### Which @angular/* package(s) are the source of the bug?

core, forms

### Is this a regression?

Yes

### Description

I am facing a disturbing and unexpected issue just as I need to push code in production asap.  My application works perfectly fine using the development configuration, however in the production configuration I see many issues boiling down to the fact that after change detection some DOM nodes are not removed from the DOM while they should. 

I see things like the below at random places of my application:

![image](https://github.com/angular/angular/assets/6731436/a4692eba-c6f8-48c3-b7e3-229f01d61a67)

```html
if (selectedPeriodDurationInMonths > 1) {
        <span i18n>months</span>
    } @else {
        <span i18n>month</span>
    }
```

(yeah I know there is a dedicated syntax for pluralization but this is just one of many examples)

![image](https://github.com/angular/angular/assets/6731436/4d0de922-a801-4703-89ef-6b9fc0cc9bd6)

```html
  @if (!isUKCompany) {
      <div>
          <label class="ms-1">
              <p-radioButton
                      [formControl]="orderForm.controls.currency"
                      value="EUR"
                      name="currencySelection"
              ></p-radioButton>
              <span i18n>Euros</span></label>
      </div>
      <div>
          <label class="ms-1">
              <p-radioButton
                      [formControl]="orderForm.controls.currency"
                      value="USD"
                      name="currencySelection"
              ></p-radioButton>
              <span i18n>American Dollars</span></label>
      </div>
  }
  @if (isUKCompany) {
      <div>
          <label class="ms-1">
              <p-radioButton
                      inputId="ukCurrency"
                      [formControl]="orderForm.controls.currency"
                      value="GBP"
                      name="currencySelection"
              ></p-radioButton>
              <span i18n>British Pound</span></label>
      </div>
}
```

Basically controls are not being removed from the DOM while they should. Does anyone have any idea on what could be the cause? I initially suspected the *ngIf syntax, but I had one page using the new control flow syntax on its forms, and the other one using the old directives and both were having this problem.

The fact that the there can be such radically different behaviors between development and build configurations is something I really dislike with Angular. I've already been beaten by these differences in the past and this is not something one would except. In other stacks, the only thing that happens when a default production configuration is switch ON is performance improvements.

### Please provide the exception or error you saw

There is no error in the development console

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.0.9
Node: 20.8.1
Package Manager: npm 10.1.0
OS: linux x64

Angular: 17.0.8
... animations, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic
... platform-server, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.9
@angular-devkit/build-angular   17.0.9
@angular-devkit/core            17.0.9
@angular-devkit/schematics      17.0.9
@angular/cli                    17.0.9
@schematics/angular             17.0.9
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.2
```

### Anything else?

Angular.json:

```json
"production": {
    "optimization": {
    "scripts": true,
    "styles": {
        "minify": true,
        "inlineCritical": false
    },
    "fonts": true
    },
    "outputHashing": "all",
    "localize": ["en"]
},
"development": {
    "buildOptimizer": true,
    "optimization": true,
    "vendorChunk": true,
    "extractLicenses": false,
    "sourceMap": true,
    "namedChunks": true,
    "localize": ["en"]
}
```
_No response_

**Comment by crisbeto** [comment] 2024-01-04 21:00
It's hard to narrow it down further without a reproduction, but one thing worth trying is if the issue goes away if you remove the `i18n` attributes since i18n can affect the DOM structure.

**Comment by everflux** [comment] 2024-01-12 21:38
@pkozlowski-opensource From reading the issue I think it was in fact the `BrowserAnimationsModule` not the `BrowserModule` - perhaps a check only for the later is in place?

**Comment by JeanMeche** [comment] 2024-02-13 13:48
Without a repro, we're going to close this.
If ever you're able to provide a repro, feel free to open a new issue, thank you.

**Closed by JeanMeche** 2024-02-13 13:48 UTC
Labels: needs reproduction, area: core, core: bootstrap
