### ISSUE TITLE
APP_INITIALIZER ->Cannot instantiate cyclic dependency!

### ISSUE THREAD

**Issue by meriturva** [angular/angular#35225] opened 2020-02-07 11:01 UTC
# 🐞 bug report

### Description
It is just present on new Angular 9.
Unable to use APP_INITIALIZER with Router anymore. Angular 8 works like a charm!

Here app.module code:
<pre><code>
@NgModule({
  imports:      [ BrowserModule, FormsModule, AppRoutingModule],
  declarations: [ AppComponent, HelloComponent ],
  providers: [
    {provide: APP_BASE_HREF, useValue : '/' },
    {
      provide: APP_INITIALIZER,
      useFactory: () => () => { },
      multi: true,
      deps: [TitleService]
    }
  ],
  bootstrap:    [ AppComponent ]
})
export class AppModule { }
</code></pre>

## 🔬 Minimal Reproduction
Just clone repository: https://github.com/meriturva/angular-9-cyclic-dependency-error and run ng serve

## 🔥 Exception or Error
<pre><code>
Error: Cannot instantiate cyclic dependency! ApplicationRef
    at throwCyclicDependencyError (core.js:5469)
    at R3Injector.push../node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js.R3Injector.hydrate (core.js:11343)
    at R3Injector.push../node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js.R3Injector.get (core.js:11170)
    at injectInjectorOnly (core.js:787)
    at ɵɵinject (core.js:792)
    at injectArgs (core.js:887)
    at Object.factory (core.js:11436)
    at R3Injector.push../node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js.R3Injector.hydrate (core.js:11347)
    at R3Injector.push../node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js.R3Injector.get (core.js:11170)
    at injectInjectorOnly (core.js:787)

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___ 
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | | 
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.0.1
Node: 12.15.0
OS: win32 x64

Angular: 9.0.0
... common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.1
@angular-devkit/build-angular     0.900.1
@angular-devkit/build-optimizer   0.900.1
@angular-devkit/build-webpack     0.900.1
@angular-devkit/core              9.0.1
@angular-devkit/schematics        9.0.1
@angular/cli                      9.0.1
@ngtools/webpack                  9.0.1
@schematics/angular               9.0.1
@schematics/update                0.900.1
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2

</code></pre>

**Comment by julmot** [comment] 2020-02-07 12:15
I'm also experiencing an issue with a cyclic dependency in Angular v9 that didn't pop up in Angular v8. The background is that I have two services:

* Service A: Loads service B
* Service B: Loads only interfaces from the file of service A

So there's no cyclic dependency on a service layer, since service B isn't loading service A, it's just loading interfaces from the same file in which service A is located.

Of course refactoring this to a central interface file would solve the issue, but I don't see **why this is an issue in Angular v9 if it wasn't an issue in v8**?

The issue is logged to the console as warning when building the application.

**Comment by leonelvsc** [comment] 2020-02-07 13:28
Same here

**Comment by mariojsnunes** [comment] 2020-02-08 14:30
Got this as well, fixed by importing with deeper path.
In my case I went from having:
`import { ComponentX } from '@app/shared' `
to
`import { ComponentX } from '@app/shared/components'`

**Comment by AndrewKushnir** [comment] 2020-02-24 21:57
Hi @meriturva,

Thanks for reporting the problem and providing a repro.

We performed the investigation and found out that Ivy throws an exception correctly (while View Engine was not doing that as expected, likely due to a bug), since there is a dependency cycle in the code as shown below:

```
AppModule (root module) -> ApplicationRef -> ApplicationInitStatus ->
APP_INITIALIZER -> TitleService -> Router -> ApplicationRef (that creates a cycle)
```

It turned out that the `ApplicationRef` dependency in `Router` is not required, so it was removed in #35642. I tested your repro case with the changes from #35642 and it seems to be working correctly now. The changes from #35642 should be available in 9.0.3 release of the framework in a few days.

Thank you.

**Comment by AndrewKushnir** [comment] 2020-02-24 22:36
Hi @julmot,

As I described in my previous comment https://github.com/angular/angular/issues/35225#issuecomment-590569490, the problem was related to a specific scenario where `Router` was used as a dependency for an init function provided within the `APP_INITIALIZER` multi-provider.

I believe the use-case that you have is a different one and it'd be great if you could create a repro (in a form of GitHub repository) that we can look at.

Thank you.

**Comment by kara** [comment] 2020-02-26 17:14
Closed by https://github.com/angular/angular/pull/35642

**Closed by kara** 2020-02-26 17:14 UTC
Labels: comp: core, comp: ivy, freq2: medium, severity5: regression, state: has PR, type: bug/fix
