### ISSUE TITLE
Feature Request: Default Encapsulation with AOT compiler

### ISSUE THREAD

**Issue by Cammisuli** [angular/angular#12251] opened 2016-10-12 19:42 UTC
**I'm submitting a ...**  (check one with "x")

```
[x] feature request
```

**Current behavior**
Current implementation of AOT does not allow us to set defaultEncapsulation as compilerOptions.

**Expected behavior**
We should be able to pass a flag, or have some type of option available in the tsconfig.json to specify the defaultEncapsulation.

**What is the motivation / use case for changing the behavior?**
When using JIT we have the option to pass compilerOptions to the bootstrapModule function like so:
`platformBrowserDynamic().bootstrapModule(NGAppModule, {defaultEncapsulation: ViewEncapsulation.None});`

When we compile the templates and use the factory with `platformBrowser().bootstrapModuleFactory()`, there is no option to specify the compilerOptions. Obviously this is the case, cause these factories are precompiled.

So because of that, having defaultEncapsulation as a tsconfig.json or a compiler option would be fantastic.

**Please tell us about your environment:**
Windows 10
- **Angular version:** 2.0.X
- **Browser:** [all]
- **Language:** [all]
- **Node (for AoT issues):** `node --version` =  v5.10.1

**Comment by tbosch** [comment] 2016-10-26 18:09
We are thinking about adding a flag to `@NgModule` to do this. With that, the configuration for JIT and AoT would be the same. Would that fit your use case?

**Comment by Cammisuli** [comment] 2016-10-26 18:13
Yes, that's a reasonable addition for me. As long as both JIT and AoT use the same configuration, it's good!

**Comment by psamsotha** [comment] 2016-11-25 03:56
Is there any work around right now for this problem? Or is there any timeline on when/if [this](https://github.com/angular/angular/issues/12251#issuecomment-256431091) is going to be rolled out?

**Comment by DzmitryShylovich** [comment] 2017-02-03 00:13
@Cammisuli I think this can be closed in favor of https://github.com/angular/angular/issues/13819

**Comment by artuska** [comment] 2017-10-30 08:18
Have the same problem — have to build with `--aot=false` option for the production build.

**Comment by Hobart2967** [comment] 2019-04-29 07:02
+1

**Comment by greggbjensen** [comment] 2019-07-15 20:33
Is this issue going to be addressed?  It seems like we want to be able to use both ViewEncapsulation.None and AOT.

**Comment by jlSites** [comment] 2019-07-18 01:46
this issue is still there.

But we put all "ViewEncapsulation.None" into all our components, which works for JIT and AOT.

**Comment by GaryLoop** [comment] 2019-09-27 18:21
+1.

**Comment by popec** [comment] 2020-08-20 17:54
+1

**Comment by Chofoteddy** [comment] 2020-11-03 23:33
This issue is still in 10.2.1.

**Comment by SamanthaAdrichem** [comment] 2020-11-17 14:11
Is there any eta on this?

The issue is open since 2016.

I've just migrated from our own custom webpack build to using ng-build and now have to change 311 components their view encapsulation... and once this is fixed, i'll have to change it back. :(

**Comment by alxhub** [comment] 2021-07-01 23:39
I'm going to close this issue, as I don't believe this feature is a good fit for Angular.

In general, we want to move towards a model where components are more self-contained. A great example of this is the project on our roadmap for "optional NgModules" - components that declare their own dependencies and aren't declared in an NgModule. Having a global setting for the compiler, or even a setting in an `NgModule`, would be a step in the wrong direction with respect to that goal.

It is a little annoying to have to specify a `ViewEncapsulation` for each component, but I believe the value of being explicit in declarations like these outweighs the relative burden.

**Closed by alxhub** 2021-07-01 23:39 UTC
Labels: comp: compiler, comp: core, core: CSS encapsulation, core: NgModule, feature, freq2: medium, under consideration
