### ISSUE TITLE
DomEventPlugin forces event handlers to run in Angular Zone

### ISSUE THREAD

**Issue by heathkit** [angular/angular#18753] opened 2017-08-17 18:15 UTC
## I'm submitting a...

<pre><code>
[X] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
In #18107 the DomEventsPlugin was changed to bypass Zone.js when adding event listeners. This improves performance when scheduling these events, but it forces their handler to run in the Angular Zone, regardless of which Zone the addEventListener call originated from.

## Expected behavior
In ngUpgrade, a `$rootScope.$digest` is called every time the NgZone is invoked. For certain events that fire frequently (scroll, mouseover, mouseout, etc), these handlers would trigger potentially expensive $digest calls frequently.

We worked around this by running Angular in a custom zone. Our custom zone would intercept when these event handlers were scheduled and instead schedule them in the root zone, thus running their handler outside of NgZone and avoiding the expensive $digest call.

This workaround is no longer an option. By default, the EventManagerPlugin will schedule events without Zone.js and we have no way to alter this behavior. This isn't an issue for us as ngUpgradeLite has solved our performance problems, but other teams using ngUpgrade might have had a similar solution.

## Example of old workaround
```ts
const customZone = Zone.current.fork({
  name: 'event blacklist',
  onScheduleTask:
      (delegate: ZoneDelegate, current: Zone, target: Zone, task: Task):
          Task => {
            // Blacklist scroll, mouse, and request animation frame events.
            if ((task.type === 'eventTask' || task.type === 'macroTask') &&
                isBlacklistedEvent(task.source)) {
              task.cancelScheduleRequest();

              // Schedule task in root zone.
              return Zone.root.scheduleTask(task);
            } else {
              return delegate.scheduleTask(target, task);
            }
          }
});
```

then, during bootstrap...
```ts
customZone.run(() => {
    platformBrowser().bootstrapModuleFactory(AppModuleNgFactory).then((ref) => {
      const adapter = ref.injector.get(UpgradeModule) as UpgradeModule;
      const zone = ref.injector.get(NgZone);
      zone.run(() => {
        adapter.bootstrap(el, modules);
     });
  });
});
```

## New workaround

We still want to control how handlers for these events are run. However, it seems that since EventManagerPlugin is not intended to be a public API, our only option is to make a custom RendererFactory.

I don't know if this is a change in behavior that needs to be fixed, or just something that needs to be documented.

**Comment by heathkit** [comment] 2017-08-17 19:57
The issue might be more serious than I thought. For example, in [angular material](https://github.com/angular/material2/blob/master/src/cdk/overlay/scroll/scrollable.ts)

```ts

  ngOnInit() {
    this._scrollListener = this._ngZone.runOutsideAngular(() => {
      return this._renderer.listen(this.getElementRef().nativeElement, 'scroll', (event: Event) => {
        this._elementScrolled.next(event);
      });
    });

    this._scroll.register(this);
  }
```

The [DomEventPlugin](https://github.com/angular/angular/blob/master/packages/platform-browser/src/dom/events/dom_events.ts#L50) will force this handler to run in NgZone, despite the listen() call being in runOutsideAngular. This is the problematic section

```ts
    if (byPassZoneJS) {
      callback = function() {
        return self.ngZone.runTask(handler as any, null, arguments as any, eventName);
      };
    }
```

**Comment by JiaLiPassion** [comment] 2017-08-22 13:16
@heathkit , could you provide a reproduce repo to describe the issue? I would like to help to check how `zone.js` can handle this issue.

**Comment by mhevery** [comment] 2017-08-30 18:26
@JiaLiPassion I discussed this offline with @heathkit. The issue is that angular bypasses Zone.js in order to gain performance. The bypass does have this property. Still thinking what to do with this.

**Comment by JiaLiPassion** [comment] 2017-08-31 06:56
@mhevery , got it, I have an idea, implement a simple version of zone aware addEventListener, just the same idea that we use to improve `zone.js` addEventListener performance .

https://github.com/JiaLiPassion/angular/commit/163c6efea84e900fc6eeb8513f1d1922cba1f750

1. all event listener use a `global` listener. so we don't need to create a `closure` to wrap the callback everytime.
2. still use `native addEventListener` so no `ZoneEventTask` will be scheduled
3. keep zone information into `target`.

Please review the idea is ok or not.

**Comment by JiaLiPassion** [comment] 2017-08-31 07:20
@mhevery , I updated a little, 

when `addEventListener`, if the `Zone.current` is `ngZone`, we do not need to use the zone patched globalListener. just use `native addEventListener`.

**Comment by mhevery** [comment] 2017-08-31 17:19
@JiaLiPassion I think you are on the right track. Let's give it a try. Just to make sure we are on the same page, this would be a PR against angular repo. (not a change to zone.js) Are you up for making a PR?

**Comment by JiaLiPassion** [comment] 2017-08-31 23:39
@mhevery , got it, I will make a PR on `angular` repo.

**Comment by JiaLiPassion** [comment] 2017-09-01 16:58
@heathkit , @mhevery , with the PR #18993, 

the following code you provide should work. the handler will run in `root` zone and will not 
trigger `$digest` call.

```javascript
  ngOnInit() {
    this._scrollListener = this._ngZone.runOutsideAngular(() => {
      return this._renderer.listen(this.getElementRef().nativeElement, 'scroll', (event: Event) => {
        this._elementScrolled.next(event);
      });
    });

    this._scroll.register(this);
  }
```

but for the first walk around, 

```javascript
const customZone = Zone.current.fork({
  name: 'event blacklist',
  onScheduleTask:
      (delegate: ZoneDelegate, current: Zone, target: Zone, task: Task):
          Task => {
            // Blacklist scroll, mouse, and request animation frame events.
            if ((task.type === 'eventTask' || task.type === 'macroTask') &&
                isBlacklistedEvent(task.source)) {
              task.cancelScheduleRequest();

              // Schedule task in root zone.
              return Zone.root.scheduleTask(task);
            } else {
              return delegate.scheduleTask(target, task);
            }
          }
});
```

this will not work, because `onScheduleTask` will not be triggered, so the `blackList` events have to be added in this way.

```javascript
this._ngZone.runOutsideAngular(() => {
  elem.addEventListener('scroll', function(event) {...}); 
});
```

### so should we just check in `DomEventsPlugin.addEventListener` , if the eventName is `blacklisted`, we just use `nativeListener`? This will resolve `elem.addEventListener('scroll`,...)`
issue.

And for the the usage `elem.on('scroll', ...);` we can use 
https://github.com/angular/zone.js/pull/877
```
 __Zone_ignore_on_properties = [
   {
        target: HTMLElement.prototype,
        ignoreProperties: ['scroll']
      }
    ];
```

**Comment by Ploppy3** [comment] 2017-09-12 12:28
I see you closed the PR, will this ever be fixed?

**Comment by JiaLiPassion** [comment] 2017-09-12 13:18
@Ploppy3 , the PR have been merged, so it should be fixed.

**Comment by Ploppy3** [comment] 2017-09-12 15:10
Sorry I'm kinda new to Github, can you please tell me where I could have got this information? Thank you very much.

**Comment by Ploppy3** [comment] 2017-09-12 15:11
Sorry I'm kinda new to Github, can you please tell me where I could have got this information? Thank you very much.

**Comment by JiaLiPassion** [comment] 2017-09-12 15:57
@Ploppy3 , you want to know the PR merge information?  you can find it here https://github.com/angular/angular/pull/18993, and you can also get the information from commit history, https://github.com/angular/angular/commits/master

**Comment by mhevery** [comment] 2017-09-12 18:28
Closing since https://github.com/angular/angular/pull/18993

**Closed by mhevery** 2017-09-12 18:28 UTC
Labels: comp: upgrade/static, comp: zones, severity5: regression, type: bug
