### ISSUE TITLE
Dart: Using strings/microsyntax in the properties list is strange, error prone.

### ISSUE THREAD

**Issue by matanlurey** [angular/angular#2435] opened 2015-06-09 16:10 UTC
So I get the reason to move from a map to a list, because in most cases you want the properties to reflect their HTML mapping. However, this should either follow a convention (e.g. maxNum becomes max-num), or cease to be a list, because having 'fooBar: foo-bar' seems really strange in Dart.

Suggestions
---

1. Use a typed `List<Symbol>`, and enforce a convention (e.g. camel becomes hyphenated):

```dart
properties: const [
  #maxNum,
  #fooBar
],
```

2. Go back to Angular 1.0 Dart semantics and allow an annotation on the property setter

```dart
// Convention based, auto assigns to max-num
@NgProperty()
void set maxNum(int maxNum) { ... }

// Explicit
@NgProperty('max-num')
void set maxNum(int maxNum) { ... }
```

**Comment by vicb** [comment] 2015-06-09 16:19
@matanlurey `'fooBar' should work (you don't have to 'fooBar: foo-bar').
Are you experiencing issues with that ?
If not, does this solve your pb ?

**Comment by matanlurey** [comment] 2015-06-09 17:42
It does work, but it also defies HTML convention a bit, which prefers '-' to camel case.

**Comment by vicb** [comment] 2015-06-09 18:02
Note that DOM properties also are camelCased.

**Comment by mhevery** [comment] 2015-06-09 18:39
closing as it seems to work as intended. Please reopen if need be.

**Closed by mhevery** 2015-06-09 18:39 UTC
Labels: P3: important

**Comment by matanlurey** [comment] 2015-06-09 20:04
I understand it's working "as intended", but it isn't working as "wanted" :)

**Comment by mprobst** [comment] 2015-06-09 20:23
Have you tried having better intentions? ;-)
