### ISSUE TITLE
ReferenceError: Injectable is not defined when building with Ivy

### ISSUE THREAD

**Issue by SvenSeemann** [angular/angular#34829] opened 2020-01-17 12:43 UTC
# 🐞 bug report

### Description

After enabling Ivy my build is broken and I'm getting `Uncaught ReferenceError: Injectable is not defined`.

The affected service is from [TrilonIO/angular-application-insights](https://github.com/TrilonIO/angular-application-insights/blob/master/src/app-insight.service.ts#L57).

## 🔬 Minimal Reproduction
[Minimal Reproduction Repo](https://github.com/SvenSeemann/injectable-is-not-defined-test)

To reproduce run `ng build` with and without enableIvy flag and serving the build result in browser.

## 🔥 Exception or Error
<pre><code>
app-insight.service.js:325 Uncaught ReferenceError: Injectable is not defined
    at app-insight.service.js:325
    at Object../node_modules/@markpieszak/ng-application-insights/__ivy_ngcc__/dist/src/app-insight.service.js (app-insight.service.js:330)
    at __webpack_require__ (bootstrap:79)
    at Object../node_modules/@markpieszak/ng-application-insights/__ivy_ngcc__/dist/index.js (index.js:22)
    at __webpack_require__ (bootstrap:79)
    at Module../src/app/app.module.ts (app.module.ts:1)
    at __webpack_require__ (bootstrap:79)
    at Module../src/main.ts (main.ts:1)
    at __webpack_require__ (bootstrap:79)
    at Object.0 (main.ts:12)
</code></pre>

When comparing build results with a dummy service without this error there is a difference in the `type` in ngInjectableDef.

<pre><code>
// dummy service without error
type: _angular_core__WEBPACK_IMPORTED_MODULE_0__["Injectable"]

// service with error
type: Injectable
</code></pre> 

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.3.23
Node: 12.4.0
OS: darwin x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.23
@angular-devkit/build-angular     0.803.23
@angular-devkit/build-optimizer   0.803.23
@angular-devkit/build-webpack     0.803.23
@angular-devkit/core              8.3.23
@angular-devkit/schematics        8.3.23
@angular/cli                      8.3.23
@ngtools/webpack                  8.3.23
@schematics/angular               8.3.23
@schematics/update                0.803.23
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.39.2
</code></pre>

**Comment by JoostK** [comment] 2020-01-17 14:26
I expect this to be a duplicate of #31394. Could you please update to Angular `9.0.0-rc.9` to test the latest Ivy fixes, as Ivy support in Angular 8 is way behind.

If the problem still persists after updating, please let me know so I can reopen.

**Closed by JoostK** 2020-01-17 14:26 UTC
