### ISSUE TITLE
Type check listeners

### ISSUE THREAD

**Issue by pauldraper** [angular/angular#27707] opened 2018-12-17 15:13 UTC
# 🚀 feature request

### Relevant Package

@angular/core or @angular/compiler

### Description

Angular checks that the bound properties exist, whether on the component or the DOM.

However, it does not check whether listened events exit, whether on the component or the DOM.

### Describe the solution you'd like

Similar to properties, maintain a list of allowed events, and cause a compile error if they are unrecognized.

### Describe alternatives you've considered

I've considered never making a typo again.

**Comment by pkozlowski-opensource** [comment] 2018-12-17 18:54
Duplicate of the existing issue #3426

**Closed by pkozlowski-opensource** 2018-12-17 18:54 UTC

**Comment by pauldraper** [comment] 2018-12-17 19:56
Ooh boy, that's a small issue number.
