### ISSUE TITLE
get routeParams in a service

### ISSUE THREAD

**Issue by jabaa** [angular/angular#12488] opened 2016-10-24 15:00 UTC
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Can't get routeParams in a service

**Expected behavior**

Get routeParams in a serivce

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

Shift the logic from component to service

**Please tell us about your environment:**

* **Angular version:** 2.0.X

2.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment] 2016-10-24 15:16
Duplicate of https://github.com/angular/angular/issues/11023

**Closed** 2016-10-24 15:19 UTC
