### ISSUE TITLE
Fail to insert raw html in iframe in Firefox using ngAfterViewInit()

### ISSUE THREAD

**Issue by bryjohns** [angular/angular#26148] opened 2018-09-27 20:33 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

This is an issue in Firefox and not WebKit based browsers.  
Setting raw HTML into an IFrame ViewChild using ngAfterViewInit fails to show inserted HTML.  
In the stackbuiltz demo I provided I noticed that it renders correctly for a few Milliseconds then the demo HTML is removed. 

## Expected behavior

Setting raw HTML into an IFrame ViewChild using ngAfterViewInit should show the inserted HTML .

## Minimal reproduction of the problem with instructions

All important code is in iframe-test.component  
This demonstrates that the iframe is not rendering the HTML set in the ViewChild. A timeout is set to demonstrate that it works when the action occurs after the "ngAfterViewInit" event.
This demo will work fine in Chrom/Webkit and demonstrates the issue in Firefox
https://stackblitz.com/edit/angular-ggmr7y

## What is the motivation / use case for changing the behavior?

I would like to make a preview component that renders HTML with default styling applied.

## Environment

<pre><code>
Angular version: X.Y.Z

Angular 6.1.8

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version 62
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by trotyl** [comment] 2018-09-28 02:47
It's the VanillaJS behavior, can be reproduced without using Angular: 
https://stackblitz.com/edit/js-ylvhs8

The issue is that Firefox only allows change after `load` event for that iframe happens: 
https://stackoverflow.com/questions/9967478/iframe-content-disappears-on-firefox

**Comment by pkozlowski-opensource** [comment] 2019-03-07 13:58
Thnx @trotyl for the investigation! I'm going to close this one as I don't think there is much we can do about it here..

**Closed by pkozlowski-opensource** 2019-03-07 13:58 UTC
Labels: comp: core & compiler, freq1: low, severity3: broken, type: bug/fix
