### ISSUE TITLE
Issue with angular (8.2.0), swagger-ui (3.24.0) integration

### ISSUE THREAD

**Issue by jayanthmay1** [angular/angular#33306] opened 2019-10-21 21:55 UTC
# 🐞 bug report

### Description
Unable to integrate swagger-ui (3.24.0) with Angular (8.2.0). The same is working fine with swagger-ui (3.21.0) with Angular (7.2.0)

## 🔬 Minimal Reproduction

 https://stackblitz.com/...

## 🔥 Exception or Error
_stream_writable.js:57 **Uncaught ReferenceError: process is not defined** at Object../node_modules/readable-stream/lib/_stream_writable.js (_stream_writable.js:57) at webpack_require (bootstrap:79) at Object../node_modules/readable-stream/readable-browser.js (readable-browser.js:4) at webpack_require (bootstrap:79) at Object../node_modules/stream-browserify/index.js (index.js:28) at webpack_require (bootstrap:79) at Object. (swagger-ui.js:8) at n (swagger-ui.js:1) at Object. (swagger-ui.js:1) at Object. (swagger-ui.js:1)
<br>
**I believe this issue is related to Polyfills and related to Angular, SwaggerUI versions incompatibility.
I tried with Angular (7.2.0) and SwaggerUI (3.21.0) and it works perfectly fine.
For your reference, here is the link I followed for SwaggerUI (3.21.0) integrate with Angular (7.2.0) https://github.com/agoncal/swagger-ui-angular6**

## 🌍  Your Environment

**Angular Version:** 8.2.0
<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by trotyl** [comment] 2019-10-22 02:23
Duplicate of https://github.com/angular/angular-cli/issues/9827

---

See https://github.com/angular/angular-cli/issues/9827#issuecomment-369578814 for detailed explanation.

**Comment by IgorMinar** [comment] 2019-11-08 20:23
This seems to be a swagger-ui issue because it appears to depend on the `process` global directly or indirectly (via its dependencies).

Angular did no polyfill this global in v7, so I'm not sure why upgrading to v8 would affect this, but since you are updating the swagger-ui library as well, I suspect that somehow the dependencies have changed to also include code that depends on `process`.

I suggest that you contact the swagger-ui authors.

**Closed by IgorMinar** 2019-11-08 20:23 UTC
Labels: comp: core
