### ISSUE TITLE
Change detection issue when implementing ControlValueAccessor along with ngOnInit

### ISSUE THREAD

**Issue by chrillewoodz** [angular/angular#12855] opened 2016-11-14 11:30 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
After implementing `ControlValueAccessor` to the component, `ngOnInit` can no longer set a default value for `this.model`. No matter what I do it does not update the component view or notify outside components of the change. 

**Expected behavior**
`ngOnInit` would update the view and notify outside components of the change.

**Minimal reproduction of the problem with instructions**
1. Open console
2. Check the message (this is the default model set by `ngOnInit`
3. Check the `pre` elements in the template (you will see `null` for the component template and `''` for the outside one), both of these should display `{id: 0, name: 'Item 1'}` but does not.

Demo:
https://plnkr.co/edit/gGCiYjcq70xaewn3n22F?p=preview

**What is the motivation / use case for changing the behavior?**
This is needed when writing custom form elements and you want a default value without having to set a default value in the outside model, the component should take care of that.

**Please tell us about your environment:**
OS X Sierra, using the latest Angular CLI version.

* **Angular version:** 2.0.X
Fails on both 2.0.2 and 2.1.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
typescript

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment] 2016-11-14 12:57
Duplicate of https://github.com/angular/angular/issues/12607

**Comment by chuckjaz** [comment] 2016-11-16 02:23
Thanks for reporting this issue. However this issue is a duplicate of an existing issue #12607. Please subscribe to that issue for future updates.

**Closed by chuckjaz** 2016-11-16 02:23 UTC
