### ISSUE TITLE
Angular 13 performance changes compared to previous major version

### ISSUE THREAD

**Issue by olcayusta** [angular/angular#45380] opened 2022-03-17 16:01 UTC
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

While testing Angular 12.2.16 and Angular 13.3.0, I saw a decrease in FCP and Speed ​​Index values ​​and an improvement in TBT values.

Then I went down to the first version of version 13 and looked for the change that created this result, unfortunately the result did not change. The first next version of Angular 13 had the same result.

Next, I wanted to test Angular with an experimental feature.

Experimental feature: `(erenderComponent)`

```typescript
import { enableProdMode, ɵrenderComponent as renderComponent } from '@angular/core';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';

import { AppModule } from './app/app.module';
import { environment } from './environments/environment';
import {AppComponent} from "./app/app.component";

if (environment.production) {
  enableProdMode();
}

renderComponent(AppComponent)

/*
platformBrowserDynamic().bootstrapModule(AppModule)
  .catch(err => console.error(err));
*/
```

With the AppModule disabled, the app behaved differently this time, and the speed was different.
So the problem seems to be caused by starting the application with the AppModule.

https://angular-12-2-16.vercel.app
https://angular-13-3-0.vercel.app
https://angular-13-3-0-render-component.vercel.app

**Angular 12.2.16**
<img src="https://user-images.githubusercontent.com/52415595/158841695-1537939a-2ff1-4f67-b277-03379c18bc1b.png" width=500>

**Angular 13.3.0**
<img src="https://user-images.githubusercontent.com/52415595/158841701-d7fa567b-af65-4c54-bdfd-fc8104519a00.png" width=500>

**Angular 13.3.0 renderComponent without module**
<img src="https://user-images.githubusercontent.com/52415595/158891330-bd98b380-c801-4fdb-9ab3-b96eec20a6a2.png" width=500>

### Please provide a link to a minimal reproduction of the bug

https://angular-13-3-0.vercel.app/

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.3.0
Node: 16.14.0
Package Manager: yarn 1.23.0-20200615.1913
OS: win32 x64

Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1303.0 (cli-only)
@angular-devkit/core         13.3.0 (cli-only)
@angular-devkit/schematics   13.3.0 (cli-only)
@schematics/angular          13.3.0 (cli-only)
```

### Anything else?

I tested it with other versions, including Next, RC, and the result is still the same.
I couldn't figure out what caused the change that made this difference.

**Comment by eneajaho** [comment] 2022-03-17 17:03
I run the tests in pagespeed.web.dev and every time I ran, it it gave me different results. So the metrics are not 100% correct all the time.

- https://pagespeed.web.dev/report?url=https%3A%2F%2Fangular-13-3-0.vercel.app%2F
- https://pagespeed.web.dev/report?url=https%3A%2F%2Fangular-12-2-16.vercel.app%2F
<img width="975" alt="Screenshot 2022-03-17 at 6 01 48 PM" src="https://user-images.githubusercontent.com/25394362/158854404-90f3f2c6-0879-4286-987d-80bff4f671cc.png">
<img width="1012" alt="Screenshot 2022-03-17 at 6 02 01 PM" src="https://user-images.githubusercontent.com/25394362/158854452-96c02939-5cb7-4025-afb1-7e1d3dce30c1.png">

**Comment by olcayusta** [comment] 2022-03-17 17:43
Yes, I tried it on Chrome versions 99, 100, 101 using the incognito mode and I get the same results.
@alan-agius4 You need to run the test on Mobile instead of Desktop. On Desktop, the difference is already incomprehensible.

**Comment by olcayusta** [comment] 2022-03-17 17:52
I would also like to point out that pagespeed insights and web.dev are not giving correct results. Please try locally for the best results.

**Comment by olcayusta** [comment] 2022-03-17 20:59
@alan-agius4 Yes, I did all the tests in incognito mode, mobile type and Developer Tools. Seems like the problem is due to bootstrap with AppModule. I'd appreciate it if you could take a look, thank you.

**Comment by tszpinda** [comment] 2022-06-15 10:55
Having the same problem Speed Index when from being bad 3.4s to horrible 8s! any ideas?

**Comment by alan-agius4** [comment] 2022-11-08 13:29
Duplicate of https://github.com/angular/universal/issues/2106

**Closed by alan-agius4** 2022-11-08 13:29 UTC
Labels: area: server
