### ISSUE TITLE
extends @Input property from Base class won't work properly with ivy

### ISSUE THREAD

**Issue by yusuke-oba1** [angular/angular#33274] opened 2019-10-20 15:36 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/core

### Is this a regression?

 No

### Description

I have defined Input binding in the base class in some cases. The sample code is like below.

```
export class Base {
  @Input() text: string;
}

@Component({
  selector: 'app-test',
  templateUrl: './test.component.html',
  styleUrls: ['./test.component.scss']
})
export class TestComponent extends Base {
  constructor() {
    super();
  }
}
```

And, binding this 'text' input with appComponent 
```
<app-test [text]="'ivy test'"></app-test>
```

With enable ivy, it causes compiler error on startup.
```
ERROR in src/app/app.component.html:1:11 - error TS8002: Can't bind to 'text' since it isn't a known property of 'app-test'.
1. If 'app-test' is an Angular component and it has 'text' input, then verify that it is part of this module.
2. If 'app-test' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.

1 <app-test [text]="'ivy test'"></app-test>
            ~~~~~~~~~~~~~~~~~~~

  src/app/app.component.ts:5:16
    5   templateUrl: './app.component.html',
                     ~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component AppComponent.
```

If Ivy is not enabled, the compiler will not cause an error.

## 🔬 Minimal Reproduction

 
```
git clone https://github.com/yusuke-oba1/ivy-test
cd ivy-test
npm install
npm start
```

## 🌍  Your Environment

**Angular Version:**

```
Angular CLI: 9.0.0-next.12
Node: 10.14.1
OS: darwin x64
Angular: 9.0.0-next.12
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-next.12
@angular-devkit/build-angular     0.900.0-next.12
@angular-devkit/build-optimizer   0.900.0-next.12
@angular-devkit/build-webpack     0.900.0-next.12
@angular-devkit/core              9.0.0-next.12
@angular-devkit/schematics        9.0.0-next.12
@ngtools/webpack                  9.0.0-next.12
@schematics/angular               9.0.0-next.12
@schematics/update                0.900.0-next.12
rxjs                              6.5.3
typescript                        3.6.4
webpack                           4.41.1
```

**Comment by JoostK** [comment] 2019-10-20 15:40
Thanks for reporting, however this is a duplicate of #30080, please follow that one!

**Closed by JoostK** 2019-10-20 15:40 UTC
