### ISSUE TITLE
RouterStateSnapshot.url does not include complete sub-path anymore

### ISSUE THREAD

**Issue by magioloro** [angular/angular#52582] opened 2023-11-07 14:40 UTC
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

No

### Description

After updating from Angular 14 to 16 and refactoring guards to functional guards, there is a new behavior of RouterStateSnapshot.url.

Prior, the entire sub path was included in the property (/download/start-download), now only the last part is included (start-download). 

Angular 14:
![image](https://github.com/angular/angular/assets/56970844/2da3f2f3-51ca-4c5a-aa38-096d18b9c5e4)

Angular 16:
![image](https://github.com/angular/angular/assets/56970844/ba97b7a8-5954-40e3-aa73-7eca6acd95d7)

Does anyone know a solution for this? How can I get the complete path again?

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 16.2.8
Node: 18.16.0
Package Manager: yarn 3.6.1
OS: win32 x64

Angular: 16.2.11
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
```

**Comment by atscott** [comment] 2023-11-07 14:46
Please provide a reproduction. In your second screenshot, the url is an array so it looks like your state variable is the ActivatedRouteSnapshot, not the RouterStateSnapshot.

**Comment by magioloro** [comment] 2023-11-07 15:45
> Please provide a reproduction. In your second screenshot, the url is an array so it looks like your state variable is the ActivatedRouteSnapshot, not the RouterStateSnapshot.

Yes i do use RouterStateSnapshot in both cases. I have extended the screenshot.

**Comment by atscott** [comment] 2023-11-07 17:01
@magioloro - `RouterStateSnapshot` is the second argument, not the first. You should update your guard to use the `CanActivateFn` type to avoid this mistake (`hasCustomerId: CanActivateFn = ...`). Closing as working as expected.

**Closed by atscott** 2023-11-07 17:01 UTC
