### ISSUE TITLE
location.back() does not work on cancelled route

### ISSUE THREAD

**Issue by michelherv** [angular/angular#14645] opened 2017-02-22 15:10 UTC
**I'm submitting a ...
```
[x] bug report
[ ] feature request
[ ] support request 
```

**Current behavior**
I'm using a guard to protect a route (**View Two**). User can go from **View One** to **View Two**. Guard checks if application has some state. If not, the guard redirect the user on a dedicated page (**View State**). On that page user will give the expected state to application. After that, I do a **location.back()**. This calls send back the user on page **View One** not on **View Two**.

**Expected behavior**
I will like that 'location.back()' back to the cancelled route (**View Two**)

**Minimal reproduction of the problem with instructions**
[A demonstration on plunkr](https://plnkr.co/edit/wxRFQlXNyClzLStcKtZQ?p=preview)

**What is the motivation / use case for changing the behavior?**
In my application, there are optional pages (optional functionalities). Those pages can be accessed only if some configurations has been done before. When users try to navigate to those pages for the first time, I redirect them to the configuration pages. On those configuration pages, I want to use 'location.back()' to back to the cancelled routes.

**Please tell us about your environment:**
* **Environment:** Windows 7, Atom, npm, Webpack-dev-server

* **Angular version:** 2.4.8
* **Browser:** all
* **Language:** TypeScript 2.1.5
* **Node (for AoT issues):** `node --version` = 6.9.5

**Comment by SamVerschueren** [comment] 2017-03-17 21:05
I took a deep dive into the router in order to track down what causes this and I found some things. Just not sure how to fix this but thought I could share my findings already.

So, the guards are executed right [here](https://github.com/angular/angular/blob/master/packages/router/src/router.ts#L655). So when navigating to `views/two`, `shouldActivate` is `false`.

So then the router goes to the next check, which is the [preActivationResolveData](https://github.com/angular/angular/blob/master/packages/router/src/router.ts#L660-L668) step. But at that point, [this check](https://github.com/angular/angular/blob/master/packages/router/src/router.ts#L661) kicks in. The `navigationId` is incremented already. The reason for this is quite simple, at that point, your guard initiated a new navigation which in turns triggers [`scheduleNavigation`](https://github.com/angular/angular/blob/master/packages/router/src/router.ts#L529) which on his turn [increments the navigation id](https://github.com/angular/angular/blob/master/packages/router/src/router.ts#L557).

```js
this.router.navigate(['/views/state']);
```

So what I tried to do, just to check if it worked, was calling `location.pushState()` right [here](https://github.com/angular/angular/blob/master/packages/router/src/router.ts#L656). It calls `pushState` correctly but `location.back()` still redirects to `views/one`.

**Comment by szh** [comment] 2017-03-30 21:28
This is still broken in Angular 4.0. Any plans to fix it?

**Comment by atscott** [comment] 2020-05-26 20:59
Duplicate of #13586

**Closed by atscott** 2020-05-26 20:59 UTC
Labels: comp: router, freq2: medium, severity3: broken, type: bug/fix
