### ISSUE TITLE
[Proposal] Add removeAll method for FormArray

### ISSUE THREAD

**Issue by sinedsem** [angular/angular#22430] opened 2018-02-24 14:24 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Now I have to write the following when I need to remove all controls from FormArray
```
while (this.formArray.length > 0) {
  this.formArray.removeAt(0);
}
```

## Expected behavior
I suggest to introduce method removeAll() with the implementation above to make FormArray API more user-friendly.

**Comment by trotyl** [comment] 2018-02-26 01:51
Duplicate of https://github.com/angular/angular/issues/18531

**Closed** 2018-02-26 15:03 UTC
