### ISSUE TITLE
computed doesn't work

### ISSUE THREAD

**Issue by mbagiella** [angular/angular#53118] opened 2023-11-22 16:46 UTC
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

[https://stackblitz.com/edit/stackblitz-starters-hvntvw?description=An%20angular-cli%20project%20based%20on%20@angular/animations,%20@angular/common,%20@angular/compiler,%20@angular/core,%20@angular/forms,%20@angular/platform-browser,%20@angular/platform-browser-dynamic,%20@angular/router,%20core-js,%20rxjs,%20tslib%20and%20zone.js&file=src%2Fmain.ts&title=Angular%20Starter](url)

computed doesn't work

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-hvntvw?description=An%20angular-cli%20project%20based%20on%20@angular/animations,%20@angular/common,%20@angular/compiler,%20@angular/core,%20@angular/forms,%20@angular/platform-browser,%20@angular/platform-browser-dynamic,%20@angular/router,%20core-js,%20rxjs,%20tslib%20and%20zone.js&file=src%2Fmain.ts&title=Angular%20Starter

### Please provide the exception or error you saw

```true
the value is not updated
```

### Anything else?

it works here : https://stackblitz.com/edit/angular-vv4wpn?file=src%2Fmain.ts,src%2Ftest.service.ts,src%2Findex.html

**Comment by atscott** [comment] 2023-11-22 16:54
Duplicate of https://github.com/angular/angular/issues/52735

the list the the computed depends on was mutated and maintained reference equality so it never notified the computed of any updates.

**Closed by atscott** 2023-11-22 16:54 UTC
