### ISSUE TITLE
input (change)

### ISSUE THREAD

**Issue by SallyOne** [angular/angular#6557] opened 2016-01-19 09:05 UTC
hi, i search document to fing change event.but it is none.I don't understand why angular2 don't have this event.

**Comment by pkozlowski-opensource** [comment] 2016-01-19 09:46
@SallyOne I'm not sure what you mean, since Angular2 doesn't "have" any events (that is, there is no special code in the framework to handle or not a particular event). 

You can subscribe to / listen to _any_ DOM event using `(eventName)="exp"` syntax (so `<input (change)="doSth()">` should work perfectly fine.

I'm going to close this one since I don't think there is missing in the framework. If you still believe that there are changes needed in the framework itself please provide more details and a live reproduce scenario using plunker or similar. Thnx!

**Closed by pkozlowski-opensource** 2016-01-19 09:46 UTC

**Comment by SallyOne** [comment] 2016-01-21 07:20
hi, <input (change)="doSth()"/> can't work.now, <input (input)="doSth()"/> can work.

**Comment by SallyOne** [comment] 2016-01-21 07:20
(input) event replace (change) event
