### ISSUE TITLE
@angular/forms: pattern directive shoud accept regexp; 

### ISSUE THREAD

**Issue by Kopleman** [angular/angular#12556] opened 2016-10-27 07:58 UTC
**I'm submitting a feature request** 

**Current behavior**
Now We can only pass strings to directive. And sometimes it is quite hard to test becouse you need to escape it and IDEs dont test it on fly.

**Minimal reproduction of the problem with instructions**
Here [plank](https://plnkr.co/edit/PIpQqCqp8pwKJD8g63Ha?p=preview) that shows the problem

**What is the motivation / use case for changing the behavior?**
Better code mantaining

* **Angular version:** 2.0.3

Thank you.

**Comment by DzmitryShylovich** [comment] 2016-10-27 08:02
https://github.com/angular/angular/pull/12323

already implemented but not released

**Comment by DzmitryShylovich** [comment] 2016-10-27 08:03
Should be fixed by https://github.com/angular/angular/pull/12323

**Comment by pkozlowski-opensource** [comment] 2016-10-27 17:18
Duplicate of #10150, already fixed in master. Thnx @DzmitryShylovich

**Closed by pkozlowski-opensource** 2016-10-27 17:18 UTC
