### ISSUE TITLE
HttpResponse's HttpHeader object is Undefined

### ISSUE THREAD

**Issue by dbwhddn10** [angular/angular#29825] opened 2019-04-11 08:58 UTC
# 🐞 bug report

### Affected Package
@angular/http

### Description
HttpHeader object(in HttpRequest)  is no problem
but I want to check server's response header..
httpHeader object(in HttpResponse) is undefined

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-fu4hgj?file=src%2Fapp%2Fjson-response.provider.ts

please see "json-response.provider.ts" file

## 🔥 Exception or Error
<pre><code>
  intercept(request: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {

    request = request.clone({
      setHeaders: {
        Authorization: `Bearer AAAAAAAAAAAAAAA`
      }
    });

    console.log(request.headers.keys()); // ["Authorization"]

    return next
      .handle(request)
      .pipe(map((event: HttpEvent<any>) => {
        let response = event;        
        console.log(response.headers); // undefined
        console.log(response.headers.keys()); // Error: Cannot read property 'keys' of undefined
        return response;
      }));
  }
</code></pre>

## 🌍  Your Environment
<pre><code>
**Angular Version:**
Angular CLI: 7.3.7
Node: 10.15.3
OS: win32 x64
Angular: 7.2.11
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.7
@angular-devkit/build-angular     0.13.7
@angular-devkit/build-optimizer   0.13.7
@angular-devkit/build-webpack     0.13.7
@angular-devkit/core              7.3.7
@angular-devkit/schematics        7.3.7
@angular/cli                      7.3.7
@ngtools/webpack                  7.3.7
@schematics/angular               7.3.7
@schematics/update                0.13.7
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.29.0
</code></pre>

**Comment by trotyl** [comment] 2019-04-13 16:58
Duplicate of https://github.com/angular/angular/issues/18098

---

`let response = <HttpResponse<any>>event;`

The problem is that your assertion is not true at runtime, an [`HttpEvent`](https://angular.io/api/common/http/HttpEvent) can be several type other than `HttpResponse`, and there is always an [`HttpSentEvent`](https://angular.io/api/common/http/HttpSentEvent).

**Comment by alxhub** [comment] 2019-04-23 22:47
As @trotyl says, the cast in the reproduction is not legal - there are other types of events besides `HttpResponse`.

**Closed by alxhub** 2019-04-23 22:47 UTC
Labels: comp: common/http
