### ISSUE TITLE
Required @Input()

### ISSUE THREAD

**Issue by muhamedkarajic** [angular/angular#46949] opened 2022-07-23 01:25 UTC
### Description

Inputs in Angular arent required at all and bugs are cached while manually testing the code. We could write for every component checks if the object will be present onInit if its null etc. From my personall experience this leads to bigger and less maintainable code structure.

### Proposed solution

I suggest angulars takes a look to add either a new pipe @Required - which I have an example for, or extend the existing one @Input to additionally provide a object with meta data if its required, what value are allowed etc.

```typescript
@RequiredInputs()
@Component({
...
})
export class MyComponent {
   readonly data$ = new ReplaySubject<string[] | undefined>();

  @Input() @Required() set data(data: string[] | undefined) { // By default undefined, null and NaN are forbidden. To change behavior just pass config.
    this.data$.next(data);
  }
}
```

### Alternatives considered

My code currently works for observables but the exact same behavior can be built for basic input fields.

For more see those files:
https://github.com/muhamedkarajic/angular-playground/tree/main/src/app/shared/decorators

P.S:

In order to extend existing decorator @Input() we should make the current string be of an string | object type. If an object is passed inside the object can be the proper input identifier and if inside that object there is no identifier it would (as currently) use the property name. If there isn't any value passed or a string is passed (as now) it would fall back to the current behavior - that way nothing would break.

**Comment by atscott** [comment] 2022-07-23 03:54
Duplicate of https://github.com/angular/angular/issues/37706

**Closed by atscott** 2022-07-23 03:54 UTC

**Comment by muhamedkarajic** [comment] 2022-07-24 00:45
I dont think this is a duplicate in the real sense cause I'm taking a declarative approach where I'm strictly forbidding the input whenever it comes it gets checked, its also possible to tell for each input what kind of values are allowed and not.

**Comment by muhamedkarajic** [comment] 2022-07-27 21:19
> @muhamedkarajic The proposed solution may be different but the feature request is the same: Provide a way to define required inputs. How this gets implemented may or may not be any of the proposed solutions. That said, we really want to consolidate all discussions rather than having 4 different issues open for each feature request.

I have stated my perspective on the topic on the other proposal, looking forward to find the best solution.

**Comment by thw0rted** [comment] 2022-08-10 06:11
@atscott if it makes any difference, I opened the issue that you called a duplicate.  @muhamedkarajic is proposing runtime type validation, while the linked issue (and the ~5 prior issues on the topic) is proposing a change to the template engine, along the lines of `strictTemplates` -- I don't believe any of the previous issues were suggesting runtime checks.

IMHO, these are different requests, and if Muhamed wishes to continue pursuing runtime checks, that would be better handled as a separate requirement.  If you agree, could you please reopen this, and maybe edit the title to specify "runtime checking"?

**Comment by pkozlowski-opensource** [comment] 2022-08-10 07:17
@thw0rted we want to centralize the discussion about required inputs in one place, regardless of the proposed solution. Generally speaking we would like to have an issue that focuses on the problem statement as there are multiple approaches and we are not settling on any of the options just yet.
