### ISSUE TITLE
File type input ngModel's value isn't updating after file upload

### ISSUE THREAD

**Issue by Halfist** [angular/angular#13910] opened 2017-01-13 10:14 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
```

**Current behavior**
File type input ngModel's value isn't updating after file upload.

**Expected behavior**
File type input ngModel's value should be updated after file upload.

**Minimal reproduction of the problem with instructions**
Steps to reproduce:
1. Bind component's class property to file type input via ngModel directive.
2. Output ngModel's value to a view.
3. Upload a file.

Demo: http://plnkr.co/edit/WC8lnvkUnOw1wxeZ0P7M.

**Environment:**

**OS:** Windows 10.
**IDE:** WebStorm 2016.3.2.

* **Angular version:** 4.0.0-beta.1.

* **Browser:** Chrome 55. Surprisingly, bug isn't reproducible at least in IE 11.
 
* **Language:** TypeScript 2.0, ES6.

**Comment by DzmitryShylovich** [comment] 2017-01-13 10:19
Angular doesn't support input with `file` type
Duplicate of https://github.com/angular/angular/issues/7341

**Comment by pkozlowski-opensource** [comment] 2017-01-13 10:31
It is indeed duplicate of #7341, thnx @DzmitryShylovich !

**Closed by pkozlowski-opensource** 2017-01-13 10:31 UTC
