### ISSUE TITLE
DI not working properly when extending a component

### ISSUE THREAD

**Issue by lqbweb** [angular/angular#12485] opened 2016-10-24 13:53 UTC
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
If I extend a component (with some DI in the constructor) from another component that does not declares the exact same constructor, the DI on the latter component does not seem to work.

Have a look at the reproduction case.

**Minimal reproduction of the problem with instructions**

Service param is null here:

https://plnkr.co/edit/cxREj4x39ZsN8h7BySqe

**Comment by DzmitryShylovich** [comment] 2016-10-24 13:55
Duplicate of https://github.com/angular/angular/issues/11606

**Comment by lqbweb** [comment] 2016-10-24 13:57
Are you sure? I am not expecting DI to work on the parent class, I understand that.

**Comment by DzmitryShylovich** [comment] 2016-10-24 14:01
https://plnkr.co/edit/pnOnhMMGkixrjjz5AbUT?p=preview

1. You forget `,`
2. u cannot use decorators in the inherited class, 
3. cyclic dependency

**Comment by lqbweb** [comment] 2016-10-24 14:06
You have removed `@SkipSelf() @Host() @Optional()` right? It should not be cyclic because I am with `@SkipSelf`. Sorry I still do not see it, where did I miss a `,` ?

**Comment by lqbweb** [comment] 2016-10-24 14:07
I also tested what you say myself, If I do not specify any `@Host` on the parent one, it works.

**Comment by DzmitryShylovich** [comment] 2016-10-24 14:08
>  where did I miss a , ?

`@SkipSelf() @Host() @Optional() private parent: Base srv : Service`

**Comment by DzmitryShylovich** [comment] 2016-10-24 14:10
>  Why an annotation on the parent component makes the DI on the child not to work? it is weird.

because angular doesn't support inheritance yet. This is why a point u to https://github.com/angular/angular/issues/11606

**Comment by lqbweb** [comment] 2016-10-24 14:21
Right, after fixing the `,` the same problem. I do not fully understand, I was aware of #11606 but I thought that was about supporting mixing, I am not expecting mixing to work here.
This then makes impossible to inherit, no matter how, any component that declares any `@Host()`. Is this right?

**Comment by DzmitryShylovich** [comment] 2016-10-24 14:25
You should avoid inheritance until https://github.com/angular/angular/issues/11606 will be resolved. It's hard to predict what kind of issues u can face using inheritance.

**Comment by lqbweb** [comment] 2016-10-24 14:26
wow, pretty significant then. I close this. Thanks!

**Closed** 2016-10-24 14:27 UTC
