### ISSUE TITLE
Angular DevTool is showing "Angular application not detected".

### ISSUE THREAD

**Issue by Panchalyashh** [angular/angular#55210] opened 2024-04-04 05:41 UTC
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

Angular DevTool was working fine previously. now it is showing "Angular application not detected".

**Comment by JoostK** [comment] 2024-04-04 06:18
Duplicate of https://github.com/angular/angular/issues/55114

**Closed by JoostK** 2024-04-04 06:18 UTC
