### ISSUE TITLE
Content projection doesn't work with nested @if

### ISSUE THREAD

**Issue by kkachniarz220** [angular/angular#58120] opened 2024-10-08 09:26 UTC
### Which @angular/* package(s) are the source of the bug?

compiler

### Is this a regression?

No

### Description

Using content projection with new control flow nested @if doesn`t work.

**NOT WORKING**
```html
@if(true) {
  @if(true) {
    <div card-title>Some title</div>
  }
}
```

**WORKS WELL**
```html
@if(true) {
   <div *ngIf="true" card-title>Some title</div>
}
```

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-a9ttfd?file=src%2Fmain.ts

### Please provide the environment you discovered this bug in (run `ng version`)

Angular CLI: 18.2.7
Node: 18.20.3
Package Manager: npm 10.2.3
OS: linux x64

Angular: 18.2.7
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1802.7
@angular-devkit/build-angular   18.2.7
@angular-devkit/core            18.2.7
@angular-devkit/schematics      18.2.7
@schematics/angular             18.2.7
rxjs                            7.8.1
typescript                      5.5.4
zone.js                         0.14.10

**Comment by JeanMeche** [comment] 2024-10-08 09:30
Duplicate of #54035.

**Closed by JeanMeche** 2024-10-08 09:30 UTC
