### ISSUE TITLE
Elvis operator doesn't work for banana-box ngModel

### ISSUE THREAD

**Issue by Nehareeka** [angular/angular#24800] opened 2018-07-09 07:44 UTC
I'm submitting a...
[x] Bug report

## Current behavior
I want to use elvis operator with [(ngModel)]="data?.firstName" to avoid undefined errors due to async calls.
However, it gives below error 
"Uncaught Error: Template parse errors
Parser Error: The '?.' operator cannot be used in the assignment "

A possible workaround is to separate [ngModel] and (ngModelChange) which is not desirable.

## Expected behavior
Elvis operator should be allowed to be used with banana-box ngModel syntax.
In case the value is null(possible why it is not supporting now), execute no action.

## Minimal reproduction of the problem with instructions
Use [(ngModel)] with elvis operator when getting init data asynchronously

## What is the motivation / use case for changing the behavior?
It is a fairly common usecase which is extensively required in an enterprise application due to high usage.

## Environment
Angular version: 5.2.9

**Comment by trotyl** [comment] 2018-07-09 07:47
Duplicate of https://github.com/angular/angular/issues/7697

**Comment by pkozlowski-opensource** [comment] 2018-07-09 08:14
Closing as a duplicate of #7697, thnx @trotyl

**Closed by pkozlowski-opensource** 2018-07-09 08:14 UTC
