### ISSUE TITLE
Compiler does not support exporting Regexp values

### ISSUE THREAD

**Issue by intellix** [angular/angular#14187] opened 2017-01-30 12:01 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Have a file containing: 
```typescript
export const mask = /\d/;
```
`ERROR in Error encountered resolving symbol values statically. Expression form not supported (position 5:21 in the original .ts file
), resolving symbol mask`

**Expected behavior**

To be able to export regexp symbols.

**Minimal reproduction of the problem with instructions**

Create a file containing: `export const mask = /\d/;`

**What is the motivation / use case for changing the behavior?**

I want to ship input masks for parsing locale date formats, for example: `[/\d/, /\d/, '/', /\d/, /\d/, '/', /\d/, /\d/, /\d/, /\d/]`

**Please tell us about your environment:**

OSX Sierra

* **Versions:**

angular-cli: 1.0.0-beta.25.5
node: 7.1.0
os: darwin x64
@angular/common: 2.4.3
@angular/compiler: 2.4.3
@angular/compiler-cli: 2.4.3
@angular/core: 2.4.3
@angular/forms: 2.4.3
@angular/http: 2.4.3
@angular/platform-browser: 2.4.3
@angular/platform-browser-dynamic: 2.4.3
@angular/router: 3.4.3
TypeScript 2.0.10

**Comment by DzmitryShylovich** [comment] 2017-03-10 08:47
Need to add support for `SyntaxKind.RegularExpressionLiteral` in [evaluateNode](https://github.com/angular/angular/blob/6bae7378b1ec3d9bfd18dcb090d011ce0688c231/tools/%40angular/tsc-wrapped/src/evaluator.ts#L221)

**Comment by DzmitryShylovich** [comment] 2017-03-30 09:44
@chuckjaz is this a tech limitation or just an oversight?

**Comment by chuckjaz** [comment] 2017-03-30 17:41
This is an intentional limitation. This shouldn't be needed during evaluation as our metadata doesn't require regular expressions.

Can I get more information when you are encountering this error?

**Comment by DzmitryShylovich** [comment] 2017-03-30 17:53
@chuckjaz just to use a regexp somewhere in metadata. for example:
```
import {Component, Inject, NgModule, VERSION} from '@angular/core'
import {BrowserModule} from '@angular/platform-browser';

export const regex = /a/;

@Component({
  selector: 'my-app',
  template: `
    <div>
      <h2>Hello {{name}}</h2>
    </div>
  `,
})
export class App {
  name:string;
  constructor(@Inject('test') reg) {
    this.name = `Angular! v${VERSION.full}`
  }
}

@NgModule({
  imports: [ BrowserModule ],
  declarations: [ App ],
  bootstrap: [ App ],
  providers: [{provide: 'test', useValue: regex}]
})
export class AppModule {}
```
ts 2.2.1

**Comment by chuckjaz** [comment] 2017-03-30 19:52
I see. As a work-around, for now, you can use `useFactory` that returns the value. That is not that convenient however, and we should support regex literals.

**Comment by zoryananaumko** [comment] 2017-06-06 16:05
Any progress on this?

**Comment by futurizing** [comment] 2018-02-15 21:03
I cannot reproduce the issue with Angular 5.0. Has this issue been resolved?

https://stackblitz.com/edit/regexp-export-test

**Comment by arobinson** [comment] 2019-06-21 18:46
This is still an issue with Angular 7. I am seeing it with a component failing with color checks. Example:
```
  private static verifyHex(hex: string): boolean {
    return /^(0[xX]|#)([0-9a-fA-F]{3}$)|([0-9a-fA-F]{6}$)|([0-9a-fA-F]{8}$)/.test(hex);
  }
```

Error:
```
 ...color.component.ts:1834:12: Metadata collected contains an error that will be reported at runtime: Expression form not supported.
  {"__symbolic":"error","message":"Expression form not supported","line":1833,"character":11}
```

**Comment by silberjan** [comment] 2019-07-30 13:55
still a problem in angular 8 when trying to put regex literals in `environment`

**Comment by csentis** [comment] 2019-10-29 13:02
any way to circumvent the `environment`'s limitation regarding RegExp?

**Comment by pkozlowski-opensource** [comment] 2020-03-10 19:51
The original issue reported here is fixed in Angular v9 running ivy: https://ng-run.com/edit/VgY4hu9Skcjzopo1WHoF

If you still encounter similar problems please open a new issue with a minimal reproduce scenario.

**Closed by pkozlowski-opensource** 2020-03-10 19:51 UTC
Labels: comp: core, effort1: hours, freq2: medium, severity3: broken, type: bug/fix
