### ISSUE TITLE
AOT Compilation Doesn't Work With Sub-Package Fonts

### ISSUE THREAD

**Issue by jameslafferty** [angular/angular#20676] opened 2017-11-29 00:39 UTC
## I'm submitting a...
[X] Bug report
(It _might_ be a regression, or it might be a bug uncovered in a browser vendor change.)

## Current behavior
When I run my project with `npm run ng -- serve --aot` or when I build `npm run build`, fonts don't show up in Chrome or Firefox. They _do_ show up correctly in Safari and they _do_ show up correctly across modern browsers when I run without --aot. See below for the project details.

## Expected behavior
Fonts should display correctly when I run under --aot.

## Minimal reproduction of the problem with instructions
Here's a repo with a minimum case reproduction:
https://github.com/jameslafferty/aot-font-issue

1. run `npm start`
2. Observe the 3 home icons at http://localhost:4200 in Chrome and Firefox
3. run `npm run ng -- serve --aot`
4. Observe the placeholder icons at the url above and the error in the dev tools console

## What is the motivation / use case for changing the behavior?
Providing a demo application within a mono-repo that hosts components used across many applications.

## Environment
Angular version: 5.0.3

Browser:
- [X] Chrome (desktop) version 62.0.3202.94
- [X] Firefox version 57.0

**Comment by wKoza** [comment] 2017-12-01 18:19
I can't reproduce your problem with `ng serve --aot' and chrome 62.0.3202.94

**Comment by jameslafferty** [comment] 2017-12-01 20:16
I'm also now having trouble reproducing it in my simplified example, although I'm still seeing the problem in our real-life code. I swear the issue came up in the example yesterday. Let me see if I can sort out what's different now between the two. Thanks for your patience and sorry about the noisiness.

**Comment by jameslafferty** [comment] 2017-12-05 18:00
It seems likely that this is the same issue as #8735. I'm also having trouble reproducing it there, and difficulty installing @chatham/pattern-library (which might be a private module that reporter is using -- similar to what I'm doing). Am continuing to work on reproducing. FWIW, I'd be content to track both issues together.

**Comment by jameslafferty** [comment] 2017-12-05 23:19
I've added another commit on my example repo (see above), and am now partly reproducing the issue:

![image](https://user-images.githubusercontent.com/1176300/33636101-aa7cb248-d9cf-11e7-9de9-0362ffbbe5b0.png)

**Comment by Andrew-Stubbs** [comment] 2017-12-06 09:10
The issue seems to be linked to the build containing two copies of the fonts causing issues when compiling in prod mode.

I can reproduce this duplication on my project 100% of the time, but the fonts only fail to show in the browser some of the time, I assume based on the lexicographical order of the duplicated fonts with hash.

This has only started happening since migration to angular-5.0.5, I'm attempting to put together a public MRE now.

Compiling without aot (`--aot=false`) or without output hashing media (`--output-hashing=bundles` or `--output-hashing=none`) also stops the duplication of fonts, but neither workaround is particularly appealing for long term production builds.

**Comment by jameslafferty** [comment] 2017-12-06 17:28
In my real-life project passing `--output-hashing` does remove the duplicate fonts, but doesn't help the Chrome/FF parsing issue for the fonts.

**Comment by laserus** [comment] 2017-12-11 11:11
@Andrew-Stubbs I tried to downgrade, but same errors happened for angular =5.0.0 for me

**Comment by cpboyd** [comment] 2018-01-12 02:03
I had zero issues with importing the Material Design Icons until the most recent version.
```SASS
@import '../../node_modules/material-design-icons/iconfont/material-icons.css';
```

The issue seems to be that the new `postcss-import` just chucks the imported CSS file inside of the one importing it, without resolving relative paths.

**Comment by pkozlowski-opensource** [comment] 2019-03-07 17:01
Could you please open, with a minimal reproduce scenario, in https://github.com/angular/angular-cli if this is still an issue? Thnx!

**Closed by pkozlowski-opensource** 2019-03-07 17:01 UTC
Labels: comp: core & compiler, freq1: low, severity3: broken, type: bug/fix
