### ISSUE TITLE
[Suggestion] Lazy load module using service

### ISSUE THREAD

**Issue by piernik** [angular/angular#24546] opened 2018-06-16 11:58 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

In angular we can lazy load module using router. It's a common example.

But is it possible to lazy load module from service or component?

Why do I need it?

I have two lazy loaded modules: clients and invoices. Both with it's add/edit view component. But in invoice add component I want to give possibility to add client in modal, so user don't have to abandon current form. So I have to lazy load ClientModule.

**Comment by trotyl** [comment] 2018-06-19 05:58
Duplicate of https://github.com/angular/angular/issues/22243

**Comment by jasonaden** [comment] 2018-06-21 23:52
This is a duplicate, but it should also be solved with the new Ivy project. Because Ivy changes how decorators compile so they only require local knowledge, lazy loading at any time shouldn't be an issue as the AOT compiler doesn't need the same global knowledge it previously did.

**Closed by jasonaden** 2018-06-21 23:52 UTC

**Comment by piernik** [comment] 2018-06-22 06:29
Great to hear. I can't wait for Ivy. I have lot of problems with AOT which, I hope, Ivy will resolve.
