### ISSUE TITLE
Broken hydration after v17 -> v18 migration if i18n blocks are used

### ISSUE THREAD

**Issue by zip-fa** [angular/angular#56074] opened 2024-05-24 18:25 UTC
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

Imagine this code:

```html
<div>
  @if (currentBreakpoint() === 'mobile') {
    <div class="mobile" i18n="@@test">
      Mobile content
    </div>
  } @else {
    <div class="desktop" i18n="@@test2">
      Desktop content
    </div>
  }
</div>
```

currentBreakpoint signal can be desktop, mobile or tablet. On server it's always set to 'desktop'.
When i add this little line to my component, hydration breaks and 'desktop' div never cleans up on mobile devices after hydration:

```ts
  private readonly vcr = inject(ViewContainerRef);
```

Video:

https://github.com/angular/angular/assets/61551308/654e3de3-26a4-4cbe-9510-6f4df2d736ad

### Please provide a link to a minimal reproduction of the bug

https://github.com/zip-fa/ng18-broken-hydration

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 18.0.1
Node: 21.7.3 (Unsupported)
Package Manager: npm 10.5.0
OS: darwin arm64

Angular: 18.0.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic
... platform-server, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1800.1
@angular-devkit/build-angular   18.0.1
@angular-devkit/core            18.0.1
@angular-devkit/schematics      18.0.1
@angular/cli                    18.0.1
@angular/ssr                    18.0.1
@schematics/angular             18.0.1
rxjs                            7.8.1
typescript                      5.4.5
zone.js                         0.14.6
    
Warning: The current version of Node (21.7.3) is not supported by Angular.
```

**Comment by JeanMeche** [comment] 2024-05-24 20:47
You repro doesn't exibit the issue you are describing. Can you double check ? 

Did you forgot the `withI18nSupport()` initially ? (without it hydration break).

**Comment by AndrewKushnir** [comment] 2024-05-24 21:43
@zip-fa thanks for providing a repro! As @JeanMeche mentioned, the problem doesn't seem to exist in the code as is, but when I **remove** `withI18nSupport()`, I see the following error:

```
Error: ASSERTION ERROR: Unable to retrieve hydration info from the
TransferState. [Expected=> null != undefined <=Actual]
```

Ideally, when i18n blocks are present, but there is no `withI18nSupport()`, hydration should work as it used to work before: components with i18n blocks should skip hydration. We should also consider producing a console warning in a browser for such cases and suggest adding `withI18nSupport()` call.

Looking at the HTML output, this is likely a culprit:

```
<app-test1 _nghost-ng-c1108691119="" ngskiphydration="" ngh="null|0">
```

i.e. the `ngh` attribute value contains `null`, which is likely unexpected and we should look at the serialization code, which appends `ngh` and see why we have `null` in this case.

cc @devknoll

**Comment by AndrewKushnir** [comment] 2024-05-24 22:27
More info after a bit more investigation: here is a unit test (can be added to the `packages/platform-server/test/hydration_spec.ts` file) that reproduces the issue:

```
        it('should append skip hydration flag if component uses i18n blocks and no `withI18nSupport()` call present', async () => {
          @Component({
            standalone: true,
            selector: 'app',
            template: '<div i18n>Hi!</div>',
          })
          class SimpleComponent {
            vcr = inject(ViewContainerRef);  // <-- this line triggers the issue 
          }

          const hydrationFeatures = [] as unknown as HydrationFeature<any>[];
          const html = await ssr(SimpleComponent, {hydrationFeatures});
          const ssrContents = getAppContents(html);
          expect(ssrContents).toContain('<app ngh');
        });
```

The fix would likely be somewhere in the `annotateLContainerForHydration` function ([code](https://github.com/angular/angular/blob/main/packages/core/src/hydration/annotate.ts#L179)), which would need to account for a case when i18n blocks are present, but `withI18nSupport()` function is not invoked (we have similar checks [here](https://github.com/angular/angular/blob/main/packages/core/src/hydration/annotate.ts#L612)).

**Comment by Openegg15** [comment] 2024-05-25 02:58
This is a follow-up to [#1822](https://rausauboocad.net/4/7446717) and [#100 ](https://tremblesyringeillusive.com/ne8muthq4i?key=474c9752b6833707c410d6e7be2d821f)

**Comment by zip-fa** [comment] 2024-05-25 08:01
<img width="710" alt="image" src="https://github.com/angular/angular/assets/61551308/db810804-1b2c-43af-ac88-01a9a81a201b">

<img width="751" alt="image" src="https://github.com/angular/angular/assets/61551308/39993be2-3b90-425e-a505-6412f88d055a">

<img width="515" alt="image" src="https://github.com/angular/angular/assets/61551308/55566aad-1549-447f-b126-46d3d0bbaf9c">


I am 100% sure that 'desktop' block is not removed on my setup - it stays in the DOM tree while it must be removed.
Tested on safari and chrome on mac os.

**Comment by zip-fa** [comment] 2024-05-25 08:05
Added slower video. When screen blinks, i just refresh the page (cmd+r):

https://github.com/angular/angular/assets/61551308/8f3ea5b0-a891-49db-a944-2f7015f0d485


@if (currentBreakpoint() === 'mobile') successfully becomes true on 'mobile screens', but @else block **is not removed from DOM tree**

**Comment by JeanMeche** [comment] 2024-05-25 09:14
This is due to the error thrown during hydration

**Comment by AndrewKushnir** [comment] 2024-05-30 04:31
@zip-fa FYI, I've created PR #56175 with the fix for the issue described in https://github.com/angular/angular/issues/56074#issuecomment-2130407699. The PR will go through the regular review and testing phases and will be included into one of the next 18.0.x releases. Thank you.

**Closed** 2024-05-30 18:37 UTC
Labels: area: i18n, area: core, state: has PR, state: confirmed, P3, core: hydration
