### ISSUE TITLE
Run resolve functions after all APP_INITIALIZER are finished

### ISSUE THREAD

**Issue by JoniJnm** [angular/angular#14767] opened 2017-02-27 14:44 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => (maybe related with #12162)
[ ] feature request
[ ] support request
```

**Current behavior**
Angular runs `resolve` methods before APP_INITIALIZER ends.

**Expected behavior**
Angular should wait for all APP_INITIALIZER promises and then run `resolve` functions for routes.

**Minimal reproduction of the problem with instructions**
https://plnkr.co/edit/MiWgLZ?p=preview

Choose angular version in config.js. In Angular 2.4.8 fails, in Angular 2.4.7 works.

**What is the motivation / use case for changing the behavior?**
In previous versions it works.

* **Angular version:**
2.4.8

Maybe related with #12162

**Comment by DzmitryShylovich** [comment] 2017-02-27 14:59
Duplicate of https://github.com/angular/angular/issues/14759

**Closed** 2017-02-27 20:21 UTC
