### ISSUE TITLE
When using Location.back() to navigate inside a router-outlet, ngOnInit() is called twice for sibling components of routerLinkActive directives.

### ISSUE THREAD

**Issue by mattheiler** [angular/angular#14331] opened 2017-02-06 23:17 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When using Location.back() to navigate inside a router-outlet, ngOnInit() is called twice for sibling components of routerLinkActive directives.

**Expected behavior**
ngOnInit() isn't called twice.

**Minimal reproduction of the problem with instructions**

```
<example-parent>
    <a routerLink="/path/to/next/component" routerLinkActive="link-active">NAVIGATE</a>     
    <example-child>
        <!-- ngOnInit() called twice! -->
    </example-child>
    <example-child>
        <!-- ngOnInit() called twice! -->
    </example-child>
</example-parent>
```

I've narrowed down the cause of this issue, but am not aware of the impact of either removing the line or changing the method called to a more _appropriate_ one...

[CONSIDER REPLACING DETECTCHANGES WITH MARKFORCHECK](https://github.com/angular/angular/blob/master/modules/%40angular/router/src/directives/router_link_active.ts?line132#L132)

**What is the motivation / use case for changing the behavior?**

ngOnInit() should be called once, when initializing the component.

**Please tell us about your environment:** Windows 7, VS2015, NPM.

* **Angular version:** 2.4.6

* **Browser:** All

 
* **Language:** All

* **Node (for AoT issues):** `node --version` =  6.3.1

**Comment by DzmitryShylovich** [comment] 2017-02-06 23:19
Duplicate of https://github.com/angular/angular/issues/14227

> CONSIDER REPLACING DETECTCHANGES WITH MARKFORCHECK

it won't work with markForCheck

**Comment by mattheiler** [comment] 2017-02-06 23:25
I wondered as much. Seemed to work with a quick test, but I wasn't so sure. I agree, this is a duplicate of 14227.

**Comment by DzmitryShylovich** [comment] 2017-02-07 14:32
@mattheiler can you pls close this on favor of #14227 ? No need to have 2 issues about 1 bug

**Comment by mattheiler** [comment] 2017-02-07 15:27
close

**Comment by mattheiler** [comment] 2017-02-07 15:30
close #14331

**Closed** 2017-02-07 15:45 UTC
