### ISSUE TITLE
Named outlets not working in child routes which are lazy loaded

### ISSUE THREAD

**Issue by ernestbofill** [angular/angular#22346] opened 2018-02-21 14:01 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

To report this issue I modified the [Routing & Navigating](https://angular.io/guide/router) live app on stackblitz.

The app routes looks like this:

```ts
const appRoutes: Routes = [
  {
    path: 'superheroes',
    component: HeroesComponent,
    children: [
      {
        path: 'other',
        component: HeroesBottomOtherComponent,
        outlet: 'bottom'
      },
      {
        path: '',
        component: HeroesBottomDefaultComponent,
        outlet: 'bottom'
      },
      {
        path: '',
        component: HeroListComponent
      },
    ]
  },
  { path: '', redirectTo: '/superheroes', pathMatch: 'full' },
  { path: '**', component: PageNotFoundComponent }
];
```

This routing configuration will load the `HeroesBottomDefaultComponent` in the `<router-outlet name="bottom">` by default. 

And will load `HeroesBottomOtherComponent` when clicking the link `<a [routerLink]="[{ outlets: { bottom: ['other'] } }]">`.

I would like to move the heroes related routes to a lazy loaded heroes module with it's own heroes-routing:

app-routing.module.ts
```ts
const appRoutes: Routes = [
  {
    path: 'superheroes',
    loadChildren: 'app/heroes/heroes.module#HeroesModule'
  },
  { path: '', redirectTo: '/superheroes', pathMatch: 'full' },
  { path: '**', component: PageNotFoundComponent }
];
```

heroes-routing.module.ts
```ts
const heroesRoutes: Routes = [
  {
    path: '',
    component: HeroesComponent,
    children: [
      {
        path: 'other',
        component: HeroesBottomOtherComponent,
        outlet: 'bottom'
      },
      {
        path: '',
        component: HeroesBottomDefaultComponent,
        outlet: 'bottom'
      },
      {
        path: '',
        component: HeroListComponent
      },
    ]
  },
];

@NgModule({
  imports: [
    RouterModule.forChild(heroesRoutes)
// ...
```

In this case the `HeroesBottomOtherComponent` doesn't work with the link `<a [routerLink]="[{ outlets: { bottom: ['other'] } }]">`

## Expected behavior

I would like to activate named outlet in lazy loaded child routes in the same way they work without lazy loading.

## Minimal reproduction of the problem with instructions

I modified the [Routing & Navigating](https://angular.io/guide/router) live app on stackblitz.

[stackblitz of the lazy loaded setup which presents the issues](https://stackblitz.com/edit/angular-457w8a-jzprp1)

[stackblitz of the working version without lazy loading](https://stackblitz.com/edit/angular-457w8a-tgidcv)

## What is the motivation / use case for changing the behavior?

I want to create an application where the layout is preserved on page navigation but the content of certain areas is changed, for example a `<router-outlet name="left">`,  `<router-outlet name="right">` and  `<router-outlet>` for the main content area. 

## Environment

<pre><code>
Angular version: 5.2.4

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by Serginho** [comment] 2018-04-10 11:06
That issue makes me crazy. I can't bear angular router, too many issue around this one.

**Comment by jamesguan** [comment] 2018-04-18 21:16
+1. Trying to have a higher order component such as app component with a router outlet that loads a child component that serves as a layout that has a named router outlet, that should load in that named router outlet other components, but it gives me a "Cannot match any routes" error. I'm trying to avoid having to reload my layout every time I change my URL.

**Comment by jasonaden** [comment] 2018-05-03 22:52
This looks like a duplicate of #10981. This is being worked on, finishing some testing to make sure the fix corrects the issue. Please subscribe to that issue for updates.

**Closed by jasonaden** 2018-05-03 22:52 UTC
Labels: comp: router
