### ISSUE TITLE
IVY+Angular elements

### ISSUE THREAD

**Issue by shashankanugu** [angular/angular#36094] opened 2020-03-17 04:37 UTC
# 🐞 bug report

### Description

Building Angular elements in angular 9 with shared libraries approach(multiple angular elements on same page, so pre-loading), results in the below runtime error.

## 🔥 Exception or Error
<pre><code>
scripts.90116728e913cf95ae8b.js:10415 Uncaught NullInjectorError: StaticInjectorError(Platform: core)[CompilerFactory]:
  NullInjectorError: No provider for CompilerFactory!

</code></pre>

## 🌍  Your Environment

**Angular Version:**
angular.json
<pre><code>
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "newProjectRoot": "projects",
  "projects": {
    "angular9-new": {
      "projectType": "application",
      "schematics": {
        "@schematics/angular:component": {
          "style": "scss"
        }
      },
      "root": "",
      "sourceRoot": "src",
      "prefix": "app",
      "architect": {
        "build": {
          "builder": "@angular-builders/custom-webpack:browser",
          "options": {
            "customWebpackConfig": { "path": "./extra-webpack.config.js",
              "mergeStrategies": { "externals": "replace" } },
            "outputPath": "dist/angular9-new",
            "index": "src/index.html",
            "main": "src/main.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "tsconfig.app.json",
            "aot": true,
            "assets": [
              "src/favicon.ico",
              "src/assets"
            ],
            "styles": [
              "src/styles.scss"
            ],
            "scripts": [
              {
                "bundleName": "polyfill-webcomp-es5",
                "input": "node_modules/@webcomponents/webcomponentsjs/custom-elements-es5-adapter.js"
              },
              {
                "bundleName": "polyfill-webcomp",
                "input": "node_modules/@webcomponents/webcomponentsjs/bundles/webcomponents-sd-ce-pf.js"
              },
              "node_modules/rxjs/bundles/rxjs.umd.js",
              "node_modules/@angular/core/bundles/core.umd.js",
              "node_modules/@angular/common/bundles/common.umd.js",
              "node_modules/@angular/common/bundles/common-http.umd.js",
              "node_modules/@angular/compiler/bundles/compiler.umd.js",
              "node_modules/@angular/animations/bundles/animations.umd.js",
              "node_modules/@angular/animations/bundles/animations-browser.umd.js",
              "node_modules/@angular/platform-browser/bundles/platform-browser.umd.js",
              "node_modules/@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js",
              "node_modules/@angular/elements/bundles/elements.umd.js",
              "node_modules/@angular/router/bundles/router.umd.js",
              "node_modules/@angular/cdk/bundles/cdk.umd.js",
              "node_modules/@angular/forms/bundles/forms.umd.js"
            ]          },
          "configurations": {
            "production": {
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true,
              "budgets": [
              ]
            }
          }
        }
      }
    }
  },
  "defaultProject": "angular9-new",
  "cli": {
    "analytics": false
  }
}

</code></pre>
app.module.ts
<pre><code>
import {BrowserModule} from '@angular/platform-browser';
import {NgModule, Injector, NO_ERRORS_SCHEMA, CUSTOM_ELEMENTS_SCHEMA} from '@angular/core';
import {AppComponent} from './app.component';
import {createCustomElement} from '@angular/elements';
import { HttpClientModule} from '@angular/common/http';
import {CommonModule} from '@angular/common';

@NgModule({
    declarations: [
        AppComponent
    ],
    imports: [
        BrowserModule,
        HttpClientModule,
        CommonModule,
    ],
    entryComponents: [AppComponent],
    schemas: [NO_ERRORS_SCHEMA, CUSTOM_ELEMENTS_SCHEMA]
})
export class AppModule {
    constructor(private injector: Injector) {
    }

    ngDoBootstrap() {
        if (!customElements.get(`my-app`)) {
            const customElement = createCustomElement(AppComponent, {injector: this.injector});
            customElements.define(`my-app`, customElement);
        }
    }
}

</code></pre>
extra-webpack.config.json

<pre><code>
module.exports = {
    output: {
        jsonpFunction: 'webpackJsonpViewMemo'
    },
    "externals": {
        "rxjs": "rxjs",
        "rxjs/operators": "rxjs.operators",
        "@angular/core": "ng.core",
        "@angular/common": "ng.common",
        "@angular/common/http": "ng.common.http",
        "@angular/compiler": "ng.compiler",
        "@angular/platform-browser": "ng.platformBrowser",
        "@angular/platform-browser-dynamic": "ng.platformBrowserDynamic",
        "@angular/elements": "ng.elements",
        "@angular/router": "ng.router",
        "@angular/forms": "ng.forms",
        "@angular/cdk": "ng.cdk",
        "@angular/animations": "ng.animations",
        "@angular/animations/browser": "ng.animations.browser"
    }
};
</code></pre>

package.json
<pre><code>
 "dependencies": {
    "@angular/animations": "~9.0.6",
    "@angular/common": "~9.0.6",
    "@angular/compiler": "~9.0.6",
    "@angular/core": "~9.0.6",
    "@angular/elements": "^9.0.6",
    "@angular/forms": "~9.0.6",
    "@angular/platform-browser": "~9.0.6",
    "@angular/platform-browser-dynamic": "~9.0.6",
    "@angular/router": "~9.0.6",
    "rxjs": "~6.5.4",
    "tslib": "^1.10.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-builders/custom-webpack": "^9.0.0",
    "@angular-devkit/build-angular": "~0.900.6",
    "@angular/cli": "^7.2.2",
    "@angular/compiler-cli": "~9.0.6",
    "@angular/language-service": "~9.0.6",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^12.11.1",
    "codelyzer": "^5.1.2",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.3.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~2.1.0",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.2",
    "ngx-build-plus": "^9.0.6",
    "protractor": "~5.4.3",
    "ts-node": "~8.3.0",
    "tslint": "~5.18.0",
    "typescript": "~3.7.5"
  }
</pre></code>

**Comment by flash-me** [comment] 2020-03-18 15:31
Try one of this:

- **EITHER** Change you angular imports to: <br>  `node_modules/@angular/<package>/__ivy_ngcc__/bundles/<package>.umd.js` in your index.html

- **OR** Do **not** creaty ivy endpoints when compiling with **ngcc**: <br> `ngcc --properties main es2015`

cheers
flash :zap:

**Comment by flash-me** [comment] 2020-03-18 15:33
P.S.

You do not need entrycomponents anymore.

cheers
flash :zap:

**Comment by crisz** [comment] 2020-03-19 09:53
@flash-me  what about using the cli?

> Try one of this:
> 
> * **EITHER** compile UMD bundles with `ngcc --properties main --create-entry-points` and change you angular imports to:   `node_modules/@angular/<package>/__ivy_ngcc__/bundles/<package>.umd.js`
> * **OR** Do **not** creaty ivy entry points when compiling with **ngcc**:  `ngcc --properties main es2015`
> 
> cheers
> flash ⚡️

**Comment by flash-me** [comment] 2020-03-19 17:37
@crisz To accomplish what? He is already using the CLI to create his angular element. But since he compiles with ivy enabled he also needs to include the ivy compiled versions of the angular packages. 

cheers
flash :zap:

**Comment by crisz** [comment] 2020-03-20 16:43
@flash-me my fault, I had misunderstood the problem that you are trying to solve. Thank you for clarity.

Best regards

**Comment by ramesh-yadav** [comment] 2020-04-27 17:07
Same issue I am getting on Linux (Docker Container). But on my Mac it is working fine.

How...................

I dont want to disable ivy.

**Comment by flash-me** [comment] 2020-04-28 08:14
Hi @ramesh-yadav 

sounds like @angular/compiler is not included which indicates that ivy is not enabled. Are you sure that your docker builds have ivy enabled? 

cheers 
flash :zap:

**Comment by ramesh-yadav** [comment] 2020-04-28 08:22
> Hi @ramesh-yadav 
> 
> sounds like @angular/compiler is not included which indicates that ivy is not enabled. Are you sure that your docker builds have ivy enabled? 
> 
> cheers 
> flash :zap:

Yes,

And issue is only when UMD files are used with ngx-build-plus and external webpack config.

For simple application everything is fine.

**Comment by flash-me** [comment] 2020-04-28 09:29
How are you compiling your UMD bundles? (the ngcc command) Are you sure you are using IVY compiled UMD bundles?

You don't need ngx-build-plus. https://github.com/flash-me/angular-micro-frontends

cheers 
flash :zap:

**Comment by shashankanugu** [comment] 2020-04-28 16:25
running npm install with --unsafe-perm will solve you're issue "npm install --unsafe-perm". 
Make sure to run post install also "postinstall": "ngcc --properties main es2015"

**Comment by flash-me** [comment] 2020-04-28 19:20
> running npm install with --unsafe-perm will solve you're issue "npm install --unsafe-perm".
> Make sure to run post install also "postinstall": "ngcc --properties main es2015"

which compiles the UMD bundles with Ivy :smile:
That's why I asked him if he compiles them also for the UMD format. 

cheers 
flash :zap:

**Comment by ramesh-yadav** [comment] 2020-04-29 18:33
> running npm install with --unsafe-perm will solve you're issue "npm install --unsafe-perm". 
> Make sure to run post install also "postinstall": "ngcc --properties main es2015"

Thanks

**Comment by gkalpak** [comment] 2020-07-13 15:39
I am afraid I am not able to understand the problem that is being reported (and whether it is related to Angular Elements, ngcc, the CLI or something entirely different).

Based on that, I am going to close this issue. If you are still running into this problem with the latest Angular version, please open a new issue and provide a minimal reproduction.

**Closed by gkalpak** 2020-07-13 15:39 UTC
Labels: comp: elements
