### ISSUE TITLE
Cannot use &#123;&#123; &#125;&#125; in template

### ISSUE THREAD

**Issue by hadley8899** [angular/angular#44320] opened 2021-11-30 21:45 UTC
### Which @angular/* package(s) are the source of the bug?

compiler

### Is this a regression?

No

### Description

Looks as if angular will not currently allow &#123;&#123; &#125;&#125; to be put into the HTML template, It throws the error 

NG5002: Parser Error: Blank expressions are not allowed in interpolated strings at column 6 in [Hello {{}}] in /home/ryan/dev/projects/github/test-stuff/src/app/app.component.html@0:3

To reproduce this error just ng new and add &#123;&#123; &#125;&#125; anywhere in the template

### Please provide the exception or error you saw

```true
NG5002: Parser Error: Blank expressions are not allowed in interpolated strings at column 6 in [Hello {{}}] in /home/ryan/dev/projects/github/test-stuff/src/app/app.component.html@0:3
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 13.0.3
Node: 16.13.0
Package Manager: npm 8.1.4
OS: linux x64

Angular: 13.0.2
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1300.3
@angular-devkit/build-angular   13.0.3
@angular-devkit/core            13.0.3
@angular-devkit/schematics      13.0.3
@angular/cli                    13.0.3
@schematics/angular             13.0.3
rxjs                            7.4.0
typescript                      4.4.4
```

**Comment by atscott** [comment] 2021-11-30 21:50
Here's what you're looking for: https://angular.io/guide/attribute-directives#deactivating-angular-processing-with-ngnonbindable

i.e.
```
<ng-container ngNonBindable>
Hello {{ }}
</ng-container>
```

Closing as working as intended.

**Closed by atscott** 2021-11-30 21:50 UTC
