### ISSUE TITLE
Language service doesn't correctly check inputs/outputs of banana in a box

### ISSUE THREAD

**Issue by StephenFluin** [angular/angular#26107] opened 2018-09-25 22:31 UTC
## I'm submitting a...

<pre><code>
[X] Bug report  
</code></pre>

## Current behavior
Parent Component
```
export class Parent {
  title:string;
}
```

```
<app-child [(bat)]="title"></app-child>
```

Child Component
```
export class Child {
@Input() bat;
@Output() batTypoChange = new EventEmitter<any>();
}
```

This does not warn with the language service. The language service only checks the Input.

## Expected behavior
The language service should warn if the output we are binding to is missing.

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/bug-banana-box-langservice?file=src%2Fapp%2Fapp.component.html

## Environment

<pre><code>
Angular version: X.Y.Z
Angular CLI: 6.1.5
Node: 10.6.0
OS: linux x64
Angular: 6.1.8
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.7.5
@angular-devkit/build-angular     0.7.5
@angular-devkit/build-optimizer   0.7.5
@angular-devkit/build-webpack     0.7.5
@angular-devkit/core              0.7.5
@angular-devkit/schematics        0.7.5
@angular/cli                      6.1.5
@ngtools/webpack                  6.1.5
@schematics/angular               0.7.5
@schematics/update                0.7.5
rxjs                              6.3.2
typescript                        2.7.2
webpack                           4.9.2

Others:

</code></pre>

**Comment by trotyl** [comment] 2018-11-17 16:50
Duplicate of https://github.com/angular/angular/issues/16952

**Comment by kyliau** [comment] 2018-12-05 00:14
This is will be addressed as part of the language service upgrade after Ivy is released

**Comment by JoostK** [comment] 2021-05-13 21:35
Since the language service now achieves type-checking using compiler, this is now sort-of working. If a corresponding output is not present the compiler will target the output side of a banana-in-a-box binding at the native element, so you'll see errors about `Event` types not being assignable to the input type. This is tracked in #39300, so closing this one as resolved.

**Closed by JoostK** 2021-05-13 21:35 UTC
Labels: P4, comp: language-service, feature, freq2: medium
