### ISSUE TITLE
Decorator usages no longer working with AOT when a function is passed as a parameter

### ISSUE THREAD

**Issue by michaelgeorgeattard** [angular/angular#21111] opened 2017-12-20 15:30 UTC
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Given the following decorator:

```
export function foo(
  test: any
) {
  return (_target: any, _name: string, descriptor: PropertyDescriptor) => {
  };
}
```
And the following usage:

```
@foo(() => 5)
bar() {
}
```

I am getting the following error:

```
Error encountered in metadata generated for exported symbol 'xxx':
 C:/git/xxx/_artifact/xxx/xxx.ts:48:24: Metadata collected contains an error that will be reported at runtime: Lambda not supported.
  {"__symbolic":"error","message":"Lambda not supported","line":47,"character":23}
```

Changing the decorator usage to the following works:

```
@foo(5)
bar() {
}
```

This breaks when building AOT

## Expected behavior

Function parameters in decorators worked before and are expected to work in 5.x.x

## What is the motivation / use case for changing the behavior?

This functionality used to work correctly in 4.x.x

## Environment

<pre><code>
Angular version: 5.1.1

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.7.0 
- Platform:  Windows 

Others:

</code></pre>

**Comment by alan-agius4** [comment] 2017-12-20 21:02
@chuckjaz can you shed some light please if it’s intended to behave this way? Also, correct me if I am wrong but ‘@dynamic’ wouldn’t help here right?

Wish there was a bit of documentation about what @dynamic is used for.

Thanks

**Comment by chuckjaz** [comment] 2017-12-20 21:53
@alan-agius4 I am writing the documentation for `"strictMetadataEmit"` today and it will land as part of my work on #20987.

In this case you can add

```ts
// @dynamic
export function foo(
  test: any
) {
  return (_target: any, _name: string, descriptor: PropertyDescriptor) => {
  };
}
```

Alternately, you can just not enable `"strictMetadataEmit"` which is off by default. Unless you are bundling a library for `npm`, you should not use this option.

I am closing this as this is working as intended and Angular 4 didn't support this either and would emit the same error if you did not specify that the function was not intended to be used in an Angular annotation.

**Closed by chuckjaz** 2017-12-20 21:53 UTC
Labels: comp: core & compiler

**Comment by alan-agius4** [comment] 2017-12-20 22:01
Hey chuck, thanks for the quick reply.

I am indeed bundling a library thats why I need ‘strictMetadataEmit’ with
skipTemplteCodeGen’

**Comment by alan-agius4** [comment] 2017-12-20 22:13
Hey @chuckjaz , thanks for the quick reply and for the solution. However it seems that it still doesn't work

```ts 
// @dynamic
export function foo(
  test: any
) {
  return (_target: any, _name: string, descriptor: PropertyDescriptor) => {
  };
}
export class FooClas {

  @foo(() => '')
  bar() {

  }
}
```

```
Error: /Users/alan/Documents/ng-packagr/integration/samples/core/public_api.ts:14:1: Error encountered in metadata generated for exported symbol 'FooClas':
 /Users/alan/Documents/ng-packagr/integration/samples/core/public_api.ts:11:10: Metadata collected contains an error that will be reported at runtime: Lambda not supported.
  {"__symbolic":"error","message":"Lambda not supported","line":10,"character":9}
```
I am indeed bundling a library that is why I need `strictMetadataEmit` with `skipTemplateCodegen`

**Comment by chuckjaz** [comment] 2017-12-21 00:05
Can you,

1) create a new issue with with the title something like "@dynamic is suppressing a metadata error".
2) create a repository I can clone that reproduces this error so I don't have to guess at how to reproduce this.

**Comment by alan-agius4** [comment] 2017-12-21 06:49
@chuckjaz opened a new issue #21123
