### ISSUE TITLE
when can this angular integrate "closure compiler"?

### ISSUE THREAD

**Issue by jackzhp** [angular/angular#19968] opened 2017-10-27 04:16 UTC
## I'm submitting a...

<pre><code>
[x ] Feature request
</code></pre>

## Current behavior
currently works with webpack.

## Expected behavior
work with closure compiler.

**Comment by CaerusKaru** [comment] 2017-10-27 04:29
Duplicate of https://github.com/angular/angular/issues/8550

**Comment by trotyl** [comment] 2017-10-27 05:55
Angular can always be integrated with Closure compiler ADVANCED mode after view engine introduced. If you're asking Angular CLI support, please reopen it in [this repo](https://github.com/angular/angular-cli).

**Comment by pkozlowski-opensource** [comment] 2017-10-30 09:47
I'm sorry but we don't understand the problem you are reporting.

If the problem still exists please open a new issue and provide a plunker reproducing the problem and describing the difference between the expected and current behavior.

**Closed by pkozlowski-opensource** 2017-10-30 09:47 UTC
