### ISSUE TITLE
DevTools - Minor - Icon visibility on dark backgrounds

### ISSUE THREAD

**Issue by iessa-pragg-ctct** [angular/angular#58011] opened 2024-09-30 01:49 UTC
### Is this a bug report or a feature request?

- [X] Bug Report
- [ ] Feature Request

### Please provide the steps to reproduce the issue [Bug Report only]

Install dev tools in firefox with dark theme active.

### Please provide the expected behavior vs the actual behavior you encountered [Bug Report only]

Expected: Icon is visible
Actual: Icon is very hard to see

### Please provide a screenshot if possible [Bug Report only]

![image](https://github.com/user-attachments/assets/f2b19d3e-e2a6-4084-a612-d25e1fd95b4e)

### Is this a browser-specific issue? If so, please specify the device, browser, and version. [Bug Report only]

```true
Firefox

Probably present in chrome with darker modes applied.
```

**Comment by JoostK** [comment] 2024-09-30 04:21
Thanks for reporting, this is a duplicate of https://github.com/angular/angular/issues/52980.

**Closed** 2024-09-30 04:21 UTC
