### ISSUE TITLE
Instance of service from NgModule.imports is not being injected in NgModule constructor or declared components

### ISSUE THREAD

**Issue by bossqone** [angular/angular#36720] opened 2020-04-20 16:32 UTC
# 🐞 bug report

### Affected Package
@angular/core

### Is this a regression?
I don't know

### Description
I have an issue with DI/NgModule. Injected `TranslateService` in `SharedModule` constructor (or `SharedComponent` constructor) is different than expected. From my understanding the nearest instance in DI hierarchy should be injected, which should be an instance registered from `TranslateModule.forChild()` (`TranslateLoader` + `TranslateService`) defined in `SharedModule.imports`. But instead `TranslateService` with `LazyTranslateLoader` (from `LazyModule`) is injected.

I've tried `SkipSelf()` in `SharedModule` or change order of imports in `LazyModule` or even define providers directly in `SharedModule` without using `TranslateModule.forChild()` but nothing has changed.

Only thing that works is to define providers directly on `SharedComponent`, but it's unfortunate because then I need to modify all components within `SharedModule`.

I couldn't find existing opened/closed issue which would be relevant to this.

## 🔬 Minimal Reproduction
- open console, there are logs
https://stackblitz.com/edit/angular-4ckgm4?file=src%2Fapp%2Fshared-module%2Fshared.module.ts

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.3.26
Node: 12.13.0
OS: darwin x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.26
@angular-devkit/build-angular     0.803.26
@angular-devkit/build-optimizer   0.803.26
@angular-devkit/build-webpack     0.803.26
@angular-devkit/core              8.3.26
@angular-devkit/schematics        8.3.26
@angular/cdk                      8.2.3
@angular/cli                      8.3.26
@ngtools/webpack                  8.3.26
@schematics/angular               8.3.26
@schematics/update                0.803.26
rxjs                              6.5.5
typescript                        3.5.3
webpack                           4.39.2
</code></pre>

**Comment by pkozlowski-opensource** [comment] 2020-04-21 12:08
This sounds very similar (duplicate?) to #11281

**Comment by jelbourn** [comment] 2020-10-23 22:06
Duplicate of #11281

**Closed by jelbourn** 2020-10-23 22:06 UTC
Labels: comp: core, core: di
