### ISSUE TITLE
docs say watch defaults to false, but it defaults to true

### ISSUE THREAD

**Issue by mbward** [angular/angular#28140] opened 2019-01-14 21:35 UTC
https://angular.io/cli/test says

```
--watch=true|false | Run build when files change. Default: false
```

But with Angular CLI 7.2.0, `ng test --watch=false` behaves differently than `ng test`, meaning that false is not actually the default.

Edit: or was this fixed in fc2d19d766d002d4816244ae9393a5faff762524, and just needs pushing to the docs site?

**Comment by alan-agius4** [comment] 2019-01-15 07:38
Duplicate of https://github.com/angular/angular/issues/27146. (Will be addressed by #27024.)

**Comment by jenniferfell** [comment] 2019-01-25 01:20
Notes: The affected doc is generated, not hand-written. The fix is a change to the doc generation tools, in the PR linked above by @alan-agius4

**Comment by gkalpak** [comment] 2019-01-25 09:40
Closing as duplicate of #angular/angular-cli#12816

**Closed by gkalpak** 2019-01-25 09:40 UTC
Labels: comp: docs, docsarea: cli and config, freq3: high, severity3: broken, state: has PR, subtype: docs-wrong, type: bug/fix
