### ISSUE TITLE
Generics for FormBuilder, FormGroup, FormControl

### ISSUE THREAD

**Issue by IliaVolk** [angular/angular#23472] opened 2018-04-20 16:29 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Classes FormControl, FormGroup, FormBuilder, etc are not generic.

## Expected behavior

Add generics to them, like
```
class FormBuilder {
    group<E>(controls: Controls<E>, extra?) {
        return new FormGroup(controls, extra);
    }
    control<E>(state: FormControlState<E>, extra?) {
        return new FormControl(state, extra);
    }
}

type Controls<E> = {
    [K in keyof E]: FormControl<E[K]>;
};
class FormGroup<E> {
    value: E;
    controls: Controls<E>;
    constructor(controls: Controls<E>, ...args) {}
}

type ExtendedState<E> = {
    value: E,
    disabled?: boolean,
};
type FormControlState<E> = ExtendedState<E>|E;

class FormControl<E> {
    value: E;
    constructor(state: FormControlState<E>, ...args) {}
}

const builder = new FormBuilder();
const form = builder.group({
    a: builder.control('str'),
    b: builder.control([]),
    c: builder.control(1),
});
const a = form.value.a;
const d = form.value.d;
```
In this case will be typescript(2.8.3) error 
`error TS2339: Property 'd' does not exist on type '{ a: string; b: any[]; c: number; }'.`.

## What is the motivation / use case for changing the behavior?

Type validation and IDE autocomplete for FormGroup.value, FormControl.value.

## Environment

 - typescript version: >=2.8.3

Others:
- IDE: WebStorm
</code></pre>

**Comment by trotyl** [comment] 2018-04-23 05:56
Duplicate of https://github.com/angular/angular/issues/13721

**Comment by kara** [comment] 2018-04-24 19:51
Closing as dupe

**Closed by kara** 2018-04-24 19:51 UTC
Labels: comp: forms
