### ISSUE TITLE
[Angular Service Worker] checkForUpdate should trigger when old artefact is rolled back

### ISSUE THREAD

**Issue by shaleen0077** [angular/angular#42940] opened 2021-07-23 08:07 UTC
Scenario - We deploy the code and let say it has hash 'HASH-V1' and next day we deploy the new code which has hash 'HASH-V2'. Let say V2 has bug, and we have to revert to last good know state i.e. V1 here. Now if the server is serving 'HASH-V1' then angular pwa service worker ignores this version thinking its a old version (which is true) as it is present in it cache.

Current code: 

      checkForUpdate() {
            return __awaiter(this, void 0, void 0, function* () {
                let hash = '(unknown)';
                try {
                    const manifest = yield this.fetchLatestManifest(true);
                    if (manifest === null) {
                        // Client or server offline. Unable to check for updates at this time.
                        // Continue to service clients (existing and new).
                        this.debugger.log('Check for update aborted. (Client or server offline.)');
                        return false;
                    }
                    hash = hashManifest(manifest);
                    // Check whether this is really an update.
                    if (this.versions.has(hash)) { <--- This line is the issue
                        return false;
                    }
                    yield this.setupUpdate(manifest, hash);
                    return true;
                }
                catch (err) {
                    this.debugger.log(err, `Error occurred while updating to manifest ${hash}`);
                    this.state = DriverReadyState.EXISTING_CLIENTS_ONLY;
                    this.stateMessage = `Degraded due to failed initialization: ${errorToString(err)}`;
                    return false;
                }
            });
        }

Suggested change:

     checkForUpdate() {
            return __awaiter(this, void 0, void 0, function* () {
                let hash = '(unknown)';
                try {
                    const manifest = yield this.fetchLatestManifest(true);
                    if (manifest === null) {
                        // Client or server offline. Unable to check for updates at this time.
                        // Continue to service clients (existing and new).
                        this.debugger.log('Check for update aborted. (Client or server offline.)');
                        return false;
                    }
                    hash = hashManifest(manifest);
                    // Check whether this is really an update.
                    if (this.latestHash === hash) { <-- Change
                        return false;
                    }
                    yield this.setupUpdate(manifest, hash);
                    return true;
                }
                catch (err) {
                    this.debugger.log(err, `Error occurred while updating to manifest ${hash}`);
                    this.state = DriverReadyState.EXISTING_CLIENTS_ONLY;
                    this.stateMessage = `Degraded due to failed initialization: ${errorToString(err)}`;
                    return false;
                }
            });
        }

**Comment by gkalpak** [comment] 2021-07-23 09:09
This is essentially a duplicate of #24338. As explained in https://github.com/angular/angular/issues/24338#issuecomment-395795128, there is no 100% reliable check (for example, imagine a proxy or CDN configured to cache the content for 1 hour).

Commit 586234bb0197ad21b2a6efe8612ad1cfdecaba39 provides a way around this by re-building the old version (or manually updating the timestamp in the generated `ngsw.json`).

I am going to close this, since I don't think there is an ideal solution here, but feel free to continue the discussion below.

**Closed by gkalpak** 2021-07-23 09:09 UTC

**Comment by shaleen0077** [comment] 2021-07-23 12:00
Thanks @gkalpak for looking into it. If we replace the check of `this.versions.has(hash)` with `this.latestHash === hash` then it would work. Do you see any downside to this?

**Comment by gkalpak** [comment] 2021-07-23 13:11
Imagine this scenario:

- You deploy version `V1`.
- The ServiceWorker downloads it, caches it and marks it as `latest`.
- Later you deploy version `V2`.
- The ServiceWorker downloads it, caches it and marks it as `latest`. It still keeps `V1` in its cache, because there are clients using it.
- Shortly after, the ServiceWorker checks again for updates.

Now imagine that you are using a CDN to serve your assets. If a CDN node happens to not be updated yet and still serves `V1`, the ServiceWorker might randomly get `V1` for a short time after `V2` has been deployed.

With the `this.latestHash === hash` check, the ServiceWorker would incorrectly re-instate `V1` as the `latest` version.
Does that make sense?
