### ISSUE TITLE
[BUG]: Angular 9 doesn't work correctly with NGXS decorators with UMD

### ISSUE THREAD

**Issue by splincode** [angular/angular#37203] opened 2020-05-19 17:57 UTC
# 🐞 bug report

### Affected Package

@angular/compiler

### Is this a regression?

Yes

### Description

https://stackblitz.com/edit/angular-9-ngxs?file=src/app/store/todo/todo.state.ts

```ts
@Persistence([
  {
      path: 'todos',
      existingEngine: localStorage
  }
])
@StateRepository()
@State<TodoStateModel>({
  name: 'todos',
  defaults: {
    todos: [],
    loaded: false,
    selectedTodo: null
  }
})
@Injectable()
export class TodoState
  extends NgxsDataRepository<TodoStateModel> {

  @Selector()
  public static todos(state: TodoStateModel) {
    return state.todos;
  }

  constructor(private readonly api: TodoApiService) {
    super()
  }

}
```

![image](https://user-images.githubusercontent.com/12021443/82360862-af569f80-9a12-11ea-9e5b-dc1056d3d2bc.png)

NGXS validates decorators through a handle. But now this does not work with Angular 9. However, if you build the application locally on the machine, everything works. Doesn't work only on stackblitz, is that because it uses CommonJS?

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-9-ngxs?file=src/app/store/todo/todo.state.ts

## 🔥 Exception or Error
<pre><code>
Error in /turbo_modules/@ngxs/store@3.6.2/__ivy_ngcc__/bundles/ngxs-store.umd.js (4626:23)
Selectors only work on methods
</code></pre>

## 🌍  Your Environment

**Angular Version:**

Angular 9.1.7

**Comment by petebacondarwin** [comment] 2020-05-19 18:34
From what I can see the compiled code is not passing a 4th argument to `__decorate`...

```ts
tslib_1.__decorate([
    store_1.Selector(),
    tslib_1.__metadata("design:type", Function),
    tslib_1.__metadata("design:paramtypes", [TodoStateModel]),
    tslib_1.__metadata("design:returntype", void 0)
], TodoState, "todos");
```

**Comment by petebacondarwin** [comment] 2020-05-19 18:43
There are some old versions of typescript mentioned in the stackblitz package.json...

**Comment by petebacondarwin** [comment] 2020-05-19 18:57
I also note that if I turn off ivy then the decorator looks like:

```
__decorate([
    store_1.Selector(),
    __metadata("design:type", Function),
    __metadata("design:paramtypes", [TodoStateModel]),
    __metadata("design:returntype", void 0)
], TodoState, "todos", null);
```

There is now a `null` but it is now a different error about the `CompilerFactory`...

**Comment by splincode** [comment] 2020-05-19 19:42
@petebacondarwin is this an Angular problem, or am I doing something wrong as a developer?

**Comment by petebacondarwin** [comment] 2020-05-19 19:47
Honestly, right now, I cannot say. I don't think it is an Angular bug since these `__decorate()` calls are added by TypeScript not the Angular compiler directly.

It might be a bug in TypeScript, in the case of UMD/CommonJS...
Or perhaps related to how Stackblitz is setup.

It would be interesting to try to force a standalone version of your reproduction to use UMD rather than ES2015... we could do this by deleting the other fields from the package.json  ...If it fails then, we can discount Stackblitz from the equation. I'll have a go tomorrow.

**Comment by splincode** [comment] 2020-05-19 19:59
@petebacondarwin Thanks for your work!

**Comment by petebacondarwin** [comment] 2020-05-20 14:26
I note in https://www.typescriptlang.org/docs/handbook/decorators.html#method-decorators there is:

> NOTE  The Property Descriptor will be undefined if your script target is less than ES5.

Now in StackBlitz the tsconfig.json is set to `ES2015` but perhaps Stackblitz actually changes that??

**Comment by petebacondarwin** [comment] 2020-05-20 14:56
One more thing I have found... Running it locally the `desc` parameter is set to `null`. In this case the `__decorate()` function will compute the `desc`:

```
var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
```

**Comment by petebacondarwin** [comment] 2020-05-20 14:57
In any case, I think that this is an issue with how TS and Stackblitz are playing together.

**Comment by petebacondarwin** [comment] 2020-05-21 07:16
It appears from talking to their team that this is actually a small bug in StackBlitz. apai4 is going to put a fix together! I am closing this here as it is not an issue with the Angular Framework.

**Closed by petebacondarwin** 2020-05-21 07:16 UTC
Labels: comp: compiler, state: needs more investigation, type: bug/fix
