### ISSUE TITLE
Improve Service Worker Failsafe and Upgrade Tool

### ISSUE THREAD

**Issue by adamzr** [angular/angular#24827] opened 2018-07-10 22:17 UTC
## I'm submitting a...

<pre><code>
[X] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[X] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
Client fails to load, shows blank white page. I believe that this is because the service worker is loading an old index.html page, and the JS assets on that page are not available on the server or in the service worker cache.

I tried making /ngsw.json return a 404, but that didn't help.

## Expected behavior
Service Worker failsafe should have deleted itself after seeing the 404 for /ngsw.json even though the MIME type of the 404 page is HTML. In fact any problem with that JSON file, e.g. getting a 500 or getting 200 and HTML, should result in the service worker deleting itself.

The ng update script should changed the ngsw-config file to use the new JS and CSS naming scheme.

The service worker should delete itself if Angular fails to load (i.e. main script is not cached and not available on the network.

## Minimal reproduction of the problem with instructions
This is what I think happened:
I upgraded versions of Angular using the ng update tool. My old service worker config used to cache:
```
        "/*.bundle.css",
        "/*.bundle.js",
        "/*.chunk.js",
```
but, the naming scheme changes to
```
        "/runtime.*.js",
        "/polyfills.*.js",
        "/main.*.js",
        "/styles.*.css"
```
but, the upgrade tool did not update ngsw-config.

Then I released a new version of the app: it didn't cache the JS and CSS assets because the naming convention changed. It did cache the index.html file. So, the page was cached, but not the assets on it.

Then, I released another version of the site, and the old version was removed from the server. The old page that was cached by the server could not load the scripts and css resulting in a blank page.

Then, I set it up, so that /ngsw.json results in a 404. But, my server returns an HTML error page with that. The service worker script throws an error because of the HTML MIME type and doesn't get to the part where the 404 triggers a script deletion.

## What is the motivation / use case for changing the behavior?
Making service worker safe to use

## Environment

<pre><code>
Angular version: 6.0.3

Browser:
- [X] Chrome (desktop) version 67
- [X] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 10.0.0
- Platform:  Mac
Others:

</code></pre>

**Comment by gkalpak** [comment] 2018-07-10 22:41
AFAICT, you are reporting the following issues:
1. `ng update` not updating the SW config.
2. The new SW not unregistering when `ngsw.json` returns a 404.

Is that right?

##
The first issue is cli-related and should be re-opened in https://github.com/angular/angular-cli/issues.

Regarding the second issue, the SW should indeed unregister on 404 without caring about the mime type or content. By looking [at the code][1], this should already work as expected. If you are seeing something different, we need a minimal reproduction in order to investigate this further.

[1]: https://github.com/angular/angular/blob/03616bcb430c027cf64120182be13ec3dc4dce15/packages/service-worker/worker/src/driver.ts#L648-L651

**Comment by CDDelta** [comment] 2018-07-11 10:16
@adamzr seems like the correct configuration for `ngsw-config.json` in v6 is [this](https://github.com/angular/devkit/commit/fb78b20b5b5d46795f31b03ce3c02ed25432bee6#diff-dba244caa12fc352f91127ba5efc49e4).

**Comment by adamzr** [comment] 2018-07-12 23:33
@gkalpak I think if the return type is HTML it blows up before it gets to checking for the 404. It's a hard thing for me to build a reproducible test for, because I'd have to create 2 states, one where the app installs a service worker, then another where it gives an HTML 404. Not sure how to do that.

I also had other suggestions that I was making:

1. Any failure to get ngsw.json should result in the SW being deleted, for example:
	- An invalid JSON file with a 200
    - An HTML doc with a 200
    - A JSON file with a 500
2. A failure to load angular should cause the SW to delete itself.

I created a CLI bug, per your request: https://github.com/angular/angular-cli/issues/11535

Thank you!

**Comment by gkalpak** [comment] 2018-07-13 11:19
> I think if the return type is HTML it blows up before it gets to checking for the 404

I don't see anything that would cause it to break before checking for 404.

> It's a hard thing for me to build a reproducible test for

You don't have to write a test. Just the code and steps to reproduce this. 

> Any failure to get ngsw.json should result in the SW being deleted

That doesn't sound like a good idea. There are cases where the response may be invalid (e.g. no network, flakey network, temporary server error, etc). Yet, if invalid content is served (e.g. not JSON), the ServiceWorker will enter a "safe mode", where it will not accept new clients.
The current behavior is by design.

> A failure to load angular should cause the SW to delete itself.

I don't see how that is related (or even how to detect that from the SW) :confused:
If the idea is that the app may have changed or removed, so that trying to load the JS scripts fails, then `ngsw.json` would 404 too, causing the SW to unregister itself.

**Comment by playground** [comment] 2018-07-17 15:07
Is there a way not to deleteallcache and unregister itself when server is down or with 404?  So the app can continue to work offline until the server comes backup.

**Comment by gkalpak** [comment] 2018-07-17 15:35
Nothing happens when the server is simply down. But returning a response with a 404 message for `ngsw.json` will unregister the SW (and delete the caches) and there is not waay to prevent that (it is by design).

**Comment by playground** [comment] 2018-07-18 14:39
For our use case, we need to app to continue to function even when server is down, since all assets are already in cache.  Only fetch the latest when server/network is backup.

**Comment by gkalpak** [comment] 2018-07-18 16:21
As I said before, when the server is down, the app works as expected. It's only when the server returns a 404 (which doesn;t happen when it is down) that the SW gets unregistered.

**Comment by gkalpak** [comment] 2018-08-23 13:41
@kwilliams-curago, if your setup does not support 404ing on specific URLs, you can easily serve a SW script that will unregister the SW (as described [here][1]).

Closing this since there is no reproduction for the originally reported issue and it works as expected afaict.

[1]: https://angular.io/guide/service-worker-devops#service-worker-safety

**Closed by gkalpak** 2018-08-23 13:41 UTC
Labels: comp: service-worker, state: Need repro, type: bug/fix

**Comment by kwilliams-curago** [comment] 2018-08-23 14:53
@gkalpak,

Thanks for your prompt response. 

In this scenario it is impossible to use ngsw-worker here as it leads to corrupt cache. 

When the worker tries to refresh the manifest and receives a 200 text/html, it fails trying to parse the html as JSON. The fetchLatestManifest implementation should be able to fail more gracefully. At least it can be wrapped it in a try catch...

https://github.com/angular/angular/blob/master/packages/service-worker/worker/src/driver.ts#L645-L659

The safety worker is not the right solution here, as the manifest must be invalidated on every deploy. This means we cannot use the service worker in CloudFront with PathLocationStrategy.

"Instead, you must serve the contents of safety-worker.js at the URL of the Service Worker script you are trying to unregister, and must continue to do so until you are certain all users have successfully unregistered the old worker. For most sites, this means that you should serve the safety worker at the old Service Worker URL forever."

**Comment by kwilliams-curago** [comment] 2018-08-24 16:37
Sure, I'm interested. I'll see if I can tackle it this weekend.

> Not sure what you mean by that 😕

Yeah, sorry I realize that statement was a little confusing. I ended up with a few clients that had corrupt cache after a deploy. My guess is that this occurred when trying to fetch an old bundle.js (cached index.html) and receiving a 200 text/html. 

I will try to reproduce this to be sure.
