### ISSUE TITLE
Build causes:   Cannot read property 'text' of undefined

### ISSUE THREAD

**Issue by scottwalter-nice** [angular/angular#44018] opened 2021-11-02 15:59 UTC
### Which @angular/* package(s) are the source of the bug?

compiler-cli

### Is this a regression?

Yes

### Description

Using 12.2.12 when I build with:  node --max_old_space_size=8048 ./node_modules/@angular/cli/bin/ng build I get the error:  

Compiling with Angular sources in Ivy partial compilation mode.TypeError: Cannot read property 'text' of undefined

If I back down to 12.2.8 the issue goes away.  Something has happened between 12.2.8 and 12.2.12

### Please provide the exception or error you saw

```true
When I run a build of a library I get:  

Compiling with Angular sources in Ivy partial compilation mode.TypeError: Cannot read property 'text' of undefined

⠋ Compiling with Angular sources in Ivy partial compilation mode.TypeError: Cannot read property 'text' of undefined
    at NodeObject.getText (/Users/scott/cxone/components/cxone-angular-domain-ui/node_modules/typescript/lib/typescript.js:152697:31)
    at getRequiredModulePath (/Users/scott/cxone/components/cxone-angular-domain-ui/node_modules/@angular/compiler-cli/ngcc/src/host/umd_host.js:519:99)
    at Object.getImportsOfUmdModule (/Users/scott/cxone/components/cxone-angular-domain-ui/node_modules/@angular/compiler-cli/ngcc/src/host/umd_host.js:510:23)
    at UmdDependencyHost.extractImports (/Users/scott/cxone/components/cxone-angular-domain-ui/node_modules/@angular/compiler-cli/ngcc/src/dependencies/umd_dependency_host.js:43:54)
    at UmdDependencyHost.DependencyHostBase.recursivelyCollectDependencies (/Users/scott/cxone/components/cxone-angular-domain-ui/node_modules/@angular/compiler-cli/ngcc/src/dependencies/dependency_host.js:85:32)
    at UmdDependencyHost.DependencyHostBase.collectDependencies (/Users/scott/cxone/components/cxone-angular-domain-ui/node_modules/@angular/compiler-cli/ngcc/src/dependencies/dependency_host.js:38:22)
    at DependencyResolver.getEntryPointWithDependencies (/Users/scott/cxone/components/cxone-angular-domain-ui/node_modules/@angular/compiler-cli/ngcc/src/dependencies/dependency_resolver.js:75:22)
    at EntryPointCollector.walkDirectoryForPackages (/Users/scott/cxone/components/cxone-angular-domain-ui/node_modules/@angular/compiler-cli/ngcc/src/entry_point_finder/entry_point_collector.js:47:52)
    at EntryPointCollector.walkDirectoryForPackages (/Users/scott/cxone/components/cxone-angular-domain-ui/node_modules/@angular/compiler-cli/ngcc/src/entry_point_finder/entry_point_collector.js:75:103)
    at /Users/scott/cxone/components/cxone-angular-domain-ui/node_modules/@angular/compiler-cli/ngcc/src/entry_point_finder/program_based_entry_point_finder.js:124:100
✖ Compiling with Angular sources in Ivy partial compilation mode.
NGCC failed.
```

### Please provide the environment you discovered this bug in

```true
Angular CLI: 12.2.12
Node: 14.17.0
Package Manager: npm 7.24.0
OS: darwin x64

Angular: 12.2.12
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, localize, material
... platform-browser, platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1202.12
@angular-devkit/build-angular      12.2.12
@angular-devkit/build-ng-packagr   0.1002.0
@angular-devkit/core               12.2.12
@angular-devkit/schematics         12.2.12
@schematics/angular                12.2.12
ng-packagr                         12.2.5
rxjs                               6.6.7
typescript                         4.3.5
```

**Comment by alan-agius4** [comment] 2021-11-02 16:24
Duplicate of https://github.com/angular/angular/issues/44019

Closing in favor of the above since it has a reproduction.

**Closed by alan-agius4** 2021-11-02 16:24 UTC
Labels: comp: ngcc
