### ISSUE TITLE
Provide type for FormControl "status" property

### ISSUE THREAD

**Issue by krzysztof-grzybek** [angular/angular#27710] opened 2018-12-17 16:36 UTC
# 🚀 feature request

### Relevant Package
This feature request is for @angular/forms

### Description
This request is about ["status" property](https://angular.io/api/forms/AbstractControl#status) of FormControl. I would like it to be more strongly typed, like` 'VALID' | 'INVALID' | 'DISABLED'` instead of just `string`.

Though it won't make huge difference, it would throw errors in case of simple typos like:
`if (formControl.status === 'INVALD')`

### Describe the solution you'd like
Add `type formControlStatus = 'VALID' | 'INVALID' | 'PENDING' | 'DISABLED';`
and assign it to status property.

**Comment by pkozlowski-opensource** [comment] 2018-12-17 19:38
I believe that this is a duplicate of #27389

**Closed by pkozlowski-opensource** 2018-12-17 19:38 UTC
Labels: comp: forms
