### ISSUE TITLE
[BUG] ApplicationRef.attachView cause error while dynamic creating component which contains structural directives

### ISSUE THREAD

**Issue by wilsoncook** [angular/angular#20515] opened 2017-11-18 04:15 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

If using `ApplicationRef.attachView` creating component dynamically in a app contains hierarchical structural directives like `ngIf`, `ngFor`, cause `ExpressionChangedAfterItHasBeenCheckedError` error in development mode:
![image](https://user-images.githubusercontent.com/1631659/32976647-581ef988-cc56-11e7-8725-0720b0446526.png)

## Expected behavior

Should not throw errors in any complex environment

## Minimal reproduction of the problem with instructions

http://plnkr.co/edit/o0PiGJv0vns1RghlRnMe?p=preview

This issue was found by using `Overlay` service from package `angular/cdk`, it indicate that every app depend on `angular/cdk/Overlay` may cause this problem:
```js
overlay
  .create()
  .attach(new ComponentPortal(XX)); // <--- Here "attach" will do "ApplicationRef.attachView"
```

## Environment

<pre><code>
Angular version: 5.0.2

Browser:
- [x] Chrome (desktop) version 62.0.3202.94 (Official Build) (64-bit)
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Platform: Mac  

Others:

</code></pre>

**Comment by goldsam** [comment] 2018-01-31 14:55
I'm also experiencing this issue for a service that dynamically introduces overlay content.

**Comment by korolariya** [comment] 2018-03-29 14:40
I'm also experiencing this issue for a service that dynamically introduces overlay content.

**Comment by lvovgeka** [comment] 2018-03-29 14:40
I'm also experiencing this issue for a service that dynamically introduces overlay content.

**Comment by paulogr** [comment] 2019-01-23 17:14
Any workaround for this issue?

**Comment by pkozlowski-opensource** [comment] 2019-03-05 14:06
I believe that this is the same issue as #15634

**Comment by pkozlowski-opensource** [comment] 2020-03-12 20:23
Duplicate of #15634

**Closed by pkozlowski-opensource** 2020-03-12 20:23 UTC
Labels: comp: core, freq1: low, severity3: broken, type: bug/fix
