### ISSUE TITLE
Failure trying to load docs

### ISSUE THREAD

**Issue by rictic** [angular/angular#42860] opened 2021-07-14 22:31 UTC
Repro steps:

1. Go to https://angular.io/docs
2. Select another page, like Understanding -> Components -> Overview

Note that the page never loads, the loading progress bar animates forever, and the following is in the console logs:

<details>
  <summary>Console error logs</summary>

```
polyfills-es2015.1a4c72da9816597260d1.js:1 A preload for 'https://angular.io/generated/navigation.json' is found, but is not used because the request headers do not match.
g @ polyfills-es2015.1a4c72da9816597260d1.js:1
docs:1 The resource https://angular.io/generated/docs/index.json was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
docs:1 The resource https://angular.io/generated/navigation.json was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
toc-toc-module-es2015.d1fa63cbc4f8ec0088ea.js:1 Failed to load resource: the server responded with a status of 404 ()
main-es2015.5bdd22efd2bd48dd1d9e.js:1 ERROR Error: [DocViewer] Error preparing document 'guide/component-overview': ChunkLoadError: Loading chunk 16 failed.
(error: https://angular.io/toc-toc-module-es2015.d1fa63cbc4f8ec0088ea.js)
    at Function.c.e (runtime-es2015.079cdaf7df823193c268.js:1)
    at loadChildren (main-es2015.5bdd22efd2bd48dd1d9e.js:1)
    at t.loadCustomElement (main-es2015.5bdd22efd2bd48dd1d9e.js:1)
    at main-es2015.5bdd22efd2bd48dd1d9e.js:1
    at Array.map (<anonymous>)
    at t.loadContainedCustomElements (main-es2015.5bdd22efd2bd48dd1d9e.js:1)
    at u.project (main-es2015.5bdd22efd2bd48dd1d9e.js:1)
    at u._next (main-es2015.5bdd22efd2bd48dd1d9e.js:1)
    at u.next (main-es2015.5bdd22efd2bd48dd1d9e.js:1)
    at c._next (main-es2015.5bdd22efd2bd48dd1d9e.js:1)
    at c.selector (main-es2015.5bdd22efd2bd48dd1d9e.js:1)
    at c.error (main-es2015.5bdd22efd2bd48dd1d9e.js:1)
    at c._error (main-es2015.5bdd22efd2bd48dd1d9e.js:1)
    at c.error (main-es2015.5bdd22efd2bd48dd1d9e.js:1)
    at u._error (main-es2015.5bdd22efd2bd48dd1d9e.js:1)
    at u.error (main-es2015.5bdd22efd2bd48dd1d9e.js:1)
    at c._error (main-es2015.5bdd22efd2bd48dd1d9e.js:1)
    at c.error (main-es2015.5bdd22efd2bd48dd1d9e.js:1)
    at u.notifyError (main-es2015.5bdd22efd2bd48dd1d9e.js:1)
    at r._error (main-es2015.5bdd22efd2bd48dd1d9e.js:1)
vs @ main-es2015.5bdd22efd2bd48dd1d9e.js:1
main-es2015.5bdd22efd2bd48dd1d9e.js:1 
ServiceWorker: activated
default~code-code-example-module~code-code-tabs-module-es2015.48e4e1c9f1670b9cec23.js:1 Failed to load resource: the server responded with a status of 404 ()
code-code-example-module-es2015.af6b398dde18d5f1d877.js:1 Failed to load resource: the server responded with a status of 404 ()
live-example-live-example-module-es2015.e26ac21b0f5aff3a4dc7.js:1 Failed to load resource: the server responded with a status of 404 ()
main-es2015.5bdd22efd2bd48dd1d9e.js:1 
Cache: ngsw:/:db:control (2 entries)
  - https://angular.io/assignments: {}
  - https://angular.io/latest: {"latest":"9fbce88f108db5f4e9baafc36552245dce56e052"}
main-es2015.5bdd22efd2bd48dd1d9e.js:1 
Cache: ngsw:/:9fbce88f108db5f4e9baafc36552245dce56e052:assets:app-shell:cache (27 entries)
  - https://angular.io/0-es2015.1bf0c2776281d14071b6.worker.js
  - https://angular.io/announcement-bar-announcement-bar-module-es2015.1b5b762c9c8837c770f8.js
  - https://angular.io/api-api-list-module-es2015.40a43cd22f50f64d63bb.js
  - https://angular.io/assets-js-prettify-js-es2015.b6cbad02a0e3ac8af12a.js
  - https://angular.io/assets/images/favicons/favicon.ico
  - https://angular.io/assets/js/prettify.js
  - https://angular.io/code-code-example-module-es2015.af6b398dde18d5f1d877.js
  - https://angular.io/code-code-tabs-module-es2015.1a6c55229832dae43d3d.js
  - https://angular.io/contributor-contributor-list-module-es2015.c8325875e1dc65af0dc6.js
  - https://angular.io/default~code-code-example-module~code-code-tabs-module-es2015.48e4e1c9f1670b9cec23.js
  - https://angular.io/events-events-module-es2015.6447f4bc09fdcfbb5676.js
  - https://angular.io/index.html
  - https://angular.io/live-example-live-example-module-es2015.e26ac21b0f5aff3a4dc7.js
  - https://angular.io/main-es2015.5bdd22efd2bd48dd1d9e.js
  - https://angular.io/polyfills-es2015.1a4c72da9816597260d1.js
  - https://angular.io/pwa-manifest.json
  - https://angular.io/resource-resource-list-module-es2015.c10f93cd4e05eaabbcfd.js
  - https://angular.io/runtime-es2015.079cdaf7df823193c268.js
  - https://angular.io/search-file-not-found-search-module-es2015.5f87faadeb778e77ea33.js
  - https://angular.io/styles.6949abf903d5ee1d9240.css
  - https://angular.io/toc-toc-module-es2015.d1fa63cbc4f8ec0088ea.js
  - https://fonts.gstatic.com/s/roboto/v27/KFOmCnqEu92Fr1Mu4mxKKTU1Kg.woff2
  - https://fonts.gstatic.com/s/roboto/v27/KFOlCnqEu92Fr1MmEU9fBBc4AMP6lQ.woff2
  - https://fonts.gstatic.com/s/roboto/v27/KFOlCnqEu92Fr1MmSU5fBBc4AMP6lQ.woff2
  - https://fonts.gstatic.com/s/roboto/v27/KFOmCnqEu92Fr1Me5g.woff
  - https://fonts.gstatic.com/s/materialicons/v85/flUhRq6tzZclQEJ-Vdg-IuiaDsNcIhQ8tQ.woff2
  - https://fonts.gstatic.com/s/materialicons/v85/flUhRq6tzZclQEJ-Vdg-IuiaDsNa.woff
main-es2015.5bdd22efd2bd48dd1d9e.js:1 
Cache: ngsw:/:db:ngsw:/:9fbce88f108db5f4e9baafc36552245dce56e052:assets:app-shell:meta (6 entries)
  - https://angular.io/https://fonts.gstatic.com/s/roboto/v27/KFOmCnqEu92Fr1Mu4mxKKTU1Kg.woff2: {"ts":1626301379462,"used":true}
  - https://angular.io/https://fonts.gstatic.com/s/roboto/v27/KFOlCnqEu92Fr1MmEU9fBBc4AMP6lQ.woff2: {"ts":1626301379463,"used":true}
  - https://angular.io/https://fonts.gstatic.com/s/roboto/v27/KFOlCnqEu92Fr1MmSU5fBBc4AMP6lQ.woff2: {"ts":1626301379468,"used":true}
  - https://angular.io/https://fonts.gstatic.com/s/roboto/v27/KFOmCnqEu92Fr1Me5g.woff: {"ts":1626301379501,"used":true}
  - https://angular.io/https://fonts.gstatic.com/s/materialicons/v85/flUhRq6tzZclQEJ-Vdg-IuiaDsNcIhQ8tQ.woff2: {"ts":1626301379650,"used":true}
  - https://angular.io/https://fonts.gstatic.com/s/materialicons/v85/flUhRq6tzZclQEJ-Vdg-IuiaDsNa.woff: {"ts":1626301379837,"used":true}
main-es2015.5bdd22efd2bd48dd1d9e.js:1 
If you see this error, please report an issue at https://github.com/angular/angular/issues/new?template=3-docs-bug.md including the above logs.
(anonymous) @ main-es2015.5bdd22efd2bd48dd1d9e.js:1
styles.6949abf903d5ee1d9240.css:1 Failed to load resource: the server responded with a status of 404 ()
toc-toc-module-es2015.d1fa63cbc4f8ec0088ea.js:1 Failed to load resource: the server responded with a status of 404 ()
main-es2015.5bdd22efd2bd48dd1d9e.js:1 ERROR Error: [DocViewer] Error preparing document 'guide/component-overview': ChunkLoadError: Loading chunk 16 failed.
(error: https://angular.io/toc-toc-module-es2015.d1fa63cbc4f8ec0088ea.js)
    at Function.c.e (runtime-es2015.079cdaf7df823193c268.js:1)
    at loadChildren (main-es2015.5bdd22efd2bd48dd1d9e.js:1)
    at t.loadCustomElement (main-es2015.5bdd22efd2bd48dd1d9e.js:1)
    at main-es2015.5bdd22efd2bd48dd1d9e.js:1
    at Array.map (<anonymous>)
    at t.loadContainedCustomElements (main-es2015.5bdd22efd2bd48dd1d9e.js:1)
    at u.project (main-es2015.5bdd22efd2bd48dd1d9e.js:1)
    at u._next (main-es2015.5bdd22efd2bd48dd1d9e.js:1)
    at u.next (main-es2015.5bdd22efd2bd48dd1d9e.js:1)
    at c._next (main-es2015.5bdd22efd2bd48dd1d9e.js:1)
    at c.selector (main-es2015.5bdd22efd2bd48dd1d9e.js:1)
    at c.error (main-es2015.5bdd22efd2bd48dd1d9e.js:1)
    at c._error (main-es2015.5bdd22efd2bd48dd1d9e.js:1)
    at c.error (main-es2015.5bdd22efd2bd48dd1d9e.js:1)
    at u._error (main-es2015.5bdd22efd2bd48dd1d9e.js:1)
    at u.error (main-es2015.5bdd22efd2bd48dd1d9e.js:1)
    at c._error (main-es2015.5bdd22efd2bd48dd1d9e.js:1)
    at c.error (main-es2015.5bdd22efd2bd48dd1d9e.js:1)
    at u.notifyError (main-es2015.5bdd22efd2bd48dd1d9e.js:1)
    at r._error (main-es2015.5bdd22efd2bd48dd1d9e.js:1)
vs @ main-es2015.5bdd22efd2bd48dd1d9e.js:1
main-es2015.5bdd22efd2bd48dd1d9e.js:1 
ServiceWorker: activated
default~code-code-example-module~code-code-tabs-module-es2015.48e4e1c9f1670b9cec23.js:1 Failed to load resource: the server responded with a status of 404 ()
code-code-example-module-es2015.af6b398dde18d5f1d877.js:1 Failed to load resource: the server responded with a status of 404 ()
live-example-live-example-module-es2015.e26ac21b0f5aff3a4dc7.js:1 Failed to load resource: the server responded with a status of 404 ()
main-es2015.5bdd22efd2bd48dd1d9e.js:1 
Cache: ngsw:/:db:control (2 entries)
  - https://angular.io/assignments: {"5ed264c6-0687-4d00-940b-0cb816a04f28":"e49a6d5e888cee588439ccbcd6a8fd60b782583d"}
  - https://angular.io/latest: {"latest":"e49a6d5e888cee588439ccbcd6a8fd60b782583d"}
main-es2015.5bdd22efd2bd48dd1d9e.js:1 
Cache: ngsw:/:e49a6d5e888cee588439ccbcd6a8fd60b782583d:assets:app-shell:cache (29 entries)
  - https://angular.io/assets/js/prettify.js
  - https://angular.io/dark-theme.css
  - https://angular.io/default-src_app_custom-elements_code_code_component_ts-src_app_custom-elements_code_code_module_ts-es2017.f8d6a0e27e1efde90171.js
  - https://angular.io/index.html
  - https://angular.io/light-theme.css
  - https://angular.io/main-es2017.064fdbebecd04e74f2d3.js
  - https://angular.io/polyfills-es2017.ec610927a82f0b11de83.js
  - https://angular.io/pwa-manifest.json
  - https://angular.io/runtime-es2017.e1f1f8a6950eeca1b3f8.js
  - https://angular.io/src_app_custom-elements_announcement-bar_announcement-bar_module_ts-es2017.4d0dad54e060dae26d21.js
  - https://angular.io/src_app_custom-elements_api_api-list_module_ts-es2017.f980eff8e5d859e829ce.js
  - https://angular.io/src_app_custom-elements_code_code-example_module_ts-es2017.fc92f848d8efa6b8481e.js
  - https://angular.io/src_app_custom-elements_code_code-tabs_module_ts-es2017.6181d8f8b607ca997edf.js
  - https://angular.io/src_app_custom-elements_contributor_contributor-list_module_ts-es2017.f9a6dbaa296700915c9f.js
  - https://angular.io/src_app_custom-elements_dist-tag_dist-tag_module_ts-es2017.ecaa4c3047d129b5d0b6.js
  - https://angular.io/src_app_custom-elements_events_events_module_ts-es2017.2aa58cf2659d268d57e0.js
  - https://angular.io/src_app_custom-elements_live-example_live-example_module_ts-es2017.7313f8c723013bdc9802.js
  - https://angular.io/src_app_custom-elements_resource_resource-list_module_ts-es2017.94ce3bc2162c582f1f27.js
  - https://angular.io/src_app_custom-elements_search_file-not-found-search_module_ts-es2017.82809ed3de0ed032f0b2.js
  - https://angular.io/src_app_custom-elements_toc_toc_module_ts-es2017.8127f651955c74bcb804.js
  - https://angular.io/src_app_search_search_worker_ts-es2017.7e4dcae7b756ff2adfb5.js
  - https://angular.io/src_assets_js_prettify_js-es2017.b2902fbe410f66d3c420.js
  - https://angular.io/styles.512fa4bf72a6a91dd197.css
  - https://fonts.gstatic.com/s/roboto/v27/KFOmCnqEu92Fr1Mu4mxKKTU1Kg.woff2
  - https://fonts.gstatic.com/s/roboto/v27/KFOlCnqEu92Fr1MmEU9fBBc4AMP6lQ.woff2
  - https://fonts.gstatic.com/s/roboto/v27/KFOlCnqEu92Fr1MmSU5fBBc4AMP6lQ.woff2
  - https://fonts.gstatic.com/s/roboto/v27/KFOmCnqEu92Fr1Me5g.woff
  - https://fonts.gstatic.com/s/materialicons/v85/flUhRq6tzZclQEJ-Vdg-IuiaDsNcIhQ8tQ.woff2
  - https://fonts.gstatic.com/s/materialicons/v85/flUhRq6tzZclQEJ-Vdg-IuiaDsNa.woff
main-es2015.5bdd22efd2bd48dd1d9e.js:1 
Cache: ngsw:/:db:e49a6d5e888cee588439ccbcd6a8fd60b782583d:assets:app-shell:meta (0 entries)

main-es2015.5bdd22efd2bd48dd1d9e.js:1 
If you see this error, please report an issue at https://github.com/angular/angular/issues/new?template=3-docs-bug.md including the above logs.
```

</details>

Reloading and retrying didn't fix, but unregistering the service worker and reloading did.

**Comment by petebacondarwin** [comment] 2021-07-15 11:14
Duplicate of https://github.com/angular/angular/issues/28114 I believe.

**Comment by gkalpak** [comment] 2021-07-15 13:00
Yes, this is indeed an occurrence of #28114. Thx for sharing this info, @rictic.
(FYI, I have also copied the logs in https://github.com/angular/angular/issues/41117#issuecomment-880647993, since that is were we keep track of all reported occurrences.)

Based on the logged info, the activated SW was from before #42776, which includes some SW fixes and more debug info. But that's actually a good thing, because it means that there is still hope that #42776 will fix/improve things (esp. due to #42607) :smiley:

##
One interesting thing I noticed in the logs is that the debug info is logged twice (i.e. it looks like these logs are from two separate navigations, both for `/guide/component-overview`). Do you have the `Preserve log` option enabled in the DevTools Console? Did you manually navigate twice (for example hit `Reload`)?

Also, what browser/version did this happen on?

**Comment by gkalpak** [comment] 2021-07-21 18:51
I am going to close this due to lack of response (although I would very much like to know the answers to the above question).
As mentioned above, the underlying issue is being tracked in #28114 and #41117.

**Closed by gkalpak** 2021-07-21 18:51 UTC
Labels: comp: docs-infra
