### ISSUE TITLE
Maximum call stack size exceeded with angular 12 

### ISSUE THREAD

**Issue by vittal288** [angular/angular#47428] opened 2022-09-14 07:04 UTC
### Which @angular/* package(s) are the source of the bug?

compiler

### Is this a regression?

Yes

### Description

![image](https://user-images.githubusercontent.com/3775684/190084212-f5cc5de4-cfb0-41f3-9bbf-a942d2e36f33.png)
![image](https://user-images.githubusercontent.com/3775684/190084308-1378f823-09d3-4fab-8be9-fd88649e4334.png)

the same code base working fine with angular 8 but once migrate from angular 12, we are seeing this error.

**Comment by JoostK** [comment] 2022-09-14 07:55
Without a reproduction this won't be actionable for us, unfortunately.

**Comment by JoostK** [comment] 2022-09-14 09:14
This is likely a duplicate of #25226/#32555, an issue with the old ViewEngine compiler. Angular 12 supports compiling libraries with Ivy partial compilation, and [the migration guide for adopting Ivy is here](https://v12.angular.io/guide/creating-libraries#ivy-libraries).

**Comment by vittal288** [comment] 2022-09-14 09:18
> Without a reproduction this won't be actionable for us, unfortunately.

How can I help you or what data do you need to reproduce the issue? Could you please mention

**Comment by JoostK** [comment] 2022-09-14 09:38
> > Without a reproduction this won't be actionable for us, unfortunately.
> 
> How can I help you or what data do you need to reproduce the issue? Could you please mention

A Github repo with a runnable reproduction. But as mentioned in https://github.com/angular/angular/issues/47428#issuecomment-1246475324 this is likely an issue in the ViewEngine compiler and I'd suggest that you migrate to building libraries using Ivy instead. Angular 13+ no longer supports ViewEngine compilation meaning that this particular issue is no longer present in latest Angular, hence the suggestion to migrate to Ivy.

**Comment by vittal288** [comment] 2022-09-14 09:46
> > > Without a reproduction this won't be actionable for us, unfortunately.
> > 
> > 
> > How can I help you or what data do you need to reproduce the issue? Could you please mention
> 
> A Github repo with a runnable reproduction. But as mentioned in [#47428 (comment)](https://github.com/angular/angular/issues/47428#issuecomment-1246475324) this is likely an issue in the ViewEngine compiler and I'd suggest that you migrate to building libraries using Ivy instead. Angular 13+ no longer supports ViewEngine compilation meaning that this particular issue is no longer present in latest Angular, hence the suggestion to migrate to Ivy.

I have made the changes as above suggested as like 
  "angularCompilerOptions": {
     "enableIvy": false,
     "strictTemplates" : false
  } 
in tsconfig.json file but still same issue

**Comment by JoostK** [comment] 2022-09-14 10:04
That's not what is suggested [in the migration guide](https://v12.angular.io/guide/creating-libraries#ivy-libraries).

**Comment by jessicajaniuk** [comment] 2022-09-19 17:19
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular version.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.

**Closed by jessicajaniuk** 2022-09-19 17:19 UTC
Labels: needs reproduction, comp: compiler

**Comment by vittal288** [comment] 2022-09-26 16:19
> That's not what is suggested [in the migration guide](https://v12.angular.io/guide/creating-libraries#ivy-libraries).

I did not get the solution to fix this issue, could you please share the proper link to fix the issue?
