### ISSUE TITLE
 Contributing: Bazel test execution fails

### ISSUE THREAD

**Issue by s-gbz** [angular/angular#30252] opened 2019-05-03 11:45 UTC
# 🐞 bug report

### Affected Package
Build tool related.

### Is this a regression?
I don't know.

### Description
I'm writing a test in order to fix #29099. Unfortunately building and testing Angular fails because 
"powershell.exe could not be found."

## 🔬 Minimal Reproduction
`yarn bazel test packages/core/test:test_web --verbose_failures`

## 🔥 Exception or Error

<pre><code>
C:\Users\grilborzer\Code\angular>yarn bazel test packages/core/test:test_web --verbose_failures
yarn run v1.14.0
$ bazel test packages/core/test:test_web --verbose_failures
DEBUG: C:/users/grilborzer/_bazel_grilborzer/5h5bt24p/external/bazel_skylib/skylark_library.bzl:1:1: WARNING: skylark_library.bzl is deprecated and will go away in the future, please use bzl_library.bzl instead.
INFO: Analysed target //packages/core/test:test_web_chromium-local (1 packages loaded, 1 target configured).
INFO: Found 1 test target...
ERROR: C:/users/grilborzer/_bazel_grilborzer/5h5bt24p/external/io_bazel_rules_webtesting/third_party/chromedriver/BUILD.bazel:28:1: Extracting ../org_chromium_chromedriver/file/chromedriver_win32.zip failed (Exit 1): extract.bat failed: error executing command
  cd C:/users/grilborzer/_bazel_grilborzer/5h5bt24p/execroot/angular
  SET PATH=C:\WINDOWS\system32
  external/io_bazel_rules_webtesting/web/internal/extract.bat external/org_chromium_chromedriver/file/chromedriver_win32.zip bazel-out/x64_windows-fastbuild/bin/external/io_bazel_rules_webtesting/third_party/chromedriver/chromedriver.out
Execution platform: @bazel_tools//platforms:host_platform
The "powershell.exe" command is either misspelled, or
could not be found.

C:\users\grilborzer\_bazel_grilborzer\5h5bt24p\execroot\angular>powershell.exe -NoP -NonI -Command "Expand-Archive 'external/org_chromium_chromedriver/file/chromedriver_win32.zip' 'bazel-out/x64_windows-fastbuild/bin/external/io_bazel_rules_webtesting/third_party/chromedriver/chromedriver.out'"
Target //packages/core/test:test_web_chromium-local failed to build
INFO: Elapsed time: 1.117s, Critical Path: 0.17s
INFO: 0 processes.
FAILED: Build did NOT complete successfully

FAILED: Build did NOT complete successfully
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
OS: Windows 10

PS C:\Users\grilborzer> Get-ExecutionPolicy -List

        Scope ExecutionPolicy
        ----- ---------------
MachinePolicy       Undefined
   UserPolicy       Undefined
      Process       Undefined
  CurrentUser       Undefined
 LocalMachine    Unrestricted
</code></pre>

**Anything else relevant?**

**Comment by kara** [comment] 2019-05-06 17:04
Looks like a duplicate of https://github.com/angular/angular/issues/29785 or https://github.com/angular/angular/issues/29760.

**Closed by kara** 2019-05-06 17:04 UTC
