### ISSUE TITLE
Can Activate Gaurd in a lazily loaded module creating new instance of a service on first load of lazy module

### ISSUE THREAD

**Issue by debapamdas** [angular/angular#14035] opened 2017-01-20 13:52 UTC
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

This is my lazily loaded module. It has AppContainerService in its provider and a Module11GaurdService for protecting a route to Module11Component, which is also lazily routed from Module1Component

import { NgModule } from '@angular/core';
import { RouterModule } from '@angular/router';
import { Module1Component } from './module1.component';
import { AppContainerService } from './module1.statecontainer';
import { module11GaurdService } from './module11/module11.gaurd';
const routes = RouterModule.forChild([
    {
        path: '',
        component: Module1Component,
        children: [{
            path: 'module11',
            loadChildren: 'app/module1/module11/module11.module#module11',
            canActivate: [module11GaurdService]
        }]
    }]);
@NgModule({
    imports: [routes],
    exports: [],
    declarations: [Module1Component],
    providers: [AppContainerService, module11GaurdService],
})
export class module1 { }

I am requesting a instance of AppContainerService in Module1Component' constructor.

import { Component, OnInit, Injector } from '@angular/core';
import { AppContainerService} from './module1.statecontainer';
@Component({
  selector: 'app-module1',
  templateUrl: './module1.component.html',
  styleUrls: ['./module1.component.css']
})
export class Module1Component implements OnInit {

  constructor(conatainer:AppContainerService) { 
  }

  ngOnInit() {
  }

}
This is my Module1Component's gaurd. Where also I am requesting an instance of AppContainerService in constructor

import { Injectable, Injector } from '@angular/core';
import { CanActivate, ActivatedRouteSnapshot, RouterStateSnapshot} from '@angular/router';
import { AppContainerService} from '../module1.statecontainer';
@Injectable()
export class module11GaurdService implements CanActivate{

    constructor(container: AppContainerService) { 
        //let x = injector.get(AppContainerService);
        debugger;
    }

    canActivate(route: ActivatedRouteSnapshot, state: RouterStateSnapshot):  boolean{
        return true;
    }

}

this is my Module11Component

import { Component, OnInit } from '@angular/core';
import { AppContainerService} from '../module1.statecontainer';

@Component({
  selector: 'app-module11',
  templateUrl: './module11.component.html',
  styleUrls: ['./module11.component.css']
})
export class Module11Component implements OnInit {

  constructor(private container:AppContainerService) { }

  ngOnInit() {
  }

}
**Current behavior**

When I am navigating to ~/module1 for **first time** an instance of AppContainer Service is created as expected for Module1Component. But when I am naviagting to ~/module1/module11 from Module1Component a new instance of AppContainerService is created for Module11GaurdService, which shouldnt be the case as AppContainerService instance is already created and injected within the child injector of Module1 and Module11GaurdService is also within Module1 Provider. So if I am updating anything in AppContainer in the gaurd it is not reflected in the AppContainer instance in Module11Component.

Same problem doesnt occur **after first time** navigation of module1 or module11.After subsequent navigation to module1 again  AppContainer Service is created in Module1Component and shared with Gaurd and Module11Component. On a different note Gaurd service is only created once for the first time routing, on subsequent navigation to module11 no new instances of gaurd is created.

**Please tell us about your environment:**
windows 7, VsCode1.8, node 7.3.0

* **Angular version:** 
angular2(2.4.4), angular-cli(beta26)

* **Browser:** [all ]

 
* **Language:** [TypeScript 2.0 ]

**Comment by dejour** [comment] 2017-01-20 13:59
pls add a plunkr

**Comment by DzmitryShylovich** [comment] 2017-01-20 14:20
It's duplicate of https://github.com/angular/angular/issues/12869

**Comment by dejour** [comment] 2017-01-20 14:28
@DzmitryShylovich how can you have so much time working on these issue. anyway, good work.

**Comment by debapamdas** [comment] 2017-01-21 04:36
thanks @DzmitryShylovich closing this as a duplicate.

**Closed** 2017-01-21 04:37 UTC
