### ISSUE TITLE
Angular 8.1.0 ResumableJS stop working

### ISSUE THREAD

**Issue by digoburigo** [angular/angular#31393] opened 2019-07-02 22:54 UTC
# 🐞 bug report

### Affected Package
http://www.resumablejs.com/
ResumableJS

### Is this a regression?
Yes, the previous version in which this bug was not present was 8.0.6

### Description
I have a installaed ResumableJS by importing this way in the angular.json
<pre><code>"node_modules/resumablejs/resumable.js"</code></pre>
and using this way on the component
<pre><code>declare const Resumable;</code></pre>
In the version 8.0.6 was working with no problems but when i upgraded to 8.1.0 using the Angular CLI this library stopped working.
## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-wgkkgq

## 🔥 Exception or Error
<pre><code>
ERROR ReferenceError: Resumable is not defined
    at ImportDialogComponent.ngOnInit (import-dialog.component.ts:261)
    at checkAndUpdateDirectiveInline (core.js:27776)
    at checkAndUpdateNodeInline (core.js:38466)
    at checkAndUpdateNode (core.js:38405)
    at debugCheckAndUpdateNode (core.js:39427)
    at debugCheckDirectivesFn (core.js:39370)
    at Object.eval [as updateDirectives] (ImportDialogComponent_Host.ngfactory.js? [sm]:1)
    at Object.debugUpdateDirectives [as updateDirectives] (core.js:39358)
    at checkAndUpdateView (core.js:38370)
    at callViewAction (core.js:38736)
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.1.0
Node: 10.15.1
OS: linux x64
Angular: 8.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.801.0
@angular-devkit/build-angular     0.801.0
@angular-devkit/build-optimizer   0.801.0
@angular-devkit/build-webpack     0.801.0
@angular-devkit/core              8.1.0
@angular-devkit/schematics        8.1.0
@angular/cdk                      8.0.2
@angular/flex-layout              8.0.0-beta.26
@angular/material                 8.0.2
@ngtools/webpack                  8.1.0
@schematics/angular               8.1.0
@schematics/update                0.801.0
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.35.2
</code></pre>

**Comment by coronabytes** [comment] 2019-07-03 12:34
8.1 renders "most" scripts in the angular.json script section non functional.
For us that includes moment.js and popper.js

**Comment by devbean** [comment] 2019-07-04 00:39
popper.js failed for us. In 7.x it works well.

**Comment by crumhorn** [comment] 2019-07-04 06:42
A lot of packages where we include them in angular.json stopped working for us too in 8.1.0, we had to revert back to 8.0.3 (es2015 in tsconfig.json)

**Comment by alan-agius4** [comment] 2019-07-08 17:04
Duplicate of https://github.com/angular/angular-cli/issues/14952

**Closed by alan-agius4** 2019-07-08 17:04 UTC
Labels: comp: core
