### ISSUE TITLE
[ivy] lazy loaded modules can not be found / imported

### ISSUE THREAD

**Issue by khaledosman** [angular/angular#28866] opened 2019-02-20 14:38 UTC
# 🐞 bug report

### Affected Package
Not sure

### Is this a regression?
Yes, the previous version in which this bug was not present was: 7.2.5

### Description
Running the project with lazily loaded routes/modules creates a runtime error 
<pre><code>
core.js:5253 ERROR Error: Uncaught (in promise): Error: Cannot find module './x/x.module.ngfactory'
Error: Cannot find module './x/x.module.ngfactory'
</code></pre>

The routes/paths are setup correctly as downgrading to 7.2.5 and removing `ivy-ngcc` from the postinstall script fixes the issue

## 🔬 Minimal Reproduction
https://github.com/khaledosman/advanced-angular-features-demo
1. `npm i && npm start`

## 🌍  Your Environment

**Angular Version:**
<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 8.0.0-beta.1
Node: 11.9.0
OS: darwin x64
Angular: 8.0.0-beta.4
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.14.0-beta.1
@angular-devkit/build-angular     0.13.2
@angular-devkit/build-optimizer   0.13.2
@angular-devkit/build-webpack     0.13.2
@angular-devkit/core              8.0.0-beta.1
@angular-devkit/schematics        8.0.0-beta.1
@angular/cli                      8.0.0-beta.1
@angular/elements                 7.2.5
@angular/pwa                      0.14.0-beta.1
@ngtools/webpack                  7.3.2
@schematics/angular               8.0.0-beta.1
@schematics/update                0.14.0-beta.1
rxjs                              6.4.0
typescript                        3.2.4
webpack                           4.29.0
</code></pre>

**Comment by gkalpak** [comment] 2019-02-20 15:16
Are you trying to use the experimental ivy?

**Comment by khaledosman** [comment] 2019-02-20 15:17
yup

**Comment by gkalpak** [comment] 2019-02-20 17:07
So, your app is not configured for ivy correctly. Since you don't seem to have used the `--experimental-ivy` cli option (which automatically takes care of things for you, you need to make some manual adjustments. See #28569 for more details.

Once you do that, there is still an error about JIT compilation, but it is really hard to debug with so much going on in the app. (It could also be an `@angular/cli` issue.)
I suggest you remove all extra modules/features and start adding them one by one until the error comes up; in other words build a minimal reproduction.

##
Closing for now, but please do open a new issue (with a minimal reproduction 🙏) if you determine there is a bug in using ivy.

**Closed by gkalpak** 2019-02-20 17:07 UTC
Labels: comp: ivy, type: bug/fix

**Comment by khaledosman** [comment] 2019-02-21 09:31
setting `"aot":true` in my angular.json build and `"enableIvy":true` in my tsconfig.app.json still didn't really fix the problem, its the same error except now generated in the console in AoT time

first I got a
```
ERROR in : Template parse errors:
The pipe 'async' could not be found ("argin:3px;" (click)="increment()">Increment</button>
    <div style="margin:3px;">Current Count: {{ [ERROR ->]counter | async }}</div>
    <button style="margin:3px;" (click)="decrement()">Decrement</button>
   "): /Users/khaledosman/Documents/github/sockets-cssvariables-pushNotification-redux-demo/client/src/app/redux/redux.component.ts.ReduxComponent.html@3:47
```
because it couldn't get the async pipe, after commenting out the div that's using the async pipe
I got the lazyloading error again but on compilation time

```

ERROR in ./src/$$_lazy_route_resource lazy namespace object
Module not found: Error: Can't resolve '/Users/khaledosman/Documents/github/sockets-cssvariables-pushNotification-redux-demo/client/src/app/chat/chat.module.ngfactory.js' in '/Users/khaledosman/Documents/github/sockets-cssvariables-pushNotification-redux-demo/client/src/$$_lazy_route_resource'
ERROR in ./src/$$_lazy_route_resource lazy namespace object
Module not found: Error: Can't resolve '/Users/khaledosman/Documents/github/sockets-cssvariables-pushNotification-redux-demo/client/src/app/css-variables-sandbox/css-variables-sandbox.module.ngfactory.js' in '/Users/khaledosman/Documents/github/sockets-cssvariables-pushNotification-redux-demo/client/src/$$_lazy_route_resource'
ERROR in ./src/$$_lazy_route_resource lazy namespace object
Module not found: Error: Can't resolve '/Users/khaledosman/Documents/github/sockets-cssvariables-pushNotification-redux-demo/client/src/app/react/react.module.ngfactory.js' in '/Users/khaledosman/Documents/github/sockets-cssvariables-pushNotification-redux-demo/client/src/$$_lazy_route_resource'
ERROR in ./src/$$_lazy_route_resource lazy namespace object
Module not found: Error: Can't resolve '/Users/khaledosman/Documents/github/sockets-cssvariables-pushNotification-redux-demo/client/src/app/redux/redux.module.ngfactory.js' in '/Users/khaledosman/Documents/github/sockets-cssvariables-pushNotification-redux-demo/client/src/$$_lazy_route_resource'
ERROR in ./src/$$_lazy_route_resource lazy namespace object
Module not found: Error: Can't resolve '/Users/khaledosman/Documents/github/sockets-cssvariables-pushNotification-redux-demo/client/src/app/sw-sandbox/sw-sandbox.module.ngfactory.js' in '/Users/khaledosman/Documents/github/sockets-cssvariables-pushNotification-redux-demo/client/src/$$_lazy_route_resource'
```

**Comment by gkalpak** [comment] 2019-02-21 15:22
You also need to add `"allowEmptyCodegenFiles": true` in `angularCompilerOptions` in `tsconfig.app.json`. This is a temporary workaround and should not be necessary soon.
I thought this was mentioned in #28569 (maybe it used to, but I don't see it now 😕).

**Comment by khaledosman** [comment] 2019-02-21 15:33
That actually fixed it, thanks!

**Comment by khaledosman** [comment] 2019-02-21 15:35
That actually fixed it, thanks!
