### ISSUE TITLE
Feature Request: Add 'newInstanceOf' to "providers"

### ISSUE THREAD

**Issue by asgerjensen** [angular/angular#22756] opened 2018-03-14 08:50 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Component providers does not have a way of getting a new instance of a module defined provider.
This makes component reuse difficult between projects, if a component needs a "private instance" of an otherwise global service.

## Expected behavior

Ideally, I'd like to be able to get a new instance of whatever `Service` is defined to be in the injector tree.

I propose a `newInstanceOf` or `newInstance` keyword in the `provide` struct, that would  walk up the tree and return a new instance of that class.

I.e.
```
@Component({
    providers: [
       { provide: Service, newInstance: true }
   ])
```

or incase I want to rename the service token

```
@Component({
    providers: [
       { provide: new InjectionToken<Service>('LocalService'), newInstanceOf: Service }
   ])
```

## Minimal reproduction of the problem with instructions

0. Create new project with `ng new`
1. Create two services, let one extend the other.
  ```
       @Injectable()
       export class Service {};

        @Injectable()
         export class BetterService extends Service {};
   ```
2. In `app.module` provide the extended service as the base service. 
   ` { provide: Service, useClass: BetterService } `
3. in `app.module` add constructor with 
```
  constructor(service: Service) {
    console.log('module', service.constructor.name);
  }
```
4. In `app.component`, add to `@Component`
```
    providers: [ Service ]
```
5. In `app.component add constructor
```
  constructor(service: Service) {
    console.log('component', service.constructor.name);
  }
```
6. Run.

Observe that console shows
Module BetterService
Component Service

## What is the motivation / use case for changing the behavior?

Writing components or entire modules that can take be reused between projects, while being able to have new versions of services injected, even when those are used as private instances. Notably, the Component, as its being reused, should not have knowledge of what concrete implementations of `Service` is available, just that it needs a private instance of whatever acts on behalf of `Service` right now.

Consider two services
```
 - Service
       - BetterService extends Service
```

In `app.module.ts` I can now define that 'Service' should provide 'BetterService'
```
   { provide: Service, useClass: BetterService }
```

In my component i need a new instance of whatever `Service` is defined to be, in the global scope, but as the component is a shared component, it should not know that `BetterService` exists.

```
@Component({
    providers: [
       { provide: Service, useClass: ??? }
   ])
```

## Environment

<pre><code>
Angular version: 5.2.3

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by trotyl** [comment] 2018-03-14 09:15
Duplicate of #18015

**Comment by asgerjensen** [comment] 2018-03-14 10:03
While I see how these are related, I dont think its a duplicate.

#18015 is concerned with avoiding writing the "providers" section on a component level to get new instances, while this is concerned with being able to write a "providers" section on the component level, that would re-use the "definition" of the binding, from the module level. I.e. allow a component to say " I want to get an instance of whatever provides `Service` at this time", but without knowing exactly what subclass of `Service` is currently being applied to the application.

**Comment by trotyl** [comment] 2018-03-15 02:19
I agree, this one is more logical and sound.

**Comment by dawidgarus** [comment] 2018-03-16 14:10
Here's workaround to achieve desired behavior: https://plnkr.co/edit/olWXoB1X4BN4dTmFYF28?p=preview
Main drawback is that You have to define static property `parameters`. It's not completely non-standard. Angular actually uses it instead of reflections to determine dependencies, so when You have `parameters` there's no need for `@Injectable` or other decorators.
It would be much cleaner if there was some standard way to get list of dependencies or provider for injected value.
Dunno if it works with AOT.

**Closed** 2022-03-28 23:17 UTC
Labels: feature, comp: core, core: di, insufficient votes, votes required
