### ISSUE TITLE
Variable replacement in styles

### ISSUE THREAD

**Issue by mbeckenbach** [angular/angular#12543] opened 2016-10-26 13:00 UTC
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**What is the motivation / use case for changing the behavior?**
Just a fix idea, but it would be cool to have model binding inside of the css styles similar to the model bindings in html templates. This would make things like theming at runtime a lot easier. 

Something like this:

.button {
  background-color: {{myColorPropertyInMyCompontent}}
}

**Comment by DzmitryShylovich** [comment] 2016-10-26 13:04
Duplicate of https://github.com/angular/angular/issues/7251

**Comment by pkozlowski-opensource** [comment] 2016-10-26 21:41
It is a duplicate of #7251 indeed. Thnx @DzmitryShylovich

**Closed by pkozlowski-opensource** 2016-10-26 21:41 UTC
