### ISSUE TITLE
Non-existent pages return `200`, but should return `404` http status

### ISSUE THREAD

**Issue by fredsa** [angular/angular#56853] opened 2024-07-04 17:59 UTC
### Describe the problem that you experienced

Non-existent pages, e.g. https://angular.dev/this-page-does-not-exist, are expected to return `404` http status. Instead, all bad URLs return http `200` and dynamically inject the 'page not found' message to the user.

The incorrect `200` status code informs web crawlers that the requested page is valid. The lack of actual useful content on that page might negatively affect ranking as those pages will be deemed to not have any relevant content on them.

The incorrect `200` status code makes it difficult to detect broken links, incl. those internal to the site. As an example, this issue was discovered while diagnosing broken page,`https://angular.dev/api/animations/%C9%B5AnimationGroupPlayer` (see #56850).

EXPECTED:
- Non-existent page returns http `404` status code

ACTUAL:
- Non-existent page returns http `200` status code

### Enter the URL of the topic with the problem

https://angular.dev/api/animations/%C9%B5AnimationGroupPlayer

**Comment by twerske** [comment] 2024-07-08 16:35
Closing as a duplicate of https://github.com/angular/angular/issues/53314.

For additional context, this is an open Angular feature request to be able to return alternative HTTP Status Codes that is not possible today.

**Closed by twerske** 2024-07-08 16:35 UTC
Labels: P2, area: adev
