### ISSUE TITLE
Service worker doesn't check update on each navigation request

### ISSUE THREAD

**Issue by Sam-Lin-MillersLab** [angular/angular#39652] opened 2020-11-12 17:26 UTC
# 🐞 bug report

### Affected Package
@angular/pwa

### Is this a regression?

not sure

### Description

https://angular.io/guide/service-worker-communications

In the document, it states 

> The service worker checks for updates during initialization and on each navigation request

However, I tested it with 
Chrome  86.0.4240.183  and Edge 86.0.622.63

However it does work in Firefox 82.0.3
## 🌍  Your Environment

**Angular Version:**
<pre><code>
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1002.0
@angular-devkit/build-angular   0.1002.0
@angular-devkit/core            10.2.0
@angular-devkit/schematics      10.2.0
@angular/cdk                    10.2.7
@angular/cli                    10.2.0
@angular/material               10.2.7
@schematics/angular             10.2.0
@schematics/update              0.1002.0
rxjs                            6.6.3
typescript                      4.0.5
</code></pre>

**Comment by gkalpak** [comment] 2020-11-12 21:11
@Sam-Lin-MillersLab, it is hard to tell what is going on without a reproduction. If you could post a minimal reproduction, that would make things a lot easier.

If that is not possible, you could try to debug this on your end (e.g. put some break-points inside the SericeWorker) and provide more info on what exactly is going on.

**Comment by maxisam** [comment] 2020-11-13 07:36
Here you go. https://github.com/maxisam/angular-pwa 

Switching between route test and route foo won't trigger update check.

**Comment by gkalpak** [comment] 2020-11-16 17:33
Thx for providing the repro, @maxisam :+1:

So, as mentioned in the docs, the SW will check for updates on **navigation** requests only (not on other types of request, because there might be many of them and checking too often will unnecessarily consume network resources).

A navigation request is a request whose [Request#mode][1] property is set to `navigate`. Essentially, it is for requests that happen when you navigate to a new HTML document.

The transitions you describe (i.e. switching between Angular routes), on the other hand, do not involve navigation requests. The app will remain on the same HTML document and only change he content that is displayed to the user (via JavaScript). See [this StackOverflow answer][2] for more info on client-side routing.

##
I hope that makes sense. I am going to close this issue, since everything works as intended afaict, but feel free to continue the discussion below (if anything is unclear or you have more questions).

[1]: https://developer.mozilla.org/en-US/docs/Web/API/Request/mode
[2]: https://stackoverflow.com/questions/10190215/what-is-client-side-routing-and-how-is-it-used#10473302

**Closed by gkalpak** 2020-11-16 17:33 UTC
Labels: comp: service-worker, needs clarification, needs reproduction

**Comment by maxisam** [comment] 2020-11-16 19:49
In my opinion, it is kind of ambiguous. 

>updates during initialization and on each navigation 

From my understanding, the navigate request is pretty much the same with initialization. I don't see a way to stay in a PWA and trigger navigation request without leaving and coming back. 

So when you put them together, it is easy to think it means angular route navigation. 

Honestly, I knew this might be the case so I didn't bother to create an repo first. 

Could we make it clearer in the document?

**Comment by gkalpak** [comment] 2020-11-17 22:23
"Initialization" refers to the SW not the Angular app. Note that the same SW instance can serve multiple pages (i.e. browser tabs) and each SW instance is only initialized once (when it receives a fetch request or a Push message).

Regarding "navigation", the docs mention that is means _"when the user navigates from a different address to your app"_ in an attempt to make it clear that it does not refer to Angular route transitions.

That said, if you have ideas on how to improve the docs and make it even more clear, please submit a pull request 🙏
(FYI, the source file is [here][1].)

[1]: https://github.com/angular/angular/blob/master/aio/content/guide/service-worker-communications.md

**Comment by maxisam** [comment] 2020-11-18 04:05
Well, I guess this is the part that confuses me. Yes, SW instance only gets initialized once, which only happens when the page gets loaded. Navigation from a different address to the app will get the page loaded. Since we are on the topic to tell people when SwUpdate will check for update, I feel like why don't we just tell people it only happens when page get loaded? It is like creating a frontend UI with too many details on the page will make users lose their focus. I think you explained it very well. I honestly don't know how to write the document clear and right to the point. So the best I can do is bringing this up and leave this here. At least, people can search and find the great explanation you provided if they get confused by the document.

**Comment by gkalpak** [comment] 2020-11-18 10:12
> SW instance only gets initialized once, which only happens when the page gets loaded. Navigation from a different address to the app will get the page loaded.

Just to be clear: The SW instance is not necessarily tied to navigating to a page.

For example, if the user navigates to your app in one browser tab and then opens the app in a second tab shortly after, both tabs will be served by the same SW instance and there will be no initialization for the second tab.

Another example is when the user navigates to your app (which causes the SW to be initialized) and then leaves the tab open for a while. After some time, the browser will destroy the SW instance (to reclaim resources). So, if the user navigates to an Anglar route in the same tab after a while and that causes more requests (that go through the SW), a new SW instance will be created by the browser (and ianother initialization will be performed).

So, as you can see, the SW instantiation/initialization is not necessarily tied to navigating to the page (although they often coinside).

**Comment by maxisam** [comment] 2020-11-18 20:00
Interesting, I didn't know SW instance will be destroyed after a while even the tab is still open. 

Thank you for the great details. I hope this thread will help others in the future.
