### ISSUE TITLE
router.navigateUrl('/') -- > zone.js drainMicroTaskQueue running into endless loop

### ISSUE THREAD

**Issue by drarsalan** [angular/angular#18981] opened 2017-08-31 19:18 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I am trying to do a simple router navigation on line 48 on app.component.ts.

When I do that the application goes into an infinite loop in zone.js. Tasks are cleared on line 598 but by the time line 602 is executed, _microTaskQueue again contains a task and this is an infinite loop that keeps on going.

Logout is being called by a simple (click) handler.
`<li><a (click)="logoutUser()">Logout</a></li>`

<pre><code>

<strong>app.component.ts</strong>

01	import {Component, OnInit} from "@angular/core";
02	import {GlobalService} from "./common/service/global.service";
03	import {Router} from "@angular/router";
04	import {EventHubService} from "./modules/event-emitter/event.emitter.service";
05	import {LoginComponent} from "./common/component/login/login.component";
06
07	@Component({
08		selector: 'app-root',
09		templateUrl: './app.component.html',
10		styleUrls: ['./app.component.css'],
11		providers: [GlobalService]
12	})
13	export class AppComponent implements OnInit
14	{
15		ngOnInit(): void
16		{
17			EventHubService.get(LoginComponent.LoginEvent)
18		}
19
20		title = 'My Company';
21		public  _loggedUserName = null;
22		public  _logginMethod : string;
23
24		constructor(private _router: Router,
25					private _gs : GlobalService)
26		{
27			var self = this;
28			EventHubService.get(LoginComponent.LoginEvent).subscribe(() => {
29				self.loginUser();
30			});
31		}
32
33		loginUser ()
34		{
35			if (GlobalService.userSession)
36			{
37				this._loggedUserName = GlobalService.userSession.displayName;
38				this._logginMethod = GlobalService.userSession.isAdLogin ? "Company" : GlobalService.userSession.companyGroup;
39			}
40		}
41
42		logoutUser()
43		{
44			this._gs.logOffUser();
45			this._loggedUserName = "";
46			this._logginMethod = "";
47
48			this._router.navigateByUrl('/');
49		}
50	}

<strong>zone.js</strong>

593	function drainMicroTaskQueue() {
594		if (!_isDrainingMicrotaskQueue) {
595			_isDrainingMicrotaskQueue = true;
596			while (_microTaskQueue.length) {
597				var queue = _microTaskQueue;
598				_microTaskQueue = [];
599				for (var i = 0; i < queue.length; i++) {
600					var task = queue[i];
601					try {
602						task.zone.runTask(task, null, null);
603					}
604					catch (error) {
605						_api.onUnhandledError(error);
606					}
607				}
608			}
609			var showError = !Zone[__symbol__('ignoreConsoleErrorUncaughtError')];
610			_api.microtaskDrainDone();
611			_isDrainingMicrotaskQueue = false;
612		}
613	}
</code></pre>

## Environment

<pre><code>
project.json:
{
  "name": "customer-support-center",
  "version": "0.0.0",
  "license": "Commercial",
  "angular-cli": {},
  "scripts": {
    "start": "ng serve",
    "lint": "tslint \"src/**/*.ts\"",
    "test": "ng test",
    "pree2e": "webdriver-manager update",
    "e2e": "protractor"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^4.3.6",
    "@angular/common": "^4.3.6",
    "@angular/compiler": "^4.3.6",
    "@angular/core": "^4.3.6",
    "@angular/forms": "^4.3.6",
    "@angular/http": "^4.3.6",
    "@angular/platform-browser": "^4.3.6",
    "@angular/platform-browser-dynamic": "^4.3.6",
    "@angular/router": "^4.3.6",
    "angular-2-local-storage": "^1.0.0",
    "angular2-cookie": "^1.2.6",
    "angular2-datatable": "^0.6.0",
    "angular2-jwt": "^0.2.3",
    "angular2-ladda": "^1.1.1",
    "angular2-modal": "^3.0.3",
    "angular2localization": "^1.4.1",
    "bootstrap-checkbox": "^1.4.0",
    "core-js": "^2.5.1",
    "lodash": "^4.17.4",
    "ng2-recaptcha": "^1.7.0",
    "ng2-sidebar": "^1.8.2",
    "ng2-validation": "^4.2.0",
    "rxjs": "^5.4.3",
    "ts-helpers": "^1.1.1",
    "zone.js": "^0.8.17"
  },
  "devDependencies": {
    "@angular/cli": "^1.3.2",
    "@angular/compiler-cli": "^4.3.6",
    "@types/jasmine": "^2.5.54",
    "@types/node": "^8.0.26",
    "codelyzer": "^3.1.2",
    "jasmine-core": "^2.8.0",
    "jasmine-spec-reporter": "^4.2.1",
    "karma": "^1.7.1",
    "karma-chrome-launcher": "^2.2.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-remap-istanbul": "^0.6.0",
    "protractor": "^5.1.2",
    "ts-node": "^3.3.0",
    "tslint": "^5.7.0",
    "typescript": "^2.5.2",
    "webdriver-manager": "^12.0.6"
  }
}

Browser:
- [X] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 6.10.2
- Platform:  Windows

Others:

</code></pre>

**Comment by Toxicable** [comment] 2017-08-31 19:34
I'm sorry but reported issues require a plunker reproducing the problem.

If this issue persists, please create a plunker using this template and describe the difference between the expected and current behavior and create a new issue: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue

**Comment by happysamyak** [comment] 2018-04-23 02:14
Facing same issue.

**Comment by JiaLiPassion** [comment] 2018-04-23 02:58
@happysamyak , could you provide a reproduce repo? thank you.

**Comment by happysamyak** [comment] 2018-04-23 04:03
We are trying to migrate ng1 project to ng5.
can share full codebase. routing functionality and boostraping is below-
Bootstrapping-
platformBrowserDynamic().bootstrapModule(AppModule).then(platformRef => {
    console.log('AppModule bootstrapped');
	  const upgrade = platformRef.injector.get(UpgradeModule) as UpgradeModule;
    upgrade.bootstrap(document.body, ['ccuiApp'], { strictDi: true });
    console.log('bootstrapping finished');
    setUpLocationSync(upgrade);
    //platformRef.injector.get(Router).initialNavigation();
});

NgModule-
export class Ng1Ng2UrlHandlingStrategy implements UrlHandlingStrategy {
  shouldProcessUrl(url: any) {
    console.log("url ng5", url.toString());
    return url.toString().startsWith("/screens/switch/configuration.html#/ng5LeftNav/");
  }

  extract(url: any) {
    
    return url;
  }

  merge(url: any, whole: any) {
    return url;
  }
}

const myDirectives = [
  DocumentStarsDirective
];

const appRoutes: Routes = [
  { path: 'screens/switch/configuration.html', component: ng5Component },
];


@NgModule({
  providers: [
     DocumentsService,
     { provide: UrlHandlingStrategy, useClass: Ng1Ng2UrlHandlingStrategy }
  ],
  declarations: [
    AppComponent,
    DocumentsService,
    myDirectives,
    ng5Component
  ],
  imports: [
    BrowserModule,
    UpgradeModule,
    RouterModule.forRoot(appRoutes, { useHash: false, initialNavigation: false, enableTracing: true })
  ],
  // exports: [
  //   RouterModule
  // ],
  entryComponents: [AppComponent]
})


Error-
Error: [$rootScope:infdig] http://errors.angularjs.org/1.2.16/$rootScope/infdig?p0=10&p1=%5B%5B%22fn%3A%20function()%7Bvar%20a%3Dd.url()%2Cb%3Dh.%24%24replace%3Bm%26%26a%3D%3Dh.absUrl()%7C%7C(m%2B%2B%2Cc.%24evalAsync(function()%7Bc.%24broadcast(%5C%22%24locationChangeStart%5C%22%2Ch.absUrl()%2Ca).defaultPrevented%3Fh.%24%24parse(a)%3A(d.url(h.absUrl()%2Cb)%2Cf(a))%7D))%3Bh.%24%24replace%3D!1%3Breturn%20m%7D%3B%20newVal%3A%2042%3B%20oldVal%3A%2041%22%5D%2C%5B%22fn%3A%20function()%7Bvar%20a%3Dd.url()%2Cb%3Dh.%24%24replace%3Bm%26%26a%3D%3Dh.absUrl()%7C%7C(m%2B%2B%2Cc.%24evalAsync(function()%7Bc.%24broadcast(%5C%22%24locationChangeStart%5C%22%2Ch.absUrl()%2Ca).defaultPrevented%3Fh.%24%24parse(a)%3A(d.url(h.absUrl()%2Cb)%2Cf(a))%7D))%3Bh.%24%24replace%3D!1%3Breturn%20m%7D%3B%20newVal%3A%2043%3B%20oldVal%3A%2042%22%5D%2C%5B%22fn%3A%20function()%7Bvar%20a%3Dd.url()%2Cb%3Dh.%24%24replace%3Bm%26%26a%3D%3Dh.absUrl()%7C%7C(m%2B%2B%2Cc.%24evalAsync(function()%7Bc.%24broadcast(%5C%22%24locationChangeStart%5C%22%2Ch.absUrl()%2Ca).defaultPrevented%3Fh.%24%24parse(a)%3A(d.url(h.absUrl()%2Cb)%2Cf(a))%7D))%3Bh.%24%24replace%3D!1%3Breturn%20m%7D%3B%20newVal%3A%2044%3B%20oldVal%3A%2043%22%5D%2C%5B%22fn%3A%20function()%7Bvar%20a%3Dd.url()%2Cb%3Dh.%24%24replace%3Bm%26%26a%3D%3Dh.absUrl()%7C%7C(m%2B%2B%2Cc.%24evalAsync(function()%7Bc.%24broadcast(%5C%22%24locationChangeStart%5C%22%2Ch.absUrl()%2Ca).defaultPrevented%3Fh.%24%24parse(a)%3A(d.url(h.absUrl()%2Cb)%2Cf(a))%7D))%3Bh.%24%24replace%3D!1%3Breturn%20m%7D%3B%20newVal%3A%2045%3B%20oldVal%3A%2044%22%5D%2C%5B%22fn%3A%20function()%7Bvar%20a%3Dd.url()%2Cb%3Dh.%24%24replace%3Bm%26%26a%3D%3Dh.absUrl()%7C%7C(m%2B%2B%2Cc.%24evalAsync(function()%7Bc.%24broadcast(%5C%22%24locationChangeStart%5C%22%2Ch.absUrl()%2Ca).defaultPrevented%3Fh.%24%24parse(a)%3A(d.url(h.absUrl()%2Cb)%2Cf(a))%7D))%3Bh.%24%24replace%3D!1%3Breturn%20m%7D%3B%20newVal%3A%2046%3B%20oldVal%3A%2045%22%5D%5D
    at angular.min_1_2_16.js?v=__stringCache:6
    at h.$digest (angular.min_1_2_16.js?v=__stringCache:107)
    at h.$apply (angular.min_1_2_16.js?v=__stringCache:109)
    at ccui-cmn.min.js?v=__stringCache:762
    at Object.execCb (require.min.js?v=__stringCache:639)
    at Z.check (require.min.js?v=__stringCache:353)
    at Z.enable (require.min.js?v=__stringCache:466)
    at Z.init (require.min.js?v=__stringCache:313)
    at require.min.js?v=__stringCache:552
    at ZoneDelegate.webpackJsonp../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:421)
(anonymous) @ angular.min_1_2_16.js?v=__stringCache:89
(anonymous) @ angular.min_1_2_16.js?v=__stringCache:66
$apply @ angular.min_1_2_16.js?v=__stringCache:109
(anonymous) @ ccui-cmn.min.js?v=__stringCache:762
execCb @ require.min.js?v=__stringCache:639
check @ require.min.js?v=__stringCache:353
enable @ require.min.js?v=__stringCache:466
init @ require.min.js?v=__stringCache:313
(anonymous) @ require.min.js?v=__stringCache:552
webpackJsonp../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:421
onInvokeTask @ core.js:4740
webpackJsonp../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:420
webpackJsonp../node_modules/zone.js/dist/zone.js.Zone.runTask @ zone.js:188
webpackJsonp../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask @ zone.js:496
ZoneTask.invoke @ zone.js:485
timer @ zone.js:2054
setTimeout (async)
scheduleTask @ zone.js:2075
webpackJsonp../node_modules/zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ zone.js:407
onScheduleTask @ zone.js:297
webpackJsonp../node_modules/zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ zone.js:401
webpackJsonp../node_modules/zone.js/dist/zone.js.Zone.scheduleTask @ zone.js:232
webpackJsonp../node_modules/zone.js/dist/zone.js.Zone.scheduleMacroTask @ zone.js:255
scheduleMacroTaskWithCurrentZone @ zone.js:1114
(anonymous) @ zone.js:2090
proto.(anonymous function) @ zone.js:1394
l.nextTick @ require.min.js?v=__stringCache:689
d @ require.min.js?v=__stringCache:548
requirejs @ require.min.js?v=__stringCache:683
(anonymous) @ ccui-cmn.min.js?v=__stringCache:762
d @ angular.min_1_2_16.js?v=__stringCache:34
(anonymous) @ angular-route_v1.2.0rc1.min.js?v=__stringCache:8
q @ angular.min_1_2_16.js?v=__stringCache:7
(anonymous) @ angular-route_v1.2.0rc1.min.js?v=__stringCache:8
u @ angular.min_1_2_16.js?v=__stringCache:97
u @ angular.min_1_2_16.js?v=__stringCache:97
(anonymous) @ angular.min_1_2_16.js?v=__stringCache:98
$eval @ angular.min_1_2_16.js?v=__stringCache:108
$digest @ angular.min_1_2_16.js?v=__stringCache:106
$apply @ angular.min_1_2_16.js?v=__stringCache:109
(anonymous) @ ccui-cmn.min.js?v=__stringCache:762
execCb @ require.min.js?v=__stringCache:639
check @ require.min.js?v=__stringCache:353
(anonymous) @ require.min.js?v=__stringCache:452
(anonymous) @ require.min.js?v=__stringCache:53
(anonymous) @ require.min.js?v=__stringCache:475
y @ require.min.js?v=__stringCache:19
emit @ require.min.js?v=__stringCache:474
check @ require.min.js?v=__stringCache:364
enable @ require.min.js?v=__stringCache:466
init @ require.min.js?v=__stringCache:313
E @ require.min.js?v=__stringCache:230
completeLoad @ require.min.js?v=__stringCache:606
onScriptLoad @ require.min.js?v=__stringCache:642
webpackJsonp../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:421
onInvokeTask @ core.js:4740
webpackJsonp../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:420
webpackJsonp../node_modules/zone.js/dist/zone.js.Zone.runTask @ zone.js:188
webpackJsonp../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask @ zone.js:496
invokeTask @ zone.js:1540
globalZoneAwareCallback @ zone.js:1566
error (async)
customScheduleGlobal @ zone.js:1666
webpackJsonp../node_modules/zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ zone.js:407
onScheduleTask @ zone.js:297
webpackJsonp../node_modules/zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ zone.js:401
webpackJsonp../node_modules/zone.js/dist/zone.js.Zone.scheduleTask @ zone.js:232
webpackJsonp../node_modules/zone.js/dist/zone.js.Zone.scheduleEventTask @ zone.js:258
(anonymous) @ zone.js:1831
l.load @ require.min.js?v=__stringCache:717
load @ require.min.js?v=__stringCache:635
load @ require.min.js?v=__stringCache:334
fetch @ require.min.js?v=__stringCache:329
check @ require.min.js?v=__stringCache:366
enable @ require.min.js?v=__stringCache:466
enable @ require.min.js?v=__stringCache:589
(anonymous) @ require.min.js?v=__stringCache:458
(anonymous) @ require.min.js?v=__stringCache:53
y @ require.min.js?v=__stringCache:19
enable @ require.min.js?v=__stringCache:440
init @ require.min.js?v=__stringCache:313
(anonymous) @ require.min.js?v=__stringCache:552
webpackJsonp../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:421
onInvokeTask @ core.js:4740
webpackJsonp../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:420
webpackJsonp../node_modules/zone.js/dist/zone.js.Zone.runTask @ zone.js:188
webpackJsonp../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask @ zone.js:496
ZoneTask.invoke @ zone.js:485
timer @ zone.js:2054
setTimeout (async)
scheduleTask @ zone.js:2075
webpackJsonp../node_modules/zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ zone.js:407
onScheduleTask @ zone.js:297
webpackJsonp../node_modules/zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ zone.js:401
webpackJsonp../node_modules/zone.js/dist/zone.js.Zone.scheduleTask @ zone.js:232
webpackJsonp../node_modules/zone.js/dist/zone.js.Zone.scheduleMacroTask @ zone.js:255
scheduleMacroTaskWithCurrentZone @ zone.js:1114
(anonymous) @ zone.js:2090
proto.(anonymous function) @ zone.js:1394
l.nextTick @ require.min.js?v=__stringCache:689
d @ require.min.js?v=__stringCache:548
requirejs @ require.min.js?v=__stringCache:683
(anonymous) @ ccui-cmn.min.js?v=__stringCache:762
d @ angular.min_1_2_16.js?v=__stringCache:34
(anonymous) @ angular-route_v1.2.0rc1.min.js?v=__stringCache:8
q @ angular.min_1_2_16.js?v=__stringCache:7
(anonymous) @ angular-route_v1.2.0rc1.min.js?v=__stringCache:8
u @ angular.min_1_2_16.js?v=__stringCache:97
u @ angular.min_1_2_16.js?v=__stringCache:97
(anonymous) @ angular.min_1_2_16.js?v=__stringCache:98
$eval @ angular.min_1_2_16.js?v=__stringCache:108
$digest @ angular.min_1_2_16.js?v=__stringCache:106
$apply @ angular.min_1_2_16.js?v=__stringCache:109
(anonymous) @ angular.min_1_2_16.js?v=__stringCache:189
dispatch @ jquery-1.8.1.min.js?v=__stringCache:2
h @ jquery-1.8.1.min.js?v=__stringCache:2
webpackJsonp../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:421
onInvokeTask @ core.js:4740
webpackJsonp../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:420
webpackJsonp../node_modules/zone.js/dist/zone.js.Zone.runTask @ zone.js:188
webpackJsonp../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask @ zone.js:496
invokeTask @ zone.js:1540
globalZoneAwareCallback @ zone.js:1566
core.js:1448 ERROR Error: [$rootScope:infdig] http://errors.angularjs.org/1.2.16/$rootScope/infdig?p0=10&p1=%5B%5B%22fn%3A%20function()%7Bvar%20a%3Dd.url()%2Cb%3Dh.%24%24replace%3Bm%26%26a%3D%3Dh.absUrl()%7C%7C(m%2B%2B%2Cc.%24evalAsync(function()%7Bc.%24broadcast(%5C%22%24locationChangeStart%5C%22%2Ch.absUrl()%2Ca).defaultPrevented%3Fh.%24%24parse(a)%3A(d.url(h.absUrl()%2Cb)%2Cf(a))%7D))%3Bh.%24%24replace%3D!1%3Breturn%20m%7D%3B%20newVal%3A%2042%3B%20oldVal%3A%2041%22%5D%2C%5B%22fn%3A%20function()%7Bvar%20a%3Dd.url()%2Cb%3Dh.%24%24replace%3Bm%26%26a%3D%3Dh.absUrl()%7C%7C(m%2B%2B%2Cc.%24evalAsync(function()%7Bc.%24broadcast(%5C%22%24locationChangeStart%5C%22%2Ch.absUrl()%2Ca).defaultPrevented%3Fh.%24%24parse(a)%3A(d.url(h.absUrl()%2Cb)%2Cf(a))%7D))%3Bh.%24%24replace%3D!1%3Breturn%20m%7D%3B%20newVal%3A%2043%3B%20oldVal%3A%2042%22%5D%2C%5B%22fn%3A%20function()%7Bvar%20a%3Dd.url()%2Cb%3Dh.%24%24replace%3Bm%26%26a%3D%3Dh.absUrl()%7C%7C(m%2B%2B%2Cc.%24evalAsync(function()%7Bc.%24broadcast(%5C%22%24locationChangeStart%5C%22%2Ch.absUrl()%2Ca).defaultPrevented%3Fh.%24%24parse(a)%3A(d.url(h.absUrl()%2Cb)%2Cf(a))%7D))%3Bh.%24%24replace%3D!1%3Breturn%20m%7D%3B%20newVal%3A%2044%3B%20oldVal%3A%2043%22%5D%2C%5B%22fn%3A%20function()%7Bvar%20a%3Dd.url()%2Cb%3Dh.%24%24replace%3Bm%26%26a%3D%3Dh.absUrl()%7C%7C(m%2B%2B%2Cc.%24evalAsync(function()%7Bc.%24broadcast(%5C%22%24locationChangeStart%5C%22%2Ch.absUrl()%2Ca).defaultPrevented%3Fh.%24%24parse(a)%3A(d.url(h.absUrl()%2Cb)%2Cf(a))%7D))%3Bh.%24%24replace%3D!1%3Breturn%20m%7D%3B%20newVal%3A%2045%3B%20oldVal%3A%2044%22%5D%2C%5B%22fn%3A%20function()%7Bvar%20a%3Dd.url()%2Cb%3Dh.%24%24replace%3Bm%26%26a%3D%3Dh.absUrl()%7C%7C(m%2B%2B%2Cc.%24evalAsync(function()%7Bc.%24broadcast(%5C%22%24locationChangeStart%5C%22%2Ch.absUrl()%2Ca).defaultPrevented%3Fh.%24%24parse(a)%3A(d.url(h.absUrl()%2Cb)%2Cf(a))%7D))%3Bh.%24%24replace%3D!1%3Breturn%20m%7D%3B%20newVal%3A%2046%3B%20oldVal%3A%2045%22%5D%5D
    at angular.min_1_2_16.js?v=__stringCache:6
    at h.$digest (angular.min_1_2_16.js?v=__stringCache:107)
    at h.$apply (angular.min_1_2_16.js?v=__stringCache:109)
    at ccui-cmn.min.js?v=__stringCache:762
    at Object.execCb (require.min.js?v=__stringCache:639)
    at Z.check (require.min.js?v=__stringCache:353)
    at Z.enable (require.min.js?v=__stringCache:466)
    at Z.init (require.min.js?v=__stringCache:313)
    at require.min.js?v=__stringCache:552
    at ZoneDelegate.webpackJsonp../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:421)

**Comment by JiaLiPassion** [comment] 2018-04-23 04:38
@happysamyak , I know about the `drainMicroTaskQueue` function, but I still need a reproduce repo, could you try to make a small sample repo to describe the issue? Thank you.

**Comment by happysamyak** [comment] 2018-04-23 05:54
sorry JiaLiPassion. It is not possible for me.

**Comment by JiaLiPassion** [comment] 2018-04-23 06:00
@happysamyak , ok , I will try to look the code.

**Comment by happysamyak** [comment] 2018-04-23 06:12
sorry JiaLiPassion. It is not possible for me. Let  me know if i have to share any file related to angular.
Seems like issue is because of url encoding. By default angular5 decodes url which will be read by angular1.
so current url is decoded and next one is not.

currentConfigPath-  /mm/mynode
nextConfigPath-  %2Fmm%2Fmynode

https://10.17.24.36:4343/screens/switch/configuration.html#/ng5LeftNav/test?configpath=/mm/mynode

**Comment by JiaLiPassion** [comment] 2018-04-23 06:50
@happysamyak , ok, thank you for the information, could you check the stacktrace when infinite loop occurs, and print out 2 `task.callback.toString()` for me? (check the comment below)

```javascript
function drainMicroTaskQueue() {
if (!_isDrainingMicrotaskQueue) {
  _isDrainingMicrotaskQueue = true; 
  while (_microTaskQueue.length) {
  var queue = _microTaskQueue;
  _microTaskQueue = [];
  for (var i = 0; i < queue.length; i++) {
    var task = queue[i];
    // break here when navigate call, and print more several task.callback.toString().
    try {
      task.zone.runTask(task, null, null);
    } catch (error) {
      _api.onUnhandledError(error);
    }
  }
}
_api.microtaskDrainDone();
_isDrainingMicrotaskQueue = false;
}
}
```

**Comment by happysamyak** [comment] 2018-04-23 07:00
task.callback.toString()
"function () {
            try {
                var parentPromiseValue = promise[symbolValue];
                var isFinallyPromise = chainPromise && symbolFinally === chainPromise[symbolFinally];
                if (isFinallyPromise) {
                    // if the promise is generated from finally call, keep parent promise's state and value
                    chainPromise[symbolParentPromiseValue] = parentPromiseValue;
                    chainPromise[symbolParentPromiseState] = promiseState;
                }
                // should not pass value to finally callback
                var value = zone.run(delegate, undefined, isFinallyPromise && delegate !== forwardRejection && delegate !== forwardResolution ? [] : [parentPromiseValue]);
                resolvePromise(chainPromise, true, value);
            }
            catch (error) {
                // if error occurs, should always return this error
                resolvePromise(chainPromise, false, error);
            }
        }"

**Comment by JiaLiPassion** [comment] 2018-04-23 10:54
@happysamyak , that's great! You just provided a very useful information to all `hybrid` developers.

**Comment by jasonaden** [comment] 2018-06-26 18:37
I'm going to close this issue as it has been resolved.

To be clear, your solution above will work for your application, but doesn't look like something that can be generalized as other applications may serialize URLs differently. The interplay between AngularJS and Angular routers (and the default URL parsing/serializing) is something larger applications will run into due to the variety of URLs they will be using on both sides.

This is a topic of an ongoing effort to create a unified router on top of the Angular router that can consume AngularJS configurations (for ngRoute and hopefully for ui-router as well).

**Closed by jasonaden** 2018-06-26 18:37 UTC
Labels: comp: router, comp: zones, freq1: low, severity5: regression, type: bug/fix

**Comment by mm44m6** [comment] 2018-09-13 19:12
I'm having the same issue. I'm trying to migrate the phoneCat project that is in the official documentation, following the step-by-step instructions. It's throwing me into an infinite loop just like this when I serve my application, before even launching anything. Help?

**package.json**

```
{
  "name": "angular-phonecat",
  "private": true,
  "version": "0.0.0",
  "description": "A tutorial application for AngularJS",
  "repository": "https://github.com/angular/angular-phonecat",
  "license": "MIT",
  "devDependencies": {
    "@types/angular": "^1.6.50",
    "@types/angular-animate": "^1.5.10",
    "@types/angular-cookies": "^1.4.5",
    "@types/angular-mocks": "^1.7.0",
    "@types/angular-resource": "^1.5.14",
    "@types/angular-route": "^1.7.0",
    "@types/angular-sanitize": "^1.3.7",
    "@types/jasmine": "^2.8.8",
    "bower": "^1.7.7",
    "http-server": "^0.9.0",
    "jasmine-core": "^2.4.1",
    "karma": "^0.13.22",
    "karma-chrome-launcher": "^0.2.3",
    "karma-firefox-launcher": "^0.1.7",
    "karma-jasmine": "^0.3.8",
    "protractor": "^4.0.9",
    "typescript": "^3.0.3"
  },
  "scripts": {
    "start": "http-server . -a localhost -p 8000 -c-1",
    "pretest": "npm install",
    "test": "karma start karma.conf.js",
    "test-single-run": "karma start karma.conf.js --single-run",
    "preupdate-webdriver": "npm install",
    "update-webdriver": "webdriver-manager update",
    "preprotractor": "npm run update-webdriver",
    "protractor": "protractor e2e-tests/protractor.conf.js",
    "update-index-async": "node -e \"var fs=require('fs'),indexFile='app/index-async.html',loaderFile='app/bower_components/angular-loader/angular-loader.min.js',loaderText=fs.readFileSync(loaderFile,'utf-8').split(/sourceMappingURL=angular-loader.min.js.map/).join('sourceMappingURL=bower_components/angular-loader/angular-loader.min.js.map'),indexText=fs.readFileSync(indexFile,'utf-8').split(/\\/\\/@@NG_LOADER_START@@[\\s\\S]*\\/\\/@@NG_LOADER_END@@/).join('//@@NG_LOADER_START@@\\n'+loaderText+'    //@@NG_LOADER_END@@');fs.writeFileSync(indexFile,indexText);\""
  },
  "dependencies": {
    "@angular/common": "^6.1.7",
    "@angular/compiler": "^6.1.7",
    "@angular/core": "^6.1.7",
    "@angular/forms": "^6.1.7",
    "@angular/http": "^6.1.7",
    "@angular/platform-browser": "^6.1.7",
    "@angular/platform-browser-dynamic": "^6.1.7",
    "@angular/router": "^6.1.7",
    "@angular/upgrade": "^6.1.7",
    "angular-in-memory-web-api": "^0.6.1",
    "rxjs": "^6.3.2",
    "systemjs": "^0.21.4",
    "zone.js": "^0.8.26"
  }
}
```
**index.html**

```
<!doctype html>
<html lang="en">
  <head>
    <base href="/app/">
    <meta charset="utf-8">
    <title>Google Phone Gallery</title>
    <link rel="stylesheet" href="bower_components/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="app.css" />
    <link rel="stylesheet" href="app.animations.css" />

    <script src="bower_components/jquery/dist/jquery.js"></script>

    <script src="bower_components/angular/angular.js"></script>
    <script src="bower_components/angular-animate/angular-animate.js"></script>
    <script src="bower_components/angular-resource/angular-resource.js"></script>
    <script src="bower_components/angular-route/angular-route.js"></script>
    <script src="app.module.ajs.js"></script>
    <script src="app.module.js"></script>
    <script src="app.config.js"></script>
    <script src="app.animations.js"></script>
    <script src="core/core.module.js"></script>
    <script src="core/checkmark/checkmark.filter.js"></script>
    <script src="core/phone/phone.module.js"></script>
    <script src="core/phone/phone.service.js"></script> 
    <script src="phone-list/phone-list.module.js"></script>
    <script src="phone-list/phone-list.component.js"></script>
    <script src="phone-detail/phone-detail.module.js"></script>
    <script src="phone-detail/phone-detail.component.js"></script>

    <script src="/node_modules/core-js/client/shim.min.js"></script>
    <script src="/node_modules/zone.js/dist/zone.js"></script>
    <script src="/node_modules/systemjs/dist/system.src.js"></script>
    <script src="/systemjs.config.js"></script>
    <script>
      SystemJS.import('/app/main.js');
    </script>
  </head>
  <body>

    <div class="view-container">
      <div ng-view class="view-frame"></div>
    </div>

  </body>
</html>

```

**systemjs.config.js**

```
/**
 * System configuration for Angular samples
 * Adjust as necessary for your application needs.
 */
(function (global) {
  System.config({
    paths: {
      // paths serve as alias
      'npm:': '/node_modules/'
    },
    // map tells the System loader where to look for things
    map: {
      // our app is within the app folder
      'ng-loader': '../src/systemjs-angular-loader.js',
      app: '/app',

      // angular bundles
      '@angular/core': 'npm:@angular/core/bundles/core.umd.js',
      '@angular/common': 'npm:@angular/common/bundles/common.umd.js',
      '@angular/compiler': 'npm:@angular/compiler/bundles/compiler.umd.js',
      '@angular/platform-browser': 'npm:@angular/platform-browser/bundles/platform-browser.umd.js',
      '@angular/platform-browser-dynamic': 'npm:@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js',
      '@angular/http': 'npm:@angular/http/bundles/http.umd.js',
      '@angular/router': 'npm:@angular/router/bundles/router.umd.js',
      '@angular/forms': 'npm:@angular/forms/bundles/forms.umd.js',
      '@angular/upgrade/static': 'npm:@angular/upgrade/bundles/upgrade-static.umd.js',

      // other libraries
      'rxjs':                      'npm:rxjs',
      'angular-in-memory-web-api': 'npm:angular-in-memory-web-api/bundles/in-memory-web-api.umd.js'
    },
    // packages tells the System loader how to load when no filename and/or no extension
    packages: {
      app: {
        defaultExtension: 'js',
        meta: {
          './*.js': {
            loader: 'systemjs-angular-loader.js'
          }
        }
      },
      rxjs: {
        defaultExtension: 'js'
      }
    }
  });
})(this);
```
