### ISSUE TITLE
Angular Library Unit Testing Errors with Ivy/Angular 9

### ISSUE THREAD

**Issue by tgrux** [angular/angular#36122] opened 2020-03-18 11:16 UTC
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/testing

### Is this a regression?
Yes, this was not an issue prior to Angular 9.  I’ve tried all Angular 9 patch versions.

### Description
Running Angular library unit tests via `ng test mylibrary` throws missing module errors for testbed modules. 

## 🔬 Minimal Reproduction
This is only reproducible by following these steps:
1. Start with no node_modules and run an npm install
2. Immediately run `ng test mylibrary`
3. You should see missing testbed module errors.

Work around
1. Start with no node_modules and run npm install
2. Immediately run `ng test`
3. Confirm you have all the testbed modules loaded into our root src spec files that you need in your library tests
4. Once all root test pass, run `ng test mylibrary`

I found that running ng test... writes to the the node_modules directory.  When running unit tests on library files first, it seems Ivy tree shakes out those test bed modules.  That’s my guess because of my work around.

## 🌍  Your Environment

**Angular Version:**
Angular 9, Angular CLI 9, Mac

**Comment by atscott** [comment] 2020-10-22 20:45
Thanks for reporting this issue. I was unable to reproduce this so I'm closing the issue. Please update to the most recent version to see if that resolves the problem.

If after upgrade the problem still exists in your application please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template, including complete steps to reproduce.

Steps I followed were:
1. ng new my-workspace --create-application=false
2. cd my-workspace
3. ng generate library my-lib
4. rm -rf node_modules
5. npm install
6. ng test my-lib
==> tests passed

**Closed by atscott** 2020-10-22 20:45 UTC
Labels: comp: testing
