### ISSUE TITLE
Default to `div` if no selector provided in compileHost

### ISSUE THREAD

**Issue by adamdbradley** [angular/angular#1857] opened 2015-05-13 02:42 UTC
I dynamically created a component using `loadNextToExistingLocation`, but forgot to add a selector to `@Component`, so the generated DOM element was `<undefined></undefined>`. 

Could it either default to creating a `<div>`, or throw an error if `directiveMetadata.selector` is `undefined` or `null`?

`var element = DOM.createElement(directiveMetadata.selector);`

https://github.com/angular/angular/blob/master/modules/angular2/src/render/dom/compiler/compiler.js#L44

**Comment by SekibOmazic** [comment] 2015-05-13 10:31
Throwing an exception would be better IMHO. Generating `<undefined></undefined>` or `<div></div>` is not what user expects.

**Comment by jelbourn** [comment] 2015-05-13 17:50
Dupe of #1662

**Closed by jelbourn** 2015-05-13 17:50 UTC
