### ISSUE TITLE
Template interpolation broken when loading angular with SystemJS from the a27 NPM package

### ISSUE THREAD

**Issue by georgiosd** [angular/angular#2597] opened 2015-06-17 20:25 UTC
I have a component `Welcome` which I route to `/` and it evaluates `username` in a `<p>` element. 
If I bootstrap the component directly, it all works fine.

If I render the `Welcome` component by creating a route for it and using `RouterOutlet` (tried both the standard and my custom one), I get an empty element.

I am on `alpha27`. No errors or anything in the console.

I was then trying to start from a working sample and try to break it in order to isolate the problem. I found that if I include the ng2 library files straight from `code.angularjs.org` instead of letting `SystemJS` do the work for me from my NPM repository, it all works! I assume this is not expected behavior.

index.html - SystemJS config
========================

```
<!-- Works if I include this -->
    <!--
    <script src="https://code.angularjs.org/2.0.0-alpha.27/angular2.dev.js"></script>
    <script src="https://code.angularjs.org/2.0.0-alpha.27/router.dev.js"></script>
        -->

    <script>
        System.defaultJSExtensions = true;
        System.config({
            baseURL: '/app',
            paths: {
                '*': '*.js'
            },
            map: {

                'angular2': 'lib/angular2',
                'rx': 'lib/rx'
            }
        });
        System.import('Bootstrap')
            .catch(console.log.bind(console));
    </script>
```

package.json
============

    {
      "version": "1.0.0",
      "private": true,
    
      "devDependencies": {
        "grunt": "^0.4.5",
        "grunt-bower": "^0.19.0",
        "grunt-typescript": "^0.6.2",
        "grunt-tsd": "^0.1.0",
        "grunt-contrib-copy": "^0.8.0",
    
        "typescript": "^1.5.0-beta"
      },
    
      "dependencies": {
        "angular2": "~2.0.0-alpha.27"
      }
    }

gruntfile.js
============

    module.exports = function (grunt) {
        grunt.initConfig({
            copy: {
                angular2: {
                    files: [
                        {
                            expand: true,
                            cwd: 'node_modules/angular2/',
                            src: ['*.js'],
                            dest: 'wwwroot/app/lib/angular2/'
                        },
                        {
                            expand: true,
                            cwd: 'node_modules/angular2/src/',
                            src: ['**/*.js'],
                            dest: 'wwwroot/app/lib/angular2/src/',
                            rename: function (dest, src) { return dest + src; }
                        },
                        {
                            expand: true,
                            flatten: true,
                            cwd: 'node_modules/rx/dist/',
                            src: ['*.min.js', '*.map'],
                            dest: 'wwwroot/app/lib/',
                            rename: function (dest, src) { return (dest + src).replace('.min.js', '.js'); }
                        }
                    ]
                }
            },
    });

WebApp.ts
========

    @Component({
        selector: 'fl-web-app',
        appInjector: [HttpService, AuthenticationService]
    })
    @View({
        template: `
            <router-outlet></router-outlet>
        `,
        directives: [LoggedInRouterOutlet, coreDirectives]
    })
    @RouteConfig([
        { path: '/welcome', as: 'welcome', component: Welcome },
        { path: '/login', as: 'login', component: Login }
    ])
    export class WebApp {

        constructor(private router: Router, browserLocation: BrowserLocation) {
            // we need to manually go to the correct uri until the router is fixed
            let uri = browserLocation.path();
            router.navigate(uri);
        }
    }

Welcome.ts
=========

    @Component({
        selector: "welcome"
    })
    @View({
        templateUrl: "app/welcome.html"
    })
    export class Welcome {
        username: string;
    
        constructor(private router: Router, private authenticationService: AuthenticationService) {
            this.username = "test"; // this.authenticationService.getUsername()
        }
    }

Welcome.html
==========

    <div>
        <h1>Welcome</h1>
        <p>{{ username }}</p>
    </div>

LoggedInOutlet.ts
=============

    @Directive({ selector: 'router-outlet' })
    export class LoggedInRouterOutlet extends RouterOutlet {
        static publicRoutes = {
            '/login': true
        };
    
        constructor(
            elementRef: ElementRef,
            loader: DynamicComponentLoader,
            private _parentRouter: Router,
            injector: Injector,
            @Attribute("name") nameAttr: string,
            private authenticationService: AuthenticationService) {
    
            super(elementRef, loader, _parentRouter, injector, nameAttr);
        }
    
        activate(instruction: Instruction) {
            var url = this._parentRouter.lastNavigationAttempt;
            if (!LoggedInRouterOutlet.publicRoutes[url] && !this.authenticationService.isLoggedIn()) {
                instruction.component = Login;
            }
            return super.activate(instruction);
        }
    }

Bootstrap.ts:
=========

    BrowserDomAdapter.makeCurrent();
    
    var formInjectables: Array<any> = [
        FormBuilder
    ];
    
    var hasShadowDom: boolean = Boolean(document && document.body && document.body.createShadowRoot);
    
    var shadowDomInjectables: Array<any> = !hasShadowDom ? [] : [
        bind(ShadowDomStrategy).toClass(NativeShadowDomStrategy)
    ];
    
    var jitInjectables: Array<any> = [
        bind(ChangeDetection).toClass(JitChangeDetection)
    ];
    
    bootstrap(WebApp,
        [
            formInjectables,
            routerInjectables,
            httpInjectables,
            shadowDomInjectables,
            jitInjectables
        ]);

**Comment by caitp** [comment] 2015-07-02 16:42
@georgiosd could you please create a reproduction of your issue, either a tarball or a plnkr?

**Comment by georgiosd** [comment] 2015-07-02 18:16
@caitp really sorry guys, I had to abandon the 2.0 branch for now because I wasn't making any progress. I presume this will be fixed indirectly one way or another or the above may be enough to reproduce it.

**Comment by caitp** [comment] 2015-07-02 20:22
The gruntfile doesn't even produce a build of your application and there's no info about your app structure so trying to fill in the blanks is taking too much effort, sorry dude

**Comment by georgiosd** [comment] 2015-07-02 20:53
I'll see if I can pull this version from my repo history

**Comment by naomiblack** [comment] 2015-07-13 17:16
@georgiosd I'm closing this issue as can't reproduce. Sorry, there's not enough here for us to work on.

**Closed by naomiblack** 2015-07-13 17:16 UTC
Labels: comp: build/dev-productivity, effort1: easy (hour), hotlist: community-help, P3: important, type: bug

**Comment by Belkar** [comment] 2015-10-03 18:56
If this is still a thing. That might help.
https://github.com/angular/angular/issues/4504
