### ISSUE TITLE
FormBuilder.group adds 

### ISSUE THREAD

**Issue by Mark-McCracken** [angular/angular#22974] opened 2018-03-24 21:35 UTC
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
When using the formbuilder to create a new group, if any of the values of the supplied object are arrays, they are created as a new form control. This means an array within the group gets treated as an object, and it simply uses the first item in the array, ignoring the rest of the items in the array, and not formatting the object as an array.

here is a fragment of the current tests and behaviour, from https://github.com/angular/angular/blob/master/packages/forms/test/form_builder_spec.ts:
<pre><code>
    it('should create controls from an array', () => {
      const g = b.group(
          {'login': ['some value'], 'password': ['some value', syncValidator, asyncValidator]});

      expect(g.controls['login'].value).toEqual('some value');
      expect(g.controls['password'].value).toEqual('some value');
      expect(g.controls['password'].validator).toEqual(syncValidator);
      expect(g.controls['password'].asyncValidator).toEqual(asyncValidator);
    });
</code></pre>
I think if developers are going to the extent of adding syncValidators and asyncValidators to their properties, then they should be using FormArray already in this case, which the FormBuilder API already caters for, as seen by this code, from https://github.com/angular/angular/blob/master/packages/forms/src/form_builder.ts:
<pre><code>
  /** @internal */
  _createControl(controlConfig: any): AbstractControl {
    if (controlConfig instanceof FormControl || controlConfig instanceof FormGroup ||
        controlConfig instanceof FormArray) {
      return controlConfig;

    } else if (Array.isArray(controlConfig)) {
      const value = controlConfig[0];
      const validator: ValidatorFn = controlConfig.length > 1 ? controlConfig[1] : null;
      const asyncValidator: AsyncValidatorFn = controlConfig.length > 2 ? controlConfig[2] : null;
      return this.control(value, validator, asyncValidator);

    } else {
      return this.control(controlConfig);
    }
  }
}
</code></pre>
Objects that contain values that are already instances of FormArray are properly handled.

## Expected behavior
Any nested arrays within the object passed to formbuilder.group should be treated as a formarray, rather than a form control with validation and options.
Tests might look like:
<pre><code>
    it('should create a form array from an array', () => {
      const g = b.group({'filterValues': ['some value A', 'some value B']});

      expect(g.controls['filterValues'].value).toEqual(['some value A', 'some value B']);
    });
</code></pre>
This should recursively check if object values within this also contain arrays/objects, rather than assuming simple controls.
A more complex test might looks like this:
<pre><code>
    it('should recursively check values for objects or arrays', () => {
      const g = b.group({
    'filterValues': [
        {"subFilter": ["Charlie", "Delta"]},
        {"subFilter": ["Echo", "Foxtrot"]}
    ]
    });
      expect(g.controls['filterValues'].value).toEqual([{"subFilter": ["Charlie", "Delta"]},{"subFilter": ["Echo", "Foxtrot"]}]);
    });
</code></pre>

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-hcftxd
Click the button to see the form builder building a new group from the object, which does not match the expected output.

## What is the motivation / use case for changing the behavior?
I recently created an application which had a very large form structure in it.
To keep the code maintainable, many sub-forms were broken down into their own components, and they "submitted" their form value, by emitting the form value through a @Component @Output, and it's parent form would listen to the event, and then add that object to the form group. however using the form builder, this didn't work as expected, and I needed to iterate through the submitted objects properties, checking at each stage if any of the properties were an array, and manually use FormArray to create the desired structure. This meant the form builder was not accurately providing the benefit it's designed for.

## Environment

<pre><code>
Angular version: 5.2.8
Browser:
- Chrome (desktop) version Version 65.0.3325.181
 
For Tooling issues:
- Node version: 9.7.1
- Platform:  Mac

</code></pre>

**Comment by kara** [comment] 2018-05-31 22:30
Duplicate of https://github.com/angular/angular/issues/24182 (keeping the newer one because it has a working stackblitz)

**Closed by kara** 2018-05-31 22:30 UTC
Labels: comp: forms
