### ISSUE TITLE
StaticInjectorError(Platform: core)[RouterScroller -> ViewportScroller]

### ISSUE THREAD

**Issue by pranavkumar389** [angular/angular#31425] opened 2019-07-05 10:12 UTC
Hi,

I am getting below error after updating the angular(ionic) application.

` core.js:7376 ERROR NullInjectorError: StaticInjectorError(AppModule)[RouterScroller -> ViewportScroller]: 
  StaticInjectorError(Platform: core)[RouterScroller -> ViewportScroller]: 
    NullInjectorError: No provider for ViewportScroller!
    at NullInjector.push../node_modules/@angular/core/fesm5/core.js.NullInjector.get (http://localhost:8100/vendor.js:62254:25)
    at resolveToken (http://localhost:8100/vendor.js:63623:24)
    at tryResolveToken (http://localhost:8100/vendor.js:63567:16)
    at StaticInjector.push../node_modules/@angular/core/fesm5/core.js.StaticInjector.get (http://localhost:8100/vendor.js:63471:20)
    at resolveToken (http://localhost:8100/vendor.js:63623:24)
    at tryResolveToken (http://localhost:8100/vendor.js:63567:16)
    at StaticInjector.push../node_modules/@angular/core/fesm5/core.js.StaticInjector.get (http://localhost:8100/vendor.js:63471:20)
    at resolveNgModuleDep (http://localhost:8100/vendor.js:82413:29)
    at _callFactory (http://localhost:8100/vendor.js:82481:67)
    at _createProviderInstance (http://localhost:8100/vendor.js:82433:26)
`

Part of the package.json file is 

 "@angular/animations": "^8.1.0",
    "@angular/common": "^8.1.0",
    "@angular/core": "^8.1.0",
    "@angular/forms": "^8.1.0",
    "@angular/http": "^7.2.15",
    "@angular/platform-browser": "^8.1.0",
    "@angular/platform-browser-dynamic": "^8.1.0",
    "@angular/router": "^8.1.0",
    "@ionic-native/core": "^5.9.0",
    "@ionic/angular": "^4.6.0"

**Comment by mlc-mlapis** [comment] 2019-07-05 10:43
@pranavkumar389 `ViewportScroller` is a part of `"@angular/cdk": "8.0.2"`.

**Comment by gkalpak** [comment] 2019-07-05 12:40
@mlc-mlapis, `@angular/common` has a `ViewportScroller` class (which is what `RouterScroller` uses), since `v6.<something>`: https://v6.angular.io/api/common/ViewportScroller

**Comment by pranavkumar389** [comment] 2019-07-05 13:12
@mlc-mlapis I am not using ` ViewportScroller ` anywhere in my application. Just wondering why I am getting this error.
If ` ViewportScroller ` is part of any other dependency, it should be present in the package by itself.
Correct me if I am going wrong.

**Comment by pranavkumar389** [comment] 2019-07-05 13:21
> @pranavkumar389 `ViewportScroller` is a part of `"@angular/cdk": "8.0.2"`.

I am using ` @angular v >8.0.2 ` which is ` 8.1.0 `.

**Comment by bjcCin** [comment] 2019-07-05 13:39
Same issue here after install @angular/cdk

**Comment by mlc-mlapis** [comment] 2019-07-05 14:01
@gkalpak ... ah, sure. You were right, of course. I was too fast.

**Comment by gkalpak** [comment] 2019-07-05 14:18
@pranavkumar389, is sounds like either an issue with ionic or (more likely) a configuration issue in your app.
It is impossible to tell without a minimal reproduction to investigate.

**Comment by pranavkumar389** [comment] 2019-07-06 05:40
Spend one whole day, unfortunately, couldn't get a solution to the issue.
Downgraded the angular packages to 7XX. And now it's worked.

**Comment by seyedghasemhosseiny** [comment] 2019-07-08 09:36
> @mlc-mlapis I am not using `ViewportScroller` anywhere in my application. Just wondering why I am getting this error.
> If `ViewportScroller` is part of any other dependency, it should be present in the package by itself.
> Correct me if I am going wrong.

i have same problem

**Comment by gkalpak** [comment] 2019-07-08 11:05
I am going to close this, because there is not sufficient information for us to understand and reproduce the problem. (Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.)

As mentioned in https://github.com/angular/angular/issues/31425#issuecomment-508773544, my best guess is that it is not a problem in Angular itself (but, again, we can't be sure).

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.

**Closed by gkalpak** 2019-07-08 11:05 UTC

**Comment by rikkepeterzen** [comment] 2019-07-10 13:28
I get the same error after `yarn upgrade @angular/cli @angular/core`

I added the following in app.component.ts:

`constructor(private ViewportScroller: ViewportScroller){
this.viewportscroller;
}`

The error is gone, but probably not the best fix. I can't figure out how the error is triggered, when I'm not using the ViewportScroller.

**Comment by Hasan-git** [comment] 2019-07-11 12:19
> I get the same error after yarn upgrade @angular/cli @angular/core

same issue

![image](https://user-images.githubusercontent.com/8820596/61049940-76ab6a00-a3ee-11e9-8bde-0124a7ae97ba.png)

**Comment by YosiLeibman** [comment] 2019-07-12 10:40
smae issue, after adding @angular/material to my project,
1. i got error that @angular/animation not same version as @angular/core, so i updated (I'm using NPM).
2. I'm getting this error.

**Comment by bharathism04** [comment] 2019-07-16 04:29
![image](https://user-images.githubusercontent.com/17472606/61265924-33674780-a7b0-11e9-8138-c77625543862.png)


this error when i am using ngx-mat-file-input concept 
please tell the solutions

**Comment by zimcoder** [comment] 2019-07-16 10:55
> I get the same error after `yarn upgrade @angular/cli @angular/core`
> 
> I added the following in app.component.ts:
> 
> `constructor(private ViewportScroller: ViewportScroller){ this.viewportscroller; }`
> 
> The error is gone, but probably not the best fix. I can't figure out how the error is triggered, when I'm not using the ViewportScroller.

That code snippet seems incomplete.. it's not making sense to me.

**Comment by zimcoder** [comment] 2019-07-16 10:56
Getting the same error, whats going on?

**Comment by acteralex** [comment] 2019-07-16 11:43
I have the same issue (not an ionic, pure angular app).

**Comment by chantimothy** [comment] 2019-07-17 03:49
Actually Just updated to Angular 8 and am getting the same issue. Tried everything but to downgrade the version, nothing works....

**Comment by gkalpak** [comment] 2019-07-17 15:21
I see several people reporting they are affecteced by this issue, but still no reproduction 😞 (see https://github.com/angular/angular/issues/31425#issuecomment-509181456).
If anyone can provide a minimal reproduction, we would be able to investigate the problem 🤷‍♂

**Comment by rikkepeterzen** [comment] 2019-07-17 16:15
> I see several people reporting they are affecteced by this issue, but still no reproduction 😞 (see [#31425 (comment)](https://github.com/angular/angular/issues/31425#issuecomment-509181456)).
> If anyone can provide a minimal reproduction, we would be able to investigate the problem 🤷‍♂

The only thing I did, was to run: `yarn upgrade @angular/cli @angular/core` and then I got the error about the ViewportScroller. I don't even use a ViewportScroller. Before the Yarn upgrade, everything worked and no errors.

**Comment by gkalpak** [comment] 2019-07-17 16:39
Thx for the extra info @rikkepeterzen. This still doesn't happen to all apps and we can't investigate without knowing what your app looks like. If you could prepare a minimal reproduction (e.g. a sample repo we can check out and run the upgrade command to see the problem ourselves), we could investigate and find out what is causing this.

**Comment by chantimothy** [comment] 2019-07-17 18:05
Sorry I cannot provide any more help then needed... I was reading a tutorial on drag and drop on material and there is a function that requires cdk8 and so I did an upgrade and found out I will also need to upgrade the core. and so I follow the instruction and do npm upgrade @angular/cli @angular/core. then I notice the issue start occuring. I have tried to upgrade the angular router too but it is still giving out the error. 

I am sorry it is very vague but this is all I can provide as the error message was not very clear as well.

**Comment by gkalpak** [comment] 2019-07-17 18:28
@chantimothy, what version of `@angular/*` packages do you have in `package.json` after the upgrade?

**Comment by chantimothy** [comment] 2019-07-17 18:32
> @chantimothy, what version of `@angular/*` packages do you have in `package.json` after the upgrade?

"@angular/animations": "^7.2.15",
    "@angular/cdk": "^8.1.1",
    "@angular/common": "^8.1.1",
    "@angular/compiler": "^8.1.1",
    "@angular/core": "^8.1.1",
    "@angular/elements": "^7.2.15",
    "@angular/forms": "^7.2.15",
    "@angular/http": "^7.2.15",
    "@angular/material": "^8.1.1",
    "@angular/platform-browser": "^7.2.15",
    "@angular/platform-browser-dynamic": "^7.2.15",
    "@angular/router": "^8.1.1",
    "@auth0/angular-jwt": "^2.1.1",
    "@nguniversal/express-engine": "^7.1.0",
    "@types/socket.io": "^2.1.2",
    "@webcomponents/custom-elements": "^1.2.4",
    "angular-google-charts": "0.0.9",
    "core-js": "^2.6.9",
    "document-register-element": "^1.13.2",
    "express": "^4.17.1",
    "hammerjs": "^2.0.8",
    "multer": "^1.3.1",
    "ngx-cookie": "^4.1.2",
    "ngx-infinite-scroll": "^7.2.0",
    "ngx-quill": "^3.2.0",
    "ngx-smart-modal": "^7.1.1",
    "ngx-socket-io": "^2.1.1",
    "ngx-toastr": "^8.8.0",
    "quill": "^1.3.6",
    "quill-image-resize-module": "^3.0.0",
    "quill-image-upload": "^0.1.2",
    "raven-js": "^3.27.2",
    "rxjs": "^6.5.2",
    "rxjs-compat": "^6.5.2",
    "socket.io": "^2.2.0",
    "zone.js": "^0.9.1"

I am trying to upgrade the @angular modules one by one as I am new to development and I don't know how to upgrade the entire @angular modules

**Comment by gkalpak** [comment] 2019-07-17 19:12
@chantimothy, upgrading the Angular packages one by one won't work. The Angular framework packages need to be on the same version. So, based on your `package.json`, the following packages should be on the same version:

- @angular/animations`
- `@angular/common`
- `@angular/compiler`
- `@angular/core`
- `@angular/elements`
- `@angular/forms`
- `@angular/http` (<-- You shouldn't be using that any more. Use [HttpClient](https://angular.io/guide/http) instead.)
- `@angular/platform-browser`
- `@angular/platform-browser-dynamic`
- `@angular/router`

Also, `@angular/compiler-cli` and `@angular/language-service`, which might be in your `devDependencies`, must also be on the same version as the rest.

Then, there are the Angular Material (aka `components`), which also need to be on the same version with each other (but can defer in minor/patch from the core Angular packages:

- `@angular/cdk`
- `@angular/material`

##
Theoretically, `ng upgrade @angular/core` and `ng upgrade @angular/material` should automatically take care of this for you, upgrading all necessary packages to the same versions.

**Comment by chantimothy** [comment] 2019-07-18 18:08
> @chantimothy, upgrading the Angular packages one by one won't work. The Angular framework packages need to be on the same version. So, based on your `package.json`, the following packages should be on the same version:
> 
> * @angular/animations`
> * `@angular/common`
> * `@angular/compiler`
> * `@angular/core`
> * `@angular/elements`
> * `@angular/forms`
> * `@angular/http` (<-- You shouldn't be using that any more. Use [HttpClient](https://angular.io/guide/http) instead.)
> * `@angular/platform-browser`
> * `@angular/platform-browser-dynamic`
> * `@angular/router`
> 
> Also, `@angular/compiler-cli` and `@angular/language-service`, which might be in your `devDependencies`, must also be on the same version as the rest.
> 
> Then, there are the Angular Material (aka `components`), which also need to be on the same version with each other (but can defer in minor/patch from the core Angular packages:
> 
> * `@angular/cdk`
> * `@angular/material`
> 
> Theoretically, `ng upgrade @angular/core` and `ng upgrade @angular/material` should automatically take care of this for you, upgrading all necessary packages to the same versions.

Hello and thank you for clarifying, I have ran the `ng upgrade` it just gave the same error because I am not too sure that it actually updated all the necessary package. what DID work at the end was that I took your advice and modify the package.json so the version of the package version that you have mentioned are consistent. THEN i do `npm install` , that is what fixed the issue.

**Comment by gkalpak** [comment] 2019-07-18 18:55
Thx for the following up, @chantimothy. Maybe `ng upgrade` was confused by the fact that some packages were on different versions than others. Normally that would never happen.

Glad you were able to sort it out anyway.

##
To everyone getting this error: Make sure you Angular packages are on the same version :smiley:

**Comment by rikkepeterzen** [comment] 2019-07-25 08:10
Thanks @gkalpak , it worked :)

**Comment by panic-coder** [comment] 2019-08-05 07:17
Just make sure that whatever version of angular cli u are using should be same for angular core, material and the other dependencies. If the version differs then there is a problem with the dependencies.

**Comment by dcolakchile** [comment] 2019-08-30 19:37
Same problem here. Upgraded angular and everything just exploded.

NullInjectorError: StaticInjectorError(AppModule)[RouterScroller -> ViewportScroller]: 
core.js:4002
message:"StaticInjectorError(AppModule)[RouterScroller -> ViewportScroller]: \n  StaticInjectorError(Platform: core)[RouterScroller -> ViewportScroller]: \n    NullInjectorError: No provider for ViewportScroller!"
name:"NullInjectorError"
ngTempTokenPath:null
ngTokenPath:Array(2) ["RouterScroller", ]

People, we live in constant fear of updating anything!!! 

Stop breaking everything with each new update!!!

**Comment by chantimothy** [comment] 2019-08-30 20:54
@dcolakchile Try following the solution proposed to me up this tread. I had the exact problem after upgrading angular, it was proposed that all angular related package should use the same version. after that the project runs fine again.

**Comment by sesharathnamani** [comment] 2019-09-03 04:01
@dcolakchile 
Today i faced same error. I tried "ng update @angular/cli @angular/core" . It automatically updated required angular packages and error disappeared.  You can also refer https://stackoverflow.com/questions/56879099/nullinjectorerror-no-provider-for-viewportscroller

**Comment by officialsharmaji** [comment] 2019-09-06 11:52
I did `ng update --all --force` and it fixed the issue. 
In case you get issue with respect to Typescript version, please decrease the version and run npm i.

**Comment by grimace** [comment] 2019-09-23 14:12
same problem here.  seems like every release brings more breaking changes.
