### ISSUE TITLE
provide a 'DateValueAccessor' for input[type=date]

### ISSUE THREAD

**Issue by Barbiero** [angular/angular#48286] opened 2022-11-29 19:36 UTC
### Which @angular/* package(s) are relevant/related to the feature request?

forms

### Description

Currently, we have a specialized [NumberValueAccessor](https://angular.io/api/forms/NumberValueAccessor) that can be used to bind FormControls with `input[type=number]`.

### Proposed solution

It would be nice if we could have a `DateValueAccessor` that supported `input[type=date]`. Would be extra nice if we could also get similar accessors for `input[type=datetime-local]`, `input[type=time]`, `input[type=month]`  and others, though it's understandable if these are lower priority given that Firefox doesn't support them properly. With the `Temporal` api on the horizon, I feel like this is specially important.

### Alternatives considered

simply treating date inputs as string is definitely doable. Implementing the directive [ourselves](https://coryrylan.com/blog/using-html5-date-input-with-date-objects-and-angular) could also be a solution; this issue is mostly because I feel like this is warranted to be part of baseline Angular.

**Comment by JeanMeche** [comment] 2024-04-09 20:23
Hi, this is basically a duplicate of #8203. Let's continue the discussion over there.

**Closed by JeanMeche** 2024-04-09 20:23 UTC
Labels: feature, area: forms, feature: insufficient votes
