### ISSUE TITLE
Aot template verification

### ISSUE THREAD

**Issue by mdaveynis** [angular/angular#13658] opened 2016-12-23 04:57 UTC
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
ngc produces not validated (un-typed) context within embedded template directives like *ngIf, *ngFor, etc.

1. Validated context (produces error when running ngc - expected behavior):
```ts
@Component({
  selector: 'my-app',
  template: '<h1>{{errorProperty}}</h1>'
})
export class AppComponent { }
```

2. Not validated context (does not produce error when running ngc - unexpected behavior):
```ts
@Component({
  selector: 'my-app',
  template: '<div *ngIf="false">{{errorProperty}}</div>'
})
export class AppComponent { }
```

**Expected behavior**
ngc produces error in the second example above.

**Minimal reproduction of the problem with instructions**
Run ngc with above examples 1 and 2.

**What is the motivation / use case for changing the behavior?**
Detects errors in complex templates during compile time. 

**Please tell us about your environment:**

* **Angular version:** 2.4.1

* **Browser:** N/A

 
* **Language:** [TypeScript 2.0.10 | ES6]

* **Node (for AoT issues):** `node --version` =   5.3.0

**Comment by DzmitryShylovich** [comment] 2016-12-23 18:29
Duplicate of https://github.com/angular/angular/issues/12398

**Closed** 2016-12-23 18:35 UTC
