### ISSUE TITLE
Feature: Variable for intermediate ngFor Pipe result

### ISSUE THREAD

**Issue by dominique-mueller** [angular/angular#8672] opened 2016-05-16 12:34 UTC
**Feature**

In Angular 1 it was possible to store the intermediate result of a filtered ngFor. Since v1.3 beta17 it's even easier by using an alias expression. See the docs here: https://code.angularjs.org/1.3.0-beta.17/docs/api/ng/directive/ngRepeat. But in Angular 2 this feature seems to be missing.

**Use case as an example**

My (example) use case: I'm using a pipe to filter a list of items depending on a search text. When the result list is empty, I want to be able to notify the user about this empty state, e.g. with a text "No search results." or similar. In addition, it would be nice to show the number of found search results at any time. In Angular 1, I was able to save the intermediate filter result in a variable and work with its length property to achieve this.

Will this feature be coming in Angualr 2 or should we better not use a Pipe in this case? Although I think a Pipe is the nicest solution here.

**Comment by zoechi** [comment] 2016-05-23 10:18
Looks like a dup of #2451

**Comment by pkozlowski-opensource** [comment] 2016-06-02 17:23
It is indeed duplicate of #2451, thnx @zoechi

**Closed by pkozlowski-opensource** 2016-06-02 17:23 UTC
