### ISSUE TITLE
Issue: Docs or angular.io Bug Report

### ISSUE THREAD

**Issue by dimOk00** [angular/angular#53577] opened 2023-12-14 20:29 UTC
### Describe the problem that you experienced

Page https://angular.dev/api/common#pipes does not exist, there is a reference to it from docs

### Enter the URL of the topic with the problem

 https://angular.dev/api/common#pipes

### Describe what you were looking for in the documentation

Documentation about pipes

### Describe the actions that led you to experience the problem

Clicked pipes full documentation in this page https://angular.dev/guide/pipes

**Comment by JoostK** [comment] 2023-12-14 20:36
Thanks for the report, closing as duplicate of https://github.com/angular/angular/issues/52968.

**Closed by JoostK** 2023-12-14 20:36 UTC
