### ISSUE TITLE
Use of input transformation is not considered in Angular language service

### ISSUE THREAD

**Issue by MikaStark** [angular/angular#50990] opened 2023-07-10 13:25 UTC
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

Hi !
If you use `transform` on an `@Input` and having Angular Language Service enabled on VSCode you get an error from the template telling that string cannot be affected to the desired type (boolean for instance). In fact, it only work if you mark your input as potential `String` but it may be not wanted.

```ts
@Component({
  selector: 'app-child',
  standalone: true,
  imports: [CommonModule],
  template: `<pre>{{ disabled | json }}</pre>`,
})
export class ChildComponent {
  @Input({ transform: booleanAttribute })
  disabled = false;
}

@Component({
  selector: 'app-host',
  standalone: true,
  imports: [ChildComponent],
  template: `<app-child disabled />`, // <--- Type 'string' is not assignable to type 'boolean'.ngtsc(2322)
})
export class HostComponent {}
```

You will not get any error on the provided Stackblitz as it doesn't use ALS. You have to download the project and open it on VSCode.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-u5b5z4?file=src%2Fmain.ts

### Please provide the exception or error you saw

```true
Type 'string' is not assignable to type 'boolean'.ngtsc(2322)
```
```


### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 16.1.4
Node: 18.16.0
Package Manager: npm 9.7.2
OS: win32 x64

Angular: 16.1.4
... animations, cdk, cli, common, compiler, compiler-cli, core
... elements, forms, material, material-date-fns-adapter
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1601.4
@angular-devkit/build-angular   16.1.4
@angular-devkit/core            16.1.4
@angular-devkit/schematics      16.1.4
@schematics/angular             16.1.4
rxjs                            7.8.1
typescript                      5.1.6
```

**Comment by ivanwonder** [comment] 2023-07-11 12:16
Duplicate of https://github.com/angular/vscode-ng-language-service/issues/1897

The input transform is introduced in version 16.1.0,  waiting for the team to release the new VSCode extension.

**Closed** 2023-07-12 07:07 UTC
