### ISSUE TITLE
Angular 12.2.14 version's Changelog is missing 

### ISSUE THREAD

**Issue by shravansofts** [angular/angular#44475] opened 2021-12-14 04:44 UTC
### Description

Angular 12.2.14 version's Changelog is missing in the changelog.md file.

**Comment by dylhunn** [comment] 2022-01-04 20:20
@atscott Since you fixed the identical bug for 13.0, do you know why this is happening?

**Comment by atscott** [comment] 2022-01-04 21:04
@dylhunn The cause for this is likely different from what I fixed. https://github.com/angular/angular/commit/532d7d436fa1e7a1ea97ea3288f0f6c6c4e34b71 _accidentally_ deleted some releases from the changelog. They were restored in my https://github.com/angular/angular/commit/4f7a838e9d0d1c59a18839ecc9b8db8e0927490e change as a side effect of needing to add an additional breaking change note to the v13 release.

The missing 12.2.14 and 12.2.15 release notes are likely due to a missed/failed step in the release process where we cherrypick the commit from `12.2.x` to `master`. I've found this step doesn't always succeed with the tool so I've needed to do it manually in the past. This might also have something to do with being the LTS branch.

resolving in #44619

**Closed** 2022-01-07 18:09 UTC
Labels: comp: docs
