### ISSUE TITLE
@angular/Core gives "Uncaught TypeError: Cannot read property 'type' of null"

### ISSUE THREAD

**Issue by cortopy** [angular/angular#11076] opened 2016-08-25 16:04 UTC
**I'm submitting a ...**  (check one with "x")

```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When I install @angular/core in a npm linked package I get the error message:

```
Uncaught TypeError: Cannot read property 'type' of null
```

**Expected/desired behavior**
Either the error message is more specific or I should be able to install @angular/core without a problem

**Reproduction of the problem**
I'm afraid I can't replicate with plunkr as it's to do with an npm linked package.

I've spent some hours getting to the cause of the problem and this is what I found:
1. I have a ngModule in my web app
2. It works great
3. I decide to move this ngModule somewhere else in my computer so that I can use with other web apps
4. I install it in my app with `npm link` (no single line of code has been edited)
5. App doesn't work anymore. I get the error:

```
Uncaught TypeError: Cannot read property 'type' of null

(anonymous function)    @   metadata_resolver.js:698
getTransitiveModules    @   metadata_resolver.js:697
CompileMetadataResolver._getTransitiveNgModuleMetadata  @   metadata_resolver.js:411
CompileMetadataResolver.getNgModuleMetadata @   metadata_resolver.js:283
RuntimeCompiler._compileComponents  @   runtime_compiler.js:150
RuntimeCompiler._compileModuleAndComponents @   runtime_compiler.js:72
RuntimeCompiler.compileModuleAsync  @   runtime_compiler.js:49
PlatformRef_._bootstrapModuleWithZone   @   application_ref.js:368
PlatformRef_.bootstrapModule    @   application_ref.js:361
(anonymous function)    @   main.ts:4
__webpack_require__ @   bootstrap 7768849…:586
fn  @   bootstrap 7768849…:109
(anonymous function)    @   main.js:7
__webpack_require__ @   bootstrap 7768849…:586
webpackJsonpCallback    @   bootstrap 7768849…:21
(anonymous function)    @   main.js:1
```

With that stack trace I was expecting it would be something with webpack or typescript. However no errors are presented in the console.
After A LOT of trial and error (I find this error message impossible to debug) I have found that I can remove `@angular/core` from my npm linked package and web app works again. The weird thing is that all the other @angular packages are installed in the package and they don't seem to cause conflict.

Right now, what I've done is remove @angular/core from the npm linked package. At least that makes app to work again. However this gives Typescript errors as @angular/core nowhere to be found in the npm linked package.

**What is the expected behavior?**
No conflict with @angular/core

**What is the motivation / use case for changing the behavior?**
Being able to use ngModules as npm linked packages

**Please tell us about your environment:**
- **Angular version:** 2.0.0-rc.5
- **Browser:** [ Chrome XX ] 
- **Language:** [ TypeScript 2]

**Comment by pkozlowski-opensource** [comment] 2016-08-25 17:34
Could you please try to see what is _minimal_ application / code that causes this? I _think_ that this is "simply" a matter of a packaging tool not finding imports from `@angular/core`. To confirm you could console.log whatever you are importing from `@angular/core` to see if it is defined or not.

From the stack-trace I think that the offensive import is `import {NgModule} from "@angular/core";` where `NgModule` comes back as undefined. This is the root cause and needs to be fixed on your side (folder structure, tooling setup etc.).

But I agree that we should improve the error message, I will look at the following case:

```typescript
@NgModule({
    imports: [undefined]
})
class MyModule {
}  
```

but I can't guarantee that it will fix _your_ problem - you will have to check / confirm if my hypothesis is correct.

**Comment by pkozlowski-opensource** [comment] 2016-08-25 17:43
Hmm, actually it seems like we correctly handle this situation already: 

```typescript
@NgModule({
    imports: [undefined]
})
class MyModule {
}  
```

**Comment by cortopy** [comment] 2016-08-26 11:09
thanks @pkozlowski-opensource for the suggestion. If that's how it's implemented, that would explain why it's a TypeError instead of ReferenceError for example.

However, this is what my ngModule looks now and I still get the exact same Error type and message:

I've tried the following scenarios to eliminate as many suspects as possible:

1. Empty object

 ```javascript
@NgModule({
})
export class BtsAngularModule { }
 ```

2. Empty imports array

 ```javascript
@NgModule({
  imports: [],
  exports: []
})
export class BtsAngularModule { }
 ```
3. Basic angular module import

 ```javascript
import { ReactiveFormsModule }        from "@angular/forms";

@NgModule({
  imports: [ReactiveFormsModule],
  exports: [ReactiveFormsModule]
})
export class BtsAngularModule { }
 ```

In all three cases, I get the same null TypeError.

And, in all three cases removing `@angular/core` from the linked module makes the error go away and the app works fine. Typescript complains that `@angular/core` is referenced but not installed. I'm guessing Webpack is packaging it anyway as it is part of the main app, and so the external module can run fine as ngModule in the browser.

**Comment by Caballerog** [comment] 2016-08-26 12:22
I've the same problem that @cortopy.

**Comment by Caballerog** [comment] 2016-08-26 17:40
I've done some test and I think that the problem is with the **symbolic links** and NgModule.

**Comment by t0f3rchr15** [comment] 2016-08-30 15:11
@Caballerog That would match the issues I've been having. I am using npm link to add my module to the project and though the linked code is available to the dev server (angular-cli@webpack) NgModule can't seem to find it and I get the TypeError. If I remove the import, my application loads without issue.

**Comment by Caballerog** [comment] 2016-08-30 15:57
@t0f3rchr15 I've copy my modules without use `npm link` and this work (`npm install` or copy in node_modules). I've had problems when I've use `npm link` and` ln -s `(NIX). I think that is a bug from `@NgModules`.

**Comment by ramirezd42** [comment] 2016-08-30 16:22
Can confirm. This happens to me only with modules that I'm developing locally via running `npm link`

**Comment by TroelsL** [comment] 2016-08-30 20:56
I got this same error from (obviously incorrectly) adding a non-module service to imports of my module. A better error message (incorrect module declaration or not a module) would have saved a lot of time.

**Comment by jmbarbier** [comment] 2016-08-31 17:15
This issue may be related to webpack resolving symbolic links (the problem was not triggered using systemjs) :  https://github.com/webpack/webpack/issues/1643 or https://github.com/webpack/webpack/issues/554

Installing without `npm link` , using `npm install ../../xxx` resolves the issue. But the message "Uncaught TypeError: Cannot read property 'type' of null" is a bit cryptic, but i think this is already addressed in another issue (?)

**Comment by cortopy** [comment] 2016-09-08 11:51
@jmbarbier is right that in the end it turned out to be an issue with Webpack.

Webpack 2 handles module resolution MUCH MUCH better!! Just upgraded and the issue is gone. 

I think I rather leave the issue open though, as it has the "error messages" label and I still think the error message is quite obscure.

**Comment by DzmitryShylovich** [comment] 2017-02-26 08:24
@cortopy can you add a reproduction so we can improve the error message? thanks

**Comment by cortopy** [comment] 2017-03-03 11:36
@DzmitryShylovich I can't remember the details of this. It's been such a long time. But it had to do with npm linked modules, so I wouldn't be able to replicate

**Comment by DzmitryShylovich** [comment] 2017-03-03 11:39
@cortopy then I think you should close this. We can't do anything without reproduction :(

**Comment by DzmitryShylovich** [comment] 2017-03-10 12:30
@pkozlowski-opensource there's nothing we can do without repro. can be closed

**Closed** 2017-05-12 18:26 UTC
Labels: hotlist: error messages
