### ISSUE TITLE
docs(content): example - directive with ngAfterContentInit - seems incorrect

### ISSUE THREAD

**Issue by wardbell** [angular/angular#10134] opened 2016-07-18 08:41 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request 
```

**Current behavior**
See [API guide for `ContentChild`](https://angular.io/docs/ts/latest/api/core/index/ContentChild-var.html).

The example in that guide page attempts to illustrate `ContentChild` by showing a **directive** that extracts child content.

How does a directive - which lacks a template - extract child content (or a child view)? From what? The example itself is unclear, perhaps nonsense?

It did reveal that `ngAfterContent...` and `ngAfterView...` hooks are called on a directive. **Why?**  How would I use them?

This all came up in [an issue filed in `angular.io` ](https://angular.io/docs/ts/latest/api/core/index/ContentChild-var.html) about our lifecycle hook documentation where I asserted that these hooks really don't apply to directives. 

I replied with some sample code there ... code that is a slight tweak of that documentation [chapter's plunker](https://angular.io/resources/live-examples/lifecycle-hooks/ts/plnkr.html).

Can elaborate if need be.

**Comment by vicb** [comment] 2016-10-06 22:06
duplicate of https://github.com/angular/angular/issues/10221

**Closed by vicb** 2016-10-06 22:06 UTC
Labels: comp: core & compiler, comp: docs
