### ISSUE TITLE
ASSERTION ERROR trying to render a component with its factory coming from an Angular Element

### ISSUE THREAD

**Issue by BossOz** [angular/angular#38592] opened 2020-08-26 14:08 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/core

### Is this a regression?

 Not tested

### Description

The error is thrown trying to render a component using its factory that is resolved inside an angular element and only if there are *ngIf in the template.

## 🔬 Minimal Reproduction

Here a little test project.
[https://github.com/BossOz/element-rendering-test](https://github.com/BossOz/element-rendering-test)

## 🔥 Exception or Error
<pre><code>
core.js:6241 ERROR TypeError: Cannot read property 'bindingStartIndex' of null
    at Module.ɵɵelementStart (core.js:21266)
    at ToolbarComponent_Template (toolbar.component.html:1)
    at executeTemplate (core.js:12169)
    at renderView (core.js:11939)
    at renderComponent (core.js:13518)
    at renderChildComponents (core.js:11740)
    at renderView (core.js:11965)
    at ComponentFactory$1.create (core.js:34111)
    at AppComponent.loadToolbar (app.component.ts:88)
    at AppComponent_Template_button_click_1_listener (app.component.html:3)
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.1.12
Node: 10.13.0
OS: win32 x64

Angular: 9.1.12
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.12
@angular-devkit/build-angular     0.901.12
@angular-devkit/build-optimizer   0.901.12
@angular-devkit/build-webpack     0.901.12
@angular-devkit/core              9.1.12
@angular-devkit/schematics        9.1.12
@angular/elements                 10.0.12
@ngtools/webpack                  9.1.12
@schematics/angular               9.1.12
@schematics/update                0.901.12
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0
</code></pre>

**Anything else relevant?**
Nope

**Comment by BossOz** [comment] 2020-08-26 14:39
**UPDATE**
This error is thrown ALWAYS if used the `ComponentFactoryResolver` coming from the `test-app`.

If we use the factory resolver injected in the angular element the error change:

```
ASSERTION ERROR: Index expected to be less than 0 but got 21 [Expected=> 0 < 21 <=Actual]
    at throwError (core.js:1344)
    at assertLessThan (core.js:1315)
    at assertDataInRange (core.js:1355)
    at selectIndexInternal (core.js:9744)
    at Module.ɵɵadvance (core.js:9722)
    at ToolbarComponent_Template (toolbar.component.html:3)
    at executeTemplate (core.js:12169)
    at refreshView (core.js:12008)
    at refreshComponent (core.js:13458)
    at refreshChildComponents (core.js:11729)
```

**Comment by AndrewKushnir** [comment] 2020-08-26 17:15
Hi @BossOz, thanks for reporting the issue and providing a repro. I looked at the code in Github repository that you shared and I believe it can be simplified a bit more to have just the essential parts. Could you please help simplify it further (keep just one app, remove all non-essential code) to speed up additional investigation? Thank you.

**Comment by BossOz** [comment] 2020-08-27 07:47
Hello @AndrewKushnir!
The `custom-element` app is an Angular Element where the `ToolbarComponent` is coming from.
The `test-app` is the "main" one (to serve), where I want to render the `ToolbarComponent`.

This is my use case. 
I will try to reproduce the error with a simpler example but I need more time.

**Comment by omanzelli** [comment] 2020-08-27 11:29
@AndrewKushnir 
I tried to simplify the project without success. The issue is not present without the Angular Element.

**Comment by BossOz** [comment] 2020-08-27 11:35
> Hi @BossOz, thanks for reporting the issue and providing a repro. I looked at the code in Github repository that you shared and I believe it can be simplified a bit more to have just the essential parts. Could you please help simplify it further (keep just one app, remove all non-essential code) to speed up additional investigation? Thank you.

I tried to simplify the project without success. The error is thrown exactly with this configuration.

**Comment by AndrewKushnir** [comment] 2020-11-04 18:35
Hi @BossOz, I've checked the repro again and it looks like there is a lot of code in https://github.com/BossOz/element-rendering-test/blob/master/projects/test-app/src/app/app.component.ts that can be simplified (i.e. please keep only the relevant parts needed for a repro) and also there might be some simplification in the following folders:
- https://github.com/BossOz/element-rendering-test/tree/master/projects/test-app/src/app/element-container
- https://github.com/BossOz/element-rendering-test/tree/master/projects/custom-element/src/app

We wouldn't be able to investigate the problem with the current state of the repro, so I'm closing this ticket for now. Feel free to reopen or create a new one once simplified version of the repro is available.

Thank you.

**Closed by AndrewKushnir** 2020-11-04 18:35 UTC
Labels: comp: core, core: DOM rendering, core: content projection, core: ng-template and *microsyntax, needs clarification, type: bug/fix
