### ISSUE TITLE
httpRequest for a post requestType has a type error and is not resolving to the correct type

### ISSUE THREAD

**Issue by xtianus79** [angular/angular#37812] opened 2020-06-28 22:59 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....
Angular 9

### Is this a regression?
yes

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...
As an example: The following code emits a type error that is not accurate upon using the requestType setting of 'text' or otherwise. As a result you have to ignore the type error which is clearly apart of the overloads but perhaps there is something wrong with the way it is not set to optional like the other choices and or the in general confusion on how you work with responses in the first place.  A little too much sugar here in my opinion.

```javascript
    /** POST: add a new user to the database */
  getConversationToken (userProfile: any): Observable<any> {
    const options = {
      headers: new HttpHeaders()
                  .set('Content-Type', 'application/json'),
      params: new HttpParams()
                  .append('code', 'xxxxxxxx=='),
      responseType: 'text'
    }
    //@ts-ignore
    return this.http.post<any>(`${this.xxxxxxx}`, userProfile, options)
      .pipe(
        catchError(this.handleError('xxxxxx', userProfile))
      );
  }
```

## 🔬 Minimal Reproduction

 https://stackblitz.com/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by JoostK** [comment] 2020-06-29 06:28
This is working as intended and can easily be achieved without the `@ts-ignore`. The `HttpClient.post` overloads require that the options object uses string literals to specify the type of response. Once you pull out the options object into a variable, TypeScript will infer the type of the `responseType` property to be string, instead of the string literal type. You can hint TypeScript to keep the string literal as its string literal type.

You can cast the `'text'` literal as `const`, which will retain the string literal type:

```ts
    const options = {
      headers: new HttpHeaders()
                  .set('Content-Type', 'application/json'),
      params: new HttpParams()
                  .append('code', 'xxxxxxxx=='),
      responseType: 'text' as const,
    };
```

There have been attempts in the past to clean up the signature overloads, but they were mostly unsuccessful due to IDE restrictions. See #21962 and https://github.com/angular/angular/issues/34318#issuecomment-580536460.

**Comment by jelbourn** [comment] 2020-10-09 20:36
Closing since this seems to be working as intended

**Closed by jelbourn** 2020-10-09 20:36 UTC
Labels: comp: common/http, flag: can be closed?
