### ISSUE TITLE
Timing-function sometimes gets ignored in safari

### ISSUE THREAD

**Issue by SlateDave** [angular/angular#37440] opened 2020-06-04 17:50 UTC
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/animations

### Description
I'm trying to build a animation with angular animations, but if I choose a custom cubic-bezier timing function, it sometimes gets ignored in apple's safari browser (desktop and mobile).

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-ivy-qyj9rv

Chrome's behavior:
![Chrome](https://user-images.githubusercontent.com/26907265/83793119-62bec580-a69c-11ea-81fd-9e41ca1b2ac4.gif)

Safari's behavior:
![Safari](https://user-images.githubusercontent.com/26907265/83793131-67837980-a69c-11ea-89da-2101e4c8caf5.gif)

## 🌍  Your Environment

<pre><code>Angular CLI: 9.1.3
Node: 12.14.1
OS: darwin x64

Angular: 9.1.3
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.3
@angular-devkit/build-angular     0.901.3
@angular-devkit/build-optimizer   0.901.3
@angular-devkit/build-webpack     0.901.3
@angular-devkit/core              9.1.3
@angular-devkit/schematics        9.1.3
@ngtools/webpack                  9.1.3
@schematics/angular               9.1.3
@schematics/update                0.901.3
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0</code></pre>

**Comment by sebaferreras** [comment] 2020-06-07 14:46
@SlateDave I found the same issue some time ago and, as far as I can tell, it doesn't happen _sometimes_ but **every time the animation involves adding or removing an element from the DOM** as part of the animation.

Please take a look at this demo: https://stackblitz.com/edit/angular-animations-safari

And also please take a look at [this demo video of the issue](https://www.dropbox.com/s/xhs0dbq4y5yp24w/Safari-Animation-Bug.mp4?dl=0).

In the Stackblitz project, I created a very simple component with 5 squares. Every square has a different timing function:

- Square 1: ease
- Square 2: ease-in
- Square 3: ease-out
- Square 4: cubic-bezier (keeping the element in the DOM)
- Square 5: cubic-bezier (adding/removing the element to/from the DOM)

When you click _Animate 1, 2, 3 and 4_, the animation works fine both in Chrome and Safari. You can see that the animation timing function applied to each square is different (which is correct).

But if you click _Animate All_ in Safari, you'll notice that all squares are animated using the same animation timing function even though they all have different timing functions being applied.

Apparently adding or removing the element from the DOM is breaking the animation timing function somehow. Could this be a bug in Safari Webkit?

**Comment by SlateDave** [comment] 2020-06-08 07:54
@sebaferreras I think there is an additional problem besides the one with adding and removing elements. And that is: If you interrupt the animation in the middle, Safari will use the "ease" function for all of them again.

![Animation](https://user-images.githubusercontent.com/26907265/84005826-0397d400-a96e-11ea-8388-737d5957fc34.gif)

**Comment by sebaferreras** [comment] 2020-06-10 07:35
@SlateDave You're absolutely right, that's another way of reproducing the issue.

So, so far the issue seems to be happening when:

1. The animation involves adding or removing an element from the DOM.
2. The animation is interrupted in the middle (even if it doesn't add or remove anything from the DOM).

**Comment by Tarek-Samy** [comment] 2020-06-15 13:07
+1

**Comment by andrewatwood** [comment] 2020-07-04 20:07
Nice reproduction. Happens to me with *ngIf based animations, never remembered to file the issue though, so good on you!

**Comment by SlateDave** [comment] 2020-08-09 09:43
Good news! This bug seems to have been fixed on the latest public beta version of macOS Big Sur and iOS 14 for me.

**Comment by jelbourn** [comment] 2020-10-26 20:55
Closing since this seems like it was a WebKit/Safari bug that has been fixed in later versions.

**Closed by jelbourn** 2020-10-26 20:55 UTC
Labels: comp: animations
