### ISSUE TITLE
URL resolution: use `./foo.html` for relative paths

### ISSUE THREAD

**Issue by mprobst** [angular/angular#8953] opened 2016-06-01 21:34 UTC
angular-cli currently resolves a path like `'foo.html'` (note: no starting dot) as a path relative to the current module URL context (which Angular calls `moduleId`).

That is different from TypeScript's module resolution semantics, which is confusing. E.g.:

``` typescript
// In a file 'my/file.ts'.
import {x} from './relative';  // --> my/relative.ts
import {y} from 'project/base';  // --> project/base.ts

@Component(
  moduleId: module.id,
  templateUrl: 'foo.html',  // currently resolves to my/foo.html ?!?
                            // should be foo.html in root, should push users to ./foo.html
)
class X {}
```

We should follow TypeScript's semantics within TypeScript files. Project relative paths are also useful, e.g. some users might want a `templateUrl: 'my/templates/foo.html'` if they keep their templates in a separate folder (not recommended, but should not be precluded by accidental resolution semantics).

TypeScript's semantics also have the advantage that they have a spec (woohoo!) and are explicitly designed for flexible project layouts, while allowing offline handling. And we get to reuse the configuration out of `tsconfig.json`, so users don't have to specify locations twice, in incompatible formats.

This is a backwards compatibility breaking change, so we should do it quick. I'd suggest as a first step always requiring an explicitly relative path (`./foo.html`, `../foo.html`), and just failing for the naked `foo.html`. That's easy to implement, and help users migrate.

**Comment by mprobst** [comment] 2016-06-01 21:36
CC @hansl @IgorMinar @jelbourn @chuckjaz

**Comment by mprobst** [comment] 2016-06-01 21:36
Oh, and @tbosch I guess.

**Comment by Toxicable** [comment] 2017-08-03 02:13
@mprobst is this still an issue on the latest version with webpack?

**Comment by mprobst** [comment] 2017-08-03 17:45
I haven't tested this in a long time, feel free to close if you think it's not important enough.

**Comment by Toxicable** [comment] 2017-08-03 18:39
I cannot close this issue

**Comment by hansl** [comment] 2017-08-03 18:56
As far as I know this issue is still happening. We haven't changed the semantics of paths for template and style Urls.

**Comment by Toxicable** [comment] 2017-08-03 19:03
@hansl the issue is asking to use relative paths right? Which currently is possible when using the CLI

**Comment by hansl** [comment] 2017-08-03 20:50
The issue is asking to support non-relative paths to follow TypeScript semantics. There is currently (outside the CLI) no error when using non-relative paths in `ngc` (or JIT). It comes down to having different semantics than TypeScript most of the time, so in general it's bad practice. 

The behaviour of non-relative paths in AOT or JIT is undefined.

**Closed** 2021-06-15 20:08 UTC
Labels: P4, comp: compiler, feature, freq3: high, insufficient votes, votes required
