### ISSUE TITLE
ng i18n --ivy,  incorrect value in "equiv-text"

### ISSUE THREAD

**Issue by Niklas187** [angular/angular#39164] opened 2020-10-07 15:10 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [x] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

not really, but it works correct without the new "--ivy" flag

### Description

If you do have a i18n translation with an interpolation and then run "ng xi18n --ivy" the generated xlf file does not have the correct value in the  "equiv-text" attribute.

Example:
`<x id="INTERPOLATION" equiv-text="&quot;\uFFFD0\uFFFD&quot;"/>`

## 🔬 Minimal Reproduction

1. git clone https://github.com/Niklas187/ng-xi18n-ivy-bug.git
3. npm i
5. npm run ex

## 🔥 Exception or Error

In the xlf file i would expect:
`<x id="INTERPOLATION" equiv-text="{{interpolationValue}}}"/`>

## 🌍 Your Environment
<pre><code>
> ng "version"

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 10.1.0
Node: 12.16.0
OS: win32 x64

Angular: 10.1.3
... animations, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1001.3
@angular-devkit/build-angular     0.1001.3
@angular-devkit/build-optimizer   0.1001.3
@angular-devkit/build-webpack     0.1001.3
@angular-devkit/core              10.1.3
@angular-devkit/schematics        10.1.0
@angular/cli                      10.1.0
@ngtools/webpack                  10.1.3
@schematics/angular               10.1.0
@schematics/update                0.1001.0
rxjs                              6.6.3
typescript                        4.0.3
webpack                           4.44.1

</code></pre>

**Comment by petebacondarwin** [comment] 2020-10-07 18:56
This is a duplicate of https://github.com/angular/angular/issues/38711 which was fixed by https://github.com/angular/angular/pull/39006 and should be available in the 10.1.5 release.

**Closed by petebacondarwin** 2020-10-07 18:56 UTC
Labels: comp: i18n
