### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by txpilot03** [angular/angular#55886] opened 2024-05-20 10:22 UTC
### Describe the problem that you experienced

A link on Angular.dev is a dead link.  The dead link of 'pipes API documentation was accessed from the below paragraph:

Note: For a complete list of built-in pipes, see the ### _[pipes API documentation](https://angular.dev/api/common#pipes)_. To learn more about using pipes for internationalization (i18n) efforts, see [formatting data based on locale](https://angular.dev/api/common/getLocaleMonthNames/guide/i18n/format-data-locale).

### Enter the URL of the topic with the problem

https://angular.dev/guide/pipes

### Describe what you were looking for in the documentation

Looking for the data on the link that is dead

### If this problem caused an exception or error, please paste it here

```true
Page Not Found 🙃

If you think this is a mistake, please open an issue so we can fix it.
```

**Comment by JoostK** [comment] 2024-05-20 11:06
Closing as duplicate of #52968

**Closed by JoostK** 2024-05-20 11:06 UTC
