### ISSUE TITLE
Does Angular cooperate with AMD/CommonJS?

### ISSUE THREAD

**Issue by SetTrend** [angular/angular#4897] opened 2015-10-25 10:29 UTC
In issue [#13133](https://github.com/angular/angular.js/issues/13133) for AngularJS it becomes clear that AngularJS doesn't work well with AMD. But AMD or CommonJS seem to become the default loading technique for TypeScript.

Will Angular v2 cope with this problem and work with AMD/CommonJS loaders, like RequireJS?

**Comment by pkozlowski-opensource** [comment] 2015-10-25 22:06
Angular2 is written in TypeScript and as such it could be transpiled to any module system supported by TS: there is nothing special here. 

I guess you are talking here about having some kind of bundled version of Angular2 and if so we do plan on providing CJS bundles (see https://github.com/angular/angular/issues/4278) but there is no intention of providing AMD bundles.

Closing as duplicate of #4278

**Closed by pkozlowski-opensource** 2015-10-25 22:06 UTC
