### ISSUE TITLE
Named outlets of lazy loaded modules in auxiliary routes do not work

### ISSUE THREAD

**Issue by joshualouisjenson** [angular/angular#26964] opened 2018-11-06 21:11 UTC
# 🐞 bug report

### Affected Package
7.0.1

### Is this a regression?
No

### Description
Named routes of lazy loaded modules which are loaded as part of an auxiliary route in another lazy loaded module do not work. Empty routes work correctly.

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-pxlnes

Note that named and unamed outlets for non-lazy loaded modules in LazyModule1 work correctly, as does the unnamed route in LazyModule2. The named route in LazyModule2, when accessed through the auxilliary route in LazyModule1 however, does not.

In the example, the problem link is the second link in the list titled "Lazy content with parameters".

## 🔥 Exception or Error
errors.ts:35 ERROR Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'lazy1/1/2'

## 🌍  Your Environment
7.0.1

I searched for other issues and found some others that are similar to this setup (such as https://github.com/angular/angular/issues/24562) but are not exactly the same. The workaround for that issue is also unsuitable for my use case, as I need to be able to reroute the auxiliary outlet without changing the primary route.

Thank you.

**Comment by henrique-barreto** [comment] 2018-12-12 17:22
Very annoying bug!!! For years, other issues were created and closed, but the problem persist.

**Comment by TGC79** [comment] 2019-01-23 21:49
Duplicate of #10726 which should be reopened since the fix for it was reverted.

Issue was first reported on Angular 2.0.0-rc.5.

**Comment by lincolnthree** [comment] 2019-06-06 14:51
Still having this issue in Angular 8. Having trouble finding a workaround. Looking into CDK portals but... that adds a lot of complications.

**Comment by dawidp-ionoview** [comment] 2019-06-24 08:30
@joshualouisjenson I checked that stackblitz and it actually started working after changing `lazy2-routes.ts:10` from `path: ':paramA:paramB'` to `path: ':paramA/:paramB'` (this is the url you are actually redirecting to in `PortalComponent`) :tada:

**Comment by superdyzio** [comment] 2019-06-24 08:31
@joshualouisjenson I checked that stackblitz and it actually started working after changing lazy2-routes.ts:10 from path: ':paramA:paramB' to path: ':paramA/:paramB' (this is the url you are actually redirecting to in PortalComponent) :tada:

**Closed** 2019-06-27 14:00 UTC
Labels: comp: router, freq2: medium, severity3: broken, type: bug/fix

**Comment by Jonathan002** [comment] 2019-07-20 07:48
@joshualouisjenson I have created a package that is suppose to be a workaround for named routes in lazy modules. Please have a look at it and hope it helps. : )

Repo Link: https://github.com/Jonathan002/route-master-example
