### ISSUE TITLE
No support for abstract class inheritance after upgrade to Angular 9

### ISSUE THREAD

**Issue by splincode** [angular/angular#35366] opened 2020-02-12 09:59 UTC
### Affected Package

The issue is caused by package @angular/schematics

### Is this a regression?

Yes.

### Description

Angular 8

```ts
export abstract class AbstractChildComponent {
  @Input() public name: string;
  public abstract hello(): void;
}

export class AbstractParentComponent extends AbstractChildComponent {
  public hello(): void {
     alert(`Hello ${name}`);
  }
}

@Component({
  selector: 'hello',
  template: `<h2 class="title">Hello {{name}}</h2>`
})
export class HelloComponent extends AbstractParentComponent {
}

@Component({
  selector: 'my-app',
  template: '<hello [name]="name"></hello>',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  name = 'Angular ' + VERSION.full;
}
```

After `$ ng update`

Angular 9

```ts
@Directive() // <---  auto decorated after update
export abstract class AbstractChildComponent {
  @Input() public name: string;
  public abstract hello(): void;
}

// BUT NOT DECORATED AbstractParentComponent ?
export class AbstractParentComponent extends AbstractChildComponent {
  public hello(): void {
     alert(`Hello ${name}`);
  }
}

@Component({
  selector: 'hello',
  template: `<h2 class="title">Hello {{name}}</h2>`
})
export class HelloComponent extends AbstractParentComponent {
}

@Component({
  selector: 'my-app',
  template: '<hello [name]="name"></hello>',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  name = 'Angular ' + VERSION.full;
}
```

I have exceptions in console and browser:

```ts
 Can't bind to 'name' since it isn't a known property of 'hello'.
    1. If 'hello' is an Angular component and it has 'list' input, then verify that it is part of this module.
    2. If 'hello' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
    3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.
```

stackblitz can't reproduce, because stackblitz running JIT mode

https://stackblitz.com/edit/angular-9-abstract

But if you run in `ng serve --aot=true` expected errors

## 🌍  Your Environment

Last Angular (v9.0.0)

**Comment by Ristaaf** [comment] 2020-02-12 10:33
This should work, and it does for me, both taking your example code into a new angular-cli project, and by downloading your stackblitz example and upgrading it to the latest angular-cli and @angular/compiler-cli and then run ng serve --aot=true

Are you sure you are using angular-cli 9?

**Comment by splincode** [comment] 2020-02-12 10:37
try in `ng-run.com` in aot mode this does not work

**Comment by splincode** [comment] 2020-02-12 10:37
`Are you sure you are using angular-cli 9?`
yes

**Comment by pkozlowski-opensource** [comment] 2020-02-12 10:41
> try in ng-run.com in aot mode this does not work

@splincode mind sharing a repro? This seems to work for me:
https://ng-run.com/edit/GuES2Ib3ZLuSmiwOrSa1?open=index.html

**Comment by splincode** [comment] 2020-02-12 10:50
Sorry, I didn’t give the right example, here you can try it like this
I updated the example

**Comment by mlc-mlapis** [comment] 2020-02-12 11:00
@splincode Even update example works for me, except the missing implementation of 
`Non-abstract class 'HelloComponent' does not implement inherited abstract member 'hello' from class 'AbstractHelloComponent'.`

**Comment by JoostK** [comment] 2020-02-12 11:25
@splincode Thanks for updating the details, that is indeed an issue today. This is essentially a duplicate of #34376 for which a PR is already in the works in #35332 

The workaround would be to manually add the `@Directive()` decorator to the base class that doesn't have it.

**Closed by JoostK** 2020-02-12 11:25 UTC

**Comment by Ristaaf** [comment] 2020-02-12 11:31
@splincode Cannot reproduce either, not in ng-run.com and not locally. And just fyi I am upgrading a repo with a lot of abstract inheritances and for me that works just fine and so does your examples. Do you have a ng-run.com project that fails that you can share, or a git repo that I can try locally that fails? I am pretty sure this is not a problem with the code itself, (since both me and @pkozlowski-opensource  can get the code to work), but it has to be a problem with the project setup somehow.
