### ISSUE TITLE
@angular/service-worker caching 3rd party api calls and causing cross-origin read blocking warnings

### ISSUE THREAD

**Issue by neonguru** [angular/angular#32644] opened 2019-09-12 18:30 UTC
### Affected Package
The issue is caused by package @angular/service-worker@8.2.5

### Is this a regression?

No, I believe the ngsw calls to 3rd party APIs have been happening all along but the Chrome cross-origin read blocking (CORB) warnings are new.

### Description

My angular app is a PWA and when it makes any calls to 3rd party APIs, ngsw-worker.js will fetch the same API call again. My 3rd party APIs include gtm (google tag manager), google maps, mongodb stitch. The Stitch call made by ngsw-worker.js is the one now throwing the CORB errors once upgrading from angular 7 to 8. Mongodb Stitch API package was not updated.

The original stitch call is a post, the calls made by ngsw-worker.js are an OPTIONS and a POST. Chrome dev tools says the OPTIONS call is the one throwing the CORB warning.

## 🔬 Minimal Reproduction

Not able to create a PWA StackBlitz repo. But add any 3rd party API call to a minimal PWA and it will repo. 

I was able to repo the ngsw-worker.js loading the 3rd party calls, by doing the following
ng new testapp
cd testapp
ng add @angular/pwa
Add a script tag to a 3rd party script, such as the following Google Maps API line to the bottom of index.html just before the </body> end tag:

<pre><code>
  <script async defer type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=api_key"></script>
</code></pre>

npm install http-server
ng build --prod
http-server -p 8080 -c-1 dist/testapp
open http://localhost:8080/
check network calls and see that ngsw-worker.js makes a call to re-load the google maps api call.

## 🔥 Exception or Error
The error is that ngsw-worker.js is re-loading 3rd party api calls.

The following exception is coming from ngsw-worker.js re-calling my mongodb stitch api call in my full app (not the minimal repo). I will include a link to my website when I release the updated version after testing has finished.

<pre><code>
Cross-Origin Read Blocking (CORB) blocked cross-origin response https://us-west-2.aws.stitch.mongodb.com/api/client/v2.0/app/app_id/functions/call with MIME type application/x-gzip. See https://www.chromestatus.com/feature/5629709824032768 for more details.
(anonymous)	@	ngsw-worker.js:2709
(anonymous)	@	ngsw-worker.js:1790
(anonymous)	@	ngsw-worker.js:1786
safeFetch	@	ngsw-worker.js:2707
(anonymous)	@	ngsw-worker.js:2159
fulfilled	@	ngsw-worker.js:1787
Promise.then (async)		
step	@	ngsw-worker.js:1789
fulfilled	@	ngsw-worker.js:1787
Promise.then (async)		
step	@	ngsw-worker.js:1789
fulfilled	@	ngsw-worker.js:1787
Promise.then (async)		
step	@	ngsw-worker.js:1789
(anonymous)	@	ngsw-worker.js:1790
(anonymous)	@	ngsw-worker.js:1786
handleFetch	@	ngsw-worker.js:2099
onFetch	@	ngsw-worker.js:1963
(anonymous)	@	ngsw-worker.js:1897
 </code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.3.4
Node: 10.15.1
OS: win32 x64
Angular: 8.2.5
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker

Package                                    Version
--------------------------------------------------------------------
@angular-devkit/architect                  0.803.4
@angular-devkit/build-angular              0.803.4
@angular-devkit/build-optimizer            0.803.4
@angular-devkit/build-webpack              0.803.4
@angular-devkit/core                       8.3.4
@angular-devkit/schematics                 8.3.4
@angular/cdk                               8.2.0
@angular/cli                               8.3.4
@angular/material                          8.2.0
@angular/pwa                               0.803.4
@ngtools/webpack                           8.3.4
@nguniversal/express-engine                8.1.1
@nguniversal/module-map-ngfactory-loader   8.1.1
@schematics/angular                        8.3.4
@schematics/update                         0.803.4
rxjs                                       6.4.0
typescript                                 3.5.3
webpack                                    4.39.2

</code></pre>

**Anything else relevant?**

I believe the warnings are only in Chrome.

**Comment by gkalpak** [comment] 2019-09-13 19:16
Based on the above info, I can't see anything wrong with the described SW behavior. The SW is not re-calling APIs: All requests (by default) go through the SW (which might decide to forward them to the network).

I also don't see a change in `@angular/service-worker` between 7 and 8 that could have introduced a related issue (unless you are trying to cache responses of these APIs.

I wonder if this is a Chrome issue (in which case you could open an issue on the Chromium tracker (if one does not exist already)).

I am going to close this issue, because I could not reproduce any problematic behavior, but happy to investigate more once your reproduction (i.e. your updated website) goes live.

**Closed by gkalpak** 2019-09-13 19:16 UTC
Labels: comp: service-worker

**Comment by neonguru** [comment] 2019-09-15 00:14
Hi @gkalpak thanks for the quick response. The stack trace pointed to ngsw-worker.js as the source of the error, but if I mod the ngsw code so it exits immediately in onFetch, it would still show the error, but without pointing to ngsw-worker.js anymore.

The issue is gone now that I upgraded from Chrome 76 to 77, and all angular 8 tests pass, so I am happy with the upgrade.
