### ISSUE TITLE
DebugElement.query() returns null though the return type cannot be null

### ISSUE THREAD

**Issue by rbirkgit** [angular/angular#47857] opened 2022-10-24 19:03 UTC
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

Looking at the source code the return type says it cannot return null. However if no match it still does. Our strict check fails when we compare the result with null.

```
export declare class DebugElement extends DebugNode {
  query(predicate: Predicate<DebugElement>): DebugElement {
    const results = this.queryAll(predicate);
    return results[0] || null;
  }
}
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 14.2.6
Node: 18.10.0 (Unsupported)
Package Manager: yarn 3.2.4
OS: win32 x64

Angular: 14.2.7
... animations, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1402.6
@angular-devkit/build-angular   14.2.6
@angular-devkit/core            14.2.6
@angular-devkit/schematics      14.2.6
@angular/cdk                    14.2.5
@angular/cli                    14.2.6
@schematics/angular             14.2.6
ng-packagr                      14.2.2
rxjs                            7.5.7
typescript                      4.8.4
```

### Anything else?

I assume the return type should be extended to also support null?

**Comment by JoostK** [comment] 2022-10-24 19:58
Closing as duplicate of #22449.

**Closed by JoostK** 2022-10-24 19:58 UTC
