### ISSUE TITLE
A2 warning/error messages should all have links

### ISSUE THREAD

**Issue by wardbell** [angular/angular#6173] opened 2015-12-29 23:16 UTC
Brought to mind by the message from DevMode which tells you that you can use ProdMode but doesn't tell you why or how.  Nor do I think it should. I think it should have a link.

A1 has links which is great! Also helped with size of the production version I'm sure. Let's do that in A2 too!

**Comment by splincode** [comment] 2018-07-27 12:17
@wardbell Is the issue relevant?

**Comment by pkozlowski-opensource** [comment] 2020-03-06 13:39
Duplicate of #18875

**Closed by pkozlowski-opensource** 2020-03-06 13:39 UTC
Labels: comp: core, hotlist: error messages, type: feature
