### ISSUE TITLE
interpret double dash as single dash when translating names

### ISSUE THREAD

**Issue by kvantetore** [angular/angular#2600] opened 2015-06-17 22:11 UTC
@mhevery wrote

We should treat double dash as single dash. `<div (custom--event)="..">` should translate to `element.addEventListener('custom-event')`. 

#2014 should support further renaming.

we convert dash into camel case because:
1. it is what properties need, and we need to be consistent
2. DOM events don't have dash in them but some are camel cased
3. most code in the wild uses camel case for custom events: https://github.com/search?utf8=%E2%9C%93&q=new+CustomEvent&type=Code&ref=searchresults (polymer being an exception)

============================
@kvantetore originally wrote

Some 3rd party events (e.g. polymer elements' iron-select) have a dash in their name. The normal binding syntax converts dashes to camelCase. 

    <paper-drawer-selector (iron-select)="doStuff()"></paper-drawer-selector>

In this case, an event handler is added to the "ironSelect" instead of the correctly named "iron-select" event. Is it possible to trick it to use the dashed event name instead?

**Comment by pkozlowski-opensource** [comment] 2015-06-18 08:02
Right. So the problem is that we've got limited control over events declared by component authors (both web components and ng2 directives) so we can't exclude that people are going to create events following both `dash-case` and `camelCase` schema... 

#2014 will help with this as it will allow us to override defaults. Having said this I think that we should re-visit dash -> camel casing for event names by default

**Comment by mhevery** [comment] 2015-06-19 21:02
Maybe we just force people to always use schema with events, and then it is not an issue. (So hold off on implementing this until we have schema working.)

**Comment by mhevery** [comment] 2015-10-27 00:31
should be solved by: #4417

**Comment by pkozlowski-opensource** [comment] 2015-12-12 11:16
Now that we've landed case-sensitive HTML parser this convention is no longer needed. Closing

**Closed by pkozlowski-opensource** 2015-12-12 11:16 UTC
Labels: comp: core/view/compiler, effort1: easy (hour), hotlist: community-help, P2: required, type: bug
