### ISSUE TITLE
Router 3.0.0 does not work with rxjs bundle

### ISSUE THREAD

**Issue by gustavgahm** [angular/angular#12060] opened 2016-10-04 08:01 UTC
**I'm submitting a ...**
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
rxjs_observable_of.of is undefined in ApplyRedirects.prototype.expandSegment when using rxjs bundle (5.0.0-beta.12)

**Expected behavior**
rxjs_observable_of.of should be defined as the Of operator.

**What is the motivation / use case for changing the behavior?**
Unable to use the router when using the bundle. The load time of my application is slow when all operators has to be loaded one by one.

**Please tell us about your environment:**
### package.json:
> {
  "name": "angular-quickstart",
  "version": "1.0.0",
  "description": "QuickStart package.json from the documentation, supplemented with testing support",
  "scripts": {
    "start": "tsc && concurrently \"tsc -w\" \"lite-server\" ",
    "pree2e": "npm run webdriver:update",
    "e2e": "tsc && concurrently \"http-server -s\" \"protractor protractor.config.js\" --kill-others --success first",
    "lint": "tslint ./Application/**/*.ts -t verbose",
    "lite": "lite-server",
    "test": "grunt build && concurrently \"grunt watch\" \"karma start Build/karma.conf.js\"",
    "test-once": "tsc && karma start karma.conf.js --single-run",
    "tsc": "tsc",
    "tsc:w": "tsc -w",
    "webdriver:update": "webdriver-manager update"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@angular/common": "2.0.1",
    "@angular/compiler": "2.0.1",
    "@angular/core": "2.0.1",
    "@angular/forms": "2.0.1",
    "@angular/http": "2.0.1",
    "@angular/platform-browser": "2.0.1",
    "@angular/platform-browser-dynamic": "2.0.1",
    "@angular/router": "3.0.1",
    "systemjs": "0.19.39",
    "core-js": "^2.4.1",
    "reflect-metadata": "^0.1.3",
    "rxjs": "5.0.0-beta.12",
    "zone.js": "^0.6.23",
    "bootstrap": "^3.3.6",
    "system-text": "0.1.0",
    "angular2-jwt": "0.1.23",
    "es6-module-loader": "0.17.11",
    "es6-promise": "4.0.5",
    "es6-shim": "0.35.1",
    "font-awesome": "4.6.3",
    "jquery": "3.1.1",
    "ng2-bootstrap": "1.1.5",
    "normalize.css": "4.2.0",
    "underscore": "1.8.3"
  },
  "devDependencies": {
    "@types/core-js": "^0.9.34",
    "@types/jasmine": "^2.2.34",
    "@types/jquery": "^2.0.32",
    "@types/karma": "^0.13.33",
    "@types/moment": "^2.13.0",
    "@types/underscore": "^1.7.33",
    "canonical-path": "0.0.2",
    "concurrently": "^3.0.0",
    "extend": "3.0.0",
    "grunt": "~0.4.0",
    "grunt-cli": "1.2.0",
    "grunt-contrib-clean": "1.0.0",
    "grunt-contrib-connect": "1.0.2",
    "grunt-contrib-copy": "1.0.0",
    "grunt-contrib-less": "1.4.0",
    "grunt-este-watch": "0.1.18",
    "grunt-ts": "6.0.0-beta.3",
    "grunt-tslint": "3.2.1",
    "http-server": "^0.9.0",
    "jasmine-core": "~2.5.2",
    "karma": "^1.3.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-htmlfile-reporter": "^0.3.4",
    "karma-jasmine": "^1.0.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "lite-server": "^2.2.2",
    "lodash": "^4.16.1",
    "protractor": "^4.0.9",
    "rimraf": "^2.5.2",
    "tslint": "^3.15.1",
    "typescript": "^2.0.3"
  },
  "repository": {}
}

* **Angular version:** 2.0.1

* **Browser:** [Chrome 53.0.2785.116 m]
 
* **Language:** [TypeScript 2.0.3]

**Comment by woppa684** [comment] 2016-10-04 08:12
I think you need to compile your own bundle :( https://github.com/angular/angular/issues/9359

**Comment by pkozlowski-opensource** [comment] 2016-10-04 09:14
This is indeed duplicate of #9359 - thnx @woppa684

**Closed by pkozlowski-opensource** 2016-10-04 09:14 UTC
