### ISSUE TITLE
Tree shakable component providers

### ISSUE THREAD

**Issue by pauldraper** [angular/angular#31355] opened 2019-06-29 22:57 UTC
# 🚀 feature request

### Relevant Package

@angular/core

### Description

I can tree shake components/directives, and module providers.

I want to tree shake component/directive providers, for services that are created per-component/directive.

### Describe the solution you'd like

Perhaps `providedIn: Component`? Not really sure.

### Describe alternatives you've considered

No general solution that I know of.

**Comment by LayZeeDK** [comment] 2019-07-01 22:33
Yeah, this is where Angular modules can burn you with their layer of indirection.

If you use [SCAMs](https://blog.angularindepth.com/emulating-tree-shakable-components-using-single-component-angular-modules-5e3d380364ea) carefully, you will only reference a SCAM when you use its component in a template. If a service is only provided and referenced by the SCAM-declared component is not used in your application, both the service, the component, and the SCAM will be left out of your application bundles.

If you use Angular CLI with AOT and the build optimizer enabled, unused components (except entry components) will be tree shaked (removed from the application bundle). I wonder whether that would also tree shake component-specific services provided by those components.

**Comment by pauldraper** [comment] 2019-07-02 14:30
> If you use SCAMs carefully

In general (Angular or otherwise), if you import carefully, tree shaking is irrelevant; you've already done it by hand.

> I wonder whether that would also tree shake component-specific services provided by those components.

It believe it would.

"Tree-shakable providers" were done in such a way that the leaves would drive whether or not the service got included. I think there's a case for the same to be done for non-singleton classes, but I'm not sure.

**Comment by trotyl** [comment] 2019-07-02 15:31
Duplicate of https://github.com/angular/angular/issues/18015

**Comment by LayZeeDK** [comment] 2019-07-02 18:53
>In general (Angular or otherwise), if you import carefully, tree shaking is irrelevant; you've already done it by hand.

Sure, but a lot of Angular modules are bundles of multiple components, which means that we have an indirect reference to components that we might not be using.

>"Tree-shakable providers" were done in such a way that the leaves would drive whether or not the service got included. I think there's a case for the same to be done for non-singleton classes, but I'm not sure.

Tree-shakable providers removed the providers from the Angular modules which were not the pieces of UI actually using the dependencies. Using providers in service decorators or injection token constructors, they can be tree shaken if no other service or declarable references them.

This is already the case for services provided by components to the element injector. With that being said, actual usage and the reference in the provider metadata can get out of sync. So this is where your suggestion could make sense.

**Comment by pauldraper** [comment] 2019-07-12 13:27
> Tree-shakable providers removed the providers from the Angular modules which were not the pieces of UI 

That's a somewhat arbitrary distinction.

The idea is (1) I want to use DI, for better code architecture, which delegates responsibility to my parent to provide the code but (2) parents can wind up including code that is never used.

Right now, tree shaking works when the DI container is the root or lazily loaded root. It doesn't work for any other DI container (a component).

**Comment by pauldraper** [comment] 2019-07-12 14:32
A common case would be routing: a parent component has no way of knowing whether the routed children do or not do use provided services.

**Comment by LayZeeDK** [comment] 2019-07-16 01:58
> That's a somewhat arbitrary distinction to make for "UI" and "non-UI".
Sure, 14 days later even I am struggling to figure out what I meant.

What I meant was that pre-Angular 6 we would have providers in Angular modules. That meant that there could be a reference to a service even without it actually being used in the application.

Using `Injectable` or `InjectionToken`, we only have references to the dependencies if other dependencies or declarables (components, directives, and pipes) actually depend on them.

So I'm simply trying to state how they make a difference for Angular projects. But you are probably already aware of this.

**Comment by alxhub** [comment] 2022-04-14 23:49
Component DI is "closed" - the set of provided services are determined entirely when the component is compiled, and cannot be expanded at runtime. This is done for performance, as component creation requires a lot of injection operations.

This means that we cannot support adding a provided service to a component after initialization, which would be necessary to implement `providedIn: component`.

**Closed by alxhub** 2022-04-14 23:49 UTC
Labels: feature, comp: core, core: di, cross-cutting: tree-shaking, insufficient votes, votes required
