### ISSUE TITLE
Cryptic error message if `let` is missing in ngFor expression

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#20901] opened 2017-12-08 23:53 UTC
## Current behavior
```
<table>
  <tr *ngFor="foo of foos">
    <td>{{foo}}</td>
  </tr>
</table>
```

results in the following error:

```
ERROR in : Can't bind to 'ngFor' since it isn't a known property of 'tr'. ("

<table>
  <tr [ERROR ->]*ngFor="foo of foos">
    <td>{{foo}}</td>
  </tr>
")
: Property binding ngFor not used by any directive on an embedded template. Make sure that the property name is spelled correctly and all directives are listed in the "@NgModule.declarations". ("

<table>
  [ERROR ->]<tr *ngFor="foo of foos">
    <td>{{foo}}</td>
  </tr>
")
```

## Expected behavior
I'd like to be told that I forgot to use `let` in the expression and should change my code to:

```
<table>
  <tr *ngFor="let foo of foos">
    <td>{{foo}}</td>
  </tr>
</table>
```

## Environment

<pre><code>
Angular version: 5.1.0

**Comment by trotyl** [comment] 2017-12-09 06:14
Duplicate of #14641?
<sub>Or supersedes that one?</sub>

**Comment by atscott** [comment] 2020-09-23 21:32
Also produces a confusing error in Ivy:
https://stackblitz.com/edit/angular-ivy-3qavxl?file=src%2Fapp%2Fapp.component.html

**Comment by JoostK** [comment] 2021-07-15 23:43
Closing as a duplicate of #14641.

**Closed by JoostK** 2021-07-15 23:43 UTC
Labels: P4, comp: core, core: ng-template and *microsyntax, freq2: medium, hotlist: error messages, state: confirmed, type: bug/fix
