### ISSUE TITLE
Tour of heroes : part 8, HeroDetailComponent Decorator @input useless

### ISSUE THREAD

**Issue by fchetouani** [angular/angular#25279] opened 2018-08-03 10:30 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[X] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Tutorial Part 8 'HTTP'
In HeroDetailComponent class
the property hero has decorator @Input

`export class HeroDetailComponent implements OnInit {
  @Input() hero: Hero; ...`

## Expected behavior

Tutorial Part 8 'HTTP'
In HeroDetailComponent class
the property hero should not have decorator @Input
because the HeroDetailComponent loads hero on init
(property hero is no more an input parameter)

`export class HeroDetailComponent implements OnInit {
  hero: Hero; ...`

## Minimal reproduction of the problem with instructions

No impact at runtime.
## What is the motivation / use case for changing the behavior?

For a new user, (s)he may be confused.

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by trotyl** [comment] 2018-08-03 10:41
Duplicate of https://github.com/angular/angular/issues/22174

**Comment by brandonroberts** [comment] 2018-08-03 20:08
Closed as a duplicate

**Closed by brandonroberts** 2018-08-03 20:08 UTC
Labels: comp: docs
