### ISSUE TITLE
feat(service-worker): add support for specifying `cache.match()` options for asset-/data-groups

### ISSUE THREAD

**Issue by mjkerster** [angular/angular#32276] opened 2019-08-22 19:02 UTC
# 🐞 bug report

### Affected Package

@angular/service-worker

### Is this a regression?

 Yes, I assumed this worked for previous versions but this is the first time trying to implement it.

### Description

I have implemented a pretty standard service worker with the below configuration:
```
{
  "index": "/index.html",
  "assetGroups": [
    {
      "name": "app",
      "installMode": "prefetch",
      "resources": {
        "files": [
          "/favicon.ico",
          "/index.html",
          "/*.css",
          "/*.js"
        ]
      }
    }, {
      "name": "assets",
      "installMode": "lazy",
      "updateMode": "prefetch",
      "resources": {
        "files": [
          "/assets/**",
          "/legacy/**",
          "/*.(eot|svg|cur|jpg|png|webp|gif|otf|ttf|woff|woff2|ani)"
        ]
      }
    }
  ],
  "navigationUrls": [
    "/**",
    "!/**/*.*",      
    "!/**/*__*",     
    "!/**/*__*/**",  
    "!/**/faqs",
    "!/**/terms-and-conditions",
  ]
}
```
The service worker is working properly as far as putting what I want into cache and busting it when a new version is found.  The problem is that all requests that match what is in the cache end up going to the network no matter what.  

After spending a lot of time debugging the ngsw-worker.js that angular generates, I found that all requests that where being checked by `cache.match` where not found.  The reason for that is the headers of the requests coming from my app were a little different than the request headers stored in cache.  Specifically the `referrer-policy` header is different.  The incoming request has the header set to `Referrer Policy: no-referrer-when-downgrade` but the header for the matching request in cache is `Referrer Policy: unsafe-url`.

One way I proved that this was the issue was by using the `cache.match()` options flag `ignoreVary: true` to ignore header differences.  After making that change my app's service worker pulled all in scope assets from cache and didn't go to the network.  Because the `ngsw-worker.js` is generated I don't think modifying it is a valid option.

I dug deeper to see why the request headers where being mismatched.  What I found was that the request that is being put in to cache `cache.put(req, res)` is accurate, but when you immediately pull that same request from cache the headers are changed.  There is something that happens when executing `cache.put()` that modifies the request headers and I am not sure what.

Is there anything from an angular service worker configuration that would cause this?  Would it be possible to update the generated service worker to use the `ignoreVary` option when checking for matches in cache?

## 🔬 Minimal Reproduction

 https://stackblitz.com/...

To reproduce this just execute the two statements below in a browser console and compare the request objects.

caches.open('exampleTest1').then(cache => {var newreq = new Request("https://www.google.com"); console.log('NEW REQUEST: ', newreq); cache.put(newreq, new Response('hello'))})

caches.open('exampleTest1').then(res => res.keys().then(keys => console.log(keys)))

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

    _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 8.2.0
Node: 10.15.3
OS: darwin x64
Angular: 8.2.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker, upgrade

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.0
@angular-devkit/build-angular     0.800.0
@angular-devkit/build-optimizer   0.800.0
@angular-devkit/build-webpack     0.800.0
@angular-devkit/core              8.2.0
@angular-devkit/schematics        8.2.0
@angular/pwa                      0.12.4
@ngtools/webpack                  8.0.0
@schematics/angular               8.2.0
@schematics/update                0.802.0
rxjs                              6.5.2
typescript                        3.5.3
webpack                           4.34.0
</code></pre>

**Anything else relevant?**

I am using this version of Chrome: Version 76.0.3809.100 (Official Build) (64-bit)

**Comment by Vandivier** [comment] 2019-08-22 19:17
Yep. Not sure it's a regression but I can repro the behavior. package name minor typo, `@angular/service-worker`.

can repro with a simpler config on FF and edge as well:
```
  "index": "/index.html",
  "assetGroups": [
    {
      "name": "app",
      "installMode": "prefetch",
      "resources": {
        "files": [
          "/index.html",
          "/*.css"
        ]
      }
    }, {
      "name": "assets",
      "installMode": "lazy",
      "updateMode": "prefetch",
      "resources": {
        "files": [
          "/assets/**"
        ]
      }
    }
  ],
  "navigationUrls": [
    "/**"
  ]
}
```

**Comment by gkalpak** [comment] 2019-08-22 20:04
I couldn't really reproduce the issue, but that is really beyond the point.
This is basically a feature request for being able to specify options to be passed to `cache.match()` for the different asset-/data-groups (because right now it is not possible to specify `ignoreVary` or anything else).

This sounds doable (and I can't think of any implementation aspect that would cause problems off the top of my head), but is not in our immediate plans. If anyone is really interested in working on a PR though, feel free to ping me to discuss further.

**Comment by mjkerster** [comment] 2019-08-23 13:31
I understand how making the ignoreVary option part for the service worker config would be an enhancement, but technically that shouldn't be needed right?

The service worker creates a new Request for every URL that needs to be cached, and then that Request is cached. This is all from the angular generated service worker code, which we don't have control over. I'm not sure how I get past this issue without abandoning the angular service worker implementation.

**Comment by gkalpak** [comment] 2019-08-23 15:01
> I understand how making the ignoreVary option part for the service worker config would be an enhancement, but technically that shouldn't be needed right?

You asked for it (😛) and I assumed this would help with your issue (in addition to being a reasonable enhancement).

##
> The service worker creates a new Request for every URL that needs to be cached, and then that Request is cached.

Are you saying that this is the root of the problem? Is it because we don't copy some headers, when creating the new request?

**Comment by mjkerster** [comment] 2019-08-24 12:45
Haha sorry for the confusion. Yes, adding options for cache.match() would help with my issue.

But if we look at the root of the problem the request headers change when put into cache. Were you able to run the example code in the issue? It shows what new request headers looked before being put into cache and what they look like after you pull the request out of cache.

I'm on vacation right now but when I get back I can try and provide better example of the issue. 

I appreciate your help with this.

**Comment by gkalpak** [comment] 2019-08-26 09:48
> Were you able to run the example code in the issue?

I tried the code (I even played with `referrer-policy` headers), but I wasn't able to reproduce the issue (probably did something wrong). Or maybe it depends on some other configurationon on the page?

I'll wait for your example :smiley:

**Comment by mjkerster** [comment] 2019-09-04 18:35
@gkalpak 

I believe my initial assessment was a little off.  The issue wasn't a difference in the headers, but there is an issue when retrieving cached assets due to the Vary header that is applied to the responses. 

All responses that have the header `Vary: Accept-Encoding,User-Agent` can not be retrieved from cache.  Testing the service worker implementation in Firefox, everything seems to work perfectly.  

Is this a Chrome problem?  It doesn't seem to be an Angular service worker problem since it's working as expected in Firefox.

**Comment by gkalpak** [comment] 2019-09-05 09:59
Yes, there seems to be an issue with Chrome+CacheStorage/ServiceWorker+`Vary` header.
See Chromium issues [595993], [756796], [962620] (and related issues mentioned in comments).

[595993]: https://bugs.chromium.org/p/chromium/issues/detail?id=595993
[756796]: https://bugs.chromium.org/p/chromium/issues/detail?id=756796
[962620]: https://bugs.chromium.org/p/chromium/issues/detail?id=962620

**Comment by mjkerster** [comment] 2019-09-05 15:18
Thanks @gkalpak

I am not sure how you want to move forward with this issue, but there isn't an issue with the Angular SW, and I am not sure the `ignoreVary` option is a needed feature if the Chromium issue is resolved.  I'll leave that decision up to you 😃

**Comment by gkalpak** [comment] 2019-09-05 15:23
As mentioned above, I am leaving this open a nice-to-have feature request.
(It is a low priority and there are no immediate plans to work on it, but it doesn't hurt to have an issue to track it. (You never know. Someone might even decide to take it on :wink:))

**Comment by gkalpak** [comment] 2019-12-22 21:06
Actually, I just realized that the feature request of adding support for `catch.match` options is being tracked in #28443. So, closing this one.

**Closed by gkalpak** 2019-12-22 21:06 UTC
Labels: comp: service-worker, effort2: days, type: feature
