### ISSUE TITLE
Inconsistent Behavior when inheriting OnPush change detection

### ISSUE THREAD

**Issue by shammy8** [angular/angular#43360] opened 2021-09-06 09:05 UTC
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

I'm having some confusion over the workings of OnPush change detection. Please see the Stackblitz I made below. 

With the current set up I have Parent component set to OnPush and the child component set to Default. But from what I read in the [spec](https://angular.io/api/core/ChangeDetectionStrategy) the Child component should also be OnPush since it gets inherited from the Parent and you can't override it.

In the Child component I have a setInterval which updates a number property which is binded in the template. With the current set up the change in the number property doesn't get updated in the view, which makes sense. When you change the parent component to Default the number property will start incrementing in the view. This all makes sense to me. 

However, when I change the Parent back to OnPush and the Child to Default (or leave it blank) then I click the 'Do Nothing' button in the Parent component it seems to trigger change detection in the child component as well. I have to explicitly change the change detection to OnPush in the Child to get the behavior I am expecting ie. change detection doesn't run in the Child component when I click 'Do Nothing' in the parent.

Is this a bug or is this the expected behavior? If it is the expected behavior what actually does OnPush in the Parent change in the Child component's behavior when OnPush isn't explicitly set in the Child?

Furthermore, in the Stackblitz (with the Parent set to OnPush) shouldn't the Child component run change detection when I click the "Change Immutably Wrapped in setTimeout" button (after the timeout). Because I'm changing the reference. Or is that not how it works?

Thanks.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-dpkge9?file=src%2Fapp%2Fparent.component.ts

**Comment by jnizet** [comment] 2021-09-06 18:40
> However, when I change the Parent back to OnPush and the Child to Default (or leave it blank) then I click the 'Do Nothing' button in the Parent component it seems to trigger change detection in the child component as well

It's expected behavior: the event in the parent component triggers the change detection of the parent, and change detection always cascades to child components, unless they're OnPush and their inputs haven't changed. Since your child component uses the default strategy, it's checked too after its parent is checked.

> If it is the expected behavior what actually does OnPush in the Parent change in the Child component's behavior when OnPush isn't explicitly set in the Child?

If all the ancestors of the child were using the default strategy, then any event detected by the Angular zone would trigger a check of the root component, and this check would cascade to the descendants, and the child would thus be checked. If one of the ancestors is OnPush, then this ancestor would only be checked in one of its inputs has changed, and if not, it wouldn't be checked, nor would any of its descendants.

> Furthermore, in the Stackblitz (with the Parent set to OnPush) shouldn't the Child component run change detection when I click the "Change Immutably Wrapped in setTimeout" button (after the timeout). Because I'm changing the reference. Or is that not how it works?

No, it shouldn't. The parent is OnPush, so it's checked only when an event is triggered from its own template or when one of its **inputs** change. `data` is not one of its inputs. So it isn't checked when `data` changes. And since it isn't checked, none of its descendants is checked.

I'm happy to help, but this should be a Stackoverflow question or a question in the ANgular Discord. Not an issue.

**Comment by shammy8** [comment] 2021-09-06 20:48
@jnizet thanks I think I'm starting to understand better now, think it's the part about it cascading that made me understand. I don't think any of the articles I've read has mentioned this.

Sorry, I posted on the Discord but didn't get a satisfying answer, I should have tried StackOverflow first. Just one more thing though.

Shouldn't we change the doc at https://angular.io/api/core/ChangeDetectionStrategy ? The bit about it applying to all child directive doesn't seem to be accurate at least the way I read it.

So from what I understand, in my StackBlitz with parent set to OnPush and Child set to Default, the reason the setInterval isn't doing anything isn't because the Child is inheriting OnPush from the parent but because the Parent doesn't invocate change detection so it doesn't cascade down to the Child.

**Comment by atscott** [comment] 2021-09-16 17:50
Closing as duplicate of #33731. The behavior is expected, but we do not have great documentation around the specifics of change detection.

**Closed by atscott** 2021-09-16 17:50 UTC
Labels: comp: core
