### ISSUE TITLE
Router: Cannot read property 'routes' of undefined (route._loadedConfig is undefined)

### ISSUE THREAD

**Issue by sgotre** [angular/angular#38755] opened 2020-09-09 10:28 UTC
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/router at [recognize.ts#L172](https://github.com/angular/angular/blob/10.0.x/packages/router/src/recognize.ts#L172)

### Is this a regression?
Probably not. 
same issue on version 6.0.8 https://github.com/angular/angular/issues/25660 (closed, missing repro code)
same issue on version 8.0.3  https://github.com/angular/angular/issues/32814 (closed, missing repro code)

### Description
- Having: Lazy Loaded Modules with Child Routes and secondary router outlet
- Opening a deep link `/(secondary:2)` to a secondary router-outlet with a lazy loaded child module crashes the app 
- It seems the error only happens on a homepage (primary router outlet route === '') 

## 🔬 Minimal Reproduction
Repro Code : https://github.com/teraone/ng-route-config-error  

Error happens only on home page when **directly** opening a link to a secondary router-outlet
- open https://ng-route-config-error.netlify.app/(secondary:2)

Does **not** happen when navigating to the same page: 
- open https://ng-route-config-error.netlify.app/
- click on Link "Please click here to navigate in the second outlet" => works
- if you then refresh the page you'll get the error

Does **not** happen when opening a secondary outlet which is NOT on the homepage
- open https://ng-route-config-error.netlify.app/2(secondary:2) 

## 🔥 Exception or Error
<pre><code>
ERROR Error: Uncaught (in promise): TypeError: can't access property "routes", route._loadedConfig is undefined
getChildConfig@http://localhost:4201/vendor.js:62906:9
processSegmentAgainstRoute@http://localhost:4201/vendor.js:62879:43
processSegment@http://localhost:4201/vendor.js:62846:29
processSegmentGroup@http://localhost:4201/vendor.js:62835:21
processChildren/children<@http://localhost:4201/vendor.js:62838:90
mapChildrenIntoArray/<@http://localhost:4201/vendor.js:60685:30
forEach@http://localhost:4201/vendor.js:60428:21
mapChildrenIntoArray@http://localhost:4201/vendor.js:60683:12
processChildren@http://localhost:4201/vendor.js:62838:46
processSegmentGroup@http://localhost:4201/vendor.js:62833:25
recognize@http://localhost:4201/vendor.js:62813:35
recognize@http://localhost:4201/vendor.js:62799:10
recognize$1/</<@http://localhost:4201/vendor.js:63040:106
_tryNext@http://localhost:4201/vendor.js:1991:27
_next@http://localhost:4201/vendor.js:1981:18
next@http://localhost:4201/vendor.js:2539:18
_next@http://localhost:4201/vendor.js:65890:26
next@http://localhost:4201/vendor.js:2539:18
notifyNext@http://localhost:4201/vendor.js:10225:26
_next@http://localhost:4201/vendor.js:66677:21
next@http://localhost:4201/vendor.js:2539:18
_next@http://localhost:4201/vendor.js:46142:26
next@http://localhost:4201/vendor.js:2539:18
_next@http://localhost:4201/vendor.js:2562:26
next@http://localhost:4201/vendor.js:2539:18
_next@http://localhost:4201/vendor.js:46142:26
next@http://localhost:4201/vendor.js:2539:18
_next@http://localhost:4201/vendor.js:46142:26
next@http://localhost:4201/vendor.js:2539:18
_next@http://localhost:4201/vendor.js:46142:26
next@http://localhost:4201/vendor.js:2539:18
_next@http://localhost:4201/vendor.js:8395:26
next@http://localhost:4201/vendor.js:2539:18
_complete@http://localhost:4201/vendor.js:3088:29
complete@http://localhost:4201/vendor.js:2551:18
notifyComplete@http://localhost:4201/vendor.js:2026:30
_complete@http://localhost:4201/vendor.js:66684:21
complete@http://localhost:4201/vendor.js:2551:18
_complete@http://localhost:4201/vendor.js:2569:26
complete@http://localhost:4201/vendor.js:2551:18
_complete@http://localhost:4201/vendor.js:2569:26
complete@http://localhost:4201/vendor.js:2551:18
_complete@http://localhost:4201/vendor.js:8409:37
complete@http://localhost:4201/vendor.js:2551:18
_next@http://localhost:4201/vendor.js:5642:34
next@http://localhost:4201/vendor.js:2539:18
_next@http://localhost:4201/vendor.js:58071:30
next@http://localhost:4201/vendor.js:2539:18
notifyNext@http://localhost:4201/vendor.js:2017:26
_next@http://localhost:4201/vendor.js:66677:21
next@http://localhost:4201/vendor.js:2539:18
_next@http://localhost:4201/vendor.js:2562:26
next@http://localhost:4201/vendor.js:2539:18
notifyNext@http://localhost:4201/vendor.js:2017:26
_next@http://localhost:4201/vendor.js:66677:21
next@http://localhost:4201/vendor.js:2539:18
_next@http://localhost:4201/vendor.js:46142:26
next@http://localhost:4201/vendor.js:2539:18
_next@http://localhost:4201/vendor.js:2562:26
next@http://localhost:4201/vendor.js:2539:18
_next@http://localhost:4201/vendor.js:8395:26
next@http://localhost:4201/vendor.js:2539:18
_next@http://localhost:4201/vendor.js:5640:30
next@http://localhost:4201/vendor.js:2539:18
_next@http://localhost:4201/vendor.js:58071:30
next@http://localhost:4201/vendor.js:2539:18
notifyNext@http://localhost:4201/vendor.js:2017:26
_next@http://localhost:4201/vendor.js:66677:21
next@http://localhost:4201/vendor.js:2539:18
_next@http://localhost:4201/vendor.js:2562:26
next@http://localhost:4201/vendor.js:2539:18
notifyNext@http://localhost:4201/vendor.js:2017:26
_next@http://localhost:4201/vendor.js:66677:21
next@http://localhost:4201/vendor.js:2539:18
subscribeToArray/<@http://localhost:4201/vendor.js:52289:20
_trySubscribe@http://localhost:4201/vendor.js:5182:25
subscribe@http://localhost:4201/vendor.js:5168:22
innerSubscribe@http://localhost:4201/vendor.js:66734:23
_innerSub@http://localhost:4201/vendor.js:2004:105
_tryNext@http://localhost:4201/vendor.js:1998:14
_next@http://localhost:4201/vendor.js:1981:18
next@http://localhost:4201/vendor.js:2539:18
subscribeToArray/<@http://localhost:4201/vendor.js:52289:20
_trySubscribe@http://localhost:4201/vendor.js:5182:25
subscribe@http://localhost:4201/vendor.js:5168:22
call@http://localhost:4201/vendor.js:1966:23
subscribe@http://localhost:4201/vendor.js:5163:31
call@http://localhost:4201/vendor.js:5676:23
subscribe@http://localhost:4201/vendor.js:5163:31
innerSubscribe@http://localhost:4201/vendor.js:66734:23
_innerSub@http://localhost:4201/vendor.js:2004:105
_tryNext@http://localhost:4201/vendor.js:1998:14
_next@http://localhost:4201/vendor.js:1981:18
next@http://localhost:4201/vendor.js:2539:18
_next@http://localhost:4201/vendor.js:46142:26
next@http://localhost:4201/vendor.js:2539:18
subscribeToArray/<@http://localhost:4201/vendor.js:52289:20
_trySubscribe@http://localhost:4201/vendor.js:5182:25
subscribe@http://localhost:4201/vendor.js:5168:22
call@http://localhost:4201/vendor.js:46123:23
subscribe@http://localhost:4201/vendor.js:5163:31
call@http://localhost:4201/vendor.js:1966:23
subscribe@http://localhost:4201/vendor.js:5163:31
call@http://localhost:4201/vendor.js:58051:23
subscribe@http://localhost:4201/vendor.js:5163:31
call@http://localhost:4201/vendor.js:5627:23
subscribe@http://localhost:4201/vendor.js:5163:31
call@http://localhost:4201/vendor.js:8384:23
subscribe@http://localhost:4201/vendor.js:5163:31
call@http://localhost:4201/vendor.js:5676:23
subscribe@http://localhost:4201/vendor.js:5163:31
call@http://localhost:4201/vendor.js:46123:23
subscribe@http://localhost:4201/vendor.js:5163:31
innerSubscribe@http://localhost:4201/vendor.js:66734:23
_innerSub@http://localhost:4201/vendor.js:2004:105
_tryNext@http://localhost:4201/vendor.js:1998:14
_next@http://localhost:4201/vendor.js:1981:18
next@http://localhost:4201/vendor.js:2539:18
notifyNext@http://localhost:4201/vendor.js:2017:26
_next@http://localhost:4201/vendor.js:66677:21
next@http://localhost:4201/vendor.js:2539:18
_next@http://localhost:4201/vendor.js:46142:26
next@http://localhost:4201/vendor.js:2539:18
_next@http://localhost:4201/vendor.js:46142:26
next@http://localhost:4201/vendor.js:2539:18
notifyNext@http://localhost:4201/vendor.js:2017:26
_next@http://localhost:4201/vendor.js:66677:21
next@http://localhost:4201/vendor.js:2539:18

</code></pre>

## 🌍  Your Environment

**Angular Version:**  10.1.0

<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 10.1.0
Node: 13.14.0
OS: darwin x64

Angular: 10.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1001.0
@angular-devkit/build-angular     0.1001.0
@angular-devkit/build-optimizer   0.1001.0
@angular-devkit/build-webpack     0.1001.0
@angular-devkit/core              10.1.0
@angular-devkit/schematics        10.1.0
@ngtools/webpack                  10.1.0
@schematics/angular               10.1.0
@schematics/update                0.1001.0
rxjs                              6.6.3
typescript                        4.0.2
webpack                           4.44.1

</code></pre>

**Anything else relevant?**

Reproducable in Chrome, Firefox, Safari

**Comment by atscott** [comment] 2020-09-09 19:04
Hi @sgotre, based on the reproduction, I think this is a duplicate of #12842 and should be fixed by https://github.com/angular/angular/commit/926ffcd8acedfc0e6870a14f48a886fa8531c750

The commit isn't part of any release yet, but will be in the `11.0.0-next.1` release today or tomorrow.

Closing as duplicate of #12842

**Closed by atscott** 2020-09-09 19:04 UTC
Labels: comp: router, router: directives, router: lazy loading

**Comment by sgotre** [comment] 2020-09-09 20:35
@atscott thanks for your quick response.
