### ISSUE TITLE
Fix background color for code-example elements inside of alerts of sub-sections

### ISSUE THREAD

**Issue by sjtrimble** [angular/angular#17639] opened 2017-06-20 17:15 UTC
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[ ] Bug report 
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Code snippets are not easily visible on certain backgrounds (contrast too low).

<img width="516" alt="screen shot 2017-06-20 at 10 15 38 am" src="https://user-images.githubusercontent.com/2958442/27346240-640ccc60-55a1-11e7-95f5-0c6e66db4e7b.png">

## Expected behavior
Code-example background color should be visible on all background colors. Update background color of code-example blocks within other elements with a background color.

## Minimal reproduction of the problem with instructions
https://aio-staging.firebaseapp.com/tguide/aot-compiler#compile-with-aot

Scroll down to blue `l-sub-section` with a code block `code-example` inside of it

## What is the motivation / use case for changing the behavior?
UX/UI

**Comment by IgorMinar** [comment] 2017-11-27 21:38
Is this still a problem? I can't reproduce it at https://aio-staging.firebaseapp.com/guide/aot-compiler

**Comment by gkalpak** [comment] 2017-11-28 09:56
I can still see the issue in https://next.angular.io/guide/aot-compiler (right **above** the [No arrow functions][1] section).

[1]: https://next.angular.io/guide/aot-compiler#no-arrow-functions

**Comment by IgorMinar** [comment] 2017-12-20 00:20
@gkalpak I think you are referring to:

<img width="1236" alt="screen shot 2017-12-19 at 4 12 35 pm" src="https://user-images.githubusercontent.com/216296/34184935-78f27358-e4d7-11e7-962d-dfb3035b6962.png">


I find that text to have similar contrast as the other text on the page with the exception of the `<code>` background (e.g. `.metadata.json` above), so I think we improved the situation a bit already.

**Comment by IgorMinar** [comment] 2017-12-20 00:24
I'm going to close this for now since I believe that we fixed the original issue. We should do a general audit of the contrast on the site and address any remaining issues separately.

**Closed by IgorMinar** 2017-12-20 00:24 UTC
Labels: comp: aio, flag: can be closed?, type: bug
