### ISSUE TITLE
Route does not resolve

### ISSUE THREAD

**Issue by fireflysemantics** [angular/angular#34535] opened 2019-12-22 21:04 UTC
This is a demo of the problem:

https://stackblitz.com/edit/angular-routing-with-resolver-observable?file=src%2Fapp%2Fpost-resolver.service.ts

Switching out `this.observeLoading$` with `of(false)` makes it work.

Here are more details:

First this does resolve:

```

    async resolve(
        route: ActivatedRouteSnapshot) {
        const topic = await of(false).pipe(
            switchMap((v) =>{
                console.log("MADE IT THIS FAR: ", v)
                return of(new Topic)
            })).toPromise()
        console.log("THE TOPIC RETURNED IS", topic)

        return topic;

```

In the above case it logs everything and performs the navigation.

In the below case it logs "MADE IT THIS FAR: false", but then it hangs.

```
    async resolve(
        route: ActivatedRouteSnapshot) {
        const id = route.paramMap.get('id')
        const topic = await this.cs.loadingTopicStore$.pipe(
            switchMap((v) =>{
                console.log("MADE IT THIS FAR: ", v)
                return of(new Topic)
            })).toPromise()
        console.log("THE TOPIC RETURNED IS", topic)

        return topic;
```

As far as I can tell the two scenarios are essentially the same.  The only difference is in the first we are using `of(false)` and in the second we are using `this.cs.loadingTopicStore$`, and both of these are firing since "MADE IT THIS FAR: " is logged in both cases.

Thoughts?

Link to Stackoverflow:

https://stackoverflow.com/questions/59447093/angular-resolver-not-resolving

**Comment by fireflysemantics** [comment] 2019-12-22 22:06
Solved .. but maybe add something to the documentation ... We need to use `takeWhile` when working with notifications from ReplaySubjects ....

```
        const topic = await this.cs.loadingTopicStore$.pipe(
            takeWhile(v => v != false, true),
            switchMap((v) => { ...
```

**Comment by fireflysemantics** [comment] 2019-12-22 23:27
Also in the above scenario, Angular does not provide any errors .. it just fails silently ...

**Comment by spock123** [comment] 2019-12-23 00:54
What does this have to do with Angular?

**Comment by textbook** [comment] 2019-12-23 08:49
As I've just commented on your SO question, this is because you're using an observable that doesn't complete with toPromise, which means you have a promise that doesn't resolve. That's why takeWhile, or any other operator that completes the observable, fixes the problem. That's nothing to do with Angular, which is just waiting for your promise to resolve.

**Comment by AndrewKushnir** [comment] 2019-12-23 18:19
It looks like the described error was not caused by Angular framework code and original problem is resolved, so I'm closing this ticket.

**Closed by AndrewKushnir** 2019-12-23 18:19 UTC
