### ISSUE TITLE
Documentation Link leads to 404 Page

### ISSUE THREAD

**Issue by TjarkGerken** [angular/angular#53479] opened 2023-12-10 12:31 UTC
### Describe the problem that you experienced

Clicking the Link to Command Reference on the Angular CLI Page https://angular.dev/tools/cli leads to a 404 Page (https://angular.dev/cli/commands) 

### Enter the URL of the topic with the problem

https://angular.dev/cli/commands

### Describe what you were looking for in the documentation

The conent of the Page: 
https://angular.dev/cli/commands

Command Reference
Discover CLI commands to make you more productive with Angular.

### Describe the actions that led you to experience the problem

1. Go to https://angular.dev/tools/cli
2. Scroll to the 4 Boxes 
3. Click on Command Reference
4. Get redirected to https://angular.dev/cli/commands
5. Get 404 Page

### Add a screenshot if that helps illustrate the problem

![image](https://github.com/angular/angular/assets/96004366/a2332046-efa6-4c19-8e7d-147035c02d68)

Link of Command Reference does not work

![image](https://github.com/angular/angular/assets/96004366/3cb45417-27a5-4256-8373-65139f12d188)

**Comment by JoostK** [comment] 2023-12-10 14:44
Thanks for the report, closing as duplicate of https://github.com/angular/angular/issues/52549.

**Closed by JoostK** 2023-12-10 14:44 UTC
