### ISSUE TITLE
Cannot pass object references into components that have been downgraded.

### ISSUE THREAD

**Issue by qisaw** [angular/angular#6856] opened 2016-02-03 00:37 UTC
Seems like you can only pass string interpolations into angular2 components that have been downgraded using the UpgradeAdapter, passing object references does not seem to work.  I have an ng1 Directive passing a variable `product` into an ng2 component that displays the name of this `product`.

_I am sorry about using ECMAScript, but my application has already got a mix of coffee and ES6. I want to try and remove all the coffee before I start adding TypeScript._
### ng1 Directive

``` javascript
angular.module('myApp.view1', [])
.directive('someDir', [ function() {
    return {
        scope: { },
        bindToController: true,
        template: '<div> <my-dir product="cont.myProduct"></my-dir></div>',
        controller: function someController ($scope) {
            this.myProduct = {
                name: 'SomeName'
            };
        },
        controllerAs: 'cont'
    }
}]);
```
### ng2 Component

``` javascript
@Component({
    selector: 'my-dir',
    template: 
    <div>
        {{product.name}}
    </div>,
})
export class MyDir  {
    @Input() product;
    ngOnInit() {
        console.log(typeof this.product);
        console.log(this.product);
    }
}
```

The `ngOnInit` function prints `string` and `"cont.myProduct"`. This is unexpected as the literal string value that is passed to the product attribute is being passed the `MyDir` instead of the `Object`. 
The `ngOnInit` function should really be printing `Object` and `Object {name: "Wasiq"}`

If however I change the template of the ng1 Directive to use string interpolation, then the `stringified` value of the `product` object is passed correctly to the directive. 
i.e.

``` javascript
angular.module('myApp.view1', [])
.directive('someDir', [ function() {
    return {
        scope: { },
        bindToController: true,
        template: '<div> <my-dir product="{{cont.myProduct}}"></my-dir></div>',
        controller: function someController ($scope) {
            this.myProduct = {
                name: 'SomeName'
            };
        },
        controllerAs: 'cont'
    }
}]);
```

Then the `ngOnInit` function of the ng2 component prints `string` and `"{"name":"SomeName"}` which is expected as the `myProduct` variable on `someDir` is being passed as a `string` instead of an object reference.

**Comment by trezm** [comment] 2016-06-01 16:14
I have seen the same issue, quite frustrating!!!

**Comment by adarshtandon** [comment] 2016-08-23 16:08
try this

angular.module('myApp.view1', [])
.directive('someDir', [ function() {
    return {
        scope: { },
        bindToController: true,
        template: '<div> <my-dir  [product]="cont.myProduct"></my-dir></div>',
        controller: function someController ($scope) {
            this.myProduct = {
                name: 'SomeName'
            };
        },
        controllerAs: 'cont'
    }
}]);

**Comment by kevindqc** [comment] 2016-10-12 15:35
Hi,

I reproduced your issue on this plunkr:
https://plnkr.co/edit/MyxolMjkaRVovieKu4KT?p=preview

It seems to work fine if, in the angular1 template, I change:
`<div><my-dir product="cont.myProduct"></my-dir></div>`

to
`<div><my-dir [product]="cont.myProduct"></my-dir></div>`

**Comment by qisaw** [comment] 2017-03-13 02:07
That will require rewriting basically every ng-1 component that interacts with any ng-2 component. Seems quite wierd, it's supposed to be an ng-1 component, not a crazy hybrid right?

**Comment by gkalpak** [comment] 2017-03-13 13:14
> That will require rewriting basically every ng-1 component that interacts with any ng-2 component.

This sounds like a bit of an overstatement :smiley:

What is indeed required, is using the appropriate attribute names in AngularJS (ng1) templates, so that Angular (ng2) can recognize the syntax and do the right thing.

For binding to Angular component properties, this means using `bind-<prop>` or `[prop]` :smiley:
Using just `<prop>` has different semantics in Angular (ng2), so even if we ngUpgrade automatically convert syntaxes, we would be hurting other usecases and changing template semantics for no good reason.

Note that the right had side (the attribute _value_) is still evaluated in the AngularJS world, so follows the AngularJS semantics. This is just a general heads-up; it doesn;t make any difference here.

##
Closing, since this already works as expected (and as [documented][1]).

[1]: https://angular.io/docs/ts/latest/guide/upgrade.html#!#using-angular-components-from-angularjs-code

**Closed by gkalpak** 2017-03-13 13:14 UTC
Labels: comp: upgrade/dynamic

**Comment by rasikat86** [comment] 2019-01-24 06:12
So this won't work for components having attribute selectors?
