### ISSUE TITLE
FormControl incorrectly rendered as disabled after updating underlying model

### ISSUE THREAD

**Issue by mstawick** [angular/angular#41881] opened 2021-04-29 12:21 UTC
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/forms

### Is this a regression?
I don't think so

### Description
An initially disabled form control is still rendered as disabled, even though the underlying model is changed, and in the updated model, the control is not disabled anymore. Please see the attached reproduction.

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-ncp9ol?file=src/app/app.component.ts

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 11.2.8
Node: 14.14.0
OS: linux x64

Angular: 11.2.9
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1102.8
@angular-devkit/build-angular      0.1102.8
@angular-devkit/core               11.2.8
@angular-devkit/schematics         11.2.8
@angular/cdk                       11.2.8
@angular/cli                       11.2.8
@angular/material                  11.2.8
@angular/material-moment-adapter   11.2.8
@schematics/angular                11.2.8
@schematics/update                 0.1102.8
rxjs                               6.6.7
typescript                         4.0.5
</code></pre>

**Comment by destus90** [comment] 2021-04-30 04:53
Duplicate of https://github.com/angular/angular/issues/22556

Workaround: https://stackblitz.com/edit/angular-m3eqzp?file=src%2Fapp%2Fapp.component.ts

**Comment by mstawick** [comment] 2021-04-30 06:43
I figured out this workaround, however, this reproduction is trivial (simplifying it lost my original issue/use case). The same thing happens when using a FormGroup with {value: 'foo', disabled: true/false} syntax, like here:
https://stackblitz.com/edit/angular-qgkxaw

```
...
constructor(private fb: FormBuilder) {
    this.form = this.fb.group({
      test: [{ value: "foo", disabled: true }]
    });
  }

  doTest() {
    this.form = this.fb.group({
      test: [{ value: "bar", disabled: false }]
    });
  }
...
```

If I then need to fetch each control for which I need to apply the workaround, it becomes very cumbersome.

**Comment by AndrewKushnir** [comment] 2021-04-30 22:41
Closing as a duplicate of #22556.

**Closed by AndrewKushnir** 2021-04-30 22:41 UTC
Labels: comp: forms
