### ISSUE TITLE
Error when a large number of elements

### ISSUE THREAD

**Issue by grehovm** [angular/angular#6848] opened 2016-02-02 20:54 UTC
I test angular2 for form with many elements(300-400) and get errors. Then i test angular1 and it's ok.
[angular1](http://plnkr.co/edit/LOAZiWum4hRsNPlgMKyy?p=preview)
[angular2](http://plnkr.co/edit/VuhCUzdmChi1EN6zHz4b?p=preview)
chrome message: `RangeError: Maximum call stack size exceeded`
forefox message: `InternalError: too much recursion`

**Comment by mohammedzamakhan** [comment] 2016-02-04 10:46
Same as #3558

**Comment by pkozlowski-opensource** [comment] 2016-08-06 09:57
Duplicate of #3558

**Closed by pkozlowski-opensource** 2016-08-06 09:57 UTC
Labels: comp: core/forms, type: bug
