### ISSUE TITLE
Form with only disabled elements has "{valid: false, invalid: false}"

### ISSUE THREAD

**Issue by StefanKern** [angular/angular#39754] opened 2020-11-19 08:44 UTC
# 🐞 bug report

### Affected Package
found in "10.0.14" and "8.0.0"

### Description
Creating a reactive `FormGroup` with one or more disabled `FormControl` results in the status of the `FormGroup` beeing `{valid: false, invalid: false}`. This is inconsitent because a `FormGroup` wihtout any elements has the staus `{valid: true, invalid: false}`.

Since per definition [w3.org definition](https://www.w3.org/TR/html401/interact/forms.html#h-17.12.1), so the disabled attribute prevents any interaction with the element, the expected behaviour is that a disabled `FormControl` doesn't have any effect on the status of the `FormGroup`.

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-8-reactive-form-validation-e1uhin?file=app%2Fapp.component.ts

```
  ngOnInit() {
    this.registerForm = this.formBuilder.group({
      email: new FormControl({ value: "1", disabled: true }, [
        Validators.required,
        Validators.email
      ])
    });
  }

  onSubmit() {
    // the form group is invalid
    if (this.registerForm.invalid) {
      return;
    }

    // however the form is not valid
    // if (!this.registerForm.valid) {
    //   return;
    // }

    // display form values on success
    alert(
      "SUCCESS!! :-)\n\n" +
        JSON.stringify(
          {
            valid: this.registerForm.valid,
            invalid: this.registerForm.invalid
          },
          null,
          4
        )
    );
```

```
        <form [formGroup]="registerForm" (ngSubmit)="onSubmit()">
            <div class="form-group">
                <label>Email</label>
                <input type="text" formControlName="email" class="form-control" [ngClass]="{ 'is-invalid': submitted && f.email.errors }" />
                <div *ngIf="submitted && f.email.errors" class="invalid-feedback">
                    <div *ngIf="f.email.errors.required">Email is required</div>
                    <div *ngIf="f.email.errors.email">Email must be a valid email address</div>
                </div>
            </div>
            <div class="text-center">
                <button class="btn btn-primary mr-1">Register</button>
                <button class="btn btn-secondary" type="reset" (click)="onReset()">Cancel</button>
            </div>
        </form>
```

**Comment by destus90** [comment] 2020-11-19 16:22
Related to https://github.com/angular/angular/issues/39287

**Comment by AndrewKushnir** [comment] 2020-11-19 18:53
Hi @StefanKern, as it was mentioned in the previous comment, this ticket is related to #39287 and is likely to have the same root cause, so I'm closing this one in favor of #39287. Thank you.

**Closed by AndrewKushnir** 2020-11-19 18:53 UTC
Labels: comp: forms, forms: Controls API, forms: disabling controls
