### ISSUE TITLE
Could not load the summary for directive

### ISSUE THREAD

**Issue by mbossX** [angular/angular#15506] opened 2017-03-26 14:45 UTC
**angular 4.0** 
when I run:  `ng build -prod -aot`

_ERROR in Illegal state: Could not load the summary for directive MyApp in E:/Programming/WEB/projects/8ju/cow/src/app/app.ts._

this is my app.ts

```
import { Component } from '@angular/core';
import { NgModule }      from '@angular/core';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';


import { PagesModule } from './pages/pages-module';
import { ServicesModule } from './Services/services-module';

@NgModule({
  imports: [
    PagesModule,
    ServicesModule
  ],
  declarations: [
    MyApp,
  ],
  providers: [
    // appRoutingProviders,
    // HttpService
  ],
  bootstrap:    [ MyApp ]
})
@Component({
    selector: 'app-root',
    template: `
                <root></root>
              `
})
export class MyApp {
  constructor() {
  }
}

Array.prototype['replace'] = function (arr: any[]) {
  if (arr && Array.isArray(arr)) {
    this.splice(0, this.length);
    arr.forEach(item => {
      this.push(item);
    });
  }
};

```

**Comment by 1424667164** [comment] 2017-03-26 14:46
by the way, `ng build` and `ng serve` is fine.

**Comment by DzmitryShylovich** [comment] 2017-03-26 14:51
Please provide a small repo that reproduces the issue. thanks

**Comment by 1424667164** [comment] 2017-03-26 15:13
Please check [this](https://github.com/1424667164/ng4_issue)

**Comment by lalitjairaj** [comment] 2017-05-25 13:50
Any luck with this problem... facing the same issue

**Comment by wangzhengzhang** [comment] 2017-06-07 07:10
@1424667164  , It seems that you app.ts file has @NgModule annotation but don't export module name.

**Comment by tbosch** [comment] 2017-10-03 20:42
@1424667164 Did this ever work? As we don't support `@NgModule` and `@Component` on the same class...

**Comment by pkozlowski-opensource** [comment] 2018-10-26 12:42
Going to close this one as it seems that the original problem was due to using `@Component` and `@NgModule` annotations on the same class which was never supported (and there is no intention of supporting it).

**Closed by pkozlowski-opensource** 2018-10-26 12:42 UTC
Labels: comp: core & compiler, freq1: low, severity3: broken, state: Follow Up, type: bug/fix
