### ISSUE TITLE
FormBuilder not supporting new Angular 5 AbstractControlOptions

### ISSUE THREAD

**Issue by udos86** [angular/angular#19849] opened 2017-10-21 11:06 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Based on `5.0.0-rc.3`  it seems that [`FormBuilder`](https://github.com/angular/angular/blob/5.0.0-rc.3/packages/forms/src/form_builder.ts) has not been updated to support new Angular 5 [`AbstractControlOptions`](https://github.com/angular/angular/blob/5.0.0-rc.3/packages/forms/src/model.ts#L83) (respectively `FormHooks`) for creating a `FormControl`, `FormGroup` or `FormArray`.

## Expected behavior
`FormBuilder` allowing the passing of new `AbstractControlOptions` when creating a `FormControl`, `FormGroup` or `FormArray` in Angular 5.

## What is the motivation / use case for changing the behavior?

Being able to use both `FormBuilder` as well as new `AbstractControlOptions` in Angular 5.

## Environment

<pre><code>Angular version: 5.0.0-rc.3</code></pre>

**Comment by kara** [comment] 2017-11-22 00:31
Dupe of https://github.com/angular/angular/issues/19163

**Closed by kara** 2017-11-22 00:31 UTC
Labels: comp: forms, type: feature
