### ISSUE TITLE
docs(aio) plunker example throws error

### ISSUE THREAD

**Issue by aravindfz** [angular/angular#16765] opened 2017-05-12 21:30 UTC
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Navigating to the [dynamic-component](https://angular.io/docs/ts/latest/cookbook/dynamic-component-loader.html) documentation and trying to refer to the live example plunker at the [link](https://angular.io/resources/live-examples/cb-dynamic-component-loader/ts/eplnkr.html) does not execute the code but throws errors

**Expected behavior**
Example should be seen

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` = **7.2**

**Comment by gkalpak** [comment] 2017-05-15 08:12
The demo seems to work, but there is indeed an error in the console 😕

**Comment by echonax** [comment] 2017-05-19 09:53
@gkalpak I think the problem you are refering to is the expression has changed after it has been checked. But @aravindfz says the example can't be seen. What I've realized is that when you use an ad-blocker with your browser, it doesn't play well with the ad-banner.component (see the name tragedy here? :-)) and example is not running. Disabling the ad-blocker seems to solve the issue. Maybe @aravindfz can confirm this?

**Comment by gkalpak** [comment] 2017-05-19 10:07
Aha! That makes sense. I have no add blocker and I only see the "expression has changed after it has been checked" error. We should probably change that component's name :smiley:

**Comment by echonax** [comment] 2017-05-19 10:55
Btw, the expression problem can be solved by adding `this.cdr.detectChanges();` at the last line of `loadComponent()` method in `AdBannerComponent`. Fixed plunker: https://plnkr.co/edit/G73PI5S8fXRRtnXvq5KY?p=preview

**Comment by wardbell** [comment] 2017-06-23 00:34
A duplicate of the later #17158. Keeping that one because it has deeper discussion.

**Closed by wardbell** 2017-06-23 00:34 UTC
Labels: comp: docs
