### ISSUE TITLE
docs(tutorial): Organization of content about master/detail could be better

### ISSUE THREAD

**Issue by manaswinidas** [angular/angular#24634] opened 2018-06-22 20:18 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[X] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

The Master/Detail(Part 5) and the Routing links(Part 7) lead to blank pages

## Expected behavior

The Master/Detail and the Routing links should be populated with the required information

## Minimal reproduction of the problem with instructions
The Master/Detail thing has already been discussed in the previous section(Part 4), either remove the sidebar link or shift the Master/Detail component to the link. The Routing link too needs to be populated or removed if it isn't required
## What is the motivation / use case for changing the behavior?

As per earlier angular.io issue #3396, the lack of clarity, accuracy & detail in sidebar links make it difficult for new learners to follow along. These issues can result in putting code in the wrong place, breaking the app and making it difficult to continue with the tutorial.

## Environment
Not required, since this is a Documentation issue

**Comment by jenniferfell** [comment] 2018-06-26 17:52
Thanks for letting us know what you're seeing. 

Master/Detail and Routing do have pages associated with them, and they should not be blank. They don't appear blank to me; I see the intended content.

I think this might be related to a more general issue with intermittent blank pages: 
https://github.com/angular/angular/issues/24392

Reloading the page generally resolves the immediate problem and displays the page content.

If you're seeing intermittent blank pages, do you mind if I close this as duplicate? 
If you're persistently seeing blank pages, is there an error or something in the inspector that might help us understand why you're not seeing the content?

(Separate issue: Regarding the mismatch between navigation numbers and directory names, my team is working on a fix. Our goal is to fix without breaking bookmarks and related links, as a near-term fix. PR in progress here: https://github.com/angular/angular/pull/24628) 

Thanks again!

**Comment by jenniferfell** [comment] 2018-06-26 18:00
I re-read your notes, and I potentially hear three things, so please forgive me for asking for clarification: 

1. You're seeing blank pages when you choose Master/Detail or Routing from the left nav?

2. You'd like to see the numbers in the left nav match the directory names (Master/Detail is part 5 in the nav but toh-pt3 in the files)?

3. You'd like to see us organize the content differently, moving some content to different sections or changing titles to be a better match? "The Master/Detail thing has already been discussed in the previous section(Part 4), either remove the sidebar link or shift the Master/Detail component to the link." 

Thanks!

**Comment by manaswinidas** [comment] 2018-06-26 18:55
1. I'm seeing blank pages when I choose Master/Detail or Routing from the left nav
2. I'd like you to remove the blank pages if that isn't affecting the consistency of the tutorial as a whole as I'm not getting any content when I reload the pages. I'd like to see you organize the content differently(referring to Part 4 of the tutorial), moving some content to different sections or changing titles to be a better match.

**Comment by jenniferfell** [comment] 2018-06-28 22:10
Thanks! 
1. Always blank or sometimes blank? Browser type and version? These blank pages are in addition to the real content for those modules, they don't replace it? Maybe a screen shot would help? We haven't defined an blank pages (so we can't remove blanks), so I'm trying to figure out if this is a build or runtime issue. Thanks!

2. Gotcha. I see your point esp wrto the master/detail info being started in one tutorial section and then continued in the section with that name.

**Comment by manaswinidas** [comment] 2018-06-29 14:52
I tried opening the tutorial with Chrome and it worked fine. But when I tried opening it with Mozilla v60.0.2(64-bit version), I encountered the above issue. I have attached a screenshot below.
![image](https://user-images.githubusercontent.com/22885912/42098939-dde655f6-7bd9-11e8-8cdb-5c022ff4d954.png)

**Comment by jenniferfell** [comment] 2018-07-02 21:37
Thanks for testing in both browsers and for the screen shot. It works for me right now in Firefox and Chrome, so I do think the blank pages are related to this issue: https://github.com/angular/angular/issues/24392

**Comment by jenniferfell** [comment] 2018-07-03 00:41
Quick summary.

Blank pages = bug and duplicate of issue https://github.com/angular/angular/issues/24392

Remaining request is an info-arch feature request: " I'd like to see you organize the content differently(referring to Part 4 of the tutorial), moving some content to different sections or changing titles to be a better match. The Master/Detail thing has already been discussed in the previous section(Part 4), either remove the sidebar link or shift the Master/Detail component to the link."

Super. Thanks! We're looking at near-term and longer-term (bigger) changes to the Tutorial, so if you don't see near-term work, know that we're considering this in our bigger changes. Thanks again for your patient and explanations.

**Comment by jenniferfell** [comment] 2018-09-25 15:37
Quick fix for numbering of TOH Tutorial navigation v. filenames (for content and for examples) is WIP In PR https://github.com/angular/angular/pull/26099

**Comment by jenniferfell** [comment] 2018-10-05 20:16
There were three things in this PR: 

1. Blank pages. This is an AIO infrastructure issue, but it can't be reliably reproduced. I'd like to consider this closed, but if you do find a reliable way to reproduce, then please open a new issue or add comments to #24392. 

2. Numbering of parts didn't match between navigation and filenames (.md files and example files). This has been resolved and merged into v7/next. https://github.com/angular/angular/pull/25776

3. Organization of content about master/detail could be better. The subject begins in part 2 (https://angular.io/tutorial/toh-pt2#masterdetail) and then continues as part 3 (https://angular.io/tutorial/toh-pt3). This is not resolved. 

Summary: Leaving PR open as a feature request for 3rd item above. Changing PR title to match that request. Thanks!

**Comment by aikidave** [comment] 2021-05-26 03:16
The documentation has undergone significant changes since this issue was opened. I'm closing it for now. If there's more to be done on this, please let me know!

**Closed by aikidave** 2021-05-26 03:16 UTC
Labels: P4, comp: docs, docsarea: tutorial, feature, subtype: docs-infoarch
