### ISSUE TITLE
Get an error when compilationing (angular 5)

### ISSUE THREAD

**Issue by teabagp** [angular/angular#20507] opened 2017-11-17 14:59 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Ater update to Angular 5 I get an error when compiling my app:
`Could not resolve './data-grid' from dist\node_modules\devextreme-angular\ui\data-grid.ngfactory.js`

## Expected behavior

Such errors did not have when I use the angular 4 
## Minimal reproduction of the problem with instructions

You can see my [example](https://github.com/teabagp/rollup).
Use the following commands:
- npm i
- npm run build

## Environment

<pre><code>
Angular version: 5.0.1

**Comment by bgarel** [comment] 2017-11-17 15:34
It is the same bug as issue #200006

**Comment by mhevery** [comment] 2017-11-28 23:47
Duplicate of #20006

**Closed by mhevery** 2017-11-28 23:47 UTC
Labels: comp: core & compiler
