### ISSUE TITLE
Save bytes by stripping error messages from production builds

### ISSUE THREAD

**Issue by pborunda** [angular/angular#15048] opened 2017-03-09 21:22 UTC
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Human readable error text is informative only and can't be minified for production build. This text does not compress well with gzip.

**Expected behavior**

Suggest moving this informative error text to console.error() to work well with UglifyJS drop_console. 

**Minimal reproduction of the problem with instructions**

From
new Error("long informative error message...")
To
console.error("long informative error message...")
new Error()

**What is the motivation / use case for changing the behavior?**

Informative-only error strings are verbose and cannot be dropped in minification.
Suggest moving most informative-only human-readable text to console.error() to work well with UglifyJS options drop_console. It might not be significant, but minification saving may be 4 or 5 KB for total build.
Top affected files are:
./forms/src/directives/error_examples.ts (1217 bytes of informative text)
./forms/src/directives/reactive_error.ts (1286 bytes of informative text)
./forms/src/directives/template_driven_errors.ts (1415 bytes of informative text)
./common/src/facade/errors.ts
./core/src/di/reflective_errors.ts
./core/src/facade/errors.ts
./core/testing/facade/errors.ts

**Please tell us about your environment:**

Windows 7
* **Angular version:** 2.0.X

2.4.9

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 all
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript
Webpack AOT
UglifyJS minify compiler

* **Node (for AoT issues):** `node --version` =   
7.2.1

**Comment by robwormald** [comment] 2017-03-11 22:07
In AngularJS, we had a build step that rewrote long-form text errors to a URL for production. @IgorMinar is this something we want to do in the future, perhaps with a typescript transform?

**Comment by IgorMinar** [comment] 2017-03-13 19:09
yeah. we'll get around to this. but we have other places to shave off bytes before this stuff starts to matter.

**Comment by IgorMinar** [comment] 2018-08-06 18:47
Thanks for reporting this issue. However this issue is a duplicate of an existing issue #6173. Please subscribe to that issue for future updates.

**Closed by IgorMinar** 2018-08-06 18:47 UTC
Labels: comp: core & compiler, comp: packaging, type: feature
