### ISSUE TITLE
NgUpgrade should unify Angular 1 and Angular 2 form validation

### ISSUE THREAD

**Issue by noamichael** [angular/angular#9213] opened 2016-06-15 12:55 UTC
- **I'm submitting a ...**
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

**Current behavior**
When utilizing ngUpgrade in a hybrid Angular 1/2 app, inputs validated by Angular 2 are not recognized as valid by Angular 1.

**Expected/desired behavior**
- **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
  http://plnkr.co/edit/gOE0qO5JGlmv4YHbKpCH?p=preview

~~NOTE: This plnkr has stopped working since RC2.~~
The plnkr has been fixed
- **What is the expected behavior?**
  Angular2 (or ngUpgrade) should notify Angular 1 when a input becomes valid/invalid.
- **What is the motivation / use case for changing the behavior?**
  In my Angular 1 App, many controls, such as "save", are disabled when a form in considered invalid or pristine. During my conversion to Angular 2, I seemingly have no way to properly manage this disabled state because Angular 2 components and the forms within are a complete black-box to Angular 1.
- **Please tell us about your environment:**
  Project is built with gulp. Typescript files are loaded and transpiled in browser with JSPM.
- **Angular version:** 2.0.0-rc-1 AND Angular 1.5.6 
- **Browser:** All
- **Language:** All

**Comment by IgorMinar** [comment] 2016-06-17 18:49
I would strongly recommend that you migrate the whole form over to Angular 2 rather than just small parts of it. Form handling is a complex issue and as you noticed we currently don't do anything to unify Angular 1 and Angular 2 form handling. We might do this in the future, but the current workaround of migrating the whole form is acceptable for most applications.

**Comment by marcalj** [comment] 2016-06-18 20:26
The problem is when using third party UI modules that are not yet fully migrated to NG2 (angular-ui-bootstrap, angular-strap, etc).

It's a big stopper for us on the fully migration to NG2.

The reason why i'm in the process of migration is due to one "infinite scrolling view" we had with terrible poor performance in NG1, and really fast with NG2, **so congrats team!!! You did an excellent job** (in dynamic mode BTW, so I'm expecting better performance when I can use the ```ngc``` compiler.

I have one big issue with a directive using ```forwardRef```ing the parent component. It doesn't boot the main NG1 app, but it will when the source is compiled and minified (dynamic mode BTW). Hard to reproduce but I'll try.
Another one is, don't know why, the NG1 app don't trigger the first route, so I have to use a hack with ```pushState``` and go back location to trigger the original one.

**Comment by petebacondarwin** [comment] 2016-12-23 11:21
@marcalj - please open new issues for each of your problems.

* we are considering basic `ngModel` <-> `ControlValueAccessor` connectivity. See #10578
* try moving to the newer `upgrade/static` library. It has support for AoT and doesn't require the use of `forwardRef`
* this is possibly due to the router running its initial navigation before the Angular 1 app has booted. Try turning off initial navigation and then triggering it from inside a component of your app.

**Closed by petebacondarwin** 2016-12-23 11:21 UTC
Labels: comp: upgrade/dynamic, type: feature
