### ISSUE TITLE
Wrong error -- Error: NG0300: Multiple components match node with tagname app-tooltip

### ISSUE THREAD

**Issue by emilalsgndr** [angular/angular#42149] opened 2021-05-18 14:48 UTC
![Screen Shot 2021-05-18 at 18 45 28](https://user-images.githubusercontent.com/71174614/118672800-92ad9d00-b809-11eb-96a9-268d1ebb634f.png)
![Screen Shot 2021-05-18 at 18 45 40](https://user-images.githubusercontent.com/71174614/118672821-950ff700-b809-11eb-993c-75a90093d183.png)
![Screen Shot 2021-05-18 at 18 46 04](https://user-images.githubusercontent.com/71174614/118672826-95a88d80-b809-11eb-8b9f-fe40d70c237c.png)

**Comment by JoostK** [comment] 2021-05-18 15:30
This looks like a bug I'd request that you share a minimal reproduction.

**Comment by AndrewKushnir** [comment] 2021-05-18 19:26
FYI, I've seen a similar problem when there is some other error that happened (in my case it was in DI), but it was in try-catch block, thus preventing further execution with corrupted data structures, see #41383. Try checking the "Pause on caught exceptions" checkbox in Chrome DevTools (the "Sources" tab) and see if there are some caught errors. If that doesn't help, as Joost mentioned above, we'd need a repro to investigate this issue further.

**Comment by JoostK** [comment] 2021-06-18 18:06
Closing due to lack of reproduction. Please open a new issue if you can share additional information on when this happens.

**Closed by JoostK** 2021-06-18 18:06 UTC
Labels: comp: compiler, needs reproduction
