### ISSUE TITLE
hydration problems with ng-content

### ISSUE THREAD

**Issue by robertIsaac** [angular/angular#50175] opened 2023-05-05 21:44 UTC
# 🐞 Bug report

#### What modules are related to this issue?

- [ ] builders
- [ ] common
- [x] express-engine

### Is this a regression?

no

### Description

when enabling hydration and passing content with ng-content, the ng-content is filled with nothing

3 changes that fixes the issue
1. instead of using Material to use `<div><ng-content></ng-content></div>` (so it only happens with Angular Material, no idea why sorry)
2.  if I moved the actual content inside the layout component instead of passing it from `app.component.html`
3. remove `provideClientHydration()`

## 🔬 Minimal Reproduction
https://github.com/robertIsaac/hydration-problem

## 🔥 Exception or Error

NA

## 🌍 Your Environment

<pre><code>
Angular CLI: 16.0.0
Node: 16.18.1
Package Manager: npm 8.19.2
OS: win32 x64

Angular: 16.0.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, material, platform-browser, platform-browser-dynamic
... platform-server, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1600.0
@angular-devkit/build-angular   16.0.0
@angular-devkit/core            16.0.0
@angular-devkit/schematics      16.0.0
@nguniversal/builders           16.0.0
@nguniversal/express-engine     16.0.0
@schematics/angular             16.0.0
rxjs                            7.8.1
typescript                      5.0.4
</code></pre>

**Comment by AndrewKushnir** [comment] 2023-05-06 18:53
@robertIsaac thanks for reporting the problem and sharing a repro, the repro is very helpful 👍 

I noticed is that the problem happens when there is a view container (`*ngFor`) in use:

```
 <app-layout>
  <p *ngFor="let content of fillerContent">{{content}}</p>
 </app-layout>
```
when there is no view container as a root node, content projection works fine.

As a temporary solution, you could try wrapping projected content into an element like this:

```
 <app-layout>
   <div>
     <p *ngFor="let content of fillerContent">{{content}}</p>
   </div>
 </app-layout>
```

We'll perform further investigation and will keep this thread updated.

Thank you.

**Comment by robertIsaac** [comment] 2023-05-06 18:56
> @robertIsaac thanks for reporting the problem and sharing a repro, the repro is very helpful 👍 
> 
> I noticed is that the problem happens when there is a view container (`*ngFor`) in use:
> 
> ```
>  <app-layout>
>   <p *ngFor="let content of fillerContent">{{content}}</p>
>  </app-layout>
> ```
> when there is no view container as a root node, content projection works fine.
> 
> As a temporary solution, you could try wrapping projected content into an element like this:
> 
> ```
>  <app-layout>
>    <div>
>      <p *ngFor="let content of fillerContent">{{content}}</p>
>    </div>
>  </app-layout>
> ```
> 
> We'll perform further investigation and will keep this thread updated.
> 
> Thank you.

Well in the real case there is no ngfor and it doesn't work, but it's complicated one

FYI using router-outlet also make it not working

**Comment by AndrewKushnir** [comment] 2023-05-07 23:35
> FYI using router-outlet also make it not working

Thanks for additional information. The `<router-outlet>` under the hood also uses view container APIs to create a component for a route, so this may have the same root cause. I was able to reproduce the problem locally and the issue happens when a view container is projected from a hydrated component to a component that skips hydration (and re-creates all nodes). I'll work on a fix and share an update when I have it.

Meanwhile, could you please try wrapping the `<router-outlet>` into an extra element to see if that resolves the issue? For example:

```
<app-layout>
  <div>
    <router-outlet />
  </div>
</app-layout>
```

Thank you.

**Comment by AndrewKushnir** [comment] 2023-05-08 02:35
@robertIsaac I've created a draft version of a fix for this issue, could you please try to test the behavior of your application with this fix applied?

You can update the `package.json` file locally and replace the `@angular/core` dependency with the following package:
```
  ...
  "@angular/core": "https://output.circle-artifacts.com/output/job/9a9e6935-0c92-4744-aedb-a26d79e479d4/artifacts/0/angular/core-pr50199-adc2a499e1.tgz",
  ...
```

After that you can run `npm install --force` and test the behavior of the app once again.

Please let us know if that resolved the issue.

Thank you.

**Comment by robertIsaac** [comment] 2023-05-08 08:13
> @robertIsaac I've created a draft version of a fix for this issue, could you please try to test the behavior of your application with this fix applied?
> 
> You can update the `package.json` file locally and replace the `@angular/core` dependency with the following package:
> 
> ```
>   ...
>   "@angular/core": "https://output.circle-artifacts.com/output/job/9a9e6935-0c92-4744-aedb-a26d79e479d4/artifacts/0/angular/core-pr50199-adc2a499e1.tgz",
>   ...
> ```
> 
> After that you can run `npm install --force` and test the behavior of the app once again.
> 
> Please let us know if that resolved the issue.
> 
> Thank you.

no it doesn't fix it
also it doesn't fix the router-outlet one
but fix the reproduction example
I have updated it to be the router-outlet case

FYI adding `div` around the content in my real application fixed the problem

**Comment by AndrewKushnir** [comment] 2023-05-09 01:51
@robertIsaac thanks for the update. The fix was applied to the Embedded Views code path only, but not the Component path. I've added the necessary changes and you can test the behavior using the following package:

```
  ...
  "@angular/core": "https://output.circle-artifacts.com/output/job/20b4bcba-871c-4700-a621-d4f9dcb60f78/artifacts/0/angular/core-pr50199-ec9f3d6e6c.tgz",
  ...
```

I've tested this package with the repro and hydration works correctly there now. Could you please try to test the fix in your real application as well and let us know if it resolved the issue?

Thank you.

**Closed** 2023-05-09 21:46 UTC
Labels: area: core, state: has PR, P2, core: hydration

**Comment by AndrewKushnir** [comment] 2023-05-10 18:27
Just wanted to share a quick update: Angular v16.0.1 was released today. Angular v16.0.1 includes the fix for this issue, please try updating to v16.0.1 and let us know if he problem still exists. Thank you.

**Comment by robertIsaac** [comment] 2023-05-10 22:00
> Just wanted to share a quick update: Angular v16.0.1 was released today. Angular v16.0.1 includes the fix for this issue, please try updating to v16.0.1 and let us know if he problem still exists. Thank you.

thank you for your update and quick fix
I confirm the reprod works fine, but for my application I can't verify it for now, if when I test it found the problem still existing I add a new comment here
