### ISSUE TITLE
Support direct child selector

### ISSUE THREAD

**Issue by jelbourn** [angular/angular#13918] opened 2017-01-13 18:06 UTC
Feature request to support selectors like
```
md-input-container > input
```

This would help reduce boilerplate for directives where some predetermined structure is required. Some scenarios where this could be useful:
* The Angular Material `md-input-container` (example used above)
* Any instance where native HTML elements dictate a specific structure, e.g., `<table>` containing `<tr>`
```
myCustomTable > tr
```

This should take into consideration the combination of multiple direct-child operators:
```
myCustomTable > tr > td
```

cc @tbosch @vicb

**Comment by DzmitryShylovich** [comment] 2017-01-13 18:08
Duplicate of https://github.com/angular/angular/issues/7278

**Comment by pkozlowski-opensource** [comment] 2017-01-13 18:13
This would be _very_ handy for [ng-bootstrap button directives[(https://ng-bootstrap.github.io/#/components/buttons). Having said this I _really_ afraid that it would make templates harder to follow / reason about.

**Comment by dietergeerts** [comment] 2017-03-16 08:59
Also not-direct childs, as in: `[formGroup] .alert-success`, as I want to hide the alert, and show it when the form is submitted and successful..... I don't want other `alert-success` elements on my page to have this directive applied......

**Comment by alxhub** [comment] 2022-03-04 00:52
This would make selector matching a non-local operation, which is not a level of complexity that we want to introduce for templates and selector matching currently.

**Closed by alxhub** 2022-03-04 00:52 UTC
Labels: feature, hotlist: components team, comp: core, core: directive matching
