### ISSUE TITLE
Module constructor invoked twice

### ISSUE THREAD

**Issue by Liork1** [angular/angular#14986] opened 2017-03-07 16:12 UTC
Hi,

I'm trying to load a module in my application router in 2 ways:
1)   {  path: 'lazy',  loadChildren:'src/lazy/lazy.module#LazyModule' }
2) { path: 'lazy', loadChildren: ()=> LazyModule }

In both ways the constructor of LazyModule is being invoked twice.
Is there any way to avoid it?

Regards,
Lior

**Comment by DzmitryShylovich** [comment] 2017-03-07 16:24
Duplicate of https://github.com/angular/angular/issues/12869

**Closed** 2017-03-07 19:31 UTC
