### ISSUE TITLE
datePipe format behaves incorrectly in IE11/Edge

### ISSUE THREAD

**Issue by StevenSongToronto** [angular/angular#13551] opened 2016-12-18 02:56 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

DatePipe format 'M/d/y hh:mm a' works well in Chrome. But in IE11 / Edge, it produces
the result like '12/17/2016 09:12/17/2016 9:56:15 PM PM'
**Expected behavior**

It should produces the same result like '2/17/2016 09:55 PM' in IE11 / Edge.
**Minimal reproduction of the problem with instructions**

https://plnkr.co/edit/9tUUlqvjUxrK0IOTgOgC?p=preview
**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

2.3.0
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript
* **Node (for AoT issues):** `node --version` =

**Comment by Toxicable** [comment] 2016-12-18 03:22
It looks like there's an issue with how 'm' or 'mm' is being parsed
Tested in Edge, with the expected values come from it being run in chrome/checking against actual time
case: `date:'hh:mm'` result `04:12/18/2016 4:19:12 PM ` expected `04:19` 
case: `date:'mm'` result `12/18/2016 4:18:36 PM` expected `19`
case: `date:'m'` result `12/18/2016 4:20:06 PM` expected `20`
So as you can see it appears to replace `m` or `mm` with a new instance of `new Date()`

**Comment by DzmitryShylovich** [comment] 2016-12-18 07:09
It' a bug in ie.
Duplicate of https://github.com/angular/angular/issues/9524

**Comment by chuckjaz** [comment] 2016-12-19 19:23
Thanks for reporting this issue. However this issue is a duplicate of an existing issue #9524. Please subscribe to that issue for future updates.

**Closed by chuckjaz** 2016-12-19 19:23 UTC
