### ISSUE TITLE
XMB and XLIFF(both) output the wrong source file for a message

### ISSUE THREAD

**Issue by Goodwine** [angular/angular#24884] opened 2018-07-13 22:20 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

XMB and XLIFF(both) print the wrong source file for a message, [example in repo tests](https://github.com/angular/angular/blob/017d67cdf81e05496e4cf73f0f912ecef94e7bb3/packages/compiler-cli/test/extract_i18n_spec.ts#L47):
```html
  <msg id="3492007542396725315"><source>src/module.ts:2</source>Welcome</msg>
```
## Expected behavior

The generated code should have been:
```html
  <msg id="3492007542396725315"><source>src/basic.html:2</source>Welcome</msg>
```

## Minimal reproduction of the problem with instructions

bazel test //packages/compiler-cli/test:extract_i18n

## What is the motivation / use case for changing the behavior?

Tools that rely on the correctness of these XMB/XLIFF files need to hack their way around this limitation. For example, a tool that analyzes these generated files would need to replace ".ts" for ".html" to read the real file and hope that the names match (which is not always the case).

Internal bug id - 67908315

## Environment
commit: 97277bc

**Comment by vicb** [comment] 2018-07-13 23:20
@Goodwine Thanks for working on this issue.

AFAIK the problem is on the compiler side - ie the compiler do not report the correct SourceSpan for the message:
- It reports `<source>.ts` when the template is in a separate file (ie `template.html`),
- It doesn't take into account the offset from the start of the ts file for inline template. The SourceSpan is reported as if the file is composed of the template only starting on line 1 column 1.

Both problems should be fixed and they should be independent of each other. Feel free to work on what is most important for you first.

The team is available to support you should you need. Thanks.

**Comment by Goodwine** [comment] 2018-07-14 00:54
After looking around, I don't think there's a problem with SourceSpan (I initially thought that too, but was not able to go forward), it seems like the html compiler doesn't read HTML files and instead it reads a string from the template which may or may not exist. Thankfully there is a previous process that normalizes the component metadata like:
- if it has `template` -> set component TS file name as `templateUrl`
- if it has `templateUrl` -> load HTML file and set contents as `template`

Before normalization tho:
```js
// ==== component with templateUrl ===
{
  "encapsulation": null,
  "template": null,
  "templateUrl": "./basic.html",
  "htmlAst": null,
  "styles": [],
  "styleUrls": [],
  "externalStylesheets": [],
  "animations": [],
  "ngContentSelectors": [],
  "interpolation": null,
  "isInline": false,
  "preserveWhitespaces": null
}
// ==== component with inline template ===
{
  "ngMetadataName": "Component",
  "changeDetection": 1,
  "selector": "basic2",
  "inputs": [],
  "outputs": [],
  "host": {},
  "queries": {},
  "template": "<div title=\"translate me\" i18n-title=\"meaning|desc\"></div>\n      <p id=\"welcomeMessage\">\n    <!--i18n-->\n    Welcome<!--/i18n-->\n    </p>"
}
```

A way to deal with this could be storing the "template offset" in the template metadata, it would be 0 for loaded templates. Then consumers can choose to take this offset into account if they want.

**Closed** 2018-07-16 20:10 UTC
Labels: comp: i18n, freq3: high, severity3: broken, type: bug/fix
