### ISSUE TITLE
Adding/Removing controls to FormGroup or FormArray is not updating the dirty status.

### ISSUE THREAD

**Issue by WreckItRalph** [angular/angular#58409] opened 2024-10-29 13:49 UTC
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

No

### Description

When pushing a dirty FormControl or FormGroup to a FormArray or FormGroup, expectation is to mark the FormArray/Group as dirty. However, this is not happening right now. Similar expectation is to mark it as pristine if a dirty group is removed and no other group is dirty.

Affected function includes: 

`FormArray: push,removeAt, insert `
`FormGroup: removeControl, addControl`

A possible workaround is to either mark the formArray dirty manually or mark the dirty control as dirty again

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-g5m8cs?file=src%2Fmain.ts,node_modules%2F%40angular%2Fforms%2Findex.d.ts

**Comment by JeanMeche** [comment] 2024-10-29 15:15
Hi, this is a duplicate of #36788

**Closed by JeanMeche** 2024-10-29 15:15 UTC
