### ISSUE TITLE
Auxiliary route from a lazy loaded module

### ISSUE THREAD

**Issue by maxime1992** [angular/angular#13807] opened 2017-01-06 07:58 UTC
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I do have a lazy loaded module which loads by default `LazyLoadedComponent` when I go to `/lazy`. So far, it's OK.

This component contains 2 router-outlet :

```
<router-outlet></router-outlet>
<router-outlet name="aux"></router-outlet>
```

And the `LazyLoadedModule` has the following routes :

```
const routes = [
  {
      path: '',
      component: LazyLoadedComponent,
      children: [
          {
              path: '',
              component: NonAuxComponent
          },
          {
              path: '',
              component: AuxComponent,
              outlet: 'aux'
          }
      ]
  }
];
```

When I go to `/lazy` I do have the 3 components loaded as expected.
But, if I want to change the path to display the `AuxComponent` like that :    

```
{
   path: 'auxpath',
   component: AuxComponent,
   outlet: 'aux'
}
```

And I try to go to `/lazy(aux:auxpath)` it's not working.

I also tried to hit that URL using the `routerLink` like that :

    <a [routerLink]="[{ outlets: { aux: 'auxpath' } }]">Load an auxiliary route</a>

But it's not working either.

![image](https://cloud.githubusercontent.com/assets/4950209/21710815/5451e5e0-d3eb-11e6-8e01-5e4a4023b06a.png)

Is this a bug with the router ? Is it just me missing out something here?

You can check out this [Plunkr](http://plnkr.co/edit/TiwzIoR8t57yRrx8zpaQ?p=preview) to make your own tests.

**Minimal reproduction of the problem with instructions**
[Plunkr](http://plnkr.co/edit/TiwzIoR8t57yRrx8zpaQ?p=preview) :
- Click on "Demo (click to lazy load the module)"
- Once the module is loaded, click on "Load an auxiliary route"
- The non auxiliary component is well displayed, the auxiliary component is not displayed

**Please tell us about your environment:**

Ubuntu 16.10
VSC
Yarn
(But as this is also happening on Plunkr, not sure it's relevant).

* **Angular version:** 2.0.X

v2.4.1 (the one used on Plunkr)

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript

* **Node (for AoT issues):** `node --version` =   
v6.8.0

**Comment by DzmitryShylovich** [comment] 2017-01-06 08:00
Duplicate of https://github.com/angular/angular/issues/10981

**Comment by maxime1992** [comment] 2017-01-06 10:54
It seems that it isn't even a problem with **lazy loaded** modules containing aux routes.

Using `loadChildren : () => ModuleName` also result in error.

**Comment by vicb** [comment] 2017-01-06 17:40
Closing as duplicate.

**Closed by vicb** 2017-01-06 17:40 UTC

**Comment by topaxi** [comment] 2018-06-18 07:13
#10981 has been fixed but this case is still not working, I'd guess because of the empty path in the parent route.

**Comment by luckylooke** [comment] 2018-10-12 13:15
@topaxi I can confirm that it is empty path related, I have posted examples here https://github.com/angular/angular/issues/10981#issuecomment-429321315
