### ISSUE TITLE
i18n extraction not working for one way binding attributes

### ISSUE THREAD

**Issue by dyingangel666** [angular/angular#35902] opened 2020-03-06 10:07 UTC
# 🐞 bug report

### Description

i18n extraction not working for one way binding properties. In my case for the following markup:

```html
<input
            formControlName="email"
            i18n-placeholder="@@text_emailAddress"
            [placeholder]="'E-Mail Adresse'"
            type="email">
```

After calling the extraction tool `ng xi18n --format=xlf --output-path=src/locales --out-file=messages.xlf` the part is completely missing in the xlf files. I know i can just use `placeholder="E-Mail Adresse"` without square brackets but then i have the issue with IE11 and untouched form fields that are not pristine. And with one way binding this issue is fixed in IE11, but then the translations no longer working :(

A thing that partially works is when i use `i18n-[placeholder]` but then i also have the single quotes within the xlf file... 

Here's a repo with reproduction. Checkout and call the extraction tool `ng xi18n` and check the message.xlf file which is generated in the projects root location.

[https://github.com/dyingangel666/angular-i18n-extraction-issue](https://github.com/dyingangel666/angular-i18n-extraction-issue)

## 🌍  Your Environment

**Angular Version:**
<pre><code>
@angular-devkit/architect         0.900.4
@angular-devkit/build-angular     0.900.4
@angular-devkit/build-optimizer   0.900.4
@angular-devkit/build-webpack     0.900.4
@angular-devkit/core              9.0.4
@angular-devkit/schematics        9.0.4
@angular/cdk                      9.1.0
@ngtools/webpack                  9.0.4
@schematics/angular               9.0.4
@schematics/update                0.900.4
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
</code></pre>

**Comment by petebacondarwin** [comment] 2020-03-06 15:09
A couple of alternative approaches are described in this StackOverflow page: https://stackoverflow.com/questions/44433804/model-driven-forms-input-placeholder-issue-on-ie11

Looking into the translation issue...

**Comment by dyingangel666** [comment] 2020-03-06 15:20
Yeah thx, already seen all this workarounds... But just to fix this for IE11 users with some dirty workarounds? Nope, thx. Then IE11 users should live with dirty form inputs ;-)

**Comment by petebacondarwin** [comment] 2020-03-06 15:24
With the introduction of `$localize` in ivy (which is currently undocumented and not officially supported yet) it is possible to move translations to the `component.ts` file. See https://github.com/dyingangel666/angular-i18n-extraction-issue/pull/1

Currently we are not able to automatically extract translations from code like this. So you have to manually add the translations to the translation file.

**Comment by dyingangel666** [comment] 2020-03-06 15:42
Ok great. I already using $localize for translations in my ts files. But i can swear that this already worked before in another project with an older angular version :-/ Is it that hard to extract the code from a property that is just surrounded with square brackets? Doesn't sound very complicated to me

**Comment by petebacondarwin** [comment] 2020-03-06 16:00
We would also need to check that the value being passed to the input (attribute with square brackets 😈) is a literal string, so it is not completely trivial. But I am going to discuss with @AndrewKushnir as to whether we can add support for this case.

**Comment by dyingangel666** [comment] 2020-03-06 16:04
Nice to hear that, looking forward for it. Thx for your help!

**Comment by petebacondarwin** [comment] 2020-03-07 21:04
I discussed with with @AndrewKushnir and we feel that changing core to handle such cases is not the best way forward. In general inputs are dynamic by nature, it just happens that in this case you are using the fact that it doesn't apply an attribute to the DOM as a workaround for the IE11 issue.

Instead we should look to fix the IE11 issue in `@angular/forms` so that the pristine state of an input is not broken by having a placeholder there.

**Comment by petebacondarwin** [comment] 2020-03-07 21:11
This is effectively a duplicate of https://github.com/angular/angular/issues/15299

There appear to be a number of issues showing similar or related issues: #16151, #14440, #14667.

**Comment by AndrewKushnir** [comment] 2020-04-24 01:14
As Pete mentioned, this ticket is a duplicate of #15299, so I'll close this issue. Please subscribe to receive further updates in #15299. Thank you.

**Closed by AndrewKushnir** 2020-04-24 01:14 UTC
Labels: comp: i18n
