### ISSUE TITLE
Bug:I upgraded from 2.2.0 to 2.2.1 or specifically 2.2.0 to 2.4.7, i get ComponentConstructor is not a constructor

### ISSUE THREAD

**Issue by abhargav7** [angular/angular#14859] opened 2017-03-02 08:18 UTC
Minimal reproduction of the problem with instructions, I was using GoldenLayout with 2.2.0 angular 
and was making a call 
    let factory =  ComponentFactoryResolver.resolveComponentFactory(MyComponent); 
           let compRef = viewContainer.createComponent(factory); 
this was working perfectly fine on 2.2.0 angular version and it started crashing on 2.2.1 angular  

core.umd.js:2837 EXCEPTION: Uncaught (in promise): Error: Error in :0:0 caused by: ComponentConstructor is not a constructor
TypeError: ComponentConstructor is not a constructor.
---------------------------------------
My current package.json is below where this crash occurs
 "version": "0.0.1",
    "license": "MIT",
    "angular-cli": {},
    "scripts": {
        "ng-start": "ng serve",
        "lint": "tslint -t verbose -c tslint-all.json --project \"src/tsconfig.json\" --type-check ",
        "test": "ng test --watch=false",
        "test-watch": "ng test",
        "CI-test": "ng test --watch=false --log-level=debug --reporters=junit",
        "pree2e": "webdriver-manager update",
        "e2e": "protractor",
        "build": "ng build -sm=true --aot=true --output-path=dist/ && npm run compile",
        "compile": "tsc -p src/",
        "prepare": "copy electron\\. dist",
        "start": "npm run build  && npm run prepare && electron dist/",
        "debug": "npm run build && npm run prepare",
        "package": "npm run build && npm run prepare && ./node_modules/electron-packager/cli.js dist App --platform=darwin --arch=all --out=dist-app --overwrite"
    },
    "private": true,
    "dependencies": {
        "@angular/common": "~2.4.7",
        "@angular/compiler": "~2.4.7",
        "@angular/compiler-cli": "^2.4.7",
        "@angular/core": "~2.4.7",
        "@angular/forms": "~2.4.7",
        "@angular/http": "~2.4.7",
        "@angular/platform-browser": "~2.4.7",
        "@angular/platform-browser-dynamic": "~2.4.7",
        "@angular/router": "~3.4.4",
        "@ng-bootstrap/ng-bootstrap": "^1.0.0-alpha.20",
        "angular-split": "^0.1.19",
        "core-js": "^2.4.1",
        "ng2-dnd": "^2.2.2",
        "rxjs": "5.1.1",
        "ts-helpers": "^1.1.1",
        "zone.js": "^0.7.6"
    },
    "devDependencies": {
        "@angular/cli": "1.0.0-beta.32",
        "@types/jasmine": "^2.2.30",
        "@types/node": "^7.0.5",
        "codelyzer": "2.0.0",
        "electron": "^1.4.4",
        "electron-packager": "^8.1.0",
        "jasmine-core": "2.5.2",
        "jasmine-spec-reporter": "3.2.0",
        "karma": "1.4.1",
        "karma-chrome-launcher": "^2.0.0",
        "karma-cli": "^1.0.1",
        "karma-jasmine": "^1.0.2",
        "karma-junit-reporter": "^1.2.0",
        "karma-remap-istanbul": "^0.6.0",
        "karma-spec-reporter": "0.0.26",
        "protractor": "5.1.1",
        "tdp-devtools": "^1.0.3",
        "ts-node": "2.1.0",
        "typescript": "~2.1.6"
    }
}

**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment] 2017-03-02 08:34
please add a plunkr

**Comment by abhargav7** [comment] 2017-03-03 08:43
Thanks for quick help, here is project attached, I wasn't able to create a punker with latest ng version, here is the project open command prompt from GUI folder and install NPM run npm start and in toggle dev tools you will see the crash, seems some angular CLI issue learnt from Google. please help here
[TestPrj.zip](https://github.com/angular/angular/files/816208/TestPrj.zip)

If you see the thread many folks had this crash on upgrade, https://github.com/deepstreamIO/golden-layout/issues/75

**Comment by DzmitryShylovich** [comment] 2017-03-03 08:51
>  I wasn't able to create a punker with latest ng version

2.x - http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue
4.x - http://plnkr.co/edit/lU32vBJY9KYXZUTW7GQQ?p=preview

**Comment by abhargav7** [comment] 2017-03-03 09:21
Never Mind, I am new to plnker, I spent some time there and not able to setup things.Can you please download the zip and give a try it would be easy reproduce the bug.Thanks again

**Comment by abhargav7** [comment] 2017-03-03 09:26
[TestPrj.zip](https://github.com/angular/angular/files/816341/TestPrj.zip)

**Comment by abhargav7** [comment] 2017-03-03 12:23
O.k. i spent my day figuring this out and found the actual root cause... that upgrading from es5 to es6 broke this which is defined in compiler options.

**Comment by DzmitryShylovich** [comment] 2017-03-06 10:18
@abhargav7 close the issue please if it was resolved. thanks

**Comment by abhargav7** [comment] 2017-03-06 10:35
ok sure, but do you have any clue why deleting new keyword fixed the issue in ES6, while with ES5 it works like a charm

**Comment by DzmitryShylovich** [comment] 2017-03-06 10:47
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Not_a_constructor

**Comment by DzmitryShylovich** [comment] 2017-03-10 07:27
@pkozlowski-opensource can be closed

**Comment by pkozlowski-opensource** [comment] 2017-03-13 16:27
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Closed by pkozlowski-opensource** 2017-03-13 16:27 UTC

**Comment by jinder** [comment] 2017-04-13 10:11
I had a very similar error that's caused by the fact that you can pass a lamda expression in ES5 target mode, which can be invoked as a constructor without error (because it's converted into a function).  When you target ES6 mode, this remains a lamda and you'll receive the error above because you can't new() a lamda.
