### ISSUE TITLE
formatDate does not take firstDayOfWeek into account

### ISSUE THREAD

**Issue by jpzwarte** [angular/angular#31130] opened 2019-06-19 12:44 UTC
Example: https://stackblitz.com/edit/angular-uk5zml

```
  constructor(@Inject(LOCALE_ID) locale: string) {
    const today = new Date(),
      lastDayOfMonth = new Date(today.getFullYear(), today.getMonth() + 1, 0);

    console.log(formatDate(lastDayOfMonth, 'W', locale));
  }
```

For the month of june, this correctly outputs "6" *for the US locale*.
![Screenshot 2019-06-19 at 14 40 15](https://user-images.githubusercontent.com/3968/59766388-61846500-92a0-11e9-9305-9d4d01867b23.png)

However, for the *nl* locale where the first day of the week is monday instead of sunday, it still outputs "6" instead of "5".
<img width="193" alt="Screenshot 2019-06-19 at 14 44 12" src="https://user-images.githubusercontent.com/3968/59766540-bde78480-92a0-11e9-88c6-b83917098baf.png">

The `weekGetter` function (https://github.com/angular/angular/blob/master/packages/common/src/i18n/format_date.ts#L362) does not seem to take the first day of the week into account.

**Comment by trotyl** [comment] 2019-06-19 13:39
Duplicate of https://github.com/angular/angular/issues/25380

**Comment by petebacondarwin** [comment] 2020-05-26 12:14
Indeed this is a duplicate of #25380 - thanks @trotyl

**Closed by petebacondarwin** 2020-05-26 12:14 UTC
Labels: comp: common, comp: i18n

**Comment by petebacondarwin** [comment] 2020-11-09 14:53
Tracking here #39606.
