### ISSUE TITLE
Navigations with async guards + nested RouterLink + urlUpdateStrategy: eager are broken

### ISSUE THREAD

**Issue by laurentgoudet** [angular/angular#40401] opened 2021-01-12 14:43 UTC
# 🐞 bug report

### Affected Package

I believe the issue is caused by package @angular/router.

### Is this a regression?

Not sure if that ever worked.

### Description

When `routerLink` is used as an input of a custom component, e.g.:

```
@Component({
  selector: 'app-link-wrapper',
  template: `
    <a [routerLink]="routerLink"><ng-content></ng-content></a>
  `,
})
export class LinkWrapperComponent {
  @Input() routerLink: string;
}
```

And that the route navigating to has an async guard:

```
@Injectable({
  providedIn: 'root',
})
export class TestGuard implements CanActivate {
  canActivate(
    route: ActivatedRouteSnapshot,
    state: RouterStateSnapshot,
  ) {
    return Rx.of(undefined).pipe(
      delay(100),
      map(() => true),
    );
  }
}
```

And that the Router `urlUpdateStrategy` is set to `eager`

Then the navigation is broken, as if the guard was unsubscribed to before emitting its value.

If any of the above conditions is not true, then the navigation works as expected, i.e.:
- If the `routerLink` input of `LinkWrapperComponent` is renamed to `myRouterLink`
- If the route guard returns synchronously
- If `urlUpdateStrategy` is not set to `eager`

## 🔬 Minimal Reproduction

Minimal repro in https://github.com/laurentgoudet/angular-nester-routerLink-eager-urlUpdateStrategy-bug. All the code is in https://github.com/laurentgoudet/angular-nester-routerLink-eager-urlUpdateStrategy-bug/blob/master/src/app/app-routing.module.ts.

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 11.0.6
Node: 12.4.0
OS: darwin x64

Angular: 11.0.8
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.6
@angular-devkit/build-angular   0.1100.6
@angular-devkit/core            11.0.6
@angular-devkit/schematics      11.0.6
@angular/cli                    11.0.6
@schematics/angular             11.0.6
@schematics/update              0.1100.6
rxjs                            6.6.3
typescript                      4.0.2
</code></pre>

**Comment by atscott** [comment] 2021-01-13 23:03
Duplicate of #28561. The issue is that you've ended up creating two `routerLink`s that both cause navigation and end up cancelling each other. If you rename the `@input` of your wrapper to be something other than `routerLink` so that the directive does not apply to the outer wrapper, this will work.

**Closed by atscott** 2021-01-13 23:03 UTC
Labels: comp: router

**Comment by laurentgoudet** [comment] 2021-01-14 11:29
Yep we are going to address it on our side by renaming the input name as it's arguably a bug in the first place, but the fact that it's only an issue with async `CanActivate` guards + `urlUpdateStrategy: 'eager'` does make it hard to debug: making `routerLink` safer to use, either by throwing an error when used in a nested context or by making it more resilient (e.g. skipping the parent navigation) would improve the developer experience here, if the root cause is not addressed by https://github.com/angular/angular/issues/28561.
