### ISSUE TITLE
Alpha 29: Bundle not available through https://code.angularjs.org/

### ISSUE THREAD

**Issue by jomeier** [angular/angular#2865] opened 2015-07-03 19:17 UTC
The title says everything :-) Thanks for uploading the bundle.

**Comment by ericmdantas** [comment] 2015-07-03 19:20
I too use the bundle from the cdn, it's by far the easiest and fastest way to get stuff done.

**Comment by jpsfs** [comment] 2015-07-04 11:58
Hi!

If you don't mind borrowing this thread, any news on typing for alpha 29?
Not only, but mostly because of the appInject change, updated typings will smooth the alpha 28 > 29 transition.

https://github.com/borisyankov/DefinitelyTyped/tree/master/angular2

**Comment by ericmdantas** [comment] 2015-07-08 02:11
Still not available :cry:

**Comment by Sabartius** [comment] 2015-07-08 06:35
Alpha 30 is also not available :(

**Comment by ericmdantas** [comment] 2015-07-09 02:01
[.30 bundle is available](https://code.angularjs.org/2.0.0-alpha.30/)

**Comment by naomiblack** [comment] 2015-07-14 03:44
Yes, sorry -- we have been changing our release process and we dropped alpha-29. Closing this issue as the problem is fixed for milestones 30 onward

**Closed by naomiblack** 2015-07-14 03:44 UTC
