### ISSUE TITLE
Support typescript's not-null caster in templates

### ISSUE THREAD

**Issue by Goodwine** [angular/angular#13280] opened 2016-12-06 22:45 UTC
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Templates complain when the object "can be null" and they don't accept using typescript's `!` not null caster. The way to do this is by using `?` instead which is inconsistent.

**Expected behavior**
Angular templates should accept `!` like if it was `?`

**Minimal reproduction of the problem with instructions**
```html
<h2>{{ video.getSnippet().getTitle() }}</h2>
```
resulted in error  "Object is possibly 'null'."

```html
<!-- Using typescript's "not null" cast -->
<h2>{{ video.getSnippet()!.getTitle() }}</h2>
```
resulted in Error: Template parse errors:
Parser Error: Unexpected token '!' at column 23 in [{{ video.getSnippet()!.getTitle() }}]

**What is the motivation / use case for changing the behavior?**
Consistency

**Please tell us about your environment:**
* Ubuntu, Atom
* **Language:** TypeScript?

**Comment by DzmitryShylovich** [comment] 2016-12-06 22:48
We already have `?` save navigation operator. Don't see any reason why do we need `!` with exactly the same meaning.

> The way to do this is by using ? instead which is inconsistent.

but it's consistent with other langs :)

**Comment by ericmartinezr** [comment] 2016-12-06 22:50
https://github.com/angular/angular/issues/10855#issuecomment-240449481

**Comment by Goodwine** [comment] 2016-12-06 23:33
Perhaps the error message `Unexpected token '!'` could add `did you mean to use '?'` (or something akin)

**Comment by chuckjaz** [comment] 2016-12-07 18:12
Thanks for reporting this issue. However this issue is a duplicate of an existing #10855. Please subscribe to that issue for future updates.

**Closed by chuckjaz** 2016-12-07 18:12 UTC
