### ISSUE TITLE
(ngModelChange) with 'time' input is triggered too early

### ISSUE THREAD

**Issue by bbaczekNomtek** [angular/angular#43202] opened 2021-08-19 09:28 UTC
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

No

### Description

The function `(ngModelChange)` seems to be called too early when used with the `time` input type. If I wrap the body of `(ngModelChange)` function in `setTimeout` is works fine.

Value of input as received in (ngModelChange) seems to always be one step behind.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-12-template-9c8trq?file=src/app/app.component.ts

### Please provide the environment you discovered this bug in

```true
@angular/animations 12.0.5
@angular/common 12.0.5
@angular/compiler 12.0.5
@angular/core 12.0.5
@angular/forms 12.0.5
@angular/platform-browser 12.0.5
@angular/platform-browser-dynamic 12.0.5
@angular/router 12.0.5
angular-in-memory-web-api 0.11.0
rxjs 6.6.7
tslib 2.3.0
zone.js 0.11.4```
```

**Comment by JoostK** [comment] 2021-08-19 10:59
Duplicate of #11234. The listener for `ngModelChange` is invoked before the two-way bound `ngModel` listener (where the two-way binding is really syntactic sugar for `[ngModel]="x" (ngModelChange)="x = $event"`), which means that the `ngModelChange` listener reads the yet-to-be-updated value as the two-way binding listener is next to be executed.

**Closed by JoostK** 2021-08-19 10:59 UTC
