### ISSUE TITLE
Hash (#) in path to project dir leads to "Could not resolve module `path_to_project`"

### ISSUE THREAD

**Issue by aborovsky** [angular/angular#22979] opened 2018-03-25 11:36 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Create new `ng new my-app` project and run `npm start`.
It ends with `Could not resolve module ...`, where `...` is a part of absolute path to current directory, where angular project placed.

## Expected behavior

Success build and serve of project.

## Minimal reproduction of the problem with instructions
* Create a path with hash (#), for example: `/Users/username/Documents/#work`. Tested on macOs and linux (Ubuntu). Suppose same thing happens on Windows.
* `cd /Users/username/Documents/#work`
* `ng new my-app`
* `cd my-app`
* `npm start`
* Get error output `ERROR in Could not resolve module /Users/username/Documents/`

## Investigation / source of problem
I'm sure it comes from here: https://github.com/angular/angular/blob/c8a1a14b87e5907458e8e87021e47f9796cb3257/packages/compiler/src/aot/lazy_routes.ts#L54

* `route` equal to `/Users/username/Documents/#work/my-app/src/app/app.module#AppModule`
* so, the splitted `routePath` becomes `/Users/username/Documents/`, instead of `/Users/username/Documents/#work/my-app/src/app/app.module`
* and `routeName ` becomes `work/my-app/src/app/app.module#AppModule` instead of `AppModule `

Need to fix the code to split the route with only last hash (#) included in the path.

## Environment

<pre><code>
Angular CLI version: 1.7.3
Angular version: 5.2.0

Browser:
- [X] Chrome (desktop) version 65.0.3325.181
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v8.9.0
- Platform: mcOs High Sierra 10.13.3

Others:

</code></pre>

**Comment by JoostK** [comment] 2020-03-15 01:44
Closing as duplicate of #19960. This is still an issue today, also in Ivy (although it's a different code path, it has the same issue)

**Closed by JoostK** 2020-03-15 01:44 UTC
Labels: comp: compiler, freq1: low, severity2: inconvenient, type: bug/fix
