### ISSUE TITLE
FireFox Dropdown Bug?

### ISSUE THREAD

**Issue by WebDragonStudios** [angular/angular#12893] opened 2016-11-15 15:45 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I'm experience an issue in FireFox (latest updated version), where it breaks on creating a dropdown. I'm not sure if possibly it's a code issue or not, but I have googled this heavily and I see many people have problems with Angular 2 not playing nicely with FireFox.

**Expected behavior**

If the bug was not there, I would have a fully populated drop down.

**Minimal reproduction of the problem with instructions**

The following code is where the application breaks:

                SearchComponent.prototype.getDepartments = function () {
                    var _this = this;
                    this._departmentService.getDepartments(true)
                        .subscribe(function (departments) { return _this.departments = departments; }, function (error) { return console.error('Error: ' + error); }, function () { return console.log('Completed!'); });
                    //this.request.department = -1;
                };

I'm assuming maybe its the .subscribe function but I'm not sure. 

**What is the motivation / use case for changing the behavior?**

The motivation is to get the drop down to populate with a list of departments. 

**Please tell us about your environment:**

Visual Studio 2015

* **Angular version:** 2.0.X

  "name": "angular-quickstart",
  "version": "1.0.0",

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 The only browser the error occurs on is FireFox (and I have the latest updated version, 50.0)

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
C#, TypeScript, Angular2

* **Node (for AoT issues):** `node --version` =   
3.10.8

**Comment by DzmitryShylovich** [comment] 2016-11-15 15:47
Pls add a repro in plunkr.

**Comment by pkozlowski-opensource** [comment] 2016-11-22 18:16
Closing due to the missing reproduce scenario.

**Closed by pkozlowski-opensource** 2016-11-22 18:16 UTC
Labels: comp: core & compiler, state: Need repro
