### ISSUE TITLE
Can not pass <audio> template

### ISSUE THREAD

**Issue by yizhan** [angular/angular#5694] opened 2015-12-08 08:17 UTC
`<audio>` element was working fine in Angular 2 alpha 46 template, but start to broken in alpha 47, and version 48 still not working, too. It seems the new template parser do not like the non closed `<source>`. By adding `</source>` will remove error message, but it would be invalid. 

I have made a example for it. Please let me know If I did anything wrong. 
http://plnkr.co/edit/Y5sr0W?p=preview
You need open console to see the error.

```
"ORIGINAL EXCEPTION: Template parse errors:
Unexpected closing tag "audio" ("io>
      <source src="http://www.pacdv.com/sounds/applause-sounds/app-5.mp3" type="audio/ogg">
    [ERROR ->]</audio>
  "): App@4:4"
```

Audio is very important to us, we normally do load src dynamically with `[src]='audioAddress'`, but with version 47 and 48 I have to add the source by creating a new Element.

**Comment by robwormald** [comment] 2015-12-08 09:24
dupe of https://github.com/angular/angular/issues/5663 and fixed in https://github.com/angular/angular/pull/5668

**Closed by robwormald** 2015-12-08 09:24 UTC
