### ISSUE TITLE
Get direct access to ng-content input

### ISSUE THREAD

**Issue by clovergaze** [angular/angular#40293] opened 2021-01-02 09:04 UTC
# 🚀 Feature request
Make content that comes in via `ng-content` more easily accessible.

### Description
I would like to be able to give content to a component like this:

```html
<app-content>{{ content }}</app-content>
```

And then get direct access to the content inside my component, e.g. via an injection or a special template variable.

I have a more detailed description of how this should work here: [Render string input of ng-content directly as HTML](https://stackoverflow.com/questions/64733677/render-string-input-of-ng-content-directly-as-html) (StackOverflow)

This also includes a StackBlitz of how I would like to avoid to do it (see [get-input-of-ng-content-directly](https://stackblitz.com/edit/get-input-of-ng-content-directly)).

### Describe the solution you'd like
I would like to use it in the template directly, something like this:

```html
<div [outerHTML]="incoming ng-content stuff"></div>
```

Or inject it like this:

```typescript
constructor(ngContentStuff: NgContent)
```

### Describe alternatives you've considered
In the StackBlitz example I am getting the content via `ng-content` in the template and than access it via `elementRef.nativeElement.textContent`.

**Comment by petebacondarwin** [comment] 2021-01-02 11:57
Hi @clovergaze - I would like to understand your use-case better to help with this request. Can you explain why you want to render the `content` string via interpolation only to then capture it again via the DOM in order to then render it back out to HTML again:

```html
<app-content>{{ content }}</app-content>
```

Why not do, as suggested in the StackOverflow answer, and pass the string as an input?

```
<app-content [content]="content"><app-content>
```

**Comment by clovergaze** [comment] 2021-01-02 13:21
Hello @petebacondarwin,

> Can you explain why you want to render the content string via interpolation only to then capture it again via the DOM in order to then render it back out to HTML again.

That is not exactly what I am doing, but basically accessing any value that comes in via content projection should be accessible *easily*. Without a detour of rendering it hidden in the view and accessing it afterwards, as demonstrated in the StackBlitz example. This is basically what I want to avoid.

> Why not do, as suggested in the StackOverflow answer, and pass the string as an input?

Because I think that being able to directly access what comes in via content projection should be given. Hence, my feature request for it.

**Comment by petebacondarwin** [comment] 2021-01-02 13:34
I am still not quite sure what your use-case is, but it sounds a bit like a structural directive (e.g. `ngIf` or `ngFor`). In these cases the directive is able to get hold of the contents via the [`TemplateRef`](https://angular.io/api/core/TemplateRef).

**Comment by ManaliKatkar** [comment] 2021-01-02 13:56
Just go through below link
https://joshblf.medium.com/wtf-is-ng-content-8382b2a664e1

**Comment by clovergaze** [comment] 2021-01-02 14:00
@ManaliKatkar How does that solve the problem of not being able to access what comes in via content projection?

**Comment by ManaliKatkar** [comment] 2021-01-02 14:07
I m able to access whatever content comes via ng-content. Just go through below images

https://user-images.githubusercontent.com/47694362/103458798-8846a700-4d31-11eb-93cc-cb5c9a5c204e.png
https://user-images.githubusercontent.com/47694362/103458829-c774f800-4d31-11eb-93d3-91786cb4d6f0.png

**Comment by clovergaze** [comment] 2021-01-02 14:17
@ManaliKatkar I am aware that this is how content projection is supposed to work. Yet, this is unrelated to my feature request.

**Comment by ManaliKatkar** [comment] 2021-01-02 14:38
@clovergaze i hope u will get ans from below link 
https://stackblitz.com/edit/ng-content-select-attribute?file=src%2Fapp%2Fapp.component.html

**Comment by Airblader** [comment] 2021-01-02 19:24
If the component has the knowledge that the content is a HTML string, then passing it as an input as the solution, and I don't really see why that shouldn't be the way to go. The purpose of content projection is exactly that the "caller" gets to decide this, and the component only determines the location.

From the referenced SO question the issue appears to be that string interpolation doesn't interpret HTML, and the solution to that is using innerHTML — on the "caller" side.

I personally still don't really see why the requested feature would be next, ie what actual benefit it would bring to the table.

**Comment by clovergaze** [comment] 2021-01-02 22:45
@Airblader

> If the component has the knowledge that the content is a HTML string (which it does because it passes it to innerHTML), then passing it as an input as the solution, and I don't really see why that shouldn't be the way to go.

I am aware that this would be a possible solution for the specific use-case here. Yet, this disregards the fact, that a direct access the the projected value is not easily possible. Whether it is a string or another object.

> From the referenced SO question the issue appears to be that string interpolation doesn't interpret HTML, and the solution to that is using innerHTML — on the "caller" side.

Yes, this is related to the use-case where the stated problem that the incoming content can not be accessed directly popped up. But putting the HTML string in the callers `innerHTML` attribute is definitely not a suitable solution in this case. Please note that these are boiled down examples.

> I personally still don't really see why the requested feature would be next, ie what actual benefit it would bring to the table.

The benefit is actually rather obvious: get direct access to the incoming content.

This could maybe be achieved by giving the developer a specialized object for injection.

**Comment by Airblader** [comment] 2021-01-02 23:08
> The benefit is actually rather obvious: get direct access to the incoming content.

That's not a benefit, that's just what you (think you) want. Features should be discussed for their intended use cases so that the best solution can be found, whether they already exists or would need to be built. For the use case you presented so far, no such feature is required as far as I can tell.

Also, you can get some level of access already through content queries. But you're talking specifically about a raw HTML string for the sole purpose of rendering it out. Doing that either on the caller or passing it as an input are two solutions for that. If your actual use case is different and these aren't applicable, you could perhaps either provide that use case or explain why, or both.

**Comment by clovergaze** [comment] 2021-01-02 23:51
@Airblader

> That's not a benefit, that's just what you (think you) want.

Why should it not be a benefit to have multiple possibilities? Please elaborate. And yes, that is actually exactly what I want.

> Features should be discussed for their intended use cases so that the best solution can be found, whether they already exists or would need to be built. For the use case you presented so far, no such feature is required as far as I can tell.

Angular in several cases provides more than one way for achieving basically the same. I do not see any reason why it should not be the case here as well.

Getting the content for projection from between the tag could save an extra attribute in the element tag and a corresponding input field in the component. So, if the requested feature is implemented in a way that allows easy access to the content, than this would be a cleaner way of getting it.

> Also, you can get some level of access already through content queries.

That is true, it would actually be great, if one could just query for an `NgContent` object or something and get the projected content. Maybe that could also be a solution for this. I think, I did try that as well as putting a template variable on the `ng-content` tag and I guess both did not work.

Surrounding the `ng-content` with an element that could be queried, for example via a template variable and accessing the underling elements from that starting point would in no way be better than the solution I provided in the StackBlitz example.

> But you're talking specifically about a raw HTML string for the sole purpose of rendering it out. Doing that either on the caller or passing it as an input are two solutions for that. If your actual use case is different and these aren't applicable, you could perhaps either provide that use case or explain why, or both.

As I said before, yes, sending the sting into the component via attribute and input field is a possible solution. As far as the provided examples are concerned, putting the HTML string on the parent's `innerHTML` attribute would work here, too. It would not work for the real component, because it is doing some more processing on the incoming data.

You might disagree and that is okay, but I see a benefit in being able to get the data via that route as well. Hence, this request for that feature.. 🙂

**Comment by Airblader** [comment] 2021-01-02 23:58
> Why should it not be a benefit to have multiple possibilities? 

A feature should either allow something that wasn't possible before, or allow something in a significantly better way.

Adding more APIs to solve problems that are already solved purely because of "why not" is something I doubt will be accepted. It drives up the bundle size of the framework and creates more learning curve for developers.

**Comment by jelbourn** [comment] 2021-01-08 22:20
I think I would consider this a duplicate of #8563, which is our overarching issue for giving more granular control of content projection. Does that sounds reasonable?

**Comment by clovergaze** [comment] 2021-01-08 23:27
@jelbourn Yes, #8563 is basically asking for the same thing, a way to programmatically get the incoming content for content projection. In addition to the ways to get the content as proposed in #8563, it would be great to also get the content via an injection in the `constructor`, like with `ElementRef` for example.

**Comment by jelbourn** [comment] 2021-01-11 17:54
Duplicate of #8563

**Closed by jelbourn** 2021-01-11 17:54 UTC
Labels: comp: core
