### ISSUE TITLE
angular2 rc5 http go wrong when body is null

### ISSUE THREAD

**Issue by vthinkxie** [angular/angular#10628] opened 2016-08-10 07:48 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
when body is null, body.text will go wrong

https://github.com/angular/angular/blob/master/modules/%40angular/http/src/body.ts#L43

**Expected/desired behavior**

add method to deal with null body

* **Angular version:** 2.0.0-rc.5

**Comment by pkozlowski-opensource** [comment] 2016-08-10 07:59
Duplicate of #10612

**Closed by pkozlowski-opensource** 2016-08-10 07:59 UTC
