### ISSUE TITLE
Angular v17 missing environment documentation for .env files with Vite

### ISSUE THREAD

**Issue by devbyray** [angular/angular#52747] opened 2023-11-09 18:01 UTC
### Describe the problem that you experienced

I can't find any documentation about how to use environment variables from a .env file inside the Angular v17 new build system (Vite). Would anyone be able to point me in the right direction? Because I can only find things about Webpack, but that feels weird since we use Vite now.

**Comment by JoostK** [comment] 2023-11-09 18:31
I don't fully understand what you're referring to w.r.t. this feature for Webpack? What documentation is that?

**Comment by devbyray** [comment] 2023-11-09 19:01
> I don't fully understand what you're referring to w.r.t. this feature for Webpack? What documentation is that?

Well for example in React or Vue I'm used to set all the environment variables in an `.env` files like secret keys or API url's. 

I want to use that in Angular. But I can only find documentation about how to create an `environment.ts` where I need to hardcode my environment variables. But this is not secure since those files will be in source control. 

This [blog describes a way you can do this with Webpack](https://medium.com/@desinaoluseun/using-env-to-store-environment-variables-in-angular-20c15c7c0e6a), but I don't want to use Webpack since v17 includes Vite.

So I was looking for documentation where I can store my environment variable safely in a `.env` file, so I can safely store them in my pipeline as well, and during build time those values are available. So in my application I can use `process.env`.

My question is, how can I achieve this? Because I think there might be a lot more developers out there that need this.

**Comment by dgp1130** [comment] 2023-11-09 19:14
Angular CLI doesn't support `.env` files right now. File replacements / environments are intended for build time configuration. Secret information typically shouldn't go in the client at all and is something which should be handled by the server.

https://github.com/angular/angular-cli/issues/4318 is probably the closest existing feature request to what you're asking for. I'll close this as a duplicate of that, since there's nothing to document right now.

Duplicate of angular/angular-cli#4318

**Closed by dgp1130** 2023-11-09 19:14 UTC
Labels: area: adev

**Comment by devbyray** [comment] 2023-11-09 22:47
> Angular CLI doesn't support `.env` files right now. File replacements / environments are intended for build time configuration. Secret information typically shouldn't go in the client at all and is something which should be handled by the server.
> 
> 
> 
> https://github.com/angular/angular-cli/issues/4318 is probably the closest existing feature request to what you're asking for. I'll close this as a duplicate of that, since there's nothing to document right now.
> 
> 
> 
> Duplicate of angular/angular-cli#4318

Thanks for the suggestion! That was indeed exactly what I was searching for 👍
