### ISSUE TITLE
bug(testing) ngOnChanges not called for component initialized via TestComponentBuilder #9866

### ISSUE THREAD

**Issue by argelj289** [angular/angular#39633] opened 2020-11-11 01:58 UTC
This issue has been automatically locked due to inactivity.
Please file a new issue if you are encountering a similar or related problem.

Read more about our [automatic conversation locking policy](https://github.com/angular/angular/blob/67d80f/docs/GITHUB_PROCESS.md#conversation-locking).

<sub>_This action has been performed automatically by a bot._</sub>

_Originally posted by @angular-automatic-lock-bot[bot] in https://github.com/angular/angular/issues/9866#issuecomment-531545509_

Not resolved and still recurring on angular 10

**Comment by AndrewKushnir** [comment] 2020-11-11 05:55
Hi @argelj289, could you please provide an example of the code that you use and describe expected behavior? Since this issue lacks the necessary info, I will close it for now. Please create a new one following an issue template and provide additional information so that we can understand the problem better. Thank you.

**Closed by AndrewKushnir** 2020-11-11 05:55 UTC
