### ISSUE TITLE
AbstractControl documentation is not complete

### ISSUE THREAD

**Issue by affinehat** [angular/angular#15567] opened 2017-03-28 22:19 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
In the transition to Angular 4, AbstractControl documentation seems to be missing some functions.

**Expected behavior**
The documentation should match with https://v2.angular.io/docs/ts/latest/api/forms/index/AbstractControl-class.html

**Minimal reproduction of the problem with instructions**
Compare https://angular.io/docs/ts/latest/api/forms/index/AbstractControl-class.html with https://github.com/angular/angular/blob/4.0.0/packages/forms/src/model.ts

* **Angular version:** 4.0

Moved from https://github.com/angular/angular.io/issues/3454

**Comment by DzmitryShylovich** [comment] 2017-03-28 22:29
Duplicates https://github.com/angular/angular/issues/15551

**Comment by IgorMinar** [comment] 2017-03-29 07:29
Thanks for reporting this issue. However this issue is a duplicate of an existing issue #15551. Please subscribe to that issue for future updates.

**Closed by IgorMinar** 2017-03-29 07:29 UTC
