### ISSUE TITLE
Refreshing a route while offline fails (angular service worker)

### ISSUE THREAD

**Issue by maa105** [angular/angular#22110] opened 2018-02-09 08:47 UTC
Moved it from https://github.com/angular/angular-cli/issues/9558

Versions: 

Windows Server 2008
Angular Version 5.2.4
Angular CLI: 1.6.4
Node: 8.9.1
OS: win32 x64
Angular:
...

Reproduce: 
1- Create new angular with service worker and routing (ng new app --service-worker --routing) 
2- add a route /home with a link to go to the /home
3- build and deploy
4- open site
5- go to /home page by clicking on the link
6- go offline
7- refresh browser

Observed behavior
when u refresh it fails (cause the URL is /home and /home was not cached but /index.html was)

Desired behavior
since the /home is just the same as /index.html but at a different route it should not fail, the problem won't show if you are offline cause this is handled by the server as in the following script ` app.get('*', function (req, res) { res.redirect('/index.html'); }); `. so the server knows about it and just return index.html. but the service worker doesn't (it just cached /index.html not /home). I guess my request/question is to be able in the service worker to create a default file for all routes or routes that do not have caching rules.

the workaround, for now, use hash routing instead of path routing (https://angular.io/guide/router#browser-url-styles)

**Comment by jackkoppa** [comment] 2018-02-10 15:16
We've been discussing a similar issue at #21636, which I think is the same root cause - response of 504 Gateway Timeout when trying to access a non-index route, while offline. My [SO question](https://stackoverflow.com/questions/48565629/how-to-handle-routing-in-angular-5-service-workers) is currently open, on this issue, but thus far no one has been able to give any explanation for how this case should be handled. I've still been trying to step through the generated `ngsw.js` file, to see where the failure occurs for non-index routes offline (such that it does not fail for the index route); I don't yet have an answer on that.

**Comment by jackkoppa** [comment] 2018-02-10 21:38
This issue can probably be closed as a duplicate of 21636. In the meantime, see [this repo](https://github.com/jackkoppa/service-worker-test/tree/routing-failure-minimal-repro) with a minimal reproduction to run locally.

**Comment by gkalpak** [comment] 2018-03-02 14:46
Closing as duplicate of #21636.

**Closed by gkalpak** 2018-03-02 14:46 UTC
Labels: comp: service-worker
