### ISSUE TITLE
<a href="#"></a> doesn't work as expected after upgrading to angular 2.2.0

### ISSUE THREAD

**Issue by kamiua** [angular/angular#12945] opened 2016-11-17 18:36 UTC
**I'm submitting a ...**
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
After upgrading from angular 2.0.0 to angular 2.2.0 we now have following issue:
clicking on ```<a href="#">Link</a>``` navigates user away from current page to ```http://app_url/#```.

**Expected behavior**
Previously clicking on the link did nothing as expected. Same behavior is expected in 2.2.0.

**What is the motivation / use case for changing the behavior?**
Upgrading to new version of angular shouldn't introduce breaking changes to application.
There is workaround: adding ```onClick="return false;"``` prevents incorrect navigation. But having third party components makes us unable to fix the issue in every place.

**Please tell us about your environment:**
Windows 10, Visual Studio 2015, npm 3.10.8, node 6.7.0.

* **Angular version:** 2.2.0

* **Browser:** [ Chrome 54.0.2840.99 m ]
 
* **Language:** [ TypeScript 2.0.3 ]

**Comment by DzmitryShylovich** [comment] 2016-12-11 12:20
Duplicate of https://github.com/angular/angular/issues/7294

**Comment by vicb** [comment] 2016-12-14 00:47
@DenysYefimenko please add a repro for both before and after

**Comment by vicb** [comment] 2017-01-06 01:55
@DenysYefimenko do you have a quick repro to add here ?

**Comment by xban1x** [comment] 2017-10-27 09:26
Should this be closed?

**Comment by jasonaden** [comment] 2017-12-08 22:21
Closing as duplicate without repro.

**Closed by jasonaden** 2017-12-08 22:21 UTC
Labels: comp: router, severity5: regression, workaround1: obvious
