### ISSUE TITLE
HTML5 datalist element's id property is not limited to the containing component's scope

### ISSUE THREAD

**Issue by tomcatmwi** [angular/angular#16142] opened 2017-04-19 04:22 UTC
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I tried to use a **datalist** element linked to an **input** field in a component as an auto-complete feature. It turned out that if I use more than one instance of the component on a page, the two components conflict with each other and only the first instance's **datalist** will work, unless the **datalist** is static and defined in the template. If it's populated programmatically, it will fail. The reason is that the **id** field of the **datalist** is identical in the two instances of the component and it causes a conflict.

**Expected behavior**
Without the bug each component would keep their DOM elements in their own scope.

**Minimal reproduction of the problem with instructions**
Try adding this to a component:

```
<input type="text" list="myList">
<datalist id="myList">
<option *ngFor="let thing of thingList">{{ thing }}</option>
</datalist>

```
In the **constructor** or **ngOnInit** of the component populate the **thingList** array with random strings. Then just add two instances of the component to a parent component. In Chrome you'll see that the first one will get the contents of the **thingList** array of both instances, and the second will get none. In Firefox both instances will get the same array.

**What is the motivation / use case for changing the behavior?**
I ran into this bug while implementing an autocomplete form element using Google Maps Places Autocomplete API. I needed two form elements, one for the place of birth and one for the current residence. They conflicted.

**Please tell us about your environment:**
Windows 7 64 bit, NetBeans 8.2, npm, Node.js

* **Angular version:** 2.4.10

* **Browser:** [all ]

 
* **Language:** [all | TypeScript 2.3.0 | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =   7.5.0

**Comment by zoechi** [comment] 2017-04-19 06:17
In `ViewEncapsulation.Emulated` (default) you have to take care yourself that the elements get unique ids. Angular doesn't encapsulate ids.
With `ViewEncapsulation.Native` the browser takes care of it.
If you still think this is an issue, you should at least provide a Plunker that allows to reproduce the problem (as stated in the issue template).

**Comment by tomcatmwi** [comment] 2017-04-19 06:29
Yes, it works with ViewEncapsulation.Native, but in this case my input
fields lose their CSS formatting.

**Comment by zoechi** [comment] 2017-04-19 07:05
That's a known problem with `ViewEncapsulation.Native`, but IMHO that's mostly a browser issue because there are no good solutions to style native shadow DOM components.
CSS variables help to some degree but  are way too limited to really solve the problem.
The easiest way is to just generate unique ids yourself and bind it to the element.

**Comment by tomcatmwi** [comment] 2017-04-19 07:07
Yes, that's what I did. Thanks for the tips.

**Comment by pkozlowski-opensource** [comment] 2017-04-19 11:34
Please add a minimal reproduce scenario using plunker, otherwise it is hard to understand if there is anything actionable on the angular side or not.

And as @zoechi pointed out, Angular won't do anything to "encapsulate" ids for a given component.

**Comment by vicb** [comment] 2018-05-31 22:38
Closing as no repro has been provided.

**Closed by vicb** 2018-05-31 22:38 UTC
Labels: comp: core & compiler, freq1: low, severity3: broken, state: Need repro, type: bug/fix
