### ISSUE TITLE
(Router) Query params not being picked up by some child routes

### ISSUE THREAD

**Issue by jsholzer** [angular/angular#9705] opened 2016-06-29 21:15 UTC
**I'm submitting a ...**
```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
While working through the Angular 2 Developer Guide's [Routing & Navigation section](https://angular.io/docs/ts/latest/guide/router.html#!#query-parameters), I noticed that when navigating back from the `CrisisDetailComponent` (i.e. /crisis-center/1) to the `CrisisListComponent` (/crisis-center), that the query parameters are not made available through the `ActivatedRoute`.

I have not done any additional testing to confirm if this issue is directly related to the use of a child route with an empty path (`path: ''`). However, that does appear to be the case in this particular scenario. I also noticed the exact same behavior with the the Plunker demo that was created for the routing section of the guide: https://angular.io/resources/live-examples/router/ts/plnkr.html

My routing setup is identical to what's in the demo...

```
export const CrisisCenterRoutes : RouterConfig = [
    {
        path: '',
        redirectTo: '/crisis-center',
        terminal: true
    },
    {
        path: 'crisis-center',
        component: CrisisCenterComponent,
        children: [
            {
                path: 'admin',
                component: CrisisAdminComponent,
                canActivate: [AuthGuard]
            },
            {
                path: ':id',
                component: CrisisDetailComponent,
                canDeactivate: [CanDeactivateGuard]
            },
            {
                path: '',
                component: CrisisListComponent
            }
        ]
    }
]
```

I navigated directly to `http://localhost:3000/crisis-center;id=1` and was able to verify that the params object, available via `this.route.params.subscript(params => ...)`, had no properties defined, though I expected an "id" property to exist. I tried the same thing for the route to the detail component (using a URL like `http://localhost:3000/crisis-center/1;foo=bar`), and the parameter "foo" was defined in the params object, as  expected.

I'm using the following code in the ngOnInit method of the `CrisisListComponent` to access the query params:
```
        this.sub = this.route.params.subscribe(params => {
            this.selectedId = +params['id'];
            this.service.getCrises()
                .then(crises => this.crises = crises);
        });
```

**Expected/desired behavior**
When using query params with child routes, regardless of the path of the route, the query parameters should be accessible through the `ActivatedRoute`. If this is not always possible, then the guide and examples provided are incorrect.

**Reproduction of the problem**

1. Go to the plunker demo for the Routing & Navigation section of the developer guide: https://angular.io/resources/live-examples/router/ts/plnkr.html
1. Select any of the "crises" to navigate to the details
1. Click the save or cancel button to return the crisis list, but this time with added query parameters (i.e. `;id=1;foo=foo`)
1. Notice that the "selected" CSS class is not applied to the crisis with the ID matching the "id" query parameter, due to the fact that the `id` parameter was returned as null to the component (even though it's provided in the URL and should have been returned as "1")

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.3 (@angular/router version 3.0.0-alpha.8)
 
* **Browser:** [all] 
 
* **Language:** [TypeScript 1.8.10]

**Comment by choeller** [comment] 2016-06-30 05:33
This seems to be the same problem that I had in #9451. The problem is that the params are send to `CrisisCenterComponent` but not to `CrisisListComponent`. According to @vsavkin those params are supposed to be merged into the `path: ''` Route-

**Comment by jsholzer** [comment] 2016-06-30 16:04
Thanks @choeller! The workaround from [#9451](https://github.com/angular/angular/issues/9451) worked for me. I'm sure the problem will be resolved in an upcoming release.

On a side note... it would also be nice to see a consistent API for defining and accessing query string parameters, regardless of whether a component is reached via a child route, and has the Matrix style query string, or not.

**Comment by vsavkin** [comment] 2016-06-30 20:19
As @choeller pointed out only the params of componentless routes get merged into the children. So I'm closing this issue.

**Closed by vsavkin** 2016-06-30 20:19 UTC
