### ISSUE TITLE
Styles for a css chunk applied with delay. No way to disable css splitting

### ISSUE THREAD

**Issue by SashaKumeiko** [angular/angular#59003] opened 2024-12-02 10:29 UTC
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

In version 19 CSS is split into lazy-loaded chunks.
CSS for a loaded chunk is applied with a tiny delay to a newly appeared component.Also I didn't find a possibility to disable CSS chunking although it could be a nice feature if fixed

Steps to reproduce: 

1. Create new project
2. Install angular material package
3. add a button that shows up on click some component for example "mat-expansion-panel"
4. Actual result - styles are applied with delay

### Please provide the exception or error you saw

```true

```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular 19.0.0
```

**Comment by JoostK** [comment] 2024-12-02 10:31
Duplicate of #58629, HMR can be disabled to make stylesheets synchronously available again.

**Closed by JoostK** 2024-12-02 10:31 UTC
