### ISSUE TITLE
CSP in chrome app with angular 2

### ISSUE THREAD

**Issue by Kleak** [angular/angular#5956] opened 2015-12-16 17:31 UTC
i have rewrite the example given on angular.io and after building the project and launch it as a chrome app i have some trouble with csp...

here is my pubspec.yaml
```yaml
name: angula2_example
version: 0.0.1

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  angular2: 2.0.0-beta.0
  browser: ^0.10.0
  chrome: 0.8.0
  dart_to_js_script_rewriter: ^0.1.0

transformers:
- angular2:
    entry_points: web/main.dart
- dart_to_js_script_rewriter
- chrome
- $dart2js:
    csp: true
```

my manifest.json :
```json
{
  "name": "Angular2 example",
  "version": "1",

  "manifest_version": 2,
  "minimum_chrome_version": "31",

  "icons": {"128": "dart_icon.png"},

  "app": {
    "background": {
      "scripts": ["background.dart.js"]
    }
  }
}
```

my index.html :
```html
<!DOCTYPE html>
<html>
  <head>
    <title>Angular2 example in chrome app</title>
    <script src="main.dart" type="application/dart"></script>
    <script src="packages/browser/dart.js"></script>
  </head>
  <body>
    <my-app>Loading...</my-app>
  </body>
</html>
```

my main.dart :
```dart
import 'package:angular2/angular2.dart';
import 'package:angular2/bootstrap.dart';

@Component(selector: 'my-app')
@View(template: '<h1>Angular 2</h1>')
class AppComponent {}

main() {
  bootstrap(AppComponent);
}
```

and my background.dart :
```dart
import "package:chrome/chrome_app.dart" as chrome;

main() {
  chrome.app.runtime.onLaunched.listen((data) {
    chrome.CreateWindowOptions createWindowOptions =
        new chrome.CreateWindowOptions();
    createWindowOptions.id = "_angular2-example";
    createWindowOptions.bounds =
        new chrome.ContentBounds(width: 800, height: 600);
    chrome.app.window.create("index.html", createWindowOptions);
  });
}
```

the error :
Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "default-src 'self' blob: filesystem: chrome-extension-resource:".

Thanks

**Comment by alextappin** [comment] 2016-02-05 01:12
I figured out how to fix this bug and figured I would post here (just in case others might want to know what happened!)

Go [here] (https://developer.chrome.com/extensions/contentSecurityPolicy) and scroll down until you read about the "unsafe eval". Basically, you need to add one line to your manifest.json in order to run "unsafe" code such as "eval".

`"content_security_policy": "script-src 'self' 'unsafe-eval'; object-src 'self'",`

**Comment by alexpaluzzi** [comment] 2016-02-05 05:12
@alextappin Does that work with Chrome Apps? I thought you could only relax that with Extensions?

**Comment by alextappin** [comment] 2016-02-05 07:54
Ah, not sure. I think you're right:/ I was having this issue for a chrome extension.

**Comment by Kleak** [comment] 2016-02-06 08:22
@alextappin @alexpaluzzi yep its not possible in a chrome app :/

**Comment by alextappin** [comment] 2016-02-06 09:42
@kleak yup. Now, Angular needs to stop using this 'unsafe' eval so we can contribute to the chrome web store! ;)

**Comment by tbosch** [comment] 2016-02-08 20:59
Right now we use `eval` to get an easier JS interop. But we should revisit this.

**Comment by alextappin** [comment] 2016-02-09 10:15
Perfect. Glad to see some work is being done on this!

**Comment by Kleak** [comment] 2016-02-10 16:22
@tbosch have you an idea of when you will revisit this ?

**Comment by tejainece** [comment] 2016-03-16 18:43
Any updates on this?

**Comment by Kleak** [comment] 2016-03-17 18:19
why this issue is not part of the release candidate milestone since it's tag "P2: required" ?

**Comment by tejainece** [comment] 2016-03-18 15:57
Sorry for the digression. I have been trying to find a work around until this problem is fixed in AngularDart2.

# Step 1
You can use 
`
"sandbox": {
    "pages": [
      "index.html"
    ]
  }
`

to avoid eval, etc CSP errors.

#Step 2
You won't be able to serve files from app's domain. To avoid CSP for serving non-HTML files, you can use:

`
"permissions": [
    "<all_urls>",
    "*://*/*",
  ]
`

#Step 3
I couldn't manage to serve component template HTML files. But you can provide HTML templates to Angular through "@View" and "@Component" decorators.

**Comment by mjaggard** [comment] 2016-04-14 14:08
Am I right in thinking that this isn't Dart specific? I'm getting the same in TypeScript.

**Comment by Kleak** [comment] 2016-04-14 14:26
yep as tbosch as said they use eval so all version of angular 2 are not compatible with chrome app csp requirement.

**Comment by tejainece** [comment] 2016-04-14 14:38
It is actually very easy to fix. I fixed it by doing this:

`eval` is used in only 3 places. All 3 of them are in the following file: `src/platform/browser/browser_adapter.dart`

`
    _setProperty = js.context.callMethod(
        'eval', ['(function(el, prop, value) { el[prop] = value; })']);
    _getProperty = js.context
        .callMethod('eval', ['(function(el, prop) { return el[prop]; })']);
    _hasProperty = js.context
        .callMethod('eval', ['(function(el, prop) { return prop in el; })']);
`

This can changed into:

`
    _setProperty = js.context["angularSetElemProp"];
    _getProperty = js.context["angularGetElemProp"];
    _hasProperty = js.context["angularHasElemProp"];
`

and add the following Js file in the html:

`
function angularSetElemProp(el, prop, value) {el[prop] = value;}
function angularGetElemProp(el, prop) { return el[prop]; }
function angularHasElemProp(el, prop) { return prop in el; }
`

**Comment by alexpaluzzi** [comment] 2016-04-14 14:54
@tbosch can we get this issue promoted to the RC milestone? I don't think Angular is "finished" until it's CSP-compliant.

**Comment by maks** [comment] 2016-05-02 00:03
Sadly this seems like a regression, since the first version of Angular clearly had good support for CSP as noted in the page on using [Angular for Chrome Apps](https://developer.chrome.com/apps/angular_framework) where it has:

> AngularJS's autodetection for CSP

**Comment by seanw** [comment] 2016-07-19 16:15
Is there a similar workaround that @tejainece mentioned or something else for the TypeScript version? After following https://angular.io/docs/ts/latest/quickstart.html and putting this in a Chrome packaged app I get this:

zone.js:101 XHR finished loading: GET "chrome-extension://djkmfolbhphnbopjiogjkdanjodiefej/app/main.js".scheduleTask @ zone.js:101ZoneDelegate.scheduleTask @ zone.js:336Zone.scheduleMacroTask @ zone.js:273(anonymous function) @ zone.js:122(anonymous function) @ zone.js:987fetchTextFromURL @ system.src.js:1156(anonymous function) @ system.src.js:1739ZoneAwarePromise @ zone.js:584(anonymous function) @ system.src.js:1738(anonymous function) @ system.src.js:2764(anonymous function) @ system.src.js:3338(anonymous function) @ system.src.js:3605(anonymous function) @ system.src.js:3990(anonymous function) @ system.src.js:4453(anonymous function) @ system.src.js:4705(anonymous function) @ system.src.js:408ZoneDelegate.invoke @ zone.js:323Zone.run @ zone.js:216(anonymous function) @ zone.js:571ZoneDelegate.invokeTask @ zone.js:356Zone.runTask @ zone.js:256drainMicroTaskQueue @ zone.js:474
2016-07-19 17:08:37.249 zone.js:101 XHR finished loading: GET "chrome-extension://djkmfolbhphnbopjiogjkdanjodiefej/node_modules/@angular/platform-browser-dynamic//bundles/platform-browser-dynamic.umd.js".scheduleTask @ zone.js:101ZoneDelegate.scheduleTask @ zone.js:336Zone.scheduleMacroTask @ zone.js:273(anonymous function) @ zone.js:122(anonymous function) @ zone.js:987fetchTextFromURL @ system.src.js:1156(anonymous function) @ system.src.js:1739ZoneAwarePromise @ zone.js:584(anonymous function) @ system.src.js:1738(anonymous function) @ system.src.js:2764(anonymous function) @ system.src.js:3338(anonymous function) @ system.src.js:3605(anonymous function) @ system.src.js:3990(anonymous function) @ system.src.js:4453(anonymous function) @ system.src.js:4705(anonymous function) @ system.src.js:408ZoneDelegate.invoke @ zone.js:323Zone.run @ zone.js:216(anonymous function) @ zone.js:571ZoneDelegate.invokeTask @ zone.js:356Zone.runTask @ zone.js:256drainMicroTaskQueue @ zone.js:474ZoneTask.invoke @ zone.js:426
2016-07-19 17:08:37.251 systemjs.config.js:2 Error: EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "default-src 'self' blob: filesystem: chrome-extension-resource:".(…)(anonymous function) @ systemjs.config.js:2ZoneDelegate.invoke @ zone.js:323Zone.run @ zone.js:216(anonymous function) @ zone.js:571ZoneDelegate.invokeTask @ zone.js:356Zone.runTask @ zone.js:256drainMicroTaskQueue @ zone.js:474ZoneTask.invoke @ zone.js:426
2016-07-19 17:08:37.256 zone.js:101 XHR finished loading: GET "chrome-extension://djkmfolbhphnbopjiogjkdanjodiefej/app/app.component.js".scheduleTask @ zone.js:101ZoneDelegate.scheduleTask @ zone.js:336Zone.scheduleMacroTask @ zone.js:273(anonymous function) @ zone.js:122(anonymous function) @ zone.js:987fetchTextFromURL @ system.src.js:1156(anonymous function) @ system.src.js:1739ZoneAwarePromise @ zone.js:584(anonymous function) @ system.src.js:1738(anonymous function) @ system.src.js:2764(anonymous function) @ system.src.js:3338(anonymous function) @ system.src.js:3605(anonymous function) @ system.src.js:3990(anonymous function) @ system.src.js:4453(anonymous function) @ system.src.js:4705(anonymous function) @ system.src.js:408ZoneDelegate.invoke @ zone.js:323Zone.run @ zone.js:216(anonymous function) @ zone.js:571ZoneDelegate.invokeTask @ zone.js:356Zone.runTask @ zone.js:256drainMicroTaskQueue @ zone.js:474ZoneTask.invoke @ zone.js:426
2016-07-19 17:08:37.261 zone.js:101 XHR finished loading: GET "chrome-extension://djkmfolbhphnbopjiogjkdanjodiefej/node_modules/@angular/core//bundles/core.umd.js".scheduleTask @ zone.js:101ZoneDelegate.scheduleTask @ zone.js:336Zone.scheduleMacroTask @ zone.js:273(anonymous function) @ zone.js:122(anonymous function) @ zone.js:987fetchTextFromURL @ system.src.js:1156(anonymous function) @ system.src.js:1739ZoneAwarePromise @ zone.js:584(anonymous function) @ system.src.js:1738(anonymous function) @ system.src.js:2764(anonymous function) @ system.src.js:3338(anonymous function) @ system.src.js:3605(anonymous function) @ system.src.js:3990(anonymous function) @ system.src.js:4453(anonymous function) @ system.src.js:4705(anonymous function) @ system.src.js:408ZoneDelegate.invoke @ zone.js:323Zone.run @ zone.js:216(anonymous function) @ zone.js:571ZoneDelegate.invokeTask @ zone.js:356Zone.runTask @ zone.js:256drainMicroTaskQueue @ zone.js:474ZoneTask.invoke @ zone.js:426

I'm not seeing any obvious way to change node_modules/@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js to fix this.

**Comment by Edheltur** [comment] 2016-07-19 16:28
I used angular-compiler-cli to precompile all components and get rid of CSP errors. Now RC4 works in my chrome app.

**Comment by zoechi** [comment] 2016-07-19 16:37
Then we only need to wait for this to become available in Dart ...

**Comment by vicb** [comment] 2016-07-19 16:44
> Now RC4 works in my chrome app.

**Comment by seanw** [comment] 2016-07-19 16:45
@Edheltur Do you mean if you run "ng build" from angular-compiler-cli you can load without errors from the generated source files? Are you able to update the files that relate to your component files only without doing a full build again while developing?

**Closed by vicb** 2016-07-19 16:44 UTC
Labels: comp: core, effort2: medium (day), P2: required, type: bug

**Comment by seanw** [comment] 2016-07-19 16:50
@vicb Are there any settings I should be looking at to avoid this error in a Chrome app? Unless I made a mistake, I'm using RC4 following the settings in https://angular.io/docs/ts/latest/quickstart.html and I'm still getting this error today.

**Comment by zoechi** [comment] 2016-07-19 16:51
@vicb this was obviously reported for Dart (see pubspec.yaml in the initial post)

**Comment by Edheltur** [comment] 2016-07-19 16:52
@seanw, Yep, after ng build and systemjs bundling I got working chrome app. I failed to figure out how to make incremental compilation. My hello world project builds several minutes =(. I could provide a snapshot of it, but it hosted on Gitlab.

**Comment by redders6600** [comment] 2016-07-27 18:24
Is there a way to fix this issue without using angular-cli? What does angular-cli do that fixes the eval issues?

I'm still having the problem with rc4 in my chrome app.

**Comment by Edheltur** [comment] 2016-07-27 18:55
The purpose of any (offline or not) compiler - transform your templates into pure js files. Online compiler is the source of eval problems. Hope this helps.

**Comment by farhan687** [comment] 2016-08-09 12:23
Any solution for this issue,? I tried angular-cli also, and it is also not working for me.

**Comment by nhenneaux** [comment] 2016-08-09 12:31
I cannot make it work too. I have a pending question on [stackoverflow ](https://stackoverflow.com/questions/38734708/make-angular2-works-with-restrictive-content-security-policy-csp).

**Comment by tbosch** [comment] 2016-08-18 08:22
You need to use the offline compiler "ngc".

**Comment by syonip** [comment] 2016-08-30 13:40
Did anyone manage to get an angular 2 app work as a chrome packaged app?

**Comment by perozdrero** [comment] 2016-09-03 17:05
I have tried to set up as chrome app new minko's https://github.com/mgechev/angular2-seed that has off-line template compilation,  and production build runs.

![image](https://cloud.githubusercontent.com/assets/3456474/18226411/60777734-7209-11e6-816b-3874a2561d62.png)
