### ISSUE TITLE
Infinite loop using beta7

### ISSUE THREAD

**Issue by albertoforesin** [angular/angular#7207] opened 2016-02-20 20:49 UTC
Hi guys,
I get an infinite loop using beta7, this is the Safari's stacktrace:

```
Error: Script terminated by timeout at:
DebugDomRenderer</DebugDomRenderer.prototype.createText@http://localhost:2067/node_modules/angular2/bundles/angular2.dev.js:7184:11
viewFactory_t0@viewFactory_t:256:18
viewFactory_t0@viewFactory_t:266:1
viewFactory_t0@viewFactory_t:266:1
viewFactory_t0@viewFactory_t:266:1
viewFactory_t0@viewFactory_t:266:1
viewFactory_t0@viewFactory_t:266:1
...
```

My packages:
```
   "angular2": "2.0.0-beta.7",
    "systemjs": "0.19.20",
    "es6-promise": "^3.0.2",
    "es6-shim": "^0.33.3",
    "reflect-metadata": "0.1.2",
    "rxjs": "5.0.0-beta.2",
    "zone.js": "0.5.15",
```

My tsd:
```
{
  "version": "v4",
  "repo": "borisyankov/DefinitelyTyped",
  "ref": "master",
  "path": "typings",
  "bundle": "typings/tsd.d.ts",
  "installed": {
    "jquery/jquery.d.ts": {
      "commit": "9027703c0bd831319dcdf7f3169f7a468537f448"
    },
    "bootstrap/bootstrap.d.ts": {
      "commit": "9027703c0bd831319dcdf7f3169f7a468537f448"
    }
  },
  "ambientDependencies": {
    "es6-shim": "github:DefinitelyTyped/DefinitelyTyped/es6-shim/es6-shim.d.ts#6697d6f7dadbf5773cb40ecda35a76027e0783b2"
  }
}
```

My boot:
```
///<reference path="../../node_modules/angular2/typings/browser.d.ts"/>

import {bootstrap}    from 'angular2/platform/browser'
import {AppComponent} from './app.component'
import {ROUTER_PROVIDERS} from 'angular2/router';
import {HTTP_PROVIDERS} from 'angular2/http'
import 'rxjs/add/operator/map';
import 'rxjs/add/operator/retry';

bootstrap(AppComponent, [ROUTER_PROVIDERS, HTTP_PROVIDERS]);
```

My rooting class:
```
import {Component} from 'angular2/core';
import {RouteConfig, Router, Location, Instruction, ROUTER_DIRECTIVES} from 'angular2/router';
import {MainComponent} from './components/sections/main.component';
import {NotFoundComponent} from './components/sections/not-found.component';
import {EventEmitterService} from './services/event-emitter.service';
import {NavigationService, Routes} from './services/navigation.service'; 

@Component({
    selector: 'my-app',
    template: '<router-outlet></router-outlet>',
    directives: [ROUTER_DIRECTIVES],
    providers: [EventEmitterService, NavigationService]
})
@RouteConfig([
    {path:'/' , name: Routes.Main , component: MainComponent, useAsDefault: true},
    {path:'/not-found' , name: Routes.NotFound , component: NotFoundComponent}
])
export class AppComponent
{   
    public constructor(private _router: Router, _location:Location) 
    {
        _router.recognize(_location.path()).then((instruction: Instruction) => {
            if (!instruction)
                _router.recognize('/not-found').then((instruction: Instruction) => _router.navigateByInstruction(instruction, true));
        });
    }
}

```

Using beta6 everything works well.

**Comment by alexeagle** [comment] 2016-02-29 17:07
@btford it looks like the only code in this app which could cause a loop is the router `recognize`->`navigateByInstruction` here. Did that change in beta.7? Seems like this case should be detected and an error reported.

**Comment by natewallace** [comment] 2016-03-22 11:55
I was just about to log a bug for this as I'm seeing it in beta 11 as well.  I think the issue is with the _createViewFactoryRuntime function in the src/compiler/template_compiler.js file.  It appears that it dynamically generates code from your components at runtime that are responsible for creating views.  This function uses the function name from your components when creating parameter, function and sub function names and the problem is that it doesn't account for the fact that different components may end up with the same function name.

In this specific case I think the component code has been minified and all the function names ended up being 't'.  This results in parameters, functions and sub functions all being named 'viewFactory_t0' which results in an infinite recursive loop occurring when trying to generate a view.

**Comment by natewallace** [comment] 2016-03-22 14:48
To add some more context to this issue I've copied some of the dynamically generated view factory code below.  For brevity's sake I've excluded a lot of the generated code and only included the relevant sections.  Sections where code has been removed have been replaced with ellipses.

The following is the code from an **unminified** source:
```
(function(exports,styles,resolvedMetadataCache,QuestionAddView,viewFactory_QuestionAddView0,QuestionListView,viewFactory_QuestionListView0,AbstractChangeDetector,ChangeDetectionUtil,ChangeDetectorState,AppProtoView,AppProtoElement,ViewType,AppView,AppElement,flattenNestedViewRenderNodes,checkSlotCount
/**/) {

  ...

  function viewFactory_QuestionControllerView0(parentRenderer,viewManager,containerEl,projectableNodes,rootSelector,dynamicallyCreatedProviders,rootInjector){
    ...
    viewFactory_QuestionAddView0(renderer, viewManager, app3_QuestionControllerView, [], null, null, null);
    ...
    viewFactory_QuestionListView0(renderer, viewManager, app9_QuestionControllerView, [], null, null, null);
    ...
  }
  return viewFactory_QuestionControllerView0
})
```

The following is from the same code as above but  **minified**:
```
(function(exports,styles,resolvedMetadataCache,t,viewFactory_t0,AbstractChangeDetector,ChangeDetectionUtil,ChangeDetectorState,AppProtoView,AppProtoElement,ViewType,AppView,AppElement,flattenNestedViewRenderNodes,checkSlotCount
/**/) {

  ...

  function viewFactory_t0(parentRenderer,viewManager,containerEl,projectableNodes,rootSelector,dynamicallyCreatedProviders,rootInjector){
    ...
    viewFactory_t0(renderer, viewManager, app3_t, [], null, null, null);
    ...
    viewFactory_t0(renderer, viewManager, app9_t, [], null, null, null);
    ...
  }
  return viewFactory_t0
})
```

You'll notice in the minified version that the occurrences of 
- viewFactory_QuestionControllerView0
- viewFactory_QuestionAddView0
- viewFactory_QuestionListView0

have all been replaced with viewFactory_t0.  This causes an infinite recursive loop as there is now a call to viewFactory_t0 within function viewFactory_t0.

**Comment by alexeagle** [comment] 2016-03-22 19:32
cc @tbosch

**Comment by wardbell** [comment] 2016-03-23 01:45
Can we have a repro of this? It seems quite serious and may deserve attention on the list of critical router issues.

**Comment by natewallace** [comment] 2016-03-23 12:09
I don't think it's a router issue.  I think it's a template compiler issue.  Here is a simple example that reproduces the error:  http://plnkr.co/XvCpQEvt9A2pd5JrzFCi

Note that if you go into the src/view.ts file and change the name of the class from App to anything else it will work correctly.  The error only occurs if you have a component that contains a component in it's template that shares the same class name with it.

**Comment by natewallace** [comment] 2016-03-28 17:27
Looks like this bug may be a duplicate or at least related to https://github.com/angular/angular/issues/6380.

**Comment by mark-buer** [comment] 2016-04-01 05:35
Many commenters also report issues with minification on #6678, so it's probably related.

**Comment by DrewynV** [comment] 2016-04-05 00:31
__________________________________

Hi! We just wanted to let you know we receievd your email. Thank you for submitting your request. Our aim is to get back to you within 24 hours at the latest. If you have any additional information to add to your request, please reply to this email.


Also please visit our knowledgebase (http://www.support.magicdust.com.au) to browse for further info, we are adding to it all the time.

Or here is our industry report about the 11 Essentials for a Successful Website (http://www.magicdust.com.au/web-design/.

We look forward to helping you succeed online.

Thanks

The Team @ Magicdust Digital

http://support.magicdust.com.au/

Ph (02) 9979 7474
M-F | 9 am-5:00 pm AEST (AEDT in Summer) excluding Public Holidays

------------------------------------------------------------------------------------------------------------
This message was sent to  reply@reply.github.com in reference to Case #166558.
------------------------------------------------------------------------------------------------------------


[[a2ef5be94b65a1fea9aeb02c5d6dda0b29cdfa96-673074307]]

**Comment by pkozlowski-opensource** [comment] 2016-06-03 17:53
Closing as a duplicate of #6678,

**Closed by pkozlowski-opensource** 2016-06-03 17:53 UTC
