### ISSUE TITLE
forms: updateValueAndValidity() should update the descendants

### ISSUE THREAD

**Issue by Gerros** [angular/angular#22166] opened 2018-02-12 14:55 UTC
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Currently the updateValueAndValidity() method of the AbstractControl class updates the abstract control itself and its ascendents, but not its descendants.

## Expected behavior
By triggering the updateValueAndValidity() method on an abstract control, I have the possibility to say that the descendants of the abstract control should be updated as well. E.g., a form group containing several form controls... executing updateValueAndValidity() on the form group should update the value and validity of the form controls which are in this form group.

## What is the motivation / use case for changing the behavior?
It is very cumbersome and a lot of additional code has to be written, to update every single form control.

## Environment

<pre><code>
Angular: 5.2.4

**Comment by trotyl** [comment] 2018-02-12 16:04
Duplicate of #6170

**Comment by mhevery** [comment] 2018-02-13 00:21
closing as dup

**Closed by mhevery** 2018-02-13 00:21 UTC
Labels: comp: forms
