### ISSUE TITLE
Return key event was not fired on bluetooth connected keyboard on iOS device

### ISSUE THREAD

**Issue by arnoldgithub** [angular/angular#11690] opened 2016-09-17 16:37 UTC
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 
Return key event was not fired when the following criteria were met (all): 1. bluetooth input device 2. iOS, 3. Angular 2

**Expected behavior**
Return key event was fired

**Reproduction of the problem**
Connect your iPhone or iPad with a bluetooth keyboard
On your iOS device, iPhone or iPad, open your favourite browser.
Visit the TODO MVC for angular 2, http://todomvc.com/examples/angular2/
or the contact list app on Made with Angular 2: https://embed.plnkr.co/ns1tfi/
Type something on bluetooth connected physical keyboard and hit Enter key.
Nothing happened.

**What is the motivation / use case for changing the behavior?**
My app was built using Angular 2, and targeted to all device, including iOS environment.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.6

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 

All
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
 all

* **Node (for AoT issues):** `node --version` =

**Comment by vicb** [comment] 2016-09-19 22:26
duplicate of https://github.com/angular/angular/issues/8273

**Closed by vicb** 2016-09-19 22:26 UTC
