### ISSUE TITLE
Error in ng serve "Could not resolve module"

### ISSUE THREAD

**Issue by hamidyfine** [angular/angular#21803] opened 2018-01-26 14:38 UTC
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
I create a new angular project by angular cli using this command:

`$ ng new ng5-app`

I wait until all the file created and all the dependencies installed, and after all of those tasks, when I try to run the app using:

`$ ng serve`

this errors shows up:

				** NG Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ ** Date: 2018-01-26T14:12:03.297Z
				Hash: 2238da56910f9b52c46b
				Time: 2158ms
				chunk {inline} inline.bundle.js (inline) 5.79 kB [entry] [rendered]
				chunk {main} main.bundle.js (main) 2.93 kB [initial] [rendered]
				chunk {polyfills} polyfills.bundle.js (polyfills) 636 bytes [initial] [rendered]
				chunk {styles} styles.bundle.js (styles) 33.6 kB [initial] [rendered]
				chunk {vendor} vendor.bundle.js (vendor) 852 kB [initial] [rendered]

				ERROR in Error: Could not resolve module H:/
					at StaticSymbolResolver.getSymbolByModule (H:\#htdocs\ng5-app\node_modules\@angular\compiler\bundles\compiler.umd.js:29765:30)
					at StaticReflector.resolveExternalReference (H:\#htdocs\ng5-app\node_modules\@angular\compiler\bundles\compiler.umd.js:31610:62)
					at parseLazyRoute (H:\#htdocs\ng5-app\node_modules\@angular\compiler\bundles\compiler.umd.js:29049:55)
					at AotCompiler.listLazyRoutes (H:\#htdocs\ng5-app\node_modules\@angular\compiler\bundles\compiler.umd.js:31142:43)
					at AngularCompilerProgram.listLazyRoutes (H:\#htdocs\ng5-app\node_modules\@angular\compiler-cli\src\transformers\program.js:156:30)
					at Function.NgTools_InternalApi_NG_2.listLazyRoutes (H:\#htdocs\ng5-app\node_modules\@angular\compiler-cli\src\ngtools_api.js:44:36)
					at AngularCompilerPlugin._getLazyRoutesFromNgtools (H:\#htdocs\ng5-app\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:248:66)
					at Promise.resolve.then.then (H:\#htdocs\ng5-app\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:565:50)
					at process._tickCallback (internal/process/next_tick.js:103:7)

				webpack: Failed to compile.

What is the problem of this error?

## Expected behavior
I just want to run sample app that is created by ```ng new```.

**Comment by alexzuza** [comment] 2018-01-26 14:43
Can you setup minimal repro? Also strange name `H:/` for module

**Comment by hamidyfine** [comment] 2018-01-26 14:45
what do you mean by minimal repo?

**Comment by alexzuza** [comment] 2018-01-26 14:51
Please read [here](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue)  to understand why we ask about minimal reproduction. 
A good way to make a minimal repro is to create a new app via ng new repro-name and add the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by alexzuza** [comment] 2018-01-26 14:54
Have you tried using something else than `H:\#htdocs` path for your project?

**Comment by hamidyfine** [comment] 2018-01-26 14:58
I create minimal repo of the project here:
https://github.com/hamidyfine/sample-ng-app

**Comment by hamidyfine** [comment] 2018-01-26 14:59
> Have you tried using something else than H:\#htdocs path for your project?

I will try it now.

**Comment by hamidyfine** [comment] 2018-01-26 16:22
> Have you tried using something else than H:\#htdocs path for your project?

It works!!!! I can't believe that the problem is ```#htdocs```!!!

**Comment by jasonaden** [comment] 2018-01-26 17:58
Looks like this was addressed, so closing. Open a new issue if needed.

**Closed by jasonaden** 2018-01-26 17:58 UTC

**Comment by mgochmuradov** [comment] 2019-01-25 15:03
This seems to be because of **#** char in project location.
My project located in **C:\dev\\#SandBox\AngularPlayground**
And I Get:
`
ERROR in Could not resolve module /C/dev/
`

**Comment by girishuppal** [comment] 2019-01-29 03:14
Yes @mgochmuradov . Spot on !
