### ISSUE TITLE
angular Not suitable for the front end, only suitable for background management ?

### ISSUE THREAD

**Issue by iloveyo123u1** [angular/angular#9349] opened 2016-06-19 13:33 UTC
Angular to do the background management program is very good

But it is not suitable for the front end, because it is too big

i used angular-cli   

Generated file is too large

1-2MB

if i used jquery, just 100KB

The official did not provide a very good compression program, a house, no matter how beautiful you decorate the inside, if the appearance is very ugly, very few people live in

I hope official can provide very good compression scheme, to dispel the concerns of us, let each of us can proceed to use it

Many times, I am hesitant, want to change jQuery to do my website front end

I love angular, and use it to do the management interface

**Comment by ericmartinezr** [comment] 2016-06-19 14:07
dup of https://github.com/angular/angular-cli/issues/1136

**Comment by robwormald** [comment] 2016-06-19 20:45
Closing as a dupe of angular/angular-cli#1136

Small bundle sizes are possible with the offline compiler, and documentation will be forthcoming on how to use it. For example: https://ng2-weather-pwa.firebaseapp.com/

**Closed by robwormald** 2016-06-19 20:45 UTC
