### ISSUE TITLE
common: `formatDate()` does not fail to parse invalid dates in Internet Explorer

### ISSUE THREAD

**Issue by imyrups** [angular/angular#28755] opened 2019-02-15 11:26 UTC
When using datePipe.transform('14/02/2019','MM/dd/yyyy') does not throw error in IE, while it does throw an error in Chrome and Firefox.
I've tried to create new Date('14/02/2019') -> returns Invalid Date in Chrome and Firefox.
IE version: 11.0.9600.19129

If there is any other way for invalid dates to throw error which could be consistent?

**Comment by petebacondarwin** [comment] 2020-05-26 11:02
The problem is that if we cannot parse the date string ourselves we fall back on the browsers `Date.parse()` functionality, which is browser dependent. In the case of IE11 it makes its best attempt at parsing rather than throwing, which is what most modern browsers do.

I note in the [MDN `Date` constructor docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/Date#Timestamp_string) it says: 

> Note: Parsing of date strings with the Date constructor (and Date.parse(), which works the same way) is strongly discouraged due to browser differences and inconsistencies.

I think we could consider adding a `strict` option to `formatDate` (and `DatePipe`) that will not attempt to use the `Date.parse()` function if we cannot parse the date ourselves, and instead just throw.

As a workaround you could create your own date pipe that checks the date validity before calling the `DatePipe` transform perhaps.

**Comment by AndrewKushnir** [comment] 2022-03-01 00:24
Closing this ticket, since the reported problem was only present in IE11 and Angular no longer supports IE.

**Closed by AndrewKushnir** 2022-03-01 00:24 UTC
Labels: type: bug/fix, comp: common, comp: i18n, freq1: low, workaround2: non-obvious, state: confirmed, browser: ie 11, triage #1, P4
