### ISSUE TITLE
`ng build  --verbose` does not work for libraries

### ISSUE THREAD

**Issue by tsteuwer-accesso** [angular/angular#59154] opened 2024-12-11 16:08 UTC
### Which @angular/* package(s) are the source of the bug?

compiler-cli

### Is this a regression?

Yes

### Description

According to [the documentation](https://angular.dev/cli/build), I should be able to pass the build argument `--verbose=true`, but the CLI bails saying:

```
Error: Unknown argument: verbose
```

This works if I build an application, but not a library, and there's no indication in the documentation that this doesn't work for building libraries.

I'm running into an issue where building the library gives no help with an error I'm encountering:

```
ng build my-library
Building Angular Package

------------------------------------------------------------------------------
Building entry point '@acme/my-library'
------------------------------------------------------------------------------
✖ Compiling with Angular sources in Ivy partial compilation mode.
Cannot destructure property 'pos' of 'file.referencedFiles[index]' as it is undefined.
```

### Please provide the exception or error you saw

```true
ng build my-library --verbose=true
Error: Unknown argument: verbose
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 18.2.8
Node: 22.5.1
Package Manager: npm 10.8.2
OS: linux x64

Angular: undefined
... 

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1802.8
@angular-devkit/build-angular   18.2.8
@angular-devkit/core            18.2.11
@angular-devkit/schematics      18.2.8
@angular/cli                    18.2.8
@schematics/angular             18.2.8
ng-packagr                      18.2.1
typescript                      5.5.4
```

**Comment by JoostK** [comment] 2024-12-11 16:18
This is working as documented on the page you linked:

> The command can be used to build a project of type "application" or "library". When used to build a library, a different builder is invoked, and only the ts-config, configuration, poll and watch options are applied. All other options apply only to building applications.

Duplicate of angular/angular-cli#28891

**Closed by JoostK** 2024-12-11 16:18 UTC
