### ISSUE TITLE
Add an option/config property within the HttpRequest object

### ISSUE THREAD

**Issue by cacothi** [angular/angular#19933] opened 2017-10-25 18:46 UTC
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[X] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
The current HttpRequest has several options that you can set before the Http.[method] happened. 

## Expected behavior
Implementing the HttpInterceptor, would be nice to have an options/config property within the HttpRequest to be able to set some configuration specific for a request.

## Minimal reproduction of the problem with instructions
With a HttpInterceptor is possible to implement a general error treatment for the application, however I may want to suppress the error for a specific request, which I would handle it withing the component. 

## What is the motivation / use case for changing the behavior?
Give more flexibility for the request talks to the interceptor.

## Environment

<pre><code>
Angular version: 4.3.6

</code></pre>

**Comment by alxhub** [comment] 2017-10-25 19:46
Duplicate of #18155 (which is planned to be implemented)

**Closed by alxhub** 2017-10-25 19:46 UTC
