### ISSUE TITLE
not able to install

### ISSUE THREAD

**Issue by vamsiambati** [angular/angular#42314] opened 2021-05-25 12:23 UTC
![image](https://user-images.githubusercontent.com/22549020/119497269-fe4fb700-bd81-11eb-9b6c-8a307fa61017.png)

the installation is stuck at the above step

**Comment by alan-agius4** [comment] 2021-05-25 12:24
Closing as this is not caused by Angular.

This can be caused by either poor internet connectivity, corrupted NPM cache or NPM having intermittent issues.

**Closed by alan-agius4** 2021-05-25 12:24 UTC
