### ISSUE TITLE
HMR not working with Ivy

### ISSUE THREAD

**Issue by splincode** [angular/angular#35409] opened 2020-02-13 08:08 UTC
### Affected Package

The issue is caused by package @angular/compiler

### Is this a regression?

Yes

### Description

After the first change in the code and update, we get an error

## 🔬 Minimal Reproduction

`src/hmr.ts`

```ts
import { NgModuleRef, ApplicationRef } from '@angular/core';
import { createNewHosts } from '@angularclass/hmr';

export const hmrBootstrap = (module: any, bootstrap: () => Promise<NgModuleRef<any>>) => {
  let ngModule: NgModuleRef<any>;
  module.hot.accept();
  bootstrap().then(mod => ngModule = mod);
  module.hot.dispose(() => {
    const appRef: ApplicationRef = ngModule.injector.get(ApplicationRef);
    const elements = appRef.components.map(c => c.location.nativeElement);
    const makeVisible = createNewHosts(elements);
    ngModule.destroy();
    makeVisible();
  });
};
```

```ts
@Component({
    selector: 'hello',
    template: 'hello',
    changeDetection: ChangeDetectionStrategy.OnPush,
    encapsulation: ViewEncapsulation.None
})
export class HelloComponent {}

@NgModule({
    imports: [
        BrowserModule, 
        CommonModule, 
        HttpClientModule, 
        BrowserAnimationsModule
    ],
    declarations: [AppComponent, HelloComponent],
    bootstrap: [AppComponent]
})
export class AppModule {
}
```

## 🔥 Exception or Error
<pre><code>
main.ts:16 Error: Type AppComponent is part of the declarations of 2 modules: AppModule and AppModule! Please consider moving AppComponent to a higher module that imports AppModule and AppModule. You can also create a new NgModule that exports and includes AppComponent then import that NgModule in AppModule and AppModule.

Type HelloComponent is part of the declarations of 2 modules: AppModule and AppModule! Please consider moving HelloComponent to a higher module that imports AppModule and AppModule. You can also create a new NgModule that exports and includes HelloComponent then import that NgModule in AppModule and AppModule.

    at verifySemanticsOfNgModuleDef (core.js:38474)
    at Function.get (core.js:38383)
    at getInjectorDef (core.js:424)
    at R3Injector.processInjectorType (core.js:16594)
    at core.js:16426
    at core.js:1367
    at Array.forEach (<anonymous>)
    at deepForEach (core.js:1367)
    at new R3Injector (core.js:16422)
    at createInjector (core.js:16386)
</code></pre>

## 🌍  Your Environment

Last Angular (v9.0.0)

**Comment by pkozlowski-opensource** [comment] 2020-02-13 09:33
Duplicate of #35265

**Closed by pkozlowski-opensource** 2020-02-13 09:33 UTC
