### ISSUE TITLE
New New Router does not work alongside ngUpgrade

### ISSUE THREAD

**Issue by Guardiannw** [angular/angular#9973] opened 2016-07-11 19:40 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[x] feature request
```

**Current behavior**
New router does not work with ngUpgrade.  There is no way to specify a primary app component as in the beta router.  And even when you try to do the same, you get an error that states `getAllAngularRootElements is not defined`

**Expected/desired behavior**
New router should work with ngUpgrade

**What is the motivation / use case for changing the behavior?**
To reduce re-coding when Angular2 hits release.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** [Chrome 51] 
 
* **Language:** [TypeScript 1.8.10]

**Comment by brandonroberts** [comment] 2016-07-12 01:33
Dupe of #9870

**Comment by vsavkin** [comment] 2016-07-14 18:39
Duplicate of #9870

**Closed by vsavkin** 2016-07-14 18:39 UTC
