### ISSUE TITLE
Agular 2 ignore target attribute

### ISSUE THREAD

**Issue by chintan3100** [angular/angular#22787] opened 2018-03-15 03:26 UTC
Below code working with HTML Page but when I run same come with angular 2 not, It's didn't worked.
```

<div style='background-color:red'>

 <iframe class="custom-frame" #frame width="400" height="400" id="frame" name="frame" frameborder="0" ></iframe>
</div>
                <form target="frame" action="https://en.wikipedia.org/wiki/IFrame" #form method="get" >
                 
                    <button type="submit" value="submit" >my button</button>
                </form>
				
```

**Comment by trotyl** [comment] 2018-03-15 04:02
Duplicate of #16689

**Comment by matsko** [comment] 2018-03-21 18:28
Closing this in favor of #16689.

**Closed by matsko** 2018-03-21 18:28 UTC
