### ISSUE TITLE
Dynamic form with [checkbox, radio, file] does not pick up formControlName

### ISSUE THREAD

**Issue by michael-letcher** [angular/angular#21418] opened 2018-01-09 17:05 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Following the design pattern given via Angular's [Dynamic Form](https://angular.io/guide/dynamic-form) guide I have found that checkbox, radio and file do not work within the question component.

Only by following this [answer](https://stackoverflow.com/a/37413304/2536454) did they begin to work.

The issue seems to be that when the html elements are dynamically build they do not connect via the formControlName.

Working code: 

```
<input (change)="field.value = $event.target.files" [(ngModel)]="field.value" [formControlName]="field.key" [type]="field.type">
```

## Expected behavior

I would expect that code like this

```
<input [formControlName]="field.key"  [type]="field.type" >
```

would work for the file type, just as it works for others when dynamically built.

## Minimal reproduction of the problem with instructions
[Plunker](https://plnkr.co/edit/nOd5LpFP9wmTuPRx8jT7?p=preview): template has both the working and broken html

## What is the motivation / use case for changing the behavior?

There is no documentation regarding this limitation on the guide or in any other official document I've found.

I would expect this to work just like all other form input methods.

## Environment

<pre><code>
Angular version: 5.1.2

Browser:
- [X] Chrome (desktop) version 63.0.3239.132
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

REF: #8811

**Comment by kara** [comment] 2018-01-25 23:49
Dupe of https://github.com/angular/angular/issues/13243

**Closed by kara** 2018-01-25 23:49 UTC
Labels: comp: forms
