### ISSUE TITLE
Afar Language Locale files are Missing inside @angular/common/locales directory

### ISSUE THREAD

**Issue by betsegawlemma** [angular/angular#53611] opened 2023-12-17 16:35 UTC
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

No

### Description

I was working on a multi (six) language application that reloads the angular application when the language is changed.
The application works fine for the 5 languages (English, Amharic, Afaan Oromoo, Somali, Tigrai). However it shows the  error posted below when I switch to Afar language

    And I have noticed that inside the  @angular/common/locales directory the corresponding files for the Afar language are not generated.
    
    In the ISO 639-1 language Code list (https://www.loc.gov/standards/iso639-2/php/code_list.php) the language code for Afar is `aa`.

### Please provide the exception or error you saw

```true
`ERROR Error: Cannot find module './aa.mjs'
    at .*\.mjs$ include: (en|am|om|ti|so|aa)\.mjs$ namespace object:54:1
    at _ZoneDelegate.invoke (zone.js:368:26)
    at Object.onInvoke (core.mjs:14695:33)
    at _ZoneDelegate.invoke (zone.js:367:52)
    at Zone.run (zone.js:129:43)
    at zone.js:1257:36
    at _ZoneDelegate.invokeTask (zone.js:402:31)
    at core.mjs:14369:55
    at AsyncStackTaggingZoneSpec.onInvokeTask (core.mjs:14369:36)
    at _ZoneDelegate.invokeTask (zone.js:401:60)`
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.0.6
Node: 20.10.0
Package Manager: yarn 1.22.19
OS: linux x64

Angular: 17.0.6
... animations, cli, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.6
@angular-devkit/build-angular   17.0.6
@angular-devkit/core            17.0.6
@angular-devkit/schematics      17.0.6
@angular/cdk                    17.0.3
@angular/material               17.0.3
@schematics/angular             17.0.6
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.2
```

**Comment by JoostK** [comment] 2023-12-18 17:51
Afar was only added as language in CLDR 43, while Angular currently uses CLDR 41. Closing as duplicate of #48697.

**Closed by JoostK** 2023-12-18 17:51 UTC
Labels: area: common
