### ISSUE TITLE
ng serve breaks the intellisense in templates

### ISSUE THREAD

**Issue by dbrezoev** [angular/angular#42852] opened 2021-07-14 15:30 UTC
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

Yes

### Description

Step 1. ng new demo 
Step 2. Go to `app.component.html `and assert that `[ngSwitch]` is navigable. (Ctrl + enter) or (cmd + return on mac)
<img width="1189" alt="Screenshot 2021-07-14 at 18 17 40" src="https://user-images.githubusercontent.com/6537017/125648899-d4feaca1-720a-473c-96b9-a42c4e2e7732.png">
Step 3. Run `ng serve`
Step 4. Close `app.component.html` and open it again.
Step 5. The same `[ngSwitch]` and also all the other ng attributes (`*ngFor` `*ngRepeat`) are not navigable and are underlined, although working
<img width="1113" alt="Screenshot 2021-07-14 at 18 28 17" src="https://user-images.githubusercontent.com/6537017/125649033-a9292604-c960-4d69-8f5a-3dcbd5e0c9e3.png">

My environment:
MacOs Big Sur
Node 14.17.3
ng cli 12.1.1
IDE: Intellij Idea

**Comment by JoostK** [comment] 2021-07-14 16:08
Jetbrains has their own analysis of Angular templates so it's unclear whether this is an Angular bug or not.

**Comment by alan-agius4** [comment] 2021-07-14 16:31
Probably a duplicate of https://github.com/angular/angular-cli/issues/21341 were the root cause seems to be Jetbrains.

**Comment by JoostK** [comment] 2021-07-14 16:42
Thanks @alan-agius4, indeed. Please see https://github.com/angular/angular-cli/issues/21341#issuecomment-879597565 for the list of relevant Jetbrains issues.

**Closed by JoostK** 2021-07-14 16:42 UTC

**Comment by dbrezoev** [comment] 2021-07-14 16:44
OK, thanks it really is the same issue.
