### ISSUE TITLE
noscript content being rendered as DOM children instead of text

### ISSUE THREAD

**Issue by kevinphelps** [angular/angular#31315] opened 2019-06-27 15:02 UTC
# 🐞 bug report

### Affected Package
Not sure.

### Is this a regression?
Also not sure.

### Description
When an Angular component renders a `noscript` element (use case: server rendering), the child content of the `noscript` element are appended as actual DOM element rather than just inner text. This causes axe-core to throw accessibility warnings for discernible text within the `noscript` content. See dequelabs/axe-core#1648, specifically https://github.com/dequelabs/axe-core/issues/1648#issuecomment-505118104, for more information.

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-asergg?file=src%2Fapp%2Fapp.component.html

I simply added the following to `app.component.html`:

```html
<noscript>
  <p>noscript content</p>
</noscript>
```

This is the result in dev tools:

![image](https://user-images.githubusercontent.com/7399499/60277152-a6248780-98c2-11e9-9bb1-e9e0bb21a1b4.png)

If you right click on the `noscript` element, select "edit as html" and edit the text, and then click outside of the text box, the browser will correctly interpret the contents as text:

![image](https://user-images.githubusercontent.com/7399499/60277028-5fcf2880-98c2-11e9-875e-f8e4a565e01d.png)

## 🔥 Exception or Error
Not applicable.

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 7.3.2
Node: 10.15.3
OS: win32 x64
Angular: 7.2.5
... animations, common, compiler, compiler-cli, core, elements
... forms, http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.2
@angular-devkit/build-angular     0.13.2
@angular-devkit/build-optimizer   0.13.2
@angular-devkit/core              7.3.2
@angular-devkit/schematics        7.3.2
@angular/cli                      7.3.2
@schematics/angular               7.3.2
@schematics/update                0.13.2
rxjs                              6.4.0
typescript                        3.2.4
webpack                           4.29.5
</code></pre>

**Comment by kevinphelps** [comment] 2019-06-27 15:08
My workaround is to put `*ngIf="node"` on the `noscript` element to prevent Angular from rendering that DOM element in the browser as it only needs to be rendered on the server.

**Comment by trotyl** [comment] 2019-06-28 03:51
Duplicate of https://github.com/angular/angular/issues/30523

**Comment by alxhub** [comment] 2019-07-02 22:57
Closing as a duplicate of #30523 - this is also effectively a request for `<noscript>` special-casing in Angular (especially in platform-server). Currently this is not supported.

**Closed by alxhub** 2019-07-02 22:57 UTC
Labels: comp: core
