### ISSUE TITLE
[Bug] Inconsistent behavior for ContentChildren with structural directive

### ISSUE THREAD

**Issue by youdz** [angular/angular#16388] opened 2017-04-27 19:36 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When content children of a component depend on an action performed by said component in `ngAfterContentInit()`, they have different behaviors based on whether they have a structural directive or not:
- if they do not have a structural directive on them, everything works fine,
- if they have a structural directive (it happens with both `*ngIf` and `*ngFor`), the app throws an "Expression has changed after it was checked" error.

**Expected behavior**

The behavior should be the same for both cases. I don't know if both cases should be fine or if both cases should throw the error, but the inconsistency shouldn't be here, it breaks apps that worked fine because of non-related changes.

**Minimal reproduction of the problem with instructions**

https://plnkr.co/edit/s1IgrVtht5nsqmmxyv7g?p=preview
Open the console and you can see for yourself 
```
ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'happy'. Current value: 'very happy'.
```
If you remove the `*ngIf="true"`, everything is fine. If you replace it with `*ngFor="let n of [1]"`, you get the error again.

**What is the motivation / use case for changing the behavior?**

I do realize that this plunker example uses `ngAfterContentInit()` for no reason, but it was just to show the inconsistency with a minimal example. In real-life cases, the action performed in `ngAfterContentInit()` can depend on `@ContentChildren`, whether it's the same ones or others.
I'm not sure what the final behavior should be, but I'm 100% sure it should not be inconsistent as it is today.

* **Angular version:** 4.X

* **Browser:** all

 
* **Language:** all

**Comment by pkozlowski-opensource** [comment] 2019-03-23 13:15
This sounds _very_ similar to #24563 and I suspect that both have the same root cause. To be investigated / fixed together.

**Comment by pkozlowski-opensource** [comment] 2020-05-27 14:53
This continues to be the problem in Angular v9 running ivy: https://stackblitz.com/edit/angular-dirvgi?file=src/app/app.module.ts

This bug is about inconsistent behaviour of "Expression has changed after it was checked" error for the 2 following cases:

No error thrown (unexpected):
```html
<parent>
     <child></child>
</parent>
```

No error thrown (expected):
```html
<parent>
     <child *ngIf="true"></child>
</parent>
```
Is seems like there is a subtle timing difference between refreshing child component views and embedded views.

**Comment by atscott** [comment] 2024-02-03 22:46
Closing as resolved by using a signal for state https://stackblitz.com/edit/angular-wbdt6m?file=src%2Fpolyfills.ts%2Csrc%2Fapp%2Fapp.module.ts&memory-freed=1

**Closed by atscott** 2024-02-03 22:46 UTC
Labels: type: bug/fix, freq2: medium, area: core, state: confirmed, core: queries, core: change detection, P4
