### ISSUE TITLE
Error and small incostincency in RouterLink

### ISSUE THREAD

**Issue by PavelPZ** [angular/angular#7586] opened 2016-03-13 16:30 UTC
See [Plunker](http://plnkr.co/edit/fj6lzemiFQUP5XsdjQHN?p=preview) and select its *Launch the preview in a separate window* in order to see resulting url:

- ```['/Parent', {}, 'Child']">/Parent', {}, 'Child']``` raises runtime error during application start
- ```['/Parent2', {par:1, w:0, x:1}, 'Child2', {id:2, y:10, z:11}]``` produces this url: ```#/parent2/1/child2/2;y=10;z=11?w=0&x=1```, with some incostincency in processing extra parent-child attributes. I can expect ```#/parent2/1/child2/2?y=10&z=11&w=0&x=1```

**Comment by brandonroberts** [comment] 2016-03-13 18:55
An empty `{}` in an expression is a duplicate of https://github.com/angular/angular/issues/6579

As far as the URL goes, its working as designed. Optional parameters for root level routes are represented as query string parameters (?name1=value1&name2=value2). Child level routes are represented as matrix parameters (;name1=value1;name2=value2)

If you want all your optional parameters to be querying string parameters, they need to be in the params for the `Parent` in this case.

`['/Parent2', {par:1, w:0, x:1, y:10, z:11}, 'Child2', {id:2}]`

**Comment by PavelPZ** [comment] 2016-03-13 19:13
@brandonroberts, thanks for an explanation and sorry for the duplicity.

**Comment by brandonroberts** [comment] 2016-03-13 20:04
:+1:

**Closed** 2016-03-15 00:50 UTC
