### ISSUE TITLE
Animation of elements, rendered by built-in control flow (@-for) is not always correct

### ISSUE THREAD

**Issue by e-oz** [angular/angular#52526] opened 2023-11-06 14:00 UTC
### Which @angular/* package(s) are the source of the bug?

animations

### Is this a regression?

No

### Description

When the list contains fewer than 3 items, their "enter" and "leave" animations are wrong if the list was created using `@for`.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-zj1g1s?file=src%2Fmain.ts

### Please provide the exception or error you saw

```true
I wrote all the steps to reproduce and detect the issue by that repro link.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular 17.0.0-rc.2 (&rc.3 - see package.json)
```

### Anything else?

Tested in Chrome 118.0.5993.117, 119.0.6045.105, 120.0.6099.5.

**Comment by pkozlowski-opensource** [comment] 2023-11-06 14:07
> When the list contains fewer than 3 items, their "enter" and "leave" animations are wrong if the list was created using @for.

Would adding actual tracking expression (I'm assuming `message.id`) help here? We can definitively expect different order of DOM operations with the new diffing algorithm. More specifically, items are removed from the end. 

When the full list is replaced it is hard to make guarantees, hence the importance of the tracking expressions, especially for the immutable data.

**Comment by e-oz** [comment] 2023-11-06 14:36
That's because the first list was affecting position of the second list.
I modified your code to remove this effect:
https://stackblitz.com/edit/stackblitz-starters-7uvwkh?file=src%2Fmain.ts

> having message.id as the track function seems to animate, still...

Here you are right, I was using "track" wrong (need docs! ;))

And video:

https://github.com/angular/angular/assets/526352/96d1d5f5-7ef6-4f8e-9e58-ed806b2640e0

**Comment by pkozlowski-opensource** [comment] 2023-11-06 15:02
> It is only reproducible with fewer than 3 animations, somehow - it gives me hope that it's not a fundamental difference and it is possible to fix.

I need to dig into it a bit more but I _think_ that what is going on is that one of the item is _not_ added / removed from the collection (the new alg is smarter with moves), so the enter / leave animations don't kick in.

This is tough since I believe that the algorithm is doing "the right thing" but this is an observable difference as compared to ngFor.

**Comment by e-oz** [comment] 2023-11-06 15:11
I've modified the CSS a little to make the difference more noticeable:
https://stackblitz.com/edit/stackblitz-starters-7uvwkh?file=src%2Fmain.ts

> This is tough since I believe that the algorithm is doing "the right thing" but this is an observable difference as compared to ngFor.

For some period, it is ok to use ngFor as a workaround, but if the algorithm could somehow "notice" the presence of "@animate" and don't apply these optimisations - that would be nice.

**Comment by pkozlowski-opensource** [comment] 2024-03-08 17:26
Coming back to my [previous comment](https://github.com/angular/angular/issues/52526#issuecomment-1795032464) - after playing with it more and thinking through this issue we've decided to mark it as "works as intended".

What is going on here is that the updated algorithm is doing less view / DOM manipulation - and this was one of the main points of doing the build-in control flow. It seems like your animations setup is closely tied to the inner working of the existing ngFor algorithm.

I'm going to close it for now as I see the change in behaviour as a bug fix. But will keep an eye on similar reports and reconsider if those are common.

**Closed by pkozlowski-opensource** 2024-03-08 17:26 UTC
Labels: area: animations, area: core, core: control flow
