### ISSUE TITLE
Cannot reattach ActivatedRouteSnapshot created from a different route

### ISSUE THREAD

**Issue by wang777777** [angular/angular#40515] opened 2021-01-22 11:24 UTC
# 🐞 bug report

### Affected Package

    "@angular/animations": "~9.0.2",
    "@angular/cdk": "^9.1.0",
    "@angular/common": "~9.0.2",
    "@angular/compiler": "~9.0.2",
    "@angular/core": "~9.0.2",
    "@angular/forms": "~9.0.2",
    "@angular/platform-browser": "~9.0.2",
    "@angular/platform-browser-dynamic": "~9.0.2",
    "@angular/router": "~9.0.2",
    "@angular/service-worker": "~9.0.2",

### Description

 A clear and concise description of the problem...
1. navigateByUrl('/dashboard') which is not RouteReuseStrategy
2. then navigateByUrl('/cached') which is RouteReuseStrategy
3. then navigateByUrl('/dashboard')
4. then navigateByUrl('/cached') which is RouteReuseStrategy
error: Cannot reattach Activated Route Snapshot created from a different route

## 🔥 Exception or Error
<pre><code>

Cannot reattach Activated Route Snapshot created from a different route
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

9.0.2

</code></pre>

<pre><code>
import { RouteReuseStrategy, ActivatedRouteSnapshot, DetachedRouteHandle } from '@angular/router';
import * as _ from 'lodash';

export interface RouteReuseStorage {
  key: string;
  handle: DetachedRouteHandle;
}

export class ReuseStrategyService implements RouteReuseStrategy {
  public static storages: RouteReuseStorage[] = [];
  private static waitDelete: string | null;

  public shouldDetach(route: ActivatedRouteSnapshot): boolean {
    // keep which you want RouteReuseStrategy
   // /dashboard keep: false
  // /cached keep: true
    return  !!route.data.keep;
  }

  public store(route: ActivatedRouteSnapshot, handle: DetachedRouteHandle): void {
    if (handle == null) return;
    if (ReuseStrategyService.waitDelete && this.getRouteUrl(route).indexOf(ReuseStrategyService.waitDelete) == 0) {
      ReuseStrategyService.waitDelete = null;
      return;
    }

    this.add(this.getRouteUrl(route), handle);
  }

  public shouldAttach(route: ActivatedRouteSnapshot): boolean {
    if (!route.routeConfig || route.routeConfig.loadChildren) {
      return false;
    }
    return !!_.find(ReuseStrategyService.storages, (x) => x.key == this.getRouteUrl(route));
  }

  public retrieve(route: ActivatedRouteSnapshot): DetachedRouteHandle | null {
    if (!route.routeConfig) return null;
    if (route.routeConfig.loadChildren) return null;
    let stroage = _.find(ReuseStrategyService.storages, (x) => x.key == this.getRouteUrl(route));
    return stroage ? stroage.handle : null;
  }

  public shouldReuseRoute(future: ActivatedRouteSnapshot, curr: ActivatedRouteSnapshot): boolean {
    console.log(future, curr)
    if (future.children && future.children.length && future.children[0].data && future.children[0].data.keep) {
      return false;
    }
    return future.routeConfig === curr.routeConfig ;
  }

  private getRouteUrl(route: ActivatedRouteSnapshot) {
    let url = (route as any)['_routerState'].url.replace(/\//g, '_')
    return url;
  }

  public static deleteRouteSnapshot(name?: string): void {
    if (name) {
      let key = name.replace(/\//g, '_');
      _.remove(ReuseStrategyService.storages, (x) => x.key.indexOf(key) === 0);
      ReuseStrategyService.waitDelete = key;
    } else {
      ReuseStrategyService.storages = [];
    }
  }

  private add(key: string, handle: DetachedRouteHandle) {
    _.remove(ReuseStrategyService.storages, (x) => x.key == key);
    ReuseStrategyService.storages = [...ReuseStrategyService.storages, { key: key, handle: handle }];
  }

  public static closeOther(name?: string): void {
    ReuseStrategyService.storages = ReuseStrategyService.storages.filter(i => i.key === name);
  }
}

</code></pre>

**Comment by atscott** [comment] 2021-01-22 20:34
Hi @wang777777, could you please provide a minimal reproduction in stackblitz or a github repo?

**Comment by tinet-dongfb** [comment] 2021-01-29 07:27
救命

**Comment by tinet-dongfb** [comment] 2021-01-29 07:28
I need help

**Comment by tinet-dongfb** [comment] 2021-02-01 06:38
在 NG-ALAIN这个中有实现路由复用,目前验证是没有问题的，好像是针对retrieve，shouldAttach，使用了!route.routeConfig || !!route.routeConfig.loadChildren || !!route.routeConfig.children进行判断，并且取url的方式与我们不同，此问题之前好像有回复说并不是一个问题。

**Comment by atscott** [comment] 2021-02-12 01:18
Closing due to lack of reproduction.

**Closed by atscott** 2021-02-12 01:18 UTC
Labels: comp: router, needs reproduction, router: RouteReuseStrategy
