### ISSUE TITLE
bug with styleUrls in component configuration

### ISSUE THREAD

**Issue by koriUA** [angular/angular#6054] opened 2015-12-21 14:27 UTC
angular 2.0.0-beta.0
loader.html and loader.css are located in directory /admin-angular-two/components/loader/

This code doesn't work:
@Component({
 selector: 'loader',
 templateUrl: '/admin-angular-two/components/loader/loader.html',
 styleUrls: ['/admin-angular-two/components/loader/loader.css']
})  

but this works:
@Component({
 selector: 'loader',
 templateUrl: '/admin-angular-two/components/loader/loader.html',
 styleUrls: ['../../../admin-angular-two/components/loader/loader.css']
})  

base url is setted:
<script>document.write('<base href="http://western.pp.ua/admin/default/adminAngularTwo/" />');</script>

**Comment by meenie** [comment] 2015-12-21 22:48
Already reported here: #4974

**Comment by pkozlowski-opensource** [comment] 2016-08-05 16:41
Closing as an duplicate of #4974

**Closed by pkozlowski-opensource** 2016-08-05 16:41 UTC
