### ISSUE TITLE
Angular Service Worker Error

### ISSUE THREAD

**Issue by GlauberF** [angular/angular#42564] opened 2021-06-12 21:40 UTC
# Bug Report

### Description
I use it in my Service Worker projects and I've been noticing some very strange actions.
Example:
I generated a new build and sent it to the server, when I access the application in production, I F5, load the new version and I can find out about it because there are new elements on the screen. But when I close the browser and open the application again, sometimes the previous version appears.

I tested accessing /ngsw/state and I get the message that is in Exception error.

I forced click on unregister in the service worker in developer tools, it registers another service worker, but still in /ngsw/state continues with error log.

Is there a way to identify that the hash failed and if it does, force a new version of the service worker?

I see that I can subscribe to updates.unrecoverable.subscribe(event => }), can I within this subscriber identify the hash error and if there is which call should I use to force a new version of the service worker and clear the old caches?

Because after I force a new service worker and clear the cache, I reload the page.

## Exception or Error
NGSW Debug Info:

Driver state: EXISTING_CLIENTS_ONLY (Degraded due to: Hash mismatch (cacheBustedFetchFromNetwork): https://app-homologacao.vimbo.com.br/index.html: expected 5de6c86e05d6b19ff5af1ddc70b13ddf5a9c5b1d, got 2ae958e133c27c01180cf89450c7eaaa06e04758 (after cache busting)
Error: Hash mismatch (cacheBustedFetchFromNetwork): https://app-homologacao.vimbo.com.br/index.html: expected 5de6c86e05d6b19ff5af1ddc70b13ddf5a9c5b1d, got 2ae958e133c27c01180cf89450c7eaaa06e04758 (after cache busting)
    at PrefetchAssetGroup.<anonymous> (https://app-homologacao.vimbo.com.br/ngsw-worker.js:763:39)
    at Generator.next (<anonymous>)
    at fulfilled (https://app-homologacao.vimbo.com.br/ngsw-worker.js:196:32))
Latest manifest hash: 2fce0503941ec162304bac74567f750c37aef515
Last update check: 8m58s281u

=== Version 2fce0503941ec162304bac74567f750c37aef515 ===

Clients: 

=== Idle Task Queue ===
Last update tick: 1s541u
Last update run: 8m51s677u
Task queue:
 * check-updates-on-navigation

Debug log:

[8m51s565u] Error(Hash mismatch (cacheBustedFetchFromNetwork): https://app-homologacao.vimbo.com.br/index.html: expected 5de6c86e05d6b19ff5af1ddc70b13ddf5a9c5b1d, got 2ae958e133c27c01180cf89450c7eaaa06e04758 (after cache busting), Error: Hash mismatch (cacheBustedFetchFromNetwork): https://app-homologacao.vimbo.com.br/index.html: expected 5de6c86e05d6b19ff5af1ddc70b13ddf5a9c5b1d, got 2ae958e133c27c01180cf89450c7eaaa06e04758 (after cache busting)
    at PrefetchAssetGroup.<anonymous> (https://app-homologacao.vimbo.com.br/ngsw-worker.js:763:39)
    at Generator.next (<anonymous>)
    at fulfilled (https://app-homologacao.vimbo.com.br/ngsw-worker.js:196:32)) initializeFully for 2fce0503941ec162304bac74567f750c37aef515
[7s914u] TypeError(Failed to fetch, TypeError: Failed to fetch) Driver.fetch(https://www.google.com.br/ads/ga-audiences?t=sr&aip=1&_r=4&slf_rd=1&v=1&_v=j90&tid=UA-80436761-1&cid=825317964.1623532590&jid=112875176&_u=QACAAEAAAAAAAC~&z=1381826650)
</code></pre>

## Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 11.2.12
Node: 14.16.1
OS: linux x64

Angular: 11.2.13
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1102.11
@angular-devkit/build-angular      0.1102.12
@angular-devkit/build-optimizer    0.1101.4
@angular-devkit/core               11.2.11
@angular-devkit/schematics         11.2.12
@angular/cdk                       11.2.12
@angular/cli                       11.2.12
@angular/flex-layout               11.0.0-beta.33
@angular/material                  11.2.12
@angular/material-moment-adapter   11.2.12
@nguniversal/builders              11.2.1
@nguniversal/express-engine        11.2.1
@schematics/angular                11.2.12
@schematics/update                 0.1102.12
rxjs                               6.6.7
typescript                         4.1.5
</code></pre>

**Anything else relevant?**
https://app-homologacao.vimbo.com.br/ngsw/state

**Comment by gkalpak** [comment] 2021-06-13 08:22
@GlauberF, as the error says, there is a hash mismatch in the `index.html` file. That means that the contents of the file served to the app are different from the contents of the file right after building, so the ServiceWorker can't tell it is downloading the correct file.

See https://github.com/angular/angular/issues/40049#issuecomment-742578878 for more details.

##
I am going to close the issue, since this looks like an application-side error, but feel free to continue the discussion below.

**Closed by gkalpak** 2021-06-13 08:22 UTC

**Comment by GlauberF** [comment] 2021-06-14 14:49
So, I followed the comment and as I use cloudflare, I disabled everything that could give a problem and the error continues, I opened a call in cloudflare to see if in fact the error is on their side.

But until the call is answered, I want to share my `ngsw-config.json`, to make sure the error is not a configuration error in the file.

```json
{
    "$schema": "./node_modules/@angular/service-worker/config/schema.json",
    "index": "/index.html",
    "assetGroups": [
        {
            "name": "index",
            "installMode": "prefetch",
            "updateMode": "prefetch",
            "resources": {
                "files": ["/favicon.ico", "/index.html", "robots.txt", "/manifest.webmanifest"]
            }
        },
        {
            "name": "app",
            "installMode": "lazy",
            "updateMode": "prefetch",
            "resources": {
                "files": ["/*.css", "/*.js"]
            }
        },
        {
            "name": "assets",
            "installMode": "lazy",
            "updateMode": "prefetch",
            "resources": {
                "files": ["/assets/**", "/*.(eot|svg|cur|jpg|png|webp|gif|otf|ttf|woff|woff2|ani)"],
                "urls": ["https://fonts.googleapis.com/**"]
            }
        }
    ]
}

```

**Comment by gkalpak** [comment] 2021-06-15 09:22
@GlauberF, as mentioned in my previous comment, the error is caused by the fact that the contents of `index.html` change between building the app and serving it to the client. Your first step should be to compare the contents of the `index.html` file right after building the app (via `ng build`) with the contents of `index.html` as served to the client.

**Comment by GlauberF** [comment] 2021-06-16 12:14
@gkalpak After more than a day of testing, I discovered the problem, but it is something related to Angular.

Today my application uses (SSR + Service Worker).

When I generate the build(npm run build:ssr) the `dist` folder is created containing the `browser` and `server` folder.
Having these files, I performed some analysis before getting to the problem.

1 - Looking at the files and the hash, they are identical, so it's not a build problem.
2 - Going into the `dist/browser` folder and running the command `http-server -c-1 --proxy http://localhost:9000 .` the service worker registers and works perfectly `NORMAL ((nominal))` .
3 - Now uploading the server with SSR `node dist/server/main.js` the service worker does not work, it is in the EXISTING_CLIENTS_ONLY state

All tests were done locally, without interference from another service.

The way I register the `ngsw-worker.js`.
```typescript
ServiceWorkerModule.register('ngsw-worker.js', {
    enabled: environment.production,
    registrationStrategy: 'registerWhenStable:30000'
})
```

My server.ts file for SSR is the default, generated by the CLI itself.

**Comment by gkalpak** [comment] 2021-06-17 14:11
@GlauberF, I could not reproduce the issue using the repository you provided (https://github.com/GlauberF/ssr-and-service-worker-error) 😕

I checked out the repo and ran `npm install && npm run build:ssr`. Then, both `http-server -c-1 dist/teste/browser` and `node dist/teste/server/main` worked correctly (i.e. the SW was registered as expected, the site worked offline and the `/ngsw/state` reported the driver state as `nominal`).

**Comment by gkalpak** [comment] 2021-06-17 14:28
:+1: LMK if you run into any more issues.
