### ISSUE TITLE
formGroup reset does not reset the property valid

### ISSUE THREAD

**Issue by LuizGGeas** [angular/angular#38538] opened 2020-08-19 17:37 UTC
when resetting formgroup after submission, it does not change the valid element of the form

**Comment by sonukapoor** [comment] 2020-08-20 12:15
@LuizGGeas I just tried this out with a simple `FormGroup` and a `FormControl` and it seems to work as expected. You can see a stackblitz here:

https://stackblitz.com/edit/angular-ivy-tuawdc?file=src%2Fapp%2Fapp.component.html

If you have a different reproducible, can you please share it?

**Comment by AndrewKushnir** [comment] 2020-08-25 00:17
Closing this ticket since there is no repro, so we can not perform further investigation. Feel free to create a new ticket once repro is available. Thank you.

**Closed by AndrewKushnir** 2020-08-25 00:17 UTC
Labels: comp: forms, forms: Controls API, state: Needs repro
