### ISSUE TITLE
ngUpgrade: The problem with upgrade the directives that use `require` attribute

### ISSUE THREAD

**Issue by aryaroudi** [angular/angular#29187] opened 2019-03-08 12:19 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/upgrade/static

### Is this a regression?

 No

### Description

 I upgraded an AJS directive that uses `require` attribute and needs the other directive controller:

```
            return {
                restrict: 'E',
                require: '^uiDrop',
                scope: true,
                controllerAs: 'uiDropTarget'
            };
```

So the question is how it should see the required controller in the upgraded directive? As I see in the official document there is no example for this however, they didn't mention this attribute in *SHOULD NOT USE* section. Not sure if it is a bug or something missing from documentation or it is not supported bu ngUpgrade

## 🔥 Exception or Error
<pre><code>
angular.js:13920 Error: Unable to find required '^uiDrop' in upgraded directive 'uiTooltipTarget'.
    at UpgradeHelper../node_modules/@angular/upgrade/fesm5/static.js.UpgradeHelper.resolveRequire (static.js:1260)
    at static.js:1242
    at Array.map (<anonymous>)
    at UpgradeHelper../node_modules/@angular/upgrade/fesm5/static.js.UpgradeHelper.resolveRequire (static.js:1242)
    at UpgradeHelper../node_modules/@angular/upgrade/fesm5/static.js.UpgradeHelper.resolveAndBindRequiredControllers (static.js:1200)
    at UiTooltipTargetDirective../node_modules/@angular/upgrade/fesm5/static.js.UpgradeComponent.ngOnInit (static.js:1388)
    at checkAndUpdateDirectiveInline (core.js:20665)
    at checkAndUpdateNodeInline (core.js:21929)
    at checkAndUpdateNode (core.js:21891)
    at debugCheckAndUpdateNode (core.js:22525)
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Node: 8.12.0
OS: darwin x64
Angular: 7.1.4
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.11.4
@angular-devkit/build-angular     0.11.4
@angular-devkit/build-optimizer   0.11.4
@angular-devkit/core              7.1.4
@angular-devkit/schematics        7.1.4
@angular/cdk                      7.3.3
@angular/upgrade                  7.2.8
@ngtools/webpack                  8.0.0-beta.5
@schematics/angular               7.1.4
@schematics/update                0.11.4
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.29.1
</code></pre>

**Anything else relevant?**

**Comment by gkalpak** [comment] 2019-03-08 20:18
In general it should be able to retrieve the required parent controller from the AngularJS directive as usual.
Could you create a minimal reproduction of the issue? (You can use [this template][1] as a starting point.)

[1]: https://stackblitz.com/edit/ngupgradestatic-playground

**Comment by aryaroudi** [comment] 2019-03-11 11:23
hey @gkalpak couldn't reproduce it in the Stackblitz, BTW it still gives me the error for $attr:

https://stackblitz.com/edit/ngupgradestatic-playground-tad6fr

it could be because of the angularjs/angular version?

**Comment by gkalpak** [comment] 2019-03-12 10:32
Yes, `$attrs` are not supported. We used to have a [list of supported/unsupported features][1] for the deprecated dynamic ngUpgrade, we don't seem to have ported it over :thinking:

I'll create an issue for that.

[1]: https://angular.io/api/upgrade/UpgradeAdapter#supported-features-1

**Comment by aryaroudi** [comment] 2019-03-12 13:22
@gkalpak Thanks. I continue investigating this to see why this is happening. I don't know why it is happening only in my local and not happening in stackblitz.

**Comment by gkalpak** [comment] 2019-03-12 16:16
Thx, @aryaroudi. I am going to close this issue, since it is not actionable without a reproduction, but feel free to continue the discussion below.
Happy to re-open and investigate once there is a minimal reproduction.

**Closed by gkalpak** 2019-03-12 16:16 UTC
Labels: comp: upgrade/static, state: Needs repro, type: bug/fix

**Comment by gkalpak** [comment] 2019-03-13 10:24
@aryaroudi, if you are trying to require between two upgraded components and transclusion/projection is involved, you might be running into #24846. That particular usecase does indeed not work, but there's a workaround in #24846 (if you're desperate :grin:).

**Comment by aryaroudi** [comment] 2019-03-14 11:35
> @aryaroudi, if you are trying to require between two upgraded components and transclusion/projection is involved, you might be running into #24846. That particular usecase does indeed not work, but there's a workaround in #24846 (if you're desperate 😁).

Thanks @gkalpak, for now, I just wrap those components inside a wrapper AJS component and upgraded that component and using it in my new Angular and it works! and the next steps going to migrate them completely to the new angular and get rid of them :)
