### ISSUE TITLE
angular2-rc-4 ng-content duplicated dont work

### ISSUE THREAD

**Issue by davidgfolch** [angular/angular#10517] opened 2016-08-05 08:27 UTC
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[ X] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
With multiple &lt;ng-content&gt;&lt;/ng-content&gt; only works last one.

**Expected/desired behavior**
Both should paint content if condition met.

**Reproduction of the problem**

http://stackoverflow.com/questions/38768324/angular2-rc-4-ng-content-duplicated-dont-work

```
<div *ngIf="dialog">
  <ng-content></ng-content>
</div>

<!-- for pages not in dialog popups put all div structure -->
<div *ngIf="!dialog" class="container content">
  <div class="page-header">
    <h2>{{title}}</h2>
  </div>
  <div class="row">
    <div class="col-md-12">
      <ng-content></ng-content>
    </div>
  </div>
</div>

```

**What is the expected behavior?**

Both should paint content if condition met.

**What is the motivation / use case for changing the behavior?**

Paint content in one or another container

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** [all] 
 
* **Language:** [ TypeScript ]

**Comment by pkozlowski-opensource** [comment] 2016-08-05 10:18
Duplicate of #7795

**Closed by pkozlowski-opensource** 2016-08-05 10:18 UTC
