### ISSUE TITLE
'$locationShim': Not a valid '@angular/upgrade' application.

### ISSUE THREAD

**Issue by andreikun** [angular/angular#36877] opened 2020-04-30 17:45 UTC
Hello,

I am trying to use a unified angular location service by following the exact [documentation](https://angular.io/guide/upgrade#using-the-unified-angular-location-service) for running an Angular hybrid between Angular 1.6 app and Angular 9.1.1 and I've got the following error:

`Error: Error while instantiating injectable '$locationShim': Not a valid '@angular/upgrade' application.
Did you forget to downgrade an Angular module or include it in the AngularJS application?`

We are using the lazy-loading upgrade approach available in the official [documentation](https://angular.io/guide/upgrade#lazy-loading-angularjs)

**Comment by gkalpak** [comment] 2020-05-01 12:02
@andreikun, can you please provide a minimal reproduction of the problem. E.g. as a [StackBlitz][1] project or a standalone repo we can check out and run. Otherwise, it is very difficult for us to investigate the issue. 

[1]: https://stackblitz.com/

**Comment by gkalpak** [comment] 2020-05-27 19:18
Closing due to lack of reproduction.

**Closed by gkalpak** 2020-05-27 19:18 UTC
Labels: comp: upgrade, state: Needs repro
