### ISSUE TITLE
Unable to prevent routerLink from navigating

### ISSUE THREAD

**Issue by slubowsky** [angular/angular#10431] opened 2016-08-01 19:40 UTC
**I'm submitting a ...**  (check one with "x")
```
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Attempting to prevent navigation on a routerLink by calling preventDefault on event has no effect.

**Expected/desired behavior**
Navigation should be canceled.

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

See http://plnkr.co/edit/58WrIkqXrevLbCtwgJCN?p=preview

**What is the expected behavior?**
Clicking on "link is to one but want to go to two" should not navigate to component one as specified in routerLink, should navigate to component two instead since (click) is bound to a function that calls event.preventDefault and navigates to two.

**What is the motivation / use case for changing the behavior?**
Want to be able to have "dynamic" default routes - .i.e not hard coded in router config (in real use case want to dynamically route to last child component used under this parent). Using routerLink instead of just code since also want user to be able to right click and choose "open in new window"

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
 all but tested in Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5] 
Using typescript 1.8.10

**Comment by sirajc** [comment] 2016-08-01 19:47
@slubowsky - To cancel a navigation, you should use canDeactivate, preventDefault is not the correct approach. 
In case you want to build dynamic routes, then you can create routes dynamically in your component and then use `this.router.navigate(['dynamicroute','somecomponent'])` to navigate.
Also `routerLink` supports variable binding i.e. you can use `[routerLink]="[dynamicRoute, dynamicComponent]"`

**Comment by slubowsky** [comment] 2016-08-01 20:12
@sirajc canDeactivate will cancel navigation from current component. That is not what I am attempting. I want to dynamically control navigation to next component. Using a canActivate guard might work - with a redirect inside, but pretty sure that would mess with my history.
Also think that many developers might expect preventDefault to work as I did so my suggestion is that this be supported (perhaps it's a feature request not a bug report?)

Using router.navigate in my component also works fine - and I had a code only approach working well, but my user specifically is asking for the default browser behavior that allows users to right click on a link and choose "open in new window". So I need the routerLink to be as good as I can make it (in my case to  a parent component with a default child) for the open in new window case, but within this instance I want to do better and go to the subcomponent I choose, not the default.

Your final suggestion about routerLink supporting variable binding sounds interesting. I thought routerLinks were only evaluated once. I'll have to take a look and see it that can work for me. Do you have a link to any examples?

**Comment by slubowsky** [comment] 2016-08-01 20:35
Changing variable bound to router link works well so using that approach for now. Not sure why I assumed router link wouldn't update when binding changed. Leaving issue open anyway since I still think calling event.preventDefault should prevent navigation.

**Comment by vsavkin** [comment] 2016-08-11 01:05
The router link directive has a click handler and you add your own click handler, so there are two click handlers in play. Since we do not impose any order on event handlers, it is not possible to use preventDefault to cancel the navigation in your handler.

We could provide a separate property (e.g., shouldNavigate) that the router link would use for this purpose. But I'm not sure how common this use case is, so I don't know if it is worth it. 

What you can do instead is to handle navigation imperatively without the router link directive. You can also implement your own directive similar to RouterLink (it is about 20 lines of code) that will support this use case.

Closing this issue.

**Closed by vsavkin** 2016-08-11 01:05 UTC
Labels: comp: router, type: bug

**Comment by troyanskiy** [comment] 2016-08-11 15:26
I have exactly that case just now.

**Comment by troyanskiy** [comment] 2016-08-11 15:28
Actually I wanted to postpone the redirection for some 300ms to wait the animation finish.

**Comment by troyanskiy** [comment] 2016-08-11 15:36
@slubowsky I'm not sure if it's correct to do. I did it like
``` html
<a [href]="getLink()" (click)="testLink()">Link</a>
```

**Comment by slubowsky** [comment] 2016-08-12 14:21
With all the fixes in latest router url is more likely to be correct alleviating most of my problem cases (where binding the value of [routerLink] resulted in it having wrong value which led me down this path in the first place)
Interestingly updating to latest I now have this problem on anchors (not routerLinks - they are actually ng2-bootstrap tabs). First my navigation occurs then the app reloads. Not the same issue of course and hipefully easily solved but I wonder what changed in RC 5...

**Comment by slubowsky** [comment] 2017-01-02 15:35
@vsavkin Can this be reviewed again? While the router has somewhat matured since this issue was written, this continues to be a problem. As far as I can tell there is no way currently to allow for the browser default behavior of being able to right click and choose "open in new window/tab" and still maintain control to prevent the navigation if needed. The suggested approach of navigating imperatively which works great for the deactivate guard doesn't allow for the browser default behavior.
I don't think this is a far fetched use case. Within one window I use a deactivate guard to prevent navigation away when there are changes, but if user chooses to open in new window I want that to work as well.
See also https://github.com/angular/angular/issues/2042 which I think shows that the current behavior is inconsistent and unexpected.

**Comment by shivarajnaidu** [comment] 2017-11-11 17:01
Me Too Facing Same Issue With Angular 5.x 

```
<a  [routerLink]="['/users', user.id]">
{{user.name}} 
<button type="button" (click)="goToUpdateUserView($event, user);">edit</button>
<button type="button" (click)="deleteUser($event, user)">delete</button>
</a>
```

```
goToUpdateUserView(event, user) {
    event.stopPropagation(); 
    console.log('Hi , Prevented  Nav');
  }
```
Even though event.stopPropagation called when clicked on button the page routing to next view.. Just Similar As @marcuslind90 's issue ...

**Comment by cnb3** [comment] 2017-12-06 15:58
@shivarajnaidu I just ran into this as well, solved it with adding $event.preventDefault()

**Comment by dotlouis** [comment] 2017-12-07 13:51
Got the same issue;
Fixed it by putting both `preventDefault()` and `stopPropagation()` on the click handler of the child HTML node. I don't understand why putting either one does not produce any result while putting both produces the intended behavior.
Weirdly enough if you replace the <a> by a <div> you just need stopPropagation().

**Comment by BBaysinger** [comment] 2018-01-17 19:54
I'm still seeing this as a problem. I'm using `$event.stopPropogation()`, `$event.preventDefault()`, and `return false`.

```
  onButtonClick(event: MouseEvent) {
    event.preventDefault();
    event.stopPropagation();
    return false;
  }
```
```
    <li class="" routerLink="release" (click)="onButtonClick($event)" routerLinkActive="active">
      <b>1:</b><b>Information Release Form</b>
  </li>
```
It still routes when I click.

**Comment by bostondevin** [comment] 2018-07-20 16:19
Sounds like a lot of overkill when all you need to do is this:
<a [routerLink]="">Non clickable</a>

**Comment by agiratech-vigneshm** [comment] 2018-08-22 07:45
Route guard is the actual way to do this IMHO.
