### ISSUE TITLE
The ngStyle directive behaves differently than the style directive.

### ISSUE THREAD

**Issue by Smiley01987** [angular/angular#26980] opened 2018-11-07 14:53 UTC
# 🐞 bug report

### Is this a regression?

Not that i know of.

### Description

`<div class="color-preview" [ngStyle]="{'box-shadow':'0 3px 6px -2px rgba(107, 13, 13, 0.4)'}"></div>`
`<div class="color-preview" [style.box-shadow]="'0 3px 6px -2px rgba(107, 13, 13, 0.4)'"></div>`

The first one works, the second one doesn't.

Also, when using a hexadecimal value instead of rgb the value gets converted to rgb.

## 🔬 Minimal Reproduction
https://angular-semvys.stackblitz.io/

## 🌍  Your Environment

**Angular Version:**
<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 7.0.1
Node: 8.11.2
OS: darwin x64
Angular: 7.0.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... http, language-service, material, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.10.1
@angular-devkit/build-angular     0.10.1
@angular-devkit/build-optimizer   0.10.1
@angular-devkit/build-webpack     0.10.1
@angular-devkit/core              7.0.1
@angular-devkit/schematics        7.0.1
@angular/cli                      7.0.1
@angular/flex-layout              7.0.0-beta.19
@ngtools/webpack                  7.0.1
@schematics/angular               7.0.1
@schematics/update                0.10.1
rxjs                              6.3.3
typescript                        3.1.3
webpack                           4.19.1
</code></pre>

**Comment by alimemonzx** [comment] 2018-11-10 20:04
@Smiley01987  I am also getting the same issue. But you can use hexadecimal value in [style.box-shadow]. 

As well as I have also tried it in different way which is working perfect. I have passed a function in `[style.box-shadow]="rgbaToHex(107, 13, 13)"`

It takes 3 values of rgb color and convert it into a hexadecimal value which gets bind with style attribute.

Here is the function

```
returnHex(rgb) {
    let hex = Number(rgb).toString(16);
    if (hex.length < 2) {
      hex = "0" + hex;
    }
    return hex;
  }

  rgbTOHex(r, g, b) {
    let red = this.returnHex(r);
    let green = this.returnHex(g);
    let blue = this.returnHex(b);
    return "#"+red + green + blue + " 1px 5px";
  }
```

**Comment by trotyl** [comment] 2018-11-17 06:11
Duplicate of https://github.com/angular/angular/issues/21691.

---

It's `[ngStyle]` who has incorrect behavior in ignoring the sanitization process, which cause the inconsistency.

The unsafe criteria for style values is a different issue linked above.

**Closed** 2018-11-29 23:57 UTC
Labels: comp: core & compiler
