### ISSUE TITLE
Error with <ng-content> or why it does not work?

### ISSUE THREAD

**Issue by KorsaR-ZN** [angular/angular#7384] opened 2016-03-02 21:30 UTC
Hi, please help me understand why this component is not working as intended?
Of the two use cases is working only case 2...

## Source
**component**
```typescript
import {Component, Input} from 'angular2/core';

@Component({
    selector: 'c12-viewport-footer',
    templateUrl: 'viewport-footer.html'
})
export class ViewportFooterComponent {
   @Input()
   button: boolean = false;
}
```

**view**
```html
<div class="c12-viewport__footer" [ngClass]="{'c12-viewport__footer--button': button}">
    <template [ngIf]="!button">
        <ng-content></ng-content>
    </template>
   <template [ngIf]="button">
      <button class="...">
         <ng-content></ng-content>
      </button>
    </template>
</div>
```
## Example use
**Case 1**
```html
<c12-viewport>
   ...
   <c12-viewport-footer>
      SOME_HTML_CONTENT
   </c12-viewport-footer>
<c12-viewport>
```

**Case 2**
```html
<c12-viewport>
   ...
   <c12-viewport-footer [button]="true">
      SOME_TEXT_CONTENT
   </c12-viewport-footer>
<c12-viewport>
```

**Comment by jpsfs** [comment] 2016-03-02 22:04
Hi!

I've had the same problem. It appears the content is always put on the first ng-content element, despite the *ngIf directive.

Not sure if it's the intended behavior or bug. Maybe someone from the team will be able to answer.

Regards,

**Comment by ericmartinezr** [comment] 2016-03-02 22:08
@jpsfs you're right, it's by desing, see https://github.com/angular/angular/issues/4631

**Comment by jpsfs** [comment] 2016-03-02 22:14
Hi @ericmartinezr,

Thank you for the link. Not sure if I agree in this case, I understand the technical solution and why it was implemented this way but it's not the more natural approach IMHO.

**Comment by KorsaR-ZN** [comment] 2016-03-02 22:26
@ericmartinezr Thank you. 
Are there any other ways that it is achieved in the desired behavior?

**Comment by iignatov** [comment] 2016-04-23 11:51
I think that this is similar/related to #7795 and was confirmed as [a valid bug](https://github.com/angular/angular/issues/7795#issuecomment-202492709).

**Comment by pkozlowski-opensource** [comment] 2016-06-16 08:11
This is duplicate of # #7795

**Closed by pkozlowski-opensource** 2016-06-16 08:11 UTC
