### ISSUE TITLE
@HostBinding and @Component({ host: { } }) have different behavior

### ISSUE THREAD

**Issue by MaKCbIMKo** [angular/angular#26251] opened 2018-10-04 14:31 UTC
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
`@HostBinding('class')` decorator replaces all other css classes. But `host` object in `@Component\@Directive` decorators append css classes instead.

## Expected behavior
`@HostBinding` behaves the same way as `host` object - appends css classes, but not replaces.

## Minimal reproduction of the problem with instructions
component.ts
```
@Component({
    selector: 'my-component',
    template: '<span>my component</span>'
})
class MyComponent {
    @HostBinding('class') public myClasses = 'my-internal-class';
}
```

index.html
```
<my-component class="my-external-class"></my-component>
```

as a result - component will have only 'my-internal-class'

## What is the motivation / use case for changing the behavior?
[Angular style guide](https://angular.io/guide/styleguide#style-06-03) and [Angular Material style guide](https://github.com/angular/material2/blob/master/CODING_STANDARDS.md) suggest using different approaches. And that's fine. But I would like to have linter to push me using only one approach. But having different behavior makes that impossible. (Moreover, lack of documentation doesn't help in that case)

## Environment

<pre><code>
Angular version: 6.0.3

Browser:
- [x] Chrome (desktop) version 67
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by trotyl** [comment] 2018-10-04 14:45
Same behavior for `host`, no difference: https://stackblitz.com/edit/angular-jthb58?file=src%2Fapp%2Fhello.component.ts

Only have `my-internal-class` is the expected behavior in this case, already explained in [class binding](https://angular.io/guide/template-syntax#class-binding) section:

> **this is an all-or-nothing, replacement binding.**
> `<!-- reset/override all class names with a binding  -->`
> `<div class="bad curly special"`
> `    [class]="badCurly">Bad curly</div>`

**Comment by MaKCbIMKo** [comment] 2018-10-04 14:50
But what if I will replace 
```
'[class]': `'my-internal-class'`
``` 
with 
```
'class': 'my-internal-class'
```

it will add both classes.

Is that possible to achieve that with `@HostBinding`?

**Comment by trotyl** [comment] 2018-10-04 14:59
Allowing `'class': 'my-internal-class'` is a legacy mistake, should not be used in any case.

**Comment by dawidgarus** [comment] 2018-10-04 14:59
@MaKCbIMKo you can do `@HostBinding('class.my-internal-class') myInternalClass: boolean = true`

**Comment by MaKCbIMKo** [comment] 2018-10-04 15:04
> Allowing non-binding non-event property like `'class': 'my-internal-class'` is a legacy mistake, should not be used in any case.

Ok, will try to avoid that.

> @MaKCbIMKo you can do `@HostBinding('class.my-internal-class') myInternalClass: boolean = true`

That will work, agreed. But in my case I need to apply css class with name that depends on component inputs. And I can't do that by `@HostBinding` w/o replacing other classes.

**Comment by trotyl** [comment] 2018-10-04 15:13
It's a open feature request at https://github.com/angular/angular/issues/7289

**Comment by pkozlowski-opensource** [comment] 2018-10-04 15:14
Yes, this is a duplicate of #7289, thnx @trotyl

**Closed by pkozlowski-opensource** 2018-10-04 15:14 UTC
