### ISSUE TITLE
ServiceWorker never installs if a timer is running

### ISSUE THREAD

**Issue by CarstenLeue** [angular/angular#25402] opened 2018-08-09 10:52 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
When registering a service worker via     ServiceWorkerModule.register('/ngsw-worker.js') it turns out that this worker will only be registered once the application is considered "stable".
This in turn is determined by checking if there are outstanding macro- or microtasks.

If the application e.g. uses a interval timer (e.g. to periodically refresh itself), then the service worker will never be registered, because the application never reaches its stable state.

## Expected behavior
I would expect that it is supported to use timers and intervals in the application and that these do NOT cause a service worker from not being registered.

## Minimal reproduction of the problem with instructions

Use an empty angular app, add service worker support via `ng add @angular/pwd` and start a timer in the constructor of your module. As a result the service worker will never be registered.

## Environment

<pre><code>
Angular version: 6.1.2

**Comment by gkalpak** [comment] 2018-08-12 13:52
Duplicate of #20970.

**Closed by gkalpak** 2018-08-12 13:52 UTC
Labels: comp: service-worker
