### ISSUE TITLE
required atteibute is mising from FormBuilder's Validators.required

### ISSUE THREAD

**Issue by vendelin8** [angular/angular#12134] opened 2016-10-06 22:14 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When using FormBuilder, FormGroup, FormControl, and Validators.required, the "required" and "ng-reflect-required" attributes are missing from the input. After [this guide](https://angular.io/docs/ts/latest/guide/forms.html):
I use
```
.ng-valid[required], .ng-valid.required  {
    ...
}
```
for signing inputs that are OK or erroneous. It sounds wrong to maintain validators in two different places.

**Expected behavior**
When Validators.required is added to the FormControl's synchronous validators, the .ng-valid[required] or .ng-valid.required should fire.

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/dQTANsTnaFbwXXjC35gD?p=info

**What is the motivation / use case for changing the behavior?**
It sounds wrong to maintain validators in two different places, but having such a CSS selector is nice to have.

**Please tell us about your environment:**
Arch Linux i686, Apache

* **Angular version:** 2.0.0

* **Browser:** [all | Chrome XX | Firefox XX]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =   v6.7.0

**Comment by manklu** [comment] 2016-10-07 06:24
see #8175

**Comment by pkozlowski-opensource** [comment] 2016-10-07 07:38
Yep, this is duplicate of #8175, thnx @manklu

**Closed by pkozlowski-opensource** 2016-10-07 07:38 UTC
