### ISSUE TITLE
Wrong warning about not animatable properties

### ISSUE THREAD

**Issue by daniel-sc** [angular/angular#57140] opened 2024-07-26 09:05 UTC
### Which @angular/* package(s) are the source of the bug?

animations

### Is this a regression?

Yes

### Description

In some situations, using an non-animatable property in a transition within a non-animated "style" step shows a (wrong) developer warning. See reproduction.

```ts
trigger('animationHeightInOutSymmetric', [
      transition(':enter', [
        style({height: 0, overflow: 'hidden'}),
        animate(`300ms ease-in-out`, style({height: '*'})),
        style({overflow: '*'})
      ])
    ])
```

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-wlp1y6?file=src%2Fmain.ts

### Please provide the exception or error you saw

```true
Warning: The animation trigger "animationHeightInOutSymmetric" is attempting to animate the following not animatable properties: overflow
(to check the list of all animatable properties visit https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_animated_properties)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 18.1.1
Node: 20.12.0
Package Manager: npm 10.5.0
OS: win32 x64

Angular: 18.1.1
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, localize, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1801.1
@angular-devkit/build-angular   18.1.1
@angular-devkit/core            18.1.1
@angular-devkit/schematics      18.1.1
@schematics/angular             18.1.1
rxjs                            7.8.1
typescript                      5.5.3
zone.js                         0.14.8
```

### Anything else?

Might be related to https://github.com/angular/angular/issues/46602 and https://github.com/angular/angular/issues/48571

**Comment by JoostK** [comment] 2024-07-26 09:23
This is a duplicate of #46928

**Closed by JoostK** 2024-07-26 09:23 UTC
