### ISSUE TITLE
i18n select-ICU generates two units in xlf

### ISSUE THREAD

**Issue by minomikula** [angular/angular#25858] opened 2018-09-07 12:05 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

`ng xi18n` creates two units for select-icu expression. Given html template:
```
              <span i18n="@@testLabel">
                {variable, select, aLabel {Label for A}}
              </span>
```
`ng xi18n --i18n-format=xlf` creates:
```
      <trans-unit id="testLabel" datatype="html">
        <source>
                <x id="ICU" equiv-text="{variable, select, aLabel {...}}"/>
              </source>
        <context-group purpose="location">
          <context context-type="sourcefile">app/shared/statistics/statistics.component.html</context>
          <context context-type="linenumber">23</context>
        </context-group>
      </trans-unit>
      <trans-unit id="b4645e675b21d80d80ff7669e6c6ac8a84bab9cd" datatype="html">
        <source>{VAR_SELECT, select, aLabel {Label for A} }</source>
        <context-group purpose="location">
          <context context-type="sourcefile">app/shared/statistics/statistics.component.html</context>
          <context context-type="linenumber">24</context>
        </context-group>
      </trans-unit>
```
also
`ng xi18n --i18n-format=xlf2` creates:
```
    <unit id="testLabel">
      <notes>
        <note category="location">app/shared/statistics/statistics.component.html:23,25</note>
      </notes>
      <segment>
        <source>
                <ph id="0" equiv="ICU" disp="{variable, select, aLabel {...}}"/>
              </source>
      </segment>
    </unit>
    <unit id="5433920347450028630">
      <notes>
        <note category="location">app/shared/statistics/statistics.component.html:24</note>
      </notes>
      <segment>
        <source>{VAR_SELECT, select, aLabel {Label for A} }</source>
      </segment>
    </unit>
```
First unit has correct id but sourse doesnt contain test to translate and (i think) is useless. Second unit has correct text, but id is generated.
## Expected behavior

`ng xi18n` would create only one unit with correct id and source containing text to translate. like:
```
    <unit id="testLabel">
      <notes>
        <note category="location">app/shared/statistics/statistics.component.html:24</note>
      </notes>
      <segment>
        <source>{VAR_SELECT, select, aLabel {Label for A} }</source>
      </segment>
    </unit>
```

## What is the motivation / use case for changing the behavior?

First unit doesn't contain text to translate, therefore it leads to confusion for translator.

## Environment

<pre><code>
ng -v

Angular CLI: 6.1.5
Node: 10.5.0
OS: win32 x64
Angular: 6.1.6

Angular version: 6.1.6

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by ocombe** [comment] 2018-09-11 08:28
It's because the compiler will extract the ICU expression separately.
With ivy we will have a new approach where the ICU expression stays in the main extracted message

**Comment by AndrewKushnir** [comment] 2020-10-12 18:06
Just wanted to mention that in Ivy the extraction mechanism remains the same and an ICU is extracted into a separate message. This behavior was retained to make Ivy more backwards compatible.

**Comment by DerZyklop** [comment] 2020-11-03 15:56
@ocombe @AndrewKushnir there is a consequential problem based on this behaviour. 
FYI: https://github.com/angular/angular/issues/39551

**Comment by AndrewKushnir** [comment] 2021-06-04 23:43
FYI, closing this ticket as a duplicate of #39551.

**Closed by AndrewKushnir** 2021-06-04 23:43 UTC
Labels: comp: i18n, feature, in backlog
