### ISSUE TITLE
Hydration issues when a component with and without ngSkipHydration are present in a template

### ISSUE THREAD

**Issue by leo6104** [angular/angular#49929] opened 2023-04-19 10:19 UTC
### Which @angular/* package(s) are the source of the bug?

platform-server

### Is this a regression?

No

### Description

It seems server-side rendered html not removed and just put client-side rendered html at the same position. 

It doesn't show any hydration error and just duplicate rendering. 

In PC project,
<img src="https://user-images.githubusercontent.com/7777929/233043151-02287c7a-e389-45a6-b12b-574a36b37734.png" width=200> 
In captured image, above one is server-side rendered html and below one is client-side rendered html. 

- use `ngSwitch + ngSwitchCase + ngSwitchDefault` directive
- node tree: `ng-container` > 2 parallel `ng-container + ngIf` > `dozen of small components`
- partially use `ng-template` with `if - else ng-container`
- list item for loop : `ngFor` + `trackBy` + `let i = index`

In Mobile project,
<img src="https://user-images.githubusercontent.com/7777929/233044109-bee75103-1c38-4f10-8bdb-98716edb8336.png" width=200> 
In captured image, left one is server-side rendered html and right is client-side rendered html. 

- not use `ngSwitch` related syntax
- node tree: `ng-container` > div > `ng-container` > `a tag with directive component` > 6 parallel ng-container > small components & div markup 
- list item for loop : `ngFor` + `trackBy` + `let i = index`

IF someone can give us similar cases or hints for reproduction, please give the information. 

### Please provide a link to a minimal reproduction of the bug

Please wait for moment. i'm trying to reproduce it. it has no hydration error and two markup condition is quite complex. Its components consist of 20+ small-size components so its complexity is quite larger than other hydration error case. 

### Please provide the exception or error you saw

```true
No error message in console & our unit test codes.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 16.0.0-rc.0
Node: 16.19.0
Package Manager: npm 8.19.3
OS: darwin x64

Angular: 16.1.0-next.0+sha-d8e16ec
... core

Package                             Version
-------------------------------------------------------------
@angular-devkit/architect           0.1600.0-rc.0
@angular-devkit/build-angular       16.0.0-rc.0
@angular-devkit/core                16.0.0-rc.0 (custom builds - fixed #49918 
@angular-devkit/schematics          16.0.0-rc.0
@angular/animations                 16.0.0-rc.1
@angular/bazel                      15.2.6
@angular/cdk                        16.0.0-rc.0
@angular/cli                        16.0.0-rc.0
@angular/common                     16.0.0-rc.1
@angular/compiler                   16.0.0-rc.1
@angular/compiler-cli               16.0.0-rc.1
@angular/elements                   16.0.0-rc.1
@angular/forms                      16.0.0-rc.1
@angular/localize                   16.0.0-rc.1
@angular/material                   16.0.0-rc.0
@angular/platform-browser           16.0.0-rc.1
@angular/platform-browser-dynamic   16.0.0-rc.1
@angular/platform-server            16.0.0-rc.1
@angular/router                     16.0.0-rc.1
@angular/service-worker             16.0.0-rc.1
@angular/youtube-player             16.0.0-next.2
@nguniversal/builders               16.0.0-next.0
@nguniversal/common                 16.0.0-next.0
@nguniversal/express-engine         16.0.0-next.0
@schematics/angular                 16.0.0-rc.0
ng-packagr                          16.0.0-rc.0
rxjs                                7.8.0
typescript                          5.0.3
```

### Anything else?

We didn't use `ngSkipHydration` directive in above two components case.

**Comment by jessicajaniuk** [comment] 2023-04-19 14:10
@leo6104 Thanks for reporting this. Can you provide us with a reproduction? You don't have to use your exact components, but we won't be able to troubleshoot without a runnable reproduction.

**Comment by leo6104** [comment] 2023-04-19 17:43
@AndrewKushnir @jessicajaniuk Summarizing the error situation like above comment is all i can do in today. It include callstack & gist code. Even though it would be best to have reproduction repo, it failed on today. I will do more investigation until this Friday and leave a comment again. 

The point of strange things in server rendered html.
- `test` text render first and `<!---->` 4 times => text node rendering position is strange. expected: `<!----><!---->test<!----><!---->` 

Hope these error reporting could be helpful to find the root cause. 😅

**Comment by AndrewKushnir** [comment] 2023-04-19 20:34
@leo6104 thanks for additional information 👍 As you mentioned, having a repro would be great, so that we can investigate further.

Quick question based on the information that you've shared: what happens if you remove `ngSkipHydration` from the `< sticky-purchase-sidebar>` component [here](https://gist.github.com/leo6104/dc65a3ced62f9366c4d53ef085519ccc#file-sheet-detail-html-L28) (or remove that component from the template)?

**Comment by AndrewKushnir** [comment] 2023-04-20 02:07
@leo6104 we've put together a PR with a fix for an issue where a presence of the same component in a template with and without hydration causes unexpected behavior, see https://github.com/angular/angular/pull/49943. This is the pattern that we've noticed in a template that you've shared. We were wondering if you could try testing your app with the following version of the `@angular/core` package and let us know if it improved the situation?

Here is an update for the `package.json` file (please run `npm install --force`):
```
...
"@angular/core": "https://output.circle-artifacts.com/output/job/87ebbc1d-88e4-477e-9c7b-f654c5c9676d/artifacts/0/angular/core-pr49943-7ba01b4ccf.tgz"
...
```

Thank you.

**Comment by leo6104** [comment] 2023-04-20 02:08
When i wrote test code like this, it raise error. and when i remove ngSkipHydration, no error. 

```
  fit('should pass `sticky-purchase-sidebar` tag', async () => {
    @Component({
      standalone: true,
      selector: 'app',
      template: `
        <sticky-purchase-sidebar
          ngSkipHydration
          [sheet]="_sheet"
          [loading]="false" />
        <sticky-purchase-sidebar
          [sheet]="_sheet"
          [loading]="false" />
      `,
      imports: [
        CommonModule,
        SyntaxSharedModule,
        HttpClientModule,
        StickyPurchaseSidebarComponent,
      ],
      providers: [
        provideHydrationMocks(),
      ],
    })
    class SimpleComponent {
      _sheet = _sheetStub;
    }

    const { verifyHydrate } = await assertionsForHydration(SimpleComponent, []);
    expect(verifyHydrate).not.toThrow();
  });
```

**Comment by leo6104** [comment] 2023-04-20 02:53
@AndrewKushnir  It works!!! 🙏 I really appreciate for helping us.

It was the last/most critical hydration problem we found in our projects. 🚀

**Comment by leo6104** [comment] 2023-04-20 03:25
I will back into the work increasing test coverage for hydration. We already build 40+ test cases for our core business components and it quite clean and easy to test. 

With enough QA testing & test code, we have a plan to deploy its hydration feature to production service (1 millions MAU service) in next week. After that, i will share the hydration testing util we built and explain about what advantages if testing util provided.

**Comment by AndrewKushnir** [comment] 2023-04-20 03:45
@leo6104 thanks a lot for verifying the fix! 👍 

> It works!!! 🙏 I really appreciate for helping us.
> It was the last/most critical hydration problem we found in our projects. 🚀

Huge thanks to you for great repros that you've provided in this and previous tickets. That helped a lot to locate problems and come up with fixes.

> With enough QA testing & test code, we have a plan to deploy its hydration feature to production service (1 millions MAU service) in next week.

Thanks for the update! If you're ok to share, we'll be curious to know how Core Web Vitals and other key performance metrics change once you enable hydration. If the website is publicly available, you could run a test via [WebPageTest](https://www.webpagetest.org/) on production website before and after enabling hydration.

> After that, i will share the hydration testing util we built and explain about what advantages if testing util provided.

That'd be great if you could create a feature request in the issue tracker and describe the testing utility APIs that would be helpful for your scenarios. We'll be collecting more feedback from the community and it would help us to prioritize the work.

**Comment by AndrewKushnir** [comment] 2023-04-21 23:26
Closing this ticket, since the corresponding PR was merged and will be released next week as a part of the pre-release version of Angular v16.

**Closed by AndrewKushnir** 2023-04-21 23:26 UTC
Labels: area: core, state: has PR, P3, core: hydration
