### ISSUE TITLE
Router: crashes if first nav command is a params object

### ISSUE THREAD

**Issue by dbandstra** [angular/angular#10170] opened 2016-07-19 22:31 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

I want to reload the current route with different route params, using a relative navigation path. Something like this:

```typescript
this.router.navigate([{'some_param': 'value'}], {relativeTo: this.route});
```

Problem: There's code in the `createNewSegment` function (`@angular/router/src/create_url_tree.ts`) which seems to allow the first element in the command array to be a params object (in which case it should apply to the current innermost route), but it crashes. `startIndex` argument seems to point to the end of `segment`, thus `segment.pathsWithParams[startIndex]` (line 241, currently) is undefined.

I don't know if the `relativeTo` navigation extra is intended to be required for this to work. It seems to crash if you specify it. If you don't specify `relativeTo`, it crashes only if you're in a nested route. See my plunker demo.

**Reproduction of the problem**
http://plnkr.co/edit/7IFbHZOo0sNXMoCtNDrj?p=preview

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.3
router 3.0.0-alpha.8
 
* **Browser:** Chrome

**Comment by brandonroberts** [comment] 2016-07-20 15:32
Dupe of https://github.com/angular/angular/issues/10054

**Closed** 2016-10-04 22:41 UTC
Labels: comp: router
