### ISSUE TITLE
Pages not loading at first attempt when accessed from a link

### ISSUE THREAD

**Issue by moniuch** [angular/angular#43467] opened 2021-09-15 19:57 UTC
### Description

This is a problem that occurs intermittently when opening docs from a link (such as from Google search results).
The progress bar loads for ever, the top menu load, but the page contents does not.
Hard reload of the page always works.

I have seen this problem many times, including RxJS site too, e.g. https://rxjs.dev/api/operators/... 

Sorry if I am misplacing the ticket in a wrong project, not sure whether it belongs to material or angular (`aio` prefix).

### What is the affected URL?

many

### Please provide the steps to reproduce the issue

Reproducible <100% when clicking a URL in Google's SERP.

### Please provide a screenshot if possible

Attached is an example of accessing ContentChild docs, fresh off the press
Note `<aio-doc-viewer>` element empty

![image](https://user-images.githubusercontent.com/681956/133499599-8f5d2038-6304-4a35-9461-6543518098ba.png)

![image](https://user-images.githubusercontent.com/681956/133499799-b8ab2de2-f232-44ec-b4a6-3d0819e42283.png)

**Comment by petebacondarwin** [comment] 2021-09-15 20:12
Thanks for reporting this @moniuch - and providing the screenshots.
I am confident that it is a duplicate of https://github.com/angular/angular/issues/28114.

**Comment by moniuch** [comment] 2021-09-15 20:15
@petebacondarwin Could be - you know better than I do. One of the screenshots indeed seems to be exactly the same. Feel free to link or close the ticket! Have a great day!

**Comment by petebacondarwin** [comment] 2021-09-15 20:19
Thanks - closing as a duplicate.
The good news is that after some years of struggling with this problem, we think that @gkalpak has finally come up with a reason for it happening and a potential solution. Watch #28114 for more info.

**Closed by petebacondarwin** 2021-09-15 20:19 UTC
