### ISSUE TITLE
https://angular.dev/api/localize/init/$localize

### ISSUE THREAD

**Issue by qq1978** [angular/angular#56356] opened 2024-06-10 07:15 UTC
### Describe the problem that you experienced

https://angular.dev/api/localize/init/$localize is not accessible

### Enter the URL of the topic with the problem

https://angular.dev/api/localize/init/$localize

**Comment by JoostK** [comment] 2024-06-10 07:35
Duplicate of #54388

**Closed by JoostK** 2024-06-10 07:35 UTC
