### ISSUE TITLE
Typo in the word "standalone" in the tutorial on "Create a pipe" step

### ISSUE THREAD

**Issue by splincool** [angular/angular#53684] opened 2023-12-22 10:56 UTC
### Describe the problem that you experienced

I have found a typo in the word "standalone" in the tutorial on the "Create a pipe" step.

Now it's 'standaone'

### Enter the URL of the topic with the problem

https://angular.dev/tutorials/learn-angular/create-a-pipe

### Add a screenshot if that helps illustrate the problem

![angular typo](https://github.com/angular/angular/assets/8850606/d903366b-6aa0-4097-b29d-b786011c4a25)

**Comment by JoostK** [comment] 2023-12-22 11:01
Thanks for the report, this is a duplicate of https://github.com/angular/angular/pull/52602 and is pending deployment.

**Closed by JoostK** 2023-12-22 11:01 UTC
