### ISSUE TITLE
Changing "const" value in Angular 2 does not give error

### ISSUE THREAD

**Issue by Hongbo-Miao** [angular/angular#8180] opened 2016-04-22 01:33 UTC
The code is simple:

    const num = 1;
    num = 2;
    console.log('num', num);

In [JSFiddle](https://jsfiddle.net/Hongbo_Miao/ofhs7jw3/), the browser console will show the following error, which is great:

> Uncaught TypeError: Assignment to constant variable.

However, the same codes in Angular 2 does not give any error, and at the end `num` equals **2**. See this [Plunker](http://plnkr.co/edit/yRAgiV0rPZTsJhe5YYbF?p=preview).

**Comment by MarkPieszak** [comment] 2016-04-22 01:43
I think this might be a plunker issue. Also Typescript is the compiler that handles those types of issues, not Angular.

**Comment by ericmartinezr** [comment] 2016-04-22 01:51
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/const
>The value of a constant cannot change through re-assignment, and it can't be redeclared.

The problem is not the fiddle, you can replicate the same error opening your console and writing
>const a = 1; a = 2;

It will throw the error above. You don't see the same error with typescript (the plnkr) because it gets transpiled to 

```
var num = 1;
num = 2;
console.log('num', num);
```

This is not related to angular2 at all, this is a general javascript question. See https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

**Comment by Hongbo-Miao** [comment] 2016-04-22 01:54
@ericmartinezr is there a way to let Angular 2 app show the error if I change a const value? Thansk

**Comment by ericmartinezr** [comment] 2016-04-22 02:03
@Hongbo-Miao I don't know really. I know you can transpile to es6, but that requires babel and other stuff that I've never tried before =/. I'm not aware that you can transpile to full es6 nowadays.

You can try in in TypeScript's gitter chatroom https://gitter.im/Microsoft/TypeScript since this is a transpilation thing and not angular2's.

**Comment by zoechi** [comment] 2016-04-22 07:42
http://stackoverflow.com/questions/36783014/why-changing-const-value-in-angular-2-does-not-give-error

This doesn't seem to be related to Angular. Looks more like a pure TypeScript issue. I think you should close the issue here and continue on SO.

**Comment by robwormald** [comment] 2016-04-22 09:53
plunker doesn't do actual typechecking of Typescript code, it only transpiles it. This isn't related to angular, and you'll find that in a proper typescript environment this does indeed error.
<img width="512" alt="screen shot 2016-04-22 at 2 53 18 am" src="https://cloud.githubusercontent.com/assets/534930/14738251/68f9a474-0835-11e6-971a-db934970e7b3.png">

**Closed by robwormald** 2016-04-22 09:53 UTC

**Comment by pkozlowski-opensource** [comment] 2016-04-22 09:56
> plunker doesn't do actual typechecking of Typescript code, it only transpiles it

@robwormald shouldn't we configure on-line TS transpiler to "fail hard" on transpilation errors? I must say that that not clearly seeing TS compilation errors results in some head-scratching from time to time.

**Comment by robwormald** [comment] 2016-04-22 10:02
@pkozlowski-opensource I don't believe the current System loader allows for it, since it's purely using the non-typechecked ts.transpile(string) API. The upcoming version switches to using the new plugin-TS loader which does, but then we'll run into a whole new set of fun with typings... I'll look into it

**Comment by MarkPieszak** [comment] 2016-04-22 13:20
You're using vs-Code I see @robwormald ? 
Seems to have the best TS compiler at the moment. Love that editor so far.
If only they had ways to debug webpack'd TS on there now lol

**Comment by Hongbo-Miao** [comment] 2016-04-22 15:28
Thanks for help, everyone!
