### ISSUE TITLE
buggy behaviour for non bound "attr.xxx-non-native"

### ISSUE THREAD

**Issue by tiagoroldao** [angular/angular#12016] opened 2016-09-30 17:05 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 
When using the attribute binding (attr.xxx), no error is thrown but the attribut is badly parsed

As expected: `<a [attr.test-id]="'my-test-id'"></a>` => `<a test-id="my-test-id"></a>`
Not as expected: `<a attr.test-id="my-test-id"></a>` => `<a attr.test-id="my-test-id"></a>`

**Expected behavior**
Both examples should yield the same result:
`<a [attr.test-id]="'my-test-id'"></a>` => `<a test-id="my-test-id"></a>`
`<a attr.test-id="my-test-id"></a>` => `<a test-id="my-test-id"></a>`

Or the latter should be considered incorrect usage. I believe this second usage was at least at some point valid.

(of course, this is relevant because using `<el test-id="my-test-id"/>` with non native, non bound properties is not allowed)

**Reproduction of the problem**
http://plnkr.co/edit/ktOfndION5KQr3aCUcWy?p=preview

**What is the motivation / use case for changing the behavior?**
Clear behaviour important for users searching how to approach this
Bind-less option terser, and oftentimes binding isn't necessary

**Please tell us about your environment:**
OSX

* **Angular version:** 2.0.0

* **Browser:** Chrome  

 
* **Language:** TypeScript 2.0

**Comment by DzmitryShylovich** [comment] 2016-09-30 17:29
Works as expected. Read the difference between property binding and attributes.

**Comment by tiagoroldao** [comment] 2016-09-30 17:35
The expected behaviour is actually how it used to work a few RC's ago. 
An example of how this was the norm is here => https://groups.google.com/forum/#!topic/angular/nfsIy3cU1MU 

I understand if the `<a attr.test-id="my-test-id"></a>` is to be disallowed, but at the moment it throws no error and fails silently.

**Comment by pkozlowski-opensource** [comment] 2016-09-30 17:41
> Works as expected. Read the difference between property binding and attributes.

It is kind of borderline since `attr.test-id` is not a real property but rather ng-specific binding syntax. Regardless, it does indeed work as intended, thnx @DzmitryShylovich 

For reference: https://angular.io/docs/ts/latest/guide/template-syntax.html#!#other-bindings

 > I understand if the <a attr.test-id="my-test-id"></a> is to be disallowed, but at the moment it throws no error and fails silently.

Currently we don't throw for any invalid / non-existing attributes (ex. `<div fooo="bar">` won't throw either but `fooo` is clearly an invalid attribute name). We should do better in #3425 (re-opened it as it was closed by accident).

You can add your use-case to #3425

**Closed by pkozlowski-opensource** 2016-09-30 17:41 UTC
