### ISSUE TITLE
IE11 Polyfills Issue - SCRIPT1002: Syntax error main.bundle.js

### ISSUE THREAD

**Issue by danail-vasilev** [angular/angular#21202] opened 2017-12-28 20:30 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I cannot open the project in IE11. The following error is thrown - SCRIPT1002: Syntax error main.bundle.js

I have done the following steps after investigating the issue a couple of hours:
1. Enabled polyfills
2. Added shims to index.html - https://npmcdn.com/angular2/es6/dev/src/testing/shims_for_IE.js
3. Set __Zone_enable_cross_context_check property to true in index.html file.
4. Set es5 in tsconfig files.

## Minimal reproduction of the problem with instructions

A fully runnable sample is available here - https://github.com/danail-vasilev/test-ng2-ie11
Just clone the repo and run:
npm install
npm start

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [x] IE version 11
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by chuckjaz** [comment] 2018-01-04 23:35
1. The shim file you are using is from a deprecated package which was deprecated early in the development of Angular.
2. There is no reason you need to use this as the shims for IE 10 and 11 are enabled in you project.
3. The error is a script parse error which shouldn't be the same in every browser not just in IE 11

Can you try reproducing this without including the out-of-date and deprecated shim?

**Comment by danail-vasilev** [comment] 2018-01-05 00:49
Hi chuckjaz,
Thank you for your reply! I was reproducing the issue before using these shims. This is the issue log of main.bundle.js file - https://www.screencast.com/t/bXcMNHCe8

**Comment by chuckjaz** [comment] 2018-01-05 19:12
I could not reproduce the issue given the repository because it gives me the error:

```
ERROR in ./node_modules/css-loader?{"sourceMap":false,"importLoaders":1}!./node_modules/postcss-loader?{"ident":"postcss"}!./node_modules/bootstrap/dist/css/bootstrap.min.css
Module build failed: BrowserslistError: Unknown browser major
```

I compiled the example directly with `ngc` using:

```
./node_modules/.bin/ngc -p src/tsconfig.app.json 
```

This emits:

```ts
import { NgModule } from '@angular/core';
import { RouterModule } from '@angular/router';
export var routes = [
    { path: '', redirectTo: '/', pathMatch: 'full' },
    { path: '**', redirectTo: '' }
];
var AppRoutingModule = /** @class */ (function () {
    function AppRoutingModule() {
    }
    AppRoutingModule.decorators = [
        { type: NgModule, args: [{
                    imports: [RouterModule.forRoot(routes)],
                    exports: [RouterModule]
                },] },
    ];
    /** @nocollapse */
    AppRoutingModule.ctorParameters = function () { return []; };
    return AppRoutingModule;
}());
export { AppRoutingModule };
//# sourceMappingURL=app-routing.module.js.map
```

which does not contain the `let` or `class` references.

From this it looks like an issue in the angular cli or one of its delegated tools, not ngc or TypeScript.. Can you report this to https://github.com/angular/angular-cli?

**Comment by mhevery** [comment] 2018-01-09 23:20
closing as not reproducible.

**Comment by danail-vasilev** [comment] 2018-01-25 16:45
Hi Guys,
The issue is still reproducible ! Please find my comments and a fully runnable sample that showcases the problem below.

1. The compiler error reproduced by chuckjaz is caused by an issue with the [cli and bootstrap 4.0.0](https://github.com/tomek199/elo-rating/commit/13f5c0c52838f3665ad0f928e13b91cf9e813d9d). More information is also available [here](https://github.com/angular/angular-cli/issues/9020).
1. I have also updated this package's version swimlane/ngx-datatable": "^11.1.7"
1. To reproduce the issue you should also change "target": "es5" to "target": "es6" in tsconfig.json, tsconfig.app.json and tsconfig.spec.json files.
1. A new fully runnable sample that reproduces the issue is available in this repo - [test-ng2-ie11-v2](https://github.com/danail-vasilev/test-ng2-ie11-v2)
1. If I use "target": "es5" the issue is resolved but I get the following issue with this code ([snapshot](https://www.screencast.com/t/92ryVLUdC6NC)):

> Type 'Map<string, boolean>' is not an array type or a string type.

`export function toggleBoolProperty(map: Map<string, boolean>) {
    for (const [key, value] of map) {
        this[key] = value;
    }
}`

So, can we make this project working with target es6 in IE11 ?

Thank you for your time and efforts !

**Comment by danail-vasilev** [comment] 2018-01-25 16:58
Also I got this error ([image](https://www.screencast.com/t/nFJeGkeKNprg)) in IE11:

> SCRIPT5011: Can't execute code from a freed script

Although I have added the following code, suggested by your team to the polyfills.ts file:
`(window as any).__Zone_enable_cross_context_check = true;
import 'zone.js/dist/zone';  // Included with Angular CLI.`

**Comment by trotyl** [comment] 2018-01-26 02:46
> If I use "target": "es5" the issue is resolved but I get the following issue with this code 

[`--downlevelIteration` flag](http://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-3.html#new---downleveliteration) is required for using `for...of` against non-array iterables.

**Comment by JiaLiPassion** [comment] 2018-01-26 07:48
@danail-vasilev , to work in IE11, you need to build with `es5` target. And I run your sample , with `es5` target, everything work fine.

**Comment by danail-vasilev** [comment] 2018-01-26 08:11
Thank you guys !

1. Ok, I will set the target to es5, however, is there any documentation or a note to use es5 target for IE 11 ? Can you add this information to the polyfills.ts file because it is related to IE 11 as well ?
1. Regarding `for..of`, I can use the downlevelIteration flag or foreach - `map.forEach((value: boolean, key: string) => { this[key] = value; });`
1. And regarding the `SCRIPT5011: Can't execute code from a freed script` issue, why the fix/workaround doesn't take effect ?

**Comment by JiaLiPassion** [comment] 2018-01-26 08:20
@danail-vasilev .

About `SCRIPT5011: Can't execute code from a freed script`, I just can't reproduce, I didn't set the flag, and I also opened `IE developer tools`, nothing happened.

**Comment by danail-vasilev** [comment] 2018-01-26 16:18
Hi @JiaLiPassion,
Please find my comments below:
1. It is strange that the issue is not reproduced on your side when you open the console and the flag is not set. I have tested this behavior on my personal and work PC and it is reproduced on both machines. My current IE11 version is - [this](https://www.screencast.com/t/VkLDJ7cXc). On my colleague's PC, however, is reproduced other issue - something with a security exception.
1. I have found something interesting - when I set directly the `__Zone_enable_cross_context_check` property to true in the index.html file the issue doesn't seem to occur. If I use, however, the approach with setting it to `(window as any)` in the polyfills.ts file it doesn't take effect. Do you know why is that happening ? Also why do you use `(window as any)` ? 
1. So, as per the issue discussion, I have concluded the following:

- The problem occurs only when you open the console in IE11 and it doesn't break the functionality.
- If you just don't want to see the exception during development you can set the `__Zone_enable_cross_context_check` property to true but in production it shouldn't be set in order to avoid performance issue.
If that is the case you can mention that in the comment of the fix that has just been merged.
Thank you !

**Comment by JiaLiPassion** [comment] 2018-01-26 16:32
@danail-vasilev , please try the below settings.

there will be websocket to connect angular web app with angular dev server, and every time refresh IE page, there will be a new web socket was created.

and in IE, the maximum websocket connections are 6 by default, https://msdn.microsoft.com/ja-jp/library/ee330736%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396.
so error occurs, you can change the number by modify the registry.

\HKEY_CURRENT_USER\Software\Policies\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_WEBSOCKET_MAXCONNECTIONSPERSERVER
and add a key, iexplore.exe（REG_DWORD) modify the value to 2~128.

I just modify to 50, and the error gone.

**Comment by danail-vasilev** [comment] 2018-01-26 17:14
Hi @JiaLiPassion,
Thank you for your investigation! I am with Windows10 and I couldn't find the `FEATURE_WEBSOCKET_MAXCONNECTIONSPERSERVER` property in the regedit. I have searched in the following places:

1. \HKEY_CURRENT_USER | HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\Internet Explorer\Main\FeatureControl
1. \HKEY_CURRENT_USER | HKEY_LOCAL_MACHINE\Software\Microsoft\Internet Explorer\Main\FeatureControl

Anyway, can  you please comment point 2 and confirm point 3 from my previous post ?
Thank you !

**Comment by mhevery** [comment] 2018-01-26 23:24
OK it seems like we are getting into the realm of technical support. We are trying to keep this repo for issue with angular, so I am going to close this again.

**Closed by mhevery** 2018-01-26 23:24 UTC
Labels: comp: core & compiler, flag: can be closed?, type: bug

**Comment by JiaLiPassion** [comment] 2018-01-27 01:30
@danail-vasilev , about the `registry`, by default, it not exists, so you need to create the keys yourself, I also tried those settings in `Windows 10`.

And about the point3 .

> So, as per the issue discussion, I have concluded the following:
> The problem occurs only when you open the console in IE11 and it doesn't break the functionality.
> If you just don't want to see the exception during development you can set the __Zone_enable_cross_context_check property to true but in production it shouldn't be set in order to avoid performance issue.
> If that is the case you can mention that in the comment of the fix that has just been merged.
> Thank you !

in fact, there are several issues related with `IE`.

1. if you compile the project with `target -> es6`, IE will not work and throw error like `Syntax error`.
2. if you open `developer tools` and without set the `__Zone_enable_cross_context_check` flag, the error like `Can't execute code from a freed script` may occur. in this case, you should set the flag to true in polyfill, it will have some performance impact so you should only do this in `dev` mode.
3. About the error `SecurityError`, I believe this is the `websocket` error with `dev` server. so you should try the `registry` way.

I would like to make a PR to add those information as `trouble shooting` in `aio document` (I am not sure it is the right place) later.

**Comment by abbymrs** [comment] 2018-06-21 07:39
@JiaLiPassion 
Hi, in my tsconfig.json, the target is set to es5, but still got the error of syntax error in 0.***.chunk.js.
When i click on the error link, was navigated to the line with "class a{constructor(e){....}}", so it seems the webpack not compile all ts to ES5, may i know how to solve this issue? Thank you.

**Comment by trotyl** [comment] 2018-06-21 07:51
@abbymrs It's not likely come from Angular. Possibly some of your 3rd-party library is publishing es2015 code directly.

**Comment by abbymrs** [comment] 2018-06-21 08:39
@trotyl Thank you. Fixed by `npm install -D @types/third-party lib name`, and add third party lib name to `types array in tsconfig.app.json && .angular-cli.json script array`.

**Comment by ekumari** [comment] 2018-06-27 07:34
I am also facing the running issue with IE11. I already uncommented required import statement from polyfills. It is not working for me. I am getting an error in the vendor.js 
"const ucs2encode = array => String.fromCodePoint(array);" Does any have faced the issue.

**Comment by abbymrs** [comment] 2018-06-28 02:09
@ekumari I think your case is similar with mine, i saw the arrow function in your error message.
trotyl's solution works for me, and i think you can try to find out which library is written in ES6, here is a link for reference: [https://nitayneeman.com/posts/how-to-add-third-party-library-in-angular-cli/](https://nitayneeman.com/posts/how-to-add-third-party-library-in-angular-cli/)


> It's not likely come from Angular. Possibly some of your 3rd-party library is publishing es2015 code directly.

**Comment by sebastiankr** [comment] 2018-07-21 19:09
I am facing the same issue. The culprit seems to be punycode@2.1.1 included by @angular-devkit.
This is my dependency tree:
```
eang@0.0.0
| Reactive components for Angular with customizable UX themes
+-- @angular-devkit/build-angular@0.6.8
|   | Angular Webpack Build Facade
|   | git+https://github.com/angular/devkit.git
|   | https://github.com/angular/devkit
|   +-- ajv@6.4.0
|   |   | Another JSON Schema Validator
|   |   | git+https://github.com/epoberezkin/ajv.git
|   |   | https://github.com/epoberezkin/ajv
|   |   `-- uri-js@3.0.2
|   |     | An RFC 3986/3987 compliant, scheme extendable URI/IRI parsing/validating/resolving library for JavaScript.
|   |     | git+ssh://git@github.com/garycourt/uri-js.git
|   |     | https://github.com/garycourt/uri-js
|   |     `-- punycode@2.1.1
|   |       A robust Punycode converter that fully complies to RFC 3492 and RFC 5891, and works on nearly all JavaScript platforms.
|   |       git+https://github.com/bestiejs/punycode.js.git
|   |       https://mths.be/punycode
```

**Comment by ekumari** [comment] 2018-07-21 19:13
Yes after adding punnycode. It worked for me. Thanks
