### ISSUE TITLE
NgStyle and style can not set `!important`

### ISSUE THREAD

**Issue by kemsky** [angular/angular#12009] opened 2016-09-30 14:40 UTC
**I'm submitting a ...**  (check one with "x")

```
[x] bug report => search github for a similar issue or PR before submitting
```

**Current behavior** 
Both options will fail:

```
[ngStyle]="{'color':'red !important'}"
[style.color]="'red !important'"
```

**Expected behavior**
`!important` is valid css usecase.

**Reproduction of the problem**
https://plnkr.co/edit/abOMwv3tcYnnjqjCe4ff?p=preview
- **Angular version:** 2.0.0 
- **Browser:** [all ] 
- **Language:** [TypeScript 1.8.11]

**Comment by vicb** [comment] 2016-09-30 16:17
Seems like it would require using `el.setAttribute()`.

**Comment by lazarljubenovic** [comment] 2016-10-14 15:24
A quick advice for people trying to do this.

`!important` is used to override any other declaration, _incluing_ declarations set to the element itself using the `style` attribute (and this is the only way to override them). You should almost never need to add `!important` directly to the element, because it makes little sense to do so. 

```
<style> div { color: blue } </style>
<div style="color: red">I'm red, not blue! No need for !important</div>
```

The only time you need `!important` is when your CSS already has it.

```
<style> span { color: blue !important } </style>
<span style="color: red !important">I'm red now.</span>
```

But `!important` is already a bad practice in the stylesheet. Are you sure you want to do this in the actual attribute?

(It's still a bug. But a bug that stops you from writing spaghetti styles.)

**Comment by arins** [comment] 2016-10-14 15:47
I think this should be possible. If you use bootstrap css framework it has css classes that set display:none !important. How should you override these classes if not by !important?

https://github.com/twbs/bootstrap/search?utf8=%E2%9C%93&q=display%3A+none+%21important%3B

even if it is spaghetti css styles code to use !important it's hard to avoid because of bootstrap css framework.

**Comment by lazarljubenovic** [comment] 2016-10-14 15:54
They have `!important` for a reason -- they don't want to be overwritten. Also I've said:

> It's still a bug.

Not saying it shouldn't be fixed, just wanted to give heads up to people who think it's necessary.

As for bootstrap, consider [ng-bootstrap.github.io](ng-bootstrap.github.io) instead.

**Comment by bostondevin** [comment] 2018-10-12 01:16
This is a bug - running into a roadblock right now because of it

You do indeed need important absolutely!!

Case - i'm setting the the background color of an element that is already styled using an !important, so the style I set, needs to override the other one.

I don't even know how to proceed here.

**Comment by lazarljubenovic** [comment] 2018-10-14 12:50
> I don't even know how to proceed here.

Use an ID (or a few IDs if you need it for specificity) to override the `!important` from the stylesheet instead of inlining the styles.

**Comment by dharders** [comment] 2018-10-19 01:51
I'm also hitting this roadblock.

Use case: Trying to set a **dynamic** `background-size.%` on a SVG background-image in Chrome.

Chrome will not render properly unless the `!important` suffix is used, even with the correct specificity (confirmed in Chrome dev tools). This may or may not be a bug in Chrome but indeed the `!important` feature is needed **in the real world**!

Sure we can hack CSSStyleDeclaration.setProperty(), but Angular should take care of these things, or at least give the option to override, as it is very often required when using third-party libraries.

**Comment by jmls** [comment] 2018-10-26 09:18
> > I don't even know how to proceed here.
> 
> Use an ID (or a few IDs if you need it for specificity) to override the `!important` from the stylesheet instead of inlining the styles.

this does not seem to work. This is the vendor css 

```
.ui.card>:first-child, .ui.cards>.card>:first-child {
    border-radius: .28571429rem .28571429rem 0 0!important;
    border-top: none!important;
}
```
if I define my css as

```
#niocard {
    border-top: 3px solid blue;
}
```
I get 
![image](https://user-images.githubusercontent.com/929523/47557368-673fcb80-d908-11e8-8aed-6fb59a0b8afe.png)

ie the #id is still being ignored because of the !important in the vendor css

**Comment by lazarljubenovic** [comment] 2018-10-28 16:14
@jmls Use the `!important` in your own ID declaration too.

**Comment by jmls** [comment] 2018-10-28 16:19
If you add !Important to ngstyle then it fails to apply anything

**Comment by kemsky** [comment] 2018-10-28 22:42
The most significant problem here is that it is impossible to create dynamic rules, for other cases it is possible to use CSS classes.

**Comment by Alan-Luna-Carreon** [comment] 2019-01-03 18:01
The "!important" property is necessary in certain cases, therefore it should be supported.

For example: currently I had a problem trying to print tables with certain styles from a function using [style.property] = 'value', since bootstrap has statements that override my styles. Since it is still not supported, change the declaration from [style] to [class] and in the class use that property, which solved my problem.

I hope it works for someone with the same problem.

**Comment by vytautas-pranskunas-** [comment] 2019-04-11 07:37
as a workaround you can do:

`[attr.style]="('font-size:' + actions.fontSize + '% !important') | safeStyle"`

where safeStyle is 
`@Pipe({ name: 'safeStyle' })
export class SafeStylePipe implements PipeTransform {
    constructor(private sanitizer: DomSanitizer) { }
    transform(value) {
        return this.sanitizer.bypassSecurityTrustStyle(value);
    }
}`

**Comment by lppedd** [comment] 2019-04-30 10:16
Run in this "edge" case too. Workaround exists but they are still workaround, and I don't like using them in production.

**Comment by ChargerIIC** [comment] 2019-05-24 19:32
Any update on this? We are having to put workarounds in an already twiddly part of Angular. It's making me fear upgrading the @angular packages.

**Comment by alekplay** [comment] 2020-01-14 17:28
Lowkey ridiculous that this is still open...

**Comment by YurriR19900821** [comment] 2020-02-13 02:29
<div (mouseover)="hover=true" (mouseleave)="hover=false">
   <span [ngStyle]="{backgroundColor: hover==true  ? 'lightgrey' : 'grey' }">hello {{ hover }}
   </span>
</div>

**Comment by dharders** [comment] 2020-02-13 03:17
Issue opened since 2016. Seriously!??

**Comment by rhartness** [comment] 2020-02-18 16:03
Agreed.  I can't believe this is neither fixed or properly addressed with a "Not a bug, but a feature" response. I'd rather not hear the latter but `!important` is "important" for a reason.  Every now and then you need to force an override from within a code-derived style.

**Comment by lazarljubenovic** [comment] 2020-02-18 17:50
@rhartness Actually, it hasn't even been addressed officially. My (heavily downvoted) comment was in that style, but I'm not a team member. Sorry if it looked official. It's been just crickets about this since the start from the core team. I guess there's always next year :joy:

**Comment by indraraj26** [comment] 2020-04-25 10:17
when are we getting fix ?

**Comment by mcantonbul** [comment] 2020-04-29 06:50
When they ask why you don't like Angular, I show this issue.

**Comment by lazarljubenovic** [comment] 2020-04-29 08:41
> When they ask why you don't like Angular, I show this issue.

When they ask you why people don't like Angular, I show this comment.

**Comment by indraraj26** [comment] 2020-05-27 17:20
Please take this on ng10, its been 4 years

**Comment by prebenborch** [comment] 2021-02-11 01:57
Let us close this issue. First of all you need to set important in some instances - in my case for print. Today after 5 years the solution is simple. Just use [attr.style], the safePipe method as described above don't apply anymore according to my testing. The [attr.style] will do it for you according to my testing ng10.

**Comment by petebacondarwin** [comment] 2021-02-11 11:35
I believe that there is now a simple workaround for this, which is to use `[style.xxx] = "'style rule !important'"`. See https://stackblitz.com/edit/angular-ivy-gnp4jg?file=src%2Fapp%2Fapp.component.ts.

Closing. If I have missed something, please post a new comment, and I will re-open.

**Closed by petebacondarwin** 2021-02-11 11:35 UTC
Labels: P3, comp: core, core: styling bindings, freq1: low, type: bug/fix

**Comment by mcantonbul** [comment] 2021-02-11 11:53
this seems solved with pr( https://github.com/angular/angular/pull/39603). However, this issue is not referenced.
