### ISSUE TITLE
@import in css affects Parent Components

### ISSUE THREAD

**Issue by redradist** [angular/angular#21348] opened 2018-01-06 01:33 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

1. Create Parent Component and one Child Component.
2. Add custom styles for Child Component ( it won't affect Parent Component -> it is good ):
```
* {
  font-size: 20px;
}
```

3. Add @ import directive in style-sheet of Child Component **( it affect Parent Component !! )**:
```
@import "https://fonts.googleapis.com/icon?family=Material+Icons";
@import "https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css";

* {
  font-size: 20px;
}
```

## Expected behavior

1. Create Parent Component and one Child Component.
2. Add custom styles for Child Component ( it won't affect Parent Component -> it is good )
3. Add @ import directive in style-sheet of Child Component **( it should not affect Parent Component !! )**

## Minimal reproduction of the problem with instructions

1. Create Parent Component and one Child Component.
2. Add custom styles for Child Component ( it won't affect Parent Component -> it is good )
3. Add @ import directive in style-sheet of Child Component **( it affect Parent Component !! )**

## What is the motivation / use case for changing the behavior?

Separate styles of Components

## Environment

<pre><code>
Angular version: 5.1.3

Browser:
- [X] Chrome (desktop) version New
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.9.4  
- Platform:  Linux 

Others:

</code></pre>

**Comment by mlc-mlapis** [comment] 2018-01-06 12:33
@redradist ... the problem is related to the fact that you import external styles as `@import "https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css";`. It's technically not possible for Angular compiler to process such a dynamic thing ... imagine that the resource can change in any moment ... so it's not possible for such imports to apply style encapsulations ... with the final effect that it would apply only to `Child` component ... **so those have always global effects**.

But if you apply them just as local things as:
* `@import 'someimport.child.component.css';`
* with the content of `.anyclass {...; background-color: #24d61d; color: #8d0a2a}`
* in a file `child.component.css`
* and use it in metadata of the `Child` as `@Component({..., styleUrls: ['child.component.css']})`

then Angular compiler is able to create encapsulated styles that are applied just for `Child` component as for example ... see `[_ngcontent-c2]` which is id of a concrete `Child` element on a page:
```
<style>.anyclass[_ngcontent-c2] {
	background-color: #24d61d;
	color: #8d0a2a
}</style>
```

**Comment by redradist** [comment] 2018-01-06 13:35
@mlc-mlapis Thank for answer. Maybe in this case it is better to add warning or compile error, because from developer side view it is not obvious behavior ...

@mlc-mlapis And maybe it is possible to do ( encapsulate @ import of external styles ) in case of **Angular Universal** when server compile templates ?

**Comment by mlc-mlapis** [comment] 2018-01-06 13:46
@redradist ... I don't think so ... processing such external styles could be extremely hard and even not possible at all in the end. And there is a question why to do it at all finally ... what are the exact cases where it would be so extremely beneficial.

> And maybe it is possible to do ( encapsulate @ import of external styles ) in case of Angular Universal when server compile templates ?

**Comment by redradist** [comment] 2018-01-06 17:24
@mlc-mlapis Okay, what about error during compilation ? To emphasis the fact it can cause unpredictable behavior ...

**Comment by mlc-mlapis** [comment] 2018-01-06 17:34
@redradist ... please, close this issue and create a new feature one for it . Link it to this one. Thanks.

**Comment by dylhunn** [comment] 2022-03-31 23:13
This is a bug, not a feature. Closing #21365.

**Comment by crisbeto** [comment] 2022-09-22 08:11
We talked through this in one of our team meetings and we decided to close this, because:
1. It appears to be working as expected based on some of the tests here: https://github.com/angular/angular/blob/main/packages/compiler/test/shadow_css_spec.ts#L432
2. We don't have a way of encapsulating the `@import` since it isn't allowed to be nested under a selector. In theory we could inline the import, but that would introduce a lot of complexity in the compiler for relatively little gain.

**Closed by crisbeto** 2022-09-22 08:11 UTC
Labels: comp: core, core: CSS encapsulation
