### ISSUE TITLE
Importing default export breaks compilation (just installed)

### ISSUE THREAD

**Issue by tsteuwer** [angular/angular#18660] opened 2017-08-12 01:00 UTC
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
First time messing with the new Angular in TS. I did a simple `ng new test-app` and started following along with the tutorial over [here](https://angular.io/tutorial/toh-pt1). I got to the part that says go create a new class called Hero. I did a simple `ng g class hero` and here is the file verbatim:

```
export default class Hero {
  id: Number;
  name: String;
}
```

Went and opened the app component and changed the definition of the component to what the tutorial says (verbatim):
```
import { Component } from '@angular/core';
import Hero from './hero';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title: 'Tour Of Heroes';
  hero: Hero = {
    id: 1,
    name: 'Windstorm',
  };
}
```

And the CLI is saying:

```
ERROR in /home/troy/development/test-angular/src/app/app.component.ts (2,8): Module '"/home/troy/development/test-angular/src/app/hero"' has no default export.

webpack: Failed to compile.
```

This is obviously not true. If I then remove the `default` on export, and simply call it in the component as `import { Hero } from './hero';` it works.

## Expected behavior
Exporting a class as a default export should not produce any compile errors.

## Minimal reproduction of the problem with instructions
Provided above. I've also made a repo with everything I have: https://github.com/tsteuwer/angular-4-default-export-issue

## What is the motivation / use case for changing the behavior?
It should be fixed.

## Environment

<pre><code>
Angular version: X.Y.Z
@angular/cli: 1.3.0
node: 6.0.0
os: linux x64
@angular/animations: 4.3.4
@angular/common: 4.3.4
@angular/compiler: 4.3.4
@angular/core: 4.3.4
@angular/forms: 4.3.4
@angular/http: 4.3.4
@angular/platform-browser: 4.3.4
@angular/platform-browser-dynamic: 4.3.4
@angular/router: 4.3.4
@angular/cli: 1.3.0
@angular/compiler-cli: 4.3.4
@angular/language-service: 4.3.4

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v6.0.0
- Platform:  Linux

Others:
None
</code></pre>

**Comment by trotyl** [comment] 2017-08-12 12:36
Duplicate of https://github.com/angular/angular/issues/11402 .

**Comment by hansl** [comment] 2017-08-14 19:16
This seems like a duplicate of #11402, but it’s not a straight duplicate so leaving this opened. This might be an issue happening inside angular-cli instead. Need to investigate.

**Comment by vicb** [comment] 2017-08-15 20:19
closing as duplicate

**Closed by vicb** 2017-08-15 20:19 UTC
Labels: comp: core & compiler
