### ISSUE TITLE
[2.1.2] When select[multiple] is false then UI is not "multiple" but the ngModel return Array

### ISSUE THREAD

**Issue by nureha** [angular/angular#12585] opened 2016-10-28 07:58 UTC
**I'm submitting a ...**  (check one with "x")

```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When select[multiple] is false then UI is not "multiple" but the ngModel return Array

**Expected behavior**
The model is not to return Array

**Minimal reproduction of the problem with instructions**
https://plnkr.co/edit/uU2p2GTf0ta0WP3ndegl?p=preview

**What is the motivation / use case for changing the behavior?**
I was trying to make a custome component that is "multiple" configureable
- **Angular version:** 2.1.2
- **Browser:** [Chrome 54]
- **Language:** [TypeScript 2.0]

**Comment by laco0416** [comment] 2016-10-28 09:43
I think probably `SelectMultipleControlValueAccessor` should check its own `multiple` property and change  the behavior of `writeValue` method.

**Comment by DzmitryShylovich** [comment] 2016-12-17 20:28
I think it's related to https://github.com/angular/angular/issues/11716

**Comment by ph55** [comment] 2017-09-19 10:27
So I need to duplicate select element inside dynamic form builder ? Yuk.
Any ETA on this ?

**Comment by AndrewKushnir** [comment] 2020-05-28 23:53
Hi, it looks like the issue still exists with the latest versions of Angular packages (9.1.7), [example test page via Stackblitz](https://stackblitz.com/edit/angular-ivy-bkbi27).

**Comment by AndrewKushnir** [comment] 2021-02-08 20:58
Closing this PR based on https://github.com/angular/angular/pull/38719#issuecomment-689031862 and information from https://github.com/angular/angular/issues/11716 (this is caused by the framework limitations related to directive matching using dynamic binding values). Thank you.

**Closed by AndrewKushnir** 2021-02-08 20:58 UTC
Labels: P4, comp: forms, forms: DOM, forms: ngModel, freq1: low, state: confirmed, triage #1, type: bug/fix
