### ISSUE TITLE
Form validation classes are not applied correctly on the input inside a custom component

### ISSUE THREAD

**Issue by michaelchiche** [angular/angular#9700] opened 2016-06-29 14:06 UTC
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

The form classes added to an input inside a custom element don't reflect the form classes applied on the custom "parent" component by the formControl.

**Expected/desired behavior**

The form classes added to an input inside a custom element should be same as the form classes applied on the custom "parent" component by the formControl.

**Reproduction of the problem**

In this plunker, the custom element becomes valid after it has 5 characters. The classes are applied correctly to the custom component, but not the input inside.

http://plnkr.co/edit/VltDxbrcQdL3YmTr1ehe?p=preview

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**
There is a need of consistency between the 2 (input inside the custom component, and the custom component itself).
Otherwise some valid style might apply to the parent, and not the input, or vice versa.

Here are also 2 screenshots showing the inconsistency:

![capture d ecran 2016-06-29 a 15 55 06](https://cloud.githubusercontent.com/assets/371278/16454935/e180bf6e-3e12-11e6-972b-6d8ee3e624ee.png)

![capture d ecran 2016-06-29 a 15 54 47](https://cloud.githubusercontent.com/assets/371278/16454891/c193da56-3e12-11e6-80e2-0d18057ad1c4.png)

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.3
 
* **Browser:** [all ] 
 
* **Language:** [all]

**Comment by slmyers** [comment] 2016-06-29 18:12
There are issues on my machine with the plunker loading -- wrt Typescript transpilation. 

![plunkrwontload](https://cloud.githubusercontent.com/assets/6344732/16463360/c1570bb4-3df2-11e6-80f1-0095220482b3.png)
)

**Comment by michaelchiche** [comment] 2016-06-29 18:25
@slmyers I just checked. It works on my end. try this one: http://embed.plnkr.co/VltDxbrcQdL3YmTr1ehe/?

**Comment by michaelchiche** [comment] 2016-07-12 16:16
any updates?

**Comment by michaelchiche** [comment] 2016-07-12 16:21
Any updates on this issue? I just updated my plunker to rc4, and I still have the same error.

**Comment by michaelchiche** [comment] 2016-07-12 23:08
I have create a new plunker to be able to see the classes applied to both the input and custom component.

You can check it here: https://run.plnkr.co/IE1ELRey6l0YTHS2/

**Comment by michaelchiche** [comment] 2016-07-19 15:30
@kara I just saw you added a label. Does it mean that you are looking into it? Is it a confirmed bug?
Thanks for your help !

**Comment by kara** [comment] 2016-10-12 18:28
@michaelchiche It’s up to the custom value accessor to dictate what its internal state should be, which includes control status classes. Its inner workings are encapsulated from the parent form. Sometimes it may not be beneficial to keep everything synced (especially in the case where your value accessor contains multiple child controls, like an address accessor). So to keep the classes the same, it needs to be explicitly implemented.

In your case, if you’d always like the custom control to have required and minlength validators, I’d add those validators on the inner input and then provide them as NG_VALIDATORS on top (so you don’t have to do it in the parent).

I’m closing this, as it works as intended. That said, we are looking into how we can simplify writing value accessors in the future, so we'll keep this case in mind as a potential pain point. Thanks for reporting.

**Closed by kara** 2016-10-12 18:28 UTC
Labels: comp: forms
