### ISSUE TITLE
strictNullChecks errors on third party library templates during AOT compilation

### ISSUE THREAD

**Issue by filipesilva** [angular/angular#21390] opened 2018-01-08 15:52 UTC
Copied from @imba3r original report in https://github.com/angular/angular-cli/issues/8373.

Repo provided as https://github.com/imba3r/angular-cli-issue-8373.

---

### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
```
Angular CLI: 1.5.0
Node: 6.9.5
OS: win32 x64
Angular: 5.0.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.5.0
@angular-devkit/build-optimizer: 0.0.32
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.35
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.0
@schematics/angular: 0.1.0
typescript: 2.4.2
webpack: 3.8.1

```

### Repro steps.

1. Create a new project.
2. Add a dependency that does not compile with strictNullChecks=true.
3. Enable strictNullChecks and skipLibCheck in tsconfig.
```
tsconfig.json:
    ...
    "strictNullChecks": true,
    "skipLibCheck": true,
    ...
```

### The log given by the failure.

```
$ ng build --prod
Date: 2017-11-06T17:27:15.764Z
Hash: 8e4cd6cc4d070e8a0de8
Time: 22346ms
chunk {0} styles.fabe2b98feb13974353f.bundle.css (styles) 229 kB [initial] [rendered]
chunk {1} polyfills.3bc34265385d52184eab.bundle.js (polyfills) 86 bytes [initial] [rendered]
chunk {2} main.e402deade8b026b7d50e.bundle.js (main) 84 bytes [initial] [rendered]
chunk {3} inline.bb2ddc972beb199ae1a7.bundle.js (inline) 1.45 kB [entry] [rendered]

ERROR in Error at C:/[......]/ui/node_modules/ng-snotify/ng-snotify.d.ts.ToastComponent.html(1,193): Object is possibly 'undefined'.
Error at C:/[......]/ui/node_modules/ng-snotify/ng-snotify.d.ts.ToastComponent.html(1,193): Object is possibly 'undefined'.
Error at C:/[......]/ui/node_modules/ng-snotify/ng-snotify.d.ts.ToastComponent.html(1,193): Object is possibly 'undefined'.
Error at C:/[......]/ui/node_modules/ng-snotify/ng-snotify.d.ts.ToastComponent.html(1,193): Object is possibly 'undefined'.


```

### Desired functionality.
The build should succeed.

### Mention any other details that might be useful.
In my case I added ng-snotify: `npm install --save ng-snotify`.
I have not tried this with a version <1.5.0.

**Comment by filipesilva** [comment] 2018-01-08 15:53
It looks like the Angular Compiler is reporting errors for `strictNullChecks` in templates for a library. I think this is a bug because you can't control third party templates or definition files.

**Comment by chuckjaz** [comment] 2018-01-08 17:10
The steps don't say it but I assume you  must turn on `"fullTemplateTypeCheck"` as well I assume; correct?

**Comment by trotyl** [comment] 2018-01-09 02:29
Relates to #21353

**Comment by filipesilva** [comment] 2018-01-09 10:33
@chuckjaz the provided repro (https://github.com/imba3r/angular-cli-issue-8373) does not contain `fullTemplateTypeCheck` in its tsconfigs.

I double checked with updated versions of everything and it still seems to happen:
```
Angular CLI: 1.6.3
Node: 8.9.1
OS: win32 x64
Angular: 5.1.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.3
@angular-devkit/build-optimizer: 0.0.36
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.42
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.3
@schematics/angular: 0.1.11
@schematics/schematics: 0.0.11
typescript: 2.4.2
webpack: 3.10.0
```

```
kamik@T460p MINGW64 D:/sandbox/angular-cli-issue-8373 (master)
$ npm run ng -- build --aot

> repro-app@0.0.0 ng D:\sandbox\angular-cli-issue-8373
> ng "build" "--aot"

Date: 2018-01-09T10:31:08.987Z
Hash: 3519c22d7b7d76376a8e
Time: 2617ms
chunk {inline} inline.bundle.js, inline.bundle.js.map (inline) 5.83 kB [entry] [rendered]
chunk {main} main.bundle.js, main.bundle.js.map (main) 303 bytes [initial] [rendered]
chunk {polyfills} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 323 bytes [initial] [rendered]
chunk {styles} styles.bundle.js, styles.bundle.js.map (styles) 11.4 kB [initial] [rendered]

ERROR in node_modules\ng-snotify\ng-snotify.d.ts.ToastComponent.html(1,193): : Object is possibly 'undefined'.
node_modules\ng-snotify\ng-snotify.d.ts.ToastComponent.html(1,193): : Object is possibly 'undefined'.
node_modules\ng-snotify\ng-snotify.d.ts.ToastComponent.html(1,193): : Object is possibly 'undefined'.
node_modules\ng-snotify\ng-snotify.d.ts.ToastComponent.html(1,193): : Object is possibly 'undefined'.
```

**Comment by Ks89** [comment] 2018-05-06 20:41
@filipesilva 
I have exactly the same problem with Angular 6.0.0 and angular-cli 6.0.0.
This is my config:

```
"angularCompilerOptions": {
    "fullTemplateTypeCheck": true,
    "preserveWhiteSpace": false,
    "strictInjectionParameters": true,
    "strictNullChecks": true
  }
```

Is there a way to enable full debug/verbose logs to see which Object is possibly undefined? I don't understand if this is an error of my library when used inside a project with aot and strictNullChecks or if it is an angular bug.

If you have a trick to log more please add it here, so I can share the log with you, because this issue is really annoying for a library developer.

**Comment by elvirdolic** [comment] 2018-05-08 09:13
Same issue can be reproduced also with the LIB: https://github.com/MurhafSousli/ngx-gallery/issues/82

**Comment by kk21717** [comment] 2018-05-13 10:01
adding
**"strictNullChecks": false**
to **tsconfig.json** worked for me!

**Comment by elvirdolic** [comment] 2018-05-19 18:10
Will this bug get fixed? Or does it need more information?

**Comment by elvirdolic** [comment] 2018-07-12 15:30
@filipesilva do you now something about this issue? How we can fix this. It's really an issue.

**Comment by filipesilva** [comment] 2018-07-14 02:44
@elvirdolic all the information I have is in this issue right now, I don't have anything myself to add. It's on the backlog for the core team to look at.

**Comment by Mr1upMachine** [comment] 2020-01-07 18:21
Is there any progress on this?

**Comment by JoostK** [comment] 2020-03-15 23:28
This issue has been resolved in Ivy, given that external libraries are no longer compiled nor type checked during the compilation of an application. Closing as resolved in Ivy.

**Closed by JoostK** 2020-03-15 23:28 UTC
Labels: comp: compiler, freq2: medium, severity3: broken, type: bug/fix
