### ISSUE TITLE
404 broken link to "pipes API documentation" 

### ISSUE THREAD

**Issue by fredsa** [angular/angular#56089] opened 2024-05-27 04:57 UTC
### Describe the problem that you experienced

https://angular.dev/guide/pipes#built-in-pipes links to  https://angular.dev/api/common#pipes, which is a 404.

Notes that https://angular.io/api/common#pipes redirects to https://v17.angular.io/api/common#pipes which does exist.

### Enter the URL of the topic with the problem

https://angular.dev/guide/pipes#built-in-pipes

### Describe what you were looking for in the documentation

Built-in types documentation

### Describe the actions that led you to experience the problem

Clicked "pipes API documentation" link

**Comment by JeanMeche** [comment] 2024-05-27 06:47
Duplicate of #52968

**Closed** 2024-05-27 06:47 UTC
