### ISSUE TITLE
Allow for service worker to be bypassed entirely for certain URL patterns

### ISSUE THREAD

**Issue by bd60** [angular/angular#25007] opened 2018-07-20 17:42 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ X ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Currently the service worker always handles the request response, even if it eventually passes straight to the fetch API. This is fine since in theory the fetch API does exactly what the browser would have, but this is not always the case in practice and the fetch API still has bugs in it. In my case, streaming long videos is not handled well at all by the fetch API.

## Expected behavior

Would be great for these situations to be able to specify a set of URLs / Patterns to entirely bypass the service worker and the fetch API.

## Minimal reproduction of the problem with instructions

No steps, just no possible way to do this right now without manually rewriting ngsw-worker.js post build.

## What is the motivation / use case for changing the behavior?

As stated, the fetch API isn't perfect and sometimes the best solution is just to bypass it.

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by gkalpak** [comment] 2018-07-20 17:57
One problem with this is that there is no way to synchronously determine if a URL should be handled or not. We have to first retrieve the manifest (aka `AppVersion`) that serves the current client and then look at its list of excluded URLs. 

The question is whether or not we can delay the decision of whether a request will be handled by the SW or not ([here][1]). If this needs to happen synchronously, then we're out of luck. (If someone wanted to investigate this and report back, that would be rad :grin:)

Alternatively, another way out would be built-in support for enhancing `ngsw-worker.js` (via some sort of SW polyfills) as described in https://github.com/angular/angular/issues/20756#issuecomment-386315924.

[1]: https://github.com/angular/angular/blob/23766b85e910f2a1488081de48e1c90d052629c6/packages/service-worker/worker/src/driver.ts#L163-L208

**Comment by bd60** [comment] 2018-07-20 18:07
waitUntil cant' be used to run an initilization check?

**Comment by gkalpak** [comment] 2018-07-20 18:18
I don't know. Maybe. That's the thing that needs investigation :grin:
I.e. is it possible to use `event.waitUntil()`, do the check asynchronously and then decide we don't want to handle the request.

**Comment by bd60** [comment] 2018-07-20 18:52
Good point, tried a few different set ups and have had no luck so far getting it to work async.  Seems like even using waitUntil, the fetch event wants a synchronous response.  Seems like your other suggestion would be the way to go with it if it were to be implemented unless someone more experienced than I with service workers can get it. 

The workaround as it stands is less than ideal given it's build and deployment implications, and makes angular service workers problematic for any site delivering things like streaming content.

**Comment by manklu** [comment] 2018-07-20 20:53
It seems that it is currently impossible to bypass a service worker.

See https://github.com/w3c/ServiceWorker/issues/1026

**Comment by bd60** [comment] 2018-07-20 21:04
title may be misleading, the service worker doesn't need to be bypassed, it just needs to not try to route the request through the fetch api and let the browser handle it natively.

**Comment by gkalpak** [comment] 2018-07-21 08:41
Unfortunately, my understanding of [the spec][1] is that `respondWith()` is a decision that needs to be made synchronously 😞 

[1]: https://w3c.github.io/ServiceWorker/#on-fetch-request-algorithm

**Comment by gkalpak** [comment] 2018-07-21 09:15
[Another thread][1] that concludes it is not possible to do that. The bottom-line is that calling `fetch(event.request)` from the SW should have the exact same behavior (so it is a browser implementation issue if it doesn't, not a spec issue) 🤷‍♂️ 

[1]: https://github.com/w3c/ServiceWorker/issues/836

**Comment by bd60** [comment] 2018-07-21 23:36
Yea it makes sense that the worker needs to tell the browser synchronously who is handling the request.  A fuller solution would be to alter the build process so the service worker conf is built into the worker itself so that it can be initialized synchronously.  There is nothing stopping the worker from requesting new copies of itself to check for updates.

**Comment by bd60** [comment] 2018-07-21 23:37
However, I think this does make angular service workers non viable for media intensive applications. I understand this is a bug in fetch and not angular itself, but it's still a big problem that needs a work around.

**Comment by gkalpak** [comment] 2018-09-17 08:10
Closing as a duplicate of #21191. Let's track the issue there.

**Closed by gkalpak** 2018-09-17 08:10 UTC
Labels: comp: service-worker, type: feature
