### ISSUE TITLE
Wrong tag closing (template parser error)

### ISSUE THREAD

**Issue by renanmontebelo** [angular/angular#28638] opened 2019-02-11 04:26 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/core

### Is this a regression?

 Can't confirm but probably yes.

### Description

The `</pre>` tag apparently is closing `<p>` tags.

## 🔬 Minimal Reproduction
Create a template like this:
```
<h3>Formbuilder</h3>
<p>
  Valid: {{ form.valid }} <br>
  Id: {{ model.id }} <br>
  First Name: {{ model.firstName }} <br>
  Last Name: {{ model.firstName }} <br>
  <pre>{{model | json}}</pre>
</p>
```

If the `<pre>...</pre>` line is deleted then no parser error happens.

## 🔥 Exception or Error
<pre><code>

Error: Template parse errors: Unexpected closing tag "p".
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 7.3.1
Node: 10.14.1
OS: linux x64
Angular: 7.2.4
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.1
@angular-devkit/build-angular     0.13.1
@angular-devkit/build-optimizer   0.13.1
@angular-devkit/build-webpack     0.13.1
@angular-devkit/core              7.3.1
@angular-devkit/schematics        7.3.1
@angular/cli                      7.3.1
@ngtools/webpack                  7.3.1
@schematics/angular               7.3.1
@schematics/update                0.13.1
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.29.0
</code></pre>

**Anything else relevant?**

**Comment by trotyl** [comment] 2019-02-11 04:36
Duplicate of https://github.com/angular/angular/issues/5540

---

Both `<pre>` and `<br>` are not allowed in `<p>` per HTML spec.

**Closed** 2019-02-11 05:03 UTC
