### ISSUE TITLE
404 in "Try out inject"

### ISSUE THREAD

**Issue by MuhAssar** [angular/angular#54153] opened 2024-01-30 07:10 UTC
### Describe the problem that you experienced

![image](https://github.com/angular/angular/assets/2022065/f4698201-838a-4261-9d78-4cd7073da69e)

![image](https://github.com/angular/angular/assets/2022065/da03a153-0309-4f99-a91b-9f4832c2b2c9)

### Enter the URL of the topic with the problem

https://angular.dev/roadmap

### Describe what you were looking for in the documentation

[Try out Inject](https://angular.dev/di) in 404 not found

**Comment by JoostK** [comment] 2024-01-30 07:16
Thanks for the report, this is a duplicate of https://github.com/angular/angular/issues/52539 for which the fix is pending deployment.

**Closed by JoostK** 2024-01-30 07:16 UTC
