### ISSUE TITLE
Add a way to change Signals values

### ISSUE THREAD

**Issue by FilipeJohansson** [angular/angular#52889] opened 2023-11-14 13:06 UTC
### Is this a bug report or a feature request?

- [ ] Bug Report
- [X] Feature Request

### Description [Feature Request only]

I like to use Angular Devtools to test some states of the application. I can change the values and this updates the view.
But with Signals, we can't do this without have some kind of event occuring from user (like the press of a button to test, or something like this).

We can change the value of Inputs() and other properties - in red -, but we can't change the value from Signals - in blue.
![image](https://github.com/angular/angular/assets/56850125/dce19d82-e264-4461-9acd-379f81d75b84)
![image](https://github.com/angular/angular/assets/56850125/8200649e-b5dc-4612-874d-22e015478afd)

### Proposed solution [Feature Request only]

Be able to change the Signals (computed also) values, so we can test what happens if some state changes.

**Comment by alxhub** [comment] 2023-12-12 17:43
Closing as a duplicate of #50944.

**Closed by alxhub** 2023-12-12 17:43 UTC
Labels: feature, feature: votes required, area: devtools, cross-cutting: signals
