### ISSUE TITLE
Signal doesn't set without setTimeout in observable v16.0.0-rc.2 

### ISSUE THREAD

**Issue by ntorrey** [angular/angular#49940] opened 2023-04-19 20:27 UTC
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

```ts
title = signal('')
selectedEvent$ = this.route.paramMap.pipe(
    switchMap((paramMap) => {
      if (paramMap.get('event-id') === 'add') {
        this.title.set('Add Event') <-- This doesn't 'fire' unless I wrap it in a setTimout
        return of(this.eventsService.createNewEvent())
      }
      ...
    }),
  )
```

### Please provide the exception or error you saw

```true
No error, it just does nothing! In rc.1, setting a signal outside a setTimeout (but within the observable) would throw an error, but not anymore. Now it just does nothing.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 16.0.0-rc.0
Node: 18.12.1
Package Manager: npm 9.6.4
OS: win32 x64

Angular: 16.0.0-rc.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1600.0-rc.0
@angular-devkit/build-angular   16.0.0-rc.0
@angular-devkit/core            13.3.8
@angular-devkit/schematics      13.3.8
@angular/cdk                    16.0.0-rc.0
@angular/cli                    16.0.0-rc.0
@angular/material               16.0.0-rc.0
@schematics/angular             15.2.6
ng-packagr                      15.2.2
rxjs                            7.8.0
typescript                      5.0.4
```

**Comment by atscott** [comment] 2023-04-19 22:50
Please provide a reproduction. I was not able to reproduce this behavior in stackblitz: https://stackblitz.com/edit/angular-n6c1x9?file=src%2Fmain.ts,package.json

Note that updating a signal _only_ marks the component dirty. If you are doing this at a time where change detection would not be scheduled, you will not see the value get updated. I would guess this is what you're observing since `setTimeout` causes another round of change detection to trigger with ZoneJS.

**Comment by ntorrey** [comment] 2023-04-20 00:39
Sorry, should have made the reproduction in the first place! This is a more accurate reproduction of what I'm seeing.
https://stackblitz.com/edit/angular-fnyavc?file=src/main.ts

So strangely enough, now it's throwing an error in Stackblitz unless I wrap it in a setTimeout (something it's not doing on my local machine).

Will 'OnPush' change detection detect changed signals in version 16?

**Comment by atscott** [comment] 2023-04-20 00:48
So what’s happening here is that you’re using the async pipe to subscribe to the observable. Then, when that subscription happens, causing a synchronous update backwards in the template, which is ExpressionChangedAfterItWasChecked. You would be able to see this without signals as well. I would guess that your project is using OnPush, and the ExpressionChanged error doesn’t work for OnPush components. 

Closing as working as expected.

**Closed by atscott** 2023-04-20 00:48 UTC
Labels: needs reproduction, area: core
