### ISSUE TITLE
AOT - Style_compiler runtime error with ViewEncapsulation.None

### ISSUE THREAD

**Issue by unsafecode** [angular/angular#12775] opened 2016-11-09 12:19 UTC
**I'm submitting a ...**
```
[X] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
When using AoT compilation, in particular with the `@ngtools/webpack` plugin, using `ViewEncapsulation.None` in a component with stylesheets, an error is raised at runtime, since component styles are *always* accessed through the *styles* exported member, but this only exists when `ViewEncapsulation` is set to `Emulated`. Because of that, the `_flattenStyles` function received an array with `undefined` items, and tries to run the `replace` method over it.

**Expected behavior**
Regardless of which `ViewEncapsulation` is used, compiled styles imports should not break at runtime.

**Minimal reproduction of the problem with instructions**
1. Clone and setup https://github.com/blacksonic/angular2-aot-webpack/
2. Delete _ngfactory_ folder and files
3. Add `ViewEncapsulation.None` to home.component.s
4. Run

**What is the motivation / use case for changing the behavior?**
You can take a look at the `style_compiler `source code: https://github.com/angular/angular/blob/master/modules/%40angular/compiler/src/style_compiler.ts#L60. When in a *component* context, a variable named *styles* is used to get the exported value. However, that variable only exists when a *shim* is used, but only happens when `ViewEncapsulation` is `Emulated`.

**Please tell us about your environment:**
Windows 10 build 1607

* **Angular version:** 2.1.2

* **Browser:** all
 
* **Language:** TypeScript 2.0.7

* **Node (for AoT issues):** `node --version` =   6.9.1

**Comment by DzmitryShylovich** [comment] 2016-11-09 12:23
Duplicate of https://github.com/angular/angular-cli/issues/2584

**Comment by tbosch** [comment] 2016-11-11 19:25
@DzmitryShylovich thanks! Closing this one then as it looks like a cli problem.

**Closed by tbosch** 2016-11-11 19:25 UTC
Labels: comp: core & compiler
