### ISSUE TITLE
Dependency injection not working for extended component when running tests with code coverage

### ISSUE THREAD

**Issue by kenborge** [angular/angular#41090] opened 2021-03-05 14:55 UTC
# 🐞 bug report

### Affected Package

Seems to be related to interaction between reflection logic in @angular/core and the Istanbul loader used by angular cli

### Is this a regression?

Exists at least in angular 10 and 11

### Description
Running tests with code coverage and typescript target es2015 causes dependency injection too stops working in parent class when extending components and you declare a property with an initial value. See example below.

The issue was discovered when we were extending CdkTable from the material project, and the dependency injection in all the Cdk classes stop working when we run tests with code coverage. 

Here are some issues from the past that seems to be similar 
https://github.com/angular/components/issues/12760
https://github.com/angular/angular/pull/24014
https://github.com/angular/angular/pull/29232

Based on these i would assume that this is caused by some change to the compiled code that the Istanbul loader is doing when tests are run with code coverage, that causes the angular reflection logic to not identify this properly. 

## 🔬 Minimal Reproduction
`ng new test-app`
`cd test-app`

Replace content of app.component.ts with
```
import { Component, ElementRef } from '@angular/core';

@Component({
  template: ''
})
export class ParentComponent {
  constructor(private el: ElementRef) {
    el.nativeElement.focus();
  }
}

@Component({
  template: ''
})
export class ChildComponent extends ParentComponent {
  thisLineCausesError = 1;
}
```

and app.component.spec.ts with

```
import { TestBed } from '@angular/core/testing';
import { ChildComponent } from './app.component';

describe('AppComponent', () => {
  beforeEach(async () => {
    await TestBed.configureTestingModule({
      declarations: [
        ChildComponent
      ],
    }).compileComponents();
  });

  it('should create the app', () => {
    const fixture = TestBed.createComponent(ChildComponent);
    const app = fixture.componentInstance;
    expect(app).toBeTruthy();
  });
});
```
Here is a repo setup with these changes: https://github.com/kenborge/angular-code-coverage-dependency-issue

Running tests normally `npm run test` works just fine:
```
Executed 1 of 1 SUCCESS (0.049 secs / 0.033 secs)
TOTAL: 1 SUCCESS
```
but then running them with code coverage enabled `npm run test -- --code-coverage` throws error because the dependency injection of ParentComponent no longer works so elementRef becomes undefined:
<pre><code>
AppComponent should create the app FAILED
	TypeError: Cannot read property 'nativeElement' of undefined
	    at new ParentComponent (src/app/app.component.ts:10:2)
	    at new ChildComponent (main.js:540:5)
	    at NodeInjectorFactory.ChildComponent_Factory [as factory] (ng:///ChildComponent/ɵfac.js:4:10)
	    at getNodeInjectable (node_modules/@angular/core/fesm2015/core.js:3534:1)
	    at instantiateRootComponent (node_modules/@angular/core/fesm2015/core.js:10083:1)
	    at createRootComponent (node_modules/@angular/core/fesm2015/core.js:12395:1)
	    at ComponentFactory$1.create (node_modules/@angular/core/fesm2015/core.js:25078:1)
	    at initComponent (node_modules/@angular/core/fesm2015/testing.js:1740:1)
	    at ZoneDelegate.invoke (node_modules/zone.js/dist/zone-evergreen.js:372:1)
	    at ProxyZoneSpec.push.QpwO.ProxyZoneSpec.onInvoke (node_modules/zone.js/dist/zone-testing.js:301:1)
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 11.2.3
Node: 12.10.0
OS: darwin x64

Angular: 11.2.4
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.3
@angular-devkit/build-angular   0.1102.3
@angular-devkit/core            11.2.3
@angular-devkit/schematics      11.2.3
@angular/cli                    11.2.3
@schematics/angular             11.2.3
@schematics/update              0.1102.3
rxjs                            6.6.6
typescript                      4.1.5

</code></pre>

**Comment by JoostK** [comment] 2021-03-05 15:08
Duplicate of #31337

**Closed by JoostK** 2021-03-05 15:08 UTC
