### ISSUE TITLE
Suggestion about generate smaller *.chunk.js

### ISSUE THREAD

**Issue by suplch** [angular/angular#13492] opened 2016-12-15 10:42 UTC
A little suggestion about generate smaller *.chunk.js
I run command ng build -aot, and then generate some *.chunk.js file in dist folder.
I open a file '0.b7bbe93ad30bd6c6f312.chunk.js, this file size is about 474kb, I search by matching text "this.renderer.createText" in file, there are 432 matches, I can also see other long variable name or method name. Can we generate a short name for them. or we create convenient method for them.
```
 transform "this.renderer.createText" to "this.r.c",   this can save (7 + 9) * 432 = 6912 character
 transform "this._text_..." to "this.txt...",  this can save 3 * 909 = 2727 character
 transform "this._anchor_..." to "this.ac..."  this can save 6 * 228 character
and etc...
```
like this
```
[ ] feature request
```

**Current behavior**
Generate big *.chunk.js file with webpack tools.

**Expected behavior**
Generate more smaller *.chunk.js.

**What is the motivation / use case for changing the behavior?**
Make more smaller *.chunk.js for mobile application.

* **Angular version:** 2.2.3

* **Browser:** [Chrome]

* **Language:** [TypeScript 2 ]

* **Node (for AoT issues):** `node --version` =  7.0

**Comment by DzmitryShylovich** [comment] 2016-12-15 10:45
Duplicate of https://github.com/angular/angular/issues/13360

**Comment by pkozlowski-opensource** [comment] 2016-12-15 10:47
It is duplicate of #13360 indeed. Let's centralize the discussion in there. Thnx @DzmitryShylovich

**Closed by pkozlowski-opensource** 2016-12-15 10:47 UTC
