### ISSUE TITLE
Setting __Zone_disable_ZoneAwarePromise to true throws error

### ISSUE THREAD

**Issue by davidstellini** [angular/angular#49538] opened 2023-03-22 10:56 UTC
### Which @angular/* package(s) are the source of the bug?

zone.js

### Is this a regression?

No

### Description

I see this issue was opened here but now closed: https://github.com/angular/angular/issues/37349

What is the idea behind this flag:
`__Zone_disable_ZoneAwarePromise`

When this check here effectively ensures it's never been enabled?

https://github.com/angular/angular/blob/1b9fd46d14ed46f78b6d761b3917ded1f0d51e0d/packages/zone.js/lib/zone.ts#L719

Minimal repro:

```
(async () => {
	(window as any).__Zone_disable_ZoneAwarePromise = true;
	require('zone.js'); 
})();
```

**Comment by JeanMeche** [comment] 2023-03-22 11:45
Hi, 

`zone.js` is a library that can be used by any app/library, not only Angular. 
For those other libraries, that don't want to patch the promises, there is `__Zone_disable_ZoneAwarePromise`. 

But Angular requires the promises to be patched. 
In Angular, you have `ng_zone`, an angular service that provides functions for working with zone within Angular. It's this service that calls `Zone.assertZonePatched();` to ensure that the patch has been applied. 

https://github.com/angular/angular/blob/69a6e09e7eb13b592fb5430cf83800d9d73aea71/packages/core/src/zone/ng_zone.ts#L140

**Comment by alan-agius4** [comment] 2023-03-23 12:36
Closing as this is by design. See explanation above and https://github.com/angular/angular/issues/37349#issuecomment-650562852

**Closed by alan-agius4** 2023-03-23 12:36 UTC
Labels: area: zones
