### ISSUE TITLE
Encountering a NullInjectorError: No provider for _RadioControlRegistry! error when using @defer block

### ISSUE THREAD

**Issue by surajchopra1234** [angular/angular#54117] opened 2024-01-27 16:38 UTC
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

Encountering a **NullInjectorError: No provider for _RadioControlRegistry!** error when using an **input type="radio"** element within a component that is defer loaded using the **@ defer block** in Angular. This issue seems to prevent radio button functionality within defer-loaded components

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/~/github.com/surajchopra1234/demo

### Please provide the exception or error you saw

```true
ERROR NullInjectorError: R3InjectorError(Standalone[_AppComponent])[_RadioControlRegistry -> _RadioControlRegistry -> _RadioControlRegistry]: 
  NullInjectorError: No provider for _RadioControlRegistry!
    at NullInjector.get (core.mjs:5682:27)
    at R3Injector.get (core.mjs:6125:33)
    at R3Injector.get (core.mjs:6125:33)
    at R3Injector.get (core.mjs:6125:33)
    at ChainedInjector.get (core.mjs:15424:36)
    at lookupTokenUsingModuleInjector (core.mjs:4193:39)
    at getOrCreateInjectable (core.mjs:4241:12)
    at ɵɵdirectiveInject (core.mjs:12042:19)
    at NodeInjectorFactory.RadioControlValueAccessor_Factory [as factory] (forms.mjs:4766:127)
    at getNodeInjectable (core.mjs:4447:44)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 17.1.1
Node: 20.9.0
Package Manager: npm 10.2.3
OS: win32 x64

Angular: 17.1.1
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router, ssr

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1701.1
@angular-devkit/build-angular   17.1.1
@angular-devkit/core            17.1.1
@angular-devkit/schematics      17.1.1
@schematics/angular             17.1.1
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.3
```

**Comment by JeanMeche** [comment] 2024-01-28 17:37
Hi, thanks for taking the time for providing a reproduction. 

I believe I have found the root cause and provided a fix in #54130

**Comment by AndrewKushnir** [comment] 2024-01-29 19:47
As Matthieu mentioned, the app should work correctly once PR https://github.com/angular/angular/pull/54130 lands. We are also working on an improvement for the `@defer` feature to resolve an issue described in #52876, which would allow using providers from NgModules imported in standalone components.

**Comment by alxhub** [comment] 2024-01-30 00:55
The root cause of this issue is #52876, so we'll close this as effectively a duplicate.

**Closed by alxhub** 2024-01-30 00:55 UTC
Labels: area: core, P3, core: defer
