### ISSUE TITLE
Using router.navigate  to navigate to another component does not invoke the onInit method 

### ISSUE THREAD

**Issue by chinna-magapu** [angular/angular#18254] opened 2017-07-20 15:12 UTC
Hi I am implementing a project in angular . and i am using the version ng-version="4.3.0" 
Here i am redirecting the app to another component doesnt invoking the oninit  method

Here is my sample code 
```
`fblogin() {
        const provider = 'facebook';
        this.socialloginservice.onFacebookLogin().subscribe(
            response => {
                this.authService.socialSignup(provider, response).subscribe(res => {
                    console.log(this.authService.getToken());
                    console.log('redirecting');
                    this._router.navigate(['/register-step2']);
                });

            },
            error => console.log(error)
        );
    }` 

```

I am redirecting the app to another route in the success of an http service call
## Current behavior
In Register step2 component
```
constructor(private authenticateservice: AuthenticateService,
              ) {
     console.log('ok Working');

  }

ngOnInit() {
 //not working
}
```

## Expected behavior

```
constructor(private authenticateservice: AuthenticateService,
              ) {
     console.log('ok Working');

  }

ngOnInit() {
 //should work
}

```

i have checked for this issue in the web and i found the articles like below saying to add below scripts
<script src="node_modules/angular2/bundles/angular2-polyfills.js"></script>
<script src="node_modules/systemjs/dist/system.js"></script>

but i didn't have such folders in my node modules. i am not getting where to import these files and from where to import.
Please let me know where i am missing
**https://github.com/angular/angular/issues/4809**

## Environment

<pre><code>
Angular version: 4.3.0

Browser:
- [ ] Chrome (desktop) latest version

**Comment by limpep** [comment] 2017-07-20 15:19
On the component you are redirecting to, do you have `import { OnInit } from '@angular/core';` and `export class SomeComponent implements OnInit,` ?

**Comment by chinna-magapu** [comment] 2017-07-20 15:22
yes I am having the same Implementation here also
export class RegisterStep2Component implements OnInit {

}

**Comment by lecogiteur** [comment] 2017-07-20 16:18
Hi,

We have the same issue. Looks like it's working fine with Chromium but not with Firefox. 
The broken versions seem to be from the 4.2.0 upward (router package only), since the 4.1.3 works fine as well.

Thanks for your help.

**Comment by chinna-magapu** [comment] 2017-07-21 10:18
Hi I have solved my issue by doing this while navigating ,

` this.authService.socialSignup(provider, response).subscribe(res => {
                    console.log(this.authService.getToken());
                    console.log('redirecting');
                    **this.zone.run(() =>  this._router.navigate(['/register-step2']));**
                });`


Reference : 
https://stackoverflow.com/questions/35936535/angular-2-ngoninit-not-called 

Thanks.

**Comment by be-ndee** [comment] 2017-07-27 10:55
I have the same issue. Angular is running in a Cordova app for iOS. I tried the router-version 4.1.3 (like @lecogiteur said), and it worked. With my current version of 4.3.1 it didn't work.

The method @chinna-magapu provided (putting it into a `ngZone.run` call), works for me.

`this.ngZone.run(() => this.router.navigateByUrl(this.encodeURL(url)))`

Hopefully there will be a fix soon.

**Comment by caztial** [comment] 2017-08-05 05:45
I have the same issue but ngOnInti calls after 5- 10 seconds

**Comment by caztial** [comment] 2017-08-05 05:53
bug only happens only when you invoke a third party library such as facebook or firebase hope it will help to resolve the issue

**Comment by tytskyi** [comment] 2017-08-07 15:02
related: https://github.com/angular/angular/issues/17473

**Comment by abelepereira** [comment] 2017-09-25 18:02
I am also experiencing the same problem. Angular 4.2.4 here.
Replacing the navigation via routerLink with this.ngZone.run(() => ...)) solves the problem.

I am also loading data subscribing from a google/facebook authentication result (using angular2-social-login 3.1.1). Similar to what @caztial mentioned above.

**Comment by emmgfx** [comment] 2017-10-08 18:29
@abelepereira I just used your idea. It works well, but I don't understand why is th ngZone needed. The 5.0.0-rc1 behaviour is the same. You saved me a lot of time, thanks.

**Comment by maxer404** [comment] 2017-10-12 04:53
Same issue while working with Facebook JS SDK and is resolved by using NgZone. Hope Angular Team would find a better solution soon.

`FB.getLoginStatus(res => {
      if (res.status == 'connected') {
        this.appService.cacheData('accessToken', res.authResponse.accessToken);
        this.ngZone.run(() => {
          this.router.navigateByUrl('/facebook-analysis');
        });
      } else {
        FB.login(res => {
          console.log(res);
        });
      }
    });`

**Comment by Splaktar** [comment] 2017-11-15 07:36
Can anyone post a Plunkr of this?
Or can you post the contents of the ngOnInit() that is not working?

It really looks like a duplicate of https://github.com/angular/angular/issues/17473, but it's impossible to tell without seeing more complete examples.

**Comment by adamdport** [comment] 2017-11-30 22:19
I'm working with Cordova, and `ngOnInit` isn't firing (on the component being navigated to) even using the `[routerLink]` directive. The exact same anchor tag with `routerLink` inside a `mat-menu`, however, is working fine. If I use `(click)` with `router.navigate...` I can probably resolve the issue the same as everyone else here, but then I'd lose middle-click and ctrl-click functionality.

@Splaktar #17473 is interesting because I _am_ seeing this behavior in a lazily loaded module. However, it addresses _the order_ in which `ngOnInit` is fired, whereas this issue is about `ngOnInit` not firing at all.

**Comment by jasonaden** [comment] 2017-12-07 23:01
Without a reproduction for this issue, there's not much we can do. There's been a number of comments above requesting a reproduction, but there still isn't one available. I'll close this issue for now, but if someone can come up with a repro, please create a new issue and reference this one in the description.

We suggest using [StackBlitz](https://stackblitz.com/fork/angular-gitter), [Plunker](http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue) or [Github](https://github.com/new).

**Closed by jasonaden** 2017-12-07 23:01 UTC
Labels: comp: router

**Comment by dandrejvv** [comment] 2017-12-13 08:05
I don't know if I am doing something wrong but on Chrome I am getting this problem.

https://github.com/dandrejvv/spikes/tree/master/signalr-chat/signalr-chat-client

It is just some code that I am playing around with to try and understand how everything works so you can clone it and just run it from there.

**Comment by MatteoNY** [comment] 2017-12-19 22:07
Using 
Angular CLI: 1.6.1
Node: 9.2.0
OS: win32 x64
Angular: 5.1.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, service-worker

@angular/cdk: 5.0.1
@angular/cli: 1.6.1
@angular/flex-layout: 2.0.0-beta.12
@angular/material: 5.0.1
@angular-devkit/build-optimizer: 0.0.36
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.42
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.1
@schematics/angular: 0.1.11
@schematics/schematics: 0.0.11
typescript: 2.5.3
webpack: 3.10.0


Had to resort to window.location.href = "/login";
this.afAuth.auth.signOut(); it looks like Firebase is not logging out this.afAuth.auth.signOut();
There is a newer Firebase but had to downgrade had issues with install and looks like new types. 
When you call the signOut and refresh all works but not the best practice, prefer to navigate back to login or signout thank you page.  

To replicate the issue in my case you need to use Firebase auth (not Google email login). 
After you signUp with email you need to sendEmailVerification and then signOut you will not go back to the login page. If you have any navigation that uses authGuards they state you need to login but do not navigate to the login page. It's like a dead app. It appears that the router has some type of issue. When you tell the router to navigate to to a route it should be a no-brainier "go".  Looking at the router debug it tries to go where you want and then changes it's own back to root ('/"). 
Sorry it's quite complex to post to StackBlitz. I hope the above is some help.

**Comment by rafalkaczmarek** [comment] 2017-12-20 13:49
I`m using angular 5.1.1 with foundation 6 and problem occurs for me too.

If I run redirect from jquery event like that:
```
$('#globalModal').on('closed.zf.reveal', () => {
     this.router.navigate(['/welcome/signIn']);
 });
```

angular is silently break (looks like it is redirect but not reloading). Component constructor is called but onInit method not.

But if i run this without jquery everything works perfectly fine.

Quick workaround that im not proud of is to use window:
window.location.assign('/welcome/signIn');

**Comment by vladimiry** [comment] 2017-12-20 13:53
**rafalkaczmarek** wrapping into `zone.run` is supposed to help as well.

**Comment by lakerko** [comment] 2017-12-30 21:27
I have the same issue and the `zone.run` helped, thank you.

**Comment by SirZach** [comment] 2018-01-19 23:49
I've been able to reproduce this issue when using Firebase to handle authentication
```
 this.$auth.login()
      .then((user: User) => {
          this.router.navigate(['dinners', user.uid]);
      });
```
Did not work. Instead, I would get an error about the Url Matcher not being able to make a match. If I paused the code and resumed, the app would catch up and I don't encounter the problem. Doing
```
    this.zone.run(() => {
      this.router.navigate(['dinners', user.uid])
    });
```
Also solves the problem but is definitely a hack.

**Comment by babusurendra** [comment] 2018-01-27 04:57
Hi, @jasonaden  here is the reproduction stack blitz url.
[https://stackblitz.com/edit/dependencyinjcttest](url)

**Comment by mlc-mlapis** [comment] 2018-01-27 09:14
@babusurendra ... what? ... look at `ngOnInIt()` hook! JS is case-sensitive! Has to be `ngOnInit()` and then it works as expected.
```
ngOnInIt() {
   alert();
   this.myuser = this.appser.username();
   this.usernamefun(this.myuser);
}
```

**Comment by simeyla** [comment] 2018-02-01 03:38
@mlc-mlapis You're absolutely right about it being case sensitive and needing to be exactly like that - and incidentally you don't need to implement anything - but what are you talking about here! Unless someone edited an answer you're the first person in this thread to use the casing `ngOnInIt` !

**Comment by trotyl** [comment] 2018-02-01 04:42
@simeyla You can delete your comments too.

**Comment by Devniz** [comment] 2018-02-07 22:27
Make sure you have `<route-outlet></route-outlet>` inside app.component.html. This should work just fine with the latest version of Angular 5.

**Comment by lakerko** [comment] 2018-02-08 18:37
@Devniz it's `<router-outlet></router-outlet>` and it has nothing to do with the issue.

**Comment by NizarBousebsi-awin** [comment] 2018-02-08 20:04
@lakerko You are right it is `router-outlet`. However it does has something to do with this issue, if you miss this, the router won't know from where to navigate. I googled this issue, found this post and realized that I missed the `<router-outlet></router-outlet>`, after that, it worked fine. So this is definitely a valid answer which may help other people doing this mistake.

**Comment by ivancas84** [comment] 2018-02-23 17:53
ngZone don't work for me in angular 5, i fix it with:

```
this.router.routeReuseStrategy.shouldReuseRoute = function(){ return false; };

    this.router.events.subscribe((evt) => {
      if (evt instanceof NavigationEnd) {
          this.router.navigated = false;
          window.scrollTo(0, 0);
      }
    });

    this.router.navigateByUrl('/' + this.entity + '-show?sid=' + sid)
```

package.json
{
  "name": "prueba",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^5.1.2",
    "@angular/cdk": "^5.0.2",
    "@angular/common": "^5.0.0",
    "@angular/compiler": "^5.0.0",
    "@angular/core": "^5.0.0",
    "@angular/forms": "^5.0.0",
    "@angular/http": "^5.0.0",
    "@angular/material": "^5.0.2",
    "@angular/platform-browser": "^5.0.0",
    "@angular/platform-browser-dynamic": "^5.0.0",
    "@angular/router": "^5.0.0",
    "@ng-bootstrap/ng-bootstrap": "^1.0.0",
    "core-js": "^2.4.1",
    "rxjs": "^5.5.2",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "@angular/cli": "1.5.4",
    "@angular/compiler-cli": "^5.0.0",
    "@angular/language-service": "^5.0.0",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "^4.0.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.2.0",
    "tslint": "~5.7.0",
    "typescript": "~2.4.2"
  }
}

**Comment by GregKass** [comment] 2018-02-27 20:07
Is this related to https://github.com/angular/angular/issues/10178?

I had an issue where the URL was updating in the nav bar, but the navigated page wouldn't load. The solution from the linked issue is to do (and worked for me):

```
this._router.navigate(['/register-step2'], { relativeTo: this.route });
```

making sure you import and inject ```ActivatedRoute``` from ```@angular/router```

**Comment by babarxm** [comment] 2018-04-10 10:01
@be-ndee solved the problem. thanks man :)

**Comment by aoancea** [comment] 2018-06-03 17:47
I've had the same issue and the answers in these thread helped me. Just a bit of input.

This works perfectly without having any 3rd party calls

```
submit(): void {

	var self = this;

	self.router.navigate(['/home']);
}
```

After you're adding 3rd party calls this goes sideways
```
submit(): void {

	var self = this;

	self.router.navigate(['/home']);

	let data = { title: this.title, content: this.content };

	this.ipfsService.ipfs.addJSON(data, (err, hash) => {

		if (err)
			console.log(err);

		console.log("Saved to IPFS", data);
		console.log("IPFS hash:", hash);

		self.hashStoreContract.instance.save(hash, { gas: 300000 }, function (err, bidResult) {
			if (err) {
				console.log(err);
			} else {
				console.log('hash saved in blockchain!');

				self.router.navigate(['/home']);
			}
		});
	});
}
```

So to fix it, I've added NgZone

```
import { Component, OnInit, NgZone } from '@angular/core';

...

submit(): void {

	var self = this;

	let data = { title: this.title, content: this.content };

	this.ipfsService.ipfs.addJSON(data, (err, hash) => {

		if (err)
			console.log(err);

		console.log("Saved to IPFS", data);
		console.log("IPFS hash:", hash);

		self.hashStoreContract.instance.save(hash, { gas: 300000 }, function (err, bidResult) {
			if (err) {
				console.log(err);
			} else {
				console.log('hash saved in blockchain!');

				self.ngZone.run(() => {
					self.router.navigate(['/home']);
				});
			}
		});
	});
}
```

**Comment by wangzhenhui1992** [comment] 2018-10-04 05:06
> Same problem in Angular 5.2.10. Still not working anything for me.

Me too

**Comment by joebrassi** [comment] 2018-11-29 13:45
Same issue still happening in Angular 6.

**Comment by george43g** [comment] 2019-01-07 06:33
Has this been fixed yet? I think the cause of the issue is quite obvious - any 3rd party method/callback/promise causes router to not work. And the only way to fix is to use NgZone.
Pausing the code in the debugger and resuming it right away also makes the router work.
Surely the Angular team could fix this by now? I nearly killed my whole project not being able to fix this issue for weeks. It really hurt, bad. Esp, for a newbie who's just learning, it's almost traumatic.

**Comment by george43g** [comment] 2019-01-27 07:08
> Curious if your problem is 'fixed' by just using setTimeout(() => { router..... }, 0). That may look nicer on the eye.

That is quite possibly an amazing solution.

**Comment by sims34** [comment] 2019-02-01 00:10
Same problem for me i use Angular 6 on Ionic v4 this code in `goBach()` function doesn't work.
```
 goBack() : void{
      this.ngZone.run(() => {
        this.router.navigate(['/users'], { relativeTo: this.route });
      });
```
Someone can help me please

**Comment by alphagamer7** [comment] 2019-02-16 05:09
> Same problem for me i use Angular 6 on Ionic v4 this code in `goBach()` function doesn't work.
> 
> ```
>  goBack() : void{
>       this.ngZone.run(() => {
>         this.router.navigate(['/users'], { relativeTo: this.route });
>       });
> ```
> Someone can help me please

same issue for Ionic 4 and Angular 7

**Comment by sivadinesh1** [comment] 2019-02-22 03:10
Same issue angular 7 and Ionic 4

**Comment by cesarjuniort** [comment] 2019-03-04 17:09
Same issue with Angular 7 and PrimeNG

**Comment by AbderrahimSoubaiElidrissi** [comment] 2019-04-01 15:48
Same for Angular 5.2.11

**Comment by Drvanon** [comment] 2019-04-23 21:44
Also having the issue with 7.2.2 in ionic.

**Comment by fsanchezsw** [comment] 2019-06-10 10:03
Using ionViewWillEnter instead of ngOnInit or AfterViewInit worked for me.
