### ISSUE TITLE
Angular.dev: Lorem Ipsum on Migrations

### ISSUE THREAD

**Issue by davidlj95** [angular/angular#52573] opened 2023-11-07 09:42 UTC
### Describe the problem that you experienced

Migrations overview page on new angular.dev site contains Lorem ipsum text for description & each of migrations presented in there

### Enter the URL of the topic with the problem

https://angular.dev/reference/migrations

### Add a screenshot if that helps illustrate the problem

![image](https://github.com/angular/angular/assets/8050648/7afd3a01-072f-4387-a945-17b9929d6c20)

**Comment by twerske** [comment] 2023-11-09 00:37
Good catch ;) 

This is a good first issue if anyone is interested contributing!

**Comment by Captainnik53** [comment] 2023-11-09 11:03
@twerske I would like to work on this issue. Can you please assign this issue to me?

**Comment by Gortyser** [comment] 2023-11-09 17:22
@Captainnik53 you can just raise a PR, this is the way

**Comment by twerske** [comment] 2023-11-29 19:31
Closing as duplicate of https://github.com/angular/angular/pull/53186

**Comment by alan-agius4** [comment] 2023-12-11 19:06
Closed via https://github.com/angular/angular/pull/53186

**Closed by alan-agius4** 2023-12-11 19:06 UTC
Labels: help wanted, state: has PR, good first issue, P2, area: adev
