### ISSUE TITLE
a11y: Applying routerLink directive to mat-button-toggle breaks keyboard tab navigation

### ISSUE THREAD

**Issue by bjmc** [angular/angular#51384] opened 2023-08-16 13:20 UTC
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

No

### Reproduction info

**Instructions**

- Load the application on a computer with a keyboard
- Press the TAB key repeatedly to advance selection from start->off->on->end
- Hold the SHIFT key and press TAB repeatedly to move through the elements in reverse order
    
**Expected and Actual behavior.**

**Expected:** shift+tab will allow moving backwards from End->On->Off->Start
**Actual:** Selection gets "stuck" at the "on" button

There seem to be duplicate tab stops set on the same element (note numbers 0, 2, 4 – 1 and 3 are obscured) *screenshot from [TabA11y](https://chrome.google.com/webstore/detail/taba11y/aocppmckdocdjkphmofnklcjhdidgmga)*

![Screenshot from 2023-08-16 14-09-32](https://github.com/angular/angular/assets/328557/b64252d4-734b-4a98-a849-1394ec19c3e5)

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-1nlukm?file=src%2Fmain.ts

### Please provide the exception or error you saw

Shift+tab navigation gets "stuck" on the first mat-button-toggle element encountered.

Removing the `routerLink` directive restores navigation.

### Please provide the environment you discovered this bug in (run `ng version`)

```true
{
  "name": "stackblitz-starters-1nlukm",
  "version": "0.0.0",
  "private": true,
  "dependencies": {
    "@angular/animations": "^16.2.0",
    "@angular/cdk": "16.2.0",
    "@angular/common": "^16.2.0",
    "@angular/compiler": "^16.2.0",
    "@angular/core": "^16.2.0",
    "@angular/forms": "^16.2.0",
    "@angular/material": "^16.2.0",
    "@angular/platform-browser": "^16.2.0",
    "@angular/platform-browser-dynamic": "^16.2.0",
    "@angular/router": "^16.2.0",
    "@types/jasmine": "^4.3.5",
    "rxjs": "^7.8.1",
    "tslib": "^2.6.1",
    "zone.js": "^0.13.1"
  },
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1100.4",
    "@angular/cli": "~11.0.4",
    "@angular/compiler-cli": "~11.0.4",
    "@types/jasmine": "~3.6.0",
    "@types/node": "^12.11.1",
    "codelyzer": "^6.0.0",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~5.1.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.0.3",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~4.0.2"
  }
}
```

### Anything else?

Possibly related to https://github.com/angular/angular/issues/28345

**Comment by atscott** [comment] 2023-08-16 14:38
Indeed, this is a duplicate of #28345

**Closed by atscott** 2023-08-16 14:38 UTC

**Comment by bjmc** [comment] 2023-08-16 14:47
That one is tagged as a feature request (enabling non-focusable routerLinks) but IMHO this is actually a bug that breaks accessibility standards. Would you be interested in a bugfix that avoids the creation of redundant tabstops (without the more general feature of making this behavior configurable)?

**Comment by atscott** [comment] 2023-08-16 15:04
> Would you be interested in a bugfix that avoids the creation of redundant tabstops (without the more general feature of making this behavior configurable)?

We're open to PRs but do note that the addition of a tab index is required for accessibility in many cases. Detecting whether it should be added or not might prove difficult. A specific opt-out would likely be easier.
