### ISSUE TITLE
RC 6 Reactive Forms doesn't support disabled binding

### ISSUE THREAD

**Issue by naveedahmed1** [angular/angular#11324] opened 2016-09-04 16:34 UTC
I recently upgraded my project to RC 6. In my app we are using Reactive Forms. Among form fields there is a field which needs to be conditionally disabled.

Prior to RC 6 we were able to achieve this by applying disabled like like this.

`<input formControlName="myField" type="text" [disabled]="form.controls.otherField.value">`

After upgrade when I browse to that component, I see below warning in console.

```
It looks like you're using the disabled attribute with a reactive form directive. If you set disabled to true
      when you set up this control in your component class, the disabled attribute will actually be set in the DOM for you. We recommend using this approach to avoid 'changed after checked' errors.
       
      Example: 
      form = new FormGroup({
        first: new FormControl({value: 'Nancy', disabled: true}, Validators.required),
        last: new FormControl('Drew', Validators.required)
      });
```

I believe the the option to disable form field should be supported with Reactive Forms as well.

Currently to overcome this warning, we have to capture change event on otherField

`(change)="onChange()"`

```
onChange() {
        if (this.form.controls['otherField'].value) {
            this.form.controls['myField'].disabled = true;
        } else {
            this.form.controls['myField'].disabled = false;
        }
    }
```

**Comment by ericmartinezr** [comment] 2016-09-04 20:55
https://github.com/angular/angular/issues/11271#issuecomment-244507976

**Comment by kara** [comment] 2016-09-08 19:06
This looks like a dupe of #11271.

**Closed by kara** 2016-09-08 19:06 UTC
Labels: comp: forms

**Comment by Krisa** [comment] 2016-09-10 10:57
@kara this issue is indeed a dupe, but https://github.com/angular/angular/issues/11271 is closed too. Shall it not be reopened, or are you not (re)considering to support the disabled attribute again?

**Comment by nildomacena** [comment] 2016-09-22 13:21
You also can use the function enable() or disable()

**Comment by alobban** [comment] 2017-06-21 20:57
@nildomacena how do I use the enable() and disable()?

**Comment by ravikumarbggit** [comment] 2017-07-20 07:25
I could disable in the FormBuilder like this:

id:[{value:'1', disabled:true}]

However my problem is ngSubmit is not sending back value of this disabled field. it will be undefined for id

save(model : any ) : void {
        this.countries = model.countries;    
        for(let c of this.countries){
             console.log(c.id+':'+c.name+':'+c.deleted);
         }
    } 

How can I access the value of disabled field?

**Comment by chriso86** [comment] 2018-02-09 12:07
This is pretty horrible.

**Comment by walhow** [comment] 2018-04-17 17:58
choui's solution works fine! That said, I do wish there was a property in the view I could bind to, to avoid all the component code.

// works:
for(let prop in this.form.controls){
  this.myForm.controls[prop].disable({onlySelf: true })  // or .enable(...)
}
