### ISSUE TITLE
Angular 5 - "Error: Cannot activate an already activated outlet" when named outlets are used in children

### ISSUE THREAD

**Issue by gigadie** [angular/angular#20694] opened 2017-11-29 18:06 UTC
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
As stated [here on stackoverflow](https://stackoverflow.com/questions/45650031/angular-4-error-cannot-activate-an-already-activated-outlet) when you have a routing configuration like:
```
export const routes = [
{
    path: '',
    component: IndexComponent, 
    children: [
        {
            path: 'home',
            children: [
                { path: '', component: FirstComponent, outlet: 'first', data: { state: 'a' } },
                { path: '', component: SecondComponent, outlet: 'second', data: { state: 'b' } }
            ]
        },
        {
            path: 'about', 
            children: [
                { path: '', component: FirstComponent, outlet: 'first', data: { state: 'b' } },
                { path: '', component: SecondComponent, outlet: 'second', data: { state: 'a' } }
            ]
        }
    ]
}
```
And you are navigating from `/home` to `/about` using a link `<a routerLink="['/about']">about</a>` it throws the following error:
```
ERROR Error: Uncaught (in promise): Error: Cannot activate an already activated outlet
Error: Cannot activate an already activated outlet
``` 

## Expected behavior
The expected behavior would be that it navigates to `/about` and the router populates the named outlets with the new components (taking internally care of deactivation/activation of outlets). 

## Minimal reproduction of the problem with instructions
Just a simple app, with routing a named outlets with the configuration above.

## What is the motivation / use case for changing the behavior?
It's a show stopper.

## Environment

<pre><code>
Angular version: 5.0.3

Browser:
- [x] Chrome (desktop) version XX
- [x] Chrome (Android) version XX
- [x] Chrome (iOS) version XX
- [x] Firefox version XX
- [x] Safari (desktop) version XX
- [x] Safari (iOS) version XX
- [x] IE version XX
- [x] Edge version XX
 
Others:

</code></pre>

**Comment by gigadie** [comment] 2017-11-30 15:38
I submitted the PR above which enables the use case described in the issue, without throwing an error.
I'm waiting to understand how to fix the `cla: no` flag at the moment.

Cheers

**Comment by Riobe** [comment] 2017-12-18 21:09
We've adopted angular at my place of work, and we're relying on this technique for routing because we don't want to embed router-outlet information into the url. Until this works we'll have to rely on a fork of @angular/router that has the fix in the pull request in it to keep moving forward.

I guess it's a more involved way of +1'ing, but I just want it clear that there are others that need this fix too.

**Comment by wboevink** [comment] 2017-12-20 11:55
I've got the same error, applying the suggested fix made it only worse (for me).
The solution was in this case removing the  component: IndexComponent, or adding a router outlet to the IndexComponent. 

I think throwing the error is still the correct way.

**Comment by ernestbofill** [comment] 2018-02-09 14:22
You need to change a little bit you routes. One of the 2 child routs should not be named. And of course the IndexComponent should also have a `<router-outlet>` without name + another with name
```
export const routes = [
{
    path: '',
    component: IndexComponent, 
    children: [
        {
            path: 'home',
            children: [
                { path: '', component: FirstComponent, data: { state: 'a' } },
                { path: '', component: SecondComponent, outlet: 'second', data: { state: 'b' } }
            ]
        },
        {
            path: 'about', 
            children: [
                { path: '', component: FirstComponent, data: { state: 'b' } },
                { path: '', component: SecondComponent, outlet: 'second', data: { state: 'a' } }
            ]
        }
    ]
}
```

**Comment by daniekpo** [comment] 2018-03-26 15:48
I applied the suggested fix and it fixed the issue for me. I'm not sure what the implications are though. I hope the Angular team accept the PR or at least let us know what their recommended workaround/fix is.

**Comment by nihique** [comment] 2018-04-04 09:24
We have also same problem and fix above helps, what are the plans for merge?

**Comment by oudekaas** [comment] 2018-04-16 14:33
Just to be sure does the solution not work without earlier version of Node?
I can't find packages/router/src/directives/router_outlet.ts I only have /router/src/directives/router_outlet.d which is different. I might try to put a second named outlet below the first outlet and then just open an empty component in the first and open the new one in the the other outlet. Is there a way to manually deactivate the outlet in later Node versions?

**Comment by JHinW** [comment] 2018-04-23 16:37
...Ah, Do not add <route-outlet></route-outlet> to any **Structural Directive**(such as  ngIF), angular cannot deactivate children component of <route-outlet/> if it is not rendered 😆

**Comment by sashagrunge** [comment] 2018-04-25 14:38
Have the configs similar to the follows, it works for me. No errors even without fixes. 

**app-routing.ts**
@NgModule({
  imports: [
    RouterModule.forRoot(
      APP_ROUTES,
      APP_ROUTES_EXTRA_OPTIONS
    ),
    DashboardModule
  ],
  exports: [
    RouterModule
  ],
  providers: []
})

**dashboard-routing.ts**

const ROUTES: Routes = [
  { path: '', component: MainMenuComponent, outlet: 'menu', pathMatch: 'full' },
  { path: 'dashboard', children: [
    { path: '', component: MainMenuComponent, outlet: 'sectionMenu' },
    { path: 'account', loadChildren: '../account/account.module#AccountModule'}
  ]}
];

**acount-routing.ts**
const ROUTES: Routes = [
  { path: '', component: AccountMenuComponent, outlet: 'sectionMenu'},
  { path: ':id',
    component: AccountDashboardComponent,
    children: [
      {
        path: 'profile',
        loadChildren: '../account-profile-page#AccountProfilePageModule'
      }
    ]
  }
];

**Comment by alexma01** [comment] 2018-04-26 22:41
solved this issue?

**Comment by maximew** [comment] 2018-05-16 06:28
Same problem here … Any fixes ?

**Comment by nofear87** [comment] 2018-06-27 08:46
found a working workaround here: https://github.com/angular/angular/pull/20712#issuecomment-398351773

**Comment by Kiennyo** [comment] 2018-07-26 10:16
Any update on this ?

**Comment by aakashgarg19** [comment] 2018-08-21 04:28
Any updates on this. Facing the same issue. I believe the fix suggested by @gigadie  is not merged till now.

**Comment by StevenLiekens** [comment] 2018-08-23 11:11
It would be better if someone could investigate how it's possible that named outlets remain activated after navigating away from them.

**Comment by dontboyle** [comment] 2018-09-10 19:57
This a popular ignore case (seems like) or.....?

**Comment by Karankang007** [comment] 2018-09-21 14:58
@dontboyle  I am facing the same issue as well, when using lazy loaded routes as children.

**Comment by aakashgarg19** [comment] 2018-09-25 08:01
I was able to get rid of this issue by correcting my router configuration. I included one router outlet where i wanted to load the module then another router-outlet in parent component of lazy loaded module to load its child components. I my case i am using nested router outlets instead of named router outlets to maintain the sanity of URLs.
My New Structure :- 
          AppComponent
                  --router-outlet
                         --AnotherComponent
                                --router-outlet
                                       --AnotherComponent2(Home Component of lazy loaded module)
                                              --router-outlet(where all other components of lazy loaded module will be displayed)

**Comment by dontboyle** [comment] 2018-10-10 12:30
@Karankang007 Similar to @aakashgarg19 I change the router file around. Check yours.

**Comment by Niaro** [comment] 2018-12-18 19:12
Come on, guys! It's been more than one year since creating of the issue! >_<

**Comment by crupest** [comment] 2019-03-08 17:40
Any progress on this?👀
I attempt to create a dialog with named route in it. But it keeps error.

**Comment by JHinW** [comment] 2019-03-31 05:13
hi, why no details about the how and where you put your `<route-outlet></route-outlet>`, which is important because `<route-outlet></route-outlet>` should be kept in your dom without damage operations like (container.remove, or NgIF directives wrapped).

hope is helps.

**Comment by mehmettkocc** [comment] 2019-04-29 00:53
In my situation, Angular misactivated a child route, path changed and Angular tried to reactivate it again. The temporary solution is to attach to that problematic router-outlet's activate event, check the activation logic yourself and if the logic fails, call deactivate on the RouterOutlet instance.

```html
<router-outlet #ro="outlet" (activate)="_routerOutletActivated(ro)"></router-outlet>
```

```ts
_router: Router;
_routerOutletActivated(ro: RouterOutlet) {
  if (!_shouldActivate(_router.url))
    ro.deactivate();
}
```

**Comment by dao1202** [comment] 2019-06-24 10:56
> In my situation, Angular misactivated a child route, path changed and Angular tried to reactivate it again. The temporary solution is to attach to that problematic router-outlet's activate event, check the activation logic yourself and if the logic fails, call deactivate on the RouterOutlet instance.
> 
> ```
> <router-outlet #ro="outlet" (activate)="_routerOutletActivated(ro)"></router-outlet>
> ```
> 
> ```ts
> _router: Router;
> _routerOutletActivated(ro: RouterOutlet) {
>   if (!_shouldActivate(_router.url))
>     ro.deactivate();
> }
> ```

What method is _shouldActivate ? can you post this also please?

**Comment by REPTILEHAUS** [comment] 2019-07-02 09:30
Also hitting this issue, but only when webpack recompiles and on screen load i get Cannot activate an already activated outlet albeit using Ionic 4/Angular.

**Comment by RaschidJFR** [comment] 2019-09-09 07:45
This guy's got a working answer: https://stackoverflow.com/a/55742986/3000466.
The workaround is deactivating manually the router on each event:

```
ngOnInit(): void {
    this.router.events.subscribe(e => {
      if (e instanceof ActivationStart && e.snapshot.outlet === "outletname")
        this.outlet.deactivate();
    });
```

**Comment by Rlcolli4** [comment] 2019-10-11 16:37
Any update on this? We are having this problem trying to set up our logout/relogin for users and our dialog outlet is having this issue.

**Comment by aakashgarg19** [comment] 2019-10-11 17:07
> Any update on this? We are having this problem trying to set up our logout/relogin for users and our dialog outlet is having this issue. We are running Angular 8!
> <img alt="Screen Shot 2019-10-11 at 9 38 39 AM" width="498" src="https://user-images.githubusercontent.com/12074293/66668817-f114a180-ec0a-11e9-9b6c-c3d6e1213adb.png">

https://github.com/angular/angular/issues/20694#issuecomment-424245085

**Comment by chimung** [comment] 2019-11-17 10:15
> > hi, why no details about the how and where you put your `<route-outlet></route-outlet>`, which is important because `<route-outlet></route-outlet>` should be kept in your dom without damage operations like (container.remove, or NgIF directives wrapped).
> > hope is helps.
> 
> Hello, refer to this video for understanding how route config works and where to put the router outlet.
> https://www.youtube.com/watch?v=LaIAHOSKHCQ

But it seems to not mention how to work with multiple outlet

**Comment by Zarepheth** [comment] 2019-11-20 17:24
@aakashgarg19 
> 
> My New Structure :-
> ![image](https://user-images.githubusercontent.com/13452345/46000993-ce7b1d80-c0c7-11e8-9cfd-dc9d65c84ce0.png)

My routing tree already looks like that - but with additional levels of lazy-loading (and the tree configuration is split into separate files at the lazy-load boundaries). And I'm still getting this error with no named outlets and nested primary outlets.

**Comment by rodlandA** [comment] 2020-02-06 07:59
Hi, struggled a while with this myself, but found a way to structure my routes so that the issue no longer occurred, have posted an example of my routes below,  hope this can help some of you.

`const routes: Routes = {
    path: ':pid',
    component: ViewComponent,
    resolve: {
      project: ProjectResolver,
    },
    children: [
      {
        path: '',
        children: [
          {
            path: '',
            component: InfoComponent,
          },
          {
            path: '',
            component: InfoComponent,
            outlet: 'tabcontent',
          },
        ]
      },
      {
        path: 'contract',
        resolve: {
          contracts: ContractsResolver,
        },
        children: [
          {
            path: '',
            component: ContractsComponent
          },
          {
            path: '',
            component: ContractsComponent,
            outlet: 'tabcontent',
          },
        ]
      },
      {
        path: 'contract/new',
        resolve: {
          contract: ContractResolver,
        },
        children: [
          {
            path: '',
            component: ContractComponent,
          },
          {
            path: '',
            component: ContractComponent,
            outlet: 'tabcontent'
          }
        ]
      },
      {
        path: 'contract/:cid/edit',
        resolve: {
          contract: ContractResolver,
        },
        children: [
          {
            path: '',
            component: ContractComponent,
          },
          {
            path: '',
            component: ContractComponent,
            outlet: 'tabcontent'
          }
        ]
      },
      {
        path: 'contract/:cid',
        resolve: {
          contract: ContractResolver,
        },
        children: [
          {
            path: '',
            component: ContractComponent,
          },
          {
            path: '',
            component: ContractComponent,
            outlet: 'tabcontent'
          }
        ]
      },
      {
        path: 'tenancy',
        resolve: {
          tenancies: TenanciesResolver,
        },
        children: [
          {
            path: '',
            component: TenanciesComponent
          },
          {
            path: '',
            component: TenanciesComponent,
            outlet: 'tabcontent',
          }
        ]
      },
      {
        path: 'tenancy/new',
        resolve: {
          tenancy: TenancyResolver,
        },
        children: [
          {
            path: '',
            component: TenancyComponent,
          },
          {
            path: '',
            component: TenancyComponent,
            outlet: 'tabcontent'
          }
        ]
      },
      {
        path: 'tenancy/:tid/edit',
        resolve: {
          tenancy: TenancyResolver,
        },
        children: [
          {
            path: '',
            component: TenancyComponent,
          },
          {
            path: '',
            component: TenancyComponent,
            outlet: 'tabcontent'
          }
        ]
      },
      {
        path: 'tenancy/:tid',
        resolve: {
          tenancy: TenancyResolver,
        },
        children: [
          {
            path: '',
            component: TenancyComponent,
          },
          {
            path: '',
            component: TenancyComponent,
            outlet: 'tabcontent'
          }
        ]
      },
      {
        path: 'file',
        children: [
          {
            path: '',
            component: FilesComponent
          },
          {
            path: '',
            component: FilesComponent,
            outlet: 'tabcontent',
          }
        ]
      },
      {
        path: 'object',
        children: [
          {
            path: '',
            component: ObjectListComponent,
          },
          {
            path: '',
            component: ObjectListComponent,
            outlet: 'tabcontent',
          },
        ]
      },
    ]
  },`

**Comment by coroiu** [comment] 2020-03-06 10:35
The suggestion above finally solved it for me. It seems like the angular router doesn't deactivate named router outlets if it can't first deactivate an un-named one, even if the un-named router-outlet doesn't exist in the template. As long as it is present in the router configuraiton, it's gonna work. Ex:

This doesn't work:
```
export const routes: Routes = [
  { path: '', component: ShellComponent, children: [
    { path: 'child-route', children: [
      { path: '', outlet: 'named-outlet', component: ChildComponent }
    ]},
    { path: '', children: [
      { path: '', outlet: 'named-outlet', component: DefaultComponent }
    ]}
  ]}
];
```

But this does:
```
@Component({ template: '' })
export class EmptyComponent {}

export const routes: Routes = [
  { path: '', component: ShellComponent, children: [
    { path: 'child-route', children: [
      { path: '', component: EmptyComponent },
      { path: '', outlet: 'named-outlet', component: ChildComponent }
    ]},
    { path: '', children: [
      { path: '', component: EmptyComponent },
      { path: '', outlet: 'named-outlet', component: DefaultComponent }
    ]}
  ]}
];
```

**Comment by Malte-BMT** [comment] 2020-04-20 08:36
Finally! Adding a primary (unnamed), empty router-outlet to my template completely fixed it. Thank you

**Comment by themizzi** [comment] 2020-04-25 06:39
Having the same problem and trying not to make our routing messier and having to embed multiple outlet state into our urls. The idea in the PR above works for us (Angular 9.0.6). Any chance there could be movement on this so we don't have to track our own fork for a one liner?

**Comment by pflugich** [comment] 2020-05-19 15:21
> Finally! Adding a primary (unnamed), empty router-outlet to my template completely fixed it. Thank you

This and deactivating the router-outlets 'manually' on an ActivationStart as suggested in this issue fixed it for me. I have one router-outlet in a BottomSheet, which in my running solution is my primary outlet (unnamed). I'm running angular in v9.0.7, would be nice to know this fixed some day ;)

**Comment by aakashgarg19** [comment] 2020-05-19 15:44
> 
> 
> > Finally! Adding a primary (unnamed), empty router-outlet to my template completely fixed it. Thank you
> 
> This and deactivating the router-outlets 'manually' on an ActivationStart as suggested in this issue fixed it for me. I have one router-outlet in a BottomSheet, which in my running solution is my primary outlet (unnamed). I'm running angular in v9.0.7, would be nice to know this fixed some day ;)

This is sort of a hack and should not be used. Manual deactivation should not be done. If your router config is proper you will not face this issue and will not need this. Please refer to my answer for resolving this.
#20694 (comment)

Basically nested router outlet you can search if still there are some doubts.

**Comment by atscott** [comment] 2020-07-10 20:37
Confirmed in v10; Stackblitz repro: https://stackblitz.com/edit/angular-ivy-2xhhaz?file=src%2Fapp%2Fapp.module.ts

**Closed** 2021-01-06 21:49 UTC
Labels: P4, comp: router, freq2: medium, router: aux routes, router: config matching/activation/validation, state: confirmed, type: bug/fix
