### ISSUE TITLE
Empty path breaks routing and consequently SEO in a server side rendered Angular application

### ISSUE THREAD

**Issue by aleksander351** [angular/angular#57715] opened 2024-09-07 21:57 UTC
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

Yes

### Description

First of all, this worked in the past, when initialNavigation: "enabled", and relativeLinkResolution was still available. Probably Angular 13, back in 2021, something like that.

After that, we updated the project a couple of times of course. Currently on Angular 17 and upgraded from nguniversal to @angular/ssr.

The problem is as follows:

We want to be able to load a specific route, say a product page, products/1. And we want to set the proper Meta and SEO information. That is the reason we are using Angular SSR in the first place.

If we load, reload or SEO verify that specific route, the page source and the SEO results show the homepage information.
When we reload the page, we can also observe, that the homepage title appears in the browser tab for a split second, before it gets replaced by the product page title.

After some testing it turns out, if we change the homepage component to use a "home" route instead of an empty " " route, the product page information loads correctly. Furthermore, if we remove `</ion-router-outlet>` (also tested with `<router-outlet></router-outlet>`), the meta information also loads corretly in the page (even though the page doesn't load of course).

We use resolvers on the homepage to fetch some data, and we have another set of resolvers for the product page.

We don't use standalone components and we don't use child modules.

Changing the order of the routes, chaining resolvers, putting the Meta service inside the resolver had no effect.

### Please provide a link to a minimal reproduction of the bug

https://github.com/aleksander351/ionic7-ssr-basic

### Please provide the exception or error you saw

```true
There is no exception.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.3.9
Node: 20.14.0
Package Manager: npm 10.8.1
OS: win32 x64

Angular: 17.3.12
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1703.9
@angular-devkit/build-angular   17.3.9
@angular-devkit/core            17.3.9
@angular-devkit/schematics      17.3.9
@angular/cli                    17.3.9
@angular/ssr                    17.3.9
@schematics/angular             17.3.9
rxjs                            7.5.0
typescript                      5.2.2
zone.js                         0.14.10
```

**Comment by jnizet** [comment] 2024-09-08 06:54
Hi @aleksander351 

I tried to reproduce your issue with the provided minimal repro, but

- there is no home page/route in the repro, only a route for `folder/:id`. The home route redirects to `folder/Inbox`. So I don't understand which home page is supposed to be displayed for a short while instead of the folder page;
- running `ng build`, then `npm run build:ssr`, then `npm run serve:ssr`to build and run the server, and `http get http://localhost:4000/folder/Outbox` does show the Outbox page as expected.

Could you explain what we're supposed to do with the repro to actually reproduce your issue?

**Comment by atscott** [comment] 2024-09-08 21:39
In addition to the points above, please create a reproduction without ionic. If the reproduction requires ionic, this should be filed in the ionic repo rather than Angular.

**Comment by forestmaxime** [comment] 2024-09-09 04:04
Hi @jnizet & @atscott,

My company SSR app has a similar problem to what is being talked about in this issue and we ain't using ionic. We didn't have time to switch to standalone either and we still use what was working in Angular 12-14-16. Our app in prod (Angular 16) is working as expected but after upgrading to Angular 18 I no longer get my "home" component rendered using SSR (local & stg env), I even get issues with other routes, ex: '/myroute/:id'.

Fresh angular ssr app that I can reproduce the same bug as this issue: https://github.com/forestmaxime/angular-18-ssr-empty-path-bug

**Comment by atscott** [comment] 2024-09-09 04:15
@forestmaxime could you clarify what the reproduction is? What are the steps, what happens and what are you expecting? I don’t see any routes in that repo.

**Comment by forestmaxime** [comment] 2024-09-09 14:53
@atscott sure thing!

Repro:
- ng serve
- navigate to http://localhost:4200/
- app.component is rendered
- home.component is not rendered when it should

I forgot to commit (it was late!)

My routes are inside my app.module.ts and home.module.ts both using `path: ''`

**Comment by forestmaxime** [comment] 2024-09-09 19:27
@jnizet It was a networking issue on my end. Cloudflare rules was blocking calls in our STG env.

**Comment by atscott** [comment] 2024-09-10 16:02
Given the current set of information, I'm going to close this as unable to reproduce.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template that include info on how to create a reproduction using our template.

**Closed by atscott** 2024-09-10 16:02 UTC
Labels: needs reproduction, area: router

**Comment by aleksander351** [comment] 2024-09-10 20:33
I updated my repository but couldn't reproduce it. Even with Ionic it was working. Then I tried to find the difference and found inside the home component's OnInit method there was a call to a service that "waits" for the browser to load. I guess that was the problem. So far looking really good.

Thanks guys for all the responses. Couldn't be happier.

**Comment by aleksander351** [comment] 2024-09-14 21:45
@atscott I did a little bit more digging and found if the home component, which is on "" route, uses the same service as the product detail page component, the homepage loads somehow as well. Looks like some kind of circular dependency to me. Fact is, if the homepage has some other route, there is no conflict (conflict meaning reloading the detail page shows meta data of homepage in the page source).

tried something like this on the homepage component:

```
if (this.router.url === "/") {
   ... call some service // if I comment this out, detail page loads as it should
}
```

**Comment by aleksander351** [comment] 2024-09-14 23:56
@atscott 
I could narrow it down further. Somehow if I try to update the meta tags in the homepage component, or in the homepage resolver, they get loaded even if I reload the product page. Provided the route for homepage is "". If I set it to "home", it works. So now, I can have either meta tags on the homepage, or on the product page. Same if I put the meta service inside app component. So far the only way I see is to set some hard coded meta tags in the index.html and update them on the product page, with the downside that homepage meta info is not translated and it doesn't update after navigating to home.

**Comment by jnizet** [comment] 2024-09-15 07:05
@aleksander351 you should really provide a complete minimal reproduction. A description is too vague and not actionable.

**Comment by aleksander351** [comment] 2024-09-15 08:33
@atscott 
I could narrow it down further. Somehow if I try to update the meta tags in the homepage component, or in the homepage resolver, they get loaded even if I reload the product page. Provided the route for homepage is "". If I set it to "home", it works. So now, I can have either meta tags on the homepage, or on the product page. Same if I put the meta service inside app component. So far the only way I see is to set some hard coded meta tags in the index.html and update them on the product page, with the downside that homepage meta info is not translated and it doesn't update after navigating to home.

**Comment by aleksander351** [comment] 2024-09-15 21:00
> @aleksander351 you should really provide a complete minimal reproduction. A description is too vague and not actionable.

I was trying to reporoduce it locally but it works on the test branch.
First the meta tags were working correctly because I actually broke something on the homepage, so the meta service wasn't called.

After more testing I found my auth guard had a redirection to the home page, and wasnt checking for Platform Browser.

Thanks @jnizet
