### ISSUE TITLE
HTML is rendered in browser differently depending on if it's in a Component or not - No CSS Used

### ISSUE THREAD

**Issue by PerryCodes** [angular/angular#40464] opened 2021-01-17 21:57 UTC
# 🐞 bug report

### Is this a regression?

Yes, this behavior did not exist prior to version 6.

Here's an example of expected layout in version 5:  https://stackblitz.com/edit/angular-v5-jp

### Description

The following HTML renders in the browser window two different ways depending on whether or not it's in a Component. No CSS is used anywhere in the project.
```
<button>-</button>
<span>0</span>
<button>+</button>
```

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-v6-jp
Here's the same issue in the latest version: https://stackblitz.com/edit/angular-latest-jp

## 🔥 Exception or Error
Angular 5:
![image](https://user-images.githubusercontent.com/2401573/104857119-f49dda80-58db-11eb-88f6-85f78bca50d7.png)

Angular 6 and greater:
![image](https://user-images.githubusercontent.com/2401573/104857202-68d87e00-58dc-11eb-90c4-27eebc3d5eab.png)

## 🌍  Your Environment

**Angular Version:**
<pre><code>Angular CLI: 9.0.7
Node: 12.15.0
OS: win32 x64

Angular: 9.0.7
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.7
@angular-devkit/build-angular     0.900.7
@angular-devkit/build-optimizer   0.900.7
@angular-devkit/build-webpack     0.900.7
@angular-devkit/core              9.0.7
@angular-devkit/schematics        9.0.7
@ngtools/webpack                  9.0.7
@schematics/angular               9.0.7
@schematics/update                0.900.7
rxjs                              6.5.5
typescript                        3.7.5
webpack                           4.41.2</code></pre>

**Comment by petebacondarwin** [comment] 2021-01-18 12:08
This was a breaking change between v5 and v6 - see https://github.com/angular/angular/commit/f1a0632
There are couple of ways to workaround this

1. Apply `  preserveWhitespaces: true` in the component definition - https://stackblitz.com/edit/angular-latest-jp-hm48e2?file=src%2Fapp%2Fapp.component.ts
2. Add `&ngsp;` (not `&nbsp;`) characters to avoid the space being collapsed - https://stackblitz.com/edit/angular-latest-jp-zsvves?file=src%2Fapp%2Fapp.component.html
3. Place spaces within the `<span>` either side of the text, which will not be collapsed - https://stackblitz.com/edit/angular-latest-jp-eejyfc?file=src%2Fapp%2Fapp.component.html

In any case this is a duplicate of https://github.com/angular/angular/issues/21049

**Closed by petebacondarwin** 2021-01-18 12:08 UTC
