### ISSUE TITLE
Missing documentation for FormControl

### ISSUE THREAD

**Issue by szeinedd-nrel** [angular/angular#58371] opened 2024-10-25 21:17 UTC
### Describe the problem that you experienced

The documentation page for `FormControl` is essentially blank.

### Enter the URL of the topic with the problem

https://angular.dev/api/forms/FormControl

### Describe what you were looking for in the documentation

Something akin to https://v17.angular.io/api/forms/FormControl

**Comment by JoostK** [comment] 2024-10-25 21:35
Yeah, it's a known issue with the docs extractor for the new docs site. Closing as duplicate of #56144.

**Closed by JoostK** 2024-10-25 21:35 UTC
