### ISSUE TITLE
Cannot compile using Ivy: Failed to read entry point info -> ERROR in Failed to list lazy routes : app.module#AppModule routes: Unknown module 

### ISSUE THREAD

**Issue by bobskigit** [angular/angular#31218] opened 2019-06-23 13:52 UTC
### Description
I've enabled the ivy compiler flag and when I compile I get the following stream of error messages

WARNING in Failed to read entry point info from ../node_modules/npm/test/fixtures/config/package.json 
with error SyntaxError: Unexpected end of JSON input.

WARNING in Failed to read entry point info from ../node_modules/npm/test/fixtures/config/package.json 
with error SyntaxError: Unexpected end of JSON input.

ERROR in Failed to list lazy routes: Unknown module '../src/app/app.module#AppModule'.

## 🔥 Exception or Error
<pre><code>

ERROR in Failed to list lazy routes: Unknown module '../src/app/app.module#AppModule'.

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

<!-@angular-devkit/build-optimizer   0.800.3
@angular-devkit/build-webpack     0.800.3
@angular-devkit/core              7.3.9
@angular-devkit/schematics        8.0.3
@angular/cdk                      8.0.1
@angular/cli                      8.0.3
@angular/pwa                      0.800.3
@ngtools/webpack                  8.0.3
@schematics/angular               8.0.3
@schematics/update                0.800.3
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.30.0- ✍️-->

</code></pre>

**Comment by bobskigit** [comment] 2019-06-23 13:53
Angular Version

@angular-devkit/build-optimizer   0.800.3
@angular-devkit/build-webpack     0.800.3
@angular-devkit/core              7.3.9
@angular-devkit/schematics        8.0.3
@angular/cdk                      8.0.1
@angular/cli                      8.0.3
@angular/pwa                      0.800.3
@ngtools/webpack                  8.0.3
@schematics/angular               8.0.3
@schematics/update                0.800.3
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.30.0

**Comment by kara** [comment] 2019-06-24 14:44
@bobskigit Can you provide a bit more info? Like Angular version (above is just related packages, not @angular/core, etc), and what some of your code looks like?

**Comment by bobskigit** [comment] 2019-06-24 21:33
Its angular 8.1.0-next.3 of @angular/core.

Its a relatively large multi-language application around 100+ components, 50 or so services. It's been migrated from 6 to 7 to 8 over the last year. There are around 20 modules all loaded lazily, with a single shared common module. If I turn IVY off it compiles perfectly.

I have removed all the lazy loaded modules and the error is exactly the same, we also use DevExtreme from Devexpress for a large number of the UI widgets. 

Is it possible to run something to provide a better pinpoint for the errors?

**Comment by Tenvan** [comment] 2019-07-04 12:27
same here with 8.1:

```bash
10% building 3/3 modules 0 activeℹ ｢wds｣: Project is running at http://localhost:4200/webpack-dev-server/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: 404s will fallback to //index.html
                                                                                                                                               
chunk {main} main.js, main.js.map (main) 1.96 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 122 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.09 kB [entry] [rendered]
chunk {stimulsoft} stimulsoft.js, stimulsoft.js.map (stimulsoft) 8.77 MB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 5.74 MB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 338 kB [initial] [rendered]
Date: 2019-07-04T12:23:24.142Z - Hash: 008e0e87a0ddc69351cf - Time: 25131ms

ERROR in Failed to list lazy routes: Unknown module '/home/stira/Workspace/Node/EagleWeb/src/client/app/app.module#AppModule'.
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
ℹ ｢wdm｣: Failed to compile.
```

```bash
Angular CLI: 8.1.0
Node: 12.4.0
OS: linux x64
Angular: 8.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.801.0
@angular-devkit/build-angular      0.801.0
@angular-devkit/build-ng-packagr   0.801.0
@angular-devkit/build-optimizer    0.801.0
@angular-devkit/build-webpack      0.801.0
@angular-devkit/core               8.1.0
@angular-devkit/schematics         8.1.0
@angular/cdk                       8.0.2
@angular/flex-layout               8.0.0-beta.26
@angular/http                      7.2.15
@angular/pwa                       0.801.0
@ngtools/json-schema               1.1.0
@ngtools/webpack                   8.1.0
@schematics/angular                8.1.0
@schematics/package-update         0.7.5
@schematics/schematics             0.801.0
@schematics/update                 0.801.0
ng-packagr                         5.3.0
rxjs                               6.5.2
typescript                         3.4.5
webpack                            4.35.2

```

**Comment by jpleclerc** [comment] 2019-07-18 17:24
Same in 8.2.0-next.2

**Comment by alxhub** [comment] 2019-08-20 22:24
Closing as there is no viable reproduction so there's no way for us to act on this report. If you can provide a minimal reproduction (likely in the form of a Github repository) please free to open a new issue.

**Closed** 2019-08-20 22:24 UTC
Labels: comp: compiler, comp: ivy, freq1: low, severity3: broken, state: Needs repro, type: bug/fix

**Comment by tracyalison11** [comment] 2019-08-29 03:56
I was also seeing this error and resolved when I realized one of the feature components I was importing was wrong. I had renamed most of the feature and forgot to make the update in my app module folder.

**Comment by Splaktar** [comment] 2019-09-04 01:30
I am seeing this as well with `9.0.0-next.3` in a project with only 2 routes, none of them lazy.

**Comment by avatsaev** [comment] 2019-09-26 09:36
same here

**Comment by Splaktar** [comment] 2019-09-26 10:29
@avatsaev this issue was closed as it didn't include a reproduction. https://github.com/angular/angular/issues/32547 has been opened, with a reproduction, to track this issue going forward.
