### ISSUE TITLE
Is it possible that @ViewChildren() select components based on base type

### ISSUE THREAD

**Issue by ThinkontrolSY** [angular/angular#18700] opened 2017-08-15 12:17 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

```typescript
@component({
  selector: 'app-base',
  template: `<p>this base component</p>`
})
export class BaseComponent {
  var1;
  var2
}

@component({
  selector: 'app-inherit1',
  template: `<p>this inherit 1 component</p>`
})
export class Inherit1Component extend BaseComponent {
  var3;
  var4
}

@component({
  selector: 'app-inherit2',
  template: `<p>this inherit 2 component</p>`
})
export class Inherit2Component extend BaseComponent {
  var5;
  var6
}

@component({
  selector: "app",
  template: `
  <app-inherit1></app-inherit1>
  <app-inherit2></app-inherit2>
`
export class AppComponent {
@ViewChildren(BaseComponent )
  childCmps: QueryList<BaseComponent >;

  ngAfterViewInit() {
    console.dir(this.childCmps);
  }
}
})
```

ViewChildren select BaseComponent, and can not select it's inherited component.

Is is possible that viewChildren will select Inherit1Componet and Inherit2Componet because they are all extended from BaseComponent?

**Comment by ericmartinezr** [comment] 2017-08-15 13:20
https://github.com/angular/angular/issues/8580

**Comment by pkozlowski-opensource** [comment] 2017-08-16 08:39
Closing as a duplicate of #18700, thnx @ericmartinezr

**Closed by pkozlowski-opensource** 2017-08-16 08:39 UTC

**Comment by MartinJohns** [comment] 2018-12-19 15:34
@pkozlowski-opensource
I assume you mean closing as a duplicate of #8580? Because this issue is #18700. 😆
