### ISSUE TITLE
service worker fails to load css file

### ISSUE THREAD

**Issue by RyanHayden** [angular/angular#27554] opened 2018-12-07 21:16 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/service-worker

### Is this a regression?

 I have not seen a version where this doesn't happen

### Description

 
Followed getting started steps:

1. npm install -g @angular/cli
2. ng new my-app (selected no to router, used scss)
3. ng add @angular/pwa --project my-app 
4. the only update i made to the code was to the styles.scss file adding:
   body { background-color: yellow; }
5. ng build --prod
6. run with http-server
7. create short cut with chrome on desktop version (Version 70.0.3538.110 (Official Build) (64-bit))

## 🔥 Exception or Error
<pre><code>

The FetchEvent for "https://mmciodev.mge.com/styles.f37e128c6af9ca929fb7.css" resulted in a network error response: the promise was rejected.
ngsw-worker.js:1 Uncaught (in promise) DOMException: Entry already exists.
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.11.2
@angular-devkit/build-angular     0.11.2
@angular-devkit/build-optimizer   0.11.2
@angular-devkit/build-webpack     0.11.2
@angular-devkit/core              7.1.2
@angular-devkit/schematics        7.1.2
@angular/pwa                      0.11.2
@ngtools/webpack                  7.1.2
@schematics/angular               7.1.2
@schematics/update                0.11.2
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.23.1
</code></pre>

**Anything else relevant?**

Chrome Version 70.0.3538.110 (Official Build) (64-bit)
![cache-css](https://user-images.githubusercontent.com/7883127/49673073-d4c83700-fa32-11e8-89f2-bd6a2caa9ad4.png)
![error-failed](https://user-images.githubusercontent.com/7883127/49673074-d560cd80-fa32-11e8-8c4b-0b6dfe05d826.png)

It is very difficult to reproduces this error consistently, almost like it is a race condition.  But having a chrome shortcut on my desktop seems to reproduce it the most often, when chrome is not currently open.

**Comment by gkalpak** [comment] 2018-12-10 14:09
It is really hard to tell without a reproduction (https://mmciodev.mge.com/ doesn't seem to work :grin:), but it sounds it could be a browser issue.
It seems similar to [this issue][1], which turned out to be a bug in Chrome's `Cache` implementation. I am not saying it is the same bug, since that has been fixed a long time ago, but it could be something similar.

[This one][2] also seems potentially relevant.

Things I would try:
- Check whether it happens on other browsers?
- Check whether it happens on ChromeCanary?
- Put some breakpoints in `ngsw-worker.js` and try to gather more info on where exactly this is failing.

##
Anyway, I am closing this since there is no indication this is an issue with Angular and we can't investigate without a reliable reproduction.

[1]: https://stackoverflow.com/questions/32669605/what-is-domexception-entry-already-exists
[2]: https://bugs.chromium.org/p/chromium/issues/detail?id=758602&q=Entry%20already%20exists&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified

**Closed by gkalpak** 2018-12-10 14:09 UTC

**Comment by shabbir-dhangot** [comment] 2018-12-29 04:18
@gkalpak : I am confirming this issue is exist. Its started happening with me from yesterday. Not able to find exact reason for the same. 

> The FetchEvent for "https://www.greatbuyz.com/styles.100ba95a826dbf6391fc.css" resulted in a network error response: the promise was rejected.

Also I would like to know correct way to update index.html file in production. Currently if I change that it always calls cache-burst. Kindly give me any doc link.

**Comment by gkalpak** [comment] 2018-12-29 10:52
@shabbir-dhangot, as mentioned above, there is no indication this is an Angular issue and there is nothing we can do without more info.
Regarding your question, I am not sure what you are asking, but it sounds like a support request (which this issue tracker is not suitable for). Please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

(If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).)

**Comment by alexthelion** [comment] 2019-05-26 07:17
@RyanHayden did you find a solution for this bug? I am getting the same error message randomly when opening  the application in PWA mode.

**Comment by RyanHayden** [comment] 2019-05-26 15:22
@alexthelion no sorry i haven't.  Luckily our app is internal only used by a small group that is aware of the issue and can just hard refresh until it works.

If you discover the resolution would be great if you can post it here.

**Comment by alexthelion** [comment] 2019-05-27 08:44
@RyanHayden Could you please describe the hosting architecture that you are using? I'm using nginx with docker native. I'm trying to figure out why there is only several reports about this issue. 
In addition, I noticed that when this issue shows up, there is no existence of styles.css file under the resource tab in chrome, but there is a (index) file which holds all the styles.css content. Refresh always resolves it, it's really strange behavior.

**Comment by RyanHayden** [comment] 2019-05-27 15:34
@alexthelion its a basic windows server with iis.  It happens when getting from the server or running locally from http-server on nodejs.  Its running disconnected so i dont believe its a hosting issue.  Also, I can see the file in the cache, for some reason chrome just doesnt recognize it.

**Comment by pierreraii** [comment] 2019-05-29 08:23
I can confirm that this happens with me too.
In my case, it's a desktop app (using Electron) built with Angular + @angular/pwa module - the issue only seems to be happening on Windows.

**Comment by alexthelion** [comment] 2019-05-29 10:59
@pierreraii On what devices you managed to reproduce this bug?
@gkalpak Maybe this issue should be reopened?

**Comment by pierreraii** [comment] 2019-05-29 11:43
@alexthelion I am not able to get a constant reproduction of this issue, it happens very randomly. And we've only had reports of this happening from our users on Windows (8/10 AFAIK).

**Comment by alexthelion** [comment] 2019-05-30 07:45
I found a website which produce randomly the same bug: https://deanhume.github.io/beer/
The error in console: 

> The fetchEvent for "https://z2s71hp3o9.execute-api.us-east-1.amazonaws.com/default/styles" resulted in a network error response: the promise was rejected.

**Comment by wanderview** [comment] 2019-05-30 14:23
This error message could be a site bug or a browser bug.  We need to know what is causing the promise to reject in order to determine.

**Comment by alexthelion** [comment] 2019-05-30 16:11
@wanderview @gkalpak  I created a projected for the bug reproduction: https://github.com/alexthelion/pwa-demo

Link for the hosted app: https://fir-918f4.firebaseapp.com

Steps for reproduction:
1. Create a shortcut on your desktop
2. Open the app once, and then go offline
3. Close and open the app until you will get the error:

![image](https://user-images.githubusercontent.com/6614196/58646348-ddc50180-830d-11e9-8da7-4f8b5085c6e2.png)

I have clients saying this could happen on the first opening, even if they are online.

**Comment by wanderview** [comment] 2019-05-30 16:45
I don't get exactly the error you see, but I definitely see that the app does not store the resources necessary to be offlined in cache_storage.  It seems somewhat random what resources are missing, though.  In one run it was the main document html missing and in another it was the jpg.

I don't know much about anguler's integration with service workers, so not sure where to look for this stuff being stored.  It seems angular does not use the install event?

```javascript
            this.scope.addEventListener('install', (event) => {
                // SW code updates are separate from application updates, so code updates are
                // almost as straightforward as restarting the SW. Because of this, it's always
                // safe to skip waiting until application tabs are closed, and activate the new
                // SW version immediately.
                event.waitUntil(this.scope.skipWaiting());
            });
```

I guess I would recommend investigating the angular mechanism that puts things into cache_storage.

**Comment by wanderview** [comment] 2019-05-30 16:48
After letting the app sit for a while online it seems to have cached everything and works offline now.

**Comment by alexthelion** [comment] 2019-05-30 18:22
> I don't get exactly the error you see, but I definitely see that the app does not store the resources necessary to be offlined in cache_storage. It seems somewhat random what resources are missing, though. In one run it was the main document html missing and in another it was the jpg.
> 
> I don't know much about anguler's integration with service workers, so not sure where to look for this stuff being stored. It seems angular does not use the install event?
> 
> ```js
>             this.scope.addEventListener('install', (event) => {
>                 // SW code updates are separate from application updates, so code updates are
>                 // almost as straightforward as restarting the SW. Because of this, it's always
>                 // safe to skip waiting until application tabs are closed, and activate the new
>                 // SW version immediately.
>                 event.waitUntil(this.scope.skipWaiting());
>             });
> ```
> 
> I guess I would recommend investigating the angular mechanism that puts things into cache_storage.

The error is that the app can't load styles css file: 

> The FetchEvent for "https://fir-918f4.firebaseapp.com/styles.14ad77ffc4bc34de71b8.css" resulted in a network error response: the promise was rejected.
