### ISSUE TITLE
SELECT ngModel with multiple="false" property not working

### ISSUE THREAD

**Issue by billfranklin** [angular/angular#14511] opened 2017-02-15 19:16 UTC
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

With the <select> tag, if you use the multiple="false" property, the ngModel will not update the selected item.  If you remove the multiple="false" property, it works correctly.

**Expected behavior**

Including the multiple="false" property of the <select> tag will allow the ngModel to correctly select the item.

**Minimal reproduction of the problem with instructions**

```
<select id="mySelect" name="mySelect" [(ngModel)]="mySelectedValue" multiple="false" size="3">
    <option *ngFor="let option of options" [ngValue]="option">{{option.label}}</option>
</select>
```

if multiple="true" it works correctly if mySelectedValue is set, if you remove multiple="false" it works as well, but you cannot dynamically set the value of multiple property utilizing [multiple]="myDecision" or multiple="false"

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Windows 7, Angular CLI (ng serve)
* **Angular version:** 2.0.X

2.4.0
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome, Firefox, IE 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all
* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment] 2017-02-15 19:25
Duplicate of https://github.com/angular/angular/issues/12585

**Comment by kara** [comment] 2017-02-17 01:13
Yep, this looks like a dupe. @billfranklin Thanks for reporting, but closing to track in the original issue, #12585.

**Closed by kara** 2017-02-17 01:14 UTC
