### ISSUE TITLE
EmailValidator allows for e-mails without a period

### ISSUE THREAD

**Issue by maartentibau** [angular/angular#32788] opened 2019-09-20 08:36 UTC
# 🐞 bug report

### Affected Package

The built in EmailValidator doesn't invalidate an e-mail address without a period.

Package: angular/packages/forms/src/validators.ts

### Is this a regression?

I went trough the changelog and I only found 2 items concerning the e-mail validator.
One is when the e-mail validator was added to the framework and one to allow an empty field to not be treated as an invalid e-mail address.

### Description

When used in a form an e-mail address like `foo@bar` is considered a valid e-mail address, which is of course not the case.

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-email-validator-bug

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.803.4
@angular-devkit/build-angular      0.803.4
@angular-devkit/build-ng-packagr   0.803.4
@angular-devkit/build-optimizer    0.803.4
@angular-devkit/build-webpack      0.803.4
@angular-devkit/core               8.3.4
@angular-devkit/schematics         8.3.4
@angular/cli                       8.3.4
@ngtools/webpack                   8.3.4
@schematics/angular                8.3.4
@schematics/update                 0.803.4
ng-packagr                         5.5.1
rxjs                               6.4.0
typescript                         3.5.3
webpack                            4.39.2
</code></pre>

**Anything else relevant?**
The pattern used to fix the issue can be found here
https://emailregex.com/#crayon-5ca92712ae76b398292347

 I would not mind creating a PR for this to fix it.

**Comment by mlc-mlapis** [comment] 2019-09-20 08:48
@maartentibau But it is the valid email `foo@bar` by the spec.

**Comment by trotyl** [comment] 2019-09-20 08:53
Duplicate of https://github.com/angular/angular/issues/16544, https://github.com/angular/angular/issues/16976, https://github.com/angular/angular/issues/17296

**Comment by maartentibau** [comment] 2019-09-20 08:58
If I look at the wiki page: https://en.wikipedia.org/wiki/Email_address

**# Valid email addresses**

- `simple@example.com`
- `very.common@example.com`
- `disposable.style.email.with+symbol@example.com`
- `other.email-with-hyphen@example.com`
- `fully-qualified-domain@example.com`
- `user.name+tag+sorting@example.com` (may go to user.name@example.com inbox depending on mail server)
- `x@example.com` (one-letter local-part)
- `example-indeed@strange-example.com`
- `admin@mailserver1` **(local domain name with no TLD, although ICANN highly discourages dotless email addresses)**
- `example@s.example` (see the List of Internet top-level domains)
- `" "@example.org` (space between the quotes)
- `"john..doe"@example.org` (quoted double dot)

using no TLD is highly discouraged, so I really questioning the reason why this is by default allowed. It would be better I think to no allow it and make it optional.

**Comment by maartentibau** [comment] 2019-09-20 09:33
@mlc-mlapis you are indeed correct. The EmailValidator does follow the HTML5 spec on an e-mail field. So maybe I should not report this as a bug, but change it to a 

### 🚀 feature request

But lets see what comes out of the discussion

**Comment by mlc-mlapis** [comment] 2019-09-20 09:45
@maartentibau It's a general problem, and there are many cases how different people see it. Because of the more advanced and structural requirements on the returned results from validators, we use our layer which encapsulates all standard validators, and it allows us to extend them either from the returned values point of view or to add some more functionality, like required TLD in this case.

**Comment by Airblader** [comment] 2019-09-20 11:10
In practice, validating an email address isn't very useful; it catches users who accidentally typed something else in the field etc. But if you want to make sure you have an actual address, you need some email activation workflow.

Just because an email address is structurally valid doesn't mean it exists or belongs to the user.

**Comment by lazarljubenovic** [comment] 2019-09-21 04:14
It's much more useful to the user to warn against typos such as `gmial.com`, `gmail.co`, etc. than try to validate it with an enormous regex. A basic validation of "has a `@`" is enough to catch people who accidetly type in their name or something. Heck, even spaces are valid if you put them between quotes.

**Comment by dannyskoog** [comment] 2019-09-24 18:56
Personally I’m happy with allowing `foo@bar` since the presence of the particular format in the HTML5 spec opens up for users potentially having it

**Closed** 2019-09-24 19:08 UTC
Labels: comp: forms
