### ISSUE TITLE
Support component style configuration (encapsulation none)

### ISSUE THREAD

**Issue by KrickRay** [angular/angular#31487] opened 2019-07-10 11:39 UTC
# 🚀 feature request

### Relevant Package

This feature request is for @angular/core

### Description
It would be nice to be able to add style without encapsulation.
- allow remove deprecated `/deep/`, `>>>`, and `::ng-deep`
- allow multiple styles with different encapsulation

### Describe the solution you'd like
Add `isEncapsulated` property to styles property. When disabled it will work like `ViewEncapsulation.None` but only for a certain style. For everything else, the selected component encapsulation will be applied.
Use so:
```ts
@Component({
  template: `
    <h1 class="header">Hello world</h1>
  `,
  styles: [
    ['.header { font-weight: normal; }', false],
    '.header { color: red; }'
  ]
})
export class HelloComponent {}
```
Or so:
```ts
styles: [
  {style: {'h1 { font-weight: normal; }', isEncapsulated: false},
  '.header { color: red; }'
]
```

### Describe alternatives you've considered

Leave `/deep/`, `>>>`, and `::ng-deep`

**Comment by trotyl** [comment] 2019-07-10 13:06
Duplicate of https://github.com/angular/angular/issues/23525

**Closed** 2019-07-10 13:30 UTC
