### ISSUE TITLE
@Ancestor() doesn't work correctly

### ISSUE THREAD

**Issue by ajoslin** [angular/angular#1216] opened 2015-04-02 20:31 UTC
WRONG: http://plnkr.co/edit/lQvNKjDU9FcEW2rF2evA?p=preview 
Right: http://plnkr.co/edit/zdx7h4Ny6z0EyWO3939c?p=preview

In this example, component 'C' cannot reach its ancestor 'A'.

Our actual use-case is this:

```html
<ion-nav-viewport>
  <ion-nav-dynamic-component *for="component of navStack" [component]="component">
    <ion-view>
      <ion-toolbar>
```

`ion-toolbar` needs to inject the ancestor `ion-nav-viewport` to check if the nav stack has length greater than 0. If so, it will show the back button, and when back is clicked pop the nav stack.

**Comment by ajoslin** [comment] 2015-04-02 20:44
(I think is because Ancestor only works within the same shadow root. But I am very much against that idea. I'm willing to discuss my reasoning for why it should work outside the shadow root in detail if desired).

**Comment by matanlurey** [comment] 2015-04-02 23:25
I've observed the same issue.

**Comment by jelbourn** [comment] 2015-04-03 16:20
I've definitely injected an `@Ancestor` across shadow root boundaries before, but something might have changed since then. I agree that it should not be restricted to directives in the same shadow root.

**Comment by naomiblack** [comment] 2015-04-07 16:18
@mhevery can we look at effort as part of M7? this is a user pain point.

**Comment by mhevery** [comment] 2015-04-07 18:35
@ajoslin I think you have the wrong plunker.

Your use case makes sense and it does not cross shadow DOM boundaries.

**Comment by SekibOmazic** [comment] 2015-04-07 18:56
@mhevery The plunk has been overridden. Here is my copy of the original that demonstrates the issue:
http://plnkr.co/edit/zdx7h4Ny6z0EyWO3939c?p=preview

**Comment by mhevery** [comment] 2015-04-07 23:07
The fallowing works:

```html
<ion-nav-viewport>
  <ion-nav-dynamic-component *for="component of navStack" [component]="component">
    <ion-view>
      <ion-toolbar>
```
Where `ion-toolbar` can  inject the ancestor `ion-nav-viewport`. But your plunker has a different use case.

```html
<ion-nav-viewport>
  <ion-nav-dynamic-component *for="component of navStack" [component]="component">
    <ion-view>
       # SHADOW
         <ion-toolbar>
```

At this point  `ion-toolbar` can not inject the ancestor `ion-nav-viewport`, because you are trying to cross a shadow DOM boundary. This is by design, since `<ion-toolbar>` is an implementation detail of `<ion-view>` and should be isolated / encapsulated.

The way we intend yuo to solve this issue is through component injector which does pass boundaries.

```
class Dependency {}

@Component({
  selector: 'parent'
  services: [Dependency]
}) 
@Template({
  inline: '<child></child>
})
class Parent {
  constructor(dep:Dependency) {}
}

@Component({
  selector: 'child'
})
@Template(...)
class Child {
  constructor(dep:Dependency) {
    // here the Dependency can pass through many Shadow DOM layers
  }
}
``` 

In the above example `Dependency` is configured by `Parent` and is available to all children. 

What we can do is to make it easier for the `Parent` to insert itself int the `Component.services` Thoughts?

**Comment by jkurz** [comment] 2015-04-07 23:55
so is this what you mean by inserting itself? 
```
@Component({
  selector: '[b]',
  services: [A,B]
})
@Template({
  inline: 'B: parentA = {{parentA}}<div c></div>',
  directives: [C]
})
class B {
  constructor(@Parent() a:A) {
    this.parentA = a.constructor.name;
  }
}
```

or

```
@Component({
  selector: '[b]',
  services: [A,this]
})
@Template({
  inline: 'B: parentA = {{parentA}}<div c></div>',
  directives: [C]
})
class B {
  constructor(@Parent() a:A) {
    this.parentA = a.constructor.name;
  }
}
```

Because if so, this works today and it does not get any easier to insert self, IMO. http://plnkr.co/edit/TloXSWQtWkhDumvwrRPJ?p=preview

**Comment by mhevery** [comment] 2015-04-08 00:04
WAT! I am surprised that it works. :-) 

In your example 1 `services: [A, B]` will insert a new instance of `B` (not what you want)
in your example 2 `services: [A, this]` at the time of evaluation the `this` should be `undefined`. So the fact that `undefined` resolves to instance of `B` is blowing my mind. 

But yes something like that.

**Comment by joshkurz** [comment] 2015-04-08 08:10
WAAAT? :) 

It looks like the annotation service evaluates `this` as `null` during runtime, and inside View.hydrate, componentDirective.annotation.services is defined and contains an Ancestor.  But its creating new instances of Ancestor just like example 1. So it still does not do what we want.

maybe all we need to do is add a check inside of hydrate for ancestor on any one of the services before creating a child injector.

**Comment by matanlurey** [comment] 2015-04-09 05:28
To double check, I'm running into the following issue:

```dart
@Decorator(
  selector: '[event-bus]'
)
class EventBusDecorator extends EventBus {
  EventBusDecorator(
      @Ancestor()
      @Inject(EventBusDecorator)
      EventBus parentEventBus)
          : super(parentEventBus);
}
```

With a DOM like this:

```html
<root event-bus>
  <child>
    <child event-bus>
      <child></child>
    </child>
  </child>
</root>
```

I get a circular dependency error, even though I assume `@Ancestor` should prevent this.

**Comment by mhevery** [comment] 2015-04-10 20:30
I think your code is not right. It should be:

```javascript
@Decorator(
  selector: '[event-bus]'
)
class EventBusDecorator extends EventBus {
  EventBusDecorator(@Ancestor() EventBusDecorator parentEventBus)
          : super(parentEventBus);
}
```

if what you want is to inject `EventBus` then you need to do something like this:

```javascript
@Decorator(
  selector: '[event-bus]'
)
class EventBusDecorator extends EventBus {
  EventBusDecorator(@Ancestor() EventBus parentEventBus)
          : super(parentEventBus);
}
```
but in the parent component:
```javascript
@Component({
  ...
})
@View({
  decorators: [bind(EventBus).toAlias(EventBusDecorator)]
})
class DemoComponent{}
```

**Comment by ajoslin** [comment] 2015-04-11 17:53
Thanks Misko, the parent injection makes total sense.

**Comment by mhevery** [comment] 2015-04-11 18:34
I am going to close this issue and replace it with https://github.com/angular/angular/issues/1319. Please comment if you think I have missed something.

**Closed by mhevery** 2015-04-11 18:34 UTC
