### ISSUE TITLE
Angular 4, deprecated code not summarized 

### ISSUE THREAD

**Issue by born2net** [angular/angular#15556] opened 2017-03-28 15:19 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
So I am maintaining 4 very large projects in Angular.
There is no way for me to know, when I open each project, which code has been deprecated.
The only reported issue I see is when I run AOT, a message of ```<template>``` now needing to be ```<ng-template>```
However, there are no mentions of any issues with things like Renderer now needing to ne Renderer2.

**Expected behavior**
I expect TypeScript and / or cli to report a summary of all deprecated API so we can fix'em before ng5 is out.

```
@angular/cli: 1.0.0
node: 6.9.5
os: win32 x64
@angular/animations: 4.0.0
@angular/common: 4.0.0
@angular/compiler: 4.0.0
@angular/core: 4.0.0
@angular/forms: 4.0.0
@angular/http: 4.0.0
@angular/platform-browser: 4.0.0
@angular/platform-browser-dynamic: 4.0.0
@angular/router: 4.0.0
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.0
@angular/language-service: 4.0.0
@ngtools/webpack: 1.3.0
```

Not sure if this issue should be opened against cli repo.

FYI, in WebStorm I will see cross outs on deprecated API, but again, I am dealing with thousands of files so I can't open each one and look for cross outs, see below:

![capture](https://cloud.githubusercontent.com/assets/5090936/24413073/332af346-138f-11e7-9bbd-18befd55bc3c.PNG)

Angular 2 Kitchen sink: http://ng2.javascriptninja.io
and source@ https://github.com/born2net/Angular-kitchen-sink
Regards,

Sean

**Comment by DzmitryShylovich** [comment] 2017-03-28 16:41
> I expect TypeScript and / or cli

this is angular repo :)

**Comment by born2net** [comment] 2017-03-28 16:43
well it's up to Angular (or cli I am not sure) to report the issue, not related to TypeScript. But would be nice it it showed in the TypeScript console same as Angular does with language service.

**Comment by born2net** [comment] 2017-03-28 18:09
that's AWESOME!!! tx
Now I still think this issue should be resolved so I will keep open, but this sure helps!!!
tx

Sean

**Comment by born2net** [comment] 2017-03-28 18:09
![dep](https://cloud.githubusercontent.com/assets/5090936/24420252/14a3bf1c-13a7-11e7-8911-ea2235409391.PNG)

**Comment by Toxicable** [comment] 2017-03-28 19:46
This isn't an Issue with the Angular framework. If you want reports you need you development tools to report it Angular dosen't do this itself with it's current depreciation method. If anything, this should be in the CLI imo

**Comment by born2net** [comment] 2017-03-28 19:49
I can move to cli sure, let's see what some of the ng dev thing, and if need be will move sure,
tx!

**Comment by IgorMinar** [comment] 2017-03-29 07:33
@mgechev and @alexeagle have some tslint checks in works that surface all the deprecation automatically while linting.

**Comment by mgechev** [comment] 2017-03-29 18:44
There's a rule for automatic migration of `<template>...</template>` to `<ng-template>...</ng-template>` in the [codelyzer's repo](https://github.com/mgechev/codelyzer/compare/template).

Waiting for [this PR](https://github.com/mgechev/tslint/commit/a7caa6b944e791edc4e1580db56383b088db0c79) to be merged in order to allow auto-fixes in external templates.

**Comment by born2net** [comment] 2017-03-29 18:47
also renderer now renderer2 etc..

**Comment by alexeagle** [comment] 2017-03-29 20:08
Deprecation linter is here: https://github.com/palantir/tslint/pull/2395

**Comment by alexeagle** [comment] 2017-04-11 17:23
Deprecation linter just merged. We can wait for the next tslint release and update our stuff. Also possible the Angular CLI could ship with a pre-release tslint version, if we want it sooner.

**Comment by born2net** [comment] 2017-04-11 18:59
ya if it was part of cli, it would be awesome!

**Comment by jenniferfell** [comment] 2019-05-10 21:40
Deprecation summary has merged into master: https://next.angular.io/guide/deprecations
Refinements in the queue: https://github.com/angular/angular/pull/30400

This is no longer a documentation issue, so I'm removing that label. 

I can't officially speak to any messages generated by the CLI during build re use of deprecated features and APIs in a project, but I believe improvements have been made there as well. @alexeagle @Splaktar ?

**Comment by jenniferfell** [comment] 2019-05-10 21:41
Removed feature and fix labels, to put this back into triage queue for re-triage in context of latest release.

**Comment by pkozlowski-opensource** [comment] 2020-03-13 07:21
Duplicate of #11996

**Closed by pkozlowski-opensource** 2020-03-13 07:21 UTC
Labels: comp: core, comp: packaging, severity3: broken, type: feature
