### ISSUE TITLE
Date Pipe formatting incorrectly (showing wrong date)

### ISSUE THREAD

**Issue by cperez1087** [angular/angular#8319] opened 2016-04-28 21:10 UTC
The Date Pipe is formatting certain dates incorrectly. It is showing the wrong date when formatted.

**Steps to reproduce and a minimal demo of the problem**
Create a Date for April, 1, 2004 (happens with 2000 too, but not with 2016).
Display this date using {{myDate | date}} pipe.

You can use plunker sample below
http://plnkr.co/edit/H32nNiSqxJJwQ0DvYcEm

**Current behavior**
For April 1, 2004. It shows the formatted date as Mar 31, 2004.

**Expected/desired behavior**
Formatted date as Apr 1, 2004

**Comment by CaptainCodeman** [comment] 2016-04-28 21:22
Probably some local-time / UTC issue somewhere. It works fine from North America.

Strangely, the two dates show as having different timezones when I run it.

**Comment by cperez1087** [comment] 2016-04-28 21:27
Im on EST.
Im seeing the following on the preview pane of the plunker sample:

```
Formatted: Mar 31, 2004
Actual: Thu Apr 01 2004 00:00:00 GMT-0400 (Eastern Daylight Time) 

Formatted: Apr 1, 2016
Actual: Fri Apr 01 2016 00:00:00 GMT-0400 (Eastern Daylight Time)
```

2000 and 2004 were leap years. Although 2016 is as well. Hence why I included these two dates.

**Comment by cperez1087** [comment] 2016-04-28 21:31
Adding 1 hour to the time returns the following:
```
Alternate with 1 extra hour
Formatted: Apr 1, 2004
Actual: Thu Apr 01 2004 01:00:00 GMT-0400 (Eastern Daylight Time)
```

Hope it helps.

**Comment by CaptainCodeman** [comment] 2016-04-28 21:32
I see this in Chrome:

```
Apr 1, 2004
Thu Apr 01 2004 00:00:00 GMT-0700 (MST) 
Apr 1, 2016
Fri Apr 01 2016 00:00:00 GMT-0600 (MDT)
```

I guess my PC isn't sure where it is so it's hedging it's bets.

**Comment by ulikoehler** [comment] 2016-04-29 02:51
In Europe/Chrome I see this in the Plunkr:

```
Formatted: Apr 1, 2004
Actual: Thu Apr 01 2004 00:00:00 GMT+0200 (CEST) 

Formatted: Apr 1, 2016
Actual: Fri Apr 01 2016 00:00:00 GMT+0200 (CEST) 

Alternate with 1 extra hour
Formatted: Apr 1, 2004
Actual: Thu Apr 01 2004 01:00:00 GMT+0200 (CEST)
```

**Comment by oodboo** [comment] 2016-05-07 09:00
version 2.0.0.rc.1
```
for format:  upddate | date:'dd-MM-yyyy' 
result is: 05/07/2016 

for format : upddate | date:'dd MMM yyyy' 
result is: May 07, 2016 

for format : upddate | date:'d/MMM/yyyy' }}
result is: May 7, 2016 

for format : upddate  | date:'MMM, dd yyyy' }}
result is: May 7, 2016 

```
always the same ...

**Comment by natcohen** [comment] 2016-06-17 22:18
Works with RC2... this should be closed

**Comment by vicb** [comment] 2016-06-17 22:54
thanks

**Comment by cperez1087** [comment] 2016-06-22 13:38
I don't believe this is fixed. 

When tested in plunker [Sample](http://plnkr.co/edit/AjYjTW9KCr2YvUcc5Xln) using the latest @angular npmcdn I still get the same issue.
```
Formatted: Mar 31, 2004
Actual: Thu Apr 01 2004 00:00:00 GMT-0400 (Eastern Daylight Time) 

Formatted: Apr 1, 2016
Actual: Fri Apr 01 2016 00:00:00 GMT-0400 (Eastern Daylight Time) 
```
Note, this is with EST. And seems to happen with some leap years. 
If I change my PC's timezone to London time, it works as expected.
```
Formatted: Apr 1, 2004
Actual: Thu Apr 01 2004 00:00:00 GMT+0100 (GMT Daylight Time) 

Formatted: Apr 1, 2016
Actual: Fri Apr 01 2016 00:00:00 GMT+0100 (GMT Daylight Time) 
```

**Comment by cperez1087** [comment] 2016-06-22 13:55
Here is a jsFiddle [Sample](https://jsfiddle.net/0naj27q1/1/) using the same April 1, 2004 with Moment.js. It formats correctly with that one (on EST)

**Comment by pkozlowski-opensource** [comment] 2016-10-11 15:31
Here is a plunker with the latest ng version: https://plnkr.co/edit/uPUgWaDUuu2ccKkYz8yl?p=preview

Could anyone within the EST time zone confirm that this is still an issue?

**Comment by cperez1087** [comment] 2016-10-11 17:42
Yes, still a problem with EST.
```
Formatted: Mar 31, 2004
Actual: Thu Apr 01 2004 00:00:00 GMT-0400 (Eastern Daylight Time) 

Formatted: Apr 1, 2016
Actual: Fri Apr 01 2016 00:00:00 GMT-0400 (Eastern Daylight Time) 

Alternate with 1 extra hour
Formatted: Apr 1, 2004
Actual: Thu Apr 01 2004 01:00:00 GMT-0400 (Eastern Daylight Time)
```

**Comment by astrobob** [comment] 2016-12-14 10:50
I have a problem with CEST to:
Formatted: 3 août 1955
Actual: Thu Aug 04 1955 00:00:00 GMT+0200 (CEST)

**Comment by pkozlowski-opensource** [comment] 2016-12-16 16:38
@astrobob thnx for this reproduce, I was able to confirm in one version of Chrome (54.0.2840.14) in CEST (France):
* `new Intl.DateTimeFormat('fr').format(new Date(1969, 9, 4))` gives `"03/10/1969"`
* `new Intl.DateTimeFormat('fr').format(new Date(1970, 9, 4))` gives `"04/10/1970"`

So just changing a year gives you 2 different days in the output. I've tested also with FFox and gives correct answers for both cases `"04/10/1969"` and `"04/10/1969"`.

I need to test with more browsers and their versions but for now it looks like a bug in at least one version of Chrome (to be confirmed).

**Comment by pkozlowski-opensource** [comment] 2016-12-16 18:16
So, just re-tested with some more browsers and for `new Intl.DateTimeFormat('fr').format(new Date(1969, 9, 4))`:
* Chrome 57.0.2951.0 (Official Build) canary gives `"03/10/1969"` (KO)
* FFox 50.1.0 gives `"04/10/1969"` (OK)

Given the above I would expect it to be a bug in Chrome and as such I've reported it here: https://bugs.chromium.org/p/v8/issues/detail?id=5747

**Comment by TobiasKrogh** [comment] 2017-03-03 18:28
@pkozlowski-opensource just stumbled upon this issue and fiddled around with it... while I can confirm your observations for `new Date(1969, 9, 4)` using `new Intl.DateTimeFormat('fr').format(new Date(1968, 9, 4))` (one year earlier) the results are similar in Chrome and Firefox:

- Chrome 56.0.2924.87 gives `"03/10/1968"` (KO)
- Firefox 51.0.1 gives `"03/10/1968"` (KO)

**Comment by natebunney** [comment] 2017-03-03 21:26
Maybe I am ignorant here but, if I am asking for a date to be formatted, why is it trying to adjust for time zone?  It seems to me that formatting and adjusting for time zone are really two different things and should be handled separately, why does the time zone even matter to this pipe?  All I expect is to get the same date out that I put in, every time.

**Comment by ocombe** [comment] 2017-03-13 10:46
The date pipe uses intl to format date and is part of the i18n package that Angular offers, that's why it uses locale dates.

**Comment by theHellyar** [comment] 2017-04-14 20:27
This is an issue for me as well...anyone have a work around for now?

**Comment by cperez1087** [comment] 2017-04-19 19:12
Seems to be related to Daylight Saving Changes before 2007.

This example shows all the dates that format inconsistently (based on US format) for a 10 year period starting Oct 1, 1999.
[plunker sample](https://plnkr.co/edit/xfeXX3QLVkYiPgeJ1bFD?p=preview)

**Comment by cperez1087** [comment] 2017-04-19 19:43
@theHellyar 
You can use Angular2-Moment to display your Dates. It seems to work correctly.

Here is a [Sample](http://plnkr.co/edit/DSAZnR0NHvpw2e1jszCL?p=preview)

**Comment by cimframe** [comment] 2017-07-28 01:42
OK. This is driving me nuts.

I am using Angular 4 (^4.0.0 in package.json) and am not getting correct times...

I set a date as follows:

`new Date("1988-11-05T14:00:00-07:00")`

and am using the date pipe to format the outout as follows:

`{{contact.lastModifiedDate | date:"EEEE, MMM dd, yyyy, hh:mm a"}}`

I get the following for output: Saturday, Nov 05, 1988, 01:00 PM
The last time I checked 14:00 should be 02:00 PM

Is this a bug or a warp in time??

**Comment by ocombe** [comment] 2017-07-28 06:56
We are completely rewriting the date pipe for angular v5, hopefully this should fix those kind of issues

**Comment by jmcclanahan** [comment] 2017-08-21 17:43
I'd also like to add that I'm seeing a similar issue. I'm using the date pipe like so:
`{{effectiveDate | date:"MM/dd/yyyy"}}`
and I'm giving the pipe a unix timestamp, for example of 1456725600000. 

This works fine in the timezone of the server (my timezone - CST), but anyone with a timezone to the west of my timezone will see the previous day. For example, if I give the date pipe `08/21/2017` I will see `08/21/2017`, but anyone viewing my app on the west coast will see the previous day of `08/20/2017` which is not correct. This is causing me lots of calls from customers as this app is used by thousands of people a day.

**Comment by ocombe** [comment] 2017-08-21 18:23
With the new date pipe coming in angular 5.0 you'll be able to fix the
timezone to avoid this kind of issues

**Comment by ocombe** [comment] 2017-08-21 19:12
It will be in the next one

**Comment by burnzoire** [comment] 2017-10-04 23:16
Why not fix it in 4 as well?

**Comment by ocombe** [comment] 2017-10-05 05:04
Because in 4.x we defer those type of formatting to the intl api, and we don't have any control over it. To fix that we had to do a breaking change, that's why it is only available in 5.x unfortunately

**Closed** 2017-10-05 05:05 UTC
Labels: comp: common, comp: i18n, freq2: medium, severity3: broken, type: bug

**Comment by omaracrystal** [comment] 2019-06-28 17:30
@ocombe Where can we find the solution to timezone?

**Comment by ocombe** [comment] 2019-06-28 17:50
https://angular.io/api/common/DatePipe
