### ISSUE TITLE
ESlint strict linter checks - warnings with angular reactive forms code 

### ISSUE THREAD

**Issue by prabh-62** [angular/angular#42758] opened 2021-07-03 18:06 UTC
# Bug Report

### Affected Package
- `@angular/core`
- `@angular/forms`

### Is this a regression?
No

### Description
When enabling all ESLint rules on strict angular 12 workspace, ESlint raises some warnings when using coding from @angular/forms

## Minimal Reproduction
- `npx @angular/cli@12 new web-apps --create-application false`
- `cd web-apps`
- Create `.eslintrc.json` and add this code snippet
 ```json
{
  "root": true,
  "ignorePatterns": ["projects/**/*"],
  "plugins": [],
  "overrides": [
    {
      "files": ["*.ts"],
      "parserOptions": {
        "project": ["tsconfig.json"],
        "createDefaultProgram": true
      },
      "extends": [
        "eslint:recommended",
        "plugin:@typescript-eslint/recommended",
        "plugin:@typescript-eslint/recommended-requiring-type-checking",
        "plugin:@angular-eslint/all"
      ],
      "rules": {
        "@angular-eslint/sort-ngmodule-metadata-arrays": "off"
      }
    },
    {
      "files": ["*.html"],
      "extends": ["plugin:@angular-eslint/template/all"],
      "rules": {
        "@angular-eslint/template/i18n": "off"
      }
    }
  ]
}

```
- `yarn ng add @angular-eslint/schematics`
- `yarn ng g @angular-eslint/schematics:app admin-console --routing --style css`
- Open `web-apps` in [VS Code](https://code.visualstudio.com) and install ESLint extension
	<img width="1219" alt="vscode_eslint" src="https://user-images.githubusercontent.com/13006107/124363086-2c3cdc80-dc07-11eb-986c-aaee1075b8c6.png">
- Edit `.vscode/settings.json` and add this code snippet
	```json
	{
	  "eslint.validate": ["typescript", "html"]
	}
	```
- Edit `projects/admin-console/src/app/app.component.ts` and add this code snippet
	```ts
  constructor(private readonly fb: FormBuilder) {
    const setPasswordFormGroup = this.fb.group({
      newPassword: ['', [Validators.required]],
      confirmPassword: ['', [Validators.required]],
    });
    console.log(setPasswordFormGroup.getRawValue());
  }
	```
- `yarn ng lint --project admin-console` (lint fails)

## Exception or Error
<code>
15:26  error  Avoid referencing unbound methods which may cause unintentional scoping of `this`.
If your function does not access `this`, you can annotate it with `this: void`, or consider using an arrow function instead  @typescript-eslint/unbound-method
</code>
<img width="1196" alt="eslint_validator_unbound_method" src="https://user-images.githubusercontent.com/13006107/124362973-7f625f80-dc06-11eb-82d1-4973611a9421.png">

## Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 12.1.1
Node: 16.4.1 (Unsupported)
Package Manager: yarn 1.22.10
OS: darwin x64

Angular: 12.1.1
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1201.1
@angular-devkit/build-angular   12.1.1
@angular-devkit/core            12.1.1
@angular-devkit/schematics      12.1.1
@schematics/angular             12.1.1
rxjs                            6.6.7
typescript                      4.3.5
</code></pre>

**Anything else relevant?**
No

**Comment by JoostK** [comment] 2021-07-03 18:17
Heya, thanks for the excellent issue report. This is however a duplicate of #40571; the PR that addresses it #40044 has proven to break apps though, due to bad interaction with TS type-checking.

**Closed by JoostK** 2021-07-03 18:17 UTC
