### ISSUE TITLE
FR(core): Platform-agnostic dispatchEvent in Renderer

### ISSUE THREAD

**Issue by trotyl** [angular/angular#27172] opened 2018-11-19 13:16 UTC
# 🚀 feature request

### Relevant Package

 This feature request is for `@angular/core`, `@angular/platform-browser`, `@angular/platform-server`, `@angular/platform-webworker`

### Description
 A clear and concise description of the problem or missing capability...

Current `Renderer` (`Renderer2` in API) can only listen to an event, but not able to trigger it, which is an inconsistency results to incomplete functionality.

Also, events are fine-grained action triggers, for example, one can trigger `.focus` programmatically with:

```typescript
this.renderer.dispatchEvent(el, new Event('focus'))
```

Which sets the focus state on element without breaking abstraction. For non-HTMLElement, the event will simply be ignored rather than causing error. (This is why `invokeElementMethod` is indeed a nonsense and should be removed)

So that https://github.com/angular/angular/issues/15674 can be handled properly.

The same abstraction have been used in jQuery for years and proven useful.

<sub>Please be aware `$(el).focus()` won't touch `.focus()` method on `el`, it's a shortcut of `$(el).trigger('focus')` which dispatch a DOM event.</sub>

Also, this can make unit testing a little simpler in which event dispatching are used frequently, as described in https://github.com/angular/angular/issues/15051.

### Describe the solution you'd like
 If you have a solution in mind, please describe it.

Adding a new method with the following signature:

```typescript
class Renderer2 {
  dispatchEvent(el: any, event: any): boolean
}
```

Which is analogous to [`EventTarget.dispatchEvent`](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/dispatchEvent) API.

Note: using `any` type here is only for consistency with other `Renderer2` APIs, it should always be a subclass of `Event`.

Note: similar to other methods, an application running in webworker cannot rely on the return value.

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

There's no way to make a platform-agnostic event dispatching without concrete knowledge of the view implementation, thus must be made into `Renderer`.

**Comment by pauldraper** [comment] 2019-03-30 15:52
Not being able to set focus is a feature regression, as pointed out by #15674.

**Comment by jelbourn** [comment] 2020-10-19 20:38
Closing since Angular has moved away from the idea of having a separate `Renderer` class and instead just using the DOM directly. For dispatching fake events for _testing_, you can check out some of the stuff in `@angular/cdk/testing`

**Closed by jelbourn** 2020-10-19 20:38 UTC
Labels: comp: core, core: DOM rendering, core: event listeners, triage #1, type: use-case
