### ISSUE TITLE
Angular Animation lost binding after changing the order of objects in an array, needs to trigger twice to re-bind the object.

### ISSUE THREAD

**Issue by tenglongroy** [angular/angular#38307] opened 2020-07-31 00:06 UTC
# 🐞 bug report

### Affected Package
@angular/animation

### Is this a regression?

No

### Description

Initially there's an array of objects for *ngFor display in HTML, and each object is assigned a boolean property "show" with value false in OnInit( ). And "show" is used to indicate the animation state 'initial' or 'final' that is defined in component.

The animation 'trigger' works fine at the beginning, but after changing the order of the objects in the array (sort or reverse), Angular Animation seems to lose binding to the objects, and the 'trigger' doesn't do anything when trying to trigger the first time, but it works fine on the second time and so on.

Expected behaviour: after changing order of the objects (sort / reverse), the animation should work at the first 'trigger'.

Please check the stackblitz below.

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-ivy-ehgtbm

## 🔥 Exception or Error

No error / exception

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 10.0.4
Node: 12.18.0
OS: win32 x64

Angular: 10.0.5
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.4
@angular-devkit/build-angular     0.1000.4
@angular-devkit/build-optimizer   0.1000.4
@angular-devkit/build-webpack     0.1000.4
@angular-devkit/core              10.0.4
@angular-devkit/schematics        10.0.4
@angular/cdk                      10.1.1
@angular/cli                      10.0.4
@angular/material                 10.1.1
@ngtools/webpack                  10.0.4
@schematics/angular               10.0.4
@schematics/update                0.1000.4
rxjs                              6.5.5
typescript                        3.9.7
webpack                           4.43.0
</code></pre>

**Comment by jelbourn** [comment] 2020-10-26 21:07
Duplicate of #37895

**Closed by jelbourn** 2020-10-26 21:07 UTC
Labels: comp: animations
