### ISSUE TITLE
Reactive forms: select tag with dynamic multiple attribute doesn't select all values (in OnInit)

### ISSUE THREAD

**Issue by exsoflowe** [angular/angular#25864] opened 2018-09-07 15:13 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

I use select tag with Reactive forms. This select can be multiple or not.
I don't write two different selects. I combine them into one select.
`[multiple]="condition"`
But in this case Angular shows me last value from array as selected
`{disabled: false, value: ['1', '2']}`
Only '2' is selected

## Expected behavior

'1' and '2' are selected.

## Minimal reproduction of the problem with instructions

1. Build reactive form with one form control (in OnInit).
2. This form control has value as array (because it's multiple select).
3. Add select tag in template with `[multiple]="condition"`.
4. You can see only last value from array as selected.

To avoid this behavior I can setValue(['1', '2']) in AfterViewInit. And it will work. But it doesn't work in OnInit.

Demo: https://stackblitz.com/edit/angular-v6-1-7-reactive-forms-select-multiple-dynamically?file=src/app/app.component.ts

## Environment

<pre><code>
Angular version: 5.2.9, 6.0.0 and 6.1.7

Browser:
- It works only in IE 11.
- It doesn't work in desktop Edge, Chrome, Firefox 

- [x] Chrome (desktop) version 68
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version 62
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [x] Edge version 17
 
Others:

</code></pre>

Maybe it's related issues
https://github.com/angular/angular/issues/20584
https://github.com/angular/angular/issues/12585

**Comment by kara** [comment] 2018-09-11 22:14
@exsoflowe Looks like a dupe of https://github.com/angular/angular/issues/12585. When you bind to `multiple`, you're not actually getting the value accessor for multi-selects because directive selectors cannot take bindings into account.

**Closed by kara** 2018-09-11 22:14 UTC
Labels: comp: forms
