### ISSUE TITLE
Pipe (`|`) operator has incorrect precedence (too tight)

### ISSUE THREAD

**Issue by thorn0** [angular/angular#27415] opened 2018-12-03 13:28 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/core

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 1.x

### Description

AngularJS: `a ? b : c | x` means `(a ? b : c) | x`.

Angular: `a ? b : c | x` means `a ? b : (c | x)`.

It is unexpected. E.g. see #19657, https://github.com/prettier/prettier/issues/5586.

Who would write `a ? b : c | x` meaning `a ? b : (c | x)` given that `a ? b | x : c` even is not a valid expression? This does not look like an intentional design decision, more like a mistake (bug).

The natural expectation is that the pipe in the end of an expression should be applied to the whole expression, even if there is no parentheses. According to the [docs](https://angular.io/guide/pipes), pipes are _a way to write display-value transformations that you can declare in your HTML_. They are perceived as external to expressions, something that modifies the expression without really being part of it. For this intuition to be valid, pipes must have the lowest precedence. The current behavior breaks the intuition for no reason, without adding any value.

## 🔬 Minimal Reproduction

* https://stackblitz.com/edit/angularjs-ouvjdv?file=home%2Fhome.html
* https://stackblitz.com/edit/angular-wn7zmz?file=src%2Fapp%2Fapp.component.html

**Comment by thorn0** [comment] 2018-12-03 17:36
The `|` operator in JS has nothing to do with the `|` operator in Angular expressions.

**Comment by thorn0** [comment] 2018-12-03 18:10
The natural expectation is that the pipe in the end of an expression should be applied to the whole expression, even if there is no parenthesis. According to the [docs](https://angular.io/guide/pipes#pipes), pipes are 'a way to write display-value transformations that you can declare in your HTML'. So they are perceived as external to expressions, something that modifies the expression without being part of it. For this intuition to be valid, pipes must have the lowest priority. The current behavior breaks the intuition for no reason, without adding any value.

**Comment by thorn0** [comment] 2018-12-04 09:31
@trotyl 
1. Why isn't `a ? b | x : c` a valid expression then?
2. Any practical reasons behind this decision (to align with those proposals)? Was its motivation like 'one day `|>` might be standardized and become really widespread, people will get used to its precedence, so the precedence of our `|` might become confusing'? I would buy this justification if Angular's operator looked the same (`|>`). But it doesn't look the same, why would anybody expect it to have the same precedence?

**Comment by trotyl** [comment] 2018-12-04 09:58
@thorn0 

1. You're making a lexer hazard here, `b | x : c` could be recognized as pipe `x` with additional pipe parameter `c`. There may need to be some better error handling, but it's the syntax ambiguity rather than precedence issue.
2. The mental model for `Pipe` is a syntax sugar for function calls with better ergonomics, which is equivalent to JavaScript pipeline operator. The template language is a JavaScript subset with additional template utils, there's no reason to violates JavaScript deliberately if already conforming.

**Comment by gkalpak** [comment] 2018-12-04 10:15
TBH, I personally find that Angular's `|` has enough differences with `|>` anyway (e.g. appearance :grin:, order of arguments), that keeping one characteristic in sync (precedence) in the name of "mental model equivalence" is a weak argument. (Even more so that JS already has a `|` operator with totally different semantics, so we've missed the "reasonable equivalence" train, I'm afraid 😛).

In my mind, Angular's `|` is more like UNIX pipes and in that sense I would also expect them to have lower precedence (from a mental model pov).
m2c

<sub>FWIW, I would always parenthesize such complex expressions, regardless of the precedences :wink:</sub>

**Comment by trotyl** [comment] 2018-12-04 10:49
@gkalpak There's no operator nor expression in unix shell, making no concept of precedence there, and everything is associative due to the streaming, so that `(a p | b q) | c r` equals `a p | (b q | c r)`. Which is already impossible for a programming language.

**Comment by trotyl** [comment] 2018-12-04 11:09
@gkalpak Have had a check with the bash operator precedence, where [pipe do have higher precedence than logical operators](https://unix.stackexchange.com/a/163494) (`&&` or `||`, sadly there's no `?:` in bash):

```bash
echo "AbC" && echo "Def" | sed 's/[^a-z]//g'
```

Would be parsed as

```bash
echo "AbC" && (echo "Def" | sed 's/[^a-z]//g')
```

rather than

```bash
(echo "AbC" && echo "Def") | sed 's/[^a-z]//g'
```

**Comment by thorn0** [comment] 2018-12-04 11:56
@trotyl And what about `a | x ? b : c`? My point about `a ? b | x : c` is that it is inconsistent. If we want to apply a pipe to some operand of `a ? b : c`, why do we have to parenthesize `a` and `b`, but not `c`?

**Comment by petebacondarwin** [comment] 2021-10-15 15:32
This is being tracked in the aggregate issue of #43485 for which we need to create a project proposal.

**Comment by jelbourn** [comment] 2024-07-10 19:34
Duplicate of #43485

Closing this as a duplicate of #43485 even though they're not _exactly_ the same thing because it's the ultimate direction things will likely move. At this point, we think it's far too breaking of a change to change the operator precedence for pipes. Any changes here would be part of a much larger (and hypothetical) shift in the way Angular template expressions work.

**Closed by jelbourn** 2024-07-10 19:34 UTC
Labels: type: bug/fix, freq1: low, area: compiler, state: confirmed, core: binding & interpolation, core: pipes, P3, compiler: parser
