### ISSUE TITLE
Preloaded image with NgOptimizedImage gets double downloaded when Async operations gets triggered

### ISSUE THREAD

**Issue by exequiel09** [angular/angular#54045] opened 2024-01-24 05:58 UTC
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

No

### Description

Not sure if it's related to out of bounds CD but when I install https://github.com/angular/angularfire, with barebones setup of `provideFirebaseApp` and `provideRemoteConfig` it will trigger redownload of the image even if it was already preloaded by `link[rel=preload]` which was generated in a SSR app. The double download happens when the app gets change detected and the values of `src` and `srcset` gets assigned even if the the previous and the new value are the same.

I have a suspicion that this is not only restricted to @angular/fire but any code that might trigger CD on a non-destructive hydrated Angular app.

### Please provide a link to a minimal reproduction of the bug

https://github.com/exequiel09/nx-ng-seventeen-ngoptimized-image-download-issue

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.1.0
Node: 20.10.0
Package Manager: npm 10.2.5
OS: linux x64

Angular: 17.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router, ssr

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1701.0
@angular-devkit/build-angular   17.1.0
@angular-devkit/core            17.1.0
@angular-devkit/schematics      17.1.0
@angular/fire                   17.0.1
@schematics/angular             17.0.10
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.3
```

### Anything else?

Happens on both v16, v17.0 and v17.1

v16 repro = https://github.com/exequiel09/nx-ng-sixteen-ngoptimized-image-download-issue
v17 repro = https://github.com/exequiel09/nx-ng-seventeen-ngoptimized-image-download-issue

v17 repro can be upgrade to v17.1 and it still happens.

NOTE: make sure to check `disable cache` when testing as the browser will not try to download it if it's already in the cache. 

![image](https://github.com/angular/angular/assets/1289472/04506e03-5353-4ec4-b4b2-51b0260dc4bf)

**Comment by exequiel09** [comment] 2024-01-24 06:05
I feel life if we are able to detect the initial src of the image tag, we  could opt skipping setting again the `src`  🤔 
 https://github.com/angular/angular/blob/main/packages/common/src/directives/ng_optimized_image/ng_optimized_image.ts#L380

**Comment by exequiel09** [comment] 2024-01-25 01:40
This is without any dependency that triggers zoneful async operation

LCP Load Time is 1.4s

![image](https://github.com/angular/angular/assets/1289472/b977083d-71a6-46a3-90d7-304863935a91)

With any dependency that triggers zoneful async operation

LCP Load time is 2.5s (almost double)

![Screenshot 2024-01-25 093656](https://github.com/angular/angular/assets/1289472/83c6fd80-ffe4-40d4-a009-6db4f7a80015)

**Comment by exequiel09** [comment] 2024-01-25 01:49
> This is without any dependency that triggers zoneful async operation
> 
> LCP Load Time is 1.4s
> 
> ![image](https://private-user-images.githubusercontent.com/1289472/299510265-b977083d-71a6-46a3-90d7-304863935a91.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxNDcxNTMsIm5iZiI6MTcwNjE0Njg1MywicGF0aCI6Ii8xMjg5NDcyLzI5OTUxMDI2NS1iOTc3MDgzZC03MWE2LTQ2YTMtOTBkNy0zMDQ4NjM5MzVhOTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjVUMDE0MDUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODA4MjRhNzNjZWU2OThiZmUxZDE4Y2Q5Njc3ODYxOGY0MDg3YjVmNWM4MmFhZDU0ODJjNGFjY2ViYzNjMjBmNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.LmPbhLK49v048mOifXZoPZ_bdLf6d5dGt0rBPRzYP6M)
> 
> With any dependency that triggers zoneful async operation
> 
> LCP Load time is 2.5s (almost double)
> 
> ![Screenshot 2024-01-25 093656](https://private-user-images.githubusercontent.com/1289472/299510572-83c6fd80-ffe4-40d4-a009-6db4f7a80015.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxNDcxNTMsIm5iZiI6MTcwNjE0Njg1MywicGF0aCI6Ii8xMjg5NDcyLzI5OTUxMDU3Mi04M2M2ZmQ4MC1mZmU0LTQwZDQtYTAwOS02ZGI0ZjdhODAwMTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjVUMDE0MDUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWQ1ZDUxM2Y4NDk2ZjA5NmMzMzI3NWFkYzFiNzNmZmY4YzkwMjc3NzI2NGEzYjhlM2JiNThiYzc5OGY5NmE5MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.36Ox-STcBtlWedDw53fsrHlLKyYUDXCh2yDpL5KXTlc)

I'm not sure if LH considers the double download for the LCP element. If it is then it's a problem

**Comment by exequiel09** [comment] 2024-02-05 07:26
This also happens when you use `APP_INITIALIZER` token since it uses `Promise`s under the hood. Repro on this branch: https://github.com/exequiel09/nx-ng-seventeen-ngoptimized-image-download-issue/tree/app-initializer

**Comment by exequiel09** [comment] 2024-02-05 10:41
> > This is without any dependency that triggers zoneful async operation
> > LCP Load Time is 1.4s
> > ![image](https://private-user-images.githubusercontent.com/1289472/299510265-b977083d-71a6-46a3-90d7-304863935a91.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxNDcxNTMsIm5iZiI6MTcwNjE0Njg1MywicGF0aCI6Ii8xMjg5NDcyLzI5OTUxMDI2NS1iOTc3MDgzZC03MWE2LTQ2YTMtOTBkNy0zMDQ4NjM5MzVhOTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjVUMDE0MDUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODA4MjRhNzNjZWU2OThiZmUxZDE4Y2Q5Njc3ODYxOGY0MDg3YjVmNWM4MmFhZDU0ODJjNGFjY2ViYzNjMjBmNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.LmPbhLK49v048mOifXZoPZ_bdLf6d5dGt0rBPRzYP6M)
> > With any dependency that triggers zoneful async operation
> > LCP Load time is 2.5s (almost double)
> > ![Screenshot 2024-01-25 093656](https://private-user-images.githubusercontent.com/1289472/299510572-83c6fd80-ffe4-40d4-a009-6db4f7a80015.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxNDcxNTMsIm5iZiI6MTcwNjE0Njg1MywicGF0aCI6Ii8xMjg5NDcyLzI5OTUxMDU3Mi04M2M2ZmQ4MC1mZmU0LTQwZDQtYTAwOS02ZGI0ZjdhODAwMTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjVUMDE0MDUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWQ1ZDUxM2Y4NDk2ZjA5NmMzMzI3NWFkYzFiNzNmZmY4YzkwMjc3NzI2NGEzYjhlM2JiNThiYzc5OGY5NmE5MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.36Ox-STcBtlWedDw53fsrHlLKyYUDXCh2yDpL5KXTlc)
> 
> I'm not sure if LH considers the double download for the LCP element. If it is then it's a problem

It does affect LH scores of LCP element as per my testing on the project I'm working on. 😓

**Comment by AndrewKushnir** [comment] 2024-02-09 23:46
@exequiel09 as you mentioned in the ticket description, the problem only happens when you disable browser cache in the network tab. In this case, the behavior is expected: a browser loads an image again. This is a behavior unrelated to Angular and can be reproduced using plain HTML and JS.

Could you please let us know if you see any problems when the cache is enabled?

**Comment by exequiel09** [comment] 2024-02-09 23:58
@AndrewKushnir it doesn't redownload when cache is enabled. the problem here is that the `src` and `srcset` attribute is getting set to the very same value that causes the browser to redownload again when CD happens. And this is native browser behavior as you all have mentioned.

I feel like not setting again the image src to the same value when non-destructive hydration is enabled would fix this. if someone one to forcefully, redownload then it should be configurable with the directive.

One question, do you recommend do lighthouse test with disable cache unchecked?

**Comment by AndrewKushnir** [comment] 2024-02-10 00:12
Thanks for additional info @exequiel09.

> I feel like not setting again the image src to the same value when non-destructive hydration is enabled would 
> fix this. if someone want to forcefully redownload, then it should be configurable with the directive.

This would require reading an existing value from an image element, which has some performance cost associated with it. We believe that relying on a browser behavior in this scenario is the best approach.

> One question, do you recommend to do lighthouse test with disable cache unchecked?

I don't have a particular recommendation on lighthouse setup for your scenarios (and whether cache setting affects the results).

I'm closing this ticket for now, since there are no action items for the framework, the logic behaves as expected.

**Closed by AndrewKushnir** 2024-02-10 00:12 UTC
Labels: area: common, common: image directive, core: hydration
