### ISSUE TITLE
Provide typesafety for ComponentRef.setInput

### ISSUE THREAD

**Issue by c-harding** [angular/angular#54693] opened 2024-03-04 18:38 UTC
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

I would like to call setInput in my tests type-safely. I have recently migrated to OnPush, and found that setting properties directly on the input (`component.myInput = newValue; fixture.detectChanges()`) does not trigger change detection. Instead, I found two alternatives:

1. `fixture.componentRef.setInput('myInput', newValue)`
2. `component.myInput = newValue; fixture.changeDetectorRef.markForCheck(); fixture.detectChanges()`.

№ 2 adds boilerplate, and will not work with signals. Therefore № 1 is preferable. However, it does not offer any typesafety.

### Proposed solution

The following type signature for setInput:

``` ts
abstract class ComponentRef<C> {
  abstract setInput<K extends MutableKeys<C>>(name: K, value: C[K]): void;
}

type MutableKeys<T> = {
  [P in keyof T]-?: 
    // Check if trying to assign a value to the property P after it's been initialized
    // does not result in a type error (indicating it's mutable). If it's mutable, include the key P.
    // We use a conditional type here, where we try to assign a different type to the property P
    // and check if it's assignable to the original type T. If it is, it means the property is mutable.
    IfEquals<{ [Q in P]: T[P] }, { -readonly [Q in P]: T[P] }, P>
}[keyof T];

// Utility type to check if two types are exactly the same
type IfEquals<X, Y, A = X, B = never> = 
  (<T>() => T extends X ? 1 : 2) extends 
  (<T>() => T extends Y ? 1 : 2) ? A : B;
```

Sample usage:
```ts
class X {
  readonly a = 1;
  b = 2;
  c?: number;
  protected d = 4;
  private e = 5;
}

declare let componentRef: ComponentRef<X>;

// @ts-expect-error - a is readonly
componentRef.setInput("a", 1);

// b is mutable
componentRef.setInput("b", 2);

// c is mutable and optional
componentRef.setInput("c", 3);
componentRef.setInput("c", undefined);

// @ts-expect-error - d is protected
componentRef.setInput("d", 4);

// @ts-expect-error - e is protected
componentRef.setInput("e", 5);
```

[Typescript Playground](https://www.typescriptlang.org/play?ssl=10&ssc=1&pln=12&pc=1#code/IYIwzgLgTsDGEAJYBthjAgwgewLYAdsA7AUyIgCUSAzAHkwD4EBvAWACgEFRIZ4EwJCAEki+AK4RaAaQQkAHhDIATDAFlJoZCWkkAnmHoMGACiLBcJAFwJpAGgQA3YMnHWsAbWkBdAJQ3HbABLZQBuDgBfDg4IPXwSBA0ILR19QwAVJgBeFg4uDwAFBCCiBABrfWxqBHTvAFoAfhs8rgQAejasAAsSWDLi6ug9EoBzBAhsbnQgkdLgJxc3ccmIHoR8KGx4qFiEIuBqJShiiAByDBASMmKiIIgglyCALxJlFq4OhGVsEgwibEQUF+4mQiBK3HGcQSJCgm2OJhKyiCsGA9yIYzu5wQuE0IG0vgAdAhhNVMRgcck8SQHCUUOJlAlVgkKno9gT3u1OgB1BLiQQQ2DEJH3YguSHxBA9IEOADuUoSMsZUFZEymYBmcy+QWo1BhZEQsQlqqZ602212BQ5n2ARGUSB6fQGJyxaHVsxSy3Ga2wUBmJTFhoS6SJJJOxTANMQlhtGBNGy2MN2QXJuO07M4rRJAFEAI7iFyGZgIDwARRue28NnShW8CAiDiLdSBwG+RGQrNL5YKlZqNbrDgKDlIjhhDEiHhZVRq3nC7A4nwAqvdkHcVVDPbAHf1teMZSsoRhgEC5PI4BB216EmALCQYuvs3mC7QABoOACaDgAgggcq+EAAhH8EGHUcgJaExaEyExfB-Jh0hPJRbQwZ8EAaBAAEYEBsAAmGCFEQ1QEHAyDTBgrI4IQlQMDfVCMKwhBcNo78bH-WcOBQV0EBQtgM2bVsL3mHJ0NnLgQCA7CRKQJpgPEXBLigST4yUeBXi+ICABZFN9ZwlDkICAFZZyiOd2AZDjj20RBBQIYh9SoagbBwGzSHIeyXwYNj2E+AABCAwDqBR4ngALYR9BA6ghZMED44h23YvBCBcygaAJQQRDESQTAAImALKHHQ3xPM+MSoopFJ4ucuyUrS0QJAgbKQDyhjCuiLzOlgcNsVTBIbTtLYRXMZAKsSqrqFSoRasyrLYCagBmFr2GskbXOqiaMvq6amvEW0aBKV4FvnTpfP8wLeggEK4XCtSoqUs7XmG2yVrGmr1uy5QmvUg62oQY6AvkILzphS6IoSG7NmUpQ3kWhLHuS561rq7KSCa-TCqAA)

Open points:

1. support for signals
2. support for aliasing (though it would be acceptable for me to pass the property name rather than the alias)

### Alternatives considered

`component.myInput = newValue; fixture.changeDetectorRef.markForCheck(); fixture.detectChanges()`

- no support for signals
- extra boilerplate

**Comment by pkozlowski-opensource** [comment] 2024-03-04 18:47
Duplicate of #51878

**Closed by pkozlowski-opensource** 2024-03-04 18:47 UTC
