### ISSUE TITLE
Possible regression: ngOnDestroy is not called when providing using a factory function

### ISSUE THREAD

**Issue by sergidt** [angular/angular#47073] opened 2022-08-08 08:45 UTC
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

Related with this issue: https://github.com/angular/angular/pull/28737

Maybe a regression is possible. 

In this provided link, I create a simple provider instantiated with a factory. That logs its creation and destruction (ngOnDestroy). It seems ngOnDestroy is not being called since logs are not appearing (debugging is not stopping inside this function). 

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-rc5ojt?file=src%2Fapp%2Fapp.component.ts

### Please provide the exception or error you saw

```true
No exception nor errors.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: ~14.0.0

Package                                                Version
-------------------------------------------------------------------------------
    @angular/core                                     ^14.0.0
    @angular-devkit/build-angular                     ^14.0.0
```

**Comment by JoostK** [comment] 2022-08-08 09:37
Duplicate of #28738

**Closed** 2022-08-08 09:37 UTC

**Comment by sergidt** [comment] 2022-08-08 10:31
Ok make sense, sorry.
