### ISSUE TITLE
Dynamic created components do not fit correctly into ngTemplateOutlet

### ISSUE THREAD

**Issue by LE88I5** [angular/angular#28818] opened 2019-02-19 10:14 UTC
# 🐞 bug report

### Is this a regression?
No

### Description
Dynamic created components do not fit correctly into ngTemplateOutlet

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-dve4cy

## 🔥 Exception or Error
In the example above, fooooooo should be in a div with a yellow background.

**Angular Version:**
Last

**Comment by pkozlowski-opensource** [comment] 2019-02-19 10:32
> In the example above, fooooooo should be in a div with a yellow background.

Why do you assume so? You are inserting a component into a `ViewContainerRef` linked to `<ng-template #dynamicHost></ng-template>` which is _outside_ of the `<div>`. Then you are using `ngTemplateOutlet` to insert content of an _empty_ template which effectively is noop.

I think that there is a confusion going on here regarding `ViewContainerRef` - please note that `ViewContainerRef` adds elements as _siblings_ of a node on which `ViewContainerRef` was asked for.

Closing as it works as intended.

**Closed by pkozlowski-opensource** 2019-02-19 10:32 UTC

**Comment by LE88I5** [comment] 2019-02-19 10:57
> > 在上面的例子中，fooooooo应该在一个黄色背景的div中。
> 
> 你为什么这么认为？要插入一个组件插入到一个`ViewContainerRef`连接到`<ng-template #dynamicHost></ng-template>`这是_外面_的`<div>`。然后你`ngTemplateOutlet`用来插入一个有效的noop _空_模板的内容。
> 
> 我认为这里有一个混乱`ViewContainerRef`- 请注意，`ViewContainerRef`添加元素作为要求的节点的_兄弟姐妹_`ViewContainerRef`。
> 
> 关闭，因为它按预期工作。

Thank you, but I don't admit that the submitted example is wrong. He does not meet expectations. Otherwise, I will not be confused about this situation.
In the example, AppComponent is a dynamic component. Sometimes it needs a clean template, which is replaced by a specific component. Sometimes it wants to wrap a specific component and wrap some behaviors. Since it is closed, I can only find other methods.

**Comment by pkozlowski-opensource** [comment] 2019-02-19 11:09
While I can understand that the behaviour you are seeing is not matching your expectations, those are the rules under which Angular operates. It is hard for me to suggest the best approach here as I don't fully understand what you are trying to do but it _seems_ to me like `ngTemplateOutlet` is not really needed here and you can insert your dynamic component directly where you want it to be inserted, see: https://stackblitz.com/edit/angular-n4dwbs?file=src%2Fapp%2Fapp.component.ts

**Comment by LE88I5** [comment] 2019-02-19 11:38
> While I can understand that the behaviour you are seeing is not matching your expectations, those are the rules under which Angular operates. It is hard for me to suggest the best approach here as I don't fully understand what you are trying to do but it _seems_ to me like `ngTemplateOutlet` is not really needed here and you can insert your dynamic component directly where you want it to be inserted, see: https://stackblitz.com/edit/angular-n4dwbs?file=src%2Fapp%2Fapp.component.ts

AppComponent's ng-template will be created according to the type of configuration, the type is divided into two types: one is the container, ng-temlate will insert all the contents of that component, no need to wrap; the other is the field, all the field types are There are checkboxes as switches and concrete editors (input, checkbox, colorpicker, datepicker, etc.), I don't want each editor to have a checkbox to write the same logic and layout. Like the following code snippet: (Please forgive me, my English is very bad, if there is no good advice on this issue, I can try to find other methods).

```
<ng-template #gadgetHost></ng-template>
<div nz-row class="field" *ngIf="prop.isField">
  <div nz-col nzSpan="10" class="field-title">
    <label nz-checkbox [(ngModel)]="enabled" (ngModelChange)="toggleEnable($event)">{{prop.key}}</label>
  </div>
  <div nz-col nzSpan="14" class="field-content">
    <button nz-button nzType="primary" nzShape="circle" *ngIf="prop.types.length > 1" (click)="switchType()">S
    </button>
    <ng-container [ngTemplateOutlet]="gadgetHost"></ng-container>
  </div>
</div>
```
