### ISSUE TITLE
Cannot assign to read only property 'firstUpdatePass' of object '[object Object]'

### ISSUE THREAD

**Issue by sanjeevsubedi** [angular/angular#35308] opened 2020-02-10 19:59 UTC
With the migration to the latest angular version 9.0.0, there is now run-time error.

"dependencies": {
    "@angular/animations": "^9.0.0",
    "@angular/cdk": "^8.2.3",
    "@angular/common": "~9.0.0",
    "@angular/compiler": "~9.0.0",
    "@angular/core": "~9.0.0",
    "@angular/forms": "~9.0.0",
    "@angular/material": "^8.2.3",
    "@angular/material-moment-adapter": "^8.0.1",
    "@angular/platform-browser": "~9.0.0",
    "@angular/platform-browser-dynamic": "~9.0.0",
    "@angular/router": "~9.0.0",
    "core-js": "^2.5.4",
    "rxjs": "~6.5.3",
    "rxjs-compat": "^6.4.0",
    "text-mask-addons": "^3.8.0",
    "tslib": "^1.10.0",
    "zone.js": "~0.10.2"
  }

<img width="977" alt="DigitalHubReferenceWebApp_and_Slack___capco-platform-zero-ui___CATO_Digital" src="https://user-images.githubusercontent.com/985819/74185061-e51b0980-4c15-11ea-8494-2e239eb9d914.png">

**Comment by ericmartinezr** [comment] 2020-02-10 20:20
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.

**Comment by AndrewKushnir** [comment] 2020-02-10 22:59
Hi @sanjeevsubedi, it looks like the problem was caused by the fact that `Object.freeze` was called on a Component/Directive class by 3rd party code (not a framework code) and as a result, Ivy runtime was unable to update internal fields stored on Component def. The issue looks similar to https://github.com/angular/angular/issues/34993, but I don't see NgRx in the list of dependencies. As @ericmartinezr mentioned, we don't have enough information to investigate this issue further, so I'm closing this ticket for now. Please open a new one and include more information and repro, so that we can perform further investigation. Thank you.

**Closed by AndrewKushnir** 2020-02-10 22:59 UTC
