### ISSUE TITLE
HostBinding getter not recalculated after HostListener event

### ISSUE THREAD

**Issue by waterplea** [angular/angular#32083] opened 2019-08-09 17:13 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/core

### Is this a regression?

 No

### Description

 When you have a HostBinding getter it gets recalculated on every change detection cycle. When you have a HostListener, this event causes change detection to mark the view for checking and change detection is ran upwards the view tree. However sometimes even though event was triggered, change detection does not recalculate HostBinding causing expression changed error.

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-hostbinding-bug

Check out this example, here click on a button causes HostBinding to apply a class since focused element is within a component, change detection is triggered by focusin/focusout HostListener. There are two cases shown here:
1) with a fieldset getting disabled (thus unfocusing the button) straight up on the parent component, which works fine
2) fieldset buried inside a 'disabler' component, wrapping around its ng-content to disable stuff that it is wrapped around. This causes expression changed error, even though change detection is similarly triggered by HostListener on focusout when button gets disabled 

## 🔥 Exception or Error
<pre><code>ExpressionChangedAfterItHasBeenCheckedError
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>7+
</code></pre>

**Anything else relevant?**

**Comment by atscott** [comment] 2020-09-11 17:06
Confirmed, though this is more or less "working as expected" since host bindings execute after the template refreshes
https://github.com/angular/angular/issues/35443#issuecomment-631027816. So the template will execute and see `class._focused` as one value, then HostBindings execute which change the value. In the `checkNoChanges` pass, the class value during template execution is now different than what it was originally so the error is thrown.

**Comment by atscott** [comment] 2024-02-03 22:21
Closing as resolved by using a signal for the host binding state instead. Updating the signal value in the listener and reading in the host binding fixes the problem.

**Closed by atscott** 2024-02-03 22:21 UTC
Labels: type: bug/fix, freq1: low, area: core, state: confirmed, core: host and host bindings, core: change detection, P4
