### ISSUE TITLE
it's just about documentation ---

### ISSUE THREAD

**Issue by sk09049** [angular/angular#18685] opened 2017-08-14 18:24 UTC
https://angular.io/guide/architecture in this page 

after simple app.module.ts example  in 

the below paragraph ..

The export of **AppComponent** is just to show how to export; it isn't actually necessary in this example. A root module has no reason to export anything because other components don't need to import the root module.

i think ,instead of( **AppComponent** ) you must use AppModule.

if it is mistake please update ,i dont know how to report this.

**Comment by diegotham** [comment] 2017-08-14 18:33
It refers to the property of the module description "exports":

@NgModule({
...
  exports:      [ AppComponent ],
...
})

**Comment by hansl** [comment] 2017-08-14 19:12
Hi @sk09049,

That sentence is referring to the exports of the NgModule (specifically, the line pointed out by @diegotham). You still need to export your AppModule itself. 

I’ll notify our documentation team to see if there is anything we can improve, but I’m going to close this as working as intended. Cheers.

**Closed by hansl** 2017-08-14 19:12 UTC

**Comment by sk09049** [comment] 2017-08-15 06:22
ok my mistake only,thanks for reply
