### ISSUE TITLE
When using the ngFor loop and two-way data-binding, I want to receive better error message

### ISSUE THREAD

**Issue by splincode** [angular/angular#21914] opened 2018-01-30 19:43 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I use Primeng components. When I use ng-templates, I can not create a component, with a link to the instance. Angular compiler sends incomprehensible errors.

```html
<pre>{{cars|json}}</pre>
<p-dataTable [value]="cars">
   
    <p-column header="FieldInstance:">
      <ng-template let-car="rowData" let-index="rowIndex" pTemplate="body">
        [{{index}}]: {{car|json}}
        <car-entity [(value)]="car"></car-entity>
      </ng-template>
    </p-column>

</p-dataTable>
```

```
ERROR in : Error: Cannot assign to a reference or variable!
    at _AstToIrVisitor.visitPropertyWrite (C:\Users\splincode\Desktop\dev\rosnfo-ui\rosnfo-ui\node_modules\@angular\compiler\bundles\compiler.umd.js:26426:23)
    at PropertyWrite.visit (C:\Users\splincode\Desktop\dev\rosnfo-ui\rosnfo-ui\node_modules\@angular\compiler\bundles\compiler.umd.js:4722:24)
    at convertActionBinding (C:\Users\splincode\Desktop\dev\rosnfo-ui\rosnfo-ui\node_modules\@angular\compiler\bundles\compiler.umd.js:25850:45)
    at C:\Users\splincode\Desktop\dev\rosnfo-ui\rosnfo-ui\node_modules\@angular\compiler\bundles\compiler.umd.js:28450:22
    at Array.forEach (<anonymous>)
    at ViewBuilder._createElementHandleEventFn (C:\Users\splincode\Desktop\dev\rosnfo-ui\rosnfo-ui\node_modules\@angular\compiler\bundles\compiler.umd.js:28446:18)
    at nodes.(anonymous function) (C:\Users\splincode\Desktop\dev\rosnfo-ui\rosnfo-ui\node_modules\@angular\compiler\bundles\compiler.umd.js:27865:27)
    at C:\Users\splincode\Desktop\dev\rosnfo-ui\rosnfo-ui\node_modules\@angular\compiler\bundles\compiler.umd.js:28391:22
    at Array.map (<anonymous>)
    at ViewBuilder._createNodeExpressions (C:\Users\splincode\Desktop\dev\rosnfo-ui\rosnfo-ui\node_modules\@angular\compiler\bundles\compiler.umd.js:28390:56)
    at ViewBuilder.build (C:\Users\splincode\Desktop\dev\rosnfo-ui\rosnfo-ui\node_modules\@angular\compiler\bundles\compiler.umd.js:27627:23)
    at C:\Users\splincode\Desktop\dev\rosnfo-ui\rosnfo-ui\node_modules\@angular\compiler\bundles\compiler.umd.js:27626:63
    at Array.forEach (<anonymous>)
    at ViewBuilder.build (C:\Users\splincode\Desktop\dev\rosnfo-ui\rosnfo-ui\node_modules\@angular\compiler\bundles\compiler.umd.js:27626:23)
    at ViewCompiler.compileComponent (C:\Users\splincode\Desktop\dev\rosnfo-ui\rosnfo-ui\node_modules\@angular\compiler\bundles\compiler.umd.js:27527:60)
    at AotCompiler._compileComponent (C:\Users\splincode\Desktop\dev\rosnfo-ui\rosnfo-ui\node_modules\@angular\compiler\bundles\compiler.umd.js:31006:62)
```

https://stackblitz.com/edit/angular-eiskqo?file=app/app.component.html

## Expected behavior

If you comment on a piece of code, you can see that `car` is an object that you can use in the future. But I can not create a component ...

https://stackblitz.com/edit/angular-bd7std?file=app/app.component.html

![image](https://user-images.githubusercontent.com/12021443/35587381-b010f8f2-060e-11e8-8c21-4f55f51deb15.png)

```html
<pre>{{cars|json}}</pre>
<p-dataTable [value]="cars">
   
    <p-column header="FieldInstance:">
      <ng-template let-car="rowData" let-index="rowIndex" pTemplate="body">
        [{{index}}]: {{car|json}}
        <!--<car-entity [(value)]="car"></car-entity>-->
      </ng-template>
    </p-column>

</p-dataTable>
```

Of course, you can bypass the error in this way:

```html
<pre>{{cars|json}}</pre>
<p-dataTable [value]="cars">
   
    <p-column header="FieldInstance:">
      <ng-template let-car="rowData" let-index="rowIndex" pTemplate="body">
        [{{index}}]: {{car|json}}
        <car-entity [(value)]="cars[index]"></car-entity>
        <!-- OR: <car-entity [value]="car" (valueChange)="valueChange()"></car-entity> -->
      </ng-template>
    </p-column>

</p-dataTable>
```

But in my opinion this is a cant, if we can not normally logically handle the code according to the syntax [(**)]. I would like to know the cause of the error.

https://stackblitz.com/edit/angular-c356jp?file=app/app.component.html

![image](https://user-images.githubusercontent.com/12021443/35588618-43267560-0612-11e8-8a08-0f72e87dcb39.png)

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-eiskqo?file=app/app.component.html

<pre><code>Angular version: 5.x.x

**Comment by lacroixdavid1** [comment] 2018-01-30 20:31
@splincode This is not related to `ng-template`, it's `*ngFor` related. You can't reassign a `*ngFor` value.

This would cause problems too : 

````html
     <div *ngFor="let car of cars">
         <car-entity [(value)]="car"></car-entity> 
      </div>
```

**Comment by trotyl** [comment] 2018-01-31 02:24
Duplicate of #17144

**Comment by splincode** [comment] 2018-01-31 10:33
https://github.com/angular/angular/issues/19819
I realized that this is not a bug. But I want to see an adequate error, with an example of how not to do in the template...

**Comment by trotyl** [comment] 2018-01-31 11:00
By convention "better error message" should be consider feature request rather than bug report, also it's better to update the title & description for that for not making others confused.

**Comment by splincode** [comment] 2018-01-31 11:08
I do renamed issue

**Comment by splincode** [comment] 2018-01-31 11:09
@lacroixdavid1 

Analogia:

```
const items = [1, 2, 3]
for (let item of items) {
  item = item + 1
}
```

**Comment by lacroixdavid1** [comment] 2018-01-31 12:05
Dont mix up template for and typescript for they do not work the same

**Comment by mhevery** [comment] 2018-02-06 23:17
The error was `Error: Cannot assign to a reference or variable!` What error would you like to see? It should be trivial to change that string and send a PR.

**Closed** 2018-07-30 10:45 UTC
Labels: comp: core & compiler, freq1: low, severity1: confusing, type: bug/fix
