### ISSUE TITLE
HTML Custom Elements which inherit from an existing element don't instantiate correctly when used in HTML templates

### ISSUE THREAD

**Issue by The-MAZZTer** [angular/angular#41348] opened 2021-03-25 22:56 UTC
# 🐞 bug report

### Affected Package

Not sure, whatever handles populating HTML templates.

### Is this a regression?

No idea, sorry.

### Description

A great example is x-frame-bypass, and this confused user in particular:

https://github.com/niutech/x-frame-bypass/issues/22

x-frame-bypass is a custom element that inherits from iframe and does some... interesting things. Regardless, if you drop it into angular and attempt to use it in an HTML template, it's clear a normal iframe gets created despite the output HTML being correct. If you manually use element.innerHTML to inject the custom element it works properly.

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-ivy-ztlius

Top frame is added with HTML templates, bottom with innerHtml injection. Both tags should function identically.

## 🔥 Exception or Error
Placing breakpoints in the constructor of the x-frame-bypass class will confirm it is only instantiated for the bottom frame. It looks like the top frame is being instantiated as a normal iframe.

## 🌍  Your Environment

**Angular Version:**
Angular CLI: 11.1.4
Node: 14.16.0
OS: win32 x64

Angular: 11.1.2
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1101.4
@angular-devkit/build-angular   0.1101.4
@angular-devkit/core            11.1.4
@angular-devkit/schematics      11.1.4
@angular/cdk                    11.2.0
@angular/cli                    11.1.4
@angular/material               11.2.0
@schematics/angular             11.1.4
@schematics/update              0.1101.4
rxjs                            6.6.3
typescript                      4.1.5

Also, reproduces in stackblitz which I assume is the latest and greatest?

**Anything else relevant?**

Related bug report on x-frame-bypass: https://github.com/niutech/x-frame-bypass/issues/22 (Assuming the reporter confirm my suspicions, at least.)

**Comment by jelbourn** [comment] 2021-03-29 21:07
Duplicate of #6827

**Closed by jelbourn** 2021-03-29 21:07 UTC
Labels: comp: elements
