### ISSUE TITLE
Angular IVY innerHTML directive broken, throws error in SSR

### ISSUE THREAD

**Issue by naveedahmed1** [angular/angular#32514] opened 2019-09-06 19:53 UTC
# 🐞 bug report

### Affected Package
**innerHTML** directive

### Is this a regression?

Yes, the previous version in which this bug was not present was: Angular 8.x

### Description
When we have IVY enabled for an SSR/Universal app, and use innerHTML in component. It throw below error

`ERROR ReferenceError: document is not defined`

## 🔬 Minimal Reproduction

Just add innerHTML to any component and it should throw error. For example:

`<div [innerHTML]="'hello'"></div>`

## 🔥 Exception or Error
<pre><code>
`ERROR ReferenceError: document is not defined`
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular 9.0.0-next.5
Angular CLI: 9.0.0-next.3
</code></pre>

**Comment by tuurbo** [comment] 2019-10-24 03:51
Still an issue as of

```
Angular CLI: 9.0.0-next.13
Node: 13.0.1
OS: win32 x64
Angular: 9.0.0-next.13
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-next.15
@angular-devkit/build-angular     0.900.0-next.15
@angular-devkit/build-optimizer   0.900.0-next.15
@angular-devkit/build-webpack     0.900.0-next.15
@angular-devkit/core              9.0.0-next.15
@angular-devkit/schematics        9.0.0-next.13
@angular/cdk                      9.0.0-next.0
@angular/material                 9.0.0-next.0
@angular/pwa                      0.900.0-next.15
@ngtools/webpack                  9.0.0-next.15
@nguniversal/common               9.0.0-next.5
@nguniversal/express-engine       9.0.0-next.5
@schematics/angular               9.0.0-next.13
@schematics/update                0.900.0-next.13
rxjs                              6.5.3
typescript                        3.6.4
webpack                           4.41.2
```

**Comment by naveedahmed1** [comment] 2019-11-06 01:57
Any update on this?

**Comment by IgorMinar** [comment] 2019-11-11 19:59
this should be fixed by https://github.com/angular/angular/pull/33712

**Comment by IgorMinar** [comment] 2019-11-11 20:00
I'm going to close this as dupe of #33651

**Closed by IgorMinar** 2019-11-11 20:00 UTC
Labels: comp: ivy, comp: server, severity5: ivy-compat, state: has PR
