### ISSUE TITLE
FormGroup and FormArray ValueChanges stream disrupts based on FormControl registration order

### ISSUE THREAD

**Issue by alexis-landrieu-avanade** [angular/angular#58240] opened 2024-10-17 08:43 UTC
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

No

### Description

Depending on the setup order, either FormGroup or FormArray disrupts the valueChanges stream of the other.

## Flowchart 
```mermaid
flowchart TD
    A[Start] --> B{Setup Order}
    B -->|Init FormGroup with FormControl first| C[FormGroup Setup]
    B -->|Init FormArray with FormControl first| D[FormArray Setup]
    C --> E[FormArray Setup]
    D --> F[FormGroup Setup]
    E --> G{Disruption}
    F --> G{Disruption}
    G -->|FormGroup Disrupted| H[FormGroup valueChanges Stream Disrupted]
    G -->|FormArray Disrupted| I[FormArray valueChanges Stream Disrupted]
```

## Example code with both scenarios
```typescript
    if (this.mode === 'InitFormGroupWithFormControlFirst') {
      this.formGroup = new FormGroup({ formControl: this.formControl });
      this.formArray.push(this.formControl);
    } else {
      this.formArray.push(this.formControl);
      this.formGroup = new FormGroup({ formControl: this.formControl });
    }

    this.formGroup.valueChanges.subscribe((changes) =>      console.log('formGroup-valueChanges', changes)    );
    this.formArray.valueChanges.subscribe((changes) =>      console.log('formArray-valueChanges', changes)    );

   // Then trigger change on formControl
   this.formControl.setValue(Date.now());  
```

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-wheeka?file=src%2Fapp%2Foverlap.component.ts

### Please provide the exception or error you saw

The property valueChanges (RxJs Observable) of the disruped control (FormGroup or FormArray) is not triggered anymore.

### Please provide the environment you discovered this bug in (run `ng version`)

Angular CLI: 18.0.6
Node: 18.20.3
Package Manager: npm 10.2.3
OS: linux x64

Angular: 18.0.5
... animations, cdk, common, compiler, compiler-cli, core, forms
... material, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1800.6
@angular-devkit/build-angular   18.0.6
@angular-devkit/core            18.0.6
@angular-devkit/schematics      18.0.6
@angular/cli                    18.0.6
@schematics/angular             18.0.6
rxjs                            7.8.1
typescript                      5.4.5
zone.js                         0.14.7

**Comment by garrettld** [comment] 2024-10-17 13:20
The root cause here is that form controls can only have one parent. Whichever parent is assigned last is the one that sees the value changes from the child control.

This has come up before, see https://github.com/angular/angular/issues/50957 for example

**Comment by JeanMeche** [comment] 2024-10-17 13:27
Closing as duplicate.

**Closed by JeanMeche** 2024-10-17 13:27 UTC
