### ISSUE TITLE
Unclear error message for badly configured custom form controls

### ISSUE THREAD

**Issue by mwaibel-go** [angular/angular#44486] opened 2021-12-15 09:42 UTC
### Which @angular/* package(s) are relevant/releated to the feature request?

forms

### Description

I was hitting the following error when implementing a custom form control:

```
ERROR Error: Value accessor was not provided as an array for form control with unspecified name attribute
    at _throwError (forms.mjs:1752)
    at selectValueAccessor (forms.mjs:1782)
    at new FormControlName (forms.mjs:5743)
    at NodeInjectorFactory.FormControlName_Factory [as factory] (forms.mjs:5827)
    at getNodeInjectable (core.mjs:3556)
    at searchTokensOnInjector (core.mjs:3493)
    at getOrCreateInjectable (core.mjs:3437)
    at ɵɵdirectiveInject (core.mjs:14720)
    at ɵɵinject (core.mjs:4778)
    at NodeInjectorFactory.factory (core.mjs:11563)
```

It was very unclear to me what this error message meant or how to fix it. My form controls all had names and formControlNames.

Only by uncommenting parts of my form could I even find the offending form control, since the error doesn’t specify what it was trying to do when the error occured.

Googling the error only brought up the [source code for the test](https://github.com/angular/angular/blob/master/packages/forms/test/directives_spec.ts#L53) regarding this error, but there’s no explanation _why_ an error is thrown there, either.

The actual error was that my form control was badly configured, i.e. it provided the NG_VALUE_ACCESSOR like this:

```
  providers: [
    { provide: NG_VALUE_ACCESSOR, useExisting: MyControl},
  ]
```
instead of this
```
  providers: [
    { provide: NG_VALUE_ACCESSOR, useExisting: forwardRef(() => MyControl), multi: true },
  ]
```

Maybe related? Maybe related: https://github.com/angular/angular/issues/3011

Here’s a reproduction: https://stackblitz.com/edit/angular-ivy-e2wj4z?file=src/app/app.component.ts

### Proposed solution

Since I still don’t know the actual cause of the error, I can’t propose a solution to a clearer error message. It would be nice to know the class or form control *something* was trying to process when the error happens.

Andrew Kushnir [proposed a solution](https://github.com/angular/angular/issues/44486#issuecomment-996307788):

> I think we can improve the error message by including a note like this:
> 
> ```
> Value accessor was not provided as an array for form control with unspecified name attribute.
> Please make sure that the `NG_VALUE_ACCESSOR` token is configured as a multi provider (with the `multi: true` property).
> ```
> 
> I think there might also be an opportunity to improve the logic around getting the attribute name (so that there is a real name vs "unspecified attribute").

### Alternatives considered

—

**Comment by AndrewKushnir** [comment] 2021-12-17 00:34
Hi @mwaibel-go, the mentioned error was caused by the missing `multi: true` in your code:

```
{ provide: NG_VALUE_ACCESSOR, useExisting: MyControl}
```

which makes it a regular provider (vs a multi provider that the code expects). Here is the code location:

https://github.com/angular/angular/blob/8ebc946c0e7bf80d26ec8268acb4ff0af9e5c34a/packages/forms/src/directives/shared.ts#L317-L318

I think we can improve the error message by including a note like this:

```
Value accessor was not provided as an array for form control with unspecified name attribute.
Please make sure that the `NG_VALUE_ACCESSOR` token is configured as a multi provider (with the `multi: true` property).
```

I think there might also be an opportunity to improve the logic around getting the attribute name (so that there is a real name vs "unspecified attribute"). Could you please create a simple example of your structure using [Stackblitz](https://stackblitz.com/), so that we can look at the logic that calculates the name and see if there is a way to improve it?

**Comment by mwaibel-go** [comment] 2021-12-21 12:34
Thank you for responding. Yes, I can certainly provide a repro. It might take until the weekend, though.

Sorry for replying so late. I did not get a notification for your response.

**Comment by bleistift-zwei** [comment] 2021-12-22 18:56
Here is a reproduction from my alt account: [https://stackblitz.com/edit/angular-ivy-e2wj4z?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-ivy-e2wj4z?file=src/app/app.component.ts)

**Comment by ameryousuf** [comment] 2022-02-08 18:40
@AndrewKushnir Can I work on this issue?

**Comment by AndrewKushnir** [comment] 2022-02-08 18:43
@ameryousuf sure, please let me know if you have any questions. Thank you.

**Comment by ameryousuf** [comment] 2022-02-24 14:49
@AndrewKushnir I changed the error message as you suggested, and opened the PR.

However, regarding improving the logic around getting the attribute name (so that there is a real name vs "unspecified attribute"), do you have any idea how to improve it?

Since the `selectValueAccessor` function is being called from the constructors of `NgModel`, `FormControlDirective`, and `FormControlName` directives, where the `name` property doesn't have a value yet. 

Besides, we can't move the call of the `selectValueAccessor` function to the lifecycle hooks.

**Comment by AndrewKushnir** [comment] 2022-03-01 03:08
@ameryousuf thanks for creating the PR and sorry for the delay in answering.

If I understand correctly, the problem happens with the `NgModel` only (for the FormControlDirective and FormControlName) we should have the necessary info in the error message). If so, we can add a special check in the `_throwError` function like this:

```
--- a/packages/forms/src/directives/shared.ts
+++ b/packages/forms/src/directives/shared.ts
@@ -15,6 +15,7 @@ import {ControlContainer} from './control_container';
 import {BuiltInControlValueAccessor, ControlValueAccessor} from './control_value_accessor';
 import {DefaultValueAccessor} from './default_value_accessor';
 import {NgControl} from './ng_control';
+import {NgModel} from './ng_model';
 import {FormArrayName} from './reactive_directives/form_group_name';
 import {ngModelWarning} from './reactive_errors';
 import {AsyncValidatorFn, Validator, ValidatorFn} from './validators';
@@ -278,6 +279,8 @@ function _throwError(dir: AbstractControlDirective, message: string): void {
     messageEnd = `path: '${dir.path!.join(' -> ')}'`;
   } else if (dir.path![0]) {
     messageEnd = `name: '${dir.path}'`;
+  } else if ((dir instanceof NgModel) && !!dir.name) {
+    messageEnd = `name: '${dir.name}'`;
   } else {
     messageEnd = 'unspecified name attribute';
   }
```

My proposal is to proceed with PR #45192 without this change and create a followup PR (which would also require some tests). Please let me know if any additional information is needed.

Thank you.

**Comment by ameryousuf** [comment] 2022-03-13 18:48
@AndrewKushnir Thanks for your reply.

Actually, it's related to  the `FormControlDirective` and `FormControlName` directives also, not only to the `NgModel`.

Why? Because the `selectValueAccessor` function is being called from the `constructor` of these directives, where the `@Input('name')` is not being initialized yet, and will be always `undefined` in this stage.

So, your suggestion won't work in this case.

We can resolve it by calling the `selectValueAccessor` function from `ngOnInit` instead of `constructor`, BUT, this of course, will break all the cases that require the `valueAccessor` to be initialized in the `constructor` not after that.

Thank you.

**Comment by AndrewKushnir** [comment] 2022-03-15 02:23
@ameryousuf thanks for the comment. You are right, the inputs wouldn't be available until the first `ngOnChanges` call. I think it might be a bit too risky to move the `valueAccessor` calculation to the `ngOnChanges` hook as there might be some code that would rely on it being available sooner than that... I think we should put this change on hold for now and we can come back to that once we do bigger refactoring in the future.

**Comment by ameryousuf** [comment] 2022-03-15 06:03
Okay, thanks @AndrewKushnir.

Please let me know if you need any help in the future. Thanks!

**Comment by akushnarov** [comment] 2022-07-22 08:40
Dear @dylhunn and @AndrewKushnir, I was looking at the "good first issue" list and I found this issue. I'd like to contribute, but first I wanted to check with you. I see a PR [45192](https://github.com/angular/angular/pull/45192) which was closed for inactivity, should I take it as a base? What would you suggest to the beginner? :)

**Comment by ashide2729** [comment] 2022-07-22 16:11
looks like the pr is already closed after committing the changes, maybe the issue is still open because of the second problem that is yet to be addressed which is [this](https://github.com/angular/angular/issues/44486#issuecomment-1054950154)
and if the issue is already fixed maybe we can close the issue as it confusing for other people who are trying to contirbute

**Comment by AndrewKushnir** [comment] 2022-07-22 16:57
Sorry about the confusion. I think the error message was improved in https://github.com/angular/angular/pull/45192, so we can close this ticket. Thank you.

**Closed by AndrewKushnir** 2022-07-22 16:57 UTC
Labels: feature, help wanted, hotlist: error messages, comp: forms, good first issue, in backlog

**Comment by ashide2729** [comment] 2022-07-23 08:47
thank you for the quick response
