### ISSUE TITLE
Include the expression in the ExpressionChangedAfterItHasBeenCheckedError

### ISSUE THREAD

**Issue by FiretronP75** [angular/angular#50272] opened 2023-05-12 21:21 UTC
### Description

When ExpressionChangedAfterItHasBeenCheckedError is thrown, it logs the previous value and the current value and a stack trace. However, it is difficult to see in the stack trace which component is causing the error.

### Proposed solution

Add the expression that threw the error into the message. This will make it clear at a glance where the problem is.

### Alternatives considered

Add the template file that threw the error (can get this from the stack trace) into the message. This will show you what file name to look for as you are scanning the stack trace for it.

**Comment by JeanMeche** [comment] 2023-05-13 12:08
Hi, I believe this a dupe of #18970.

**Comment by AndrewKushnir** [comment] 2023-05-14 01:01
I think we can improve the current error to include the name of the component where the problem happened. We have a similar function here: https://github.com/angular/angular/blob/main/packages/core/src/render3/instructions/element_validation.ts#L260-L276 and we can reuse it (as it or reuse parts of the logic from it) for the ExpressionChangedAfterItHasBeenCheckedError.

(we can still keep the https://github.com/angular/angular/issues/18970 open as a tracking issue for further improvements)

**Comment by JeanMeche** [comment] 2023-06-29 17:24
With #50286 being merged, I'll close this issue. We'll be continue tracking improvement at #18970

**Closed by JeanMeche** 2023-06-29 17:24 UTC
Labels: help wanted, hotlist: error messages, area: core, core: change detection
