### ISSUE TITLE
Angular AOT server doesn't play nicely with Bazel for LocationUpgradeModule

### ISSUE THREAD

**Issue by achew22** [angular/angular#31873] opened 2019-07-28 07:43 UTC
# 🐞 bug report

### Affected Package

The issue is caused by the interaction of `@angular/common/upgrade` with the Bazel based AOT compiler. 

### Is this a regression?

No, this has not worked in any older versions.

### Description

 When you attempt to import `LocationUpgradeModule.config()` as a dependency you get a difficult error message that doesn't quite scan for me.

## 🔬 Minimal Reproduction

I've created a repo that has an approximately minimal reproduction. In [this commmit](https://github.com/achew22/angular-bazel-demo/commit/140f14e7707d5d26acbe4bcc4444509caee9ad8d) I start loading `LocationUpgradeModule.config()` and `UpgradeModule` in my [`AppModule`](https://github.com/achew22/angular-bazel-demo/commit/140f14e7707d5d26acbe4bcc4444509caee9ad8d#diff-9c65dd65fa6398eefd837de234828683). However, when I add this, I get the following exception.

## 🔥 Exception or Error

```
Loading: 0 packages loaded
Analyzing: 14 targets (0 packages loaded, 0 targets configured)
INFO: Analyzed 14 targets (0 packages loaded, 0 targets configured).
INFO: Found 14 targets...
[0 / 1] [Prepa] BazelWorkspaceStatusAction stable-status.txt
[1 / 39] Compiling Angular templates (ngc) //my-app/src:src; 1s worker ... (2 actions running)
ERROR: /home/achew22/Projects/angular-bazel-demo/my-app/src/BUILD.bazel:27:1: Compiling Angular templates (ngc) //my-app/src:src failed (Exit 1)
Error during template compile of 'AppModule'
  Function calls are not supported in decorators but 'LocationUpgradeModule' was called.
: Unexpected value 'undefined' imported by the module 'AppModule in /home/achew22/.cache/bazel/_bazel_achew22/e93e1b7ac2af1e379678c6e725b6b9dc/execroot/project/my-app/src/app/app.module.ts'
Error during template compile of 'AppModule'
  Function calls are not supported in decorators but 'LocationUpgradeModule' was called.

INFO: Elapsed time: 6.126s, Critical Path: 5.22s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
```

## 🌍  Your Environment

**Angular Version:**
I don't think `ng version` is the correct dep version, but I do have

```
    "@angular/bazel": "~8.1.0",
```

in my [`package.json`](https://github.com/achew22/angular-bazel-demo/blob/master/package.json), which I believe is the information you want.

**Things I've done to try to fix it**

I tried running this outside of the sandbox to see if that helped (it didn't), and I also tried turning on [`trace`](https://github.com/angular/angular/blob/e8ae3c5f2efe01acee894f3ea094544689310066/packages/compiler-cli/src/transformers/api.ts#L40) which didn't print any additional output. I would love to debug this myself, but I don't know how to even manipulate at the abstraction layer where this is happening. Sorry.

**Anything else relevant?**

@gregmagolan and @alexeagle since I think they are working on Angular/Bazel.

Thanks so much!

**Comment by alexeagle** [comment] 2019-08-21 20:57
@mrmeku is on the right track - we didn't include these files in the postinstall script which runs ngc using the angular-metadata.tsconfig.json.
The upgrade packages are excluded because `@angular/common/upgrade` and `@angular/router/upgrade` reference `@angular/upgrade/static` but their package.json files don't declare a dependency on `@angular/upgrade`.

So I think the answer is to install `@angular/upgrade` and remove those exclusions from the `angular-metadata.tsconfig.json`.

(Also I think it's a bug that the .d.ts has a broken reference like this)

**Comment by alexeagle** [comment] 2019-08-21 21:02
https://github.com/angular/angular/issues/32249 is that last bit

**Comment by achew22** [comment] 2019-08-22 06:05
@alexeagle thanks for investigating this!

**Comment by petebacondarwin** [comment] 2020-05-28 13:01
I can confirm that installing `@angular/upgrade` and then removing

```
    "node_modules/@angular/common/upgrade*",
    "node_modules/@angular/router/upgrade*"
```

from the `angular-metadata.tsconfig.json` file does allow the installation and then `ng build` to complete successfully.

This seems like the right approach here.

**Comment by alxhub** [comment] 2022-03-14 23:27
Closing as obsolete - the Bazel builder and associated CLI functionality are deprecated and no longer supported.

**Closed by alxhub** 2022-03-14 23:27 UTC
Labels: type: bug/fix, comp: common, freq1: low, workaround2: non-obvious, comp: bazel, comp: upgrade, type: confusing, triage #1, P4
