### ISSUE TITLE
feature request (router): add interstitial loading component option to be used with guards/resolvers

### ISSUE THREAD

**Issue by ilovett** [angular/angular#19187] opened 2017-09-13 19:41 UTC
## I'm submitting a...
[X] Feature request

## Current behavior
Resolvers do not enter states until data is resolved.

## Desired behavior
Option to show an interstitial state where the url has not changed yet, but a defined loading component EG: `resolvingComponent` or `loadingComponent` for the intended state is swapped with the current url's component (but the url does not change).  Once the data is resolved, the url changes and the intended state's `resolvingComponent` is swapped for the `component`.

If there is an error, goes swaps loading component back to the current route's component.

May also be nice to have an error handle?

May want to define explicitly for CanActivate vs. Resolve or may just not make sense to use this for guards.

```
export const routes: Routes = [
  {
    path: 'my-page',
    component: MyPageComponent
    resolve: {
      data: MyDataResolver
    },
    resolvingComponent: MyPageLoadingComponent
    ...
  }
  ...
```

```
@Component({
  selector: 'my-page-loading-component',
  template: '<some-spinner /> Loading {{ resolvers.thingOne }}...'
})

(inject snapshot of all resolver observables for displaying progress, etc.)

```

**Comment by atscott** [comment] 2021-07-23 23:30
duplicate of #42489

**Closed by atscott** 2021-07-23 23:30 UTC
Labels: comp: router, feature, insufficient votes, votes required
