### ISSUE TITLE
Language Service: prioritize suggesting component inputs first

### ISSUE THREAD

**Issue by petermikitsh** [angular/angular#36988] opened 2020-05-07 20:28 UTC
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/language-service

### Description

I have a component in a third-party library of components. One component with selector `ds-avatar` has inputs `size` and `label`, as shown in the decorator below:

```tsx
@Component({
  selector: 'ds-avatar',
  inputs: ["size","label"],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>'
})
export class DSAvatar { ... }
```

In my IDE, suggestions for properties shows `label`, a long list of angular options, then `size`.

<img width="497" alt="Screen Shot 2020-05-07 at 1 28 04 PM" src="https://user-images.githubusercontent.com/1571918/81341604-ac4cce00-9066-11ea-8f23-419e8bdd6c5a.png">

<img width="450" alt="Screen Shot 2020-05-07 at 1 25 53 PM" src="https://user-images.githubusercontent.com/1571918/81341505-81627a00-9066-11ea-8574-ebb1590b966b.png">

### Describe the solution you'd like

Show component inputs first, before all other options.

### Describe alternatives you've considered

No alternatives have been identified.

**Comment by atscott** [comment] 2022-03-02 01:12
Closing as duplicate of https://github.com/angular/vscode-ng-language-service/issues/1537

**Closed by atscott** 2022-03-02 01:12 UTC
Labels: feature, comp: language-service, P3, insufficient votes, votes required
