### ISSUE TITLE
[zonejs] XMLHttpRequest macrotask left hanging if `onload` throws

### ISSUE THREAD

**Issue by mleibman** [angular/angular#41520] opened 2021-04-08 20:45 UTC
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/zone.js.

### Is this a regression?
AFAICT it has always been like this.

### Description
ZoneJS invokes the XHR macrotask after all existing `load` handlers run, but if any of them throw an unhandled exception, the task remains stuck in a `scheduled` state and none of the delegate hooks (e.g. `onInvokeTask()`) run. This creates problems for test environments and any instrumentation that relies on task counts.

(It is somewhat similar to issue #38795.)

## 🔬 Minimal Reproduction
```javascript
Zone.root
  .fork({
    name: 'xhr',
    onHasTask(delegate, currentZone, zone, taskState) {
      console.log('hasMacrotask', taskState.macroTask);
      return delegate.hasTask(zone, taskState);
    },      
  })
  .run(() => {
    const xhr = new XMLHttpRequest();
    xhr.open('GET', 'https://cdnjs.cloudflare.com/ajax/libs/zone.js/0.11.4/zone.min.js');
    xhr.addEventListener('load', () => {
      throw new Error();
    });
    xhr.send();
  });
```

This code ends by printing `hasMacrotask true` and the XHR task left in a `scheduled` state.

Note that this repro specifically forks the root zone. If you try to repro this in StackBlitz or in Angular's `NgZone` and for the current zone instead, you'll need to wrap the `addEventListener()` call in `Zone.root.run()` to make it work. The reason is that `NgZone` implements a `onHandleError()` delegate hook that always returns false, and the exception get swallowed instead of being thrown.

**Comment by mleibman** [comment] 2021-04-08 21:13
Actually, I think the error is rooted a bit deeper in the `globalZoneAwareCallback` where it executes the event handlers:

https://github.com/angular/angular/blob/51bb922a081a1059929cb549ffbc3cf1d1366e2a/packages/zone.js/lib/common/events.ts#L150-L155

Each handler is called directly, meaning if it errors out, all remaining tasks are ignored. This is inconsistent with W3C event handling, which runs each callback independently.


### Repro

When run directly, clicking the button prints both `click 1` and `click 2`.
When run with ZoneJS loaded, only `click 1` is printed.

```javascript
(function() {
  const btn = document.body.appendChild(document.createElement('button'));
  btn.textContent = 'Click me';

  btn.addEventListener('click', () => {
    console.log('click 1');
    throw new Error();
  });

  btn.addEventListener('click', () => {
    console.log('click 2');
  });
})()
```

**Comment by mleibman** [comment] 2021-04-08 21:25
I have identified the root cause in https://github.com/angular/angular/issues/41522.

**Comment by JiaLiPassion** [comment] 2021-04-09 15:38
@mleibman , Got it, I will fix this one ASAP.

**Comment by jelbourn** [comment] 2021-04-09 20:37
Can we close this as a duplicate of #41522?

**Comment by mleibman** [comment] 2021-04-09 20:42
> Can we close this as a duplicate of #41522?

I think so.

**Closed** 2021-04-10 11:33 UTC
Labels: comp: zones
