### ISSUE TITLE
What is the alternative for ::ng-deep?

### ISSUE THREAD

**Issue by chetanapadmane1** [angular/angular#33814] opened 2019-11-14 09:30 UTC
Hi Team,
I am working on angular from last year.
I wanted to override the style of child component through parent component.
After reading document I got the information as ::ng-deep and >>> is deprecated now. What is the alternative for ::ng-deep excluding encapsulation none?

**Comment by rodolfojnn** [comment] 2019-11-14 15:57
Duplicate of #17867 and #25160

**Comment by pkozlowski-opensource** [comment] 2019-11-16 07:23
Yes, this is a duplicate of #25160

**Closed by pkozlowski-opensource** 2019-11-16 07:23 UTC
