### ISSUE TITLE
Angular 9 Router - CanActivate not working with redirects

### ISSUE THREAD

**Issue by axos88** [angular/angular#36052] opened 2020-03-13 11:48 UTC
# 🐞 bug report

### Affected Package
router

### Is this a regression?

Not sure

### Description

The use case: I want to redirect logged in users to /dashboard, and non-logged in users to /landing.

First take:
```
  {
    path: '**',
    redirectTo: '/dashboard',
    canActivate: [AuthGuard],
  },
  {
    path: '**',
    redirectTo: '/landing'
  }
```

```
@Injectable({
  providedIn: 'root'
})
export class AuthGuard implements CanActivate {

  constructor(private auth: AuthService, private router: Router) {}

  canActivate(next: ActivatedRouteSnapshot, state: RouterStateSnapshot): Observable<boolean|UrlTree> | Promise<boolean|UrlTree> | boolean | UrlTree {
    return this.auth.isAuthenticated$
  }
}
```

All users are redirected to the dashboard page.

Second try:

```
  {
    path: '**',
    redirectTo: '/home/loggedin',
    canActivate: [AuthGuard],
    data: { authGuard: { redirect: '/home/loggedout' } }
  },
  {
    path: '**',
    redirectTo: '/home/loggedin'
  }
```

```
@Injectable({
  providedIn: 'root'
})
export class AuthGuard implements CanActivate {

  constructor(private auth: AuthService, private router: Router) {}

  canActivate(
    next: ActivatedRouteSnapshot,
    state: RouterStateSnapshot
  ): Observable<boolean|UrlTree> | Promise<boolean|UrlTree> | boolean | UrlTree {
    return this.auth.isAuthenticated$.pipe(
      map(loggedIn => {
        console.log(`A=${loggedIn} ${JSON.stringify(next.data.authGuard.redirect)}`)
        if (!loggedIn && next.data.authGuard.redirect) {
          return this.router.parseUrl(next.data.authGuard.redirect);
        } else {
          return false;
        }
      })
    );
  }
}

```

Seems like the AuthGuard is not even invoked. Possibly if I use a component instead of a redirect?

```
  {
    path: '**',
    component: RedirectingComponent,
    canActivate: [AuthGuard],
    data: { authGuard: { redirect: '/home/loggedout' }, redirectComponent: { redirect: '/home/loggedin' } }
  }
```

Now this seems to work, but it also is an awful hack.

How can AuthGuards be made to work with redirects?

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-issue-repro2-8h22zn

## 🌍  Your Environment

```
**Angular Version:**
Angular CLI: 9.0.5
Node: 10.19.0
OS: linux x64

Angular: 9.0.5
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.5
@angular-devkit/build-angular     0.900.5
@angular-devkit/build-optimizer   0.900.5
@angular-devkit/build-webpack     0.900.5
@angular-devkit/core              9.0.5
@angular-devkit/schematics        9.0.5
@angular/cdk                      9.1.1
@angular/fire                     5.4.2
@angular/flex-layout              9.0.0-beta.29
@angular/material                 9.1.1
@ngtools/webpack                  9.0.5
@schematics/angular               9.0.5
@schematics/update                0.900.5
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
```

**Comment by spock123** [comment] 2020-03-14 09:15
@axos88 forgive me if this is a stupid question, but why is it necessary with a guard on a redirect? Why not have the guard on the target route? I'm trying to imagine a valid use case but I fall short.

**Comment by axos88** [comment] 2020-03-16 11:50
That's ummm... A good question. :))

But the landing page is viewable wether or not the user is logged in. Only unknown routes would redirect to the dashboard instead of the landing page.
Also my plan is that is the user visits a known page such as the dashboard page without being logged in, they would be redirected to the login page. So redirecting the ** route to the dashboard (which would based on your plan) redirect to the landing page would not work, because they would be redirected to the login page instead.

That's a bit fuzzy, let me explain it again:

With a user that is logged in:

/Login -> dashboard page
/Dashboard -> dashboard page
/Landing -> landing page
/NonExistent -> dashboard page

With a user that is NOT logged in:

/Login -> login page
/Dashboard -> login page
/Landing -> landing page
/NonExistent -> landing page

Hope it's clear what I'm trying to achieve.

**Comment by axos88** [comment] 2020-03-16 11:54
So the main issue here with your approach (having the logic in the guard on the dashboard page), and redirecting the ** to dashboard that would redirect to the landing is that the app should behave different if a non logged in user accesses the dashboard page or a non existent page.

**Comment by axos88** [comment] 2020-03-16 11:55
So the main issue here with your approach (having the logic in the guard on the dashboard page), and redirecting the ** to dashboard that would redirect to the landing is that the app should behave different if a non logged in user accesses the dashboard page or a non existent page.

**Comment by atscott** [comment] 2020-03-17 22:26
Hey @axos88, I think your approach with having a dummy component on the `**` route and moving the redirect logic to the guard itself is reasonable. I'm not really sure what it means to have a guard on a route that is a redirect. 

I'll file this away as a feature request, but I would recommend using that empty component and composing a new auth guard which returns the correct `UrlTree` for when a user is logged in vs logged out.

**Comment by axos88** [comment] 2020-03-18 10:02
@atscott thanks. I'm coming from akka-http, where routes that don't meet conditions are usually simply ignored as if they were not there, and the next route is then considered. I'm not sure if angular works in the same way, but if that's possible i would expect a redirect route whose guard does not match (guard returns false, and not an UrlTree) to consider the following rules as possible ways to handle the route.
I don't see how/why that should be different from component routes and redirect routes.

**Comment by ahmedemad3** [comment] 2020-05-05 22:07
i solve it by import the AuthGuard in the routingmodule itself and apply canActivate and it's working

**Comment by Liero** [comment] 2020-07-08 14:02
@ahmedemad3 : short example?

**Comment by atscott** [comment] 2020-07-14 00:12
Closing as duplicate of #18605

**Closed by atscott** 2020-07-14 00:12 UTC
Labels: comp: router, freq1: low, type: feature
