### ISSUE TITLE
Example not moved to Stackblitz

### ISSUE THREAD

**Issue by jbogarthyde** [angular/angular#26235] opened 2018-10-03 16:02 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

The demo referred to in the API page for `NgForOf` is still in Plunkr.

## Expected behavior

Demo should be moved to Stackblitz

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by trotyl** [comment] 2018-10-03 16:06
Duplicate of https://github.com/angular/angular/issues/25547

**Closed** 2018-10-03 17:39 UTC
