### ISSUE TITLE
Aux only routerLink definition inside a router-outlet fails

### ISSUE THREAD

**Issue by intellix** [angular/angular#12369] opened 2016-10-18 14:41 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When you specify a [routerLink] with the below: 
```html
[routerLink]="[{ outlets: { right: 'account' } }]
```

Inside primary: home produces a link like: `/home/(right:account)`
Outside primary produces a link like: `/home(right:account)`

It creates a different link depending on location of the button. Clicking that link doesn't take you to the account section inside the `right` outlet.

**Expected behavior**

Clicking the button on the left should open up the account section.

**Minimal reproduction of the problem with instructions**

1) Go to: http://plnkr.co/edit/DzjKIB3NzPmPWYe7FV2r?p=preview
2) Click button on the left, it doesn't go to account (clicking same exact button on top right menu  does)

**What is the motivation / use case for changing the behavior?**

Inside a primary route, I want to open up the account section in the right hand side. I feel like I should be able to just pass in an object saying I want the "account" to load in the right outlet. 

**Please tell us about your environment:**

**OS**: OSX Sierra

* **Angular version:** 2.0.X

**Angular**: 2.1.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Chrome**: Version 54.0.2840.59 (64-bit)
**Firefox**: 49.0.1
**Safari**: Version 10.0 (12602.1.50.0.10)
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
**TypeScript**: 2.0.2

* **Node (for AoT issues):** `node --version` =

**Comment by vsavkin** [comment] 2016-10-24 20:09
Router links are relative, i.e., the same router link expression can produce different results depending on where it's used. That is why the link used in the home component produces `/home/(right:account)`, whereas the link outside produces `/home(right:account)`.

### Why Relative Links?

Why relative links? Relative links make your components more reusable as they make fewer assumptions about the structure of the application. You can update the link used in the home component to look like this:

```
<a [routerLink]="['../', { outlets: { right: 'account' } }]">
```

This link is still relative, and it'll create the right URL. 

### Absolute Links

You can also make the link absolute like this:

```
<a [routerLink]="['/', { outlets: { right: 'account' } }]">
```

So this is not a bug. Closing the issue.

**Closed by vsavkin** 2016-10-24 20:09 UTC
Labels: comp: router, freq2: medium, severity3: broken, type: bug

**Comment by intellix** [comment] 2016-10-25 08:05
Apologies for my lack of understanding and thanks for the explanation :) It makes sense and have updated my plnkr, which includes an example of what you say, and works.

**Comment by chenyingyin** [comment] 2016-12-01 05:29
![default](https://cloud.githubusercontent.com/assets/24284270/20782714/60f05eaa-b7c9-11e6-9006-f7beb8bef322.png)

**Comment by randallmeeker** [comment] 2017-02-20 20:11
When I attempt the solution provided, it navigates just as expected, but creates the following invalid url. 

`http://localhost:4200/dispatcher/1/(incidents//modal:/(modal:settings/project))`

If I continue to use linked references as such, it will continue to embed modals

`http://localhost:4200/dispatcher/2/(incidents//modal:/(modal:/(modal:/(modal:/(modal:/(modal:/(modal:/(modal:/(modal:/(modal:settings/users))))))))))`

**Comment by randallmeeker** [comment] 2017-02-20 20:13
ignore my comment. inside the outlet I can use relative links . . .

**Comment by kmjungersen** [comment] 2018-12-03 21:10
@vsavkin I know this thread is super old, but thank you so much.  I've spent half a day trying to get an aux route to work properly on every component throughout the app, and the issue was the relative link in RouterLink.

For anyone who may come across this, I have an aux route set up to render a modal, like so:

```typescript
const appRoutes: Routes = [
  {
    path: '',
    component: HomeComponent,
  },
  // .....
  // routes for other pages/components here
  // .....
  {
    path: ':entity/:action/:id',
    component: ModalRouterComponent,
    outlet: 'modal',
  },
  {
    path: '**',
    component: PageNotFoundComponent,
  },```

And then based on the route, the `ModalRouterComponent` renders a component for the appropriate CRUD operation in a modal.  Given this setup, the modal was working fine on `HomeComponent` since it was the root route.  But in other routes, it wasn't working. 

So, instead of:
```html
<a [routerLink]="[{ outlets: { modal: 'someEntity/edit/1234' } }]">
```
I needed:
```html
<a [routerLink]="['/', { outlets: { modal: 'someEntity/edit/1234' } }]">
```
