### ISSUE TITLE
Error "@ContentChild options must be an object literal" while migrating from angular 8 to 9

### ISSUE THREAD

**Issue by JoelAzevedo** [angular/angular#35267] opened 2020-02-09 17:32 UTC
Hello,

Today I tried to migrate a project to Angular 9 but I am struggling a bit. I got the error below:

```
ERROR in @ContentChild options must be an object literal
ERROR in ./projects/moviik-ui/src/styles/styles.scss (./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??embedded!./node_modules/sass-loader/dist/cjs.js??ref--15-3!./projects/moviik-ui/src/styles/styles.scss)
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
ValidationError: Invalid options object. Sass Loader has been initialised using an options object that does not match the API schema.
 - options has an unknown property 'importer'. These properties are valid:
   object { implementation?, sassOptions?, prependData?, sourceMap?, webpackImporter? }
    at validate (C:\Users\Admin\Documents\programming\mik-frontend\node_modules\schema-utils\dist\validate.js:50:11)
    at Object.loader (C:\Users\Admin\Documents\programming\mik-frontend\node_modules\sass-loader\dist\index.js:36:28)
```

I removed node_modules and installed everything again, but the issue remains.

Any clue or anyone facing the same issue?

Thanks in advance.

**Comment by JoostK** [comment] 2020-02-09 18:35
Closing as duplicate of #34958, there's some more details in that thread. There's PR #35244 pending so that this error will properly indicate where it originates.

**Closed by JoostK** 2020-02-09 18:35 UTC
