### ISSUE TITLE
"template directives" don't properly export to a variable

### ISSUE THREAD

**Issue by endash** [angular/angular#4950] opened 2015-10-27 20:35 UTC
When attempting to use `exportAs` with a template-based directive, the following behaviour occurs:

(1) **When used with `*` syntax:** You get the error "There is no directive with "exportAs" set to "foo"" despite this not being true
(2) **When used with `template`**: You don't get an error, but the export is null, so any method calls or property access will error

~~The only way for the export to work is:~~

~~(1) Using `<template>`~~
~~(2) and specifying exportAs, despite having to... [edit: not actually necessary for workaround]~~
~~(3) manually set the local with `ViewRef.setLocal("exportAsName", this);~~

~~Additionally, in no case is the exported variable accessible in the external context. When set with `setLocal` it can only be accessed inside the template. (It makes sense that setLocal only works inside the template, so this is more a consequence of the overall divergent behaviour)~~

(While that's a workaround to get at the variable inside the template, it doesn't constitute a "way for the export to work" since it's somewhat unrelated feature-wise)

Demonstration plunkr: http://plnkr.co/edit/jXYxQ6NYk7tec4QNf355?p=preview

**Comment by pkozlowski-opensource** [comment] 2016-05-13 21:38
This is duplicate of #7142 and already got solved by d2efac18ed592b020a3f5d37a72e443a4efbb836

**Closed by pkozlowski-opensource** 2016-05-13 21:38 UTC
