### ISSUE TITLE
I am unable to display an "Update Available" message - Service Worker

### ISSUE THREAD

**Issue by guimaraesSalgado** [angular/angular#40049] opened 2020-12-09 18:44 UTC
I enabled the service worker in my project, but for some reason the message is not displayed, I have already configured my **ngsw-config**, when I do the local test it works, when I deploy to the server, I saw in a forum the solution to insert the url in **ngsw.json** after build but shouldn't that be done at the time of build? can you help me, what am i missing?

follow my cod

**ngsw-config**

```
{
  "$schema": "./node_modules/@angular/service-worker/config/schema.json",
  "index": "/index.html",
  "appData": {
    "name": "my sistem",
    "description": "Sistem new"
  },
  "assetGroups": [
    {
      "name": "app",
      "installMode": "prefetch",
      "updateMode": "prefetch",
      "resources": {
        "files": [
          "/favicon.ico",
          "/index.html",
          "/assets/**",
          "/*.css",
          "/*.js"
        ]
      }
    },
    {
      "name": "assets",
      "installMode": "lazy",
      "updateMode": "prefetch",
      "resources": {
        "files": [
          "/assets/**",
          "/*.(eot|svg|cur|jpg|png|webp|gif|otf|ttf|woff|woff2|ani)"
        ],
        "urls": [
          "https://fonts.googleapis.com/**"
        ]
      }
    }
  ],
  "dataGroups": [
    {
      "name": "api",
      "urls": [
        "/app/core/services/tipos-pessoas-fisicas.service*"
      ],
      "cacheConfig": {
        "strategy": "performance",
        "maxSize": 5,
        "maxAge": "30s"
      }
    }
  ],
  "navigationRequestStrategy": "freshness"
}
```
**My update service**

```
this.swUpdate.available.subscribe(event => {
      // tslint:disable-next-line: no-console
      console.log('teste', event);
      this.promptUser();
    });
 this.swUpdate.activated.subscribe(event => {
      // tslint:disable-next-line: no-console
      console.log('teste 02', event);
    });
```
**my website**
![image](https://user-images.githubusercontent.com/49767698/101672994-5180b800-3a35-11eb-9d43-983df8094bf8.png)
![image](https://user-images.githubusercontent.com/49767698/101673006-59405c80-3a35-11eb-9d78-5ac95e6c2689.png)

Don't get out of it, I'm getting desperate already!

**Comment by gkalpak** [comment] 2020-12-09 22:23
From a quick look everything seems fine. There is not much we can do without getting our hands on a reproduction 🤷‍♂️
You could try to debug into the SW logic and find out what happens when a check for an update is triggered (for example: does the server send the updated `ngsw.json`? can the SW download the updated file? does it post a message to the client? etc.)

I am going to close this, since it is not actionable in its current state, but feel free to continue the discussion below.
BTW, for general support question such as this one, it is better to reach out on one of our [support channels][1].

[1]: https://github.com/angular/angular/blob/d39d64c15dcba74aa673cacfc1365bd35a1d4f95/CONTRIBUTING.md#question

**Closed by gkalpak** 2020-12-09 22:23 UTC
Labels: comp: service-worker

**Comment by guimaraesSalgado** [comment] 2020-12-10 01:13
@gkalpak Location works perfectly, he sends the message, however when he goes up to prod the situation changes and he does not send me the message "Update available", this is my current ngsw.json

```
{
  "configVersion": 1,
  "timestamp": 1607542660176,
  "appData": {
    "name": "my website",
    "description": "new website"
  },
  "index": "/index.html",
  "assetGroups": [
    {
      "name": "app",
      "installMode": "prefetch",
      "updateMode": "prefetch",
      "urls": [
        "/0-es2015.8d1a2ab15f1bfaedb2f2.js",
        "/0-es5.8d1a2ab15f1bfaedb2f2.js",
        "/1-es2015.5e741be983a566b161fb.js",
        "/1-es5.5e741be983a566b161fb.js",
        "/14-es2015.85ae11af3ab8763a86f7.js",
        "/14-es5.85ae11af3ab8763a86f7.js",
        "/15-es2015.f678a33582002b834d81.js",
        "/15-es5.f678a33582002b834d81.js",
        "/16-es2015.978329f7c9e407834107.js",
        "/16-es5.978329f7c9e407834107.js",
        "/17-es2015.36bd98684cdfc075ef9d.js",
        "/17-es5.36bd98684cdfc075ef9d.js",
        "/18-es2015.b0cb2eead1e334e1c18f.js",
        "/18-es5.b0cb2eead1e334e1c18f.js",
        "/19-es2015.2aa1dc4a2142d358bfab.js",
        "/19-es5.2aa1dc4a2142d358bfab.js",
        "/20-es2015.7af769a73f89a5441d09.js",
        "/20-es5.7af769a73f89a5441d09.js",
        "/21-es2015.aad32d1244b5b4659482.js",
        "/21-es5.aad32d1244b5b4659482.js",
        "/22-es2015.1ceb31bfcf6187f33d0f.js",
        "/22-es5.1ceb31bfcf6187f33d0f.js",
        "/23-es2015.c310d1a1c224fb2d74ef.js",
        "/23-es5.c310d1a1c224fb2d74ef.js",
        "/24-es2015.038069465b3362d546d1.js",
        "/24-es5.038069465b3362d546d1.js",
        "/25-es2015.88538c8ee10fc33e7de4.js",
        "/25-es5.88538c8ee10fc33e7de4.js",
        "/26-es2015.85ff54d139b85ee205d5.js",
        "/26-es5.85ff54d139b85ee205d5.js",
        "/3-es2015.011b78ca53ddb00016d2.js",
        "/3-es5.011b78ca53ddb00016d2.js",
        "/5-es2015.6b028633680505eae286.js",
        "/5-es5.6b028633680505eae286.js",
        "/6-es2015.761cdaed6d38fe4e2b9e.js",
        "/6-es5.761cdaed6d38fe4e2b9e.js",
        "/7-es2015.3851c3144c0e74e8d4f7.js",
        "/7-es5.3851c3144c0e74e8d4f7.js",
        "/8-es2015.c2567c4f559180e34e1c.js",
        "/8-es5.c2567c4f559180e34e1c.js",
        "/9-es2015.ce64e7025a2a9b0dc260.js",
        "/9-es5.ce64e7025a2a9b0dc260.js",
        "/assets/icons/icon-128x128.png",
        "/assets/icons/icon-144x144.png",
        "/assets/icons/icon-152x152.png",
        "/assets/icons/icon-192x192.png",
        "/assets/icons/icon-384x384.png",
        "/assets/icons/icon-512x512.png",
        "/assets/icons/icon-72x72.png",
        "/assets/icons/material-icons/outline/fonts/material-outline-icons.svg",
        "/assets/icons/material-icons/outline/fonts/material-outline-icons.ttf",
        "/assets/icons/material-icons/outline/fonts/material-outline-icons.woff",
        "/assets/icons/material-icons/outline/style.css",
        "/assets/images/avatar/150.png",
        "/assets/images/avatar/f.png",
        "/assets/images/avatar/foto-padrao.jpg",
        "/assets/images/avatar/m.png",
        "/assets/images/avatar/profile-default.png",
        "/assets/images/icons-doc/application/pdf.png",
        "/assets/images/icons-doc/image/jpeg.png",
        "/assets/images/icons-doc/image/png.png",
        "/assets/images/logos/icon-investigador.png",
        "/assets/images/logos/policia-civil.png",
        "/assets/images/others/imageNotFound.png",
        "/assets/images/others/loading.gif",
        "/common-es2015.1491e6a037ffa83db1e4.js",
        "/common-es5.1491e6a037ffa83db1e4.js",
        "/favicon.ico",
        "/index.html",
        "/main-es2015.1a41908372a27c9e5ff3.js",
        "/main-es5.1a41908372a27c9e5ff3.js",
        "/polyfills-es2015.66dc389feeff8b4acbc3.js",
        "/polyfills-es5.30f83485052eeeeebc9f.js",
        "/runtime-es2015.cfa1d924f9f803a14847.js",
        "/runtime-es5.cfa1d924f9f803a14847.js",
        "/styles.731704e6430859778da3.css"
      ],
      "patterns": []
    },
    {
      "name": "assets",
      "installMode": "lazy",
      "updateMode": "prefetch",
      "urls": [
        "/color.c7a33805ffda0d32bd2a.png",
        "/hue.0614c27197fc3ce572e1.png",
        "/line.567f57385ea3dde2c9ae.gif",
        "/loading.8732a6660b528fadfaeb.gif",
        "/open-sans-v15-latin-300.177cc92d2e8027712a8c.ttf",
        "/open-sans-v15-latin-300.27ef0b062b2e221df16f.svg",
        "/open-sans-v15-latin-300.521d17bc9f3526c690e8.woff",
        "/open-sans-v15-latin-300.60c866748ff15f5b347f.woff2",
        "/open-sans-v15-latin-300.76b56857ebbae3a5a689.eot",
        "/open-sans-v15-latin-700.148a6749baa5f658a451.eot",
        "/open-sans-v15-latin-700.2e00b2635b51ba336b4b.svg",
        "/open-sans-v15-latin-700.623e3205570002af47fc.woff",
        "/open-sans-v15-latin-700.7e08cc656863d52bcb5c.ttf",
        "/open-sans-v15-latin-700.d08c09f2f169f4a6edbc.woff2",
        "/open-sans-v15-latin-regular.7aab4c13671282c90669.svg",
        "/open-sans-v15-latin-regular.9dce7f01715340861bdb.eot",
        "/open-sans-v15-latin-regular.bf2d0783515b7d75c35b.woff",
        "/open-sans-v15-latin-regular.c045b73d86803686f4cd.ttf",
        "/open-sans-v15-latin-regular.cffb686d7d2f4682df83.woff2",
        "/password-meter.d59e6dc2616c53ce8e77.png",
        "/primeicons.2d2afb2719a1ee903e57.eot",
        "/primeicons.66ee0deb739ca71f0ecd.woff",
        "/primeicons.df0140f8e79ecfeffaf8.ttf",
        "/primeicons.e5e0e94474d5fd92e7e8.svg"
      ],
      "patterns": [
        "https:\\/\\/fonts\\.googleapis\\.com\\/.*"
      ]
    }
  ],
  "dataGroups": [],
  "hashTable": {
    "/0-es2015.8d1a2ab15f1bfaedb2f2.js": "f0c6857e303ddec2ef03331df160848a08b3ac3f",
    "/0-es5.8d1a2ab15f1bfaedb2f2.js": "978ec481985cd710d926ba0dcf595539c4e4f2d4",
    "/1-es2015.5e741be983a566b161fb.js": "9bb796a209ceec2602fdf471e8fa5af03b92c3b2",
    "/1-es5.5e741be983a566b161fb.js": "d320f90ed3ba6b67d60f095f536dcb9b9043d6c9",
    "/14-es2015.85ae11af3ab8763a86f7.js": "f9be431bae2638c434f2116362066bfcffbaa00c",
    "/14-es5.85ae11af3ab8763a86f7.js": "13a0f7211cf45e73c680d7c37f6db8c2eaa861ca",
    "/15-es2015.f678a33582002b834d81.js": "8ae8447989f4272b6470a904483a848160094c2f",
    "/15-es5.f678a33582002b834d81.js": "6e47a2b9e87063e5b5c6fa127a24622a93e13840",
    "/16-es2015.978329f7c9e407834107.js": "10812bfc323dbbd45e056f56feecc16ad39bdd96",
    "/16-es5.978329f7c9e407834107.js": "36d33d8d9948e9210873afdf77cb439717dfb3ee",
    "/17-es2015.36bd98684cdfc075ef9d.js": "42eb845238457155b6adf15c3f6689f715ebf12e",
    "/17-es5.36bd98684cdfc075ef9d.js": "52d1480524e054530c223ef879a4d35cde14f4f8",
    "/18-es2015.b0cb2eead1e334e1c18f.js": "9ef4dbfd8f6a2228315c53b7a209b4aead4f768e",
    "/18-es5.b0cb2eead1e334e1c18f.js": "89821c7cb9b7a4dd3a3d5cdb694e1eac5c847d1a",
    "/19-es2015.2aa1dc4a2142d358bfab.js": "73b728ef333b2509bd48761b500704ccb1458b2a",
    "/19-es5.2aa1dc4a2142d358bfab.js": "03ad6ac304269f0c5d5104190a9183bbd1e14c33",
    "/20-es2015.7af769a73f89a5441d09.js": "dd363cb1bb6c7ae4d51e69cdd62db85cb8fae6ef",
    "/20-es5.7af769a73f89a5441d09.js": "26f18c33cefa3764b84f44aea3b91917aa9641f4",
    "/21-es2015.aad32d1244b5b4659482.js": "4709f268c02b99d0e8f9b425a04f744c987585e4",
    "/21-es5.aad32d1244b5b4659482.js": "e4f25369f70c37d695df228a6bb6fba1137c2d4e",
    "/22-es2015.1ceb31bfcf6187f33d0f.js": "1c5aad0effa070b7997c4bc56ac5ffdc2c2e7698",
    "/22-es5.1ceb31bfcf6187f33d0f.js": "da60b04cede0ec60d525b69b1175609099e6d77e",
    "/23-es2015.c310d1a1c224fb2d74ef.js": "aa258e3b14af5dcf77b4e83c5514ec82fb2ccb46",
    "/23-es5.c310d1a1c224fb2d74ef.js": "3b99db15acc7ed8bc8abe18345e43b25aec3c044",
    "/24-es2015.038069465b3362d546d1.js": "ef214258e830a9333e8e792da6215aad8c6af17f",
    "/24-es5.038069465b3362d546d1.js": "2fb9b56b79c682d8c9887837141ff3d442b2f758",
    "/25-es2015.88538c8ee10fc33e7de4.js": "39bc7f64f3cab00f793fb3e178d2f287cf967acc",
    "/25-es5.88538c8ee10fc33e7de4.js": "30231b4de3d66ff47b469751f867e0464bfd0338",
    "/26-es2015.85ff54d139b85ee205d5.js": "b3691622652bf342242555ee935c4f748333d38d",
    "/26-es5.85ff54d139b85ee205d5.js": "773d57c8f858e0f02fcdd941c3db05e4c1e4b02f",
    "/3-es2015.011b78ca53ddb00016d2.js": "1acb8990cbfc46339fc968b485f055c8274700be",
    "/3-es5.011b78ca53ddb00016d2.js": "3c4f1c89425f9577be9e1c3f647e5419fee401be",
    "/5-es2015.6b028633680505eae286.js": "9811411b23ea17bbfec2536951f78ec5edf16688",
    "/5-es5.6b028633680505eae286.js": "b3f7157a3e7dbe75bde767b1e9d46b102697206a",
    "/6-es2015.761cdaed6d38fe4e2b9e.js": "db56afdb36e304f39c215180cf3b1d0f09ce63f6",
    "/6-es5.761cdaed6d38fe4e2b9e.js": "18c868a984e1c59355d9bf2f2402bdca1052bb1d",
    "/7-es2015.3851c3144c0e74e8d4f7.js": "3732870da42edce2a636cdb5c29af1185632538e",
    "/7-es5.3851c3144c0e74e8d4f7.js": "c94bfccd33ac40874481d7c37b2df419f28a3a1a",
    "/8-es2015.c2567c4f559180e34e1c.js": "935e7ec2992cdc3409f92666c36cfaf3175e4b3d",
    "/8-es5.c2567c4f559180e34e1c.js": "62e76723c012f1eaf5c793a9eb32ee84b5954273",
    "/9-es2015.ce64e7025a2a9b0dc260.js": "dca3308a0f027194574d87d37a848c475a973e09",
    "/9-es5.ce64e7025a2a9b0dc260.js": "fe40776c289820868847647db875849f49a07965",
    "/assets/icons/icon-128x128.png": "f7bf7c6de258ec7ed76b81bca3a82f084e5d4b88",
    "/assets/icons/icon-144x144.png": "d2edea7e06d6ceb051737c3ac9215deb7919175b",
    "/assets/icons/icon-152x152.png": "d9fb1c52672871d0785d75b7352d457af1b4d671",
    "/assets/icons/icon-192x192.png": "439f188a7fd905253dfbe8aaf1b48cb317b76357",
    "/assets/icons/icon-384x384.png": "6f87ffc36689c96055c18efe14ba5afcb165a29d",
    "/assets/icons/icon-512x512.png": "b695de84dd5c44ba278c94f26d14535b878ca898",
    "/assets/icons/icon-72x72.png": "5ad749c1f945853c3e0e1d2ea45696c776f56a55",
    "/assets/icons/material-icons/outline/fonts/material-outline-icons.svg": "2258400a9f153bdc2cc358f3ff33a79cdde459df",
    "/assets/icons/material-icons/outline/fonts/material-outline-icons.ttf": "c6c03160f21a4b7fb3636af08b1cb80d4f6be3c1",
    "/assets/icons/material-icons/outline/fonts/material-outline-icons.woff": "f15ed79081c35cc862d89805048ebdf3ebba1043",
    "/assets/icons/material-icons/outline/style.css": "2df63edcc1c48e97a894c9ae8df11d107d5857aa",
    "/assets/images/avatar/150.png": "627b6e89274174b664c1a6a4ccd58926c47ec646",
    "/assets/images/avatar/f.png": "8158013a1fd9c3286377afc133d1df4fe6b0ba8e",
    "/assets/images/avatar/foto-padrao.jpg": "4a1d69d3a85561d580b105a569191a787718c58a",
    "/assets/images/avatar/m.png": "977873144d70b214dd0b46daf258632f89cfd353",
    "/assets/images/avatar/profile-default.png": "797d845656a080e489c8a2377a2a2b0e6859740a",
    "/assets/images/icons-doc/application/pdf.png": "a090721409837a33716759f90d59dc605bee8614",
    "/assets/images/icons-doc/image/jpeg.png": "1810a0f118bd8c50a646b3c893a1ad8b56700935",
    "/assets/images/icons-doc/image/png.png": "04a42510bbe1f32cb2a767803f47e6ce6b5f1a76",
    "/assets/images/logos/icon-investigador.png": "7fe5633b88c7dd667968f5e7a901d46547c65531",
    "/assets/images/logos/policia-civil.png": "992152872a8aac70315a689d76275d96508d8679",
    "/assets/images/others/imageNotFound.png": "30daea1b788741449d623ad38b99271ecf29ce09",
    "/assets/images/others/loading.gif": "cfc27fba301e487f34ae135405c9624422eff94d",
    "/color.c7a33805ffda0d32bd2a.png": "ff4c4bcb2207891b292f544edb4da9d2df5d45cf",
    "/common-es2015.1491e6a037ffa83db1e4.js": "bad351c3b1ff64a7d85fc6c845484ca5bc95f998",
    "/common-es5.1491e6a037ffa83db1e4.js": "621b681212ae555dd49a7baffb9621df5417c7b3",
    "/favicon.ico": "fc324e31d48ebed8dddb4a0d0393e7b28dbd0490",
    "/hue.0614c27197fc3ce572e1.png": "f81ae627637a684614aa726e206c73ce099a01fd",
    "/index.html": "5f5cb9888521e0d2368691a7b7f6738984ac0e87",
    "/line.567f57385ea3dde2c9ae.gif": "a2af20bd160ca9cfc2c85527663ff7429267519a",
    "/loading.8732a6660b528fadfaeb.gif": "72998a116936156dc7cace0606dab499fe4f3ce8",
    "/main-es2015.1a41908372a27c9e5ff3.js": "87679005ac46403e8c32c86baa8f71e66feff8e7",
    "/main-es5.1a41908372a27c9e5ff3.js": "ed95333c091d21fa5dcfdbe8957acc4fcd7f7efa",
    "/open-sans-v15-latin-300.177cc92d2e8027712a8c.ttf": "861b3593521709d9fa8a8efb6f40817dd7fa9337",
    "/open-sans-v15-latin-300.27ef0b062b2e221df16f.svg": "1183c2939f6cad1ac69dc16d4a0b943d546e4b2e",
    "/open-sans-v15-latin-300.521d17bc9f3526c690e8.woff": "0c74bab4a4ebdafe080c8a35bd61d38f1b692358",
    "/open-sans-v15-latin-300.60c866748ff15f5b347f.woff2": "34f486906decb7c8cf7a02d4758add9a2408c7a5",
    "/open-sans-v15-latin-300.76b56857ebbae3a5a689.eot": "7ee41fc56711a91b386b72d60d42feb9b4148f50",
    "/open-sans-v15-latin-700.148a6749baa5f658a451.eot": "29ac62f8162f60358348d8f80b191736885fdc12",
    "/open-sans-v15-latin-700.2e00b2635b51ba336b4b.svg": "8338e3159cc9c5ff55cac72674afb7e90118ff19",
    "/open-sans-v15-latin-700.623e3205570002af47fc.woff": "b5f79d1934da79c8a4ba381092dad82ffb0582cb",
    "/open-sans-v15-latin-700.7e08cc656863d52bcb5c.ttf": "f6e1c78441d4ca2ef589ce79e48d3dbf9dca9a0d",
    "/open-sans-v15-latin-700.d08c09f2f169f4a6edbc.woff2": "5a6a45d6f98752b11ccb7c4f0f6fd7faf18ad1a7",
    "/open-sans-v15-latin-regular.7aab4c13671282c90669.svg": "4ca4e88a77a4d81138206a10793507cde43e31a8",
    "/open-sans-v15-latin-regular.9dce7f01715340861bdb.eot": "8bfad53d1b3c94c9e13bdd7c0b6c7d605396d7b4",
    "/open-sans-v15-latin-regular.bf2d0783515b7d75c35b.woff": "0e92462e402c15295366d912a7b8be303d0257d8",
    "/open-sans-v15-latin-regular.c045b73d86803686f4cd.ttf": "92d652578c531e2c3d9db4622584f6a1ab2c225a",
    "/open-sans-v15-latin-regular.cffb686d7d2f4682df83.woff2": "2c07a9656f1e38da408f20f1cf11581a15cbd7a2",
    "/password-meter.d59e6dc2616c53ce8e77.png": "e0e101bd2a1cbda41398b48a4ab1792d89cb7334",
    "/polyfills-es2015.66dc389feeff8b4acbc3.js": "51fb3fa393aaba37a6e4eaca14e281e3644d4177",
    "/polyfills-es5.30f83485052eeeeebc9f.js": "65872d402f7f7fc24f3e31e9dedf973f9dfc2446",
    "/primeicons.2d2afb2719a1ee903e57.eot": "3a564ee7b180527eeba74f3dccfa6f779fcc48ab",
    "/primeicons.66ee0deb739ca71f0ecd.woff": "c4b44a9b0bc025f62101936b37de1977cd25e3fd",
    "/primeicons.df0140f8e79ecfeffaf8.ttf": "5695d34fc4ebc0bbd2fcb0babe238c3023638a7d",
    "/primeicons.e5e0e94474d5fd92e7e8.svg": "98255677416ed656903e9190e976c00fb2ac862d",
    "/runtime-es2015.cfa1d924f9f803a14847.js": "6855c2ab7a1fa09532c26a32d5ad135232273943",
    "/runtime-es5.cfa1d924f9f803a14847.js": "9abc7ee506bb6edac1e2ab7f35114fa1b6b84d6c",
    "/styles.731704e6430859778da3.css": "9cdb4d9b2ad0cbc8d3e88e86cab3906eb9b2aa52"
  },
  "navigationUrls": [
    {
      "positive": true,
      "regex": "^\\/$"
    }
  ]
}
```

My website is newweb.com, is it necessary for this url to be next to the others within assetGroups -> URL?

I don't see any problem in the application, as you mentioned, but still, I can't display the message. Perhaps the ideal is to call swUpdate.availabl on app.component?

Detail: I already have the service worker for more than 6 months and I can't get the message to appear, only local

**Comment by gkalpak** [comment] 2020-12-10 09:36
This screenshot shows that there is an error while updating to the latest version. What is the error?

**Comment by guimaraesSalgado** [comment] 2020-12-10 12:35
in this case, it seems to be "EXISTING_CLIENTS_ONLY", however when debugging in ngsw / state everything is ok. Could it be something with ambience? I'm not knowing how to find this problem on the front end

**Comment by gkalpak** [comment] 2020-12-10 14:48
You can debug SW the same way you debug regular client-side code: You can set breakpoints in the SW script and step through the executed code. Other than that, I am not sure how to help further assist you without a concrete reproduction to play with.

**Comment by guimaraesSalgado** [comment] 2020-12-10 14:51
I found that when enter in the setupUpdate method, for some reason the hash conflicts, thus breaking the initializeFully method, do you have any hash ordering? because I believe that the SW generates the hash after the build, does it compare this hash generating with the current one?

**Comment by gkalpak** [comment] 2020-12-10 15:07
@guimaraesSalgado, the SWcalculates the hashes for all assets after the build. These hashes are stored in `ngsw.json` (which is generated based on `ngsw-config.json`). When setting up an update, it checks the hashes of the fetched files against those stored in `ngsw.json` (and it bails out if they don't match).

It sounds like the hashes do no match in your case, which means that somehow the files are modfied after building. If you are not explicitly modifying them in a post-build step, it could be some automatic optimization done by some other tool you use. For example, I've seen FTP clients normalizing whitespaces and servers or proxies minify files to improve download speed.

You can compare the downloaded files with the ones right after building to find out what the differences are. This might give you some idea what tool could be modifying them.

**Comment by guimaraesSalgado** [comment] 2020-12-10 16:02
this being the reason for the error


Degraded due to failed initialization: Hash mismatch (cacheBustedFetchFromNetwork): https://myweb.sp.gov.br/14-es2015.6806b9c668313a11cde0.js: expected 349c6ced18fc268ba4dd20de5ce154ede22fabcb, got bc1a96f58626b312d0e28fca0b1be7a00c9a5350 (after cache busting)↵Error: Hash mismatch (cacheBustedFetchFromNetwork): https://myweb.sp.gov.br/14-es2015.6806b9c668313a11cde0.js: expected 349c6ced18fc268ba4dd20de5ce154ede22fabcb, got bc1a96f58626b312d0e28fca0b1be7a00c9a5350 (after cache busting)↵ at PrefetchAssetGroup.<anonymous> (https://myweb.sp.gov.br/ngsw-worker.js:699:35)↵ at Generator.next (<anonymous>)↵ at fulfilled (https://myweb.sp.gov.br/ngsw-worker.js:320:62)"
