### ISSUE TITLE
@angular/bazel add schematic fails

### ISSUE THREAD

**Issue by cexbrayat** [angular/angular#30052] opened 2019-04-23 13:14 UTC
# 🐞 bug report

### Affected Package

The issue is caused by package @angular/bazel

### Is this a regression?

I don't know

### Description

Running `ng add @angular/bazel@next` throws on first try (next being `8.0.0-beta.13` at the time of writing).
Running it a second time succeeds.

## 🔬 Minimal Reproduction

```
npm i -g @angular/cli@8.0.0-beta.16
ng new hello-bazel --defaults
cd hello-bazel
ng add @angular/bazel@next --name hello-bazel
```

## 🔥 Exception or Error
<pre><code>
Installing packages for tooling via npm.
+ @angular/bazel@8.0.0-beta.13
added 27 packages from 78 contributors in 8.376s
Installed packages for tooling via npm.
Cannot find module '/Users/ced-pro/Code/test/cli-tests/hello-bazel/node_modules/@angular/bazel/package.json'
Error: Cannot find module '/Users/ced-pro/Code/test/cli-tests/hello-bazel/node_modules/@angular/bazel/package.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:649:15)
    at Function.Module._load (internal/modules/cjs/loader.js:575:25)
    at Module.require (internal/modules/cjs/loader.js:705:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at NodeModulesEngineHost._resolveCollectionPath (/Users/ced-pro/Code/test/cli-tests/hello-bazel/node_modules/@angular-devkit/schematics/tools/node-module-engine-host.js:74:39)
    at NodeModulesEngineHost.createCollectionDescription (/Users/ced-pro/Code/test/cli-tests/hello-bazel/node_modules/@angular-devkit/schematics/tools/file-system-engine-host-base.js:115:27)
    at SchematicEngine._createCollectionDescription (/Users/ced-pro/Code/test/cli-tests/hello-bazel/node_modules/@angular-devkit/schematics/src/engine/engine.js:147:40)
    at SchematicEngine.createCollection (/Users/ced-pro/Code/test/cli-tests/hello-bazel/node_modules/@angular-devkit/schematics/src/engine/engine.js:140:43)
    at AddCommand.getCollection (/Users/ced-pro/Code/test/cli-tests/hello-bazel/node_modules/@angular/cli/models/schematic-command.js:128:35)
    at AddCommand.runSchematic (/Users/ced-pro/Code/test/cli-tests/hello-bazel/node_modules/@angular/cli/models/schematic-command.js:306:50)
    at AddCommand.executeSchematic (/Users/ced-pro/Code/test/cli-tests/hello-bazel/node_modules/@angular/cli/commands/add-impl.js:142:31)
    at AddCommand.run (/Users/ced-pro/Code/test/cli-tests/hello-bazel/node_modules/@angular/cli/commands/add-impl.js:106:21)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.0.0-beta.16
Node: 11.11.0
OS: darwin x64
Angular: 8.0.0-beta.13
... animations, bazel, common, compiler, compiler-cli, core
... forms, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.0-beta.16
@angular-devkit/build-angular     0.800.0-beta.16
@angular-devkit/build-optimizer   0.800.0-beta.16
@angular-devkit/build-webpack     0.800.0-beta.16
@angular-devkit/core              8.0.0-beta.16
@angular-devkit/schematics        8.0.0-beta.16
@angular/cli                      8.0.0-beta.16
@ngtools/webpack                  8.0.0-beta.16
@schematics/angular               8.0.0-beta.16
@schematics/update                0.800.0-beta.16
rxjs                              6.4.0
typescript                        3.4.4
webpack                           4.30.0
</code></pre>

**Anything else relevant?**

Running the command another time succeeds:

```
Skipping installation: Package already installed
CREATE angular-metadata.tsconfig.json (638 bytes)
CREATE e2e/protractor.on-prepare.js (1101 bytes)
CREATE src/initialize_testbed.ts (432 bytes)
CREATE src/main.dev.ts (185 bytes)
CREATE src/main.prod.ts (249 bytes)
CREATE src/rxjs_shims.js (1259 bytes)
CREATE angular.json.bak (3573 bytes)
CREATE tsconfig.json.bak (573 bytes)
UPDATE package.json (1651 bytes)
UPDATE angular.json (1942 bytes)
UPDATE tsconfig.json (315 bytes)
```

**Comment by cexbrayat** [comment] 2019-04-23 13:17
The second run succeeds but then no command work.
For example `ng serve` throws:
```
Cannot find module '@angular-devkit/architect/src/index2'
Error: Cannot find module '@angular-devkit/architect/src/index2'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:649:15)
    at Function.Module._load (internal/modules/cjs/loader.js:575:25)
    at Module.require (internal/modules/cjs/loader.js:705:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at /Users/ced-pro/Code/test/cli-tests/hello-bazel/node_modules/@angular/bazel/src/builders/index.js:22:20
    at /Users/ced-pro/Code/test/cli-tests/hello-bazel/node_modules/@angular/bazel/src/builders/index.js:12:17
    at Object.<anonymous> (/Users/ced-pro/Code/test/cli-tests/hello-bazel/node_modules/@angular/bazel/src/builders/index.js:18:3)
    at Module._compile (internal/modules/cjs/loader.js:799:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
    at Module.load (internal/modules/cjs/loader.js:666:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
    at Function.Module._load (internal/modules/cjs/loader.js:598:3)
    at Module.require (internal/modules/cjs/loader.js:705:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Promise.resolve.then (/Users/ced-pro/Code/test/cli-tests/hello-bazel/node_modules/@angular-devkit/architect/node/node-modules-architect-host.js:75:61)
    at process.runNextTicks [as _tickCallback] (internal/process/next_tick.js:47:5)
```

**Comment by alan-agius4** [comment] 2019-04-23 13:29
The second error should have been fixed https://github.com/angular/angular/pull/29966/ which is not yet released.

However, I am unable to reproduce the first error.

**Comment by alexeagle** [comment] 2019-04-23 16:58
Maybe `@angular/bazel` package didn't get installed in the project before the add schematic ran? Keen has been changing the point where the `npm install` happens so it's probably that.

**Comment by alxhub** [comment] 2022-03-14 23:31
Closing as obsolete - the Bazel builder and associated CLI functionality are deprecated and no longer supported.

**Closed by alxhub** 2022-03-14 23:31 UTC
Labels: type: bug/fix, freq1: low, comp: bazel, P4
