### ISSUE TITLE
I think the ViewChild API documentation page is broken

### ISSUE THREAD

**Issue by sdedieu** [angular/angular#57366] opened 2024-08-13 10:05 UTC
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

The [@ViewChild API documentation page](https://angular.dev/api/core/ViewChild) seems broken.

Clicking on the parameters on the right panel doesn't display the documentation for the selected parameter.

![Screenshot 2024-08-13 at 12 01 27](https://github.com/user-attachments/assets/5268378d-bb25-4677-865e-5d34ad534867)

The Description Panel content display `[object Object]` instead of stringified Javascript Object. 

![Screenshot 2024-08-13 at 12 01 40](https://github.com/user-attachments/assets/56e020a5-e174-48fb-a053-f4758cafcad8)

### Please provide a link to a minimal reproduction of the bug

Go to the https://angular.dev/api/core/ViewChild

**Comment by sdedieu** [comment] 2024-08-13 10:09
The "Usage Notes" tab content is also not working. 
![Screenshot 2024-08-13 at 12 07 45](https://github.com/user-attachments/assets/290dde8d-7d4e-44e2-81be-f84cfd2f7f9e)

**Comment by JeanMeche** [comment] 2024-08-13 13:19
This is a duplicate of #57336, already fixed on main but needs a backport on `18.2.x`(#57363) because we're already targeting the next major.

**Closed by JeanMeche** 2024-08-13 13:19 UTC
