### ISSUE TITLE
Change Angular name to AngularX to successfully distinguish it from angularJS

### ISSUE THREAD

**Issue by KErez** [angular/angular#20543] opened 2017-11-20 12:29 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Angular 2,4,5... name is confusing and it is hard to define a correct search over the web.
Many of the old sites that had angularJS insights did not refer to angular1.x as angularJS but rather as angular and thus you get these unwanted result in your search.
In addition, now that we are in angular 5 you cannot make a search with "Angular 2/4/5" since you may loose information or resources that refer to other versions.

## Expected behavior
I want a clear name for the library that will distinguish angular from angularJS.
Proposition:
AngularX

## Minimal reproduction of the problem with instructions
Irrelevant
## What is the motivation / use case for changing the behavior?
Global and future usability and remove ambiguity. 

## Environment
All
<pre><code>
Angular version: All

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by ericmartinezr** [comment] 2017-11-20 12:36
https://github.com/angular/angular/issues/19318#issuecomment-331253909

**Comment by trotyl** [comment] 2017-11-20 14:11
Duplicate of #14802, #16171, #16577, #18200, #19318

**Comment by StephenFluin** [comment] 2017-11-20 22:36
We've spent a lot of time discussing our branding in the past. This resulted in the branding guidelines that we published a year ago http://angularjs.blogspot.com/2017/01/branding-guidelines-for-angular-and.html and https://angular.io/presskit#brand-names.

We expected that it will take some time for the guidelines to get widely adopted, but in reality most of the highly visible resources have been updated to use the branding correctly long time ago. Since then we've seen good adoption of the guidelines and we currently have no intention to change them.

If you see someone using the terminology incorrectly, you can help by pointing them to the blog post I mentioned above. Thank you!

**Closed by StephenFluin** 2017-11-20 22:36 UTC

**Comment by mderoche** [comment] 2017-12-05 21:33
@StephenFluin Whenever you Google anything with "Angular", you get mostly AngularJS results.  This makes searching for information extremely frustrating.  People called AngularJS "Angular" the entire time it was being actively used, there's no way to go back and erase that from history.

At this point it's probably too late to call it anything but "Angular", but I'll join most people in saying that I think it just makes everything more frustrating than it has to be.

**Comment by mlc-mlapis** [comment] 2017-12-05 21:43
@mderoche ... use `-angularjs` when googling and you'll eliminate 95% of your problems.

**Comment by mderoche** [comment] 2017-12-05 21:49
@mlc-mlapis That assumes they are using "AngularJS" instead of "Angular", which I was saying they often do not.  It could also easily exclude relevant documents.  (Not to mention, in my opinion, we should be able to easily search for documentation and information without using Google search modifiers on every request...)

**Comment by mlc-mlapis** [comment] 2017-12-05 21:54
@mderoche ... that's why I wrote 95% ... I am using the same so I know the results. Another tip is the time line ... you can search just for docs 1 year old or newer ... then you'll be on 98%.

OK ... try to stop thinking about that ... you can't change it ... and it is also absolutely non-sense to think that Angular will be renamed to another new brand name right now.

**Comment by mderoche** [comment] 2017-12-05 22:01
@mlc-mlapis I think 95% is a very inflated number.  As I said, people used "Angular" when referring to "AngularJS" for years.

And again, excluding with "-angularjs" can remove valid documents.  For example, `angular router -angularjs` hides the actual Angular website for me, while `angular router` does not.

Obviously it's too late to change the name at this point, so I guess it's pointless to discuss it.
