### ISSUE TITLE
Angular 2, IE9 & pushState issue!

### ISSUE THREAD

**Issue by andycwk** [angular/angular#6506] opened 2016-01-15 13:39 UTC
Hi,

I'm having some issues with Angular 2, pushState & IE9 as I've documented initially in https://groups.google.com/forum/#!topic/angular/TdCt6KyhwI8 before carrying out much more investigation!

I've read https://github.com/angular/angular/issues/5792 and attempted to apply the history.js script with mixed results!

I have had to modify angular2.dev.js locally to return window.History instead of window.history (not a long term solution really!)

In Everything but IE9 things work as expected using path location mode - in IE9 history.js takes over and injects urls to look like http://my.app.com/#./dashboard

But those hashtag paths are then not recognised by the angular router..!!

So I turn on the hash location strategy and that works fine in chrome etc but in IE history.js kicks in and alerts the following..

>> History.js does not support states with fragment-identifiers (hashes/anchors). 

The root issue is found in the following code in the router..

```
    PlatformLocation.prototype.pushState = function(state, title, url) {
        console.log('pushState line 2022');
      this._history.pushState(state, title, url);
      console.log('after push line 2026');
    };
```
If I comment out the pushState line then everything works.. but of course the url is not updated in the browser window :(

It feels a bit like a catch-22 situation!!

a) Is this a bug??
b) Does the Angular team have a compatible IE9 routing solution?

Help!!!

**Comment by brianaprince** [comment] 2016-02-09 18:44
So is the Angular 2 team calling this a bug or are they not supporting a shim for IE9?  I have to support IE9 and this affects my routing decisions.

**Comment by bionicvapourboy** [comment] 2016-03-14 14:43
+1

**Comment by sasidhar** [comment] 2016-04-01 01:32
+1

**Comment by zoechi** [comment] 2016-04-01 06:17
As a workaround you could just provider a custom `LocationStrategy` (for example extend the `PathLocationStrategy` or `HashLocationStrategy` and override the behavior you want have changed then provide it like

```ts
bootstrap(AppComponent, [ROUTER_PROVIDERS, provide(LocationStrategy, {useClass: MyLocationStrategy})
```

then you don't have to modify `angular2.dev.js`

**Comment by sasidhar** [comment] 2016-04-01 06:47
@zoechi I am facing this issue in IE9.

It seems the issue is with the line : `this._history.pushState(state, title, url);` and it seems, this line will be triggered every time when there is a route change. 

Does creating a custom `LocationStrategy` will prevent running the above code in IE9? If yes, how can we achieve the working routes in IE9 without no more `pushState` errors? Is it possible to show use some more code on implementing custom `LocationStrategy`?

**Comment by zoechi** [comment] 2016-04-01 06:57
- https://github.com/angular/angular/tree/master/modules/angular2/src/router/location 
You need to override the code that offeneds IE9. 
Sorry, I don't plan to spend time for IE9 (I'm not a member of the Angular team)

**Comment by sasidhar** [comment] 2016-04-01 14:02
@zoechi Thanks

**Comment by narr** [comment] 2016-04-18 07:35
Before @sasidhar PR is merged, you can override Angular2's https://github.com/angular/angular/blob/master/modules/angular2/src/router/location/browser_platform_location.ts that is suspected of having the problem as making your own 'browser_platform_location.ts'.

Just make a clone of this https://github.com/sasidhar/angular/blob/6af02a0df54a8744003e4075b1bd077be976ea3f/modules/angular2/src/router/location/browser_platform_location.ts and change the class name to MyBrowserPlatformLocation

Lastly do DEPENDENCY INJECTION like bootstrap(AppComponent, [ROUTER_PROVIDERS, provide(PlatformLocation, {useClass: MyBrowserPlatformLocation})

It is a temporary solution but it worked to me.

**Closed** 2016-05-26 16:49 UTC
Labels: comp: router-deprecated, effort2: medium (day), P2: required, type: bug
