### ISSUE TITLE
Rehydration doesn't work with throw error `el.setAttribute is not a function` in Angular 16 rc.1

### ISSUE THREAD

**Issue by leo6104** [angular/angular#49849] opened 2023-04-14 16:25 UTC
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

When we enable `provideClientHydration(withNoHttpTransferCache())` option in AppModule and check ssr hydration result, I got some error which is unhandled by NG0XXX error code. 

I don't know how to reproduce this error in stackblitz yet. 

But hope it could be helpful if we provide callstack for error message first. 
Here is the error callstack. 

### Please provide a link to a minimal reproduction of the bug

https://github.com/leo6104/ng-rehydrate-error-repro

### Please provide the exception or error you saw

```true
re.mjs:10057 ERROR TypeError: el.setAttribute is not a function
    at EmulatedEncapsulationDomRenderer2.setAttribute (platform-browser.mjs:592:16)
    at BaseAnimationRenderer.setAttribute (animations.mjs:270:23)
    at setUpAttributes (core.mjs:1020:26)
    at setupStaticAttributes (core.mjs:7535:9)
    at ɵɵelementStart (core.mjs:15088:5)
    at _a5_ng_container_0_Template (_a5.js:1:1)
    at ReactiveLViewConsumer.runInContext (core.mjs:10311:13)
    at executeTemplate (core.mjs:11069:18)
    at renderView (core.mjs:10889:13)
    at TemplateRef2.createEmbeddedViewImpl (core.mjs:22766:9)
h
```

another error case (same but little more detail callstack) 
```
handled Promise rejection: el.setAttribute is not a function ; Zone: <root> ; Task: Promise.then ; Value: TypeError: el.setAttribute is not a function
    at NoneEncapsulationDomRenderer.setAttribute (platform-browser.mjs:592:16)
    at BaseAnimationRenderer.setAttribute (animations.mjs:270:23)
    at setUpAttributes (core.mjs:1020:26)
    at setupStaticAttributes (core.mjs:7535:9)
    at ɵɵelementStart (core.mjs:15088:5)
    at _a5_ng_container_0_Template (template.html:6:5)
    at ReactiveLViewConsumer.runInContext (core.mjs:10311:13)
    at executeTemplate (core.mjs:11069:18)
    at renderView (core.mjs:10889:13)
    at TemplateRef2.createEmbeddedViewImpl (core.mjs:22766:9) 

TypeError: el.setAttribute is not a function
    at NoneEncapsulationDomRenderer.setAttribute (https://.../chunk-SET2APWZ.js:16109:14)
    at BaseAnimationRenderer.setAttribute (https://.../chunk-XDNB56EC.js:4246:23)
    at setUpAttributes (https://.../chunk-YTYK4I53.js:4664:18)
    at setupStaticAttributes (https://.../chunk-YTYK4I53.js:7713:5)
    at ɵɵelementStart (https://.../chunk-YTYK4I53.js:11031:3)
    at _a5_ng_container_0_Template (ng:///_a5.js:10:5)
    at ReactiveLViewConsumer.runInContext (https://.../chunk-YTYK4I53.js:17559:11)
    at executeTemplate (https://.../chunk-YTYK4I53.js:9029:14)
    at renderView (https://.../chunk-YTYK4I53.js:8884:7)
    at TemplateRef2.createEmbeddedViewImpl (https://.../chunk-YTYK4I53.js:18567:9)
a
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 16.0.0-rc.0
Node: 16.19.0
Package Manager: npm 8.19.3
OS: darwin x64

Angular: 16.0.0-rc.1
... animations, common, compiler, compiler-cli, core, elements
... forms, localize, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1600.0-rc.0
@angular-devkit/build-angular   16.0.0-rc.0
@angular-devkit/core            16.0.0-rc.0
@angular-devkit/schematics      16.0.0-rc.0
@angular/bazel                  15.2.6
@angular/cdk                    16.0.0-rc.0
@angular/cli                    16.0.0-rc.0
@angular/material               16.0.0-rc.0
@angular/youtube-player         16.0.0-next.2
@nguniversal/builders           16.0.0-next.0
@nguniversal/common             16.0.0-next.0
@nguniversal/express-engine     16.0.0-next.0
@schematics/angular             16.0.0-rc.0
ng-packagr                      16.0.0-rc.0
rxjs                            7.8.0
typescript                      5.0.3
```

### Anything else?

the component html markup is here and got error in `*ngIf="d.header"` condition. 
```
<ng-container *ngLet="{
  fullWidth: fullWidth$ | async,
  header: header$ | async
} as d">
  <div class="board-section" [class.full-width]="d.fullWidth" cdkScrollable>
    <global-navigation-bar *ngIf="d.header"></global-navigation-bar>
    <div class="body-container" [class.show-header]="d.header">
      <router-outlet></router-outlet>
    </div>
    <km-footer />
  </div>
</ng-container>
<ng-template #fabWrapperContainer></ng-template>

```

`root-cmp` decorator
```
@Component({
  selector: 'root-cmp',
  templateUrl: './root-cmp.component.html',
  styleUrls: [
    './root-cmp.component.scss'
  ],
  host: {
    toastContainer: 'true' // ToastContainerDirective,
  },
})
```

and header$ variable use ngrx route data 

```
  header$ = this.store.select(selectRouteData).pipe(
    map(({ header }) => !header || header !== 'hide'),
    distinctUntilChanged(),
  );
```

ngLet directive 
```

interface LetContext<T> {
  ngLet: T;
}

@Directive({
  selector: '[ngLet]',
  standalone: true,
})
export class LetDirective<T> {
  private _context: LetContext<T> = { ngLet: null };

  constructor(_viewContainer: ViewContainerRef, _templateRef: TemplateRef<LetContext<T>>) {
    _viewContainer.createEmbeddedView(_templateRef, this._context);
  }

  @Input()
  set ngLet(value: T) {
    this._context.ngLet = value;
  }
}

```

**Comment by AndrewKushnir** [comment] 2023-04-14 17:06
@leo6104 thanks for reporting the issue. It's be very helpful if you could provide an repro in a form of a GitHub repository with a minimal required setup (and fake components) based on an `ng new` command output.

A couple questions that may also help with the debugging:

- Do you run the app in the dev mode? If not, you could try enabling the dev mode and see if there is a hydration-specific error message.
- Do you see the error **only** when `provideClientHydration` is used?
- Try adding `ngSkipHydration` to that component ([as described here](https://next.angular.io/guide/hydration#how-to-skip-hydration-for-particular-components)) and see if the error goes away.
- When the error is thrown, what's the value of `el` (if it `null`/`undefined` or a comment node)?

Thank you.

**Comment by leo6104** [comment] 2023-04-15 00:24
1. We run in prod mode with calling `enableProdMode()` and when we remove this, there is no changes. 
2. It only seen when `provideClientHydration` used. 
3 + 4. When i debug el value, it was #text node generated by cdkScrollable directive. 

<img width="1483" alt="image" src="https://user-images.githubusercontent.com/7777929/232173666-335299d4-2c15-45c9-8e2f-5c56866622b4.png">

And when i remove cdkScrollable in html tag, it doesn't throw the error. 
I think i can make some reproduction github repo with this clue. I will try it. Thanks @AndrewKushnir

**Comment by leo6104** [comment] 2023-04-15 01:19
It only show errors in hydration enabled case. 

When i run in dev mode, it shows error like 

```
ROR Error: NG0500: During hydration Angular expected a comment node but found a text node.

Angular expected this DOM:

<root-cmp toastcontainer="" _nghost-mms-c3289612811="" class="" _nghost-mms-c3087788877="">
  …
  <!-- container -->  <-- AT THIS LOCATION
  …
</root-cmp>

Actual DOM is:

<root-cmp toastcontainer="" _nghost-mms-c3289612811="" class="" _nghost-mms-c3087788877="">
  …
  #text
  #text  <-- AT THIS LOCATION
  …
</root-cmp>

Note: attributes are only displayed to better represent the DOM but have no effect on hydration mismatches.

To fix this problem:
  * check the "_a5" component for hydration-related issues
  * or skip hydration by adding the `ngSkipHydration` attribute to its host node in a template. Find more at https://angular.io/errors/NG0500
    at validateMatchingNode (core.mjs:14260:15)
    at locateOrCreateContainerAnchorImpl (core.mjs:14963:9)
    at ɵɵtemplate (core.mjs:14922:21)
    at _a5_Template (template.html:1:1)
    at ReactiveLViewConsumer.runInContext (core.mjs:10311:13)
    at executeTemplate (core.mjs:11069:18)
    at renderView (core.mjs:10889:13)
    at renderComponent (core.mjs:12124:5)
    at renderChildComponents (core.mjs:10747:9)
    at renderView (core.mjs:10914:13)
h
```

And #text node `el` variable looks like this.

![](https://user-images.githubusercontent.com/7777929/232173666-335299d4-2c15-45c9-8e2f-5c56866622b4.png)

**Comment by AndrewKushnir** [comment] 2023-04-15 04:25
@leo6104 thanks for additional information. Unfortunately it's not enough to identify where the problem is coming from. It'd be great to have a reproduction in a form of a GitHub repository, so that we can replicate the issue.

Based on the error message mentioned in your comment, Angular expected a comment node to be present at a particular location, but instead a text node was found in the DOM. Since there are no text nodes in the template that you've mentioned, there is a chance that they are somehow inserted and likely via direct DOM manipulation (see a section about it in [the hydration guide](https://next.angular.io/guide/hydration#direct-dom-manipulation)). If those text nodes are no created in your app code, they might be coming from the 3rd party libraries. You can try disabling (commenting out) the following host attribute as well (and/or disable the Toast-related directives) to see if this fixes the problem.:
```
  host: {
    toastContainer: 'true' // ToastContainerDirective,
  },
```

We'll be happy to investigate further, but we need a reproduction, so that we can perform the necessary debugging.

Thank you.

**Comment by leo6104** [comment] 2023-04-15 06:36
Here is the reproduction. the markup `router-outlet` inside `ng-container [ngLet]` + ng-template is problem.

https://github.com/leo6104/ng-rehydrate-error-repro 

In app.component.html, 

### Case 0: Hydration error with text node. (this issue case) 
```
<ng-container *ngLet="{} as d">
  <cmp-1 />
  <router-outlet />
</ng-container>
<ng-template #fabWrapperContainer />
```

### Case 1 : "EpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked." error occur but no hydration error.
```
<cmp-1 />
<router-outlet />
<ng-template #fabWrapperContainer />
```

### Case 2: No error. 
```
<ng-container *ngLet="{} as d">
  <cmp-1 />
  <router-outlet />
</ng-container>
```

Should i consider these life-cycle error to fix rehydration?

**Comment by leo6104** [comment] 2023-04-15 09:58
When i use `*ngrxLet` directive from `@ngrx/component` npm instead of using our custom `*ngLet` directive, `ExpressionChangedAfterItHasBeenCheckedError` error disappear. 

However, still have hydration issue. 
`ViewContainerRef.createEmbededView` + `router-outlet` + `ng-template` might be the cause.

**Comment by AndrewKushnir** [comment] 2023-04-15 21:48
@leo6104 thanks a lot for the reproduction! This helped to identify the root cause: the problem was triggered by an issue in the internal Angular logic that collects root nodes in a given view. The logic was not taking into account ViewContainerRef's anchor (comment) nodes, thus returning incorrect output (less DOM nodes). Hydration logic relies on the **number** of root nodes in a view to properly split the DOM into segments (which belong to a particular view), thus the logic incorrectly identified the end of a segment.

The problem should be fixed by https://github.com/angular/angular/pull/49867. The PR would go through the usual review and test process before the merge, but you can test the fix by using the `core` package from the PR. You can update the `package.json` as shown below and run `npm install` (you may need to use `--force` to skip version conflicts):
```
  ...
  "@angular/core": "https://output.circle-artifacts.com/output/job/c6a99b5b-02c5-4094-9c28-be5eee45915c/artifacts/0/angular/core-pr49867-8af03dfa43.tgz",
  ...
```
Please let me know if this resolves the problem.

Thank you.

**Comment by leo6104** [comment] 2023-04-16 00:31
Thanks for updates. I apply new version of @angular/core but it seems still have an hydration issue with another node. 

To find out which tag cause the problem, i just remove `ng-container`, `ng-template`, any tag usage in root-cmp component and just remain `router-outlet`. Still have error.

Here is the error message. 

```
ROR Error: NG0500: During hydration Angular expected <router-outlet> but found a text node (with the "" content).

Angular expected this DOM:

<app-root _nghost-mms-c326412346="" class="" _nghost-mms-c543572020="">
  <router-outlet>…</router-outlet>  <-- AT THIS LOCATION
  …
</app-root>

Actual DOM is:

<app-root _nghost-mms-c326412346="" class="" _nghost-mms-c543572020="">
  #text  <-- AT THIS LOCATION
  …
</app-root>

Note: attributes are only displayed to better represent the DOM but have no effect on hydration mismatches.

To fix this problem:
  * check the "_a19" component for hydration-related issues
  * or skip hydration by adding the `ngSkipHydration` attribute to its host node in a template. Find more at https://angular.io/errors/NG0500
    at validateMatchingNode (core.mjs:14274:15)
    at locateOrCreateElementNodeImpl (core.mjs:15196:18)
    at ɵɵelementStart (core.mjs:15095:20)
    at ɵɵelement (core.mjs:15174:5)
    at _a19_Template (VM1145 _a19.js:8:21)
    at ReactiveLViewConsumer.runInContext (core.mjs:10310:13)
    at executeTemplate (core.mjs:11068:18)
    at renderView (core.mjs:10888:13)
    at renderComponent (core.mjs:12123:5)
    at renderChildComponents (core.mjs:10747:9)
h
```

I expect there is some issue with nested router-outlet and some tags. I will figure out how to reproduce it and share here with new reproduction.

**Comment by AndrewKushnir** [comment] 2023-04-17 03:52
@leo6104 thanks for testing the fix! Just want to double check: with the updated `@angular/core` the original error is gone and now you see a different one somewhere in a nested route, is that correct?

As you mentioned, it'd be great if you could narrow down the use-case that is causing hydration issue and update the reproduction with this new pattern (with the minimal code required to reproduce the issue). We'll be happy to investigate it further.

Thank you.

**Comment by leo6104** [comment] 2023-04-17 04:43
@AndrewKushnir  Yes it is. It seems completely solve hydration error from ViewContainerRef.

Me and my colleague found another hydration issue in our project with below markup condition. 
this error exists on 16.0.0-rc.1 and your custom core builds. Both one. 

```
@Component(...) 
export class Component {
   test: string; 
   test$ = of('test').pipe(
      tab((t) => this.test = t), 
   );
}
```

in PC project, 
```
{{ test }} 
``` 

![image](https://user-images.githubusercontent.com/7777929/232374958-af1feb3b-cff5-4267-93bd-c7dda683538b.png)
![image](https://user-images.githubusercontent.com/7777929/232374981-e2404cf8-f910-4db9-a918-891f0ee32d2b.png)

In server side rendering, it just show 'test' text only
In client hydration timing, its text duplicated `testtest` without no hydration error.

Furthermore, When we wrap to <div> tag, it raise Hydration error.

in PC project, raise Hydration error. 
```
  <div>
    {{test}} 
  </div>
```


in Mobile project, just wrap one time <div> doesn't raise error but two times wrap caused hydration error. 
```
<div>
  <div>
    {{test}} 
  </div>
</div>
```


But it is very difficult to reproduce this. It seems some global logic in our AppModule / router interceptor / configuration affected to this error case.

**Comment by AndrewKushnir** [comment] 2023-04-17 05:59
@leo6104 thanks for the reply.

There is a chance that this issue was caused by a special logic to handle empty text nodes during hydration. I've put together some tests and can reproduce a similar (but **not exactly the same**) problem, see https://github.com/angular/angular/pull/49877. I've also put together a possible fix and I wanted to ask if you could use the following `@angular/core` package to test the behavior:

```
...
 "@angular/core": "https://output.circle-artifacts.com/output/job/90bae8de-aa9f-4cfa-aced-faf3895b07a0/artifacts/0/angular/core-pr49877-c21878ec3a.tgz",
...
```

Note: the PR does **not** include the other fix discussed above, please let me know if this is a problem for testing, I can create a temporary PR with a combination of both fixes.

> If you can give us some hints to reproduce it, please let us know the information.

It'd be great if you could check the following use-cases and let us know the observed behavior:

- What happens when you replace a text interpolation with just some static text in a template?
- Does it make any difference if you do not have spaces before and after interpolation, i.e. `<div>{{test}}</div>`?
- Do you see a different behavior when you wrap text interpolation with extra symbols like this:
```
<div>
  --{{test}}--
</div>
```

It'd still be very helpful to have a repro, so that we can perform further investigation.

Thank you.

**Comment by leo6104** [comment] 2023-04-17 12:35
@AndrewKushnir  Thanks for giving us information. It was great helpful for us. 

With your clue, we do more investigation and finally found a clue. 

It was related with `preserveWhitespaces` option in `angularCompilerOptions` tsconfig.json. 
When we remove `preserveWhitespaces: true` option in tsconfig.json, the second issue solved. 

With remaining this comment, we really want to provide reproduction repo but i already spent 6 working hours to find above clue. It makes us hold new feature progress too much. 😅 

I can spent more times to figure out how to reproduce it on Wednesday. 

Thanks. 😊

**Closed** 2023-04-17 13:36 UTC
Labels: area: core, state: has PR, P2, core: hydration

**Comment by AndrewKushnir** [comment] 2023-04-17 17:25
@leo6104 thanks a lot for your help with a repro! This ticket was closed automatically since the PR https://github.com/angular/angular/pull/49867 got merged. Thanks for creating a new ticket, we will review it and comment.

Quick question: we were wondering if the `preserveWhitespaces` configuration was intentional and which use-case you were covering with it? We'll be investigating the effect of the `preserveWhitespaces: true` on hydration, but it's likely that the recommendation would be to not use it with hydration (at least for now). Would it be possible in your case to disable `preserveWhitespaces` (i.e. bring it back to the default state)?

**Comment by leo6104** [comment] 2023-04-18 03:05
@AndrewKushnir Actually, there is no special reason we putting `preserveWhitespaces: true` option. It was preserved by legacy. We have been use angular for 6 years (migrated from angularjs in 2016) and at some moment `tsconfig.json` included `preserveWhitespaces: true` option. (maybe it was default option.)

when we setup initial SSR part few years ago, we want to reduce html size so we just turn off `preserveWhitespaces` in `tsconfig.server.json` to remove all whitespaces in prerendered html. 
(without changing `preserveWhitespaces` in tsconfig.app.json)

It was the reason we have mismatch value between `tsconfig.app.json` and `tsconfig.server.json` 

But, at this moment, we can turn off `preserveWhitespaces`. it is no problem. 

However, its difference between two tsconfig files shows `\n` `text node` hydration error and Developer cannot expect the error came from `preserveWhitespaces` option. 😅 It could be the point angular can improve. 


BTW, it would be nice if angular team provide some test utils for hydration. 
We have lots of experience in Angular usage so we can build `ssr-dev-server` and can start hydration feature. But it was like end-to-end hydration testing process by human. We want to be more smarter and save times to testing hydration in the future. 
I saw your PR and its hydration test util is awesome. we are trying to build similiar hydration test code in our project. It can make our project sustainable and trustful. And i expect that easy to find unhandled case from angular internal logic.

**Comment by AndrewKushnir** [comment] 2023-04-18 04:09
@leo6104 thanks for the reply and for all your help to investigate the problems! 👍 

> However, its difference between two tsconfig files shows \n text node hydration error and Developer cannot expect the error came from preserveWhitespaces option. 😅 It could be the point angular can improve.

Yes, that is a quite tricky case. We will look into improving the detection for such cases.

> BTW, it would be nice if angular team provide some test utils for hydration.

Thanks for the feedback.

Testing utilities for applications that use hydration is something that we'd like to explore and collect more feedback about. Could you please open a new ticket (a feature request) and describe a solution that would work for your application and test scenarios? We'll also use the ticket to collect the feedback from the community to capture more use-cases that we'd need to take into account.

**Comment by leo6104** [comment] 2023-04-19 02:12
@AndrewKushnir  Thanks for suggestion! 

We made first-version test util and it works well. Its error message shows all child components hydration mismatch. It makes we find the root cause component of hydration error. 

```
  fit('should pass `list-item[withImage]` tag', async () => {
    @Component({
      standalone: true,
      selector: 'app',
      template: '<list-item withImage></list-item>',
      imports: [
        ListItemWithImage,
      ],
    })
    class SimpleComponent {
    }

    const { verifyHydrate } = await assertionsForHydration(SimpleComponent, []);
    expect(verifyHydrate).not.toThrow();
  });
```

[Result]
![image](https://user-images.githubusercontent.com/7777929/232947954-b352dd34-da8c-493c-8274-811dea13f2c0.png)

With more investigation, i will make new feature-request issue in next week and share brief concept for these `assertionsForHydration` utils.
