### ISSUE TITLE
Method Signature of Route Config UrlMatcher does not match Shared.ts defaultUrlMatcher

### ISSUE THREAD

**Issue by co-al-re** [angular/angular#34729] opened 2020-01-10 21:14 UTC
# 🐞 bug report

### Affected Package
@angular/packages/router

### Is this a regression?

Issue existed and reported before in Angular 8 but not resolved correctly. Someone suggested changing it to test against a zero length consumed[] array but there was never followup to make the change. Personally I think leaving it with expecting null is fine, but the method signature for UrlMatcher needs to be fixed.

Bug still exists in 9 RC 1.

Should be: <pre><code>
export type UrlMatcher = (segments: UrlSegment[], group: UrlSegmentGroup, route: Route) =>
    UrlMatchResult | null;
</code></pre>

### Description

The implementation in recognize.ts match(...) tests the result of either the config.matcher or defaultUrlMatcher against null and throws a NotMatch(). The method signature in shared.ts for defaultUrlMatcher is correct and works, but the signature in config.ts UrlMatcher does not allow nulls to be returned.

This doesn't match documentation and results in typescript compile errors when trying to implement a custom matcher.

## 🔬 Minimal Reproduction
<pre><code>
const routes: Routes = [
  {
    matcher: (url) => {
      return url.length === 1 && url[0].path.match(/\d+/) ? 
         ({
          consumed: url,
          posParams: {
            id: url[0].path
          }
        }) : null;
    },
    component: MyComponent
  }
</code></pre>

## 🔥 Exception or Error
<pre><code>
Type '{ consumed: UrlSegment[]; posParams: { id: string; }; } | null' is not assignable to type 'UrlMatchResult'.
        Type 'null' is not assignable to type 'UrlMatchResult'.
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.3.21
Node: 12.13.1
OS: win32 x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.21
@angular-devkit/build-angular     0.803.21
@angular-devkit/build-optimizer   0.803.21
@angular-devkit/build-webpack     0.803.21
@angular-devkit/core              8.3.21
@angular-devkit/schematics        8.3.21
@angular/cli                      8.3.21
@angular/material                 <error>
@ngtools/webpack                  8.3.21
@schematics/angular               8.3.21
@schematics/update                0.803.21
rxjs                              6.5.4
typescript                        3.5.3
webpack                           4.39.2
</code></pre>

**Comment by william-lohan** [comment] 2020-01-14 16:16
dup of #29824 
fixed by #31098

**Comment by atscott** [comment] 2020-01-14 23:31
Duplicate of #29824

**Closed by atscott** 2020-01-14 23:31 UTC
Labels: comp: router
