### ISSUE TITLE
issue : in angular 2+ version "this" key world  get conflict or overlap many times. If you use nested function or way out of from parent function.!  In angular why they not create special  key instance of  'this' key world ? which hold separate angular application scope for 'this'.   Suggestion: In angular component  they can create   special key world  example: "ngThis"

### ISSUE THREAD

**Issue by JituG22** [angular/angular#33640] opened 2019-11-07 03:45 UTC
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

Please help us process issues more efficiently by filing an
issue using one of the following templates:

https://github.com/angular/angular/issues/new/choose

Thank you!

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by AndrewKushnir** [comment] 2019-11-07 05:38
Closing as a duplicate of #33641.

**Closed by AndrewKushnir** 2019-11-07 05:38 UTC
