### ISSUE TITLE
Add model to FormGroup

### ISSUE THREAD

**Issue by pacocom** [angular/angular#38935] opened 2020-09-22 07:33 UTC
Add model to FormGroup similar to:

```
interface FormModel {
  name: string;
  car: number;
  ...
}

@Component({
  selector: 'app-form',
  templateUrl: './form.component.html',
  styleUrls: ['./form.component.scss'],
})
export class AppAddComponent implements OnInit {
form: FormGroup<FormModel>;

constructor( private fb: FormBuilder }

ngOnInit(): void {
  this.form = this.fb.group({
    name: new FormControl(''),
    car: new FormControl(10),
  })
}
```

# 🚀 feature request

### Relevant Package

 This feature request is for @angular/....

### Description
 A clear and concise description of the problem or missing capability...

### Describe the solution you'd like
 If you have a solution in mind, please describe it.

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

**Comment by Airblader** [comment] 2020-09-22 08:36
Duplicate of #31963 and about a dozen issues linked in there

**Comment by AndrewKushnir** [comment] 2020-09-22 21:13
Closing as a duplicate of #31963.

**Closed by AndrewKushnir** 2020-09-22 21:13 UTC
Labels: comp: forms, type: feature
