### ISSUE TITLE
bug: service instantiated eagerly when it has a lifecycle hook

### ISSUE THREAD

**Issue by wardbell** [angular/angular#14552] opened 2017-02-17 04:29 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When a provided service implements the `ngOnDestroy` lifecycle hook (the only LC hook honored by Angular at this point), Angular instantiates the service eagerly with the module/component/directive that creates it. But if the service does not implement this hook, Angular waits and only instantiates it when the service is requested.

**This is clearly intended behavior**. There is a test for it here:
https://github.com/angular/angular/blob/d169c2434e3b5cd5991e38ffd8904e0919f11788/modules/%40angular/core/test/linker/ng_module_integration_spec.ts#L919

At a minimum we need to document this extraordinary result. 

> p.s. We also need to add documentation about `ngOnDestroy` in the regular docs; that is already on the docs' todo list.

More importantly, I believe this behavior is mistaken on several grounds.

1. It is inconsistent. Why create in the presence of a destroy method and but not create w/o a destroy method?

1. Such a service could unintentionally acquire resources and start working when it isn't actually needed at all. Developers don't know about this behavior and won't know that their constructors are called before they are expected to be called.

1. Adding the destroy hook changes the behavior of the service. A service that was once constructed lazily will now be created eagerly for no apparent reason.

1. It complicates the service API. There is no easy way to make the service wait until needed before it starts doing potentially expensive initialization work. Folks will have to come up with private protocols to call init on the service or bury the init logic in the methods of the service's public API.

1. It's not clear that its scope of application is as intended. The behavior appears to have been introduced in connection with NgModules but, per the test and my experience, it applies also when the service is provided to components and directives.

This "feature" appears to have been in the product since August of 2016 (ecdaded) so I can't say that it is a breaking change.

**Expected behavior**

Please either remove this behavior for Angular v.4  **OR** explain what good purpose it serves.  In the latter case, the documentation should convey this explanation to users so they will understand what is otherwise a mysterious and inconsistent result.

* **Angular version:** 2.4.X (since RC5)

It's still in master.

**Comment by DzmitryShylovich** [comment] 2017-02-17 07:45
> remove this behavior for Angular

Eager/lazy initialization is a must for any decent DI impl.

But I agree it was a poor design decision to use `ngOnDestroy` for this. There's https://github.com/angular/angular/issues/13960 already a proposal to change configuration by:
1. extending provider syntax
```
{provide: Service, useClass: MyService, lazy: false}
```
2. extending `Injectable` annotation
```
@Injectable({lazy: false})
```

So I would say it's a duplicate of https://github.com/angular/angular/issues/13960

**Comment by wardbell** [comment] 2017-02-17 18:22
>a must for any decent DI impl

Really? Where is that written? I do not know of any DI system that instantiates its services until they are requested. I've been using DI for 15 years.

Why would it be OK to wait when there is no `ngOnDestroy`.  If decency demands immediate construction, then that should have been true for all dependencies, whether or not they had a particular method.

What is the value of constructing a service immediately, before it is ever requested? What purpose does that serve? I can't think of a use case. And if I did (and it would be rare),  I could achieve the intended effect trivially by immediately injecting the service in the module/component/directive that provided it.

Whether decent or indecent, I'm still waiting for an explanation.

**Comment by DzmitryShylovich** [comment] 2017-02-17 18:32
> I do not know of any DI system that instantiates its services until they are requested. I've been using DI for 15 years.

[Spring](http://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/context/annotation/Lazy.html). the most popular java framework.

[Google Guice](https://github.com/google/guice/wiki/Scopes#eager-singletons) also has the ability to eager/lazy initialize services.

If you don't have such a use case it doesn't mean nobody hasn't.

**Closed** 2017-03-14 21:32 UTC
