### ISSUE TITLE
@Optional triggers warning "Can't resolve all parameters" with AOT-compilation (official documentation)

### ISSUE THREAD

**Issue by akloeber** [angular/angular#24533] opened 2018-06-15 07:04 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
With AOT-compilation enabled the example for `@Optional` at https://angular.io/api/core/Optional raises the following warning:
```
ng build --prod --aot=true
Warning: Can't resolve all parameters for Car in /private/tmp/foo/src/app/Car.ts: (?). This will become an error in Angular v6.x
...
```
With JIT-compilation there is not error.

## Expected behavior
There should not be a warning.

## Minimal reproduction of the problem with instructions

1. Bootstrap project via `ng new foo --version 1.7.4`
2. Add `src/app/Car.ts` with the following content

        import {Injectable, Optional} from '@angular/core';

        class Engine {
        }

        @Injectable()
        export class Car {
          constructor(@Optional() public engine: Engine) {
          }
        }

    __NOTE: Class Car needs to be exported in order to trigger this error!__ 
3. Run `ng build --prod --aot=true`:

         10% building modules 4/4 modules 0 activeWarning: Can't resolve all parameters for Car in /private/tmp/foo/src/app/Car.ts: (?). This will become an error in Angular v6.x
        Warning: Can't resolve all parameters for Car in /private/tmp/foo/src/app/Car.ts: (?). This will become an error in Angular v6.x
        Date: 2018-06-15T06:54:12.105Z                                                          
        Hash: 500b30562c9f670e5970
        Time: 3837ms
        chunk {0} polyfills.515ed9df1f4876ab6cb6.bundle.js (polyfills) 59.8 kB [initial] [rendered]
        chunk {1} main.f46d9721702aed0cb018.bundle.js (main) 154 kB [initial] [rendered]
        chunk {2} styles.ac89bfdd6de82636b768.bundle.css (styles) 0 bytes [initial] [rendered]
        chunk {3} inline.318b50c57b4eba3d437b.bundle.js (inline) 796 bytes [entry] [rendered]
## Environment

```
$ ng --version

    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
    
Angular CLI: 1.7.4
Node: 8.9.4
OS: darwin x64
Angular: 5.2.11
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.7.4
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.5.3
webpack: 3.11.0
```

**Comment by splincode** [comment] 2018-06-15 07:57
also just add the demo repository right away

**Comment by akloeber** [comment] 2018-06-15 09:31
@splincode But then an instance of `Engine` is instantiated and injected into the `Car` instance. As far as I understand the intention of `@Optional` is to define a dependency that may be missing for DI and it should only be injected if available.

**Comment by splincode** [comment] 2018-06-15 09:42
https://medium.com/frontend-coach/self-or-optional-host-the-visual-guide-to-angular-di-decorators-73fbbb5c8658

Maybe we can

```ts
import {Injectable, Optional, SkipSelf} from '@angular/core';

 class Engine {
 }

 @Injectable()
 export class Car {
   constructor(@SkipSelf() @Optional() public engine: Engine) {
   }
 }
```

**Comment by magnattic** [comment] 2018-06-15 16:57
Can confirm, this happens even during runtime for me, when resolving a service in a lazy loaded module. It seems the Optional() is simply being ignored.

**Comment by akloeber** [comment] 2018-06-15 19:00
@splincode Using `@SkipSelf` doesn't make any difference.

**Comment by jhkuperus** [comment] 2018-10-31 10:53
Is this issue expected to be fixed in a 7.x release? It currently breaks our AOT build as well. Working around it now by lazy-assigning the default value in a class:

Our problem was in this code:

```
@Injectable()
class MyService {
  constructor(@Optional() readonly serviceName: string = 'default') {}
}
```

And I turned it into this for now:

```
@Injectable()
class MyService {
    private _actualServiceName: string

    public get serviceName(): string {
        return (this._actualServiceName) ? this._actualServiceName : 'default'
    }

    public set serviceName(newName: string) {
        this._actualServiceName = newName
    }

  constructor() {}
}
```

It's not exactly the semantics I want, but at least the AOT-compiler accepts it. I've added a note to revert it back to its old self when this issue gets resolved :)

**Comment by shwetdalal** [comment] 2018-12-04 10:10
I am facing the similar kind of issue while creating build for application.
It runs fine with local build when creating production build it does not minify one function.

in component file
```
editRescheduleCall(currentLeadData) {
    const dialogRef = this.dialog.open(FormComponent, {
      height: 'auto',
      width: '480px',
      panelClass: 'no-padding'
    });
    this.messagingService.publish(new EditMessage(true, currentLeadData as Call))
  }
```

in model file
```
export  class EditMessage {
  constructor(public show: boolean, public lead: Call){ }
}
```

After creating build this.messagingService.publish(new EditMessage( minifies to Jh or Hj function name everywhere. Just at one place it does not minifies and keep the function name as it is.

**Comment by dmattsson** [comment] 2018-12-09 09:32
I'm also facing this issue when building for prod (but not with ng serve). Is @Optional() not supported for AOT?

**Comment by trotyl** [comment] 2018-12-09 09:53
@akloeber You have to add `export` to `class Engine` like:

```typescript
export class Engine {
}
```

The AOT compiler is going to create an extra file imports the token, but a non-export class cannot be referenced, which cause the error.

The error message could indeed be improved somehow.

**Comment by akloeber** [comment] 2018-12-10 17:48
@trotyl Indeed, if `Engine` is exported the warning is not shown. Still not really obvious and hopefully fixed in Ivy.

**Comment by QXD-me** [comment] 2019-03-23 14:16
I got this error from an optional Date (i.e. the built in date object). Am I supposed to export Date to make the AOT complier work for my service?

**Comment by bjohnson-va** [comment] 2019-05-15 21:19
A workaround that I've been using (accidentally until today) is to add the @Inject() decorator, as well.

```
constructor(
  @Optional() @Inject('TokenNoOneWillEverUse') private readonly myOptionalThing?: MyThing,
)
```

**Comment by NgoKimPhu** [comment] 2019-05-27 10:11
@akloeber This issue is mentioned in https://angular.io/guide/aot-compiler#could-not-resolve-type
> The compiler encountered a type and can't determine which module exports that type.

thus the class needs to be exported in order to be seen by the compiler

**Comment by damienwebdev** [comment] 2019-06-25 15:25
Tacking on here from another issue... as laid out by @csbenjamin [here](https://github.com/angular/angular/issues/23849#issuecomment-407446551)

```
export class MyService {
    constructor(@Optional() @Inject('MY_STRING_TOKEN') private myOptionalService) {}
}
```

and I don't provide 'MY_STRING_TOKEN', the app works as expected and I have `this.myOptionalService === null'. But if I do the following

```
export const MY_NON_STRING_TOKEN = new InjectionToken<string>('MY_NON_STRING_TOKEN');
export class MyService {
    constructor(@Optional() @Inject(MY_NON_STRING_TOKEN) private myOptionalService) {}
}
```

even if I do provide something with this token, Angular throws an error:
> Can't resolve all parameters for MyService:

**Comment by alxhub** [comment] 2019-06-25 17:21
@damienwebdev 

1) `MyService` should be `@Injectable`. I suspect that's the root of the problem.
2) This needs a proper reproduction, either via Stackblitz or Github repo. I can't reproduce it myself, it appears to work: https://stackblitz.com/edit/angular-fbynmw?file=src%2Fapp.ts

**Comment by damienwebdev** [comment] 2019-06-26 18:42
@alxhub https://stackblitz.com/edit/angular-wx1lsk?file=src/app.ts

I'm not sure if this is a quirk of stackblitz, but I removed the `readonly` and was able to replicate.

**Comment by ggradnig** [comment] 2019-07-11 14:36
I found this issue when transpiling to `es5`, because `const` is converted to `var` there and that seems to break these InjectionTokens. Try chaning your target to `es6` and see if it works then.

**Comment by redplane** [comment] 2019-09-06 06:14
So annoying bug. I'm facing the same issue with @damienwebdev

**Comment by waterplea** [comment] 2020-01-22 08:25
> @akloeber You have to add `export` to `class Engine` like:
> 
> ```ts
> export class Engine {
> }
> ```
> 
> The AOT compiler is going to create an extra file imports the token, but a non-export class cannot be referenced, which cause the error.
> 
> The error message could indeed be improved somehow.
> 
> Fixed by Ivy.

But what if I'm injecting native class? I have `AudioNode` extending directives that provide themselves as `AudioNode`. It works fine in JIT but in AOT it breaks. Wouldn't want to add a redundant token :(

**Comment by totszwai** [comment] 2020-02-12 13:36
It even fail like this:
`
@Injectable()
export class Blah {
  constructor(@Optional() blah?: any) {}
}
`

I tried providing my own deps doesn't work either...
`
@Component({
  providers: [
    {
      provide: Blah,
      useClass: BlahBlah,
      deps: [ { hello: 'world' } ]
    }
  ]
`
Am I doing something wrong?

**Comment by brutuscat** [comment] 2020-03-12 14:59
We are getting the warning, in our case because our service declares some of its dependencies using an interface, but we see no errors nor other problems. It is just a warning for us and it makes sense in this case given that we use factories to provide the service.

```typescript
export class MyService {
  constructor(
    other: OtherDep,
    [..],
    readonly foo: IFoo,
    readonly bar: IBar,
  ) {}
[..]
}

export function myServiceFactory(
  other: OtherDep,
  records: IRecords
) {
  let foo = new ConcreteBFoo();
  if (records.getAll().first instanceof typeA) {
    foo = new ConcreteAFoo();
  }
 
  return new MyService(
    other,
    [..],
    foo,
    new ConcreteBar(foo)
  );
}

export const typeAMyServiceProvider = {
  provide: MyService,
  useFactory: myServiceFactory,
  deps: [
    OtherDep,
    ARecordsService
  ],
};

// Then in the lazy loaded module
providers: [
  typeAMyServiceProvider,
]
```

Probably if you have a provider that uses a factory it should work?

**Comment by JoostK** [comment] 2020-03-17 23:19
The reported issue has been resolved in Ivy!

@totszwai The constructor of `Blah` asks for a paramter of type `any`. The Angular DI system has no idea what you're asking for in that case, so it'll produce the error. The example with `deps` should work, iff you remove `@Injectable()` from the `Blah` class.

**Closed by JoostK** 2020-03-17 23:19 UTC
Labels: comp: compiler, comp: core, comp: docs, comp: docs/api, core: di, fixed by Ivy, freq2: medium, severity3: broken, type: bug/fix
