### ISSUE TITLE
Form control has incorrect value type

### ISSUE THREAD

**Issue by chabb** [angular/angular#50318] opened 2023-05-16 07:31 UTC
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

No ( not 100% sure )

### Description

Form control value is incorrectly typed when I use bindings

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-xwwgsg?file=src/index.html

### Please provide the exception or error you saw

```true
The form input has the `number` type. You can only enter numbers. But when you click on the button, you'll notice the value is a string ( incorrect )

If you remove the binding, and explicitly set the type, the value of the form will be a number ( correct )
```

### Please provide the environment you discovered this bug in (run `ng version`)

angular 15

**Comment by JeanMeche** [comment] 2023-05-16 08:23
Hi, this is a long standing issue. 

Dupe of #13243

**Closed** 2023-05-16 09:35 UTC
