### ISSUE TITLE
adding the quote key in html usage

### ISSUE THREAD

**Issue by teamIgal** [angular/angular#46816] opened 2022-07-13 07:56 UTC
### Description

hi there
I am not sure if it is already possible or not but I could find anything on the internet.
I would like to do something like this <input (keydown.shift.quote)> the important thing is the quote part i know i could do this on the typescript part of the component but it would be more nice to do it like the way i showed.
thank you for the help :)

### Proposed solution

adding a name to the quote(") key like arrowUp for example

### Alternatives considered

checking the key in the typescript like event.key === '"'

**Comment by jessicajaniuk** [comment] 2022-07-13 16:10
@teamIgal Thanks for the submission. This looks like a duplicate of #45992, which would allow using the code field, making using Quote with key events possible. There's an open PR in review right now that should address this. Feel free to follow #46030.

**Closed by jessicajaniuk** 2022-07-13 16:10 UTC
Labels: comp: core
