### ISSUE TITLE
`model()` with `transform` option for common ControlValueAccessor use-cases

### ISSUE THREAD

**Issue by lacolaco** [angular/angular#56912] opened 2024-07-09 09:50 UTC
### Which @angular/* package(s) are relevant/related to the feature request?

- `@angular/core`

## Summary

- In common situations about ControlValueAccessor, `input()` and `model()` are not useful too.
- I think the missing piece is the `transform` option of the `model()` function.

Please consider a custom checkbox scenario like below. The component has `disabled` input which can set by three ways: 1. HTML-standard style `<app-checkbox disabled>`, 2. Simple property-binding `<app-checkbox [disabled]="true">` and 3. via form control `disable()` method.

```ts
@Component({
  selector: 'app-root',
  standalone: true,
  imports: [AppCheckbox, ReactiveFormsModule],
  template: `
    <app-checkbox disabled />
    <app-checkbox [disabled]="true" />
    <app-checkbox [formControl]="formControl" />
  `,
})
export class App {
  formControl = new FormControl(false);

  constructor() {
    this.formControl.disable();
  }
}
```

Quite simply, that functionality cannot be achieved with Signal APIs at the same time. 

With `input()` function, the `disabled` property becomes a read-only signal within the component. So `setDisabledState()` cannot set a value from the form control. 

```ts
@Component({
  selector: 'app-checkbox',
})
export class AppCheckbox {
  disabled = input(false, { transform: booleanAttribute });

  setDisabledState(isDisabled: boolean) {
    this.disabled.set(isDisabled); // <--- input() is read-only
  }
}
``` 

On the other hand, with `model()` function cannot take the `transform` option. So `<app-checkbox disabled>` doesn't work.

```ts
@Component({
  selector: 'app-checkbox',
})
export class AppCheckbox {
  disabled = model(false, { transform: booleanAttribute }); // <-- model doesn't have `transform`

  setDisabledState(isDisabled: boolean) {
    this.disabled.set(isDisabled);
  }
}
```

Unfortunately, there was an issue proposed in the past regarding a similar problem, but it was closed by implementing the `model()` function. However, it does not cover the existing CVA use cases.

- https://github.com/angular/angular/issues/53889

### Proposed solution

Making the `model()` function to accept the `transform` option.

### Alternatives considered

Or, adding a completely new method for use cases such as `ControlValueAccessor`.

**Comment by JeanMeche** [comment] 2024-07-09 10:49
Transform for model has been discussed previously in #55166. 

> `model()` not supporting `transform` is by design.
> 
> Model properties are designed for synchronization - keeping an outside copy of the data in sync with the value of the model. This is expressed via the two-way binding sugar `[(model)]="outsideData"`. With this statement, `outsideData` and the model should stay in sync via change detection (data -> model) and the `modelChange` event (model -> data).
> 
> Because this synchronization is bi-directional, it'd be confusing to support a transformation during the data -> model operation. That would result in the value in the model being _different_ than the value of the outside data. Either:
> 
> 1. We accept this discrepancy as how things work.
> 
> We don't think this option is a good fit, because it makes `model` more difficult to reason about if the internal value can be different than the external value when its entire purpose is to keep them in sync.
> 
> This is also equivalent to declaring a `computed` that applies the transform, which is straightforward to achieve already.
> 
> 2. We make `model` emit a `modelChange` event after the transform changes the value.
> 
> This would keep the outside data in sync with the model, but has some major issues. For one, it would cause `ExpressionChanged` errors if used with a non-signal two way binding. Even with signals, it could result in infinite looping change detection if the transform always produces a new value, which is easy to do accidentally.
> 
> Given that it's straightforward to work around this by using a `computed` (which makes it obvious to anyone looking at the code that the transform is internal-only), we don't plan on adding any support for `transform` to `model`. However, we would be interested in collecting use cases when people feel like `transform` is necessary, or that the additional boilerplate of a `computed` is too great.

**Comment by pkozlowski-opensource** [comment] 2024-07-09 11:10
As @JeanMeche mentioned, `model` is lacking transform by design. We do understand that the story of signals + forms is not ideal yet and this is one of the integration points that is high on our priority list.

Duplicate of https://github.com/angular/angular/issues/55166.

**Closed by pkozlowski-opensource** 2024-07-09 11:10 UTC
