### ISSUE TITLE
Template reference variable not accessible across <ng-template>'s

### ISSUE THREAD

**Issue by delashum** [angular/angular#31825] opened 2019-07-24 16:40 UTC
# 🐞 bug report

### Affected Package

The issue is cause by package @angular/core

### Is this a regression?

No

### Description

When using multiple templates in a single component, a template reference variable defined in one template is undefined in the other.

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-lgdbcy

## 🔥 Exception or Error

none

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.0.0
Node: 11.13.0
OS: darwin x64
Angular: 8.0.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.0
@angular-devkit/build-angular     0.800.1
@angular-devkit/build-optimizer   0.800.1
@angular-devkit/build-webpack     0.800.0
@angular-devkit/core              8.0.0
@angular-devkit/schematics        8.0.0
@ngtools/webpack                  8.0.1
@schematics/angular               8.0.0
@schematics/update                0.800.0
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.29.0
</code></pre>

**Comment by pkozlowski-opensource** [comment] 2019-07-24 17:37
This is by design - local references are scoped to a template (view). Closing as works as intended.

**Closed by pkozlowski-opensource** 2019-07-24 17:37 UTC
Labels: comp: core
