### ISSUE TITLE
ngFor list tracking

### ISSUE THREAD

**Issue by kesheshyan** [angular/angular#13623] opened 2016-12-22 00:01 UTC
**I'm submitting a**
```
[x] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Not sure if this is a bug or a feature request, but radokirov@google.com suggested me to file an issue. 
When there is a list of primitives, let say booleans ```let list: Array<boolean> = [true, true, false, true]```, *ngFor is not capable to track it correctly. It's clear from documentation, that it is required to use some tracking function, but it looks overkilled to implement a tracking function that looks like this:
 ```
track(i: number): number {
   return i;
}
```

**Expected behavior**

Is it possible to add a predefined variable `index` as a tracking parameter?
```*ngFor="let item of list; let i = index; trackBy: index"```

**Minimal reproduction of the problem with instructions**

https://plnkr.co/edit/I1MP9vMfDyC9jdCgJCe0?p=preview

**What is the motivation / use case for changing the behavior?**
Get rid of unnecessary tracking function.

**Please tell us about your environment:** Goobuntu, Cider
* **Angular version:** 2.2.1
* **Browser:**  Chrome 55.0.2883.87 (64-bit)
* **Language:** TypeScript

**Comment by DzmitryShylovich** [comment] 2016-12-22 00:04
Duplicate of https://github.com/angular/angular/issues/12969

**Comment by DzmitryShylovich** [comment] 2017-02-01 13:09
@pkozlowski-opensource duplicate

**Closed** 2017-02-01 14:08 UTC
Labels: comp: core & compiler
