### ISSUE TITLE
TestComponentBuilder needs common directives referenced in @View

### ISSUE THREAD

**Issue by matthewdenobrega** [angular/angular#6195] opened 2015-12-31 14:45 UTC
Currently the common directives (CORE_DIRECTIVES and FORM_DIRECTIVES) are included automatically and do not need to be manually referenced in a component's @View annotation. However this is not the case for the TestComponentBuilder, which fails to build the component if the component uses unreferenced common directives. An example error message is:

    {"message":"Template parse errors: Can't bind to 'ngFormControl' since it isn't a known native property...

It's possible to add these references in to the component definition, but ideally the TCB should be able to build whatever Angular builds normally. Also the way the TCB handles errors (calling the onrejected callback of the promise, which I seldom see anyone binding to) means that tests can be regarded as passing if the component fails to build:

    tcb.createAsync(testComponent).then((fixture: ComponentFixture) => {
        expect(true).toBe(false)
    })

Will pass if the TCB fails to create the component. 

So proposed solution would be to make the common directives available to the TCB.

**Comment by ericmartinezr** [comment] 2015-12-31 15:09
There's a fix for this in https://github.com/angular/angular/pull/5975

**Comment by pkozlowski-opensource** [comment] 2015-12-31 15:29
Closing as duplicate of #5433

**Closed by pkozlowski-opensource** 2015-12-31 15:29 UTC
