### ISSUE TITLE
Looking for list of built-in pipes

### ISSUE THREAD

**Issue by angelinaebreo** [angular/angular#56465] opened 2024-06-15 00:15 UTC
### Describe the problem that you experienced

https://angular.dev/guide/pipes
`Note: For a complete list of built-in pipes, see the [pipes API documentation](https://angular.dev/api/common#pipes). To learn more about using pipes for internationalization (i18n) efforts, see [formatting data based on locale](https://angular.dev/guide/i18n/format-data-locale).`

Note refers to [pipes API documentation](https://angular.dev/api/common#pipes) which is "Page Not Found"

### Enter the URL of the topic with the problem

https://angular.dev/api/common#pipes

**Comment by JeanMeche** [comment] 2024-06-15 05:24
Duplicate of https://github.com/angular/angular/issues/52968

**Closed by JeanMeche** 2024-06-15 05:24 UTC
