### ISSUE TITLE
Angular 4.3 onwards -# in regular expression causes screens not to hide

### ISSUE THREAD

**Issue by MikePater** [angular/angular#19862] opened 2017-10-22 23:49 UTC
## I'm submitting a...

<pre><code>
[X ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
From Angular 4.3.6 onwards ( I tested up to 4.4.6 ) the following pattern ( Validators.pattern) in a form control causes screens to duplicate ( ie not hide.. )
^[a-zA-Z0-9'.,-#]+(\\s+[a-zA-Z0-9'.,-#]+)*$

So you see the screen you are on now.. and below it the previous screen is displayed
I tracked the issue down to the pattern validation... the dash and the hash character together in the above pattern causes the issue.  There was no java script error in the console.
The following works okay... 
^[#a-zA-Z0-9'.,-]+(#\\s+[a-zA-Z0-9'.,-]+)*$
It also works okay if the dash and has are not together

## Expected behavior
When going from one component to another the previous screen should not be shown.
Or at least an error message in the console.

## What is the motivation / use case for changing the behavior?
Defect

## Environment

<pre><code>
Angular version: 4.3.6 up to 4.4.6 doesn't work.
4.2.6 does.

Browser:
- [X ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by erbsenkoenig** [comment] 2017-10-23 02:02
Ich kehre zurück am 01.11.2017.

Ich werde Ihre Nachricht nach meiner Rückkehr beantworten.
In dringenden Fällen senden Sie bitte eine Kopie Ihrer E-Mail für
technische Angelegenheiten an entwicklung@arxes-tolina.de, ansonsten an
info@arxes-tolina.de. Ein anderer Mitarbeiter wird sich dann Ihrer E-Mail
annehmen.


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht
"[angular/angular] Angular 4.3 onwards -# in regular expression causes
screens not to hide (#19862)" gesendet am 23.10.2017 01:49:54.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während
diese Person abwesend ist.

**Comment by vicb** [comment] 2017-10-23 18:12
This should be an easy fix: escape the `-`.
I have seen inconsistent behavior across browser wrt to `-` but here escaping is the obvious solution.
/cc @kara

**Comment by MikePater** [comment] 2017-10-23 22:37
Escaping the – will fix the issue..

But I logged the defect so that the form control doesn’t throw some invisible internal error when it’s an invalid regular expression…   is that able to be fixed ?

We don’t require it, just thought for future issues from other people..

Thanks
Mike Pater

**Comment by kara** [comment] 2017-10-24 19:20
Yeah, it looks like the regex is just invalid. I'm not sure why the error isn't being thrown in your project. We don't do anything special to suppress regex errors and none of the pattern validator code has changed in about a year.  Created a quick plunker with 4.4.6 and confirmed that the error comes up in the console: https://stackblitz.com/edit/angular-esk5zt?file=app%2Fapp.component.ts. 

Given that we can't reproduce this, closing the issue.

**Closed by kara** 2017-10-24 19:20 UTC
Labels: comp: forms
