### ISSUE TITLE
*ngFor structural directive on multiple checkboxes breaks checked state inside <form> element.

### ISSUE THREAD

**Issue by cdslijngard** [angular/angular#19592] opened 2017-10-06 10:05 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
I'm looping over a JSON object array using *ngFor structural directive to show checkboxes. I want them ticked if a property of the object == true.

I found out (after pulling half my hair off) that if you try to this inside a `<form></form>` element, the checked status of checkboxes break.

If I'm just not understanding how forms work or anything, please let me know in the comments below, otherwise, please see my stackoverflow post.
[https://stackoverflow.com/questions/46601361/angular-2-handling-multiple-checkboxes-checked-state/46603106#46603106](url)

## Expected behavior

It should tick / untick the checkboxes just as if the *ngFor loop functions outside of the form element.

## Minimal reproduction of the problem with instructions
[https://stackoverflow.com/questions/46601361/angular-2-handling-multiple-checkboxes-checked-state/46603106#46603106](url)

## What is the motivation / use case for changing the behavior?

[https://stackblitz.com/edit/angular-hoemtb?file=app%2Fapp.component.ts](url)

Try the Stackblitz above. Without the <form> element wrapping the form-group div, it works the way I want.

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [latest ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ latest] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 6.11.3
- Platform:  Windows 10
- Angular CLI version 1.4.4
- NPM 5.4.2

Others:

</code></pre>

**Comment by alexzuza** [comment] 2017-10-07 18:38
Sounds like similar to https://stackoverflow.com/questions/44476677/ngmodel-cannot-detect-array-changes-correctly

**Comment by trotyl** [comment] 2017-10-14 18:15
Duplicate of https://github.com/angular/angular/issues/13993.

**Comment by kara** [comment] 2018-06-07 22:51
As @trotyl pointed out, the problem in the example is that the controls are being created with the same name. As soon as you put controls with the same name in the same form group, there won't be a way to differentiate them. Generally speaking, for things like this, `formArrayName` is the preferred way to go.

**Closed by kara** 2018-06-07 22:51 UTC
Labels: comp: forms

**Comment by dannygoncalves** [comment] 2018-12-07 15:51
@kara your answer saved me a lot of time digging through this error, thanks a lot.
