### ISSUE TITLE
Flexlayout not working with ivy

### ISSUE THREAD

**Issue by chrste90** [angular/angular#32289] opened 2019-08-23 13:31 UTC
# 🐞 bug report

### Affected Package
@angular/flex-layout with ivy enabled

### Is this a regression?
Yes, the previous version in which this bug was not present was: same version, with ivy disabled

### Description
With ivy enabled, i can't use flex layout.

## 🔬 Minimal Reproduction
```
git clone https://github.com/chrste90/flex-layout-ivy
cd flex-layout-ivy
npm install
ng serve
```

## 🔥 Exception or Error
Runtime error if you open the browser at `http://localhost:4200`
<pre><code>
ERROR TypeError: Cannot read property 'init' of undefined
    at DefaultLayoutDirective.init (core.js:463)
    at new LayoutDirective (flex.js:176)
    at new DefaultLayoutDirective (flex.js:188)
    at core.js:5689
    at NodeInjectorFactory.DefaultLayoutDirective_Factory [as factory] (flex.js:192)
    at getNodeInjectable (core.js:5531)
    at instantiateAllDirectives (core.js:13001)
    at createDirectivesAndLocals (core.js:12367)
    at Module.ɵɵelementStart (core.js:21558)
    at AppComponent_Template (app.component.html:1)
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.0.0-next.0
Node: 10.16.3
OS: darwin x64
Angular: 9.0.0-next.3
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-next.0
@angular-devkit/build-angular     0.900.0-next.0
@angular-devkit/build-optimizer   0.900.0-next.0
@angular-devkit/build-webpack     0.900.0-next.0
@angular-devkit/core              9.0.0-next.0
@angular-devkit/schematics        9.0.0-next.0
@angular/cdk                      8.1.3
@angular/cli                      9.0.0-next.0
@angular/flex-layout              8.0.0-beta.26
@angular/material                 8.1.3
@ngtools/webpack                  9.0.0-next.0
@schematics/angular               9.0.0-next.0
@schematics/update                0.900.0-next.0
rxjs                              6.5.2
typescript                        3.5.3
webpack                           4.39.2
</code></pre>

**Comment by pkozlowski-opensource** [comment] 2019-08-23 14:13
flexlayout+ivy is already tracked in #31956, closing as a duplicate.

**Comment by kara** [comment] 2019-08-29 22:26
@Splaktar Can you explain why this is not a duplicate of #31956? Looking at it, they both have the same root cause that `this.marshal` is undefined, so trying to call `init` throws.

I suspect the root cause for both is the third breaking change on [this list](https://docs.google.com/document/d/1Dije0AsJ0PxL3NaeNPxpYDeapj30b_QC0xfeIvIIzgg/preview). flex-layout needs to decorate `LayoutDirective` with a `@Directive()` decorator to make it compatible with Ivy.

**Closed** 2019-08-29 22:27 UTC
Labels: comp: ivy

**Comment by Splaktar** [comment] 2019-08-29 23:05
OK, thank you for the update. Nothing in this report or the error messages that I saw mentioned `this.marshal`.

AFAIK @CaerusKaru isn't aware of the need to change `@angular/flex-layout` to be compatible with Ivy.

> Base classes extended by directives must also have an Angular @Directive() decorator if they use Angular-specific features like DI or param decorators (previously, undecorated base classes were allowed).

It does sound like a pretty simple fix though.

**Comment by akvaliya** [comment] 2019-09-03 14:33
Is this issue resolved. I am also facing issue with prod build

**Comment by Splaktar** [comment] 2019-09-06 23:05
This is fixed in `@angular/flex-layout` release `v8.0.0-beta.27`.

**Comment by xDveGax** [comment] 2019-10-03 06:48
Hi @Splaktar. Im having the same error when i run my test on Karma with a Headless browsers.
If my .html has a custom-breakpoint directive the error show.

```
ERROR TypeError: Cannot read property 'init' of undefined
    at DefaultLayoutDirective.init (core.js:463)
    at new LayoutDirective (flex.js:176)
    at new DefaultLayoutDirective (flex.js:188)
    at core.js:5689
    at NodeInjectorFactory.DefaultLayoutDirective_Factory [as factory] (flex.js:192)
    at getNodeInjectable (core.js:5531)
    at instantiateAllDirectives (core.js:13001)
    at createDirectivesAndLocals (core.js:12367)
    at Module.ɵɵelementStart (core.js:21558)
    at AppComponent_Template (app.component.html:1)

```

I have v8.0.0-beta.27
```

    "@angular/animations": "^8.2.9",
    "@angular/cdk": "^8.2.2",
    "@angular/common": "^8.2.9",
    "@angular/compiler": "^8.2.9",
    "@angular/core": "^8.2.9",
    "@angular/flex-layout": "^8.0.0-beta.27",
    "@angular/forms": "^8.2.9",
    "@angular/material": "^8.2.2",
    "@angular/platform-browser": "^8.2.9",
    "@angular/platform-browser-dynamic": "^8.2.9",
    "@angular/router": "^8.2.9",
```

Regards.

**Comment by Splaktar** [comment] 2019-10-03 07:36
@xDveGax Please [open a new issue here](https://github.com/angular/flex-layout/issues/new/choose) with a GitHub repo reproduction.

**Comment by JoostK** [comment] 2019-10-03 07:53
> @xDveGax Please [open a new issue here](https://github.com/angular/flex-layout/issues/new/choose) with a GitHub repo reproduction.

But before you do, please first try with a `next` release first: currently that's `9.0.0-next.9`.
