### ISSUE TITLE
There is no way to view the docs for specific previous angular versions

### ISSUE THREAD

**Issue by andrewl-telnyx** [angular/angular#19514] opened 2017-10-02 16:59 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

There is no way to view the docs for Angular 4.2.4...

## Expected behavior

There should be a way to view previous docs other than just v2, next, current, and dart.

## Minimal reproduction of the problem with instructions

Go here:
https://angular.io/guide/quickstart

click "API > stable(v...)"
There are only 4 versions to select from.

## What is the motivation / use case for changing the behavior?

It is not feasible for us to do a version bump at this exact point in time, and so much of angular changes/evolves so quickly that it is useful to go back in time to view the docs as they were at a specific version. My current use case is that I'm trying to test a service that uses HTTP. The newest docs say to use

```
import { HttpTestingController } from '@angular/common/http/testing';
```

expectOne, etc... but in 4.2.4 that module does not appear to exist.
I just need to write unit tests. Because of how quickly angular changes, there are no blog posts for that specific version that I can easily find, and [this: Angular Update Guide - 4.2 -> 4.4 for Basic Apps](https://angular-update-guide.firebaseapp.com/) mentions

> Switch from HttpModule and the Http service to HttpClientModule and the HttpClient service. HttpClient simplifies the default ergonomics (You don't need to map to json anymore) and now supports typed return values and interceptors. 

so some stuff changed with HttpModule and it's a mystery what it is completely that changed and what the implications are.

I understand that the reason for the current system (only showing 4 versions) may be to incentivize people to always use the latest version, however, that is not always realistic being that Angular changes so drastically so frequently.

## Environment

<pre><code>
Angular version: 4.2.4

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by gkalpak** [comment] 2017-10-02 18:25
Duplicate of #18324, so let's track it there.

As a work-around, if you absolutely need the docs for a specific version, you can checkout the repo and build the docs yourself. (I am ony suggesting this as a last-resort work-around, not implying it is good developer experience :smiley:)

For the `http` guide specifically, bc1ea8c54 is the commit that switched to the new `HttpClient` (so anything before that refers to the old `Http` service).

##
You are right that the idea is that there should be no breaking changes between minor versions, so keeping up-to-date should be as simple as updating your `@angular` dependencies, but in any case replacing the old guide with the new one might not be the best idea (for the `4.x` branch).

**Closed by gkalpak** 2017-10-02 18:25 UTC

**Comment by andrewl-telnyx** [comment] 2017-10-04 15:21
@gkalpak you again for the win! :-) 
thanks dood. 
that's what i ended up doing; though it was a bit of a pain to do because you require a specific yarn version (0.3.something >= and <1.0.0)
and yarn is currently on a version greater than that. The workaround was to remove that requirement from the package.json file and do some other weird stuff. I'd suggest looking into that; i can create a separate issue for it if you'd like.

**Comment by gkalpak** [comment] 2017-10-04 15:25
We have since upgraded `yarn` (on the latest branch at least). If you think there is more we ned to look into, please do file issue :smiley:
Glad it worked out for you 👍
