### ISSUE TITLE
Support Control flow analysis in angular template

### ISSUE THREAD

**Issue by xiaoxiangmoe** [angular/angular#39682] opened 2020-06-30 05:59 UTC
```ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  template: `
    <ng-container *ngIf="field.type === 'string'; else elseTemplate">
      {{ field.value }}
    </ng-container>
    <ng-template #elseTemplate>
      {{ field.value }}
    </ng-template>
    `,
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  field:
  | {
    type: 'number',
    value: number,
  }
  | {
    type: 'string',
    value: string,
  } = {
    type: 'string',
    value: 'str',
  };
}
```

The first `field.value` should have type `string` and the last should have type `number`. But in `angular.ng-template v0.1000.1`  both of these have type `string | number`

**Comment by JoostK** [comment] 2020-11-13 22:52
At which point it becomes a duplicate of #37840 and the issues that are linked from there: #34522, #20780 and #21504, so I'll close this one so we track it in one place.

**Closed by JoostK** 2020-11-13 22:52 UTC
