### ISSUE TITLE
Angular.dev Tutorial Missing Crucial Files

### ISSUE THREAD

**Issue by robmats99** [angular/angular#58841] opened 2024-11-23 19:11 UTC
### Describe the problem that you experienced

When going to the URL listed below and downloading the source code for the tutorial, the following files are missing:

1. angular.json
2. package.json
3. tsconfig.*

I believe the files are also missing for subsequent pages of the tutorial as well

Without a package.json, `npm install` fails, causing anyone who takes this tutorial to be sad 😭

### Enter the URL of the topic with the problem

https://angular.dev/tutorials/first-app/01-hello-world

### Describe what you were looking for in the documentation

The following files: 

1. angular.json
2. package.json
3. tsconfig.*

### Describe the actions that led you to experience the problem

1. Downloading the zip file from the tutorial
2. Running npm install in the directory

### Describe what you want to experience that would fix the problem

Having the files in all of the tutorial zips. They appear to be missing in more than just the first lesson.

### If this problem caused an exception or error, please paste it here

```true
npm error code ENOENT
npm error syscall open
npm error path ...\first-app_01-hello-world\package.json
npm error errno -4058
npm error enoent Could not read package.json: Error: ENOENT: no such file or directory, open '...\first-app_01-hello-world\package.json'  
npm error enoent This is related to npm not being able to find a file.
npm error enoent
```

### If the problem is browser-specific, please specify the device, OS, browser, and version

```true

```

### Provide any additional information here in as much as detail as you can

```true

```

**Comment by JoostK** [comment] 2024-11-23 21:47
Are you using Windows? This sounds like a duplicate of https://github.com/angular/angular/issues/57075 which is platform specific to Windows.

**Comment by JoostK** [comment] 2024-11-23 21:48
Based on the backwards slashes as directory separators I conclude this is indeed Windows, so closing as a duplicate of https://github.com/angular/angular/issues/57075

**Closed** 2024-11-23 21:48 UTC
