### ISSUE TITLE
i18n throws error when ICU definitions differ only by whitespace

### ISSUE THREAD

**Issue by pburkindine** [angular/angular#39227] opened 2020-10-12 15:30 UTC
# 🐞 bug report

### Affected Package
@angular/cli - xi18n

### Is this a regression?

No

### Description

The following two pieces of HTML differ only in whitespace:

```
<div i18n="@@foo">{bar, select, a {A} b {B}}</div>

<!-- prettier-ignore -->
<div i18n="@@foo">
  {bar, select,
   a {A}
   b {B}}
</div>
```

The i18n parser produces this output (notice the second ICU doesn't belong to @@foo as expected, but to an anonymous wrapping unit that doesn't however include the whitespace):

messages.xlf
```
      <trans-unit id="foo" datatype="html">
        <source>{VAR_SELECT, select, a {A} b {B}}</source>
        <context-group purpose="location">
          <context context-type="sourcefile">src/app/app.component.html</context>
          <context context-type="linenumber">1</context>
        </context-group>
      </trans-unit>
      <trans-unit id="1e174d9d008a1608b8d1a8d0efbb593125ac6e1a" datatype="html">
        <source>{VAR_SELECT, select, a {A} b {B}}</source>
        <context-group purpose="location">
          <context context-type="sourcefile">src/app/app.component.html</context>
          <context context-type="linenumber">5,7</context>
        </context-group>
      </trans-unit>
```

messages.es.xlf
```
      <trans-unit id="foo" datatype="html">
        <source>{VAR_SELECT, select, a {A} b {B}}</source>
        <target>{VAR_SELECT, select, a {C} b {D}}</target>
        <context-group purpose="location">
          <context context-type="sourcefile">src/app/app.component.html</context>
          <context context-type="linenumber">1</context>
        </context-group>
      </trans-unit>
      <trans-unit id="1e174d9d008a1608b8d1a8d0efbb593125ac6e1a" datatype="html">
        <source>{VAR_SELECT, select, a {A} b {B}}</source>
        <target>{VAR_SELECT, select, a {C} b {D}}</target>
        <context-group purpose="location">
          <context context-type="sourcefile">src/app/app.component.html</context>
          <context context-type="linenumber">5,7</context>
        </context-group>
      </trans-unit>
```

When the app is actually compiled (build or serve), neither unit is shown onscreen; instead, they both produce the error `Unable to parse ICU expression in "{VAR_SELECT, select, a {C} b {D}}" message.`

Many developers, myself included, would consider the leading and trailing whitespace in the `div` an error, but not everyone would agree on that point.  However, it's definitely not a syntax or breaking error (just extra whitespace in a div).  And the error messaging here didn't really help to detect our dev's mistake.

Our expectation would be that either
a) if there is nothing but whitespace around the ICU, it should be trimmed, or
b) that the wrapping, anonymous ICU should include the whitespace and handle wrapping the ICU quietly, or
c) a descriptive error could be thrown.

## 🔬 Minimal Reproduction

https://github.com/pburkindine/i18n-whitespace

`npm run start-es`

## 🔥 Exception or Error
<pre><code>

Unable to parse ICU expression in "{VAR_SELECT, select, a {C} b {D}}" message.

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 10.1.6
Node: 12.18.3
OS: darwin x64

Angular: 10.1.5
... animations, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1001.6
@angular-devkit/build-angular   0.1001.6
@angular-devkit/core            10.1.6
@angular-devkit/schematics      10.1.6
@angular/cli                    10.1.6
@schematics/angular             10.1.6
@schematics/update              0.1001.6
rxjs                            6.6.3
typescript                      4.0.3
</code></pre>

**Anything else relevant?**

No

**Comment by AndrewKushnir** [comment] 2020-10-12 18:08
This issue seems to be related to #25858 and #24080, but we should look into the error message and/or detection of such cases to see if we can improve it.

**Comment by petebacondarwin** [comment] 2020-10-12 18:23
I note that when there is no extra whitespace then in the `extractParts()` function we get a block that looks like:

```
"�0�, select, a {C} b {D}"
```

But in the case where there is whitespace we get:

```
"{VAR_SELECT, select, a {C} b {D}}"
```

So it looks like the post-process has not worked...

**Comment by petebacondarwin** [comment] 2020-10-12 18:25
In fact this message does not get a post-process instruction at all:

```ts
    var i18n_0;

    if (typeof ngI18nClosureMode !== "undefined" && ngI18nClosureMode) {
      const MSG_EXTERNAL_foo$$SRC_APP_APP_COMPONENT_TS_1 = goog.getMsg("{VAR_SELECT, select, a {A} b {B}}");
      i18n_0 = MSG_EXTERNAL_foo$$SRC_APP_APP_COMPONENT_TS_1;
    } else {
      i18n_0 = "{VAR_SELECT, select, a {C} b {D}}";
    }

    i18n_0 = _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵɵi18nPostprocess"](i18n_0, {
      "VAR_SELECT": "\uFFFD0\uFFFD"
    });
    var i18n_3;

    if (typeof ngI18nClosureMode !== "undefined" && ngI18nClosureMode) {
      const MSG_EXTERNAL_7353165759268544954$$SRC_APP_APP_COMPONENT_TS_4 = goog.getMsg("{VAR_SELECT, select, a {A} b {B}}");
      i18n_3 = MSG_EXTERNAL_7353165759268544954$$SRC_APP_APP_COMPONENT_TS_4;
    } else {
      i18n_3 = "{VAR_SELECT, select, a {A} b {B}}";
    }

    i18n_3 = _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵɵi18nPostprocess"](i18n_3, {
      "VAR_SELECT": "\uFFFD0\uFFFD"
    });
    var i18n_2;

    if (typeof ngI18nClosureMode !== "undefined" && ngI18nClosureMode) {
      const MSG_EXTERNAL_foo$$SRC_APP_APP_COMPONENT_TS_5 = goog.getMsg(" {$icu}\n", {
        "icu": i18n_3
      });
      i18n_2 = MSG_EXTERNAL_foo$$SRC_APP_APP_COMPONENT_TS_5;
    } else {
      i18n_2 = "{VAR_SELECT, select, a {C} b {D}}";
    }

    return [i18n_0, i18n_2];
```

**Comment by AndrewKushnir** [comment] 2020-10-13 00:54
I've performed additional investigation, see results below.

The part of code (generated code based on app's template) that causes the problem is:

```
    var i18n_2;
    if (typeof ngI18nClosureMode !== "undefined" && ngI18nClosureMode) {
      const MSG_EXTERNAL_foo = goog.getMsg(" {$icu}\n", {"icu": i18n_3});
      i18n_2 = MSG_EXTERNAL_foo;
    } else {
      i18n_2 = "{VAR_SELECT, select, a {C} b {D}}";
    }
    ...
    return [i18n_0, i18n_2];
```

As Pete mentioned, there is no `i18nPostprocess` function (that takes care of replacing the `VAR_SELECT` with corresponding binding id) there, however it look like it should not be there. Note that the Closure and $localize branches are different. In the Closure branch ICU is referred to via a placeholder when in $localize version the ICU is used as is.

Looking at the file with extracted translation (messages.xlf):

```
      <trans-unit id="foo" datatype="html">
        <source>{VAR_SELECT, select, a {A} b {B}}</source>
        <context-group purpose="location">
          <context context-type="sourcefile">src/app/app.component.html</context>
          <context context-type="linenumber">1</context>
        </context-group>
      </trans-unit>
      <trans-unit id="1e174d9d008a1608b8d1a8d0efbb593125ac6e1a" datatype="html">
        <source>{VAR_SELECT, select, a {A} b {B}}</source>
        <context-group purpose="location">
          <context context-type="sourcefile">src/app/app.component.html</context>
          <context context-type="linenumber">5,7</context>
        </context-group>
      </trans-unit>
```

The value of the `trans-unit > source` field looks incorrect, because it should contain a structure that would refer to an ICU as placeholder, i.e. something like this:

```
<trans-unit id="foo" datatype="html">
  <source>
    <x id="ICU" equiv-text="{bar, select, a {...} b {...}}"/>
  </source>
```

I believe the issue is that the message with the "@foo" was already processed by extraction mechanism when the following code (with *no* whitespaces) was examined:

```
<div i18n="@@foo">{bar, select, a {A} b {B}}</div>
```

and since the message with the `foo` id was already extracted, it does not generate it again. The result would be different if the order of the `<div>` elements in the template is changed (when ICU wrapped in whitespaces appears first).

So the root cause is that extracted messages might have same IDs (configured using `i18n="@@id"` syntax), but different content, thus triggering a problem when ICUs are not processed correctly. [We do have a logic in Ivy i18n extractor](https://github.com/angular/angular/blob/79620f5139c80f1b3b38168744ca99a224c7e5cd/packages/localize/src/tools/src/extract/main.ts#L89-L95) that handles a situation when messages with the same id but different text are present (and prints a warning if it detects such case). Once `ng xi18n` is switched to use Ivy for extraction by default (and the `duplicateMessageHandling` is exposed in Angular CLI), there should be an error message indicating such problems.

@pburkindine please update the template and assign a different message ID to an i18n block that has different formatting (or use the same formatting for both blocks).

**Comment by petebacondarwin** [comment] 2020-10-13 07:09
By the way the whitespace within the ICU expression is not at fault here. The extraction mechanism ignores such whitespace. The problem here is the whitespace before and after the ICU expression.

Changing the second message to be:

```
<div i18n="@@foo">{bar, select,
  a {A}
  b {B}}</div>
```

Results in only a single `foo` message being parsed from the file.

In the current example the two generated `$localize` tagged strings are (effectively stripping out the metadata):

```ts
i18n_0 = $localize `{VAR_SELECT, select, a {A} b {B}}`;
```

and

```ts
ICU = $localize `{VAR_SELECT, select, a {A} b {B}}`;
i18n_2 = $localize ` ${ICU}
`
```

Note that in the second string there is a space before the inner ICU and a carriage return after it.

Normally it doesn't matter what the actual content of the message text is when using custom identifiers (e.g. `@@foo`) since the extractor and translator will just use this as the marker and not concern itself about the content. But when there placeholders (e.g. ICUs or embedded HTML) then the ivy runtime needs to know about them be able to postprocess them.

**Comment by petebacondarwin** [comment] 2020-10-13 07:17
Finally it is worth noting that custom ids are not necessarily the best strategy, unless you have some legacy need for it.
A combination of the content of the message and the "meaning" metadata will generate unique identifiers for messages, which are resilient to this sort of thing. Removing the `@@foo` ids results in the following extracted message file:

```
<?xml version="1.0" encoding="UTF-8" ?>
<xliff version="1.2" xmlns="urn:oasis:names:tc:xliff:document:1.2">
  <file source-language="en-US" datatype="plaintext" original="ng2.template">
    <body>
      <trans-unit id="2197276418862391692" datatype="html">
        <source>{VAR_SELECT, select, a {A} b {B}}</source>
        <context-group purpose="location">
          <context context-type="sourcefile">src/app/app.component.html</context>
          <context context-type="linenumber">1</context>
        </context-group>
      </trans-unit>
      <trans-unit id="2380939390102386148" datatype="html">
        <source> <x id="ICU" equiv-text="{bar, select,
   a {A}
   b {B}}
"/>
</source>
        <context-group purpose="location">
          <context context-type="sourcefile">src/app/app.component.html</context>
          <context context-type="linenumber">5,8</context>
        </context-group>
      </trans-unit>
    </body>
  </file>
</xliff>
```

In this case there is only one ICU message to translate and the message with extra whitespace is clearly identifiable via (equiv-text removed):

```
<source> <x id="ICU" ... />
</source>
```

**Comment by petebacondarwin** [comment] 2020-10-25 10:34
I have created an issue on CLI project to implement the `duplicateMessageHandling` warnings: https://github.com/angular/angular-cli/issues/19207

**Comment by petebacondarwin** [comment] 2020-10-25 10:34
Closing here as I don't believe there is any action to be done on the framework side.

**Closed by petebacondarwin** 2020-10-25 10:34 UTC
Labels: P4, comp: i18n, fixed by Ivy, state: confirmed, workaround2: non-obvious
