### ISSUE TITLE
Components page bullet writed twice

### ISSUE THREAD

**Issue by isaquebock** [angular/angular#53694] opened 2023-12-24 22:14 UTC
### Describe the problem that you experienced

In topic `Every component must have:`

The bullet `A CSS selector that defines how the component is used in HTML` was write twice.

### Enter the URL of the topic with the problem

https://angular.dev/guide/components

**Comment by JoostK** [comment] 2023-12-24 22:34
Thanks for the report, this is a duplicate of #52575 for which the fix is pending deployment.

**Closed by JoostK** 2023-12-24 22:34 UTC
