### ISSUE TITLE
Angular 13 Universal (SSR) slow after migration from Angular 11

### ISSUE THREAD

**Issue by dirk-jacobs** [angular/angular#45398] opened 2022-03-20 11:19 UTC
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

Our Angular 11 Universal application had a first page loaded after 75ms

After upgrading to Angular 13, no other code changes, loading time is about 1.6s !!!

### Please provide a link to a minimal reproduction of the bug

https://test-help.pixenzo.com/

### Please provide the exception or error you saw

```true
-
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.2.4
Node: 14.15.5
Package Manager: npm 6.14.11
OS: win32 x64

Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1302.4 (cli-only)
@angular-devkit/core         13.2.4 (cli-only)
@angular-devkit/schematics   13.2.4 (cli-only)
@schematics/angular          13.2.4 (cli-only)
```

### Anything else?

**Link towards a version compiled with Angular 11**:
https://help.pixenzo.com/

**Link towards a version compiled with Angular 13**:
https://test-help.pixenzo.com/

**No other changes were made to the application !**

Deployed on Google Cloud / Kubernetes running on : node:14.15-alpine

Running locally on windows  (dev) it appears to be acceptable fast, but once deployed it is unacceptable slow.

I'm 100% sure it has to do with the compilation because running exact the same version on exact the same environment but compiled with Angular 11 is rather fast.

Please check the provided links to simulate the problem

**Timing with Angular 13**

![image](https://user-images.githubusercontent.com/63724492/159159955-46abe689-be28-414b-aa40-b2562782ba13.png)

**Timing with Angular 11**

![image](https://user-images.githubusercontent.com/63724492/159160003-dc24c6e8-9cc9-455c-b2a4-47d729189822.png)

**Comment by JoostK** [comment] 2022-03-20 11:29
Can you profile a server request to determine where time is being spent? Just the two pages loading slowly won't be sufficient for us to determine where the culprit may be.

**Comment by dirk-jacobs** [comment] 2022-03-20 11:30
Hi, 
thanks for the super-fast response.

What exactly do you mean by : 'profile a server request'. Any tools you had in mind ?

**Comment by JoostK** [comment] 2022-03-20 11:32
I am not too familiair with SSR deployments and how to profile things. Node can be started with `--cpu-prof` after which it will write `*.cpuprofile` files in batches, which should capture an incoming request as well.

**Comment by dirk-jacobs** [comment] 2022-03-20 11:38
ok, that's already something I can study and check.

Some extra information: We have currently 3 SSR applications.
If compiled with Angular 13 'pre-rendered', the result is also acceptable.
The problems are:
1. It's not normal that by changing the Angular version makes the application 10-20 times slower
2. Making an application ready for pre-rendering is not a walk in the parc. There are always some errors, sometimes in external libs popping up preventing from compiling in pre-render mode.


I was able to pre-render 1 of the 3 applications to have some acceptable results.

Thanks again for teh quick response and hope we find the root cause

**Comment by alan-agius4** [comment] 2022-03-20 17:49
@dirk-jacobs, unfortunately without a cpu profile there is not much we can investigate here, that said, I suspect it might be related to critical css inlining (https://github.com/angular/universal/issues/2106).

**Comment by dirk-jacobs** [comment] 2022-03-21 21:44
> @dirk-jacobs, unfortunately without a cpu profile there is not much we can investigate here, that said, I suspect it might be related to critical css inlining ([angular/universal#2106](https://github.com/angular/universal/issues/2106)).

Thanks @alan-agius4 this actually helped

in server.ts

```
server.engine('html', ngExpressEngine({
  inlineCriticalCss: false,
  bootstrap: AppServerModule,
}));
```

**Comment by alan-agius4** [comment] 2022-03-21 22:05
In that case closing as a duplicate of https://github.com/angular/universal/issues/2106

**Closed by alan-agius4** 2022-03-21 22:05 UTC
Labels: needs reproduction, comp: server
