### ISSUE TITLE
Preserve query params in redirectTo for absolute paths

### ISSUE THREAD

**Issue by calebegg** [angular/angular#28661] opened 2019-02-12 18:48 UTC
As discussed in #13315, query params are only preserved when redirecting if the path is relative. This is maddeningly subtle, and I can't imagine that it's an intentional feature. I think query params should always be preserved across redirectTo-based redirects, even those with absolute paths.

**Comment by FortinFred** [comment] 2019-02-25 20:58
It should also work for HashLocationStrategy

**Comment by jasonaden** [comment] 2019-04-09 23:14
I took a look into this recently and it appears to be a side effect of how this feature was implemented. I can't find any tests to confirm this was the intended behavior, so yes, I think it's a bug and should be fixed. Looks like it'll be some time during the RC period for Version 8.

**Comment by AdamModus** [comment] 2019-07-04 12:23
I'm facing this exact same issue while dealing with deeplinking in a big enterprise app.
Example: native side of the app wants to open a particular page and on the web side, we have our own deeplinking routing redirects so that both sides are not forced to always point to the same urls (easier to maintain this way).

Due to this though, it is not possible to preserve/merge the query params unless we hack and intercept the request and then **manually** add the queryParams ourselves. If this becomes an added feature, it would be greatly appreciated as our codebase would become a lot cleaner! 😄 

@jasonaden, not wanting to put pressure or anything, just looking for info. Since Angular 8 is already out (I can't update yet because the app is written in Ionic 4 and Angular is is not supported as of yet): has this been attended to?

**Comment by bluegrounds** [comment] 2020-04-19 18:44
The amount of issues that have been opened, and the comments discussing it, since 2016, is proof enough that this feature is badly needed by many, many people.

Is it difficult to implement such a feature?

**Comment by atscott** [comment] 2020-07-09 18:42
stackblitz repro, for completeness: https://stackblitz.com/edit/angular-ivy-router-base-zcbibf?file=src%2Fapp%2Fapp.component.html

**Closed** 2024-03-14 18:19 UTC
Labels: type: bug/fix, freq4: critical, area: router, state: confirmed, router: URL parsing/generation, router: config matching/activation/validation, router: navigation pipe, P3
