### ISSUE TITLE
[NGC] Error encountered resolving symbol values statically

### ISSUE THREAD

**Issue by gund** [angular/angular#13668] opened 2016-12-25 10:09 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
If you have generic class that used inside of Service exposed in @NgModule providers array NGC will fail with error:
```
ERROR in Error encountered resolving symbol values statically. Could not resolve type T (position X
 resolving symbol Y in D)
```

**Expected behavior**
Should compile without any problems.

**Minimal reproduction of the problem with instructions**
* Create simple app with `ng new` command
* Create some service and some generic class that one of methods of the service returns
* Run `ng build --aot` and watch it fails

Or just clone and run [this repo](https://github.com/gund/ngc-test).

**What is the motivation / use case for changing the behavior?**
This kind of code prevents entire application from AOT compilation

**Please tell us about your environment:**
Windows 10 x64
Node v6.9.2
TS 2.0.3

* **Angular version:** 2.3.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =   6.9.2

**Comment by gund** [comment] 2016-12-25 10:20
It will also fail even if I set explicitly which type should be used when `new` keyword is used.
See [this change](https://github.com/gund/ngc-test/commit/361eb5682b2b856457bcd0697d8c94c858a0a001).

**Comment by DzmitryShylovich** [comment] 2016-12-26 19:57
https://github.com/rangle/angular-2-aot-sandbox#service-with-generic-type-param-top

**Comment by gund** [comment] 2016-12-27 05:34
Hi @DzmitryShylovich, thanks for the reference.

However I should note that generic type parameter within constructor does work with AOT (as an example please see [ngrx/store](https://github.com/ngrx/store) library - the way you use it is injecting `Store<SomeStateInterface>`).

But here problem arises when I don't use generic class but the whole type is generic and I do not want to make generic `LoggerInContext` to be `Injectable` - in fact I want it to not to be that guy =)

And one more thing - I was able to pass AOT compilation if I split common parts of code for `LoggerService` and `LoggerInContext` into non injectable class `Logger` and extend each of them from that class so that `LoggerInContext` will not inherit `Injectable` metadata from `LoggerService` anymore.

So the way I currently see this issue is that AOT compiler looks for `@Injectable` annotation and tries to resolve constructor types for that class even when it's a subclass of the `Injectable` class (please correct me if I'm wrong).

Maybe it makes sense to have some sort of `@NonInjectable` annotation to tell compiler not to resolve constructor types for a class even if it's base class is `Injectable`?

Thanks

**Comment by tbosch** [comment] 2016-12-27 22:34
@gund As `TestInContextService<T> extends TestService`, and `TestService` has an `@Injectable`, we automatically make `TestInContextService` also injectable based on our inheritance rules for decorators.

And all `@Injectable` classes require non generic constructor arguments.

So this is a dupe of #11057, combined with inheritance.

**Closed by tbosch** 2016-12-27 22:34 UTC
Labels: comp: core & compiler

**Comment by gund** [comment] 2016-12-30 11:38
@tbosch yes I understand why compiler makes `TestInContextService` class `Injectable` but the thing is I do not need it to be `Injectable`. In fact all instantiating will happen in one of the methods in `TestService`.
So `TestInContextService` becomes sort of wrapper around `TestService` and controls how some of the methods are invoked in `TestService` however it should preserve all semantics of the original `TestService` that's why `extend`ing is necessary here but not DI capabilities.

That being said I was thinking about a way of telling NGC compiler to not assume some classes `Injectable`s even though they extend `Injectable` (please keep in mind that this will work without any problems in JIT mode so it is purely a NGC limitation).

It seems like it goes more to a feature request so considering all the above what do you think does it makes sense to create another issue as a feature request?
(I still think having something like `@NonInjectable` annotation would be great (: ).

So use case will be like this:
```ts
@Injectable()
class TestService { }

@NonInjectable()
class TestInContextService extends TestService { } // But no longer injectable and not provided anywhere
```

`NonInjectable` annotation might even do nothing because no action required for these case to work in runtime, so it can be just as a marker for compiler.
