### ISSUE TITLE
Creating ROUTES with custom factory function ends up with "Cannot read property 'loadChildren' of undefined" error

### ISSUE THREAD

**Issue by jtomaszewski** [angular/angular#22700] opened 2018-03-10 21:44 UTC
## I'm submitting a...

```
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  <!-- Please search GitHub for a similar issue or PR before submitting -->
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

## Current behavior

When angular compiler finds a provider that defines `ROUTES`, but which doesn't have a `useValue` property, (because it has f.e. `useFactory` property instead) it fails with the following error:

```
ERROR in TypeError: Cannot read property 'loadChildren' of undefined
    at _collectLoadChildren (/Users/jtomaszewski/src/recruitee/rails/admin_app/node_modules/@angular/compiler/bundles/compiler.umd.js:29034:20)
    at listLazyRoutes (/Users/jtomaszewski/src/recruitee/rails/admin_app/node_modules/@angular/compiler/bundles/compiler.umd.js:29009:49)
    at AotCompiler.listLazyRoutes (/Users/jtomaszewski/src/recruitee/rails/admin_app/node_modules/@angular/compiler/bundles/compiler.umd.js:31150:51)
    at AngularCompilerProgram.listLazyRoutes (/Users/jtomaszewski/src/recruitee/rails/admin_app/node_modules/@angular/compiler-cli/src/transformers/program.js:156:30)
    at AngularCompilerPlugin._listLazyRoutesFromProgram (/Users/jtomaszewski/src/recruitee/rails/admin_app/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:304:38)
    at Promise.resolve.then.then (/Users/jtomaszewski/src/recruitee/rails/admin_app/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:583:50)
    at process._tickCallback (internal/process/next_tick.js:109:7)
webpack: Failed to compile.
```

## Expected behavior

Defining a provider for `ROUTES` with other providers like f.e. `FactoryProvider` should just work.

## Minimal reproduction of the problem with instructions

1. Write your module like this:

```ts
import { NgModule, NgModuleFactory, Compiler } from '@angular/core';
import { Routes, RouterModule, ROUTES } from '@angular/router';

export function MainRoutingLazyRoutesFactory(compiler: Compiler): Routes {
  return [
    {
      path: 'dashboard',
      loadChildren: () => {
        return <any>System.import('../features/dashboard/dashboard.module')
          .then(({ DashboardFeatureModule }) => DashboardFeatureModule)
          .then(ngModule => {
            if (ngModule instanceof NgModuleFactory) {
              return ngModule;
            } else {
              return compiler.compileModuleAsync(ngModule);
            }
          });
      },
    },
  ];
}

@NgModule({
  imports: [RouterModule],
  exports: [RouterModule],
  providers: [
    {
      provide: ROUTES,
      multi: true,
      deps: [Compiler],
      useFactory: MainRoutingLazyRoutesFactory,
    },
  ],
})
export class MainRoutingModule {}
```

2. Try to compile it, in either JiT or AoT mode.

## What is the motivation / use case for changing the behavior?

It lets you to easily implement lazy loaded modules in your routes with your custom way.

## Environment

```
node 6.11.5
npm 5.6.0
angular 5.2.8
@ngtools/webpack 1.10.2
```

**Comment by jtomaszewski** [comment] 2018-03-10 21:46
I've followed through the stack trace and think I've found what causes the bug:

I think it's because of [this code](https://github.com/angular/angular/blob/c8a1a14b87e5907458e8e87021e47f9796cb3257/packages/compiler/src/aot/lazy_routes.ts#L28) in the angular/compiler's source:

```
function listLazyRoutes(moduleMeta, reflector) {
    var /** @type {?} */ allLazyRoutes = [];
    for (var _i = 0, _a = moduleMeta.transitiveModule.providers; _i < _a.length; _i++) {
        var _b = _a[_i], provider = _b.provider, module = _b.module;
        if (tokenReference(provider.token) === reflector.ROUTES) {
            var /** @type {?} */ loadChildren = _collectLoadChildren(provider.useValue);
            for (var _c = 0, loadChildren_1 = loadChildren; _c < loadChildren_1.length; _c++) {
                var route = loadChildren_1[_c];
                allLazyRoutes.push(parseLazyRoute(route, reflector, module.reference));
            }
        }
    }
    return allLazyRoutes;
}
```

According to the stacktrace, it fails on `_collectLoadChildren(provider.useValue);`.

Obviously, this provider has no `useValue`. IMHO we should skip parsing it, if it doesn't have such a property.

P.S. We've submitted this issue on angular-cli first ( https://github.com/angular/angular-cli/issues/9913 ) but they redirected us here.

**Comment by jasonaden** [comment] 2018-03-16 21:45
@jtomaszewski Thanks for the issue. I would like to help dig into this a little bit as it's something I think many people want. However, can you please provide a running example of your code? Both the working and not working version using [StackBlitz](http://stackblitz/com)?

**Comment by emanuelpinho** [comment] 2018-04-10 11:52
@jasonaden I am getting the same error but with a different case scenario. I don't know if this is related with angular or webpack cli.

My issue seems to be related with using an object initializer in a route object. Here an example code https://stackblitz.com/edit/angular-nxvknf. I am using a 'test' key inside app routes and seems like it is working using stackblitz.

When using webpack to compile, it is not working. It is calling _collectLoadChildren with provider.useValue, that is undefined in this case.
If i switch the data property to a string, it works.

Do you think that they could be related?

**Comment by jtomaszewski** [comment] 2018-04-14 12:42
@jasonaden Sure, here it is: https://stackblitz.com/edit/angular-db84dh .

Strangely it works okay in stackblitz, but don't let it mislead you. 

When you download the code on your computer and run `npm install && ng serve` manually, then it will return the error in the console:

![image](https://user-images.githubusercontent.com/1862580/38768304-fed1c882-3ff1-11e8-9caf-ee99dc79672e.png)

**Comment by tarekis** [comment] 2018-05-18 07:55
I am not quite sure if that is related to this exact issue, but this might just be an issue with anonymous functions in route objects, i found a solution on stackoverflow that worked for me, having a similar setup: https://stackoverflow.com/a/48205304/3880255.

Changing the anonymous functions to named functions fixed the error, i sadly have no insight on why tho, might be worth a try.

```
const routes: Routes = [
    ....
    {
        path: ':id',
        component: RegionCrudComponent,
        canDeactivate: [LeaveGuard],
        data: {
            staticRouteBreadcrumbName: 'Region',
            dynamicRouteComponent: RegionCrudComponent,
            dynamicRouteComponentModule: () => RegionModule
        }
    }
];

export const routing: ModuleWithProviders = RouterModule.forChild(routes);
```

```

export function getRegionModule() {
    return RegionModule;
}

const routes: Routes = [
    ...
    {
        path: ':id',
        component: RegionCrudComponent,
        canDeactivate: [LeaveGuard],
        data: {
            staticRouteBreadcrumbName: 'Region',
            dynamicRouteComponent: RegionCrudComponent,
            dynamicRouteComponentModule: getRegionModule
        }
    }
];

export const routing: ModuleWithProviders = RouterModule.forChild(routes);
```

**Comment by samherrmann** [comment] 2018-06-06 16:59
I experienced the same behavior as @DominikDitoIvosevic . I was able to solve the issue, i.e. make it not fail on `ng serve` by exporting my factoring function. Below is my simplified setup (No lazy loading involved).

my-routing.module.ts:
```
const routes: Routes = [
  createRoute('my-path', MyComponent)
];

@NgModule({
  imports: [
    RouterModule.forChild(routes)
  ]
})
export class MyRoutingModule { }

// Removing export throws "ERROR in Cannot read property 'loadChildren' of undefined"
export function createRoute<T>(path: string, component: Type<T>): Route {
  return {
    path: path,
    component: component
  };
}
```

**Comment by mjamin** [comment] 2018-07-11 10:13
I also ran into this issue and came to the same conclusion as @jtomaszewski that [this](https://github.com/angular/angular/blob/master/packages/compiler/src/aot/lazy_routes.ts#L28) is the culprit.

I was about to create an issue with this repro: https://github.com/mjamin/lazy-loaded-routes

It seems that providing lazy loaded routes via anything other than `useValue` is currently not supported, atleast in a webpack setup.

[This](https://github.com/mjamin/lazy-loaded-routes/blob/master/src/app/feature/feature.module.ts#L17) is triggering the `Cannot read property 'loadChildren' of undefined` error.

Notes:
- When using `ng serve` the error disappears after the first incremental compilation following the initial one. The lazy loaded module is somehow picked up from then on.
- Using `ng serve --prod` will trigger the error even on incremental builds.
- [On Stackblitz](https://stackblitz.com/edit/angular-e2vdxr?file=src%2Fapp%2Ffeature%2Ffeature.module.ts) I'm unable to reproduce the error:

**Comment by mjamin** [comment] 2018-07-11 12:09
After a little more digging I found [this](https://github.com/angular/angular/pull/15334) where @fulls1z3 tried to provide a fix. See the discussion there for more info.

**Comment by DKIMN** [comment] 2019-01-15 12:48
Same problem, but the fix for me was:
{
      provide: ROUTES,
      multi: true,
      deps: [ModuleLoaderService, Compiler],
      useValue: {}, // Can't compile when not defined
      useFactory: LazyRoutesFactory
 }

**Comment by DominikDitoIvosevic** [comment] 2019-01-15 14:24
For me a quick fix was to simply switch to the new Ivy renderer and for one reason or another that was enough. Set the flag useIvy: true in the angular config (not sure where to set it, sending from my phone)

**Comment by ildoc** [comment] 2019-03-28 11:28
I'm experiencing the same error even after enabling ivy.

Also, as @DominikDitoIvosevic said, the error shows up consistently only on the first iteration `ng serve` building

**Comment by rynqu** [comment] 2019-05-10 06:37
@samherrmann Your comment was super helpful for me! Indeed my problem disappeared after I added the export statement on the function building the sub routes (the makeRoutes function). This is how it looks like for me:
`
export function makeRoutes(homeComponent: Type<any>): Routes {
    return [
        {
            path: '',
            component: homeComponent
        },
        {
            path: 'blog',
            loadChildren: './modules/blog/blog.module#BlogModule'
        },
        {
            path: 'shop',
            loadChildren: './modules/shop/shop.module#ShopModule'
        },
        {
            path: 'account',
            loadChildren: './modules/account/account.module#AccountModule'
        },
        {
            path: 'site',
            loadChildren: './modules/site/site.module#SiteModule'
        },
        {
            path: '**',
            component: PageNotFoundComponent
        }
    ];
}

const routes: Routes = [
    {
        path: '',
        pathMatch: 'full',
        redirectTo: 'pl'
    },
    {
        path: 'pl',
        component: RootComponent,
        data: {
            headerLayout: 'classic'
        },
        children: makeRoutes(PageHomeOneComponent)
    },
    {
        path: 'en',
        component: RootComponent,
        data: {
            headerLayout: 'classic'
        },
        children: makeRoutes(PageHomeOneComponent)
    },
    {
        path: '**',
        redirectTo: 'pl'
    }
];

@NgModule({
    imports: [RouterModule.forRoot(routes, {
        scrollPositionRestoration: 'enabled',
        anchorScrolling: 'enabled'
    })],
    exports: [RouterModule]
})
`

**Comment by danbilokha** [comment] 2019-07-24 12:11
@samherrmann I have your corner case. 

```
const routes: Routes = [
 *someBasicRoutes*
  ...createRoute(APIs, Components)
];

@NgModule({
  imports: [
    RouterModule.forChild(routes)
  ]
})
export class MyRoutingModule { }

// Removing export throws "ERROR in Cannot read property 'loadChildren' of undefined"
export function createRoute<T>(APIs: Array<api>, components: Type<T>): Route {
  return APIs.map(api => {
    path: path,
    component: component
  });
}
```

Which isn't resolving the loadChildren null \ undefined error. I have found no other way rather than using 

`
router.reserConfig(someBasicRoutes.concat(createRoute(APIs, Components))
`

Maybe someone will have a solution here or it could be useful.

**Comment by pkarny** [comment] 2019-07-26 10:36
@danbilokha I found a possible workaround for you. It's still not a fix, but I feel that is the most clean solution for that.

Instead of defining routes during const declaration 
```
const routes: Routes = [
  ...createRoutesFunc(some, params),
  {
    path: 'static-route',
    component: ComponentForStaticRoute,
  },
  differentFunctionForRouteCreation(params)
];

@NgModule({
  imports: [
    RouterModule.forRoot(routes)
  ]
})
export class MyRoutingModule { }
```

`.push` all the values just after declaration. It looks almost the same and the routes are in your desired order.
 
```
const routes: Routes = [];

routes.push(
  ...createRoutesFunc(some, params),
  {
    path: 'static-route',
    component: ComponentForStaticRoute,
  },
  differentFunctionForRouteCreation(params)
);

@NgModule({
  imports: [
    RouterModule.forRoot(routes)
  ]
})
export class MyRoutingModule { }
```

I was previously thinking that it's something related to the `spread` operator, but debugging gave me nothing. I have also tried exporting of those factory functions but this did not work, either. Anyway this issue needs to be fixed because it's very confusing to deal with.

**Comment by lin-hun** [comment] 2019-09-05 09:11
ivy fix the bug.

**Comment by arkadiusz-skubala** [comment] 2020-01-21 13:07
As @DominikDitoIvosevic mentioned, for me it was failing on the first 

> ng serve

but doing just a simple change in code, anywhere, and saving fixed the issue. Sadly it was further failing on Jenkins.

**Solution in my case was ridiculous:**
It was specifically related to a feature module routing module which was lazy loaded.

This was failing:

```
let routes: Routes;
routes = [
  {
    path: "my-custom-route",
    component: LayoutComponent,
    children: [
      { path: "", component: MyComponent }
    ],
    data: {
      title: "Some title"
    }
  }
];
```

This was working:

```
let routes: Routes = [
  {
    path: "my-custom-route",
    component: LayoutComponent,
    children: [
      { path: "", component: MyComponent }
    ],
    data: {
      title: "Some title"
    }
  }
];
```
Ridiculous, but if this helps someone...

**Comment by shripatki** [comment] 2020-04-20 18:32
I am facing same issue but unable to resolve with the given solution. I am using below configuration

- angular 8.3
- node 10.15
 please help me for this issue

**Comment by lincolnthree** [comment] 2020-05-27 16:08
I can also get this to fail in Angular 9 and 10 with the simple configuration anywhere in app-routing.module.ts:

```
          {
            path: 'login', loadChildren: () => import('./pages/login/login.module').then(m => m.LoginPageModule),
            canActivate: [AccessRequiredGuard], data: {
              ['AccessRequiredGuard']: {
                allowedRoles: ['anonymous'],
                failureRoute: ['/'],
                silent: true
              }
            }
          },
```

However, this works fine:
```
          {
            path: 'login', loadChildren: () => import('./pages/login/login.module').then(m => m.LoginPageModule),
            canActivate: [AccessRequiredGuard], data: {
              'AccessRequiredGuard': {
                allowedRoles: ['anonymous'],
                failureRoute: ['/'],
                silent: true
              }
            }
          },
```

Note the change from `['AccessRequiredGuard']` to `'AccessRequiredGuard'`.

This is the same if a variable is used to index the property, like this:

```

              [AccessRequiredGuard.DATA_KEY]: {
                allowedRoles: ['anonymous'],
                failureRoute: ['/'],
                silent: true
              }
```

**Comment by JoostK** [comment] 2021-09-30 20:46
This was a ViewEngine bug and `listLazyRoutes` was removed in #43591.

**Closed by JoostK** 2021-09-30 20:46 UTC
Labels: type: bug/fix, freq1: low, comp: core, fixed by Ivy, P5, needs clarification
