### ISSUE TITLE
Support discriminated unions for ngSwitch

### ISSUE THREAD

**Issue by pauldraper** [angular/angular#40768] opened 2021-02-09 22:00 UTC
# 🚀 feature request

### Relevant Package

@angular/core

@angular/common

### Description

I'd like to use discriminated unions in Angular templates.

https://www.bennadel.com/blog/3696-discriminated-unions-dont-seem-to-work-in-angular-9-0-0-next-5-when-fulltemplatetypecheck-is-enabled.htm

### Describe the solution you'd like

ngSwitch/ngSwitchCase works like switch-case in TS and TSX

### Describe alternatives you've considered

$any, $any, $any
Must be funny
In the typed man's world
$any, $any, $any
Always sunny
In the typed man's world
Aha aha
All the things I could do
If I had a little $any
It's a typed man's world
It's a typed man's world

**Comment by AndrewKushnir** [comment] 2021-02-10 19:16
@pauldraper thanks for the proposed improvement. It looks like this ticket is a duplicate of #34522, so I'm closing this one in favor of #34522.

**Closed by AndrewKushnir** 2021-02-10 19:16 UTC
Labels: comp: common, comp: core, cross-cutting: types, feature
