### ISSUE TITLE
Reactive form inputs not in sync

### ISSUE THREAD

**Issue by mbeckenbach** [angular/angular#26631] opened 2018-10-21 06:45 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
When 2 inputs are both connected to the same reactive form control their values are not synchronized when typing. The form control value updates as it should. When setting the value through .setValue() both inputs update their value. But when typing the second input does not know about that change.

## Expected behavior
Both inputs should stay in sync

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-gitter-7mqyxl

## What is the motivation / use case for changing the behavior?
When an input is displayed twice (maybe on 2 tabs inside of a tab control) the values should stay in sync. 

## Environment

<pre><code>
Angular version: 6.x and 7

Browser:
- [x] Chrome (desktop) version 70
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.11
- Platform:  Mac
Others:
</code></pre>

**Comment by trotyl** [comment] 2018-10-21 09:34
Duplicate of https://github.com/angular/angular/issues/10036

**Comment by kara** [comment] 2018-11-21 00:00
Closing as dupe

**Closed by kara** 2018-11-21 00:00 UTC
Labels: comp: forms
