### ISSUE TITLE
Property table is wider than its container

### ISSUE THREAD

**Issue by dangrussell** [angular/angular#46153] opened 2022-05-26 13:41 UTC
### Description

The table under Options on https://angular.io/cli/build is wider than its container (the `<main>` element with `sidenav-content` class) which is limited by a max-width of 50em (800px).

This causes the content in the table to be hidden / cut off.

### What is the affected URL?

https://angular.io/cli/build

### Please provide a screenshot if possible

https://i.imgur.com/XVpu3vx.png

**Comment by gkalpak** [comment] 2022-05-26 16:01
Thx for reporting this, @dangrussell :+1:
That's indeed not great.

I am going to close this as a duplicate of #42789. If you have any suggestions about how to address this, please post it there.

**Closed by gkalpak** 2022-05-26 16:01 UTC
Labels: comp: docs
