### ISSUE TITLE
Wrong link to NgComponentOutlet API

### ISSUE THREAD

**Issue by HymanZHAN** [angular/angular#53275] opened 2023-11-30 07:52 UTC
### Describe the problem that you experienced

Wrong link:

> See the [NgComponentOutlet API reference](https://angular.dev/api/core/NgComponentOutlet) for more information on the directive's capabilities.

Should be:

> See the [NgComponentOutlet API reference](https://angular.dev/api/common/NgComponentOutlet) for more information on the directive's capabilities.

### Enter the URL of the topic with the problem

https://angular.dev/guide/components/programmatic-rendering#using-ngcomponentoutlet

**Comment by srinathsree66** [comment] 2023-12-01 05:16
Hi, this this was addressed in #52829

**Comment by sasidharansd** [comment] 2023-12-12 19:30
Hi @JoostK, think we can close this one as it is a duplicate of https://github.com/angular/angular/issues/52828 and it is completed.

**Comment by JoostK** [comment] 2023-12-12 19:34
@sasidharansd Thanks!

**Closed by JoostK** 2023-12-12 19:34 UTC
Labels: state: blocked, help wanted, good first issue, P3, area: adev
