### ISSUE TITLE
ng update to Angular 8 fails: Cannot read property 'module' of undefined

### ISSUE THREAD

**Issue by darkbasic** [angular/angular#30356] opened 2019-05-04 14:31 UTC
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description

```
$ ng update @angular/core --from 7 --to 8 --migrate-only
            ------ Static Query migration ------
            In preparation for Ivy, developers can now explicitly specify the
            timing of their queries. Read more about this here:
            https://github.com/angular/angular/pull/28810
            
            There are two available migration strategies that can be selected:
              • Template strategy  -  migration tool (short-term gains, rare corrections)
              • Usage strategy  -  best practices (long-term gains, manual corrections)
            For an easy migration, the template strategy is recommended. The usage
            strategy can be used for best practices and a code base that will be more
            flexible to changes going forward.
? What migration strategy do you want to use? Template strategy
            
Cannot read property 'module' of undefined
```

```
$ ng update @angular/core --from 7 --to 8 --migrate-only
            ------ Static Query migration ------
            In preparation for Ivy, developers can now explicitly specify the
            timing of their queries. Read more about this here:
            https://github.com/angular/angular/pull/28810
            
            There are two available migration strategies that can be selected:
              • Template strategy  -  migration tool (short-term gains, rare corrections)
              • Usage strategy  -  best practices (long-term gains, manual corrections)
            For an easy migration, the template strategy is recommended. The usage
            strategy can be used for best practices and a code base that will be more
            flexible to changes going forward.
? What migration strategy do you want to use? Usage strategy
            
Cannot read property 'kind' of undefined
```

## 🔥 Exception or Error
<pre><code>
Template strategy:
Cannot read property 'module' of undefined

Usage strategy:
Cannot read property 'kind' of undefined
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 8.0.0-rc.2
Node: 10.15.3
OS: linux x64
Angular: 8.0.0-rc.2
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router

Package                                    Version
--------------------------------------------------------------------
@angular-devkit/architect                  0.800.0-rc.2
@angular-devkit/build-angular              0.800.0-rc.2
@angular-devkit/build-ng-packagr           0.800.0-rc.2
@angular-devkit/build-optimizer            0.800.0-rc.2
@angular-devkit/build-webpack              0.800.0-rc.2
@angular-devkit/core                       8.0.0-rc.2
@angular-devkit/schematics                 8.0.0-rc.2
@angular/cdk                               8.0.0-rc.0
@angular/flex-layout                       7.0.0-beta.24
@angular/http                              8.0.0-beta.10+1.sha-a28b3e3
@angular/material                          8.0.0-rc.0
@ngtools/json-schema                       1.1.0
@ngtools/webpack                           8.0.0-rc.2
@nguniversal/express-engine                v7.0.2
@nguniversal/module-map-ngfactory-loader   v7.0.2
@schematics/angular                        8.0.0-rc.2
@schematics/update                         0.800.0-rc.2
ng-packagr                                 5.1.0
rxjs                                       6.5.1
typescript                                 3.4.5
webpack                                    4.30.0
</code></pre>

Note: `flex-layout` still doesn't support Angular 8: https://github.com/angular/flex-layout/issues/1029
Maybe it is related to it?

I tried to install a local copy of `@angular/cli` in order to debug it, but I didn't succeed.
Despite `yarn link`ing all of the following
```
@angular-devkit/core
@angular-devkit/schematics
@schematics/angular
@schematics/update
@angular-devkit/architect
@angular-devkit/build-optimizer
@angular-devkit/build-webpack
@ngtools/webpack
@angular-devkit/build-angular
@angular-devkit/build-ng-packagr
```

I still get:
```
$ ./node_modules/.bin/ng --version            
internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module '../lib/init'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/niko/WebstormProjects/deps/angular-cli/packages/angular/cli/bin/ng:25:1)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
```

**Comment by devversion** [comment] 2019-05-10 07:42
Fixes landed for the `_updateContext` and a better messaging when the AOT compiler fails for the template strategy. I'll do some manual testing again, but I'm pretty sure the template strategy failure is caused by having a tsconfig with `angularCompilerOptions` > `flatModuleX` options set.

**Closed** 2019-07-02 21:18 UTC
Labels: comp: ivy
