### ISSUE TITLE
Error using `@angular/common/http` and `@angular/router`

### ISSUE THREAD

**Issue by brunoromeiro** [angular/angular#47291] opened 2022-08-29 20:44 UTC
### Which @angular/* package(s) are the source of the bug?

common, router

### Is this a regression?

Yes

### Description

Since version 14.2.0 we are having problems with testing our component library.
Our tests can no longer find the services using configureTestSuit as shown in the example:
```typescript
configureTestSuite(() => {
    TestBed.configureTestingModule({
      imports: [HttpClientTestingModule],
      ...
    });
  });
```

Our component [library](https://po-ui.io/) is always updated, as a new version of Angular comes out, and we noticed this today when we were going to generate a new package we noticed the errors, and we did a regression test and we saw that in the previous version 14.1.3 the error did not happen.

### Please provide the exception or error you saw

```true
NullInjectorError: R3InjectorError(DynamicTestModule)[ActivatedRoute -> ActivatedRoute]:
          NullInjectorError: No provider for ActivatedRoute!
        error properties: Object({ ngTempTokenPath: null, ngTokenPath: [ 'ActivatedRoute', 'ActivatedRoute' ] })
        NullInjectorError: R3InjectorError(DynamicTestModule)[ActivatedRoute -> ActivatedRoute]:
          NullInjectorError: No provider for ActivatedRoute!

============================== AND ==============================

NullInjectorError: R3InjectorError(DynamicTestModule)[HttpClient -> HttpClient]:
          NullInjectorError: No provider for HttpClient!
        error properties: Object({ ngTempTokenPath: null, ngTokenPath: [ 'HttpClient', 'HttpClient' ] })
        NullInjectorError: R3InjectorError(DynamicTestModule)[HttpClient -> HttpClient]:
          NullInjectorError: No provider for HttpClient!
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 14.2.1
Node: 16.16.0
Package Manager: npm 8.15.1
OS: win32 x64

Angular: 14.2.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1402.1
@angular-devkit/build-angular   14.2.1
@angular-devkit/core            13.3.9
@angular-devkit/schematics      13.3.9
@angular/cli                    14.2.1
@schematics/angular             13.3.9
ng-packagr                      14.2.0
rxjs                            7.5.6
typescript                      4.8.2
```

**Comment by JoostK** [comment] 2022-08-30 06:33
Could you please provide a minimal reproduction of the issue you're seeing?

**Comment by brunoromeiro** [comment] 2022-09-01 17:20
The problem occurs when I need to use the HttpClient within a unit test. Even using the HttpClientTestingModule, my tests can't find it and it ends up breaking in at least 200 tests out of the 6000 we have.

I'll put an example of how we are creating the test instance and the return in the terminal I added in the opening of the issue.

Example:

```typescript
      TestBed.configureTestingModule({
        imports: [PoModalModule, HttpClientTestingModule, PoDynamicModule, RouterTestingModule],
        declarations: [PoLookupModalComponent],
        providers: [LookupFilterService, PoComponentInjectorService],
        schemas: [NO_ERRORS_SCHEMA]
      }).compileComponents();
```


And when I run karma it gives me these errors here


```bash
NullInjectorError: R3InjectorError(DynamicTestModule)[ActivatedRoute -> ActivatedRoute]:
          NullInjectorError: No provider for ActivatedRoute!
        error properties: Object({ ngTempTokenPath: null, ngTokenPath: [ 'ActivatedRoute', 'ActivatedRoute' ] })
        NullInjectorError: R3InjectorError(DynamicTestModule)[ActivatedRoute -> ActivatedRoute]:
          NullInjectorError: No provider for ActivatedRoute!

============================== AND ==============================

NullInjectorError: R3InjectorError(DynamicTestModule)[HttpClient -> HttpClient]:
          NullInjectorError: No provider for HttpClient!
        error properties: Object({ ngTempTokenPath: null, ngTokenPath: [ 'HttpClient', 'HttpClient' ] })
        NullInjectorError: R3InjectorError(DynamicTestModule)[HttpClient -> HttpClient]:
          NullInjectorError: No provider for HttpClient!
```


It helps?

**Comment by JoostK** [comment] 2022-09-01 17:49
Please share a runnable repo; just snippets don't nearly tell the whole picture necessary for analyzing this issue.

**Comment by brunoromeiro** [comment] 2022-09-02 12:29
Beauty! I will pass the repository of our component library: https://github.com/po-ui/po-angular/tree/v14.3.0

In this release we are letting angular update the version minor and patch. Angular needs to be at version 14.2.1

Just run `npm run test:ui`

**Comment by JoostK** [comment] 2022-09-05 07:20
That repro is _huge_ and it's not feasible for me to dissect the whole codebase to figure out where to start, especially because there are 1443 failing tests instead of just a single one.

**Comment by brunoromeiro** [comment] 2022-09-06 20:35
Hi @JoostK That and all tests are breaking because they are not finding the import from HttpClientTestingModule and RouterTestingModule.
And it was impossible to update the Angular version, I don't know if something was deprecated or changed the way these guys are used.

**Comment by brunoromeiro** [comment] 2022-09-06 20:53
I'm going to create a simple application using the imports we made within this project and I'll put it here.

**Comment by atscott** [comment] 2022-09-19 16:24
I'm going to close this since it's not actionable for us in the current state. Please open a new issue when you have a reproduction that we can use.

**Closed by atscott** 2022-09-19 16:24 UTC
Labels: comp: common, needs reproduction, comp: router
