### ISSUE TITLE
ng-container: need warning when ng-template variable matches component variable

### ISSUE THREAD

**Issue by jzabinski** [angular/angular#29567] opened 2019-03-28 15:36 UTC
# 🚀 feature request

### Relevant Package
@angular/core, I think. Wherever the structural directives live.

### Description
If a component variable and an ng-template variable use the same name and are used within the same ng-template section, then the ng-template variable will always be used. We need to indicate this behavior to the user.

### Describe the solution you'd like
It would be great if we could get a warning in this situation.

### Describe alternatives you've considered
Using unique names for the variables resolves the situation.

See [this Stackblitz example](https://stackblitz.com/edit/angular-zubvg7?file=src%2Fapp%2Fhello.component.ts). The important code is as follows:
<pre>@Component({`
  selector: 'hello',
  template: `
  &lt;ng-container&gt; *ngIf='<i>name</i>;then <b>name</b> else donthandlename' &lt;/ng-container&gt;
  &lt;ng-template #<b>name</b>&gt; Hello {{ name }} &lt;/ng-template&gt;
  &lt;ng-template #donthandlename&gt; Hello unknown person &lt;/ng-template&gt;
  `,
  styles: [`h1 { font-family: Lato; }`]
})
export class HelloComponent  {
  @Input() <i>name</i>: string;
}</pre>

The basic idea is to use one template if the class's input variable 'name' has been given to the component, and to use a different template if 'name' is not defined. When we get to 'Hello {{ name }}', the definition of 'name' seems ambiguous: it could refer to the component's input variable, or it could refer to the TemplateRef being used in the enclosing template:
<pre>&lt;ng-template #name&gt;</pre>

As it turns out, Angular uses the TemplateRef from ng-template, not the input variable. By itself, that isn't necessarily broken, but it would be great if 'name' in 'Hello {{ name }}' was underlined in red in order to highlight the ambiguity. (I'm using Visual Studio Code, by the way.)

**Comment by pkozlowski-opensource** [comment] 2019-03-28 15:53
Yeh, we had it reported previously in #28632 (slightly different scenario but the principle is the same).

Basically local vars (`#foo`) will "shadow" (take precedence) over properties defined on the component instance.

**Comment by Airblader** [comment] 2019-03-28 17:08
Shouldn't we make this an error instead? I doubt there's a good reason to want to shadow, abodijg it is easy and there's a clear user benefit.

**Comment by alxhub** [comment] 2019-04-09 22:30
I'm with @Airblader. I think it's too hard to look at a template and infer which identifier refers to which variable/reference.

**Comment by jzabinski** [comment] 2021-06-04 15:09
cc @JamesHenry

As pointed out by @pkozlowski-opensource, this is essentially an issue of template variables shadowing component variables. In other parts of Angular projects, this is normally highlighted through linting.

Is Angular still in the linting game? Or would this be better addressed through @angular-eslint?

**Comment by JamesHenry** [comment] 2021-06-04 16:54
Linting a single concept across these separate concerns (TypeScript sources and Angular Templates) is not really a thing. The best place for this based on current tooling would be the Angular compiler I think.

**Comment by JamesHenry** [comment] 2021-06-04 16:55
Any linting capabilities in this domain would have to be built on top of the angular compiler for this very reason

**Comment by JoostK** [comment] 2022-05-27 20:43
Closing this one in favor of #29567

**Closed by JoostK** 2022-05-27 20:43 UTC
Labels: feature, hotlist: error messages, comp: core, core: local references, insufficient votes, votes required

**Comment by pkozlowski-opensource** [comment] 2022-05-27 22:02
> Closing this one in favor of https://github.com/angular/angular/issues/29567

@JoostK closing as a duplicate of itself?

**Comment by JoostK** [comment] 2022-05-27 22:15
> > Closing this one in favor of https://github.com/angular/angular/issues/29567
> 
> 
> 
> @JoostK closing as a duplicate of itself?

Oops, copying numbers is hard. It should be #45227.
