### ISSUE TITLE
Function calls are not supported in decorators but 'ɵmakeDecorator' was called in 'Injectable'

### ISSUE THREAD

**Issue by ovione** [angular/angular#32694] opened 2019-09-16 08:34 UTC
# 🐞 bug report

### Is this a regression?
Yes, the previous version in which this bug was not present was: 6
I upraded my project to version 8

### Description

I build for production and I got the error.

Globally I have @angular/cli@7.3.5 but locally I have angular/cli": "8.3.3",
I guess the local angular cli is used.
My project uses libraries that I build with angular 6.1.0

## 🔬 Minimal Reproduction

ng build --prod

## 🔥 Exception or Error
<pre><code>
ERROR in Error during template compile of 'PlatformRef'
  Function calls are not supported in decorators but 'ɵmakeDecorator' was called in 'Injectable'
    'Injectable' calls 'ɵmakeDecorator'.

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.3.4
Node: 10.14.2
OS: win32 x64
Angular: 8.2.6
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.4
@angular-devkit/build-angular     0.803.4
@angular-devkit/build-optimizer   0.803.4
@angular-devkit/build-webpack     0.803.4
@angular-devkit/core              8.3.4
@angular-devkit/schematics        8.3.4
@angular/cli                      8.3.4
@ngtools/webpack                  8.3.4
@schematics/angular               8.3.4
@schematics/update                0.803.4
rxjs                              6.5.3
typescript                        3.5.3
webpack                           4.39.2

</code></pre>

**Anything else relevant?**
this is my package.json

<pre><code>
 "dependencies": {
   "dependencies": {
    "@angular/animations": "8.2.6",
    "@angular/common": "8.2.6",
    "@angular/compiler": "8.2.6",
    "@angular/core": "8.2.6",
    "@angular/forms": "8.2.6",
    "@angular/platform-browser": "8.2.6",
    "@angular/platform-browser-dynamic": "8.2.6",
    "@angular/router": "8.2.6",
    "@ngx-translate/core": "10.0.2",
    "@ngx-translate/http-loader": "3.0.1",
    "bootstrap": "^4.3.1",
    "core-js": "2.5.7",
    "font-awesome": "4.7.0",
    "jquery": "3.3.1",
    "json-server": "0.14.2",
    "moment": "2.22.2",
    "moment-timezone": "0.5.21",
    "ngx-bootstrap": "3.0.1",
    "ngx-cookie": "4.0.2",
    "ngx-webstorage": "2.0.1",
    "rxjs": "6.5.3",
    "tslib": "^1.10.0",
    "web-animations-js": "^2.3.2",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.803.4",
    "@angular/cli": "~8.3.4",
    "@angular/compiler-cli": "^8.2.6",
    "@angular/language-service": "^8.2.6",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/moment-timezone": "0.5.9",
    "@types/node": "~8.9.4",
    "codelyzer": "^5.0.1",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~3.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "~3.5.3"
  }
</code></pre>

**Comment by ovione** [comment] 2019-09-17 10:57
For my project I found the solution:

In my project in angular 6 I had:

<pre><code>
import { ParamMap } from "@angular/router/src/shared";

this.route.queryParamMap.subscribe((paramMap: ParamMap) => {
</code></pre>

When I migrated to angular 8 this code I had to:

<pre><code>
this.route.queryParamMap.subscribe((paramMap) => {
</code></pre>

PS: note that I deleted the ParamMap everywhere.

**Comment by alxhub** [comment] 2019-10-08 22:25
Hello @ovione,

Unfortunately we won't be able to investigate this issue without a minimal reproduction, including the code (preferably a link to a Github repo) which causes the issue.

Thanks,
Alex

**Comment by nmanthena18** [comment] 2019-10-29 18:13
I am also facing same issue. anybody got the solutions for it?.

**Comment by zwietabak** [comment] 2019-12-06 18:45
Same here like @nmanthena18 after upgrading from angular 7 to 8...

**Comment by lan-dry** [comment] 2019-12-09 10:37
Hi please I ma getting the same issue after migrating from angular 6 to 8:
Error during template compile of 'Injectable'
  Function calls are not supported in decorators but 'ɵmakeDecorator' was called.
...
May someone help me please?

**Comment by vagnersabadi** [comment] 2019-12-12 01:43
Angular 7 for 8

```sh
> ng.cmd run app:build:production

ERROR in Error during template compile of 'NgModule'
  Function calls are not supported in decorators but 'ɵmakeDecorator' was called.
Error during template compile of 'Directive'
  Function calls are not supported in decorators but 'ɵmakeDecorator' was called.
Error during template compile of 'Directive'
  Function calls are not supported in decorators but 'ɵmakeDecorator' was called.
Error during template compile of 'Injectable'
  Function calls are not supported in decorators but 'ɵmakeDecorator' was called.
Error during template compile of 'Injectable'
  Function calls are not supported in decorators but 'ɵmakeDecorator' was called.
Error during template compile of 'Injectable'
Error during template compile of 'Injectable'
  Function calls are not supported in decorators but 'ɵmakeDecorator' was called.
Error during template compile of 'Injectable'
  Function calls are not supported in decorators but 'ɵmakeDecorator' was called.
Error during template compile of 'Injectable'
  Function calls are not supported in decorators but 'ɵmakeDecorator' was called.
Error during template compile of 'Injectable'
  Function calls are not supported in decorators but 'ɵmakeDecorator' was called.
Error during template compile of 'NgModule'
  Function calls are not supported in decorators but 'ɵmakeDecorator' was called.
Error during template compile of 'Injectable'
  Function calls are not supported in decorators but 'ɵmakeDecorator' was called.

[ERROR] An error occurred while running subprocess ng.

        ng.cmd run app:build:production exited with exit code 1.
```

**Comment by AntonyJos** [comment] 2019-12-16 12:21
![Angular issue](https://user-images.githubusercontent.com/42953694/70906415-52525a00-202c-11ea-846c-40ecdf6296b4.PNG)

receiving the above set of errors on upgrading the project from Angular 5 to Angular 8 for Prod build

@alxhub / @AndrewKushnir , Any update on this issue?

**Comment by Sanketjo** [comment] 2020-01-13 12:17
Same issue I am facing , Any help will definitely appreciated

**Comment by dovoosh** [comment] 2020-01-13 15:49
Same issue.
I noticed that I get the error when aot set to true in angular.json

**Comment by akshaykmr080** [comment] 2020-01-14 23:23
Any update regarding this issue?

**Comment by davidemess** [comment] 2020-01-16 09:18
```
"compilerOptions": {
    "paths": {
        "@angular/*": [ "node_modules/@angular/*"]
    }
  }
```

Adding this to tsconfig.json worked for me

Look at #9576 issue too

**Comment by Hank1370** [comment] 2020-02-02 07:53
> ```
> "compilerOptions": {
>     "paths": {
>         "@angular/*": [ "node_modules/@angular/*"]
>     }
>   }
> ```
> 
> Adding this to tsconfig.json worked for me
> 
> Look at #9576 issue too

this worked for me

**Comment by cefamax** [comment] 2020-02-05 11:30
this worked for me too; but why?

**Comment by jasmeetappinventiv** [comment] 2020-03-13 11:17
> ![Angular issue](https://user-images.githubusercontent.com/42953694/70906415-52525a00-202c-11ea-846c-40ecdf6296b4.PNG)
> 
> receiving the above set of errors on upgrading the project from Angular 5 to Angular 8 for Prod build
> 
> @alxhub / @AndrewKushnir , Any update on this issue?

did you found any solution?

**Comment by ChaitanyaBabar** [comment] 2020-03-23 09:36
> ```
> "compilerOptions": {
>     "paths": {
>         "@angular/*": [ "node_modules/@angular/*"]
>     }
>   }
> ```
> 
> Adding this to tsconfig.json worked for me
> 
> Look at #9576 issue too

To : @davidemess 
CC :@Hank1370 , @cefamax 

This worked for me too.

I am still wondering how/why it worked ?
@davidemess Can you please elaborate why/how it worked ?

Thanks,
Chaitanya

**Comment by segux** [comment] 2020-05-07 15:06
I think it works because compiler are resolving every angular dependency with node_modules root folder dependency. 
Probably you have some dependencies with different angular versions

**Comment by alxhub** [comment] 2020-05-27 21:06
Yeah, I've seen this happen when there are multiple versions of Angular in `node_modules`. `npm ls` is your friend.

**Comment by JoostK** [comment] 2021-05-14 12:18
This is no longer an issue with Ivy, so closing as resolved.

**Closed by JoostK** 2021-05-14 12:18 UTC
Labels: P5, comp: compiler, engine: ve, freq1: low, hotlist: error messages, triage #1, type: confusing
