### ISSUE TITLE
Cannot find the outlet from lazy loaded components (modules)

### ISSUE THREAD

**Issue by tamasfoldi** [angular/angular#12777] opened 2016-11-09 14:43 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When I'm trying to make a router-outlet work from a lazy loaded component I receive the following error message: ` EXCEPTION: Uncaught (in promise): Error: Cannot find the outlet test to load 'TestToOutletComponent'`

**Expected behavior**
It should find router-outle of lazy loaded components (modules)

**Minimal reproduction of the problem with instructions**
[Here](https://github.com/tamasfoldi/lazyload-router-outlet) is a repo created with cli. After ng serve, navigate [http://localhost:4200/test ](http://localhost:4200/test ) and click on Outlet Test link and the error will appear on the console

**What is the motivation / use case for changing the behavior?**
I would like to have a lazy loaded module which has its own routing. In my concrete project I'm loading a module lazy, and this module has a "menu bar" which should load the components based on the route. When I'm trying to make it work I'm receiving the error mentioned above.

**Please tell us about your environment:**
OpenSuse 13.1, angular-cli, VSCode 1.8

* **Angular version:** 2.0.X
angular version: 2.1.0

* **Browser:** all 
 
* **Language:** TypeScript 2.0.8

**Comment by vsavkin** [comment] 2016-11-14 19:05
Could you provide a plunkr reproducing the issue?

You can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5

**Comment by tamasfoldi** [comment] 2016-11-16 09:56
@vsavkin [Here](http://plnkr.co/edit/ehaT3f0K06BCn08sJ8ns) you can find the plunkr. I've put it in the crisis-center module. If you clink on the `Crisis Center` menu and then on the `Outlet Test` you can see in the console that it says: `Error: Cannot find the outlet test to load 'TestToOutletComponent'`

**Comment by chenyingyin** [comment] 2016-12-01 05:26
![default](https://cloud.githubusercontent.com/assets/24284270/20782714/60f05eaa-b7c9-11e6-9006-f7beb8bef322.png)

**Comment by exedriver** [comment] 2017-01-18 14:15
We are facing the same problem - any updates regarding this bug?

**Comment by DzmitryShylovich** [comment] 2017-01-18 14:26
@exedriver can you reproduce it on Plunkr? Sorry, but without a repro it's not actionable

**Comment by DzmitryShylovich** [comment] 2017-01-18 14:26
@exedriver can u add a small reproduction on Plunkr?

**Comment by exedriver** [comment] 2017-01-18 14:31
@DzmitryShylovich Look at the comment before mine, @tamasfoldi already added a plunkr.

**Comment by DzmitryShylovich** [comment] 2017-01-18 14:34
@exedriver the provided plunker is too big. It contains a lot of unnecessary components/service which makes debugging much more complicated. This is probably why the issue is still open :)

**Comment by exedriver** [comment] 2017-01-18 15:13
This is my first own plunkr ever and I'm still very new to angular2, but here it is: [Plunkr](http://plnkr.co/edit/foNP7L1V5yUoVKw7pGPq?p=preview)

You can see in the app.ts itself, that I'm lazy loading an external module (ExtModule) when clicking on the ExtModule link. In the ExtModule I have a ExtComponent, which links to a seconed (named) router-outlet to link to the ExtChildComponent. If you click on the "To ExtChildComponent" link, you'll get the error mentioned before "Error: Cannot find the outlet extOutlet to load 'ExtChildComponent'"

Hope this will help you debugging :)

**Comment by AHelper** [comment] 2017-01-20 19:18
Looking at your plunker (I've hit this same situation), it seems like it is trying to resolve the outlet in the top-level component, `App`. If you move the router outlet from `ExtComponent` to there, it displays it, however it feels like there should be a way to accomplish this. 

Stepping through `Router` and `RouterOutlet`, the named outlet in `ExtComponent` registers itself in the RouterOutletMap of the outlet in `App`.  However, the router, when navigating, only looks at the top-level outlet map, which only contains the primary route.

Modified plunker that adds the extOutlet outlet to the root outlet map of the router, workaround for expected behavior: http://plnkr.co/edit/OeBC1KqWkeGmHj3d6msO?p=preview

**Comment by denu5** [comment] 2017-03-07 18:35
@AHelper in your plunker: this.router.outletMap -> outletMap is private so that doesnt work when I want to compile ts.

**Comment by jasonaden** [comment] 2018-05-22 22:40
I would like to know if this issue persists for anyone. The plunker no longer works, and if this isn't an issue at this time, I would like to close it. Please comment here if this issue persists.

**Comment by jasonaden** [comment] 2018-05-24 22:49
Closing due to lack of response and no working repro. Please open a new issue if this comes up again.

**Closed by jasonaden** 2018-05-24 22:49 UTC
Labels: comp: router, flag: can be closed?, state: Need repro
