### ISSUE TITLE
Inheritance In Components Makes Build Error

### ISSUE THREAD

**Issue by moshtaba** [angular/angular#21586] opened 2018-01-17 11:42 UTC
## I have a parent Component like this:
<pre><code>
import { Component} from '@angular/core';

@Component({
    selector: 'app-main-parent',
    template: '',
})
export class ParentComponent {
    constructor(protected service) {
        service.doSomething();
    }
}
</code></pre>

## and a child Component that extends parent:
<pre><code>
import { Component} from '@angular/core';
import { ChildService} from './services';

@Component({
    selector: 'app-main-child',
    templateUrl: './child.component.html',
})
export class ChildComponent extends ParentComponent{

    constructor(private _childService: ChildService) {
        super(_childService);
    }
}

</code></pre>

## and in main.module.ts added these components:
<pre><code>
import { NgModule } from '@angular/core';
import { ParentComponent,
        ChildComponent } from './components'

@NgModule({
    imports: [
	...
    ],
    declarations: [
        ParentComponent,
        ChildComponent,
        ...
    ],
    providers: [
	...
    ]
})
export class MainModule { }

</code></pre>

## I build project with following command:
`npm run build`

## And got this Error:
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
npm ERR! code ELIFECYCLE
npm ERR! errno 3
npm ERR! proj.panel@0.0.0 build: `ng build --aot --prod --stats-json`
npm ERR! Exit status 3
npm ERR!
npm ERR! Failed at the proj.panel@0.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2018-01-17T10_37_32_166Z-debug.log

## If I remove ParentComponent from main.module.ts, then get this Error:
Cannot determine the module for class ParentComponent in C:/Users/user/source/repos/proj/web-panel/app/main/components.ts! Add ParentComponent to the NgModule to fix it.

## Other Stuff:
if I run project with `npm start` command it works fine. only in build I got these Errors.

I ran build command with no aot (`ng build --no-aot --prod`) but errors are still there.

I dont use ParentComponent anywhere but for childs components to extend.

Angular version: 5.0.0
 
For Tooling issues:
- Node version: 6.11.4
- Platform:  Windows 10
- npm version: 5.6.0

**Comment by moshtaba** [comment] 2018-01-20 07:29
really?! No one?! No comment?! No hint?!

**Comment by trotyl** [comment] 2018-02-07 11:33
Duplicate of #16566, see https://github.com/angular/angular/issues/16566#issuecomment-337960028

**Comment by chuckjaz** [comment] 2018-02-08 23:57
Thanks for reporting this issue. However this issue is a duplicate of an existing issue #16637. Please subscribe to that issue for future updates.

**Closed by chuckjaz** 2018-02-08 23:57 UTC
Labels: comp: core & compiler

**Comment by moshtaba** [comment] 2018-02-14 10:07
So I searched a lot, and ask everyone I thought could help and nothing was solution.
Then I created a new project and copied all files from main project and magically errors get gone.
The problem was not about inheritance in components and still don't know what made errors
