### ISSUE TITLE
PatternValidator with Property Binding is null

### ISSUE THREAD

**Issue by DHainzl** [angular/angular#7595] opened 2016-03-14 13:49 UTC
* **I'm submitting a ... **
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, see note at the top of this template.

* **What is the current behavior?**
When using a PatternValidator with Property Binding, e.g. the following syntax: `[pattern]="pattern"`, it does not validate with the content of the `pattern` variable, but with `null` instead.

Demo: http://plnkr.co/edit/xOJsBjZquDBEJNHh7i3Y?p=preview

Output is:
```
{
  "pattern": {
    "requiredPattern": "^null$",
    "actualValue": "asdf"
  }
}
```

but the content of my `pattern` variable is `[a-zA-Z1-9+]`

* **Please tell us about your environment:**
  - Angular version: 2.0.0-beta.9
  - Browser: Tested in Chrome 49, Firefox 44.0.2
  - Language: TypeScript

**Comment by PascalPrecht** [comment] 2016-03-14 19:09
Pretty much a dupe of https://github.com/angular/angular/issues/7393

The reason why this doesn't work is that the current implementation of validators doesn't support property binding. In other words, as long as you're template-driven forms, you can't pass an expression to built-in validators.

**Comment by brachi-wernick** [comment] 2016-07-26 06:21
still happens in RC4. what are the plans?

**Comment by kara** [comment] 2016-08-29 20:21
Should have been fixed by https://github.com/angular/angular/pull/11116.

**Closed by kara** 2016-08-29 20:21 UTC

**Comment by alexlukin-softgrad** [comment] 2017-01-18 18:30
@kara It still doesn't work for me...

**Comment by DzmitryShylovich** [comment] 2017-01-18 18:34
@alexlukin-softgrad reproduce on Plunkr and file a new issue

**Comment by alexlukin-softgrad** [comment] 2017-01-18 21:22
@DzmitryShylovich my fault. I managed to figure out, it works. Hope this sample or email validation using regexp pattern binding will be helpful to someone.
https://plnkr.co/edit/UD9DEoBJ7APs1u4bmGEF?p=preview
