### ISSUE TITLE
Routing inside angular element not working script gets loaded page showing below the main element page old companant stasy as is

### ISSUE THREAD

**Issue by lalitsonje** [angular/angular#38523] opened 2020-08-19 07:51 UTC
Created sub application like angular element and loaded into another application. Use Following Reference

https://dzone.com/articles/build-micro-front-ends-using-angular-elements-the

Main entry component loaded but redirection from their not working.

**Comment by sonukapoor** [comment] 2020-08-19 12:05
@lalitsonje Could you please provide a minimal reproducible stackblitz with only the important pieces for us?

**Comment by lalitsonje** [comment] 2020-08-19 12:25
@sonukapoor will share the 


Subapplication app module.ts

 @NgModule({
  declarations: [
   
    AdcHomeComponent,
   
  ],
  imports: [
	--
	---
    
  ],
  providers: [],
  bootstrap: [],
  entryComponents: [AdcHomeComponent],
  
})
export class AppModule { 

  constructor(private injector: Injector) {
    const iap = createCustomElement(AdcHomeComponent, { injector });
    customElements.define('app-adc-home', iap);
  }

  ngDoBootstrap() {}
  
}

Routing in sub application ie. angular element

@NgModule({
  

  imports: [
    ElementRoutingModule.withRoutes([
   
      {
        path: 'processDetails', outlet: 'iapui',
        component: UploadDetailsComponent,
        data: { breadcrumb: 'Upload Details' },
      },
      {
        path: 'applicationDetails', outlet: 'iapui',
        component: ApplicationDetailsComponent,
        data: { breadcrumb: 'Application Details' },
      },
      {
        path: 'createSubscription', outlet: 'iapui',
        component: CRUDComponent,
        data: { breadcrumb: 'Create Subscription' },
      },
      {
        path: 'modifySubscription/:subscriptionId',outlet: 'iapui', 
        component: CRUDComponent,
        data: { breadcrumb: 'Modify Subscription' },
      },
      {
        path: 'viewSubscription/:subscriptionId',outlet: 'iapui',
        component: CRUDComponent,
        data: { breadcrumb: 'View Subscription' },
      },
      // { path: '', redirectTo: 'datacollection', pathMatch: 'full' }
    ]),
  ],
  exports: [ElementRoutingModule],

  
})
export class AppRoutingModule { 

  
}

==> Inside Entry compoent added 

<router-outlet name="iapui"></router-outlet>

In main application 

<app-adc-home *axLazyElement="elementUrl"></app-adc-home>

Elements gets loades if try to navagiage after first page loading next page script working but page is not redirected

**Comment by sonukapoor** [comment] 2020-08-19 17:46
@lalitsonje Thank you for providing additional information. However, it's still not possible for us to debug this based on the provided code. Can you try to move the important parts only to a stackblitz? Also, have you tried to use the GitHub code provided in the article and see if that is working?

**Comment by atscott** [comment] 2020-08-19 17:47
There are several issues related to [custom elements with routing](https://github.com/angular/angular/issues?q=is%3Aissue+is%3Aopen+label%3A%22comp%3A+router%22+elements+label%3A%22cross-cutting%3A+custom+elements%22). This specifically sounds like a duplicate of #31587 though it may be related to some of the others as well. In general, routing was not designed to support this use-case. There is a single address bar, so it makes sense that the router itself is also a singleton. Using custom elements, each which have their own routing, breaks this concept. Closing as a duplicate and due to not having a reproduction.

**Closed by atscott** 2020-08-19 17:47 UTC
