### ISSUE TITLE
How can I use a route's resolve data in a title resolver?

### ISSUE THREAD

**Issue by wgibbons1** [angular/angular#47781] opened 2022-10-16 09:35 UTC
### Which @angular/* package(s) are relevant/related to the feature request?

router

### Description

How can I access a route's resolver data in the route's title resolver?

I want to dynamically set my route's title, using the data from the resolver. For example, my route is to view a product, and I get the product data via a route resolver (ProductResolverService below), and I want my route title to be 'Product X', where X would come from the resolve data. I've tried below but the route.data is undefined.

```
{ title: ProductNameTitleResolver, resolve: { product: ProductResolverService } } // Route

@Injectable()
export class ProductNameTitleResolver implements Resolve<string> {
  resolve(route: ActivatedRouteSnapshot, state: RouterStateSnapshot): string | Promise<string> | Observable<string>  {
    const productData = route.data['product'] // Unfortunately this is undefined
    return `Product ${productData.name}`
  }
}
```

This would be useful to eliminate the need to make two http calls in this situation (one for the route-resolver and one for the title-resolver).

### Proposed solution

Populate route-resolver data into title-resolvers' route.data.

### Alternatives considered

None

**Comment by atscott** [comment] 2022-10-17 13:42
The `title` property is a resolver itself so it follows the same rules as other resolvers (you can't access resolved data from other resolvers). For accessing resolved data from a parent, I'll close this as a duplicate of https://github.com/angular/angular/issues/47287

**Closed by atscott** 2022-10-17 13:42 UTC
Labels: area: router

**Comment by wgibbons1** [comment] 2022-10-19 07:10
Don't know why this is being closed. This is a major drawback.
