### ISSUE TITLE
Angular SSR app meta tag not updating

### ISSUE THREAD

**Issue by Dev-Mohit-1220** [angular/angular#56733] opened 2024-06-27 09:48 UTC
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

 I have added the meta tag in my angular SSR application and Meta tag updating locally but when I host in different services like
 firebase and netlify it's not working.
 

### Please provide a link to a minimal reproduction of the bug

https://angular-18-ssr.netlify.app

### Please provide the exception or error you saw

```true
Here is my package.json, angular json file and tsconfig respectively.

{
  "name": "angular18-ssr",
  "version": "1.0.1",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "watch": "ng build --watch --configuration development",
    "test": "ng test",
    "serve:ssr:Angular18_SSR": "node dist/angular18-ssr/server/server.mjs"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^18.0.0",
    "@angular/common": "^18.0.0",
    "@angular/compiler": "^18.0.0",
    "@angular/core": "^18.0.0",
    "@angular/forms": "^18.0.0",
    "@angular/platform-browser": "^18.0.0",
    "@angular/platform-browser-dynamic": "^18.0.0",
    "@angular/platform-server": "^18.0.0",
    "@angular/router": "^18.0.0",
    "@angular/ssr": "^18.0.4",
    "@ng-bootstrap/ng-bootstrap": "^17.0.0",
    "@popperjs/core": "^2.11.8",
    "bootstrap": "^5.3.2",
    "express": "^4.18.2",
    "rxjs": "~7.8.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.14.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^18.0.4",
    "@angular/cli": "^18.0.4",
    "@angular/compiler-cli": "^18.0.0",
    "@angular/localize": "^18.0.0",
    "@types/express": "^4.17.17",
    "@types/jasmine": "~5.1.0",
    "@types/node": "^18.18.0",
    "jasmine-core": "~5.1.0",
    "karma": "~6.4.0",
    "karma-chrome-launcher": "~3.2.0",
    "karma-coverage": "~2.2.0",
    "karma-jasmine": "~5.1.0",
    "karma-jasmine-html-reporter": "~2.1.0",
    "typescript": "~5.4.2"
  }
}


---------------------------------------------------------------------------------------------------


{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "newProjectRoot": "projects",
  "projects": {
    "Angular18_SSR": {
      "projectType": "application",
      "schematics": {
        "@schematics/angular:component": {
          "style": "scss"
        }
      },
      "root": "",
      "sourceRoot": "src",
      "prefix": "app",
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:application",
          "options": {
            "outputPath": "dist/angular18-ssr",
            "index": "src/index.html",
            "browser": "src/main.ts",
            "polyfills": [
              "zone.js",
              "@angular/localize/init"
            ],
            "tsConfig": "tsconfig.app.json",
            "inlineStyleLanguage": "scss",
            "assets": [
              "src/favicon.ico",
              "src/assets"
            ],
            "styles": [
              "src/styles.scss"
            ],
            "scripts": [],
            "server": "src/main.server.ts",
            "prerender": false,
            "ssr": {
              "entry": "server.ts"
            }
          },
          "configurations": {
            "production": {
              "budgets": [
                {
                  "type": "initial",
                  "maximumWarning": "500kB",
                  "maximumError": "1MB"
                },
                {
                  "type": "anyComponentStyle",
                  "maximumWarning": "2kB",
                  "maximumError": "4kB"
                }
              ],
              "outputHashing": "all"
            },
            "development": {
              "optimization": false,
              "extractLicenses": false,
              "sourceMap": true
            }
          },
          "defaultConfiguration": "production"
        },
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "configurations": {
            "production": {
              "buildTarget": "Angular18_SSR:build:production"
            },
            "development": {
              "buildTarget": "Angular18_SSR:build:development"
            }
          },
          "defaultConfiguration": "development"
        },
        "extract-i18n": {
          "builder": "@angular-devkit/build-angular:extract-i18n"
        },
        "test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "polyfills": [
              "zone.js",
              "zone.js/testing",
              "@angular/localize/init"
            ],
            "tsConfig": "tsconfig.spec.json",
            "inlineStyleLanguage": "scss",
            "assets": [
              "src/favicon.ico",
              "src/assets"
            ],
            "styles": [
              "src/styles.scss"
            ],
            "scripts": []
          }
        }
      }
    }
  }
}
  

----------------------------------------------------------------------------------------------------

/* To learn more about Typescript configuration file: https://www.typescriptlang.org/docs/handbook/tsconfig-json.html. */
/* To learn more about Angular compiler options: https://angular.dev/reference/configs/angular-compiler-options. */
{
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "strict": true,
    "noImplicitOverride": true,
    "noPropertyAccessFromIndexSignature": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "sourceMap": true,
    "declaration": false,
    "experimentalDecorators": true,
    "moduleResolution": "bundler",
    "importHelpers": true,
    "target": "ES2022",
    "module": "ES2022",
    "useDefineForClassFields": false,
    "lib": [
      "ES2022",
      "dom"
    ]
  },
  "angularCompilerOptions": {
    "enableI18nLegacyMessageIdFormat": false,
    "strictInjectionParameters": true,
    "strictInputAccessModifiers": true,
    "strictTemplates": true
  }
}
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 18.0.4
Node: 20.11.1
Package Manager: npm 10.2.4
OS: win32 x64

Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1800.4 (cli-only)
@angular-devkit/core         18.0.4 (cli-only)
@angular-devkit/schematics   18.0.4 (cli-only)
@schematics/angular          18.0.4 (cli-only)


C:\Users\NS 73>
```

### Anything else?

Any other thing you need, please feel free to ask.

https://angular-18-ssr.netlify.app/

https://angular-18-ssr.netlify.app/6

**Comment by alan-agius4** [comment] 2024-06-27 10:02
Hi @Dev-Mohit-1220, it looks like the page is not being SSR'd properly inspecting the source-code I noticed that the blog details are not populated. 

```html
 <router-outlet _ngcontent-ng-c1063383644=""></router-outlet
        ><app-home _nghost-ng-c2183094776="" ngh="0"
          ><!---->
          <h1 _ngcontent-ng-c2183094776=""><!--ngetn--></h1>
          <div _ngcontent-ng-c2183094776="" class="text-center my-3">
            <!---->
          </div>
          <div _ngcontent-ng-c2183094776="" class="innerhtml"></div>
          <div _ngcontent-ng-c2183094776="" class="text-center my-5 py-5">
            <h2 _ngcontent-ng-c2183094776="">No blog details found 🙁</h2>
          </div>
```

This suggests that there is an error during rendering, likely the API is not accessible from the production server.

**Comment by Dev-Mohit-1220** [comment] 2024-06-27 10:18
Currently I can access the hosted site and getting data properly with the API Call.
![Screenshot_4](https://github.com/angular/angular/assets/149872549/e0145e7e-0f04-480e-a500-679cc50d7d64)
![Screenshot_3](https://github.com/angular/angular/assets/149872549/949c40ab-a1f7-417a-a8a6-bd8a2eccb578)

**Comment by Dev-Mohit-1220** [comment] 2024-06-27 10:19
Hello @alan-agius4, please check above message.
Thanks for reply

**Comment by alan-agius4** [comment] 2024-06-27 10:29
The screenshots above were taken from the browser. During SSR, API calls are made from the server. Unfortunately, without a reproduction of the issue, we are unable to provide further assistance. Could you please set up a minimal reproduction?

You can read [here](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by JeanMeche** [comment] 2024-07-10 06:46
I'm going to close this as a dupe of #53711. This was likely not implemented correctly, the apps becomes stable before the tags could be set.

**Closed by JeanMeche** 2024-07-10 06:46 UTC
Labels: needs reproduction, area: server
