### ISSUE TITLE
minLength, maxLength validators has different naming in hasError method

### ISSUE THREAD

**Issue by pumano** [angular/angular#53133] opened 2023-11-23 13:50 UTC
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

No

### Description

when set validator for reactive form we use something like this:

```ts
public someField = new FormControl('', [Validators.required, Validators.maxLength(20));
```

while when we need to check error via `someField.hasError('maxLength');` we have false. Why? Because maxLength validator has different naming in errors bucket:

```ts
console.log(somefield.errors)
```
leads to:
```ts
{ maxlength: { requiredLength: 50, actualLength: 55 } }
```

Would be good if it be accessible via  `.hasError()`  using `maxLength` too (camelCase syntax). For `minLength` validator same needed. 

### Please provide the environment you discovered this bug in (run `ng version`)

```true
angular 16 latest
```

**Comment by JoostK** [comment] 2023-11-23 14:40
Duplicate of #7407.

The error names curently reflect the native HTML5 validation attributes. If anything I'd think the `Validators.{min,max}Length` should be lowercased (and aliased), but that seems like quite bit of churn for little gain when considering the other ones would need to be deprecated.

**Closed** 2024-01-11 16:52 UTC
Labels: area: forms
