### ISSUE TITLE
Language agnostic AOT renderer

### ISSUE THREAD

**Issue by bryanrideshark** [angular/angular#26844] opened 2018-10-30 03:46 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

# TL; DR
Why can't we just emit a language agnostic AST as an output opinion for ng build, instead of only having JavaScript as a compilation target? A language agnostic AST might allow us to target other platforms easier, and allow the community to easily add new platforms for Angular.

## Long Winded Version

Currently, the state of native mobile development with Angular feels like you're getting the least quality in terms of "feeling native" as the only fully feature complete option is Nativescript, which, for better or for worse, seems to be treated like the black sheep of the app development world.

I never want to leave Angular. Our team never wants to compromise on quality. So when you see React Native, Flutter, you start wondering... Could I have a sexier app with better plugins / widgets / animations if I'd only chosen a different framework?

Thing is, choosing another framework is out of the question. So what if it was possible to make a Flutter renderer, a React Native renderer, etc, that were fully featured?

I don't have the expertise or time to write a renderer for React Native or Flutter. But I bet if I was given an AST schema, I could make a piece of the pipeline that output JSX, or Flutter Dart, or some other language of the day. My ultimate goal would be to have all business logic running in JS in one thread, provided with a function to talk with the view layer, and then the view layer output as an AST just awaiting the renderer of your choice to be selected.

Maybe this has already been done. If it has been, maybe we just need better docs.

**Comment by trotyl** [comment] 2018-10-30 03:55
Duplicate of https://github.com/angular/angular/issues/22398

**Comment by robwormald** [comment] 2018-10-30 17:20
Angular already has a Renderer API, and that's how projects like NativeScript (and this super-old experiment https://github.com/angular/react-native-renderer) work, specifically designed for this purpose. 

> My ultimate goal would be to have all business logic running in JS in one thread, provided with a function to talk with the view layer, and then the view layer output as an AST just awaiting the renderer of your choice to be selected.

This is pretty much how it works :)

WIth React Native and friends, developers write JavaScript, and there's a JS execution environment where your JavaScript is pretty much run *as-is*, and it talks to the native environment through something like the Renderer API. You can do this today.

The reality is that we have limited resources, and we're focused on making the best *web* applications, and enabling third-parties like NativeScript to extend where needed.

It should also be said that this abstraction doesn't come without a cost - a lot of the work we're doing in Ivy is simplifying, cleaning up old APIs that were designed with this sort of thing in mind, and they end up adding a lot of indirection and bulk to the codebase. 

The AST and such you're asking for already exist, but they're generally internal / private APIs, because to do anything useful with them, you basically have to write a compiler, which is a non-trivial thing, and opening up those APIs publicly is not something we're ready to do yet.

**Comment by robwormald** [comment] 2018-10-30 17:22
re: Flutter - its a significantly different model (you're authoring in Dart, for a start), so its not really the same concept. Under the hood, Flutter is using the Skia engine in Chrome (https://www.chromium.org/developers/design-documents/graphics-and-skia), which is the layer you'd likely interop with. We've looked into this, and it's definitely *possible*, but not something we're currently planning on pursuing.

**Comment by robwormald** [comment] 2018-10-30 17:23
Closing this as a dupe of #22398

**Closed by robwormald** 2018-10-30 17:23 UTC
