### ISSUE TITLE
Updating disabled state after replacing FormGroup.

### ISSUE THREAD

**Issue by dgluszczyk** [angular/angular#18381] opened 2017-07-27 15:32 UTC
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
When I try to replace FormGroup that is bound to template, disabled state of controls isn't updated.
I know, that I can use enable() and disable() methods, but in my case I'm generating complete FormGroups and I have to replace them.

For now I'm using workaround which crawls through whole AbstractControls tree and runs enable() and disable() methods but I believe it should be fixed in better way inside framework.

## Expected behavior
Properly refreshed DOM when I toggle control's state using new instance of FormGroup.

## Minimal reproduction of the problem with instructions
1. Open related plunker: https://plnkr.co/edit/XSp2RhwBEEPylQub8W0L?p=preview
2. Click on 'Two enabled fields' button. Title select hasn't changed state to enabled.
3. Click on 'Two disabled fields' button. Name input hasn't changed state to disabled.

After each step value and state are updated inside connected FormControl (printed values) but change of disabled/enabled state is not propagated to DOM.

I created second plunker with one small change, I'm binding controls using [formControl] instead of formControlName and it behaves slightly different: it hasn't got any problems with switching state to disabled but it can't return to enabled state. Link: http://plnkr.co/edit/Xipc02DXwcv5y5gPmexo?p=preview

## What is the motivation / use case for changing the behavior?
I need a clean way to replace FormGroups containing FormControls with disabled/enabled DOM state that corresponds to FormControl state.

## Environment

<pre><code>
Angular version: 4.3.0-beta.0

Browser:
- [x] Chrome (desktop) version 59.0.3071.115
- [x] Firefox version 54.0.1
- [x] IE version 11
 
For Tooling issues:
- Node version: v6.9.5
- Platform:  Windows

**Comment by TheRemjx01** [comment] 2017-08-03 08:04
I have also got troubled with this issue also. Is it fixed?

**Comment by dzonatan** [comment] 2017-08-16 19:55
Duplicate of #17806.
Also a fix for this is ready #18575

**Comment by kara** [comment] 2017-12-12 23:20
Yeah, looks like the bug tracked here https://github.com/angular/angular/issues/17806

**Closed by kara** 2017-12-12 23:20 UTC
Labels: comp: forms, type: bug
