### ISSUE TITLE
(>ng18 SSR) NG0205 when trying to create dynamically imported component (only on server)

### ISSUE THREAD

**Issue by Aukevanoost** [angular/angular#59019] opened 2024-12-03 08:02 UTC
### Command

serve

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When I try to create a dynamic component loader, the following code fails in the server but succeeds in the browser: 

The idea is to be able to import components at runtime:

```
import { Component, inject, ChangeDetectionStrategy, PLATFORM_ID, ViewContainerRef, Injector, signal, computed } from "@angular/core";
import { CommonModule } from "@angular/common";

@Component({
    selector: 'test-proxy',
    standalone: true,
    imports: [CommonModule],
    template: ``,
    changeDetection: ChangeDetectionStrategy.OnPush
})
export class TestProxyComponent {
    #platformID = inject(PLATFORM_ID);
    #vcr = inject(ViewContainerRef);
    #injector = inject(Injector);

    // Signals for state management
    componentRef = signal<any>(null);
    
    constructor() {}

    async ngOnInit() {
        console.log('Host init');

        try {
            const comp = await import("./../test.component");
            console.log("Comp loaded");
            
            const ref = this.#vcr.createComponent(comp.TestComponent, {
                injector: this.#injector,
            });
            console.log("Comp created");

            this.componentRef.set(ref);
        } catch(e) {
            console.log(e);
        }
    }

    async ngOnDestroy() {
        console.log('Host destroyed');
        if (this.componentRef()) {
            this.componentRef().destroy();
        }
    }
}
```

The output in the console is: 

```
Starting SSR for Shell
Node Express server listening on http://localhost:4000
http://localhost:4000/

init host
Angular is running in development mode.
Destroyed host
Comp loaded
RuntimeError: NG0205: Injector has already been destroyed.
```

This seems like a race condition, but when I wait for the component to be imported before destroying the host (test-proxy). The Injector also seems to b destroyed. Am I missing something? 

In angular v19, this fails in the browser as well because the imported component is being rendered after the hydration cycle potentially again because of the import finishing after the Change detection run finished. 

### Minimal Reproduction

Create a minimal ssr angular application >18.2.x

```
"dependencies": {
    "@angular/animations": "^18.2.0",
    "@angular/common": "^18.2.0",
    "@angular/compiler": "^18.2.0",
    "@angular/core": "^18.2.0",
    "@angular/forms": "^18.2.0",
    "@angular/platform-browser": "^18.2.0",
    "@angular/platform-browser-dynamic": "^18.2.0",
    "@angular/platform-server": "^18.2.0",
    "@angular/router": "^18.2.0",
    "@angular/ssr": "^18.2.12",
    "cors": "^2.8.5",
    "express": "^4.18.2",
    "rxjs": "~7.8.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.14.10"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^18.2.12",
    "@angular/cli": "^18.2.11",
    "@angular/compiler-cli": "^18.2.0",
    "@types/express": "^4.17.17",
    "@types/jasmine": "~5.1.0",
    "@types/node": "^18.18.0",
    "jasmine-core": "~5.2.0",
    "karma": "~6.4.0",
    "karma-chrome-launcher": "~3.2.0",
    "karma-coverage": "~2.2.0",
    "karma-jasmine": "~5.1.0",
    "karma-jasmine-html-reporter": "~2.1.0",
    "ng-packagr": "^18.2.0",
    "typescript": "~5.5.2"
  }
```

Reproduction path
- Create the 2 test components (test-proxy and test.component.ts)
- Import and declare test-proxy in the app.component.ts
- Build the app (ng build {your-app})
- Serve the app with serve:ssr:{your-app}
- Navigate to the webpage 
- Observe the error in the terminal.

### Exception or Error

```text
RuntimeError: NG0205: Injector has already been destroyed.
    at R3Injector.assertNotDestroyed (file:///chunk-XL3YIOMR.mjs:18492:17)
    at R3Injector.get (file:chunk-XL3YIOMR.mjs:18399:14)
    at ChainedInjector.get (file:chunk-XL3YIOMR.mjs:18845:36)
    at lookupTokenUsingModuleInjector (file:chunk-XL3YIOMR.mjs:5848:31)
    at getOrCreateInjectable (file:chunk-XL3YIOMR.mjs:5873:10)
    at NodeInjector.get (file:chunk-XL3YIOMR.mjs:18860:16)
    at ViewContainerRef2.createComponent (file:chunk-XL3YIOMR.mjs:20637:36)
    at _TestProxyComponent.<anonymous> (file:chunk-PZQSFX4J.mjs:72:35)
    at Generator.next (<anonymous>)
    at fulfilled (file:chunk-JYXTTNQK.mjs:73:24) {
  code: 205
}
```

### Your Environment

```text
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 18.2.12
Node: 23.3.0 
Package Manager: npm 10.9.0
OS: darwin arm64

Angular: 18.2.13
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1802.12
@angular-devkit/build-angular   18.2.12
@angular-devkit/core            18.2.12
@angular-devkit/schematics      18.2.12
@angular/cli                    18.2.12
@angular/ssr                    18.2.12
@schematics/angular             18.2.12
ng-packagr                      18.2.1
rxjs                            7.8.1
typescript                      5.5.4
zone.js                         0.14.10
    
Warning: The current version of Node (23.3.0) is not supported by Angular.
```

**Comment by alan-agius4** [comment] 2024-12-03 09:40
Duplicate of https://github.com/angular/angular/issues/53191

**Closed by alan-agius4** 2024-12-03 09:40 UTC

**Comment by Aukevanoost** [comment] 2024-12-03 09:55
Ah yeah! thanks for the tip, it works like a charm! (on v18.2.x)

```
import { Component, inject, ChangeDetectionStrategy, PLATFORM_ID, ViewContainerRef, Injector, signal, computed, ExperimentalPendingTasks, DestroyRef } from "@angular/core";
import { CommonModule } from "@angular/common";

@Component({
    selector: 'test-proxy',
    standalone: true,
    imports: [CommonModule],
    template: ``,
    changeDetection: ChangeDetectionStrategy.OnPush
})
export class TestProxyComponent {
    // #platformID = inject(PLATFORM_ID);
    #vcr = inject(ViewContainerRef);
    #injector = inject(Injector);
    private pendingTasks = inject(ExperimentalPendingTasks);
    private destroyed = false;
    
    constructor() {
        inject(DestroyRef).onDestroy(() => (this.destroyed = true));
    }

    ngOnInit() {
        this.render();
    }

    private async render() {
        console.log('Host init');
        const removeTask = this.pendingTasks.add();


        try {
            const comp = await import("./../test.component")
                .then(({TestComponent}) => TestComponent);
            console.log("Comp loaded");
            if (this.destroyed) return;

            const ref = this.#vcr.createComponent(comp, {
                injector: this.#injector,
            });
            console.log("Comp created");
            ref.changeDetectorRef.detectChanges();
            console.log("Change detection");
        } catch(e) {
            console.log(e);
        } finally {
            removeTask();
        }
    }

    async ngOnDestroy() {
        console.log('Host destroyed');
    }
}
```
