### ISSUE TITLE
Getting Started Documentation

### ISSUE THREAD

**Issue by elnino07** [angular/angular#43211] opened 2021-08-20 13:47 UTC
### Description

It would be nice to have the Documentation updated for the `Getting Started` page.  At the end of the step `Pass data to a child component` you will get an compiling error if doing every step according to the documentation. There is no hint anywhere at this page, that the component `ProductAlertsComponent` needs to be added to the `module.ts`.

### What is the affected URL?

https://angular.io/start

### Please provide the steps to reproduce the issue

Follow step by step the tutorial of `Getting Started` until the end of `Pass data to a child component`, where it will display a compiler error.

### Please provide the expected behavior vs the actual behavior you encountered

compiler error vs. no compiler error

### Please provide a screenshot if possible

![image](https://user-images.githubusercontent.com/55378895/130243082-a1358ef8-6c51-460c-ad7f-e95f64449a47.png)

### Please provide the exception or error you saw

```true
see screenshot
```

**Comment by subson** [comment] 2021-08-20 15:15
Looks like it is missing a step of adding to the app.module.ts. Created a PR to fix the docs - #43212 43212

**Comment by vugar005** [comment] 2021-08-20 15:54
@subson  This seems related to those too [#43053](https://github.com/angular/angular/issues/43053) and [#43020](https://github.com/angular/angular/issues/43020).

**Comment by subson** [comment] 2021-08-20 20:50
These 2 issues(#43053 , #43020) can be fixed with the same PR - #43212

**Comment by gkalpak** [comment] 2021-08-23 09:45
Thx for reporting this, @elnino07 :+1:
I am going to close this as a duplicate of #43020.

**Closed by gkalpak** 2021-08-23 09:45 UTC
Labels: comp: docs
