### ISSUE TITLE
[Ivy] customElements.define fails when in Module constructor

### ISSUE THREAD

**Issue by pmilic021** [angular/angular#35639] opened 2020-02-23 13:12 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/core

### Is this a regression?

 Yes, the previous version in which this bug was not present was: v8

### Description

 After updating to angular 9 from angular 8 (but it is not related to the update as it is reproducible in clean ng9 repo), my angular component stopped working, and the issue is related to the `Optional()` DI mechanism, when used inside of an angular element component. 
<br/><br/>
Peculiarities:
- If used without ivy, the issue disappears (i.e. `"angularCompilerOptions": {"enableIvy": false}`).
- If optional DI is used outside of angular elements component, it works without any issues.
- Also, if the angular element component is used within some other _normal_  angular component, there will be no issue, only when it is used directly within `index.html` or any other nonangular environment (which is where the angular elements components mostly get used anyway).
- One more thing I noticed is that when the injection is tried in next tick (i.e. wrapped inside of `setTimeout(()=>{...}, 0)`) the issue is gone as well.
- Moving `createCustomElement` call from the module constructor to `ngDoBootstrap` also fixes issue, but it is probably for the same reason as the above bullet.

## 🔬 Minimal Reproduction

 Since the stackblitz is infamous for its angular elements support (and the template is not updated for ng9, I made a github repo for that: https://github.com/pmilic021/angular-elements-optional-repro .

## 🔥 Exception or Error
<pre><code>
test.module.ts:20 Trying to load Router in `test.module.ts`...
test.module.ts:21 success
test.component.ts:11 Trying to load Router in `test.component.ts`...
test.component.ts:14 fail TypeError: Cannot read property 'get' of undefined
    at NgModuleRef$1.get (core.js:35665)
    at Object.get (core.js:33422)
    at getOrCreateInjectable (core.js:5498)
    at NodeInjector.get (core.js:5746)
    at new TestComponent (test.component.ts:12)
    at NodeInjectorFactory.TestComponent_Factory [as factory] (test.component.ts:16)
    at getNodeInjectable (core.js:5643)
    at instantiateRootComponent (core.js:12570)
    at createRootComponent (core.js:26011)
    at ComponentFactory$1.create (core.js:33544)
test.component.ts:11 Trying to load Router in `test.component.ts`...
test.component.ts:12 success
</code></pre>
The test module is the module that creates the angular elements component (as seen in repro git provided). Test component is the component turned into the angular elements component. The one failing to load Router module is the one called from `index.hmtl` and the one that succeedes is the one called from `app.component.ts`.

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.0.3
Node: 10.15.3
OS: darwin x64

Angular: 9.0.2
... animations, common, compiler, compiler-cli, core, elements
... forms, language-service, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.3
@angular-devkit/build-angular     0.900.3
@angular-devkit/build-optimizer   0.900.3
@angular-devkit/build-webpack     0.900.3
@angular-devkit/core              9.0.3
@angular-devkit/schematics        9.0.3
@angular/cli                      9.0.3
@ngtools/webpack                  9.0.3
@schematics/angular               9.0.3
@schematics/update                0.900.3
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
</code></pre>

**Anything else relevant?**

Naturally, the same applies for `@Optional()` decorator.

**Comment by pkozlowski-opensource** [comment] 2020-02-24 15:16
@pmilic021 it would help immensely if you could provide a minimal, runnable reproduce scenario via stackblitz or https://ng-run.com/

**Comment by pmilic021** [comment] 2020-02-26 10:08
While stackblitz proved to be buggy in combination with elements, I did in fact manage to reproduce it in ng-run: https://ng-run.com/edit/BQGQtb5CMAaiw6HERj6O?open=app%2Ftest%2Ftest.component.ts

should be able to see error in console: 
![image](https://user-images.githubusercontent.com/29102199/75334523-500c4780-5888-11ea-9278-8ec2014022cb.png)

**Comment by atscott** [comment] 2020-02-28 17:52
Just a quick note that the issue occurs because `customElements.define('test-ce', headerCE);` happens in the `TestModule` constructor and is unrelated to `Optional` DI.

The failure chain is 
1. `AppModule` instantiates and starts creating a root injector 
2. during root injector creation, hydrate `TestModule` 
3. `TestModule` defines `TestComponent` customElement 
4. Angular Elements attempts to instantiate root component for `TestComponent`
5. `TestComponent` attempts to inject `Router`
6. Try to retrieve `Router` from injector that hasn't been created yet

**Comment by pmilic021** [comment] 2020-02-29 16:46
Yeah, mentioned something similar in the description under the last bullet. This works with ng8 though, we had that code in production already. I'm not very good with internals of angular, but if I understood correctly, it's some kind of race condition which was not happening in ng8? Perhaps it is just no longer a valid way to use `customElements.define`?

**Comment by atscott** [comment] 2020-03-02 16:13
Right, the difference you're observing between v8 and v9 is that v9 would enable Ivy by default which is a completely different runtime than before (including the injector implementation). The injector was instantiated in a more incremental way in the previous runtime (https://github.com/angular/angular/blob/master/packages/core/src/view/refs.ts#L374-L379) - `injector = this` followed by pushing to providers in `initNgModule`.

I'm still investigating if there's something that can be done about this in Ivy. Your proposed workaround of moving the `customElements.define` to `ngDoBootstrap` seems correct and reasonable in the meantime.

**Comment by atscott** [comment] 2020-03-02 19:22
This will likely be fixed by https://github.com/angular/angular/pull/35731

**Closed** 2020-03-03 21:52 UTC
Labels: comp: core, comp: elements, comp: ivy, freq1: low, severity5: regression, state: has PR, type: bug/fix
