### ISSUE TITLE
Ivy compiler doesn't build library with secondary entry points. Gives unable to write reference error.

### ISSUE THREAD

**Issue by aishwaryasharma14** [angular/angular#44174] opened 2021-11-15 14:21 UTC
### Which @angular/* package(s) are the source of the bug?

compiler

### Is this a regression?

No

### Description

I have a library with secondary entry points and has following structure.

```
projects
|____components
       |     package.json
       |     ng-package.json
       |____editable-grid //secondary entry point
       |       |____src
       |               package.json
       |               ng-package.json
       |               public-api.ts
       |               // ...other components files and folder
       |____src // primary entry point
              |    public-api.ts
              |____lib
                     |____modules
                            |____grid
                                    grid.models.d.ts
                                    // ...other components files and folder
```

It builds successfully if I set `enableIvy: false` in tsconfig.lib.json. But when I use Ivy compilation, the primary entry point is built successfully, but it gives error for the secondary entry point as given below -

✖ Compiling with Angular sources in Ivy full compilation mode.
An unhandled exception occurred: Unable to write a reference to ContextMenuItemModel in C:/source/project-folder/dist/components/lib/modules/grid/grid.models.d.ts from c:/source/project-folder/projects/components/editable-grid/src/editable-grid.component.ngtypecheck.ts 
See "C:\Users\www33\AppData\Local\Temp\ng-tisOKv\angular-errors.log" for further details.

### Please provide the exception or error you saw

```true
✖ Compiling with Angular sources in Ivy full compilation mode.
An unhandled exception occurred: Unable to write a reference to ContextMenuItemModel in C:/source/project-folder/dist/components/lib/modules/grid/grid.models.d.ts from c:/source/project-folder/projects/components/editable-grid/src/editable-grid.component.ngtypecheck.ts 
See "C:\Users\www33\AppData\Local\Temp\ng-tisOKv\angular-errors.log" for further details.
```

### Please provide the environment you discovered this bug in

```true
Angular CLI: 12.2.13
Node version: 14.x

"dependencies": {
    "@angular-devkit/schematics": "^12.2.5",
    "@angular/animations": "^12.2.5",
    "@angular/cdk": "^12.2.5",
    "@angular/cdk-experimental": "^12.2.5",
    "@angular/common": "^12.2.5",
    "@angular/compiler": "^12.2.5",
    "@angular/core": "^12.2.5",
    "@angular/forms": "^12.2.5",
    "@angular/localize": "^12.2.5",
    "@angular/platform-browser": "^12.2.5",
    "@angular/platform-browser-dynamic": "^12.2.5",
    "@angular/router": "^12.2.5",
},
  "devDependencies": {
    "@angular-devkit/build-angular": "^12.2.12",
    "@angular-devkit/build-ng-packagr": "~0.1002.0",
    "@angular-eslint/builder": "0.8.0-beta.3",
    "@angular-eslint/eslint-plugin": "0.8.0-beta.3",
    "@angular-eslint/eslint-plugin-template": "0.8.0-beta.3",
    "@angular-eslint/schematics": "^12.6.1",
    "@angular-eslint/template-parser": "0.8.0-beta.3",
    "@angular/cli": "^12.2.5",
    "@angular/compiler-cli": "^12.2.5",
    "@angular/language-service": "^12.2.5",
}
```

### Anything else?

tsconfig.lib.json looks like this -
```
{
    "compilerOptions": {
    "outDir": "../../out-tsc/lib",
    "target": "es2015",
    "module": "es2015",
    "moduleResolution": "node",
    "declaration": true,
    "sourceMap": true,
    "inlineSources": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "types": [],
    "strict": false,
    "lib": [
      "dom",
      "es2015"
    ]
  },
  "angularCompilerOptions": {
    "skipTemplateCodegen": true,
    "strictMetadataEmit": true,
    "fullTemplateTypeCheck": true,
    "strictInjectionParameters": true,
    "flatModuleId": "AUTOGENERATED",
    "flatModuleOutFile": "AUTOGENERATED",
    "enableIvy": true
  }
}
```

And ng-package.json for the secondary endpoint looks like this -
`{
  "$schema": "../../../../node_modules/ng-packagr/ng-package.schema.json",
  "dest": "../../dist/components/editable-grid",
  "lib": {
    "entryFile": "public-api.ts"
  }
}
`
While ng-package.json for the primary endpoint looks like this -
`{
  "$schema": "../../node_modules/ng-packagr/ng-package.schema.json",
  "dest": "../../dist/components",
  "deleteDestPath": false,
  "lib": {
    "entryFile": "src/public_api.ts"
  }
}
`

**Comment by petebacondarwin** [comment] 2021-11-15 14:25
May be related to https://github.com/angular/angular/issues/38876

**Comment by petebacondarwin** [comment] 2021-11-15 14:33
Please can you create a reproduction that we can try to run ourselves?

**Comment by JoostK** [comment] 2021-11-15 16:16
Actually this is a duplicate of #43624.

**Closed by JoostK** 2021-11-15 16:16 UTC
Labels: needs reproduction, comp: compiler, needs clarification
