### ISSUE TITLE
`toSignal` created inside the `computed` crashes

### ISSUE THREAD

**Issue by agroupp** [angular/angular#50465] opened 2023-05-25 12:30 UTC
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

Create the signal with the `computed` function. Inside the `computed` function, convert the observable into a signal with `toSignal` function and return it. Inject the `Injector` and add it to the `toSignal` function. If observable will emit the error, the application will crash with "Writing to signals is not allowed in a `computed` or an `effect` by default.".

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-wsinya?file=src%2Fmain.ts

### Please provide the exception or error you saw

```true
Error: NG0600: Writing to signals is not allowed in a `computed` or an `effect` by default. Use `allowSignalWrites` in the `CreateEffectOptions` to enable this inside effects.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular 16.0.1
```

### Anything else?

I believe the problem is related to the hardcoded flag `consumerAllowSignalWrites` set to false in the `ComputedImpl` class. That is pretty much logical, and I agree that we must not change the signal values in the computation process. However, the conversion of the observable into a signal demands running the method `set` of the `state` signal inside the `toSignal` function, which brings us to writing to the signal.

I don't claim to be right. My conclusions are the result of study of the source code only.

**Comment by JeanMeche** [comment] 2023-05-25 13:40
Hi, this has been discussed in a previous issue: #50192.

**Comment by jessicajaniuk** [comment] 2023-05-25 14:44
Thanks for reporting this issue. However this issue is a duplicate of an existing issue #50192. Please subscribe to that issue for future updates.

**Closed by jessicajaniuk** 2023-05-25 14:44 UTC
