### ISSUE TITLE
Angular2 Http request with empty body

### ISSUE THREAD

**Issue by kirilkalchev** [angular/angular#10692] opened 2016-08-11 16:28 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Right now if you set a the Content-Type header in the request and you leave the body of the request empty angular2 is throwing 'ORIGINAL EXCEPTION: TypeError: Cannot read property 'toString' of null' before even try to make the request.

**Expected/desired behavior**
As far as I know if you have an Content-Type header and an empty request body it is a perfectly valid request. I suppose the correct behaviour is to execute the request. 

**Reproduction of the problem**
You can see the wrong behaviour in this plnkr.
https://plnkr.co/edit/9J1hTVC8W65vLTU3ByhO?p=preview

**What is the expected behavior?**
I expect to be able to load the application if I made a request with Content-Type and without a body with angular2 http module

**What is the motivation / use case for changing the behavior?**
I think it is perfectly valid http request and don't see any value in make them impossible with angular2 http library

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** [all] 
 I have tried with chrome/firefox/safari.

* **Language:** [TypeScript] 
I have just used what plnkr provides for their default angular2 typescript plunk.

**Comment by pkozlowski-opensource** [comment] 2016-08-11 17:01
Duplicate of #10612

**Closed by pkozlowski-opensource** 2016-08-11 17:01 UTC
