### ISSUE TITLE
Default CSS Encapsulation does not prevent bleed out when using /deep/

### ISSUE THREAD

**Issue by zackarychapple** [angular/angular#13724] opened 2016-12-30 20:05 UTC
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Putting styles with a `/deep/` selector bleeds into sibling components.
 
When I have a component on one route with a style of the following:
```
/deep/ app-my-header {
  header {
    background-color: yellow;
  }
}
```

If I then navigate to another component (not a child component) the styles from the sibling route still persist on the `app-my-header`.

**Expected behavior**
Styles should not bleed outside of their component even when using the `/deep/` selector.

**Minimal reproduction of the problem with instructions**
https://github.com/zackarychapple/ng-css-encapsulation

**What is the motivation / use case for changing the behavior?**
We have styles to a header that changes as we navigate through the application, this bleeding causes breaking changes across route events. 

**Please tell us about your environment:**
OSX, IntelliJ, Node

* **Angular version:** 2.0.X
verified in 2.3.1 and 2.4.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
tested in Chrome
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript

**Comment by krassx** [comment] 2016-12-31 03:19
I think you should place your css rules within ':host' block to prevent their leakage. Thus you deckare the context for them.

```
:host {
    /* Your CSS here */
}
```

**Comment by martinmcwhorter** [comment] 2017-01-04 21:59
+1 on :host {} already providing this functionality

**Comment by petebacondarwin** [comment] 2021-01-23 21:29
This is effectively a duplicate of #5059

**Closed by petebacondarwin** 2021-01-23 21:29 UTC
Labels: P4, comp: core, core: CSS encapsulation, freq2: medium, type: bug/fix, workaround2: non-obvious
