### ISSUE TITLE
Output events of components are not checked if they exists on the component

### ISSUE THREAD

**Issue by bgpedersen** [angular/angular#53631] opened 2023-12-19 12:34 UTC
### Which @angular/* package(s) are the source of the bug?

compiler

### Is this a regression?

No

### Description

Outputs events `(someOutputEvent)` of components are not checked if they exists on the component, like it does for Inputs `[someInput]`. This can lead to mistypings of the event names that are hard to debug or other bugs.

Input error that works:
![image](https://github.com/angular/angular/assets/3582953/098b1b4b-db93-4adb-b0e9-9b73e094d3ce)

Output that doesn't exists, but no errors:
![image](https://github.com/angular/angular/assets/3582953/94d744f8-45f5-4ae3-884d-bd6eafc66bbd)

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-xgaa8g?file=src%2Fmain.ts

### Please provide the exception or error you saw

```true
There is no error - but we want to have an error.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.0.3
Node: 18.16.0
Package Manager: npm 9.5.1
OS: win32 x64

Angular: 17.0.4
... animations, common, compiler, compiler-cli, core, elements
... forms, language-service, platform-browser
... platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1700.3
@angular-devkit/build-angular      17.0.3
@angular-devkit/core               17.0.3
@angular-devkit/schematics         17.0.3
@angular/cdk                       17.0.1
@angular/cdk-experimental          17.0.1
@angular/cli                       17.0.3
@angular/material                  17.0.1
@angular/material-moment-adapter   17.0.1
@schematics/angular                17.0.3
rxjs                               7.8.1
typescript                         5.2.2
webpack                            5.89.0
zone.js                            0.14.2
```

**Comment by crisbeto** [comment] 2023-12-19 12:55
This is because it's possible to dispatch arbitrary custom DOM events.

**Comment by e-oz** [comment] 2023-12-19 13:24
It's not a bug for sure and I would not like to have limitations like this. IDE is enough to catch it.

**Comment by bgpedersen** [comment] 2023-12-19 13:59
@crisbeto @e-oz We use VS Code editor - do you have any suggestion on how we can/should catch these then, if we would like to?

**Comment by JoostK** [comment] 2023-12-19 15:40
Closing as duplicate of #43603

**Closed by JoostK** 2023-12-19 15:40 UTC
