### ISSUE TITLE
TypeScript Definition of RouteConfig Shows Error if component's Constructor has > 1 parameter

### ISSUE THREAD

**Issue by johnpapa** [angular/angular#4038] opened 2015-09-08 04:48 UTC
When I have a Component that takes more just RouteParams in its constructor, I get a TypeScript definition error in the editor. The code runs, but the typings file likely needs to be updated. here is my component
![2015-09-08_00-45-07](https://cloud.githubusercontent.com/assets/1202528/9726595/14a1fdb0-55c3-11e5-88da-0052dfcd2727.png)

And here is the red underlines in the RouteConfig.

![2015-09-08_00-44-48](https://cloud.githubusercontent.com/assets/1202528/9726594/121521a8-55c3-11e5-84bc-b3815ee02bed.png)

**Comment by johnpapa** [comment] 2015-09-08 04:48
cc // @wardbell

**Comment by Nemikolh** [comment] 2015-09-08 10:03
I have the same problem and it is due to the fact that the angular definitions of Type is:
```ts
interface Type extends Function {
    new(args: any): any;
}
```
So it restrict the constructor to one argument only. If you replace in `angular.d.ts`, the definition of `Type` by this:
```ts
interface Type extends Function {
    new(...args: any[]): any;
}
```
then you're problem is sovled.

**Comment by Nemikolh** [comment] 2015-09-08 10:23
I just realized that the `Type` interface generated by the build task `docs/typings` on master is correct. So I guess, you can also simply wait for the next alpha release (assuming the definitions update will follow at the same time on DefinitelyTyped).

**Comment by btford** [comment] 2015-09-08 18:39
Duplicate of #3753.

**Closed by btford** 2015-09-08 18:39 UTC
