### ISSUE TITLE
Error navigating to secondary router-outlet from lazy loaded module

### ISSUE THREAD

**Issue by MasDevProject** [angular/angular#39650] opened 2020-11-12 16:04 UTC
# 🐞 bug report

### Affected Package
Angular router

### Is this a regression?
I don't think so

### Description
I'm trying to display at the same time two routes: the primary one and an named router-outlet.
It work using only eager navigation, but with lazy loaded module it breaks.

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-router-auxilary-issue-6djzwp

## 🔥 Exception or Error
The error in described here: https://stackblitz.com/edit/angular-router-auxilary-issue-6djzwp?file=src%2Fapp%2Fhome%2Fhome.module.ts

## 🌍  Your Environment

**Angular Version:**
<pre><code>
I tried on Angular 8, 9, 10
</code></pre>

**Comment by atscott** [comment] 2020-11-16 17:23
This doesn't appear to be related to lazy loading, but rather a duplicate of #10726
https://stackblitz.com/edit/angular-router-auxilary-issue-z3m9we?file=src%2Fapp%2Fapp.module.ts

**Closed by atscott** 2020-11-16 17:23 UTC
Labels: comp: router
