### ISSUE TITLE
ng-animate can not be used to change of route .

### ISSUE THREAD

**Issue by ibufu** [angular/angular#6614] opened 2016-01-21 13:10 UTC
I add class 'ng-animate' to  a component, but when route changed,  ng-enter and ng-leave was not added to the component.

**Comment by zoechi** [comment] 2016-01-21 13:15
I don't think there is an ngAnimate yet.

**Comment by ibufu** [comment] 2016-01-21 13:19
@zoechi 
I have seen the demo and success to run it. But I failed to use it to route.
https://github.com/angular/angular/blob/master/modules/playground/src/animate/animate-app.ts

**Comment by ericmartinezr** [comment] 2016-01-21 13:29
You can use `routerOnActivate` and `routerOnDeactivaite` to achieve this.

**Comment by ibufu** [comment] 2016-01-21 13:39
@ericmartinezr thx,but i have many route components, if I use the method, I should write routerOnActivate and routerOnDeactivaite to each route component.

**Comment by ThiagoT1** [comment] 2016-01-21 13:50
You could try router.subscribe(...)

It fires when navigation occurs.

Thiago

**Comment by ibufu** [comment] 2016-01-21 14:02
@ThiagoT1 thx,but i really think ng-animate should work at route changing.

**Comment by jesperronn** [comment] 2016-02-10 10:39
@ibufu, @ThiagoT1, @ericmartinezr can you point me to a working example, which would be easier for me to understand?

**Comment by sdfacre** [comment] 2016-02-12 09:30
you probably added ng-animate to the content not host.

**Comment by pkozlowski-opensource** [comment] 2016-10-04 11:50
This is duplicate of #9845 and AFAIK this is work in progress.

**Closed by pkozlowski-opensource** 2016-10-04 11:50 UTC
