### ISSUE TITLE
CPU overload when using the Promise in the template

### ISSUE THREAD

**Issue by splincode** [angular/angular#24133] opened 2018-05-25 15:57 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[x] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

```ts
import { Component } from '@angular/core';

@Component({
  selector: 'my-app',
  templateUrl: './app.component.html',
  styleUrls: [ './app.component.css' ]
})
export class AppComponent  {
  name = 'Angular 6';

  public async getFullName() {
    return await this.name;
  }

}
```

```html
<ng-template let-userTemplate
[ngTemplateOutletContext]="{ $implicit: getFullName() }"
[ngTemplateOutlet]="template" #template>
 userTemplate = {{userTemplate}}
</ng-template>
```

Everything freezes and does not work

![image](https://user-images.githubusercontent.com/12021443/40554284-eab6d456-604d-11e8-8817-2018b4906457.png)

in a few minutes (memory leak)

![image](https://user-images.githubusercontent.com/12021443/40555322-5bf4256c-6051-11e8-9887-60ed65165fc1.png)

## Expected behavior
There must be either an adequate error, or else that

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-1bpcep?file=src%2Fapp%2Fapp.component.ts

**Comment by splincode** [comment] 2018-05-25 16:14
If we usage changeDetection: ChangeDetectionStrategy.OnPush

![image](https://user-images.githubusercontent.com/12021443/40554846-bf2c0ce6-604f-11e8-9330-cfbb3e3fc46e.png)

Well, is this a problem Zone.js?

**Comment by trotyl** [comment] 2018-05-25 17:09
It's technically expected, when creating a new promise you scheduled a new microtask, as it's scheduled within Angular zone, a new change detection will be triggered on that microtask, but it then scheduled another new microtask again.

It's never a good idea to perform scheduling inside template execution.

**Comment by splincode** [comment] 2018-05-26 13:41
@trotyl I do understand, this was just for fun, but probably we need to write about this in the style guide..

**Comment by alexeagle** [comment] 2018-05-29 22:59
Could we catch this in the compiler?

**Comment by trotyl** [comment] 2018-05-30 04:40
@alexeagle  Technically it's impossible to tell which expression has a real side-effect.

But should be easy to detect at runtime: set current zone to a special `BlockingTaskZone` before template execution (set it back after), and throw error for whatever microtask/macrotask inside it.

Since not the Angular zone, no further tick will be triggered.

**Comment by trotyl** [comment] 2018-05-30 09:57
For tracking: duplicate of https://github.com/angular/angular/issues/6696

**Comment by JiaLiPassion** [comment] 2018-05-31 21:05
@trotyl , 

> But should be easy to detect at runtime: set current zone to a special BlockingTaskZone before template execution (set it back after), and throw error for whatever microtask/macrotask inside it.

yes, I think it should work, I will try it.

**Closed** 2020-09-09 16:20 UTC
Labels: comp: core, core: change detection, freq1: low, severity1: confusing, type: bug/fix
