### ISSUE TITLE
Ability to call constructors within a template

### ISSUE THREAD

**Issue by axos88** [angular/angular#53792] opened 2024-01-04 09:31 UTC
### Which @angular/* package(s) are relevant/related to the feature request?

compiler, core

### Description

I'd like to be able to do something like:

```
  <button (onClick)="myHandler(new Foo(42))"></button>
```  

### Proposed solution

Support the new keyword in the template language

### Alternatives considered

I tried `Foo.constructor(42)`, `Foo.prototype.constructor(42)`, `Foo.constructor.call(42)`, `Foo.prototype.constructor.call(42)`, but nothing seems to work.

**Comment by axos88** [comment] 2024-01-04 09:32
Related: https://stackoverflow.com/questions/77751881/how-to-call-constructor-from-template/77752065#77752065

**Comment by pkozlowski-opensource** [comment] 2024-01-10 14:57
Currently it is hard to call constructors in the template expressions due to the 2 separate issues:
* the `Foo` symbol is not available in the context against which the template expressions are evaluated - this is tracked in #25963;
* the `new` keyword is not recognized in the Angular expression syntax - we do have an umbrella issue for this in #43485

Long story short: this is a legitimate issue but we are aware of it and tracking it already through #25963 and #43485.

Duplicate of #25963
Duplicate of #43485

**Closed by pkozlowski-opensource** 2024-01-10 14:57 UTC
Labels: area: core
