### ISSUE TITLE
[docs] ViewChild examples aren't shown

### ISSUE THREAD

**Issue by naaajii** [angular/angular#57506] opened 2024-08-23 23:35 UTC
### Describe the problem that you experienced

The examples for [ViewChild](https://angular.dev/api/core/ViewChild?tab=usage-notes) seems to be missing

io:
![image](https://github.com/user-attachments/assets/a31ed93f-e89b-4b4c-a1a9-6234cb2070a3)
adev:
![image](https://github.com/user-attachments/assets/2c04ec68-7da1-482c-b535-d10deb3e7d27)

### Enter the URL of the topic with the problem

https://angular.dev/api/core/ViewChild?tab=usage-notes

**Comment by JeanMeche** [comment] 2024-08-24 18:30
Duplicate of #56068

**Closed by JeanMeche** 2024-08-24 18:30 UTC
