### ISSUE TITLE
Form considered as not valid despites autocompletion

### ISSUE THREAD

**Issue by ssougnez** [angular/angular#12130] opened 2016-10-06 20:46 UTC
**I'm submitting a ...**  (check one with "x")

```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I have a form with a submit button disabled if the form is not valid. This form contains a "username" input and a "password" one. When the page is loaded, these inputs are automatically filled in by Chrome but the button stays disabled (while all input contains valid data).

**Expected behavior**

The button should become enabled when the form is automatically completed by Chrome with valid data.

**Minimal reproduction of the problem with instructions**
- Run [this plunkr](http://plnkr.co/edit/9FrwjhbFaa0y5UMMGHHf)
- Select the option to open the plunkr in a separate window
- If the form is not automatically filled in, fill it in, submit the form, close the window and run the plunkr in a separate window again
- Normally, the form should be automatically filled in by the browser but the button will be grayed out

Note that, even though the button is grayed out, I can click on it to send the form but it's not obvious for the user. 

**What is the motivation / use case for changing the behavior?**

A concrete use case would be to prevent a form to be sent if it's empty. However, the user should be able to send the form if this one is completed automatically by the browser.

**Please tell us about your environment:**

- Windows 10
- PHPStorm
- npm
- Webpack
- Angular 2.0.2
- Chrome 53
- TypeScript 2.0.2
- node 4.4.7

**Comment by DzmitryShylovich** [comment] 2016-10-06 21:43
Can you provide a plunkr with reproduction?

**Comment by ssougnez** [comment] 2016-10-07 12:20
Ji,

I just edited the original post to provide a link to a plunkr. I tried yesterday but it was complicated to reproduce. However, I just discovered the "Launch preview in a separate window" option thanks to which I could reproduce the issue.

Thanks

**Comment by DzmitryShylovich** [comment] 2016-12-04 21:36
Duplicate of https://github.com/angular/angular/issues/12130

**Comment by jasonaden** [comment] 2017-05-15 18:31
Closing as duplicate

**Closed by jasonaden** 2017-05-15 18:31 UTC
Labels: comp: forms, freq2: medium, severity1: confusing, type: bug
