### ISSUE TITLE
The AOT build error info should be more friendly

### ISSUE THREAD

**Issue by bokire** [angular/angular#21164] opened 2017-12-25 11:43 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I'm sorry for my bad English first.
If I miss a component declaration in the module like the png.
![image](https://user-images.githubusercontent.com/4404438/34338999-f8f19788-e9a9-11e7-9f64-66ff465a13b1.png)
Build the work without 'AOT' is successed , but build with command 'ng build --prod --build-optimizer' will be error and the error message is
![image](https://user-images.githubusercontent.com/4404438/34339180-1161afd2-e9ab-11e7-81c1-ff66ceaefe7d.png)
In the message I can't find any useful info about I miss a component declaration in the module.
 
## Environment

<pre><code>
Angular version: 5.0.x

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by trotyl** [comment] 2017-12-25 11:57
Duplicate of #20292 and #20978.

**Closed** 2018-01-02 23:09 UTC
Labels: comp: core & compiler
