### ISSUE TITLE
Validators in template confuse reactive forms validation if *ngIf is used

### ISSUE THREAD

**Issue by Rhobal** [angular/angular#25440] opened 2018-08-11 11:30 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ X ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

I have a reactive form.
To use the "required" validation conditionally, I added `[required] = "condition" ` in the template. This works unless I remove the input with `*ngIf`; according to #7970, it's expected behaviour that the "required" condition is still active even if the input containing the `required` attribute is removed with `*ngIf`.
In this setup, before removing the control with `*ngIf`, the `required` validation reacts to the condition. But if the condition is true when the input is removed, the `required` flag will remain, regardless of condition. The required validation seems to lose the connection to the condition.

## Expected behavior

I suggest adding to the [validation docs](https://angular.io/guide/form-validation#reactive-form-validation) that template validation should not be used in reactive forms, or at least no conditional validation, and if possible, add a warning in dev mode. And there should be a better method to add dynamic validation.

## Minimal reproduction of the problem with instructions

[Stackblitz](https://stackblitz.com/edit/angular-tktzbu)
1. Check  "required": input2 wil become invalid
2. Uncheck "required": input2 will become valid
3. Uncheck "ngIf": Input fields are hidden, input1 remains invalid, to be expected according to #7970
4. Check "ngIf", check "required": input2 wil become invalid
5. Uncheck "ngIf": Input fields are hidden, both remain invalid
6. Check "ngIf", uncheck required: input2 will remain invalid, although it should become valid

## What is the motivation / use case for changing the behavior?

I would like to generate the static validation from the constraints in the swagger model definition. Using `clearValidators()` and `setValidators()` is cumbersome, because I need to know all the static validators when removing the dynamic validator. Thus, I wanted to use the static validators and add dynamic validation in the template.

Currently, I'm using a conditional validator
```typescript
export function conditionalValidator(condFn: (control: AbstractControl) => boolean,
validators: ValidatorFn | ValidatorFn[]): ValidatorFn {
  return (control) => {
    if (!condFn(control)) {
      return null;
    }

    if (!Array.isArray(validators)) {
      return validators(control);
    }

    return validators.map(v => v(control)).reduce((errors, result) =>
      result === null ? errors :
        (Object.assign(errors || {}, result))
    );
  };
}
```
This allows dynamic validation without adding and removing validators, but it doesn't solve the swagger issue as the conditional validator has to be added at the same time when the static validators are defined.

## Environment

<pre><code>
Angular version: 6.1.2

Browser:
- [ X ] Chrome (desktop) version 68
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by JoostK** [comment] 2018-08-11 11:36
Looks like a duplicate of #19081

**Comment by kara** [comment] 2018-08-14 22:43
Yeah, same root issue that needs discussion. Please track in #19081.

**Closed by kara** 2018-08-14 22:43 UTC
Labels: comp: forms
