### ISSUE TITLE
Providers does not work when setting them via bootstrapModule

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [angular/angular#11195] opened 2016-08-31 13:06 UTC
Hello, 

i was trying to specify provider when bootstrapping module like :

`var apieProvider = new ApiProvider();`
`
platformBrowserDynamic().bootstrapModule(SomeModule, {
            providers: [provide(ApiProvider , { useValue: apiProvider })]
        });`

Having :

`@NgModule({
    imports: [BrowserModule],
    bootstrap: [SomeComponent]
})
export class SomeModule{ }`

and get exception that 'No provider ApiProvider found'

but if i mimic provider setup in NgModule by writing it straight to metadata everything works fine: 

`
 ((<any>Reflect).getMetadata('annotations', SomeModule)[0]) .providers.push(provide(ApiProvider , { useValue: this.apieProvider }));
`

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** [all ] 
 
* **Language:** [TypeScript 1.8]

**Comment by pkozlowski-opensource** [comment] 2016-08-31 13:09
Shouldn't it be `provide: ApiProvider, ...` instead of `provide(ApiProvider`? Please provide a plunker as requested in the issue template.

**Comment by vytautas-pranskunas-** [comment] 2016-08-31 13:18
Can you write whole line 

`
.bootstrapModule(SomeModule, { providers: [provide(ApiProvider , { useValue: apiProvider })] })
`

if does not work i will create plunker

**Comment by pkozlowski-opensource** [comment] 2016-08-31 13:21
> i will create plunker

Please do.

**Comment by vytautas-pranskunas-** [comment] 2016-08-31 13:25
So you dont know syntax how providers should be specified correctly? Because i could not find it in your docs . But i found this: https://github.com/angular/angular/issues/8867
tried both ways does not work. Creating plunker takes a bit more time than try correct way. So can you provide correct example of syntax and if does not work i will create plunker.

**Comment by vytautas-pranskunas-** [comment] 2016-08-31 13:28
p.s. for now i have tried three different ways if you know 4th please tell

`
          platformBrowserDynamic().bootstrapModule(TestModule, {
            providers: [{provide: TestApi, useValue: this.testApi}]
        });

         platformBrowserDynamic().bootstrapModule(TestModule, {
            providers: [{provide: TestApi, useValue: this.testApi}]
        });

        platformBrowserDynamic().bootstrapModule(TestModule, {
            providers: [new Provider(TestApi, {useValue: this.testApi})]
        });

`

**Comment by pkozlowski-opensource** [comment] 2016-08-31 13:29
This is the valid syntax: `{ providers: [{ provide: ApiProvider, useValue: apiProvider }]`. Provide a plunker otherwise we can't move forward on this one.

**Comment by vytautas-pranskunas-** [comment] 2016-08-31 13:30
ok

**Comment by vytautas-pranskunas-** [comment] 2016-08-31 13:32
btq: is there any plunker basic setup for RC5?

**Comment by vytautas-pranskunas-** [comment] 2016-08-31 13:48
I have created plunker: http://plnkr.co/edit/T4iA3JgIPWS138tCl2mv

**Comment by alxhub** [comment] 2016-08-31 14:29
Those providers are used to bootstrap the compiler, which compiles all your components. They're not part of the application injector. For that, you need to specify the `providers` in your app module.

**Comment by vytautas-pranskunas-** [comment] 2016-08-31 14:31
So is there any way to add providers to module dynamically, by not hacking metadata?

**Comment by mhevery** [comment] 2016-08-31 16:51
@vytautas-pranskunas- being able to provide providers dynamically would break offline compilation and so it is not supported. A set of providers needs to be know statically. 

Dynamically one can bind a provider to a factory and then one has a freedom to create any value for that provider. This should be sufficient.

Having the ability to dynamically add a provider (which was not present during static analysis) is strange as each provider needs both the configuration, and site where it is injected (the user). So adding one without the other is not useful. 

Closing as this is working as intended.

**Closed by mhevery** 2016-08-31 16:51 UTC
Labels: need: repro

**Comment by christiantoms** [comment] 2016-08-31 20:23
@mhevery I think @vytautas-pranskunas- is asking a slightly different question. Let's say that we have some data we need to retrieve from a REST API at the beginning of our application, and we have some services that rely on that information (maybe the ng service needs a baseurl provided by the rest service or something similar), how could that be done? Is there a way to do something like this: 

`http.get('api.com/config').subscribe((config)=>{platformBrowserDynamic().bootstrapModule(AppModule, { providers: { provider: 'config', useValue: config } } );});`

We don't need to provide different providers dynamically during the lifecycle of the application, but some of our services might rely on information that needs to be available prior to the application bootstrapping.

**Comment by alxhub** [comment] 2016-08-31 20:30
@christiantoms, @mhevery answered that question if you read carefully :)

Here's how it's done:

```
@NgModule({
 ...
 providers: [{provide: 'config', useFactory: () => window['myConfig']}],
})
export class MyAppModule {}
```

Then to bootstrap:
```
fetch('/config.json').then(resp => resp.json()).then(config => {
  window['myConfig'] = config;
  platformBrowserDynamic().bootstrapModule(AppModule);
})
```

This keeps both Angular and you happy :) The AOT compiler knows that 'config' will be provided and can call the factory function during bootstrapping to get a value for it. At bootstrap time that value will already have been set up ready to read.

**Comment by zoechi** [comment] 2016-09-01 05:16
@alxhub wouldn't be `APP_INITIALIZER` the preferred way like explained in https://github.com/angular/angular/issues/9047#issuecomment-224075188

**Comment by vytautas-pranskunas-** [comment] 2016-09-01 06:21
Disadvantage of this approach is that you have to store in some place (e.g. window) before you can access it. In my case it is better to push straight to metadata.

**Comment by offnertho** [comment] 2016-09-13 08:35
Hi, 

The "APP_INITIALIZER" approach, seems not to be working for me, because i need a backend config value, before the bootstrapping completes. 

The solution provided by @alxhub works fine tough. With the exception that i get an error: 
"Cannot find name 'fetch'"

Do i need an import here?

Regards

**Comment by zoechi** [comment] 2016-09-13 16:38
@offnertho, @vytautas-pranskunas-  you can store the value in a service. No need to use `window`
http://stackoverflow.com/questions/37611549/how-to-pass-parameters-rendered-from-backend-to-angular2-bootstrap-method/37611614#37611614

**Comment by offnertho** [comment] 2016-09-13 16:50
@zoechi thanks your your reply. 

Unfortunately that example didn't work out for me, because i needed a value loaded from the config service during the bootstrapping of the AppComponent. 

It seemed that the bootstrapping completed, before the "config.json" go loaded from the server.

**Comment by zoechi** [comment] 2016-09-13 19:11
@offnertho sounds there is something wrong with the promise or observable returned from the factory function. It probably completes before the data is loaded.

**Comment by d-kostov-dev** [comment] 2016-09-19 15:09
Here is how i did it without using window:

```
export const AppModule = (settings: ServerSettings) => {
    @NgModule({
        imports: [
          ...
        ],
        declarations: [AppComponent],
        providers: [
            {
                provide: ServerSettings,
                useValue: settings,
            },
        ],
        bootstrap: [AppComponent]
    })

    class AppModule { }

    return AppModule;
}
```
and

```
// ... Some code to get the settings
platformBrowserDynamic().bootstrapModule(AppModule(settings));
```

then it's injectable anywhere

```
@Injectable()
export class AppConfig {
    constructor(private serverSettings: ServerSettings) {
        console.log("Server Settings", this.serverSettings);
    }
}
```

**Comment by odolha** [comment] 2018-02-27 08:06
The above is what I tried and seems to (no longer?) work because of:

`ERROR in Error: Tried to find bootstrap code, but could not. Specify either statically analyzable bootstrap code or pass in an entryModule to the plugins options.`
