### ISSUE TITLE
Local Variable cannot be camelCased

### ISSUE THREAD

**Issue by anandgupta08** [angular/angular#3398] opened 2015-07-30 16:57 UTC
If i name a local variable using camelCasing (e.g. #sizeHandler) and then use that local variable in another element, then angular throws an error. Is this expected? Is there a reason why the variable name cannot be camelCased.
e.g.

![image](https://cloud.githubusercontent.com/assets/12773087/8989151/f078dbd0-371c-11e5-9176-02fb2e23a750.png)

throws an error as below:

![image](https://cloud.githubusercontent.com/assets/12773087/8989071/74697dc4-371c-11e5-87b8-0b91cabf5183.png)

However, if i just change the variable name as lowercase (e.g. #sizehandler), as below, then things work fine without any error:

![image](https://cloud.githubusercontent.com/assets/12773087/8989178/2067cd4c-371d-11e5-946d-25c4df1b0121.png)

Also, if were simply declaring the local variable with camelCasing but not using it any other component or DOM element, then there is no error. The error seems to occur only when a change detection happens and the variable is attempted to be evaluated during change detection.
If camelCasing should not be used for variable naming, then the behavior should be consistent in all situations (i.e. angular should complain about the incorrect variable name when angular is loaded initially and / or this local variable naming rules should be documented - perhaps it is already , in which case please redirect me to the documentation). 
Personally, i would like the variable naming to allow camelCasing as it is quite common to have camelCased variable names in programming world - at least it is allowed even if not considered as best practice in some languages.

**Comment by pkozlowski-opensource** [comment] 2015-07-30 17:05
It is a browser that lower-cases HTML attributes before Angular can do anything about it. This makes sense since HTML is not case-sensitive and not case-preserving.

To work-around this we've got convention in place: you can declare variables with mixed-case like this: `<input #size-handler>`

**Comment by pkozlowski-opensource** [comment] 2015-07-30 17:07
I'm not sure we can do much more about this one, since we can't guess if a user wanted to use foobar or fooBar - a browser simply removes this info. And looking at the error message it is actually saying exactly what is happening...

I know it might be confusing but we don't have a great technical solution here....

**Comment by matanlurey** [comment] 2015-07-30 18:07
Theoretically the ProtoView compiler could convert camelCase to camel_case, but that's probably too much magic for most.

**Comment by mhevery** [comment] 2015-08-06 19:05
@matanlurey by the time angular gets a hold of DOM all attributes are lowercased. :-( So we can't do anything. 

Closing, since working as intended.

**Closed by mhevery** 2015-08-06 19:05 UTC
