### ISSUE TITLE
i18n with Angular Universal

### ISSUE THREAD

**Issue by mferuscomelo** [angular/angular#40856] opened 2021-02-15 15:47 UTC
# 📚 Docs or angular.io bug report

### Description

I'd like to implement i18n in my Angular Universal app, but am running into errors since the documentation doesn't cover SSR. If I run `npm run build:ssr`, the app builds without issue, but when I run `npm run serve:ssr`, I get the error `Error: Failed to lookup view "index" in views directory "C:\PATH_TO_PROJECT\dist\browser"`.

### What's the affected URL?**
https://angular.io/guide/i18n#configuring-servers

## 🔥 Exception or Error
<pre><code>
Error: Failed to lookup view "index" in views directory "C:\PATH_TO_PROJECT\dist\browser"
</code></pre>

**Comment by petebacondarwin** [comment] 2021-02-15 19:48
I am told that this is really a duplicate of https://github.com/angular/universal/issues/1454, and that since there is no documentation of Universal in angular.io, there is no point in keeping this issue open here.

**Closed by petebacondarwin** 2021-02-15 19:48 UTC
Labels: comp: i18n, comp: server
