### ISSUE TITLE
HttpClient package does not export HttpParamsOptions

### ISSUE THREAD

**Issue by wardbell** [angular/angular#22013] opened 2018-02-04 01:04 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Is there some reason that `HttpParamsOptions` is not exported at the package level? 

It is an exported interface in https://github.com/angular/angular/blob/5.2.3/packages/common/http/src/params.ts#L77

But it is not re-exported from the package root so this is an error:
```
import { HttpParamsOptions } from '@angular/common/http';
```

## Expected behavior
Expect that import to work

## Minimal reproduction of the problem with instructions
Try it yourself

## What is the motivation / use case for changing the behavior?
Be able to write a wrapper method like this

```javascript
  getWithQuery(queryParams: QueryParams | string ): Observable<T[]> {
    const qParams = typeof queryParams === 'string' ? { fromString: queryParams } : { fromObject: queryParams };
    const params = new HttpParams(qParams);
    return this.execute('GET', this.entitiesUrl, undefined, { params });
  }
```
## Environment

<pre><code>
Angular version: ^5.0.0 and current master
</code></pre>

**Comment by Toxicable** [comment] 2018-02-04 01:28
fixed by https://github.com/angular/angular/pull/20332

**Comment by gkalpak** [comment] 2018-02-05 11:45
Duplicate of #20276.

**Closed by gkalpak** 2018-02-05 11:45 UTC
