### ISSUE TITLE
Minificated version of angular2-all.umd is broken

### ISSUE THREAD

**Issue by vagran** [angular/angular#7204] opened 2016-02-20 19:24 UTC
See this example (derived from simple form example):
http://plnkr.co/edit/TyLCDmO5LNYOkflxu2eY?p=preview

It works until you change a line in index.html
`<script src="https://code.angularjs.org/2.0.0-beta.6/angular2-all.umd.js"></script>`
to
`<script src="https://code.angularjs.org/2.0.0-beta.6/angular2-all.umd.min.js"></script>`

When changed, the form is not working anymore. Exception is thrown:

> TypeError: Cannot read property 'subscribe' of undefined

**Comment by ffMathy** [comment] 2016-02-23 18:58
Duplicate of #6380?

**Comment by IgorMinar** [comment] 2016-03-30 04:53
yup. this is a dupe. please see my assessment of the issue: https://github.com/angular/angular/issues/6380#issuecomment-203247147

**Closed by IgorMinar** 2016-03-30 04:53 UTC

**Comment by DrewynV** [comment] 2016-04-05 00:31
__________________________________

Hi! We just wanted to let you know we receievd your email. Thank you for submitting your request. Our aim is to get back to you within 24 hours at the latest. If you have any additional information to add to your request, please reply to this email.


Also please visit our knowledgebase (http://www.support.magicdust.com.au) to browse for further info, we are adding to it all the time.

Or here is our industry report about the 11 Essentials for a Successful Website (http://www.magicdust.com.au/web-design/.

We look forward to helping you succeed online.

Thanks

The Team @ Magicdust Digital

http://support.magicdust.com.au/

Ph (02) 9979 7474
M-F | 9 am-5:00 pm AEST (AEDT in Summer) excluding Public Holidays

------------------------------------------------------------------------------------------------------------
This message was sent to  reply@reply.github.com in reference to Case #166557.
------------------------------------------------------------------------------------------------------------


[[1fa180f2312bbc755e616e885b0c57a573a9f3a3-673074304]]
