### ISSUE TITLE
Ivy doesn't allow @Input() called "style" to be set from template using a static value

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#39580] opened 2020-11-05 19:29 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/core

### Is this a regression?

Yes, this behavior worked as expected under View Engine.

### Description

Initializing an `@Input()` called `style` using a static value from a template doesn't work under Ivy. The provided value is never used to set the input.

This bug could be causing silent failures because it almost never results in a runtime error and most tests don't directly test the input initialization.

Relevant code snippets:

Input definition:
```ts
export class HelloComponent {
  @Input() style: string;
```

Input initialization:
```html
<hello style="new value">
```

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-ivy-ojvdl8?file=src%2Fapp%2Fapp.component.html

## 🌍  Your Environment

**Angular Version:**
<pre><code>
v11.0.0-rc.2 and older with Ivy enabled

</code></pre>

## Additional info
- There are several dozens 1P and 3P components that use the `style` name for inputs, but it's unclear how frequently they are being initialized using a static value.
- At least one application google3 is broken due to this issue.
- Inputs called `class` are not affected by this issue and work as expected.

**Comment by mhevery** [comment] 2020-11-05 21:54
I think this works as intended. We could add better error messages?

The issue is that `<hello style="new value">` is not a valid style and therefore it can't be parsed resulting in blank value. Try `<hello style="color: blue">` to see that it works if style is parsable.

One could argue that we could make an exception here and make it work, but we would only be pushing the problem down the line as: `<hello style="new value" [style.color]="'red'">` would now fail, is there is no reasonable way to merge `new value` with `color: red`.

**Comment by the-mgi** [comment] 2020-11-13 14:21
I am guessing that you want to set the style dynamically from parent **at the time of creation** of ```HelloComponent```
first you need to write it like ```<hello [style]="'background-color: white'">``` this for property binding. Then you need to add a local reference on the ```HelloComponent``` html file,  element on which you want to apply styles. Then in the typescript file add ```@ViewChild('localReference') ref: ElementRef```. Add a private object in the constructor(private renderer: Renderer2) {} like this. then in ```ngOnInit``` write ```this.renderer.setStyle(this.ref, this.style.split(':')[0], this.style.split(':')[1].trim()) this will get the job done.
Hope it helps!!!

**Comment by iRealNirmal** [comment] 2021-05-03 15:21
@mhevery if we are not going to cover, can we close this ?

**Closed** 2022-02-11 00:09 UTC
Labels: comp: core, engine: ivy, core: stylesheets, P2
