### ISSUE TITLE
Reactive form not cleaning up correctly when navigating to a lazy loaded route

### ISSUE THREAD

**Issue by PackBjamin** [angular/angular#41786] opened 2021-04-23 14:41 UTC
Formerly working reactive page control encountered errors when navigating away from the below page using Router.navigate(). The below error surfaced upon changing some routes to use lazy loading and updating packages, including from Angular 11.2.7 to 11.2.11.

Stack trace:
```bash
TypeError: control._registerOnCollectionChange is not a function
    at cleanUpControl (http://localhost:4200/main.js:13163:17)
    at FormControlDirective.ngOnDestroy (http://localhost:4200/main.js:16651:13)
    at executeOnDestroys (http://localhost:4200/main.js:160986:28)
    at cleanUpView (http://localhost:4200/main.js:160899:9)
    at destroyViewTree (http://localhost:4200/main.js:160725:21)
    at destroyLView (http://localhost:4200/main.js:160877:9)
    at RootViewRef.destroy (http://localhost:4200/main.js:176182:9)
    at ComponentRef$1.destroy (http://localhost:4200/main.js:178725:23)
    at RouterOutlet.deactivate (http://localhost:4200/main.js:243645:28)
    at ActivateRoutes.deactivateRouteAndOutlet (http://localhost:4200/main.js:240410:28)
```

The erroring code is within the form.js function cleanUpControl(control, dir, validateControlPresenceOnChange). Normally, the passed in control parameter is a control. However in the error state, a string containing the control's name is passed in instead. This causes the subsequent block to error:
```javascript
  if (control) {
      dir._invokeOnDestroyCallbacks();
      control._registerOnCollectionChange(function () { });
  }
```

This can be bypassed by wrapping the offending line of code with an if block verifying the _registerOnCollectionChange method exists. Of course the band aid solution doesn't address the root problem.

The offending passed in control is the below mat-form-field "runStartDate".
```html
  <div *ngFor="let run of runsFormArray.controls; let i = index" [formGroupName]="i">
    <span [formGroup]="run">
      <!-- Start Date -->
      <mat-form-field formControl="runStartDate" [style.width.px]=130>
        <input [matDatepicker]="runStartDatePicker_i"
               formControlName="startDate"
               placeholder="Run Start Date"
               matInput
               (dateInput)="onRunStartDatePickerChange($event, i)"
               (dateChange)="onRunStartDatePickerChange($event, i)">
        <mat-datepicker-toggle [for]="runStartDatePicker_i" matSuffix></mat-datepicker-toggle>
        <mat-datepicker #runStartDatePicker_i></mat-datepicker>
      </mat-form-field>
...
    </span>
  </div>
```

**Comment by AndrewKushnir** [comment] 2021-04-23 15:32
@PackBjamin thanks for reporting the issue. Could you please provide a [Stackblitz](https://stackblitz.com/) repro, so that we can investigate the issue further? Also, could you please try to downgrade the `@angular/forms` back to `11.2.7` version (while keeping other packages at the newer version) to see if the problem still exists (so we can better understand which version introduced the issue)?

**Comment by PackBjamin** [comment] 2021-04-23 17:23
Downgraded @angular packages to 11.2.7, with no discernable effect. I'm not in a place at the moment to create a reproducing Stackblitz, but will try to carve some time in the upcoming week.

**Comment by AndrewKushnir** [comment] 2021-04-23 17:33
@PackBjamin thanks for the update. So it looks like the problem is in some different (non-Angular) packages? May be try to switch other packages to previous versions (to a state when the problem didn't happen) to find which package (and which version) is causing the problem.

**Comment by PackBjamin** [comment] 2021-04-23 19:03
I reverted the previous version of package.json. No change or improvement. By elimination, changing routes to lazy loading appears to be the causative factor. I'm not sure how that would impact garbage collection or cleanup.

**Comment by PackBjamin** [comment] 2021-04-23 19:07
I reverted to the previous version of package.json. No change or improvement. By elimination, changing routes to use lazy loading remains as the causitive factor.

**Comment by AndrewKushnir** [comment] 2021-04-23 21:52
I've looked at the provided code once again and the following part might be related (based on the error stacktrace):
```
<mat-form-field formControl="runStartDate">
```
Could you please check whether the `runStartDate` has the right type (i.e. `FormControl`)?

If the type is correct and the problem still exists, we'd need a repro using [Stackblitz](https://stackblitz.com/), so we can investigate it further.

**Comment by Airblader** [comment] 2021-04-23 22:03
> Could you please check whether the runStartDate has the right type (i.e. FormControl)?

Thst shouldn't be necessary. The snippet you provided sets a string value, it doesn't bind an object.

**Comment by PackBjamin** [comment] 2021-04-26 15:36
No compilation errors. Once I reverted package.json, the only change to the (previously working) code base is migrating to lazy loaded routes.

Here's the FormBuilder code:
```javascript
 private _createForm(tracking: Tracking): void {
   this.trackingFormGroup = this._formBuilder.group({
     name: [tracking.name],
     projectedStartDate: [tracking.projectedStartDate || new Date(), Validators.required],
     startDate: [tracking.startDate],
     fieldContact: [tracking.fieldContact],
     pigType: [tracking.pigType],
     product: [tracking.product],
     purchasingCompanyWorkNumber: [tracking.purchasingCompanyWorkNumber],
     servicingCompanyWorkNumber: [tracking.servicingCompanyWorkNumber],
     workState: [tracking.workState]
   });

   // Runs
   this.runsFormGroup = this._formBuilder.group({
     runs: new FormArray([])
   });
   this.runsFormArray = this.runsFormGroup.controls.runs as FormArray;
   for (const run of tracking.runs) {
     this.runsFormArray.push(this._formBuilder.group({
       startDate: [run.startDate, Validators.required],
       startTime: [formatDate(run.startDate, 'shortTime', 'en'), Validators.required]
     }));
   }

   this.formGroup = this._formBuilder.group({
     trackingFormGroup: this.trackingFormGroup,
     runsFormGroup: this.runsFormGroup
   });
 }
```

**Comment by AndrewKushnir** [comment] 2021-04-27 23:36
@PackBjamin thanks for additional information. I don't see any issues in the code that you've shared and we'd need a repro (using https://stackblitz.com/) so that we investigate the issue further.

**Comment by mittalshubham093gmailcom** [comment] 2021-05-25 14:34
Hi @PackBjamin ,

I found that while looping formArray inside html page, you gave [formGroupName]="i" , so it's not required to give [formGroup] again .
Please try with this:-
<div *ngFor="let run of runsFormArray.controls; let i = index" [formGroupName]="i">
    <span [formGroup]="run">
 
      <mat-form-field formControl="runStartDate" [style.width.px]=130>
        <input [matDatepicker]="runStartDatePicker_i"
               formControlName="startDate"
               placeholder="Run Start Date"
               matInput
               (dateInput)="onRunStartDatePickerChange($event, i)"
               (dateChange)="onRunStartDatePickerChange($event, i)">
        <mat-datepicker-toggle [for]="runStartDatePicker_i" matSuffix></mat-datepicker-toggle>
        <mat-datepicker #runStartDatePicker_i></mat-datepicker>
      </mat-form-field>
...
  </div>
  
  Please give access of the private repo it will be helpful to check the issue or give the sample link of slackbiltz.

**Comment by AndrewKushnir** [comment] 2021-05-25 16:17
Closing this ticket for now since there is no repro, thus we can not perform further investigation. Please reopen or create a new ticket once repro is available.

**Closed by AndrewKushnir** 2021-05-25 16:17 UTC
Labels: comp: forms, needs reproduction
