### ISSUE TITLE
Production Unit Tests Intermittently Fail In afterAll with Uncaught [object Object]

### ISSUE THREAD

**Issue by jkyoutsey** [angular/angular#33800] opened 2019-11-13 16:36 UTC
# 🐞 bug report

### Affected Package
ng test --prod

### Is this a regression?
No?

### Description

Intermittently we are seeing *different* unit tests fail on production configuration test runs. 
WallabyJS does not fail (it doesn't run production configuration).
`ng test` does not fail.
`ng test --prod` does fail intermittently on random tests.
It seems to never be the same test.
I can't find anything common between the tests or the objects under test. Sometimes a service, sometimes a component.

## 🔬 Minimal Reproduction

There is no way to consistently reproduce an intermittent error that is happening in random unit tests.

## 🔥 Exception or Error
This is output from the TeamCity reporter:
<pre><code>
HeadlessChrome 78.0.3904 (Mac OS X 10.14.6) ERROR
  {
    "message": "An error was thrown in afterAll\nUncaught [object Object] thrown",
    "str": "An error was thrown in afterAll\nUncaught [object Object] thrown"
  }
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.0.2
Node: 10.16.0
OS: darwin x64
Angular: 8.0.0
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.2
@angular-devkit/build-angular     0.800.2
@angular-devkit/build-optimizer   0.800.2
@angular-devkit/build-webpack     0.800.2
@angular-devkit/core              7.3.6
@angular-devkit/schematics        8.0.2
@angular/cdk                      8.0.1
@angular/cli                      8.0.2
@angular/material                 8.0.1
@angular/pwa                      0.801.1
@angular/service-worker           8.1.1
@ngtools/webpack                  8.0.2
@schematics/angular               8.0.2
@schematics/update                0.800.2
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.30.0
</code></pre>

**Anything else relevant?**
This is happening locally as well as on our build agents.

```
{
  "name": "my-med-study",
  "version": "0.0.0",
  "license": "UNLICENSED",
  "private": true,
  "scripts": {
    "cypress:run": "cypress run --reporter teamcity",
    "cypress:open": "./node_modules/.bin/cypress open",
    "ng": "ng",
    "ng-high-memory": "node --max_old_space_size=8000 ./node_modules/@angular/cli/bin/ng",
    "start": "ng serve",
    "start:local": "ng serve -o --proxy-config proxy.conf.local.json",
    "start:remote:ie": "ng serve --configuration es5 --host JKYMacbookProWork.local --port 4201 --disable-host-check",
    "start:remote": "ng serve --host JKYMacbookProWork.local --port 4201 --disable-host-check",
    "build:devdeploy": "ng build --configuration devdeploy",
    "build:staging": "ng build --configuration staging",
    "build:prod": "ng build --configuration production",
    "test": "ng test",
    "test:prod": "ng test --prod --watch false --code-coverage",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "e2e:local": "npm run e2e -- --configuration=local",
    "e2e:local:api": "npm run e2e -- --configuration=localApi",
    "mocked": "ng serve --configuration mastermock",
    "ci:serve": "ng build --prod && http-server dist -p 4200",
    "cypress:ci": "start-server-and-test ci:serve http://localhost:4200 cypress:run"
  },
  "dependencies": {
    "@angular-devkit/core": "^7.3.6",
    "@angular/animations": "^8.0.0",
    "@angular/cdk": "~8.0.1",
    "@angular/common": "^8.0.0",
    "@angular/compiler": "^8.0.0",
    "@angular/core": "^8.0.0",
    "@angular/forms": "^8.0.0",
    "@angular/material": "~8.0.1",
    "@angular/platform-browser": "^8.0.0",
    "@angular/platform-browser-dynamic": "^8.0.0",
    "@angular/router": "^8.0.0",
    "@angular/pwa": "^0.801.1",
    "@angular/service-worker": "^8.0.0",
    "@ngrx/effects": "^8.4.0",
    "@ngrx/entity": "^8.4.0",
    "@ngrx/store": "^8.4.0",
    "@ngrx/store-devtools": "^8.4.0",
    "@types/hammerjs": "^2.0.36",
    "blob-util": "^2.0.2",
    "configcat-js": "1.1.x",
    "core-js": "^2.6.1",
    "hammerjs": "^2.0.8",
    "http-server": "^0.11.1",
    "lodash": "^4.17.11",
    "moment": "^2.23.0",
    "ng2-dragula": "^2.1.1",
    "ngx-cookie-service": "^2.2.0",
    "ngx-infinite-scroll": "^7.0.1",
    "reflect-metadata": "^0.1.12",
    "rxjs": "^6.5.2",
    "subsink": "^1.0.0",
    "tslib": "^1.9.3",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.800.0",
    "@angular/cli": "^8.0.2",
    "@angular/compiler-cli": "^8.0.0",
    "@angular/language-service": "^8.0.0",
    "@netbasal/spectator": "^3.1.3",
    "@ngrx/schematics": "^7.0.0",
    "@types/jasmine": "~3.3.5",
    "@types/jasminewd2": "~2.0.6",
    "@types/lodash": "^4.14.119",
    "@types/node": "~10.10.1",
    "angular2-template-loader": "^0.6.2",
    "codelyzer": "^5.0.1",
    "cypress": "^3.3.1",
    "cypress-file-upload": "^3.1.2",
    "cypress-teamcity-reporter": "^2.6.1",
    "jasmine-core": "~3.3.0",
    "jasmine-marbles": "^0.5.0",
    "jasmine-reporters": "^2.3.2",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~3.1.4",
    "karma-chrome-launcher": "~2.2.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^2.0.4",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "karma-teamcity-reporter": "^1.1.0",
    "lint-staged": "^8.1.4",
    "ng-mocks": "^8.0.0",
    "ngx-spec": "^1.0.1",
    "prettier": "^1.18.2",
    "protractor": "~5.4.2",
    "protractor-fail-fast": "^3.1.0",
    "start-server-and-test": "^1.9.1",
    "ts-node": "~7.0.1",
    "tslint": "~5.12.0",
    "tslint-defocus": "^2.0.6",
    "typescript": "~3.4.0",
    "wallaby-webpack": "^3.9.13"
  }
}
```

Test config from angular.json:
```
				"test": {
					"builder": "@angular-devkit/build-angular:karma",
					"options": {
						"main": "src/test.ts",
						"polyfills": "src/polyfills.ts",
						"tsConfig": "src/tsconfig.spec.json",
						"karmaConfig": "src/karma.conf.js",
						"styles": ["src/styles.scss"],
						"scripts": [],
						"assets": ["src/favicon.ico", "src/assets", "src/web.config", "src/manifest.json"],
						"codeCoverageExclude": ["**/*.mock.ts", "**/*.module.ts"],
						"fileReplacements": [
							{
								"replace": "src/environments/environment.ts",
								"with": "src/environments/DO_NOT_IMPORT.ENVIRONMENT.UNITTESTING.ts"
							}
						]
					},
					"configurations": {
						"production": {
							"karmaConfig": "src/karma.conf.prod.js"
						}
					}
				},
```

**Comment by JiaLiPassion** [comment] 2019-11-15 00:39
could you provide a reproduce repo?

**Comment by IgorMinar** [comment] 2019-11-19 06:51
it's odd that you are trying to run the unit tests with `--prod`. What's the goal of that?

Often unit tests depend on availability of debugging information which is stripped away or disabled via `--prod` so I don't think that we will ever be able to run unit tests after prod optimizations reliably.

**Comment by jkyoutsey** [comment] 2019-11-19 15:16
@IgorMinar  that’s interesting as I’ve been doing this in CI for years now. And it’s consistently working very well. However whatever was causing this issue seems to have disappeared. So I’m just going to close this as a fluke.

**Comment by jkyoutsey** [comment] 2019-11-22 20:39
I'm re-opening this because this happens even with non-prod builds.
ng test --watch false --code-coverage is generating this error with or without the --prod flag.
I can't repro a completely random test failing in a large system with > 300 tests.
I'm open to other ways to provide more info if at all possible.

**Comment by FDIM** [comment] 2019-12-06 20:19
@jkyoutsey I'd recommend to run the test in standard chrome and not headless so that you could inspect output console. I am 99% sure that you'll find why it breaks. I'd argue that this should be best practice when writing unit tests.

From personal experience, most of the time I see these kind of errors when it happens in async path when something is not mocked and standard javascript error is not handled

**Comment by ylixir** [comment] 2020-01-27 16:33
We are having this issue as well, however it _only_ happens in headless. I can not get it to pop when using regular chrome. It will occasionally pass all tests in headless, but probably 75% of the time it gives the `afterAll` error on a random test

**Comment by aaltotsky** [comment] 2020-05-05 17:46
I have the same issue. Tests sometimes failed with afterAll error. I have automated headless tests using GitHub Action. The same code-base may pass or fail. The example:
https://github.com/RenetConsulting/angularcore.net/runs/644967831?check_suite_focus=true ( Test ngx-utils-demo with npm) fails. But the same code-base run https://github.com/RenetConsulting/angularcore.net/runs/644971870?check_suite_focus=true successfully completed. The https://github.com/RenetConsulting/angularcore.net/ repository is public. 
My problem: I have a lot of tests and the ChromeHeadless does not output many details.
Any help here will be appreciated.

**Comment by aaltotsky** [comment] 2020-05-05 18:36
Good news. First, I found the failed set of tests by counting in the projects ("projects" tag) in the angular.json file. Second, I fixed the random execution order with the following code in karma.conf.js
`client: {
      jasmine: {
        random: false // Don't run tests in random order
      }
    },`

Finally, I count the test (when it successfully run) to locate the test that is failing. And here my fail test (.\Services\ngx-utils-demo\projects\external-auth\src\lib\external-token-handler.service.spec.ts):
`        it('error', () => {
            const error = { error: state };
            authService.getToken.and.returnValue(throwError(error));
            service.handle(access_token, state).subscribe();
            expect(authService.getToken).toHaveBeenCalledWith(token);
            expect(tokenService.setToken).not.toHaveBeenCalled();
        });`

**Comment by aaltotsky** [comment] 2020-05-06 04:36
I found a solution. I changed code to the following:
`
        it('error', () => {
            const error = { error: state };
            authService.getToken.and.returnValue(throwError(error));

            service.handle(access_token, state).subscribe(
                () => fail('should have failed with error'),
                () => {
                    expect(authService.getToken).toHaveBeenCalledWith(token);
                    expect(tokenService.setToken).not.toHaveBeenCalled();
                }
            );
        });
`
No more "An error was thrown in afterAll" error.

**Comment by FDIM** [comment] 2020-05-06 07:51
Just a tip, if you ever subscribe to an observable or use promises - always, always use done param provided by jasmine to an `it` 
Think about it, if your source never resolves or emits a value, the test will pass :)

I usually pass `done.fail` as an error handler

**Comment by aaltotsky** [comment] 2020-05-07 01:49
@FDIM : Would you share a sample of your code?

**Comment by shravansofts** [comment] 2020-06-17 05:05
We are also facing this issue(below) at random places. There is no proper error why and where?

Chrome 83.0.4103 (Windows 10.0.0) ERROR
  An error was thrown in afterAll
  [object Object] thrown
Chrome 83.0.4103 (Windows 10.0.0) ERROR
  An error was thrown in afterAll
  [object Object] thrown

**Comment by FDIM** [comment] 2020-06-17 15:43
@shravansofts I'd advise you to run entire suite locally in regular chrome (not headless) and see dev tools console. I am 99.9% sure you will see an error there and it will have nothing to do with angular.
Personally such errors immediately suggest that some spec is not mocking properly and not using 'done' function param provided by jasmine.

**Comment by JiaLiPassion** [comment] 2020-06-18 15:51
If anyone can provide a reproduce repo, I would like to research into it, thanks.

**Comment by AndrewKushnir** [comment] 2021-01-12 19:30
Closing this ticket due to the lack of repro.

**Closed by AndrewKushnir** 2021-01-12 19:30 UTC
Labels: comp: testing, needs clarification, needs reproduction
