### ISSUE TITLE
[ngClass] object notation causes Object Expected error in IE11 breaking the app.

### ISSUE THREAD

**Issue by rondog** [angular/angular#36817] opened 2020-04-27 16:58 UTC
# 🐞 bug report

> Note: This bug report is specifically for IE11.

### Affected Package
I believe it would be @angular/core? It would be whatever handles transpiling for ES5. I am using 8.2.14 at the moment.

### Is this a regression?
I don't know as this is the first version I have used.

### Description
If I use the object notation on an element using [ngClass] like so:

`<ul [ngClass]="{'hidden': activeLoc}">`

`activeLoc` is a number in my case. In some cases it is undefined.

IE 11 reports a very vague error saying `Object expected` and after I dug around in the stack trace it pointed to this function in vendor-es5.js on line 82596 (I know that line number will be different for other folk). This error causes the rest of the application not to work by the way.

```
    function iterateListLike$1(obj, fn) {
      if (Array.isArray(obj)) {
        for (var i = 0; i < obj.length; i++) {
          fn(obj[i]);
        }
      } else {
        /** @type {?} */
        var iterator = obj[getSymbolIterator()]();
        /** @type {?} */

        var item;

        while (!(item = iterator.next()).done) {
          fn(item.value);
        }
      }
    }
```
I ended up adding a console log in this vendor file to see what `obj` was and the stack trace in IE11 was an object with a 'hidden': undefined property in it. The fix for me was to use a ternary function. After I did this and rebuilt, the error went away in IE 11.

`<ul [ngClass]="(activeLoc) ? 'hidden' : ''">`

## 🔥 Exception or Error
<pre><code>
ERROR TypeError: Object expected
</code></pre>

Then after expanding the stack says:
<pre><code>
TypeError: Object expected at iterateListLike$1 on line 82596
</code></pre>

## 🌍  Your Environment
```
Angular CLI: 8.3.25
Node: 12.4.0
OS: darwin x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, elements
... forms, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.25
@angular-devkit/build-angular     0.803.25
@angular-devkit/build-optimizer   0.803.25
@angular-devkit/build-webpack     0.803.25
@angular-devkit/core              8.3.25
@angular-devkit/schematics        8.3.25
@angular/cli                      8.3.25
@ngtools/webpack                  8.3.25
@schematics/angular               8.3.25
@schematics/update                0.803.25
rxjs                              6.5.4
typescript                        3.5.3
webpack                           4.39.2
```

**Comment by pkozlowski-opensource** [comment] 2020-05-18 15:23
@rondog could you please share a minimal reproduce scenario (GitHub repo or stackblitz) so we can confirm the issue? It definitively sounds fishy as you are providing an object but from your code / debugging info it sounds like this object is interpreted as an array? This sounds very off, this is why we need a minimal reproduce scenario as requested in the issue template.

Other thing to check - did you enable all the polyfills required for IE11? See https://angular.io/guide/browser-support

**Comment by rondog** [comment] 2020-05-18 16:10
I was going to make a stackblitz, but turns it its not even viewable in IE11. I will create a new angular app and upload a zip somewhere. Also, yes I enabled the polyfills. Just to be clear, the code I posted was in the transpiled vendor-es5.js file. The error in IE11 happened to be pointing to that file.

**Comment by pkozlowski-opensource** [comment] 2020-05-19 21:02
>  I will create a new angular app and upload a zip somewhere

Or better yet - create a minimal github repo and link it from here. I'm afraid we will need a reproduce scenario as the issue strikes me as very odd - `<ul [ngClass]="{'hidden': activeLoc}">` sounds like rather basic usage of pretty much fundamental functionality so I would expect much more reports in this area.

So yes, we need to have exact scenario to confirm / investigate / fix.

**Comment by petebacondarwin** [comment] 2020-05-28 13:17
Closing since we have no reproduction. @rondog - if you do have a reproduction please post it and I will reopen.

**Closed by petebacondarwin** 2020-05-28 13:17 UTC
Labels: browser: ie 11, comp: common, state: Needs repro
