### ISSUE TITLE
[4.x] The default ViewEncapsulation should be at @NgModule level (vs global compiler option)

### ISSUE THREAD

**Issue by vicb** [angular/angular#13819] opened 2017-01-07 00:44 UTC
Only in 4.x.

**Comment by DzmitryShylovich** [comment] 2017-01-13 12:39
@vicb so every module will have its own default encapsulation or it's only for the root module?

**Comment by djwelch** [comment] 2017-10-20 16:17
Is https://stackoverflow.com/questions/39452729/angular2-setting-view-encapsulation-globally not the way to do this already?

**Comment by mtuzinskiy** [comment] 2017-11-09 19:00
@djwelch No, the bootstrapModule setting work with JIT, but ignored by AOT :(

**Comment by pkozlowski-opensource** [comment] 2020-03-10 19:20
Let's track it in one place, closing as a duplicate of #18346

**Closed by pkozlowski-opensource** 2020-03-10 19:20 UTC
Labels: comp: core, hotlist: community-help, type: feature
