### ISSUE TITLE
Object expected error thrown in angular 9.0.x - IE11 application

### ISSUE THREAD

**Issue by Vikki123** [angular/angular#36694] opened 2020-04-17 17:13 UTC
i all. I  am developing an angular application which is running on version 9.0.x. The application runs as an ifame of the parent application. There is a signalR connection to the backend and we try to close the connection when the frame is unloading using @microsoft/signalr HubConnection.stop() method.

**What is the problem:**
When the application runs on IE 11, when the above is called , it works fine in the normal scenario. But when called on window unload as follows

```
import { Component, OnDestroy, OnInit } from '@angular/core';
import { HubConnection, HubConnectionBuilder } from '@microsoft/signalr';
import { Subject } from 'rxjs';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent implements OnInit {
  title = 'lkasjsd';

  hubConnection: HubConnection;
  subject = new Subject();
  subjectObs = this.subject.asObservable();

  ngOnInit() {
    this.hubConnection =
      new HubConnectionBuilder().withUrl('/diagHub?RequestId=ed8a41ef-9c47-4de6-8029-bbe7971041ce&AuthenticationToken=4EVYS-Q39CA&AuthenticationType=1&ToolId=EA0100&WorkStreamId=None').build();
    window.addEventListener('unload', this.handleWindowUnload.bind(this));

    this.hubConnection.start().then(() => {
      console.log('Connnected Success');
    });

    this.subjectObs.subscribe(() => {
      console.log('Stopping');
      this.hubConnection.stop();
    })
  }

  handleWindowUnload() {
      this.subject.next();
  }
}
```

i see the following error in the IE  browser console

![image](https://user-images.githubusercontent.com/8450434/79594938-9b5e0c00-80fb-11ea-9980-7db9fd252160.png)

**What is more weird:**

Just out of curiosity i changed the code in node_modules\core-js\internals\to-integer.js and put a console log

![image](https://user-images.githubusercontent.com/8450434/79595189-04458400-80fc-11ea-9a00-6ebfd3eed89d.png)

This results in the log as follows

![image](https://user-images.githubusercontent.com/8450434/79595303-3820a980-80fc-11ea-924c-1eb0cdb60927.png)

 If you see isNaN was deffined before but gets undefined in the middle of executiion. !!

Also the issue gets resolved if i install core-js@2.5.4 manually and import the following in the polyfills file

```
import 'core-js/es6/symbol';
import 'core-js/es6/object';
import 'core-js/es6/function';
import 'core-js/es6/parse-int';
import 'core-js/es6/parse-float';
import 'core-js/es6/number';
import 'core-js/es6/math';
import 'core-js/es6/string';
import 'core-js/es6/date';
import 'core-js/es6/array';
import 'core-js/es6/regexp';
import 'core-js/es6/map';
import 'core-js/es6/weak-map';
import 'core-js/es6/set';

/** IE10 and IE11 requires the following for NgClass support on SVG elements */
// import 'classlist.js';  // Run `npm install --save classlist.js`.

/** IE10 and IE11 requires the following for the Reflect API. */
import 'core-js/es6/reflect';


/** Evergreen browsers require these. **/
// Used for reflect-metadata in JIT. If you use AOT (and only Angular decorators), you can remove.
import 'core-js/es7/reflect';
```
How is this possible ? What am i missing here ?

My dev box

Angular CLI: 9.0.4
Node: 10.19.0
OS: win32 x64

Angular:
...
Ivy Workspace:

Angular

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.900.4
@angular-devkit/core         9.0.4
@angular-devkit/schematics   9.0.4
@schematics/angular          9.0.4
@schematics/update           0.900.4
rxjs                         6.5.3

tsconfig
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "module": "esnext",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2018",
      "dom"
    ]
  },
  "angularCompilerOptions": {
    "fullTemplateTypeCheck": true,
    "strictInjectionParameters": true
  }
}
```

**Comment by pkozlowski-opensource** [comment] 2020-05-15 13:30
@Vikki123 see https://github.com/angular/angular/issues/36701#issuecomment-629234221 - we would need a minimal reproduce scenario, otherwise it is not actionable.

**Comment by atscott** [comment] 2020-09-23 18:05
Closing due to lack of reproduction after several months. 

If the problem still exists in your application and you can create a reproduction, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.

**Closed by atscott** 2020-09-23 18:05 UTC
Labels: browser: ie 11, browser: ie 9 or 10, comp: core, freq1: low, severity3: broken, state: Needs repro, type: bug/fix
