### ISSUE TITLE
Add a mechanism to assure that the Angularjs app loads first in hybrid application 

### ISSUE THREAD

**Issue by aryaroudi** [angular/angular#27844] opened 2018-12-27 10:19 UTC
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/upgrade

### Description
All you can find about the migration incrementally to new Angular has been mentioned [here](https://angular.io/guide/upgrade) and many examples across the web which all mention to a little application that you can load the Angularjs file by script tag inside index.html and then bootstrap the app. In case that you have a big application more than 500,000 lines of code this approach won't work in any way and loading a bundle of old angularjs app too. If the bundle be huge, there is no way you be sure the angularjs has been loaded first and then Angular ngUpgrade bootstrap the app.

### Describe the solution you'd like
It would be great that there be a mechanism that you be able to load first the angularjs or somehow tell the angular app to wait first for Angularjs and then load the angular app and bootstrap it.

### Describe alternatives you've considered
I don't know if it is a good idea but In this case, I guess the only way is to change completely the building setup and customize it somehow by implementing Webpack instead of Angular-Cli (I'm still working on it) and build your app the way it will work.

**Comment by gkalpak** [comment] 2018-12-27 17:35
Sorry, but it is not clear to me what exactly you are requesting. Since you will be calling `upgrade.bootstrap(...)` whenever you want, you are free to wait for whatever preconditions make sense for your usecase (e.g. lazily or asynchronously loading AngularJS). Dealing with how AngularJS is loaded is outside the scope of `@angular/upgrade`.

Closing, because the issue is not actionable in its current form, but feel free to continue the discussion below.

**Closed by gkalpak** 2018-12-27 17:35 UTC

**Comment by aryaroudi** [comment] 2018-12-28 08:45
Hi @gkalpak 

the upgrade.bootstrap(...) gets called before the Angularjs loads completely because it is a heavy project. you mentioned:
> you are free to wait for whatever preconditions make sense for your use case
So my question is how you can manage that `whenever` from new angular to say wait and execute after the Angularjs app is loaded completely. As we have 2 bundles one for Angularjs and another for angular and they load async, I couldn't find a way to tell one to wait until other is loaded.

Is that may be necessary to completely change the build process in Angular-Angularjs and put them in one process to make only one bundle for both applications and manage it that way?

**Comment by aryaroudi** [comment] 2018-12-28 12:00
> > So my question is how you can manage that `whenever` from new angular to say wait and execute after the Angularjs app is loaded completely. As we have 2 bundles one for Angularjs and another for angular and they load async, I couldn't find a way to tell one to wait until other is loaded.
> 
> It really depends on how you load the bundles and bootstrap the Angular app, so I can't give specific instructions. But the loader should give you a promise that will be resolved when a bundle is loaded, so you could for example wait for both promises to resolve (i.e. both Angular and Angular JS bundles to be loaded) and then bootstrap the Angular app.

Thanks for advice @gkalpak I just went in the path to change the whole build process. I had Webpack 4 to bundle the Angularjs so basically, I just took out the Angular-Cli build and added the appropriate configuration to Webpack to compile the Angular application and now everything is on time.

My only concern is if it is a good approach to put aside the Angular-Cli build system. Any advice for that?
