### ISSUE TITLE
Add an ng-host element

### ISSUE THREAD

**Issue by StephenPaul** [angular/angular#36450] opened 2020-04-06 08:57 UTC
# 🚀 feature request

### Relevant Package
Unsure

### Description
The `@HostBinding` and `@Hostlistener` decorators are not very intuitive to use. The API feels inconsistent with the how styles and event handlers are added to most elements. Furthermore `@HostBinding` does not work with observables.

### Describe the solution you'd like
Templates can be wrapped in a special `ng-host` tag which will be erased by the Angular compiler (similar to the `ng-container` tag)
```
<ng-host 
  (click)="onClickContainer()" 
  [class.my-class]="myClass$ | async" 
  [style.background-color]="myColor$ | async">
  <!-- template content -->
</ng-host>

```
Obviously, it should not be possible to create more than one `ng-host` tag. I'm not sure about structural directives. `*ngFor` certainly doesn't make sense. `*ngIf` may be useful.

### Describe alternatives you've considered
None

**Comment by pkozlowski-opensource** [comment] 2020-04-06 09:03
I believe that this idea was raised previously in #19119. Not sure if we want to have 2 issues tracking the same need / solution.

**Comment by StephenPaul** [comment] 2020-04-06 09:12
@pkozlowski-opensource for some reason I didn't find the linked issue. Thanks for pointing that out. The only thing which is missing from that task is a mention of binding to observables but I trust that is implied.

You can close this if you like.

**Comment by pkozlowski-opensource** [comment] 2020-04-06 09:22
Yeh, let's track it in one place. Closing as a duplicate of #19119.

**Closed by pkozlowski-opensource** 2020-04-06 09:22 UTC
Labels: comp: core, core: host and host bindings
