### ISSUE TITLE
Jasmine constructs aren't available with beta 2 anymore

### ISSUE THREAD

**Issue by andrashatvani** [angular/angular#6817] opened 2016-02-01 14:36 UTC
After the upgrade to beta 2 I suddenly see the following errors:
Error:(4, 5) TS2304: Cannot find name 'it'.
Error:(13, 9) TS2304: Cannot find name 'expect'.
Error:(39, 36) TS2339: Property 'toBeNull' does not exist on type 'NgMatchers'.

**Comment by alexeagle** [comment] 2016-02-01 22:15
looks like a typechecking issue, do you have `jasmine.d.ts

**Comment by alexeagle** [comment] 2016-02-01 22:57
Dupe of 6813

**Comment by andrashatvani** [comment] 2016-02-04 07:22
No, I don't explicitly reference jasmine.d.ts and it was no problem with beta 1. Starting with beta 2 my IDE complains that these constructs can't be found. The issue is still present with beta 3.

**Comment by ericmdantas** [comment] 2016-02-04 14:16
Same here.

**Comment by filipesilva** [comment] 2016-02-04 14:22
Ditto.

**Comment by alexeagle** [comment] 2016-02-04 19:35
@filipesilva you are right, this was an undocumented breaking change:
https://github.com/angular/angular/commit/a4b5cb837682ce61f8c07eabd7ae8c4dc3ba80a7
cc @vicb and @juliemr 

We have a test
https://github.com/angular/angular/blob/a4b5cb837682ce61f8c07eabd7ae8c4dc3ba80a7/gulpfile.js#L869
which sets up a directory to look like an angular2 app, and type-checks it.
But you can see here
https://github.com/angular/angular/tree/a4b5cb837682ce61f8c07eabd7ae8c4dc3ba80a7/typing_spec
that we are missing a testing example. If we had one, we would have noticed the breaking change.

I am working on this stuff right now, I will fold a fix into https://github.com/angular/angular/pull/6267

But note that the fix will be: Angular 2 no longer pollutes your compilation with our typings files, because you might use a different version of the library, and therefore should use the corresponding typing file. So you will indeed continue installing the jasmine typing yourself. We need to add documentation for that in beta.4.

Sorry for breaking you.

**Comment by ericmdantas** [comment] 2016-02-04 20:06
Thanks!

**Comment by filipesilva** [comment] 2016-02-04 20:30
It makes sense, and is a sensible change. The other option would be to magically guess whatever typings angular2 included, and avoiding those (otherwise `tsc` would error out due to duplicate typings).

**Comment by alexeagle** [comment] 2016-02-04 21:07
Even with that magic, you have the versioning problem that you might want a
newer (or older!) jasmine.d.ts than angular2 ships with.
The typings version should match your devDependency version, not whatever
was latest when the angular package you're using shipped.

To be clear, I'm fixing this issue by documenting the breaking change, not
by re-instating the jasmine typing.

**Comment by filipesilva** [comment] 2016-02-04 21:15
:+1:

**Closed** 2016-02-04 23:05 UTC
