### ISSUE TITLE
Router: Cannot read property 'path' of undefined

### ISSUE THREAD

**Issue by cuiliang** [angular/angular#22643] opened 2018-03-08 03:16 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

**Optional param will not work if 
(1) last component hast empty path, 
(2) it's parent component has named path.**

`<a [routerLink]="[{param1: 'test'}]">This link will cause error</a>`
![image](https://user-images.githubusercontent.com/1972649/37130238-7f0f2078-22bd-11e8-8716-b9ab79c06578.png)

## Expected behavior

url parameter changed normally.

## Minimal reproduction of the problem with instructions

[https://angular-gjpvor.stackblitz.io/crisis-center/center](https://angular-gjpvor.stackblitz.io/crisis-center/center)
Open console to see errors.
What I have changed to the code from official example:
1) change path of `CrisisListComponent` from `''` to `'center'`:
```
const crisisCenterRoutes: Routes = [
  {
    path: '',
    component: CrisisCenterComponent,
    children: [
      {
        path: 'center',  <=== parent has named path
        component: CrisisListComponent,
        children: [
          {
            path: ':id',
            component: CrisisDetailComponent,
            canDeactivate: [CanDeactivateGuard],
            resolve: {
              crisis: CrisisDetailResolver
            }
          },
          {
            path: '',  <===  Empty path
            component: CrisisCenterHomeComponent
          }
        ]
      }
    ]
  }
];
```
2) put  routerLink in `CrisisCenterHomeComponent`
```
<div style='border: red 1px solid; padding:10px;'>
      <a [routerLink]="[{param1: 'test'}]">This link will cause error</a>
    </div>
```
or call `router.navigate([{param: 'value'}], {relativeTo: this.route})` in component code will also cause error.

I have debugged and found some possible problem.
[See this line](https://github.com/angular/angular/blob/6d1367d29707c2c449fda1adfa8a7177693f680b/packages/router/src/create_url_tree.ts#L279)

when error happens, `startIndex` is bigger than `segmentGroup.segments.length`, so `p` is undefined, `p.path` will be invalid.

Seems `segmentGroup.segments` is from url. For url `/path/to/child`, this array will contains 3 elements. If we have components with empty path, route levels will be bigger than that. `startIndex` will also bigger than that. Perhaps there is a bug here.

`startIndex` equals ActivatedRouteSnapshot._lastIndex of current component.

here is an example from out project: 
![image](https://user-images.githubusercontent.com/1972649/37131165-1d189980-22c2-11e8-94b4-433d3aa75ffc.png)

Route definition of a sub module. 
```
const routes: Routes = [
  {
    path: '',
    component: ProjectSettingsComponent,
    children: [
      {
        path: '',
        component: ProjectSettingsHomeComponent
      },
      {
        path: 'project-roles',
        component: ProjectRolesComponent
      },
      {
        path: 'workflow',
        component: WorkflowWrapperComponent,
        children: [
          {
            path: '',  //TODO: if empty, will cause error: ERROR TypeError: Cannot read property 'path' of undefined
            component: WorkflowComponent
          },
          {
            path: 'node/:workflowNodeId',
            component: WorkflowNodeConfigComponent
          }
        ]
      },
      {
        path: 'fields',
        component: ProjectFieldsComponent
      }
    ]
  }

];
```

## Environment

<pre><code>
Angular version: 5.2.7

Browser:
all

For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by briancodes** [comment] 2018-03-12 18:14
Hi @cuiliang 

From your description of the problem, 

`<a [routerLink]="[{param1: 'test'}]">This link will cause error</a>`

I'm pretty sure that `[routerLink]` accepts an array of strings, or a string value. The `[queryParams]="{param1: 'test'}"` should be provided as a separate input

**Comment by cuiliang** [comment] 2018-03-12 23:32
Hi @briancodes 
There are 3 type of params. What you mean is query parameters, but this is Optional Parameters.
See [this](https://stackoverflow.com/questions/44864303/sending-data-with-route-navigate-in-angular-2/44865817)

**Comment by briancodes** [comment] 2018-03-13 11:07
@cuiliang The [routerLink] directive in a template cannot accept query parameters.
`<a [routerLink]="[{param1: 'test'}]">` will cause an error because you should not be passing in query params here

**Comment by cuiliang** [comment] 2018-03-13 11:28
@briancodes It's not query paramemer, it's **Optional Parameter**.  
The [routerLink] array can take object item as optional parameters.
You can see this answer on stackoverflow: https://stackoverflow.com/questions/44864303/sending-data-with-route-navigate-in-angular-2/44865817#44865817

**Comment by briancodes** [comment] 2018-03-13 12:55
@cuiliang My bad! Sorry, I see what you mean now

**Comment by jasonaden** [comment] 2018-05-03 22:28
Closing as this appears resolved.

**Closed by jasonaden** 2018-05-03 22:28 UTC
Labels: comp: router

**Comment by teflonwaffles** [comment] 2018-05-08 22:53
I'm facing problems related to this as well. Is there a specific pull request that fixed this? (I'd like a sense of what Angular version I need to wait for in order for this to be resolved.)

**Comment by reppners** [comment] 2018-06-01 10:34
Just ran into this issue. It's not resolved. Optional matrix parameters will fail if empty routes are involved. Have to resort to query parameters to workaround it.

**Comment by uvv001** [comment] 2018-10-18 02:06
Ran into this issue too. With route definition from first post can be reproduced by
```javascript
router.navigate([{key: "value"}], { relativeTo: activatedRoute })
```

Workaround:
```javascript
urlTree = router.parseUrl(router.url);
segments = urlTree.root.children.primary.segments;
segment = segments[segments.length-1];
Object.assign(segment.parameters, {key: 'value'});
router.navigateByUrl(router.serializeUrl(urlTree));
```

**Comment by jcairney** [comment] 2018-10-18 15:36
> @teflonwaffles This was closed because it appeared resolved from the above conversation. To produce the result OP was looking for, you would change the code to:
> 
> `<a [routerLink] [queryParams]="{param1: 'test'}">This link will NOT cause error</a>`

I'm sorry @jasonaden, though that may even be the solution I needed, nobody is going to figure out that out without coming to this bug.  On that grounds I'd say this should be reopened and given a proper fix.

**Comment by jcairney** [comment] 2018-10-18 16:57
Actually what I quoted above did not work for my situation.
Related to what @reppners  said, how do we change matrix parameters on the current route if empty routes are involved?

I tried:
`<a [routerLink]="[{param1: 'test'}]">Still causes 'path' error</a>` 
and 
`<a [routerLink]="['.',{param1: 'test'}]">Also causes 'path' error</a>` 
and 
`<a [routerLink]="['../' + currentRequiredParamValueFromRouteParamsObservable,{param1: 'test'}]">Causes error when trying to navigate</a>` Did this since the route to the empty path contained an :id required parameter in the last real segment that lead to the module with the empty path.

**Comment by devpreview** [comment] 2018-12-12 15:54
Same error.

Route:
```
const routes: Routes = [
  {
    path: '',
    component: IndexComponent
  },
  {
    path: 'parent',
    component: ParentComponent,
    children: [
      {
        path: 'child',
        component: ChildComponent,
        children: [
          {
            path: '',
            component: ThirdComponent
          }
        ]
      }
    ]
  }
];
```

ThirdComponent link:
```
<a [routerLink]="['.', {arg1: '1'}]">link</a>
```

Error:
```
ERROR TypeError: Cannot read property 'path' of undefined
```

Reproduction: https://angular-router-error.stackblitz.io/parent/child
![Image of Reproduction](https://habrastorage.org/webt/gc/mz/j_/gcmzj_gwdzlhkuov6r5bfuk_v7g.png)

**Comment by devpreview** [comment] 2018-12-13 17:16
@jasonaden Is a any fix planned?

**Comment by millimoose** [comment] 2019-03-07 14:47
This shouldn't be closed, it's flat out a bug in the scenario as reported, that a workaround exists that avoids triggering it sometimes is not a resolution.

I hit this yesterday, for instance our app has very modular routing where we might have the same route segment appear several times in the same URL, we absolutely cannot use query parameters since they're not tied to a segment.
