### ISSUE TITLE
Structural Directive's provides are no longer available in template as of Angular 4.0

### ISSUE THREAD

**Issue by tyler-gh** [angular/angular#15998] opened 2017-04-14 18:31 UTC
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I may be a unicorn wanting this behavior, but when a template is constructed from a structural directive with providers the providers are not made available to components within the template.

**Expected behavior**
In version 2.x the providers were available to components within the template and should still be available in 4.x.

**Minimal reproduction of the problem with instructions**

**Angular 4.0** 
https://plnkr.co/edit/xgJmWalVRShMWveolG9I?p=preview
throws error `ERROR Error: No provider for ThingToBeProvided!`

**Angular 2.4.1**
https://plnkr.co/edit/qDFsvElHhvQe0mEhDuRQ?p=preview
works as expected

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X
4.0.2 (You should update this boilerplate ^ to reflect the new versioning)

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by chuckjaz** [comment] 2017-04-14 23:40
This was a bug fix. The structural directive is a sibling to the content, not the parent. 4.0 is working as intended and the 2.4 behavior was a bug.

Can you explain why you want such a thing and why a simple directive is not sufficient?

**Comment by davityle** [comment] 2017-04-17 12:53
The only place that we were using this in 2.x was in a cached `NgIf` directive. We needed a cached version of the `NgIf` directive for two reasons. 
1. Creating dom can be expensive, especially in IE and Edge. By caching the dom of select components after they were first created we were able to significantly increase ui responsiveness.
2. Easily maintain state. Since the component and its state is also retained in memory when cached, retaining the state of a component after it has been removed from the document is as simple as changing `*ngIf` to `*cachedNgIf`. 

However, you may be wondering why we would need to provide something from such a directive. Well, the answer is simple- lifecycle hooks! There are no lifecycle hooks for `ViewContainerRef.insert` and `ViewContainerRef.detach`. There few directives in our application that rely heavily on knowing their lifecycle state. For example, we have a feature that allows users to search/discover features in our application. As they are searching for features the user interface will open to the feature that is being searched and show the user where they can find that feature. 

![Feature Find](https://image.ibb.co/jg4HO5/GIFrecord_2017_04_17_063302.gif)

Most of these features are not available directly from the visible dom. Some part of the user interface has to be opened in order to view the feature. This is where lifecycle hooks and directives come in handy. A directive is placed everywhere that is "discoverable". This directive has two purposes-to know where in the feature us positioned in the application and to know whether or not the feature is visible. The directive will register with the discovery service when it is created and unregister in `ngOnDestroy`. If a particular feature isn't registered when it is discovered than the parent of that feature knows that it must make itself visible to the user and so on up the chain until the correct feature is visible to the user. 

That leads us back to the original question. We have a structural directive `*cachedNgIf` that provides two things - `Attached` and `Detached`. If there is something in our application that needs to know its lifecycle state it can optionally inject those two "lifecycle" hooks and listen to them. When `Attached` is fired it can register with a service or do whatever else it needs to do and when `Detached` is fired it can also perform an action. Allowing the template to inject the classes provided by a structural directive means that this directive can be completely self contained. The work around that we are using currently is having a separate directive that can optionally be placed on the parent the provides `Attached` and `Detached` when lifecycle hooks are needed. It is a bit unfortunate however because now two directives are required where previously only one was required. One of the directives also has to be on the parent of the other directive.

**Comment by tbosch** [comment] 2017-04-17 17:57
Let me try to summarize:
- you have a `*cachedNgIf` that caches views, and uses `ViewContainer.detach` / `ViewContainer.insert` to detach/attach it into the DOM.
- you need a way of telling the components in the cached view whether they are attached or not.
- you would like to encapsulate this into the `*cachedNgIf` directive

Your problem: Right now, neither DI nor queries allow `*cachedNgIf` to communicate with the created view.

Your proposed solution: expose providers from template directives to the views (i.e. change the visibility)

How about another solution: support custom lifecycle hooks
- have a `@Lifecycle('someName')` decorator on methods
- add `ViewRef.triggerLifecycleHook(name: string)`

This way, we would not need to make a breaking change but rather introduce a new feature...

What do you think?

**Comment by davityle** [comment] 2017-04-17 18:07
@tbosch that works for me

**Comment by tbosch** [comment] 2017-05-19 23:28
We talked internally and we are planning to support the DI communication, with the reasoning that in the template that the user wrote, the structural directive is actually on a parent element.

**Comment by thekalinga** [comment] 2017-05-31 09:45
@tbosch

Since the other issue I raised is closed in favor of this ticket & also because I have not response to an observation, I'm positing the comment here

> Creating a directive via TemplateRef and inserting it via ViewContainerRef creates the template as a sibling in the dom, not as a child.

I'm not sure if the above observation is true.

Here is the DOM created by the example

```html
<h1>
  From parent<br>
  <!--template bindings={}--><span>From child</span>
 </h1>
```

The template responsible for template generation

```html
<h1 *appInlineEdit>
  From parent<br>
  <span *appShowOnEdit>From child</span>
</h1>
```

The children (child directives & components) should be made accessible so that the communication between parent & children can accomplished without external co-ordination (such as managing mapping between parent & child via external service)

Please have a look at this fragile implementation in material2 (not exactly same issue as I have mentioned here, but the root cause is not having the ability to get access to the component he just created)

https://github.com/andrewseguin/material2/blob/data-table-prototype/src/lib/data-table/data-table.ts#L313

He is using static variable to get access to most recently created directive, which is clearly something scary

**Comment by tytskyi** [comment] 2017-05-31 09:54
@thekalinga i think you did not provide sufficient DOM. 
I assume complete output is:

```html
<!--template bindings={}-->
<h1>
  From parent<br>
  <!--template bindings={}--><span>From child</span>
 </h1>
```

where first is `<!--template bindings={}-->` is `*appInlineEdit`, and second `<!--template bindings={}-->` is `*appShowOnEdit`

But this just for better understanding that

> I'm not sure if the above observation is true.

It is true.

Anyway, look at the comment above your - they plan to support this Dependency Injection in future.

**Comment by thekalinga** [comment] 2017-05-31 10:26
@tytskyi Sorry, what I meant was that, it does not seems to be true for the child directives that are within the template of the directive.

**Comment by samherrmann** [comment] 2017-07-24 23:39
Is there an ETA for this feature?

**Comment by mdvorak** [comment] 2018-02-12 12:17
The problem seems to be actually in `TemplateRef.createEmbeddedView` (used by `ViewContainerRef.createEmbeddedView`), see https://github.com/angular/angular/blob/c8a1a14b87e5907458e8e87021e47f9796cb3257/packages/core/src/view/refs.ts#L318
TemplateRef is created using parentView of the template, and that cannot be changed. Along with it, it inherits `Injector` and few other properties.

The behavior is clearly shown here:
https://stackblitz.com/edit/angular-3bcv2q
The template is reused in two places, however since it is bound to the context of the template, not the context where it is actually placed, it might create quite confusing behavior (but someone might rely on this behavior).

**Comment by brunsten** [comment] 2018-10-17 13:05
> The problem seems to be actually in `TemplateRef.createEmbeddedView` (used by `ViewContainerRef.createEmbeddedView`), see
> 
> [angular/packages/core/src/view/refs.ts](https://github.com/angular/angular/blob/c8a1a14b87e5907458e8e87021e47f9796cb3257/packages/core/src/view/refs.ts#L318)
> 
> Line 318 in [c8a1a14](/angular/angular/commit/c8a1a14b87e5907458e8e87021e47f9796cb3257)
> 
>  createEmbeddedView(context: any): EmbeddedViewRef<any> { 
> 
> TemplateRef is created using parentView of the template, and that cannot be changed. Along with it, it inherits `Injector` and few other properties.
> The behavior is clearly shown here:
> https://stackblitz.com/edit/angular-3bcv2q
> The template is reused in two places, however since it is bound to the context of the template, not the context where it is actually included, it might create quite confusing behavior (but someone might rely on this).

As you mention, it's really confusing. There are no way of making a child and a parent of a structural directive communicate directly. Is there any way forward on this?

**Comment by alxhub** [comment] 2019-02-26 23:26
I'm going to convert this issue to a feature request as it's not a regression (the original change was a bugfix and the current behavior is correct).

**Comment by PierreDuc** [comment] 2019-09-03 08:05
Had the same issue today, and figured out a hack for my use-case. I don't know if it survives ivy, but for now it works. It uses the context of the embedded view and the private property `view` on the `Injector` which contains the `ViewData`:

Parent structural directive:

```
constructor(readonly vc: ViewContainerRef, readonly tr: TemplateRef<any>) {
  this.vc.createEmbeddedView(this.tr, { parentDirective: this });
}
```

And you can then get the parent in the child directive like this:

```
readonly parentDirective?: ParentDirective;

constructor(injector: Injector) {
  let view = (injector as any).view;
  
  while (!this.parentDirective && view) {
    this.parentDirective = view.context && view.context.parentDirective;
    view = view.parent;
  }
}
```

Perhaps there is a way to inject the `viewData` directly, but I doubt that, seeing as this class is not part of the public API.

**Comment by alberto-chiesa** [comment] 2019-10-16 07:38
I'm trying to understand if this issue applies to my problem. I have a standard directive used to inject a "theme" into child components:

```html
<ng-container [myButtonTheme]="'titlebar'">
  <!-- this button receives 'titlebar' as an Optional constructor parameter -->
  <my-button icon="far fa-times"></sv-button>
</ng-container>
```

I also have a structural directive used to identify page title templates:


```html
<ng-container *myPageTitle>
  <!-- I would like to have this button receive a 'titlebar' injected token. -->
  <my-button icon="far fa-times"></sv-button>
</ng-container>
```

AFAICT, currently there is no way to pass "something" from the structural directive `myPageTitle` to  the components instantiated into the template. Which doesn't make ANY sense, to me: `myPageTitle` IS a parent of `my-button` and the template scoping should be like the JavaScript lexical scoping.

Any consideration upon my case or insights on why on earth the structural directive _is not_ a parent of the button, would be really appreciated.

**Comment by Ignasimg** [comment] 2020-09-29 18:16
Any update on this?

I did try @PierreDuc hack and sadly it doesn't work for me (I'm using ivy).

From my perspective I also wonder why there's no way (or at least I don't know how) to use viewchild on a different element rather than the one holding the annotation.

**Comment by PierreDuc** [comment] 2020-09-30 08:33
> Any update on this?
> 
> I did try @PierreDuc hack and sadly it doesn't work for me (I'm using ivy).
> 
> From my perspective I also wonder why there's no way (or at least I don't know how) to use viewchild on a different element rather than the one holding the annotation.

After migrating to ivy, that hack indeed did not work anymore. However, I managed with another way to get the parent reference:

```
export class ChildDirective {
  constructor(private injector: Injector) {}

  @HostListener('click')
  onClick(): void {
    const parent = this.inject.get(ParentDirective);
  }
}
```

Luckily for me I just needed the parent in an event handler and not during creation. I did try the regular life cycle hooks, or by using `forwardRef` but it wasn't available in there yet. Didn't look into the how and why though

**Comment by Ignasimg** [comment] 2020-10-05 06:19
Thank you @PierreDuc!

On my side, I could inject it in the AfterViewInit hook without problems.

**Comment by pauldraper** [comment] 2020-11-07 00:57
Strongly disagree with @chuckjaz and agree with @alberto-chiesa 

> The structural directive is a sibling to the content, not the parent. 4.0 is working as intended and the 2.4 behavior was a bug.

```html
<ng-container provider>
  <example></example>
</ng-container>
```

```html
<ng-template provider>
  <example></example>
</ng-template>
```

Any reasonable person would consider the `provider` directive to be the DI parent of `example` in both cases.

Perhaps it could be justified by having reserving the DI parent for the call site of the template, but that's not the case either.

Since the Angular 4 """bugfix""", **there is no way to influence the DI parent of template.** It's indefensible to classify this as an improvement.

**Comment by pauldraper** [comment] 2021-03-26 09:21
Fixing this four-year regression would effectively resolve #37857 (Feature request: Choose injector when creating components)

**Comment by pauldraper** [comment] 2021-03-26 10:00
Unless....this was fixed?

Ported initial example and it seems to work.

https://stackblitz.com/edit/angular-v4bnvv?file=src/app.ts

**Comment by alxhub** [comment] 2023-12-15 16:55
Closing as resolved.

**Closed by alxhub** 2023-12-15 16:55 UTC
Labels: feature, area: core, core: ng-template and *microsyntax, core: di, feature: under consideration
