### ISSUE TITLE
Custom library issue

### ISSUE THREAD

**Issue by kursatsaka** [angular/angular#39642] opened 2020-11-12 08:01 UTC
I upgraded my project from Angular 6.3 to 10.1.3. Screenshot of package.json is below of the text. I created custom library and build my library using ng build --prod.. When i use this library another project i am getting this error all component and module "x component is not a known element" . Screenshot of error also below. It was working in version 6 just fine. Thank for your help.

Package.json: 
![image](https://user-images.githubusercontent.com/47352541/98911415-9a485e00-24d5-11eb-8a40-7fa6eba7bf96.png)

Error :
![image](https://user-images.githubusercontent.com/47352541/98910775-ab449f80-24d4-11eb-96d5-e5407d1e65c9.png)

**Comment by petebacondarwin** [comment] 2020-11-12 09:05
@kursatsaka - thanks for reporting this issue. It is difficult to diagnose your problem without more information. The errors imply that your library has not been picked up by the application project. It may be that it was not processed by ngcc correctly, in order to convert the ViewEngine code in the library to Ivy code. To help you further we would need to know more about how your project is setup - how you are building your library and application, and how the application references the library.

**Comment by kursatsaka** [comment] 2020-11-12 13:10
Here is what i am doing.
Build my library then copy files under dist folder to my main project node_modules folder. Use ngcc -s node_modules --create-ivy-entry-points for register view engine.

tsconfig.
{
  "extends": "../node_modules/@tsconfig/node12/tsconfig.json",
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "allowSyntheticDefaultImports": true,
    "declaration": false,
    "strictFunctionTypes": false,
    "strictNullChecks": false,
    "noImplicitThis": false,
    "noImplicitAny": false,
    "forceConsistentCasingInFileNames": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es2015",
    "typeRoots": [
      "../node_modules/@types"
    ],
    "lib": [
      "es2018",
      "dom"
    ],
    "paths": {
      "AlterNextUIModels": [
        "../Features/AlterNext.Module.UIModel/public_api"
      ],
      "@altern/theme": [
        "../node_modules/@altern/internetbankingtheme"
      ],
      "@vendor/*": [
        "../AlterNext.UI.Host/ClientApp/vendor/*"
      ]
    }
  },
  "include": [ "**/*.ts", "../Features/**/*.ts", "../../node_modules/@altern/**/*" ],
  "exclude": [
    "node_modules",
    "**/*.spec.ts"
  ]
}

**Comment by petebacondarwin** [comment] 2020-11-12 13:14
Could you please try to make a minimal reproduction of this that we could investigate.

**Comment by kursatsaka** [comment] 2020-11-18 17:47
Here is my minimal reproduction:

[Web.zip](https://github.com/angular/angular/files/5561756/Web.zip)

**Comment by petebacondarwin** [comment] 2020-11-18 19:33
Great! I'll take a look...

**Comment by petebacondarwin** [comment] 2020-11-18 20:55
@kursatsaka - the zip file doesn't seem to be complete. For example, there is no top level `package.json`. Also please provide steps to follow to recreate the error in this reproduction.

**Comment by kursatsaka** [comment] 2020-11-19 08:38
I moved the node_modules folder to a parent folder because I use the same node_modules in several projects, so no package.json is needed. All you have to do is run npm install. Then cut the contents of the node_modules folder in Alternext.UI.Host and paste it into node_modules in the top folder and run the ng build --prod command. You will see the error. Thanks for your help.

**Comment by yusufgedik** [comment] 2020-11-19 08:48
There is no solved issues related to this problem. Wellcome to "Angular Ivy". I have the same problem at Angular update 6.3 to 9  :(.

**Comment by petebacondarwin** [comment] 2020-11-19 09:02
@yusufgedik - if you have a reproduction of your problem, please provide it in a new issue and I will gladly try to help you resolve it.

**Comment by petebacondarwin** [comment] 2020-11-19 09:31
Just to be clear these are the steps I have taken to try to reproduce your issue (this sort of thing is what I wanted when I asked for reproduction steps):

* Unzip Web.zip
* `cd Web`
* `npm i`
* > Not Found - GET https://registry.npmjs.org/@altern%2fcomponent - Not found
* `cd AlterNext.UI.Host`
* `npm i`
* `ng build --prod`
* > An unhandled exception occurred: Script file ../node_modules/jquery/dist/jquery.min.js does not exist.
* `cd ..`
* `mv node_modules node_modules_tmp`
* `cp -r AlterNext.UI.Host/node_modules .`
* `cd AlterNext.UI.Host`
* `ng build --prod`
* > Compiling @angular/core : es2015 as esm2015
  > Compiling @angular/animations : es2015 as esm2015
  > Compiling @angular/common : es2015 as esm2015
  > Compiling @angular/animations/browser : es2015 as esm2015
  > Compiling @angular/platform-browser : es2015 as esm2015
  > Compiling @angular/forms : es2015 as esm2015
  > Compiling @angular/common/http : es2015 as esm2015
  > Compiling @angular/platform-browser-dynamic : es2015 as esm2015
  > Compiling @angular/platform-browser/animations : es2015 as esm2015
  > 0% compiling
  > Compiling @angular/core : es2015 as esm2015
  > Compiling @ngx-translate/core : es2015 as esm2015
  > ...
  > ERROR in ../Features/AlterNext.Module.BulkTransfers/flows/bulkmoneytransferflow/bulkmoneytransferflow.module.ts:2:29 - error TS2307: Cannot find module '@altern/theme' or its corresponding type declarations.
  
  It is interesting to note that there are two builds of `@angular/core` for `es2015`, which is a bit surprising, and possibly indicates two copies of the package.
* `cd ..`
* `cp -r node_modulesx/@altern node_modules`
* `cd AlterNext.UI.Host`
* `ng build --prod`
* > 0% compiling
  > Compiling @angular/common : es2015 as esm2015
  > Compiling @angular/forms : es2015 as esm2015
  > Compiling @angular/cdk/platform : es2015 as esm2015
  > Compiling @angular/cdk/keycodes : es2015 as esm2015
  > Compiling @angular/cdk/observers : es2015 as esm2015
  > Compiling @angular/cdk/a11y : es2015 as esm2015
  > Compiling @angular/cdk/bidi : es2015 as esm2015
  > Compiling @angular/cdk/collections : es2015 as esm2015
  > Compiling @angular/cdk/scrolling : es2015 as esm2015
  > Compiling @angular/cdk/portal : es2015 as esm2015
  > Compiling @angular/cdk/overlay : es2015 as esm2015
  > Compiling @angular/platform-browser : es2015 as esm2015
  > Compiling @angular/animations : es2015 as esm2015
  > Compiling @angular/animations/browser : es2015 as esm2015
  > Compiling @angular/platform-browser/animations : es2015 as esm2015
  > Compiling @angular/material/core : es2015 as esm2015
  > Compiling @angular/material/button : es2015 as esm2015
  > Compiling @angular/material/dialog : es2015 as esm2015
  > Compiling @angular/material/form-field : es2015 as esm2015
  > Compiling @angular/cdk/text-field : es2015 as esm2015
  > Compiling @angular/material/input : es2015 as esm2015
  > Compiling @angular/material/datepicker : es2015 as esm2015
  > Compiling @ng-select/ng-select : es2015 as esm2015
  > Compiling ngx-bootstrap/utils : es2015 as esm2015
  > Compiling ngx-bootstrap/positioning : es2015 as esm2015
  > Compiling ngx-bootstrap/component-loader : es2015 as esm2015
  > Compiling ngx-bootstrap/tooltip : es2015 as esm2015
  > Compiling ngx-bootstrap/popover : es2015 as esm2015
  > Compiling angular2-text-mask : main as commonjs
  > Compiling @angular/material/checkbox : es2015 as esm2015
  > Compiling @swimlane/ngx-datatable : es2015 as esm2015
  > Compiling ngx-mask : es2015 as esm2015
  > ...
  > ERROR in ClientApp/app/app.component.html:340:3 - error NG8001: 'altern-textbox' is not a known element:
  > 1. If 'altern-textbox' is an Angular component, then verify that it is part of this module.
  > 2. If 'altern-textbox' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
  > 
  > 340   <altern-textbox></altern-textbox>
  >       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  > 
  >   ClientApp/app/app.component.ts:4:16
  >     4   templateUrl: './app.component.html',
  >                      ~~~~~~~~~~~~~~~~~~~~~~
  >     Error occurs in the template of component AppComponent.

  This appears to be similar to the error you are describing above?

**Comment by petebacondarwin** [comment] 2020-11-19 09:37
I note in the following file: `node_modules/@altern/internetbankingtheme/package.json` there is this:

```
  "scripts": {
    "prepublishOnly": "node --eval \"console.error('ERROR: Trying to publish a package that has been compiled by Ivy. This is not allowed.\\nPlease delete and rebuild the package, without compiling with Ivy, before attempting to publish.\\n')\" && exit 1"
  }
```

This indicates that this library was compiled with Ivy enabled, which is not valid for publishing to npm. Is this intentional? (Sometime when using a mono-repo or local private npm mirrors this is a usable scenario but needs to be understood carefully.)

**Comment by yusufgedik** [comment] 2020-11-19 09:47
@Petebacondarwin I'm editing my comment. I believe that fixing this problem will fix my problem.If not, I'll open a new  issue

**Comment by petebacondarwin** [comment] 2020-11-19 09:53
As I understand it:

* Your main application depends upon `../../../Features/AlterNext.Module.BulkTransfers/flows/bulkmoneytransferflow/bulkmoneytransferflow.module`
* This, in turn, depends upon `ThemeModule` from `@altern/theme`, which is mapped via the `tsconfig.json` `paths` property to `../node_modules/@altern/internetbankingtheme`.
* It appears that `../node_modules/@altern/internetbankingtheme` has been compiled with ivy enabled.
* The definition of the `ThemeModule` (in the `theme.module.d.ts` file) contains:
  ```ts
  export declare class ThemeModule {
    static ɵmod: i0.ɵɵNgModuleDefWithMeta<
    ThemeModule,
    [typeof i1.InputDateComponent],
    [
      typeof i2.CommonModule,
      typeof i3.NgSelectModule,
      typeof i4.FormsModule,
      typeof i5.TooltipModule,
      typeof i4.ReactiveFormsModule,
      typeof i6.PopoverModule,
      typeof i7.MatDatepickerModule,
      typeof i8.TextMaskModule,
      typeof i9.MatCheckboxModule,
      typeof i10.NgxDatatableModule,
      typeof i11.NgxMaskModule
    ],
    [typeof i1.InputDateComponent]>;
    static ɵinj: i0.ɵɵInjectorDef<ThemeModule>;
  }
  ```
* This implies that only the `InputDateComponent` is exported from this `NgModule` (see the last type parameter).
* Therefore I would not expect the Angular compiler, when compiling your `AppComponent` to know about the `<altern-textbox>`, which does not appear to have a definition in this project.

**Comment by kursatsaka** [comment] 2020-11-25 16:56
First of all, thanks for your help. I think i fixed that problem. I closed Ivy my main project and custom library and add @NgModule() to BaseModule. I can build project now. But if i enabled Ivy i get this error. Is there any way to fix it or do i have to disabled Ivy.

Error:
![image](https://user-images.githubusercontent.com/47352541/100258033-a0b7ea80-2f57-11eb-9cae-4bc62d13fbd0.png)

I updated my minimal reproduction. 
[Web.zip](https://github.com/angular/angular/files/5598128/Web.zip)

Steps for recreate the error: 

cd Web\AlterNext.UI.Host

npm i 

move all files under node_modules folder to node_modules in upper folder 

cd AlterNext.UI.Host

ng b --prod

**Comment by iRealNirmal** [comment] 2021-04-12 09:43
@kursatsaka is it possible to share stackblitz for this ?

**Comment by alxhub** [comment] 2021-04-15 13:52
Closing this issue as I do not believe it's actionable for us at this time. Based on the previous discussion and reproduction, I believe Angular is functioning as intended and the problem lies in the custom build and `node_modules` layout of the project.

If you need support in getting this project working, you can get your questions answered using other communication channels. Please see: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

**Closed by alxhub** 2021-04-15 13:52 UTC
Labels: comp: compiler, needs clarification, needs reproduction
