### ISSUE TITLE
use core-js instead of es6-shim

### ISSUE THREAD

**Issue by rolandjitsu** [angular/angular#5755] opened 2015-12-09 20:17 UTC
Is there a reason for not using [core-js](https://github.com/zloirock/core-js)? From the [es6 compat table](http://kangax.github.io/compat-table/es6/#typescript) core-js covers a lot more than [es6-shim](http://kangax.github.io/compat-table/es6/#es6shim).

**Comment by IgorMinar** [comment] 2015-12-10 13:06
I believe that @rkirov picked es6-shim.

Rado, did we consider core-js? we could consider es6 coverage / what we actually need / payload size / development activity - project maturity

**Comment by gdi2290** [comment] 2015-12-23 06:45
is it because `es6-promise` is used in [zone.js/lib/microtask.ts#L23](https://github.com/angular/zone.js/blob/39b4a9129af9a07b07d7e86a09a040258019470a/lib/microtask.ts#L23) and `core-js` includes a promise polyfill? `core-js` allows for custom builds https://github.com/zloirock/core-js#custom-build-automatic-with-webpack

**Comment by gdi2290** [comment] 2015-12-30 07:37
Denis (the maintainer of `core-js`) added the experimental Reflect feature to `core-js` via https://github.com/zloirock/core-js/commit/4feb559f5cdc325df8b868dd952281469ee12867 for issue https://github.com/zloirock/core-js/issues/152, so the only thing that needs to happen to make sure zone.js with microtasks works with `core-js` since they also provide a `Promise` and other async polyfills

**Comment by rixrix** [comment] 2016-01-07 02:13
+1 

We use core-js behind Webpack but our typings is referencing `node_modules/angular2/typings/es6-shim/es6-shim.d.ts` - it works ATM :confused: - using DefinitelyType es6-shim typings would just spit out duplicate errors

**Comment by alexeagle** [comment] 2016-02-12 03:32
in beta.6, we do not expose es6-shim typings in our package. Users can reference `node_modules/angular2/typings/browser.d.ts` to get the es6-collections and es6-promise typings. However you should be able to choose any runtime polyfill you like, including core-js.

However, angular2 still has a peerDependency on es6-shim (and also es6-promise) which I think is not right, instead we just require that applications bring some es6-promise and es6-collections shim at runtime.

**Comment by laco0416** [comment] 2016-02-12 03:37
+1 on removing es6-shim dependency!

**Comment by DaSchTour** [comment] 2016-04-27 12:05
so what's the current state of this?

**Comment by alexeagle** [comment] 2016-04-28 03:43
I believe the current state is that you can ignore the warning from NPM that the peerDependency on es6-shim is missing, and instead use core-js to provide the dependency. Can you try this and report back?

**Comment by laco0416** [comment] 2016-04-28 03:49
as @alexeagle says, actually I'm using core-js with Angular2. And because I'd like to use `npm shrinkwrap`, I also install es6-shim. (shrinkwrap doesn't allow warning)

**Comment by IgorMinar** [comment] 2016-04-28 04:16
we'll drop the peer dependency on es6 shims and it will be developers
responsibility to provide the right polyfills for the targeted environment.

**Comment by jdonenine** [comment] 2016-05-09 23:17
Our legal department is refusing to approve the use of es6-shim in our products because of its reference to the older es6-shim library. At the moment that blocks our use of ng2. Any chance this dropping of the dependence on es6-shim will happen sooner rather than later so that we could swap in corejs instead?

**Comment by alexeagle** [comment] 2016-05-09 23:19
You do *not* need to install or use es6-shim. Just ignore that warning from
`npm` for now.

**Comment by battmanz** [comment] 2016-05-09 23:59
I'm at the point where I could use either library (core-js or es6-shim). Which one should I prefer for Angular 2 development? From the comments I've read it sounds like core-js has more features. Is that true? What are the advantages of es6-shim?

**Comment by gdi2290** [comment] 2016-05-10 00:13
imho I would suggest core-js. if you need advantages you can read the readme at [core-js](https://github.com/zloirock/core-js)

**Comment by battmanz** [comment] 2016-05-10 00:23
@gdi2290 Thanks Patrick! I'm trying core-js right now.

**Comment by qlonik** [comment] 2016-06-05 02:40
Hi. I wasn't sure where to report about this, so here it is.

My IDE of choice is Webstorm and I was trying out angular2 with typescript in that IDE, however whenever I install typings for core-js I get this error in Webstorm/IntelliJ:

![ng2-core-js-webstorm-error](https://cloud.githubusercontent.com/assets/1373271/15803260/f3a0b670-2aaa-11e6-9da2-80e9ba491c8d.png)

That might be one little reason against core-js...

Is there anyone who might be aware of the solution to this problem?

Thanks!

**Comment by cebor** [comment] 2016-06-05 07:59
@qlonik
Cannot reproduce this, have you removed all es6-shim npm-pkgs/typings? Do you also installed `core-js` via npm?

**Comment by pkozlowski-opensource** [comment] 2016-06-05 08:09
Closing this issue as it was about moving from es6-shim to core-js which we did. WebStorm support seems to be a separate (and non confirmed) issues. Feel free to continue the discussion in here and if it turns out that WebStrom support is not ideal due to deps on shims please open a new issue. Thnx!

**Closed by pkozlowski-opensource** 2016-06-05 08:09 UTC

**Comment by qlonik** [comment] 2016-06-05 15:13
I've created tiny project with only necessary stuff: [ng2-core-js-test.tar.gz](https://github.com/angular/angular/files/299381/ng2-core-js-test.tar.gz)

In IntelliJ/Webstorm settings I enabled support for node.js and added `node_modules/` as the library of this project and everything else was left by default.

As soon as I type `typings i -SG dt~core-js` and code analysis completes, I get that error above, and as soon as I type `typings r -SG core-js` it disappears.

**Comment by vsakaria** [comment] 2016-06-08 10:57
The core.js polyfill doesn't work in IE9 specifically. I have a polyfills.ts file which imports core-js and additionally requires the specific shim. 

`import 'core-js';

require('core-js/client/shim.min')
require('zone.js/dist/zone');
require('zone.js/dist/long-stack-trace-zone');
` 

And in IE9 I get the following error: 

`ORIGINAL EXCEPTION: TypeError: Object doesn't support property or method 'requestAnimationFrame'`

I have used the seed project.

It's a real shame the Beta version had a standard way of dealing with IE9 and RC doesn't wired :(

**Comment by zloirock** [comment] 2016-06-08 12:34
@vsakaria `requestAnimationFrame` is not a part of ECMAScript, you should use a separate polyfill for this feature.

**Comment by kylecordes** [comment] 2016-06-08 13:25
Related to all this, I wondered what browsers/versions are planned for Angular 2 support. I have heard it described as "all the evergreen browsers" but I don't know if that is official/final, I didn't spot it somewhere.

(Presumably, if IE9 support makes the cut, the responsibility would fall on the Angular team, not on a user thereof, to select/bundle/depend-on a polyfill that includes all the pieces Angular needs for it.)

**Comment by DaSchTour** [comment] 2016-06-08 14:10
I guess this answers all questions :D https://saucelabs.com/u/angular2-ci

**Comment by ericmartinezr** [comment] 2016-06-08 14:32
This answeres even more https://github.com/angular/angular/issues/3333#issuecomment-219561520

**Comment by pmulac** [comment] 2016-07-06 13:51
@qlonik curious if you've used any workaround to get core-js to play nice with Webstorm/IntelliJ.  I'm facing the same problem.  It seems that when core-js is used, classes are not considered "Types" and the IDE shows many errors.

**Comment by qlonik** [comment] 2016-07-08 22:55
@pmulac

Hey, sorry for delayed response. What I ended up doing is using core-js as a polyfill library in the code, however using typing for es6-shim. I thought that both these libraries are supposed to have the same functionality, so the d.ts are supposed to match for the most part.

**Comment by HorvathAkosPeter** [comment] 2017-02-16 11:51
Beside others, the shim for the Promise objects doesn't exist in @angular/core.
