### ISSUE TITLE
Attribute directive is unable to get reference to content grandchildren

### ISSUE THREAD

**Issue by agrossman** [angular/angular#18242] opened 2017-07-20 02:23 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Any `@Directive` instance that specifies `@ContentChildren` with `descendants: true` will not pick up the children of any components. It will only pick up direct descendants of the element decorated with the directive.

## Expected behavior
The `descendants` option should do what it says on the tin and include indirect descendants.

## Minimal reproduction of the problem with instructions
http://plnkr.co/edit/se8JRc?p=preview

Just run and look at the console log. It will output an empty array instead of an array containing the `#inner` elements.

If you add `<div #inner></div>` directly underneath the `wrapper` then it is found.

## What is the motivation / use case for changing the behavior?
Same motivation as `ContentChildren` itself. The actual use case in our scenario is complex to describe, but it goes something like this:

- We have a generic `List` component that supports element recycling
- This `List` may contain other Lists, or components that want to run custom actions when recycled. We'll call this `Recyclable` and give it an interface, and mark with `#recyclable` in templates.
- The `List` can't talk directly to these nested `Recyclable` instances because they are dynamically created; however, we can use a Directive to detect when an item should be recycled via some context property.
- In order for this to work, our Directive must be able to find any `#recyclable` descendants, which may be nested inside some outer component. We can't instantiate the Directive "inside" the component, because then it loses access to the aforementioned context.

I'm sure there are simpler use cases where this would be useful. For example, let's say we want to have a global built-in search function for all pages in our app, including a highlighting feature. We'd want to encapsulate the highlighting behavior in an attribute directive (`[highlight]="someText"`) and mark searchable sections with `#highlightable`. In order for this to work, we'd require a working recursive `ContentChildren` query.

## Environment

<pre><code>
Angular version: 4.3.1

Browser:
- [X] Chrome (desktop) version 59.0.3071.115
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
</code></pre>

**Comment by mlaval** [comment] 2017-07-31 16:13
As far as I understand, the query mechanism cannot break the components boundaries by design. Since queries are resolved at compilation time, extending it to the full application would be highly complex, if not impossible.
@tbosch Do you confirm my analysis please?

About your use case, couldn't ut be solved with some recursive querying?
Someting like this: http://plnkr.co/edit/q5MgFVQMbAba9LrEeInZ?p=preview

**Comment by pkozlowski-opensource** [comment] 2018-01-10 14:29
Yep, @mlaval is right - queries and not meant to descent into _view_ of a content component. In your plunker `#inner` elements are part of the `<outer>` directive template (view) and _not_ part of the `wrapper`'s content.

I'm not saying that your use-case is not legit, just saying that current queries design / impl follow different set of rules / mental model. As such we would need a new design / impl to cover your use-case. Marking it as a feature request that needs design.

**Comment by pkozlowski-opensource** [comment] 2018-01-11 10:13
Discussing this some more with @mhevery - we really do _not_ want to descend into a template rendered by a component placed as content. This would require us to _know_ much more.

@mlaval suggestion is the way to go.

Closing as won't fix.

**Closed by pkozlowski-opensource** 2018-01-11 10:13 UTC
Labels: comp: core & compiler, freq1: low, state: Needs Design, type: bug, type: feature
