### ISSUE TITLE
new control flow makes `ng-content` not works

### ISSUE THREAD

**Issue by leo6104** [angular/angular#52341] opened 2023-10-24 03:48 UTC
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

When we render component with @if / @for syntax, it doesn't projection to `ng-content` usage.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-at-xnyger?file=src%2Fmain.ts

### Please provide the exception or error you saw

```true
No error message, just not rendered.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.0.0-rc.0
Node: 18.16.0
Package Manager: npm 9.5.1
OS: darwin x64

Angular: 17.0.0-rc.0
... animations, cli, common, compiler, compiler-cli, core
... elements, forms, language-service, localize
... platform-browser, platform-browser-dynamic, platform-server
... router, service-worker, ssr

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.0-rc.0
@angular-devkit/build-angular   17.0.0-rc.0
@angular-devkit/core            17.0.0-rc.0
@angular-devkit/schematics      17.0.0-rc.0
@angular/cdk                    16.2.4
@angular/material               16.2.4
@angular/youtube-player         16.2.0
@schematics/angular             17.0.0-rc.0
ng-packagr                      17.0.0-next.2
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.0
```

**Comment by swami-sanapathi** [comment] 2023-10-24 04:04
https://github.com/angular/angular/issues/52277

**Comment by swami-sanapathi** [comment] 2023-10-24 04:04
#52277

**Comment by swami-sanapathi** [comment] 2023-10-24 04:05
Similar issue: https://github.com/angular/angular/issues/52277

**Comment by JoostK** [comment] 2023-10-24 04:38
Closing as a duplicate of #52277

**Closed** 2023-10-24 04:38 UTC
