### ISSUE TITLE
FEATURE: NgComponentOutlet access to created component

### ISSUE THREAD

**Issue by kukjevov** [angular/angular#15915] opened 2017-04-12 07:06 UTC
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Currently when you use `NgComponentOutlet` you cant access created component for "binding". So it can be used only for displaying dynamic components, but not for interaction with them.

**Expected behavior**
It would be nice to have option how to retrieve created component instance from this directive.

**What is the motivation / use case for changing the behavior?**
Be able to use dynamic declarative component creation with full access to created component for "binding".

**Suggested solution**
There are two possible ways as far as i see it :).
I. Use of `Output`
first change directive to generic
```typescript
export class NgComponentOutlet<TComponent> implements OnChanges, OnDestroy 
```

then add
```typescript
@Output()
public ngComponentOutletCreated: EventEmitter<TComponent> = new EventEmitter<TComponent>();
```
and after component has been created by `_viewContainerRef.createComponent` `emit` new component.

II. Add exportAs and public getter for instance of `Component`
first change directive to generic and add exportAs
```typescript
@Directive({selector: '[ngComponentOutlet]', exporAs: 'ngComponentOutlet'})
export class NgComponentOutlet<TComponent> implements OnChanges, OnDestroy 
```

then add public getter
```typescript
    public get component(): TComponent
    {
        if(!this._componentRef)
        {
            return null;
        }

        return this._componentRef.instance;
    }
```

Or implement both solutions, because they can work together well.

Both of these solutions are working, but you cant use `<ng-container *ngComponentOutlet="comp">` syntax, since i havent figured out how to use "output" binding for `*ngComponentOutlet` or how to use `#myComponent="ngComponentOutlet"` with this syntax.

I had to change it to `<ng-template [ngComponentOutlet]="comp">` and you can then use "output" binding and also reference with "exportAs" for obtaining directive using `ViewChild`.

Thank you

**Please tell us about your environment:**
Windows 10, VSCode 1.11.1

* **Angular version:** 4.0.1

* **Browser:** [all]
 
* **Language:** [TypeScript 2.2.1]

**Comment by trotyl** [comment] 2017-04-12 10:13
Is it duplicate of https://github.com/angular/angular/issues/15360?

**Comment by kukjevov** [comment] 2017-04-12 11:22
Yes, lets say it is duplicate, but with suggested solutions. I would rather not close it yet, since we dont know what will be solution :).

**Comment by irowbin** [comment] 2017-06-10 10:25
Angular docs says it is EXPERIMENTAL. Can i implement it to my production project? @kukjevov

**Comment by kukjevov** [comment] 2017-06-14 07:23
Hi.

I am using modification in production, so i dont see any problem :)

**Comment by irowbin** [comment] 2017-06-14 13:55
EXPERIMENTAL means can be removed, modify or deprecated? Right?

**Comment by trotyl** [comment] 2017-06-14 14:32
@irowbin Everything can be removed or modify, `STABLE` APIs would have the deprecated state while `EXPERIMENTAL` APIs may be changed directly. See http://angularjs.blogspot.hk/2016/10/versioning-and-releasing-angular.html#Deprecation_policy_31 for more information.

**Comment by irowbin** [comment] 2017-06-14 15:11
Thanks. @trotyl

**Comment by pkozlowski-opensource** [comment] 2017-12-21 14:15
Closing as a duplicate of #15360 as both issues are about the same exact thing. Let's centralize the discussion in one place.

**Closed by pkozlowski-opensource** 2017-12-21 14:15 UTC
Labels: comp: common, type: feature
