### ISSUE TITLE
NG01050: formControlName must be used with a parent formGroup directive

### ISSUE THREAD

**Issue by misko626** [angular/angular#58118] opened 2024-10-08 07:33 UTC
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

Yes

### Description

Hello. 

I have a problem:
---------------------------
I have my custom component. I send form: UntypedFormGroup like an Input to this component.
Component code: 

import { Component, Input } from '@angular/core';
import { UntypedFormGroup } from '@angular/forms';

@Component({
  selector: 'app-radio-buttons',
  templateUrl: './radio-buttons.component.html',
  styleUrl: './radio-buttons.component.scss'
})
export class RadioButtonsComponent {
  @Input() form: UntypedFormGroup;
  @Input() values: string[];
  @Input() formControlName: string;
}

Template code: 

@if (form && values) {
  <div class="radio-buttons-container" [formGroup]="form">
    @for (value of values; track value) {
      <div class="buttons-wrapper">
        <input
            type="radio"
            class="radio form-control"
            formControlName="{{formControlName}}"
            [id]="'radioButton' + value"
            [value]="value"
            [attr.data-test]="'radio-button-' + value">
        <label [for]="'radioButton' + value">
          {{ 'order-approve.' + value | translate }}
        </label>
      </div>
    }
  </div>
} @else {
  {{ 'order-approve.no-needed-data-provided' | translate }}
}

I have got the error (see below in error section).

In case I move template code right to the parent component, the error not appears. 

Can someone help me with that?

### Please provide the exception or error you saw

NG01050: formControlName must be used with a parent formGroup directive.  You'll want to add a formGroup
      directive and pass it an existing FormGroup instance (you can create one in your class).

    Example:

    
  <div [formGroup]="myGroup">
    <input formControlName="firstName">
  </div>

  In your class:

  this.myGroup = new FormGroup({
      firstName: new FormControl()
  });

### Please provide the environment you discovered this bug in (run `ng version`)

Angular CLI: 17.3.6
Node: 20.16.0
Package Manager: npm 10.8.2
OS: win32 x64

Angular: 17.3.6
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1703.6
@angular-devkit/build-angular   17.3.6
@angular-devkit/core            17.3.6
@angular-devkit/schematics      17.3.6
@schematics/angular             17.3.6
rxjs                            7.8.1
typescript                      5.3.3
zone.js                         0.14.4

**Comment by JoostK** [comment] 2024-10-08 07:48
This is working as designed, with #47580 as similar situation. Closing as duplicate of that one.

**Closed by JoostK** 2024-10-08 07:48 UTC
