### ISSUE TITLE
Input field memory leak

### ISSUE THREAD

**Issue by kobaska** [angular/angular#41981] opened 2021-05-07 06:26 UTC
# Bug Report

### Is this a regression?

Exists in 11.0.5 too

### Description
Component with input fields, when edited aren't removed from memory when component is destroyed

## Minimal Reproduction

https://stackblitz.com/edit/angular-ivy-xvdcid?file=src%2Fapp%2Fempty%2Fempty.component.html

Also on Github:
https://github.com/kobaska/ng-memory-leak

**Reproduction steps**

1. Click list button
2. Edit one of the input fields
3. Click empty button
4. Repeat step 1 to 3 couple times 
5. Open inspect memory tab
6. Click bin to collect garbage
7. Take a heap snapshot
8. Search for ListComponent

**Current behavior**

Instances of ListComponent in the memory.

**Expected behavior**

No instance of ListComponent to exist in memory.

This only happens when the input field is modified

![image](https://user-images.githubusercontent.com/7113767/117406370-4e401880-af50-11eb-9d7c-c4d076c17a04.png)

## Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 11.2.12
Node: 12.13.0
OS: darwin x64

Angular: 11.2.13
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.12
@angular-devkit/build-angular   0.1102.12
@angular-devkit/core            11.2.12
@angular-devkit/schematics      11.2.12
@angular/cli                    11.2.12
@schematics/angular             11.2.12
@schematics/update              0.1102.12
rxjs                            6.6.7
typescript                      4.1.5

</code></pre>

**Comment by JoostK** [comment] 2021-05-07 08:32
Duplicate of #41047. There have been some experiments to mitigate this, but a final solution is not yet known.

**Closed by JoostK** 2021-05-07 08:32 UTC
