### ISSUE TITLE
How to wrap an existing Directive?

### ISSUE THREAD

**Issue by codeNoobie** [angular/angular#26839] opened 2018-10-29 22:16 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[X] Other... Please describe: Question
</code></pre>

What is the guideline around wrapping a directive? Basically we have a directive which is composed of another directive. Is this supported by Angular?

**Comment by pkozlowski-opensource** [comment] 2018-10-30 08:05
Yeh, it sounds like a duplicate of #8785.

**Closed by pkozlowski-opensource** 2018-10-30 08:05 UTC
