### ISSUE TITLE
Inaccurate error when `BrowserAnimationsModule` is loaded but the `@Component.animations` property is missing

### ISSUE THREAD

**Issue by Tinalst** [angular/angular#27702] opened 2018-12-17 13:05 UTC
# 🐞 bug report

### Affected Package
 I have no idea. Maybe is the rxjs/core?

### Is this a regression?

no

### Description

As the below code, which is work in the desktop browser. However, it is doesn't work in the mobile browser. I find it is because of the subject.next() did not send successfully. It is happen when switch the chrmoe devtools to mobile mode
**ToastService.ts**
` 
    
    public subject = new Subject<ToastModel>();

    constructor() {}
    getToast = (toastId?: string): Observable<any> => {
       return this.subject.asObservable();
    };
    success(message: string, keepAfterRouteChange = false) {
      this.toast(ToastType.Success, message, keepAfterRouteChange);
    }
    toast(type: ToastType, message: string, keepAfterRouteChange = false) 
    {
       this.keepAfterRouterChange = keepAfterRouteChange;
       // I think is this code doesn't work
       this.subject.next(<ToastModel>{ type: type, message: message });
    }`

**toast.component.ts**
`

    constructor(private toastService: ToastService) {
    }

    ngOnInit() {
     this.toastService.getToast().subscribe((toast: ToastModel) => {
        // because in here can not catch the data from subject.next()
        console.log('toast')
        if(!toast) {
          this.toasts = [];
         return;
        }
        this.toasts.push(toast);
      })

      this.toastService.subject.subscribe((toast: ToastModel) => {
        console.log(toast);
      })
    }`

**Above those codes is work in the desktop browser, However, it is not work in the mobile browser**

## 🔬 Minimal Reproduction

[https://stackblitz.com/edit/angular-nmpadm?file=src%2Fapp%2Fapp.component.ts](url)

## 🔥 Exception or Error
<pre><code>

Hope can support in mobile browser
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 6.2.5
Node: 8.12.0
OS: darwin x64
Angular: 6.1.10
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.8.5
@angular-devkit/build-angular     0.8.5
@angular-devkit/build-optimizer   0.8.5
@angular-devkit/build-webpack     0.8.5
@angular-devkit/core              0.8.5
@angular-devkit/schematics        0.8.5
@angular/cli                      6.2.5
@ngtools/webpack                  6.2.5
@schematics/angular               0.8.5
@schematics/update                0.8.5
rxjs                              6.2.2
typescript                        2.9.2
webpack                           4.20.2
</code></pre>

**Anything else relevant?**

chrome version 70.0.3538.110

**Comment by pkozlowski-opensource** [comment] 2018-12-17 19:03
Could you please provide a minimal, runnable reproduce scenario in a stackblitz?

**Comment by Tinalst** [comment] 2018-12-18 01:07
ok, I will push a reproduce as soon as possible

**Comment by luki215** [comment] 2018-12-20 11:08
Hi, the problem in your example is not in observables nor subjects. It's in animations - as you can see in error console. If you remove `[@slideDownAnimation]="isShow"` from your `toast.component.html` your example works - even on phone as you can see here: https://stackblitz.com/edit/angular-72dne4.

**Comment by matsko** [comment] 2019-01-08 23:19
Looks like there's something else going on here which is causing `BrowserAnimationsModule` not to work. Looking into it.

**Comment by JoostK** [comment] 2020-10-25 19:04
The problem here is that `BrowserAnimationsModule` is indeed not present, but once you add it the error remains. This is because `ToastComponent` does not declare any animation triggers, which causes it to not be assigned the dedicated `AnimationRenderer`.

**Comment by AndrewKushnir** [comment] 2021-04-26 04:30
Closing this ticket in favor of #18751 (the error message would be improved in #41356).

**Closed by AndrewKushnir** 2021-04-26 04:30 UTC
Labels: P4, comp: animations, freq1: low, hotlist: error messages, type: bug/fix
