### ISSUE TITLE
Compiler performance regression

### ISSUE THREAD

**Issue by doxavore** [angular/angular#13146] opened 2016-11-29 23:17 UTC
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
After updating to 2.2.1 or 2.2.3, the a mid-sized app (~50k LOC or so) takes over 90 seconds to bootstrap. In 2.2.0, the same app bootstraps in under 5 seconds.

**Expected behavior**
Time to bootstrap should not take this long.

**Minimal reproduction of the problem with instructions**
The app is using the JIT compiler and includes approximately 30 app NgModules, built with Webpack. It is a sizable enough codebase that makes reproducing in the small difficult.

I have captured a CPU profile from Chrome, screenshot attached below. The green lines are angular. This profile runs 90 seconds.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.2.1 and 2.2.3

* **Browser:** all (tested latest Chrome, Firefox, Safari across different operating systems); tested with devtools open and closed

 
* **Language:** TypeScript 2.0.9

* **Node (for AoT issues):** `node --version` =   

![image](https://cloud.githubusercontent.com/assets/633/20733088/5eb78776-b657-11e6-9d91-3d31f594b44d.png)

**Comment by doxavore** [comment] 2016-11-29 23:18
After looking through the 2.2.0->2.2.1 changelog, I'm not sure if this may be of interest to @chuckjaz (via https://github.com/angular/angular/commit/5b0f9e2f519af250513827cfba35ebfd46db7459)

**Comment by chuckjaz** [comment] 2016-11-29 23:41
@doxavore Could you give a crack at coming up with a repository we could clone to see the difference?

**Comment by doxavore** [comment] 2016-11-30 01:24
I am attempting to reproduce on a smaller sample but am not having much luck. There aren't cyclical dependencies in this codebase that I'm aware of, but there are many files that import into the root module (eventually) - around 700 files by my count. If that has something to do with it, it's not terribly easy for me to reproduce that. :>

**Comment by robwormald** [comment] 2016-11-30 01:27
Is this with CLI or your own webpack setup? That trace looks pretty suspicious, in that it appears to be repeatedly bootstrapping(?) modules, which would point to some wackiness in your webpack build.

**Comment by doxavore** [comment] 2016-11-30 01:34
This is a custom webpack configuration on webpack 1.13.3. It could certainly be something wonky in that config, but we see the 90s vs <5s times when we only change the angular packages from 2.2.0 to 2.2.1 or 2.2.3.

**Comment by doxavore** [comment] 2016-11-30 01:54
@robwormald Sorry for the confusion, I'm not sure what happened with the above profile. This one is more representative and doesn't show my `runBootstrap` code running multiple times, with `PlatformRef_.bootstrapModule` taking 2.1 minutes.

![image](https://cloud.githubusercontent.com/assets/633/20736674/a46933a8-b66d-11e6-9d12-3eb220e45752.png)

**Comment by simplifia** [comment] 2016-11-30 09:12
Hello,

In the exact same way as doxavore, we've encoutered the exact same issue, after seeing the screenshot. We have the same performance issue with AoT compiler (from almost instant to 10 minutes).

Using chrome timeline tool, it looks like that the time lost is in ListWrapper.flatten. This something that has been changed between 2.2.0 and 2.2.1.

We tried to remove `ListWrapper.flatten(transitiveExportedModules.map(function (ngModule) { return ngModule.directiveLoaders; }));` in  metadata_resolver.js in @angular/compiler/src and replace it with an empty array and the performance boost is big, even when we only have two custom directives in the entire app and @angular/material.

On our app, chrome profiler :
![time-line-ng2](https://cloud.githubusercontent.com/assets/5381271/20746047/5e7bac00-b6e4-11e6-8b57-67e01892bd47.jpg)

**Comment by aleksclark** [comment] 2016-11-30 11:20
@simplifia would you mind sharing how you're using modified @angular/compiler packages in your project? I've tried npm linking @angular/compiler but seem to be missing something.

**Comment by simplifia** [comment] 2016-11-30 12:57
We've just edited in our node_modules the compiler file metadata_resolver.js (@angular/compiler/src)

`var directiveLoaders = ListWrapper.flatten(transitiveExportedModules.map(function (ngModule) { return ngModule.directiveLoaders; }));`

Replaced by

`var directiveLoaders = [];`

That edit was for debug purpose only, we do not use a customised version of the compiler if that's your question.

**Comment by nadavsinai** [comment] 2016-11-30 13:08
I have seen this too, my app is big, (100+ modules... don't know how many components anymore...) not open source unfortunately ( i can not show it to you on plunker etc.. )-; ) I can not bootstrap it in 2.2.x / 2.3.x latest working version is 2.1.2
it is stuck for what seems like an infinite loop inside ListWrapper.flatten ( but chrome dies before I can prove it's infinite...)
I told @pkozlowski-opensource about this in gitter but he told me that if I can not reproduce via a plunker I should not open an issue. I'm happy someone else is facing this too so we can track it and fix it, I'll be happy to help with testing possible fixes on my large scale app. (BTW - medical imaging workstation for those interested what it is)

**Comment by aleksclark** [comment] 2016-11-30 14:26
@simplifia Thanks. I was looking for a way to directly test the commits in question. After a lot of `npm link` I managed to get it working. I've attached profiles for 5b0f9e2f519af250513827cfba35ebfd46db7459 and 462879887a2c0b697f9149f81d738f1d3e76e5b3, the preceding commit. It looks like 5b0f9 is definitely the culprit here, hopefully @chuckjaz can give us some insight as to how to work around this, or perhaps a patch.

**Comment by chuckjaz** [comment] 2016-11-30 19:13
@doxavore @aleksclark I have not been able to reproduce the regression locally but I have a theory about what might be causing it.

Can one of you look at #13163 and try the changes implied by this. The following is a diff of the changes it makes to `compiler.umd.js` on the `2.2.x` branch.

```
14471c14471
<               var templateMeta_1 = this._directiveNormalizer.normalizeTemplate({
---
>               var templateMeta = this._directiveNormalizer.normalizeTemplate({
14482,14483c14482,14483
<               if (templateMeta_1.syncResult) {
<                   createDirectiveMetadata(templateMeta_1.syncResult);
---
>               if (templateMeta.syncResult) {
>                   createDirectiveMetadata(templateMeta.syncResult);
14490c14490
<                   return function () { return templateMeta_1.asyncResult.then(createDirectiveMetadata); };
---
>                   return templateMeta.asyncResult.then(createDirectiveMetadata);
14712,14714c14712
<                       var loader = _this._loadDirectiveMetadata(declaredType, isSync);
<                       if (loader)
<                           transitiveModule.directiveLoaders.push(loader);
---
>                       transitiveModule.directiveLoaders.push(function () { return _this._loadDirectiveMetadata(declaredType, isSync); });
```

Let me know if this change helps.

**Comment by doxavore** [comment] 2016-11-30 20:07
@chuckjaz YES, that takes the call to `PlatformRef_.bootstrapModule` down to 300ms on my machine. I made the changes above directly to my local `compiler.umd.js` at the released 2.2.3.

**Comment by chuckjaz** [comment] 2016-11-30 20:37
Thanks! I will move this to master and get this into 2.2.4.

**Comment by doxavore** [comment] 2016-11-30 20:53
Excellent - thanks for the quick help @chuckjaz 

I don't suppose you have any insight as to what the release timeline may look like? We need 2.2.1+ for #12911 but those are also the released versions that are painful for us to work against.

**Comment by chuckjaz** [comment] 2016-11-30 21:09
it will be in 2.2.4 which should be released today or tomorrow.

**Comment by tbosch** [comment] 2016-11-30 21:48
@doxavore Could you help us create a reproduction so we are able to detect regressions in the future?

We would nee the following for each `NgModule` of yours:
```
@NgModule({
  imports: [...],
  exports: [...],
  declarations: [...]
  // don't need providers nor entryComponents
})
class SomeModule {
// don't need the implementation
}
```

And for each directive / component / pipes, we only need:
```
@Directive({
  selector: 'someSelector'
  // don't need anything else.
  // for components: just use `template: ''`
 })
class MyDirective {
  // don't need the body
}

@Pipe({
  name: 'someName'
})
class MyPipe {
  // don't need the body
}
```

I.e. we only need the structure of the `NgModule`s, but no implementation code. This is enough as we now know that the regression is because of our book keeping code when we collect metadata for NgModules.

**Comment by doxavore** [comment] 2016-11-30 22:00
@tbosch That's not a terribly easy thing to do since it's combing through and cleaning out/renaming over 500 files. It may be easier for us to script out something that just generates some representative set of files and test if it would have caused the issue.

I'm open to doing either, but both will take some to do. I'm assuming you'd want them in separate physical files to appropriately simulate this?

**Comment by chuckjaz** [comment] 2016-11-30 22:33
@doxavore All we care about is that it reproduces the issue. The steps @tbosch describes above should be enough to reproduce the issue but generating a similarly shaped set of modules should also reproduce the issue.

The repro doesn't have to match your project; any set of files that demonstrate the issue is sufficient. If it easier to generate all in one or a small number of files then start there. The physical location of the module declaration shouldn't matter, just its shape (the number of declarations, inputs, and exports).

Even though the issue is resolved as reported we want to make sure we don't regress this again as we are making substantial changes in this area. We also believe this might be indicative of an underlying issue, that the fix reduces the impact of, but we should fix. The previous change shouldn't have gone exponential.

**Closed** 2016-11-30 22:56 UTC
Labels: comp: performance, severity5: regression

**Comment by simplifia** [comment] 2016-12-01 08:36
@chuckjaz @tbosch Do you still need a list of NgModules and Directives/Components/Pipes of an app that had the issue ? If yes, we'll provide ours.

**Comment by doxavore** [comment] 2016-12-01 12:56
@simplifia I won't be able to work this up for at least a few days, so if this is something you're able to do I would very much appreciate it!

**Comment by tbosch** [comment] 2016-12-01 17:34
@simplifia @doxavore yes, we still need this data so we can make sure we won't regress, as right now we can't reproduce it. And the compiler is constantly changing...

**Comment by simplifia** [comment] 2016-12-02 14:17
Hello guys,

We created a Gist containing the required data :
https://gist.github.com/simplifia/c9eb59e186083d2148561e2e9c22959d

Please let us know if further information is needed.

**Comment by tbosch** [comment] 2016-12-02 23:24
@simplifia Thanks, I will try to reproduce the performance problem with it.

**Comment by chuckjaz** [comment] 2016-12-03 00:08
@simplifia With a few modifications to the above Gist I was able to reproduce the issue.  Thank you!!

**Comment by simplifia** [comment] 2016-12-05 13:10
Nice ! :) Happy to help !
