### ISSUE TITLE
Compiling different parts of Angular application in specific zones

### ISSUE THREAD

**Issue by sharikovvladislav** [angular/angular#32137] opened 2019-08-14 11:12 UTC
# 🚀 feature request

### Relevant Package

 This feature request is (probably) for @angular/compiler, @angular/core

### Description

I am not sure, that it is must have feature of Angular Framework, but probably some of you can show the way how I can achieve what I need without changing the code of Angular.

Probably it would be nice for some cases, to have some mechanism to compile component and its child components in specific zones (chilren of `angular` zone).

For example: we have 2 business parts in out application. For example, we have Shop part and Settings part in our app. I think it would be nice to compile components in shop part in some child zone of angular zone like `shop`. Settings part would be compiled in `settings` zone. Also, it would be nice to allow create hierarchy of zones. Like shop/cart or shop/sales or settings/profile, settings/subscription, settings/cards etc. Also, you can have shared reusable component which is used in settings and in shop modules. It would be compiled in settings/list and shop/list zones.

What are profits:
- easily debug how your application works (for example you have shared service with business logic or logger service and you can understand context in methods of such services).
- track contexts of API requests (for example in our app we have tons of requests and we can implement some monitoring on server side. we use such feature in AngularJS part of our application).

### Describe the solution you'd like
 If you have a solution in mind, please describe it.

Example:

```
@Component({
  selector: `app-shop-container`,
  template: `
    <app-profile-data></app-profile-data>
    <app-shop-cart></app-shop-cart>
    <app-shop-sales></app-shop-sales>
    <app-shop-goods></app-shop-goods>
  `,
  zone: `shop`
})
export class ShopCart {
}

@Component({
  selector: `app-shop-cart`,
  template: `
    <div></div>
  `,
  zone: `cart`
})
export class ShopCart {
  ngAfterViewInit() {
    fetchCart(); // this would be in zone shop/cart
  }
}

@Component({
  selector: `app-shop-goods`,
  template: `
    <div></div>
  `
})
export class ShopGoods {
  ngAfterViewInit() {
    fetchGoods(); // this would be in zone shop (since we don't have zone property in decorator
  }
}


@Component({
  selector: `app-settings-container`,
  template: `
    <app-profile-data></app-profile-data>
    <app-profile-edit></app-profile-edit>
  `
  zone: `settings`
})
export class ShopGoods {
  ngAfterViewInit() {
    fetchSomething(); // this would be in zone settings
  }
}

@Component({
  selector: `app-profile-data`,
  template: `
    <app-profile-data></app-profile-data>
    <app-profile-edit></app-profile-edit>
  `
  zone: `profile-data`
})
export class ShopGoods {
  ngAfterViewInit() {
    fetchProfile(); // this would be in zone settings/profile-data or shop/profile-data (it depends on place where component is rendered: in shop module, or in settings module
  }
}
```

All of these zones are children of `angular` zone, so they would not affect change detection, rendering and others.

I think it could be made by improvement of Component/Directive decorators. `zone` properties should be added there. This properties should somehow be stored in views which are created when application compiles. For example, in `view.zone` property. And final point that ngfactories of views/components (if I remember correctly it is about `view.def.updateDirectives`) should be called in `view.zone` zone. If zone was not passed to Component/Directive decorator, then zone from parent view would be in created view.

If anybody will use something like `NgZone.isInAngularZone` method in such zones he will get same result as now, since all of created zones are children of `angular` zone.

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

Our team tried some ways. I will describe one of them, which was the closest.

We tried to create our own decorator like Component which will call constructor and patch methods of the component. Patched methods are same methods, but with `zone.run` wrapper. Such decorator was able to accept `zoneName` property. This way does not work, since we got exception on AOT build.

Any way, this way is not what we need there. If I remember correctly, there was not any problem with calling `cdr.detectChanges` manually. Zones were correct in child components. But if component was created after calling `appRef.tick`, then zone was not correct (`angular` zone). It happened because some other part of application triggered `tick` and `changeDetection` from root.

Trying to run `appRef.tick` in some specific zone is not correct, since change detection in whole application would be performed in some specific zone.

Seems to me, correct way to solve the problem is running ngfactories of components in needed zones.

**Comment by trotyl** [comment] 2019-08-14 11:32
Relates to or duplicate of https://github.com/angular/angular/issues/27885

**Comment by sharikovvladislav** [comment] 2019-08-14 11:43
@trotyl thanks for your answer. #27885 is something very close, but with another purposes. My suggestion is also give some control to developers.

And also I have same problem as described in last message.

> I don't know any easy way to add this after. A custom decorators could take care of part, but there isn't DI that would allow me to get a ChangeDetectorRef.

I end up with same problem. I created some custom decorator which extends Component decorator (not very clear, but that works at the moment). In my opinion I should wrap `updateDirectives` method and run it in some zone (which is not very good too). Do you have any ideas how to do this?

**Comment by sharikovvladislav** [comment] 2019-08-15 07:06
@AndrewKushnir do we have any workarounds to achieve that at current version?

We use 8.1.1.

**Closed** 2022-04-14 23:53 UTC
Labels: feature, comp: core, insufficient votes, votes required
