### ISSUE TITLE
Add headers to lazy loading requests

### ISSUE THREAD

**Issue by Mark-McCracken** [angular/angular#28774] opened 2019-02-16 20:52 UTC
# 🚀 feature request

### Relevant Package
This feature request is for @angular/router

### Description
My application has some lazy loaded routes.
Depending on the user, I need to send them a slightly different module, with different features available. I don't want a web developer to simply issue a get request for the module and uncover the features that might be available to different users, so a route guard would not work. I'd like to attach a header for the requests for these lazy loaded modules, so my server can check the user's capabilities and respond with the correct module to lazy load.

### Describe the solution you'd like
Provide a way to append headers to lazy loaded module requests

### Describe alternatives you've considered
Server side rendering, but the goals of this process are quite different, and would involve signifcant rework of an app for what could otherwise be a small feature

**Comment by mlc-mlapis** [comment] 2019-02-16 21:32
@Mark-McCracken ... sounds like a case for a programmatic way to load such a module, so you can have any combinations which you need.

**Comment by trotyl** [comment] 2019-02-18 07:21
Duplicate of https://github.com/angular/angular/issues/23632

---

Not feasible, all chunks are loaded via `<script>` tag, not XHR, you cannot control how `<script>` is fetched.

<sub>If you're **NOT** using Webpack nor native browser `import` for code splitting, then you do can achieve it by your own loader, but it's not possible for Angular to do that.</sub>

**Comment by Mark-McCracken** [comment] 2019-02-18 07:46
Ok, sorry I did have a long look for similar issues but didn’t find that one.
This sounds really difficult.
Do you know of any existing resources that might help me achieve that, or can you point me in the right direction?
Barring that, I think this issue can be closed. Thanks so much for clarifying!

**Comment by trotyl** [comment] 2019-02-18 08:15
@Mark-McCracken I mean don't do that, loading JavaScript via XHR means abusing `eval()`, it should not happen in a prod environment. And it will never be possible when you switch to native ES module features in browser.

Better to fix your server-side implementation.

**Comment by Mark-McCracken** [comment] 2019-02-18 08:32
Ok I will definitely avoid that then.
So if this is the case, it sounds like the simplest and perhaps only solution, is to build and deploy 2 separate applications, and once the user is authenticated, redirect them to the correct one.

For my particular use case, I don’t think this won’t work because the users know they’re visiting distinct websites as they’d need a different URL.

Am I wrong about that do you think?

If I’m not, then I think this feels like an advanced enterprise type feature, do you think this is something Angular might consider adding the capability to do later?

**Comment by trotyl** [comment] 2019-02-18 08:38
JavaScripts are just static files, if you want authentication you'll need to protect your API.

**Comment by Mark-McCracken** [comment] 2019-02-18 08:46
Yeah, my APIs are already authenticated which is great as this stops users getting at the wrong data.

But if they were to inspect the static js files, they would see that there is another feature available, that they don’t have access to.
I’d rather send them different sets of static files, where it’s not obvious that there’s another feature, if you see what I mean.

What I’m really asking is, if there’s a way to effectively protect some of those static files

**Comment by mlc-mlapis** [comment] 2019-02-18 09:04
@Mark-McCracken ... maybe this post would be interesting for you: https://netbasal.com/the-need-for-speed-lazy-load-non-routable-modules-in-angular-30c8f1c33093

**Comment by trotyl** [comment] 2019-02-18 09:07
> But if they were to inspect the static js files, they would see that there is another feature available

@Mark-McCracken That would happen regardless of whether you prevent them from access of that module as the logic to retrieve lazy module lives in main module.

**Comment by jasonaden** [comment] 2019-04-09 22:59
Thanks for all the community help on this one. Closing as resolved.

**Closed by jasonaden** 2019-04-09 22:59 UTC
Labels: comp: router
