### ISSUE TITLE
Angular 16 failed to run when built

### ISSUE THREAD

**Issue by ptatoChi** [angular/angular#50248] opened 2023-05-11 06:49 UTC
### Which @angular/* package(s) are the source of the bug?

compiler, Don't known / other

### Is this a regression?

Yes

### Description

I've recently updated my Angular 15 to 16.  It runs normally when i use npm start. but when deploying it after ng build, it shows this error 

![image](https://github.com/angular/angular/assets/11557985/5473ce7e-1a98-4959-801a-7a4b03060b6d)

upon looking into the dist code, i saw this

![image](https://github.com/angular/angular/assets/11557985/6a169b66-38ed-4d96-b7eb-7796d38a99a0)

i checked some libraries, and it seems that its under \node_modules\@angular\compiler\esm2022\src\template\pipeline\ir\src\expression.mjs

![image](https://github.com/angular/angular/assets/11557985/30a1a8e2-a1bb-4643-a33f-afd5df557be1)

### Please provide the exception or error you saw

```true
I've provided screenshots above
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular 16
Node 19
Package manager: npm
OS: (tried to build both from windows 11 and ubuntu)
```

**Comment by dondelice257** [comment] 2023-05-11 09:29
I think it's not a source code's bug because for me it works correctly, try running 'npm install' to install all dependencies and then run 'ng serve'
if 'npm install' doesn't work, you can use 'yarn add ' instead

I hope that this helps, if you still encounter errors, please let me know

**Comment by JoostK** [comment] 2023-05-11 11:48
It is unclear to me how you're building the app. At least it seems like you're pulling in the JIT compiler. At the minimum we would need to know which builder you are using, but this would need a reproduction for us to actually investigate.

**Comment by ptatoChi** [comment] 2023-05-11 12:50
Oh I think you're right.  This is what i used to build.

`ng build --configuration production --build-optimizer=falseng build --configuration production --build-optimizer=false`

Now i just used `ng build` the app works fine. Thank you so much!

**Comment by dondelice257** [comment] 2023-05-11 16:01
It's a pleasure to hear that your issue has resolved, You're welcome

**Comment by AndrewKushnir** [comment] 2023-05-12 20:16
Closing this ticket as resolved for now, please reopen if needed.

**Closed by AndrewKushnir** 2023-05-12 20:16 UTC
Labels: needs reproduction

**Comment by ptatoChi** [comment] 2023-05-15 05:31
Hi. Sorry I brought this up again. 

I'm trying to narrow down why `--configuration production` is causing the issue of having the undefined error. 

It only happens when I set `optimization.scripts: true` under the configuration of angular.json. 
![image](https://github.com/angular/angular/assets/11557985/74d15b06-c455-4d76-b2a5-bff6bca654da)

Do you have any idea where should look into? My builder is set to @angular-devkit/build-angular:browser in case you're wondering.

I've updated everything to 16.0.1, deleted node_modules, deleted package-lock.json, and it still produce the same result.
