### ISSUE TITLE
Property 'map' does not exist on type '{}'.ts(2339) on service.ts 

### ISSUE THREAD

**Issue by ruhaifie** [angular/angular#30647] opened 2019-05-24 01:11 UTC
![1](https://user-images.githubusercontent.com/47075903/58295650-f8294780-7e02-11e9-814f-dd9deb50538a.png)
![2](https://user-images.githubusercontent.com/47075903/58295652-f8294780-7e02-11e9-89a0-54cff3a79678.png)

# 🐞 bug report

### Description
there are 2 problems about which is:
Property 'map' does not exist on type '{}'.ts(2339)
Property 'id' does not exist on type '{}'.ts(2339)

Please help me,im new to coding and i still learning to use the firebase storage

## 🌍  Your Environment

**Angular Version:**
Angular CLI: 7.3.9
Node: 10.15.3
OS: win32 x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.13.9
@angular-devkit/core         7.3.9
@angular-devkit/schematics   7.3.9
@schematics/angular          7.3.9
@schematics/update           0.13.9
rxjs                         6.3.3
typescript                   3.2.4

**Comment by dblVs** [comment] 2019-05-28 12:32
@ruhaifie This is not a bug with angular itself. Please refer to https://github.com/angular/angular/blob/master/CODE_OF_CONDUCT.md . if you need further help you can ask in the gitter for angular. The issue is that you haven't put a type on the map functions. you need to put a type to actions and idea. I think this issue needs closing

**Comment by matsko** [comment] 2019-05-28 22:19
Closing since this doesn't have anything to do with angular/angular.

**Closed by matsko** 2019-05-28 22:19 UTC
Labels: type: bug/fix

**Comment by ruhaifie** [comment] 2019-05-29 19:49
tq

> @ruhaifie This is not a bug with angular itself. Please refer to https://github.com/angular/angular/blob/master/CODE_OF_CONDUCT.md . if you need further help you can ask in the gitter for angular. The issue is that you haven't put a type on the map functions. you need to put a type to actions and idea. I think this issue needs closing



> Closing since this doesn't have anything to do with angular/angular.

tq,im still new ^^
