### ISSUE TITLE
[Service Worker] Can't update sw if in SAFE_MODE

### ISSUE THREAD

**Issue by sean-nicholas** [angular/angular#22087] opened 2018-02-08 09:57 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
When the service worker is installed / initialized the first time, it fetches the `ngsw.json`. If the content of `ngsw.json` is not an valid json the sw goes into SAFE_MODE:

https://github.com/angular/angular/blob/c8a1a14b87e5907458e8e87021e47f9796cb3257/packages/service-worker/worker/src/driver.ts#L320-L325

From thereon it is impossible to update the service worker. If you call `SwUpdate.checkForUpdate()` it never resolves or rejects and no new fetch to `ngsw.json` is performed due to the fact that messages are ignored in SAFE_MODE:

https://github.com/angular/angular/blob/c8a1a14b87e5907458e8e87021e47f9796cb3257/packages/service-worker/worker/src/driver.ts#L189-L193

Replacing the wrong `ngsw.json` with the correct one does only resolve this issue if:
* the service worker is unregistered (if `ngsw.json` did not contain json. for example it contains html)
* or the sw is unregistered and the cache is cleared (if `ngsw.json` did contain a json. ex: `{ "test": 123 }`).
This also triggers the following error: `Error: Invariant violated (initialize): latest hash null has no known manifest`

This issue occurred on our firebase hosted app. It seems a cache sometimes returns a html page with a 2xx status instead of the `ngsw.json` and broke our service worker. We also needed to clear the cache and unregister the service worker on some mobile clients. It might be that firebase sends sometimes a wrong json file or there might be another way to lock the service worker in the SAFE_MODE with `latest hash null` error. 

## Expected behavior
* It should be possible to update the sw with `SwUpdate.checkForUpdate()` when the sw is in SAFE_MODE
* Maybe the sw should try to refetch the `ngsw.json`? I'm not sure when and if this would be the appropriated way to handle this issue.

## Minimal reproduction of the problem with instructions
Repo: https://github.com/sean-nicholas/test-angular-service-worker

* run `npm run build`
* `cd` into `dist``
* change the content of `ngsw.json` to 
  * For non json case: `asdjknkfdnjgdfkaslkdm` 
  * For json case: `{ "test": 123 }`
* run `http-server` (or something similar) in `dist` folder
* goto localhost in incognito mode
* you get the error
  * For non json case: `Unexpected token a in JSON at position 0`
  * For json case: `TypeError: Cannot convert undefined or null to object`
* sw installation fails and sw goes into SAFE_MODE
* reload & press the `Check for SW Update` Button
* `Checking` will stay true and not fall back to false after a few ms
* Replace the content of `ngsw.json` with the correct data

For non json case:
* Unregister the sw & reload -> it works again

For json case:
* Unregister the sw & reload
* Error: `Error: Invariant violated (initialize): latest hash null has no known manifest` occures
* `Check for SW Update` seems to work but if you reload it fails (does not resolve) again
* Clear the cache, unregister the sw & reload -> it works again

## What is the motivation / use case for changing the behavior?
The service worker should not lock itself into a state were it can not be updated anymore.

## Environment

<pre><code>
"@angular/animations": "^5.2.4",
"@angular/cdk": "^5.2.0",
"@angular/common": "^5.2.4",
"@angular/compiler": "^5.2.4",
"@angular/core": "^5.2.4",
"@angular/forms": "^5.2.4",
"@angular/http": "^5.2.4",
"@angular/material": "^5.2.0",
"@angular/platform-browser": "^5.2.4",
"@angular/platform-browser-dynamic": "^5.2.4",
"@angular/router": "^5.2.4",
"@angular/service-worker": "^5.2.4"

Browser:
(Only tested in)
- [x] Chrome (desktop) version 64.0.3282.140
- [x] Chrome (Android) version 64.0.3282.137
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 </code></pre>

**Comment by alxhub** [comment] 2018-02-15 23:17
Once the SW enters a degraded state (SAFE_MODE), it will stay there - it's not possible to exit such a state from the application.

A restart of the SW should end up in a good state though, provided `ngsw.json` is valid. I'll investigate whether that's the case.

**Comment by sean-nicholas** [comment] 2018-02-15 23:41
Thanks for investigating 😊.

What do you think about a function on `SwUpdate` that could get the mode / state from the SW, so the application could un- and reregister the SW?

A current workaround would be to call `SwUpdate.checkForUpdate()` and check if the promise does not resolve or rejected within a given time and then unregister the SW. Well, this should not be the standard way to do it, because the not resolving / rejecting promise might be another issue.

**Comment by petivagyok16** [comment] 2018-02-19 12:20
Im experiencing the same issue. `swUpdate.checkForUpdate()` promise never gets resolved/rejected, so that now i cannot trigger manually the refreshing in my app.

**Comment by gkalpak** [comment] 2018-03-20 14:00
Hopefully the DevTools related issues will be fixed by #22883, @petivagyok16. 

##
But it does seem that after entering `SAFE_MODE`, you are unnecessarily stuck in there for good :grin:
Theoretically, you should be able to cause the SW to unregister itself by removing `ngsw.json` from the server (i.e. return 404) which doesn't seem to work, since SW ignores all messages/requests (as @sean-nicholas said).

Also, I can't think of any reason not to process `checkForUpdates()` when in `SAFE_MODE` (and exit `SAFE_MODE` if an update is successfully activated).

@alxhub, wdyt? Also what does "a restart of the SW" mean?

**Comment by k-schneider** [comment] 2018-04-17 01:02
I was just hit by this on my dev machine and had a hell of a time figuring out what happened.  Unregistering the service worker wasn't enough... had to unregister AND clear my cache in Chrome.  If this were to ever affect an end user they wouldn't stand a chance.

**Comment by fscamuzzi2** [comment] 2019-04-19 08:22
Hi .. same problem here :


ngsw-worker.js:2270 Uncaught (in promise) Error: Invariant violated (assignVersion): want AppVersion for null but not loaded
    at Driver.lookupVersionByHash (ngsw-worker.js:2270)
    at Driver.<anonymous> (ngsw-worker.js:2287)
    at Generator.next (<anonymous>)
    at ngsw-worker.js:1783
    at new Promise (<anonymous>)
    at ngsw-worker.js:1779
    at Driver.assignVersion (ngsw-worker.js:2278)
    at Driver.<anonymous> (ngsw-worker.js:2124)
    at Generator.next (<anonymous>)
    at fulfilled (ngsw-worker.js:1780)



If i clear chache and hit CTRL + F5 the service worker throw error and app crash.

**Comment by gkalpak** [comment] 2019-07-26 20:41
As mentioned above, the current behavior is by design. The degraded modes will not persist across instances, so once the browser terminates the SW instance after a period of inactivity, the mode will go back to `NORMAL` again.

See, also, #31109 for a related discussion about the `EXISTING_CLIENTS_ONLY` mode specifically.
#31865 (if we decide to merge it), will make the `EXISTING_CLIENTS_ONLY` mode recoverable, since we have more info about the reasons that could have led to entering that mode.

`SAFE_MODE` on the other side can be a result of any unanticipated issue and will be far more riskier to try and recover from.

##
So, I am going to close this issue as `won't fix`.

That said, I think it might be reasonable to expose the driver state as a service (or maybe expose the whole debug info (including the driver state) as JSON).

Free free to open a feature request for that.

An ugly work-around for now, would be to request [/ngsw/state][1] and parse the text content to extract the driver state. E.g.:

```ts
fetch('/ngsw/state').
  then(res => res.text()).
  then(text => (text.match(/Driver state: (\w+)/) || [, 'UNKNOWN'])[1]);
```

[1]: https://angular.io/guide/service-worker-devops#locating-and-analyzing-debugging-information

**Closed by gkalpak** 2019-07-26 20:41 UTC
Labels: comp: service-worker, freq2: medium, severity3: broken, type: bug/fix
