### ISSUE TITLE
NG600 is probably to vague / a bit misleading. 

### ISSUE THREAD

**Issue by JeanMeche** [angular/angular#50476] opened 2023-05-25 21:09 UTC
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

Our beloved NG600 (```Writing to signals is not allowed in a `computed` or an `effect` by default. Use `allowSignalWrites` in the `CreateEffectOptions` to enable this inside effects.``` ) is an error that arrises frequently atm due to people playing a lot with signals. 

From the errors I have been seeing, it seems that the error message is a bit misliding. The error occurs when the is no obvious effect in play. 

For example here, a synchronous tap triggered from the template. 
```
@Component({
  selector: 'my-app',
  template: `Current Count: {{ counter$|async }}`,
})
export class AppComponent {
  private dummy = signal(0);

  private counterSubject = new BehaviorSubject(0);
  counter$ = this.counterSubject.pipe(tap(() => this.dummy.set(1)));
}
```

Edit: Pawel already mentionned [in this comment](https://github.com/angular/angular/issues/49967#issuecomment-1519627030), the reason of why it happens here and that the message does need improvement.

**Comment by pkozlowski-opensource** [comment] 2023-09-15 09:15
Hmm, it looks like we've broken something in this error reporting in the rewrite since I can't reproduce the NG600 error any more with the latest version of the signals library, tried here:
https://stackblitz.com/edit/stackblitz-starters-kcajjq?file=src%2Fmain.ts 

@JeanMeche is this is the scenario that you had on your mind? 

In any case it needs more investigation!

**Comment by pkozlowski-opensource** [comment] 2023-09-15 15:15
OK, "mystery" solved. With #50522 merged we no longer track async pipe subscriptions so the ` {{ counter$|async }}` effectively runs without a reactive consumer. 

There is another, albeit more convoluted, way of reproducing the same confusing error message: https://stackblitz.com/edit/stackblitz-starters-kcajjq?file=src%2Fmain.ts

So I still think that we should update the logic to allow reactive consumers to specify heir error message (or at least part of it). One idea there would be to extend `consumerAllowSignalWrites` flag to be either a boolean or a string with an error message. Or introduce names of reactive nodes (which we kind of avoided so far).

**Closed** 2024-04-07 07:56 UTC
Labels: hotlist: error messages, area: core, core: reactivity, cross-cutting: signals
