### ISSUE TITLE
Compilation issue with Angular 5

### ISSUE THREAD

**Issue by AbinayaSubbiah** [angular/angular#20140] opened 2017-11-03 09:05 UTC
Hi

I am facing below compilation issue in webpack.

`ERROR in [at-loader] ./node_modules/@angular/platform-browser/src/browser/transfer_state.d.ts:34:40
    TS1005: ',' expected.

ERROR in [at-loader] ./node_modules/@angular/platform-browser/src/browser/transfer_state.d.ts:34:42
    TS1139: Type parameter declaration expected.

ERROR in [at-loader] ./node_modules/@angular/platform-browser/src/browser/transfer_state.d.ts:34:46
    TS1109: Expression expected.

ERROR in [at-loader] ./node_modules/@angular/platform-browser/src/browser/transfer_state.d.ts:34:51
    TS1005: ')' expected.

ERROR in [at-loader] ./node_modules/@angular/platform-browser/src/browser/transfer_state.d.ts:34:59
    TS1005: ';' expected.

ERROR in [at-loader] ./node_modules/@angular/platform-browser/src/browser/transfer_state.d.ts:34:60
    TS1128: Declaration or statement expected.

ERROR in [at-loader] ./node_modules/@angular/platform-browser/src/browser/transfer_state.d.ts:34:73
    TS1005: '(' expected.

ERROR in [at-loader] ./node_modules/@angular/platform-browser/src/browser/transfer_state.d.ts:34:42
    TS2532: Object is possibly 'undefined'.

ERROR in [at-loader] ./node_modules/@angular/platform-browser/src/browser/transfer_state.d.ts:34:48
    TS2304: Cannot find name 'key'.

ERROR in [at-loader] ./node_modules/@angular/platform-browser/src/browser/transfer_state.d.ts:34:53
    TS2304: Cannot find name 'string'.

ERROR in [at-loader] ./node_modules/@angular/platform-browser/src/browser/transfer_state.d.ts:34:62
    TS2693: 'StateKey' only refers to a type, but is being used as a value here.`

my package.json is

    dependencies": {
    "@angular/common": "~5.0.0",
    "@angular/compiler": "~5.0.0",
    "@angular/core": "~5.0.0",
    "@angular/forms": "~5.0.0",
    "@angular/http": "~5.0.0",
    "@angular/platform-browser": "~5.0.0",
    "@angular/platform-browser-dynamic": "~5.0.0",
    "@angular/router": "~5.0.0",
    "@angular/upgrade": "~5.0.0",
    "core-js": "^2.4.1",
    "rxjs": "^5.4.3",
    "zone.js": "^0.7.4",
    "@types/jquery": "2.0.34",
    "@types/node": "6.0.52",
    "angular-in-memory-web-api": "0.1.1",
    "bootstrap": "^3.3.6",
    "jquery-validation": "^1.16.0",
    "reflect-metadata": "^0.1.10"
    },
    "devDependencies": {
    "angular2-router-loader": "^0.3.5",
    "angular2-template-loader": "~0.6.2",
    "awesome-typescript-loader": "~3.1.3",
    "bootstrap": "^3.3.6",
    "css-loader": "^0.26.1",
    "extract-text-webpack-plugin": "~2.1.2",
    "file-loader": "~0.11.1",
    "html-loader": "~0.4.5",
    "html-webpack-plugin": "^2.16.1",
    "null-loader": "^0.1.1",
    "phantomjs-prebuilt": "^2.1.7",
    "protractor": "~4.0.14",
    "raw-loader": "^0.5.1",
    "rimraf": "^2.5.4",
    "style-loader": "^0.13.1",
    "tslint": "^3.15.1",
    "typescript": "~2.2.0",
    "uglifyjs-webpack-plugin": "^1.0.0-beta.1",
    "url-loader": "^0.5.8",
    "webpack": "~2.7.0",
    "webpack-dev-server": "~2.4.5",
    "webpack-merge": "~4.1.0"
    }

![image](https://user-images.githubusercontent.com/21117461/32371448-ea2eb59e-c0b6-11e7-84a0-0faf67950b2d.png)

**Comment by trotyl** [comment] 2017-11-03 15:00
Duplicate of #20109?

**Comment by vicb** [comment] 2017-11-03 17:18
I'm sorry but we don't understand the problem you are reporting.

If the problem still exists please open a new issue and provide a plunker reproducing the problem and describing the difference between the expected and current behavior. You can use this plunker template: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue

**Closed by vicb** 2017-11-03 17:18 UTC

**Comment by tettusud** [comment] 2017-11-05 01:56
@AbinayaSubbiah you found any solution?

**Comment by tettusud** [comment] 2017-11-05 15:44
@AbinayaSubbiah i am able to resolve it by updating the relevant packages to latest version you can take a look at this sample repo https://github.com/tettusud/angular-electron

**Comment by TheThingRus** [comment] 2017-11-14 13:24
I have the same problem while upgrading.

**Comment by alzdrak** [comment] 2017-11-20 09:02
Not sure if this will help anyone, but in my case I'm using visual studio 2015, and I just needed to upgrade my Typescript Tools for Visual Studio 2015 to 2.6.1.

**Comment by coryshaw1** [comment] 2017-11-22 18:59
As @alzdrak stated, you need to update your typescript dependency to the latest. I updated mine to "^2.6.1" and the errors went away

**Comment by wohral** [comment] 2018-01-25 13:27
After you install new version of Typescript Tools for VS, make sure you change TypeScript Build on your project
[](https://github.com/Microsoft/TypeScript/wiki/Updating-TypeScript-in-Visual-Studio-2017#setting-typescript-versions-in-visual-studio-2017-version-153)
