### ISSUE TITLE
[Request] initialize templateRef inside ts file

### ISSUE THREAD

**Issue by arnotes** [angular/angular#40980] opened 2021-02-24 14:41 UTC
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

We have a rare use case where we have a dynamic component that supports @Input templateRef and I was wondering if its possible are there are any plans to do something like this
`
public myTemplate: templateRef<any> = new templateRef('
    <ng-template let-name="name">hello {{ name }}<.ng-template>
');
`

right now the approach we use is to component it but we dont like the idea of having tons of ngSwitchCase convoluted on html
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by jelbourn** [comment] 2021-03-05 21:54
Duplicate of #15275

**Closed by jelbourn** 2021-03-05 21:54 UTC
Labels: comp: core
