### ISSUE TITLE
Improve tree shake- and compressability of angular

### ISSUE THREAD

**Issue by sod** [angular/angular#40997] opened 2021-02-25 17:50 UTC
If you create a blank angular project with @angular/cli and build it in production mode:
`npm i -g @angular/cli; ng new ng-test; cd ng-test; ng build --prod`
things you find in the bundle (354kb):

* https://angular.io/api/common/HashLocationStrategy (even though this is opt-in and not enabled by default)
* unused code that adds `window.ng` in dev mode (e.g. search for `addToWindow`)
* full blown HTML sanitizer, even if you never use `[innerHTML]`
* locale data even if you don't use it (e.g. search for `NumberFormats`)
* 70kb of @angular/router (is that thing tree shakeable? For comparison, vue-router tree shakes every feature you don't use and at max grows to 27kb!)
* if I just need a binding on an input, let's say `<input [ngModel]="foo">`, I have to import FormsModule => thats gonna be 33kb extra

<details>
  <summary>Edit: Irrelevant stuff because I compiled with `"compilationMode": "partial"`:</summary>
  
* ~code to support annotations even though your compiler removes the annotations at build time (e.g. search for `__prop__metadata__` or `propMetadata`)~
* ~pre-ivy debug code (e.g. search for `._debugContext` which belongs to `DebugNode__PRE_R3__`)~
* ~more debug code (e.g. search for `setCurrentNode:`, where one of those belong to `createDebugServices` with all its debug helper methods)~
* ~code that is only used in dev mode (e.g. search for `ng-reflect-` which belongs to `normalizeDebugBindingName`)~
* ~code that is only used in tests like `DebugRenderer2` (e.g. search for `.createDebugContext`~
* ~tons of translations capabilities, even if you don't use angular for translating or don't translate at all (e.g. search for `ICU`)~
* ~runtime templateUrl resource resolver, even when you compile with `directTemplateLoading: true`~
</details>

This seems highly unoptimized. Pretty sad given that angular itself is darn fast, but loses big time in the total blocking time department as the browser has to parse and run all this stuff thats not even used.

**Comment by AndrewKushnir** [comment] 2021-02-25 18:59
Hi @sod, thanks for creating this ticket.

I've tried to reproduce this and built a new app using the most recent version of CLI (v11.2.2). After that I ran the build command in prod mode (`ng build --prod`) and the main.js file was 134.97 KB. After that I've built the bundle with additional flags to avoid minification:
```
NG_BUILD_MANGLE=false NG_BUILD_MINIFY=false NG_BUILD_BEAUTIFY=true ng build --prod
```
and inspected the `main.js` file. I didn't find most of the symbols that you refer to.

Could you please create a repo with the current state of your test app (including the `dist` folder after the build) and share a link?

Thank you.

**Comment by sod** [comment] 2021-02-25 20:14
Half the points were my fault I guess. ~crossed them out~ in the initial comment. Had `"compilationMode": "partial"` active.

So just left why router is 70kb, why forms is 33kb if you just need ngModel.

**Comment by AndrewKushnir** [comment] 2021-02-26 08:27
@sod thanks for additional information. Forms and Router heavily use classes, which do not tree-shake well (i.e. if class is used, all its logic is retained). In any case, there is still a chance for improvement and I've created ticket #41011 with additional results from my investigation (which was focused on Forms package). I'm going to close this ticket in favor of #41011. Thank you.

**Closed by AndrewKushnir** 2021-02-26 08:27 UTC
Labels: comp: core, comp: forms, comp: router, cross-cutting: tree-shaking, needs clarification, needs reproduction

**Comment by indraraj26** [comment] 2021-02-26 10:14
Hi @atscott ,

Can you please look into Router package as well

Thank you

**Comment by itea-dev** [comment] 2021-02-28 23:21
Improving tree shaking and reducing the bundle size of default blank app generated by CLI will allow more users to take advantage of Angular features.

At present we have some embedded apps built with Vue because we can't fit in Angular. And I would like in the near future to use Angular for all our apps and be able to use the same libraries, styles, project structure and coding standards we already have and use in our current Angular apps.

**Comment by AndrewKushnir** [comment] 2021-03-01 17:51
Hi @indraraj26, thanks for the comment. We do plan to perform similar investigation with the focus on the Router package, but there is not ETA at this moment. We'll share more info once we have it. Thank you.
