### ISSUE TITLE
Required checkbox inside form not validating properly

### ISSUE THREAD

**Issue by asotog** [angular/angular#12401] opened 2016-10-20 01:30 UTC
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When i have checkbox inside a form with required attribute, if its unchecked, the validation is passing
```
<label for="acceptance" class="form-check-label" 
     [ngClass]="{'field-error-text': acceptance.errors && acceptance.errors.required}">
   <input [(ngModel)]="contact.acceptance" 
       #acceptance="ngModel" id="acceptance" 
       name="acceptance" type="checkbox" class="form-check-input" 
       required> Please accept lorem ipsum terms conditions.
 </label>
```
submit button is always enabled on unchecked field
```
<button (click)="submit()" [disabled]="!contactForm.form.valid" type="submit" class="btn btn-primary">Submit</button>
```
all this code is inside a form tag like 
```
<form #contactForm="ngForm">
```

**Expected behavior**

If an input is required, validation should not pass and in this case, button should be disabled

**Minimal reproduction of the problem with instructions**
I was able to reproduce the behavior even on plunkr
http://plnkr.co/edit/iG5fpGo8DqHtIKLnrDrp?p=preview

**What is the motivation / use case for changing the behavior?**
For example the use case here is a terms and conditions acceptance, so user has to accept the check all the time

**Please tell us about your environment:**
El Capitan, MacOS, Atom, NPM, browser sync

* **Angular version:** 2.0.X
Tried on 2.1

* **Browser:** 
Tried Chrome 53, but probably same on other browsers
 
* **Language:**
Typescript

* **Node (for AoT issues):**  = 
v5.2.0

**Comment by ericmartinezr** [comment] 2016-10-20 02:03
See https://github.com/angular/angular/issues/11459

**Comment by asotog** [comment] 2016-10-20 02:08
thanks @ericmartinezr  so it's an issue already ?

**Comment by pkozlowski-opensource** [comment] 2016-10-20 08:23
Closing as a duplicate of #11459

**Closed by pkozlowski-opensource** 2016-10-20 08:23 UTC
