### ISSUE TITLE
Two-way data binding doesn't work on Select field in Angular2.0.0-beta.1

### ISSUE THREAD

**Issue by kbugala** [angular/angular#6721] opened 2016-01-27 17:57 UTC
This works in Beta.0 but doesn't work in Beta.1

```<select [(ngModel)]="name"> <option *ngFor="#n of names" [value]="n">{{n}}</option> </select> {{name}}```

the current workaround in beta-1:

template.html:

```<select class="form-control" #t (change)="update(t.value)"> <option *ngFor="#type of types" [value]="type">{{type}}</option> </select>```

in component.ts
```
update(value){
    console.log(value);
    this.name=value;
  }```

**Comment by eostrom** [comment] 2016-02-01 03:10
Duplicate of #6573, which should probably have "select" added to its title.

**Comment by kara** [comment] 2016-04-20 03:52
Yeah, this looks like a dupe of #6573, so closing!  Feel free to track in the other issue :)

**Closed by kara** 2016-04-20 03:52 UTC
