### ISSUE TITLE
Combine multiple "| async as" in the same ngIf

### ISSUE THREAD

**Issue by nicolaric** [angular/angular#43907] opened 2021-10-20 13:39 UTC
### Which @angular/* package(s) are relevant/releated to the feature request?

common

### Description

Currently it is not possible to have the following:
```
<ng-container *ngIf="(data1$ | async as data1) && (data2$ | async as data2)">
  <div>{{ data1 }}</div>
  <div>{{ data2 }}</div>
</ng-container>
```

Workarounds are as follow:
```
<ng-container *ngIf="data1$ | async as data1">
  <ng-container *ngIf="data2$ | async as data2">
    <div>{{ data1 }}</div>
    <div>{{ data2 }}</div>
  <ng-container>
</ng-container>
```

Or even something like this:
```
// TS
data$ = combineLatest([
  data1$,
  data2$
]).pipe(
  map(([data1, data2]) => ({
    data1,
    data2
  }))
)

<!-- HTML -->
<ng-container *ngIf="data$ | async as data">
  <div>{{ data.data1 }}</div>
  <div>{{ data.data2 }}</div>
</ng-container>
```

This, in my eyes, is not super clean and is more difficult to read. It would be very helpful to extend the `as` keyword for this.

### Proposed solution

As described above, it would be super clean to have something like this:
```
<ng-container *ngIf="(data1$ | async as data1) && (data2$ | async as data2)">
  <div>{{ data1 }}</div>
  <div>{{ data2 }}</div>
</ng-container>
```

### Alternatives considered

I don't see any alternatives, except of using the workarounds which I use today already.

**Comment by teamIgal** [comment] 2022-09-14 14:01
hi would like to add a similar question can i use this in like this <div *ngIf="(cars$ | async as cars)?.length">
i couldnt find if this is possible.
i know i can use 2 ngIf statements with ng-container like this
<ng-container *ngIf="cars$ | async as cars">
     <div *ngIf="cars.length">
the first example is just more simple and i dont have to add the ng-container that has no actual use.

**Comment by alxhub** [comment] 2023-12-15 16:48
I'm going to close this issue as a duplicate of #15280 - fundamentally this is a request for template local variables.

**Closed by alxhub** 2023-12-15 16:48 UTC
Labels: feature, area: common, feature: under consideration, common: async pipe
