### ISSUE TITLE
NgIf doesn't work properly in case of async event 

### ISSUE THREAD

**Issue by marcoCatto** [angular/angular#46350] opened 2022-06-13 07:15 UTC
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

I have an ngIf controlling the visibility of a DOM element. For a moment the element is visible even if the ngIf should hide it.

In the test, the ngIf shows either a div with "hello word" text or the MyComponentComponent component. A promise in the OnInit of the main component shows MyComponentComponent when resolved.

In the onInit of MyComponentComponent, I check if the "hello world" div is still visible. The check returns true, while it should return false. With a breakpoint in the onInit of MyComponentComponent it is possible to see that both the "hello world" div and MyComponentComponent are rendered, while just one of the two should be.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-kzusn8?embed=1&file=src/app/my-component/my-component.component.ts

### Anything else?

The bug is present when an async event is thrown, not only with a promise.

**Comment by JoostK** [comment] 2022-06-13 08:01
As @Totati indicates. This is an exact duplicate of #46320 without any more info.

**Closed by JoostK** 2022-06-13 08:01 UTC
