### ISSUE TITLE
ngComponentOutlet

### ISSUE THREAD

**Issue by dh05011984** [angular/angular#54123] opened 2024-01-28 11:12 UTC
### Describe the problem that you experienced

on clicking this page not found error received.
please find the below url
https://angular.dev/api/core/NgComponentOutlet

### Enter the URL of the topic with the problem

https://angular.dev/guide/components/programmatic-rendering

**Comment by JoostK** [comment] 2024-01-28 12:00
Thanks for the report, closing as a duplicate of https://github.com/angular/angular/issues/52828 for which the fix is pending deployment.

**Closed by JoostK** 2024-01-28 12:00 UTC
