### ISSUE TITLE
Disappearing Child Components using ViewContainerRef

### ISSUE THREAD

**Issue by cgolden1a** [angular/angular#11640] opened 2016-09-15 19:41 UTC
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see 
**Current behavior** 
While using ViewContainerRef to add nested dynamic children to a component, If you use NgIf to toggle visibility on the first child it will lose reference to all nested children following after it. 

**Expected behavior**
When toggling visibility using NgIf the current component structure made by dynamically adding components remain.

**Reproduction of the problem**
http://plnkr.co/edit/Vyk4QUSPirSVmIyRS5CV?p=preview

**What is the motivation / use case for changing the behavior?**
Dynamically laying out components for a designer while allowing the user to minimize and expand areas they have already worked on 

**Please tell us about your environment:**
windows 10, visual studio

* **Angular version:** 2.0.0-release

* **Browser:**
chrome | edge have not checked all
 
* **Language:** Type Script
 
* **Node (for AoT issues):** `node --version` =

**Comment by pkozlowski-opensource** [comment] 2016-09-15 19:49
This is not how it works - if you've got `ngIf` around something it is going to create / destroy the entire tree of components below it. It is not even related to dynamically created components (although the effect is more pronounced with them) - you would see the same with nested ngIfs.

You've got several ways of achieving the visual effect you are looking for:
* don't use ngIf but hide parts of the DOM instead
* keep state outside of a component

State management in large component trees _is_ hard but the bottom line is that ngIf creates / destroys entire component trees.

Going to close this one as I believe that it works as intended.

**Closed by pkozlowski-opensource** 2016-09-15 19:49 UTC

**Comment by cgolden1a** [comment] 2016-09-15 20:23
thank you for your time
