### ISSUE TITLE
Components with class selector do not initialize when Ivy is enabled

### ISSUE THREAD

**Issue by dmosemann** [angular/angular#36689] opened 2020-04-17 13:42 UTC
# 🐞 bug report

### Affected Package
Not sure which package, related to Ivy

### Is this a regression?
Yes, the previous version in which this bug was not present was: Angular 8, or Angular 9 with Ivy disabled

### Description
A component with a class selector does not initialize if there is also an interpolated variable in the class attribute. Example:

**icon.component.ts**
`@Component { selector: '.icon', template: '<svg><use attr.xlink:href="{{iconFilePath}}#{{iconName}}"></use></svg>'}`

**button.component.html**
`<i class="icon {{icon}}"></i>`

If there is no interpolated variable in the class attribute it works as expected.
**button.component.html**
`<i class="icon my-icon"></i>`

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-t48rmp

## 🔥 Exception or Error
None.

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.1.1
Node: 10.15.0
OS: darwin x64

Angular: 9.1.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.901.1
@angular-devkit/build-angular      0.901.1
@angular-devkit/build-ng-packagr   0.901.1
@angular-devkit/build-optimizer    0.901.1
@angular-devkit/build-webpack      0.901.1
@angular-devkit/core               9.1.1
@angular-devkit/schematics         9.1.1
@angular/cli                       9.1.1
@ngtools/webpack                   9.1.1
@schematics/angular                9.1.1
@schematics/update                 0.901.1
ng-packagr                         9.1.1
rxjs                               6.5.5
typescript                         3.8.3
webpack                            4.42.0
</code></pre>

**Comment by pkozlowski-opensource** [comment] 2020-05-07 13:36
Yep, this is a confirmed bug - it seems like we are not matching directives on the interpolated `class` attribute. To be honest I'm a bit surprised that it worked in VE since the class name is dynamic. But yes, this is clearly difference in the behaviour.

**Comment by alxhub** [comment] 2022-02-11 00:41
Closing as we don't intend to fix this issue. At the core here, the problem is that `class="icon {{icon}}` causes the whole attribute to become dynamically valued (an interpolation), and the compiler/runtime don't match selectors against dynamic attribute values.

A workaround is to express two class attributes instead: `class="icon" class="{{icon}}"`.

**Closed by alxhub** 2022-02-11 00:41 UTC
Labels: type: bug/fix, freq1: low, regression, comp: core, engine: ivy, state: confirmed, core: styling bindings, core: directive matching, triage #1, P2
