### ISSUE TITLE
RC1 Memory leak when NgIf present in the parent scope of NgFor

### ISSUE THREAD

**Issue by ValeriiVasin** [angular/angular#8566] opened 2016-05-10 09:43 UTC
**Steps to reproduce and a minimal demo of the problem**

Plunkr: http://plnkr.co/edit/IIZFhPWaFDIRSg0fmEAB?p=preview

_What steps should we try in your demo to see the problem?_
* See two children on the page, and the message, that only 2 children are alive.
* Click update button
* See that another 2 items with new uuids appeared;
* See that more then 2 components are alive already
* Do click on the BODY to see (in console) that mentioned children are really alive

**Current behavior**
Each second component is not destroyed.

**Expected/desired behavior**
All components should properly be destroyed (you should have every time 2 children alive on the page)

**Other information**
* In angular2-beta.15 issue does not exist. Components created / destroyed properly.
* Also interesting part is that each 2nd component in ng-for is not destoyed.
* If you remove ngIf from parent - everything will work as expected

**Comment by igorzg** [comment] 2016-05-12 10:43
+1

**Comment by ValeriiVasin** [comment] 2016-05-12 17:24
@igorzg Could be ngFor or their conjunction or smth else :) Just spotted here the case i was able to reproduce.

**Comment by tbosch** [comment] 2016-05-12 18:00
I think this is a duplicate of #8458 which was already fixed on master but not yet released.

**Comment by igorzg** [comment] 2016-05-12 18:02
@ValeriiVasin I introduced a big memory leak in app when I update to rc from beta.15 :)

**Comment by igorzg** [comment] 2016-05-12 18:06
@ValeriiVasin @tbosch but I se allot live objects holding from DebugNode. Looks to me like not all listeners are detached there while removing nodes.

![screen shot 2016-05-12 at 20 05 25](https://cloud.githubusercontent.com/assets/1614531/15225082/ecc6bc54-187c-11e6-8e42-c3def1c23328.png)

**Comment by igorzg** [comment] 2016-05-12 18:11
@tbosch  I can see here only parent is nullified but listeners ware never removed while detaching node:

[](https://github.com/angular/angular/blob/master/modules/%40angular/core/src/debug/debug_node.ts#L74)

And here

[](https://github.com/angular/angular/blob/master/modules/%40angular/core/src/debug/debug_node.ts#L89)

**Comment by ValeriiVasin** [comment] 2016-05-12 18:11
@tbosch Yes, it looks like duplicate. Thanks for the response, guess you could mark issue as duplicate.

**Comment by IgorMinar** [comment] 2016-05-12 20:17
closing as dupe of #8458

**Closed by IgorMinar** 2016-05-12 20:17 UTC
