### ISSUE TITLE
ngClass not working

### ISSUE THREAD

**Issue by CodeJason** [angular/angular#7232] opened 2016-02-23 00:12 UTC
Followed the docs exactly and the ng class key:value method where value is boolean isn't working.
- beta 2.0.0-beta.7

**Comment by thelgevold** [comment] 2016-02-23 01:31
From what I can tell, there doesn't seem to be an issue with ngClass in beta 7

`
<div [ngClass]="{myClass:condition}"></div>
`

I tried the above and it worked.

**Comment by Sabartius** [comment] 2016-02-23 11:47
Have you set the directives on your Component?

For NgClass to work you need to set:

`View({`
`   directives: [NgClass]`
`})`

on your Component

**Comment by ericmartinezr** [comment] 2016-02-23 11:48
@Sabartius no, he doesn't need to add it in the directives. What he needs to do is to make a plnkr to reproduce his issue.

**Comment by pkozlowski-opensource** [comment] 2016-02-23 13:13
@thelgevold @Sabartius thank you for chiming in and helping out with the issues, very much appreciated! 

@CodeJason unfortunately there is not enough detail in your bug report that would allow us to reproduce the issue you are having and we can't fix what we can't reproduce. Please go over [issue submitting guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to see what kind of info we require to be able to help out effectively. Most importantly we need a live reproduce scenario using a tool like plunker or similar. You can modify this plunk to reproduce your issue: http://plnkr.co/edit/MJeXoPerqXCr0eIv2ptI?p=preview

I'm going to close this one as it is not actionable as-is. Happy to re-open when you've got a reproduce scenario, though.

**Closed by pkozlowski-opensource** 2016-02-23 13:13 UTC

**Comment by CodeJason** [comment] 2016-02-23 23:07
Sorry for the late reply, here is what I mean: http://plnkr.co/edit/37uQY2

**Comment by thelgevold** [comment] 2016-02-24 03:59
I have made a tweak to your code here:

```
import {Component} from 'angular2/core'

@Component({
  selector: 'my-app',
  providers: [],
  template: `
    <div>
      <h2>Hello {{name}}</h2>
      <div [ngClass]="styles">This should change class and color</div>
    </div>
  `,
  styles:[`
    .red{
      color:red; 
    }
    .blue{
      color:blue;
    }
  `]
  directives: []
})
export class App {
  styles;
  constructor() {
    this.name = 'Angular2'
    this.styles= this.getMyClasses();
  }
  
  getMyClasses(){
    let toReturn = {
      red:true,
      blue:false
    };
    return toReturn;
  }
}
```

**Comment by CodeJason** [comment] 2016-02-24 10:09
Thanks. Although it doesn't look like it, I'll see if I can somehow change the returned value during run-time to alter the classes. One plunkr is back up and running that is. 
Could the documentation be changed to accommodate this method or can the issue be fixed? Like I stated at the start, I followed the documentation precisely (template syntax section).

**Comment by CodeJason** [comment] 2016-02-24 21:10
Updated the plunkr - http://plnkr.co/edit/37uQY2?p=preview
I was able to keep the function binding, given that I didn't return a new object. There's two ways of changing the classes there that work.
