### ISSUE TITLE
ERROR in Expected array when reading property declarations

### ISSUE THREAD

**Issue by soyjuanmedina** [angular/angular#30798] opened 2019-06-01 10:15 UTC
# 🐞 bug report

### Affected Package
Maybe the issue is caused by package @angular/cli because it's happens when I update Angular from 6.1 to 8

### Is this a regression?

Yes, the previous version in which this bug was not present was: 6.1

### Description

After update when npm start I get this error:

> ERROR in Expected array when reading property declarations

## 🔬 Minimal Reproduction

I'dont know how to do it.... It's possible its something mine, but I review all my declarations arrays and don't see anything extrange:

In app.module
```
  declarations: [
    AppComponent,
    NavbarComponent,
    LangSelectorComponent,
    FooterComponent,
    BookappointmentsComponent,
    RegisterComponent,
    ConfirmmailComponent,
    SecondopinionComponent,
    FaqComponent,
    SelectComponent
  ],
```

In components.module
```
  declarations: [
    LoadingComponent
  ],
```

In admin.module
```
  declarations: [
    UserManagementComponent
  ],
```

```
and in user.module
  declarations: [
    AccountinfoComponent,
    MyappointmentsComponent,
    MydocumentsComponent,
    MydependentsComponent,
    VideocallComponent
  ],
```

## 🔥 Exception or Error
<pre><code>
ERROR in Expected array when reading property declarations
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
i ｢wdm｣: Failed to compile.

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.1
@angular-devkit/build-angular     0.800.1
@angular-devkit/build-optimizer   0.800.1
@angular-devkit/build-webpack     0.800.1
@angular-devkit/core              8.0.1
@angular-devkit/schematics        8.0.1
@angular/cli                      8.0.1
@angular/fire                     5.2.0
@angular/http                     7.2.15
@angular/pwa                      0.800.1
@ngtools/webpack                  8.0.1
@schematics/angular               8.0.1
@schematics/update                0.800.1
rxjs                              6.5.2
typescript                        3.5.1
webpack                           4.32.2
</code></pre>

**Anything else relevant?**

**Comment by Airblader** [comment] 2019-06-01 10:45
1. The CLI has its own repository at @angular/cli
2. It is not recommended to skip major versions during upgrade, so perhaps try to do 6—7 first and then 7—8. It would also pijnidoen which upgrade causes the issue.
3. Please provide a full project reproducing the problem.

**Comment by soyjuanmedina** [comment] 2019-06-02 15:56
Thaks a lot @Airblader 
1. Sorry, I don't know where is better to post it. If you say me it's better in cli I move there.
2. You are right. I downgrade to versión 6 and then upgrade to 7 (with some problems I can solve), and now, I'm traying to upgrade from 7 to 8 and get an error I can solve and don't find anythig:
`ERROR in Cannot combine @Input decorators with query decorators`
3. I upload the proyect in gitlab:
[https://github.com/soyjuanmedina/patient-portal-cms-in-gitlab](url)

Thanks and hope you can help me

**Comment by Airblader** [comment] 2019-06-03 06:29
I think this is likely the same as the PR https://github.com/angular/angular/pull/30796

**Comment by soyjuanmedina** [comment] 2019-06-03 07:12
Ok, thanks a lot.

Then it's a well knowing issue and I have to wait to a solution isn't it?

**Comment by Airblader** [comment] 2019-06-03 07:40
I haven't looked at your project, but from what I can tell it's an issue in your code. With the PR you'd only get a better error message of where exactly the error is.

I would maybe locally patch your Angular with what the PR does (or just set breakpoints) to find the place in your code.

**Comment by Eddygn** [comment] 2019-06-03 08:41
In some projects the error appears when compiling with production flag and ivy enabled. There isn't an issue with Ivy disabled. Ivy should be backward compatible, so such issue should not occur. 

Perhaps not related, but seems somewhat similar to the _spread issue:
https://github.com/angular/angular/issues/30299
https://github.com/angular/angular/pull/30492

**Comment by Airblader** [comment] 2019-06-03 08:46
AFAIK Ivy is backwards-compatible for functionality, but it does introduce better checking against things that are broken. The `declarations` property should always have been an array, so if you have something other than an array there it was never intended to work.

Just my understanding, though; I'm not from the Angular team. :-)

**Comment by adrogon** [comment] 2019-06-03 10:31
The issue is not in your code, `@angular/fire` currently fails with Ivy enabled, e.g. https://github.com/angular/angularfire2/issues/2021

https://github.com/angular/angular/pull/30492 might fix the issue. You can try it by getting the latest master `"@angular/compiler-cli": "https://github.com/angular/compiler-cli-builds"`, or from the `8.1.x` branch.

**Comment by soyjuanmedina** [comment] 2019-06-03 16:48
Thanks a lot to all of you.
I can solve it changing the in tsconfig.json
```
  "angularCompilerOptions": {
    "enableIvy": true
  },
```
to 
```
  "angularCompilerOptions": {
    "enableIvy": false
  },
```
When it's in true trhows this error:

`ERROR in Cannot combine @Input decorators with query decorators`

when it's in false compiler ok, but I really don't know if this flag it's necesarry and what do :-(

**Comment by adrogon** [comment] 2019-06-03 16:54
@soyjuanmedina Ivy is the rendering engine that will be Angular's default in the future (version 9).
For now, it's not stable enough for production, and is available only to be tested.
Please read https://next.angular.io/guide/ivy for more information.

**Comment by soyjuanmedina** [comment] 2019-06-03 16:56
Ok @adrogon, then it's no problem have it in false for the moment, isn't it?

**Comment by adrogon** [comment] 2019-06-03 17:10
It **should** be set to `false` for the moment, until Ivy is backwards-compatible and stable.
You may simply remove it from the configuration file, `false` being the default value.

**Comment by trotyl** [comment] 2019-06-04 02:55
@soyjuanmedina Please take a look at https://angular.io/guide/deprecations#contentchild--input-used-together, it's a deprecated pattern and won't be allowed in the future, you should fix it anyway.

**Comment by soyjuanmedina** [comment] 2019-06-04 06:43
Thanks @trotyl , but I don't have this pattern.
I only use @Input() in one component and this is the declaration

```
export class SelectComponent implements OnInit {
  @Input() label: string;
  @Input() items: Array<any>;
  @Output() public actionToDoOnChange = new EventEmitter<string>();
```
As you can see I don't use @ContentChild and definitly not in one line :-(

@adrogon, do you think I should warn of this issue in some other forum. Really I want to help to this project (even if I could collaborate with small code modifications :-)

**Comment by trotyl** [comment] 2019-06-04 06:49
> Thanks @trotyl , but I don't have this pattern.

@soyjuanmedina The error message you posted above `ERROR in Cannot combine `@Input` decorators with query decorators` is for to the deprecation, are you sure none of your 3rd-party library is doing that?

**Comment by soyjuanmedina** [comment] 2019-06-04 13:43
Oh.... crisis!!!!
Finally I updated my project and all works ok..... npm start works and npm build too.... but when I upload it to my server have this error:

```
Uncaught TypeError: Cannot read property 'WebSocket' of undefined
    at Object.<anonymous> (main-es2015.fcbef38e0b64f6988647.js:1)
```
Help please!!!!

**Comment by Airblader** [comment] 2019-06-04 13:50
@soyjuanmedina GitHub is for bug reports and features. For support questions please head over to StackOverflow.

**Comment by soyjuanmedina** [comment] 2019-06-04 14:00
Ok, sorry... I ask in StackOverflow, but because it's happens when I update I supousse is an Issue.

**Comment by soyjuanmedina** [comment] 2019-06-04 17:05
> > Thanks @trotyl , but I don't have this pattern.
> 
> @soyjuanmedina The error message you posted above `ERROR in Cannot combine @Input decorators with query decorators` is for that deprecation, are you sure none of your 3rd-party library is doing that?

You are right, @trotyl , I found this pattern in @ng-bootstrap/ng-bootstrap and when update to version 4.2.1 I fix it and only have the error:

`ERROR in Failed to list lazy routes: Unknown module 'C:/Desarrollos/Udemy/patient-portal-cms/src/app/app.module#AppModule'.'.`

That I solve with the 

```
  "angularCompilerOptions": {
    "enableIvy": false
  },
```
Now I'm fightin whit this 

```
Uncaught TypeError: Cannot read property 'WebSocket' of undefined
    at Object.<anonymous> (main-es2015.fcbef38e0b64f6988647.js:1)
```

**Comment by soyjuanmedina** [comment] 2019-06-04 17:36
I finally solve the 'websocket' issue...I don't know but I suspect was some angular update,

I solve it changing compilerOptions in tsconfig.json from 'es2015' to 'es5'

Thanks and sorry if not your fault.

**Comment by pkozlowski-opensource** [comment] 2019-07-01 15:13
Sounds like this one was resolved on the user's end, closing.

**Closed by pkozlowski-opensource** 2019-07-01 15:13 UTC
Labels: comp: core, severity5: regression
