### ISSUE TITLE
RouterLinkActive { exact: true } doesn't work with redirected routes

### ISSUE THREAD

**Issue by jmcooper** [angular/angular#45933] opened 2022-05-09 17:13 UTC
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

No

### Description

I have found an interesting behavior in the way `routerLinkActive` when using routes with route params. The behavior only occurs when using a redirect route.

Consider an application with these two routes:

```typescript
  { path: 'page2/:id', component: Page2Component },
  { path: 'page2', redirectTo: '/page2/', pathMatch: 'full' },
```

And, in the same app, a page with these links with `routerLinkActive`:

```html
      <a 
        routerLink="/page2" 
        routerLinkActive="active"
        [routerLinkActiveOptions]="{exact: true}">Page 2</a>

      <a routerLink="/page2/foo" routerLinkActive="active">Page 2 / Foo</a>
```

I would expect the first link (/page2) to be have the `active` class only when the url is `/active` and not when the url is `/active/foo`. However, when I have the `redirect` route shown above, the first link never gets the `active` class applied to it. This is true regardless of whether I add a trailing slash to the routerLink or not (i.e. `routerLink="/page2/foo/"`).

It does work as expected if, instead of the redirect route, I just have a second route as follows:

```typescript
  { path: 'page2/:id', component: Page2Component },
  { path: 'page2', component: Page2Component },
```

However, it seems to be a better practice to use the redirect route, because then the component does not get re-loaded when navigating to itself from itself (i.e. navigating from `/page2/foo` to `/page2/bar`). So I'd prefer the redirect route, but I can't see how to get the `[routerLinkActiveOptions]="{exact: true}"` working when using a redirect route.

Here are examples in stackblitz:

Broken example with redirect route: https://stackblitz.com/edit/angular-ivy-ii1882?file=src/app/app.module.ts

Working example with non-redirect route: https://stackblitz.com/edit/angular-ivy-rh1tj1?file=src/app/app.module.ts

Is this a bug, or is there a solution I'm not seeing that would allow me to have both a redirect route and a working `routerLinkActiveOptions`?

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-ii1882?file=src/app/app.module.ts

### Please provide the exception or error you saw

```true
No, exception. Of course, without the redirect route, I do get an `Error: Cannot match any routes. URL Segment: 'catalog'` exception if I try to navigate to just `/catalog` or `/catalog/`.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.3.4
Node: 16.14.2
Package Manager: npm 8.5.0
OS: win32 x64

Angular: 13.3.5
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1303.4
@angular-devkit/build-angular   13.3.4
@angular-devkit/core            13.3.4
@angular-devkit/schematics      13.3.4
@angular/cli                    13.3.4
@schematics/angular             13.3.4
rxjs                            7.5.5
typescript                      4.6.4
```

### Anything else?
I created a corresponding StackOverflow question with the same description as above. It is here: https://stackoverflow.com/questions/72156917/angular-routerlinkactive-with-redirected-routes

**Comment by atscott** [comment] 2022-05-09 19:51
`RouterLinkActive` does not expand redirects to determine the final path. Generally, this is working as designed. Doing so would be require a step beyond the directive's current capabilities and require running the path matching algorithm rather than just converting the path to a `UrlTree`. Expansion of the redirect is also not known statically because it may require lazy loading of modules under some child segment in that path. 

Further, this is an easy fix in your application. If you know you have a static redirect, why not update the `routerLink` to go to the final destination in the first place? The `redirectTo` is meant to ensure any bookmarked pages that no longer exist don't result in a dead link. In this example, your `routerLink` should be written as `[routerLink]="['page2', '']"`.

Marking this as a feature request rather than a bug.

**Comment by jmcooper** [comment] 2022-05-09 21:58
Ahh, passing the empty parameter (`[routerLink]="['page2', '']" `) was the piece I was missing. I had tried `routerLink="page2"` and `routerLink="page2/"` to no avail. I'm curious if there's a reason why the following can't be made to be functionally equivalent:

- `routerLink="page2"`
- `[routerLink]="['page2', '']"`

If Angular knows there is a route defined with `page2:id`, why can't `routerLink="page2"` resolve with an empty (or undefined) parameter? I guess assuming the application wants an empty string is to presumptive, but it seems that null or undefined would make sense. I realize this is transforming into a feature request, but thought I'd ask to understand any reasoning that's already been considered before I make the request.

**Comment by jmcooper** [comment] 2022-05-09 22:24
Actually, the solution you provided (passing an empty parameter), has another side effect. I've implemented the change [in this Stackblitz](https://stackblitz.com/edit/angular-ivy-siqxgq?file=src%2Fapp%2Fheader%2Fheader.component.ts), but notice that even though I don't have `{exact: true}` on the ` [routerLink]="['page2', '']"` link, it does not highlight apply the active class when I'm on the route `page2/foo`. I would expect it to have the active class since exact is not set to true.

**Comment by atscott** [comment] 2022-05-09 22:58
> If Angular knows there is a route defined with page2:id, why can't routerLink="page2" resolve with an empty (or undefined) parameter

As you know from your route config "page2" and "page2:id" are _different routes_. There is an additional segment present in the latter. We cannot make the assumption that "page2" is the same as "page2:id" where `id` is empty string.

> `routerLink="page2/"` to no avail

Arguably, this could/should be considered a bug, albeit low priority and definitely a breaking change.

> but notice that even though I don't have {exact: true} on the [routerLink]="['page2', '']" link, it does not highlight apply the active class when I'm on the route page2/foo. I would expect it to have the active class since exact is not set to true.

This is working correctly, actually. It's the same as if your `routerLink` was `routerLink="page2/bar"`. This should not be listed as active when the URL is `page2/foo`. For `page2/`, the `id` is `''`, so `foo` should not match.

**Comment by atscott** [comment] 2022-05-09 23:04
I'm actually going to close this as working as intended. Routes which have redirects by definition cannot be active. It would certainly be bizarre behavior for `{path: 'apple', redirectTo: 'banana'}` to be marked active when the URL is `/banana`.

**Closed by atscott** 2022-05-09 23:04 UTC
Labels: feature, comp: router
