### ISSUE TITLE
ERROR in Error encountered resolving symbol values statically WITH functions exported.

### ISSUE THREAD

**Issue by laPlacek** [angular/angular#13892] opened 2017-01-12 13:05 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Consider following module:
```
export function angularHttpFactory(backend: XHRBackend, defaultOptions: RequestOptions): Http {
  return new Http(backend, defaultOptions);
}

export function authHttpFactory(auth: Auth, backend: XHRBackend, defaultOptions: RequestOptions): AuthHttp {
  return new AuthHttp(auth, backend, defaultOptions);
}

@NgModule({
  declarations: [LoginLoaderComponent],
  imports: [CommonModule, HttpModule, Ng2Webstorage],
  exports: [LoginLoaderComponent]
})
export class AuthModule {
  static forRoot(authConfig: AuthConfig): ModuleWithProviders {
    return {
      ngModule: AuthModule,
      providers: [
        { provide: AUTH_CONFIG, useValue: authConfig },
        { provide: ANGULAR_HTTP, useFactory: angularHttpFactory, deps: [XHRBackend, RequestOptions] },
        Auth,
        { provide: Http, useFactory: authHttpFactory , deps: [Auth, XHRBackend, RequestOptions] },
        AuthUser
      ]
    };
  }

  static forChild(): ModuleWithProviders {
    return {
      ngModule: AuthModule
    };
  }
}
```

Following error occurs when importing npm package with above module definition:
ERROR in Error encountered resolving symbol values statically. Calling function 'AuthModule', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule in C:/Users/jacek_dauth3h/Documents/dev/action-center-web-app/src/app/app.module.ts, resolving symbol AppModule in C:/Users/jacek_dauth3h/Documents/dev/action-center-web-app/src/app/app.module.ts

**Expected behavior**
No error.

* **Angular version:** 2.4.3
* **Angular CLI version:** 1.0.0-beta.24

* **Browser:** all
 
* **Language:** TypeScript 2.1.4

* **Node (for AoT issues):** `node --version` =  v6.9.4

**Comment by DzmitryShylovich** [comment] 2017-01-12 13:07
Pls format your code.

**Comment by DzmitryShylovich** [comment] 2017-01-12 13:14
```
static forRoot(authConfig: AuthConfig): ModuleWithProviders {
    return {
      ngModule: AuthModule,
      providers: [
          { provide: AUTH_CONFIG,  useValue: authConfig },
         { provide: Http, useFactory: authHttpFactory , deps: [Auth, XHRBackend, RequestOptions] },
         ...
       ]
    };
  }
```

**Comment by laPlacek** [comment] 2017-01-12 13:18
Ok, but why? What difference does it make, if both examples apre perfectly fine in terms of language contract?

**Comment by DzmitryShylovich** [comment] 2017-01-12 13:22
Aot mode has some limitations https://gist.github.com/chuckjaz/65dcc2fd5f4f5463e492ed0cb93bca60
We don't run any code during AOT. We only use values we can be statically determine from the annotations, this is why you can't call function inside annotations.

**Comment by laPlacek** [comment] 2017-01-12 13:27
Sure. Pleae note though, that all functions called inside static method _are_ in fact exported functions.
Also, following example also produces an error:
```
export function angularHttpFactory(backend: XHRBackend, defaultOptions: RequestOptions): Http {
  return new Http(backend, defaultOptions);
}

export function authHttpFactory(auth: Auth, backend: XHRBackend, defaultOptions: RequestOptions): AuthHttp {
  return new AuthHttp(auth, backend, defaultOptions);
}

@NgModule({
  declarations: [LoginLoaderComponent],
  imports: [CommonModule, HttpModule, Ng2Webstorage],
  exports: [LoginLoaderComponent]
})
export class AuthModule {
  static forRoot(authConfig: AuthConfig): ModuleWithProviders {
    return {
      ngModule: AuthModule,
      providers: [
        { provide: AUTH_CONFIG, useValue: authConfig },
        { provide: ANGULAR_HTTP, useFactory: angularHttpFactory },
        Auth,
        { provide: Http, useFactory: authHttpFactory , deps: [Auth, XHRBackend, RequestOptions] },
        AuthUser
      ]
    };
  }

  static forChild(): ModuleWithProviders {
    return {
      ngModule: AuthModule
    };
  }
}
```

> ERROR in Error encountered resolving symbol values statically. Calling function 'AuthModule', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule in C:/Users/jacek_dauth3h/Documents/dev/action-center-web-app/src/app/app.module.ts, resolving symbol AppModule in C:/Users/jacek_dauth3h/Documents/dev/action-center-web-app/src/app/app.module.ts

**Comment by DzmitryShylovich** [comment] 2017-01-12 13:37
> 2.4.0

pls update to the latest angular

**Comment by laPlacek** [comment] 2017-01-12 13:52
Done,
angular-cli: 1.0.0-beta.24
node: 6.9.4
os: win32 x64
@angular/common: 2.4.3
@angular/compiler: 2.4.3
@angular/core: 2.4.3
@angular/forms: 2.4.3
@angular/http: 2.4.3
@angular/platform-browser: 2.4.3
@angular/platform-browser-dynamic: 2.4.3
@angular/platform-server: 2.4.3
@angular/router: 3.4.3
@angular/compiler-cli: 2.4.3


Problem still exsits.

**Comment by serhiisol** [comment] 2017-01-12 21:29
Confirm, same problem, https://github.com/angular/angular-cli/issues/3674#issuecomment-272287641

**Comment by DzmitryShylovich** [comment] 2017-01-12 21:31
@serhiisol it's not a bug. [this](https://github.com/serhiisol/ng2-webpack/blob/master/src/app/app.module.ts#L24) is not supported. See https://github.com/rangle/angular-2-aot-sandbox#current-status

**Comment by DzmitryShylovich** [comment] 2017-01-12 21:32
@laPlacek pls add a small repository with reproduction without cli

**Comment by serhiisol** [comment] 2017-01-12 21:34
@DzmitryShylovich I'm not running compiler with aot, that's without aot

**Comment by DzmitryShylovich** [comment] 2017-01-12 21:35
that error is aot only

**Comment by serhiisol** [comment] 2017-01-12 21:36
than ngc or @ngtools/webpack don't work as expected

**Comment by DzmitryShylovich** [comment] 2017-01-12 21:37
everything works as expected :)

**Comment by serhiisol** [comment] 2017-01-12 21:38
ha ha, right, running commands without aot and producing bugs, of course

**Comment by DzmitryShylovich** [comment] 2017-01-12 22:53
then it's a cli issue

**Comment by serhiisol** [comment] 2017-01-13 11:20
It's not cli issue but ngc issue. Ngc analyzes code for both cases, aot and without aot. I thought AOT is optional, but it seems to be not.

**Comment by DzmitryShylovich** [comment] 2017-01-13 11:24
> Ngc analyzes code for both cases, aot and without aot

it doesn't make any sense :) Pls read what is aot and ngc.

**Comment by serhiisol** [comment] 2017-01-13 11:27
```
▶ ./node_modules/.bin/ngc -p ./src/tsconfig.json
Error: Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (position 24:19 in the original .ts file), resolving symbol AppModule
```

dude

**Comment by DzmitryShylovich** [comment] 2017-01-13 11:29
There're 2 compilation mods: aot and jit. ngc is used only in aot.
> ngc without aot

doesn't make any sense

**Comment by serhiisol** [comment] 2017-01-13 11:31
ng-xi18n uses ngc just for strings extraction, which also doesn't make sense

**Comment by laPlacek** [comment] 2017-01-13 20:06
@DzmitryShylovich i cannot make the repo public, since the imported package is a property of my employer. saying that, we can establish some remote screen session, would that make sense?

Obviously the issue also occurres when using AoT without CLI (i guess you knew that - but just to confirm ;)).



The full error produced by `.\node_modules\.bin\ngc -p .\src\tsconfig.json` is following:

> Error: Error encountered resolving symbol values statically. Calling function 'AuthModule', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule in C:/Users/jacek_dauth3h/Documents/dev/action-center-web-app/src/app/app.module.ts, resolving symbol AppModule in C:/Users/jacek_dauth3h/Documents/dev/action-center-web-app/src/app/app.module.ts
    at simplifyInContext (C:\Users\jacek_dauth3h\Documents\dev\action-center-web-app\node_modules\@angular\compiler\bundles\compiler.umd.js:25709:25)
    at StaticReflector.simplify (C:\Users\jacek_dauth3h\Documents\dev\action-center-web-app\node_modules\@angular\compiler\bundles\compiler.umd.js:25721:15)
    at StaticReflector.annotations (C:\Users\jacek_dauth3h\Documents\dev\action-center-web-app\node_modules\@angular\compiler\bundles\compiler.umd.js:25218:62)
    at NgModuleResolver.resolve (C:\Users\jacek_dauth3h\Documents\dev\action-center-web-app\node_modules\@angular\compiler\bundles\compiler.umd.js:17564:84)
    at CompileMetadataResolver.getNgModuleMetadata (C:\Users\jacek_dauth3h\Documents\dev\action-center-web-app\node_modules\@angular\compiler\bundles\compiler.umd.js:18072:62)
    at addNgModule (C:\Users\jacek_dauth3h\Documents\dev\action-center-web-app\node_modules\@angular\compiler\bundles\compiler.umd.js:24980:60)
    at C:\Users\jacek_dauth3h\Documents\dev\action-center-web-app\node_modules\@angular\compiler\bundles\compiler.umd.js:24991:16
    at Array.forEach (native)
    at _createNgModules (C:\Users\jacek_dauth3h\Documents\dev\action-center-web-app\node_modules\@angular\compiler\bundles\compiler.umd.js:24990:28)
    at analyzeNgModules (C:\Users\jacek_dauth3h\Documents\dev\action-center-web-app\node_modules\@angular\compiler\bundles\compiler.umd.js:24865:16)
Compilation failed


Please note that **AuthModule** that is presented in the issue is in fact npm package, and it is imported as such to the application that produces the error. Do those packages have any other restrictions than not using anonymous functions inside Module's definitions? Should they also be compiled by ngc instead of tsc? Should they be prepared in any other way to work with AoT? Thanks.

**Comment by DzmitryShylovich** [comment] 2017-01-13 20:25
@laPlacek 
> i cannot make the repo public, since the imported package is a property of my employer

we don't need your real code. Just create a mock module with the same shape.

**Comment by mhevery** [comment] 2017-01-13 22:14
- `ngc` is for AoT only. What you are trying to do is not supported in AoT as described in the limitations [here](https://gist.github.com/chuckjaz/65dcc2fd5f4f5463e492ed0cb93bca60). 
- The fact that you are getting this error, means you are running `ngc` which means that you are doing AoT. (Maybe you are not intending, but that is what is happening)
- If you are trying to do JiT mode, then don't use `ngc` but use `tsc`

Closing for now. Reopen with reopen case

**Closed by mhevery** 2017-01-13 22:14 UTC

**Comment by serhiisol** [comment] 2017-01-13 22:18
@mhevery angular-cli and ng-xi18n perform static analysis and produce errors. with cli even if you won't enable aot (so afaiu triggers ngc) and ng-xi18n as well. I thought it's optional process, but it seems like angular itself requires it by default. It would be nice to have option not to use it at all. e.g. for ng-xi18n just extract strings from html without super-per compilation...

**Comment by mhevery** [comment] 2017-01-13 22:36
@hansl Is this true?

**Comment by serhiisol** [comment] 2017-01-13 22:39
@mhevery that's easy to reproduce: new project and add incorrect arrow function for provider useFactory function, run ```ng serve``` without aot flag and voila, save will happen for ```ng-xi18n```

**Comment by hansl** [comment] 2017-01-13 22:52
Yes, this is true. Let's chat offline.

**Comment by serhiisol** [comment] 2017-01-13 22:54
@mhevery @hansl Thank you guys!

**Comment by laPlacek** [comment] 2017-01-14 00:37
@mhevery Sorry, but I completly don't understand. I use AoT because I want to use it! 
I'm importing npm package which is a regular angular module that has .forRoot anf .forChild methods with **neither anonymous functions nor lambas**. For some reason AoT compiler still sees there some function calls pr lambdash! 

>  Calling function 'AuthModule', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule...

But neither lambdas nor anonymous functions are called in ANY referenced modules. Taking above under consideration, why have you closed the issue?!

**Comment by DzmitryShylovich** [comment] 2017-01-14 00:46
@laPlacek I want a link to a github repo with the demo which I can run and see the error.

**Comment by laPlacek** [comment] 2017-01-14 00:50
@DzmitryShylovich you'll get it as soon as the issue is reopened or it is explain, why it's closed. Closing issues that are neither solved nor clarified is sweeping it under the rug. If that's how Angular comunity solves the problems, I'd rather stay passive here.

**Comment by laPlacek** [comment] 2017-01-14 21:50
Moved to opened issue, since it's obviously not closed. 
@DzmitryShylovich You'll find the repo there
https://github.com/angular/angular/issues/13931
