### ISSUE TITLE
[Bug] Binding a variable to inputs type property results in the model getting converted to string

### ISSUE THREAD

**Issue by CurtisDS** [angular/angular#26456] opened 2018-10-15 18:37 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

When you bind `type` to a variable and set that variable to `'number'` the model will be converted to a string when the user edits the input value.

## Expected behavior

When the input `type` is set to `'number'` it should not convert the model data to a string

## Minimal reproduction of the problem with instructions

create an input tag and bind type to a variable. Set that variable to `'number'`:

`typeVariable='number';`

`<input [type]="typeVariable" [formControl]="control">`

https://stackblitz.com/edit/angular-input-binding-type-bug?file=app%2Fform-field-number-example.html

initial state:
![image](https://user-images.githubusercontent.com/20732674/46970556-719bd300-d087-11e8-863a-7cd403628b9d.png)

after editing:
![image](https://user-images.githubusercontent.com/20732674/46970582-84aea300-d087-11e8-8421-01e4cdc20010.png)

## What is the motivation / use case for changing the behavior?

I would like to set the input type to a variable and have it determined dynamically without it converting everything to a string.

## Environment

<pre><code>
Angular version: 6.1.10

Browser:
- [x] Chrome (desktop) version 69.0.3497.100
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by trotyl** [comment] 2018-10-16 01:40
Duplicate of https://github.com/angular/angular/issues/13243

**Closed** 2018-10-16 11:40 UTC
