### ISSUE TITLE
Custom form control (ControlValueAccesor) doesn't make parent run change detection

### ISSUE THREAD

**Issue by christianlundberg** [angular/angular#30494] opened 2019-05-15 22:12 UTC
# 🐞 bug report

### Affected Package
angular/forms

### Description
I've created a custom file dropzone which should work correctly with ReactiveFormsModule. The problem is that after I've added a file, the control's parent (the form component) isn't being updated. According to the valueChanges Observable, the value is being emitted correctly.
```
<form
    (ngSubmit)="onSubmit()"
    [formGroup]="form"
>
    {{ form.value.file }} <-- this isn't updated until I drop a second file, then it always shows the previous file
<div
        fileDropzone
        formControlName="file"
    ></div>
</form>
```
I've noticed that if I add a custom event on the control, everything works correctly, but I shouldn't have to do that.

```
<form
    (ngSubmit)="onSubmit()"
    [formGroup]="form"
>
    {{ form.value.file }} <-- This updates correctly when listening to any custom event on the control
<div
        fileDropzone
        (changed)="onChange($event)"
        formControlName="file"
    ></div>
</form>
```
I assumed the problem might be OnPush change detection, but even after removing it, the problem persists.

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 7.3.8
Node: 8.10.0
OS: win32 x64
Angular: 7.2.13
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.13.8
@angular-devkit/build-angular      0.13.8
@angular-devkit/build-optimizer    0.13.8
@angular-devkit/build-webpack      0.13.8
@angular-devkit/core               7.3.8
@angular-devkit/schematics         7.3.8
@angular/cdk                       7.3.7
@angular/cli                       7.3.8
@angular/flex-layout               7.0.0-beta.24
@angular/material                  7.3.7
@angular/material-moment-adapter   7.3.7
@ngtools/webpack                   7.3.8
@schematics/angular                7.3.8
@schematics/update                 0.13.8
rxjs                               6.4.0
typescript                         3.2.2
webpack                            4.29.0
</code></pre>

**Comment by Airblader** [comment] 2019-05-16 04:22
Can you share a StackBlitz reproducing this problem?

**Comment by trotyl** [comment] 2019-05-16 05:12
> The problem is that after I've added a file, the control's parent (the form component) isn't being updated. According to the valueChanges Observable, the value is being emitted correctly.

Change detection is independent with RxJS events, but the native events that triggers the event loop in browser, it's most likely a problem with your `fileDropzone` directive implementation.

**Comment by clundberg1** [comment] 2019-05-16 17:30
@Airblader @trotyl 
Actually it apparently does have something to do with OnPush. Here's the StackBlitz: 
https://stackblitz.com/edit/angular-pcrona?file=src%2Fapp%2Fapp.component.ts

If you enable OnPush, then it's always behind on rendering the file's name until you actually hover the dropzone again.

Is this a bug with Angular or am I supposed to do something else with my custom form control?

**Comment by trotyl** [comment] 2019-05-17 04:49
@clundberg1 It's the expected behavior, the problem is that you're [changing the form value asynchronously](https://github.com/ngez/platform/blob/1cbfe2e44d8e66b9c2f0cc8119c43706e846d9b3/projects/core/src/file/file-dropzone.directive.ts#L113-L117):

```typescript
const files = await (items
  ? this.getFilesFromDataTransferItemList(items)
  : Promise.resolve(Array.from(dataTransfer.files)));

this.setValueAndUpdate(files, 'drop');
```

So that when the control/form value changes (in a different tick than DOM events), the component view is no longer pending for check.

You can just manually `markForCheck()` if you do want update the form in asynchronous callback.

**Comment by clundberg1** [comment] 2019-05-17 13:33
@trotyl 
Oh okay thanks! That worked. I have a question though. Is there something I can change in the custom directive so that it updates the form, so that I don't have to markForCheck() in every single form?

**Comment by trotyl** [comment] 2019-05-17 14:07
> Is there something I can change in the custom directive so that it updates the form

1. Wait for https://github.com/angular/angular/issues/27885 being implemented, which could link the promise callback to the directive who invokes it. But I don't think that would land as the current design path is not depends on Zone.js when possible.

2. Make a feature request that a form/control directive should always mark itself for check in `viewToModelUpdate`, but it also seems deviated with current design that all views needs to be explicit mark for check. In the future [even DOM events may not update its view to be dirty](https://github.com/angular/angular/pull/25969), but require explicit `markDirty(this)` in event handler. ([temporarily reverted](https://github.com/angular/angular/pull/28474) for compatibility)

**Comment by trotyl** [comment] 2019-07-10 02:14
Duplicate of https://github.com/angular/angular/issues/21780

**Closed** 2019-07-10 10:22 UTC
Labels: comp: forms
