### ISSUE TITLE
Safari really slow/unresponsive (change detection?)

### ISSUE THREAD

**Issue by ahitchen** [angular/angular#6350] opened 2016-01-08 16:42 UTC
Hello,

I'm sorry if this is too vague an issue to post.

I have an application that is working pretty well across chrome, firefox, edge, and ie11 (all on windows). I was testing it on safari (OSX) this morning, and I noticed it was noticeably slower than on any other browser. 

This an entirely unscientific test, but I put a bunch of console logs in the javascript to follow when the data is actually being loaded in the js. It seems like I have all the data long before it is being displayed. Is this a safari issue that angular 2 has nothing to do with?

I notice it is also happening with a canvas element that I create. Essentially, when sharing images, I paste the company logo on the image using a canvas. The javascript says it has loaded, but the logo doesn't appear until I toggle a button on the page.

**Comment by QuentinFchx** [comment] 2016-03-25 13:44
:+1: 
My app is "lagging" on Safari (especially when scrolling), but it's running fine on other browsers.

**Comment by zoechi** [comment] 2016-03-25 13:47
Is this only in `devMode` or also in `prodMode`?

**Comment by QuentinFchx** [comment] 2016-03-25 14:04
Both

**Comment by mhevery** [comment] 2016-03-28 18:58
Can we have a repro case in plunker?

**Comment by pkozlowski-opensource** [comment] 2016-08-05 17:00
Closing since we haven't seen any reproduce scenario.

**Closed by pkozlowski-opensource** 2016-08-05 17:00 UTC

**Comment by alberto-f** [comment] 2016-09-11 15:54
Unfortunately for me it's happening the same... Im trying to simplify as much as I can but it's really really laggy. I will try to reproduce it somehow...

**Comment by vicb** [comment] 2016-09-11 16:39
There is no way we can help without a repro.

Once you have a **minimal** repro demonstrating the defect, create a new issue. Thanks.

**Comment by fouadchamoun** [comment] 2017-07-21 10:29
I had the same problem with scroll performance on Safari and @QuentinFchx 's suggestion to use `transform: translate3d(0, 0, 0)` worked quite well. After looking at the performance timeline in Safari's dev tools, I noticed that this dramatically limits the amount of redraw operations when scrolling. I'm afraid I don't have much more knowledge of how redrawing events work in browsers... But yeah, adding `transform: translate3d(0, 0, 0)` to an 'entire-page' container div fixed this for me too :)

**Comment by pitAlex** [comment] 2017-12-23 00:55
I'm facing same issue and I can tell you how to reproduce. This is in the latest Mac OS with the latest Safari:
Just put some elements in a page that have hover effects like color changes. Then make an ngFor with at least 15 items with some content, not just text maybe one or 2 images as well. You will see how the hover effect lags in the page with devMode on. But if you put ChangeDetectionStrategy.OnPush it won't lag anymore. The problem is, the more stuff you have in the ngFor the more lag you will get.

**Comment by ignaciofuentes** [comment] 2018-12-19 02:51
Oh wow. @fouadchamoun's solution also worked for me.
