### ISSUE TITLE
JIT support missing even though specifically imported

### ISSUE THREAD

**Issue by gp187** [angular/angular#46495] opened 2022-06-24 20:19 UTC
### Which @angular/* package(s) are the source of the bug?

compiler, core, platform-browser

### Is this a regression?

No

### Description

When trying to create a dynamic component using the `createComponent` function of a `@ViewChild` I get the error `JIT compiler unavailable` event though I added the line `import '@angular/compiler` in the main.ts file

```typescript
  @ViewChild(`vc`, { read: ViewContainerRef }) _container!: ViewContainerRef;

  public buildComponent(): void {
    const MegaComponentClass = class MegaComponentClass {
      data = 13
    };
    const MegaComponent = Component({
      selector: 'xxx',
      template: `<div>D {{ data }}</div>,
      standalone: true,
      imports: [
        SharedCoreModule,
        SnowfoxCoreModule,
        NaoUtilsSharedModule,
      ]
    })(MegaComponentClass);
    this.cmpRef = this._container.createComponent(MegaComponent);
  }
```

Serving the app with ng serve > works
Building the app with `--configuration development` > works
Building the app with `--configuration production` > throws error

### Note
The error only appears if you have the following flags in the build configuration in angular.json

```
"buildOptimizer": true,
"optimization": true,
````

### Please provide the exception or error you saw

```true
ERROR Error: JIT compiler unavailable
    at Jo (main.350e21b112ecbef4.js:1:814934)
    at Function.get (main.350e21b112ecbef4.js:1:921480)
    at Bt (main.350e21b112ecbef4.js:1:801563)
    at Bv.resolveComponentFactory (main.350e21b112ecbef4.js:1:894122)
    at n.buildComponent11 (580.b9659a7fd062bb17.js:1:54672)
    at 580.b9659a7fd062bb17.js:1:57314
    at s_ (main.350e21b112ecbef4.js:1:863773)
    at x (main.350e21b112ecbef4.js:1:863912)
    at HTMLButtonElement.<anonymous> (main.350e21b112ecbef4.js:1:1060144)
    at v.invokeTask (polyfills.04b80b36a80dbd3d.js:1:7155)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular: 14.0.3
Npm: latest
```

### Anything else?

Using `createComponent` in a ViewChild is not a deprecated function, like the old method where you had to create a module and then inject the component from the factory

DEPRECATED METHOD
```typescript
    const mod = this.compiler.compileModuleAndAllComponentsSync(MegaModule);
      const factory = mod.componentFactories.find((comp) => {
        return comp.componentType === MegaComponentClass;
      });
      if (factory) {
        this.cmpRef = this._container.createComponent(factory);
        this.cmpRef.hostView.detectChanges();
      }
```

This also works in development but not production

**Comment by alan-agius4** [comment] 2022-06-26 08:15
Duplicate of #46196

**Closed by alan-agius4** 2022-06-26 08:15 UTC
