### ISSUE TITLE
ngcc: Unable to write a reference to NgSelectElementsComponent

### ISSUE THREAD

**Issue by kukjevov** [angular/angular#29783] opened 2019-04-09 12:15 UTC
# 🐞 bug report

### Affected Package
`@angular/compiler-cli`

### Is this a regression?

Dont know, probably not.

### Description

When i am trying to use `ngcc` compiler i get following error.
> Error: Unable to write a reference to NgSelectElementsComponent in D:/git/ivy-code-size/node_modules/@ng/select/src/elements/components/ngSelectElements.component.d.ts from D:/git/ivy-code-size/node_modules/@ng/select/src/elements/modules/ngSelectElements.module.d.ts

When i am trying to use `ngcc` with my libraries i will get mentioned error for *submodule*. Dont know what exactly could be problem, maybe that my component extends another component. Because rest of application compilation is working correctly. Maybe problem is that it is in subdirectory.

This might relate to https://github.com/angular/angular/issues/29361 i am not sure, this one is with `ngcc`. 

## 🔬 Minimal Reproduction

Problem is here https://github.com/kukjevov/ivy-code-size/tree/bug binaries for my @ng packages are versioned in git.

> git clone https://github.com/kukjevov/ivy-code-size
> cd ivy-code-size
> git checkout bug
> npm install
> git reset --hard
> npm run ngcc

## 🔥 Exception or Error
```
Error: Unable to write a reference to NgSelectElementsComponent in D:/git/ivy-code-size/node_modules/@ng/select/src/elements/components/ngSelectElements.component.d.ts from D:/git/ivy-code-size/node_modules/@ng/select/src/elements/modules/ngSelectElements.module.d.ts
    at ReferenceEmitter.emit (D:\git\ivy-code-size\node_modules\@angular\compiler-cli\src\ngtsc\imports\src\emitter.js:56:19)
    at Object.toR3Reference (D:\git\ivy-code-size\node_modules\@angular\compiler-cli\src\ngtsc\annotations\src\util.js:131:31)
    at NgModuleDecoratorHandler._toR3Reference (D:\git\ivy-code-size\node_modules\@angular\compiler-cli\src\ngtsc\annotations\src\ng_module.js:268:31)
    at D:\git\ivy-code-size\node_modules\@angular\compiler-cli\src\ngtsc\annotations\src\ng_module.js:123:83
    at Array.map (<anonymous>)
    at NgModuleDecoratorHandler.analyze (D:\git\ivy-code-size\node_modules\@angular\compiler-cli\src\ngtsc\annotations\src\ng_module.js:123:48)
    at DecorationAnalyzer.analyzeClass (D:\git\ivy-code-size\node_modules\@angular\compiler-cli\ngcc\src\analysis\decoration_analyzer.js:162:38)
    at D:\git\ivy-code-size\node_modules\@angular\compiler-cli\ngcc\src\analysis\decoration_analyzer.js:105:87
    at Array.map (<anonymous>)
    at DecorationAnalyzer.analyzeFile (D:\git\ivy-code-size\node_modules\@angular\compiler-cli\ngcc\src\analysis\decoration_analyzer.js:105:51)
```

## 🌍  Your Environment

**Angular Version:**
8.0.0-beta.11

**Anything else relevant?**
NPM: 6.9.0
NodeJS: 11.6.0
Windows 10.0.17763

**Comment by alexzuza** [comment] 2019-04-14 05:09
I ran through the repro and have found what is the root cause of the issue.

ngtsc compiler tries to resolve path to your declaration file through LogicalProjectStrategy and it's looking for typings in `@ng/select/elements` folder but you placed it in `@ng/select/src`.

https://github.com/angular/angular/blob/ea70d41ac2314cdfc58688b488f85108466e5f92/packages/compiler-cli/src/ngtsc/path/src/logical.ts#L83

```
...node_modules/@ng/select/src/elements/components/ngSelectElements.component.d.ts
...node_modules/@ng/select/elements"
```
You can also take a look at angular material builds artefacts https://github.com/angular/material2-builds It works there because they keep typings in dedicated secondary entry points.

**Comment by gkalpak** [comment] 2019-04-18 15:16
Thx for looking into it, @alexzuza. AFAICT, this is a duplicate of #29361 (see there for more details).

**Closed by gkalpak** 2019-04-18 15:16 UTC
Labels: comp: ivy

**Comment by kukjevov** [comment] 2019-06-01 18:36
Hmmm weird, i have changed typings path and it still does not work. I will prepare example to demonstrate.
