### ISSUE TITLE
Validator for `step` attribute of input[type="number|date|..."]

### ISSUE THREAD

**Issue by spike-rabbit** [angular/angular#43174] opened 2021-08-16 12:00 UTC
### Which @angular/* package(s) are relevant/releated to the feature request?

forms

### Description

HTML input[type="number|date|..."] elements have a [step attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/step) which is already causing browser validations on that input type.

This attribute needs to be modified for different number types:
- integer (step="1" which is the default)
- currency (step="0.01")
- floating points (step="any")
- ...

As this is a web-standard I would suggest that Angular can handle this in the same way like min/max/... .

### Proposed solution

1. add a new step validator to `Validators` -> `Validators.step(step: number | 'any'): ValidatorFn`
2. pick up the step attribute in TemplateDriven and ReactiveForms

### Alternatives considered

It is possible to write a custom validator like [this](https://stackoverflow.com/a/60485467).
The drawback is that the application / developer needs to sync the step attribute of the validator and the html-element on it's own.

**Comment by JoostK** [comment] 2021-08-16 13:49
Thanks for opening this feature request. I believe this is a duplicate of #42845, please follow that one.

**Closed by JoostK** 2021-08-16 13:49 UTC

**Comment by spike-rabbit** [comment] 2021-08-16 17:43
You are right. I didn't noticed that this already exists. I just checked for the `forms: validators` label.
