### ISSUE TITLE
Declare a variable of the ngModel, causes EXCEPTION

### ISSUE THREAD

**Issue by rajjejosefsson** [angular/angular#10016] opened 2016-07-12 22:17 UTC
**I'm submitting a ...** 
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Im new to Angular and following the docs, and I'm getting the following Exception message in the console:

> EXCEPTION: Error: Uncaught (in promise): Template parse errors: There is no directive with "exportAs" set to "ngModel"

(This happen when I'm declare a variable assigned to the directive of "ngModel".)

**Expected/desired behavior**
Everything works but the Exception message wont disappear. 

**Reproduction of the problem**
Attached Error-log can you find inside the text file at plunker:
http://plnkr.co/edit/qo7rpKv3hx8XsEpOmqnu?p=preview

* **Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** [Chrome 51.0.2704.106 ] 
 
* **Language:** [TypeScript 1.8.10]

**Comment by kara** [comment] 2016-07-12 22:30
@rajjejosefsson  There seems to be a problem with the plunker you linked. It's looking for a main.js file that doesn't exist, so the Angular code isn't running to show your issue.  Can you reproduce the issue on a fresh plunker? 

http://plnkr.co/edit/4cq1KVEGfvRqqRutclLD?p=preview

**Comment by rajjejosefsson** [comment] 2016-07-13 11:38
@kara Here you go: http://plnkr.co/edit/p6MuYMlInooUrh1YpCaa

**Comment by kara** [comment] 2016-07-13 15:42
Thanks @rajjejosefsson.  It looks like you haven't provided the new forms module.  It is turned off by default, so you need to add some lines to your bootstrap in main.ts:

```ts
import {disableDeprecatedForms, provideForms} from '@angular/forms';

bootstrap(AppComponent, [
  disableDeprecatedForms(),
  provideForms()
]);
```

You can see an updated plunker here: http://plnkr.co/edit/H1HZuVW7skBKFZt1wHaP?p=preview.

I'm closing this, as it doesn't seem to be a bug, but please feel free to re-open if I'm missing something or you encounter any additional issues.

**Closed by kara** 2016-07-13 15:42 UTC
Labels: comp: forms
