### ISSUE TITLE
Ivy ngcc script run exception on @angular/core compiling: TypeError: Cannot read property 'fileName' of null

### ISSUE THREAD

**Issue by iSerganov-andersen** [angular/angular#32086] opened 2019-08-09 20:01 UTC
The issue is suffered once Ivy ngcc scripts compiles @angular/core package:

Compiling @angular/core : es2015 as esm2015
TypeError: Cannot read property 'fileName' of null
    at Object.getImportRewriter (C:\Development\FiLogic-OpenTMS\angular\node_modules\@angular\compiler-cli\ngcc\src\rendering\utils.js:22:72)
    at DtsRenderer.renderDtsFile (C:\Development\FiLogic-OpenTMS\angular\node_modules\@angular\compiler-cli\ngcc\src\rendering\dts_renderer.js:75:72)
    at C:\Development\FiLogic-OpenTMS\angular\node_modules\@angular\compiler-cli\ngcc\src\rendering\dts_renderer.js:67:134
    at Map.forEach (<anonymous>)
    at DtsRenderer.renderProgram (C:\Development\FiLogic-OpenTMS\angular\node_modules\@angular\compiler-cli\ngcc\src\rendering\dts_renderer.js:67:26)
    at Transformer.transform (C:\Development\FiLogic-OpenTMS\angular\node_modules\@angular\compiler-cli\ngcc\src\packages\transformer.js:69:52)
    at Object.mainNgcc (C:\Development\FiLogic-OpenTMS\angular\node_modules\@angular\compiler-cli\ngcc\src\main.js:93:64)
    at C:\Development\FiLogic-OpenTMS\angular\node_modules\@angular\compiler-cli\ngcc\main-ngcc.js:68:20
    at C:\Development\FiLogic-OpenTMS\angular\node_modules\@angular\compiler-cli\ngcc\main-ngcc.js:4:17
    at Object.<anonymous> (C:\Development\FiLogic-OpenTMS\angular\node_modules\@angular\compiler-cli\ngcc\main-ngcc.js:10:3)

It points here:

`return new imports_1.R3SymbolsImportRewriter(r3SymbolsFile.fileName);`

Versions:
Angular CLI: 8.2.1
Node: 10.16.0
OS: win32 x64
Angular: 8.2.1
... animations, bazel, cli, common, compiler, compiler-cli, core
... forms, platform-browser, platform-browser-dynamic
... platform-server, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.802.1
@angular-devkit/build-angular      0.802.1
@angular-devkit/build-optimizer    0.802.1
@angular-devkit/build-webpack      0.802.1
@angular-devkit/core               8.2.1
@angular-devkit/schematics         8.2.1
@angular/cdk                       8.1.2
@angular/http                      8.0.0-beta.10
@angular/material                  8.1.2
@angular/material-moment-adapter   8.1.2
@ngtools/webpack                   8.2.1
@schematics/angular                8.2.1
@schematics/update                 0.802.1
rxjs                               6.3.3
typescript                         3.4.5
webpack                            4.38.0

    tsconfig compiler options:

  "compilerOptions": {
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": [ "es7", "dom" ],
    "mapRoot": "./",
    "module": "esnext",
    "skipLibCheck": true,
    "moduleResolution": "node",
    "outDir": "../dist/out-tsc",
    "sourceMap": true,
    "resolveJsonModule": true,
    "target": "es5",
    "typeRoots": [
      "../node_modules/@types"
    ]

**Comment by gkalpak** [comment] 2019-08-12 09:57
@iSerganov-andersen, is this with a vanilla `@angular/cli` project? If not, could you provide us with a minimal reproduction (e.g. GitHub project we can check out and investigate)?

**Comment by iSerganov-andersen** [comment] 2019-08-12 23:01
@gkalpak , sure! You may find the link to the project with the issue below:
https://github.com/iSerganov-andersen/Ivy-test
Please do not hesitate to contact me if you need any additional information. Thank you.

**Comment by gkalpak** [comment] 2019-08-14 21:18
The error happens, because `angular-io-slimscroll` has a direct dependency on `@angular/core@5.x`. I am surprized this even worked before Ivy. Angular libraries should _not_ bring in their own version of Angular (they should have `@angular/*` packages as `peerDependencies` instead).

The last commit on `angular-io-slimscroll` was more than 1.5 years ago, so the project is likely not maintained any more. There are also several open issues about compatibility with recent Angular versions: rd-dev-ukraine/angular-io-slimscroll#25, rd-dev-ukraine/angular-io-slimscroll#27, rd-dev-ukraine/angular-io-slimscroll#29

Since you don't seem to be using it, you can probably remove the package. 

##
Doing that, there seems to be an issue with `ngx-bootstrap/accordion`. The error is similar to the one reported in #31032 for `ngx-pipes`:

```
Value at position 1 in the NgModule.imports of AccordionModule is not a reference: [object Object]
```

The [version of `ngx-bootstrap`][1] in `package.json` seems rather old. Upgrading to the latest version (5.1.1) makes the error go away (at least with `@angular/*` at version `9.0.0-next.2`).

##
I am going to close this, since everything seems to work fine on the `ivy-ngcc` side.

BTW, for the time being, I suggest using the `@next` version of Angular when trying out Ivy, because that's where the latest fixes/improvements are in. 

[1]: https://github.com/iSerganov-andersen/Ivy-test/blob/f2f9eadc370ca7dd5e7a4b94d5d2206186127326/package.json#L109

**Closed by gkalpak** 2019-08-14 21:18 UTC
Labels: comp: ngcc

**Comment by iSerganov-andersen** [comment] 2019-08-15 20:54
@gkalpak , thanks a lot for your investigation!
