### ISSUE TITLE
Error in @ViewChild While migrating from angular 8 to 9

### ISSUE THREAD

**Issue by shinchan305** [angular/angular#34958] opened 2020-01-24 20:17 UTC
Hi there,

I am trying to migrate my Angular 8 project to Angular 9.

Everything went smoothly, but when I run the project, I am getting the below error:

**ERROR in @ViewChild options must be an object literal**
C:\Users\10637900\source\Workspaces\Atlas\PG.Atlas\PG.Atlas.Client\node_modules\@angular\compiler-cli\src\ngtsc\program.js:326
                    finally { if (e_2) throw e_2.error; }
                                       ^

Error: @ViewChild options must be an object literal
    at extractQueryMetadata (C:\Users\10637900\source\Workspaces\Atlas\PG.Atlas\PG.Atlas.Client\node_modules\@angular\compiler-cli\src\ngtsc\annotations\src\directive.js:281:23)
    at C:\Users\10637900\source\Workspaces\Atlas\PG.Atlas\PG.Atlas.Client\node_modules\@angular\compiler-cli\src\ngtsc\annotations\src\directive.js:431:20
    at Array.map (<anonymous>)
    at queriesFromFields (C:\Users\10637900\source\Workspaces\Atlas\PG.Atlas\PG.Atlas.Client\node_modules\@angular\compiler-cli\src\ngtsc\annotations\src\directive.js:417:23)
    at Object.extractDirectiveMetadata (C:\Users\10637900\source\Workspaces\Atlas\PG.Atlas\PG.Atlas.Client\node_modules\@angular\compiler-cli\src\ngtsc\annotations\src\directive.js:180:35)
    at ComponentDecoratorHandler.analyze (C:\Users\10637900\source\Workspaces\Atlas\PG.Atlas\PG.Atlas.Client\node_modules\@angular\compiler-cli\src\ngtsc\annotations\src\component.js:142:47)
    at TraitCompiler.analyzeTrait (C:\Users\10637900\source\Workspaces\Atlas\PG.Atlas\PG.Atlas.Client\node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:314:40)
    at analyze (C:\Users\10637900\source\Workspaces\Atlas\PG.Atlas\PG.Atlas.Client\node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:281:58)
    at _loop_1 (C:\Users\10637900\source\Workspaces\Atlas\PG.Atlas\PG.Atlas.Client\node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:290:21)
    at TraitCompiler.analyzeClass (C:\Users\10637900\source\Workspaces\Atlas\PG.Atlas\PG.Atlas.Client\node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:296:21)

I tried reinstalling the node modules, but still the same.

Anyone else facing the same issue?

**Comment by Barzille** [comment] 2020-01-28 16:12
Same for me and no hint, where to look at in my code ^^

**Comment by Barzille** [comment] 2020-01-28 16:26
I found a @ViewChild in my code, commented it out and the application started up fine.

**Comment by kara** [comment] 2020-01-30 23:43
@shinchan305 It sounds like you might have a `@ViewChild` somewhere that has a reference instead of an object literal, e.g.:

```
@ViewChild(Foo, myOptions) foo: any;
```

I think that error message could use some work, though. It's unclear that the problem is the reference, not the type.

**Comment by EyadIT94** [comment] 2020-02-23 05:43
I have the same issue, I don't have any code for @ViewChild, any help!!

**Comment by AndrewKushnir** [comment] 2020-02-23 20:28
@EyadIT94 the mentioned error message was improved in https://github.com/angular/angular/commit/646655d09a087b8246b62aeb188c60701354cb0a and these improvements will be available as a part of the 9.0.3 release. New error message should also contain a file name and location which triggers the issue.

You can wait a few days for 9.0.3 release to go out or test the behavior using artifacts from [this page](https://circleci.com/gh/angular/angular/631075#artifacts/containers/0) as described in [this document](https://github.com/angular/angular/blob/master/docs/DEVELOPER.md#archives-for-each-package). **Please note**: the mentioned artifacts are for **testing purposes only** and are not suitable for production usage (these artifacts will be removed at some point).

**Comment by ahmadalsadder** [comment] 2020-02-26 10:48
@AndrewKushnir any update on this i have the same issue ?! i add options for all viewChild i had but still the same ?

**Comment by AndrewKushnir** [comment] 2020-02-27 19:26
Hi @ahmadalsadder, the `9.0.3` version of Angular framework was released and available on NPM. Please try upgrading to the `9.0.3` version and build your app again - you should see more descriptive error message that contains the `@ViewChild` decorator location that is causing the problem. The problem might happen because the `options` argument is not statically resolvable as described in https://github.com/angular/angular/issues/34958#issuecomment-580514332.

I'm closing this ticket for now (since the error message is improved and additional investigation on the app side is required), feel free to file a new issue if the problem still exists.

Thank you.

**Closed by AndrewKushnir** 2020-02-27 19:26 UTC
Labels: comp: compiler, comp: ivy, severity1: confusing, state: Needs repro, type: bug/fix
