### ISSUE TITLE
Validators: required <select>  marked as ng-invalid for option value "0"

### ISSUE THREAD

**Issue by cghislai** [angular/angular#6527] opened 2016-01-16 12:04 UTC
I have a required select with enum values options :
```
 export enum Pricing {
  VALUE0,
  VALUE1,
  VALUE2
}


@Component({
  selector: 'home',
  template: `
    Welcome Home
    <form>
     <select id="pricing"
        [ngModel]="pricingModel"
        (change)="onPricingChanged($event)"
        ngControl="pricingControl" required>
        <option *ngFor="#pricing of allPricings"
                [value]="pricing">
            {{ getPricingLabel(pricing) }}
        </option>
    </select>
    {{ pricingModel }}
  `,
  styles: [`
  .ng-invalid { border: 2px solid red; }
  `]
  viewProviders: [FORM_DIRECTIVES]
})
export class Home {

  pricingModel: Pricing;
  
  allPricings: Pricing[] = [
    Pricing.VALUE0,
    Pricing.VALUE1,
    Pricing.VALUE2
    ];
    constructor() {
      this.pricingModel = Pricing.VALUE0;
    }
    
    onPricingChanged(event) {
      var value:string = event.target.value;
      var pricing:Pricing = <Pricing>parseInt(value);
      this.pricingModel = pricing;
    }
    
    getPricingLabel(pricing: Pricing) {
      return Pricing[pricing];
    }
}
```

Using this code, the control is marked as invalid when selecting the first value.
plunker: http://plnkr.co/edit/ABh8pzp1afXkINcunKR8?p=preview

**Comment by mhevery** [comment] 2016-01-20 20:24
The issue is that `0` is falsy which fails the `required` check.

**Comment by fredgate** [comment] 2016-02-12 23:01
That does not solve the issue when required valiator is applied to an input of type number, and the entered text is empty : the value is then NaN.
See : https://github.com/angular/angular/issues/6932

**Comment by danielfigueiredo** [comment] 2016-02-21 16:53
@fredgate I'm not sure how #6932 should be resolved
NumberValueAccessor tries to parseFloat an empty string resulting in NaN, which required validator also doesn't understand. Should required validator throw invalid when NaN is sent? I put a reference to a commit from my fork in the issue. 
It looks for me that the problem should be solved in numberValueAccessor, because they're the bridge between a DOM element and a Control. Thus it should know that if a user deletes the content and the value is empty string, the input is empty and not NaN.
I don't have much knowledge on this so I can be wrong :)

**Comment by awerlang** [comment] 2016-03-01 20:18
Either start you enum with 1 or do not call parseInt().

```
 export enum Pricing {
  VALUE0 = 1,
  VALUE1,
  VALUE2
}
```

**Comment by fredgate** [comment] 2016-03-01 21:54
No.
A ValueAccessor assures the mapping between the text in the input field (in the DOM) and the value of the angular control. NumberValueAccessor is a specific ValueAccessor ensuring that the control value will be a number. It is normal that is call parseInt. And it should support 0 which is a number like others.
NumberValueAccessor must always set the value of a control to a number and never to a string. NaN is a special number but it is a number. The exception could be for the empty string : may be that NumberValueAccessor should in this case produce a special value like null or undefined. This could solve all the issues with validators.
The discussion is open. See #6932

**Comment by ericmartinezr** [comment] 2016-03-10 00:31
This issue can be closed, the fix landed with beta.6

**Comment by DrewynV** [comment] 2016-04-05 00:32
__________________________________

Hi! We just wanted to let you know we receievd your email. Thank you for submitting your request. Our aim is to get back to you within 24 hours at the latest. If you have any additional information to add to your request, please reply to this email.


Also please visit our knowledgebase (http://www.support.magicdust.com.au) to browse for further info, we are adding to it all the time.

Or here is our industry report about the 11 Essentials for a Successful Website (http://www.magicdust.com.au/web-design/.

We look forward to helping you succeed online.

Thanks

The Team @ Magicdust Digital

http://support.magicdust.com.au/

Ph (02) 9979 7474
M-F | 9 am-5:00 pm AEST (AEDT in Summer) excluding Public Holidays

------------------------------------------------------------------------------------------------------------
This message was sent to  reply@reply.github.com in reference to Case #166600.
------------------------------------------------------------------------------------------------------------


[[44090321a4a567f786b63fc9844deea93ad0fd6e-673074599]]

**Comment by kara** [comment] 2016-04-18 22:27
Closing (fixed by https://github.com/angular/angular/pull/6617)

**Closed by kara** 2016-04-18 22:27 UTC
Labels: comp: core/forms, effort1: easy (hour), hotlist: community-help, P2: required, type: bug
