### ISSUE TITLE
 Service Worker update crashes with property access on undefined

### ISSUE THREAD

**Issue by starman15** [angular/angular#33764] opened 2019-11-12 17:56 UTC
# 🐞 bug report

### Affected Package
Service worker     "@angular/service-worker": "^8.2.0",

### Is this a regression?

Possibly.  I've been using service worker since it was first released and began seeing this issue with angular 6.x

### Description

Driver state: EXISTING_CLIENTS_ONLY (Degraded due to failed initialization: Cannot read property 'previouslyCachedResources' of undefined
TypeError: Cannot read property 'previouslyCachedResources' of undefined
    at Driver.<anonymous> (https://test.taramala.com/ngsw-worker.js:2638:32)
    at Generator.next (<anonymous>)
    at fulfilled (https://test.taramala.com/ngsw-worker.js:1801:62))
Latest manifest hash: none
Last update check: 18s119u

This problem seems a lot like that reported in https://github.com/angular/angular/issues/24333

## 🔬 Minimal Reproduction
1. Go to https://dev.taramala.com

2. Login to this dev environment using demo as the username and 'd' as the password
3. Just keep the page open and refresh from time to time.  It may take a few hours before it happens but a blue box with a triangle will appear in the top right.  This means the error started happening.  If you go to https://dev.taramala.com/ngsw/state you'll see the error status shown above.

## 🔥 Exception or Error
<pre><code>
Driver state: EXISTING_CLIENTS_ONLY (Degraded due to failed initialization: Cannot read property 'previouslyCachedResources' of undefined
TypeError: Cannot read property 'previouslyCachedResources' of undefined
    at Driver.<anonymous> (https://test.taramala.com/ngsw-worker.js:2638:32)
    at Generator.next (<anonymous>)
    at fulfilled (https://test.taramala.com/ngsw-worker.js:1801:62))

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.3.10
Node: 10.16.1
OS: win32 x64
Angular: 8.2.11
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
... service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.802.2
@angular-devkit/build-angular     0.802.2
@angular-devkit/build-optimizer   0.802.2
@angular-devkit/build-webpack     0.802.2
@angular-devkit/core              8.2.2
@angular-devkit/schematics        8.3.10
@angular/cdk                      8.2.3
@angular/cli                      8.3.10
@angular/flex-layout              8.0.0-beta.27
@angular/http                     7.2.15
@angular/language-service         <error>
@angular/material                 8.2.3
@angular/pwa                      0.803.10
@ngtools/webpack                  8.2.2
@schematics/angular               8.3.10
@schematics/update                0.803.10
rxjs                              6.5.3
typescript                        3.5.3
webpack                           4.41.2

</code></pre>

**Anything else relevant?**

**Comment by ajitsinghkaler** [comment] 2019-11-12 18:05
@starman15 this is a mistakenly put by you @brad @kara  can you please close this issue.

**Comment by starman15** [comment] 2019-11-12 18:10
Sorry.  Not familiar with this system and have now finished entering the case.

**Comment by ajitsinghkaler** [comment] 2019-11-12 18:41
@starman15 Sorry earlier when I opened this issue the issue seemed empty and I thought that you may have submitted it by mistake.

**Comment by gkalpak** [comment] 2019-11-13 10:45
This error should no longer happen after 094538c0c (and 72eba7745 should also help eliminating the root cause). I am going to close this issue now.

Please open a new issue if you still see the error after upgrading to the latest 9.x version (or the upcomming 8.2.14).

**Closed by gkalpak** 2019-11-13 10:45 UTC
Labels: comp: service-worker
