### ISSUE TITLE
Allow test to replace/stub a single component in an imported module

### ISSUE THREAD

**Issue by pcroc** [angular/angular#24607] opened 2018-06-21 12:03 UTC
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
I am testing a large dashboard-like component which uses many smaller components within it. The child components are imported from another module SharedModule:

```
beforeEach(async(() => {
  TestBed.configureTestingModule({
    declarations: [ ParentComponent ],
    imports: [ SharedModule, RouterTestingModule.withRoutes(routes) ]
  })
  .compileComponents();
}));
```

One of the used child components (from Shared) now got changed and depends on the behaviour of some injected services. I'd like to provide a stub version of *just this component*, for the parent test:

```
@Component({ selector: 'xx-todays-news', template: '' })
export class TodaysNewsStubComponent { }

beforeEach(async(() => {
  TestBed.configureTestingModule({
    declarations: [ ParentComponent, TodaysNewsStubComponent ],
    imports: [ SharedModule, RouterTestingModule.withRoutes(routes) ]
  })
  .compileComponents();
}));
```

But now get an error:
```
Error: Template parse errors:
More than one component matched on this element.
Make sure that only one component's selector can match a given element.
Conflicting components: TodaysNewsComponent,TodaysNewsStubComponent ("
  </div>
  <div class="container my-4">
    [ERROR ->]<xx-todays-news></xx-todays-news>
  </div>
  <div class="container">
"): ....
```

## Expected behavior
I am able to replace/stub a single imported component without causing errors.

## Minimal reproduction of the problem with instructions
See above

## What is the motivation / use case for changing the behavior?
Allow us to stub out a single component without having to re-implement an entire module.

With the current behaviour I am forced to either choose between:
- import the module, and provide stubs for every service that is required by any of the components used by the parent
- do not import the module **or any other modules that also import it**, and then declare individually every component that is used by the parent

The bold part is significant - by needing to stub out just one component in a widely-imported module, the test module can't import any other modules that have it as a dependency. The test also now has a whole lot of component declarations that need to be maintained.

## Environment

<pre><code>
Angular CLI: 1.7.3
Node: 8.11.1
OS: linux x64
Angular: 5.2.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.7.3
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.5.3
webpack: 3.11.0
</code></pre>

**Comment by trotyl** [comment] 2018-06-21 12:44
Possibly duplicate of https://github.com/angular/angular/issues/17474 or https://github.com/angular/angular/issues/22797

**Comment by vikerman** [comment] 2018-12-05 00:01
Duplicate.

**Closed by vikerman** 2018-12-05 00:01 UTC
Labels: comp: testing
