### ISSUE TITLE
Meta class addTag() with httpEquiv MetaDefinition adds incorrect attribute

### ISSUE THREAD

**Issue by chrisnghs** [angular/angular#31525] opened 2019-07-12 10:17 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/platform-browser

### Is this a regression?

 Not sure, tested on latest version only

### Description

 this.meta.addTag({ httpEquiv: "Content-Security-Policy", content: "default-src 'self';" }); 
adds <meta **httpequiv**="Content-Security-Policy" content="default-src 'self';"> to HTML <header> attribute should be **http-equiv** instead

## 🔬 Minimal Reproduction

 [https://angular-issue-repro2-jgtevn.stackblitz.io] [src](https://stackblitz.com/edit/angular-issue-repro2-jgtevn)

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 7.3.1
Node: 11.9.0
OS: linux x64
Angular: 
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.13.1
@angular-devkit/core         7.3.1
@angular-devkit/schematics   7.3.1
@schematics/angular          7.3.1
@schematics/update           0.13.1
rxjs                         6.3.3
typescript                   3.2.4

</code></pre>

**Comment by sabeersulaiman** [comment] 2019-07-12 17:28
Looks like a bug, one way can you can work around the issue is to use the following snippet
```ts
this._meta.addTag({'http-equiv': 'Content-Security-Policy', content: "default-src 'self';" });
```

I can confirm the issue is persistent in v8.1.1, check this repo for [reproduction.](https://github.com/sabeersulaiman/angular-repro-httpequiv)

Seems like the issue is with how the Meta class calls the `setAttribute` method with the keys of the object. I would like to work on this issue.

An easy fix would be to check if the `httpEquiv` key is present and change the value passed to the `setAttribute` method, in which case we may also have to make changes to the code that checks for pre-existing meta tags.

**Comment by pkozlowski-opensource** [comment] 2020-05-25 13:05
I'm not sure why we are assuming that this is a bug. The `Meta` service should just add entries as specified by a user and not try to interpret / change them in any way - doing so would be really confusing. 

> one way you can work around the issue is to use the following code instead

I don't think that this is a work-arround - I would say that this is the proper and recommended way of doing things. Again, we want to limit surprising behaviour in the framework.

Here is a working stackblitz illustrating the recommended approach: https://stackblitz.com/edit/angular-tyjtsd?file=src/app/app.module.ts

I'm going to close this issue as I don't think we should be doing any transformation on meta keys provided by a user.

**Comment by pkozlowski-opensource** [comment] 2020-05-25 13:08
Ohhh, actually, r

**Comment by pkozlowski-opensource** [comment] 2020-05-25 13:12
This is a confirmed bug where our types suggest supplying value that doesn't work in practice. 

The problem here is that the [MetaDefinition](https://github.com/angular/angular/blob/540c29cd6bfc4124a30f5f8e7b599d326baf6af4/packages/platform-browser/src/browser/meta.ts#L20) specifies `httpEquiv?: string` while the actual key name should be `http-equiv?: string` (or we should have some sort of mapping) as suggested in #32531.

**Comment by AndrewKushnir** [comment] 2021-02-06 02:10
Closing this issue since the corresponding PR #32531 was merged.

**Closed by AndrewKushnir** 2021-02-06 02:10 UTC
Labels: P3, comp: core, core: DOM rendering, freq1: low, state: confirmed, state: has PR, triage #1, type: bug/fix
