### ISSUE TITLE
ng-content inside ngFor only added once

### ISSUE THREAD

**Issue by bennylut** [angular/angular#6571] opened 2016-01-19 21:42 UTC
Using ng-content inside ngFor produce a single content. 
For example:
```typescript
@Component({
    selector: 'some-component',
    template: `
        <div *ngFor="#x of arr">
            <ng-content></ng-content>
       </div>
    `
});
class SomeComponent {
    arr = [1,2,3];
}

@Component({
    selector: 'app'
    template: `
        <some-component> data </some-component>
    `,
    directives: [SomeComponent]
}) 
class App {}
```

produces the word "data" a single time instead of three times.  (plunker: https://plnkr.co/edit/p6YA4dAsuiybTjtnSBnz)

**Comment by ericmartinezr** [comment] 2016-01-19 22:20
That's by design, check https://github.com/angular/angular/issues/4631

**Comment by pkozlowski-opensource** [comment] 2016-01-20 11:24
Yep, this is duplicate of #4631, thnx @ericmartinezr !

**Closed by pkozlowski-opensource** 2016-01-20 11:24 UTC

**Comment by mcchae7** [comment] 2018-08-02 19:42
Simple List Component Example with dynamic ngTemplate: https://stackblitz.com/edit/angular-list-ngtemplateoutlet
