### ISSUE TITLE
HttpParams.toString multiplication after parameter deletion

### ISSUE THREAD

**Issue by 3orys** [angular/angular#23432] opened 2018-04-18 14:36 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

When using HttpParams, after deleting particular parameter, toString() returns unexpected result. Using angular version 5.1.0 (haven't checked whether later versions have similar results).
<pre><code>
let params = new HttpParams();

params = params.append('param1', 'firstParamValue');
params = params.append('param2', 'secondParamValue');

// OK, outputs:
// param1=firstParamValue&param2=secondParamValue
console.warn(params.toString()); 

params.delete('param1');

// OK, outputs:
// param1=firstParamValue&param2=secondParamValue
console.warn(params.toString())

params = params.delete('param2');

// not OK I suppose, or is this correct behavior? outputs:
// param1=firstParamValue&param1=firstParamValue
console.warn(params.toString());
</code></pre>

## Expected behavior

Shouldn't the last output be "param1=firstParamValue"?

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by trotyl** [comment] 2018-04-18 16:08
Duplicate of https://github.com/angular/angular/issues/20430

**Comment by alxhub** [comment] 2018-04-24 22:16
Closing as a duplicate.

**Closed by alxhub** 2018-04-24 22:16 UTC
Labels: comp: common/http
