### ISSUE TITLE
Angular uses old URL params when calling router.navigate from a resolver

### ISSUE THREAD

**Issue by dzinxed** [angular/angular#34675] opened 2020-01-08 13:33 UTC
# 🐞 Angular uses old URL params when calling router.navigate from a resolver

### Affected Package
Router. Specifically, [this line](https://github.com/angular/angular/blob/18d89c9c891844440a919b835c0f198a2b7395a6/packages/router/src/router.ts#L983)

### Is this a regression?
Probably not, the inconsitency is caused by urlUpdateStrategy, which is a recent thing.

### Description
When you call router.navigate from a resolver (e.g. when a resolver determines that the user does not have required permissions and you want to redirect to an error page), the query parameters of the URL are not taken from the URL. Rather, they are taken from rawUrlTree. This can cause a problem because the parameters might have changed with urlUpdateStrategy set to 'eager'.

## 🔬 Minimal Reproduction
Here's a stackblitz repro based on heroes app from the router tutorial:
https://stackblitz.com/edit/angular-router-redirect

The example is changed from [the original](https://angular.io/guide/router#wrap-up-and-final-app) in the following ways:
 - it keeps the user ID in a query param instead of the path param,
 - initially, it loads /superheroes?id=11,
 - for /superhero path, it adds a RedirectingResolver that, when id=12, redirects to /crisis-center,
 - it has urlUpdateStrategy: 'eager'.

*To trigger the error, follow these steps*:
1. Open https://stackblitz.com/edit/angular-router-redirect
1. You should start on the list of heroes (url is /superheroes?id=11), with hero 11 selected.
1. Click "Narco" (hero 12) (its URL is /superhero?id=12)
1. See that you get redirected to /crisis-center?id=11.

However, if you look at RedirectingResolver in heroes-routing.module.ts, you'll see that:
 - it checks for query parameter and determines it's equal to 12
 - it redirects to /crisis-center with merged query params

With urlUpdateStragegy: 'eager' in app-routing.module.ts, I would expect to land at /crisis-center?id=12.

## 🌍  Your Environment

**Angular Version:**
Angular 8.2.14 on StackBlitz.

## Fix proposal

This issue could be fixed by changing [this line](https://github.com/angular/angular/blob/18d89c9c891844440a919b835c0f198a2b7395a6/packages/router/src/router.ts#L983):

<code>const mergedTree = this.urlHandlingStrategy.merge(urlTree, this.rawUrlTree);</code>

to:

<code>const mergedTree = this.urlHandlingStrategy.merge(urlTree, this.browserUrlTree);</code>

Then, the code behaves as expected: you get redirected to /crisis-center?id=12. As browserUrlTree is updated in coordination with urlUpdateStrategy, it will correctly merge the new id when constructing the URL to redirect to.

**Comment by atscott** [comment] 2020-06-04 21:59
At first glance, this seems like it could break current behavior pretty significantly. `this.currentUrlTree` represents the url of the activated route and is currently set right before activating the route synchronously. The proposed solution in the issue report mentioned using `browserUrlTree` rather than `rawUrlTree`, which would respect the `eager`/`deferred` values for `urlUpdateStrategy` and seems reasonable. Did you happen to try that, and if so, did it not work as expected or break something?

**Comment by praveeno** [comment] 2021-01-31 08:51
Hello, is this issue is ready to accept PR?

**Comment by praveeno** [comment] 2021-01-31 08:59
If anyone else not already working on this, Can i submit a PR for this?

**Comment by atscott** [comment] 2021-03-17 22:14
Closing - this is working as intended. The information in the resolver is about the current route. A new navigation triggered by `router.navigate` should cancel the previous navigation. There was no successful navigation to `?id=12` so the resulting id on the crisis center should be 11.

**Closed by atscott** 2021-03-17 22:14 UTC
Labels: P3, comp: router, effort1: hours, freq2: medium, help wanted, router: URL parsing/generation, router: guards/resolvers, router: navigation pipe, state: confirmed, triage #1, type: bug/fix
