### ISSUE TITLE
Set attribute error when compiling

### ISSUE THREAD

**Issue by isaacvr** [angular/angular#39173] opened 2020-10-08 02:58 UTC
# 🐞 bug report

### Description
There is a very strange event that happened today. It seems to be a problem of Angular instead of my code because the code was running fine until I added a call to a function. It's very hard to explain, so please take a look of this:

<img width="851" alt="angular_error" src="https://user-images.githubusercontent.com/18685720/95409522-c88fb800-08ef-11eb-884d-ab5eb03a9752.png">

## 🔬 Minimal Reproduction
I don't have any idea of how to reproduce this error. It's so strange that the name of the attribute changes every time and sometimes it works and sometimes WITH THE SAME CODE, it fails. That's totally crazy, please, fix it!!!

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 10.0.8
Node: 10.14.2
OS: win32 x64

Angular: 10.0.14
... common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.12
@angular-devkit/build-angular     0.1000.8
@angular-devkit/build-optimizer   0.901.12
@angular-devkit/build-webpack     0.901.12
@angular-devkit/core              9.1.12
@angular-devkit/schematics        10.0.8
@angular/animations               10.1.2
@angular/cdk                      10.2.1
@angular/cli                      10.0.8
@angular/material                 10.2.1
@ngtools/webpack                  9.1.12
@schematics/angular               10.0.8
@schematics/update                0.1000.8
rxjs                              6.6.2
typescript                        3.9.7
webpack                           4.42.0
</code></pre>

**Anything else relevant?**
I'm currently working in the Electron environment. I don't know if that's useful, but maybe it make sense for you.

**Comment by atscott** [comment] 2020-10-08 16:41
Hi @isaacvr, could you please provide a reproduction of this issue? Without a reproduction, we will not be able to investigate any further.

**Comment by AleksanderBodurri** [comment] 2020-10-15 03:05
Are you providing the [`APP_ID`](https://angular.io/api/core/APP_ID) di token manually in any module?

The [DOM spec](https://dom.spec.whatwg.org/#dom-element-setattribute) defines constraints on what characters can be used as attribute names for `Element.prototype.setAttribute`.

The Dom Renderer uses the `APP_ID` constant to create unique `_nghost` and `_ngcontent` prefixes to be used for emulated view encapsulation (internally it will call `Element.prototype.setAttribute` with a name that contains the string representation of `APP_ID`).

 It looks to me like `APP_ID` is being provided manually as something not within the constraints of `Element.prototype.setAttribute`. Hard to say for sure without a reproduction app to test on.

**Comment by jelbourn** [comment] 2020-10-19 22:02
Closing since there's been no update with more information

**Closed by jelbourn** 2020-10-19 22:02 UTC
Labels: comp: core, needs clarification, needs reproduction
