### ISSUE TITLE
Router no longer navigates when navigating to the current URL.

### ISSUE THREAD

**Issue by Kriskit** [angular/angular#13340] opened 2016-12-09 11:17 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When navigating to the current URL, the route is not reloaded and no navigation events are fired.

**Expected behavior**

The router should navigate to the route, firing the navigation events.

**Minimal reproduction of the problem with instructions**

Plunker:
http://plnkr.co/edit/TlRwYcDmV0JacgD9UgFU?p=preview

Click the link for the current page and note the events don't fire.

**What is the motivation / use case for changing the behavior?**

My specific case is that I have been using the router events to enable me to scroll the page back to the top when the NavigationEnd event is fired. This no longer gets fired when navigating to the current URL and so when someone is on my home page and scrolls down to the bottom, if they click a home link it doesn't scroll them back to the top. Also, if this were running as a standard website, the page would reload in this circumstance. This used to work absolutely fine but has since changed after upgrading. 

At the very least it would be good to be able to have an option when initialising the routes to change this behaviour.

* **Angular version:** 2.3.0

* **Browser:** all

 
* **Language:** all

* **Node (for AoT issues):** `node --version` =

**Comment by martinop** [comment] 2016-12-10 20:27
I have this problem too, pls help

**Comment by vsavkin** [comment] 2016-12-21 14:14
The router is a state machine. 

Being able to navigate to the "current state" might lead to confusing behaviour. For example, consider this scenario:

- The current state is A
- I'm navigating to A
- A guard rejects the navigation
- I'm supposed to go back to the current state, which is A, which I'm no longer allowed to navigate to. Sort of.

Also, we are considering rerunning resolvers every time a navigation happens, which won't work with your use case as well.

I think we should either always allow it, or never allow it, so don't have an extra option. 

Is it just the scrolling you are concerned about? If so, maybe it's better to have a directive with this selector `[routerLink]` that will force the scrolling?

**Comment by Kriskit** [comment] 2016-12-21 16:03
I understand what you're saying but it still feels like the router should at least tell us **something**, even if it was a `NavigationCancel` event. At present, despite a call being made to the router to navigate (through a `[routerLink]` click or otherwise) no events get fired at all.

I'm not convinced using a `[routerLink]` selector directive would cover everything I need it to do but I will give it a try, although feels like a workaround.

**Comment by DzmitryShylovich** [comment] 2016-12-21 19:37
Duplicate of https://github.com/angular/angular/issues/13166

**Comment by tipag** [comment] 2016-12-22 08:22
In our application we navigate to a page with "skipLocationChange". In this case the url in the browser stays the same, and no history entry is created. On the new Page we then, update the query parameters according to some information we get from our backend service. Once we receive the data we navigate to the same page with the intention to create a history entry. In some cases however, no data is returned from the service which we need to display in the query parameters. That's when we navigate to the same page the router holds as state. This state however is not displayed in the browser url and neither in the browser history state.

We need this whole procedure to make back and forward navigation in our application work correctly. Of course we could just navigate to the page without skipLocationChange but then we would have multiple history entries for this page. Also navigating back in browser history would lead to our page being reloaded, meaning it would again update the query parameter and then the browser navigation will end up in an endless loop.

So I guess if navigating to the same state is not an option, the router should provide the functionality to update the browser url and history without actually navigating.

**Comment by vsavkin** [comment] 2016-12-22 21:25
@Kriskit Firing some sort of event is a good idea. Maybe "IgnoredNavigation" or something like that.

**Comment by macd2point0** [comment] 2017-02-23 21:26
It looks like the NavigationStart event occurs after urlHandlingStrategy.shouldProcessUrl(rawUrl), I have been of the school of thought that you fire a start event then you do stuff, in this implementation stuff is done (shouldProcessUrl) before the start event. NavigationStart should be renamed to RoutingStart and NavigationStart should fire immediately after any navigation event.

**Comment by willshowell** [comment] 2017-04-27 16:53
I would love to see this reviewed again. The `IgnoredNavigation` event would work well for our use case.

**Comment by macd2point0** [comment] 2017-08-10 22:20
from router.ts

  private executeScheduledNavigation({id, rawUrl, extras, resolve, reject}: NavigationParams):
      void {
    const url = this.urlHandlingStrategy.extract(rawUrl);
    const urlTransition = !this.navigated || url.toString() !== this.currentUrlTree.toString();

    if (urlTransition && this.urlHandlingStrategy.shouldProcessUrl(rawUrl)) {
      this.routerEvents.next(new NavigationStart(id, this.serializeUrl(url)));
      Promise.resolve()
          .then(
              (_) => this.runNavigate(
                  url, rawUrl, !!extras.skipLocationChange, !!extras.replaceUrl, id, null))
          .then(resolve, reject);

      // we cannot process the current URL, but we could process the previous one =>
      // we need to do some cleanup
    } else if (
        urlTransition && this.rawUrlTree &&
        this.urlHandlingStrategy.shouldProcessUrl(this.rawUrlTree)) {
      this.routerEvents.next(new NavigationStart(id, this.serializeUrl(url)));
      Promise.resolve()
          .then(
              (_) => this.runNavigate(
                  url, rawUrl, false, false, id,
                  createEmptyState(url, this.rootComponentType).snapshot))
          .then(resolve, reject);

    } else {
      this.rawUrlTree = rawUrl;
      resolve(null);
    }
  }

I think developers would like to see some sort of event fire before going through the if tree, something to indicate that an attempt to navigate was made

**Comment by jibbers42** [comment] 2017-08-10 23:25
> I think developers would like to see some sort of event fire before going through the if tree, something to indicate that an attempt to navigate was made

I'd like to see the component(s) refreshed (as the OP titled and described). I don't disagree with a new event as suggested in this thread, but it would be best for a separate issue to be created for that.

**Closed** 2017-10-24 04:58 UTC
Labels: comp: router, hotlist: google

**Comment by corbfon** [comment] 2018-01-18 20:40
For anyone else finding this issue in the future, it looks like `router.navigate()` returns a promise, which holds the value `true` if navigation occurred. This is what I've been using for fallback behavior

**Comment by lemoinem** [comment] 2018-02-08 20:08
As far as I can see, this issue is closed, but the "navigations" Observable in the router is private.
Is there another feature request or way of allowing a end-user to listen to navigation.

My use case is a single component (enclosing an iframe) that needs to reset its state (iframe's URL) when the user clicks on a link toward the current page.
Having a directive override `[routerLink]` for my whole application seems a bit overkill...

In my case, being able to override `onSameUrlNavigation` on a per-route basis would be perfect (actually)...

**Comment by mlc-mlapis** [comment] 2018-02-08 21:32
@lemoinem ... it is not clear why you aren't able to reset anything on the base any observable from `router.events` / `running an attached guard` / `running attached resolver` on the base of setting `onSameUrlNavigation` flag.
