### ISSUE TITLE
Extractor no longer extracts the parameter/expression of the interpolated string into disp attribute

### ISSUE THREAD

**Issue by jaska45** [angular/angular#38711] opened 2020-09-04 11:07 UTC
# 🐞 bug report

### Is this a regression?

Yes. This used to work in 10.0 and earlier.

### Description

Extractor no longer extracts the parameter/expression of the interpolated string into disp attribute

## 🔬 Minimal Reproduction

Repo is [here](https://github.com/jaska45/DisplayBug).

Write an interpolated string that has any parameter. For example

`<p i18n>My name is {{name}}</p>`

Then run the extractor

`ng xi18n --format=xlf2 --output-path src/locale --ivy`

The result XLIFF no longer contain disp attribute of it does not contain the parameter/expression used in the interpolated string

```
      <segment>
        <source>My name is <ph id="0" equiv="INTERPOLATION" disp="&quot;\uFFFD0\uFFFD&quot;"/></source>
      </segment>

```
This used to be

```
      <segment>
        <source>My name is <ph id="0" equiv="INTERPOLATION" disp="{{name}};"/></source>
      </segment>

```

## 🌍  Your Environment

**Angular Version:**

```
Angular CLI: 10.1.0
Node: 12.9.1
OS: win32 x64

Angular: 10.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1001.0
@angular-devkit/build-angular     0.1001.0
@angular-devkit/build-optimizer   0.1001.0
@angular-devkit/build-webpack     0.1001.0
@angular-devkit/core              10.1.0
@angular-devkit/schematics        10.1.0
@ngtools/webpack                  10.1.0
@schematics/angular               10.1.0
@schematics/update                0.1001.0
rxjs                              6.6.2
typescript                        4.0.2
webpack                           4.44.1
```

**Comment by sonukapoor** [comment] 2020-09-04 12:22
Hi, @jaska45 Is this different from the other issue you posted #38711?

**Comment by jaska45** [comment] 2020-09-04 12:30
Yes this is a different issue

**Comment by petebacondarwin** [comment] 2020-09-04 12:48
This might be fixed by https://github.com/angular/angular/pull/38645 I will test later today

**Comment by petebacondarwin** [comment] 2020-09-04 14:42
Tested locally and #38645 does appear to fix this issue. Running the commands on the above reproduction results in:

```xml
<?xml version="1.0" encoding="UTF-8" ?>
<xliff version="2.0" xmlns="urn:oasis:names:tc:xliff:document:2.0" srcLang="en-US">
  <file id="ngi18n" original="ng.template">
    <unit id="5078016957909331967">
      <segment>
        <source>My name is <ph id="0" equiv="INTERPOLATION" disp="{{name}}"/></source>
      </segment>
    </unit>
  </file>
</xliff>
```

**Comment by AndrewKushnir** [comment] 2020-09-08 21:39
FYI, the changes were merged to master and will be release within 10.1.1 version. Thank you.

**Comment by jaska45** [comment] 2020-09-09 21:23
I tested with 10.1.1. It works if the legacy extractor is used. However if I use the ivy option the disp value is not right.

`ng xi18n --format=xlf2 --output-path src/locale --ivy`

**Comment by petebacondarwin** [comment] 2020-09-10 10:35
@jaska45 - are you talking about the repo you originally posted?

**Comment by petebacondarwin** [comment] 2020-09-10 10:47
Similarly I did:

```
ng update @angular/core@10.1.1
ng xi18n --format=xlf2 --output-path src/locale --ivy
```

And again got what I expected.

Can you clarify how to reproduce the problem?

**Comment by jaska45** [comment] 2020-09-10 12:31
I did the same but got wrong result.
I updated to repo and pushed changes.

**Comment by petebacondarwin** [comment] 2020-09-10 12:53
I just pulled down your updated repo and re-ran the command. This is what I see in `messages.xlf`:

```xml
<?xml version="1.0" encoding="UTF-8" ?>
<xliff version="2.0" xmlns="urn:oasis:names:tc:xliff:document:2.0" srcLang="en-US">
  <file id="ngi18n" original="ng.template">
    <unit id="5078016957909331967">
      <notes>
        <note category="location">src/app/app.component.html:1</note>
      </notes>
      <segment>
        <source>My name is <ph id="0" equiv="INTERPOLATION" disp="{{name}}"/></source>
      </segment>
    </unit>
  </file>
</xliff>
```

This seems correct to me. Can you check that the correct packages are installed by deleting `node_modules` and reinstalling?

**Comment by jaska45** [comment] 2020-09-10 13:36
You got it right. Did you use Mac? I just tried my repo on Mac and it works. Initially I used Windows 10 where it does not work. I will try on another Windows box.

**Comment by jaska45** [comment] 2020-09-10 13:48
I just tried on another Windows and it does not work. I have now tried on two Windows and got the same (wrong) result on both of them. On Mac it works.

**Comment by jaska45** [comment] 2020-09-10 13:49
This is the info of my second Windows box.

```
Angular CLI: 10.1.0
Node: 14.9.0
OS: win32 x64
Angular: 10.1.1
```

**Comment by petebacondarwin** [comment] 2020-09-10 18:04
OK, so it is something to do with the CLI integration... on Windows I get the same problem if I use `ng xi18n`.
But try the following:

```bash
node_modules\.bin\ngc -p tsconfig.app.json
node_modules\.bin\localize-extract -s out-tsc\**\*.js -f xlf2 -o src\locale\messages.xlf
```

This generates the correct output.

**Comment by petebacondarwin** [comment] 2020-09-10 18:04
Perhaps @clydin has some ideas?

**Comment by petebacondarwin** [comment] 2020-09-12 16:16
OK, I worked out what is going on. The localize stuff relies upon a `FileSystem`, which the CLI is mocking up to get everything to work. But... internally the extraction is calling `absoluteFrom()`, which looks for a "current" `FileSystem` by calling `getFileSystem()`. This is a kind of global that should be set via `setFileSystem()` before running the localize code.

I'll look into the best way to fix this...

**Closed** 2020-09-30 19:49 UTC
Labels: comp: i18n, engine: ivy, freq2: medium, os: Windows, severity5: regression, state: has PR, type: bug/fix

**Comment by Niklas187** [comment] 2020-10-09 09:38
Hey guys, I still have a problem with the "equiv-text" attribute.
I am using the latest  tag  `10.1.6` from the CLI but some translation messages still have  incorrect  values.

eg.:
`     <ng-container i18n="Update @@update">
   <b>{{value1}}:</b>
    current {{value2}}
    to new {{value3}}
  </ng-container>`

will be extracted as (with --ivy): 
```
        <source>
                <x id="START_BOLD_TEXT" equiv-text="  &lt;b&gt;{{value1"/>
                <x id="INTERPOLATION" equiv-text="b&gt;{{value1"/>:
                <x id="CLOSE_BOLD_TEXT" equiv-text="}:&lt;/b&gt;"/>
                 current <x id="INTERPOLATION_1" equiv-text="t {{value2"/> 
                 to new <x id="INTERPOLATION_2" equiv-text=" to new {{"/>
       </source>
```

will be extracted as (**without** --ivy): 
```
        <source>
                <x id="START_BOLD_TEXT" ctype="x-b" equiv-text="&lt;b&gt;"/>
                <x id="INTERPOLATION" equiv-text="{{value1}}"/>: 
                <x id="CLOSE_BOLD_TEXT" ctype="x-b" equiv-text="&lt;/b&gt;"/>
                current <x id="INTERPOLATION_1" equiv-text="{{value2}}"/>
                to new <x id="INTERPOLATION_2" equiv-text="{{value3}}"/>
        </source>
```

Is this an issue in my code or in the cli extraction command?

Example Repo https://github.com/Niklas187/ng-xi18n-ivy-bug.git


version: 
> 
> Angular CLI: 10.1.6
> Node: 12.16.0
> OS: win32 x64
> 
> Angular: 10.1.3
> ... animations, common, compiler, core, forms, localize
> ... platform-browser, platform-browser-dynamic, router
> Ivy Workspace: Yes
> 
> Package                         Version
> ---------------------------------------------------------
> @angular-devkit/architect       0.1001.6
> @angular-devkit/build-angular   0.1001.6
> @angular-devkit/core            10.1.6
> @angular-devkit/schematics      10.1.6
> @angular/cli                    10.1.6
> @angular/compiler-cli           10.1.5
> @schematics/angular             10.1.6
> @schematics/update              0.1001.6
> rxjs                            6.6.3
> typescript                      4.0.3

**Comment by petebacondarwin** [comment] 2020-10-09 10:02
@Niklas187 - I just tried you reproduction - it doesn't include the example in you comment so I added that. These are the results I get (on OS/X not Windows):

**Without ivy:** (`ctype` attributes removed for clarity)
```xml
<source>
  <x id="START_BOLD_TEXT" equiv-text="&lt;b&gt;"/>
  <x id="INTERPOLATION" equiv-text="{{value1}}"/>:
  <x id="CLOSE_BOLD_TEXT" equiv-text="&lt;/b&gt;"/> current
  <x id="INTERPOLATION_1" equiv-text="{{value2}}"/> to new
  <x id="INTERPOLATION_2" equiv-text="{{value3}}"/>
</source>
```

**With ivy:**
```xml
<source>
  <x id="START_BOLD_TEXT" equiv-text="&lt;b&gt;{{value1}}"/>
  <x id="INTERPOLATION" equiv-text="{{value1}}"/>:
  <x id="CLOSE_BOLD_TEXT" equiv-text="&lt;/b&gt; "/> current
  <x id="INTERPOLATION_1" equiv-text="{value2}} "/> to new
  <x id="INTERPOLATION_2" equiv-text="{value3}} "/>
</source>
```

Interestingly this is a bit different from your output but I agree that it is not quite right.

It seems that there is some offsetting going on, which is making the start and end points in the `equiv-text` appear in the wrong place. I'll need to debug into this but since these `equiv-text` attributes are primarily to aid the translator's job, it will not be high on my priority list. Hopefully I can take a look at it later next week or the week after.

Also, this issue is a different problem to what this issue was about, so I'll start a new issue to track this.

**Comment by niklasherw** [comment] 2020-11-09 13:28
> @Niklas187 - I just tried you reproduction - it doesn't include the example in you comment so I added that. These are the results I get (on OS/X not Windows):
> 
> **Without ivy:** (`ctype` attributes removed for clarity)
> 
> ```
> <source>
>   <x id="START_BOLD_TEXT" equiv-text="&lt;b&gt;"/>
>   <x id="INTERPOLATION" equiv-text="{{value1}}"/>:
>   <x id="CLOSE_BOLD_TEXT" equiv-text="&lt;/b&gt;"/> current
>   <x id="INTERPOLATION_1" equiv-text="{{value2}}"/> to new
>   <x id="INTERPOLATION_2" equiv-text="{{value3}}"/>
> </source>
> ```
> 
> **With ivy:**
> 
> ```
> <source>
>   <x id="START_BOLD_TEXT" equiv-text="&lt;b&gt;{{value1}}"/>
>   <x id="INTERPOLATION" equiv-text="{{value1}}"/>:
>   <x id="CLOSE_BOLD_TEXT" equiv-text="&lt;/b&gt; "/> current
>   <x id="INTERPOLATION_1" equiv-text="{value2}} "/> to new
>   <x id="INTERPOLATION_2" equiv-text="{value3}} "/>
> </source>
> ```
> 
> Interestingly this is a bit different from your output but I agree that it is not quite right.
> 
> It seems that there is some offsetting going on, which is making the start and end points in the `equiv-text` appear in the wrong place. I'll need to debug into this but since these `equiv-text` attributes are primarily to aid the translator's job, it will not be high on my priority list. Hopefully I can take a look at it later next week or the week after.
> 
> Also, this issue is a different problem to what this issue was about, so I'll start a new issue to track this.

Hi @petebacondarwin, did you solve this issue (in 10.2.0) or do you have a link to the new issue ?

Thanks in advance,
Niklas
