### ISSUE TITLE
make http interceptor configuration available on Component level

### ISSUE THREAD

**Issue by ayaka209** [angular/angular#19852] opened 2017-10-22 08:45 UTC
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[*] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
now,  http interceptors have to added inside NgModule, 
```
{
			provide: HTTP_INTERCEPTORS,
			useClass: xxxInterceptor,
			multi: true,
}  
```
if add it to Component, http client ignores the interceptor. the interceptor is not called.

## Expected behavior
interceptor added into Component providers section should affect the component.

## Minimal reproduction of the problem with instructions
```
@Component({
	providers: [
		{
			provide: HTTP_INTERCEPTORS,
			useClass: xxxInterceptor,
			multi: true,
		}                        <------------ not working now.
	],
})                
```
## What is the motivation / use case for changing the behavior?
I need add interceptor in one component but some other components need another interceptor. 

## Environment

<pre><code>
Angular version: 4.4.3

Browser:
- [ ] Chrome (desktop) version XX
- [*] Chrome (Android) version 53
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.2.1, Ionic 3.7.1
- Platform:  Android

Others:

</code></pre>

Thank you.

**Comment by trotyl** [comment] 2017-10-22 13:14
Likely relates #18894.

**Comment by jasonaden** [comment] 2017-11-10 22:53
I've added this to the `common/http` component for second-level triage. It looks like this is caused by #18894 and could be resolved once that issue is.

**Comment by petebacondarwin** [comment] 2021-07-01 14:46
This particular issue did not get hardly any votes, but appears to be a special case of #18894, so I am going to close this and leave a note on that one.

**Closed by petebacondarwin** 2021-07-01 14:46 UTC
Labels: comp: common/http, feature, insufficient votes, votes required
