### ISSUE TITLE
API results only 2 cols when wide

### ISSUE THREAD

**Issue by wardbell** [angular/angular#17251] opened 2017-06-06 16:35 UTC
We display only two columns of results when the screen is wide and long items may overlap the next column as seen in these screen shots from a browser that is 1270px wide.   Overlap issue also raised in #17250

![image](https://user-images.githubusercontent.com/129061/26840680-c433fd54-4a9b-11e7-8ea4-9a7cfb2fa44b.png)

...

![image](https://user-images.githubusercontent.com/129061/26840707-d6d28368-4a9b-11e7-90d1-3175f58fbd0c.png)

**Comment by sjtrimble** [comment] 2017-06-06 16:59
@wardbell this is also a dupe....

**Comment by wardbell** [comment] 2017-06-06 17:06
It's a partial dup. The two cols issue is separate. Retitled and linked.

**Comment by sjtrimble** [comment] 2017-06-07 16:33
That is due to the TOC taking up 18% of the screen. The list items are set to take up 1/3 of it's container but it only has 82% to work with.

**Comment by gkalpak** [comment] 2017-06-07 16:43
The 82%/18% issue will be fixed by #17293 btw. But it is not sufficient to solve this.

**Comment by sjtrimble** [comment] 2017-06-07 16:56
@gkalpak This issue only addresses the 3 columns item. The overlap issue is a separate one. If so, do you still think #17293 wouldn't fix this?

**Comment by gkalpak** [comment] 2017-06-07 17:04
I meant it won't fix the overlap issue (although it will improve things). Not sure about the two-cols issue, because I can't reproduce it :grin:

**Comment by sjtrimble** [comment] 2017-06-07 17:19
@gkalpak Ok then we're on the same page :) that one is a separate issue. This one is related to the 82%. Once I make md-sidenav-container 100% width, it puts them back in 3 columns b/c it has the space to do so.

**Comment by gkalpak** [comment] 2017-06-09 08:49
Since I can't reproduce the issue, could you confirm that #17293 fixes this?

**Comment by gkalpak** [comment] 2017-06-11 20:03
<sub>(I'll interpret the 👍 as confirmation that it has been fixed :grin:)</sub>

**Comment by gkalpak** [comment] 2017-06-11 20:58
As I mentioned earlier, I cannot reproduce this. If you still see it feel free to reopen the issue :smiley:

**Comment by petebacondarwin** [comment] 2017-06-11 21:11
I added a commit to my other API filter page related PR (#17411) which fixes this.

**Closed** 2017-06-13 06:41 UTC
Labels: comp: aio
