### ISSUE TITLE
Lazy loading module from package located in node_modules fails to build. ng build

### ISSUE THREAD

**Issue by Learn-Ravi** [angular/angular#39042] opened 2020-09-29 13:16 UTC
I am trying to load a module through lazy loading. Giving me this error.

ERROR in ./src/app.routes.ts
Module not found: Error: Can't resolve './../../../../node_modules/@frontend/vanilla/features/src/logout-page/logout-page.module.d.ngfactory' in 'C:\dev\app'

{
        path: 'logout',
        loadChildren: () => import('@frontend/vanilla/features/src/logout-page').then(m => m.LogoutPageModule)
    },

Using below angular version:

"@angular-devkit/architect": "~0.901.7",
		"@angular-devkit/build-angular": "0.901.7",
		"@angular-devkit/build-ng-packagr": "~0.901.7",
		"@angular-devkit/build-optimizer": "~0.901.0",
		"@angular-devkit/core": "~9.1.2",
		"@angular/animations": "~9.1.2",
		"@angular/cdk": "~9.2.4",
		"@angular/cli": "~9.1.7",
		"@angular/common": "9.1.9",
		"@angular/compiler": "~9.1.9",
		"@angular/compiler-cli": "~9.1.9",
		"@angular/core": "~9.1.9",
		"@angular/flex-layout": "9.0.0-beta.31",
		"@angular/forms": "~9.1.9",
		"@angular/localize": "~9.1.9",
		"@angular/material": "~9.2.4",
		"@angular/platform-browser": "~9.1.9",
		"@angular/platform-browser-dynamic": "~9.1.9",
		"@angular/platform-server": "~9.1.2",
		"@angular/router": "~9.1.9",
		"@angular/service-worker": "~9.1.9",
		"@angular/upgrade": "~9.1.2",
		"@angularclass/hmr": "^2.1.3",
		"@angularclass/hmr-loader": "^3.0.4",

Running it on Windows 10. 64 bit

{
  "compilerOptions": {
    "allowJs": false,
    "target": "es5",
    "module": "esnext",
    "stripInternal": true,
    "moduleResolution": "node",
    "declaration": false,
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": ["es5", "dom", "es2015", "esnext.array"],
    "importHelpers": true,
    "outDir": "../ClientDist",
    "noImplicitAny": true,
    "noUnusedParameters": false,
    "noUnusedLocals": true,
    "suppressImplicitAnyIndexErrors": true,
    "baseUrl": ".",
    "paths": {
   
    },
    "typeRoots": [
      "../../node_modules/@types"
    ],
  },
  "angularCompilerOptions": {
    "fullTemplateTypeCheck": true,
    "preserveWhitespaces": true,
    "enableIvy": false
  }
}

**Comment by alan-agius4** [comment] 2020-09-29 17:41
This is working as intended.

Duplicate of https://github.com/angular/angular-cli/issues/6373 see last 2 comments.

**Closed by alan-agius4** 2020-09-29 17:41 UTC

**Comment by Learn-Ravi** [comment] 2020-10-05 06:26
@alan-agius4  This is working if we EnableIvy compilation. Is n't this suspicious that same functionality working by just enabling different compilation. Thoughts?
