### ISSUE TITLE
Error formatting currency in Safari 9 (ReferenceError: Can't find variable: Intl)

### ISSUE THREAD

**Issue by wardbell** [angular/angular#6009] opened 2015-12-18 18:04 UTC
Relocated from `angular.io`, [issue 562](https://github.com/angular/angular.io/issues/562)

angular2: 2.0.0-beta.0
Safari 9.0 (10601.1.56.2)

```
EXCEPTION: ReferenceError: Can't find variable: Intl in [ ({{item.price | currency:'USD':true:'.2-2'}}) in AppComponent@7:164]
logErrorangular2.dev.js:23513
logGroupangular2.dev.js:23524
callangular2.dev.js:1144
(anonymous function)angular2.dev.js:14800
_notifyOnErrorangular2.dev.js:5795
onErrorangular2.dev.js:5699
runangular2-polyfills.js:140
(anonymous function)angular2.dev.js:5718
zoneBoundFnangular2-polyfills.js:110
lib$es6$promise$$internal$$tryCatchangular2-polyfills.js:1510
lib$es6$promise$$internal$$invokeCallbackangular2-polyfills.js:1522
lib$es6$promise$$internal$$publishangular2-polyfills.js:1493
(anonymous function)angular2-polyfills.js:242
microtaskangular2.dev.js:5750
runangular2-polyfills.js:137
(anonymous function)angular2.dev.js:5718
zoneBoundFnangular2-polyfills.js:110
lib$es6$promise$asap$$flushangular2-polyfills.js:1304
promiseReactionJob
```

```
format@http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:15669:22
_format@http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:15824:43
transform@http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:15871:32
detectChangesInRecordsInternal
detectChangesInRecords@http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:8824:44
runDetectChanges@http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:8807:34
_detectChangesContentChildren@http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:8871:30
runDetectChanges@http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:8808:41
_detectChangesInViewChildren@http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:8877:30
runDetectChanges@http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:8811:40
detectChanges@http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:8796:28
detectChanges@http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:4978:29
http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:14977:40
forEach@[native code]
tick@http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:14976:41
_loadComponent@http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:14942:16
tick@http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:14917:33
run@http://localhost:3000/node_modules/angular2/bundles/angular2-polyfills.js:138:22
http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:5719:37
zoneBoundFn@http://localhost:3000/node_modules/angular2/bundles/angular2-polyfills.js:111:22
lib$es6$promise$$internal$$tryCatch@http://localhost:3000/node_modules/angular2/bundles/angular2-polyfills.js:1511:24
lib$es6$promise$$internal$$invokeCallback@http://localhost:3000/node_modules/angular2/bundles/angular2-polyfills.js:1523:52
lib$es6$promise$$internal$$publish@http://localhost:3000/node_modules/angular2/bundles/angular2-polyfills.js:1494:52
http://localhost:3000/node_modules/angular2/bundles/angular2-polyfills.js:243:7
microtask@http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:5751:19
run@http://localhost:3000/node_modules/angular2/bundles/angular2-polyfills.js:138:22
http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:5719:37
zoneBoundFn@http://localhost:3000/node_modules/angular2/bundles/angular2-polyfills.js:111:22
lib$es6$promise$asap$$flush@http://localhost:3000/node_modules/angular2/bundles/angular2-polyfills.js:1305:17
promiseReactionJob@[native code]
```

**Comment by wesleycho** [comment] 2015-12-20 13:48
What looks like is happening is that `Intl.NumberFormat` is never implemented - the stack trace points to https://github.com/angular/angular/blob/79472b77ca3c79475330312353b0d93edfdd07a5/modules/angular2/src/facade/intl.ts#L70 as the culprit.

This seems to also suggest that https://github.com/angular/angular/blob/79472b77ca3c79475330312353b0d93edfdd07a5/modules/angular2/src/facade/intl.ts#L143 is also a problem too.

It could be a use issue, as I'd guess that the intention is that the user implements the interface and then that is consumed, but perhaps users should be able to provide the implementation to the method to NumberFormatter and DateFormatter.

**Comment by mlaval** [comment] 2015-12-20 15:40
This s a known issue, see #3333.
AFAIK, @vicb is working/will work on a solution which doesn't rely on the Internationalization API.

**Comment by pkozlowski-opensource** [comment] 2016-01-28 09:40
Duplicate of #3333

**Closed by pkozlowski-opensource** 2016-01-28 09:40 UTC
