### ISSUE TITLE
MockConnection doesn't accurately portray a real connection

### ISSUE THREAD

**Issue by jacobwindsor** [angular/angular#13690] opened 2016-12-28 16:33 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
`MockConnection` isn't consistent with a real connection in its error handling. The real connection checks the response status and if it is okay. If the status is within 200 and 299 then it calls next on the observable, otherwise error. [MockRespond always calls next](https://github.com/angular/angular/blob/master/modules/%40angular/http/testing/mock_backend.ts#L63). This means you have to explicitly check the status code in unit tests and call [MockError](https://github.com/angular/angular/blob/master/modules/%40angular/http/testing/mock_backend.ts#L63)

**Expected behavior**
MockRespond would fire an error if the response status is not okay. Therefore, I cannot see much need for MockError except if one requires to test the error handling method without creating a mock HTTP method maybe.

**Minimal reproduction of the problem with instructions**
Not sure this is 100% neccesary, will do if so. See [this SO question](http://stackoverflow.com/questions/41365022/angular-2-unit-testing-observable-errors-http?noredirect=1#comment69932655_41365022) for more info.

**What is the motivation / use case for changing the behavior?**
Better portrayal of a real HTTP connection in unit tests

**Please tell us about your environment:**
Ubuntu 15.0, Webstorm, @angular/http version 2.4.1

* **Angular version:** 2.0.X
2.4.1

* **Browser:** 
all
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 2.1.4

**Comment by devoto13** [comment] 2016-12-28 23:37
Possibly duplicate of #12857.

**Comment by alxhub** [comment] 2017-04-01 00:41
Closing as a duplicate of #12857 (which will be fixed).

**Closed by alxhub** 2017-04-01 00:41 UTC
Labels: comp: http, severity3: broken
