### ISSUE TITLE
Custom decorators not working using AoT

### ISSUE THREAD

**Issue by zehavibarak** [angular/angular#41962] opened 2021-05-06 12:09 UTC
# Bug Report

### Affected Package

The issue is caused by package @angular/cli

### Is this a regression?

no

### Description

Custom component decorator ignored on AoT.

## Minimal Reproduction

https://stackblitz.com/edit/angular-ivy-mupixg?file=src/app/app.component.ts

## Exception or Error

Expected to have 1 message on reproduction, receives 0 on build prod with aot true.

## Your Environment

**Angular Version:**
<pre><code>
ngular CLI: 11.2.12
Node: 15.5.0
OS: win32 x64

Angular: 11.2.13
... animations, common, compiler, compiler-cli, core, elements
... forms, language-service, platform-browser
... platform-browser-dynamic, platform-server, router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1102.12
@angular-devkit/build-angular      0.1102.12
@angular-devkit/build-webpack      0.1102.12
@angular-devkit/core               11.2.12
@angular-devkit/schematics         11.2.12
@angular/cdk                       11.2.12
@angular/cli                       11.2.12
@angular/flex-layout               11.0.0-beta.33
@angular/material                  11.2.12
@angular/material-moment-adapter   11.2.12
@schematics/angular                11.2.12
@schematics/update                 0.1102.12
ng-packagr                         11.2.4
rxjs                               6.6.7
typescript                         4.1.5
</code></pre>

**Comment by alan-agius4** [comment] 2021-05-06 12:52
I'm sorry, but we can't reproduce the problem following the instructions you provided.

![image](https://user-images.githubusercontent.com/17563226/117301161-a3a9f600-ae7a-11eb-9f8a-57e3a7647c02.png)

**Comment by zehavibarak** [comment] 2021-05-06 14:31
This works localy. However, deploying it to Azure it does not. Azure manipulate the code in vendor.js.

Looking at the source code, I can find my decorator const:
```js
        const dWe = {};
        let uWe = (()=>{
            class e {
                constructor() {
                }
            }
        }
        )();
```
However, it is not in use anywhere.

**Comment by alxhub** [comment] 2021-05-06 20:13
I'm going to close this issue, as it's not actionable for us - in a normal Angular build, the decorator works as expected.

If Azure is modifying the deployed application in a way that breaks some if its functionality, you may need to open an issue with them to figure out why. Alternatively, if this does indeed turn out to be an Angular bug and you can provide a reproduction that doesn't require deploying to Azure, feel free to open a new issue.

**Closed by alxhub** 2021-05-06 20:13 UTC

**Comment by zehavibarak** [comment] 2021-05-06 22:57
This is an **Angular cli issue**. It has to do with webpack/terser tree shaking Angular does when `optimization` flag is true. This is a BUG.

**Comment by zehavibarak** [comment] 2021-05-07 02:35
> I'm going to close this issue, as it's not actionable for us - in a normal Angular build, the decorator works as expected.
> 
> If Azure is modifying the deployed application in a way that breaks some if its functionality, you may need to open an issue with them to figure out why. Alternatively, if this does indeed turn out to be an Angular bug and you can provide a reproduction that doesn't require deploying to Azure, feel free to open a new issue.

I ask you reopen this issue, as it is clearly a bug in angular-cli package which process the optimization. If you do not know how to procure this, please tag someone who might have a know-how of the code.
