### ISSUE TITLE
Language service.  Error checking updates only when reopening template

### ISSUE THREAD

**Issue by Yerkon** [angular/angular#22236] opened 2018-02-15 06:17 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

* We have component from 'B' module(exported), which we import it into modula 'A' by importing his module.
* In module 'A', we have component 'CA' which used component 'B' in it's template.  Ok
* In module 'A', in import prop **comment** module 'B'. Template of 'CA' component is opened at the same time. Service worker doesn't throw error; 
* Close the 'CA' template in editor and open it again(Reopen), then error throws. 
* The same case when we again **uncomment**  module 'B' from import array prop in module 'A'. In editor 'CA' template is staying opened. Error still staying.  To make error dissappear, need to close 'CA' template and open it again. 

## Expected behavior

Update Language service error analyzer smarter. Not only when reopening component template. If it will affect to User experience as lagging the editor, current behavior will be sufficient. But I hope it can be realizable  

## Environment

<pre><code>
Angular version: 5.2.4
Language-service: 5.2.4

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by JoostK** [comment] 2021-05-14 11:40
I can't reproduce this with the Ivy language service, so I'll go ahead and close this. If this continues to be a problem for someone, please open a new issue.

**Closed by JoostK** 2021-05-14 11:40 UTC
Labels: P3, comp: language-service, freq3: high, type: bug/fix
