### ISSUE TITLE
Service worker is not been registered DOMException

### ISSUE THREAD

**Issue by alexonozor** [angular/angular#47049] opened 2022-08-05 11:56 UTC
I keep getting this error using PWA service worker.

```
Service worker registration failed with: DOMException: Failed to register a ServiceWorker for scope ('http://localhost:8080/ngsw-worker.js') Operation has been aborted

```

</code>
   ng add @angular/pwa@13
</code>

App Module
```


@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    AppRoutingModule,
    BrowserAnimationsModule,
    HttpClientModule,
    RouterModule,
    ServiceWorkerModule.register('/ngsw-worker.js', { enabled: true }),
    
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

***ngsw-config.json***
```
{
  "$schema": "./node_modules/@angular/service-worker/config/schema.json",
  "index": "/index.html",
  "assetGroups": [
    {
      "name": "shopbot",
      "installMode": "prefetch",
      "resources": {
        "files": [
          "/favicon.ico",
          "/index.html",
          "/manifest.webmanifest",
          "/*.css",
          "/*.js"
        ]
      }
    },
    {
      "name": "assets",
      "installMode": "lazy",
      "updateMode": "prefetch",
      "resources": {
        "files": [
          "/assets/**",
          "/*.(svg|cur|jpg|jpeg|png|apng|webp|avif|gif|otf|ttf|woff|woff2)"
        ]
      }
    }
  ]
}
```

*package.json*

```
{
  "name": "shopbot",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "watch": "ng build --watch --configuration development",
    "test": "ng test"
  },
  "private": true,
  "dependencies": {
    "@agm/core": "^3.0.0-beta.0",
    "@angular-material-extensions/google-maps-autocomplete": "^6.2.2",
    "@angular/animations": "~13.1.0",
    "@angular/cdk": "^13.1.3",
    "@angular/common": "~13.1.0",
    "@angular/compiler": "~13.1.0",
    "@angular/core": "~13.1.0",
    "@angular/flex-layout": "^13.0.0-beta.36",
    "@angular/forms": "~13.1.0",
    "@angular/material": "^13.1.3",
    "@angular/platform-browser": "~13.1.0",
    "@angular/platform-browser-dynamic": "~13.1.0",
    "@angular/router": "~13.1.0",
    "@angular/service-worker": "~13.1.0",
    "@auth0/angular-jwt": "^5.0.2",
    "@google/maps": "^1.1.3",
    "angular-jwt": "^0.1.11",
    "crypto-js": "^4.1.1",
    "lodash": "^4.17.21",
    "moment": "^2.29.1",
    "moment-range": "^4.0.2",
    "ngx-material-timepicker": "^5.5.3",
    "rxjs": "~7.4.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~13.1.2",
    "@angular/cli": "~13.1.2",
    "@angular/compiler-cli": "~13.1.0",
    "@types/google.maps": "^3.47.3",
    "@types/googlemaps": "^3.39.13",
    "@types/jasmine": "~3.10.0",
    "@types/node": "^12.11.1",
    "jasmine-core": "~3.10.0",
    "karma": "~6.3.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.1.0",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "~1.7.0",
    "typescript": "~4.5.2"
  }
}

```

**Comment by alxhub** [comment] 2022-08-05 20:42
Hi @alexonozor,

Can you share a Github repo with reproduction instructions which demonstrates this problem? It's unclear by your description if there are any other changes in the application, how you're serving the app, etc.

**Comment by alexonozor** [comment] 2022-08-07 13:24
> Hi @alexonozor,
> 
> Can you share a Github repo with reproduction instructions which demonstrates this problem? It's unclear by your description if there are any other changes in the application, how you're serving the app, etc.

@alxhub Thanks for your reply.
I am serving the app with the `http-server dist/shopbot` after `ng build` please find the link to the repo thanks in advance.

[](https://github.com/alexonozor/shopbot)

**Comment by gkalpak** [comment] 2022-08-17 09:35
I tried out the project you shared and it works fine for me.

This DOMException is usually caused by a browser configuration that prevents the SW from being registered. For example, you might have disabled persistent storage (or the storage might be full) or something similar.

I am going to close this, since there is no indication this is an issue with Angular, but feel free to continue the discussion below.

**Closed by gkalpak** 2022-08-17 09:35 UTC
Labels: needs reproduction, comp: service-worker, bug
