### ISSUE TITLE
Style tags in the DOM are not cleaned up after each test run.

### ISSUE THREAD

**Issue by Zshuff03** [angular/angular#35693] opened 2020-02-26 20:23 UTC
# 🐞 bug report

### Affected Package
Base project created by an `ng new app-name`

### Is this a regression?
Nope

### Description
Component style tags are not getting cleaned up after each test run, causing a major slow down on larger projects.

## 🔬 Minimal Reproduction
https://github.com/Zshuff03/style-tag-cleanup
Clone the repo, run the tests. It will console log the total number of style tags each test.
You can also run the tests headed, click debug, and search for style tags in the chrome inspector.

## 🌍  Your Environment

**Angular Version:**
latest: 9.0.3

**Anything else relevant?**

**Comment by jelbourn** [comment] 2020-10-19 21:03
Duplicate of #31834

**Closed by jelbourn** 2020-10-19 21:03 UTC
Labels: comp: core, comp: testing, core: stylesheets
