### ISSUE TITLE
data-target attribute on a tag being duplicated 

### ISSUE THREAD

**Issue by michael-letcher** [angular/angular#24726] opened 2018-07-02 05:44 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Adding `data-target` to an a tag will have angular produce two attributes
`data-target` & `target` meaning the link will open in a new tab.

## Expected behavior

I would expect that there is not extra attribute called `target` affecting the links behaviour.

## Minimal reproduction of the problem with instructions
This
`<a *ngIf="!link.disabled"  role="button" routerLink="/{{link.url}}" id="{{link.id}}" data-toggle="collapse" data-target=".navbar-collapse.in">{{link.name}}</a>`

would compile to 
`<a _ngcontent-c1="" data-target=".navbar-collapse.in" data-toggle="collapse" ng-reflect-target=".navbar-collapse.in" ng-reflect-router-link="/home" id="navLinkHome" target=".navbar-collapse.in" href="/home" class="ng-star-inserted">Home</a>`

As you can see above there is now an unwanted target attribute.

To fix this I had to change the declaration to be `[attr.data-target]`
`<a *ngIf="!link.disabled" role="button" routerLink="/{{link.url}}" id="{{link.id}}" data-toggle="collapse" [attr.data-target]="'.navbar-collapse.in'">{{link.name}}</a>`

which compiles to

`<a _ngcontent-c1="" data-toggle="collapse" role="button" ng-reflect-router-link="/home" id="navLinkHome" data-target=".navbar-collapse.in" href="/home" class="ng-star-inserted">Home</a>` 

Was following this fix for a Bootstrap 3.3.7 navbar
https://stackoverflow.com/a/21797534/2536454

## Environment

<pre><code>
Angular version: 6.0.2

Browser:
- [X] Chrome (desktop) version 67.0.3396.87
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.11.1  
- Platform: Mac

**Comment by trotyl** [comment] 2018-07-02 07:21
Duplicate of https://github.com/angular/angular/issues/19054

**Comment by michael-letcher** [comment] 2018-07-03 01:58
https://github.com/angular/angular/issues/19054#issuecomment-327253870
"We should probably revisit this but for now you can use explicit attribute binding"

Is there a plan for this?

Workaround still works, if there is no plans. You can close this ticket.

**Comment by mhevery** [comment] 2018-07-12 23:00
Duplicate of #19054

**Closed by mhevery** 2018-07-12 23:00 UTC
