### ISSUE TITLE
strictNullChecks with RequestOptions not passing

### ISSUE THREAD

**Issue by nascosto** [angular/angular#16663] opened 2017-05-09 19:38 UTC
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
With strictNullChecks turned on, I get this error:
```
ERROR in <xxx>\node_modules\@angular\http\src\base_request_options.d.ts
(63,18): error TS2459: Type 'RequestOptionsArgs | undefined' has no property 'method' and no string index signature.
```
It has the same error for method, headers, body, url, search, params, withCredentials, and responseType.

**Expected behavior**
The build passes without errors.

**Minimal reproduction of the problem with instructions**
```
let options: RequestOptionsArgs = { body: {} };
this.http.delete(url, new RequestOptions(options));
```

**What is the motivation / use case for changing the behavior?**
One of 4.1's features is passing strictNullChecks

**Please tell us about your environment:**
Typescript 2.3.2
tsconfig.json
```
 "compilerOptions": {
		"alwaysStrict": true,
		"emitDecoratorMetadata": true,
		"experimentalDecorators": true,
		"forceConsistentCasingInFileNames": true,
		"lib": [
			"es2015",
			"dom"
		],
		"module": "commonjs",
		"moduleResolution": "node",
		"noImplicitReturns": true,
		"sourceMap": true,
		"strictNullChecks": true,
		"suppressImplicitAnyIndexErrors": true,
		"target": "es5"
	}
```
* **Angular version:** 4.1.1
 
* **Language:** TypeScript 2.3.2

**Comment by jasonaden** [comment] 2017-05-10 18:09
@mhevery Looks like we don't have strictNullChecks enabled in HTTP: https://github.com/angular/angular/blob/master/packages/http/tsconfig-build.json

**Comment by mhevery** [comment] 2017-05-11 22:16
@jasonaden Yes, we should have it there, but there is a seperate place where we compile the whole world with "strictNullChecks": true so that is not the issue.

**Comment by mhevery** [comment] 2017-05-11 22:21
@nascosto I am unable to reproduce this issue. Can you provide more detailed instructions?

**Comment by Owain94** [comment] 2017-05-12 14:22
@mhevery 

This does the trick

```
constructor(private http: Http) {
  const headers = new Headers();
  headers.append('Content-Type', 'application/json');
  this.options = new RequestOptions({ headers: headers });
}
```

here are the errors

    ERROR in /Users/Owain/angular/angular-webshop/node_modules/@angular/http/src/base_request_options.d.ts (63,18): Type 'RequestOptionsArgs | undefined' has no property 'method' and no string index signature.
    ERROR in /Users/Owain/angular/angular-webshop/node_modules/@angular/http/src/base_request_options.d.ts (63,26): Type 'RequestOptionsArgs | undefined' has no property 'headers' and no string index signature.
    ERROR in /Users/Owain/angular/angular-webshop/node_modules/@angular/http/src/base_request_options.d.ts (63,35): Type 'RequestOptionsArgs | undefined' has no property 'body' and no string index signature.
    ERROR in /Users/Owain/angular/angular-webshop/node_modules/@angular/http/src/base_request_options.d.ts (63,41): Type 'RequestOptionsArgs | undefined' has no property 'url' and no string index signature.
    ERROR in /Users/Owain/angular/angular-webshop/node_modules/@angular/http/src/base_request_options.d.ts (63,46): Type 'RequestOptionsArgs | undefined' has no property 'search' and no string index signature.
    ERROR in /Users/Owain/angular/angular-webshop/node_modules/@angular/http/src/base_request_options.d.ts (63,54): Type 'RequestOptionsArgs | undefined' has no property 'params' and no string index signature.
    ERROR in /Users/Owain/angular/angular-webshop/node_modules/@angular/http/src/base_request_options.d.ts (63,62): Type 'RequestOptionsArgs | undefined' has no property 'withCredentials' and no string index signature.
    ERROR in /Users/Owain/angular/angular-webshop/node_modules/@angular/http/src/base_request_options.d.ts (63,79): Type 'RequestOptionsArgs | undefined' has no property 'responseType' and no string index signature.

**Comment by mattma** [comment] 2017-05-17 03:34
@ericmartinezr Is there a timeline when this fix can be released? It is a blocker to use with `strict = true` config in the *TypeScript 2.3.0+*

**Comment by nascosto** [comment] 2017-05-17 03:56
@mattma They do weekly point releases. The last one was on the 10th. It should be any day now.

**Comment by Owain94** [comment] 2017-05-18 12:05
@mattma any luck?
@mhevery

I'm still getting these errors with angular 4.1.3

```
ERROR in <xxx>/node_modules/@angular/http/src/base_request_options.d.ts (63,18): Type 'RequestOptionsArgs | undefined' has no property 'method' and no string index signature.
ERROR in <xxx>/node_modules/@angular/http/src/base_request_options.d.ts (63,26): Type 'RequestOptionsArgs | undefined' has no property 'headers' and no string index signature.
ERROR in <xxx>/node_modules/@angular/http/src/base_request_options.d.ts (63,35): Type 'RequestOptionsArgs | undefined' has no property 'body' and no string index signature.
ERROR in <xxx>/node_modules/@angular/http/src/base_request_options.d.ts (63,41): Type 'RequestOptionsArgs | undefined' has no property 'url' and no string index signature.
ERROR in <xxx>/node_modules/@angular/http/src/base_request_options.d.ts (63,46): Type 'RequestOptionsArgs | undefined' has no property 'search' and no string index signature.
ERROR in <xxx>/node_modules/@angular/http/src/base_request_options.d.ts (63,54): Type 'RequestOptionsArgs | undefined' has no property 'params' and no string index signature.
ERROR in <xxx>/node_modules/@angular/http/src/base_request_options.d.ts (63,62): Type 'RequestOptionsArgs | undefined' has no property 'withCredentials' and no string index signature.
ERROR in <xxx>/node_modules/@angular/http/src/base_request_options.d.ts (63,79): Type 'RequestOptionsArgs | undefined' has no property 'responseType' and no string index signature.
```

**Comment by mattma** [comment] 2017-05-18 22:45
@Owain94 Tried with latest release **4.1.3**, it is still error out in `ng build --prod --aot`, and it works in `ng serve`. 

By reading [4.1.3 changelog](https://github.com/angular/angular/compare/4.1.3...master), i do not see the commit of "http aot" fix. This release does not come with **beta release**, that seems weird.

**Comment by Owain94** [comment] 2017-05-18 23:08
@mattma @mhevery In this commit https://github.com/angular/angular/pull/16738 the issue is closed but the issue isn't fixed yet. Can this issue be reopened?

**Comment by mhevery** [comment] 2017-05-19 03:51
@alxhub could you have a look?

**Comment by Delagen** [comment] 2017-05-19 13:40
The same with angular/core ViewChild decorator
```
TS2459: Type '{ read?: any; } | undefined' has no property 'read' and no string index signature.
```

**Comment by Delagen** [comment] 2017-05-22 06:19
with updated 4.2.0-rc.0
```
TS2459: Type '{ onlySelf?: boolean | undefined; emitEvent?: boolean | undefined; } | undefined' has no property 'onlySelf' and no string index signature.
```
on definitions like
```
setValue(value: any, options?: {
        onlySelf?: boolean;
        emitEvent?: boolean;
        emitModelToViewChange?: boolean;
        emitViewToModelChange?: boolean;
    }): void;
```

**Comment by mattma** [comment] 2017-05-23 04:05
with updated 4.2.0-rc.0

Still seeing the same build error.

**Comment by mattma** [comment] 2017-05-30 23:37
Updated to `"@angular/http": "4.2.0-rc.1",`, still see the same build error. Any timeline when this bug will be fixed? 

```
...
node_modules/@angular/http/src/base_request_options.d.ts (63,54): Type 'RequestOptionsArgs | undefined' has no property 'params' and no string index signature.
...
```

**Comment by fbascheper** [comment] 2017-06-06 11:26
We're getting the same error with 4.2.0-rc.2 as well. 
This is getting increasingly frustrating, as this inhibits the use of strictNullChecks with AOT whenever a special Http configuration using RequestOptions is required. 

Can we provide any assistance to resolve this issue?

**Comment by jneveux** [comment] 2017-06-07 08:03
@alxhub would it be possible to post the modified lines for the definition files line 63 `base_request_options.d.ts` and line 46 `base_response_options.d.ts`.

**Comment by Martin-Wegner** [comment] 2017-06-09 09:28
4.2.0 is out and this issue breaks the whole AOT build.

You can reproduce this with:

```
ng new myApp
importing HttpModule in app.module.ts
enable strictNullChecks in tsconfig.json
ng build --aot
```

**Comment by andrei-ivanov** [comment] 2017-06-09 09:52
With 4.2.0:
_base_request_options.d.ts:63_: `constructor({method, headers, body, url, search, params, withCredentials, responseType}?: RequestOptionsArgs);`
_base_response_options.d.ts:46_: `constructor({body, status, headers, statusText, type, url}?: ResponseOptionsArgs);`

**Closed** 2017-06-09 21:34 UTC
Labels: comp: http

**Comment by Delagen** [comment] 2017-06-11 19:37
The same with
AbstractControl in angular/forms
```
TS2459: Type '{ onlySelf?: boolean | undefined; } | undefined' has no property 'onlySelf' and no string index signature.
TS2459: Type '{ onlySelf?: boolean | undefined; emitEvent?: boolean | undefined; } | undefined' has no property 'onlySelf' and no string index signature.
```

**Comment by mhevery** [comment] 2017-06-12 01:12
@Delagen Please file a separate bug. Once the bug is closed we almost never look at it.

**Comment by Yevhensh** [comment] 2017-06-26 09:07
I can't refer to options?: RequestOptionsArgs (its undefined) in my custom http implementation even when i pass RequestOptions with my request and one header.
