### ISSUE TITLE
NG0912: Component ID generation collision detected for same component

### ISSUE THREAD

**Issue by cca-developer** [angular/angular#53592] opened 2023-12-15 20:55 UTC
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

After upgrading to Angular 17, I'm now seeing lots of warnings like this:
```
NG0912: Component ID generation collision detected. Components 'PicklistComponent' and 'PicklistComponent' with selector 'picklist' generated the same component ID.
```
I only have one component of that name and the warning is listing it twice.  How am I supposed to resolve that?

### Please provide the exception or error you saw

```true
NG0912: Component ID generation collision detected. Components 'PicklistComponent' and 'PicklistComponent' with selector 'picklist' generated the same component ID. To fix this, you can change the selector of one of those components or add an extra host attribute to force a different ID. Find more at https://angular.io/errors/NG0912
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.0.7
Node: 20.10.0
Package Manager: npm 10.2.3
OS: win32 x64

Angular: 17.0.7
... cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.7
@angular-devkit/build-angular   17.0.7
@angular-devkit/core            17.0.7
@angular-devkit/schematics      17.0.7
@schematics/angular             17.0.7
ng-packagr                      17.0.2
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.2
```

**Comment by JoostK** [comment] 2023-12-15 23:38
Duplicate of #50158.

---

> I only have one component of that name and the warning is listing it twice. How am I supposed to resolve that?

This may occur in HMR scenarios, or if the component is part of a library it may be duplicated if there's multiple versions of the library being loaded.

**Closed by JoostK** 2023-12-15 23:38 UTC

**Comment by cca-developer** [comment] 2023-12-18 13:40
This does not seem like a duplicate of https://github.com/angular/angular/issues/50158.  In my case, there are selectors.  I am using the component as part of a library, but I'm seeing the problem in the demo app for that library, so I don't see how there could possibly be multiple versions of the library being loaded.  I suppose it could be due to HMR, although then it still seems like a bug that it would display warnings for something that is not actually a real problem.  Is there a way that I can disable HMR to test that theory?

**Comment by vityapro** [comment] 2024-01-05 16:39
Same issues in my project.
