### ISSUE TITLE
[Proposal] Allow referencing the whole TemplateRef context object from the template

### ISSUE THREAD

**Issue by lazarljubenovic** [angular/angular#39884] opened 2020-11-30 08:55 UTC
# 🚀 feature request

### Relevant Packages

This feature request is for `@angular/core` and `@angular/compiler`.

### Description

The object used as context for `TemplateRef` is not accessible from the template; only the values of its keys are. Therefore, it's not possible to

1. easily reference keys of a large object, or
2. pass the whole context to another template reference.

For example, consider the following context.

```ts
const context = { foo: 1, bar: 2, baz: 3, qux: 4 }
```

In order to just print all of these values, it's necessary to write the following template.

```html
                   <!-------------- verbose & error-prone --------------->
<ng-template #tpl1 let-foo="foo" let-bar="bar" let-baz="baz" let-qux="qux">
  {{ foo }}, {{ bar }}, {{ baz }}, {{ qux }}
</ng-template>
```

The list of `let-xxx="xxx"` will just keep increasing with the same mundane boilerplate code as the object grows. 

Furthermore, two such templates won't be easily composable, even though they accept the same kind of context.

```html
                   <!-------------- verbose & error-prone --------------->
<ng-template #tpl2 let-foo="foo" let-bar="bar" let-baz="baz" let-qux="qux">
  Elements: 
  <ng-template
    [ngTemplateOutlet]="tpl1"
    [ngTemplateOutletContext]="{ foo: foo, bar: bar, baz: baz, qux: qux }" 
  >
                               <!-------- verbose & error-prone -------->
</ng-template>
```

Apart from `{ foo: foo, bar: bar, baz: baz, qux: qux }` being equally verbose and error-prone as `let-foo="foo" let-bar="bar" let-baz="baz" let-qux="qux"` (especially since there's almost no type checking for these cases), this will create a new object for every CD cycle (more on that below).

### Describe the solution you'd like

A way to get a hold of the context object itself. Templates in the examples above could be rewritten as follows.

```html
                   <!-- <3 -->
<ng-template #tpl1 let-ctx="*">
  {{ ctx.foo }}, {{ ctx.bar }}, {{ ctx.baz }}, {{ ctx.qux }}
</ng-template>
```

```html
                   <!-- <3 -->
<ng-template #tpl2 let-ctx="*">
  Elements:
  <ng-template
    [ngTemplateOutlet]="tpl1"
    [ngTemplateOutletContext]="ctx"
  >
                            <!--<3-->
</ng-template>
```

The precise syntax doesn't have to be like this, but the `*` symbol should ring a bell from the namespaced import syntax `import * as context from 'context'`. I don't think there's issues about confusion with the microsyntax prefix (`*ngFor`, `*ngIf`) since the asterisk in case of `let-ctx="*"` doesn't come as a prefix, and it's placed in the spot where a variable name can otherwise come in.

An alternative syntax that comes to mind would be using `...` which rings the bell of the spread/rest operator, which is similar in nature to what this proposal tries to achieve.

```html
                   <!--  <3  -->
<ng-template #tpl1 let-ctx="...">
  {{ ctx.foo }}, {{ ctx.bar }}, {{ ctx.baz }}, {{ ctx.qux }}
</ng-template>
```

```html
                   <!--  <3  -->
<ng-template #tpl2 let-ctx="...">
  Elements:
  <ng-template
    [ngTemplateOutlet]="tpl1"
    [ngTemplateOutletContext]="ctx"
  >
</ng-template>
```

Ultimately, the syntax isn't the main point of this proposal and these are just examples. I'd love to see others' take on what looks easiest to write and read, and how to make the intent more intuitive based on existing ES and/or Angular constructs.

### Describe alternatives you've considered

Obviously, `$implicit` is the alternative. This _seems_ like a good solution:

```ts
const context = { $implicit: { foo: 1, bar: 2, baz: 3, qux: 4 } } // meh
```

```html
<ng-template #tpl1 let-ctx>
  {{ ctx.foo }}, {{ ctx.bar }}, {{ ctx.baz }}, {{ ctx.qux }}
</ng-template>

<ng-template
  [ngTemplateOutlet]="tpl1"
  [ngTemplateOutletContext]="context"
></ng-template>
```

The problem that arises now is that we've changed our model. If we have an array of `User` objects, now we need an array of `{ $implicit: User }` objects. Wrapping objects to an `$implicit` property is something that we'd have to do only because the view requires so. Changing our model to match the view is not how the whole separation of concerns and the model-view architecture is supposed to work (or at least we try to minimize that). The view should be able to adapt to the model, not the other way around.

Now, one way for the view to adopt to the model is, of course, the following.

```ts
const context = { foo: 1, bar: 2, baz: 3, qux: 4 } // good
```

```html
<ng-template #tpl1 let-ctx>
  {{ ctx.foo }}, {{ ctx.bar }}, {{ ctx.baz }}, {{ ctx.qux }}
</ng-template>

<ng-template
  [ngTemplateOutlet]="tpl1"
  [ngTemplateOutletContext]="{ $implicit: context }"
></ng-template>
                             <!-- mixed feelings -->
```

The issue is that this creates a new object `{ $implicit: context }` in every CD cycle. 

Note that [`NgTemplateOutlet` of `@angular/common` itself was changed to check for equality-by-shape instead of equality-by-reference](https://github.com/angular/angular/commit/685cc26ab2dc7f8d836ec932a43d45edfa0f8e97) because it was such a common use-case to create the object inline in the template. That idea introduces more runtime checks in order to allow this common style.

While the solution works, I'm not sure it was a step in the right direction (I'd like to hear what the author of the commit, @pkozlowski-opensource thinks about it). Apart from introducing the runtime check, I feel like it attempts to patch the problem instead of addressing the root cause: the actual _need_ to create objects inline in the template as opposed to just using them from the code -- which is what this proposal is about. Either way, this proposal is not in conflict with the established runtime check-by-shape, so it's not a breaking change; users who worry about performance can create their own variant `NgTemplateOutlet` which only does a simple check by reference.

----

This mostly seems like job for the compiler, as I don't think it introduces any special changes to the core -- that object is already passed around unchanged, and this proposal “only” allows grabbing the object itself instead of just its keys via `let-localName`.

As usual, “only” is possibly a rabbit hole of issues. I haven't tried to implement this yet, but I will post here if I manage to get a prototype working for the `let-ctx="*"` syntax (it _looks_ as if it's just a matter of treating `*` as a special case and then passing in `context` instead of `context['*']` for it).

**Comment by Airblader** [comment] 2020-11-30 12:08
I know you mentioned the exact syntax isn't the core of this issue, but I just wanted to comment on the fact that both proposed syntax versions are "backwards": in `let-x="y"`, x is the name of the local variable and y the name of they key in the context, so it'd rather have to be something like `let-ctx="*"` instead.

Also, the syntax needs to keep in mind HTML-compatibility (since Angular's template syntax does still hold on to that).

**Comment by ulrikwalter** [comment] 2020-11-30 21:44
Maybe:
(context, ctx, c: the name can be anything)

```js
const context = { foo: 1, bar: 2, baz: 3, qux: 4 }
```

```html
<ng-template #tpl1 let-c="ctx">
  {{ c.foo }}, {{ c.bar }}, {{ c.baz }}, {{ c.qux }}
</ng-template>

<ng-template
  [ngTemplateOutlet]="tpl1"
  [ngTemplateOutletContext]="{ctx: context}"
></ng-template>

```

**Comment by lazarljubenovic** [comment] 2020-12-01 05:31
@Airblader Thanks for the review; I've updated the issue now. 

@ulrikwalter That looks like the second code example from “Describe alternatives you've considered”. It will create a new object `{ ctx: context }` on every CD cycle.

**Comment by pkozlowski-opensource** [comment] 2021-07-23 13:33
I believe that this is a duplicate of #22323 - let's centralise the discussion in one place.

**Closed by pkozlowski-opensource** 2021-07-23 13:33 UTC
Labels: comp: core, core: ng-template and *microsyntax, feature, insufficient votes, votes required

**Comment by lazarljubenovic** [comment] 2021-07-23 15:08
And yet another reason why the issue voting system makes no sense 😄
