### ISSUE TITLE
parseUrl does not work for absolute url

### ISSUE THREAD

**Issue by cheng93** [angular/angular#42619] opened 2021-06-22 10:35 UTC
# Bug Report

### Affected Package

 The issue is caused by package @angular/router

### Is this a regression?

 Unknown

### Description
 router.parseUrl does not work for absolute url

* The url tree only contains `https:`
* No query params

## Minimal Reproduction

https://stackblitz.com/edit/angular-ivy-nuuott?file=src/app/app.component.ts

## Exception or Error
<pre><code>

</code></pre>

## Your Environment

**Angular Version:**
<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by atscott** [comment] 2021-06-28 22:35
The `Router` APIs are intended to be used with _paths_ internal to the Angular app. The `navigateByUrl` and `parseUrl` names are unfortunate because they really do not deal with "URLs" as defined by the spec. That said, the methods themselves behave as intended despite the misleading names. Unfortunately the cost to migrate the names of the methods is far greater than the benefit of fixing technical incorrectness of them.

Closing as working as intended.

**Closed by atscott** 2021-06-28 22:35 UTC
Labels: comp: router, type: bug/fix
