### ISSUE TITLE
Unexpected behaviour of the form-fields when using 2 for-loops with nested arrays

### ISSUE THREAD

**Issue by guna-neutrinos** [angular/angular#51098] opened 2023-07-19 14:55 UTC
### Which @angular/* package(s) are the source of the bug?

Common

### Is this a regression?

No

### Description

In the code that I have added below , if there are two form fields with the same values , if we do the changes in the first form field ,the second form field that has the same value gets updated along with the first . In this case only template is getting changed not the model .

#### Steps:
Note: Each input's model value is displayed next to each of the corresponding input field.
1. Copy value from the first input in the second section(after "Below template has bug")
2. Paste the value in the second field in the same section
3. change the value of the first input field by typing.
4. Now, the second input field value is changed, but the model bound to it (that is displayed next to each field) remains unchanged

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-vfmyf5?file=src%2Fmain.ts

https://github.com/angular/angular/assets/91047250/d4f4c7fe-84a8-4b1f-bc2c-4e404285c43b

### Please provide the environment you discovered this bug in (run `ng version`)

```true
I have attached a stackblitz link
```

**Comment by stagefright5** [comment] 2023-07-19 15:35
Wow. This seems like a notorious bug. I tried to debug this issue myself, but no success. Hopefully it is a bug in your code and not in angular. 🤞🏼

**Comment by paul-thomas0** [comment] 2023-07-19 15:49
> https://stackblitz.com/edit/angular-vfmyf5?file=src%2Fmain.ts

Something similar was happening on a project I was working on as well. But, we were using an older version of Angular (13.x.x), we did the same thing as well.

Something to with index tracking vs object in Angular.

**Comment by JoostK** [comment] 2023-07-19 17:44
Closing as a duplicate of #45647.

**Closed by JoostK** 2023-07-19 17:44 UTC
Labels: area: forms

**Comment by stagefright5** [comment] 2023-07-19 17:46
> Closing as a duplicate of #45647.

Okay, but, is there any workaround for this, atleast?

**Comment by stagefright5** [comment] 2023-07-19 17:52
This seems like it should fix this issue as mentioned in this comment
https://github.com/angular/angular/issues/45647#issuecomment-1100913387

```typescript
const trackByIdentityOrIndex =
    (index: number, item: any) => {
      if (typeof item === 'object') return item;
      return index;
    }
```
