### ISSUE TITLE
[MS Edge] Improve error message for syntax errors in HostBinding

### ISSUE THREAD

**Issue by Tragetaschen** [angular/angular#9998] opened 2016-07-12 14:03 UTC
**I'm submitting a ...**  (check one with "x")

```
[ ] bug report
[x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
A syntax error in a `@HostBinding` gives a `InvalidCharacterError` for an "inline template" with no indication where it's coming from.

**Expected/desired behavior**
The error message should mention, which inline template is meant.

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

http://plnkr.co/edit/SMtHq6Hr4nSZE4EahdJ6?p=preview

**What is the expected behavior?**
Still asking twice?

**What is the motivation / use case for changing the behavior?**
To have better error messages

**Please tell us about your environment:**
- **Angular version:** 2.0.0-rc.4
- **Browser:** [<s>all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView </s>]  Edge
- **Language:** [all | TypeScript X.X | ES6/7 | ES5 | Dart]

**Comment by Tragetaschen** [comment] 2016-07-12 18:12
![image](https://cloud.githubusercontent.com/assets/1947968/16778138/dcda7dba-486c-11e6-9480-380bb5ca248c.png)

Uhm, no, it's not :-/

**Comment by vicb** [comment] 2016-07-12 18:15
> Uhm, no, it's not :-/

It is in Chrome... please remember to specify the browser when creating an issue

**Comment by pkozlowski-opensource** [comment] 2016-07-12 18:21
@vicb this error comes directly from a browser, so is browser-specific. In this sense it is not Edge-specific  (just happens that Chrome has a better err message than Edge). It could be easily reproduced outside Angular by doing:

```javascript
var div = document.createElement('div');
div.setAttribute('[[class.my-class]]', 'foo');
```

We could / should look at the attribute names when collecting host bindings and provide better error message. Can have a look into this tomorrow.

**Comment by Tragetaschen** [comment] 2016-07-12 18:22
I just checked with Chrome and indeed, the error message is much, much (much) better.

When something bad happens with Angular in Edge, I'm always faced with this totally useless `Uncaught (in promise)` error and a `resolvePromise` stack trace from zone.js. I thought this was the way it is…

That's what you get from developing with the (still) weakest of the evergreen browsers.

**Comment by vicb** [comment] 2016-07-13 02:28
@pkozlowski-opensource it would be great, thanks !

**Comment by pavankjadda** [comment] 2021-06-02 06:16
I don't think this applies to MS Edge Chromium which Microsoft announced last year and also Edge Legacy browser is no longer supported by MicroSoft.

**Comment by AndrewKushnir** [comment] 2021-06-02 15:38
@pavankjadda thanks for the comment. Since IE is now deprecated this ticket looks obsolete, so I'm closing it. Thank you.

**Closed by AndrewKushnir** 2021-06-02 15:38 UTC
Labels: comp: core, core: host and host bindings, feature, hotlist: error messages, votes required
