### ISSUE TITLE
Automatic change detection broken after routing using Electron menu

### ISSUE THREAD

**Issue by pamtbaau** [angular/angular#13363] opened 2016-12-10 09:59 UTC
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
After routing between components via an Electron menu call, automatic change detection is broken after upgrading from Angular 2.1 to 2.3

**Expected behavior**
Continue to detect changes like in Angular 2.1

**Minimal reproduction of the problem with instructions**
See [git repository](https://github.com/pamtbaau/ng2-webpack-electron-menu-routing-failing-change-detection) and README

**Please tell us about your environment:**
Windows 10
VScode

* **Angular version:** 2.3.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome embedded in Electron 1.4.12
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript

**Comment by robwormald** [comment] 2016-12-11 12:49
Thanks for the repro. This is related to zone.js, rather than angular itself.

The basic issue is that events coming in from electron-land aren't patched by zone (like native browser APIs are), so angular drops out of its zone, and because the new component is created outside of the zone, we lose change detection.

I'm going to close this issue here and reopen over in zone.js - see https://github.com/angular/zone.js/issues/537

In the interim, you can work around this by wrapping the navigate call in a zone.run:
```ts
submenu: [
  { label: 'Page 1', click: () => this.zone.run(() => this.router.navigate(['/page1']))},
  { label: 'Page 2', click: () => this.zone.run(() => this.router.navigate(['/page2'])) },
],
```

I tested this in your repo and it works fine.

**Closed by robwormald** 2016-12-11 12:49 UTC
Labels: comp: core & compiler

**Comment by pamtbaau** [comment] 2016-12-11 12:55
@robwormald Thanks for the swift response and workaround. Opens the door for upgrade...

**Comment by JiaLiPassion** [comment] 2016-12-11 13:21
@pamtbaau 
I use your repository, update angular to 2.3 and zone.js to 0.7.2, can't reproduce, can you provide the package.json and a more detailed reproduce steps? thanks.
