### ISSUE TITLE
Disabled controls from FormGroup (part of component that implements ControlValueAccessor) are excluded by .getRawValue() on parent.

### ISSUE THREAD

**Issue by kvitozev** [angular/angular#28070] opened 2019-01-11 12:02 UTC
# 🐞 bug report

### Affected Package

This issue is caused by package `@angular/forms`

### Is this a regression?

N/A

### Description

Having a component that implements `ControlValueAccessor`, with internal `FormGroup` to maintain the state of custom form control. When any field, that's part of that `FormGroup` is disabled, the field isn't visible when calling `.getRawValue()` method in parent form (i.e. `.getRawValue() === .value`) . By specification, `getRawValue()` should return the raw object, including disabled fields.

## 🔬 Minimal Reproduction
Examine the output of `.value` and `.getRawValue()` when clicking enable/disable button on the nested form.

https://stackblitz.com/edit/angular-nested-reactive-form-jjgkef

## 🔥 Exception or Error

When given form control (part of `FormGroup`, that acts like custom form control) is disabled, the `.getRawValue()` should return the raw object with all fields, including disabled ones.

## 🌍  Your Environment

**Angular Version:**

Angular CLI: 1.7.0
Node: 10.14.1
OS: win32 x64
Angular: 5.2.4
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic
... platform-server, router

@angular/cdk: 5.2.5
@angular/cli: 1.7.0
@angular/flex-layout: 5.0.0-beta.14
@angular/material-moment-adapter: 6.3.0
@angular/material: 5.2.5
@angular-devkit/build-optimizer: 0.3.1
@angular-devkit/core: 0.4.6
@angular-devkit/schematics: 0.3.1
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.0
@schematics/angular: 0.3.1
@schematics/package-update: 0.3.1
typescript: 2.4.2
webpack: 3.11.0

**Comment by kvitozev** [comment] 2019-01-11 14:59
In the source code of `getRawValue()`, I can see the following:

```
  getRawValue(): any {
    return this._reduceChildren(
        {}, (acc: {[k: string]: AbstractControl}, control: AbstractControl, name: string) => {
          acc[name] = control instanceof FormControl ? control.value : (<any>control).getRawValue();
          return acc;
        });
  }
```

So, whenever we have custom form control (its instance of `FormControl`, correct?) Angular is retrieving `.value` property. 

Is there any workaround? Can we consider this as issue?

**Comment by alan-mroczek** [comment] 2019-01-29 05:53
Hi @kvitozev. This isn't an issue with @angular/forms package itself. It's caused because of the way your code works. In your control in `registerOnChange` you're passing directly value from subscription to function that reads changes. That subscription doesn't have information of every control state as you disable it beforehand. You can verify that by [watching in console](https://stackblitz.com/edit/angular-nested-reactive-form-cchurr?file=src/app/details-fields/details-fields.component.ts) my `console.log`. To make it work the way you want to, you would need to pass whole form state including disabled controls `fn(this.formGroup.getRawValue())`.

**Comment by kara** [comment] 2019-03-05 23:24
@alan-mroczek Thanks for commenting; I hadn't caught that either. Looks like this is working as intended, so closing.

**Closed by kara** 2019-03-05 23:24 UTC
Labels: comp: forms, freq2: medium, hotlist: community-help, severity3: broken, type: bug/fix
