### ISSUE TITLE
Unmatched selector: ;400;500;600;700;800&amp;display=swap) due to import fonts in css

### ISSUE THREAD

**Issue by techyaura** [angular/angular#42243] opened 2021-05-23 03:00 UTC
Oh hi there!

I have recently upgrade an existing application to angular 12, after that  I am getting a warning shown in attached screenshot.
It's reproducing only on production build.

![image](https://user-images.githubusercontent.com/5227618/119246517-dd2f7080-bb9f-11eb-94d9-d3bebb20d10d.png)

# Bug Report

### Affected Package
![image](https://user-images.githubusercontent.com/5227618/119246534-03551080-bba0-11eb-9919-15aa8771678e.png)

### Is this a regression?

Did this behavior use to work in the previous version? 
Yes, the previous version in which this bug was not present.

### Description
Issue happening on production build only. Below is `angular.json` screenshot 
![image](https://user-images.githubusercontent.com/5227618/119246599-7199d300-bba0-11eb-8af0-d3deab64414a.png)

## Exception or Error
1 rules skipped due to selector errors:
 300;400;500;600;700;800&amp;display=swap); -> Unmatched selector: ;400;500;600;700;800&amp;display=swap);

**The below import in css causing the error**

![image](https://user-images.githubusercontent.com/5227618/119246664-f71d8300-bba0-11eb-84f5-40deab9e404a.png)

## Your Environment

**Angular Version:** v12.0

**Anything else relevant?**
Nodejs Version: `v12.22.1`

**Comment by petebacondarwin** [comment] 2021-05-23 06:00
Duplicate of https://github.com/angular/angular-cli/issues/20906

**Closed by petebacondarwin** 2021-05-23 06:00 UTC
