### ISSUE TITLE
Angular2 model-driven forms and prepopulated values

### ISSUE THREAD

**Issue by yusijs** [angular/angular#9716] opened 2016-06-30 10:37 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I have an app that I built for rc.1 that I'm now upgrading to rc.3, and the new forms module. I've been ripping my hair out beacuse of it, and decided to see if anyone had any ideas what I'm doing wrong.

Basically I'm building the form like this (fb is an instance of FormBuilder):

```
this.form = fb.group({
  client_id: ['Customer', Validators.compose([Validators.required, formValidators.mustBeNumber])],
  data_owner_id: ['Data Owner (if different from Customer)', formValidators.mustBeNumber],
  order_time: [new Date(), Validators.compose([formValidators.mustBeDate, Validators.required])]
})
```

And prepopulating with ngModel like this:

```
<form class="form"  [formGroup]="form" (ngSubmit)="submitJob(f)">
      <legend>{{title}}</legend>
      <div class="form-group">
        <label for="client_id">Client</label>
   <select (change)="clientHasChanged($event.target.value)" class="form-control" id="client_id" formControlName="client_id" [(ngModel)]='job.client_id'>
              <option value="" disabled selected>Customer</option>
              <option *ngFor="let client of clients" [ngValue]="client.client_id">{{client.client_id}} - {{client.client_id_name}}</option>
            </select>
```

This worked perfectly fine for rc.1 (outside of the renamed directives), but now I'm getting an error:

> browser_adapter.ts:74 EXCEPTION: Error in http://localhost:4200/app/+wih2/+job/job.component.html:6:129 
> ORIGINAL EXCEPTION: No value accessor for ''

Removing the ngModel removes the error, but I kinda need the data it provides, and I don't know of any other way to resolve this.

I'm using the new forms module, and yes I am bootstrapping with it:

`bootstrap(AppComponent, [disableDeprecatedForms(), provideForms(), HTTP_PROVIDERS, APP_ROUTER_PROVIDERS]);`

If this is just me missing something, I'll close this off right away, but it does seem like a bug, namely because it fails on the ngModel, but explicitly setting the value I request (job = new Job(); job.client_id = 1;) yields the same results. 

For the record, I tried updating the form directly with the values after getting my data from an api, but found no way of coherently both updating the value and the input without databinding:
this.form.value.client_id = this.job.client_id;
console.log(this.form.value); // This logs out the new value I set, but it still shows a blank input field. 

**Expected/desired behavior**

The input should update according to the ngModel. 

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

I'm not able to reproduce the error in plnkr, as forms isn't available on npmcdn. Error: (SystemJS) Error: XHR error (404) loading https://npmcdn.com/@angular/src/forms(…) - ./src/forms is exported by https://npmcdn.com/@angular/forms@0.1.1

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.3
 
* **Browser:** Chrome 51.0.2704.103 m
 
* **Language:** TypeScript

**Comment by aryeh** [comment] 2016-06-30 13:07
In your component you can get the data of the form with  `this.form.value`

Do you have an member of your component class called `job`?  i.e.  this.job = {};

**Comment by yusijs** [comment] 2016-06-30 13:14
I'm aware - I'm not trying to get it, but set it based on data from an external source. 

Yes:
job: Job = new Job(); // Job is a class that creates an object.

**Comment by aryeh** [comment] 2016-06-30 13:43
are you including REACTIVE_FORM_DIRECTIVES?

**Comment by yusijs** [comment] 2016-06-30 13:45
Yes. The entire form works, just not ngmodel for some reason. And yes, I am including ngmodel to.

**Comment by kara** [comment] 2016-06-30 15:40
This one will be hard to diagnose without a plunker.  You should be able to create one with the new forms module. Just fork this one:

http://plnkr.co/edit/F11jEoCBO4og8Ri0pmtN?p=preview

**Comment by yusijs** [comment] 2016-06-30 16:06
Alright. I'll try creating a plunk for it later today (couple hrs) and update.

**Comment by yusijs** [comment] 2016-06-30 17:05
@kara http://plnkr.co/edit/KH9aNuHHMwQ1rJIoVNNP?p=preview is reproducing my issue (only difference is that I grab my data from an api, while I declared static values here)

**Comment by kara** [comment] 2016-06-30 17:15
@yusijs It looks like you're mixing the deprecated and new forms API here.  When you import from `@angular/common`, you're taking symbols from the old API, but you're providing platform directives from the new one in main.ts.   If you update your code to use only `@angular/forms`, the error does not appear and your form works as expected:

http://plnkr.co/edit/J4q5q1KmbpowtPgsryNV?p=preview

I'm closing this, as it seems to be working. Let me know if I'm missing something!

**Closed by kara** 2016-06-30 17:15 UTC
Labels: need: repro

**Comment by yusijs** [comment] 2016-06-30 17:33
Yeah that works. Breaking changes and component names are hard. Apologies for the support request :3

**Comment by kara** [comment] 2016-06-30 17:39
No worries.  Glad it was a quick fix!

**Comment by andyrue** [comment] 2016-07-07 19:00
@kara Did something break this in rc.4? Seems your plunker isn't working now. I stumbled upon this thread after upgrading from rc.3 and my form no longer pre-populating. I haven't discovered what's wrong yet.

**Comment by kara** [comment] 2016-07-07 19:07
Hmm, the plunker looks right to me.  If you take another look, you'll see the initial value is deliberately being set to "Customer", which is not a real option value - just a placeholder. If you change the initial value in the component class to a real client ID like `1`, it pre-populates as you'd expect.  Or if you change the value of the placeholder option to "Customer", it will pre-populate "Customer". Depends what you're trying to do.

Can you link to a plunker with your issue?

**Comment by andyrue** [comment] 2016-07-07 19:22
You're right. Sorry! I'll see if I can reproduce my problem.

**Comment by andyrue** [comment] 2016-07-07 21:23
I guess my case is a little different, probably should have opened a new issue. I'm taking an `@Input` value and populating the form fields so it has a few more moving pieces. Examples are below. Clicking on clients should display details with form inputs populated with details. Thanks for your time!

This is working with rc.3, forms-0.1.1
http://plnkr.co/edit/wWbkUOLXN58njAPZONma?p=preview

This is not working with rc.4, forms-0.2.0
http://plnkr.co/edit/tw7BMxaMJ65ulTbFKFYA?p=preview

**Comment by kara** [comment] 2016-07-07 22:42
Thanks for sharing the plunker examples.  It looks like you're trying to use a reactive strategy, but you're missing a vital directive, `formControlName`.  Confusingly, it *happens* to work in 0.1.1, but as we made our type checking stricter in 0.2.0, it (rightly) fails.    We are planning to add some friendly errors so that it doesn't silently fail, as it does here.

To explain further, in your plunker, you're creating the `FormGroup` instance and its child controls using `FormBuilder`. But then you're not connecting the child form control "name" to any form control element in the DOM.  That's what `formControlName` does in the reactive approach - you pass in the string name of the control you'd like to connect, and it connects the form control element with that `FormControl` instance**. 

If you'd then like to init some data, you have a few choices.  You can use a one-way binding with `ngModel` and the valueChanges observable:
http://plnkr.co/edit/6EEuqvkRVL5GDmYkraO7?p=preview

You can use `updateValue()` to make this truly driven by the class and not the template:
http://plnkr.co/edit/W2iPVmcnvDtJ2SUsI11J?p=preview

Another option would be to switch entirely to a template-driven strategy, which would actually simplify your code a lot.  In this case, you can keep the two-way binding on `ngModel`:
http://plnkr.co/edit/SkjT86Selj2RsbA32aRe?p=preview

Also keep in mind that the form itself always contains the correct value, so you don't always need to update the domain model so assiduously.

Does that resolve your issue? Let me know if I'm missing some part of your use case. 

**In a template-driven strategy, the control instances are created and registered implicitly by the form directives in the template, so there's no need for a `formControlName` (and in fact, that won't work). You only need a `name` attribute.   A good rule of thumb to follow is to use all "form" prefixed directives together, and all ngModel prefixed directives together.

**Comment by andyrue** [comment] 2016-07-07 22:52
Above and beyond! Thanks, this was super helpful.

I had originally been using a template-driven form but couldn't figure out how to subscribe to the inputs as I wanted to do some on-the-fly formatting to input 1 and store it in input 2 so I switched to model driven. Is there a way to get the simplicity of template-driven but still be able to subscribe to an input's changes?

**Comment by srivch** [comment] 2016-08-02 16:02
@kara  Question regarding Reactive Directives - So if I infer the above information correctly, when I use reactive, there is no option of two way binding. I can set intial value for my control using control.updateValue() as and when I receive it, and then have to subscribe to value changes of the control, if I have to update my model [I don't want to use form.value] (Or) is it okay to use [(ngModel)] for my input controls by including FORM_DIRECTIVES along with REACT_FORM_DIRECTIVES?

**Comment by yusijs** [comment] 2016-08-02 16:11
Easiest way to do what you're asking is [ngModel], so just one-way binding. You don't need to update the model from the form, so no need for 2-way binding.

**Comment by srivch** [comment] 2016-08-02 17:47
i was probably not clear.. I understand how to do one way binding when using reactive directives, but what if I want to update the model as and when the input changes (I want to accomplish two way binding).. can I use [(ngModel)] or is there any other way?

**Comment by yusijs** [comment] 2016-08-02 17:53
You can iirc, but you need inputs named similar to templatedriven:
<input name="aninput" #aninput="ngModel" [(ngModel)]="model"> 

This should work, but it's a lot of extra work imo (and could possibly impact performance, since it tracks both FormGroup and model. I'd suggest the reactive route:

this.form.valueChanges.subscribe(values => this.yourModel = values); 

This will accomplish the same thing.

**Comment by srivch** [comment] 2016-08-02 18:00
thanks for the update
