### ISSUE TITLE
Relative TemplateUrl with SystemJS

### ISSUE THREAD

**Issue by meriturva** [angular/angular#6053] opened 2015-12-21 14:16 UTC
As mention on https://github.com/angular/angular/issues/2383 we could use Relative TemplateUrl just setting the property "module" inside component decoration.

Actually we are unable to use this feature because we use systemjs as described in "5 Min Quickstart - ts" sample....so we don't have any "module.id" set by the loader.

The question is just simple...how to use Relative TemplateUrl with SystemJS?

**Comment by tomwayson** [comment] 2015-12-23 18:11
I believe I'm having the same issue. When I include the following in my component decoration it appears that `module` is undefined and I get the error below:
```ts
@Component({
  selector: 'home-button',
  template: '<a class="esri-home" href="#" (click)="onClick($event)"><i class="material-icons">home</i></a>',
  moduleId: module.id,
  styleUrls: ['home.component.css']
})
```

![image](https://cloud.githubusercontent.com/assets/662944/11982062/e3cebfc8-a95c-11e5-8b7b-7e8874e1012f.png)

I'm using SystemJS as per the beta.0 quickstart - below are my dependencies from package.json:
```json
  "dependencies": {
    "angular2": "2.0.0-beta.0",
    "systemjs": "0.19.6",
    "es6-promise": "^3.0.2",
    "es6-shim": "^0.33.3",
    "reflect-metadata": "0.1.2",
    "rxjs": "5.0.0-beta.0",
    "zone.js": "0.5.10"
  },
  "devDependencies": {
    "concurrently": "^1.0.0",
    "lite-server": "^1.3.1",
    "typescript": "^1.7.3"
  }

```

**Comment by piernik** [comment] 2015-12-31 10:20
+1

**Comment by GregJPreece** [comment] 2016-01-17 04:47
+1

**Comment by VictorLeach96** [comment] 2016-01-20 17:15
+1

**Comment by soncodi** [comment] 2016-01-23 21:16
@meriturva: try

```js
@Component({
  selector: 'app',
  moduleId: __moduleName
})
```

also look here: https://github.com/systemjs/systemjs/issues/808

**Comment by evanplaice** [comment] 2016-01-28 23:59
ref #6131

**Comment by evanplaice** [comment] 2016-01-29 00:08
Here's a workaround. Be careful though, it won't work with minification.
https://github.com/angular/angular/issues/2383#issuecomment-176461396

**Comment by goldenbearkin** [comment] 2016-01-29 16:25
+1

**Comment by otabekgb** [comment] 2016-02-02 13:48
+1

**Comment by tbragaf** [comment] 2016-02-02 17:28
@tomwayson With systemjs you are supposed to use __moduleName instead of module.id, since this one is from commonjs.

The problem now is __moduleName is being parsed to "$__moduleContext.id" and $__moduleContext is a string (with the moduleName value) and $__moduleContext.id sets to undefined.

Has anyone solved this yet?

**Comment by prokher** [comment] 2016-02-06 17:42
+1

**Comment by Pro** [comment] 2016-02-11 12:30
:+1:

**Comment by MonkeyDo** [comment] 2016-02-19 15:33
Same here, reproduced in the same way @tomwayson describes.

As a workaround, I've temporarily changed typescriptOptions.module to 'commonjs' in my jspm config file.
For now, and for my project, this seems to work with no negative impact.

I would love to see this resolved in a cleaner manner.

**Comment by xx0r** [comment] 2016-02-21 09:45
while this workaround did the trick, it does not anymore in beta7, since the module seems to be undefined:

`error TS2304: Cannot find name 'module'.`

+1 for me, relative paths are really a must have...

**Comment by xx0r** [comment] 2016-02-21 10:39
I found a way to make it compile:

you need to create a .d.ts file (e.g. shim.d.ts) containing:
`declare var module: any;`

then reference it in your bootstrap file for example:

`/// <reference path="../../typings/shim.d.ts" />`

you still need to have the typescript compilation (tsconfig.json) option set:

`"compilerOptions":
  {
    ...
    "module": "commonjs",
...
  },`

**Comment by MonkeyDo** [comment] 2016-03-02 10:20
My workaround ('module':'commonjs' typescript options) worked fine until I started using Rxjs observables.
Importing Observable from rxjs produced this error in the browser console:
```reflect-metadata shim is required when using class decorators```
even though reflect-metadata was loaded at the very beginning in my main.ts file.

Reverting to 'module':'system' fixed that, and I've had to revert to an absolute path templateURL, unfortunately.

**Comment by basvdijk** [comment] 2016-03-11 12:52
+1

**Comment by hulucc** [comment] 2016-03-23 04:53
+1

**Comment by rogerbush8** [comment] 2016-03-26 16:30
+1

**Comment by zoechi** [comment] 2016-03-26 17:16
There is a nice new GitHub feature to "add reaction"s instead of `+1` posts. Please use this instead :+1:

**Comment by tomwayson** [comment] 2016-03-26 17:55
Which is unfortunately not available in mobile view. :disappointed:

**Comment by DrewynV** [comment] 2016-04-05 00:28
__________________________________

Hi! We just wanted to let you know we receievd your email. Thank you for submitting your request. Our aim is to get back to you within 24 hours at the latest. If you have any additional information to add to your request, please reply to this email.


Also please visit our knowledgebase (http://www.support.magicdust.com.au) to browse for further info, we are adding to it all the time.

Or here is our industry report about the 11 Essentials for a Successful Website (http://www.magicdust.com.au/web-design/.

We look forward to helping you succeed online.

Thanks

The Team @ Magicdust Digital

http://support.magicdust.com.au/

Ph (02) 9979 7474
M-F | 9 am-5:00 pm AEST (AEDT in Summer) excluding Public Holidays

------------------------------------------------------------------------------------------------------------
This message was sent to  reply@reply.github.com in reference to Case #166456.
------------------------------------------------------------------------------------------------------------


[[c3f8925044db2cf49bd730d334d09a15ff6c8d3b-673073406]]

**Comment by DrewynV** [comment] 2016-04-05 00:31
__________________________________

Hi! We just wanted to let you know we receievd your email. Thank you for submitting your request. Our aim is to get back to you within 24 hours at the latest. If you have any additional information to add to your request, please reply to this email.


Also please visit our knowledgebase (http://www.support.magicdust.com.au) to browse for further info, we are adding to it all the time.

Or here is our industry report about the 11 Essentials for a Successful Website (http://www.magicdust.com.au/web-design/.

We look forward to helping you succeed online.

Thanks

The Team @ Magicdust Digital

http://support.magicdust.com.au/

Ph (02) 9979 7474
M-F | 9 am-5:00 pm AEST (AEDT in Summer) excluding Public Holidays

------------------------------------------------------------------------------------------------------------
This message was sent to  reply@reply.github.com in reference to Case #166568.
------------------------------------------------------------------------------------------------------------


[[f3a6db822336c93d1e805ad365d8e6828273b80d-673074350]]

**Comment by DrewynV** [comment] 2016-04-05 00:31
__________________________________

Hi! We just wanted to let you know we receievd your email. Thank you for submitting your request. Our aim is to get back to you within 24 hours at the latest. If you have any additional information to add to your request, please reply to this email.


Also please visit our knowledgebase (http://www.support.magicdust.com.au) to browse for further info, we are adding to it all the time.

Or here is our industry report about the 11 Essentials for a Successful Website (http://www.magicdust.com.au/web-design/.

We look forward to helping you succeed online.

Thanks

The Team @ Magicdust Digital

http://support.magicdust.com.au/

Ph (02) 9979 7474
M-F | 9 am-5:00 pm AEST (AEDT in Summer) excluding Public Holidays

------------------------------------------------------------------------------------------------------------
This message was sent to  reply@reply.github.com in reference to Case #166574.
------------------------------------------------------------------------------------------------------------


[[47d86bc24aeb1bcd6aa86b20b04ae72f858b6088-673074356]]

**Comment by maksir** [comment] 2016-04-14 09:22
If you use 'module':'system', like me, you may fix moduleId on absolute component path and use relative path for templateUrl and styleUrl.
`
@Component({
	selector: 'doc-list',
	moduleId: 'app/components/documents/doclist.component',
	templateUrl: './list.html',  // transform to http-get  my-site/app/components/documents/list.html
    directives: [CORE_DIRECTIVES, FORM_DIRECTIVES]
})
export class DocListComponent {
...
}
`

**Comment by AlexCatch** [comment] 2016-04-15 18:41
+1

**Comment by segersrobbert** [comment] 2016-04-16 20:29
+1

**Comment by ChrisFulstowAGL** [comment] 2016-04-25 06:38
Seems to work fine now for SystemJS modules in TypeScript 1.8.9.
```
declare var __moduleName: string;

@Component({
    selector: 'my-component',
    moduleId: __moduleName,
    templateUrl: './my.component.html'
})
export class MyComponent { }
```

**Comment by j2L4e** [comment] 2016-04-25 12:13
Is there any downside to specifying `moduleId`?

**Comment by webmutation** [comment] 2016-05-03 13:09
@j2L4e Well its loader specific so its not very portable.

**Comment by evanplaice** [comment] 2016-05-04 16:25
@j2L4e Modules are CommonJS-specific.

There's no tc39 specification for ES modules yet. They have been mentions of adding them in the future but the feature hasn't even reached the proposal state yet.

Committing to a non-official module format right now is a poor design decision at this point (ie incurs tech debt) unless the ES standard concerges on the CommonJS format in the future.

**Comment by kylecordes** [comment] 2016-05-05 21:30
Like a zillion others, I am eager for this.

**Comment by nrubiano1** [comment] 2016-05-06 00:41
as @maksir says, in this way works.

` @Component({ selector: 'doc-list', moduleId: 'app/components/documents/doclist.component', templateUrl: './list.html', directives: [CORE_DIRECTIVES, FORM_DIRECTIVES] }) export class DocListComponent { ... } `

**Comment by kylecordes** [comment] 2016-05-06 01:44
Yes, that "works" - but the point is not to split up typing the path the template again in a different field; the point is to not type it at all, but rather have it be automatically relative to the component source code.

**Comment by tbragaf** [comment] 2016-05-07 13:57
@kylecordes 
```js
@Component({
    selector: 'my-component',
    moduleId: __moduleName,
    templateUrl: './my.component.html'
})
export class MyComponent { }
```

Why isn't this an option?
Being automatically relative can't be an option I guess. AngularJS 1.X had its own module loader but on the other hand, NG2 doesn't pack its own module loader, so that you can choose between require, systemjs, etc.
I am not really sure on how the suggestion would affect the module loader DSL.

**Comment by juristr** [comment] 2016-05-07 15:20
John Papa used relative template urls with the latest Angular 2 CLI in his presentation @ ngconf:
https://youtu.be/WAPQF_GA7Qg

**Comment by kylecordes** [comment] 2016-05-07 16:35
@tbragaf - Yes, this "works" also. @juristr -  Yes, thank you, I was there in the room. :-)

Maybe I should open a new issue for the thing I am getting at here: I believe this is fundamentally a problem for the Angular team to solve, at least within the realm of whatever subset of bundling options they plan to support. Perhaps they will choose to simply not support any at all. So far the CLI tool uses the require syntax (module.id) for this; though I've not looked to see what bundler it actually uses. I have working programs here that use both the module.moduleId syntax (projects where I use webpack) and the __moduleName syntax (projects where I use system). But this is a mess. It is suitable for some awful legacy thing, it is not a suitable solution, having these different syntaxes to move back and forth between in the source code depending on the bundler used, for the shining new state-of-the-art Angular 2.

**Comment by juristr** [comment] 2016-05-07 16:46
@kylecordes agree. Lucky you, that you were in the room :wink:

**Comment by born2net** [comment] 2016-05-27 05:04
I am on TS 1.8.10 and can't use:
```
@Component({
    selector: 'my-component',
    moduleId: __moduleName,
    templateUrl: './my.component.html'
})
export class MyComponent { }
```
and yes I am using system (not cjs) in both tsconfig and config.js
is this a known issue? is there  fix?

regards

**Comment by robwormald** [comment] 2016-05-29 03:39
Soooo let's do some explaining here:
> @j2L4e Modules are CommonJS-specific.

> There's no tc39 specification for ES modules yet. They have been mentions of adding them in the future but the feature hasn't even reached the proposal state yet.

> Committing to a non-official module format right now is a poor design decision at this point (ie incurs tech debt) unless the ES standard concerges on the CommonJS format in the future.

@evanplaice this is, sorry, entirely wrong. The ES6 module specification is finalized and in http://www.ecma-international.org/ecma-262/6.0/#sec-ecmascript-language-scripts-and-modules - and Typescript implements it in it's entirety. 

What is not finalized yet is the *Loader* specification, which is why, despite the fact that Chrome, for example, supports 98% of the ES6 specification, you have to run your code through some kind of bundling tool (Webpack) or use a dynamic module loader (SystemJS). 

@kylecordes 
> Maybe I should open a new issue for the thing I am getting at here: I believe this is fundamentally a problem for the Angular team to solve, at least within the realm of whatever subset of bundling options they plan to support. ... But this is a mess. It is suitable for some awful legacy thing, it is not a suitable solution, having these different syntaxes to move back and forth between in the source code depending on the bundler used, for the shining new state-of-the-art Angular 2.

The unfortunate reality here is that this problem is fundamentally unsolvable, at least from a dynamically loaded point of view. Note that angular1 had the *exact* same problem - once bundled, there's no correlation between where the single blob of code lives to where the templates live, thus some hack like `module.id` / `__moduleName` has to be used, hence why 99.9% of angular projects used some tool like gulp-ng-template-cache.

Here's the long term:
- if you are build-tool averse, you are stuck with `module.id` / `__moduleName`, or using absolute urls - I'd love it if there was a better answer, but there simply is not. The Angular team cannot change the fundamental mechanics of your browser. 
- The soon-to-be-shipped actual solution to this problem is template precompilation, where (at build time) your external templates and CSS are turned into code, and thus are bundled like any other source file in your project. More information on this is forthcoming (and of course, the CLI will handle this) - this allows you to use relative templates without issue.
- An interim solution (which we ourselves use on the Angular Material2 project) is to use a tool to inline your templates / css into your source at build-time, turning 
```typescript
templateUrl: 'foo.html'
```
into
```typescript
template: '<div>foo</div>
```
See https://github.com/ludohenin/gulp-inline-ng2-template for an example of this sort of thing.

Webpack users can use `require('./some-template.html')` - see https://angular.io/docs/ts/latest/guide/webpack.html for an example of how to use this.

SystemJS has the ability to use loaders for text in a similar fashion - https://github.com/systemjs/plugin-text

In a proper production application, you don't want to be making XHR requests to fetch templates anyway, so some form of tooling is highly advised. Personally, I'd use one of the inliners in the interim as that's the most portable solution, and should require no changes when template precompilation comes online.

**Closed by robwormald** 2016-05-29 03:39 UTC

**Comment by kylecordes** [comment] 2016-05-29 14:35
@robwormald "If you are build-tool averse, you are stuck with module.id / __moduleName". I am not averse to a build tool, I've been working with several of the build tool choices (we already have units in our curriculum about them) for months. The thing I'm averse to is the difference between module.id / __moduleName depending on which build tool is used. I'm thinking about some chunk of syntax, however ugly, that would be deemed acceptable to the typescript compiler and would let us include both of those syntaxes in a source file, so that the source file does not need to change when I switch build tools.

(About template precompilation, yes, absolutely, this is excellent. I realize it is not shipped yet but I've already been working with it based on the examples you have published in your Github account; I had been hoping actually to chat with you about this at ng-conf, but I didn't get a chance. And of course, separate request to fetch each template is ridiculous as you say. Serious applications never shipped anything to production with A1 doing that, and won't either with A2.)

**Comment by webmutation** [comment] 2016-05-31 15:22
@robwormald what about images, the plan is to inline that as well? That doesn't make creating portable widget libraries very nice. Please see issue [6637](https://github.com/angular/angular/issues/6637)

**Comment by robwormald** [comment] 2016-05-31 15:33
@webmutation we're entirely open to suggestions, but its not a "decision" we've made, we're simply working within the constraints of the web platform. Without using a hack like moduleName / module.id, there's no way to correlate a module that's in a bundle (generally in the root of a /dist directory) with a physical location on disk (and again, note that this isn't a new problem)

If you've got any bright ideas, I'm all for hearing them. We (the angular team) have looked at this for *months* and currently the module hack is the best we've been able to come up with so far.

**Comment by kylecordes** [comment] 2016-05-31 18:12
@robwormald and @webmutation The conclusion we have reached here is that, when building portable/reusable widgets or libraries, use in-line templates. I'm not yet 100% sure whether that will work with the template pre-compiler though, looking forward to the next RC to find out. It does however completely self the problem keeping the template associated with the code. Some IDEs (unfortunately not VS code yet) can do syntax highlighting of an embedded template.

**Comment by webmutation** [comment] 2016-05-31 18:20
@robwormald my goal is to understand if there will be an automated way (like images get transformed into dataURI and inlined if they are used relatively inside of the templates? Or its just for the templates themselves?

Perhaps it is best if I can explain a bit the context of the question: The project my team is currently working is the creation of reusable ng2 components (this will be used by multiple DGs in the European Commission), some of these components have images and absolute urls break the re-usability (the images are relative to the component not the app). We currently "fix" this by using a gulp task to rewrite the relative into absolute urls (but we hoped this issue could be solved by the ng2 team at the framework level). 

Is there a better way to tackle component isolation that contain images?

On a related note ` url('image.jpg') `or `<img src='image.jpg' />` inside of the templates are still broken, this seems to be within the constrains of the web platform. If you create a web page the browser will load those files relative to the page, but in ng2 that does not happen.

Regarding ideas (perhaps not so bright), could a decorator be used (something like @relativePath) to actually look up the module loader that is being used (is there a simple way to detect this... it could be as simple as looking up the value on tsconfig.json)? Perhaps abstract the module hack behind it?

The issue like @kylecordes says is that devs are currently forced to change from module.id / __moduleName just because the module loader changed, if this could be abstracted away it would make things nicer at least for relative templateURL, and allows to keep the template and the component separate.

I will take a look at how code is generated using the angular compiler, this is important for us but i understand if its not currently a big priority for the angular project.

**Comment by robwormald** [comment] 2016-05-31 19:01
@kylecordes inline CSS and templates are supported by the template compiler, so there's no issue there... but if you're using the compiler there's no particular reason *to* use inlined (and you actually pay a bit of a penalty, since they are now included in both your Component code and your generated Component code...)

> If you create a web page the browser will load those files relative to the page, but in ng2 that does not happen.

because the concept of a "folder" is an entirely alien concept to a browser, so a component that's fetched from 
`/foo/bar/baz.ts` has no way to know where it is in a hierarchical structure, without some hint (which is exactly what module.id / __moduleName do...) as to where it exists... 

Because the hint has to come from the module code itself, there's no way for us to do it "behind the scenes" - the only place the path is available is from the module itself, and thus it has to be done *in* your module's code. A quick and dirty cheat:
```typescript
moduleId: __moduleName || module.id
``` 

> I will take a look at how code is generated using the angular compiler, this is important for us but i understand if its not currently a big priority for the angular project.

Again, it's not a question of *priority* as much as it is a question of the basic mechanics of the web. Single page applications, by definition, are all pretty much running at index.html, and all modular code runs at that path as well, so the idea of "relative paths" totally disappears at runtime.

This is something that has to be handled at build time, and a myriad of tools exist in the ecosystem to handle such things (because this isn't a new problem specific to angular2)

Precompilation currently doesn't have any hooks for image/resources as far as I'm aware, and I'm not entirely sure it should, but will discuss.

**Comment by kylecordes** [comment] 2016-06-01 22:10
Ouch: I definitely do not want to ship both the template source and the compiled results. So I will change the practice here and stop using in-line templates at all. Seems like something to warn people about if they use in line.  Thank you.

As I understand, this general category of problem is attacked effectively (at a cost of rather considerable complexity) in the webpack plug-in ecosystem. I realized the CLI is heading in a different direction (a good direction I think), but if we had the angular template compiler and an Angular-aware wrapper around typescript, implemented as webpack plug-ins, they could solve this problem even across components reused as node modules. The solution would even transitively apply to all of the further resources mentioned inside an angular template. That seems like a monster of a dependency to take, so this is a discussion comment and not a feature request :-)  But I think it is worth thinking about at least to understand that a solution is possible.

**Comment by jinwyp** [comment] 2016-08-05 10:28
I am on TS 1.8.10 and can't use:

```
@Component({
    selector: 'my-component',
    moduleId: __moduleName,
    templateUrl: './my.component.html'
})
export class MyComponent { }
```

after run 'tsc' got error 
"error TS2304: Cannot find name '__moduleName'."

**Comment by choeller** [comment] 2016-08-05 10:33
@jinwyp this has nothing to do with typescript, but with the module-loader you are using. When using a newer version of system.js try:
```    
moduleId: module.id,
```
also don't forget to declare the module-variable for typescript in some typing-file like this:
```
module: any
```
(you could also create the correct interface here, but `any` makes it easier ;) )

**Comment by Turash** [comment] 2016-08-07 10:00
Hi I solved the issue. I imported Obervable from rxjs and rxjs map function

`import { Observable} from 'rxjs';
import "rxjs/add/operator/map";`

And used standard templateurl
` templateUrl: 'app/app.component.html'`

Hope it works. Will provide tsconfig.json and package.json file if you need assistance

**Comment by mlc-mlapis** [comment] 2016-08-07 10:36
I do not understand how the line:
import { Observable} from 'rxjs'; import "rxjs/add/operator/map";
is related to the problem of relative addressing in templateUrl property.

@choeller What you mean as newer version of system.js? Which one exactly? They left syntax `moduleId: __moduleName;`?

**Comment by enrico-atzeni** [comment] 2016-08-07 10:43
@mlc-mlapis I think @choeller is quoting @ChrisFulstowAGL comment of the 25 April.
I solved too in the @ChrisFulstowAGL way without changing the module to **commonjs**.

**Comment by mlc-mlapis** [comment] 2016-08-07 10:55
@enrico-atzeni OK. So it means that nothing changed from this point of view.

**Comment by Turash** [comment] 2016-08-07 19:50
Hi @mlc-mlapis This is my file:
<img width="772" alt="github1" src="https://cloud.githubusercontent.com/assets/5880099/17464834/6948ccb8-5ce8-11e6-86f7-e927a4630048.png">

<img width="526" alt="github2" src="https://cloud.githubusercontent.com/assets/5880099/17464864/b8afa8e4-5ce8-11e6-962c-ffd3d2277ac3.png">
This is my package.json file

Apart from this it is important you have tsconfig.json file like this 
`{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false
  }
}`

**Comment by mlc-mlapis** [comment] 2016-08-07 20:02
Fine but what was the original problem to which you responded? I am actually a bit lost about what we are actually discussing. Thanks.

**Comment by Turash** [comment] 2016-08-07 20:20
Isnt it the referecing template url with system.js?. Oh I presumed it was the issue.

**Comment by mlc-mlapis** [comment] 2016-08-07 21:54
OK, so it is st that was solved already sometime ago. The way with system.js is to use `moduleId: __moduleName;` like:

`declare const __moduleName: string;

@Component({
	selector: 'page-info',
	moduleId: __moduleName,
	templateUrl: 'panelPageInfo.tmpl'
})`

This case means that the template is stored in the same directory as the component itself. And if the template is saved in a subdirectory (for example 'template') then	templateUrl should be:
`templateUrl: 'template/panelPageInfo.tmpl'`.

**Comment by Turash** [comment] 2016-08-07 22:02
ok. I need to try this then. I showed how I achieved the result in alternative way.
