### ISSUE TITLE
Use of @starting-style makes Chrome crash

### ISSUE THREAD

**Issue by vanthome** [angular/angular#54107] opened 2024-01-26 22:04 UTC
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

When we use the new `@starting-style` CSS directive and build the angular app, it makes chrome crash. Just see this simple test app:

https://github.com/n-fuse/starting-rule-for-entry-animation/tree/main

- works with `ng serve`
- `ng build` and serving the built app from the `dist` folder --> chrome crashes

We tried it with plain SASS and that does not lead to the issue, so it must be the way how Angular bundles those things together.

### Please provide the exception or error you saw

```true
Chrome crashes
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
vAngular CLI: 17.1.1
Node: 20.8.0
Package Manager: npm 10.1.0
OS: linux x64

Angular: 17.1.1
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1701.1
@angular-devkit/build-angular   17.1.1
@angular-devkit/core            17.1.1
@angular-devkit/schematics      17.1.1
@schematics/angular             17.1.1
rxjs                            7.5.7
typescript                      5.3.3
zone.js                         0.14.3
```

**Comment by JeanMeche** [comment] 2024-01-28 17:13
I wasn't able to reproduce the crash with Chrome M121. Is your version update to date ?

**Comment by pkozlowski-opensource** [comment] 2024-01-29 04:50
Also make sure that your tests are done without browser extensions that might interfere with the application.

**Comment by vanthome** [comment] 2024-01-30 17:06
It even happens on my Android Chrome which certainly has no add-ons.

**Comment by JoostK** [comment] 2024-01-30 18:12
Since `@starting-style` is relative new, I wouldn't be surprised if this is a Chrome bug. A web app should never be able to crash a browser like this, so this is almost certainly on Chrome's side. I suspect this can be reproduced without Angular, at which point you could consider opening an issue with Chrome.

**Comment by JeanMeche** [comment] 2024-01-30 18:54
As a simple repro:

index.html

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="stylesheet" href="./style.css" />
  </head>
  <body></body>
</html>

```

style.css

`@starting-style {}`

Is enough to crash Google Chrome. (121.0.6167.139 in my case). 

I'll close it as not an Angular issue.

**Closed by JeanMeche** 2024-01-30 18:54 UTC
Labels: area: core

**Comment by ginger-tek** [comment] 2024-02-14 17:04
Holy crap, I's so glad I found this!! Been pulling my hair out thinking this was my Caddy install, PHP-CGI, PHP itself... nope; experimental @starting-style I was using for <dialog> animations.

How tf does a CSS rule cause a whole browser tab to crash...

Anyway, this is great to finally figure out 👍
