### ISSUE TITLE
Improve Error for:  No provider for XService!

### ISSUE THREAD

**Issue by cedvdb** [angular/angular#15552] opened 2017-03-28 11:19 UTC
```
[ X ] feature request
```

**Current behavior**

The current error thrown when a service hasn't been defined in a module is:

```
zone.js:522 Unhandled Promise rejection: No provider for XService! ; Zone: <root> ; Task: Promise.then ; Value: 
Error
 Error
    at Error.ZoneAwareError (http://localhost:3000/polyfills.bundle.js:3588:33)
    at ZoneAwareError (http://localhost:3000/polyfills.bundle.js:3585:35)
    at injectionError (http://localhost:3000/vendor.bundle.js:3087:86)
    at noProviderError (http://localhost:3000/vendor.bundle.js:3125:12)
    at ReflectiveInjector_._throwOrNull (http://localhost:3000/vendor.bundle.js:4627:19)
    at ReflectiveInjector_._getByKeyDefault (http://localhost:3000/vendor.bundle.js:4666:25)
    at ReflectiveInjector_._getByKey (http://localhost:3000/vendor.bundle.js:4598:25)
    at ReflectiveInjector_.get (http://localhost:3000/vendor.bundle.js:4467:21)
    at AppModuleInjector.get (ng:///AppModule/module.ngfactory.js:180:107)
    at AppModuleInjector.getInternal (ng:///AppModule/module.ngfactory.js:295:53)
    at AppModuleInjector.NgModuleInjector.get (http://localhost:3000/vendor.bundle.js:5431:44)
    at resolveDep (http://localhost:3000/vendor.bundle.js:12836:45)
    at createClass (http://localhost:3000/vendor.bundle.js:12699:91)
    at createDirectiveInstance (http://localhost:3000/vendor.bundle.js:12530:37)
    at createViewNodes (http://localhost:3000/vendor.bundle.js:13879:49)
```

**Expected behavior**

I'd like to know what class the error originated from. What class is trying to inject XService.

**What is the motivation / use case for changing the behavior?**

When a module has been installed via `npm install` it becomes annoying to debug. Which NgModule is throwing this error ? 

* **Angular version:** 4.0.0

 
* **Language:** [TypeScript 2 ]

**Comment by DzmitryShylovich** [comment] 2017-03-28 11:29
Duplicate of https://github.com/angular/angular/issues/10734

**Closed** 2017-03-28 11:34 UTC
