### ISSUE TITLE
Error while trying to build docs locally on Windows 11 machine

### ISSUE THREAD

**Issue by bampakoa** [angular/angular#57920] opened 2024-09-23 11:56 UTC
### Describe the problem that you experienced

I tried to build the Angular Docs locally in Windows 11 and I get the attached error.

### If this problem caused an exception or error, please paste it here

```true
[2,185 / 2,591] Action adev/src/content/guide/components/advanced-configuration.
md.html; 71s local ... (20 actions, 18 running)
ERROR: C:/users/bampa/documents/github/angular/adev/src/content/guide/components
/BUILD.bazel:3:16: Action adev/src/content/guide/components/advanced-configurati
on.md.html failed: (Exit 1): markdown.bat failed: error executing command bazel-
out\x64_windows-opt-exec-2B5CBBC6\bin\adev\shared-docs\pipeline\markdown.bat baz
el-out/x64_windows-fastbuild/bin/adev/src/content/guide/components/advanced-conf
iguration.md.html-0.params ... (remaining 1 argument skipped)
file:///C:/Users/bampa/_bazel_bampa/b4ricovm/execroot/angular/node_modules/@baze
l/runfiles/runfiles.js:118
        const e = new Error(`could not resolve module ${modulePath}`);
                  ^
Error: could not resolve module angular/node_modules/mermaid/dist/mermaid.js
Please report this to https://github.com/markedjs/marked.
    at Runfiles.resolve (file:///C:/Users/bampa/_bazel_bampa/b4ricovm/execroot/a
ngular/node_modules/@bazel/runfiles/runfiles.js:118:19)
    at Runfiles.resolveWorkspaceRelative (file:///C:/Users/bampa/_bazel_bampa/b4
ricovm/execroot/angular/node_modules/@bazel/runfiles/runfiles.js:130:21)
    at getMermaidScriptTagData (file:///C:/Users/bampa/_bazel_bampa/b4ricovm/exe
croot/angular/adev/shared-docs/pipeline/guides/mermaid/index.ts:27:20)
    at Object.processMermaidCodeBlock (file:///C:/Users/bampa/_bazel_bampa/b4ric
ovm/execroot/angular/adev/shared-docs/pipeline/guides/mermaid/index.ts:54:29)
    at async Promise.all (index 265)
    at main2 (file:///C:/Users/bampa/_bazel_bampa/b4ricovm/execroot/angular/adev
/shared-docs/pipeline/guides/index.ts:29:31)
Target //adev:serve failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: C:/users/bampa/documents/github/angular/adev/src/assets/BUILD.bazel:5:
18 Copying files to directory failed: (Exit 1): markdown.bat failed:
 error executing command bazel-out\x64_windows-opt-exec-2B5CBBC6\bin\adev\shared
-docs\pipeline\markdown.bat bazel-out/x64_windows-fastbuild/bin/adev/src/content
/guide/components/advanced-configuration.md.html-0.params ... (remaining 1 argum
ent skipped)
INFO: Elapsed time: 257.859s, Critical Path: 114.70s
INFO: 2235 processes: 1398 internal, 620 local, 217 worker.
FAILED: Build did NOT complete successfully
ERROR: Build failed. Not running target
FAILED: Build did NOT complete successfully
iBazel [6:55PM]: Error starting process: fork/exec C:\Users\bampa\AppData\Local\
Temp\bazel_script_path4180415306.bat: %1 is not a valid Win32 application.
iBazel [6:55PM]: Run start failed fork/exec C:\Users\bampa\AppData\Local\Temp\ba
zel_script_path4180415306.bat: %1 is not a valid Win32 application.
################################################################################
# Did you know iBazel can invoke programs like Gazelle, buildozer, and         #
# other BUILD file generators for you automatically based on bazel output?     #
# Documentation at: https://github.com/bazelbuild/bazel-watcher#output-runner  #
################################################################################
```
```


### If the problem is browser-specific, please specify the device, OS, browser, and version

_No response_

### Provide any additional information here in as much as detail as you can

_No response_

**Comment by JeanMeche** [comment] 2024-09-23 12:05
Can you check if `node_modules/mermaid/dist/mermaid.js` exisit locally ?

**Comment by bampakoa** [comment] 2024-09-23 13:12
@JeanMeche it does!

**Comment by bampakoa** [comment] 2024-09-23 13:21
Thank you for your suggestions 🙏 I would prefer to avoid WSL though. I think that building the docs natively in Windows should be supported.

**Comment by alan-agius4** [comment] 2024-09-23 13:59
I think the issue is how mermaid is being resolved in https://github.com/angular/angular/blob/7b2fda16b1bc13419b40f1b661758c9e99f21008/adev/shared-docs/pipeline/guides/mermaid/index.ts#L27.

 Instead, it should be resolved from `npm/node_modules/mermaid`, which is a Bazel root path that also works on Windows.

**Comment by alan-agius4** [comment] 2024-09-23 14:07
@bampakoa, can you verify if patching the line fixes the issue?

**Closed** 2024-09-23 15:20 UTC
Labels: area: docs-infra
