### ISSUE TITLE
fix(typings): include RouterOutlet constructor signature in type definitions for 'angular2/router'

### ISSUE THREAD

**Issue by NathanWalker** [angular/angular#3291] opened 2015-07-25 03:29 UTC
Sample error when doing something along these lines...
```
export class LoggedInRouterOutlet extends RouterOutlet {
  publicRoutes: any
  constructor(public _elementRef: ElementRef, public _loader: DynamicComponentLoader,
              public _parentRouter: Router, @Attribute('name') nameAttr: string) {
      super(_elementRef, _loader, _parentRouter, nameAttr);
```
```
WARNING in ./src/app/LoggedInOutlet.ts
(13,7): Supplied parameters do not match any signature of call target.
```

When extending RouterOutlet, the generated type definition does not include the constructor signature, so compiling something like the above gives TypeScript Warnings.

**Comment by btford** [comment] 2015-07-28 18:57
duplicate of #3282

**Closed by btford** 2015-07-28 18:57 UTC
Labels: comp: router, effort1: easy (hour), P3: important, type: bug
