### ISSUE TITLE
4.0.0-rc.4 Increased Bundle Size

### ISSUE THREAD

**Issue by naveedahmed1** [angular/angular#15239] opened 2017-03-17 14:09 UTC
I updated my project to Angular 4.0.0-rc.4  and now when I compile my project the produced bundles are larger in size than the one generated with Angular 4.0.0-rc.3.

Bundle size with Angular 4.0.0-rc.4  is 5.71 Mb
Bundle size with Angular 4.0.0-rc.3  is 5.32 Mb

Is it the expected?

**Comment by kylecordes** [comment] 2017-03-17 15:19
Also seeing this here. Small repro:

https://github.com/OasisDigital/angular-aot-closure

Commit showing the difference:

https://github.com/OasisDigital/angular-aot-closure/commit/950b43d83ec1bb2ae02a3dec78dbde8b233dac1e

This is a Closure Compiler example of a small app. From the sizes stated, I would guess @naveedahmed1 's example is non-Closure, larger app.

**Comment by naveedahmed1** [comment] 2017-03-17 16:39
@kylecordes yes its relatively large and non-Closure app. Let me add, with Angular 2.x the size of the same app was around 14mb whereas with new View Engine, introduced in Angular 4.0.0-rc.1, the size was reduced to 5.32 Mb.

**Comment by tbosch** [comment] 2017-03-21 00:15
The size is increased a bit because we added sourcemap support, for which we needed to change the codegen slightly. There also were 2 size regressions that were fixed after we cut rc.4:

- https://github.com/angular/angular/commit/2a0e55ffb56bf4c42e87811425d258664e0d0b8c (only affects code that uses Closure Compiler, as it relates to tree shaking)
- https://github.com/angular/angular/pull/15322 (affected everybody)

Both will be part of the next rc / final.

**Comment by naveedahmed1** [comment] 2017-03-21 01:02
Thanks @tbosch for the update,  Is there anyway to disable sourcemap for productions builds to get smaller bundle size?

**Comment by tbosch** [comment] 2017-03-21 16:43
@naveedahmed1 no, one of the bigger changes in Ng4 is that we generate the same code for prod and dev mode. 
Some background: For each element or text node, we added a call like this `(l()(),...)` to the view definition. This is needed so that we can log errors from the place where elements / text nodes are defined, and together with sourcemaps this leads to a nice user experience. 

With the previous fixed and after https://github.com/angular/angular/pull/15350 lands, the additional size should be marginal. Plus it should gzip pretty well, as the characters `(),` are used in all JS code...

**Comment by tbosch** [comment] 2017-03-21 16:44
Thanks for pointing out this increase, as it allowed me to make the impact smaller.

Closing this now, as works as intended.

**Closed by tbosch** 2017-03-21 16:44 UTC
Labels: comp: core & compiler, comp: packaging, severity5: regression, type: bug

**Comment by naveedahmed1** [comment] 2017-03-21 17:34
Makes sense, Awesome work ! 👍

**Comment by evanjmg** [comment] 2017-06-13 22:59
I really like Angular 4, but with large apps AOT is still bigger than JIT, is there any update on this? Oor any way to address this now with the latest? I really don't like see doubles of my code
<img width="634" alt="screen shot 2017-06-13 at 11 08 12 pm" src="https://user-images.githubusercontent.com/9342155/27108307-4996316c-5094-11e7-9722-3bab949a2899.png">
