### ISSUE TITLE
ERROR in TypeError: Cannot read property 'flags' of undefined

### ISSUE THREAD

**Issue by lramnath** [angular/angular#36994] opened 2020-05-08 03:28 UTC
Fresh project causes error when doing ng serve

Angular CLI: 9.1.4
Node: 13.2.0
OS: win32 x64

Angular: 9.1.5
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.4
@angular-devkit/build-angular     0.901.4
@angular-devkit/build-optimizer   0.901.4
@angular-devkit/build-webpack     0.901.4
@angular-devkit/core              9.1.4
@angular-devkit/schematics        9.1.4
@angular/cli                      9.1.4
@ngtools/webpack                  9.1.4
@schematics/angular               9.1.4
@schematics/update                0.901.4
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0

**Comment by lramnath** [comment] 2020-05-08 03:31
ERROR in TypeError: Cannot read property 'flags' of undefined
    at resolveAlias (C:\Users\Latha\Documents\myTestApp\node_modules\typescript\lib\typescript.js:36513:37)
    at checkAliasSymbol (C:\Users\Latha\Documents\myTestApp\node_modules\typescript\lib\typescript.js:64502:26)
    at checkImportBinding (C:\Users\Latha\Documents\myTestApp\node_modules\typescript\lib\typescript.js:64534:13)
    at checkImportDeclaration (C:\Users\Latha\Documents\myTestApp\node_modules\typescript\lib\typescript.js:64552:29)
    at checkSourceElementWorker (C:\Users\Latha\Documents\myTestApp\node_modules\typescript\lib\typescript.js:64961:28)
    at checkSourceElement (C:\Users\Latha\Documents\myTestApp\node_modules\typescript\lib\typescript.js:64800:17)
    at Object.forEach (C:\Users\Latha\Documents\myTestApp\node_modules\typescript\lib\typescript.js:317:30)
    at checkSourceFileWorker (C:\Users\Latha\Documents\myTestApp\node_modules\typescript\lib\typescript.js:65123:20)
    at checkSourceFile (C:\Users\Latha\Documents\myTestApp\node_modules\typescript\lib\typescript.js:65091:13)
    at getDiagnosticsWorker (C:\Users\Latha\Documents\myTestApp\node_modules\typescript\lib\typescript.js:65179:17)
    at Object.getDiagnostics (C:\Users\Latha\Documents\myTestApp\node_modules\typescript\lib\typescript.js:65165:24)
    at C:\Users\Latha\Documents\myTestApp\node_modules\typescript\lib\typescript.js:98703:85
    at runWithCancellationToken (C:\Users\Latha\Documents\myTestApp\node_modules\typescript\lib\typescript.js:98665:24)
    at getBindAndCheckDiagnosticsForFileNoCache (C:\Users\Latha\Documents\myTestApp\node_modules\typescript\lib\typescript.js:98691:20)
    at getAndCacheDiagnostics (C:\Users\Latha\Documents\myTestApp\node_modules\typescript\lib\typescript.js:98956:26)
    at getBindAndCheckDiagnosticsForFile (C:\Users\Latha\Documents\myTestApp\node_modules\typescript\lib\typescript.js:98688:20)

**Comment by guillermohernandez** [comment] 2020-05-08 03:42
Run:
npm install @angular/core@9.1.4 @angular/animations@9.1.4 @angular/common@9.1.4 @angular/forms@9.1.4 @angular/platform-browser@9.1.4 @angular/router@9.1.4 @angular/platform-browser-dynamic@9.1.4 @angular/compiler@9.1.4 @angular/compiler-cli@9.1.4 @angular/language-service@9.1.4

ng build

From: https://stackoverflow.com/a/61671596/5157008

**Comment by lramnath** [comment] 2020-05-08 04:20
Thanks it worked

Sent from my iPhone

On May 7, 2020, at 8:42 PM, Guillermo Hernandez Jr <notifications@github.com> wrote:

﻿

Run:
npm install @angular/core@9.1.4 @angular/animations@9.1.4 @angular/common@9.1.4 @angular/forms@9.1.4 @angular/platform-browser@9.1.4 @angular/router@9.1.4 @angular/platform-browser-dynamic@9.1.4 @angular/compiler@9.1.4 @angular/compiler-cli@9.1.4 @angular/language-service@9.1.4

ng build

From: https://stackoverflow.com/a/61671596/5157008

**Comment by geetheshbhat** [comment] 2020-05-08 09:42
Thanks, I was also facing this issue

**Comment by petebacondarwin** [comment] 2020-05-08 10:02
Duplicate of #36993

**Closed by petebacondarwin** 2020-05-08 10:02 UTC

**Comment by JoseTurron** [comment] 2020-05-08 12:56
Thanks, it worked even without ng build :)

**Comment by ankitbinjola** [comment] 2020-05-08 14:48
thanks , it worked one more thing do we have to Run the above command every  i have to create a new app... 
thanks

**Comment by pishangujeniya** [comment] 2020-05-08 15:20
@guillermohernandez  Thanks a lot it worked like a boon, was struggling for last 2 hours to solve the issue.
