### ISSUE TITLE
Support destructuring assignment in *ngIf ... as ...

### ISSUE THREAD

**Issue by adamal** [angular/angular#27555] opened 2018-12-07 21:17 UTC
# 🚀 feature request

### Relevant Package
This feature request is for @angular/common

### Description
ES2015 allows _destructuring assignments_ such as `var {a, b} = {a: 2, b: 3}`.
In Angular templates we can currently use constructs such as 
```
<div *ngIf="thing$ | async as thing">
```
Being able to do destructuring assignment in templates would be very helpful in some circumstances. I might expect this to work:
```
<div *ngIf="thingAndOther$ | async as {thing, other}">
```
assuming `thingAndOther$` emits objects that look like `{thing: ... , other: ...}`

### Alternative
Having an `ngIf`-free way of doing local assignments in templates (see #15280) could reduce the need for this. Following IgorMinar's  comment [here](https://github.com/angular/angular/pull/25351#pullrequestreview-165442868), I might expect it to look like this
```
<div *ngIf="thingAndOther$ | async as thingAndOther" #[thing]="thingAndOther.thing" #[other]="thingAndOther.other" >
```
, though that is less convenient than direct destructuring assignment.

**Comment by thekiba** [comment] 2019-01-24 12:55
🚀Awesome issue!
@alxhub I think this is `comp: core & compiler`, not `comp: common`

Also will be great to see the destructuring assignment with the arrays and lettable template variables.

**Comment by trotyl** [comment] 2019-01-30 10:01
Relates to https://github.com/angular/angular/issues/8709

**Comment by amitbeck** [comment] 2021-01-26 08:14
Honestly #8709 is far more relevant for such feature, and sadly the PR has been locked. This and #36528 are definitely core functionalities I'm hoping Angular bring into the templates into the future.

**Comment by pkozlowski-opensource** [comment] 2024-08-14 14:46
Closing as a duplicate/specific case of https://github.com/angular/angular/issues/43485.
Duplicate of #43485

**Closed by pkozlowski-opensource** 2024-08-14 14:46 UTC
Labels: feature, area: core, area: compiler, core: binding & interpolation, feature: under consideration
