### ISSUE TITLE
Angular SSR does not call API on every page request

### ISSUE THREAD

**Issue by princ09** [angular/angular#55259] opened 2024-04-09 06:14 UTC
### Which @angular/* package(s) are the source of the bug?

platform-server

### Is this a regression?

No

### Description

I am rendering cards from an API. The response of the API is very dynamic, changing every few seconds. I expect to show the latest API data when we load the page. However, because of the below line in Hydration,
```
withHttpTransferCacheOptions({
        includePostRequests: true,
}),
```
 it caches the response and shows it on every load. We used this option to avoid making two calls from the backend and frontend, but then this new problem arose where the data is not refreshing at all. It shows data from the build time only.
 
I believe this is due to the caching mechanism you've implemented. It seems you're permanently caching the request, but ideally, it should only transfer the response to the frontend. I understand that we can use TransferState, but it's very inconvenient to generate a key and write code for transferring state for every request, especially considering we have 100 requests in the application.

Is there way to fix this? All we want is avoid making twice API call without transfer state and we need latest data to fetched from server everytime user request for a page. API calls are getting triggered in ngOnInit mostly.

**Comment by alan-agius4** [comment] 2024-04-09 12:53
Based on your description, it appears that the data is being shown from build time, indicating the use of SSG rather than SSR. This method may not be ideal for frequent data updates. I recommend checking out https://angular.io/guide/prerendering and https://angular.io/guide/ssr for further details.

**Comment by alxhub** [comment] 2024-04-09 17:48
Closing as the issue described is intended behavior for SSG. If this isn't the case, feel free to open a new issue with a reproduction showing the unexpected behavior.

**Closed by alxhub** 2024-04-09 17:48 UTC
