### ISSUE TITLE
(bug): Date pipe throws Reference error in Safari

### ISSUE THREAD

**Issue by markharding** [angular/angular#4445] opened 2015-10-01 11:33 UTC
The issue appears to be related to DateFormatter 'Intl' service.

```
[Error] EXCEPTION: ReferenceError: Can't find variable: Intl in [null]
	logError (angular2.dev.js, line 25219)
	logGroup (angular2.dev.js, line 25230)
	call (angular2.dev.js, line 20915)
	(anonymous function) (angular2.dev.js, line 27327)
	_onError (angular2.dev.js, line 16659)
	onError (angular2.dev.js, line 16579)
	run (angular2.dev.js, line 139)
	(anonymous function) (angular2.dev.js, line 16600)
	zoneBoundFn (angular2.dev.js, line 109)
	lib$es6$promise$asap$$flush (angular2.dev.js, line 1213)
[Error] ORIGINAL EXCEPTION: ReferenceError: Can't find variable: Intl
	logError (angular2.dev.js, line 25219)
	call (angular2.dev.js, line 20924)
	(anonymous function) (angular2.dev.js, line 27327)
	_onError (angular2.dev.js, line 16659)
	onError (angular2.dev.js, line 16579)
	run (angular2.dev.js, line 139)
	(anonymous function) (angular2.dev.js, line 16600)
	zoneBoundFn (angular2.dev.js, line 109)
	lib$es6$promise$asap$$flush (angular2.dev.js, line 1213)
[Error] ORIGINAL STACKTRACE:
	logError (angular2.dev.js, line 25219)
	call (angular2.dev.js, line 20927)
	(anonymous function) (angular2.dev.js, line 27327)
	_onError (angular2.dev.js, line 16659)
	onError (angular2.dev.js, line 16579)
	run (angular2.dev.js, line 139)
	(anonymous function) (angular2.dev.js, line 16600)
	zoneBoundFn (angular2.dev.js, line 109)
	lib$es6$promise$asap$$flush (angular2.dev.js, line 1213)
[Error] format@http://dev.minds.io/lib/angular2.dev.js?v=0.0.1:16069:37
transform@http://dev.minds.io/lib/angular2.dev.js?v=0.0.1:23275:38
detectChangesInRecordsInternal
detectChangesInRecords@http://dev.minds.io/lib/angular2.dev.js?v=0.0.1:26173:50
runDetectChanges@http://dev.minds.io/lib/angular2.dev.js?v=0.0.1:26156:40
_detectChangesInLightDomChildren@http://dev.minds.io/lib/angular2.dev.js?v=0.0.1:26217:36
runDetectChanges@http://dev.minds.io/lib/angular2.dev.js?v=0.0.1:26157:50
_detectChangesInLightDomChildren@http://dev.minds.io/lib/angular2.dev.js?v=0.0.1:26217:36
runDetectChanges@http://dev.minds.io/lib/angular2.dev.js?v=0.0.1:26157:50
_detectChangesInShadowDomChildren@http://dev.minds.io/lib/angular2.dev.js?v=0.0.1:26223:36
runDetectChanges@http://dev.minds.io/lib/angular2.dev.js?v=0.0.1:26160:51
_detectChangesInLightDomChildren@http://dev.minds.io/lib/angular2.dev.js?v=0.0.1:26217:36
runDetectChanges@http://dev.minds.io/lib/angular2.dev.js?v=0.0.1:26157:50
_detectChangesInShadowDomChildren@http://dev.minds.io/lib/angular2.dev.js?v=0.0.1:26223:36
runDetectChanges@http://dev.minds.io/lib/angular2.dev.js?v=0.0.1:26160:51
_detectChangesInLightDomChildren@http://dev.minds.io/lib/angular2.dev.js?v=0.0.1:26217:36
runDetectChanges@http://dev.minds.io/lib/angular2.dev.js?v=0.0.1:26157:50
_detectChangesInShadowDomChildren@http://dev.minds.io/lib/angular2.dev.js?v=0.0.1:26223:36
runDetectChanges@http://dev.minds.io/lib/angular2.dev.js?v=0.0.1:26160:51
detectChanges@http://dev.minds.io/lib/angular2.dev.js?v=0.0.1:26147:34
tick@http://dev.minds.io/lib/angular2.dev.js?v=0.0.1:16463:47
http://dev.minds.io/lib/angular2.dev.js?v=0.0.1:16453:29
run@http://dev.minds.io/lib/angular2.dev.js?v=0.0.1:136:22
http://dev.minds.io/lib/angular2.dev.js?v=0.0.1:16600:41
zoneBoundFn@http://dev.minds.io/lib/angular2.dev.js?v=0.0.1:109:22
lib$es6$promise$asap$$flush@http://dev.minds.io/lib/angular2.dev.js?v=0.0.1:1213:17
	logError (angular2.dev.js, line 25219)
	call (angular2.dev.js, line 20928)
	(anonymous function) (angular2.dev.js, line 27327)
	_onError (angular2.dev.js, line 16659)
	onError (angular2.dev.js, line 16579)
	run (angular2.dev.js, line 139)
	(anonymous function) (angular2.dev.js, line 16600)
	zoneBoundFn (angular2.dev.js, line 109)
	lib$es6$promise$asap$$flush (angular2.dev.js, line 1213)
```

**Comment by pkozlowski-opensource** [comment] 2015-10-01 11:37
Yes, those filters need update. This is duplicate of https://github.com/angular/angular/issues/3333

**Closed by pkozlowski-opensource** 2015-10-01 11:37 UTC
