### ISSUE TITLE
Support containerless components

### ISSUE THREAD

**Issue by HamedFathi** [angular/angular#28132] opened 2019-01-14 17:24 UTC
# 🚀 feature request

### Description
I wrote a very simple component based on Bootstrap 4 by Angular 7.

The final result is:
[![enter image description here][1]][1]
[![enter image description here][2]][2]

Everything work perfectly but in Aurelia, we can create a component **containerless**.

It is necessary for creating other components based on Bootstrap 4 that can not wrap into a non-bootstrap div element. (Angular div)

[![enter image description here][3]][3]

After investigationg in `stackoverflow` I found out we can not remove `ng-content` (containerless component). 
This is a problem to convert some Bootstrap 4 components (or other CSS frameworks) for example: 

```html
<div class="progress">
  <div class="progress-bar" role="progressbar" style="width: 15%" aria-valuenow="15" aria-valuemin="0" aria-valuemax="100"></div>
  <div class="progress-bar bg-success" role="progressbar" style="width: 30%" aria-valuenow="30" aria-valuemin="0" aria-valuemax="100"></div>
  <div class="progress-bar bg-info" role="progressbar" style="width: 20%" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100"></div>
</div>
```

We can not create two components `progress-group` and `progress` because inside dives can not accept another div (`ng-content`). Bootstrap 4 does not work in this way.

Existing `ng-content` for each component destroys the Bootstrap 4 structure I can show you another examples:

```html
<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="..." class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="..." class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="..." class="d-block w-100" alt="...">
    </div>
  </div>
```

```html
<div class="input-group mb-3">
  <div class="input-group-prepend">
    <span class="input-group-text">$</span>
  </div>
  <input type="text" class="form-control" aria-label="Amount (to the nearest dollar)">
  <div class="input-group-append">
    <span class="input-group-text">.00</span>
  </div>
</div>
```

and a lot more.

So I want to ask for **containerless (a component without `ng-content` as a wrapper) feature** for component design system. It can help us to convert a CSS framework to complete Angular toolbox.

  [1]: https://i.stack.imgur.com/rU0ed.png
  [2]: https://i.stack.imgur.com/tDs4M.png
  [3]: https://i.stack.imgur.com/UtTY7.png

**Comment by HamedFathi** [comment] 2019-01-16 04:21
@alxhub

Thanks but I know about it.
I want to hide heavy Bootstrap 4 HTML as much as possible with Angular components rather than mixing it.

**Comment by trotyl** [comment] 2019-01-16 13:33
Duplicate of https://github.com/angular/angular/issues/18877, https://github.com/angular/angular/issues/19610, https://github.com/angular/angular/issues/22208,

**Comment by pkozlowski-opensource** [comment] 2019-01-29 20:08
Duplicate of the existing issues, as @trotyl have pointed out (thnx!)

**Closed by pkozlowski-opensource** 2019-01-29 20:08 UTC
Labels: comp: core & compiler, type: feature
