### ISSUE TITLE
Is moduleId a reserved Keyword in Angular?

### ISSUE THREAD

**Issue by rahulrsingh09** [angular/angular#15286] opened 2017-03-19 10:25 UTC
export class AppComponent {
  title = 'app works!';

      constructor() {

          let test1 = {
                id: 'test',
                moduleId1: 'moduleId1',
                moduleId: 'IsThisReserverdWord',
                moduleId2: 'moduleId2'
            };

          console.log(test1.moduleId);

          let test2 = {
                moduleId: 'moduleId3',
            };
      }

It is very strange that the console log part is never hit and there is no exception. By removing the moduleId: 'IsThisReserverdWord' property it is all fine. 

Is moduleid reserved key word as when i try and print the moduleId without having any other property in test it gives undefined and also if i try and print moduleId2 in the above test object it throws error test1 is not defined.

**Comment by DzmitryShylovich** [comment] 2017-03-19 10:28
http://plnkr.co/edit/6UTClINXw8JEZPzujTqp?p=preview works like a charm

**Comment by laclac777** [comment] 2017-03-19 11:33
The issue can reproduced with a webpack CLI project.

**Comment by DzmitryShylovich** [comment] 2017-03-19 11:43
ok, re-open it on https://github.com/angular/angular-cli/issues
because I can't reproduce it neither in plunkr nor in https://github.com/AngularClass/angular2-webpack-starter

**Comment by rahulrsingh09** [comment] 2017-03-19 14:51
@DzmitryShylovich I am using AngularCli and this is not working over there

**Comment by DzmitryShylovich** [comment] 2017-03-19 16:18
> Not sure how its working for u

it's working for me because I don't use CLI.
The OP question is `Is moduleId a reserved Keyword in Angular?`. No, it's not a reversed keyword. If it doesn't work in CLI this means it's a CLI issue. https://github.com/angular/angular-cli/issues - CLI repo

**Comment by rahulrsingh09** [comment] 2017-03-19 16:27
@DzmitryShylovich  Shall i post this in Cli issues ? can i get a answer there

**Comment by DzmitryShylovich** [comment] 2017-03-19 16:29
@rahulrsingh09 yeas, please, open this in cli repo. thanks

**Comment by IgorMinar** [comment] 2017-03-20 22:47
resolving since this is being handled within the cli project

**Closed by IgorMinar** 2017-03-20 22:47 UTC
