### ISSUE TITLE
EXCEPTION: Error: Uncaught (in promise): TypeError: Cannot read property 'isSkipSelf' of null

### ISSUE THREAD

**Issue by info007** [angular/angular#8704] opened 2016-05-18 06:45 UTC
<img width="1381" alt="screen shot 2016-05-17 at 11 35 20 pm" src="https://cloud.githubusercontent.com/assets/19370275/15349562/96c5a3e6-1c88-11e6-8a76-45108350ba53.png">

<img width="543" alt="screen shot 2016-05-17 at 11 42 40 pm" src="https://cloud.githubusercontent.com/assets/19370275/15349661/56b7c97c-1c89-11e6-920b-f1e220ae8292.png">
<img width="558" alt="screen shot 2016-05-17 at 11 42 58 pm" src="https://cloud.githubusercontent.com/assets/19370275/15349662/56bbc824-1c89-11e6-80d2-5f6f12a676c8.png">

**Comment by ericmartinezr** [comment] 2016-05-18 11:50
See https://github.com/angular/angular/issues/8519

**Comment by beemsoft** [comment] 2016-05-18 19:00
Try the following:

- Replace the SearchService constructor with: 

`constructor(@Inject(forwardRef(() => Jsonp)) jsonp: Jsonp)`
- Add Jsonp to the providers list of AppComponent

**Comment by info007** [comment] 2016-05-18 20:26
No change it didn't solved problem.

**Comment by beemsoft** [comment] 2016-05-18 20:36
Strange, what happens on the console when you add SearchService to the bootstrap:
`bootstrap(AppComponent, [SearchService])`

**Comment by info007** [comment] 2016-05-18 21:20
Same error.

**Comment by rktawni** [comment] 2016-05-19 10:23
`providers:[SearchService]`

Why making AppComponent 'Injectable' when it is root component? Just make your service injectable by enter it into the providers property's array in your root component "AppComponent". `@Injectable()` is always used to make any service injectable, and to make it available same service need to be entered in providers metadata in root component.

**Comment by ecozoic** [comment] 2016-05-20 21:03
Getting the same issue here. I'm working w/ an API and I have separate services for all the API resources, and then one main service that all the separate services consume.

My setup is basically:
WidgetComponent -> WidgetService -> APIService -> Http

I get this exact error, even if my services are all decorated with @Injectable() and I have them registered as providers.  @beemsoft's solution using @Inject(forwardRef(() => APIService)) in my WidgetService constructor causes the "isSkipSelf of null" error to go away, but then all my API calls fail with net::ERR_CONNECTION_RESET. Right now I have the APIService provided at the App component level, but I have also tried at the bootstrap level as well with the same results.

Removing API Service and consuming Http directly in the Widget Service works fine.
WidgetComponent -> WidgetService -> Http

Definitely seems like a bug and I agree that the error message should be more helpful to assist.

**Comment by ecozoic** [comment] 2016-05-20 22:25
I ended up finding the solution to my problem at least

[here](https://github.com/angular/angular/issues/8519#issuecomment-218182719)

Basically I can't import my service from a barrel, I have to go to the particular file.

In other words:

`import { ApiService } from './services` does not work

`import { ApiService } from './services/api.service` does

This is with Webpack using CommonJS modules. Not sure what's going on but at least it works. Barrel files are super nice to have though.

**Comment by kingjordan** [comment] 2016-05-22 17:43
I can confirm the what @ecozoic found out.  I ended up having a circular reference to a service because the service I was using imported another service from the same folder, but I used the index.ts barrel to import it.  I changed the import statement to reference the actual file and not the barrel and it solved the problem.

**Comment by pkozlowski-opensource** [comment] 2016-06-02 17:30
Duplicate of #8519 - we've got a reproduce scenario in the other issue

**Closed by pkozlowski-opensource** 2016-06-02 17:30 UTC
Labels: hotlist: error messages

**Comment by AIon-Gbbe** [comment] 2016-07-18 15:38
I hot a similar error when using angular2 forms - data driven approach.

Here it is: " **Uncaught (in promise): TypeError: Cannot read property 'setParent' of null** "

After 3-4 hours of continuous searching and debugging I found out that my  form does not have the [formGroup]="myForm" directive on it !!
So when I tried to use my formControlName="email" without [formGroup] directive  I got this cryptic error. 
Of course this is a dumb mistake! But there was no way for me to know that I'm missing the formGroup directive!! 
So again, before trying to do debugging or anything please verify you got all the dependencies you need all the Providers, all the directives etc..

**Comment by ericmartinezr** [comment] 2016-07-18 16:26
@Alon-Gbbe that is not related this issue, but it seems a valid bug. Try the same with latest forms release and reproduce it in a plnkr, when you have that you may want to file an issue.
