### ISSUE TITLE
Custom pipe breaking

### ISSUE THREAD

**Issue by rohitjindal1991** [angular/angular#24753] opened 2018-07-04 08:17 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Custom pipe applied on both the angular expressions {{fruits}} & {{fruits  | sortStringPipe:'asc'  }} .

## Expected behavior

It should apply only on the second one  {{fruits  | sortStringPipe:'asc'  }} where i pass pipe symbol in the expression.

## Minimal reproduction of the problem with instructions

> mypipecomponent.component.ts

```
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'cts-mypipecomponent',
  templateUrl: './mypipecomponent.component.html',
  styleUrls: ['./mypipecomponent.component.css']
})
export class MypipecomponentComponent implements OnInit {

  fruits = ['mango','apple','banana','papaya','kiwi']

  constructor() { }

  ngOnInit() {
  }

}
```

> Custom pipe (sort-string-pipe.pipe.ts)

```
import { Pipe, PipeTransform } from '@angular/core';

@Pipe({
  name: 'sortStringPipe'
})
export class SortStringPipePipe implements PipeTransform {

  transform(value: any, args?: any): any {

    if(args === 'asc'){
      return value.sort()    

    }
    if(args === 'dsc'){
      return value.sort().reverse()
    }

    return value.sort();

  }

}
```

> mypipecomponent.component.html

```
Unsorted Fruits: {{fruits}}
Sorted Fruits: {{fruits  | sortStringPipe:'asc'  }}
```

**Output :**

`Unsorted Fruits: apple,banana,kiwi,mango,papaya Sorted Fruits: apple,banana,kiwi,mango,papaya`

## What is the motivation / use case for changing the behavior?

If i pass any HTML element like <hr>,<br> between both the expressions then it is working but i do not want to use these elements between the expressions.

## Environment

<pre><code>
Angular version: 6.0.7

Browser:
- [x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x ] Firefox version XX
- [x ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 9.7.1  
- Platform: Windows 

Others:

</code></pre>

**Comment by pkozlowski-opensource** [comment] 2018-07-04 08:36
> The sort() method sorts the elements of an array _in place_ and returns the array. 

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort

You are sorting a _shared_ array instance so all the parts of the UI will show a sorted version.

Closing this one as it has nothing to do with Angular pipes but rather how  `Array.sort` behaves.

**Closed by pkozlowski-opensource** 2018-07-04 08:36 UTC

**Comment by rohitjindal1991** [comment] 2018-07-04 09:51
@pkozlowski-opensource If it is a sort() method behaviour than why it is working fine if i put `<br>` or `<hr>` element between two expressions. It is a bug.

**Comment by pkozlowski-opensource** [comment] 2018-07-04 09:54
@rohitjindal1991 if you believe that this is a bug please provide _minimal_ reproduce scenario in stackblitz as requested in the issue template. I've commented based on the info provided in the issue.

**Comment by rohitjindal1991** [comment] 2018-07-04 10:17
@pkozlowski-opensource I added reproduce scenario link using stackblitz. Please have a look.

**Comment by rohitjindal1991** [comment] 2018-07-04 10:29
@pkozlowski-opensource See this modified stackblitz that shows if i removed `<br>` from first line. It modifies first line as per the pipe without using pipe.

https://stackblitz.com/edit/angular-gitter-mzpzkm?file=app/app.component.html

**Comment by pkozlowski-opensource** [comment] 2018-07-04 10:32
@rohitjindal1991 sure, because you are in one text node so it is updated in one go with a sorted array (expression are executed first, than DOM is updated).

Again and again, your fundamental problem is that sorting is modifying the data model.

**Comment by rohitjindal1991** [comment] 2018-07-04 10:40
@pkozlowski-opensource But why it has been gone after using `<br>` that is only concern. If it modified all the arrays having same address using Array.sort(). It should be happen with `<br>` as well but it is behaving differently.

**Comment by trotyl** [comment] 2018-07-04 11:10
Duplicate of https://github.com/angular/angular/issues/22604

**Comment by rohitjindal1991** [comment] 2018-07-05 04:48
@trotyl It is not a duplicate of #22604 as here behaviour are different with adding HTML element between the two angular expression.

**Comment by trotyl** [comment] 2018-07-05 04:50
@rohitjindal1991 Please read the thread rather than title, thanks.

**Comment by rohitjindal1991** [comment] 2018-07-05 06:20
@trotyl Thanks for the explanation. It helps a lot to understand the concept of partial binding with `node`. With `<br>` in between they're are behaving as two individual Texts, so unrelated.
