### ISSUE TITLE
[compiler-cli]: AOT build use @angular/forms/src/directives/number_value_accessor and cannot find it

### ISSUE THREAD

**Issue by Delagen** [angular/angular#12428] opened 2016-10-21 08:47 UTC
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
2.1.0 version does not include @angular/forms/src/directives/number_value_accessor in generated factories
2.1.1 include it but in genDir/node_modules/@angular... this file is missing

**Expected behavior**
Compiling as was

* **Angular version:** 2.1.1
 
* **Language:** Typescript 2.03

* **Node (for AoT issues):** `node --version` =   6.9.1

**Comment by DzmitryShylovich** [comment] 2016-10-21 09:18
Can u pls provide repo with reproduction?

**Comment by SamVerschueren** [comment] 2016-10-21 10:09
Experiencing the same issue. It happens when you have a form element that has `input type="number"`.

**Comment by SamVerschueren** [comment] 2016-10-21 10:31
Created a repository that reproduces this bug.

https://github.com/SamVerschueren/angular2-number-value-accessor-bug

**Comment by tbosch** [comment] 2016-10-21 19:55
This seems to be a duplicate of https://github.com/angular/angular/issues/11889. That previous bug was only about components. However, as we now also generate `.ngfactory.ts` files for directives, this bug becomes more severe.

**Comment by Delagen** [comment] 2016-10-22 06:06
@tbosch No. it appear only in 2.1.1, before all works well, Number Value Accessor missing before 2.1.1 both in generated factories and in forms module

**Closed** 2016-10-24 20:28 UTC
Labels: comp: forms
