### ISSUE TITLE
Instantiating components programmatically, doesn't instantiate possible matching directives

### ISSUE THREAD

**Issue by alirezamirian** [angular/angular#17165] opened 2017-06-01 20:28 UTC
**I'm submitting a**
- [x] bug report
- [ ] feature request
- [ ] support request

**Current behavior**
When instantiating a component with [ViewContainerRef.createComponent()](https://angular.io/docs/ts/latest/api/core/index/ViewContainerRef-class.html#!#createComponent-anchor), if component has a selector, and there are also directives that match the component selector, they don't get instantiated.

**Expected behavior**

All matching directives should get instantiated along with the component instantiation.

**Minimal reproduction of the problem with instructions**
This plunk: https://plnkr.co/edit/1oLA6HkAuOTgwOPMseG2?p=preview

**What is the motivation / use case for changing the behavior?**

Creating component from **template**, or **programmatically** is a matter of use case and should result in the same outcome as much as possible. Although there is no support for explicitly applying a custom set of directives on the instantiated component when working with `ViewContainerRef.createComponent()`, and it may be too complicated to add support for it, the case when component selector matches some other directives can and need to be handled.

The specific use case in which I encountered the issue:
I was creating a structural `*myLoading="condition"` directive, which simply renders a spinner if the condition is true or renders the host element otherwise. I was using [MdProgressSpinner](https://material.angular.io/components/component/progress-spinner) component for the spinner but the stroke color was not applying because the theme related classes are adding via a directive with exact same selector as the component selector.
I created a [simple plunk](https://plnkr.co/edit/DLJoA3L40p7WLSxcoDO4?p=preview) for this example.

 
**Please tell us about your environment:**

Not related actually.

* **Angular version:** 4.1.3

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by alirezamirian** [comment] 2017-06-01 20:48
BTW, I know the `*appLoading` can be handled with a component instead of a directive in a much simpler and declarative way, I was trying to learn and play with structural directives.

**Comment by tbosch** [comment] 2017-06-01 22:30
This is a duplicate of https://github.com/angular/angular/issues/8785.

**Closed by tbosch** 2017-06-01 22:30 UTC
Labels: comp: core & compiler
