### ISSUE TITLE
Angular Form Inputs are memory leaking.

### ISSUE THREAD

**Issue by burdokat** [angular/angular#37598] opened 2020-06-15 23:15 UTC
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/forms
Unable to confirm if it is related to other packages.

### Is this a regression?
No, the previous angular 8 version does not present this issue.

### Description

Any instances pertaining the form keeps piling up in memory. Hence, everything else from the form up to its container (component, modal, or anything else) are not being garbage collected. Hence, memory is hugely leaking (See image below of nodes piling up).
A very simple sample demo has been uploaded as an example to represent this issue in its minimum expression. It is a very simple two page app: an auth page with a single input field (template driven form) and the explore page to simplify things up. There are 2 buttons inside the auth page; one of them is the submit button of the form. Both buttons navigate to the explore page. (Is done this way to detect the possible issue). 
The explore page has a button to navigate back to the auth page and close the loop. 

To prove the issue, we navigate back and forth using only the buttons (completely ignoring the input field). 
We just keep routing back and forth pressing the buttons. The result is the expected behaviour where garbage is collected.
This also proves that the issue is unrelated to the router.

![image](https://user-images.githubusercontent.com/20394220/84711021-00cb4f00-af2b-11ea-8939-5d23e895b9b3.png)
![image](https://user-images.githubusercontent.com/20394220/84711492-1f7e1580-af2c-11ea-9abd-87bba4a84baa.png)

PROBLEM DETECTED:
The memory leaks bubbles out whenever the form is dirty, in other words, when something is typed in the input field and the form is dirty before navigating. If we navigate back and forth and we keep typing in the simple input field, then the memory leak clarifies.

First Iteration:
![image](https://user-images.githubusercontent.com/20394220/84711267-8b13b300-af2b-11ea-978f-0b35c11e0a64.png)
![image](https://user-images.githubusercontent.com/20394220/84711440-fe1d2980-af2b-11ea-90d7-ff879a1bc94d.png)
![image](https://user-images.githubusercontent.com/20394220/84714593-c1553080-af33-11ea-8fa5-82285e3574ed.png)

Second Iteration:
![image](https://user-images.githubusercontent.com/20394220/84711378-d037e500-af2b-11ea-93b4-1b88b7bbc366.png)
![image](https://user-images.githubusercontent.com/20394220/84711459-08d7be80-af2c-11ea-9553-91287fab404c.png)
![image](https://user-images.githubusercontent.com/20394220/84714614-cd40f280-af33-11ea-9bd8-391f3bbaf258.png)

(Please note that this demo was created solely to describe and mark up this bug behavior. The actions described here may not represent actual practical uses for angular forms. But in essence, this memory leak can be a huge performance issue for any angular application using @angular/forms, if certain conditions are met.)

## 🔬 Minimal Reproduction
Please check the link to the git repository below where the sample demo code is published:
https://github.com/burdokat/Angular9SimpleFormBugDemo

## 🔥 Exception or Error
No exception or error thrown.

## 🌍  Your Environment

**Angular Version:**

Angular CLI: 9.1.8
Node: 12.16.3
OS: win32 x64

Angular: 9.1.11
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.8
@angular-devkit/build-angular     0.901.8
@angular-devkit/build-optimizer   0.901.8
@angular-devkit/build-webpack     0.901.8
@angular-devkit/core              9.1.8
@angular-devkit/schematics        9.1.8
@angular/cli                      9.1.8
@ngtools/webpack                  9.1.8
@schematics/angular               9.1.8
@schematics/update                0.901.8
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0

**Anything else relevant?**
Unable to confirm if this is a browser specific issue.
IMPORTANT. The same behaviour is exhibited in reactive driven forms too.

This may be related to other bugs see https://github.com/angular/angular/issues/37576, https://github.com/angular/angular/issues/37431 
(Requires more thorough investigation).

**Comment by AndrewKushnir** [comment] 2020-06-17 05:43
Hi @burdokat, thanks for reporting the issue and providing a repro.

I'm working on a PR #37566 that contains changes to perform the cleanup after Forms-related directives are destroyed. Could you please try to test the scenario with the code from that PR to check if you still see the memory leak?

To test your demo app with the changes from that PR, you can follow an instruction in [this document on how to use PR artifacts](https://github.com/angular/angular/blob/master/docs/DEVELOPER.md#archives-for-each-package). An archive with updated `@angular/forms` package that contains changes from the PR is available [here](https://738015-24195339-gh.circle-artifacts.com/0/angular/forms-pr37566-f3b3239d71.tgz). **Note**: the mentioned archive with updated `@angular/forms` package is for **testing purposes only** and not suitable for production usage (that archive will be removed once this PR is closed).

Thank you.

**Comment by capc0** [comment] 2020-07-28 11:53
related https://github.com/angular/angular/issues/37952

**Comment by jelbourn** [comment] 2020-10-12 22:15
Duplicate of #20007

**Closed by jelbourn** 2020-10-12 22:15 UTC
Labels: P3, comp: forms, memory leak, state: confirmed, type: bug/fix
