### ISSUE TITLE
App does not compile with Ivy - Angular 9

### ISSUE THREAD

**Issue by whyboris** [angular/angular#32466] opened 2019-09-03 18:54 UTC
# 🐞 Bug report

### Command (mark with an `x`)
- [x] serve

### Is this a regression?

Production app builds with version 8, fails with version 9 and *IVY enabled*

### Description

Everything in this ticket is about/with the experimental *Ivy* enabled.

## 🔬 Minimal Reproduction

Sorry unsure what the problem is. Part of the behavior is documented here:
https://github.com/swimlane/ngx-datatable/issues/1699#issuecomment-520957242

With AngularCLI `8.3.0-next.1`
The error was:
> ERROR in node_modules/@swimlane/ngx-datatable/release/datatable.module.d.ts(1,22): error TS-996002: Appears in the NgModule.imports of AdminModule, but could not be resolved to an NgModule class

But after updating, with AngularCLI `9.0.0-next.1` I get a different output I am unable to discern:

## 🔥 Exception or Error

![image](https://user-images.githubusercontent.com/17264277/64199542-87111b80-ce58-11e9-892a-fa26648fdc44.png)

```
ERROR in Error: Assertion error: failed to find directive with exportAs: ngForm
    at /Users/byakubchik/Desktop/WIP/angular8/node_modules/@angular/compiler/bundles/compiler.umd.js:28444:31
    at Array.forEach (<anonymous>)
    at DirectiveBinder.visitElementOrTemplate (/Users/byakubchik/Desktop/WIP/angular8/node_modules/@angular/compiler/bundles/compiler.umd.js:28427:29)
    at DirectiveBinder.visitElement (/Users/byakubchik/Desktop/WIP/angular8/node_modules/@angular/compiler/bundles/compiler.umd.js:28401:76)
    at Element.visit (/Users/byakubchik/Desktop/WIP/angular8/node_modules/@angular/compiler/bundles/compiler.umd.js:4132:71)
    at /Users/byakubchik/Desktop/WIP/angular8/node_modules/@angular/compiler/bundles/compiler.umd.js:28473:67
    at Array.forEach (<anonymous>)
    at DirectiveBinder.visitElementOrTemplate (/Users/byakubchik/Desktop/WIP/angular8/node_modules/@angular/compiler/bundles/compiler.umd.js:28473:27)
    at DirectiveBinder.visitElement (/Users/byakubchik/Desktop/WIP/angular8/node_modules/@angular/compiler/bundles/compiler.umd.js:28401:76)
    at Element.visit (/Users/byakubchik/Desktop/WIP/angular8/node_modules/@angular/compiler/bundles/compiler.umd.js:4132:71)
    at /Users/byakubchik/Desktop/WIP/angular8/node_modules/@angular/compiler/bundles/compiler.umd.js:28473:67
    at Array.forEach (<anonymous>)
    at DirectiveBinder.visitElementOrTemplate (/Users/byakubchik/Desktop/WIP/angular8/node_modules/@angular/compiler/bundles/compiler.umd.js:28473:27)
    at DirectiveBinder.visitTemplate (/Users/byakubchik/Desktop/WIP/angular8/node_modules/@angular/compiler/bundles/compiler.umd.js:28402:78)
    at Template.visit (/Users/byakubchik/Desktop/WIP/angular8/node_modules/@angular/compiler/bundles/compiler.umd.js:4150:72)
    at /Users/byakubchik/Desktop/WIP/angular8/node_modules/@angular/compiler/bundles/compiler.umd.js:28473:67
```

## 🌍 Your Environment
<pre><code>
Angular CLI: 9.0.0-next.2
Node: 12.6.0
OS: darwin x64
Angular: 9.0.0-next.4
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-next.2
@angular-devkit/build-angular     0.900.0-next.2
@angular-devkit/build-optimizer   0.900.0-next.2
@angular-devkit/build-webpack     0.900.0-next.2
@angular-devkit/core              9.0.0-next.2
@angular-devkit/schematics        9.0.0-next.2
@angular/cli                      9.0.0-next.2
@angular/http                     7.2.15
@ngtools/webpack                  9.0.0-next.2
@nguniversal/express-engine       7.1.1
@schematics/angular               9.0.0-next.2
@schematics/update                0.900.0-next.2
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.39.3
</code></pre>

**Anything else relevant?**
Will be happy to clarify more. 
The original problem preventing the app from compiling was the inclusion of three libraries

- ngx-datatable - https://github.com/swimlane/ngx-datatable/issues/1699#issuecomment-520957242
- mydatepicker - https://www.npmjs.com/package/mydatepicker (no new versions since > 1 year ago)
- ng2-charts - https://www.npmjs.com/package/ng2-charts (haven’t tried their latest version yet)

🤷‍♂ 
Tagging @StephenFluin for reference 🙇

**Comment by whyboris** [comment] 2019-09-05 16:13
I am getting very inconsistent behavior, with the latest versions NOW:

I wish someone else can confirm -- in our project with the _latest_ versions of _angular_ and `ngx-datatable` v`16.0.0` I get this error now:
```
An unhandled exception occurred: Cannot destructure property `createHash` of 'undefined' or 'null'.
See "/private/var/folders/32/pqw73fv945dcd6n_g619n7f8c_tzhw/T/ng-qSFBT3/angular-errors.log" for further details.
```
Above `.log` file:
```
[error] TypeError: Cannot destructure property `createHash` of 'undefined' or 'null'.
    at Object.<anonymous> (/Users/byakubchik/Desktop/WIP/angular8/node_modules/mini-css-extract-plugin/dist/index.js:22:9)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/Users/byakubchik/Desktop/WIP/angular8/node_modules/mini-css-extract-plugin/dist/cjs.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/Users/byakubchik/Desktop/WIP/angular8/node_modules/@angular-devkit/build-angular/src/angular-cli-files/models/webpack-configs/styles.js:14:30)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
```

**Comment by whyboris** [comment] 2019-09-06 16:20
Checked again with latest:
```
Angular CLI: 9.0.0-next.3
Node: 12.10.0
OS: darwin x64
Angular: 9.0.0-next.5
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-next.3
@angular-devkit/build-angular     0.900.0-next.3
@angular-devkit/build-optimizer   0.900.0-next.3
@angular-devkit/build-webpack     0.900.0-next.3
@angular-devkit/core              9.0.0-next.3
@angular-devkit/schematics        9.0.0-next.3
@angular/cli                      9.0.0-next.3
@angular/http                     7.2.15
@ngtools/webpack                  9.0.0-next.3
@nguniversal/express-engine       7.1.1
@schematics/angular               9.0.0-next.3
@schematics/update                0.900.0-next.3
rxjs                              6.5.2
typescript                        3.4.5
webpack                           3.8.1
```
Someone in another comment: https://github.com/swimlane/ngx-datatable/issues/1699#issuecomment-528496318 suggested that the latest error I am getting (`Cannot destructure property `createHash` of 'undefined' or 'null'.`) may stem from webpack 🤷‍♂ 

I see webpack `3.8.1` (which is 2 years old) ... and I don't have it in my `package.json`, in the `package-lock.json` I see it's required by `react-scripts` which is in turn required by something else. `@angular-devkit/build-angular` is using `4.39.3` which seems like everything should be fine ... but I don't know if there's some weird mis-behavior because of this 🤷‍♂ 

Please let me know if I can clarify anything 🙇

**Comment by JoostK** [comment] 2019-09-10 20:05
Hi @whyboris,

Thanks so much for putting together this issue! I am looking into `ngx-datatable` right now, that seems to be compiling correctly for me right now. I'm using 16.0.2 together with Angular bbd4a33 (a commit from today). The compilation failures you're seeing might be related to the fix being done in #32539, however I can't know for sure as I don't have a reproduction available.

Can you share a repro (may be in private) for me to investigate? Alternatively if that's not possible, do you have a clue on which template is failing compilation? If so,  we might be able to come up with a reproduction. Thanks again!

**Comment by whyboris** [comment] 2019-09-11 16:26
Update:
Now the app compiles with these: 
- `"enableIvy": true` in `tsconfig.json` 
- `"aot": false` in `angular.json`

To get here I temporarily rolled back to `"@angular-devkit/build-angular": "^0.803.3",`, and set `enableIvy` and `aot` to `false`: discovered I needed to undo adding webpack in package.json (as I did last week as an experiment) - everything compiled. I then updated to `"@angular-devkit/build-angular": "^0.900.0-next.3",` and saw that I needed to add `"@angular/localize": "9.0.0-next.5",` (and `import '@angular/localize'` to `polyfills.ts`) 🎉 (found out because chrome console was showing a message). Along the way CLI complained with numerous lines like:
```
WARNING in /Users/byakubchik/Desktop/WIP/angular8/src/fixtures/quill/FakeIInsert.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.
```
But at this point everything was compiling. I did `"enableIvy": true` and it worked (app compiles, works, etc), but when I did `"aot": true` it failed:
```
ERROR in Error: Assertion error: failed to find directive with exportAs: ngForm
    at /Users/byakubchik/Desktop/WIP/angular8/node_modules/@angular/compiler/bundles/compiler.umd.js:28622:31
    at Array.forEach (<anonymous>)
    at DirectiveBinder.visitElementOrTemplate (/Users/byakubchik/Desktop/WIP/angular8/node_modules/@angular/compiler/bundles/compiler.umd.js:28605:29)
    at DirectiveBinder.visitElement (/Users/byakubchik/Desktop/WIP/angular8/node_modules/@angular/compiler/bundles/compiler.umd.js:28579:76)
    at Element.visit (/Users/byakubchik/Desktop/WIP/angular8/node_modules/@angular/compiler/bundles/compiler.umd.js:4159:71)
    at /Users/byakubchik/Desktop/WIP/angular8/node_modules/@angular/compiler/bundles/compiler.umd.js:28651:67
    at Array.forEach (<anonymous>)
    at DirectiveBinder.visitElementOrTemplate (/Users/byakubchik/Desktop/WIP/angular8/node_modules/@angular/compiler/bundles/compiler.umd.js:28651:27)
    at DirectiveBinder.visitElement (/Users/byakubchik/Desktop/WIP/angular8/node_modules/@angular/compiler/bundles/compiler.umd.js:28579:76)
    at Element.visit (/Users/byakubchik/Desktop/WIP/angular8/node_modules/@angular/compiler/bundles/compiler.umd.js:4159:71)
    at /Users/byakubchik/Desktop/WIP/angular8/node_modules/@angular/compiler/bundles/compiler.umd.js:28651:67
    at Array.forEach (<anonymous>)
    at DirectiveBinder.visitElementOrTemplate (/Users/byakubchik/Desktop/WIP/angular8/node_modules/@angular/compiler/bundles/compiler.umd.js:28651:27)
    at DirectiveBinder.visitTemplate (/Users/byakubchik/Desktop/WIP/angular8/node_modules/@angular/compiler/bundles/compiler.umd.js:28580:78)
    at Template.visit (/Users/byakubchik/Desktop/WIP/angular8/node_modules/@angular/compiler/bundles/compiler.umd.js:4177:72)
    at /Users/byakubchik/Desktop/WIP/angular8/node_modules/@angular/compiler/bundles/compiler.umd.js:28651:67
```

**Comment by whyboris** [comment] 2019-09-11 16:42
I thought I checked `ngForm` across our codebase and I thought we had many, but turns out it exists only once! `#myForm="ngForm"` so when I removed it the app got further in compilation, erring out dozens of times with errors like:
```
app/dashboard/insights/insights.component.html:71:33 - error TS8002: 'name' is not a valid property of <app-svg-icon>.

<app-svg-icon class="arrow" [name]="'svg-arrow'"></app-svg-icon>
```
Despite the `app-svg-icon` component having `@Input() name: string;` in the component 😕

**Comment by JoostK** [comment] 2019-09-11 16:54
So it seems as if the component that fails compilation has trouble resolving its module scope. That determines which directives/components it can see, and apparently it's empty as the `'name' is not a valid property of <app-svg-icon>.` message is produced by the template type checker for elements that were not matched by any component. I reckon, based on its name, that `app-svg-icon` is **not** in a library, but just application code?

**Comment by whyboris** [comment] 2019-09-11 16:55
Yes `app-svg-icon` is a component we created to house our SVGs 👍 not an external library

**Comment by JoostK** [comment] 2019-09-11 17:00
Okay, thanks. That's actually surprising, as ngcc shouldn't be involved in that case (which is usually the culprit when it comes to Ivy not working as desired). I can't think of any causes from the top of my head, are you able to extract a minimum working example, e.g. as a Github repo so we can investigate?

**Comment by whyboris** [comment] 2019-09-11 17:01
I'll try. What's puzzling are errors like `'ngClass' is not a valid property of <span>.` 😖

**Comment by whyboris** [comment] 2019-09-17 21:03
@JoostK minimal reproduction: https://github.com/angular/angular/issues/32729

thank you for your time 🙇

**Comment by compeek** [comment] 2019-09-17 21:26
I already commented in your other issue (https://github.com/angular/angular/issues/32729), so but I would suggest the same things here, so please see that comment: https://github.com/angular/angular/issues/32729#issuecomment-532407017

I am not using the same third party libraries you are, but I've had some of the same errors, such as `Appears in the NgModule.imports of AdminModule, but could not be resolved to an NgModule class`.

The two things I mentioned in the other issue seem to have resolved these errors for me, although I don't fully understand why.

**Comment by whyboris** [comment] 2019-09-18 18:00
@JoostK I created another minimal reproduction of the error, this time with the 2nd library that's causing trouble: https://github.com/angular/angular/issues/32748

**Comment by JoostK** [comment] 2019-09-18 18:13
Thanks so much @whyboris. I'm in London for Angular Connect at the moment so won't be able to look into it immediately, expect an update during the weekend.

**Comment by whyboris** [comment] 2019-09-18 18:32
Please no rush 👌at work we don't intend to upgrade to Angular 9 until at least a few months after its release.

**Comment by JoostK** [comment] 2019-09-26 19:56
Sorry, I've lost a bit track of what the state of this is now, after having diagnosed why `mydatepicker` did not work. Is this still an issue with the other date library?

**Comment by whyboris** [comment] 2019-09-28 15:27
Thank you @JoostK 🙇 

I think it's acceptable for new major releases of Angular to stop supporting outdated versions of libraries. 

In my case there were three, each fixed with newer releases:
- upgrade ` mydatepicker` to its successor `angular-mydatepicker` (by the same author!) ✅ 
- upgrade `ng2-charts` version `1.6.0` to latest `2.3.0` ✅ 
- upgrade `ngx-datatable` to `16.0.1` ✅ 

Had we been keeping our library versions up to date at work, we wouldn't have run into this complicated mess of errors. I hope the time everyone spent working through this and related issues wasn't wasted time 🙇 

This issue can be closed if there's nothing valuable to work through. Perhaps during Angular 9 release it's worth making public that some old versions of libraries might not work and some library upgrades might be needed.

❤️

**Closed** 2019-10-01 20:34 UTC
Labels: comp: ivy, comp: ngcc, freq2: medium, hotlist: devrel, severity3: broken, type: bug/fix
