### ISSUE TITLE
ng build in prod doesn't throw error if html is invalid

### ISSUE THREAD

**Issue by muneer-memon** [angular/angular#22019] opened 2018-02-05 05:43 UTC
## I'm submitting a...
<pre><code>
[x] Bug report 
</code></pre>

## Current behavior
while building in prod mode it went successful although Html is invalid

## Expected behavior
it should through error message

## Minimal reproduction of the problem with instructions
Steps to Reproduce:
Add html button on page with ) before closing tag

http://plnkr.co/edit/K6JgcQsuFBfTMFi4juFQ?p=preview

## What is the motivation / use case for changing the behavior?
Its very difficult to find it from html or if you have many components having many changes

## Environment
Angular version: 4

Browser:
- [ ] Chrome (desktop) Version 63.0.3239.132 (Official Build) (64-bit)

**Comment by trotyl** [comment] 2018-02-05 06:04
```html
<button type="button" id="reset" )>Reset</button>
``` 

This is [**totally valid HTML**](https://html.spec.whatwg.org/multipage/syntax.html#syntax-attribute-name), means an attribute named `)` without any value.

But still it should be reported as an unknown attribute under default schema config.

**Comment by IgorMinar** [comment] 2018-02-05 14:04
while valid html, it's unlikely that it was intentionally written in this way. we already enforce a stricter subset of html via our compiler, so it's not too crazy to say that we shouldn't report this as an error or at least as a warning.

**Comment by trotyl** [comment] 2018-02-17 06:42
Duplicate of #3425

**Closed** 2018-02-26 15:06 UTC
Labels: comp: core & compiler, type: feature
