### ISSUE TITLE
IE11 - Function.prototype.toString: 'this' is not a Function object

### ISSUE THREAD

**Issue by regnete** [angular/angular#39672] opened 2020-11-13 10:45 UTC
This issue is pending since a long time and I know that support for IE 11 is not in your primary focus. But this issue is a showstoper for angular on IE 11.

The issue occurs whenever window is extended.

The steps to reproduce were _Originally posted by @hansmaad in https://github.com/angular/angular/issues/31678#issuecomment-622976785_

I shifted them up to the current level:

Follow these steps to reproduce:

```
npm i @angular/cli
ng new repro --directory .
```

add IE 11 to browserlist

Add a module:
```
ng g m test
```
Define the module as:

```
import {Injectable, ModuleWithProviders, NgModule} from '@angular/core';
import { CommonModule } from '@angular/common';

Injectable()
export class WindowWrapper extends Window {
}

@NgModule({
  imports: [CommonModule],
  declarations: [],
})
export class TestModule {
  static forRoot(): ModuleWithProviders<any> {
    return {
      ngModule: TestModule,
      providers: [
        {
          provide: WindowWrapper,
          useValue: window
        }
      ]
    }
  }
}

```

Import the module in AppModule (just add the following line ad the end)

```
TestModule.forRoot()
```

```
npm run build
npx live-server ./dist/repro
```

open in IE 11

System Info:

Angular CLI: 11.0.1
Node: 10.21.0
OS: win32 x64

Angular: 11.0.0
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.1
@angular-devkit/build-angular   0.1100.1
@angular-devkit/core            11.0.1
@angular-devkit/schematics      11.0.1
@angular/cli                    11.0.1
@schematics/angular             11.0.1
@schematics/update              0.1100.1
rxjs                            6.6.3
typescript                      4.0.5

It would be great if someone could provide a solution or workarround for this.

**Comment by JiaLiPassion** [comment] 2020-11-13 20:19
@regnete, the root cause is here https://github.com/babel/babel/issues/8915, even we can resolve this `toString` issue, it still failed, since you can not call `super` on an object, so I don't think currently `class WindowWrapper extends Window` will work, so what is your use case to use a `WindowWrapper`?

**Comment by regnete** [comment] 2020-11-16 08:10
@JiaLiPassion, tahnak you for the quick reply. We are implementing an angular app (pdf viewer) for use in cordova and major browsers incl. IE11. I'll have a talk with the responsible developers to check out if they may avoid this pattern. Will come back to you soon.

**Comment by regnete** [comment] 2020-11-16 09:11
@JiaLiPassion, after further investogation I found out that we aren't using "extends window". We are using customElements (which use "extends HTMLElement") and they are breaking the IE11 compatibility.

Follow these steps to reproduce:

```
npm i @angular/cli
ng new repro --directory .
npm i @angular/elements
```

add IE 11 to browserlist


Define the app module as:

```ts
import { BrowserModule } from '@angular/platform-browser';
import {DoBootstrap, Injector, NgModule} from '@angular/core';

import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';
import {createCustomElement} from "@angular/elements";

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    AppRoutingModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule implements DoBootstrap {

  constructor(private injector: Injector) {
    const c = createCustomElement(AppComponent, {injector});
    customElements.define('my-component', c);
  }

  ngDoBootstrap() {
  }
}
```

build & serve
```
npm run build
npx live-server ./dist/repro
```

open in IE 11

**Comment by JiaLiPassion** [comment] 2020-11-20 20:19
@regnete, you need to install the polyfills.

```
npm i @webcomponents/custom-elements --save
```

add the following line in the `polyfills.ts`.

```
import '@webcomponents/custom-elements/custom-elements.min';
```

add the scripts to `angular.json` 

```
"scripts": [
  "node_modules/@webcomponents/custom-elements/src/native-shim.js"
]
```

I have tested it, and it works with your test code.

**Comment by regnete** [comment] 2020-11-22 14:28
@JiaLiPassion, thanks for the quick reply. Hopefully that will fix our issues. 

Anyway I expected the angualr cli to automatically solve this issue by injecting the polyfilles and shims to the es5 bundle. Am I wrong with this expectation?

**Comment by Vladlan** [comment] 2020-11-25 16:47
> @regnete, you need to install the polyfills.
> 
> ```
> npm i @webcomponents/custom-elements --save
> ```
> 
> add the following line in the `polyfills.ts`.
> 
> ```
> import '@webcomponents/custom-elements/custom-elements.min';
> ```
> 
> add the scripts to `angular.json`
> 
> ```
> "scripts": [
>   "node_modules/@webcomponents/custom-elements/src/native-shim.js"
> ]
> ```
> 
> I have tested it, and it works with your test code.

Didn't help.

**Comment by Vladlan** [comment] 2020-11-25 16:52
![Problem](https://user-images.githubusercontent.com/20605638/100258131-bc22f580-2f57-11eb-8408-5eac479876ba.PNG)

**Comment by JiaLiPassion** [comment] 2020-11-26 13:08
@Vladlan , could you provide a reproduce repo?

**Comment by Vladlan** [comment] 2020-11-30 10:34
@JiaLiPassion https://github.com/Vladlan/angular-with-stencil . This is not exactly the same repo and has a little bit different errors, but still not working in IE-11. Thanks in advance.

**Comment by jelbourn** [comment] 2020-12-02 16:37
To clarify- is this only an issue when using custom elements with IE11?

**Comment by regnete** [comment] 2020-12-02 17:28
as far as I know: Yes

**Comment by Vladlan** [comment] 2020-12-03 19:50
@JiaLiPassion 
Excluded all files from a project and just started adding them chunk by chunk and found that this error is just because of enums)))
![problem2](https://user-images.githubusercontent.com/20605638/101080361-c5483e00-35b9-11eb-9060-80ae81066018.PNG)

**Comment by Vladlan** [comment] 2020-12-03 19:51
@JiaLiPassion do you have any idea why this could happen?

**Comment by JiaLiPassion** [comment] 2020-12-04 18:20
@Vladlan , I can run your sample in `IE11` successfully after some modificaiton since your project can not build.

![Screen Shot 2020-12-05 at 3 17 46](https://user-images.githubusercontent.com/1442575/101199632-85ac4f80-36a8-11eb-9b5a-e40dcf4d5dcf.png)

1. Make sure you install `core-js` 

2. and also config 

```
  extras: {
    cssVarsShim: true,
    dynamicImportShim: true,
    safari10: true,
    shadowDomShim: true,
  },
```

in the `stencil` config, I am not familiar with stencil

**Comment by JiaLiPassion** [comment] 2020-12-04 18:21
@regnete , 

> Anyway I expected the angular cli to automatically solve this issue by injecting the polyfills and shims to the es5 bundle. Am I wrong with this expectation?

Yeah, that will be great, I will create an issue in Angular CLI, and I will close this issue here.

**Closed by JiaLiPassion** 2020-12-04 18:21 UTC
Labels: P4, browser: ie 11, comp: core
