### ISSUE TITLE
Binding to input type property causing number value accessor to not work

### ISSUE THREAD

**Issue by MRamos62786** [angular/angular#15837] opened 2017-04-07 21:47 UTC
**I'm submitting a bug**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Binding to an input's type causes number value accessor in forms to not work as expected.

**Expected behavior**
Same as when not binding to the input's type.

**Minimal reproduction of the problem with instructions**
1. Run [Plunker](http://plnkr.co/edit/xGC5O6G86qunGbxBwTRH)
2. Enter number in left input, note "Type of age" is number.
3. Modify number in right input, note "Type of age" is now a string.

**What is the motivation / use case for changing the behavior?**
I would be more convenient to not have to parse the string. In a simple form, parsing the string into a number is not a problem. The problem arises when you have more complex forms that are being generated at run-time. Ideally, once a form is valid, I want to be able to just access it's value, JSON stringify it, and POST it to some API without having to muck about with it.

**Please tell us about your environment:**
I don't think it matters for this issue.

* **Angular version:** 2.0.X
Version 4.0.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome 57.0.2987.133
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 2.2

**Comment by trotyl** [comment] 2017-04-08 07:16
It's the expected behavior. (Or design limit?)

All directives are determined at compilation time, changing the attribute/property won't affect the existence of directives which match the original selector.

In template-driven form, the [ControlValueAccessor](https://github.com/angular/angular/blob/master/packages/forms/src/directives/control_value_accessor.ts#L21-L44)s are all directives like [NumberValueAccessor](https://github.com/angular/angular/blob/master/packages/forms/src/directives/number_value_accessor.ts#L28-L58) and [DefaultValueAccessor](https://github.com/angular/angular/blob/master/packages/forms/src/directives/default_value_accessor.ts#L45-L98).

Since the accessor is determined at compilation time, it won't affect the data-binding mechanism by changing the signature of element to match another selector in runtime.

BTW, it's a duplicate of https://github.com/angular/angular/issues/7329, https://github.com/angular/angular/issues/8392, https://github.com/angular/angular/issues/9837, https://github.com/angular/angular/issues/12025, https://github.com/angular/angular/issues/13243. Please consider `search github for a similar issue or PR before submitting` first as suggested in issue template.

**Comment by tbosch** [comment] 2017-04-08 16:42
Closing as a duplicate. Thanks @trotyl for the hint.

**Closed by tbosch** 2017-04-08 16:42 UTC
