### ISSUE TITLE
Form validation fails randomly

### ISSUE THREAD

**Issue by aslamsayyed** [angular/angular#19067] opened 2017-09-06 08:26 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I have form with 3 inputs with validations, randomly test used to fail I tried running test in loop and observed issue,
// html
<form id="registrationForm" #registrationForm="ngForm" (ngSubmit)="registrationForm.form.valid && onRegister()">
<input mdInput #firstName="ngModel" name="name" [pattern]="/^[a-zA-Z \.\']*$/" minlength="2" maxlength="20" [(ngModel)]="name" placeholder="Name"
      required>
<input mdInput #mail="ngModel" name="email" [pattern]="/^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/" [(ngModel)]="email" placeholder="Email" required>
<input mdInput #phoneNumber="ngModel" name="phone" [pattern]="/^[789]\d{9}$/" maxlength="10" [(ngModel)]="phone" placeholder="Phone"
      required>
</form>
// test snippet
for (let i = 0; i < 100; i++) {
      fit('should validate form and features', async(() => {
        page.addRegisterSpy();
       
       // enter name
        let name = fakeName.findName();
        page.setNameValue(name);

        // enter email
        let email = fakeInternet.email();
        page.setEmailValue(email);

        // enter phone
        let phone = fakePhone.phoneNumber('9#########');
        page.setPhoneValue(phone);
        //page.expectPhoneModelToBe(phone);

          page.clickSubmit();

          console.log("Data", name, email, phone);
          page.printFormErrorIfAny('#registrationForm');

          page.expectSubmitSuccess();
      }));
    }
// function 
  printFormErrorIfAny(selector) {
    let ngForm = this.findForm(selector);
    if (ngForm.invalid) {
      console.log("Invalid: " + ngForm.invalid);
      console.log("Valid: " + ngForm.valid);
      console.log("errors: " + ngForm.errors);
      console.log("submitted: " + ngForm.submitted);

      console.log(ngForm);
    }
  }
// logs values
LOG: 'Valid: false'
LOG: NgForm{_submitted: true, ngSubmit: EventEmitter{_isScalar: false, observers: [...], closed: false, isStopped: false, hasError: false, thrownError: null, __isAsync: false}, form: FormGroup{validator: null, asyncValidator: null, _onCollectionChange: function () { ... }, _pristine: false, _touched: false, _onDisabledChange: [], controls: Object{name: ..., email: ..., phone: ...}, _valueChanges: EventEmitter{_isScalar: ..., observers: ..., closed: ..., isStopped: ..., hasError: ..., thrownError: ..., __isAsync: ...}, _statusChanges: EventEmitter{_isScalar: ..., observers: ..., closed: ..., isStopped: ..., hasError: ..., thrownError: ..., __isAsync: ...}, _statuLOG: NgForm{_submitted: true, ngSubmit: EventEmitter{_isScalar: false, observers: [...], closed: false, isStopped: false, hasError: false, thrownError: null, __isAsync: false}, form: FormGroup{validator: null, asyncValidator: null, _onCollectionChange: function () { ... }, _pristine: false, _touched: false, _onDisabledChange: [], controls: Object{name: ..., email: ..., phone: ...}, _valueChanges: EventEmitter{_isScalar: ..., observers: ..., closed: ..., isStopped: ..., hasError: ..., thrownError: ..., __isAsync: ...}, _statusChanges: EventEmitter{_isScalar: ..., observers: ..., closed: ..., isStopped: ..., hasError: ..., thrownError: ..., __isAsync: ...}, _status: 'INVALID', _value: Object{name: ..., email: ..., phone: ...}, _errors: null}}
## Expected behavior

ngform.valid should be true but in few cases it was failing so I have moved it into 

## What is the motivation / use case for changing the behavior?

Registration page of ongoing app.

## Environment
Test
<pre><code>
Angular version: 4.3.6

Browser:
- [x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 6.11.3 
- Platform:  Linux 

Others:

</code></pre>

**Comment by Toxicable** [comment] 2017-09-06 10:42
I'm sorry but reported issues require a plunker reproducing the problem.

If this issue persists, please create a plunker using this template and describe the difference between the expected and current behavior and create a new issue: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue

**Comment by aslamsayyed** [comment] 2017-09-06 12:38
Ok I will... do you have example to "how to write & run  a run test in plnkr" ?

**Comment by kara** [comment] 2017-11-03 22:08
Closing since we don't have an actionable repro case. Please feel free to re-open with a plunker demonstrating your issue.

**Closed by kara** 2017-11-03 22:08 UTC
Labels: comp: forms, state: Need repro
