### ISSUE TITLE
[2.2.1] Change Detection Not Working Correctly with Upgrade Adapter and Propagating Changes to Descendent Components

### ISSUE THREAD

**Issue by gregjacobs** [angular/angular#12318] opened 2016-10-14 22:31 UTC
**I'm submitting a ...**  (check one with "x")

```
[*] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When using the `UpgradeAdapter`, change detection does not propagate properties to descendent components in the `'angular'` Zone (either into setters, or `ngOnChanges()`). 

Instead, it propagates changes in the `'<root>'` zone, which causes problems when the child component performs some asynchronous operation. At the end of the async operation, change detection does not trigger again, so those async changes are not seen in the DOM.

Note: the problem does not exist when using `platformBrowserDynamic` in place of the `UpgradeAdapter`.

**Expected behavior**
When using `platformBrowserDynamic` instead of the `UpgradeAdapter`, changes propagate to child components in the `'angular'` zone, which is correct, and there is no bug. Same should happen with `UpgradeAdapter`.

**Minimal reproduction of the problem with instructions**

Reproduction Plnkr: http://plnkr.co/edit/DNF8BapmfaDIhIM7fvkS?p=preview

Explanation of Plnkr: When loaded, click the button. You will see that the parent component (AppComponent) updates the `numClicks`, as well as the child component's synchronous `numClicks` value. However, you will see that a value changed from an async promise resolution has _not_ been updated in the DOM.

Note: Inside `main.ts`, you can comment out the `UpgradeAdapter`, and uncomment `platformBrowserDynamic()` to see the correct behavior.

**General Steps to reproduce:**
1) Create a parent component, which passes an input attribute to a child component.
2) On click of a button (or anything) in the parent component, modify the value of the property/attribute.
3) Create a setter on the child component for that `@Input` attribute.
4) Resolve a promise from the setter in the child component which updates another child component property. You will not see that property change in the DOM.

**What is the motivation / use case for changing the behavior?**
We have an Angular 1 app which is now in the process of being upgraded to Angular 2. 

We have one of our Angular 1 components trigger a change in an Angular 2 component, but then change detection breaks inside the Angular 2 component tree when children try to asynchronously retrieve data from the server. We essentially don't see that data populated on the Angular 2 components when the server requests are complete, because the `'<root>'` zone doesn't trigger change detection.

**Please tell us about your environment:**
OS: Mac OSX 10.11.1 (El Capitan) / Windows 7. 
IDE: IntelliJ 2016.2 / Visual Studio Code / Plnkr
Package Manager: npm
- **Angular version:** 2.1.0
- **Browser:** 
  OSX Chrome 53.0.2785.143 (64-bit)
  OSX Safari 9.0.3
  Win7 Internet Explorer 11.0.9600.18449
- **Language:** TypeScript 2.0.2
- **Node (for AoT issues):** `node --version` = 6.7.0

**Comment by mbenna** [comment] 2016-11-18 23:29
I spent the morning chasing down my own repro case of this using angular 2.2.1 and zone.js 0.6.26 and came to exactly the same conclusion... with upgradeAdapter the child component is called in <root> zone, and without upgradeAdapter the child component is called in angular zone as expected. For now I'm working around it by wrapping constructor code and ngOnChanges code with return this._ngZone.run(() => { desired code })

The plnkr above is exactly what I was going to create, so thanks for saving me the time :)

**Comment by amcdnl** [comment] 2016-11-25 19:47
I'm also experiencing the issue. 

Can we assume it's Angular related since it works without upgrade?

**Comment by gregjacobs** [comment] 2016-12-13 14:35
Yes, I do believe it is `upgradeAdapter` specific. When bootstrapping with `platformBrowserDynamic()` instead, it works as expected.

For everyone's FYI by the way, anything you run asynchronously where you notice the view is not updating, try the following workaround as mentioned by @mbenna:

Change something like this code:

```ts
ngOnChanges( changes: SimpleChanges ) {
    this.loadMoreData().subscribe( result => this.message = result.message );
}
```

to:

```ts
constructor( private ngZone: NgZone ) {}

ngOnChanges( changes: SimpleChanges ) {
    this.ngZone.run( () =>
        this.loadMoreData().subscribe( result => this.message = result.message );
    } );
}
```

**Comment by sebasrodriguez** [comment] 2016-12-13 18:50
@gregjacobs the problem with this workaround is when you use a third party library that we don't have control over the code.

I had that same issue with a calendar control I was using and I had to fork that library to run some of that library code inside a zone just to make it work with upgradeAdapter.

I think that the lead developer for upgrade adapter is @petebacondarwin maybe he could help us pinpoint the root cause and we could create a PR with the fix.

**Comment by mhevery** [comment] 2016-12-13 23:59
I updated the plunker (http://plnkr.co/edit/L1W8ZNhY15BN4h71Ww1T?p=preview) to have assertions which show what is going on in the console. 

```
Error: Error in ./AppComponent class AppComponent - inline template:7:21 caused by: Expected to be in Angular Zone, but it is not!
Error: Expected to be in Angular Zone, but it is not!
    at Function.NgZone.assertInAngularZone (core.umd.js:6099) [<root>]
    at ChildComponent.set [as numClicks] (VM669 child.component.ts!transpiled:27) [<root>]
    at _View_AppComponent0.detectChangesInternal (AppComponent.ngfactory.js:76) [<root>]
    at _View_AppComponent0.AppView.detectChanges (core.umd.js:9325) [<root>]
    at _View_AppComponent0.DebugAppView.detectChanges (core.umd.js:9430) [<root>]
    at _View_AppComponent_Host0.AppView.detectViewChildrenChanges (core.umd.js:9351) [<root>]
    at _View_AppComponent_Host0.AppView.detectChangesInternal (core.umd.js:9336) [<root>]
    at _View_AppComponent_Host0.AppView.detectChanges (core.umd.js:9325) [<root>]
    at _View_AppComponent_Host0.DebugAppView.detectChanges (core.umd.js:9430) [<root>]
    at ViewRef_.detectChanges (core.umd.js:7421) [<root>]
    at eval (upgrade.umd.js:150) [<root>]
    at Scope.$digest (angular.js:17515) [<root>]
    at code.angularjs.org/1.5.8/angular.js:17721:26 [<root>]
    at completeOutstandingRequest (angular.js:5964) [<root>]
```

The issue is [here](https://github.com/angular/angular/commit/d6791ff0e0007801d987af325dbb34af3c34459f#commitcomment-20178842). @petebacondarwin can you take a look as it is your change.

**Comment by petebacondarwin** [comment] 2016-12-14 10:04
@mhevery actually the commit you linked to is for AoT (`upgrade/static`) this bug is for the original `upgrade` library. But I suspect we might end up with the same problem in AoT, since we borrowed the code for this from `upgrade` :-)

I will take a look.

**Comment by sebasrodriguez** [comment] 2016-12-14 15:01
@petebacondarwin I'm using the upgrade/static in my project and I can confirm that the issue also exists with upgrade/static. I'm on angular 2.2.3 currently.

**Comment by petebacondarwin** [comment] 2016-12-14 18:27
So this is my plan...

Currently we are using a `$watch` to trigger the change detection. This watch is triggered, in turn, by a call to `$evalAsync` which is called when the microtask queue becomes empty.

Instead, let’s `$broadcast` a detect changes event from the `$rootScope` and get downgraded components to listen for the message.

This avoids having to trigger unwanted digests after every time the microtask queue empties, and may even have better performance since we won't be triggering change detection on every turn of the digest.

I'll have a PR ready today.

**Comment by mbenna** [comment] 2016-12-14 18:31
How does the `$broadcast` instead of `$watch` change help solve things running in the wrong zone?

**Comment by petebacondarwin** [comment] 2016-12-14 20:13
The problem with the infinite digests is that triggering a change detection was causing a digest which was then triggering a change detection, etc.
By using broadcast, we have two separate mechanisms that are not going to keep triggering each other.
I am happy to proven wrong - this might break everything.
I have a branch that is almost working; I'll publish it within the next hour for your review.

**Comment by petebacondarwin** [comment] 2016-12-14 21:24
Here is my idea: https://github.com/angular/angular/pull/13477
It is not working yet but I thought I would make it public so that you can give me some feedback.

**Comment by mhevery** [comment] 2016-12-14 21:53
I think using `broadcast` is not right because:

1. It is slow
2. It does not guarantee that the ng1 and ng2 change detection is interleaved in the right order.

Can we just autodect that we are in infinite loop and break out of it?

**Comment by petebacondarwin** [comment] 2016-12-17 08:51
I agree that the `$broadcast` approach is not going to work. How about #13540 instead?

**Comment by mhevery** [comment] 2016-12-18 17:56
@petebacondarwin left comments

**Comment by amcdnl** [comment] 2016-12-20 19:25
@petebacondarwin - did this land in 2.4?

**Comment by petebacondarwin** [comment] 2016-12-20 22:32
@amcdnl - I'm afraid we still don't have an agreed solution. See https://github.com/angular/angular/pull/13540

**Comment by mlakmal** [comment] 2017-02-08 20:39
still getting this issue when component is added to a page dynamically inside setTimeout or promise. any idea how to resolve this issue? we are loading our components dynamically to v1 app and none of our v2 components work due to changeDetection not working ...

http://plnkr.co/edit/byzoGIDIwho4lSI5HIJr?p=preview

`
import { Component, Input, NgZone, ElementRef, Injector } from '@angular/core';
import {ChildComponent} from './child.component';
import { UpgradeModule, downgradeComponent } from '@angular/upgrade/static';

@Component( {
  selector : 'loader-component',
  template : `<div>loader</div>`
} )
export class LoaderComponent {
  
  constructor(private _eleRef: ElementRef,
    public injector: Injector,
    private _zone: NgZone){}
  
  ngAfterContentInit() {
    
    
    this._zone.run(()=>{
    setTimeout(()=>{
    tcpV2Module
        .asyncRegister.directive(
        'cnsLoginCmp',
        downgradeComponent({component: ChildComponent}));
      let e = angular.element('<cns-login-cmp></cns-login-cmp>');
      let p = angular.element(this._eleRef.nativeElement);
      p.append(e);
      this.injector.get('$compile')(e)(this.injector.get('$rootScope').$new());
    }, 500);
    });
  }
  
}
`

**Comment by petebacondarwin** [comment] 2017-02-09 08:16
Yes this is now fixed.

**Closed by petebacondarwin** 2017-02-09 08:16 UTC
Labels: comp: upgrade/dynamic

**Comment by mightypenguin** [comment] 2017-04-03 18:03
Seeing what looks like the same issue against 4.0.1 (zone.js v0.8.4)
setTimeout and subscribe changes do not show up in templates.
(angular/cli v1.0.0)

**Comment by tudorgergely** [comment] 2017-07-12 08:01
This is still a problem for me, version 4.2.4. Will try to make a quick example if I can. Does anyone else still have this issue?

**Comment by ronakvpanchal** [comment] 2018-03-16 23:29
I'm still seeing this issue on Angular 5.2.3 version.

**Comment by petebacondarwin** [comment] 2018-03-19 20:23
It would be very helpful if you could create an example @tudorgergely.

**Comment by dariuszbasiak** [comment] 2018-08-13 13:02
I have the same issue on the hybrid app with Angular 6.1.0. Any idea how to fix it?

**Comment by gregjacobs** [comment] 2018-08-13 19:47
Hey @dariuszbasiak. Make sure you're pulling in the zonejs cordova patch with a require() statement in your polyfills
