### ISSUE TITLE
Meta Tags not inserted for view page source

### ISSUE THREAD

**Issue by Lizard-King101** [angular/angular#43442] opened 2021-09-13 19:13 UTC
# 🐞 Bug report

### Is this a regression?

Un sure.

### Description

Fresh angular project and added angular universal from provided guide. was testing out adding dynamic title and meta tags. came across an issue of not being able to add meta tags to `view-page-source`.

``` javascript
this.meta.addTag({
    name: 'description',
    content: 'some description'
})
```
the above does not append any meta tags to the page source.
but it turns out that you need a metatag in the `index.html` for them to be updated

index.html
``` html
<head>
  <meta charset="utf-8">
  <title>My Site</title>
  <base href="/">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
  <meta name="description" content="">
</head>
```
home.component.ts
``` javascript
this.title.setTitle('My Site - Home');
this.meta.updateTag({
    name: 'description',
    content: 'some description'
})
```

![image](https://user-images.githubusercontent.com/54893135/133142122-c0dd1368-c3a3-4ca6-82a2-aa72e247230e.png)

## 🌍 Your Environment
<pre><code>
Angular CLI: 12.2.5
Node: 14.15.4
Package Manager: npm 6.14.10
OS: win32 x64

Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1202.5 (cli-only)
@angular-devkit/core         12.2.5 (cli-only)
@angular-devkit/schematics   12.2.5 (cli-only)
@schematics/angular          12.2.5 (cli-only)
</code></pre>

**Comment by petebacondarwin** [comment] 2021-09-14 20:11
Can you please provide a runnable reproduction of this issue?
From looking at the code for the `Meta` service, it looks like `addTag()` will work fine if there is not `meta` tag already.
I do think that it will fail to add an element if there is no `head` tag in the document.

**Comment by TheCoderFish** [comment] 2021-09-20 02:33
@petebacondarwin is right, use addTag instead of update.

**Comment by JoostK** [comment] 2021-12-11 12:39
Closing due to missing reproduction.

**Closed by JoostK** 2021-12-11 12:39 UTC
Labels: needs reproduction, comp: server
