### ISSUE TITLE
Form Component can't see ng-control inside child component

### ISSUE THREAD

**Issue by trippytango** [angular/angular#5524] opened 2015-12-01 11:26 UTC
While I don't know if this is an issue, but I'm confused on how this is supposed to work within angular2 compared to angular1.

Summary of the current scenario I have:

 - I have a container component which has a form. 
 - I have a secondary component which has an input field.

The container component has a control group and would like to assign the input field inside the secondary component to this control group.

Container Component code: 

    controlInput1: Control = new Control('');
    controlInput2: Control = new Control('');
    
    containerForm: ControlGroup = new ControlGroup({
      input1: this.controlInput1,
      input2: this.controlInput2
    });

controlInput2 or input2 is based in the secondary component which is included in the containerForm.

    <form [ng-form-model]="containerForm">
      <input ng-control="input1" id="input1">
      <secondary-component control-id="input2"></secondary-component>
    </form>

Secondary component code html:

    <h1>Secondary Component!</h1>
    <input ng-control="{{controlId}}" id="{{controlId}}">

Secondary component code TS:

    @component({
      inputs: ['controlId']
    })
    export class SecondaryComponent {
      @Input() controlId;
    }

How can I get the component to start talking with the control group in the container?

**Comment by kara** [comment] 2016-08-09 17:10
@trippytango  This looks like a dupe of https://github.com/angular/angular/issues/9281.  The short answer is that your secondary component needs to implement ControlValueAccessor. See my comment [here](https://github.com/angular/angular/issues/9281#issuecomment-238610807) for a more detailed explanation.

**Closed by kara** 2016-08-09 17:10 UTC
