### ISSUE TITLE
Angular 9.1.5

### ISSUE THREAD

**Issue by hugoebarboza** [angular/angular#37016] opened 2020-05-08 17:07 UTC
I updated to 9.1.5 and then I got the bellow Error.

 @angular/animations                 ^9.1.4  →   ^9.1.5
 @angular/cdk                        ^9.2.2  →   ^9.2.3
 @angular/common                     ^9.1.4  →   ^9.1.5
 @angular/compiler                   ^9.1.4  →   ^9.1.5
 @angular/core                       ^9.1.4  →   ^9.1.5
 @angular/elements                   ^9.1.4  →   ^9.1.5
 @angular/forms                      ^9.1.4  →   ^9.1.5
 @angular/localize                   ^9.1.4  →   ^9.1.5
 @angular/platform-browser           ^9.1.4  →   ^9.1.5
 @angular/platform-browser-dynamic   ^9.1.4  →   ^9.1.5
 @angular/platform-server            ^9.1.4  →   ^9.1.5
 @angular/router                     ^9.1.4  →   ^9.1.5
 @angular/service-worker             ^9.1.4  →   ^9.1.5
 @angular/compiler-cli               ^9.1.4  →   ^9.1.5
 @angular/language-service           ^9.1.4  →   ^9.1.5

*****************************************************************************************************
ERROR in TypeError: Cannot read property 'flags' of undefined
    at resolveAlias (C:\xampp\htdocs\odisdkp\node_modules\typescript\lib\typescript.js:36513:37)
    at checkAliasSymbol (C:\xampp\htdocs\odisdkp\node_modules\typescript\lib\typescript.js:64502:26)
    at checkImportBinding (C:\xampp\htdocs\odisdkp\node_modules\typescript\lib\typescript.js:64534:13)
    at checkImportDeclaration (C:\xampp\htdocs\odisdkp\node_modules\typescript\lib\typescript.js:64552:29)
    at checkSourceElementWorker (C:\xampp\htdocs\odisdkp\node_modules\typescript\lib\typescript.js:64961:28)
    at checkSourceElement (C:\xampp\htdocs\odisdkp\node_modules\typescript\lib\typescript.js:64800:17)
    at Object.forEach (C:\xampp\htdocs\odisdkp\node_modules\typescript\lib\typescript.js:317:30)
    at checkSourceFileWorker (C:\xampp\htdocs\odisdkp\node_modules\typescript\lib\typescript.js:65123:20)
    at checkSourceFile (C:\xampp\htdocs\odisdkp\node_modules\typescript\lib\typescript.js:65091:13)
    at getDiagnosticsWorker (C:\xampp\htdocs\odisdkp\node_modules\typescript\lib\typescript.js:65179:17)
    at Object.getDiagnostics (C:\xampp\htdocs\odisdkp\node_modules\typescript\lib\typescript.js:65165:24)
    at C:\xampp\htdocs\odisdkp\node_modules\typescript\lib\typescript.js:98703:85
    at runWithCancellationToken (C:\xampp\htdocs\odisdkp\node_modules\typescript\lib\typescript.js:98665:24)
    at getBindAndCheckDiagnosticsForFileNoCache (C:\xampp\htdocs\odisdkp\node_modules\typescript\lib\typescript.js:98691:20)
    at getAndCacheDiagnostics (C:\xampp\htdocs\odisdkp\node_modules\typescript\lib\typescript.js:98956:26)
    at getBindAndCheckDiagnosticsForFile (C:\xampp\htdocs\odisdkp\node_modules\typescript\lib\typescript.js:98688:20)

**Comment by petebacondarwin** [comment] 2020-05-08 17:12
Duplicate of #36992 
Moreover we have just released 9.1.6 which should not have this problem.

**Comment by santoshyadav198613** [comment] 2020-05-08 17:12
New version is getting released which will fix this.

**Closed** 2020-05-08 17:12 UTC

**Comment by petebacondarwin** [comment] 2020-05-08 17:30
9.1.6 is released. Please test.

**Comment by hugoebarboza** [comment] 2020-05-08 17:32
Now it's work well....thanks a lot.
