### ISSUE TITLE
angular 17/18 read cookie in server side with ssr

### ISSUE THREAD

**Issue by bastianparedes** [angular/angular#57510] opened 2024-08-24 17:54 UTC
### Which @angular/* package(s) are relevant/related to the feature request?

platform-browser, platform-server

### Description

It's not possible to read a cookie in server side with ssr. It's important when the cookie contains the session and the UI must change acordingly

### Proposed solution

httpClient request made in server side should contain and send cookies

### Alternatives considered

....

**Comment by alan-agius4** [comment] 2024-08-25 11:16
Duplicate of https://github.com/angular/angular/issues/15730

**Closed by alan-agius4** 2024-08-25 11:16 UTC
