### ISSUE TITLE
Stylesheet added to the template of an Angular element doesn't get applied

### ISSUE THREAD

**Issue by JenPeleva** [angular/angular#26853] opened 2018-10-30 12:24 UTC
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Adding a stylesheet link to the component template is supported, and works (https://angular.io/guide/component-styles). However, if the component is turned into an Angular element and the ViewEncapsulation is set ot ShadowDom, the css link gets loaded, but the styles do not get applied to the template of the element. Works with ViewEncapsulation None and Emulated.

## Expected behavior

The css should get applied to the html of the Angular element.

## Minimal reproduction of the problem with instructions

I'm loading font awesome and adding a circle icon to the template of my hello component. It works here:
https://stackblitz.com/edit/angular-7kx5ik (ViewEncapsulation None)

Doesn't work here:
https://stackblitz.com/edit/angular-eaz7af (ShadowDom ViewEncapsulation)

## What is the motivation / use case for changing the behavior?

Linking stylesheets in a custom elements is supported (https://developers.google.com/web/fundamentals/web-components/shadowdom) and I believe Angular should provide the same functionality. Thanks! :jack_o_lantern: :ghost:

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [x] Chrome (desktop) version 70.0.3538.67
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.11.3 
- Platform:

**Comment by trotyl** [comment] 2018-10-30 13:17
It's two separated issue:

1\. Angular attaches the element before setting attributes (https://github.com/angular/angular/pull/25240), so there's no `rel` attribute when that `<link>` element being attached, then resulting to `HTML element <link> is ignored in shadow tree`.

When setting attribute before attaching then the stylesheet would be recognized:

https://stackblitz.com/edit/angular-p6oi5y?file=src%2Fapp%2Fhello%2Fhello.component.ts

2\.  `@font-face` would not work inside ShadowRoot (https://bugs.chromium.org/p/chromium/issues/detail?id=336876), so even that `<link>` was recognized the font itself still won't got honored, so you got no icon but only the corresponding placeholder, which cannot be fixed by Angular.

**Comment by JenPeleva** [comment] 2018-10-30 15:31
Hi @trotyl,
Thanks for the input. I'm not sure I understood the first point completely. The rel attribute of my links isn't removed when they're inserted in the Shadow dom. Or you're saying that the attribute isn't there during some event and is added later on? 

As for the @font-face being ignored, according to this discussion (check the end - https://github.com/mdn/interactive-examples/issues/887) there used to be a bug in Chrome, which is now fixed. Although, I can't get it to work even inside a vanilla custom element. Hm... Pretty confusing...

**Comment by robwormald** [comment] 2018-10-30 17:50
@trotyl is right about the first one, for sure:
> The rel attribute of my links isn't removed when they're inserted in the Shadow dom. Or you're saying that the attribute isn't there during an event and is added too late?

Exactly that. The order of operations is something like:
- createElement
- appendChild
- setAttribute

The Web Component specs were designed with everybody using HTML Template Elements (lol), so there's a bit of a mismatch here.

**Comment by robwormald** [comment] 2018-10-30 20:44
Turns out, this is fixed in Ivy (not this issue directly, but in Ivy, attributes are set before the Node is inserted, which is the root cause of this issue). As a workaround, you could temporarily do this imperatively by just injecting the `ElementRef` and appending a link tag to it's Shadow Root.

**Comment by trotyl** [comment] 2018-10-31 01:39
@JenPeleva Any template element is constructed by imperative operations (DOM operations on Web), so that the order matters.

The Chrome bug ticket was closed due to "too complicated", I don't think it means fixed.

**Comment by JenPeleva** [comment] 2018-10-31 08:38
@robwormald, @trotyl, thanks for the clarification, guys!

**Comment by sandeep1030** [comment] 2019-03-04 11:24
So this means custom element created with Angular element is not production ready? 
Because shadowDom is a essential part to encapsulate style.

**Comment by siddharthpal** [comment] 2019-03-05 11:27
@robwormald  Is there any workaround we have as of now? 
Thanks

**Comment by vishranti5** [comment] 2019-06-24 10:36
Hi guys,
I have created one micro application using angular elements and i added external style sheet in components css file using @import . But after consuming micro application into base application, external style sheet doesn't got applied. do you know anything about this.
Also, If i create link element using html and add href to newly created link element in Components ts ( which means dynamically adding external style sheet ) This time it works after consuming into base application
I dont understand what happens here

**Comment by mhevery** [comment] 2020-02-14 23:49
Closing as this is fixed in Ivy and it has been released in v9.0.0

**Closed by mhevery** 2020-02-14 23:49 UTC
Labels: comp: core, fixed by Ivy, freq1: low, severity3: broken, type: bug/fix
