### ISSUE TITLE
Form input validation fails after being reenabled

### ISSUE THREAD

**Issue by lukengda** [angular/angular#39025] opened 2020-09-28 17:29 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/forms

### Is this a regression?

 I did not encounter this exact scenario prior to now, i have not tested previous versions 

### Description

Disabling and re-enabling a FormGroup that has a PatternValidator attached to it, causes the validation to fail if it was previously matched.

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-ivy-a7nhnq?file=src/app/app.component.html

Please see the instructions in the stackblitz demo app.

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 10.1.3
Node: 10.19.0
OS: linux x64

Angular: 10.1.3
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1001.3
@angular-devkit/build-angular   0.1001.3
@angular-devkit/core            10.1.3
@angular-devkit/schematics      10.1.3
@angular/cdk                    10.2.2
@angular/material               10.2.2
@schematics/angular             10.1.3
@schematics/update              0.1001.3
rxjs                            6.6.3
typescript                      4.0.3
</code></pre>

**Anything else relevant?**
If this is intended (which i wouldn't get yet), how could it be documented to explain the behavior of the PatternValidator?

**Comment by AleksanderBodurri** [comment] 2020-09-29 01:04
You made a very useful reproduction app, it made debugging incredibly easy, thank you 🙏 The TLDR; is that you should remove your `/g` global flag for the specific regex you've listed. Explanation below: 

The `Validator.pattern` HOF creates a regex object from the pattern you pass in. This object is stored within the closure created by the HOF.

There is a javascript regex gotcha (imagine that) associated with creating a regex with the `\g` global flag. The Mozilla docs explain it very well.  https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/test

Important snippets from the Mozilla docs (link above):
> When a regex has the global flag set, test() will advance the lastIndex of the regex. (RegExp.prototype.exec() also advances the lastIndex property.)

> When test() returns false, the calling regex's lastIndex property will reset to 0.

> Note: As long as test() returns true, lastIndex will not reset—even when testing a different string!

```js
const regex = /foo/g; // the "global" flag is set

// regex.lastIndex is at 0
regex.test('foo')     // true

// regex.lastIndex is now at 3
regex.test('foo')     // false
```

For this case the relevant code is:
https://github.com/angular/angular/blob/3ba97ab3917b682b6d08b9e71599051e77e2d3ac/packages/forms/src/validators.ts#L380-L406

Specifically,
https://github.com/angular/angular/blob/3ba97ab3917b682b6d08b9e71599051e77e2d3ac/packages/forms/src/validators.ts#L402-L405

When you manually enable the form, angular looks through it's child controls (in this case there is a single input) and reruns it's validators. The reason it's not working in this case is because the `lastIndex` from the previous validation was not reset (since the regex test returned true).

![regex](https://user-images.githubusercontent.com/39253660/94499984-098b1c80-01cc-11eb-80c3-f07b8f784e5b.png)

It's difficult to determine exactly what the standard behavior should be here. It's easy to say that Angular should just handle this case for you but the current implementation is more in line with how you would expect vanilla js to handle regex testing. 

Would be great to get some feedback from the Angular team on this.

**Comment by lukengda** [comment] 2020-09-29 08:14
@AleksanderBodurri thank you very much for your extensive analysis and reply. This solves my problem and yes, my regex knowledge is not so strictly coupled to javascript, so i may run into more gotachs...

**Comment by AndrewKushnir** [comment] 2020-09-30 03:21
Hi,

@lukengda thanks for creating a ticket with useful repro and thanks @AleksanderBodurri for the investigation and detailed comment.

As it was mentioned, the issue was caused by the `lastIndex` value being preserved for `RegExp`s with the `g` flag used. I will close this ticket, but I've created a new one to update the `Validators.pattern` docs to include more information on that (see #39053), please let me know if someone might be interested in creating a PR to add the note to the docs.

Thank you.

**Closed by AndrewKushnir** 2020-09-30 03:21 UTC
Labels: comp: forms, state: needs more investigation
