### ISSUE TITLE
Add user defined data to HttpRequest

### ISSUE THREAD

**Issue by goyaltushar92** [angular/angular#33561] opened 2019-11-04 04:31 UTC
# 🚀 feature request

### Relevant Package
This feature request is for @angular/common

### Description
Currently, there is no way to provide some user-defined data along with a request when creating an HTTP request with `HttpClient`, which will be accessible to `HttpInterceptor`s along with a request.
I was trying to create a loader, which uses `HttpInterceptor` to hide/show. but I want user should we able to specify on which request he does not want the loader to show. This is not possible in the current implementation of `HttpClient`.

### Describe the solution you'd like
 Currently almost all methods of `HttpClient` accepts options as a parameter, I want options should have an optional property `interceptorsData` of type `{[key: string]: any}`. The same property must also be added to `HttpRequeast`. so, that it became available for `HttpInterceptor`s. The only problem with this solution is that multiple library providers may use the same property names for there library.
If there is some batter solution you have, please comment.

**Comment by trotyl** [comment] 2019-11-04 04:34
Duplicate of https://github.com/angular/angular/issues/18155

**Comment by atscott** [comment] 2019-11-05 23:23
closing as duplicate of #18155

**Closed by atscott** 2019-11-05 23:23 UTC
Labels: comp: router
