### ISSUE TITLE
angular.copy

### ISSUE THREAD

**Issue by joshkurz** [angular/angular#1264] opened 2015-04-08 06:49 UTC
is there a plan to add the `angular.copy` function into facade/lang? If not anywhere in the project?

**Comment by pkozlowski-opensource** [comment] 2015-04-08 08:24
Nope, there is no currently plan of adding `angular.copy` or similar helpers. The problem with those helpers, initially needed by the framework internals, is that those grew beyond the initial intention as consequently are:
* way to big for what is needed by the framework itself
* are still enough as a general-purpose utils

So while ng2 will for sure have some internal helpers, those are not intended to be public. There are many excellent libraries that provide great utils and there is not much value in angular providing / maintaining duplicate of those.

**Closed by pkozlowski-opensource** 2015-04-08 08:24 UTC

**Comment by joshkurz** [comment] 2015-04-08 13:17
ok sounds good. Thanks

On Wed, Apr 8, 2015 at 4:24 AM, Pawel Kozlowski <notifications@github.com>
wrote:

> Closed #1264 <https://github.com/angular/angular/issues/1264>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/angular/angular/issues/1264#event-276009251>.
>



-- 
*Josh Kurz*
www.joshkurz.net
