### ISSUE TITLE
Display the version of a specific feature from its documentation page

### ISSUE THREAD

**Issue by pBouillon** [angular/angular#57469] opened 2024-08-21 06:24 UTC
### Describe the problem that you experienced

Whenever I am consulting the documentation about a specific feature, I cannot see the version in which it was released and need to dig into the release notes of the previous Angular versions. Ideally, I would like to see that information directly from the documentation page.

### Describe what you were looking for in the documentation

I was looking for the release version of a feature / primitive / etc. but couldn't find any from the documentation page itself

### Describe what you want to experience that would fix the problem

I would like to have the version in which the feature has been released or the versions for which this feature is available, this might be presented in the header for instance:

![Version displlay suggestion](https://github.com/user-attachments/assets/86b39bbd-7afe-49b9-a9ad-1f5c7e1c7396)

**Comment by JeanMeche** [comment] 2024-08-21 07:41
Duplicate of #49668

**Closed by JeanMeche** 2024-08-21 07:41 UTC
