### ISSUE TITLE
Getter/Setter for ng-control

### ISSUE THREAD

**Issue by rosendi** [angular/angular#5342] opened 2015-11-17 18:15 UTC
In angular 1 we transform form data in this way `ng-model-options="{ getterSetter: true }"`. In my plunk http://plnkr.co/edit/hWuOlOQn9iTlTKEL38sM?p=preview emails input can be a comma delimited email list. How could it be implemented without moving transform logic to the `onSubmit` method?

I found the `ControlValueAccessor`, `DefaultValueAccessor` and `NumberValueAccessor` classes, but I don't know how to use my own on a single input.

**Comment by mhevery** [comment] 2015-11-20 04:12
@vsavkin can you comment?

**Comment by tb** [comment] 2015-11-21 17:50
I am also interested in this. In our app we have directives for date input and time input. They both access the same ng-model. Based on "blur" we can tell that user has finished editing and we should parse it and update ng-model.

I think the way to do it is via DefaultValueAccessor but it requires #3011

**Comment by rosendi** [comment] 2015-12-08 12:53
Is there any progress?

**Comment by pkozlowski-opensource** [comment] 2016-09-09 17:12
@rosendi getters / setters won't work for your use-case due to #11097. As of today your best option is to implement the `ControlValueAccessor` interface and handle view <-> model value in there. Here is the example: https://plnkr.co/edit/TnV3tRe5P67LHk1mBEQm?p=preview

I fully recognise that it is a bit of code to write just for data conversion and the streamlined approach will come from #3009 so closing as duplicate of #3009.

**Closed by pkozlowski-opensource** 2016-09-09 17:12 UTC
Labels: comp: forms
