### ISSUE TITLE
Json file load failure, regardless of launcher

### ISSUE THREAD

**Issue by Solverbolt** [angular/angular#34639] opened 2020-01-05 11:24 UTC
Before you claim this is NOT YOUR ISSUE, You might want to actually review your own code and verify that it is not an issue with a corrupt or missing file in your modpack. Do not immediately ASSUME like an idiot that it is someones elses problem.

**Comment by ericmartinezr** [comment] 2020-01-05 14:25
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by alxhub** [comment] 2020-01-09 00:23
Hi @Solverbolt,

I think you have the wrong repository, as "modpack" is not a concept anywhere in the Angular ecosystem. Additionally, the language in your issue description is unnecessarily antagonistic and goes against the [Angular Code of Conduct](https://github.com/angular/angular/blob/master/CODE_OF_CONDUCT.md) which applies to our issue tracker.

Because I'm almost certain you have the wrong project, I'm going to close this issue for now. If you are actually trying to report an issue with the Angular web framework, please feel free to open another issue. In order to receive the best possible support in that case, it would be very helpful if you included reproduction instructions (especially a link to a repository which demonstrates the problem). Additionally, please refrain from accusatory language and keep the code of conduct in mind.

Thanks,
Alex

**Closed by alxhub** 2020-01-09 00:23 UTC
