### ISSUE TITLE
ngControl is Undefined using with directive after update to Angular 9 IVY

### ISSUE THREAD

**Issue by ofirrifo** [angular/angular#36438] opened 2020-04-05 15:47 UTC
# 🐞 bug report

### Affected Package
import { NgControl } from '@angular/forms';

### Is this a regression?
Yes, the issue wasn't appear with angular 8

### Description
in order to disable a form control field I'm using directive that inject the NgControl

**My Form Control** 
```
 <input type='url' [canEdit]="allowToEdit" formControlName='name'>
```

**My Directive** 
```
@Directive({
  selector: '[canEdit]'
})
export class CanEditDirective {
  @Input()
  set mgmtIfUserCanEdit(canEdit: boolean) {
    const action = canEdit ? 'enable' : 'disable'; 
    this.ngControl.control[action](); // <-- this.ngControl is undefined
  }

  constructor(private ngControl: NgControl) {}
}
``` 

**Angular Version:**
<pre><code>
Angular CLI: 9.1.0
Node: 12.3.1
OS: darwin x64

Angular: 9.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.0
@angular-devkit/build-angular     0.901.0
@angular-devkit/build-optimizer   0.901.0
@angular-devkit/build-webpack     0.901.0
@angular-devkit/core              9.1.0
@angular-devkit/schematics        9.1.0
@angular-devkit/schematics-cli    0.803.26
@angular/cdk                      9.2.0
@angular/material                 9.2.0
@ngtools/webpack                  9.1.0
@nguniversal/common               9.1.0
@nguniversal/express-engine       9.1.0
@schematics/angular               9.1.0
@schematics/schematics            0.803.26
@schematics/update                0.901.0
rxjs                              6.5.4
typescript                        3.8.3
webpack                           4.42.0

</code></pre>

**Comment by SteffenSchwaiger** [comment] 2020-04-06 07:25
Duplicate of #35330

**Closed** 2020-04-06 11:09 UTC
