### ISSUE TITLE
TypeScript generates more after*Checked events than Dart does

### ISSUE THREAD

**Issue by kwalrath** [angular/angular#6498] opened 2016-01-15 00:49 UTC
When converting the TypeScript lifecycle example to Dart, @adaojunior noticed that the TS & Dart versions generate slightly different events.

I'm not sure these differences are significant, but I'm reporting it just in case. I initially interpreted this test as meaning that the Dart UI wasn't updated every time it should be. Now I think it _is_ updated the same way the TS UI is, but that **the TS version has 1 extra pair of after*Checked events**.

The source code for both the TS & Dart versions is in https://github.com/adaojunior/lifecycle-hooks. To see the diffs when they run:

1. [Right-click here](https://angular.io/resources/live-examples/lifecycle-hooks/ts/plnkr.html) to open a window with the runnable TS sample.

2. [Right-click here](https://adaojunior.github.io/lifecycle-hooks) to open another window with the runnable Dart sample.

3. Open the Dart window's console. 

4. In both windows, click **Create PeekABooComponent**.
   The **Dart** UI displays this:  

   ```
#1 onChanges (1): name initialized to "Windstorm"
#1 onInit
#1 afterContentInit
#1 afterContentChecked (1)
#1 afterViewInit
#1 afterViewChecked (1)
```

   Its console displays the same messages, plus 2 more:  

   ```
...
#1 afterContentChecked (2)
#1 afterViewChecked (2)
```

  The TS UI displays these messages:  

   ```
#1 onChanges (1): name initialized to "Windstorm"
#1 onInit
#1 afterContentInit
#1 afterContentChecked (1)
#1 afterViewInit
#1 afterViewChecked (1)
#1 afterContentChecked (2)
#1 afterViewChecked (2)
```

   So the Dart and TS logs appear to be the same, but the 2 last events don't make it to the Dart UI (yet).

5. In both windows, click **Update Hero**.

  The Dart UI adds the following lines:  

  ```
...
#1 afterContentChecked (2)
#1 afterViewChecked (2)
#1 onChanges (2): name changed to "Windstorm!"
#1 afterContentChecked (3)
#1 afterViewChecked (3)
```

 The Dart console adds the following lines:

   ```
...
#1 onChanges (2): name changed to "Windstorm!"
#1 afterContentChecked (3)
#1 afterViewChecked (3)
#1 afterContentChecked (4)
#1 afterViewChecked (4)
```

  The TS UI adds the following lines:  
  
   ```
...
#1 afterContentChecked (3)
#1 afterViewChecked (3)
#1 onChanges (2): name changed to "Windstorm!"
#1 afterContentChecked (4)
#1 afterViewChecked (4)
#1 afterContentChecked (5)
#1 afterViewChecked (5)
```

Each click of **Update Hero** results in 1 onChanges event and 2 (Dart) or 3 (TS) groups of afterContentChecked+afterViewChecked events.

**Comment by zoechi** [comment] 2016-01-15 07:02
I saw a comment somewhere that indicated that Dart doesn't have a development mode. Development mode runs each change detection twice to check if change detection itself causes changes, which is probably a bug in the application because change detection shouldn't have side effects.

**Comment by kwalrath** [comment] 2016-01-15 18:19
That sounds like the cause. In the Dart console:

```
Angular 2 is running in the production mode. Call enableDevMode() to enable the development mode.
```

In the TS console:

```
Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode.
```

I never noticed they were different because "is running in **the**...mode" distracted me from the actually meaningful words. :)

**Comment by adaojunior** [comment] 2016-01-15 18:29
I ran the TS example in production mode but I could not find any difference.
Still two more pairs of **after*Checked**

**Comment by vicb** [comment] 2016-10-07 19:11
Duplicate of #6974

**Comment by DzmitryShylovich** [comment] 2016-10-17 07:01
Can be closed?

**Closed** 2016-10-17 07:02 UTC
Labels: comp: core & compiler, effort2: medium (days), type: bug
