### ISSUE TITLE
ng-xi18n Fails with Error encountered resolving symbol values statically.

### ISSUE THREAD

**Issue by slangley** [angular/angular#13902] opened 2017-01-12 22:13 UTC
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Exception.  Unable to extract any localization XLIFF files.

**Expected behavior**
Able to run and extract at least empty XLIFF files

**Minimal reproduction of the problem with instructions**
$ npm install -g angular-cli
$ ng new fuzzballs
$ cd fuzzballs
$ ng-xi18n

Results in the following error:
Error: Error encountered resolving symbol values statically. Calling function 'NoOpAnimationDriver', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AnimationDriver.NOOP in /Users/slnl/fuzzballs/node_modules/@angular/platform-browser/src/dom/animation_driver.d.ts, resolving symbol BrowserTestingModule in /Users/slnl/fuzzballs/node_modules/@angular/platform-browser/testing/browser.d.ts, resolving symbol BrowserTestingModule in /Users/slnl/fuzzballs/node_modules/@angular/platform-browser/testing/browser.d.ts
    at simplifyInContext (/Users/slnl/fuzzballs/node_modules/@angular/compiler/bundles/compiler.umd.js:25709:25)
    at StaticReflector.simplify (/Users/slnl/fuzzballs/node_modules/@angular/compiler/bundles/compiler.umd.js:25721:15)
    at StaticReflector.annotations (/Users/slnl/fuzzballs/node_modules/@angular/compiler/bundles/compiler.umd.js:25218:62)
    at NgModuleResolver.resolve (/Users/slnl/fuzzballs/node_modules/@angular/compiler/bundles/compiler.umd.js:17564:84)
    at CompileMetadataResolver.getNgModuleMetadata (/Users/slnl/fuzzballs/node_modules/@angular/compiler/bundles/compiler.umd.js:18072:62)
    at CompileMetadataResolver.getNgModuleSummary (/Users/slnl/fuzzballs/node_modules/@angular/compiler/bundles/compiler.umd.js:18028:54)
    at /Users/slnl/fuzzballs/node_modules/@angular/compiler/bundles/compiler.umd.js:18118:70
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (/Users/slnl/fuzzballs/node_modules/@angular/compiler/bundles/compiler.umd.js:18113:51)
    at addNgModule (/Users/slnl/fuzzballs/node_modules/@angular/compiler/bundles/compiler.umd.js:24980:60)
Extraction failed

**What is the motivation / use case for changing the behavior?**
Basic functionality is broken to generate localization data.

**Please tell us about your environment:**
MacOS X, angular CLI.

* **Angular version:** 2.0.X
$ ng --version
angular-cli: 1.0.0-beta.24
node: 6.9.2
os: darwin x64
@angular/common: 2.4.3
@angular/compiler: 2.4.3
@angular/core: 2.4.3
@angular/forms: 2.4.3
@angular/http: 2.4.3
@angular/platform-browser: 2.4.3
@angular/platform-browser-dynamic: 2.4.3
@angular/router: 3.4.3
@angular/compiler-cli: 2.4.3

* **Browser:** 
all 
 
* **Language:**
all

* **Node (for AoT issues):** `node --version` =   
v6.9.2

**Comment by DzmitryShylovich** [comment] 2017-01-12 22:15
https://github.com/angular/angular/issues/13624#issuecomment-270489067

**Comment by MrSingh** [comment] 2017-03-01 15:42
I am encountering the same problem.

`Error: Error encountered resolving symbol values statically. Calling function 'makeDecorator', function calls are not supported. Consider replacing the function or lambda with a
reference to an exported function, resolving symbol Injectable in C:/home/git/ng-luna/node_modules/angular-datatables/node_modules/@angular/core/src/di/metadata.d.ts, resolving s
ymbol OpaqueToken in C:/home/git/ng-luna/node_modules/angular-datatables/node_modules/@angular/core/src/di/opaque_token.d.ts, resolving symbol OpaqueToken in C:/home/git/ng-luna/
node_modules/angular-datatables/node_modules/@angular/core/src/di/opaque_token.d.ts
    at SyntaxError.BaseError [as constructor] (C:\home\git\ng-luna\node_modules\@angular\compiler\bundles\compiler.umd.js:1597:31)
    at new SyntaxError (C:\home\git\ng-luna\node_modules\@angular\compiler\bundles\compiler.umd.js:1795:20)
    at simplifyInContext (C:\home\git\ng-luna\node_modules\@angular\compiler\bundles\compiler.umd.js:25783:27)
    at StaticReflector.simplify (C:\home\git\ng-luna\node_modules\@angular\compiler\bundles\compiler.umd.js:25795:17)
    at StaticReflector.annotations (C:\home\git\ng-luna\node_modules\@angular\compiler\bundles\compiler.umd.js:25291:64)
    at NgModuleResolver.resolve (C:\home\git\ng-luna\node_modules\@angular\compiler\bundles\compiler.umd.js:17771:86)
    at CompileMetadataResolver.getNgModuleMetadata (C:\home\git\ng-luna\node_modules\@angular\compiler\bundles\compiler.umd.js:18272:64)
    at addNgModule (C:\home\git\ng-luna\node_modules\@angular\compiler\bundles\compiler.umd.js:25053:62)
    at C:\home\git\ng-luna\node_modules\@angular\compiler\bundles\compiler.umd.js:25064:18
    at Array.forEach (native)
Extraction failed`

**Comment by ocombe** [comment] 2017-03-13 13:54
I've used the cli on new projects lately and it works just fine, I think that the issue is resolved on their part. Try again with rc1 of the cli, and let me know if it still fails.

**Comment by thegene** [comment] 2017-03-17 14:59
am seeing the same issue in `@angular/platform-browser` using rc1 or rc2 (have tried with both)
```
ERROR in Error encountered resolving symbol values statically. Calling function 'NoOpAnimationDriver', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AnimationDriver.NOOP in /Users/ewestbrook/projects/smartshopper-ui/node_modules/@angular/platform-browser/src/dom/animation_driver.d.ts, resolving symbol BrowserTestingModule in /Users/ewestbrook/projects/smartshopper-ui/node_modules/@angular/platform-browser/testing/browser.d.ts, resolving symbol BrowserTestingModule in /Users/ewestbrook/projects/smartshopper-ui/node_modules/@angular/platform-browser/testing/browser.d.ts
```

**Comment by doubletriplezero** [comment] 2017-03-17 15:55
We had the same issue today. The cause turned out to be a duplicate import of an NgModule. It was getting imported directly and also as part of a second NgModule which was also importing and re-exporting the same module.

So basically a situation like the following will cause this error:
`@NgModule({
    imports: [ Module2 ],
    declarations: [],
    exports: [Module2],
    providers: [],
})
export class Module1`

`@NgModule({
    imports: [ Module1, Module2 ],
    declarations: [],
    exports: [],
    providers: [],
})
export class Module3`

**Comment by ocombe** [comment] 2017-03-20 15:04
It should work starting from rc3

**Comment by marob** [comment] 2017-03-21 18:25
KO in rc4 following "Minimal reproduction of the problem with instructions":
```
Error: Error encountered resolving symbol values statically. Could not resolve events relative to /tmp/fuzzballs/node_modules/blocking-proxy/built/lib/webdriver_commands.d.ts., resolving symbol WebDriverCommand in /tmp/fuzzballs/node_modules/blocking-proxy/built/lib/webdriver_commands.d.ts
    at SyntaxError.BaseError [as constructor] (/tmp/fuzzballs/node_modules/@angular/compiler/bundles/compiler.umd.js:1597:31)
    at new SyntaxError (/tmp/fuzzballs/node_modules/@angular/compiler/bundles/compiler.umd.js:1795:20)
    at simplifyInContext (/tmp/fuzzballs/node_modules/@angular/compiler/bundles/compiler.umd.js:25774:27)
    at StaticReflector.simplify (/tmp/fuzzballs/node_modules/@angular/compiler/bundles/compiler.umd.js:25786:17)
    at StaticReflector.annotations (/tmp/fuzzballs/node_modules/@angular/compiler/bundles/compiler.umd.js:25278:84)
    at NgModuleResolver.resolve (/tmp/fuzzballs/node_modules/@angular/compiler/bundles/compiler.umd.js:17762:86)
    at CompileMetadataResolver.getNgModuleMetadata (/tmp/fuzzballs/node_modules/@angular/compiler/bundles/compiler.umd.js:18263:64)
    at addNgModule (/tmp/fuzzballs/node_modules/@angular/compiler/bundles/compiler.umd.js:25044:62)
    at /tmp/fuzzballs/node_modules/@angular/compiler/bundles/compiler.umd.js:25055:18
    at Array.forEach (native)
Extraction failed

```

**Comment by romafederico** [comment] 2017-04-04 05:20
Same thing here. Minimal reproduction gives me the same error. RC4.

**Comment by Tryptich** [comment] 2017-06-14 09:01
I have a same error, i solve it like that ng xi18n -op src/language, hope it works for you. you should also exclude test files in your tsconfig file.

**Comment by ocombe** [comment] 2017-11-03 08:49
Hello, can you try again in v5 please ?

**Comment by vicb** [comment] 2017-11-28 23:47
Closing as no feedback after the last message.

Please re-open if still an issue.

**Closed by vicb** 2017-11-28 23:47 UTC
Labels: comp: i18n, type: bug
