### ISSUE TITLE
Date pipe time component extraction issues across locales

### ISSUE THREAD

**Issue by gary-b** [angular/angular#12632] opened 2016-10-31 19:12 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**
The date pipe output is incorrect when custom formats are used with various locales. The current implementation will use Intl.DateTimeFormat to localize DateTime information, and then use string manipulation to extract individual components as the output is not granular enough. The bugs come mainly from assumptions about how the format looks across all locales. 

I've provided unit tests as a repro- the expected results are valid on Chrome, but not necessarily IE - (different browsers format locales differently, including the order of components, number system and alphabets used.) See the full tests created while investigating the issue at https://gist.github.com/gary-b/bdc67fae4767c7da08ee93965a955fa5 

assume date = new Date(2015, 5, 15, 9, 3, 1);
1.The day part ('a') output fails in various locales
```
// When Intl.DateTimeFormat puts the day part in front of the hour for the locale
pipe = new DatePipe('hu');
expect(pipe.transform(date, 'a')).toEqual('de.'); // outputs 9
// When Intl.DateTimeFormat has a space in the day part string itself for the locale
pipe = new DatePipe('sr');
expect(pipe.transform(date, 'a')).toEqual('пре подне'); // outputs npe
```
See the Intl.ts hourClockExtractor function. 

2.The 2 digit formatting (eg "hh") outputs a mix of numbering systems
```
pipe = new DatePipe('mr');
expect(pipe.transform(date, 'hh')).toEqual('०९'); // outputs 0९
```
The '0' is hard coded into angular's Intl.js digitModifier function.

3.The timezone output fails with certain locales
```
// When the browser puts the hour after the timezone for the locale
pipe = new DatePipe('zh');
expect(pipe.transform(date, 'Z')).toEqual('GMT+1'); // outputs +19时
// When Intl.DateTimeFormat outputs an hour identifier between the hour and the timezone for the locale, eg for fr you get 09 h UTC+1
pipe = new DatePipe('fr');
expect(pipe.transform(date, 'Z')).toEqual('UTC+1'); // outputs h UTC+1
```
See the Intl.ts timeZoneGetter function.

4.The era output doesn't work on any locale I tried
```
expect(pipe.transform(date, 'G')).toEqual('A');//outputs 6 15, 2015 A
```
Angular's Intl.ts assumes the Intl.DateTimeFormat object will output the era on its own, it doesn't.

**What is the motivation / use case for changing the behavior?**
Broken.

**Please tell us about your environment:**
Windows 10

* **Angular version:** 2.0.X
Angular master

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome (also have details of IE output in the gist)

**Comment by DzmitryShylovich** [comment] 2016-10-31 19:14
Duplicate of https://github.com/angular/angular/issues/10809

**Comment by gary-b** [comment] 2016-10-31 19:25
@DzmitryShylovich As that issue states it "is mostly to summarize issues about Intl.API." These are 4 new specific issues.

**Comment by DzmitryShylovich** [comment] 2016-10-31 19:34
We can add new issue forever but it doesn't change anything. We need some real alternative or design doc.

**Comment by pkozlowski-opensource** [comment] 2016-12-12 13:47
@gary-b thnx for the super-detailed summary issues. Indeed the current handling of custom formats needs much more love and your list helps us making things better! Thank you.

@DzmitryShylovich I'm going to keep this one open as it is very detailed and valuable. We need to make sure that all the use-cases here are turned into tests and those tests are run as part of CI on each and every supported browser.

**Comment by ocombe** [comment] 2017-06-28 08:39
Hello, most of these issues will be fixed with the PR to replace the intl API for angular v5 (see [#10809](https://github.com/angular/angular/issues/10809))

- The day part "a" works according to your tests
- The numbering system will show 09, but not ०९ because we only support latin characters for now (we could support all numbering systems with the data that we have, but only if someone ask for it, because it adds a lot of data)
- The timezones with `Z` will show +0200 in both cases, if you want GMT+2 you'll have to use `O`. Note that it's +0200 because of the summer/winter times, but you can fix the timezone as a new additional parameter of the pipe

**Closed** 2017-08-25 08:01 UTC
Labels: comp: common, comp: i18n, freq2: medium, severity3: broken, type: bug
