### ISSUE TITLE
Update Angular 8 to 9 problem with angular.json translation file format

### ISSUE THREAD

**Issue by pacocom** [angular/angular#35525] opened 2020-02-18 12:23 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description
After update to Angular 9 appears when I try to build with a configuration appears this error:
`ng serve client --configuration=default` or `ng build client --configuration=default`
**An unhandled exception occurred: Unsupported translation file format.**
![image](https://user-images.githubusercontent.com/7735329/74735850-cfc76000-5251-11ea-8a4c-a3f30a8a4768.png)
![image](https://user-images.githubusercontent.com/7735329/74735868-d6ee6e00-5251-11ea-95a9-09d7bf08bd0c.png)
![image](https://user-images.githubusercontent.com/7735329/74736100-554b1000-5252-11ea-8195-b0066c5f0ce0.png)

Before update to Angular 9 (Work fine!)
![image](https://user-images.githubusercontent.com/7735329/74425677-5e07a480-4e54-11ea-852f-5e48c5de018d.png)
After update to Angular 9
![image](https://user-images.githubusercontent.com/7735329/74735511-1f595c00-5251-11ea-9648-0e7e3de39f00.png)

`package.json`
```
      "root": "apps/client",
      "sourceRoot": "apps/client/src",
      "prefix": "app",
      "architect": {
        "build": {
          "builder": "@angular-builders/custom-webpack:browser",
          "options": {
            "indexTransform": "apps/client/index-html-transform.js",
            "outputPath": "dist/apps/client",
            "index": "apps/client/src/index.html",
            "main": "apps/client/src/main.ts",
            "polyfills": "apps/client/src/polyfills.ts",
            "tsConfig": "apps/client/tsconfig.app.json",
...
            "default": {
              "fileReplacements": [
                {
                  "replace": "apps/client/src/environments/environment.ts",
                  "with": "apps/client/src/environments/environment.prod.ts"
                }
              ],
              "optimization": true,
              "outputHashing": "none",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true,
              "budgets": [
                {
                  "type": "initial",
                  "maximumWarning": "2mb",
                  "maximumError": "5mb"
                }
              ],
              "i18nFile": "i18n/default.xliff",
              "i18nFormat": "xlf",
              "i18nLocale": "en",
              "i18nMissingTranslation": "warning"
            },
...
        "extract-i18n": {
          "builder": "@angular-devkit/build-angular:extract-i18n",
          "options": {
            "browserTarget": "client:build",
            "i18nFormat": "xlf",
            "outputPath": "../../i18n",
            "outFile": "messages.xliff"
          }
        },
...
```

Update:
Working without IVY, but **I want IVY** for `ng build --configuration=default` but `ng serve` entryComponents error with;
```
  "angularCompilerOptions": {
    "enableIvy": false
  }
```

**Comment by JoostK** [comment] 2020-02-18 17:07
The problem seems to be that your `i18nFile` has the `.xliff` extension, not `.xlf`. Since the extension seems to be the primary way to identify a suitable translation parser, this causes a mismatch when searching for a parser.

I don't know what the expected behavior should be here. @clydin Could you suggest what needs to be done, if anything?

**Comment by clydin** [comment] 2020-02-18 19:09
The translation file parsers contained within the `@angular/localize` package control the detection of the file format.  For xliff1 files the relevant code can be found [here](https://github.com/angular/angular/blob/939e2f76f6c3180e13886357a7dbdf8d562e98f4/packages/localize/src/tools/src/translate/translation_files/translation_parsers/xliff1_translation_parser.ts#L31).  Currently, the code to determine the format checks for the `xlf` extension and not the `xliff` extension.  This code could potentially be expanded.  @petebacondarwin may have more insight into this though.

**Comment by pacocom** [comment] 2020-02-19 07:47
Please, can you help me with a more complete example of angular.json file?
```
"projects": {
  ...
  "angular.io-example": {
    ...
    "i18n": {
      "sourceLocale": "en-US",
      "locales": {
        "fr": "src/locale/messages.fr.xlf"
      }
    }
    ...
    "targets": {
      ...
    }
  }
}
```
(According with the documentation https://angular.io/guide/i18n#localize-config for Angular 9).

Please, remove ... and write me a full example. I don't know where write sourceLocale. In my project inside `client.i18n.sourceLocale`?

Thank.

**Comment by laurentgoudet** [comment] 2020-02-24 16:01
Had a similar issue (working fine without Ivy, "Unsupported translation file format" in Ivy): for me the file extension was fine (`.xlf`) but our translation system did not set an XML Namespace (`xmlns`) on the XLIFF localized dictionaries, causing the second condition (`XLIFF_1_2_NS_REGEX.test(contents)`) in the code pointed by @clydin to return `false`.

**Comment by laurentgoudet** [comment] 2020-02-24 16:20
Actually looking at the [XLIFF 1.2 standard](http://docs.oasis-open.org/xliff/v1.2/os/xliff-core.html):

> If necessary, you can also specify a namespace for XLIFF. The namespace identifier for this standard is "urn:oasis:names:tc:xliff:document:1.2".
>
>A minimal XLIFF document with one entry looks something like this:
>```
><?xml version="1.0"?>
><xliff version="1.2">
><file source-language="EN" datatype="plaintext" original="file.ext">
><body>
><trans-unit id="1">
><source>Hello World!</source>
></trans-unit>
></body>
></file>
>```

i.e., it looks like `@angular/localize` is a bit too strict when it comes to matching XLIFF 1.2 files.

**Comment by petebacondarwin** [comment] 2020-02-24 16:45
For sure we can relax the file extension check. The problem after that is how to tell XLIFF 1.2 files from XLIFF 2.0 file? I guess we should be just checking the `version` attribute on the `xliff` element.

Moreover we could even ditch the file-extension check altogether and just look for an XML file that has the `<xliff version='XXX'>` element? WDYT?

**Comment by laurentgoudet** [comment] 2020-02-24 16:54
> Moreover we could even ditch the file-extension check altogether and just look for an XML file that has the <xliff version='XXX'> element? WDYT?

Given that the goal here is only to tell apart XLIFF 1.2 files from XLIFF 2.0, XMB, or JSON ones, IMO just looking at the `<xliff version="XXX">` does the job.

**Comment by petebacondarwin** [comment] 2020-02-26 08:25
Working on a fix...

**Comment by JoostK** [comment] 2020-03-14 14:48
Closing as #35793 has been merged and is available in 9.0.6

**Closed by JoostK** 2020-03-14 14:48 UTC
Labels: comp: i18n, freq2: medium, severity5: regression, type: bug/fix

**Comment by nodermatt** [comment] 2020-03-17 16:46
I still have this problem using angular 9.06 and using this angular.json file:

```
{
  ...
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1, 
  "newProjectRoot": "projects",
  "projects": {
      "i18n": {
        "sourceLocale": "en-US",
        "locales": {
          "fr": "src/locale/messages.fr.xlf"
        }
      },
      "architect": {
        "build": {
          "configurations": {
            ...
            "fr": {
              "localize": ["fr"]
            }
          }
        }
}
```

I am using .xlf extension for the translation files and they do contain the namespace attribute:
![image](https://user-images.githubusercontent.com/1467464/76879507-a3b1f580-6876-11ea-95d4-56b69d19b7e0.png)

<xliff version="1.2" xmlns="urn:oasis:names:tc:xliff:document:1.2">


Here is the content from the log file:
```
[error] Error: Unsupported translation file format.
    at C:\Users\niod\Code\displaying-data\node_modules\@angular-devkit\build-angular\src\utils\load-translations.js:23:15
    at Object.configureI18nBuild (C:\Users\niod\Code\displaying-data\node_modules\@angular-devkit\build-angular\src\utils\i18n-options.js:162:28)
    at async Object.generateI18nBrowserWebpackConfigFromContext (C:\Users\niod\Code\displaying-data\node_modules\@angular-devkit\build-angular\src\utils\webpack-browser-config.js:85:36)
    at async setup (C:\Users\niod\Code\displaying-data\node_modules\@angular-devkit\build-angular\src\dev-server\index.js:103:47)


```

@JoostK Can you spot my mistake?

**Comment by JoostK** [comment] 2020-03-17 17:34
@nodermatt I don't know, sorry. The extension doesn't seem to be relevant anymore, maybe there's something wrong in the XML contents.

**Comment by petebacondarwin** [comment] 2020-03-17 21:46
Can you try running the `@angular/localize` binary directly against your XLIFF file. Something like:

```
yarn localize-translate -r "dist" -s "**/*" -l "fr" -t "src/locale/messages.fr.xlf" -o "../tmp/translations/{{LOCALE}}"
```

And see if you get a more detailed error message...

**Comment by nodermatt** [comment] 2020-03-18 10:22
Hi @JoostK & @petebacondarwin thanks for the quick response, glad to get any input on this.

The yarn command yielded output like below:
```
 C:\Users\niod\Code\displaying-data\node_modules\.bin\localize-translate -r dist -s **/* -l fr -t src/locale/messages.fr.xlf -o ../tmp/translations/{{LOCALE}}
C:\Users\niod\Code\displaying-data\node_modules\@angular\localize\src\tools\src\translate\translation_files\translation_loader.js:75
                throw new Error("There is no \"TranslationParser\" that can parse this translation file: " + filePath + ".");
                ^

Error: There is no "TranslationParser" that can parse this translation file: src/locale/messages.fr.xlf.
```

I did actually start from scratch, deleting both the messages files and regenerating them. Afterwards it worked fine so I guess it must have been something with the content. Maybe it helped that I used xliffmerge this time to avoid copying the files back and forth. This is quite convenient and helps to reduce errors: ng xi18n --outputPath=src/i18n; ng run displaying-data:xliffmerge

angular.json entry
```
"xliffmerge": {
          "builder": "@ngx-i18nsupport/tooling:xliffmerge",
          "options": {
            "xliffmergeOptions": {
              "i18nFormat": "xlf",
              "srcDir": "src/i18n",
              "genDir": "src/i18n",
              "defaultLanguage": "en-US",
              "languages": [
                "fr"
              ]
            }
          }
        }
``` 

Interestingly, the yarn command still throws an error although it works using ng serve:
```
$ C:\Users\niod\Code\displaying-data\node_modules\.bin\localize-translate -r dist -s **/* -l fr -t src/i18n/messages.fr.xlf -o ../tmp/translations/{{LOCALE}}
C:\Users\niod\Code\displaying-data\node_modules\@angular\localize\src\tools\src\translate\translation_files\translation_loader.js:73
                    finally { if (e_1) throw e_1.error; }
                                       ^

Error: The translation file "src/i18n/messages.fr.xlf" does not contain a target locale and no explicit locale was provided for this file.
    at C:\Users\niod\Code\displaying-data\node_modules\@angular\localize\src\tools\src\translate\translation_files\translation_loader.js:55:35
    at Array.map (<anonymous>)
    at TranslationLoader.loadBundles (C:\Users\niod\Code\displaying-data\node_modules\@angular\localize\src\tools\src\translate\translation_files\translation_loader.js:38:41)
    at translateFiles (C:\Users\niod\Code\displaying-data\node_modules\@angular\localize\src\tools\src\translate\main.js:100:46)
    at C:\Users\niod\Code\displaying-data\node_modules\@angular\localize\src\tools\src\translate\main.js:83:9
    at C:\Users\niod\Code\displaying-data\node_modules\@angular\localize\src\tools\src\translate\main.js:4:17
    at Object.<anonymous> (C:\Users\niod\Code\displaying-data\node_modules\@angular\localize\src\tools\src\translate\main.js:10:3)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
```
However, this isn't related to my initial problem which luckily has disappeared.

Sorry for the noise and thanks again for the help.

**Comment by petebacondarwin** [comment] 2020-03-18 12:05
Glad you got it sorted. The error you just reported is expected as we have not provided the target locale for the translation. The CLI does this for you. You should be able to fix that (if you wanted) by providing ` --target-locales fr` I believe
