### ISSUE TITLE
clang-format should not break link tags in comments

### ISSUE THREAD

**Issue by naomiblack** [angular/angular#2287] opened 2015-06-02 15:49 UTC
The line wrap reformat introduced by clang-format has made the doc comments break oddly. This is mostly an aesthetic annoyance when browsing the code, but in some cases, where the formatter breaks a link tag such as `{@link annotations/onChange}` across lines, our dgeni doc formatter can't resolve the link.

Can we make clang-format smarter about how it breaks lines? Or, make dgeni more tolerant of linebreaks in link statements?

**Comment by naomiblack** [comment] 2015-06-02 15:49
@petebacondarwin @IgorMinar would be interested in what the best way to solve this is.

**Comment by petebacondarwin** [comment] 2015-06-02 19:08
I think we might be able to make dgeni more tolerant but the output from clang is particularly ugly in this regard and I think it should be fixed too

**Comment by IgorMinar** [comment] 2015-06-19 21:54
@mprobst what's the effort for teaching clang-format not to break lines within `{@...}` in comment blocks? it's kind of domain specific to javascript and jsdoc, but it would be nice if we didn't break it.

@petebacondarwin regardless of the formatting, dgeni should be able to deal with the linebreaks. can you estimate the effort please?

**Comment by mprobst** [comment] 2015-06-19 22:01
Shouldn't be too hard, it has the same functionality for comments in Java already, iirc. I'll file a bug.

**Comment by IgorMinar** [comment] 2015-06-19 22:11
```
/**
 * *Component Injectors*: Each component instance has its own {@link something really long here baba baba booo Injector}, and they follow
*/
```

should break into:

```
/**
 * *Component Injectors*: Each component instance has its own
 * {@link something really long here baba baba booo Injector}, and they follow
 */

and not:

```
/**
 * *Component Injectors*: Each component instance has its own {@link something really long here
 * baba baba booo Injector}, and they follow
 */
```

**Comment by mprobst** [comment] 2015-06-19 22:34
@IgorMinar what if the text within {@link} is longer than one line?

**Comment by petebacondarwin** [comment] 2015-06-20 09:02
I thought that dgeni was resilient to these line breaks now anyway. Can you provide a reproduction where it breaks?

**Comment by mhevery** [comment] 2015-08-20 18:36
@naomiblack looks like `dgeni` is resilient. I am going to close. Please provide a specific use case if you reopen.

**Closed by mhevery** 2015-08-20 18:36 UTC
Labels: comp: build/dev-productivity, effort2: medium (day), P1: urgent, state: Periodic Review, type: bug
