### ISSUE TITLE
Number input fires valueChanges twice

### ISSUE THREAD

**Issue by manofearth** [angular/angular#12540] opened 2016-10-26 08:27 UTC
May be bug.

ReactiveFormsModule. Input with type "number" fires valueChanges event twice when changed from browser.

I expect it to fire valueChanges once.

Here is a plunkr example: https://plnkr.co/edit/HYCtlP72W3edsaZe9HtR?p=preview

I use ngrx/store to manage state and subscribe my store to valueCahnges observable. When I change value of input, reducers fires twice. It is not optimal, I suppose.

Angular version: 2.1.0

Browser: Chrome

**Comment by robwormald** [comment] 2016-10-26 08:30
Hmm, yeah, looks like a bug to me. We're listening to both events https://github.com/angular/angular/blob/master/modules/%40angular/forms/src/directives/number_value_accessor.ts#L34-L35 - depending on the browser, that'll fire twice in certain scenarios.

cc @kara

**Comment by buddyackerman** [comment] 2016-12-20 17:07
Curious if this is going to be fixed soon.

**Comment by buddyackerman** [comment] 2017-02-02 15:42
This has been open for quite a while, is it going to be fixed soon?

**Comment by DzmitryShylovich** [comment] 2017-02-02 15:45
@buddyackerman browser?

**Comment by buddyackerman** [comment] 2017-02-02 16:00
@DzmitryShylovich  Chrome, FF, IE11

**Comment by DzmitryShylovich** [comment] 2017-02-02 16:10
We will be able to fox it when https://github.com/angular/angular/pull/12990 will be merged

**Comment by buddyackerman** [comment] 2017-02-02 16:17
@DzmitryShylovich OK, any idea when that will be?

**Comment by DzmitryShylovich** [comment] 2017-02-02 16:18
no idea :)

**Comment by robachma** [comment] 2017-02-26 22:54
Wondering when this will be fixed. I think it is causing the same issue that I am facing. 

`setValue() { 
    this.myForm.controls['control1'].valueChanges.subscribe({
      next: (change) => {
        if (change = 'Yes') {
          this.myForm.controls['controlGroup'].enable() 
        }
        else if (change = 'No') {
          this.myForm.controls['controlGroup'].disable();
        }      
      }        
    });` 

Using a radio button for this. When the value changes to 'Yes', it is working as expected. But when 'No' is selected, it does not disable my control group. 

Not positive if these are related. Please help. Thx

**Comment by makiJS** [comment] 2017-06-08 08:27
+
version "@angular/forms": "2.0.0"

**Comment by ebem** [comment] 2017-06-12 09:44
+1  "@angular/forms": "^4.0.0"

**Comment by ChrisDevinePimss** [comment] 2017-07-26 10:04
am still getting this issue in latest angular, any idea on a fix date?

**Comment by sebinbenjamin** [comment] 2017-08-15 19:25
same issue in "@angular/forms": "4.2.3",

**Comment by michellequack** [comment] 2017-10-12 19:48
This is actually a huge issue for us.  We send significant data back to the server on some changes (customer requirement for autosave) and it is causing our application to be just too slow to use angular reactive forms.  Is there any chance at all that this will be fixed soon?

**Comment by dgroh** [comment] 2017-11-10 12:30
+1

**Comment by tomas-cani** [comment] 2017-11-24 13:48
+1
Same problem as you @michellequack. As a temporary workaround you may want to use [distinctUntilChanged](http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html#instance-method-distinctUntilChanged)

**Comment by MSAJJAN-EEOC** [comment] 2017-12-26 22:25
@michellequack. Awesome. it works for me

**Comment by manichandra** [comment] 2017-12-26 22:28
Thanks @tomas-cani . It works perfectly. Used Observable.fromEvent() to capture the (onchange) event. I am using it for file upload feature.

**Comment by carlospalacin** [comment] 2018-01-08 16:28
same issue in "@angular/forms": "5.1.3"

**Comment by magoss** [comment] 2018-03-08 13:53
+1

**Comment by RockGuitarist1** [comment] 2018-03-15 17:59
Having this same issue on v5.2.9. Causing multiple API hits on component load.

**Comment by Provson** [comment] 2018-04-17 12:15
Same issue on v5.2.10, any idea ?

**Comment by Provson** [comment] 2018-04-24 09:16
`<input type="number" (ngModelChange)="myFonction($event)">` fires myFonction twice
`<input type="number" (change)="myFonction($event)">` fires myFonction once

**Comment by davidgg** [comment] 2018-04-27 09:37
You can use input to avoid onblur events too

`<input type="number" (input)="myFunction($event)">`

**Comment by valmirphp** [comment] 2018-08-15 06:14
Export helper `jsonEqual`

```ts
export function jsonEqual(a, b): boolean {   
    return JSON.stringify(a) === JSON.stringify(b);   
}   
``` 

Use pipe `distinctUntilChanged`

```ts
this.form     
            .valueChanges
            .pipe(distinctUntilChanged((a, b) => jsonEqual(a, b)))
            .subscribe(values => ....);
```

**Comment by jgbpercy** [comment] 2019-02-05 21:51
A workaround that I haven't seen posted above...

For some reason this works: 
```
<input [type]="'number'" formControlName="whatever" />
```

But as has been noted, this does not work (fires too many valueChanges):
```
<input type="number" formControlName="whatever" />
```

Stackblitz here: https://stackblitz.com/edit/angular-yamx3e

**Comment by NurRehman** [comment] 2019-02-14 14:57
`<input **[type]="'number'"** formControlName="whatever" />`
Providing **type** in **'number'**  in single quote will not emit the value twice but will always cast the value in string instead of number. FYI

**Comment by mattiLeBlanc** [comment] 2019-03-06 05:31
Having same issue with Angular 7, using ReactiveForms. Added a custom validation which triggers twice now because i am using `onUpdate: change` for a `matInput` with `type=number`. This is pretty annoying because I am validating that field to be a unique number, but when it runs the second time it is not considered unique.
I can remove `type=text` but then I have to cast it everywhere.
Any update on when this is resolved?

**Comment by SamuelCox** [comment] 2019-03-12 14:33
Is there any timeline on this? It's a pretty big deal, with seemingly a high frequency and high severity?

**Comment by Egorvoz** [comment] 2019-03-21 14:32
Google what's up? What is the progress of it?

**Comment by yankee42** [comment] 2019-03-25 09:38
> For some reason this works:
> 
> ```
> <input [type]="'number'" formControlName="whatever" />
> ```

The reason this works is because the `NumberValueAccessor` [works only on input[type=number]](https://github.com/angular/angular/blob/cfe6581fc8c292dc7aa1aac07a461de64ebf1c36/packages/forms/src/directives/number_value_accessor.ts#L45) and when you write `[type]="'number'"` the attribute `type="number"` will be set AFTER compilation an thus the `NumberValueAccessor` will not be used and angular treats the field as a normal text field.

**Comment by Falci** [comment] 2019-05-01 13:23
UP~date~?

**Comment by FrancescoBorzi** [comment] 2019-06-07 22:44
Confirmed on:

```
Angular CLI: 8.0.2
Node: 10.16.0
OS: linux x64
Angular: 8.0.0
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.2
@angular-devkit/build-angular     0.800.2
@angular-devkit/build-optimizer   0.800.2
@angular-devkit/build-webpack     0.800.2
@angular-devkit/core              8.0.2
@angular-devkit/schematics        8.0.2
@angular/cli                      8.0.2
@angular/http                     7.2.15
@ngtools/webpack                  8.0.2
@schematics/angular               8.0.2
@schematics/update                0.800.2
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.30.0
```

**Comment by mekbeb** [comment] 2019-06-20 04:32
> Temporary solution:
> 
> ```
> this._form.valueChanges.pipe(
>       distinctUntilChanged((a, b) => JSON.stringify(a) === JSON.stringify(b))
>     ).subscribe(() => {
>     // ...
> });
> ```
> 
> Bug confirmed on:
> 
> ```
> Angular CLI: 8.0.2
> Node: 10.16.0
> OS: linux x64
> Angular: 8.0.0
> ... animations, common, compiler, compiler-cli, core, forms
> ... platform-browser, platform-browser-dynamic, router
> 
> Package                           Version
> -----------------------------------------------------------
> @angular-devkit/architect         0.800.2
> @angular-devkit/build-angular     0.800.2
> @angular-devkit/build-optimizer   0.800.2
> @angular-devkit/build-webpack     0.800.2
> @angular-devkit/core              8.0.2
> @angular-devkit/schematics        8.0.2
> @angular/cli                      8.0.2
> @angular/http                     7.2.15
> @ngtools/webpack                  8.0.2
> @schematics/angular               8.0.2
> @schematics/update                0.800.2
> rxjs                              6.5.2
> typescript                        3.4.5
> webpack                           4.30.0
> ```

That worked for me. tnx

**Comment by keatkeat87** [comment] 2019-07-22 02:40
same issue here 8.1.1
when input type=number unblur the valueChanges fire again.

**Comment by JonMarbach** [comment] 2019-07-30 21:43
+1 Would love to see this fixed.

**Comment by theCrius** [comment] 2019-08-19 15:24
Unbelievable that this problem exists since 2.1.x and in Angular 8.x we still have it around.

**Comment by p0rsche** [comment] 2019-08-28 13:41
I'd like to subscribe on this.

**Comment by bennawanda** [comment] 2019-09-02 08:19
Same problem

**Comment by boredomkillsme91** [comment] 2019-09-08 00:13
I also have the same problem.

**Comment by ADudar** [comment] 2019-09-13 09:02
i also run into this problem.
I've changed to attribute binding and add validator for maxlength where it was needed
it seems working...

**Comment by mucbits** [comment] 2019-09-29 06:42
> same issue here 8.1.1
> when input type=number unblur the valueChanges fire again.

same here, unblur fire again for input type=number

**Comment by pieterdb4477** [comment] 2019-12-12 13:12
This fires my async validator twice and blocks my submit button in the progres.. :/

**Comment by dimiork** [comment] 2020-01-09 10:03
Temporary solution: RXJS debounceTime operator: https://www.learnrxjs.io/operators/filtering/debouncetime.html`

**Comment by SLGShark6** [comment] 2020-01-09 19:41
[https://gist.github.com/SLGShark6/806b5f756db48dbe69da24fbaa92e23d](https://gist.github.com/SLGShark6/806b5f756db48dbe69da24fbaa92e23d)

**Comment by traviskaufman** [comment] 2020-01-10 15:10
Just an FYI that this basically makes number fields impossible to use with async validators 😄. Are @kara @robwormald are you open to contributions for a fix? This really seems like something that if fixed could really improve DX and lead to less surprises.

**Comment by deumax** [comment] 2020-01-13 15:26
I experienced a similiar issue with text input fields, but it was a different problem.
I have a custom component which emits an event if form values change. The problem was that I named the output event 'change', which was fired a second time (presumedly on blur). Renaming 'change' to 'filterChange' fixed my problem.

**Comment by traviskaufman** [comment] 2020-01-18 22:28
FWIW I was able to fix the number fields issue I mentioned above by creating a custom directive extending `NumberValueAccessor`. This class stores any previous values emitted by the host element,  and implements `@HostListener('input')` and `@HostListener('change')` which only call `onChange()` if the given value is different than the stored value. Might not be perfect for every use-case but worked for mine!

```ts
import {Directive, HostListener, forwardRef} from '@angular/core';
import {NumberValueAccessor, NG_VALUE_ACCESSOR} from '@angular/forms';

export const FIXED_NUMBER_VALUE_ACCESSOR: any = {
  provide: NG_VALUE_ACCESSOR,
  useExisting: forwardRef(() => FixedNumberValueAccessor),
  multi: true
};

@Directive({
  selector: 'input[type=number][formControl][fixedNumberField],input[type=number][formControlName][fixedNumberField],input[type=number][ngModel][fixedNumberField]',
  providers: [FIXED_NUMBER_VALUE_ACCESSOR],
})
export class FixedNumberValueAccessor extends NumberValueAccessor {
  private lastValue: string;
  
  @HostListener('change', ['$event.target.value']) handleOnChange(value) {
    this.handleUpdate(value);
  }

  @HostListener('input', ['$event.target.value']) handleOnInput(value) {
     this.handleUpdate(value);
  }

  private handleUpdate(value: string) {
    if (value === this.lastValue) {
      return;
    }
    this.lastValue = value;
    this.onChange(value);
  }
}
```

[StackBlitz](https://stackblitz.com/edit/fixed-number-value-accessor)

Would love to see a longer-term fixed prioritized and merged into core 😄

**Comment by SLGShark6** [comment] 2020-01-19 17:08
> FWIW I was able to fix the number fields issue I mentioned above by creating a custom directive extending `NumberValueAccessor`. This class stores any previous values emitted by the host element, and implements `@HostListener('input')` and `@HostListener('change')` which only call `onChange()` if the given value is different than the stored value. Might not be perfect for every use-case but worked for mine!
> 
> ```ts
> import {Directive, HostListener, forwardRef} from '@angular/core';
> import {NumberValueAccessor, NG_VALUE_ACCESSOR} from '@angular/forms';
> 
> export const FIXED_NUMBER_VALUE_ACCESSOR: any = {
>   provide: NG_VALUE_ACCESSOR,
>   useExisting: forwardRef(() => FixedNumberValueAccessor),
>   multi: true
> };
> 
> @Directive({
>   selector: 'input[type=number][formControl][fixedNumberField],input[type=number][formControlName][fixedNumberField],input[type=number][ngModel][fixedNumberField]',
>   providers: [FIXED_NUMBER_VALUE_ACCESSOR],
> })
> export class FixedNumberValueAccessor extends NumberValueAccessor {
>   private lastValue: string;
>   
>   @HostListener('change', ['$event.target.value']) handleOnChange(value) {
>     this.handleUpdate(value);
>   }
> 
>   @HostListener('input', ['$event.target.value']) handleOnInput(value) {
>      this.handleUpdate(value);
>   }
> 
>   private handleUpdate(value: string) {
>     if (value === this.lastValue) {
>       return;
>     }
>     this.lastValue = value;
>     this.onChange(value);
>   }
> }
> ```
> 
> [StackBlitz](https://stackblitz.com/edit/fixed-number-value-accessor)
> 
> Would love to see a longer-term fixed prioritized and merged into core 😄

See my comment above, for just completely replacing it in the DI container,
[https://gist.github.com/SLGShark6/806b5f756db48dbe69da24fbaa92e23d](https://gist.github.com/SLGShark6/806b5f756db48dbe69da24fbaa92e23d)

**Comment by turulb** [comment] 2020-01-23 14:44
+1

**Comment by marcodafonseca** [comment] 2020-01-24 04:38
+1
Discovered this bug recently. It affects my forms where calculations are done from a mobile device. Older devices get terribly slow to hide the keyboard due to events firing twice

**Comment by mrpharderwijk** [comment] 2020-02-01 20:55
+1
I got this on an input with [(ngModel)] & (ngModelChange), the ngModelChange function is called twice. If I change my setup for using formControls and subscribe to the valueChanges it fires twice too, so this doesn't make a difference...

**Comment by andreyinkin** [comment] 2020-02-04 00:02
+1
The issue occurs only when clicking up or down arrows on the input fiewld

**Comment by musk-coding** [comment] 2020-03-11 09:28
+1
Got the same problem, no fix coming soon :) ?

**Comment by laptrinhvien1994** [comment] 2020-03-13 03:22
+1
I got the same issue.
For now, I used RxJS operator to handle it.

**Closed** 2020-05-07 17:20 UTC
Labels: comp: forms, freq3: high, severity3: broken, type: bug/fix

**Comment by maxdulieu** [comment] 2020-05-07 17:44
Right on!

**Comment by theCrius** [comment] 2020-05-08 11:01
OMG I can't believe it! I'll have to go back and remove all the workaround now 🤣 👏

**Comment by andreElrico** [comment] 2020-05-12 08:09
I was about to file an issue: https://stackblitz.com/edit/angular-ahq3v1?file=src/app/hello.component.ts

Wow, its been open for almost 4 years despite being a performance killer and easy to fix.

Thanks Alex for fixing <3

**Comment by Splaktar** [comment] 2020-05-31 05:36
> We needed a pandemic to have the time to fix this issue :D

That wasn't quite it. There was a blocker to fixing this that was finally resolved.
