### ISSUE TITLE
NgForm.hasError() does not return expected result when using more than one path

### ISSUE THREAD

**Issue by hanct** [angular/angular#28109] opened 2019-01-13 05:13 UTC
Angular : 7.0.0

Hi, I am writing angular code for form validation using template driven method. Both my typescript codes

<pre>
ngForm.hasError('required',['<b>startId</b>'])
ngForm.hasError('required',['<b>numOfId</b>'])
</pre>

return true, which is as expected, since both my input fields with the name attribute startId and numOfId is empty.  But when i do this
<pre>
ngForm.hasError('required',['<b>startId</b>','<b>numOfId</b>'])
</pre>
it returns false.  Is this a bug in the framework code? or did i have misunderstanding how the hasError 's path parameter works?

**Comment by manklu** [comment] 2019-01-13 09:20
```typescript
ngForm.hasError('required',['startId','numOfId'])
```
is equivalent to
```typescript
this.root.get('startId').get('numOfId').hasError('required')
```

**Comment by hanct** [comment] 2019-01-13 10:49
> ```ts
> ngForm.hasError('required',['startId','numOfId'])
> ```
> 
> is equivalent to
> 
> ```ts
> this.root.get('startId').get('numOfId').hasError('required')
> ```

Thanks for the response. But can briefly explain "this.root" refers to what object? i couldn't uderstand on what this   **get('startId').get('numOfId') means.**

**Comment by manklu** [comment] 2019-01-13 11:17
@hanct Sorry, Copy and paste error

```typescript
ngForm.get('startId').get('numOfId').hasError('required')
```

**Comment by hanct** [comment] 2019-01-13 11:50
Hi, Thanks for the response. but I still dont quite get the idea how get('startId').get('numOfid') work..it seem like I am trying to get a form control from another form control. 
Most importantly is under what circumstance does having more than 1 path in hasError method be feasible to be used?

initially, i thought that ngForm.hasError('required',['startId','numOfId']) will return true, if any of the listed path does not meet the 'required' validation. Seem like my thinking is wrong.

> @hanct Sorry, Copy and paste error
> 
> ```ts
> ngForm.get('startId').get('numOfId').hasError('required')
> ```

**Comment by kara** [comment] 2019-01-22 23:51
@hanct As @manklu mentioned, the second argument is an array that represents the path to one control (you cannot provide multiple paths). You can read more about how to construct a path in our docs for `hasError`:

https://angular.io/api/forms/AbstractControl#haserror

Closing, as this works as intended.

**Closed by kara** 2019-01-22 23:51 UTC
Labels: comp: forms
