### ISSUE TITLE
Ivy: NGCC incorrectly compiles the "@ngxs/router-plugin" as UMD

### ISSUE THREAD

**Issue by arturovt** [angular/angular#34191] opened 2019-12-02 19:18 UTC
# 🐞 bug report

### Affected Package
@angular/compiler-cli

### Is this a regression?

Yes

### Description

The NGCC incorrectly compiles the `@ngxs/router-plugin` as UMD.

## 🔬 Minimal Reproduction
https://github.com/arturovt/ivy-ngxs-router-plugin-umd-repro

* clone and install dependencies
* check the `postinstall` script

Or open the `node_modules/@ngxs/router-plugin/bundles/ngxs-router-plugin.umd` file in your IDE and see the generated code at the end of the `factory(....)` function. This has to be something like `global...modules.ngxsFeature.module`.

Providing screenshot below (this is how it looks like on my PC):

![image](https://user-images.githubusercontent.com/7337691/69987873-25407a80-1549-11ea-8935-eda123d432c9.png)

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.0.0-rc.4
Node: 12.11.1
OS: linux x64

Angular: 9.0.0-rc.4
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-rc.4
@angular-devkit/build-angular     0.900.0-rc.4
@angular-devkit/build-optimizer   0.900.0-rc.4
@angular-devkit/build-webpack     0.900.0-rc.4
@angular-devkit/core              9.0.0-rc.4
@angular-devkit/schematics        9.0.0-rc.4
@ngtools/webpack                  9.0.0-rc.4
@schematics/angular               9.0.0-rc.4
@schematics/update                0.900.0-rc.4
rxjs                              6.5.3
typescript                        3.6.4
webpack                           4.41.2
</code></pre>

---

**UPD**

I could guess that it emits such code due to the inability to compile this package at all. The compiler behaves differently, because:

* in 80% of cases it compiles without errors and generates such code
* in 20% of cases it throws during compilation with:
```
Error: Error on worker #1: Error: Failed to compile entry-point @ngxs/router-plugin due to compilation errors:
node_modules/@ngxs/router-plugin/bundles/ngxs-router-plugin.umd.js(1034,34): error TS-991010: Value at position 0 in the NgModule.imports of NgxsRouterPluginModule is not a reference: [object Object]
```

**Comment by arturovt** [comment] 2019-12-02 19:18
@JoostK CC.

**Comment by arturovt** [comment] 2019-12-04 18:57
I've debugged a little bit, and it seems like it resolves invalid `directImport`:

https://github.com/angular/angular/blob/44623a116158c8048ce61a873ed63a290c039202/packages/compiler-cli/src/ngtsc/reflection/src/typescript.ts#L553-L556

It returns a `NodeObject` which has an `moduleSpecifier` property. In my case the `moduleSpecifier.text` equals `'./modules/ngxs-feature.module'`. 

If I manually change it to something like (just for debugging purposes):
```ts
if (importDecl.moduleSpecifier.text === './modules/ngxs-feature.module') {
  importDecl.moduleSpecifier.text = '@ngxs/store'
}
```

Then it works like a charm and the UMD file is emitted w/o errors.

**Comment by markwhitfeld** [comment] 2019-12-05 18:25
@mgechev do you now who would be the best to look into this from the Angular Ivy team side?

**Comment by markwhitfeld** [comment] 2019-12-05 18:26
This is our last hurdle to releasing a fully Ivy compatible version of NGXS.

**Comment by splincode** [comment] 2019-12-09 10:46
@petebacondarwin Could you see how it turns out that?

https://circleci.com/gh/ngxs/store/23968?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

```
Compiling @angular/platform-browser/animations : fesm2015 as esm2015
Error: Error on worker #8: Error: Failed to compile entry-point @angular/platform-browser due to compilation errors:
node_modules/@angular/core/core.d.ts(259,22): error TS-996003: Appears in the NgModule.exports of BrowserModule, but could not be resolved to an NgModule, Component, Directive, or Pipe class

    at ClusterWorker.compile (/home/circleci/workspace/app/integrations/ivy/node_modules/@angular/compiler-cli/ngcc/src/main.js:170:27)
    at Worker.<anonymous> (/home/circleci/workspace/app/integrations/ivy/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/worker.js:41:42)
```

![image](https://user-images.githubusercontent.com/12021443/70429681-27935f00-1a8a-11ea-8dcc-4a5d8aa62521.png)

**Comment by petebacondarwin** [comment] 2019-12-09 11:51
I'll take a look today

**Comment by petebacondarwin** [comment] 2019-12-10 12:08
Quick update... I am a bit lost on what is happening here.
What I can say is that if you set `--async false` on the ngcc invocation it does not appear to fail - at least in the numerous times I have tried it.

**Comment by gkalpak** [comment] 2019-12-10 12:23
Smells like a dependency detection failure. I've had such issues with CommonJS (will be fixed in #34169 for most common usecases), but the same is true for UMD (iirc).

**Comment by arturovt** [comment] 2019-12-10 21:29
@petebacondarwin 

Hey. I've tried your approach with `--async false`, but it didn't help. See the screenshot below:

![image](https://user-images.githubusercontent.com/7337691/70570530-c01e0200-1ba4-11ea-9b87-e72b47e35c37.png)

**Note:** those 3 dots at `global...modules.ngxsFeature.module`, they are added during compilation.

See this comment also https://github.com/angular/angular/issues/34191#issuecomment-561789290

**Comment by markwhitfeld** [comment] 2019-12-11 07:56
Thank you so much for looking into this! Just to make sure that we are debugging the same issue please look at the issue description and @arturovt 's comments. I'm not sure if the issue that @splincode mentioned is related.
Is there any way to test if this is resolved with the PR that @gkalpak mentioned?

**Comment by gkalpak** [comment] 2019-12-11 11:04
Sorry, I now realize I was had the error mentioned in https://github.com/angular/angular/issues/34191#issuecomment-563176252 in mind (which you said is likely unrelated). So, my PR won't help with your original issue 😅

**Comment by petebacondarwin** [comment] 2019-12-11 12:00
@arturovt - sorry I was testing with some local changes (e..g https://github.com/angular/angular/pull/34254) and a small custom fix. With those in-place I could not get it to fail in non-async mode.
Still working on it...

**Comment by petebacondarwin** [comment] 2019-12-11 12:34
I updated the https://github.com/arturovt/ivy-ngxs-router-plugin-umd-repro repository to point at the latest `dev` versions of `@ngxs/router-plugin` and `@ngxs/store`, which is `3.5.1-dev.master-7a75f33` and with the latest Angular `next` release (`9.0.0-rc.4`) I no longer get the error above (i.e. the `global...modules.ngxsFeature.module`).

Instead we are back to our old friend:

```
Compiling @ngxs/router-plugin : main as umd
Error: Error on worker #3: Error: Failed to compile entry-point @ngxs/router-plugin due to compilation errors:
node_modules/@ngxs/router-plugin/bundles/ngxs-router-plugin.umd.js(1034,34): error TS-991010: Value at position 0 in the NgModule.imports of NgxsRouterPluginModule is not a reference: [object Object]
```

**Comment by petebacondarwin** [comment] 2019-12-11 12:56
Updating Angular to use the artifacts from https://github.com/angular/angular/pull/34254 removes this error and the ngcc processing seems to complete without error.

That being said I now see that it adds an incorrect export into the `node_modules/@ngxs/store/ngxs-store.d.ts` file:

```
export {ɵl as NgxsRootModule} from './src/modules/ngxs-root.module';
export {ɵx as NgxsFeatureModule} from './src/modules/ngxs-feature.module';
```

It is confusing the public export from this file:

```
export { NgxsFeatureModule as ɵx } from './src/modules/ngxs-feature.module';
export { NgxsRootModule as ɵl } from './src/modules/ngxs-root.module';
```

with the exports from the referenced files.

**Comment by petebacondarwin** [comment] 2019-12-11 19:35
Actually it additionally needs this PR to complete successfully: https://github.com/angular/angular/pull/34356

**Comment by petebacondarwin** [comment] 2019-12-12 08:40
OK so now that #34356 has landed, I believe that #34254 should be enough to fix this package, assuming that you are using the latest `dev` version of the package. Hopefully it will be merged this week and appear in the next RC next week.

**Comment by splincode** [comment] 2019-12-21 17:45
@petebacondarwin fixed Angular 9.rc-7
https://github.com/ngxs/store/pull/1506

**Comment by petebacondarwin** [comment] 2019-12-22 09:37
Great. Thanks for the update!

**Closed by petebacondarwin** 2019-12-22 09:37 UTC
Labels: comp: ngcc, state: has PR, type: bug/fix

**Comment by mgechev** [comment] 2020-01-06 20:38
@splincode would you add a regression test in [angular/ngcc-validation](https://github.com/angular/ngcc-validation)?
