### ISSUE TITLE
Angular SSR not waiting for HTTP request

### ISSUE THREAD

**Issue by walec51** [angular/angular#53913] opened 2024-01-14 21:55 UTC
### Which @angular/* package(s) are the source of the bug?

platform-server

### Is this a regression?

Yes

### Description

We have upgraded to Angular 17 recently and noticed that some parts of your DOM stopped getting rendered in SSR.

On some pages this behavior was consisted - sections that ware always present before the upgrade stopped getting rendered.

On other pages it looked like a race condition - sometimes it rendered sometimes it did not.

No error messages in the logs.

We added an interceptor to log everything that happened around HTTP API calls done by HttpClient and we noticed that some requests got there observables unsubscribed and never logged a response from the server. Our server logs on the other hand reported that the server has correctly responded in ~100ms.

On forums we noted that some resolved this problem by wrapping their API call to ensure they are macrotasks. Eg.: https://stackoverflow.com/a/66699719

I've also notices this article: https://dev.to/krisplatis/angular-ssr-v16-saying-goodbye-to-a-sneaky-trick-macrotask-wrapping-for-http-calls-487b

from which I understand that Angular stopped doing that because of a better solution. I don't think however that it works.

We found a more elegant solution by adding `provideHttpClient(withFetch())` to ours `AppServerModeul` providers <- theoretically this should have not changed anything but practice it solved the problem.

In conclusion I think that there is a bug lurking here or at least the documentation should state that   `provideHttpClient(withFetch())` is not only the preferred way but the required way for a working SSR app.

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.0.8
Node: 20.10.0
Package Manager: npm 10.2.3
OS: win32 x64

Angular: 17.0.8
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router, ssr

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.8
@angular-devkit/build-angular   17.0.8
@angular-devkit/core            17.0.8
@angular-devkit/schematics      17.0.8
@angular/cdk                    17.0.4
@angular/flex-layout            15.0.0-beta.42
@angular/material               17.0.4
@schematics/angular             17.0.8
ng-packagr                      17.0.3
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.2
```

**Comment by JeanMeche** [comment] 2024-01-14 22:23
How did you setup your HttpModule/http providers in your `AppServerModule` before `provideHttpClient(withFetch())` ?

**Comment by walec51** [comment] 2024-01-14 22:41
before `provideHttpClient(withFetch())` we just had

```
@NgModule({

  imports: [
    HttpClientModule,
    ...
```

**Comment by alan-agius4** [comment] 2024-01-15 10:27
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by alfmos** [comment] 2024-01-19 11:23
Hi @alan-agius4, I have the same issue and I have managed to create a repro.
[https://stackblitz.com/github/alfmos/angular-ssr-test-fetch](https://stackblitz.com/github/alfmos/angular-ssr-test-fetch)
Let me know if I can help in some other way.
Of course if you prefer github source it is here
[https://github.com/alfmos/angular-ssr-test-fetch](https://github.com/alfmos/angular-ssr-test-fetch)

**Comment by alan-agius4** [comment] 2024-01-19 11:42
@alfmos, thanks for the reproduction. However it does seem that it is working as expected.

```
yarn ssr:build:serve
yarn run v1.22.19
warning ../package.json: No license field
$ ng build && node dist/test-angular/server/server.mjs
bored: {
  activity: 'Make a new friend',
  type: 'social',
  participants: 1,
  price: 0,
  link: '',
  key: '1000000',
  accessibility: 0
Prerendered 1 static route.


Initial Chunk Files   | Names           |  Raw Size | Estimated Transfer Size
chunk-CUHAP6RZ.js     | -               | 124.69 kB |                36.48 kB
main-N2BBKZ2G.js      | main            |  83.96 kB |                21.45 kB
polyfills-RX4V3J3S.js | polyfills       |  33.01 kB |                10.68 kB
styles-5INURTSO.css   | styles          |   0 bytes |                 0 bytes

                      | Initial Total   | 241.67 kB |                68.60 kB

Lazy Chunk Files      | Names           |  Raw Size | Estimated Transfer Size
chunk-R4CAWUFA.js     | bored-component | 972 bytes |               972 bytes

Application bundle generation complete. [10.051 seconds]
Node Express server listening on http://localhost:4000
request:  http://localhost:4000/bored
html:  <!DOCTYPE html><html lang="en" data-critters-container><head>
  <meta charset="utf-8">
  <title>TestAngular</title>
  <base href="/">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
<link rel="stylesheet" href="styles-5INURTSO.css"><link rel="modulepreload" href="chunk-CUHAP6RZ.js"></head>
<body>
  <app-root _nghost-ng-c396512821 ng-version="17.1.0" ng-server-context="ssg"><h1 _ngcontent-ng-c396512821>App running</h1><nav _ngcontent-ng-c396512821><a _ngcontent-ng-c396512821 routerlink="/bored"> Go to bored </a></nav><router-outlet _ngcontent-ng-c396512821></router-outlet><app-bored _nghost-ng-c436716051><p _ngcontent-ng-c436716051>bored works!</p><button _ngcontent-ng-c436716051>
Carica
</button><div _ngcontent-ng-c436716051> Result: {
  "activity": "Make a new friend",
  "type": "social",
  "participants": 1,
  "price": 0,
  "link": "",
  "key": "1000000",
  "accessibility": 0
}
</div><div _ngcontent-ng-c436716051> Error: {}
</div></app-bored><!----></app-root>
<script src="polyfills-RX4V3J3S.js" type="module"></script><script src="main-N2BBKZ2G.js" type="module"></script>

</body></html>
```

In your case, the rendered view did not contain the response, because the request failed with a timeout.
```
  message: 'Http failure response for https://www.boredapi.com/api/activity: 0 undefined',
  error: TypeError: fetch failed
      at Object.fetch (node:internal/deps/undici/undici:14062:11)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
    cause: ConnectTimeoutError: Connect Timeout Error
```

**Comment by alfmos** [comment] 2024-01-19 11:55
@alan-agius4, the code works perfectly client-side, and fails always server side. 
Does the universal engine has different timeouts for fetch?
What should I do to make it working on SSR side?
The api is a public one and it answers always with some hundred milliseconds. 
I see something not working here. Am I wrong ?

**Comment by alan-agius4** [comment] 2024-01-19 12:22
This might be related https://github.com/nodejs/undici/issues/1531 which is fetch implementation of Node.js.

**Comment by alfmos** [comment] 2024-01-19 12:34
Angular CLI: 17.0.7
Node: 18.13.0
Package Manager: npm 9.6.4
OS: win32 x64

Angular: 17.0.6
... animations, common, compiler, compiler-cli, core, forms    
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                         Version
---------------------------------------------------------      
@angular-devkit/architect       0.1700.7
@angular-devkit/build-angular   17.0.7
@angular-devkit/core            17.0.7
@angular-devkit/schematics      17.0.7
@angular/cli                    17.0.7
@angular/ssr                    17.0.7
@schematics/angular             17.0.7
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.2
 I have nodejs 18.13.
The latest comment says with nodejs 20 the problem disappears. I am going to update it to 20 and will get back with feedback

**Comment by alfmos** [comment] 2024-01-19 13:51
I also tried what is currently working in our app:
```
export class ServerXhr implements XhrFactory {
	build(): XMLHttpRequest {
		xhr2.prototype._restrictedHeaders.cookie = false;
		return new xhr2.XMLHttpRequest();
	}
}


const serverConfig: ApplicationConfig = {
  providers: [
    { provide: XhrFactory, useClass: ServerXhr },
```
but nothing changes

**Comment by alfmos** [comment] 2024-01-19 16:29
I've tried on WSL (Ubuntu 22.04), and it works. On Windows, it doesn't

**Comment by JeanMeche** [comment] 2024-03-11 13:29
OP didn't provide a reproduction, we going to close this issue for now. If someone has a similar issue with a reproduction, feel free to open a new issue and we'll address it. Thank you.

**Closed by JeanMeche** 2024-03-11 13:29 UTC
Labels: needs reproduction, area: server, area: common/http
