### ISSUE TITLE
Memory leak while calling Renderer2.listen for parent elements

### ISSUE THREAD

**Issue by andrei-ilyukovich** [angular/angular#28288] opened 2019-01-22 09:24 UTC
# 🐞 bug report

### Affected Package
First time observed  in @angular 7.1.0, but reproducible in 7.2 as well

### Description

Lets say we have small application with root `<demo-app>` component and two routes which open `<first-component>` and `<second-component>` inside root one. `<first-component>` start listening for any root component event(`scroll` in example). The expected behavior is that after opening `<second-component>` the first one should be completely destroyed as far as all subscriptions are unsubscribed and listener dispose function was invoked as well. But actual behavior is that FirstComponent is still in the memory heap. If we switch between first and second component several times - several instances of FirstComponent are hanging in the heap that is memory leak, especially noticeable if component is huge.

On the screen below you can see that FirstComponent instance retains in memory because of DebugElement__PRE_R3__(corresponds to `demo-app`) still keeps listeners that added by Renderer2.listen before. And every listener keep reference to callback, and callback keeps reference to FirstComponent.

![image](https://user-images.githubusercontent.com/6919053/51522811-44578180-1e3b-11e9-9664-b734d16771fa.png)

## 🔬 Minimal Reproduction

Working example is available here:
https://stackblitz.com/edit/angular-renderer-listen-for-parent

## 🌍  Your Environment

**Angular Version:**
I've reproduced the bug in Angular@v7.* versions

**Comment by Shijir** [comment] 2019-01-29 00:11
I believe this shouldn't happen in production mode if this has to do with DebugElement__PRE_R3__. However, that doesn't mean it's not a bug.

**Comment by pkozlowski-opensource** [comment] 2019-01-29 19:50
This will be fixed in ivy since there are are not storing debug elements in memory but rather create them on-the-fly when requested.

**Comment by mhevery** [comment] 2020-02-15 00:23
Ivy release in v9.0.0 closing

**Closed by mhevery** 2020-02-15 00:23 UTC
Labels: comp: core, comp: testing, fixed by Ivy, freq2: medium, severity4: memleak, type: bug/fix
