### ISSUE TITLE
No way to pass custom typescript transformers through angular.json to AngularCompilerPlugin

### ISSUE THREAD

**Issue by nickbullock** [angular/angular#32437] opened 2019-09-01 14:44 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/cli

### Is this a regression?

 No

### Description

I want to pass platformTransformers property to AngularCompilerPlugin through angular.json, but i can't find any option for it.
I can only pass it directly to private property _transformers now using "customWebpackConfig"
```
const { AngularCompilerPlugin } = require('@ngtools/webpack');
const { MyTransformer } = require('./transformers');

module.exports = function (baseConfig, opts) {
  const AngularCompilerPluginInstance = baseConfig.plugins.find(plugin => plugin instanceof AngularCompilerPlugin);

  const defaultsTransformers = AngularCompilerPluginInstance._transformers;
  AngularCompilerPluginInstance._transformers = [MyTransformer, ...defaultsTransformers];

  return baseConfig;
}

```
So i think we need something like platformTransformers property (like we can use it with lazyModules property and pass it to AngularCompiler additionalLazyModules) in angular.json, and it will contains path to the file with transformers
```
"platformTransformers:" "./transformers.ts"
```

and transformers.ts is
```
module.exports = [MyTransformer1, MyTransformer2, ...]
```

I can make a PR.

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 8.3.0
Node: 10.15.3
OS: darwin x64
Angular: 8.2.3
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.0
@angular-devkit/build-angular     0.803.0
@angular-devkit/build-optimizer   0.803.0
@angular-devkit/build-webpack     0.803.0
@angular-devkit/core              8.3.0
@angular-devkit/schematics        8.3.0
@angular/cli                      8.3.0
@ngtools/webpack                  8.3.0
@schematics/angular               8.3.0
@schematics/update                0.803.0
rxjs                              6.5.2
typescript                        3.5.3
webpack                           4.39.2

</code></pre>

**Anything else relevant?**

**Comment by sharikovvladislav** [comment] 2019-09-01 17:33
Probably, for somebody it would be intersting to specify where to add transformer: before internal transformers or after.
So probably it can be done like this. 3 options, for example:

Default (internal then custom):
```
module.exports = [MyTransformer1, MyTransformer2, ...]
```

Pre:

```
module.exports = {
  transformers: [MyTransformer1, MyTransformer2],
  enforce: 'pre'
}
```
Post (same as default):

```
module.exports = {
  transformers: [MyTransformer1, MyTransformer2],
  enforce: 'post'
}
```

Pre post could be done as `enum`. Like: 

```
enum TransformAddStrategy {
  Pre,
  Post
}
```

**Comment by trotyl** [comment] 2019-09-02 07:56
Duplicate of https://github.com/angular/angular/issues/22434

**Comment by mhevery** [comment] 2019-09-03 22:34
closing as dup

**Closed by mhevery** 2019-09-03 22:34 UTC
