### ISSUE TITLE
updated to latest node-5.5.6, typings-0.6.8, angular-beta-5 and my NPM INSTALL fails

### ISSUE THREAD

**Issue by nhhockeyplayer** [angular/angular#7004] opened 2016-02-11 06:09 UTC
C:\apache-tomcat-8.0.23\webapps\ROOT\new\lps.transpile>typings search es6-promise
Showing 1 results...

NAME        SOURCE HOMEPAGE                                  DESCRIPTION
es6-promise npm    https://www.npmjs.com/package/es6-promise

C:\apache-tomcat-8.0.23\webapps\ROOT\new\lps.transpile>typings install --ambient --save es6-promise
? Found es6-promise typings for DefinitelyTyped. Continue? Yes
Installing es6-promise@~* (DefinitelyTyped)...

es6-promise
└── (No dependencies)

C:\apache-tomcat-8.0.23\webapps\ROOT\new\lps.transpile>typings install --ambient --save es6-collections
? Found es6-collections typings for DefinitelyTyped. Continue? Yes
Installing es6-collections@~0.5.1 (DefinitelyTyped)...

es6-collections
└── (No dependencies)

C:\apache-tomcat-8.0.23\webapps\ROOT\new\lps.transpile>typings install --ambient --save es6-collections

C:\apache-tomcat-8.0.23\webapps\ROOT\new\lps.transpile>
C:\apache-tomcat-8.0.23\webapps\ROOT\new\lps.transpile>
C:\apache-tomcat-8.0.23\webapps\ROOT\new\lps.transpile>
C:\apache-tomcat-8.0.23\webapps\ROOT\new\lps.transpile>npm install
npm WARN deprecated object-pick@0.1.2: Deprecated as of version 0.1.2 please use object.pick instead.
npm WARN prefer global typings@0.6.6 should be installed with -g

> angular2@2.0.0-beta.5 postinstall C:\apache-tomcat-8.0.23\webapps\ROOT\new\lps.transpile\node_modules\angular2
> typings install --ambient --name es6-promise github:DefinitelyTyped/DefinitelyTyped/es6-promise/es6-promise.d.ts#830e8ebd9ef137d039d5c7ede24a421f08595f83; typings install --ambient --name es6-collections github:DefinitelyTyped/DefinitelyTyped/es6-collections/es6-collections.d.ts#9f97e2a2bc1f502550c9b4fcaad1c48df5521d37

? What is the dependency name? es6-promise
typings ERR! message Unable to read typings for "es6-promise". You should check the path is correct
typings ERR! caused by https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/830e8ebd9ef137d039d5c7ede24a421f08595f83;/es6-promise/es6-promise.d.ts responded with 404, expected it to equal 200

typings ERR! cwd C:\apache-tomcat-8.0.23\webapps\ROOT\new\lps.transpile\node_modules\angular2
typings ERR! system Windows_NT 10.0.10586
typings ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\apache-tomcat-8.0.23\\webapps\\ROOT\\new\\lps.transpile\\node_modules\\typings\\dist\\bin\\typings-install.js" "--ambient" "--name" "es6-promise" "github:DefinitelyTyped/DefinitelyTyped/es6-promise/es6-promise.d.ts#830e8ebd9ef137d039d5c7ede24a421f08595f83;" "typings" "install" "--ambient" "--name" "es6-collections" "github:DefinitelyTyped/DefinitelyTyped/es6-collections/es6-collections.d.ts#9f97e2a2bc1f502550c9b4fcaad1c48df5521d37"
typings ERR! node -v v5.6.0
typings ERR! typings -v 0.6.6

typings ERR! If you need help, you may report this error at:
typings ERR!   <https://github.com/typings/typings/issues>

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.7
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\owner\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v5.6.0
npm ERR! npm  v3.5.3
npm ERR! code ELIFECYCLE

npm ERR! angular2@2.0.0-beta.5 postinstall: `typings install --ambient --name es6-promise github:DefinitelyTyped/DefinitelyTyped/es6-promise/es6-promise.d.ts#830e8ebd9ef137d039d5c7ede24a421f08595f83; typings install --ambient --name es6-collections github:DefinitelyTyped/DefinitelyTyped/es6-collections/es6-collections.d.ts#9f97e2a2bc1f502550c9b4fcaad1c48df5521d37`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2@2.0.0-beta.5 postinstall script 'typings install --ambient --name es6-promise github:DefinitelyTyped/DefinitelyTyped/es6-promise/es6-promise.d.ts#830e8ebd9ef137d039d5c7ede24a421f08595f83; typings install --ambient --name es6-collections github:DefinitelyTyped/DefinitelyTyped/es6-collections/es6-collections.d.ts#9f97e2a2bc1f502550c9b4fcaad1c48df5521d37'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     typings install --ambient --name es6-promise github:DefinitelyTyped/DefinitelyTyped/es6-promise/es6-promise.d.ts#830e8ebd9ef137d039d5c7ede24a421f08595f83; typings install --ambient --name es6-collections github:DefinitelyTyped/DefinitelyTyped/es6-collections/es6-collections.d.ts#9f97e2a2bc1f502550c9b4fcaad1c48df5521d37
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\apache-tomcat-8.0.23\webapps\ROOT\new\lps.transpile\npm-debug.log

C:\apache-tomcat-8.0.23\webapps\ROOT\new\lps.transpile>typings -v
0.6.8

C:\apache-tomcat-8.0.23\webapps\ROOT\new\lps.transpile>node -v
v5.6.0

C:\apache-tomcat-8.0.23\webapps\ROOT\new\lps.transpile>

**Comment by nhhockeyplayer** [comment] 2016-02-11 06:46
Feel free to refer to this repo as this is where it happened

https://github.com/nhhockeyplayer/TEST

**Comment by nhhockeyplayer** [comment] 2016-02-11 06:48
npm install 

reproduces it

**Comment by nhhockeyplayer** [comment] 2016-02-11 06:51
npm update fails too

is this now a show stopper for any project ?
It would be nice to get movin again

**Comment by nhhockeyplayer** [comment] 2016-02-11 06:56
npm install --save angular2@2.0.0-beta.4

failed also

**Comment by Tjeerd-menno** [comment] 2016-02-11 06:57
npm update (--save) fails too.

Node version 5.6.0
NPM version 3.5.3

**Comment by nhhockeyplayer** [comment] 2016-02-11 07:01
so this is where i am anchored

C:\apache-tomcat-8.0.23\webapps\ROOT\new\lps.transpile>npm install --save angular2@2.0.0-beta.3
lps@1.0.0 C:\apache-tomcat-8.0.23\webapps\ROOT\new\lps.transpile
├── angular2@2.0.0-beta.3
├── UNMET PEER DEPENDENCY reflect-metadata@0.1.3
├── UNMET PEER DEPENDENCY rxjs@5.0.0-beta.2
└── UNMET PEER DEPENDENCY zone.js@0.5.14

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.7
npm WARN angular2@2.0.0-beta.3 requires a peer of reflect-metadata@0.1.2 but none was installed.
npm WARN angular2@2.0.0-beta.3 requires a peer of rxjs@5.0.0-beta.0 but none was installed.
npm WARN angular2@2.0.0-beta.3 requires a peer of zone.js@0.5.11 but none was installed.

C:\apache-tomcat-8.0.23\webapps\ROOT\new\lps.transpile>npm i --save reflect-metadata@0.1.3
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.7
npm WARN angular2@2.0.0-beta.3 requires a peer of reflect-metadata@0.1.2 but none was installed.
npm WARN angular2@2.0.0-beta.3 requires a peer of rxjs@5.0.0-beta.0 but none was installed.
npm WARN angular2@2.0.0-beta.3 requires a peer of zone.js@0.5.11 but none was installed.

C:\apache-tomcat-8.0.23\webapps\ROOT\new\lps.transpile>npm i --save rxjs@5.0.0-beta.2
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.7
npm WARN angular2@2.0.0-beta.3 requires a peer of reflect-metadata@0.1.2 but none was installed.
npm WARN angular2@2.0.0-beta.3 requires a peer of rxjs@5.0.0-beta.0 but none was installed.
npm WARN angular2@2.0.0-beta.3 requires a peer of zone.js@0.5.11 but none was installed.

C:\apache-tomcat-8.0.23\webapps\ROOT\new\lps.transpile>npm i --save zone.js@0.5.14
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.7
npm WARN angular2@2.0.0-beta.3 requires a peer of reflect-metadata@0.1.2 but none was installed.
npm WARN angular2@2.0.0-beta.3 requires a peer of rxjs@5.0.0-beta.0 but none was installed.

**Comment by eXXeption** [comment] 2016-02-11 08:16
+1

Had the same message.
I cancled the npm process while the message was displayed, that i atleast get the angular2 folder in npm_modules.
The compiler now throws error messages that it "Cannot find name 'Promise'." which is kinda expected..

But i cannot reproduce the es6-promise message now, even if i reinstall angular 2 now, the message doesn't show up anymore, but the errors stay the same..

**Comment by amb-it-ion** [comment] 2016-02-11 12:47
+1

**Comment by lsancho** [comment] 2016-02-11 15:23
+1

**Comment by rmacteague** [comment] 2016-02-11 16:09
+1

**Comment by vsDizzy** [comment] 2016-02-11 16:12
What is the purpose of releasing broken build?

**Comment by spipo** [comment] 2016-02-11 16:50
+1

**Comment by lokeshwarreddy** [comment] 2016-02-11 18:27
+1

**Comment by alexeagle** [comment] 2016-02-11 19:08
Dupe of #7000 
Beta.6 on the way shortly (after some manual testing)

**Closed by alexeagle** 2016-02-11 19:08 UTC

**Comment by soorireddy** [comment] 2016-02-11 19:50
+1

**Comment by nhhockeyplayer** [comment] 2016-02-12 10:50
so is -beta.6 operable ?

have the last there betas been operable ?

when is someone going to start releasing something tangible or step down and permit someone else to drive?

????????????

**Comment by nhhockeyplayer** [comment] 2016-02-12 10:54
in case a nyone else is interested i ROLLED BACK TO BETA.3 just to get typings and typescriupt to compile

**Comment by nhhockeyplayer** [comment] 2016-02-12 10:55
I just reviewed all the comments... and closing out this issue is irresponsible in itself.

These mile long issues threads are pathetic

shut the whole process down

shut it down !

**Comment by michaelbromley** [comment] 2016-02-12 11:06
I can confirm that beta.6 installs fine on my Windows 10 machine, where beta.5 did not.

@nhhockeyplayer this issue thread was a good deal shorter before those comments. This is beta software, which is being provided to you for free. Keep that in mind.

> Beta phase generally begins when the software is feature complete but likely to contain a number of known or unknown bugs.[4] Software in the beta phase will generally have many more bugs in it than completed software, as well as speed/performance issues and may still cause crashes or data loss. ([from Wikipedia](https://en.wikipedia.org/wiki/Software_release_life_cycle#Beta))
