### ISSUE TITLE
Angular pwa does not work offline

### ISSUE THREAD

**Issue by BLecha** [angular/angular#29163] opened 2019-03-07 17:57 UTC
I trying to achive the following. 

Angular pwa with angular version 6 and 7 works fine when I follow the online guides.
I create new ng app be it 6 or 7. Then I execute ng build --prod and then a go to the dist folder and run the command http-server -o And everything works fine as promised.

But when I cretate a local IIS (with the cert that google browser accepts) app by poiting it to my ng dist folder and I browse to https://localhost/test/pwatest the project work fine my manifest json work and the ngsw worker is registered. But when I go offline the tyrex appears. Nothing is fetched. I really google a lot and saw many people having this issue but this problem persists.

manifest.json
`{
  "name": "pwatest",
  "short_name": "pwatest",
  "theme_color": "#1976d2",
  "background_color": "#fafafa",
  "display": "standalone",
  "scope": "/",
  "start_url": "/",
  "icons": [
    {
      "src": "assets/icons/icon-72x72.png",
      "sizes": "72x72",
      "type": "image/png"
    },
    {
      "src": "assets/icons/icon-96x96.png",
      "sizes": "96x96",
      "type": "image/png"
    },
    {
      "src": "assets/icons/icon-128x128.png",
      "sizes": "128x128",
      "type": "image/png"
    },
    {
      "src": "assets/icons/icon-144x144.png",
      "sizes": "144x144",
      "type": "image/png"
    },
    {
      "src": "assets/icons/icon-152x152.png",
      "sizes": "152x152",
      "type": "image/png"
    },
    {
      "src": "assets/icons/icon-192x192.png",
      "sizes": "192x192",
      "type": "image/png"
    },
    {
      "src": "assets/icons/icon-384x384.png",
      "sizes": "384x384",
      "type": "image/png"
    },
    {
      "src": "assets/icons/icon-512x512.png",
      "sizes": "512x512",
      "type": "image/png"
    }
  ]
}`

ngsw-config.json

`{
  "index": "/index.html",
  "assetGroups": [
    {
      "name": "app",
      "installMode": "prefetch",
      "resources": {
        "files": [
          "/favicon.ico",
          "/index.html",
          "/*.css",
          "/*.js"
        ]
      }
    }, {
      "name": "assets",
      "installMode": "lazy",
      "updateMode": "prefetch",
      "resources": {
        "files": [
          "/assets/**",
          "/*.(eot|svg|cur|jpg|png|webp|gif|otf|ttf|woff|woff2|ani)"
        ]
      }
    }
  ]
}
`

index.html 
`<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Pwatest</title>
  <base href="/test/pwatest/">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
  <link rel="manifest" crossorigin="use-credentials" href="manifest.json" />
  <meta name="theme-color" content="#1976d2">
</head>
<body>
  <app-root></app-root>
  <noscript>Please enable JavaScript to continue using this application.</noscript>
</body>
</html>
`
what is the problem? I also tried adding the router to manifest.json no success.

By the way when I perform audit it shows Failures: Service worker does not successfully serve the manifest's start_url, Timed out waiting for fetched start_url.

**Comment by gkalpak** [comment] 2019-03-07 20:34
Hard to tell without being able to get our hands on a reproduction, but if I had to guess I would say it is because you are not serving the app from the root of the domain in ISS (but from https://localhost/test/pwatest). Maybe you could try building with `ng build --prod --baseHref=/test/pwatest/` for IIS.

I am going to close this, because there is no minimal reproduction and also it sounds like a support request. Since this issue tracker is reserved fro bug reports or feature requests, you might want to repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

<sub>If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).</sub>

**Closed by gkalpak** 2019-03-07 20:34 UTC
Labels: comp: service-worker

**Comment by BLecha** [comment] 2019-03-08 08:11
@gkalpak  it is a bug and if your read how to reproduce this it takes you 5 minutes. I cannot shart my localhost with can I ? And your suggestion is not working ng build --prod --baseHref=/test/pwatest/ for IIS. This is a real issue and should not be closed!

**Comment by gkalpak** [comment] 2019-03-08 10:45
@BLecha, please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why providing a minimal reproduction of the problem is important.

You don't have to share your localhost, but you can make sure the steps we have to follow in order to reproduce the problem are minimal (e.g. providing a sample repo we can check out and/or listing the exact commands we have to run).

<sub>(BTW, I have served an Angular PWA with IIS before, so 🤷‍♂️)</sub>

**Comment by BLecha** [comment] 2019-03-08 10:52
@gkalpak  The steps reproduce are,

create new angular pwa project or do you need the steps how to this?
set up certificate on localhost do you need the steps how to this?
on iis add the angular app you just created or do you need the steps?

These are such trivial things man why dont you better redirect this issue to someone more advanced? And yes it is a bug! Im here to discuss withsome a bit more capable if you dont mind can you just open back this ticket and let someone else have a look at it? Thank you very much!

**Comment by gkalpak** [comment] 2019-03-08 12:03
I just tried it again (with @angular/cli v7.3.5 and IIS v10.0.18353.1) and it worked fine (with the `--baseHref=/test/pwatest/` option) 🤷‍♂️
(I didn't use a certificate, because you didn't send me the steps, but luckily it turned out it is not necessary on localhost 😌)

For future reference, these are the steps I followed:
```
ng new test-app --defaults
cd test-app
ng add @angular/pwa
ng build --prod --baseHref=/test/pwatest/

mkdir -p dist/test/pwatest/
cp -r dist/test-app/* dist/test/pwatest/

# Add a website in IIS pointing to `.../test-app/dist/`.
# Browse to `http://localhost/test/pwatest`.
```

**Comment by BLecha** [comment] 2019-03-08 12:44
@gkalpak  I said I am using certificates coz  I need to. Second I already have a website with web applications in it and of these web ap is angular pwa app.  Please do not try to get away from the topic and read carefully. I have seen you in other posts doing the same thing. Now in that web site add one more web app and inside that web app add angular pwa app and see if it works and you will see it does not. Again read carefully and dont go away from topic!

**Comment by BLecha** [comment] 2019-03-08 13:39
so Ladies thanks for your help I nailed it and yes it is a bug!

**Comment by renemarty** [comment] 2019-05-21 05:00
Any news on solving this bug?

**Comment by inthegarage** [comment] 2019-05-28 13:10
@renemarty it's not w.r.t this ticket, as it's closed.
