### ISSUE TITLE
Angular doesn't use UrlSerializer when navigating via router.navigate or routerLink

### ISSUE THREAD

**Issue by orromis** [angular/angular#33946] opened 2019-11-20 22:22 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/router

### Is this a regression?

 No

### Description

On our BE we use special convention for pagination query parameters - we nest those parameters in pg object and query string looks like this: `/some-url?pg[limit]=50&pg[offset]=100&foo=bar`

On FE we use custom UrlSerializer to correctly parse this query string into an object. Parsed object looks like this: `{ pg: { limit: 50, offset: 100 }, foo: 'bar' }`.

The problem is that when we make any navigation (via router.navigate or via routerLink), Angular's router ignores our custom serializer and parses query string manualy. The code that is responsible for this behaviour is [here](https://github.com/angular/angular/blob/bbeac0727b8f267a47aba1ff1bcfc8cc5ca15b61/packages/router/src/create_url_tree.ts#L46).

I'm not really sure if this is a bug but I would expect that when i override default UrlSerializer (which is also used for parsing query string), it shouldn't be ignored. 

## 🔬 Minimal Reproduction

 
https://stackblitz.com/edit/angular-issue-repro2-pboqxa

## 🔥 Exception or Error
There is no exception.

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 8.3.6
Node: 12.13.0
OS: darwin x64
Angular: 8.2.8
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.6
@angular-devkit/build-angular     0.803.6
@angular-devkit/build-optimizer   0.803.6
@angular-devkit/build-webpack     0.803.6
@angular-devkit/core              8.3.6
@angular-devkit/schematics        8.3.6
@angular/cdk                      8.1.3
@angular/cli                      8.3.6
@ngtools/webpack                  8.3.6
@schematics/angular               8.3.6
@schematics/update                0.803.6
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.41.2
</code></pre>

**Anything else relevant?**

No

**Comment by Mohendran** [comment] 2019-12-27 07:10
Im also facing the same Issue. The Custom UrlSerializer gets triggered when a url is redirected(using href) or when it is entered but it also should be triggered when using routerLink.

Or is there any workaround for this ?

**Comment by aksahta** [comment] 2020-06-29 05:52
@pkozlowski-opensource  any update on this issue?

**Comment by cosmoKenney** [comment] 2020-07-09 22:25
Same here. Any workaround?

**Comment by Vedanshu7** [comment] 2021-04-06 05:12
This will help I think 

**[https://medium.com/dev-genius/advanced-router-configuration-in-angular-d22c6dc420be](https://medium.com/dev-genius/advanced-router-configuration-in-angular-d22c6dc420be)**

**Comment by atscott** [comment] 2022-10-03 17:17
Closing as duplicate of #47307

**Closed by atscott** 2022-10-03 17:17 UTC
Labels: feature, freq1: low, comp: router, insufficient votes, votes required
