### ISSUE TITLE
web.dev/lighthouse points out that we have a11y regressions on angular.io 

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#27723] opened 2018-12-18 08:21 UTC
# 📚 Docs or angular.io bug report

### Description

 web.dev reports a11y issues

### What's the affected URL?**
 https://angular.io/

### Reproduction Steps**

- go to web.dev
- enter angular.io
- run the report

### Expected vs Actual Behavior**

no a11y issues

## 📷Screenshot

<img width="1176" alt="screen shot 2018-12-18 at 12 19 46 am" src="https://user-images.githubusercontent.com/216296/50140759-a8928e80-025a-11e9-9991-084cfdea2bab.png">

**Comment by gkalpak** [comment] 2018-12-18 08:36
FWIW, this will only checks the homepage. We should address issues in other pages as well.

**Comment by gkalpak** [comment] 2019-07-12 09:20
I checked again and there are no a11y isues reported on web.dev.
<sub>Again, this doesn't mean everything is perfect and it also only checks the homepage (so there might still be obvious issues on other pages). But it _does_ mean things have improved :tada:</sub>

As of #31414, we run a11y checks on several pages (not just the homepage) on CI, which will at least prevent regressions. Hopefully, we will improve the overall a11y over time.

Closing this particular issue for now, since it has been addressed.

**Closed by gkalpak** 2019-07-12 09:20 UTC
Labels: comp: docs-infra
