### ISSUE TITLE
Lazy loaded module in named outlet throws error

### ISSUE THREAD

**Issue by acohenOT** [angular/angular#39692] opened 2020-11-14 20:03 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/router

### Is this a regression?

 No

### Description

 Navigating to route with lazy loaded module in named outlet throws error:

## 🔬 Minimal Reproduction

   
https://stackblitz.com/edit/angular-ivy-lazy-load

Open the console and click the third link "**Named outlet - lazy load - console error**". The other two links on the page work properly.

![image](https://user-images.githubusercontent.com/34688558/99155914-619db580-268a-11eb-99c8-7f803cd9b162.png)

## 🔥 Exception or Error
<pre><code>

ERROR
Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'home'
Error: Cannot match any routes. URL Segment: 'home'
at ApplyRedirects.noMatchError (https://angular-ivy-lazy-load.stackblitz.io/turbo_modules/@angular/router@11.0.0/__ivy_ngcc__/bundles/router.umd.js:2904:20)
at CatchSubscriber.eval [as selector] (https://angular-ivy-lazy-load.stackblitz.io/turbo_modules/@angular/router@11.0.0/__ivy_ngcc__/bundles/router.umd.js:2887:33)
at CatchSubscriber.error (https://angular-ivy-lazy-load.stackblitz.io/turbo_modules/rxjs@6.6.3/internal/operators/catchError.js:46:31)
at MapSubscriber.Subscriber._error (https://angular-ivy-lazy-load.stackblitz.io/turbo_modules/rxjs@6.6.3/internal/Subscriber.js:92:26)
at MapSubscriber.Subscriber.error (https://angular-ivy-lazy-load.stackblitz.io/turbo_modules/rxjs@6.6.3/internal/Subscriber.js:72:18)
at MapSubscriber.Subscriber._error (https://angular-ivy-lazy-load.stackblitz.io/turbo_modules/rxjs@6.6.3/internal/Subscriber.js:92:26)
at MapSubscriber.Subscriber.error (https://angular-ivy-lazy-load.stackblitz.io/turbo_modules/rxjs@6.6.3/internal/Subscriber.js:72:18)
at MapSubscriber.Subscriber._error (https://angular-ivy-lazy-load.stackblitz.io/turbo_modules/rxjs@6.6.3/internal/Subscriber.js:92:26)
at MapSubscriber.Subscriber.error (https://angular-ivy-lazy-load.stackblitz.io/turbo_modules/rxjs@6.6.3/internal/Subscriber.js:72:18)
at ThrowIfEmptySubscriber.Subscriber._error (https://angular-ivy-lazy-load.stackblitz.io/turbo_modules/rxjs@6.6.3/internal/Subscriber.js:92:26)

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular: 11.0.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, localize, material, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.1
@angular-devkit/build-angular   0.1100.1
@angular-devkit/core            11.0.1
@angular-devkit/schematics      11.0.1
@angular/cli                    11.0.1
@schematics/angular             11.0.1
@schematics/update              0.1100.1
rxjs                            6.6.3
typescript                      4.0.5
</code></pre>

**Anything else relevant?**

See issue #12842 -- this was reportedly fixed in Angular 11 by @atscott. 
`Uncaught (in promise): TypeError: Cannot read property 'routes' of undefined`

With Angular 11, the issue still exists, but the error has changed.
`Uncaught (in promise): Error: Cannot match any routes.`

**Comment by atscott** [comment] 2020-11-14 21:06
This looks like a separate issue; closing as duplicate of #10726.

**Closed by atscott** 2020-11-14 21:06 UTC
