### ISSUE TITLE
HTML5 <video>  does not auto play in chrome

### ISSUE THREAD

**Issue by Tinalst** [angular/angular#27252] opened 2018-11-24 09:55 UTC
# 🐞 bug report

### Affected Package

 I am not sure

### Is this a regression?

 No

### Description

 HTML5 video tag does not auto play in chrome.
I have tried some method , however only on methond can resolve this problem . 
1.  open chrome chrome://flags/#autoplay-policy  
2. setting Autoplay policy to no user gesture is required
Even this can resolve ,however I do not think is the beast way to resolve this problem . 
what's more,  I find the (loadedate) and (load)  also does not work in angular .
And when I try to get the video tag ElementRef to set the.video.nativeElement.paly() I got some error msg
`Uncaught (in promise) DOMException: play() failed because the user didn't interact with the document first.`

## 🔬 Minimal Reproduction

 
```
// app.component.html
<video *ngIf="testurl" class="bannerVideo"  [src]="testurl"  [autoplay]="'true'" [loop]="true" (loadeddata)="load()" [muted]="muted"></video>

// app.component.ts
testurl = 'assets/video/homebg1080.mp4';
loadeddata = () => {
      alter(1)
}

```
```
<video appVedio class="bannerVideo" loop muted autoplay="" id="video">
    <source src="./assets/video/homebg1080.mp4" type="video/mp4">
<source [src]="testurl" type="video/mp4">
 
```

```
// app.component.html 
<video *ngIf="testurl" class="bannerVideo"  [src]="testurl"  [autoplay]="'true'" [loop]="true" (loadeddata)="load()" [muted]="muted" #video controls></video>

// app.component.ts
@ViewChild('video') video: ElementRef;
this.video.nativeElement.play();
 this.video.nativeElement.src= `assets/video/homebg1080.mp4`;
```

above those does work .

## 🔥 Exception or Error
<pre><code>

No error 

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular: 7.0.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.10.5
@angular-devkit/build-angular     0.10.5
@angular-devkit/build-optimizer   0.10.5
@angular-devkit/build-webpack     0.10.5
@angular-devkit/core              7.0.5
@angular-devkit/schematics        7.0.5
@angular/cli                      7.0.5
@ngtools/webpack                  7.0.5
@schematics/angular               7.0.5
@schematics/update                0.10.5
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.19.1

</code></pre>

**Anything else relevant?**

chrome version 70.0.3538.110

**Comment by AnthonyLenglet** [comment] 2018-11-25 21:41
Chrome automaticaly blocks autoplay videos since Version 66
https://developers.google.com/web/updates/2017/09/autoplay-policy-changes

**Comment by pkozlowski-opensource** [comment] 2018-11-26 21:06
Thnx @AnthonyLenglet - I'm going to close this one as it seems that the issue is about browser's behaviour and not something specific to Angular / anything that Angular could address.

**Closed by pkozlowski-opensource** 2018-11-26 21:06 UTC
Labels: comp: core & compiler

**Comment by madakk** [comment] 2018-12-08 22:29
@pkozlowski-opensource Chrome prevents autoplay under certain circumstances but not if the video is muted. From the page linked by @AnthonyLenglet:

> Muted autoplay is always allowed.

The issue appears to be that the `muted` attribute fails to apply. You can see discussions of this on SO: https://stackoverflow.com/questions/48856562/ and https://stackoverflow.com/questions/51464647/ all suggesting different workarounds to apply the `muted` property manually after initialization to allow for autoplay. There's also issue #23009 which seems related, although the solution suggested there of using `[muted]=true` doesn't seem to make a difference.
