### ISSUE TITLE
Relative imports not working with ng-xi18n

### ISSUE THREAD

**Issue by rolandoldengarm** [angular/angular#12760] opened 2016-11-08 00:12 UTC
**I'm submitting a ...**  (check one with "x")
```
[* ] bug report => search github for a similar issue or PR before submitting
```
**Current behavior**
- Added baseUrl for relative imports
- Set up a shared module in /app/shared
- From root module, add 
````
import {SharedModule} from 'app/shared/shared.module'
````
- Project works fine in JIT (using Angular CLI)
- Running ng-xi18n:
````
$ ng-xi18n
Error: Unexpected value 'SharedModule' imported by the module 'ClientModule'
````
When I change the import to .. from './shared/shared.module' it works fine.

**Expected behavior**
Relative imports should work with ng-xi18n

**Minimal reproduction of the problem with instructions**
Can't put on plunkr as it requires ng-xi18n to run

**What is the motivation / use case for changing the behavior?**
Relative imports are supported by JIT and make the code cleaner.

**Please tell us about your environment:**
Windows 10, Node 6, NPM 3

* **Angular version:** 2.0.X
2.1.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
n/a
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript
* **Node (for AoT issues):** `node --version` =   
6.9.1

**Comment by vicb** [comment] 2016-11-08 22:22
please provide a repro (ie in a git repo)

**Comment by rolandoldengarm** [comment] 2016-11-09 06:58
Sure @vicb 
See here: https://github.com/rolandoldengarm/ng-xi18n-relative

Just clone it, run npm install. Then if you run ng-xi18n it throws an error:

````
$ .\node_modules\.bin\ng-xi18n
Error: Unexpected value 'TestComponent' declared by the module 'AppModule'
    at C:\Projects\git\ng-xi18n-relative\node_modules\@angular\compiler\bundles\compiler.umd.js:14374:33
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (C:\Projects\git\ng-xi18n-relative\node_modules\@angular\compiler\bundles\compiler.umd.js:14361:51)
    at C:\Projects\git\ng-xi18n-relative\node_modules\@angular\compiler\bundles\compiler.umd.js:13284:43
    at Array.forEach (native)
    at _extractModulesAndPipesOrDirectives (C:\Projects\git\ng-xi18n-relative\node_modules\@angular\compiler\bundles\compiler.umd.js:13283:28)
    at Object.analyzeNgModules (C:\Projects\git\ng-xi18n-relative\node_modules\@angular\compiler\bundles\compiler.umd.js:13039:16)
    at Extractor.extract (C:\Projects\git\ng-xi18n-relative\node_modules\@angular\compiler-cli\src\extractor.js:34:30)
    at extract (C:\Projects\git\ng-xi18n-relative\node_modules\@angular\compiler-cli\src\extract_i18n.js:19:35)
    at Object.main (C:\Projects\git\ng-xi18n-relative\node_modules\@angular\tsc-wrapped\src\main.js:30:16)
Extraction failed
````

**Comment by rolandoldengarm** [comment] 2016-11-12 07:48
@vicb Did you have time to look at this? Alternatively I can switch back to ../../.. imports but that's not a 5 minute exercise; I've just switched to relative imports.
Hope you can shed a light on this, thanks!

**Comment by vicb** [comment] 2016-11-13 00:48
Do you run ngc on your app, do you have the same issue there ?

**Comment by rolandoldengarm** [comment] 2016-11-14 06:56
As I'm using Angular CLI, I've tried AOT compilation with "$ ng build --aot" and that works without issues @vicb

**Comment by reynardmh** [comment] 2016-11-28 20:04
I also encounter this problem when importing angular component from another node_module. I can run the app just fine (using the imported component), but ng-xi18n failed with the same message.

Here is a github repo to reproduce the issue:

https://github.com/reynardmh/bugdemo-angular-i18n

Just checkout the repo, run `npm install`, and run `./node_modules/.bin/ng-xi18n`
I got: Error: Unexpected value 'CoolComponent' declared by the module 'AppModule'

However, running `ng serve` works without any warning.

**Comment by vicb** [comment] 2016-11-28 20:23
I'm going to close this issue as it seems to be a CLI issue. Please re-open there.

Note:
- If you can build the app there are great chances that you'll be able to extract the translatable strings as the code path is mostly the same - that's provided the CLI provides a wrapper around `ng-xi18n` with the same config, I'm not sure about the status here. I know it was not supported a few weeks ago and someone opened an issue on the CLI repo,
- If you are not using the CLI (for other people finding the issue) then you should specify the path to your tsconfig: `ng-xi18n -p path/to/tsconfig`

**Closed by vicb** 2016-11-28 20:23 UTC
Labels: comp: i18n

**Comment by reynardmh** [comment] 2016-11-29 14:01
I don't know the CLI and angular code well, but how is this an issue with the CLI? The stack trace is from angular code, and the error happens when I'm running `ng-xi18n` not the `ng` CLI. 
```
Error: Unexpected value 'CoolComponent' declared by the module 'AppModule'
    at /bugdemo-angular-i18n/node_modules/@angular/compiler/bundles/compiler.umd.js:14722:29
    at Array.forEach (native)
    at CompileMetadataResolver._loadNgModuleMetadata (/bugdemo-angular-i18n/node_modules/@angular/compiler/bundles/compiler.umd.js:14702:56)
    at CompileMetadataResolver.getUnloadedNgModuleMetadata (/bugdemo-angular-i18n/node_modules/@angular/compiler/bundles/compiler.umd.js:14636:23)
    at addNgModule (/bugdemo-angular-i18n/node_modules/@angular/compiler/bundles/compiler.umd.js:12944:43)
    at /bugdemo-angular-i18n/node_modules/@angular/compiler/bundles/compiler.umd.js:12957:16
    at Array.forEach (native)
    at _createNgModules (/bugdemo-angular-i18n/node_modules/@angular/compiler/bundles/compiler.umd.js:12956:28)
    at analyzeNgModules (/bugdemo-angular-i18n/node_modules/@angular/compiler/bundles/compiler.umd.js:12700:16)
    at Object.analyzeAndValidateNgModules (/bugdemo-angular-i18n/node_modules/@angular/compiler/bundles/compiler.umd.js:12704:20)
Extraction failed
```

FYI, I copied the tsconfig.json to the root so ng-xi18n can run. I tried using -p /path/to/tsconfig but got the same result. 

This originally happens on my project that does not use the CLI, I just created the demo using CLI and was able to reproduce the same error as my project.

**Comment by TeodorKolev** [comment] 2017-01-20 12:33
Will that be fixed in 2017?
