### ISSUE TITLE
@Input on Starter Component not assined

### ISSUE THREAD

**Issue by nandel** [angular/angular#7997] opened 2016-04-09 22:22 UTC
**Steps to reproduce and a minimal demo of the problem**
- Create a component with a input field
- Start hin on ur index.html

http://plnkr.co/edit/1v1u6OyC5Ti32nPeUXmw?p=preview

**Current behavior**
The Input value is empty

**Expected/desired behavior**
The input value should be set to the component

app.component.ts
```
import {Component, Input} from 'angular2/core';

@Component({
	selector: 'my-app',
	template: '<h1>Current Value: {{ val }}</h1>'
})
export class AppComponent {
  @Input('init-value') val: string;
}
```

index.html
```
<body>
    <my-app init-value="Helo World!">Loading...</my-app>
  </body>
```

**Comment by ericmartinezr** [comment] 2016-04-09 22:26
Known issue https://github.com/angular/angular/issues/1858

**Comment by robwormald** [comment] 2016-04-12 05:35
Closing as a dupe of #1858

**Closed by robwormald** 2016-04-12 05:35 UTC
