### ISSUE TITLE
@HostBinding doesn't create a compiled and active directive

### ISSUE THREAD

**Issue by ghoullier** [angular/angular#14114] opened 2017-01-26 09:26 UTC
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When a directive is attached to the DOM via @HostBinding decorator, it seems to not be active.

```ts
import { Component, Directive, ElementRef, HostBinding } from '@angular/core';

@Directive({
  selector: '[ui-color]',
})
export class ColorDirective  {
  constructor(el: ElementRef) {
    el.nativeElement.style.backgroundColor = 'red';
  }
}

@Component({
  selector: 'test-cmp',
  template: `Should be red`,
})
export class TestComponent {
  @HostBinding('attr.ui-color') color = '';
}

@Component({
  selector: 'my-app',
  template: `
    <test-cmp></test-cmp>
    <div ui-color>Should be red</div>
  `,
})
export class AppComponent {}

//Two text lines should be red
```

The problem is also reproduced with modules: https://github.com/angular/flex-layout/issues/76

**Expected behavior**

Directive should be active when injected via @HostBinding decorator.

**Minimal reproduction of the problem with instructions**

https://plnkr.co/edit/j5MSVP5pIRjTTK9D2LsS

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X | 4.0.X

* **Browser:** [all ]
 
* **Language:** [all]

**Comment by DzmitryShylovich** [comment] 2017-01-26 09:42
Duplicate of https://github.com/angular/angular/issues/11716

**Closed** 2017-01-26 09:43 UTC
