### ISSUE TITLE
feat(core): KeyValueDiffer support for NgForOf

### ISSUE THREAD

**Issue by skreborn** [angular/angular#21990] opened 2018-02-02 15:26 UTC
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report
[x] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior
`NgForOf` only supports `IterableDiffer`.

## Expected behavior
`NgForOf` should support `KeyValueDiffer` by default, making ES6 `Map`s easily iterable using `ngFor`.

## What is the motivation / use case for changing the behavior?
Iteration of an ES6 `Map` is currently possible by caching `Map.entries()` every time a change is detected manually within `ngDoCheck` (using our own injected `KeyValueDiffer`), and iterating through that. The caching is required because `Map.entries()` returns a different value on each call, making Angular's default change detection go crazy.

While this isn't a problem that's impossible to work around, it's certainly inconvenient, and a built-in way to tackle this would be much appreciated. Then again, if you believe that this change would introduce too much complexity to a core directive, and the trade is simply not worth it, please feel free to close the issue.

**Comment by chuckjaz** [comment] 2018-02-02 22:28
Thanks for reporting this issue. However this issue is a duplicate of an existing issue #2246. Please subscribe to that issue for future updates.

**Closed by chuckjaz** 2018-02-02 22:28 UTC

**Comment by skreborn** [comment] 2018-02-03 00:12
Sorry about that, my mistake. Don't know how I missed that.
