### ISSUE TITLE
Content children created dynamically from templates using NgFor or NgIf are not inserted with <ng-content>

### ISSUE THREAD

**Issue by gionkunz** [angular/angular#5868] opened 2015-12-13 15:55 UTC
Given the use case of dynamically instantiating content children using the NgFor of NgIf directives I've found this not working in alpha.52. I thought this was working before in alpha.44 but after testing it seems this was never working.

I'd expect this to work and I thought this was the reason for content children being represented with a `QueryList` in the first place.

```javascript
import {Component, Input, NgFor, NgIf} from 'angular2/angular2';

@Component({
  selector: 'child'
  template: `
    <p>{{text}}</p>
  `
})
export class Child {
  @Input() text;
}

@Component({
  selector: 'parent'
  template: `
    <section>
      <strong>Content children:</strong>
      <ng-content select="child"></ng-content>
    </section>
  `
})
export class Parent {}

@Component({
  selector: 'app'
  template: `
    <section>
      <strong>Outside of parent</strong>
      <child *ngIf="true" text="Child in the wild"></child>
      <child *ngFor="#t of text" [text]="t"></child>
    </section>
  
    <parent>
      <child *ngIf="true" text="Child in the wild"></child>
      <child *ngFor="#t of text" [text]="t"></child>
    </parent>
  `,
  directives: [Parent, Child, NgFor, NgIf]
})
export class App {
  text = ['Child 1', 'Child 2', 'Child 3']
}
```
http://plnkr.co/edit/aUSkWPQmT3XHf6QLqif5?p=preview

**Comment by vicb** [comment] 2015-12-13 21:38
/cc @tbosch 
(note: `<ng-content select="template"></ng-content>` or `<ng-content></ng-content>` would display the children.)

**Comment by vicb** [comment] 2015-12-14 18:21
Duplicate of #5363

You can use `<ng-content select="template"></ng-content>` for now, we will probably improve the matching mechanism in further releases.

**Closed by vicb** 2015-12-14 18:21 UTC

**Comment by uMaxmaxmaximus** [comment] 2016-07-19 08:14
But in MY framework is WORK ^__^ https://www.youtube.com/watch?v=tmKMAfzR8Ow
