### ISSUE TITLE
Can not use my local angular 8 npm library (local registry)

### ISSUE THREAD

**Issue by walidabouzaid** [angular/angular#33836] opened 2019-11-14 21:12 UTC
Can not use my local angular 8 npm library which is published to a local registry on my company servers. Check error below.

Error: C:\my-workspace\node_modules\@thiqah\tree\src\lib\thiqah-tree-lib.module.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property. The missing file seems to be part of a third party library.

![thiqahNPMCriticalIssue_2](https://user-images.githubusercontent.com/19210082/68896164-f8642900-073b-11ea-88da-67c89c5a054f.png)

Please this is really a **panic** if you don't support yet publishing to a local feed on Angular 8 state that apparently.

I've about three days till now without any benefit.

**Comment by alxhub** [comment] 2019-11-14 23:07
Hello @walidabouzaid,

Unfortunately in order to investigate this issue, we're going to need a reproduction in the form of a Github repository with instructions on how to produce the error you're getting.

However, looking at the error message, it appears the `@thiqah/tree` package you have is published with plain `.ts` files into whatever repository you're using. This is not a good practice typically - NPM packages should be built in the Angular package format with `.d.ts` and `.metadata.json` files. I'm not surprised you're running into issues here.

**Comment by walidabouzaid** [comment] 2019-11-15 01:07
Hello @alxhub 
Why your angular builder and/or your publisher did not produce these files from its self. I think this is not my job to produce those files. You are stating as an angular team that We can create, build, package, and publish a library from your CLI. I think it's not my job to produce those files from my self. Or you should state this info apparently at your angular.io docs.
Unfortunately I'm surprised. Awaiting for descriptive, quick, and clear reply.
Thanks in advance.

**Comment by blemaire** [comment] 2019-11-15 07:42
@walidabouzaid The process is fairly well resumed in the 3 commands provided in the official documentation:
https://angular.io/guide/creating-libraries#publishing-your-library

**Comment by walidabouzaid** [comment] 2019-11-16 08:09
@blemaire , @alxhub I already did these steps, but these steps don't produce some necessary files like main.d.ts or index.d.ts as I knew from someone in other related issue.

It's not about to just reply and **VOA LA** every thing is working by its self. The steps is not enough to produce a working library.0 Surely you've missed a major and critical thing that do not enable the library from working when published to a local npm registry.
Awaiting for a positive answer not just writing a line any child knows angular knows this not beneficial tutorial.

**Comment by walidabouzaid** [comment] 2019-11-17 13:43
Dears @blemaire , @alxhub  ,
I'm still waiting your response. Really I'm in a showstopper. No way to use my NPM on different app. after puplishing it to local npm feed on TFS server on my company premises.

If you have no time kindly mention anybody.
### URGENT HELP NEEDED

**Comment by mlc-mlapis** [comment] 2019-11-17 15:11
@walidabouzaid You still don't have a reproduction of your problem. It means as simple as a possible project published (GitHub for example) that allows step by step to reproduce it. This is always required, so don't be surprised that nobody responses.

**Comment by IgorMinar** [comment] 2019-11-19 07:10
@walidabouzaid as @blemaire mentioned in https://github.com/angular/angular/issues/33836#issuecomment-554250292, the steps to produce a library are documented on angular.io.

If those steps are not working for you, then we need much more information about what the problem is and how to reproduce what you are doing.

Please also note, that your language comes across as demanding and borderline threatening. This might not be your intention, but that's the perception we get. We do are best to support Angular users, but any kind of threatening behavior/language is against our https://github.com/angular/code-of-conduct, and will result in this issue being closed. Please be respectful of everyone's time and ability to help you, especially considering the limited information you provided us with.

**Comment by alxhub** [comment] 2019-12-05 23:50
@walidabouzaid I'm going to close this issue as we cannot investigate this problem without a working reproduction. In particular, you ask:

> Why your angular builder and/or your publisher did not produce these files from its self. 

Without knowing what precise steps you're taking to build and publish the library, there is no way to answer this question.

**Closed** 2019-12-05 23:50 UTC
Labels: comp: compiler, freq1: low, severity3: broken, state: Needs repro, type: bug/fix
