### ISSUE TITLE
NGC generates invalid imports in ngfactory

### ISSUE THREAD

**Issue by dawidgarus** [angular/angular#28019] opened 2019-01-09 16:29 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/compiler-cli

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 6.0.4
Since 6.0.5 up until current version 7.2.0 the bug is present

### Description
NGC generates invalid imports in ngfactory. See ` Exception or Error` for more details.

## 🔬 Minimal Reproduction

1. Clone repo: https://github.com/dawidgarus/angular-ngc-bug
2. run `npm i`
3. run `npm run compile`

## 🔥 Exception or Error
Generated app.module.ngfactory.js contains import:
```
require("../node_modules/@angular/router/router.ngfactory")
```
Which should be
```
require("@angular/router")
```
For one, there is no route.ngfactory.js.
Secondly, invalid imports causes webpack to end with error:
```
ERROR in ./xxx/app.module.ngfactory.js
Module not found: Error: Can't resolve '../node_modules/@angular/router/router.ngfactory' in 'c:\xxx'
```
Even with @ngtools/webpack.

## 🌍  Your Environment

**Angular Version:**
<pre><code>
  "dependencies": {
    "@angular/common": "6.0.5",
    "@angular/compiler": "6.0.5",
    "@angular/compiler-cli": "6.0.5",
    "@angular/core": "6.0.5",
    "@angular/platform-browser": "6.0.5",
    "@angular/router": "6.0.5",
    "typescript": "2.7.2"
  }

</code></pre>

**Anything else relevant?**
OS: Windows 8.1
NPM: 5.6.0
Node: 8.11.2

---

That's a huge regression since version 6 is suppose to be LTS. What's the point of having LTS if I cannot update angular if there were important fix because I wouldn't be able to use AOT compilation.
Honestly, I feel like if you don't use angular-cli, then you are second class citizen for angular. I mean, even bug report template is biased (asks for `ng version`). Isn't `ngc` supposed to be the primary and out-of-the-box way to compile angular app? How come nobody noticed it yet.
And please, don't tell me it will be fixed by ivy. Unless you are gonna backport it to v6 that's really bs for LTS users.

**Comment by dawidgarus** [comment] 2019-01-11 16:49
Also, it looks like `ɵEmptyOutletComponentNgFactory` is not present in any angular bundle.

**Comment by mlc-mlapis** [comment] 2019-01-11 17:02
@dawidgarus ... `require("../node_modules/@angular/router/router.ngfactory")` is generated during `ngc` compilation. It is the same as with any other libs and `*.ngfactory` generated on the base of using those libs which contains any templates.

**Comment by mlc-mlapis** [comment] 2019-01-11 17:06
@dawidgarus ... the relevant Angular source code is in `angular/packages/router/src/components/empty_outlet.ts` and it's:

```
@Component({template: `<router-outlet></router-outlet>`})
export class EmptyOutletComponent {
}
```

**Comment by dawidgarus** [comment] 2019-01-11 18:21
@mlc-mlapis Well it's not generated:
```
e:\Projects\angular-ngc-bug-master\dist>node app.module.ngfactory
module.js:549
    throw err;
    ^

Error: Cannot find module '../node_modules/@angular/router/router.ngfactory'
```

**Comment by mlc-mlapis** [comment] 2019-01-11 19:02
@dawidgarus ... hmm, on my side ... when I did it the last time with Angular 6.1.9, it has been generated.

**Comment by dawidgarus** [comment] 2019-01-11 19:06
@mlc-mlapis I also tried on Windows 10 with node 8.11.1 and 10.15.0 with same result. Is it possible that it's a Windows thing?

**Comment by mlc-mlapis** [comment] 2019-01-11 19:08
@dawidgarus ... I don't think so. I did it also on Windows 10, Node 10.2.1.

**Comment by mlc-mlapis** [comment] 2019-01-11 19:11
@dawidgarus ... but I used this setting in `tsconfig.json`:
```
"compilerOptions": {
	"baseUrl": ".",
	"target": "es5",
	"module": "commonjs",
	"moduleResolution": "node",
	...
}
```

**Comment by dawidgarus** [comment] 2019-01-11 22:20
@mlc-mlapis I've finally cracked what's wrong. rootDir in tsconfig.json must be a directory which contains node_modules, otherwise ngfactory files created from libraries in node_modules won't be generated.
I find this behavior very confusing. Can't see it being mentioned anywhere in docs. With `tsc` you don't need to include node_modules in rootDir. It would be nice if `ngc` give some sort of warning or error.

**Comment by mlc-mlapis** [comment] 2019-01-12 01:38
@dawidgarus ... oh, yep.

**Comment by alxhub** [comment] 2019-01-29 23:43
@dawidgarus I'm going to close this as 1) the cause is known (`node_modules` not in the `rootDirs`) and 2) Ivy obviates the need for ngfactories and thus this entire problem. I don't think we need to work it into our documentation given #2.

**Closed by alxhub** 2019-01-29 23:43 UTC
Labels: comp: core & compiler, fixed by Ivy, freq1: low, severity5: regression, type: bug/fix
