### ISSUE TITLE
ReactiveForms, validator weird behaviour in FormArray

### ISSUE THREAD

**Issue by matteo-mosca** [angular/angular#24424] opened 2018-06-11 15:49 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Take this snippet:

<pre><code>
static createPhoneNumber(formBuilder: FormBuilder, item: string): FormGroup {
        return formBuilder.group({
            phone: formBuilder.control([item, [Validators.required]])
        });
    }
</code></pre>

<pre><code>
addPhoneNumber() {
        (this.controlContainer.control.get("phoneNumbers") as FormArray).push(ContactFormGroupComponent.createPhoneNumber(this.formBuilder, ""));
    }
</code></pre>

With this template block:

`<div formArrayName="phoneNumbers">
            <div *ngFor="let phoneNumber of phoneNumbers.controls; let i=index">
                <div [formGroupName]="i">
                    <mat-form-field>
                        <input matInput type="text" placeholder="numero di telefono" maxlength="15" formControlName="phone" autocomplete="tel"/>
                        <mat-hint align="end">{{phoneNumbers.controls[i].controls.phone.value?.length || 0}}/15</mat-hint>
                        <mat-error *ngIf="phoneNumber?.errors?.length">{{phoneNumbers.controls[i].controls.phone.errors}}</mat-error>
                    </mat-form-field>
                    <button mat-button (click)="removePhoneNumber(i)"><mat-icon matTooltip="Elimina">delete</mat-icon></button>
                </div>
            </div>
        </div>`

When used in another FormGroup, it behaves correctly. It creates a new formgroup containing a "phone" control with "item" value and the validator.
But when used inside a FormArray (like the provided template block), pushing in the form array a call to this function, the created control contains this text, meaning it appears inside the rendered textbox:

`,function (control) {        return isEmptyInputValue(control.value) ? { 'required': true } : null;    }`

And if I add more validators, the text grows with more code.

If I remove the validators, the textbox appears empty but the mat-hint counter I use underneath indicates that it has 1 character inside. If I write 1 character, the counter remains 1, and if I delete the character, the counter goes down to zero.

## Expected behavior

I expect the control to work as intended when used inside a FormArray.

## Environment

<pre><code>
Angular version: 6.0.4

Browser:
- [x] Chrome (desktop) version 67
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 9.5.0  
- Platform: Windows 10 

Others:

</code></pre>

**Comment by kara** [comment] 2018-07-12 22:46
Can you provide a stackblitz for this case without the Material components? We are not able to reproduce given the code snippet.

**Comment by kara** [comment] 2018-08-21 22:43
Closing, since this doesn't have enough actionable information. Please feel free to open a new issue with a repro.

**Closed by kara** 2018-08-21 22:43 UTC
Labels: comp: forms, flag: can be closed?, freq1: low, severity1: confusing, state: Need repro, type: bug/fix

**Comment by benmatela** [comment] 2019-04-25 05:59
Hi, I had a similar issue. 

I added an extra disabled input field(had to be creative) and that solved the issue. 
I'm guessing it might have something to do with the index of the input field.
