### ISSUE TITLE
router CanLoad Route guard broken for common use case

### ISSUE THREAD

**Issue by figuerres** [angular/angular#17359] opened 2017-06-09 13:32 UTC
there is an issue filed but it is listed as a feature request and i think it needs to be more of a priotity:
https://github.com/angular/angular/issues/12411

**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
an angular app has a feature module that should be lazy loaded , a CanLoad  guard needs to deal with the use case that the caller is not yet authenticated and needs to get a token before the guard can determine how the request will be handled.
with a call to  [https://github.com/IdentityModel/oidc-client-js](url)  that uses [https://github.com/IdentityModel/oidc-client-js](url)
a call to the STS server is used to return back to the angular app with a token.
Can Load does not have the same access that Can Activate has to the router.navigate() data so the can load fails to get the user to the route.

**Expected behavior**

CanLoad  should have the navigate route available in some reasonable form.
in CanActivate we can access the url and pass it to the STS server and the  STS server passes that back to the angular app and everything works.  
CanLoad needs to be able to work in the same way, if the router data can not be the final url then we need some other "state" object that we can get and a way to load that state back into the router when the STS  server returns the user token to the app.

this STS server case happens with any third party auth like Google,Facebook,Microsoft or Twitter

**Minimal reproduction of the problem with instructions**
this needs several items to repro,  i can't give a sample right now but the parts are [this:](https://github.com/IdentityModel/oidc-client-js)
[https://github.com/IdentityModel/oidc-client-js](url)

and an angular app that has a feature module that should not be loaded unless the user has a token that grants access to a view inside the feature module.

canLoad needs to make a call `this.mgr.signinRedirect({ data: state })`
and the oidc manager 'mgr' returns to finish the callback and we then have code like this:
`this.mgr.signinRedirectCallback().then((user) => {
    //  console.log("signed in", user);
      this.loggedIn = true;
      this.currentUser = user;
      this.userLoadededEvent.emit(user);
      // 
      // if the login request was for a given view 
      // we saved that before we redirected the user to the login page.
      // now we need to restore the view or route to the view
      // restore if they were already there, route to it if needed authentication to 
      // get to that view 
      //
      // console.log( " user.state = " ,  user.state );
      if( user.state){
        this.router.navigate([ user.state ]);
      }else{
        this.router.navigate(['']);
      }
    }).catch( (err) => {
      console.log(err);
    });`

**What is the motivation / use case for changing the behavior?**
so that lazy loading of a feature module will work when using a third party authentication server via OIDC/ Oauth 2.

**Please tell us about your environment:**
WIndows Server 2012, IIS 8.5  but this issue will happen on any web server.

* **Angular version:** 2.0.X
 4.xxx  current version as of a week ago.

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
tested in chrome as of now, should happen with any browser.
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 2.3.2

* **Node (for AoT issues):** `node --version` =   
6.9.1

**Comment by Toxicable** [comment] 2017-06-10 10:36
Your situation seams very domain related, can you narrow it down to an issue with the framework then provide a minimal reproduction of this, otherwise it's not actionable

**Comment by figuerres** [comment] 2017-06-10 12:16
Can load does not give the target route, it only gives the target module name. Can activate gives the target route. That is the problem, that is all that is needed to fix the can load interface

**Comment by figuerres** [comment] 2017-06-13 12:17
Here is a more general statement of the problem:

canLoad cannot decide to load a module if the logic needs the route.
for example if the module is Admin  and the admin module  has a view that it can route to called roles and the navigate route is called /admin/manage/roles
can load  does not know that the target is manage/roles  it only sees that the admin module is the target.

also if a user enters a full url like https://myapp.com/myaccount/orders/list
can load can use the location url to see what the target path is.
but if you call navigate( '/myaccount/orders/list')
the can load function can not see that path / route

so in any case where the user enters the url can load can see the route but a call from navigate blinds can load to the the same information.

that cripples the utility of can load when the application does navigation.
but can activate does not suffer this route blandness problem.


this difference means that the application has to be designed to not navigate into any feature that needs a can load guard if it needs the route.

**Comment by un33k** [comment] 2017-07-22 16:18
@figuerres This bug negates the usefulness of canLoad guard in many cases. 

Common case:

1. The user bookmarks a URL into a lazy-loaded module that requires auth. (let's call it `1.chunk`)
2. The user sends the url to a friend
3. Sometimes later, the friend clicks on the bookmarked link in step 1
4. `canLoad()` kicks-in & wants to possibly prevent an unnecessary fetch of `1.chunk`
5. The friend is redirected to the login to authenticated first
6. The friend is authenticated, but the system has no recollection of where to redirect the friend to.
7. Very unhappy friend.

The question is, how can we send a link to a lazy-loaded `canLoad-guarded` module and expect the recipient of the link to make it to the destination, post authentication, in this example?

`Workaround`: disable canLoad guards and let canActivate do the guarding.  Yes, your friend just paid the price of loading a chuck, and probably decided not to even follow up with auth.

@Toxicable This is not a special case. Bookmarking in this example is a normal and common use-case.

**Comment by un33k** [comment] 2017-07-22 16:42
@angular/router is like that special someone that you cannot live without, who comes with a flaw, which is when you lend her something, good luck getting it back.

**Comment by ivanpadavan** [comment] 2017-08-16 14:09
I need to make loading of some module by a condition on the same route. I cannot make this scenario because of first-of-all route matching. I think that appropriate place for such is 'canActivateChild' interceptor. But it fires after canLoad.

```{
    path: '',
    canActivateChild: [RootRedirect],
    component: AppComponent,
    children: [
      {
        path: 'auth',
        component: AuthComponent,
      },
      {
        path: 'auth/:role',
        component: AuthComponent,
      },
      {
        path: 'app',
        canLoad: [RootRedirect],
        loadChildren: './modules/admin/admin.module#AdminModule', /*Could be manager or user module by condition*/
      }
    ]
  }```

**Comment by figuerres** [comment] 2017-08-16 18:16
@ivanpadavan 
that only works if the user has entered a url to load the application.

if the app is running and the code issues a navigate request that hit's a can load the path has not been loaded yet, the navigation has not been sent to the browser.
so that does not fix a very common problem.

**Comment by PhotoPaul** [comment] 2017-12-15 09:12
After hours of frustration, I came up with a solution that in my case works perfectly.

```
canLoad(route: Route) {
        if (this.auth.authenticated) {
            return true;
        }

        this.auth.redirectUrl = window.location.pathname;
        this.router.navigate(['/login']);
        return new Promise((resolve) => {
            resolve();
        })
    }
```
**auth** is my Authentication Service
**auth.redirectUrl** is where my Authentication Service navigates the user once authentication succeeds

Basically the Router only knows how to handle **true** or a **Promise**.
If you return **false** it throws one or more errors.

**Comment by fysp11** [comment] 2017-12-15 16:57
What I've observed is that you can't use canLoad on children path.

The same canLoad on "root" path won't work on a child path.

**Comment by figuerres** [comment] 2017-12-15 17:21
the problem has to do with loading a module and that if the guard needs to call an auth that we do not have the full url for the child to use in the post login stage.
this is not an issue if your login process does not need to do navigation.
the other part is that the can load is only able to know the module to be loaded and not which view is the target  so it can't do permission filtering past module level.
each item can be worked past 

by contrast can activate  has the full path .

i think they were adding the full path to can load to solve this.

**Comment by felixhayashi** [comment] 2018-05-11 21:16
@PhotoPaul with your suggestion (using `window.location.pathname`) you are moving away from the router state being your single source of truth. this should only be considered as the last resort.

**Comment by PhotoPaul** [comment] 2018-05-12 07:45
You are absolutely right, I'm open to other working suggestions.

**Comment by DibyodyutiMondal** [comment] 2019-05-07 02:33
I am new to Angular and Typescript and ran into the same problem. After a lot of reading and veritably frustrated with not finding a default for a feature that I now admit I took for granted with frameworks like asp.net, and misled due to expectations that canLoad() will work like canActivate(), I am publishing my solution on this thread with the hope that it saves others valuable time

Relevant excerpts from AuthGuard.ts:

```
@Injectable({
  providedIn: 'root'
})
export class AuthGuard implements CanLoad {

  constructor(
    //inject router for navigation
    private router: Router,
    //other required injections for your case
  ) { }

  canLoad(route: Route, segments: UrlSegment[]): boolean | Observable<boolean> | Promise<boolean> {
    //----implement your authorization logic----//
   
   //when you need to navigate away to login:
  this.router.navigate(['/Login'], {
        queryParams: {
          //I'm using 'returnUrl' here because in my login component, I am using
          //a query parameter with that exact name to redirect after successful authentication
          returnUrl: this.UrlSegmentsToUrl(segments)
        }
      });
}
```

```
private UrlSegmentsToUrl(segments: UrlSegment[]): string {
    //containing string for the result url
    let url: string = '';

    //for each urlSegment, add the path with a leading slash
    segments.forEach(function (value) {
      url = url + '/' + value.path;

      //for each matrix parameter corresponding to the current segment,
      //add the name and value(s) with a leading semicolon
      value.parameterMap.keys.forEach(function (mpk) {

        //get all the value of the current parameter. As of implementation,
        //getAll() returns an array with only one string having comma-separated values,
        //so no further processing needed, but if that changes in the future,
        // we'll need to make a single 'params' string using necessary logic
        let params = value.parameterMap.getAll(mpk)[0];

        url = url + ';' + mpk + '=' + params
      });
    });

    //add any query parameters if present
    let qpindex = window.location.href.indexOf("?");
    if (qpindex != -1) {
      url = url + window.location.href.substr(qpindex);
    }

    return url;
  }
```

I read somewhere that router state is not accessible at the stage when canLoad() is called for routes, so the only choice left was to parse the segments into a string ourselves. It works for both matrix parameters and query parameters, and even if both are used simultaneously. 

As you can see, this method depends on the browser through window.location.href and I am unsure if that is a good thing or a bad thing. However, I tried it with anchor-tag links using both 'deferred' and 'eager' url update strategy, as well as directly typing urls into the browser and they worked
```
//For those who don't know what url update strategy is and how to configure it
@NgModule({
  declarations: [ ],
  imports: [
    BrowserModule,
    BrowserAnimationsModule,
    RouterModule,
    RouterModule.forRoot(
      routes,
      {
        preloadingStrategy: PreloadAllModules,
        anchorScrolling: "enabled",
        scrollPositionRestoration: "enabled",
        urlUpdateStrategy: 'eager'
      }),
    HttpClientModule,
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

However, it is unknown to me what effects configuring the 'paramsInheritanceStrategy' will have on the results of this function. It would be appreciated if those more familiar with this issue clarify that for us.

The UrlSegmentsToUrl() method is heavily expanded for clarity and probably unoptimized because I am a new at Typescript and Angular. Improvements will be appreciated.

**Comment by DibyodyutiMondal** [comment] 2019-05-07 02:48
I am new to Angular and Typescript and ran into the same problem. After a lot of reading and veritably frustrated with not finding a default for a feature that I now admit I took for granted with frameworks like asp.net, and misled due to expectations that canLoad() will work like canActivate(), I am publishing my solution on this thread with the hope that it saves others valuable time. 
I am using Angular 8 which provides an array of UrlSegments in the canLoad(). 

Relevant excerpts from AuthGuard.ts:

```
@Injectable({
  providedIn: 'root'
})
export class AuthGuard implements CanLoad {

  constructor(
    private router: Router,
    //other required injections for your case
  ) { }

  canLoad(route: Route, segments: UrlSegment[]): boolean | Observable<boolean> | Promise<boolean> {
    //----implement your authorization logic----//
   
   //when you need to navigate away to login:
  this.router.navigate(['/Login'], {
        queryParams: {
          returnUrl: this.UrlSegmentsToUrl(segments)
        }
      });
}
```

```
private UrlSegmentsToUrl(segments: UrlSegment[]): string {
    let url: string = '';
    segments.forEach(function (value) {
      url = url + '/' + value.path;
      value.parameterMap.keys.forEach(function (mpk) {

        //getAll() currently returns a string array with only one item, 
        //which contains the comma-separated values,
        //so no further processing needed, but if that changes in the future,
        // we'll need to make a single 'params' string using necessary logic

        let params = value.parameterMap.getAll(mpk)[0];
        url = url + ';' + mpk + '=' + params
      });
    });

    let qpindex = window.location.href.indexOf("?");
    if (qpindex != -1) {
      url = url + window.location.href.substr(qpindex);
    }

    return url;
  }
```
I read somewhere that router state is not accessible at the stage when canLoad() is called for routes, so the only choice left was to parse the segments into a string ourselves, or use a pipe like in the previous answer. It works for both matrix parameters and query parameters, and even if both are used simultaneously. 
What we are essentially doing is:
1. For each url segment, we append a slash followed by the segment name
2. For each matrix parameter corresponding to the current segment, we append a semi-colon and the name and value(s) of the parameter
3. Append any query parameters

As you can see, this method depends on the browser through window.location.href and I am unsure if that is a good thing or a bad thing. However, I tried it with anchor-tag links using both 'deferred' and 'eager' url update strategy, as well as directly typing urls into the browser and they worked
```
//For those who don't know what url update strategy is and how to configure it
@NgModule({
  declarations: [ ],
  imports: [
    BrowserModule,
    BrowserAnimationsModule,
    RouterModule,
    RouterModule.forRoot(
      routes,
      {
        preloadingStrategy: PreloadAllModules,
        anchorScrolling: "enabled",
        scrollPositionRestoration: "enabled",
        urlUpdateStrategy: 'eager'
      }),
    HttpClientModule,
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

However, it is unknown to me what effects configuring the 'paramsInheritanceStrategy' will have on the results of this function. It would be appreciated if those more familiar with this issue clarify that for us.

The UrlSegmentsToUrl() method is heavily expanded for clarity and probably unoptimized because I am a new at Typescript and Angular. Improvements will be appreciated.

**Comment by yankee42** [comment] 2019-11-14 11:00
Concerning the use of `location.pathname`: This does not include queryParams. So if you send a link to your friend "check out what are coolest heroes are": https://example.com/heroes/list?sort=coolness, then the `sort` param will get lost during redirection.

Of course `window.location` does have more properties to also add these and don't forget the fragment. However the solution by @myrddraall actually seems to work just fine. It also includes query params and while it while it cries "this is a weird workaround" it is actually quite easy to understand.

**Comment by maxwellium** [comment] 2020-02-11 18:14
there's an even more angular compliant solution without using window.location:

```typescript
export class AuthnGuard implements CanLoad {
  constructor(private authnService: AuthnService, private router: Router) { }

  canLoad( ): Observable<boolean> | Promise<boolean> | boolean {
    const navigation = this.router.getCurrentNavigation();
    let url = '/';

    if (navigation) {
      url = navigation.extractedUrl.toString();
    }
    this.authnService.storeRedirectUrl(url);
```
...

**Comment by atscott** [comment] 2020-07-08 20:08
As @maxwellium mentioned, this information would be available by using `this.router.getCurrentNavigation()`. If I'm understanding this issue correctly, that should accomplish the goal here. Can this be closed now or is that not what's needed?

**Comment by atscott** [comment] 2021-02-09 18:10
Closing, as the information is available using `this.router.getCurrentNavigation()`

**Closed by atscott** 2021-02-09 18:10 UTC
Labels: comp: router, feature, freq2: medium, router: guards/resolvers
