### ISSUE TITLE
Use loadChildren load sub module, when visit sub route page, submodule's dependency module will repeat new.

### ISSUE THREAD

**Issue by hstarorg** [angular/angular#13885] opened 2017-01-12 09:16 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Use loadChildren loaded module will repeat new dependencies module.

**Expected behavior**
Not repeat new, use the singleton module.

**Minimal reproduction of the problem with instructions**

Define a child module, set more than one route, like this:

```javascript
import { ModuleWithProviders } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';

import {
  Page1Component,
  Page2Component
} from './pages';

const appRoutes: Routes = [
  { path: '', component: Page1Component },
  { path: 'page2', component: Page2Component },
];

export const routing: ModuleWithProviders = RouterModule.forChild(appRoutes);

```

In the parent routing config, dynamic load the child module, like this:

```javascript
import { SubModule } from 'modules/demo1';
const appRoutes: Routes = [{
  path: '', component: LayoutComponent,
  children: [
    { path: 'demo1', loadChildren: () => AppModule },
    { path: '**', component: NotFoundComponent }
  ]
}];
export const routing: ModuleWithProviders = RouterModule.forRoot(appRoutes, { useHash: true });
```

When visit `/demo1` and  `/demo1/page1`, the sub module's dependency module will also  init.

**What is the motivation / use case for changing the behavior?**
When route change in dynamic loaded module.

**Please tell us about your environment:**
It is not important.

* **Angular version:** 
2.4.1

**Comment by DzmitryShylovich** [comment] 2017-01-12 09:25
Duplicate of https://github.com/angular/angular/issues/12889

**Comment by hstarorg** [comment] 2017-01-12 09:27
@DzmitryShylovich  Caused a new problem, that can't use common module's service to store data.

**Comment by mhevery** [comment] 2017-01-13 22:20
@hstarorg whey can't you use common-module service to store data?

**Comment by hstarorg** [comment] 2017-01-16 10:35
@mhevery Only common-module is dynamic load will has the bug.

**Comment by hstarorg** [comment] 2017-02-15 11:44
@DzmitryShylovich Would you tell me which version will fix this bug?

**Comment by DzmitryShylovich** [comment] 2017-02-15 11:46
@hstarorg 4.0 (not sure about 2.x)

**Comment by hstarorg** [comment] 2017-02-15 11:48
@DzmitryShylovich 4.0.0-beta.7 also has this bug,

**Comment by DzmitryShylovich** [comment] 2017-02-15 12:03
4.0 final...

**Comment by hstarorg** [comment] 2017-02-15 13:54
@DzmitryShylovich ok, I must waiting a long time.

**Closed** 2017-03-14 23:26 UTC
Labels: comp: router
