### ISSUE TITLE
R3InjectorError with services not providedIn root

### ISSUE THREAD

**Issue by Fabiryn** [angular/angular#39811] opened 2020-11-23 13:02 UTC
# 🐞 bug report

### Affected Package

@angular/core

### Is this a regression?

it worked for angular 9 and for 10. Somehow when I try to set the angular version to 10, I also run into this issue now.

### Description

After updating to angular 11, my app started to show errors similar to this:
```
NullInjectorError: R3InjectorError(AngularPageModule)[AngularService -> AngularService -> TestService -> TestService -> TestService]
```
Seems like the DependencyInjector has a problem to find services, which were not `providedIn: "root"`. So in the main scenario I consume `@ionic-native/file` or other native wrapper libraries. These come with services without the `providedIn: "root"` decorator. However the services consuming these libraries use the `providedIn: "root"` method. Only providing the service without the `providedIn` decorator, doesn't help.

The only workaround I could find, is to manually provide the outer service and the ionic-native service.

<details>
<summary>In Code</summary>

ionic.service.ts
```typescript
import {Injectable} from '@angular/core';
import {File} from '@ionic-native/file/ngx';

@Injectable({
  providedIn: 'root'
})
export class IonicService {

  constructor(private readonly file: File) {
  }

  ...
}
```
ionic.module.ts
```typescript
import {NgModule} from '@angular/core';
import {CommonModule} from '@angular/common';
import {File} from '@ionic-native/file/ngx';

@NgModule({
  declarations: [],
  imports: [
    CommonModule
  ],
  providers: [
    File
  ]
})
export class IonicServiceModule {
}
```
</details>

It also gets more confusing when using an angular library and try to use the `providedIn` method. When just using an angular app, you could provide the missing ionic-native service in the core `app.module.ts` and the DI is working.
On the other hand, when you try the same thing with an angular lib (shown in the repo), it doesn't work.

## 🔬 Minimal Reproduction

https://github.com/Fabiryn/angular-lib-injector-bug

## 🔥 Exception or Error
<pre><code>ERROR Error: Uncaught (in promise): NullInjectorError: R3InjectorError(AngularPageModule)[AngularService -> AngularService -> TestService -> TestService -> TestService]: 
  NullInjectorError: No provider for TestService!
NullInjectorError: R3InjectorError(AngularPageModule)[AngularService -> AngularService -> TestService -> TestService -> TestService]: 
  NullInjectorError: No provider for TestService!
    at NullInjector.get (core.js:10756)
    at R3Injector.get (core.js:10923)
    at R3Injector.get (core.js:10923)
    at R3Injector.get (core.js:10923)
    at injectInjectorOnly (core.js:2290)
    at ɵɵinject (core.js:2294)
    at Object.AngularService_Factory [as factory] (herbert.js:93)
    at R3Injector.hydrate (core.js:11091)
    at R3Injector.get (core.js:10912)
    at NgModuleRef$1.get (core.js:24988)
    at resolvePromise (zone-evergreen.js:798)
    at resolvePromise (zone-evergreen.js:750)
    at zone-evergreen.js:860
    at ZoneDelegate.invokeTask (zone-evergreen.js:399)
    at Object.onInvokeTask (core.js:28225)
    at ZoneDelegate.invokeTask (zone-evergreen.js:398)
    at Zone.runTask (zone-evergreen.js:167)
    at drainMicroTaskQueue (zone-evergreen.js:569)
    at ZoneTask.invokeTask [as invoke] (zone-evergreen.js:484)
    at invokeTask (zone-evergreen.js:1621)
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>Angular CLI: 11.0.2
Node: 14.15.0
OS: darwin x64

Angular: 11.0.2
... cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.2
@angular-devkit/build-angular   0.1100.2
@angular-devkit/core            11.0.2
@angular-devkit/schematics      11.0.2
@schematics/angular             11.0.2
@schematics/update              0.1100.2
rxjs                            6.5.5
typescript                      4.0.5
</code></pre>

**Comment by jelbourn** [comment] 2020-12-02 16:24
@mhevery did anything change with DI resolution that would affect this for v11?

**Comment by mhevery** [comment] 2020-12-02 20:22
@Fabiryn let me see if I understand the issue. You have 
````
@Injectable({
  providedIn: 'root'
})
class AngularService {
  constructor(test:TestService) {...}
}

@Injectable()
export class TestService {}

@NgModule({
  providers: [
    TestService,
    // AngularService, <== POINT OF INTEREST
  ]
})
export class AngularPageModule {
}

```

When the system is configured without explicitly listing `AngularService` in `AngularPageModule` then you get the above error. When on the other hand you explicitly list `AngularService` in `AngularPageModule` then everything works. 

I believe this is working as intended. In your application you create an injector hierarchy as follows (simplified): 

```
- rootInjector
   - angularPageModuleInjector
```

Above notice that `angularPageModuleInjector` is a child of `rootInjector`.

Use cases:
- When `AngularService` is explicitly listed in `AngularPageModule`, then:
```
- rootInjector
   - angularPageModuleInjector {
        TestService: new TestService(),
        AngularService: new AngularService(thisInjector[TestService]),
      }
```
In above setup everything works.

- When `AngularService` is *NOT* explicitly listed in `AngularPageModule`, then `AngularService` is provided by `rootInjector` like so
```
- rootInjector {
     AngularService: new AngularService(thisInjector[TestService]), <= ERROR
   }
   - angularPageModuleInjector {
        TestService: new TestService(),
      }
```

The above will error out as `rootinjector` can't see `angularPageModuleInjector`

So if my understanding of the issue is correct, this is working as intended. Do let me know if I am misunderstanding.

As to why it used to work, that is not clear to me, but it seems like a bug fix must have landed which made the behavior consistent.

**Comment by jelbourn** [comment] 2020-12-02 23:38
Closing as working as intended- feel free to revisit if there's more information that would indicate a bug.

**Closed by jelbourn** 2020-12-02 23:38 UTC
Labels: P3, comp: core
