### ISSUE TITLE
DatePipe shows years 2027, 2028 wrongly as 2026, 2027

### ISSUE THREAD

**Issue by josoing** [angular/angular#45234] opened 2022-03-02 12:25 UTC
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

No

### Description

DatePipe shows years 2027 and 2028 (possibly others) wrongly as 2026 and 2027 when format parameter is set.

{{ 'Jan 1, 2026' | date: 'YYYYMMMdd' }}, 
{{ 'Jan 1, 2027' | date: 'YYYYMMMdd' }}, 
{{ 'Jan 1, 2028' | date: 'YYYYMMMdd' }}

result:
2026Jan01, 2026Jan01, 2027Jan01 

expected:
2026Jan01, 2027Jan01, 2028Jan01 

Issue appears also when JavaScript Date object is used as input. Issue appears also when other formats are set. Issue does not appear when format parameter is not set. Seems wrong years can vary if date is set to other day or month than Jan 1.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-vtbbem?file=src/app/app.component.html

### Please provide the exception or error you saw

```true
no exception or error
```

### Please provide the environment you discovered this bug in (run `ng version`)
Angular CLI: 13.2.3
Node: 16.5.0
Package Manager: npm 7.19.1
OS: linux x64

Angular: 13.2.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

### Anything else?
Observed on Ubuntu, Firefox and Chrome

**Comment by JoostK** [comment] 2022-03-02 12:54
Duplicate of #44350, #44425, #44715, #44722. You should be using `yyyy`

**Closed by JoostK** 2022-03-02 12:54 UTC
