### ISSUE TITLE
Add info for required inputs in ComponentMirror inputs array

### ISSUE THREAD

**Issue by nikolatasikj** [angular/angular#53653] opened 2023-12-20 14:42 UTC
### Description

If we create ComponentMirror from some component, there is an array with all the inputs from that component, but currently, there is no way to determine if that input is required or not.
`reflectComponentType(component).inputs` - This will give only an array of inputs with no info for `required: true`

### Proposed solution

`reflectComponentType(component).inputs` - This array should be an array of objects where we will have the name of the input and info about whether is it required or not, something like:
`[{name: "inputName", required: true}]`

### Alternatives considered

There is no other way to determine if the input is required because it's info in the decorator.

**Comment by JoostK** [comment] 2023-12-20 14:51
Essentially a duplicate of #52117, with https://github.com/angular/angular/issues/52117#issuecomment-1755989206 still true today.

**Closed** 2023-12-20 15:41 UTC
