### ISSUE TITLE
Router exponentially slows down by increasing outlet count

### ISSUE THREAD

**Issue by vendi95** [angular/angular#40310] opened 2021-01-05 14:22 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/router

### Is this a regression?

 Probably not.

### Description
In our application, users can open multiple virtual windows. Each of them uses a router outlet to display content. The maximum number of openable windows is limited by the number of different outlets in the router config.
Unfortunately, we found out, that increasing the number of sibling outlets with (the same) children routes leads to an exponential slowdown.
The debugger shows that the Recognizer.processSegmentAgainstRoute function is causing the bad performance.

In the provided stackblitz example this function takes the following times on my machine:
20 outlets - 10ms
200 outlets - 954ms
2000 outlets - 187000ms

In our real project, these times are somewhat higher. So using a not unrealistic (20-30) number of windows already leads to long tasks.

## 🔬 Minimal Reproduction

 https://stackblitz.com/edit/angular-ivy-ldbunw?file=src/app/app.module.ts

Navigation will be slow when clicking the links. This is with 200 outlets with 2 children each.

## 🌍  Your Environment
Also reproduced in Angular 10 on stackblitz.

**Angular Version:**
<pre><code>
Angular CLI: 9.1.11
Node: 12.16.2
OS: win32 x64

Angular: 9.1.12
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router, service-worker
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.11
@angular-devkit/build-angular     0.901.11
@angular-devkit/build-optimizer   0.901.11
@angular-devkit/build-webpack     0.901.11
@angular-devkit/core              9.1.11
@angular-devkit/schematics        9.1.11
@angular/cdk                      9.2.4
@angular/cli                      9.1.11
@ngtools/webpack                  9.1.11
@schematics/angular               9.1.11
@schematics/update                0.901.11
rxjs                              6.6.0
typescript                        3.8.3
webpack                           4.42.0

</code></pre>

**Comment by atscott** [comment] 2021-01-06 20:48
Hi @vendi95, I think the issue is that all of your outlets are matching because they start with the empty path (which is sort of a "phantom" match that doesn't map to any part of the url). So for each outlet you've defined, the empty path route gets "activated". Each matched outlet then tries to find a matching config matches. So by the end of the traversal, you've exponentially increased the the attempted matches by something like `[num outlets]^2` (with three outlets, 3 empty path matches, then each empty path tries to match against the 3 defined outlets `= 3*3`).

You can fix this by modifying your config so that you don't have the empty path outlet at the top level:
https://stackblitz.com/edit/angular-ivy-dezs2b?file=src/app/app.module.ts
This is your same example with `20,000` outlets and no discernible performance hit.

**Comment by mlc-mlapis** [comment] 2021-01-06 21:39
@atscott Great shot in the black. 🚀

**Comment by atscott** [comment] 2021-11-01 03:47
Closing as working as expected, per https://github.com/angular/angular/issues/40310#issuecomment-755672307

**Closed by atscott** 2021-11-01 03:47 UTC
Labels: comp: router, type: use-case, router: config matching/activation/validation, P5
