### ISSUE TITLE
navigation have white screen flicker on swipe on ios

### ISSUE THREAD

**Issue by hiepxanh** [angular/angular#45223] opened 2022-03-01 09:38 UTC
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

No

### Description
I think it is a bug since angular animation not solve the problem 

https://drive.google.com/file/d/1TXrvWSaAGtcddV2tlTPcNrB7WwwixdRx/view?usp=sharing

compare with https://ionicframework.com/ and https://angular.io

CASE 1: routing still on screen:
- we do not scroll down, just routing on the current screen. forward and backward show preview on next / previous page smoothly.
CASE 2: scroll down below screen:
- we scroll down  below screen. then tap to next route (other page). then `swipe back` on ios. that thing happen. ionicframework page still show preview good. and other page (not angular) is still normal. But angular.io is have white screen. only swipe complete it start render screen. 
that really weird, my customer start complain about this so I notice this. It's small detail but ... well. user report to me. and I make this issue

### Please provide a link to a minimal reproduction of the bug

 https://angular.io

### Please provide the exception or error you saw

```true
scroll down screen. Tap other route. Swipe back must still have preview, not have white screen and flicker.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1301.2 (cli-only)
@angular-devkit/build-angular   13.1.2
@angular-devkit/core            13.2.2
@angular-devkit/schematics      13.2.2
@angular/cli                    13.1.2
@nguniversal/builders           13.0.2
@nguniversal/common             13.0.2
@nguniversal/express-engine     13.0.2
@schematics/angular             13.2.2
rxjs                            7.5.2
typescript                      4.5.4
webpack                         5.68.0

```
```


### Anything else?

I'm try a lot of version:
- have lazyload >< non lazyload 
- have service worker >< no service worker
- have SSR >< no SSR

still not affect this.

**Comment by atscott** [comment] 2022-03-01 16:55
I did see this on angular.io but could not reproduce it in other Angular applications. As such, I'm removing the `router` tag because this appears to be more of a property of application layout rather than any router components or behavior.

Please provide a _minimal_ reproduction so this can be investigated further.

**Comment by atscott** [comment] 2022-03-01 19:12
I'm actually going to close this as unrelated to Angular. I was able to reproduce it with ionicframework.com on iOS as well. Scrolling down and then up a bit reproduces the problem. Scrolling a bit up so the interface appears again then slightly swiping back does show the preview. While this doesn't fix it on angular.io, an example application does act the same as the ionic website (https://angular-ivy-router-base-ctgws4.stackblitz.io/parent). So this really appears to be an issue with iOS anyways. Regardless, this isn't something we'd spend time investigating and fixing even if it were an issue with Angular.

**Closed by atscott** 2022-03-01 19:12 UTC
Labels: needs reproduction, comp: docs-infra, iOS, P5

**Comment by hiepxanh** [comment] 2022-03-07 03:37
finally, can find which is root cause of this issue https://github.com/angular/universal/issues/1164

```
What is the current behavior?
All the style elements from SSR, style[ng-transition], are removed.
The page is effectively being re-rendered client side causing the page/component to flicker.
The flicker duration is dependent on the bundle size of lazy loaded module. For heavier modules, it takes a bit for the bundle to be downloaded and parsed causing extended period of white screen.
```

**Comment by hiepxanh** [comment] 2022-03-24 10:21
I think it is SPA problem https://stackoverflow.com/questions/47792759/scrollrestoration-set-to-manual-and-swipe-back-functionality-on-safari-ios

iOS swipe back gesture that shows a white background in the back (sneak peek) and once the swipe is made nothing happens for 2-3 seconds.

Desired: show previous state or disable the gesture with all.

If you want to see this behaviour you can check the view screen capture linked bellow or check https://mobile.twitter.com/ on your iPhone.

Any ideas on how to achieve the desired behaviour mentioned above?

Current behaviour: http://recordit.co/rn5ORRtICg

it must be cache system problem

**Comment by hiepxanh** [comment] 2022-03-24 10:26
yes it is it: https://web.dev/bfcache/
