### ISSUE TITLE
@angular/platform-server need support to generate HTML as the pre-rendered version

### ISSUE THREAD

**Issue by 4garfield** [angular/angular#16985] opened 2017-05-24 07:59 UTC
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Currently, the `renderModuleFactory` method generated HTML depends the client `main.bundle.js`. If use this HTML as pre-rendered version, while browser load the HTML, Angular would re-render the DOM.

**Expected behavior**

The platform-server package can provide the method to generate the pre-rendered HTML version

**Minimal reproduction of the problem with instructions**

the entry file: main.server.ts:
```typescript
import { ngExpressEngine } from '@nguniversal/express-engine';
import * as express from 'express';
import { AppServerModule } from './app/app.server.module';
import { ROUTES } from './routes';

app.engine('html', ngExpressEngine({
  bootstrap: AppServerModule
}));

app.set('view engine', 'html');
app.set('views', 'dist/client');

ROUTES.forEach(route => {
  app.get(route, (req, res) => {
    console.time(`GET: ${req.originalUrl}`);
    res.render('index', {
      req: req,
      res: res,
      preboot: true,
    });
    console.timeEnd(`GET: ${req.originalUrl}`);
  });
});
```

After the express server start, using `curl` to get the generated HTML as pre-rendered version.
upload the HTML file to CDN network, open the HTML URL in browser, Angular would re-render the DOM.

**What is the motivation / use case for changing the behavior?**

In some use case, we only have static web server & we also care about the SEO, so we choose Angular Universal.
And we want to use the pre-rendered HTML to boot app.

**Please tell us about your environment:**

* **Angular version:** 4.1.2

* **Browser:** [all ]

 
* **Language:** [TypeScript 2.3.2]

* **Node (for AoT issues):** `node --version` = v6.9.1

Reference: #13822

**Comment by adrienboulle** [comment] 2017-06-04 19:34
I'm not sure to understand ? The pre-render html is not meant to be re-used by the platform-browser, it's "just" here for a better user expérience and of course for SEO. What's wrong with that ?

**Comment by trotyl** [comment] 2017-06-05 01:38
It's already on the [roadmap](https://github.com/angular/universal/blob/master/README.md#angular-50-and-beyond) I think:

> Full client rehydration strategy that reuses DOM elements/CSS rendered on the server

Maybe relates to https://github.com/angular/angular/issues/13446

**Comment by adrianolsk** [comment] 2017-08-10 14:58
@adrienboulle It work for SEO but for better user experience it's not the case since it brings the html rendered on the server (from a http call)  to the client and on the client the data disappear and the http call is fired again.

So it blinks the app ( If your http call is fast) or it's just an empty placeholder (If http call takes too long)

Full client rehydration would be the solution indeed.

**Comment by feloy** [comment] 2017-09-17 17:36
@adrienboulle I can confirm that it is not a good user experience. You can see in this website (http://codes-lois-reglements.fr/) for example that the first loaded page blinks after the content is re-loaded and redisplayed by the XHR request.

It would be interesting to have a process that:
- do not XHR-reload content if the content is already present in the DOM (thanks to server-side rendering)
- or, better, XHR-load the content and compare if the XHR-loaded content is newer than the already displayed content (from SSR) with some hashID placed in the DOM for example , so we can have potentially older server-rendered versions that would be updated by XHR.

**Comment by CaerusKaru** [comment] 2020-06-17 06:06
@feloy You can use `TransferState` to accomplish what you commented about. Otherwise, @trotyl is correct that this is a duplicate of the main rehydration tracking issue.

**Comment by CaerusKaru** [comment] 2020-06-17 06:06
Duplicate of #13446

**Closed by CaerusKaru** 2020-06-17 06:06 UTC
Labels: comp: server, type: feature
