### ISSUE TITLE
Router throws 'Cannot activate an already activated outlet' when lazy loaded module fails and tries to navigate to another route.

### ISSUE THREAD

**Issue by DanPinzaru** [angular/angular#29303] opened 2019-03-14 11:45 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/router

### Is this a regression?

 No

### Description

A lazy loaded route with a path of 'users' is a child route of a 'dashboard' router state.
If the URL 'http:://app-name/dashboard/users' is navigated from the browser window (not programatically) and an uncaught error is triggered (in my case I forgot to register a service), the router is unable to navigate anywhere else afterwards. In my case I have a custom error handler where I attempt to bring the user to an `error` page, when trying to navigate to the error page another error is thrown: 

`Error: Cannot activate an already activated outlet`.

I believe this happens because the `users` route is a lazy loaded child route of 
the `dashboard` route which is not lazy loaded. It seems that the <router-outlet> directive
responsible for attaching the dashboard (default) component is not deactivated if building 
the lazy loaded module fails.

A snippet of my routes config:

<pre>
[{
   path: 'dashboard',
   component: DefaultPageComponent,
   children: [{
       path: 'home',
       loadChildren: './home/home.module#HomeModule'
  }, {
       path: 'users',
       loadChildren: './users/users.module#UsersModule
  }]
}]
</pre>

My guess that the parent `DefaultPageComponent` is involved is based on me trying to 
deliberately invoke the same error on a lazy loaded route that did NOT have a parent route, 
the intentional error was thrown and my custom error handler was able to navigate to the
error route successfully.

Link to stackblitz repo is below. Please note that this happens only 
when visiting the lazy loaded route directly from browser's address bar so after
opening the stackblitz, please change the URI to `/dashboard/users`. When navigating to the failing `/dashboard/users` programatically (or using routerLink), the error handler
is able to successfully navigate to the error page.

There are ways for me to get around this but it would be nice to have it working without any 
messy logic.

Thanks for taking the time!

## 🔬 Minimal Reproduction

 https://stackblitz.com/edit/router-bug-report

## 🔥 Exception or Error
<pre><code>

Error: Uncaught (in promise): Error: Cannot activate an already activated outlet
Error: Cannot activate an already activated outlet
    at RouterOutlet.activateWith (router_outlet.ts:127)
    at ActivateRoutes.activateRoutes (activate_routes.ts:187)
    at eval (activate_routes.ts:133)
    at Array.forEach (<anonymous>)
    at ActivateRoutes.activateChildRoutes (activate_routes.ts:132)
    at ActivateRoutes.activate (activate_routes.ts:42)
    at MapSubscriber.eval [as project] (activate_routes.ts:27)
    at MapSubscriber._next (map.ts:84)
    at MapSubscriber.Subscriber.next (Subscriber.ts:99)
    at TapSubscriber._next (tap.ts:125)
    at resolvePromise (zone.js:831)
    at resolvePromise (zone.js:788)
    at eval (zone.js:892)
    at ZoneDelegate.invokeTask (zone.js:423)
    at Object.onInvokeTask (ng_zone.ts:262)
    at ZoneDelegate.invokeTask (zone.js:422)
    at Zone.runTask (zone.js:195)
    at drainMicroTaskQueue (zone.js:601)
    at ZoneTask.invokeTask (zone.js:502)
    at ZoneTask.invoke (zone.js:487)
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre>7.2.5<code>

</code></pre>

**Anything else relevant?**

**Comment by christopher-ingmar-schramek** [comment] 2019-06-06 21:50
Duplicate of #20694.

**Comment by Zarepheth** [comment] 2019-11-19 23:08
> 
> 
> Duplicate of #20694.

This error can happen with nested, lazy-loaded, primary routes - not merely with named router outlets.

**Comment by bhushanon** [comment] 2020-02-11 23:57
Is there any work around for this? I have a well organized Child route structure, i don't want to change that as it will be a large change

**Comment by saghishiri** [comment] 2020-09-15 08:17
same issue, any ideas?

**Comment by ihor-zinchenko** [comment] 2020-10-02 10:23
same for me

**Comment by hawkwind71** [comment] 2020-10-05 04:53
same issue for me

**Comment by atscott** [comment] 2021-01-06 21:50
Should be fixed by #40196

**Closed by atscott** 2021-01-06 21:50 UTC
Labels: P3, comp: router, freq3: high, router: config matching/activation/validation, router: lazy loading, state: confirmed, type: bug/fix
