### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by bhosalevishal** [angular/angular#25439] opened 2018-08-11 11:25 UTC
There is a typo on this screen/page
https://angular.io/guide/architecture

There are **tow** types of data binding: -- NG.
There are **two** types of data binding: -- OK.

**Comment by JoostK** [comment] 2018-08-11 11:27
Duplicate of pending PR #25438

**Comment by pkozlowski-opensource** [comment] 2018-08-13 12:05
Thnx @JoostK - it is indeed a duplicate of pending PR #25438. I'm going to close this issue here as the mentioned PR is approved and will be merged.

**Closed by pkozlowski-opensource** 2018-08-13 12:05 UTC
