### ISSUE TITLE
Template variables does not exist if *ngIf is used

### ISSUE THREAD

**Issue by aureole82** [angular/angular#40126] opened 2020-12-15 11:30 UTC
# 🐞 Bug report

As long as a `*ngIf` is used on a tag the tag or its children cannot define template variables used somewhere else outside the 
`*ngIf` decorated tag.

## My simplified issue
```html
<span [class.invalid]="form2?.isInvalid">Model 2</span>
<app-form *ngIf="true" #form2 ...></app-form>
```
returns:
> Property 'form2' does not exist on type 'AppComponent'.

## My complete use case
https://stackblitz.com/edit/no-template-reference-ngif?file=src%2Fapp%2Fapp.component.html

## Expected
Template variables should be declared at least. (But might not be initialized if `*ngIf="false"`.)

**Comment by Airblader** [comment] 2020-12-15 16:40
This is working as intended. Structural directives turn into their own template, and there's no sensible way to refer to a template reference variable which is inside s different template since you cannot know how many times that template will be instantiated (ngIf isn't special compiler syntax).

**Comment by Airblader** [comment] 2020-12-15 16:43
See https://angular.io/guide/template-reference-variables#template-variable-scope

**Comment by alxhub** [comment] 2020-12-15 22:11
@Airblader is correct. Translating your code to plain JS further illustrates why this doesn't work:

```typescript
if (true) {
  const form2 = new AppFormCmp(...);
}
span.class.invalid = form2.invalid; // error, form2 is not in scope here.
```

**Closed by alxhub** 2020-12-15 22:11 UTC

**Comment by aureole82** [comment] 2020-12-17 09:56
First of all: I'm really sorry that I missed the corresponding part in the documentation. So of course **it's not a bug**!

But's a **feature request** now, I'd like to have:
```ts
let form2 : AppFormCmp = null;
if (true) {
  form2 = new AppFormCmp(...);
}
span.class.invalid = form2?.invalid; // error, form2 is in scope here.
```

**Comment by Airblader** [comment] 2020-12-17 10:21
This is just fundamentally incompatible with how structural directives work. You're focusing on the ngIf case, but for something like ngFor there's no logical way of how this should even behave. Both ngIf and ngFor are "just" regular structural directives, though.

The only way to address this is by making ngIf not a structural directive inside angular/common, but part of the template syntax in the compiler. This is something the team has stated they are thinking about doing, but without concrete plans at the moment.

**Comment by Airblader** [comment] 2020-12-17 10:31
Just to reference that, see https://github.com/angular/angular/issues/14479#issuecomment-742775350

> We've discussed on-and-off the idea of someday moving from ngIf and ngFor directives to something built into the templating language in order to reduce the cost of ngIf and ngFor as directives (basically optimizing them in the framework directly).

**Comment by petebacondarwin** [comment] 2020-12-17 10:31
Depending upon your use case, you could workaround this by simply "hiding" the element using `[style.visible]` instead of `*ngIf`: https://stackblitz.com/edit/no-template-reference-ngif-itg3vu?file=src%2Fapp%2Fapp.component.html

**Comment by aureole82** [comment] 2020-12-17 10:48
@Airblader I really appreciate that the team is thinking about it. 🤞

@petebacondarwin Hiding a template when its corresponding model is `null` (instead of omitting) needs to handle the `null` case inside the complete component. That's very nasty and the next violation of the Single Responsibility Principle.

**Comment by Airblader** [comment] 2020-12-17 10:54
The solution for now is to not use template reference variables in this case, but rather a `@ViewChild` query. 

> In a big team of developers it's very likely one developer introduces the template variable and weeks later another puts a tiny *ngIf somewhere and everything is spoiled.

If your project is set up correctly, this will fail compilation, so this should be caught at the very latest in your CI anyway.
