### ISSUE TITLE
@ContentChildren does set value every time the DOM changes

### ISSUE THREAD

**Issue by wis-ekubesh** [angular/angular#32121] opened 2019-08-13 14:43 UTC
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/core@8.2.0

### Is this a regression?
No

### Description
As we can see in the documentation ([link](https://angular.io/api/core/ContentChildren#description)) – we are getting QueryList by using ContentChildren decorator and after that all changes will happen in QueryList.

By this logic next pice of code should be executed only once.

```javascript
@ContentChildren(DirectDirective)
private set columnTemplates(listColumnDirectives: QueryList<DirectDirective>) {

   // Some logic here

}
```

But actually it will be executed for every change target element in the DOM.

What is it? Is it documentation problem (hidden feature) or bug? Can I use this approach in my projects instead of subscribe to QueryList changes or not?

Also tested with Ivy and still have this behaviour.

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-bxznyt

## 🌍  Your Environment

**Angular Version:**

All Angular packages have 8.2 version

**Comment by mlc-mlapis** [comment] 2019-08-13 15:00
@wis-ekubesh This still the setter, so `listColumnDirectives` is the coming value and inner code runs every time when the value is being changed.

**Comment by wis-ekubesh** [comment] 2019-08-13 15:22
> @wis-ekubesh This is still the setter, so `listColumnDirectives` is the coming value and inner code runs every time when the value is being changed.

Yes, but in docs we can see

> Any time a child element is added, removed, or moved, the query list will be updated

And by this logic query list should be updated but not re-created again.
Otherwise it doesn't make sense to subscribe to QueryList changes.

**Comment by pkozlowski-opensource** [comment] 2019-08-13 15:30
> And by this logic query list should be updated but not re-created again.

Are you sure it is re-created? I think that it is just re-assigned (I mean, a setter is called with the same `QueryList` instance).

**Comment by wis-ekubesh** [comment] 2019-08-13 16:41
> > And by this logic query list should be updated but not re-created again.
> 
> Are you sure it is re-created? I think that it is just re-assigned (I mean, a setter is called with the same `QueryList` instance).

Yes, I meant re-assigned, sure.

**Comment by mlc-mlapis** [comment] 2019-08-13 16:52
@wis-ekubesh But the standard using is the syntax:

@ContentChildren(DirectDirective) private listColumnDirectives: QueryList<DirectDirective>;

**Comment by wis-ekubesh** [comment] 2019-08-13 17:05
@mlc-mlapis yes, but I just didn't want to create and manage Subscription for listen changes. 
As I think my approach just easier way to interact with content children changes and I want to be sure that I can do that like in my example (with setter). And that it won't be broken with future release.

**Comment by mhevery** [comment] 2019-08-22 22:37
This is by intention. Every time the query changes we re-assign the same instance. 

Closing as working as intended.

**Closed by mhevery** 2019-08-22 22:37 UTC
Labels: comp: core
