### ISSUE TITLE
Secondary route in lazy loading module cannot matches

### ISSUE THREAD

**Issue by cecilulysess** [angular/angular#37807] opened 2020-06-28 09:40 UTC
# 🐞 bug report

### Affected Package

The issue is caused by package @angular 9.1.11

### Is this a regression?
Unsure.

### Description

The RouterLink to a secondary/auxiliary route at a lazy loaded module not able to route. An exception "Cannot match any routes" thrown (Example 1 below.)
However, directly import the module works fine (Example 2 below).

Another example that putting the secondary route at a mat dialog (Example 3 below). It throws an error that not able to match the secondary route's own url. However, once change to import by simply comment out line 32 at app.module.ts. It works fine.

 A clear and concise description of the problem...

## 🔬 Minimal Reproduction
[Example 1: https://stackblitz.com/edit/angular-ivy-ythkup](https://stackblitz.com/edit/angular-ivy-ythkup) <-- broken example
[Example 2: https://stackblitz.com/edit/angular-ivy-jpyfsp](https://stackblitz.com/edit/angular-ivy-jpyfsp)   <-- working example without lazy loading

[Example 3: https://stackblitz.com/edit/angular-ivy-6vcr55?file=src%2Fapp%2Fapp.module.ts](https://stackblitz.com/edit/angular-ivy-6vcr55?file=src%2Fapp%2Fapp.module.ts) <-- example with mat dialog

## 🔥 Exception or Error

<pre><code>
preview-7c4885dca5d67df12ae8b.js:1 ERROR Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'demo'
Error: Cannot match any routes. URL Segment: 'demo'
    at ApplyRedirects.noMatchError (router.umd.js? [sm]:2743)
    at CatchSubscriber.eval [as selector] (router.umd.js? [sm]:2724)
    at CatchSubscriber.error (catchError.ts:132)
    at MapSubscriber.Subscriber._error (Subscriber.ts:143)
    at MapSubscriber.Subscriber.error (Subscriber.ts:113)
    at MapSubscriber.Subscriber._error (Subscriber.ts:143)
    at MapSubscriber.Subscriber.error (Subscriber.ts:113)
    at MapSubscriber.Subscriber._error (Subscriber.ts:143)
    at MapSubscriber.Subscriber.error (Subscriber.ts:113)
    at ThrowIfEmptySubscriber.Subscriber._error (Subscriber.ts:143)
    at resolvePromise (zone.js:832)
    at resolvePromise (zone.js:784)
    at eval (zone.js:894)
    at ZoneDelegate.invokeTask (zone.js:421)
    at Object.onInvokeTask (core.umd.js? [sm]:28252)
    at ZoneDelegate.invokeTask (zone.js:420)
    at Zone.runTask (zone.js:188)
    at drainMicroTaskQueue (zone.js:601)
    at ZoneTask.invokeTask [as invoke] (zone.js:507)
    at invokeTask (zone.js:1671)
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
9.1.11
</code></pre>
Version 83.0.4103.106 (Official Build) (64-bit) @ Ubuntu 20.04

**Anything else relevant?**

**Comment by destus90** [comment] 2020-06-28 11:00
Duplicate of https://github.com/angular/angular/issues/24562

**Comment by atscott** [comment] 2020-06-30 21:19
Duplicate of #10726

**Closed by atscott** 2020-06-30 21:19 UTC
Labels: comp: router
