### ISSUE TITLE
Closed tickets "locked" after 30 days without activity (angular-automatic-lock-bot)

### ISSUE THREAD

**Issue by Chealer** [angular/angular#43639] opened 2021-09-29 21:42 UTC
Ticket #43071 was presumably closed by error, but unfortunately that cannot be determined since it was "locked".
As can be seen in [the last comment](https://github.com/angular/angular/issues/43071#issuecomment-927142246), a bot (angular-automatic-lock-bot) "locked" the ticket, which even I can no longer comment, as the form was replaced with:

> This conversation has been locked and limited to collaborators.

There are 2 issues here.

The first is purely terminological. The bot’s message is nonsensical, referring to "issue locking", "issue filing", and "conversation locking".

The second is that tickets would be locked at all. [The linked document](https://github.com/angular/angular/blob/8f24bc9443b3872fe095d9f7f77b308a361a13b4/docs/GITHUB_PROCESS.md#conversation-locking) gives the following as only "reason":

> Why lock conversations?
> 
> Automatically locking closed, inactive issues guides people towards filing new issues with updated context rather than commenting on a "resolved" issue that contains out-of-date or unrelated information. As an example, someone may comment "I'm still having this issue", but without providing any of the additional information the team needs to investigate.

Obviously, nothing will prevent unspecific comments, but perhaps providing specific cases of undesirable comments would let us figure some reasonable alternative.

I won't speculate on what kind of problems presumably triggered that response, but it seems @josephperrott  should have a clue.

**Comment by Airblader** [comment] 2021-09-30 05:33
> The first is purely terminological. The bot’s message is nonsensical, referring to "issue locking", "issue filing", and "conversation locking".

None of those seem nonsensical to me. Can you elaborate what issue you see with those phrases?

> [...] perhaps providing specific cases of undesirable comments would let us figure some reasonable alternative.

Long-standing issues like to accumulate comments like "bump", "are there any news on this", "I'm experiencing this too", etc. A new issue requires users to go through the issue template again, providing all environment information and reproduction instructions.

**Comment by petebacondarwin** [comment] 2021-09-30 08:21
@Chealer - the original issue you link to was closed on purpose, not by accident. In the comment where it was closed @AndrewKushnir links to the reason. Once an issue is closed it is deemed no longer relevant; so after a short period of time, where people can comment and try to get it re-opened if it was indeed closed in error, the issue is locked to prevent unwanted noise being added to long closed issues.

If you feel that the issue was closed in error, then either you should have commented within the timeframe before the issue was locked, or simply create a new issue that adds more information and links to the original issue. It seems that you have tried to do the latter here but you have not provided the additional information to explain why closing the issue was incorrect.

The process is working as designed, so I am going to close this issue as "working as expected". If you would like to discuss the original issue, and believe that it was indeed closed incorrectly, then please create an issue with the further information, and we can happily look into it.

**Closed by petebacondarwin** 2021-09-30 08:21 UTC

**Comment by Chealer** [comment] 2021-10-18 22:13
> 
> 
> > The first is purely terminological. The bot’s message is nonsensical, referring to "issue locking", "issue filing", and "conversation locking".
> 
> None of those seem nonsensical to me. Can you elaborate what issue you see with those phrases?

Well, an issue can obviously neither be "locked" or "filed". It can be "reported". And then, the ticket (or issue **report**) can be locked.

As for "conversation locking", the problem is simply the term "conversation". A ticket's message stream may or not contain conversations (this one, for example, does).
 
> > [...] perhaps providing specific cases of undesirable comments would let us figure some reasonable alternative.
> 
> Long-standing issues like to accumulate comments like "bump", "are there any news on this", "I'm experiencing this too", etc. A new issue requires users to go through the issue template again, providing all environment information and reproduction instructions.

I agree that could be an advantage of the current situation in the sense that it could provide more new information. Unfortunately, it also loses all of the "old" information in the original report, so the net result would be a loss.

**Comment by Chealer** [comment] 2021-10-18 22:27
> 
> 
> @Chealer - the original issue you link to was closed on purpose, not by accident. In the comment where it was closed @AndrewKushnir links to the reason. Once an issue is closed it is deemed no longer relevant; so after a short period of time, where people can comment and try to get it re-opened if it was indeed closed in error, the issue is locked to prevent unwanted noise being added to long closed issues.

Thanks @petebacondarwin , I do hope the bot does have a purpose. The question is _what is that purpose?_ Can the bot's author or someone else describe the situations the bot supposedly helps preventing, or providing specific examples of such "unwanted noise"?
Can the bot's purpose be achieved without sacrificing development efficiency?
 

> If you feel that the issue was closed in error, then either you should have commented within the timeframe before the issue was locked, or simply create a new issue that adds more information and links to the original issue.

I certainly "feel" that the issue was closed in error, but I am sorry; my job is not to fix Angular. I can't commit to any level of involvement, and I certainly can't commit to notice **and react** to every problem within 30 days. There is also a limit to the energy I can allocate to this project. I probably don't have to tell how often tickets are closed in error. I can't afford to start a new ticket from scratch every time that happens, and I'm afraid a large part of us are in the same situation.

Just as importantly, leaving tickets with misleading information is most confusing for those who read them without being aware that they are outdated.

> It seems that you have tried to do the latter here but you have not provided the additional information to explain why closing the issue was incorrect.

This ticket reports the meta-issue of excessive "ticket locking", which I'm afraid affects numerous tickets, not just the example provided.
 

> The process is working as designed, so I am going to close this issue as "working as expected".

Thank you for reopening this ticket. A ticket is closed when the issue it reports is solved, not just because the problem is expected/known.
