### ISSUE TITLE
i18n: `equiv-text` value is not trimmed

### ISSUE THREAD

**Issue by kamilchlebek** [angular/angular#41176] opened 2021-03-11 11:24 UTC
# 🐞 bug report

### Affected Package

The issue is caused by package @angular/localize

### Is this a regression?

Yes, the previous version in which this bug was not present was: v10

#### Plurals. Unnecessary line break is added before closing `"` in `equiv-text` attribute

Given template:
```
<a i18n>
  {{ 1 }} {1, plural, =1 {one} other {more}}
</a>
```

✅  Angular 10:
```
<source>
  <x id="INTERPOLATION" equiv-text="{{ 1 }}"/> <x id="ICU" equiv-text="{1, plural, =1 {...} other {...}}"/>
</source>
```

:x: Angular 11:
```
<source> <x id="INTERPOLATION" equiv-text="{{ 1 }}"/> <x id="ICU" equiv-text="{1, plural, =1 {one} other {more}}
"/>
</source>
```

#### ng-bootstrap translations

I couldn't reproduce it with my own example, so I'll demonstrate it using ng-bootstrap.

✅  Angular 10:
```
<source>
          Slide <x id="INTERPOLATION" equiv-text="{{i + 1}}"/> of <x id="INTERPOLATION_1" equiv-text="{{c}}"/>
        </source>
```

:x: Angular 11:
```
<source> Slide <x id="INTERPOLATION" equiv-text="private _pauseO"/> of <x id="INTERPOLATION_1" equiv-text="Subject(false);"/> </source>
```

## 🔬 Minimal Reproduction

https://github.com/kamilchlebek/equiv-text-angular11/tree/demo/angular-11.2.5

Compare v10 messages: https://github.com/kamilchlebek/equiv-text-angular11/blob/demo/angular-11.2.5/messages.v10.xlf
with v11 messages: https://github.com/kamilchlebek/equiv-text-angular11/blob/demo/angular-11.2.5/messages.xlf

## 🌍  Your Environment

**Angular Version:**
<pre><code>Angular CLI: 11.2.4
Node: 12.16.1
OS: darwin x64

Angular: 11.2.5
... animations, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.4
@angular-devkit/build-angular   0.1102.4
@angular-devkit/core            11.2.4
@angular-devkit/schematics      11.2.4
@angular/cli                    11.2.4
@schematics/angular             11.2.4
@schematics/update              0.1102.4
rxjs                            6.6.3
typescript                      4.0.5
</code></pre>

**Comment by petebacondarwin** [comment] 2021-03-11 11:37
This is actually two different issues. Neither of these will affect the actual processing of translations by Angular. The `equivText` properties are only informative to be used by a human when translating the message.

The first issue is that the equivText is no longer trimmed of whitespace. I agree that we can fix this.

The second is that with the the current state of post-processing libraries using `ngcc`, there is no way to accurately compute what the original source of the message was, which is what I believe is happening in your ng-bootstrap example. This is a duplicate of https://github.com/angular/angular/issues/40689.

Let's focus this issue on the trimming of these values. I will update the title of the issue accordingly.

**Comment by kamilchlebek** [comment] 2021-03-11 11:48
Thank you for super quick response!

For me correct and deterministic `equiv-text` make it easier to spot issues by looking at the diff. Migrating from v10 to v11 is quite tough because of that. 

Good luck with #40689

**Closed** 2021-03-11 18:31 UTC
Labels: P3, comp: i18n, state: has PR
