### ISSUE TITLE
Broken npm/bower packages

### ISSUE THREAD

**Issue by josip** [angular/angular#443] opened 2015-01-17 08:39 UTC
`index.js` file in all of `bower-angular-*` repositories has a syntax error:

```javascript
require('./angular-sanitize');

module.exports = angular-sanitize;
```
[(link)](https://github.com/angular/bower-angular-sanitize/blob/master/index.js)

Which makes it a bit more complicated to use them with browserify. I couldn't find the script that's used to generate those repos, but the fix would be as simple as rewriting the file to:

```javascript
module.exports = require('./angular-sanitize');
```

Another option would be to add `"main":"angular-sanitize.js"` to `package.json` [(spec)](https://docs.npmjs.com/files/package.json#main) and not have an `index.js` file at all (as it's already done in `bower.json`).

**Comment by pkozlowski-opensource** [comment] 2015-01-17 08:40
This is wrong repo and duplicate of https://github.com/angular/angular.js/issues/10785

**Closed by pkozlowski-opensource** 2015-01-17 08:40 UTC
