### ISSUE TITLE
View not reflecting properly when modal changes.

### ISSUE THREAD

**Issue by sarwan1096** [angular/angular#33301] opened 2019-10-21 19:42 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/core

### Is this a regression?

 Yes.

### Description

 I am changing value of Wk22 from "yes" to "sarwan" and after clicking update button "sarwan" is showing in WK30 which is not correct. It should be "yes".

## 🔬 Minimal Reproduction

 https://stackblitz.com/fork/angular-issue-repro2-xmckmw

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 8.3.12
Node: 10.16.0
OS: win32 x64
Angular: 8.2.11
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router, upgrade

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.0
@angular-devkit/build-angular     0.800.0
@angular-devkit/build-optimizer   0.800.0
@angular-devkit/build-webpack     0.800.0
@angular-devkit/core              8.0.0
@angular-devkit/schematics        8.3.12
@angular/cli                      8.3.12
@ngtools/webpack                  8.0.0
@schematics/angular               8.3.12
@schematics/update                0.803.12
rxjs                              6.5.3
typescript                        3.4.4
webpack                           4.30.0

</code></pre>

**Anything else relevant?**

**Comment by ashishpatelcs** [comment] 2019-10-21 20:17
I don't find anything wrong with it.

**Comment by sarwan1096** [comment] 2019-10-22 05:59
Hi Ashish,
Actually I have narrowed down the problem to a single string array.  The
problem is I am printing values from array weeksValueDoubleArray. Its
printing correctly and then
I edit the array like say from "yes" to "sarwan". Now when I click update
button it populates new values into the array, however I get "sarwan
" displayed in html page which I dont expect.

Here is the html code:
======================================================================
<div class="table-responsive mb-4 mt-4">
  <button (click)="update()">update</button>

  <table class="table table-bordered custom-table" id="mytable">
    <tr id="headerRow">
      <ng-container *ngFor="let wk of arrayOfWeeks;let i=index">
        <th id="arrayWks{{i}}">{{wk}}</th>
      </ng-container>
    </tr>

      <tr>
        <ng-container *ngFor=
"let weekValue of weeksValueDoubleArray;let i=index">
          <td>
            <input type="text" value={{weeksValueDoubleArray[i]}}>
          </td>

        </ng-container>
      </tr>
  </table>
</div>
==================================================================================
and my ts code is below:

===========================================================================
import { Component, OnInit, ViewChild, ElementRef, OnChanges,DoCheck,
  SimpleChanges } from '@angular/core';

@Component({
  selector: 'app-test',
  templateUrl: './test.component.html',
  styleUrls: ['./test.component.css']
})
export class TestComponent implements OnInit,OnChanges,DoCheck {
  public currentSamples: string[];
  public arrayOfWeeks: string[];
  public weeksValueDoubleArray: string[];
  public weeksValue: string[];
  constructor() { }

  ngOnInit() {
    this.currentSamples = new Array();
    this.currentSamples.push("0");
    this.populateWeeksValue();
    this.arrayOfWeeks = new Array();
    for (var i = 1; i <= 54; i++) {
      if (i < 10) {
        this.arrayOfWeeks.push("WW0" + String(i));
      }
      else {
        this.arrayOfWeeks.push("WW" + String(i));
      }
    }
  }

  update() {
    this.weeksValueDoubleArray = new Array();
    for (let ind = 0; ind < this.currentSamples.length; ind++) {
      this.weeksValue = new Array();
      for (var i = 1; i < 54; i++) {
        let value = "";
        if (i > 31 && i < 40) {
          value = "yes";
        }
        this.weeksValue.push(value);
      }
      this.weeksValueDoubleArray = Object.assign([],this.weeksValue);
    }
  }
  populateWeeksValue() {
    this.weeksValueDoubleArray = new Array();
    for (let ind = 0; ind < this.currentSamples.length; ind++) {
      this.weeksValue = new Array();
      for (var i = 1; i < 54; i++) {
        let value = "";
        if (i > 21 && i < 30) {
          value = "yes";
        }
        this.weeksValue.push(value);
      }
      this.weeksValueDoubleArray= Object.assign([],this.weeksValue);
    }
  }
}
=============================================================================


Request you to look into the issue again. For me it seems really an angular
problem.

Regards,
Sarwan Kumar.

**Comment by IgorMinar** [comment] 2019-11-08 20:24
This is a duplicate of https://github.com/angular/angular/issues/33393

**Closed by IgorMinar** 2019-11-08 20:24 UTC
Labels: comp: core, freq2: medium, severity5: regression, type: bug/fix
