### ISSUE TITLE
Wildcard/dynamic routed component is not rendered when navigating from/to itself

### ISSUE THREAD

**Issue by stanislavromanov** [angular/angular#44742] opened 2022-01-18 13:20 UTC
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

Components with dynamic routes do not render but only when navigated from dynamic component itself.

Consider this scenario:

Application with some static routes like `/user`, `/dashboard` and so on. Application also has dynamic routes that come via JSON CMS. The CMS pages work like this:

- Navigate to any route e.g. `/foo-bar`
- Get content from CMS based on this URL
- Render the content if it exists
- Show 404 page if it does not exist

With version 11 it was working fine, however starting with version 12 navigating from these dynamic urls to different dynamic urls does not work. (Actually navigation happens, you can even see it when you set `enableTracing: true`, **the component is not displayed**)

When you click on any static route e.g. `/user` it works fine, if you are on any static route first navigation to any dynamic page will work fine as well.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-idy2ak?file=src%2Fapp%2Fapp.module.ts

### Please provide the exception or error you saw

```true
There is no error, however as you can see the component content is not rendered. Also you can see a very slight lag for URL to change (so something weird definitely is happening)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.1.3
Node: 16.13.2
Package Manager: npm 8.1.2
OS: darwin arm64

Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1301.3 (cli-only)
@angular-devkit/core         13.1.3 (cli-only)
@angular-devkit/schematics   13.1.3 (cli-only)
@schematics/angular          13.1.3 (cli-only)
```

**Comment by atscott** [comment] 2022-01-18 17:32
Hi @stanislavromanov, I'm a bit confused by the reproduction here for a couple reasons:

* I tried a few different versions and also enabling/disabling Ivy and the behavior is the same in all cases from v10 to v13. 
* The behavior is actually correct. Since the component doesn't change between the routes, it should not be destroyed and recreated. You're only updating the `this.currentUrl` value in the `ngOnInit` rather than subscribing to the `url` observable and updating the template value when it changes. This means it only gets the initial value from the first navigation.

I'm going to close this as working as intended based on the reproduction provided. Please do open a new issue and I'll look at that as well if you're able to come up with a new reproduction that demonstrates broken behavior.

**Closed by atscott** 2022-01-18 17:32 UTC
Labels: comp: router
