### ISSUE TITLE
Service worker performance strategy makes network request to ngsw.json for dataGroups

### ISSUE THREAD

**Issue by Exocomp** [angular/angular#31480] opened 2019-07-10 00:29 UTC
### Description

Angular Service Worker configured with dataGroups cacheConfig performance strategy makes a network call to ngsw.json after serving the resource.

Steps to reproduce:

1) Configure ngsw-config.json with the following settings:

```
"dataGroups": [
	{
		"name": "photos",
		"urls": [
			"/photo/**"
		],
		"cacheConfig": {
			"strategy": "performance",
			"maxSize": 1000,
			"maxAge": "7d"
		}
	}
]
```

2) Browse to your Angular page that has a image to http://hostname/photo/unqiue_photo.png
3) The service worker should cache page and the photo
4) Open another tab and copy and paste directly to http://hostname/photo/unqiue_photo.png
5) The browser shows that the image was retrieved from service worker, however, a couple seconds later service worker makes a network call to "/ngsw.json?ngsw-cache-bust=0.5564537918108132"

**Expectation**: Since the request is part of the "dataGroups" it will not be in ngsw.json so I don't see a point to make a call to "ngsw.json".  Also note that the strategy is "performance".  So my expectation was no network call would be made.  Documentation states that no network call will be made for strategy "performance" until expiration time specified by maxAge.

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.1.0
Node: 10.13.0
OS: win32 x64
Angular: 8.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker

Package                                    Version
--------------------------------------------------------------------
@angular-devkit/architect                  0.801.0
@angular-devkit/build-angular              0.801.0
@angular-devkit/build-optimizer            0.801.0
@angular-devkit/build-webpack              0.801.0
@angular-devkit/core                       8.1.0
@angular-devkit/schematics                 8.1.0
@angular/cdk                               8.0.2
@angular/http                              7.2.15
@angular/material                          8.0.2
@angular/pwa                               0.801.0
@ngtools/webpack                           8.1.0
@nguniversal/module-map-ngfactory-loader   7.1.1
@schematics/angular                        8.1.0
@schematics/update                         0.801.0
rxjs                                       6.5.2
typescript                                 3.4.5
webpack                                    4.35.2
</code></pre>

**Comment by gkalpak** [comment] 2019-07-10 11:34
The request you are seeing is unrelated to serving the image. Since you go to a new page, you make a so called "navigation request". The SW is configured to automatically check for updates after instantiation and on every navigation request. Fetching `ngsw.json` is how it checkes for available updates (it checkks to see if `ngsw.json` is different that the last time it fetched it).

Closing, since everything works as intended afaict.

**Closed by gkalpak** 2019-07-10 11:34 UTC

**Comment by Exocomp** [comment] 2019-07-10 17:35
@gkalpak 

Please reopen this.
There logic a problem to what you just stated.

> The SW is configured to automatically check for updates after instantiation and on every navigation request. Fetching ngsw.json is how it checkes for available updates (it checkks to see if ngsw.json is different that the last time it fetched it).

Please answer this question.  How does that make sense in case of dataGroups?  dataGroups are not exposed in ngsw.json so making a call to it is a complete waste of resources and bandwidth.  What do you gain from making a call to ngsw.json if the resource being requested is not exposed in ngsw.json?

Please provide a logical answer.

**Comment by gkalpak** [comment] 2019-07-10 19:26
@Exocomp, sorry, I wasn't clear enough apparently. The SW does not check for updates for the requested resources. The SW versions all assets of an app together. Each different `ngsw.json` consistutes a different "app version".

So, the SW has to check for an updated `ngsw.json` every now and then. When it sees a new `ngsw.json` (i.e. different content), it signifies there is a new app version available, in which case it fetches the necessary assets, updates the caches, notifies existing clients about the available update and starts serving new clients with this new version.

The checks for new versions happens (among other cases) on navigation requests (i.e. when you navigate to a page). This would happen regardless of fetching the dataGroup-matched asset. It would happen anyway (as long as the oage you navigated to is controlled by the SW).

For example, if you have an SPA and your landing page does not contain the http://hostname/photo/unqiue_photo.png image, the check for updates will still happen. If you then load a template that contains the http://hostname/photo/unqiue_photo.png image (via client-side routing for example, not a direct navigation), the SW will handle the request for the image, but will not check for an update (i.e. will not request `ngsw.json`).

I hope this clears it up. Let me know, if anything is still unclear ☮️

**Comment by Exocomp** [comment] 2019-07-11 18:35
@gkalpak 

Please take a moment and understand what I'm trying to get across.

What you stated is how Angular Service Worker is implemented (which I already understand) and doesn't address the issue I'm pointing out.

This needs to be considered as a bug (which seems like an oversight) or a feature request however you want to handle it.

I'll explain it again. Consider these steps:

1) Setup an Angular app (for example image gallary) with Angular Service Worker and make image paths part of the dataGroups in ngsw-config.json with cacheConfig strategy performance (maxAge something large like 100 days)
2) Browse to a site to give Angular Service Worker a chance to cache all the images
3) Close the site
4) Setup a page with a direct link to the image, open a new browser instance and go to the new page click on the link to the image or just copy and page the image url
5) Angular Service Worker makes a network call to ngsw.json

**NOTE**: Since the image was part of dataGroups it is NOT in ngsw.json. So to making call to ngsw.json is a complete waste of resources and bandwidth.

Consider this, say "ngsw.json" is 20kb (compressed). Even a tiny resource like 1 byte triggers another 20kb to be downloaded. 

Please explain how that logic makes sense?

Wouldn't it be better to conditionally make the call to "ngsw.json"? It would be much more efficient use of resources/bandwidth.

**Comment by gkalpak** [comment] 2019-07-11 19:29
I am afraid I don't know how to better explain this 😞

What you describe on step 4 is a navigation request (see [Request.mode: navigate][1]): The browser "navigates" to a URL, which involves requesting a document from the server (or the service worker for that matter). The fact that the URL maps to a document that is an image and not an HTML document is irrelevant.

By design, on every navigation request, a "check for app updates" is scheduled (for when the SW is idle). I understand that (for some specific usecase) checks might be too often, but for the vast majority of usecases (involving a SW) the overhead will be minimal (very few navigation requests compared to other types of requests and very small payload of `ngsw.json` compared to other fetched resources/data).

##
Every design desicion will inevitably leave someone unsatisfied and there is only so much you can do (especially since the Angular SW is intentionally opinionated and unflexible for the time being) 🤷‍♂

Feel free to open a feature request for either reducing the frequency of update checks (e.g. not check if last check was less than X amount of time ago) or disabling the automatic update checks (although I would not be keen on introducing this option :grin:).

[1]: https://developer.mozilla.org/en-US/docs/Web/API/Request/mode

**Comment by Exocomp** [comment] 2019-07-26 22:50
@gkalpak 

You keep on explaining but as I've explained I already understand the current functionality, see my previous responses. Please consider this my request to open this and turn it into a feature request it already has all the details necessary.

The feature request is simple in concept:

* Have an option to turn off a network request to "ngsw.json" file for certain sections (my use case applies only to the section dataGroups)
* Have an option to delay the network request to "ngsw.json" file for certain sections (my use case applies only to the section dataGroups)

If you understand my feature request and the reasoning why I've requested it and still choose not to do it then so be it.
