### ISSUE TITLE
zone.js update 0.13.1 regression with Jest mock `Cannot redefine property`

### ISSUE THREAD

**Issue by JohnnyDevNull** [angular/angular#50756] opened 2023-06-19 06:11 UTC
### Which @angular/* package(s) are the source of the bug?

zone.js

### Is this a regression?

Yes

### Description

Before Update to 0.13.1 all Unit-Tests where green in zone.js 0.13.0. After Update to 0.13.1 some Unit-Tests are failing with errors, which  seems not belonging to zone.js, but the changelog let's assuming that patching the node Promise API causes the error.

The problem is the mocking logic from jest, which can't `spyOn` some ways now:

e.g.

```
import * as utils from '@redngapps/shared/util';

...

jest.spyOn(utils, 'sanitizeHtml').mockImplementation(value => value);
```
is failing now, errors see below.

```
import * as arrayBufferUtils from '@redngapps/shared/util';

...

jest.spyOn(arrayBufferUtils, 'generateRandomHexString').mockReturnValue('mock-state');
```
is failing now, errors see below.

and all other kind of `spyOn` defined the mentioned way above are failing now

### Please provide the exception or error you saw

```true
TypeError: Cannot redefine property: sanitizeHtml
TypeError: Cannot redefine property: generateRandomHexString
TypeError: Cannot redefine property: fetchEntity
TypeError: Cannot redefine property: generateRandomUint8Array
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Nx Version:
- Local: v15.9.4
```

```
    "@angular/animations": "15.2.9",
    "@angular/cdk": "15.2.9",
    "@angular/common": "15.2.9",
    "@angular/compiler": "15.2.9",
    "@angular/core": "15.2.9",
    "@angular/forms": "15.2.9",
    "@angular/localize": "15.2.9",
    "@angular/material": "15.2.9",
    "@angular/platform-browser": "15.2.9",
    "@angular/platform-browser-dynamic": "15.2.9",
    "@angular/router": "15.2.9",
    "zone.js": "0.13.1"


    "@angular-devkit/architect": "0.1502.8",
    "@angular-devkit/build-angular": "15.2.8",
    "@angular-devkit/core": "15.2.8",
    "@angular-devkit/schematics": "15.2.8",
    "@angular-eslint/eslint-plugin": "15.2.1",
    "@angular-eslint/eslint-plugin-template": "15.2.1",
    "@angular-eslint/template-parser": "15.2.1",
    "@angular/cli": "15.2.8",
    "@angular/compiler-cli": "15.2.9",
    "@angular/language-service": "15.2.9",
```

**Comment by alan-agius4** [comment] 2023-06-19 08:12
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by JohnnyDevNull** [comment] 2023-06-19 12:45
@alan-agius4 here is my minimal reproduction:

https://github.com/JohnnyDevNull/zonejs_bug_50756/tree/main

What i can ay is:
* default ng new in version 15 + zone.js 0.13.1 works
* default nx new in version 15 + zone.js 0.13.1 fails

I think it has something to do with some extended jest angular configurations.

You can run the tests in the example repo with: `nx test feature`
You can also drop the zone.js update commit and re-install, then they will run through without error

**Comment by JohnnyDevNull** [comment] 2023-06-19 13:43
@alan-agius4 Update: i got it also to fail with default ng now:

https://github.com/JohnnyDevNull/zonejs_bug_50756_2

just run `ng test`
I've used the `@angular-builders/jest` here

![Bildschirmfoto 2023-06-19 um 15 43 14](https://github.com/angular/angular/assets/5759334/f4bc2021-fd13-4c42-bbd3-b84e3d389655)

**Comment by alan-agius4** [comment] 2023-06-23 08:31
Hi @JohnnyDevNull, as suspected this is not caused by Zone.js infact the same thing can be observed when using earlier version of zone.js.

The problem you are seeing is caused because Jest spyOns do not work with ESM. There is a good explanation here: https://stackoverflow.com/questions/67872622/jest-spyon-not-working-on-index-file-cannot-redefine-property/69951703#69951703

Closing as this problem is not caused by Angular.

**Comment by JohnnyDevNull** [comment] 2023-06-23 08:52
Ok, but why is this working with zone.js 0.13.0 und fails with zone.js 0.13.1 ?

**Comment by alan-agius4** [comment] 2023-06-23 10:12
Actually I got confused as in both cases the test fail with different errors. 

I looked into this a bit more and it seems to have been caused by https://github.com/angular/angular/pull/49327

**Comment by zargham-leanix** [comment] 2023-06-24 22:47
Hi, facing the same issue. This is blocking us for Angular 16 upgrade.

```TypeError: Cannot redefine property: ***
        at Function.defineProperty (<anonymous>)
        ```
        Going back to zone.js 0.12.0 resolves the issue.

**Comment by JiaLiPassion** [comment] 2023-06-30 00:16
@alan-agius4 @JohnnyDevNull 
In fact, this is not a regression, the current `zone.js 0.13.1` behavior is `correct`.

The `jest.spyOn(utils, 'add')` is trying to spy on a `exported` function https://github.com/JohnnyDevNull/zonejs_bug_50756/blob/main/libs/shared/util/src/lib/add.func.ts.

And the Property Descriptor of `utils.add` is 

```
{
        get: [Function: get],
        set: undefined,
        enumerable: true,
        configurable: false
      }
```

which is not configurable, in the previous version of `zone.js 0.13.0`, zone.js try to make such kind of property descriptor configurable.

I am not sure whether we should bring back the previous behavior. Or maybe we could add such kind of behavior into the zone.js jest patch.

**Comment by alan-agius4** [comment] 2023-06-30 04:48
@JiaLiPassion, that make sense.

Indeed you are right as even without zone.js, the `spyOn` will not work.

Overall, I think in this case, the error and nee behaviour is correct as it aligns with the native ECMA behaviour.

**Comment by zargham-leanix** [comment] 2023-06-30 09:01
I am not able to understand root cause of the issue, what has changed on Jest side ? @alan-agius4  @JiaLiPassion

**Comment by zargham-leanix** [comment] 2023-07-01 22:53
@JiaLiPassion  as zone.js did make descriptors configurable, lots of tests in our project are using this to spy on modules. I am scared that this will result in a lot of work for us to migrate to angular 16/ jest v29 in a nx workspace. I wonder if there is any other way to make tests still pass without fixing the mocks.

**Comment by JiaLiPassion** [comment] 2023-07-01 23:38
@zargham-leanix 
Here is the walk around.

1. add a `setup.js` under the project root.
```
require("zone.js/plugins/zone-legacy");
require("jest-preset-angular/setup-jest");
```

2. In `angular.json`. update the `"test"` options

```
 "test": {
          "builder": "@angular-builders/jest:run",
          "options": {
            "setupFilesAfterEnv": "./setup.js"
          }
        }
```

**Comment by alan-agius4** [comment] 2023-07-02 17:56
Closing as per above.

**Closed by alan-agius4** 2023-07-02 17:56 UTC
Labels: area: zones

**Comment by NsdHSO** [comment] 2023-07-31 01:35
for nx workspace, you must to update the `jest.config.ts` 
```
...
  setupFilesAfterEnv: ['./setup.js'],
...
 ```
