### ISSUE TITLE
elements schema: detect dangling attributes

### ISSUE THREAD

**Issue by pkozlowski-opensource** [angular/angular#3425] opened 2015-07-31 12:02 UTC
In the ideal world we should be able to detect "dangling" attributes. In the `<div foo>` example we should report `foo` as "dangling" when:
- foo is not a valid HTML attribute (how come should we identify valid attributes? From a spec / schema?)
- there is no matching directive
- it wasn’t consumed by a binding / event handler / var declaration / other ng-specific construct
- it is not prefixed with `data-` (?)

In practice "dangling" attributes in templates are most probably attributes are introduced due to:
- typos
- forgetting to add a directive (in the `directives` for the `@View` annotation) that should match a given attribute

**Comment by pkozlowski-opensource** [comment] 2015-08-11 14:22
Grr, detection of dangling attributes would really help to catch cases of using directives in a template without listing a given directive in `@View`. Maybe as a first step we could throw for all attributes that:
* have `-` in their names
* are not on elements with names containing `-`
* are not `data-` (and / or `x-`?) prefixed

While not perfect it should be able to catch some common errors.

**Comment by mhevery** [comment] 2015-08-21 00:19
@pkozlowski-opensource what is stoping up from implementing this? I thought we had something already work.ng

**Comment by pkozlowski-opensource** [comment] 2015-08-21 14:19
@mhevery nothing particular stops us, apart that it needs work. Here are the items to take care of:
* [ ] - need to have a way of knowing which attributes were "consumed" by a directive (selector + "static" property bindings)
* [ ] - need to have a way of knowing what are legitimate attributes on both regular HTML elements (we can hand-code this in schema from HTML specs) and web components (this will require hand-written schema by devs)

So, it is definitively doable but require some work - we can put it in one of the releases, depending on other priorities.

**Comment by mhevery** [comment] 2016-07-01 17:50
implemented

**Comment by pkozlowski-opensource** [comment] 2016-07-01 18:42
I believe that this is still an issue. If I have an attribute `fooo` but meant to kick-off directive `foo` it will fail silently.

**Comment by pkozlowski-opensource** [comment] 2016-09-30 17:41
Re-opening as this is not implemented, see #12016 as an example.

**Comment by tiagoroldao** [comment] 2016-09-30 17:48
As mentioned, `<element attr.my-attr="my-val"/>` should be explicitly disallowed, in favour of  `<element [attr.my-attr]=" 'my-val' "/>`

**Comment by splincode** [comment] 2018-07-25 16:53
@pkozlowski-opensource Is the issue relevant?

**Comment by jelbourn** [comment] 2018-08-27 17:02
Per #25005, this should now track, at least, that doing something like
```ts
host: {
  'attr.aria-label': 'Hello'
}
```

Should throw an error (missing `[ ]`)

**Comment by crisbeto** [comment] 2021-09-03 15:37
We talked about this during the feature triage and we decided to close it, because there are valid cases where you can have attributes that Angular doesn't know about. E.g. using an attribute for CSS styling.

**Closed by crisbeto** 2021-09-03 15:37 UTC
Labels: feature, comp: compiler, core: basic template syntax, core: directive matching, compiler: template type-checking

**Comment by th0r** [comment] 2021-09-03 16:27
But why Angular compiler can't detect component inputs like `title` and don't set HTML attribute/prop in this case?

**Comment by petebacondarwin** [comment] 2021-09-03 16:40
This is part of the sticking point:

 - need to have a way of knowing what are legitimate attributes on both regular HTML elements (we can hand-code this in schema from HTML specs) and web components (this will require hand-written schema by devs)

The problem is that we would need a way to tell Angular what attributes we don't mind appearing. People do use "unknown" attributes in custom elements but also with 3rd party libraries that are working outside Angular.

The additional cost of providing an API to specify this compared to the benefit that compiler errors provide is not high. Especially considering how few comments and votes this issue has received.


Regarding your point @th0r - we cannot remove `title` attribute since it might be used for CSS styling etc.

**Comment by th0r** [comment] 2021-09-04 07:23
I don't suggest to remove any attribute, I suggest to fix the most common case when component's input has the same name as some already existing html attribute and not set this attribute in this case. It can be easily done as I believe Angular compiler has all necessary information for this. If one really needs to set this html attribute, he can always do it via `[attr.]`.

**Comment by th0r** [comment] 2021-09-04 07:28
My concern is that more new arrtibutes may appear in  html in the future which potentially may overlap with input names on your already existing components and it may break their behavior.

**Comment by petebacondarwin** [comment] 2021-09-04 10:23
> I don't suggest to remove any attribute, I suggest to fix the most common case when component's input has the same name as some already existing html attribute and not set this attribute in this case. It can be easily done as I believe Angular compiler has all necessary information for this. If one really needs to set this html attribute, he can always do it via `[attr.]`.

So you are saying that if there is

```html
<my-component title="static text">...</my-component>
```

Then the rendered HTML should not contain the `title` attribute? Is this not equivalent to removing that attribute?

In any case I think that this use case is probably not the same as detecting dangling attributes as outlined in this issue, so perhaps it should be discussed separately?

**Comment by splincode** [comment] 2021-09-04 11:10
@petebacondarwin https://github.com/angular-eslint/angular-eslint/issues/320

I think prefer for correct behaviour restrict input when name conflicted with native attribute. 

What do you think about check it when running AOT (if we don't have eslint)?

**Comment by th0r** [comment] 2021-09-04 11:14
Frankly speaking, I don't understand why Angular sets attributes for co-named inputs on component's host element at all. IMO it's very confusing and strange as most of them simply become `[object Object]`. 

> In any case I think that this use case is probably not the same as detecting dangling attributes as outlined in this issue, so perhaps it should be discussed separately?

I posted it here because if [this comment](https://github.com/angular/angular/issues/24376#issuecomment-397149927) - it says that issue with `title` is blocked by this one which has been closed.

**Comment by petebacondarwin** [comment] 2021-09-04 12:19
I think that comment @th0r is not correct. That issue is not dependent upon this one.
I don't think it is wise for the Angular compiler to error here. There are many cases where you actually do want to have the attribute appear; moreover, if you do not want an attribute to appear then you simply use a square bracket binding to a string instead.
Rather I think the right approach to support developers it to vote for the [issue on angular-eslint](https://github.com/angular-eslint/angular-eslint/issues/320) as mentioned by @splincode.

**Comment by th0r** [comment] 2021-09-04 12:39
@petebacondarwin could you provide a few examples when you need an attribute for corresponding input to be set on host component?

**Comment by petebacondarwin** [comment] 2021-09-04 13:01
I'm. not quite sure what you are asking for @th0r - but the Angular Material library has possible examples: the `MatInput` directive has a `placeholder` input, which can be set without creating a square bracket binding, https://material.angular.io/components/form-field/overview#floating-label.

**Comment by th0r** [comment] 2021-09-05 08:59
OK, thanks. For such cases we could have an extra decorator for the inputs e.g. `@Attr` which would tell Angular to also set corresponding attribute to the host element.

**Comment by petebacondarwin** [comment] 2021-09-08 17:21
Thanks for the additional viewpoint @th0r - This checking can be achieved through linting, without creating a breaking change to how the Angular compiler works, so we do not intend to implement this feature.
