### ISSUE TITLE
NgForm's properties are not reflected to the view (at first) with OnPush ChangeDetectionStrategy

### ISSUE THREAD

**Issue by UserGalileo** [angular/angular#44115] opened 2021-11-08 14:55 UTC
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

No

### Description

If a Template-driven Form is used in a component which uses `ChangeDetectionStrategy.OnPush`, and we grab the `NgForm` Directive from the `<form>` element, its properties are not immediately reflected to the view. They need another Change Detection cycle to become correct.

Eg.

```html
<form #f="ngForm">
  <input type="text" ngModel name="foo" required>
  {{ f.invalid }} <!-- false, should be true -->
  {{ f.valid }} <!-- true, should be false-->
  {{ f.status }} <!-- VALID, should be INVALID -->
  {{ f.value }} <!-- empty object, should contain "foo" -->
</form>
```

This does not happen with a single control, grabbing the `NgModel` Directive:

```html
<input type="text" ngModel name="foo" required #foo="ngModel">
{{ foo.invalid }} <!-- true -->
{{ foo.valid }} <!-- false -->
{{ foo.status }} <!-- INVALID -->
```

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-gefrhy?file=src%2Fapp%2Fhello.component.ts

### Please provide the environment you discovered this bug in

```true
Angular CLI: 12
Angular: 12.2.5
```

**Comment by AndrewKushnir** [comment] 2021-11-10 22:43
Thanks for reporting the problem. It looks like a duplicate of #10816.

**Closed by AndrewKushnir** 2021-11-10 22:43 UTC
Labels: comp: forms

**Comment by UserGalileo** [comment] 2021-11-11 12:05
@AndrewKushnir Hmmm ok, so this appears to be all `ngModel`'s fault?

Interesting thing, validators also seem to behave differently if the `ngModel` is inside a `<form>`:

```ts
public value = 'test';
```

## Standalone:
```html
<input type="text" [ngModel]="value" #foo="ngModel" required>

{{ foo.value | json }} <!-- Late by 1 cycle, displays "null" -->
{{ foo.errors | json }} <!-- Late by 1 cycle, displays "required: true" -->
```

As noted by the other issue, everything is late by 1 cycle.

## Inside a form:
```html
<form #f="ngForm"> 
  <input type="text" [ngModel]="value" name="bar" #bar="ngModel" required>
</form> 

{{ bar.value | json }}  <!-- Late by 1 cycle, displays "null" -->
{{ bar.errors | json }} <!-- At first, displays "null" -->
```

In this case, errors are not just late by 1 cycle, they're not set initially.
