### ISSUE TITLE
*ngFor re renders elements

### ISSUE THREAD

**Issue by OmerShemesh** [angular/angular#10417] opened 2016-07-31 20:45 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
 I have this ngFor reading data from a Firebase database:

`<div *ngFor="let post of myPosts | async" >`

`myPosts` is of type `FirebaseListObservable`

Each time a new post is being pushed, all of the posts elements are being re rendered.

**Expected/desired behavior**
Only the newly pushed post would render.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4

**Comment by ericmartinezr** [comment] 2016-07-31 21:02
Will be fixed by https://github.com/angular/angular/pull/10287

**Comment by tbosch** [comment] 2016-10-04 19:20
Duplicate of #10287

**Closed by tbosch** 2016-10-04 19:20 UTC
