### ISSUE TITLE
Route resolver should resolve on first value emitted from stream, but it waits for entire stream to complete

### ISSUE THREAD

**Issue by lansana** [angular/angular#28799] opened 2019-02-18 14:24 UTC
# 🐞 bug report

### Affected Package
 @angular/router

### Is this a regression?
No

### Description
Route resolver currently waits until subscription is complete. It should resolve after the first value is emitted.

Assuming I use this `CacheInterceptor`...:

```typescript
export class CacheInterceptor implements HttpInterceptor {
    intercept(req: HttpRequest<any>, next: HttpHandler) {
        if (req.method !== 'GET') {
            return next.handle(req);
        }

        const cachedResponse = cache.get(req);
        const results$ = sendRequest(req, next);
        return cachedResponse ? results$.pipe(startWith(cachedResponse)) : results$;
    }
}

function sendRequest(req: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
    return next.handle(req).pipe(
        tap(event => {
            if (event instanceof HttpResponse) {
                cache.put(req, event);
            }
        })
    );
}

export class HttpCache {
    cache: Map<string, HttpResponse<any>>;

    constructor() {
        this.cache = new Map();
    }

    get(req: HttpRequest<any>): HttpResponse<any> | undefined {
        return this.cache.get(req.urlWithParams);
    }

    put(req: HttpRequest<any>, response: HttpResponse<any>): void {
        this.cache.set(req.urlWithParams, response);
    }
}

const cache: HttpCache = new HttpCache();
```

I can then make HTTP requests using the following `DataService`:

```typescript
@Injectable()
export class DataService {
    constructor(private http: HttpClient) {}

    getData(): Observable<string> {
        return this.http.get<string>(url).pipe(delay(2000));
    }
}
```

As such, if I make 3 HTTP requests from a component, like this...:

```typescript
@Component({...})
export class DataComponent {
    constructor(private dataService: DataService) {}

    ngOnInit() {
        return this.dataService.getData().subscribe(
            (data: string) => console.log(data);
        );
    }
}
```

Then, the following should (and does) occur:

1. The first request will take at least 2 seconds, since there is a delay of 2 seconds in the service method. 
2. The 2nd call will be instant since it comes from the cache. 
3. The 3rd call will also take at least 3 seconds since it is being called again from the service.

Now, if I add a resolver to the route that loads the component, like this...:

```typescript
@Injectable()
export class DataResolver implements Resolve<string> {
    constructor(private dataService: DataService) {}

    resolve(route: ActivatedRouteSnapshot, state: RouterStateSnapshot): Observable<string> {
        return this.dataService.getData();
    }
}
```

Then, in my component I should be able to subscribe to the route data, and experience _**_the same_**_ functionality as in the first example...right?:

```typescript
@Component({...})
export class DataComponent {
    constructor(private route: ActivatedRoute) {}

    ngOnInit() {
        return this.route.data.subscribe(
            (data: any) => console.log(data);
        );
    }
}
```

Nope. This doesn't work the same way as the first example. In the component here, the cached result is not immediately available. No data is streamed to the component until the entire observable stream has completed. So the cache is essentially ignored here, because the resolver waits for the entire observable to complete.

My HTTP interceptor unit tests on the `CacheInterceptor` seem to fail for the same reason as they do in the resolver. Seems the testing HTTP controller waits for the observable to complete as well.

Hope that makes sense. If this is not a bug, please advise on a way to remedy this issue. I need to use a resolver and I need the RxJS `startWith` to work the same way on a resolver as it does for without a resolver. Adding in this functionality shouldn't have an effect on anything else, cause the "first value" also acts as a "completion" in RxJS terms, so for routes that don't emit multiple times this shouldn't break backwards compatibility at all. Let me know and I can create a PR...

Thank you.

## 🌍  Your Environment

**Angular Version:**
 7.2.5

**Comment by ericmartinezr** [comment] 2019-02-18 14:35
https://github.com/angular/angular/issues/10556

**Comment by trotyl** [comment] 2019-03-02 16:27
@lansana Please be aware your use case won't work if resolver only takes the first value, that way the observable would be unsubscribed immediately and your HTTP request would completely lost.

What you want is "resolver should take every emission into account".

**Comment by jasonaden** [comment] 2019-04-09 22:57
Thank you for the detailed issue. I agree, the current way we handle Observables is fundamentally incorrect. We do have plans to eventually fix it.

Because this is a duplicate of #10556, I'm going to close it. It is on the roadmap to get this addressed though.

**Closed by jasonaden** 2019-04-09 22:57 UTC
Labels: comp: router
