### ISSUE TITLE
Ivy library does not render in MatDialog with buildOptimizer

### ISSUE THREAD

**Issue by PapaNappa** [angular/angular#37282] opened 2020-05-25 15:45 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/core (probably).

### Is this a regression?

 Yes, in the sense that this problem did not occur pre-ivy.

### Description

When you create an Angular library and compile it with Ivy (`ng build lib` as opposed to `ng build lib --prod`), dialog components inside the library are not properly rendered.

In my reproduction below, I have created a [lib component](https://github.com/PapaNappa/angular-bug-ivyLib/blob/master/projects/lib/src/lib/my-dialog/my-lib.component.ts) with a simple "works!" template.
This component's selector is `lib-component`.

This component can be shown in a MatDialog by calling its static `openDialog` method.
This method opens a wrapping [dialog component](https://github.com/PapaNappa/angular-bug-ivyLib/blob/master/projects/lib/src/lib/my-dialog/my-dialog.component.ts) that has `<lib-component>` in its template.

When the library is built with Ivy (`ng build lib`), and the buildOptimizer of the consuming app is enabled, no directives of the dialog get executed:
* the `mat-dialog-title` directive of `<h5 mat-dialog-title>` is not applied, i.e. no `class="mat-dialog-title`" is added.
* the `<lib-component>` is not rendered.

![image](https://user-images.githubusercontent.com/705175/82827130-ad775b00-9eae-11ea-97d6-4a83ad2f1295.png)

The expected behaviour is shown here:

![image](https://user-images.githubusercontent.com/705175/82827254-e9aabb80-9eae-11ea-93c7-0b71809903a2.png)

This issue does not occur when the buildOptimizer is disabled, or alternatively the library is built _without_ ivy.

This issue might include other usages of the libraries components, not just when shown in MatDialog. However, this is the case where I experienced this issue and how I can reproduce it.

## 🔬 Minimal Reproduction

https://github.com/PapaNappa/angular-bug-ivyLib

The issue can be observed by running first `npm run build-lib` and then `npm run start:prod`.

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 9.1.7
Node: 12.14.1
OS: win32 x64

Angular: 9.1.9
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.901.7
@angular-devkit/build-angular      0.901.7
@angular-devkit/build-ng-packagr   0.901.7
@angular-devkit/build-optimizer    0.901.7
@angular-devkit/build-webpack      0.901.7
@angular-devkit/core               9.1.7
@angular-devkit/schematics         9.1.7
@angular/cdk                       9.2.4
@angular/cli                       9.1.7
@angular/material                  9.2.4
@ngtools/webpack                   9.1.7
@schematics/angular                9.1.7
@schematics/update                 0.901.7
ng-packagr                         9.1.5
rxjs                               6.5.5
typescript                         3.8.3
webpack                            4.42.0

</code></pre>

**Comment by PapaNappa** [comment] 2020-05-25 15:54
I am aware that shipping libraries with Ivy is not the recommended approach with Angular 9, and thus the case of Ivy-lib with production app is not the intended usage.

There are however valid reasons why this is a relevant bug:
* Afaik, in the future libraries are supposed to ship directly with ivy enabled, making ngcc unnecessary. (Whenever View-Engine-support is no longer needed). Then this bug become very relevant.
* Sometimes you want to start you application locally with build optimizations, but still use a local development-version of your library (you do not want to re-compile the lib just because you configure your app differently).
* When you develop libraries for internal usage _only_ and use Ivy in all of your projects, shipping the library with Ivy improves app compilation as ngcc does not need to run for your internal apps.

**Comment by JoostK** [comment] 2020-05-25 16:08
This has the same cause as #35602, please see https://github.com/angular/angular/issues/35602#issuecomment-591133414 for a workaround.

The `MyDialogComponent` uses `MyLibComponent` which imports `MyDialogComponent`, which would introduce a cycle. The Ivy compiler currently avoids the cycle by creating a side-effectfull `ɵɵsetComponentScope` call near the NgModule which declares `MyDialogComponent`, however this call is removed in an optimized build as the library is not marked to contain side-effects. This approach is being reconsidered to avoid this pitfall.

Closing as duplicate of #35602.

**Closed by JoostK** 2020-05-25 16:08 UTC
