### ISSUE TITLE
uable to install angular kindly help me to slove the problem

### ISSUE THREAD

**Issue by pardhasaradhihulk** [angular/angular#28695] opened 2019-02-13 16:39 UTC
I:\node setup>npm install -g@angular/cli
npm WARN enoent ENOENT: no such file or directory, open 'I:\node setup\package.json'
npm WARN node setup No description
npm WARN node setup No repository field.
npm WARN node setup No README data
npm WARN node setup No license field.

npm ERR! path I:\node setup\node_modules\.staging
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall mkdir
npm ERR! Error: EPERM: operation not permitted, mkdir 'I:\node setup\node_modules\.staging'
npm ERR!  { [Error: EPERM: operation not permitted, mkdir 'I:\node setup\node_modules\.staging']
npm ERR!   cause:
npm ERR!    { Error: EPERM: operation not permitted, mkdir 'I:\node setup\node_modules\.staging'
npm ERR!      errno: -4048,
npm ERR!      code: 'EPERM',
npm ERR!      syscall: 'mkdir',
npm ERR!      path: 'I:\\node setup\\node_modules\\.staging' },
npm ERR!   stack:
npm ERR!    'Error: EPERM: operation not permitted, mkdir \'I:\\node setup\\node_modules\\.staging\'',
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: 'I:\\node setup\\node_modules\\.staging' }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
npm ERR! or that you lack permissions to access it.
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\pardhasaradhi\AppData\Roaming\npm-cache\_logs\2019-02-13T16_33_53_740Z-debug.log

I:\node setup>

**Comment by pkozlowski-opensource** [comment] 2019-02-13 19:25
Here is the root cause of your problem:

> Error: EPERM: operation not permitted, mkdir 'I:\node setup\node_modules.staging']

Sounds like, for whatever reason, the `I:\node setup\node_modules.staging` folder can't be created in your local environment. In any case it is something that you can only resolve on your end so I'm going to close it here as it is not actionable.

**Closed by pkozlowski-opensource** 2019-02-13 19:25 UTC
