### ISSUE TITLE
RxJS does not infer type information from EventEmitter using combineLatest

### ISSUE THREAD

**Issue by andrewseguin** [angular/angular#30436] opened 2019-05-13 18:37 UTC
The `EventEmitter` stream does not provide the right type information to pass through operators like `combineLatest`.

It looks like it is due to `EventEmitter` defining a custom `subscribe` interface.

See reproduction of the issue here: https://stackblitz.com/edit/rxjs-xayikm?file=index.ts

See that the first item in the `results` array is correctly typed as `string`, but the `EventEmitter` stream is incorrectly typed as `{}`

![ftaViYM8Cj8](https://user-images.githubusercontent.com/22898577/57645680-aadfe700-7573-11e9-965c-a3dbd5e7f310.png)

**Comment by Airblader** [comment] 2019-05-13 19:13
Possibly related: #29016

Also in the past the Angular stance has been that EventEmitter being a Subject is an implementation detail, and exists solely for output bindings. Thus there's no argument within this reasoning why this should work. 

Does this mean Angular will now officially support and guarantee EventEmitter to be a subject?

**Comment by Airblader** [comment] 2019-05-13 19:13
Also related #29499

**Comment by alxhub** [comment] 2019-06-18 22:42
I agree this is a little weird. For now `.asObservable()` should make it work.

**Comment by kara** [comment] 2020-05-27 22:22
Agree with @Airblader that this looks like a dupe of earlier issue, https://github.com/angular/angular/issues/29016, so closing this one.

**Closed by kara** 2020-05-27 22:22 UTC
Labels: comp: core, core: inputs / outputs, cross-cutting: types, freq1: low, severity2: inconvenient, triage #1, type: bug/fix
