### ISSUE TITLE
Issue with $rootScope service upgraded and used in angular2

### ISSUE THREAD

**Issue by vasuneet** [angular/angular#10590] opened 2016-08-09 14:15 UTC
I have created the following RootScopeService wrapper of $rootScope as below and after that i have used this under angular2 service named for example xService. : 

```
import {Injectable, bind, Inject} from '@angular/core';

@Injectable()
export class RootScopeService {
    private static instance:RootScopeService;
    constructor( @Inject('$rootScope') public rootScope: any) {
        if(RootScopeService.instance==null){
            RootScopeService.instance = this;
        }
        return RootScopeService.instance;
    }

    public broadcast(eventName, event) {
        this.rootScope.$broadcast(eventName, event);
    }

    public getRootScope() {
        return this.rootScope;
    }

}

export var RootScopeServiceInjectables: Array<any> = [
    bind(RootScopeService).toClass(RootScopeService)
];

import {Injectable,Inject} from '@angular/core'
import {Logger,Level} from 'angular2-logger/core';
//import {RootScopeService} from './RootScopeService';

@Injectable()
export class xService {
    private log: Logger;
    private static instance:xService;
    constructor(@Inject("$rootScope") public rootScopeService:any){
        if(xService.instance==null){
            this.log = new Logger();
            this.log.Level = Level.DEBUG;
           xService.instance = this;
        }
        return xService.instance;
    }
    trackCustomEvent(customEvent, currentScope){
        try{
            xService.instance.rootScopeService.broadcast(customEvent, currentScope);
        }catch(ex){
              x.instance.log.error("x:: trackCustomEvent : " + ex.toString());
        }
    }
    trackActionEvent(actionEvent, scope){
        xService.instance.trackCustomEvent(actionEvent, scope);
    }
}
```

After this i am downgrading this service is using this. Getting following issue
"TypeError: Cannot read property 'get' of null↵    at UpgradeAdapter.upgradeNg1Provider.providers.push.useFactory (http://localhost:3000/node_modules/@angular/upgrade//bundles/upgrade.umd.js:1019:72)↵    at ReflectiveInjector_._instantiate (http://localhost:3000/node_modules/@angular/core//bundles/core.umd.js:6373:31)↵

**Comment by zoechi** [comment] 2016-08-09 14:17
Please provide a Plunker to reproduce and please edit your post and add triple backticks before and after the code to make it readable.

**Comment by marcalj** [comment] 2016-08-10 08:46
From my experience, I had to switch all my ```$rootScope``` event handling to Observables, like:

```ts
import {Subject, Observable} from 'rxjs/Rx';

export interface ISomeService {
    sfUpdate$:Observable<boolean>;
    emitUpdate(profileChanged:boolean):void;
}

export class SomeService implements ISomeService {
    // Observable string streams
    sfUpdate$:Observable<boolean>;
    // Observable string sources
    private sfUpdateSource = new Subject<boolean>();

    constructor() {
        this.sfUpdate$ = this.sfUpdateSource.asObservable();
    }

    emitUpdate(profileChanged:boolean):void {
        // Emit event (SearchFilter:update)
        this.sfUpdateSource.next(Boolean(profileChanged));
    }
```

```ts
import {Subscription} from 'rxjs/Subscription';
import {ISomeService} from '../<path>/some.service';

export class Angular1Controller {
    private sfUpdateSubscription:Subscription;

    // @ngInject
    constructor(private SomeService:ISomeService) {
    }

    $onInit():void {
        // Subscribe to event
        this.sfUpdateSubscription = this.SomeService.sfUpdate$
            .subscribe(
                (profileChanged:boolean):void => {
                    this.$scope.$evalAsync(():void => {
                        this._handleLoadDataAction();
                    });
                });
    }

    $onDestroy():void {
        this.sfUpdateSubscription.unsubscribe();
    }
```

I hope it helps! :)

**Comment by gkalpak** [comment] 2017-12-13 12:22
Closing since there is no actual reproduction and the issue is very old anyway. FWIW, it should be possible to upgrade `$rootScope`. In fact we are doing it ourselves internally:

https://github.com/angular/angular/blob/8c5208834671a8a1f29cf28a5a4e7f16a816e21e/packages/upgrade/src/static/angular1_providers.ts#L47

**Closed by gkalpak** 2017-12-13 12:22 UTC
Labels: comp: upgrade/dynamic
