### ISSUE TITLE
Forms: Radio buttons don't function correctly with dynamic type on model-driven form

### ISSUE THREAD

**Issue by brandonroberts** [angular/angular#12025] opened 2016-10-01 02:45 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When building form inputs dynamically, if the `type` property for a `radio` button is a binding the radio inputs don't function correctly.

**Expected behavior**

The `type` binding for an input element is dynamically set to to `radio` and the form still functions.

**Minimal reproduction of the problem with instructions**

http://plnkr.co/edit/6mU55f?p=preview

Open the plunker
Note the first form with generated input fields and a `type='radio'` functions correctly
Note the second form with generated input fields and a `type` binding doesn't function correctly

**What is the motivation / use case for changing the behavior?**

Simple form generation with reuse of an input element while providing different `type` values.

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by pkozlowski-opensource** [comment] 2016-10-01 14:55
This is duplicate of #7329

**Closed by pkozlowski-opensource** 2016-10-01 14:55 UTC
Labels: comp: forms

**Comment by brandonroberts** [comment] 2016-10-01 15:05
Thanks
