### ISSUE TITLE
Angular localization file generation unexpected whitespace characters

### ISSUE THREAD

**Issue by dovydasjuodkazis** [angular/angular#54923] opened 2024-03-18 12:17 UTC
### Which @angular/* package(s) are the source of the bug?

localize

### Is this a regression?

Yes

### Description

There is an issue where there are duplicate text entries but with different spacing (whitespaces at the beginning/end of the string). After running i18n-extract the generated .xlf files includes these:

```
  <trans-unit id="5983969941473094568" datatype="html">
    <source>Please provide more information</source>
    <context-group purpose="location">
      <context context-type="sourcefile">src/app/features/game/components/game-boosting.ts</context>
      <context context-type="linenumber">150</context>
    </context-group>
    <note priority="1" from="description">Form validation error</note>
  </trans-unit>

  <trans-unit id="5273018339487538226" datatype="html">
    <source> Please provide more information </source>
    <context-group purpose="location">
      <context context-type="sourcefile">src/app/features/users/components/user/user.html</context>
      <context context-type="linenumber">19,21</context>
    </context-group>
  </trans-unit>

```

They both have the same source tag content, thus one of them has whitespaces wrapping the text.

To avoid this error I have to put my .html code in one line, but that will conflict with my code formatting rules.

Currently:

    <eld-error-message i18n *ngIf="formSubmitAttempt && !userReportFormGroup.get('message')?.valid"
    >
      Please provide more information
    </eld-error-message>

To make it work (but invalid solution):

    <eld-error-message i18n *ngIf="formSubmitAttempt && !userReportFormGroup.get('message')?.valid">Please provide more information</eld-error-message>

This also interferes with prettifying the code, after automatically formatting html code in your IDE, your tag placing may shift causing the .xlf file to have whitespaces for translations, which would later be duplicated in your translation software (f.e. Phrase).

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular: 16.2.12
npm: v18.12.0
```

**Comment by JoostK** [comment] 2024-03-18 14:22
Duplicate of #13114

**Closed by JoostK** 2024-03-18 14:22 UTC
