### ISSUE TITLE
router: observable members should return `Observable`, not `Subject`

### ISSUE THREAD

**Issue by wardbell** [angular/angular#13852] opened 2017-01-10 00:30 UTC
```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**

Many (all?) observable properties are actually `Subjects`.  `route.params` is one such example.

Yes, these propertes are cast as `Observable` in TypeScript. But they are actually `Subjects` and that invites abuse. Because these are also `Observer`s, a developer ... especially a JavaScript developer ... is invited to call `next`, `error`, `complete`. This is improper.

The implementation should call `subject.asObservable()`. That's why that method exists.

This only seem `picayune` until someone starts calling `next` "_because I have a really good use cast for that._"

Fixing the API as recommended would **not** be a breaking change; the intent is clear by the TypeScript cast and anyone who treats `route.params` as an `Observer` deserves what s/he gets.

**Expected behavior**

Every observable property based on a `Subject` should be based on `Subject.asObservable()`. This prevents attempts to call `next`, `error`, `complete` or any other `Observer` method.

**Minimal reproduction of the problem with instructions**
1) Load https://angular.io/resources/live-examples/router/ts/eplnkr.html
2) Add `hero-detail.component.ts#ngOnInit` ..
```
   let x = this.route.params.asObservable();
   debugger;
```
3) Run and click a hero.
4) Inspect `x` and `this.route.params` and note the real JavaScript types

```
> x
Observable {_isScalar: false, source: BehaviorSubject}
> this.route.params
BehaviorSubject {_isScalar: false, observers: Array[0], closed: false, isStopped: false, hasError: false…}
```

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web

all

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TS

**Comment by DzmitryShylovich** [comment] 2017-01-10 08:01
Don't think it's worth field duplication.
If user can do
```
(<any>route.params).next();
```
what will stop him from doing?
```
(<any>route)._params.next();

or

route['_params'].next();
```

**Comment by laco0416** [comment] 2017-01-11 01:53
@DzmitryShylovich This is mentioning about public API correctness. Even if some guys access to `route._params`, it doesn't have to be supported. 
The problem is a deviation between the type definition and actual. I totally agree on proposed idea.

**Comment by vicb** [comment] 2017-01-11 03:58
The public API **is** correct as Subject derives from Observable.

**Comment by laco0416** [comment] 2017-01-11 04:07
You are absolutely right. But in this case, clearly, `ActivatedRoute#params` is a read-only API and the type definition is for indicating that.

**Comment by vicb** [comment] 2017-01-11 04:51
I'm in favor of closing this one, the pb is inherent to JS.

Because the `Observable` have to [link back](https://github.com/ReactiveX/rxjs/blob/79afcd3fc83ee73d897250cb9c5740bc4df50fe2/src/Subject.ts#L117) to the Subject, users will always be able to access the underlying until JS supports private members.

**Closed by vicb** 2017-01-11 04:51 UTC
Labels: comp: router, type: feature

**Comment by wardbell** [comment] 2017-01-11 08:38
@DzmitryShylovich For the record, if the `params` property were the product of `asObservable`, you could not cast it or in any way call `next` on it. Go ahead and try with `x` in my repro.

@vicb Yes, JS can't stop you from probing to get at the subject. You can do that in the console with `x.source`, which returns the `BehaviorSubject`.  But that takes a deliberate act of sabotage whereas, when it appears in the JS to be a `Subject` (as `route.params` does), it appears to be part of the API.

Someday we might ask Ben Lesh why he bothered to add the `asObservable()` method to the `Subject` if he didn't intend for us to use in just this scenario. He went to the trouble of creating it like so:
```
  asObservable(): Observable<T> {
    const observable = new Observable<T>();
    (<any>observable).source = this;
    return observable;
  }
```
That isn't an accident. 

OTOH, he didn't put a docs comment on it either so we can't know what he was thinking.

Although I disagree with your conclusion, I can't say this is the biggest issue in the world nor am I offended by our difference of opinion. On we go.

**Comment by DzmitryShylovich** [comment] 2017-01-11 10:20
@wardbell 
> For the record, if the params property were the product of asObservable, you could not cast it to call next on it. 

I know. But u need to store subject in a "private" property anyway:
```
class ActivatedRoute {
   _params = new BehaviorSubject();

   get params(): Observable<any> {
        return this._params.asObservable();
   }
}
```
So u can access both.

**Comment by blesh** [comment] 2017-01-11 20:59
> Because the Observable have to link back to the Subject, users will always be able to access the underlying until JS supports private members.

@vicb it's on my TODO-list to rename private properties to `_prop` so people don't think `source.next()` is a valid thing... because it's not. 

### The purpose of asObservable

While `asObservable()` is just a layer of indirection, it's there for authors who don't want to leak internal implementation details to consumers of their libraries. RxJS can't assume that every user is using TypeScript. In fact, most users are not using TypeScript at all.

`asObservable()` provides some explicit intent for library authors spanning all consumers of a contract. Types in TypeScript only help TypeScript users.

If the world was _all_ TypeScript, though, I'd remove the method completely, as it wouldn't have a point.

### Caveats

If you find that performance is of the utmost importance, and that your subject is in the critical path, you can skip using `asObservable()`. It will only _minorly_ help performance, as most of those paths are inline-able I think, but it's a micro-optimization. The trade off being that you're now leaking some implementation detail in a way people might abuse.  RxJS 5 does this, in fact. Most subscriptions returned actually have a next, error and complete method on them because of some allocation optimizations that were done for performance reasons. We might move away from this, but it *is* a thing.

**Comment by DzmitryShylovich** [comment] 2017-01-11 21:19
@blesh thx for clarification

This is the standard usage of `ActivatedRoute`.
```
export class ComponentA {
  
  constructor(
    private route: ActivatedRoute,
  ) {}

  ngOnInit() {
    this.route.params
      .pluck('id')
      .subscribe((id) => ...);
  }

  onClick(e) {
     (<any>this.route.params).next(e);
  }
}
```
so what will happen if a user will push new values into `params` observable? nothing. he will push new values into his own subscription. will it break app? nope. so why do we care?

**Comment by wardbell** [comment] 2017-01-12 08:36
@DzmitryShylovich Only because I'm picky about doing it right. I haven't looked at any of the ones that are more problematic ... say Observables on the `router` which are visible outside this particular component. The `data` observable comes to mind; it's shared across routes and who knows what people are going to do with that. There are a bunch of properties to examine.

Of course your argument applies to any use of a foot gun. Why would I shoot myself? Don't I deserve it if I do?  Somehow, I feel that an API should take a different attitude.

All that said, I'm done on the subject ... at least here. Ben Lesh confirmed his intentions for `asObservable`.  I will continue to recommend it (although not require) it in Angular doc guidelines.
