### ISSUE TITLE
Angular devtools stopped working few days ago. "Angular application not detected"

### ISSUE THREAD

**Issue by Gertjan-Goetynck** [angular/angular#55114] opened 2024-03-29 08:28 UTC
### Is this a bug report or a feature request?

- [X] Bug Report
- [ ] Feature Request

### Please provide the steps to reproduce the issue [Bug Report only]

Try to run the dev tools on an angular project

### Please provide the expected behavior vs the actual behavior you encountered [Bug Report only]

Expected behavior: See the dev tools
Actual behavior: "Angular application not detected" on apps that detected it a few days ago. No changes in app happened.

This seems to be the same bug that was active a month or so ago and was caused by a new feature in Dev Tools. The feature got rolled back as a hotfix, but now the bug returned.

Link to the previous bug: https://github.com/angular/angular/issues/53953#issuecomment-2026356328

### Please provide a screenshot if possible [Bug Report only]

<img width="1905" alt="image" src="https://github.com/angular/angular/assets/47894477/1946789e-bd09-47eb-bab4-d0e1641b20f9">

### Please provide the exception or error you saw [Bug Report only]

```true
Angular application not detected
```

**Comment by AleksanderBodurri** [comment] 2024-03-29 16:33
Thanks for the report @Gertjan-Goetynck 

Could you provide which version of Angular you are experiencing this issue with? Is this application using any custom build tools or just `ng serve`/`ng build`?

**Comment by JeanMeche** [comment] 2024-03-31 05:29
Can you also double check the version of your devtools. Should be 1.0.12.

**Comment by Gertjan-Goetynck** [comment] 2024-04-04 11:37
> Thanks for the report @Gertjan-Goetynck
> 
> Could you provide which version of Angular you are experiencing this issue with? Is this application using any custom build tools or just `ng serve`/`ng build`?

The angular version we are using is 11.2.10. We do an ng serve with a custom host and disabled hostcheck.

**Comment by Gertjan-Goetynck** [comment] 2024-04-04 11:37
> Can you also double check the version of your devtools. Should be 1.0.12.

Its version 1.0.12 indeed.

**Comment by AleksanderBodurri** [comment] 2024-04-05 22:31
Thank you @Gertjan-Goetynck. I'm tracking a fix for this issue here https://github.com/angular/angular/pull/55233. The cause here is that Angular DevTools currently officially supports v12 and above. A recent change to how DevTools scripts get injected into applications prevented those scripts from being injected into Angular applications below version 12. The PR in question allows this script to be injected as normal for these apps again, but also implements an warning notice in those applications to inform the user that they are not on a supported version.

**Closed** 2024-06-12 21:51 UTC
Labels: area: devtools
