### ISSUE TITLE
ngSwitchCase/ngSwitchDefault in ngIf not work well

### ISSUE THREAD

**Issue by w6942** [angular/angular#48444] opened 2022-12-12 07:22 UTC
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

Yes

### Description

ngSwitchCase or ngSwitchDefault in ngIf, after change switchVal, the view not refresh

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-5nmna3?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 11.2.14
Node: 16.13.2
OS: win32 x64

Angular: 11.2.14
... animations, cli, common, compiler, compiler-cli, core
... elements, forms, language-service, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1102.14
@angular-devkit/build-angular      0.1102.14
@angular-devkit/build-ng-packagr   0.1002.0
@angular-devkit/core               11.2.14
@angular-devkit/schematics         11.2.14
@angular/cdk                       11.2.13
@schematics/angular                11.2.14
@schematics/update                 0.1102.14
ng-packagr                         11.2.4
rxjs                               6.6.7
typescript                         4.0.2
```

**Comment by JoostK** [comment] 2022-12-12 09:10
Duplicate of #47578; this usage pattern is not supported by `ngSwitch`.

**Closed by JoostK** 2022-12-12 09:10 UTC
