### ISSUE TITLE
Angular @ContentChildren of an recursive ng-template 

### ISSUE THREAD

**Issue by sky007** [angular/angular#21751] opened 2018-01-24 15:10 UTC
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
When you use recursion in ng-template (in combination with ng-content) the @ContentChildren doesn't know/find the components which are produced by the ng-template.

Example of recursion template in [Stackblitz](https://stackblitz.com/edit/angular-qhzpw1)

As you can see **ul-item** doesn't know the **ul-title** in the @ContentChildren even though they are the ng-content of the component.

## Expected behavior
What I expect is that @ContentChildren will be detected by the component which is included in de ng-content even if it's produced by the ng-template.

## Minimal reproduction of the problem with instructions
[Stackblitz](https://stackblitz.com/edit/angular-qhzpw1)

## What is the motivation / use case for changing the behavior?
Simple readable code and flexibility usage of ng-template

## Environment
<pre><code>
Angular version: 5.1.2
Angular CLI: 1.6.5
Typescript: 2.5.3
RXJS: 5.5.2

Browser:
- [x] Chrome (desktop) version XX
- [x] Chrome (Android) version XX
- [x] Chrome (iOS) version XX
- [x] Firefox version XX
- [x] Safari (desktop) version XX
- [x] Safari (iOS) version XX
- [x] IE version XX
- [x] Edge version XX
 
For Tooling issues:
- Node version: 6.9.4
- Platform:  Windows

**Comment by pkozlowski-opensource** [comment] 2019-03-19 10:56
Slightly simplified (limited usage of `*` syntax) stackblitz: https://stackblitz.com/edit/angular-uvweur?file=app%2Ftest.component.ts

The issue here is a mismatch of expectation vs. design of content queries in Angular, see: https://github.com/angular/angular/issues/14842#issuecomment-470167258

Both here and in #14842 a user is expecting content queries to pickup nodes _as rendered_ (that is, taking into account views _insertion point_) while what Angular takes into account is the _definition_ point (as explained in https://github.com/angular/angular/issues/14842#issuecomment-470167258).

Now the interesting question is: _why_  

> What I expect is that @ContentChildren will be detected by the component which is included in de ng-content even if it's produced by the ng-template.

It _sounds_ like what you want to do is to do almost DOM query... I'm genuinely interested in knowing why a parent directive wants to "know" about their children... Would anyone mind elaborating on a functional use-case?

**Comment by sky007** [comment] 2019-03-19 15:05
> It sounds like what you want to do is to do almost DOM query... I'm genuinely interested in knowing why a parent directive wants to "know" about their children... Would anyone mind elaborating on a functional use-case?

The use-case is to make an expandable list-tree depending on if there are children on that level of item. Instead of making a pile code of `<title><item><title><item><title><item>` and so to repeat on.

**Comment by pkozlowski-opensource** [comment] 2019-03-19 15:11
> The use-case is to make an expandable list-tree depending on if there are children on that level of item.

**Comment by pkozlowski-opensource** [comment] 2020-05-29 07:20
Based on the latest use-case description it really sounds like a duplicate of #26061

**Closed by pkozlowski-opensource** 2020-05-29 07:20 UTC
Labels: comp: core, core: queries, type: feature

**Comment by pkozlowski-opensource** [comment] 2020-05-29 09:22
Actually, let's track it as a duplicate of #14842
