### ISSUE TITLE
angular beta html parser not correctly processing <pre> tag

### ISSUE THREAD

**Issue by afvieira** [angular/angular#6000] opened 2015-12-18 09:49 UTC
```
<pre>
  test
</pre>
```

`EXCEPTION: Template parse errors:...`

I include:

```
<script src="../node_modules/angular2/bundles/angular2.dev.js"></script> 
<script src="../node_modules/angular2/bundles/router.dev.js"></script>
<script src="../node_modules/angular2/bundles/http.dev.js"></script>
<script src="../node_modules/angular2/bundles/angular2-polyfills.js"></script>
```

**Comment by gdi2290** [comment] 2015-12-18 10:05
please include the polyfills first before angular2

**Comment by afvieira** [comment] 2015-12-18 10:44
```
<script src="../node_modules/angular2/bundles/angular2-polyfills.js"></script>
<script src="../node_modules/angular2/bundles/angular2.dev.js"></script>
<script src="../node_modules/angular2/bundles/router.dev.js"></script>
<script src="../node_modules/angular2/bundles/http.dev.js"></script>
```
still doesn't work.

**Comment by pkozlowski-opensource** [comment] 2015-12-18 11:42
@afvieira could you please try to reproduce it in plunker? I can't reproduce it, see here: http://plnkr.co/edit/MCQhhmEQzpSDaK5vAZq4?p=preview (at least not in chrome / ffox)

**Comment by gdi2290** [comment] 2015-12-18 17:07
could you include `es6-shim` before the `angular2-polyfills`
`<script src="../node_modules/es6-shim/es6-shim.js"></script>`

**Comment by afvieira** [comment] 2015-12-21 09:39
@gdi2290 still doesn´t work.

Making using of @pkozlowski-opensource plunkr I reproduce the problem: http://plnkr.co/edit/kveXXFQyf04GMruDpndd?p=preview

**Comment by wesleycho** [comment] 2015-12-21 17:21
One probably should not be nesting a <pre> tag inside a <p> tag - I believe this is invalid HTML.

**Comment by gdi2290** [comment] 2015-12-21 18:31
@afvieira wrap all `pre` tags with `code` tags
http://plnkr.co/edit/DlksARoVGMY1sVP85QWb?p=preview

**Comment by vicb** [comment] 2015-12-21 18:57
> One probably should not be nesting a <pre> tag inside a <p> tag - I believe this is invalid HTML.

This is the root cause of the issue, see http://www.w3.org/TR/html5/syntax.html#optional-tags

`<p><pre>...</pre></p>` is equivalent to `<p></p><pre>...</pre></p>`, you then have a closing p without the matching opening tag which trigger the issue.

**Closed by vicb** 2015-12-21 18:57 UTC

**Comment by George35mk** [comment] 2017-12-13 17:34
Yes if you have 

## ERROR
```html
<p>
  <pre>
    {{ data | json }}
  </pre>
</p>
```

## WORKS
```html
<div>
  <pre>
    {{ data | json }}
  </pre>
</div>
```
