### ISSUE TITLE
Unable to reuse TemplateRef in different containers

### ISSUE THREAD

**Issue by stalniy** [angular/angular#13080] opened 2016-11-24 15:31 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Currently when I try to reuse the same `TemplateRef` instance for multiple items it renders wrong view

**Expected behavior**
It should render a separate view inside each view container

**Minimal reproduction of the problem with instructions**
https://plnkr.co/edit/PZe5XnmJ2KoJ99ts33F9?p=preview

Currently you will see 2 words "Enabled".
Should be "
{ "enabled": true } Enabled
{ "enabled": false } disabled" (as in https://plnkr.co/edit/rZuCs8O7YE4fYplfI3gF?p=preview)

**What is the motivation / use case for changing the behavior?**
I have a slider with hundreds of slides and want to optimise DOM by using lazy DOM creation. For this I need to use template reference. Eventually it's something like this:
```html
<lazy-slides [items]="files">
   <template let-file="item">
       <preview-file [src]="file.url"></preview-file>
   </template>
</lazy-slides>
```
Then using `ngFor` and `ngTemplateOutlet` I put this template for first 5 items and when user slides I change references inside array.

**Please tell us about your environment:**
npm: 3.9.3
OSX EI Capitan 10.11.5
Atom
Chrome 54.0.2840.98

* **Angular version:** 2.0.X
Reproducible starting from 2.2.0, the same in 2.3.0. Works properly in 2.2.0-rc.0 and older ( https://plnkr.co/edit/rZuCs8O7YE4fYplfI3gF?p=preview )

* **Browser:**
Chrome 54.0.2840.98
 
* **Language:** all

**Comment by vinckobb** [comment] 2016-11-24 16:33
Looks like it's same as #12968 

@ribizli provided there workaround which may help. Updated plnkr https://plnkr.co/edit/JSIksQln36mIlbwnPEVd?p=preview

**Comment by stalniy** [comment] 2016-11-25 08:07
thanks @vinckobb that works for me

**Comment by sgomanf** [comment] 2016-11-25 11:40
#1346

**Comment by tbosch** [comment] 2016-12-03 00:23
Closing as a duplicate of https://github.com/angular/angular/issues/13118, and that issue describes the underlying problem better.

**Closed by tbosch** 2016-12-03 00:23 UTC
Labels: comp: core & compiler
