### ISSUE TITLE
angular 8: aplicacion PWA error 404 not found ngsw-worke.js 

### ISSUE THREAD

**Issue by SalvadorFuture** [angular/angular#38529] opened 2020-08-19 12:10 UTC
Hello,

I have a PWA application that worked perfectly, but now loading the application in production shows the following error:

https://drive.google.com/file/d/1MW2eTMfQfIGj5ncpO-nNPEiR4LAPWht_/view?usp=sharing

On the other hand, if I access the application from Chrome with an incognito window or CTRL + F5 then the application loads correctly.

I understand that it has something to do with the cache but I cannot configure the application to work properly without having to clear the cache or with a Chrome window in incognito.

On the other hand, in the local development environment everything works OK

The problems appear after building and uploading the application to the production server.

The content of the ngsw.json file can be seen in the following image:

https://drive.google.com/file/d/1WiC7ddw6Y6P2mhzfVmR9fqZ-wDO1T2d7/view?usp=sharing

The angular versión I'm working is:

Angular CLI: 8.3.17
Node: 12.13.0
OS: win32 x64

Please, can you help me?

The url aplication with this error is:  https://residenciasuniversitarias.ulpgc.es/areaprivadapwa/login

Thanks a lot

**Comment by MukeshJ2506** [comment] 2020-08-20 09:50
I am facing the same issue in 
Angular CLI 10.0.1
Angular Core 10.0.2
Node 12.16.3
OS: win32 x64
issue is also noted in Azure CDN as well as local http-server in production mode

**Comment by SalvadorFuture** [comment] 2020-08-20 11:22
I have read this article and I performed multiple tests but I don´t find de solution: [How to configure ngsw-config.json?](https://medium.com/@srashtisj/how-to-configure-ngsw-config-json-4f2a026d8374)

In this other article, there is same solution but any is good for me: [NGSW based Service Worker doesn't work in ng8 with differential builds](https://github.com/angular/angular-cli/issues/15259) 

Also I revised the file .htacess but I don't have had changes for a long time. ¿?¿?¿?¿?

Same times I think is a problem of Chrome, but is not posible.... because the proble exists also in Chrome of Android phones

Please... same help is very important.

Thanks.

**Comment by SalvadorFuture** [comment] 2020-08-20 12:13
Also in the next url an image with content of ngsw-config.json y project to build the aplication web .

https://drive.google.com/file/d/10ALk2VA55zyurjJxt_G9T3eBmdyOl47N/view?usp=sharing

Thanks

**Comment by gkalpak** [comment] 2020-08-20 14:24
I am sorry, @SalvadorFuture, but it is not possible to investigate the issue with the info you have provided. From the partial error messages shown, it seems like the ServiceWorker is trying to fetch some non-existent files.

Also, while you didn't specify the version of Angular you are using (i.e. the version of the `@angular/core` package), you seem to be using an old version of the `ngsw-config.json`. More specifically, you use the `versionedFiles` property, which is deprecated (in favor of just `files`), and the patterns you specify in there seem outdated (have you confirmed that your app's `dist` directory contains such `.js` files?).

I am afraid we can't help much. I suggest you go through the latest ServiceWorker docs on angular.io and especially the [SW Configuration](https://angular.io/guide/service-worker-config) guide.

I am going to close this, since it is not actionable in its current state. If you are still having problems, please open a new issue and provide all requested information, including a minimal reproduction. (Otherwise, it is really hard for us to investigate and diagnose errors.)

##
<sub>BTW, you should probably exclude the `.php` files from the `assets` asset-group :grin:</sub>

**Closed by gkalpak** 2020-08-20 14:24 UTC
Labels: comp: service-worker
