### ISSUE TITLE
hostBinding `class.xxx` can not update after `zone.onStable`

### ISSUE THREAD

**Issue by hpyou** [angular/angular#34611] opened 2020-01-02 08:14 UTC
# 🐞 bug report

### Affected Package
possibly to be  @angular/core and NgZone

### Is this a regression?

this bug is happened in ng8 and ng9

### Description

I add `host:{'[class.blue]': 'isColorful'}` in `@Component`, and in lifeCycleHooks like `ngOnInit` or `ngAfterViewInit` or `ngAfterContentInit` i update the property `isColorful` like
 ```
    this._zone.onStable.asObservable().pipe(take(1)).subscribe(() => {
      this.isColorful = true;
    });
```
and the view was not updated, if not use  `zone.onStable`, it works ok.

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-bb6xlp

## 🔥 Exception or Error

code:

![image](https://user-images.githubusercontent.com/15992591/71657431-c6099c00-2d7a-11ea-956e-393a43e321f0.png)

the expected view :

![image](https://user-images.githubusercontent.com/15992591/71657260-103e4d80-2d7a-11ea-90d9-bce55b15c342.png)

current view:

![image](https://user-images.githubusercontent.com/15992591/71657275-1fbd9680-2d7a-11ea-92be-9c781d66ff7a.png)

I expect when trigger `zone.onStable` to update the hostBinding property, the view will be update too. 

## 🌍  Your Environment

Angular CLI: 9.0.0-rc.7
Node: 10.18.0
OS: win32 x64

Angular: 9.0.0-rc.7
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-rc.7
@angular-devkit/build-angular     0.900.0-rc.7
@angular-devkit/build-optimizer   0.900.0-rc.7
@angular-devkit/build-webpack     0.900.0-rc.7
@angular-devkit/core              9.0.0-rc.7
@angular-devkit/schematics        9.0.0-rc.7
@ngtools/webpack                  9.0.0-rc.7
@schematics/angular               9.0.0-rc.7
@schematics/update                0.900.0-rc.7
rxjs                              6.5.3
typescript                        3.6.4
webpack                           4.41.2

**Comment by tieppt** [comment] 2020-01-03 09:10
That is because onStable is outside Angular. So this work as expected.

https://github.com/angular/angular/blob/9.0.x/packages/core/src/zone/ng_zone.ts#L246-L262

You can modify your code as following, then it's work too.
```ts
this._zone.run(() => {
  console.log('on Zone', NgZone.isInAngularZone());
  this.isColorful = true;
})
```

**Comment by dawidgarus** [comment] 2020-01-07 15:43
I think it's because calling `detectChanges()` doesn't update host bindings.
See: https://github.com/angular/angular/issues/22560
For some bizarre reason in Angular updating host binding are not a part of change detection of the component...

**Comment by pkozlowski-opensource** [comment] 2020-01-08 19:57
To clarify:
* this is _not_ a regression (all previous versions behave the same) - currently host bindings, for a given component, are _not_ updated as part of component's view change detection;
* longer term we _might_ revisit behaviour of host bindings wrt to calling `detectChanges()` as I can see how the current behaviour could be confusing...

**Comment by hpyou** [comment] 2020-01-14 10:37
@tieppt `this._zone.run()` fixes my problem

**Comment by marcus-sa** [comment] 2020-01-21 09:53
@dawidgarus that is really absurd, as bindings are part of ones view

**Comment by mhevery** [comment] 2020-03-03 23:42
closing as working as intended.

**Closed by mhevery** 2020-03-03 23:42 UTC
Labels: comp: core

**Comment by dandean** [comment] 2020-03-26 18:47
Just want to post to make it clear what the solution is for updating a component's `@HostBinding()`. The solution is to tell the parent component to detect changes:

https://github.com/angular/angular/issues/22560#issuecomment-473958144

```
constructor(@SkipSelf() protected cdRef: ChangeDetectorRef) {
```

**Comment by dawidgarus** [comment] 2020-03-27 09:46
@dandean I wouldn't recommend it. That's not a solution, that's a workaround. And not a very good one. Imagine having 10 independent tiny components used in the same component and all of them want to update their host bindings. You would trigger change detection in parent element 10 times and it will unnecessarily check bindings in the whole component (10 times) which could be costly if there are many of them or you use ngFor.

**Comment by dandean** [comment] 2020-03-27 16:22
@dawidgarus What do you recommend as an alternative workaround? `zone.run()` doesn't solve the issue for me.

**Comment by dawidgarus** [comment] 2020-03-27 17:05
@dandean I'm using Renderer2 inside ngDoCheck instead of HostBinding. It introduces little additional boilerplate and actually works when change detection happens for the component:
```typescript
ngDoCheck(): void {
  bindClass(renderer, element.nativeElement, 'foo', this.classFoo);
}
```

**Comment by dandean** [comment] 2020-03-27 17:17
@dawidgarus is `bindClass` a custom function of your own?

**Comment by dawidgarus** [comment] 2020-03-30 08:21
@dandean Yes. It's simple if true then renderer.addClass else renderer.removeClass.
