### ISSUE TITLE
routerLinks doesn't match active state when route contains query string params

### ISSUE THREAD

**Issue by marco-gagliardi** [angular/angular#6683] opened 2016-01-25 17:34 UTC
Not sure if it's an intended behavior, anyway it seems that Angular2 doesn't assign the active state (the "router-link-active" class) to a routerLink element when its corresponding route  contains query string params. 
You can reproduce this situation with the official routing example itself:
https://angular.io/resources/live-examples/router/ts/plnkr.html

- Click on "heroes" to step in the Horoes list view (note how the active class has been correctly assigned to the Heroes anchor element in the navbar)
- Choose one from the list ( the new route removes the active state from the heroes link)
- Click on the back button 
- You're back in the hero list view, but the Heroes anchor element hasn't been given the router-link-active class in the navbar

The last click triggers the following:
    this._router.navigate(['Heroes',  {id: heroId, foo: 'foo'} ]);

As stated in the doc "Unfortunately, the browser address bar does not change when running the live example in plunker." anyway "The id value appears in the query string (?id=15&foo=foo), not in the URL path. The path for the "Heroes" route doesn't have an :id token."

**Comment by brandonroberts** [comment] 2016-01-25 20:14
Duplicate of https://github.com/angular/angular/issues/6459

**Comment by vicb** [comment] 2016-09-26 20:26
obsolete - former router

**Closed by vicb** 2016-09-26 20:26 UTC
