### ISSUE TITLE
Feature Request:  default 'router-link-active' class attachment (old router behaviour)

### ISSUE THREAD

**Issue by robwormald** [angular/angular#9503] opened 2016-06-22 19:12 UTC
_From @dharders on June 21, 2016 2:54_

PR #57 added the directive `routerLinkActive`, which enabled us to set a custom class on the current `routerLink` element. This is great!

But AFAIK, I have to attach this `routerLinkActive` directive to EVERY SINGLE LINK.

eg

```
<ul>
    <li><a [routerLink]="['/sales']"    routerLinkActive="router-link-active" ...
    <li><a [routerLink]="['/reports']"  routerLinkActive="router-link-active" ...
    <li><a [routerLink]="['/search']"   routerLinkActive="router-link-active" ...
    <li><a [routerLink]="['/settings']" routerLinkActive="router-link-active" ...
    ...
</ul>
```

The old Angular router would attach the class `router-link-active` automatically so all I had to include was a custom `.router-link-active { }` css style and I got active link feedback for free!

Is there a way I can set a default `routerLinkActive="router-link-active"` once only? Per app ? Per router ? Per component ? Per parent element (i.e. the `<ul>`)?

It seems like a lot of unnecessary noise (especially when you also start adding `[routerLinkActiveOptions]="{exact: false}"` to the same `routerLink` element.

_Copied from original issue: angular/vladivostok#97_

**Comment by robwormald** [comment] 2016-06-22 19:12
_From @kordianbruck on June 21, 2016 12:26_

https://github.com/angular/vladivostok/pull/57#issuecomment-226948183 already commented on the PR, that it would be better (simpler) to attach the routerLinkActive to the parent element, e.g. `<ul>` or `<nav>` which would be pretty much the same thing then, right?

**Comment by robwormald** [comment] 2016-06-22 19:12
_From @brandonroberts on June 21, 2016 12:56_

Having a separate directive for active classes is more flexible as you can put it on parent elements and host elements. I do think the default should be `{ exact: false }` though

**Comment by robwormald** [comment] 2016-06-22 19:12
_From @dharders on June 21, 2016 12:56_

@kordianbruck yes and no.

The **ideal** solution would add the class automatically on the `routerLink` element (ala old router stytle).

If this isn't possible with the new router, then yes, attaching `routerLinkActive` (manually) to the `<ul>` would be better, but I think we still should strive for the ideal whilst in alpha.

To be clear: Desired outcome in decreasing order:

1. Angular attaches the default class name to `routerLink` element automatically (potentially configurable `routerLinkActive` at App level  - manually done by user, but if not specified, defaults to `router-link-active` like the old router) user can opt-out too
2. User attaches the `routerLinkActive` once at Router level (at config time)
3. User attaches the `routerLinkActive` once at parent Element level (i.e. `<ul>`)
4. User attaches the `routerLinkActive` at each `routerLink` level    (**current behaviour**)



I should note here that I am NOT using *ngFor to create my `routerLink`'s, so there is quite a bit of extra manual work generating the template (not to mention redundant noise) that wasn't there in the last router.

**Comment by robwormald** [comment] 2016-06-22 19:12
_From @dharders on June 21, 2016 13:5_

@brandonroberts Yes absolutely agree that it is more flexible and I probably will end up using different `active` classes for `children` routes in the future. I'm just trying to work out if this **is just how it is now** or can we do better ?

**Comment by robwormald** [comment] 2016-06-22 19:12
_From @brandonroberts on June 21, 2016 14:18_

@dharders both. The issue with the old way it worked was that you couldn't change the default class `router-link-active` and you couldn't use it on parent elements. We could have the routerLink only add `router-link-active` and use routerLinkActive where needed, but it sounds confusing. 

Maybe the routerLinkActive selector can be updated to match routerLink elements?

As a side note, the router will be merged back into http://github.com/angular/angular soon, so you might want to re-open this issue there.

**Comment by robwormald** [comment] 2016-06-22 19:12
_From @dharders on June 21, 2016 14:33_

@brandonroberts 

> Maybe the routerLinkActive selector can be updated to match routerLink elements?

Yes, I think this would be a good compromise. 

I guess we just need clear syntax to enable the user to opt-in/out of the feature.

Maybe  `[routerLinkActiveOptions]="{autoapply: true}"` at the `<ul>` level or similar ?

**Comment by dharders** [comment] 2016-06-23 05:22
Dupe of #9426, but up to you @robwormald if you still want this one open here (as this was the original issue in the old angular/vladivostok repository). I had already created a cleaner issue report in angular/angular here #9426. (although it isn't labelled `comp: router` yet!)

**Closed** 2016-06-23 05:25 UTC
Labels: comp: router
