### ISSUE TITLE
Why isn't ViewEncapsulation automatically determined based on availability?

### ISSUE THREAD

**Issue by chaim770** [angular/angular#7394] opened 2016-03-03 12:53 UTC
According to the [docs](https://angular.io/docs/js/latest/api/core/ViewEncapsulation-enum.html), the default component encapsulation is `ViewEncapsulation.Emulated`.

Why can't the framework automatically determine whether ShadowDOM is indeed supported or not (pretty easy) and act accordingly (by default)?

**Comment by zoechi** [comment] 2016-03-03 14:31
What if you want `None` to be able to apply styles added to the `<head>` to the whole page?

**Comment by chaim770** [comment] 2016-03-03 14:36
@zoechi I never meant to disable the option completely. Obviously, there needs to be a way to control style encapsulation.

My question is why isn't there *additional* (and possibly the default) option that is `ViewEncapsulation.Auto` that will automatically detect whether native ShadowDOM can be used.

**Comment by zoechi** [comment] 2016-03-03 14:46
I see. I expected `Native` to fall back to `Emulated` if not available.

**Comment by chaim770** [comment] 2016-03-03 14:55
@zoechi, I doubt that's the case. Also, the documentation doesn't state so (where it really should).

See: https://github.com/angular/angular/blob/e7470d557df0400a812d84551524970cb5f12eee/modules/angular2/src/platform/dom/dom_renderer.ts#L109

**Comment by zoechi** [comment] 2016-03-03 15:07
Ok, than it's good you created the issue. I hope my questions helped make it more clear for future visitors what the issue is about instead of obscuring it ;-)

**Comment by TheLarkInn** [comment] 2016-03-09 19:13
+1

**Comment by zoechi** [comment] 2016-07-08 05:05
This should now be easier after #7883 has landed.

**Comment by vicb** [comment] 2016-07-08 16:19
it's not possible because the behavior are not exactly the same (there are edge cases)

**Closed by vicb** 2016-07-08 16:19 UTC
