### ISSUE TITLE
Adding Navigation Id generator issue

### ISSUE THREAD

**Issue by shiftybloke** [angular/angular#40238] opened 2020-12-22 16:47 UTC
# 📚 Docs or angular.io bug report

### Description

This part of the tutorial asks a user to create a For loop to dynamically create an Id value for each item in products.ts
however, the Id value is not created by following the steps in the tutorial and so the app fails to load information about each product when you click through to their individual pages.

Manually adding an Id variable to each of the products in products.ts resolves the issue, but does not allow a user to dynamically set the value with a For loop.

### What's the affected URL?**
https://angular.io/start/start-routing

## 🔥 Exception or Error

Property 'id' does not exist on type '{ name: string; price: number; description: string; }'.

Found in file: product-details.component.ts when inspecting this line: return product.id === Number(productIdFromRoute);
![image](https://user-images.githubusercontent.com/60511512/102912418-45edb200-4475-11eb-9d2b-1e15eb1d3add.png)

**Comment by gkalpak** [comment] 2020-12-22 17:06
Thx for reporting this, @shiftybloke! The problem will be fixed by #40197.
(Closing this as a duplicate of #40189.)

**Closed by gkalpak** 2020-12-22 17:06 UTC
Labels: P3, comp: docs, docsarea: quickstart
