### ISSUE TITLE
first-app-lesson-01 does not install

### ISSUE THREAD

**Issue by jeremy-ekers** [angular/angular#53283] opened 2023-11-30 16:07 UTC
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

I started to look at angular, trying the first tutorial.

Installed node-v20.10.0-x64.msi on windows. Run in cygwin bash. "npm -v" returns "10.2.4".

Step 1 , running "npm install" fails.

### Please provide the exception or error you saw

```true
> npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: angular.io-example@0.0.0
npm ERR! Found: @angular/common@17.0.0
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"17.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^16.0.0" from angular-in-memory-web-api@0.16.0
npm ERR! node_modules/angular-in-memory-web-api
npm ERR!   angular-in-memory-web-api@"~0.16.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR!
npm ERR! For a full report see:
npm ERR! C:\Users\jeremy\AppData\Local\npm-cache\_logs\2023-11-30T15_58_47_296Z-eresolve-report.txt
npm ERR! A complete log of this run can be found in: C:\Users\jeremy\AppData\Local\npm-cache\_logs\2023-11-30T15_58_47_296Z-debug-0.log
```

**Comment by jessicajaniuk** [comment] 2023-11-30 16:24
Looks like there's a mismatch between what the `angular-in-memory-web-api` package requires and what the rest of the app requires. the in memory web api package is looking for `angular/common` at v16, and the rest is looking for v17. Is this a fresh install or an updated install?

**Comment by spock123** [comment] 2023-11-30 20:53
`npm i --force`

**Comment by VishalPawar1010** [comment] 2023-12-01 07:00
Hey @jeremy-ekers, I tried reproducing above issue you mentioned.
 - I assumed you downloaded demo-app from page : https://angular.io/tutorial/first-app/first-app-lesson-01 , with download link (Completed code): https://angular.io/generated/zips/first-app-lesson-01/first-app-lesson-01.zip 
 - after `npm install` faced same issue

You can go with 2 possible approaches (both worked for me)- 

Option 1 : 
1. Run `npm install angular-in-memory-web-api@latest`, 
2. Run `npn install`
3. Run `ng serve` : app is successfully deployed.

Option 2 : 
1. Just run `npm install --force` , it will install all required dependecies forcefully.
2. Then run `ng serve` : app is successfully deployed.

I hope it helps for you.

**Comment by jeremy-ekers** [comment] 2023-12-01 14:16
Neither method works for me. Error below.

I reverted to shell cmd.exe, since cygwin is another layer of unneeded complexity here. 

Also, ng is not found. Seems like maybe the node install didn't work properly.

>C:\Users\jeremy\b\cygwin64\home\jeremy\projects\node.js\angular\first-app-lesson-00>npm install angular-in-memory-web-api@latest
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: @angular-devkit/build-angular@17.0.0
npm ERR! Found: typescript@4.9.5
npm ERR! node_modules/typescript
npm ERR!   peerOptional typescript@">=4.9.5" from cosmiconfig@8.3.6
npm ERR!   node_modules/cosmiconfig
npm ERR!     cosmiconfig@"^8.2.0" from postcss-loader@7.3.3
npm ERR!     node_modules/postcss-loader
npm ERR!       postcss-loader@"7.3.3" from @angular-devkit/build-angular@17.0.0
npm ERR!       node_modules/@angular-devkit/build-angular
npm ERR!         dev @angular-devkit/build-angular@"17.0.0" from the root project
npm ERR!   peer typescript@">=2.7" from ts-node@10.9.1
npm ERR!   node_modules/ts-node
npm ERR!     dev ts-node@"~10.9.0" from the root project
npm ERR!   1 more (the root project)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer typescript@">=5.2 <5.3" from @angular-devkit/build-angular@17.0.0
npm ERR! node_modules/@angular-devkit/build-angular
npm ERR!   dev @angular-devkit/build-angular@"17.0.0" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: typescript@5.2.2
npm ERR! node_modules/typescript
npm ERR!   peer typescript@">=5.2 <5.3" from @angular-devkit/build-angular@17.0.0
npm ERR!   node_modules/@angular-devkit/build-angular
npm ERR!     dev @angular-devkit/build-angular@"17.0.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR!
npm ERR! For a full report see:
npm ERR! C:\Users\jeremy\AppData\Local\npm-cache\_logs\2023-12-01T13_39_14_007Z-eresolve-report.txt

>npm ERR! A complete log of this run can be found in: C:\Users\jeremy\AppData\Local\npm-cache\_logs\2023-12-01T13_39_14_007Z-debug-0.log

**Comment by LostKatana** [comment] 2023-12-01 23:24
Node version: v20.10.0

Option 1 didn't work for me either.
`npm install angular-in-memory-web-api@latest`

> ERR! code ERESOLVE                             
> ERR! ERESOLVE unable to resolve dependency tree
> ERR!                                           
> ERR! While resolving: angular.io-example@0.0.0 
> ERR! Found: typescript@4.9.5
> ERR! node_modules/typescript
> ERR!   dev typescript@"~4.9.3" from the root project
> ERR!
> ERR! peer typescript@">=5.2 <5.3" from @angular/compiler-cli@17.0.0
> ERR! node_modules/@angular/compiler-cli
> ERR!   dev @angular/compiler-cli@"17.0.0" from the root project
> ERR!   peer @angular/compiler-cli@"^17.0.0" from @angular-devkit/build-angular@17.0.0
> ERR!   node_modules/@angular-devkit/build-angular
> ERR!     dev @angular-devkit/build-angular@"17.0.0" from the root project
> ERR!
> ERR! Fix the upstream dependency conflict, or retry
> ERR! this command with --force or --legacy-peer-deps
> ERR! to accept an incorrect (and potentially broken) dependency resolution.
> ERR!
> ERR!
> ERR! For a full report see:
> ERR! C:\Users\----\AppData\Local\npm-cache\_logs\2023-12-01T23_14_05_169Z-eresolve-report.txt


Forcefully installing with `npm i --force` was working with conflicting dependencies.

**Comment by slav-getov** [comment] 2023-12-07 10:57
Same thing happened to me. The only option that worked was the > npm install --force

**Comment by ChrisMSaltire** [comment] 2023-12-08 17:32
in package.json I changed
```
    "typescript": "~4.9.3"
```
to 
```
    "typescript": "~5.2"
```
reran `npm i`

**Comment by chbussler** [comment] 2023-12-10 16:53
Option 2 worked for me as well, but not Option 1.

**Comment by 7stud** [comment] 2024-01-05 01:20
Same problem on macOS 12.5.1:
```
% asdf current
elixir          1.16.0-otp-26   /Users/7stud/.tool-versions
erlang          26.1.2          /Users/7stud/.tool-versions
nodejs          20.10.0         /Users/7stud/.tool-versions
python          3.10.4          /Users/7stud/.tool-versions
ruby            3.1.2           /Users/7stud/.tool-versions

% npm -v
10.2.3
```

I'm trying the [Lesson 1: Hello world](https://angular.io/tutorial/first-app/first-app-lesson-01#lesson-1-hello-world).  First, the downloaded folder is named:

`first-app-lesson-00`

Yet, the tutorial says:

In your project directory, navigate to the `first-app` directory.  There is no first-app directory.  After going into  the directory:

`first-app-lesson-00`

and running npm install, this is what I see:
```
%npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: angular.io-example@0.0.0
npm ERR! Found: @angular/common@17.0.0
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"17.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^16.0.0" from angular-in-memory-web-api@0.16.0
npm ERR! node_modules/angular-in-memory-web-api
npm ERR!   angular-in-memory-web-api@"~0.16.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /Users/7stud/.npm/_logs/2024-01-05T01_04_50_686Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: /Users/7stud/.npm/_logs/2024-01-05T01_04_50_686Z-debug-0.log
```

If the angular team can't produce a hello world app that works without error, then angular is not for me.  Goodbye.

**Comment by Tillern** [comment] 2024-01-18 17:30
Option 2 worked for me npm install --force

**Comment by ChrisMSaltire** [comment] 2024-01-18 17:36
How do we get some attention on this? It is absurd that the very first beginner example Angular is putting forward is non-functional out of the box.

**Comment by MarkTechson** [comment] 2024-01-18 19:13
> How do we get some attention on this? It is absurd that the very first beginner example Angular is putting forward is non-functional out of the box.

Sorry that this is causing frustration. We are working on tracking down a solution for this dependency error that's happening.

The `first-app-lesson-01` can run if you try one of the options listed above and as an alternative, you can also do this lesson in the browser on angular.dev:

https://angular.dev/tutorials/first-app

**Comment by MarkTechson** [comment] 2024-01-18 22:37
Quick update - we have a [PR](https://github.com/angular/angular/pull/53979#pullrequestreview-1830657518) open to address the infra-changes that should fix this issue.

Stay tuned.

**Comment by GraemeHedges** [comment] 2024-01-25 21:08
Trying this this evening and seeing the same errors as all previous posters.

That PR has been closed but it looks like those changes have gone in, be useful to know if anyone else is seeing these errors following those changes.

**Comment by JeanMeche** [comment] 2024-01-25 21:44
Changes haven't been deployed yet !

**Comment by MarkTechson** [comment] 2024-01-25 21:51
> The `first-app-lesson-01` can run if you try one of the options listed above and as an alternative, you can also do this lesson in the browser on angular.dev:
> 
> https://angular.dev/tutorials/first-app

These changes will go out in the next minor release but I understand that this is frustrating. As an alternative for now the first-app-lesson-01 can be run if you try one of the options listed above or you can also do this lesson in the browser on angular.dev:

https://angular.dev/tutorials/first-app

Thank you for your patience on this one.

**Comment by GraemeHedges** [comment] 2024-01-25 22:18
Thanks both, I will wait - I'd prefer to work locally - where can I follow the releases?

**Comment by AndrewH2O** [comment] 2024-02-14 14:31
Not a very good introduction to angular unfortunately.

Option 1 above fails with:
```
npm ERR! While resolving: @angular-devkit/build-angular@17.1.3
npm ERR! Found: protractor@3.3.0
npm ERR! node_modules/protractor
npm ERR!   dev protractor@"^3.3.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peerOptional protractor@"^7.0.0" from @angular-devkit/build-angular@17.1.3
npm ERR! node_modules/@angular-devkit/build-angular
npm ERR!   dev @angular-devkit/build-angular@"^17.1.3" from the root project


```
Option 2 works but there are many critical errors which the npm audit doesn't fix.

I note that we are now on @angular-devkit/build-angular@17.1.3 compared to @angular-devkit/build-angular@17.0.0 are these more regressions? 
Any eta on the fixes?

**Comment by mindblower23** [comment] 2024-03-03 11:09
I can't install the first-app, too. For me after downloading, the root folder only contains the "src" folder and no "package.json" at all. So "npm install" states:

npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path C:\Users\me\Downloads\first-app_01-hello-world/package.json
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\me\Downloads\first-app_01-hello-world\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in: C:\Users\Harald.Salaun\AppData\Local\npm-cache\_logs\2024-03-03T11_07_17_664Z-debug-0.log

**Comment by stuartjp** [comment] 2024-03-13 01:44
I had the same issues trying out the 'Try it' tutorial. Didn't want to use --force as it seems to defeat the purpose of learning about how everything is supposed to work.

**I got it to work by altering the package.json file to alter:**
1) all the "@angular/..." versions in  dependacies & devDependencies  to my (presumably?) latest version "17.2.3"
2) updated "typescript" to "~5.2.2"
3) removed "angular-in-memory-web-api": "^0.16.0" from dependencies
4) **ran in terminal**: npm i angular-in-memory-web-api
          - This adds in :    "angular-in-memory-web-api": "^0.17.0",
          The project seems to work without this but I presume it is there for a reason?
5) ng i
6) ng serve

hope this helps someone.

**Comment by sheariley** [comment] 2024-05-08 04:48
I tried to follow the tutorial and found that the package.json file is entirely missing from the downloaded zip file on the first page of the hello world tutorial.  Seems like post-release testing needs some work.

**Comment by vincent-bru** [comment] 2024-05-19 15:34
> in package.json I changed
> 
> ```
>     "typescript": "~4.9.3"
> ```
> 
> to
> 
> ```
>     "typescript": "~5.2"
> ```
> 
> reran `npm i`

This worked

Also, do not install angular localy, somehow it is better to keep -g

**Comment by JeanMeche** [comment] 2024-10-08 16:22
Should be fixed now.

**Closed by JeanMeche** 2024-10-08 16:22 UTC
Labels: area: dev-infra, P3, area: devtools, area: docs
