### ISSUE TITLE
Unexpected template type-checking error from Angular 9 upgrade

### ISSUE THREAD

**Issue by msorens** [angular/angular#34548] opened 2019-12-23 18:12 UTC
# 🐞 bug report

### Affected Package

 Unknown

### Is this a regression?

 Yes, the previous version in which this bug was not present was 8.2.14

### Description

Working through issues upgrading from 8.2 to 9.0RC. I understand there is now template type-checking (woot!) but could use an assist figuring out what an error is trying to tell me: 
```
ASSERTION ERROR: Should be one of Element but got ElementContainer.
```
The stack trace gives me one clue where to look (ProjectDetailsComponent_section_25_ng_container_2_Template (ng:///ProjectDetailsComponent.js:288:5)) but how do I go from that to something in my html file? I only have 2 `<section>` elements, not 25, for instance. And not sure what `ng_container` refers to... Is there any way I can see that intermediate file (ProjectDetailsComponent.js) ?

## 🔬 Minimal Reproduction
While I am not able to create a minimal reproduction, I believe my [actual codebase](https://github.com/chef/automate/tree/ms/angular-9) (which is open-source) is sufficient to demonstrate the issue.

```
cd components/automate-ui
npm install
make unit | grep -v "does not exist in the state"
```

(That grep is just to filter out some unrelated noise.)

There are more than a dozen instances of the above error occurring.

## 🔥 Exception or Error
<pre><code>HeadlessChrome 79.0.3945 (Mac OS X 10.14.6) ProjectDetailsComponent when there are rules enables delete-rule button when a rule has edits pending FAILED
	Error: ASSERTION ERROR: Should be one of Element but got ElementContainer
	    at throwError (http://localhost:9876/_karma_webpack_/vendor.js:62870:11)
	    at assertEqual (http://localhost:9876/_karma_webpack_/vendor.js:62824:9)
	    at assertNodeOfPossibleTypes (http://localhost:9876/_karma_webpack_/vendor.js:64956:5)
	    at instantiateAllDirectives (http://localhost:9876/_karma_webpack_/vendor.js:74505:26)
	    at createDirectivesInstances (http://localhost:9876/_karma_webpack_/vendor.js:73815:5)
	    at ɵɵelementContainerStart (http://localhost:9876/_karma_webpack_/vendor.js:83135:9)
	    at ProjectDetailsComponent_section_25_ng_container_2_Template (ng:///ProjectDetailsComponent.js:288:5)
	    at executeTemplate (http://localhost:9876/_karma_webpack_/vendor.js:73772:9)
	    at renderView (http://localhost:9876/_karma_webpack_/vendor.js:73572:13)
	    at TemplateRef_.createEmbeddedView (http://localhost:9876/_karma_webpack_/vendor.js:76905:17)</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.0.0-rc.8
Node: 12.13.1
OS: darwin x64

Angular: 9.0.0-rc.8
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-rc.8
@angular-devkit/build-angular     0.900.0-rc.8
@angular-devkit/build-optimizer   0.900.0-rc.8
@angular-devkit/build-webpack     0.900.0-rc.8
@angular-devkit/core              9.0.0-rc.8
@angular-devkit/schematics        9.0.0-rc.8
@angular/cdk                      9.0.0-rc.7
@angular/material                 9.0.0-rc.7
@ngtools/webpack                  9.0.0-rc.8
@nguniversal/express-engine       8.2.6
@schematics/angular               9.0.0-rc.8
@schematics/update                0.900.0-rc.8
rxjs                              6.5.4
typescript                        3.6.4
webpack                           4.41.2
</code></pre>

**Anything else relevant?**
I originally posted this on 2019.12.19 on gitter (https://gitter.im/angular/angular) and @alxhub responded: _"That sounds like a bug in our compiler, @msorens. Can you send me your template?"_

I thought it would be better to keep all the info on this together, so opening this issue instead of continuing on gitter.

Here is one of the template files in question:

https://github.com/chef/automate/blob/3303d0d3bee01e2bb9a1427f967c822e086f5fba/components/automate-ui/src/app/pages/project/details/project-details.component.html

(Just in case that branch becomes inaccessible, the file is unchanged from master:
https://github.com/chef/automate/blob/master/components/automate-ui/src/app/pages/project/details/project-details.component.html)

**Comment by msorens** [comment] 2020-01-13 23:07
Just an FYI, that I did a fresh upgrade from 8.2 to the latest 9.0RC and the issue is still occurring. (I have updated my version info above.)

**Comment by alxhub** [comment] 2020-01-21 23:43
I'm guessing this is i18n related. @AndrewKushnir have you seen this before?

**Comment by AndrewKushnir** [comment] 2020-01-22 00:34
@alxhub I had a quick look at the template and it seems like there are no i18n attrs there.

@msorens, as you pointed out, the error is being thrown from the `ProjectDetailsComponent_section_25_ng_container_2_Template` function, which indicates that the issue is somewhere [in this block](https://github.com/chef/automate/blob/3303d0d3bee01e2bb9a1427f967c822e086f5fba/components/automate-ui/src/app/pages/project/details/project-details.component.html#L56-L108). I didn't find any particular code that might trigger the error. Since there is a lot of logic in that template, could you please try to narrow down the part of template that is causing a problem (by removing bits of template until the error goes away and eventually find a minimum possible template that would trigger that error)? Having a smaller repro would help us investigate this issue further.

Thank you.

**Comment by alxhub** [comment] 2020-01-28 23:43
@msorens, can you provide a branch (that's upgraded to Ivy) with instructions to reproduce the problem. Ideally that would involve running `ngc` directly and not the `ng build` wrapper, but I can work with either.

**Comment by msorens** [comment] 2020-01-29 01:48
Sorry, @AndrewKushnir, I did not see your response from a week ago. I will work on addressing both your request and that of @alxhub. Thank you both!

**Comment by msorens** [comment] 2020-01-29 04:38
I have re-run the upgrade steps and the necessary tweaks (a couple compilation errors and lint fixes necessary) to bring my state up to the latest release candidate (9.0.0-rc.10), and I have confirmed the error is still present. 

@alxhub I was not clear if you were seeking a smaller repro (similar to @AndrewKushnir has requested) or not. I will work on that, but in the meantime [my just refreshed branch](https://github.com/chef/automate/tree/ms/angular-9) is available if you are able to examine the full project.
Once downloaded, you can reproduce the errors with this:
```
cd components/automate-ui
ng test
```

**Comment by msorens** [comment] 2020-02-03 17:03
I have whittled down the suspect template file to this single line that still manifests the error:
```
<ng-container *ngIf="true">Stuff</ng-container>
```
I have pushed a commit on my [branch](https://github.com/chef/automate/tree/ms/angular-9) that includes that template change, plus added a couple `fdescribe` and `fit` calls so `ng test` runs just a single test.

Here again are the instructions for showing the error:
```
cd components/automate-ui
ng test
```

A couple other notes:
 * I am seeing the error under discussion on two templates: the other one also uses an `ng-container`.
 * A quick search of my code base shows dozens of other uses of `ng-container`, so it is not totally failing on that element.

**Comment by AndrewKushnir** [comment] 2020-02-05 23:25
Hi @msorens,

Thank you for additional information and instructions on how to reproduce the problem.

I performed further investigation and found out that the problem was caused by the fact that you have a mock component with `ng-container` selector defined in [testing module here](https://github.com/chef/automate/blob/ms/angular-9/components/automate-ui/src/app/pages/project/details/project-details.component.spec.ts#L100). In this case during component/directive matching at runtime (the process which finds which directives/components should be initialized for a given node), the `<ng-container>` is matched against that mock component (which is supposed to become component's host node). However this is not allowed (since only elements might become hosts for components), the assert fails and you see the error message. I believe it was not functioning as expected in View Engine as well, but there was no error thrown.

Removing the line that declares mock component with `ng-container` selector resolves the problem. Please try to remove that line, test your app once again and let us know if everything works as expected now.

Thank you.

**Comment by msorens** [comment] 2020-02-06 18:02
Thank you for the update! I should be able to test that later today. 🤞

**Comment by kara** [comment] 2020-02-06 22:41
We shouldn't be supporting the use case for `ng-container` as a component, so this behavior is working as intended. That said, we should throw a clearer error message (rather than relying on a framework-specific assertion), so let's keep this issue open.

**Comment by msorens** [comment] 2020-02-07 03:45
Success--looks like it was indeed a PEBKAC. 😁 

Thank you @AndrewKushnir for identifying the problem in my code!

<img width="754" alt="image" src="https://user-images.githubusercontent.com/6817500/73999288-1b584080-4919-11ea-913b-228745a3eb72.png">

**Comment by kara** [comment] 2020-02-07 19:47
Since @AndrewKushnir created #35240 to track the error, I'm going to close this one.

**Closed by kara** 2020-02-07 19:47 UTC
Labels: comp: compiler, comp: ivy, freq2: medium, severity3: broken, type: bug/fix
