### ISSUE TITLE
--stats-json generates broken output

### ISSUE THREAD

**Issue by nosovk** [angular/angular#33427] opened 2019-10-27 01:37 UTC
This issue probably caused because if ivy enabled

### Is this a regression?

Yes, when ivy was not enabled feature was working correctly

### Description

1. before ivy there was 2 stats.json files present: `stats-es5.json` and `stats-es2015.json`
Now only `stats-es2015.json` geneated
2. In newly created `stats-es2015.json` there is a link to broken polyfill bunlde file, like: `polyfills-es5-es2015.hash.js`
there are two different files produced during the build: `polyfills-es5.hash.js` and `polyfills-es2015.hash.js`
but `stats-es2015.json` refers to nonexistant file
## Minimal Reproduction
Create new project with ivy enabled, run `ng build --prod --stats-json`
inspect produced bundle - es5 report is missing
try to run `webpack-bundle-analyzer stats-es2015.json --mode static --report webpack.html`
it will fail becouse of refference to missing file.

## 🌍  Your Environment

**Angular Version:**
<pre>Angular CLI: 8.3.9
Node: 10.16.3
OS: linux x64
Angular: 8.2.10
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.9
@angular-devkit/build-angular     0.803.9
@angular-devkit/build-optimizer   0.803.9
@angular-devkit/build-webpack     0.803.9
@angular-devkit/core              8.3.9
@angular-devkit/schematics        8.3.9
@angular/cli                      8.3.9
@ngtools/webpack                  8.3.9
@schematics/angular               8.3.9
@schematics/update                0.803.9
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2
</code></pre>

**Comment by trotyl** [comment] 2019-10-27 02:33
Duplicate of https://github.com/angular/angular-cli/issues/15915 (and wrong repo)

**Comment by AndrewKushnir** [comment] 2019-10-28 06:02
Hi @nosovk, as @trotyl mentioned, this issue looks like a duplicate of angular/angular-cli#15915. Please refer to that issue for additional information and further updates. Thank you.

**Closed by AndrewKushnir** 2019-10-28 06:02 UTC
