### ISSUE TITLE
ngcc - failing to compile dependencies and own libraries with secondary entries

### ISSUE THREAD

**Issue by klemenoslaj** [angular/angular#38296] opened 2020-07-30 14:40 UTC
# 🐞 bug report

### Affected Package

`@angular/compiler-cli` - ngcc

### Description

In a medium sized monorepo, containing libraries with secondary entries the `ngcc` seems to fail to properly compile local libraries. The example exception is in the `Exception or Error` section.

The triggered command:
```
main-ngcc.js
    --properties es2015 browser module main
    --first-only
    --create-ivy-entry-points
    --source <PATH-TO-NODE_MODULES>
    --tsconfig ./tsconfig.base.json
```

Current workaround:
- Trigger `ngcc` before any library is built
- Build all the libraries
- Trigger `ngcc` on `./dist` instead of `node_modules`

## 🔬 Minimal Reproduction

I tried to create small reproduction and didn't succeed. If the above description is not enough I will try once again with creating the same structure as we have in our monorepo - it's a bigger effort.

## 🔥 Exception or Error
<pre><code>Compiling @angular/core : es2015 as esm2015
Compiling @angular/cdk/keycodes : es2015 as esm2015
Compiling @angular/animations : es2015 as esm2015
Compiling apollo-angular-link-persisted : es2015 as esm2015
Compiling @demo/library1/secondary1 : es2015 as esm2015
Compiling @angular/compiler/testing : es2015 as esm2015
Compiling @angular/service-worker/config : es2015 as esm2015
Compiling @angular/cdk/observers : es2015 as esm2015
Compiling @angular/common : es2015 as esm2015
Compiling @angular/animations/browser : es2015 as esm2015
Compiling @angular/cdk/collections : es2015 as esm2015
Compiling apollo-angular : es2015 as esm2015
Compiling @angular/cdk/platform : es2015 as esm2015
Compiling @angular/cdk/bidi : es2015 as esm2015
Compiling @angular/platform-browser : es2015 as esm2015
Compiling @angular/forms : es2015 as esm2015
Compiling @angular/cdk/a11y : es2015 as esm2015
Compiling @angular/platform-browser/animations : es2015 as esm2015
Compiling @angular/cdk/scrolling : es2015 as esm2015
Compiling @angular/common/http : es2015 as esm2015
Compiling @angular/material/core : es2015 as esm2015
Compiling @angular/cdk/portal : es2015 as esm2015
Compiling @angular/router : es2015 as esm2015
Compiling @angular/material/button : es2015 as esm2015
Compiling @angular/cdk/overlay : es2015 as esm2015
Compiling @angular/material/form-field : es2015 as esm2015
Compiling @angular/material/icon : es2015 as esm2015
Compiling apollo-angular-link-http-common : es2015 as esm2015
Compiling @angular/flex-layout/core : es2015 as esm2015
Compiling @angular/material/divider : es2015 as esm2015
Compiling apollo-angular-link-http : es2015 as esm2015
Compiling @ag-grid-community/angular : es2015 as esm2015
Compiling @angular/material/select : es2015 as esm2015
Compiling @demo/library1 : es2015 as esm2015
Compiling @angular/cdk/text-field : es2015 as esm2015
Compiling @ng-action-outlet/core : es2015 as esm2015
Compiling @angular/flex-layout/extended : es2015 as esm2015
Compiling @angular/flex-layout/flex : es2015 as esm2015
Compiling @angular/flex-layout/grid : es2015 as esm2015
Compiling @angular/material/dialog : es2015 as esm2015
Compiling @angular/material/input : es2015 as esm2015
Compiling @angular/flex-layout : es2015 as esm2015
Compiling @angular/material/toolbar : es2015 as esm2015
Compiling @angular/material/datepicker : es2015 as esm2015
Compiling @angular/material/button-toggle : es2015 as esm2015
Compiling @angular/material/checkbox : es2015 as esm2015
Compiling @angular/material/chips : es2015 as esm2015
Compiling @angular/material/autocomplete : es2015 as esm2015
Compiling @angular/material/progress-spinner : es2015 as esm2015
Compiling @angular/material/list : es2015 as esm2015
Compiling @angular/material/badge : es2015 as esm2015
Compiling @angular/elements : es2015 as esm2015
Compiling @angular/material/sidenav : es2015 as esm2015
Compiling @angular/cdk/layout : es2015 as esm2015
Compiling @demo/library1/secondary2 : es2015 as esm2015
Compiling @demo/library2/some-pipe : es2015 as esm2015
Compiling @demo/library3 : es2015 as esm2015
Compiling @angular/cdk/tree : es2015 as esm2015
Compiling @angular/material/menu : es2015 as esm2015
Compiling @angular/material/card : es2015 as esm2015
Compiling @angular/material/tree : es2015 as esm2015
Compiling @demo/library2/entry/fancy-component : es2015 as esm2015
Compiling @demo/library2/entry/another-component : es2015 as esm2015
Compiling @demo/library3 : es2015 as esm2015
Compiling @demo/library2/entry/boring-component : es2015 as esm2015
Compiling @demo/library2/entry/yet-another-component : es2015 as esm2015
Error: Failed to compile entry-point @demo/library3 (es2015 as esm2015) due to compilation errors:

dist/library2/some-pipe/some-pipe.module.d.ts:1:22 - error NG6002: Appears in the NgModule.imports of Library3Module, but could not be resolved to an NgModule class.

This likely means that the dependency (@demo/library2/some-pipe) which declares SomePipeModule has not been processed correctly by ngcc.

1 export declare class SomePipeModule {
                       ~~~~~~~~~~~~~~~~~
</code></pre>


## 🌍  Your Environment

<pre><code>
Angular CLI: 10.0.2
Node: 12.18.2
OS: darwin x64

Angular: 10.0.3
... animations, common, compiler, compiler-cli, core
... platform-browser, platform-browser-dynamic
Ivy Workspace: <error>

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1000.2
@angular-devkit/build-angular      0.1000.2
@angular-devkit/build-ng-packagr   0.1000.2
@angular-devkit/build-optimizer    0.1000.2
@angular-devkit/build-webpack      0.1000.2
@angular-devkit/core               10.0.2
@angular-devkit/schematics         10.0.2
@angular/cli                       10.0.2
@angular/pwa                       0.1000.2
@ngtools/webpack                   10.0.2
@schematics/angular                10.0.2
@schematics/update                 0.1000.2
ng-packagr                         10.0.1
rxjs                               6.5.5
typescript                         3.9.6
webpack                            4.43.0
</code></pre>

**Comment by JoostK** [comment] 2020-07-30 15:11
I suspect the issue is somewhere here:

https://github.com/angular/angular/blob/6b311552f04e3b35f1089145c0a44b93d9aa2fdd/packages/compiler-cli/ngcc/src/entry_point_finder/targeted_entry_point_finder.ts#L119-L148

This logic attempts to derive a package path (e.g. `@angular/common`) from an entry-point path (e.g. `@angular/common/http`) and if this is done incorrectly, strange errors such as the one reported may occur. I notice some logic around `node_modules` there which is not the case with the `dist` folders, so I'm guessing that's the area to focus on.

> The triggered command:
> ```
> main-ngcc.js
>    --properties es2015 browser module main
>    --first-only
>    --create-ivy-entry-points
>    --source <PATH-TO-NODE_MODULES>
>    --tsconfig ./tsconfig.base.json
>```

@klemenoslaj Who triggers this command, and when? It does not look like the invocation the CLI would make, so I assume it's in a custom script?

**Comment by klemenoslaj** [comment] 2020-07-30 16:13
> This logic attempts to derive a package path (e.g. @angular/common) from an entry-point path (e.g. @angular/common/http) and if this is done incorrectly, strange errors such as the one reported may occur. I notice some logic around node_modules there which is not the case with the dist folders, so I'm guessing that's the area to focus on.

Having no in depth knowledge here, but that is the guess I was having too.

> Who triggers this command, and when? It does not look like the invocation the CLI would make, so I assume it's in a custom script?

This error is thrown from `ng build` of application, where `ngcc` is triggered automatically by the corresponding builder.
I extracted the command from CLI directly 1 to 1 of what was executed in attempt to reproduce the issue without CLI: https://github.com/angular/angular-cli/blob/1396ed4533d04a434b943eab48e0c6eaa4740c95/packages/ngtools/webpack/src/ngcc_processor.ts#L118.

There are subtle differences with my reported command to the latest CLI version which now looks like:
```ts
[
  require.resolve('@angular/compiler-cli/ngcc/main-ngcc.js'),
  '--source', /** basePath */
  this._nodeModulesDirectory,
  '--properties', /** propertiesToConsider */
  ...this.propertiesToConsider,
  '--first-only', /** compileAllFormats */
  '--create-ivy-entry-points', /** createNewEntryPointFormats */
  '--async',
  '--tsconfig', /** tsConfigPath */
  this.tsConfigPath,
  '--use-program-dependencies',
]
```

but before looked like:
```ts
[
  require.resolve('@angular/compiler-cli/ngcc/main-ngcc.js'),
  '--source',
  this._nodeModulesDirectory,
  '--properties',
  ...this.propertiesToConsider,
  '--first-only',
  '--create-ivy-entry-points',
  '--async',
  '--tsconfig',
  this.tsConfigPath,
]
```

The `--use-program-dependencies` flag was added (and I omitted the async as it's default, right?)

**Comment by JoostK** [comment] 2020-07-30 17:02
> There are subtle differences with my reported command to the latest CLI version which now looks like:
> 
> ```ts
> [
>   require.resolve('@angular/compiler-cli/ngcc/main-ngcc.js'),
>   '--source', /** basePath */
>   this._nodeModulesDirectory,
>   '--properties', /** propertiesToConsider */
>   ...this.propertiesToConsider,
>   '--first-only', /** compileAllFormats */
>   '--create-ivy-entry-points', /** createNewEntryPointFormats */
>   '--async',
>   '--tsconfig', /** tsConfigPath */
>   this.tsConfigPath,
>   '--use-program-dependencies',
> ]
> ```
> 
> but before looked like:
> 
> ```ts
> [
>   require.resolve('@angular/compiler-cli/ngcc/main-ngcc.js'),
>   '--source',
>   this._nodeModulesDirectory,
>   '--properties',
>   ...this.propertiesToConsider,
>   '--first-only',
>   '--create-ivy-entry-points',
>   '--async',
>   '--tsconfig',
>   this.tsConfigPath,
> ]
> ```
> 
> The `--use-program-dependencies` flag was added (and I omitted the async as it's default, right?)

I see, I was expecting to see a `--target` option as well, but realize now that the invocation you shared is the asynchronous invocation that runs when starting the CLI. The `--use-program-dependencies` is new in 10.1 and therefore not yet released, and `--async` is indeed the default. So it was just me being confused. That `--use-program-dependencies` does influence how entry-points are scanned, but I'm not sure whether it will have the same issue.

I can't say for sure yet whether we will be able to reproduce, but with the above information I'm hopeful we will be.

**Comment by klemenoslaj** [comment] 2020-07-30 17:16
I think I even tried the `--use-program-dependencies` flag because reading the `--help` it sounded like something that could influence the outcome.

Please let me know if you need me to give the reproduction another try. Completely replicating the monorepo structure should hopefully do the trick, unless it's some extreme edge case triggered by something specific.

**Comment by klemenoslaj** [comment] 2020-08-04 15:20
@JoostK was reproduction possible or should I try to reproduce again?

This is extremely problematic right now and there is nothing we can do about it. Now issue is popping out again despite my workaround.

**Comment by JoostK** [comment] 2020-08-05 13:14
@klemenoslaj I haven't yet looked into it, so there's no update really.

Can you share your paths mapping configuration? The packages in `dist` are probably accessed using path-mappings, and these matter in correct computation of package paths.

**Comment by klemenoslaj** [comment] 2020-08-05 13:43
@JoostK I just managed to reproduce it the exact same way and figured out what was the problem and to me it looks like it's on our side.

The main entry point of one of our libraries was missing in the path mapping. After adding it everything seems fine so far, but I am still testing it and will report back.

The point is that this library has empty main entry point while exposing a lot of secondary entry points.
Developer thought that omitting the main entry point from paths mapping is not gonna be a problem.

This was hard to detect due to the huge amount of libraries and secondary entry points configured in paths mapping.

---

Do you think this is something `ngcc` should know how to come with?

**Comment by JoostK** [comment] 2020-08-05 14:27
@klemenoslaj not needing a path mapping for an empty primary entry-point sounds like a fair assumption to make, indeed. Unfortunately this does introduce issues for ngcc, which needs this path-mapping to correctly interpret the secondary entry-points as belonging to a certain package. Without the path mapping, the secondary entry-point is processed independently and this causes things to break. I totally agree with you that this is hard to debug, as there's nothing that indicates where the root cause of the issue could be (even the relation to path mappings is not at all obvious).

I am not sure whether ngcc can do something to detect this situation. If it were able to, I expect it to also be able to just work without the path mappings. Possibly the logic in `computePackagePath` can be completely revised to work without path mappings, but I'm really not sure whether that could work like that.

**Comment by klemenoslaj** [comment] 2020-08-05 16:41
Hmm, wouldn't it be fair to assume that a package with multiple `/` is a secondary entry point since `npm` package name (main entry) anyway cannot contain multiple `/`? At the very least you could detect that the secondary entry point is an orphan in paths mapping and display a warning? 🤔

This might work unless you try to cover any use case, like if people would name their secondary entries somehow unconventionally, like with `-` for some reason (would that even work? guess so...)?

**Comment by JoostK** [comment] 2020-08-05 16:56
Yeah, so that approach might be one alternative that doesn't rely on the path mappings information. I guess it's a bit tricky, though, as all we got is a single absolute path (so slashes are somewhat meaningless) and the `package.json` file of secondary entry-points doesn't necessarily have a `name`, so we can't always start from there. That's why we currently use the path mappings to figure out where in the path the package boundaries are, assuming that there is indeed a path mapping for the package.

An alternative could be to look into parent folders and check for `package.json` files. It is however possible that a parent directory does not contain a `package.json` file, so we'd need to traverse all the way up. This becomes problematic when `dist` is next to the project's `package.json` file, as that file will then be considered where it shouldn't have been. I think this can be solved by stopping at the `package.json` file that does have a `name`  _and_ that name is a root name, i.e. there are no slashes at all or a single slash in case of a scoped package. I _think_ that approach might work without needing the path mappings, but I may be missing something here.

**Comment by klemenoslaj** [comment] 2020-08-05 17:47
Hmm, I understand.

One more thing, with `ng-packagr` secondary entry point can be created by either creating a `pakcage.json` with `ngPackage` config or alternatively with `ng-package.json`. Maybe something to take in consideration if you think of alternative strategies.

I am fine with closing this issue now. Will continue testing tomorrow and observing out pipelines if something breaks again and can follow up in this issue (if it won't get locked).

I guess the minimal thing that could be done is to document the relationship between the paths mapping and ngcc?

**Comment by JoostK** [comment] 2020-08-05 17:49
Let's keep it open as this is a legitimate case that others might run into as well.

**Comment by diminutivesloop** [comment] 2020-08-14 15:16
This appears to be biting us as well. I develop an internal Angular library for our company that exports components via secondary entry points and I'm trying to update it to support Angular 9 but I'd like to keep the secondary entry points so the upgrade isn't a breaking change.

**Comment by JoostK** [comment] 2020-08-14 15:40
@diminutivesloop there shouldn't be any issue to retain the secondary entry-points. In this particular case, the path mapping for the primary entry-point was missing, is that the same for you? What's the exact version you're using?

**Comment by diminutivesloop** [comment] 2020-08-14 16:21
Ah sorry I missed that in the discussion. I'm building the library with Angular 8.3.26 and the consuming application is at Angular 9.1.12.

Also by "path mapping" are you referring to the `compilerOptions.path` entry in `tsconfig.json` or something else? I checked that and my library has entries for the empty primary entry point but none for the secondary entry points.

**Comment by JoostK** [comment] 2020-08-14 16:31
@diminutivesloop Yes, I indeed meant `compilerOptions.paths` (notice the plural `s` but I guess that was a typo). An entry for the primary entry-point should be sufficient to avoid the particular issue as reported here, but maybe there's something else acting up. I can't think of anything from the the top of my head, though, so I'm afraid I can't give you any pointers at the moment. If you are able to share a reproduction then I can look into it.

**Comment by alan-agius4** [comment] 2023-02-16 09:04
Closing as NGCC will be removed in the upcoming major version.

**Closed by alan-agius4** 2023-02-16 09:04 UTC
Labels: type: bug/fix, freq1: low, workaround2: non-obvious, state: confirmed, P5
