### ISSUE TITLE
OnPush change detection doesn't work for outputs emitted from lifecycle callbacks

### ISSUE THREAD

**Issue by sebek64** [angular/angular#24965] opened 2018-07-18 16:25 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

This issue is related to the closed issue https://github.com/angular/angular/issues/24690 for which I managed to create a simple repro case. Complete description follows.

When a component with OnPush change detection subscribes an output of a subcomponent, it works pretty well, unless this subcomponent emits values from the initialization lifecycle callbacks (ngOnInit, ngAfterViewInit). Then, no change detection is performed, and even calling changeDetectorRef.markForCheck() doesn't help. Only calling detectChanges() manually works.

Quite surprisingly, when the value is emitted from ngOnInit, it is shown in the interpolation strings, but not passed to subcomponents. On the other hand, ngAfterViewInit value is not used at all.

## Expected behavior

It should work out of the box, without the need to work with change detector manually. If this is not supported for some architectural reason, the documentation should contain a big warning about it.

## Minimal reproduction of the problem with instructions

I've prepared a git repo here: https://github.com/sebek64/angular-issue-repro

The initial commit is a plain angular-cli project. The next commit adds the repro code. Run via "yarn start", open the browser, and you should see output like this:

```
outer component value: "emitted value from ngOnInit"
inside subcomponent: ""
Button
```

When the button is clicked, the output changes to

```
outer component value: "Emitted value from button"
inside subcomponent: "Emitted value from button"
Button
```

## Environment

<pre><code>
Angular version: 6.0.9

Browser:
- [X] Chrome (desktop) version 67.0.3396.99
- [X] Firefox version 52.9.0
- Platform:  Linux
</code></pre>

**Comment by mlc-mlapis** [comment] 2018-07-18 17:01
@sebek64  ... do you have any problems with creating an online reproduction demo using https://stackblitz.com because it is much easier for everybody to look at it than to clone a repository, run CLI, ... and so on ... ?

**Comment by sebek64** [comment] 2018-07-18 17:10
@mlc-mlapis Well, actually no, just laziness :). So I'll prepare it. Initially, a few weeks ago, I started by creating an obvious demo online and failed, because it always worked as expected. So this time, I used more convenient tools for me.

So I try to copy everything into an online version and post a link. I suspect some race condition according to the behavior in the real-world project, so it may well be irreproducible in web-based tool.

**Comment by sebek64** [comment] 2018-07-18 17:17
Here is a web-based repro: https://stackblitz.com/edit/angular-gitter-egxquq

**Comment by manklu** [comment] 2018-07-18 17:19
@mlc-mlapis With stackblitz you can load the code direktly from GitHub.

https://stackblitz.com/github/sebek64/angular-issue-repro

**Comment by mlc-mlapis** [comment] 2018-07-18 17:21
@manklu ... yep, thanks, I forgot about this feature. 👍

**Comment by manklu** [comment] 2018-07-18 21:02
Yes, there is a problem with events during change detection. As workaround you can use something like this:

```javascript
Promise.resolve().then(() => this.valueChange.emit("emitted value from ngOnInit"));
```

Better than calling detectChanges() directly.

**Comment by trotyl** [comment] 2018-07-19 04:34
This should raise an `ExpressionChangedAfterItHasBeenCheckedError` error, not producing any error message is indeed a BUG.

**Comment by sebek64** [comment] 2018-07-19 11:33
So if I understand it correctly, the described scenario is not going to work, because the change detection mechanism is not designed to support it.

Based on the @manklu comment, I found another possible workaround - use "async = true" for EventEmitter, i.e., new EventEmitter<...>(true).

**Comment by manklu** [comment] 2018-07-19 20:56
If most events are emitted during change detection, this is the best solution.

**Comment by atscott** [comment] 2022-04-15 05:18
Closing as duplicate of #45612

**Closed by atscott** 2022-04-15 05:18 UTC
Labels: type: bug/fix, freq1: low, comp: core, state: confirmed, core: change detection, P3
