### ISSUE TITLE
:root css pseudo-class ignored in angular elements

### ISSUE THREAD

**Issue by ramirezmike** [angular/angular#32177] opened 2019-08-18 02:04 UTC
🐞 

### Affected Package

This might be related to @angular/elements or ViewEncapsulation in @angular/core

### Is this a regression?

No

### Description

Any styles or variables set in a [css pseudo-class ":root"
](https://developer.mozilla.org/en-US/docs/Web/CSS/:root) within an "angular element" (@angular/elements) stylesheet aren't applied. The root styles would apply on the <html> element in a typical website, but if you're trying to use an angular element to sandbox some structure/style/behavior in an element, if the styles happen to use :root it seems to have nothing to attach to, regardless of ViewEncapsulation setting.

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-elements-root-css-issue

In this stackblitz I made a custom element called "custom-hello" which is rendered with the <custom-hello> tag in index.html. In the component file, it's setup with the following styles:

`    :root {
      background-color: blue;
    }
    h1 {
      color: red;
    }`

Additionally, there's a css style in styles.css with the following:

`:root {
  background-color: rgb(87, 172, 87);
}`

This ends up showing red text (from h1 css inside angular element) against a green background (from the :root tag in styles.css) but ignores the blue background style rule on :root within the angular element.

Again, regardless of how I configure the angular element, anything I put in a :root style within the element doesn't apply.

![image](https://user-images.githubusercontent.com/1421719/63219208-d35f1a80-c13a-11e9-804f-76b9444a7e90.png)

![image](https://user-images.githubusercontent.com/1421719/63219213-e96cdb00-c13a-11e9-8c81-de0e3925cf1e.png)

**Comment by ramirezmike** [comment] 2019-08-19 14:32
Digging into the code a bit, I did find this in [packages/platform-browser/src/dom/shared_styles_host.ts](https://github.com/angular/angular/blob/184d2707256a41d6b3618331cbfb453d38b49d11/packages/platform-browser/src/dom/shared_styles_host.ts)

<pre>
 private _addStylesToHost(styles: Set<string>, host: Node): void {
    styles.forEach((style: string) => {
      const styleEl = this._doc.createElement('style');
      styleEl.textContent = style;
      this._styleNodes.add(host.appendChild(styleEl));
    });
  }
</pre>

which I suspect might be what's creating the <style> element in the scenario I created above. Doing something similar here in [this jsfiddle](https://jsfiddle.net/shcv4yd1/) if I include a :root style in the content, it does get applied once it's appended to the DOM (in this example, I have a "root" style that makes the background color blue), but the code above, if it is what's being used in angular elements, doesn't seem to behave the same when it comes to the :root pseudo-class. Not sure if I'm off track here, will update as I piece more things together.

**Comment by trotyl** [comment] 2019-08-26 03:04
Expected behavior, `:root` in a ShaodowRoot will not affect the global document, this is working as intended without even using Angular:

https://jsbin.com/pepeyahuru/edit?html,css,js,output

**Comment by gkalpak** [comment] 2020-06-02 21:02
Closing based on the discussion above.

**Closed by gkalpak** 2020-06-02 21:02 UTC
Labels: comp: elements
