### ISSUE TITLE
Angular >= 5.1.0-rc.0 regression in AOT compilation error reporting

### ISSUE THREAD

**Issue by Sky4CE** [angular/angular#20781] opened 2017-12-04 18:21 UTC
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When building with AOT I get very general error which is useless a bit more than completely.
![image](https://user-images.githubusercontent.com/9821633/33568706-0db78db0-d930-11e7-9b9b-190cb13bdcf6.png)

P.S.: Version 5.1.0-beta.2 shows proper error message in this particular case.

## Expected behavior

Error should describe root of the problem with proper stacktrace.

## Minimal reproduction of the problem with instructions
[reproduction repository](https://github.com/Sky4CE/angular-5-cli-barrels/tree/5.1.0-rc.0-regression) (make sure you're on `5.1.0-rc.0-regression` branch)
to run: `ng build --aot=true` or `ng build --prod`

## Environment

<pre><code>
Angular version: 5.1.0-rc.0 and 5.1.0-rc.1

 
For Tooling issues:
- Node version: 6.11.1
- Npm: 5.5.1
- Platform:  Windows10 x64

</code></pre>

**Comment by chuckjaz** [comment] 2017-12-05 06:17
@Sky4CE Can you produce a repository that reproduces the error? What was the text of the error you received in 5.1.0-beta-2 and how is it different than 5.1.0-rc.1?

Also, it would be more helpful if you included the entire text of the error instead of just a screen shot of part of it.

**Comment by Sky4CE** [comment] 2017-12-05 09:50
@chuckjaz , the point is that in 5.1.0-rc.0 and 5.1.0-rc.1 the text always the same regardless of error I have, it can be any error, it always states that it cannot find main app module factory while in beta-2 it was precise error about the problem, i.e. some parameters could not be resolved in constructor or some properties is private but used on template etc, and it points to exact file with problem: 
![image](https://user-images.githubusercontent.com/9821633/33600225-4bcb510a-d9b1-11e7-9cbf-02415ffa3d82.png)
Actually I have included the full text with error (for 5.1.0-rc.0 and 5.1.0-rc.1), the rest is just regular webpack metadata info about built html etc... the same as in beta-2. I have also tried 'verbose' logging and there was no additional useful info. I will prepare a repo later, right now I have no time, sorry.

**Comment by chuckjaz** [comment] 2017-12-05 21:55
I am not seeing the same thing. 

Can you create a repository I can clone that produces the error message you are seeing. I will then test this against 5.1.0-beta.1 and 5.1.0-rc.1 and see the difference.

BTW, In the future, please refrain from using images captures of your screen; pasting the text from the console is usually sufficient.

**Comment by Sky4CE** [comment] 2017-12-06 17:52
@chuckjaz I have prepared [reproduction repo](https://github.com/Sky4CE/angular-5-cli-barrels/tree/5.1.0-rc.0-regression) for you, it uses angular-cli and barrels system. In fact problem related to this bug #8581, I've found it when testing different kind of errors and current problem with insufficient error message appears with barrels bug. Please make sure you restoring `5.1.0-rc.0-regression` branch from my repo. Then just build it with aot either `ng build --aot=true` or `ng build --prod` to see error.

**Comment by Sky4CE** [comment] 2017-12-07 15:18
@chuckjaz , any progress on this? I saw v5.1.0 has been released, I tested it and saw that this bug didn't resolved, that's very disappointed. This situation force me to stay on 5.1.0-beta2

**Comment by Andrey-Pavlov** [comment] 2017-12-08 13:57
@Sky4CE THANK YOU!
**Rollback Angular to 5.1.0-beta.2** helped me to find AOT build fails and resolve mystery error message:

Error: ./src/app/main.ts
Module not found: Error: Can't resolve './app.module.ngfactory'

**Comment by earlyster** [comment] 2017-12-11 20:06
I also faced similar issue and using @Sky4CE and @Andrey-Pavlov solution to go back to 5.1.0-beta.2 helped show correct error message  due to issue with missing @Inject tag for locale. I wanted to give example I ran into. 

before:
    constructor(private locale: string) {
      super(locale);
    }

with 5.1 I received the aot strange error message 

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './app/app.browser.module.ngfactory' in 'src'
resolve './app/app.browser.module.ngfactory' in 'src'
  using description file: /package.json (relative path: ./src)
    Field 'browser' doesn't contain a valid alias configuration

after

    constructor(@Inject(LOCALE_ID) private locale: string) {
      super(locale);
    }

ERROR in Error: Can't resolve all parameters for NegativeNumberPipe in pipes/custom-pipe.pipe.ts: (?).

**Comment by alxhub** [comment] 2017-12-13 22:38
I've converted the reproduction into an `ngc_spec` test: https://github.com/alxhub/angular/commit/b86bf5ff25edf2afa94f50bd09bcd86de6620e59

The good news is that this test passes on `master`! So this issue is resolved, and I'll close it as such.

**Closed by alxhub** 2017-12-13 22:38 UTC
Labels: comp: core & compiler, freq3: high, severity5: regression, type: bug
