### ISSUE TITLE
Mock errors with custom objects is impossible

### ISSUE THREAD

**Issue by pakkk** [angular/angular#24781] opened 2018-07-06 15:33 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
I want to mock an error response. This error response contains a custom value like 'boolean', 'number', 'complex object like a JSON, etc.

## Expected behavior
Http Common mocks could provide any way to accept custom error objects

## Minimal reproduction of the problem with instructions
The current mock library does not provide any way to do that. If I try to do the following:

```
        const mockErrorResponse = {
            error: {
                code: 'ERR-001',
                message: 'Test error'
            },
            result: undefined
        };

        authorsService.getAuthor('1').subscribe(
            (response) => {

            },
            (error) => {
                expect(error.result).toBeUndefined();
                expect(error.error).toBeDefined();
                expect(error.error.code).toBe(mockErrorResponse.error.code);
                expect(error.error.message).toBe(mockErrorResponse.error.message);
            });

            http.expectOne(`${ENDPOINT_URL}/1`).flush(mockErrorResponse, {status: 490, statusText: 'Error'});
```
The test fails :(

## What is the motivation / use case for changing the behavior?
I would like to mock error response with custom objects.

## Environment
All the environments
<pre><code>
Angular version: 5.2.1

Browser:
- [x] Chrome (desktop) version XX
- [x] Chrome (Android) version XX
- [x] Chrome (iOS) version XX
- [x] Firefox version XX
- [x] Safari (desktop) version XX
- [x] Safari (iOS) version XX
- [x] IE version XX
- [x] Edge version XX
 
For Tooling issues:
- Node version: v8.11.3
- Platform:  Windows

**Comment by trotyl** [comment] 2018-07-06 16:17
Duplicate of https://github.com/angular/angular/issues/12857

**Closed** 2018-12-05 00:02 UTC
Labels: comp: testing
