### ISSUE TITLE
AoT error with `@Inject` and interface type

### ISSUE THREAD

**Issue by jeffbcross** [angular/angular#12631] opened 2016-10-31 18:52 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I have a constructor that uses `@Inject` to get a dependency, and references an interface for that the dep, [`constructor( @Inject(FirebaseApp) _fbApp: firebase.app.App)`](https://github.com/angular/angularfire2/blob/01b04a315053e7a6433e73c552754d9355b12a92/src/auth/firebase_sdk_auth_backend.ts#L30). When I compile the lib with `ngc`, I get this error:

```
Error: angularfire2/src/auth/firebase_sdk_auth_backend.ts:27:1: Error encountered in metadata generated for exported symbol 'FirebaseSdkAuthBackend':
 angularfire2/src/auth/firebase_sdk_auth_backend.ts:30:45: Metadata collected contains an error that will be reported at runtime: Expression form not supported.
  {"__symbolic":"error","message":"Expression form not supported","line":29,"character":44}
    at angularfire2/node_modules/@angular/tsc-wrapped/src/collector.js:514:27
    at Array.forEach (native)
    at validateMetadata (angularfire2/node_modules/@angular/tsc-wrapped/src/collector.js:502:42)
    at MetadataCollector.getMetadata (angularfire2/node_modules/@angular/tsc-wrapped/src/collector.js:374:17)
    at MetadataWriterHost.writeMetadata (angularfire2/node_modules/@angular/tsc-wrapped/src/compiler_host.js:111:51)
    at MetadataWriterHost.writeFile (angularfire2/node_modules/@angular/tsc-wrapped/src/compiler_host.js:103:19)
    at Object.writeFile (angularfire2/node_modules/typescript/lib/typescript.js:45364:132)
    at Object.writeFile (angularfire2/node_modules/typescript/lib/typescript.js:7597:14)
    at writeEmittedFiles (angularfire2/node_modules/typescript/lib/typescript.js:37854:20)
    at doEmit (angularfire2/node_modules/typescript/lib/typescript.js:37714:17)
```

If I change the type to `any`, compilation succeeds.

**Expected behavior**

I would expect to be able to reference an interface in a constructor in conjunction with `@Inject`.

**Minimal reproduction of the problem with instructions**

`ngc` this thing:

```typescript
import { NgModule, Inject, Injectable } from '@angular/core';
import { Http } from '@angular/http';

export interface Foo {}

@Injectable()
export class MyClass {
  constructor(@Inject(Http) http: Foo) {}
}

@NgModule({
  providers: [MyClass]
})
export class MyModule {}


```

* **Angular version:** 2.0.X

`@angular/compiler-cli@2.1.2`
`@angular/core@2.1.2`

* **Node (for AoT issues):** `node --version` =   

Node 5.10.1

**Comment by filipesilva** [comment] 2016-11-14 12:39
I am also experiencing this with `@types/angular-router` while upgrading an app with `@angular/upgrade/static`: https://github.com/angular/angular/issues/12860:
```
@Component({
  // ...
})
export class PhoneDetailComponent {
  // ...
  constructor(@Inject('$routeParams')
                $routeParams: angular.route.IRouteParamsService,
              phone: Phone) {
// ...
```

**Comment by psaussure** [comment] 2016-12-12 16:44
Same here by using
`@Inject(FirebaseApp) private firebaseApp: firebase.app.App` 

in my constructor. I confirm the @jeffbcross error and agree we shouldn't have to type using `any` to get the intended behavior.

**Comment by Kamshak** [comment] 2016-12-14 12:54
Getting the same thing 


```ts
export interface LazyMapsAPILoaderConfigLiteral {
  /**
   * The Google Maps API Key (see:
   * https://developers.google.com/maps/documentation/javascript/get-api-key)
   */
  apiKey?: string;

  /**
   * The Google Maps client ID (for premium plans).
   * When you have a Google Maps APIs Premium Plan license, you must authenticate
   * your application with either an API key or a client ID.
   * The Google Maps API will fail to load if both a client ID and an API key are included.
   */
  clientId?: string;
}


@Injectable()
export class LazyMapsAPILoader extends MapsAPILoader {
  private _scriptLoadingPromise: Promise<void>;

  constructor(
    @Inject(LAZY_MAPS_API_CONFIG) private _config: LazyMapsAPILoaderConfigLiteral,
  ) {
    super();
    this._config = this._config || {};
  }
//...
}
```

Fails with 

```

Failed on type {"filePath":"C:/Dev/trvlm8s/frontend/src/app/services/map/lazy-maps-api-loader.ts","name":"LazyMapsAPILoader"} with error Error: Error encountered resolving symbol value
s statically. Could not resolve type LazyMapsAPILoaderConfigLiteral (position 106:52 in the original .ts file), resolving symbol LazyMapsAPILoader in C:/Dev/trvlm8s/frontend/src/app/se
rvices/map/lazy-maps-api-loader.ts
Error: Error encountered resolving symbol values statically. Could not resolve type LazyMapsAPILoaderConfigLiteral (position 106:52 in the original .ts file), resolving symbol LazyMaps
APILoader in C:/Dev/trvlm8s/frontend/src/app/services/map/lazy-maps-api-loader.ts
```

**Comment by mmc41** [comment] 2016-12-28 18:30
Getting the same thing with a test component (AOT really miss a feature to exclude things):

```
export const TEST_CONFIG_TOKEN = new OpaqueToken('TestConfig');

export interface TestConfig {
  ...
};

@Component({
  template: `
    ...
  `
})
export class TestHostComponent {
  constructor(@Inject(TEST_CONFIG_TOKEN) public config: TestConfig) {
  }
}

```
The component is only used for testing but still AOT insist it should be defined in a module (otherwise another error will occur) and when processing AOT produces this error:

> ERROR in Error encountered resolving symbol values statically. Could not resolve type TestConfig (position 100:57 in the original .ts file), resolving symbol TestHostComponent ...

A complete blocker - could not be more serious. Only way forward is to delete all my advanced tests in order to get AOT working... NO

**Comment by DzmitryShylovich** [comment] 2016-12-28 18:46
>  Only way forward is to delete all my advanced tests

but u can just change type to any...

**Comment by mmc41** [comment] 2016-12-28 19:11
Thanks. This workaround works too. Annoying that I lose type safety here but at least I can proceed.

**Comment by DzmitryShylovich** [comment] 2016-12-28 19:14
> Annoying that I lose type safety

I believe u can do something like

```
export class TestHostComponent {
 config: TestConfig;
  constructor(@Inject(TEST_CONFIG_TOKEN) config: any) {
       this.config = <TestConfig>config;
  }
}
```

**Comment by mmc41** [comment] 2016-12-28 19:21
Yes indeed. I actually did exactly what you suggest with an additional comment referencing this bug to explain why I had to write bad code like this (it hurts to write 'any', to do type conversions and to add seemingly unnecessary lines of code ;-))

**Comment by oliverjanik** [comment] 2017-01-11 06:24
Wow this took a long time to find on Google. This is still happening in 2.4.1 using @ngtools/webpack npm package. Why does AOT even care about constructor arguments?

**Comment by chuckjaz** [comment] 2017-01-11 17:40
In this case it shouldn't. In general, if no `@Inject()` is provided, the type of the argument is the type of the instance created by the injector. This bug is tracking that non-reified (such as interfaces) are handled correctly by the collector and the static reflector.

**Comment by itsnotvalid** [comment] 2017-01-18 07:27
Provider Alias also depend of `@Inject()` which produces the same error.

**Comment by Meligy** [comment] 2017-01-21 12:54
I am having this as well.

This fails with AoT compiler in Angular CLI:

```
export function getWindow() { return window; }

@NgModule({
  declarations: [
    AppComponent,
    SimpleRouteComponent
  ],
  imports: [
    BrowserModule,
    FormsModule,
    HttpModule,
    AppRoutingModule
  ],
  providers: [
    {provide: 'window', useFactory: getWindow}
  ],
  bootstrap: [AppComponent]
})
export class AppModule {
  constructor(@Inject('window') w: Window) {
    console.log(w);
  }
}
```

With error:

> ERROR in Error encountered resolving symbol values statically. Could not resolve type Window (position 29:36 in the original .ts file), resolving symbol AppModule in /Users/Meligy/Code/github/Meligy/routing-angular-cli/src/app/app.module.ts

(More details in #14050)

The workaround (other than using `any` type in the constructor) was to create a dummy class type to trick the compiler, like:

```
@Injectable()
export class WindowWrapper extends Window {

}

export function getWindow() { return window; }

@NgModule({
  declarations: [
    AppComponent,
    SimpleRouteComponent
  ],
  imports: [
    BrowserModule,
    FormsModule,
    HttpModule,
    AppRoutingModule
  ],
  providers: [
    {provide: WindowWrapper, useFactory: getWindow}
  ],
  bootstrap: [AppComponent]
})
export class AppModule {
  constructor(w: WindowWrapper) {
    console.log(w);
  }
}
```

**Comment by gund** [comment] 2017-01-24 06:26
Still happening on v2.4.4. Trying to inject angular's `DOCUMENT` token:
```ts
import { Inject, Injectable } from '@angular/core';
import { DOCUMENT } from '@angular/platform-browser';

@Injectable()
export class MyService {
  constructor(
    @Inject(DOCUMENT) doc: Document // <-- This fails with ngc =(
  ) { }
}
```

**Comment by nosachamos** [comment] 2017-01-25 15:43
I'm also facing this attempting to inject Window. This is a major pain for real-world apps.

**Comment by dscheerens** [comment] 2017-02-23 07:27
Our team is facing the same issue. Rather than solving it by (temporarily) changing the type for such parameters to `any` we decided to create temporary 'companion' classes for these interfaces, so we don't loose type safety. For example:

```TypeScript

export interface MyConfig {
    foo: string;
    bar: boolean;
    baz(a: number): Date;
}

abstract class MyConfigClass {
    foo: string;
    bar: boolean;
    baz(a: number): Date;
}

@Injectable()
export class MyService {
    // Use MyConfigClass here instead of the MyConfig interface
    constructor(@Inject(MY_CONFIG_TOKEN) config: MyConfigClass) {
    }
}
```

This ain't pretty and has the drawback of having to repeat the interface definition again in the (abstract) class, but at least it is type safe.

**Comment by Meligy** [comment] 2017-02-23 10:20
@dscheerens see my version of this in this https://github.com/angular/angular/issues/12631#issuecomment-274260009. In TypeScript, a `class` can say it `extends` an `interface` rather than `implements` it, which does not require the `class` to repeat the `interface` members.

**Comment by dscheerens** [comment] 2017-02-23 10:33
I actually tried that, but that only seems to work for the Window interface. If I do this for my own interface, TypeScript is complaining that you cannot extend an interface:

`[ts] Cannot extend an interface 'MyConfig'. Did you mean 'implements'?`

I also tried to mimic the same behavior from the Window interface by doing this:

```TypeScript
declare var MyConfig: {
    prototype: MyConfig;
    new(): MyConfig;
}
```
That works to get rid of the *cannot extend an interface* message, but then NGC again gives me an error that it cannot resolve `MyConfig` :(

**Comment by Meligy** [comment] 2017-02-23 11:09
I [went for some help from Twitter](https://twitter.com/Meligy/status/834717355322126338) to find out why. Here's how to do it:

```
export interface RealInterface {
  title: string;
}

declare var RealInterface: {
    prototype: RealInterface;
    new(): RealInterface;
};

class FakeClass extends RealInterface {
}
```

[Live Sample](http://www.typescriptlang.org/play/index.html#src=export%20interface%20RealInterface%20%7B%0D%0A%20%20title%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Adeclare%20var%20RealInterface%3A%20%7B%0D%0A%20%20%20%20prototype%3A%20RealInterface%3B%0D%0A%20%20%20%20new()%3A%20RealInterface%3B%0D%0A%7D%3B%0D%0A%0D%0Aclass%20FakeClass%20extends%20RealInterface%20%7B%0D%0A%7D)

Thanks @dscheerens. I just learned something new :)

**Comment by dscheerens** [comment] 2017-02-23 11:12
@Meligy That works to for the extend stuff, but you'll end up with the initial AoT compilation error. So unfortunately it doesn't help as a workaround for the AoT issues.

**Comment by sod** [comment] 2017-02-23 13:25
It was nice if typescript would export something for interfaces the angular DI could work with. But until then you can use abstract instead of interface:

https://plnkr.co/edit/xzGHB54LVOb2If6mJfZl?p=preview

```typescript
abstract class AbstractFooService {
  abstract fooProperty: string;
}

class FooService implements AbstractFooService {
  fooProperty = 'string from service'
}

@Component({
  providers: [{provide: AbstractFooService, useClass: FooService}],
  selector: 'my-app',
  template: `{{ fooService.fooProperty }}`
})
export class AppComponent {
  constructor(public fooService: AbstractFooService) {
  }
}
```

The angular team does the same right now - e.g. the [ReflectorReader](https://github.com/angular/angular/blob/8b81bb1eb6b57afce4c384f7db2e734cab06421e/modules/%40angular/core/src/reflection/reflector_reader.ts#L13) provided by that [abstract token](https://github.com/angular/angular/blob/fcc1d17ccbf64c5eee0a0800cbeef753f5b838e8/modules/%40angular/compiler/src/jit/compiler_factory.ts#L54).

If everything is abstract in the abstract class, all that is left is an [empty function after transpilation to es5](http://www.typescriptlang.org/play/index.html#src=abstract%20class%20AbstractFooService%20%7B%0D%0A%20%20abstract%20fooProperty%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Aclass%20FooService%20implements%20AbstractFooService%20%7B%0D%0A%20%20fooProperty%20%3D%20'string%20from%20service'%0D%0A%7D).

**Comment by skdhir** [comment] 2017-03-01 22:07
Thanks @DzmitryShylovich for referencing my issue here.
Reading the comments, I'm not sure if you guys found the workaround / solution

**Comment by DzmitryShylovich** [comment] 2017-03-01 22:11
@skdhir for example:
```
private window: Window;
constructor(@Inject('Window') window: any) {
   this.window = window as Window;
}
```

**Comment by skdhir** [comment] 2017-03-01 22:20
Thanks @DzmitryShylovich, it definetly resolved the issue. 
As I'm using Window at many places... I have created a base class accepting type any, so I dont have to do this vodo programming everywhere

**Comment by skdhir** [comment] 2017-03-01 22:57
Now it compiles with warning:
WARNING in ./src/$$_gendir/app/app.module.ngfactory.ts
405:36-50 "export 'window' (imported as 'import1') was not found in '../../app/a
pp.module'

WARNING in ./src/$$_gendir/app/clientadmin/clientadmin.module.ngfactory.ts
197:36-50 "export 'window' (imported as 'import1') was not found in '../../../ap
p/clientadmin/clientadmin.module'

**Comment by matejamateusz** [comment] 2017-03-10 08:02
@DzmitryShylovich Can you please provide full example? Cause I want to use your workaround but struggling with implementation. Thank you very much in advance! ;)

**Comment by DzmitryShylovich** [comment] 2017-03-10 08:12
@matejamateusz full example?

**Comment by matejamateusz** [comment] 2017-03-10 08:21
@DzmitryShylovich Yep. I mean I'm having this issue for Ionic 2 - having function in app.module.ts: 

`export function httpInterceptor(backend: XHRBackend, defaultOptions: RequestOptions, events: Events) {
    return new HttpInterceptor(backend, defaultOptions, **window**, events);
}`

which in httpInterceptor.ts : 

`@Injectable()
export class HttpInterceptor extends Http {
  constructor(
      backend: ConnectionBackend,
      defaultOptions: RequestOptions,
      public window: Window,
      public event: Events
  ) {
    super(backend, defaultOptions);
  }`

Now the ngc is saying me: `Could not resolve type Window 
            (position 11:22 in the original .ts file), resolving symbol HttpInterceptor...`

**Comment by DzmitryShylovich** [comment] 2017-03-10 08:25
@matejamateusz remove `@Injectable()` from `HttpInterceptor. You don't need it if you use factory provider.

And don't extend `Http`. Create a wrapper.

**Comment by matejamateusz** [comment] 2017-03-10 08:26
@DzmitryShylovich What do you mean by wrapper?

**Comment by mmc41** [comment] 2017-03-11 12:38
@chuckjaz Is this fixed in v4 ? If so, I have a good reason for upgrading :-)

**Comment by DzmitryShylovich** [comment] 2017-03-11 12:39
not yet

**Comment by mmc41** [comment] 2017-03-11 12:50
@DzmitryShylovich Thanks for the info. It seems whenever I have a angular question/issue, you provide a good answer within 5 minutes. Very impressive. I can't state enough how much your help is appreciated!

**Comment by matejamateusz** [comment] 2017-03-11 12:51
Exactly the same feeling!;)

**Comment by DzmitryShylovich** [comment] 2017-03-11 12:56
https://github.com/angular/angular/pull/14894 the fix

**Closed** 2017-03-15 16:24 UTC
Labels: comp: metadata-extractor

**Comment by MadUser** [comment] 2017-03-30 08:56
Are you sure this works with ng build --prod?

**Comment by DzmitryShylovich** [comment] 2017-03-30 08:59
@MadUser it does work using plain ngc. If it doesn't work in cli then it's a cli issue

**Comment by MadUser** [comment] 2017-03-30 09:31
I don't understand the difference.
I am using the stable angular CLI 1.
why "ng build" works and "ng build --prod" breaks?

Thanks

**Comment by mmc41** [comment] 2017-03-30 20:33
Works fine for me with angular cli 1.0 and angular 4.0 project

**Comment by DzmitryShylovich** [comment] 2017-03-30 20:41
@MadUser looks like it doesn't work with ts interfaces such as `Window`, `Document` etc. See https://github.com/angular/angular/issues/15640
