### ISSUE TITLE
 Attribute [attr] that is not matched is silently removed.

### ISSUE THREAD

**Issue by thso** [angular/angular#6508] opened 2016-01-15 14:44 UTC
When making a typo in the template of forgetting to include the directive in the component, the attribute silently gets removed without any warning.

Example:
  <a [routeLink]="['Something']">Go to Something</a>
where 'routeLink' is a typo and should be 'routerLink'.

Would there be a way to provide a warning when this happens, maybe together with a list of available directives?

**Comment by pkozlowski-opensource** [comment] 2016-01-15 14:58
> Would there be a way to provide a warning when this happens, maybe together with a list of available directives?

Yep, this is the plan. Duplicate of https://github.com/angular/angular/issues/3425

**Closed by pkozlowski-opensource** 2016-01-15 14:58 UTC
