### ISSUE TITLE
AOT errors after NG 8.2 -> NG 9 update

### ISSUE THREAD

**Issue by GuillaumeUnice** [angular/angular#37312] opened 2020-05-27 17:00 UTC
# 🐞 bug report

### Affected Package
I don't know something probably related with ngcc

### Is this a regression?

Everything wokrs in the previous version 8.2 and also in this 9.0 version in JIT mode instead of AOT.

### Description

Nothing is found: Pipes could not be founds, every component is not declared.

## 🔬 Minimal Reproduction
I've a problem with that it's an existing big project so yes I just can't allow to create a new project around that.

## 🔥 Exception or Error
<pre><code>

 [webpack.Progress] 100% 

[1m[31m[0m[39m[22m
[1m[31m[1m[31mERROR in [96msrc/app/components/modal/modal-ref.ts[0m:[93m41[0m:[93m14[0m - [91merror[0m[90m NG2003: 
[0mNo suitable injection token for parameter 'id' of class 'IxbatModalRef'.[39m[22m
[1m[31mFound string[39m[22m
[1m[31m[39m[22m
[1m[31m[7m41[0m     readonly id: string = `ixbat-modal-${uniqueId++}`[39m[22m
[1m[31m[7m  [0m [91m             ~~[0m[39m[22m
[1m[31m[96mnode_modules/ej-angular2/src/ej/schedule.component.d.ts[0m:[93m200[0m:[93m20[0m - [91merror[0m[90m NG1010: 
[0mValue at position 0 in the NgModule.declarations of OperationalPlanningModule is not a class[39m[22m
[1m[31m[39m[22m
[1m[31m[7m200[0m export declare var EJ_SCHEDULE_COMPONENTS: Type<any>[];[39m[22m
[1m[31m[7m   [0m [91m                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~[0m[39m[22m
[1m[31m[96msrc/app/features/operational-planning/containers/op-page/op-page.component.html[0m:[93m1[0m:[93m1[0m - 
[91merror[0m[90m NG8001: [0m'router-outlet' is not a known element:[39m[22m
[1m[31m1. If 'router-outlet' is an Angular component, then verify that it is part of this module.[39m[22m
[1m[31m2. If 'router-outlet' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to 
suppress this message.[39m[22m
[1m[31m[39m[22m
[1m[31m[7m1[0m <router-outlet></router-outlet>[39m[22m
[1m[31m[7m [0m [91m~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~[0m[39m[22m
[1m[31m[39m[22m
[1m[31m  [96msrc/app/features/operational-planning/containers/op-page/op-page.component.ts[0m:[93m9[0m:[93m16[0m[39m[22m
[1m[31m    [7m9[0m   templateUrl: './op-page.component.html',[39m[22m
[1m[31m    [7m [0m [96m               ~~~~~~~~~~~~~~~~~~~~~~~~~~[0m[39m[22m
[1m[31m    Error occurs in the template of component OpPageComponent.[39m[22m
[1m[31m[96msrc/app/features/operational-planning/components/op-team-configuration/op-team-configuration.component.html[0m:[93m1
[0m:[93m1[0m - [91merror[0m[90m NG8001: [0m'ixbat-modal' is not a known element:[39m[22m
[1m[31m1. If 'ixbat-modal' is an Angular component, then verify that it is part of this module.[39m[22m
[1m[31m2. If 'ixbat-modal' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to 
suppress this message.[39m[22m
[1m[31m[39m[22m
[1m[31m[7m1[0m <ixbat-modal [title]="'global.mana[39m[22m
[1m[31mge-user-settings' | translate">[39m[22m
[1m[31m[7m [0m [91m~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~[0m[39m[22m
[1m[31m[39m[22m
[1m[31m  [96msrc/app/features/operational-planning/components/op-team-configuration/op-team-configuration.component.ts[0m:[93m10
[0m:[93m16[0m[39m[22m
[1m[31m    [7m10[0m   templateUrl: './op-team-configuration.component.html',[39m[22m
[1m[31m    [7m  [0m [96m               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~[0m[39m[22m
[1m[31m    Error occurs in the template of component OpTeamConfigurationComponent.[39m[22m
[1m[31m[96msrc/app/features/operational-planning/components/op-team-configuration/op-team-configuration.component.html[0m:[93m2
[0m:[93m9[0m - [91merror[0m[90m NG8002: [0mCan't bind to 'formGroup' since it isn't a known property of 'form'.[39m[22m
[1m[31m[39m[22m
[1m[31m[7m2[0m   <form [formGroup]="configurationForm">[39m[22m
[1m[31m[7m [0m [91m        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~[0m[39m[22m
[1m[31m[39m[22m
[1m[31m  [96msrc/app/features/operational-planning/components/op-team-configuration/op-team-configuration.component.ts[0m:[93m10
[0m:[93m16[0m[39m[22m
[1m[31m    [7m10[0m   templateUrl: './op-team-configuration.component.html',[39m[22m
[1m[31m    [7m  [0m [96m               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~[0m[39m[22m
[1m[31m    Error occurs in the template of component OpTeamConfigurationComponent.[39m[22m
[1m[31m[96msrc/app/features/operational-planning/components/op-team-configuration/op-team-configuration.component.html[0m:[93m8
[0m:[93m42[0m - [91merror[0m[90m NG8002: [0mCan't bind to 'ngValue' since it isn't a known property of 'option'.[39m[22m
[1m[31m[39m[22m
[1m[31m[7m8[0m           <option *ngFor="let a of axes" [ngValue]="a.value">{{ a.label }}</option>[39m[22m
[1m[31m[7m [0m [91m                                         ~~~~~~~~~~~~~~~~~~~[0m[39m[22m
[1m[31m[39m[22m
[1m[31m  [96msrc/app/features/operational-planning/components/op-team-configuration/op-team-configuration.component.ts[0m:[93m10
[0m:[93m16[0m[39m[22m
[1m[31m    [7m10[0m   templateUrl: './op-team-configuration.component.html',[39m[22m
[1m[31m    [7m  [0m [96m               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~[0m[39m[22m
[1m[31m    Error occurs in the template of component OpTeamCo[39m[22m[1m[31mnfigurationComponent.[39m[22m
[1m[31m[96msrc/app/features/operational-planning/components/op-team-configuration/op-team-configuration.component.html[0m:[93m26
[0m:[93m49[0m - [91merror[0m[90m NG8002: [0mCan't bind to 'ngValue' since it isn't a known property of 'option'.[39m[22m
[1m[31m[39m[22m
[1m[31m[7m26[0m             <option *ngFor="let t of timeModes" [ngValue]="t.value">{{ t.label }}</option>[39m[22m
[1m[31m[7m  [0m [91m                                                ~~~~~~~~~~~~~~~~~~~[0m[39m[22m
[1m[31m[39m[22m
[1m[31m  [96msrc/app/features/operational-planning/components/op-team-configuration/op-team-configuration.component.ts[0m:[93m10
[0m:[93m16[0m[39m[22m
[1m[31m    [7m10[0m   templateUrl: './op-team-configuration.component.html',[39m[22m
[1m[31m    [7m  [0m [96m               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~[0m[39m[22m
[1m[31m    Error occurs in the template of component OpTeamConfigurationComponent.[39m[22m
[1m[31m[96msrc/app/features/operational-planning/components/op-team-configuration/op-team-configuration.component.html[0m:[93m33
[0m:[93m3[0m - [91merror[0m[90m NG8001: [0m'ixbat-button' is not a known element:[39m[22m
[1m[31m1. If 'ixbat-button' is an Angular component, then verify that it is part of this module.[39m[22m
[1m[31m2. If 'ixbat-button' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to 
suppress this message.[39m[22m
[1m[31m[39m[22m
[1m[31m[7m33[0m   <ixbat-button (click)="onSubmit($event)" [dis
abled]="configurationForm.pristine || configurationForm.invalid">{{[39m[22m
[1m[31m[7m  [0m [91m  
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~[0m[39m[22m
[1m[31m[39m[22m
[1m[31m  [96msrc/app/features/operational-planning/components/op-team-configuration/op-team-configuration.component.ts[0m:[93m10
[0m:[93m16[0m[39m[22m
[1m[31m    [7m10[0m   templateUrl: './op-team-configuration.component.html',[39m[22m
[1m[31m    [7m  [0m [96m               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~[0m[39m[22m
[1m[31m    Error occurs in the template of component OpTeamConfigurationComponent.[39m[22m
[1m[31m[96msrc/app/features/operational-planning/components/op-team-configuration/[39m[22m
[1m[31mop-team-configuration.component.html[0m:[93m33[0m:[93m44[0m - [91merror[0m[90m NG8002: [0mCan't bind to 'disabled' 
since it isn't a known property of 'ixbat-button'.[39m[22m
[1m[31m1. If 'ixbat-button' is an Angular component and it has 'disabled' input, then verify that it is part of this 
module.[39m[22m
[1m[31m2. If 'ixbat-button' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to 
suppress this message.[39m[22m
[1m[31m3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.[39m[22m
[1m[31m[39m[22m
[1m[31m[7m33[0m   <ixbat-button (click)="onSubmit($event)" [disabled]="configurationForm.pristine || 
configurationForm.invalid">{{[39m[22m
[1m[31m[7m  [0m [91m                                           
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~[0m[39m[22m
[1m[31m[39m[22m
[1m[31m  [96msrc/app/features/operational-planning/components/op-team-configuration/op-team-configuration.component.ts[0m:[93m10
[0m:[93m16[0m[39m[22m
[1m[31m    [7m10[0m   templateUrl: './op-team-configuration.component.html',[39m[22m
[1m[31m    [7m  [0m [96m               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~[0m[39m[22m
[1m[31m    Error occurs in the template of component OpTeamConfigurationComponent.[39m[22m
[1m[31m[96msrc/app/features/operational-planning/containers/op-team-page/op-team-page.component.html[0m:[93m1[0m:[93m1[0m - 
[91merror[0m[90m NG8001: [0m'ixbat-op-team-navbar' is not a known element:[39m[22m
[1m[31m1. If 'ixbat-op-team-navbar' is an Angular component, then verify that it is part of this module.[39m[22m
[1m[31m2. If 'ixbat-op-team-navbar' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this 
component to suppress this message.[39m[22m
[1m[31m[39m[22m
[1m[31m[7m1[0m <ixbat-op-team-navbar (configuration)="openConfigurationModal$.next()"></ixbat-op-team-navbar>[39m[22m
[1m[31m[7m [0m [91m~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~[0m[39m[22m
[1m[31m[39m[22m
[1m[31m  
[96msrc/app/features/operational-planning/containers/op-team-page/op-team-page.component.ts[0m:[93m34[0m:[93m16[0m[39m[22m
[1m[31m    [7m34[0m   templateUr[39m[22m
[1m[31ml: './op-team-page.component.html',[39m[22m
[1m[31m    [7m  [0m [96m               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~[0m[39m[22m
[1m[31m    Error occurs in the template of component OpTeamPageComponent.[39m[22m
[1m[31m[96msrc/app/features/operational-planning/containers/op-team-page/op-team-page.component.html[0m:[93m3[0m:[93m29[0m - 
[91merror[0m[90m NG8001: [0m'ixbat-splash-screen' is not a known element:[39m[22m
[1m[31m1. If 'ixbat-splash-screen' is an Angular component, then verify that it is part of this module.[39m[22m
[1m[31m2. If 'ixbat-splash-screen' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this 
component to suppress this message.[39m[22m
[1m[31m[39m[22m
[1m[31m[7m3[0m <ng-template #splashScreen> <ixbat-splash-screen></ixbat-splash-screen></ng-template>[39m[22m
[1m[31m[7m [0m [91m                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~[0m[39m[22m
[1m[31m[39m[22m
[1m[31m  
[96msrc/app/features/operational-planning/containers/op-team-page/op-team-page.component.ts[0m:[93m34[0m:[93m16[0m[39m[22m
[1m[31m    [7m34[0m   templateUrl: './op-team-page.component.html',[39m[22m
[1m[31m    [7m  [0m [96m               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~[0m[39m[22m
[1m[31m    Error occurs in the template of component OpTeamPageComponent.[39m[22m
[1m[31m[96msrc/app/features/operational-planning/containers/op-team-page/op-team-page.component.html[0m:[93m4[0m:[93m89[0m - 
[91merror[0m[90m NG8002: [0mCan't bind to 'ngClass' since it isn't a known property of 'div'.[39m[22m
[1m[31m[39m[22m
[1m[31m[7m4[0m <div *ngIf="isReady$ | async; else splashScreen" class="operational-planning-container" [ngClass]="{ toggle: 
!toggle }">[39m[22m
[1m[31m[7m [0m [91m                                                                                        
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~[0m[39m[22m
[1m[31m[39m[22m
[1m[31m  
[96msrc/app/features/operational-planning/containers/op-team-page/op-team-page.component.ts[0m:[93m34[0m:[93m16[0m[39m[22m
[1m[31m    [7m34[0m   templateUrl: './op-team-page.component.html',[39m[22m
[1m[31m    [7m  [0m [96m               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~[0m[39m[22m
[1m[31m    Error occurs in the template of component OpTeamPageComponent.[39m[22m
[1m[31m[96msrc/app/features/o[39m[22m
[1m[31mperational-planning/containers/op-team-page/op-team-page.component.html[0m:[93m7[0m:[93m7[0m - [91merror[0m[90m 
NG8001: [0m'ngb-tabset' is not a known element:[39m[22m
[1m[31m1. If 'ngb-tabset' is an Angular component, then verify that it is part of this module.[39m[22m
[1m[31m2. If 'ngb-tabset' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to 
suppress this message.[39m[22m
[1m[31m[39m[22m
[1m[31m[7m7[0m       <ngb-tabset #tabset [hidden]="!toggle" (tabChange)="onTabChange($event)" [destroyOnHide]="false">[39m[22m
[1m[31m[7m [0m [91m      
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~[0m[39m[22m
[1m[31m[39m[22m
[1m[31m  
[96msrc/app/features/operational-planning/containers/op-team-page/op-team-page.component.ts[0m:[93m34[0m:[93m16[0m[39m[22m
[1m[31m    [7m34[0m   templateUrl: './op-team-page.component.html',[39m[22m
[1m[31m    [7m  [0m [96m               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~[0m[39m[22m
[1m[31m    Error occurs in the template of component OpTeamPageComponent.[39m[22m
[1m[31m[96msrc/app/features/operational-planning/containers/op-team-page/op-team-page.component.html[0m:[93m7[0m:[93m80[0m - 
[91merror[0m[90m NG8002: [0mCan't bind to 'destroyOnHide' since it isn't a known property of 'ngb-tabset'.[39m[22m
[1m[31m1. If 'ngb-tabset' is an Angular component and it has 'destroyOnHide' input, then verify that it is part of this 
module.[39m[22m
[1m[31m2. If 'ngb-tabset' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to 
suppress this message.[39m[22m
[1m[31m3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.[39m[22m
[1m[31m[39m[22m
[1m[31m[7m7[0m       <ngb-tabset #tabset [hidden]="!toggle" (tabChange)="onTabChange($event)" [destroyOnHide]="false">[39m[22m
[1m[31m[7m [0m [91m                                                                               
~~~~~~~~~~~~~~~~~~~~~~~[0m[39m[22m
</code></pre>


## 🌍  Your Environment

**Angular Version:**
<pre><code>
Your global Angular CLI version (9.0.5) is greater than your local
version (9.0.1). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 9.0.1
Node: 10.13.0
OS: win32 x64

Angular: 9.0.0
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.1
@angular-devkit/build-angular     0.900.1
@angular-devkit/build-optimizer   0.900.1
@angular-devkit/build-webpack     0.900.1
@angular-devkit/core              9.0.1
@angular-devkit/schematics        9.0.1
@angular/cdk                      8.2.3
@angular/cli                      9.0.1
@angular/http                     7.2.16
@angular/localize                 9.1.9
@ngtools/webpack                  9.0.1
@schematics/angular               9.0.1
@schematics/update                0.900.1
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
</code></pre>

**Anything else relevant?**
I let the es2015 as target inside the tsconfig.json

At least if no resolution, if you know related subject cause I find some of them have the trouble but not resolved are resolved through the AOT

Thanks in advance

**Comment by JoostK** [comment] 2020-05-27 17:22
I can't say for sure and the logging is very hard to read due to the color tags, however the second error stands out:

```
node_modules/ej-angular2/src/ej/schedule.component.d.ts:200:93 - error NG1010: 
Value at position 0 in the NgModule.declarations of OperationalPlanningModule is not a class

export declare var EJ_SCHEDULE_COMPONENTS: Type[];
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

This makes me believe that the declarations of an NgModule refer to `EJ_SCHEDULE_COMPONENTS` from a different compilation unit (a library). This is no longer possible in Ivy, please see [this explanation on why](https://github.com/angular/angular/blob/3723e349d1e153d662bacfde7673c658111a5f1a/aio/content/guide/ivy-compatibility-examples.md#foreign-functions-and-foreign-values-arent-statically-resolvable) (from pending PR #36092) this has changed.

Unrelated to the above, you appear to be using version 9.0.0, which is behind on several important bugfixes. Consider updating to the latest release to benefit from those fixes.

**Comment by JoostK** [comment] 2020-10-17 13:58
I'll go ahead and close this as there's not been a response. See my previous comment on what the root cause likely is:

> This makes me believe that the declarations of an NgModule refer to EJ_SCHEDULE_COMPONENTS from a different compilation unit (a library). This is no longer possible in Ivy, please see this explanation on why (from pending PR #36092) this has changed.

**Closed by JoostK** 2020-10-17 13:58 UTC
Labels: comp: compiler, needs clarification, triage #1
