### ISSUE TITLE
IE edge: When initializing form it is set to dirty 

### ISSUE THREAD

**Issue by Sumei1009** [angular/angular#15452] opened 2017-03-24 09:24 UTC
On IE edge mode, the form is set to dirty when initialized. I found that it said that was a bug in IE, but had been fixed. Now I am still facing this issue. 

https://github.com/angular-ui/ui-mask/issues/29

https://connect.microsoft.com/IE/feedback/details/899139/angular-js-ie11-form-control-dirty-attribute-always-true-if-placeholder-has-non-ascii-chars-and-required-attribute

Any ideas?

**Comment by DzmitryShylovich** [comment] 2017-03-24 09:26
are you using angular 1? because this is angular 2 repo

**Comment by Sumei1009** [comment] 2017-03-24 09:32
@DzmitryShylovich  Yes I am using Angular2. Sorry that I forgot to mention. I searched online and found that someone using angular1 faced the same issue.

**Comment by DzmitryShylovich** [comment] 2017-03-24 09:35
Sounds like duplicate of https://github.com/angular/angular/issues/14440

**Comment by IgorMinar** [comment] 2017-03-24 15:23
Thanks for reporting this issue. However this issue is a duplicate of an existing issue #14440. Please subscribe to that issue for future updates.

**Closed by IgorMinar** 2017-03-24 15:23 UTC
