### ISSUE TITLE
Angular.io down

### ISSUE THREAD

**Issue by cmarsh940** [angular/angular#21882] opened 2018-01-30 03:47 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

going to angular.io on safari and chrome and nothing showing up when inspecting element you see "Uncaught SyntaxError: Unexpected end of input .    main.579e733255738eda4ef4.bundle.js"

## Expected behavior

you should be able to see your site

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [x] Safari (desktop) version XX
- [x] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:   . Mac and ipad

Others:

</code></pre>

**Comment by IgorMinar** [comment] 2018-01-30 07:39
I can't reproduce this. Can you please specify the version of safari that is affected?

**Comment by tech-no-logical** [comment] 2018-01-30 13:34
also get this error in firefox and chrome. site is effectively down.

**Comment by albertosantini** [comment] 2018-01-30 13:38
@IgorMinar see the same error here: https://material.angular.io/
Tested with Chrome and FF.

**Comment by ericmartinezr** [comment] 2018-01-30 13:39
This must be somehow related to https://github.com/angular/angular/issues/21889, does it happen if you use a VPN?

**Comment by petebacondarwin** [comment] 2018-01-30 13:59
Duplicate of #21889. Closing this, even though it was earlier, as there is more info there.

**Closed by petebacondarwin** 2018-01-30 13:59 UTC
Labels: comp: aio, freq1: low, severity5: regression, type: bug
