### ISSUE TITLE
App not loaded in default mobile browser (Android) and Google Search Console

### ISSUE THREAD

**Issue by qrsof** [angular/angular#15790] opened 2017-04-05 14:40 UTC
**I'm submitting a ...**  (check one with "x")
```
[ X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

### Versions.
@angular/cli: 1.0.0
node: 7.4.0
os: darwin x64
@angular/common: 4.0.1
@angular/compiler: 4.0.1
@angular/core: 4.0.1
@angular/forms: 4.0.1
@angular/http: 4.0.1
@angular/platform-browser: 4.0.1
@angular/platform-browser-dynamic: 4.0.1
@angular/router: 4.0.1
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.1

### Repro steps.
ng serve --host 0.0.0.0 and try accessing from an android web browser or put the site online and index from search console, I have developed with angular2 and google search console render the page successfully but with new version it does not load the page

**Comment by DzmitryShylovich** [comment] 2017-04-05 14:47
Please add steps to reproduce

Also see https://angular.io/docs/ts/latest/guide/browser-support.html

**Comment by mirevil666** [comment] 2017-04-05 14:56
steps to reproduce:

With the newest version of angular-cli: https://github.com/angular/angular-cli

Generating and serving an Angular project via a development server

ng new PROJECT_NAME
cd PROJECT_NAME
ng serve --host 0.0.0.0


Look for the ip of your computer: windows(ipconfig) linux (ifconfig)
Navigate to http://ip:4200/ and then open it in the mobile browser, I tested with an Samsung Galaxy S7 default mobile browser (with mobile chrome works fine).

**Comment by tbosch** [comment] 2017-04-08 17:24
Hello,
this is most likely due to missing polyfills. However, we need more information, as we don't have this device:
- which version of Android are you running?
- what is the error that you are getting? See [this link](http://stackoverflow.com/questions/2314886/how-can-i-debug-javascript-on-android) on how to get the error via `adb`.

**Comment by qrsof** [comment] 2017-04-13 18:43
Cannot read property 'apply' of undefined 
common.es5

**Comment by mhevery** [comment] 2018-04-10 22:59
closing as obsolete

**Closed by mhevery** 2018-04-10 22:59 UTC
Labels: comp: core & compiler, state: Need repro, type: bug/fix
