### ISSUE TITLE
"updateOn: 'blur'" does not work in formBuilder/formControl

### ISSUE THREAD

**Issue by DywiTom** [angular/angular#55504] opened 2024-04-24 07:13 UTC
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

Yes

### Description

Hello,

"updateOn: 'blur'" does not work in formBuilder.
It will not be called on blur.

 See Stackblitz

Thanks

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-lq34co?file=src%2Fapp%2Fapp.component.ts

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Latest Angular (v17.5.3)
```

**Comment by DywiTom** [comment] 2024-04-24 07:48
Sorry i fixed the compile problems.

Open console and clear it.
Click on any control and lose focus.
Blur event should be triggerd.

**Comment by DywiTom** [comment] 2024-04-24 08:53
Normaly it should call the custom validator after bluring. It doesn't do that.

1. Start server
2. Clear console
3. Click on control
4. Lose focus (blur event)
5. Validator should be called and console.log should be visible

![no call](https://github.com/angular/angular/assets/87300270/d42e5055-8b6d-4321-8892-64f9a630b5ad)

**Comment by geromegrignon** [comment] 2024-04-24 09:32
There are no pending changes to be evaluated in the example shown in your video.
With blur strategy, Angular expects changes upon the field value to update it and run validators.

**Comment by geromegrignon** [comment] 2024-04-24 09:42
As you can see in your console, there are logs at the form init. That's about the same for required.
By blurring from it without any changes, it was already in error.

How do you see "it shows" or "fire the error"?

**Comment by DywiTom** [comment] 2024-04-24 09:49
My expectation with "updateOn: 'blur'" is that the validators should be executed again, otherwise it should better be "updateOn: 'change'". That is confusing.

Let's say I click on a FormControl with Validators.required and I don't change anything. If I then click on something else, I see the mat-error. But this does not apply to my custom validators because they are not executed again.

**Comment by geromegrignon** [comment] 2024-04-24 09:56
mat-error internally only displays if the field has been touched.
It's about the same for your validators. If the control was invalid before blurring without any change, the error will appear.

If you need to update the validity of some field based on a parent one, use a validator on the parent itself.

**Comment by JeanMeche** [comment] 2024-04-24 10:53
I'll close this as a dupe of #45015

**Closed by JeanMeche** 2024-04-24 10:53 UTC
Labels: needs reproduction, area: forms

**Comment by DywiTom** [comment] 2024-04-24 11:04
Ok guys, thanks for your answers
