### ISSUE TITLE
routerLinkActive throwing error when there's no route match

### ISSUE THREAD

**Issue by celesteking** [angular/angular#39488] opened 2020-10-29 13:24 UTC
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/router/RouterLinkActive

### Description

I'm trying to apply some CSS rules based on class at the top app level (above the component level).
I'm using `routerLinkActive` to do that. *Everything* is working fine, except when navigation happens, it throws an error:
```
core.js:6241 ERROR Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'list-records'
Error: Cannot match any routes. URL Segment: 'list-records'
    at ApplyRedirects.noMatchError (router.js:4396)
    at CatchSubscriber.selector (router.js:4360)
    at CatchSubscriber.error (catchError.js:27)
    at MapSubscriber._error (Subscriber.js:75)
    at MapSubscriber.error (Subscriber.js:55)
    at MapSubscriber._error (Subscriber.js:75)
    at MapSubscriber.error (Subscriber.js:55)
    at MapSubscriber._error (Subscriber.js:75)
    at MapSubscriber.error (Subscriber.js:55)
    at ThrowIfEmptySubscriber._error (Subscriber.js:75)
    at resolvePromise (zone-evergreen.js:798)
    at resolvePromise (zone-evergreen.js:750)
    at zone-evergreen.js:860
    at ZoneDelegate.invokeTask (zone-evergreen.js:399)
    at Object.onInvokeTask (core.js:41645)
    at ZoneDelegate.invokeTask (zone-evergreen.js:398)
    at Zone.runTask (zone-evergreen.js:167)
    at drainMicroTaskQueue (zone-evergreen.js:569)
    at ZoneTask.invokeTask [as invoke] (zone-evergreen.js:484)
    at invokeTask (zone-evergreen.js:1621)
```

`app.component.html`:
```
  <div routerLink="/list-records" routerLinkActive="theclass" >
    <router-outlet></router-outlet>
```

`app-routing.module.ts`:
```
...
const routes: Routes = [
  {
    path: '',
    component: DomainsComponent,
  },
  {
    path: 'list-records/:domain',
    component: DateRedirComponent,
  },
  {
    path: 'list-records/:domain/:start/:end',
    component: ListRecordsComponent,
  },
  {
    path: 'report/:domain',
    component: DateRedirComponent
  },
  {
    path: 'report/:domain/:start/:end',
    component: ReportComponent,
  },
  {
    path: 'test',
    component: TestComponent,
  },
  { path: '**', component: PageNotFoundComponent } // added later , see comment below
];

@NgModule({
  imports: [RouterModule.forRoot(routes, /*{enableTracing: true}*/)],
  exports: [RouterModule]
})
export class AppRoutingModule { }
```

The navigation itself is happening in components via `this.router.navigate(['someroute', param]);` . 
I don't care for that error as everything is working just fine. I don't mind waiting until a route loads and that "theclass" kicks in and only then the styles get applied. That's actually what I expect to happen.

Is there a parameter somewhere to let it suck it up and just proceed silently? I don't like error log being populated with irrelevant info.

## 🔬 Minimal Reproduction
Sadly, this proj is internal.

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.1.12
Node: 10.19.0
OS: linux x64

Angular: 9.1.12
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.12
@angular-devkit/build-angular     0.901.12
@angular-devkit/build-optimizer   0.901.12
@angular-devkit/build-webpack     0.901.12
@angular-devkit/core              9.1.12
@angular-devkit/schematics        9.1.12
@angular/cdk                      9.2.4
@angular/flex-layout              9.0.0-beta.31
@angular/material                 9.2.4
@ngtools/webpack                  9.1.12
@schematics/angular               9.1.12
@schematics/update                0.901.12
rxjs                              6.6.3
typescript                        3.8.3
webpack                           4.42.0

</code></pre>

**Comment by celesteking** [comment] 2020-10-29 14:26
I just can't stress enough how easy this was on Rails and how hard all this is on Angular...  I have just added a wildcard route to the router and.. lo and behold... all navigation is now going to that wildcard route (and no errors in log). WTF?! This all is really unexpected. 

When `this.router.navigate(['/report', domain]);` is invoked on button press, the `DateRedirComponent` is navigating properly to /report/$domain/$start/$end, but in reality it ends up in wildcard route with "/list-records" in the path. I don't get why and how?!!

```typescript
  ngOnInit(): void { // of DateRedirComponent
    this.route.params.subscribe(async params => {
      const { startDate, endDate } = getlastDateRange(60*60*24*7);
      await this.router.navigate(
          [`${startDate}/${endDate}`],
          { relativeTo: this.route }
      );
    });
  }
```

Thanks.

**Comment by celesteking** [comment] 2020-10-29 15:34
I was able to achieve what I wanted with  `[class.theclass]="this.route.snapshot._routerState.url.match('^/list-records')"`, but this is insane. So much trouble for something that should've been so much easier. This is clearly a big deficiency on Angular router's part.

**Comment by atscott** [comment] 2020-10-30 23:01
Here's a reproduction for what I think you're reporting: https://stackblitz.com/edit/angular-ivy-router-base-pxwtuo?file=src%2Fapp%2Fapp.component.html


* The wildcard route matches `/list-records` because you don't have any routes configured that match 'list-records'
* When you didn't have the wildcard, an error was _correctly_ reported, again because you don't have a route which matches
* You're seeing that "all navigations go to the wildcard" because you made the top level div of your application a link. So no matter where you click, you're clicking on the `/list-records` link. See alternative example with the other links outside: https://stackblitz.com/edit/angular-ivy-router-base-p2fnbk?file=src%2Fapp%2Fapp.module.ts
* If you didn't want your top level div to be a link, you shouldn't use `routerLink` with `routerLinkActive`. By design, `routerLinkActive` is meant to be used in conjunction with a `routerLink`. If you want other behavior, such as applying a class on a given element conditionally based on the active route, you can always create your own directive
* Only navigations which do not match any preceding routes are directed to the wildcard route. This would not be the case in your example, unless you had put the wildcard route at the top. [Order matters](https://angular.io/guide/router#route-order) in the routing config as in https://stackblitz.com/edit/angular-ivy-router-base-vykph3?file=src%2Fapp%2Fapp.module.ts
* If your goal is to match `'list-records'` with a `routeLink` and `routerLinkActive` you could define the `'list-records'` route with children, as in this example https://stackblitz.com/edit/angular-ivy-router-base-4gnhjh?file=src%2Fapp%2Fapp.module.ts

Closing as working as intended.

**Closed by atscott** 2020-10-30 23:01 UTC
Labels: comp: router
