### ISSUE TITLE
Failed to load module script: The server responded with a non-JavaScript MIME type of "text/html"

### ISSUE THREAD

**Issue by Gnorro** [angular/angular#39759] opened 2020-11-19 14:13 UTC
# 🐞 bug report

### Description
Hi

I already read lot of threads about this problem, but I can't fix it.
Our app has service worker enabled.
Before deploying new version, we delete all files inside root, then we copy the new ones there. Service worker should have file installed in browser, so I don't understand why the error is on files that we manually deleted before deploying last build. I know that I deleted them from root site, but they should be in user browser service worker.

Previous build:
index.html has link to main.1234.js

New build:
index.html has link to main.5678.js

We delete index.html and main.1234.js
We copy new index.html and main.5678.js

We open browser and we get errors:

<pre><code>
Failed to load module script: The server responded with a non-JavaScript MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.
/main-es2015.b542f2fdb703ba496e2c.js:1 Failed to load module script: The server responded with a non-JavaScript MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.
The FetchEvent for "styles.9df4a9a0a84fb13887b1.css" resulted in a network error response: the promise was rejected.
ngsw-worker.js:615 Uncaught (in promise) Error: Response not Ok (fetchAndCacheOnce): request for styles.9df4a9a0a84fb13887b1.css returned response 504 Gateway Timeout
    at PrefetchAssetGroup.<anonymous> (ngsw-worker.js:615)
    at Generator.next (<anonymous>)
    at fulfilled (ngsw-worker.js:160)
/styles.9df4a9a0a84fb13887b1.css:1 Failed to load resource: net::ERR_FAILED
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.1.1
Node: 12.16.2
OS: win32 x64

Angular: 9.1.1
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.1
@angular-devkit/build-angular     0.901.1
@angular-devkit/build-optimizer   0.901.1
@angular-devkit/build-webpack     0.901.1
@angular-devkit/core              9.1.1
@angular-devkit/schematics        9.1.1
@angular/cdk                      9.2.0
@angular/material                 9.2.0
@ngtools/webpack                  9.1.1
@schematics/angular               9.1.1
@schematics/update                0.901.1
rxjs                              6.5.4
typescript                        3.8.3
webpack                           4.42.0
</code></pre>

Service Worker (SW) should load all js and css files of angular app from client (browser) and then connect to webserver to check for a new version. It seems that if I delete js or css files from site root they can't be loaded also on client, while they should. They should be loaded also without any internet connection, also if there is no comunication with webserver (I say this to exclude that the problem could be caused by any cache configuration from webserver)

My ngsw config file:

<pre><code>
{
	"index": "/index.html",
	"appData": {
		"version": "1.3.70"
	},
	"dataGroups": [
		{
			"name": "path-exclusions",
			"urls": [
				"/api"
			],
			"cacheConfig": {
				"maxSize": 0,
				"maxAge": "0u",
				"strategy": "freshness"
			}
		}
	],
	"assetGroups": [
		{
			"name": "app",
			"installMode": "prefetch",
			"updateMode": "prefetch",
			"resources": {
				"files": [
					"/favicon.ico",
					"/index.html",
					"/.css",
					"/vendor..js",
					"/main..js",
					"/polyfills..js",
					"/runtime..js",
					"/.js",
					"/.(woff2)",
					"!/-sw.js",
					"/manifest.webmanifest"
				]
			}
		},
		{
			"name": "assets",
			"installMode": "lazy",
			"updateMode": "prefetch",
			"resources": {
				"files": [
					"/assets/**",
					"/*.(eot|svg|cur|jpg|png|webp|gif|otf|ttf|woff|woff2|ani)"
				]
			}
		}
	]
}
</code></pre>

Thanks

**Comment by gkalpak** [comment] 2020-11-19 14:46
@Gnorro, it seems that your SW configuration (in `ngsw-config.json`) is not correct.
The `app` asset-group contains the following file patterns:

```json
"files": [
  "/favicon.ico",
  "/index.html",
  "/.css",
  "/vendor..js",
  "/main..js",
  "/polyfills..js",
  "/runtime..js",
  "/.js",
  "/.(woff2)",
  "!/-sw.js",
  "/manifest.webmanifest"
],
```

As it is, it will try to match files literally named `.css` (i.e. just the extension) or `vendor..js` (with double dots). I assume you were going for something more like:

```json
"files": [
  "/favicon.ico",
  "/index.html",
  "/manifest.webmanifest",
  "/*.css",
  "/*.js",
  "/*.woff2",
  "!/*-sw.js",
],
```

See, also the [SW configuration guide][1] for more info on the supported glob format.

##
I am going to close this issue, since this is not a bug in Angular, but feel free to continue the discussion below.

[1]: https://angular.io/guide/service-worker-config

**Closed by gkalpak** 2020-11-19 14:46 UTC
Labels: comp: service-worker

**Comment by gkalpak** [comment] 2020-11-19 14:48
Just to be clear, the error is happening because (due to your incorrect configuration) the SW caches `index.html` but not the JS/CSS files. So, when you remove them from the server, it can find the `index.html` that references `main.1234.js`, but it can't fine `main.1234.js` (neither in its cache, nor on the server).

**Comment by Gnorro** [comment] 2020-11-19 14:54
I'm sorry George. I posted wrong ngsw config file. My current file is:

<pre><code>
{
	"index": "/index.html",
	"appData": {
		"version": "1.3.73"
	},
	"dataGroups": [
		{
			"name": "path-exclusions",
			"urls": [
				"/api"
			],
			"cacheConfig": {
				"maxSize": 0,
				"maxAge": "0u",
				"strategy": "freshness"
			}
		}
	],
	"assetGroups": [
		{
			"name": "app",
			"installMode": "prefetch",
			"updateMode": "prefetch",
			"resources": {
				"files": [
					"/favicon.ico",
					"/index.html",
					"/*.css",
					"/vendor.*.js",
					"/main.*.js",
					"/polyfills.*.js",
					"/runtime.*.js",
					"/*.js",
					"/*.(woff2)",
					"!/*-sw.js",
					"/manifest.webmanifest"
				]
			}
		},
		{
			"name": "assets",
			"installMode": "lazy",
			"updateMode": "prefetch",
			"resources": {
				"files": [
					"/assets/**",
					"/*.(eot|svg|cur|jpg|png|webp|gif|otf|ttf|woff|woff2|ani)"
				]
			}
		}
	]
}
</code></pre>

**Comment by gkalpak** [comment] 2020-11-19 18:06
Does it happen reliably (i.e. every time you update, on every client, etc.) or only sometimes/on some clients?
Could you check what is in the `Cache`s before and after the update (if you are using Chrome, you can check in `DevTools > Application > Cache Storage`).

Could you provide a minimal reproduction of the issue (e.g. a repo we could check out and steps to reproduce the problem)? Otherwise, it is really hard to investigate this.

**Comment by Gnorro** [comment] 2020-11-23 09:58
It happens randomly. On some browser there is no problem, in other there is.

On my pc every time I open site I get that error. Then I do a simple F5 to refresh and problem disappear. It happens the same on other pc

App is huge I can't create e repo sorry. I know it's difficult to understand the problem without it. 

In cache storage I see always files for which there is the error
