### ISSUE TITLE
Form Input type=number required is ng-valid when empty

### ISSUE THREAD

**Issue by GreenToast** [angular/angular#6248] opened 2016-01-04 15:03 UTC
I have this input with the required-property and type="text" and it is not validated correctly. If the input is empty int the beginning the associated ng-invalid. But after typing and deleting some values its ng-valid when empty again. This not happening at type="text."

input type="number" class="datainput" placeholder="Founded..." [(ngModel)]="newtypeData.properties.founded" ngControl="founded"  #name="ngForm" required

**Comment by user414** [comment] 2016-01-08 20:52
Just noticed it myself. Made a plunk of the hero tutorial with the type number

http://plnkr.co/edit/Lx6WZDgZ3YzlIrxBkcMP?p=preview

There's more problem then what you stated, when number is 0 it goes to invalid, when field is erase it stays valid. I'm assuming this would be fixed when doing

https://github.com/angular/angular/issues/2961

**Comment by danielfigueiredo** [comment] 2016-02-21 16:36
NumberValueAccessor is currently returning NaN when it tries to parse '' (empty string). 
https://github.com/angular/angular/issues/6932

**Comment by fredgate** [comment] 2016-02-21 22:00
I think that it is normal that NumberValueAccessor returns NaN when the text entered in the input is empty. Its job is to convert a string to a number, so the NaN value appears appropriate.

**Comment by DrewynV** [comment] 2016-04-05 00:32
__________________________________

Hi! We just wanted to let you know we receievd your email. Thank you for submitting your request. Our aim is to get back to you within 24 hours at the latest. If you have any additional information to add to your request, please reply to this email.


Also please visit our knowledgebase (http://www.support.magicdust.com.au) to browse for further info, we are adding to it all the time.

Or here is our industry report about the 11 Essentials for a Successful Website (http://www.magicdust.com.au/web-design/.

We look forward to helping you succeed online.

Thanks

The Team @ Magicdust Digital

http://support.magicdust.com.au/

Ph (02) 9979 7474
M-F | 9 am-5:00 pm AEST (AEDT in Summer) excluding Public Holidays

------------------------------------------------------------------------------------------------------------
This message was sent to  reply@reply.github.com in reference to Case #166595.
------------------------------------------------------------------------------------------------------------


[[9588c90722ceae94943b318963ceda95be4a57f5-673074595]]

**Comment by kara** [comment] 2016-04-18 22:35
Looks like a dupe of #6932.  Closing in favor of that issue to make it easier to track.

**Closed by kara** 2016-04-18 22:35 UTC
