### ISSUE TITLE
ZoneAwarePromise conflicts with native CacheStorage

### ISSUE THREAD

**Issue by davemecha** [angular/angular#31698] opened 2018-08-31 19:43 UTC
I'm working on a project where I wanted to dynamically cache URLs in browsers native CacheStorage, that is also accessed by the service worker.

I just try to access the cache like this:

```
window.caches.open(CACHE_NAME)
  .then(cache => cache.addAll(ARRAY_OF_URLS))
  .catch(err => console.log('error while caching', err));
```

I get the error:

```
ERROR Error: Uncaught (in promise): TypeError: the given value is not a Promise
```

I can easily reproduce this by typing `window.caches.open('testcache').then(result => result.add('/'))` on the browser console window my angular app.

I assume this problem is caused because the native Promise is overwritten by ZoneAwarePromise but I'm not able to really find the root cause.

I'm running on Angular 5.2.11 and zone.js 0.8.26. Browser is Chrome, version 69.0.3497.35 beta (64-bit) on a Chromebook.

I found a workaround for my problem that I documented on stackoverflow on a matching problem. https://stackoverflow.com/a/52083423/2258093

**Comment by JiaLiPassion** [comment] 2020-05-28 14:06
@davemecha, sorry for very long time delay, it seems this issue can not be reproduced with the latest version of zone.js, could you try it, thanks.

**Comment by jelbourn** [comment] 2020-10-23 21:40
Closing since this seems to be a non-issue with later versions.

**Closed by jelbourn** 2020-10-23 21:40 UTC
Labels: comp: zones, needs clarification, needs reproduction
