### ISSUE TITLE
Error during instantiation of $state! ng-upgrade

### ISSUE THREAD

**Issue by jcao02** [angular/angular#10441] opened 2016-08-02 02:40 UTC
**I'm submitting a ...** 
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I'm currently upgrading an application from angular1 to angular2. I have an angular2 service `CurrentUserService` which uses `$state` from `ui.router` module. I downgraded this service so I can use it in angular1 components but when I run the app in the browser I get the following 

```
EXCEPTION: Error during instantiation of $state! (CurrentUserService -> $state)
``` 

I think there's some kind of circular dependency because I'm using and angular1 service inside an angular2 service which I'm injecting to my angular1 app.

**Expected/desired behavior**

Following the [ngUpgrade](https://angular.io/docs/ts/latest/guide/upgrade.html) tutorial, I'd expect successfully inject the diferent providers to the app.

**Reproduction of the problem**

These are the involved files:

current-user.service.ts
```
import { IStateService } from 'angular-ui-router';

/**
 * CurrentUserService 
 */
@Injectable()
export class CurrentUserService {

  constructor(
    @Inject('$state') private $state: IStateService
  ) { ... }
}
```

app.ts
```
...
upgradeAdapter.addProvider(CurrentUserService);
upgradeAdapter.upgradeNg1Provider('$state');
...
angular.module('myapp', ['ui.router'])
.factory('CurrentUserService', upgradeAdapter.downgradeNg2Provider(CurrentUserService))
```

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** [all] 
 
* **Language:** [TypeScript 1.8.10]

**Comment by christopherthielen** [comment] 2016-08-11 00:33
UI-Router has a  `ng1-to-ng2` project for hybrid ui-router apps: https://github.com/ui-router/ng1-to-ng2

UI-Router for ng1 hosts the application and the ui-router services are [exposed as ng2 providers](https://github.com/ui-router/ng1-to-ng2/blob/master/ng1-to-ng2.ts#L66-L75)

**Comment by tbosch** [comment] 2016-10-04 20:21
Closing this issue as there seems to be a solution. Otherwise please reopen with a plunker to reproduce.

**Closed by tbosch** 2016-10-04 20:21 UTC
