### ISSUE TITLE
AoT with typescript@2.1.1 fails

### ISSUE THREAD

**Issue by blaugold** [angular/angular#12966] opened 2016-11-18 13:15 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When compiling project with ngc and typescript@2.1.1 compilation fails with:
`Metadata emit requires the sourceFiles are passed to WriteFileCallback. Update to TypeScript ^1.9.0-dev`

When downgrading typescript to 2.0.10 the compilation is successful.

**Expected behavior**
ngc should compile project with typescript@2.1.1.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
macOS@10.12.1
node@v6.9.1
angular@2.2.1
typescript@2.1.1

* **Angular version:** 2.0.X

Yes.

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 2.1.1

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment] 2016-11-18 13:23
Pls provide a minimal repo with reproduction.

**Comment by blaugold** [comment] 2016-11-18 14:21
[This repo](https://github.com/blaugold/aot-typescript) has two branches: ts-2.1.1 and ts-2.0.10.
* checkout the branch
* run `rm -rf node_modules && npm i` or `yarn`
* run `npm run build`

ts-2.0.10 compiles fine, ts-2.1.1 gives me the mentioned error.

**Comment by rubber-duck** [comment] 2016-11-18 14:46
In my case running ngc does not fail with an error but the output directory only contains AoT files for node_modules. 

Using the typescript 2.0.x produces correct/expected output. 

You can check out the project [here](https://github.com/rubber-duck/angular2-webpack2-setup) - do `npm run ngc` and it will create correct output in the `build/aot` folder, upgrade to typescript 2.1.x and retry and you will only see `build/aot/node_modules`.

I would really like to get babel out of my build process and TS 2.1 finally implements ES5 async/await emit but this is a blocking issue before upgrading (I've also seen closed issues reporting the same problem without a response  eg. #11689)

**Comment by blaugold** [comment] 2016-11-18 15:28
@rubber-duck The repo you reference uses `"skipMetadataEmit": true` which passes since the compiler never tries to emit the metadata but I too only see `node_modules ` and non of the projects factories.

**Comment by rubber-duck** [comment] 2016-11-18 15:30
@blaugold I tried removing that line to see if I could reproduce before I posted and I couldn't get the error (I'm on windows btw.)

**Comment by gustavLatte** [comment] 2016-11-20 23:30
In my case, similar to @rubber-duck the AOT output folder contained only the `angular` and `angularfire2` folders under the `node_modules` folder.

**Comment by jimmytheneutrino** [comment] 2016-11-24 11:50
I did a little debugging on the rubber-duck's problem.
One of the reasons seems to be the line 187 in tsc-wrapped's collector.js:
`                  if (node.flags & ts.NodeFlags.Export) {`
Here, ts.NodeFlags.Export is undefined in Typescript 2.1.

**Comment by imcotton** [comment] 2016-11-25 19:32
@jimmytheneutrino thank you for the hint 

I've made further digging, it turns out in TS v2.1 should use `ModifierFlags` instead of `NodeFlags`, I opened PR #13081 as first step of migration, once goes merged could easily make the final change as showed in draft PR imcotton/angular#1.

**Comment by actra-gschuster** [comment] 2016-12-01 22:16
I digged deep into a similiar issue today - ng-xi18n did produce my .xlf file but it had no content.
TypeScript changed the "NodeFlags" ENUM, in 2.0.10 it was "Export", in ^2.1 it is "ExportContext".
There where more changes like these so currently NG2 isn't (fully) compatible with TS ^2.1
Downgrading TS to 2.0.10 currently solved my problem.

**Comment by laco0416** [comment] 2016-12-08 05:28
Relates to #13204

**Comment by jamespacileo** [comment] 2016-12-13 01:55
Any news on this issue? Ionic framework suffers from the same issue.

**Comment by laco0416** [comment] 2016-12-13 01:56
@jamespacileo they're working on this. see https://github.com/angular/angular/pull/13294

**Closed** 2016-12-13 05:27 UTC
Labels: comp: core & compiler
