### ISSUE TITLE
ErrorHandler should be extended rather than implemented in Angular Docs

### ISSUE THREAD

**Issue by jliang6** [angular/angular#24872] opened 2018-07-13 17:34 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

https://angular.io/api/core/ErrorHandler#example describe "implements" ErrorHandler but ErrorHandler is a class rather than an interface.

## Expected behavior

It should be like:

`class MyErrorHandler extends ErrorHandler {
  handleError(error) {
    // do something with the exception
  }
}

@NgModule({
  providers: [{provide: ErrorHandler, useClass: MyErrorHandler}]
})
class MyModule {}`

## Minimal reproduction of the problem with instructions

It is an error in the documentation.

## What is the motivation / use case for changing the behavior?

Implementing a class is impossible in Typescript.

## Environment

<pre><code>
Angular version: 6.0.9

Browser:
- [x] Chrome (desktop) version XX
- [x] Chrome (Android) version XX
- [x] Chrome (iOS) version XX
- [x] Firefox version XX
- [x] Safari (desktop) version XX
- [x] Safari (iOS) version XX
- [x] IE version XX
- [x] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by jotatoledo** [comment] 2018-07-13 17:57
https://github.com/angular/angular/issues/21697

**Comment by brandonroberts** [comment] 2018-07-16 14:12
Closing as a duplicate of #21697

**Closed by brandonroberts** 2018-07-16 14:12 UTC
