### ISSUE TITLE
Edge Web Extensions Cause Symbol.iterator Errors with ngFor

### ISSUE THREAD

**Issue by kspearrin** [angular/angular#23340] opened 2018-04-12 15:34 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

When building a web extension using Angular for a [browser_action popup window](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/user_interface/Popups), any calls to the [background page](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/background) fetching an array of objects causes errors when iterating those objects from the Angular app in the popup.

While iterating these objects with `*ngFor="let item of items"`, the following errors are thrown repeatedly in the console:

```
ERROR TypeError: Object doesn't support property or method 'Symbol(Symbol.iterator)'
ERROR CONTEXT [object Object]
```

The array still draws to the screen so I am not sure what the errors are being thrown about. These errors do not manifest themselves whenever iterating objects created from the popup window itself.

**Popup Angular App**

```
@Component({
    selector: 'app-root',
    template: `
        <div>{{href}}</div><br><br>
        <div *ngFor="let item of items">
            Item: {{item.name}}
        </div>`,
})
export class AppComponent implements OnInit {
    items: any[];
    href: string;

    private myItems = [
        { name: 'a' },
        { name: 'b' },
        { name: 'c' },
    ];

    ngOnInit() {
        this.href = window.location.href;
        const bgItems =  browser.extension.getBackgroundPage().myItems;

        console.log(this.myItems);
        console.log(bgItems);

        // Uncomment this line to see that iterating objects in Edge has no problem from the popup page itself.
        // this.items = this.myItems;

        // Uncomment this line to see that getting the same objects from the background page causes errors to occur:
        // ERROR TypeError: Object doesn't support property or method 'Symbol(Symbol.iterator)'
        // ERROR CONTEXT [object Object]
        this.items = bgItems;
    }
}
```

**Background**

```
const myItems = [
    { name: 'a_bg' },
    { name: 'b' },
    { name: 'c' },
];

(window as any).myItems = myItems;
```

My guess is that the serialization processes between the popup and the background page are causing some sort of loss of object data that Angular is trying to utilize.

This only occurs in the Edge browser. I have also tested Safari, Chrome, and Firefox. The others do not manifest this problem.

Turning on prod mode causes the errors to go away in the console:

**Popup App `main.js`**

```
// Enabling prod mode causes the errors to go away, but the performance
// impact of this error are still there.
// enableProdMode();
```

The only workaround I have seen to stop the errors is to clone object arrays after they are fetched from the background page. This re-creates them in the popup window's context.

Since I am not sure if this is an Angular problem or an Edge problem (maybe both?) I also submitted this problem to Edge's issue tracker here: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/16906063/

## Expected behavior

Be able to iterate arrays from the background page without error.

## Minimal reproduction of the problem with instructions

Repo: https://github.com/kspearrin/angular-ext-edge-bug

```
git clone https://github.com/kspearrin/angular-ext-edge-bug.git
cd angular-ext-edge-bug
npm install
npm run build:watch
```

Load the extension in Edge:

Settings -> Extension -> Load Extension

Then open the popup and view the console. Beware: the Edge dev tools for extensions are pretty bad. Very glitchy and often require browser restart to function.

And if you care, my real app that also manifests this problem can be found here: https://github.com/bitwarden/browser

## What is the motivation / use case for changing the behavior?

Using Angular in a web extension for the Edge browser.

## Environment

<pre><code>
Angular version: 5.2.0

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [x] Edge version 41.16299.371.0
 
For Tooling issues:
- Node version: 9.7.1  
- Platform:  Windows 10

Others:

</code></pre>

**Comment by robwormald** [comment] 2018-04-13 21:02
Thanks for the thorough reproduction - I repro'd this locally, but it appears to be an Edge bug, vs anything Angular specific. Fairly often, this sort of weirdness can be attributed to transpilation issues, but this one appears to be unrelated to that - I created a simple test script to run in the extension:
//test.js
```
var items1 = browser.extension.getBackgroundPage().myItems;
var items2 = [
    { name: 'a_bg' },
    { name: 'b' },
    { name: 'c' },
];

for(let item of items1){
  console.log(item);
}


for(let item of items2){
  console.log(item);
}

```

It explodes exactly the same way. The reason it pops up in dev mode in Angular is we do a comparison to check that you're not violating one way data flow, and that comparison involves using the iterator protocols to walk the array. Closing this, but please do update this if you get a response from the Edge team.

**Comment by kspearrin** [comment] 2018-04-14 13:32
Thanks. I have followed up in the Edge issue tracker with your findings.

**Closed** 2018-04-14 13:32 UTC
Labels: comp: core & compiler
