### ISSUE TITLE
incorrect definition of form validity for Control Value Accessor with NG_VALIDATORS

### ISSUE THREAD

**Issue by vladiag** [angular/angular#31672] opened 2019-07-20 14:14 UTC
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/forms

### Is this a regression?
This behavior present in Angular 7 and Angular 8 version, don't know about others

### Description
Form Control validation state not updated correctly if you using custom form control created with Control Value Accessor and using NG_VALIDATORS for update validity state. When you trying to update value state of your FormControl with patchValue or setValue, validity state of form control changed like this control doesn't have validators, but provider for NG_VALIDATORS present in component, that used as custom form control with CVA.

Validation checks involked in next order after we do control.setValue:
1. control updating validity state with validators, specified when FormControl was created and emit value in statusChange subscription
2. checks provided NG_VALIDATORS and execute validate method, after update validity state and NOT emit validity state in statusChange subscription

P.S.
when user himself invoked control value change (from interactions, not from code), all works fine

## 🔬 Minimal Reproduction
app.component and home.component
home.component play role of custom control component with CVA and NG_VALIDATORS. When we set not valid value to control, it emit VALID status to statusChange subscription

https://stackblitz.com/edit/angular-1citlk?file=src/app/app.component.html

## 🔥 Exception or Error
no error

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 7.3.5
Node: 10.15.3
OS: darwin x64
Angular: 7.2.8
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.0
@angular-devkit/build-angular     0.13.0
@angular-devkit/build-optimizer   0.13.0
@angular-devkit/build-webpack     0.13.0
@angular-devkit/core              7.3.5
@angular-devkit/schematics        7.3.5
@angular/cli                      7.3.5
@ngtools/webpack                  7.3.0
@schematics/angular               7.3.5
@schematics/update                0.13.5
rxjs                              6.4.0
typescript                        3.2.4
webpack                           4.29.0
</code></pre>

**Comment by vladiag** [comment] 2020-02-07 10:32
Hi! Any info about issue? almost half a year has passed

**Comment by AndrewKushnir** [comment] 2020-08-13 01:02
Hi @vladiag, thanks for reporting the issue and providing a repro. I perform further investigation and it looks like this issue is caused by the behavior described in #29218. I'm closing this ticket (as a duplicate of #29218), please subscribe to the #29218 for further discussion/updates. Thank you.

**Closed by AndrewKushnir** 2020-08-13 01:02 UTC
Labels: comp: forms, forms: ControlValueAccessor, forms: validators, freq2: medium, severity3: broken, state: needs more investigation, triage #1, type: bug/fix
