### ISSUE TITLE
Why can't *ngFor ergodic Object?

### ISSUE THREAD

**Issue by BengBu-YueZhang** [angular/angular#19588] opened 2017-10-06 06:48 UTC
Why can't *ngFor ergodic Object? 
Object.keys(),Not concise enough

**Comment by MikeSaprykin** [comment] 2017-10-06 07:17
@BengBu-YueZhang - well, *ngFor can iterate only iterable thing, like Array.
Object can't be iterated. Event when you're using Object.keys() you are basically pulling off keys of the object and transform it to Array.

In my projects, when I rarely need to iterate over and Object with *ngFor, I use a custom pipe in a template:
```
@Pipe({
  name: 'values',
})
export class ValuesPipe implements PipeTransform {

  transform(object: any): Array<any> {
    if (object) {
      return Object.keys(object).map(key => object[key]);
    }
  }

}
```
then in a template you can iterate like
```
<div *ngFor="let item of object | values">
<!-- Do whatever you want -->
</div>
```

Sidenote: You can also create your own [structural directive](https://angular.io/guide/structural-directives), that will be able to iterate over Objects

**Comment by mlc-mlapis** [comment] 2017-10-06 07:24
@BengBu-YueZhang ... objects don't guarantee the fixed order ... so it is still the best way to use your own separate vectors of object keys for iteration because they helps also with re-orderings, sorting and other content manipulations ... and it is also the most performance way.

**Comment by ohjames** [comment] 2017-10-06 07:49
@mlc-mlapis the spec doesn't but every widely used JS implementation does.

**Comment by mlc-mlapis** [comment] 2017-10-06 08:04
@ohjames ... I know ... 👍  but still for reasons like dynamic filtering, sorting, ... it is better yo use index vectors.

**Comment by ericmartinezr** [comment] 2017-10-06 10:38
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by trotyl** [comment] 2017-10-06 10:44
Duplicate of #2246.

**Comment by ocombe** [comment] 2017-10-06 13:46
Thanks for reporting this issue. However this issue is a duplicate of the existing issues #2246, #6663 and #16430. Please subscribe to these issues for future updates.

**Closed by ocombe** 2017-10-06 13:46 UTC
