### ISSUE TITLE
HttpClient fails to parse an empty 200 response in IE11

### ISSUE THREAD

**Issue by alexeikostevich** [angular/angular#18680] opened 2017-08-14 16:02 UTC
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
The [HttpClient](https://angular.io/api/common/http/HttpClient) throws an error "_Http failure during parsing for ..._" in the case of an empty 200 response in IE11.
The issue is not reproducible in Chrome and Firefox.
Setting a _responseType_ option to "_text_" helps to resolve the issue.

## Expected behavior
IE11 returns null by analogue with other browsers.

## Minimal reproduction of the problem with instructions
Make an [HttpClient.get](https://angular.io/api/common/http/HttpClient#get) request to an endpoint with the an empty file in IE11.
See this [plunker](http://plnkr.co/edit/6CVGCdVdr2ggxcVVnnD1?p=preview) for an example.

## What is the motivation / use case for changing the behavior?
It is expected to have a consistent behavior across all browsers.

## Environment
Angular version: 4.3.4

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [x] IE version 11
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 6.10
- Platform:  Windows

**Comment by jonathanp** [comment] 2017-09-11 12:02
I get the exact same error in Chrome desktop v60.

**Comment by brentos99** [comment] 2017-09-19 03:43
Hi, 
I'm now getting the same error in Chrome and Edge. I recently upgraded to Angular 4.4.1 and i dont remember seeing it in angular 4.3 

Http failure during parsing for <URL>
HttpErrorResponse

JSON.parse Error: Unexpected input at position:0
SyntaxError

Brent

**Comment by brentos99** [comment] 2017-09-19 04:27
For my error, I was able to fix the problem by setting the _responseType:_ to  _'text'_ in the options. This stopped the HttpClient from trying to parse the empty response as a JSON object. (just realised this was mentioned in the initial bug submission.)

this.http.put(
     url,
     data,
     {
        headers: new HttpHeaders().set('Content-Type', 'application/json'),
        **responseType: 'text'** 
     }
  ).subscribe(  ....   );

This appears to work in Chrome and Edge.

**Comment by TheParad0X** [comment] 2017-09-20 12:46
Same problem here, it used to work with 4.3.6, but with 4.4.3 reading empty responses causes the parsing error.

**Comment by thetric** [comment] 2017-09-20 12:55
This issue is indeed caused by Angular 4.4: #18466

**Comment by snakenstein** [comment] 2017-09-27 09:38
Yeah, I have this problem too. "Unexpected end of JSON input" on empty 200 response.
Chrome v.61.0.3163.100 (Official Build) (64-bit).
Any plans to solve this?

**Comment by thetric** [comment] 2017-09-27 09:49
@snakenstein See brentos99 [comment](https://github.com/angular/angular/issues/18680#issuecomment-330425866). Just add `responseType`:

```ts
    return this.http.post('api/groups', group, {
      responseType: 'text',
    });
```

**Comment by snakenstein** [comment] 2017-09-27 10:01
@thetric I saw this workaround, but It is not suitable for me. 
I have a .net api with a lot of methods which returns an empty 200 response. And I use swagger and NSwagStudio which generates typescript client for this api.
So, I can't change the way NSwagStudio generates code for calling http.post(...). Of course, I can manually change particular method calls. But this is not a practical solution.
Thats why I wondering if there any plans on solving this issue (not a workaround).

**Comment by jonathanp** [comment] 2017-09-27 14:11
A workaround that did it for me was to replace `200 OK` responses to `POST`/`PUT`/`DELETE` requests with `204 No Content`.

It seems strange that this breaking change was introduced in a minor version though, so I guess it was not intentional by the Angular team.

**Comment by snakenstein** [comment] 2017-09-27 19:36
I came to the same workaround as **jonatanp** (`204 No Content` instead of empty `200 Ok`) and it works for me

**Comment by mircowidmer** [comment] 2017-09-30 17:24
```
this.http
  .put(url, payload, {responseType: null})
  .subscribe(() => { ... }

```
seems to work as well as a temporary workaround.

**Comment by lazarljubenovic** [comment] 2017-10-02 16:56
You should change the title of the issue to drop the "IE11" part, since it apparently **affects all browsers**.

This looks like the oldest issue and it's most upvoted, so here's a list of dupes:

https://github.com/angular/angular/issues/19502
https://github.com/angular/angular/issues/19413
https://github.com/angular/angular/issues/19090

Also, _could_ be related to https://github.com/angular/angular/issues/19195, which has a PR https://github.com/angular/angular/pull/19303.

**Comment by Yura13** [comment] 2017-10-05 15:02
I have the same issue with an empty response for post/delete. 
After downgrade to 4.3.x this problem still present only in IE11(```Http failure during parsing...```).

**Comment by Toub** [comment] 2017-10-05 15:54
This can be fixed by setting default encoding to JSON on server-side. 

@Yura13 be sure to fix the minor version, eg "4.3.6" or "~4.3.6", not "^4.3.6"

**Comment by Yura13** [comment] 2017-10-05 17:38
@Toub I am using exactly match "4.3.6"

**Comment by hspier** [comment] 2017-10-06 12:32
Small clarification here:
In 4.3.X, there is an error in IE11 only when parsing empty content (which can be the case in POST, PUT or DELETE). Setting responseType to text is a workaround but since the old Http code does work correctly, HttpClient should handle this too.
In 4.4.X, the error is in every browser and setting responseType to text is a workaround as mentioned in this (and all other related) defect. Again, HttpClient should handle this.

As @snakenstein mentioned, when using automatically generated code makes the workaround less trivial to implement, not counting the fact that we are consuming JSON payloads from various vendors and making them change their code server side just for a simple case of handling a response that is empty or "ok" is hard to justify.

**Comment by Jajunk** [comment] 2017-10-12 13:02
Agree with everything @hspier said. Because of this issue I can not use HttpClient. I will continue to use the older Http and consider this "replacement" to be broken and unusable until this issue is resolved.

**Comment by manuel-di-iorio** [comment] 2017-10-19 12:35
Same in Chrome v61

**Comment by ehsaanwelcome** [comment] 2017-10-21 10:16
same issue as i upgraded 4.4

**Comment by duykhuongkid** [comment] 2017-10-23 06:04
I have same issue when upgraded to 4.4.5

**Comment by erbsenkoenig** [comment] 2017-10-23 07:02
Ich kehre zurück am 01.11.2017.

Ich werde Ihre Nachricht nach meiner Rückkehr beantworten.
In dringenden Fällen senden Sie bitte eine Kopie Ihrer E-Mail für
technische Angelegenheiten an entwicklung@arxes-tolina.de, ansonsten an
info@arxes-tolina.de. Ein anderer Mitarbeiter wird sich dann Ihrer E-Mail
annehmen.


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re:
[angular/angular] HttpClient fails to parse an empty 200 response in IE11
(#18680)" gesendet am 23.10.2017 08:05:45.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während
diese Person abwesend ist.

**Comment by ikramcheb** [comment] 2017-10-24 07:39
same issue when I upgraded to 4.4.6

**Comment by duykhuongkid** [comment] 2017-10-24 10:29
@ikramcheb Could you please check the content of body when get the response from Server? Does it empty?

**Comment by compeek** [comment] 2017-10-24 15:20
I'm am also still noticing this problem in 4.4.6 (Chrome, probably the rest too). The response from the server is empty. Setting `responseType` to `text` fixes it, but than I have to manually parse the JSON in any error responses, which is annoying.

**Comment by compeek** [comment] 2017-10-26 16:40
For what I'm working on, it's not an option to change the response codes the server sends, so I have to tolerate 200 and 201 responses with empty bodies. For now my workaround is an HttpInterceptor that catches errors when the status code is in the 200 range and returns an HttpResponse with a null body instead (just like HttpClient does with 204 Not Content responses):

```
@Injectable()
export class EmptyResponseBodyErrorInterceptor implements HttpInterceptor {
  intercept(req: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
    return next.handle(req)
      .catch((err: HttpErrorResponse) => {
        if (err.status >= 200 && err.status < 300) {
          let res = new HttpResponse({
            body: null,
            headers: err.headers,
            status: err.status,
            statusText: err.statusText,
            url: err.url
          });

          return Observable.of(res);
        } else {
          return Observable.throw(err);
        }
      });
  }
}
```

**Comment by kevin-work** [comment] 2017-11-01 14:09
Also seems to be broken with 202.

**Comment by jbw91** [comment] 2017-11-02 16:32
Still broken in the Angular 5 release. Affects all browsers I've tested. This is a really big issue, a 200 ok is not a server error. @hansl looks like you added a tag for this back in August, but no activity at all since then. Can we get someone to look at this?

**Comment by ginosiccio** [comment] 2017-11-07 07:40
A void response from any HTTP REST EndPoint cause an error. How it could happens ?? 
This is really not serious guys.
You really must fix this quickly as you can as, this should affect any project which use REST calls.
This issue is here since we use the httpclient package in our project and since 2 months...
I will remove the horrible hack in the spring boot application in order to put the shitty responseType Text in front-end side.

**Comment by lazarljubenovic** [comment] 2017-11-07 17:13
@ginosiccio You can also get rid of anything you consider "shitty" by submitting a pull request or joining the search for the cause of a bug. Or even forking Angular and using your own version.

For this concrete one, things _are_ happening, as you can see below your comment. No good will come from rushing the team to do a "quick fix" -- if it's quick and not tested and thought through properly, it will just cause more bugs. Let's value quality over quantity. :smile:

**Comment by vieko** [comment] 2017-11-10 00:45
@compeek Alex: you are a saint! thank you.

**Comment by alexandremoore** [comment] 2017-11-10 13:29
@alxhub Do you plan to create a PR with your fix?

**Comment by Maximaximum** [comment] 2017-11-10 15:26
I've just updated my app from angular 4 to angular 5. I had to rewrite some parts of it to use the new HttpClient instead of the deprecated Http. But now I find out this problem. It's 3 months already, but hopefully @alxhub's solution works. However, it'still needs to be merged and released.

Hopefully this won't take long, because this is really a huge problem :)

**Comment by kevinkjt2000** [comment] 2017-11-14 23:00
:confetti_ball: https://github.com/angular/angular/pull/19958 :confetti_ball:

**Comment by dirisujesse** [comment] 2017-11-19 20:31
Setting the responseType option to text solved the problem for me.
`
uploadAvatar(id: any, picture: string) {
       return this.http.put(`${this.url}/providers/addAvatar/`, JSON.stringify({id: id, picture: picture}),
            {headers: new HttpHeaders().set('Content-Type', 'application/json'), responseType: 'text'});
}
`

**Comment by Andrey-Pavlov** [comment] 2017-11-20 11:39
@compeek workaround works for me!
https://github.com/angular/angular/issues/18680#issuecomment-339726251

**Comment by Draluy** [comment] 2017-11-21 14:36
@compeek  workaround works for me too.
I saw that @alxhub made a fix for this. I updated to 5.0.2 hoping that it would have been merged, but no difference from 5.0.0.

Any idea what version will  have @alxhub's fix?

**Comment by egervari** [comment] 2017-11-23 20:44
I agree that seeing the response to text is a poor workaround. My app is 150,000 lines of code with tons of rest calls. This is such a huge breaking change :/

**Comment by mrahhal** [comment] 2017-11-24 05:01
@egervari you can always use an interceptor, which would make things a bit more bearable.

For reference, this is the one I'm using:
```ts
import { HttpErrorResponse, HttpEvent, HttpHandler, HttpInterceptor, HttpRequest, HttpResponse } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs/Observable';

// Remove when https://github.com/angular/angular/pull/18466 gets merged.
// Also: https://github.com/angular/angular/issues/18680

@Injectable()
export class WA18396Interceptor implements HttpInterceptor {
	constructor() { }

	intercept(req: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
		if (req.responseType == 'json') {
			req = req.clone({ responseType: 'text' });

			return next.handle(req).map(response => {
				if (response instanceof HttpResponse) {
					response = response.clone<any>({ body: JSON.parse(response.body) });
				}

				return response;
			});
		}

		return next.handle(req);
	}
}
```

**Closed** 2017-11-29 18:12 UTC
Labels: comp: common/http, freq1: low, severity3: broken, type: bug

**Comment by arpan2501** [comment] 2017-11-30 07:46
Sir what is the final response as i am also facing this error - 
Shall i update my angular version OR set the responseType as "text"

I am very new to this and working out - kindly guide

**Comment by claudiuconstantin** [comment] 2017-12-05 09:14
@arpan2501 I believe the bug-fix will be included in the next ng version. Until then you can use the `responseType as "text"` workaround

**Comment by dgsqrs** [comment] 2017-12-05 09:23
It works as expected using ng 5.0.5

**Comment by fertandil87** [comment] 2018-01-02 16:11
it's not fixed, I updated to 5.1.2

**Comment by alexandredavi** [comment] 2018-01-10 13:23
same issue when I upgraded to 5.2.0

**Comment by atheros** [comment] 2018-01-15 08:52
@mrahhal's solution doesn't work for HttpErrorReponse. Here is my improvement:

```typescript
import { Injectable } from '@angular/core';
import { HttpErrorResponse, HttpEvent, HttpHandler, HttpInterceptor, HttpRequest, HttpResponse, HttpResponseBase } from '@angular/common/http';
import { Observable } from 'rxjs/Observable';

import 'rxjs/add/operator/catch';
import 'rxjs/add/observable/throw';

/**
 * Handle empty JSON responses.
 */
@Injectable()
export class EmptyResponseBodyInterceptor implements HttpInterceptor {
    constructor() {
    }

    /**
     * Intercept request and convert it to text response.
     *
     * BUG: https://github.com/angular/angular/issues/18680
     * As of 2018-01-11 it is closed and reported fixed in Angular 5, however people are still reporting it not working.
     *
     * @param {HttpRequest<any>} req
     * @param {HttpHandler} next
     * @return {Observable<HttpEvent<any>>}
     */
    intercept(req: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
        /* istanbul ignore next */
        if (req.responseType === 'json') {
            req = req.clone({responseType: 'text'});

            return next.handle(req).map(response => {
                if (response instanceof HttpResponse) {
                    response = response.clone<any>({body: JSON.parse(response.body)});
                }

                return response;
            }).catch((error: any) => {
                if (error instanceof HttpErrorResponse) {
                    if (error.error && error.error.length && error.headers.get('content-type').startsWith('application/json')) {
                        error = new HttpErrorResponse({
                            error: JSON.parse(error.error),
                            headers: error.headers,
                            status: error.status,
                            statusText: error.statusText,
                            url: error.url
                        });
                    }
                }

                return Observable.throw(error);
            });
        }

        return next.handle(req);
    }
}
```

**Comment by heuristicAL** [comment] 2018-02-08 14:57
For those who are still monitoring this: updating to 5.2.4 seems to fix the problem.
😄

**Comment by FelixFriedman** [comment] 2018-02-20 04:25
I installed 5.2.5 but the issue seem to be still there. I have a http.get that returns text. but seem to be getting an error still

error: SyntaxError: Unexpected token h in JSON at position 0
    at JSON.parse (<anonymous>)
    at XMLHttp…

**Comment by tenderloin420** [comment] 2018-03-09 02:59
I was previously using the empty response body interceptor to workaround this issue. After upgrading to 5.2.6 and removing the interceptor everything works as expected.

**Comment by leojkwan** [comment] 2018-03-18 02:44
Ran into same problem making a `put` request to my endpoint. I realized I was sending 200 without a response body. Sending status code `204` made angular http 5.2.8 stop complaining. This problem should not be happening even with a 200, but 204 is the correct code for empty responses.

**Comment by lazarljubenovic** [comment] 2018-03-18 10:12
@leojkwan Empty string is not a valid JSON. Angular by default assumes that the response is JSON and tries to parse it. If you know your endpoint returns a different type, tell that to Angular with `resopnseType`. In your case, `text` should work.

It's not an issue with Angular, it's your API: if you say it's `application/json` and then return an empty body, you're not tagging the payload properly.

**Comment by leojkwan** [comment] 2018-03-19 15:31
@lazarljubenovic thanks for clarifying, I did try the aforementioned suggestions, that is, to tell Angular that my `responseType` is `text`, but I still ran into with http 5.2.8, I will try again and try to provide more information for the context of my issue.

To be clear, if I do not want an endpoint to send any payload back, just a success 200, I would need to set `responseType` to `text`?

**Comment by lazarljubenovic** [comment] 2018-03-19 18:05
> [I]f I do not want an endpoint to send any payload back, just a success 200, I would need to set `responseType` to `text`?

Yes.

**Comment by funkizer** [comment] 2018-03-24 17:37
This seems to be still affecting `.head()`? I can't read any headers. Tried everything listed here including sending with status 204 from the server. Express doesn't seem to allow a body in a head response so can't try sending back a non-empty one.

**Comment by funkizer** [comment] 2018-03-24 18:10
Ok so no custom headers can be read currently, doesn't matter if it's GET or HEAD. A gloriously ugly workaround is to pass the string I need in `content-type`.  :D
```
// Express:
const hash = connector.store.getHash(req.path);
res.set('content-type', 'application/' + hash).send();
// client:
const hash = res.headers.get('content-type').split(/\/|\;/)[1];
```

**Comment by petercunha** [comment] 2018-06-21 18:34
WHY DO YOU DO THIS, ANGULAR?

**Comment by funkizer** [comment] 2018-06-21 20:37
@petercunha just pass responseType: 'text' in the options dude!  :D

**Comment by petercunha** [comment] 2018-06-21 21:35
@funkizer I tried that, it didn't fix anything.

**Comment by gatschet** [comment] 2018-07-16 10:33
Still an issue in Angular 6.0.6. Workaround {responseType: 'text'} can fix it.

**Comment by lazarljubenovic** [comment] 2018-07-16 14:12
@gatschet There's nothing wrong with how Angular handles this. If your server returns 200 with an empty body, your server is not complying with the Http spec.

The spec states the following.

> All 1xx (informational), 204 (no content), and 304 (not modified) responses MUST NOT include a message-body. All other responses do include a message-body, although it MAY be of zero length.

There's a difference here. 1xx, 204 and 304 do not _contain_ the body _at all_. This is handled by Angular after the fix: if the response type is 204, the HttpClient doesn't attempt to transform its body to JSON.

However, when your server is returning a 200 with an _empty_ body (that is, an _empty string_ -- as the spec says, of zero length), **and** specifies `Content-Type` as `application/json`, then your server is lying: `''` is not a valid JSON.

You can try it yourself.

![image](https://user-images.githubusercontent.com/7661457/42763316-f67543de-8912-11e8-870e-382d4286b4a1.png)

**Comment by gatschet** [comment] 2018-07-16 14:30
@lazarljubenovic I don't think my server is lying because it's defined as TEXT_PLAIN on server side 
```
    	@POST
	@Path("/testmail/")
	@Consumes(MediaType.WILDCARD)
	@Produces(MediaType.TEXT_PLAIN)
	public Response sendTestMail() {
            return Response.ok("testmessage").build();
        }
```
As you can see the body is not emty ("testmessage")! The problem is, that angular is thinking this is an json response and fails to parse.

**Comment by lazarljubenovic** [comment] 2018-07-16 15:04
That's not a problem, that's the feature. The default `responseType` is `'json'`. You have to tell Angular if you want to parse body as a different type.

So, your code `{responseType: 'text'}` is not a "workaround" or a "fix" for a "bug", it's simply the correct way to declare the type of the body.

**Comment by gatschet** [comment] 2018-07-17 05:37
@lazarljubenovic In Response Header is content-type: text/plain;charset=UTF-8 as you see
`    
HTTP/1.1 200 OK
     X-Powered-By: Express
     Access-Control-Allow-Origin: *
     connection: close
     content-type: text/plain;charset=UTF-8
     date: Tue, 17 Jul 2018 05:28:09 GMT
     Transfer-Encoding: chunked
`

Angular just ignores that and you tell me this is a feature??? For real?

**Comment by mlc-mlapis** [comment] 2018-07-17 06:03
@gatschet ... the situation is that `responseType` plays a key role and affects the rest of the behavior.

**Comment by lazarljubenovic** [comment] 2018-07-17 09:46
@gabejohnson If Angular used the runtime check for headers, it would not be possible to correctly type your code.

If you do not know the response type or want to use the header to differently parse the body, you can create a util function where all responses are interpreted as `{ responseType: 'text' }`, and then your custom logic kicks in, along the lines of `if (headerSaysTextPlain) { return body } else if (headerSaysJson) { return JSON.parse(body) }`.

You'll, however, lose any typing information which makes this kind of useless since you'll have to include some runtime check for the correct type, and you're back to square one -- you could've just used the original `responseType` setting.

**Comment by trotyl** [comment] 2018-07-17 09:49
@lazarljubenovic I guess you were `@`ing the wrong person?

**Comment by lazarljubenovic** [comment] 2018-07-17 10:41
@trotyl Sorry, GitHub's autocomplete ain't the prettiest. :sweat_smile:

**Comment by vegaskev** [comment] 2019-07-13 00:10
I see a lot of people commenting and saying things like "this is a breaking change", or "when will this be fixed".  That said, I want to briefly notate the bottom of this thread so that when users get here, start scrolling through the answers and inevitably scroll to the bottom, they'll understand what's what and how to resolve without having to read through 802 million answers (which by the way, a good amount are helpful).

1. This IS NOT a "break".  **This is a feature not a bug**
2. Angular's default response type (aka 'response-type') is JSON.  I don't work on the Angular team, but I would venture to say this is because "most" modern API's return JSON...yes yes yes, don't yell, I know that are other options, but most server side engineers (these days) build their APIs to return JSON in modern applications because JSON is universal and can be read by modern languages used for web, desktop and mobile clients.  This 'default' saves us from repetitive code in every single service we write -- so, I say "thank you" to the ng team for this.  If you have been using Angular since 2.0 beta, you know exactly what I'm talking about.  If, by chance, you are working on an API that does not return JSON, the Angular framework makes it easy to write a service that intercepts http requests and add your desired responseType to your requests.  Write it once and be done ...yay [HTTP Interceptors](https://angular.io/api/common/http/HttpInterceptor).
    * What about scenarios where I do have an API that returns JSON, but some of the requests don't return JSON?
        * No worries, you have the option of adding the responseType to your method call :)  
        * Ideally, I would recommend that you communicate with your server side team and ask them if they could return JSON in all responses to be more consistent across the API, however, we all know that isn't always an option...but yes, they should - good programming is about consistency, however who knows what your server side team's backlog and deadlines look like, right?
3. You are getting errors caught because by default, Angular expects those responses to be JSON and you are getting something else like XML, text, etc.  Simply add the following to your requests and you'll be good to go.  👍 

```javascript
yourServiceFunction(reqData) {
  this.http.post(`/my/api`, reqData, { responseType: 'text' })
    // your pipe, subscribe, etc goes here
}
```

Keep in mind, if you are getting something other than text back from your API responses that aren't serving you JSON, you would swap out `'text'` with something else.

If you're new to API requests, I highly recommend spending 2-5 minutes reading the document below to get you acclimated with additional response types.  There's not many and it's always good to know what's out there.

https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/responseType
