### ISSUE TITLE
add casted control getters

### ISSUE THREAD

**Issue by Toxicable** [angular/angular#36405] opened 2020-04-02 23:22 UTC
# 🚀 feature request

### Relevant Package
`@angular/forms`

### Description
Currently `get` on AbstractControl returns an `AbstractControl`. This works as intended but dosen't play well with `strictTemplates` and deeply nested forms.

### Describe the solution you'd like
add the methosd `getGroup` `getControl` `getArray` which will run the `get` function but then cast the type and do a runtime check to ensure it's the correct runtime type also.

### Describe alternatives you've considered
Put a method in your component class, but this isn't ergonomic
```
asControl(c: AbstractControl): FormControl { return c as FormControl }
```

Happy to submit a patch

**Comment by jayoungers** [comment] 2020-07-07 20:23
For most of my forms, I generally end up extending the `FormGroup` class like so:

```TS
class MyFormGroup extends FormGroup {
  constructor() {
    super({
      code: new FormControl(null, Validators.required),
      description: new FormControl(null, Validators.required),
      things: new FormArray([])
    });
}
```

For the more complicated forms, it helps keep the form logic isolated (`valueChange` subscriptions, etc) as well as reusable if I have multiple pages with similar functionality.

Assuming they're not dynamic, you could then do something like this:

```TS
controls!: { code: FormControl, description: FormControl, things: FormArray };
```

Given where TS is at currently, is there any way to infer this based on what's passed in to the constructor?  If so I'm guessing the next hurdle would be allowing `FormArray` to have a generic type

I would think giving the `controls` object a true type definition would be preferable to casting function calls from a html binding perspective

**Comment by jelbourn** [comment] 2020-10-12 22:11
Duplicate of #13721

**Closed by jelbourn** 2020-10-12 22:11 UTC
Labels: comp: forms, cross-cutting: types, feature, forms: Controls API, triage #1
