### ISSUE TITLE
Static ViewChild is intermittently undefined on first ngOnChanges

### ISSUE THREAD

**Issue by patxbert** [angular/angular#40547] opened 2021-01-25 04:55 UTC
# 🐞 bug report

### Affected Package

The issue is caused by package @angular/core

### Is this a regression?

Yes, not sure when this started happening, but it's only started happening within the last week.

### Description

I have an IconComponent which is very similar to [this StackBlitz](https://stackblitz.com/edit/angular-ivy-sj9oba?file=src/app/icon/icon.component.ts), in which the method `getIconTemplate` returns `undefined` for all templates.

The only way I have found to fix this issue is by deleting the node_modules folder and running `npm i` again, but this does not always work.

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-ivy-sj9oba?file=src/app/icon/icon.component.ts

Video of reproduction with above code:

https://user-images.githubusercontent.com/75599348/105662531-0e669f80-5f24-11eb-9d3d-dd427f0d638c.mp4

## 🌍  Your Environment
**Browser:**
Chrome Version 87.0.4280.141 (Official Build) (64-bit)
**Angular Version:**
<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 11.0.5
Node: 15.5.0
OS: win32 x64

Angular: 11.0.5
... cli, core
Ivy Workspace: Yes

Package                             Version
-------------------------------------------------------------
@angular-devkit/architect           0.1100.2
@angular-devkit/build-angular       0.1100.2
@angular-devkit/core                11.0.2
@angular-devkit/schematics          11.0.2
@angular/animations                 11.0.2
@angular/cdk                        10.2.4
@angular/common                     11.0.2
@angular/compiler                   11.1.0
@angular/compiler-cli               11.1.0
@angular/forms                      11.0.2
@angular/localize                   11.1.0
@angular/platform-browser           11.0.2
@angular/platform-browser-dynamic   11.0.2
@angular/platform-server            11.0.2
@angular/pwa                        0.1001.6
@angular/router                     11.0.2
@angular/service-worker             11.0.2
@schematics/angular                 10.1.6
@schematics/update                  0.1100.5
rxjs                                6.6.3
typescript                          4.0.3
</code></pre>

**Comment by JoostK** [comment] 2021-01-25 09:16
Heya, I notice in the version output that you're using various different versions of Angular dependencies, which may very well result in strange behavior. Could you please update all versions to be aligned?

**Comment by patxbert** [comment] 2021-01-26 23:06
@JoostK I'll try your suggestion and let you know.

**Comment by patxbert** [comment] 2021-01-27 00:01
@JoostK Your suggestions *may* have fixed the issue, but I can not be sure since this issue seems to not always happen.

**Comment by petebacondarwin** [comment] 2021-04-12 09:10
Closing as we are not able to reproduce the issue, and it looks like this was an version mismatch issue.

**Closed by petebacondarwin** 2021-04-12 09:10 UTC
Labels: comp: core, needs clarification
