### ISSUE TITLE
VS Code auto-import doesn't identify secondary entry points

### ISSUE THREAD

**Issue by mhamri** [angular/angular#40407] opened 2021-01-13 09:52 UTC
# 🐞 bug report

### Affected Package
tested on ` "@angular/core": "~11.0.5",`

### Is this a regression?
not sure

### Description
https://github.com/microsoft/TypeScript/issues/42247

there are missing exports from the angular library that cause the typescript doesn't show available options as part of vscode IntelliSense 

`import { BrowserAnimationsModule } from '@angular/platform-browser/animations'`

![](https://user-images.githubusercontent.com/8991783/104149335-c66a5780-5410-11eb-80f0-f325754e3983.gif)

## 🔬 Minimal Reproduction
https://github.com/mhamri/vscode-typescript-intellisense-bug2

## 🌍  Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___ 
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | | 
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | | 
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 11.0.5
Node: 14.15.1
OS: win32 x64

Angular: 11.0.5
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.5
@angular-devkit/build-angular   0.1100.5
@angular-devkit/core            11.0.5
@angular-devkit/schematics      11.0.5
@angular/cdk                    11.0.3
@angular/material               11.0.3
@schematics/angular             11.0.5
@schematics/update              0.1100.5
rxjs                            6.6.3
typescript                      4.0.5

</code></pre>

**Comment by alan-agius4** [comment] 2021-01-13 10:57
The TypeScript auto import functionality doesn't handle secondary entry-points as it assumes that everything is exported from the main entry-point using a barrel file.

Unfortunately, we cannot export using the barrel file as suggested in the linked TypeScript issue as this will essentially void all the benefits of using such entry-points.

**Comment by mhamri** [comment] 2021-01-13 15:40
@alan-agius4 is it possible to bring the discussion to the typescript team, there should be a solution for this eventually. I mentioned the same concern and Ryan Cavanaugh suggested using import without export in the barrel. I didn't give it a try yet, but if it's something that doesn't work, maybe we can elaborate more on that issue and find a possible solution or suggestion from the typescript team?

**Comment by jelbourn** [comment] 2021-01-13 16:09
I'm going to close this since the behavior in question belongs to TypeScript/VS Code; I don't see us changing our packaging for this specifically (if that's even feasible) since a lot of thought has gone into our [Angular Package Format](https://docs.google.com/document/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-NtkJglDaBVs/preview). It may be worth raising this to the TypeScript team.

**Comment by mhamri** [comment] 2021-01-13 16:23
@jelbourn I already raised it with the typescript team and they proposed a solution with considering your current packaging behavior, closing the issue without even considering if even it's feasible isn't a little bit lazy way of dealing with things? 

if their suggestion works wouldn't be beneficial to update your package format document (as far as I know it's not the bible)? I don't see any reason why you need to play tai chi against a genuine and simple improvement that could enhance the development experience by alot. I preferred to see that you are bringing a technical issue after trying their solution, but ...

**Comment by petebacondarwin** [comment] 2021-01-13 16:55
@mhamri - sorry for the short response. We didn't see that a workaround was suggested that would not invalidate our Angular Package format - although I think it could have other detrimental consequences.

For clarity the suggestion is to import (but not re-export) all of the secondary entry-point exports into the primary entry-point.

I will re-open and test this idea before commenting further.

**Comment by petebacondarwin** [comment] 2021-01-13 17:14
To make the suggestion even more concrete. I cloned and installed node_modules in the reproduction above (https://github.com/mhamri/vscode-typescript-intellisense-bug2).

Then I opened up `node_modules/@angular/platform-browser/platform-browser.d.ts` and added the following line to the top of the file:

```ts
import './animations';
```

Then when I restart VS Code the intellisense auto-import works as expected.

**Comment by petebacondarwin** [comment] 2021-01-13 17:16
I am not sure whether these imports could be added to the primary entry-point barrels without breaking the isolation of the secondary entry-points. It may even affect tree-shaking.

**Comment by petebacondarwin** [comment] 2021-01-13 17:20
Personally, I still think that the proposal is just a hack and that TS needs to come up with a better solution. My understanding is that it is not feasible for them to parse every file in node_modules looking for possible entry-points since that would kill VS Code. But here are two suggestions:

1. Do a glob of `node_modules` for `package.json` files that contain the `typings` property.  And add these all as candidates.
2. Support a new property in primary entry-point `package.json` files that lists all the secondary entry-points.

**Comment by mhamri** [comment] 2021-01-13 17:25
@petebacondarwin thanks for spending time on this. 

we can always ask them if it's a hack or not and what if it's how it's meant to be used in the first place, I'm sure there is no one better to answer this than the typescript team.

**Comment by petebacondarwin** [comment] 2021-01-13 19:27
One more concern about this approach is that it not only ties the primary entry-point to the secondary ones, it could also create circular imports.

**Comment by clydin** [comment] 2021-02-10 15:35
I think a promising method to solve this issue would be the `exports` field within `package.json` (https://nodejs.org/api/packages.html#packages_package_entry_points).  This would allow TypeScript to only need to look in one package.json to discover all secondary entry points.  It could also be used with an exports conditional (e.g., `types`/`typings`) to allow TypeScript to discover type information for that secondary entry point.
This would, however, require TypeScript support for the `exports` field.

Minimal Example:
```
  "exports": {
    ".": "./bundles/platform-browser.umd.js",
    "./animations": {
      "typings": "./animations/animations.d.ts",
      "default": "./bundles/platform-browser-animations.umd.js"
    }
  }
```

**Comment by mwitteveen** [comment] 2022-01-14 10:23
> To make the suggestion even more concrete. I cloned and installed node_modules in the reproduction above (https://github.com/mhamri/vscode-typescript-intellisense-bug2).
> 
> Then I opened up `node_modules/@angular/platform-browser/platform-browser.d.ts` and added the following line to the top of the file:
> 
> ```ts
> import './animations';
> ```
> 
> Then when I restart VS Code the intellisense auto-import works as expected.

HERO!!!! this is working for all multiple entry points npm packages!!

Was screwing around for days to get the following entrypoint working.

{
....
  "exports": {
    ".": "./lib/index.js",
    "./events/generics": "./lib/events/generics/index.js",
    "./register": "./lib/register.js",
    "./logger": "./lib/logger.js"
  },
  "types": "lib/index.d.ts",
  "typesVersions": {
    "*": {
      "events/generics": [
        "./lib/events/generics/index.d.ts"
      ],
      "register": [
        "./lib/register.d.ts"
      ],
      "logger": [
        "./lib/logger.d.ts"
      ]
    }
...
  }

Added: 

import "./logger";
import "./register";
import "./events/generics";

to the index.d.ts file and everything is autocompleting!!!

**Comment by alan-agius4** [comment] 2022-05-13 07:36
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.

**Closed by alan-agius4** 2022-05-13 07:36 UTC
Labels: comp: packaging, P3
