### ISSUE TITLE
Tutorial parts missing on the angular.io website

### ISSUE THREAD

**Issue by lenardmotion** [angular/angular#25594] opened 2018-08-21 10:47 UTC
Those two pages from the angular.io tutorial pages are not working.
https://angular.io/tutorial/toh-pt3
https://angular.io/tutorial/toh-pt5
Please can you check into that ?

Thanks

**Comment by s-gbz** [comment] 2018-08-21 11:59
Please clarify,
are you unable to open the links or is there something wrong with the example code?

If so, please specify what exactly and post a minimal reproduction. 

[Read here](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#submit-issue) for more information.

**Comment by s-gbz** [comment] 2018-08-21 12:59
Well that's interesting! Why don't you provide some more details like operating system version and Chrome build. You could also open the browser console via F12 and see if there's some useful information. 

Maybe there already is some related issue.

**Comment by gkalpak** [comment] 2018-08-21 13:43
Closing as duplicate of #25595.

**Closed by gkalpak** 2018-08-21 13:43 UTC
