### ISSUE TITLE
PLATFORM_DIRECTIVES not defined in tests

### ISSUE THREAD

**Issue by alxhub** [angular/angular#5585] opened 2015-12-03 22:07 UTC
`createTestInjector` uses bindings that are missing `PLATFORM_DIRECTIVES`.

This means that if a user defines a component that uses `NgIf` for example but doesn't specify an explicit dependency via `@Component({directives})`, it will work in the app but fail in tests.

**Comment by juliemr** [comment] 2015-12-03 22:13
See also https://github.com/angular/angular/issues/5351

**Comment by pkozlowski-opensource** [comment] 2015-12-03 22:16
This is duplicate of #5433

**Comment by juliemr** [comment] 2015-12-17 05:26
Can I close this as a dupe? There's a fix design in #5351 - please continue discussion there! :)

**Closed by juliemr** 2015-12-17 05:26 UTC
Labels: effort1: easy (hour), state: Needs Design
