### ISSUE TITLE
Is it normal not to be able to use absolute URLs in the styleUrls property

### ISSUE THREAD

**Issue by templth** [angular/angular#6905] opened 2016-02-05 09:51 UTC
Following this [question](http://stackoverflow.com/questions/35188803/angular-2-external-style-doesnt-get-inlined-to-header/35197976#35197976) on StackOverflow, it appears that it's not possible to use absolute URLs within the styleUrls property of components.

There is a check in the [`isStyleUrlResolvable`](https://github.com/angular/angular/blob/master/modules/angular2/src/compiler/style_url_resolver.ts#L12) function:

```
export function isStyleUrlResolvable(url: string): boolean {
  if (isBlank(url) || url.length === 0 || url[0] == '/') return false; // <-----
    var schemeMatch = RegExpWrapper.firstMatch(_urlWithSchemaRe, url);
    return isBlank(schemeMatch) || schemeMatch[1] == 'package' || schemeMatch[1] == 'asset';
}
```

I wonder if it's something normal?
Thanks!
Thierry

**Comment by matsko** [comment] 2016-02-08 22:27
@tbosch any idea why this happened?

**Comment by diestrin** [comment] 2016-02-10 21:00
If I give it a relative url (to the file) it will resolve it with the browser's url. If I give it an absolute path to the file, it does not fetch the files because it's not a valid url, thanks to the **isStyleUrlResolvable** function. How can I make this to work?

**Comment by pxwise** [comment] 2016-02-10 22:28
Would be nice to use absolute paths... currently I'm working around with:

```
const ORIGIN = window.location.protocol + '//' + window.location.hostname + (window.location.port ? ':' + window.location.port : '');
const myStyleUrl = ORIGIN + '/absolute/path/to/my.css';
```

but we shouldn't expect window to be around for server rendering.

**Comment by diestrin** [comment] 2016-02-15 15:05
@pxwise actually, it doesn't work. [This regex](https://github.com/angular/angular/blob/master/modules/angular2/src/compiler/style_url_resolver.ts#L13) is preventing the load because of a protocol present in the path. :(

**Comment by iamdavidfrancis** [comment] 2016-09-27 15:57
I was able to get it to work locally on my machine by changing the `_cssImportRe` to 

    /(?:@import\s+(?:url\()?\s*(?:(?:['"]([^'"]*))|^([^;\)\s]*))[^;]*;?)|(http(?:s)?:\/\/.+)$/g

I added another capture group that will match any string starting with `http://` or `https://` which allows the [extractStyleUrls](https://github.com/angular/angular/blob/master/modules/@angular/compiler/src/style_url_resolver.ts#L30) function to read the url.

I also changed the [isStyleUrlResolvable](https://github.com/angular/angular/blob/master/modules/@angular/compiler/src/style_url_resolver.ts#L20) method's return value to include `http` and `https` schemes.

I'm willing to submit a PR with my fix if it's acceptable. If not, I'll wait for a proper fix here.

**Comment by vicb** [comment] 2016-10-07 18:44
duplicate of #4974

**Closed by vicb** 2016-10-07 18:44 UTC
Labels: comp: core & compiler
