### ISSUE TITLE
FormControlName ngOnDestroy does not remove validators from FormControl

### ISSUE THREAD

**Issue by CSchulz** [angular/angular#25386] opened 2018-08-08 14:56 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
FormControlName registers the validators on the given FormControl and does not remove them on destroy.

## Expected behavior
FormControlName registers the validators on the given FormControl and should remove them on destroy.

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-ym2gjq

Check the "check me" check and remove the check. The form statusChange keeps the invalid value and the form has the valid state.

This happens because the ngOnDestroy in the FormControlName just removes itself from the directives list and do not change the corresponding FormControl.

https://github.com/angular/angular/blob/master/packages/forms/src/directives/reactive_directives/form_group_directive.ts#L109

## Environment
Angular version: 6.1.2

**Comment by kara** [comment] 2018-08-09 22:43
Dupe of https://github.com/angular/angular/issues/19081

**Closed by kara** 2018-08-09 22:43 UTC
Labels: comp: forms
