### ISSUE TITLE
Enable ivy in angular 8  - production build got failed

### ISSUE THREAD

**Issue by kumaresan-subramani** [angular/angular#30818] opened 2019-06-01 08:11 UTC
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

Yes

### Description

I have created an angular project with **enabling ivy** mode using **below commands**

> ng new hello-ivy --enable-ivy

When I try to **serve** my application using below command 

> ng serve

it does not throw any compilation error but when I try to load this in browser [chrome] it throws below error:

![Screenshot (259)](https://user-images.githubusercontent.com/36756050/58745557-f816f080-846f-11e9-8ef5-ad019d942813.png)

**When i try to take prod build using below command**

> ng build --prod

it throws below compilation error :

![Screenshot (260)](https://user-images.githubusercontent.com/36756050/58745570-21d01780-8470-11e9-8409-59a1455d1fe0.png)

> I don't know why this issue occurs

## 🔬 Minimal Reproduction

1. Download below sample - 
[ivySample.zip](https://github.com/angular/angular-cli/files/3243558/ivySample.zip)

2. Give below command to install our third-party package

> npm i @syncfusion/ej2-angular grids 

**Or Download this and place it inside node_modules folder** 

## 🌍 Your Environment
<pre><code>

</code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 8.0.1
Node: 10.16.0
OS: win32 x64
Angular: 8.0.0
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.1
@angular-devkit/build-angular     0.800.1
@angular-devkit/build-optimizer   0.800.1
@angular-devkit/build-webpack     0.800.1
@angular-devkit/core              8.0.1
@angular-devkit/schematics        8.0.1
@angular/cli                      8.0.1
@ngtools/webpack                  8.0.1
@schematics/angular               8.0.1
@schematics/update                0.800.1
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.30.0
</pre>

**Anything else relevant?**

**Comment by petebacondarwin** [comment] 2019-06-03 13:52
I notice that you are running Angular v8.0.1. This is not the correct version for trying out IVY. You should install the `next` version. E.g.

```
yarn add @angular/compiler-cli@next
...
```

**Comment by alexzuza** [comment] 2019-06-03 20:06
@petebacondarwin

Just tried it with  "@angular/compiler-cli": "next", which is 8.1.0-beta.0

Seems Esm5ReflectionHost looks for "decorators" static property of function declaration inside IIFE and will never find.

**ej2-angular-grids.es5.js**
```

var GridAllModule = /** @class */ (function () {
    function GridAllModule() { <========== at this level
    }
    return GridAllModule;
}());
GridAllModule.decorators = [ 
    { type: NgModule, args: [{...
```

From source code

https://github.com/angular/angular/blob/815443313044e0ec0ec87af588d09eda6b88f0c8/packages/compiler-cli/ngcc/src/host/esm5_host.ts#L304-L310

**Comment by JoostK** [comment] 2019-06-03 20:10
@alexzuza It's known, see #30795

**Comment by kumaresan-subramani** [comment] 2019-06-06 05:11
HI @JoostK ,

Is there any update on this?

Thanks in advance

**Comment by vgb1993** [comment] 2019-06-06 18:17
What's the status of this? I get the same error: 

ERROR in Unexpected value 'PostService in C:/myAngularApp/src/app/service/posts.
component.ts' declared by the module 'AppModule in C:/myAngularApp/src/app/app.m
odule.ts'. Please add a @Pipe/@Directive/@component annotation.

**Comment by kumaresan-subramani** [comment] 2019-06-11 13:34
HI Team,

Any update on this?

**Comment by kumaresan-subramani** [comment] 2019-06-14 04:48
HI @JoostK ,

Can we get any update regarding this?

**Comment by petebacondarwin** [comment] 2019-06-28 15:29
This should be fixed in v8.1.0-rc.0 - @kumaresan-subramani can you check?

**Comment by kumaresan-subramani** [comment] 2019-07-01 05:52
HI @petebacondarwin , When should i expect this release?

**Comment by JoostK** [comment] 2019-07-01 05:57
@kumaresan-subramani it's already on NPM

**Comment by kumaresan-subramani** [comment] 2019-07-01 06:01
okay @JoostK , let me check and will update you.

Thanks for your Fast reply

**Comment by kumaresan-subramani** [comment] 2019-07-01 06:03
Have one more dooubt.

may i need to change angular-cli version ? or else just **@angular/compiler-cli** package

**Comment by JoostK** [comment] 2019-07-01 06:26
@kumaresan-subramani Please update everything Angular related: all `@angular` packages together with `@angular/angular-cli` and also `@angular-devkit`

**Comment by kumaresan-subramani** [comment] 2019-07-01 10:00
HI @JoostK ,

Still application not working in Angular IVY mode but working fine in normal mode.

### Repo steps

1. sample - 

[sample.zip](https://github.com/angular/angular/files/3344978/sample.zip)

2. Give below commands

> npm i

> npm i @syncfusion/ej2-angular-grids

3. Then give - "ng serve"

You will see below error:

![Screenshot (5)](https://user-images.githubusercontent.com/36756050/60427833-26295500-9c15-11e9-88e0-889f6abb1b13.png)
![Screenshot (4)](https://user-images.githubusercontent.com/36756050/60427835-26295500-9c15-11e9-9958-e434d26d0f36.png)

**Comment by kumaresan-subramani** [comment] 2019-07-01 10:12
This is my actual code:
```
import { Component, OnInit } from '@angular/core';
import { data } from './datasource';

@Component({
    selector: 'app-root',
    template: `<ejs-grid [dataSource]='data'>
                <e-columns>
                    <e-column field='OrderID' headerText='Order ID' textAlign='Right' width=90></e-column>
                    <e-column field='CustomerID' headerText='Customer ID' width=120></e-column>
                    <e-column field='Freight' headerText='Freight' textAlign='Right' format='C2' width=90></e-column>
                    <e-column field='OrderDate' headerText='Order Date' textAlign='Right' format='yMd' width=120></e-column>
                </e-columns>
                </ejs-grid>`
})
export class AppComponent implements OnInit {

    public data: object[];

    ngOnInit(): void {
        this.data = data;
    }
}
```

While having this i have faced above error so that i have removed **dataSource** property after that i haven't face any compilation error and control also not get render

Any idea reg this?

**Comment by petebacondarwin** [comment] 2019-07-01 10:33
The error is in the IVY compiler template type checker... It looks, from first glance, like the compiler is not recognizing the `<esj-grid>` tag as a component that has an input called `dataSource`. 

I think this is because the ej2 components use a dynamic mixin approach to creating their components and this component doesn't statically declare `dataSource` as a property on the `GridComponent` class. See https://github.com/syncfusion/ej2-angular-ui-components/blob/2b12b0202728b6e634cb1c8adb9650b2843fdbd0/components/grids/src/grid/grid.component.ts

**Comment by petebacondarwin** [comment] 2019-07-01 10:36
It would be interesting to see if this project can be compiled using the ngtsc compiler from source which could show that the problem is in the ngcc compiler.

**Comment by kumaresan-subramani** [comment] 2019-07-01 10:42
HI @petebacondarwin ,

We haven't use dynamic mixin approach to create our component.

**Comment by petebacondarwin** [comment] 2019-07-01 12:51
> We haven't use dynamic mixin approach to create our component.

By dynamic mixin approach I am referring to this line of code:

```
@ComponentMixins([ComponentBase])
```

I accept that this might be a red herring in this case as the problem is more likely caused by the component not having the relevant input declared as a typed property on the class.

But it is likely to have an impact in the compiler knowing whether relevant lifecycle methods are available on the component.

**Comment by kumaresan-subramani** [comment] 2019-07-30 05:02
HI @alxhub ,

Any update on this query

**Comment by kumaresan-subramani** [comment] 2019-07-30 06:13
Hi @JoostK ,

I have tried your workaround, it wont throws any errors and also control not get render while using below commands

> ng build --prod

> ng serve --prod

While using "ng serve" command it throws below error with your workaround [https://github.com/angular/angular/issues/30080#issuecomment-500499410].

![Screenshot (8)](https://user-images.githubusercontent.com/36756050/62104889-8b2ca500-b2be-11e9-92c2-2f3a5640112e.png)


## Repo steps

1. Download sample- 
[sample.zip](https://github.com/angular/angular/files/3445394/sample.zip)

2. Give below commands

> npm i

> ng serve 
               - you will see reported issue

> ng build --prod 
                 - No errors and run using **live-serve or web-server** controls not get rendered

**Comment by kumaresan-subramani** [comment] 2019-09-03 07:31
@JoostK  && @alan-agius4 ,

Is there any other way to resolve my issue?

**Comment by kumaresan-subramani** [comment] 2019-09-05 13:29
@alxhub , 

I am facing reported issue since angular-cli version 8.1.0-next. can I get any update regarding this issue?

**Comment by kumaresan-subramani** [comment] 2019-10-09 04:48
Hi @alan-agius4 ,

Can you update on this? still, i am facing this error

**Comment by JoostK** [comment] 2019-10-09 06:03
@kumaresan-subramani the issue with the type checker has not been resolved yet, as it's quite tricky to deal with properly. We are working on implementing additional `"strict*"` flags so that the type checking can be less strict for the time being, which we hope to land within the coming two weeks.

**Comment by kumaresan-subramani** [comment] 2019-10-09 06:08
@JoostK , thanks for your reply.

I just want to ensure whether this is fixed or not.

**Comment by kumaresan-subramani** [comment] 2019-10-18 09:28
@JoostK ,

I am facing the same issue in latest **version 8.3.12** while using command `ng serve`

### I thought issue occurs due to Ivy compilation. please refer below image:

While it goes `refreshChildComponets` ,ethod there is `ejs-grid` component but `datasource` property has not been included.

![Screenshot (5)](https://user-images.githubusercontent.com/36756050/67081528-f34fa080-f1b4-11e9-85c4-f32053b89814.png)


### In detail - >

**First it takes component property from `app.compnent.ts` file**

![Screenshot (8)_LI](https://user-images.githubusercontent.com/36756050/67081855-a0c2b400-f1b5-11e9-9ed7-23bcd57231cd.jpg)

**After that, it goes `ɵɵproperty()` to update component property:**

![Screenshot (9)](https://user-images.githubusercontent.com/36756050/67082216-49711380-f1b6-11e9-9a88-8a8aeb8507ea.png)

Here, the **property** [datasource] has not been updated correctly so that when it goes to `elementPropertyInternal()` method, it throws an error.

![Screenshot (11)](https://user-images.githubusercontent.com/36756050/67082602-111e0500-f1b7-11e9-8239-4f3c9a2a4784.png)

### So that it throws error, due to `validateAgainstUnknownProperties()` method:

![Screenshot (13)](https://user-images.githubusercontent.com/36756050/67082865-a3bea400-f1b7-11e9-81d4-8bd73c8b0eb4.png)


### Error screenshot
![Screenshot (4)](https://user-images.githubusercontent.com/36756050/67082914-bafd9180-f1b7-11e9-9b96-7ca207f01a85.png)

**Comment by kumaresan-subramani** [comment] 2019-10-18 10:46
@JoostK  || @alan-agius4 ,

### at least, please provide a workaround for this.

**Comment by JoostK** [comment] 2019-10-18 10:57
@kumaresan-subramani I have a feeling there's an issue with compiling the library that has `ejs-grid` using ngcc, which results in the `ejs-grid` component not representing a component. You are using Ivy in v8.x, which has not received relevant Ivy fixes for a very long time, so I would request you try Ivy with the latest 9.x next release.

**Comment by kumaresan-subramani** [comment] 2019-10-18 11:03
Thanks @JoostK , i will check and update you

**Comment by kumaresan-subramani** [comment] 2019-10-18 11:31
@JoostK ,

In the latest v9.0.0-next.12 angular/CLI version, it won't throw any console and compilation error while using below command

> ng serve

And control also not get rendered, refer below image:

![Screenshot (15)](https://user-images.githubusercontent.com/36756050/67090914-e3da5280-f1c8-11e9-88c5-d58d7bcbed8c.png)

**Comment by kumaresan-subramani** [comment] 2019-10-25 04:15
Hi @JoostK ,

Is below relate to this issue:

https://github.com/angular/angular/pull/33131

And I am facing same issue in latest version which got released 23rd

**Comment by JoostK** [comment] 2019-11-17 15:19
`@syncfusion/ej2-ng-grids` is not bootstrapping as its lifecycle methods are provided [by a mixin mechanism](https://github.com/syncfusion/ej2-ng-grids/blob/69986218e4f67a5a1fdd3d59dfe2b79316bcdf95/src/grid/grid.component.ts#L95) that are not visible to the Ivy runtime, as they are bound too late. Related issue: #31495

**Comment by kumaresan-subramani** [comment] 2019-11-17 23:11
@JoostK , This is deprecated package. Try @syncfusion/ej2-angular-grid, which is bootraped properly. And i have used ng-packagr to generate ej2-angular-grid package.

**Comment by JoostK** [comment] 2019-11-18 16:24
@kumaresan-subramani Ah, I'm _super_ confused by all this, but it appears I did test `@syncfusion/ej2-angular-grid` and it's basically failing because of the same reason: the `@ComponentMixins([ComponentBase])` is applied after the Ivy runtime has captured the component's details, so the overridden lifecycle hooks are never called.

**Comment by PritiMaurya** [comment] 2019-11-24 06:18
ERROR in Failed to find exported name of node (class BsDatepickerDayDecoratorComponent {
}) 

I am getting this error

**Comment by kumaresan-subramani** [comment] 2019-11-24 06:21
> ERROR in Failed to find exported name of node (class BsDatepickerDayDecoratorComponent {
> })
> 
> I am getting this error

@PritiMaurya , can you explain in detail please

**Comment by PritiMaurya** [comment] 2019-11-24 07:50
my project is in angular 8 i want enable Ivy in my project but after enable that I am getting error in ngx bootstrap

**Comment by kumaresan-subramani** [comment] 2019-12-03 07:12
@JoostK ,

Any update on this issue?

**Comment by kolkov** [comment] 2019-12-03 07:25
@kumaresan-subramani try 9.0.0-rc.4, maybe this fixed in next versions.

**Comment by kumaresan-subramani** [comment] 2019-12-03 07:27
@kolkov , i have already tried but same issue occurs.

**Comment by kolkov** [comment] 2019-12-03 07:35
@kumaresan-subramani I use 9.0.0 beats and rcs versions for a long time, it's works as expected.

**Comment by kumaresan-subramani** [comment] 2019-12-03 07:50
@kolkov ,

Refer below issue this is cause of problem https://github.com/angular/angular/issues/31495

**Comment by kolkov** [comment] 2019-12-03 08:02
@kumaresan-subramani I think we need to fix all external packages that caused this issue.

**Comment by kumaresan-subramani** [comment] 2019-12-03 08:04
@kolkov , Thanks,
Finally you understood my problem....
when can i expect issue fix

**Comment by petebacondarwin** [comment] 2019-12-09 16:06
Moving the discussion to #31495.

**Closed by petebacondarwin** 2019-12-09 16:07 UTC
Labels: comp: ivy, freq1: low, severity3: broken, type: bug/fix
