### ISSUE TITLE
Awesome dev experience: Can we detect infinite loops in change detection?

### ISSUE THREAD

**Issue by matanlurey** [angular/angular#2947] opened 2015-07-08 23:48 UTC
Right now, it's possibly to hook up a listener on `onChange` or `onAllChangesDone`, and have it trigger a change, which in turn, will cause the function to be called again, ad-infinitum. In dev mode, could Angular detect a loop that will likely never complete (maybe > 10 times?) and throw/fail?

**Comment by mhevery** [comment] 2015-07-22 00:30
Change detection only runs once in angular, by design. Can you post code which can repro the problem.

**Comment by matanlurey** [comment] 2015-07-22 03:29
Sure, let me clarify, because we have the onAllChangesDone lifecycle event, you could update the model which triggers a child update which triggers the event, so on and so forth. Does that make sense? I can create a repro but I feel like this is a simple enough case to understand ;)

**Comment by mhevery** [comment] 2015-07-27 18:16
onAllChangesDone, can not change model. If it did the dev mode check would fail. Ng2 does not allow infinite digest. There is a strict limit of one in ng2.

Do you have a use case which reproduces this?

**Comment by mhevery** [comment] 2015-07-27 22:41
Per discussion with @matanlurey Closing, reopen when you have repro case.

**Closed by mhevery** 2015-07-27 22:41 UTC
Labels: comp: core/change_detection, hotlist: GT, P3: important
