### ISSUE TITLE
ng xi18n generation for app with multiple components

### ISSUE THREAD

**Issue by ecl66** [angular/angular#30537] opened 2019-05-17 13:39 UTC
I am trying to generate xlf files for translating an Angular app constructed around several components (each being in a subfolder of the app/src main folder).
When I run ng xi18n to generate xlf translation, only one component is being analyzed and the output only contains translation source for the html of that component. All others seems to be ignored. Am I doing something wrong or is this a general issue with CLI?
Thanks a lot,
Emmanuel

**Comment by hugo-valcourt** [comment] 2019-08-20 13:23
I have the same issue

**Comment by petebacondarwin** [comment] 2020-05-26 12:08
@ecl66 or @hugo-valcourt - please can you provide a reproduction of this issue? Or if it turned out that it was not an issue can you confirm so that we can close this issue?

This is not how the message extraction should work but we cannot investigate without a reproduction.

**Comment by petebacondarwin** [comment] 2020-08-13 08:22
Closing due to now reproduction.

**Closed by petebacondarwin** 2020-08-13 08:22 UTC
Labels: comp: i18n, state: Needs repro, triage #1
