### ISSUE TITLE
@ContentChild no longer working with ng-content for Angular 9

### ISSUE THREAD

**Issue by rveerd** [angular/angular#37255] opened 2020-05-22 14:30 UTC
# 🐞 bug report

### Affected Package

Not sure.

### Is this a regression?

Yes, it used to work in the latest version of Angular 8.

### Description

`@ContentChild` returns `undefined` for projected content using `ng-content` when using attribute selector for the component.

## 🔬 Minimal Reproduction

Component:

```ts
import { Component, ContentChild } from '@angular/core';
import { MenuTriggerDirective } from '../menu-trigger.directive';

@Component({
  selector: '[appMenuItem]',
  templateUrl: './menu-item.component.html',
  styleUrls: ['./menu-item.component.scss'],
  host: {
    '[class.app-menu-heading]': 'isHeading'
  }
})
export class MenuItemComponent {
  @ContentChild(MenuTriggerDirective) menuTrigger: MenuTriggerDirective;

  get isHeading() {
    return this.menuTrigger != null;
  }

  constructor() { }
}
```

Template:

```html
<div class="d-flex align-items-center">
  <div class="flex-grow-1">
    <ng-content></ng-content>
  </div>
  <div class="app-menu-toggle">
    <i class="fas fa-chevron-right fa-fw"></i>
  </div>
</div>
```

Usage:

```html
<button appMenuItem [appMenuTrigger]="subMenu">File</button>
<app-menu-group #subMenu>
  <button appMenuItem>New</button>
  <button appMenuItem>Open</button>
  <button appMenuItem>Save</button>
</app-menu-group>
```

With Angular 8, `menuTrigger` was defined and `isHeading` returns `true` for the `MenuItemComponent` for the "File" `<button>`.

With Angular 9, `menuTrigger` is `undefined`.

I have seen that `@ContentChild` and `@ContentChildren` have changed as described [here](https://angular.io/guide/ivy-compatibility-examples#contentchildren-queries-only-match-direct-children-by-default). I have also seen issues that might may be related but those are mainly about `ng-container`.

I cannot use the solutions/workaround described:

1. `@ContentChildren` also returns no items, even with `descendants: true`.
2. Rewriting may be possible but I do not see how this could be done.

When I use the element syntax (add and `app-menu-item` to the selectors) instead of the attribute syntax, it does work:

```html
<app-menu-item>
  <button [appMenuTrigger]="subMenu">File</button>
</app-menu-item>
```

I am not sure if this is as intended. If it is, it should be documented as a breaking change.

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.1.7
Node: 12.16.3
OS: win32 x64

Angular: 9.1.9
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.7
@angular-devkit/build-angular     0.901.7
@angular-devkit/build-optimizer   0.901.7
@angular-devkit/build-webpack     0.901.7
@angular-devkit/core              9.1.7
@angular-devkit/schematics        9.1.7
@angular/cli                      9.1.7
@ngtools/webpack                  9.1.7
@schematics/angular               9.1.7
@schematics/update                0.901.7
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0
</code></pre>

**Comment by pkozlowski-opensource** [comment] 2020-05-22 14:40
@rveerd your situation has nothing to do with `ng-container` or the `descendants` flag. It is about a known breaking change (we consider this a bug fix!) where previously a content query would pick-up directives from a host element.

I've provided responses to situations similar to yours in the past - see #36945. I'm going to close this one as a duplicate of #36945. If you need further clarifications please provide a minimal reproduce scenario using https://stackblitz.com/

**Closed by pkozlowski-opensource** 2020-05-22 14:40 UTC
Labels: comp: core, core: queries
