### ISSUE TITLE
HttpInterceptor catchError cannot see a 303 response

### ISSUE THREAD

**Issue by thomasdtucker** [angular/angular#29037] opened 2019-02-28 20:50 UTC
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/common/http;

### Is this a regression?
Unknown. I have only handled 2xx responses before

### Description

In a request being made with Angular 7 running server side on node express, Angular is issuing an API request, with observe: response, to an endpoint which is returning a 303. That 303 is then automatically called and the result of the 303 shows up in the interceptor, but the 303 itself does not. We want to intercept the 303 itself.

<pre><code>
Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.12.4
@angular-devkit/build-angular     0.12.4
@angular-devkit/build-optimizer   0.12.4
@angular-devkit/build-webpack     0.12.4
@angular-devkit/core              7.2.4
@angular-devkit/schematics        7.3.1
@angular/cli                      7.3.1
@angular/compiler-cli             7.2.7
@ngtools/webpack                  7.2.4
@schematics/angular               7.3.1
@schematics/update                0.13.1
rxjs                              6.4.0
typescript                        3.1.6
webpack                           4.28.4
</code></pre>

**Anything else relevant?**
SSR with Universal

**Comment by pkaufi** [comment] 2019-03-01 05:44
I guess those two are related: https://github.com/angular/angular/issues/28966

**Comment by amcnea** [comment] 2019-03-01 17:31
I have been having similar issues around this.

@pkaufi I am not sure if this is related to #28966 as that is Client side, and this is Server side.  The Node.js core request library can intercept a 303.

I know browsers are hiding this and there isn't much you can do about that except complain, but I find this behavior very odd because 303 means: we are NOT giving the resource you requested, but here is a related resource that is NOT the resource you requested.  It really seems like at the 303 stage you should be able to decide if you want to get the other resource, instead of being given the non-requested resource as if it was the resource you requested.

**Comment by pkaufi** [comment] 2019-03-02 09:29
You're right @amcnea, they're not related. I must've overread the server side part, my apologies.

**Comment by trotyl** [comment] 2019-03-02 14:53
@amcnea It doesn't matter what the platform is, Angular `HttpClient` is built on XHR by default in both client and server side ([`xhr2`](https://www.npmjs.com/package/xhr2) package used). Any redirection is not exposed to client, which is the expected behavior defined by XHR.

**Comment by alxhub** [comment] 2019-04-23 22:35
Closing as this is effectively a duplicate of #28966. There is no redirect handling in `HttpClient` whatsoever, it's entirely up to the browser how it will interpret 3xx responses.

**Closed by alxhub** 2019-04-23 22:35 UTC
Labels: comp: common/http
