### ISSUE TITLE
New @Required() decorator to enforce usage of @Intput()

### ISSUE THREAD

**Issue by TheColorRed** [angular/angular#49748] opened 2023-04-07 17:47 UTC
### Which @angular/* package(s) are relevant/related to the feature request?

@angular/core

### Description

It would be nice to require some inputs to be enforced on the component. Based on this [stackoverflow answer](https://stackoverflow.com/questions/35528395/make-directive-input-required), It would be nice to not have to put the required elements in the selector, then add an input for each one:

```typescript
/** Note: requires the [a] attribute to be passed */
@Component({
  selector: 'my-dir[a]', // <-- use attribute selector along with tag to ensure both tag name and attribute are used to "select" element by Angular in DOM
});
export class MyComponent {
  @Input() a: number;
}
```

### Proposed solution

By adding a `@Required()` decorator could be a solution.

```typescript
@Component({
  selector: 'example-component',
  template: ''
})
export class ExampleComponent {

  @Required()
  @Input()
  myInput: string;

  @Required()
  @Input()
  // Should not have a default value (other than undefined)
  invalidUsage: string = 'Hello';

}
```

When executed, an error is thrown if `myInput` doesn't have a value.

**Comment by JoostK** [comment] 2023-04-07 18:04
This is a duplicate of #37706, which is being added in Angular 16 using `@Input({ required: true })` syntax.

**Closed by JoostK** 2023-04-07 18:04 UTC
