### ISSUE TITLE
docs: forms API - missing documentation for AbstractControl.get

### ISSUE THREAD

**Issue by Mufasa** [angular/angular#16255] opened 2017-04-22 13:59 UTC
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
The documentation page for **FormGroup** contains a link to **AbstractControl.get**. When I click on this link I get a 404 page.

**Expected behavior**
I expect to see the documentation for the **get** method on **AbstractControl**

**Minimal reproduction of the problem with instructions**
- Navigate to https://angular.io/docs/ts/latest/api/forms/index/FormGroup-class.html#!#controls-anchor
- Look at the documentation for the **contains** method
- Click on the link in there to **AbstractControl.get**
- You will end up on a 404 page

**What is the motivation / use case for changing the behavior?**
I would like to know how to use the **get** method

**Please tell us about your environment:**
macOS Sierra v10.12.4

* **Angular version:** 4.1.0-rc.0

* **Browser:** Google Chrome Browser Version 57.0.2987.133 (64-bit)

**Comment by kara** [comment] 2017-08-11 20:47
Duplicate of https://github.com/angular/angular/issues/17088 (keeping the other, as it contains more info).

**Closed by kara** 2017-08-11 20:47 UTC
Labels: comp: docs, comp: forms
