### ISSUE TITLE
Lazy-loading into named router outlet leaves orphaned primary outlet content

### ISSUE THREAD

**Issue by isaacplmann** [angular/angular#12517] opened 2016-10-25 14:59 UTC
**I'm submitting a ...**  (check one with "x")

```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
If you lazy load a module into a named (auxiliary) router outlet, two bad things happen:
1. The contents of the lazy loaded component are inserted into the _primary_ outlet, not the named one.
2. The existing contents of the primary outlet are left in place and are not removed on subsequent route changes.

**Expected behavior**
1. The lazy loaded component is placed in the named router outlet.
2. The primary router outlet is unaffected.

**Minimal reproduction of the problem with instructions**
*Plunkr:* [This plunker](http://plnkr.co/edit/LqEJY1IZbb1XHUkE4YfC?p=preview) reproduces the bug I described above.

*Or github repo:*
- git clone https://github.com/isaacplmann/ng2-lazy-named-router-outlet
- npm install
- ng serve
- Follow instructions on the page

**What is the motivation / use case for changing the behavior?**
I want to be able to lazy load auxiliary routes just like primary ones.

**Please tell us about your environment:**

- **Angular version:** 2.1.1
- **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
  
  
- **Language:** [all | TypeScript X.X | ES6/7 | ES5]
- **Node (for AoT issues):** `node --version` =

**Comment by vicb** [comment] 2016-10-26 02:10
What is your router version ?

**Comment by intellix** [comment] 2016-10-26 11:25
This sounds like the issue I'm having locally but couldn't reproduce quite the same in a plnkr. You can see an example of lazy loading in a plnkr in my issue which is similar to this one: https://github.com/angular/angular/issues/12360

**Comment by isaacplmann** [comment] 2016-10-26 12:02
@vicb The router version is 3.1.1.
@intellix Thanks for showing me how lazy loading works in a plunker.

[This plunker](http://plnkr.co/edit/LqEJY1IZbb1XHUkE4YfC?p=preview) reproduces the bug I described above.

**Comment by isaacplmann** [comment] 2016-10-26 15:44
3.1.1

**Comment by isaacplmann** [comment] 2016-10-31 13:36
With recent changes to the router, the plunker I created before now throws an error instead of loading the auxiliary content into the primary outlet.

I've created a [work around plunker](http://plnkr.co/edit/LqEJY1IZbb1XHUkE4YfC?p=preview) that uses a shell component (No content, just a `<router-outlet>`) to load things correctly.

The routing looks like this.

app.module.ts:

    {
      component: ShellComponent,
      path: 'account',
      outlet: 'right',
      loadChildren: 'src/account.module#AccountModule',
    },

account.module.ts:

    {
      path: '',
      pathMatch: 'full',
      component: AccountComponent
    }


I still think it's a pain (and non-obvious) to have to create a shell component.  But the severity in my mind just dropped from a blocker to a mild annoyance.

**Comment by vsavkin** [comment] 2016-10-31 22:54
The issue has been fixed in master. The reason why you need a shell component is described here:
https://github.com/angular/angular/pull/12412

**Closed by vsavkin** 2016-10-31 22:54 UTC
Labels: comp: router

**Comment by chenyingyin** [comment] 2016-12-01 05:26
![default](https://cloud.githubusercontent.com/assets/24284270/20782714/60f05eaa-b7c9-11e6-9006-f7beb8bef322.png)

**Comment by evanjmg** [comment] 2017-01-17 10:00
@isaacplmann your plunkr doesn't seem to work and is not complete. Could you use the account summary component in your nested route? I really want a shell component in my lazy loaded module - this is important for breadcrumbs and initialising services.
