### ISSUE TITLE
Incorrect return type on `KeyValuePipe`

### ISSUE THREAD

**Issue by rafaelss95** [angular/angular#43883] opened 2021-10-18 20:59 UTC
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

No

### Description

Consider this snippet:

```ts
import { KeyValue } from '@angular/common';
import { ChangeDetectionStrategy, Component } from '@angular/core';

const items = { a: { someKey: true, }, b: { someKey: false, } } as const

type Keys = keyof typeof items;

@Component({
  changeDetection: ChangeDetectionStrategy.OnPush,
  selector: 'my-app',
  template: `
    <h1>Items:</h1>
    <!-- error here -->
    <div *ngFor="let item of items | keyvalue; trackBy: trackByKey">
      {{ item.key | json }}
    </div>
  `,
})
export class AppComponent  {
  readonly items = items;
  
  // Workaround: `KeyValue<string, typeof items[Keys]> `
  trackByKey(_: number, item: KeyValue<Keys, typeof items[Keys]>) {
    return item.key
  }
}
```

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-jmhewq

### Please provide the exception or error you saw

```true
> Type '(_: number, item: KeyValue<"a" | "b", { readonly someKey: true; } | { readonly someKey: false; }>) => "a" | "b"' is not assignable to type 'TrackByFunction<KeyValue<string, { readonly someKey: true; } | { readonly someKey: false; }>>'.
```

### Please provide the environment you discovered this bug in

```true
Angular CLI: 12.0.0
Node: 14.17.6
Package Manager: npm 7.24.1
OS: linux x64

Angular: 12.0.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, upgrade

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.0
@angular-devkit/build-angular   12.0.4
@angular-devkit/core            12.2.0
@angular-devkit/schematics      12.0.0
@angular/cdk                    12.2.0
@angular/material               12.2.0
@schematics/angular             12.0.0
rxjs                            6.6.7
typescript                      4.2.4
```

### Anything else?

Unless I'm missing something, it seems like the problem is that the `transform` doesn't infer the key types correctly. It returns `string` instead of `'key' | 'key2' | etc` (look at this [TS repl](https://www.typescriptlang.org/play?ssl=17&ssc=73&pln=16&pc=1#code/PTAEGICcFMHMEsD2A7U0AeAHRkAuoBjAGwEMBnM0AaWgE8A1EogV2gAV5NpQAKAxTPGgATUADNIiALagAFrlyYyALhAJcs5gCMAdPynASyWM1KRDx0yXNaiiLcGgAWAEwkSANgIBGAMxaATjFvMQAOMQBWLRdoUIIXAHZoAITfUIAGLUiEp2EtUNTgTBICAGsSWGgyYH0pFGAySAIizirgUroANyZWAH1BLh1cMgBKAChhaGJrbnhkXGhIMRLuGgYe6AAeKgAaUHoAPlAAbzHQc9AO2mVqAG4zi+6WaBv6e4BfMYmps24xZmQBFwSFQuEgRjIYhwUm2e0OPDmmGYuBuACVoCRhCgiLQALIkTCw-YHPb6YowABiyAA-DceCQbmtGM8iYc9lpGXRmaxWQcRqAALxHZDMKRaRYjG4AQUg4No2y5G15B3uk2mMHEAKBINAYIhUMgMKoaHQC2QwkoIrFizhBwRyCRKNA6P4kGEvNJ0nJ0CptN4DOoipZZDBc1gtvZnPWwdDxlt-KFoCt4sgktAMrlCujPJDkDDtpV33Vfy1wJQuvByEh0O2JrNFtAufzxPtjrRUxw7t2xNAAB9nRiscgcfjCd22YQvTNfXSA0yleOSaAOYHs1tFwnhaKU2mMyR5fOWYvC2rfprAWXQZXq4bW8ibiKiEQ+6AAZMxHMRJ6pN6Z-6o9yWwAqUyCIAA7sgezAaBEFLiuh48tB4GQa+yAgchfKClu1qpg+phEKqPwzOe2rlnqVYGkatp3k66KYtieIEryL6Ps+-ZvtAH7IF+k4-tONKzgBC4RsuQlHvGWFJtuErSrK+5ZoByosfhhHFiRl4VvqNbGhg9aWtJkDUYi94Dq6Xa2spT4vhxXE8WS-F+vSYk5rG4bEpGq6KU2cbEpuUk4buckHkGLl5j5hxHP2rGqWe-wXjq5E3kadbQOalDeW58LGbRHZusx-Z0UOI5MYullsah76fsI36-gJ-6ecJ7miQ14m+ZJyYyemQUKY1EVlfcIAQKlwgwAgKBfGM-BVvg8ALFIlACicoABscjbSNAaw3GCrB7O8HmrWQ62beITBkNAu2gO8y2UFNIaTSgIaaRR0IiAAknNC1PUlCIffyg1ndwGiA7QXCgIAKASgLNjayIgpiiOKoAAAYIVsADkJCoy+qNaKjew6PjByI3scwhoOoCwIg+DIyFWwZXjBOIzoQA)).

**Comment by JoostK** [comment] 2021-10-18 21:24
I believe this is working as expected, given that a subtype of `items` can be passed which may have additional properties to those in `Keys`. See [this SO answer for why `Object.keys()` returns `string[]`](https://stackoverflow.com/questions/55012174/why-doesnt-object-keys-return-a-keyof-type-in-typescript).

Closing as working as intended, but feel free to follow up.

**Closed by JoostK** 2021-10-18 21:24 UTC

**Comment by rafaelss95** [comment] 2021-11-17 03:48
Hey @JoostK, sorry to bother you again, but it looks like it's the last day before the bot lock this 😅. Did you get to take a look at it?
