### ISSUE TITLE
HttpParams does erroneous URL Encoding

### ISSUE THREAD

**Issue by NanoSpicer** [angular/angular#40797] opened 2021-02-11 10:05 UTC
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/common/http; concretely using the HttpParams API

### Is this a regression?
I do not know

### Description

This is what I was trying to do:
`cardData` holds a base64 encoded payload.

```typescript
private getAnnualReceiptPdfBlob(cardData: string, receiptId: string): Observable<any> {
    const queryParams = new HttpParams().append('cardData', cardData).append('receiptId', receiptId);
    const apiCall = `${environment.API_BASE_PATH}/api/Reading/receipt`;
    return this.httpClient.get(apiCall, {
      responseType: 'blob',
      params: queryParams
    });
 }
 ```
With this, the backend was not able to successfully decode the payload. 

If I did the codification myself like below, then it works:

```typescript
private getAnnualReceiptPdfBlob(cardData: string, receiptId: string): Observable<any> {
    const apiCall = `${environment.API_BASE_PATH}/api/Reading/receipt`;
    const queryParams = `?receiptId=${receiptId}&cardData=${encodeURIComponent(cardData)}`;
    return this.httpClient.get(`${apiCall}${queryParams}`, {
      responseType: 'blob'
    });
}
 ```

## 🔬 Minimal Reproduction

I cannot provide "samples" because the cardData holds sensitive information. But it's a base64 encoded string

## 🔥 Exception or Error

No errors, just a 400 from the backend which couldn't decode the data.

## 🌍  Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 11.1.0
Node: 14.15.0
OS: darwin x64

Angular: 11.1.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, material, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1101.0
@angular-devkit/build-angular   0.1101.0
@angular-devkit/core            11.1.0
@angular-devkit/schematics      11.1.0
@schematics/angular             11.1.0
@schematics/update              0.1101.0
rxjs                            6.6.3
typescript                      4.0.5
</code></pre>

**Comment by Gemorroj** [comment] 2021-02-11 10:08
see https://github.com/angular/angular/issues/11058
and possible fix https://github.com/angular/angular/issues/11058#issuecomment-717239897

**Comment by petebacondarwin** [comment] 2021-02-11 11:08
Yes, closing as a duplicate of #11058. Anyone want to attempt a PR to add the new codec to the framework (see https://github.com/angular/angular/issues/11058#issuecomment-636114557)?

**Closed by petebacondarwin** 2021-02-11 11:08 UTC

**Comment by Gemorroj** [comment] 2021-02-11 11:11
@petebacondarwin they didnt add the new codec. i dont know why.

**Comment by petebacondarwin** [comment] 2021-02-11 11:16
"they" being the Angular team? I don't believe there is a technical reason not to do this. The reason the core team has not implemented it yet is that we are working at capacity on other parts of the framework and this has not been high enough priority. That is why I suggested that a community contributor might like to take up the challenge. If there is a volunteer, I would be happy to help them with the process.

**Comment by solos** [comment] 2021-02-23 06:30
@petebacondarwin  what about this pr https://github.com/angular/angular/pull/40958 ? Please review it. Hope this problem could be solved as quickly as possible.
