### ISSUE TITLE
Iterable Differs incorrectly indicates required operations.

### ISSUE THREAD

**Issue by Humberd** [angular/angular#35641] opened 2020-02-23 14:43 UTC
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/core

### Is this a regression?

It did not work in 8.2.14 and it does not work in 9.0.3.

### Description

I have a collection `baseOrder`, which I track by `id` field and there are multiple items with that id. Then I remove the item from the index 1, then readd it in the same place, then remove, and readd, and so on. When removing the second time the `IterableDiffer` tells that, apart from just remove operation, there is also an additional operation -> position change (From index 3 to 1).

What is worth noting is that the collection order is correct - the item removed is gone and other elements didn't change place. But when listing the operations it says the item from index 3 has been moved to index 1). 

![image](https://user-images.githubusercontent.com/10242142/75114050-1999b700-5653-11ea-8f02-ba37099528bf.png)

```typescript
const _differs = iterableDiffers.find([]).create<RenderRow>((index, item) => {
  return item.data.id;
});

const baseOrder: RenderRow[] = [
  {data: {id: 'abc'}, dataIndex: 0},
  {data: {id: 'abc'}, dataIndex: 1},
  {data: {id: 'def'}, dataIndex: 2},
  {data: {id: 'def'}, dataIndex: 3},
  {data: {id: 'vwx'}, dataIndex: 4},
  {data: {id: 'xyz'}, dataIndex: 5},
];

const changedOrder: RenderRow[] = [
  {data: {id: 'abc'}, dataIndex: 0},
  {data: {id: 'def'}, dataIndex: 2},
  {data: {id: 'def'}, dataIndex: 3},
  {data: {id: 'vwx'}, dataIndex: 4},
  {data: {id: 'xyz'}, dataIndex: 5},
];

this._differs.diff(this.baseOrder);

// ---- STEP 1: I'm removing one element from index [1] ----
this._differs.diff(this.changedOrder);
this._differs.forEachOperation(console.log);
// 1 change: index 1 -> null

// ---- STEP 2: I'm readding the same element to index [1] ----
this._differs.diff(this.baseOrder);
this._differs.forEachOperation(console.log);
// 1 change: index null => 1

// ---- STEP 3: I'm removing that element from index [1] again (Should be the same as in STEP 1) ----
this._differs.diff(this.changedOrder);
this._differs.forEachOperation(console.log);
// 2 changes: index 1 -> null, index 3 -> 1

// !!! The differs' internal collection reflects the order CORRECTLY, but the operations, which Angular CDK  Table uses internally tells something else.
```

## 🔬 Minimal Reproduction

https://stackblitz.com/github/Humberd/iterable-differ-bug

</code></pre>
## 🌍  Your Environment

**Angular Version:**
<pre><code>Angular CLI: 9.0.3
Node: 13.7.0
OS: win32 x64

Angular: 9.0.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.3
@angular-devkit/build-angular     0.900.3
@angular-devkit/build-optimizer   0.900.3
@angular-devkit/build-webpack     0.900.3
@angular-devkit/core              9.0.3
@angular-devkit/schematics        9.0.3
@angular/cli                      9.0.3
@ngtools/webpack                  9.0.3
@schematics/angular               9.0.3
@schematics/update                0.900.3
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2

</code></pre>

**Anything else relevant?**

**Comment by Humberd** [comment] 2020-02-23 15:48
What I have found out is that it happens when when the following conditions are present:
1. There are 2 elements with the same id next to each other.
2. The element we remove and readd is directly before that pair from 1. 

So:

This triggers the additional reorder operation.
```typescript
const baseOrder: RenderRow[] = [
  {data: {id: 'abc'}, dataIndex: 0},
  {data: {id: 'def'}, dataIndex: 3},
  {data: {id: 'vwx'}, dataIndex: 4},
  {data: {id: 'vwx'}, dataIndex: 5},
];

const changedOrder: RenderRow[] = [
  {data: {id: 'abc'}, dataIndex: 0},
  {data: {id: 'vwx'}, dataIndex: 4},
  {data: {id: 'vwx'}, dataIndex: 5},
];
```

This works OK
```typescript
const baseOrder: RenderRow[] = [
  {data: {id: 'abc'}, dataIndex: 0},
  {data: {id: 'def'}, dataIndex: 3},
  {data: {id: 'vwx'}, dataIndex: 4},
  {data: {id: 'vwx'}, dataIndex: 5},
];

const changedOrder: RenderRow[] = [
  {data: {id: 'def'}, dataIndex: 3},
  {data: {id: 'vwx'}, dataIndex: 4},
  {data: {id: 'vwx'}, dataIndex: 5},
];
```

**Comment by pkozlowski-opensource** [comment] 2020-02-24 09:03
This sounds very similar to #23815 - @Humberd could you please have a look at the linked issue and let me know if you agree that this is a duplicate?

**Comment by Humberd** [comment] 2020-02-24 10:01
@pkozlowski-opensource Yes, that's the same issue.

**Comment by pkozlowski-opensource** [comment] 2020-02-24 10:03
@Humberd thnx for confirming, going to close it as a duplicate of  #23815

**Closed by pkozlowski-opensource** 2020-02-24 10:03 UTC
Labels: comp: core, flag: can be closed?, freq1: low, severity3: broken, type: bug/fix
