### ISSUE TITLE
CircleCI webhooks are sometimes triggered with long delay (or not at all) - causing `test_aio_preview` job to fail due to timeout

### ISSUE THREAD

**Issue by gkalpak** [angular/angular#27352] opened 2018-11-29 16:04 UTC
In the last couple of days (since 2018-11-28), CircleCI jobs seem to occasionally take a lot longer than usual to trigger the webhook on completed jobs.
As a result, the PR preview fails to be created (since it relies on the webhook of the `aio_preview` job pinging the preview server) and subsequently the `test_aio_preview` job fails (since it relies on the preview being available within 5 mins of the completion of the `aio_preview` job).

We had seen a couple of sporadic failures in the days before, but they seemed too isolated to pay attention.
- On 2018-11-28, @pkozlowski-opensource reported that PR #27322 had failed to create a preview, which resulted in its [test_aio_preview](https://circleci.com/gh/angular/angular/114342) failing. @petebacondarwin, looked at the preview server logs and there was no record of CircleCI pinging the preview server for the corresponding `aio_preview` job.
  Finally, the webhook was triggered 20+ mins after the `aio_preview` job's completion. At this point, we were able to restart the `test_aio_preview` job and get it to pass, as the preview was available.

- On 2018-11-29, @mgechev's PR #27339 hasn't received a preview after 60mins after `aio_preview` job's completion.
  I looked at the preview server logs and there is no record of CircleCI pinging the preview server for the latest [aio_preview](https://circleci.com/gh/angular/angular/115246) job.
  (Note: The same PR had its preview created normally for earlier commits.)

- On 2018-11-29, PR #27300's e7382d6 was also affected, with no preview after at least 30 mins after [aio_preview](https://circleci.com/gh/angular/angular/115657) job completion.

**Comment by IgorMinar** [comment] 2018-11-29 22:50
I updated the description because the jobs do get scheduled, but they sit in a queue for too long which occasionally causes the timeout of the test_aio_preview job.

CircleCI dashboard reports that our median queue time is currently 31min (peaking at over one hour!). That's very unexpected because previously we were nowhere close to this kind of CI backlog, so seeing it spike like this and remain this high is unusual.

<img width="443" alt="screen shot 2018-11-29 at 2 42 31 pm" src="https://user-images.githubusercontent.com/216296/49256808-1169b200-f3e5-11e8-8567-ba2fc3c5c124.png">

We'll need to follow up with CircleCI and have them provide more insights.

**Comment by IgorMinar** [comment] 2018-11-29 22:52
Also note that in the last few builds there has been no time spent in the queue (the gray line), so maybe there was something going on with CircleCI's infrastructure but has since been resolved?

**Comment by IgorMinar** [comment] 2018-11-29 22:53
Do we have any recent occurrences of this issue? One PR I just watched triggered all jobs immediately.

**Comment by gkalpak** [comment] 2018-11-29 23:56
By looking at the CircleCI logs, the last occurrence seems to be from 3 hours ago: https://circleci.com/workflow-run/022f136b-c68f-4796-818c-b32463bcc8a3

##
Note that the problem is NOT about our jobs timing out because of jobs staying long in the queue. The `test_aio_preview` job requires the `aio_preview` job, which means that it only starts polling the preview server for a preview AFTER the `aio_preview` job (which triggers the preview creation) has finished.

The problem is specifically with CircleCI not sending out webhook notifications (or sending them with a considerable delay (>60mins)).

##
CircleCI did have an issue 1 or 2 days ago which created a job backlog for them, but according to their status they have fixed it, worked through the backlog and are back to 100% operational for almost a day or so. Maybe that somehow affected their webhook notifications?

**Comment by IgorMinar** [comment] 2018-11-30 06:35
I filed https://support.circleci.com/hc/en-us/requests/43427 asking for the circleci support to look into this.

**Comment by IgorMinar** [comment] 2018-12-05 07:33
We've merged in #27458 as a workaround for this issue so that we no longer have PRs broken due to this problem.

**Comment by IgorMinar** [comment] 2018-12-11 23:57
CircleCI confirmed that the workaround is likely the best way forward on this because webhooks are still experimental.

**Closed by IgorMinar** 2018-12-11 23:57 UTC
Labels: comp: build & ci, freq2: medium, severity5: regression, type: bug/fix
