### ISSUE TITLE
Currency Pipe: Be able to set/change the default currency.

### ISSUE THREAD

**Issue by agusdutra** [angular/angular#25461] opened 2018-08-13 13:51 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[X ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

When using CurrencyPipe if you want to show a different currency than US Dollars, you have to set explicitly every time that you use the pipe in the templates.

`<span> {{ 1200.18 | currency }} </span>` 

**Output:** $ 1,200.18

`<span> {{ 1200.18 | currency:'GBP' }} </span>` 

**Output:** £1,200.18

## Expected behavior

Be able to set in the root module, the default currency that you want to use using `provide: CURRENCY_ID`
The currency symbol that is going to show by default when no currency is specified in the template, is the one defined in the loaded locale for that currency code.

For Example: 

**app.module.ts:** 

```
providers: {provide: CURRENCY_ID, useValue: 'GBP'}]
```

**component.html:** 

```
<span> {{1200.18 | currency }} </span>
``` 
If I'm using `LOCALE_ID = 'en'`

**Output**: £1,200.18 

If I'm using `LOCALE_ID = 'es'`

**Output**: 1.200,18 GBP

## What is the motivation / use case for changing the behavior?

I'm developing an application for a country where the Locale that we use, uses the symbol US$ for dollars.
So every time you use {{ 1200.18 | currency }} it outputs: US$ 1.200,18. And we don't want to use dollars.

We have a lot of currency outputs to display in our local currency (pesos, $) and found that expliciting it in every place we use, was not the best way to go.

We found a way of working this around, but for sure it's not the best option, I think this feature request would be a more suitable option.
What we did was change that 'US$' symbol for dollars: 

```
const currencySymbols = localeUy[LocaleDataIndex.Currencies];
currencySymbols['USD'] = ['$', '$']; // Previous value was : ['US$', '$']
registerLocaleData(localeUy, 'en');
```
That way, we could without expliciting in the templates the currency, show the code $ for currencies with the locale 'es-UY'

## Others:
Issue associated with the request: https://github.com/angular/angular/issues/22519

**Comment by MRMokwa** [comment] 2018-08-15 17:35
Yes, this is really necessary. Writing in every single template {{value | currency:'BRL'}} doesn't seem like a great solution.

**Comment by Wilt** [comment] 2018-09-13 09:32
The problem lies in this line:

    var currency = currencyCode || 'USD';

When no `currencyCode` is passed the fallback is simply a hardcoded string 'USD'. This could simply be changed to a constant

    var currency = currencyCode || CURRENCY_CODE;

```
`CURRENCY_CODE` could by default still be set to 'USD' but can be configured through a provider the same way like @agusdutra suggested in his answer.

```
  providers: [
      { provide: DEFAULT_CURRENCY_CODE, useValue: "EUR" },
  ],
```
I think this will make a lot of angular users very happy, there are an enormous amount of posts/issues on this topic.

**Comment by simeyla** [comment] 2018-10-21 19:10
No! The currency pipe encourages bad behavior in the first place.

We should be using the 'money pattern' and always storing currency alongside the value. This makes it infinitely easier if you decide at some future point to support multiple currencies.

Currency pipe should check to see which of `{ currency: string, amount: number } | number` is used for the value passed in and act accordingly. 

I wish they'd do this in the official pipe, but in the meantime I'm implementing this myself as my own pipe.

https://martinfowler.com/eaaCatalog/money.html

**Comment by MickL** [comment] 2018-10-23 12:09
If i register the language an set the locale:

```
registerLocaleData(localeDe, 'de');
// ...
providers: [
    {
      provide: LOCALE_ID,
      useValue: 'de',
    }
  ],
```

I expect the currency-code to change (to Euro). The format is changing from "$20.00" to "20,00 $" already, but the currency-code stays dollar.

**Comment by chaosmonster** [comment] 2018-10-23 12:17
I like the idea of a global `CURRENCY_ID` as a fallback, but I woudn't make it related to the `LOCALE_ID`. As @Wilt already pointed out where it can be found why not add a "easy first contribution" label to this?

**Comment by MickL** [comment] 2018-10-23 12:19
But the format is also related to LOCALE_ID ?

**Comment by agusdutra** [comment] 2018-10-23 12:20
@MickL the locale will change the way dollars is shown according to 'es' definition, but not the currency. Because dollars is set to default in currency. 
That is wat this feature request is about, to be able to set the currency in a general way similar to the locale.

**Comment by chaosmonster** [comment] 2018-10-23 12:33
@MickL Let me give you an example on why the approach to only use the `LOCALE_ID` would cause problems. 
Let's say I have a app that provides German (de) and English (en). And I have prices in Euro in this app. 
Your approach means that when I change the `LOCALE_ID` to en that my prices switch from Euro to GBR. 
When using a `CURRENCY_ID` those are separated and can change separate.

**Comment by MickL** [comment] 2018-10-23 12:37
Yes thats nice and i would appreciate that, but currently as of Angular 7 if you set locale_id it will change format from: `$ 20.00` to `20,00 $`. So if you want to change the currency independent from the language/locale then the whole locale-stuff needs to be refactored or you should find another way.

**Comment by agusdutra** [comment] 2018-10-23 12:46
The currency is already independent from the locale.
That change from $ 20.00 to 20,00 $ is because for the locale 'en' the symbol goes before the number and the decimal separator is a dot, and for 'es' goes after and the decimal separator is a comma.
The currency is never affected.
We are requesting a way to be able to set the default currency for the project, because today is set to dollars and no matter which locale you set, the currency will be dollars.

**Comment by chaosmonster** [comment] 2018-10-23 12:48
I can't find a global example so fast, but the Euro for example depends on the locale not the currency https://en.wikipedia.org/wiki/Language_and_the_euro#Summary so the formatting is dependent on the locale the currency I want to use as default is something different and should be made settable e.g with `CURRENCY_ID`

**Comment by DmitryEfimenko** [comment] 2019-02-11 09:33
@agusdutra  what happened to that PR of yours? This would be a great feature!

**Comment by agusdutra** [comment] 2019-02-11 12:21
@DmitryEfimenko I had some trouble with the CI and left it behind when I saw @gund was doing the same. But I'll open a new one.

**Comment by gund** [comment] 2019-02-11 14:11
@agusdutra I was working on this feature but then I found that some tests were failing even without my changes so I basically gaveup.

**Comment by nitrique** [comment] 2019-08-13 10:56
👍 as usual Americans thinks that every people speak US English and use USD as currency

**Comment by agusdutra** [comment] 2019-08-13 14:22
@gund  it happened the same to me, if anyone else can give a look that'll be great

**Comment by g3rrydanc3** [comment] 2019-08-16 13:30
I found a solution to this. Create custom pipe that extends the original CurrencyPipe and give default parameter.
````typescript
import { Pipe, PipeTransform } from '@angular/core';
import { CurrencyPipe } from '@angular/common';

@Pipe({
  name: 'mycurrency'
})
export class MyCurrencyPipe extends CurrencyPipe implements PipeTransform {

  transform(value: any, currencyCode?: string, display?: 'code' | 'symbol' | 'symbol-narrow' | string | boolean, digitsInfo?: string, locale?: string): string | null {
    return super.transform(
      value,
      currencyCode || 'IDR',
      display || 'symbol',
      digitsInfo,
      'id'
    );
  }

}
````
(Works in Angular 8.1.2)

**Comment by Devqon** [comment] 2019-08-16 13:38
> I found a solution to this. Create custom pipe that extends the original CurrencyPipe and give default parameter.
> 
> ```ts
> import { Pipe, PipeTransform } from '@angular/core';
> import { CurrencyPipe } from '@angular/common';
> 
> @Pipe({
>   name: 'mycurrency'
> })
> export class MyCurrencyPipe extends CurrencyPipe implements PipeTransform {
> 
>   transform(value: any, currencyCode?: string, display?: 'code' | 'symbol' | 'symbol-narrow' | string | boolean, digitsInfo?: string, locale?: string): string | null {
>     return super.transform(
>       value,
>       currencyCode || 'IDR',
>       display || 'symbol',
>       digitsInfo,
>       locale || 'id'
>     );
>   }
> 
> }
> ```
> 
> (Works in Angular 8.1.2)
> 
> And don't forget to setting your [locales i18n pipes](https://angular.io/guide/i18n#i18n-pipes)

I actually **override** the default pipe:

```
/*
    This pipe overrides the default currency pipe from angular,
    this can be removed when angular supports currency defaults
    https://github.com/angular/angular/issues/25461
*/

import { CurrencyPipe } from "@angular/common";
import { Pipe, PipeTransform } from "@angular/core";

@Pipe({
  name: "currency"
})
export class CurrencyNlProxyPipe extends CurrencyPipe implements PipeTransform {
  constructor() {
    super("nl");
  }

  transform(
    value: any,
    code = "EUR",
    display = "symbol",
    digitsInfo = "1.2-2",
    locale = "nl"
  ) {
    return super.transform(value, code, display, digitsInfo, locale);
  }
}
```

Importing this pipe in your modules works, but I still 'expect' that overriding the defaults should be a feature, so I don't opt for closing this issue.

**Comment by tsteuwer** [comment] 2019-12-06 19:25
Any updates on this? I can try to offer assistance if needed

**Comment by MickL** [comment] 2019-12-06 19:37
With Ivy, isnt this be totally different and should be closed? And reopened if still persistent?

**Comment by MRMokwa** [comment] 2019-12-06 19:47
@tsteuwer There's an open pull request about to go on, made by @Hayouung. Probably will enter after 9.0.0 release.
https://github.com/angular/angular/pull/32584#issuecomment-558086648

@MickL Don't think it's Ivy related, also, it's not a bug but a feature request.

**Closed** 2020-01-13 17:57 UTC
Labels: comp: common, type: feature
