### ISSUE TITLE
ViewContainerRef.createComponent and projectableNodes contains component

### ISSUE THREAD

**Issue by DMITRYTISHKIN** [angular/angular#35412] opened 2020-02-13 10:41 UTC
# 🐞 bug report

### Affected Package
@angular/core 9.0.1

### Is this a regression?

Yes, the previous version in which this bug was not present was: 8.2.14

### Description

ViewContainerRef createComponent throw error when projectableNodes contains Angular components 

## 🔬 Minimal Reproduction

https://github.com/DMITRYTISHKIN/ivy-view-ref-bug/blob/master/src/app/app.component.ts

## 🔥 Exception or Error
<pre><code>
core.js:5845 ERROR DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at DefaultDomRenderer2.insertBefore (http://10.99.101.144:4300/vendor.js:100106:20)
    at BaseAnimationRenderer.insertBefore (http://10.99.101.144:4300/vendor.js:98665:23)
    at nativeInsertBefore (http://10.99.101.144:4300/vendor.js:59683:18)
    at applyToElementOrContainer (http://10.99.101.144:4300/vendor.js:59169:13)
    at applyNodes (http://10.99.101.144:4300/vendor.js:59935:17)
    at applyView (http://10.99.101.144:4300/vendor.js:59969:5)
    at addRemoveViewFromContainer (http://10.99.101.144:4300/vendor.js:59210:9)
    at ViewContainerRef.insert (http://10.99.101.144:4300/vendor.js:60858:17)
    at ViewContainerRef.createComponent (http://10.99.101.144:4300/vendor.js:60814:22)
    at MenuTreeService._createSpoiler (http://10.99.101.144:4300/default~app-modules-administration-administration-module~app-modules-customer-customer-module.js:16393:33)
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.0.1
Node: 10.15.0
OS: darwin x64

Angular: 9.0.1
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.1
@angular-devkit/build-angular     0.900.1
@angular-devkit/build-optimizer   0.900.1
@angular-devkit/build-webpack     0.900.1
@angular-devkit/core              9.0.1
@angular-devkit/schematics        9.0.1
@ngtools/webpack                  9.0.1
@schematics/angular               9.0.1
@schematics/update                0.900.1
rxjs                              6.5.3
typescript                        3.7.5
webpack                           4.41.2
</code></pre>

**Comment by alexzuza** [comment] 2020-02-13 10:47
Online reproduction https://ng-run.com/edit/bCDFekp47nIYgjPHKHTS?open=src%2Fapp%2Fapp.component.ts

**Comment by pkozlowski-opensource** [comment] 2020-02-17 06:16
Debugged it a little bit and it turns out that the problem itself has nothing to do with projectable nodes: one can make it work with them: https://ng-run.com/edit/sI6wEocqOTh9jzT4n6LB?open=src%2Fapp%2Fapp.component.ts

What _is_ important is passing 0 as the view index to the ` const refParent = this.viewRef.createComponent(factoryParent, 0);` - you can see that we can trigger error in question without projectable nodes at all: https://ng-run.com/edit/15snU26JUBcG5RLdAq33

The root cause of the problem is that there is manual DOM manipulation going on when we move DOM of the _first_ (child) inserted view (as in `node.appendChild(refChild.location.nativeElement);`). The problem is that then we are trying to use the moved DOM as an anchor for inserting the second (parent) view.

**Comment by pkozlowski-opensource** [comment] 2020-02-17 06:34
So, this used to work in VE since we were:
* using an anchor node for a view;
* doing insert _after_ this anchor to insert DOM elements.

With ivy we've switched to the `insertBefore` which means that inserting a view at the index 0, we need to get the first node of the view at index 1. In the error case here nodes from the view at index 1 were moved to a different place in the DOM hierarchy so those can't be reliably used as the "insert before" node.

Now, doing this kind of DOM manipulation _is_ bound to cause problems as the frameworks assumes that DOM nodes are in one place while in reality those are in a different place. The particular scenario might have worked in VE but there are plenty of other scenarios where it would fail.

BUT, none of this matters, really, as I would argue that the example scenario illustrates _incorrect_ us of the `ViewContainerRef` API to create a child component - the intention is to create an instance and pass it as a projectable node but using `ViewContainerRef` API makes it (unnecessarily) attached to the DOM.

The correct way of doing this would be to _not_ create child instances through `ViewContainerRef` but use the `create` method on a factory. Here is a working reproduction: https://ng-run.com/edit/pG94AVIEWn4rN2eA2rXT (this should work in both ivy and VE).

I'm going to close this issue since the root cause here is the manual DOM manipulation outside of the framework / incorrect use of the existing APIs. While this particular scenario might have worked in the past, it would also fail in VE under slightly different condition - simply put this is _not_ the pattern we want to encourage.

**Closed by pkozlowski-opensource** 2020-02-17 06:34 UTC
Labels: comp: core, comp: ivy, severity5: regression
