### ISSUE TITLE
disabled attribute doesn't work with required attribute on select tag

### ISSUE THREAD

**Issue by smartm0use** [angular/angular#11532] opened 2016-09-12 12:06 UTC
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 
`select` tag is always disabled if Angular `disabled` attribute and HTML5 `required` attributes are set on the same item.

**Expected behavior**
`select` tag should appear active when the condition for `disabled` attribute is false.

**Reproduction of the problem**
Here is the [Plunker](http://plnkr.co/edit/75YWP2te0gCopGtOCQxO). As you can see the second select is disabled until the users choose one option from first select. So if the users choose an option from the first select, the second select become active.
Now i want to add `required` attribute even to the second select. But if i do it the second select is always disabled. Here is the [updated Plunker](http://plnkr.co/edit/sx1qFH607cjmdTxPcvjl).

_Update:_ it works if there are positive conditions for Angular `disabled` tag. For example if i use `[disabled]="firstSelect"` instead of `[disabled]="!firstSelect"` it works with no problems.

**Please tell us about your environment:**
I'm on LinuxMint 17.2 (64-bit), using Atom as IDE.

* **Angular version:**
Angular 2.0.0-rc.6

* **Browser:**
I'm using Chromium v52.0.2743.116 but i'm sure it will be the same on other browsers.
 
* **Language:**
Typescript / ES5

I answered the same on [Stackoverflow](http://stackoverflow.com/questions/39448285/disabled-attribute-doesnt-work-with-required-attribute-on-select-tag), but in my opinion this could be an Angular's bug.

**Comment by cozmy** [comment] 2016-09-12 12:52
Removing `[(ngModel)]` seems to fix this.

This behavior is also encountered on `input` tags. I think this applies to all elements which supported the `required`, `disabled` and `ngModel` properties.

**Comment by kara** [comment] 2016-09-12 18:35
@smartm0use  This was a bug in RC.6 that is fixed in master. If you npm install the nightly build from `angular/forms-builds` (or wait for the next official release), it should work as intended.

**Closed by kara** 2016-09-12 18:35 UTC
Labels: comp: forms
