### ISSUE TITLE
PWA not working, seems like start_url isn't properly read.

### ISSUE THREAD

**Issue by glemiere** [angular/angular#31380] opened 2019-07-02 04:01 UTC
# 🐞 bug report

### Affected Package
@angular/core @angular/cli

### Is this a regression?
Yes

### Description
Creating a PWA by using the command `ng add @angular/pwa --project <name>` works as expected but the service worker isn't able to handle start_url.

![Screen Shot 2019-07-01 at 9 43 02 PM](https://user-images.githubusercontent.com/7260880/60481639-79b69580-9c4b-11e9-8a83-e1b1f6725bc7.png)

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 8.0.3
Node: 10.9.0
OS: darwin x64
Angular: 8.0.1
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.3
@angular-devkit/build-angular     0.800.3
@angular-devkit/build-optimizer   0.800.3
@angular-devkit/build-webpack     0.800.3
@angular-devkit/core              8.0.3
@angular-devkit/schematics        8.0.3
@angular/cli                      8.0.3
@angular/pwa                      0.800.6
@angular/service-worker           8.0.3
@ngtools/webpack                  8.0.3
@schematics/angular               8.0.3
@schematics/update                0.800.3
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.30.0
</code></pre>

**Comment by jeebanKishore** [comment] 2019-07-02 07:07
I am having the same issue in angular 8

**Comment by gkalpak** [comment] 2019-07-02 10:21
I just started with the latest cli and it worked fien for me.

How I built the project:

```sh
npm install --global @angular/cli@8.0.6
ng new test-app --defaults && cd test-app
ng add @angular/pwa --project test-app
ng build --prod
```

Things I tried:
1. Serving with [http-server][1]: `http-server dist/test-app`
2. Serving with [light-server][2]: `light-server --bind="localhost" --historyindex="/index.html" --no-reload --serve="dist/test-app"
3. Renaming `dist/test-app/manifest.webmanifest` to `dist/test-app/manifest.webmanifest.txt` (and the associated reference in `dist/test-app/index.html`), which caused it to be served with `Content-Type: test/plain`.

Lighthouse PWA checks passed in all cases.

##
So, it sounds like it is something specific to your app/config that is causing the failure. (FWIW, I doubt it is related to the manifest file extention.)

I am going to close this issue, since it is not actionable in its current state. If you think there is a bug in one of the `@angular` packages, feel free to open a new issue, providing the necessary details to (minimally) reproduce the problem, so we can investigate.

I suggest you first try asking for help on one of our [support forums][3].

[1]: https://www.npmjs.com/package/http-server
[2]: https://www.npmjs.com/package/light-server
[3]: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

**Closed by gkalpak** 2019-07-02 10:21 UTC
