### ISSUE TITLE
ComponentRef.changeDetectorRef is not the same instance that's injected into the Component it's a Ref for

### ISSUE THREAD

**Issue by Toxicable** [angular/angular#18817] opened 2017-08-21 23:15 UTC
## I'm submitting a...
<pre><code>
[x] Feature
</code></pre>

## Current behavior
When you create a Dynamic Component via `ViewContainerRef#createComponent` the returned `ComponentRef#changeDetectorRef` does not equal the one injected into the component created.
This behavior produces unexpected results when the Dynamic Component is using OnPush since you  cannot mark it to be checked from the `ComponentRef#changeDetectorRef` .
Instead have to use the `ChangeDetectorRef` injected into the component which means you have to use a setter for every property on the component then call markForCheck there where the responsibility to handle this should be in the parent.
It also appears that `ComponentRef#changeDetectorRef` belongs no nothing if you inspect it's `rootNodes` it's just a textNode

## Expected behavior
In the API docs https://angular.io/api/core/ComponentRef#changeDetectorRef 
it mentions that "The ChangeDetectorRef of the Component instance." meaning that you'd expect that the returned `ComponentRef#changeDetectorRef` to equal the one injected into the component

So either this is a misunderstanding of my interpretation of the above or there is a bug here

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-different-cdrs?file=app/app.module.ts

## Related issues
#12313 #14656  #17356
#14087 #36667

**Comment by chuckjaz** [comment] 2017-09-20 23:25
I have marked this as a feature request as we never intended these to be identical instances.

**Comment by Toxicable** [comment] 2017-09-20 23:32
@chuckjaz Ahh alrighty, I wasn't aware of that, thanks for pointing it out

**Comment by sharikovvladislav** [comment] 2018-09-26 07:53
Big pain for us. We have a lot of dynamic components and same problem with CDR.

**Comment by ngx-lib** [comment] 2019-01-20 04:06
I can't really test my component those are  on `OnPush` strategy. Painful thing I've ever seen. No workaround work for me.

**Comment by kovaja** [comment] 2019-08-28 10:21
@ngx-lib There is one possible workaround 

```
  let changeDetectorRef: ChangeDetectorRef;

  beforeEach(() => {
    fixture = TestBed.createComponent(Component);
    component = fixture.componentInstance;
    
    changeDetectorRef = component['changeDetectorRef'];
```

In the end it is still just javascript :)

**Comment by atheros** [comment] 2019-08-28 17:01
Guys, the problem is mostly with lack of proper documentation on how to test components with OnPush strategy. But it turns out that it is quite simple and I have 3 solutions for you

Let's test this component
```typescript
import {ChangeDetectionStrategy, Component, Input} from '@angular/core';

@Component({
  selector: 'app-test',
  template: '<strong>{{input}}</strong>',
  styles: [],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class TestComponent {
  @Input() input = 5;
  constructor() {
  }
}
```
it has an initial input value of 5. So let's see if we can set it to 10 in our unit tests.


**Solution 1**
```typescript
@Component({
    template: '<app-test [input]="input"></app-test>',
    styles: []
})
class TesterComponent {
    input = undefined;
}

describe('TestComponent - with component', () => {
    let testerComponent: TesterComponent;
    let component: TestComponent;
    let fixture: ComponentFixture<TesterComponent>;

    beforeEach(async(() => {
        TestBed.configureTestingModule({
            declarations: [
                TestComponent,
                TesterComponent
            ]
        })
            .compileComponents();
    }));

    beforeEach(() => {
        fixture = TestBed.createComponent(TesterComponent);
        testerComponent = fixture.componentInstance;
        component = fixture.debugElement.query(By.directive(TestComponent)).componentInstance;
        fixture.detectChanges();
    });

    it('should have 10', () => {
        expect(fixture.nativeElement.textContent).not.toContain('10');
        testerComponent.input = 10;
        fixture.detectChanges();
        expect(fixture.nativeElement.textContent).toContain('10');
    });
});
```
This is the simplest approach. I suspect that is what we are supposed to be doing to test our OnPush components. Unfortunately the wrapper component can grow in complexity very fast, so as soon as I found other ways, I stopped doing that.

**Solution 2**
```typescript
describe('TestComponent - with events', () => {
    let component: TestComponent;
    let fixture: ComponentFixture<TestComponent>;
    const pushChanges = () => fixture.debugElement.triggerEventHandler('__push_changes', null);

    beforeEach(async(() => {
        TestBed.configureTestingModule({
            declarations: [
                TestComponent
            ]
        })
            .overrideComponent(TestComponent, {
                set: {
                    host: {'(__push_changes)': 'dummy'}
                }
            })
            .compileComponents();
    }));

    beforeEach(() => {
        fixture = TestBed.createComponent(TestComponent);
        component = fixture.componentInstance;
        fixture.detectChanges();
    });

    it('should have 10', () => {
        expect(fixture.nativeElement.textContent).not.toContain('10');
        component.input = 10;
        pushChanges();
        fixture.detectChanges();
        expect(fixture.nativeElement.textContent).toContain('10');
    });
});
```
If you dive deep into angular, you'll know that events may trigger change detection and in our tests, mark component for check. Knowing this, we can abuse TestBed a bit by adding a custom event listener to our component, the __push_changes (name doesn't matter). When we trigger this event, next call to fixture.detectChanges() will actually check that component, as it will already be marked as dirty.
It's kind of awkward to type this every time, so creating helper functions to generate the pushChanges() and calling the TestBed.overrideComponent() is advised.


**Solution 3**
This is a solution I found recently by accident and it rocks!
```typescript
describe('TestComponent - with change detector', () => {
    let component: TestComponent;
    let fixture: ComponentFixture<TestComponent>;
    let changeDetectorRef: ChangeDetectorRef;

    beforeEach(async(() => {
        TestBed.configureTestingModule({
            declarations: [
                TestComponent
            ]
        })
            .compileComponents();
    }));

    beforeEach(() => {
        fixture = TestBed.createComponent(TestComponent);
        component = fixture.componentInstance;
        changeDetectorRef = fixture.debugElement.injector.get(ChangeDetectorRef);
        fixture.detectChanges();

    });

    it('should have 10', () => {
        component.input = 10;
        changeDetectorRef.detectChanges();
        expect(fixture.nativeElement.textContent).toContain('10');
    });
});
```
I call it the ultimate solution as it doesn't use any hacks, it is a drop-in replacement for your usual fixture.detectChanges() calls and it's quite convenient to use.

The only thing left to solve is the lack of this information in official docs/guides :)

I hope this helps!

**Comment by palpatine1991** [comment] 2020-02-24 10:51
This is a pain even in the runtime. When I want to create component dynamically, I have no reference to its change detector to execute `detectChanges`  when I update its properties via API

**Comment by intellix** [comment] 2020-09-09 15:26
Not sure what the original intent of `componentRef.changeDetectorRef` is for if it doesn't do anything but I'm doing the following workaround:
```ts
componentRef.injector.get(ChangeDetectorRef).detectChanges();
```

Initially I tried these two which did nothing:
```ts
componentRef.changeDetectorRef.detectChanges();
viewRef.detectChanges();
```

Was trying to get the componentRefs by index as well but failed there too. Ended up maintaining my own array of componentRefs

**Comment by alxhub** [comment] 2022-01-21 00:40
Closing as this is not actually a feature request, but a duplicate of the bug report in #36667.

**Closed by alxhub** 2022-01-21 00:40 UTC
Labels: feature, comp: core, core: di, insufficient votes, votes required
