### ISSUE TITLE
(docs): wrong table format

### ISSUE THREAD

**Issue by maxkorz** [angular/angular#24920] opened 2018-07-17 09:32 UTC
## I'm submitting a...

<pre><code>[x] Documentation issue or request
</code></pre>

## Current behavior
Page https://angular.io/api/core/Renderer2
Table of properties looks like this:
![image](https://user-images.githubusercontent.com/25089646/42808856-d90b9f64-89bc-11e8-9c38-af9d1d64880f.png)

## Expected behavior
I think it should look like this:
![image](https://user-images.githubusercontent.com/25089646/42808883-e79f83d8-89bc-11e8-889f-9108994ee70f.png)

The table should not have CSS class `list-table` (or it should have, but the class is broken).

## Environment

<pre><code>Browser:
- [x] Chrome (desktop) version 67
</code></pre>

**Comment by gkalpak** [comment] 2018-07-17 09:35
I will be fixed by #24919.

**Comment by trotyl** [comment] 2018-07-17 09:41
Duplicate of https://github.com/angular/angular/issues/24902

**Closed** 2018-07-17 09:44 UTC
