### ISSUE TITLE
using `styleUrls` on component throws range exception

### ISSUE THREAD

**Issue by rolandjitsu** [angular/angular#2672] opened 2015-06-22 09:19 UTC
If I use `styleUrls` on a component I get a `Zone already exported on the window object`. If I do that on another component, then I get an exception:

![screenshot 2015-06-22 11 14 52](https://cloud.githubusercontent.com/assets/1479737/8278956/1932909a-18d0-11e5-996f-421ddc91c83a.png)

Not sure why it happens, and it also does not apply the styling. I should mention that I use the `NativeShadowDomStrategy`:
```js
// common/shadow_dom.js
import { ShadowDomStrategy, NativeShadowDomStrategy } from 'angular2/render';
import { bind } from 'angular2/angular2';
import { document } from 'angular2/src/facade/browser';

export var supportsNativeShadowDOM: boolean = Boolean(document && document.body && document.body.createShadowRoot);

export var shadowDomInjectables: Array<any> = !supportsNativeShadowDOM ? [] : [
    bind(ShadowDomStrategy).toClass(NativeShadowDomStrategy)
];


// app/bootstrap.js
import { shadowDomInjectables } from 'common/shadow_dom'; 

bootstrap(App, [
    shadowDomInjectables
]);
```

**Comment by vicb** [comment] 2015-06-22 10:09
@rolandjitsu could you please your code (ideally only the bare minimum to reproduce the issue). Thanks.

**Comment by rolandjitsu** [comment] 2015-06-22 10:33
@vicb of course :) [here](https://github.com/rolandjitsu/ng2-play/blob/master/src/app/components/app/app.ts#L32) is where I have changed the `styleUrls` to `styles` and used `@import` instead because of the error. If you clone it and run it locally and change the `styles` to `styleUrls` you should be getting the same exception.

**Comment by rolandjitsu** [comment] 2015-06-23 09:07
@vicb also note that if I want to use `styles` or `styleUrls` without `templateUrl`, the styles are no longer resolved relative to the component but relative to the root (so `app.css` will be resolved at the root instead of the folder where the component is, for example `components/app/app.css`).

**Comment by vicb** [comment] 2015-06-23 09:25
Hopefully this should all be fixed later this week. I'm currently working on relative URLs resolution.

**Comment by rolandjitsu** [comment] 2015-06-23 09:32
@vicb looking forward to it :+1:

**Comment by vicb** [comment] 2015-06-23 09:38
same here :)

**Comment by rolandjitsu** [comment] 2015-06-25 11:03
@vicb it seems like I do not get this exception anymore when I use `styleUrls`, but, if I do use it and I give a wrong path to the `templateUrl` then I get the same issue.

**Comment by vicb** [comment] 2015-06-25 17:17
Thanks for the report, I'll take a look.

What release/SHA1 are you using (now & before) ? Thanks

**Comment by rolandjitsu** [comment] 2015-06-26 06:50
@vicb before I was using `27` and now I am using `28` (the alpha release versions from npm).

**Comment by mhevery** [comment] 2015-08-21 02:49
Looks like this has been resolved, closing.

**Closed by mhevery** 2015-08-21 02:49 UTC
Labels: comp: core/view/compiler, effort2: medium (day), P2: required, state: Periodic Review, type: bug
