### ISSUE TITLE
<my-app> in angular documentation

### ISSUE THREAD

**Issue by pasha-bolokhov-cs** [angular/angular#20235] opened 2017-11-07 04:20 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[X] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

In some places you write my-app for the root selector, while in others you use app-root. This even happens on the same page, in particular at https://angular.io/guide/displaying-data
This is clearly a copying error
I suggest you do a search for other examples of this, in particular the Tour of Heroes

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by trotyl** [comment] 2017-11-07 05:04
Duplicate of https://github.com/angular/angular/pull/19778

**Comment by kapunahelewong** [comment] 2017-11-09 19:54
@pasha-bolokhov-cs Thanks for bringing this up. We're in the middle of changing these selectors per the PR @trotyl mentioned. It's just because `my-app` is leftover from pre-CLI documentation.

**Comment by pasha-bolokhov-cs** [comment] 2017-11-10 19:23
look for this too
my-child
on https://angular.io/guide/lifecycle-hooks and perhaps around

**Comment by jenniferfell** [comment] 2018-04-25 10:00
Quick update. displaying-data appears to have been updated to app-root. lifecycle-hooks still uses my-child. 

Search needs to be done on the source, not on the angular.io/docs site to correctly locate any remaining instances.

**Closed** 2021-05-25 22:13 UTC
Labels: P3, comp: docs, comp: examples, freq3: high, state: has PR, type: bug/fix
