### ISSUE TITLE
Angular elements in another angular project: Uncaught Error: Zone already loaded

### ISSUE THREAD

**Issue by Sunil-chelatt** [angular/angular#24466] opened 2018-06-13 11:38 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

I have created an angular 6 element and added the js files to another angular application and I get the Zone.js already loaded. I tried removing the polyfills from the element project, then it complain angular requires Zone.js in dev and --prod builds when the element is added to the host angular project. 

## Expected behavior

Should able to add elements to host projects by referring the  element js files.  

## Minimal reproduction of the problem with instructions

1. create a angular element in project a
2. create a angular application project b
3. use angular element created in project a in project b

## What is the motivation / use case for changing the behavior?

Idea of web component/angular elements is to import the components to other project and work seamlessly. 

## Environment

<pre><code>
Angular version: 6.0.7

Browser:
- [x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by JiaLiPassion** [comment] 2018-06-13 15:59
This has been fixed here, https://github.com/angular/zone.js/pull/1093, but still under review.

**Comment by SchneiderMK** [comment] 2018-07-16 13:45
Workaround: remove zone.js from pollyfill.ts and add it to index.html
`<script type="text/javascript" src="https://unpkg.com/zone.js"></script>`

**Comment by RezaRahmati** [comment] 2018-09-18 13:34
> <script type="text/javascript" src="https://unpkg.com/zone.js"></script>

This workaround doesn't work for me, I am using ng 6

**Comment by smasala** [comment] 2018-10-19 08:56
I'd like to be able to define different entry / polyfill points in `angular.json` instead of the workaround when booting the app in `serve` or `build` mode. Either way, thanks @SchneiderMK :+1:

**Comment by shai93** [comment] 2019-05-27 08:36
ERROR Error: Uncaught (in promise): TypeError: n.e is not a function
TypeError: n.e is not a function
    at o (main.054737874ce72b1240e0.js:1)
    at t.loadFactory (main.054737874ce72b1240e0.js:1)
    at t.load (main.054737874ce72b1240e0.js:1)
    at t.loadModuleFactory (main.054737874ce72b1240e0.js:1)
    at t.load (main.054737874ce72b1240e0.js:1)
    at e.project (main.054737874ce72b1240e0.js:1)
    at e._tryNext (main.054737874ce72b1240e0.js:1)
    at e._next (main.054737874ce72b1240e0.js:1)
    at e.next (main.054737874ce72b1240e0.js:1)
    at t._subscribe (main.054737874ce72b1240e0.js:1)
    at t._trySubscribe (main.054737874ce72b1240e0.js:1)
    at t.subscribe (main.054737874ce72b1240e0.js:1)
    at t.call (main.054737874ce72b1240e0.js:1)
    at t.subscribe (main.054737874ce72b1240e0.js:1)
    at t.call (main.054737874ce72b1240e0.js:1)
    at new v (polyfills.c2a982f40ec7317bc92d.js:1)
    at Z (polyfills.c2a982f40ec7317bc92d.js:1)
    at Z (polyfills.c2a982f40ec7317bc92d.js:1)
    at polyfills.c2a982f40ec7317bc92d.js:1
    at e.invokeTask (polyfills.c2a982f40ec7317bc92d.js:1)
    at Object.onInvokeTask (main.054737874ce72b1240e0.js:1)
    at e.invokeTask (polyfills.c2a982f40ec7317bc92d.js:1)
    at Object.onInvokeTask (main.054737874ce72b1240e0.js:1)
    at e.invokeTask (polyfills.c2a982f40ec7317bc92d.js:1)
    at t.runTask (polyfills.c2a982f40ec7317bc92d.js:1)
    at y (polyfills.c2a982f40ec7317bc92d.js:1)


ERROR Error: Expected to not be in Angular Zone, but it is!
    at new v (polyfills.c2a982f40ec7317bc92d.js:1)
    at Function.t.assertNotInAngularZone (main.054737874ce72b1240e0.js:1)
    at Object.next (main.054737874ce72b1240e0.js:1)
    at e.object.i [as _next] (main.054737874ce72b1240e0.js:1)
    at e.__tryOrUnsub (main.054737874ce72b1240e0.js:1)
    at e.next (main.054737874ce72b1240e0.js:1)
    at e._next (main.054737874ce72b1240e0.js:1)
    at e.next (main.054737874ce72b1240e0.js:1)
    at e.next (main.054737874ce72b1240e0.js:1)
    at e.emit (main.054737874ce72b1240e0.js:1)
    at main.054737874ce72b1240e0.js:1
    at e.invoke (polyfills.c2a982f40ec7317bc92d.js:1)
    at Object.onInvoke (main.054737874ce72b1240e0.js:1)
    at e.invoke (polyfills.c2a982f40ec7317bc92d.js:1)
    at t.run (polyfills.c2a982f40ec7317bc92d.js:1)

**Comment by santoshyadav198613** [comment] 2019-05-27 08:45
> ERROR Error: Uncaught (in promise): TypeError: n.e is not a function
> TypeError: n.e is not a function
> at o (main.054737874ce72b1240e0.js:1)
> at t.loadFactory (main.054737874ce72b1240e0.js:1)
> at t.load (main.054737874ce72b1240e0.js:1)
> at t.loadModuleFactory (main.054737874ce72b1240e0.js:1)
> at t.load (main.054737874ce72b1240e0.js:1)
> at e.project (main.054737874ce72b1240e0.js:1)
> at e._tryNext (main.054737874ce72b1240e0.js:1)
> at e._next (main.054737874ce72b1240e0.js:1)
> at e.next (main.054737874ce72b1240e0.js:1)
> at t._subscribe (main.054737874ce72b1240e0.js:1)
> at t._trySubscribe (main.054737874ce72b1240e0.js:1)
> at t.subscribe (main.054737874ce72b1240e0.js:1)
> at t.call (main.054737874ce72b1240e0.js:1)
> at t.subscribe (main.054737874ce72b1240e0.js:1)
> at t.call (main.054737874ce72b1240e0.js:1)
> at new v (polyfills.c2a982f40ec7317bc92d.js:1)
> at Z (polyfills.c2a982f40ec7317bc92d.js:1)
> at Z (polyfills.c2a982f40ec7317bc92d.js:1)
> at polyfills.c2a982f40ec7317bc92d.js:1
> at e.invokeTask (polyfills.c2a982f40ec7317bc92d.js:1)
> at Object.onInvokeTask (main.054737874ce72b1240e0.js:1)
> at e.invokeTask (polyfills.c2a982f40ec7317bc92d.js:1)
> at Object.onInvokeTask (main.054737874ce72b1240e0.js:1)
> at e.invokeTask (polyfills.c2a982f40ec7317bc92d.js:1)
> at t.runTask (polyfills.c2a982f40ec7317bc92d.js:1)
> at y (polyfills.c2a982f40ec7317bc92d.js:1)
> 
> ERROR Error: Expected to not be in Angular Zone, but it is!
> at new v (polyfills.c2a982f40ec7317bc92d.js:1)
> at Function.t.assertNotInAngularZone (main.054737874ce72b1240e0.js:1)
> at Object.next (main.054737874ce72b1240e0.js:1)
> at e.object.i [as _next] (main.054737874ce72b1240e0.js:1)
> at e.__tryOrUnsub (main.054737874ce72b1240e0.js:1)
> at e.next (main.054737874ce72b1240e0.js:1)
> at e._next (main.054737874ce72b1240e0.js:1)
> at e.next (main.054737874ce72b1240e0.js:1)
> at e.next (main.054737874ce72b1240e0.js:1)
> at e.emit (main.054737874ce72b1240e0.js:1)
> at main.054737874ce72b1240e0.js:1
> at e.invoke (polyfills.c2a982f40ec7317bc92d.js:1)
> at Object.onInvoke (main.054737874ce72b1240e0.js:1)
> at e.invoke (polyfills.c2a982f40ec7317bc92d.js:1)
> at t.run (polyfills.c2a982f40ec7317bc92d.js:1)

https://blog.angularindepth.com/using-angular-elements-with-ngrx-bc655e1eb212

You can check this blog I have used an Angular Element withing Angular and as well as with a Static page.

**Comment by shai93** [comment] 2019-05-27 09:03
Im getting above error on ng build --prod not on ng build

**Comment by santoshyadav198613** [comment] 2019-05-27 09:07
Yes i have used it in prod mode, can you share the github repo, so I can check.

**Comment by shai93** [comment] 2019-05-27 09:44
Sorry i cannot share the github repo, is there any way to solve this without using NgRx?

**Comment by santoshyadav198613** [comment] 2019-05-27 09:48
Ngrx is optional, you can take code from my github repo mentioned in blog and try

**Comment by shai93** [comment] 2019-05-31 08:07
Thank you so much, Santosh your solution works for me.

Thanks
Shailesh

**Comment by santoshyadav198613** [comment] 2019-05-31 08:11
Happy to help Shailesh.

**Comment by ukreddy** [comment] 2019-08-26 06:39
Uncaught Error: Zone already loaded.
    at main.js:10519
    at main.js:11131
    at ./node_modules/zone.js/dist/zone-mix.js.FUNCTION (main.js:10497)
    at Object../node_modules/zone.js/dist/zone-mix.js (main.js:10499)
    at __webpack_require__ (main.js:77)
    at Object../src/app/app.module.ts (main.js:14062)
    at __webpack_require__ (main.js:77)
    at Object../src/main.ts (main.js:17568)
    at __webpack_require__ (main.js:77)
    at Object.3 (main.js:17695)

Here my package.json file
{
  "name": "AngularwithElectronapp",
  "version": "0.0.0",
  "description": "Testing",
  "author": {
    "name": "test",
    "email": "test@gmail.com"
  },
  "main": "main.js",
  "private": true,
  "scripts": {
    "postinstall": "npm run postinstall:electron && npx electron-builder install-app-deps",
    "postinstall:web": "node postinstall-web",
    "postinstall:electron": "node postinstall",
    "ng": "ng",
    "start": "npm run postinstall:electron && npm-run-all -p ng:serve electron:serve",
    "build": "npm run postinstall:electron && npm run electron:serve-tsc && ng build",
    "build:dev": "npm run build -- -c dev",
    "build:prod": "npm run build -- -c production",
    "build:editor": "npm run build -- -c actionEditor",
    "build:editor:local": "npm run build -- -c editor.local",
    "ng:serve": "ng serve",
    "ng:serve:web": "npm run postinstall:web && ng serve -o",
    "electron:serve-tsc": "tsc -p tsconfig-serve.json",
    "electron:serve": "wait-on http-get://localhost:4201/ && npm run electron:serve-tsc && electron . --serve",
    "electron:local": "npm run build:prod && electron .",
    "electron:windows": "npm run build:prod && npx electron-builder build --windows",
    "electron:windows:dev": "npm run build:dev && npx electron-builder build --windows",
    "electron:windows:editor": "npm run build:editor && npx electron-builder build --windows",
    "electron:windows:editor:local": "npm run build:editor:local && npx electron-builder build --windows",
    "test": "npm run postinstall:web && ng test",
    "e2e": "npm run postinstall:web && ng e2e"
  },
  "dependencies": {
    "@angular/animations": "^5.2.11",
    "@angular/flex-layout": "^2.0.0-beta.10",
    "angular-split": "^1.0.0-rc.3",
    "bootstrap-scss": "^4.1.3",
    "botframework-directlinejs": "^0.9.17",
    "botframework-webchat": "^0.14.2",
    "element-resize-detector": "^1.1.14",
    "font-awesome": "^4.7.0",
    "guid-typescript": "^1.0.9",
    "jsonwebtoken": "^8.4.0",
    "lodash": "^4.17.11",
    "moment": "^2.22.2",
    "ngx-bootstrap": "^3.0.1",
    "ngx-pagination": "^3.2.1",
    "ngx-spinner": "^2.0.0",
    "querystring": "^0.2.0",
    "rxjs": "^5.5.0",
    "sass-loader": "^7.1.0",
    "save": "^2.3.2",
    "split": "^1.0.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "0.6.3",
    "@angular/cli": "6.2.2",
    "@angular/common": "5.2.11",
    "@angular/compiler": "5.2.11",
    "@angular/compiler-cli": "5.2.11",
    "@angular/core": "5.2.11",
    "@angular/forms": "5.2.11",
    "@angular/http": "5.2.11",
    "@angular/language-service": "5.2.11",
    "@angular/platform-browser": "5.2.11",
    "@angular/platform-browser-dynamic": "5.2.11",
    "@angular/router": "5.2.11",
    "@ngx-translate/core": "9.1.1",
    "@ngx-translate/http-loader": "2.0.1",
    "@types/jasmine": "2.8.7",
    "@types/jasminewd2": "2.0.3",
    "@types/node": "8.9.4",
    "codelyzer": "4.2.1",
    "core-js": "2.5.6",
    "electron": "2.0.7",
    "electron-builder": "20.28.1",
    "electron-reload": "1.2.2",
    "jasmine-core": "3.1.0",
    "jasmine-spec-reporter": "4.2.1",
    "karma": "^3.0.0",
    "karma-chrome-launcher": "2.2.0",
    "karma-coverage-istanbul-reporter": "2.0.0",
    "karma-jasmine": "1.1.2",
    "karma-jasmine-html-reporter": "1.1.0",
    "node-sass": "^4.9.3",
    "npm-run-all": "4.1.3",
    "npx": "10.2.0",
    "protractor": "^5.4.1",
    "ts-node": "6.0.3",
    "tslint": "5.10.0",
    "typescript": "^2.6.2",
    "wait-on": "2.1.0",
    "webdriver-manager": "12.0.6",
    "zone.js": "0.8.26"
  }
}

can anyone help me please?

**Comment by warrendugan** [comment] 2019-11-20 19:43
You can piggy back off the zone from the consuming/parent angular application. https://angular-extensions.github.io/elements/#/docs/change-detection

**Comment by rahulshinde11** [comment] 2020-04-21 20:00
for me locally it's working fine. but in prod build i get `polyfills.0dd82ec61b0c3f88f791.js:1 Uncaught Error: Zone already loaded`.

has somone found a solution for this

**Comment by JiaLiPassion** [comment] 2020-04-22 11:21
@rahulshinde11, could you post a reproduce repo?

**Comment by rahulshinde11** [comment] 2020-04-23 15:48
> @rahulshinde11, could you post a reproduce repo?

It was an issue with muliple instance of webpack, just had to rename the jsonpFunction, using @angular-builders/custom-webpack

**Comment by gkalpak** [comment] 2020-06-01 14:49
I am going to close this, because we didn't get a reproduction (and thus it is hard to tell whether it is still an issue with the latest versions). (E.g. based on https://github.com/angular/angular/issues/24466#issuecomment-396992106 it should have been fixed, but again hard to tell without a minimal reproduction).

If you are still running into this error with the latest Angular/Zone.js versions, please open a new issue providing the necessary details (including a (minimal 🙏) reproduction).

**Closed by gkalpak** 2020-06-01 14:49 UTC
Labels: comp: elements, freq1: low, severity3: broken, type: bug/fix
