### ISSUE TITLE
Parsing html template with [hidden] fails in IE9/10

### ISSUE THREAD

**Issue by wkwiatek** [angular/angular#5774] opened 2015-12-10 08:45 UTC
I just started to test app which is built on top of Angular2 in different environments and it turned out there are some issues on IE (mostly 9) and I'll try to let you know about them. 

One of them is html parser. When trying to parse following lines: 
```<div [hidden]="!isAuthorized">``` 

I get such error on both IE9 and IE10:
```Template parse errors: Can't bind to 'hidden' since it isn't a known native property```

Code above works on modern browsers like a charm. 

To fix it I had to make a workaround which seem to have no problems: 
```<div [style.display]="isAuthorized ? 'block' : 'none'">```

**Comment by zoechi** [comment] 2015-12-10 08:56
See #5761

**Comment by pkozlowski-opensource** [comment] 2015-12-10 09:26
@wkwiatek I presume this is because IE9 doesn't have `hidden`  _property_ - will try to confirm later on. If so it would need a polyffil, I'm not sure we want to work-around it in the framework (to be seen).

@zoechi why are you saying it is related to #5761? Could you elaborate? I don't see connection at all...

**Comment by zoechi** [comment] 2015-12-10 09:29
@pkozlowski-opensource because of the boolean attribute, seems I didn't pay enough attention when I read the error message.

**Comment by pkozlowski-opensource** [comment] 2015-12-10 09:31
@zoechi right. So those are not related really. I'm going to delete misleading comments so we can focus on the root cause here.

**Comment by wkwiatek** [comment] 2015-12-10 09:38
@pkozlowski-opensource Yes, there's no attribute like `hidden` in IE9/10 (it was introduced in IE11)

I'm just wondering what is the preferable way of showing/hiding elements that is cross-browser compatible? I mean what's the successor of `ng-show`, `ng-hide`? If the one above is that one I would vote for it to have polyfill in angular itself.

**Comment by pkozlowski-opensource** [comment] 2015-12-10 09:42
> Yes, there's no attribute like hidden in IE9/10 (it was introduced in IE11)

@wkwiatek `[hidden]` means binding to a _property_ not an attribute. So we need to check if a _property_ exists (probably not since there is no attribute)

**Comment by wkwiatek** [comment] 2015-12-10 10:27
Neither property nor attribute `hidden` exists in IE9/10.

**Comment by zoechi** [comment] 2015-12-10 10:37
I didn't do much web development with older browsers but I haven't heard yet that attributes need to exist on an element in order to be set. Can't arbitrary custom attributes added to elements? Is it just that Angular treats the `hidden` attribute special or is this special with older browsers?

**Comment by pkozlowski-opensource** [comment] 2015-12-10 10:39
@zoechi once again `[hidden]="exp"` means binding to PROPERTY, not an attribute. And yes, a property must exist - like any other member of a class that you are trying to use

**Comment by pkozlowski-opensource** [comment] 2015-12-10 18:39
> I'm just wondering what is the preferable way of showing/hiding elements that is cross-browser compatible?

I would say `ngIf`

**Comment by e-oz** [comment] 2016-04-13 12:03
better alternative to slow `*ngIf` is combination of `[attr.data-hidden]` (instead of `[hidden]`) and rule `[data-hidden="true"]{display: none !important}` in global CSS.

**Comment by zoechi** [comment] 2016-04-13 12:35
I think this can be closed. @e-oz is the common workaround for the missing `hidden` support in IE9.

**Comment by e-oz** [comment] 2016-04-13 13:04
it was not mentioned here, @zoechi.

**Comment by zoechi** [comment] 2016-04-13 14:52
@e-oz Sorry, didn't fully formulate the sentence - updated.

**Comment by ocombe** [comment] 2016-04-25 15:04
Not really, since this is not consistent with the other browser this should be fixed: either force to use [attr.hidden] everywhere or fix it for IE9/10. I just found out that my website couldn't display in IE10 because of this.

**Comment by e-oz** [comment] 2016-04-25 15:07
@ocombe in IE9/10 it's better to use `[attr.data-hidden]`, because they want to use custom attributes only with "data-" prefix.

**Comment by ocombe** [comment] 2016-04-25 15:09
They = IE ?

**Comment by e-oz** [comment] 2016-04-25 15:11
Yes, IE 9 and IE 10. Small group of ugly browsers.

**Comment by gog182** [comment] 2016-05-23 14:41
Would it seem normal to you that I face the same issue with IE 11 as well?

**Comment by zoechi** [comment] 2016-05-23 14:51
@gog182 Without a Plunker that demonstrates what you tried and allows to reproduce the issue it's hard to tell.

**Comment by pkozlowski-opensource** [comment] 2016-06-06 12:21
Going to close this one as there is no much we can do here... If a given browser doesn't support properties than it doesn't... One way to go would be to use polyffils, if possible....

**Closed by pkozlowski-opensource** 2016-06-06 12:21 UTC

**Comment by ikuriel** [comment] 2017-08-13 19:19
@e-oz solution, can't handle conditional var initialization, like:

`[attr.data-hidden]="someVar"`

but works if you explicitly check var init:

`[attr.data-hidden]="someVar?true:false"`

btw, i hate you IE a lot of patches to make you run....

**Comment by ocombe** [comment] 2017-08-14 07:54
@ikuriel even simpler: `[attr.data-hidden]="!!someVar"`

**Comment by ikuriel** [comment] 2017-08-15 04:00
yes, simpler tnx.

**Comment by kayode-anthony** [comment] 2017-10-25 15:10
If you are using bootstrap you can also use bootstrap's hidden. Similar to the CSS solution but you don't have to add anything to the global CSS file.
