### ISSUE TITLE
Shorthand Property Binding

### ISSUE THREAD

**Issue by achilesmatheus** [angular/angular#53109] opened 2023-11-22 00:47 UTC
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

Hello. Reading the tutorial for the new angular.dev path, in the [Property Binding](https://angular.dev/tutorials/learn-angular/property-binding) section, I saw the following code.

```js
import {Component} from '@angular/core';

@Component({
  selector: 'app-root',
  styleUrls: ['app.component.css'],
  template: `
    <div [contentEditable]="isEditable"></div>
  `,
  standalone: true,
})
export class AppComponent {
  isEditable = true;
}
```

### Proposed solution

To make it easier, I suggest a shortened form when the element's attribute matches the class property name:

The code would look like this:

```js
import {Component} from '@angular/core';

@Component({
  selector: 'app-root',
  styleUrls: ['app.component.css'],
  template: `
    <div [contentEditable]></div> // Shorthand property
  `,
  standalone: true,
})
export class AppComponent {
  contentEditable = true;
}
```

### Alternatives considered

When the elements repeat with the same attribute, you could do it like this:

```js
import {Component} from '@angular/core';

@Component({
  selector: 'app-root',
  styleUrls: ['app.component.css'],
  template: `
    <div [contentEditable].first></div>
    <div [contentEditable].second></div>
  `,
  standalone: true,
})
export class AppComponent {
  contentEditable = {first: true, second: false}
}
```

or the standard mode

```js
import {Component} from '@angular/core';

@Component({
  selector: 'app-root',
  styleUrls: ['app.component.css'],
  template: `
    <div [contentEditable]="isEditable"></div>
    <div [contentEditable]="isEditable2"></div>
  `,
  standalone: true,
})
export class AppComponent {
  isEditable = true;
  isEditable2 = true;
}
```

**Comment by pkozlowski-opensource** [comment] 2023-11-22 19:02
Duplicate of #21136

**Closed by pkozlowski-opensource** 2023-11-22 19:02 UTC
