### ISSUE TITLE
BrowserAnimationsModule Lazy loading

### ISSUE THREAD

**Issue by manduriomane** [angular/angular#47257] opened 2022-08-25 16:50 UTC
### Which @angular/* package(s) are relevant/related to the feature request?

animations

### Description

Hi,

I imported BrowserAnimationsModule in my app.module but, when I have compiled my project, my main.js file has grown a lot.

Is there a way to lazy load BrowserAnimationsModule?

I tried to import it in app.component.js in this way:

```
ngOnInit() {
import('src/libs/ng-uikit-pro/pro/alerts/toast/toast.module').then(m => m.ToastModule);
}
```

or in this way:
```
ngOnInit() {
const module = await import('@angular/platform-browser/animations');
const moduleFactory = await this.compiler.compileModuleAsync(module.BrowserAnimationsModule);
const moduleRef = moduleFactory.create(this.injector);
}
```

but components that use Angular animations don't work.

Thanks

### Proposed solution

.

### Alternatives considered

.

**Comment by AndrewKushnir** [comment] 2022-08-29 20:32
Closing as a duplicate of #38982.

**Closed by AndrewKushnir** 2022-08-29 20:32 UTC
