### ISSUE TITLE
Dynamic input field type not working as expected

### ISSUE THREAD

**Issue by hchockarprasad** [angular/angular#25188] opened 2018-07-29 09:50 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
`ngModel` value does not change for Input with `[type]="'checkbox'"`, whereas the value changes properly for input with `type`="checkbox".

## Expected behavior
`[type]="'checkbox'"` is equal to `type="checkbox"`

## Minimal reproduction of the problem with instructions

STACKBLITZ EDITOR URL -> https://stackblitz.com/edit/angular-1dphmy
STACKBLITZ APP URL -> https://angular-1dphmy.stackblitz.io

## Environment

<pre><code>
Angular version: 6.0.0

Browser:
- [X] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by trotyl** [comment] 2018-07-29 09:59
Duplicate of https://github.com/angular/angular/issues/13243

**Comment by kara** [comment] 2018-08-02 22:25
Closing as dupe of #13243. Angular currently doesn't allow triggering of directives through property bindings, so this is a limitation of the framework that needs to be addressed.

**Closed by kara** 2018-08-02 22:25 UTC
Labels: comp: forms
