### ISSUE TITLE
Uncaught Token must be defined!

### ISSUE THREAD

**Issue by Giegling** [angular/angular#8237] opened 2016-04-26 10:54 UTC
Hello, after updating to angular beta 16 I started getting this error. Does anyone have an idea what can cause this?

**Comment by shaneeb** [comment] 2016-04-26 11:02
Are you using ES6 modules and importing LocationStrategy? If yes then take a look at #8229. Basically LocationStrategy has been moved  to 'angular2/common/platform'

**Comment by Giegling** [comment] 2016-04-26 11:27
I don't use TS and I'm not importing anything like that.

**Comment by shaneeb** [comment] 2016-04-26 11:38
For me this error was being raised when calling bootstrap on the main app component and passing along application-wide providers. One of these providers was undefined (because of the above import issue) which caused this. I would suggest looking where you are defining providers to see if they are valid.

**Comment by shaneeb** [comment] 2016-04-26 11:41
For me this error was being raised when calling bootstrap on the main app component and passing along application-wide providers. One of these providers was undefined (because of the above import issue) which caused this. I would suggest looking where you are setting providers to see if they are valid.

**Comment by ericmartinezr** [comment] 2016-04-26 11:42
That's why a reproduction is required (e.g plnkr, repro, fiddle, etc)

**Comment by Giegling** [comment] 2016-04-26 11:51
How can I reproduce this on plnkr or somewhere else?


├── app.html
├── app.js
├── directives
│   └── learnInput
│       └── learnInput.js
├── localization
│   ├── eng.json
│   └── geo.json
├── pages
│   ├── auth
│   │   ├── auth.html
│   │   ├── auth.js
│   │   ├── auth.scss
│   │   ├── forgot.html
│   │   └── forgot.js
│   ├── learn
│   │   ├── learn.html
│   │   ├── learn.js
│   │   ├── learn.scss
│   │   └── tasks
│   │       ├── dictation
│   │       │   ├── dictation.html
│   │       │   └── dictation.js
│   │       └── translate
│   │           ├── translate.html
│   │           └── translate.js
│   └── wizard
│       ├── steps
│       │   ├── second.html
│       │   ├── second.js
│       │   ├── third.html
│       │   └── third.js
│       ├── wizard.html
│       ├── wizard.js
│       └── wizard.scss
├── providers
│   ├── appSettings.js
│   ├── auth
│   │   └── auth.js
│   ├── config.js
│   ├── learn
│   │   ├── learnProvider.js
│   │   └── learnService.js
│   ├── pipes.js
│   ├── storage
│   │   └── storage.js
│   └── validator
│       ├── messages.js
│       └── validator.js
└── theme
    ├── app.core.scss
    ├── app.ios.scss
    ├── app.md.scss
    ├── app.variables.scss
    └── app.wp.scss

**Comment by tleguijt** [comment] 2016-04-26 12:26
This error is also raised when I use ROUTER_PROVIDERS in my bootstrap

**Comment by Delagen** [comment] 2016-04-26 13:33
I think this is because no export LocationStrategy and HashLocationStrategy from angular2/router

**Comment by ericmartinezr** [comment] 2016-04-26 13:35
@Giegling by copy & pasting your project code into the plnkr. Anyway, the error is because you're passing something undefined to the bootstrap, so as everyone have suggested check the paths, a few and littke *cough* breaking changes landed with b.16.

**Comment by Delagen** [comment] 2016-04-26 13:37
> breaking changes landed with b.16.
No any defined in CHANGELOG.md

**Comment by ericmartinezr** [comment] 2016-04-26 13:39
@Delagen actually yes https://github.com/angular/angular/blob/master/CHANGELOG.md#breaking-changes , but I understand what you say, all the important changes didn't appear in the changelog, which doesn't mean they're there. See the new issues/PRs. People already reported and they're sending PRs to update the changelog.

**Comment by Delagen** [comment] 2016-04-26 13:42
So webpack builds are broken due no export of LocationStrategy and others in any variable.

**Comment by mattcarp** [comment] 2016-04-26 13:45
Try changing:

    import { ROUTER_PROVIDERS, LocationStrategy, HashLocationStrategy } from 'angular2/router';

to:

    import {ROUTER_PROVIDERS} from 'angular2/router';
    import {LocationStrategy, HashLocationStrategy} from 'angular2/platform/common';

`

**Comment by Giegling** [comment] 2016-04-26 13:46
I don't import anything which has connection with router.

**Comment by Delagen** [comment] 2016-04-26 13:47
If you use ready webpack build you cannot.
added to builds
```
common:     require("angular2/platform/common"),
```

**Comment by ericmartinezr** [comment] 2016-04-26 13:48
@Giegling nobody knows what's going on, everyone is guessing. Reproduce it in a plnkr, paste your code on gist, pastebin, or whatever. You will never solve your issue if you don't help anyone to help you.

**Comment by Delagen** [comment] 2016-04-26 13:52
try to use plnkr with build from https://code.angularjs.org/2.0.0-beta.16/angular2-all.umd.js
Simply no any access to platform/common namespace through ng.platform.common.
Correct file tools/build/webpack/angular2-all.umd.js and rebuild

**Comment by Delagen** [comment] 2016-04-26 14:12
Throws the error
```
No base href set. Please provide a value for the APP_BASE_HREF token or add a base element to the document.
```
added
```
provide(LocationStrategy, {useClass: HashLocationStrategy}),
provide(APP_BASE_HREF, {useValue: "/"})
```
but nothing changed

**Comment by yfain** [comment] 2016-04-26 15:30
This was an unannounced breaking change in beta.16.

I also had this "Token must be defined" error after upgrading to beta.16 (I am using TypeScript). I had to delete the node_modules directory and then npm install.
The error was gone after importing locatin strategies like this:

import {LocationStrategy, HashLocationStrategy} from 'angular2/platform/common';

 Without deleting node_modules the above line wouldn't compile.

**Comment by Giegling** [comment] 2016-04-26 15:52
`import { App, IonicApp, Platform, Events, MenuController } from 'ionic-angular';
import { provide } from 'angular2/core';
import { TRANSLATE_PROVIDERS, TranslateService, TranslatePipe, TranslateLoader, TranslateStaticLoader } from 'ng2-translate/ng2-translate';
import { HTTP_PROVIDERS, JSONP_PROVIDERS, Http } from 'angular2/http';
import { AuthProvider } from './providers/auth/auth';
import { StorageProvider } from './providers/storage/storage';
import { AuthPage } from './pages/auth/auth';
import { WizardPage } from './pages/wizard/wizard';
import { LearnPage } from './pages/learn/learn';`

That's all I'm importing in my main app.js.

**Comment by chrisbenseler** [comment] 2016-04-26 18:03
I'm facing the same problem with the upgrade to beta16. None of the tips have worked (change the import path from LocationStrategy and HashLocationStrategy, event after deleting node_modules directory).
The same code works perfect with beta15.

**Comment by Delagen** [comment] 2016-04-27 05:15
Seems that
```
provide(LocationStrategy, {useClass: HashLocationStrategy}),
```
does not override LocationStrategy ((

**Comment by radoslavpetranov** [comment] 2016-04-27 06:16
Changing 

````
import {LocationStrategy, HashLocationStrategy, ROUTER_PROVIDERS} from 'angular2/router';
````

to 

````
import {ROUTER_PROVIDERS} from 'angular2/router';
import {LocationStrategy, HashLocationStrategy} from 'angular2/platform/common';
````

solved the compilation issue for me. Thanks @mattcarp !!

**Comment by radoslavpetranov** [comment] 2016-04-27 07:47
I noticed something else - in beta15, when we use

````
changeDetection: ChangeDetectionStrategy.OnPush,
````

and then have something like

````
<h2>Hello {{_model.firstName}}</h2>
<div class="form-group">
	<input *ngIf="_model" type="text" class="form-control" required [(ngModel)]="_model.firstName" ngControl="firstName">
</div>

<template [ngIf]="_model">
	<input type="text" class="form-control" required [(ngModel)]="_model.firstName" ngControl="test2"  #myInput >
	<br>Class: {{myInput?.className}}
</template>
````

the 2 inputs are constantly in sync and the text interpolation is also updated.

The moment you switch to beta16, all model changes require a markForCheck() in order for the UI to get updated.

It looks like this really is a bug fix and not a regression but can someone confirm that this indeed is the desired behavior.

You can reproduce the behavior here:

beta15: http://plnkr.co/edit/iFT1155D3mwn7vOYGjKF?p=preview

beta16: http://plnkr.co/edit/6NDj3OPmHvE5wOPHoxQy?p=preview

**Comment by zoechi** [comment] 2016-04-27 08:04
@radoslavpetranov sounds like #8242

**Comment by radoslavpetranov** [comment] 2016-04-27 08:11
@zoechi, thanks, yeah looks like it - I'll post in that issue not to hijack this one any further.

**Comment by Delagen** [comment] 2016-04-27 08:14
@ericmartinezr Thanks for support, cause tsconfig.json issue. Now all fine. But npm packages contains   incompleted umd builds, so rebuild it. (They have inaccessible angular2/platform/common namespace)

**Comment by NathanWalker** [comment] 2016-04-27 23:31
UMD builds should be fixed with this: https://github.com/angular/angular/issues/8300

For those using ionic independent of their own angular install, you may need to wait until ionic supports beta.16 due to `Location` import changes.

For all other issues, as mentioned above, changing the import:
```
import {LocationStrategy, HashLocationStrategy, ROUTER_PROVIDERS} from 'angular2/router';
```
to
```
import {ROUTER_PROVIDERS} from 'angular2/router';
import {LocationStrategy, HashLocationStrategy} from 'angular2/platform/common';
```

Should help you.

**Comment by kfirufk** [comment] 2016-04-28 05:08
same error: Uncaught Token must be defined! 
using angular2 beta 16

working on an angualr2-meteor project. 

downgraded to beta15 for meantime till issue will be resolved.

**Comment by deepakgd** [comment] 2016-04-28 05:39
@NathanWalker thanks

**Comment by EdmondWang** [comment] 2016-04-28 06:09
@mattcarp , thank you, this resolved my 'Token must be defined', after upgrade to 16.

**Comment by chrisbenseler** [comment] 2016-04-29 17:35
@NathanWalker this explains why I cannot upgrade 10 16+: I'm using angular2 in an Ionic app.
Waiting for a new ionic's release.

**Comment by NathanWalker** [comment] 2016-04-29 19:34
You might want to post an issue on Ionic's repo to encourage the update?

**Closed** 2016-06-22 00:27 UTC
Labels: hotlist: error messages
