### ISSUE TITLE
Adding routing breaks document.referrer functionality in IE 11

### ISSUE THREAD

**Issue by xtrandom** [angular/angular#38234] opened 2020-07-25 21:13 UTC
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/router

### Description
In IE 11, when redirecting to angular apps with routing, `document.referrer` is empty (instead of sender)

## 🔬 Minimal Reproduction
<pre><code>
!Works:
- In IE, open console and go to https://referrer-source.netlify.app/
- Click "Target Site" (redirects to https://referrer-target.netlify.app/)
- Check `document.referrer` value in console
- Returns ""

Works:
- In IE, open console and go to https://referrer-source.netlify.app/
- Click "Target Site -- No Routing" (redirects to https://referrer-target-simple.netlify.app/)
- Check `document.referrer` value in console
- Returns "https://referrer-source.netlify.app/"

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.1.12
Node: 12.16.3
OS: win32 x64

Angular: 9.1.12
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.12
@angular-devkit/build-angular     0.901.12
@angular-devkit/build-optimizer   0.901.12
@angular-devkit/build-webpack     0.901.12
@angular-devkit/core              9.1.12
@angular-devkit/schematics        9.1.12
@ngtools/webpack                  9.1.12
@schematics/angular               9.1.12
@schematics/update                0.901.12
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0

</code></pre>

**Comment by xtrandom** [comment] 2020-08-03 12:44
Has anyone had a chance to look into this? It has been in `needsTriage` stage for over a week.

**Comment by atscott** [comment] 2020-08-04 18:55
This appears to be an issue with IE 11 which does not keep the `document.referrer` value when calling `history.replaceState` like other browsers. The router's initial navigation would trigger a `replaceState` via `setBrowserUrl`. The only way to avoid this on the Angular Router side would be to not call `replaceState` to store the `navigationId` which would need quite a bit of thought and design.

If all you need is to get the true value of `document.referrer` in your app, you can achieve this by saving the value in an `APP_INITIALIZER` that runs before the initial navigation.

**Comment by xtrandom** [comment] 2020-08-10 12:45
@atscott There's still IE limitations (on refresh), but getting `document.referrer` value in an `APP_INITIALIZER` worked for my purposes! Thank you!

**Comment by mcalmus** [comment] 2020-12-08 10:29
I'm seeing that document.referrer isn't working in <any> browser. Not just IE.

**Comment by atscott** [comment] 2020-12-08 15:42
@mcalmus can you please clarify your issue? Document.referrer does not get set when navigating internal to a site. It would not be the job of the Angular application to set document.referrer. This issue here is due to the Angular routing accidentally clearing the value on initial navigation.

**Comment by mcalmus** [comment] 2020-12-08 19:06
I need a way to determine whether a component was accessed via an external link in or was linked to from within the app. This would typically be done using the referrer. Perhaps this should be a feature request, but document.referrer is definitely not working.

**Comment by atscott** [comment] 2020-12-08 19:16
@mcalmus - Are you saying that `document.referrer` is not assigned when navigating to your application from an external link? I do not see that behavior. [Here's a link](https://angular-ivy-s55fln.stackblitz.io/#/hello) to the reproduction from your original report. `document.referrer` is `"https://github.com/angular/angular/issues/38234"`. Again, as discussed in this report, assigning `document.referrer` is the responsibility of the browser, not Angular.

**Comment by mcalmus** [comment] 2020-12-08 20:25
`document.referrer` is getting set by the browser when I navigate to my application. However, when navigating to another route within the application, the same initial value is there. This makes sense but means there is no way to reliably tell what actually referred to a page.

**Comment by atscott** [comment] 2020-12-08 21:07
@mcalmus - Okay, I understand. I would recommend a different approach in your application then. What you're describing is browser behavior unrelated to Angular. You can see this same behavior when navigating around any other website as well.

**Comment by atscott** [comment] 2021-11-01 03:24
Closing as an issue outside of Angular.

**Closed by atscott** 2021-11-01 03:24 UTC
Labels: type: bug/fix, comp: router, browser: ie 11, P4
