### ISSUE TITLE
AOT compilation fails - Recursion not supported - Angular 5.0.0-beta.7

### ISSUE THREAD

**Issue by MrBlaise** [angular/angular#19200] opened 2017-09-14 14:39 UTC
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Can't build with `ng build` because it fails due to AOT failing, `ng build --aot=false` and `ng serve` works fine. This issue occured after I upgraded to 5.0.0-beta.7 (using the package [ngx-toastr](https://github.com/scttcper/ngx-toastr)). It happened with different third party package as well I changed it to another one and the error is the same. Did AOT compilation change significantly in Angular 5.x, should it affect every third party library already out there?

```

ERROR in Error: Recursion not supported, resolving symbol style in /Users/balazsrostas/Development/Avatao/NewFrontend/frontend/node_modules/@angular/core/index.d.ts, resolving symbol Toast in /Users/balazsrostas/Development/Avatao/NewFrontend/frontend/node_modules/ngx-toastr/index.d.ts, resolving symbol Toast in /Users/balazsrostas/Development/Avatao/NewFrontend/frontend/node_modules/ngx-toastr/index.d.ts, resolving symbol Toast in /Users/balazsrostas/Development/Avatao/NewFrontend/frontend/node_modules/ngx-toastr/index.d.ts, resolving symbol Toast in /Users/balazsrostas/Development/Avatao/NewFrontend/frontend/node_modules/ngx-toastr/index.d.ts
    at syntaxError (/Users/balazsrostas/Development/Avatao/NewFrontend/frontend/node_modules/@angular/compiler/bundles/compiler.umd.js:251:17)
    at simplifyInContext (/Users/balazsrostas/Development/Avatao/NewFrontend/frontend/node_modules/@angular/compiler/bundles/compiler.umd.js:18251:23)
    at StaticReflector.simplify (/Users/balazsrostas/Development/Avatao/NewFrontend/frontend/node_modules/@angular/compiler/bundles/compiler.umd.js:18263:13)
    at StaticReflector.annotations (/Users/balazsrostas/Development/Avatao/NewFrontend/frontend/node_modules/@angular/compiler/bundles/compiler.umd.js:17752:41)
    at NgModuleResolver.resolve (/Users/balazsrostas/Development/Avatao/NewFrontend/frontend/node_modules/@angular/compiler/bundles/compiler.umd.js:11512:53)
    at CompileMetadataResolver.getNgModuleMetadata (/Users/balazsrostas/Development/Avatao/NewFrontend/frontend/node_modules/@angular/compiler/bundles/compiler.umd.js:9076:43)
    at addNgModule (/Users/balazsrostas/Development/Avatao/NewFrontend/frontend/node_modules/@angular/compiler/bundles/compiler.umd.js:17645:41)
    at /Users/balazsrostas/Development/Avatao/NewFrontend/frontend/node_modules/@angular/compiler/bundles/compiler.umd.js:17656:14
    at Array.forEach (native)
    at _createNgModules (/Users/balazsrostas/Development/Avatao/NewFrontend/frontend/node_modules/@angular/compiler/bundles/compiler.umd.js:17655:26)
    at analyzeNgModules (/Users/balazsrostas/Development/Avatao/NewFrontend/frontend/node_modules/@angular/compiler/bundles/compiler.umd.js:17547:14)
    at analyzeAndValidateNgModules (/Users/balazsrostas/Development/Avatao/NewFrontend/frontend/node_modules/@angular/compiler/bundles/compiler.umd.js:17551:18)
    at AotCompiler.analyzeModulesAsync (/Users/balazsrostas/Development/Avatao/NewFrontend/frontend/node_modules/@angular/compiler/bundles/compiler.umd.js:17267:29)
    at CodeGenerator.codegen (/Users/balazsrostas/Development/Avatao/NewFrontend/frontend/node_modules/@angular/compiler-cli/src/codegen.js:31:14)
    at Function.NgTools_InternalApi_NG_2.codeGen (/Users/balazsrostas/Development/Avatao/NewFrontend/frontend/node_modules/@angular/compiler-cli/src/ngtools_api.js:70:30)
    at _donePromise.Promise.resolve.then (/Users/balazsrostas/Development/Avatao/NewFrontend/frontend/node_modules/@ngtools/webpack/src/plugin.js:386:44)
    at <anonymous>


```

## Expected behavior
It shoud build properly.

## Minimal reproduction of the problem with instructions

Upgrade to Angular 5.0.0-beta.7 use [ngx-toastr](https://github.com/scttcper/ngx-toastr) package
try to build with `ng build --prod --aot`

## Environment

<pre><code>
Angular version: 5.0.0-beta.7

 
For Tooling issues:
- Node version: v8.1.4  
- Platform: macOS 10.12.6

**Comment by scttcper** [comment] 2017-09-14 17:33
Tried using angular-cli 1.5.0-beta.0 as well. Different error. Slightly better?

```bash
ERROR in Error: Error encountered resolving symbol values statically. Calling function 'ToastrModule', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule in /Users/scoope7/toastr5/src/app/app.module.ts, resolving symbol AppModule in /Users/scoope7/toastr5/src/app/app.module.ts
    at syntaxError (/Users/scoope7/toastr5/node_modules/@angular/compiler/bundles/compiler.umd.js:251:17)
    at simplifyInContext (/Users/scoope7/toastr5/node_modules/@angular/compiler/bundles/compiler.umd.js:18251:23)
    at StaticReflector.simplify (/Users/scoope7/toastr5/node_modules/@angular/compiler/bundles/compiler.umd.js:18263:13)
    at StaticReflector.annotations (/Users/scoope7/toastr5/node_modules/@angular/compiler/bundles/compiler.umd.js:17752:41)
    at NgModuleResolver.resolve (/Users/scoope7/toastr5/node_modules/@angular/compiler/bundles/compiler.umd.js:11512:53)
    at CompileMetadataResolver.getNgModuleMetadata (/Users/scoope7/toastr5/node_modules/@angular/compiler/bundles/compiler.umd.js:9076:43)
    at addNgModule (/Users/scoope7/toastr5/node_modules/@angular/compiler/bundles/compiler.umd.js:17645:41)
    at /Users/scoope7/toastr5/node_modules/@angular/compiler/bundles/compiler.umd.js:17656:14
    at Array.forEach (<anonymous>)
    at _createNgModules (/Users/scoope7/toastr5/node_modules/@angular/compiler/bundles/compiler.umd.js:17655:26)
    at analyzeNgModules (/Users/scoope7/toastr5/node_modules/@angular/compiler/bundles/compiler.umd.js:17547:14)
    at analyzeAndValidateNgModules (/Users/scoope7/toastr5/node_modules/@angular/compiler/bundles/compiler.umd.js:17551:18)
    at AotCompiler.analyzeModulesAsync (/Users/scoope7/toastr5/node_modules/@angular/compiler/bundles/compiler.umd.js:17267:29)
    at AngularCompilerProgram.loadNgStructureAsync (/Users/scoope7/toastr5/node_modules/@angular/compiler-cli/src/transformers/program.js:104:30)
    at _donePromise.Promise.resolve.then (/Users/scoope7/toastr5/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:363:38)
    at <anonymous>
```

I'm not able to compile the ngx-toastr project and try w/ newer metadata from 5.0.0-beta.7 due to #18867

**Comment by yarrgh** [comment] 2017-09-15 15:07
It's an issue with animations being used by the Toastr component. If you comment out the whole animations section in the Toastr component (and any component that uses animations), everything compiles. Did the use of animations change with angular 5.0.0-beta.7?

The compiler has issues with animations being used in `@angular/core`. This includes `trigger`, `animate`, `style`, and probably `transition`

**Comment by scttcper** [comment] 2017-09-15 21:17
@yarrgh fixed this by changing the import on our animations form `@angular/core` to `@angular/animations`. The errors could've been more helpful, not sure why typescript allowed us to import from `@angular/core` still.

**Comment by alexeagle** [comment] 2017-09-16 05:47
@matsko Looks like an issue with the published typings, allowing those symbols to type-check?

**Comment by matsko** [comment] 2017-09-18 19:15
@chuckjaz it looks like this bug resurfaced. Can you investigate?

**Comment by TakanashiOuken** [comment] 2017-09-19 08:41
Having the same bug. Hope fixed soon~

**Comment by chuckjaz** [comment] 2017-09-26 23:30
I tried the following steps:

1) `ng new toast5`
2) cd toast5
3) followed the instructions [here](https://github.com/scttcper/ngx-toastr/blob/master/README.md) to update the project to add `ngx-toastr`
4) `ng serve` to verify it works without aot
5) `ng serve --aot` verify it works with aot
6) `ng build --aot` to just build

All of the above steps work. What am I missing?

The following is a diff of the changes I made:

```
diff --git a/.angular-cli.json b/.angular-cli.json
index 7940e74..95642ec 100644
--- a/.angular-cli.json
+++ b/.angular-cli.json
@@ -19,7 +19,8 @@
       "testTsconfig": "tsconfig.spec.json",
       "prefix": "app",
       "styles": [
-        "styles.css"
+        "styles.css",
+        "../node_modules/ngx-toastr/toastr.css"
       ],
       "scripts": [],
       "environmentSource": "environments/environment.ts",
diff --git a/package.json b/package.json
index a9da5ea..d038c9a 100644
--- a/package.json
+++ b/package.json
@@ -12,23 +12,24 @@
   },
   "private": true,
   "dependencies": {
-    "@angular/animations": "^4.2.4",
-    "@angular/common": "^4.2.4",
-    "@angular/compiler": "^4.2.4",
-    "@angular/core": "^4.2.4",
-    "@angular/forms": "^4.2.4",
-    "@angular/http": "^4.2.4",
-    "@angular/platform-browser": "^4.2.4",
-    "@angular/platform-browser-dynamic": "^4.2.4",
-    "@angular/router": "^4.2.4",
+    "@angular/animations": "^5.0.0-beta.7",
+    "@angular/common": "^5.0.0-beta.7",
+    "@angular/compiler": "^5.0.0-beta.7",
+    "@angular/core": "^5.0.0-beta.7",
+    "@angular/forms": "^5.0.0-beta.7",
+    "@angular/http": "^5.0.0-beta.7",
+    "@angular/platform-browser": "^5.0.0-beta.7",
+    "@angular/platform-browser-dynamic": "^5.0.0-beta.7",
+    "@angular/router": "^5.0.0-beta.7",
     "core-js": "^2.4.1",
+    "ngx-toastr": "^6.3.0",
     "rxjs": "^5.4.2",
     "zone.js": "^0.8.14"
   },
   "devDependencies": {
     "@angular/cli": "1.4.3",
-    "@angular/compiler-cli": "^4.2.4",
-    "@angular/language-service": "^4.2.4",
+    "@angular/compiler-cli": "^5.0.0-beta.7",
+    "@angular/language-service": "^5.0.0-beta.7",
     "@types/jasmine": "~2.5.53",
     "@types/jasminewd2": "~2.0.2",
     "@types/node": "~6.0.60",
diff --git a/src/app/app.component.html b/src/app/app.component.html
index 46d517b..54dd76d 100644
--- a/src/app/app.component.html
+++ b/src/app/app.component.html
@@ -3,6 +3,9 @@
   <h1>
     Welcome to {{title}}!
   </h1>
+  <div>
+    <button (click)="showSuccess()">Click Me!</button>
+  </div>
   <img width="300" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNTAgMjUwIj4KICAgIDxwYXRoIGZpbGw9IiNERDAwMzEiIGQ9Ik0xMjUgMzBMMzEuOSA2My4ybDE0LjIgMTIzLjFMMTI1IDIzMGw3OC45LTQzLjcgMTQuMi0xMjMuMXoiIC8+CiAgICA8cGF0aCBmaWxsPSIjQzMwMDJGIiBkPSJNMTI1IDMwdjIyLjItLjFWMjMwbDc4LjktNDMuNyAxNC4yLTEyMy4xTDEyNSAzMHoiIC8+CiAgICA8cGF0aCAgZmlsbD0iI0ZGRkZGRiIgZD0iTTEyNSA1Mi4xTDY2LjggMTgyLjZoMjEuN2wxMS43LTI5LjJoNDkuNGwxMS43IDI5LjJIMTgzTDEyNSA1Mi4xem0xNyA4My4zaC0zNGwxNy00MC45IDE3IDQwLjl6IiAvPgogIDwvc3ZnPg==">
 </div>
 <h2>Here are some links to help you start: </h2>
diff --git a/src/app/app.component.ts b/src/app/app.component.ts
index 7b0f672..21027d3 100644
--- a/src/app/app.component.ts
+++ b/src/app/app.component.ts
@@ -1,4 +1,5 @@
 import { Component } from '@angular/core';
+import { ToastrService } from 'ngx-toastr';
 
 @Component({
   selector: 'app-root',
@@ -7,4 +8,10 @@ import { Component } from '@angular/core';
 })
 export class AppComponent {
   title = 'app';
+
+  constructor(private toastr: ToastrService) {}
+
+  showSuccess() {
+    this.toastr.success('Hello world!', 'Toastr fun!');
+  }
 }
diff --git a/src/app/app.module.ts b/src/app/app.module.ts
index f657163..cd35421 100644
--- a/src/app/app.module.ts
+++ b/src/app/app.module.ts
@@ -1,6 +1,8 @@
 import { BrowserModule } from '@angular/platform-browser';
 import { NgModule } from '@angular/core';
+import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
 
+import { ToastrModule } from 'ngx-toastr';
 import { AppComponent } from './app.component';
 
 @NgModule({
@@ -8,7 +10,9 @@ import { AppComponent } from './app.component';
     AppComponent
   ],
   imports: [
-    BrowserModule
+    BrowserModule,
+    BrowserAnimationsModule,
+    ToastrModule.forRoot()
   ],
   providers: [],
   bootstrap: [AppComponent]
```

**Comment by scttcper** [comment] 2017-09-27 00:08
@chuckjaz we switched our animation imports from `@angular/core` to `@angular/animations` on the latest version.

An older version would have the issue.
`npm i ngx-toastr@6.1.4`

**Comment by chuckjaz** [comment] 2017-09-27 16:53
The issue is that the metadata in `@angular/core/index.metadata.json` records `style` as calling a shrouded private function `ɵbc` which is a alias of `style` causing a recursive loop.

We have fixed several bugs regarding how the metadata is produced that seems to have fixed this as in the latest build in `angular/core-builds` doesn't exhibit this issue.

The primary work around, as you discovered, is to avoid referencing the deprecated animation functions in `@angular/core` by switching to importing these functions from `@angluar/animations`. 

I will leave this open until we can very that this has been fixed in the latest release.

**Comment by scttcper** [comment] 2017-09-30 16:16
@chuckjaz working on the RC correctly. It looks like we can import from `@angular/core` again.

**Comment by chuckjaz** [comment] 2017-10-01 02:16
@scttcper Is there a reason for you importing from `@angular/core`? The core versions of those methods are deprecated

**Closed** 2017-10-01 02:16 UTC
Labels: comp: core & compiler, severity5: regression, state: Follow Up, type: bug

**Comment by scttcper** [comment] 2017-10-01 02:57
@chuckjaz No reason. Just never changed it because it worked.
