### ISSUE TITLE
Add `RouteTitle` to the public API

### ISSUE THREAD

**Issue by markostanimirovic** [angular/angular#46869] opened 2022-07-18 14:10 UTC
### Which @angular/* package(s) are relevant/related to the feature request?

router

### Description

The [`@ngrx/router-store`](https://www.npmjs.com/package/@ngrx/router-store) package needs access to the resolved title. Therefore, it would be good to expose the [`RouteTitle`](https://github.com/angular/angular/blob/3a60063a54d850c50ce962a8a39ce01cfee71398/packages/router/src/operators/resolve_data.ts#L24) symbol and use it to get the resolved title from the `route.data` object.

Related issue: https://github.com/ngrx/platform/issues/3495

### Proposed solution

**I'll create the PR if this feature request is accepted.**

### Alternatives considered

We can get the resolved title in the following way:

```ts
const routeTitleSymbol = Object.getOwnPropertySymbols(route.data).find(
  (symbol) => symbol.toString() === 'Symbol(RouteTitle)'
);
const routeTitle = route.data[routeTitleSymbol];
```

However, the `@ngrx/router-store` package will be broken if `Symbol('RouteTitle')` is changed internally.

**Comment by atscott** [comment] 2022-07-18 14:29
Duplicate of https://github.com/angular/angular/issues/46825. We’ll be exposing it as `route.title` on the ActivatedRoute/ActivatedRouteSnapshot.

**Closed by atscott** 2022-07-18 14:29 UTC
