### ISSUE TITLE
Is PromisePipe working?

### ISSUE THREAD

**Issue by armorik83** [angular/angular#2148] opened 2015-05-25 07:40 UTC
Hi.

```
npm i browserify angular2@2.0.0-alpha.25 typescript@1.5.0-alpha reflect-metadata babel-core
cp ./node_modules/babel-core/browser-polyfill.min.js ./browser-polyfill.min.js
touch index.html index.ts angular2.d.ts
```

**index.ts**
```ts
/// <reference path="angular2.d.ts" />
'use strict';

declare var require: any, Promise: any;
import 'reflect-metadata';
import {bind, PipeRegistry, Component, View, bootstrap} from 'angular2/angular2';
import {defaultPipes} from 'angular2/change_detection';

const pipes = (<any>Object).assign({}, defaultPipes);

@Component({
  selector: 'app'
})
@View({
  template: `<p>Sync: {{syncval}}</p><p>Async: {{asyncval|async}}</p>`
})
class App {
  syncval = 'syncval';
  asyncval: any;

  constructor() {
    this.asyncval = new Promise(resolve => {
      setTimeout(() => {
        resolve('asyncval');
      }, 1000);
    });
  }
}

bootstrap(App, [
  bind(PipeRegistry).toValue(new PipeRegistry(pipes))
]);
```

**angular2.d.ts**
```ts
declare module "angular2/angular2" {
  export function Component(arg: any);
  export function View(arg: any);
  export function bootstrap(...args: any[]);
  export function bind(...args: any[]): any;
  export class PipeRegistry{
    constructor(_: any);
  }
}

declare module "angular2/change_detection" {
  export var defaultPipes: any;
}
```

**index.html**
```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Document</title>
</head>
<body>
  <app></app>
  <script src="./browser-polyfill.min.js"></script>
  <script src="./bundle.js"></script>
</body>
</html>
```

Building
```
$(npm bin)/tsc index.ts -t es5 -m commonjs && $(npm bin)/browserify -e index.js -o bundle.js
```

Rewrite `bundle.js` to the below

```
PromisePipe.prototype._updateLatestValue = function (value) {
  console.log('_updateLatestValue', value); // Added
  this._latestValue = value;
  this._ref.requestCheck();
};
```

The result on Chrome 43.0.2357.65

```
Sync: syncval
Async:
```

and, the result in console.log

```
_updateLatestValue asyncval
```

`{{asyncval|async}}` is not bound to the screen? is this a bug or am I missing something?

**Comment by jeffbcross** [comment] 2015-05-26 23:34
Looking into this...

**Comment by jeffbcross** [comment] 2015-05-27 00:02
I've created a plunker to verify that basic promise usage is functioning correctly: http://plnkr.co/edit/Tm88sFUDonkeKANw0qTv?p=preview

Now I'm going to try to reproduce with your code.

**Comment by jeffbcross** [comment] 2015-05-27 00:09
@armorik83  this plunker with your code is working as expected: http://plnkr.co/edit/iDcfhZ182E46tGBcQX0L?p=preview

Since promise pipe is already in the async pipe, which is in the `defaultPipes`, you shouldn't need to create and bind your own PipeRegistry. Can you try removing that and seeing if it works as expected?

It could also be an issue with the polyfill you're using, can you share what polyfill you're using?

**Comment by armorik83** [comment] 2015-05-27 12:26
Well, I see...! I was sure it works indeed.

I have reproduced this sample at my hand.
It works correctly when using this `https://code.angularjs.org/2.0.0-alpha.25/angular2.sfx.dev.js`.
But, It does not work in Angular 2.0.0-alpha.25 + Browserify@latest.

I have used the `browser-polyfill.js` of Babel@latest for the Promise-polyfill of both case.

---

`browser-polyfill.js` is here.

```
npm i babel-core
# ./node_modules/babel-core/browser-polyfill.js
```

index.html

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <script src="https://code.angularjs.org/2.0.0-alpha.25/angular2.sfx.dev.js"></script>
  <title>example</title>
</head>
<body>
  <my-app></my-app>
  <script src="./browser-polyfill.min.js" charset="utf-8"></script>
  <script src="./bundle.js" charset="utf-8"></script>
</body>
</html>
```

index.ts

```
/* The wrong case, with `npm i angular2@2.0.0-alpha.25` */
// declare var require: any;
// const reflect = require('reflect-metadata');
// import {Component, View, bootstrap} from 'angular2/angular2';

/* The good case, with `angular2.sfx.dev.js` */
const {Component, View, bootstrap} = (<any>window).angular;

@Component({
  selector: 'my-app'
})
@View({
  template: '<p>Sync: {{syncval}}</p><p>Async: {{asyncval|async}}</p>'
})
class MyAppComponent {
  syncval = 'syncval';
  asyncval = new Promise(function (resolve) {
    setTimeout(function () {
      resolve('asyncval');
    }, 1000);
  });
}

bootstrap(MyAppComponent);
```

```
$(npm bin)/tsc index.ts -t es5 -m commonjs && $(npm bin)/browserify -e index.js -o bundle.js
```

Thank you.

**Comment by vicb** [comment] 2015-05-27 12:59
A Promise monkey patch is included in ng2 (via zone.js). You **should not** use any other Promise polyfill.

**Comment by armorik83** [comment] 2015-05-27 13:37
uh oh! I had forgotten completely about Zone.js.
This was re-challenge in view of the Zone.js, it worked. It's a blind spot.
Thank you for me a hint @vicb.

**Comment by vicb** [comment] 2015-05-27 14:21
We can leave this open until we have more time to check what was going wrong.
I've just tried the Promise polyfill you use (from GH master) but it does not seem to overwrite the monkey patch.

**Comment by armorik83** [comment] 2015-05-27 14:34
Understood.
I use this `https://code.angularjs.org/2.0.0-alpha.25/angular2.sfx.dev.js` for a while, and I will try to check for a more `src/facade`.

**Comment by vicb** [comment] 2015-05-27 14:42
`src/facade` is mainly something we use internally because with need to generate both a .js and a .dart version of Angular (`Observable` & `EventEmitter` being 2 exceptions). You should not need to use this - unless you target both js & dart of course.

**Comment by armorik83** [comment] 2015-05-27 14:59
Okay. I think It is difficult to support both JS and Dart.
Understood way to use of `facade`.

**Comment by mhevery** [comment] 2015-05-31 03:14
Sounds like there is no action on our side. Closing.

**Closed by mhevery** 2015-05-31 03:14 UTC
Labels: comp: core/change_detection, type: RFC / discussion / question
