### ISSUE TITLE
Using compiler-cli/main directly on a module with import `@uirouter/angular` renames import in compiled file.

### ISSUE THREAD

**Issue by Kamilius** [angular/angular#19327] opened 2017-09-22 08:09 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Trying to create a `ngModule as separate NPM package`, using following generator: https://github.com/jvandemo/generator-angular2-library.
Module (and a consumer project) utilizes `@uirouter/angular` for routing. Generator's gulp script is compiling angular, in a following manner:
```js
var gulp = require('gulp');
var ngc = require('@angular/compiler-cli/src/main').main;

/**
 * 4. Run the Angular compiler, ngc, on the /.tmp folder. This will output all
 *    compiled modules to the /build folder.
 */
gulp.task('ngc', function () {
  return ngc({
    project: `${tmpFolder}/tsconfig.es5.json`
  })
    .then((exitCode) => {
      if (exitCode === 1) {
        // This error is caught in the 'compile' task by the runSequence method callback
        // so that when ngc fails to compile, the whole compile process stops running
        throw new Error('ngc compilation failed');
      }
    });
});
```
`.tmp` folder is just a folder with copies of an `src` `ts` files, nothing gets changed there.

tsconfig.es5.json:
```js
{
  "compilerOptions": {
    "declaration": true,
    "module": "es2015",
    "target": "es5",
    "baseUrl": ".",
    "stripInternal": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "moduleResolution": "node",
    "outDir": "../build",
    "rootDir": ".",
    "lib": [
      "es2015",
      "dom"
    ],
    "skipLibCheck": true,
    "types": []
  },
  "angularCompilerOptions": {
    "annotateForClosureCompiler": true,
    "strictMetadataEmit": true,
    "skipTemplateCodegen": true,
    "flatModuleOutFile": "amedia.js",
    "flatModuleId": "amedia"
  },
  "files": [
    "./index.ts"
  ]
}
```
After this task, an output file gets it's original import renamed which crashes consumer project:
```js
// Originally is in index.ts file
import { UIRouterModule } from '@uirouter/angular';

// Compiled to index.js file
import { UIRouterModule } from '@uirouter/angular/index';
```
This causes consumer project to crash with error `can not resolve module '@uirouter/angular/index'`.
If I remove added `/index` part from a result file manually, everything works perfectly - as expected.

## Expected behavior
The import path should not be modified.

## Minimal reproduction of the problem with instructions

1. Generate project using Yeoman generator: https://github.com/jvandemo/generator-angular2-library
for minimizing effort for reproduction environment initialization.
2. `$ npm install --save-dev @angular/router @uirouter/angular`
3. Add `import { UIRouterModule } from '@uirouter/angular';` into `index.ts` module file.
4. Run following commands (which are basically build steps in order of appearance):
```bash
$ gulp clean:dist
$ gulp copy:source // will clone /src folder into /.tpm
$ gulp inline-resources // Inline template (.html) and style (.css) files into the the component .ts files
$ gulp ngc // Run the Angular compiler, ngc, on the /.tmp folder and output all compiled modules into /build folder
```
5. Check `/build/index.js`, which already has it's `@uirouter/angular` path changed to `@uirouter/angular/index`

## What is the motivation / use case for changing the behavior?

Ability to extract modules and even whole website pages into external NPM packages.

## Environment

<pre><code>
Angular version: 4.4.3
 
For Tooling issues:
- Node version: 6.10.0
- Platform: Mac

</code></pre>

**Comment by Toxicable** [comment] 2017-09-22 08:13
Duplicate of #19026
Would you be able to make a minimal reproduction in a repository I can clone?

**Comment by Kamilius** [comment] 2017-09-22 08:40
@Toxicable please check issue description again. I've just added a Reproduction steps.

**Comment by Toxicable** [comment] 2017-09-22 20:21
This one can be closed since we already have an issue tracking it

**Closed** 2017-09-23 04:44 UTC
Labels: comp: core & compiler
