### ISSUE TITLE
Angular Router - An index signature parameter type must be either 'string' or 'number'

### ISSUE THREAD

**Issue by parksmart-dev** [angular/angular#45355] opened 2022-03-15 18:22 UTC
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

No

### Description

Trying to build/serve the app gives a typescript validation error.

### Please provide a link to a minimal reproduction of the bug

NA

### Please provide the exception or error you saw

```true
[ng] Error: node_modules/@angular/router/router.d.ts:1626:6 - error TS1023: An index signature parameter type must be either 'string' or 'number'.
[ng] 
[ng] 1626     [key: string | symbol]: any;
[ng]           ~~~
[ng] 
[ng] 
[ng] 
[ng] ✖ Failed to compile.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
ng version                                   

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 13.2.6
Node: 16.13.0
Package Manager: npm 8.1.0
OS: darwin x64

Angular: 13.2.6
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1302.6
@angular-devkit/build-angular   13.2.6
@angular-devkit/core            13.2.6
@angular-devkit/schematics      13.2.6
@schematics/angular             13.2.6
rxjs                            7.5.5
typescript                      4.5.5
```

### Anything else?

Had to downgrade to Angular 13.1.2 to build but would ideally like to know how to use latest version of Angular.

**Comment by JoostK** [comment] 2022-03-15 18:40
This is really a duplicate of #44844. Does https://github.com/angular/angular/issues/44844#issuecomment-1026150876 help? What's the output of `rpm ls typescript`? Without a repro we are unlikely to be able to help.

**Comment by JoostK** [comment] 2022-03-15 18:46
This is very likely your issue:

```
├─┬ @ionic/angular-toolkit@5.0.3
│ └─┬ @angular-devkit/build-angular@12.2.16
│   ├─┬ @angular-devkit/build-optimizer@0.1202.16
│   │ └── typescript@4.3.5
│   ├─┬ @angular/compiler-cli@12.2.16
│   │ └── typescript@4.3.5 deduped
│   ├─┬ @ngtools/webpack@12.2.16
│   │ └── typescript@4.3.5 deduped
│   └── typescript@4.3.5
```

**Comment by parksmart-dev** [comment] 2022-03-15 18:49
ahh, you're a star, I see there's an update.

**Comment by atscott** [comment] 2022-03-15 20:42
Closing (https://github.com/angular/angular/issues/45355#issuecomment-1068339294)

**Closed** 2022-03-15 20:42 UTC
