### ISSUE TITLE
Lifecycle hooks change should appear on breaking changes

### ISSUE THREAD

**Issue by Foxandxss** [angular/angular#5551] opened 2015-12-02 16:33 UTC
So having to use `ngOnIinit`, `ngOnChange` etc etc is a required changed so I think it should appear on breaking changes.

Cheers.

**Comment by pkozlowski-opensource** [comment] 2015-12-02 16:35
Duplicate of https://github.com/angular/angular/pull/5545

**Closed by pkozlowski-opensource** 2015-12-02 16:35 UTC

**Comment by Foxandxss** [comment] 2015-12-02 16:39
Oh, looked into issues but not prs
