### ISSUE TITLE
i18nSelect Pipe not exporting keys to messages.xlf on ng xi18n

### ISSUE THREAD

**Issue by ChazUK** [angular/angular#22802] opened 2018-03-15 16:09 UTC
## I'm submitting a...
<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question</code></pre>

## Current behavior
Using the i18nSelect pipe doesn't populate the XLF file with any keys or references to the template.

`app.component.ts`
```
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  template: `<div><span i18n>Status:</span> {{ status | i18nSelect: statusMap }}</div>`
})
export class AppComponent {
  status: string = 'SHIPPED';
  statusMap: any = {
    'OPEN': 'Open',
    'CLOSED': 'Closed',
    'SHIPPED': 'Shipped'
  };
}
```

run `ng xi18n` and check the exported XLF file.

`messages.xlf`
```
<?xml version="1.0" encoding="UTF-8" ?>
<xliff version="1.2" xmlns="urn:oasis:names:tc:xliff:document:1.2">
  <file source-language="en" datatype="plaintext" original="ng2.template">
    <body>
      <trans-unit id="4dc1eb8327e6fcbe9cf10f611d18ccab26ac12cf" datatype="html">
        <source>Status :</source>
        <context-group purpose="location">
          <context context-type="sourcefile">app/app.component.ts</context>
          <context context-type="linenumber">1</context>
        </context-group>
      </trans-unit>
    </body>
  </file>
</xliff>
```

## Expected behavior
Expect the exported XLF file to display source for all entries in the `statusMap` object

`messages.xlf`
```
<?xml version="1.0" encoding="UTF-8" ?>
<xliff version="1.2" xmlns="urn:oasis:names:tc:xliff:document:1.2">
  <file source-language="en" datatype="plaintext" original="ng2.template">
    <body>
      <trans-unit id="4dc1eb8327e6fcbe9cf10f611d18ccab26ac12cf" datatype="html">
        <source>Status :</source>
        <context-group purpose="location">
          <context context-type="sourcefile">app/app.component.ts</context>
          <context context-type="linenumber">1</context>
        </context-group>
      </trans-unit>
      <trans-unit id="" datatype="html">
        <source>OPEN</source>
        ...
      </trans-unit>
      <trans-unit id="" datatype="html">
        <source>CLOSED</source>
        ...
      </trans-unit>
      <trans-unit id="" datatype="html">
        <source>SHIPPED</source>
        ...
      </trans-unit>
    </body>
  </file>
</xliff>
```

## Minimal reproduction of the problem with instructions
Run `ng xi18n` on the following project https://stackblitz.com/edit/angular-gitter-bn8byx

## What is the motivation / use case for changing the behavior?
Being able to translate key/value pairs that may come from external sources such as an API.

## Environment

<pre><code>Angular version: 5.2.9

Browser:
- [all]
 
For Tooling issues:
- Node version: v8.9.3
- Platform: Mac</code></pre>

**Comment by ChazUK** [comment] 2018-03-15 16:10
It'd be great to get @ocombe's guidance on this.

**Comment by ocombe** [comment] 2018-03-15 16:15
hello, it's not possible right now, but you can use the select ICU if all your keys are static, and this will be extracted: https://angular.io/guide/i18n#select-among-alternative-text-messages

however with v6 we'll introduce runtime i18n for the ivy compiler, and it should be able to extract those kind of data, I'll put it on our todo list to make sure that it's a use case that we support

**Comment by ChazUK** [comment] 2018-03-15 16:36
Thanks for the blazing response @ocombe, can I ask why this pipe is currently in the code, and what it's intended use is for?

**Comment by ocombe** [comment] 2018-03-15 16:38
I'm not sure, it's a bit of a duplicate of the ICU expressions, but it can be used in a service I guess

**Comment by vicb** [comment] 2018-03-15 18:04
closing as work as intended

**Closed by vicb** 2018-03-15 18:04 UTC

**Comment by ChazUK** [comment] 2018-03-15 18:08
@vicb Is it possible to remove it from the I18nSelectPipe from the core? As it isn't functional
