### ISSUE TITLE
`NG8102` should not trigger when left-side is `any`

### ISSUE THREAD

**Issue by NateRadebaugh** [angular/angular#44898] opened 2022-01-30 14:26 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

No, it's from a new feature. When NG8102 was added, it didn't quite work as expected.
* https://angular.io/extended-diagnostics/NG8102

### Description

NG8102 should not trigger when left-side is `any`

## 🔬 Minimal Reproduction

Simple repro repo from a new angular 13.2.0 CLI: https://github.com/NateRadebaugh/nullishCoalescingNotNullable

In particular, the following commit introduces code that will trigger NG8102 but since `any` could be null or undefined, it should not trigger.
* https://github.com/NateRadebaugh/nullishCoalescingNotNullable/commit/95f290eaf526b28d544e3888c835392d6f0053c2

Ex:
```ts
title: any = 'my-app';
```
```html
<span>{{ title ?? 'default title' }} app is running!</span>
```

## 🔥 Exception or Error

```
Warning: src/app/app.component.html:344:14 - warning NG8102: The left side of this nullish coalescing operation does not include 'null' or 'undefined' in its type, therefore the '??' operator can be safely removed.
```

## 🌍 Your Environment

```
Angular CLI: 13.2.0
Node: 14.18.3
Package Manager: npm 6.14.15
OS: darwin x64

Angular: 13.2.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1302.0
@angular-devkit/build-angular   13.2.0
@angular-devkit/core            13.2.0
@angular-devkit/schematics      13.2.0
@schematics/angular             13.2.0
rxjs                            7.5.2
typescript                      4.5.5
```

### Anything else relevant?

I've temporarily disabled this extended diagnostic via the following config as documented:
> https://angular.io/extended-diagnostics/NG8102#what-if-i-cant-avoid-this

```json
{
  "angularCompilerOptions": {
    "extendedDiagnostics": {
      "checks": {
        "nullishCoalescingNotNullable": "suppress"
      }
    }
  }
}
```

**Comment by JoostK** [comment] 2022-01-30 15:56
Duplicate of #44859.

**Closed by JoostK** 2022-01-30 15:56 UTC
Labels: comp: compiler
