### ISSUE TITLE
Angular.dev page not found, on /roadmap -> "Try out inject"

### ISSUE THREAD

**Issue by sdev95** [angular/angular#52723] opened 2023-11-09 08:38 UTC
### Describe the problem that you experienced

I wanted to check out the "Explore modern Angular section" and click on production ready features.
When I reached [Try out Inject](https://angular.dev/di), the link shows a page not found.

### Enter the URL of the topic with the problem

https://angular.dev/roadmap

### Describe what you were looking for in the documentation

I wanted to check out the "Explore modern Angular section" and click on production ready features.
When I reached [Try out Inject](https://angular.dev/di), the link shows a page not found.

### Describe the actions that led you to experience the problem

1. From the main page, click on "reference"
2. Click on "Roadmap"
3. Go to the section "Explore modern Angular" 
4. Click on "Try out Inject"

### Describe what you want to experience that would fix the problem

I would like to see the correct page with content instead of a 404.

**Comment by JoostK** [comment] 2023-11-09 09:06
Thanks for the report! This is a duplicate of #52539

**Closed by JoostK** 2023-11-09 09:06 UTC
