### ISSUE TITLE
Angular throws "Unable to parse ICU expression" error for valid ICU expression

### ISSUE THREAD

**Issue by pjcdev** [angular/angular#49648] opened 2023-03-30 13:05 UTC
### Which @angular/* package(s) are the source of the bug?

localize

### Is this a regression?

No

### Description

I have following translation in en.xlf file:

```
      <trans-unit id="something">
        <source xml:lang="en">whatever</source>
        <target xml:lang="en">{x,plural,=1{one}other{two}}</target>
      </trans-unit>
```

and code in one components:

```
<ng-template #something i18n="@@something">test {x}</ng-template>
```

And it always throws an error `Unable to parse ICU expression...`

If I don't use `plural` but put whatever there it works. Works also with interpolation but never with plural

### Please provide the exception or error you saw

```true
Unable to parse ICU expression in ... message
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.3.10
Node: 14.16.1
Package Manager: npm 6.14.12
OS: darwin x64

Angular: 13.3.12
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, platform-server, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1303.9
@angular-devkit/build-angular   13.3.9
@angular-devkit/core            13.3.10
@angular-devkit/schematics      13.3.10
@angular/cdk                    13.3.9
@angular/cli                    13.3.10
@angular/material               13.3.9
@schematics/angular             13.3.10
rxjs                            7.8.0
typescript                      4.6.2
```

### Anything else?

Worked fine in Angular 8 with same notation

**Comment by JoostK** [comment] 2023-03-30 13:43
This is likely a duplicate of #48217; ICU expressions should occur in the source text, _not_ in the translation. Please see https://github.com/angular/angular/issues/48217#issuecomment-1405940237

**Comment by pjcdev** [comment] 2023-03-30 14:03
Hey, looks like the same issue but somehow example where ICU is in translation is in official angular docs: https://v13.angular.io/guide/i18n-example

**Comment by JoostK** [comment] 2023-03-30 14:06
The docs are different though:

```
        <source>{VAR_PLURAL, plural, =0 {just now} =1 {one minute ago} other {<x id="INTERPOLATION" equiv-text="{{minutes}}"/> minutes ago by {VAR_SELECT, select, male {male} female {female} other {other} }} }</source>
```

That is the compiled represenation of ICUs, as compiled from the template source.

**Comment by AndrewKushnir** [comment] 2023-03-30 17:10
Closing as a duplicate of https://github.com/angular/angular/issues/48217.

**Closed by AndrewKushnir** 2023-03-30 17:10 UTC
