### ISSUE TITLE
Bootstrap Atleast One Component Before Injecting Router !!

### ISSUE THREAD

**Issue by ersandeepranjit** [angular/angular#11660] opened 2016-09-16 08:45 UTC
**I'm submitting a bug report**

**Current behavior** 
I am using Angular 2 for only the admin section and login section of my application. so I bootstrap my application for "/login" and "/admin/**" route. So inorder to protect the admin router I used AUTH Guard Service as explained in Routing and Navigation Doc of Angular 2. It was working till the RC 4 but since RC5 it is giving the Issue. It suggest to bootstrap atleast One Component but there is no other component than Login and Admin 

* **Angular version:** 2.0.0-RC-5 to 2.0.0
*  I have posted the issue in StackOverflow and Gitter but didn't the any solution as it is said to be the known bug 

```zone.js:344 Unhandled Promise rejection: Bootstrap at least one component before injecting Router. ; Zone: <root> ; Task: Promise.then ; Value: Error: Bootstrap at least one component before injecting Router.(…) Error: Bootstrap at least one component before injecting Router.
    at setupRouter (http://localhost:3000/scripts/@angular/router//bundles/router.umd.min.js:13:18707)
    at NgModuleInjector.get (AppModule.ngfactory.js:372:57)
    at NgModuleInjector.get (AppModule.ngfactory.js:377:118)
    at NgModuleInjector.get (AppModule.ngfactory.js:502:99)
    at NgModuleInjector.AppModuleInjector.createInternal (AppModule.ngfactory.js:561:64)
    at NgModuleInjector.create (http://localhost:3000/scripts/@angular/core//bundles/core.umd.min.js:30:1140)
    at NgModuleFactory.create (http://localhost:3000/scripts/@angular/core//bundles/core.umd.min.js:30:673)
    at eval (http://localhost:3000/scripts/@angular/core//bundles/core.umd.min.js:29:25106)
    at ZoneDelegate.invoke (http://localhost:3000/scripts/zone.js/dist/zone.js:192:28)
    at Object.onInvoke (http://localhost:3000/scripts/@angular/core//bundles/core.umd.min.js:29:16609)consoleError @ zone.js:344_loop_1 @ zone.js:371drainMicroTaskQueue @ zone.js:375ZoneTask.invoke @ zone.js:297
zone.js:346 Error: Uncaught (in promise): Error: Bootstrap at least one component before injecting Router.(…)consoleError @ zone.js:346_loop_1 @ zone.js:371drainMicroTaskQueue @ zone.js:375ZoneTask.invoke @ zone.js:297```

**Comment by DzmitryShylovich** [comment] 2016-09-16 11:02
Duplicate of https://github.com/angular/angular/issues/10770

**Closed** 2016-09-16 20:16 UTC
Labels: comp: router

**Comment by ersandeepranjit** [comment] 2016-09-26 08:19
Didn't got the solution  yet !!!!
