### ISSUE TITLE
ERROR in TypeError: Cannot read property 'flags' of undefined

### ISSUE THREAD

**Issue by monish07122001** [angular/angular#37006] opened 2020-05-08 13:55 UTC
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

ERROR in TypeError: Cannot read property 'flags' of undefined
    at resolveAlias (D:\Programing\Angular\first-app\node_modules\typescript\lib\typescript.js:36513:37)
    at checkAliasSymbol (D:\Programing\Angular\first-app\node_modules\typescript\lib\typescript.js:64502:26)
    at checkImportBinding (D:\Programing\Angular\first-app\node_modules\typescript\lib\typescript.js:64534:13)
    at checkImportDeclaration (D:\Programing\Angular\first-app\node_modules\typescript\lib\typescript.js:64552:29)
    at checkSourceElementWorker (D:\Programing\Angular\first-app\node_modules\typescript\lib\typescript.js:64961:28)
    at checkSourceElement (D:\Programing\Angular\first-app\node_modules\typescript\lib\typescript.js:64800:17)
    at Object.forEach (D:\Programing\Angular\first-app\node_modules\typescript\lib\typescript.js:317:30)
    at checkSourceFileWorker (D:\Programing\Angular\first-app\node_modules\typescript\lib\typescript.js:65123:20)
    at checkSourceFile (D:\Programing\Angular\first-app\node_modules\typescript\lib\typescript.js:65091:13)
    at getDiagnosticsWorker (D:\Programing\Angular\first-app\node_modules\typescript\lib\typescript.js:65179:17)
    at Object.getDiagnostics (D:\Programing\Angular\first-app\node_modules\typescript\lib\typescript.js:65165:24)
    at D:\Programing\Angular\first-app\node_modules\typescript\lib\typescript.js:98703:85
    at runWithCancellationToken (D:\Programing\Angular\first-app\node_modules\typescript\lib\typescript.js:98665:24)
    at getBindAndCheckDiagnosticsForFileNoCache (D:\Programing\Angular\first-app\node_modules\typescript\lib\typescript.js:98691:20)
    at getAndCacheDiagnostics (D:\Programing\Angular\first-app\node_modules\typescript\lib\typescript.js:98956:26)
    at getBindAndCheckDiagnosticsForFile (D:\Programing\Angular\first-app\node_modules\typescript\lib\typescript.js:98688:20)

** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **

screenshot:
[https://drive.google.com/file/d/1-3PNAYowbk88jGqxT-4b-yPnT8X_iLYG/view?usp=sharing](url)

Thank you!
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by petebacondarwin** [comment] 2020-05-08 13:57
Duplicate of #36993

**Closed by petebacondarwin** 2020-05-08 13:57 UTC
