### ISSUE TITLE
Angular Service worker not sending 'body' in POST request sometimes

### ISSUE THREAD

**Issue by blackblood19** [angular/angular#27822] opened 2018-12-24 09:27 UTC
# 🐞 bug report
Angular Service worker is not sending 'body' in POST request sometimes. It works almost all the time, but, once in a while, I see that the POST request is sent with no body. When this happens, it continues to not send the body even after refreshing and disabling the cache. To resolve the issue, I open Application tab in dev tools, and stop and start the service worker, and it starts working, it starts sending 'body' for POST request.

### Affected Package
"@angular/service-worker": "^6.1.0"

## 🔬 Minimal Reproduction
I am unable to reproduce the issue whenever I want.

## 🌍  Your Environment
"@angular/core": "^6.1.0",
"@angular/service-worker": "^6.1.0"

**Comment by gkalpak** [comment] 2018-12-27 16:54
I'm afraid there is not much we can do without a reproduction. Angular's SW doesn't do anything special with request bodies afaict.
This could very well be a browser bug.

Closing, since there is not enough info for us to act on this, but feel free to continue the discussion below.

**Closed by gkalpak** 2018-12-27 16:54 UTC
Labels: comp: service-worker

**Comment by blackblood19** [comment] 2019-03-30 15:14
@gkalpak This issue is still happening to me. I made a simple reproduction, but as I mentioned earlier, it is not reproducible everytime. So, please take some time for me and follow the steps below. 

I observed that the problem happens when sending a file (not sure if it happens with any request.'body')

Open https://reproduction.stackbox.xyz/ and select any file. If the backend receives file, browser will display that. If backend does not receive the file, it will display that and this is what we are trying to achieve. The backend just checks if the file has come and throws if the file is not received.

**Reproduction Steps:**

- Open the above link, upload any file, you will most probably see that "File was sent successfully". 
- Close the tab. 
- Now comes the tricky part, Open the link again after an hour, and try uploading a file again. The issue will most probably happen. (If the issue happens, open the network tab and try uploading a file again, and the issue will happen again. We can see that the request sent by service worker has no body/file. Now, restart the service worker in Application tab, and the issue disappears.)

Please test this case for me. And please confirm if you have faced the issue.

**Comment by gkalpak** [comment] 2019-04-01 12:28
I saw you opened a new issue, @blackblood19: #29629 
I'll answer there.
