### ISSUE TITLE
Borken Link

### ISSUE THREAD

**Issue by Usman024** [angular/angular#53217] opened 2023-11-28 06:08 UTC
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

No

### Description

![borken link](https://github.com/angular/angular/assets/101615944/038e0218-c0cd-4578-aaa5-8c930ffd2c84)
There's a link on the page https://angular.dev/tools/cli/setup-local. I have attached a screenshot for that link: See [Angular's version compatibility](https://angular.dev/versions) guide for more information. when I open this link it is broken.

### Please provide a link to a minimal reproduction of the bug

https://angular.dev/versions

**Comment by JoostK** [comment] 2023-11-28 06:10
Thanks for the report, this is a duplicate of #52562 and has since been addressed, but is pending a deployment.

**Closed by JoostK** 2023-11-28 06:10 UTC
