### ISSUE TITLE
when the content children are the component same as the parent, use `ContentChildren` and get the children which contain the parent component

### ISSUE THREAD

**Issue by hpyou** [angular/angular#21148] opened 2017-12-22 03:20 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Happened when the content children are the component same as the parent.
In the demo the content children are two layoutComponent 
![image](https://user-images.githubusercontent.com/15992591/34283597-9bd21e78-e707-11e7-9d4e-bc82cbf433c3.png)
when use `@ContentChildren(LayoutComponent)`, and in `ngAfterContentInit` i get three children which one is the parent component
![image](https://user-images.githubusercontent.com/15992591/34283591-8cad0dfe-e707-11e7-9387-23c6fc400c2e.png)

## Minimal reproduction of the problem with instructions

http://plnkr.co/edit/bK6y3wDNkHYhzOsTl0IL?p=preview
## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [x] Chrome (desktop) version 63.0.3239.84
 
For Tooling issues:
- Node version: 8.9.3  
- Platform:  Windows 7

Others:

@angular/animations | 5.1.1 |  
@angular/cli | 1.6.1 |  
@angular/common | 5.1.1 |  
@angular/compiler | 5.1.1 | 
@angular/compiler-cli | 5.1.1 |  
@angular/core | 5.1.1 |  
@angular/forms | 5.1.1 |  
@angular/language-service | 5.1.1 |  
@angular/platform-browser | 5.1.1 |  
@angular/platform-browser-dynamic | 5.1.1 |  
@angular/router | 5.1.1 |  

</code></pre>

**Comment by pkozlowski-opensource** [comment] 2017-12-22 11:20
This is a duplicate of #10098

Yes, this is a bug and we should fix it.

**Closed by pkozlowski-opensource** 2017-12-22 11:20 UTC
