### ISSUE TITLE
docs(aio) Configuring Webpack section has older angular version in package.json

### ISSUE THREAD

**Issue by aravindfz** [angular/angular#20198] opened 2017-11-05 11:08 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Navigate to **[Webpack Configuration Section](https://angular.io/guide/webpack#configuring-webpack)**
![image](https://user-images.githubusercontent.com/22231525/32414189-a60a9b52-c247-11e7-9351-3ceb46385d88.png)

## Expected behavior

package.json should have the updated versions of dependencies

## What is the motivation / use case for changing the behavior?

Doc support

## Environment

<pre><code>
Angular version: 5.0.0

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by gkalpak** [comment] 2017-11-06 08:21
Closing as duplicate of #20141.

**Closed by gkalpak** 2017-11-06 08:21 UTC
