### ISSUE TITLE
Routing doesn't destroy components properly 

### ISSUE THREAD

**Issue by SebastianSchenk** [angular/angular#17261] opened 2017-06-06 17:38 UTC
**I'm submitting a ...** (check one with "x")

```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When navigating between components they don't get destroyed properly. A reference of the navigated component and its children is still in memory.

**Expected behavior**

The components shouldn't be in memory after they where destroyed. 

**Minimal reproduction of the problem with instructions**

[?p=preview http://plnkr.co/edit/KF49IB82ffvRFXVdYtyx?p=preview](http://plnkr.co/edit/KF49IB82ffvRFXVdYtyx)

1. Open plunker
1. Click "Launch the preview in a separate window"
1. Click "Page2" button
1. Open Devtools
1. Go to Memory Tab
1. Take Heap Snapshot 
1. Search for My

--> Now you can see that there are still references to MyPage1, MyPage2 and two MyChild.

**Please tell us about your environment:**

* **Angular version:** 4.1.3

* **Browser:** all

* **Language:** TypeScript 2.2.1

**Comment by jasonaden** [comment] 2017-06-27 22:57
@SebastianSchenk Thanks for this issue. However, looking at the plunker it appears this is just the first time you're instantiating the component. There doesn't appear to be a long-term leak here. If I continue going to page 2 and back to page 1 and run garbage collection, we don't have anything retained.

**Comment by SebastianSchenk** [comment] 2017-06-28 10:26
@jasonaden That's true. However, this is still not expected behaviour. Once a component gets removed from DOM, it should also be removed from memory. Having a big enterprise application with many components will still blow up the memory eventually. 

It would only make sense to keep the components in memory if they are reused, but this only happens then the current and the future route are the same [(https://medium.com/@juliapassynkova/angular-2-component-reuse-strategy-9f3ddfab23f5)](https://medium.com/@juliapassynkova/angular-2-component-reuse-strategy-9f3ddfab23f5)

I don't think this issue can just be closed. This is still a bug.

**Comment by jasonaden** [comment] 2017-06-29 16:18
@SebastianSchenk Okay, thanks for the clarification. I'll re-open and take a closer look.

**Comment by a-zen** [comment] 2017-10-10 08:59
@jasonaden did you have a chance to take a closer look already?

**Comment by jasonaden** [comment] 2017-12-08 18:56
This appears to be a duplicate of #13725. Closing this issue as it's tracked there.

**Closed by jasonaden** 2017-12-08 18:56 UTC
Labels: comp: router

**Comment by Goldflow** [comment] 2018-07-13 22:51
@jasonaden hi Jason the only contributor responding in #13725 is not active anymore on github since this year
is there anyone else looking in to this & more importantly, is there a recommended work around for this?
 thank you for taking the time in responding to this! :)

**Comment by tskweres** [comment] 2019-08-28 21:27
+1
