### ISSUE TITLE
ngAttribute to access property of encapsulated elements

### ISSUE THREAD

**Issue by victor-assis** [angular/angular#46991] opened 2022-07-28 23:38 UTC
### Which @angular/* package(s) are relevant/related to the feature request?

common

### Description

To create some components we often need to encapsulate them in a custom tag, to access their properties we need to create inputs and rewrite some apis, for example the input checkbox, theoretically we rewrite the focus and blur methods when creating custom components

### Proposed solution

A new directive that receives the properties and pass them to the html element, as it is done in the directive/component decorator with host, I created an example in [stackblitz](https://stackblitz.com/edit/angular-ivy-mvhptb?file=src%2Fapp%2Fdirectives%2Fng_attribute.ts), if it makes sense, I would like to find a solution for the typing

stackblitz: https://stackblitz.com/edit/angular-ivy-mvhptb?file=src%2Fapp%2Fdirectives%2Fng_attribute.ts

implementation example

```
// component usage
<app-checkbox
  [inputAttributes]="{
    checked: true,
    'aria-label': 'exemple',
    focus: test
  }"
>
  Exemple
</app-checkbox>

// components
<label class="checkbox">
  <input
    class="checkbox__input"
    type="checkbox"
    [ngAttribute]="inputAttributes"
  />
  <ng-content></ng-content>
</label>
```

### Alternatives considered

Maybe inheritance from native elements

**Comment by pkozlowski-opensource** [comment] 2022-08-01 09:21
This is really a duplicate of #14545 - the proposed _solution_ idea is different but the _problem_ is the same. I'm going to close this is a duplicate of #14545 to centralize the discussion in one place.

Feel free to add your solution idea in #14545.

Duplicate of #14545

**Closed by pkozlowski-opensource** 2022-08-01 09:21 UTC
