### ISSUE TITLE
NG11 DI for JIT compiled components at runtime fails

### ISSUE THREAD

**Issue by Revivius** [angular/angular#41933] opened 2021-05-03 22:57 UTC
# 🐞 bug report

### Affected Package

The issue is caused by package @angular/core and/or @angular/compiler

### Is this a regression?

Yes, the previous version in which this bug was not present was: 9 (based on this: https://github.com/angular/angular/issues/35908)

### Description

Importing @angular/compiler in main.ts before bootstrapping and compiling components at runtime works but injection to this compiled component fails.

## 🔬 Minimal Reproduction

Please see the sample at:  https://stackblitz.com/edit/angular-ivy-b2vgzx?file=src/app/renderer.component.ts

1. Without constructor (renderer.component.ts line 27 commented) and hence no DI; click 'Compile': everything works
2. Uncomment the constructor in renderer.component.ts line 27; click 'Compile': error is thrown 

## 🔥 Exception or Error
<pre><code>
ERROR
Error: Uncaught (in promise): Error: This constructor is not compatible with Angular Dependency Injection because its dependency at index 0 of the parameter list is invalid.
This can happen if the dependency type is a primitive like a string or if an ancestor of this class is missing an Angular decorator.

Please check that 1) the type for the parameter at index 0 is correct and 2) the correct Angular decorators are defined for this class and its ancestors.
Error: This constructor is not compatible with Angular Dependency Injection because its dependency at index 0 of the parameter list is invalid.
This can happen if the dependency type is a primitive like a string or if an ancestor of this class is missing an Angular decorator.

Please check that 1) the type for the parameter at index 0 is correct and 2) the correct Angular decorators are defined for this class and its ancestors.

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 11.2.10
Node: 14.16.0
OS: win32 x64

Angular: 11.2.11
... animations, common, compiler, compiler-cli, core, elements
... forms, platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.10
@angular-devkit/build-angular   0.1102.10
@angular-devkit/core            11.2.10
@angular-devkit/schematics      11.2.10
@angular/cli                    11.2.10
@schematics/angular             11.2.10
@schematics/update              0.1102.10
rxjs                            6.6.7
typescript                      4.1.5
</code></pre>

**Anything else relevant?**

I tried importing  'core-js/es/reflect' and import 'reflect-metadata' in polyfills.ts  suggested by @alxhub here for NG9 with no success: https://github.com/angular/angular/issues/35908

**Comment by petebacondarwin** [comment] 2021-05-04 07:55
The problem is that the Angular JIT compiler is not receiving any type metadata for the constructor parameters. The generated JS code looks like:

```ts
class DynamicComponent {
  constructor(s) {
    this.text = "Text";
  }
  handle() {
    this.text = "Event handler works!";
  }
}
```

There is no type information about the `s` parameter, so Angular is not able to generate appropriate DI instructions...

**Comment by petebacondarwin** [comment] 2021-05-04 08:10
I tried adding `emitDecoratorMetadata` to the StackBlitz, which should have added this type information, but it didn't see to work.

**Comment by petebacondarwin** [comment] 2021-05-04 08:25
You can work around this by adding the metadata yourself manually:

```ts
  (cmpClass as any).ctorParameters = () => [ {type: Service1 }];
```

See https://stackblitz.com/edit/angular-ivy-2ecjic?file=src/app/renderer.component.ts

**Comment by Revivius** [comment] 2021-05-04 22:19
thank you @petebacondarwin, adding ctorParameters manually works.

I think 'emitDecoratorMetadata' is not working because I am creating the component class at runtime where TS compilation was way before. Do I understand that correctly ?

**Comment by JoostK** [comment] 2021-05-05 08:00
> I think 'emitDecoratorMetadata' is not working because I am creating the component class at runtime where TS compilation was way before. Do I understand that correctly ?

Indeed, there is no decorator attached to `DynamicComponent` so even with `emitDecoratorMetadata` enabled there is no knowledge of the constructor parameter types at runtime. Manually setting the `ctorParameters` as Pete suggested works, and an alternative could be to introduce a dummy decorator to enable the generation of metadata:

https://stackblitz.com/edit/angular-ivy-ydmawy?file=src%2Fapp%2Frenderer.component.ts

```ts
export function Annotate() {
  return klass => klass;
}

// ...

  const cmpClass = (() => {
    @Annotate()
    class DynamicComponent {
      text: string = "Text";

      constructor(public s: Service1) {
        console.log(s);
      }

      handle() {
        this.text = "Event handler works!";
      }
    }
    return DynamicComponent;
  })();
```

**Comment by alxhub** [comment] 2021-05-05 15:07
Closing as this isn't actionable for the framework - JIT is working as intended here.

**Closed by alxhub** 2021-05-05 15:07 UTC
Labels: comp: compiler, comp: core, core: di
