### ISSUE TITLE
Reference to enclosing ViewContainerRef as a property in ViewRef

### ISSUE THREAD

**Issue by vinayluzrao** [angular/angular#32925] opened 2019-10-01 03:06 UTC
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/core

### Description

It would be useful for `ViewRef` to have a reference to the enclosing `ViewContainerRef` to which the `ViewRef` is (possibly) attached to. 

An example use case is moving dynamic components around between different `ViewContainerRef`s. Depending on the underlying data structure model of the components, it might be cumbersome to have to keep a reference to the enclosing `ViewContainerRef` on the application side.

### Describe the solution you'd like

```TypeScript
// assume the following vars were previously created and have the following types:
// dynamicallyCreatedComponent: ComponentRef
// newViewContainerRef: ViewContainerRef
const oldViewContainerRef = dynamicallyCreatedComponent.hostView.enclosingViewContainerRef // the feature request is for something similar to this "enclosingViewContainerRef" property
const indexInOldViewContainer = oldViewContainerRef.indexOf(dynamicallyCreatedComponent.hostView)
oldViewContainerRef.detach(indexInOldViewContainer) // necessary because components have to be detached before they can be reinserted.
newViewContainerRef.insert(dynamicallyCreatedComponent.hostView)
```

### Describe alternatives you've considered
 The current workaround is to keep a reference to the enclosing ViewContainerRef inside the component instance, and update it whenever it changes (i.e whenever the component is moved to another ViewContainerRef).

**Comment by pkozlowski-opensource** [comment] 2019-12-03 17:18
I don't think we want to expose a reference to a containing `ViewContinarRef` as a public API. The basic issue you are facing here is that there is a bug in the current implementation of Angular that is not properly detaching views (when those are moved between containers). This bug is already tracked in #20824 .

The good news is that this issue will be fixed in ivy via #34156

Closing as a duplicate of the above issue / PR.

**Closed by pkozlowski-opensource** 2019-12-03 17:18 UTC
Labels: comp: core, type: feature
