### ISSUE TITLE
Broken routerLink on recompile when used with Ivy

### ISSUE THREAD

**Issue by vajahath** [angular/angular#32388] opened 2019-08-29 07:48 UTC
# 🐞 bug report

```html
<a routerLink="hiya">link</a>
```
The `routerLink` breaks when application recompiles. On browser, this is shown as an anchor tag that is not clickable.

This works correctly when Ivy is turned off.

### Affected Package
I hope the issue may be related to @angular/router or may be Ivy

### Description

I put the `<a routerLink=".." ..` in a component inside a lazyloaded module. When we stop the server and `npm start` again, this works correctly. But again fails on the next compile-on-save.

I turned off the Ivy flag and everything works fine. So this may be related to Ivy.

## 🔬 Minimal Reproduction

I was following the [lazy-loading-ngmodules guide](https://angular.io/guide/lazy-loading-ngmodules).

A very minimal zip is attached here (without node_modules).
[broken-routerLink.zip](https://github.com/angular/angular/files/3554413/broken-routerLink.zip)

## 🔥 Exception or Error

No errors are shown.

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.3.1
Node: 10.16.2
OS: linux x64
Angular: 8.2.4
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.1
@angular-devkit/build-angular     0.803.1
@angular-devkit/build-optimizer   0.803.1
@angular-devkit/build-webpack     0.803.1
@angular-devkit/core              8.3.1
@angular-devkit/schematics        8.3.1
@angular/cli                      8.3.1
@ngtools/webpack                  8.3.1
@schematics/angular               8.3.1
@schematics/update                0.803.1
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2
</code></pre>

**Comment by Kaffesumpen** [comment] 2019-11-02 19:39
Not sure if it matters but I am having the same issue.

**Comment by mhevery** [comment] 2019-11-12 00:19
@alxhub I think this issue is for you.

The source code contains:

```javascript
@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    AppRoutingModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'broken-routerLink';
}
```

The key thing to notice is `templateUrl: './app.component.html'`. The resulting generated code is: 

```javascript
        AppComponent.ngComponentDef = _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵɵdefineComponent"]({
            type: AppComponent,
            selectors: [["app-root"]],
            factory: function AppComponent_Factory(t) {
                return new (t || AppComponent)();
            },
            consts: 2,
            vars: 0,
            template: function AppComponent_Template(rf, ctx) {
                if (rf & 1) {
                    _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵɵtext"](0, "My App\n");
                    _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵɵelement"](1, "router-outlet");
                }
            },
            styles: ["\n/*# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IiIsImZpbGUiOiJzcmMvYXBwL2FwcC5jb21wb25lbnQuc2NzcyJ9 */"]
        });
        /*@__PURE__*/
        _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵsetClassMetadata"](AppComponent, [{
            type: _angular_core__WEBPACK_IMPORTED_MODULE_0__["Component"],
            args: [{
                selector: 'app-root',
                templateUrl: './app.component.html',
                styleUrls: ['./app.component.scss']
            }]
        }], null, null);
```

The key thing to notice is that `defineComponent({ ... })` is missing `directives`

When I change input from `templateUrl: './app.component.html'` to `template: '<router-outlet></router-outlet>'` the generated output becomes correct and properly includes `directives: [_angular_router__WEBPACK_IMPORTED_MODULE_1__["RouterOutlet"]],`

So as far as I can tell the issue is that the compiler somehow gets confused with `templateUrl`.

**Comment by mhevery** [comment] 2019-11-12 18:25
@alxhub says this may be fixed by https://github.com/angular/angular/pull/33551 or https://github.com/angular/angular/pull/33522.

**Closed** 2019-11-20 19:46 UTC
Labels: comp: compiler, comp: ivy, freq1: low, severity2: inconvenient, severity5: ivy-compat, state: has PR, type: bug/fix
