### ISSUE TITLE
 Template reference is not pointing to htmlelement when a component or directive is applied

### ISSUE THREAD

**Issue by sheikalthaf** [angular/angular#45774] opened 2022-04-27 09:07 UTC
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

When its comes to template reference we can use export as to select which directive or component we are going to reference in template reference, But what if I have to target the host element itself. 

![image](https://user-images.githubusercontent.com/22526247/165482844-44c75a0e-c567-4011-803c-1c2a84e99839.png)

In above image itself you can see that I want to take href from anchor tag but template ref always targeting the component itself. It is possible to ref the anchor element in my example

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.2.0
Node: 16.13.0
Package Manager: yarn 1.22.17
OS: darwin arm64

Angular: 13.2.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, material, material-moment-adapter
... platform-browser, platform-browser-dynamic, pwa, router
... service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1302.0
@angular-devkit/build-angular   13.2.0
@angular-devkit/core            13.2.0
@angular-devkit/schematics      13.2.0
@angular/flex-layout            13.0.0-beta.37
@schematics/angular             13.2.0
rxjs                            7.4.0
typescript                      4.5.5
```

### Anything else?

Is there any way to point the root element with template ref?

**Comment by JoostK** [comment] 2022-04-27 09:16
AFAIK this is working as designed so it's not a bug, but I can see how there's a feature gap to select the native element instead of the component instance.

One possible approach that works today is to declare a `ViewChild` query with `{read: ElementRef}` predicate, and reference its `nativeElement` instead of the ref itself:

```ts
export class DemoCmp {
  @ViewChild('ref', { read: ElementRef }) elRef: ElementRef<HTMLAnchorElement>;
}
```

**Comment by sheikalthaf** [comment] 2022-04-27 09:30
> AFAIK this is working as designed so it's not a bug, but I can see how there's a feature gap to select the native element instead of the component instance.
> 
> One possible approach that works today is to declare a `ViewChild` query with `{read: ElementRef}` predicate, and reference its `nativeElement` instead of the ref itself:
> 
> ```ts
> export class DemoCmp {
>   @ViewChild('ref', { read: ElementRef }) elRef: ElementRef<HTMLAnchorElement>;
> }
> ```

@JoostK  I know this solution but In my case it is a lot of work because the element is in ngFor so i have to use `ViewChildren`. Also my need is simple I want to copy the anchor element href to clipboard (I'm using material cdk clipboard) so I have to give input to it. This is what I want to achieve

![image](https://user-images.githubusercontent.com/22526247/165487948-cb1651c6-1597-4c8d-91e6-6daa26440f32.png)

**Comment by pkozlowski-opensource** [comment] 2022-04-27 10:20
This is really a duplicate of #21089. This issue surfaces from time to time and shows a gap in the design of our templating syntax. This is definitively a valid issue and we should consider it when evolving our templating syntax.

Duplicate of #21089

**Closed by pkozlowski-opensource** 2022-04-27 10:20 UTC
Labels: comp: core, core: basic template syntax, core: local references
