### ISSUE TITLE
Allow non-ASCII characters in Template Expressions

### ISSUE THREAD

**Issue by lacolaco** [angular/angular#34003] opened 2019-11-23 03:29 UTC
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/compiler

### Description

Allowing any characters which are valid in ECMAScript specification.

#### Problem 

Currently, Angular's template parser doesn't allow non-ASCII characters in an expression part. For example, `我的` consists of chinese characters as below;

```ts
@Component({
  selector: 'my-app',
  template: '<div>{{ 我的 }} </div>',
})
export class AppComponent  {
  // Chinese character
  我的 = 'Angular';
}
```

It throws template parsing error like the below;

```
Template parse errors:
Parser Error: Unexpected token Lexer Error: Unexpected character [我] at column 2 in expression [ 我的 ] at column 3 in [{{ 我的 }}] in ng:///AppModule/AppComponent.html@0:5 ("<div>[ERROR ->]{{ 我的 }}</div>"): ng:///AppModule/AppComponent.html@0:5
```

https://stackblitz.com/edit/angular-nu81kk?file=src/app/app.component.ts

#### Causes

This is a problem at the scanning phase of the lexer.

https://github.com/angular/angular/blob/8c76e78ec454b0b9c2d1fadb6c3d1d1202772ea5/packages/compiler/src/expression_parser/lexer.ts#L160

This line tries to judge that the character is the start of an _idenfiter_. In the above context, an identifier is `我的`. 
But the scanner's `isIdentifierStart` method allows only characters like ASCII.

https://github.com/angular/angular/blob/8c76e78ec454b0b9c2d1fadb6c3d1d1202772ea5/packages/compiler/src/expression_parser/lexer.ts#L334-L337

As a result, `我` is not recognized the start of the identifier and at last, the scanner throws an unexpected token error.

#### Usecase

In the JavaScript context, `this.我的` is valid. Sometime non-English developers prefer using their own language in the code for readability.

### Describe the solution you'd like

To solve this, Angular has to change the code around finding identifiers.
For only expression scope, I guess it is not too difficult.

### Related issues

https://github.com/angular/angular/issues/517 

This is a very old issue. Some issues have been closed due to duplication to that, but we may need to reset the discussion about this problem.

cc/ @zackarychapple

**Comment by SanderElias** [comment] 2019-11-23 03:43
_This should be fixed!_. I feel that this is a bug in the Angular compiler

If somehow, it is for some reason impossible to have no-ascii code properties on controllers accessible in the template we should:
1. **document this**
2. make sure we properly explain why
3. have the compiler throw a warning when such a property is used in the controller.

**Comment by JounQin** [comment] 2019-11-23 05:17
Angular is always teaching developers what is the correct coding style.

This is highly unrecommended IMO.

**Comment by SanderElias** [comment] 2019-11-23 07:18
@JounQin Can you please elaborate on your opinion?
As it is valid (by spec) in JS and TS to use UTF-16 tokens as/in your variable names. In HTML All Unicode points are valid (even in attribute names). Also by spec. 
Can you explain to me why do you feel using those is not a "correct coding style"?

Perhaps I'm missing something obvious.

**Comment by pkozlowski-opensource** [comment] 2019-11-23 07:59
I believe that this is a duplicate of the existing issue #517 - we should centralise the discussion in one place.

**Comment by pkozlowski-opensource** [comment] 2019-11-23 12:06
> This is a very old issue. Some issues have been closed due to duplication to that, but we may need to reset the discussion about this problem.

@lacolaco the referenced issue is still open and I don't think that opening a new issue is helping to focus the discussion. I'm going to close this one as a duplicate of #517  - please add your use-case(s) / input in there. But also happy to re-open this one if you believe that it is _not_ a duplicate.

**Closed by pkozlowski-opensource** 2019-11-23 12:06 UTC
