### ISSUE TITLE
Server side rendering not serving link stylesheets in index.html or CSS

### ISSUE THREAD

**Issue by albanx** [angular/angular#50269] opened 2023-05-12 16:15 UTC
### Which @angular/* package(s) are the source of the bug?

platform-browser, platform-server, Don't known / other

### Is this a regression?

Yes

### Description

I have a project upgraded to angular 16, with SSR enabled and Angular material integrated.

The issue I have is that the Server Side rendering not load properly the CSS files, changing the media types from `this.media='all'` to `this.media='print'`

My index.html has this line of code:

```
<link rel="stylesheet" href="material.5c8ff7095e201185.css" media="print" onload="this.media='all'"><noscript><link rel="stylesheet" href="material.5c8ff7095e201185.css"></noscript><link rel="stylesheet" href="styles.f2a9e6ffd091c89e.css" media="print" onload="this.media='all'"><noscript><link rel="stylesheet" href="styles.f2a9e6ffd091c89e.css"></noscript></head>
```

When I run the server locally with `node .\server\main.js` (or on Lambda function), the `styles.f2a9e6ffd091c89e.css` is not served.
What I see in the return HTML is as following:
![image](https://github.com/angular/angular/assets/1130664/339bca16-9f5d-4f8a-a276-1ee03197da4e)

### Please provide a link to a minimal reproduction of the bug

https://test1.homezone.al/properties/sale

### Please provide the exception or error you saw

```true
Link styles are not loaded.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 16.0.0
Node: 18.15.0
Package Manager: npm 9.5.0
OS: win32 x64

Angular: 16.0.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, material, platform-browser, platform-browser-dynamic
... platform-server, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1600.0
@angular-devkit/build-angular   16.0.0
@angular-devkit/core            16.0.0
@angular-devkit/schematics      16.0.0
@nguniversal/builders           16.0.0
@nguniversal/express-engine     16.0.0
@schematics/angular             16.0.0
rxjs                            7.8.1
typescript                      5.0.4
```

### Anything else?

After some extensive debugging found out that the issue is related to change in this line of angular universal:
https://github.com/angular/universal/blob/main/modules/common/engine/src/engine.ts#L105

Opened a related issue in the package:
https://github.com/angular/universal/issues/3128

**Comment by albanx** [comment] 2023-05-12 23:35
Another issue I have notice so far is that the media of the link css stylesheet remains in print:
```
<link rel="stylesheet" href="styles.f2a9e6ffd091c89e.css" media="print" onload="this.media='print'">
```

**Comment by alan-agius4** [comment] 2023-05-13 05:59
Duplicate of https://github.com/angular/universal/issues/3128

**Closed by alan-agius4** 2023-05-13 05:59 UTC
