### ISSUE TITLE
input fields in sub-components are not included in form

### ISSUE THREAD

**Issue by advgal** [angular/angular#10037] opened 2016-07-13 10:33 UTC
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report

**Current behavior**

look at the plunkr:
http://plnkr.co/edit/hB34VjxP98uz1iAYS7Dw?p=preview

input Name is part of form, Name1, which is defined in a sub-component is not part of form

**Expected/desired behavior**

If I enter "abc" and "xyz", heroForm.form.value should be {name: "abc", name1: "xyz"}

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** [all] 
 
* **Language:** [ TypeScript X.X ]

**Comment by kara** [comment] 2016-07-13 18:51
This looks like a duplicate of https://github.com/angular/angular/issues/9600. Closing - please track the issue there.

**Closed by kara** 2016-07-13 18:51 UTC
Labels: comp: forms
