### ISSUE TITLE
Angular TestBed memory leak

### ISSUE THREAD

**Issue by GoGoris** [angular/angular#24048] opened 2018-05-22 15:20 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

When running Angular tests with Jest, the javascript heap keeps growing with each test untill the tests finish or an out of memory exception is thrown. The growing heap seems to be caused by the Angular TestBed, is it possible that this is the cause for the growing heapsize?

## Expected behavior

The javascript heap size stays more or less constant for the whole test suite.
No out of memory exceptions are thrown.

## Minimal reproduction of the problem with instructions

See the following bug report: facebook/jest#6147

## Environment

<pre><code>
Angular version: 6.0.1

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.11.1  
- Platform: Windows 

Others:

Jest 22.4.4 & 23.0.1
</code></pre>

**Comment by FreeleX** [comment] 2018-06-06 14:58
Hi, I have faced the same issue with Jest + Angular + Zone.js + JSDOM.
I use jest-preset-angular for test environment setup, which imports zone.js

Heap keeps growing due to zone.js and jsdom not playing well together

The workaround was to backup methods on prototypes of:
`XMLHttpRequestEventTarget`
`EventTarget`
`Event`
`HTMLCanvasElement`
(figured out by looking at zone.js sources)
before running test suite and restore them after (to untie zone.js patches from global object and make them available for garbage collection)

It seems like the workaround works due to the fact that JSDOM shares prototypes even between test suites' invocations, please take a look at https://github.com/jsdom/jsdom#shared-constructors-and-prototypes
And zone.js patches some methods on prototypes of mentioned above objects over and over without checking that they were already patched. 
As an example you may take a look at the case that HTMLCanvasElement.prototype.toBlob method is patched always on script load - https://github.com/angular/zone.js/blob/master/dist/zone.js#L2908
It calls original method, but after patching few times the call chain becomes smth like patched5 -> patched4() -> patched3() -> patched2() -> patched1() -> original() and it keeps growing.
So it seems like combined with closures it makes heap grow.

**Comment by JiaLiPassion** [comment] 2018-06-07 07:40
@GoGoris , I would like to look into this one, to reproduce, I just use the repo here, https://github.com/ngrx/platform, is that correct?

@FreeleX , could you also post a reproduce repo?

**Comment by FreeleX** [comment] 2018-06-09 19:32
@JiaLiPassion here it is https://github.com/FreeleX/jest-angular-memory-leak-example

**Comment by GoGoris** [comment] 2018-06-11 18:23
Yes I tested that repository to be sure that the error is not in my setup. I found that the problem is really easy to reproduce with any repository that has Angular + Jest if you run the tests using `--watchAll` and `--run-in-band` (see facebook/jest#6147).

**Comment by etavener** [comment] 2018-06-19 15:30
I would be very interested in a solution to this problem, or at least a temp fix. My tests take way too long to run at the moment.

**Comment by brianmcd** [comment] 2018-07-12 18:06
Applying @anjmao's fix from here fixed my memory leak issue: https://github.com/thymikee/jest-preset-angular/pull/135#issuecomment-384882416

**Comment by FreeleX** [comment] 2018-08-07 20:28
Hi guys, some time ago fix landed into zone.js master branch https://github.com/angular/zone.js/pull/1106
This should fix the issue mentioned here, please grab master and check it if possible. 
JFYI. Regards.

**Comment by MikeMatusz** [comment] 2018-09-06 16:47
@FreeleX I'm using Karma/Chrome, not Jest/JSDOM, but updating zone.js to 0.8.26 (which contains your PR) definitely helped a ton with memory.  We have over 3K tests running, and the memory held steady the whole time, which was not the case before (using v0.8.21). Thank you for your contribution!

**Comment by jfairley** [comment] 2018-09-06 21:44
@MikeMatusz That seems strange, because 0.8.26 was released in April.

https://github.com/angular/zone.js/releases/tag/v0.8.26

**Comment by MikeMatusz** [comment] 2018-09-07 12:06
Ah, you're right, apparently my mental date comparison algorithm is broken, thanks for correcting the record.  I guess the Karma/Chrome case must be difference, because updating to 0.8.26 was my only change and I definitely saw a huge improvement (from growing without bounds to staying with a range for the duration of the run), so hopefully that information will still be useful to a subset of users.

**Comment by AndrewKushnir** [comment] 2020-11-17 19:33
Hi, I'm closing this ticket based on the comments above (that zone.js v0.8.26 helped improve the situation). Feel free to create a new ticket if the problem still exists. Thank you.

**Closed by AndrewKushnir** 2020-11-17 19:33 UTC
Labels: P3, comp: testing, freq2: medium, memory leak, type: bug/fix
