### ISSUE TITLE
Directive `routerLink` dont correctly work with empty `fragment` option

### ISSUE THREAD

**Issue by Dok11** [angular/angular#29683] opened 2019-04-03 13:12 UTC
# 🐞 bug report

### Description

When `fragment` of `routerLink` are empty the anchor save `#` in `href`.
But expected will remove `#` character for use clean url.

So, for fix this issue I need use two diffrent temaplates of one link: with fragment and without.
I think this is not pretty decision.

And I think the solution located something here: https://github.com/angular/angular/blob/7.2.x/packages/router/src/url_tree.ts#L293

Now:
```ts
const fragment =
        typeof tree.fragment === `string` ? `#${encodeUriFragment(tree.fragment !)}` : '';
```

But it should be something like this:
```ts
const fragment = (typeof tree.fragment === `string` && tree.fragment)
    ? `#${encodeUriFragment(tree.fragment !)}` : '';
```

## 🔬 Minimal Reproduction
```ts
<!-- correct link with fragment -->
<a routerLink="/abc" fragment="myFragment">link 1 with fragment</a>

<!-- bug with empty fragment -->
<a routerLink="/def" fragment="">link 2 with blank fragment</a>
```

https://stackblitz.com/edit/angular-puzmfb?file=src%2Fapp%2Fapp.component.html

![image](https://user-images.githubusercontent.com/2697890/55480773-b0b7e380-5629-11e9-9b6d-dee24c9a2d7e.png)

**Comment by alan-agius4** [comment] 2019-04-03 13:21
Hi, this seems like a framework issue and such bugs should be logged here: https://github.com/angular/angular

Thanks.

**Comment by Dok11** [comment] 2019-04-03 13:29
@alan-agius4 I dont feel difference. You provide link to this same repo

**Comment by alan-agius4** [comment] 2019-04-03 13:36
Opps sorry @Dok11 my mistake. I got confused.

**Comment by jasonaden** [comment] 2019-04-03 22:49
Thanks for the issue. Looks valid. Would you be interested in creating a pull request to fix this?

[Developer docs](https://github.com/angular/angular/blob/master/docs/DEVELOPER.md) can be found here that explain how to set up your environment.

**Comment by lbassin** [comment] 2019-04-09 09:11
Is anyone doing a PR for this issue ? Otherwise i have some free time and can do it

**Comment by atscott** [comment] 2020-05-28 17:48
Closing this as working as intended. Empty string fragments are valid and act the same as writing `<a href="#">navigate to empty fragment</a>`. Additionally, `[fragment]="null"` works as I would expect by removing the fragment completely.

**Closed by atscott** 2020-05-28 17:48 UTC
Labels: comp: router, effort1: hours, freq2: medium, severity3: broken, state: needs more investigation, triage #1, type: bug/fix
