### ISSUE TITLE
Jasmine createSpyObj w/ properties: Properties lost when spy is provided to and retrieved from TestBed

### ISSUE THREAD

**Issue by daleclements** [angular/angular#33657] opened 2019-11-07 17:14 UTC
# 🐞 bug report
### Is this a regression?
No

### Description
Jasmine 3.5.0 added a new parameter to createSpyObj that allows you to specify properties in addition to methods (https://github.com/jasmine/jasmine/issues/1442), however if I create a spy object that way in a beforeEach() and provide it in TestBed.configureTestingModule, then get it with TestBed.get() in an "it" block, the mock function is there but the mock property is not.

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-issue-repro2-yayobe I tried to make a blitz with a repro but I have no idea how to make it actually run the test.

The important part is this:

```
describe('AppComponent', () => {
  beforeEach(() => {

    //Note the third parameter
    // @ts-ignore
    const someServiceSpy = jasmine.createSpyObj('SomeService', ['someFunction'], ['aProperty']);

    TestBed.configureTestingModule({
      declarations: [
        AppComponent
      ],
      providers: [
        {provide: SomeService, useValue: someServiceSpy},
      ]
    }).compileComponents();

  });

  it('should create the app', () => {
    //spyObj will have someFunction, but will not have aProperty
    let spyObj = TestBed.get(SomeService);
  });
```

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 7.3.9
Node: 10.15.0
OS: win32 x64
Angular: 7.2.15
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic
... platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.8.9
@angular-devkit/build-angular     0.8.9
@angular-devkit/build-optimizer   0.8.9
@angular-devkit/build-webpack     0.8.9
@angular-devkit/core              0.8.9
@angular-devkit/schematics        7.3.9
@angular/cdk                      7.3.7
@angular/cli                      7.3.9
@ngtools/webpack                  6.2.9
@schematics/angular               7.3.9
@schematics/update                0.13.9
rxjs                              6.5.3
typescript                        3.2.4
webpack                           4.16.4

</code></pre>

**Comment by JiaLiPassion** [comment] 2019-11-16 08:22
@daleclements, this is not a bug, it should be `undefined` you can check the `jasmine.createSpyObj` usage here, https://github.com/jasmine/jasmine/pull/1722/files#diff-f627290893ae16272e030bb1632e9c0dR178-R205

**Comment by JiaLiPassion** [comment] 2019-11-16 08:57
I accidentally clicked the `close and comment` button, please confirm and close this issue.

**Comment by vikerman** [comment] 2019-11-19 21:53
Closing this as part of triage. Please re-open if still an issue.

**Comment by daleclements** [comment] 2019-11-21 16:10
@JiaLiPassion The difference is that in the beforeEach (when the spyObj is created), the spy object has the property with a value of undefined, but in the it(), it doesn't have the property at all.

The bug is more obvious if you consider the second test of this feature from the link you provided ('creates an object with property names and return values if second object is passed') the value is not expected to be undefined because a value is provided. If I create a spy object with a property and value like this test in the beforeEach, and then get it from the TestBed in an it(), the property does not exist on the object:

```
describe('AppComponent', () => {
  beforeEach(() => {

    //Note the third parameter
    // @ts-ignore
    const someServiceSpy = jasmine.createSpyObj('SomeService', ['someFunction'], {prop1: 'foo'});
    //At this point, someServiceSpy has a property called prop1 with a value of 'foo'

    TestBed.configureTestingModule({
      declarations: [
        AppComponent
      ],
      providers: [
        {provide: SomeService, useValue: someServiceSpy},
      ]
    }).compileComponents();

  });

  it('should create the app', () => {
    //spyObj doesn't have prop1 at all. It should, right?
    let spyObj = TestBed.get(SomeService);
  });
```

**Comment by JiaLiPassion** [comment] 2019-11-22 13:19
@daleclements , ok, in your very first example, you are using
```
    const someServiceSpy = jasmine.createSpyObj('SomeService', ['someFunction'], ['aProperty']);

```

the `aProperty` dones't have a `value`, I will check your latest example.

**Comment by p0lar-bear** [comment] 2019-12-16 21:02
I am also experiencing this in the beforeEach block.

wearetestingthis.service.spec.ts:

    beforeEach(() => {
      const spyObj = jasmine.createSpyObj(
        'DependedOnService',
        [],
        { serviceData: of(testFixtures.testObject) }
      );
      console.log(spyObj.moduleData);

      TestBed.configureTestingModule({
        providers: [
          WeAreTestingThisService,
          { provide: DependedOnService, useValue: spyObj }
        ]
      });

      svc = TestBed.get(WeAreTestingThisService);
    });

wearetestingthis.service.ts: 

    export class WeAreTestingThisService {
      constructor(private dataSvc: DependedOnService) {
        this.dataSvc.serviceData.subscribe(() => void); //Not my actual code
      }
    }

Jasmine fails on the constructor because the `serviceData` property is undefined, but the console.log call shows the spy all set up. So it seems that the property is somehow just being lost through the TestBed.

**Comment by AlesDo** [comment] 2019-12-17 16:25
I suggest you step into the `createSpyObj` and see if you are actually calling the correct version of the method. 
I had the same issue and I discovered that karma-jasmine had its own node_modules folder with an older version of jasmine which does not have the functionality so the properties were never created at all.

**Comment by daleclements** [comment] 2019-12-17 16:42
@AlesDo We are seeing that the properties ARE created though, when we inspect the spyObj after it is created in beforeEach it has the properties we expect it to have. Only when we get it from the TestBed are they not there.

**Comment by pickfire** [comment] 2019-12-23 08:23
The property also seemed to lost even without using `jasmine.createSpyObj`.
```typescript
describe('hello', () => {
  let spy: jasmine.SpyObj<Hello>;

  beforeEach(() => {
    spy = { hello: 'fail' } as jasmine.SpyObj<Hello>;
    TestBed...
  });

  it('should have world', () => {
    spy.hello = 'world';
    expect(spy.hello).toEqual('world'); // this works
    // but the component does not see 'world'
  }
});
```
Maybe it is related?

**Comment by JiaLiPassion** [comment] 2020-01-02 05:21
@daleclements, I tested your code, but can not reproduce the issue, could you provide a reproduce repo?

**Comment by daleclements** [comment] 2020-01-02 19:48
@JiaLiPassion Sure, how's this? https://github.com/daleclements/reproduce-angular-issue33657

Never done this before so let me know if I need to do anything differently

**Comment by JiaLiPassion** [comment] 2020-01-03 05:25
@daleclements , thanks, the reason is `jasmine.createSpyObj` create those propertyNames with enumerable false, I created a PR to fix this one.

**Comment by bre-smith** [comment] 2020-02-06 22:58
> @daleclements , thanks, the reason is `jasmine.createSpyObj` create those propertyNames with enumerable false, I created a PR to fix this one.

That is def it. Could always do this as a work around until its fixed.

```
    let descriptors: PropertyDescriptor = Object.getOwnPropertyDescriptor(someServiceSpy , "aProperty");
    descriptors.enumerable = true;
    Object.defineProperty(someServiceSpy , "aProperty", descriptors);
```

**Closed** 2020-06-29 19:22 UTC
Labels: comp: testing
