### ISSUE TITLE
Guards should be able to use Resolvers output

### ISSUE THREAD

**Issue by bsh314** [angular/angular#24045] opened 2018-05-22 08:59 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[X] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
Resolvers executes after Guards
## Expected behavior
Resolvers can be executed before Guards
## Minimal reproduction of the problem with instructions
Any route with one or more Resolver & one or more Guard
## What is the motivation / use case for changing the behavior?
Guards should be able to use Resolvers output  to determine navigation validity 

## Environment
Angular 5 

</code></pre>

**Comment by trotyl** [comment] 2018-05-22 09:14
Relates to or duplicate of https://github.com/angular/angular/issues/15032

**Comment by jasonaden** [comment] 2018-05-24 22:20
Duplicate of #15032

**Closed by jasonaden** 2018-05-24 22:20 UTC
Labels: comp: router
