### ISSUE TITLE
Using UpgradeAdapter with nested NgModules

### ISSUE THREAD

**Issue by mkorenko** [angular/angular#11069] opened 2016-08-25 12:13 UTC
Currently it is possible to use only one instance of UpgradeAdapter created from the main AppModule, because only this instance of adapter becomes bootstrapped and is capable of initializing ng1 components.
But when using several feature NgModules there becomes an issue with the project structure:

``` javascript
// upgradeAdapter.ts, imports AppModule (5)
const upgradeAdapter = new UpgradeAdapter(forwardRef(() => AppModule));

// ui-select.component.ts (1)
@Component({
    selector: 'ui-select',
    template: `...`
})
class UiSelectComponent

// ui-select.module.ts, imports UiSelectComponent (2)
@NgModule({
    declarations: [
        UiSelectComponent,
        upgradeAdapter.upgradeNg1Component('ng1UiSelect')
    ],
    exports: [
        UiSelectComponent
    ]
})
export class UiSelectModule {}

// feature.module.ts, imports UiSelectModule (3)
@NgModule({
    imports: [
        UiSelectModule
    ]
})
export class FeatureModule {}

// app.module.ts, imports FeatureModule (4)
@NgModule({
    imports: [
        FeatureModule
    ]
})
class AppModule {}
```

This plane code works just fine, but if you place it into separate files it will result in cyclical dependency issue.
I'm using ts + rollup setup for bundling, and it places the code in the order described in commented lines (with an allert about cyclical dependency).
upgradeAdapter initialization code becomes the last in the result bundle and UiSelectModule is unable to reference it.

The only workaround now is not to reference AppModule in upgradeAdapter and to store it somewhere else, f.e. in the window:

``` javascript
// upgradeAdapter.ts (1)
const upgradeAdapter = new UpgradeAdapter(forwardRef(() => window.appModule));
...
// app.module.ts, imports FeatureModule (5)
...
class AppModule {}
window.appModule = AppModule 
```

**Comment by marcalj** [comment] 2016-08-26 10:17
I'm using this way:

app.module.ts
```ts
export const upgradeAdapter = new UpgradeAdapter(forwardRef(() => AppModule));

export const ng1Component:Type = upgradeAdapter.upgradeNg1Component('ng1Component');

@NgModule({
    imports: [...],
    declarations: [ng1Component, ...],
    providers: [...]
})
class AppModule {}
```

app.ts
```ts
...
import ng1AppMain from './modules/ng1app.main';

import { upgradeAdapter } from './app.module';

angular.module('App')
    .factory('ng1Service', upgradeAdapter.downgradeNg2Provider(ng1Service))
    ....

import './upgrade_config';

angular.element(document).ready(function () {
    upgradeAdapter.bootstrap(document.body, [ng1AppMain.name]);
});
```

upgrade_config.ts
```ts
import {upgradeAdapter} from './app.module';

upgradeAdapter.upgradeNg1Provider('$filter');
...
```

It works with JIT but not with AoT (ngc):

```
$ ./node_modules/.bin/ngc -p tsconfig.json 
Error: Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol ng1Component in /foo/app.module.ts, resolving symbol AppModule in /foo/app.module.ts, resolving symbol AppModule in /foo/app.module.ts
    at simplifyInContext (node_modules/@angular/compiler-cli/src/static_reflector.js:463:23)
    at StaticReflector.simplify (node_modules/@angular/compiler-cli/src/static_reflector.js:466:22)
    at StaticReflector.annotations (node_modules/@angular/compiler-cli/src/static_reflector.js:52:36)
    at _loop_1 (node_modules/@angular/compiler-cli/src/codegen.js:50:54)
    at CodeGenerator.readFileMetadata (node_modules/@angular/compiler-cli/src/codegen.js:63:13)
    at node_modules/@angular/compiler-cli/src/codegen.js:91:74
    at Array.map (native)
    at CodeGenerator.codegen (node_modules/@angular/compiler-cli/src/codegen.js:91:35)
    at codegen (node_modules/@angular/compiler-cli/src/main.js:7:69)
    at Object.main (node_modules/@angular/tsc-wrapped/src/main.js:25:16)
Compilation failed
```

**Comment by marcalj** [comment] 2016-08-26 10:23
Related issue: https://github.com/angular/angular/issues/10789

**Comment by mkorenko** [comment] 2016-08-26 10:52
@marcalj You are using only one AppModule. In this case it is possible to avoid cyclical dependency. The original issue is about using several NgModules.

**Comment by marcalj** [comment] 2016-08-26 13:51
I'm really using two own modules and other third party modules. But I only using ```upgradeAdapter``` on the main one.

Did you try to put all ```upgradeAdapter.upgradeNg1Component('...')``` into AppModule once?

**Comment by mkorenko** [comment] 2016-08-26 14:25
@marcalj It won't work for me, as I need to declare an upgraded ng1 component exactly in the nested "feature" module, because the component of that module uses it.

**Comment by dparish** [comment] 2016-08-26 21:05
The problem is mainly with upgrading an angular 1 directive to work in an angular 2 component:

```
import { upgradeAdapter } from '../../../app.module';

const fooDirective = upgradeAdapter.upgradeNg1Component('fooDirective');

@Component({
  directives: [fooDirective],
  pipes: [TranslatePipe],
  selector: 'my-selector',
})
```

The only way to make this work is to get a handle on the upgradeAdapter instance from your root module.  

Since the root module needs to be able to also reference the above component so it can be used in the app then you get a circular reference.

I tried removing all barrels to solve this but since you still get a require for every import it's still not working.

I'm concerned that RC5's upgrade process was not tested on a real app, just apps built like the examples all in one or two files.

**Comment by guojenman** [comment] 2016-09-03 14:27
@mkorenko this is the approach I'm using with multiple NgModules and no circular dependencies failure. Hope this helps.

in upgrader.ts
```
// RC 6 now requires a module be passed to UpgradeAdapter
// we'll replace it before bootstrap
@NgModule({})
class DummyModule{}
export const upgrader = new UpgradeAdapter(DummyModule);
```

in bootstrap.ts
```
export function bootstrap (appModule) {
  upgrader['ng2AppModule'] = appModule;
  upgrader.bootstrap(document.body, ['jmApp'], { strictDi: true });
}}
```

in html
```
<script src="my-bundle.js"></script>
<script>
    SystemJS.import('upgrader.js')
        .then(function() {
            // needs to be loaded after upgrader because we need access to 
            return SystemJS.import('ng1-app.js');
        })
        .then(function() {
            // now run main.js from my-bundle.js
            SystemJS.import('main.js');
        });
</script>
```

**Caveat:** notice upgrader['ng2AppModule'], since "ng2AppModule" is not part of the type declarations, I'm sure if this method will work in the future

**Comment by Polvista** [comment] 2016-09-15 09:59
@guojenman Thanks, that's worked!

**Comment by ryanburr** [comment] 2016-10-04 15:11
I have ran into a similar issue, but with a lazy loaded module. 

https://plnkr.co/edit/1wW8T1WbuwoExwjZwmuf (see src/home/home.component.html) 

I receive a "No provider for $scope" error when trying to use an upgraded ng1 component within a lazy loaded module.

Any ideas?

**Comment by sebasrodriguez** [comment] 2016-10-06 21:24
I'm also running into the same issue of not seeing the upgrade adapter if I have multiple ngModules. 

@robwormald @mhevery Is there a plan to natively support multiple ngModules with ngUpgrade or a workaround will be needed to avoid this circular dependency problem?

**Comment by alexsapps** [comment] 2016-12-15 23:13
Bypass UpgradeAdapter by using UpgradeComponent and downgradeComponent from '@angular/upgrade/static'. Since it's in /static and not dynamic, I assume this means you also must enable ahead-of-time compilation (AoT) for your project for this to work. If you can't do AoT, then look at guojenman's workaround above. 

See https://angular.io/docs/ts/latest/guide/upgrade.html for UpgradeComponent/downgradeComponent usage.

**Comment by mgol** [comment] 2016-12-15 23:18
@alexsapps `@angular/upgrade/static` doesn't *require* AOT. It just makes it possible. `@angular/upgrade` works only in JIT mode.

**Comment by shnmkhk** [comment] 2017-01-15 10:58
We see methods like `downgradeInjectable, downgradeComponent` part of `@angular/upgrade/static `(I am switching to upgrade module approach from upgrade adapter way)

What about `upgradeNg1Provider` (or) `upgradeInjectable` for making angular-1's built in providers like `$filter, $q, $rootScope` available in Angular 2 components as dependencies

**Comment by guojenman** [comment] 2017-01-16 21:14
@shnmkhk You can access ng1 services from ng2 in different ways

```
constructor(@Inject('$injector') ngInjector) {
 ngInjector.get('YourServiceName');
}
```
May not be available in lazy-loaded modules since they get a different services context

Or

```
angular.element(document.body).injector()
  .get('YourServiceName');

```
replace document.body with where you bootstrapped your app.

**Comment by shnmkhk** [comment] 2017-01-17 02:47
@guojenman

Thanks for your reply. I do understand how you access ng1 user defined services. What about accessing built-in services like `'$http', '$rootScope', etc.`

When I try to access `angular.element(document.body).Injector().Get('$rrootScope')` it says undefined

**Comment by shnmkhk** [comment] 2017-01-17 02:49
With upgrade Adapter approach, it was simple to make angular 1's built in services available in angular 2

`upgradeAdapter upgradeNg1Provider('$rootScope')`

**Comment by guojenman** [comment] 2017-01-17 14:51
@shnmkhk 

You mispelled $rootScope and have wrong case for the injector and get functions.

This is the corrected version:
`angular.element(document.body).injector().get('$rootScope')`
Again, this assumes you bootstrapped to document.body

**Comment by shnmkhk** [comment] 2017-03-10 06:41
Hello @guojenman 

I see the issue with not-instantiating root module in angular1 context, that is why 

```
angular.element(document.body).injector().get('$rootScope')
```

is returning error. 

Can you guide me how to get angular1's root module context initialized already by the time angular2's components are about to instantiate

**Comment by guojenman** [comment] 2017-03-10 12:28
@shnmkhk If this is in an ng2 Component, as long as you request ng1's injector in the constructor/ngOnInit you should be fine (preferably ngOnInit, you should do as little as possible in the constructor). If you try to get it outside of the class definition, this will always fail. If you're requesting it from an ng2 service, you're going to have to pay greater consideration of when things are initialized and in what order. The way you import and bundle will make a difference here too. In the case of the service, you're going to have to trace all of the services dependencies and their dependencies and see when they're initialized.

**Comment by gkalpak** [comment] 2017-12-13 12:30
I am going to close this since th dynamic version of ngUpgrade has been deprecated and the issue is quite old anyway. If you are still running into problems with the static version, please open a new issue.

**Closed by gkalpak** 2017-12-13 12:30 UTC
Labels: comp: upgrade/dynamic, type: feature
