### ISSUE TITLE
Object.prototype.toString() is overridden and behaves incorrectly

### ISSUE THREAD

**Issue by ma2ciek** [angular/angular#31678] opened 2019-05-30 13:51 UTC
After updating to version 0.9, the `Object.prototype.toString.call( undefined )` returns `[Object Window]` instead of `[Object Undefined]` when the `strict` mode isn't turned on.

The root of this bug is caused by this line:

https://github.com/angular/zone.js/pull/734/files#diff-7cf54420c5bf443f7d3575ad72ac1de3R44

where `this` refers to the `Window` in non-strict mode.

**Comment by mokeev1995** [comment] 2019-12-16 11:35
@JiaLiPassion hi, was the issue fixed with any release?

I've recently ran into a problem with bootstrap (which relies on toString method)

**Comment by michaelz** [comment] 2020-02-17 13:37
I've had the following error in IE11 on bootstrap since Angular 8.3.20 (not present in version 8.3.19): 

`Function.prototype.toString: 'this' is not a Function object`

Is this related ?

**Comment by JiaLiPassion** [comment] 2020-02-17 15:09
@michaelz, could you provide a reproduce repo? thanks.
@mokeev1995, sorry I didn't see your comment, could you provide a reproduce repo? Thanks.

**Comment by michaelz** [comment] 2020-02-18 10:44
@JiaLiPassion I finally found the problem. It came from the my specific file: 

```javascript
import { Injectable } from '@angular/core';
import { TagCommanderClient } from './tag-commander.client';
import { MappedEventData, TagCommanderMappedData } from './tag-management.dto';

@Injectable()
export class WindowsWrapperService extends Window {
	// tslint:disable:variable-name
	tc_events_2: (client: TagCommanderClient, eventName: string, data: MappedEventData[] | MappedEventData) => void;
	tc_vars: TagCommanderMappedData;
}

export function getWindow() {
	return window;
}
```

**Comment by JiaLiPassion** [comment] 2020-02-18 12:53
@michaelz, so the error will occur when you call the `getWindow().toString()`?

**Comment by michaelz** [comment] 2020-02-18 15:31
@JiaLiPassion I'm not sure. This file wasn't even used... so I just removed it and it worked.

**Comment by JiaLiPassion** [comment] 2020-02-18 22:52
@michaelz , yeah, if you can reproduce the issue, and make a break point at `Object.prototype.toString` to find out the value of `this` , that will be very helpful.

**Comment by hansmaad** [comment] 2020-04-28 10:15
@JiaLiPassion @michaelz 

I have the same issue with `Function.prototype.toString: 'this' is not a Function object`
"@angular/core": "^8.2.14",
"@angular/cli": "^8.3.26",

I figured out that it's caused by msal.js angular module that provides `window` here:

https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/f25944f44fa65b201e90965ee9915e4cf3e55dc3/lib/msal-angular/src/msal.module.ts#L39


It then causes the error in polyfills-es5.js here:
```
  function node_modulesCoreJsInternalsInspectSourceJs(module, exports, __webpack_require__) {
    var store = __webpack_require__(
    /*! ../internals/shared-store */
    "./node_modules/core-js/internals/shared-store.js");

    var functionToString = Function.toString; // this helper broken in `3.4.1-3.4.4`, so we can't use `shared` helper

    if (typeof store.inspectSource != 'function') {
      store.inspectSource = function (it) {
        return functionToString.call(it);  // <<<<=== HERE
      };
    }

    module.exports = store.inspectSource;
    /***/
  }
```

**Comment by JiaLiPassion** [comment] 2020-04-30 16:07
@hansmaad, thanks for the information, could you provide a reproduce repo?

**Comment by hansmaad** [comment] 2020-05-02 16:09
@JiaLiPassion Follow these steps to reproduce:

```
npm i @angular/cli@8.3.26
ng new repro --directory .
```

add IE 9-11 to browserlist

Add a module:
```
ng g m test
```
Define the module as:

```
Injectable()
export class WindowWrapper extends Window {
}

@NgModule({
  imports: [CommonModule],
  declarations: [],
})
export class TestModule {
   static forRoot(): ModuleWithProviders {
    return {
      ngModule: TestModule,
      providers: [
        {
            provide: WindowWrapper,
            useValue: window
        }
      ]
    }
  }
}
```

Import the module in AppModule 

```
TestModule.forRoot()
```

```
npm run build
npx live-server ./dist/repro
```

open in IE

**Comment by sunnyyadav100** [comment] 2020-05-08 16:35
> @JiaLiPassion @michaelz
> 
> I have the same issue with `Function.prototype.toString: 'this' is not a Function object`
> "@angular/core": "^8.2.14",
> "@angular/cli": "^8.3.26",
> 
> I figured out that it's caused by msal.js angular module that provides `window` here:
> 
> https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/f25944f44fa65b201e90965ee9915e4cf3e55dc3/lib/msal-angular/src/msal.module.ts#L39
> 
> It then causes the error in polyfills-es5.js here:
> 
> ```
>   function node_modulesCoreJsInternalsInspectSourceJs(module, exports, __webpack_require__) {
>     var store = __webpack_require__(
>     /*! ../internals/shared-store */
>     "./node_modules/core-js/internals/shared-store.js");
> 
>     var functionToString = Function.toString; // this helper broken in `3.4.1-3.4.4`, so we can't use `shared` helper
> 
>     if (typeof store.inspectSource != 'function') {
>       store.inspectSource = function (it) {
>         return functionToString.call(it);  // <<<<=== HERE
>       };
>     }
> 
>     module.exports = store.inspectSource;
>     /***/
>   }
> ```

I am also facing same issue, any workaround for IE11?

**Comment by JiaLiPassion** [comment] 2020-05-28 06:23
This is not a zone.js issue, you can disable the monkey patch of zone.js for `toString()` by define 
`(window as any).__Zone_disable_toString = true` in a file called `zone-flags.ts` and then import this file before importing zone.js

```
import './zone-flags.ts';
import 'zone.js/dist/zone';
```

After this, the error still exists, the reason is 

```
export class WindowWrapper extends Window {
}
```

in IE, the base class `Window` is not a function, instead a `Object`, so this issue can be reproduced by the following code.

```
<html>
  <body>
    <script>
      const w = Window;
      console.log(typeof w);
    </script>
  </body>
</html>

```

in `Chrome`, the type will be `function`, and in IE it will be `Object`, so the error happened, so we need some other tricks to `extends Window` in IE, but still this has nothing to do with `zone.js`, I will do some research later about this issue, but will close this one for now.

**Closed by JiaLiPassion** 2020-05-28 06:23 UTC
Labels: comp: zones
