### ISSUE TITLE
Possibility to use static variables in template.

### ISSUE THREAD

**Issue by AmerAnsari** [angular/angular#40822] opened 2021-02-12 10:03 UTC
Is it possible to do that?

**Comment by mlc-mlapis** [comment] 2021-02-12 10:42
@AmerAnsari Probably not clear what you exactly mean by that.

**Comment by sod** [comment] 2021-02-12 12:58
Probably

```typescript
import {foo} from './foo';

@Component({template: `<div>${foo}</div>`})
export class FooComponent {}
```

Like you can do e.g. on vue or react. The benefit? If you remove the usage from the template, the bundler will automatically treeshake the import away or your ide will tell you that the import is being unused. With the current approach:

```typescript
import {foo} from './foo';

@Component({template: `<div>{{ foo }}</div>`})
export class FooComponent {
    foo = foo
}
```

tooling is just out of luck

**Comment by petebacondarwin** [comment] 2021-02-12 13:20
Duplicate of at least one of: #33652, #9962, #15487

**Closed by petebacondarwin** 2021-02-12 13:20 UTC
