### ISSUE TITLE
Importing readonly array of standalone components/pipes

### ISSUE THREAD

**Issue by yusijs** [angular/angular#48233] opened 2022-11-25 11:52 UTC
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

I *think* this is a regression of https://github.com/angular/angular/issues/47643, but not 100% sure since the related PR talks about component.Imports

As described in [the docs](https://angular.io/guide/standalone-components#standalone-components-for-library-authors), I have published a library where I'm deprecating my modules, and exporting them as Arrays for as an interrim solution:
```
export const DirectivesModule = [
  QuickKeysDirective
  , DateFormFieldClickDirective
....
] as const;
```

This gives me ts-error TS2322, which seems correct since the type definition for imports looks like this:
`imports?: Array<Type<any> | ModuleWithProviders<{}> | any[]>;`
but the type from the compilation is `readonly [typeof QuickKeysDirective, typeof DateFormFieldClickDirective]`

### Please provide the exception or error you saw

```true
TS2322: Type 'readonly [typeof QuickKeysDirective, typeof DateFormFieldClickDirective]' is not assignable to type 'any[] | Type<any> | ModuleWithProviders<{}>'.   The type 'readonly [typeof DateFormatPipe, typeof KeysPipe, typeof NumberFormatPipe, typeof CurrencyFormatPipe, typeof GetUnit, typeof ExcludeUnit, typeof YesNoPipe]' is 'readonly' and cannot be assigned to the mutable type 'any[]'.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Using nx, so not able to run ng version for some reason, but:

    "@angular/animations": "15.0.1",
    "@angular/cdk": "15.0.0",
    "@angular/common": "15.0.1",
    "@angular/compiler": "15.0.1",
    "@angular/core": "15.0.1",
    "@angular/forms": "15.0.1",
    "@angular/material": "15.0.0",
    "@angular/material-date-fns-adapter": "15.0.0",
    "@angular/platform-browser": "15.0.1",
    "@angular/platform-browser-dynamic": "15.0.1",
    "@angular/router": "15.0.1",
    "@angular/service-worker": "15.0.1",
```

**Comment by JoostK** [comment] 2022-11-25 12:48
Duplicate of #48089.

**Comment by yusijs** [comment] 2022-11-25 12:49
jesus how did I not find that when I searched 🤦 thanks @JoostK

**Closed by JoostK** 2022-11-25 12:48 UTC
