### ISSUE TITLE
Fix: Bug in Guards CanActiveFn

### ISSUE THREAD

**Issue by GkIgor** [angular/angular#54459] opened 2024-02-15 16:56 UTC
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

Yes

### Description

When adding a Router.navigate inside a guard in Angular v17, it first redirects to the defined route. When the Promise/Observable is resolved or returns true, a new redirect is made to the protected route that was accessed.

The redirect does not occur in the UrlTree; only the component defined in app.routes.ts is rendered until a return true is made.

I encountered this issue when making an HTTP call to validate a JWT token. Due to several dynamic components that require states created after token validation, the UI ends up breaking.

The solution to work around the problem was to use loadComponent instead of component in app.routes.ts.

### Please provide a link to a minimal reproduction of the bug

https://github.com/GkIgor/bug-guards-v17

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.2.0
Node: 20.10.0
Package Manager: pnpm 8.13.1
OS: linux x64

Angular: 17.2.1
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.9
@angular-devkit/build-angular   17.2.0
@angular-devkit/core            17.0.9
@angular-devkit/schematics      17.0.9
@angular/cli                    17.2.0
@angular/ssr                    17.2.0
@schematics/angular             17.0.9
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.4
```

### Anything else?

# BugGuardsV17

## When F5 or CTRL + R (Or in reload page in route /home) navigate for authComponent

This project was generated with [Angular CLI](https://github.com/angular/angular-cli) version 17.0.9.

## CLI

```zsh
Angular CLI: 17.2.0
Node: 20.10.0
Package Manager: pnpm 8.13.1
OS: linux x64

Angular: 17.2.1
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.9
@angular-devkit/build-angular   17.2.0
@angular-devkit/core            17.0.9
@angular-devkit/schematics      17.0.9
@angular/cli                    17.2.0
@angular/ssr                    17.2.0
@schematics/angular             17.0.9
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.4
```

### Components

The components that make up the bug reproduction are similar to those in the development project. The minimalistic reproduction has the following components: `
AppComponent,
HomeComponent,
NavbarComponent,
AuthComponent. `

if token is valid and Router.navigate(['/auth']) is present in guard, occurs navigation for auth until the observable is resolved. After new navigate to homeComponent.

### Objective

```mermaid
---
title: Auth Strategy
---
stateDiagram-v2
    Home --> Guard
    Guard --> Token
    Token --> exists

    exists --> yes
    exists --> no
    yes --> Home
    no --> Auth


    Guard --> Home


```

### Running

```mermaid

stateDiagram-v2
    Home --> Guard
    Guard --> AuthComponent: If Router.navigate includes in guard,\n redirect to AuthComponent


    AuthComponent --> Token
    Token --> yes
    Token --> no


    yes --> Home: If token is valid,\n redirect a HomeComponent.\n\n Press F5 or CTRL + R for view bug
    no --> AuthComponent

    AuthComponent --> Guard

    Home --> Bug: Render UI Broken


```

**Comment by GkIgor** [comment] 2024-02-15 17:04
Minimal reproduction in production: https://bug-guards-v17.vercel.app/auth/login

**Comment by atscott** [comment] 2024-02-15 23:23
@GkIgor I'm not really following what is expected and what's actually happening in this example. There are at least two problems I'm seeing: The auth component just navigates but never sets the token, so you're always going to be redirected to auth. Second, while this doesn't matter, it's kind of confusing to understand the intent in the example: your guard is resolving `false` without returning and then resolving `true`.

I'm not really seeing anything here that's a bug in Angular. You've also listed that this is a regression. What version did this work in previously? Can you also upload and example of the expected behavior so it's easier to compare the two?

**Comment by GkIgor** [comment] 2024-02-16 13:47
Sorry for the error in the playback, I made a commit correcting the lack of the token.
Looking at the code, you can see that in the guard I set a timeout of 2 seconds so that the guard's behavior can be observed.

The intention is for the guard to protect a private route until the validation of a JWT saved in cookies.
The expected behavior is that there is no pre-navigation, as it occurs in Angular v16.

However, the guard is directing the user to the route defined in router.navigate before checking if the token is valid (hence the timeout). If the validation occurs on the server side, an HTTP call is necessary. In slower connections, the user would stay on the /auth route until the promise/observable is resolved (imagine 10 seconds of HTTP call, it would be 10 seconds of waiting on the /auth screen).

**Comment by GkIgor** [comment] 2024-02-16 14:34
Minimal reproduction in v16: https://github.com/GkIgor/guard-in-v16

**Comment by atscott** [comment] 2024-02-17 04:43
This appears to be working as expected. In v17, you have SSR enabled. When `/home` is requested, the server is redirected to the login page and that's what gets serialized down to the client. So this content is rendered immediately when the app loads, routing on the client kicks in, and redirects to the login page, finally updating the URL to `/auth/login` and completing client hydration.

 As far as the Router and guard behavior goes, the behavior seems correct.

// cc @alan-agius4 @AndrewKushnir for your thoughts on this topic. How should the server handle redirects from the Router? Does this behavior seem correct?

**Comment by GkIgor** [comment] 2024-02-18 17:40
In minimal reproduction, we have this example:
```ts

export const isAuthenticateGuard: CanActivateFn = (route, state) => {

  const token = inject(CookieService).check('_AUTH_TOKEN');
  const router = inject(Router);

  const reqFakeHttp = (): Promise<boolean> => 

    new Promise((resolve) => {

      setTimeout(() => {

        if (!token) {
          router.navigate(['/auth']);
          resolve(false);
        }

        resolve(true);
        
      }, 2000);

    });

  return reqFakeHttp(); // Wait 2s and if token no exists, navigate for /auth 
};

```

I'm not sure how this is happening, but before token verification, the AuthComponent is rendered on the screen and persists there until the function returns. This is also happening with Observables, but the issue itself is this pre-rendering of the component. This occurs when we use router.navigate, but it's not the expected behavior of the method.

To emphasize, in v16, this doesn't happen.


In the real project, this happens when the page is loaded:

![2024-02-08 19-14-07 - Trim](https://github.com/angular/angular/assets/113538225/ca127e29-ee7c-4c98-a350-663072a6a8b0)

**Comment by atscott** [comment] 2024-02-18 20:46
> I'm not sure how this is happening, but before token verification, the AuthComponent is rendered on the screen and persists there until the function returns. This is also happening with Observables, but the issue itself is this pre-rendering of the component. This occurs when we use router.navigate, but it's not the expected behavior of the method.

As mentioned above, this is due to SSR and prerendering on the server. This is the default behavior in Angular v17. You can disable this in the `angular.json` by adding `"ssr": false` to the production and dev configs and setting `"prerender": false` in the build.

 Your cookie service is not configured to read the cookies correctly. [ngx-cookie-service](https://github.com/stevermeister/ngx-cookie-service?tab=readme-ov-file#server-side-rendering) does not work on the server and you need `ngx-cookie-service-ssr` instead. I did check the demo there and it appears that's not working either. I would suggest opening an issue on that repo.

Closing as expected behavior and an issue outside of Angular.

**Closed by atscott** 2024-02-18 20:46 UTC
Labels: area: server
