### ISSUE TITLE
Timing of class host bindings can be inconsistent 

### ISSUE THREAD

**Issue by xiaody** [angular/angular#37279] opened 2020-05-25 14:48 UTC
# 🐞 bug report

### Affected Package

Not sure.

### Is this a regression?

Not sure.

### Description

See the reproduction. If some CSS transition styles is set on host binding [class.xxx],
depending on what codes run in `ngOnInit()`, the CSS transition may work or not.

## 🔬 Minimal Reproduction

 
[https://stackblitz.com/edit/angular-host-class-css-transition?file=src/app/hello.component.ts](https://stackblitz.com/edit/angular-host-class-css-transition?file=src/app/hello.component.ts)

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.1.7
Node: 12.15.0
OS: darwin x64

Angular: 9.1.9
... animations, common, compiler, core, forms, localize
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.7
@angular-devkit/build-angular     0.901.7
@angular-devkit/build-optimizer   0.901.7
@angular-devkit/build-webpack     0.901.7
@angular-devkit/core              9.1.7
@angular-devkit/schematics        9.1.7
@angular/cdk                      9.2.3
@angular/cli                      9.1.7
@angular/compiler-cli             9.1.7
@angular/language-service         9.1.7
@ngtools/webpack                  9.1.7
@schematics/angular               9.1.7
@schematics/update                0.901.7
rxjs                              6.5.5
typescript                        3.7.5
webpack                           4.42.0

</code></pre>

**Anything else relevant?**

**Comment by DanWebb** [comment] 2020-08-06 15:25
This is really odd, trying `document.body.clientHeight` must slow something down? Can anyone explain it?

I would expect the transition to not show in any case because `green` is already set to `true` when the component is added to the DOM so the green class should be applied from the first render. It's really problematic that classes get added to the host element after it's already rendered.

**Comment by jelbourn** [comment] 2020-10-23 22:23
This one is tricky because it may actually just be a browser behavior. It seems like if a reflow occurs, the browser's rendering engine may wait until its next "tick" to apply the CSS class, which would cause the transition to run. I'm not sure there's anything Angular can do to change this.

**Comment by atscott** [comment] 2020-10-23 22:33
Here's a reproduction without Angular:
https://stackblitz.com/edit/web-platform-1iro6w

1. create div
2. append div to body
3. add green class
===> transition not seen

1. create div
2. append div to body
3. read document.body.clientHeight
4. add green class
===> transition seen

Closing this issue as the problem is not with Angular, but is instead a browser behavior.

**Closed by atscott** 2020-10-23 22:33 UTC
Labels: P4, comp: core, core: host and host bindings, core: styling bindings
