### ISSUE TITLE
aio: API docs no longer link to source code

### ISSUE THREAD

**Issue by wardbell** [angular/angular#17718] opened 2017-06-23 01:35 UTC
## I'm submitting a ...

<pre><code>
[x] Regression (behavior that used to work and stopped working in a new release)
[ ] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Old API docs had links to the source code. Can't find those anymore.

For example:  https://angular.io/api/core/EventEmitter

## Expected behavior
Add links to source!  They were really valuable!

If there actually are links to source, let's do something to make them more prominent.

**Comment by wardbell** [comment] 2017-06-23 01:37
Closing because API docs no longer link to source code at all!

At least I couldn't find those links. See issue #17718

**Comment by gkalpak** [comment] 2017-06-23 12:47
Duplicate of #17372.

**Closed by gkalpak** 2017-06-23 12:47 UTC
Labels: comp: aio
