### ISSUE TITLE
Form control's state is not correctly when ChangeDetectionStrategy.OnPush

### ISSUE THREAD

**Issue by lonyel** [angular/angular#19759] opened 2017-10-17 11:41 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
When the compoent's changeDetection: ChangeDetectionStrategy.OnPush, the form control(required,value is empty) state is ng-valid. After cklicked any,the state is ok.
But,when use formControlName,the state is ok.

## Expected behavior
The state=ng-invalid

## Minimal reproduction of the problem with instructions

app.component.ts:
```js
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class AppComponent {
  domain = { a: 100, b: '', c: new Date() };
  
  constructor() {
  }
}
```
app.compoent.html:
```html
<div>
  <form [formGroup]="form">
    <div class="form-group">
      <label>A</label>
      <input type="number" [(ngModel)]="domain.a" name="a">
    </div>
    <div class="form-group">
      <label>B</label>
      <input type="text"  [(ngModel)]="domain.b" name="b" required>
    </div>
    <div class="form-group">
      <label>C</label>
      <input type="date"  [(ngModel)]="domain.c" name="c">
    </div>
  </form>
</div>
```
app.component.scss:
```scss
form {
    .ng-valid[required],
    .ng-valid.required {
        border-left: 5px solid #42A948;
        /* green */
    }
    .ng-invalid:not(form):not(div) {
        border-left: 5px solid #a94442;
        /* red */
    }

}
```
## Environment
Angular version: 4.4.5

Browser:
- [x] Chrome (desktop) version 61
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 6 
- Platform:  Windows

Others:

</code></pre>

**Comment by Toxicable** [comment] 2017-10-17 19:34
Could you make a minimal reproduction in either plunkr or Stack blitz
https://stackblitz.com/
https://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5

**Comment by lonyel** [comment] 2017-10-18 00:29
https://angular-j32iq5.stackblitz.io

**Comment by andreialecu** [comment] 2017-11-28 23:43
@Toxicable, here is another repro of this, with `ng-invalid`:

https://plnkr.co/edit/CAE9LWARVg2RzQbSTAaD?p=preview

I found a workaround by calling `markForCheck()` on a change detector after a 1ms delay after setting the value, but this seems like a quite inconvenient bug otherwise.

**Comment by trotyl** [comment] 2019-07-10 02:15
Duplicate of https://github.com/angular/angular/issues/10816

**Closed** 2019-07-10 10:23 UTC
Labels: comp: forms, freq2: medium, severity3: broken, type: bug/fix
