### ISSUE TITLE
<template is-"dom-bind"> cant be used in html

### ISSUE THREAD

**Issue by bluEEil** [angular/angular#8276] opened 2016-04-27 10:14 UTC
I have been struggling with issues using the paper-data-table written in polymer
(more information about the issue and my questetion is here: [http://stackoverflow.com/questions/36864501/using-paper-datatable-in-angular2](The issue)
One of the suggested solution is to surround the table with: <template is="dom-bind"></template>
which is a polymer binding helper element. The problem is that angular removes all the template tags from the dom which dont use an angular directive (inside my component html).
I didn't find a way to coop with this, maybe there should be some way of telling angular to not process the some template tags (but still process their children because I do need to use data biniding inside the template tag in order to pass data for the table element)

**Comment by pkozlowski-opensource** [comment] 2016-04-27 11:22
Duplicate of #7974

**Closed by pkozlowski-opensource** 2016-04-27 11:22 UTC
