### ISSUE TITLE
Template generated types doesn't behave the same as in native Typescript

### ISSUE THREAD

**Issue by ArielGueta** [angular/angular#43438] opened 2021-09-13 18:40 UTC
### Which @angular/* package(s) are the source of the bug?

language-service

### Is this a regression?

No

### Description

Let's say we have the following component:

```ts
@Component()
export class FooComponent<T, F extends boolean = true> {
  @Input() prop!: T;
  @Input() bar: F = true as F;
}
```

if we use it like this:

```html
<app-foo prop="dummy"></app-foo>
```

We'll see that the inferred type of the second generic is `any`:

<img width="525" alt="Screen Shot 2021-09-13 at 21 37 24" src="https://user-images.githubusercontent.com/20522870/133138372-75bfc98b-741a-4a15-b45c-bcf7245990e4.png">

But if we do the same in plain TS:

```ts
class FooComponent<T, F extends boolean = true> {
  prop!: T;
  bar: F = true as F;
}

new FooComponent<string>()
```

We'll see the the second generic is not typed as `any`:

<img width="658" alt="Screen Shot 2021-09-13 at 21 38 46" src="https://user-images.githubusercontent.com/20522870/133138562-1ec75810-1fa5-4d3c-94de-25e5ef752326.png">

I'm expecting the types to be the same as we use in native TS.

### Please provide the environment you discovered this bug in

```true
Angular: 12.2.5
```

**Comment by atscott** [comment] 2021-09-14 17:40
Closing as duplicate of https://github.com/angular/angular/issues/41395. The language service operates under certain limitations because we cannot perform inline modifications to the files. More information can be found here: https://github.com/angular/angular/commit/0f54d6c4a58b2839430ce514a84916fa7834fac3 / #41513

**Comment by atscott** [comment] 2021-09-14 17:40
Closing as duplicate of https://github.com/angular/angular/issues/41395. The language service operates under certain limitations because we cannot perform inline modifications to the files. More information can be found here: https://github.com/angular/angular/commit/0f54d6c4a58b2839430ce514a84916fa7834fac3 / #41513

**Closed by atscott** 2021-09-14 17:40 UTC
Labels: comp: language-service
