### ISSUE TITLE
double(or consecutive) redirection not working as expected

### ISSUE THREAD

**Issue by theGivingTree** [angular/angular#20370] opened 2017-11-12 10:51 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

[plunker link](https://embed.plnkr.co/IZt19J/)
With this route config:
```
  { path: '', pathMatch: 'full', redirectTo: '/aaa' },
  { path: 'aaa', pathMatch: 'full', redirectTo: '/bbb' },
  { path: 'bbb', component: Hello3 }
```
accessing `''` emits long error logs starting with:
`Error: Cannot match any routes. URL Segment: 'aaa'`

## Expected behavior

Accessing `''` redirects finally to `/bbb`.

## Minimal reproduction of the problem with instructions

[plunker link](https://embed.plnkr.co/IZt19J/)

## What is the motivation / use case for changing the behavior?

The plunker example is just for demo.
In my real application, 1st redirection lazy-loads some module (to `<root>/lazy`),
and 2nd redirection, which is coded inside the lazy-loaded module, is expected to redirect `<root>/lazy` to `<root>/lazy/foo`. (But actually not work at all)

In lazy-module case, there is no error message, but redirection is stopped after the 1st redirection, requiring manual navigation to `<root>/lazy` (hitting enter on  address bar) in order to kick in the 2nd redirection to `<root>/lazy/foo`.

Here's lazy-load cases
[double redirection, lazy-load version](https://embed.plnkr.co/Fo9UPP/)
[single redirection only inside lazy-loaded module](https://embed.plnkr.co/APolWD/)
[single redirection only inside root module](https://embed.plnkr.co/CKBVIV/)

## Environment

<pre><code>
Angular version: 5.0.0

Browser:
- [x] Chrome (desktop) version 62
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by Toxicable** [comment] 2017-11-12 19:37
I don't have a link for you  but I'm 73% sure that a redirect into a redirect is specifically caught and stopped.

**Comment by mlc-mlapis** [comment] 2017-11-12 23:48
I think also, it is just a protection against infinite re-directions ...

**Comment by theGivingTree** [comment] 2017-11-13 04:32
If it is expected behavior, `router.navigate` inside the component of 1st redirection is the only way of simulate subsequent redirections, is it correct? (I mean recommended way)

Is it impossible to detect circular redirection? (or not statically analyzable?) If it is please ignore the below. I will deal with that. (if it is **possible**...)↓↓↓

There is some situation that root module configures its routing to `/home` to some lazy-loaded module (`/home/lazyfeat1`), and that lazy-loaded module may have also its own redirection behavior.
(Let's ignore the case that double redir is configured inside same routing module. It is just for demo, and is stupid)

It seems somewhat ugly that 1st redirection merges the 2nd redirection. It's my opinion that route configs should be separated between modules, which means root module should not care about the routing inside another module, and vice versa (especially between root module and lazy-loaded module)

**Comment by jasonaden** [comment] 2017-11-13 23:40
I think you're looking for this logic:

https://github.com/angular/angular/blob/master/packages/router/src/apply_redirects.ts#L87

Specifically, redirect is not allowed after absolute redirect. Closing this issue as it's working as intended (try redirect without using an absolute path).

**Closed by jasonaden** 2017-11-13 23:40 UTC

**Comment by simeyla** [comment] 2019-03-05 10:32
Really odd that I can't redirect

   `/shop` to `/store`

where 

   `/store` is a lazy route that redirects to `/store/products`

So it's 'by design' but it's very unexpected, especially considering there's no server round trip. You can literally end up 'orphaned' at an invalid URL that would otherwise redirect. This is a very dangerous decision if you're not careful!

Anyway the relative redirection works fine, it just makes it harder to redirect from one module to another if you don't know the final URL.

            {
                path: '',
                redirectTo: 'orders',
                pathMatch: 'full',
                runGuardsAndResolvers: () => false
            },            
            { 
                path: 'orders',
                
                children: [
                    { 
                        path: '',
                        pathMatch: 'full',
                        redirectTo: 'history'
                    },
                    {
                        path: 'history',
                        resolve: { orders: AccountOrdersResolve },
                        component: AccountOrderListComponent
                    },
                    {
                        path: ':id',
                        resolve: { order: OrderResolve },
                        component: AccountOrderHistoryComponent
                    }
                ]
            }

It's also kind of funny how easy it is to make a redirect loop (using router.navigate) in angular that will KILL Chrome to the point where it's almost impossible to stop the task because it's taking up so much CPU - doing a redirect!
