### ISSUE TITLE
bazel failed to publish build artifacts because of wrong bazel-bin dir

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#23579] opened 2018-04-27 17:59 UTC
I ran:
```
./scripts/release/publish-next
```

and got:
```
...
INFO: Found 1 target...
Target //packages/upgrade:npm_package.publish up-to-date:
  /usr/local/google/home/iminar/.cache/bazel/_bazel_iminar/59bb2d32ef7f0c65b91d2f978929a58d/execroot/angular/bazel-out/k8-fastbuild/bin/packages/upgrade/npm_package.publish
INFO: Elapsed time: 0.598s, Critical Path: 0.06s
INFO: Build completed successfully, 1 total action

INFO: Running command line: /usr/local/google/home/iminar/.cache/bazel/_bazel_iminar/59bb2d32ef7f0c65b91d2f978929a58d/execroot/angular/bazel-out/k8-fastbuild/bin/packages/upgrade/npm_package.publish --access public --tag next
npm ERR! path /usr/local/google/home/iminar/gits/angular/bazel-out/k8-fastbuild/bin/packages/upgrade/npm_package/package.json
npm ERR! code ENOPACKAGEJSON
npm ERR! errno -2
npm ERR! syscall open
npm ERR! package.json ENOENT: no such file or directory, open '/usr/local/google/home/iminar/gits/angular/bazel-out/k8-fastbuild/bin/packages/upgrade/npm_package/package.json'
npm ERR! package.json npm can't find a package.json file in your current directory.

npm ERR! A complete log of this run can be found in:
npm ERR!     /usr/local/google/home/iminar/.npm/_logs/2018-04-27T17_53_34_575Z-debug.log
ERROR: Non-zero return code '254' from command: Process exited with status 254
```

the issue seems to be that the `bazel-bin` path is hardcoded incorrectly somewhere:
```
$ bazel info bazel-bin
/usr/local/google/home/iminar/.cache/bazel/_bazel_iminar/59bb2d32ef7f0c65b91d2f978929a58d/execroot/angular/bazel-out/k8-fastbuild/bin
```

**Comment by alexeagle** [comment] 2018-04-27 18:17
root cause: https://github.com/bazelbuild/rules_nodejs/issues/187

**Comment by IgorMinar** [comment] 2018-04-27 18:39
workaround:

```
diff --git a/tools/bazel.rc b/tools/bazel.rc
index 1d0f39dfd2..c5590d38f9 100644
--- a/tools/bazel.rc
+++ b/tools/bazel.rc
@@ -19,7 +19,7 @@ test:debug --test_arg=--node_options=--inspect-brk --test_output=streamed --test
 # eventually a surprising failure with auto-discovery of the C++ toolchain in
 # MacOS High Sierra.
 # See https://github.com/bazelbuild/bazel/issues/4603
-build --symlink_prefix=/
+#build --symlink_prefix=/

 # Performance: avoid stat'ing input files
 build --watchfs
```

**Comment by jelbourn** [comment] 2020-10-16 21:04
Closing since this appears to be obsolete

**Closed by jelbourn** 2020-10-16 21:04 UTC
Labels: P3, comp: build & ci, freq3: high, type: bug/fix
