### ISSUE TITLE
ViewEncapsulation ShadowDom containing NoEncapsulation components

### ISSUE THREAD

**Issue by Detzito** [angular/angular#53155] opened 2023-11-24 21:02 UTC
### Describe the problem that you experienced

The documentation seems not to reflect the reality when using ShadowDom embedding NoEncapsulation components.

### Enter the URL of the topic with the problem

https://angular.io/guide/view-encapsulation

### Describe the actions that led you to experience the problem

I discovered the problem when i switched some of my components to ShadowDom. They are using @angular/material components (declared as NoEncapsulation). All the styles of the material components that I overrode where lost. For example, I cannot override the background of a material card.

### Add a screenshot if that helps illustrate the problem

Documentation pretends : 
![image](https://github.com/angular/angular/assets/12083780/7fe31eb4-b5a3-404e-947c-4986f7b8dda9)

What I get with the same components hierarchy : 
![image](https://github.com/angular/angular/assets/12083780/f35f61f5-3c6f-43b5-9225-010f58619c0b)

**Comment by JoostK** [comment] 2023-11-24 21:09
The documented behavior as [showcased in StackBlitz](https://stackblitz.com/edit/qqxbx1?file=src%2Fapp%2Fapp.component.ts) does correspond with the screenshot in the documentation. Since you haven't shared your code I can't comment on the behavior you are experiencing, but something seems off.

**Comment by Detzito** [comment] 2023-11-24 21:17
https://stackblitz.com/edit/qqxbx1-w86p62?file=src%2Fapp%2Fapp.component.ts

I don't understand why the shadow component is different if you use Emulated and NoEncapsulation next to it...

**Comment by Detzito** [comment] 2023-11-26 17:43
> The documented behavior as [showcased in StackBlitz](https://stackblitz.com/edit/qqxbx1?file=src%2Fapp%2Fapp.component.ts) does correspond with the screenshot in the documentation. Since you haven't shared your code I can't comment on the behavior you are experiencing, but something seems off.

I edited your showcase to illustrate my problem : https://stackblitz.com/edit/qqxbx1-w86p62?file=src%2Fapp%2Fapp.component.ts

The styles seem to be inserted in a different order in your example and mine.
Maybe am I wrong but I don't see any reason for this difference.

My sample : 
![image](https://github.com/angular/angular/assets/12083780/f59ea4df-722b-4300-8e4f-496dca61da45)

Your : 
![image](https://github.com/angular/angular/assets/12083780/7ba747dd-c59d-40f3-9842-d357805172f8)

**Comment by JeanMeche** [comment] 2023-11-26 22:47
Looks like a dupe of #49803. Let's continue over there !

**Closed by JeanMeche** 2023-11-26 22:47 UTC
