### ISSUE TITLE
AoT error when using static member in `Route#redirectTo`

### ISSUE THREAD

**Issue by luisbirchenz** [angular/angular#16321] opened 2017-04-25 15:42 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I'm dealing with a strange situation, at least for me. In my angular 2 project, in a typescript module I tried to replace the hardcoded routes showed below:

const routes: Routes = [
 { path: '', redirectTo: 'login', pathMatch: 'full' },
 { path: 'login', component: LoginComponent, canActivate: [AuthGuardLogin] },
 { path: 'landing', component: LandingComponent, canActivate: [AuthGuardService] }
];
By this approach:

const routes: Routes = [
 { path: RootUris.Base, redirectTo: RootUris.Login, pathMatch: 'full' },
 { path: RootUris.Login, component: LoginComponent, canActivate: [AuthGuardLogin] },
 { path: RootUris.Landing, component: LandingComponent, canActivate: [AuthGuardService] }
];
Where RootUris is a class like this:

export class RootUris {
    public static readonly Base: string = '';
    public static readonly Login: string = 'login';
    public static readonly Landing: string = 'landing';
}
Everything goes well when I work in dev, even though if I run the app it works fine but when I try to build it by using ng build --prod I got this:

ERROR in Illegal state: symbol without members expected, but got {"filePath":"C:/dev/myApp/client/src/app/common/url-mapping.ts","name":"RootUris","members":["Base"]}.

ERROR in ./src/main.ts Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in 'C:\repo\behavioral-health-legend\client\src' @ ./src/main.ts 4:0-74 @ multi ./src/main.ts
The rarest thing here is that if I replace the first element of the array (Only that, the rest still using the static attributes):

{ path: RootUris.Base, redirectTo: RootUris.Login, pathMatch: 'full' }

By this one:

{ path: '', redirectTo: 'login', pathMatch: 'full' }

Everything works fine.

So, does anyone know why I cannot use the static attribute of my class there (in the first element of the array)? Any ideas?

**Expected behavior**

It should work in the same way it works when I run the app by using ng serve. By running it locally it works.

Because, as I mentioned early, when I run ng build --prod it fails.

**Minimal reproduction of the problem with instructions**

If you perform the same settings I mentioned before when you are going to get the same error.

**What is the motivation / use case for changing the behavior?**

I'm trying to define in just one place the URL mappings. That's why I created that class to map every url there.
For every new module created I'll use this class to map the url there too. Considering that the name could be repeated this is the best approach.

**Please tell us about your environment:**

Visual Studio Code 1.10.2

backend java rest services.

package.json

{
    "name": "bh-legend",
    "version": "0.0.0",
    "license": "MIT",
    "scripts": {
        "ng": "ng",
        "build": "ng build --prod",
        "lint": "tslint \"src/**/*.ts\" --project src/tsconfig.lint.json --type-check && tslint \"e2e/**/*.ts\" --project e2e/tsconfig.e2e.json --type-check",
        "start": "ng serve --proxy-config proxy.conf.json",
        "test": "ng test",
        "test-single-run": "ng test --watch=false --code-coverage=true",
        "pree2e": "webdriver-manager update --standalone false --gecko false",
        "e2e": "protractor"
    },
    "private": true,
    "dependencies": {
        "@angular/common": "4.0.0",
        "@angular/compiler": "4.0.0",
        "@angular/core": "4.0.0",
        "@angular/forms": "4.0.0",
        "@angular/http": "4.0.0",
        "@angular/platform-browser": "4.0.0",
        "@angular/platform-browser-dynamic": "4.0.0",
        "@angular/router": "4.0.0",
        "angular2-text-mask": "8.0.0",
        "bootstrap": "3.3.7",
        "core-js": "2.4.1",
        "mydatepicker": "1.7.16",
        "ng2-bootstrap": "1.6.1",
        "ng2-bootstrap-modal": "1.0.1",
        "ng2-cookies": "1.0.10",
        "ng2-device-detector": "0.1.0",
        "rxjs": "5.1.0",
        "ts-helpers": "1.1.2",
        "typescript": "2.2.2",
        "typings": "2.1.0",
        "zone.js": "0.8.4"
    },
    "devDependencies": {
        "@angular/cli": "1.0.0",
        "@angular/compiler-cli": "4.0.0",
        "@types/jasmine": "2.5.38",
        "@types/node": "6.0.60",
        "codelyzer": "2.0.0",
        "jasmine-core": "2.5.2",
        "jasmine-spec-reporter": "3.2.0",
        "karma": "1.4.1",
        "karma-chrome-launcher": "2.0.0",
        "karma-cli": "1.0.1",
        "karma-coverage-istanbul-reporter": "0.2.0",
        "karma-jasmine": "1.1.0",
        "karma-jasmine-html-reporter": "0.2.2",
        "karma-phantomjs-launcher": "1.0.4",
        "phantomjs-prebuilt": "2.1.4",
        "protractor": "5.1.0",
        "ts-node": "2.0.0",
        "tslint": "4.5.0",
        "typescript": "2.2.2"
    }
}

* **Angular version:** 2.0.X

See information pasted above (before this point)

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

I work with Firefox and IE 11 / Edge according to client requirements. I do not use chrome or any mobile platform so far.
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

Typescript (Version was specified above)

* **Node (for AoT issues):** `node --version` =   
6.9.4

**Comment by Toxicable** [comment] 2017-04-25 19:43
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by Toxicable** [comment] 2017-04-25 19:44
The AOT compiler cannot evaluate `RootUris.Login` therefore as the error says it is invalid.

**Comment by luisbirchenz** [comment] 2017-04-25 19:52
Thanks for replaying it. But according to your response AOT compiler cannot evaluate RootUris.Login but this only happens in the first position of the array:

const routes: Routes = [
**{ path: RootUris.Base, redirectTo: RootUris.Login, pathMatch: 'full' },**
{ path: RootUris.Login, component: LoginComponent, canActivate: [AuthGuardLogin] },
{ path: RootUris.Landing, component: LandingComponent, canActivate: [AuthGuardService] }
];

It does not happen for the rest of the array. Why?

Anyway, thanks again.

Regards,

Luis.

**Comment by Toxicable** [comment] 2017-04-25 19:55
@luisbirchenz 
Does this throw an error?
```
const routes: Routes = [
{ path: RootUris.Base, redirectTo: 'login', pathMatch: 'full' },
{ path: RootUris.Login, component: LoginComponent, canActivate: [AuthGuardLogin] },
];
```

**Comment by luisbirchenz** [comment] 2017-04-25 20:02
If I use this way:

const routes: Routes = [
**{ path: RootUris.Base, redirectTo: RootUris.Login, pathMatch: 'full' },**
{ path: RootUris.Login, component: LoginComponent, canActivate: [AuthGuardLogin] },
{ path: RootUris.Landing, component: LandingComponent, canActivate: [AuthGuardService] }
];

This throws an error:

**ERROR in Illegal state: symbol without members expected, but got {"filePath":"C:/dev/myApp/client/src/app/common/url-mapping.ts","name":"RootUris","members":["Base"]}.

ERROR in ./src/main.ts Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in 'C:\repo\behavioral-health-legend\client\src' @ ./src/main.ts 4:0-74 @ multi ./src/main.ts
The rarest thing here is that if I replace the first element of the array (Only that, the rest still using the static attributes):**

BUT if I use this way:

const routes: Routes = [
**{ path: '', redirectTo: 'login', pathMatch: 'full' },**
{ path: RootUris.Login, component: LoginComponent, canActivate: [AuthGuardLogin] },
{ path: RootUris.Landing, component: LandingComponent, canActivate: [AuthGuardService] }
];

**This works**. That's why I said you it does not work for the first position of the array (routes) but it does not happen for the others. Why? AOT compiler cannot evaluate just one position, is that the explanation? It is not clear enough for me.


Regards,

Luis.

**Comment by Toxicable** [comment] 2017-04-25 20:13
Can you make a *minimal* (ie only the routing config) reproduction repo that I can clone

**Comment by luisbirchenz** [comment] 2017-04-25 20:16
Ok, give me time to create an example for you because my project is big and I have no permission to share it. Anyway, I'll put here the link to github as soon as I can.

Regards,

Luis.

**Comment by luisbirchenz** [comment] 2017-04-26 15:07
Hello Toxicable,

As I promised you yesterday, I created a demo in order to reproduce the problem I reported before. 
Here is a simple demo: [demo bug](https://github.com/luisbirchenz/demoBug.git)

Just to clarify it much better, in appModule.ts there are 3 scenarios:

1 - (Commented) The hardcoded URLs which works without any problems, common situation.
/*
```
const routes: Routes = [
  { path: '', redirectTo: 'home', pathMatch: 'full' },
  { path: 'home', component: HomeComponent },
  { path: 'other', component: OtherComponent }
];
```
*/

2 - The URLs referred by static methods from a class which represent the URL and it works without any problems by running it with **ng serve** but it does not work when we create the production version  by using **ng build --prod** (THIS IS THE ISSUE - error described above)
    
```
const routes: Routes = [
  { path: RootUri.Base, redirectTo: RootUri.Home, pathMatch: 'full' },
  { path: RootUri.Home, component: HomeComponent },
  { path: RootUri.Other, component: OtherComponent }
];
```

3 - (Commented) The last one that works in both situations, by running with **ng server** and **ng build --prod** and it is related to my last question when you said that the second scenario (2) happened because the AOT compiler cannot evaluate RootUri.Login.
Based on that, by using this setting here I can demonstrate that it works just replacing the static attribute used in the first position of the array but the 2 last remain as before.
I mean they use static method and the AOT compiler does not complain about that.  Just for the first position of the array, Why? That was not clear for me. It does not make sense for me.
/*
```
const routes: Routes = [
  { path: '', redirectTo: 'home', pathMatch: 'full' },
  { path: RootUri.Home, component: HomeComponent },
  { path: RootUri.Other, component: OtherComponent }
];
```
*/

I hope it helps your understanding right now.

I look forward to receiving your feedback.

Thanks in advance.
Luis.

**Comment by gkalpak** [comment] 2017-05-04 08:47
FWIW, this only affects the `redirectTo` field, not `path` (and it is not related to the index of the element in the array). Are `redirectTo` fields special is some way?

**Comment by jasonaden** [comment] 2017-12-13 00:07
This should be fixed with updates to the Compiler allowing variable access in configuration properties. If this is still a problem with current Angular and Router, please create a new issue.

**Closed by jasonaden** 2017-12-13 00:07 UTC
Labels: comp: router, type: bug

**Comment by evabat** [comment] 2017-12-21 15:27
This is not exactly a satisfying answer or functional, in factr it is quite obscure. Which are those properties exactly in compiler options? I have a date string as parameter in my app and this should change everyday (as happens with dates as usual). Locally my solution works fine, at production mode with --aot=false works fine, why the deployed app with --aot=true mode should NOT work? My routes look like this:
`const routes: Routes = [
    {path: '', redirectTo: '/date/' + date.format(new Date(), 'YYYYMMDD'), pathMatch: 'full'},
....]`

I just need that date string to be returned by a variable!
I cannot get rid of the parameter date because it is crucial for my observable object.
I cannot get rid of AOT because I am not willing to sacrifice my app's performance.
I am using angular4, version 4.2.4. Thank you in advance for your time.

**Comment by tuanbs** [comment] 2019-08-29 11:44
Hi, I had the same issue and spent few days to find out a solution. But thanks to this question, my issue is solved now. Instead of using `static readonly`, I used `public static get homePath(): string { return 'home'; }` which caused error when I run `ng build --prod`. But after switching to `static readonly`, it works now. It even works with the `redirectTo`. So I think the new version of Angular (I'm using 7.x) fixed this issue.

I think this is a good practice because hardcoded the route path value violates the DRY principle as value could be repeated. Anyway, thanks @luisbirchenz for this question.
