### ISSUE TITLE
Setting/updating a signal must be done in NgZone(?)

### ISSUE THREAD

**Issue by csisy-btw** [angular/angular#53566] opened 2023-12-14 07:11 UTC
### Describe the problem that you experienced

We've just started using signals and OnPush change detection and found out that setting/updating a signal must be done in NgZone, otherwise the component will not be updated (until something else forces a change detection).

The documentation writes about signals and OnPush components, but it does not mention anything about the zone.

### Enter the URL of the topic with the problem

https://angular.io/guide/signals#reading-signals-in-onpush-components

### Describe what you were looking for in the documentation

Clarification, or more in-depth description about the connection between the zone and signals.

### Describe the actions that led you to experience the problem

We are using a `ResizeObserver` to detect if an element is resized. The following Stackblitz example is simplified, but the root problem is the same: https://stackblitz.com/edit/stackblitz-starters-fbyzdi?file=src%2Fmain.ts

All you have to do is to resize the viewport and check if the `is small?` value turns to true (the value is logged into the console as well).

Currently, the `OutsideZoneComponent` is used and as you can see, the component is not updated. More importantly, the component will not be updated even if the OnPush strategy is not used.

If you uncomment the `<app-inside-zone/>` tag in the `App`'s template, everything works as expected.

**Comment by JeanMeche** [comment] 2023-12-14 08:49
Hi, this is a dupe of #31695. 
Essentially, `ResizeObserver` isn't patched by `zone.js` so the callback is run outside the angular zone.

**Closed by JeanMeche** 2023-12-14 08:49 UTC
