### ISSUE TITLE
Wildcard route (**) does not catch "Named router-outlet not found"

### ISSUE THREAD

**Issue by TheJLifeX** [angular/angular#40845] opened 2021-02-14 18:49 UTC
# 🐞 bug report

### Affected Package

@angular/angular

### Is this a regression?

no

### Description

Wildcard route (**) does not catch "named router-outlet not found".

With the following routes
```ts
const routes: Routes = [
  {
    outlet: 'test',
    path: 'test',
    loadChildren: () => import('./test-page/test-page.module').then(m => m.TestPageModule)
  },
  {
    outlet: 'test',
    path: '**',
    loadChildren: () => import('./page-not-found/page-not-found.module').then(m => m.PageNotFoundModule)
  },
  {
    path: '**',
    loadChildren: () => import('./page-not-found/page-not-found.module').then(m => m.PageNotFoundModule)
  }
];
```

you get the following results.
| URL                                   | Result                |
|---------------------------------------|-----------------------|
| http://localhost:4200/(test:test)   | Okay (test-page)      |
| http://localhost:4200/(test:unknow) | Okay (page-not-found) |
| http://localhost:4200/unknow        | Okay (page-not-found) |
| http://localhost:4200/(testt:test)  | **Error**             |
| http://localhost:4200/(unknow:test) | **Error**             |
| http://localhost:4200/(unknow) | **Error**             |
| http://localhost:4200/a-path(unknow:test) | **Error**             |
| http://localhost:4200/a-path(unknow) | **Error**             |

<br/>

**Thank you in advance for considering this issue.**

### Clone [this minimal GitHub repository](https://github.com/TheJLifeX/bug-named-router-outlet-not-found)
```sh
npm install
```

Run the app then open http://localhost:4200/(unknow:test) on your browser and look at the browser console.
```sh
npm run start
```

## 🔥 Exception or Error
<pre><code>
ERROR Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'test'
Error: Cannot match any routes. URL Segment: 'test'
    at ApplyRedirects.noMatchError (router.js:2623)
    at CatchSubscriber.selector (router.js:2605)
    at CatchSubscriber.error (catchError.js:27)
    at MapSubscriber._error (Subscriber.js:75)
    at MapSubscriber.error (Subscriber.js:55)
    at MapSubscriber._error (Subscriber.js:75)
    at MapSubscriber.error (Subscriber.js:55)
    at ThrowIfEmptySubscriber._error (Subscriber.js:75)
    at ThrowIfEmptySubscriber.error (Subscriber.js:55)
    at TakeLastSubscriber._error (Subscriber.js:75)
    at resolvePromise (zone-evergreen.js:1209)
    at resolvePromise (zone-evergreen.js:1163)
    at zone-evergreen.js:1275
    at ZoneDelegate.invokeTask (zone-evergreen.js:402)
    at Object.onInvokeTask (core.js:28515)
    at ZoneDelegate.invokeTask (zone-evergreen.js:401)
    at Zone.runTask (zone-evergreen.js:174)
    at drainMicroTaskQueue (zone-evergreen.js:578)
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
     _                      _                 ____ _     ___ 
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | | 
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | | 
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 11.2.0
Node: 12.16.1
OS: win32 x64

Angular: 11.2.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.0
@angular-devkit/build-angular   0.1102.0
@angular-devkit/core            11.2.0
@angular-devkit/schematics      11.2.0
@schematics/angular             11.2.0
@schematics/update              0.1102.0
rxjs                            6.6.3
typescript                      4.1.5
</code></pre>

**Anything else relevant?**
no

**Comment by atscott** [comment] 2021-02-20 01:23
I'm going to close this because it doesn't affect future navigations and still produces a `NavigationError`. 

Navigations return a promise that rejects when they fail. This is expected behavior and isn't specific to wildcard routes or named outlets.

**Closed by atscott** 2021-02-20 01:23 UTC
Labels: comp: router
