### ISSUE TITLE
Incorrect NgModule resolution with library and npm link

### ISSUE THREAD

**Issue by IgorAufricht** [angular/angular#35447] opened 2020-02-14 16:03 UTC
# 🐞 bug report

### Affected Package

 The issue is probably caused by package @angular/compiler-cli.

### Is this a regression?

 Yes, the previous version in which this bug was not present was:
^8.2.0 (not using Ivy)

### Description

For our project we are using Angular workspace combined with [lerna](https://github.com/lerna/lerna) (we use lerna mainly to handle versioning and release of our libraries as npm packages). We have a single application and multiple packages. After upgrading to Angular 9, we are getting the following error when trying to build the application:
> Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class

Because we use lerna, our libraries are linked inside `node_modules`, which seems to be the problem (and possibly makes this different from the other github issues with the same error). If we remove the link in `node_modules`, the app builds as expected.

## 🔬 Minimal Reproduction
https://github.com/IgorAufricht/angular-import-not-resolved-repro

The steps are included in the readme, but for clarity, here they are:
* `git clone https://github.com/IgorAufricht/angular-import-not-resolved-repro.git && cd angular-import-not-resolved-repro`
* `npm install`
* `ng build lib1 --prod && ng build --prod` (builds correctly)
* `cd projects/lib1 && npm link && cd ../.. && npm link lib1` (1)
* `ng build lib1 --prod && ng build --prod` (fails)

(1) With our lerna setup we use yarn workspaces, but it creates the links in `node_modules` in the same way.

## 🔥 Exception or Error
<pre><code>ERROR in dist/lib1/lib/lib1.module.d.ts:1:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class

1 export declare class Lib1Module {
                       ~~~~~~~~~~</code></pre>


## 🌍  Your Environment

**Angular Version:**
<pre><code>Angular CLI: 9.0.2
Node: 12.13.1
OS: win32 x64

Angular: 9.0.1
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.900.2
@angular-devkit/build-angular      0.900.2
@angular-devkit/build-ng-packagr   0.900.2
@angular-devkit/build-optimizer    0.900.2
@angular-devkit/build-webpack      0.900.2
@angular-devkit/core               9.0.2
@angular-devkit/schematics         9.0.2
@angular/cli                       9.0.2
@ngtools/webpack                   9.0.2
@schematics/angular                9.0.2
@schematics/update                 0.900.2
ng-packagr                         9.0.0
rxjs                               6.5.4
typescript                         3.7.5
webpack                            4.41.2</code></pre>

**Anything else relevant?**
Related issue: #35255

**Comment by gkalpak** [comment] 2020-02-14 16:22
FWIW, there is potentially relevant discussion in #33395.

**Comment by FranzZemen** [comment] 2020-02-16 17:59
When get NG6002 with a module issue as above, delete the top node_modules in the workspace (where you should have installed it), and rebuild libraries/apps.

Seems like on first build, output is added to node_modules that gets occasionally confused.

This 'trick" works for me with problems incrementally added angular material modules to a library and app.

**Comment by IgorAufricht** [comment] 2020-02-17 08:43
@FranzZemen That doesn't seem to help in this case, although I did run into the issue you mention and reinstalling did help there.

This is my current understanding of this issue:
When Angular CLI needs to include a non-Ivy library (which should be every library at the moment, since it's not recommended to build a library using Ivy), it needs to use the `ngcc` (compatibility compiler) to compile the library for Ivy before it can be included in the build. This will manifest as the compiler adding a directory named `__ivy_ngcc__` to the library to the place where it loads the code when it builds the application:
1. If the library is in `node_modules`, the directory is added there (e.g. `node_modules/@angular/common/__ivy_ngcc__`).
2. If the library is from the same monorepo, the directory is added to the `dist` folder of the library (in our case that would be `dist/lib1/__ivy_ngcc__`).

The problem here is that when the package is npm linked, the directory from scenario 2 (`dist/lib1/__ivy_ngcc__`) is not generated, thus resulting in a failing build.

**Comment by okko** [comment] 2020-02-18 11:34
Add the `"postinstall"` documented in https://angular.io/guide/ivy#speeding-up-ngcc-compilation, then `rm -rf node_modules`, then `yarn` if using yarn workspaces (`lerna` in your case). This fixed it for me, our project is using yarn workspaces instead of lerna.

If it fixes it for the others too, the guide's title could be changed to "Ngcc compilation with lerna, yarn workspaces, or just speeding up ngcc compilation in general"

**Comment by andreialecu** [comment] 2020-02-28 08:05
Probably related: https://github.com/angular/angular/issues/35747

**Comment by CDevine1** [comment] 2020-03-24 23:18
@okko Doesn't work with lerna, but the concept does. Compiling your package manually with ngcc works around the problem.

**Comment by petebacondarwin** [comment] 2020-05-24 19:27
Marking as a duplicate of #33395 since we seem to be having the same discussions in both issues.

**Closed by petebacondarwin** 2020-05-24 19:27 UTC
Labels: comp: compiler, comp: ngcc, engine: ivy, severity5: regression
