### ISSUE TITLE
angular.dev: @example overflow

### ISSUE THREAD

**Issue by moniuch** [angular/angular#52591] opened 2023-11-07 16:46 UTC
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

Not sure this is the right repo to report angular.dev glitch, but I couldn't find one on the list of angular repos that would seem appropriate.

![image](https://github.com/angular/angular/assets/681956/f8f54ed8-ddfa-46f3-a86f-33155f6d1f06)

### Please provide a link to a minimal reproduction of the bug

https://angular.dev/api/router/testing/RouterTestingHarness

### Please provide the environment you discovered this bug in
```true
angular.dev
Chrome 118
```

**Comment by twerske** [comment] 2023-11-08 23:26
This is the right repo! We haven't yet implemented `{@example code}` in the API reference due to needing to open source the repo. This is actually generated from the source code in this same repo, so it's all currently in progress. 

You can further track this work in the API Reference issue: https://github.com/angular/angular/issues/52663
Closing this as a duplicate of the known bugs there.

Thanks for the report and helping us beta test Angular.dev

**Closed by twerske** 2023-11-08 23:26 UTC
Labels: area: adev-infra
