### ISSUE TITLE
Unable to set scrollOffset using provideRouter

### ISSUE THREAD

**Issue by vickieallen-certua** [angular/angular#51601] opened 2023-08-31 15:49 UTC
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

Yes

### Description

As far as I can see from the documentation we are no longer able to set scrollOffset when using 
`  provideRouter(
     routes,
    withComponentInputBinding(),
     withInMemoryScrolling({
        anchorScrolling: 'enabled',
     })
    ),`
    
    This is still available if I use importProvidersFrom(RouterModule.... 
    
Please can we have this added to the withInMemoryScrolling options above

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 16.1.1
Node: 18.16.1
Package Manager: yarn 1.22.19
OS: win32 x64

Angular: 16.1.2
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1601.1
@angular-devkit/build-angular   16.1.1
@angular-devkit/core            16.1.1
@angular-devkit/schematics      16.1.1
@angular/cli                    16.1.1
@schematics/angular             16.1.1
rxjs                            7.8.0
typescript                      4.9.5
```

**Comment by atscott** [comment] 2023-08-31 19:10
This was done intentionally because the option is a duplicate of what's already available in `ViewportScroller`. Instead, call you should call `ViewportScroller.setOffset` (https://angular.io/api/common/ViewportScroller#setOffset)

**Closed by atscott** 2023-08-31 19:10 UTC
Labels: area: router, cross-cutting: standalone
