### ISSUE TITLE
Clarify multiple downgradeModules example

### ISSUE THREAD

**Issue by thelgevold** [angular/angular#29975] opened 2019-04-18 13:24 UTC
# 📚 Docs or angular.io bug report

### Description

I think the section about multiple downgradeModules needs more clarification and detail.
The sample uses the Angular Compiler to dynamically compile separate modules to downgrade. This does not work in the CLI when doing AoT, so it would be good to include a more production ready sample. 

The error you see when running this sample is `Runtime compiler is not loaded`, which makes sense when doing AoT. However, the sample is not very practical if AoT is unsupported.

The article in question can be found here: https://angular.io/api/upgrade/static/downgradeModule 

### What's the affected URL?**
https://angular.io/api/upgrade/static/downgradeModule

### Reproduction Steps**
Running the code from the sample

```
const downgradedNg2AModule = downgradeModule(async(extraProviders: StaticProvider[]) => {
  const rootInjector = await getRootInjector(extraProviders);
  const moduleAFactory = await rootInjector.get(Compiler).compileModuleAsync(Ng2AModule);
  return moduleAFactory.create(rootInjector);
});
```

## 🔥 Exception or Error
<pre><code>

</code></pre>

### Browser info
All browsers

**Comment by rockument69** [comment] 2020-05-28 22:32
@kapunahelewong : The problem is: "The sample uses the Angular Compiler to dynamically compile separate modules to downgrade. This does not work in the CLI when doing AoT, so it would be good to include a more production ready sample." I think we need engineering input for this, so adding that label.

**Comment by atscott** [comment] 2022-03-02 00:40
Closing since AngularJS and the upgrade module are nearing end of life. Realistically, we won't be prioritizing work in these areas.

**Closed by atscott** 2022-03-02 00:40 UTC
Labels: type: bug/fix, comp: docs, freq2: medium, state: needs eng input, comp: docs/api, comp: upgrade, triage #1, P4
