### ISSUE TITLE
404 on 'https://angular.dev/cli/commands' page

### ISSUE THREAD

**Issue by dan-laskowski** [angular/angular#52949] opened 2023-11-16 07:37 UTC
### Describe the problem that you experienced

Like I mentioned on the title - entering https://angular.dev/cli/commands website returns 404 page.

### Enter the URL of the topic with the problem

https://angular.dev/cli/commands

### Describe what you were looking for in the documentation

List of commands for angular cli

### Describe the actions that led you to experience the problem

1. Enter your favorite web browser
2. Type https://angular.dev/cli/commands and enter the page

### Add a screenshot if that helps illustrate the problem

![image](https://github.com/angular/angular/assets/13076235/ba2f6b86-33cf-464c-97f6-3d3cdd6f0d85)

### If the problem is browser-specific, please specify the device, OS, browser, and version

```true
No, I checked it on:
- Edge and Brave - Windows 11
- Chrome and Brave - Android 13
```

**Comment by JoostK** [comment] 2023-11-16 07:40
Thanks for the report, this is a duplicate of https://github.com/angular/angular/issues/52549, pending a new deployment.

**Closed by JoostK** 2023-11-16 07:40 UTC
