### ISSUE TITLE
docs: clarify ivy breaking change for `ngFor` and `<select>` with animations and no `trackBy`

### ISSUE THREAD

**Issue by rsheptolut** [angular/angular#35896] opened 2020-03-06 05:40 UTC
# 🐞 bug report

### Affected Package

 The issue seems to be related to package @angular/platform-browser

### Is this a regression?

 Yes, the previous version in which this bug was not present was: v8.* (8.2.14)

### Description

Upgrading to Angular v9 broke the functionality of `<select>` for us. The `*ngFor` directive we use for populating it with `<option>` elements now all of the sudden re-renders items if you simply refresh the collection with new instances, even if their contents are the same. This resets the selected option, which is not expected and not desirable. This wasn't happening in v8. This isn't happening in v9 either, *unless* `BrowserAnimationsModule` is imported by the `app-module`. This also can be worked around by using `trackBy`, but for that you'd need to track down all the problematic `ngFor` directives after upgrading to v9.

## 🔬 Minimal Reproduction

[Click here for v9 repro repository](https://github.com/rsheptolut/repro123)
[Click here to see the same v9 repro app in action](https://rsheptolut.github.io/repro123/)
[Same demo working without problems in Angular v8](https://angular-wqxppc.stackblitz.io) - although StackBlitz doesn't have this problem with v9 either (not sure why), but at least helps illustrate how it was working before

The v9 repro is based on `ng new` of Angular CLI 9.0.5. If building yourself, run locally with `ng serve`, because if imported into `StackBlitz`, the issue can't be reproduced.

1. Choose an item in any drop down (the two are linked and simply illustrate the `trackBy` difference)
2. Notice that the first button adds a new item but the selected option doesn't get reset.
3. Clicking the second button though resets the selected option in the first drop down.

## 🔥 Exception or Error
<pre><code>

 None

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.0.5
Node: 10.16.3
OS: win32 x64

Angular: 9.0.5
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.5
@angular-devkit/build-angular     0.900.5
@angular-devkit/build-optimizer   0.900.5
@angular-devkit/build-webpack     0.900.5
@angular-devkit/core              9.0.5
@angular-devkit/schematics        9.0.5
@ngtools/webpack                  9.0.5
@schematics/angular               9.0.5
@schematics/update                0.900.5
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
</code></pre>

**Anything else relevant?**
Happens only in Angular v9, when `BrowserAnimationsModule` is imported into `AppModule` and `ngFor` is not set up with `trackBy`.

**Comment by C0ZEN** [comment] 2020-03-06 11:02
I could not tell you if this is really a bug or a feature of the v9 nevertheless the `trackBy` feature is dedicated to avoid re-rendering the DOM to improve the performances.
It seems to me that you should have used a `trackBy` and your issue is in fact, a bad design from your project.

Even if Angular considers it as a bug, you should really use the `trackBy` anytime it is possible.

**Comment by xonuzofa** [comment] 2020-04-28 03:10
This is still happening on Angular 9.1.3.  Without using `trackBy`, when assigning a new list to the `*ngFor` list in a select, it sets the select back to the default value '', but the form contains the correct id and the formControlName is not working with select correctly.

**Comment by atscott** [comment] 2020-05-08 17:25
This appears to be related to the breaking change related to insertion order ([reference](https://angular.io/guide/ivy-compatibility)):

> Embedded views (such as ones created by *ngFor) are now inserted in front of anchor DOM comment node (e.g. ) rather than behind it as was the case previously. In most cases this does not have any impact on rendered DOM. In some cases (such as animations delaying the removal of an embedded view) any new embedded views will be inserted after the embedded view being animated away. This difference only last while the animation is active, and might alter the visual appearance of the animation. Once the animation is finished the resulting rendered DOM is identical to that rendered with View Engine.

In the stackblitz example, you can see that when Ivy is disabled, the new items are added to the front of the list (add a break on: subtree modifications to the dom). If you go to the settings in stackblitz and check the box to "Enable Ivy", you'll see that new items are added to the end of the list. To clarify, both Ivy and View Engine are re-rendering the items because you don't have `trackBy`. The difference is the location of the newly inserted items.
Because `BrowserAnimationsModule` queues up the removal of the old items in order to animate them, you will briefly have duplicate items in the list if you don't use `trackBy`. In the Ivy example, since the old being removed are above the new items, when they're removed, the browser sees this as the selected item being removed.
As a quick fix, I would recommend using `trackBy` to avoid this issue.

**Comment by matsko** [comment] 2020-05-27 19:42
@rsheptolut unfortunately the only way forward with this is to use `trackBy`. This API allows for the behavior to stay the same despite the internals of the framework changing.

**Comment by xonuzofa** [comment] 2020-05-27 20:05
How is this a valid solution to suggest using `trackBy`?  `BrowserAnimationsModule` breaks selects in Angular 9, this is new breaking changes.  Selects are used widely throughout all web applications.  `trackBy` has never been a necessity before, but all of a sudden is.  

I have 15 applications using Angular 9 that all inherited this issue and have no way to fix this without tremendous overhaul of all applications by adding `trackBy` functions on every single *ngFor.  

Angular team should not expect people who rely on Angular to rework their entire source code and have temporary work arounds when they break huge components of html!

**Comment by C0ZEN** [comment] 2020-05-27 20:18
RTFM. `trackBy` is one of the famous step forward the optimization of the DOM and has always been a very recommend step since as long as I aware of the `ngFor` directive. Let me prove it to you simply by linking the very first [ngx documentation about the ngFor](https://v2.angular.io/docs/ts/latest/guide/structural-directives.html#!#ngFor) showing in EACH example the `trackBy`. Hell maybe they should have made it required but there is always someone to complain. 
Yes there is a breaking change, yes this is unfortunate and yes the lack of communication is very bad but keep in mind that this is a feature to enhance your application.

**Comment by petebacondarwin** [comment] 2020-05-27 20:53
@matsko and @atscott - I wonder if it could be possible to identify such cases and provide a migration to help?

**Comment by xonuzofa** [comment] 2020-05-27 21:16
@C0ZEN  
> RTFM

Your rude comment is not appreciated.  

You do realize that instead of using `trackBy` to increase performance, on pages that 'need' performance enhancement, you can use `changeDetection: ChangeDetectionStrategy.OnPush` and `ChangeDetectorRef.detectChanges()` as needed to prevent DOM from reevaluating so much.  There is not a need for `trackBy` if you do the following.  

Theres more than 1 way to skin a cat.  Forcing us to use 1 way and not bothering to tell anyone is not what leading framework development teams should be doing.

**Comment by C0ZEN** [comment] 2020-05-27 21:26
@xonuzofa asking to read the doc is not rude.
About the changeDetection and the trackBy, I am pretty sure that combining both is better and they are not here as a choice like pick this one or that other one.
ChangeDetection with onpush will avoid to render the DOM for objects and arrays but once you detect the changes manually to trigger the change in the DOM that's the trackBy job to ensure to rebuild only the new items in the DOM that need a change.

**Comment by kara** [comment] 2020-05-27 21:28
I'm re-opening this issue while we discuss the best way to tackle this. This change was expected based on how Ivy works, but I agree the experience is confusing and there's probably a way to make it less painful for users.

**Comment by xonuzofa** [comment] 2020-05-27 22:07
Not sure exactly if this is possible since `select` is a standard html element, but what makes sense to me is treat `select` as though it's another angular component.  Components have `ngOnChanges()` which trigger when an `@Input` array address is changed.  

Would this not eliminate all issues with when and how often to render?  Only on address changes when `onChanges` triggers would Angular need to update the DOM.  This would inherently remove `trackBy` and would bring greater performance enhancements without essentially having to 'index' each `*ngFor` loop.  

I do not know how that would work with using <option *ngFor>, but another option is to use [items]="", etc.

**Comment by rsheptolut** [comment] 2020-05-27 22:10
If nothing else, let's just please make it easier for the user to migrate from v8 to v9 and avoid this bug. Could be an automatic migration by `ng update` or at least a warning that you have to do this manipulation yourself, because it did take quite some time to figure out, since not all of us are as smart as the almighty @C0ZEN

**Comment by theodorejb** [comment] 2020-05-27 23:10
It looks like PR #23784 also fixes this issue.

**Comment by Da13Harris** [comment] 2020-06-11 18:53
It looks like there's attention and progress on this bug. If a fix is found, is there any chance it could be introduced with a minor or patch update in the near future, since it's clearly a significant regression bug? Or would it more likely have to wait until the Angular 10 release?

I'm just trying to gauge the likelihood that it will be fixed within our development window, or whether I should be looking to implement trackBy in all the places where we have issues.

**Comment by petebacondarwin** [comment] 2021-05-21 16:59
It looks like this is a bug that requires a code fix, so removing the `comp:docs` label.

**Comment by petebacondarwin** [comment] 2021-05-24 15:42
Having discussed offline with @atscott - I now understand that this is part of how Angular works (by design) and it just happens that the browser didn't notice with View Engine, while it becomes obvious under Ivy.

Therefore this specific case needs to be listed more clearly in our Ivy breaking changes so that people can more quickly resolve their problem.

**Closed** 2021-05-27 18:12 UTC
Labels: comp: core, comp: docs
