### ISSUE TITLE
Angular pwa not working for ./

### ISSUE THREAD

**Issue by ganeshsundaram39** [angular/angular#36152] opened 2020-03-20 05:52 UTC
# 🐞 bug report

### Affected Package
ng add @angular/pwa

### Description

Angular pwa not working for ./ in offline mode but its working for ./index.html

![image](https://user-images.githubusercontent.com/25497778/77139585-91190580-6a9c-11ea-98e6-9bb22b916ef6.png)

## 🔬 Minimal Reproduction

repo:  https://github.com/ganeshsundaram39/ganeshsundaram39.github.io/tree/scully

not working for 
https://ganeshsundaram39.github.io/

but works for 
https://ganeshsundaram39.github.io/index.html

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.0.6
Node: 12.14.1
OS: win32 x64

Angular: 9.0.6
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.6
@angular-devkit/build-angular     0.900.6
@angular-devkit/build-optimizer   0.900.6
@angular-devkit/build-webpack     0.900.6
@angular-devkit/core              9.0.6
@angular-devkit/schematics        9.0.6
@ngtools/webpack                  9.0.6
@schematics/angular               9.0.6
@schematics/update                0.900.6
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
</code></pre>

**Comment by gkalpak** [comment] 2020-03-20 14:16
Going to https://ganeshsundaram39.github.io/ngsw/state (after having the ServiceWorker activated), I see the following debug info (see [here][1] for details on `/ngsw/state`):

```
NGSW Debug Info:

Driver state: EXISTING_CLIENTS_ONLY (Degraded due to: Hash mismatch (cacheBustedFetchFromNetwork): https://ganeshsundaram39.github.io/index.html: expected 900c53257790571dcf7663ddaa0ec3feaee62797, got 6b93dcbb09a8e4ea0175bb85cd3bbb08319d3a6b (after cache busting)
Error: Hash mismatch (cacheBustedFetchFromNetwork): https://ganeshsundaram39.github.io/index.html: expected 900c53257790571dcf7663ddaa0ec3feaee62797, got 6b93dcbb09a8e4ea0175bb85cd3bbb08319d3a6b (after cache busting)
    at PrefetchAssetGroup.<anonymous> (https://ganeshsundaram39.github.io/ngsw-worker.js:702:35)
    at Generator.next (<anonymous>)
    at fulfilled (https://ganeshsundaram39.github.io/ngsw-worker.js:323:62))
Latest manifest hash: 28dcf60a1bd07ca5a2bb14ad5febbd8af44fe4ab
Last update check: 1m2s858u

=== Version 28dcf60a1bd07ca5a2bb14ad5febbd8af44fe4ab ===

Clients: 

=== Idle Task Queue ===
Last update tick: 1m8s356u
Last update run: 1m3s354u
Task queue:


Debug log:

[3m50s634u] Error(Hash mismatch (cacheBustedFetchFromNetwork): https://ganeshsundaram39.github.io/index.html: expected 900c53257790571dcf7663ddaa0ec3feaee62797, got 6b93dcbb09a8e4ea0175bb85cd3bbb08319d3a6b (after cache busting), Error: Hash mismatch (cacheBustedFetchFromNetwork): https://ganeshsundaram39.github.io/index.html: expected 900c53257790571dcf7663ddaa0ec3feaee62797, got 6b93dcbb09a8e4ea0175bb85cd3bbb08319d3a6b (after cache busting)
    at PrefetchAssetGroup.<anonymous> (https://ganeshsundaram39.github.io/ngsw-worker.js:702:35)
    at Generator.next (<anonymous>)
    at fulfilled (https://ganeshsundaram39.github.io/ngsw-worker.js:323:62)) initializeFully for 28dcf60a1bd07ca5a2bb14ad5febbd8af44fe4ab
[3m16s788u] Ignoring invalid request: 'only-if-cached' can be set only with 'same-origin' mode Driver.fetch(https://ganeshsundaram39.github.io/, cache: only-if-cached, mode: no-cors)
[2m59u] TypeError(Failed to fetch, TypeError: Failed to fetch) Driver.fetch(https://ganeshsundaram39.github.io/)
[1m55s46u] TypeError(Failed to fetch, TypeError: Failed to fetch) Driver.fetch(https://ganeshsundaram39.github.io/ngsw.json?ngsw-cache-bust=0.829731350266063)
[1m55s46u] Check for update aborted. (Client or server offline.) 
```

What this basically means is that the `index.html` that is sent by the server is different than the `index.html` in your dist directory after `ng build`. Possibly because it has been subsequently processed by Scully?

Not sure how Scully is supposed to work with the ServiceWorker. I suggest you ask on their repo.
If Scully modifies the built files, you might need to re-run the script that generates the `ngsw.json` SW "manifest" with `./node_modules/.bin/ngsw-config dist/ganesh-sundaram-website ngsw-config.json`.
(This is normally run for you by `ng build` under the hood, but if you manually modify files afterwards, you can re-generate the `ngsw.json` manifest by running this command.)

##
I am going to close this, since everything works as intended here (afaict), but feel free to continue the discussion below.

(Also, if you open an issue on Scully, feel free to ping me there in case I can help by providing info on how `@angular/service-worker` works.)

[1]: https://angular.io/guide/service-worker-devops#locating-and-analyzing-debugging-information

**Closed by gkalpak** 2020-03-20 14:16 UTC
Labels: comp: service-worker
