### ISSUE TITLE
multiple root components with shared zone and base module

### ISSUE THREAD

**Issue by sod** [angular/angular#10681] opened 2016-08-11 12:54 UTC
**I'm submitting a ...**  (check one with "x")

```
[x] feature request
```

**Current behavior**

We don't have an SPA. And we can't go full SPA right now. So there are multiple root components placed in the DOM

``` html
<my-app1></my-app1>
<my-app2></my-app2>
```

``` typescript
@NgModule({
    imports: [ BrowserModule ],
    providers: [ MyService ],
})
export class BaseModule {
  ngDoBootstrap(applicationRef: ApplicationRef) {
    const zone = applicationRef.zone;
    platform._injector = applicationRef.injector;

    zone.runOutsideAngular(() => {
      // run several modules in same zone and with same parent injector
      platform._bootstrapModuleWithZone(AppModule1, [], zone);
      platform._bootstrapModuleWithZone(AppModule2, [], zone);
    });
  }
}

const platform = platformBrowserDynamic();

platform.bootstrapModule(BaseModule);
```

**Expected/desired behavior**

Have multiple root modules that share one base injector and zone. Don't have to override private properties and call private methods. Maybe a `applicationRef.bootstrapChildModule(AppModule1)` method.

**Reproduction of the problem**

Plunkr: http://plnkr.co/edit/80s1jvwrqH3a3YEuxz6D?p=preview

**What is the motivation / use case for changing the behavior?**

Not everyone that might want to switch to angular2 can go full single-page-app.
- **Angular version:** 2.0.0-rc.5

**Comment by vascofernandes** [comment] 2016-09-01 08:34
I would like to see this solved as well.

**Comment by sod** [comment] 2016-10-05 16:39
My current workaround/approach for angular2@2.0.1

With JIT:

```typescript
const platform = platformBrowserDynamic();

platform.bootstrapModule(BaseModule).then(function(module: NgModuleRef<any>) {
  const zone = module.injector.get(NgZone);
  platform._injector = module.injector;
  platform._bootstrapModuleWithZone(AppModule1, [], zone);
  platform._bootstrapModuleWithZone(AppModule2, [], zone);
});
```

With AOT:

```typescript
const platform = platformBrowser();

platform.bootstrapModuleFactory(BaseModuleNgFactory).then(function(module: NgModuleRef<any>) {
  const zone = module.injector.get(NgZone);
  platform._injector = module.injector;
  platform._bootstrapModuleFactoryWithZone(AppModule1NgFactory, zone);
  platform._bootstrapModuleFactoryWithZone(AppModule2NgFactory, zone);
});
```

http://plnkr.co/edit/pHeBYwXTe5fdXZJSfu1F?p=preview

**Comment by DzmitryShylovich** [comment] 2017-01-04 10:33
Duplicate of https://github.com/angular/angular/issues/7136

**Comment by DzmitryShylovich** [comment] 2017-02-03 19:13
@pkozlowski-opensource ☝️ duplicate

**Closed** 2017-02-04 10:11 UTC
Labels: comp: core & compiler, freq1: low, type: feature
