### ISSUE TITLE
Cli command reference is not available

### ISSUE THREAD

**Issue by arindamgit** [angular/angular#52951] opened 2023-11-16 08:01 UTC
### Describe the problem that you experienced

Tried to view angular cli reference page. Page was not found

### Enter the URL of the topic with the problem

https://angular.dev/cli/commands

**Comment by JoostK** [comment] 2023-11-16 08:31
Thanks for the report, this is a duplicate of https://github.com/angular/angular/issues/52549, pending a new deployment.

**Closed by JoostK** 2023-11-16 08:31 UTC
