### ISSUE TITLE
Use more than one CustomValueAcessor in one Input field

### ISSUE THREAD

**Issue by gentios** [angular/angular#16755] opened 2017-05-12 12:37 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I have created 2 directives with a CustomValueAcessor, and when I use them in an <input type="number"> field I got the following error:

> Error: Uncaught (in promise): Error: More than one custom value accessor matches form control with unspecified name attribute

**Expected behavior**
The input field should accept more than 2 CustomValueAcessor

**Minimal reproduction of the problem with instructions**

http://plnkr.co/edit/zPz40DNYmAO7mokJ09a9?p=preview

**Please tell us about your environment:**

> 
> "dependencies": {
> "@angular/animations": "^4.1.0",
> "@angular/cli": "^1.0.0-beta.28.3",
> "@angular/common": "^4.1.0",
> "@angular/compiler": "^4.1.0",
> "@angular/compiler-cli": "^4.1.0",
> "@angular/core": "^4.1.0",
> "@angular/forms": "^4.1.0",
> "@angular/http": "^4.1.0",
> "@angular/platform-browser": "^4.1.0",
> "@angular/platform-browser-dynamic": "^4.1.0",
> "@angular/platform-server": "^4.1.0",
> "@angular/router": "^4.1.0"
> }

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by BioPhoton** [comment] 2017-08-09 23:08
Hi!

Ran in the same issue. The related issue in TextMask says in one comment that it is not possible and there is no workaround. => https://github.com/text-mask/text-mask/issues/452#issuecomment-286585770

I cant beleive that there no solution for this. I was so happy to find an issue to this problem and now im really afraid that this is maybe not possible.

There is definitley the need for more than one ControlValueAccressor on the same control.

Could someone @kara @Toxicable clarify this?

**Comment by Toxicable** [comment] 2017-08-09 23:43
I don't think having 2 ValueAccessors make much sense.
I understand the use case in the OP, where you have 2 independent Accessors that you can combine at some point to make the final output.

However, I think conceptually you're thinking of Accessors incorrectly.
The Accessor is the connector between the native DOM element and the Control class.
Therefore if you have 2 accessors your first issue is: What ones goes first?
lets say you have 2 writeValue functions
```js
writeValue(value: string){ //percent
  this.el.nativeElement.value = parseFloat(value) / 100
}
writeValue(value: string){ //round
  this.el.nativeElement.value = parseFloat(value).toFixed(2)
}
```
then lets say you write the value `10.11`
if you call `percent` then `round` you will get `0.1011`
but if you call `round` then `percent` you will get `0.10`
Which are different values, given you could just adjust the functions so that they can accommodate values from the other but there could be a million other situations where this could happen with multiple Accessors so without some design that could fix these kinds of issues Multiple Accessors aren't a good idea for these kinds of use cases

**Comment by BioPhoton** [comment] 2017-08-10 07:06
Hi @Toxicable 

THX for your answer!!

I may have to reconsider my approaches in hooking into view and model value adjustments...

I ran into a lot of different problems with the ControlValueAcessor now. 
Let me outline one little problem of many i have now... :-D

I have created i.e. this lib: [angular-formatter-parser](https://github.com/BioPhoton/angular-formatter-parser)
Form my current point of view i consider this as the best "angular way" to implement fromatter/parser for angular. Now i'm facing the problem that if i use this directive on i.e. an input i lock a lot of other things out. I.e. using this lib in combination with [material design](https://github.com/angular/material2) modules or many other libs. Actually i would want to use [angular-alternative-validation](https://github.com/BioPhoton/angular-alternative-validation) together with the formater/parser lib.

Could you suggest a clean and "angular way" to solve my problem? In fact i believe i may miss understand the use of ControlValueAccessor. If you could clear my mind for this topic i could be very happy again, which i'm currently not... ;-)

Best Michael

**Comment by kara** [comment] 2017-08-10 17:10
Thanks @Toxicable for the answer; I was just coming over to say something similar. The current control value accessor system is not really made for this because there can only be one source of truth for processes like the final write of the value. That said, to @gentios and @BioPhoton's point, we *do* need a solution for allowing multiple formatters / parsers on a form control. 

We have an [open issue](https://github.com/angular/angular/issues/3009) for implementing a real formatters/parsers system in core Angular forms. It's definitely on my todo list to start on the design for this, as it's intimately connected to the reactive validator rewrite that's in-progress. I'm going to close this issue, as value accessors are working as intended, but please feel free to continue further discussion on formatters etc in the existing issue.

**Closed by kara** 2017-08-10 17:10 UTC
Labels: comp: forms

**Comment by remborg** [comment] 2017-12-20 13:30
As mentioned above, text-mask won't work with material2. A workaround is to use the vanilla version of text-mask:
1 - Import the library in your component 
`import * as textMask from "vanilla-text-mask/dist/vanillaTextMask.js";`
2 - Add your mask in the component and init your input (don't forget to import AfterViewInit and implement it to your component)
`
  mask = [ /[1-9]/, /\d/, /\d/];
  maskedInputController;

  @ViewChild("input", { read: ViewContainerRef }) public input;

  ngAfterViewInit(): void {
    setTimeout(() => {
      this.maskedInputController = textMask.maskInput({
        inputElement: this.input.element.nativeElement,
        mask: this.mask
      });
    });
  }

  ngOnDestroy() {
    this.maskedInputController.destroy();
  }
`
3 - in your template, make sure the input element has an #input attribute
`<mat-form-field class="input">
  <input matInput [matDatepicker]="picker" [(ngModel)]="selectedValue" #input>
  <mat-datepicker-toggle matSuffix [for]="picker"></mat-datepicker-toggle>
  <mat-datepicker #picker></mat-datepicker>
</mat-form-field>
`

**Comment by brandon1525** [comment] 2018-02-12 20:04
i have a solution with a directive using the solution of @remborg 
```
import { Directive, ElementRef, OnDestroy } from '@angular/core';
import * as textMask from 'vanilla-text-mask/dist/vanillaTextMask.js';

@Directive({
  selector: '[appMaskDate]'
})
export class MaskDateDirective implements OnDestroy {

  mask = [/\d/, /\d/, '/', /\d/, /\d/, '/', /\d/, /\d/, /\d/, /\d/]; // dd/mm/yyyy
  maskedInputController;

  constructor(private element: ElementRef) {
    this.maskedInputController = textMask.maskInput({
      inputElement: this.element.nativeElement,
      mask: this.mask
    });
  }

  ngOnDestroy() {
    this.maskedInputController.destroy();
  }

}
```
`<input matInput formControlName="FechaInicio" [matDatepicker]="FechaInicioRef" placeholder="Fecha Inicio" appMaskDate>`

**Comment by jogelin** [comment] 2018-03-12 11:56
@remborg @brandon1525 You had any issues with the synchronization between the text-mask value and the datepicker value ?

[I put an example on stackblitz to illustrate my issue](https://stackblitz.com/edit/angular-datepicker-custom-adapter?file=app%2Fdatepicker-type.component.ts)

If you type manually and quickly 14, you will see in the errors that the value is **14_/__/____** instead of **14/__/____**. If you continue, you will have **14/03/2018_**....which is indeed incorrect for the date picker but in your field the value is correct....

**Comment by ojuniorbezerra** [comment] 2018-03-22 13:14
@jogelin Could you solve it? I have this problem.

**Comment by jogelin** [comment] 2018-03-22 14:40
@ojuniorbezerra I fixed this with an ugly patch on the date picker component. 

I register on the input event of the field, then I call again the function `_onInput` of the datepicker.

You can find my fix here : [https://stackblitz.com/edit/angular-datepicker-custom-adapter-fixed?file=app%2Fdatepicker-type.component.ts](https://stackblitz.com/edit/angular-datepicker-custom-adapter-fixed?file=app%2Fdatepicker-type.component.ts)

**Comment by JulidaRocks** [comment] 2018-11-28 06:01
![image](https://user-images.githubusercontent.com/39371377/49132162-5c979e00-f2db-11e8-8a85-6f30a5a1f784.png)


@jogelin In your example the date that is saved is one day before the day I am typing, see screenshot.

**Comment by mohamed-badaoui** [comment] 2018-11-28 15:45
@JulidaRocks It's the same date, just in different format.
01/08/2019 it is with your locale format while 2019-07-31 ... is GTM/UTC format

**Comment by mohamed-badaoui** [comment] 2018-11-28 15:46
> ![image](https://user-images.githubusercontent.com/39371377/49132162-5c979e00-f2db-11e8-8a85-6f30a5a1f784.png)
> 
> @jogelin In your example the date that is saved is one day before the day I am typing, see screenshot.

@JulidaRocks It's the same date, just in different format.
01/08/2019 it is with your locale format while 2019-07-31 ... is GMT/UTC format

**Comment by ajaynarang** [comment] 2019-03-17 20:25
@jogelin do you have this patch implemented not using formly library. 

We are using angular 7 + material + ng-mask, which is giving this issue. Custom Directive add masking but keep throwing invalid date.

**Comment by dacrypt** [comment] 2019-04-26 01:15
I also have this issue. ionic4 + angular 7 + ngx-mask:
` <input matInput  [matDatepicker]="picker"  mask="XXX/X0/0000" formControlName="idIssueDate" required>
` 
results in:
`
ERROR Error: Uncaught (in promise): Error: More than one custom value accessor matches form control with unspecified name attribute
Error: More than one custom value accessor matches form control with unspecified name attribute
    at _throwError (forms.js:2144)
    at forms.js:2202
    at Array.forEach (<anonymous>)
    at selectValueAccessor (forms.js:2191)
    at new FormControlName (forms.js:5782)
    at createClass (core.js:22160)
    at createDirectiveInstance (core.js:22029)
    at createViewNodes (core.js:23255)
    at callViewAction (core.js:23571)
    at execComponentViewsAction (core.js:23490)
    at resolvePromise (zone.js:831)
    at resolvePromise (zone.js:788)
    at zone.js:892
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:423)
    at Object.onInvokeTask (core.js:17290)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:422)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:195)
    at drainMicroTaskQueue (zone.js:601)
`

**Comment by aemonge** [comment] 2019-06-13 10:45
Any updates in for this bug ?

**Comment by Erick-Zanetti** [comment] 2019-09-03 12:50
I resolve this using my CustomDateAdapter

`

    import { NativeDateAdapter } from '@angular/material/core';
    import { Injectable } from '@angular/core';
    import * as moment from 'moment';

    @Injectable()
    export class CustomDateAdapter extends NativeDateAdapter {
        useUtcForDisplay = true;

        format(date: Date): string {
            return moment(date).format('DD/MM/YYYY');
        }

        parse(value: any): Date | null {
            if (value && typeof value === 'string') {
                value = value.replace('_', '');
            }
            if (!moment(value, 'DD/MM/YYYY', true).isValid()) {
                return this.invalid();
            }
            return moment(value, 'DD/MM/YYYY', true).toDate();
        }
    }

`
