### ISSUE TITLE
Redirected to 'https://angular.dev/api/router/Routedata' but page not found

### ISSUE THREAD

**Issue by micun9** [angular/angular#56029] opened 2024-05-23 10:04 UTC
### Describe the problem that you experienced

After click on Routedata button on 'https://angular.dev/api/router/Data' I was redirected to 'https://angular.dev/api/router/Routedata' and got 'Page Not Found'

### Enter the URL of the topic with the problem

https://angular.dev/api/router/Data

**Comment by bougwal** [comment] 2024-05-23 11:19
This bug has a large impact in ADEV where links are referenced in the format x#y where the # is being skipped yielding broken references in multiple places: 

Current (broken): 

- https://angular.dev/api/router/Routernavigate 
- https://angular.dev/api/router/RoutercreateUrlTree

Expectation(working): 
- https://angular.dev/api/router/Router#navigate 
- https://angular.dev/api/router/Router#createUrlTree


It might be an dev-infra issue as per previous bugs with @ link 
__
@JeanMeche I know you are fast, let me know if you are already looking at it

**Comment by JeanMeche** [comment] 2024-05-23 11:26
The root of the issue is also related a TS bug, this time: microsoft/TypeScript#58259

Either we replace it with a manuel link or we wait for the upgrade to TS 5.5 which will is scheduled to be released in less than a month !

**Comment by JeanMeche** [comment] 2024-06-25 20:31
The fix is already visible here : https://next.angular.dev/api/router/Data

**Closed by JeanMeche** 2024-06-25 20:31 UTC
Labels: P2, area: adev
