### ISSUE TITLE
Memory leakage in SSR while using native node fetch

### ISSUE THREAD

**Issue by vz-tl** [angular/angular#56586] opened 2024-06-25 09:12 UTC
### Which @angular/* package(s) are the source of the bug?

ssr

### Is this a regression?

Yes

### Description

After upgrading our enterprise application to NG17, we also enabled native fetch on SSR using `withFetch()`. Once after deployment of  the upgraded application we encountered permanent memory  increase and finally the application restarting due to OOM. 

After investigating it became obvious that the heap space size only got exceeded when using native node fetch. Removing `withFetch()` fixed the problem. Below find a screeshot from Datadog monitoring, which nicely shows what happened over the past weeks.

![app_heap_space_usage_graph_4_weeks](https://github.com/angular/angular/assets/48031693/7e0713f8-b5d8-4047-ab50-2d24263606ad)

In order to exclude a dependency to the node version , we tried with several versions from v20 up to recent v22. The behaviour when using native fetch was reproducible.

Assuming that native node fetch will very likely become standard in future NG versions and the polyfill will become removed, this makes me a bit nervous when seeing our massive problems while using native fetch!

I won't provide a repo at this point, as it requires time preparing it and I am not sure if it will add value, because
* the issue is so obvious it actually must be known already (even though I'm wondering I didn't find anything related)
* I'm not fully sure if it is even related to Angular but rather a bug in node / undici implementation (found a lot of not cleaned up undici Timeout references between heap size snapshots)
* when providing a repro, the memory footprint for such example app is much smaller than with our enterprise app, so it will only be possible to recognize a memory increase by taking multiple memory snapshots while app is requesting data and comparing new instances created but not cleaned up between 2 snapshots.

That's why I first wanna post this issue in hope someone already knows the issue and might have an idea or direction what's causing it or even how to fix it. If still a repro would be required, let me know and I will try to provide one.

Kind regards,
Tobias

### Please provide a link to a minimal reproduction of the bug

--

### Please provide the exception or error you saw

```true
See above
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.3.5
Node: 20.11.0
Package Manager: npm 10.2.4
OS: linux x64

Angular: 17.3.5
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, google-maps, language-service, platform-browser
... platform-browser-dynamic, platform-server, router, ssr
... youtube-player

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1703.5
@angular-devkit/build-angular   17.3.5
@angular-devkit/core            17.3.5
@angular-devkit/schematics      17.3.5
@schematics/angular             17.3.5
ng-packagr                      17.3.0
rxjs                            7.8.1
typescript                      5.4.5
zone.js                         0.14.4
```

**Comment by JeanMeche** [comment] 2024-06-25 10:34
This reminds me of #55396 with a fix that will land in 18.1 (#55530). 
Can you make sure that optimization are enable on your prod build ? (for example you could check if the `ng` global is present on the browser console).

**Comment by vz-tl** [comment] 2024-06-25 10:42
@JeanMeche , you mean optimization in prod build config? Yes, it's configured with
```
 "optimization": {
          "scripts": true,
          ....
}
```

And `ng` is only available in a dev build but ont on prod. I found the issue you referred to during my initial research and it seems unrelated to me, as it apparently only happens while running a dev build. But we faced our issue on production, which increases criticality and urge to find a solution.

**Comment by alan-agius4** [comment] 2024-06-25 12:10
The above fix that was mentioned by @JeanMeche is included in 17.3.7. @vz-tl it unclear from your comments if you are using the application or server builder Angular CLI builder. Can you please share your `angular.json`?

**Comment by vz-tl** [comment] 2024-06-25 13:41
@alan-agius4 , we do pure runtime SSR (no pre-rendering) using v17 @angular/ssr package.

As we're in an NX  monorepo, we don't use angular.json but a project.json per app/lib. I cannot share the full project.json due to company restrictions, but below find the most important configs for the regular build and server target. 
```
{
  "name": "website",
  "$schema": "../../node_modules/nx/schemas/project-schema.json",
  "sourceRoot": "apps/website/src",
  "projectType": "application",
  "prefix": "website",
  "targets": {
    "build": {
      "executor": "@angular-builders/custom-webpack:browser",
      "options": {
        "index": "apps/website/src/index.html",
        "indexTransform": "apps/website/scripts/index.transform.js",
        "customWebpackConfig": {
          "path": "apps/website/webpack.extra.config.js"
        },
        "outputPath": "dist/apps/website/browser",
        "main": "apps/website/src/main.ts",
        "polyfills": "apps/website/src/polyfills.ts",
        "tsConfig": "apps/website/tsconfig.app.json",
        "webWorkerTsConfig": "apps/website/tsconfig.workers.json",
        "outputHashing": "none",
        "extractLicenses": false,
        "vendorChunk": false,
        "namedChunks": false,
        "aot": true,
        "sourceMap": {
          "scripts": true,
          "styles": true,
          "hidden": false,
          "vendor": false
        },
        "optimization": {
          "scripts": true,
          "styles": {
            "minify": true,
            "inlineCritical": false
          },
          "fonts": false
        },
        "assets": [...],
        "styles": [...],
        "stylePreprocessorOptions": {
          "includePaths": [...]
        },
        "scripts": [...]
      },
      "configurations": {
        ....
        "production": {
          "sourceMap": {
            "scripts": true,
            "styles": false,
            "hidden": true,
            "vendor": false
          },
          "buildOptimizer": true,
          "extractLicenses": true,
          "styles": [...],
          "budgets": [...]
        }
      }
    },
    "server": {
      "executor": "@angular-builders/custom-webpack:server",
      "options": {
        "customWebpackConfig": {
          "path": "apps/website/webpack.extra.config.js"
        },
        "outputPath": "dist/apps/website/server",
        "main": "apps/website/server.ts",
        "tsConfig": "apps/website/tsconfig.server.json",
        "externalDependencies": [...],
        "stylePreprocessorOptions": {
          "includePaths": [...]
        }
      },
      "configurations": {
        ...
        "production": {
          "sourceMap": false,
          "optimization": true
        }
      }
    },
  }
}
```
We are using `@angular-builders/custom-webpack` builder by adapting the build via custom webpack config, but in a non-impacting way wrt. the server build respectively totally unrelated to any issues with fetching data (what is the actual issue). So please don't take the fact of using a custom builder (not supported by Angular team) as a reason for current issue.

**Comment by alan-agius4** [comment] 2024-06-25 14:04
The configuration appears correct since both settings have `optimization` set to `true`. I trust that `@angular-builders/custom-webpack:server` is applying the appropriate options for the production configuration. Additionally, I recommend updating to the latest version of `@angular`, or at least to the latest patch, to see if the issue persists.

To further investigate this problem, we need a minimal reproduction. Could you please set one up?

You can read [here](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is necessary. A good way to create a minimal reproduction is to generate a new app using `ng new repro-app`, add the minimal code required to replicate the issue, then push this repository to GitHub and share the link here.

**Comment by vz-tl** [comment] 2024-06-28 16:18
@alan-agius4 , here we go: https://github.com/vz-tl/ng-fetch-leakage-repro

Please have a look at the README.md I created with instructions how to test. There's a test script which fires 1000 requests against the running app. The app itself will do a request from a testing API on the web, by using HttpClient.  Usually, I always run the test script 3-5 times in a row, after each time saving a memory snapshot.

Let's get one thing out of the way: I'm definitely not an expert in  debugging memory leaks! :D  Chrome inspector still is somewhat double Dutch to me. I tried my best to read something out of the memory snapshots.

Obviously,this super-tiny example app likely will never run OOM, compared to our real app, which of course has a much bigger memory footer print. But at least I see a clear tendency:

- using `withFetch()` seems to increase the heap size much more than without.
- there are are much more not removed instances like `Document2`, `R3Injector`, `core_NGZone` (which looks to me they could belong to not garbage collected application instances)
- quite obvious is the amount of `undici` Timeout references, wich is not present at all when not using node fetch. Not sure those leftover could be cause by a  bug with native fetch leading to leakage.

I'd be glad if you could have a look and I hope I'm not totally on the wrong track.

**Comment by alan-agius4** [comment] 2024-07-01 08:51
@vz-tl, thanks for the reproduction. The first thing I noticed is that you are generating a development build. I switched to using the production build with `ng run leakage-repro-app:server:production` and ran the tests along with several memory snapshots. After running the tests four times, the memory usage remained around 14.1-14.3 MB. I also switched to using `XHR` instead of `fetch`, and the memory usage stayed within this range as well.
 
It's important to manually force garbage collection (GC) before taking memory snapshots. Can you confirm if you're doing this?

When handling numerous requests, it's normal for memory usage to increase and stay elevated; this doesn't necessarily indicate a memory leak. V8 tends to delay memory cleanup under CPU pressure until it's absolutely necessary, often after transferring memory to the old space.

I noticed in your screenshot that the memory usage reaches 640 MB, leading to an OOM. Assuming your production environment is running in a container, ensure that the --max-old-space-size aligns with the container's memory limit. Otherwise, the application might encounter out-of-memory (OOM) errors.

**Comment by YnsSev** [comment] 2024-07-01 13:51
@vz-tl removing `WithFetch()` resolved this for you? We currently updated Angular from 15 to 17 and started using `WithFetch()`. On the server the memory usage is also increasing until ~4GB after which OOM occurs and the process restarts. But after removing `WithFetch()` and reverting to `XHR` this is still happening. This behavior was not observed when we ran on Angular 15.

**Comment by SebastianKohler** [comment] 2024-07-02 11:20
We also have an Angular (18.0.3) SSR production app which has a memory leak we haven't been able to resolve. We added `withFetch()` in January, but I'm not sure if we had memory issues before that. We'll remove `withFetch()` and see if it makes a difference in our app. We are using the `@angular-devkit/build-angular:browser` and `@angular-devkit/build-angular:server` builders.

**Comment by alan-agius4** [comment] 2024-07-02 12:36
@vz-tl, I looked at it again and successfully replicated the issue with your reproduction. I'm not sure why I couldn't see it before. Unfortunately, I didn't have time to investigate further today, but I'll continue looking into it in the coming days.

**Comment by alan-agius4** [comment] 2024-07-03 07:22
I managed to pinpoint the cause of the issue. It seems that `zone.js` is not interacting well with `undici`, the internal library used by Node.js for handling `fetch` operations.

I confirmed this with the following code:

```js
import "zone.js/node";
import { fetch } from "undici";

(async () => {
  for (let i = 0; i <= 100; i++) {
    console.log(i + 1);
    await fetch("https://reqres.in/api/users");
  }

  setTimeout(() => {}, 50_000);
})();
```

In the memory snapshot, we can observe 153 instances of `Timeout`:
<img width="712" alt="Screenshot 2024-07-03 at 09 17 17" src="https://github.com/angular/angular/assets/17563226/b2a680b9-1c7b-4e41-b8c5-d4b87c9f5c3f">

However, removing `zone.js` results in no additional `Timeout` instances:
<img width="833" alt="Screenshot 2024-07-03 at 09 22 14" src="https://github.com/angular/angular/assets/17563226/20fadde4-5514-4906-90ed-fedfad7ef4fb">

**Closed** 2024-07-16 19:46 UTC
Labels: memory leak, area: zones, area: server, area: common/http, state: has PR

**Comment by JeanMeche** [comment] 2024-07-17 21:16
Please note that zone 0.14.8 has been released and should land a fix for the memory leak.

**Comment by vz-tl** [comment] 2024-07-17 21:26
Thx for the work, @alan-agius4 ! Will report back ASAP!

**Comment by vz-tl** [comment] 2024-07-19 08:19
Tests on staging system went successfully. However, due to not being able to simulate same load as on prod, a final verification will only be possible once we deployed to production. Still I'm confident the issue is fixed now. Thx again to all involved!
