### ISSUE TITLE
RC5 Breaking Change - Http UMD 

### ISSUE THREAD

**Issue by robinkedia** [angular/angular#10612] opened 2016-08-09 21:31 UTC
**I'm submitting a ...**  (check one with "x")
```
[ X] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Post RC5 upgrade, facing below error -

> platform-browser.umd.js:937 EXCEPTION: TypeError: Cannot read property 'toString' of nullBrowserDomAdapter.logError @ platform-browser.umd.js:937BrowserDomAdapter.logGroup @ platform-browser.umd.js:947ExceptionHandler.call @ core.umd.js:4389next @ core.umd.js:9971schedulerFn @ core.umd.js:9168SafeSubscriber.__tryOrUnsub @ Subscriber.ts:240SafeSubscriber.next @ Subscriber.ts:192Subscriber._next @ Subscriber.ts:133Subscriber.next @ Subscriber.ts:93Subject._finalNext @ Subject.ts:154Subject._next @ Subject.ts:144Subject.next @ Subject.ts:90EventEmitter.emit @ core.umd.js:9156onError @ core.umd.js:9394onHandleError @ core.umd.js:9266ZoneDelegate.handleError @ zone.js:327Zone.runTask @ zone.js:259drainMicroTaskQueue @ zone.js:474ZoneTask.invoke @ zone.js:426
> platform-browser.umd.js:937 STACKTRACE:BrowserDomAdapter.logError @ platform-browser.umd.js:937ExceptionHandler.call @ core.umd.js:4391next @ core.umd.js:9971schedulerFn @ core.umd.js:9168SafeSubscriber.__tryOrUnsub @ Subscriber.ts:240SafeSubscriber.next @ Subscriber.ts:192Subscriber._next @ Subscriber.ts:133Subscriber.next @ Subscriber.ts:93Subject._finalNext @ Subject.ts:154Subject._next @ Subject.ts:144Subject.next @ Subject.ts:90EventEmitter.emit @ core.umd.js:9156onError @ core.umd.js:9394onHandleError @ core.umd.js:9266ZoneDelegate.handleError @ zone.js:327Zone.runTask @ zone.js:259drainMicroTaskQueue @ zone.js:474ZoneTask.invoke @ zone.js:426
> platform-browser.umd.js:937 TypeError: Cannot read property 'toString' of null
>     at Request.Body.text (http.umd.js:1138)
>     at Request.getBody (http.umd.js:1720)
>     at Observable.eval [as _subscribe] (http.umd.js:1419)
>     at Observable.subscribe (Observable.ts:93)
>     at Observable._subscribe (Observable.ts:152)
>     at MapOperator.call (map.ts:54)
>     at Observable.subscribe (Observable.ts:93)
>     at Observable._subscribe (Observable.ts:152)
>     at CatchOperator.call (catch.ts:32)
>     at Observable.subscribe (Observable.ts:93)BrowserDomAdapter.logError @ platform-browser.umd.js:937ExceptionHandler.call @ core.umd.js:4392next @ core.umd.js:9971schedulerFn @ core.umd.js:9168SafeSubscriber.__tryOrUnsub @ Subscriber.ts:240SafeSubscriber.next @ Subscriber.ts:192Subscriber._next @ Subscriber.ts:133Subscriber.next @ Subscriber.ts:93Subject._finalNext @ Subject.ts:154Subject._next @ Subject.ts:144Subject.next @ Subject.ts:90EventEmitter.emit @ core.umd.js:9156onError @ core.umd.js:9394onHandleError @ core.umd.js:9266ZoneDelegate.handleError @ zone.js:327Zone.runTask @ zone.js:259drainMicroTaskQueue @ zone.js:474ZoneTask.invoke @ zone.js:426
> zone.js:463 TypeError: Cannot read property 'toString' of null(…)consoleError @ zone.js:463drainMicroTaskQueue @ zone.js:477ZoneTask.invoke @ zone.js:426

 **Angular version:** 2.0.0-rc.5
 
* **Browser:** [all] 
 
* **Language:** [all | TypeScript 1.8.10 |  ES5]

**Comment by goldibex** [comment] 2016-08-09 21:59
I get this error also on HTTP requests:

```
browser_adapter.ts:82 TypeError: Cannot read property 'toString' of null
    at Request.Body.text (body.ts:56)
    at Request.getBody (static_request.ts:152)
    at Observable.eval [as _subscribe] (xhr_backend.ts:134)
    at Observable.subscribe (Observable.ts:93)
    at Object.subscribeToResult (subscribeToResult.ts:32)
    at SwitchMapSubscriber._innerSub (switchMap.ts:109)
    at SwitchMapSubscriber._next (switchMap.ts:101)
    at SwitchMapSubscriber.Subscriber.next (Subscriber.ts:93)
    at FirstSubscriber._emitFinal (first.ts:140)
    at FirstSubscriber._emit (first.ts:124)

BrowserDomAdapter.logError @ browser_adapter.ts:82
ExceptionHandler.call @ exception_handler.ts:62
next @ application_ref.ts:362
schedulerFn @ async.ts:95
SafeSubscriber.__tryOrUnsub @ Subscriber.ts:240
SafeSubscriber.next @ Subscriber.ts:192
Subscriber._next @ Subscriber.ts:133
Subscriber.next @ Subscriber.ts:93
Subject._finalNext @ Subject.ts:154
Subject._next @ Subject.ts:144
Subject.next @ Subject.ts:90
EventEmitter.emit @ async.ts:80
onError @ ng_zone.ts:142
onHandleError @ ng_zone_impl.ts:95
ZoneDelegate.handleError @ zone.js:327
Zone.runTask @ zone.js:259
ZoneTask.invoke @ zone.js:423
```

**Comment by goldibex** [comment] 2016-08-09 22:00
And I've double-checked that the response did, in fact, have body text.

**Comment by goldibex** [comment] 2016-08-09 22:02
Ah, but the _request_ didn't, because it was a GET.

**Comment by goldibex** [comment] 2016-08-09 22:17
For me, this turned out to be because I use `Http#request` directly with a `RequestOptionsArgs` that I constructed myself. I tried explicitly setting an empty body (`body: ""`) and everything works again.

**Comment by robinkedia** [comment] 2016-08-09 22:28
@goldibex - Could you please help share some sample code so I can understand better. Appreciate your help. Thanks!

**Comment by qdouble** [comment] 2016-08-09 22:32
basically, if you're using request options, you have to make a get request, you can't leave the body empty.

```
options = new RequestOptions({
    body: '',
    headers: this.noPreFlightHeaders,
    withCredentials: true
  });
```

**Comment by robinkedia** [comment] 2016-08-09 22:36
@qdouble @goldibex - What has changed from RC4 to RC5 that we have to explicitly set body to ''. Thanks!

**Comment by robwormald** [comment] 2016-08-09 22:38
this would be an easy PR if anybody wants to fix

**Comment by qdouble** [comment] 2016-08-09 22:39
@robinkedia it's not documented, but it must have been one of the recent commits to http. I see rob has just labeled it as a bug.

**Comment by robinkedia** [comment] 2016-08-09 23:08
@goldibex @qdouble - Thanks, I have temporarily fixed this using body:''

**Comment by nukuuk** [comment] 2016-08-11 01:21
Can somebody show me how to use RequestOptions with a get request with **body:''**.  Here is what was working until I upgraded to RC5:
> let headers = new Headers();
        headers.append("Content-Type", "application/json");
        headers.append("Authorization", "Bearer " + this.globalEventsManager.authentication.token);
let get: Observable<ISomeDef[]> = this.http.get(url, { headers: headers }).map((response) => {//do something etc});

**Comment by goldibex** [comment] 2016-08-11 01:45
In your call to this.http.get, in the options object (the second argument,
for which you currently have { headers: headers }), add another property
body: "".

**Comment by nukuuk** [comment] 2016-08-11 02:15
@goldibex aaah ok, many thanks, worked like a charm!

**Comment by 790** [comment] 2016-08-11 16:04
This bug seems to only occur when a Content-Type header is set. Here is a minimal reproduction of the problem.
http://plnkr.co/edit/uMQlKO7RKvyRVJ2Y1L6v?p=preview

**Comment by vapits** [comment] 2016-08-11 16:10
Remove `headers.append("Content-Type", "application/json");` and it works.

**Comment by GrantGochnauer** [comment] 2016-08-11 21:12
I am running into the same issue when upgrading to RC5. 

This code fails because I am supplying headers:
`read():Observable<ConfigureOption> {
        let headers = new Headers();
        headers.append('Content-Type', 'application/json');
        let options = new RequestOptions({ headers: headers });

        return this.http.get('/readConfiguration', options)
            .map(this.extractData)
            .catch(this.handleError);
    }`

This code works but fails on the back-end because it expects the content-type header:
`read():Observable<ConfigureOption> {
        return this.http.get(url)
            .map(this.extractData)
            .catch(this.handleError);
    }`

**Comment by DavidRSchaller** [comment] 2016-08-12 00:49
The following work-around seems to resolve the issue: 
`
let options = new RequestOptions({ headers: headers, body: '' });
`

**Comment by pkozlowski-opensource** [comment] 2016-08-12 09:58
This is already fixed in master (7cd4741).

**Closed by pkozlowski-opensource** 2016-08-12 09:58 UTC
Labels: comp: http, hotlist: community-help, type: bug

**Comment by isaacplmann** [comment] 2016-08-15 13:36
Note that if you are automatically adding headers (like an auth token) to all http verbs, putting a value for `body` in the `options` parameter will override the the value for the `body` parameter.  
Example:

```js
class BearerAuthInterceptorNg2 extends Http {
  public get(url: string, options?: RequestOptionsArgs): Observable<Response> {
    // must set options.body = '' to work around this bug
    return this.intercept(super.get(url, this.getRequestOptionsArgs(options)));
  }

  public post(url: string, body: string, options?: RequestOptionsArgs): Observable<Response> {
    // setting options.body = '' will override the body parameter in super.post
    return this.intercept(super.post(url, body, this.getRequestOptionsArgs(options)));
  }
}
```

**Comment by yves-s** [comment] 2016-08-16 09:12
In my case it was `'Content-Type': 'application/json'` on a *get* request. Makes sense it isn't allowed/required but had it in my default headers.

Found the hint here: [Stackoverflow - Unable to make http request with Angular 2 rc5](http://stackoverflow.com/questions/38908973/unable-to-make-http-request-with-angular-2-rc5)

**Comment by isaacplmann** [comment] 2016-08-16 13:12
@yves-s - You're right.  If you specify `Content-Type` and no `body` rc5 will complain.  I was fixing it by adding an empty body, but removing the `Content-Type` header is better.

**Comment by golechwierowicz** [comment] 2016-08-16 13:15
how to fix this when working with post?

**Comment by isaacplmann** [comment] 2016-08-16 13:18
You shouldn't have a problem with post.  Just make sure not to set `options.body = ''` which will override whatever body you set in `Http.post(url, body, options)`

**Comment by dope9967** [comment] 2016-08-17 19:12
My problem was pretty stupid - bad code here:
`delete(upload: UplordUpload){
        let headers = new Headers();
        headers.append('Content-Type', 'application/json');

        let url = `${this.fileServiceUrl}/${upload.id}`;

        return this.http
            .delete(url, {headers: headers})
            .toPromise()
            .catch(this.handleError);
    }`

http.delete does not actually send any data, but since I copy/pasted from post method, I left the header part. Just don't pass any headers in case like this. This was dumb of me, but maybe an invalid header error would be cool :)

**Comment by gtsopour** [comment] 2016-08-29 11:34
Also for me same issue that was caused from the 'Content-Type': 'application/json' in the headers. Just removed it and everything seems ok.

**Comment by jakehowell** [comment] 2016-09-02 22:02
Same here. It's definitely the 'Content-Type' in the headers for GET requests. Thanks for posting that solution @yves-s.

**Comment by ghatul** [comment] 2016-09-04 11:41
After migration of my project rc4 to rc5 ,i stuck with this   

zone.js?1472988368674:478 Unhandled Promise rejection: Cannot read property 'toString' of null ; Zone: angular ; Task: Promise.then ; Value: TypeError: Cannot read property 'toString' of null(…) TypeError: Cannot read property 'toString' of null
    at Request.Body.text (http://localhost:5555/node_modules/@angular/http/bundles/http.umd.js:1138:30)
    at Request.getBody (http://localhost:5555/node_modules/@angular/http/bundles/http.umd.js:1720:33)
    at Observable.eval [as _subscribe] (http://localhost:5555/node_modules/@angular/http/bundles/http.umd.js:1419:41)
    at Observable.subscribe (http://localhost:5555/node_modules/rxjs/Observable.js:52:62)
    at Observable._subscribe (http://localhost:5555/node_modules/rxjs/Observable.js:109:28)
    at DoOperator.call (http://localhost:5555/node_modules/rxjs/operator/do.js:62:23)
    at Observable.subscribe (http://localhost:5555/node_modules/rxjs/Observable.js:52:38)
    at Observable._subscribe (http://localhost:5555/node_modules/rxjs/Observable.js:109:28)
    at CatchOperator.call (http://localhost:5555/node_modules/rxjs/operator/catch.js:29:23)
    at Observable.subscribe (http://localhost:5555/node_modules/rxjs/Observable.js:52:38)
