### ISSUE TITLE
RC1 too many javascript files to load!

### ISSUE THREAD

**Issue by adamwuyu** [angular/angular#8591] opened 2016-05-11 11:49 UTC
Hi, we've prepared ourselves for angular2 a while, and decided to use the RC1 version for our new projects. But RC1 is loading hundreds of javascript files. Is this a feature mean to be? Or it will be solved soon? About when?

Thank you for your attention.

**Comment by ajayambre** [comment] 2016-05-11 11:53
Possible duplicate of [#8542: over 290 xhr requests to bootstrap hello world app (many duplicated)](https://github.com/angular/angular/issues/8542)

**Comment by kylecordes** [comment] 2016-05-11 14:45
Release candidates 0/1 are a notable reorganization of how we consume Angular in applications, so there is a temporary setback in terms of all of us having tooling in place to do so with a modest number of files. But the situation is not really any different than before. Although the quick start shows a way to run it where you do get hundreds of separate HTTP requests, there are other examples already out there showing:

* a couple of dozen requests (by using SystemJS to load UMD bundled shipped in the box)
* Webpack - as few files as you like
* SystemJS Bundler works well also, to as few files as you like
* Work in progress on the CLI to handle all this with one command

**Comment by mhevery** [comment] 2016-05-13 01:50
@adamwuyu It seems to me that you are not using bundles. See example of bundle set up here: http://plnkr.co/edit/6qKhdlpauky7D8DGWLpx 

We are targeting two kinds of customers

1. Easy set up => Use UMD bundles as shown here: http://plnkr.co/edit/6qKhdlpauky7D8DGWLpx
2. Super Small => Still working on tools to bundle and tree shake into a single file. See the dome here: https://youtu.be/bSssb9AmiJU?t=25m25s

So I think you are using this incorrectly, and so I will close the issue.

**Closed by mhevery** 2016-05-13 01:50 UTC

**Comment by adamwuyu** [comment] 2016-05-13 05:31
@mhevery I was mis led by the quick start project. By now I am using Angular CLI to solve this:

> ng build -prod 

Thank you for your information.
