### ISSUE TITLE
Input number validation and letter 'e'

### ISSUE THREAD

**Issue by sylvainpolletvillard** [angular/angular#12042] opened 2016-10-03 13:38 UTC
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

User can type letter "e" in input type="number" fields and any value containing one or many letters "e" is considered valid. Also, having letters "e" in input breaks pattern validation.

**Expected behavior**
I assume it is possible to use *exponential notation* in number inputs, but the value still should be tested as a valid number, and pattern validation still should be applied.

**Minimal reproduction of the problem with instructions**

http://plnkr.co/edit/1aQRuixe6f9bzN0Wf2RU?p=preview

1. Try to type "eeeeeeeeee". This is considered a valid number
2. Try to type "123456". Pattern validation works as intended and the field is invalid
3. Now add letter 'e' : "123456e". The field is now considered valid
4. Conclusion: Letter 'e' is not taken in account for number validation and breaks pattern validation.

**What is the motivation / use case for changing the behavior?**

This is a silent failure in the validation process of number inputs, that currently needs to be manually adressed with input event handlers.

**Please tell us about your environment:** Windows 7

* **Angular version:** 2.0.0

* **Browser:** Chrome 53

 
* **Language:** all

**Comment by DzmitryShylovich** [comment] 2016-10-03 14:18
http://stackoverflow.com/a/31706796

**Comment by arciisine** [comment] 2016-10-03 14:51
Per the stackoverflow link, that would explain why a single 'e' is allowed, but not why 'eeeeeeee' is allowed as that shouldn't be a valid number.  The 'eeeeeee' input is allowed in Chrome  (with and without angular) but breaks in firefox.  Firefox does not like the input with an 'e' unless its a single 'e' and followed by at least one number.

**Comment by sylvainpolletvillard** [comment] 2016-10-03 14:59
Firefox 47 let the user enter 'eeeeee' but consider the field invalid as shown by the red outline. But Angular still consider the field valid. I think this is related with https://github.com/angular/angular/issues/2962

**Comment by pkozlowski-opensource** [comment] 2016-10-05 19:06
The crux of the issue is here: https://github.com/angular/angular/blob/ec3a5b54dea3fa296fd782257dbc02ba46965ea1/modules/%40angular/forms/src/directives/number_value_accessor.ts#L53

Passing invalid number (`e`, `eeee` etc.) will result in NaN being propagated to the control's value. The `NumberValueAccessor` has not validation mechanism built in and your pattern validator isn't taking NaN into account (not surprising). So no one is validating the invalid-number, really.

A proper solution will come from #2962. For now you can write a custom validator: http://blog.thoughtram.io/angular/2016/03/14/custom-validators-in-angular-2.html

Closing as a duplicate of #2962

**Closed by pkozlowski-opensource** 2016-10-05 19:06 UTC
Labels: comp: forms
