### ISSUE TITLE
Support @Input(), @Output(), @HostBinding() defined in superclasses and mixins

### ISSUE THREAD

**Issue by zoechi** [angular/angular#6953] opened 2016-02-08 17:12 UTC
Lifecycle interfaces implementations in superclasses seem to be already supported (https://github.com/angular/angular/pull/4222)

It would be great for `@Input()`, `@Output()`, `@HostBinding()` to also be supported for reusable implementations (like behaviors in Polymer).

**Comment by laco0416** [comment] 2016-02-09 03:17
+1

**Comment by zoechi** [comment] 2016-02-10 06:57
Support for lifecycle interface implementations in superclasses will be reverted :-(

**Comment by kegluneq** [comment] 2016-02-10 20:49
To clarify: in Dart, support for inheriting lifecycle hooks from superclasses is currently implemented in dev mode, but not in transformed model. This leads to inconsistent behavior between dev and transformed mode.

For reasons explained in the [transformer design doc][], we want to avoid global resolution in the transformer, so we do not implement this in transformed code. As a result, we will revert support in dev mode to avoid the inconsistent behavior.

https://github.com/angular/angular/pull/6879 introduces a dev-mode check which will alert users to missing `implements <hook_interface>` clauses. We are working on a way to make inheriting hooks from superclasses work, but do not have an agreed-upon design right now.

[transformer design doc]: https://docs.google.com/document/d/1Oe7m96QnOrilxpH1B5o9G_PnfBGovhH-n_o7RU6LYII/edit#heading=h.8kxtxfm4leo6

**Comment by zoechi** [comment] 2016-02-10 21:26
Ok, sounds promising :)

**Comment by pkozlowski-opensource** [comment] 2016-10-04 09:59
Closing as a duplicate of #11606. If there is a specific use-case to be added please comment on #11606.

**Closed by pkozlowski-opensource** 2016-10-04 09:59 UTC
