### ISSUE TITLE
UpgradeAdapter: Issue with `hasOwnProperty`

### ISSUE THREAD

**Issue by marcalj** [angular/angular#9030] opened 2016-06-05 18:02 UTC
- **I'm submitting a ...**
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

**Current behavior**
https://github.com/angular/angular/blob/bb8976608db93b9ff90a71187608a4390cbd7a07/modules/%40angular/upgrade/src/angular_js.ts#L141

`window.hasOwnProperty('angular')` is false
`!!window.angular` is true

![image](https://cloud.githubusercontent.com/assets/63667/15807192/96f73cde-2b57-11e6-8793-5a96d4da4850.png)

Had to change the code manually in order to use the upgrade adapter.

**Expected/desired behavior**
`window.hasOwnProperty('angular')` is true
`!!window.angular` is true
- **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
  https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).
- **What is the expected behavior?**
- **What is the motivation / use case for changing the behavior?**
- **Please tell us about your environment:**
- **Angular version:** 2.0.0-rc.1
- **Browser:** tested in Chrome and Firefox latest versions 
- **Language:** TypeScript 1.9.0-dev.20160605-1.0 with **SystemJS** module loader

Related: https://github.com/angular/angular/issues/6165

**Comment by marcalj** [comment] 2016-06-16 07:21
Same with rc2 and ng1.5.7
![image](https://cloud.githubusercontent.com/assets/63667/16108513/c403254a-33a3-11e6-8699-b99297ba3884.png)

**Comment by marcalj** [comment] 2016-09-05 08:24
Just FYI, still happens with RC6.

**Comment by petebacondarwin** [comment] 2016-12-23 11:41
duplicate of #6165

**Closed by petebacondarwin** 2016-12-23 11:41 UTC
Labels: comp: upgrade/dynamic
