### ISSUE TITLE
control flow migration fails when ng-container has ngIf

### ISSUE THREAD

**Issue by gmfun** [angular/angular#52295] opened 2023-10-20 09:37 UTC
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

Below code
```
<ng-container *ngIf="errorMessage(); else success">
            <div class="alert alert-error">
              {{ errorMessage() }}
            </div>
          </ng-container>
          <ng-template #success>
            <securezapp-step-validation-loader
              [loading]="checkRoleMutation().isLoading || updateAccount().isLoading"
            >
              Verifying IAM role creation
            </securezapp-step-validation-loader>
          </ng-template>
```

Is transformed to
```
@if (errorMessage()) {<ng-container>
            <div class="alert alert-error">
              {{ errorMessage() }}
            </div>
          </ng-container>} @else {
            <securezapp-step-validation-loader
              [loading]="checkRoleMutation().isLoading || updateAccount().isLoading"
            >
              Verifying IAM role creation
            </securezapp-step-validation-loader>
          }
```

`<ng-container>` should not be there

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.0.0-rc.0
Node: 20.7.0 (Unsupported)
Package Manager: yarn 1.22.19
OS: darwin arm64

Angular: 17.0.0-rc.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.0-rc.0
@angular-devkit/build-angular   17.0.0-rc.0
@angular-devkit/core            17.0.0-rc.0
@angular-devkit/schematics      17.0.0-rc.0
@angular/cdk                    16.2.4
@schematics/angular             16.2.1
ng-packagr                      16.2.2
rxjs                            7.8.1
typescript                      5.1.6
zone.js                         0.13.1
```

**Comment by crisbeto** [comment] 2023-10-20 09:59
`<ng-container>` does affect the behavior of the template so I think it's correct that it's still there. E.g. removing it may change the content projection behavior.

**Comment by pkozlowski-opensource** [comment] 2023-10-20 10:29
> <ng-container> does affect the behavior of the template so I think it's correct that it's still there. E.g. removing it may change the content projection behavior.

This is a good discussion. WE might potentially be able to remove `<ng-container>` that are empty

**Comment by pkozlowski-opensource** [comment] 2023-10-23 12:02
One additional data point: there is a common pattern involving `<ng-container>`, control flow and content projection, ex.:

```html
<ng-container *ngIf="conditionExp" ngProjectAs="some-selector">
    ...
</ng-container>
```

Notice the usage of `ngProjectAs` - again, in this case we can't remove `<ng-container>` as it wraps content to be projected as one block.

**Comment by jessicajaniuk** [comment] 2023-11-06 14:17
This use case (where no more attributes are on the ng-container) is one we normally remove the ng-container. So I'm not sure why it didn't. I'll add this as a test case.

**Comment by jessicajaniuk** [comment] 2023-11-06 15:00
@gmfun I just added a test with this exact use case in the issue, and the test passes and removes the container as expected. So this suggests it's possibly something else going on in your template that's interfering. Can you share a more complete reproduction of your template?

**Comment by jessicajaniuk** [comment] 2023-11-07 20:11
I'm going to close this as resolved, since we've verified that this case is handled.

**Closed by jessicajaniuk** 2023-11-07 20:11 UTC
Labels: needs reproduction, area: migrations, core: control flow
