### ISSUE TITLE
HttpParams of New HttpClient Doesn't Support Number, Boolean and Date

### ISSUE THREAD

**Issue by Halfist** [angular/angular#23856] opened 2018-05-11 14:41 UTC
## I'm submitting a...
```
[x] Regression (a behavior that used to work and stopped working in a new release)
```

## Current behavior
```
ERROR in /path/to/heroes.service.ts(23,44): error TS2345: Argument of type '{ params: { groupId: number; }; }' is not assignable to parameter of type '{ headers?: HttpHeaders | { [header: string]: string | string[]; }; observe?: "body"; params?: Ht...'.
  Types of property 'params' are incompatible.
    Type '{ groupId: number; }' is not assignable to type 'HttpParams | { [param: string]: string | string[]; }'.
      Type '{ groupId: number; }' is not assignable to type '{ [param: string]: string | string[]; }'.
        Property 'groupId' is incompatible with index signature.
          Type 'number' is not assignable to type 'string | string[]'.
```

## Expected behavior
No errors should occur.

## Minimal reproduction of the problem with instructions
```
// heroes-query-params.model.ts
export class HeroesQueryParams {
    groupId: number;
    country: string;
    dead: boolean;
}

// heroes.component.ts
const params: HeroesQueryParams = {
    groupId: 1,
    name: 'US',
    dead: false
};
this.heroesService.getHeroes(params).subscribe((heroes: Heroes) => {
    console.log(heroes);
});

// heroes.service.ts
import { HttpClient } from '@angular/common/http';
// ...
getHeroes(params: HeroesQueryParams): Observable<Heroes> {
    return this.httpClient.get<Heroes>('/path/to/heroes', {
        params: params // ERROR
    });
}
```

To cut a long story short, new `HttpClient`, which is imported from `@angular/common/http`, doesn't support non-string values in query params. This is related to numbers, booleans, dates etc. That's why I should use old one, write some transform utils or just `.toString()`.

## What is the motivation / use case for changing the behavior?
It worked previously.

## Environment
```
Angular version: 6.0.0

Browser:
- [x] Chrome (desktop) version 66
```

**Comment by Halfist** [comment] 2018-05-11 14:43
The issue is also mentioned [here](https://github.com/angular/angular/issues/18012#issuecomment-361870811) and [here](https://github.com/angular/angular/issues/18012#issuecomment-367656487).

**Comment by ericmartinezr** [comment] 2018-05-11 14:43
See https://github.com/angular/angular/pull/19595

**Comment by jotatoledo** [comment] 2018-05-23 07:38
@ericmartinezr seems like #19595 wont be updated

**Comment by Halfist** [comment] 2018-06-15 10:10
This is for those who want fast solution.

```
// utils.service.ts
import { HttpParams } from '@angular/common/http';
// ...
export class UtilsService {
    static buildQueryParams(source: Object): HttpParams {
        let target: HttpParams = new HttpParams();
        Object.keys(source).forEach((key: string) => {
            const value: string | number | boolean | Date = source[key];
            if ((typeof value !== 'undefined') && (value !== null)) {
                target = target.append(key, value.toString());
            }
        });
        return target;
    }
}

// heroes.service.ts
import { HttpClient } from '@angular/common/http';
// ...
getHeroes(params: HeroesQueryParams): Observable<Heroes> {
    const queryParams: HttpParams = UtilsService.buildQueryParams(filter);
    return this.httpClient.get<Heroes>('/path/to/heroes', {
        params: queryParams
    });
}
```

**Comment by othmanekais** [comment] 2018-07-22 14:34
@Halfist  thank you , you save my day :)

**Comment by AlainD-** [comment] 2018-08-06 11:59
@Halfist That was very helpful indeed. Except for the Date value, where I `toISOString()` instead:

`const toString = (val instanceof Date) ? val.toISOString() : val.toString();`

**Comment by Halfist** [comment] 2018-08-06 12:15
@AlainD-, thanks for pointing this out. It really depends on the client-server contract. For example, maybe you want `Date.now().toString()` instead of `new Date().toISOString()`. In this solution I wanted to mimic AngularJS behavior, so I need to take a look at its date auto convertion and replicate it. What's even more important, is to safely handle reference types: `Object`, `Array` and `Function`. Arrays work as expected, because `[1, 2, 3].toString()` returns `'1,2,3'`, but it's not the case for objects and functions. Probably objects auto conversion should be just `JSON.stringify({ foo: 'bar' })`. And for functions I think we may leave `toString()`. What's your opinion? Am I overcomplicating this?

**Comment by AlainD-** [comment] 2018-08-06 13:18
Well... Since all of this is about the query params in the query (not the body), I don't see the point of using Objects, Arrays and Functions. I never met in my experience one of these 3 directly used in the list of parameters of a HTTP request.

Regarding the date, it is not always that I need to use the current date (Date.now() or new Date()), but it is rather to filter on dates. Our contract with the backend is now transferring date properties in UTC, that's why I toISOString() them. (e.g GET a collection where dateProperty lower than a certain date: `?le_dateProperty=2018-08-06T13:16:35.000Z`)

**Comment by Halfist** [comment] 2018-08-06 13:47
@AlainD-, let's discuss all the points.

> Since all of this is about the query params in the query (not the body), I don't see the point of using Objects, Arrays and Functions
I feel that good solution of anything should be as much bulletproof as possible. Of course you won't ever treat a function as a query parameter, but it doesn't mean a user (software engineer in this case) won't do that, most likely by mistake. My point is to handle these edge cases gracefully. More of that, latest Angular version allows you to use string array as a query parameter. An example could be something like /path/to/microwaves?color=black,white. However, since native implementation supports only string arrays, we may have a problem with number ones. In the situation above, there could another way to pass colors, for example, black is 1 and white is 2. Though, since we're using `toString()` here, we don't care whether it's string or number array, because the conversion result is the same.

> Our contract with the backend is now transferring date properties in UTC
In my case it's Unix format. That's why I'm doing the conversion before, and the method then works with something like `1533562812905` - a number, which then gets converted into a string. So, I assumed that user will be doing something similar, and not pass plain `Date` here, because then it'll be converted as is. The only reason I mentioned `Date` in types is that I wanted to show that this type is supported. Of course you may proceed with `toISOString()`, but I wanted the solution to be more flexible.

So, I think it makes sense to rewrite this a little bit. I'll post the updated version later.

**Comment by Halfist** [comment] 2018-08-07 14:28
Finally, here's the solution.

```
// utils.service.ts
import isNil from 'lodash/isNil';
import isPlainObject from 'lodash/isPlainObject';

import { HttpParams } from '@angular/common/http';
// ...
export class UtilsService {
    static buildQueryParams(source: Object): HttpParams {
        let target: HttpParams = new HttpParams();
        Object.keys(source).forEach((key: string) => {
            let value: any = source[key];
            if (isNil(value)) {
                return;
            }
            if (isPlainObject(value)) {
                value = JSON.stringify(value);
            } else {
                value = value.toString();
            }
            target = target.append(key, value);
        });
        return target;
    }
}
```

Here I used two helper methods from [Lodash](https://lodash.com/).

**Comment by alxhub** [comment] 2018-09-04 22:29
This is not a regression, since `HttpClient` is explicitly not API-compatible with the old `@angular/http` library. However, it is something we should support.

**Comment by gautamkrishnar** [comment] 2019-04-10 09:23
Still no update on this?

**Comment by Halfist** [comment] 2019-04-10 09:41
@gautamkrishnar, I think there won't be any. It seems like Angular team sees us using `new HttpParams().append(key, nonStringValue.toString())` each time, so I just proceed with my solution above.

**Comment by nhays89** [comment] 2019-07-30 17:07
FIX THIS!

**Comment by Halfist** [comment] 2019-07-30 17:15
@nhays89, instead of yelling you'd better create pull request with fix.

**Comment by dinohorvat** [comment] 2019-08-07 06:53
I encountered the same problem but with HttpHeaders

https://stackoverflow.com/questions/57384500/httpheaders-instantiate-with-constructor-vs-using-set/57384949#57384949

Both take only 'string' params. How ever I noticed that using set() allows you to pass a number (As an object without type number)

**Comment by beniregev** [comment] 2019-10-01 07:55
> FIX THIS!
@nhays89, how did you fix it? Please share it with the group.

**Comment by luninroman** [comment] 2019-10-11 08:20
> @gautamkrishnar, I think there won't be any. It seems like Angular team sees us using `new HttpParams().append(key, nonStringValue.toString())` each time, so I just proceed with my solution above.

this OOP enthusiasm is definitely went too far in this case

**Comment by KheireddineAzzez** [comment] 2020-09-04 10:58
> @nhays89, instead of yelling you'd better create pull request with fix.

HttpParams is immutable. set() creates and returns a new HttpParams instance, without mutating the instance on which set() is called. So the code should be

const params = new HttpParams().set('status', status);

**Comment by KheireddineAzzez** [comment] 2020-09-04 10:58
HttpParams is immutable. set() creates and returns a new HttpParams instance, without mutating the instance on which set() is called. So the code should be

const params = new HttpParams().set('status', status);

**Closed** 2021-02-26 20:04 UTC
Labels: P4, comp: common/http, feature, freq3: high
