### ISSUE TITLE
Using private property in template is not raising compilation error if used inside structural directive

### ISSUE THREAD

**Issue by ibenjelloun** [angular/angular#30384] opened 2019-05-10 13:23 UTC
# 🐞 bug report

### Description

While using a private member in the component template, the build fails but if the member is used inside a structural directive it does not fail :
This is failing : `{{ privateMember }}`
This is not failing (should fail) : `<ng-container *ngIf="true">{{ privateMember }}</ng-container>`

## 🔬 Minimal Reproduction

[https://github.com/ibenjelloun/angular-protected-member-compilation-issue](Here is a reproduction repository)

The `SucceedingChildComponent` is the component with the issue.
After cloning the repo just run `ng build --prod`, we get an error for `FailingChildComponent` :

```
ERROR in src\app\failing-child.component.ts.FailingChildComponent.html(1,1): : Property 'variable' is private and only accessible within class 'FailingChildComponent'.
```

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 7.3.9
Node: 10.15.3
OS: win32 x64
Angular: 7.2.15
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.9
@angular-devkit/build-angular     0.13.9
@angular-devkit/build-optimizer   0.13.9
@angular-devkit/build-webpack     0.13.9
@angular-devkit/core              7.3.9
@angular-devkit/schematics        7.3.9
@angular/cli                      7.3.9
@ngtools/webpack                  7.3.9
@schematics/angular               7.3.9
@schematics/update                0.13.9
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.29.0
</code></pre>

**Comment by trotyl** [comment] 2019-05-10 13:51
Duplicate of https://github.com/angular/angular/issues/15801

**Comment by JoostK** [comment] 2019-05-10 16:45
Thanks for reporting, and thanks @trotyl for linking the dup. I will go ahead and close this as duplicate of #15801.

For the sake of completeness, though: a much more accurate type-checker is currently being worked on for Ivy. It will be able to type-check more template code than the current type-checker is able to.

**Closed by JoostK** 2019-05-10 16:45 UTC
