### ISSUE TITLE
Angular Service Worker fetch errors

### ISSUE THREAD

**Issue by robertmazzo** [angular/angular#25580] opened 2018-08-20 18:28 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

We're struggling with this service worker related error when accessing our QA website via Chrome - Site can't be reached.

A temp fix is to open f12 dev console and choose "Update on reload" and "Bypass for network" checkboxes, then refresh the page to access the site. 

## Expected behavior

Service worker fetches and caches files, QA website is accessible.

## Minimal reproduction of the problem with instructions

When I first access the website (host in IIS on a Windows Server), we may get a Chrome error stating "Site can't be reached".  
Choosing  "Update on reload" and "Bypass for network"  in F12 Dev Console fixes the issue after a page refresh.

![Image of Chrome error](https://i.stack.imgur.com/OKgQ5.png)

## What is the motivation / use case for changing the behavior?

Website must be accessible first time accessing it after several hours.

## Environment

<pre><code>
Angular version: 6.0.9

Browser:
- [x ] Chrome (desktop) version 68
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.9.3  
- Platform:  Windows 

Others:

</code></pre>

One obvious thing we noticed is the path to our index.html page, which is wrong. It's trying to reference index.html at the domain root - i.e. https://mydomain.myserver.com/index.html - whereas it should reference https://mydomain.myserver.com/mytestwebsite/index.html .

Perhaps there's a problem in our ngsw config file :

```
  {
  "index": "/index.html",
  "assetGroups": [{
    "name": "app",
    "installMode": "prefetch",
    "resources": {
      "files": [
        "/favicon.ico",
        "/index.html",
        "/*.css",
        "/*.js"
      ]
    }
  }, {
    "name": "assets",
    "installMode": "lazy",
    "updateMode": "prefetch",
    "resources": {
      "files": [
        "/assets/**"
      ]
    }
  }],
  "dataGroups": [
    {
      "name": "api-performance",
      "urls": [
        "/api/**"
      ],
      "cacheConfig": {
        "strategy": "freshness",
        "maxSize": 100,
        "maxAge": "6h"
      }
    },
    {
      "name": "custom-server",
      "urls": [
        "**/CustomServer.aspx?**"
      ],
      "cacheConfig": {
        "strategy": "performance",
        "maxSize": 100,
        "maxAge": "1d"
      }
    }
  ]
}
```

**Comment by gkalpak** [comment] 2018-08-20 18:52
It is hard to tell what might be the root of the issue without an actual, minimal reproduction. Maybe you need to build with `--baseHref /mytestwebsite/` (if you are using `@angular/cli`).

Closing since this is not actionable as is. Happy to re-open and investigate if you can provide a minimal reproduction (either steps to run to create a project that demonstrates the issue or a standalone repo that we can check out and investigate).

**Closed by gkalpak** 2018-08-20 18:52 UTC
