### ISSUE TITLE
Custom Template for Template Driven Form Plunker example does not work!

### ISSUE THREAD

**Issue by dannyhchan** [angular/angular#21242] opened 2018-01-01 21:56 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

The plunker examples does not work when entering "bob" in the name field which is suppose to kick off the custom validation message.  Instead, because "bob" is less than 4 characters, that message will always display.

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by ericmartinezr** [comment] 2018-01-01 23:45
Dup of https://github.com/angular/angular/issues/20206 ?

**Comment by dannyhchan** [comment] 2018-01-02 00:27
Yes, same one.

**Comment by pkozlowski-opensource** [comment] 2018-01-02 10:28
Closing as a duplicate of #20206

**Closed by pkozlowski-opensource** 2018-01-02 10:28 UTC
