### ISSUE TITLE
Zone does not check when change router using href in safari

### ISSUE THREAD

**Issue by vthinkxie** [angular/angular#10297] opened 2016-07-26 15:25 UTC
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When using href to change router in Safari, like `<a href='#/about'>About</a>` in Safari,components in this router will not be init until moving mouse.

I add ApplicationRef.tick() after router changes as a temporary solution.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** [Safari ] 
 
* **Language:** [TypeScript]

**Comment by zoechi** [comment] 2016-07-26 18:29
Looks like a dup of #7722 and #9565

**Comment by vsavkin** [comment] 2016-07-28 21:44
Could you provide a repro using the latest nightly build?  The issue has been fixed here https://github.com/angular/angular/commit/f08060b0b00c98341c7e1fd9acb984402c280396

**Comment by vsavkin** [comment] 2016-08-08 23:25
Closing this issue. Please reopen it with a plunker reproducing the problem

**Closed by vsavkin** 2016-08-08 23:25 UTC
Labels: comp: router, need: repro, type: bug
