### ISSUE TITLE
RFC: Use protected variables in HTML

### ISSUE THREAD

**Issue by prabh-62** [angular/angular#29648] opened 2019-04-02 02:33 UTC
# 🚀 feature request

### Relevant Package
This feature request is for `@angular/compiler-cli`

### Description
In order to access variables in HTML, we have to set variable's access level to `public`. This introduces plethora of problems. I can name few here:

Imagine, we create a variable `loginFormGroup` inside `.ts` file.
```typescript
  private loginFormGroup = new FormGroup({ username: new FormControl('') });
```
To hook into HTML, I have to change variable's access level to `public` which I don't want to do but I have to.
```html
<form [formGroup]="loginFormGroup">
...
</form>

```

- @ViewChild : If a parent component gets a reference to child componentInstance, the parent component can now modify all public properties and methods. This is fine except at times when it is not. 

Inside a parent component
```typescript
@ViewChild(ChildComponent) childComponent: ChildComponent;

// This formGroup is supposed to be internal 😡
// I don't want anybody to play with my loginFormGroup variable
this.childComponent.loginFormGroup.patchValue({username: 'Hacked'});
```

- Unit test
```typescript
  it('should enable login button if username is entered', () => {
    // Totally Wrong: loginFormGroup should not be accessible here
    // We should set username by accessing HTML Input control using CSS
    component.loginFormGroup.patchValue({
      username: 'John'
    });
    fixture.detectChanges();
    const loginButton = fixture.debugElement.query(By.css('.login-button'));
     expect(loginButton.nativeElement.disabled).toBe(false);
   });
```

### Describe the solution you'd like
We should be able to use variables in HTML without setting them to be `public`. We can consider `protected` access modifier however I am open to other suggestions.

**Comment by Airblader** [comment] 2019-04-02 06:07
This is essentially a duplicate of #11422

**Comment by alxhub** [comment] 2019-04-02 22:56
Closing as a duplicate of #11422. The same arguments apply to `private` vs `protected`.

**Closed** 2019-04-03 07:47 UTC
Labels: comp: core & compiler
