### ISSUE TITLE
Angular 2 will not work with RequireJs

### ISSUE THREAD

**Issue by shadow999** [angular/angular#5412] opened 2015-11-20 17:25 UTC
I have created a very simple angular app with pure javascript as follows:
```
<html>
<head>
	<script type="text/javascript" src="require.js"></script>
	<script type="text/javascript" src="angular2.sfx.dev.js"></script>
    <meta charset="UTF-8">
    <title>Angular 2 Test</title>
</head>
<body>
    <my-app>Hello World</my-app>
    <script type="text/javascript">
            (function() {
                var AppComponent = ng
                        .Component({
                            selector: 'my-app',
                            template: '<h1>My First Angular 2 App</h1>'
                        })
                        .Class({
                            constructor: function () { }
                        });

                document.addEventListener('DOMContentLoaded', function() {
                    ng.bootstrap(AppComponent);
                });
            })();
    </script>
</body>
</html>
```

I got "Uncaught TypeError: Cannot read property '_setAsap' of undefined" error in chrome dev tool. However, if I removed require.js, it works perfectly.

I am wondering how can I use both Angular 2 and RequireJs, because part of my project needs RequireJs to load scripts.

**Comment by PascalPrecht** [comment] 2015-11-20 17:31
Based on your code snippet, there's no require.js machinery at all except the library itself. This particular code shouldn't cause any errors since you don't even use require.js

Could you set up a plunk that reproduces your issue?

**Comment by shadow999** [comment] 2015-11-20 19:02
Sample project is here: https://codenvy.com/ide-resources/share/project/emoc1989/Anglura2WithRequireJs

The running server is here: http://runnerp10.codenvycorp.com:65254/
"Uncaught TypeError: Cannot read property '_setAsap' of undefined" error would be found after navigate to this page.

**Comment by PascalPrecht** [comment] 2015-11-20 19:07
Looks like you're missing some es6-polyfills.

**Comment by shadow999** [comment] 2015-11-20 19:34
The problem is at this line: var es6Promise = require('es6-promise').Promise;
After RequireJs being loaded, require('es6-promise') would return empty object. But it works if RequireJs was not loaded.

I do not quite understand what is happening here.

**Comment by ericmartinezr** [comment] 2015-11-20 20:12
@shadow999 try putting `require.js` below `angular2.sfx.dev.js`, it looks like it is overriding the `require` used in the bundle.

**Comment by shadow999** [comment] 2015-11-20 20:14
@ericmartinezr Thanks for reply. This will solve my original code snippet. But it will not work in my a bit more complicate same project here: https://codenvy.com/ide-resources/share/project/emoc1989/Anglura2WithRequireJs

**Comment by shadow999** [comment] 2015-11-20 22:00
After further investigation, I found there is some code in angular2.js
```
if (typeof define === 'function' && define['amd']) {
	define(function() { return lib$es6$promise$umd$$ES6Promise; });
} else if (typeof module !== 'undefined' && module['exports']) {
	module['exports'] = lib$es6$promise$umd$$ES6Promise;
} else if (typeof this !== 'undefined') {
	this['ES6Promise'] = lib$es6$promise$umd$$ES6Promise;
}
```
If RequireJs was loaded, "define" is a function and define['amd'] is an object. It will try to call "define" by passing a function which returns the promise. However, the callback was executed too late to return promise before calling _setAsap.

**Comment by robwormald** [comment] 2015-11-21 11:42
The SystemJS loader (recommended) will load AMD files and uses the same configuration syntax, fwiw.

**Comment by cjolif** [comment] 2015-11-21 14:44
I am facing the same issue. I'm wondering if configuring TypeScript to compile angular to amd instead of commonjs would not solve this issue as well ( `"module": "amd"`,  instead of `"module": "commonjs"`)
.

**Comment by shadow999** [comment] 2015-11-21 20:13
@robwormald, I tried SystemJs and got same error. The reason I need to use RequireJs is to be able to reuse my existing code. Is there a way to make RequireJs work with Angular 2?

**Comment by robwormald** [comment] 2015-11-24 21:23
There's nothing that should prevent the two of them working together. I'm unable to run your code on CodeEnvy, so if you can create a plunker [template](http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5) - i'll have a closer look.

**Comment by pkozlowski-opensource** [comment] 2015-11-24 21:44
Also the sfx bundles that we are producing today are not great fit for AMD loaders. You should wait till https://github.com/angular/angular/pull/5313 lands / get released.

**Comment by shadow999** [comment] 2015-11-24 22:16
@robwormald Here is the plunker: http://plnkr.co/edit/vyhAxi

**Comment by robwormald** [comment] 2015-11-24 22:28
Sort of backwards here, IMHO. Angular2 (could conceivably) be transpiled to AMD from Typescript, but we're unlikely to support it. The SystemJS loader is *universal*, meaning it will load AMD, CJS, and ES6 code from the same loader. So I would advise not authoring new code in AMD - use the System loader to allow you to load legacy (AMD) code into your new Angular2 application.

For example - http://plnkr.co/edit/ecEX8G1vdYHAnR7Efxjg?p=preview - see also https://github.com/systemjs/systemjs/blob/master/docs/config-api.md - it basically works the same as the requireJS loader.

**Comment by robwormald** [comment] 2015-11-24 22:37
I'm going to close this, as it works, but feel free to carry on discussion.

**Closed by robwormald** 2015-11-24 22:37 UTC

**Comment by shadow999** [comment] 2015-11-25 21:05
@robwormald Thanks for the example. I finally get it working by loading SystemJs, Angular 2, and RequireJs in this order.

**Comment by variab1e** [comment] 2016-01-08 08:34
@shadow999 May I ask how you /what sequence you were able to get it working in?

I am using SystemJS to write ES6 code and then downconvert on the fly with babel (so systemjs + babel + es6 + angular2)

**Comment by shadow999** [comment] 2016-01-08 15:54
@variab1e I am not using babel. The way I got it working is that I changed my typescript compiler to compile ts file into SystemJs format. And, in my html page, I loaded SystemJs globally before anything else. With Angular 2 beta, you also need to load angular2-polyfill and rxjs before loading Angular 2 itself.

**Comment by variab1e** [comment] 2016-01-10 19:02
@shadow999 Ok, cool, got that bit. I was trying to figure out how to do es6/7 decorators in systemjs on the fly tranpilation, but since babel stopped supporting browser.js it has made things a bit harder. Thanks for the help though!
