### ISSUE TITLE
Wildcard route works before lazy loaded children are parsed

### ISSUE THREAD

**Issue by andreystorchous** [angular/angular#31283] opened 2019-06-26 12:53 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....
Router

### Is this a regression?
Dunno

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...
I have a following routing configuration:
[
 {
  path: 'parent',
  children: [
   {
    path: ':parentId',
    children: [
     {
      path: 'child1',
      loadChildren: () => import(...),
     },
     {
      path: 'child2',
      loadChildren: () => import(...),
     }
    ]
   }
  ],
 { path: '**', component: NotFoundPageComponent },
]
When I am on child1 and trying to navigate to child2, the wildcard route is activated instead of navigating to child2. I think this is caused by the fact that module is being loaded lazy. When I comment the wildcard statement, routing works fine.
## 🔬 Minimal Reproduction

 https://stackblitz.com/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by atscott** [comment] 2019-08-08 22:33
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.

**Comment by mleibman** [comment] 2019-08-09 16:13
I think I have come across a same/similar issue.
I noticed that when loading the app with a URL matching a known router config path, the module specified as `loadChildren` in the `**` wildcard route is always downloaded anyway. I would expect it to only get loaded when no other route config matches, but that appears not to be the case. This is consistent with the situation described above.

**Comment by mleibman** [comment] 2019-08-30 10:08
@atscott 
Ping. If the `**` route refers to a lazy-loaded module via `loadChildren`, this is a performance issue that affects all Angular applications.

**Comment by agale123** [comment] 2019-11-26 21:30
Is this a duplicate of #25494

**Comment by atscott** [comment] 2019-11-26 21:33
Thanks @agale123, I'll close this one in favor of #25494 then.

**Closed by atscott** 2019-11-26 21:33 UTC
Labels: comp: router, state: Needs repro
