### ISSUE TITLE
In EDGE and IE11 routing requires me to click twice on the route to make it work 

### ISSUE THREAD

**Issue by johnpapa** [angular/angular#6493] opened 2016-01-14 19:55 UTC
cc @wardbell @IgorMinar @btford

**Comment by wardbell** [comment] 2016-01-14 20:02
Works for me in Edge v.25.10586.0.0 but I do see the behavior in IE11 on Windows 10.

**Comment by gdi2290** [comment] 2016-01-14 20:09
another common error is including systemjs polyfills after the angular ones inside of index.html
```
es6-shim
systemjs-polyfills
angular2-polyfills

systemjs/typescript/angular2
```

**Comment by wardbell** [comment] 2016-01-14 20:21
@gdi2290 That was the secret sauce!

We were omitting the systemjs polyfill. Didn't even know it was needed.

The following prolog **for plunker** seems to work. Awaiting John's confirmation:
```
    <script src="https://cdnjs.cloudflare.com/ajax/libs/es6-shim/0.34.1/es6-shim.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/systemjs/0.19.16/system-polyfills.js"></script>
    <script src="https://code.angularjs.org/2.0.0-beta.0/angular2-polyfills.js"></script>
    <script src="https://code.angularjs.org/tools/system.js"></script>
    <script src="https://code.angularjs.org/tools/typescript.js"></script>
    <script src="https://code.angularjs.org/2.0.0-beta.0/Rx.js"></script>
    <script src="https://code.angularjs.org/2.0.0-beta.0/angular2.dev.js"></script>
    <script src="https://code.angularjs.org/2.0.0-beta.0/router.dev.js"></script>
```
Adjustments needed when loading from npm modules. 

But the net of it is that, for IE, must load
* es6 shim
* systemjs polyfills
* angularjs polyfills
before proceeding

**Comment by johnpapa** [comment] 2016-01-14 20:52
where do i get this in the npm package for systemjs? i dont see it

```
    https://cdnjs.cloudflare.com/ajax/libs/systemjs/0.19.16/system-polyfills.js
```

**Comment by johnpapa** [comment] 2016-01-14 20:55
I found it ... here is the npm strategy ...

```
  <!-- IE required polyfills, in this exact order -->
  <script src="node_modules/es6-shim/es6-shim.min.js"></script>
  <script src="node_modules/systemjs/distsystem-polyfills.js"></script>

  <!-- Angular polyfill required everywhere -->
  <script src="node_modules/angular2/bundles/angular2-polyfills.js"></script>

  <script src="node_modules/systemjs/dist/system.src.js"></script>
  <script src="node_modules/rxjs/bundles/Rx.js"></script>
  <script src="node_modules/angular2/bundles/angular2.dev.js"></script>
  <script src="node_modules/angular2/bundles/router.dev.js"></script>
  <script src="node_modules/angular2/bundles/http.dev.js"></script>
```

**Comment by wardbell** [comment] 2016-01-14 21:16
Unfortunately, can't use [conditional comments](https://msdn.microsoft.com/en-us/library/ms537512(v=vs.85).aspx) to ONLY download these files if using IE. 

IE11 ignored this "downlevel hidden" comment:
```
    <!--[if IE]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/es6-shim/0.34.1/es6-shim.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/systemjs/0.19.16/system-polyfills.js"></script>
    <![endif]--> 
```
Using the "downlevel revealed" comment 
```
    <![if IE]>
      ...
    <![endif]--> 
```
is like having no comment at all; the scripts are always loaded.

My best guess at the moment is to simply make all browsers pay the price of downloading ES6-shim (16kb) and systemjs-polyfills (5kb).  

A browser-sniffing server could do something about it I guess but that's beyond my skill level.

**Comment by dsebastien** [comment] 2016-01-14 21:25
Thanks for the tip guys, I was just trying to understand what the blip was going on under IE

**Comment by CaptainCodeman** [comment] 2016-01-14 23:36
Just to clarify - the system-polyfills are required for IE/Edge _regardless_ of whether you're using system.js (the loader) or not ... right? (i.e. they are needed if packaging with webpack).

It appears support for automatically requesting the system-polyfills.js if required is built in to the system.js loader but the folder location needs to match.

https://github.com/systemjs/systemjs#polyfills
https://github.com/systemjs/systemjs/blob/9ed38dd94f52eefa1b623d8c2b8623a92b480b2a/lib/wrapper-end.js

**Comment by pkozlowski-opensource** [comment] 2016-01-15 11:06
> Just to clarify - the system-polyfills are required for IE/Edge regardless of whether you're using system.js (the loader) or not ... right? (i.e. they are needed if packaging with webpack).

Nope, this is only SystemJS-internal stuff and I think that SystemJS is not a well-behaving citizen here - in my opinion it shouldn't try to fetch polyffils on their own but rather require people to provide ones if needed.

**Comment by varadero** [comment] 2016-01-17 08:41
This might be related to #6140

**Comment by wardbell** [comment] 2016-01-18 04:40
I updated all published TS samples (except homepage) in [angular.io commit 7ed0fce](https://github.com/angular/angular.io/commit/7ed0fce10dedcbfd98aa4ff265edca389df9a3b0)

**Comment by vsavkin** [comment] 2016-07-06 23:44
We are no longer maintaining the deprecated router to focus our efforts on making the new router solid.

Could you reproduce the problem using the new router and submit a separate issue?

Closing this.

**Closed by vsavkin** 2016-07-06 23:44 UTC
Labels: comp: router-deprecated, effort1: easy (hour), P2: required, type: bug
