### ISSUE TITLE
Many "Circular source file mapping dependency" warnings on first build

### ISSUE THREAD

**Issue by jtsom** [angular/angular#38001] opened 2020-07-10 15:17 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [X] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes
 Yes, the previous version in which this bug was not present was: ....
10.0.2

### Description

 A clear and concise description of the problem...
After updating a very simple, almost stock 'ng new'd application to 10.0.2, upon first build (ng serve), lots of these circular dependency warnings appeared during the first pass (building for es2015)

```
Compiling @angular/core : es2015 as esm2015
Compiling @angular/cdk/keycodes : es2015 as esm2015
Compiling @angular/animations : es2015 as esm2015
Compiling @angular/compiler/testing : es2015 as esm2015
Warning: Unable to fully load /Users/johntsombakos/Dev/ng9-test/node_modules/@angular/cdk/keycodes/index.d.ts for source-map flattening: Circular source file mapping dependency: /Users/johntsombakos/Dev/ng9-test/node_modules/@angular/cdk/keycodes/index.d.ts.map -> /Users/johntsombakos/Dev/ng9-test/node_modules/@angular/cdk/keycodes/index.d.ts.map
Compiling @angular/animations/browser : es2015 as esm2015
Compiling @angular/cdk/observers : es2015 as esm2015
Compiling @angular/cdk/collections : es2015 as esm2015
Compiling @angular/common : es2015 as esm2015
Compiling @angular/core/testing : es2015 as esm2015
Warning: Unable to fully load /Users/johntsombakos/Dev/ng9-test/node_modules/@angular/cdk/collections/unique-selection-dispatcher.d.ts for source-map flattening: Circular source file mapping dependency: /Users/johntsombakos/Dev/ng9-test/node_modules/@angular/cdk/collections/unique-selection-dispatcher.d.ts.map -> /Users/johntsombakos/Dev/ng9-test/node_modules/@angular/cdk/collections/unique-selection-dispatcher.d.ts.map
Warning: Unable to fully load /Users/johntsombakos/Dev/ng9-test/node_modules/@angular/cdk/collections/index.d.ts for source-map flattening: Circular source file mapping dependency: /Users/johntsombakos/Dev/ng9-test/node_modules/@angular/cdk/collections/index.d.ts.map -> /Users/johntsombakos/Dev/ng9-test/node_modules/@angular/cdk/collections/index.d.ts.map
```

## 🔥 Exception or Error
<pre><code>Warning: Unable to fully load /Users/johntsombakos/Dev/ng9-test/node_modules/@angular/cdk/keycodes/index.d.ts for source-map flattening: Circular source file mapping dependency: /Users/johntsombakos/Dev/ng9-

</code></pre>

## 🌍 Your Environment
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 10.0.2
Node: 14.5.0
OS: darwin x64

Angular: 10.0.3
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.2
@angular-devkit/build-angular     0.1000.2
@angular-devkit/build-optimizer   0.1000.2
@angular-devkit/build-webpack     0.1000.2
@angular-devkit/core              10.0.2
@angular-devkit/schematics        10.0.2
@angular/cdk                      10.0.1
@angular/cli                      10.0.2
@angular/material                 10.0.1
@ngtools/webpack                  10.0.2
@schematics/angular               10.0.2
@schematics/update                0.1000.2
rxjs                              6.6.0
typescript                        3.9.6
webpack                           4.43.0
</code></pre>

**Anything else relevant?**

**Comment by petebacondarwin** [comment] 2020-07-10 15:53
Are the warnings only for CDK packages or others too?

**Comment by jtsom** [comment] 2020-07-10 15:56
Possibly, but as I mentioned, I can't get the `ng serve` command to do the double-build to check. How do I get it to "build for the first time"?

**Comment by petebacondarwin** [comment] 2020-07-10 16:15
You must delete and reinstall node_modules

**Comment by jtsom** [comment] 2020-07-10 16:19
Ok. I deleted and reinstalled node_modules and it did do the double-build. But this time I did not get those warnings. So I'm not sure what changed or if it was just a normal Angular weirdness....

**Comment by petebacondarwin** [comment] 2020-07-10 16:46
I just created a new project and added CDK. I could not reproduce. I think that perhaps your node_modules were just a bit skewed for some reason. Closing as this doesn't appear to be a reproducible problem. If it comes back please open a new issue.

**Closed by petebacondarwin** 2020-07-10 16:46 UTC
Labels: comp: ngcc

**Comment by GeorgeTailor** [comment] 2020-07-10 18:36
@petebacondarwin do an update from 9 to 10, this is the case when this error pops up.

**Comment by petebacondarwin** [comment] 2020-07-10 18:46
That fits with node_modules being messed up...
