### ISSUE TITLE
Navigate to self scrolls to top unless scrollPositionRestoration disabled

### ISSUE THREAD

**Issue by ZNS** [angular/angular#27275] opened 2018-11-26 20:16 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/router

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 6.1.4?

### Description

I'm basically having this exact issue in 6.1.10 /issues/25353 which was supposedly fixed in 6.1.4 /pull/25586

## 🔬 Minimal Reproduction

See the issue above and [this stackblitz](https://stackblitz.com/edit/angular-issue-27275)

## 🌍  Your Environment

**Angular Version:**  6.1.10
<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by ZNS** [comment] 2018-11-26 21:36
Added stackblitz which shows this problem. I can't get it to work with 7.1.0 either. https://stackblitz.com/edit/angular-issue-27275

**Comment by ericmartinezr** [comment] 2018-11-26 22:51
The PR you referenced changed the default behavior from `enabled` to `disabled` by default, which is what happens in your stackblitz if you remove the `enabled` from the `forRoot`.

**Comment by ZNS** [comment] 2018-11-27 00:05
Ok, so the behaviour to scroll to the top when the querystring changes and scrollPositionRestoration is set to "enabled" is expected? I thought it would restore (keep) the position when simply changing the query.

**Comment by jasonaden** [comment] 2018-11-27 19:09
Yes, that's expected as currently implemented. The reason is it's a new navigation as we have no way of knowing what your application does with that query string and therefore can't know what would be rendered and if it's materially different or not.

The restoration only comes into play when using `back` and `forward` buttons.

If you want to customize the behavior, you can provide your own scrolling manager that would handle this type of transition differently.

Closing based on this working as intended.

**Closed by jasonaden** 2018-11-27 19:09 UTC
