### ISSUE TITLE
Template reference variable - value not updated

### ISSUE THREAD

**Issue by arturhun** [angular/angular#32081] opened 2019-08-09 15:32 UTC
# 🐞 bug report

### Affected Package
@angular/core

### Is this a regression?

Possibly. I am pretty sure it used to work once, and it is described as a valid template syntax here: https://angular.io/guide/template-syntax (see the box entitled **template reference variable**)

### Description

When an input is captured as template variable, its value doesn't update.
This issue looks similar to 31825 with the difference that the enclosed example also demonstrates malfunction at the basic usage level, outside of `ng-template`.

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-scrgem

**Comment by NoamBuzaglo** [comment] 2019-08-09 19:37
Hey,
I want to start contribute to angular and this issue can be nice starting for me.
Thanks.

**Comment by trotyl** [comment] 2019-08-12 10:01
Duplicate of https://github.com/angular/angular/issues/6618, https://github.com/angular/angular/issues/22108

---

Working as expected.

**Closed** 2019-08-20 22:58 UTC
Labels: comp: core
