### ISSUE TITLE
Support interpolation in <style></style>

### ISSUE THREAD

**Issue by tonn** [angular/angular#13802] opened 2017-01-05 23:44 UTC
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Interpolations are ignored in <style> block.

**Expected behavior**

Support interpolations in <style> block.

**Minimal reproduction of the problem with instructions**

https://plnkr.co/edit/pA0FcxdV6VEaupsTFe2V

**What is the motivation / use case for changing the behavior?**

If I know only css-class name of element - I can't change its styles dynamicaly

**Please tell us about your environment:**

* **Angular version:** 2.2.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment] 2017-01-05 23:51
Duplicate of https://github.com/angular/angular/issues/7251

**Closed** 2017-01-06 01:17 UTC
