### ISSUE TITLE
Tutorial about InMemoryWebApiModule is out of date

### ISSUE THREAD

**Issue by exzhawk** [angular/angular#19736] opened 2017-10-16 08:14 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Simulated web API get undefined data

## Expected behavior

Simulated web API get data like it defined in the tutorial 

## Minimal reproduction of the problem with instructions

follow the tutorial till https://angular.io/tutorial/toh-pt6#simulate-the-web-api

## What is the motivation / use case for changing the behavior?

Use InMemoryWebApiModule to mock HTTP service

## Environment

<pre><code>
Angular version: 4.4.5

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

Due to the breaking change of Angular in-memory-web-api https://github.com/angular/in-memory-web-api#http-response-data-no-longer-wrapped-in-object-w-data-property ,the tutorial should add `dataEncapsulation: true` or replace `response.json().data` with `response.json()` as https://github.com/angular/in-memory-web-api/blob/master/CHANGELOG.md/#050-2017-10-05 said.

**Comment by gkalpak** [comment] 2017-10-16 11:15
This is essentially a duplicate of #19602 and will be fixed (temporarily) by #19668. The gist of the issue is that we lock `angular-in-memory-web-api` to 0.4.x locally, on CI and for the downloaded zips (so the code works fine there), but leave the version unrestricted on plnkrs.

We have planned to change the plnkr generation, so that the same version ranges are used everywhere (including plnkrs). This way, we can be sure that the same version that we use and test on CI will also be used on plnkrs.

Eventually, of course, we should update the version of `angular-in-memory-web-api` to the latest version and update our examples (but that doesn't really affect the users much - as long as there is a working in-memory API).

**Closed by gkalpak** 2017-10-16 11:15 UTC
