### ISSUE TITLE
Angular CLI can't build in production, because of `common.js` files have extra commas

### ISSUE THREAD

**Issue by Aristocr2t** [angular/angular#21595] opened 2018-01-17 16:34 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I don't know why `common.js` files have extra commas (`<...>\node_modules\@angular\common\esm5\common.js:913-948`, `<...>\node_modules\@angular\common\esm2015\common.js:724-756`), but because of it:
```
var localeEn = [
    'en',
    [
        ['a', 'p'],
        ['AM', 'PM'],
    ],
    [
        ['AM', 'PM'],
        ,
    ],
    [
        ['S', 'M', 'T', 'W', 'T', 'F', 'S'], ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
        ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
        ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa']
    ],
    ,
    [
        ['J', 'F', 'M', 'A', 'M', 'J', 'J', 'A', 'S', 'O', 'N', 'D'],
        ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
        [
            'January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September',
            'October', 'November', 'December'
        ]
    ],
    ,
    [['B', 'A'], ['BC', 'AD'], ['Before Christ', 'Anno Domini']], 0, [6, 0],
    ['M/d/yy', 'MMM d, y', 'MMMM d, y', 'EEEE, MMMM d, y'],
    ['h:mm a', 'h:mm:ss a', 'h:mm:ss a z', 'h:mm:ss a zzzz'],
    [
        '{1}, {0}',
        ,
        '{1} \'at\' {0}',
    ],
    ['.', ',', ';', '%', '+', '-', 'E', '×', '‰', '∞', 'NaN', ':'],
    ['#,##0.###', '#,##0%', '¤#,##0.00', '#E0'], '$', 'US Dollar', converter
];
```
I can't build a project in production (`ng build --prod`).
```
ERROR in chunk main [initial]
[name].[chunkhash:20].bundle.js
Cannot read property 'range' of null
TypeError: Cannot read property 'range' of null
    at enterNode (<...>\node_modules\webpack\lib\optimize\ConcatenatedModule.js:149:15)
    at getPathInAst (<...>\node_modules\webpack\lib\optimize\ConcatenatedModule.js:128:24)
    at getPathInAst (<...>\node_modules\webpack\lib\optimize\ConcatenatedModule.js:137:24)
    at enterNode (<...>\node_modules\webpack\lib\optimize\ConcatenatedModule.js:152:18)
    at getPathInAst (<...>\node_modules\webpack\lib\optimize\ConcatenatedModule.js:141:25)
    at enterNode (<...>\node_modules\webpack\lib\optimize\ConcatenatedModule.js:152:18)
    at getPathInAst (<...>\node_modules\webpack\lib\optimize\ConcatenatedModule.js:128:24)
    at getPathInAst (<...>\node_modules\webpack\lib\optimize\ConcatenatedModule.js:137:24)
    at enterNode (<...>\node_modules\webpack\lib\optimize\ConcatenatedModule.js:152:18)
    at getPathInAst (<...>\node_modules\webpack\lib\optimize\ConcatenatedModule.js:128:24)
    at getPathInAst (<...>\node_modules\webpack\lib\optimize\ConcatenatedModule.js:137:24)
    at info.moduleScope.variables.forEach.variable (<...>\node_modules\webpack\lib\optimize\ConcatenatedModule.js:539:23)
    at Array.forEach (<anonymous>)
    at modulesWithInfo.forEach.info (<...>\node_modules\webpack\lib\optimize\ConcatenatedModule.js:527:34)
    at Array.forEach (<anonymous>)
    at ConcatenatedModule.source (<...>\node_modules\webpack\lib\optimize\ConcatenatedModule.js:519:19)
```
If I remove that commas, the issue disappears.

## Environment
<pre><code>
Angular version: 5.2.0
Angular CLI version: 1.6.4

 
For Tooling issues:
- Node version: 8.9.3  
- Platform: Windows
</code></pre>

**Comment by ocombe** [comment] 2018-01-17 19:29
The error is the "converter" at the end, which should not be there! Thanks for the report I'll fix it

**Comment by vicb** [comment] 2018-01-17 19:30
The extra commas are required - see elision in https://www.ecma-international.org/ecma-262/5.1/#sec-11.1.4

**Comment by ocombe** [comment] 2018-01-17 19:31
Nevermind, @alexeagle changed the generation script to export the plural function apparently, so converter should not be the cause of the error.
As for the extra commas, it's valid ES5 because we have undefined values in the array

**Comment by ocombe** [comment] 2018-01-17 19:42
Can you give us your version of typescript, and the version of webpack that you have?
Also if you can generate a minimal reproduction project on github that we can use, that'd be great, because I just tester with a new cli project and it builds just fine for me (same version of cli / node, / angular on windows)

**Comment by ocombe** [comment] 2018-01-19 13:38
From the project that you sent me in private, I've narrowed the error down to `const converter = new Converter();` in your markdown directive.

Since `Converter` is imported from the library `showdown`, the error is there, not in Angular. Something in their code is breaking the webpack optimizer somehow.

I'm closing the issue since it is not a problem in Angular source code.

**Closed by ocombe** 2018-01-19 13:38 UTC
Labels: comp: i18n, state: Need repro, type: bug

**Comment by marcuslind90** [comment] 2018-01-30 12:17
I'm having exactly the same issue. I don't use `showdown` library.

I tried with Angular CLI 1.6.6 and Angular 5.2.1 and 5.2.2.

**Comment by azulinternet** [comment] 2018-02-04 19:45
Related:
https://github.com/webpack/webpack/commit/2aebfbe48ca1de63a16b82cda8182e5f47955870#diff-e33d2e7031dc20d53a5c70153b79adf2
