### ISSUE TITLE
Angular.io page is not loaded

### ISSUE THREAD

**Issue by abumuawiyah** [angular/angular#41073] opened 2021-03-04 01:44 UTC
# 📚 Docs or angular.io bug report

### Description

The Angular.io page is not loaded and require user to refresh the page.

## 🔬 Minimal Reproduction

- open up Brave browser, I am using Version 1.20.110 Chromium: 88.0.4324.192 (Official Build) (x86_64)
- navigate to https://angular.io/api/router

### What's the affected URL?**
https://angular.io/api/router

### Reproduction Steps**

- open up Brave browser, I am using Version 1.20.110 Chromium: 88.0.4324.192 (Official Build) (x86_64)
- navigate to https://angular.io/api/router

### Expected vs Actual Behavior**

Expected: Page loaded successfully 
Actual: Page is not loaded and keep on loading

## 📷Screenshot
<img width="1280" alt="Screen Shot 2021-03-04 at 9 35 37 AM" src="https://user-images.githubusercontent.com/2411183/109897717-14436380-7cce-11eb-81e1-09ac3f5967c6.png">

## 🔥 Exception or Error
Please see the screenshot

## 🌍  Your Environment
<img width="581" alt="Screen Shot 2021-03-04 at 9 36 12 AM" src="https://user-images.githubusercontent.com/2411183/109897742-21f8e900-7cce-11eb-888c-31919320a2d3.png">

### Browser info
Brave browser Version 1.20.110 Chromium: 88.0.4324.192 (Official Build) (x86_64)

### Anything else relevant?
No

**Comment by petebacondarwin** [comment] 2021-03-04 08:24
When I tried this I got the following error in the console:

```
Error: [DocViewer] Error preparing document 'api/router': ChunkLoadError: Loading chunk 16 failed.
(error: https://angular.io/toc-toc-module-es2015.62138261011a04eb2d09.js)
```

Note that once you have refreshed it does not happen again - for me at least.

**Comment by petebacondarwin** [comment] 2021-03-04 08:25
I suspect that it was down to the service-worker being updated...

**Comment by abumuawiyah** [comment] 2021-03-04 13:58
@petebacondarwin you are right. Once refreshed, the issue does not happen again. Weird.

**Comment by petebacondarwin** [comment] 2021-03-04 14:00
Almost definitely a duplicate of https://github.com/angular/angular/issues/28114

**Closed by petebacondarwin** 2021-03-04 14:00 UTC
