### ISSUE TITLE
FormControl disabled state is always initialized to false instead of null

### ISSUE THREAD

**Issue by aam-antonio** [angular/angular#43293] opened 2021-08-31 11:02 UTC
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

No

### Description

When the @Input attribute `disabled` is set to true and a FormControl is used only with the default value, the disabled state from the FormControl will initialize to false instead of null, and then the input field will not be disabled.
 
On the directive input.ts from Angular Material, the case where `disabled === null` will never be true. So it will return the state of `this.ngControl.disabled` although is it not initialized.
```
@Input()
  get disabled(): boolean {
    if (this.ngControl && this.ngControl.disabled !== null) {
      return this.ngControl.disabled;
    }
    return this._disabled;
  }
```

Is this case correct? Should `this.ngControl.disabled` be initialized to null when is not defined?

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-udxffk?file=src%2Fapp%2Finput-overview-example.html

**Comment by jnizet** [comment] 2021-09-01 06:11
Hi @aam-antonio 

You're not supposed to use `[disabled]` on an input using a reactive form directive.
If you open the console in your stackblitz, demo, you'll see this warning being logged:
```
It looks like you're using the disabled attribute with a reactive form directive. If you set disabled to true
      when you set up this control in your component class, the disabled attribute will actually be set in the DOM for
      you. We recommend using this approach to avoid 'changed after checked' errors.

      Example:
      form = new FormGroup({
        first: new FormControl({value: 'Nancy', disabled: true}, Validators.required),
        last: new FormControl('Drew', Validators.required)
      });
```

**Comment by dylhunn** [comment] 2022-07-21 23:26
Duplicate of #35309.

**Closed by dylhunn** 2022-07-21 23:26 UTC
Labels: comp: forms
