### ISSUE TITLE
STOP IGNORING #30835

### ISSUE THREAD

**Issue by westlakem** [angular/angular#35734] opened 2020-02-27 23:42 UTC
Anyone who hosts an angular application on a cloud vendor like AWS, Google, Microsoft, etc, are running into this problem.  Many people have commented on it, even though you've closed the issue as "not our problem" and decided not to discuss it with the community anymore.  This issue deserves more attention than you are giving it.

#30835

**Comment by Miboch** [comment] 2020-02-28 10:26
have you tried https://github.com/aws-amplify/amplify-cli/issues/1995#issuecomment-521896775 ?

**Comment by tomnar** [comment] 2020-02-28 12:20
Well, @westlakem is right. I'm running into the same problem after upgrading angular from 6 to 9 and hosting on AWS. 
Since the dist path already is configured as suggested in the linked comment by @Miboch, the issue isn't resolved. I don't know, maybe the output-path default has changed for new projects?

**Comment by Venipa** [comment] 2020-02-28 14:52
make a js file, replace <script with <script type="..." in any index file after build
just a workaround which should work.

**Comment by westlakem** [comment] 2020-02-29 04:38
@Venipa That doesn't work when you have a codebuild, or any other continuous deployment project that bundles your application for deployment.  Why is angular the only platform that's having you modify assets that they build?

**Comment by westlakem** [comment] 2020-02-29 04:40
There are no shortage of workarounds, but they all require you changing something that the CLI bundles and builds for you.  Why the angular team won't address this is beside me.  Is angular the next project that google orphans?

**Comment by IgorMinar** [comment] 2020-02-29 16:43
I'll take a look at this next week. Just for the record, we are trying very hard to be receptive to the community feedback, but we simply cannot guarantee that every single issue will be resolved promptly and to the everyone's liking. On the other hand legitimate issues do fall through the cracks occasionally and we do course correct when necessary. All we ask is that everyone collaborates while assuming good intentions and uses empathy, kindness and comparison when resolving conflicts.

**Comment by westlakem** [comment] 2020-02-29 17:33
I appreciate you looking into it @IgorMinar .  @alan-agius4 commented on the issue mentioned, which his comment got a lot of "downvote" and "confused" responses, as well as many, many comments after the fact of potential "workarounds" for this issue that it appeared the Angular team wasn't going to address, and no one from the Angular team spoke a word of it since.

I know you have 2800+ open issues (yikes) but you might want to have someone on the team monitor recently closed issues, just in case the community highly disagrees with the reasoning for closing the issue.

**Comment by Splaktar** [comment] 2020-03-01 00:46
The solution [here](https://stackoverflow.com/a/59886825/633107) seems very relevant. Nginx's default MIME configuration does not support the "module" MIME type.

You mentioned Google in the OP, but I don't see this when hosting Angular version 8+ apps on Google App Engine or Firebase. I also don't see Google mentioned in any of the linked threads/issues.

### AWS S3

It looks like you can set the MIME type of files in s3 via [the AWS console](https://stackoverflow.com/questions/19100858/how-do-you-change-the-mime-on-amazon-s3) or via [the API](https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutObject.html) as `Content-Type`. Some third party s3 upload tools will let you configure the `Content-Type` in the tool.

### Azure Blog Pages

I'm not at all familiar with Azure Blog Pages, but it does appear that you can both register the `module` MIME type and set `text/javascript` as the default MIME type for `.js` files
- https://stackoverflow.com/a/11846971/633107
- https://blogs.iis.net/richma/adding-mime-types-to-your-windows-azure-web-site
- https://stackoverflow.com/a/44790362/633107

### GitHub Pages

GitHub Pages has a support page for MIME types 
- https://help.github.com/en/github/working-with-github-pages/about-github-pages#mime-types-on-github-pages

**Comment by atscott** [comment] 2020-03-02 23:21
#30835 has been reopened so I'll close this one to avoid duplication of discussions.

**Closed by atscott** 2020-03-02 23:21 UTC
Labels: hotlist: devrel
