### ISSUE TITLE
After app is destroyed router keeps track of location

### ISSUE THREAD

**Issue by kirill-konshin** [angular/angular#20491] opened 2017-11-17 01:21 UTC
## I'm submitting a...

```
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
```

## Minimal reproduction of the problem with instructions

http://plnkr.co/edit/YCtSvp0dhps6fdIE5gGe

Make sure that `**` route is not set (for sake of simple reproducibility), here is the snippet from `main.ts`:

```js
(async () => {

  const platform = platformBrowserDynamic();
  const appModule = await platform.bootstrapModule(AppModule);

  window['kill'] = () => {
    appModule.destroy();
    platform.destroy();
    window.location.hash = '#/xxx';
  };
  
})();
```

Run in browser console (as if something external is trying to kill the Angular app):

```js
kill();
```

## Current behavior

![image](https://user-images.githubusercontent.com/1530410/32924550-03c1c3ee-caf2-11e7-9007-43d043f3c4da.png)

## Expected behavior
When app is destroyed all handlers should be disconnected and destroyed as well.

## Environment

```
Angular version: 5.0.0
```

**Comment by mhevery** [comment] 2017-11-17 03:55
Thank you for submitting the issue. All issues require a [plunker](https://plnkr.co/) which demonstrates the problem and how to reproduce it. Please re-open the issue or create a new issue once you have a reproducible use case.

We are sorry that we are so aggressive on closing the issues. We are overwhelmed with the number of issues we get, and so we only have time to look at the ones which are easy for us to reproduce.

**Comment by kirill-konshin** [comment] 2017-11-17 18:35
Here you go: http://plnkr.co/edit/YCtSvp0dhps6fdIE5gGe

Just click "Kill" button and observe error message in console.

**Comment by kirill-konshin** [comment] 2017-11-19 22:25
@mhevery is provided sandbox good enough?

**Comment by trotyl** [comment] 2017-11-20 03:11
Possibly duplicate of https://github.com/angular/angular/issues/19079?

**Comment by kirill-konshin** [comment] 2017-11-20 03:29
Looks like yes, but that one is for 4.x and this one is for 5.x, so I think it's OK to keep both.

**Comment by jasonaden** [comment] 2017-11-21 23:58
Closing as a duplicate of #19079. Yes, it's reproduced in 5.x, but there wouldn't have been a change between 5 and 4 in the router that would have changed this behavior.

**Closed by jasonaden** 2017-11-21 23:58 UTC
Labels: comp: router
