### ISSUE TITLE
Outbound Link Issue

### ISSUE THREAD

**Issue by talesofatlantis** [angular/angular#53972] opened 2024-01-18 14:51 UTC
### Describe the problem that you experienced

https://angular.dev/tutorials/learn-angular/updating-the-component-class

`The city property is of type string but you can omit the type because of [type inference in TypeScript](https://angular.dev/typescript.org/type-inference).`

Link needs to use / instead of full URL.

### Enter the URL of the topic with the problem

https://angular.dev/tutorials/learn-angular/updating-the-component-class

### If the problem is browser-specific, please specify the device, OS, browser, and version

```true
Not sure if it is but am using Microsoft Edge.
```

**Comment by JoostK** [comment] 2024-01-18 14:56
Thanks for the report, this is a duplicate of https://github.com/angular/angular/issues/52553 for which the fix is pending deployment.

**Closed by JoostK** 2024-01-18 14:56 UTC
