### ISSUE TITLE
The router HashLocationStrategy should not use the History API

### ISSUE THREAD

**Issue by drager** [angular/angular#12341] opened 2016-10-17 14:38 UTC
```
[x] bug report
```

The router HashLocationStrategy should not use the History API. When using the router with HashLocationStrategy it results in the following error:

```
main.aca1d67….bundle.js:1235 EXCEPTION: Uncaught (in promise): SecurityError: Failed to execute 
'replaceState' on 'History': A history state object with URL 'file:///#/' cannot be created in a document with 
origin 'file://' and URL 'file:///android_asset/www/index.html'.t.handleError @ 
main.aca1d67….bundle.js:1235
main.aca1d67….bundle.js:1235 ORIGINAL STACKTRACE:t.handleError @ 
main.aca1d67….bundle.js:1235
main.aca1d67….bundle.js:1235 Error: Uncaught (in promise): SecurityError: Failed to execute 
'replaceState' on 'History': A history state object with URL 'file:///#/' cannot be created in a document with 
origin 'file://' and URL 'file:///android_asset/www/index.html'.
```

**Comment by DzmitryShylovich** [comment] 2016-12-04 20:17
can u pls add a repro in plunkr?

**Comment by zoechi** [comment] 2016-12-05 06:41
Are you loading the application from a file URL? AFAIK this is not supported. You need to load from an HTTP server.

**Comment by DzmitryShylovich** [comment] 2016-12-17 20:05
@drager is this still an issue?

**Comment by drager** [comment] 2016-12-19 10:17
@DzmitryShylovich: I haven't tried it for while now so I don't really know. Is there any commit that points to a fix?

**Comment by DzmitryShylovich** [comment] 2016-12-19 10:19
>  points to a fix?

fix for what? u didn't provide sufficient info to understand or reproduce the issue 😄 
This is why I asked you for repro https://github.com/angular/angular/issues/12341#issuecomment-264727933

**Comment by drager** [comment] 2016-12-19 10:48
>fix for what?

A rewrite of HashLocationStrategy that does not use the History API.

>That's a browser limitation, not an Angular2 limitation.

That is why the HashLocationStrategy should not use the History API.

**Comment by DzmitryShylovich** [comment] 2016-12-19 10:59
Sorry, but it doesn't work like this.
> A rewrite of HashLocationStrategy that does not use the History API.

nobody will rewrite anything until there's a clear evidence of the issue with description and reproduction.

**Comment by zoechi** [comment] 2016-12-19 11:16
@drager 
> > That's a browser limitation, not an Angular2 limitation.

> That is why the HashLocationStrategy should not use the History API.

So you are actually loading from disk without using an HTTP server?
That's not supported and above error probably won't be your only issue. Therefore I don't see the point for this request.

**Comment by drager** [comment] 2016-12-19 12:38
@zoechi: That was what this issue was about :) but if you don't want to support it, just close it.

**Comment by oocx** [comment] 2017-07-14 05:53
There are also use cases where an app is served by a web server but calling the history api is still not allowed:

We run an Angular app in a browser control within a desktop client application. In this context, calls to window.history.replaceState are not allowed and cause the app to crash.

**Comment by phodal** [comment] 2018-10-11 08:55
I think  rewrite of HashLocationStrategy should be a better solution. 

Recently, we run our application in a mobile webView. With ``file://`` protocol, we can easily access remote resources without any CORS issue. But if we with start a HTTP server to run this, we will need a totally rewrite a HTTP client to fix CORS problem.

It seems this issue was hard to fixed, it's also two years.

**Comment by zoechi** [comment] 2018-10-11 09:07
You could just provide your own LocationStrategy.

**Comment by jelbourn** [comment] 2020-10-21 15:10
Closing this since it seems obsolete

**Closed by jelbourn** 2020-10-21 15:10 UTC
Labels: comp: router, feature, freq1: low, router: LocationStrategy, triage #1, type: confusing, type: support
