### ISSUE TITLE
Question: How can I specialize a component without breaking ngContent?

### ISSUE THREAD

**Issue by fenduru** [angular/angular#6307] opened 2016-01-06 21:29 UTC
What is the correct way to specialize a component in a way that doesn't break `ngContent`?

http://plnkr.co/edit/jS8JHmD0xibJ8UGOKlCC?p=preview

In this example I have a button container that contains an `<ng-content select="my-button">`. The problem is what happens if my-button has various options that I want to abstract over and create my-specialized button?

**Comment by zoechi** [comment] 2016-01-07 10:08
> In this example I have a button container that contains an .

seems to be missing something at the end of the sentence. Please wrap inline code with `

**Comment by fenduru** [comment] 2016-01-07 16:06
@zoechi thank you, fixed (I forgot my backticks)

**Comment by pkozlowski-opensource** [comment] 2016-06-16 08:23
@fenduru I've just spend some time looking at your plunk and it is not clear to me at all what are you trying to achieve / what doesn't work... Could you please clearly describe current vs. expected behavior? Expose your real-life use-case?

Going to close this one till we've got more info, happy to re-open then.

**Closed by pkozlowski-opensource** 2016-06-16 08:23 UTC
