### ISSUE TITLE
SCRIPT5009: 'System' is undefined  

### ISSUE THREAD

**Issue by Sri276286** [angular/angular#12970] opened 2016-11-18 14:53 UTC
SCRIPT5009: 'System' is undefined  

I am still facing this issue. I tried including whatever told 

My index.html
---------------------

```
<html>

<head>
    <title>RPortal</title>
    <base href="/">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- inject:js -->
    <script src="system.src.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/es6-shim/0.33.3/es6-shim.min.js"></script>
    <script src="https://npmcdn.com/angular2/es6/dev/src/testing/shims_for_IE.js"></script>
    <script src="vendors.min.js"></script>
    <script src="lib.bundle.js"></script>
    <script src="system-config.js"></script>
    <!-- endinject -->
</head>

<body>
    <app-root>Loading...</app-root>
    <script>
        System.import('main.js');
    </script>
</body>

</html>
```

In vendors.min.js, I bundled polyfills from

```
 import 'core-js/es6/symbol';
 import 'core-js/es6/object';
 import 'core-js/es6/function';
import 'core-js/es6/parse-int';
import 'core-js/es6/parse-float';
import 'core-js/es6/number';
import 'core-js/es6/math';
import 'core-js/es6/string';
import 'core-js/es6/date';
import 'core-js/es6/array';
import 'core-js/es6/map';
import 'core-js/es6/set';
import 'core-js/es6/reflect';
import 'core-js/es7/reflect';
```

Please help me.

Please let me know if any information needed.

**Comment by ericmartinezr** [comment] 2016-11-18 14:54
https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

**Comment by Sri276286** [comment] 2016-11-18 15:31
I referenced all those references. still I couldn't fix it

**Comment by webprofusion-chrisc** [comment] 2016-11-18 23:36
Use Ionic 2 - it currently works out of the box and does the bundling for you.

**Comment by robwormald** [comment] 2016-11-23 03:09
I'm closing this because 
[ x ] you deleted the issue template.
[ x ] you did not provide a reproduction of the issue.
[ x ] this is a support question.

**Closed by robwormald** 2016-11-23 03:09 UTC
