### ISSUE TITLE
Angular 15.0.0: extremely strange behavior in Chrome's DevTools

### ISSUE THREAD

**Issue by artuska** [angular/angular#48151] opened 2022-11-21 19:28 UTC
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

1. do not create an app with `ng new`
2. just upgrade your own application to the Angular 15.0.0
3. open your app in any latest Chromium-based browser (Google Chrome, Microsoft Edge)
4. inspect any DOM element
5. this will open DevTools styles pane
6. uncheck or change any style rule

Now inspected element's styles will double; some other element's styles will just disappear breaking your layout.

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.0.0
Node: 18.12.1
Package Manager: npm 9.1.1
OS: win32 x64

Angular: 15.0.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... elements, forms, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1500.0
@angular-devkit/build-angular   15.0.0
@angular-devkit/core            15.0.0
@angular-devkit/schematics      15.0.0
@schematics/angular             15.0.0
rxjs                            7.5.7
typescript                      4.8.4
```

**Comment by artuska** [comment] 2022-11-21 19:30
This behavior is relevant for all Chromium based browsers (checked in Crome, Edge); in Firefox everything is fine.

**Comment by FetterBaby** [comment] 2022-11-21 19:35
I've got same problem

**Comment by JoostK** [comment] 2022-11-21 20:26
This doesn't seem to reproduce on angular.io (an Angular 15 app), can you share a repro?

**Comment by FetterBaby** [comment] 2022-11-21 21:14
@JoostK 
I hope this is clear enough, this is my first experience of participating in such things, I may be incorrect, sorry if this is so
https://user-images.githubusercontent.com/108720183/203159159-4e6b3564-85bf-4680-a251-35219a5d198e.mov

**Comment by JoostK** [comment] 2022-11-21 21:19
That is almost certainly a Chrome bug.

**Comment by ardesbois** [comment] 2022-12-05 13:14
i've got same problem only from ng serve
no problem with the package generated from ng build (deployed into apache server)

**Comment by JoostK** [comment] 2022-12-09 22:35
I am going to close this in favor of #48425 since that includes a reproduction.

**Closed by JoostK** 2022-12-09 22:35 UTC
Labels: needs reproduction, area: devtools
