### ISSUE TITLE
Attaching a jQuery event handler triggers change detection for that event for every element

### ISSUE THREAD

**Issue by dianabarsan** [angular/angular#40606] opened 2021-01-28 04:09 UTC
# 🐞 bug report

### Description

Attaching an event handler with `jQuery("body").on` will trigger change detection when the event is triggered on any element! 

## 🔬 Minimal Reproduction
Minimal reproduction: https://stackblitz.com/edit/angular-ivy-czsfzb?devtoolsheight=33&file=src/app/hello.component.ts

Moving your mouse in/out of text + clicking *anywhere* on the page should log stuff in the console:
![image](https://user-images.githubusercontent.com/35681649/106087391-90291980-612c-11eb-8e0f-9fca6a180c8c.png)
Additionally, these call stacks can be seen: 
![image](https://user-images.githubusercontent.com/35681649/106087459-b8187d00-612c-11eb-8bc1-e2ddc748c000.png)
![image](https://user-images.githubusercontent.com/35681649/106087489-c8c8f300-612c-11eb-9b19-aaf4e3473315.png)

## 🌍  Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 11.0.7
Node: 12.14.1
OS: win32 x64

Angular: 11.1.1
... animations, common, compiler, core, forms, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.7
@angular-devkit/build-angular   0.1100.7
@angular-devkit/core            11.0.7
@angular-devkit/schematics      11.0.7
@angular/cli                    11.0.7
@angular/compiler-cli           11.0.9
@schematics/angular             11.0.7
@schematics/update              0.1100.7
rxjs                            6.6.3
typescript                      4.0.5
</code></pre>

**Anything else relevant?**
This doesn't seem to be browser specific, or version specific. 
I've initially seen this on Angular 10 + jQuery 3.2.x. The linked repro uses latest for both.

**Comment by dianabarsan** [comment] 2021-01-28 05:41
I want to clarify that running the code that attaches the jQuery event handlers outside of Angular zone fixes the issue. 
reproduced here: https://angular-ivy-5mzqws.stackblitz.io

**Comment by gkalpak** [comment] 2021-01-28 11:05
That is expected behavior from what I can tell. `jQuery('body').on(...)` will attach an event handler on `<body>` and thus it will be triggered for any [bubbling][1] event (from any element inside `<body>`).

NOTE:
Passing a selector as a second argument to `.on()` to "filter" events is a jQuery-only concept. I.e. jQuery will attach the listener with the built-in `addEventListener()` method and then it will examine the event's target and determine whether it needs to call your handler. The native event will be dispatched always (regardless of the whether the event target matches the specified selector).

##
As you already mentioned, if you don't want this to happen you should call the `.on()` method outside the Angular zone (and you could re-enter the Angular zone in your event handler if necessary.

I am going to close this issue, since everything works an intended (afaict), but feel free to continue the discussion below.

[1]: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Events#event_bubbling_and_capture

**Closed by gkalpak** 2021-01-28 11:05 UTC

**Comment by dianabarsan** [comment] 2021-01-28 16:02
@gkalpak Thanks for the answer and the explanation.

After spending some time reading zone.j` code today, I understand why this is happening. 
I agree with the fact that it's intended behavior. 

However, given the seriousness of this side-effect, I think there should be some large disclaimer somewhere, or at least an eslint rule to raise awareness!

**Comment by gkalpak** [comment] 2021-01-28 21:01
Yeah, the truth is that our documentation on Zone.js is lacking. There are currently two issues tracking the work of adding more documentation on Zone.js and app performance (#28493 and #34735). Feel free to post a comment there to make sure we mention that when we create the docs.

Also, if you have any other ideas on where such a notice would be helpful today, feel free to create a pull request :wink:
