### ISSUE TITLE
[Feature] Add a target to the Output decorator as to not restrict it to parent 

### ISSUE THREAD

**Issue by cedvdb** [angular/angular#12455] opened 2016-10-22 04:45 UTC
**I'm submitting a ...** 
```
[ X ] feature request
```

**Current behavior**

At the moment when a component wants to communicate with another component to which he is not directly related it has to use a service since only a parent can "subscribe" to an event emitted by its children.

This means that if we have a scenario like this where `grand-grand-son3` wants to talk to `grand-son-2` we have to use a service (or a dirty combination of  ViewChild):

```
<parent>
    <child-1>
        <grand-son-1>
             <grand-grand-son3></grand-grand-son3>
        </grand-son1>
    </child-1>
    <child-2>
        <grand-son-2>
        </grand-son2>
    </child-2>
</parent>
```

Creating a service for a simple click that manages the color of grand-son-2 would be silly. So one creates a service that deals with everything inside the `parent` and every components subscribe to it as needed. This way parent doesn't have a dozen services related to it. I like this solution but it's a lot of boiler plate just to change a color. It also breaks the principle of least privilege a bit. If there was a grandson-4, maybe I wouldn't want him to be able to subscribe to a specific event.

Another option is not to break components in mini components. In other words bigger components to not deal with yet again another service. I don't like this solution but I think the current behavior somewhat encourages that in some instances. 

**What I'm proposing**

```
 @Output(null, MyTargetComponent) sonClicked= new EventEmitter<any>();
```
It's easy and is in my opinion cleaner than a service.

* **Angular version:** 2.0.0

**Comment by ericmartinezr** [comment] 2016-10-22 12:54
See this discussion https://github.com/angular/angular/issues/2296

**Comment by pkozlowski-opensource** [comment] 2016-10-22 18:31
Yes, this is duplicate of #2296, thnx @ericmartinezr

**Closed by pkozlowski-opensource** 2016-10-22 18:31 UTC
