### ISSUE TITLE
Hyperlink to "type inference in TypeScript" is getting page not found message

### ISSUE THREAD

**Issue by akashmadhavai** [angular/angular#52563] opened 2023-11-07 04:07 UTC
### Describe the problem that you experienced

I was going through new tutorials section where in one of the paragraph is the link to [type inference in TypeScript](https://angular.dev/typescript.org/type-inference), which is giving page not found message.

### Enter the URL of the topic with the problem

https://angular.dev/tutorials/learn-angular/updating-the-component-class

### Describe what you were looking for in the documentation

I was just exploring new tutorials section 

### Describe the actions that led you to experience the problem

Clicking on hyperlink of [type inference in TypeScript]

### Describe what you want to experience that would fix the problem

User should get navigated to typescript docs to read more about [type inference in TypeScript]

### Add a screenshot if that helps illustrate the problem

![image](https://github.com/angular/angular/assets/51307156/91f67882-64ae-4af0-8857-02e3a94f2fe2)

### If the problem is browser-specific, please specify the device, OS, browser, and version

```true
Macbook pro, macOS Sonoma 14.1
chrome Version 118.0.5993.117
```

**Comment by atscott** [comment] 2023-11-07 04:21
Duplicate of https://github.com/angular/angular/issues/52553

**Closed by atscott** 2023-11-07 04:21 UTC
