### ISSUE TITLE
Incorrect error message: `Could not resolve /my/missing/import relative to [object Object]`

### ISSUE THREAD

**Issue by joe-denea** [angular/angular#30832] opened 2019-06-03 19:17 UTC
# 🐞 bug report

### Affected Package

The issue is caused by package @angular/compiler

### Is this a regression?

Yes, the previous version in which this bug was not present was: prior to [pull 26759](https://github.com/angular/angular/pull/26759)

### Description

On line 423-424 in [static_symbol_resolver](https://github.com/angular/angular/pull/26759/commits/08df043399a78e251fdb8be47a2f3d8078e75bff#diff-2b2c85ebf30d6d9cbb4fbed0d8729692) in [pull 26759](https://github.com/angular/angular/pull/26759) the following line was changed to call `self.host.getMetadataFor` on the filepath. This change causes the returned value to be an object, which is then inserted into the template string, producing the output `[object Object]`.

```TypeScript
message:
  `Could not resolve ${module} relative to ${self.host.getMetadataFor(sourceSymbol.filePath)}.`,
```

On a separate note the period at the end of the statement is duplicated when it is logged out so it could be removed here.

## 🔬 Minimal Reproduction

Can be reproduced by forcing the relevant error to be thrown, or simply taking the template string provided and passing it any object type where `self.host.getMetadataFor(sourceSymbol.filePath)` is.

## 🔥 Exception or Error

```text
Could not resolve /my/missing/import relative to [object Object]
```

## 🌍  Your Environment

**Angular Version:** `8.1.0-beta.0`

**Anything else relevant?** Google Environment

**Comment by alxhub** [comment] 2019-06-04 22:49
Hello @joe-denea,

Thank you for tracking down the PR which caused this. Can you also include a reproduction - a repository with code that produces the error, and instructions on how to run the build? Without a reproduction it's difficult for us to both identify the issue and to verify that it's fixed.

**Comment by joe-denea** [comment] 2019-06-05 02:37
Hey @alxhub 

I already identified the issue in the actual code. `getMetaDataFor` returns an object type and that return value is being directly inserted into an ES6 template literal, producing the output `[object Object]`. Any object inserted into a template literal will produce this output and thus any return value generated by `getMetaDataFor` will produce this output. There is nothing else I could make clear by creating a repro repository, the entire issue is that `` `${{}}` `` = `'[object Object]'` so the code I referenced is fundamentally incorrect. Likely the intent was to access a particular property of the returned metadata object to get a relative path or something. You might have a better idea what the intent was since you wrote the PR in question.

**Comment by alxhub** [comment] 2020-02-28 23:22
@joe-denea 

Likely the intent was to call `self.host.getOutputName` instead of `self.host.getMetadataFor`.

Given that this is in View Engine code, I'm inclined to close this as the metadata system is going away in its entirety with Ivy, and without a reproduction demonstrating the issue it would take me too long to develop a test for the admittedly trivial fix.

**Comment by petebacondarwin** [comment] 2020-11-02 20:15
Closing due to a lack of reproduction, and also since it only affects the deprecated ViewEngine compiler mode.

**Closed by petebacondarwin** 2020-11-02 20:15 UTC
Labels: P5, comp: compiler, engine: ve, freq1: low, needs clarification, needs reproduction, regression, state: confirmed, triage #1, type: bug/fix
