### ISSUE TITLE
Failed to compile after adding @angular/pwa

### ISSUE THREAD

**Issue by neofuture** [angular/angular#33910] opened 2019-11-18 22:29 UTC
# 🐞 bug report

### Affected Package
@angular/pwa 

### Description
Added Angular/PWA and failed to complie

## 🔥 Exception or Error
<pre><code>
> ng serve

10% building 3/3 modules 0 activeℹ ｢wds｣: Project is running at http://localhost:4200/webpack-dev-server/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: 404s will fallback to //index.html

chunk {0} 0.js, 0.js.map () 1.25 kB  [rendered]
chunk {1} 1.js, 1.js.map () 1.18 kB  [rendered]
chunk {2} 2.js, 2.js.map () 1.18 kB  [rendered]
chunk {3} 3.js, 3.js.map () 1.18 kB  [rendered]
chunk {main} main.js, main.js.map (main) 266 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 140 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 8.97 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 51.5 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 3.04 MB [initial] [rendered]
Date: 2019-11-18T22:24:01.030Z - Hash: 5b571da310162fd20b1e - Time: 19153ms

ERROR in ./node_modules/@angular/common/__ivy_ngcc__/fesm2015/common.js 4904:4-16
"export 'ɵLOCALE_DATA' was not found in '@angular/core'
ERROR in ./node_modules/@angular/common/__ivy_ngcc__/fesm2015/common.js 4906:8-20
"export 'ɵLOCALE_DATA' was not found in '@angular/core'
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
ℹ ｢wdm｣: Failed to compile.
</code></pre>

```
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.0.0-rc.0
Node: 12.13.0
OS: darwin x64
Angular: 9.0.0-rc.1
... core

Package                             Version
-------------------------------------------------------------
@angular-devkit/architect           0.900.0-rc.0
@angular-devkit/build-angular       0.900.0-rc.0
@angular-devkit/build-optimizer     0.900.0-rc.0
@angular-devkit/build-webpack       0.900.0-rc.0
@angular-devkit/core                9.0.0-rc.0
@angular-devkit/schematics          9.0.0-rc.0
@angular/animations                 9.0.0-rc.0
@angular/cdk                        8.2.3
@angular/cli                        9.0.0-rc.0
@angular/common                     9.0.0-rc.0
@angular/compiler                   9.0.0-rc.0
@angular/compiler-cli               9.0.0-rc.0
@angular/forms                      9.0.0-rc.0
@angular/language-service           9.0.0-rc.0
@angular/platform-browser           9.0.0-rc.0
@angular/platform-browser-dynamic   9.0.0-rc.0
@angular/router                     9.0.0-rc.0
@ngtools/webpack                    9.0.0-rc.0
@schematics/angular                 9.0.0-rc.0
@schematics/update                  0.900.0-rc.0
rxjs                                6.5.3
typescript                          3.6.4
webpack                             4.41.2
```

**Comment by neofuture** [comment] 2019-11-18 23:03
How I got round the issue (Mac)

1) Created a brand new project
2) Update to RC.2
3) ng add @angular/pwa
4) Copy over source from other project
5) make sure the changes are in the jsons retained, they got nuked Doh !!!
6) Nuke node_modules
7) SUDO ng add @angular/pwa
8) Nuke node_modules again
9) yarn install
10) Compile
11) ng build --prod now has service workers

**Comment by neofuture** [comment] 2019-11-18 23:05
<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.0.0-rc.2
Node: 12.13.0
OS: darwin x64
Angular: 9.0.0-rc.2
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-rc.2
@angular-devkit/build-angular     0.900.0-rc.2
@angular-devkit/build-optimizer   0.900.0-rc.2
@angular-devkit/build-webpack     0.900.0-rc.2
@angular-devkit/core              9.0.0-rc.2
@angular-devkit/schematics        9.0.0-rc.2
@angular/cdk                      8.2.3
@angular/pwa                      0.803.19
@ngtools/webpack                  9.0.0-rc.2
@schematics/angular               8.3.19
@schematics/update                0.900.0-rc.2
rxjs                              6.5.3
typescript                        3.6.4
webpack                           4.41.2
</code></pre>

**Comment by IgorMinar** [comment] 2019-11-19 07:51
this is strange. can you please provide information/steps/repo on how to reproduce this problem? thanks

**Comment by gkalpak** [comment] 2019-11-19 10:30
Based on the `ng version` info in your original comment, it seems that you had mismatching version of `@angular/core` and `@angular/*` packages in your `package.json`:

- `@angular/core`: 9.0.0-rc.1
- `@angular/{animations,common,compiler,compiler-cli,forms,language-service,platform-browser,platform-browser-dynamic,router}`: 9.0.0-rc.0

That would explain the problem (you should always have matching versions). The real problem is how you ended up with mismiatching versions. Maybe it was a pre-RC `ng update` bug that has since been fixed, as you said.

Given that we don't have a reproduction and you got it working, I am going to close this issue.

**Closed by gkalpak** 2019-11-19 10:30 UTC
Labels: comp: ngcc, state: Needs repro
