### ISSUE TITLE
i18n Ivy extractor only reports the first location context

### ISSUE THREAD

**Issue by laurentgoudet** [angular/angular#39330] opened 2020-10-19 15:36 UTC
Small repro in https://github.com/laurentgoudet/ivy-xi18n-bug.

Steps:
- Create a new project & `ng add @angular/localize`
- Add `i18n` tags to a couple of tags, one of them being duplicated (https://github.com/laurentgoudet/ivy-xi18n-bug/blob/master/src/app/app.component.html#L343), to simulate the same piece of text being repeated across an application

```
  <!-- Resources -->
  <h2>Resources</h2>
  <p i18n>Here are some links to help you get started:</p>
  <p i18n>Here are some links to help you get started:</p>
```

- Run `ng xi18n`: the dictionary (https://github.com/laurentgoudet/ivy-xi18n-bug/blob/master/messages-ve.xlf) shows all the location references

```
      <trans-unit id="2b26c7522dda8ad6bc76a0462d7a3c94f0f8a688" datatype="html">
        <source>Here are some links to help you get started:</source>
        <context-group purpose="location">
          <context context-type="sourcefile">src/app/app.component.html</context>
          <context context-type="linenumber">343</context>
        </context-group>
        <context-group purpose="location">
          <context context-type="sourcefile">src/app/app.component.html</context>
          <context context-type="linenumber">344</context>
        </context-group>
      </trans-unit>
```

- Run `ng x18n --ivy`:  the dictionary (https://github.com/laurentgoudet/ivy-xi18n-bug/blob/master/messages.xlf) only shows the first location reference

```
      <trans-unit id="2b26c7522dda8ad6bc76a0462d7a3c94f0f8a688" datatype="html">
        <source>Here are some links to help you get started:</source>
        <context-group purpose="location">
          <context context-type="sourcefile">src/app/app.component.html</context>
          <context context-type="linenumber">343</context>
        </context-group>
      </trans-unit>
```

This means translators have less context to understand how a piece of text is used across an app.

**Comment by petebacondarwin** [comment] 2020-10-19 15:43
Thanks for this @laurentgoudet 
It is actually a duplicate of https://github.com/angular/angular/issues/39314
But since you provide an actual reproduction, I will close that and keep this.

**Closed** 2020-10-26 17:52 UTC
Labels: P3, comp: i18n, state: has PR
