### ISSUE TITLE
Tour of Heroes subject/observable code requires an extra conversion call in order to compile

### ISSUE THREAD

**Issue by MikeBeaton** [angular/angular#18422] opened 2017-07-31 10:06 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

The Subject/Observable code in [Tour of Heroes Section 7](https://angular.io/tutorial/toh-pt6) does not compile.

The code:

```
this.searchTerms
    .debounceTime(300)
```

will not compile for me, giving the error:

```
The 'this' context of type 'Subject<string>' is not assignable to method's 'this' of type 'Observable<string>'.
```

## Expected behavior

When I change to code to:

```
this.searchTerms
    .asObservable()
    .debounceTime(300)
````

then the code compiles and works (I think) as expected.

## Environment

<pre><code>
Angular version: 4.0.3

For Tooling issues:
- Node version: 6.11.1  
- Platform: Windows 10 v1703 

Others:

- IDE: Visual Studio Code 1.14.2
</code></pre>

**Comment by thienedits** [comment] 2017-10-05 22:30
I think updating to rxjs 5.4.3 and typescript 2.4.1 made it work

**Comment by gkalpak** [comment] 2017-10-05 22:53
I just tried downloading the example and building and everything worked fine 😕.

I downloaded it from [this link][1] and ran `yarn install` and `yarn build`. I tried with yarn@1.0.2 and yarn@1.1.0 and also with `npm@3.10.10` (all on node@6.11.3).

There is indeed some incompatibility with certain combinations of RxJS/TypeScript versions, but using the ones provided in the example (or the latest ones for both packages) should work.

##
Since this issue is old (and we have since updated some of the dependencies), I am going to close it. If you are still facing problems, please open a new issue providing all the necessary steps/info for reproducing the failure.

[1]: https://angular.io/generated/zips/toh-pt6/toh-pt6.zip

**Closed by gkalpak** 2017-10-05 22:53 UTC
Labels: comp: docs, type: bug
