### ISSUE TITLE
Provide information on loaded lazy routes on RouteConfigLoadEnd

### ISSUE THREAD

**Issue by meeroslav** [angular/angular#16282] opened 2017-04-24 15:40 UTC
**I'm submitting a ...** (check one with "x")

```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When accessing modules lazily, RouteConfigLoadEnd gets fired once the factory gets loaded, but before routes are loaded and assigned to `route._loadedConfig`. 

**Expected behavior**
RouteConfigLoadEnd should be fired after `_loadedConfig` is assigned, or return routes as a parameter if it's fired from `RouterConfigLoader`.

Change proposal:

```ts
return map.call(moduleFactory$, (factory: NgModuleFactory<any>) => {
  const module = factory.create(parentInjector);
  const routes = flatten(module.injector.get(ROUTES));

  if (this.onLoadEndListener) {
    this.onLoadEndListener(route, routes);
  }

  return new LoadedRouterConfig(routes, module);
});
```

**What is the motivation / use case for changing the behavior?**
Most common use case of `RouteConfigLoadEnd` is to react once lazy loaded routes are loaded. In [localize-router](https://github.com/Greentube/localize-router) we can use this information for routes localization. However if even is fired before routes are de facto available in `_loadedConfig` and/or it doesn't provide this information it makes the entire event unusable as it's not that different from RouteConfigLoadStart.

Issue is already mentioned here: [https://github.com/angular/angular/issues/14036](https://github.com/angular/angular/issues/14036)

* **Angular version:** 4.0.X

* **Browser:** all

* **Language:** all

**Comment by George02** [comment] 2017-08-30 14:58
+1

**Comment by CamusAran** [comment] 2017-09-21 00:43
@jasonaden any update on this?

**Comment by marko999** [comment] 2017-11-29 16:28
+1
important, also some router implementations like localize-router depending on this

**Comment by meeroslav** [comment] 2017-11-29 20:02
@marko999, actually `localize-router` no longer depends on this.

With the help from @vsavkin, there is a workaround using `SystemJsNgModuleLoader` that solves the lazy loading problem and does not require changes in the Router's code. 

So unless there are some other interested parties in this feature, this issue can be closed.

@conor-mac-aoidh, @brandonroberts, @johnpapa, are you still interested in having this event as mentioned in #14036?

Maybe extending `SystemJsNgModuleLoader` would work for you as well?:

```ts
export class YourCustomLoader extends SystemJsNgModuleLoader {

  load(path: string): Promise<NgModuleFactory<any>> {
    return super.load(path).then((factory: NgModuleFactory<any>) => {
      return {
        moduleType: factory.moduleType,
        create: (parentInjector: Injector) => {
          const module = factory.create(parentInjector);
          const getMethod = module.injector.get.bind(module.injector);

          module.injector['get'] = (token: any) => {
            const getResult = getMethod(token);

            if (token === ROUTES) {
              // This is the place where routes are loaded, but not yet returned
              // Do some custom magic here, throw a custom event etc.
              return getResult;
            } else {
              return getResult;
            }
          };
          return module;
        }
      };
    });
  }
}
```

You can see how it was (mis)used in `localize-router` [here](https://github.com/Greentube/localize-router/blob/master/src/localize-router-config-loader.ts).

**Comment by hdrdiab** [comment] 2017-11-30 09:39
Hi,
I have a problem with the nested routes of a Lazy Loaded module,throwing an error when navigating between child routes, is that a normal behavior from the angular router? I mean will we see any solution other than we extending the `SystemJsNgModuleLoader`.

**Comment by HMubaireek** [comment] 2019-06-03 02:30
The mentiond solution by @meeroslav doesn't work anymore as SystemJsNgModuleLoader got depricated with Angular 8

**Comment by atscott** [comment] 2022-02-01 00:15
Closing as duplicate of #40010 / #44577 / #24069

**Closed by atscott** 2022-02-01 00:15 UTC
Labels: feature, comp: router, router: lazy loading, insufficient votes, votes required
