### ISSUE TITLE
ngcc error: path is not absolute

### ISSUE THREAD

**Issue by filipesilva** [angular/angular#28754] opened 2019-02-15 11:10 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/core

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 8.0.0-beta.3

### Description

Running ngcc fails with `Error: Internal Error: AbsoluteFsPath.from(D:/sandbox/ivy-latest-project/node_modules/@angular/animations): path is not absolute`

## 🔬 Minimal Reproduction

- `ng new ngcc-issue --experimentalIvy --next && cd ngcc-issue`
- use snapshots for https://github.com/angular/angular/commit/8accc98d28249628e84136d7306fdbbe1f4caaef:
```
// deps
    "@angular/animations": "8.0.0-beta.3",
    "@angular/common": "8.0.0-beta.3",
    "@angular/compiler": "github:angular/compiler-builds#8.0.0-beta.3+8accc98",
    "@angular/core": "github:angular/core-builds#8.0.0-beta.3+8accc98",
    "@angular/forms": "github:angular/forms-builds#8.0.0-beta.3+8accc98",
    "@angular/platform-browser": "github:angular/platform-browser-builds#8.0.0-beta.3+8accc98",
    "@angular/platform-browser-dynamic": "github:angular/platform-browser-dynamic-builds#8.0.0-beta.3+8accc98",
    "@angular/router": "github:angular/router-builds#8.0.0-beta.3+8accc98",
//devdeps
    "@angular/compiler-cli": "github:angular/compiler-cli-builds#8.0.0-beta.3+8accc98",
    "@angular/language-service": "github:angular/language-service-builds#8.0.0-beta.3+8accc98",
```
- `rm -rf node_modules && npm i`

## 🔥 Exception or Error
<pre><code>
> ivy-latest-project@0.0.0 postinstall D:\sandbox\ivy-latest-project
> ivy-ngcc

Error: Internal Error: AbsoluteFsPath.from(D:/sandbox/ivy-latest-project/node_modules/@angular/animations): path is not absolute
    at Object.from (D:\sandbox\ivy-latest-project\node_modules\@angular\compiler-cli\src\ngtsc\path\src\types.js:30:23)
    at Object.makeEntryPointBundle (D:\sandbox\ivy-latest-project\node_modules\@angular\compiler-cli\src\ngcc\src\packages\entry_point_bundle.js:41:47)
    at D:\sandbox\ivy-latest-project\node_modules\@angular\compiler-cli\src\ngcc\src\main.js:68:55
    at Array.forEach (<anonymous>)
    at D:\sandbox\ivy-latest-project\node_modules\@angular\compiler-cli\src\ngcc\src\main.js:63:25
    at Array.forEach (<anonymous>)
    at Object.mainNgcc (D:\sandbox\ivy-latest-project\node_modules\@angular\compiler-cli\src\ngcc\src\main.js:56:25)
    at D:\sandbox\ivy-latest-project\node_modules\@angular\compiler-cli\src\ngcc\main-ngcc.js:17:35
    at D:\sandbox\ivy-latest-project\node_modules\@angular\compiler-cli\src\ngcc\main-ngcc.js:4:17
    at Object.<anonymous> (D:\sandbox\ivy-latest-project\node_modules\@angular\compiler-cli\src\ngcc\main-ngcc.js:10:3)
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 7.3.1
Node: 10.10.0
OS: win32 x64
Angular: 8.0.0-beta.3
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.1
@angular-devkit/build-angular     0.14.0-beta.0
@angular-devkit/build-optimizer   0.14.0-beta.0
@angular-devkit/build-webpack     0.14.0-beta.0
@angular-devkit/core              7.3.1
@angular-devkit/schematics        7.3.1
@angular/cli                      7.3.1
@ngtools/webpack                  8.0.0-beta.0
@schematics/angular               7.3.1
@schematics/update                0.13.1
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.29.3
</code></pre>

**Anything else relevant?**
cc @petebacondarwin @gkalpak

**Comment by devversion** [comment] 2019-02-15 11:20
@filipesilva Possibly related to @alan-agius4's PRs: #28752

**Comment by alan-agius4** [comment] 2019-02-15 11:22
Yeah that is correct

**Comment by stefanocke** [comment] 2019-02-26 16:15
Confirmed that this is still an issue with 8.0.0-beta.5.

**Comment by alan-agius4** [comment] 2019-02-26 16:20
The fix has not been merged yet.

**Closed** 2019-02-27 19:28 UTC
Labels: comp: core & compiler

**Comment by johncrim** [comment] 2019-03-06 18:29
Also still an issue in 8.0.0-beta.6 + @angular/cli 8.0.0-beta.4 .

**Comment by alan-agius4** [comment] 2019-03-06 18:32
This will be released in 8.0.0-beta.7

Thanks

**Comment by alan-agius4** [comment] 2019-03-06 18:53
This has been just released.

**Comment by thesayyn** [comment] 2019-04-09 12:35
FYI: This issue still persists in beta.11

**Comment by stefanocke** [comment] 2019-04-10 17:44
@thesayyn , it worked for me since beta.7 and it stills works in beta.11

**Comment by thesayyn** [comment] 2019-04-10 21:50
Strange I'm still getting this error sometimes.
