### ISSUE TITLE
RC 4 no longer guarantees your order of css classes to an element

### ISSUE THREAD

**Issue by frankadrian** [angular/angular#34219] opened 2019-12-03 21:15 UTC
# 🐞 bug report

### Affected Package

 

The issue is caused by package @angular/compiler

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 8.2.8

### Description

 
When defining an element, in an html file, with multiple css classes the order of theses classes is no longer guranteed.
For example:

    <div class="center aligned">
        ...
    </div>

the element gets rendered in the dom like so:

    <div _ngcontent-ikg-c67="" class="aligned center ng-tns-c67-1">
        ...
    </div>

## 🔥 Exception or Error
<pre><code>

no error
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 9.0.0-rc.4
Node: 12.11.1
OS: darwin x64

Angular: 9.0.0-rc.4
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, platform-browser, platform-browser-dynamic, router
... service-worker
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-rc.4
@angular-devkit/build-angular     0.900.0-rc.4
@angular-devkit/build-optimizer   0.900.0-rc.4
@angular-devkit/build-webpack     0.900.0-rc.4
@angular-devkit/core              9.0.0-rc.4
@angular-devkit/schematics        9.0.0-rc.4
@angular/http                     7.2.15
@ngtools/webpack                  9.0.0-rc.4
@schematics/angular               9.0.0-rc.4
@schematics/update                0.900.0-rc.4
rxjs                              6.5.3
typescript                        3.6.4
webpack                           4.41.2

</code></pre>

**Anything else relevant?**

This happens for both `ng serve` and `ng serve --prod`

**Comment by JoostK** [comment] 2019-12-03 21:33
Closing as a duplicate of #33111. FYI, this is being addressed.

**Closed by JoostK** 2019-12-03 21:33 UTC
