### ISSUE TITLE
NPM install error. cb() never called

### ISSUE THREAD

**Issue by basters** [angular/angular#8184] opened 2016-04-22 07:25 UTC
Helllo, I have a problem with installation angular2 beta 15

> npm install angular2 -d
> npm info it worked if it ends with ok
> npm info using npm@3.8.7
> npm info using node@v5.9.1
> npm info attempt registry request try #1 at 10:22:16 AM
> npm http request GET https://registry.npmjs.org/angular2
> npm http 304 https://registry.npmjs.org/angular2
> npm ERR! cb() never called!

This problem is only with the beta15, If I try to install previous versions, then all is well

**node version:** v5.9.1
**npm version:**  3.8.7

**Comment by pkozlowski-opensource** [comment] 2016-04-22 07:37
Duplicate of #8053

tl;dr; buggy node version

**Closed by pkozlowski-opensource** 2016-04-22 07:37 UTC
