### ISSUE TITLE
Internal compiler error on style interpolation `style="{{exp}}"` with Ivy

### ISSUE THREAD

**Issue by EmaGht** [angular/angular#33575] opened 2019-11-04 16:56 UTC
# 🐞 bug report

### Affected Package
@angular/compiler

### Is this a regression?
Yes, works without ivy

### Description
Interpolating the style of a component with 

> `style = {{style}}`

Throws error in ivy

## 🔬 Minimal Reproduction
https://github.com/EmaGht/angularStyleInterpolation

instructions in README

## 🌍  Your Environment

**Angular Version:**
9.0.0-rc0

**Anything else relevant?**
Could you also, please, give a couple informations more when something like this happens?

When ivy crashes during template compilation it doesn't give any pointer to which file is actually affected by the error. It took me 5 hours of commenting out components to find this bug. 

Next time this happens, my sanity is on your conscience! 😭

**Comment by IgorMinar** [comment] 2019-11-06 17:02
The culprit in question: https://github.com/EmaGht/angularStyleInterpolation/blob/master/src/app/test-comp/test-comp.component.html

The compiler should definitely give you info about the file location of the error. I'm sorry that you wasted so much time on this. We'll need to investigate.

**Comment by IgorMinar** [comment] 2019-11-06 17:29
```
Angular CLI: 9.0.0-rc.0
Node: 10.13.0
OS: darwin x64
Angular: 9.0.0-rc.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-rc.0
@angular-devkit/build-angular     0.900.0-rc.0
@angular-devkit/build-optimizer   0.900.0-rc.0
@angular-devkit/build-webpack     0.900.0-rc.0
@angular-devkit/core              9.0.0-rc.0
@angular-devkit/schematics        9.0.0-rc.0
@ngtools/webpack                  9.0.0-rc.0
@schematics/angular               9.0.0-rc.0
@schematics/update                0.900.0-rc.0
rxjs                              6.5.3
typescript                        3.6.4
webpack                           4.41.2
```

```
ERROR in Error: Internal Error: Unexpected interpolation
    at error (node_modules/@angular/compiler/bundles/compiler.umd.js:2639:15)
    at _AstToIrVisitor.interpolationFunction (node_modules/@angular/compiler/bundles/compiler.umd.js:17529:179)
    at _AstToIrVisitor.visitInterpolation (node_modules/@angular/compiler/bundles/compiler.umd.js:10199:29)
    at Interpolation.visit (node_modules/@angular/compiler/bundles/compiler.umd.js:6481:28)
    at convertPropertyBinding (node_modules/@angular/compiler/bundles/compiler.umd.js:9975:52)
    at TemplateDefinitionBuilder.convertPropertyBinding (node_modules/@angular/compiler/bundles/compiler.umd.js:17529:44)
    at node_modules/@angular/compiler/bundles/compiler.umd.js:17464:39
    at Object.params (node_modules/@angular/compiler/bundles/compiler.umd.js:15099:41)
    at node_modules/@angular/compiler/bundles/compiler.umd.js:17461:30
    at node_modules/@angular/compiler/bundles/compiler.umd.js:17446:71
    at node_modules/@angular/compiler/bundles/compiler.umd.js:16755:83
    at Array.map (<anonymous>)
    at TemplateDefinitionBuilder.buildTemplateFunction (node_modules/@angular/compiler/bundles/compiler.umd.js:16755:56)
    at Object.compileComponentFromMetadata (node_modules/@angular/compiler/bundles/compiler.umd.js:18364:58)
    at ComponentDecoratorHandler.compile (node_modules/@angular/compiler-cli/src/ngtsc/annotations/src/component.js:509:34)
    at _loop_2 (node_modules/@angular/compiler-cli/src/ngtsc/transform/src/compilation.js:385:53)
```

**Comment by IgorMinar** [comment] 2019-11-06 17:31
marking this as a blocker because it's an internal compiler error affecting a seemingly common use-case.

**Comment by mhevery** [comment] 2019-11-12 19:35
Currently this is not supported because `<div style="{{exp1}}" [style.width]="exp1">` requires that we parse the `exp1` to see if it has `width` so that `exp2` can overwrite it.

Turns out that @matsko had to add parser for other reasons so now we should be able to support it.

**Comment by EmaGht** [comment] 2019-12-12 08:36
Is there a particular reason this has been pushed away from blockers? :worried:

This "seemingly common use-case" is gonna cause me major problems on updating my company's applications and i was eager to try the new version of Angular when it came out :sob::sob:

**Comment by JulienBourgain** [comment] 2020-01-09 13:35
I'm blocked for that too :( when you have 100k line of code, you can't try to find where is the problem without more information :(

**Comment by mhevery** [comment] 2020-01-27 16:45
WIP: https://github.com/angular/angular/pull/34202

**Comment by SkrupSulten** [comment] 2020-02-13 10:39
I get the same error even after removing all style="{{exp}}" and [style.xx]="exp1" tags:

ERROR in Error: Internal Error: Unexpected interpolation
    at error (C:\Users\mbi\source\repos\NemexFrontend\nemex\node_modules\@angular\compiler\bundles\compiler.umd.js:2721:15)
    at _AstToIrVisitor.interpolationFunction (C:\Users\mbi\source\repos\NemexFrontend\nemex\node_modules\@angular\compiler\bundles\compiler.umd.js:17810:179)
    at _AstToIrVisitor.visitInterpolation (C:\Users\mbi\source\repos\NemexFrontend\nemex\node_modules\@angular\compiler\bundles\compiler.umd.js:8498:29)
    at Interpolation.visit (C:\Users\mbi\source\repos\NemexFrontend\nemex\node_modules\@angular\compiler\bundles\compiler.umd.js:7572:28)
    at convertPropertyBinding (C:\Users\mbi\source\repos\NemexFrontend\nemex\node_modules\@angular\compiler\bundles\compiler.umd.js:8274:52)
    at TemplateDefinitionBuilder.convertPropertyBinding (C:\Users\mbi\source\repos\NemexFrontend\nemex\node_modules\@angular\compiler\bundles\compiler.umd.js:17810:44)    at Object.value (C:\Users\mbi\source\repos\NemexFrontend\nemex\node_modules\@angular\compiler\bundles\compiler.umd.js:17699:63)
    at C:\Users\mbi\source\repos\NemexFrontend\nemex\node_modules\@angular\compiler\bundles\compiler.umd.js:17760:42
    at Array.map (<anonymous>)
    at C:\Users\mbi\source\repos\NemexFrontend\nemex\node_modules\@angular\compiler\bundles\compiler.umd.js:17759:38
    at C:\Users\mbi\source\repos\NemexFrontend\nemex\node_modules\@angular\compiler\bundles\compiler.umd.js:17037:83
    at Array.map (<anonymous>)
    at TemplateDefinitionBuilder.buildTemplateFunction (C:\Users\mbi\source\repos\NemexFrontend\nemex\node_modules\@angular\compiler\bundles\compiler.umd.js:17037:56) 
    at C:\Users\mbi\source\repos\NemexFrontend\nemex\node_modules\@angular\compiler\bundles\compiler.umd.js:17579:60
    at C:\Users\mbi\source\repos\NemexFrontend\nemex\node_modules\@angular\compiler\bundles\compiler.umd.js:17013:81
    at Array.forEach (<anonymous>)

**Comment by pkozlowski-opensource** [comment] 2020-02-13 10:54
This is duplicate of #33575 (and we've got a PR that fixes it already)

**Comment by Venipa** [comment] 2020-02-13 13:51
just going along with the errors...
![image](https://user-images.githubusercontent.com/17952364/74441515-40e0cf00-4e70-11ea-8b66-fcb6e4376b06.png)

**Comment by AliYusuf95** [comment] 2020-02-18 14:47
I have the same error, at least the compiler should point to the files that contain errors.

```log
ERROR in Error: Internal Error: Unexpected interpolation
    at error (/../node_modules/@angular/compiler/bundles/compiler.umd.js:2721:15)
    at _AstToIrVisitor.interpolationFunction (/../node_modules/@angular/compiler/bundles/compiler.umd.js:17810:179)
    at _AstToIrVisitor.visitInterpolation (/../node_modules/@angular/compiler/bundles/compiler.umd.js:8498:29)
    at Interpolation.visit (/../node_modules/@angular/compiler/bundles/compiler.umd.js:7572:28)
    at convertPropertyBinding (/../node_modules/@angular/compiler/bundles/compiler.umd.js:8274:52)
    at TemplateDefinitionBuilder.convertPropertyBinding (/../node_modules/@angular/compiler/bundles/compiler.umd.js:17810:44)
    at /../node_modules/@angular/compiler/bundles/compiler.umd.js:17732:39
    at Object.params (/../node_modules/@angular/compiler/bundles/compiler.umd.js:13700:49)
    at Object.value (/../node_modules/@angular/compiler/bundles/compiler.umd.js:17730:34)
    at /../node_modules/@angular/compiler/bundles/compiler.umd.js:17760:42
    at Array.map (<anonymous>)
    at /../node_modules/@angular/compiler/bundles/compiler.umd.js:17759:38
    at /../node_modules/@angular/compiler/bundles/compiler.umd.js:17037:83
    at Array.map (<anonymous>)
    at TemplateDefinitionBuilder.buildTemplateFunction (/../node_modules/@angular/compiler/bundles/compiler.umd.js:17037:56)
    at Object.compileComponentFromMetadata (/../node_modules/@angular/compiler/bundles/compiler.umd.js:18664:58)

```

**Version:**
```

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.0.2
Node: 12.13.1
OS: darwin x64

Angular: 9.0.1
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, platform-server, router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.900.2
@angular-devkit/build-angular      0.900.2
@angular-devkit/build-optimizer    0.900.2
@angular-devkit/core               9.0.2
@angular-devkit/schematics         9.0.2
@angular/cdk                       9.0.0
@angular/cli                       9.0.2
@angular/material                  9.0.0
@angular/material-moment-adapter   9.0.0
@schematics/angular                9.0.2
@schematics/update                 0.900.2
rxjs                               6.5.4
typescript                         3.7.5
webpack                            4.41.6
```

**Comment by Venipa** [comment] 2020-02-18 15:22
I could resolve the files by logging the file paths which were included throw, took a hour tho

**Closed** 2020-02-20 23:13 UTC
Labels: comp: compiler, comp: ivy, severity5: regression, type: bug/fix

**Comment by RickStrahl** [comment] 2020-02-24 01:03
Just as an aside a big problem with this particular bug is that it isn't reporting the source.  Fixing the `style` issue is great, but the underlying problem of some sort of compilation error in a template not pointing back to the template is really the bigger problem here I think.

**Comment by SkrupSulten** [comment] 2020-02-28 10:37
I'm still getting the same error with Angular 9.0.4 :(

```
ERROR in Error: Internal Error: Unexpected interpolation
    at error (C:\Users\mbi\source\repos\NemexFrontend\Nemex\node_modules\@angular\compiler\bundles\compiler.umd.js:2721:15)
    at _AstToIrVisitor.interpolationFunction (C:\Users\mbi\source\repos\NemexFrontend\Nemex\node_modules\@angular\compiler\bundles\compiler.umd.js:17867:179)
    at _AstToIrVisitor.visitInterpolation (C:\Users\mbi\source\repos\NemexFrontend\Nemex\node_modules\@angular\compiler\bundles\compiler.umd.js:8517:29)
    at Interpolation.visit (C:\Users\mbi\source\repos\NemexFrontend\Nemex\node_modules\@angular\compiler\bundles\compiler.umd.js:7590:28)
    at convertPropertyBinding (C:\Users\mbi\source\repos\NemexFrontend\Nemex\node_modules\@angular\compiler\bundles\compiler.umd.js:8292:52)
    at TemplateDefinitionBuilder.convertPropertyBinding (C:\Users\mbi\source\repos\NemexFrontend\Nemex\node_modules\@angular\compiler\bundles\compiler.umd.js:17867:44)
    at Object.value (C:\Users\mbi\source\repos\NemexFrontend\Nemex\node_modules\@angular\compiler\bundles\compiler.umd.js:17756:63)
    at C:\Users\mbi\source\repos\NemexFrontend\Nemex\node_modules\@angular\compiler\bundles\compiler.umd.js:17817:42
    at Array.map (<anonymous>)
    at C:\Users\mbi\source\repos\NemexFrontend\Nemex\node_modules\@angular\compiler\bundles\compiler.umd.js:17816:38
    at C:\Users\mbi\source\repos\NemexFrontend\Nemex\node_modules\@angular\compiler\bundles\compiler.umd.js:17094:83
    at Array.map (<anonymous>)
    at TemplateDefinitionBuilder.buildTemplateFunction (C:\Users\mbi\source\repos\NemexFrontend\Nemex\node_modules\@angular\compiler\bundles\compiler.umd.js:17094:56)
    at C:\Users\mbi\source\repos\NemexFrontend\Nemex\node_modules\@angular\compiler\bundles\compiler.umd.js:17636:60
    at C:\Users\mbi\source\repos\NemexFrontend\Nemex\node_modules\@angular\compiler\bundles\compiler.umd.js:17070:81
    at Array.forEach (<anonymous>)
```

**Comment by kloose** [comment] 2020-03-01 03:28
Having the same issue, im posting here the easiest way I found to debug it

disable ivy in tsconfig.json

you'll at least then get a sensible error message for tracking down the culprit, solve the issue, then re-enable, hopefully in a near-future release IVY will be able to produce more helpful error messages during template compilation

**Comment by EmaGht** [comment] 2020-03-02 08:41
> 
> 
> Having the same issue, im posting here the easiest way I found to debug it
> 
> disable ivy in tsconfig.json
> 
> you'll at least then get a sensible error message for tracking down the culprit, solve the issue, then re-enable, hopefully in a near-future release IVY will be able to produce more helpful error messages during template compilation

This is an Ivy-specific error tho. If you disable it, compilation will work.

For other kind of errors your suggestion may work

**Comment by rkkp1023** [comment] 2020-03-02 10:55
Having the same issue, @EmaGht 
Any one knows how to debug this error !

**Comment by petebacondarwin** [comment] 2020-03-02 11:03
We should definitely provide a more informative error message here. Although, it is concerning that it suggests that it is an "Internal error" which implies that there is something wrong with the compiler and not the template.

One approach to debug this is to put a break point on the place where there error is thrown and the look up the call stack. The first function of interest looks like `convertPropertBinding()` has a `value: AST` parameter. This should give you some information about what part of the template is triggering the problem.

**Comment by pkozlowski-opensource** [comment] 2020-03-02 11:05
We are tracking this error in #35752 - if anyone has an additional use-case please add it to #35752
