### ISSUE TITLE
Angular SSR build for production is stuck at building forever

### ISSUE THREAD

**Issue by OmarMohamed256** [angular/angular#57721] opened 2024-09-08 11:04 UTC
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

When creating a new fresh angular SSR project then trying to build it in production mode it takes forever
steps to replicate:
1- ng new --ssr
2- ng build --configuration production --verbose

### Please provide a link to a minimal reproduction of the bug

https://github.com/OmarMohamed256/test

### Please provide the exception or error you saw

```true
ng build --configuration production --verbose
/ Building...

  polyfills-SCHOHYNV.js  33.7kb

Done in 605ms

  polyfills.server.mjs  262.3kb

/ Building...
● [DEBUG] Lookbehind assertions in regular expressions are not available in the configured target environment ("chrome127.0", "edge127.0", "firefox115.0", "ios16.0", "node22.0.0", "safari16.0" + 5 overrides) [unsupported-regexp]

    node_modules/critters/dist/critters.mjs:1343:51:
      1343 │         const crittersComment = rule.text.match(/^(?<!\! )critters:(.*)/);
           ╵                                                    ~~~

  This regular expression literal has been converted to a "new RegExp()" constructor to avoid
  generating code with a syntax error. However, you will need to include a polyfill for "RegExp" for
  your code to have the correct behavior at run-time.

● [DEBUG] Lookbehind assertions in regular expressions are not available in the configured target environment ("chrome127.0", "edge127.0", "firefox115.0", "ios16.0", "node22.0.0", "safari16.0" + 5 overrides) [unsupported-regexp]

    node_modules/critters/dist/critters.mjs:1401:30:
      1401 │           sel = sel.replace(/(?<!\\)::?[a-z-]+(?![a-z-(])/gi, '').replace(/::?not\(\s*\)/g, '')
           ╵                               ~~~

  This regular expression literal has been converted to a "new RegExp()" constructor to avoid
  generating code with a syntax error. However, you will need to include a polyfill for "RegExp" for
  your code to have the correct behavior at run-time.
- Building...
● [DEBUG] This call to "require" will not be bundled because the argument is not a string literal [unsupported-require-call]

    node_modules/express/lib/view.js:72:13:
      72 │     var fn = require(mod).__express;
         ╵              ~~~~~~~
| Building...
● [DEBUG] Indirect calls to "require" will not be bundled [indirect-require]

    node_modules/picocolors/picocolors.js:3:163:
      3 │ ...s("--color") || process.platform === "win32" || require != null && require("tty").isatty(1) && env.TERM...
        ╵                                                    ~~~~~~~
\ Building...

  main-MR5DYDKN.js  214.8kb

| Building...

  server.mjs                 1.1mb
  chunk-VGICRMYO.mjs       516.4kb
  chunk-RWMY522A.mjs        18.7kb
  chunk-7YC4RJ5P.mjs        11.8kb
  chunk-5XUXGTUW.mjs         2.5kb
  render-utils.server.mjs    1.4kb
  main.server.mjs            149b

\ Building...
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 18.2.3
Node: 22.2.0
Package Manager: npm 10.8.3
OS: win32 x64

Angular: 18.2.3
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router, ssr

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1802.3
@angular-devkit/build-angular   18.2.3
@angular-devkit/core            18.2.3
@angular-devkit/schematics      18.2.3
@schematics/angular             18.2.3
rxjs                            7.8.1
typescript                      5.5.4
zone.js                         0.14.10
```

**Comment by jnizet** [comment] 2024-09-08 12:01
I can reproduce this on macOS, with Node 22.2.0. It builds fine with Node 20.12.2 though.

**Comment by JeanMeche** [comment] 2024-09-08 16:16
This is a duplicate of angular/angular-cli/issues/27674

**Closed by JeanMeche** 2024-09-08 16:16 UTC
