### ISSUE TITLE
Max DateTime UTC (9999-12-31T23:59:59Z) in date pipe broken on IE11 and Edge

### ISSUE THREAD

**Issue by tariknz** [angular/angular#13291] opened 2016-12-07 22:28 UTC
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
{{ '9999-12-31T23:59:59Z' : date:'short'}} => page errors out without an error in the console
{{ '9998-12-31T23:59:59Z' : date:'short'}} => formats to 1/1/9999 12:59 PM 

**Expected behavior**
{{ '9999-12-31T23:59:59Z' : date:'short'}} => 1/1/9999, 12:59 PM
{{ '9998-12-31T23:59:59Z' : date:'short'}} => 1/1/10000, 12:59 PM

(current behaviour in Chrome)

**Minimal reproduction of the problem with instructions**
Plunkr to replicate it: https://plnkr.co/edit/xTi4YetvG8ASlS7vPdg3?p=preview

**What is the motivation / use case for changing the behavior?**
Browser consistency 

**Please tell us about your environment:**
Windows 10

* **Angular version:** 2.2.4

* **Browser:** [IE11 | Edge ]

 
* **Language:** [TypeScript 2.0.3]

**Comment by tariknz** [comment] 2016-12-07 23:05
Might be good to add that I am in NZDT (+13) – New Zealand Daylight Time (Daylight Saving Time) so its likely overflowing. Momentjs seems to handle it fine.

**Comment by vicb** [comment] 2016-12-08 21:49
Duplicate of https://github.com/angular/angular/issues/8319

**Closed by vicb** 2016-12-08 21:49 UTC
Labels: comp: common, type: bug

**Comment by tariknz** [comment] 2016-12-08 21:56
@vicb How is that the same?
