### ISSUE TITLE
fix(service-worker): handle eagerly-cached assets unexpectedly missing from the cache

### ISSUE THREAD

**Issue by gkalpak** [angular/angular#36539] opened 2020-04-09 10:51 UTC
## Context

It has been observed that occasionally angular.io loads an `index.html` file that contains (transitive) references to some JS chunks (e.g. lazy-loaded custom elements, such as the ToC module/component) which no longer exist neither on the server nor on the SW cache. When this happens, the page cannot be loaded and user sees the app-shell with a blank content area.

The frequency of these issues (which have been reported for other apps using `@angular/service-worker`) seem to be declining recently (see https://github.com/angular/angular/issues/28114#issuecomment-581989614), possibly due to fixes such as #32525. They still happen, though.

This is puzzling because these missing chunks are part of the same asset cache group (`app-shell`) and should be cached together with the `index.html` and `main.js`/`runtime.js` bundles that reference them. #28114 has much more info and in-depth discussions.

## A Theory

While we haven't found the root cause of this, here is a theory:

The browser deletes some entries from the `app-shell` cache. E.g. it removes the ToC module/component chunk but retains the `index.html` and `main.js`/`runtime.js` that reference it.

Browsers are free to decide when/what to evict from the cache, so different browsers can have different behavior.

## Possible Solution

One possible solution is be to:
1. Detect this situation in the SW (i.e. when a hashed, eagerly cached asset cannot be found in the cache and also does not exist on the server).
2. Purge the corresponding cache.
3. Communicate from the SW to the page that the SW and the app are in an unrecoverable state and the page needs to be reloaded.
4. Have the page listen for the message and handle it accordingly. For example it could show a notification to the user prompting them to reload) or automatically reload the page. (For angular.io, the latter would make more sense, since there is basically no app state to be lost.)

**Comment by sonukapoor** [comment] 2020-04-09 16:16
@gkalpak I will try to take a look at this.

**Comment by IgorMinar** [comment] 2020-04-09 20:28
I'm marking this as freq:low (it does not happen very often) + severity: regression (when it does however happen, it really sucks because an app that worked no longer works).

**Comment by IgorMinar** [comment] 2020-04-09 20:28
thanks @sonukapoor for taking this on!

**Comment by sonukapoor** [comment] 2020-04-26 20:51
@gkalpak please see the below inline questions:

> One possible solution is be to:
> 
> 1. Detect this situation in the SW (i.e. when a hashed, eagerly cached asset cannot be found in the cache and also does not exist on the server).
> 2. Purge the corresponding cache.

If the asset doesn't exist in the cache anymore, then nothing needs to be purged. Is that my correct understanding?

> 3. Communicate from the SW to the page that the SW and the app are in an unrecoverable state and the page needs to be reloaded.

Would you recommend to use an `Observable` so that the page can be notified of this state?

> 4. Have the page listen for the message and handle it accordingly. For example it could show a notification to the user prompting them to reload) or automatically reload the page. (For angular.io, the latter would make more sense, since there is basically no app state to be lost.)

Again, would an `Observable` here be sufficient?

**Comment by gkalpak** [comment] 2020-04-27 14:52
> If the asset doesn't exist in the cache anymore, then nothing needs to be purged. Is that my correct understanding?

We need to clear the whole cache. See https://github.com/angular/angular/issues/36539#issue-597196606 for more details.

##
> Would you recommend to use an `Observable` so that the page can be notified of this state?

Sounds reasonable. (I would be open to suggestions, though.)

##
> Again, would an `Observable` here be sufficient?

Ehm...this is the same observable we are talking about in the previous point.
Basically, the SW will communicate to the pages via `postMessage()`. On the page side, an Angular service (possibly `SwUpdate` or a similar one) will expose an observable that will get a new emission each time such a message is received from the SW.

**Comment by sonukapoor** [comment] 2020-04-27 16:30
@gkalpak Makes sense. 👍

**Comment by expcapitaldev** [comment] 2020-06-15 06:32
any updates ? it is real problem

**Comment by gkalpak** [comment] 2020-06-15 14:21
@expcapitaldev, this is being worked on in #36847. Please follow #36847 for updates.

**Closed** 2020-08-31 18:41 UTC
Labels: comp: docs-infra, comp: service-worker, freq1: low, severity5: regression, state: confirmed, triage #1, type: bug/fix

**Comment by expcapitaldev** [comment] 2020-09-01 17:31
any updates ? it is real problem

**Comment by gkalpak** [comment] 2020-09-02 09:54
@expcapitaldev, see https://github.com/angular/angular/issues/36539#issuecomment-644165407.
