### ISSUE TITLE
Can't bind input when using abstract classes (2+ level of hierarchy)

### ISSUE THREAD

**Issue by FrancescoBorzi** [angular/angular#35295] opened 2020-02-10 11:54 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Most likely yes

### Description

- When a Component uses an Input that is defined in its direct parent (abstract) class, everything works fine.

- When a Component uses an Input that is defined in a 2-levels up parent (abstract) class, the `ng build` or `ng serve` give an error.

## 🔬 Minimal Reproduction

A minimal reproduction repo is available here: https://github.com/FrancescoBorzi/angular-9-issue-reproduction

I have 4 classes:

```
export abstract class AbstractAComponent {
  @Input() myInput: string;
}
```
```
export abstract class AbstractBComponent extends AbstractAComponent {}
```

```
@Component({
  selector: 'app-one',
  templateUrl: './one.component.html',
  styleUrls: ['./one.component.scss']
})
export class OneComponent extends AbstractAComponent {}
```

```
@Component({
  selector: 'app-two',
  templateUrl: './two.component.html',
  styleUrls: ['./two.component.scss']
})
export class TwoComponent extends AbstractBComponent {}
```

This is how I use them:

```
<app-one [myInput]="'value 1'"></app-one>
<app-two [myInput]="'value 2'"></app-two>
```

In a nutshell:
- `@Input() myInput` is defined in `AbstractAComponent`
- `OneComponent` directly extends `AbstractAComponent`
- `TwoComponent` extends `AbstractBComponent` which extends  `AbstractAComponent`

Expected behaviour:
- both `OneComponent` and `TwoComponent` should have `@Input() myInput`

Current behaviour:
- looks like `TwoComponent` doesn't correctly inherit  `@Input() myInput`

## 🔥 Exception or Error
<pre><code>

ERROR in src/app/app.component.html:2:10 - error NG8002: Can't bind to 'myInput' since it isn't a known property of 'app-two'.
1. If 'app-two' is an Angular component and it has 'myInput' input, then verify that it is part of this module.
2. If 'app-two' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.

</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 9.0.1
Node: 12.14.0
OS: linux x64

Angular: 9.0.0
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.1
@angular-devkit/build-angular     0.900.1
@angular-devkit/build-optimizer   0.900.1
@angular-devkit/build-webpack     0.900.1
@angular-devkit/core              9.0.1
@angular-devkit/schematics        9.0.1
@angular/cli                      9.0.1
@ngtools/webpack                  9.0.1
@schematics/angular               9.0.1
@schematics/update                0.900.1
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2

</code></pre>

**Anything else relevant?**

N/A

**Comment by elvisbegovic** [comment] 2020-02-10 13:22
Hi, hmm ...
Thank you for your repro 👍 I cloned your project and reproduce the bug ...

I think, there are two answers here:

1. The way you writing Angular code (when make use of typescript's abstract power) was "working" in Angular < v9.0.0 even if it should NOT.
From >= v9.0.0 (your version) all abstract classes (as long you use Angular things like `DI` or any annotation like here `@Input()` ) should have class level annotation `@Directive()`; like that Angular can know there are Angular things inside your abstract classes and correctly inherit.
So if you annotate your both classes 
``` 
//in file abstract-a.component.ts
@Directive()
export abstract class AbstractAComponent {
  @Input() myInput: string;
}
```
And 
``` 
//in file abstract-b.component.ts
@Directive()
export abstract class AbstractBComponent extends AbstractAComponent {}
```
Your code should works as expected.


2. In v9-migration there is a schematic called [migration-v9-undecorated-classes-with-decorated-fields](https://github.com/angular/angular/blob/5a7f33496b91145b6ba5a407ba616485f39a42d9/packages/core/schematics/migrations.json#L33-L36) which is supposed migrate your project from theses cases (missing decoration). 

But I realize there is problem, because is if you run automatic update `ng update --migrate-only --from=8 --to=9` the result will be:
![image](https://user-images.githubusercontent.com/2789203/74152687-20fea080-4c0f-11ea-9980-25b7ed78e49c.png)

The schematic will update `AbstractAComponent` but it doesn't update `AbstractBComponent` because this abstract class doesn't contain and Angular stuff just `extends AbstractAComponent` : 
`export abstract class AbstractBComponent extends AbstractAComponent {}` 

To resume, if you write valid Angular code it will works, but unintentionally I think your issue led to the discovery of another bug on this schematic. 
Maybe this is by design, @devversion @alan-agius4  can you please give some inputs here.

If it is schematic bug then issue should be on angular/angular

**Comment by devversion** [comment] 2020-02-10 14:06
I can confirm that this is a bug in a migration. Not a bug in the `undecorated-classes-with-di` migration which adds the decorator to intermediary classes, but in the `undecorated-classes-with-fields` migration.

We have an issue for this in #34376. I think we can close this issue since the actual fix is to add `@Directive` to the `BComponent`, and the other schematic issue is already tracked, right?

**Closed by devversion** 2020-02-10 14:06 UTC
