### ISSUE TITLE
OnPush change detection fails to trigger from event listeners via Intersection Observer

### ISSUE THREAD

**Issue by psybuzz** [angular/angular#41771] opened 2021-04-22 22:00 UTC
# 🐞 bug report

### Affected Package
@angular/angular

### Is this a regression?
Unknown, probably not.

### Description
Articles online indicate that components using OnPush change detection will trigger change detection if it handles an event from a child component that emits using @Output.

While often the case, this does not work when the creation of the child event is done in the same task(?) as the handler of an IntersectionObserver.  In a particularly large webapp, this can be very frustrating, as knowing whether a component will be created via some IntersectionObserver callback further up the stack is non-trivial.

## 🔬 Minimal Reproduction
Repro:
- See https://stackblitz.com/edit/change-detection-strategy-onpush-5c8mvr?file=src/app/example.component.ts
- Click the "Show" button

Actual: the "i should be disabled" button is enabled
Expected: the "i should be disabled" button is disabled

**Comment by lukasmatta** [comment] 2021-04-23 12:44
Maybe I'm missing something but shouldn't you let the change detector know that `shouldShowAppMultiple` attribute has changed? Like I do in https://stackblitz.com/edit/change-detection-strategy-onpush-wu8ok1?file=src/app/example.component.ts

**Comment by AleksanderBodurri** [comment] 2021-04-23 17:17
Your minimal reproduction app is running Angular v6. See https://angular.io/guide/releases#support-policy-and-schedule.

Could you upgrade to a supported version to see if the issue still persists?

**Comment by gkalpak** [comment] 2021-04-23 18:54
The problem in your example, @psybuzz, (once dependencies are updated to latest versions :grin:) is that `ExampleComponent` is `OnPush`, which means that there will be no change detection once the `IntersectionObserver`'s callback is triggered (since no inputs have changed). So, while `shouldShowAppMultiple` will be true, nothing will trigger change detection and thus `MultipleComponent` will not be instantiated (and thus not trigger an event).

One way to solve this is to explicitly call [ChangeDetectorRef#markForCheck()][1] in the `IntersectionObserver` callback. See this [updated StackBlitz][2].

##
Closing the issue, since everything seems to work as expected, but feel free to continue the discussion below.

[1]: https://angular.io/api/core/ChangeDetectorRef#markForCheck
[2]: https://stackblitz.com/edit/ngissue-41771?file=src/app/example.component.ts

**Closed by gkalpak** 2021-04-23 18:54 UTC
Labels: comp: core, core: change detection
