### ISSUE TITLE
Universal: status and 2.4 release

### ISSUE THREAD

**Issue by DavidRouyer** [angular/angular#13585] opened 2016-12-20 12:07 UTC
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```
Can you give us insights on Angular Universal (is it merged yet?), will it be updated and part of the 2.4 release?

**Comment by DzmitryShylovich** [comment] 2016-12-20 12:08
Duplicate of https://github.com/angular/angular/issues/12495

Pls subscribe to updates.

**Closed** 2016-12-20 17:59 UTC
