### ISSUE TITLE
Validator binding does not work in RC6

### ISSUE THREAD

**Issue by rolandoldengarm** [angular/angular#11434] opened 2016-09-08 09:21 UTC
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Describe how the bug manifests. 
Setting a pattern for validation, bound to variable, does not work. When set directly in HTML, it works.

**Expected behavior**

According to this pull request it should work:
https://github.com/angular/angular/pull/11116

**Reproduction of the problem**
````
HTML:
<input class="input-sm" type="text" [pattern]="pattern" [(ngModel)]="number" required  name="number" #number="ngModel"/>
<div [hidden]="number.valid || number.pristine" class="alert alert-danger">
Invalid number (not 111)</div>

TS:
pattern: string = "111";
number: string = "";
````
When typing in 111, the error message does not disappear.
When setting pattern to 111 straight in the HTML, it works.

**What is the motivation / use case for changing the behavior?**
According to the pull request, this should be implemented in RC6. We need this to validate a credit card number based on the type selected, as the regex will change then.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.6
 
* **Browser:** [all ] 
 
* **Language:** [ TypeScript 2.0]

**Comment by pkozlowski-opensource** [comment] 2016-09-08 12:52
What is the `pattern` variable in your case. Could you please put together a minimal plunker?

**Comment by pkozlowski-opensource** [comment] 2016-09-08 13:00
Can't reproduce here: https://plnkr.co/edit/fziiNIYzBxMMpiN3qvzv?p=preview

Please note that there are few fishy things going on in your code snippet:
* you are binding to the `number` member (`[(ngModel)]="number"`) but in a plunk TS complains about it being an invalid member name
* you are assigning instance of the `NgModel` directive to the `number` variable which seems to be the same as the (invalid) model name

I can't see any issue here so I'm going to close this one for now. Happy to re-open if you can provide a plunker exposing the issue.

**Closed by pkozlowski-opensource** 2016-09-08 13:00 UTC

**Comment by rolandoldengarm** [comment] 2016-09-09 00:49
@pkozlowski-opensource I'm so sorry, my mistake. I had upgraded all packages, except... angular/forms... So that's why it obviously did not work.
All good now!
