### ISSUE TITLE
Preloading modules are freezing the UI

### ISSUE THREAD

**Issue by bhaskerchari** [angular/angular#28270] opened 2019-01-21 08:53 UTC
We are preloading "lazy-loaded modules" to reduce initial payload and improve the app startup time. So that, we have decided to use "PreloadAllModules Strategy".

But the problem is when we try to preload the modules it loads them in the background asynchronously which is good but then the UI looks frozen while the loaded scripts are getting executed and the current user interaction is not smooth until the preloaded lazy modules execution is complete.

It looks like since the javascript is single threaded it is halting the current execution of whatever user is interacting with and trying to load and execute the asynchronously loaded modules which is what causing freeing of UI.

Are there any alternatives to this problem or any work around to this problem while we still take advantage of preloading without freezing the UI.

My current scenario is something like below:

1) First the login page is loaded and then after successful login redirected to home page and the user tries to interact with the application.
2) I am trying to preload the lazy loaded after 5 seconds delay after my app is loaded so that the user is able to interact with the login page withot delay.
3) When user is trying to interact with the home page after the lazy loaded scripts are loaded it immediately trying to execute the loaded scripts and delaying the current interaction of the user which makes it less responsive or interactive which is not desirable.

Here is the Custom Preloading strategy I am using to delay the loading of Prealoading Modules.

import * as _ from 'lodash';
import { AppService } from '../../app.service';
import { Injectable } from '@angular/core';
import { Observable, of, timer } from 'rxjs';
import { PreloadingStrategy, Route } from '@angular/router';
import { tap } from 'rxjs/operators';

@Injectable({
    providedIn: 'root'
})

export class CustomPreloadingStrategy implements PreloadingStrategy {

    constructor(private appService: AppService) { }

    preload(route: Route, load: () => Observable<any>): Observable<any> {
        return timer(5000).pipe(
            tap(() => {
                    return _.flatMap.call(load(), () => of(null));
            })
        );
    }
}

Now the problem is after the login is screen is loaded 

# 🐞 bug report

### Is this a regression?

 NO

### Description

 A clear and concise description of the problem...

## 🌍  Your Environment

**6.0.5**
<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by dawidgarus** [comment] 2019-01-21 16:07
It's not the execution of script that causes the halt, but the compilation of angular module. It would be great if JIT compiler could work as a web worker.

**Comment by bhaskerchari** [comment] 2019-01-21 18:03
@dawidgarus ,

Yes you are right I meant the same execution of script means executing the angular module code which is actually compilation of angular modules.

It would really be great if angular could work it out to execute using a web worker to really make things responsive and performant at the same time.

But i am wondering no where this concern has been mentioned in angular docs nor raised as an issue anywhere so thinking how others are handling this issue?

**Comment by spock123** [comment] 2019-01-21 19:03
Webworkers are a completely different beast, and there are many issues with using them for compilation. For one, the communication channels between main thread and workers are extremely limited and I don't think it would help, but rather further complexify stuff.

**Comment by dawidgarus** [comment] 2019-01-21 22:31
@spock123 Parsing templates into AST or some other intermediate form should be relatively easy to do in worker. Rest (matching selectors with components, dependencies etc) could be done in requestIdleCallback (if available) to make it more responsive.

**Comment by spock123** [comment] 2019-01-22 07:58
@dawidgarus yeah you're right. I just remember that the Angular team did experiment with putting logic into Workers but I think they abandoned it because it didn't prove to be a significant advantage. I might be wrong though.

**Comment by dawidgarus** [comment] 2019-01-22 09:14
@spock123 I can see why if you move bootstrap to worker it might not be a difference. You have to wait for whole app to compile and whether it's done in main thread or one worker thread is not much of a difference I suppose. I wonder if it does improve performance for preloaded modules though. Also, it might not be significant advantage for simple app, but my complex app take over a minute to bootstrap in not high-end mobile device in development mode. Hopefully Ivy will make things faster.

**Comment by EmaGht** [comment] 2019-01-23 15:18
Had the same problem in my modest 20ish modules application.
Setting preloadingStrategy to "NoPreloading" nullifies startup freezes (you still have a tiny freeze everytime you load a new module), but using AOT compilation with it really speed things up seemingly removing all the freezes.

I also don't think a "PreloadAllModules" strategy (or anything similar) is usually a good idea; why would you preload modules that your user might not call while browsing your application? Sounds like a waste of bandwidth to me

**Comment by jscti** [comment] 2019-01-23 15:41
For what it worth, I had the same problem :
- I want to have a first startup as quick as possible
- I don't want to freeze my UI (startup animation) while lazy modules are loaded
- I don't want my customer to wait for loading when clicking on a lazy loaded module link

So I made a quick & dirty custom loader that preloads lazy modules with a delay ... :

```
export class PreloadAllModulesWithDelay implements PreloadingStrategy {
    preload(route: Route, fn: () => Observable<any>): Observable<any> {
        return timer(1500).pipe(
            first(),
            switchMap(() => fn().pipe(catchError(() => of(null))))
        );
    }
}
```
And an event "all modules have been loaded" is also really missing

**Comment by pkozlowski-opensource** [comment] 2019-01-29 19:58
I'm confused why we are talking about JIT here - compilation of Angular templates _is_ expensive so I wouldn't be surprised in a browser is busy during this time. But in the prod mode all modules should be loaded asynchronously and be already AOT-compiled. Doing any perf measurements in the JIT mode is just missing the point - it is the dev mode facility only. 

I'm going to close this one as I don't think there is anything actionable here - unless someone can provide a minimal reproduce scenario illustrating significant perf degradation with  lazy-loaded modules in the AOT/ prod mode.

**Closed by pkozlowski-opensource** 2019-01-29 19:58 UTC
Labels: comp: core & compiler

**Comment by dawidgarus** [comment] 2019-01-30 14:08
@pkozlowski-opensource It matters for development. If app bootstrap takes 1 minute (every time you refresh) in not high end mobile device you want to take advantage of lazy loading for faster development. PreloadAllModules makes it useless.

**Comment by jscti** [comment] 2019-01-30 14:20
For my case, I wasn't talking about JIT, my app is fully aot-compiled & deployed.
I don't have a repro case but basically :
- main module load & run
- displaying of a smooth SVG animation that take several seconds
- during that time, angular try loading lazy modules (PreloadAllModules)
- animation gets noticeable freezes

For this reason I had to use a custom preloader (wainting x seconds, or waiting for an observable).

I don't know if angular could load thoses modules without impacting the UI .. or choose the right moment to do it (when app idle) ... but the problem exists.

**Comment by devel112** [comment] 2019-05-30 13:51
The preload function should take boolean or something to tell it only to download and not execute the module, and only execute the module when needed

**Comment by poddarkhushbu07** [comment] 2019-06-07 10:11
> I'm confused why we are talking about JIT here - compilation of Angular templates _is_ expensive so I wouldn't be surprised in a browser is busy during this time. But in the prod mode all modules should be loaded asynchronously and be already AOT-compiled. Doing any perf measurements in the JIT mode is just missing the point - it is the dev mode facility only.
> 
> I'm going to close this one as I don't think there is anything actionable here - unless someone can provide a minimal reproduce scenario illustrating significant perf degradation with lazy-loaded modules in the AOT/ prod mode.

In dev mode, if too much time is taken to pre-load the lazily loaded modules then it will hinder the speed  of developers and testers .

**Comment by alokshakya** [comment] 2019-08-15 10:34
I also had the same issue in one of my application, when I run application using ```ng serve``` it freezes UI but when I used ```ng serve --aot``` it doesn't freeze UI in development. For production you should use command ```ng build --prod --aot```  then it would not freeze UI. This way your eagerly loaded components loaded first and will be rendered for user to have interaction at the same time ```preloaded``` modules will be loaded in background so that user will feel smooth running of application.
