### ISSUE TITLE
RFC: `as local-val` syntax proposal

### ISSUE THREAD

**Issue by mhevery** [angular/angular#15020] opened 2017-03-09 00:25 UTC
At times it is useful to be able to get a hold of the result of a binding.

```
<div *ngIf="userStream|async">...</div>
```

In the above example getting hold `userStream|async` is useful so that developer can bind to the value.  (see #13061) The current syntax to do that is:

```
<div *ngIf="userStream|async; let user">...</div>
```

The above syntax is awkward because it places the `let user` on the right hand side. It is also un-natural to use `let` in `if` since there is no equivalent in JavaScript. The proposed syntax is:

```
<div *ngIf="expression as varName">...</div>
<div *ngIf="userStream|async as user">...</div>
```
The above would desugar to:
```
<template [ngIf]="expression" let-user="ngIf">
```

- `as varName` becomes `let-varName="bindingName"` where `bindingName` is `ngIf` because the `expression` is bound to `ngIf`

This could also be used with `ngFor` as:
```
<div *ngFor="let user of userStream|async as users; let i=index">
  {{user}} {{i}} of {{users.length}}
</div>
```

We could also add `,` for let so that it can become:
```
<div *ngFor="let i = index, user of userStream|async as users">
  {{user}} {{i}} of {{users.length}}
</div>
```

Alternatively it could be expressed as:
```
<div *ngFor="let user of userStream|async as users; index as i">
  {{user}} {{i}} of {{users.length}}
</div>
```

## Summary

- add `key exp as local` syntax which is equivalent to `[key]="exp" var-local="key"`
  - ensure that `as` syntax can be used even if there is no expression as in `index as i`
- add `,` to `let` so that we can do: `let localA=exportA, localB=exportB`

## Breaking Change

The consequence of this change is that we are grabbing `as` as a keyword, which means that it can no longer be used for binding. In an unlikely event that someone has created a structural directive which has an `as` binding that user would be broken. Example
```
<div *custom="expr as expr">
```
would now have different meaning. The fix would be to add `;` like so:
```
<div *custom="expr; as expr">
```

## Clarification

These are equivalent
- `*ngIf="exp as var1"` => `*ngIf="exp; let var1 = ngIf"`
- `*ngFor="var item of itemsStream |async as items"` => `*ngFor="var item of itemsStream |async; let items = ngForOf"`

**Comment by alxhub** [comment] 2017-03-09 00:59
Does
    <div *ngFor="let user of userStream|async as users; let i=index">
desugar to
    <ng-template ngFor [ngForOf]="userStream|async" let-user="$implicit" let-users="ngForOf" let-i="index">
?

In other words, does the fact that `as` occurs in the `of` keyed binding result in the variable assigned the value of the `ngForOf` export, not `ngFor`? Can I therefore do
    <div *custom="a as b of c as d">
?

**Comment by alxhub** [comment] 2017-03-09 01:03
I think one problem is that this won't work unless the directive supports it. If my directive does not instantiate its template with `custom` in the context, then:
```html
<div *custom="expr as value">
```
does not do what I would expect as a developer, since the desugared `let-value="custom"` refers to a context property which doesn't exist.

**Comment by wardbell** [comment] 2017-03-09 01:23
I'm confused.  When I looked at the code, the reason that the following works today
```
<div *ngIf="userStream|async; let user">...</div>
```
is that
* the `NgIf` directive assigns the condition to the `$implicit` property
* the microsyntax interprets a `let x` with no assignment as the equivalent of `let-x=$implicit`.

It follows that your proposed `as user` is another way of saying `let-user=$implicit`.

That interpretation falls apart when we look at
```
<div *ngFor="let user of userStream|async as users; index as i">
```
because there are now TWO rivals for the `$implict` value:  `let-user` and `let-users`.

THEREFORE, I take it that you are adding a new `as` option to the microsyntax in which `as x` means "assign the value of the *-property to `let-x`"

The `$implicit` plays no role in this.  It follows that the (legal) expression
```
<div *ngIf="userStream|async as user; let user">...</div>
```
Would assign `let-user` TWICE
1. via `$implicit` ... an artifact of the way `NgIf` is written
1. via "as", which assigns the result of the `[ngIf]` expression to `let-user`.

***Have I got this right so far?***

If so, then the answer to @alxhub's challenges are as follows:

1. The *ngFor does NOT de-sugar to `let-users="ngForOf"` but rather to `let-users="ngFor"` 

1. Directives don't have to do _anything_ to support the proposed syntax. Taking his example
```
<div *custom="expr as value">
```
the microsyntax ensures that `let-value` is the value of `expr`

### Is "as" a good name?

I was taken aback at first because `as` is how we cast in TypeScript. But I can't think of anything better.

**Comment by laco0416** [comment] 2017-03-09 01:29
I'm confused a little, too. I think this proposal should be separated two. Support for `,` syntax for multiple `let` assignments is easy to understand because it's compatible with JavaScript. 
I agree on that casually. It's very good change.

But `as` syntax is completely new DSL and incompatible with JavaScript. It's not well-known syntax. 
And as @wardbell says, `as` is used in `TypeScript`.

Is this proposal for 5.0?

**Comment by wardbell** [comment] 2017-03-09 01:36
I agree with @laco0416 that the syntax for `,` is tangential to this proposal and probably should be in a different RFC.  I'm not convinced that it solves a problem that is serious enough to justify the additional overhead.

**Comment by alxhub** [comment] 2017-03-09 01:39
@wardbell, @mhevery says
> `as varName` becomes `let-varName="bindingName"` where `bindingName` is `ngIf` because the expression is bound to `ngIf`

So I don't think this competes for `$implicit` as `varName` is set to `ngIf`, not `$implicit`.

I also don't think @mhevery meant that `ngIf` refers to the value of the binding to the `ngIf` input, but some clarification is needed. If it _does_ connect to the binding, then it does mean this syntax is more general purpose and doesn't require support from the directive to work, but it means that `let-foo="bar"` differs in meaning depending on whether there is a `bind-bar` also present.

**Comment by wardbell** [comment] 2017-03-09 01:41
Did you consider
```
<div *ngIf="let user = userStream|async">...</div>
<div *ngFor="let user of let users = userStream|async; let i = index">
<div *ngFor="let user of (let users = userStream|async); let i = index">
```
Using `let x =` syntax is what we'd expect.  (2) is ugly but consistent; I'd feel better writing it as (3).

**Comment by alxhub** [comment] 2017-03-09 01:44
@wardbell, the problem is that `let user = foo` already has a meaning in Angular. `foo` is a reference to a context property in a template (`$implicit` in the case of the `let user`, `index` in `let i = index`, etc).

In that sense, as I understand it the proposal is that `<div *ngIf="expr as value">` has the same meaning as `<div *ngIf="expr; let value = ngIf">`.

**Comment by wardbell** [comment] 2017-03-09 01:47
@alxhub I see the problem. Can't index the context by 'userStream|async`.  Oh well.

**Comment by mhevery** [comment] 2017-03-09 04:06
> @alxhub  In other words, does the fact that as occurs in the of keyed binding result in the variable assigned the value of the ngForOf export, not ngFor?

yes

> I think one problem is that this won't work unless the directive supports it. If my directive does not instantiate its template with custom in the context

Correct, if the directive does not support it, than it would be an error.

**Comment by mhevery** [comment] 2017-03-09 04:12
> @wardbell  Have I got this right so far?

Yes, you got it all correct

> The *ngFor does NOT de-sugar to let-users="ngForOf" but rather to let-users="ngFor"

No, it desugars to `let-users="ngForOf"` since `of items as users` is the unit.

> Directive authors don't have to do anything to support the proposed syntax. Taking his example

No, the directive authors have to explicitly export the value under that string otherwise it does not work. This implies that the value could be transformed by the directive.

> the microsyntax ensures that let-value is the value of expr

No it does not. See above. It is possible that the directive exports the value other than the one which was bound to it. Remember, we are not creating new rules here, just defining how things are desugared, and the only primitive we have is `let`. `as` is another way to do `let`

**Comment by mhevery** [comment] 2017-03-09 04:13
@laco0416 

> But as syntax is completely new DSL and incompatible with JavaScript. It's not well-known syntax.
> And as @wardbell says, as is used in TypeScript.
> 
> Is this proposal for 5.0?

This is for v4.0 because there is large pushback for `*ngIf="userStream|async; let user"` and people prefer `*ngIf="userStream|async as user"`.

**Comment by mhevery** [comment] 2017-03-09 04:16
> @alxhub  I also don't think @mhevery meant that ngIf refers to the value of the binding to the ngIf input, but some clarification is needed. If it does connect to the binding, then it does mean this syntax is more general purpose and doesn't require support from the directive to work, but it means that let-foo="bar" differs in meaning depending on whether there is a bind-bar also present.

Yes I did mean that `key1 exp1 as var1` is `[key1]="exp1" let-var1="key1"`. Yes it does mean that the directive has to support it, and it does mean that the directive could do a transformation.

Again, we can't create new semantics, we can only desugar to existing primitives which are already implemented and we don't support creation of local variable without directive support.

**Comment by mhevery** [comment] 2017-03-09 04:17
> @alxhub  In that sense, as I understand it the proposal is that `<div *ngIf="expr as value">` has the same meaning as `<div *ngIf="expr; let value = ngIf">`.

Yes that is 100% correct and a good way to think about it.

**Comment by Toxicable** [comment] 2017-03-09 04:26
I think it's a good idea to simply the syntax but I'm not a fan of the `as` keyword since in your TS you use `as` for type casting which could cause confusion

**Comment by laco0416** [comment] 2017-03-09 05:02
@mhevery Ok, well... So, `NgIfLet` will be reverted at rc.X and new `as` syntax will be in the place of that, right? Or, will the both syntaxes be in 4.0?

**Comment by codef0rmer** [comment] 2017-03-09 05:09
In the following example, I'm evaluating the stream twice i.e. in ngIf and ngFor.

```
<ul *ngIf="(calls$ | async)?.length == 0">
   <li *ngFor="let call of calls$ | async">{{ call.caller }}</li>
</ul>
```
Will the proposed syntax convert the above example to following, evaluating the stream only once in ngIf and using the result in ngFor. If yes, I see some #perf improvements too. 

```
<ul *ngIf="(calls$ | async as calls)?.length == 0">
   <li *ngFor="let call of calls">{{ call.caller }}</li>
</ul>
```

**Comment by Toxicable** [comment] 2017-03-09 05:33
@laco0416 I believe the intention is to replace the current syntax with whatever is decided here
@codef0rmer this is already possible with the improved ngIf in 4.x , this discussion is for the syntax of it

@mhevery I think that `as` is not a good choice of keyword here since it's being used in TS for type casting already as pointed out by @laco0416 and @wardbell 
SoI propose a symbol instead if possible? and if that's possible them perhaps `#` since that is already familiar syntax.
For example `<div *ngIf="expr #value"` or `ngIf="userStream|async #user"`
I understand it's that using `#` might be impossible since it's already being used but wanted to check anyway

**Comment by laco0416** [comment] 2017-03-09 05:51
probably this is not good to say here, to begin this, I think `NgIf` and `NgFor` should not become _smarter_. As my idea, most of all problems mentioned here can be solved by one directive, `ngAssign`. 

```html
<ng-container *ngAssign="let users = users$ | async">
  <ul *ngIf="users">
    <li *ngFor="let user of users">{{user.name}}</li>
  </ul>
</ng-container>
```

maybe this is verbose a little, but simplest. People can read this template as well as JavaScript.

```
let users = async(users$);
if (users) {
  for (let user of users) {
  }
}
``` 

BTW, I was going to submit the above proposal in the near future. but it runs counter to this issue :)

**Comment by petebacondarwin** [comment] 2017-03-09 06:20
Is it important that the new keyword is a reserved word in TypeScript? If not then how about `into`?

```
<div *ngIf="userStream|async into user">...</div>
```

**Comment by bfricka** [comment] 2017-03-09 06:33
> Is "as" a good name?
>
> I was taken aback at first because as is how we cast in > TypeScript. But I can't think of anything better.

This is precisely how you alias ES2015 imports. For two modules exporting `foo`:

```ts
import {foo as bar} from './bar';
import {foo as baz} from './baz';
```

**Comment by bfricka** [comment] 2017-03-09 06:36
> Is it important that the new keyword is a reserved word in TypeScript? If not then how about into?

`let` is a keyword as well

**Comment by mprobst** [comment] 2017-03-09 08:34
What about `let foo := expr`?

**Comment by laco0416** [comment] 2017-03-09 08:49
FYI, I like golang's if-statement with assignment

```go
if foo := someFunc(); foo != nil {
}
```

**Comment by vukasin-nikodijevic** [comment] 2017-03-09 09:08
To be honest I don't have anything against `let` syntax - for me it is more declarative  and readable.

**Comment by jsayol** [comment] 2017-03-09 10:05
+1 on the proposed syntax from me.

And go with `as` since everyone will understand what it means. Like @bfricka pointed out, `as` is already being used in ES6/TS to rename a symbol being imported and that's a very similar concept to what it will be used for in the microsyntax. No need to complicate things introducing new keywords or formatting.

**Comment by martinmcwhorter** [comment] 2017-03-09 10:26
Initially didn't like `as` syntax. Would have preferred @wardbell suggestion of `let foo = fooObservable|async`...but @bfricka argument won me over.

**Comment by jsayol** [comment] 2017-03-09 10:33
Just a note on ngFor:

> We could also add , for let so that it can become:
> ```html
> <div *ngFor="let i = index, user of userStream|async as users">
>   {{user}} {{i}} of {{users.length}}
> </div>
> ```

I don't really like this syntax, the comma makes it awkward to read.

Much better this way:

> Alternatively it could be expressed as:
> ```html
> <div *ngFor="let user of userStream|async as users; index as i">
>   {{user}} {{i}} of {{users.length}}
> </div>
> ```

**Comment by jvandemo** [comment] 2017-03-09 10:46
+1 for `as` syntax.

The semantics of both

```html
<div *ngIf="userStream|async as user">
  {{user}}
</div>
```
and
```html
<div *ngFor="let user of userStream|async as users; let i=index">
  {{user}} {{i}} of {{users.length}}
</div>
```
are easy to understand for developers.

The syntax is easy, concise and looks similar to aliasing module names in ES6.

If there is no technical reason not to use `as`, then I would vote for `as` 👍

**Comment by netstart** [comment] 2017-03-09 11:42
I think 'async' should not be necessary
The framework should have abstracted this for me.

transparent and clear

**Comment by DzmitryShylovich** [comment] 2017-03-09 12:08
@netstart it's just an example. it can be any pipe

**Comment by chaosmonster** [comment] 2017-03-09 13:41
+1 for `as`syntax as mentioned by @jvandemo

**Comment by Brocco** [comment] 2017-03-09 13:50
@netstart there were issues over this dating back to AngularJS whether promises were automatically unwrapped or not, I much prefer being explicit when using observables especially because at times I find it helpful to pass an observable to a child component rather than just the latest value.

As for the proposed syntax, I like the use of the `as` keyword because it accomplishes two things. It provides clear syntax for referencing values and it alleviates multiple subscriptions to observables by eliminating the need to use the async pipe in multiple places.

This has the added benefit of reducing the use of the `share` operator in component's code which is really a concern of the view and not of component's logic.

**Comment by sod** [comment] 2017-03-09 15:54
Do it like in angularjs. Felt naturally to a javascript developer:
```twig
<div *ngFor="item of (items = itemsStream|async)"></div>
<div *ngIf="item = itemStream|async"></div>
```

or with let
```twig
<div *ngFor="let item of (let items = itemsStream|async)"></div>
<div *ngIf="let item = itemStream|async"></div>
```

Don't have to invent syntax if it behaves just like javascript :)

**Comment by tbosch** [comment] 2017-03-09 16:06
+1. In general, I am worried that our syntax is very permissive, i.e. allows many cases that are usually unintended errors by users. Maybe we should revisit our micro syntax for v5 to make it more strict and give users better error messages.

**Closed** 2017-03-15 03:46 UTC
Labels: comp: common, comp: core & compiler, type: feature

**Comment by Martin-Wegner** [comment] 2017-03-17 10:05
@mhevery before I cached the Observable with `.share()` and used this template:

```
<span *ngIf="!(user$ | async)">Loading user information...</span>
<span *ngIf="(user$ | async)">{{(user$ | async).firstName}} {{(user$ | async).lastName}}</span>
```

With your solution I don't need the caching anymore but how I can show the loading message?

```
<span *ngIf="user$ | async as user">{{user.firstName}} {{user.lastName}}</span>
```

I got a template exception for:

```
<span *ngIf="!(user$ | async as user)">Loading user information...</span>
```

This code throws no template exception but also it does not trigger the Observable:

```
<span *ngIf="!user$ | async as user">Loading user information...</span>
```

And if the above code would work the Observable would be called twice:

```
<span *ngIf="!(user$ | async as user)">Loading user information...</span>
<span *ngIf="user$ | async as user">{{user.firstName}} {{user.lastName}}</span>
```

Any solution available?

**Comment by jsayol** [comment] 2017-03-17 10:13
@Martin-Wegner You're probably looking for `else`:

```html
<span *ngIf="user$ | async as user; else loadingUserInfo">{{user.firstName}} {{user.lastName}}</span>
<span #loadingUserInfo>Loading user information...</span>
```

It would pobably be better if you used other channels to ask support questions, though.

**Comment by Martin-Wegner** [comment] 2017-03-17 10:24
@jsayol with this code I get `ERROR TypeError: templateRef.createEmbeddedView is not a function` :(
