### ISSUE TITLE
Tour of Heroes tutorial issue

### ISSUE THREAD

**Issue by ryan-fanhub** [angular/angular#23590] opened 2018-04-28 10:57 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[*] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

On Live example from tutorial https://stackblitz.com/angular/ronrqepaoll 
https://ronrqepaoll.angular.stackblitz.io/heroes if you will remove all heroes and try to add new one the hero name and number will be empty. Also the message in "HeroService" will be  ''deleted hero" but action was  "adding".

## Expected behavior

When  I try to add hero (with name in input) I should see new hero card with name and id.

## What is the motivation / use case for changing the behavior?

Base tutorial should't be with such issues. :)

## Environment

<pre><code>
Angular version: 5.2.10

Browser:
- [*] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by lacolaco** [comment] 2018-04-29 08:47
It's occurred in new `id` generation. 

It might have to define a strategy for that. Here's an example;

```
import { InMemoryDbService } from 'angular-in-memory-web-api';

export class InMemoryDataService implements InMemoryDbService {
  private _lastId: number = 0;

  createDb() {
    const heroes = [
      { id: 11, name: 'Mr. Nice' },
      { id: 12, name: 'Narco' },
      { id: 13, name: 'Bombasto' },
      { id: 14, name: 'Celeritas' },
      { id: 15, name: 'Magneta' },
      { id: 16, name: 'RubberMan' },
      { id: 17, name: 'Dynama' },
      { id: 18, name: 'Dr IQ' },
      { id: 19, name: 'Magma' },
      { id: 20, name: 'Tornado' }
    ];
    this._lastId = 20;
    return { heroes };
  }

  responseInterceptor(res, reqInfo) {
    switch (reqInfo.method) {
      case 'post':
        const { body } = res;
        this._lastId = body['id'];
        break;
    }
    return res;
  }

  genId(collection, collectionName) {
    return this._lastId + 1;
  }
}
```

**Comment by trotyl** [comment] 2018-04-29 08:53
Duplicate of https://github.com/angular/angular/issues/22120

**Closed** 2018-04-30 11:11 UTC
