### ISSUE TITLE
Error: Cannot make XHRs from within a fake async test.

### ISSUE THREAD

**Issue by andrashatvani** [angular/angular#8280] opened 2016-04-27 12:53 UTC
**Steps to reproduce and a minimal demo of the problem**

_What steps should we try in your demo to see the problem?_

``` typescript
export function setupComponentFakeAsync(type:any, continuation:Function) {
    return fakeAsync(inject([TestComponentBuilder], (tcb:TestComponentBuilder) => {
        let fixture:ComponentFixture = null;
        tcb.createAsync(type).then((f:ComponentFixture) => fixture = f);
        tick(50);
        fixture.detectChanges();
        continuation(fixture);
    }));
}


it('shows an empty origin station text field in the default component state',
    setupComponentFakeAsync(SearchComponent, (fixture:ComponentFixture) => {
        let input:any = fixture.nativeElement.querySelector('#fromStation');

        expect(input.value).toBe('');
    })
);



**Current behavior**
Exception:

> Error: Cannot make XHRs from within a fake async test. in d:/Users/l026291/Development/ts-automat-fe/node_modules/zone.js/dist/fake-async-test.js (line 248)
    onScheduleTask@d:/Users/l026291/Development/ts-automat-fe/node_modules/zone.js/dist/fake-async-test.js:248:96
    scheduleTask@d:/Users/l026291/Development/ts-automat-fe/node_modules/angular2/bundles/angular2-polyfills.js:359:64
    scheduleMacroTask@d:/Users/l026291/Development/ts-automat-fe/node_modules/angular2/bundles/angular2-polyfills.js:299:52
    d:/Users/l026291/Development/ts-automat-fe/node_modules/angular2/bundles/angular2-polyfills.js:148:39
    send

**Expected/desired behavior**
The test is working just as with beta 15.

**Other information**
```

**Comment by aprinaresh97** [comment] 2016-05-20 06:26
We are also running into the same issue. Is there a solution for this. All our unittests are failing because  of this issue. I assume the XHR is used to load the styleUrl. Is there a workaround for this. Due to this issue, we are not able to close any story because of failure to meet the acceptance criteria.

Let us know how to proceed.

**Comment by aprinaresh97** [comment] 2016-05-20 09:37
To make some of the tests passing, I had to remove the fakeAsync and skip tests that uses tick (as tick works only in the fakeAsyncZone).

What are our options? Is this going to be fixed soon?

**Comment by simo14** [comment] 2016-05-22 16:40
Same here. If I use async to inject the component karma fails. If I use fakeAsync I get this exception.

**Comment by onlyann** [comment] 2016-05-25 05:05
This issue is also preventing us from unit testing any component that makes uses of `setTimeout` or the `delay` Rxjs operator.

**Comment by roni-frantchi** [comment] 2016-06-09 08:46
+1 here...

**Comment by yjaaidi** [comment] 2016-06-17 12:46
+1

**Comment by yjaaidi** [comment] 2016-06-17 23:31
I guess I know where it comes from!
Are you guys using `templateUrl` ?
Because I have mocked the `Http` service and still got the error until I replaced `templateUrl` with `template`.

We should find a way to override all component templates.

**Comment by zoechi** [comment] 2016-06-20 09:14
@yjaaidi what Angular2 version?

**Comment by yjaaidi** [comment] 2016-06-21 06:40
Hi @zoechi,

It's rc1. Didn't try with rc2 yet.

**Comment by juliemr** [comment] 2016-06-21 16:43
This is working as intended - we can't "fake" async behavior in any reasonable way if a real XHR is made, so the test must throw an error. `templateUrl` and `styleUrl` make XHRs.

Something that we can do, however, is run tests against a cached version of the templates and styles, so we don't need to make the XHR in the first place. @vikerman worked on a system to do this, see https://github.com/angular/angular/pull/7940

There is little documentation though - we should add an example of a test setup using this. @vikerman does one exist that I don't know about, or should I create one?

**Comment by vicb** [comment] 2016-06-21 16:44
Should that be in a cookbook on angular.io ? If you think this makes sense could you please create an issue with the detailson the angular.io repo. Thanks.

**Comment by centaure** [comment] 2016-06-23 04:35
Below is a spec example for a component using `templateUrl` (adapted from [here](https://github.com/angular/angular/blob/master/modules/%40angular/platform-browser-dynamic/test/xhr/xhr_cache_spec.ts)). 

However, the `templateUrl` is being mapped to its content string within `setTemplateCache` below (i.e. content of _./application.html_ is still being inlined). 
Is there a straightforward way to read from the actual _./application.html_ file in this example (Note that I am using [systemjs](https://github.com/systemjs/systemjs) for loading modules)?

     import { ComponentFixture, TestComponentBuilder } from '@angular/compiler/testing';
     import { Component } from '@angular/core';
     import {
       beforeEachProviders,
       describe,
       expect,
       fakeAsync,
       inject,
       it,
       tick,
     } from '@angular/core/testing';
     import { UrlResolver, XHR } from '@angular/compiler';
     import { CachedXHR } from '@angular/platform-browser-dynamic/src/xhr/xhr_cache';

     describe('ApplicationComponent fixture', () => {
       var xhr: CachedXHR;
       function createCachedXHR(): CachedXHR {
         setTemplateCache(
           {
             './application.html': '<div>Hello World</div>',
           }
         );
         return new CachedXHR();
       }
       beforeEachProviders(() => {
         return [
           { provide: UrlResolver, useClass: TestUrlResolver },
           { provide: XHR, useFactory: createCachedXHR }
         ];
       });

       it ('should have the correct content',
         fakeAsync(inject([TestComponentBuilder],
           (tcb: TestComponentBuilder) => {
             let fixture: ComponentFixture;

             tcb.createAsync(ApplicationComponent).then((f) => { fixture = f; });
             tick();
             expect(fixture.debugElement.children[0].nativeElement).toHaveText('Hello World');
           }
         ))
       );
     });

     export function setTemplateCache(cache): void {
       (<any>window).$templateCache = cache;
     }

     class TestUrlResolver extends UrlResolver {
       resolve(baseUrl: string, url: string): string {
         // Don't use baseUrl to get the same URL as templateUrl.
         // This is to remove any difference between Dart and TS tests.
         return url;
       }
     }

     @Component({
       selector: 'app',
       templateUrl: './application.html'
     })
     export default class ApplicationComponent {}

**Comment by simonxca** [comment] 2016-08-03 03:28
@centaure Here's how I hacked my way through this:
- Serve your `.html` and `.css` files. I'm using Karma so in my karma.conf.js I put:
```
files: [
  ...
  {
    pattern: 'public/templates/**/*.html',
    included: false,
    served: true
  },
  {
    pattern: 'public/css/**/*.css',
    included: false,
    served: true
  },
  ...
]
```
- At the start of your tests, do a GET request for the files you want cached and save them in `window.$templateCache`. At the start of my tests, I'm loading a file called `karma-test-shim.js` (https://github.com/simonxca/mean2-playground/blob/master/karma-test-shim.js) so in my `karma-test-shim.js`, I would:

1. Define `window.$templateCache = {}` at the top.
2. Populate the template cache:

```
// load your test files
}).then(function () {
  ...

// GET .html and .css templates and cache them
}).then(function () {

  return Promise.all(
    Object.keys(window.__karma__.files)

    .filter(function (filename) {
      var isTemplate = filename.startsWith('/base/public/templates') && filename.endsWith('.html');
      var isCss = filename.startsWith('/base/public/css') && filename.endsWith('.css');
      return isTemplate || isCss;
    })

    .map(function (filename) {
      return new Promise((resolve, reject) => {
        $.ajax({
          type: 'GET',
          url: filename,
          dataType: 'text',
          success: function (contents) {
            filename = filename.replace('/base/public/', '');
            window.$templateCache[filename] = contents;
            resolve();
          }
        });
      });
    })
  );

// start karma
}).then(function () {
  ...
});
```
As you can see, I make a GET request for the contents of the files I want and just save them in the `window.$templateCache` object, which will be loaded later by CachedXHR.

**Comment by gridcellcoder** [comment] 2016-09-28 21:27
@juliemr  @vikerman  do you guys have an example of using the cache to load template url contents?

**Comment by mattxo** [comment] 2016-11-17 07:43
Hm, same problem here... 

`    it('should show already exists message when save button clicked', fakeAsync(() => 
    {                     
        Promise.all
        ([
            page.sendInput(page.firstNameInput, 'Matt'),
            page.sendInput(page.lastNameInput, 'Searles'),
            page.sendInput(page.emailInput, 'matt_2304@hotmail.com'),
            page.sendInput(page.passwordInput, 'abcDEF123'),
        ])
        .then(() => 
        {            
            page.form.submit();                                    
            tick();
            expect(boilerplate.component.errorMessage).toContain('already exists');                                                                                                                                
        })         
    }));   `

Where page.form.submit() simply calls register() and users.register() is hitting a local unit test database...
`
    register(event : any)
    {                        
        event.preventDefault();
                
        return this.users.register(this.model)            
            .then(user => this.onSuccess(user))
            .catch(error => this.onError(error));        
    }`

**Comment by yjaaidi** [comment] 2016-11-17 20:48
Hello @mattxo ,

Oh! That's normal. As your app is making an http request, `fakeAsync` can't fake http.

You should mock the http backend. It's not as fun as AngularJS 1.x `$httpBackend` but here's a batteries included pattern.

```typescript

    beforeEach((done) => {

        TestBed
            .configureTestingModule({
                imports: [
                    UserModule
                ],
                providers: [
                    MockBackend,
                    {
                        provide: Http,
                        deps: [MockBackend, RequestOptions],
                        useFactory: (mockBackend, requestOptions) => {
                            return new Http(mockBackend, requestOptions);
                        }
                    }
                ]
            })
            .compileComponents()
            .then(done);

    });

    beforeEach(inject([MockBackend], (mockBackend: MockBackend) => {

        this.spyConnection = jasmine.createSpy('connection');

        mockBackend.connections.subscribe((connection: MockConnection) => {
            connection.mockRespond(new Response(new ResponseOptions(this.spyConnection({
                body: connection.request.text(),
                method: connection.request.method,
                url: connection.request.url
            }))));
        });

    }));

    it(..., () => {
        this.spyConnection.and.returnValue({
            body: { /* YOUR EXPECTED RESPONSE HERE */ },
            status: 200
        });

        expect(this.spyConnection).toHaveBeenCalledTimes(1);
        expect(this.spyConnection.calls.argsFor(0)[0].method).toEqual(RequestMethod.Get);
        expect(this.spyConnection.calls.argsFor(0)[0].url).toEqual('/api/v1/endpoint.../');

    });

```

**Comment by mattxo** [comment] 2016-11-18 00:37
Hey @yjaaidi,

Thanks for the sample code :) 

I'd prefer not mock the backend in this case though, if I can help it. It's an integration test, and performance isn't an issue with a local database. 

The fakeAsync in this case is only there to make this work

```
form.submit();
tick(); // wait until all promises resolve

```

What I really like, if it's not possible to have the XHR run synchronously when called under fakeAsync, is to have a promise returned from form.submit() or possibly better still, from page.submitButton.click(), but that doesn't seem possible either...

**Comment by Olgagr** [comment] 2017-10-26 15:08
We had the same error. For us the key thing was setup providers correctly in TestBed.configureTestingModule.

```
let lastConnection: any;
let component: InvoiceFormComponent;

beforeEach(() => {
TestBed.configureTestingModule({
    imports: [...],
    providers: [
        {
          provide: ConnectionBackend,
          useClass: MockBackend,
        },
        {
          provide: RequestOptions,
          useClass: BaseRequestOptions,
        },
        Http, // DON'T FORGET TO ADD THIS! 
    ],
    declarations: [MyComponent],
}).compileComponents();
    let backend = TestBed.get(ConnectionBackend) as MockBackend;
    backend.connections.subscribe((connection: any) => { lastConnection = connection; });
));
```

Then in the test:

```
it('getWorkItemsOptions', fakeAsync(() => {
    let options;
    componentFixture = TestBed.createComponent(MyComponent);
    component = componentFixture.componentInstance;

    component.someAsyncAction().subscribe((result) => {
        options = result;
    });

   lastConnection.mockRespond(new Response(new ResponseOptions({
       body: JSON.stringify([{ name: 'one' }, { name: 'two' }]),
       status: 200,
    })));
   tick();
   expect(options.length).toEqual(2);
}));
```

**Comment by vikerman** [comment] 2018-01-26 22:18
Example should be covered as part of resolving #12409

**Closed by vikerman** 2018-01-26 22:18 UTC
Labels: comp: testing, hotlist: example tests
