### ISSUE TITLE
Name outlets doesn't work with lazy loaded modules.

### ISSUE THREAD

**Issue by markqian** [angular/angular#17343] opened 2017-06-08 19:44 UTC
I am submitting a [x] **bug report**

**Current behavior**

with lazy loaded modules I can not visit its child routes that uses named outlets.
For example

localhost:3000/heroes/(abc:list) doesn't work where heroes module is lazy loaded.

**Expected behavior**

I should be able to visit localhost:3000/heroes/(abc:list)

**Minimal reproduction of the problem with instructions**

Go to https://plnkr.co/edit/NNXAoZItM00RIIxzemts?p=preview and download the sample app into a zip file then run it by npm install and npm start. 

**What is the motivation / use case for changing the behavior?**

To lazy load module with name outlets.

**Please tell us about your environment:**

Windows 10, visual studio code, chrome

* **Angular version:** 
4.0
* **Browser:** 

 Chrome, Firefox

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

TypeScript

**Comment by jasonaden** [comment] 2017-07-18 00:52
Duplicate of #10981

**Closed by jasonaden** 2017-07-18 00:52 UTC
Labels: comp: router

**Comment by Jonathan002** [comment] 2019-07-20 08:06
@markqian Hi Markqian, I've created a workaround solution that is intended to help with named outlets and lazy modules. Please have a look and hope this helps.

Repo: https://github.com/Jonathan002/route-master-example
