### ISSUE TITLE
Unexplained DOM Node accumulation and performance degradation in Angular 17 while routing between pages

### ISSUE THREAD

**Issue by benb545** [angular/angular#53915] opened 2024-01-14 23:22 UTC
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

When navigating between my pages in my application using `this.router.navigate`, my DOM Nodes are increasing and the whole application eventually starts to slow down (Especially animations and transitions). 

This happens mostly on Chrome, but also happens in Edge and Firefox but a lot better, takes more time to make it slow, or navigating between bigger pages with more elements.

I have another app in the company that is a lot bigger than the app I write now with Angular 17, and is written with Angular 13 and has way more content and heavier pages, written very similar and this doesn't happen, nodes getting cleared eventually and nothing slows down.

I am not sure how to fix this, after long researching.

I unsubscribe on destroys, I destroy unused components (actually it does it automatically on navigating), I use trackBy, I use a lot of ngIfs for skeleton loaders though, not sure if it can cause an issue. I don't use the new control flow.

There are some performance & memory screenshots:

![image](https://github.com/angular/angular/assets/108220449/94bc5710-1a0c-4214-892f-827baefbab0e)
![image](https://github.com/angular/angular/assets/108220449/d548c46f-6df3-4ec2-813a-3c020205bc35)

### Please provide the exception or error you saw

```true
No errors
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 17.0.5
Node: 18.13.0
Package Manager: npm 8.19.3
OS: win32 x64

Angular: 17.0.5
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.5
@angular-devkit/build-angular   17.0.5
@angular-devkit/core            17.0.5
@angular-devkit/schematics      17.0.5
@angular/cdk                    17.0.4
@schematics/angular             17.0.5
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.2
```

**Comment by JeanMeche** [comment] 2024-01-14 23:24
Hi, without a reproduction this isn't actionnable to use. Please try to provide a narrowed down example of the memory leak.

**Comment by JeanMeche** [comment] 2024-02-09 18:48
You didn't provide a reproduction also I see that this is likely animation related, so I believe it is a dupe of #54149

**Closed by JeanMeche** 2024-02-09 18:48 UTC
Labels: needs reproduction, area: router
