### ISSUE TITLE
Expression has changed after it was checked exception if asyncpipe is used together with class property binding

### ISSUE THREAD

**Issue by Matthias247** [angular/angular#6467] opened 2016-01-13 19:46 UTC
See the following Plunker for repro: http://plnkr.co/edit/MrCUDP8qwGPj7ler4ySW

The code `[class.selected]="toggleSvc.isActive | async"` where toggleSvc.isActive is a BehaviorSubject results in the following error message:

> EXCEPTION: Expression 'toggleSvc.isActive | async in AppComponent@1:7' has changed after it was checked. Previous value: 'true'. Current value: 'true' in [toggleSvc.isActive | async in AppComponent@1:7]

I don't see how the value is changed after change detection - ng2 even says that it stayed the same in this error message (true -> true).

Don't exactly know if this is related only to class property bindings or to all kinds, because this is currently the main thing that I'm observing.

Replacing the line with `[class.selected]="toggleSvc._isActive"` makes it run correctly.
The binding in the content (`Active: {{toggleSvc.isActive | async}}`) works without issues.

**Comment by CaptainCodeman** [comment] 2016-01-13 23:21
Don't know if this helps (maybe related) but I get the same error if I try and return dictionary values using any form of `Object.keys(value).map(key => value[key])` (whether in a method, via a pipe, as the iterator source for the `ngFor` etc...).

It's like it's looking at the list rather then the values _in_ the list.

**Comment by robwormald** [comment] 2016-01-14 05:24
this is a known issue with BehaviorSubjects, see https://github.com/angular/angular/pull/5996, fix is pending so I'll close as a duplicate of that.

**Closed by robwormald** 2016-01-14 05:24 UTC
