### ISSUE TITLE
bundle does not contain NativeShadowDomStrategy

### ISSUE THREAD

**Issue by tbosch** [angular/angular#2688] opened 2015-06-22 21:45 UTC

**Comment by rkirov** [comment] 2015-06-22 22:06
It should be because it is exported here https://github.com/angular/angular/blob/master/modules/angular2/render.ts#L10

**Comment by PascalPrecht** [comment] 2015-06-23 11:16
@rkirov unfortunately both, `EmulatedScopedShadowDomStrategy` and `NativeShadowDomStrategy` are not part of the bundle. Try a simple search here: https://code.angularjs.org/2.0.0-alpha.27/angular2.dev.js

**Comment by rkirov** [comment] 2015-06-24 01:19
The problem is in the entry point for the bundle which is `angular2.ts` we don't import the `render.ts` module.

https://github.com/angular/angular/blob/master/modules/angular2/angular2.ts#L76

Instead we reexport `angular2/src/render/api`. @tbosch what is the reason for that, and are you ok with changing that line to `angular2/render`?

**Comment by PascalPrecht** [comment] 2015-06-24 08:22
Prepared a PR at #2717 that can be merged, once @tbosch made a decision.

**Comment by tbosch** [comment] 2015-06-25 18:21
Yes, please export everything from `angular2/render`.

**Comment by rkirov** [comment] 2015-06-25 18:23
Pascal can you change your PR to just reexport `angular2/render` and reassign the PR to me for review.
Ideally, `angular2/angular2` should not have any `angular2/src/*` paths.

**Comment by PascalPrecht** [comment] 2015-06-26 07:54
Yeap, taking care of this!

**Comment by PascalPrecht** [comment] 2015-06-26 08:06
Just one quick question: There are a couple of imports that come from angular2/src/render but are **not** exported by angular2/render e.g. https://github.com/angular/angular/blob/master/modules/angular2/src/core/application.ts#L40-L41

Shall I just leave them in?

**Comment by mhevery** [comment] 2015-08-21 02:50
Obsolete

**Closed by mhevery** 2015-08-21 02:50 UTC
Labels: comp: build/dev-productivity, effort2: medium (day), P2: required, state: Periodic Review, type: feature
