### ISSUE TITLE
I can access a private variable but don't get an angular error

### ISSUE THREAD

**Issue by kevincam3** [angular/angular#18638] opened 2017-08-10 20:50 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I set a variable in a component to private but using it directly in my html template it doesn't issue a warning with ! in front but does without ! 

## Expected behavior

Expected a warning

## Environment

<pre><code>
Angular version: 4.3.4

 
For Tooling issues:
- Node version: 8.3.0  
- Platform: Windows 10  

Others:

</code></pre>

![private-var-with-not-no-error](https://user-images.githubusercontent.com/870934/29191503-560dd340-7df4-11e7-933d-afd3badf84be.jpg)

![private-var-with-error](https://user-images.githubusercontent.com/870934/29191511-5cdeec0e-7df4-11e7-8949-bd31d585dbb7.jpg)

**Comment by Toxicable** [comment] 2017-08-11 00:55
Run the AOT compiler, it will throw when using a private variable in a template

**Comment by KostyaTretyak** [comment] 2017-09-22 13:47
How about VS Code? With this editor I have everything working as it should be.

**Comment by trotyl** [comment] 2018-11-16 12:51
Duplicate of https://github.com/angular/angular/issues/14739

**Comment by pkozlowski-opensource** [comment] 2020-03-11 12:23
This is already fixed, see https://github.com/angular/angular/issues/14739#issuecomment-597602255

**Closed by pkozlowski-opensource** 2020-03-11 12:23 UTC
Labels: comp: language-service, freq3: high, severity3: broken, type: bug/fix
