### ISSUE TITLE
Getting error while Angular Universal server running related to cookie

### ISSUE THREAD

**Issue by dexbytesmanish** [angular/angular#27230] opened 2018-11-22 13:12 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....
@angular/platform-server
@ng-toolkit/universal

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....
No

### Description

 A clear and concise description of the problem...
I am getting following error in terminal after running npm run server command and opening http://localhost:8080 URL in browser :

ERROR { Error: Uncaught (in promise): Error: This method is not implemented in DominoAdapter: getCookie
Error: This method is not implemented in DominoAdapter: getCookie
at _notImplemented (/var/www/html/project-angular6/dist/server.js:87272:12)
at DominoAdapter.module.exports.DominoAdapter.getCookie (/var/www/html/project-angular6/dist/server.js:87463:65)
at CookieXSRFStrategy.module.exports.CookieXSRFStrategy.configureRequest (/var/www/html/project-angular6/dist/server.js:76600:101)
at XHRBackend.module.exports.XHRBackend.createConnection (/var/www/html/project-angular6/dist/server.js:76641:28)
at httpRequest (/var/www/html/project-angular6/dist/server.js:77008:20)
at Http.module.exports.Http.request (/var/www/html/project-angular6/dist/server.js:77106:34)
at Http.module.exports.Http.get (/var/www/html/project-angular6/dist/server.js:77117:21)
at topbannerService.module.exports../src/app/home/top-banner/top-banner.service.ts.topbannerService.getTopFeatureData (/var/www/html/project-angular6/dist/server.js:154860:26)
at TopBannerComponent.module.exports../src/app/home/top-banner/top-banner.component.ts.TopBannerComponent.getTopFeaturedArtworks (/var/www/html/project-angular6/dist/server.js:154815:31)
at new TopBannerComponent (/var/www/html/project-angular6/dist/server.js:154811:14)
at resolvePromise (/var/www/html/project-angular6/dist/server.js:117327:31)
at resolvePromise (/var/www/html/project-angular6/dist/server.js:117284:17)
at /var/www/html/project-angular6/dist/server.js:117386:17
at ZoneDelegate.module.exports.ZoneDelegate.invokeTask (/var/www/html/project-angular6/dist/server.js:116934:31)
at Object.onInvokeTask (/var/www/html/project-angular6/dist/server.js:4204:33)
at ZoneDelegate.module.exports.ZoneDelegate.invokeTask (/var/www/html/project-angular6/dist/server.js:116933:36)
at Zone.module.exports.Zone.runTask (/var/www/html/project-angular6/dist/server.js:116701:47)
at drainMicroTaskQueue (/var/www/html/project-angular6/dist/server.js:117108:35)
at module.exports.ZoneTask.invokeTask (/var/www/html/project-angular6/dist/server.js:117013:21)
at Server.ZoneTask.invoke (/var/www/html/project-angular6/dist/server.js:116998:48)

and not able to see server side rendered page content in view source on other than home page routes and lazy loaded modules routes.

## 🔬 Minimal Reproduction

 https://stackblitz.com/...

I have followed this tutorial to setup Universal : https://www.devglan.com/angular/angular-universal-server-side-rendering. I am getting error where I am calling API to get data in following code :
in component.ts :
this.topbannerService.getTopFeatureData().subscribe(data=>{ })
topbannerUrl = this._global.baseAPIUrl+"home-page-top-featured";

in service.ts:
getTopFeatureData(){
return this.http.get(this.topbannerUrl)
.pipe(
map(res =>this.extractData(res)),
catchError(err => this.handleError(err))
);
}
## 🔥 Exception or Error
<pre><code>

ERROR { Error: Uncaught (in promise): Error: This method is not implemented in DominoAdapter: getCookie
Error: This method is not implemented in DominoAdapter: getCookie
at _notImplemented (/var/www/html/project-angular6/dist/server.js:87272:12)
at DominoAdapter.module.exports.DominoAdapter.getCookie (/var/www/html/project-angular6/dist/server.js:87463:65)
at CookieXSRFStrategy.module.exports.CookieXSRFStrategy.configureRequest (/var/www/html/project-angular6/dist/server.js:76600:101)
at XHRBackend.module.exports.XHRBackend.createConnection (/var/www/html/project-angular6/dist/server.js:76641:28)
at httpRequest (/var/www/html/project-angular6/dist/server.js:77008:20)
at Http.module.exports.Http.request (/var/www/html/project-angular6/dist/server.js:77106:34)
at Http.module.exports.Http.get (/var/www/html/project-angular6/dist/server.js:77117:21)
at topbannerService.module.exports../src/app/home/top-banner/top-banner.service.ts.topbannerService.getTopFeatureData (/var/www/html/project-angular6/dist/server.js:154860:26)
at TopBannerComponent.module.exports../src/app/home/top-banner/top-banner.component.ts.TopBannerComponent.getTopFeaturedArtworks (/var/www/html/project-angular6/dist/server.js:154815:31)
at new TopBannerComponent (/var/www/html/project-angular6/dist/server.js:154811:14)
at resolvePromise (/var/www/html/project-angular6/dist/server.js:117327:31)
at resolvePromise (/var/www/html/project-angular6/dist/server.js:117284:17)
at /var/www/html/project-angular6/dist/server.js:117386:17
at ZoneDelegate.module.exports.ZoneDelegate.invokeTask (/var/www/html/project-angular6/dist/server.js:116934:31)
at Object.onInvokeTask (/var/www/html/project-angular6/dist/server.js:4204:33)
at ZoneDelegate.module.exports.ZoneDelegate.invokeTask (/var/www/html/project-angular6/dist/server.js:116933:36)
at Zone.module.exports.Zone.runTask (/var/www/html/project-angular6/dist/server.js:116701:47)
at drainMicroTaskQueue (/var/www/html/project-angular6/dist/server.js:117108:35)
at module.exports.ZoneTask.invokeTask (/var/www/html/project-angular6/dist/server.js:117013:21)
at Server.ZoneTask.invoke (/var/www/html/project-angular6/dist/server.js:116998:48)
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 6.2.6
Node: 10.10.0
OS: linux x64
Angular: 6.1.10
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.8.6
@angular-devkit/build-angular     0.8.6
@angular-devkit/build-optimizer   0.8.6
@angular-devkit/build-webpack     0.8.6
@angular-devkit/core              0.8.6
@angular-devkit/schematics        0.8.6
@angular/cli                      6.2.6
@angular/pwa                      0.8.6
@ngtools/webpack                  6.2.6
@schematics/angular               0.8.6
@schematics/update                0.8.6
rxjs                              6.3.3
typescript                        2.9.2
webpack                           4.23.1
</code></pre>

**Anything else relevant?**

No, this is server specific

No

**Comment by CaerusKaru** [comment] 2018-11-28 20:19
As I have mentioned now in two other repositories, this is not an issue with Angular Universal or Domino. You are depending on an outside library that is using an unsupported API. To resolve this, you must either remove this library on the server, or add a polyfill for the API in question. You can receive help with both of these approaches on channels better suited for that, like Gitter or StackOverflow. This is an issue tracker, not a support forum.

**Comment by CaerusKaru** [comment] 2018-11-28 20:20
For reference, duplicate of https://github.com/angular/universal/issues/1094 and https://github.com/fgnass/domino/issues/132

**Comment by dexbytesmanish** [comment] 2018-11-29 05:34
I have resolved the issue by replacing Http with
 import { HttpClient } from '@angular/common/http';
as dependincy for http request since Http was not compatible with universal
package after upgrade.

**Closed** 2018-12-04 23:49 UTC
Labels: comp: server
