### ISSUE TITLE
undefined element under <router-outlet></router-outlet> when routing

### ISSUE THREAD

**Issue by PrimeObjects** [angular/angular#6284] opened 2016-01-06 01:48 UTC
you can try http://plnkr.co/edit/?p=preview to reproduce

if click the crisis center, in Chrome dev tool, you can see the follow html elements

&lt;undefined&gt; &lt;h2&gt;CRISIS CENTER&lt;/h2&gt; &lt;router-outlet&gt;&lt;/router-outlet&gt;&lt;undefined _nghost-nwi-7=&quot;&quot;&gt; &lt;h3 _ngcontent-nwi-7=&quot;&quot;&gt;&quot;Release Deadline Looms&quot;&lt;/h3&gt; &lt;div _ngcontent-nwi-7=&quot;&quot;&gt; &lt;label _ngcontent-nwi-7=&quot;&quot;&gt;Id: &lt;/label&gt;4&lt;/div&gt; &lt;div _ngcontent-nwi-7=&quot;&quot;&gt; &lt;label _ngcontent-nwi-7=&quot;&quot;&gt;Name: &lt;/label&gt; &lt;input placeholder=&quot;name&quot; _ngcontent-nwi-7=&quot;&quot; class=&quot;ng-untouched ng-pristine ng-valid&quot;&gt; &lt;/div&gt; &lt;button _ngcontent-nwi-7=&quot;&quot;&gt;Save&lt;/button&gt; &lt;button _ngcontent-nwi-7=&quot;&quot;&gt;Cancel&lt;/button&gt; &lt;/div&gt; &lt;/undefined&gt; &lt;/undefined&gt;

**Comment by brandonroberts** [comment] 2016-01-06 01:55
@PrimeObjects See https://github.com/angular/angular/issues/6222

**Comment by pkozlowski-opensource** [comment] 2016-01-13 16:20
@PrimeObjects your link to a plunker is not valid, please provide adequate reproduce scenario

**Comment by PrimeObjects** [comment] 2016-01-13 16:24
I tried just now, it worked to me. please try to put a very simple router-outlet and you should see undefined element in Chrome debug.

**Comment by mindarelus** [comment] 2016-07-26 06:07
I have the same issue.

**Comment by vicb** [comment] 2016-07-26 14:00
For now you should add a selector to you component to create a tag. I'm closing this because there is an other issue tracking this

**Closed by vicb** 2016-07-26 14:00 UTC

**Comment by chenyingyin** [comment] 2016-12-01 05:29
![default](https://cloud.githubusercontent.com/assets/24284270/20782714/60f05eaa-b7c9-11e6-9006-f7beb8bef322.png)
