### ISSUE TITLE
HttpErrorResponse error field is a string when response is json.

### ISSUE THREAD

**Issue by Alan502** [angular/angular#19664] opened 2017-10-11 16:28 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When Angular's HttpClient http.get() gets a json-formatted error response, the error field in the HttpErrorResponse returned is a string.

## Expected behavior

When a json formatted error is returned by HttpClient's http.get(), the error field on HttpErrorResponse should be a json.

Angular version: 4.4.4

Browser:
- [x ] Chrome (desktop) version 61.0.3163.100

**Comment by trotyl** [comment] 2017-10-11 16:35
Duplicate of https://github.com/angular/angular/issues/19103.

**Comment by tbosch** [comment] 2017-10-13 15:48
Closing...

**Closed by tbosch** 2017-10-13 15:48 UTC
