### ISSUE TITLE
feat(form): Apply pipe to display value of input field

### ISSUE THREAD

**Issue by JanStureNielsen** [angular/angular#13140] opened 2016-11-29 20:11 UTC
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
```

**Current behavior**
Cannot apply a pipe to the display value of an input field.

**Desired behavior**
I'd like to be able to apply a pipe to the display value of an input. Suppose I have a pipe which converts a whole number of cents into dollars and adds a dollar sign, e.g., "110" => "$1.10". As a user is typing, I'd like to apply the pipe to the displayed value while the value of the input field remains 110, i.e., only apply the pipe to the display of the field's value.

Here's a Plnkr which shows the input field and the value of the input run through the pipe. I'd like the actual displayed value in the input field to look like content below the input field.

  http://plnkr.co/edit/NgNoxQ2GTUYKmEYjnYAh?p=preview

And here's my SO question about this feature, demonstrated in Angular Material:

  http://stackoverflow.com/questions/40855106/transform-md-input-value-via-pipe

**What is the motivation / use case for changing the behavior?**
This specific scenario is a common use-case in finance-related applications but the scenario is general, date formats, etc.

**Please tell us about your environment:**

OpenSUSE 13.2 Linux, Emacs, ... N/A

* **Angular version:** 2.0.X
2.x

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
All

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
All

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment] 2016-11-29 20:13
Duplicate of https://github.com/angular/angular/issues/3009

**Comment by chuckjaz** [comment] 2016-11-29 21:46
Try replacing your input element with:

```html
<input [(ngModel)]='price'>
```

**Comment by JanStureNielsen** [comment] 2016-11-29 21:50
Sure, @chuckjaz, but that does not address the issue...

**Comment by chuckjaz** [comment] 2016-11-29 23:00
Sorry about that!

**Comment by webia1** [comment] 2016-12-20 14:07
Could[ that ](http://stackoverflow.com/questions/39642882/using-pipes-within-ngmodel-on-input-elements-in-angular2-view)help you?

**Comment by kara** [comment] 2017-02-17 23:09
@JanStureNielsen We are definitely planning to add support for cases like this, but we are tracking in the main issue, #3009, so I'm going to close this one as a duplicate.

**Closed by kara** 2017-02-17 23:09 UTC
Labels: comp: forms
