### ISSUE TITLE
[host] binding works differently in ngUpgrade app

### ISSUE THREAD

**Issue by hisham** [angular/angular#13694] opened 2016-12-28 23:11 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

See https://github.com/valor-software/ng2-bootstrap/issues/1398. this._ngZone.onStable is firing before it actually becomes stable. 

**Expected behavior**

ngUpgrade apps should work same for this use case as pure Angular 2 apps with no hack needed. 

**Minimal reproduction of the problem with instructions**

See repo that repros this at https://github.com/hisham/ng1-ng2-modal.git

**What is the motivation / use case for changing the behavior?**

Using tooltip module from ng2-bootstrap in hybrid app

**Please tell us about your environment:**

* **Angular version:** 2.0.X

2.4

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

All browsers 

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 

* **Node (for AoT issues):** `node --version` =   
6.4.0

**Comment by gkalpak** [comment] 2017-04-18 18:58
The provided reporduction uses the old, dynamic version of `ngUpgrade`. Is this still an issue on the latest version of `upgrade/static`?

**Comment by gkalpak** [comment] 2017-12-13 12:39
I am going to close this, because it is old, didn't here back from the OP and the reproduction uses the now deprecated dynamic version of ngUpgrade. If there is still something you think should be fixed in the static version of ngUpgrade, please open a new issue.

**Closed by gkalpak** 2017-12-13 12:39 UTC
Labels: comp: upgrade/dynamic
