### ISSUE TITLE
How to prevent IE11/10/9 from triggering automatically input validation?

### ISSUE THREAD

**Issue by finalxcode** [angular/angular#15299] opened 2017-03-20 09:28 UTC
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

`<md-dialog-content>`
    `<form [formGroup]="privilegeForm">`
        `<md-input-container class="account-login-material" style="width: 100%">`
            `<input mdInput required placeholder="Name" formControlName="name" [(ngModel)]="name" maxlength="16">`
            `<md-hint align="start" *ngIf="privilegeForm.name.valid || privilegeForm.name.pristine">Name is required</md-hint>`
            `<md-hint align="end">{{name?.length}} / 16</md-hint>`
        `</md-input-container>`
    `</form>`
`</md-dialog-content>`

when i use `placeholder="Name"` in IE11/10/9, I get the message "Name is required" is diplayed as soon as the field gets focus.

**Expected behavior**

i expect that there is a method to prevent IE11/10/9 from triggering automatically input validation?

**Minimal reproduction of the problem with instructions**

none

**What is the motivation / use case for changing the behavior?**

when this input field is pristine and valid, the message "required" should not be displayed

**Please tell us about your environment:**

@angular/cli: 1.0.0-beta.31
node: 6.9.4
os: win32 x64

* **Angular version:** 2.0.X

@angular/common: 2.4.8
@angular/compiler: 2.4.8
@angular/core: 2.4.8
@angular/forms: 2.4.8
@angular/http: 2.4.8
@angular/material: 2.0.0-beta.2
@angular/platform-browser: 2.4.8
@angular/platform-browser-dynamic: 2.4.8
@angular/router: 3.4.8
@angular/cli: 1.0.0-beta.31
@angular/compiler-cli: 2.4.8

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 IE11/10/9

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
 ES5

* **Node (for AoT issues):** `node --version` =   
node: 6.9.4

**Comment by DzmitryShylovich** [comment] 2017-03-20 09:30
https://www.w3schools.com/tags/att_form_novalidate.asp

**Comment by finalxcode** [comment] 2017-03-20 09:38
@DzmitryShylovich but i want this form validate this field when submit, because this field is pristine before the user input, i wish `required` message not display in ie 11?

**Comment by DzmitryShylovich** [comment] 2017-03-20 09:59
can you reproduce in plunkr? doesn't look like it related to angular

**Comment by DzmitryShylovich** [comment] 2017-03-20 13:01
@finalxcode https://github.com/angular/angular/issues/14527#issuecomment-280726674 ?

**Comment by finalxcode** [comment] 2017-03-21 05:35
@DzmitryShylovich thanks, but i validate every field when field value or status change, then display error message, i don't want to display error message after submit form.

**Comment by DzmitryShylovich** [comment] 2017-03-21 07:33
@finalxcode ok, so what is the angular bug here? :)

**Comment by finalxcode** [comment] 2017-03-21 10:57
@DzmitryShylovich , not angular bug, I will produce a plunkr for you

**Comment by DzmitryShylovich** [comment] 2017-03-22 08:39
> not angular bug

This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
cc @pkozlowski-opensource

**Comment by GZidar** [comment] 2017-04-13 01:58
This may not be a bug in Angular but it is something that perhaps should be fixed by Angular so that workarounds are not needed in all client applications. A similar issue was discussed (and supposedly fixed) in Angular JS.

https://github.com/angular/angular.js/issues/2614

Put simply the input form field is marked as dirty immediately upon receiving focus rather than waiting for the user to enter a value.

The page loads, user tabs onto an input and the control is immediately set to dirty. In Edge, Chrome, and Firefox this is not the case. This difference of behaviour is the "bug".

**Comment by muziekklas** [comment] 2017-04-14 09:54
Any update on this issue? Is there a similar patch as in AngularJS?

**Comment by albinocordeiro** [comment] 2017-05-31 18:29
I'm facing the issue now May 31st. Any update on this?

**Comment by fedu** [comment] 2017-08-24 20:28
It seems this triggers, when the form is focused by browser or some other native javascript code. Angular triggers the validation for other form fields too. So I would assume this actually is a Angular IE11 bug.

**Comment by zmad5306** [comment] 2017-12-11 13:28
This may be the root cause: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/101220/

**Comment by tashoecraft** [comment] 2018-01-03 20:51
Happening to me as well. While it seems to be an IE issue, is there any change of this being covered by Angular or is it going to require us to handle the annoying logic?

**Comment by 1stein** [comment] 2018-01-10 15:24
Fixed it for myself with this custom directive

	import { Directive, ElementRef } from '@angular/core';
	import { NgControl } from '@angular/forms';

	const ieRegex = /(msie|trident|edge)/i;

	@Directive({
		selector: 'input[type="text"]',
		host: {
			'(input)': 'onInput()',
			'(focus)': 'onFocus()'
		}
	})
	export class InputIeFixDirective {
		private setPristine: boolean = false;

		constructor(private el: ElementRef, private control: NgControl) {
		}

		private get isIe(): boolean {
			return ieRegex.test(window.navigator.userAgent);
		}

		onInput() {
			if (this.setPristine) {
				this.control.control.markAsPristine();
				this.setPristine = false;
			}
		}

		onFocus() {
			this.setPristine = this.isIe && this.control.pristine;
		}
	}

**Comment by merken** [comment] 2018-06-19 08:07
Somewhat related, we fixed it by delaying the registration for the 'change' and 'input' events until after the view inits.

https://gist.github.com/merken/c994ccecbd5f1f03798c0d70b0605393#file-compcomponent-ts

**Comment by williamchristophercooley** [comment] 2018-07-20 18:14
There are many people trying to hack a solution for this, but the issue is still open.

https://stackoverflow.com/questions/38054024/angular-2-how-to-prevent-ie-from-triggering-automatically-input-validation

**Comment by dylhunn** [comment] 2021-08-16 20:46
My understanding is that this only affects IE, which has been deprecated for the next major version.

**Closed by dylhunn** 2021-08-16 20:46 UTC
Labels: type: bug/fix, freq2: medium, comp: forms, state: confirmed, browser: ie 9 or 10, browser: ie 11, triage #1, P4
