### ISSUE TITLE
(AOT): Angular does not invoke lifecycle listeners if typescript mixins are used

### ISSUE THREAD

**Issue by kemsky** [angular/angular#19145] opened 2017-09-11 16:54 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Assume we have base class, mixin and component class:
```typescript
class Base implements OnInit {
    constructor(){}
    ngOnInit():void {}
}

type Constructor<T> = new(...args: any[]) => T;

function Tagged<T extends Constructor<{}>>(base: T) {
    return class extends base {
        value: string;
        constructor(...args: any[]) {
            super(...args);
            this.value= "test";
        }
    }
}

export class Component extends Tagged(Base) {
    public item:any;

    constructor()  {
        super();
    }
}
```

Component's `ngOnInit` listener will not be called in AOT.

Workaround:
```typescript
export class Component extends Tagged(Base) {
    public item:any;

    constructor() {
        super();
    }

   ngOnInit():void {
         super.ngOnInit();
   }
}
```

## Expected behavior
`ngOnInit` should be called.

## Environment

<pre><code>
Angular version: 4.4.0-RC.0
TypeScript: 2.4.2

**Comment by alexeagle** [comment] 2017-09-16 05:49
@chuckjaz looks like the static reflector doesn't understand some part of the mixin syntax (maybe `return class extends base`) to grasp the type inheritance

**Comment by chuckjaz** [comment] 2017-10-27 21:24
The issue is that that static reflector does not use the type checker of TypeScript. Currently, if there is an expression in the `extends` clause we ignore it. This means we have no idea that the base class implements `onInit` nor an easy way to calculate it as it would require us to ask the type-checker.

We avoid using the type-checker because we need to be able to produce factory functions before type checker or we would have to do two full type-checks.

We should consider recognizing the pattern `function f<T extends Constructor<{}>>(base: T) {` as meaning we should just ignore the `f` and treat its parameter as the base class.

However, this would mean that we would not catch things like,

```ts
function CoolInitMixin<T extends Constructor<{}>>(base: T) {
    return class extends base {
        constructor(...args: any[]) {
            super(...args);
        }
        ngOnInit() {
         // something cool.
       }
    }
}
```

**Comment by HideDev** [comment] 2017-10-31 12:53
+1

**Comment by chaosmonster** [comment] 2018-02-12 08:38
Just leave this here as @trotyl made me aware of this issue.
I think this is what alex thought about and it won't work in aot. Do you think this can be fixed?

https://gist.github.com/chaosmonster/f2576bbd1bc9a50282a2b3b492195b29

**Comment by trotyl** [comment] 2018-02-12 08:57
I guess this tracker is only for life-cycle hooks problem, what I meant is the mixin pattern not generally supported is AOT, but some basic functionality may be able to work already. 

I'd suggest to raise separated issues when founding other concrete problems. 😃

**Comment by AndriiDidkivsky** [comment] 2018-07-25 05:31
Any updates for this? Well-supported mixins would be a powerful feature.

**Comment by trotyl** [comment] 2018-07-25 05:34
This is already fixed by Ivy. But not likely to be fixed on current view engine.

**Comment by redplane** [comment] 2019-06-21 08:06
How about angular 8 ? I'm facing with the same issue on angular 6 and thinking about moving to angular 8. For now, I have to copy everything again and again

**Comment by mlc-mlapis** [comment] 2019-06-21 08:13
@redplane ... as @trolyl mentioned the Ivy. You can try it in Angular 8 if you enable Ivy.

**Comment by kemsky** [comment] 2019-06-21 08:13
Currently inheritance is broken in Ivy, so would not expect much.

**Comment by 0x1000000** [comment] 2020-02-10 18:53
Angular 9 has been released but  the issue is still there

**Comment by JoostK** [comment] 2021-07-15 23:41
Closing as fixed in Ivy.

**Closed by JoostK** 2021-07-15 23:41 UTC
Labels: comp: core, core: lifecycle hooks, feature, under consideration, votes required

**Comment by karptonite** [comment] 2021-07-16 07:55
@JoostK Does that mean that the mixin pattern is actually supported now in Ivy? For component life cycles? Do you happen to have a references to a commit or docs about this?

**Comment by JoostK** [comment] 2021-07-16 18:55
@karptonite Ivy merges lifecycle hooks across an inheritance chain at runtime, so it is constrained by AOT limitations (provided that the base class is decorated with e.g. `@Directive()`, as otherwise the lifecycle hooks are not visible to the runtime).

That said, template type checking _is_ constrained by static analysis and having a dynamic base class does not currently play well with input/output bindings. We also don't test these kinds of patterns, so your mileage may vary (from this perspective; no, mixins are not really supported; only statically known facts are supported and using complex expressions in the inheritance clause may fail to be statically evaluated). If you do run into particular usages that you think should work, please open a new issue.

**Comment by karptonite** [comment] 2021-07-16 19:37
@JoostK thanks, I was only asking for clarification because you closed the issue as “fixed in Ivy”. I’m not actually using mixins because they were previously unsupported.
