### ISSUE TITLE
NgModel works incorrectly when using onPush ChangeDetection strategy

### ISSUE THREAD

**Issue by kkovalevskiy** [angular/angular#10816] opened 2016-08-15 14:01 UTC
**I'm submitting a ...** 

```
[x] bug report - related issue https://github.com/angular/angular/issues/10148, but it's about testing.
```

**Current behavior**
I have two components: the first one is a simple child component with some input and basic support of `[ngModel]` directive via `ControlValueAccesor` interface. The second one is a parent component has `onPush` change detection strategy and populates a value into child component via `[ngModel]` directive (right after that it's marked for changes via `ChangeDetectorRef` class). When `[ngModel]` is updated child component still displays an old value in the template while the component object has  actual value in target property.

As I can see NgModel directive updates target component asynchronously - https://github.com/angular/angular/blob/2.0.0/modules/%40angular/forms/src/directives/ng_model.ts#L191-L193 so the following scenario occurs
1. Change detection executes for parent component.
2. Change detection updates [ngModel] value
3. [ngModel] schedules async task that updates child component
4. Change detection executes for child component
5. Actual value arrives in child component.

**Expected/desired behavior**
Change detection should work with already updated component to ensure that new value has been populated into UI.

So it looks like that last two steps should be swapped (or even better - [ngModel] can update child component synchronously).

**Reproduction of the problem**
Here is a tiny example with the issue. I'm expecting here that right after 2 seconds App Component should display "new value".
~~http://plnkr.co/edit/IabIsT3323GpZmQSPd4z?p=preview~~
new example can be found here http://plnkr.co/edit/KowgH96EtDbVJao13Hz5?p=preview, thanks to @andreialecu 

if I use the following markup in the example above 
`<my-child [value]="value"></my-child>`
instead of 
`<my-child [ngModel]="value"></my-child>`
all work as expected

**Please tell us about your environment:**
- **Angular version:** 2.0.0-rc.05
- **Browser:** [ Chrome 52] 
- **Language:** [TypeScript 1.8 | ES5]

**Comment by kara** [comment] 2016-10-17 23:42
Related: https://github.com/angular/angular/issues/9782

**Comment by andreialecu** [comment] 2016-11-02 16:02
Updated plunker to work with Angular 2.0 final: http://plnkr.co/edit/KowgH96EtDbVJao13Hz5?p=preview Old one wasn't working any more.

This seems pretty severe, I cannot use `ngModel` because of this and have to resort to avoiding ControlValueAccesor and using separate explicit `@Input` and `@Output` properties with a different name than `ngModel`.

**Comment by bennadel** [comment] 2016-11-04 12:36
I would also add explicitly that the `ngOnChanges()` life-cycle event method should be fired. I didn't see that mentioned in this version of the ticket.

**Comment by ilianiv** [comment] 2016-11-14 13:28
Have the same issue. Cannot use onPush in my components because I use 3rd party components (value accessors) as child components that cannot be pinged outside to markForCheck() themselves and trigger change detection.

**Comment by eckdanny** [comment] 2016-12-19 16:39
I _think_ I can get around this by subscribing to `statusChanges` outside the validator:

```js
// When you go from PENDING to anything else :p
this.myFormCtrl.statusChanges
  .bufferCount(2, 1)
  .map(states => states[0])
  .filter(prevState => prevState === 'PENDING')
  .subscribe(status => {
    this._ref.markForCheck();
  });
```

**Comment by andreialecu** [comment] 2017-01-14 00:21
This continues to be a severe problem for my project needing ugly workarounds.

Been reported in August, still no fix in sight? @kara, might taking a look? This fiddle clearly shows the issue: http://plnkr.co/edit/KowgH96EtDbVJao13Hz5?p=preview

**Comment by kkovalevskiy** [comment] 2017-01-14 05:54
@kara could you clarify pls, why `ngModel` should update target controls asynchronously? (https://github.com/angular/angular/blob/2.0.0/modules/%40angular/forms/src/directives/ng_model.ts#L191-L193). If they will be updated synchronously it will resolve the issue.

**Comment by DzmitryShylovich** [comment] 2017-01-14 07:11
@kkovalevskiy 
> could you clarify pls, why ngModel should update target controls asynchronously? 

```
`ngModel` forces an additional change detection run when its inputs change:
 E.g.:
 
 <div>{{myModel.valid}}</div>
 <input [(ngModel)]="myValue" #myModel="ngModel">
 
 I.e. `ngModel` can export itself on the element and then be used in the template.
 Normally, this would result in expressions before the `input` that use the exported directive
 to have and old value as they have been
 dirty checked before. As this is a very common case for `ngModel`, we added this second change
 detection run.
```
but we can change it to `ChangeDeetectorRef.deetectChnages` which will make it sync.

**Comment by kkovalevskiy** [comment] 2017-01-16 05:20
@DzmitryShylovich thanks for your answer, looks like I got it, but I still have several questions.

1. `ngModel forces an additional change detection run when its inputs change:` probably I didn't understand how it's implemented, but I don't see any code in `ng_model.ts` that forces second change detection. All that I see is just the following calling chain `ngOnChanges -> _updateValue -> <async call> this.control.setValue`
2. Also I see a note in the comment to `resolvedPromise` - `this is a general problem when using exportAs for directives!` Probably the original issue is that `exportAs` and `ngModel` don't play well with unidirectinal dataflow? Maybe in this example we should use some `@Output` property instead of `<div>{{myModel.valid}}</div>`? As I understand conception of unidirectional dataflow, myModel.value is somekind of output property.

**Comment by freedonaab** [comment] 2017-03-12 17:11
Any update on this issue? or a temporary workaround? I need this for my project too.
I have a parent component (with `OnPush` strategy & `ControlValueAccessor`) that wraps a third party component (with default strategy & `ControlValueAccessor`). 
When the parent component changes the value, the child component is never updated, unless it receives an user event (ie: hover, click).

**Comment by DzmitryShylovich** [comment] 2017-03-12 17:41
> Any update on this issue?

Doesn't look like it will be fixed in the near future.

> temporary workaround?

Don't use `OnPush` with form components

**Comment by kkovalevskiy** [comment] 2017-03-13 14:25
@freedonaab 
> I have a parent component (with OnPush strategy & ControlValueAccessor) that wraps a third party component (with default strategy & ControlValueAccessor).

Not sure that your issue is related with this one. I'd say that in your case default change detection strategy of child component won't be working automatically if parent component has OnPush change detection strategy. You have to subscribe on events (or observables) of child component and run change detection manually via ChangeDetectorRef in parent component. This happens due to the fact that angular doesn't track child components of OnPush component (see also https://vsavkin.com/change-detection-in-angular-2-4f216b855d4c#.jwoetznkz)

This issue is just about the fact that embedded forms directives doesn't work with OnPush components and looks like they violate unidirectional dataflow principle - https://vsavkin.com/two-phases-of-angular-2-applications-fda2517604be#.d30zyylv1. This also leads to necessity to run change detection  several times, until component don't become "stable". Interesting fact that one core part of angular framework doesn't follow its core principles and looks like these directives are working only due to the fact that angular runs change detection _very often_, even on mouse move.

**Comment by Itrulia** [comment] 2017-03-21 17:05
@DzmitryShylovich so my whole application is not allowed to? Because it isn't working if parent has onPush enabled.

**Comment by bakasmarius** [comment] 2017-06-09 07:58
> Doesn't look like it will be fixed in the near future.

May we ask why? It's kind of important issue for lots of people...

> Don't use OnPush with form components

What if all the components in my app use forms? Should I just forget about the OnPush and use the Default strategy which uses A LOT of CPU on bigger SPAs and results in constant massive lag? :/

**Comment by christianacca** [comment] 2017-06-10 14:17
If you can modify the source code of the component that implements the `ControlValueAccessor`, a workaround is to call `markForCheck` eg:

```ts
    public writeValue(value: any): void {
        this.value = value;
        this.cdf.markForCheck();
    }
```
Here's the plunker from the original poster, using this technique: http://plnkr.co/edit/fy0gZdT5qpBZ3nKVOAzo?p=preview

**Comment by tytskyi** [comment] 2017-06-10 17:27
`onPush` strategy is not meant to be used with component that has its own state. But for the component that receives data from outside. Form control **does** have internal state.

Otherwise you need to work manually with `ChangeDetectorRef` as @christianacca shows, which is not convenient way.

**Comment by xindexer** [comment] 2017-06-11 16:02
This worked for me:

`ngAfterInit() {
    this.changeDectorRef.markForCheck()
}`

**Comment by kmolerov** [comment] 2017-07-13 09:02
I think the angular architecture does not permit this. If proper way to fix the issue is to force the component library author to make it work with OnPush change detection, maybe there should be a guideline for them.
Currently I am unable to make all my form components work with OnPush.

Also it will be better in future to remove the "default" change detection all together. This will force everyone to use OnPush, which will result in better applications.

**Comment by valdestrijus** [comment] 2017-09-12 06:49
This issue is really big flaw of Angular IMO. OnPush strategy helps us build fully controllable, predictable and unidirectional applications with great performance. But various third parties which are using two-way data binding is forcing us to workaround child components by manually detecting changes.

**Comment by m-przybylski** [comment] 2018-02-21 19:08
I use Firebase as my backend server and the issue I'm facing is the following:
1. Component ChangeDetectionStrategy is set to OnPush
2. There is Reactive form with async validator 
```  
private ValidateSKU: AsyncValidatorFn = (control: AbstractControl) => {
    return this.productService.getProductBySKU(control.value).pipe(
      take(1),
      map((products: Product[]) => {
        console.log(products.length > 0 ? { skuExists: true } : null)
        return products.length > 0 ? { skuExists: true } : null
      }),
    )
  }
```
3. My template binds errors in following way:
```
      <div class='ui-input-error' *ngIf='productSku.errors'>
        <div *ngIf='productSku.errors.skuExists'>SKU already exists</div>
        <div *ngIf='productSku.errors.required'>SKU is required</div>
      </div>
```
Whenever validator is fired it does not trigger change detection on my component. 

I found workaround that with following code:
```
  private ValidateSKU: AsyncValidatorFn = (control: AbstractControl) => {
    return this.productService.getProductBySKU(control.value).pipe(
      take(1),
      map((products: Product[]) => {
        requestAnimationFrame(() => {
          this.cdr.markForCheck()
        })
        console.log(products.length > 0 ? { skuExists: true } : null)
        return products.length > 0 ? { skuExists: true } : null
      }),
    )
  }
```
If someone have any better idea please let me know.

**Comment by mlc-mlapis** [comment] 2018-02-21 19:17
@m-przybylski ... a bit lost ... why do you expect that CD should run if the component is on `OnPush`? Do you have a simple demo reproduction? Because it is not related to Firebase you can simulate it on http://stackblitz.com.

> Whenever validator is fired it does not trigger change detection on my component.

**Comment by m-przybylski** [comment] 2018-02-21 21:03
@mlc-mlapis, so sorry if I confused you. I have prepared sample app [here](https://stackblitz.com/edit/angular-ck1fkx?file=app%2Fapp.component.ts)
all inputs are required, all inputs have async validator to check if value is a (Promise resolves after 1 second). When component uses `OnPush` CD is triggered when you interact with template (either you click on it or loose focus from input). Try to use first input wait for timeout and you will notice that nothing happens, second input works as a charm. 
Maybe I'm confused and do something wrong, let me know.

**Comment by mlc-mlapis** [comment] 2018-02-21 21:38
@m-przybylski ... I apologize that I don't have enough time right now to look more deeply but just one notice immediately ... `OnPush` has only sense if we are talking about `parent` / `child` components composition ... when the child has `changeDetection: ChangeDetectionStrategy.OnPush` setting and the parent is passing an object as an input to the child ... and here is the crux of the concept `only when the parent passes the object with a new reference ... the child's CD should run`. But your demo has all code in `AppComponent` ... so `OnPush` is irrelevant here.

**Comment by m-przybylski** [comment] 2018-02-21 21:51
@mlc-mlapis totally agree with you it does not make sence to set onpush if you use only one component, but this is just an example. What I try to say is that there is no place to trigger CD on component when you use async validators in forms and OnPush strategy.

**Comment by mlc-mlapis** [comment] 2018-02-21 22:01
@m-przybylski ... I would prefer to not talk about `OnPush` at all in that case ... because it's not really related ... and it'll always be just confusing. Your case is just about async-validators and nothing more.

**Comment by m-przybylski** [comment] 2018-02-22 05:44
@mlc-mlapis sorry, but you are wrong. Change detection strategy to default and it works as expected...

**Comment by mlc-mlapis** [comment] 2018-02-22 06:53
@m-przybylski ... oh, interesting ... I'll look more deeply ... probably some hidden unexpected relation.

**Comment by dirkluijk** [comment] 2018-03-01 21:29
Wow, this really surprises me! My first thought: shouldn't any directive (like ngModel) with bindings at least trigger changeDetection on its host component?

Of course this would only solve it for components used in template-driven forms (with `ngModel`), because with reactive forms no binding would change...

**Comment by agarbund** [comment] 2018-10-26 07:50
@m-przybylski I know it's 8 months later and you've probably already fixed the problem one way or another, but maybe someone else will come here with the similar issue so I wanted to explain what's happening.

Problem is that with `OnPush` change detection changes in `control.errors` done by async validators aren't spotted, so you can't just do `*ngIf="control.errors"`. Solution is to wrap errors into Observable and use `async` pipe.

In component you'd need to do sth like this:
```
errors$ = control.statusChanges.pipe(
  startWith(null),
  map(() => control.errors)
);
```

and in template:
```
<div *ngIf="errors$ | async as errors">
  ... display errors ...
</div>
```
`startWith` is needed to trigger an initial validation.

See working example here: https://stackblitz.com/edit/angular-nmrtjx

**Comment by CorporateDog** [comment] 2018-11-03 19:40
Here's my cheesy work-around...

Write a Directive with the following code:

```
@Directive({
    selector: '[onPushNgModelComponent]'
})
export class OnPushNgModelDirective implements OnInit {

    private cdr: ChangeDetectorRef;

    constructor(private injector: Injector, private ngZone: NgZone) { }

    public manuallyDetectChanges() {
        this.ngZone.runOutsideAngular(() => {
            requestAnimationFrame(() => {
                if (this.cdr) { this.cdr.detectChanges(); }
            });
        });
    }

    ngOnInit() {
        this.cdr = this.injector.get<ChangeDetectorRef>(ChangeDetectorRef as any) as ChangeDetectorRef;
    }
}
```

Attach the directive to your third-party components that need it, and then when you would normally trigger a 'detectChanges' from the parent component, cycle through your view children that have this directive, and run the 'manuallyDetectChanges' function.

**Comment by vvolodin** [comment] 2020-07-03 12:32
4 years and still going nowhere with this...

**Comment by MarkoSulamagi** [comment] 2021-03-22 11:23
Bumping this topic. I just spent hours debugging why change detection isn't working until I found this thread :/

**Comment by DoanVanThuong** [comment] 2021-04-16 09:57
I spent half a day to find solution, and now, I found this issue in github and it's still opening. hoho

**Comment by mlc-mlapis** [comment] 2021-04-16 10:18
@DoanVanThuong This is a simple example of `OnPush` effect on CD:
https://stackblitz.com/edit/angular-parent-child-onpush?file=src%2Fapp%2Fparent%2Fparent.component.ts

**Comment by IgorKurkov** [comment] 2021-04-20 10:31
any updates? how to trigger `ngForm.statusChanges` when `onSubmit` is fired? I can't tell child components about form submitting that they are invalid (empty) when onPush is enabled.

**Closed** 2022-02-01 17:26 UTC
Labels: type: bug/fix, freq2: medium, comp: forms, state: confirmed, triage #1, forms: ngModel, forms: change detection, P3

**Comment by chabb** [comment] 2022-02-04 10:54
I think #11563 is still an issue.  Here : https://stackblitz.com/edit/angular-6msgu9?file=src%2Fapp%2Fapp.component.ts
When you click on the change button, the value is correctly updated, but the ng-invalid class is still present.
Is it expected ?

**Comment by AndrewKushnir** [comment] 2022-02-04 20:08
@chabb could you please create a new ticket to describe what the problem is (what's the expected vs actual behavior that you see)? Thank you.

**Comment by chabb** [comment] 2022-02-05 07:35
@AndrewKushnir  I've opened #44976
