### ISSUE TITLE
5.0.0 rc.1: AOT compiler creates module factories outside oudir

### ISSUE THREAD

**Issue by kemsky** [angular/angular#19597] opened 2017-10-06 15:31 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
`ngc` creates folders for each angular module i.e. router, forms, common right in the project root instead of `outDir`.
![screenshot](https://user-images.githubusercontent.com/3826972/31285594-660427f2-aac4-11e7-97ae-a2031bb00c72.png)

## Expected behavior
Should create files in `outDir`  or not create at all.

## Environment

<pre><code>
Angular version: 5.0.0 rc1

 
For Tooling issues:
- Node version: 8.4.0

- Platform:   Windows
</code></pre>

**Comment by ocombe** [comment] 2017-10-06 16:01
Thanks for reporting this issue. However this issue is a duplicate of an existing issue #19543. Please subscribe to that issue for future updates.

**Closed** 2017-10-06 16:02 UTC
