### ISSUE TITLE
Angular 9 Upgrade updates to tsconfig.app.json are undocumented.

### ISSUE THREAD

**Issue by devin5885** [angular/angular#37168] opened 2020-05-18 04:01 UTC
# 📚 Docs or angular.io bug report

### Description

The Angular 9 upgrade updated the tsconfig.app.json and tsconfig-es5.app.json as follows (the project uses the differential loading workaround from the angular 8 upgrade to allow ng serve to support IE):

```
tsconfig.app.json
Old:
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc/app",
    "types": []
  },
  "exclude": [
    "src/test.ts",
    "**/*.spec.ts"
  ]
}
New:
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc/app",
    "types": []
  },
  "files": [
    "main.ts",
    "polyfills.ts"
  ],
  "include": [
    "src/**/*.d.ts"
  ]
}
```

(i.e.) 'exclude' was removed and 'files' and 'include' were added.

```
tsconfig-es5.app.json
Old:
{
    "extends": "./tsconfig.app.json",
    "compilerOptions": {
        "target": "es5"
     }
}
New:
{
    "extends": "./tsconfig.app.json",
    "compilerOptions": {
        "target": "es5"
     }
   ,  "include": [
    "src/**/*.d.ts"
  ]
}
```

Checking the tsconfig.app.json for a default CLI Angular 8 project upgraded to 9 the file is:

```
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "outDir": "./out-tsc/app",
    "types": []
  },
  "files": [
    "src/main.ts",
    "src/polyfills.ts"
  ],
  "include": [
    "src/**/*.ts"
  ],
  "exclude": [
    "src/test.ts",
    "src/**/*.spec.ts"
  ]
}
```

This seems to be the only information about this in the upgrade documentation:
We have updated the tsconfig.app.json to limit the files compiled. If you rely on other files being included in the compilation, such as a typings.d.ts file, you need to manually add it to the compilation.

I think the addition of the include statement may be related to:
https://github.com/angular/angular-cli/issues/16923.

And the addition of files may be related to:
https://github.com/angular/angular-cli/issues/17066

Why were these changes made?
Why was the 'exclude' statement removed?
Why are the changes different for the es5 file?

Please update the upgrade documentation to include information about why these the upgrader is makes these changes.

### What's the affected URL?**
https://update.angular.io/#8.0:9.0l3
https://angular.io/guide/updating-to-version-9

**Comment by kapunahelewong** [comment] 2020-05-28 20:45
@devin5885, thanks for all the helpful info and questions! They will help guide the docs team.

Status: Docs team will need an engineer to help answer questions above.

**Comment by roopeshreddy** [comment] 2020-08-14 19:01
Any luck on this item?

We've mock files along with the .spec files. We're in assumption that it compiles only the code that kicks off from main.ts file.

if we've documentation around it, that would be helpful.

**Comment by roopeshreddy** [comment] 2020-08-17 13:34
I referred this question on Enterprise slack group and @mgechev confirmed me my assumption was correct! As @devin5885 explained, we may need to explicitly include the additional files to be compiled. 

IMO this change is for simplification, but unfortunately, it's not documented anywhere!

I just shared this information, so that, if anyone is looking for this, it may be helpful!

**Comment by tdkehoe** [comment] 2020-10-27 15:51
What does the "d" mean in "src/**/*.d.ts"? It includes files that don't have a "d" and excludes other files. And what's the difference between "files" and "include"? Which files or paths go where?

**Comment by argelj289** [comment] 2020-11-23 06:53
I'm having the same issue here

is there any fix for this?

**Comment by AlphaJuliettOmega** [comment] 2020-11-23 13:33
What @tdkehoe said, What is the difference between 'files' and 'include'?

I don't care so much for the reason behind the change, only that I can use it to the best of my ability.

**Comment by sander1095** [comment] 2021-01-29 14:34
Any update :)?

**Comment by mgechev** [comment] 2021-01-30 01:54
Hi everyone, over the past few releases we transformed `tsconfig.json` a few times for different reasons. For example, we disabled differential loading by default and we're now only shipping ES2015 by default. To ensure proper auto-completion support in editors and IDEs we changed from solution-style project to a different format, etc.

Ideally, you should be treating such configuration as a black box, but I do agree that you have a legit use case to add additional files to the compilation. I'll open an issue in our update guide and we'll follow up with update steps as soon as we can.

>What @tdkehoe said, What is the difference between 'files' and 'include'?

I'd recommend you checking the TypeScript [docs](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html) on tsconfig.

**Closed by mgechev** 2021-01-30 01:54 UTC
Labels: P4, comp: docs, feature, freq1: low, state: needs eng input, subtype: docs-completeness, triage #1
