### ISSUE TITLE
docs-infra: make API examples Monospace font

### ISSUE THREAD

**Issue by HymanZHAN** [angular/angular#52612] opened 2023-11-08 06:15 UTC
### Describe the problem that you experienced

I expect to see a monospace font rather than "Inter" for code/API.

### Enter the URL of the topic with the problem

https://angular.dev/api/forms/NgModel

### Describe what you were looking for in the documentation

API documentation.

### Describe what you want to experience that would fix the problem

Stick to monospace font for all code samples.

### Add a screenshot if that helps illustrate the problem

![image](https://github.com/angular/angular/assets/26806995/490196fe-07f8-401a-bbc8-bd683b478d11)

**Comment by twerske** [comment] 2023-11-08 23:15
This is a good point - I believe the font is set to be monospace and due to making it a button to hover and scroll through methods, the CSS override of Inter is accidentally being applied.

If a community member is interested, we would accept this change as a contribution!

As a quick reminder, we are still in the process of open sourcing the repo, so the app is not currently buildable. I am marking this as `good first issue` but please check the `adev/` folder's README for updates when Angular.dev is fully open sourced and ready for contributions!

**Comment by amirhosseinfaraji** [comment] 2023-11-17 00:09
@twerske The issue is in the `_button. mixin ` , buttons have the `font-family: var(--inter-font)` property that affects all of the buttons. also, in the `api-reference-details-page.component.scss` we have a specific selector for `buttons` with `hljs-ln-line` class. if we add a `var(--code-font)` variable to these buttons the issue will be fix.  if it's ok I can create a PR for this issue.

**Comment by JeanMeche** [comment] 2023-11-17 00:13
@amirhosseinfaraji  Wdyt of having the style set with `code button { ... }` so we would't rely on the hljs classes ?

**Comment by amirhosseinfaraji** [comment] 2023-11-17 00:43
@JeanMeche Actually we can use `code button` selector. but now `.adev-reference-api-tab>.docs-code button.hljs-ln-line` selector has some properties like `font-weight` and `text-align`. so I think it would be better that we add to this selector. but both selectors fix the issue

**Closed** 2024-03-29 23:46 UTC
Labels: help wanted, good first issue, P3, area: adev, area: adev-infra
