### ISSUE TITLE
ng serve and ng build is very slow

### ISSUE THREAD

**Issue by guehmann** [angular/angular#42100] opened 2021-05-14 17:52 UTC
Updated my environment from v11 to v12.

Now everything is very slow. Even recompiling simple text changes take much time.

Deploy to production is extreme slow. (IIS via Visual Studio 2019)

I'm using micro-repo nrwl with the nx command, but even with normal angular (ng) it's the same.

Is there something i missed to updated!
Thank you.

**Comment by JoostK** [comment] 2021-05-14 23:39
The primary investigation for v12 slowdowns is in angular/angular-cli#20792. I'm keeping this one open for visibility, but please refer to angular/angular-cli#20792 for further details.

**Comment by Xumochuan** [comment] 2021-05-21 05:25
Hi, @guehmann 
I have the same issue. How did you solve it?

**Comment by guehmann** [comment] 2021-05-21 06:29
Hi, @Xumochuan.
I updated to 12.0.1, now it seems to be faster.

**Comment by danielehrhardt** [comment] 2021-05-21 19:45
I downgraded to 11. The Build Times went from 35 Seconds to 11 Seconds. This is Insane.

**Comment by mittalshubham093gmailcom** [comment] 2021-05-22 18:12
Sometimes we load unnecessary modules at an initial time so it takes time to compile and make its bundling. Please try for lazy-loading if you are not using it.

**Comment by guehmann** [comment] 2021-05-22 18:14
@mittalshubham093gmailcom 
Thank you. Yes I'am using it but with 12.0.1 is goes really better now.

**Comment by tomaszwawrzyniakit** [comment] 2021-05-23 11:07
For  me it's still very slow. I'm noticed no changes in build time between 12 and 12.0.1

**Comment by mittalshubham093gmailcom** [comment] 2021-05-23 11:53
@tomaszwawrzyniakit  
Please ensure few points:
1) what are the libraries you are using in app.module.ts file.
 2)Ensure that you are using all the package that you imported in app.module.ts file in your project. 
3) check any any unnecessary package imported in app.module.ts file.
4) Try which package and bundle is taking more time to build and try to manage it in lazy loaded module.

**Comment by danielehrhardt** [comment] 2021-05-23 13:11
> @tomaszwawrzyniakit  
> Please ensure few points:
> 1) what are the libraries you are using in app.module.ts file.
>  2)Ensure that you are using all the package that you imported in app.module.ts file in your project. 
> 3) check any any unnecessary package imported in app.module.ts file.
> 4) Try which package and bundle is taking more time to build and try to manage it in lazy loaded module.
> 
> 
> 

Sorry, but i do not understand why this is important here. 
With version 11 there is the same amount of packages imported in the app module and it is also fast. 
So, why should we check now something that did not changed since the update?

**Comment by JoostK** [comment] 2021-05-23 15:28
> > @tomaszwawrzyniakit
> > Please ensure few points:
> > 
> > 1. what are the libraries you are using in app.module.ts file.
> >    2)Ensure that you are using all the package that you imported in app.module.ts file in your project.
> > 2. check any any unnecessary package imported in app.module.ts file.
> > 3. Try which package and bundle is taking more time to build and try to manage it in lazy loaded module.
> 
> Sorry, but i do not understand why this is important here.
> With version 11 there is the same amount of packages imported in the app module and it is also fast.
> So, why should we check now something that did not changed since the update?

Agreed. It would be helpful if you can provide profiling info in angular/angular-cli#20792; there's instructions in that thread on how to do that. We have identified ~4 things that contribute to the slowdown:

1. The usage of the new SASS module system (using `@use`) in `@angular/material` has caused severe slowdowns when still using the old-style imports (using `@import`).
    - Switching over to `@use` should result in build time improvements.
2. Type-checking became slower due to the adoption of TypeScript's incremental type-checking, which has a performance penalty for cold builds.
    - This was addressed in CLI 12.0.1 for non-watch builds.
3. In production builds, minification by Terser is no longer cached if nothing has changed.
4. I have seen source-mapping to take a lot more time in v12 compared to v11. We have not established where this comes from.

Lastly, the switch to Webpack 5 in the CLI can also have made builds a bit slower. Again, if you can help by sharing profiling sessions, or private access to your project, that would be appreciated.

**Comment by danielehrhardt** [comment] 2021-05-23 18:20
> > > @tomaszwawrzyniakit
> > > Please ensure few points:
> > > 
> > > 1. what are the libraries you are using in app.module.ts file.
> > >    2)Ensure that you are using all the package that you imported in app.module.ts file in your project.
> > > 2. check any any unnecessary package imported in app.module.ts file.
> > > 3. Try which package and bundle is taking more time to build and try to manage it in lazy loaded module.
> > 
> > 
> > Sorry, but i do not understand why this is important here.
> > With version 11 there is the same amount of packages imported in the app module and it is also fast.
> > So, why should we check now something that did not changed since the update?
> 
> Agreed. It would be helpful if you can provide profiling info in [angular/angular-cli#20792](https://github.com/angular/angular-cli/issues/20792); there's instructions in that thread on how to do that. We have identified ~4 things that contribute to the slowdown:
> 
> 1. The usage of the new SASS module system (using `@use`) in `@angular/material` has caused severe slowdowns when still using the old-style imports (using `@import`).
>    
>    * Switching over to `@use` should result in build time improvements.
> 2. Type-checking became slower due to the adoption of TypeScript's incremental type-checking, which has a performance penalty for cold builds.
>    
>    * This was addressed in CLI 12.0.1 for non-watch builds.
>    * TypeScript 4.3 should have improved here for watch builds.
> 3. In production builds, minification by Terser is no longer cached if nothing has changed.
> 4. I have seen source-mapping to take a lot more time in v12 compared to v11. We have not established where this comes from.
> 
> Lastly, the switch to Webpack 5 in the CLI can also have made builds a bit slower. Again, if you can help by sharing profiling sessions, or private access to your project, that would be appreciated.

I can give you private access to the repo. 
E-Mail daniel.ehrhardt@codext.de

Angular 12: 
Build at: 2021-05-23T18:16:48.765Z - Hash: 21b7f1ac30bd9aee364b - Time: 64778ms
Angular 11: 
Build at: 2021-05-23T18:19:30.667Z - Hash: 4aa14386e42ba8206db5 - Time: 19764ms

**Comment by mlc-mlapis** [comment] 2021-05-23 21:47
@danielehrhardt First of all, did you transform @import to @forward and @use in relation to angular/material scss styles?

**Comment by danielehrhardt** [comment] 2021-05-23 22:04
> @danielehrhardt First of all, did you transform @import to @forward and @use in relation to angular/material scss styles?

I do not use angular material

**Comment by JoostK** [comment] 2021-05-24 21:02
Another update:

Projects that have not used `ng update` to update to v12 are missing important migrations that switch some builder options to their default values in v11. Without this migration, the builder now assumes production configuration as the defaults were changed to represent production builds by default. An automatic migration that is run in `ng update @angular/cli` would set the affected options to their prior defaults, such that a project continues to behave the same. Without this migration however, builds are configured for production with the corresponding optimisations turned on, making development builds very slow.

Please use `ng update @angular/cli --migrate-only --from=11.2.0` to apply the migrations or update using `ng update @angular/core @angular/cli` when still on v11.

**Comment by mlc-mlapis** [comment] 2021-05-25 12:36
@JoostK Just a notice to:

> Projects that have not used ng update to update to v12 are missing important migrations that switch some builder options to their default values in v11. 

There are probably some cases (including our) when the standard `ng update ...`  doesn't do the default changes correctly, and it's necessary to do it manually. I don't have any reproducible case to document you exactly that case, but it can happen. It's just for info.

**Comment by BamAnas** [comment] 2021-05-25 17:44
@JoostK Works for me the build got from more then 300 000 To 19 000 ms

**Comment by diogen737** [comment] 2021-06-01 11:43
my two cents here: I'm using `@angular-builders/custom-webpack` package. Upgrading angular base packages with `ng update @angular/core@12 @angular/cli@12` doesn't really affects `ng serve` performance (average ~0.5s increase in hot reload - from ~0.9s to ~1.4s). But after updating `@angular-builders/custom-webpack` package hot reload times jump to over 10s.

**Comment by simeyla** [comment] 2021-06-02 08:09
If you're on Windows you may be running into this issue: https://github.com/angular/angular-cli/issues/20891

A second incremental build is unintentially triggered after the main `ng serve` build is ready, so it takes maybe 25% more time to complete that and be able to load the site.

**Comment by negberts** [comment] 2021-06-03 14:16
> @danielehrhardt First of all, did you transform @import to @forward and @use in relation to angular/material scss styles?

How to do that? Don't see anything about it in the update guide. When just replacing @import by @use the compiler starts to complain:

` Unknown word
You tried to parse SCSS with the standard CSS parser; try again with the postcss-scss parser [C:/GIT/PIM/Pim.Solution/Pim.PortalApp/src/app/mengsels/molenreceptkaart/moleninstelling-tab/moleninstelling-tab.component.scss:1,1]
You tried to parse SCSS with the standard CSS parser; try again with the postcss-scss parser
    at Input.error (C:\GIT\PIM\Pim.Solution\Pim.PortalApp\node_modules\postcss\lib\input.js:123:16)
    at Parser.unknownWord (C:\GIT\PIM\Pim.Solution\Pim.PortalApp\node_modules\postcss\lib\parser.js:518:22)
    at Parser.other (C:\GIT\PIM\Pim.Solution\Pim.PortalApp\node_modules\postcss\lib\parser.js:149:12)
    at Parser.parse (C:\GIT\PIM\Pim.Solution\Pim.PortalApp\node_modules\postcss\lib\parser.js:59:16)
    at parse (C:\GIT\PIM\Pim.Solution\Pim.PortalApp\node_modules\postcss\lib\parse.js:11:12)
    at new LazyResult (C:\GIT\PIM\Pim.Solution\Pim.PortalApp\node_modules\postcss\lib\lazy-result.js:132:16)
    at Processor.process (C:\GIT\PIM\Pim.Solution\Pim.PortalApp\node_modules\postcss\lib\processor.js:34:12)
    at cssnanoMinify (C:\GIT\PIM\Pim.Solution\Pim.PortalApp\node_modules\css-minimizer-webpack-plugin\dist\utils.js:58:61)
    at minify (C:\GIT\PIM\Pim.Solution\Pim.PortalApp\node_modules\css-minimizer-webpack-plugin\dist\minify.js:15:32)
    at C:\GIT\PIM\Pim.Solution\Pim.PortalApp\node_modules\css-minimizer-webpack-plugin\dist\index.js:262:128`

**Comment by mlc-mlapis** [comment] 2021-06-03 18:39
@negberts You need to @forward it somewhere before @use.

**Comment by BenRacicot** [comment] 2021-06-26 23:38
I'm not sure if the Material conversation belongs here but I was able to fix this issue.

I was using the default Angular serve so I updated it to use my custom serve configuration.

```
"scripts": {
    "ng": "ng",
    "start": "ng serve --proxy-config proxy.conf.json --configuration dev",
    "start:dev": "ng serve --proxy-config proxy.conf.json --configuration dev",
    "start:stage": "ng serve --c stage --proxy-config proxy.conf.json --configuration stage",
    "start:prod": "ng serve --c stage --proxy-config proxy.conf.json --configuration prod",
```

Then  configured it within angular.json's build -> configurations

```
"configurations": {
    "dev": {
        "fileReplacements": [
            {
                "replace": "src/environments/environment.ts",
                "with": "src/environments/environment.dev.ts"
            }
        ],
        "optimization": true,
        "sourceMap": true,
        "namedChunks": false,
        "extractLicenses": true,
        "vendorChunk": true,
        "buildOptimizer": true
    },
    ...
```
Hope this helps.

Wrote a 3 part article on [customizing development environments](https://benracicot.medium.com/customize-angulars-build-system-for-local-dev-stage-and-prod-53516c8bc311) if you're interested.

**Comment by Splaktar** [comment] 2021-07-09 18:54
As mentioned in https://github.com/angular/angular/issues/42100#issuecomment-841552268, this issue is being investigated and tracked in the Angular CLI repo. This issue can probably be closed as it doesn't seem to provide any additional info.

**Comment by JoostK** [comment] 2021-07-09 22:40
There's also now #42799 which is a more complete report of perf issues when using the AOT compiler, so let's close this one indeed.

**Closed by JoostK** 2021-07-09 22:40 UTC
Labels: comp: compiler

**Comment by AlexanderChechyotko** [comment] 2021-07-15 14:17
In the tsConfig use `"target": "es6"`(es2020) instead of `"target": "es5"`

**Comment by simeyla** [comment] 2021-07-15 22:29
@AlexanderChechyotko you made a typo - `es6` is `es2015`, not 2020.
All options: https://www.typescriptlang.org/tsconfig#target

Currently by default [in Angular](https://angular.io/guide/typescript-configuration#libdts), the target is es2015.

But yes definitely shouldn't be `es5` for probably 99.9% of people.

**Comment by zeshan321** [comment] 2021-07-28 16:10
Removing `"emitDecoratorMetadata": true,` from tsconfig.json reduced our build time significantly.
