### ISSUE TITLE
Change of QueryParam not detected

### ISSUE THREAD

**Issue by tschaka1904** [angular/angular#27393] opened 2018-12-01 20:49 UTC
About a year ago created #17609, which still seems to an issue and get more and more attention. 

Unfortunately it was closed by  @jasonaden, as he didn't see the need value in it. Please open #17609 again, to be able to find a solution.

**Comment by jotatoledo** [comment] 2018-12-03 21:44
The issue was closed because it lacks a repro.
This one lacks it too.

Instead of asking for the old issue to be reopened, edit this one (fill the issue template) with all the information required to _replace_ the old one, with a clear reference to it.

**Comment by jasonaden** [comment] 2018-12-07 00:04
Please see response on #17609. Closing as per that response.

That being said, it sounds like you have a real issue so filing a new one would be helpful. And now for the canned response:

<hr>

I'm sorry but reported issues require a reproduction of the issue. We suggest using [StackBlitz](https://stackblitz.com/fork/angular-gitter).

If this issue persists, please create a reproduction using one of the links above. Describe the difference between the expected and current behavior in a new issue with the reproduction linked.

**Closed by jasonaden** 2018-12-07 00:04 UTC
Labels: comp: router

**Comment by tschaka1904** [comment] 2018-12-07 01:17
Wow, @jasonaden! Did you have a look at #17609? I may didn't meet the "requirements", but some people did actually come up the a reproduction. This is what I call community, thanks @jasonaden! Maybe one of the reason why I'm not part of this one anymore.

**Comment by jotatoledo** [comment] 2018-12-07 12:58
A solution for the repro in the original source was already mentioned in the comments. 

Basically, mutating members of the source `queryParams` object leaded to the faulty state of the promise returned by `navigate`. See https://stackblitz.com/edit/github-hwwd6n-n6ogpy

Im not sure if this solves your original problem, as once again, there is no concrete reproduction of it.

**Comment by onamfc** [comment] 2019-02-27 19:58
I haven't been following both threads here, but when it comes to detecting queryParams, have you tried to add runGuardsAndResolvers: 'paramsOrQueryParamsChange' to your routes? That will rerun your resolver and guards. 

`Routes = [{
    path: '',
    component: VideoComponent,
    resolve: {
        tracking: UserTrackingService,
        video: VideoService
    },
    runGuardsAndResolvers: 'paramsOrQueryParamsChange',
}];`

**Comment by MrGWest** [comment] 2019-06-13 12:22
I had the same problem and tried to reproduce it on Stackblitz.com, but without success (as in, it won't break). If someone would like to try and break it. https://angular-gitter-zb2wky.stackblitz.io

My code looks exactly the same, but I'm not getting any of the observable value changes.

**Comment by MrGWest** [comment] 2019-06-13 15:26
Also, make absolutely sure that there is not an error inside your subscribe function!
