### ISSUE TITLE
ngIf keeps node in memory

### ISSUE THREAD

**Issue by devInterests** [angular/angular#27263] opened 2018-11-25 19:50 UTC
# 🐞 bug report

### Affected Package

I do not know.

### Is this a regression?

Fails in Angular 5 and 7.

### Description

First tried on StackOverflow https://stackoverflow.com/questions/53470286/angular-ngif-memory-usage, had no luck with it.

What the documentation says:

When the condition is false, NgIf removes its host element from the DOM, detaches it from DOM events (the attachments that it made), detaches the component from Angular change detection, and destroys it. The component and DOM nodes can be garbage-collected and free up memory.

My observation:
*ngIf host element is not in the DOM but it is in the memory.

I have a huge list. Inside each list element are some *ngIfs. I see a lot of detached nodes and memory usage. When I remove *ngIfs then my memory and detached nodes counter is much smaller.

Please, see stackblits.
Created a demo. Checked the difference with Performance monitor from Chrome.
Please, check the Dom Nodes count with the span and without.
The count difference is by 10000. The size of the list.

Thanks.

## 🔬 Minimal Reproduction

 
https://stackblitz.com/edit/angular-4uzenw

**Comment by trotyl** [comment] 2018-11-26 02:41
It's the expected behavior, try replace:

```html
<span *ngIf="item.count === 2"> Item 2 </span>
```

With:

```html
<ng-container *ngIf="item.count === 2"></ng-container>
```

You'll get same number of nodes.

> *ngIf host element is not in the DOM but it is in the memory.

Please be aware the host ~~element~~ node is always a comment to mark the position, it's not related to where you put it. Of course comment nodes are also nodes being counted, but it's not a memory leak.

**Comment by devInterests** [comment] 2018-11-26 10:17
> With:
> 
> ```
> <ng-container *ngIf="item.count === 2"></ng-container>
> ```
 I tried it out with ng-container, it has the same Node count as ngIf.

**Comment by sarunint** [comment] 2018-11-26 10:38
And please note that the comment nodes exist in development mode only. So calling `enableProdMode` will make it go away.

**Comment by trotyl** [comment] 2018-11-26 10:50
@sarunint The comment nodes would actually always exists (which is critical for position marking), but in dev mode it will expose extra binding info inside the comment text.

**Comment by sarunint** [comment] 2018-11-26 10:53
@trotyl You are right, my mistake. 😛

**Comment by devInterests** [comment] 2018-11-26 12:43
Ok, understood.
I have a very big table. Each td shows different elements, based on the table model object. However, each cell contains multiple ngIfs. The memory usage and the Dom Nodes count are both very big. So the site is running slow. If I remove the ngIfs from the td implementation (leave just one) everything works well.
The type of td is required just on the beginning, after the table is shown nothing in td will be changed. 
Any suggestions how to improve that?
Beside virtual scrolling.

**Comment by mlc-mlapis** [comment] 2018-11-26 13:57
@devInterests ... without simple reproduction of that case? ... hard to say anything.

**Comment by dawidgarus** [comment] 2018-11-26 15:14
@devInterests That's really case specific... Each ngIf is a binding which will be checked for changes... If it's possible simplify your conditions and keep them simple.
Don't call any computation heavy functions in bindings or cache the result.
It may be possible to group adjacent cells:
```html
<!-- BAD -->
<td *ngIf="A">1</td>
<td *ngIf="A">2</td>

<!-- GOOD -->
<ng-container *ngIf="A">
  <td>1</td>
  <td>2</td>
</ng-container>
```
Perhaps you can pull out `ngIf`s outside `ngFor`:
```html
<!-- BAD -->
<tr *ngFor>
  <td *ngIf="caseA">A</td>
  <td *ngIf="caseB">B</td>
</tr>

<!-- GOOD -->
<ng-container *ngIf="caseA">
  <tr *ngFor>
    <td>A</td>
  </tr>
</ng-container>
<ng-container *ngIf="caseB">
  <tr *ngFor>
    <td>B</td>
  </tr>
</ng-container>
```
Or you can replace `ngIf` with `ngSwitch`.
Finally, consider using OnPush [change detection strategy](https://angular.io/api/core/ChangeDetectionStrategy)

**Comment by mlc-mlapis** [comment] 2018-11-26 15:33
@devInterests ... also correct using of `trackBy` on `*ngFor` is  one of the necessary building stone.

**Comment by devInterests** [comment] 2018-11-26 15:58
Thank you for your suggestions.
 OnPush is used in all components, tackBy-functions with unified ids is also used.  
I also checked ng.profiler.timeChangeDetection(); it takes less than 0.300 milliseconds.

Simple structure example of my code:

 ```html
<table>

  <td *ngFor="let td of tableRows; trackBy:trackRowFunc; let rowIndex = index">

  <ng-container *ngIf="td.edit">
     <input [xxx]=xxx />
  </ng-container >

  <ng-container *ngIf="td.read">
    <div [xxx] =xxx/>
  </ng-container >

  <ng-container *ngIf="td.time">
   <time-picker [xxx] =xxx />
  </ng-container >

  <ng-container *ngIf="td.date">
    <date-picker  [xxx] =xxx/>
  </ng-container >

  <ng-container *ngIf="td.xxx">
    <xxx  [xxx] =xxx/>
  </ng-container >

</td>

</table>

 ```
I tried with ngIf and ngSwitch.

The problem is that with all ngIfs it takes a lot of memory and has a lot of nodes. But actually I do not need them after initialization. If something in the table will be changed, a new table-model object will be provided to a @input-field because of onPush.

My idea was to create the content of td dynamically in the code or something like that?

**Comment by mlc-mlapis** [comment] 2018-11-26 16:19
@devInterests ... some comments:
* is `trackBy` using global unique `id` for a row or just index?\
* using separate templates defined one level up could be a way
* and of course dynamic creation of rows eliminates all `*ngIf`

**Comment by devInterests** [comment] 2018-11-26 16:45
@mlc-mlapis 

1. Table-rows are using index, table-data unique id. Is there a issue to use the index?
2. Will try.
3. Will try.

@pkozlowski-opensource  @dawidgarus 
So the strategy is to reduce ngIfs to have less entry-nodes for it.
I already started to implement it, will see.

Thanks to all.

**Comment by mlc-mlapis** [comment] 2018-11-26 19:58
@devInterests ... when you insert a new row or delete an existing one somewhere in the middle, the index and rows are shifting and all behind the place is necessary to re-render again.

**Comment by alxhub** [comment] 2018-11-27 23:39
(Closing this issue as Working As Intended, feel free to continue discussions)

**Closed by alxhub** 2018-11-27 23:39 UTC
Labels: comp: core & compiler

**Comment by devInterests** [comment] 2018-11-28 08:47
1. Moved all available types of td to templates.
2. Leaved one ng-container:  <ng-container *ngTemplateOutlet="getTableDataTemplateId(td); ...>

That reduced more than half of the memory usage and the node counter.
Thanks all for support.
