### ISSUE TITLE
Feature: Add type informations regarding structure of FormGroup and FormArray

### ISSUE THREAD

**Issue by dawidgarus** [angular/angular#27072] opened 2018-11-13 11:15 UTC
# 🚀 feature request

### Releavant Package

 This feature request is for @angular/forms

### Description
Reactive forms should have type informations about the structure of the form

### Describe the solution you'd like
Change `FormArray`, `FormGroup` classes to be generic types with following signatures:
`FormArray<ItemType = AbstractControl>`
and
`FormGroup<ItemsMapType = { [key: string]: AbstractControl }>`
All methods that adds/removes controls to `FormArray` and `FormGroups` should return this but with changed template variable that reflects what was changed, for example:
```typescript
const group = new FormGroup({}); // group type is FormGroup<{}>
const newGroup = group
  .addControl('name', new FormControl())
  .addControl('address', new FormGroup({
    city: new FormControl(),
    street: new FormControl(),
  })); // newGroup type is FormGroup<{ name: FormControl, address: FromGroup<{city: FormControl, street: FormControl}> }>
console.log(newGroup.controls.name) // ok
console.log(newGroup.controls.surname) // error, missing field surname
```
Similar changes should be made to `FormBuilder`

### Describe alternatives you've considered
It could be probably done by creating custom classes which derive from `FormXxx` but it's such a useful (and backwards compatible) change that I think should go to @angular/forms.

One problem I see is that `FormGroup` is mutable - you can add and remove controls and structure information can be different than actual. Maybe introduce `FormImmutableGroup` (base class for `FormGroup`) to which you cannot add/remove controls?

**Comment by sarunint** [comment] 2018-11-13 15:15
Duplicate of #13721, will be fixed by #20040, blocked at Microsoft/TypeScript#16229.

**Closed** 2018-11-13 19:14 UTC
