### ISSUE TITLE
Lazy-loaded module import increases the size of main.js

### ISSUE THREAD

**Issue by h3d0** [angular/angular#37576] opened 2020-06-14 12:02 UTC
# 🐞 bug report

### Affected Package

Unable to specify which package exactly might cause the issue.

### Is this a regression?

Unable to confirm whether this is a regression.

### Description

Adding imports in the lazy-loaded module increases the size of the **main.js** file, although one would expect to increase the size of **the lazy-loaded chunk instead**.

## 🔬 Minimal Reproduction

1. Create a new project:

`ng new --routing --style=scss --minimal --directory . foo`

2. Install any source explorer tool, e.g.:

`npm i --save-dev source-map-explorer`

3. Run the tool and verify the initial bundle size:

```
ng build --prod --source-map && npx source-map-explorer ./dist/foo/main-es2015*
Generating ES5 bundles for differential loading...
ES5 bundle generation complete.

chunk {3} polyfills-es5.525c0f1df1216a56cb7c.js, polyfills-es5.525c0f1df1216a56cb7c.js.map (polyfills-es5) 129 kB [initial] [rendered]
chunk {2} polyfills-es2015.9ccc4b3451c3b03e42c9.js, polyfills-es2015.9ccc4b3451c3b03e42c9.js.map (polyfills) 36.2 kB [initial] [rendered]
chunk {0} runtime-es2015.1eba213af0b233498d9d.js, runtime-es2015.1eba213af0b233498d9d.js.map (runtime) 1.51 kB [entry] [rendered]
chunk {0} runtime-es5.1eba213af0b233498d9d.js, runtime-es5.1eba213af0b233498d9d.js.map (runtime) 1.51 kB [entry] [rendered]
chunk {1} main-es2015.e041871c6406abdadff8.js, main-es2015.e041871c6406abdadff8.js.map (main) 188 kB [initial] [rendered]
chunk {1} main-es5.e041871c6406abdadff8.js, main-es5.e041871c6406abdadff8.js.map (main) 229 kB [initial] [rendered]
chunk {4} styles.a5383db5766266fff045.css, styles.a5383db5766266fff045.css.map (styles) 0 bytes [initial] [rendered]
Date: 2020-06-14T11:41:24.285Z - Hash: 9c55b17bc019f03f9ae3 - Time: 18465ms
./dist/foo/main-es2015.e041871c6406abdadff8.js
  Unable to map 130/192829 bytes (0.07%)
```

4. Add a lazy-loaded component:

`ng g m --routing --route bar -m / bar`

5. Verify bundle increase:

```
Generating ES5 bundles for differential loading...
ES5 bundle generation complete.

chunk {2} polyfills-es2015.9ccc4b3451c3b03e42c9.js, polyfills-es2015.9ccc4b3451c3b03e42c9.js.map (polyfills) 36.2 kB [initial] [rendered]
chunk {3} polyfills-es5.525c0f1df1216a56cb7c.js, polyfills-es5.525c0f1df1216a56cb7c.js.map (polyfills-es5) 129 kB [initial] [rendered]
chunk {0} runtime-es2015.797be83d07987fc161ae.js, runtime-es2015.797be83d07987fc161ae.js.map (runtime) 2.3 kB [entry] [rendered]
chunk {0} runtime-es5.797be83d07987fc161ae.js, runtime-es5.797be83d07987fc161ae.js.map (runtime) 2.29 kB [entry] [rendered]
chunk {5} 5-es2015.14ba29b5ea525d800548.js, 5-es2015.14ba29b5ea525d800548.js.map () 808 bytes  [rendered]
chunk {5} 5-es5.14ba29b5ea525d800548.js, 5-es5.14ba29b5ea525d800548.js.map () 1.26 kB  [rendered]
chunk {1} main-es2015.44e342da6bd03a967503.js, main-es2015.44e342da6bd03a967503.js.map (main) 215 kB [initial] [rendered]
chunk {1} main-es5.44e342da6bd03a967503.js, main-es5.44e342da6bd03a967503.js.map (main) 259 kB [initial] [rendered]
chunk {4} styles.a5383db5766266fff045.css, styles.a5383db5766266fff045.css.map (styles) 0 bytes [initial] [rendered]
Date: 2020-06-14T11:45:40.140Z - Hash: dac0e67574dd642184ef - Time: 58321ms
./dist/foo/main-es2015.44e342da6bd03a967503.js
  Unable to map 132/220413 bytes (0.06%)
```

6. Import some module **into in the lazy-loaded module**, e.g.:

```
import { ReactiveFormsModule } from '@angular/forms';
...
@NgModule({
  declarations: [BarComponent],
  imports: [
    CommonModule,
    BarRoutingModule,
    ReactiveFormsModule,
  ]
})
export class BarModule { }
```

7. Verify **main.js** size:

```
Generating ES5 bundles for differential loading...
ES5 bundle generation complete.

chunk {2} polyfills-es2015.9ccc4b3451c3b03e42c9.js, polyfills-es2015.9ccc4b3451c3b03e42c9.js.map (polyfills) 36.2 kB [initial] [rendered]
chunk {3} polyfills-es5.525c0f1df1216a56cb7c.js, polyfills-es5.525c0f1df1216a56cb7c.js.map (polyfills-es5) 129 kB [initial] [rendered]
chunk {0} runtime-es2015.374620d6b9ff23e2bd3c.js, runtime-es2015.374620d6b9ff23e2bd3c.js.map (runtime) 2.3 kB [entry] [rendered]
chunk {0} runtime-es5.374620d6b9ff23e2bd3c.js, runtime-es5.374620d6b9ff23e2bd3c.js.map (runtime) 2.29 kB [entry] [rendered]
chunk {5} 5-es2015.ed0485104d2f68ad511d.js, 5-es2015.ed0485104d2f68ad511d.js.map () 17.5 kB  [rendered]
chunk {5} 5-es5.ed0485104d2f68ad511d.js, 5-es5.ed0485104d2f68ad511d.js.map () 26.7 kB  [rendered]
chunk {1} main-es2015.5e41a9b0d9be82402ec4.js, main-es2015.5e41a9b0d9be82402ec4.js.map (main) 223 kB [initial] [rendered]
chunk {1} main-es5.5e41a9b0d9be82402ec4.js, main-es5.5e41a9b0d9be82402ec4.js.map (main) 267 kB [initial] [rendered]
chunk {4} styles.a5383db5766266fff045.css, styles.a5383db5766266fff045.css.map (styles) 0 bytes [initial] [rendered]
Date: 2020-06-14T11:48:05.768Z - Hash: 2ea3762715eea9c13021 - Time: 61086ms
./dist/foo/main-es2015.5e41a9b0d9be82402ec4.js
  Unable to map 132/228478 bytes (0.06%)
```

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 9.1.8
Node: 12.16.3
OS: linux x64

Angular: 9.1.11
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.8
@angular-devkit/build-angular     0.901.8
@angular-devkit/build-optimizer   0.901.8
@angular-devkit/build-webpack     0.901.8
@angular-devkit/core              9.1.8
@angular-devkit/schematics        9.1.8
@angular/cli                      9.1.8
@ngtools/webpack                  9.1.8
@schematics/angular               9.1.8
@schematics/update                0.901.8
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0
</code></pre>

**Anything else relevant?**

Is this the expected behavior that after importing the `ReactiveFormsModule` in the `Bar` component (lazy loaded in the app-routing module like `{ path: 'bar', loadChildren: () => import('./bar/bar.module').then(m => m.BarModule) }` the **main.js** size has increase from 215 KB to 223 KB?

Importing more module increases the **main.js** size even more.

This makes route-level code splitting non-effective (_what is the point of code-splitting at all in this case?_).

---

Real-world example:
- There is an e-commerce PWA which is supposed to load items as fast as possible (for SEO). It contains a "closed" page (e.g. a Cart) which does no need SEO or being crawled. The Cart page `ReactiveFormsModule`.

It should be possible to load the `ReactiveFormsModule` code only when it is needed and not put it into the main bundle on every page load.

**Comment by petebacondarwin** [comment] 2020-10-19 14:28
I just tried this but with `optimization` turned off, so it is easier to see the difference between the `main.js` files.

What I found was that after the initial creation of the project there was this line in main.js:

```ts
const routes = [];
```

After adding a single `bar` route as described above the only difference to `main.js` was the above line changed to:

```ts
const routes = [
  {
    path: 'bar',
    loadChildren: () => __webpack_require__.e(/*! import() | bar-bar-module */ "bar-bar-module")
        .then(__webpack_require__.bind(null, /*! ./bar/bar.module */ "KCcC"))
        .then(m => m.BarModule)
  }
];
```

(I have added some formatting to make it easier to read - but in the file it is all on one line.)

After adding the reference to the `ReactiveFormsModule` library in the lazy module, there is no change to the main.js file at all.

**Comment by petebacondarwin** [comment] 2020-10-19 14:29
I do see increases to the file sizes of the optimized code, similar to what is in this issue report.
So I wonder if the problem is related to how terser / build-optimizer is optimizing the code?

**Comment by petebacondarwin** [comment] 2020-10-19 15:01
I think this might need to be transferred to the CLI...

**Comment by petebacondarwin** [comment] 2020-10-19 15:51
These are my results:

**With source-maps on:**

Runtime | Main | Polyfills
---------|------|--------
1.5kb | 186kb | 36.1kb
2.3kb | 211kb | 36.1kb
2.3kb | 218kb | 36.1kb

**With source-maps off:**

Runtime | Main | Polyfills
---------|------|--------
1.45kb | 186kb | 36kb
2.23kb | 211kb | 36kb
2.23kb | 218kb | 36kb

**Comment by alan-agius4** [comment] 2020-10-20 09:54
When adding add a lazy loaded module we notice an increase in the `main.js` which comes from the inclusion of additional of extra RxJS operators, and extra code being pulled from `@angular/{core/routing/common}` such as more code from `instructions.ts`, `config.ts` etc..., these are all need to handle lazy routing.

When adding the `ReactiveFormsModule` in the lazy loaded module, we also notice an additional increase in the `main.js` file. This is because for the forms to work, we need to pull in additional code from `@angular/core`, once again additional instructions among others. 

This is actually working as expected because `Webpack`, which is the tool used under the hood by the Angular CLI, doesn’t do code motion, meaning that a module cannot be split/moved in multiple chunks based on usage.
 
Example, when having the below code structure, which is a very simplified version of what is happening in your case. All 3 methods will be be included in the shared chunk (In your case the shared chunk happens to be main.js), even though `foo` and `bar` are never used in the same module.

**shared.js**
```.js
export function foo() { }

export function bar() { }

export function buz() { }
```

**main.js**
```js
import { foo, buz } from './shared';
foo();
buz();
```

**lazy.js**
```js
import { bar, buz } from './shared';
bar();
buz();
```
 
Closing as this is not actionable by the Angular team.

**Closed by alan-agius4** 2020-10-20 09:54 UTC
Labels: P4, comp: packaging, state: needs more investigation
