### ISSUE TITLE
Router isn't destroyed when the owning Module is destroyed.

### ISSUE THREAD

**Issue by joeldenning** [angular/angular#19079] opened 2017-09-06 22:20 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
After destroying a module that uses @angular/router, the router will still be active and try to perform routing.

## Expected behavior
After you call `module.destroy()` on a module that has uses angular router, the router should no longer listen to hashchange and popstate events and does not try to match routes to components.

If there is something else that I should be doing to deactivate angular router besides `module.destroy()`, would love to hear!

If there isn't anything I'm missing, then this is a bug and I have debugged it enough to maybe be close to knowing enough to send a pr for the fix. What seems to be happening is that the [Router class' ngOnDestroy](https://github.com/angular/angular/blob/master/packages/router/src/router.ts#L335-L343) is not being called when the module is destroyed, which is what cleans up the subscription to Location. The reason that ngOnDestroy isn't being called seems to be that `NodeFlags.onDestroy` is not being set for the [Router class](https://github.com/angular/angular/blob/master/packages/router/src/router.ts#L200). This matters because when module.destroy() is called, the [onDestroy flag needs to be set in order for `ngOnDestroy()` to be called](https://github.com/angular/angular/blob/master/packages/core/src/view/ng_module.ts#L167-L172). I am not exactly sure with all of the reflection/JIT compiler stuff how to get the Router class to have that NodeFlag set, but my current guess is that it might be related to the Router class not formally declaring that it `implements OnDestroy`. Other providers that do so seem to have the onDestroy flag set (such as [RouterPreloader](https://github.com/angular/angular/blob/master/packages/router/src/router_preloader.ts#L76))

## Minimal reproduction of the problem with instructions
http://plnkr.co/edit/1IkhNPCCkvuLTheNTcAw

1) Click on "Navigate to angular app"
2) Click on "Navigate to non-angular app"
3) View errors in browser console.

## What is the motivation / use case for changing the behavior?
This is problematic when you navigate to a route that Angular router doesn't know about because it should be dormant for that route. If a single-page app consists of some routes owned by angular and some routes owned by something else, it does not seem possible to turn off angular router even by calling `module.destroy()`

## Environment

<pre><code>
Angular version: 4.4.4

Browser:

(All browsers affected)

- [X] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by kirill-konshin** [comment] 2017-11-21 00:50
Issue is reproduced in v5.x too.

**Comment by kirill-konshin** [comment] 2017-11-22 01:02
So since #20491 was closed as duplicate what's the ETA of this one fixed? This is quite an old bug, it was reported in September.

Is there any workaround or quick fix?

**Comment by joeldenning** [comment] 2017-11-22 01:09
The workaround I ended up going with is this (see example [here](https://github.com/CanopyTax/single-spa-angular2/blob/master/src/single-spa-angular2.js#L62-L63)):

```js
const routerRef = bootstrappedModule.injector.get(opts.Router);
routerRef.dispose();
```

So I'm just manually disposing the Router since Angular doesn't do it during the destroy process like I would expect. For a day or two I tried to figure out how to fix this in the angular source, but gave up after a while and have just happily using my workaround :)

**Comment by kirill-konshin** [comment] 2017-11-22 01:14
@joeldenning thanks for the workaround! Where `opts.Router` is defined?

**Comment by joeldenning** [comment] 2017-11-22 03:26
Yeah `opts` is just part of how single-spa-angular2 is storing variables and things -- not related to angular at all

**Comment by joeldenning** [comment] 2019-04-09 19:37
I think this might be fixed in angular 7. Tried to reproduce this just now and wasn't able to. Not 100% sure though if i did all the steps to verify everything is fixed though

**Comment by atscott** [comment] 2020-07-08 20:01
This appears to have been resolved at some point. I cannot reproduce this in v10 anymore (https://stackblitz.com/edit/angular-ivy-cgjc6a?file=src%2Findex.html)

If after upgrade the problem still exists in your application please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.

**Closed by atscott** 2020-07-08 20:01 UTC
Labels: comp: router, freq1: low, severity4: memleak, type: bug/fix
