### ISSUE TITLE
Animations causing problems with SSR: document is not defined

### ISSUE THREAD

**Issue by kukjevov** [angular/angular#15098] opened 2017-03-12 20:29 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When i use animations in HTML, SSR crashes. 

I have my animation defined and used in html like this
```html
<div [@flyIn]></div>
```
I have browser module which imports `import {BrowserAnimationsModule} from '@angular/platform-browser/animations';`

I received error on server 
Error: Found the synthetic property @flyIn. Please include either "BrowserAnimationsModule" or "NoopAnimationsModule" in your application.

When i import in server module `import {NoopAnimationsModule} from '@angular/platform-browser/animations';`
i receive another error which cause crash of server.

EXCEPTION: document is not defined
ORIGINAL STACKTRACE:
ReferenceError: document is not defined
    at DefaultDomRenderer2.selectRootElement (F:\git\ng-universal-demo\dist\server.js:31873:72)
    at createElement (F:\git\ng-universal-demo\dist\server.js:9067:23)
    at createViewNodes (F:\git\ng-universal-demo\dist\server.js:11533:44)
    at createRootView (F:\git\ng-universal-demo\dist\server.js:11480:5)
    at Object.createProdRootView [as createRootView] (F:\git\ng-universal-demo\dist\server.js:12049:12)
    at ComponentFactory_.create (F:\git\ng-universal-demo\dist\server.js:9485:46)
    at ApplicationRef_.bootstrap (F:\git\ng-universal-demo\dist\server.js:4862:57)
    at F:\git\ng-universal-demo\dist\server.js:4657:89
    at Array.forEach (native)
    at PlatformRef_._moduleDoBootstrap (F:\git\ng-universal-demo\dist\server.js:4657:42)
    at F:\git\ng-universal-demo\dist\server.js:4620:27
    at ZoneDelegate.invoke (F:\git\ng-universal-demo\dist\server.js:59567:26)
    at Object.onInvoke (F:\git\ng-universal-demo\dist\server.js:4017:37)
    at ZoneDelegate.invoke (F:\git\ng-universal-demo\dist\server.js:59566:32)
    at Zone.run (F:\git\ng-universal-demo\dist\server.js:59359:43)
Unhandled Promise rejection: document is not defined ; Zone: <root> ; Task: Promise.then ; Value: { ReferenceError: document is not defined
    at DefaultDomRenderer2.selectRootElement (F:\git\ng-universal-demo\dist\server.js:31873:72)
    at createElement (F:\git\ng-universal-demo\dist\server.js:9067:23)
    at createViewNodes (F:\git\ng-universal-demo\dist\server.js:11533:44)
    at createRootView (F:\git\ng-universal-demo\dist\server.js:11480:5)
    at Object.createProdRootView [as createRootView] (F:\git\ng-universal-demo\dist\server.js:12049:12)
    at ComponentFactory_.create (F:\git\ng-universal-demo\dist\server.js:9485:46)
    at ApplicationRef_.bootstrap (F:\git\ng-universal-demo\dist\server.js:4862:57)
    at F:\git\ng-universal-demo\dist\server.js:4657:89
    at Array.forEach (native)
    at PlatformRef_._moduleDoBootstrap (F:\git\ng-universal-demo\dist\server.js:4657:42)
    at F:\git\ng-universal-demo\dist\server.js:4620:27
    at ZoneDelegate.invoke (F:\git\ng-universal-demo\dist\server.js:59567:26)
    at Object.onInvoke (F:\git\ng-universal-demo\dist\server.js:4017:37)
    at ZoneDelegate.invoke (F:\git\ng-universal-demo\dist\server.js:59566:32)
    at Zone.run (F:\git\ng-universal-demo\dist\server.js:59359:43)
  __zone_symbol__currentTask:
   ZoneTask {
     zone:
      Zone {
        _properties: {},
        _parent: null,
        _name: '<root>',
        _zoneDelegate: [Object] },
     runCount: 0,
     _zoneDelegates: null,
     _state: 'notScheduled',
     type: 'microTask',
     source: 'Promise.then',
     data: undefined,
     scheduleFn: undefined,
     cancelFn: null,
     callback: [Function],
     invoke: [Function] } } ReferenceError: document is not defined
    at DefaultDomRenderer2.selectRootElement (F:\git\ng-universal-demo\dist\server.js:31873:72)
    at createElement (F:\git\ng-universal-demo\dist\server.js:9067:23)
    at createViewNodes (F:\git\ng-universal-demo\dist\server.js:11533:44)
    at createRootView (F:\git\ng-universal-demo\dist\server.js:11480:5)
    at Object.createProdRootView [as createRootView] (F:\git\ng-universal-demo\dist\server.js:12049:12)
    at ComponentFactory_.create (F:\git\ng-universal-demo\dist\server.js:9485:46)
    at ApplicationRef_.bootstrap (F:\git\ng-universal-demo\dist\server.js:4862:57)
    at F:\git\ng-universal-demo\dist\server.js:4657:89
    at Array.forEach (native)
    at PlatformRef_._moduleDoBootstrap (F:\git\ng-universal-demo\dist\server.js:4657:42)
    at F:\git\ng-universal-demo\dist\server.js:4620:27
    at ZoneDelegate.invoke (F:\git\ng-universal-demo\dist\server.js:59567:26)
    at Object.onInvoke (F:\git\ng-universal-demo\dist\server.js:4017:37)
    at ZoneDelegate.invoke (F:\git\ng-universal-demo\dist\server.js:59566:32)
    at Zone.run (F:\git\ng-universal-demo\dist\server.js:59359:43)
{ Error: Uncaught (in promise): ReferenceError: document is not defined
ReferenceError: document is not defined
    at DefaultDomRenderer2.selectRootElement (F:\git\ng-universal-demo\dist\server.js:31873:72)
    at createElement (F:\git\ng-universal-demo\dist\server.js:9067:23)
    at createViewNodes (F:\git\ng-universal-demo\dist\server.js:11533:44)
    at createRootView (F:\git\ng-universal-demo\dist\server.js:11480:5)
    at Object.createProdRootView [as createRootView] (F:\git\ng-universal-demo\dist\server.js:12049:12)
    at ComponentFactory_.create (F:\git\ng-universal-demo\dist\server.js:9485:46)
    at ApplicationRef_.bootstrap (F:\git\ng-universal-demo\dist\server.js:4862:57)
    at F:\git\ng-universal-demo\dist\server.js:4657:89
    at Array.forEach (native)
    at PlatformRef_._moduleDoBootstrap (F:\git\ng-universal-demo\dist\server.js:4657:42)
    at F:\git\ng-universal-demo\dist\server.js:4620:27
    at ZoneDelegate.invoke (F:\git\ng-universal-demo\dist\server.js:59567:26)
    at Object.onInvoke (F:\git\ng-universal-demo\dist\server.js:4017:37)
    at ZoneDelegate.invoke (F:\git\ng-universal-demo\dist\server.js:59566:32)
    at Zone.run (F:\git\ng-universal-demo\dist\server.js:59359:43)
    at resolvePromise (F:\git\ng-universal-demo\dist\server.js:59898:31) [<root>]
    at resolvePromise (F:\git\ng-universal-demo\dist\server.js:59869:17) [<root>]
    at F:\git\ng-universal-demo\dist\server.js:59946:17 [<root>]
    at Zone.runTask (F:\git\ng-universal-demo\dist\server.js:59399:47) [<root> => <root>]
    at drainMicroTaskQueue (F:\git\ng-universal-demo\dist\server.js:59779:35) [<root>]
    at ZoneTask.invoke (F:\git\ng-universal-demo\dist\server.js:59657:25) [<root>]
    at data.args.(anonymous function) (F:\git\ng-universal-demo\dist\server.js:60752:25) [<root>]
    at FSReqWrap.oncomplete (fs.js:114:15) [<root>]
  __zone_symbol__error:
   { Error: Uncaught (in promise): ReferenceError: document is not defined
   ReferenceError: document is not defined
       at DefaultDomRenderer2.selectRootElement (F:\git\ng-universal-demo\dist\server.js:31873:72)
       at createElement (F:\git\ng-universal-demo\dist\server.js:9067:23)
       at createViewNodes (F:\git\ng-universal-demo\dist\server.js:11533:44)
       at createRootView (F:\git\ng-universal-demo\dist\server.js:11480:5)
       at Object.createProdRootView [as createRootView] (F:\git\ng-universal-demo\dist\server.js:12049:12)
       at ComponentFactory_.create (F:\git\ng-universal-demo\dist\server.js:9485:46)
       at ApplicationRef_.bootstrap (F:\git\ng-universal-demo\dist\server.js:4862:57)
       at F:\git\ng-universal-demo\dist\server.js:4657:89
       at Array.forEach (native)
       at PlatformRef_._moduleDoBootstrap (F:\git\ng-universal-demo\dist\server.js:4657:42)
       at F:\git\ng-universal-demo\dist\server.js:4620:27
       at ZoneDelegate.invoke (F:\git\ng-universal-demo\dist\server.js:59567:26)
       at Object.onInvoke (F:\git\ng-universal-demo\dist\server.js:4017:37)
       at ZoneDelegate.invoke (F:\git\ng-universal-demo\dist\server.js:59566:32)
       at Zone.run (F:\git\ng-universal-demo\dist\server.js:59359:43)
       at resolvePromise (F:\git\ng-universal-demo\dist\server.js:59898:31) [<root>]
       at resolvePromise (F:\git\ng-universal-demo\dist\server.js:59869:17) [<root>]
       at F:\git\ng-universal-demo\dist\server.js:59946:17 [<root>]
       at Zone.runTask (F:\git\ng-universal-demo\dist\server.js:59399:47) [<root> => <root>]
       at drainMicroTaskQueue (F:\git\ng-universal-demo\dist\server.js:59779:35) [<root>]
       at ZoneTask.invoke (F:\git\ng-universal-demo\dist\server.js:59657:25) [<root>]
       at data.args.(anonymous function) (F:\git\ng-universal-demo\dist\server.js:60752:25) [<root>]
       at FSReqWrap.oncomplete (fs.js:114:15) [<root>]

**Expected behavior**
When i use animations in HTML, it will have no influence on SSR.

**Minimal reproduction of the problem with instructions**

* **Angular version:** >=4.0.0-rc.3

* **Browser:** [all]

 
* **Language:** [TypeScript 2.2.1]

* **Node (for AoT issues):** `node --version` = v7.7.1

**Comment by kbarralon** [comment] 2017-03-13 01:27
Same error with the same config.

**Comment by michaelwaihenya** [comment] 2017-03-13 02:52
+1

**Comment by kukjevov** [comment] 2017-03-13 06:57
Here is repository where last commit simulates error:

https://github.com/kukjevov/ng-universal-demo

It looks like that this https://github.com/angular/angular/pull/14880/files PR started this bug, or it is somehow connected to this.

**Comment by nicky-lenaers** [comment] 2017-03-13 11:49
Same error happens when using in Universal context

**Comment by feloy** [comment] 2017-03-13 13:37
I got the same error upgrading to v4-rc.3 when using material2-beta2 (and the Menu component which uses animations). 
I had to import the BrowserAnimationsModule from the AppModule and it worked again. (or NoopAnimationsModule if you do not want animations).

**Comment by kukjevov** [comment] 2017-03-13 13:51
@feloy Are you using Server Side Rendering (SSR) aka Universal ? Because this error happens in NodeJs environment, not in browser, during rendering on server side.

I have `BrowserAnimationsModule` on browser side and it is working, this is not problem :).

**Comment by feloy** [comment] 2017-03-13 14:00
@kukjevov Well, no, I got the same error (Error: Found the synthetic property ...  Please include either "BrowserAnimationsModule" or "NoopAnimationsModule" in your application.) but in the browser. My answer were not directly directed to you, but placed here if somebody had the same error in my context (using Material in the browser), because your description helped me resolve my problem. 

It was not very clear, sorry ;)

**Comment by kukjevov** [comment] 2017-03-13 14:04
No problem :), but that server side part is a bug :).

**Comment by DzmitryShylovich** [comment] 2017-03-13 14:04
Probably duplicate of https://github.com/angular/angular/issues/14784

**Comment by kukjevov** [comment] 2017-03-13 16:06
It is not duplicate :). Recomended solution in #14784 cause error mention above *document is not defined*.

**Comment by MikeRyan52** [comment] 2017-03-13 17:43
Ran into the same problem. If you need a fix you can patch the server renderer to ignore the error:

```ts
import { ɵServerRendererFactory2 } from '@angular/platform-server';


const createRenderer = ɵServerRendererFactory2.prototype.createRenderer;

ɵServerRendererFactory2.prototype.createRenderer = function () {
  const result = createRenderer.apply(this, arguments);

  const setProperty = result.setProperty;

  result.setProperty = function () {
    try {
      setProperty.apply(this, arguments);
    } catch (e) {
      if (e.message.indexOf('Found the synthetic') === -1) {
        throw e;
      }
    }
  };

  return result;
}
```

**Comment by yfain** [comment] 2017-03-14 22:08
I'm not using SSR, but Angular Material Beta.2 gives me the following error with 4.00-rc.2 when I run ng serve:

Error: Found the synthetic property @transformPlaceholder. Please include either "BrowserAnimationsModule" or "NoopAnimationsModule" in your application.
    at checkNoSyntheticProp (http://localhost:4200/vendor.bundle.js:21462:15) [angular]
    at DefaultDomRenderer2.setProperty (http://localhost:4200/vendor.bundle.js:21430:9) [angular]
    at DebugRenderer2.setProperty (http://localhost:4200/vendor.bundle.js:12813:23) [angular]
    at setElementProperty (http://localhost:4200/vendor.bundle.js:9272:19) [angular]
    at checkAndUpdateElementValue (http://localhost:4200/vendor.bundle.js:9188:13) [angular]
    at checkAndUpdateElementInline (http://localhost:4200/vendor.bundle.js:9128:24) [angular]
    at checkAndUpdateNodeInline (http://localhost:4200/vendor.bundle.js:11679:23) [angular]
    at checkAndUpdateNode (http://localhost:4200/vendor.bundle.js:11654:16) [angular]
    at debugCheckAndUpdateNode (http://localhost:4200/vendor.bundle.js:12276:59) [angular]
    at debugCheckRenderNodeFn (http://localhost:4200/vendor.bundle.js:12255:13) [angular]
    at Object.eval [as updateRenderer] (/MdSelectModule/MdSelect/component.ngfactory.js:455:5) [angular]
    at Object.debugUpdateRenderer [as updateRenderer] (http://localhost:4200/vendor.bundle.js:12240:21) [angular]
    at checkAndUpdateView (http://localhost:4200/vendor.bundle.js:11626:14) [angular]
    at callViewAction (http://localhost:4200/vendor.bundle.js:11938:17) [angular]

**Comment by vikerman** [comment] 2017-03-14 22:11
@yfain - Unrelated to this bug.

You should include BrwoserAnimationModule in your app module as the error indicates.

**Comment by yfain** [comment] 2017-03-14 22:28
Yes, I actually fixed this issue by adding import {BrowserAnimationsModule} from '@angular/platform-browser/animations'; to the app.module.

**Closed** 2017-03-17 21:51 UTC
Labels: comp: animations, comp: server, severity3: broken, type: bug

**Comment by darklx** [comment] 2017-04-15 06:16
I have the same Error in Angualr 4.0.2 Universal

ZoneAwarePromise {
     __zone_symbol__state: 0,
     __zone_symbol__value: 
      ReferenceError: document is not defined
          at ViewportRuler._cacheViewportGeometry (/Users/laurel/git/Nanhua.IOT/IOT-master/src/client2/dist/server.js:43537:30)
          at new ViewportRuler (/Users/laurel/git/Nanhua.IOT/IOT-master/src/client2/dist/server.js:43483:14)
          at Object.VIEWPORT_RULER_PROVIDER_FACTORY (/Users/laurel/git/Nanhua.IOT/IOT-master/src/client2/dist/server.js:43556:27)
          at AppServerModuleInjector.get [as _ɵh_81] (/Users/laurel/git/Nanhua.IOT/IOT-master/src/client2/dist/server.js:171879:94)
          at AppServerModuleInjector.getInternal (/Users/laurel/git/Nanhua.IOT/IOT-master/src/client2/dist/server.js:172711:24)
          at AppServerModuleInjector.NgModuleInjector.get (/Users/laurel/git/Nanhua.IOT/IOT-master/src/client2/dist/server.js:3980:44)
          at resolveDep (/Users/laurel/git/Nanhua.IOT/IOT-master/src/client2/dist/server.js:11354:45)
          at createClass (/Users/laurel/git/Nanhua.IOT/IOT-master/src/client2/dist/server.js:11223:32)
          at createDirectiveInstance (/Users/laurel/git/Nanhua.IOT/IOT-master/src/client2/dist/server.js:11051:37)
          at createViewNodes (/Users/laurel/git/Nanhua.IOT/IOT-master/src/client2/dist/server.js:12401:49)
          at callViewAction (/Users/laurel/git/Nanhua.IOT/IOT-master/src/client2/dist/server.js:12771:13)
          at execComponentViewsAction (/Users/laurel/git/Nanhua.IOT/IOT-master/src/client2/dist/server.js:12710:13)
          at createViewNodes (/Users/laurel/git/Nanhua.IOT/IOT-master/src/client2/dist/server.js:12428:5)
          at createRootView (/Users/laurel/git/Nanhua.IOT/IOT-master/src/client2/dist/server.js:12306:5)
          at Object.createProdRootView [as createRootView] (/Users/laurel/git/Nanhua.IOT/IOT-master/src/client2/dist/server.js:12884:12) },

**Comment by szykov** [comment] 2017-04-16 13:17
Same thing for me:

> Exception: Call to Node module failed with error: ReferenceError: document is not defined
> at DefaultDomRenderer2.selectRootElement (C:\Users\Administrator\Desktop\ng2-cv-blog\src\SPA\rendered\dist\app-server.js:18047:72)
> at createElement (C:\Users\Administrator\Desktop\ng2-cv-blog\src\SPA\rendered\dist\app-server.js:9587:23)


```
     /**
     * @param {?} selectorOrNode
     * @return {?}
     */
    DefaultDomRenderer2.prototype.selectRootElement = function (selectorOrNode) {
        var /** @type {?} */ el = typeof selectorOrNode === 'string' ? document.querySelector(selectorOrNode) :
            selectorOrNode;
        if (!el) {
            throw new Error("The selector \"" + selectorOrNode + "\" did not match any elements");
        }
        el.textContent = '';
        return el;
    };
```

**Comment by ysus** [comment] 2017-04-21 16:00
update for the last release but sitll i have the same errorr (Angular 4.0.3) Universal

`ERROR { ReferenceError: document is not defined
    at DefaultDomRenderer2.selectRootElement (C:\src2\evertonrobertoauler\cli-universal-demo-master\node_modules\@angular\platform-browser\bundles\platform-browser.umd.js:2821:72)`

**Comment by qdouble** [comment] 2017-04-28 00:16
I still see this error in 4.1.0... @MikeRyanDev where do you apply that patch?

**Comment by ysus** [comment] 2017-04-28 00:24
@MikeRyanDev 
https://github.com/pquarme/cli-universal-demo

**Comment by NelsonLamprecht** [comment] 2017-05-03 21:10
I still see this issue with angular universal running 4.0.0. Does 4.1 fix this?

**Comment by BillyQin** [comment] 2017-06-15 09:07
I have Same error in 4.1.0,how to resolve this problem? thanks @kukjevov 
I don't know how to use ɵServerRendererFactory2 , ɵServerRendererFactory2 can replace document in node?thanks @MikeRyanDev

**Comment by sudippal** [comment] 2017-06-15 20:56
@BillyQin  I just figured it out after the long day search, hope this helps

```
// imports
import { NgModule, NgModuleFactory, NgModuleFactoryLoader, RendererFactory2, NgZone } from '@angular/core';
import { ServerModule, ɵServerRendererFactory2 } from '@angular/platform-server';
import { ɵAnimationEngine } from '@angular/animations/browser';
import { NoopAnimationsModule, ɵAnimationRendererFactory } from '@angular/platform-browser/animations';

// declarations
export function instantiateServerRendererFactory(
  renderer: RendererFactory2, engine: ɵAnimationEngine, zone: NgZone) {
   return new ɵAnimationRendererFactory(renderer, engine, zone);
}

const createRenderer = ɵServerRendererFactory2.prototype.createRenderer;
ɵServerRendererFactory2.prototype.createRenderer = function () {
  const result = createRenderer.apply(this, arguments);
  const setProperty = result.setProperty;
  result.setProperty = function () {
    try {
      setProperty.apply(this, arguments);
    } catch (e) {
      if (e.message.indexOf('Found the synthetic') === -1) {
        throw e;
      }
    }
  };
  return result;
}

export const SERVER_RENDER_PROVIDERS = [
  {
    provide: RendererFactory2,
    useFactory: instantiateServerRendererFactory,
    deps: [ɵServerRendererFactory2, ɵAnimationEngine, NgZone]
  }
];

// Module ref.
@NgModule({
  imports: [
    ServerModule,
    NoopAnimationsModule
  ],
  bootstrap: [.....],
  providers: [
    { provide: ........, useClass: ...... },
    SERVER_RENDER_PROVIDERS
  ]
})
```

**Comment by imjaninerd** [comment] 2017-06-20 06:37
thank you! this fixed my issue.

**Comment by kakins** [comment] 2017-09-12 18:08
I am still experiencing this issue, and not really sure what the resolution is.

**Comment by shamoh19** [comment] 2017-10-24 11:34
@sudippal Hi can you please elaborate you solution? I am facing the same issue while server side rendering to serve a fully generated HTML page in server.ts

 ```
> ang_bs@0.0.0 start /Applications/Workspace/Angular/Ang_Bs
    > ts-node src/server.ts

    listening on http://localhost:4001!
    ERROR { ReferenceError: document is not defined
        at DefaultDomRenderer2.selectRootElement (/Applications/Workspace/Angular/Ang_Bs/node_modules/@angular/platform-browser/bundles/platform-browser.umd.js:2818:72)
        at BaseAnimationRenderer.selectRootElement (/Applications/Workspace/Angular/Ang_Bs/packages/platform-browser/animations/src/animation_renderer.ts:166:62)
        at createElement (/Applications/Workspace/Angular/Ang_Bs/node_modules/@angular/core/bundles/core.umd.js:9220:23)
        at createViewNodes (/Applications/Workspace/Angular/Ang_Bs/packages/core/src/view/view.ts:320:1)
        at createRootView (/Applications/Workspace/Angular/Ang_Bs/node_modules/@angular/core/bundles/core.umd.js:12114:5)
        at Object.createProdRootView [as createRootView] (/Applications/Workspace/Angular/Ang_Bs/node_modules/@angular/core/bundles/core.umd.js:12788:12)
        at ComponentFactory_.create (/Applications/Workspace/Angular/Ang_Bs/node_modules/@angular/core/bundles/core.umd.js:9893:46)
        at ComponentFactoryBoundToModule.create (/Applications/Workspace/Angular/Ang_Bs/node_modules/@angular/core/bundles/core.umd.js:3365:29)
        at ApplicationRef_.bootstrap (/Applications/Workspace/Angular/Ang_Bs/packages/core/src/application_ref.ts:670:1)
        at /Applications/Workspace/Angular/Ang_Bs/packages/core/src/application_ref.ts:415:1
    __zone_symbol__currentTask:
    ZoneTask {
        _zone:
        Zone {
            _properties: [Object],
            _parent: [Object],
            _name: 'angular',
            _zoneDelegate: [Object] },
        runCount: 0,
        _zoneDelegates: null,
        _state: 'notScheduled',
        type: 'microTask',
        source: 'Promise.then',
        data: undefined,
        scheduleFn: undefined,
        cancelFn: null,
        callback: [Function],
        invoke: [Function] } }
    Unhandled Promise rejection: document is not defined ; Zone: <root> ; Task: Promise.then ; Value: { ReferenceError: document is not defined
        at DefaultDomRenderer2.selectRootElement (/Applications/Workspace/Angular/Ang_Bs/node_modules/@angular/platform-browser/bundles/platform-browser.umd.js:2818:72)
        at BaseAnimationRenderer.selectRootElement (/Applications/Workspace/Angular/Ang_Bs/packages/platform-browser/animations/src/animation_renderer.ts:166:62)
        at createElement (/Applications/Workspace/Angular/Ang_Bs/node_modules/@angular/core/bundles/core.umd.js:9220:23)
        at createViewNodes (/Applications/Workspace/Angular/Ang_Bs/packages/core/src/view/view.ts:320:1)
        at createRootView (/Applications/Workspace/Angular/Ang_Bs/node_modules/@angular/core/bundles/core.umd.js:12114:5)
        at Object.createProdRootView [as createRootView] (/Applications/Workspace/Angular/Ang_Bs/node_modules/@angular/core/bundles/core.umd.js:12788:12)
        at ComponentFactory_.create (/Applications/Workspace/Angular/Ang_Bs/node_modules/@angular/core/bundles/core.umd.js:9893:46)
        at ComponentFactoryBoundToModule.create (/Applications/Workspace/Angular/Ang_Bs/node_modules/@angular/core/bundles/core.umd.js:3365:29)
        at ApplicationRef_.bootstrap (/Applications/Workspace/Angular/Ang_Bs/packages/core/src/application_ref.ts:670:1)
        at /Applications/Workspace/Angular/Ang_Bs/packages/core/src/application_ref.ts:415:1
    __zone_symbol__currentTask:
    ZoneTask {
        _zone:
        Zone {
            _properties: {},
            _parent: null,
            _name: '<root>',
            _zoneDelegate: [Object] },
        runCount: 0,
        _zoneDelegates: null,
        _state: 'notScheduled',
        type: 'microTask',
        source: 'Promise.then',
        data: undefined,
        scheduleFn: undefined,
        cancelFn: null,
        callback: [Function],
        invoke: [Function] } } ReferenceError: document is not defined
        at DefaultDomRenderer2.selectRootElement (/Applications/Workspace/Angular/Ang_Bs/node_modules/@angular/platform-browser/bundles/platform-browser.umd.js:2818:72)
        at BaseAnimationRenderer.selectRootElement (/Applications/Workspace/Angular/Ang_Bs/packages/platform-browser/animations/src/animation_renderer.ts:166:62)
        at createElement (/Applications/Workspace/Angular/Ang_Bs/node_modules/@angular/core/bundles/core.umd.js:9220:23)
        at createViewNodes (/Applications/Workspace/Angular/Ang_Bs/packages/core/src/view/view.ts:320:1)
        at createRootView (/Applications/Workspace/Angular/Ang_Bs/node_modules/@angular/core/bundles/core.umd.js:12114:5)
        at Object.createProdRootView [as createRootView] (/Applications/Workspace/Angular/Ang_Bs/node_modules/@angular/core/bundles/core.umd.js:12788:12)
        at ComponentFactory_.create (/Applications/Workspace/Angular/Ang_Bs/node_modules/@angular/core/bundles/core.umd.js:9893:46)
        at ComponentFactoryBoundToModule.create (/Applications/Workspace/Angular/Ang_Bs/node_modules/@angular/core/bundles/core.umd.js:3365:29)
        at ApplicationRef_.bootstrap (/Applications/Workspace/Angular/Ang_Bs/packages/core/src/application_ref.ts:670:1)
        at /Applications/Workspace/Angular/Ang_Bs/packages/core/src/application_ref.ts:415:1
```

**Comment by UTGuy** [comment] 2017-11-05 16:53
To solve the SSR issue I just created 3 modules - a Common module, a Browser module, and a Server module...

**app-material.module.ts** (common one)
```
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatCalendar } from '@angular/material';

@NgModule({
    imports: [
        CommonModule,
        //Add imorted material items here - ex. MatCalendar
    ],
    exports: [
        //Add imorted material items here - ex. MatCalendar
    ]
})
export class AppMaterialModule { }
```

**app-material.module.server.ts** (import the common one here)
```
import { NgModule } from '@angular/core';
import { NoopAnimationsModule } from '@angular/platform-browser/animations';
import { AppMaterialModule } from "./app-material.module";

@NgModule({
    imports: [
        AppMaterialModule,
        NoopAnimationsModule
    ],
    exports: [
        AppMaterialModule,
        NoopAnimationsModule
    ]
})
export class AppMaterialServerModule { }
```

**app-material.module.browser.ts** (import the common one here)
```
import { NgModule } from '@angular/core';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { AppMaterialModule } from "./app-material.module";

@NgModule({
    imports: [
        AppMaterialModule,
        BrowserAnimationsModule
    ],
    exports: [
        AppMaterialModule,
        BrowserAnimationsModule
    ]
})
export class AppMaterialBrowserModule { }
```

Now just import the one you need into your main module

**Comment by atariman5000** [comment] 2017-12-12 20:17
I too had this error. However, I was able to resolve the error by importing `import { BrowserAnimationsModule } from '@angular/platform-browser/animations';` into the "app.module.browser.ts" file.

`import { NgModule } from '@angular/core';
import { BrowserModule, DOCUMENT } from '@angular/platform-browser';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';


// App
import { AppModuleShared } from './app.module.shared';
import { AppComponent } from './pages/shared/app/app.component';

@NgModule({
    bootstrap: [ AppComponent ],
    imports: [
        BrowserAnimationsModule,
        BrowserModule,
        AppModuleShared
    ],
    providers: [
        { provide: 'BASE_URL', useFactory: getBaseUrl }
    ]
})
export class AppModule {
}

export function getBaseUrl() {
    return document.getElementsByTagName('base')[0].href;
}
`

**Comment by viraya** [comment] 2018-04-19 07:34
In my case i did add the import of BrowserAnimationsModule to the top of app.module.ts but i forgot to add it to the imports array. after adding it my issue was fixed.

**Comment by tiberiumihai** [comment] 2018-08-07 05:41
In my case I was importing NoopAnimationsModule before BrowserAnimationsModule like this:
```
NoopAnimationsModule,
BrowserAnimationsModule,
```
Just switch the order so that BrowserAnimationsModule is first:
```
BrowserAnimationsModule,
NoopAnimationsModule,
```
