### ISSUE TITLE
@Input properties are not being recognized from angular-cli built component library when extending component and using Barrrels

### ISSUE THREAD

**Issue by sir-captainmorgan21** [angular/angular#25249] opened 2018-08-01 16:11 UTC
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ X ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
So I have my base component...

<pre><code>
import { FormGroup, FormControl, ValidatorFn, Validators, AbstractControl } from '@angular/forms';
import { SnagFormGroup } from '../forms';
import { Component, OnInit, Input } from '@angular/core';
import { IMaskConfig } from '../interfaces';

@Component({
  selector: 'snag-input',
  templateUrl: './snag-input.component.html'
})
export class SnagInputComponent implements OnInit {

  @Input() maskArray: (string | RegExp)[];
  @Input() maxLength: number;
  @Input() minLength: number;
  @Input() regex: RegExp;
  @Input() required: boolean;
  @Input() label: string = '<No Label Provided>';
  @Input() controlName: string;
  @Input() form: SnagFormGroup;
  control: FormControl;
  validators: ValidatorFn[] = [];
  @Input() maskConfig: IMaskConfig = {
    mask: null,
    pipe: null,
    guide: false
  };

  ngOnInit(): void {
    this.validateInputs();
    this.configureInputMask();
    this.buildValidators();
    this.control = new FormControl('', this.validators);
    this.form.addControl(this.controlName, this.control);
  }

  constructor() {}

  hasError(errorName: string): boolean {
    return (this.control.touched || this.form.submitted) && this.control.hasError(errorName);
  }

  isValid(): boolean {
    return this.control.touched && this.control.valid;
  }

  configureInputMask(): void {
    this.maskArray ? this.maskConfig.mask = this.maskArray : null;
  }

  trimToMaxLength(conformedValue: string): string {
    return conformedValue.substring(0, this.maxLength);
  }

  buildValidators(): void {
    this.required ? this.validators.push(Validators.required) : null;
    this.maxLength ? this.validators.push(Validators.maxLength(this.maxLength)) : null;
    this.minLength ? this.validators.push(Validators.minLength(this.minLength)) : null;
    this.regex ? this.validators.push(Validators.pattern(this.regex)) : null;
  }

  validateInputs() {
    if (!this.form) {
      throw 'Dont forget to pass in your SnagFormGroup! EX: <snag-input [form]=\'mySnagFormGroup\'>';
    }
  }

  getFormControl(): AbstractControl {
    return this.form.controls[this.controlName];
  }

}
</code></pre>

And I have my child components 
<pre><code>
import { Component } from '@angular/core';
import { Validators } from '@angular/forms';
import { SnagInputComponent } from '../snag-input';

@Component({
  selector: 'snag-email',
  templateUrl: 'email.component.html'
})

export class EmailComponent extends SnagInputComponent {

  buildValidators(): void {
    this.validators.push(Validators.email);
    this.required ? this.validators.push(Validators.required) : null;
    this.maxLength ? this.validators.push(Validators.maxLength(this.maxLength)) : null;
    this.minLength ? this.validators.push(Validators.minLength(this.minLength)) : null;
  }

}

-------------------------------------------------------------------------------------------

import { Component, Input } from '@angular/core';
import { Validators } from '@angular/forms';
import { SnagInputComponent } from '../snag-input';

@Component({
  selector: 'snag-select',
  templateUrl: 'select.component.html'
})

export class SelectComponent extends SnagInputComponent {

  @Input() options: any[];
  @Input() value: string;
  @Input() name: string;

}

</code></pre>

The child component is just overriding the buildValidators method. Both of these components exist in a component library generated by angular-cli (v6.0.0). In my app that I use to test the library, if I import the module by pathing to /projects, everything is ok. However, when I build the project library and import the module from the /dist folder, the app can no longer recognize the @input properties that are on the child component from the extended base component. I get the following when I try to build the app with aot, and these errors show up in my IDE also. As you can see every input that comes from the base model is not being recognized.

![image](https://user-images.githubusercontent.com/7041924/43542470-14aa934c-959b-11e8-9218-a831847f267a.png)

<pre><code>
ERROR in : Can't bind to 'form' since it isn't a known property of 'snag-email'.
1. If 'snag-email' is an Angular component and it has 'form' input, then verify that it is part of this module.
2. If 'snag-email' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. (" <div *ngIf="this.formState != 'fade'">
    <div class="input-row">
      <snag-email class="input" [ERROR ->][form]="form" [label]="'Email'" [required]="true" [controlName]="'email'"></snag-email>
      <snag-p")
: Can't bind to 'label' since it isn't a known property of 'snag-email'.
1. If 'snag-email' is an Angular component and it has 'label' input, then verify that it is part of this module.
2. If 'snag-email' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("his.formState != 'fade'">
    <div class="input-row">
      <snag-email class="input" [form]="form" [ERROR ->][label]="'Email'" [required]="true" [controlName]="'email'"></snag-email>
      <snag-phone [form]="f")
: Can't bind to 'required' since it isn't a known property of 'snag-email'.
1. If 'snag-email' is an Angular component and it has 'required' input, then verify that it is part of this module.
2. If 'snag-email' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("fade'">
    <div class="input-row">
      <snag-email class="input" [form]="form" [label]="'Email'" [ERROR ->][required]="true" [controlName]="'email'"></snag-email>
      <snag-phone [form]="form" [label]="'Pho")
: Can't bind to 'controlName' since it isn't a known property of 'snag-email'.
1. If 'snag-email' is an Angular component and it has 'controlName' input, then verify that it is part of this module.
2. If 'snag-email' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("lass="input-row">
      <snag-email class="input" [form]="form" [label]="'Email'" [required]="true" [ERROR ->][controlName]="'email'"></snag-email>
      <snag-phone [form]="form" [label]="'Phone Number'" [contr")
</code></pre>

## Environment

<pre><code>
Angular version: 6.0.0
</code></pre>

**Comment by sir-captainmorgan21** [comment] 2018-08-01 18:50
So I have found something, and I have updated my issue

**Comment by sir-captainmorgan21** [comment] 2018-08-01 19:01
@splincode @ericmartinezr @trotyl  I have updated my issue. I was able to find out more information. Can you please review.

**Comment by splincode** [comment] 2018-08-01 19:05
@sir-captainmorgan21 what is snag-email?
where did you get this component?

**Comment by splincode** [comment] 2018-08-01 19:11
Add please link to repo or stackblitz example your code for reproduce

**Comment by splincode** [comment] 2018-08-01 19:17
You inherit from the class, but you do not call the constructor in the child classes

You need call operator super

```ts
class EmailComponent extends SnagInputComponent {
  constructor() {
     super();
  }
}
```

**Comment by jotatoledo** [comment] 2018-08-01 19:28
The input decorators wont be inherited. You need to explicitly make angular aware of that by doing the following changes:

```
@Component({
  selector: 'snag-email',
  templateUrl: 'email.component.html',
  inputs: ['maxLength', .... ]
})
```

More info can be found in [the docs](https://angular.io/api/core/Directive#inputs)

**Comment by splincode** [comment] 2018-08-01 19:49
@sir-captainmorgan21 add stackblitz example

**Comment by sir-captainmorgan21** [comment] 2018-08-02 02:09
@splincode stackblitz isn't saving my changes. Looks like other people are running into this also.

**Comment by sir-captainmorgan21** [comment] 2018-08-02 02:49
@splincode the original repo was private, but I created this temp one. Here you go. 

https://github.com/sir-captainmorgan21/temp-snag-forms

**Comment by trotyl** [comment] 2018-08-02 02:58
> `"snagajob-style": "git+ssh://git@github.com:Snagajob/Lib.Web.Style.git#snag-future"`

@sir-captainmorgan21 This is not public.

**Comment by sir-captainmorgan21** [comment] 2018-08-02 03:01
@trotyl you can remove it and remove 
`@import 'snagajob-style/theme/snag.scss';` from styles.scss

**Comment by trotyl** [comment] 2018-08-02 03:43
@sir-captainmorgan21 Remove **ALL BARREL**  usage from library and it would work.

e.g.

```typescript
import { SnagInputComponent } from '../snag-input';
```

to

```typescript
import { SnagInputComponent } from '../snag-input/snag-input.component';
```

This is not about inheritance, but metadata extraction.

**Comment by sir-captainmorgan21** [comment] 2018-08-02 04:09
@trotyl ok! Will there be anything done to allow for Barrels in the future?

**Comment by sir-captainmorgan21** [comment] 2018-08-02 13:16
@trotyl thanks for the help. That did it. I updated the title to mention barrels also. You can close this issue if you like.

**Comment by sir-captainmorgan21** [comment] 2018-08-02 13:48
@trotyl Sounds good. Maybe you should be?

**Comment by trotyl** [comment] 2018-08-02 14:38
@sir-captainmorgan21 Possibly take GDE as a first step goal. (It's totally off-topic...)

**Comment by softEngJason** [comment] 2018-08-22 00:42
@mhevery By adding the `fixed by Ivy` label, does this mean that we will be able to use barrels again in Ivy?

**Comment by gatimus** [comment] 2019-03-05 17:45
Wait I didn't know metadata was inherited. I assumed you would have to write `EmailComponent` like:

    @Component({
      selector: 'snag-email',
      templateUrl: 'email.component.html',
      inputs: [
        'maskArray',
        'maxLength',
        'minLength',
        'regex',
        'required',
        'label',
        'controlName',
        'form',
        'maskConfig'
      ]
    })
    export class EmailComponent extends SnagInputComponent { ... }

Can someone link me to how metadata inheritance works? All I can find is the feature being closed here https://github.com/angular/angular/issues/7968#issuecomment-219865739 .

Also I'm having similar issue extending a component from a library so I don't have the option of not using the barrel, how can I work around that?

**Comment by alxhub** [comment] 2020-05-28 16:39
I'm going to close this as a duplicate of #33121, which has some additional discussion of the problem. It'll be tracked there from now on, but in general the status hasn't changed. This is a confirmed bug in `ngc`, and the fix is to migrate to Ivy which doesn't use metadata and doesn't have the same limitations.

**Closed by alxhub** 2020-05-28 16:39 UTC
Labels: comp: compiler, fixed by Ivy, freq1: low, severity3: broken, type: bug/fix
