### ISSUE TITLE
HttpParams do not encoode a stringified object correctly

### ISSUE THREAD

**Issue by demiro** [angular/angular#18884] opened 2017-08-25 23:09 UTC
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

```
const includeStr = JSON.stringify({include: 'match-timeline-events'});
const params: HttpParams = new HttpParams().set('filter', includeStr);
```
generates this in http.get

> http://localhost:3000/api/...?filter=%7B%2‌​2include%22:%22match‌​-timeline-events%22%‌​7D

## Expected behavior
I shoul get this:
> http://localhost:3000/api/...?filter=%7B%2‌​2include%22%3A%22match‌​-timeline-events%22%‌​7D

## What is the motivation / use case for changing the behavior?
being able to use more complex url params than just simple string key/value pairs

it seems this forcefully denies encoding of the colon
https://github.com/angular/angular/blob/54be25a7a1b481482b5956719e1ce4f8c0d4e8cc/packages/common/http/src/params.ts#L60

## Environment

<pre><code>
Angular version: 4.3.6
Browser:
- [x ] Chrome (desktop) version 60.0.3112.101
 
For Tooling issues:
- Node version: 6.10.2
- Platform:  Windows

**Comment by tiangolo** [comment] 2017-11-25 20:59
I created a PR to solve this here: https://github.com/angular/angular/pull/19710 .

---

I also created a package to solve it (at least while it is reviewed / merged) for the case of `HttpClient`. It's a simple drop-in replacement that modifies the minimum to fix the problem. It works with just changing one import.

Check it here: https://github.com/tiangolo/ngx-http-client

**Comment by SmallhillCZ** [comment] 2018-12-22 10:42
Just to add, same problem lies with plus, which is not encoded and on the server side usually decoded as space. ISO Date representation therefore becomes not legible to Date object.

Example: `2019-01-01T00:00:00.000+01:00` becomes `2019-01-01T00:00:00.000 01:00` which in case of Mongoose becomes `Error('Cast to date failed for value...')`

**Comment by rgunczer** [comment] 2019-04-30 21:14
Is there any workaround for this? Angular 7

**Comment by earshinov** [comment] 2019-04-30 22:02
@rgunczer , I know it is ugly, but we are currently using this:

utils.ts:
```
/**
 * Encode a dictionary of query params into a string
 *
 * Example:
 *
 *   > encodeParams({ a: 1, b: 2 })
 *   "a=1&b=2"
 *
 * Use it instead of passing `params` to `HttpClient.get` and `HttpClient.post`,
 * because the latter have a known issue with encoding '+':
 * https://github.com/angular/angular/issues/18884
 */
export function encodeParams(params: {[key: string]: string}) {
  if (!params)
    return '';
  const ret = [];
  for (const name in params) {
    if (params.hasOwnProperty(name)) {
      const value = params[name];
      if (value != null)
        ret.push(`${name}=${encodeURIComponentFull('' + value)}`);
    }
  }
  return ret.join('&');
}

// encodeURIComponent() will not encode: ~!*()'
// https://stackoverflow.com/a/44431811
export function encodeURIComponentFull(str: string): string {
  str = encodeURIComponent(str);

  str = str.replace('(', '%28');
  str = str.replace(')', '%29');
  str = str.replace('*', '%29');
  str = str.replace('!', '%21');
  str = str.replace('~', '%7E');
  str = str.replace('\'', '%27');

  return str;
}
```

Usage example:

```
makeSomeRequest(params?: StringMap<string>): Observable<SomeResponse> {
  return this.http.get<SomeResponse>(`some-url/?${encodeParams(params)}`);
})
```

**Comment by mruzicka** [comment] 2019-05-01 18:00
Hi, I've created the following custom `HttpParameterCodec` as a workaround:
```typescript
import { HttpUrlEncodingCodec } from '@angular/common/http';
  
export class UrlParameterEncodingCodec extends HttpUrlEncodingCodec {

  encodeKey(key: string): string {
    return encodeURIComponent(key);
  }

  encodeValue(value: string): string {
    return encodeURIComponent(value);
  }

}
```
And I use it like this: 
```typescript
export class AppComponent {
  static readonly ISO_8601_DATE_FORMAT = 'yyyy-MM-ddTHH:mm:ss.sssZ';
  static readonly URL_PARAMETER_ENCODING_CODEC = new UrlParameterEncodingCodec();

...

  query() {
    this.queryService.execute(new HttpRequest('GET', '/api/endpoint', {
      params: new HttpParams({
        fromObject: {
          datePublished__lt: formatDate(Date.now(), AppComponent.ISO_8601_DATE_FORMAT, 'en-US'),
          fields: 'amount'
        },
        encoder: AppComponent.URL_PARAMETER_ENCODING_CODEC
      }),
      headers: new HttpHeaders({
        'X-Order': 'datePublished'
      })
    })).subscribe(

...

    );
  }

...

}
```

**Comment by AneelaBrister** [comment] 2019-05-16 17:59
@mruzicka 's solution worked great for me in Angular 6.

**Comment by alxhub** [comment] 2020-05-29 21:53
I'm going to close this as a duplicate of #11058, which tracks the chaos of replacements that `HttpUrlEncodingCodec` performs.

**Closed** 2020-05-29 21:53 UTC
Labels: comp: common/http, freq1: low, severity3: broken, triage #1, type: bug/fix
