### ISSUE TITLE
angular.io about page bug

### ISSUE THREAD

**Issue by Kirkhammetz** [angular/angular#2184] opened 2015-05-27 17:18 UTC
Don't know if it's the right place to report it but if you open a bio on the about of angular.io then close it and reopen another one it fail to bind.

![immagine](https://cloud.githubusercontent.com/assets/5617452/7842625/b5a102b2-04a4-11e5-9cb8-761eebb4bd7e.jpg)

**Comment by gdi2290** [comment] 2015-05-27 17:35
https://github.com/angular/angular.io

**Comment by Kirkhammetz** [comment] 2015-05-27 18:03
Ok, thanks sorry for the wrong repo.

**Comment by pkozlowski-opensource** [comment] 2015-05-28 02:30
Duplicate of https://github.com/angular/angular.io/issues/132

**Closed by pkozlowski-opensource** 2015-05-28 02:30 UTC
