### ISSUE TITLE
Safari: angular input file doesn't become valid when you uploaded file 

### ISSUE THREAD

**Issue by zoeyzou** [angular/angular#25680] opened 2018-08-27 08:02 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Version: Angular 6
For both reactive form and template-driven form, the input type file doesn't change to valid after you uploaded a file. This issue is only found on safari, and behavior absolutely well on chrome and firefox.

## Expected behavior

When user upload a file using the input, the class "ng-invalid" should be "ng-valid" and "ng-pristine" be "ng-dirty".

## Minimal reproduction of the problem with instructions

I've made a snippet to reproduce this problem. Please open it on safari to see.
https://stackblitz.com/edit/angular-inputbug

## What is the motivation / use case for changing the behavior?

Many users are using safari on Mac os, so if the form cannot be submitted or the form cannot be validated, they are both affecting user experience and use case.

## Environment

<pre><code>
Angular version: 6

Browser:
- [x] Safari (desktop) version 11.1.2
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by trotyl** [comment] 2018-08-27 08:09
Duplicate of https://github.com/angular/angular/issues/7341.

Without `ControlValueAccessor` support the control got no value thus required validation failed always.

**Comment by pkozlowski-opensource** [comment] 2018-08-27 08:30
Closing as a duplicate of #7341, thnx @trotyl

**Closed by pkozlowski-opensource** 2018-08-27 08:30 UTC

**Comment by zoeyzou** [comment] 2018-08-27 09:31
Thanks for pointing out. 
Here's the solution in case someone navigates here: https://stackoverflow.com/questions/41889384/angular2-validation-for-input-type-file-wont-trigger-when-changing-the-fi/41938495#41938495
