### ISSUE TITLE
Angular 2,4 website angular routing not working after deploy on server.

### ISSUE THREAD

**Issue by kaushiksunil** [angular/angular#20066] opened 2017-11-01 06:48 UTC
## I'm submitting a...

i am deploy dist folder on server then website routing not working after deploy on server. Routing isn't working during go to next component through the menu then refresh that page it's giving error like 404 not found.

Please help me.

**Comment by trotyl** [comment] 2017-11-01 07:19
Duplicate of #3861, #6315, #8788, #9696, #10260, #10466, #10627, #12365, #14727, #19009.

**Closed** 2017-11-01 08:03 UTC
