### ISSUE TITLE
please update the "Upgrading from Angular JS" section of documentation to optionally use UpgradeAdapter

### ISSUE THREAD

**Issue by sharathc10** [angular/angular#19415] opened 2017-09-26 18:09 UTC
I recently worked on trying to get an existing Angular JS module to use a new Angular 4 service.  I  followed the instructions on the angular.io Upgrade section.  After trying it and not succeeding, I tried using the UpgradeAdapter based on the following book (ng-book The Complete Book on Angular4 by Murray, Coury, Lerner, Taborda).    I found using the UpgradeAdapter with downgradeNg2Provider to be much simpler than what you had recommended in the documentation i.e. use downgradeInjectable.  Using UpgradeAdapter made is also easy to bootstrap the application.  I am sure the downgradeInjectable works but the process seems to be much more complicated than it needs to be.  

## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Simplify upgrade process 

## What is the motivation / use case for changing the behavior?

See above

## Environment

<pre><code>
Angular version: 4.0.2

Browser:
- [ ] Chrome (desktop) version 61.0.3163.100
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX   6.11.2
- Platform:   Mac

Others:

</code></pre>

**Comment by gkalpak** [comment] 2017-09-26 18:55
UpgradeAdapter (which belongs to the old "dynamic" ngUpgrade (imported from `@angular/upgrade`) will be deprecated since v5.x and is not recommended for new projects. Thus we will not update the developer guide with examples showing `UpgradeAdapter`.

Instead you should use the newer, AoT-compatible ngUpgrade (imported from `@angular/upgrade/static`).

##
FWIW, `downgradeNg2Provider()` is [just a wrapper][1] around `downgradeInjectable()`, so if that isn't working the problem is lying somewhere else.

If you have found something that is wrong in the docs (e.g. a broken example) or you are running into what you believe is a bug in `@angular/upgrade/static`, please create a new issue with detailed instructions to reproduce the problem (ideally a minimal live reproduction).

You can use [this template][2]) for the reproduction (which is also a good illustration of how to bootstrap a hybrid app using `@angular/upgrade/static`).

<sub>Closing since this is not actionable.</sub>

[1]: https://github.com/angular/angular/blob/e889c68aff33adeddf2ea9931ded9c70c86ab2cf/packages/upgrade/src/dynamic/upgrade_adapter.ts#L469
[2]: http://plnkr.co/edit/tpl:BXA3Onj8CkbmfuDKXu1N?p=preview

**Closed by gkalpak** 2017-09-26 18:55 UTC

**Comment by sharathc10** [comment] 2017-09-26 19:56
George,

Thanks for your quick response.   Can you then help me with this.  For some reason, the following code doesn't work and I am not sure why:

export class AppModule {
  constructor(private upgrade: UpgradeModule) { }
  ngDoBootstrap() {
    this.upgrade.bootstrap(document.body, ['heroApp'], { strictDi: true });
  }
}

ngDoBootstrap doesn't get called
I had to move -----   this.upgrade.bootstrap(document.body, ['heroApp'], { strictDi: true }); ---- into the constructor for it to work.  Why is the ngDoBootstrap() not being called.  Am I missing something?

**Comment by gkalpak** [comment] 2017-09-26 20:00
How are you bootstraping `AppModule`?
What does your `NgModule({...})` decorator look like? (For example, if you have `bootstrap` components, then `ngDoBootstrap()` won't get called iirc.)

**Comment by sharathc10** [comment] 2017-09-26 21:23
George,

See my responses below:
1.  AppModule bootstrapped as follows:
import { platformBrowserDynamic } from "@angular/platform-browser-dynamic";
platformBrowserDynamic().bootstrapModule(AppModule)

2.  NgModule does not have bootstrap in it.  It looks as follows:
@NgModule({
    exports: [
        ...
    ],
    imports: [
       ....
    ],
    providers: [
        ....
    ],
})
export class xxxModule {
}

**Comment by gkalpak** [comment] 2017-09-26 22:46
That is very weird. Could you try to reproduce with [this template][1]?

[1]: http://plnkr.co/edit/tpl:BXA3Onj8CkbmfuDKXu1N?p=preview

**Comment by sharathc10** [comment] 2017-09-26 23:45
I do apologize - I sent you the wrong @NgModule - this is what it looks like and it does have the bootstrap - 

@NgModule({
    providers: [
            <blank>    ],
    declarations: [
           <blank>
    ],
    imports: [
        ......
    ],
    exports: [
        <blank>
    ],
    entryComponents: [
        <blank> 
    ],
    bootstrap: [
       name of component here
    ],
})
export class AppModule {

    constructor(private upgrade: UpgradeModule) {
            this.upgrade.bootstrap(document.body, ['myApp'], { strictDi: true });
    }
}

I modified it by removing the bootstrap component and putting the component in entryComponents and modified the class as follows:

export class AppModule {
  constructor(private upgrade: UpgradeModule) { }
  ngDoBootstrap() {
    this.upgrade.bootstrap(document.body, ['myApp'], { strictDi: true });
  }
}
Now the Angular 4 components don't load and I get no errors.  The good news is that the upgrade.bootstrap is working and loads the angularJS module.  Is there any reason I can't put this.upgrade.bootstrap... in the constructor or maybe you have another suggestion?

**Comment by gkalpak** [comment] 2017-09-27 08:33
My guess is that the Angular components aren't loading, because you haven't downgraded the root component. As documented, in hybrid apps, AngularJS needs to own the root of the template (because that sets up some things that are needed for upgraded/downgraded components.

As shown in [the template][1] I shared above, if you want Angular to be the root element, you can downgrade your Angular `AppComponent` and use it in your `index.html`:

**index.html**
```html
<body>
  <demo-app>Loading...</demo-app>
</body>
```

**demo-app.component.ts**
```ts
@Component({
  selector: 'demo-app',
  ...
})
export class AppComponent {}
```

**ng1.module.ts**
```ts
angular.
  module('ng1App', []).
  ...
  directive('demoApp', downgradeComponent({component: AppComponent});
```

##
If you _must_ call `upgrade.bootstrap()` in the constructor (which there should be no reason to), you could try the following work around:

**demo-app.module.ts**
```ts
export function getRootScope(upgrade: UpgradeModule) {
  return upgrade.$inejctor.get('$rootScope');
}

@NgModule({
  ...
  providers: [
    {provide: '$scope', useFactory: getRootScope, deps: [UpgradeModule]}
  ],
  bootstrap: [DemoAppComponent]
})
export class DemoAppModule {
  constructor(upgrade: UpgradeModule) {
    upgrade.bootstrap(...);
  }
}

##
<sub>It seems that this has turned into a support request and GitHub is not the right place for that. There are [more appropriate places][2] for getting help with these types of issues :wink:</sub>

[1]: http://plnkr.co/edit/tpl:BXA3Onj8CkbmfuDKXu1N?p=preview
[2]: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

**Comment by sharathc10** [comment] 2017-09-27 12:03
Thanks again and I will try these...also one last question - what are timelines for Angular 5?

**Comment by gkalpak** [comment] 2017-09-27 13:51
Here is an approximate schedule: https://github.com/angular/angular/blob/master/docs/RELEASE_SCHEDULE.md

**Comment by sharathc10** [comment] 2017-09-27 14:05
Thanks!
