### ISSUE TITLE
@angular/compiler-cli - better error reporting for build error "cannot find module of undefined"

### ISSUE THREAD

**Issue by babeal** [angular/angular#25956] opened 2018-09-14 02:50 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
If a module is incorrectly imported the @angular/compiler-cli throws an exception that is impossible to interpret without debugging node and stepping through the bundler code module by module.  

![image](https://user-images.githubusercontent.com/4511994/45526997-331cab00-b79f-11e8-9145-2ba8ec88a046.png)

## Expected behavior
The exception thrown includes more information about what the compiler can't find and where it came from.  

## Minimal reproduction of the problem with instructions
Just forget to export a component out of the index file of an ng-packagr project or try to import by folder instead of folder/index etc.  There are many ways to get the dreaded "Cannot read property of undefined" error

## What is the motivation / use case for changing the behavior?
Better error reporting during compilation.

## Environment

<pre><code>
Angular version: 6.1.2

Browser:
N/A
 
For Tooling issues:
- Node version: 8.11.1
- Platform:  Mac

Others:

</code></pre>

**Comment by trotyl** [comment] 2018-09-14 10:07
Duplicate of https://github.com/angular/angular/issues/20931?

**Comment by babeal** [comment] 2018-09-14 11:30
@trotyl, the 20931 issue is related to the same code though slightly different.  There are going to be some cases where a developer imports incorrectly or forgets to export certain symbols that causes a module resolution failure where the added information about what imported the missing symbol will help in finding the problem.  It is about improving the error messages from the cli compiler.  You can lump them together if you want to keep things tidy.  I’ve just run into this issue several times in the last week and keep having to debug to find out the cause so I though a try catch and rethrow right there will really help :)

**Comment by pkozlowski-opensource** [comment] 2020-02-21 09:28
Those situations are now correctly reported in Angular v9 with the ivy compiler: https://ng-run.com/edit/adZWspXSGKvirUkbO1p6

The example error message:

> src/app/app.module.ts(10,17): error TS-991010: Value at position 1 in the NgModule.declarations of AppModule is not a reference: undefined

**Closed by pkozlowski-opensource** 2020-02-21 09:28 UTC
Labels: comp: core, fixed by Ivy, freq4: critical, severity1: confusing, type: bug/fix
