### ISSUE TITLE
Angular 8 IE Issues

### ISSUE THREAD

**Issue by Seemspyo** [angular/angular#30766] opened 2019-05-31 06:32 UTC
Hi. I updated my project to version 8.0.0 and it work pretty fine on modern browser.

But there is some issue supporting legacy browsers like IE.

**1. Can't run local test build**
When I try <code>ng serve</code> and open it on IE after update, it got an script error and the app didn't initialize at all.

**2. Animation not working**
I use some Angular Animation in my project, especially for routing. But some animation script got broke on IE after update. I found the error message on console and it says _"cannot find position of null"_, _"cannot find toString of null"_.

**3. ngIf not work propery**
Some <code>ngIf</code> are not work propery on IE. What I found my project is, toggle element with <code>ngIf</code> once appears, it is not disappears but keep appends. Even though the boolean value have changed propery.

Do I need to edit config like angular.json or tsconfig? or import special module for legacy browser?

Here is my project [https://eunsatio.io](https://eunsatio.io)

**Comment by gkalpak** [comment] 2019-05-31 09:15
It is hard to investigate the issue without a minimal reproduction with step-by-step instructions.
Please provide a minimal reproduction (e.g. a repo we can check out and run) and detailed instructions on how to reproduce the issues (including browser versions affected).

**Comment by gkalpak** [comment] 2019-05-31 09:25
Actually, this seems like a duplicate of #30765.
(Can't really tell due to the lack of info, but feel free to submit a new issue with more details if it turns out to be a different problem.)

**Closed by gkalpak** 2019-05-31 09:25 UTC
Labels: comp: animations, comp: common, severity5: regression
