### ISSUE TITLE
Angular Language Service in VSCode extension - Displays 'not a known element' error even after NO_ERRORS_SCHEMA added. Compiles fine with build

### ISSUE THREAD

**Issue by louzena** [angular/angular#42356] opened 2021-05-26 17:12 UTC
# 🐞 bug report

### Is this a regression? 

Not that I'm aware of  

### Description

Angular Language Service displays a compiler error when referencing a custom HTML element even when NO_ERROR_SCHEMA (or CUSTOM_ELEMENTS_SCHEMA) added to the SCHEMAS array in the TestBed configuration.  The test compiles fine using `ng build`

Error message is

'app-about' is not a known element:
1. If 'app-about' is an Angular component, then verify that it is part of this module.
2. If 'app-about' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.

## Bug Type

- [x ] Angular Language Service VSCode extension
- [  ] Angular Language Service server

## Reproduction

````

import { Component, CUSTOM_ELEMENTS_SCHEMA, DebugElement, NO_ERRORS_SCHEMA } from '@angular/core';
import { ComponentFixture, TestBed } from '@angular/core/testing';
import { By } from '@angular/platform-browser';
import { AboutComponent } from './about.component';

@Component({   
  template: '<app-about><span>testing content projection</span></app-about>'   
  })
export class ContentProjectionTesterComponent {   
}

describe('AboutComponent', () => {
   let component: AboutComponent;  
   let fixture: ComponentFixture<AboutComponent>;

   let ngContent : DebugElement;

   beforeEach(async () => {
     
     await TestBed.configureTestingModule({          
      schemas: [ NO_ERRORS_SCHEMA],
      declarations: [AboutComponent]     
     })
     .compileComponents();     
   });

   beforeEach(() => {
     fixture = TestBed.createComponent(AboutComponent);
     component = fixture.componentInstance;
     fixture.detectChanges();     
   });

   it('should create', () => {
     expect(component).toBeTruthy();
   });

````

**Expected behavior**

There shouldn't be a compiler error 

### **Logs**

No errors in the log

## 🌍  Your Environment
**Angular Version:**
<pre><code>

Angular CLI: 11.2.0
Node: 12.16.2
OS: win32 x64

Angular: 11.0.9
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.7
@angular-devkit/build-angular   0.1100.7
@angular-devkit/core            11.0.7
@angular-devkit/schematics      11.2.0
@angular/cli                    11.2.0
@schematics/angular             11.2.0
@schematics/update              0.1102.0
rxjs                            6.6.7
typescript                      4.0.7

</code></pre>

Extension Version:
<pre><code>

12.0.2

</code></pre>

VSCode Version:
<pre><code>

Version: 1.56.2 (user setup)
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-12T17:13:13.157Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19042

</code></pre>

Operating System:
<pre><code>

Windows 10 Pro 
Version	10.0.19042 Build 19042

</code></pre>

**Comment by atscott** [comment] 2021-06-01 22:44
Hi @louzena, this is because the AOT compiler has no knowledge of the test bed. While the `TestBed` configuration itself will compile and run just fine because you added `NO_ERRORS_SCHEMA`, you need to tell the AOT compiler to ignore your class by adding `jit: true` to the component metadata. This would be the preferred solution here. 
Another option would be to declare another module in your test file like: 
```
@Component({   
  template: '<app-about><span>testing content projection</span></app-about>'   
  })
export class ContentProjectionTesterComponent {   
}

@NgModule({          
      schemas: [ NO_ERRORS_SCHEMA],
      declarations: [AboutComponent]     
     })
export class TestModule {}

...

TestBed.configureTestingModule({imports: [TestModule]});
...
  
```
This works because the way you have written your test currently, the AOT compiler sees the component as not having a module at all, so it compiles it as-is. This works by declaring it in a test module that the AOT compiler can see with `NO_ERRORS_SCHEMA`.

Closing as working as intended.

**Closed by atscott** 2021-06-01 22:44 UTC
Labels: comp: compiler, comp: language-service

**Comment by louzena** [comment] 2021-06-03 22:34
Thank you for the detailed explanation - used `jit: true` in this instance and no compiler errors . Good to know about the option of declaring another module.
