### ISSUE TITLE
I have no sourcemaps for CSS

### ISSUE THREAD

**Issue by smartm0use** [angular/angular#10232] opened 2016-07-22 08:28 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I created a new Component and set style using `styleUrl` property. This works with no problems, but i can't debug it in my browser.

**Expected/desired behavior**
Since Angular2 injects the code within `<style>` tag it prevents styles code to be paired with CSS source files. I would like to get sourcemaps for CSS files.

**Reproduction of the problem**
Here is an example of Component:

```
import {Component} from '@angular/core';

@Component({
    moduleId: module.id,
    selector: 'home',
    templateUrl: 'home.component.html',
    styleUrls: ['home.component.css']
})

export class HomeComponent {
}
```

**What is the expected behavior?**
I expect to see sourcemaps for style files in Chrome inspector, but this doesn't happen.

**What is the motivation / use case for changing the behavior?**
I would see CSS files mapped in sourcemaps to easily debug style in my projects.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** Chromium 50.0.2661.102 Built on Ubuntu 14.04, running on LinuxMint 17.2 (64-bit)
 
* **Language:** TypeScript 1.8.10

**Comment by vicb** [comment] 2016-07-22 15:28
Duplicate of #9664

**Closed by vicb** 2016-07-22 15:28 UTC
