### ISSUE TITLE
ServiceWorker generated by cli with base-href gets registered but doesn't cache any javascript assets

### ISSUE THREAD

**Issue by piyushgupta1** [angular/angular#24050] opened 2018-05-22 16:09 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

ServiceWorker generated by cli with base-href get registered in the browser. So for context i am generating the production bundle with a base-href 'pe360'. and i followed this (https://github.com/angular/angular-cli/issues/8515#issuecomment-378083959) to get the service worker registered. So now the service worker gets registered 
![screen shot 2018-05-22 at 9 23 45 pm](https://user-images.githubusercontent.com/13146476/40375187-8beebd72-5e08-11e8-9d51-374b382a733d.png)

 but i get this error in console after its registered 
![screen shot 2018-05-22 at 9 23 59 pm](https://user-images.githubusercontent.com/13146476/40376165-3d9a32c0-5e0b-11e8-881c-2253331ce0b7.png)

And nothing gets cached. 

ngsw-config.json
```json
{
  "index": "/index.html",
  "assetGroups": [
    {
      "name": "app",
      "installMode": "prefetch",
      "resources": {
        "files": [
          "/favicon.ico",
          "/manifest.json",
          "/index.html"
        ],
        "versionedFiles": [
          "/*.bundle.css",
          "/*.bundle.js",
          "/*.chunk.js"
        ]
      }
    },
    {
      "name": "assets",
      "installMode": "lazy",
      "updateMode": "prefetch",
      "resources": {
        "files": [
          "/assets/**"
        ]
      }
    }
  ]
}
```
generated ngsw.json | 'pe360' is base-href
```json
{
  "configVersion": 1,
  "index": "/pe360/index.html",
  "assetGroups": [
    {
      "name": "app",
      "installMode": "prefetch",
      "updateMode": "prefetch",
      "urls": [
        "/pe360/favicon.ico",
        "/pe360/index.html",
        "/pe360/manifest.json",
        "/pe360/0.913792f4c0f99d0ac151.chunk.js",
        "/pe360/1.9a95994e0db526f48705.chunk.js",
        "/pe360/10.63fa9a615a40113c0369.chunk.js",
        "/pe360/11.fa2f3905ac575bbd24ef.chunk.js",
        "/pe360/12.1a967e0a3abad9ef53ad.chunk.js",
        "/pe360/13.8f1557eb38c37c9907e1.chunk.js",
        "/pe360/14.d31f15e2ba3ad3d19f42.chunk.js",
        "/pe360/15.7e4ab1848cf38498f29d.chunk.js",
        "/pe360/16.e42d24af4de5c036b273.chunk.js",
        "/pe360/17.8454183fb73f1c28e3fc.chunk.js",
        "/pe360/18.fa25797f15b0d4fdc1af.chunk.js",
        "/pe360/19.25750574380bad5246a1.chunk.js",
        "/pe360/2.b40d07d23374f0b4f833.chunk.js",
        "/pe360/20.27341138d94e72cf8971.chunk.js",
        "/pe360/21.2f68a9b926c924e20add.chunk.js",
        "/pe360/22.4b57d092ac6c78aac4b7.chunk.js",
        "/pe360/23.b611af10dadbaf93dc79.chunk.js",
        "/pe360/24.3b9726d1e0293cf7abad.chunk.js",
        "/pe360/25.bc360cf31cf7bccbb18a.chunk.js",
        "/pe360/3.aff1d114ec138e9e950b.chunk.js",
        "/pe360/4.c84b50aaeca2467400d2.chunk.js",
        "/pe360/5.ebd525b487571d2e0cd9.chunk.js",
        "/pe360/6.1480a309fbfc39f43197.chunk.js",
        "/pe360/7.cf86cea2b93c0d4d45a5.chunk.js",
        "/pe360/8.506e3612f9f31fec8c24.chunk.js",
        "/pe360/9.d09a110aa5aa1c4681b7.chunk.js",
        "/pe360/inline.dcbf348730d881f88c71.bundle.js",
        "/pe360/main.e1f6c7c48172401c1dcd.bundle.js",
        "/pe360/polyfills.b87a83c1200f3d1984c6.bundle.js",
        "/pe360/styles.791cbc655813524c80af.bundle.css"
      ],
      "patterns": []
    },
    {
      "name": "assets",
      "installMode": "lazy",
      "updateMode": "prefetch",
      "urls": [
        "/pe360/assets/home-bg.png",
        "/pe360/assets/ngx-rocket-logo.png",
        "/pe360/assets/fonts/OpenSans-Bold.ttf",
        "/pe360/assets/fonts/OpenSans-Regular.ttf",
        "/pe360/assets/fonts/WorkSans-Light.ttf",
        "/pe360/assets/fonts/WorkSans-Regular.ttf",
        "/pe360/assets/icon/Star@3x.png",
        "/pe360/assets/icon/arrow-down.png",
        "/pe360/assets/icon/arrow-up-box.png",
        "/pe360/assets/icon/fire.png",
        "/pe360/assets/icon/flag-header.png",
        "/pe360/assets/icon/go-back.png",
        "/pe360/assets/icon/ico_arrow-right-circle.png",
        "/pe360/assets/icon/ico_arrow-right-triangle.png",
        "/pe360/assets/icon/ico_caret-right.png",
        "/pe360/assets/icon/ico_delete.png",
        "/pe360/assets/icon/ico_edit.png",
        "/pe360/assets/icon/ico_export.png",
        "/pe360/assets/icon/ico_filter.png",
        "/pe360/assets/icon/ico_flagged.png",
        "/pe360/assets/icon/ico_pie-chart.png",
        "/pe360/assets/icon/ico_print.png",
        "/pe360/assets/icon/ico_raising_fund.png",
        "/pe360/assets/icon/ico_search.png",
        "/pe360/assets/icon/ico_share.png",
        "/pe360/assets/icon/ico_star.png",
        "/pe360/assets/icon/ico_star_gray.png",
        "/pe360/assets/icon/ico_star_green.png",
        "/pe360/assets/icon/ico_star_purple.png",
        "/pe360/assets/icon/ico_star_yellow.png",
        "/pe360/assets/icon/ico_unflagged.png",
        "/pe360/assets/icon/ico_unsorted.png",
        "/pe360/assets/icon/location-header.png",
        "/pe360/assets/icon-selected/ico_filter.png",
        "/pe360/assets/icon-selected/ico_flagged.png",
        "/pe360/assets/icon-selected/ico_pie-chart.png"
      ],
      "patterns": []
    }
  ],
  "dataGroups": [],
  "hashTable": {
    "/pe360/0.913792f4c0f99d0ac151.chunk.js": "6ab71e5d53bb9456fb7eaf5a722c8e7014de9876",
    "/pe360/assets/home-bg.png": "b2b3e043ec76e714e81a4259addf8eb55b825f3c",
    "/pe360/1.9a95994e0db526f48705.chunk.js": "bf183c654273a4265c8e7df256086aa7832865b6",
    "/pe360/assets/ngx-rocket-logo.png": "0ac53fd27406fe5a36e68285315fb0012e54058e",
    "/pe360/10.63fa9a615a40113c0369.chunk.js": "f68301617b7308cc5e8db46b56e0085eec7cbc71",
    "/pe360/assets/fonts/OpenSans-Bold.ttf": "2808aa965268ff1d34fa8b312fd5f456df7ae503",
    "/pe360/11.fa2f3905ac575bbd24ef.chunk.js": "6de26d23d553a38ec902b371ac285bc110e42fc9",
    "/pe360/assets/fonts/OpenSans-Regular.ttf": "3564ed0b5363df5cf277c16e0c6bedc5a682217f",
    "/pe360/12.1a967e0a3abad9ef53ad.chunk.js": "c448258e1220b6547ad5b106ab80bf6df38cacf3",
    "/pe360/assets/fonts/WorkSans-Light.ttf": "6060c3bfa57182834eac1e9de1d0d50fa33ba7a1",
    "/pe360/13.8f1557eb38c37c9907e1.chunk.js": "f393e4e11bcebd010144626c92ce57f26e33d229",
    "/pe360/assets/fonts/WorkSans-Regular.ttf": "962c129f1129594b40e6fb1132cb597495ce9813",
    "/pe360/14.d31f15e2ba3ad3d19f42.chunk.js": "a08e602c4318706763eb7c1f05b773e8920476a2",
    "/pe360/assets/icon/Star@3x.png": "0b03bbf1392630d6d0688ec66824fc251aebc15f",
    "/pe360/15.7e4ab1848cf38498f29d.chunk.js": "40c47ef2b272b17258a1a086cdca8a0f7cdd6af1",
    "/pe360/assets/icon/arrow-down.png": "4c8fc49b9a8f042e3538799caa739debef47f16e",
    "/pe360/16.e42d24af4de5c036b273.chunk.js": "d59cdfa4310927d678af100b6f564dc2fece3c3a",
    "/pe360/assets/icon/arrow-up-box.png": "4267489567e0bae8054750121d97172328bd7172",
    "/pe360/17.8454183fb73f1c28e3fc.chunk.js": "ce12a0036b87644fdf5ad02a8ef5b17af1ff035a",
    "/pe360/assets/icon/fire.png": "6749e4da09130467958b1799e516e195ae0cb0a1",
    "/pe360/18.fa25797f15b0d4fdc1af.chunk.js": "c298a84194524cef77f30503b579889943a7bb18",
    "/pe360/assets/icon/flag-header.png": "c19dc03cfa28fa9104b9304ebc3349ec7f744b81",
    "/pe360/19.25750574380bad5246a1.chunk.js": "d107e0d0f5291d5b22bf9247bc9463b3d226373e",
    "/pe360/assets/icon/go-back.png": "b263a5a3f207546cdbe47237218b5df95ba11b83",
    "/pe360/2.b40d07d23374f0b4f833.chunk.js": "07242ef19eb5b29e4be2fdf29bda04fa6497640b",
    "/pe360/assets/icon/ico_arrow-right-circle.png": "e1059a256ff3ad9d8657d50815cc6cc1c52fc461",
    "/pe360/20.27341138d94e72cf8971.chunk.js": "125c2f01c85385d142133d23b17f93c969457f5c",
    "/pe360/assets/icon/ico_arrow-right-triangle.png": "89f1317ee28034975da1f56fb04d6ace78a93a8d",
    "/pe360/21.2f68a9b926c924e20add.chunk.js": "a54f161c5dd00c7b085d4a816f94c3e5d4e37844",
    "/pe360/assets/icon/ico_caret-right.png": "bb88d63010aeabd60a9ce556fbaaab230ac106d7",
    "/pe360/22.4b57d092ac6c78aac4b7.chunk.js": "28510400305128efc0bccfcb52896dcd01fec481",
    "/pe360/assets/icon/ico_delete.png": "8c5c8fa6018ece87d7ca53fb0f55d1edf3259b5f",
    "/pe360/23.b611af10dadbaf93dc79.chunk.js": "38767459cb7eb32901246029587736df992ee530",
    "/pe360/assets/icon/ico_edit.png": "81c2cb0caf312c56bc923fa9e1efdc069de7ac6d",
    "/pe360/24.3b9726d1e0293cf7abad.chunk.js": "376681e8496f63bbaf0ec4f5c5e287594a446cb4",
    "/pe360/assets/icon/ico_export.png": "412e3bffe20daf365a07e4380b65fa193f3bd719",
    "/pe360/25.bc360cf31cf7bccbb18a.chunk.js": "aad4d7c6abdbfb2a3b8e928728136d61b1de52cc",
    "/pe360/assets/icon/ico_filter.png": "d0f0c8d5a496cc4d63e3bddcf83893432f25714c",
    "/pe360/3.aff1d114ec138e9e950b.chunk.js": "748274e5814b141551cc10191730eb4d245d8a49",
    "/pe360/assets/icon/ico_flagged.png": "3327d7e9d0532df3faca71009f4f7dd8189df13d",
    "/pe360/4.c84b50aaeca2467400d2.chunk.js": "cc99d4bf6b453973fbd822397240d911780efcaf",
    "/pe360/assets/icon/ico_pie-chart.png": "6c93f7dd6615558dadc913cc0c22f065770a3a32",
    "/pe360/5.ebd525b487571d2e0cd9.chunk.js": "5100b0de98f98c0910584303a56cd243d7419497",
    "/pe360/assets/icon/ico_print.png": "f28eb1147a35eb9f445af1c1e5f67d3a0f975fe7",
    "/pe360/6.1480a309fbfc39f43197.chunk.js": "a0fd0bde9af403d1b54cdfbdf66b425a743655e1",
    "/pe360/assets/icon/ico_raising_fund.png": "55a719230baecf21e7d7e9b863110d0c64707b43",
    "/pe360/7.cf86cea2b93c0d4d45a5.chunk.js": "e567625302e4a9bdb3218c82b32371505c35f5ee",
    "/pe360/assets/icon/ico_search.png": "17ae83f5cc3a88616a73071126826977b615190c",
    "/pe360/8.506e3612f9f31fec8c24.chunk.js": "a7d2a465c9f2c7a7e1932619d9f20208ff985523",
    "/pe360/assets/icon/ico_share.png": "16d00e3401c205514812d5ee4d508ce6d36631d0",
    "/pe360/9.d09a110aa5aa1c4681b7.chunk.js": "7d818ea690abf42774e25e4e010b9f8669e06f83",
    "/pe360/assets/icon/ico_star.png": "0b03bbf1392630d6d0688ec66824fc251aebc15f",
    "/pe360/inline.dcbf348730d881f88c71.bundle.js": "f0b913adecf072ef67b0171bc8f6da2519d348e3",
    "/pe360/assets/icon/ico_star_gray.png": "9fc29519003684f429a8dc3261890a815cd49b46",
    "/pe360/main.e1f6c7c48172401c1dcd.bundle.js": "a92f46b92b351371a4e8c0104277264aba5a8097",
    "/pe360/assets/icon/ico_star_green.png": "3e611d3bb80170e88a9b430b0b35a6d0e3a1bb99",
    "/pe360/polyfills.b87a83c1200f3d1984c6.bundle.js": "d772c3b7271a72f6b0e35ae71805006c0f5fc1a0",
    "/pe360/assets/icon/ico_star_purple.png": "923b29ad84004da9e8454fb8a96d03ac2b7f8825",
    "/pe360/styles.791cbc655813524c80af.bundle.css": "4dac55acb512251612a12f903098dda7d66b21ef",
    "/pe360/assets/icon/ico_star_yellow.png": "c4d0d820ebb7892d315e423875d401d4cedece7a",
    "/pe360/favicon.ico": "b65083d46bbf63692d5d2cdd69622e6d7ecae317",
    "/pe360/assets/icon/ico_unflagged.png": "cad052a40743300a1da4eb93ab39e7b2893eedd5",
    "/pe360/index.html": "3203d2cc2cfe5ed29560d645af6f1d6b37bc721d",
    "/pe360/assets/icon/ico_unsorted.png": "f81fe7d7a4b78f046b1c01de75da700dff4ca31f",
    "/pe360/manifest.json": "ab87700b946cea3fca4c933e9a39dd785938a739",
    "/pe360/assets/icon/location-header.png": "a55a63a8067327bf3250cc011be5ce2e84f2bc32",
    "/pe360/assets/icon-selected/ico_filter.png": "05be731c4d1357cb9bf4a8ced4b4ad60d6d09c5b",
    "/pe360/assets/icon-selected/ico_flagged.png": "cad052a40743300a1da4eb93ab39e7b2893eedd5",
    "/pe360/assets/icon-selected/ico_pie-chart.png": "b1c5be522e0773f536c6b8abb09f46671e0912cd"
  }
}
```

## Expected behavior

Should cache Javascript bundles

## Environment

<pre><code>
Angular version: 5.2.10

Browser:
- [x] Chrome (desktop) version 66.0.3359.181
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.11.1  
- Platform:  Linux

Others:

</code></pre>

**Comment by gkalpak** [comment] 2018-05-22 17:44
Based on the error message, this seems to be a duplicate of #23605.

**Closed by gkalpak** 2018-05-22 17:44 UTC

**Comment by clsatw** [comment] 2018-05-30 01:12
i'm having the same problem. it seems that service worker ignore the base-href. e.g., your site  root is http://abc.com/pe360/, but service worker always try to caches assets on http://abc.com/ 
 
plz can someone help me out.
