### ISSUE TITLE
NavigationStart event doesn't fire when browser back/forward button is used

### ISSUE THREAD

**Issue by mena149f** [angular/angular#37670] opened 2020-06-22 14:51 UTC
# 🐞 bug report

### Affected Package

The issue is caused by package @angular/router

### Description

Browser back/forward doesn't fire NavigationStart event if the following conditions happen

1. Component navigating from has CanDeactivate guard
2. Navigating using router to the same component that the browser button would navigate to
3. Cancel the navigation using the guard
4. Navigate again to the same component using the browser button

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-ivy-s3hcel

**Scenario 1:**

1. Observe the console log with every navigation (NavigationStart event is being logged)
2. Click "Go to first"
3. Click "Go to Base"
4. Click "Cancel" in the confirmation message
5. Click the browser back button
6. NavigationStart event is not logged and the confirmation message is not shown and navigation doesn't happen
7. Browser URL is wrong (pointing on base component url), and browser history is messed up

**Scenario 2:**

1. Observe the console log with every navigation (NavigationStart event is being logged)
2. Click "Go to first"
3. Click "Go to Base"
4. Click "Cancel" in the confirmation message
5. Click "Go to Base" again
6. Click "OK" in the confirmation message
7. NavigationStart event is logged and the navigation happen

Browser button is expected to behave like the normal navigation using router.

## 🌍  Your Environment

Angular CLI: 9.1.9
Node: 12.18.1
OS: win32 x64

Angular: 9.1.11
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.9
@angular-devkit/build-angular     0.901.9
@angular-devkit/build-optimizer   0.901.9
@angular-devkit/build-webpack     0.901.9
@angular-devkit/core              7.3.10
@angular-devkit/schematics        7.3.10
@angular/cdk                      9.2.4
@angular/cli                      9.1.9
@angular/flex-layout              9.0.0-beta.31
@angular/material                 9.2.4
@ngtools/webpack                  9.1.9
@schematics/angular               8.3.27
@schematics/update                0.901.9
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0

### Anything else relevant?
Replicated in Chrome: Version 83.0.4103.106 (Official Build) (64-bit)

**Comment by atscott** [comment] 2020-06-30 21:09
Hi @mena149f, I believe this would be fixed by #37716. The issue is a bit complicated, but the summary is that the `scheduleNavigation` function is always using the `lastNavigation.rawUrl` to determine if the navigation is a duplicate to the previous navigation. However, when that previous navigation via `router.navigate` was cancelled by a guard and then followed by a browser navigation with browser back/forward or a change in the url to the same destination, that is erroneously considered a duplicate and not processed.

**Comment by atscott** [comment] 2020-07-08 16:31
Closing, as #37716 was merged. This should be fixed in the upcoming 10.1 release

**Closed by atscott** 2020-07-08 16:31 UTC
Labels: comp: router, freq1: low, router: navigation pipe, severity3: broken, state: confirmed, type: bug/fix
