### ISSUE TITLE
About Style 04-13

### ISSUE THREAD

**Issue by dev054** [angular/angular#42539] opened 2021-06-09 23:37 UTC
# Docs or angular.io Bug Report

### Description
Style 04-13 mentions that we should avoid use pipe for filtering and ordering with this reason:

> Why? Filtering and especially sorting are expensive operations. As Angular can call pipe methods many times per second, sorting and filtering operations can degrade the user experience severely for even moderately-sized lists.

But... is it really true? AFAIK, Angular only call pipe's transform function many times if it's declared as "impure". Isn't it?

What's the problem in having a **pure** pipe to avoid repeating logic between several components, like this:

```ts
@Pipe({
  name: 'filter',
})
class FilterPipe implements PipeTransform {
  transform<T>(list: readonly T[], predicateFn: (value: T, index: number, array: readonly T[]) => unknown): readonly T[] {
    return list.filter(predicateFn);
  }
}
```

Usage:

```ts
@Component({
  template: `
    <ng-container *ngFor="let item of list$ | async | filter: predicateFn">
      {{ item | json }}
    <ng-container>
  `
})
class MyComponent {
  readonly predicateFn = (value) => value.property === 1;
}
```

### What's the affected URL?**
https://angular.io/guide/styleguide#do-not-add-filtering-and-sorting-logic-to-pipes.

## Screenshot
![Captura de Tela 2021-06-09 às 20 35 20](https://user-images.githubusercontent.com/28629080/121442519-39491180-c962-11eb-948b-c064db71a10a.png)

**Comment by petebacondarwin** [comment] 2021-06-10 09:39
With pure pipe filters you have to be careful that the array you pass in actually changes identity and is not just mutated, since it would not run again. See https://stackblitz.com/edit/angular-ivy-j85kql?file=src%2Fapp%2Fapp.component.ts

If you make the pipe "unpure" then it will update when the array has been mutated but then it will also be called on every change detection cycle: https://stackblitz.com/edit/angular-ivy-zcix5r?file=src%2Fapp%2Fapp.component.ts

Regarding the case when there is an observable that is emitting the list, as in your example, then one could argue that you should just do the filtering in an RXJS `map` operator, avoiding the filter pipe altogether, which also then handles in-place mutation of the array: https://stackblitz.com/edit/angular-ivy-zurobb?file=src%2Fapp%2Fapp.component.ts

**Comment by alxhub** [comment] 2021-06-10 21:17
I'm gonna close this as the issue is not actionable for us. @petebacondarwin's explanation is on point.

You're correct that a pure `filter` pipe would not perform poorly. Unfortunately the behavior of such a pipe would probably be confusing for developers not familiar with the semantics of `pure: true`.

**Closed by alxhub** 2021-06-10 21:17 UTC

**Comment by dev054** [comment] 2021-06-11 01:03
Thanks for the demos @petebacondarwin. @alxhub While I was aware of that behavior, my concern is about the docs.. maybe we can include that it isn't recommended to perform this for non-pure pipes? Because IMHO, create **pure** pipes is the key to be DRY, otherwise we would have to repeat logic over the components/services unnecessarily.
