### ISSUE TITLE
【Version 12】scss load error

### ISSUE THREAD

**Issue by ryuseikurata** [angular/angular#42166] opened 2021-05-19 04:05 UTC
# Bug Report

### Affected Package
https://github.com/ryuseikurata/ng-v12-error/blob/main/package.json

### Is this a regression?
Yes, the previous version in which this bug was not present was no error.

### Description
- As I command `ng s --prod` ,there is an error like the below.

```
Error: ~/Test/v12/assets/scss/colors.scss:1:5: Unknown word
You tried to parse SCSS with the standard CSS parser; try again with the postcss-scss parser
```

- **As I command `ng s --optimization=false`、 there is no error.**
- As I remove comment-out in colors.scss, there is no error

## Minimal Reproduction

https://github.com/ryuseikurata/ng-v12-error

## Exception or Error

```
Error: ~/Test/v12/assets/scss/colors.scss:1:5: Unknown word
You tried to parse SCSS with the standard CSS parser; try again with the postcss-scss parser
```

## Your Environment

**Angular Version:**
https://github.com/ryuseikurata/ng-v12-error/blob/main/package.json

**Anything else relevant?**

This repository is only used for the reproduction of error.

The repository I usually develop has the other errors which I don't know the cause

like below the code.

```
Error: Expected a pseudo-class or pseudo-element.

Error: Expected a pseudo-class or pseudo-element.

Error: Unexpected '/'. Escaping special characters with \ may help.

Error: Unexpected '/'. Escaping special characters with \ may help.

Error: Unexpected '/'. Escaping special characters with \ may help.
```

**Comment by petebacondarwin** [comment] 2021-05-19 06:18
Duplicate of https://github.com/angular/angular-cli/issues/20812

**Closed by petebacondarwin** 2021-05-19 06:18 UTC
