### ISSUE TITLE
AbstractControl has/getError path argument typing inconsistent with underlying methods

### ISSUE THREAD

**Issue by happenslol** [angular/angular#26191] opened 2018-10-01 15:05 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

AbstractControl has/getError currently expects an optional path as the second argument, typed as an array of strings. So, when accessing a nested form element, the following syntax can be used: `someForm.hasError('min', ['foo', 'bar'])`. However, `get` on AbstractControls offers the possibility to get nested controls using dot seperated paths: `this.get('foo.bar')` Under the hood, `hasError` calls `getError` which in turn calls `get`, which means they could use the same path syntax, even though getError/hasError only take arrays for the path.

## Expected behavior

For better consistency when working with forms, it would be nice if the path argument could be the same type for the methods that use `AbstractControl.get` under the hood. This is only a minor typing change and has no implications for any functionality. The following calls would then be possible:
```ts
someForm.hasError('min', 'foo.bar')
const error = someForm.getError('min', 'foo.bar.baz')
```

## What is the motivation / use case for changing the behavior?

I think it should be possible to consistently define form paths in the same way, and I use the dot separated syntax everywhere since it looks more concise than the array variant. Since the same methods are being called underneath (`get -> _find`), I think the same arguments should be allowed for any functions that use them.

**Comment by happenslol** [comment] 2018-10-04 14:04
I would be open to make a PR for this, but it would be nice to know if there is any interest for this/if this could get merged in the near future.

**Comment by kara** [comment] 2018-10-09 22:48
@happenslol This looks like a duplicate of https://github.com/angular/angular/issues/19734

**Closed by kara** 2018-10-09 22:48 UTC
Labels: comp: forms, type: feature
