### ISSUE TITLE
Exceptions inside zone.run are not propagated to ErrorHandler

### ISSUE THREAD

**Issue by kemsky** [angular/angular#20834] opened 2017-12-06 18:09 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Example:

```typescript
private zone:NgZone;

zone.run(() => throw new Error('test'));
```

In this case error is not caught by `ErrorHandler`.

## Expected behavior
`ErrorHandler` should be able to handle such errors.

## What is the motivation / use case for changing the behavior?
Automatic crash reporting.

## Environment

<pre><code>
Angular version: 5.0.3

</code></pre>

**Comment by JiaLiPassion** [comment] 2017-12-07 02:40
@kemsky , I can't reproduce, could you provide a reproduce repo?

**Comment by kemsky** [comment] 2017-12-07 13:17
@JiaLiPassion, it is large project, so it will take some time to extract.

**Comment by tytskyi** [comment] 2017-12-07 13:23
@kemsky see https://github.com/angular/angular/blob/master/packages/core/src/application_ref.ts#L237

Platform listens to errors in `NgZone` and then executes handler manually (outside `NgZone`). 

I suppose you need to listen for errors in your custom zone manually.

**Comment by tytskyi** [comment] 2017-12-07 13:37
@kemsky see docs: https://angular.io/api/core/NgZone#run
> If a synchronous error happens it will be rethrown and not reported via onError

**Comment by kemsky** [comment] 2017-12-07 17:20
I think i know why it happens:

```typescript
    protected onInit():void
    {
        this.zone.runOutsideAngular(() =>
        {
            //add this.onShowDropdown listener
        });
    }

    private onShowDropdown = ():void =>
    {
        this.zone.run(() =>
        {
             throw new Error('test');
        });
    };
``` 

Error is rethrown, but it is rethrown outside of zone... While this is documented, it makes me wonder how to rethrow error back into angular zone.

**Comment by tytskyi** [comment] 2017-12-07 17:28
@kemsky i think `runGuarded()` everywhere instead of just `run()`.

See tests: https://github.com/angular/zone.js/blob/v0.8.18/test/common/zone.spec.ts#L26

**Comment by kemsky** [comment] 2017-12-07 17:48
It solves my issue, however this is still 50/50 solution, for example:

```typescript
    private onShowDropdown = ():void =>
    {
        this.zone.run(() =>
        {
             throw new Error('test');
        });

        //more code to execute
    };
```

Error will be reported, but execution will continue and can cause other errors.

**Comment by mhevery** [comment] 2017-12-07 23:10
It seems to me that this works as intended. Closing

**Closed by mhevery** 2017-12-07 23:10 UTC
Labels: comp: core & compiler, comp: zones
