### ISSUE TITLE
input[type=range] with both [min] and [max]: Thumb position is reset when input is hidden and shown again

### ISSUE THREAD

**Issue by jtammen** [angular/angular#31062] opened 2019-06-14 19:47 UTC
# 🐞 bug report

### Description

I have an `<input type="range" [min]="rangeMin" [max]="rangeMax" formControlName="sample">`. The input is placed inside a tabset and thus gets shown/hidden when tabs are being switched.

When the input thumb has been used to set a value and then the input is hidden and shown again, the thumb's position is being reset to the initial position.

This does not happen when either `[min]/[max]` is being removed or I use static values like `min="50" max="200"`.

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-issue-repro2-rbd9ti

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.0.2
Node: 12.3.1
OS: darwin x64
Angular: 8.0.0
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router

Package                                    Version
--------------------------------------------------------------------
@angular-devkit/architect                  0.800.2
@angular-devkit/build-angular              0.800.2
@angular-devkit/build-optimizer            0.800.2
@angular-devkit/build-webpack              0.800.2
@angular-devkit/core                       8.0.2
@angular-devkit/schematics                 8.0.2
@angular/cli                               8.0.2
@ngtools/webpack                           8.0.2
@nguniversal/common                        7.1.1
@nguniversal/express-engine                7.1.1
@nguniversal/module-map-ngfactory-loader   7.1.1
@schematics/angular                        8.0.2
@schematics/update                         0.800.2
rxjs                                       6.5.2
typescript                                 3.4.5
webpack                                    4.30.0
</code></pre>

**Comment by gchronos** [comment] 2019-06-20 15:38
[min] - works 
[max] - no

if [max] >= 100 (100 is default value of input range)
then we have 100

probably it's because of the render queue

**Comment by jtammen** [comment] 2019-08-28 09:06
@gchronos Thanks for your addition! Is there any kind of workaround for this?

**Comment by AndrewKushnir** [comment] 2021-02-03 22:04
Hi @jtammen, I've tested this behavior using  your repro and the most up-to-date versions of Angular packages (v11.1.1) and was unable to reproduce the issue, see: https://stackblitz.com/edit/angular-ivy-bbhjip. I'm closing this ticket for now, but feel free to reopen if the problem still exists. Thank you.

**Closed by AndrewKushnir** 2021-02-03 22:04 UTC
Labels: P3, comp: forms, freq1: low, state: confirmed, triage #1, type: bug/fix

**Comment by jtammen** [comment] 2021-02-04 08:50
Hey @AndrewKushnir, thanks, I just tested it in my application (Angular 11.1.0) and I can confirm that the issue is gone!
