### ISSUE TITLE
Can't redirect to url with query params while preserving initial query params

### ISSUE THREAD

**Issue by takahser** [angular/angular#42580] opened 2021-06-15 22:15 UTC
# Bug Report

### Affected Package
The issue is caused by package @angular/router

### Is this a regression?
No

### Description
When redirecting a path to a 2nd path which uses query params the initial query params are discarded.

Example:

```
const routes: Routes = [{
  path: 'used-cars',
  redirectTo: '/cars?used=true',
}];

@NgModule({
  imports: [RouterModule.forRoot(routes, { paramsInheritanceStrategy: 'always' })],
  exports: [RouterModule]
})
export class AppRoutingModule { }

```

(Note that the leading slash is required as discussed in https://github.com/angular/angular/issues/9921)

If I now navigate to `/used-cars` I will be redirected to `/cars?used=true` which is the expected behaviour.
However, if I navigate to `/used-cars?color=yellow` I will be redirected to the same url which is not the expected behaviour. Instead, it should redirect to `/cars?used=true&color=yellow` since the `paramsInheritanceStrategy` in the `ExtraOptions` is set to `'always'`.

## Minimal Reproduction
https://stackblitz.com/edit/angular-ivy-hsyujd?file=src/app/app.module.ts

## Exception or Error
-

## Your Environment

**Angular Version:**
<pre><code>
Your global Angular CLI version (12.0.1) is greater than your local version (10.1.4). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 10.1.4
Node: 12.22.1
OS: darwin x64

Angular: 10.1.4
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1001.4
@angular-devkit/build-angular   0.1001.4
@angular-devkit/core            10.1.4
@angular-devkit/schematics      10.1.4
@angular/cdk                    10.2.4
@angular/flex-layout            10.0.0-beta.32
@angular/material               10.2.4
@schematics/angular             10.1.4
@schematics/update              0.1001.4
rxjs                            6.6.3
typescript                      4.0.3

</code></pre>

**Anything else relevant?**
If anybody knows a workaround pls let me know.

**Comment by atscott** [comment] 2021-06-16 19:54
Duplicate of #28661

**Closed by atscott** 2021-06-16 19:54 UTC
Labels: comp: router
