### ISSUE TITLE
Router navigateByUrl does not consistently apply queryParams

### ISSUE THREAD

**Issue by jinder** [angular/angular#18798] opened 2017-08-20 18:26 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
In certain scenarios, navigateByUrl does not apply query params.  

## Expected behavior
It should always apply query params.

## Minimal reproduction of the problem with instructions
Plunkr provided here:  http://plnkr.co/edit/846in1yy0rjneOR5YbXD

Click the two buttons at the top to see the difference in behaviour.

## Environment

<pre><code>
Angular version: 4.3.5

Browser:
- [X] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by jinder** [comment] 2017-09-01 11:28
@vicb @jasonaden could you confirm if this is expected behaviour or not?

**Comment by everedifice** [comment] 2017-09-11 06:59
same issue

**Comment by kingkassem** [comment] 2018-04-19 04:10
same issue

**Comment by soulfresh** [comment] 2018-04-30 20:56
For me, this worked (maintained the query params in navigation events):
```
this.router.navigateByUrl(
  this.router.createUrlTree(
    ['some/route'], {queryParams: myParamObject}
  )
);
```
But this did not (navigation events did not contain the query param string):
```
this.router.navigateByUrl('some/route', {queryParams: myParamObject});
```

**Comment by jasonaden** [comment] 2018-05-02 17:54
This is an unfortunate issue with the documentation. The `navigateByUrl` command documentation says it will `Navigate based on the provided url`. This URL can be either a string or a UrlTree. What it doesn't say is it ignores most of the `NavigationExtras`. It only looks at `skipLocationChange` and `replaceUrl`, neither of which actually modify the URL.

The `navigate` command will operate on `navigationExtras.queryParams` to create a new URL tree, then internally calls `navigateByUrl` with that new URL Tree.

I've created a task to get this sorted out. Either by deprecating `NavigationExtras` and providing the correct API surface area, or at least clarifying in the documentation.

**Comment by schankam** [comment] 2018-11-12 09:19
I was having headache trying to figure out what was the problem, and this post save me a lots of time. By why the documentation is completely unclear and broken about this ??

**Comment by majaray** [comment] 2018-11-12 10:18
same issue here.
Any temp fix for this issue while we waiting the official fix?

**Comment by egyedia** [comment] 2018-11-16 09:18
This post is great. It is a pity that the documentation was not fixed yet. I just lost ~1.5h trying to come up with very tricky workarounds. I need to work on my searching skills instead :)

**Comment by vesrah** [comment] 2019-02-07 18:15
> Is there any other method to navigate with a queryParams?

router.navigate(['/path/here'], { queryParams: { k: v }})

**Comment by gund** [comment] 2019-02-13 15:46
This is really confusing, I've spent 30 minutes on this to realise it is broken and not my fault...

Why `navigationExtras` still not deprecated, it is easy to do and this issue is open for 2 years already?...

**Comment by guidelli** [comment] 2019-05-06 12:18
Same problem for me. I'm using angular 7.

**Comment by sam-s4s** [comment] 2019-08-28 00:54
Oh wow, I'm in August 2019 and have just run into this problem. Still hasn't been fixed?
Why can't navigateByUrl just look at the NavigationExtras?

Also the documentation literally gives you an example doing this, which obviously won't work:
```
let navigationExtras: NavigationExtras = {
  queryParamsHandling: 'preserve',
  preserveFragment: true
};

// Redirect the user
this.router.navigateByUrl(redirect, navigationExtras);
```

What the heck??? A 2 year old problem that hasn't been fixed or documentation updated? Wastes half an hour of every developer's time when they run into this problem...

**Comment by cmunerap** [comment] 2019-09-10 00:49
I have exactly the same issue at this moment with the tutorial @sam-s4s :

This doesn't work:
```typescript
const navigationExtras: NavigationExtras = {
  queryParamsHandling: 'preserve',
  preserveFragment: true
};

// Redirect the user
this.router.navigateByUrl(redirect, navigationExtras);
```

This works as expected
```typescript
const navigationExtras: NavigationExtras = {
  queryParamsHandling: 'preserve',
  preserveFragment: true
};

// Redirect the user
this.router.navigate(['admin'], navigationExtras);
```

https://angular.io/guide/router#query-parameters-and-fragments

**Comment by kl2426** [comment] 2019-10-25 11:53
什么情况？有其他解决办法吗

**Comment by speciesunknown** [comment] 2019-11-26 15:54
This is a bit of a joke. I had to write my own. Bug it begs the question, whats the point of router.navigateByUrl if it doesnt support half the features of the full one?

**Comment by sam-s4s** [comment] 2019-11-26 20:36
Yes, because of this bug, I was dropping query params and not even knowing until someone found the bug. Not good.

The only workaround seems to be to either use `router.navigate` , if you can, or use `router.navigateByUrl` but add your query params to the end of the url (in my case, I have to read them when the app loads, and then re-construct them and add them on the end when I want to navigatebyUrl).

This bug should never have existed, let alone been documented incorrectly, and then not fixed for literally years... seems to be getting ignored, too, sadly.

**Comment by TheParad0X** [comment] 2019-11-27 17:29
This Bug cost me 4 hours :(

**Comment by odaper** [comment] 2020-01-12 15:41
I've encountered the same issue, I unfortunately used the route.navigate instead of route.navigateByUrl.
I'm using ngrx and routing via effects, I share with you my solution:
```
this.router.navigate([this.route.url,
       {
         outlets: {
           'call': [
             'product',
             'search',
           ]
         }
       }
     ],
     {
         queryParams: { userId: data.userId},
         relativeTo: this.activeRoute
     });

We can't with the last version of angular v8 send queryParams via navigateByUrl
I hope that it will be resolved soon 

```

**Comment by danyroIL** [comment] 2020-02-26 16:33
facing same issue with state param :/

**Comment by sebinbenjamin** [comment] 2020-06-01 12:41
What's going on?  Will this be fixed or it already fixed ?

**Comment by dmkuba** [comment] 2020-06-06 10:28
Still reproduces. Signature of the function `navigateByUrl` allows us to pass query params (as second argument within extras object), but these params are ignored when navigation happened.

**Comment by speciesunknown** [comment] 2020-06-06 10:38
> What's going on? Will this be fixed or is it already fixed?
> Looks like this was fixed.

It won't be. Its been a problem for 3 years and hasn't received any attention.

**Comment by atscott** [comment] 2020-07-08 19:52
Lowering severity to "confusing" as the [documentation](https://angular.io/api/router/Router#navigateByUrl) does state that "The function ignores any properties in the NavigationExtras that would change the provided URL." This is working as intended, as described by Jason in [this comment](https://github.com/angular/angular/issues/18798#issuecomment-386065087). The function signature could be improved further by not accepting the whole `NavigationExtras` type, but only the options that are actually used.

**Comment by codemile** [comment] 2020-08-13 11:36
I hope someone on the Angular team receives a notification for this comment, navigates to this issue from their email, scrolls all the way down to the bottom past all the previous comments, and finds that I'm just here to complain that I wasted almost an hour trying to figure this problem.

Here that person would think. "Darn... I just wasted my time reading this person's comment".

See.. that's what it feels like.

**Comment by SchnWalter** [comment] 2020-09-11 19:28
I've completely forgot that I've ran into this issue some time ago and I've ended up wasting a good amount of time debugging the router, for a 2nd time.

For those that really want to use `queryParams` with `navigateByUrl()`, here's an example service:

```ts
import { NavigationExtras as CoreNavigationExtras, Router, UrlTree } from '@angular/router';
import { trim } from 'lodash';

/**
 * A list of NavigationExtras options that are used by Router.navigateByUrl() with added support for queryParams.
 *
 * @see https://github.com/angular/angular/pull/38227
 */
export type MyNavigationExtras = Pick<CoreNavigationExtras, 'skipLocationChange'|'replaceUrl'|'state'|'queryParams'>;

export class MyNavigationService {
  constructor(private readonly router: Router) { }

  /**
   * Navigates to a view using an absolute route path, with support for query parameters.
   *
   * @see https://angular.io/api/router/NavigationExtras
   * @see https://github.com/angular/angular/issues/18798
   */
  public navigateByUrl(url: string | UrlTree, extras?: MyNavigationExtras): Promise<boolean> {
    if (extras?.queryParams) {
      const updatedExtras: CoreNavigationExtras = {
        ...extras,
        relativeTo: this.router.routerState.root
      };
      const urlString: string = url instanceof UrlTree ? this.router.serializeUrl(url) : url;
      const urlCommands: string[] = trim(urlString, '/').split('/');
      return this.router.navigate(urlCommands, updatedExtras);
    }
    return this.router.navigateByUrl(url, extras);
  }
}
```

**Comment by guy-roberts** [comment] 2020-09-24 11:53
Yep,  it took me over an hour to get here,  after first following the example in the doc.

**Closed** 2020-09-25 14:36 UTC
Labels: comp: router, freq2: medium, severity1: confusing, state: confirmed, type: bug/fix
