### ISSUE TITLE
ViewChild on component placed inside of template being used by other component is always set to same component

### ISSUE THREAD

**Issue by marclerman** [angular/angular#14835] opened 2017-03-01 17:50 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Please look at [this Plunker](https://plnkr.co/edit/ulqFSi42Xwiyr1lLGXjW?p=preview).
This test case shows that the ViewChild for a component placed inside of a template used by another component will remain unchanged, although the actual component follows the expected lifecycle (construction, OnInit, OnDestroy).

**Expected behavior**
I expected that the ViewChild variable would be updated according to the InnerComponent actually in the DOM.

**Minimal reproduction of the problem with instructions**
- Go to [the Plunker](https://plnkr.co/edit/ulqFSi42Xwiyr1lLGXjW?p=preview).
- When the application loads, we only have a "Toggle content" button. Click it, and a new InnerComponent (of index 1) will be constructed, and will go through its OnInit. The ViewChild for #inner in AppComponent is set to that InnerComponent of index 1.
- Click "Toggle content" again, and the InnerComponent of index 1 will have its OnDestroy called and it will be removed from the DOM.
- Click "Toggle content" again, and a new instance of the InnerComponent (of index 2) will be constructed, and its OnInit will be called. However, #inner will be set again to first InnerComponent of index 1.
- Click "Toggle content" again, and the InnerComponent of index 2 will have its OnDestroy called and it will be removed from the DOM.
- Every time you will make InnerComponent appear, #inner will still be called with the same InnerComponent of index 1.

**What is the motivation / use case for changing the behavior?**
It is a big problem that what we see in the browser and the component we get at through the ViewChild are not the same. ViewChildren seems to be exhibiting the same problem.

**Please tell us about your environment:**
Windows 10

* **Angular version:** 2.4.8

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
All
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 2.0.3

* **Node (for AoT issues):** `node --version` =

**Comment by alexzuza** [comment] 2017-03-01 20:20
Maybe it is related somehow with this issue https://github.com/angular/angular/issues/13921

In your case you can try using the following workaround:

**TogglerComponent**
   ```
 <template *ngIf="_isShowing" #ngTemplateOutletContainer [ngTemplateOutlet]="_content?.templateRef"></template>

 @ViewChild('ngTemplateOutletContainer', { read: ViewContainerRef })
  private ngTemplateOutletContainer: ViewContainerRef;

public toggle(): void {
    if(this.ngTemplateOutletContainer) {
      this.ngTemplateOutletContainer.clear();
    }
    this._isShowing = !this._isShowing;
}

```
https://plnkr.co/edit/8RJHdsFAXtoylE01pVZi?p=preview

**Comment by marclerman** [comment] 2017-03-02 08:13
Great workaround, thanks very much @alexzuza!

Of course, it looks like this should be fixed in Angular itself.

**Comment by amcdnl** [comment] 2017-03-27 14:06
Can anyone confirm if this is an issue in ng4 still?

**Comment by pkozlowski-opensource** [comment] 2019-03-23 09:08
I can't reproduce it any more with the latest Angular: https://stackblitz.com/edit/angular-p6jhzm
Alternatively, I might be misunderstanding the issue :-)

I'm going to close it for now as I can't reproduce but please feel free to open a new issue with a minimal stackblitz if anyone thinks that things are still not working as expected.

**Closed by pkozlowski-opensource** 2019-03-23 09:08 UTC
Labels: comp: core & compiler, freq2: medium, severity3: broken, type: bug/fix
