### ISSUE TITLE
localize doesn't work with target: ES2015

### ISSUE THREAD

**Issue by DaSchTour** [angular/angular#40702] opened 2021-02-04 12:44 UTC
I'm working with angular since several years now and localization is a problem again and again.
First it starts with the question, how should the ecosystem around translation look like, what's the best practice here? There is no documentation, recommendation or help for the steps after extracting i18n.
It start's with the fact, that translations by default are not merged, so I added xliffmerge do my stack. That works pretty okay.
For doing translations I use [poedit](https://poedit.net) which is also a pretty nice tool.

But in the end I regularly get issues broken translations, because interpolation doesn't correctly find it self through the process or currently with this _Unexpected messageParts for `$localize` (expected an array of strings)._. This error message itself is already a pain because it's not helpful at all, because it actually just tells you "There is something wrong with your translations, good luck finding the bad one".

The problem for me is, that I really don't know who to "blame". Is angular not creating proper XLIFF files, is xliffmerge not merging them correctly or is poedit doing something wrong with my files. It's really frustrating to work with translations when beeing confronted with such errors.

So I really hope that the angular team can spend some time to add documentation about tools that are proven to work with angular. To think about integrating xliffmerge into angular CLI and to add more helpful error messages so that broken translations can be identified easier.

P.S.: Oh and what I forgot is prettier. It also adds to the mess because messages are wrapped or spaces are added which makes creating translations also harder.

**Comment by petebacondarwin** [comment] 2021-02-04 13:37
@DaSchTour - I am sorry you are having difficulties around translating your projects. While I understand your frustration there is little in this issue that we can act upon. I will create a PR to provide more information when the `Unexpected messageParts for $localize (expected an array of strings)` error is thrown. But other than that I don't think this issue is actionable by us.

If you wish to propose concrete feature requests or have a specific scenario that is broken, please can you create a new issue with clear instructions on how to reproduce the issue or what exactly the feature would do. Please note that we do not intend to implement translation file "merging" since there are tools that do this and we do not have the capacity in the team to support such additional tooling.

**Comment by DaSchTour** [comment] 2021-02-04 14:09
@petebacondarwin thanks for the quick answer. A better error message will definitely help at maybe solve the biggest issue. I must admit, that I currently don't have the time to think about concrete feature, as I'm stuck in my i18n disaster. But I'll take some time for this after I solved it.

**Comment by petebacondarwin** [comment] 2021-02-04 14:20
Can we assume that you have `target: es5` in your tsconfig.json?

**Comment by KrakenTyio** [comment] 2021-02-04 14:52
we have issue after upgrade to 11.1.2 and recreate new transaltions with ng extract-i18n and merge with xliffmerge
issue occure after complete remove node_modules + package.json and reinstall
now we investigating which part is proken if, whole translations, merged or extraction

**Comment by KrakenTyio** [comment] 2021-02-04 14:55
our target are 
```
 "target": "ES2015",
    "module": "es2020",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "noUnusedParameters": false,
    "noUnusedLocals": true,
    "noImplicitAny": true,
    "suppressImplicitAnyIndexErrors": true,
    "removeComments": false,
    "allowSyntheticDefaultImports": true,
    "sourceMap": true,
    "noEmitHelpers": true,
    "importHelpers": true,
    "strictNullChecks": false,
    "skipLibCheck": true,
    "strictPropertyInitialization": false,
    "pretty": true,
    "resolveJsonModule": true,
    "declaration": false,
    "lib": ["dom", "es2019"],
    ```

**Comment by DaSchTour** [comment] 2021-02-04 15:09
> Can we assume that you have `target: es5` in your tsconfig.json?

Okay, that actually was the issue. Changing target to es5 fixed the problem. Thanks a lot lot lot

**Comment by DaSchTour** [comment] 2021-02-04 17:38
Yeah, changing to es5 also means that I can't use differential loading anymore. So that's only a temporary solution. I still wonder why this only fails when doing a production build. So there must be something with minified ES2015 which breaks generating localized bundle. I wonder for what I should look out to find the actual cause. It's also hard to tell which module or component causes the problem. Although I have a bit the impression, that it's somewhat random 😕

**Comment by KrakenTyio** [comment] 2021-02-04 18:23
optimization: off in angular.json help temporary, it has something with that

**Comment by KrakenTyio** [comment] 2021-02-04 18:31
I replace thor errro of this message:
instead of `throw new BabelParseError(array.node, 'Unexpected messageParts for `$localize` (expected an array of strings).');`
i put there `throw new BabelParseError(array.node, JSON.stringify(array.node)');`

response for optimization: true
```
{"type":"LogicalExpression","start":11731,"end":11835,"loc":{"start":{"line":1,"column":11731},"end":{"line":1,"column":11835}},"left":{"type":"Identifier","start":11731,"end":11732,"loc":{"start":{"line":1,"column":11731},"end":{"line":1,"column":11732},"identifierName":"e"},"name":"e"},"operator":"||","right":{"type":"SequenceExpression","start":11735,"end":11834,"loc":{"start":{"line":1,"column":11735},"end":{"line":1,"column":11834}},"extra":{"parenthesized":true,"parenStart":11734},"expressions":[{"type":"AssignmentExpression","start":11735,"end":11741,"loc":{"start":{"line":1,"column":11735},"end":{"line":1,"column":11741}},"operator":"=","left":{"type":"Identifier","start":11735,"end":11736,"loc":{"start":{"line":1,"column":11735},"end":{"line":1,"column":11736},"identifierName":"t"},"name":"t"},"right":{"type":"ArrayExpression","start":11737,"end":11741,"loc":{"start":{"line":1,"column":11737},"end":{"line":1,"column":11741}},"elements":[{"type":"StringLiteral","start":11738,"end":11740,"loc":{"start":{"line":1,"column":11738},"end":{"line":1,"column":11740}},"extra":{"rawValue":"","raw":"\"\""},"value":""}]}},{"type":"LogicalExpression","start":11742,"end":11759,"loc":{"start":{"line":1,"column":11742},"end":{"line":1,"column":11759}},"left":{"type":"Identifier","start":11742,"end":11743,"loc":{"start":{"line":1,"column":11742},"end":{"line":1,"column":11743},"identifierName":"n"},"name":"n"},"operator":"||","right":{"type":"AssignmentExpression","start":11746,"end":11758,"loc":{"start":{"line":1,"column":11746},"end":{"line":1,"column":11758}},"extra":{"parenthesized":true,"parenStart":11745},"operator":"=","left":{"type":"Identifier","start":11746,"end":11747,"loc":{"start":{"line":1,"column":11746},"end":{"line":1,"column":11747},"identifierName":"n"},"name":"n"},"right":{"type":"CallExpression","start":11748,"end":11758,"loc":{"start":{"line":1,"column":11748},"end":{"line":1,"column":11758}},"callee":{"type":"MemberExpression","start":11748,"end":11755,"loc":{"start":{"line":1,"column":11748},"end":{"line":1,"column":11755}},"object":{"type":"Identifier","start":11748,"end":11749,"loc":{"start":{"line":1,"column":11748},"end":{"line":1,"column":11749},"identifierName":"t"},"name":"t"},"computed":false,"property":{"type":"Identifier","start":11750,"end":11755,"loc":{"start":{"line":1,"column":11750},"end":{"line":1,"column":11755},"identifierName":"slice"},"name":"slice"}},"arguments":[{"type":"NumericLiteral","start":11756,"end":11757,"loc":{"start":{"line":1,"column":11756},"end":{"line":1,"column":11757}},"extra":{"rawValue":0,"raw":"0"},"value":0}]}}},{"type":"AssignmentExpression","start":11760,"end":11834,"loc":{"start":{"line":1,"column":11760},"end":{"line":1,"column":11834}},"operator":"=","left":{"type":"Identifier","start":11760,"end":11761,"loc":{"start":{"line":1,"column":11760},"end":{"line":1,"column":11761},"identifierName":"e"},"name":"e"},"right":{"type":"CallExpression","start":11762,"end":11834,"loc":{"start":{"line":1,"column":11762},"end":{"line":1,"column":11834}},"callee":{"type":"MemberExpression","start":11762,"end":11775,"loc":{"start":{"line":1,"column":11762},"end":{"line":1,"column":11775}},"object":{"type":"Identifier","start":11762,"end":11768,"loc":{"start":{"line":1,"column":11762},"end":{"line":1,"column":11768},"identifierName":"Object"},"name":"Object"},"computed":false,"property":{"type":"Identifier","start":11769,"end":11775,"loc":{"start":{"line":1,"column":11769},"end":{"line":1,"column":11775},"identifierName":"freeze"},"name":"freeze"}},"arguments":[{"type":"CallExpression","start":11776,"end":11833,"loc":{"start":{"line":1,"column":11776},"end":{"line":1,"column":11833}},"callee":{"type":"MemberExpression","start":11776,"end":11799,"loc":{"start":{"line":1,"column":11776},"end":{"line":1,"column":11799}},"object":{"type":"Identifier","start":11776,"end":11782,"loc":{"start":{"line":1,"column":11776},"end":{"line":1,"column":11782},"identifierName":"Object"},"name":"Object"},"computed":false,"property":{"type":"Identifier","start":11783,"end":11799,"loc":{"start":{"line":1,"column":11783},"end":{"line":1,"column":11799},"identifierName":"defineProperties"},"name":"defineProperties"}},"arguments":[{"type":"Identifier","start":11800,"end":11801,"loc":{"start":{"line":1,"column":11800},"end":{"line":1,"column":11801},"identifierName":"t"},"name":"t"},{"type":"ObjectExpression","start":11802,"end":11832,"loc":{"start":{"line":1,"column":11802},"end":{"line":1,"column":11832}},"properties":[{"type":"ObjectProperty","start":11803,"end":11831,"loc":{"start":{"line":1,"column":11803},"end":{"line":1,"column":11831}},"method":false,"key":{"type":"Identifier","start":11803,"end":11806,"loc":{"start":{"line":1,"column":11803},"end":{"line":1,"column":11806},"identifierName":"raw"},"name":"raw"},"computed":false,"shorthand":false,"value":{"type":"ObjectExpression","start":11807,"end":11831,"loc":{"start":{"line":1,"column":11807},"end":{"line":1,"column":11831}},"properties":[{"type":"ObjectProperty","start":11808,"end":11830,"loc":{"start":{"line":1,"column":11808},"end":{"line":1,"column":11830}},"method":false,"key":{"type":"Identifier","start":11808,"end":11813,"loc":{"start":{"line":1,"column":11808},"end":{"line":1,"column":11813},"identifierName":"value"},"name":"value"},"computed":false,"shorthand":false,"value":{"type":"CallExpression","start":11814,"end":11830,"loc":{"start":{"line":1,"column":11814},"end":{"line":1,"column":11830}},"callee":{"type":"MemberExpression","start":11814,"end":11827,"loc":{"start":{"line":1,"column":11814},"end":{"line":1,"column":11827}},"object":{"type":"Identifier","start":11814,"end":11820,"loc":{"start":{"line":1,"column":11814},"end":{"line":1,"column":11820},"identifierName":"Object"},"name":"Object"},"computed":false,"property":{"type":"Identifier","start":11821,"end":11827,"loc":{"start":{"line":1,"column":11821},"end":{"line":1,"column":11827},"identifierName":"freeze"},"name":"freeze"}},"arguments":[{"type":"Identifier","start":11828,"end":11829,"loc":{"start":{"line":1,"column":11828},"end":{"line":1,"column":11829},"identifierName":"n"},"name":"n"}]}}]}}]}]}]}}]}}

```

but have no clue what is mean if is correct or not, yesterday was everthing fine

**Comment by petebacondarwin** [comment] 2021-02-04 18:58
I reverse engineered that AST and it looks something like this:

```js
e || (t="", n || (n=t.slice(0)), e = Object.freeze(Object.defineProperties(t, {raw: {value: Object.freeze(n)}}))
```

So the overall `$localize` call will be:

```js
$localize(e || (t="", n || (n=t.slice(0)), e = Object.freeze(Object.defineProperties(t, {raw: {value: Object.freeze(n)}})))
```

This is basically a downleveling of 

```
$localize``
```

In other words some aspect of your build system is converting the tagged template literal and generating a call.
Different transpilers can generate different version of this. We have the ability to parse various forms of this.
See https://github.com/angular/angular/blob/bb6d791dab5c74ae7571cd68ee7cddf322247dc6/packages/localize/src/tools/test/source_file_utils_spec.ts#L79-L166

It seems that this is another format that we have not come across before. It would necessary to know more about the build tooling you are using to generate these files.

**Comment by vpetrusevici** [comment] 2021-02-04 20:46
Hi, I have exact the same issue now. And build works only with optimization: false

**Comment by vpetrusevici** [comment] 2021-02-04 20:55
"target": "es5" also fixed the problem, but I hope this is a temporary solution

**Comment by petebacondarwin** [comment] 2021-02-04 21:40
Hmm. so I wonder if there has been a change to the downlevelling in CLI that is now producing this new ES5 transpilation of tagged template literals.

**Comment by petebacondarwin** [comment] 2021-02-04 22:07
It looks like Babel changed its output for tagged template literals: https://github.com/babel/babel/pull/12588
I'll put together a PR to fix this.

**Comment by vpetrusevici** [comment] 2021-02-04 22:11
@petebacondarwin thanks. Good luck!

**Comment by KrakenTyio** [comment] 2021-02-05 08:45
adding `"@babel/plugin-transform-template-literals": "7.12.1"` to devDependencies temporary fixe issue, as you said @petebacondarwin  its related to babel changes

**Comment by DaSchTour** [comment] 2021-02-05 08:50
@petebacondarwin thanks for your efforts and sorry for my rant at the beginning 😅 most of the time localization works fine, it's just if it doesn't work it's hard to fix 😄

**Comment by hugodes** [comment] 2021-02-05 13:56
This thread is tracking 2 issues it seems.

1) Better error messages for i18n
2) A regression in angular 11.1.2 that caused errors on previously working repos.

I see 1) is being addressed, but what about 2) ?

Thanks for the clarification :)

**Comment by petebacondarwin** [comment] 2021-02-05 14:31
The second one is also being addressed. See https://github.com/angular/angular/issues/40702#issuecomment-773634754

**Closed** 2021-02-09 21:52 UTC
Labels: P4, comp: docs, comp: i18n, state: has PR

**Comment by DaSchTour** [comment] 2021-02-12 11:44
@petebacondarwin thanks a lot for fixing this issue. Everything works fine now 👍
