### ISSUE TITLE
[loose proposal] Self closing tags

### ISSUE THREAD

**Issue by alshdavid** [angular/angular#25082] opened 2018-07-25 02:58 UTC
Hey, first off - Love your work guys.
I have a request to allow for self closing component/element tags

Often times I wrap functionality using custom elements and never require a closing tag.
This results in a slightly less aesthetic mark up.

e.g.
```
<icon src="my-icon" />
<icon src="my-icon"></icon>
```

I realise this is a very low priority feature, but the feature makes for an aesthetically pleasing result.

**Comment by trotyl** [comment] 2018-07-25 03:00
Duplicate of https://github.com/angular/angular/issues/673

**Comment by vicb** [comment] 2018-07-25 03:59
This behavior would deviate from HTML and we do not plan to go down that path, sorry.
One of the main reason is that most of the existing tooling out here rely on the HTML behavior.

**Closed by vicb** 2018-07-25 03:59 UTC

**Comment by alshdavid** [comment] 2018-08-07 22:42
That makes sense and is fair enough. Are there plans to support html preprocessors in future?

**Comment by merveillevaneck** [comment] 2019-05-16 08:38
im struggling to understand how this implementation request deviates from html? its simply syntactical sugar, which not only is relatively easy to implement, but also ups the development experience of the devs using angular on the daily. self-closing tags already exist in pure html, on specific types of tags. allowing a dynamic html generator to produce higher-order components that are parsed to html is already deviating way more from html that simply allowing self-closing components. parsing vs virtualisation.

Perhaps im completely not understanding the issue here. I am not very experienced after all, but nontheless i think there are many reasons to support this change.

**Comment by trotyl** [comment] 2019-05-16 09:06
@merveillevaneck 

> This error occurs if the parser encounters a start tag for an element that is not in the list of void elements or is not a part of foreign content (i.e., not an SVG or MathML element) that has a U+002F (/) code point right before the closing U+003E (>) code point. **The parser behaves as if the U+002F (/) is not present.**

https://html.spec.whatwg.org/#parse-error-non-void-html-element-start-tag-with-trailing-solidus

It has been explicitly specified in HTML that `<my-app/>` is just equivalent to `<my-app>`, so that any following content is considered children, not sibling, you can test this behavior in any browser:

```javascript
container = document.createElement('div')
container.innerHTML = `<my-app/><p>You may think this is sibling but it's always child</p>`
console.log(container.innerHTML)

// <my-app><p>You may think this is sibling but it's always child</p></my-app>
```
