### ISSUE TITLE
[i18n] Interpolated text within tags is not rendered

### ISSUE THREAD

**Issue by PJMS** [angular/angular#37281] opened 2020-05-25 15:27 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/localize

### Is this a regression?

 This syntax used to work back in my project before upgrade to v9 from 7.1.2

### Description

 A clear and concise description of the problem...
I use `@angular/localize` for i18n of my Angular v9 project.
I run `ng xi18n` and `xliffmerge` in order to get `messages.<LOCALE_ID>.xlf` in `xlf2` format.

Everything's fine when I serve(or build) the app in the source locale, but the following happens when I serve in translated language.

Any INTERPOLATION is basically gone from the html when it is between the `<pc>` tags.

## 🔬 Minimal Reproduction
[StackBlitz](https://stackblitz.com/edit/angular-issue-repro2-8qjbdt?file=angular.json)

After you download the files and install the packages
1. `npm run i18n` to extract and generate xlf file for translation.

The following is the generated target text.
`<pc id="0" equivStart="START_BOLD_TEXT" equivEnd="CLOSE_BOLD_TEXT" type="fmt" dispStart="&lt;b>" dispEnd="&lt;/b>">Right <ph id="1" equiv="INTERPOLATION" disp="{{ interpolatedText }}"/> here</pc>`

2. `ng serve` will serve the app in `en-us` locale and will render

![스크린샷 2020-05-26 00 13 57](https://user-images.githubusercontent.com/1370225/82825486-4c6b7980-9ee6-11ea-8f7a-e1c6dd60343d.png)
> Right TEXT here

includes 'TEXT' which is an interpolated text.

3. `ng serve --configuration=ja-jp` will render the app in ja-jp locale but will render

![스크린샷 2020-05-26 00 13 30](https://user-images.githubusercontent.com/1370225/82825498-51c8c400-9ee6-11ea-9b9f-e767d3844c49.png)
> Right here

that removes an interpolated text within the tags.

### Repro Conditions
- As soon as I pull the interpolation tag(<ph>) out of the <pc> tag, everything goes back to normal.
- It only behaves this way only when there is any text other than the <ph> tag between the <pc> and </pc> tag. For instance, `<pc id="0" equivStart="START_BOLD_TEXT" equivEnd="CLOSE_BOLD_TEXT" type="fmt" dispStart="&lt;b>" dispEnd="&lt;/b>"><ph id="1" equiv="INTERPOLATION" disp="{{ interpolatedText }}"/></pc>` will still render just fine.

## 🔥 Exception or Error
No error displayed.

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.1.7
Node: 12.13.0
OS: darwin x64

Angular: 9.1.9
... animations, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.7
@angular-devkit/build-angular     0.901.7
@angular-devkit/build-optimizer   0.901.7
@angular-devkit/build-webpack     0.901.7
@angular-devkit/core              9.1.7
@angular-devkit/schematics        9.1.7
@angular/cli                      9.1.7
@ngtools/webpack                  9.1.7
@schematics/angular               9.1.7
@schematics/update                0.901.7
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0
</code></pre>

**Anything else relevant?**

No, all evergreen browsers render the same.

**Comment by petebacondarwin** [comment] 2020-05-25 16:17
Thanks for this report and the excellent reproduction. I can confirm that this looks like a bug. I might not be able to look into it further until the start of next week.

**Comment by petebacondarwin** [comment] 2020-05-25 20:27
OK, so a bit of debugging shows that this is a bug in the `MessageSerializer.visitContainedNodes()` method which is responsible for loading the translations. It appears that it doesn't cope well with `<pc>` container nodes that contain more than one child node. It should be a fairly straightforward fix.

**Comment by petebacondarwin** [comment] 2020-10-23 19:33
I appears that this was actually fixed by https://github.com/angular/angular/commit/68a9a01a648f9332b34f272146546faaca934476

**Closed by petebacondarwin** 2020-10-23 19:33 UTC
Labels: P3, comp: i18n, freq1: low, state: confirmed, state: in investigation, triage #1, type: bug/fix

**Comment by PJMS** [comment] 2020-11-08 18:09
I'm on 10.2.0 and I can confirm that this bug has been fixed. Thanks!
