### ISSUE TITLE
Navigating to named router-outlet with 'null' does not work from within named router-outlet

### ISSUE THREAD

**Issue by gunsh** [angular/angular#36766] opened 2020-04-22 16:56 UTC
# 🐞 bug report

### Affected Package
@angular/router

### Is this a regression?
Not sure. I just stumbled upon it.

### Description
The app shows two side by side instances of router-outlet. One is primary, the other one is secondary. The two links (show and hide) navigate to the secondary outlet only. "Show" navigates to OtherComponent while "hide" navigates to 'null' effectively clearing the router-outlet. Both use [routerLink] to achieve this result. This is working fine.

When a link from within OtherComponent is activated (which also features a [routerLink] navigating the secondary outlet to 'null') clicking the link does not work. Furthermore, as router tracing is enabled upon clicking the link in OtherComponent, no routing information is shown and no errors are displayed either. As if the [routerLink] attribute never existed.

But to make sure OtherComponent is still working, it is also included in HelloComponent's template. Clicking on a link from OtherComponent instantiated by HelloComponent **works** as expected.

Conclusion: clearing a secondary outlet from a component currently active in a secondary outlet does not work. I do not see a reason why this would not work. If this is a bad thing to do, one would at least expect A) a router error in the console or B) any other error either of which would let me know that I am doing something wrong.

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-spzbc3

## 🔥 Exception or Error
No related errors.

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.1.2
Node: 12.16.2
OS: win32 x64

Angular: 9.1.2
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, platform-server, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.2
@angular-devkit/build-angular     0.901.2
@angular-devkit/build-optimizer   0.901.2
@angular-devkit/build-webpack     0.901.2
@angular-devkit/core              9.1.2
@angular-devkit/schematics        9.1.2
@angular/cdk                      9.2.1
@ngtools/webpack                  9.1.2
@schematics/angular               9.1.2
@schematics/update                0.901.2
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0
</code></pre>

**Comment by atscott** [comment] 2020-04-23 22:40
Hi @gunsh, thanks for your report and reproduction. Closing as a duplicate of #35732.

**Closed by atscott** 2020-04-23 22:40 UTC
Labels: comp: router
