### ISSUE TITLE
How to use Testability? Unclear from the docs

### ISSUE THREAD

**Issue by goldylucks** [angular/angular#42425] opened 2021-05-31 04:56 UTC
# Docs or angular.io Bug Report

### Description

The Testability doc has no example or explanation on how to use it. For example I'm using cypress to e2e test my app and I have no clue how to access it in my tests.

**Comment by ChristopherKiss** [comment] 2021-06-11 05:45
This would be an, albeit brief, duplicate of a ticket I raised 2 years ago that looks like it's going to be closed due to lack of upvotes.

https://github.com/angular/angular/issues/28968

**Comment by mgechev** [comment] 2021-11-11 23:15
I'll move forward and close the feature request because it didn't reach a sufficient number of votes. I'd recommend filling the gap in a community blog post or other resource.

**Closed by mgechev** 2021-11-11 23:15 UTC
Labels: feature, comp: docs, insufficient votes
