### ISSUE TITLE
Angular2 Final : Component with class inheritance 

### ISSUE THREAD

**Issue by h2qutc** [angular/angular#12063] opened 2016-10-04 09:04 UTC
Hi everyone, 
I'm trying to extend a component using Class inheritance. 

Here is my component (feed.ts)

@Component({
    selector: 'feed',
    templateUrl: 'feed.html',
   // providers: [provide(BaseListContainer, { useExisting: BaseListContainer })]
})
export class Feed extends BaseListContainer {
}

and my classe BaseListContainer is like that: 

export class BaseListContainer  {
    @Input() key: string;
}

The "feed" component is used in *.html like: 
<feed [key]="somevalue"></feed>

The error I received is : 
polyfills.js:3 Unhandled Promise rejection: Template parse errors:
Can't bind to 'key' since it isn't a known property of 'feed'. ("

This schema worked fine with angular2 Rc4 but not with angular2 final. 
For more detail, I'am using Ionic2 Rc/ Typescript 2

Thanks for any help

**Comment by pkozlowski-opensource** [comment] 2016-10-04 09:05
This is duplicate of #11606

**Closed by pkozlowski-opensource** 2016-10-04 09:05 UTC
