### ISSUE TITLE
Router - cross module lazy routing

### ISSUE THREAD

**Issue by klinki** [angular/angular#24124] opened 2018-05-25 07:55 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
Currently lazy loaded module can define routes only nested under its route segment.

We have a following routing structure:

```
Transactions Module: 
/transactions
/transactions/1/detail
.....
Users Module
/users
/users/1
/users/1/transactions  <--- HERE COMES THE PROBLEM
```

Currently (AFAIK) there is no way to define upper level routes in lazy loaded module.

In root we have:
```javascript
[
      { path: 'transactions', loadChildren: 'app/transactions/transactions.module#TransactionsModule' },
      { path: 'users', loadChildren: 'app/users/users.module#UsersModule' },
] 
```

UsersModule:

```javascript
[
      { path: '', component: UsersListComponent },
      { path: ':id', children: [
          { path: '', component: UserDetailComponent },
          { path: 'transactions', loadChildren: 'app/transactions/transactions.module#TransactionsModule' }
          // ^^^^^^^^^^^^^^^^^^
          // this is also part of the problem
      ] },
] 
```

TransactionsModule:

```javascript
[
      { path: '', component: AllTransactionsListComponent },
      { path: '', component: UserTransactionsComponent },
      // ^^^^^^^^^^^^^^^^^^
      // ???? what now? I don't know if it came from /transactions or /user/1/transactions
      // I want to have different components for routes /user/1/transactions and for /transactions
] 
```

## Expected behavior

It would be great if lazy loaded module could specify also routes not nested under its segment.

In that case, TransactionsModule could provide route `/users/1/transactions` (which it currently can't).

-------------

I have 3 other ideas:

1) Add some back-tracking - router could choose proper route not only by current segment, but also by previous one. In that case, route could look something like

```
{ path: '', component: AllTransactionsListComponent },
{ path: '', previousPath: '/users/:id', component: UserTransactionsComponent }
```

2) Add other mode then `prefix` and `full`.  (Maybe `absolute` ? )

3) Other possible solution would be to add some additional criteria to match routes. For example based on what is in data (when they are inherited from parent using `paramsInheritanceStrategy`). Or even better, add a callback which would be called with all previous routes. This would solve also the 1) and be most flexible solution allowing many additional scenarios.

```
{ path: '', component: AllTransactionsListComponent },
{ path: '', routeMatchCallback: (previousRoutes: ActivatedRouteSnapshot[]) => ...., component: UserTransactionsComponent }  
```

## What is the motivation / use case for changing the behavior?

It would greatly simplify routing and provide currently unsupported scenarios.

**Comment by montella1507** [comment] 2018-05-25 08:54
+1

**Comment by jasonaden** [comment] 2018-06-14 22:56
Thanks for the issue. From the description though, I think what you're describing is a system where a lazy loaded module can affect the route matching of parent modules. If that's the case, this isn't something we would like to do.

The reason being lazy loading a module shouldn't be able to have effect on modules outside of that module's scope. Let's say you're lazy loading the `UserModule`, and it defines a path from the root of `/users/:id`. What if another module had already defined the same path? Should the lazy loaded module overwrite the route config from another module? What happens when a lazy loaded module defines a new path for itself from root that doesn't match the URL you used to get to the lazy loaded module? Do you now have two ways to get to that lazy module?

Currently the only "external" effect a lazy loaded module can have is through redirects to paths outside of the lazy loaded module. At this time, we weren't planning on changing that model. Does that make sense?

**Comment by klinki** [comment] 2018-06-19 11:43
@jasonaden I understand the reasoining why it behaves like this now. But it is very limiting :( 

What about adding some callback to route, which could affect if route matches or not? That would be even more flexible. (It is described as number 3 in my original post).

**Comment by jasonaden** [comment] 2018-06-19 23:31
Okay. I *think* from what you're saying here you're looking for the [`UrlMatcher`](https://angular.io/api/router/UrlMatcher) api. Take a look, leave a note if that looks like it might solve the issue here.

The problem is you're not going to be able to get an `ActivatedRouteSnapshot` at the time of URL matching. The router needs to determine matches up front, as well as handle redirects, before it creates the snapshot.

**Comment by jasonaden** [comment] 2018-06-26 22:50
Closing due to lack of further information. But if there's more information, please create a *new* issue and reference this one for history.

**Closed by jasonaden** 2018-06-26 22:50 UTC
Labels: comp: router, flag: can be closed?
