### ISSUE TITLE
Typo in Angular Docs at Composing Components Tutorial

### ISSUE THREAD

**Issue by AppleLAN** [angular/angular#52757] opened 2023-11-09 22:15 UTC
### Describe the problem that you experienced

There's a typo in the Angular documentation at the route https://angular-dev-site.web.app/tutorials/learn-angular/composing-components.

In the first step titled "Add a reference to UserComponent", the current instructions incorrectly state to add AppComponent into the AppComponent's imports array.

However, it should instruct to add UserComponent instead.

![image](https://github.com/angular/angular/assets/6935240/590e5f54-4053-405a-aab1-bfdfd577603a)

Thanks for the amazing new Document and Framework

Thank you !!! 🥰🥰🥰

### Enter the URL of the topic with the problem

https://angular-dev-site.web.app/tutorials/learn-angular/composing-components

### Describe what you were looking for in the documentation

Just streaming live the new tutorial

### Describe the actions that led you to experience the problem

Reading the steps

### Describe what you want to experience that would fix the problem

Correct the typo

**Comment by twerske** [comment] 2023-11-09 23:11
Duplicate of https://github.com/angular/angular/issues/52584

**Closed by twerske** 2023-11-09 23:11 UTC
