### ISSUE TITLE
saucelabs tunnel is not established within 120 seconds on CI 

### ISSUE THREAD

**Issue by pkozlowski-opensource** [angular/angular#28579] opened 2019-02-06 21:55 UTC
One of the source of CI flakes is in the problem with establishing saucelabs tunnel that fails with:

> #!/bin/bash -eo pipefail
./scripts/saucelabs/wait-for-tunnel.sh
................................................................................................................................................................................................................................................
Timed out after 120 seconds waiting for tunnel ready file
Exited with code 5

Example job: https://circleci.com/gh/angular/angular/191457?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

Not sure if we can fix it but maybe we could:
* re-try
* not sure is SauceLabs exposes their health status but maybe we could call such API  and print useful info ("hey, Sauce is down, no reason to keep restarting your job"

**Comment by pkozlowski-opensource** [comment] 2019-02-07 13:53
Another instance if it helps investigation: https://circleci.com/gh/angular/angular/192722?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

https://status.saucelabs.com/ is announcing all green when this happened.

**Comment by devversion** [comment] 2019-02-07 18:31
For tracking. This is the output of the `start-tunnel.sh` script. 

```
+ sauceArgs=' --readyfile /tmp/angular/sauce-connect-ready-file.lock --pidfile /tmp/angular/sauce-connect-pid-file.lock --tunnel-identifier angular-191457-0'
+ echo 'Starting Sauce Connect. Passed arguments:  --readyfile /tmp/angular/sauce-connect-ready-file.lock --pidfile /tmp/angular/sauce-connect-pid-file.lock --tunnel-identifier angular-191457-0'
Starting Sauce Connect. Passed arguments:  --readyfile /tmp/angular/sauce-connect-ready-file.lock --pidfile /tmp/angular/sauce-connect-pid-file.lock --tunnel-identifier angular-191457-0
+ /home/circleci/ng/scripts/saucelabs/../../node_modules/sauce-connect/bin/sc -u angular-ci -k 78924453-3ea4-4aa8-acbf-8ff434f889b9 --readyfile /tmp/angular/sauce-connect-ready-file.lock --pidfile /tmp/angular/sauce-connect-pid-file.lock --tunnel-identifier angular-191457-0
6 Feb 16:57:42 - Sauce Connect 4.5.3, build 4602 4b3da11 
6 Feb 16:57:42 - Using CA certificate bundle /etc/ssl/certs/ca-certificates.crt.
6 Feb 16:57:42 - Using CA certificate verify path /etc/ssl/certs.
6 Feb 16:57:42 - Starting up; pid 261
6 Feb 16:57:42 - Command line arguments: /home/circleci/ng/scripts/saucelabs/../../node_modules/sauce-connect/bin/sc -u angular-ci -k **** --readyfile /tmp/angular/sauce-connect-ready-file.lock --pidfile /tmp/angular/sauce-connect-pid-file.lock --tunnel-identifier angular-191457-0 
6 Feb 16:57:42 - Log file: /tmp/sc-angular-191457-0.log
6 Feb 16:57:42 - Pid file: /tmp/angular/sauce-connect-pid-file.lock
6 Feb 16:57:42 - Timezone: UTC GMT offset: 0h
6 Feb 16:57:42 - Using no proxy for connecting to Sauce Labs REST API.
6 Feb 16:57:43 - Started scproxy on port 41049.
6 Feb 16:57:43 - Please wait for 'you may start your tests' to start your tests.
6 Feb 16:57:51 - Secure remote tunnel VM provisioned.
6 Feb 16:57:51 - Tunnel ID: 9393f6611aed4f9785dde63614e1fb6c
6 Feb 16:57:51 - Using no proxy for connecting to tunnel VM.
6 Feb 16:57:51 - Starting Selenium listener...
6 Feb 16:57:51 - Establishing secure TLS connection to tunnel...
6 Feb 16:57:51 - Selenium listener started on port 4445.
Step was canceled
```

**Comment by mhevery** [comment] 2019-02-08 23:16
https://circleci.com/gh/angular/angular/196477?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by devversion** [comment] 2019-02-08 23:46
I've tried to investigate this as much as possible from our side. This is a small status update. Currently waiting for more information from the support team. 

We are limited because `sauce-connect` is not open source, nor the protocol that is used for establishing the tunnels seems to be documented/open-sourced somewhere.

Here is a timed out job with very verbose logging: https://circleci.com/gh/angular/angular/193452

---

**Verbose log findings:**

SauceConnect seems to have a `MAIN` loop that gets stuck in an _infinite loop_. The same
errors show up repeatedly.

1) `SauceConnect` tries to connect to a specific host 
2) This attempt to connect to the host through `Saucelabs KGP` fails:

```bash
"2019-02-07 19:10:12.196 [253] KGP libevent connection error"
```
3) Repeats (1) --> `MAIN` loop --> **Infinite loop**

```bash
2019-02-07 19:10:12.196 [253] MAIN client event loop exiting: 0
2019-02-07 19:10:12.196 [253] MAIN main loop exited, return code: 5
2019-02-07 19:10:12.197 [253] MAIN starting client event loop"
```

**Confirmations/support answers**

* Saucelabs support says: `The return code 5 means that the connection to the tunnel VM was closed from the client's end.`
* Saucelabs support thinks that this could be related to our firewall settings. I've made sure that there is nothing within our CircleCI containers that would do that. CircleCI doesn't mention such a limitation anywhere either. Also it wouldn't explain why it _works_ **sometimes** and _breaks_ sometimes.

* Confirmed on local dev-machine that this is not specific to a firewall. Could reproduce same flakiness on windows with firewall disabled.

**Comment by pkozlowski-opensource** [comment] 2019-02-11 16:57
New instance if it helps tracking: https://circleci.com/gh/angular/angular/198061?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by kara** [comment] 2019-02-14 17:12
Paul's PR should have fixed this. If anyone sees new instances, please re-open with a link to the failing job.

**Comment by AndrewKushnir** [comment] 2019-03-03 20:21
Re-opening this issue, since it started to happen a lot more often, example failure:
https://circleci.com/gh/angular/angular/228330
also you can see the list of failed jobs (due to SauceLabs connection timeout):
https://circleci.com/gh/angular/workflows/angular/tree/master

// cc @devversion

**Comment by devversion** [comment] 2019-03-03 20:47
@AndrewKushnir That's really interesting. For reference: the timeout message includes all type of root causes which lead to a tunnel not being established within 2min. This #29084 should help a bit with clarifying this (there should be different failures)

**Comment by AndrewKushnir** [comment] 2019-03-03 20:52
Thanks @devversion for additional info on that! Let's look at the root causes and create new tickets as needed (and close this one once we identify root causes). Thank you.

**Comment by AndrewKushnir** [comment] 2019-03-05 21:34
FYI after merging recent changes, I see API rate limit errors, for example here:

https://circleci.com/gh/angular/angular/231631

The error message is:
```
2019-03-05 21:03:19.706 [134] error querying from https://saucelabs.com/rest/v1/angular-ci/tunnels/XXX, error was: {"message": "API rate limit exceeded for public:angular-ci. See rate-limiting section in our API documentation."}. HTTP status: 429 Unknown Status
```

**Comment by kara** [comment] 2019-03-21 22:31
This should be fixed. Please re-open if not.

**Closed by kara** 2019-03-21 22:31 UTC
Labels: comp: build & ci, severity5: regression
