### ISSUE TITLE
APP_INITIALIZER not blocking the application startup while loading configurations in 2.4.8

### ISSUE THREAD

**Issue by ahmadqarshi** [angular/angular#14615] opened 2017-02-21 10:47 UTC
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I am loading some application configurations from a json file just before the application loads using APP_INITIALIZER shown below:

    @Injectable()
    export class ConfigService {
      private _config: any;
      constructor(private http: Http) {
      }

      load(): Promise<any> {
        let promise: Promise<any> = new Promise((resolve: any) => {
          this.http.get('app/config/appConfig.json').map(res => res.json())
            .subscribe(config => { 
              this._config = config;
              resolve(true);
            });
        });
        return promise;
      }

      get(key: any) {
        return this._config[key];
      }
    }

    export function initConfiguration(configService: ConfigService): Function {
      return () => configService.load();
    }

    @NgModule({
      imports: [
        //Some imports here.
      ],
      declarations: [AppComponent],
      bootstrap: [AppComponent],
      providers: [
        {
          provide: APP_INITIALIZER,
          useFactory: initConfiguration,
          deps: [ConfigService],
          multi: true
        }
      ]
    })
    export class AppModule { }

There are few services which use the loaded configurations by calling the `get` method defined in `ConfigService`. It was all working fine but after upgrading to 2.4.8, I can see that the `get` function is invoked before the configurations are loaded which produces an error.

**Expected behavior**
`ConfigService.load` should run in blocking mode like it used to work until 2.4.7

**Please tell us about your environment:**
OS: Windows 10 Pro
IDE: Visual Studio Code

* **Angular version:** 2.0.8
* **Browser:** [all]
* **Language:** [TypeScript 2.1 | ES6]

**Comment by DzmitryShylovich** [comment] 2017-02-21 11:07
pls add a plunkr

**Comment by wKoza** [comment] 2017-02-21 13:09
Should not you rather write this: 
```javascript
providers: [
    ConfigService,
    {
      provide: APP_INITIALIZER,
      useFactory: initConfiguration,
      deps: [ConfigService],
      multi: true
    }
  ]

```
?

**Comment by meeroslav** [comment] 2017-02-21 13:10
I guess this might be related to changes done in router [here](https://github.com/angular/angular/commit/541de26f7e7900d8161dc0afbb2cb82c92bb1fc5).

I have a plugin that also stopped working, since router no longer waits for APP_INITIALIZER to finish it's tasks.

@mhevery, @vsavkin: Is this an error or is there another way to block app load in 2.4.8 (or 4.0.0)?

**Comment by mlc-mlapis** [comment] 2017-02-21 23:10
Hmm, we discussed functionality of APP_INITIALIZER yesterday because it seemed that there was a problem with inconsistency. See https://github.com/angular/angular/issues/14601.

I tried some tests with HTTP request and setTimeout simulation of async opperations and everything worked. We finally found out that the original problem was with the order of defined block of code in one plunkr file then.

Correct plunkr: https://plnkr.co/edit/gf170UQuN4oHGdbPA8Vw?p=preview
Wrong plunker: https://plnkr.co/edit/rtMBpe8Vp7EDLtYqPaP9?p=preview

Environment for tests on dev locale:
Windows: 8.1 64 bits, Node: 6.9.5, angular: 2.4.8, systemjs: 0.20.9, rxjs: 5.1.1, zone.js: 0.7.7, TS: 2.0.10

**Comment by cladera** [comment] 2017-02-22 15:43
Same issue here.

**Comment by mlc-mlapis** [comment] 2017-02-22 17:38
@cladera Can you describe your situation a bit more because the problem has to related to something special. The clean test as you can try with plunkr https://plnkr.co/edit/gf170UQuN4oHGdbPA8Vw?p=preview works even with version 2.4.8.We did also tests on local development server and again it works.

**Comment by darianferrer** [comment] 2017-02-22 19:29
I have the same problem, in my app module I define:

`providers: [
        {
            provide: APP_INITIALIZER,
            useFactory: useFactory,
            deps: [SecurityService],
            multi: true
        }
    ]`

`export function useFactory(service: SecurityService) {
    return () => service.userInfo();
}`

service.userInfo:

`userInfo() {
        return this.http.get('/api/security/currentuser', { responseType: ResponseContentType.Json }).map((res: Response) => {
            let json = res.json()
            if (json) {
                this.loginInfo = json;
                return this.loginInfo;
            }
            return null;
        }).toPromise();
    }`

I have a guard set in my routes to redirect to login component if user is not loged in. Until angular 2.4.7 it works: the request is finish before the guard is executed; in latest version, the request is not done when guard is executed.

**Comment by mlc-mlapis** [comment] 2017-02-22 21:20
Oh, thank you. So then it is clear. The problem is directly related and effected by the problem introduced by: https://github.com/angular/angular/issues/14588 and Victor also described the background of the problem and the immediate solution for now and relations to Angular Universal.

It is possible to close this issue.

**Closed** 2017-02-23 01:41 UTC

**Comment by pravash-upreti** [comment] 2017-12-20 08:08
I had solve this problems for temporary

 canActivate(): Observable<boolean> {

        return new Observable<boolean>((observer) => {
            var timer = Observable.timer(0, 100);
            var subscriber = timer.subscribe(t => {
                if (AuthUserService.didConfigLoaded()) {
                    this.Auth = AuthUserService.getLoggedInStatus()
                    if (!this.Auth) {
                        observer.next(true)
                        observer.complete()
                    } else {
                        this.router.navigate(['/']);
                        observer.next(false)
                        observer.complete()
                    }
                    subscriber.unsubscribe()
                }
            });
        })
    }
__________________________________________________________

AuthUserService.didConfigLoaded() is the function which will return the boolean and this boolean is set true when config from server is loaded

**Comment by krushn** [comment] 2019-04-29 11:57
`canActivate(
    route: ActivatedRouteSnapshot,
    state: RouterStateSnapshot
  ): Observable<boolean | UrlTree> | Promise<boolean | UrlTree> | boolean | UrlTree 
  {
    /**
     * new router changes don't wait for startup service 
     */
    return new Promise(resolve => {

      if(this.isLogin) {
        resolve(true);
      }
        
      this._storage.get('loggedInUser').then(data => {
        if (data) {
          this.isLogin = true; 
          resolve(true);
        } else {
          resolve(false);
        }
      });
    });
  }`
