### ISSUE TITLE
Local library "not a known element" error but still builds fine 

### ISSUE THREAD

**Issue by then3rdman** [angular/angular#36275] opened 2020-03-27 11:02 UTC
I believe this is specifically caused by angular 9, very much a guess but the ivy compiler most likely?

When consuming a library generated and built the CLI, both externally via NPM link and in a project in the same workspace, an error is thrown by the editor and some times in the command line (not always) that any components from with the library are "not know elements". However the build will succeed and run perfectly fine.

I am running angular version 9.1. both for the library and the consuming app.

**Comment by petebacondarwin** [comment] 2020-03-27 11:10
Can you provide more detail of the template that is causing the error?

Also when you say, error is thrown in the IDE, do you mean that the "Angular Language Service" plugin for VS Code?

**Comment by then3rdman** [comment] 2020-03-29 03:31
It's every template. Anything that is included from the library has the same error message. As for the error, some times it will show up in the terminal, other times it wont show up in the terminal but in both cases the app spins up fine. 

Yes it is the language service with the errors.

**Comment by then3rdman** [comment] 2020-03-30 00:00
Some more things I have discovered. If i import the modules directly from their source (inside the library project) there is no issue.
`import { DplIconModule } from 'projects/dpl/src/lib/icon/icon.module';`
However if I import as you should be able to using libraries
`import { DplIconModule } from 'dpl';`
There is an error.

**Comment by petebacondarwin** [comment] 2020-03-30 15:45
I assume that you have `paths` mappings setup to achieve the second import?
I think that using `npm link` for your internal library is not a good way to go, since ngcc (which needs to process the library) will not follow symlinks.

**Comment by then3rdman** [comment] 2020-03-30 15:50
So when consuming a library from with in the same workspace, there is not need for path mappings. You can import directly from {'library-name'}. I amusing npm-link for the second app however you can preserve sym links which allows it work. I don't believe this is the issue as the app in the same workspace as the library has the exact same issues. Additionally it is seemingly random as yo when there are erorrs and when not.

**Comment by petebacondarwin** [comment] 2020-03-30 16:01
Is it possible that you could create some reproduction that you could share with me?

**Comment by alxhub** [comment] 2020-05-26 22:08
Closing as no reproduction was provided. @then3rdman, if you're still experiencing this issue please feel free to open a new report with a reproduction. Thanks!

**Closed by alxhub** 2020-05-26 22:08 UTC
Labels: comp: compiler, comp: language-service, state: Needs repro, type: bug/fix, type: support
