### ISSUE TITLE
For loops in new control flow are extremely slow and taking much more memory than ngFor

### ISSUE THREAD

**Issue by naveedahmed1** [angular/angular#52524] opened 2023-11-06 12:14 UTC
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

I recently upgraded an Angular app to new control flow. All I did was:

1. Run automatic migration
2. Fix components where the migration didn't properly updated the code to the new syntax

On few components where we have large lists with infinite scroll, the app becomes very unresponsive as soon as we start loding more data to the list and list becomes large.

This was working perfectly with old ngFor syntax.

I have tried it with inline list as well as moving list to a seperate component with `ChangeDetectionStrategy.OnPush`.

### Please provide a link to a minimal reproduction of the bug

For this I can add you to a private repo

### Please provide the exception or error you saw

```true
The app becomes unresponsive and starts consume more memory 4Gb-6Gb.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.0.0-rc.3
Node: 18.18.2
Package Manager: npm 9.8.1
OS: win32 x64

Angular: 17.0.0-rc.2
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.0-rc.3
@angular-devkit/build-angular   17.0.0-rc.3
@angular-devkit/core            17.0.0-rc.3
@angular-devkit/schematics      17.0.0-rc.3
@angular/cdk                    17.0.0-rc.1
@angular/cli                    17.0.0-rc.3
@angular/fire                   16.0.0
@angular/google-maps            17.0.0-rc.1
@angular/material               17.0.0-rc.1
@angular/pwa                    17.0.0-rc.3
@schematics/angular             17.0.0-rc.3
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.0
```

**Comment by zip-fa** [comment] 2023-11-06 12:36
Please give repro link so team can verify your issue. May be related to track’ing or making function calls inside for loop

**Comment by pkozlowski-opensource** [comment] 2023-11-06 13:47
> For this I can add you to a private repo

@naveedahmed1 we will need a small reproduction indeed - please try to isolate the issue so it is easier for us to understand what is going on.

**Comment by naveedahmed1** [comment] 2023-11-06 15:15
Sure, I will share the repo soon.

**Comment by pkozlowski-opensource** [comment] 2023-11-06 16:16
> Sure, I will share the repo soon.

Thnx. Would appreciate if it is as minimal as possible ❤️

**Comment by naveedahmed1** [comment] 2023-11-06 20:25
@pkozlowski-opensource I have added you to the repo. I have also added the instruction in the readme file.

**Comment by JeanMeche** [comment] 2023-11-06 23:15
Also interesting I think, the repro that was provided for #36878 (a memory leak with the DefaultIterableDiffer) just freezes the app with the new control flow syntax.

**Comment by naveedahmed1** [comment] 2023-11-06 23:51
@JeanMeche we are also noticing some random app freez.

**Comment by pkozlowski-opensource** [comment] 2023-11-08 21:02
I believe that I've go a fix for this issue in https://github.com/angular/angular/pull/52697 - it is really one-liner change in https://github.com/angular/angular/pull/52697/files#diff-50d29735590abe5158e57a756c63b2d04c0bfd65bbd6a75c4ee48ca82c8ee1caR291 - if anyone is facing similar issue and want to test with a patched Angular version it would be appreciated!

**Comment by naveedahmed1** [comment] 2023-11-09 02:45
I'd be happy with test that, can you please guide how to try this?

**Comment by pkozlowski-opensource** [comment] 2023-11-09 15:17
@naveedahmed1 after profiling your scenario it turns out that your issue is not linked to the repeater at all. So the issue I've fixed in https://github.com/angular/angular/pull/52697 is a different one.

I do understand what is going on in your case and working on a fix. Thnx for reporting and sharing a reproduction scenario!

**Comment by naveedahmed1** [comment] 2023-11-09 15:30
Thank you so much @pkozlowski-opensource for the update.

**Comment by pkozlowski-opensource** [comment] 2023-11-09 15:51
Re-opening since we will need another PR to fully resolve it.

**Closed** 2023-11-09 19:58 UTC
Labels: needs reproduction, area: core, core: control flow

**Comment by naveedahmed1** [comment] 2023-11-09 21:00
This indeed was pretty quick, thank you @pkozlowski-opensource and @jessicajaniuk.

**Comment by naveedahmed1** [comment] 2023-11-09 21:40
I can see [v17.0.2](https://github.com/angular/angular/releases/tag/17.0.2) on github but I think neither 17.0.2 nor 17.0.1 are availble on npm.

**Comment by pkozlowski-opensource** [comment] 2023-11-09 21:42
Yay, @jessicajaniuk did a fantastic job cutting another release. @naveedahmed1 17.0.2 should be on npm: https://www.npmjs.com/package/@angular/core/v/17.0.2

**Comment by naveedahmed1** [comment] 2023-11-09 21:57
I tried `ng update @angular/cli @angular/core @angular/pwa --create-commits=true --force=true --next` it didnt update anything. Probabbly due to the `--next` flag, removing `--next` worked.

It seems the issue still exists, its not taking that much memory now but as soon as we scroll the list and load more items to the list, the dropdown menu starts taking more time to open. I understand rendering more items would ultimately make the app slow, but surprizingly it was'nt the case with `NgFor` I believe.

**Comment by pkozlowski-opensource** [comment] 2023-11-09 22:14
@naveedahmed1 I've actually tested with your repro and saw the issue being fixed with my PR. So we are clearly seeing different results. Could you please  push the updated reproduction scenario to make sure that we are looking at the same set of pcakages?

**Comment by naveedahmed1** [comment] 2023-11-09 22:45
I just pushed the updated reproduction with `17.0.2`. Scroll till around 20 pages and you should notice that the menu taking time.

**Comment by pkozlowski-opensource** [comment] 2023-11-10 08:46
@naveedahmed1 thnx for sharing the updated reproduction! Given the updated code I could see the following:
* the fix from https://github.com/angular/angular/pull/52742 is making massive difference so the actual fix from there works;
* I've understood the source of the slowness for the dropdown opening and and it is _not_ related to the new control flow in any way.

The dropdown menu opening is slow since clicking ion the toggle button runs change detection multiple times. In fact, the change detection is run as many times as there are rows in the jobs collection (!!!).

This is due to the `@HostListener('document:click', ['$event', '$event.target'])` in the `MenuDirective`. Each directive instance (present on each and every row): 
* will add a new event listener;
* all those event listeners will fire on each menu toggle;
* each event handler will trigger a _separate_ change detection.

There are many ways of addressing this issue, I would argue that the easiest one is to make sure that only one event listener is registered on the document level (this would require re-design of the menu directive). Another option is to use event coalescing on the zone.js level.

In any case, I believe that this is _not_ related to the new control flow - I think that you would see the same issue with `ngFor`. But I'm happy to look into it more if you can share a branch with the `ngFor`-based implementation and much better performance.

**Comment by naveedahmed1** [comment] 2023-11-10 14:37
Thank you so much @pkozlowski-opensource for looking it in more details.

Yes you are right, removing `@HostListener('document:click', ['$event', '$event.target'])` actully fixed the issue. I have tested it with with even 50 pages and the performance is consistant. And yes the PR you mentioned fixed the memory issue, and now it's not increasing exponentially, no matter how many pages you scroll.

I will have to find a way to avoid multiple event listners.

>  I would argue that the easiest one is to make sure that only one event listener is registered on the document level (this would require re-design of the menu directive).

Can you please provide any direction on this? I think there's no built in way, neither `Renderer2` has any support for this, It has a listen function but that doesnt check if the event listner already exists.
