### ISSUE TITLE
[routerLink] tries to bind to href when used in a button with Router 3.0-alpha.7

### ISSUE THREAD

**Issue by michaeloryl** [angular/angular#9561] opened 2016-06-24 03:06 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Cannot use `[routerLink]` on a `button`, only on an `a` tag (anchor).
You get an error like this:

```
EXCEPTION: Error: Uncaught (in promise): Template parse errors:
Can't bind to 'href' since it isn't a known native property ("            <ul class="nav navbar-nav">
	                <li class="nav-item">
	                    [ERROR ->]<button [routerLinkActive]="['active']" [routerLink]="['/public']" class="nav-link btn btn-success-ou"): Navbar@9:21
```
**Expected/desired behavior**
Should be able to use `[routerLink]` on a `button`

**Reproduction of the problem**

Any button with routerLink in it, like `<button [routerLink]="['/public']">Public</button>`

**What is the expected behavior?**

Same as you get with `<a [routerLink]="['/public']">Public</a>`

**What is the motivation / use case for changing the behavior?**

I upgraded to router 3.0-alpha.7 from RC2 of router-deprecated, and now have to use `a` links where I had been using buttons.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.3
 
* **Browser:** [all] 
 
* **Language:** [TypeScript]

**Comment by michaeloryl** [comment] 2016-06-24 03:17
Related to [8357](https://github.com/angular/angular/issues/8357).

In this case I'm using Bootstrap 4 (yes) and I need to use the `disabled` attribute in a button (it's not available on an anchor tag), and I also need to use the `routerLinkActive`. I can't wrap the button with an anchor because then the `routerLinkActive` directive wouldn't work - plus it's just plain weird.

**Comment by vsavkin** [comment] 2016-06-25 20:10
This is a duplicate of #9471.

**Closed by vsavkin** 2016-06-25 20:10 UTC
Labels: comp: router, type: feature
