### ISSUE TITLE
FormControl doesn't update fields when used in multiple locations.

### ISSUE THREAD

**Issue by ShiftySituation** [angular/angular#22199] opened 2018-02-13 15:17 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When using the same FormControl on multiple input fields, the values shown are not updated on all input fields when one field is edited.

## Expected behavior

Proper 2-way binding should reflect like with ngModel.

## Minimal reproduction of the problem with instructions

[https://stackblitz.com/edit/angular-vhhfqb](https://stackblitz.com/edit/angular-vhhfqb) 
This stackblitz shows the behavior using FormControls as well as ngModel.  As you can see, ngModel updates both input fields where the formControl does not.

## What is the motivation / use case for changing the behavior?

Segmenting long forms where it makes sense to show the same input on multiple sections

## Environment

<pre><code>
@angular/cli: 1.4.0-rc.2

Browser:
- [ x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.2.1  
- Platform:  win32 x64 

Others:

</code></pre>

**Comment by kara** [comment] 2018-02-14 00:02
Dupe of https://github.com/angular/angular/issues/13792

**Closed by kara** 2018-02-14 00:02 UTC
Labels: comp: forms
