### ISSUE TITLE
"Final code review" on Step 5 of Tour of Heroes tutorial doesn't link to the right code

### ISSUE THREAD

**Issue by jdob** [angular/angular#45814] opened 2022-04-29 14:06 UTC
### Description

This bug is in reference to the page: https://angular.io/tutorial/toh-pt5

Under "Final code review", the code snippets appear to be organized in groups (e.g. "AppRoutingModule", "AppModule", and "HeroService" is one such group). The actual code mentioned in those sections don't appear to match the section headers. For example, both the first and second group contain the code for `hero-search.component.html`, but HeroSearch isn't mentioned in either group name. Additionally, the `app-routing-module.ts` file isn't listed anywhere (I'm guessing it belongs in the first section). 

### What is the affected URL?

https://angular.io/tutorial/toh-pt5

### Please provide the steps to reproduce the issue

View tutorial page

### Please provide the expected behavior vs the actual behavior you encountered

Admittedly, I'm not 100% sure. The issue might be that the groups are mislabeled, or the code snippets are incorrectly grouped/missing entirely. Or some combination of the two.

**Comment by dario-piotrowicz** [comment] 2022-04-30 09:15
I think this is a duplicate of https://github.com/angular/angular/issues/45736

**Closed** 2022-04-30 10:33 UTC
Labels: comp: docs
