### ISSUE TITLE
Cannot build 5.2 with bazel

### ISSUE THREAD

**Issue by jelbourn** [angular/angular#21456] opened 2018-01-10 22:11 UTC
PR #20678 introduced [`ParamsInheritanceStrategy` to `router_state.ts`](https://github.com/angular/angular/blob/master/packages/router/src/router_state.ts#L178-L179) marked as `@internal`. The tsconfig config is set to `stripInternal`, so the symbol is removed from the published d.t.s, but the type is [still referenced from `pre_activation.ts`](https://github.com/angular/angular/blob/master/packages/router/src/pre_activation.ts#L24), causing a compilation error if you try to compile with Angular's d.ts files.

To reproduce, simply try to compile anything that's using the problematic d.ts files
(e.g., using Angular Material's [angular.tsconfig.build](https://github.com/angular/material2/blob/master/angular.tsconfig.json), which is needed for bazel).

**Comment by pshields** [comment] 2018-01-16 17:50
I notice in #20678 that there are several places where the `ParamsInheritanceStrategy` type could seemingly be used, but ''emptyOnly' | 'always'` is hard-coded instead. I'm not sure why one or the other isn't done consistently.

@voithos, do you recall why the ParamsInheritanceStrategy type wasn't used consistently?

I'm also curious why this wasn't caught by testing. Is there some kind of test we can add that tries to compile the project after `stripInternal` step has been applied?

**Comment by pshields** [comment] 2018-01-16 18:24
It looks like the `stripInternal` setting has caused breakages before (#8819) but the tests may not have been updated to catch this kind of bug.

**Comment by pshields** [comment] 2018-01-16 19:06
I have sent out a PR with what I believe is the simplest solution to this regression--removing the `@internal` tag from the type so that it will remain in the relevant .d.ts file and resolve the compilation error.

**Comment by voithos** [comment] 2018-01-16 19:17
I believe the original reasoning, per the discussion in the PR, was to avoid littering the public namespace with yet-another type alias. Thus, `ParamsInheritanceStrategy` was used internally for consistency, whereas the external types used the (equivalent) `'emptyOnly'|'always'`.

Does this imply that anything in `pre_activation.ts` is public...?

**Comment by pshields** [comment] 2018-01-16 21:01
Thanks @voithos; it sounds like updating `pre_activation.ts` to use `'emptyOnly' | 'always'` in place of `ParamsInheritanceStrategy` would also be another reasonable solution here, then.

> Does this imply that anything in pre_activation.ts is public...?

Check out https://github.com/angular/router-builds/blob/master/src/pre_activation.d.ts to see the declarations produced for `pre_activation.ts`. Is that what you mean? Even though those declarations are not directly part of the router's public API surface, they are still public to consumers of the package, and I believe the use of `ParamsInheritanceStrategy` there is part of the problem.

**Comment by voithos** [comment] 2018-01-16 21:54
Ah, that may have been the oversight, then. I think the intent was to keep it internal. Using `'emptyOnly' | 'always'` in `pre_activation.ts` sounds like a reasonable solution, but @IgorMinar would be able to confirm.

**Comment by pshields** [comment] 2018-01-16 22:10
In case that is the preferred approach, I've put out #21574 as an alternate PR.

**Comment by pshields** [comment] 2018-01-22 20:09
Ping. I have PRs out for both of the two solutions discussed so far (#21563 or #21574). Can someone on the core team review/merge one of them so this can get into the next patch release?

**Comment by IgorMinar** [comment] 2018-01-22 22:22
@pshields can you please merge #21563 and #21574 into a single PR and rebase against master. I'd like to get this in before our release on Tuesday evening / Wednesday.

**Comment by pshields** [comment] 2018-01-23 12:16
@IgorMinar either one fixes the regression, so IMO merging both would be redundant - I'd recommend merging #21574 based on earlier discussion in this issue.

If you do you really want to merge both, let me know and I'll proceed with combining them into a single PR.

**Comment by IgorMinar** [comment] 2018-01-24 04:41
Thanks. I picked the #21574. I think we'll need both eventually because we
want to remove all `@internal` annotations, but #21574 is good enough for
now.

**Comment by pshields** [comment] 2018-01-25 12:00
It turns out there is one other file, `packages/router/src/recognize.ts`, whose published declarations reference `ParamsInheritanceStrategy`, so this is still an issue. Can someone reopen this?

Sorry - missing it was my mistake. :(

Although I had searched for all occurrences of ParamsInheritanceStrategy in the published declarations, I must have either missed it, or incorrectly assumed that this other reference was not in the compilation path, since it hadn't shown up in the original error.

Based on @IgorMinar's [earlier comment](https://github.com/angular/angular/issues/21456#issuecomment-360019021) about wanting to eventually remove all `@internal` annotations, I've put out #21773 which removes the `@internal` annotation on `ParamsInheritanceStrategy`. That change avoids this class of error in the first place by making the type definition available in the declarations. Since AFAIK Angular doesn't currently have a good way to test the compilation of the published package yet, I think that's the safest way to do it.

**Comment by hmagrini** [comment] 2018-01-30 16:15
I was going to open another issue, but since it's related to the `@angular/router` maybe we should track here as well.

As referenced on https://github.com/angular/angular/pull/21898, there seems to be another issue when compiling with Bazel, but it's unrelated to `ParamsInheritanceStrategy`. 

Compiling `@angular/router` throws the following error:

```
node_modules/@angular/router/upgrade/src/upgrade.d.ts(9,31): error TS2307: Cannot find module '@angular/upgrade/static'.
```

Isolated repro steps are simple:
1) clone https://github.com/alexeagle/angular-bazel-example
2) run `bazel run @yarn//:yarn` -> build succeeds
3) run `yarn add @angular/router` 
4) run `bazel run @yarn//:yarn` -> build fails with above error

**Comment by mhevery** [comment] 2018-01-30 22:58
@alexeagle ^^^

**Comment by hmagrini** [comment] 2018-01-31 10:54
@mhevery I was kinda unsure to open it on that repo since the issue seems more related to `@angular/upgrade/static` exports rather than the Bazel build (or at the very least with `ngc` compilation). 

The error seems to be caused when `@angular/router` tries to import `UpgradeModule` [here](https://github.com/angular/angular/blob/master/packages/router/upgrade/src/upgrade.ts#L11), and although that module does [get exported](https://github.com/angular/angular/blob/master/packages/upgrade/static/public_api.ts#L21), it seems that the whole `@angular/upgrade/static` can't be found.

**Comment by alexeagle** [comment] 2018-01-31 15:19
I think that `@angular/upgrade` is meant as an optionalDependency from `@angular/router` - it doesn't make sense for a greenfield Angular app to install ngUpgrade if they have no history with AngularJS.

I wonder if this is reproducible outside of Bazel - I agree with you it ought to be. Just type-checking the router's .d.ts files would fail if ngUpgrade is not installed.

/cc @jasonaden

**Comment by alexeagle** [comment] 2018-02-09 00:01
Discussed in person with @IgorMinar - we want to understand better why this error is visible only under Bazel and not for all Angular users - I can't see why it's a difference

**Comment by IgorMinar** [comment] 2018-04-10 22:59
I believe that his has been resolved already. Can this issue be closed?

**Comment by alexeagle** [comment] 2018-04-10 23:01
I don't think we should close this until
- the integration tests run against bazel output
- the bazel integration test uses `@angular/router` like in the report above

**Comment by alxhub** [comment] 2019-02-26 23:28
Per @jelbourn this is no longer a regression (but I agree with @alexeagle about closing this).

**Comment by alexeagle** [comment] 2019-03-19 21:11
@kyliau this is basically asking for the same improved integration test coverage that we just added to the sprint

**Comment by kyliau** [comment] 2019-03-22 20:29
https://github.com/angular/angular/pull/29459 improved coverage by exposing and fixing https://github.com/angular/angular/issues/29454

**Comment by alexeagle** [comment] 2019-03-22 21:34
I think it's fixed then, cool!

**Closed by alexeagle** 2019-03-22 21:34 UTC
Labels: comp: bazel, flag: can be closed?, hotlist: angular-core-team, hotlist: material2, type: bug/fix
