### ISSUE TITLE
Change detection for async Observable.

### ISSUE THREAD

**Issue by infacto** [angular/angular#48195] opened 2022-11-23 12:29 UTC
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

Not sure if this is a bug, improvement or feature request. But currently the "async" pipe is not a guarantee to safely update the UI when the value changes. If the value is an `Observable` and the `next` method of the underlaying `Subject` is updated outside the zone, the template does not update. I thought that an `Observable` in template with `async` always automatically updates the value / triggers change detection (depending on update strategy). Currently I have to call `next` in `NgZone#run`. Why does Angular not subscribe to it when using `async` and updates the template when the value changed? This behavior is maybe intended. But what do you think to simplify this case? For example with an option in Component config or a special pipe like `inZone` or a configuration for `async`.

### Proposed solution

It would be great there is an easy way to update values in template which are changed outside the zone. Especially for Observables. Personally I expect UI updated when using `observable | async`. Regardless if `observable.next(value)` is run outside the zone or not.  And for external observable, I need to wrap it to run in zone. Results in too much confusing and ugly code. Maybe I missed something what solve my issue. But consider to add this if there is no elegant solution yet.

### Alternatives considered

I have to wrap any value to run in zone. Subscribe to observable and unsubscribe on component destroy.

```ts
class MyComponent {
  subscription: Subscription;
  ngOnInit() {
    this.subscription = this.observable.subscribe((value) => this.ngZone.run(() => this.value = value));
  }
  ngOnDestroy() {
    this.subscription.unsubscribe();
  }
}
```

Background: I get values as observables from an external library (native plugins on Android; Ionic; Cordova) which doesn't run in Angular Zone. But I want this be updated in Angular HTML template. Workaround is wrapping in zone or e.g. use `setInterval` dummy for period trigger change detection. 

Possible solution to wrap a value in zone (e.g. just set the same value to it):

```html
<div>{{ myValue | async | inZone }}</div>
```

### Summary

**It would be great if I could tell Angular to run everything in template in its Zone.** Either as config in Component or pipe, etc.

(Angular 14)

**Comment by JeanMeche** [comment] 2022-11-23 14:23
That’s a dupe of #36139

**Comment by pkozlowski-opensource** [comment] 2022-11-30 15:04
> Why does Angular not subscribe to it when using async and updates the template when the value changed?

As of today the `async` pipe does _not_ trigger change detection: it only marks a given component as "dirty" (needing change detection). 

We do plan to make several improvements in this area as part of making zone.js optional. But this is a major undertaking / project that will be running throughout 2023.

I'm going to close this issue for now as there is no additional info for us here and nothing immediately actionable.

**Closed by pkozlowski-opensource** 2022-11-30 15:04 UTC
Labels: area: core, core: change detection, cross-cutting: observables
