### ISSUE TITLE
Ampersand within embedded expressions causes HTML entities not to render

### ISSUE THREAD

**Issue by mcv203** [angular/angular#46931] opened 2022-07-21 21:51 UTC
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

When an ampersand appears in an embedded expression, for example as part of a logical operator or literal, and the expression can evaluate to an HTML entity, that entity may not display properly.  E.g. <pre>{{(true && true) ? '&amp;ndash;' : '&amp;eacute;'}}</pre> results in the string "&amp;ndash;" being displayed.

More specifically, it appears that all characters from any ampersand to the subsequent semicolon are interpreted as if they are an entity regardless of placement, as can be seen in the reproduction:
<pre>
{{(true && true) ? '&amp;ndash;' : '&amp;eacute;'}} -> renders the string "&amp;ndash;"
{{(true && ';') ? '&amp;ndash;' : '&amp;eacute;'}} -> renders &ndash; (an en dash)
</pre>

Examples in the reproduction follow:
![image](https://user-images.githubusercontent.com/109766913/180320422-9c1a69c8-832c-46d2-90b6-ea8c1a2a330a.png)

I recently upgraded from Angular 11 to 14 following the instructions.  I do not believe this existed in the earlier version, but suppose I can't be 100% positive of that.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-znh2ze

### Please provide the exception or error you saw

```true
HTML entity renders as a string instead of the symbol.  No error is reported.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 14.0.6
Node: 14.15.1
Package Manager: npm 6.14.5
OS: win32 x64

Angular: 14.0.6
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1400.6
@angular-devkit/build-angular   14.0.6
@angular-devkit/core            14.0.6
@angular-devkit/schematics      14.0.6
@angular/cdk                    14.0.5
@schematics/angular             14.0.6
rxjs                            6.6.3
typescript                      4.7.4
```

### Anything else?

This is my first bug report, so let me know if I'm missing anything or if there's an easy way to know which package.  Thank you!

**Comment by pkozlowski-opensource** [comment] 2022-07-22 07:20
> HTML entity renders as a string instead of the symbol.  No error is reported.

I believe that this is the intended behaviour. An expression evaluates to a string that is used to update text [node value](https://developer.mozilla.org/en-US/docs/Web/API/Node/nodeValue). You can think about it as being an equivalent of:

```javascript
const tn = document.createTextNode('');
tn.nodeValue = '&ndash;';

console.log(tn.nodeValue);
```

I'm actually surprised that some of those entities are actually rendered (!). There is clearly something inconsistent going on with our expression parsing.

**Comment by pkozlowski-opensource** [comment] 2022-07-22 09:08
Update: this is a valid bug report. It seems like we _do_ replace some of the entities in expression (it is not fully intentional, mostly for historical reasons).

**Comment by pkozlowski-opensource** [comment] 2022-08-17 12:42
The root cause here is the same as in #40902 - the long story short is that our parser doesn't recognize the context of HTML text nodes vs. expressions. But fixing it in the compiler would mean that entities are _not_ replaced, as indicated in my [initial comment](https://github.com/angular/angular/issues/46931#issuecomment-1192264772)

**Comment by JeanMeche** [comment] 2022-12-02 18:35
I'd say it's a dupe of #44827

**Closed** 2024-02-11 18:56 UTC
Labels: area: core, area: compiler, core: binding & interpolation, P3, compiler: parser, bug
