### ISSUE TITLE
2.0.0-alpha.13 fails in Safari

### ISSUE THREAD

**Issue by ajoslin** [angular/angular#1006] opened 2015-03-18 23:11 UTC
Error: http://ajoslin.co/Vi2o
`SyntaxError: Cannot use initialiser syntax in a strict mode enumeration.`

Line 5155 of code has the error:  http://ajoslin.co/9NDW

It looks like MapWrapper#createFromStringMap does an illegal strict mode operation in Safari.

It's the first line of this for loop: https://github.com/angular/angular/blob/master/modules/angular2/src/facade/collection.es6#L11-L17

This is weird and might be a Traceur problem.

**Comment by robwormald** [comment] 2015-03-25 04:54
yeah, this is an indeed an issue in traceur, fixed here https://github.com/google/traceur-compiler/issues/1647

We fixed it temporarily with perhaps the dirtiest hack I have ever done, ever.
```js
gulp.task('safarihack',['transpile'],function(){
  gulp.src(['temp/app-bundle.js'])
    .pipe(replace(" = void 0 in "," in "))
    .pipe(gulp.dest('dist/'))
});
```

**Comment by zoe-1** [comment] 2015-04-02 19:39
Just downloaded the quick start tutorial learned about from Brad Greens twitter post today. 
I was using Safari and got errors:
[Error] ReferenceError: Can't find variable: System
global code (index.html, line 5)
[Error] SyntaxError: Cannot use initialiser syntax in a strict mode enumeration.
(anonymous function) (es6-shim.js, line 4941)
Hope this helps.

**Comment by naomiblack** [comment] 2015-06-01 22:00
@alexeagle can you check whether this is still an issue, post-ts-ification?

**Comment by alexeagle** [comment] 2015-06-01 23:15
Closing as dupe of #2163 
Which should be fixed as of next release (alpha-26)

**Closed by alexeagle** 2015-06-01 23:15 UTC
Labels: comp: build/pipeline, effort: day, P2: required, type: bug
