### ISSUE TITLE
IVY: animation performance issues, on :enter trigger

### ISSUE THREAD

**Issue by kukjevov** [angular/angular#35029] opened 2020-01-29 09:40 UTC
# 🐞 bug report

### Affected Package
probably one of these

`@angular/core`
`@angular/animations`
`@angular/common`

### Is this a regression?

Yes it is much more fluent with less FPS drops during animations in version 8.

### Description

When new part of template is added using `ngIf` animation framerates drops much more drastically than in previous version of *Angular*.

This happens also when animating route, so it means any new template, component is added using `ViewContainerRef`.

Here are measured results, same page same operation, top is v9.0.0-rc.11 IVY, bottom v8.2.0:
![problem](https://raw.githubusercontent.com/ressurectit/ressurectit.github.io/master/AnimationPerformance.8vs9ivy.png)

## 🔬 Minimal Reproduction

I have it only on private project with quite complicated page with many many components. I`ll try to mock it and paste it here as sample.

## 🔥 Exception or Error
No exception.

## 🌍  Your Environment

**Angular Version:**
Angular 9-rc.11

**Anything else relevant?**
Windows: 10.0.17763
Node: 11.6.0
NPM: 6.9.0

**Comment by pkozlowski-opensource** [comment] 2020-01-29 13:42
@kukjevov thnx for the report, we are definitively interested in the perf of real-life applications. Having said this we will need some form of a reproduce scenario - as you imagine it is hard to say more at this point without being able to profile...

**Comment by kukjevov** [comment] 2020-01-29 14:24
I will try to take existing code and just mock data and provide it i hope it will work, tomorrow i should have time for this :).

**Comment by kukjevov** [comment] 2020-01-30 08:30
Here is repo for reproduction.

> `git clone https://github.com/kukjevov/ng-universal-demo.git`
> `cd ng-universal-demo`
> `git checkout perfIvy/1.0`
> `npm install`
> `npm start`
> open `http://localhost:8888/perfSample/hodnotenie/VAST-101-VSETCI-N18583-201702;state=JTdCJTIyU1VNQVIlMjIlM0ElN0IlMjJkZXRhaWwlMjIlM0F0cnVlJTJDJTIyY2hhcnQlMjIlM0F0cnVlJTdEJTJDJTIyU1BPTFUlMjIlM0ElN0IlMjJkZXRhaWwlMjIlM0F0cnVlJTJDJTIyY2hhcnQlMjIlM0FmYWxzZSU3RCUyQyUyMlBSSUFNRSUyMiUzQSU3QiUyMmRldGFpbCUyMiUzQXRydWUlMkMlMjJjaGFydCUyMiUzQWZhbHNlJTdEJTJDJTIyU1ZMWiUyMiUzQSU3QiUyMmRldGFpbCUyMiUzQXRydWUlMkMlMjJjaGFydCUyMiUzQWZhbHNlJTdEJTJDJTIyUFJFU0tSJTIyJTNBJTdCJTIyZGV0YWlsJTIyJTNBZmFsc2UlMkMlMjJjaGFydCUyMiUzQWZhbHNlJTdEJTdE`

Most of the code that you can see on that page is here https://github.com/kukjevov/ng-universal-demo/tree/perfIvy/1.0/app/pages/%2Bperf

And to simulate performance problem itself you have to expand (click) on first `plus` sign on right side on line *priamo poskytnutá ZS*, or any other `plus` to expand. You can see tearing during animation. I know that there is a lot of html but in version 8 of *Angular* it is much less visible to human eye, it looks and in fact it is more fluent. Also you can see it in performance measurement.

If lower blocks are collapsed it is not there. But still there is quite difference with previous version of Angular. 

Also animation between routes is much less fluent or sometimes even not visible (it just renders it without animation) if new route contains a lot of html/components.

Thx for any help.

**Comment by pkozlowski-opensource** [comment] 2020-01-30 11:20
@kukjevov thnx for sharing the repository with the reproduce scenario - I was able to run the application and profile it.

One major observation so far: when I do `npm start` your application seems to be running in the ivy development mode (look for `ngDevMode` in the source code - normally it should be tree-shaken away; also when you type `ngDevMode` in a browser console, you will see that it is defined - this shouldn't be the case).

Please note that the VE and ngIvy activate prod mode differently (programatic in VE and build-time in ngIvy). I had a brief look at your package.json and it seems like the setup you've shared isn't using angular-cli. Is this the case? This would explain why `ngDevMode` is not tree-shaken away.

Anyway, comparing ngIvy perf in dev mode to VE in prod mode will obviously show that VE is faster. So the first thing here would be to modify your build to make sure that ivy runs in the prod mode.

**Comment by kukjevov** [comment] 2020-01-30 11:38
hi @pkozlowski-opensource thx,

no I am not using Angular CLI :), i rather have full control over build process. Yes ng dev mode is set to `true` if you run it as `npm start`. If you run `npm run build:min` it is set to `false`. But it will also minify sources. So if you want to try it in `npm start` just change it here https://github.com/kukjevov/ng-universal-demo/blob/perfIvy/1.0/webpack.config.js#L278

Just one question what does VE means ?

**Comment by kukjevov** [comment] 2020-01-30 11:39
If you want test my *production* build, you have to run `npm run build:min` and then `npm run server` and it will run on same address.

**Comment by pkozlowski-opensource** [comment] 2020-01-30 13:23
@kukjevov thnx for the additional info - I was able to build your app in the prod mode with `npm run build:min` but then JS is indeed minified. I must say that I'm lost in your setup so what I would like to get is a production with JS mangling (renaming) off - all other parts of the production pipeline should run, just JS renaming should be skipped. Could you help me modify this setup in a way that I can get the above? 

> Just one question what does VE means

View Engine - default rendering engine in version 8. I was assuming that with v8.2.0 you were running on view engine. Unless you had ivy activated in v8.2.0 as well?

**Comment by kukjevov** [comment] 2020-01-30 13:54
Ok i will update repo, turn of mangling of names. 

I have tried ivy also in version 8, but only tried (since it was not ready), on version 8 i am using non ivy build so it uses View Engine as you said. Thx for explanation of VE :).

**Comment by pkozlowski-opensource** [comment] 2020-01-30 13:58
> Ok i will update repo, turn off mangling of names, then i will let you know.

Thank you, it would be very helpful.

Another quick observation: there are warnings in the console (`Can't bind to 'ngIf' since it isn't a known property of 'div'.`) that comes from the `VahaTagComponent` (as far as I can tell). Constructing this warning "costs" a _lot_ (~9% of the entire JS execution time) - calls to `console.warn` are pretty expensive since we are calling native APIs. 

So one of the things would be to look into this warning - maybe the `VahaTagComponent` is _not_ part of the module where `CommonModule` was imported?

**Comment by pkozlowski-opensource** [comment] 2020-01-30 14:13
@kukjevov one last (and super important observation) - I did `npm run build:min` and then `npm run server` and after loading an app in a browser I can see that the code is minified BUT `ngDevMode` is _still_ part of the bundle (just search for it) and accessible in the console.

This means that the `ngDevMode` is not tree-shaken properly and your application run in the development mode. As such there is no point in talking about performance here...

You need to modify your build so your minifier removes `ngDevMode` completely (it should _not_ be part of any bundle).

**Comment by kukjevov** [comment] 2020-01-30 14:19
Hmm ok, i have updated it.

Are you telling me that if you build `npm run build:min` you can find `string` `ngDevMode` in compiled `.js` files? 

Because i have just done it and i cant see it anywhere. I am going to try `console.log(ngDevMode)` in browser.

**Comment by kukjevov** [comment] 2020-01-30 14:43
Ok i have checked it once again.

If you run `npm run build` you can find in `dependencies.js` around 4000 occurences of `ngDevMode` and you can print `console.log(ngDevMode)` and it prints out counters.

If you run `npm run build:min` you can not find any occurence of `ngDevMode` in any `*.js` file in `wwwroot/dist` and also `console.log(ngDevMode)` prints out error **ReferenceError: ngDevMode is not defined**.

I do not see any problem with build :). It is exactly as you requested (maybe some cache?).

Also i do not see any warning which you mentioned. It is also weird because `VahaTagComponent` is part of `CommonSharedModule` which imports `CommonModule` so this should not happen.

I am going to try one more thing download clean repo and remove all npm cache, because i do not understand this different behavior.

Thx for help anyway :)

**Comment by kukjevov** [comment] 2020-01-30 15:04
Ok i have tried it once again all from start.

> `npm cache clear -f`
> `git clone https://github.com/kukjevov/ng-universal-demo.git`
> `cd ng-universal-demo`
> `git checkout perfIvy/1.0`
> `npm install`
> `npm run build:min`
> open `http://localhost:8888/perfSample/hodnotenie/VAST-101-VSETCI-N18583-201702;state=JTdCJTIyU1VNQVIlMjIlM0ElN0IlMjJkZXRhaWwlMjIlM0F0cnVlJTJDJTIyY2hhcnQlMjIlM0F0cnVlJTdEJTJDJTIyU1BPTFUlMjIlM0ElN0IlMjJkZXRhaWwlMjIlM0F0cnVlJTJDJTIyY2hhcnQlMjIlM0FmYWxzZSU3RCUyQyUyMlBSSUFNRSUyMiUzQSU3QiUyMmRldGFpbCUyMiUzQXRydWUlMkMlMjJjaGFydCUyMiUzQWZhbHNlJTdEJTJDJTIyU1ZMWiUyMiUzQSU3QiUyMmRldGFpbCUyMiUzQXRydWUlMkMlMjJjaGFydCUyMiUzQWZhbHNlJTdEJTJDJTIyUFJFU0tSJTIyJTNBJTdCJTIyZGV0YWlsJTIyJTNBZmFsc2UlMkMlMjJjaGFydCUyMiUzQWZhbHNlJTdEJTdE`

Then i searched for `ngDevMode` string in all `.js` files with no result found. Also tried to open that provided page and i can not see any mentioned warning and also can access `ngDevMode`. Hmm this is weird. I also tried Chrome since i use Firefox usually and with same result. There is no ngDevMode and still framerates drop quite a lot.

I use Windows and Node 11.6. I hope we will get on same soon :). 
Thx a lot.

PS: what is also weird is that your `npm run build:min` would still produce `ngDevMode` because for me it was gone even with previous commit, last comming only turned off names mangling.

**Comment by kukjevov** [comment] 2020-01-30 15:05
And i forgot here are screenshots
![ndDevMode](https://user-images.githubusercontent.com/16702037/73461358-4cb19900-437a-11ea-8f77-6f0c40a5e2d6.png)

**Comment by pkozlowski-opensource** [comment] 2020-01-30 15:09
@kukjevov I've pulled your webpack update and now I can get proper build _without_ `ngDevMode` mode! So we are good here, I can investigate. Thnx for amending the build as requested! 

For now I've got everything I need to investigate, I will come back to you if I need / got more info.

**Comment by matsko** [comment] 2020-01-30 23:27
@kukjevov I'm able to run the app and reproduce the slowdown. Yes it is definitely janky.

How do I run the app in master? After running `npm install` and `npm start` I get the following error:

```
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration[0].output.path: The provided value "dist" is not an absolute path!
 - configuration[1].output.path: The provided value "dist" is not an absolute path!
```

**Comment by kukjevov** [comment] 2020-01-31 05:45
hi guys, thx a lot for your time and effort :).

Why would you like to run in in master? Master is currently way behind and there is reason for these *special* branch names. These numbered branch names are used to automatic generation of version number. Like from this branch you will get version `1.0.0-perfIvy-beta.20200130153352`.

But i can merge it in master and turn this feature off, but only after 9 30 CET.

**Comment by kukjevov** [comment] 2020-01-31 09:04
@matsko i have updated master branch and it should work now

**Comment by pkozlowski-opensource** [comment] 2020-01-31 09:20
@kukjevov I'm not sure why @matsko wanted to have `master` running but I _presume_ that maybe he wanted to compare v9RC.11 profile with v8 (without ivy). Actually, this is my question as well - do you happen to have a branch / repo where we can see v8 without ivy for the same application? 

I was trying to switch off ivy in `tsconfig.browser.json` on the https://github.com/kukjevov/ng-universal-demo/tree/perfIvy/1.0 branch but then the application doesn't compile...

Do you happen to have a version of this app running on v8 _without_ ivy so we can compare perf characteristics before and after? 

Sorry for all those requests - it is just that this app is not trivial and has custom build so it is hard for us to get repro scenarios that we need for investigations....

**Comment by kukjevov** [comment] 2020-01-31 09:24
I can *downgrade* app to make it working without ivy. Reason why it is not working without ivy is that there are some IVY dependent parts of code. I will prepare it for you and let you know. :)

**Comment by pkozlowski-opensource** [comment] 2020-01-31 09:26
> I can downgrade app to make it working without ivy. Reason why it is not working without ivy is that there are some IVY dependent parts of code. I will prepare it for you and let you know. :)

That would be awesome @kukjevov - if you do this in a separate branch so we can have both ivy and  non-ivy versions, it would be fantastic! 

Thnx so much for bearing with us - we are trying hard to get to the bottom of the issue here and appreciate your help!

**Comment by kukjevov** [comment] 2020-01-31 09:26
It is my intention to make it in separate branch :).

**Comment by kukjevov** [comment] 2020-01-31 11:54
Hmm downgrade was not as easy as i thought and also it does not show what we want to see :(. I will have to do it other way, because here on `masterDowngraded` branch you can see version 8.2.0. I tried to made as little changes as possible, but when i run it i can see very similar framerate drop as you can see on version 9. I am not sure if i set version 8 correctly.

But i have 2 environments, one with *old* v8 and one with *new* v9, i can open them in two tabs and there you can clearly see difference. I can record it for you, but it will not help you. 

I am thinking of taking real application and drop out code that you do not need to debug it. Because to me it looks same on this repo, which will not help.

If you want to try `masterDowngraded` then do clear `npm install`. I hope i will have time to create proper testing diff scenario. I will try do my best. :)

**Comment by pkozlowski-opensource** [comment] 2020-01-31 13:29
@kukjevov thnx for the update. In the meantime I'm getting some preliminary results and can spot small things to fix here and there in the framework - nothing major, though.

What I see very clearly, though, is that _layout_ for this page is pretty slow (20+ms). On top of this browser needs to relayout the whole page on each animation frame. As the result one animations take anything between 20-50ms and with those numbers we obviously can't have smooth animations.

So one area of investigation on your side would be to check if there were any markup / CSS changes on your side that would make layout slower. 

Again, I can see few improvements in the framework but those will, most probably, only impact JS time _before_ animations start. The slow layout part is independent of the framework version and might be a result of some other changes in the app. 

Anyway, I'm starting to get better picture of what is going on (where the time is spent) and I will share data with you as soon as I'm sure of those findings (and can compare with v8.x version). But you might also want to check markup / CSS to see if this could explain slower layout.

**Comment by kukjevov** [comment] 2020-01-31 14:04
@pkozlowski-opensource thx a lot for your time.

Well with moving to version 9 i did also some refactoring and shuffling in scss, which could be the problem. In provided demo it was "refactored" version also after downgrading. Well i will take real application of version 8 and drop code you dont need to and i think there we will see difference.

Anyway many thanks for your effort.

**Comment by pkozlowski-opensource** [comment] 2020-02-03 09:50
@kukjevov we (@matsko and myself) have spent quite a bit of time debugging the reproduce scenario you've shared and the current conclusion, based on the data we can verify, is that animation slowness is linked to slow layout on the page in question.

Indeed, if you inspect time spent in the layout, we can see that each animation frame requires the whole page re-layout and given the markup / CSS it takes non-trivial amount of time (often more than 30ms - at this point there is no way we can see smooth animations):

![Screenshot 2020-01-31 at 14 37 17](https://user-images.githubusercontent.com/973550/73642539-2178c380-4672-11ea-8612-e75bde062bad.png)

At this point we've got no evidence pointing to Angular changes being responsible for the slower layout - when animations start to execute the framework finished its job. As such, without more data-points we've got no choice but assume that the slowdown that you are observing is linked to markup / CSS changes and _not_ linked to the Angular version.

Obviously, we are more than happy to investigate further if you can share a reproduce scenario where we can see the slow-down with the _exactly the same_ markup, CSS and functionality (in other words: the only variable part being Angular version). 

On the positive side we've identified 2 improvements in the framework itself (#35116 and #35117), but the mentioned issues were present in Angular 8 as well (so those can't explain the slow-down you are observing).

I would also have few suggestions on improving the performance of your app (mostly linked to the bootstrap's JS usage) if this is sth you would find interesting.

**Comment by kukjevov** [comment] 2020-02-03 13:06
@pkozlowski-opensource 

Thx a lot for your investigation, both of you.

I created repo https://github.com/kukjevov/perf-problem.git which contains working version with old layout. If you want to try it.

> `npm install`
> `git reset --hard`
> `npm run build:min`
> `npm run server`
> `http://localhost:8888/`

Interesting thing is that the problem is on top level i think. Because there are only changes that affects all pages. There is several flexboxes and css grids with `1fr` and i think this could cause a problem. I know this is not arrea of interest, but i would be very glad if you at least take a look at that, maybe if you can point me out what of css changes could cause the problem. Because page itself is absolutely same. Anyway thx for everything :).

**Comment by kukjevov** [comment] 2020-02-03 13:19
I have found the problem, this selector `app router-outlet + *` *asterisk* is not very good :).

**Comment by kara** [comment] 2020-02-03 15:35
Thanks for the investigation @pkozlowski-opensource! Now that we know what's going on (and that there are no Ivy-related issues), I'm going to close this issue in favor of the more specific ones https://github.com/angular/angular/issues/35116 and https://github.com/angular/angular/issues/35117.

**Closed by kara** 2020-02-03 15:35 UTC
Labels: comp: ivy, comp: performance, state: Needs repro
