### ISSUE TITLE
Something in angular2-polyfills.js is interfering with SemanticUI Search

### ISSUE THREAD

**Issue by gaiottino** [angular/angular#7750] opened 2016-03-24 12:03 UTC
**Steps to reproduce and a minimal demo of the problem**

http://plnkr.co/edit/QcbOZCLEMxDqB9Hal0ef?p=preview

**Current behavior**

Just press `a` in the search field to get a list of options and then press down key. The selected result is constantly reset. Selecting one will keep the single result open.

**Expected/desired behavior**

Here's a version of the plunkr without `angular2-polyfills.js` to show the difference.

http://plnkr.co/edit/FIygVljA8bIWaoAFehDr?p=preview

Any insights in why just including `angular2-polyfills.js` causes this inwanted change would be great. At first I thought it was an issue which could be solved by `ngZone.runOutsideAngular` but that was before I narrowed it down to simply including `angular2-polyfills.js`

**Comment by eelwayadmin** [comment] 2016-03-25 22:50
I got similar issues when trying to integrate stripe.js : angular-polyfills is interfering with stripe.
Just after the first call (createToken), no more change are dispatched, and got many issues with views contruction.

Is someone investigating this ?

**Comment by pkozlowski-opensource** [comment] 2016-04-13 10:27
Duplicate of https://github.com/angular/zone.js/issues/319

**Closed by pkozlowski-opensource** 2016-04-13 10:27 UTC
