### ISSUE TITLE
Allow Dependency Injection for Class properties so inheritance is cleaner. 

### ISSUE THREAD

**Issue by bvkimball** [angular/angular#12152] opened 2016-10-07 16:07 UTC
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Currently you can only inject services into your constructor, ie.

```
export class Simple {
    constructor(element:ElementRef, http:Http, custom:CustomService1) { ... }
}
```

So to extend this class i would have to get all of the dependencies again and pass them to the super. eg.

```
export class Complex extends Simple  {
    constructor(element:ElementRef, http:Http, custom:CustomService1, custom2:CustomService2) {
          super(element, http, custom);
          this.custom2 = custom2;
    }
}
```

This get tedious when you need to add or change a dependency.

**Expected behavior**

Lets use an optional Class Property Annotation so that we can leave all DI out of the constuctor if we want. eg:

```
export class Simple {
    @Inject() element:ElementRef;
    @Inject() http:Http;
    @Inject() custom:CustomService1;
    constructor() {}
}

export class Complex extends Simple  {
    @Inject() custom2:CustomService;
}
```

**Comment by DzmitryShylovich** [comment] 2016-10-07 16:29
You should avoid inheritance until https://github.com/angular/angular/issues/11606 will be resolved.

**Comment by pkozlowski-opensource** [comment] 2016-10-07 16:36
Yup, this is duplicate of  #11606

**Closed by pkozlowski-opensource** 2016-10-07 16:36 UTC

**Comment by bvkimball** [comment] 2016-10-10 23:18
Ahh, i do not believe this is a duplicate of #11606, maybe a feature request related to the definition of how angular support inheritance.  Everything works today for me when i inherit Inputs and Outputs.  

I would like to have an `@Inject()` on a class param to inject a injectable service into a property instead of in the constructor.
