### ISSUE TITLE
Service worker is not working offline after deploying to github pages

### ISSUE THREAD

**Issue by tejindermakkar786** [angular/angular#32685] opened 2019-09-15 09:29 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/pwa

### Is this a regression?

 No Idea

### Description

 I have developed a PWA in angular 8 and deployed it to github. after deployment service worker is not working offline. I don't know what is the problem.

Infact I have followed the solution here https://github.com/angular/angular/issues/31316. but it didn't work.

## 🔬 Minimal Reproduction

https://github.com/tejindermakkar786/angular-pwa/tree/gh-pages
https://tejindermakkar786.github.io/angular-pwa/

## 🔥 Exception or Error
<pre><code>

status is failed for https://tejindermakkar786.github.io/angular-pwa/ngsw.json?ngsw-cache-bust=0.20943296921136034

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 8.2.2
Node: 10.16.2
OS: win32 x64
Angular: 8.2.5
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.802.2
@angular-devkit/build-angular     0.802.2
@angular-devkit/build-optimizer   0.802.2
@angular-devkit/build-webpack     0.802.2
@angular-devkit/core              8.2.2
@angular-devkit/schematics        8.2.2
@angular/cdk                      8.1.4
@angular/cli                      8.2.2
@angular/material                 8.1.4
@angular/pwa                      0.803.3
@ngtools/webpack                  8.2.2
@schematics/angular               8.2.2
@schematics/update                0.802.2
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.38.0

</code></pre>

**Anything else relevant?**

i used command to build the project as mentioned in above link.

`ng build --prod --base-href "/angular-pwa/"`
then this
`ngh --dir=dist/angular-pwa-demo`

I submitted an issue 2 days ago but that was closed due to duplicate,Please help me

**Comment by gkalpak** [comment] 2019-09-25 19:06
@tejindermakkar786, I just tried https://tejindermakkar786.github.io/angular-pwa/ and it seems to work fine in offline more (the table is shown and populated with users).

> status is failed for https://tejindermakkar786.github.io/angular-pwa/ngsw.json?ngsw-cache-bust=0.20943296921136034

Seeing some failed requests in the `Network` panel in DevTools is expected (since there is no network connectivity), but that doesn't mean that the ServiceWorker is not working in offline mode.

##
Closing since everything works as expected (afaict). If you are still having issues, please describe in detail what is the observed behavior and what you expected instead.

**Closed by gkalpak** 2019-09-25 19:06 UTC
Labels: comp: service-worker

**Comment by RayDragon** [comment] 2019-10-01 19:33
I am facing the same problem, mines is https://ray-hacker-company.github.io/dcem/setip, 
Steps to reproduce:
1. Open the above link in chrome(windows 10 64x) and refresh 1-2 times 
2. Press f12 for inspection/console, select network, go offline...
3. Refresh

Result:
This page isn’t workingray-hacker-company.github.io took too long to respond.
HTTP ERROR 504

I tried https://tejindermakkar786.github.io/angular-pwa/ as well, sure enough when online, everything works fine, but when I go offline, it doesn't open

Am I doing something wrong....?
BTW, i built it with
`ng build --prod --base-href "/dcem/" `
then changed the start_url in manifest.json to "/dcem/" as well, locally it runs offline quite well...

**Comment by gkalpak** [comment] 2019-10-01 20:47
@RayDragon, it seems that there is a hash mismatch for your assets. It means that the files served are different to the files after `ng build` (based on which the hashes for `ngsw.json` were computed. It could be a tiny difference (e.g. in whitespace or line breaks), but the files have to be identical for the SW to be able to cache them.
