### ISSUE TITLE
Improve router work with `history.state`

### ISSUE THREAD

**Issue by samogot** [angular/angular#28954] opened 2019-02-24 18:52 UTC
# 🚀 feature request

### Relevant Package
This feature request is for @angular/router

### Disclaimer
This feature request can be broken down to several separate issues (bugs and FRs) but I've decided to create one issue to describe my actual use case, problems I have encountered, ideal solution I'd like to have and workaround I came up with.

### Use case
I'm working on web site for reading books. I have some "reader" page with infinite scroll that loads next chapter when user scrolls near to of a page. When some chapter enters view-port, I change browser URL to this chapter without triggering navigation (using `Location.replaceState`). 

If users scroll to some next chapter and then reload page or go back/forward in history, they lost scroll position, because saved scroll position (on page with several chapters) is greater then reloaded page length (on page with only "last" chapter)

The idea was to use `history.state` to save scroll position relative to current chapter top.

### Problems
Saving position was pretty straightforward, because `Location.replaceState` method already has state property. But restoring this state is a pain.

Thanks to #27198 router already knows something about history state, current design/implementation isn't enough do described use case. I didn't figure out why we need both `NavigationStart.restoredState` and `NavigationExtras.state`, but despite similar description, they are not the same. 

Router itself lacks public method that behaves like `Location.replaceState` (#24617), and any "outside" changes to `history.state` are not available as `NavigationExtras.state` of `Router.getCurrentNavigation()`, but only available as `NavigationStart.restoredState`. There is private `setBrowserUrl` method, that can be used for public implementation.

`NavigationStart.restoredState` of initial page load can't be reached inside component that is responsible for text rendering (i.e. in the place, which knows chapter top offset, where we need to add saved scroll position), because initial `NavigationStart` is fired before any component (except of `AppComponent`) is created. And there is no way to get this value otherwise, except of catching it in `AppComponent` and saving in some service.

Buy the way workaround from https://github.com/angular/angular/pull/27198#issuecomment-453789450 to pass `NavigationStart.restoredState` as `NavigationExtras.state` doesn't work (any more?) because of resetting `currentNavigation` [here](https://github.com/angular/angular/blob/7.2.6/packages/router/src/router.ts#L711) in case of "redirect during NavigationStart".

And even if we can get `NavigationStart.restoredState` in such hackish way, there is no sense to do this, because of bug. We don't get load any stored state from history in initial navigation (see `null` in [line 951](https://github.com/angular/angular/blob/7.2.6/packages/router/src/router.ts#L951) called from [line 778](https://github.com/angular/angular/blob/7.2.6/packages/router/src/router.ts#L778))

Actually we don't even have a way to get this initial state, because all classes on the way from `Location`, through `LocationStrategy`, `PathLocationStrategy`, `PlatformLocation`, `BrowserPlatformLocation` up to `History` lacks an abstraction to get current state.

Hopefully we still can access `window.history.state` directly. But again, we cann't do it in the component code, because before we create component, router already resets saves `history.state` with `{navigationId:1}`. So I still need to write some hackish way to store this value somewhere before first `ActivationStart` event.

### Describe the solution you'd like
I'd like to have a way to straightforwardly call something on router to replace current state and than be able to get this state in `Scroll` router event. I want this state to be persistently saved even after page reload to moving back/forward outside of angular application. 

I don't really care how it will be implemented internally, but just fixing problems above should be enough.

Router should have it's own `replaceState` (or something) method, that encapsulate any logic around  `Location.replaceState` to handle `navigationId` or any other possible future angular-specific internal structure of `history.state` (#27607) and also to provide state as `NavigationExtras.state` instead of `NavigationStart.restoredState`.

### Describe alternatives you've considered
This section is mostly for someone looking for solution for exactly my use case. 
Workaround I came up with consists of two parts. 
First - I use resolver to get saved data directly from `window.history.state`.
Second - because of the same reason I can get data on initial page load - I receive wrong data on navigating away to another chapter. What do I mean? Consider following use case:
- Initial page load without history. 
- No data in history -> no scrolling to position.
- Scroll a bit, position is saved to history.
- Reload page. 
- Router will rewrite history only on ActivationStart, so we get correct data in resolver. 
- There is data from resolver -> scroll to saved position.
- Scroll a bit, position is saved to history.
- Navigate to another chapter directly (there is contents feature in my app). 
- _Router will rewrite history only on ActivationStart_, so we get **incorrect** data of previous chapter in resolver.
- There is data from resolver -> we scroll to incorrect saved position of previous chapter.

To workaround this problem, I save chapter id together with scroll position, so I can check is this data is relevant.
Final code looks something like this:

progress-resolver.service.ts:
```TypeScript
import { Inject, Injectable, PLATFORM_ID } from '@angular/core';
import { isPlatformBrowser } from "@angular/common";
import { ActivatedRouteSnapshot, Resolve, RouterStateSnapshot } from "@angular/router";

interface Progress {
  scroll: number,
  chapterId: number,
}

@Injectable({
  providedIn: 'root'
})
export class ProgressResolverService implements Resolve<Progress | null> {

  constructor(@Inject(PLATFORM_ID) private platformId: Object) {
  }

  resolve(route: ActivatedRouteSnapshot, state: RouterStateSnapshot): Progress | null {
    if (isPlatformBrowser(this.platformId) && window && window.history && window.history.state && window.history.state.progress) {
      return {
        scroll: window.history.state.scroll,
        chapterId: window.history.state.chapterId,
      };
    }
    return null;
  }
}
```

chapter-text.component.ts:
```TypeScript
import { AfterViewInit, Component, ElementRef, Input, OnDestroy, ViewChild } from '@angular/core';
import { OnScrollService } from "../on-scroll/on-scroll.service";
import { ActivatedRoute } from "@angular/router";
import { Location, ViewportScroller } from "@angular/common";
import { debounceTime, filter, map } from "rxjs/operators";
import { Subscription } from "rxjs";

@Component({
  selector: 'app-chapter-text',
  templateUrl: './chapter-text.component.html',
  styleUrls: ['./chapter-text.component.scss']
})
export class ChapterTextComponent implements OnDestroy, AfterViewInit {
  @Input() chapter: any;
  private progressSub: Subscription;
  private subscription: Subscription;
  private position: { top: number; height: number };

  constructor(
    private elem: ElementRef,
    private route: ActivatedRoute,
    private onScroll: OnScrollService,
    private location: Location,
    private viewportScroller: ViewportScroller,
  ) {
  }

  ngAfterViewInit() {
    this.position = {
      top: this.elem.nativeElement.offsetTop,
      height: this.elem.nativeElement.offsetHeight
    };
    this.subscribe();
  }

  subscribe() {
    this.subscription = this.onScroll.scroll.pipe(
      filter(scroll => this.position.top < scroll && scroll < this.position.top + this.position.height),
      debounceTime(100),
    ).subscribe(scroll => this.location.replaceState(this.chapter.url, undefined, {
      ...window.history.state,
      scroll: scroll - this.position.top,
      chapterId: this.chapter.chapterId
    }));
    
    this.progressSub = this.route.data.pipe(
      map(data => data.progress),
      filter(progress => progress && this.chapter.chapterId == progress.chapterId),
      map(progress => progress.scroll),
    ).subscribe(scroll => this.viewportScroller.scrollToPosition([0, this.position.top + scroll]));
  }

  ngOnDestroy() {
    this.subscription.unsubscribe();
    this.progressSub.unsubscribe();
  }
}
```

**Comment by samogot** [comment] 2019-02-24 18:57
@jasonaden, please take a look at this feature request. As far as I can see, you are the right person, who works with this area.

**Comment by colmben** [comment] 2019-03-28 23:08
I am currently trying to implement a reasonable back button solution that would also allow some state manipulation in-page. The current way state and popstates are handled is very...peculiar! 

As this request says, the navigation process now has the ability to set state. Instead of just popping the stored state, location.back() actually creates a new navigation with a restoredState property in the NavigationStart event. Why? 

If you change the state with location.replaceState(), location.back wouldn't even find that state to restore, unless you also merge in the (correct? Not sure it needs to be the actual right number) navigationId. Why does it do this?

What I was expecting to find when I saw these changes was an Angular implementation of the History API [,](https://developer.mozilla.org/en-US/docs/Web/API/History_API) which allows any arbitrary state to be placed in history and that state to be immediately available on a pop. Both Location and Router are using names that seem to be related to the History API (replaceState, back etc) but they aren't doing what you would expect from a History API compliant process. Why are we complicating the thing with navigation IDs and restored states? It feels like Location and Router are at cross purposes here and one or the other should properly implement the History API to allow intuitive state management over pops.

**Comment by jasonaden** [comment] 2019-04-04 23:07
Thanks for the issue. I agree, we need much better APIs for dealing with `history.state`. I've got some ongoing work that might help with your use cases. But I wouldn't mind having a further discussion.

If you can ping me on Twitter @jasonaden1 we could set up a time to discuss. I would like to see if what I'm currently implementing would end up working for your needs.

**Comment by samogot** [comment] 2019-04-08 09:12
Sorry, I don't use twitter :)

**Comment by eric-gagnon** [comment] 2019-05-16 19:46
+1

I stumbled on the very same problem. When reloading page, state seem to be lost.

**Comment by colmben** [comment] 2021-06-04 16:13
Just FYI for the 22 people who thumbs-up'ed the +1 comment, the angular voting process requires a thumbs-up on the first post, the one describing the feature request. This is currently sitting at 7 thumbs-up and requires 20 to be considered.

**Comment by anishmgoyal** [comment] 2021-08-10 16:56
+1

When reloading the page, state's lost. Going forward or back from the page after reload shows that OTHER pages retain their state, but the initially loaded page does not.

After checking in the constructor for the app component, the value is definitely present - it's just that, for the first page, the router is ignoring it.

**Comment by cyraid** [comment] 2022-08-17 18:45
My use case is different, and it was kinda difficult to even find this github issue. There are probably others out there that face this issue and have to do workarounds. I use location.go() and try to store state without using navigate. I store the state, but when I listen for window:popstate event, the state just holds the navigationId, not the data I put into it. Is there not a way to get the state I put in, using a navigationId? Or better yet, don't erase my state data I put in? :)

**Comment by jksware** [comment] 2022-08-30 00:04
For anyone with the same issue, I found a workaround that might suit you (although with a compromise, see at the end):

1. On your router, set `onSameUrlNavigation` to `reload`.
```
this.router.onSameUrlNavigation = 'reload';
```

2. To save your current state, navigate to the same URL the browser is in, and include the state you want to save in the second argument.
```
await this.router.navigateByUrl(this.router.url, { state: state });
```

The compromise is that this method is effectively reprocessing the URL, as noted by the comments in the code for `onSameUrlNavigation`:
> Note that this only configures whether the Route reprocesses the URL and triggers related
> action and events like redirects, guards, and resolvers. By default, the router re-uses a
> component instance when it re-navigates to the same component type without visiting a different
> component first.

**Comment by robmv** [comment] 2022-09-15 14:55
I wrote a workaround using a service. It listen for `NavigationStart` triggered by a `popstate` and store the native `history.state` before Angular touches it. Some top level component must inject it in order to not lose states before it is used down the component hierarchy.

I hope this helps until Angular has better support for it.

```typescript
import { Location, PopStateEvent } from '@angular/common';
import { Injectable } from '@angular/core';
import { Event as REvent, NavigationEnd, NavigationError, NavigationStart, Router } from '@angular/router';
import { filter, SubscriptionLike } from 'rxjs';

@Injectable({
  providedIn: 'root',
})
export class NativeHistory {
  private isPopstate = false;

  private _state: unknown = window.history.state;

  constructor(
    private readonly router: Router,
    private readonly location: Location) {
    function filterPred(event: REvent): event is NavigationStart | NavigationEnd | NavigationError {
      return event instanceof NavigationStart || event instanceof NavigationEnd || event instanceof NavigationError;
    };

    this.router.events
      .pipe(
        filter(filterPred)
      )
      .subscribe(event => this.processEvent(event));
  }

  private processEvent(event: NavigationStart | NavigationEnd | NavigationError) {
    if (event instanceof NavigationStart) {
      if (event.navigationTrigger == 'popstate') {
        this.isPopstate = true;
        this._state = window.history.state;
      }
    } else if (event instanceof NavigationEnd) {
      if (this.isPopstate) {
        // The current state is stored again in order to not lose it after another navigation
        this.location.replaceState(this.location.path(), '', this._state);
        this.isPopstate = false;
      }
    } else {
      this.isPopstate = false;
      this._state = undefined;
    }
  }

  get state(): unknown {
    return this._state;
  }
}
```

**Comment by nebkat** [comment] 2022-11-10 03:45
I think a lot of this thread has lost focus from the core problem:

## Goal

The goal is to allow the current state to be modified after a page has been loaded, i.e. to reflect user interactions. This is essential to maintain intuitive forward/back navigation. `History.replaceState()` provides a way to achieve this natively.

## Issue

The issue is that the Angular Router uses `history.state` for it's own internal functionality and unintentionally interferes with `history.state` after `popstate` events (forward/back events).

Since #27198 the router allows a `state` to be passed when navigating, but there is no clean way for the app to modify the state on the current page after navigation. As originally suggested by @samogot, there should be a `Router.replaceState()` method to mirror `History.replaceState()` without URL changes.

There is also a bug that causes the router to discard the state if the internal fields added by the router are not present when forward/back navigation occurs. This means that if the user manually calls History.replaceState(), the state will later be overwritten when returning to the page.

This bug is not a regression but rather the router was never built to handle app states and it is an unintended consequence of some very old code.

## General Solution

- Add a `Router.replaceState()` method that allows the app to alter the state on a page without affecting router internal operation.
- Fix unintended behaviours and remove unnecessary `restoredState` field.

## Workaround

There is currently a very simple workaround that appears to fix the problem entirely, but it is really just a hack to patch the bug in the router.

```ts
history.replaceState({ ...history.state, foo: 'bar' }, '')
// OR
history.replaceState({ navigationId: history.state.navigationId, foo: 'bar' }, '')
```

## Summary

I have done a lot of digging on this so I hope it may help in determining the best course of action.

A number of commits along the way have led to the current situation so there are likely a variety of possible fixes.

## Short History

#### 2016
- The router originally did not care about history states at all, and their use by the app was undocumented.
- Whenever `history.pushState()` was used by the router, `null` was always provided as the state.
- However, there _was_ logic to avoid resetting states after forward/back navigation.

#### 2016
- eb2ceff4b (unintentionally?) removes this logic and causes state to be reset on every `popstate`.

#### 2018
- af2c0b34 starts using state to store `navigationId` and then populates `NavigationStart.restoredState`
- Motives are unclear, `restoredState` seems completely unnecessary at this point.
- Bug behavior isn't changed, but logic to extract `navigationId` from state is introduced that later gets misinterpreted.

#### 2019
- #27198 allows state to be passed with `Router.navigate()`
- f7ef94a0f81 incorrectly rewrites earlier `navigationId` extract logic to also include the entire state object, but _only_ if `navigationId` is present.
- 

## Long History

We start with eb2ceff4ba19a09a5f400f81e371ec176878cd37 way back in 2016.

The router uses `history.pushState()` and `history.replaceState()` to change the URL displayed in the browser without refreshing the page. `null` is always passed as the `state` parameter, as the router does not still make any use of the state.

When the browser forward/back buttons are pressed (or `location.forward()`/`location.back()`) are used, a `popstate` event is emitted. The router listens for this in order to handle the necessary routing changes.

Previously, when the router detected a `popstate` event, `skipLocationChange` would be used to avoid further altering the state with `history.replaceState()` within the router, as there was no need for this.

In order to solve #13491, `skipLocationChange` is disabled for `popstate`/`hashchange` event routing. I am not sure if this was the intended result of the commit, but from this point on it seems any `popstate` even will cause `state` to be set to `null` due to the forced location reset.

----

Next there is af2c0b34 in 2018.

This commit adds `navigationTrigger` and `restoredState` to the `NavigationStart` event. `navigationTrigger` is a useful addition to allow differentiating between imperative and `popstate` changes. However, `restoredState` seems entirely redundant:

https://github.com/angular/angular/blob/af2c0b34a251a597e9142bb87e325b0c0ba7d407/packages/router/src/events.ts#L55-L62

https://github.com/angular/angular/blob/af2c0b34a251a597e9142bb87e325b0c0ba7d407/packages/router/src/events.ts#L64-L76

`navigationId` is an internal field used by the router and to my knowledge is not meaningful outside of the router. The comment suggests that checking for its presence would indicate if a `popstate` triggered the navigation, but why do this when it is already evident from `navigationTrigger`?

In this commit it appears the addition of `navigationId` to `state` was solely for the purposes of populating `restoredState`, which as per the above should be unnecessary, so I am totally confused as to why it was done.

The present day bug then stems from the `popstate` handling code introduced in this commit.

https://github.com/angular/angular/blob/af2c0b34a251a597e9142bb87e325b0c0ba7d407/packages/router/src/router.ts#L312-L320

Line 315 just extracts the `navigationId` from the state and creates a new object.

----

Later on #27198 introduced the ability to pass a state during navigation. The internal fields are appended and as long as they are not modified by the app there are no issues.

A commit from the PR, f7ef94a0f81 now deals with the `popstate` state handling code slightly differently:

https://github.com/jasonaden/angular/blob/f7ef94a0f817c701068866dc9ba6e5d1242c8b53/packages/router/src/router.ts#L684-L686

The purpose here is probably to maintain the behavior of `restoredState`, but now this state value is also being written to `history.replaceState` i.e. it will potentially overwrite it to null.

**Comment by atscott** [comment] 2022-11-11 23:43
@nebkat Appreciate the detailed research here. I don't have the full history either, but I've discovered information that I believe to be true after inheriting ownership of the Router code around 2019:

> Remove unnecessary and confusing restoredState field. https://github.com/angular/angular/issues/27607 closed as completed?

This was probably closed before GitHub's feature that allowed you to close as won't do vs completed. It was closed as “not worth it”. The unfortunate truth is that it _is_ public API and applications _do_ use it (though it’s rare). Removing it would be a pretty big headache.

> navigationId is an internal field used by the router and to my knowledge is not meaningful outside of the router.

The navigationId on the history state is used in two places:
1. The [router scroller](https://github.com/angular/angular/blob/ec8b52af69a2e04a7b077eb4d4309870ba40e273/packages/router/src/router_scroller.ts#L59) to restore the stored scroll position for that item in history (this is actually mentioned in the [docs](https://github.com/angular/angular/blob/af2c0b34a251a597e9142bb87e325b0c0ba7d407/packages/router/src/events.ts#L73-L74).
2. The [upgrade](https://github.com/angular/angular/blob/main/packages/router/upgrade/src/upgrade.ts#L87) code to coordinate AngularJS/Angular hybrid apps.

> 	•	Add a Router.replaceState() method that allows the app to alter the state on a page without affecting router internal operation. TODO

The solution for this is certainly up for debate. I don’t know if adding a `replaceState` is necessary. We will be adding an `onSameUrlNavigation` option to the `navigate` method to override the default (which is `ignore`). So you could instead do `router.navigate([], {state: newState, onSameUrlNavigation: ‘reload’});`

**Comment by cyraid** [comment] 2022-11-16 19:43
@nebkat I believe "Remove unnecessary and confusing restoredState field. https://github.com/angular/angular/issues/27607 closed as completed?" was closed because it didn't get the votes?

**Comment by atscott** [comment] 2023-12-03 20:15
Closing as generally not relevant anymore. @nebkat outlined quite a few changes that improved things since this was reported and contributed https://github.com/angular/angular/pull/48033 to shore up yet another issue. There are a lot of options now, including the availability of `onSameUrlNavigation` in the navigation extras to effectively reload a route with new `state`.

If there are still specific issue that need to be addressed, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template that include info on how to create a reproduction using our template.

**Closed by atscott** 2023-12-03 20:15 UTC
Labels: feature, freq3: high, area: router, feature: under consideration, feature: votes required

**Comment by TerrorLumpiRaf** [comment] 2023-12-03 20:53
Dddssdddddsddswgkjjjmkjjjkmfmfmvvmvm . ' '
