### ISSUE TITLE
routing + lazy loading - angular is ignoring modules in the middle of path

### ISSUE THREAD

**Issue by maciejtreder** [angular/angular#15851] opened 2017-04-09 10:13 UTC
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I got problem with routing inside lazy loaded modules. 

Here is my "root" routes:

    const routes: Routes = [
      {path: '', redirectTo: 'admin', pathMatch: 'full' },
        {path: 'admin', loadChildren: 'app/admin.module#AdminModule'}
    ];
    
    @NgModule({
      imports: [
          RouterModule.forRoot(routes)
      ],
      exports: [
          RouterModule
      ]
    })
    export class MainRoutingModule {}

So what I expect from my app, is to redirect empty path to `/admin` - this works fine, module is loaded.

in AdminModule I got another redirect:

    const routes: Routes = [
        {path: '', component: AdminComponent, children: [
            {path: '', redirectTo: 'app', pathMatch: 'full' },
            {path: 'app', loadChildren: './app/app.module#AppModule', canActivate: [ AuthGuard ] },
            {path: 'login', component: LoginComponent}
        ]},
    ];
    
    @NgModule({
        imports: [
            RouterModule.forChild(routes),
            AppModule
        ],
        exports: [
            RouterModule
        ]
    })
    export class AdminRoutingModule {}

Here I got two scenarios:

- if user is authenticated redirect to `app` - so the whole path would be `/admin/app`
- otherwise redirect to `login` - so the whole path should be `/admin/login`

and finally routing in admin application:

    const routes: Routes = [
      { path: '', component: AppComponent, children: [
        { path: '',  redirectTo: 'home', pathMatch: 'full' },
        { path: 'home', component: HomeComponent},
      ]}
    ];

And now problems starts. If I will enter my side with url `localhost:3000/admin/app/(*)` everything works as expected, AuthGuard is invoked, url is ok, in case that user is unauthenticated he gets redirect to login page.

But!: If I will enter `localhost:3000` app redirects me to `localhost:3000/admin/home` (`app` is missing) and AuthGuard is not invoked. It looks like Angular is ommiting the `admin-routing.module` and goes directly to the last one.

**Expected behavior**
angular should respect all modules described between root and last one.

* **Angular version:** 
    "@angular/animations": "4.0.0",
    "@angular/common": "4.0.0",
    "@angular/compiler": "4.0.0",
    "@angular/core": "4.0.0",
    "@angular/forms": "4.0.0",
    "@angular/http": "4.0.0",
    "@angular/material": "2.0.0-beta.2",
    "@angular/platform-browser": "4.0.0",
    "@angular/platform-browser-dynamic": "4.0.0",
    "@angular/platform-server": "4.0.0",
    "@angular/router": "4.0.0",

* **Browser:** 
all
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 2.X

**Comment by Toxicable** [comment] 2017-04-09 15:36
could you please make a minimal reproduction. here is a template plunkr with some basic routing http://plnkr.co/edit/GyvsGPZJyqjQ5wKMGNUF?p=preview

**Comment by aebmknrl** [comment] 2017-04-25 04:25
Same behavior here. I have a shared module and another Calendar module. I import this on a child module (which is lazy loaded) and ignore this imports.

The child module:

```
import { NgModule } from '@angular/core';
import { CalendarModule } from 'angular-calendar';
import { SharedModule } from "../../shared/shared.module";
import { CalendarComponent } from './calendar.component';
import { AddEventComponent } from './add-event/add-event.component';
import { RouterModule } from "@angular/router";
import { AuthGuard } from "../../authentication/auth-guard.service";

@NgModule({
    imports: [    
            RouterModule.forChild([
                {path: 'calendar', component: CalendarComponent, canActivateChild : [AuthGuard]}
            ])
        ],
    exports: [],
    declarations: [
        CalendarComponent,
        AddEventComponent
        ],
    providers: [],
})
export class CayenaCalendarModule { }
```

On my parent module i call this module by lazy loading:

`{ path: 'adminarea',loadChildren: 'app/dashboard/calendar/cayena-calendar.module#CayenaCalendarModule',canActivate: [AuthGuard]}`

I have a couple of directives on my shared module that i need to use. The result is that when try to load the component then twrows errors because this directives and components are not loading.

**Comment by aebmknrl** [comment] 2017-04-25 11:10
Here is my plunker about this:

http://plnkr.co/edit/8l9n6fybwzqyCiDnwLLk?p=preview

**Comment by reppners** [comment] 2017-07-03 12:41
@aebmknrl In your plunkr there is no import of the `FormsModule` which you'll have to import explicitly to your app.

I extended your plunkr and imported/exported the `FormsModule` in your `SharedModule` to make it work:
http://plnkr.co/edit/K94VzW7qgQl38LkTO1UA?p=preview

So maybe you're just missing the export to make it work? I think your issue is not quite the same issue as the author is experiencing.

**Comment by reppners** [comment] 2017-07-03 12:59
@maciejtreder

I struggled with a problem quite similar to yours until I found out that I statically imported the module that should be lazy loaded in a parent module. Double check that you're not importing the lazy loaded module statically. Sounds like a good candidate for a `codelyzer` rule.

**Comment by sreekumarp** [comment] 2017-07-12 09:23
I am also experiencing same problem.

**Comment by Mattnmoore** [comment] 2017-08-07 10:19
+1. Any news on this issue?

**Comment by mariuslazar93** [comment] 2018-02-11 18:17
I had some sort of the same issue, but understanding what should be and what shouldn't be imported solved my issue.

Make sure you don't import `AdminModule` inside the your main/root app component (where you import `MainRoutingModule`). You also don't need to import `AppModule` inside `AdminRoutingModule` and also make sure you don't import `AppModule` inside the `AdminModule` (where you import AdminRoutingModule). Since they are lazy loaded modules (both AdminModule and AppModule), they shouldn't be imported anywhere.

**Comment by jasonaden** [comment] 2018-05-15 23:17
Closing this issue based on no reproduction provided for the original issue. If this issue persists, please create a new issue with reproduction.

**Closed by jasonaden** 2018-05-15 23:17 UTC
Labels: comp: router

**Comment by rebendajirijr** [comment] 2018-06-04 13:32
@reppners Thank you very much, this fixed my problem, too.

**Comment by abhinesh128** [comment] 2018-10-25 05:41
Guys, I have 2 modules and 3 components in all models so how to implement lazy loading.
