### ISSUE TITLE
Routing issue

### ISSUE THREAD

**Issue by tyagideepu133** [angular/angular#17223] opened 2017-06-06 03:57 UTC
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

During LazyLoading routing address are not behaving properly.For example if we are lazy loading module with route 'admin' than its component should work having a base address(admin/(ChildComponent)) but it is working also as (/(ChildComponent))  
**Expected behavior**

without bug (/(ChildComponent)) must not work
**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Windows 10,Vscode,Git
* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 all
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript
* **Node (for AoT issues):** `node --version` =

**Comment by jotatoledo** [comment] 2017-06-06 10:16
Can you add a reproduction of this?

**Comment by vicb** [comment] 2017-06-16 22:54
Closing as missing a repro - re-open a new issue when the repro is available. Thanks

**Closed by vicb** 2017-06-16 22:54 UTC
Labels: comp: router, state: Need repro

**Comment by chouclee** [comment] 2017-09-08 19:08
I met the same issue. After reading the sample code of router. I found the issue is due to importing lazy loaded module directly into `app.module`, lol

**Comment by tyagideepu133** [comment] 2017-09-09 04:05
Hmm i also that and thanks for replying
