### ISSUE TITLE
Does AoT not work with forwardRef?

### ISSUE THREAD

**Issue by buu700** [angular/angular#12475] opened 2016-10-24 07:00 UTC
**I'm submitting a ...**  (check one with "x")

```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Before 2.1.1, building our code with ngc would compile it with no errors (but not actually AoT the Angular templates because we use the upgrade adapter). Now that upgrade adapter AoT support has been added with 2.1.1, I get the following error:

```
Error: Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule in /home/gibson/.build/shared/js/cyph.im/appmodule.ts, resolving symbol AppModule in /home/gibson/.build/shared/js/cyph.im/appmodule.ts
    at simplifyInContext (/usr/lib/node_modules/@angular/compiler-cli/src/static_reflector.js:472:23)
    at StaticReflector.simplify (/usr/lib/node_modules/@angular/compiler-cli/src/static_reflector.js:475:22)
    at StaticReflector.annotations (/usr/lib/node_modules/@angular/compiler-cli/src/static_reflector.js:61:36)
    at _loop_1 (/usr/lib/node_modules/@angular/compiler-cli/src/codegen.js:66:54)
    at CodeGeneratorModuleCollector.readFileMetadata (/usr/lib/node_modules/@angular/compiler-cli/src/codegen.js:79:13)
    at /usr/lib/node_modules/@angular/compiler-cli/src/codegen.js:41:74
    at Array.map (native)
    at CodeGeneratorModuleCollector.getModuleSymbols (/usr/lib/node_modules/@angular/compiler-cli/src/codegen.js:41:35)
    at CodeGenerator.codegen (/usr/lib/node_modules/@angular/compiler-cli/src/codegen.js:120:39)
    at codegen (/usr/lib/node_modules/@angular/compiler-cli/src/main.js:7:81)
```

**Expected behavior**
Code builds successfully.

**Minimal reproduction of the problem with instructions**
Running ngc on our project that includes the following main module:

```
import {AppComponent} from './appcomponent';
import {CommonModule} from '@angular/common';
import {NgModule, forwardRef} from '@angular/core';
import {BrowserModule} from '@angular/platform-browser';
import {UpgradeAdapter as NgUpgradeAdapter} from '@angular/upgrade';
...


export const UpgradeAdapter = new NgUpgradeAdapter(
    forwardRef(() => AppModule)
);


@NgModule({
    imports: [
        BrowserModule,
        CommonModule
    ],
    declarations: [
        AppComponent,
        UpgradeAdapter.upgradeNg1Component(
            ...
        ),
        ...
    ]
})
export class AppModule {}
```

**What is the motivation / use case for changing the behavior?**
Being able to use Angular 2 at all. (We can't use JIT'd ng2 in prod due to our CSP.)

**Please tell us about your environment:** Debian Jessie inside Docker on OS X El Capitan
- **Angular version:** 2.1.1
- **Browser:** N/A
- **Language:** TypeScript 2.0.3
- **Node (for AoT issues):** 6.7.0

**Comment by DzmitryShylovich** [comment] 2016-10-24 07:09
Duplicate of https://github.com/angular/angular/issues/12465

**Comment by buu700** [comment] 2016-10-24 08:13
Got it, thanks! Any idea what might be causing the above error in this case?

I changed the above UpgradeAdapter/forwardRef code to:
```
export function AppModuleFunction () {
	return AppModule;
}

export const UpgradeAdapter	= new NgUpgradeAdapter(
	forwardRef(AppModuleFunction)
);
```

So far, no luck: `Error: Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule in /home/gibson/.build/shared/js/cyph.im/appmodule.ts, resolving symbol AppModule in /home/gibson/.build/shared/js/cyph.im/appmodule.ts`.

**Comment by DzmitryShylovich** [comment] 2016-10-24 13:54
U don't need `forwardRef` if u use it inside decorator. Decorated class is already available.

**Comment by buu700** [comment] 2016-10-24 15:20
Well, I just tried this as well, and managed to change the error message slightly:

```
export function AppModuleFunction () {
    return AppModule;
}

export const UpgradeAdapter = new NgUpgradeAdapter(
    forwardRef(AppModuleFunction)
);


export const Ng1Component	= UpgradeAdapter.upgradeNg1Component(
	'Ng1Component'
);
...


@NgModule({
	imports: [
		BrowserModule,
		CommonModule
	],
	declarations: [
		AppComponent,
		Ng1Component,
		...
	]
})
export class AppModule {}
```

New error message: `Error: Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol Beta in /home/gibson/cyph/shared/js/cyph.im/appmodule.ts, resolving symbol AppModule in /home/gibson/cyph/shared/js/cyph.im/appmodule.ts, resolving symbol AppModule in /home/gibson/cyph/shared/js/cyph.im/appmodule.ts`.

Still not sure what to do with that or how many other ways I can try modifying this file. Could the actual problem be in a file other than appmodule.ts, and if so how should I go about trying to debug this?

Is this maybe just a bug in the new upgrade adapter AOT support?

**Comment by DzmitryShylovich** [comment] 2016-10-24 15:23
I don't use UpgradeUdapter so I can't help you . If you think it's a bug pls provide a minimal repository with reproduction.

**Comment by buu700** [comment] 2016-10-24 15:24
Got it. Will update with a minimal test case later today.

**Comment by buu700** [comment] 2016-10-26 01:56
Okay, here's a minimal repository that reproduces the same result (output copied below): https://github.com/buu700/upgradeadapter-ngc-test

Does this look like an ngc bug, or am I doing something wrong? (cc @petebacondarwin)

```
Error: Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule in /test.tmp/appmodule.ts, resolving symbol AppModule in /test.tmp/appmodule.ts
    at simplifyInContext (/usr/lib/node_modules/@angular/compiler-cli/src/static_reflector.js:472:23)
    at StaticReflector.simplify (/usr/lib/node_modules/@angular/compiler-cli/src/static_reflector.js:475:22)
    at StaticReflector.annotations (/usr/lib/node_modules/@angular/compiler-cli/src/static_reflector.js:61:36)
    at _loop_1 (/usr/lib/node_modules/@angular/compiler-cli/src/codegen.js:66:54)
    at CodeGeneratorModuleCollector.readFileMetadata (/usr/lib/node_modules/@angular/compiler-cli/src/codegen.js:79:13)
    at /usr/lib/node_modules/@angular/compiler-cli/src/codegen.js:41:74
    at Array.map (native)
    at CodeGeneratorModuleCollector.getModuleSymbols (/usr/lib/node_modules/@angular/compiler-cli/src/codegen.js:41:35)
    at CodeGenerator.codegen (/usr/lib/node_modules/@angular/compiler-cli/src/codegen.js:120:39)
    at codegen (/usr/lib/node_modules/@angular/compiler-cli/src/main.js:7:81)
Compilation failed
``

**Comment by buu700** [comment] 2016-11-15 17:00
Just ran the minimal test against the final release of 2.2.0; still reproducing this.

**Comment by petebacondarwin** [comment] 2016-11-16 10:45
@buu700 you cannot use the `UpgradeAdapter` with AoT in any case.
We have an additional form of the upgrade library available that does support AoT.
It is called `upgrade/static` and you can get the UMD build from here npm:@angular/upgrade/bundles/upgrade-static.umd.js

**Closed** 2016-11-16 10:49 UTC
Labels: comp: upgrade, flag: can be closed?, state: Need repro

**Comment by buu700** [comment] 2016-11-16 14:22
Got it, thanks! That makes _a lot_ more sense. (I was really confused as to how a feature that didn't seem to work at all was merged and then promoted in the latest release notes.)

I'll see how that works out for us when the new docs are live.
