### ISSUE TITLE
Insert / Detach ViewRefs between multiple ViewContainerRefs

### ISSUE THREAD

**Issue by azarus** [angular/angular#20824] opened 2017-12-06 12:56 UTC
## I'm submitting a...

[X] Bug Report
[X] Feature request
I am not sure if the behavior is intended but it clearly causes problems.

## Current behavior

We are unable to detach a ViewRef from **ViewContainerRef A** and attach it to a different **ViewContainerRef B**

Insert / Detaching doesn't trigger change detection on both ViewContainers.
Using `@ContentChildren` fails to update changes properly.

## Expected behavior

I would like to be able to detach a ViewRef and attach it to a new ViewContainer without recreating the components inside the view. This should work without any issues.

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-gitter-couoxk?file=app%2Ftest.ts

## What is the motivation / use case for changing the behavior?

Would allow to implement Drag & Drop that doesn't recreate the  components when an item is dragged over.
Would allow to manipulate dom without using nativeElement, No more worrying about *ngFor trying to find the changes and throwing errors when nodes are missing in dom.

## Environment

<pre><code>
Angular version: 4.x
and 
Angular version: 5.x

Browser:

- [x] Chrome (desktop) version XX
- [x] Chrome (Android) version XX
- [x] Chrome (iOS) version XX
- [x] Firefox version XX
- [x] Safari (desktop) version XX
- [x] Safari (iOS) version XX
- [x] IE version XX
- [x] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by mlc-mlapis** [comment] 2017-12-06 18:36
@azarus ... the reasons sound interesting ... especially elimination of `nativeElement`.

**Comment by azarus** [comment] 2017-12-07 07:59
Using Native element to detach and attach dom to a different ngFor causes problems because when ngFor tries to detach the view the dom is not present. Ans ngFor also destroys the component when its removed. Is there a problem with the reasoning it is recommended to not to use nativeElement whenever possible.

**Comment by woppa684** [comment] 2018-02-01 13:00
So, this is not what you're trying to achieve? 
https://embed.plnkr.co/W9dYwrfJPfY3MSUFTOzz/

**Comment by azarus** [comment] 2018-02-01 13:35
@woppa684 This is exactly what i want to achieve. The problem is that i DO NOT want to recreate the components for this. Only attach and & dettach. I am kind of sad that its not assigned yet and im scared its gona spend lots of time in the backlog. Right now i created a workaround by creating my own *ngFor directive that solves this issue. Basically one line of code is missing. I am not sure if Angular accepts PRs for this as i have solved the issue internally for myself but it would be better to be available in the next public release.

**Comment by woppa684** [comment] 2018-02-01 15:28
... but that is exactly what this plnkr does right? Detach from one ViewContainerRef and insert into another one without destroying the component/view in the mean time. Is there some subtle difference with your usecase that I am unaware of?

I use this approach in our software for an customizable user interface where a user can reshuffle and resize components. These "workspaces" as we call them are in fact a tree (because nesting of components is possible). So, before removing a component (for example when moving it) I detach the view and save the ComponentRef in the Node that component represents. When this node gets

**Comment by azarus** [comment] 2018-02-01 15:50
Oh yes this works for basic stuff, but i list components with *ngFor, when moving the components around in an *ngFor your approach breaks, and the host / parent references are no longer maintained.

**Comment by woppa684** [comment] 2018-02-02 07:23
Ah, I see, I couln't get that from the title or the "expected behavior" :)

**Comment by trotyl** [comment] 2018-02-18 16:56
Duplicate of #13183 (Better to close that one since it's too old)

**Comment by pkozlowski-opensource** [comment] 2019-12-02 09:54
#34156 should fix it in ivy

**Comment by pkozlowski-opensource** [comment] 2020-02-16 16:59
Moving views between `ViewContaineRef` should work perfectly fine in ivy. If anyone bumps into related problems please open a new issue with a reproduction scenario.

**Closed by pkozlowski-opensource** 2020-02-16 16:59 UTC
Labels: comp: core, fixed by Ivy, type: feature
