### ISSUE TITLE
Get an error "Process unexpectedly crashed" on CI

### ISSUE THREAD

**Issue by dxvladislavvolkov** [angular/angular#36541] opened 2020-04-09 15:13 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 9.1.0

### Description

 Module has not been processed correctly by ngcc

## 🔬 Minimal Reproduction

 You can see the issue in this repo https://github.com/dxvladislavvolkov/testapp5
if you open circleci details 
https://circleci.com/gh/dxvladislavvolkov/testapp5/5?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

## 🔥 Exception or Error
<pre><code>
Error: Process unexpectedly crashed, while processing format property es2015 for entry-point '/home/circleci/project/node_modules/devextreme-angular/ui/file-manager'.
    at ClusterMaster.onWorkerExit (/home/circleci/project/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:153:23)
    at /home/circleci/project/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:51:101
    at ClusterMaster.<anonymous> (/home/circleci/project/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:246:57)
    at step (/home/circleci/project/node_modules/tslib/tslib.js:139:27)
    at Object.next (/home/circleci/project/node_modules/tslib/tslib.js:120:57)
    at /home/circleci/project/node_modules/tslib/tslib.js:113:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/home/circleci/project/node_modules/tslib/tslib.js:109:16)
    at EventEmitter.<anonymous> (/home/circleci/project/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:240:32)
    at EventEmitter.emit (events.js:311:20)

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
9.1.1

</code></pre>

**Anything else relevant?**

**Comment by gkalpak** [comment] 2020-04-09 15:29
Closing as a duplicate of #36278. Please follow #36278 for updates.

**Closed by gkalpak** 2020-04-09 15:29 UTC
