### ISSUE TITLE
Support (ngSubmit) for [form] directives

### ISSUE THREAD

**Issue by lekhnath** [angular/angular#9211] opened 2016-06-15 11:17 UTC
* **I'm submitting a ...**
- [ ] feature request

**Current behavior**

(ngSubmit)="onSubmit()" do not trigger when used with `[form]` directives.
```html
<table>
<tbody>
<tr>
<!-- PARTICULARS LIST WILL BE POPULATED HERE -->
</tr>
</tbody>
<tbody>
                  <tr form [ngFormModel]="particularForm" (ngSubmit)="addParticular()">

                    <td class="form-group">
                      <input ngControl="item" type="text" class="form-control" placeholder="Item">
                    </td>
                    <td class="form-group">
                      <input ngControl="unit" type="text" class="form-control" placeholder="Unit">
                    </td>
                    <td class="form-group">
                      <input ngControl="quantity" type="text" class="form-control" placeholder="Quantity">
                    </td>
                    <td class="form-group">
                      <input ngControl="price" type="text" class="form-control" placeholder="Price">
                    </td>
                    <td class="form-group">
                      <input ngControl="remarks" type="text" class="form-control" placeholder="Remarks">
                    </td>
                    <td>
                      <button type="submit" class="btn btn-primary"> Add </button>
        
                    </td>

                  </tr>
              </tbody>
</table>
```

**Expected/desired behavior**
It would be nice to have native support for (ngSubmit) for `[form]` directives also like `<form>` elements have currently.

* **What is the motivation / use case for changing the behavior?**
I've `paritculars` ControlArray which contains `ControlGroup` with fields item, unit, quantity... .
I was building an interface where user will enter some values and upon submitting the from it will be instantly displyed in tabular view above the form. Something like grid but not actually grid. Thats the use case.

* **Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.1 

* **Browser:** All Browsers 
 
* **Language:** TypeScript 1.8

**Comment by Namek** [comment] 2016-06-15 16:04
try replacing
```html
<tr form [ngFormModel]="particularForm" (ngSubmit)="addParticular()">
//...
</tr>
```

to
```html
<tr>
<form [ngFormModel]="particularForm" (ngSubmit)="addParticular()">
// ...
</form>
</tr>
```

**Comment by kara** [comment] 2016-07-12 22:36
Closing as duplicate of #7807

**Closed by kara** 2016-07-12 22:36 UTC
Labels: comp: core/forms, type: feature
