### ISSUE TITLE
Issues with Angular Router Module and enableViewTransitions Impacting SEO

### ISSUE THREAD

**Issue by wahid-wex** [angular/angular#57468] opened 2024-08-21 06:20 UTC
### Which @angular/* package(s) are the source of the bug?

animations, compiler

### Is this a regression?

Yes

### Description

Dear Angular Team,

I would like to report an issue related to the Angular v18 Router Module and its impact on SEO when enableViewTransitions is set to true.

Issue 1: SEO Impact from enableViewTransitions = true
I enabled the enableViewTransitions property in the Angular v18 Router Module to create smooth animations during route changes. While this feature works perfectly for end users and does not impact the functionality of the site, it has caused a significant issue with SEO. After deploying the site, I checked the rendered pages in Google Search Console. The screenshots captured by Google's crawler show a blank (white) page instead of the actual content. This suggests that the Google crawler is unable to properly render the content when enableViewTransitions is enabled, leading to potential SEO issues as the pages appear empty to the crawler.

Issue 2: Component Instantiation in Hierarchical Components
Additionally, I noticed a strange behavior when adding console logs in the constructors of hierarchical components (parent-child structure). Only the AppComponent was instantiated and logged in the console, while none of the child components were instantiated. This is unexpected and may indicate an issue with how components are being initialized in a hierarchical structure in this version of Angular.

These issues do not affect the user experience or the site's functionality, but they do present a significant problem for SEO. I hope the Angular team can investigate and address these problems.

Thank you for your attention to these matters.

Best regards,
Vahid

### Please provide the environment you discovered this bug in (run `ng version`)

```true
"dependencies": {
    "@angular/animations": "^18.1.2",
    "@angular/cdk": "~16.2.5",
    "@angular/common": "^18.1.2",
    "@angular/compiler": "^18.1.2",
    "@angular/core": "^18.1.2",
    "@angular/forms": "^18.1.2",
    "@angular/material": "~16.2.5",
    "@angular/platform-browser": "^18.1.2",
    "@angular/platform-browser-dynamic": "^18.1.2",
    "@angular/platform-server": "^18.1.2",
    "@angular/router": "^18.1.2",
    "@angular/service-worker": "^18.1.2",
    "rxjs": "^7.8.1",
    "tslib": "^2.3.0",
    "zone.js": "~0.14.5"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^18.1.2",
    "@angular/cli": "~18.1.2",
    "@angular/compiler-cli": "^18.1.2",
    "@types/express": "^4.17.0",
    "@types/jasmine": "~4.3.0",
    "jasmine-core": "~4.6.0",
    "karma": "~6.4.0",
    "karma-chrome-launcher": "~3.2.0",
    "karma-coverage": "~2.2.0",
    "karma-jasmine": "~5.1.0",
    "karma-jasmine-html-reporter": "~2.1.0",
    "typescript": "~5.4.5"
  }
```

### Anything else?

This is the Module that make problem:

import {NgModule} from '@angular/core';
import {PreloadAllModules, RouterModule, Routes} from '@angular/router';

export const routes: Routes = [
  // routes ...
];

@NgModule({
  imports: [RouterModule.forRoot(routes, {
    initialNavigation: 'enabledBlocking',
    scrollPositionRestoration: 'top',
    preloadingStrategy: PreloadAllModules,
    enableViewTransitions: true,
  })],
  exports: [RouterModule]
})
export class AppRoutingModule {
}

**Comment by atscott** [comment] 2024-08-21 17:35
Issue 1 does not sound related to Angular. I suspect you would be able to reproduce this without vanilla js and should report the issue at https://github.com/WICG/view-transitions. 

I don’t follow what you mean for the second issue. Do you mean that only the constructor of the app component happens and no child components were ever created? Or, I’m assuming you mean this was the case at a certain point in time. Again, this would be expected and not related to Angular, but an issue that needs to be reported against the browser view transitions. 

Angular routing must wait to create routed components until the view transition callback is ready to execute. That’s how the feature works in the browser and if this causes issues with SEO, those should be reported elsewhere rather than in the Angular repo.

**Comment by atscott** [comment] 2024-08-21 17:43
You may also be interested in trying to disable the initial view transition https://angular.dev/api/router/ViewTransitionsFeatureOptions#skipInitialTransition

**Comment by wahid-wex** [comment] 2024-08-22 05:31
Actually, Issue 1 and Issue 2 are related to each other. When "enableViewTransitions" is activated, both issues occur.

When I noticed the problem (a white page in Google Search Console), I added some console.log statements to each component and published the changes to see the results in Google Search Console. I then discovered that only the AppComponent was being instantiated, while the other components were not (Only when enableViewTransitions is activated).

**Comment by atscott** [comment] 2024-08-26 15:07
@wahid-wex Have you tried skipping the initial transition, as mentioned above?

**Comment by atscott** [comment] 2024-09-06 15:41
Closing as an issue outside Angular. I did some experimenting of my own and the issue is with view transitions and search indexing in general. Until that's fixed, you can disable the initial transition (I know you mentioned this isn't available in RouterModule.forRoot but there's nothing there that prevents a migration to provideRouter)

**Closed by atscott** 2024-09-06 15:41 UTC
Labels: area: animations, area: router
