### ISSUE TITLE
Async pipe breaks on specific project structure

### ISSUE THREAD

**Issue by devandreassimmeth** [angular/angular#51768] opened 2023-09-14 06:28 UTC
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

We managed to create a specific project structure that breaks the async pipe in components that get data from the backend using NgRX while NgRX is working fine. Our structure is the following:
- We have an AppComponent that implements the main navbar/navigation. Therefor we have this navbar and an router-outlet in the AppComponent.
- These so loaded top sub-components implement another level of navigation, a more fine-grained navigation over a sidenav. Therefor you find this sidenav, a main with another router-outlet to load the data-pages itself and a footer there.
- To get data from the backend we use NgRX. So the component that needs data requests it over dispatching an action, the data is loaded over an effect and comes back into the component over a selector. There the data is loaded in the HTML using the async pipe.
- In addition to that we have pages, where the data requesting is done in the parent component (so in one of the top sub-components), because a set of pages under a specific route (e.g. .../results/...) need the same dataset and it makes sense to load it once for all of these pages instead of in every component again.

This creates a specific situation that breaks the async pipe / change detection in the HTML besides the fact, that NgRx works properly. This can be proved by subscriptions in the corresponding typescript file of the broken HTML that log the current state values in the browser console. IMPORTANT NOTE / ATTENTION: This error only occurs when NO plugins like "Redux DevTools", etc are installed in the browser. When you install e.g. the Redux DevTools, the error does NOT occur!

I added a link with an Angular project that implements the described structure and where you can see the bug.
When you load one of the two data-components by clicking on the corresponding sidenav-button, the async pipe breaks (see UI) besides the fact, that the data load through NgRx works fine (see browser console). This is logged in the browser console using subscriptions.

In addition to that when you reload the component, where the data is loaded in the parent window, over the browser reload the async pipe also breaks on browser reload. In the component that loads it itself, the async pipe does not break on browser reload. That's the only version where the async pipe does not break.

Now the question is: Is this a bug or do I have an error somewhere in my application?

### Please provide a link to a minimal reproduction of the bug

https://github.com/devandreassimmeth/browser-reload-bug

**Comment by JoostK** [comment] 2023-09-14 09:01
> IMPORTANT NOTE / ATTENTION: This error only occurs when NO plugins like "Redux DevTools", etc are installed in the browser. When you install e.g. the Redux DevTools, the error does NOT occur!

This is an indication that the async pipe is observing an Observable that pushes its values outside of the Angular zone, meaning that updates won't actually trigger change detection. Plugins can fire events that do have listeners inside the Angular zone installed, such that these plugins cause a change detection run to be initiated.

**Comment by devandreassimmeth** [comment] 2023-09-14 09:22
I don't know how NgRX pushes its values in the selector-Observables, but these Observables are exactly what I use in the async pipe (see example application).

But that was also something I had in my mind, because of the strange behavior, that in some situations, it works on Browser reload, and on normal routing on runtime using `routerLink`, it does not work. Maybe something connected to the router? Since I updated my Angular application to Angular 16 and Standalone, I also get the console error `Navigation triggered outside Angular zone, did you forget to call 'ngZone.run()'?` on routing. Routing is configured like it is described [here](https://angular.io/guide/standalone-components) in the standalone documentation (see also example application).

**Comment by garrettld** [comment] 2023-09-14 21:48
I spent a while trying to create a simple recreation, and things got weirder and weirder, which made me think this was a low-level change detection issue. It appears that you're bootstrapping the application outside of the Angular zone, and that causes all kinds of weird change detection issues, including the apparent failure of the AsyncPipe in your reproduction.

When calling `bootstrapApplication` the `appRef.bootstrap(rootComponent)` call that it makes happens inside a `zone.run(() => ...)` callback. Updating your `main.ts` file to do the same fixes the issue:

```typescript
(async () => {
  const app = await createApplication(appConfig);
  // NgZone.isInAngularZone() // this is false here
  // app.bootstrap(AppComponent);
  const zone = app.injector.get(NgZone);
  zone.run(() => app.bootstrap(AppComponent));
})();
```

I'm not sure if this is the intended use for `createApplication`, but it seems to work.

**Comment by devandreassimmeth** [comment] 2023-09-15 05:43
Thanks for your help. Tried it in our application and it seams to work. All issues are gone now.

But somehow it feels a bit strange, that I have to define that and that's not done by Angular itself. Has this always been the case or is it due to the new standalone version?

I think it would be really helpful to add a site to the documentation, where you see how you can create an application asyncronously like in my case, where you configure some things before bootstraping the app. These things were part of the AppModule before, which no longer exists. But the requirement stays in some situations and you find nothing about this in the documentation. Would be nice to add a page or a paragraph for that!

**Comment by pkozlowski-opensource** [comment] 2023-09-15 08:50
@devandreassimmeth glad to hear that you've figured it out. Bootstrapping an Angular application outside of zone.js won't work for sure, so depending on a setup you might need to do what @garrettld suggested.

I'm going to close this issue as a support request.

**Closed by pkozlowski-opensource** 2023-09-15 08:50 UTC
