### ISSUE TITLE
Webpack Sample doesn't work

### ISSUE THREAD

**Issue by coultonluke** [angular/angular#24396] opened 2018-06-09 21:06 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Webpack example that is downloadable from https://angular.io/guide/webpack doesn't work (https://angular.io/generated/zips/webpack/webpack.zip).  Just shows 'Loading...' and doesn't pull in the required JS files to run the app.

## Expected behavior

App should initialise and display "Hello from Angular App with Webpack" from the `app.component.html`.

## Minimal reproduction of the problem with instructions

1. Download sample using link at the top of the documentation
2. Navigate to the folder and run `npm install`
3. Run `npm run start`, this opens https://localhost:3000 in chrome
4. App doesn't initialise, just shows 'Loading...'.

## Environment
Windows 10.
<pre><code>
Angular version: 6.0.0

Browser:
- [x] Chrome (desktop) version  66.0.3359.181
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v8.11.1  
- Platform: Windows 

Others:

</code></pre>
I've seen [this issue](https://github.com/angular/angular/issues/23937) and [this issue](https://github.com/angular/angular.io/issues/3568) but one is just talking about whether it should be deprecated and the other isn't for the current Angular version.

**Comment by jenniferfell** [comment] 2018-06-11 22:08
Duplicate of https://github.com/angular/angular/issues/22941

That issue was closed with this message: 
The webpack guide is outdated and no longer publicly linked. Tracking here #23937

Closing as duplicate. #23937 handles this issue as well. Thanks for submitting this issue. We'll keep them linked.

**Closed by jenniferfell** 2018-06-11 22:08 UTC
Labels: comp: docs, comp: examples, freq3: high, severity3: broken, type: bug/fix
