### ISSUE TITLE
[Question] Support for media queries in the style compiler

### ISSUE THREAD

**Issue by vicb** [angular/angular#4884] opened 2015-10-24 00:14 UTC
The `TemplateNormalizer` push the content of any `<style>` tag to the `styles` List discarding any `media` attribute (the same applies to `<link rel="stylesheet">`).

I guess we want to add support for that ?

This would need some thinking wrt to `@import` rules (i.e. it would not be possible to only add them to `styleUrls` when a media query applies).

**Comment by vicb** [comment] 2016-10-07 22:14
see https://plnkr.co/edit/M6JnmnNfoy4XwE3AYwo0

**Comment by splincode** [comment] 2018-07-26 15:31
@vicb Is the issue relevant?

**Comment by jelbourn** [comment] 2020-11-06 21:36
Duplicate of #6513 (choosing that one since it has more activity)

**Closed by jelbourn** 2020-11-06 21:36 UTC
Labels: P3, comp: core, core: stylesheets, freq1: low, type: bug/fix
