### ISSUE TITLE
ng Serve going down with OutOfMemory Error.

### ISSUE THREAD

**Issue by PPInfy** [angular/angular#37780] opened 2020-06-26 20:17 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....
core

### Is this a regression?

yes
 Yes, the previous version in which this bug was not present was: ....9

### Description
Whenever I start ng serve at build phase it is giving outofmemory error.
 A clear and concise description of the problem...

## 🔬 Minimal Reproduction

 https://stackblitz.com/...

## 🔥 Exception or Error
<pre><code>

(node:864) ExperimentalWarning: The fs.promises API is experimental
Warning: Entry point 'ng5-slider' contains deep imports into 'D:/Workspace/frontend/node_modules/ng5-slider/node_modules/rxjs/Subject', 'D:/Project/Releases/Spike/Workspace/frontend/node_modules/ng5-slider/node_modules/rxjs/Subscription', 'D:/Project/Releases/Spike/Workspace/frontend/node_modules/ng5-slider/node_modules/rxjs/operators'. This is probably not a problem, but may cause the compilation of entry points to be out of order.
93% after chunk asset optimization SourceMapDevToolPlugin vendor.js generate SourceMap
<--- Last few GCs --->

[864:000001A9346180C0]    88247 ms: Mark-sweep 1320.0 (1440.6) -> 1306.2 (1442.1) MB, 848.5 / 0.0 ms  (average mu = 0.221, current mu = 0.220) allocation failure scavenge might not succeed
[864:000001A9346180C0]    89282 ms: Mark-sweep 1323.8 (1444.1) -> 1310.2 (1445.5) MB, 947.0 / 0.0 ms  (average mu = 0.157, current mu = 0.085) allocation failure scavenge might not succeed

<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 000002DD911DC5C1]
Security context: 0x035a5471e6e9 <JSObject>
    1: /* anonymous */ [0000012EC37F5C49] [D:\Workspace\frontend\node_modules\webpack-sources\node_modules\source-map\lib\source-node.js:~342] [pc=000002DD92A4C010](this=0x01cc1b80d481 <GlobalObject Object map = 0000017EC7B9C509>,chunk=0x027197caf3b9 <String[9]: nodeAttrs>,original=0x033a480ee791 <Object map = 000000CD23EBB511>)
    ...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF7960FDD8A v8::internal::GCIdleTimeHandler::GCIdleTimeHandler+4506
 2: 00007FF7960D8886 node::MakeCallback+4534
 3: 00007FF7960D9200 node_module_register+2032
 4: 00007FF7963F30DE v8::internal::FatalProcessOutOfMemory+846
 5: 00007FF7963F300F v8::internal::FatalProcessOutOfMemory+639
 6: 00007FF7965D9804 v8::internal::Heap::MaxHeapGrowingFactor+9620
 7: 00007FF7965D07E6 v8::internal::ScavengeJob::operator=+24550
 8: 00007FF7965CEE3C v8::internal::ScavengeJob::operator=+17980
 9: 00007FF7965D7B87 v8::internal::Heap::MaxHeapGrowingFactor+2327
10: 00007FF7965D7C06 v8::internal::Heap::MaxHeapGrowingFactor+2454
11: 00007FF796701EA7 v8::internal::Factory::NewFillerObject+55
12: 00007FF79677F096 v8::internal::operator<<+73494
13: 000002DD911DC5C1
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

10.0.0
</code></pre>

**Anything else relevant?**

No

No

**Comment by ericmartinezr** [comment] 2020-06-26 20:23
Probably dup of https://github.com/angular/angular-cli/issues/18034

**Comment by alan-agius4** [comment] 2020-06-26 20:33
Duplicate of https://github.com/angular/angular-cli/issues/18034

**Closed by alan-agius4** 2020-06-26 20:33 UTC
