### ISSUE TITLE
Router rewrite urls when has = at the end of path and has query params.

### ISSUE THREAD

**Issue by namerci** [angular/angular#31649] opened 2019-07-19 10:02 UTC
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/router

### Is this a regression?
I don't know.

### Description
When we use router with param and this params end with equals sign (=) and there are query params after that, the query params are removed by angular.

Let's take a two links as example:
1.  https://angular-eaf2ld.stackblitz.io/hello/my_name?abc=1
2.  https://angular-eaf2ld.stackblitz.io/hello/my_name=?abc=1

If you go into first link, you will see that link doesn't change and the hello component wrote "my_name". 

If you go into second link, you will see that link has been rewritten to https://angular-eaf2ld.stackblitz.io/hello/my_name so component still wrote "my_name" instead of "my_name=" and removes all query params.

The problem is really important, because we have a Backend API that we can not change in any way, and backend send email to client with link to frontend, where they pass TOKEN that often ends with = and few query params. So, token is invalid, and query params are missed.

## 🔬 Minimal Reproduction
Edit panel: https://stackblitz.com/edit/angular-eaf2ld

As you can see, I used latest verion of Angular (8.1.2).

**Comment by Airblader** [comment] 2019-07-20 17:12
I'm fairly sure that an equals sign at that position would have to be encoded to form a valid URL.

**Comment by namerci** [comment] 2019-07-20 17:24
Maybe, but it works well without encoding on AngularJS and old fashion
websites.

sob., 20 lip 2019, 19:14 użytkownik Ingo Bürk <notifications@github.com>
napisał:

**Comment by atscott** [comment] 2020-01-23 23:43
Duplicate of #21381

**Closed by atscott** 2020-01-23 23:43 UTC
Labels: comp: router
