### ISSUE TITLE
Add ngc option to inline templates for libraries.

### ISSUE THREAD

**Issue by filipesilva** [angular/angular#16157] opened 2017-04-19 12:59 UTC
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Angular library authors should inline templates (html/css) to ensure overall compatibility between different consumer types. 

This can be done with a fairly simple [script](https://github.com/filipesilva/angular-quickstart-lib/blob/master/inline-resources.js), but it has a few pitfalls:
- special care must be taken to maintain sourcemap lines (inline over TS sources before `ngc`).
- unit testing requires a separate module.id based setup to load templates into karma.
- no watch mode.

**Expected behavior**

Since inlining is heavily encouraged for library AOT compilation, it should be included as an option for `ngc` (e.g. `angularCompilerOptions.inlineTemplates`).

**Minimal reproduction of the problem with instructions**
An example library can be found at https://github.com/filipesilva/angular-quickstart-lib.

**What is the motivation / use case for changing the behavior?**
Less work for everyone building and shipping components, one less point of failure.

* **Angular version:** 4.x
 
* **Language:** [ TypeScript 2.x ]

/cc @IgorMinar @jasonaden

**Comment by dherges** [comment] 2017-04-19 19:36
dupe of #15722

**Comment by dherges** [comment] 2017-05-19 09:39
As a workaround, you can use [gulp-inline-ng2-template ](https://github.com/ludohenin/gulp-inline-ng2-template) writing to intermedita TypeScript sources, which are then compiled by `ngc`. [Here is an example](https://github.com/dherges/ng-packagr/blob/master/steps/assets.ts#L22-L43).

**Comment by pdmshrestha** [comment] 2017-09-18 11:51
@dherges the second link is dead. Could you provide working link?

**Comment by mlc-mlapis** [comment] 2017-09-18 13:33
... this one? https://github.com/dherges/ng-packagr/blob/master/src/lib/steps/assets.ts#L22-L43

**Comment by dherges** [comment] 2017-11-10 15:41
cc @filipesilva 

You had something in mind like [TypeScript transformations](http://blog.scottlogic.com/2017/05/02/typescript-compiler-api-revisited.html)?

**Comment by dherges** [comment] 2017-11-12 13:25
Hi @filipesilva,

is like you said: `ngc` generates the AoT metadata **BEFORE** TypeScript transformations are applied. Tried [with customTransformers](https://github.com/dherges/ng-packagr/blob/095a24fe8d4a78b951fc86ec80f661bc52efe9ff/src/lib/steps/ts-transformers.ts#L35-L42):

```ts
  // Hook into TypeScript transformation API
  const customTransformers: ng.CustomTransformers = {
    beforeTs: [ componentTransformer ]
  };
```

```ts
    const visitComponents = (node: ts.Decorator): ts.Node => {
      if (isPropertyAssignment(node) && node.name.getText() === 'templateUrl') {
        return ts.updatePropertyAssignment(
          node,
          ts.createIdentifier('template'),
          ts.createLiteral('foobar')
        );
      }

      return ts.visitEachChild(node, visitComponents, context);
    };
```

And then, the `.metadata.json` still includes "templateUrl" but the `.js` files include the "template" property in the decorator.


--- 

(☀️ day in 🇩🇪  -> ☔️  ...)Oo

**Comment by dherges** [comment] 2017-11-13 18:32
Found a [workaround](https://github.com/dherges/ng-packagr/pull/279#issuecomment-344013115)https://github.com/dherges/ng-packagr/pull/279#issuecomment-344013115: explicitly call `ts.transform()`, then create a `ts.CompilerHost` reading `ts.SourceFile` from the previous transformation result.

Now I wonder whether we can apply `rollup` and `uglify` as `afterTs` transformers?

**Comment by filipesilva** [comment] 2017-11-14 10:55
Heya @dherges, thanks for looking into this! It's rather unfortunate that we can't truly run transforms before AOT does it's thing... I get how your workaround works but I expect that it would get cumbersome and error prone to maintain those patched in transforms in more complicated scenarios. 

@chuckjaz WDYT about allowing custom transforms before the AOT compiler ones?

**Comment by mlc-mlapis** [comment] 2017-11-14 12:17
It would be super elegant to do some things by this way.

> Allowing custom transforms before the AOT compiler ones.

**Comment by Toxicable** [comment] 2018-03-17 02:56
done via https://github.com/angular/angular/pull/22615

**Comment by dherges** [comment] 2018-03-17 16:28
Should someone like to do a rather academic study: try to figure out the impact of resource inlining (copy by value) vs. require()'ing resources (by reference).

Given that several components `require('shared.css')`, bundle sizes should go up (increased network traffic) and runtime/rendering performance should stay the same (at least for ViewEncapsulation.NATIVE and ViewEncapsulation.EMULATED - would ViewEncapsulation.NONE optimize for de-duplicating stylesheets?). In practice, I doubt that there's a relevant impact since most components would follow the "1 stylesheet, 1 component" rule of thumb.

**Comment by IgorMinar** [comment] 2018-04-16 06:26
done via b5be18f

**Closed by IgorMinar** 2018-04-16 06:26 UTC
Labels: comp: core & compiler, type: feature
