### ISSUE TITLE
IterableDiffer is not detecting changes within array

### ISSUE THREAD

**Issue by mertdeg2** [angular/angular#20309] opened 2017-11-09 20:28 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
IterableDiffer.diff is not detecting a change in the array item on certain cases. 

## Expected behavior
IterableDiffer.diff should detect changes in the array.

## Minimal reproduction of the problem with instructions
1. Go to https://plnkr.co/edit/RrCQmsYQHn0yzG4nzEjU?p=preview
2. On Chrome, Open Developers Console -> Console

## What is the motivation / use case for changing the behavior?
My actual use case is different than plunk above. But this is blocking me from using ChangeDetectionStrategy.OnPush along with IterableDiffer as its not detecting the change (Hence the view is not updated).

## Environment

<pre><code>
Angular version: 5.0.1

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [x] Chrome (iOS) 60.0.3112.113 (Official Build) (64-bit)
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by vicb** [comment] 2017-11-09 21:09
1) `IterableDiffer` compare elements by reference & do not recurse. This explains why your plunker does not work - and why we have the `indexBy` (If I remember the name correctly) on `NgFor`.
2) `ChangeDetectionStrategy.OnPush` compares input by reference (doesn't use an `IterableDiffer`)

So closing because works as intended

**Closed by vicb** 2017-11-09 21:09 UTC
