### ISSUE TITLE
state input of RouterLink does not work

### ISSUE THREAD

**Issue by broweratcognitecdotcom** [angular/angular#33173] opened 2019-10-15 12:34 UTC
# 🐞 bug report

### Affected Package
@angular/router: 8.1.2
@angular/router: 8.2.10

### Is this a regression?

No

### Description

state input of RouterLink does not work. However, Router.navigate() with state specified in NavigationExtras does work.

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-szomyj

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 8.1.2
Node: 10.16.0
OS: linux x64
Angular: 8.1.2
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.801.2
@angular-devkit/build-angular      0.801.2
@angular-devkit/build-ng-packagr   0.801.2
@angular-devkit/build-optimizer    0.801.2
@angular-devkit/build-webpack      0.801.2
@angular-devkit/core               8.1.2
@angular-devkit/schematics         8.1.2
@angular/cdk                       8.1.1
@angular/material                  8.1.1
@angular/material-moment-adapter   8.1.1
@ngtools/webpack                   8.1.2
@schematics/angular                8.1.2
@schematics/update                 0.801.2
ng-packagr                         5.4.0
rxjs                               6.5.2
typescript                         3.4.5
webpack                            4.35.2

</code></pre>

**Anything else relevant?**
Also doesn't work in "@angular/router": "8.2.10", see the StackBlitz

**Comment by trotyl** [comment] 2019-10-15 12:44
Confirmed, seems to be a silly mistake that `state` handling only added to `RouterLinkWithHref`, but missing in `RouterLink`:

https://github.com/angular/angular/blob/8b0cb2f0c503f6be25ae070b0588774285374d04/packages/router/src/directives/router_link.ts#L260-L264

https://github.com/angular/angular/blob/8b0cb2f0c503f6be25ae070b0588774285374d04/packages/router/src/directives/router_link.ts#L163-L166

**Comment by santoshyadav198613** [comment] 2019-10-15 19:02
@trotyl @broweratcognitecdotcom ,
Are you planning to open a PR, or should I go ahead and open one.

**Comment by trotyl** [comment] 2019-10-16 01:10
> @trotyl @broweratcognitecdotcom ,
> Are you planning to open a PR, or should I go ahead and open one.

@santoshyadav198613 Negative from my side, feel free to go ahead (if OP don't mind) 😃

**Comment by broweratcognitecdotcom** [comment] 2019-10-16 06:59
@santoshyadav198613 Please do so.

**Comment by santoshyadav198613** [comment] 2019-10-16 08:27
Cool thanks guys will raise an PR today. @kapunahelewong can you tag it under community I will work on it.

**Comment by broweratcognitecdotcom** [comment] 2020-01-08 08:14
@atscott inconvenient? The feature is downright broken.

**Comment by psenechal** [comment] 2020-03-30 21:17
Not sure if this comment in the CHANGELOG indicates that this was supposed to be fixed in 9.1.0:

router: state data missing in routerLink (#33203) (de67978)

But it appears to be broken again in 9.1.0. It was working fine in 9.0.7.
If I don't use routerLink in the html and navigate from the component using router.navigate instead, it works fine.

**Comment by atscott** [comment] 2020-03-30 21:24
The changelog is incorrect - the commit was reverted, as noted in the PR (changelog generation doesn't understand reverted PRs and the manual correction is prone to errors). Waiting on PR author to add a test case.

**Closed** 2020-04-07 18:31 UTC
Labels: comp: router, freq2: medium, severity2: inconvenient, type: bug/fix
