### ISSUE TITLE
Module parse failed: Identifier 'ɵngcc0' has already been declared 

### ISSUE THREAD

**Issue by buhosiliscodirococo** [angular/angular#41206] opened 2021-03-14 08:08 UTC
# 🐞 bug report

### Affected Package

 

./node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js
./node_modules/@ngtools/webpack/src/ivy/index.js

### Description

 
In a basic project (some path modifications and nothing else) I installed angular material, I was try angular material, then installed ng bootstrap and I think right after that the error appeared.
This error occurred earlier in the same week in a project under the same circumstances, which I could not solve. 

## 🔬 Minimal Reproduction

 https://stackblitz.com/...

## 🔥 Exception or Error
<pre><code>

Error: ./node_modules/@angular/forms/__ivy_ngcc__/fesm2015/forms.js 27:12
Module parse failed: Identifier 'ɵngcc0' has already been declared (27:12)
File was processed with these loaders:
 * ./node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js
 * ./node_modules/@ngtools/webpack/src/ivy/index.js
You may need an additional loader to handle the result of these loaders.
|  */
| import * as ɵngcc0 from '@angular/core';
> import * as ɵngcc0 from '@angular/core';
| const NG_VALUE_ACCESSOR = new InjectionToken('NgValueAccessor');
| 

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 11.2.4
Node: 15.9.0
OS: darwin x64

Angular: 11.2.5
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.4
@angular-devkit/build-angular   0.1102.4
@angular-devkit/core            11.2.4
@angular-devkit/schematics      11.2.4
@angular/cli                    11.2.4
@schematics/angular             11.2.4
@schematics/update              0.1102.4
rxjs                            6.6.6
typescript                      4.1.5

</code></pre>

**Anything else relevant?**

VS Code 1.54.2
macOS Mojave

**Comment by JoostK** [comment] 2021-03-14 15:58
Duplicate of #41198.

**Closed by JoostK** 2021-03-14 15:58 UTC
