### ISSUE TITLE
common/http: HttpParams encoding of form data

### ISSUE THREAD

**Issue by achimha** [angular/angular#18261] opened 2017-07-20 19:58 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When using `HttpClient` to send form data using `HttpParams`, a plus sign (+) in a parameter is not correctly encoded.

## Expected behavior

Encoding should be correct.

## Minimal reproduction of the problem with instructions

https://plnkr.co/edit/x4T7Dw4QZgHRHfyFaNWz?p=preview

The plunker performs a bogus HTTP POST request with form data that contains an email address containing a plus sign.

## Environment

<pre><code>
Angular version: 4.3.1

Browser:
- [x] Chrome (desktop) version 59

**Comment by achimha** [comment] 2017-07-20 20:03
The relevant code:

```
export class App implements OnInit {
  constructor(private http: HttpClient) {
  }
  
  ngOnInit() {
    const body = new HttpParams().set('email', 'my+name@email.com');
    this.http.post('/foobar', body).subscribe(() => {});
  }
}
```

**Comment by trotyl** [comment] 2017-07-21 02:25
Relates to https://github.com/angular/angular/issues/11058

**Comment by CDDelta** [comment] 2017-07-21 05:43
It seems like the params are being encoded with this function.
```
function standardEncoding(v: string): string {
  return encodeURIComponent(v)
      .replace(/%40/gi, '@')
      .replace(/%3A/gi, ':')
      .replace(/%24/gi, '$')
      .replace(/%2C/gi, ',')
      .replace(/%3B/gi, ';')
      .replace(/%2B/gi, '+')
      .replace(/%3D/gi, '=')
      .replace(/%3F/gi, '?')
      .replace(/%2F/gi, '/');
}
```
is there a reason to replace '%2b' with '+'? This makes it so that there is not way to encode a '+' with `HttpParams`.

**Comment by wirefreethought** [comment] 2017-09-11 01:47
This bug currently makes it impossible for me to use HttpClient to encode a latitude/longitude param in ISO-6709 format (which uses the +/- separator between the values).

**Comment by lostllama** [comment] 2017-09-21 04:50
This bug also makes it impossible to put _some_ e-mail addresses in the query string (for example, a search). As demonstrated by Google, a + is a valid symbol in an e-mail address. For example `testuser+github@gmail.com`.

Angular removes the encoding for the + symbol, apparently because IETF RFC 3986 lists it as one of the characters that is valid in a query string parameter. That's true, it is valid if it's intended as a _space_. What happens with the e-mail above, is that when it reaches the server, the server interprets it as "testuser github@gmail.com" and predictably can't find a corresponding e-mail address.

**Comment by orestes** [comment] 2017-10-02 14:39
I'm hitting this bug when sending out ISO datetimes including a timezone offset

**Comment by sting2804** [comment] 2017-10-04 09:00
The same problem.

**Comment by wirefreethought** [comment] 2017-10-21 00:47
For anyone who can't wait for the eventual patch, I was able to workaround this by manually encoding the '+' and appending the param to the HttpClent uri via '?'. As in:
```
    const myEncodedQueryParamValue = myQueryParamValue.replace("+", "%2B");
    const endpoint = myEndpoint + "?myQueryParam=" + myEncodedQueryParamValue;

    return this.httpClient.get<MyResponseType>(
      endpoint,
      {
        params: myParams
      }
    );
```
HttpClient will do the right thing here and append any passed-in HttpParams to the existing query string.

**Comment by orestes** [comment] 2017-10-21 01:16
What I've done is implement `HttpParameterCodec` into a simple encoder that uses the browser standard `encodeURIComponent` [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent).

```typescript
class CustomEncoder implements HttpParameterCodec {
  encodeKey(key: string): string {
    return encodeURIComponent(key);
  }

  encodeValue(value: string): string {
    return encodeURIComponent(value);
  }

  decodeKey(key: string): string {
    return decodeURIComponent(key);
  }

  decodeValue(value: string): string {
    return decodeURIComponent(value);
  }
}
```

And then use it when I need HttpParams instances.

```typescript
// These params get encoded correctly
const params = new HttpParams({encoder: new CustomEncoder()});
```

**Comment by tiangolo** [comment] 2017-11-25 21:03
I created a PR to solve this here: https://github.com/angular/angular/pull/19710 .

---

I also created a package to solve it (at least while it is reviewed / merged) for the case of `HttpClient`. It's a simple drop-in replacement that modifies the minimum to fix the problem. It works with just changing one import.

Check it here: https://github.com/tiangolo/ngx-http-client

**Comment by etorras** [comment] 2018-02-19 11:17
We have the inverse problem, when we put the URL on the browser like this `https://example.com?someQueryParam=My+Query+Param+With+Plus+Sign` Angular transform all the `+` to `%2B`, we build a pretty friendly URL in other script (or in our fronted server) but when came to Angular the problem begins!

Any helps?

Many thanks!

**Comment by dantman** [comment] 2018-04-27 01:46
This issue breaks the password flow of [angular-oauth2-oidc](https://www.npmjs.com/package/angular-oauth2-oidc) for emails (and presumably passwords) that have a plus in them.

**Comment by dorival** [comment] 2018-06-07 20:37
This issue is back on Angular 6.0.3, passing parameters through `http.get` with a query value containing "+" sign is being converted to %20, arriving wrong in the server side.

**Comment by vitorfgsantos** [comment] 2018-10-02 18:34
> What I've done is implement `HttpParameterCodec` into a simple encoder that uses the browser standard `encodeURIComponent` [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent).
> 
> ```ts
> class CustomEncoder implements HttpParameterCodec {
>   encodeKey(key: string): string {
>     return encodeURIComponent(key);
>   }
> 
>   encodeValue(value: string): string {
>     return encodeURIComponent(value);
>   }
> 
>   decodeKey(key: string): string {
>     return decodeURIComponent(key);
>   }
> 
>   decodeValue(value: string): string {
>     return decodeURIComponent(value);
>   }
> }
> ```
> 
> And then use it when I need HttpParams instances.
> 
> ```ts
> // These params get encoded correctly
> const params = new HttpParams({encoder: new CustomEncoder()});
> ```

Me too. I've created a new class that extends HttpUrlEncodingCodec, and overwritten two of its functions.

`import { HttpUrlEncodingCodec } from '@angular/common/http';

export default class CustomEncoder extends HttpUrlEncodingCodec {
  encodeKey(key: string): string {
    return encodeURIComponent(key);
  }

  encodeValue(value: string): string {
    return encodeURIComponent(value);
  }
}`

**Comment by MarkoSulamagi** [comment] 2018-10-10 13:00
@vitorfgsantos 

> > ...
> 
> Me too. I've created a new class that extends HttpUrlEncodingCodec, and overwritten two of its functions.
> 
> ```ts
> import { HttpUrlEncodingCodec } from '@angular/common/http';
> 
> export default class CustomEncoder extends HttpUrlEncodingCodec {
>   encodeKey(key: string): string {
>     return encodeURIComponent(key);
>   }
> 
>   encodeValue(value: string): string {
>     return encodeURIComponent(value);
>   }
> }
> ```

Don't forget to make the class Injectable and inject it in constructor. Otherwise testing gets more complicated.

```
@Injectable({
  providedIn: 'root'
})
export default class CustomEncoder extends HttpUrlEncodingCodec {
```

```
constructor(private customEncoder: CustomEncoder) { }

const params = new HttpParams({encoder: this.customEncoder});
```

**Comment by FARHANE** [comment] 2018-11-12 10:38
Bug angular 7.0.2

**Comment by Royceb** [comment] 2019-02-06 22:31
Hitting this when trying to send a phone number to the backend:

```
const body = new HttpParams().set('phoneNumber', phoneNumber) // phoneNumber === +1234567890

return this.http.post(url, body, {
      headers: new HttpHeaders().set('Content-Type', 'application/x-www-form-urlencoded')
});
```

![image](https://user-images.githubusercontent.com/3469263/52378145-c76ffe80-2a1b-11e9-9075-911810715225.png)

@orestes's custom encoder worked.

**Comment by arlowhite** [comment] 2019-02-12 22:00
@alxhub What's the reasoning behind these exceptions to `encodeURIComponent`?
https://github.com/angular/angular/blame/f8096d499324cf0961f092944bbaedd05364eea1/packages/common/http/src/params.ts#L59

I'm guessing this is for Router URLs?
`HttpClient` should not be using `standardEncoding()`, it should just use `encodeURIComponent()`

**Comment by cherurg** [comment] 2019-07-18 14:28
I also tried posting `phoneNumber`. However, I have to use `URLSearchParams` instead of `HttpParams`. For me, none of the solutions worked.

**Comment by apoklyak** [comment] 2019-07-19 12:13
Hello everyone!
I am also sending the string with + character (+375) and my server is receiving my string correctly, that is +375.

But in Chrome, I see the next data: https://i.gyazo.com/4e475a8446078fbd6641e2b85e970cc6.png

It seems like I have space instead of plus :)
But it works.

And If I click in the 'View URL encoded' link in Chrome, I will get data with plus character.
Look at https://i.gyazo.com/1581c20433272986727a5212630f6323.mp4

I don't know why it is. Why do I get the space?

**Comment by Snupss** [comment] 2019-12-06 15:42
How is this not fixed still?
Why was this behavior added in the first place?

**Comment by christiaan-lombard** [comment] 2019-12-11 11:39
Encountered this attempting to url encode ISO8601 timestamp, eg. '2019-05-22T04:20:33+0000' :(

Angular 8.2.14

What is the reasoning behind these exceptions to 'encodeURIComponent'?

Stackblitz: https://stackblitz.com/edit/angular-url-encode

**Comment by rdkmaster** [comment] 2020-04-17 07:21
Any updates with this issue now?

**Comment by kashesandr** [comment] 2020-04-24 10:19
Experiencing the same issue

**Comment by piotrkorlaga** [comment] 2020-04-24 10:31
Guys, I proposed some solution on SO: https://stackoverflow.com/a/52458069/4191683

**Comment by Lonli-Lokli** [comment] 2020-05-28 20:55
Most of all I like tag freq1: low with the issue with 102 upvotes

**Comment by alxhub** [comment] 2020-05-29 18:48
I'm going to close this as a duplicate of #11058 - we'll track this problem there.

**Closed by alxhub** 2020-05-29 18:48 UTC
Labels: comp: common/http, comp: http, freq1: low, severity3: broken, triage #1, type: bug/fix
