### ISSUE TITLE
Directives don't apply to dynamically rendered components

### ISSUE THREAD

**Issue by maxkorz** [angular/angular#25067] opened 2018-07-24 14:23 UTC
## I'm submitting a...

<pre><code>[x] Bug report</code></pre>

## Current behavior
Directive with element-name selector doesn't apply to dynamically rendered components.

## Expected behavior
The opposite behavior.

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-lnpyo9?file=src%2Fapp%2Fapp.component.ts

`ElementComponent` should turn green when component is loaded dynamically.

Open console to see `console.log` output. You will notice that message `Initialized: ElementDirective` appears for when a component is rendered statically and conditionally, but not when dynamically.

## What is the motivation / use case for changing the behavior?
I wanted to extend (patch) a component from a 3rd party package. This bug prevents me from doing so. Maybe there are other use-cases, but I can't think of any.

## Environment
<pre><code>Angular version: 6.0.x</code></pre>

**Comment by maxkorz** [comment] 2018-07-24 14:29
Sorry for off topic

@mlc-mlapis 
> A software bug is an error, flaw, failure or fault in a computer program or system that causes it to produce an incorrect or unexpected result, or to behave in unintended ways.

The fact that directives don't apply to dynamically loaded components is an incorrect and unexpected result. Thus this is a bug by definition.

**Comment by mlc-mlapis** [comment] 2018-07-24 15:47
@maxkorz ... lol, it was never meant to work from the beginning by design so how can you call it bug?

**Comment by maxkorz** [comment] 2018-07-24 17:43
@mlc-mlapis sorry, how do you know that? I don't see Contributor or Member tag next to your name.

**Comment by mhevery** [comment] 2018-07-31 22:56
Selectors are evaluated at compile time, not runtime, hence can't be evaluated for dynamically inserted components. There is no plan to complicate when selectors get evaluated to support such a feature. 

Closing as working as intended.

**Closed by mhevery** 2018-07-31 22:56 UTC
Labels: comp: core & compiler
