### ISSUE TITLE
Allow the service-worker to immediately update an application upgrade

### ISSUE THREAD

**Issue by omatrot** [angular/angular#46504] opened 2022-06-27 07:20 UTC
### Which @angular/* package(s) are relevant/related to the feature request?

service-worker

### Description

As far as I know, upon documentation, I quote "In the interest of speed, the service worker doesn't wait to check for updates before it serves the application that it has cached."

I see a problem with this, especially if the corresponding API and the application have both changed. They must be in sync. 

Thanks.

### Proposed solution

Allow to opt-out from the default behaviour.

### Alternatives considered

Are there any simple alternatives ?

**Comment by gkalpak** [comment] 2022-06-27 16:25
Checking for updates before serving the request would take too much time, thus beating most of the purpose of a Service Worker. In general, if you intend to use a ServiceWorker (and want to benefit from it), your application and config should be crafted in a way that it can benefit from the presence of a ServiceWorker. For example, you should try to let the ServiceWorker cache static assets that it will need to serve with a specific app version (i.e. `index.html` + lazy bundles).

Regarding an API endpoint in particular, it is a common practice to version it independently of the app and keep older versions around (for some time) to avoid breaking clients. Having an older app version break because the API has changed is a problem that is not related to ServiceWorkers (i.e. it can happen without a ServiceWorker) and should be accounted for anyway.

That said, you can instruct the ServiceWorker to try to fetch responses from the server (only falling back to the cache if the server fails to respond is a specified period) by using `freshness` as the [navigation request strategy][1] and [data-group cache strategy][2].

I hope this covers your needs.
I am going to close this issue, since the current behavior is as intended. But feel free to continue the discussion below.

[1]: https://angular.io/guide/service-worker-config#navigationrequeststrategy
[2]: https://angular.io/guide/service-worker-config#strategy
[3]: https://angular.io/guide/service-worker-config#assetgroups

**Closed by gkalpak** 2022-06-27 16:25 UTC
Labels: comp: service-worker
