### ISSUE TITLE
pipe: number pipe does not work on mobile browsers

### ISSUE THREAD

**Issue by varadero** [angular/angular#7396] opened 2016-03-03 14:48 UTC
Simply add anywhere in template the following:

```{{123456 | number}}```
or
```{{123456 | number:'4.2-2'}}```

In desktop browsers (Firefox, Chrome, IE10) the value is correctly interpolated as:
```
123,456
```
or
```
123,456.00
```

but on mobile browsers on iPad iOS 9.2.1 (Chrome 47, Safari, Firefox 2.0) it fails resulting in empty value.

**Comment by zoechi** [comment] 2016-03-03 15:10
What polyfills did you add? What Angular version?

**Comment by varadero** [comment] 2016-03-03 15:40
This is mine index.html - angular version is 2.0.0-beta.7

```
    <!-- Fix for IE + angular 2 beta 3 -->
    <script>
        //<![CDATA[
        if (!Object.hasOwnProperty('name')) {
            Object.defineProperty(Function.prototype, 'name', {
                get: function() {
                var matches = this.toString().match(/^\s*function\s*(\S*)\s*\(/);
                var name = matches && matches.length > 1 ? matches[1] : "";
                // For better performance only parse once, and then cache the
                // result through a new accessor for repeated access.
                Object.defineProperty(this, 'name', {value: name});
                return name;
                }
            });
        }
        //]]
    </script>

    <script src="node_modules/es6-shim/es6-shim.min.js"></script>
    <script src="node_modules/systemjs/dist/system-polyfills.js"></script>

    <script src="node_modules/angular2/bundles/angular2-polyfills.js"></script>
    <script src="node_modules/systemjs/dist/system.js"></script>
    <script src="node_modules/rxjs/bundles/Rx.min.js"></script>
    <script src="node_modules/angular2/bundles/angular2.dev.js"></script>
    <script src="node_modules/angular2/bundles/router.dev.js"></script>
    <script src="node_modules/angular2/bundles/http.dev.js"></script>
```

**Comment by wesleycho** [comment] 2016-06-01 13:54
This seems to be a duplicate of #3333, as the NumberPipe uses NumberFormatter from the intl facade, which uses the Intl api. One needs to polyfill for Intl.

**Closed** 2016-06-01 16:16 UTC
