### ISSUE TITLE
Manual FormControl setErrors lose state during component lifeCycle (initialization process)

### ISSUE THREAD

**Issue by ama1er** [angular/angular#48515] opened 2022-12-16 11:55 UTC
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

No

### Description

When you set the errors of a `FormControl` manually inside the `ngOnInit `process, the error state ins't reflected after the component closure. The FormControl contains **no** direct **validators**, the error should be handled only in a manual process. The control value is not lost.

```
  group = new FormGroup({
    text: new FormControl(null),
  });

  ngOnInit(): void {
    this.group.controls.text.setValue('Hello');
    this.group.controls.text.setErrors({ texterror: 'notallowed' });
    // the value is written to the control.
    // the error is available on the control.
  }

  ngAfterViewInit(): void {
    // the value is still in the control.
    // the error is no longer available on the control.
  }

```

Provided `setErrors` is processed via `setTimeout`, this works. Therefore this could also be a duplicate of #38191. 

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-form-manual-error?file=src%2Fapp%2Fapp.component.ts

### Please provide the exception or error you saw

```true
The manual error state ins't reflected. See the console.log of provided stackblitz sample.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```
Angular CLI: 14.0.7
Node: 16.17.1
Package Manager: npm 8.15.0
OS: win32 x64

Angular: 15.0.4
... animations, common, compiler, core, forms, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1402.10
@angular-devkit/build-angular   14.2.10
@angular-devkit/core            14.2.10
@angular-devkit/schematics      14.0.7
@angular/cli                    14.0.7
@angular/compiler-cli           14.2.12
@schematics/angular             14.0.7
rxjs                            7.8.0
typescript                      4.7.4
```

**Comment by urugator** [comment] 2023-04-03 08:50
+1. In my case I am loosing errors just by rendering the form conditionally:
I hide the form on submit, then map server errors to controls and unhide the form. Because the form is "remounted", validators re-run and errors are lost. Took quite some time to realize what's happening.
Running validators as a side effect of rendering process is absolutely unexpected and confusing behavior.

**Comment by JeanMeche** [comment] 2024-04-08 23:59
Let's close this as a dupe of #38191. 

Also note that validation will erase any existing errors.

**Closed by JeanMeche** 2024-04-08 23:59 UTC
Labels: area: forms
