### ISSUE TITLE
Error: Expected to be running in 'ProxyZone', but it was not found

### ISSUE THREAD

**Issue by alavaros** [angular/angular#40977] opened 2021-02-24 10:50 UTC
# 🐞 bug report

### Affected Package

zone.js

### Is this a regression?

No

### Description

When I try to implement an asynchronous test with `waitForAsync` I get the following error:
```
1) should behave...
     MyService
     Error: Expected to be running in 'ProxyZone', but it was not found.
    at Function.ProxyZoneSpec.assertPresent (node_modules/zone.js/dist/zone-testing.js:210:1)
    at runInTestZone (C:/Path/To/My/Project/node_modules/zone.js/dist/zone-testing.js:1126:27)
    at UserContext.<anonymous> (C:/Path/To/My/Project/node_modules/zone.js/dist/zone-testing.js:1092:21)
    at ZoneDelegate.invoke (node_modules/zone.js/dist/zone-evergreen.js:364:1)
```

## 🔬 Minimal Reproduction

```
import { Injectable } from '@angular/core';
import { BehaviorSubject, Observable } from 'rxjs';

@Injectable({
  providedIn: 'root',
})
export class MyService {

  private myProperty: BehaviorSubject<boolean> = new BehaviorSubject(false);
  public myProperty$: Observable<boolean> = this.myProperty.asObservable();
  
  constructor() { }

  public toggleProperty(): void {
    this.myProperty.next(true);
  }
}
```
```
it('should behave...', waitForAsync(() => {
  service.toggleProperty();

  service.myProperty$.subscribe(value => {
    expect(value).toBe(true);
  });
}));
```

## 🔥 Exception or Error

```
1) should behave...
     MyService
     Error: Expected to be running in 'ProxyZone', but it was not found.
    at Function.ProxyZoneSpec.assertPresent (node_modules/zone.js/dist/zone-testing.js:210:1)
    at runInTestZone (C:/Path/To/My/Project/node_modules/zone.js/dist/zone-testing.js:1126:27)
    at UserContext.<anonymous> (C:/Path/To/My/Project/node_modules/zone.js/dist/zone-testing.js:1092:21)
    at ZoneDelegate.invoke (node_modules/zone.js/dist/zone-evergreen.js:364:1)
```

## 🌍  Your Environment

**Angular Version:**

```
"@angular/*": "11.1.1",
"zone.js": "0.10.3"
```

**Anything else relevant?**

**Comment by gkalpak** [comment] 2021-02-24 14:00
@alavaros, what does your `test.ts` file look like?

**Comment by alavaros** [comment] 2021-02-25 09:29
> @alavaros, what does your `test.ts` file look like?

```
// This file is required by karma.conf.js and loads recursively all the .spec and framework files

// tslint:disable:ordered-imports
import { getTestBed } from '@angular/core/testing';
import {
  BrowserDynamicTestingModule,
  platformBrowserDynamicTesting,
} from '@angular/platform-browser-dynamic/testing';
import 'zone.js/dist/zone-testing';
// tslint:enable:ordered-imports

declare const require: any;

// First, initialize the Angular testing environment.
getTestBed().initTestEnvironment(
  BrowserDynamicTestingModule,
  platformBrowserDynamicTesting(),
);
// Then we find all the tests.
const context = require.context('./', true, /\.spec\.ts$/);
// And load the modules.
context.keys().map(context);
```

**Comment by gkalpak** [comment] 2021-02-25 10:01
That's the problem then :smiley:
`import 'zone.js/dist/zone-testing'` must be the first import on that file. The disabled `ordered-imports` tslint rule seems to be a step in the right direction, but it seems that the imports were re-ordered anyway, which is what causes the error you are seeing :smiley:

I am going to close this, since restoring the order of the imports should solve the problem.

**Closed by gkalpak** 2021-02-25 10:01 UTC
Labels: comp: zones

**Comment by alavaros** [comment] 2021-02-25 10:43
> That's the problem then 😃
> `import 'zone.js/dist/zone-testing'` must be the first import on that file. The disabled `ordered-imports` tslint rule seems to be a step in the right direction, but it seems that the imports were re-ordered anyway, which is what causes the error you are seeing 😃
> 
> I am going to close this, since restoring the order of the imports should solve the problem.

I already tried that, and I get the same error.

Some time ago, in another project and with another Angular version I ran into the same problem and it was solved by putting that import at the beginning.

But this is not the case, because there was no `waitForAsync` back then, so it's still a bug.

Please reopen it.

**Comment by gkalpak** [comment] 2021-02-25 13:34
Sorry, but I could not reproduce the error with the code you provided. Happy to re-open this if you can provide a minimal reproduction :pray:
