### ISSUE TITLE
Improperly Formed Component Markup Fails Silently

### ISSUE THREAD

**Issue by roblarsen** [angular/angular#24613] opened 2018-06-21 19:43 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

We ran into this issue and it took us a while to figure out what exactly was going on. [I've provided a reduced test case](https://github.com/roblarsen/angular-reduced-test-case), but the gist is, if you have two components, `app-component-one` and `app-component-two` included in your app and instead of closing component `app-component-one` properly you accidentally insert a second non-closed instance of app-component-one, `app-component-two` will not render. Nothing after the un-closed component renders.   

```html
  <h1>
    Main component
  </h1>
<app-component-one><app-component-one>
<app-component-two></app-component-two>
```

Renders as follows:

![image](https://user-images.githubusercontent.com/361421/41741072-0aab8bc4-7568-11e8-8273-a455d2c1555f.png)

This is the result with properly closed components

![image](https://user-images.githubusercontent.com/361421/41741690-cf9d83d2-7569-11e8-9b7c-b8466035b79e.png)

Obviously, there's an error in the code. `app-component-one` should be closed properly. 

```html
<app-component-one></app-component-one>
```

The problem, as I see it, is that Angular swallows this error, somewhere. It just stops rendering the parent  component (?) and there's no error in the console or in the compiler indicating that something went awry.

## Expected behavior
Either it would fail to compile or at minimum warn that there was a problem in the console. 

## Minimal reproduction of the problem with instructions

[I've provided a reduced test case](https://github.com/roblarsen/angular-reduced-test-case)

## Environment
Angular version 6.0.3

Browser:
- [x] Chrome (desktop) Version 67.0.3396.87 (Official Build) (64-bit)

**Comment by trotyl** [comment] 2018-06-22 03:16
Technically duplicate of https://github.com/angular/angular/pull/14136, which is considered expected as per https://github.com/angular/angular/pull/14136#issuecomment-306546468.

**Comment by roblarsen** [comment] 2018-06-22 03:54
Is this a dupe of that issue? The referenced issue is actually referring to HTML, referencing an unclosed `<div>.`  I'm not concerned with the compiler flagging invalid HTML. I don't care what people do with their HTML. As long as the browser renders it properly, go nuts. Save those bytes, if that's your thing. 

The example _here_ shows the rendering of Angular components failing in a way that wouldn't actually fail  in HTML. 

```html
<div>this doesn't actually stop rendering here. 
<div>BUT
<div>Angular would if the above were unclosed components</div>
```
Angular swallows the error. So... it's not behaving like modern HTML, which is designed to be forgiving of invalid markup and it's not behaving like xHTML (served as XML) which would die with invalid markup. We're in this laissez faire limbo where invalid markup is acceptable, in that it doesn't error, but it also doesn't work as expected (based on the experience of working with with modern HTML) and rendering dies in the template.

**Comment by trotyl** [comment] 2018-06-22 04:41
The `<app-component-one>` here is just an HTML tag, nothing different than `<div>`. And directive is not determined by element name, but selector.

The matching is performed on AST, say there is:

```text
- Element('h1')
  - Text('Main component')
- Element('app-component-one')
  - Element('app-component-one')
    - Element('app-component-two')
```

And how AST being generated has nothing to do with how the match process going.

I'm also in favor of revisiting this, but won't change the fact this is indeed an exact duplicate.

**Comment by pkozlowski-opensource** [comment] 2020-05-26 13:13
While I agree that the current behaviour could be super-confusing, this is how HTML works and this is what we've modeled our parsers after. In retrospect we could be more strict and go with sth similar to XHTML but changing this right now would be a massive breaking change :-/

**Comment by jessicajaniuk** [comment] 2022-03-14 23:35
It appears this behaves as expected. If you still feel there is an issue, please provide further details in a new issue.

**Closed by jessicajaniuk** 2022-03-14 23:35 UTC
Labels: freq2: medium, comp: compiler, core: basic template syntax, type: confusing, triage #1, design complexity: major, P5, compiler: parser
