### ISSUE TITLE
TS5055 Error. JS file would overwrite input file

### ISSUE THREAD

**Issue by Rasit1009** [angular/angular#20700] opened 2017-11-29 23:09 UTC
Hey everyone, 

Due to the fact that this is my first angular Project I am facing some Problems.. This error you are seeing below is driving me nuts.. None of the Solutions mentioned in similar issues seemed to work.
 I need to compile a js file, so I added "allowJS" to my tsconfig. Ever since then this error occurs. 
There is also a way to compile correctly. Every time I delete a letter, do ng serve, add the letter again, then do ng serve, the file is compiling correctly. 

The Error shown in terminal: 
![terminal_error](https://user-images.githubusercontent.com/29611057/33395548-35294278-d546-11e7-8bd8-e25fc9993d85.PNG)
My tsconfig file
![tsconfig](https://user-images.githubusercontent.com/29611057/33394806-d1e7cce0-d543-11e7-851d-095219ef2427.PNG)
the angular-cli.json file
![angular-cli](https://user-images.githubusercontent.com/29611057/33394811-d4e77f58-d543-11e7-884a-35da55512957.PNG)

I'd be thankful for help!

**Comment by yooRabbit** [comment] 2017-11-30 03:10
Same nuts problem in my case.

**Comment by trotyl** [comment] 2017-11-30 03:21
Duplicate of #19757

**Closed** 2017-11-30 04:30 UTC
