### ISSUE TITLE
Test bed and user story for Angular 2

### ISSUE THREAD

**Issue by matanlurey** [angular/angular#1144] opened 2015-03-27 20:48 UTC
There are a handful of tests in Angular's code base, but nothing that really does a good job giving non-Angular-core developers a way to test their components. See Angular Dart 1.0's `TestBed` for examples.

**Comment by vicb** [comment] 2015-03-27 20:55
duplicate of #615 
There is a google doc (early stage) attached in this issue, feel free to comment there

**Closed by vicb** 2015-03-27 20:55 UTC

**Comment by jbdeboer** [comment] 2015-05-01 22:56
This is closed, but https://github.com/angular/angular/pull/1160#issuecomment-88772048 claims that the fix doesn't actually cover the "non Angular-core developer" case.  There is also #1609 now, which is asking for the same time.
