### ISSUE TITLE
https://stackoverflow.com/questions/47864660/rxjs-pipe-does-not-work-in-angular-resolver-but-works-fine-in-ngoninit

### ISSUE THREAD

**Issue by rudybene** [angular/angular#21126] opened 2017-12-21 08:08 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Hello, we tried to add a RxJS pipe in our Angular Resolver: the resolver process starts but doesn't end, so we can't show the result in our html component.

## Expected behavior

We need to use Resolver to prepare and pass the necessary data to the component / view. Otherwise, everything works correctly if we move the pipe to the ngOnInit method of the main component.

## What is the motivation / use case for changing the behavior?

Example with myResolver.ts **(Resolve doesn’t end his process)**:

```
resolve(): Observable<any> | Promise<any> | any {
    let T = mergeMap((user: firebase.User) => {return Observable.fromPromise(user.getIdToken()) });
    let D = mergeMap((token: string) => { return this.http.get('https://myfakedomain.com/user?access_token=' + token) });
    let P = this.afAuth.authState // return Observable<User>
    .pipe(
    T, D
    )
    return P;
    }
```

Example with ngOnInit on mainComponent.ts **(it works!)**:

```
ngOnInit() {
    let T = mergeMap((user: firebase.User) => { return Observable.fromPromise(user.getIdToken()) });
    let D = mergeMap((token: string) => {return this.http.get(' https://myfakedomain.com/user?access_token=' + token) });
    let P = this.afAuth.authState // return Observable<User>
    .pipe(
    T, D
    ).subscribe(data => this.myData = data);
    }
```

## Environment

<pre><code>
Angular version: cli 1.3.0

Browser:
- [x] Chrome (desktop) version 60
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v8.3.0  
- Platform:  Linux 

Others:

</code></pre>

**Comment by trotyl** [comment] 2017-12-21 08:40
Duplicate of #10556, #18991.

And it's declared in [documentation](https://angular.io/guide/router):

> The Router guards require an Observable to complete, meaning it has emitted all of its values.

If you're interested in changing the current design, please follow the first linked issue.

**Comment by jasonaden** [comment] 2017-12-21 23:31
Closing as duplicate.

**Closed by jasonaden** 2017-12-21 23:31 UTC
Labels: comp: router
