### ISSUE TITLE
DomSanitizer, SafeHtml - Node is not defined

### ISSUE THREAD

**Issue by patrykp57** [angular/angular#23892] opened 2018-05-14 09:47 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

`ERROR ReferenceError: Node is not defined`  appears in  Node console after compilation.

It's linking to function :
```
function isTemplateElement(el) {
    return el.nodeType === Node.ELEMENT_NODE && el.nodeName === 'TEMPLATE';
}
```
## Expected behavior

Error shouldn't appear

## Minimal reproduction of the problem with instructions

Problem is related to DomSanitizer and SafeHtml module. My sample usage

```
import { Pipe, PipeTransform } from "@angular/core";
import { DomSanitizer, SafeHtml } from '@angular/platform-browser';

@Pipe({
  name: 'sanitizeHtml'
})
export class SanitizeHtmlPipe implements PipeTransform {

  constructor(private _sanitizer:DomSanitizer) {
  }

  transform(v:string):SafeHtml {
    return this._sanitizer.bypassSecurityTrustHtml(v);
  }
}
```

## Environment

<pre><code>
Angular version: 6.0.1

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 9.4.0
- Platform:  Window

Others:

</code></pre>

**Comment by trotyl** [comment] 2018-05-14 09:58
Duplicate of https://github.com/angular/angular/issues/23280, https://github.com/angular/angular/issues/23741

**Comment by IgorMinar** [comment] 2018-05-22 22:55
Closing in favor of #23280 - please follow that issue for updates.

**Closed by IgorMinar** 2018-05-22 22:55 UTC
Labels: comp: core & compiler
