### ISSUE TITLE
Feature: Allow functions to return html

### ISSUE THREAD

**Issue by jmsutorus** [angular/angular#51404] opened 2023-08-17 16:35 UTC
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

It would be great if in angular I could build html in a function and return it to the template. I find it difficult to write small reusable code in angular to accomplish a single task when it involves HTML and logic together.

### Proposed solution

Allow functions to return HTML with inline css so that those functions can be used across many different components.

```
    <ul>
        {{ myFunc(myList) }}
    </ul>
```

```
    myFunc(list) {
        return list.map( x => { <li style="margin: 25px"> hello world {{ x }} </li> });
    }
```

### Alternatives considered

The alternative to the description above is to just run a ngFor loop over the list and map it to the function that you need to call. Then put all this in a component and reference it where you need it.  But for more complex applications would be nice to isolate html with logic for reusability across many components.

```
<ul>
  <li *ngFor="let x of things"> (1)
    {{ myFunc(x) }}
  </li>
 </ul>
```

```
myFunction(x) {
    return 'hello world ' + x;
 }
```

**Comment by JoostK** [comment] 2023-08-17 16:54
This is a duplicate of #43120 in spirit. There are no plans to adopt a JSX-like expression approach to Angular templates.

**Closed by JoostK** 2023-08-17 16:54 UTC
