### ISSUE TITLE
HTML Number fields being bounds as Strings

### ISSUE THREAD

**Issue by jondejong** [angular/angular#7945] opened 2016-04-07 14:59 UTC
If a bound value can be of more than one type, then HTML Number input fields are being bound as Strings. My expectation is that they should be bound to the same type as the input field. In my case, we change the type of the input field based on value of other fields on the form. This becomes a problem downstream when REST service is expecting numbers but gets strings. Obviously, there are a lot of downstream work arounds for this involving parsing the numbers and changing the types (both the Angular app, and the REST service), but none the less, it **feels** like a bug. Below is a very contrived example to demonstrate the problem. 

**Current behavior**

Typescript snippet:

    export class Demo {
      value: number | String;
      inputType:String;

      constructor() {
        this.inputType = 'text';
      }

      makeNumber() {
        this.inputType = 'number';
      }

      log() {
        console.log(JSON.stringify(this.value));
      }
    };

HTML:

    <div>
      <input [(ngModel)]=.value" [type]="inputType">
    </div>
    <span class="button" (click)="makeNumber()">Make Number</>
    <span class="button" (click)="log()">Log This</>
    

**Expected/desired behavior**

User clicks the "Make Number" button, enters 42 in the what is now a number input field, and then clicks "Log This". The console should log:

    42

**Other information**

User clicks the "Make Number" button, enters 42 in the what is now a number input field, and then clicks "Log This". The console actually logs:

    "42"

**Comment by zoechi** [comment] 2016-04-07 15:21
dup of #6919 or #7945

**Comment by pkozlowski-opensource** [comment] 2016-06-02 12:47
Closing as a duplicate of #4014 (seems like it is fixed already). Thnx @zoechi

**Closed by pkozlowski-opensource** 2016-06-02 12:47 UTC
