### ISSUE TITLE
Control Flow Migration does not work correctly on template

### ISSUE THREAD

**Issue by yharaskrik** [angular/angular#53779] opened 2024-01-03 16:43 UTC
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

Running control flow migration on the following template does not work correctly.

Original Template:
```html
<ng-container *ngIf="generic; else specific">
    <ng-container [ngSwitch]="dueWhen">
        <ng-container *ngSwitchCase="due.NOW">
            <div class="alert alert-danger generic" [template]="tooltip" trTemplateTooltip position="centre-end">
                Required Information
            </div>
        </ng-container>
        <ng-container *ngSwitchCase="due.SOON">
            <div class="alert alert-warning generic" [template]="tooltip" trTemplateTooltip position="centre-end">
                Information Required Soon
            </div>
        </ng-container>
        <ng-container *ngSwitchDefault></ng-container>
    </ng-container>
</ng-container>
<ng-template #specific>
    <ng-container [ngSwitch]="dueWhen">
        <ng-container *ngSwitchCase="due.NOW">
            <div
                class="alert alert-danger"
                matTooltip="Stripe requires this information immediately to verify your account.">
                Required Now
            </div>
        </ng-container>
        <ng-container *ngSwitchCase="due.SOON">
            <div class="alert alert-warning" matTooltip="Stripe may require this information in the future.">
                Required Soon
            </div>
        </ng-container>
        <ng-container *ngSwitchDefault>
            <div class="trellis-p" [ngClass]="{ 'text-muted': !value && !overrideValue }">
                {{ value && !overrideValue ? value : altValue }}
            </div>
        </ng-container>
    </ng-container>
</ng-template>
<ng-template #tooltip>
    <tr-stripe-banking-missing-info [account]="account"></tr-stripe-banking-missing-info>
</ng-template>
```

Migrates to: 

```html
@if (generic) {
    @switch (dueWhen) {
        @case (due.NOW) {
            <div class="alert alert-danger generic" [template]="tooltip" trTemplateTooltip position="centre-end">
                Required Information
            </div>
        }
        @case (due.SOON) {
            <div class="alert alert-warning generic" [template]="tooltip" trTemplateTooltip position="centre-end">
                Information Required Soon
            </div>
        }
        @default {}
    }
} @else {
    @switch (dueWhen) {
        @case (due.NOW) {
            ">
            <div
                class="alert alert-danger"
                matTooltip="Stripe requires this information immediately to verify your account.">
                Required Now
            </div>
        }
        r>
        @case (due.SOON) {
            ">
            <div class="alert alert-warning" matTooltip="Stripe may require this information in the future.">
                Required Soon
            </div>
        }
        r>
        @default {
            t>
            <div class="trellis-p" [ngClass]="{ 'text-muted': !value && !overrideValue }">
                {{ value && !overrideValue ? value : altValue }}
            </div>
        }
        r>
    }
}

<ng-template #tooltip>
    <tr-stripe-banking-missing-info [account]="account"></tr-stripe-banking-missing-info>
</ng-template>
```

**Comment by OBe95** [comment] 2024-01-05 13:58
I was able to reproduce with the cli with `@angular/core:control-flow`

However, running the `control-flow` schematic from the `main` branch produces a correct migration, so I guess it's a matter of bumping `@angular/core` in the cli

I see @jessicajaniuk is the main contributor to the migration schematic, maybe you can confirm ?

**Comment by jessicajaniuk** [comment] 2024-01-08 19:20
I've been able to replicate this behavior and found the issue. The empty `<ng-container *ngSwitchDefault></ng-container>` was being migrated in a way that was throwing the offset off by 2 characters. This would only happen with empty ng-containers being converted to the new control flow where the control flow was on that container. Should be fixed after this lands.

**Comment by OBe95** [comment] 2024-01-08 20:02
@jessicajaniuk I am wondering if it was straightforward to reproduce

And if you would have an idea why I couldn't reproduce locally with the main branch (I started with a similar unit test to the one in your PR and it went through successfully then with the schematic same successfully migrated)

**Comment by jessicajaniuk** [comment] 2024-01-08 22:10
@OBe95 Without seeing your setup, I don't know. Even a single space or a line break in the ngSwitchDefault would make the test pass. So it could just be that.

**Comment by OBe95** [comment] 2024-01-08 22:30
I thought maybe there is a known pitfall that I missed
I don't think I had an extra whitespace, I'll retry and dive more into it
Thank you 🙏

**Closed** 2024-01-09 20:09 UTC
Labels: area: migrations, core: control flow
