### ISSUE TITLE
FormControl Validator.pattern RegExp with g flag causing invalidity

### ISSUE THREAD

**Issue by bojidaryovchev** [angular/angular#37538] opened 2020-06-11 13:49 UTC
# 🐞 bug report

FormControl Validator.pattern RegExp with g flag causing invalidity

### Description

In my case I wanted to verify that there are no trailing whitespaces at the start or end of the input so I applied Validator.pattern(/^\S/g) and Validator.pattern(/\S$/g), however for some reason every keystroke changes the validity, it doesn't matter that there are no white spaces, you just enter 'aaaaaaaaaaaa' for example and you will see how for every character entered it goes from valid to invalid and vice-versa.. turns out if I remove the g flag it works fine.. so why is that? am I missing something? check out the stackblitz example

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-ivy-2w3mhe

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.1.0
Node: 10.14.1
OS: win32 x64

Angular: 9.0.1
... animations, cdk-experimental, common, compiler, compiler-cli
... core, forms, language-service, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.0
@angular-devkit/build-angular     0.901.7
@angular-devkit/build-optimizer   0.901.7
@angular-devkit/build-webpack     0.901.7
@angular-devkit/core              9.1.0
@angular-devkit/schematics        9.1.0
@angular/cdk                      9.0.0
@angular/cli                      9.1.0
@ngtools/webpack                  9.1.7
@schematics/angular               9.1.0
@schematics/update                0.901.0
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.42.0

</code></pre>

**Comment by AndrewKushnir** [comment] 2020-06-11 18:55
Hi @bojidaryovchev, thanks for providing a repro.

The problem was caused by the fact that the RegExp with the "g" (global) flag keeps track of the [last matched index](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/lastIndex). Since [the same RegExp instance is being used in the "pattern" validator](https://github.com/angular/angular/blob/master/packages/forms/src/validators.ts#L396) to check the input, this index is shifted and once new character is added, the check starts from the last index. The solution is to avoid using the "g" flag and update the RegExp to something like this:
```
Validators.pattern(/^[\S]+(.*?)[\S]+$/)
```
Since there are no action items for the Framework, I'm closing this ticket.

Thank you.

**Closed by AndrewKushnir** 2020-06-11 18:55 UTC
Labels: comp: forms, forms: validators, type: support

**Comment by gkalpak** [comment] 2020-06-12 13:51
/^[\S]+(.*?)[\S]+$/

/^\S(?:|.*\S)$/

**Comment by gkalpak** [comment] 2020-06-12 13:52
Tiny suggestion:

`/^[\S]+(.*?)[\S]+$/` requires at least two characters to match.
You can use `/^\S(?:|.*\S)$/` instead (or even `/^(?:|\S(?:|.*\S))$/` if you want the empty string to be valid).
