### ISSUE TITLE
Radio button data binding and form validation not working

### ISSUE THREAD

**Issue by manish2aug** [angular/angular#7282] opened 2016-02-25 14:38 UTC
Used [(ngModel)] for two way data binding and [ngFormControl] for control mapping in From builder, error occurs when choosing a radio button. 

HTML as follow
```html
<div class="form-group">
            <label class="col-sm-2 control-label required">Preferred language</label>
            <div class="col-sm-2 radio">
                <label for="idLanguageEnglish" class="radio-inline" style="padding-top: 0px">
                    <input type="radio" id="idLanguageEnglish" #languageEnglish name="preferredLanguage" value="English"
                           class="form-control" (click)="contactDetail.preferredLanguage = languageEnglish.value"
                           [(ngModel)]="contactDetail.preferredLanguage"/>
                    <span class="cr"><i class="cr-icon radio-circle"></i></span>
                    English
                </label>
            </div>
            <div class="col-sm-2 radio">
                <label for="idLanguageAfrikaans" class="radio-inline" style="padding-top: 0px">
                    <input type="radio" id="idLanguageAfrikaans" #languageAfrikaans name="preferredLanguage" value="Afrikaans"
                           class="form-control"
                           (click)="contactDetail.preferredLanguage = languageAfrikaans.value"
                           [(ngModel)]="contactDetail.preferredLanguage"/>
                    <span class="cr"><i class="cr-icon radio-circle"></i></span>
                    Afrikaans
                </label>
            </div>
        </div>
```

Component as follows 
```ts 
  constructor(private formBuilder:FormBuilder) {

        this.prepareDefaultState();

        this.clientContactDetailsForm = formBuilder.group({
            'preferredLanguage': [this._contactDetail.preferredLanguage, Validators.required],
            'workTelephone': [this._contactDetail.workTelephone],
            'homeTelephone': [this._contactDetail.homeTelephone],
            'cellPhone': [this._contactDetail.cellPhone],
            'fax': [this._contactDetail.fax],
            'emailForEmail': [this._contactDetail.email, Validators.compose([Validators.required, ValidationService.email])],
            'emailForPost': [this._contactDetail.email, ValidationService.email],
            'physicalPostalAddressDistinguisher': [this.physicalAndPostalAddressSame],
            'physicalAddressLine1': [this._contactDetail.physicalAddress.line1, Validators.required],
            'physicalAddressLine2': [this._contactDetail.physicalAddress.line2, Validators.required],
            'physicalAddressLine3': [this._contactDetail.physicalAddress.line3],
            'physicalAddressCity': [this._contactDetail.physicalAddress.city, Validators.required],
            'physicalAddressPostalCode': [this._contactDetail.physicalAddress.postalCode, Validators.required],
            'physicalAddressProvience': [this._contactDetail.physicalAddress.provience],
            'physicalCountry': [this._contactDetail.physicalAddress.country, Validators.required],
            'postalAddressLine1': [this._contactDetail.postalAddress.line1],
            'postalAddressLine2': [this._contactDetail.postalAddress.line2],
            'postalAddressLine3': [this._contactDetail.postalAddress.line3],
            'postalAddressCity': [this._contactDetail.postalAddress.city],
            'postalAddressPostalCode': [this._contactDetail.postalAddress.postalCode],
            'postalAddressProvience': [this._contactDetail.postalAddress.provience],
            'postalAddressCountry': [this._contactDetail.postalAddress.country]
        });
    }
```

Error as follows

```
EXCEPTION: Error during evaluation of "change"
angular2.dev.js:23083 EXCEPTION: Error during evaluation of "change"BrowserDomAdapter.logError @ angular2.dev.js:23083BrowserDomAdapter.logGroup @ angular2.dev.js:23094ExceptionHandler.call @ angular2.dev.js:1185(anonymous function) @ angular2.dev.js:12591NgZone._notifyOnError @ angular2.dev.js:13635collection_1.StringMapWrapper.merge.onError @ angular2.dev.js:13539Zone.run @ angular2-polyfills.js:1247(anonymous function) @ angular2.dev.js:13558NgZone.run @ angular2.dev.js:13520outsideHandler @ angular2.dev.js:13355Zone.run @ angular2-polyfills.js:1243zoneBoundFn @ angular2-polyfills.js:1220
angular2.dev.js:23083 ORIGINAL EXCEPTION: TypeError: Cannot read property 'value' of undefinedBrowserDomAdapter.logError @ angular2.dev.js:23083ExceptionHandler.call @ angular2.dev.js:1194(anonymous function) @ angular2.dev.js:12591NgZone._notifyOnError @ angular2.dev.js:13635collection_1.StringMapWrapper.merge.onError @ angular2.dev.js:13539Zone.run @ angular2-polyfills.js:1247(anonymous function) @ angular2.dev.js:13558NgZone.run @ angular2.dev.js:13520outsideHandler @ angular2.dev.js:13355Zone.run @ angular2-polyfills.js:1243zoneBoundFn @ angular2-polyfills.js:1220
angular2.dev.js:23083 ORIGINAL STACKTRACE:BrowserDomAdapter.logError @ angular2.dev.js:23083ExceptionHandler.call @ angular2.dev.js:1197(anonymous function) @ angular2.dev.js:12591NgZone._notifyOnError @ angular2.dev.js:13635collection_1.StringMapWrapper.merge.onError @ angular2.dev.js:13539Zone.run @ angular2-polyfills.js:1247(anonymous function) @ angular2.dev.js:13558NgZone.run @ angular2.dev.js:13520outsideHandler @ angular2.dev.js:13355Zone.run @ angular2-polyfills.js:1243zoneBoundFn @ angular2-polyfills.js:1220
angular2.dev.js:23083 TypeError: Cannot read property 'value' of undefined
    at RadioControlValueAccessor.onChange (angular2.dev.js:16197)
    at AbstractChangeDetector.ChangeDetector_ClientContactDetailsComponent_0.handleEventInternal (viewFactory_ClientContactDetailsComponent:7257)
    at AbstractChangeDetector.handleEvent (angular2.dev.js:8075)
    at AppView.triggerEventHandlers (angular2.dev.js:10856)
    at eval (viewFactory_ClientContactDetailsComponent:9417)
    at angular2.dev.js:14003
    at angular2.dev.js:13356
    at Zone.run (angular2-polyfills.js:1243)
    at Zone.run (angular2.dev.js:13558)
    at NgZone.run (angular2.dev.js:13520)BrowserDomAdapter.logError @ angular2.dev.js:23083ExceptionHandler.call @ angular2.dev.js:1198(anonymous function) @ angular2.dev.js:12591NgZone._notifyOnError @ angular2.dev.js:13635collection_1.StringMapWrapper.merge.onError @ angular2.dev.js:13539Zone.run @ angular2-polyfills.js:1247(anonymous function) @ angular2.dev.js:13558NgZone.run @ angular2.dev.js:13520outsideHandler @ angular2.dev.js:13355Zone.run @ angular2-polyfills.js:1243zoneBoundFn @ angular2-polyfills.js:1220
angular2.dev.js:23083 ERROR CONTEXT:BrowserDomAdapter.logError @ angular2.dev.js:23083ExceptionHandler.call @ angular2.dev.js:1201(anonymous function) @ angular2.dev.js:12591NgZone._notifyOnError @ angular2.dev.js:13635collection_1.StringMapWrapper.merge.onError @ angular2.dev.js:13539Zone.run @ angular2-polyfills.js:1247(anonymous function) @ angular2.dev.js:13558NgZone.run @ angular2.dev.js:13520outsideHandler @ angular2.dev.js:13355Zone.run @ angular2-polyfills.js:1243zoneBoundFn @ angular2-polyfills.js:1220
```

In this case there is no default value of radio button and this is a mandatory input, so I had to use required validator (as 'preferredLanguage': [this._contactDetail.preferredLanguage, Validators.required]) and simply handle click event and manually set model (for example (click)="contactDetail.preferredLanguage = languageAfrikaans.value") then form becomes InValid. 

So Data binding and validation both are not working``

**Comment by zoechi** [comment] 2016-02-25 20:18
Wow that's quite an unreadable mess. Can you please modify your post and wrap code in triple backticks ``` . A Plunker would be nice as well to get a proper repo case.

**Comment by PascalPrecht** [comment] 2016-02-26 20:38
Hey @manish2aug just to double check: I can't see an `[ngFormModel]` being bound to a `<form>` element in your code. Did you just not include it in the snippet, or is it really not there?

Also could you elaborate a little bit on *when* this error occours? As in, what actions are required? From your description I can't really see if this is how to reproduce it or how to work around it.

**Comment by manish2aug** [comment] 2016-02-29 14:21
Sorry for the mess, here is the plunkr link https://plnkr.co/edit/o0Etl6XVnCKxIa4CA4Gs?p=info

**Comment by PascalPrecht** [comment] 2016-03-04 14:44
Hi @manish2aug,

no worries it's not a mess. You've cleaned it up :)

I took a look at your plunk and tried other variations with `ngControl` too. This is a bug.

**Comment by davidrensh** [comment] 2016-03-07 21:33
Hi, I have similar issue, is this the correct way to bind radio on AG2?

**Comment by rbriank** [comment] 2016-03-08 19:52
As a workaround I was able to get mine this way:

<input type="radio" [ngFormControl]="itemtype" (click)="itemtype='0'" value="0">Singl2<br/>
....

**Comment by davidrensh** [comment] 2016-03-08 22:27
Perfect to remove error as your suggestion.
The only issue is very hard to set the checked status back to proper checked radio control based on [(ngModel)] value. I tried many ways: renderer.setElementAttribute, elementRef

Beta 8 should be fine with [(ngModel)] 2-way binding. Confused.
>         <div [hidden]="false" >
>           <input [(ngModel)]="itemtype" >Hide ngModel
>         </div>
>         <form>
>             <input type="radio" name="it"  [ngFormControl]="itemtypec" (click)="itemtype='0'" value="0">Single<br>
>             <input type="radio" name="it"  [ngFormControl]="itemtypec" (click)="itemtype='1'" value="1">Multiple<br>
>             <input type="radio" name="it"  [ngFormControl]="itemtypec" (click)="itemtype='2'" value="2">Text<br>
>         </form>

**Comment by davidrensh** [comment] 2016-03-09 00:06
I know this is the stupidest way. But this is the only working solution for radio 2 way binding.
Thx Brian!
Please let me know if there is any better solution for beta8.

>         <form>
> 		    <span class="radio">Form Detail info for {{myformname}}<br>
>             <input  [(ngModel)]="num" placeholder="Eneter item number"><br>
>             <input  [(ngModel)]="des" placeholder="Eneter item description"><br>
>             <input  [(ngModel)]="itype" placeholder="type value"><br>
> 
>             <input *ngIf="itype !== 0" type="radio" name="it"  [ngFormControl]="itemtypec" (click)="selectRadio(0)" value="0" >
>             <input *ngIf="itype === 0" type="radio" name="it"  [ngFormControl]="itemtypec" (click)="selectRadio(0)" value="0" checked>Single<br>
> 
>             <input *ngIf="itype !== 1" type="radio" name="it"  [ngFormControl]="itemtypec" (click)="selectRadio(1)" value="1" >
>             <input *ngIf="itype === 1" type="radio" name="it"  [ngFormControl]="itemtypec" (click)="selectRadio(1)" value="1"  checked>Multiple<br>
> 
>             <input *ngIf="itype !== 2" type="radio" name="it"  [ngFormControl]="itemtypec" (click)="selectRadio(2)" value="2" >
>             <input *ngIf="itype === 2" type="radio" name="it"  [ngFormControl]="itemtypec" (click)="selectRadio(2)" value="2"  checked>Text<br>
> 
>             <span></span>
>             <button class="twitter" (click)="saveFormDetail()">Save</button>
>             </span><br>  
>             <ul>
>                 <li *ngFor="#fd of itemList | async" >
>                     <input type="radio" name= "xform2" value= "{{fd.num}}" (click)="selectItem(myformname,fd.num,fd.des,fd.itemtype)" > {{fd.num}}. &nbsp; {{fd.des}}
>                 </li>
>             </ul>	  
>         </form>

>     selectRadio(itemtype: number) {
>         this.itype = itemtype;
> 
>         console.log("gg 12222:" + itemtype);
>     }
>     selectItem(name: string, num: number,des:string , tp:number) {
>         this.num = num;
>         this.des = des;
>         this.itype = tp;
> 
>         console.log("itemtype 8:" + tp);
>         this.itemChanged.emit([name, num]);
>     }
>     saveFormDetail() {
>         var usersRef = this.messagesRef.child(this.myformname).child("items").child(this.num.toString());
>         console.log("itemtype=" + this.itype + " num=" + this.num + " des = " + this.des);
>         usersRef.set({
>             num: this.num,
>             des: this.des,
>             itemtype: this.itype
>         });
> 
>     }

**Comment by mrMoe** [comment] 2016-03-13 22:34
Confirming the input radio bug is still existing in angular2 2.0.0-beta.9.

**Comment by Paladinium** [comment] 2016-03-25 11:10
I totally agree that radio buttons should work with ngModel. But I would like to see radio buttons work with ngFormControl and ngFormModel without necessarily requiring ngModel. For example:

Controller:
```
form: ControlGroup;
constructor (fb: FormBuilder) {
        this.form = fb.group({
            'myRadio': ['valueA'] // or new RadioButtonState('valueA')
        });
}

onSubmit () {
     var radioValue = this.form.value.myRadio.selectedValue; // either 'valueA' or 'valueB'
}
```

and in the template:

```
<input [ngFormControl]="form.controls['myRadio']" type="radio" name="someName" value="valueA">
<input [ngFormControl]="form.controls['myRadio']" type="radio" name="someName" value="valueB">
```

The radio buttons belonging together have the same 'name', just like in normal HTML forms (there is another issue regarding that: #7051)

Any opinions about that?

**Comment by kenkopelson** [comment] 2016-05-22 18:46
Hi guys :)  Has anyone done anything to get radio buttons working?  This really is quite important, since radio buttons are a key part of any user interface screen.  Please make sure this gets fixed, and that radio buttons work  as expected.  Working with [(ngModel)] is mandatory since many use-cases involve binding a form to existing data inside of data objects from the backend.  Having them work with the ngFormControl is also required from a consistency point of view.  So basically, they should work just like all the other form controls, supporting both.  Also, keep in mind that the name of the radio controls is used to group them together, so all the radio buttons with the same name should all share the same [(ngModel)] or ngFormControl, and the "value" field of the control is what gets set into the control when selected.

From this user's perspective, this really is the biggest glaring bug in the rc1 release.  This is a major breakage, and doing work-arounds is not really desired when building green-field applications with a brand new well-designed framework.  Please raise this issue to the top and get it fixed. Many thanks!

**Comment by kara** [comment] 2016-06-28 22:26
Thanks for the report! Radio buttons have been revamped in the new forms module (RC.2 and onward). See new usage here: https://github.com/angular/angular/pull/9228.  Closing, as the issues have been addressed. Please feel free to re-open if you see problems with the new module.

**Closed by kara** 2016-06-28 22:26 UTC
