### ISSUE TITLE
ng build --prod --aot file sizes WAY too big

### ISSUE THREAD

**Issue by lansana** [angular/angular#16850] opened 2017-05-17 17:14 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report (already looked at similar issues, the --aot and --prod commands seem to not do anything here)
```

**Current behavior**
When building the app for production using `ng build --prod --aot`, the vendor comes out to be 2.42MB, which is just way too large. I assume it's including every file in node_modules?

**Expected behavior**
I expected it to shrink down the vendor to only things that are used, such that is is around 100-200kb as I've seen in other similar issues.

**Minimal reproduction of the problem with instructions**
`ng build --prod --aot`

**What is the motivation / use case for changing the behavior?**
I want to build files for production.

**Please tell us about your environment:**
Mac OS, JetBrains WebStorm, Golang for HTTP server, NPM package manager.

* **Angular version:** 
4.1.1
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript

* **Node (for AoT issues):** 
7.5.0

This is what the command output looks like:
```bash
$ ng build --prod --aot
Hash: d0b07a3ae728049f5231                                                               
Time: 59164ms
chunk    {0} 0.b09f645f6ae94cf1a08e.chunk.js 153 kB {1} {2} {3} {4} {5} {6} {7} {8} {9} {10} {12} [rendered]
chunk    {1} 1.59e7c2524ba944dc24b7.chunk.js 147 kB {0} {2} {3} {4} {5} {6} {7} {8} {9} {10} {12} [rendered]
chunk    {2} 2.f5d4c655a1f681810488.chunk.js 141 kB {0} {1} {3} {4} {5} {6} {7} {8} {9} {10} {12} [rendered]
chunk    {3} 3.94a30ed4e8372ac659e5.chunk.js 114 kB {0} {1} {2} {4} {5} {6} {7} {8} {9} {10} {12} [rendered]
chunk    {4} 4.52b826197326ccb23de1.chunk.js 162 kB {0} {1} {2} {3} {5} {6} {7} {8} {9} {10} {12} [rendered]
chunk    {5} 5.2c0893db74e366daac3e.chunk.js 150 kB {0} {1} {2} {3} {4} {6} {7} {8} {9} {10} {12} [rendered]
chunk    {6} 6.32bbdc373570e63034bc.chunk.js 129 kB {0} {1} {2} {3} {4} {5} {7} {8} {9} {10} {12} [rendered]
chunk    {7} 7.02eeb0a8321a1b8fac31.chunk.js 106 kB {0} {1} {2} {3} {4} {5} {6} {8} {9} {10} {12} [rendered]
chunk    {8} 8.9977b38e6394de667c07.chunk.js 84.6 kB {0} {1} {2} {3} {4} {5} {6} {7} {9} {10} {12} [rendered]
chunk    {9} 9.673cd663e6a2e30b5a83.chunk.js 77.5 kB {0} {1} {2} {3} {4} {5} {6} {7} {8} {10} {12} [rendered]
chunk   {10} 10.6207dda91b0683debb1c.chunk.js 75.7 kB {0} {1} {2} {3} {4} {5} {6} {7} {8} {9} {12} [rendered]
chunk   {11} polyfills.b3a048b94439c4525381.bundle.js (polyfills) 157 kB {16} [initial] [rendered]
chunk   {12} main.9aff36e0339c45d20486.bundle.js (main) 159 kB {15} [initial] [rendered]
chunk   {13} scripts.536b7ae3472538919b8e.bundle.js (scripts) 128 kB {16} [initial] [rendered]
chunk   {14} styles.05882976bd5a722e5e4a.bundle.css (styles) 122 bytes {16} [initial] [rendered]
chunk   {15} vendor.dc1eaf2660844251576c.bundle.js (vendor) 2.42 MB [initial] [rendered]
chunk   {16} inline.68fad1432c4719c51fe8.bundle.js (inline) 0 bytes [entry] [rendered]
```

**Comment by HoumanKml** [comment] 2017-05-17 22:11
If you are using angular-cli to build your app, I believe it has gzip compression turned off by default; you'll need to compress your app while serving it on the server. Try to compress your dist folder yourself and see if its size decreases or not.

**Comment by dottodot** [comment] 2017-05-18 14:44
I'm have the same issues, I can't get a vendor bundle under 1MB (before gzip) which seems pretty big, especially when I compare to previous backbone projects where the vendor bundle size is 200kb. 

I just can't work out if it's "normal" or if something isn't right but when using Webpack Bundle Analyzer it shows that it's mostly `@angular` followed by `rxjs` so it's not as if I added a load of packages that have made it so big.

**Comment by HoumanKml** [comment] 2017-05-18 15:05
@dottodot Are you adding the whole rxjs module or just the components you need? Generally speaking though, [Angular is a heavy weight compared to, say, Vue or React](https://gist.github.com/Restuta/cda69e50a853aa64912d).

There are some steps you can take to reduce the bundle size: use lazy-loading, use cdn for styles and such. However, the solution to radically increase the start up time is to use server side rendering for the initial landing page. Take a look at [Angular Universal](https://github.com/angular/universal). The counterparts to Universal in React and Vue world would be Next and Nuxt, in case you have heard of those (though each have different features, but all are based on server-side rendering.)

**Comment by dottodot** [comment] 2017-05-18 15:25
Yes i'm only import the components I need from rxjs and also already using lazy-loading.

Not got round to trying universal, I was holding off in the hope it might be added to cli at some point and still have a lot to learn getting the basics sorted.

**Comment by HoumanKml** [comment] 2017-05-18 15:35
@dottodot Unfortunately it seems we can't do much to reduce the size any further. I have the same issue, but it seems reducing the size and improving the speed are one of the main goals of angular 5; apparently right now the tree shaking does not really remove all the unnecessary parts  ([watch here](https://youtu.be/anzsE2TbCyk?t=40m15s))

**Comment by kemsky** [comment] 2017-05-18 18:56
Could you post your vendor file?

**Comment by sod** [comment] 2017-05-19 14:10
Just a wild guess, have you something like
```typescript
import 'rxjs';
import '@angular/common';
// ...
```

in your code? When yes, this makes tree shaking impossible as you explicitly tell webpack to include everything.

If you only import on demand like
```typescript
import {Component} from '@angular/core';
import {Observable} from 'rxjs/Observable';
// ...
```

Then webpack can throw away everything else for you.

**Comment by lansana** [comment] 2017-05-19 14:13
I do something more along the lines of this:

import { Observable } from 'rxjs';
import 'rxjs/add/operator/publishReplay';
import 'rxjs/add/operator/map';

**Comment by lansana** [comment] 2017-05-19 14:13
I do something more along the lines of this:

```ts
import { Observable } from 'rxjs';
import 'rxjs/add/operator/publishReplay';
import 'rxjs/add/operator/map';
```

**Comment by tytskyi** [comment] 2017-05-19 14:20
Could you try: 

```
import { Observable }  from 'rxjs/Observable';
```

**Comment by sod** [comment] 2017-05-19 14:32
If you use typescript, you can create a rxjs.ts in your project, point to it in your tsconfig.json like:
```json
{
    "compilerOptions": {
        "paths": {
            "rxjs": ["./application/vendor/rxjs.ts"]
        },
    }
}
```

and your rxjs.ts looks like
```typescript
export {Subject, AnonymousSubject} from 'rxjs/Subject';
export {Observable} from 'rxjs/Observable';
export {Subscription} from 'rxjs/Subscription';
export {Subscriber} from 'rxjs/Subscriber';
export {ReplaySubject} from 'rxjs/ReplaySubject';
export {Observer} from 'rxjs/Observer';
export {Operator} from 'rxjs/Operator';
```

So your `import {Observable} from 'rxjs'` will use your custom rxjs build instead off the full thing (https://github.com/ReactiveX/rxjs/blob/master/src/Rx.ts)

This should shave off 300 kb from your build. There must be something else wrong if your vendor file is 2.42 MB in size.

**Comment by sod** [comment] 2017-05-19 14:37
I don't know anything about `ng` angular-cli, but if you have access to the webpack config or can add another plugin, you can add https://github.com/th0r/webpack-bundle-analyzer and build again. Gives pretty nice overview in your browser of what your build files contain.

**Comment by kylecordes** [comment] 2017-05-30 15:36
This may seem crazily out of scope, but could `ngc` (and the code underneath it, which gets run by CLI via the webpack plug-in) detect various common anti-patterns like `import {Observable} from 'rxjs'` and emit a warning? It seems that this could help every user of Angular, whereas documentation in the issue tracker only helps the subset who recognize they are getting an unnecessarily large bundle and make their way here to investigate why.

**Comment by johnrivelt** [comment] 2017-07-25 03:54
In my case, 
I thought chunk size as dist file size first, but in dist folder, vendor file size was okay.

>ng build --prod --aot
...
chunk    {0} polyfills.106c1049bbf8c119e10f.bundle.js (polyfills) 160 kB {4} [initial] [rendered]
chunk    {1} main.c909f26ad2950ab65b78.bundle.js (main) 60.2 kB {3} [initial] [rendered]
chunk    {2} styles.532043307593380cd798.bundle.css (styles) 69 bytes {4} [initial] [rendered]
chunk    {3} **vendor.0bd52d751a8cb202da45.bundle.js (vendor) 1.5 MB** [initial] [rendered]
chunk    {4} inline.091712b113b6d17d7f4d.bundle.js (inline) 0 bytes [entry] [rendered]

in folder /dist
inline.091712b113b6d17d7f4d.bundle.js 2KB
main.c909f26ad2950ab65b78.bundle.js 24KB
polyfills.106c1049bbf8c119e10f.bundle.js 59KB
styles.532043307593380cd798.bundle.css 1KB
**vendor.0bd52d751a8cb202da45.bundle.js 419KB**

**Comment by lansana** [comment] 2017-07-25 19:12
I don't understand how your vendor file size is only 419kb, mine is so massive, all my imports are accurate. I need to really dig deep and find out what's going on when I get home... still around 1.5-2mb even with `ng build -prod -aot`.

**Comment by johnrivelt** [comment] 2017-07-26 00:37
@lansana I just followed [angular 4.3.1 tutorial](https://angular.io/tutorial) and it looks okay.
Can you git clone the tutorial, bulid and check the file size is right ?

If this looks right, your code or configuration caused your issuse.
In that case, you would be better create [plunkr](https://plnkr.co/) to test your code, it would be good for someone to look into further.

**Comment by msc117** [comment] 2017-07-30 02:51
The servers my Angular + Angular material is served from doesn't support GZIP and doesn't change the fact that the browser is still parsing multiple MBs of JS. This is my build 

```
              mat-themes/purple-green.css    33.7 kB          [emitted]         
          0.74621ab2dd5d5fd44177.chunk.js    3.68 kB       0  [emitted]         
          2.79d102da9aafab1b7dcc.chunk.js    19.5 kB       2  [emitted]         
          3.79552a782dfbeabbf66a.chunk.js     120 kB       3  [emitted]         
          4.698a5868c999b8e4ddcd.chunk.js    3.96 kB       4  [emitted]         
          5.1019965f7b36cce51954.chunk.js    32.6 kB       5  [emitted]         
          6.dd76a76160de9f565dc8.chunk.js    30.5 kB       6  [emitted]         
    vendor.b0b5b31af7e3a59639d0.bundle.js    1.15 MB       7  [emitted]  [big]  vendor
      main.92f392b1caa4356f3514.bundle.js     822 kB       8  [emitted]  [big]  main
          9.7b6b8cb745bb1a66e192.chunk.js    24.6 kB       9  [emitted]         
         10.4aa4509d43e6bd2a9311.chunk.js    3.74 kB      10  [emitted]         
         11.5c6f2289f88fad994d6e.chunk.js    3.71 kB      11  [emitted]         
  polyfill.a9d42e2b4181e3f4fc9a.bundle.js     159 kB      12  [emitted]         polyfill
main.f838569151723fcb8228a98d592869d0.css    7.74 kB       8  [emitted]         main
     main.92f392b1caa4356f3514.bundle.map  118 bytes       8  [emitted]         main
                               index.html  878 bytes          [emitted]         
               mat-themes/indigo-pink.css    33.5 kB          [emitted]         
             mat-themes/pink-bluegrey.css    33.7 kB          [emitted]         
          1.9a7ec4529784045f9622.chunk.js    3.87 kB       1  [emitted]         
          mat-themes/deeppurple-amber.css    33.6 kB          [emitted]         
```

How is there 1.15MB of fully compressed vender files being loaded? It just doesn't seem right.

**Comment by HunderlineK** [comment] 2017-07-30 03:59
@msc117 The vendor bundle is probably not compressed; just try zipping it in your OS and see if the file size doesn't reduce to ~1/5th of its original size. If your server does not support gzip natively, you can configure your server to dynamically compress the files by using a compression middle-ware, e.g. [express-compression](https://github.com/expressjs/compression) if you are using node

**Comment by msc117** [comment] 2017-07-30 04:17
That is fully optimized. As I said, the servers I'm using do not support gzip and it shouldn't be expected to use gzip in order to get a realistic file size.

**Comment by HunderlineK** [comment] 2017-07-30 07:40
@msc117 
- " it shouldn't be expected to use gzip in order to get a realistic file size." 
If being lightweight is crucial to your project, you should try out a view library like React or VueJs until angular properly supports server-side rendering and platform-server is documented. Since angular is a complete framework, its large size is expected and getting the served files to less than 100kb even with compression is not possible in production  [I've read some people experimenting with the closure compiler getting builds ~50kb in size]

- " As I said, the servers I'm using do not support gzip" 
. The express compression middle-ware does the compression on the fly as a client requests the resources and does not need the server to support  gzip files, meaning that the files you'll be uploading to your server are going to be the original files built using ng build command as-is, without being compressed.

**Comment by mlc-mlapis** [comment] 2017-07-30 08:57
@msc117 ... just a question of curiosity ... what server type you use? I don't know any which doesn't support gzip compression of some type.

**Comment by msc117** [comment] 2017-07-31 02:17
@HunderlineK It's a little too late for that now... I think it's just pretty misleading to advertise a 57KB "hello world" app where a real use case app can easily get in the MBs. It's more of an issue on my end of not realizing this, but I think this needs to be more well known to potential Angular developers.

@mlc-mlapis The server the static files will be sent from are serving multiple projects at a large company where modifying server software and settings is not a simple task. It's Tomcat 6.

**Comment by HunderlineK** [comment] 2017-07-31 15:13
@msc117  I don't recall the official documents advertising a size of 57KB. Nevertheless, I still believe you should be able to serve your files in gzip format to the client.

For Angular to work on your server, whatever the architecture, it should support Node.js development environment and if it does support Node.js, you can simply build your Angular project on top of an express project with the compression middleware.

**Comment by erlloyd** [comment] 2017-07-31 22:12
Also want to chime in and remind that, like @johnrivelt mentioned, the chunk size reported by the cli is *not* the same as the file size on disk. I have:

```
Hash: 29415c3b72d3ad1a609f
Time: 58220ms
chunk    {0} main.028b98df52e879ae2c5c.bundle.js (main) 2.17 MB {3} [initial] [rendered]
chunk    {1} polyfills.1123973fb77a2ad92013.bundle.js (polyfills) 160 kB {4} [initial] [rendered]
chunk    {2} styles.d2cf5e4e06a948654619.bundle.css (styles) 69 bytes {4} [initial] [rendered]
chunk    {3} vendor.d9149b09affa0e702618.bundle.js (vendor) 1.96 MB [initial] [rendered]
chunk    {4} inline.43670416a0c2ec9e3e56.bundle.js (inline) 0 bytes [entry] [rendered]
```

But on disk:
```
root@29d6916a5069:/app/dist# ls -al | grep .js
-rw-r--r--  1 root root    1460 Jul 31 21:40 inline.43670416a0c2ec9e3e56.bundle.js
-rw-r--r--  1 root root 1281005 Jul 31 21:40 main.028b98df52e879ae2c5c.bundle.js
-rw-r--r--  1 root root   59621 Jul 31 21:40 polyfills.1123973fb77a2ad92013.bundle.js
-rw-r--r--  1 root root  590344 Jul 31 21:40 vendor.d9149b09affa0e702618.bundle.js
```

So 590K vs 1.96M reported. Not sure why the reporting is different.

**Comment by lansana** [comment] 2017-08-01 12:02
@erlloyd Makes a very good point! I am the OP, and I just tested this myself. 

This is the result of `ng build -prod -aot`:

```
chunk   {26} main.78d1a2781cc2d3698d14.bundle.js (main) 1.06 MB {30} [initial] [rendered]
chunk   {27} polyfills.e744eb77c66538be6d7c.bundle.js (polyfills) 160 kB {31} [initial] [rendered]
chunk   {28} scripts.a93f556e3ca69ad34d3f.bundle.js (scripts) 349 kB {31} [initial] [rendered]
chunk   {29} styles.f7b6b138795a6f56bb59.bundle.css (styles) 69 bytes {31} [initial] [rendered]
chunk   {30} vendor.9a2628ae40de7c6fb14d.bundle.js (vendor) 2.03 MB [initial] [rendered]
chunk   {31} inline.a3483f40d08246fb4888.bundle.js (inline) 0 bytes [entry] [rendered]
```

This is the result of `ng build -prod -aot` using `ls -larth` to get file details:

```
685K Aug  1 07:56 vendor.9a2628ae40de7c6fb14d.bundle.js
136K Aug  1 07:56 styles.f7b6b138795a6f56bb59.bundle.css
335K Aug  1 07:56 scripts.a93f556e3ca69ad34d3f.bundle.js
60K Aug  1 07:56 polyfills.e744eb77c66538be6d7c.bundle.js
402K Aug  1 07:56 main.78d1a2781cc2d3698d14.bundle.js
2.1K Aug  1 07:56 inline.a3483f40d08246fb4888.bundle.js
```

As you can see, the file sizes are MUCH more reasonable. False advertising!! 

I think there is a bug in the way the output is being printed to std out when running `ng serve` or `ng build`. Should I open another issue for this?

**Comment by tavy87** [comment] 2017-08-07 19:39
I'm seeing this large file sizing as well when running ng serve.

**Comment by ptrzyna** [comment] 2017-11-05 20:26
Angular 5 seems to produce huge vendor bundle sizes. I'm seeing 13MB

**Comment by Toxicable** [comment] 2017-11-05 20:43
Running any command without `--prod` it is expected and normal and totally fine to see large files

**Comment by trotyl** [comment] 2017-11-06 01:04
@ptrzyna Actually Angular 5 will use `—build-optimizer` with `—vendor-chunk=false` by default in production builds, so there won't be a vendor bundle.

**Comment by alfredobialo** [comment] 2017-11-06 05:16
Try ng build  -- prod, without aot

**Comment by trotyl** [comment] 2017-11-06 05:44
@alfredobialo `ng build -prod -aot` is same to `ng build -prod`, `-aot` won't have any effect here, 
 it's useless but not the argue point in this thread.

**Comment by sandangel** [comment] 2017-11-06 06:39
![image](https://user-images.githubusercontent.com/22189661/32428313-7553080c-c308-11e7-9056-b64a2a6f98cc.png)

I don't know why, 2m to build and 2mb for main. Angular 5

**Comment by dottodot** [comment] 2017-11-06 08:27
Best I've managed in a real world app is a 1.1Mb main bundle. Also seeing a pretty low performance score using lighthouse which definitely isn't helped by this.

**Comment by anjmao** [comment] 2017-11-22 10:54
In angular cli 1.5.3 bundling new empty app using `ng build prod` I'm getting these results
``
chunk {0} polyfills.ad37cd45a71cb38eee76.bundle.js (polyfills) 61 kB [initial] [rendered]
chunk {1} main.bc97ddaa99d95dbcd66e.bundle.js (main) 151 kB [initial] [rendered]
chunk {2} styles.d41d8cd98f00b204e980.bundle.css (styles) 0 bytes [initial] [rendered]
chunk {3} inline.3c299e275eecb0e438e9.bundle.js (inline) 1.45 kB [entry] [rendered]
```

Main bundle size is only 151kb raw and only 42kb in gzip. It's a huge improvement, bravo angular-cli team :))))

**Comment by aitboudad** [comment] 2017-11-22 11:33
angular team have done a lot of work on this but I think still have a lot of things to improve,
in a real world app which use router, forms and material2 I would say that it's hard to make the main bundle smaller, angular deps itself take 50% of the size:

|                 -          |   -    |
| ------------------------- | ----- |
| @angular/core             | 100kb |
| @angular/router           |  65kb |
| @angular/animations       |  65kb |
| @angular/forms            |  43kb |
| @angular/common           |  42kb |
| @angular/platform-browser |  42kb |
| rxjs                      |  50kb |
| zone.js                   |  39kb |
| | **456kb**

adding polyfills + third part bundle + app code will result an average of `800kb -> 1MB`

\cc @IgorMinar

**Comment by IgorMinar** [comment] 2017-11-22 16:48
@aitboudad how were these numbers collected? Was the latest version of cli used? Were the numbers extracted from source maps?

**Comment by aitboudad** [comment] 2017-11-22 16:53
@IgorMinar yep, extracted from source maps (`source-map-explorer`) and the latest version of cli (`1.5.2`)
```ts
ng build --prod --sm
```

**Comment by sarunint** [comment] 2017-11-22 17:03
I think the numbers from the source map is misleading. It's *pre-uglify* size.

**Comment by dottodot** [comment] 2017-11-22 17:05
I get pretty similar results to @aitboudad using webpack-bundle-analyzer after running `ng build -prod -aot --buildOptimizer --statsJson`

**Comment by aitboudad** [comment] 2017-11-22 17:09
@sarunint I'm talking about minified version (post-uglify + no-gzip), gzip is effective way to save bandwidth but not for memory/parsing.

**Comment by arsyed04** [comment] 2017-12-14 09:35
@sandangel which tool did you use to get a visual tree size?

**Comment by bhagatparwinder** [comment] 2017-12-27 21:16
Same issue here. I am seriously disappointed by the file sizes. I tried a few things to see if they would reduce it. They do, but it is still not acceptable.

![image](https://user-images.githubusercontent.com/6809087/34393506-8c4a3ac0-eb18-11e7-8283-08995c9b4291.png)

It's anywhere from **6-10MB for production build**

Here is my package.json if that helps!

```
"dependencies": {
    "@angular/animations": "^5.1.2",
    "@angular/cdk": "^5.0.2",
    "@angular/common": "^5.0.0",
    "@angular/compiler": "^5.0.0",
    "@angular/core": "^5.0.0",
    "@angular/forms": "^5.0.0",
    "@angular/http": "^5.0.0",
    "@angular/material": "^5.0.2",
    "@angular/platform-browser": "^5.0.0",
    "@angular/platform-browser-dynamic": "^5.0.0",
    "@angular/router": "^5.0.0",
    "core-js": "^2.4.1",
    "rxjs": "^5.5.2",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "@angular/cli": "1.6.2",
    "@angular/compiler-cli": "^5.0.0",
    "@angular/language-service": "^5.0.0",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "^4.0.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.2.0",
    "tslint": "~5.7.0",
    "typescript": "~2.4.2"
  }
```

**Comment by MattiJarvinen-BA** [comment] 2017-12-28 00:04
@bhagatparwinder with current tree shake it's most likely that your rxjs or angular material imports in rs files are to blame. Also you could check that typescript version against latest angular cli new project.

**Comment by dottodot** [comment] 2017-12-28 11:19
Something else I'm see when using `webpack-bundle-analyzer` is a main.ts of around 200kb and `webpack-bundle-analyzer` just reports it as main.ts + 53 modules, but I can't drill down into it to see what it comprises of.

**Comment by IgorMinar** [comment] 2018-01-03 00:19
@dottodot you can't drill down into the module because the modules have been concatenated by Webpack's ModuleConcatenationPlugin.

@bhagatparwinder it's hard to tell why your prod bundle is 6-10MB. that's definitely not normal. most of the optimizations are on by default in the latest cli release so please make sure you are using the latest and you build using `ng build --prod`.

If the issue persists then please provide a minimal reproduction in a form of a git repo we can clone and inspect.

Currently our baseline is 214KB for a stock hello world app produced by cli. This is without forms, router and material. You can track the progress here: https://angular-payload-size.firebaseapp.com/cli-hello-world/master

We are working on further improving the sizes. I filed #21268, #21269, #21270, #21271 so that we start tracking the size for apps that use all of the common combination of our libraries.

**Comment by paulotokimatu** [comment] 2018-01-04 16:20
@bhagatparwinder 
Try running `ng build --target=production --environment=prod` The bundle size should be much smaller.

Also, just in case you may not know, be careful with RxJS imports, and if you are using HttpClient, you don't need to install @angular/http anymore. You can user [source-map-explorer](https://www.npmjs.com/package/source-map-explorer) of your build to check what else is responsible for the large size.

**Comment by IgorMinar** [comment] 2018-01-16 23:33
I'm going to close this issue as it's too generic and not actionable.

we are continuously working on reducing the size. If there are concrete size regressions or you found a particular issue that if fixed will result in size decrease, please file a new issue.

**Closed by IgorMinar** 2018-01-16 23:33 UTC
Labels: comp: packaging

**Comment by renilbabu03** [comment] 2018-03-07 04:59
The following solution assumes you are serving your dist/ folder using nodejs. Please use the following app.js in root level


    const express = require('express'),http = require('http'),path = require('path'),compression = require('compression');
    
    const app = express();
    
    app.use(express.static(path.join(__dirname, 'dist')));
    app.use(compression()) //compressing dist folder 
    app.get('*', (req, res) => {
      res.sendFile(path.join(__dirname, 'dist/index.html'));
    })
    
    const port = process.env.PORT || '4201';
    app.set('port', port);
    
    const server = http.createServer(app);
    server.listen(port, () => console.log('Running at port ' + port))

Make sure you install dependencies;

    npm install compression --save
    npm install express --save;

Now build the app

    ng build --prod --build-optimizer


> If you want to further compress the build say reduce 300kb(approx)
> from , then follow the below process;

Create a folder called **`vendor`** inside the **`src`** folder and inside vendor folder create a file **`rxjs.ts`**  and paste the below code in it;


    export {Subject} from 'rxjs/Subject';
    export {Observable} from 'rxjs/Observable';
    export {Subscription} from 'rxjs/Subscription';

And then add the follwing in the **`tsconfig.json`** file in your angular-cli application;

    "paths": {
          "rxjs": [
            "./vendor/rxjs.ts"
          ]
        }

 
This will make your build size way too smaller. In my project I reduced the size from 11mb to 1mb.
Hope it helps

**Comment by MA-Maddin** [comment] 2018-04-01 23:19
Just a note to all that tell us to do stuff like `ng build --target=production --environment=prod --aot --build-optimizer`, etc.:

> Both `--dev`/`--target=development` and `--prod`/`--target=production` are 'meta' flags, that set other flags. If you do not specify either you will get the --dev defaults.
> 
> Flag | --dev | --prod
> -- | -- | --
> --aot | false | true
> --environment | dev | prod
> --output-hashing | media | all
> --sourcemaps | true | false
> --extract-css | false | true
> --named-chunks | true | false
> --build-optimizer | false | true with AOT and Angular 5
> 


https://github.com/angular/angular-cli/wiki/build#--dev-vs---prod-builds

**Comment by gustavogsimas** [comment] 2018-04-09 20:44
@renilbabu03 I'm kinda lost here, how do you exactly do the app.js part?

**Comment by aboobacker5577** [comment] 2019-03-07 12:05
Date: 2019-03-07T12:03:46.871Z
Hash: cd9da120a6b2bbf89b25
Time: 42072ms
chunk {0} runtime.b57bf819d5bdce77f1c7.js (runtime) 1.41 kB [entry] [rendered]
chunk {1} es2015-polyfills.0d4f876df327d0111ca2.js (es2015-polyfills) 56.4 kB [initial] [rendered]
chunk {2} main.fc28e2d023fd5b8de026.js (main) 3.11 MB [initial] [rendered]
chunk {3} polyfills.f1a86b50434b1a515c5a.js (polyfills) 41 kB [initial] [rendered]
chunk {4} styles.cc62f00b7e7a53f33bf6.css (styles) 65.4 kB [initial] [rendered]
  

in my case  main.fc28e2d023fd5b8de026.js (main) 3.11 MB how to solve this issue 
i used command
ng build --prod --build-optimizer

i am facing loading tooo time for loading Please Help

**Comment by unosbaghaie** [comment] 2019-04-18 08:14
How To Keep Angular Deployment Size Small :

Take a look at the structure of my [project ](https://github.com/younos1986/HowToKeepAngularDeploymentSizeSmall).

Home page size is 922kb . [demo](https://younos1986.github.io/)

**Comment by trotyl** [comment] 2019-04-18 08:29
> Home page size is 922kb . [demo](https://younos1986.github.io/)

@unosbaghaie Have you really checked the demo you provided?

![image](https://user-images.githubusercontent.com/6059170/56347419-d1219980-61f6-11e9-8b84-de88ffe4c0eb.png)

Or are you blaming Angular for the picture size in your app?

**Comment by kemsky** [comment] 2019-04-29 09:27
@trotyl this size is after GZip, if you open in Firefox you'll see original size.

**Comment by trotyl** [comment] 2019-04-29 10:31
@kemsky Yep, and the size after gzip (min+gzip) is what being transferred thus the only thing relevant in computing the loading time, which is the de-facto conventional measurement across libraries:

+ https://preactjs.com/
+ https://vuejs.org/v2/guide/installation.html

**Comment by kemsky** [comment] 2019-04-29 10:54
@trotyl, it might be somewhat standard measurement for desktops, but if you consider mobile devices/slower devices, parsing 1mb of (ungzipped) js takes noticeable time, that is why I do not support gzipped size comparisons.

**Comment by trotyl** [comment] 2019-04-29 11:39
> but if you consider mobile devices/slower devices, parsing 1mb of (ungzipped) js takes noticeable time, that is why I do not support gzipped size comparisons

@kemsky That's reasonable, as long as the baseline is correct, for example:

+ jquery.min.js: 88.2 kB
+ bootstrap.min.js: 58.1 kB
+ lodash.min.js: 73.2 kB
+ axios.min.js: 12.9 kB
+ moment-with-locales.min.js: 336 kB

By using the libraries above there're 568.4 kB. The runtime dependencies of [above demo](https://younos1986.github.io/) includes:

<details>
<summary>Expand</summary>

+ @agm/core
+ @angular/animations
+ @angular/cdk
+ @angular/common
+ @angular/core
+ @angular/flex-layout
+ @angular/forms
+ @angular/material
+ @angular/material/button
+ @angular/material/card
+ @angular/material/checkbox
+ @angular/material/core
+ @angular/material/datepicker
+ @angular/material/dialog
+ @angular/material/divider
+ @angular/material/form-field
+ @angular/material/icon
+ @angular/material/list
+ @angular/material/menu
+ @angular/material/progress-bar
+ @angular/material/select
+ @angular/material/sidenav
+ @angular/material/tabs
+ @angular/material/toolbar
+ @angular/platform-browser
+ @angular/router
+ @ngx-loading-bar/core
+ @ngx-loading-bar/router
+ @ngx-translate/core
+ @ngx-translate/http-loader
+ @progress/kendo-angular-buttons
+ @progress/kendo-angular-dateinputs
+ @progress/kendo-angular-dialog
+ @progress/kendo-angular-dropdowns
+ @progress/kendo-angular-excel-export
+ @progress/kendo-angular-grid
+ @progress/kendo-angular-inputs
+ @progress/kendo-angular-intl
+ @progress/kendo-angular-l10n
+ @progress/kendo-angular-layout
+ @progress/kendo-angular-pdf-export
+ @progress/kendo-angular-popup
+ @progress/kendo-angular-resize-sensor
+ @progress/kendo-common
+ @progress/kendo-data-query
+ @progress/kendo-date-math
+ @progress/kendo-drawing
+ @progress/kendo-file-saver
+ @progress/kendo-ooxml
+ @progress/kendo-popup-common
+ @telerik/kendo-draggable
+ @telerik/kendo-inputs-common
+ @telerik/kendo-intl
+ core-js
+ jquery
+ jszip
+ ng-snotify
+ ngx-perfect-scrollbar
+ pako
+ perfect-scrollbar
+ resize-observer-polyfill
+ rxjs
+ rxjs-compat
+ screenfull
+ tslib
+ zone.js

</details>

Even I do agree Angular official libraries should be more concise, but in that application Angular is definitely not the one to account this for.

**Comment by unosbaghaie** [comment] 2019-04-29 11:45
I wanted to make dependencies heavy and then make its performance and its size reasonable. 
Actually I didn't know that Gzip is not the default case in Firefox. 

And I don't load tese files

- jquery.min.js: 88.2 kB
- bootstrap.min.js: 58.1 kB
- lodash.min.js: 73.2 kB
- axios.min.js: 12.9 kB
- moment-with-locales.min.js: 336 kB

**Comment by trotyl** [comment] 2019-04-29 12:08
@unosbaghaie 

> Actually I didn't know that Gzip is not the default case in Firefox.

gzip is the default case in Firefox, but it provided the original size stat in Network panel of the devtool. gzip is supported by IE6+, I don't think any user still use IE5- today.

> And I don't load tese files

I mean that every project documents their size in gzipped value, if you want to compare the uncompress number, you should be aware that the number would always looks much bigger.

**Comment by unosbaghaie** [comment] 2019-04-30 06:42
@trotyl  So transfered size is size of all requests to server and all files (which is transfered in gzipped value). Here 329 KB is transfered from server but they have taken 1.20MB space in the browser.  Am I right ?

**Comment by trotyl** [comment] 2019-04-30 08:03
@unosbaghaie 

> So transferred size is size of all requests to server and all files

Depends what filter used, here is **JS**, and there're other files (like images), which doesn't matter here.

> Here 329 KB is transferred from server but they have taken 1.20 MB space in the browser. Am I right ?

Yep, you're right, sorry for reading it wrong (previous thought that be be unfiltered size, not familiar with Firefox).

**Comment by HardikDG** [comment] 2019-05-30 09:41
> If you use typescript, you can create a rxjs.ts in your project, point to it in your tsconfig.json like:
> 
> ```json
> {
>     "compilerOptions": {
>         "paths": {
>             "rxjs": ["./application/vendor/rxjs.ts"]
>         },
>     }
> }
> ```
> 
> and your `application/vendor/rxjs.ts` looks like
> 
> ```ts
> export {Subject, AnonymousSubject} from 'rxjs/Subject';
> export {Observable} from 'rxjs/Observable';
> export {Subscription} from 'rxjs/Subscription';
> export {Subscriber} from 'rxjs/Subscriber';
> export {ReplaySubject} from 'rxjs/ReplaySubject';
> export {Observer} from 'rxjs/Observer';
> export {Operator} from 'rxjs/Operator';
> ```
> 
> So your `import {Observable} from 'rxjs'` will use your custom rxjs build instead of the full thing (https://github.com/ReactiveX/rxjs/blob/master/src/Rx.ts)
> 
> This should shave off 300 kb from your build. But there must be something else wrong if your vendor file is 2.42 MB in size.

By this, we are getting circular definition errors for the modules which are exported manually from vendor/rxjs.ts

`src/vendor/rxjs.ts(3,1): error TS2303: Circular definition of import alias 'Observable'. src/vendor/rxjs.ts(4,1): error TS2303: Circular definition of import alias 'SubscriptionLike'. src/vendor/rxjs.ts(5,1): error TS2303: Circular definition of import alias 'Subscription'. src/vendor/rxjs.ts(6,1): error TS2303: Circular definition of import alias 'throwError'. src/vendor/rxjs.ts(7,1): error TS2303: Circular definition of import alias 'BehaviorSubject'. src/vendor/rxjs.ts(8,1): error TS2303: Circular definition of import alias 'Observer'. src/vendor/rxjs.ts(9,1): error TS2303: Circular definition of import alias 'Operator'. src/vendor/rxjs.ts(10,1): error TS2303: Circular definition of import alias 'ObservableInput'. src/vendor/rxjs.ts(11,1): error TS2303: Circular definition of import alias 'Unsubscribable'. src/vendor/rxjs.ts(12,1): error TS2303: Circular definition of import alias 'TeardownLogic'. src/vendor/rxjs.ts(13,1): error TS2303: Circular definition of import alias 'SchedulerLike'. src/vendor/rxjs.ts(14,1): error TS2303: Circular definition of import alias 'ReplaySubject'.`

Anyone faced the same scenario?

**Comment by sod** [comment] 2019-05-30 10:30
Do you use rxjs 6? If yes, you don't need the workaround anymore. Just delete the rxjs.ts file and the paths config and import everything from `rxjs` and `rxjs/operator` directly. I updated my comment to reflect that it's outdated.
