### ISSUE TITLE
ngModel initially sets text input to last property value in an array of objects when using @angular/forms

### ISSUE THREAD

**Issue by rrfenton** [angular/angular#10511] opened 2016-08-05 00:14 UTC
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
If using the forms library, if you bind to a property of an object derived from an ngFor to a text input, the initial value of the text input is the same as the value of that property for the last item in an array.

**Expected/desired behavior**
The initial value of the textboxes should be the same as the value for that property of the object.

**Reproduction of the problem**
https://plnkr.co/edit/uaunzoPKjlJpSJ8oS76z

**What is the motivation / use case for changing the behavior?**
This only happens when using the form library.  If I omit the forms library, it functions normally.
If a user has a form that utilizes arrays to iterate over similar objects, the reliability of the form is poor.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** Chrome 51.0.2704.103 m
 
* **Language:** TypeScript 1.8 transpiling to ES5

**Comment by rrfenton** [comment] 2016-08-05 00:22
It appears that it has to do with all the ngFor items having the same form name.

If this is intended, I must have missed it in the docs.

**Comment by kara** [comment] 2016-08-05 00:52
Yes, every form control name on the same level must be unique if you don't want them to share a control.   If you're not using the name, you can always use the index. Closing as it works as intended.

**Closed by kara** 2016-08-05 00:52 UTC
