### ISSUE TITLE
Docs version change not redirecting to valid url

### ISSUE THREAD

**Issue by proUserSid** [angular/angular#35657] opened 2020-02-25 04:43 UTC
# 📚 Docs or angular.io bug report

### Description

 Docs Version change Stable to next not redirect to valid URL.
It is redirecting to https://next.angular.iodocs/
It need to be redirect to https://next.angular.io/docs/

### What's the affected URL?**
 https://angular.io/docs

### Reproduction Steps**

![Untitled](https://user-images.githubusercontent.com/52596235/75215077-98a70080-57b5-11ea-9b8d-335bf7086d6c.png)

### Expected vs Actual Behavior**

Expected 
![image](https://user-images.githubusercontent.com/52596235/75215510-f2f49100-57b6-11ea-8e88-2873a9fb669e.png)

Actual 
![image](https://user-images.githubusercontent.com/52596235/75215171-e0c62300-57b5-11ea-801f-9b55d8ccccc0.png)

**Comment by JoostK** [comment] 2020-02-25 06:49
Duplicate of #35630, addressed in #35632

**Closed by JoostK** 2020-02-25 06:49 UTC
