### ISSUE TITLE
Route params in non route component

### ISSUE THREAD

**Issue by otolol** [angular/angular#10700] opened 2016-08-11 18:42 UTC
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report
[ x ] feature request
[ ] support request => Please do not submit support request here, instead see 
```

**Current behavior**

I have app.routes.ts

```
    {path:'hero', component: HeroCmp},
    {path:'hero/:id', component: HeroDetailCmp}

```

app.component.html

```
<hero-header></hero-header>
<router-outlet></router-outlet>

```

when I am navigated on hero/:id route and tried to get route params in  HeroDetailCmp like this:

```
   this.route.params.subscribe((params) => {
                console.log(params.id) 
   });
```
where route is instance of `ActivatedRoute`, everything is ok.

but if I try to get route params in `hero-header`,  which is not root component. There is returned empty object: ` Object {}`.

**What is the expected behavior?**

I expected that to get route params (in this case heroID) in hero-header component too, same way as in `heroDetailCmp`, cause I want highlight `hero-header`, which is depended on hero id.

* **Angular version:** 2.0.0-rc.4

**Comment by mlc-mlapis** [comment] 2016-08-11 18:51
I think that you have to use [st]="st" @Input attribute on <hero-header  [st]="st"> tag to transfer the value of 'id' to a child cmp. Abilityto use 'this.route.params.subscribe.....' is related to each route and its cmp separately.

**Comment by otolol** [comment] 2016-08-11 19:02
@mlc-mlapis 
I have structure like this

                           Appcomponent
                               |                 |
                   hero-header        router-outlet
                                                        |
                                                    hero
                                                        |
                                                    hero-detail


hero is separate from hero-header cause hero-header is common for many components, which are depended on route change. And route params are empty also in AppComponent.

**Comment by mlc-mlapis** [comment] 2016-08-11 19:19
OK, but still I think that you will have to choose you own channel how to transfer 'id' to other places like a central comm hub service (singelton + observable/subscribes) or so because there are many combinations how routes could be defined (like /XXX/5/YYY/6/ZZZ/7 - three :ids exist).

**Comment by otolol** [comment] 2016-08-11 19:28
I can make service for hero-header subscribe and subsrcibe every component root. but for this I need fire observer in every component.  e.x. for id. for id/xx. for id/xx/yy for id/xx/yy/zz. If I could catch all params in hero-header it will be less boilerplate in more flexible.

**Comment by mlc-mlapis** [comment] 2016-08-11 20:26
I thought a concept like:
- a singelton hub service that will be available through constructor DI on each cmp
- this service will have a method through which each cmp will send its :id
- each cmp can subscribe to a hub observable through which ids will be distributed
- syntax and structure of messages are on you

**Comment by otolol** [comment] 2016-08-11 21:25
a singelton hub service that will be available through constructor DI on each cmp.  This one is big problem imho. Another things ok. Because header is common for every component and u can have more than twenty or thirty components and write same thing in every component. Which is les abstracted.

**Comment by vsavkin** [comment] 2016-08-11 22:13
Route params are scoped to the route they are defined in. This is by design. 

You can, however, navigate the router state tree to get other routes' params. 

If you want to share your params across different routes, you should use queryParams. Another option would be to provide a custom URL serializer, that will push the same set of params into every activated route.

Closing this issue.

**Closed by vsavkin** 2016-08-11 22:13 UTC

**Comment by mlc-mlapis** [comment] 2016-08-11 23:00
So maybe use a 'componentless' route at the root of your route tree (all others will be children) and only one guard on it that will be processed also on any child route. In this guard you have the ability to analyze an actual activated route and push info to a hub service. This eliminates the necessity to repeatedly create the same code and call a method from a hub service from each component.
