### ISSUE TITLE
AOT generated scss.shim imported path && scss brackets bugs

### ISSUE THREAD

**Issue by zhaxi** [angular/angular#12539] opened 2016-10-26 07:49 UTC
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Following angular.io docs:<AHEAD-OF-TIME COMPILATION>

Using node_modules/.bin/ngc command to generate AOT code into /aot dir,

**Include Path Bugs**:

 For example in home.ngfatory.ts  it shows :

![image](https://cloud.githubusercontent.com/assets/4652360/19724581/a0a6159e-9bb3-11e6-9b1c-914995520ee2.png)

Actually the structure in AOT dir is:

![image](https://cloud.githubusercontent.com/assets/4652360/19724590/adf37e30-9bb3-11e6-86b1-2f4e1c2aa3ab.png)

The structure in App dir is :

![image](https://cloud.githubusercontent.com/assets/4652360/19724600/b9f4e9d0-9bb3-11e6-9fdf-d32fa3a4f9fb.png)

**SCSS brackets bugs:**

In AOT mode, styles became a mess,

in component.scss.shim shows:
￼￼￼￼￼
![wangwang20161026154111](https://cloud.githubusercontent.com/assets/4652360/19717344/a64f5e4a-9b92-11e6-8a53-be0748992b20.png)
￼
￼It has a pair of needless brackets compared to JIT mode,  if I delete the brackets in head styles，all became normal

**Expected behavior**

**SCSS Include expected behavior**
![image](https://cloud.githubusercontent.com/assets/4652360/19724618/d26bb8ae-9bb3-11e6-8473-04a58563af90.png)

**SCSS brackets expected behavior**
![image](https://cloud.githubusercontent.com/assets/4652360/19717424/20e7e230-9b93-11e6-9b07-79140ee403b1.png)

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

AOT shows the same as JIT mode

**Please tell us about your environment:**

MacOS Serria, Visual Studio Code, NPM
* **Angular version:** 2.1.1

* **Browser:** [all ]

* **Language:** [TypeScript 2.0.3]
* **Node (for AoT issues):** 6.8.1
* **Webpack:** 2.1.0-beta.25

**Comment by DzmitryShylovich** [comment] 2016-10-26 07:52
Hi. Can u pls provide a minimal repository with reproduction?

**Comment by robwormald** [comment] 2016-10-26 07:59
Also, how are you running the SCSS compilation? do your components point to `foo.css` or `foo.scss` ?

**Comment by zhaxi** [comment] 2016-10-26 08:20
@DzmitryShylovich  I will try to make a demo,
@robwormald , I'm using angular2-template-loader,  and the scss compilation is:
![image](https://cloud.githubusercontent.com/assets/4652360/19718402/b0086d5a-9b97-11e6-91ea-65be5545716c.png)

the component code is:
![image](https://cloud.githubusercontent.com/assets/4652360/19718417/c0a626ca-9b97-11e6-9623-4ae29864d3ea.png)

**Comment by zhaxi** [comment] 2016-10-28 02:39
@robwormald @DzmitryShylovich  I know why now, I use scss in styleUrls, and with webpack sass-loader, app runs well in JIT mode using webpack. In AOT mode, I have to run ngc command first, and ngc compiled scss files to scss.shim.ts directly without any scss compilation. The scss.shim.ts include path is wrong, also In scss.shim.ts scss grammer exists(I thought 'shim' means scss is compiled).

**Comment by vicb** [comment] 2016-10-28 05:37
@zhaxi does it means this issue can be closed ?

**Comment by zhaxi** [comment] 2016-10-28 07:57
@vicb , I think it's a bug, cause ngc realize scss is style files, and add shim to scss files, but the include path and style code are not correct.

**Comment by Krisa** [comment] 2016-10-29 10:19
This is a dupe of https://github.com/angular/angular/issues/11688

**Closed** 2016-10-29 18:55 UTC
