### ISSUE TITLE
Expose list of validators (with meta data) to FormControl / AbstractControl

### ISSUE THREAD

**Issue by Bidthedog** [angular/angular#15173] opened 2017-03-15 18:03 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] feature request
```

**Current behavior**
There's no way to list the current validators that are applied to a FormControl / AbstractControl.

**What is the motivation / use case for changing the behavior?**
I'd like to create dynamic error messages, and apply attributes in child components based on the validators that are present.

For example, I would like to be able to add the `maxlength` HTML attribute on to a text box control, if the maxLength validator is present (to reduce duplication) - but I need to be able to access the validator's metadata to do so.

The closest I can get is the following, but because the `error` object only exists after the user has typed over the validator limit, I can only limit it to 11 chars, instead of the expected 10:

FormBuilder config excerpt:
```
firstName: ['', [Validators.required, Validators.maxLength(10)]]
```

Template:
```
<input type="text"
    formControlName="firstName"
    [attr.maxlength]="control.getError('maxlength')?.requiredLength"
```

Where `control` is an AbstractControl.

**Comment by DzmitryShylovich** [comment] 2017-03-15 18:06
Duplicate of https://github.com/angular/angular/issues/13461

**Comment by IgorMinar** [comment] 2017-03-16 15:54
Thanks for reporting this issue. However this issue is a duplicate of an existing issue #13461. Please subscribe to that issue for future updates.

**Closed by IgorMinar** 2017-03-16 15:54 UTC
