### ISSUE TITLE
ngClass and conditions

### ISSUE THREAD

**Issue by nauw** [angular/angular#17274] opened 2017-06-06 20:12 UTC
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When using ngClass Directive with 2 conditions, it seems that similar class used in both are removed when the first condition is true.

Consider the following code to display standard Bootstrap alert if the server is online or offline.

`<div [ngClass]="{'alert alert-danger': serverStatus!='online','alert alert-success': serverStatus==='online'}">`

**Expected behavior**

Expected result is 

`<div class="alert alert-danger">Server is not online</div>`
or
`<div class="alert alert-success">Server is online</div>`

Result is 

`<div class="alert-danger">Server is not online</div>` _-- Missing class 'alert'_
or
`<div class="alert alert-success">Server is online</div>` _-- OK_

**Minimal reproduction of the problem with instructions**

Pushing the test as far as i can, every similar class existing on both condition are "removed" when the first condition is true.

Just for the sake of demonstration.

`<div [ngClass]="{'alert alert-success': serverStatus!='online','alert alert-success': serverStatus==='online'}">`

Result is 

`<div >Server is not online</div>` _-- no class at all_
or
`<div class="alert alert-success>Server is online</div>` _-- OK_

**Please tell us about your environment:**
MacOSX

* **Angular version:** 4.0.X

* **Browser:** [all]
 
* **Language:** [TypeScript ]

Thank you for your review.

Arnaud

**Comment by pkozlowski-opensource** [comment] 2017-06-06 20:22
Duplicate of #5763 - please check https://github.com/angular/angular/issues/5763#issuecomment-166114033 for more details.

**Closed by pkozlowski-opensource** 2017-06-06 20:22 UTC
