### ISSUE TITLE
Merging search parameters with the same key in URL

### ISSUE THREAD

**Issue by bratzie** [angular/angular#13425] opened 2016-12-13 13:12 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

If you navigate to a route with multiple search parameters with the same key, they will be merged to one with only the last appearing parameters value. i.e. 
    `host.com/test?p=test&p=best `
would result in 
    `host.com/test?p=best` 
once Angular has loaded.

**Expected behavior**

Navigating to 
    `host.com/test?p=test&p=best` 
should result in 
    `host.com/test?p=test&p=best` 
once Angular has loaded.

**Minimal reproduction of the problem with instructions**

Steps to reproduce: Implement routing, navigate to a route with more than one search parameter with the same key.
Here's a [plnkr](http://plnkr.co/edit/CmrBf43z3m9lsRq8fPoT) of the issue. Open it full screen and click on the thing that says click me.

**What is the motivation / use case for changing the behavior?**

The rest point I'm using for filtering/facetting adds multiple search parameter keys of the same type if I select more than one filter/facet. With the current behaviour I can only select one filter per type as it will merge everything with the same key together. Feels unnecessary to merge?

**Please tell us about your environment:**

OSX El Capitan 10.11.6. Locally with Brackets / Webpack / NG Live Development Server. Also reproduced in plunkr.

* **Angular version:** 2.0.X (I tested it with Angular 2.2.3 locally and was able to reproduce. Looked through fixes for 2.3.0 and I don't think a fix has been implemented.)

* **Browser:**  I can reproduce this in Chrome 54, FF 48, Safari 10.0.1.

 
* **Language:** [all]

**Comment by DzmitryShylovich** [comment] 2016-12-13 13:16
Duplicate of https://github.com/angular/angular/issues/11374

**Comment by bratzie** [comment] 2016-12-13 13:19
Ah, my bad, I tried searching around for something similar. Feel free to close this then!

If it helps others, in my case I solved it by saving the search parameters before Angular parsed them, and reinstated them after initial load had been done.

**Comment by DzmitryShylovich** [comment] 2016-12-13 13:20
> Feel free to close this then!

u have the power to close it yourself :)

**Closed** 2016-12-13 13:21 UTC
