### ISSUE TITLE
Angular6 Test cases fail with unrelated error messge

### ISSUE THREAD

**Issue by Aakash06** [angular/angular#25573] opened 2018-08-20 06:23 UTC
I have migrated Angular 4 app to Angular 6 and now Test cases fail with following error message in the terminal and it shows success on the browser. Also, sometimes test cases pass without showing any error message. So we can say I get following error 60% of the times I run ng test.
```
Chrome 67.0.3396 (Linux 0.0.0) ERROR
 {
    "message": {
      "isTrusted": true
    },
    "str": "[object ErrorEvent]"
  }
```
I have tried upgrading and downgrading jasmine and jasmine-core

This is my package.json
```
{
  "name": "anonymos",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^6.0.3",
    "@angular/common": "^6.0.3",
    "@angular/compiler": "^6.0.3",
    "@angular/core": "^6.0.3",
    "@angular/forms": "^6.0.3",
    "@angular/http": "^6.0.3",
    "@angular/platform-browser": "^6.0.3",
    "@angular/platform-browser-dynamic": "^6.0.3",
    "@angular/router": "^6.0.3",
    "@ng-bootstrap/ng-bootstrap": "^2.2.0",
    "angular-cookie": "^4.1.0",
    "angular-in-memory-web-api": "^0.6.0",
    "angular2-cookie": "^1.2.6",
    "angular2-recaptcha": "1.1.0",
    "body-parser": "1.18.3",
    "bootstrap": "4.1.2",
    "cookie-parser": "1.4.3",
    "core-js": "^2.5.4",
    "es6-shim": "0.35.3",
    "http-server": "0.11.1",
    "jquery": "^3.3.1",
    "js-base64": "2.4.8",
    "node-sass": "^4.9.2",
    "popper.js": "^1.14.3",
    "reflect-metadata": "0.1.12",
    "rxjs": "^6.0.0",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.6.8",
    "@angular/cli": "~6.0.8",
    "@angular/compiler-cli": "^6.0.3",
    "@angular/language-service": "^6.0.3",
    "@types/jasmine": "~2.8.6",
    "@types/jasminewd2": "~2.0.3",
    "@types/jquery": "3.3.4",
    "@types/node": "^8.10.21",
    "codelyzer": "~4.2.1",
    "jasmine": "^3.1.0",
    "jasmine-core": "^2.9.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "^2.0.4",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.0",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.3.0",
    "ts-node": "~5.0.1",
    "tslint": "~5.9.1",
    "typescript": "~2.7.2"
  }
}
```
If anything else is needed to debug please let me know. I can't upload test cases as they are around 350 of them.

You can refer 
https://stackoverflow.com/questions/51807914/angular6-test-cases-fail-with-unrelated-error-messge

**Comment by jasonaden** [comment] 2018-08-20 18:30
@Aakash06 It looks like there's a suggestion over on StackOverlow to fix this. Please try that and update here.

Also, we need a reproduction in order to accept an issue. If you can produce a repro today, we can pull in this issue. Otherwise we have to close the issue as a support request without a reproduction.

Hopefully the suggestion on StackOverflow fixes this for you.

**Comment by jasonaden** [comment] 2018-08-20 18:31
Note that a reproduction can be just a single test. You don't need to upload 350 tests, and generally we wouldn't accept that anyway as it isn't specific enough of a reproduction.

**Comment by jasonaden** [comment] 2018-08-21 20:54
I'm sorry but reported issues require a reproduction of the issue. We suggest using [StackBlitz](https://stackblitz.com/fork/angular-gitter), [Plunker](http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue) or [Github](https://github.com/new).

If this issue persists, please create a reproduction using one of the links above. Describe the difference between the expected and current behavior in a new issue with the reproduction linked.

**Closed by jasonaden** 2018-08-21 20:54 UTC
