### ISSUE TITLE
Angular 17: If SSR is enabled, The route is loaded before guard returns a boolean (returning Observable<boolean> | Promise<boolean>)

### ISSUE THREAD

**Issue by georgemff** [angular/angular#56691] opened 2024-06-26 10:41 UTC
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

Yes

### Description

I added "canActivate" to route but it still loads (like jumps on the screen) before guard redirects to another route (when user is not authorised). when I disabled "ssr" and "prerender", it doesn't happens.

**Comment by JeanMeche** [comment] 2024-06-26 10:43
Hi, the discription of your issue doesn't make clear what you're actually expecting. 
Could you provide a stackblitz of the issue ?

**Comment by georgemff** [comment] 2024-06-26 10:44
> Hi, the discription of your issue doesn't make clear what you're actually expecting. Could you provide a stackblitz of the issue ?

I added screen recording if it helps

**Comment by JeanMeche** [comment] 2024-06-26 10:45
Did you check the console for error ? 
A stackblitz repro would really help understand what you did.

**Comment by georgemff** [comment] 2024-06-26 10:47
> Did you check the console for error ? A stackblitz repro would really help understand what you did.

Unfortunately can not upload it on stackblitz. no errors in console but another detail: it happens when canActivate returns Promise<boolean> or Observable<boolean>

**Comment by georgemff** [comment] 2024-06-26 10:49
<img width="684" alt="Screenshot 2024-06-26 at 2 48 52 PM" src="https://github.com/angular/angular/assets/37007370/93b67eb1-2228-48f3-8159-90b248449e78">

**Comment by JeanMeche** [comment] 2024-06-26 10:49
Navigating inside a guard is not recommended. you should return an URL tree of the boolean.

**Comment by georgemff** [comment] 2024-06-26 10:54
> Navigating inside a guard is not recommended. you should return an URL tree of the boolean.

I tried to return UrlTree but it still happens if ssr is enabled (ssr: true in angular.json).
I think the problem is that the component on this route still jumps on the screen before observable returns value (from api in this case).

**Comment by JeanMeche** [comment] 2024-06-26 10:57
You probably need to log when you application becomes stable. 
SSR send the generated HTML when the app becomes stable for the first time. 

HttpClient keeps the application unstable, but if your auth relies on Firebase for example, it's know to not keep the app unstable until the response arrive. 

This doesn't look like a bug but a support issue which is much suited on stackoverflow.

**Comment by georgemff** [comment] 2024-06-26 11:11
it still happens if I use ngrx store and not httpclient.
that's what I mean, canActivate method is not finished and component is already loaded... 

<img width="1242" alt="Screenshot 2024-06-26 at 3 10 19 PM" src="https://github.com/angular/angular/assets/37007370/13c16ead-3d2c-494f-a50b-5e0cb83106e8">

**Comment by JeanMeche** [comment] 2024-06-26 11:14
Have a look at https://angular.dev/api/core/ExperimentalPendingTasks to keep your app unstable.

**Comment by JeanMeche** [comment] 2024-06-26 11:34
Right. 

To understand what is happening in your case, we'll really need a narrowed down reproduction (either github or stackblitz). 
Without this it, this issue isn't actionable to us.

**Comment by atscott** [comment] 2024-06-26 20:45
This is most likely something to do with how authorization works on your server rather than an issue with the Router or serializing before the guard returns. A similar issue was discussed in #54459. Closing as a support request/unable to reproduce.

**Closed by atscott** 2024-06-26 20:45 UTC
Labels: needs reproduction
