### ISSUE TITLE
provide api to reorganize the content inside hostView and <ng-content>

### ISSUE THREAD

**Issue by vthinkxie** [angular/angular#41074] opened 2021-03-04 02:59 UTC
# 🚀 feature request

### Relevant Package

@angular/core

### Description

In React, users can reorganize the children easily, such as insert a separator between all components

here is an example

https://stackblitz.com/edit/react-ts-cbvesy?file=Space.tsx

it is hard(impossible) to make the same space component inside Angular since there is no suitable API to do this.

1. `ContentChildren` can only get `component` or `directive` which has a declaration
2. `ViewContainerRef.move` or `insert` can only manipulating the `ViewRef` that inserted inside it, not all `ElementRef` inside it.
3. no suitable API to watch all changes inside `<ng-content>` or `hostView`

### Describe the solution you'd like

1. provide API to get children inside `<ng-content>` and `hostView` like React
2. provide API to manipulate `ElementRef` inside `<ng-content>` and `hostView`
3. provide `Observable` to get changes inside `<ng-content>` and `hostView`

related https://github.com/WICG/webcomponents/blob/gh-pages/proposals/Imperative-Shadow-DOM-Distribution-API.md

or

provide a Renderer Interceptor which could intercept the render process, here is a POC https://github.com/trotyl/angular-contrib/tree/master/projects/core/src/render-intercept

related issue https://github.com/angular/angular/issues/3929

**Comment by pkozlowski-opensource** [comment] 2022-03-10 14:12
Duplicate of #37319

**Closed by pkozlowski-opensource** 2022-03-10 14:12 UTC
Labels: feature, comp: core, core: content projection, under consideration, votes required
