### ISSUE TITLE
Some TestModuleMetadata properties are different from NgModule properties types 

### ISSUE THREAD

**Issue by abarghoud** [angular/angular#40874] opened 2021-02-16 18:05 UTC
# 📚 Docs or angular.io bug report

### Description
Types of properties `providers`, `declarations` and `imports` of `TestModuleMetadata` are different from the ones in `NgModule` 

See TestModuleMetadata:
https://github.com/angular/angular/blob/master/packages/core/testing/src/test_bed_common.ts#L38-L44

NgModuleMetadata
https://github.com/angular/angular/blob/c461acd12e529a253b17ebfae41c4a81fb757707/packages/core/src/metadata/ng_module.ts#L57-L246

### What's the affected URL?**
https://angular.io/api/core/testing/TestModuleMetadata

## 🌍  Your Environment

Angular latest.

**Comment by AndrewKushnir** [comment] 2021-02-16 19:17
Hi @abarghoud, this looks like a duplicate of #37178 and should be resolved by PR #28662, so I'm closing this issue. Please reopen if I'm missing something and this is a different issue. Thank you.

**Closed by AndrewKushnir** 2021-02-16 19:17 UTC
