### ISSUE TITLE
Tabs Support

### ISSUE THREAD

**Issue by tettusud** [angular/angular#15027] opened 2017-03-09 09:11 UTC
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

    I would like to have Tab feature support from angular, currently I do not see a way to implement tabs, opening routes in each tab and preserve the state.
  I tried to use RouteReuseStrategy ,but it doenst not work with lazy loaded module.
Is there a way to implement tabs?
**Expected behavior**

  Open each routes in a separate tab,and allow users to go back and forth whle editing.
**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

yes
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 all
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES5
* **Node (for AoT issues):** `node --version` =

**Comment by Toxicable** [comment] 2017-03-09 09:19
If you are talking about the browser tab then each tab is a new window object, therefore it is a new instance of the application and from my understanding code cannot be shared between

**Comment by tettusud** [comment] 2017-03-09 11:12
Thank you @Toxicable  ,But my requirement is this, whenever user clicks on menu item,I need to open each in a tab.
Currently whenever its clicked ,individual routes open in same <router-outlet></router-outlet> and replaced previously opened right?
But instead each route should open in a separate tab,so user can switch between tabs

routes:Routes=[
  {path:'customer' ,component:CustomerDetails},
 {path:'products', component:ProductDetails}
]

<a [routerLink]="['customer']">customer</a>
<a [routerLink]="['products']">product</a>

 so user should be able to opne and switch between back and forth, while preserving the state, whatever entered in customer form should be still intact whne he navigates to product and comes back.
 
Somehow i was able to achieve the above one by implement RouteReuseStrategy, but if the route is a lazyloaded one it still fails.

**Comment by Toxicable** [comment] 2017-03-10 04:34
@tettusud Are you talking about browser tabs or tabs within your application?

**Comment by tettusud** [comment] 2017-03-10 06:25
Tabs within my application

Sent from my HTC

----- Reply message -----

**Comment by neilhem** [comment] 2017-03-10 06:50
Seems like dupe of #5275

**Comment by tettusud** [comment] 2017-03-10 11:29
@neilhem ,you got any working example for implementing it?

**Comment by buctwbzs** [comment] 2017-08-24 12:34
I have same issue,I have already made great efforts on it,but I did not finish it.At present, lazy loading is really impossible to achieve.There is a blog about RouteReuseStrategy in lazy loading  [here，but](https://medium.com/@gerasimov.pk/how-to-reuse-rendered-component-in-angular-2-3-with-routereusestrategy-64628e1ca3eb) i can't understand how to finish it.you can read it,maybe you will  get inspiration from it.Last but not least,if you got it ,plz tell me....

**Closed** 2020-06-19 12:59 UTC
Labels: comp: router, type: feature
