### ISSUE TITLE
Protractor E2E tests time out with NG1-NG2 hybrid bootstrapped application.

### ISSUE THREAD

**Issue by bringking** [angular/angular#8758] opened 2016-05-20 20:18 UTC
**Steps to reproduce and a minimal demo of the problem**
Setup a basic NG1 -> NG2 hybrid application and run E2E tests with protractor
#### Main entry point

``` typescript
  upgradeAdapter.addProvider([...PROVIDERS, ...ENV_PROVIDERS, ...DIRECTIVES, ...PIPES]);

  return upgradeAdapter.bootstrap(document.documentElement,
    ['app'], {strictDi: true});
```
#### Protractor config

``` js
const defaultConfig = {
  multiCapabilities: [
    {
      browserName: 'chrome', true, maxInstances: 6,
      chromeOptions: { args: ['--lang=en', '--window-size=360,600'] }
    }
  ],
  getPageTimeout: 10000, // How long to wait for a page to load in ms.
  allScriptsTimeout: 22000,
  baseUrl: 'http://localhost:3001',
  specs: `${__dirname}/../test/e2e/*.spec.js`,
  jasmineNodeOpts: {
    // If true, print colors to the terminal.
    showColors: true,
    // Default time to wait in ms before a test fails.
    defaultTimeoutInterval: 30000
  }
};

module.exports = { config: defaultConfig };

```
#### Sample test

``` js
const LoginPage = require('./page-objects/login.page');
const NavPage = require('./page-objects/nav.page');
const LogHelpers = require('./helpers/log.helper');

describe('login', () => {
  const loginPage = new LoginPage();
  const navPage = new NavPage();
  const logHelpers = new LogHelpers();

  beforeEach(() => {
    browser.get('login');
  });

  afterEach(() => {
    logHelpers.expectNoErrors();
  });

  describe('when valid credentals are given', () => {
    it('takes user to home', () => {
      expect(loginPage.submit.isEnabled()).toBe(false);
      loginPage.loginUser().then(() => {
        return navPage.logout.click();
      }).then(() => {
        return expect(browser.getCurrentUrl()).toMatch(/home/);
      });
    });
  });
});

```

**Current behavior**

Protractor throws the following error, no matter the timeout- 

``` bash
[chrome #1-10]   Message:
[chrome #1-10]     Failed: Timed out waiting for Protractor to synchronize with the page after 22 seconds. Please see https://github.com/angular/protractor/blob/master/docs/faq.md
```

[UPDATE] - 
I have tracked down the behavior to timeout when trying to use the `getCurrentUrl` method. 

``` js

this.loginUser = () => {
    return this.username.sendKeys('test').then(() => { // this succeeds
      return this.password.sendKeys('test'); // this succeeds
    }).then(() => {
      return this.submit.click(); // this succeeds
    }).then(() => {
      expect(browser.getCurrentUrl()).not.toMatch(/login/); // this times out
    });
  };

```

**Expected/desired behavior**

A successful test

**Other information**

Angular 1.x Version = 1.5.3
Angular 2.x Version = 2.0.0-rc.1
Protractor Version = 3.3.0

Possibly related to this PR - https://github.com/angular/angular/pull/7603

**Comment by dparish** [comment] 2016-08-31 17:16
I can't get this to work with RC5 and 4.0.4. From the notes on other defects it sounds like RC5 fixes it but it's not working for me.

Anyone know the magic combination of protractor config settings to get a hybrid app to work?

**Comment by DzmitryShylovich** [comment] 2017-03-11 22:37
@bringking is this still relevant?

**Comment by mbhalera** [comment] 2017-05-11 23:01
yes. I am also running into same issue.

**Comment by bringking** [comment] 2017-05-11 23:28
@DzmitryShylovich @mbhalera I can't verify anymore, we cancelled the project. However, it was unresolved when we stopped working on it.

**Comment by gkalpak** [comment] 2017-07-04 21:33
There is no way to investigate this without a reproduction. I am going to close it, since it is pretty old and not relevant for the OP any more. If anyone is still running into this problem (especially if using the new `upgrade/static` version), please open a new issue with a minimal reproduction.

**Closed by gkalpak** 2017-07-04 21:33 UTC
Labels: comp: testing, type: bug

**Comment by matt-senseye** [comment] 2017-07-05 08:04
For an example project showing this issue, and more discussion around it - see https://github.com/angular/protractor/issues/4290#issuecomment-308672943

**Comment by gkalpak** [comment] 2017-07-05 09:40
OK, thx for the link 👍
Let's track it there (although I am not sure this is ngUpgrade-specific in the first place - still an issue nonetheless).

**Comment by tonybranfort** [comment] 2018-02-26 14:06
angular/protractor#4290 is still open without any update since October 2017.  There are definitely people stuck on AngularJS due to that issue.
