### ISSUE TITLE
NgZone.onError not receiving errors

### ISSUE THREAD

**Issue by christianacca** [angular/angular#17012] opened 2017-05-25 07:18 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

`NgZone.onError` does not emit even though my component throws an error

**Expected behavior**

I should be able to subscribe to `NgZone.onError` and receive errors emitted

**Minimal reproduction of the problem with instructions**

See the following plunker: https://embed.plnkr.co/1ExTUf/

* Click the button `Throw`
* Notice the 'Error count' value does not change from '0'

Compare this to the following plunker that shows a **working example**: https://embed.plnkr.co/9Iat9QUI0VF8w7bgYJqS/

The only difference between these two examples is the version of angular: working in v4.1.0; broke in v4.1.1. 

I suspect the following commit introduced the breakage: [don’t stop change detection because of errors](https://github.com/angular/angular/commit/07cef36)

**What is the motivation / use case for changing the behavior?**

I want to receive errors so that I can respond to them programmatically. I want to be able to write this code in a library without forcing the hosting app to provide a custom `ErrorHandler` from this library.

**Please tell us about your environment:**

* Windows 10 Anniversary

* **Angular version:** 2.0.X

4.1.1 (but also reproducible in 4.1.3

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* Chrome 58.0.3029.110 (64-bit)
* IE 11
* Edge 38.14393.0.0
* Firefox 53.0.3 (32-bit) 

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

Typescript 2.2.1

* **Node (for AoT issues):** `node --version` =   

6.9.2

**Comment by mhevery** [comment] 2017-05-25 18:25
Before https://github.com/angular/angular/commit/07cef36 errors were never caught hence they would eventually cross the zone boundary and be caught. After this change the errors are caught bi the change detection and are feed to `ErrorHandler`. If you would like to intercept errors, please override `ErrorHandler`

Closing since this is working as intended.

**Closed by mhevery** 2017-05-25 18:25 UTC
Labels: comp: zones, severity5: regression, type: bug

**Comment by christianacca** [comment] 2017-05-26 07:02
Shame as that means that a library author will not be able to programmatically respond to an error in the application without forcing the app to use a custom `ErrorHandler` that the *library* supplies. That's a problem when the app already has overridden this for it's own purpose.
