### ISSUE TITLE
HttpClient no parse json in error body

### ISSUE THREAD

**Issue by miguelcaravantes** [angular/angular#19631] opened 2017-10-10 05:01 UTC
## Current behavior
in last release the angular 4 httpclient (@angular/common/http) dont parse error body to json

## Expected behavior
when result of http is error, angular must parse the response body to json

## Environment
Angular version: 4.4.4

The actual code in https://github.com/angular/angular/blob/master/packages/common/http/src/xhr.ts
    
 ```
  if (ok && req.responseType === 'json' && typeof body === 'string') {
          // Attempt the parse. If it fails, a parse error should be delivered to the user.
          body = body.replace(XSSI_PREFIX, '');
          try {
            body = JSON.parse(body);
          } catch (error) {
            // Even though the response status was 2xx, this is still an error.
            ok = false;
            // The parse error contains the text of the body that failed to parse.
            body = { error, text: body } as HttpJsonParseError;
          }
        }

        if (ok) {
          // A successful response is delivered on the event stream.
          observer.next(new HttpResponse({
            body,
            headers,
            status,
            statusText,
            url: url || undefined,
          }));
          // The full body has been received and delivered, no further events
          // are possible. This request is complete.
          observer.complete();
        } else {
          // An unsuccessful request is delivered on the error channel.
          observer.error(new HttpErrorResponse({
            // The error in this case is the response body (error from the server).
            error: body,
            headers,
            status,
            statusText,
            url: url || undefined,
          }));
        }
```

the parse is executed only when response is ok

**Comment by trotyl** [comment] 2017-10-10 05:47
Duplicate of #19103.

**Comment by alxhub** [comment] 2017-10-19 13:55
Closing as a duplicate.

**Closed by alxhub** 2017-10-19 13:55 UTC
Labels: comp: common/http
