### ISSUE TITLE
Binding to textarea value in IE/Edge when value is null, displays null.

### ISSUE THREAD

**Issue by P-de-Jong** [angular/angular#14241] opened 2017-02-02 07:09 UTC
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When binding to the value of a textarea and the value is null like so:

`public name: string = null;`
`<textarea [value]="name"></textarea>`

 In IE and Edge the textarea will display 'null'. In Chrome and FireFox the texarea is empty.
When using NgModel this does not happen.

**Expected behavior**
The textarea should be empty.

**Minimal reproduction of the problem with instructions**

[https://plnkr.co/edit/gmK3xItlgsAhc2K4FzvD?p=preview](https://plnkr.co/edit/gmK3xItlgsAhc2K4FzvD?p=preview)

**What is the motivation / use case for changing the behavior?**
We have a case where we use the value of inputs/textarea on blur to set a property. NgModel is not possible here.

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:**  Internet Explorer 11, Edge 38.14393.0.0, Chrome 56, FireFox 49.0.1

 
* **Language:** 2.1.5

**Comment by DzmitryShylovich** [comment] 2017-02-02 07:30
as a quick workaround `<textarea [attr.value]="name"></textarea>`

**Comment by P-de-Jong** [comment] 2017-02-02 07:35
@DzmitryShylovich This seems to work for now, thank you :)

**Comment by jdalton** [comment] 2017-02-18 00:12
I've reported this to Edge.

**Comment by DzmitryShylovich** [comment] 2017-02-18 08:45
@jdalton could you add a link here so we can track the issue? thx

**Comment by carlosrafaelcolon** [comment] 2018-03-04 16:49
@DzmitryShylovich Do you know how this workaround can work if your code is written like this: 
`<div [innerHTML]="person?.bio | sanitizeHtml" id="bio"></div>`
(not sure where I can throw in the `attr` value.

**Comment by lmmrssa** [comment] 2018-11-15 06:51
@carlosrafaelcolon you need to add `*ngIf="person?.bio"`

**Comment by pkozlowski-opensource** [comment] 2020-05-25 08:25
Here is a minimal reproduce scenario with the latest Angular: https://stackblitz.com/edit/angular-whv75y?file=src/app/app.module.ts

It looks like binding `null` to the `<textarea>`'s `[value]` property results in the null being converted to the `"null"` string. I'm not sure if we should special-case this in Angular as what we are facing here are cross-browser compatibility issues. So far we don't have any special-casing for property bindings so I'm not sure we should start adding ones.

Fortunately there is an easy work-around here: `<textarea [value]="name || ''"></textarea>`

**Comment by pkozlowski-opensource** [comment] 2020-05-25 08:30
BTW, it can only be reproduced in Edge that is _not_ based on chromium (ex. Edge 18).

**Comment by AndrewKushnir** [comment] 2022-03-01 00:28
Closing this ticket, since the reported problem was only present in IE11 and Angular no longer supports IE.

**Closed by AndrewKushnir** 2022-03-01 00:28 UTC
Labels: type: bug/fix, workaround1: obvious, freq1: low, comp: core, state: confirmed, core: binding & interpolation, core: DOM rendering, browser: edge, browser: ie 11, triage #1, P4
