### ISSUE TITLE
The documentation of HttpParams doesn't load

### ISSUE THREAD

**Issue by DazHsv** [angular/angular#27036] opened 2018-11-10 01:40 UTC
When I go to the documentation on angular.io, and select HttpParams from the search menu I got this message in the console and the page doesn't load.

`ERROR Error: [DocViewer] Error preparing document 'api/common/http/HttpParams': Error: Loading chunk 10 failed.
(error: https://angular.io/toc-toc-module-ngfactory.af5ec6fc598a8b5a66a9.js)
    at HTMLScriptElement.c (runtime.3314cba9b60341afaef9.js:1)
    at HTMLScriptElement.D (polyfills.92ff7bd39a33b228eade.js:1)
    at e.invokeTask (polyfills.92ff7bd39a33b228eade.js:1)
    at Object.onInvokeTask (main.4202909235a02f3a24ae.js:1)
    at e.invokeTask (polyfills.92ff7bd39a33b228eade.js:1)
    at t.runTask (polyfills.92ff7bd39a33b228eade.js:1)
    at t.invokeTask [as invoke] (polyfills.92ff7bd39a33b228eade.js:1)
    at y (polyfills.92ff7bd39a33b228eade.js:1)
    at HTMLScriptElement._ (polyfills.92ff7bd39a33b228eade.js:1)
    at HTMLScriptElement.c (runtime.3314cba9b60341afaef9.js:1)
    at HTMLScriptElement.D (polyfills.92ff7bd39a33b228eade.js:1)
    at e.invokeTask (polyfills.92ff7bd39a33b228eade.js:1)
    at Object.onInvokeTask (main.4202909235a02f3a24ae.js:1)
    at e.invokeTask (polyfills.92ff7bd39a33b228eade.js:1)
    at t.runTask (polyfills.92ff7bd39a33b228eade.js:1)
    at t.invokeTask [as invoke] (polyfills.92ff7bd39a33b228eade.js:1)
    at y (polyfills.92ff7bd39a33b228eade.js:1)
    at HTMLScriptElement._ (polyfills.92ff7bd39a33b228eade.js:1)
    at e.selector (main.4202909235a02f3a24ae.js:1)
    at e.error (main.4202909235a02f3a24ae.js:1)
    at e._error (main.4202909235a02f3a24ae.js:1)
    at e.error (main.4202909235a02f3a24ae.js:1)
    at e._error (main.4202909235a02f3a24ae.js:1)
    at e.error (main.4202909235a02f3a24ae.js:1)
    at e._error (main.4202909235a02f3a24ae.js:1)
    at e.error (main.4202909235a02f3a24ae.js:1)
    at e.notifyError (main.4202909235a02f3a24ae.js:1)
    at e._error (main.4202909235a02f3a24ae.js:1)`

**Comment by kounelios13** [comment] 2018-11-10 09:01
Do you use firefox?

**Comment by DazHsv** [comment] 2018-11-10 09:04
I was using Google Chrome

**Comment by kounelios13** [comment] 2018-11-10 09:05
I faced a similar issue on pipes docs on firefox

**Comment by AndrewKushnir** [comment] 2018-11-12 04:48
Thanks for reporting this issue. However this issue is a duplicate of an existing issue #26540 (as @ericmartinezr mentioned in the comment above). Please refer to the mentioned thread to find additional information about the issue.

**Closed by AndrewKushnir** 2018-11-12 04:48 UTC
