### ISSUE TITLE
Wildcard route with parameter

### ISSUE THREAD

**Issue by vahidvdn** [angular/angular#31551] opened 2019-07-14 09:24 UTC
# 🐞 bug report

### Description

When I use the path `path: '**'` for handling 404 page, it works fine. but I have a language parameter before each route. So I must have something like this:

```JS
path: ':lang/**'
```
But when I navigate to a url like this: `en/abcd` it gives me this error:

```
Error: Cannot match any routes. URL Segment: 'en/abcd'
```

Any idea?

## 🔥 Exception or Error
```
Error: Cannot match any routes. URL Segment: 'en/abcd'
```

## 🌍  Your Environment

**Angular Version:** 8.0.2

**Comment by santoshyadav198613** [comment] 2019-07-15 06:12
Hi @vahidvdn ,
Can you share your routes config, the wild card routes should be last, otherwise it will handle all the request.

**Comment by vahidvdn** [comment] 2019-07-15 07:30
Hi @santoshyadav198613. Here you are:

```JS
const routes: Routes = [
	{
		path: '',
		component: AppComponent,
		pathMatch: "full",
		canActivate: [LanguageRoutingGuardService]
	},
	{
		path: ':lang',
		loadChildren: './modules/home/home.module#HomeModule',
	},
	{
		path: ':lang/learn',
		loadChildren: './modules/learn/learn.module#LearnModule'
	},
	...
	{
		path: ':lang/**',
		loadChildren: './modules/not-found/not-found.module#NotFoundModule',
	},
];
```

**Comment by alxhub** [comment] 2019-08-15 23:04
Hi @vahidvdn,

Can you please post a stackblitz or github repo illustrating this problem?

In general `path: 'foo/**'` is not supported in the router. I believe the only way to make this work is to use a config like:

```typescript
{path: 'foo', children: [
  {path: '**', component: ...},
]}
```

**Comment by vahidvdn** [comment] 2019-08-16 08:39
@alxhub Hi
Please pay attention to `:` sign. It's not a route name, it's just a route param. For example:

```
en/notFound
fr/notFound
...
```

**Comment by atscott** [comment] 2020-07-09 17:54
Closing as working as intended. Example provided by @alxhub works with route params: https://stackblitz.com/edit/angular-ivy-router-base-wc8gqk?file=src%2Fapp%2Fapp.module.ts

**Closed by atscott** 2020-07-09 17:54 UTC
Labels: comp: router, freq1: low, severity3: broken, state: Needs repro, type: bug/fix
