### ISSUE TITLE
Docs not in left side nav don't get TOCs

### ISSUE THREAD

**Issue by kapunahelewong** [angular/angular#33582] opened 2019-11-04 20:32 UTC
# 📚 Docs or angular.io bug report

### Description

When a doc is in the left side nav of aio, it gets an autogenerated table of contents (toc). However, if it's not in the left sidenav, it doesn't.

### What's the affected URL?**
For example: https://next.angular.io/guide/migration-renderer

### Reproduction Steps**

Just have to create a new md file in aio/content/guides.

### Expected vs Actual Behavior**

It'd be helpful if TOCs applied to all docs.

## 📷Screenshot

Here's an example of one without a toc:

![image](https://user-images.githubusercontent.com/4116963/68155746-48f7ad00-ff18-11e9-9bd4-c16704343469.png)

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by ajitsinghkaler** [comment] 2019-11-11 18:13
Can I take this one

**Comment by ajitsinghkaler** [comment] 2019-11-11 18:18
can I add left nav to some of the docs

**Comment by gkalpak** [comment] 2019-11-11 19:06
Thx for offering to help, @ajitsinghkaler!

This is actually an issue/limitation of our infrastructure (not related to docs content). So, not a good issue for someone that is not familiar with our docs infrastructure/tooling.

I saw you volunteered to help out with a few other issues too, so I am sure one of those will be more suitable for you to contribute. Thx againf for stepping up!

##
(BTW, as a work-around, one can have a ToC in a doc without it appearing in the SideNav by adding it to `navigation.json` with `hidden: true` ([example][1].)

[1]: https://github.com/angular/angular/blob/ca1ff3ea11ef1b32bfff1ee365480fcc71c7119e/aio/content/navigation.json#L58

**Comment by ajitsinghkaler** [comment] 2019-11-12 18:13
So should I try this @gkalpak

**Comment by gkalpak** [comment] 2019-11-13 10:51
As mentioned above, I am afraid it is not a good issue for a first contribution, so I suggest you start somewhere else. But if you insist, I won't stand in your way 😛

**Comment by gkalpak** [comment] 2020-05-10 11:36
This is not actually fixed by #34979. Re-opening...

**Comment by aikidave** [comment] 2021-05-13 20:33
This behavior is actually intended. In general, all documentation should appear in the left navigation. There are a couple of exceptions--most notably when a topic may no longer be necessary, but do not have an appropriate redirect. In those cases, we mark the topic as ready for archiving and let the reader know the topic may not be reliable.

I'm going to close this issue as this is intended behavior. Happy to discuss it further if folks would like!

**Closed by aikidave** 2021-05-13 20:33 UTC
Labels: P4, comp: docs, comp: docs-infra, freq1: low, type: bug/fix
