### ISSUE TITLE
[Angular.dev] Cannot find module '@angular/core' or its corresponding type declarations.

### ISSUE THREAD

**Issue by Gehad28** [angular/angular#53151] opened 2023-11-24 16:27 UTC
### Describe the problem that you experienced

All examples/tutorials in angular.dev have the error: Cannot find module '@angular/core' or its corresponding type declarations.

Here is a screenshot of the problem:
![image](https://github.com/angular/angular/assets/81963100/16f44d59-35ba-49ac-b19a-cddb51af2e95)

and the console doesn't show anything:
![image](https://github.com/angular/angular/assets/81963100/55357164-74aa-461d-8062-0d846d986c20)

### Enter the URL of the topic with the problem

https://angular.dev/tutorials/learn-angular/components-in-angular

**Comment by csvn** [comment] 2023-11-28 20:22
I dunno if it's related, but the [API reference on angular.dev](https://angular.dev/api) is missing some 50 types on the `core` section, such as the [OnChanges](https://angular.dev/api/core/OnChanges) interface.

**Comment by twerske** [comment] 2023-11-29 18:00
While the WebContainer is booting (as shown on your screen) the dependencies are not yet resolved. These errors should disappear once the app is loaded. See https://github.com/angular/angular/issues/52649 as this is a duplicate of that possible feature add to wait to load TS resolution until after the app is loaded

**Closed by twerske** 2023-11-29 18:00 UTC
Labels: area: adev
