### ISSUE TITLE
ASSERTION ERROR: Should be run in update mode

### ISSUE THREAD

**Issue by kemsky** [angular/angular#35398] opened 2020-02-12 23:53 UTC
# 🐞 bug report

### Is this a regression?

 Yes, application works fine when I disable Ivy.

### Description

 
Crash happens when detectChanges is called right from component input setter (OnPush mode). Probably related to #32756.

```ts
    @Input()
    public set readonly(value: boolean) {
        // somewhere in other function:
        this.changeDetectorRef.detectChanges();
    }
```

This code seems to be a bad idea, but it can happen and error message is not helpful at all.

## 🔬 Minimal Reproduction

 Currently I don't have any.

## 🔥 Exception or Error
<pre><code>

Error: ASSERTION ERROR: Should be run in update mode [Expected=> false == true <=Actual]
    at oi (tap.ts:143)
    at Jn (tap.ts:143)
    at fl (tap.ts:143)
    at Jl (tap.ts:143)
    at e.detectChanges (tap.ts:143)
    at n.dispatchReadonlyChanged (abstract.form.component.ts:312)
    at n.set [as readonly] (abstract.form.component.ts:298)
    at Bl (tap.ts:143)
    at tap.ts:143
    at yl (tap.ts:143)
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular: 9.0.1
... common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.803.9 (cli-only)
@angular-devkit/core         8.3.9 (cli-only)
@angular-devkit/schematics   8.3.9 (cli-only)
@angular/cdk                 9.0.0
@schematics/angular          8.3.9 (cli-only)
@schematics/update           0.803.9 (cli-only)
rxjs                         6.5.4
typescript                   3.7.5
webpack                      4.41.6

</code></pre>

**Anything else relevant?**

I'm not using angular-cli, app is built with ngcc + ngc + rollup.

**Comment by pkozlowski-opensource** [comment] 2020-02-13 11:30
> Probably related to #32756.

Actually, this is direct duplicate of #32756 so closing it as such.

**Closed by pkozlowski-opensource** 2020-02-13 11:30 UTC
Labels: comp: core, comp: ivy
