### ISSUE TITLE
ngModel ERROR in angular2.min.js

### ISSUE THREAD

**Issue by diamo1213** [angular/angular#6987] opened 2016-02-10 12:22 UTC
ngModel does err when use https://code.angularjs.org/2.0.0-beta.3/angular2.min.js

**Comment by ericmartinezr** [comment] 2016-02-10 12:41
And what wouls be the error?........

**Comment by diamo1213** [comment] 2016-02-10 12:58
doesn't the code then:
`import {Component} from 'angular2/core';

@Component({
    selector: 'my-app',
    template: `
    <h1 [class.clicked]="isRed === true"
    (click)="showRed()">
    {{appData.firstName}}</h1>
    <input [(ngModel)]="appData.firstName" type="text">
    `,
    styleUrls: ["./src/css/app.css"]
})
export class AppComponent {
    public appData = {"firstName": "UIhui"};
    public isRed = false;
    showRed():void{this.isRed = !this.isRed;}
    
}`

**Comment by zoechi** [comment] 2016-02-10 16:03
I still can't find an error message.

**Comment by carlos-algms** [comment] 2016-02-10 22:19
+1

**Comment by ffMathy** [comment] 2016-02-11 18:22
Related to my #7006 I think.

**Comment by alexeagle** [comment] 2016-02-12 03:21
dupe of #7006

**Closed by alexeagle** 2016-02-12 03:21 UTC
