### ISSUE TITLE
Internet Explorer not always redirecting to page when you enter URL into address bar

### ISSUE THREAD

**Issue by ray-advs** [angular/angular#12100] opened 2016-10-05 21:31 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
My application is not always redirecting when I enter the URL into the address bar of Internet Explorer 11.  Sometimes it works and sometimes it does not.  I do not see this problem with the Chrome browser.

**Expected behavior**
When an user enters an URL into the address bar, my application should always redirect to the "page" associated with the URL.

**Minimal reproduction of the problem with instructions**
I cannot provide a *MINIMAL DEMO* of the problem via plnkr because I need to enter a value into the address bar for the application and that functionality is not supported by plnkr.

To reproduce, 

1)  First, get and build a starter project like the one from Angular class.
`
git clone --depth 1 https://github.com/angularclass/angular2-webpack-starter.git
`
`
cd angular2-webpack-starter  
`
`
npm install  
`
`
npm start  
`

2)  When the application is ready, then open an internet explorer 11 browser, enter the URL "http://localhost:3000" into the address bar, and press enter.

3)  Click on the hyperlink "Detail" in the page.  Then select (CTRL-A) and copy (CTRL-C) the URL from the address bar.  You should have copied "http://localhost:3000/#/detail".

4)  Click on the hyperlink "Index" in the page to return to the home page.

5)  In the internet explorer address bar, replace the entire URL by pasting (CTRL-V) the URL from step 3, and press enter.

6)  This should redirect internet explorer to the detail page but sometimes it does not.  If you do see the detail page, repeat steps 4 and 5 until you see the bug.  I usually see the error by the third repetition.

**Please tell us about your environment:**

* **Angular version:** 2.0.0

* **Browser:**  IE 11
 
* **Language:** TypeScript 2.0.3

**Comment by ericmartinezr** [comment] 2016-10-05 23:20
https://github.com/angular/angular/issues/10342#issuecomment-251504148

**Comment by chuckjaz** [comment] 2016-10-06 16:35
This is a duplicate of #10342 which was closed with the comment referenced above by @ericmartinezr .

**Closed by chuckjaz** 2016-10-06 16:35 UTC

**Comment by francosioquim** [comment] 2016-10-06 16:48
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead  
see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
My application is not always redirecting when I enter the URL into the  
address bar of Internet Explorer 11.  Sometimes it works and sometimes it  
does not.  I do not see this problem with the Chrome browser.

**Expected behavior**
When an user enters an URL into the address bar, my application should  
always redirect to the "page" associated with the URL.

**Minimal reproduction of the problem with instructions**
I cannot provide a *MINIMAL DEMO* of the problem via plnkr because I need  
to enter a value into the address bar for the application and that  
functionality is not supported by plnkr.

To reproduce,

1)  First, get and build a starter project like the one from Angular class.
`
git clone --depth 1  
https://github.com/angularclass/angular2-webpack-starter.git
`
`
cd angular2-webpack-starter
`
`
npm install
`
`
npm start
`

2)  When the application is ready, then open an internet explorer 11  
browser, enter the URL "http://localhost:3000" into the address bar, and  
press enter.

3)  Click on the hyperlink "Detail" in the page.  Then select (CTRL-A) and  
copy (CTRL-C) the URL from the address bar.  You should have  
copied "http://localhost:3000/#/detail".

4)  Click on the hyperlink "Index" in the page to return to the home page.

5)  In the internet explorer address bar, replace the entire URL by pasting  
(CTRL-V) the URL from step 3, and press enter.

6)  This should redirect internet explorer to the detail page but sometimes  
it does not.  If you do see the detail page, repeat steps 4 and 5 until you  
see the bug.  I usually see the error by the third repetition.

**Please tell us about your environment:**

* **Angular version:** 2.0.0

* **Browser:**  IE 11

* **Language:** TypeScript 2.0.3




-- 
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/angular/angular/issues/12100

**Comment by ray-advs** [comment] 2016-10-06 16:50
You are closing this as an Internet Explorer issue?  If it is an Internet Explorer issue, why does it work some of the times?

**Comment by tbosch** [comment] 2016-10-06 21:43
I do think this is an IE bug. If you enter an address that only changes the hash fragment, IE is probably not reloading the page. However, if you were on a different host (e.g. google.com) and then paste the url, IE will reload the page.

**Comment by ray-advs** [comment] 2016-10-06 22:51
Thank you for the explanation of what you think the issue in IE is.  So what you are saying is that for this to work correctly, IE is supposed to reload the page?  And that is the expected behavior Angular expects from the browser.

Is there a way that I can prove that IE is or is not reloading the page?

**Comment by tbosch** [comment] 2016-10-10 21:43
Create a simple `index.html` page that contains the following:
```
<!doctype html>
<html>
<body>
<script>console.log('loaded', Date.now());
<a href="#/detail">Detail</a>
<a href="#">Index</a>
</script>
</body>
</html>
```

Then serve it (maybe via `http-server` npm package) under `localhost`. Then retry your example above and look at the browser console to check the reload behavior.

**Comment by ray-advs** [comment] 2016-10-11 03:57
I took a modified version of your sample -- moving the anchor links out of the script tags -- and hosted it in lite-server just like in the Angular 2 quick start.

My results are that I do not get any new console log entries retrying my example above.  BUT I tried the same tests in Chrome and got the same result.  So I am still lost of how the same results causes issue in IE but not Chrome?
