### ISSUE TITLE
Weird behavior happening when CanActviate is used with Resolve 

### ISSUE THREAD

**Issue by waynechaw** [angular/angular#19796] opened 2017-10-18 23:41 UTC
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Suppose I am protecting /admin with CanActivate, and it redirect the user to /login which has a resolve.

When I directly hit /admin in the browser, I noticed the browser will temporarily go to root (/) until the resolve completes, then it will go to /login as expected.

This only happens when the user directly hits /admin in the browser.

## Expected behavior

Angular shouldnt go to root while the resolve is pending

## Minimal reproduction of the problem with instructions

I have a plunker set up: https://embed.plnkr.co/YEYoXZVZt8dtq23sHgUL/

It is exactly the same as the official angular router example, but with resolve added to the /login.

You have to download and run the app on your localhost to see it happen though.

## What is the motivation / use case for changing the behavior?

I am using CanActivate to redirect user to a route that waits for a resolve.

## Environment

<pre><code>
Most recent version

Browser:
Chrome, havent tried other browsers

**Comment by montella1507** [comment] 2017-10-19 05:13
Maybe the same problem as for me:
https://github.com/angular/angular/issues/19799

I have reinstalled node_modules 2 days ago and my project stopped working (i have there CanActivate guard and it behaves super strangely)

**Comment by henev** [comment] 2017-11-01 12:55
Same problem here.
If `/` is a private route with a guard that can be accessed only by authorized users and any unauthorized user will be redirected to `/login` - then we have an infinite loop because navigating to `/login` will go first through `/` which will redirect to `/login` and so on ... Which means that `this.router.navigate(['/login'])` will also go though `/` on the way to `/login`.

**Comment by jasonaden** [comment] 2017-11-11 00:34
Thanks for this issue. I've definitely seen this issue and worked on debugging it. I don't have a solution for it yet, but it's something that should be fixed relatively soon.

**Comment by waynechaw** [comment] 2018-04-03 21:16
how soon is relatively soon?

**Comment by waynechaw** [comment] 2018-04-03 21:16
any progress? :)

**Comment by atscott** [comment] 2020-07-06 19:09
This happens because the approach used for "redirecting" here is by calling `router.navigate` from inside the guard. The Router's navigation pipe is implemented using a `switchMap` which means that the second navigation cancels the first. When a navigation is cancelled, the router resets the browser url and in the case of an initial navigation, that will be `/`. The solution here would be to return a `UrlTree`, which acts more like a proper redirect. This feature was added in version 8 and the router tutorial has since been updated to return `UrlTree` as well.

Closing this as the documentation has been updated to recommend the correct solution here and the other path is working as intended.

**Closed by atscott** 2020-07-06 19:09 UTC
Labels: comp: router, freq2: medium, severity3: broken, type: bug/fix
