### ISSUE TITLE
Clarify + usage

### ISSUE THREAD

**Issue by sdavids** [angular/angular#36373] opened 2020-04-01 14:54 UTC
# 📚 Docs or angular.io bug report

### Description

The documentation is aimed at newcomers to Angular/JavaScript--so please clarify why `+` is used.

### What's the affected URL?
https://angular.io/start/start-routing#using-route-information

```javascript
ngOnInit() {
  this.route.paramMap.subscribe(params => {
    this.product = products[+params.get('productId')];
  });
}
```

`products[+params.get('productId')]`

vs.

`products[params.get('productId')]`

**Comment by AnthonyLenglet** [comment] 2020-04-01 15:00
Duplicate of https://github.com/angular/angular/issues/33001

**Closed** 2020-04-07 20:24 UTC
Labels: comp: docs
