### ISSUE TITLE
Inconsistent behavior of input binding to object property returned by async pipe

### ISSUE THREAD

**Issue by jotatoledo** [angular/angular#23933] opened 2018-05-16 10:59 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ X ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
Currently, binding expressions of the form `(objectStream$ | async).fooProperty` to an input property will trigger change detection on the related child component _more often_ than expressions of the form `fooProperty$ | async` or `object.fooProperty` (sync).

With _more often_ I mean situations when the source object has changed, but the value of the bounded property has not.

## Expected behavior

Change detection behavior of components whose properties were bounded with `(objectStream$ | async).fooProperty` or `fooProperty$ | async` should be the same.

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/angular-async-prop-issue

If you click on the next button, change detection will be run for the components whose properties were bonded with a `(source$ | async).property`, but not the ones bounded with `property$ | async` expressions

## Environment

Angular version: 6.x.x

Browser:
- [x] Chrome (desktop) version 66.0.3359.181 
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by jotatoledo** [comment] 2018-05-16 15:06
@ghetolay I updated the blitz with a 3rd expression binding that makes your statement

> So in the end the binding on the name property will be updated when either name or the object holding that property changes.

not entirely correct (if I understood it correctly).

**Comment by mlc-mlapis** [comment] 2018-05-16 15:35
@jotatoledo ... **OR** `the object holding that property changes` is the key because it is impossible to suppose that Angular would check the deep structure of the object to find out if something has been changed (because of performance point of view).

... if we still suppose that the behavior should be the same in both cases and if we still use immutable principle when updating the object.

**Comment by ghetolay** [comment] 2018-05-16 16:10
@jotatoledo I've made a stackblitz to explain it better : https://stackblitz.com/edit/angular-async-prop-issue-raxthx?file=src/app/app.component.ts

So if any of the checkbox is checked you'll get an update on the child component. While the expected behavior is to get updated only when a new name is set no matter if the object was mutated or is a new one

**Comment by mlc-mlapis** [comment] 2018-05-16 21:26
@ghetolay ... maybe it'd be good to also mention that if a child'd be updated only on a real change in `name` value then `(data$ | async).name` would also mean that it's not possible to use `OnPush` strategy on that child because of no new object reference.

**Comment by ghetolay** [comment] 2018-05-17 10:06
`OnPush` mostly works it just get triggered more often than it should, when a new object but with the same property (===) is emitted. In my stackblitz it means a new `Foo` object with same `name`.

**Comment by mhevery** [comment] 2018-05-24 22:33
closing as working as intended.

**Closed by mhevery** 2018-05-24 22:33 UTC
Labels: comp: common, comp: core & compiler

**Comment by jotatoledo** [comment] 2018-05-28 15:38
@mhevery hey Misko, would you mind giving some further explanations to why is this the correct behavior? I always thought of input properties as a stream that "emits" (triggers cd) whenever a new value flows through it, no matter where the value comes from. 

Any further help would be greatly appreciated.

**Comment by gregbown** [comment] 2018-06-04 22:44
So the weird thing is that if you change the top stackblitz to rxjs: 5.6.0-forward-compat.5 they all work.  I notice this issue only after I went through the rxjs update, some of my async pipes worked and others failed. the store would update but the async subscription/@Input would be null on in ngOnInit

**Comment by jotatoledo** [comment] 2018-06-08 19:17
UP, still waiting for some clarification.
