### ISSUE TITLE
Ivy : Build fails when component is injecting service which is declared in index.d.ts file

### ISSUE THREAD

**Issue by prakulgupta** [angular/angular#33488] opened 2019-10-30 08:29 UTC
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

I'm injecting a service in a component which is declared in an index.d.ts file. The services in this file are written in angular 1. This thing works in normal & AOT mode. When I'm converting this component to web component, ngx-build-plus is failing with below errors - 

![image](https://user-images.githubusercontent.com/6064632/67840982-149d7e80-fb1d-11e9-8c6f-93ded207ea08.png)

Errors are like -

1. Cannot find module
2. Cannot find namespace 'angular'
3. Duplicate identifier

Do we have a way to support this thing in web components ? 

Versions I'm using 
"@angular/core": "8.2.5",
"@angular/elements": "8.2.5",
"ngx-build-plus": "8.1.5", 
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by alxhub** [comment] 2019-10-31 22:18
Hi @prakulgupta,

We would be happy to investigate this, but we'll need a working reproduction in the form of a Stackblitz or a Github repo demonstrating the problem. Otherwise it's impossible for us to track down this issue.

Thanks,
Alex

**Comment by prakulgupta** [comment] 2019-11-01 07:17
The sample project is here  https://github.com/prakulgupta/webComponent
Steps -
1. npm i 
2. npm run build:ce

In this sample project I'm trying to convert a component into web component and using Ivy compiler. The web components creation works absolutely fine but as I injects a service which is coming from index.d.ts file, then on-wards build starts to throw errors. What I'm understanding is compiler is looking for definition of these services but it's not present as it's just a d.ts file. 

The above scenario of using services through index.d.ts works good, in normal case when I build project in AOT & JIT mode and hosts this application inside another parent application which contains definition of these services already.

So, I'm looking for a way that compiler understands that this index.d.ts shouldn't be considered while bundling and it should created a bundle.

**Comment by IgorMinar** [comment] 2019-11-09 01:15
@prakal please update your project to the latest `@next` version of @angular/core and @angular/cli.  

you can run `ng update @angular/core @angular/cli --next` to do that.

**Comment by prakulgupta** [comment] 2019-11-15 05:24
@IgorMinar - Updated to @next version but getting the same set of errors. Compilation is failing
![image](https://user-images.githubusercontent.com/6064632/68918958-4148cb80-0796-11ea-824a-8125d3eecc84.png)

**Comment by alxhub** [comment] 2019-11-20 00:03
Where is `IFeatureFlagConfiguration` defined in your repro? The `index.d.ts` file in question is structured like:

```
export interface IFeatureFlagConfiguration {...}
export declare class FeatureFlagAngular1Module {...}
import { IFeatureFlagConfiguration } from "../interface/IFeatureFlagConfiguration";
export declare class FeatureFlagService {...}
export declare class FeatureFlagServiceProvider implements angular.IServiceProvider {...}
```

That is, it both declares `IFeatureFlagConfiguration` as an interface, and then attempts to import it from `../interface/IFeatureFlagConfiguration`, which is a path that doesn't exist in the repro repository. It also uses `angular` in the global scope, and no typings definition seems to be specified.

Upon examining the code, the errors as reported by TypeScript/ngc are 100% accurate and correct. They are indicating real problems with your code, not bugs in the compiler. I'm going to close this issue as WAI - feel free to reopen with a correct reproduction.

**Closed by alxhub** 2019-11-20 00:03 UTC
Labels: comp: compiler, freq2: medium, severity3: broken, state: Needs repro, type: bug/fix
