### ISSUE TITLE
docs: the DI framework should throws an error

### ISSUE THREAD

**Issue by ukyo** [angular/angular#28748] opened 2019-02-15 04:41 UTC
# 📚 Docs or angular.io bug report

### Description

https://angular.io/guide/dependency-injection-in-action#qualify-dependency-lookup-with-parameter-decorators

This document explains "If no provider is found in the root injector, the DI framework returns null to the constructor." on line 154 but it should throw an error. It says "throw an error" in the following text.

### What's the affected URL?**
 https://angular.io/guide/dependency-injection-in-action#qualify-dependency-lookup-with-parameter-decorators

**Comment by jinbeomhong** [comment] 2019-02-15 09:57
Original documents were written correctly, but some documents including DI in action document were poorly re-written at https://github.com/angular/angular/pull/21915 . This PR was a big sudden change. Now, we can't track the errors on document easily. And https://github.com/angular/angular/issues/28508 issue is also caused by the PR.

**Comment by brandonroberts** [comment] 2019-02-25 14:54
Fixed via #28753

**Closed by brandonroberts** 2019-02-25 14:54 UTC
Labels: comp: docs
