### ISSUE TITLE
CSS Class Odd Behaviour

### ISSUE THREAD

**Issue by TiagoBraga39** [angular/angular#3192] opened 2015-07-22 13:54 UTC
Hi all!

I came accross and odd behaviour on binding my css classes to HTML elements.
Am I supposed to use an expression on [class] property?

Example:
![image](https://cloud.githubusercontent.com/assets/8090726/8826875/5c9baeb6-3081-11e5-8d4e-58d923b653d2.png)

HTML Element:
![image](https://cloud.githubusercontent.com/assets/8090726/8826869/517f8db8-3081-11e5-8635-14df64e69cea.png)

---

<b>The css class properties are not visible on the HTML (background color).</b>

As you can see, I used an expression to bind the class of the element.
But the output has hyphens instead of Capital Letters.

The expected output of the class:
MenuItemBlueColor

By the way, the class exists and the expected output would be the background color.

Best regards,
Tiago Braga

**Comment by pkozlowski-opensource** [comment] 2015-07-22 14:00
Duplicate of https://github.com/angular/angular/issues/3001 - please add your use-case in there.

**Closed by pkozlowski-opensource** 2015-07-22 14:00 UTC

**Comment by TiagoBraga39** [comment] 2015-07-22 14:04
@pkozlowski-opensource  Thank you! I couldn't find anything about this before.

:+1:
