### ISSUE TITLE
ivy: failed to create dynamic component

### ISSUE THREAD

**Issue by mattlewis92** [angular/angular#34152] opened 2019-11-29 12:50 UTC
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/core

### Is this a regression?

Yes, it worked fine in v8

### Description

Trying to create a dynamic component fails to work when calling `insert` on a `ViewContainerRef` with a component instance's `hostView`

## 🔬 Minimal Reproduction
```
git clone https://github.com/mattlewis92/ivy-dynamic-component-bug.git
cd ivy-dynamic-component-bug
npm i
npm start -- --open
```

then click the "click me" button and you'll see the error thrown

## 🔥 Exception or Error
<pre><code>
ERROR Error: ASSERTION ERROR: index must be positive
    at throwError (core.js:1229)
    at assertGreaterThan (core.js:1213)
    at ViewContainerRef_._adjustIndex (core.js:17341)
    at ViewContainerRef_.insert (core.js:17264)
    at ViewContainerRef_.move (core.js:17288)
    at ViewContainerRef_.insert (core.js:17264)
    at SafeSubscriber._next (modal-keeper.component.ts:24)
    at SafeSubscriber.__tryOrUnsub (Subscriber.js:183)
    at SafeSubscriber.next (Subscriber.js:122)
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.0.0-rc.4
Node: 12.10.0
OS: darwin x64

Angular: 9.0.0-rc.4
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-rc.4
@angular-devkit/build-angular     0.900.0-rc.4
@angular-devkit/build-optimizer   0.900.0-rc.4
@angular-devkit/build-webpack     0.900.0-rc.4
@angular-devkit/core              9.0.0-rc.4
@angular-devkit/schematics        9.0.0-rc.4
@ngtools/webpack                  9.0.0-rc.4
@schematics/angular               9.0.0-rc.4
@schematics/update                0.900.0-rc.4
rxjs                              6.5.3
typescript                        3.6.4
webpack                           4.41.2
</code></pre>

**Anything else relevant?**
nope

**Comment by pkozlowski-opensource** [comment] 2019-11-29 15:25
@mattlewis92 thnx for the reproduction - this is a regression that we've introduced in rc.4 and the fix will be trivial. Having said this, you are hitting this particular issue because  you are attaching your component host view to _two_ different view containers. As the result there is more processing happening (ex. a view is attached to the first container which results in attaching things to the DOM, modifying internal data structures etc.). Then, a given view is attached to the _second_ container so the DOM needs to be cleared, internal data structures cleared etc. just to do the same work ... again.

So, the suggestion here would be to do:

`componentFactory.create(injector)`

instead of:

`const component = this.container.createComponent(componentFactory);`

Documentation here: https://angular.io/api/core/ComponentFactory

Again, this is clearly a bug that we will fix asap, but the above is just a suggestion to work-around this particular bug right now _and_ speed up processing as a bonus!

**Comment by mattlewis92** [comment] 2019-11-29 16:31
Hey @pkozlowski-opensource, thanks a lot for getting back to me so quickly on this! 

We're actually already using `const component = componentFactory.create(injector)` for all new code, it's just that we have _a lot_ of legacy code still using `const component = this.container.createComponent(componentFactory);` so migrating and testing all of that will take a lot of time 😄

**Comment by pkozlowski-opensource** [comment] 2019-11-29 21:28
Marking it as a release blocker since it turned out to be a scenario (moving views between containers) that we don't support properly in ivy.

**Closed** 2019-12-04 00:08 UTC
Labels: comp: ivy, severity5: ivy-compat, state: has PR, type: bug/fix
