### ISSUE TITLE
ng-content handling in dynamic components

### ISSUE THREAD

**Issue by iskathi** [angular/angular#27406] opened 2018-12-03 06:59 UTC
# 🚀 feature request

### Relevant Package

 @angular/core

### Description
 When components having ng-content in their templates are created dynamically, nested components are not handled

```
@Component({
  selector: 'test-a',
  template: `<ng-content></ng-content>`,
})
export class A  {
}
---
@Component({
  selector: 'test-b',
  template: `<ng-content></ng-content>`,
})
export class B  {
}
---
  const el = window.document.getElementById('test');
  const elA = window.document.createElement('test-a');
  const elB = window.document.createElement('test-b');
  const elC = window.document.createElement('hello');

  elC.setAttribute('name', '{{ name }}')
  elC.innerText = 'placeholder';
  elB.appendChild(elC);
  elA.appendChild(elB);
  el.appendChild(elA);

const node = Array.from(el.childNodes)[0];

const resolver = injector.get(ComponentFactoryResolver);
const factory = resolver.resolveComponentFactory(A);
const ngComponent = factory.create(injector, [ Array.from(node.childNodes) ], node);
appRef.attachView(ngComponent.hostView);
```

```
<div _ngcontent-c112="" id="test">
  <test-a ng-version="7.0.1">
    <test-b>
      <hello name="{{ name }}">placeholder</hello>
    </test-b>
  </test-a>
</div>
```
Full sample: https://stackblitz.com/edit/angular-n5yh1d

### Describe the solution you'd like
 Since projetable nodes are passed, nested components should be resolved in factory.create

**Comment by trotyl** [comment] 2018-12-03 08:55
Duplicate of https://github.com/angular/angular/issues/4946

**Comment by mhevery** [comment] 2018-12-04 23:34
Thanks for reporting this issue. However this issue is a duplicate of an existing issue #4946. Please subscribe to that issue for future updates.

**Closed** 2018-12-04 23:35 UTC
Labels: comp: core & compiler
