### ISSUE TITLE
Default to static: false

### ISSUE THREAD

**Issue by pauldraper** [angular/angular#30809] opened 2019-06-02 22:22 UTC
If I understand correctly,

In Angular 7, `@ContentChild`, `@ContentChildren`, `@ViewChild`, and `@ViewChildren` are "dynamic".

In Angular 8, `@ContentChildren` and `@ViewChildren` are dynamic. `@ContentChild` and `@ViewChild` must be explicitly specified as static or dynamic.

In Angular 9, `@ContentChild`, `@ContentChildren`, `@ViewChild`, and `@ViewChildren` are dynamic. This optionally can be overriden for `@ContentChild` and `@ViewChild`.

This makes Angular 8 stick out like a sore thumb.

---

**Feature request:** All of the query selectors should default to dynamic, as they have in the past, and as they will in the future.

If I could upgrade from 7 to 9 without rewriting half of my queries, upgrading from 7 to 8 shouldn't somehow introduce even *more* friction and code churn.

**Comment by trotyl** [comment] 2019-06-03 02:45
Duplicate of https://github.com/angular/angular/issues/30751

**Comment by devversion** [comment] 2019-06-03 11:29
Angular 7: Timing for `ContentChild` and `ViewChild` is determined automatically (based on what the query selects). So the query can be either dynamic or static.

Angular 8: Timing for `ContentChild` and `ViewChild` needs to be specified explicitly. This is part of the migration phase and is necessary because the automatic timing detection logic is _deprecated_ and in V9+ queries will be by _dynamic_ by default.

Angular 9: Automatic timing detection logic is no longer available. Default is `static: false` and can be omitted. See [here](https://angular.io/guide/static-query-migration#why-do-i-have-to-specify-static-false-isnt-that-the-default)

---

> If I could upgrade from 7 to 9 without rewriting half of my queries, upgrading from 7 to 8 shouldn't somehow introduce even more friction and code churn.

based on what I wrote above.. this is not true because in Angular 7 omitting the `static` flag has different semantics as in Angular 9+. [Read more about this here](https://angular.io/guide/static-query-migration#why-do-i-have-to-specify-static-false-isnt-that-the-default)

**Closed by devversion** 2019-06-03 11:29 UTC
