### ISSUE TITLE
error NG6002 shows a problem in an import, but there is no other error detailing what is wrong with the module

### ISSUE THREAD

**Issue by luizfbicalho** [angular/angular#50792] opened 2023-06-21 13:32 UTC
### Which @angular/* package(s) are relevant/related to the feature request?

compiler

### Description

```
ERROR in src/app/corretor/corretor.module.ts:27:36 - error NG6002: This import contains errors, which may affect components that depend on this NgModule.

27   imports: [CommonModule, routing, SharedModule, AcoesAprovacaoModule],
                                      ~~~~~~~~~~~~
Error: src/app/corretor/corretor.module.ts:27:36 - error NG6002: This import contains errors, which may affect components that depend on this NgModule.

27   imports: [CommonModule, routing, SharedModule, AcoesAprovacaoModule],
                                      ~~~~~~~~~~~~

    at addError (C:\ProjetosGIT\SA\NgSa\node_modules\@ngtools\webpack\src\ivy\diagnostics.js:31:29)
    at C:\ProjetosGIT\SA\NgSa\node_modules\@ngtools\webpack\src\ivy\diagnostics.js:17:17
    at C:\ProjetosGIT\SA\NgSa\node_modules\@ngtools\webpack\src\ivy\plugin.js:408:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

We got this error after upgrade to angular 16, the problem is that the error doesn't show any information on what is the error

### Proposed solution

error NG6002 should display more information on what is causing this problem in the module import

### Alternatives considered

one alternative is to have another error first that show the error in the module

**Comment by Cassinotte** [comment] 2023-06-21 13:54
I am also having a similar problem... there is no detail about the root cause... just a generic error

**Comment by garrettld** [comment] 2023-06-28 22:04
Could you share a reproduction of this problem? Without being able to see the import that is reported by NG6002, this isn't very actionable.

**Comment by luizfbicalho** [comment] 2023-06-30 12:34
I don't think that I was clear, my main issue is the message that doesn't help with the error. 

Maybe just the error in the module declaration of what is wrong and not this erros in the module import averywhere

My  module is to complex to show here, but basically I had a component from another module added in this module, when I imported the correct module it worked fine

**Comment by garrettld** [comment] 2023-06-30 16:33
I understand, but NG6002 is working as intended here. What's supposed to happen is that as the compiler inspects your modules, the "real" error is found in your SharedModule (for example), and that error is reported. Then, later, SomeOtherModule that imports SharedModule is inspected and the compiler reports NG6002 because SomeOtherModule is possibly broken because of the transitive dependency.

That first error isn't being logged for you for some reason, and I think that's the bug that needs fixing. If we fix that, then you'd see the "real" error as well as NG6002, and you'd have the information you're looking for.

**Comment by ajay20015** [comment] 2023-08-01 17:05
Hi @luizfbicalho @garrettld ,
You solved that issue..?
right now I am facing that issue... if you figure out that issue please suggestion for me to solve that issue...
Thank You...!

**Comment by luizfbicalho** [comment] 2023-08-01 17:31
> Hi @luizfbicalho @garrettld , You solved that issue..? right now I am facing that issue... if you figure out that issue please suggestion for me to solve that issue... Thank You...!

I solved the problem, with the help of other developer, he saw an error in the module declaration, a problem with other modules in the import, it's not clear but my help is this, forget this error and aim the other errors in your code, eventually you'll find the one

**Comment by luizfbicalho** [comment] 2023-08-01 17:51
is there any errors in the shared module definition? try to comment some part of it to see if it works

**Comment by ajay20015** [comment] 2023-08-02 11:50
Hi @luizfbicalho,
I solved that issue,

I Upgrade angular version 11 to angular 16, so some packages are deprecated, I am Used that deprecated package in sharedModule. so angular not compiling that package, its throw error in sharedModule importing modules.

its one line error its throw nested importing module.

If any one facing this issue please check your shared module include any deprecated packages. That main issue for my project after updating. 

Thank You..!

**Comment by Razorshnegax018** [comment] 2023-08-02 23:06
Hello, I'm a new dev learning angular having this issue in my tutorial app. I'm trying to import a feature module into my root module but I'm getting this error which I have never seen before. My feature module works fine with absolutely no errors.I'm using angular and angular material 16.1, alongside the latest versions of other packages.

**Comment by Razorshnegax018** [comment] 2023-08-02 23:09
Nevermind, I found the issue: I had imported components into multiple modules

**Comment by JeanMeche** [comment] 2023-09-16 19:34
Without a repro this isn't actionable so I'll close this.

Feel free to reopen if you are able to provide a repro 👍

**Closed by JeanMeche** 2023-09-16 19:34 UTC
Labels: needs reproduction, area: compiler
