### ISSUE TITLE
Simple Array string interpolation doesn't work without another neighboring string interpolation

### ISSUE THREAD

**Issue by fsciuti** [angular/angular#35977] opened 2020-03-09 23:17 UTC
# 🐞 bug report

### Description

The binding doesn't work properly when I use a _string interpolation_ to interpolate a simple array.
But if I use an adjacent (or neighboring) _string interpolation_ with same array (with a pipe or another behaviour)...it's work!

## 🔬 Minimal Reproduction
I create a minimal reproduction of the issue with a lot of cases:
[Stackblitz Demo](https://stackblitz.com/edit/angular-u3ae1a)
## 🌍  Your Environment

**Anything else relevant?**
This problem is found on Angular 8 and 9.

**Comment by petebacondarwin** [comment] 2020-03-10 08:44
@fsciuti - this is actually working as expected.

In the case that does not get updated Angular is watching the array object itself for changes (not its internals). Since you are only pushing a value into the array, the identity of the array is not changing and so change detection is not triggered.

In the other cases that you mention the `{{ items | json }}` expression is being evaluated on every change detection cycle because it is marked as `pure: false`, which means that it is re-computed whether or not its inputs (i.e. `items`) have changed. When this is in the same block of text (i.e. no HTML element between them) the whole block gets re-rendered together, which causes the `{{items}}` interpolation to be re-rendered, even though it would not have triggered change detection itself.

One way around this is to avoid mutating arrays (or objects) if you are binding to them as a single object. Generally this is quite uncommon for interpolations anyway. Instead replace the array with a new one that contains the original items plus the new one. For example:

```
setTimeout(() => this.items = [...this.items, u], 3000);
```

**Comment by petebacondarwin** [comment] 2020-03-10 08:45
Closing as this is how Angular works and is not a bug.

**Closed by petebacondarwin** 2020-03-10 08:45 UTC
Labels: comp: core, flag: can be closed?, state: works-as-expected
