### ISSUE TITLE
router.navigate() not working inside HttpInterceptor while route resolver is running

### ISSUE THREAD

**Issue by chrisschaetzlein** [angular/angular#21149] opened 2017-12-22 10:12 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
- A route resolver fetches data from a server using HttpClient
- The server sends an error (401 for instance)
- A HttpInterceptor that catches the error tries to navigate the user to another route
- router.navigate() won't navigate, it silently discards the navigation request

## Expected behavior
- router.navigate() should cancel the running navigation and start navigating to the given route, OR
- router.navigate() should throw an error, stating that a route navigation is already running. There should then be a way to cancel the running navigation.

## Minimal reproduction of the problem with instructions

routes.ts:
```
{ 
  path: ':id',
  component: EditComponent,
  resolve: {
    user: UserResolver
  }
}
```

auth-interceptor.ts:
```
@Injectable()
export class AuthenticationInterceptor implements HttpInterceptor {
    constructor(private router: Router) {}
    intercept(request: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
        return next.handle(request).do(event => {
        }, error => {
            if (error instanceof HttpErrorResponse && error.status === 401) {
                this.router.navigate([ '/login' ]);
            }
            return error;
        });
    }
}
```

user-resolver.ts:
```
@Injectable()
export class EditResolver implements Resolve<UserModel[]> {
    constructor(private userService: UserService, private router: Router) {}
    public resolve(route: ActivatedRouteSnapshot, state: RouterStateSnapshot): Observable<any> {
        return this.userService.getById(+route.params.id);
    }
}
```

user-service.ts:
```
@Injectable()
export class UserService {
    constructor(private http: HttpClient) {}
    public getById(userId: Number): Observable<UserModel> {
        return this.http.get('/api/1.0/users/' + userId);
    }
}
```

1. Return a 401 error from the server
2. The HttpInterceptor catches the error and executes this.router.navigate
3. Nothing happens

## What is the motivation / use case for changing the behavior?
If a resolver fails fetching data, the app should be able to redirect the user to another route (a login prompt for instance)

## Environment

- Angular version: 5.1.1
- Angular CLI 1.6.1

**Comment by jasonaden** [comment] 2018-01-02 14:57
Sounds like a duplicate of https://github.com/angular/angular/issues/17023. Basically the problem is the router has a hard time with redirects while navigation is already executing.

If that's not the case, please create a new issue with a running example such as on [StackBlitz](http://stackblitz.com).

**Closed by jasonaden** 2018-01-02 14:57 UTC
Labels: comp: router

**Comment by hyoda** [comment] 2018-02-02 21:02
this solution saved my life... 

in that case. it works for me.

import { Injectable } from '@angular/core';
import { HttpEvent, HttpErrorResponse, HttpInterceptor, HttpHandler, HttpRequest } from '@angular/common/http';
import { Router } from '@angular/router';
import { Observable } from 'rxjs/Observable';
import 'rxjs/add/observable/throw';
import 'rxjs/add/operator/catch';

@Injectable()
export class ErrorInterceptor implements HttpInterceptor {
  constructor(private router: Router) {}

  intercept(req: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
    return next.handle(req)**.catch(
      (err: HttpErrorResponse) => {
        if (this.router.url !== '/login' && err.status === 401) {
          this.router.navigate(['/logout']);
        }
        return Observable.throw(err);
      }
    );**
  }
}

https://stackoverflow.com/questions/47098386/using-router-in-services-in-angular-4

**Comment by dkreider** [comment] 2018-11-30 16:33
You can also use [`Router.navigateByUrl(link)`](https://angular.io/api/router/Router#navigatebyurl) like this:

`this.router.navigateByUrl('/login');`
