### ISSUE TITLE
Input control value change modifies a succeeding control value when control binding to an array

### ISSUE THREAD

**Issue by RaleS** [angular/angular#13116] opened 2016-11-28 11:47 UTC
```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
A change of value of a date input control (that is created using ngFor and that is bound to an item in an array) modifies the value of the succeeding control.

**Expected behavior**
A modification of date input control value should only be applied to the selected date input control.

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/5ZdUsGolUk5AAYgJ9qgP?p=preview

- Steps to reproduce -
(Chrome)
1. Use plnkr link, and wait for the app to load.
2. Click on the up button next to the first date input control to modify it.
3. Notice that both first and second date input control values have changed. Also notice that the focus has changed to the second date input control.
4. Click once again on the up button next to the first date input control.
5. Notice that this time only first date input control value has changed.

(Firefox)
1. Use plnkr link, and wait for the app to load.
2. Click the first date input control to set focus, and press Backspace key.
3. Notice that both first and second date input control value have changed. Also notice that the focus has changed to the second date input control.
4. Click once again on the first date input control to set focus,  and press Backspace key.
5. Notice that this time only first date input control value has changed.

(Edge)
1. Use plnkr link, and wait for the app to load.
2. Click the first date input control to select new date value, and press check-mark button to apply.
3. Notice that both first and second date input control value have changed.
4. Click once again on the first date input control to select new date value, and press check-mark button to apply.
5. Notice that this time only first date input control value has changed.

**Please tell us about your environment:**
Windows 10

* **Angular version:** 2.2.3

* **Browser:** Chrome 54, Edge 38/14, Edge 39/15, Firefox 50
 
* **Language:** TypeScript 2.0.3

* **Node (for AoT issues):** 6.6.0

**Comment by DzmitryShylovich** [comment] 2016-11-28 12:34
You need to use `trackBy` when u have inputs inside `ngFor` http://plnkr.co/edit/g4R8bjsRcccmNmV83aIN?p=preview

**Comment by pkozlowski-opensource** [comment] 2016-11-28 13:21
This is a duplicate of  #10423 indeed, thnx @DzmitryShylovich

**Closed by pkozlowski-opensource** 2016-11-28 13:21 UTC
