### ISSUE TITLE
Strong typing in ng-template with let-field

### ISSUE THREAD

**Issue by dylanvdmerwe** [angular/angular#40716] opened 2021-02-05 09:15 UTC
# 🚀 feature request

### Relevant Package

This feature request is for language service.

### Description
We have templates that use `let-data` and `let-field` but there is no typing information within the actual template. This could be a cause for errors if fields change or if any refactoring happens. 

For example:
![image](https://user-images.githubusercontent.com/2852839/107013600-3b784500-67a3-11eb-9748-ba4b4afda745.png)

### Describe the solution you'd like
It would be great if somewhere we could specify the type that `field` should be in this example. Or if language services can infer it. 

For example:
![image](https://user-images.githubusercontent.com/2852839/107013725-65316c00-67a3-11eb-987a-01a3f88c5a05.png)

**Comment by Airblader** [comment] 2021-02-05 17:01
Duplicate of #28731

**Comment by atscott** [comment] 2021-02-05 17:24
Closing as duplicate fo #28731

**Closed by atscott** 2021-02-05 17:24 UTC
