### ISSUE TITLE
Router: Add RouterStateSnapshot to canLoad guard

### ISSUE THREAD

**Issue by brandonroberts** [angular/angular#10584] opened 2016-08-09 02:29 UTC
**I'm submitting a ...**  (check one with "x")

```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

The `canLoad` guard is called with the `Route` as the only argument.

**Expected/desired behavior**

The `RouterStateSnapshot` of the future state is provided so the URL can be stored. The use case would be redirecting the user to a login page, then returning to the previously attempted URL after logging in.

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
- **Angular version:** 2.0.0-rc.X
- **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
- **Language:** [all | TypeScript X.X | ES6/7 | ES5] 

cc: @vsavkin

**Comment by kdorion** [comment] 2016-10-20 15:52
Is there any way to keep the attempted url using a canLoad guard currently? (I don't want to use the canActivate guard to prevent module loading)

**Comment by brandonroberts** [comment] 2016-10-20 23:32
You should be able to use the `router.events` Observable to get the last event which will contain the attempted URL

**Comment by kdorion** [comment] 2016-10-24 13:51
@brandonroberts I can't subscribe to the router events in the canLoad since it is asynchronous right ? CanLoad returns a value before the observable return it's value.

**Comment by willshowell** [comment] 2017-01-23 17:33
@kdorion, I know I'm late, but you ought to be able to subscribe to `router.events` in your root app component. Then use a app-wide service to store the attempted URL until your login flow needs to apply the redirect.

**Comment by kdorion** [comment] 2017-01-25 19:52
@willshowell Yes this is what I'm already doing, I found out about that couple of days after my comments :+1:

**Comment by DzmitryShylovich** [comment] 2017-02-03 19:16
@pkozlowski-opensource duplicate of https://github.com/angular/angular/issues/12411#issuecomment-257411355

**Closed** 2017-02-04 10:11 UTC
Labels: comp: router, freq2: medium, type: feature
