### ISSUE TITLE
i18n: remove i18n markup by default

### ISSUE THREAD

**Issue by vicb** [angular/angular#15762] opened 2017-04-04 16:36 UTC
If the templates are authored in `en` then you will no translate the app for the `en` locale.

However when the app is not translated, the i18n specific markup (`i18n` attributes, ... ) is not removed.

The markup should always be removed even when the application is not translated.

**Comment by ocombe** [comment] 2017-04-19 13:23
Duplicate of #11042?

**Closed** 2017-07-05 16:52 UTC
Labels: comp: i18n, type: feature
