### ISSUE TITLE
[dev mode] ngFor with slice pipe throws

### ISSUE THREAD

**Issue by cexbrayat** [angular/angular#5948] opened 2015-12-16 09:27 UTC
Chaining `ngFor` with a `slice` pipe throws errors.
I just realized that now that the dev mode is enabled by default (alpha-55).

````TypeScript
@Component({
  selector: 'users-cmp',
  template: `<div *ngFor="#user of users | slice:0:2">{{user.name}}</div>`
})
export class UsersCmp {
  users: Array<any> = [
    {name: 'Cedric},
    {name: 'Agnes'},
    {name: 'Cyril'}
  ];
}
````

Gives  `Expression 'users | slice:0:2 in UsersCmp@0:5' has changed after it was checked`.
Runtime works (despite the errors), but unit tests are failing.

Related to #5941 I think.

**Comment by pkozlowski-opensource** [comment] 2015-12-16 09:30
Duplicate of https://github.com/angular/angular/issues/5918

**Closed by pkozlowski-opensource** 2015-12-16 09:30 UTC
