### ISSUE TITLE
Inconsistency between Properties syntax and Events

### ISSUE THREAD

**Issue by typotter** [angular/angular#3371] opened 2015-07-29 21:38 UTC
For Properties:
1. If I define property  properties: const [ 'propertyName']  - it's fine, it will translate to 'property-name' in html
2. I can also do [ 'internalName : property-name' ] - which is fine as well.
3. Strange (but kind of ok behavior) is I can do even [ 'internalName : propertyName' ], which will autotranslate to 'property-name'

The problem is for events option (2) is broken. I.E. with  
events: const ['eventCtrl : event-name'] you will not be able to (event-name)="callThing()"

**Comment by gdi2290** [comment] 2015-07-29 23:09
same for lifecycle hooks. Here's an overloaded example of the directive api currently (might be a few mistakes or typos)

```typescript
@Directive({
  selector: 'input:not([type=checkbox])[control],textarea[control]',
  properties: [ 'sameName', 'directiveProp: elProp | async' ],
  events: [ 'status-change' ],
  lifecycle: [ LifecycleEvent.onChange, LifecycleEvent.onDestroy ],
  host: {
    // listeners
    '(change)': 'onChange($event.target.value)',
    '(window:resize)': 'onResize($event)',
    // action
    '@emitFocus': 'focus()',
    // prop
    '[value]': 'hostValue',
    // attr
    'role': 'button'
  },
  hostInjector: [ bind(ShadowDomStrategy).toClass(NativeShadowDomStrategy) ],
  viewInjector: [ Greeter ],
  compileChildren: true
})
class MyDirective {
  elProp: any;
  sameName: any;
  hostValue: any = null;
  emitFocus:    Observable = new EventEmitter();
  statusChange: Observable = new EventEmitter();
  
  constructor(private el: ElementRef, private greeter: Greeter) {
  
  }
 
  focus() {
    this.emitFocus.next();
  }
  // conflicts
  onChange() {
    // do two things including lifecycle
  }
  onResize() {
    // resize logic
  }
  onComplete() {
    this.statusChange.next('completed');
  }
  onDestroy() {
    // clean up
  }
}
```
that's not including the shadow dom change to `@View` or the router's way of handling lifecycle methods with decorators (which I prefer). There's also the question of why can't you convert the event listeners callbacks to an EventEmitter. For example, [angular2-webpack-starter/src/app/components/rxjs-examples/draggable_div/drag_element.ts#L9](https://github.com/angular-class/angular2-webpack-starter/blob/efc6d54ac79448c73b5dda75e383a62deefc0805/src/app/components/rxjs-examples/draggable_div/drag_element.ts#L9)

**Comment by mhevery** [comment] 2015-08-05 17:59
I think this works as intended. I think ` [ 'internalName : property-name' ]` can be used as `[property--name]` notice the double dash.

**Comment by mhevery** [comment] 2015-08-19 17:52
Closing as dup of https://github.com/angular/angular/issues/2600

**Closed by mhevery** 2015-08-19 17:52 UTC
