### ISSUE TITLE
ng-content childs initiliazed even without any render points

### ISSUE THREAD

**Issue by mhamri** [angular/angular#40483] opened 2021-01-19 16:38 UTC
# 🐞 bug report

### Affected Package
tested on ~ 10, 11

### Is this a regression?
not sure 

### Description

```TSX
import { Component, OnInit } from "@angular/core";

@Component({
  selector: "app-dummy-component",
  template: `
    <ng-template>
      <ng-content></ng-content>
    </ng-template>
  `
})
export class DummyComponentComponent implements OnInit {
  constructor() {}

  ngOnInit() {}
}

```
and if the usage is like this

```HTML
<app-dummy-component>

	<app-dummy-child></app-dummy-child>

</app-dummy-component>
```
given this code where there is no place to render ng-template, still, the `app-dummy-child` is being instantiated. this can cause redundant API call when the content isn't rendered yet or wait for some user interaction. we can see that `app-dummy-child` is instantiated and also its `ngOnInit` method is being called. 

any workaround method is welcomed 

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-ivy-juzx3b?file=src/app/dummy-component/dummy-component.component.ts

## 🔥 Exception or Error

ngOnInit on child items is being called. 

## 🌍  Your Environment

**Angular Version:**
<pre>Angular CLI: 11.0.5
Node: 14.15.1
OS: win32 x64

Angular: 11.0.5
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.5
@angular-devkit/build-angular   0.1100.5
@angular-devkit/core            11.0.5
@angular-devkit/schematics      11.0.5
@angular/cdk                    11.0.3
@angular/material               11.0.3
@schematics/angular             11.0.5
@schematics/update              0.1100.5
rxjs                            6.6.3
typescript                      4.0.5<code>

**Comment by petebacondarwin** [comment] 2021-01-19 17:30
I believe this is working as intended. The `<app-dummy-child></app-dummy-child>` DOM node is actually defined and instantiated in the containing template (i.e. where `<app-dummy-component>` appears). So the `ng-content` is not responsible for instantiating this DOM, it is only responsible for "moving" the DOM nodes into the `ng-content` location.

**Comment by mlc-mlapis** [comment] 2021-01-19 17:31
@petebacondarwin Exactly. ❗

**Comment by Airblader** [comment] 2021-01-19 19:47
The typical solution for lazy rendering is not to use content projection but passing templates to begin with.

**Comment by AndrewKushnir** [comment] 2021-01-19 22:22
Closing this ticket based on the comments in this thread (working as intended).

**Closed by AndrewKushnir** 2021-01-19 22:22 UTC
Labels: comp: core, core: DOM rendering, core: content projection

**Comment by mhamri** [comment] 2021-01-20 07:38
@Airblader I will open a feature request for that then. the usage shouldn't be affected if a component wants to handle things lazily or instantaneously

**Comment by Airblader** [comment] 2021-01-20 07:48
I don't think that would be accepted, because the way it behaves is logical (and as intended, see above). From the perspective of the parent, you are creating an instance of that component. It would be quite confusing if your component may or may not be instantiated depending on implementation details of the wrapping component, IMO.

**Comment by mhamri** [comment] 2021-01-20 11:49
but do you think is it really logical? 

https://stackblitz.com/edit/angular-ivy-hgkkgt?file=src/app/app.component.html

just imagine this case where the usage is wrong and there isn't any placeholder for the child to be shown. 

```
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-dummy-parent',
  template:`
    <ng-content select="abcdefg-component"></ng-content> 
  `,
})
export class DummyParentComponent {
}


// usage 

<app-dummy-parent>
	<app-dummy-child></app-dummy-child>
</app-dummy-parent>

```

why angular should instantiate something that has no place to get rendered? if it was a react method, the child item's render method would never be called, but from what I can see, angular goes through the instantiation steps either the component gets rendered or not.

and there is a big question mark about this behavior performance where angular literally executing a useless code. 

I understand that it's necessary to protect the child content against third party components. but it's true if there is a placeholder to render that child. but if it's not getting rendered then what is the use case to instantiate something that has no way to be shown?

I also don't have any problem with instantiation, my main problem is why it calls the lifecycles when there is no way that component goes through any cycle, to begin with?

also, it stops the component creators encapsulate the usage without dictating a usage pattern and it forces them to introduce very empty directives to just get hold of the templates. 

```
<lazy-load-it> 
<!-- put whatever you want here and it will get lazy loaded -->
</lazy-load-it>
```

compare to this 


```
<lazy-load-it> 
<!-- put whatever you want here and it will get lazy loaded but don't forget to use my structural directive x -->
<!-- or just pass an ng-template-->
</lazy-load-it>
```

**Comment by mlc-mlapis** [comment] 2021-01-20 14:15
@mhamri It's probably related to the fact Angular compiler does all the content projection job statically and ahead of time. So using a concrete `select` leads to the concrete fixed code. Maybe there is a part that could be improved when select leads to nothing so that projected instance would not be instantiated, but then you need a new flag to control that because there still could be a case when you need that instance even without any UI.

**Comment by Airblader** [comment] 2021-01-20 14:51
AFAIK content queries also work regardless of whether the content is actually projected into any slot, so not instantiating these components would be a breaking change.

**Comment by mlc-mlapis** [comment] 2021-01-20 15:02
@Airblader Yep, that's why it would have to be a new flag and new functionality under that flag.

**Comment by mhamri** [comment] 2021-01-21 06:11
@mlc-mlapis thanks 

> need a new flag to control that because there still could be a case when you need that instance even without any UI.

unfortunately, I can't find any reason someone needs to put something in a child component of another component where the usage is wrong and angular goes silent about it. not silence, even render it out. 

```
<ng-content *ngIf="false"></ng-content> 
```

even this case doesn't stop the angular to not call the lifecycles. 

I appreciate it to share if you have anything in mind that can resonate with current usage or what this static rendering tries to solve? if it was a concern of who instantiates the component and who owns it, still we could achieve the current functionality by requesting it from the owner to instantiate it (whenever we need it) and then pass it, instead of just passing a pre-instantiated one. this way the owner still is the same, the third-party component still receive the same thing, performance-wise this has some benefit and no different than an ng-template.

**Comment by mlc-mlapis** [comment] 2021-01-21 10:07
@mhamri 

As @Airblader already mentioned above and probably other customs variants that we are not aware of at the moment, it still has to be a new functionality to avoid a breaking change.

> AFAIK content queries also work regardless of whether the content is actually projected into any slot

It's also related to the scope, and when a CD is invoked, and probably other details, I am not aware of at this moment.

> if it was a concern of who instantiates the component and who owns it

There are some plans (partly on the way already) how to improve the content projection mechanism, such as how to recognize that nothing has been projected (either it was an error or a wanted effect) more easily and others.

There is a roadmap https://angular.io/guide/roadmap, and I don't think that potential changes we are talking about here can be realized in the nearest future, so it is certainly outside of the scope for Angular 12.
