### ISSUE TITLE
After upgrading from Angular 6 to 11 i18n translations are not working

### ISSUE THREAD

**Issue by ibigrock-ashish** [angular/angular#40683] opened 2021-02-03 07:20 UTC

**Comment by AndrewKushnir** [comment] 2021-02-03 07:26
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

Could you please provide more information on this issue? Check "Bug report" issue template to see which information we are looking for. It'd be also helpful if you could provide a minimal repro (in a form of GitHub repo).

**Comment by ibigrock-ashish** [comment] 2021-02-03 08:29
# 🐞 bug report

### Affected Package
i18n

### Is this a regression?
Same code was working fine before upgrade. Previous version was 6.

### Description
After Upgrade, all the components are working fine, even ngx-translations(using pipes) are also working fine, but i18n translations(using message.el-EL.xlf and similar files for other languages like french, german etc.) are not loading on dashboard. And I am not able to see any issue in console as well. I am able to see message.el-EL.xlf being loaded in Network tab. 

## 🔬 Minimal Reproduction
Please check the below repo :
https://github.com/ibigrock-ashish/i18nSample

refer main.ts and locale folders for my code.

## 🔥 Exception or Error
No errors

## 🌍  Your Environment

**Angular Version:**
Angular 11

**Comment by petebacondarwin** [comment] 2021-02-03 15:02
I see in your project that you are using `TRANSLATIONS` and `TRANSATIONS_FORMAT` to provide translations at runtime.
This is not supported in Ivy projects. So that is probably why it is not working for you.

I believe that, even in View Engine mode, this approach would have only worked with JIT mode compilation, since in View Engine i18n translations were merged into templates only at compile time.

So while this is a breaking change between VE and IVY, it has not been picked up in the docs very well, since it was not a use-case in AOT compilation mode, which has become the norm.

It is actually possible to load translations at runtime using the new Ivy translation but it is setup in a very different way. Arguably the new Ivy approach is better, since you can still compile your project in AOT mode - no JIT compilation needed - and then do the translation merging in the browser just before booting the Angular application, which I believe is the use-case here.

Currently the runtime translation approach is not yet documented, nor is it supported very well: you are required to parse the translation file into a JSON object before it can be loaded. To get started you can look at this integration test sample in our repository: https://github.com/angular/angular/blob/a3b08644280fb43d9dfd037927c4e6a48a2c9a46/integration/ivy-i18n/src/polyfills-runtime.ts#L62-L79

**Comment by petebacondarwin** [comment] 2021-02-03 15:05
Closing this as there is already a PR to expose the `$localize` API at https://github.com/angular/angular/pull/40317.

**Closed by petebacondarwin** 2021-02-03 15:05 UTC
Labels: comp: i18n, needs reproduction
