### ISSUE TITLE
feat: ng-descendant - content projection between ancestors and descendant classes

### ISSUE THREAD

**Issue by chuckjaz** [angular/angular#13766] opened 2017-01-04 00:19 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] feature request
```

**Problem**

> Inspired by #13757 

The template provided by an ancestor component is not useful to a descendant component since its content cannot be reference nor can it be used to build the descendant (even with #13764). This limits the usefulness of inheritance as a model for building components.

**Proposal**

Add a pseudo-element called `ng-descendant` that can be used analogously to `ng-content` except that the content is from the descendant class' template instead of instantiating template.

Descendant components are required to use an `ng-extend` elements that contains the content that is projected into the ancestor template. If the descendant does not use an `ng-extend` element as the root element of its template then its template will replace the ancestor template instead of extending it.

**Example**

```ts
@Component({
  template: `
    <h1><ng-descendant select=".header"></ng-descendant></h1>
    <ng-descendant select=".body"></ng-descendant>
    <div>
      <ng-descendant select=".footer"></ng-descendant>
    </div>`
})
class BaseClass {
}

@Component({
  template: `
    <ng-extend>
      <span class="header">My Component</span>
      <span class="body">Body of the component</span>
      <span class="footer">Footer of the component</span>
    </ng-extend>`  
})
class MyComponent extends BaseClass {
}
```

This would be interpreted as if `MyComponent` had been written as:

```ts
@Component({
    template: `
    <h1><span class="header">My Component</span></h1>
    <span class="body">Body of the component</span>
    <div>
       <span class="footer">Footer of the component</span>
    </div>`
})
class MyComponent extends BaseClass {
}
```

**Comment by asfernandes** [comment] 2017-01-04 00:27
This is a proposal for the #13757 I just submitted.

**Comment by chuckjaz** [comment] 2017-01-04 00:28
Exactly. I recast it to a concrete proposal. I was in the processes of commenting on yours to replace it with this more concrete proposal.

**Comment by chuckjaz** [comment] 2017-01-04 00:31
I updated the content to directly reference your original request.

**Comment by vicb** [comment] 2017-01-04 04:20
@chuckjaz @asfernandes could you add concrete use cases ? Especially uses cases that could not be implemented with the current `<ng-content>`

**Comment by asfernandes** [comment] 2017-01-04 09:30
Any case that inheritance makes more sense than composition. The example in the proposal is a valid one, define a base page with a generic layout.

Maybe could be implemented with another component and transclusion, but overall application design/implementation may make more sense to have a base class.

**Comment by chuckjaz** [comment] 2017-01-04 16:56
`<ng-descendant>` is the inheritance analog to `<ng-content>` so it would be difficult (if not impossible) to come up with an example that would could not be accomplished with `<ng-content>` and composition. However, now that we are supporting inheritance as a mechanism to construct components the same use cases that justify `<ng-content>` for composition justify `<ng-descendant>` for inheritance.

As @asfernandes points out, there exist patterns that are more conveniently and efficiently expressed using inheritance. This feature would increase the reach of inheritance allowing it to be used when it is more deemed more appropriate than composition.

**Comment by szanellato93** [comment] 2017-12-12 15:50
@vicb here an example: https://stackblitz.com/edit/ng-content-projection-lzjwea

Explain of my problem: https://stackoverflow.com/questions/47773136/angular-2-include-component-html-in-a-component-inherited-template

**Comment by mlc-mlapis** [comment] 2017-12-12 16:01
@szanellato93 ... can you simply describe what is the problem in your example? I am not sure ...

**Comment by mlc-mlapis** [comment] 2017-12-12 16:08
@szanellato93 ... you are talking about HTML markup but there is no HTML at all finally in Angular app ... everything is compiled to JS ... so you can access what doesn't exist.

**Comment by szanellato93** [comment] 2017-12-12 16:12
@mlc-mlapis i want that the Hello2 have Hello1 template with values of overrided properties of Hello2. See the name property, i override it but the Hello2 component still have the old name. The solution is change all override properties to Input and inject them.. but if there are a possibility to include the base component html and extend it, all work fine.

I'm reference the base component html when i don't need to change it and all work fine. I need a way to change it withoit creating an istance of it.

**Comment by mlc-mlapis** [comment] 2017-12-12 16:33
@szanellato93 ... without an instance it is just a class definition ... and its HTML template is present only by compiled JS functions ...

... and as I know ... inheritance on Angular components doesn't support `template / templateUrl` and `styles / styleUrls` metadata.

**Comment by HideDev** [comment] 2018-01-03 09:46
Any news when this is done?

**Comment by HideDev** [comment] 2018-01-15 00:28
@chuckjaz )

**Comment by listepo** [comment] 2018-01-19 00:18
@chuckjaz can we get this before Angular 6?

**Comment by sandrocsimas** [comment] 2018-05-01 22:06
Currently I'm doing this way:
https://scotch.io/tutorials/angular-2-transclusion-using-ng-content

**Comment by listepo-alterpost** [comment] 2018-05-23 16:14
@chuckjaz any news for Ivy Renderer?

**Comment by inspirassion** [comment] 2018-07-03 09:01
This would be really great, it simplifies the design

**Comment by lambidu** [comment] 2018-07-26 20:01
Please, Angular Gods, give it to us!

**Comment by abadakhshan** [comment] 2020-01-13 06:25
[Narik](https://docs.narik.me/04.-ui-inheritance) provides a way to do something like this.

**Comment by Suresh918** [comment] 2020-04-23 23:30
The mentioned approach is still limited.

@Component({
  template: `
    <h1><ng-descendant select=".header"></ng-descendant></h1>
    <ng-descendant select=".body"></ng-descendant>
    <div>
      <ng-descendant select=".footer"></ng-descendant>
    </div>`
})
class BaseClass {
}

@Component({
  template: `
    <ng-extend>
      <span class="header">My Component</span>
      <span class="body">Body of the component</span>
      <span class="footer">Footer of the component</span>
    </ng-extend>`  
})
class MyComponent extends BaseClass {
}

Here we can add header, body, footer only from child component. It is not fully flexible.
By default, every element in the base class and child elements of header, body, footer are protected.
Only header, body, footer are allowed to replace from the child component.
Here base component  has more control so it's not flexible.

If there are more elements (for instance 100) in header and i want to replace only one element in the header. In that case i need to implement whole header template (100 elements). It is a duplication of code.

If the design is like below it will be flexible,
By default every element in the base class should be allowed to replace from the client and the elements which we want to protect are configured in the base class.
Here child component has more control so it's flexible.

If we are able to identify all the elements in the base component uniquely by some computation or logic using element tags, classes, indexes etc., then each element can be replaced from child component.

**Comment by jaqx0r** [comment] 2021-03-03 04:54
I came to this issue while looking for examples on how to correctly reuse `ng-templates` and `*ngTemplateOutlet` in subclasses of an angular component.  (Also, `ng-content` doesn't work in the same way.)

My case is that I have tens of components for rendering different protobuf messages in a data entry UI.  The messages are variations of a particular type, and otherwise not interesting for the problem here.  The components all inherit from the same base class that knows how to read from an actual protobuf message, but each knows how to read its own particular type of message.

Similarly the ng.html is the same boilerplate of `<mat-expansion-panel><mat-expansion-header> ...` roughly 20 lines of the same per component around a short bit of rendering for the message in the child component.  The boilerplate includes `@Input`s like 'name' and 'description' from the base class, set in the child classes.

I want to remove the boilerplate into the base class, but I cannot do it easily.

The closest I can do is put the parent class's selector in the ng.html, passing it a TemplateRef like described here, https://blog.angular-university.io/angular-ng-template-ng-container-ngtemplateoutlet/ but I need to resend the component parameters like `name` and `description` in the child template's invocation of the parent's selector to make them in scope.  I had assumed incorrectly that they would be visible to the base template as it's the base of the class.

The proposal here would make that work as I'd expected, I believe, so please consider adding it so that code reuse of *templates* is simpler, and less wordy than currently possible.  It made me sad to find out that I have to write lots of boilerplate in the form of shuffling Inputs around to avoid lots of boilerplate.

**Comment by lzilioli** [comment] 2021-05-20 16:18
I too have been seeking the ability to implement a base component, extend from that, but wrap its template. It seems at present, angular provides no way of doing this. I think `ng-decsendant` is an exellent proposal that would meet my use case very well.

In the absence of `ng-decsendant`, we are left with keeping component state in sync between parent and child (as has been discussed previously), in which case we lose access to one of the primary benefits offered by inheritance: implementation-level method overrides. 

I came up with a relatively non-invasive approach that I believe achieves the best of both worlds, documented it with a working demo, and published it here: https://github.com/lzilioli/extend-to-template

I hope others find this useful. Feedback is welcome.

**Comment by jessicajaniuk** [comment] 2022-02-15 00:37
Thanks for reporting this issue. However this issue is a duplicate of an existing issue #37319. Please subscribe to that issue for future updates.

**Closed by jessicajaniuk** 2022-02-15 00:37 UTC
Labels: feature, state: Needs Design, comp: core, core: component extension and customization, under consideration
