### ISSUE TITLE
angular.io not rendering properly on internet explorer

### ISSUE THREAD

**Issue by skhekare** [angular/angular#32858] opened 2019-09-25 19:38 UTC
![Clipboard01](https://user-images.githubusercontent.com/9753536/65633524-f4e4d900-dff9-11e9-8ce9-e8caa2343335.jpg)
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

Some of the page content is not rendered on internet explorer 11 with windows 8

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by gkalpak** [comment] 2019-09-25 20:26
Thx for reporting this issue. It looks like a duplicate of #32832. Let's move the discussion there.

**Closed by gkalpak** 2019-09-25 20:26 UTC
