### ISSUE TITLE
Documentation at angular.io/guide/bootstrapping is not working.

### ISSUE THREAD

**Issue by beatgrabe** [angular/angular#25595] opened 2018-08-21 12:32 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
Navigating to https://angular.io/guide/bootstrapping leads into console error:

```javascript
ERROR [DocViewer] Error preparing document 'guide/bootstrapping': Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at t.extractHeadingSafeHtml (https://angular.io/main.d553c07cb1ab4b9d11e4.bundle.js:1:264514)
    at https://angular.io/main.d553c07cb1ab4b9d11e4.bundle.js:1:263980
    at Array.map (<anonymous>)
    at t.genToc (https://angular.io/main.d553c07cb1ab4b9d11e4.bundle.js:1:263947)
    at https://angular.io/main.d553c07cb1ab4b9d11e4.bundle.js:1:307690
    at e._next (https://angular.io/main.d553c07cb1ab4b9d11e4.bundle.js:1:309987)
    at e.__tryOrSetError (https://angular.io/main.d553c07cb1ab4b9d11e4.bundle.js:1:52231)
    at e.next (https://angular.io/main.d553c07cb1ab4b9d11e4.bundle.js:1:51342)
    at e._next (https://angular.io/main.d553c07cb1ab4b9d11e4.bundle.js:1:50476)
    at e.next (https://angular.io/main.d553c07cb1ab4b9d11e4.bundle.js:1:50147)
```

## Expected behavior
The corresponding view renders properly.

## What is the motivation / use case for changing the behavior?
Working documentation page would be awesome.

## Environment

<pre><code>Browser:
- [x] Chrome (desktop) version 68.0.3440.106

**Comment by gkalpak** [comment] 2018-08-21 13:33
This is not the first report of this issue (e.g. https://github.com/angular/angular/issues/24973#issuecomment-414055269) 😞
Interestingly, though, [extractHeadingSafeHtml()][1] does not contain any call to `removeChild()` 😕 
(May be a Chrome bug.)

[1]: https://github.com/angular/angular/blob/d2be3d57759c93bd5f4a2b9df780a8a7f8e12c95/aio/src/app/shared/toc.service.ts#L56-L76

**Comment by gkalpak** [comment] 2018-08-21 13:37
Some people have faced the same error in unrelated projects:
- https://github.com/ianstormtaylor/slate/issues/1861
- https://github.com/sanity-io/sanity/issues/910

Could be related to IME (but [not necessarilly][1]).

[1]: https://github.com/ianstormtaylor/slate/issues/1861#issuecomment-394305277

**Comment by s-gbz** [comment] 2018-08-21 13:50
Maybe this is related to #24392 as well?

**Comment by gkalpak** [comment] 2018-08-21 14:28
No, that one is different (see #24847).

**Comment by gkalpak** [comment] 2019-12-10 10:43
The `extractHeadingSafeHtml()` (which was the source of the error, according to your stack track) has been reworked in #32871, so hopefully this issue has been resolved.

Given that (and the fact that I can't reproduce the issue anyway), I am going to close this. Please, open a new issue if you run into this again.

**Closed by gkalpak** 2019-12-10 10:43 UTC
Labels: comp: docs-infra, type: bug/fix
