### ISSUE TITLE
ng_jsonp_callback_0 is not defined

### ISSUE THREAD

**Issue by Toso82** [angular/angular#42892] opened 2021-07-19 09:37 UTC
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

Yes

### Description

I have a http.jsonp request work well in old version now give error

```ts
return this.http.jsonp<HereGeocoder.HereResponseGeocoding>(`${this.urlBase}GetCoordinatesFromAddress?${param}`, callback).pipe(      
        catchError(() => new Observable<HereGeocoder.HereResponseGeocoding>())
 );
```

### Please provide the exception or error you saw

```true
Uncaught ReferenceError: ng_jsonp_callback_0 is not defined
    at GetCoordinatesFromAddress?address=mantova&callback=ng_jsonp_callback_0:1
(anonymous) @ GetCoordinatesFromAddress?address=mantova&callback=ng_jsonp_callback_0:1
```

### Please provide the environment you discovered this bug in

```true
Angular CLI: 12.1.2
Node: 16.4.0 (Unsupported)
Package Manager: npm 7.19.1
OS: win32 x64

Angular: 12.1.2
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, localize, material, material-moment-adapter
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1201.2
@angular-devkit/build-angular   12.1.2
@angular-devkit/core            12.1.2
@angular-devkit/schematics      12.1.2
@angular/flex-layout            12.0.0-beta.34
@schematics/angular             12.1.2
rxjs                            6.6.7
typescript                      4.3.4
```

**Comment by petebacondarwin** [comment] 2021-07-19 09:56
Could you please provide a runnable reproduction of this error that we could debug?

**Comment by Toso82** [comment] 2021-07-20 10:22
@petebacondarwin  I try to reproduce in a isolate project

**Comment by JoostK** [comment] 2021-12-11 13:27
Closing due to lack of reproduction. This may be the same as #34818.

**Closed by JoostK** 2021-12-11 13:27 UTC
Labels: needs reproduction, comp: common/http
