### ISSUE TITLE
npm install on [ivy / angular 9 libraries] creates error TS2300: Duplicate identifiers in the type file [*.d.ts]

### ISSUE THREAD

**Issue by claygifford** [angular/angular#35394] opened 2020-02-12 21:35 UTC
npm install on [ivy / angular 9 libraries] creates error TS2300: Duplicate identifiers

example: npm install [angular9-lib]

for certain components an invalid *.d.ts file is created.
however the __ivy_ngcc_bak version is correct.

node_modules -> 
grid-row-component.d.ts.__ivy_ngcc_bak [this one is correct]
grid-row-component.d.ts 
[this one contains duplicate identifiers]

import * as i0 from "@angular/core";
import * as ɵngcc0 from '@angular/core';
...
static ɵfac: i0.ɵɵFactoryDef<GridRowComponent>;
static ɵfac: ɵngcc0.ɵɵFactoryDef<GridRowComponent>;

version
    "@angular/common": "9.0.0",
    "@angular/core": "9.0.0",
    "@angular/forms": "9.0.0",
    "@angular/platform-browser": "9.0.0",
    "@angular/platform-browser-dynamic": "9.0.0",
    "@angular-devkit/build-angular": "0.900.1",
    "@angular-devkit/build-ng-packagr": "0.900.1",
    "@angular/cli": "9.0.1",
    "@angular/compiler": "9.0.0",
    "@angular/compiler-cli": "9.0.0",
    "typescript": "3.7.5"

**Comment by JoostK** [comment] 2020-02-12 22:37
You seem to be installing a library that is compiled for Ivy and the processed for Ivy once more by ngcc, resulting in duplicated compiled output. I don't know how that would occur as the initial compile should remove the decorators, so that ngcc should not have any decorators to process.

Without an exact repro we can't really investigate this more, unfortunately.

**Comment by claygifford** [comment] 2020-02-13 13:51
Thanks for the helpful comment.
ng serve is 'compiling module as esm5' as you stated unnecessarily.
I will continue to investigate

**Comment by claygifford** [comment] 2020-02-13 17:09
ng serve appears to compile the module as esm5. This consistent with other ivy built libraries.
However, there appears to be a bug. Manually removing the duplicates, gets me past the issue, but I am running into other issues.

Looks like angular 9 [project] -> angular 9 [library] is just not ready.

I guess I will wait until 9.1

**Comment by alxhub** [comment] 2020-02-13 23:28
I agree with @JoostK's assessment - it appears that the library is being built with Ivy enabled, then run through ngcc somehow. This is indeed a bug, but without a reproduction, we won't be able to investigate further. @claygifford, are you able to provide a Github repo that demonstrates this problem?

**Comment by alxhub** [comment] 2020-03-04 20:24
Closing as no reproduction was provided and we have no way of investigating further.

**Closed by alxhub** 2020-03-04 20:24 UTC
Labels: comp: compiler, comp: ivy, freq2: medium, severity3: broken, state: Needs repro, type: bug/fix

**Comment by gokselb** [comment] 2020-03-12 19:02
@alxhub  Dear Alex, to reproduce the issue please follow these steps. 
I can't provide the repo because the project that I am working on has privacy disclosure. 

1. Create an Angular library with Angular@9.0.6
2. Build with ivy and push it as npm package
3. Create an Angular project with Angular@9.0.6 and import the npm library as dependency. 
4. Try to build this project with Ivy. 

Then you should be able to see error. 
The problem is when I build the project, Angular inserts additional code lines to .d.ts files of my library. 
It imports `@angular/core` with different `as` annotation. You can see below. 

`/node_modules/my_library/lib/path/to/component/info-template.component.d.ts`

Pre-ng build
```ts
import { OnChanges, OnDestroy, SimpleChanges } from '@angular/core';
import * as i0 from "@angular/core";
export declare class InfoTemplateComponent implements OnChanges, OnDestroy {
    private sendingTemplateService;
    static ɵfac: i0.ɵɵFactoryDef<InfoTemplateComponent>;
    static ɵcmp: i0.ɵɵComponentDefWithMeta<InfoTemplateComponent, "bilisim-info-template", never, { "templateId": "templateId"; "headers": "headers"; }, {}, never>;
}

//# sourceMappingURL=info-template.component.d.ts.map
```

Post-ng build
```ts
import { OnChanges, OnDestroy, SimpleChanges } from '@angular/core';
import * as i0 from "@angular/core";
import * as ɵngcc0 from '@angular/core';
export declare class InfoTemplateComponent implements OnChanges, OnDestroy {
    private sendingTemplateService;
    static ɵfac: i0.ɵɵFactoryDef<InfoTemplateComponent>;
    static ɵcmp: i0.ɵɵComponentDefWithMeta<InfoTemplateComponent, "bilisim-info-template", never, { "templateId": "templateId"; "headers": "headers"; }, {}, never>;
    static ɵfac: ɵngcc0.ɵɵFactoryDef<InfoTemplateComponent>;
    static ɵdir: ɵngcc0.ɵɵDirectiveDefWithMeta<InfoTemplateComponent, never, never, {}, {}, never>;
}

//# sourceMappingURL=info-template.component.d.ts.map
```
Eventually build fails with error: `/node_modules/my_library/lib/path/to/component/info-template.component.d.ts:19:12 - error TS2300: Duplicate identifier 'ɵfac'.`

You see it created 2 more static variable for new `@angular/core` (ɵngcc0) with the same old name. 
Trying to fix this issue for 2 weeks. The task given to me is to update angular to version 9 with ivy compiler compatibility.

Do I miss something. What can cause this Duplicate identifier error? 
I would appreciate any idea, any.

**Comment by JoostK** [comment] 2020-03-12 20:15
I notice now that ngcc inserts a definition for `@Directive`, whereas the `InfoTemplateComponent` is actually a component. So that indicates that this is not the result of compiling decorators (as those should have been removed, as mentioned above) but a migration that is run from within ngcc.

It could either be the `UndecoratedChildMigration` or the `UndecoratedParentMigration` migration, both of which add a `@Directive` decorator where deemed appropriate to do so. I expect the `UndecoratedParentMigration` to be the culprit in your case.

In your library, there's likely a component without a constructor that extends from another component that has a constructor. In Ivy, the base class is required to have an `@Component` decorator, but since your library has already been Ivy compiled this decorator has already been stripped so ngcc assumes that it needs to add the `@Directive` decorator to the base class in the `UndecoratedParentMigration`.

One thing that strikes me as odd, still: ngcc would only compile a package if there is a `*.metadata.json` file, which should _not_ be produced if the library has been compiled for Ivy. So, no migrations in ngcc should be executing at all. Can you check whether there's a file with the `.metadata.json` suffix next to the `typings` file of the package (you can find the `typings` file by looking in `package.json`)?

There's possibilities to ignore certain packages in ngcc so that they would not be processed, but I'd like to understand why ngcc is processing the package in the first place. Note, also, that publishing libraries using Ivy instructions is not supported at the moment!

**Comment by gokselb** [comment] 2020-03-13 08:26
Thank you for your response. I've recently noticed it is not recommended. So I compile my libs without ivy on prod now. I am looking forward to see support for ivy lib to ivy app. 

Honestly my component only implements `onChanges` and `OnDestroy` and has `@Component` annotation as below. 
```ts
@Component({
  selector: 'bilisim-info-template',
  templateUrl: './info-template.component.html',
  providers: [SendingTemplateService]
})
export class InfoTemplateComponent implements OnChanges, OnDestroy {
  public constructor(private sendingTemplateService: SendingTemplateService) { }
```

For your question. I didn't check if there is metadata.json now I'm compiling the project with ivy enabled. I'll let you know if i see `.metadata.json` file.

**Comment by JoostK** [comment] 2020-03-13 08:38
@gokselb Please check whether `InfoTemplateComponent` has any subclasses with an `@Component` decorator.

**Comment by gokselb** [comment] 2020-03-13 08:48
This is the entire info-template.component.ts file.
Dou you think erros has something to do with `@Input()`s?

```
import { Component, Input, OnChanges, OnDestroy, OnInit, SimpleChanges } from '@angular/core';
import { Subscription } from 'rxjs';

// Common
import { GenericExpression, CompanyHttpResponse, Comparison, HeaderParameter } from '@company/common';

// Local
import { SendingTemplate } from '../../models/parameters/sending-template.model';
import { SendingTemplateService } from '../../services/module-services/parameters/sending-template.service';


@Component({
  selector: 'company-info-template',
  templateUrl: './info-template.component.html',
  providers: [SendingTemplateService]
})
export class InfoTemplateComponent implements OnChanges, OnDestroy {

  @Input() public templateId: string;
  @Input() headers: HeaderParameter[];
  public sendingTemplatePreview: SendingTemplate;
  private subscriptions: Subscription[] = [];

  public constructor(private sendingTemplateService: SendingTemplateService) { }

  public ngOnChanges(changes: SimpleChanges): void {
    if (changes.templateId && this.templateId) this.getSendingTemplate()
  }

  public ngOnDestroy(): void {
    this.subscriptions.forEach(subscription => subscription.unsubscribe());
  }

  private getSendingTemplate(): void {

    const filterQueryTemplate: GenericExpression = {
      FilterGroups: [
        { Filters: [{ PropertyName: 'TemplateKey', Value: this.templateId, Comparison: Comparison.EqualTo }] },
      ],
    };
    this.sendingTemplateService.getListBy(filterQueryTemplate, null, this.headers).subscribe(
      (obs: CompanyHttpResponse<SendingTemplate[]>) => {
        this.sendingTemplatePreview = obs.serviceResult.Result.length > 0 ? obs.serviceResult.Result[0] : null;
      }
    )

  }
}
```

**Comment by JoostK** [comment] 2020-03-13 08:58
I don't think so. I'm particularly interested in any subclasses.

**Comment by gokselb** [comment] 2020-03-13 15:55
Would you mind elaborating subclasses? As much as I know -also you see [in this comment](https://github.com/angular/angular/issues/35394#issuecomment-598613755)-  there is no subclass complexity.

**Comment by JoostK** [comment] 2020-03-13 16:22
@gokselb From that code I can't tell whether there's any subclasses. A subclass would be some other component that `extends InfoTemplateComponent`.

**Comment by JoostK** [comment] 2020-03-13 22:00
@claygifford Excellent! Do you have any clue how that file ends up there?
