### ISSUE TITLE
The system cannot find the file specified.

### ISSUE THREAD

**Issue by fendypurnomo** [angular/angular#55679] opened 2024-05-06 06:47 UTC
### Describe the problem that you experienced

D:\Applications\docs\angular.io>yarn docs
yarn run v1.22.19
$ [[ -n $CI ]] && echo 'Cannot run this yarn script on CI' && exit 1 || yarn bazel run //adev:serve --fast_adev
'[[' is not recognized as an internal or external command,
operable program or batch file.
$ D:\Applications\docs\angular.io\node_modules\.bin\bazel run //adev:serve --fast_adev
2024/05/06 13:17:07 Downloading https://releases.bazel.build/5.0.0/release/bazel-5.0.0-windows-x86_64.exe...
Downloading: 44 MB out of 44 MB (100%)
Starting local Bazel server and connecting to it...
... still trying to connect to local Bazel server after 10 seconds ...

INFO: Analyzed target //adev:serve (1319 packages loaded, 82781 targets configured).
INFO: Found 1 target...

ERROR: D:/applications/docs/angular.io/packages/zone.js/BUILD.bazel:12:8: Executing genrule //packages/zone.js:LICENSE_copy failed: (Exit -1): bash.exe failed: error executing command c:\tools\msys64\usr\bin\bash.exe -c source external/bazel_tools/tools/genrule/genrule-setup.sh; cp LICENSE bazel-out/x64_windows-fastbuild/bin/packages/zone.js/LICENSE
Action failed to execute: java.io.IOException: ERROR: src/main/native/windows/process.cc(202): CreateProcessW("c:\tools\msys64\usr\bin\bash.exe" -c "source external/bazel_tools/tools/genrule/genrule-setup.sh; cp LICENSE bazel-out/x64_windows-fastbuild/bin/packages/zone.js/LICENSE"): The system cannot find the file specified.
 (error: 2)

ERROR: D:/applications/docs/angular.io/packages/zone.js/BUILD.bazel:19:8: Executing genrule //packages/zone.js:LICENSE_wrapped failed: (Exit -1): bash.exe failed: error executing command c:\tools\msys64\usr\bin\bash.exe -c ... (remaining 1 argument skipped)
Action failed to execute: java.io.IOException: ERROR: src/main/native/windows/process.cc(202): CreateProcessW("c:\tools\msys64\usr\bin\bash.exe" -c "source external/bazel_tools/tools/genrule/genrule-setup.sh; (echo '/**
 @license' && cat LICENSE && echo '*/') > bazel-out/x64_windows-fastbuild/bin/packages/zone.js/LICENSE.wrapped"): The system cannot find the file specified.
 (error: 2)
Target //adev:serve failed to build
Use --verbose_failures to see the command lines of failed build steps.

INFO: Elapsed time: 485.410s, Critical Path: 3.70s
INFO: 51 processes: 8 internal, 43 local.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
error Command failed with exit code 34.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 34.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by alan-agius4** [comment] 2024-05-06 06:59
Duplicate of https://github.com/angular/angular/issues/55657

**Closed by alan-agius4** 2024-05-06 06:59 UTC
