### ISSUE TITLE
IVY issue?: Can't resolve all parameters for Pipe: (?)

### ISSUE THREAD

**Issue by LanderBeeuwsaert** [angular/angular#31990] opened 2019-08-03 21:17 UTC
### Is this a regression?

This is in IVY upgrade issue.
Angular version is: 9.0.0-next.0

### Description

During the same update as described here:
https://github.com/angular/angular/issues/31981

I have a second issue where a pipe gives the following error:
![image](https://user-images.githubusercontent.com/1098243/62416965-ba3b7180-b644-11e9-9c12-ef2754824622.png)

because of this source code:
![image](https://user-images.githubusercontent.com/1098243/62416971-ca535100-b644-11e9-9190-fc24ae6452e0.png)

**Comment by JoostK** [comment] 2019-08-03 22:08
Hi @LanderBeeuwsaert, could you please try to provide us with a minimum reproduction of the issue, as the screenshots do not provide sufficient information to be able to understand the problem you have.

**Comment by LanderBeeuwsaert** [comment] 2019-08-05 21:37
Hey @JoostK ,

is there a sort of starter IVY stackblitz or something that I can use.
Or a starter github IVY project or something?

**Comment by JoostK** [comment] 2019-08-05 21:48
There's no Ivy-enabled StackBlitz at the moment, although it's quite easy to get started with an Ivy project:

```
npx @angular/cli@next new --enable-ivy my-ivy-app
```

This is using npx to resolve the preview release of the CLI, which ensures you're on the latest versions, without needing a global CLI installation.

**Comment by LanderBeeuwsaert** [comment] 2019-08-06 07:31
@JoostK Hey, can I send you the repro zipped somewhere? (I Prefer not to put it online)

**Comment by JoostK** [comment] 2019-08-06 18:45
@LanderBeeuwsaert Feel free to upload [to WeTransfer](https://wetransfer.com) and send me the link [in a DM on twitter](https://twitter.com/devjoost).

<sup>In WeTransfer, you have to click the small circle in the bottom left to switch to "Send as: **Link**"</sup>

**Comment by JoostK** [comment] 2019-08-06 20:00
I'm seeing an issue during the compilation of `ng2-odometer` that causes the `BaseModule` to become invalid, which is potentially causing errors downstream. Since I can't get the project to compile properly, I'm not sure how you arrived at the runtime errors.

FYI, the issue with `ng2-odometer` is because of how its code is structured in a way that ngcc doesn't currently recognize. At the moment there's no workaround to avoid this problem, I'm afraid.

**Comment by LanderBeeuwsaert** [comment] 2019-08-06 20:24
you can just leave out the odometer library, it has no use in the reproduction.
For me, the odometer was giving issues as well but https://github.com/angular/angular/issues/30680 resolved this. So angular.9.0.0 worked for me.

**Comment by JoostK** [comment] 2019-08-08 19:36
Ah, I see now you're injecting a different pipe into the broken pipe's constructor. [This is known to be a breaking change](https://docs.google.com/document/d/1Dije0AsJ0PxL3NaeNPxpYDeapj30b_QC0xfeIvIIzgg/preview):

> All provided or injected tokens must have `@Injectable` decorator (previously, injected tokens without `@Injectable` were allowed if another decorator was used, e.g. pipes).

There's work underway to potentially support this use-case once again, see #31953. For now, you can add `@Injectable()` as a decorator next to the `@Pipe()` decorator of the `ParseTo3Decimal` pipe, such that its constructor parameters become visible to the DI system.

Since this is a known breaking change at the moment, I will close this issue. Thanks for trying out Ivy and reporting the issues you had, if you encounter others please let us know!

**Closed by JoostK** 2019-08-08 19:36 UTC
Labels: comp: ivy, state: Needs repro
