### ISSUE TITLE
angular.dev missing versions page

### ISSUE THREAD

**Issue by aboudard** [angular/angular#53111] opened 2023-11-22 10:12 UTC
### Describe the problem that you experienced

The url https://angular.dev/versions is missing content.

### Enter the URL of the topic with the problem

https://angular.dev/versions

### Describe what you were looking for in the documentation

When navigating to https://angular.dev/tools/cli/setup-local, there's a link to a page that should probably look like this one :
https://angular.io/guide/versions
But this link is displaying a "page not found"

### Describe the actions that led you to experience the problem

Just visit the page and click on the Angular's version compatibility link :
![image](https://github.com/angular/angular/assets/767767/fa7e4a3b-41b5-47aa-97f3-2207c7d10557)

### Describe what you want to experience that would fix the problem

We should either fix the link to a correct page or create the page with the same content as https://angular.io/guide/versions

### Add a screenshot if that helps illustrate the problem

![image](https://github.com/angular/angular/assets/767767/611d1a05-89bd-4367-99c3-3bdfa84b6b9f)

**Comment by sasidharansd** [comment] 2023-11-22 10:16
Duplicate of https://github.com/angular/angular/issues/52562, https://github.com/angular/angular/issues/53108 , fixed with the PR: https://github.com/angular/angular/pull/52585

**Comment by JoostK** [comment] 2023-11-22 10:22
Thanks for the report, closing per the above.

**Closed by JoostK** 2023-11-22 10:22 UTC

**Comment by aboudard** [comment] 2023-11-22 10:35
> Duplicate of #52562, #53108 , fixed with the PR: #52585

My bad, didn't search well enough !
