### ISSUE TITLE
Loadchildren (dynamic imports) in routing not working when 'enableIvy' is set to true in tsconfig.app.json

### ISSUE THREAD

**Issue by supercoder123** [angular/angular#34462] opened 2019-12-18 07:12 UTC
# 🐞 BUG REPORT
### Description
When I use loadChildren inside a children array the child modules are not loaded. This happens only when enableIvy is set to true. Works fine if enableIvy is set to false. Also aot is set to true in angular.json. Also there is no error shown. Only the parent component is loaded (PageComponent) in this case.

<pre>
<code>
const PAGE_ROUTES: Routes = [
  {
    path: ' ',
    component: PageComponent,
    children: [
      {
        path: 'child1',
        loadChildren: () => import('../../../child1/child1.module').then(m => m.child1Module)
      },
      {
        path: 'child2',
        loadChildren: () => import('../../../child2/child2.module').then(m => m.child2Module)
      }
    ]
  }
];
</code>
</pre>

If the loadChildren modules are specified directly (shown below) everything works fine even when ivy is enabled. But I can't do that in the above shown case as I have to display the modules inside the parent based on the route.

<pre> 
<code>
  { path: '', loadChildren: () => import('./shared/modules/page/page.module').then(m => m.PageModule) },
</code>
</pre>

### Angular version 
<pre>
<code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 8.0.6
Node: 11.9.0
OS: linux x64
Angular: 8.0.3
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.6
@angular-devkit/build-angular     0.800.6
@angular-devkit/build-optimizer   0.800.6
@angular-devkit/build-webpack     0.800.6
@angular-devkit/core              8.3.20
@angular-devkit/schematics        8.0.6
@angular/cdk                      8.0.0
@angular/cli                      8.0.6
@angular/http                     5.0.0
@angular/material                 8.0.0
@angular/pwa                      0.803.20
@ngtools/webpack                  8.0.6
@schematics/angular               8.0.6
@schematics/update                0.800.6
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.30.0
</code>
</pre>

**Comment by JoostK** [comment] 2020-10-25 19:23
I cannot reproduce using the sample you provided; Ivy has matured significantly since Angular 8.0.3 so the issue may have been fixed in the meanwhile. I'll close this one; please open a new issue with reproduction if you're still having an issue with latest Angular.

**Closed by JoostK** 2020-10-25 19:23 UTC
Labels: P2, comp: router, engine: ivy, regression
