### ISSUE TITLE
NgModelChange event timing depends on the attribute order before or after ngModel directive

### ISSUE THREAD

**Issue by leonelvsc** [angular/angular#42632] opened 2021-06-23 19:39 UTC
# Bug Report

### Affected Package
@angular/forms

### Description
 

Depending on the order in which attributes of a DOM element event or directive are defined it affects the order in which Angular process the events

## Minimal Reproduction

https://stackblitz.com/edit/angular-ivy-ym6jsl?file=src/app/app.component.ts

## Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 12.0.5
Node: 14.17.0
Package Manager: npm 7.16.0
OS: linux x64

Angular: 12.0.5
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.5
@angular-devkit/build-angular   12.0.5
@angular-devkit/build-webpack   0.1200.5
@angular-devkit/core            12.0.5
@angular-devkit/schematics      12.0.5
@angular/fire                   6.1.5
@schematics/angular             12.0.5
ng-packagr                      12.0.5
rxjs                            6.6.7
typescript                      4.2.4

</code></pre>

**Anything else relevant?**
Is this behaviour on purpose?

**Comment by JoostK** [comment] 2021-06-23 20:37
Duplicate of #11234.

**Closed by JoostK** 2021-06-23 20:37 UTC
Labels: comp: forms
