### ISSUE TITLE
ngControl control property is null when OnInit hook

### ISSUE THREAD

**Issue by Delagen** [angular/angular#9291] opened 2016-06-17 07:37 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
using new @angular/forms package with disable deprecated forms

```html
<form #form="ngForm">
<input type="text" formControlName="username" class="form-control" placeholder="Login" required/>
</form>
```
```ts
@Directive({
			   selector: "input"
		   })
export class InputDirective implements AfterViewInit, OnDestroy {
	private subscription: Subscription;

	constructor(@Optional() @Inject(NgControl) private ngControl: NgControl) {
	}

	ngOnInit(): void {
		console.log("control", this.ngControl, this.ngControl.control);
	}
}
```
this.ngControl.control is null

**Expected/desired behavior**
this.ngControl.control is not null

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.2
 
* **Browser:** Chrome 51
* **Language:** TypeScript@1.9.0-dev

**Comment by zoechi** [comment] 2016-06-17 09:08
Can't reproduce https://plnkr.co/edit/bUpuykUPRmlZnPzfI9yZ?p=preview

GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by Delagen** [comment] 2016-06-17 17:29
https://plnkr.co/edit/oxNuBLo8Y6Hg3OKbm25M?p=preview

**Comment by IgorMinar** [comment] 2016-06-17 19:10
@Delagen it is not clear from your plunker what is the expected result vs actual result of that repro. Can you please clarify?

**Comment by Delagen** [comment] 2016-06-18 05:51
see console.log
first log ngControl.control property is null
second log after some timeout ngControl.control property is not null

**Comment by zoechi** [comment] 2016-06-18 06:24
![image](https://cloud.githubusercontent.com/assets/405837/16169431/0d33b488-352e-11e6-91c7-34c1bbb92bd3.png)

(the error message at the end is from a Chrome plugin)

**Comment by kara** [comment] 2016-08-24 01:21
Hmm, the plunker errors (rightfully) with RC.5 because you're using a `formControlName` directive without a parent `FormGroup` instance or directive.  If you switch one way or the other, the control seems to print in both cases.  Closing, as I can't reproduce.

**Closed by kara** 2016-08-24 01:21 UTC
Labels: comp: core/forms
