### ISSUE TITLE
More than one complex property in input?

### ISSUE THREAD

**Issue by AbinayaSubbiah** [angular/angular#14204] opened 2017-01-31 12:23 UTC
Getting script error while define more than on complex property in **@Input()**  or

How to define complex property. Please find plnkr link.

https://plnkr.co/edit/NcvjuqZvo6jilmrdeZ1R?p=preview

`VM1920 zone.js:420 Unhandled Promise rejection: Template parse errors:
Can't bind to 'content.value' since it isn't a known property of 'custom-div'.
1. If 'custom-div' is an Angular component and it has 'content.value' input, then verify that it is part of this module.
2. If 'custom-div' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("
    </div>
    
    <custom-div  [ERROR ->][content.value] = "content"></custom-div>
  "): App@5:17 ; Zone: <root> ; Task: Promise.then ; Value: SyntaxError {__zone_symbol__error: Error: Template parse errors:
Can't bind to 'content.value' since it isn't a known property of 'cust…, _nativeError: ZoneAwareError, __zone_symbol__stack: "Error: Template parse errors:↵Can't bind to 'conte…ps://unpkg.com/zone.js@0.7.6/dist/zone.js:433:35)", __zone_symbol__message: "Template parse errors:↵Can't bind to 'content.valu…t.value] = "content"></custom-div>↵  "): App@5:17"} Error: Template parse errors:
Can't bind to 'content.value' since it isn't a known property of 'custom-div'.
1. If 'custom-div' is an Angular component and it has 'content.value' input, then verify that it is part of this module.
2. If 'custom-div' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("
    </div>
    
    <custom-div  [ERROR ->][content.value] = "content"></custom-div>
  "): App@5:17
    at SyntaxError.ZoneAwareError (https://unpkg.com/zone.js@0.7.6/dist/zone.js:811:33)
    at SyntaxError.BaseError [as constructor] (https://unpkg.com/@angular/compiler/bundles/compiler.umd.js:1592:20)
    at new SyntaxError (https://unpkg.com/@angular/compiler/bundles/compiler.umd.js:1795:20)
    at TemplateParser.parse (https://unpkg.com/@angular/compiler/bundles/compiler.umd.js:11434:23)
    at JitCompiler._compileTemplate (https://unpkg.com/@angular/compiler/bundles/compiler.umd.js:27568:72)
    at eval (https://unpkg.com/@angular/compiler/bundles/compiler.umd.js:27451:66)
    at Set.forEach (native)
    at JitCompiler._compileComponents (https://unpkg.com/@angular/compiler/bundles/compiler.umd.js:27451:23)
    at createResult (https://unpkg.com/@angular/compiler/bundles/compiler.umd.js:27333:23)
    at ZoneDelegate.invoke (https://unpkg.com/zone.js@0.7.6/dist/zone.js:242:26)
    at Zone.run (https://unpkg.com/zone.js@0.7.6/dist/zone.js:113:43)
    at https://unpkg.com/zone.js@0.7.6/dist/zone.js:535:57
    at ZoneDelegate.invokeTask (https://unpkg.com/zone.js@0.7.6/dist/zone.js:275:35)
    at Zone.runTask (https://unpkg.com/zone.js@0.7.6/dist/zone.js:151:47)
    at drainMicroTaskQueue (https://unpkg.com/zone.js@0.7.6/dist/zone.js:433:35)`

**Comment by ericmartinezr** [comment] 2017-01-31 12:34
https://plnkr.co/edit/NcvjuqZvo6jilmrdeZ1R?p=preview

Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by AbinayaSubbiah** [comment] 2017-01-31 12:40
@ericmartinezr  How i can use complex property with custom tag like 

 <cus-tag [form.fname]=""  [form.lname]=""> </cus-tag>

and how to do this?

**Comment by kevinwardenga** [comment] 2017-01-31 22:47
@AbinayaSubbiah  why would you want to do this?

Just use `<custom-tag [form]="form">`

And in CustomTagComponent.ts use:
```
@Input('form')
public form: YourFormType;

public get fname() {
  return this.form && this.form.Iname
}
```

**Comment by AbinayaSubbiah** [comment] 2017-02-01 04:40
@kevinwardenga  For example if custom component is grid i have set of properties like pagesetting, which is like json property.

pagesetting property as

**pagesetting { "count":"count","size":"size"}**

i want to define grid like below.

<my-grid [pagesetting.count]="count"></my-grid>

**Comment by DzmitryShylovich** [comment] 2017-02-01 13:28
@pkozlowski-opensource it's a duplicate of https://github.com/angular/angular/issues/11663

**Comment by trotyl** [comment] 2018-08-02 14:55
Duplicate of https://github.com/angular/angular/issues/13355

**Comment by pkozlowski-opensource** [comment] 2019-03-12 14:07
Correct @trotyl - it is a duplicate of #13355 - thnx!

**Closed by pkozlowski-opensource** 2019-03-12 14:07 UTC
Labels: comp: core & compiler, type: feature
