### ISSUE TITLE
Error angular element wi

### ISSUE THREAD

**Issue by kamalkech** [angular/angular#29962] opened 2019-04-17 17:24 UTC
- File package.json : 

```
{
  "name": "ng-element",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "build:elements": "ng build --prod --output-hashing=none && node build-script.js",
    "serve:elements": "http-server ./elements -p 4201"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~7.2.0",
    "@angular/common": "~7.2.0",
    "@angular/compiler": "~7.2.0",
    "@angular/core": "~7.2.0",
    "@angular/elements": "^7.2.13",
    "@angular/forms": "~7.2.0",
    "@angular/platform-browser": "~7.2.0",
    "@angular/platform-browser-dynamic": "~7.2.0",
    "@angular/router": "~7.2.0",
    "core-js": "^2.5.4",
    "rxjs": "~6.3.3",
    "tslib": "^1.9.0",
    "zone.js": "~0.8.26",
    "document-register-element": "^1.7.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.13.0",
    "@angular/cli": "~7.3.1",
    "@angular/compiler-cli": "~7.2.0",
    "@angular/language-service": "~7.2.0",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.5.0",
    "concat": "^1.0.3",
    "fs-extra": "^7.0.1",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~3.1.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "~3.2.2"
  }
}
```

I get this error to try to test element in outside

```
user-poll.js:3 Uncaught TypeError: Failed to construct 'HTMLElement': Please use the 'new' operator, this DOM object constructor cannot be called as a function.
    at n.t [as constructor] (user-poll.js:3)
    at new n (user-poll.js:3)
t @ user-poll.js:3
n @ user-poll.js:3
```

**Comment by ericmartinezr** [comment] 2019-04-17 17:26
https://github.com/angular/angular/issues/24390

**Comment by benlesh** [comment] 2019-04-17 18:27
Thanks for reporting this issue. However this issue is a duplicate of an existing issue #24390. Please subscribe to that issue for future updates.

**Closed by benlesh** 2019-04-17 18:27 UTC
