### ISSUE TITLE
Number input fire 2 event on valueChanges

### ISSUE THREAD

**Issue by Typhon0** [angular/angular#23601] opened 2018-04-30 07:08 UTC
## I'm submitting a...

<pre><code>[X] Bug report  </code></pre>

## Current behavior

When we click on the up arrow of the input number, valueChanges fire 2 events .

## Expected behavior

Only fire 1 event when we click on the up arrow of an input number.

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-material2-issue-number-input-event
https://stackblitz.com/edit/angular-material2-issue-number-input-event-qjkub4?

## Environment

<pre><code>
Angular version: 6.0.0-rc2

Browser:
- [X] Chrome (desktop) version 66.0.3359.139
- [X] Firefox version 58.0.1
- [X] Safari (desktop) version 11.1

 
For Tooling issues:
- Node version: v8.11.1
- Platform:  Mac, Linux, Windows

Others:

</code></pre>

**Comment by trotyl** [comment] 2018-04-30 08:59
Duplicate of https://github.com/angular/angular/issues/12540

**Comment by kara** [comment] 2018-05-01 22:10
Closing as dupe

**Closed by kara** 2018-05-01 22:10 UTC
Labels: comp: forms
