### ISSUE TITLE
Compiler DI errors are difficult to interpret

### ISSUE THREAD

**Issue by akopchinskiy** [angular/angular#31592] opened 2019-07-16 17:30 UTC
**Angular debugging is bad**

Best example: 

> dependency injection errors

```
Uncaught Error: Can't resolve all parameters for FormComponent: ([object Object], [object Object], [object Object], [object Object], ?, [object Object], ?, ... and a lot more parameters).
    at syntaxError (compiler.js:2409)
    at CompileMetadataResolver._getDependenciesMetadata (compiler.js:21311)
    at CompileMetadataResolver._getTypeMetadata (compiler.js:21203)
    at CompileMetadataResolver.getNonNormalizedDirectiveMetadata (compiler.js:20822)
    at CompileMetadataResolver._getEntryComponentMetadata (compiler.js:21407)
    at compiler.js:21398
    at Array.forEach (<anonymous>)
    at CompileMetadataResolver._getEntryComponentsFromProvider (compiler.js:21397)
    at compiler.js:21370
    at Array.forEach (<anonymous>)
```

How i'm suppose to know what exact **parameter** is cannot be resolved and why?

```
constructor(
        private snackBar: MatSnackBar,
        @Inject(BackendService) private backend: BackendService,
        @Inject(ChromeMessengerService) private chromeMessenger: ChromeMessengerService,
        @Inject(DateTimeService) private datetime: DateTimeService,
        @Inject(SettingsService) private settings: SettingsService,
        @Inject(StoreService) private store: StoreService,
        ... other dozens of services ...
    ) {
```

Why it points me to his modules instead of error in my code?
```
syntaxError | @ | compiler.js:2409
-- | -- | --
  | CompileMetadataResolver._getDependenciesMetadata | @ | compiler.js:21311
  | CompileMetadataResolver._getTypeMetadata | @ | compiler.js:21203
  | CompileMetadataResolver.getNonNormalizedDirectiveMetadata | @ | compiler.js:20822
  | CompileMetadataResolver._getEntryComponentMetadata | @ | compiler.js:21407
  | (anonymous) | @ | compiler.js:21398
  | CompileMetadataResolver._getEntryComponentsFromProvider | @ | compiler.js:21397
  | (anonymous) | @ | compiler.js:21370
  | CompileMetadataResolver._getProvidersMetadata | @ | compiler.js:21333
  | (anonymous) | @ | compiler.js:21335
  | CompileMetadataResolver._getProvidersMetadata | @ | compiler.js:21333
  | (anonymous) | @ | compiler.js:20955
  | CompileMetadataResolver.getNgModuleMetadata | @ | compiler.js:20946
  | CompileMetadataResolver.getNgModuleSummary | @ | compiler.js:20881
  | (anonymous) | @ | compiler.js:20968
  | CompileMetadataResolver.getNgModuleMetadata | @ | compiler.js:20946
  | JitCompiler._loadModules | @ | compiler.js:27106
  | JitCompiler._compileModuleAndComponents | @ | compiler.js:27087
  | JitCompiler.compileModuleAsync | @ | compiler.js:27047
  | CompilerImpl.compileModuleAsync | @ | platform-browser-dynamic.js:143
  | compileNgModuleFactory__PRE_R3__ | @ | core.js:27089
  | PlatformRef.bootstrapModule | @ | core.js:27301
  | ./src/app/grabber/app.main.ts | @ | app.main.ts:15
  | __webpack_require__ | @ | bootstrap:19
  | (anonymous) | @ | bootstrap:83
  | (anonymous) | @ | bootstrap:83
```

My code is only in `app.main.ts:15` and that is only application entry:
```
platformBrowserDynamic().bootstrapModule(AppModule);
```

So it clearly tell me: "The problem is somewhere in your app, but I don't give a **** where it's exactly".

**Comment by Airblader** [comment] 2019-07-16 19:18
Feel free to send a PR to improve this. If you had ever written a compiler you'd understand why it's so hard to give good error messages. But complaining is easier, I get it.

**Comment by akopchinskiy** [comment] 2019-07-16 19:51
@Airblader 
>Feel free to send a PR to improve this.
I just did.
> If you had ever written a compiler you'd understand why it's so hard to give good error messages.
If you would ever written a compiler you wouldn't speak this nonsense. Moreover it's no need to write own compiler to compare Angular's one with other analogs (Vue, React, Knockout).
> But complaining is easier, I get it.
Yeah, so tell that nonsense somewhere else.

**Comment by Airblader** [comment] 2019-07-16 20:03
> I just did.

No you didn't. 

Apart from that I won't further interact with a troll like you.

**Comment by alxhub** [comment] 2019-07-16 22:21
I agree the error message could be significantly improved.

In the future (Ivy), DI is entirely a runtime concept. This means that you won't see errors like this at compilation time, but instead on application startup. It should be very easy to use the browser debugger to understand the source of these errors, due to the nature of Ivy's generated DI factories.

I would also remind you that on the Angular issue tracker, our [Code of Conduct](https://github.com/angular/code-of-conduct/blob/master/CODE_OF_CONDUCT.md) applies. Please communicate thoughtfully and respectfully in future messages - there is no call for insults here. I'm also going to change the title of this issue to be more appropriate.

**Comment by akopchinskiy** [comment] 2019-07-17 08:32
@Airblader troll is you with your compiler that trolling devs through whole development process. I just can't take serious his error messages and your responses also, because they both are ridiculous.

@alxhub Thank you for your reasonable answer. The title of this topic was originally inspired by these two cool famous publications, that explictly expose known Problems of Angular, which are devs are stubbornly unwilling to notice:
1. https://medium.com/hackernoon/why-angular-made-me-quit-web-dev-f63b83a157af
2. https://medium.com/dirtyjs/why-angular-2-4-5-6-sucks-afb36567ad68

But there wasn't many topics on Github like mine, which are could tell to the Angular devs that's something is wrong with their framework, because they only saying that it is "hero", "awesome" and other similar funny stuff. But when you actually pointing at the problems, they instantly starting to whine, like:
`If you had ever written a compiler you'd understand why it's so hard to give good error messages`

Currently I still struggling with this error in my project. I forced to debug through entire Angular source code to find the single problem, because @Airblader  said that `it's so hard to give good error messages`, <sarcasm> which is absolutely unarguable position, of course. </sarcasm>

**Comment by Airblader** [comment] 2019-07-17 08:40
No one said you cannot criticize the error messages. It's your complete lack of respect, self-entitled attitude and ignorance of the Conde of Conduct that makes people angry and unwilling to engage in a discussion.

It's also the fact that you fall back to personal insults (calling me "disabled") that I reported you to GitHub.

**Comment by akopchinskiy** [comment] 2019-07-17 09:17
@Airblader instead of inspecting the problem you said: 
`But complaining is easier, I get it.`
meaning that I only complaining, despite that fact that I had describe complete problem from start to finish. Is that ok for you, right?

**Comment by trotyl** [comment] 2019-07-17 09:48
@akopchinskiy You can write:

```typescript
console.log(MatSnackBar)
console.log(BackendService)
console.log(ChromeMessengerService)
console.log(DateTimeService)
console.log(SettingsService) // Escpecially this one
console.log(StoreService)
```

In the same file and have a look, if any of these logs `undefined`, than it's your own fault, not Angular's. There's no way Angular knowns why you declare `undefined` as a dependency.

Also, please always provide minimal runnable reproduction when opening issues.

**Comment by JoostK** [comment] 2021-05-14 12:20
Closing as Ivy is able to report why a certain constructor parameter is not a valid DI token.

**Closed by JoostK** 2021-05-14 12:20 UTC
Labels: P5, comp: compiler, engine: ve, freq3: high, hotlist: error messages, triage #1, type: confusing
