### ISSUE TITLE
Change of QueryParam not detected when mutating Array

### ISSUE THREAD

**Issue by mralexandernickel** [angular/angular#27533] opened 2018-12-07 06:28 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/router

### Is this a regression?

 Not sure, but the Issue is present for at least one year. This issue at first came up here #17609 

### Description

When mutating an Array inside QueryParams, the change is not detected by @angular/router:

```typescript
    // queryParams look something like this:
    // {
    //   'one': '1',
    //   'two': ['1', '2', '3']
    // }
    const nextQueryParams: Params = Object.assign(
      {},
      this.activatedRoute.snapshot.queryParams
    );

    nextQueryParams.two.push('b3');

    this.router
      .navigate([], {
        relativeTo: this.activatedRoute,
        queryParams: nextQueryParams
      })
      .then(res => {
        console.log('# Response from Router.navigate is (null) ==>', res);
      });
```

As you can see in the provided Stackblitz the updated queryParams will not be reflected inside the URL, and no subscribers to `activatedRoute.queryParams` will be notified about the change.

## 🔬 Minimal Reproduction

[stackblitz](https://stackblitz.com/github/mralexandernickel/angular-queryparams-bug?file=src%2Fapp%2Freproduction%2Freproduction.component.ts)

## 🔥 Exception or Error

No error is thrown, but Router.navigate is resolving with NULL

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 7.0.6
Node: 9.11.2
OS: darwin x64
Angular: 7.0.4
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.10.6
@angular-devkit/build-angular     0.10.6
@angular-devkit/build-optimizer   0.10.6
@angular-devkit/build-webpack     0.10.6
@angular-devkit/core              7.0.6
@angular-devkit/schematics        7.0.6
@angular/cli                      7.0.6
@ngtools/webpack                  7.0.6
@schematics/angular               7.0.6
@schematics/update                0.10.6
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.19.1
</code></pre>

**Anything else relevant?**

Inside my reproduction, the Router is detecting the change when the reference of the provided array inside the queryParams changed (just setting a new array to the queryParams). I am working on a application right now, where this is not true. Still trying to figure out what is different there, to provide even more information on this.

**Comment by mralexandernickel** [comment] 2018-12-07 06:29
#17609

**Comment by manklu** [comment] 2018-12-08 17:13
Duplicate of https://github.com/angular/angular/issues/27528

**Comment by jasonaden** [comment] 2018-12-18 22:10
Thanks for the issue. I'm going to close this one as a duplicate of #27528 (which looks like it was created JUST before your issue).

I'll post an update there.

**Closed** 2018-12-18 22:10 UTC
Labels: comp: router, type: bug/fix
