### ISSUE TITLE
KeyValue pipe does not support custom object type

### ISSUE THREAD

**Issue by diksha-v** [angular/angular#38695] opened 2020-09-03 09:34 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/core@9.0.2

### Is this a regression?

 Not sure, never turned on full template type check on before v9

### Description

 using keyvalue pipe for custom object type throws "No overload matches this call." error

## 🔬 Minimal Reproduction

 https://stackblitz.com/edit/angular-ivy-ehsope

## 🔥 Exception or Error
<pre><code>

No overload matches this call.
The last overload gave the following error.
Argument of type 'Employee' is not assignable to parameter of type 'Map<unknown, unknown>'.
Type 'Employee' is missing the following properties from type 'Map<unknown, unknown>': clear, delete, forEach, get, and 8 more.
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 9.0.3
Node: 10.19.0
OS: win32 x64

 

Angular: 9.0.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

 

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.900.3
@angular-devkit/build-angular      0.900.3
@angular-devkit/build-ng-packagr   0.900.3
@angular-devkit/build-optimizer    0.900.3
@angular-devkit/build-webpack      0.900.3
@angular-devkit/core               9.0.3
@angular-devkit/schematics         9.0.3
@angular/cli                       9.0.3
@ngtools/webpack                   9.0.3
@schematics/angular                9.0.3
@schematics/update                 0.900.3
ng-packagr                         9.1.1
rxjs                               6.5.5
typescript                         3.7.5
webpack                            4.41.2
</code></pre>

**Anything else relevant?**

**Comment by dannyskoog** [comment] 2020-09-04 19:21
You have to make sure that your input matches one of the following overloads https://github.com/angular/angular/blob/9.0.2/packages/common/src/pipes/keyvalue_pipe.ts#L53-L67

**Comment by petebacondarwin** [comment] 2020-09-10 17:50
Indeed this is due to TS typings: see this [playground](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgKIFsAOBlArgIwBEIw5gAbAZ2QG8AoZZCLASQBNkAuZSsKUAOYBuBshBx0Kbr34hhdAL506CAPYheyNiTJVuGHAWKkK1ALy1RzTO24ByAIwAmAMx2ANKPGT7AKVUAFiAeiiIq6poA1hAAngBucOS4ENw0ANrRMdJ8ggC62bICCsgW2iZUQkA).

Closing as this is not a bug in the framework.

**Closed by petebacondarwin** 2020-09-10 17:50 UTC
Labels: comp: common
