### ISSUE TITLE
Possibly broken selectors in Angular 4.0.0

### ISSUE THREAD

**Issue by kemsky** [angular/angular#16727] opened 2017-05-11 18:41 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
We can define component selector as `.input[attr1=value][attr2]`.

This selector will match also binding expressions like `<div class="input" attr1="value" [attr2]="'bla-bla'"/>`.

I'm pretty sure that before Angular 4.0.0 the following example also worked `<div class="input" [attr1]="'value'" [attr2]="'bla-bla'"/>` with slight selector modification `.input[attr1='value'][attr2]`. 
All validators using such selectors are now broken in our app.

**Expected behavior**
Selectors could also work for static bindings and they did before 4.0.0.

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/xOeXrCyqkiKgWyM678m2?p=preview
Change `Sample` directive selector to `.input[mask='test'][maxvalue]`

**What is the motivation / use case for changing the behavior?**
Plain attributes do not provide validation, while bindings are checked.

**Please tell us about your environment:**

* **Angular version:** 4.1.2

* **Browser:** [all ]
 
* **Language:** [TypeScript 2.1.3]

**Comment by tbosch** [comment] 2017-05-16 22:36
Thank you for the bug report.
However, the general rule is that selectors don't take expressions into account. That it worked before Angular 4 was an unintended side effect.

Closing as works as intended.

**Closed by tbosch** 2017-05-16 22:36 UTC
Labels: comp: core & compiler
