### ISSUE TITLE
ng update @angular/core and .pug templates 

### ISSUE THREAD

**Issue by Olgagr** [angular/angular#32326] opened 2019-08-26 13:12 UTC
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ x] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?
Not sure.

### Description
We are using pug as a template preprocessor. We are trying to migrate from Angular 7 to Angular 8. We manage to update angular-cli. However, when we run `ng update @angular/core --from 7 --to 8 --migrate-only` we get template parsing Typescript errors.

## 🔥 Exception or Error
<pre><code>
 The template migration strategy uses the Angular compiler internally and therefore projects that no longer build successfully after the update cannot use the template migration strategy. Please ensure there are no AOT compilation errors.
            
            Could not setup migration strategy for "src/tsconfig.app.json". The following error has been reported:

Error: error TS100: Template parse errors:
            Unexpected character "EOF" (Do you have an unescaped "{" in your template? Use "{{ '{' }}") to escape it.) ("arret(*ngIf="showCaret")
            .dropdown-body(#dropdown='')
              ng-content(select="[dropdown-part=dropdown]")[ERROR ->]"): /home/ograbek/Documents/projects/fieldly-angular/src/app/shared/components/dropdown/dropdown.template.pug@8:47
            Invalid ICU message. Missing '}'. ("arret(*ngIf="showCaret")
            .dropdown-body(#dropdown='')
              ng-content(select="[dropdown-part=dropdown]")[ERROR ->]"): /home/ograbek/Documents/projects/fieldly-angular/src/app/shared/components/dropdown/dropdown.template.pug@8:47

</code></pre>

The pug template is:

```
.dropdown-toggle(
  (click)='toggleDropdown($event)',
  [ngClass]="({'b-button': asButton, 'm-success': asButton})"
)
  .dropdown-toggle-content
    ng-content(select="[dropdown-part=toggle]")
  .b-carret(*ngIf="showCaret")
.dropdown-body(#dropdown='')
  ng-content(select="[dropdown-part=dropdown]")
```

We notice that the problem is with `ngClass` and `ng-content`.

## 🌍 Your Environment
<pre><code>
Angular CLI: 8.2.1
Node: 10.15.2
OS: linux x64
Angular: 8.2.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.802.1
@angular-devkit/build-angular     0.802.1
@angular-devkit/build-optimizer   0.802.1
@angular-devkit/build-webpack     0.802.1
@angular-devkit/core              8.2.1
@angular-devkit/schematics        8.2.1
@angular/cli                      8.2.1
@ngtools/webpack                  8.2.1
@schematics/angular               8.2.1
@schematics/update                0.802.1
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.38.0

</code></pre>

**Comment by devversion** [comment] 2019-08-27 12:58
I think the problem is that we create the `AngularCompilerProgram` (to perform analysis of queries), but don't use the compiler program that is configured through the Angular CLI webpack plugin.

I'm not sure if we can leverage the same configured compiler program as with the CLI as we would need to the respect webpack configuration (e.g. the `AngularCompilerPlugin`).

**Comment by mhevery** [comment] 2019-09-03 23:00
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by Olgagr** [comment] 2019-09-04 12:22
@devversion Now I'm confused why this issue was closed. Your comment suggested that indeed there was a problem with `ng update @angular/core` that it didn't take webpack plugin into consideration. Closing this issue means that this is not true and webpack config is used during update and the issue is a problem on our site? Thanks for additional information about this rejection.

**Comment by devversion** [comment] 2019-09-09 15:48
Hey @Olgagr, yeah this got closed by mistake. This is a valid issue. Thanks for submitting that.

**Comment by CharlesGouldmann** [comment] 2019-09-19 10:55
I also ran into the same issue when trying to migrate to Angular 8. As Olgagr mentioned it seems to happen when using brackets in ngClass.

**Comment by devversion** [comment] 2019-10-23 18:30
We actually fixed this for the v9 migration with https://github.com/angular/angular/commit/6f5f481fdae03f1d8db36284b64c7b82d9519d85#diff-ae675f022e8eca96a7e19526dc893fd3. Please try again when you get a chance, and let me know 😄

**Comment by devversion** [comment] 2019-10-23 18:32
And for the V8 migrations, this still remains an issue. Though for these migrations it's more difficult to solve, since we actually need to interpret templates in order to perform some migrations.

**Comment by bhofner** [comment] 2019-11-27 19:47
I'm facing the same issue. Is there a workaround? Migrating directly from 7 to 9 seems also a no-go, since the migration doc tells us to migrate to 8 first.
I inherited the project with the .pug templates - would it be advisable to get rid of them? Is there a tool that might be able to do so?

**Comment by perrosen** [comment] 2019-11-29 03:03
Noticed the same issue with [ngClass] and pug templates. Will this be patched for the 8 migrations?

**Comment by Olgagr** [comment] 2020-01-24 09:10
@perrosen No, they will probably won't fix that for 8 migrations, only for 9 migrations. So the options are:
* migrate 7 -> 9
* migrate from HTML to pug and then migrate to 8

We choose the second option and I can only recommend it. The process is easy and painless (just use pug CLI) and after going from HTML to pug our tests are more than twice faster which is a big deal.

**Comment by Lhari** [comment] 2020-02-13 22:31
I just attempted to force upgrade my Angular 7.3.x project with pug enabled to Angular 9, while I no longer got the EOF error, I now get an ICU error

```
Invalid ICU message. Missing '}'. 
img.preload(#preloader, [ngClass]="{'is-preload': preload, 'animation': animation}", [ERROR ->](error)="onError()" [draggable]="draggable")"): projectPath/components/image/tpl.image.pug@27:89
```

**Comment by matheo** [comment] 2020-02-15 17:46
@devversion any idea if we can inject pug-loader before the HTML parser of `language-service` to lint our pug templates too?

**Comment by Lhari** [comment] 2020-02-16 01:51
I've tried to make a few different reproductions of the error, created a new Angular 9.x project, added pug. No problems, Moved my code over and modified everything to make a build work, and error's started occuring. There seems to be something happening where the TemplateUrl is executed as HTML instead of script, causing it to fail when it attempts to build the template?

```
path/modules/footer/pages/tpl.footer.pug:1:206 - error NG8001: 'module' is not a known element:
1. If 'module' is an Angular component, then verify that it is part of this module.
2. To allow any element add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.

<var>req = require("!!path\\node_modules\\pug-loader\\index.js!path\\src\\libraries\\project\\modules\\footer\\pages\\tpl.footer.pug");</var><module class="exports">= (req['default'] || req).apply(req, [])</module>
```
I'm not sure this is the issue that also affects the main project, but it does seem something in the upgrade of angular.json / migration of the project is causing the issue.

**Comment by devversion** [comment] 2020-02-17 10:05
To summarize what is going on in this issue: Our migration that runs for v7.0.0 to v8.0.0 relies on the `@angular/compiler-cli`. The compiler itself does not have logic for pug templates. The Angular CLI provides custom logic to make that template pre-processing possible. We can't use that from within our migrations, so the migration won't work for apps using pug templates.

The migration relies on template parsing because it tries to statically determine what view queries match in the template. So that it can migrate to `static: true` if needed. We have a similar migration for version 9 that uses the `@angular/compiler-cli`, but it does not rely on template parsing. Therefore it will work as expected with pug templates.

There is not much we can do for that version 8 migration. We'll try to account for this in future migrations (if possible), or document it clearly if a migration won't work with template processing.

---

A potential workaround could be hooking into the compiler resource reads. I have not tested if that will work, but it might be useful:

1. Go to `node_modules/@angular/core/schematics/migrations/static-queries/strategies/template_strategy/template_strategy.js`
2. Insert this into the script (after `options.enableIvy = false`)

```js
    options.enableIvy = false;

    // Insert this and wire up the pug transformer:
    this.host.readResource = fileName => {
      const fileContent = /* read content from file system */ 
      if (fileName.endsWith('.pug')) {
        return /* process pug template logic */;
      }
      return fileContent;
    }
```
3. Re-run the migration using `--migrate-only`. You don't want to run without that flag as the CLI could discard your local modifications otherwise.

Closing this issue since there isn't any action we could take (as mentioned above). Happy to chat more about this!

**Closed by devversion** 2020-02-17 10:05 UTC
Labels: comp: core, freq1: low, severity3: broken, type: bug/fix

**Comment by Lhari** [comment] 2020-02-17 13:29
@devversion I completely understand that we cannot migrate to Version 8, however, my attempt is to circumvent that, by skipping straight from 7 to 9, which also fails, does the process go through the process of transfering to 8?

**Comment by devversion** [comment] 2020-02-17 13:42
Sorry if that was unclear. If one updates from version 7 to version 9, the migrations from version 8 will still run with `ng update`. So the update will still fail due to the non-compatible version 8 migration.
