### ISSUE TITLE
flex layout compile issue

### ISSUE THREAD

**Issue by kschwidder** [angular/angular#34976] opened 2020-01-26 17:20 UTC
# 🐞 bug report

### Affected Package
angular 9.0.0 rc 11
flex-layout 8.0.0-beta.27

### Is this a regression?

yes

### Description

when compiling angular flex-layout the following error from ngcc

## 🔬 Minimal Reproduction

 https://stackblitz.com/...

## 🔥 Exception or Error
<pre><code>

ERROR in ./node_modules/@angular/flex-layout/__ivy_ngcc__/esm2015/extended.js 789:13-25
"export 'ɵNgStyleImpl' was not found in '@angular/common'
    
    ERROR in node_modules/@angular/flex-layout/extended/typings/style/style.d.ts:9:19 - error TS2724: Module '"../../../../common/common"' has no exported member 'ɵNgStyleImpl'. Did you mean 'ɵNgStyleR2Impl'?
    
    9 import { NgStyle, ɵNgStyleImpl, ɵNgStyleR2Impl } from '@angular/common';

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 9.0.0-rc.10
Node: 12.13.0
OS: darwin x64

Angular: 9.0.0-rc.11
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-rc.10
@angular-devkit/build-angular     0.900.0-rc.10
@angular-devkit/build-optimizer   0.900.0-rc.10
@angular-devkit/build-webpack     0.900.0-rc.10
@angular-devkit/core              9.0.0-rc.10
@angular-devkit/schematics        9.0.0-rc.10
@angular/cdk                      9.0.0-rc.8
@angular/cli                      9.0.0-rc.10
@angular/flex-layout              8.0.0-beta.27
@angular/material                 9.0.0-rc.8
@ngtools/webpack                  9.0.0-rc.10
@schematics/angular               9.0.0-rc.10
@schematics/update                0.900.0-rc.10
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2

</code></pre>

**Comment by pkozlowski-opensource** [comment] 2020-01-26 17:31
This is a duplicate of #34963 - looks like `flex-layout` is importing private APIs that changed (more precisely - were removed). I would expect that `flex-layout` will cut a new release fixing this problem.

In any case, let's centralise the discussion in  #34963

**Closed by pkozlowski-opensource** 2020-01-26 17:31 UTC
