### ISSUE TITLE
[NgTemplateOutlet] _updateExistingContext causes side effects 

### ISSUE THREAD

**Issue by konossow** [angular/angular#40493] opened 2021-01-20 12:29 UTC
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/common

### Is this a regression?

I don't know, but I'm sure it occurs also in version 9.

### Description

1. Prepare a template that has an object passed by $implicit (cannot be a primitive value).
2. Change 2 times context value of ngTemplateOutlet.
3. After second change origin object was changed.

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-fvm7oz?file=src/app/app.component.html
1. Select 0.
2. Inspect selected item - has changed.
3. Select 1.
4. Inspect selected item - has changed.
5. Inspect contents of contexts array - value at index 0 was replaced with value at index 1.
6. Select 0.
7. Inspect selected item - has not changed.

## 🔥 Exception or Error
No error is presented, but if objects inside contexts array are freezed (uncomment line 28 and 31) error is shown:
<pre><code>
ERROR TypeError: Cannot assign to read only property '$implicit' of object '[object Object]'
    at NgTemplateOutlet._updateExistingContext (ng_template_outlet.ts:104)
    at NgTemplateOutlet.ngOnChanges (ng_template_outlet.ts:68)
    at checkAndUpdateDirectiveInline (provider.ts:213)
    at checkAndUpdateNodeInline (view.ts:440)
    at checkAndUpdateNode (view.ts:400)
    at debugCheckAndUpdateNode (services.ts:435)
    at debugCheckDirectivesFn (services.ts:396)
    at Object.eval [as updateDirectives] (AppComponent.html:6)
    at Object.debugUpdateDirectives [as updateDirectives] (services.ts:390)
    at checkAndUpdateView (view.ts:370)

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
11.0.8
</code></pre>

**Anything else relevant?**
The reason why I use an object in $implicit is that I don't know the structure of object - it's created dynamically. Therefore I cannot separate properties through additional properties.

**Comment by JoostK** [comment] 2021-01-20 13:04
Heya, this is a known issue as reported in #24515. There has been recent activity in #40360 to fix this, but it proved to be a breaking change so it needs coordination to land.

I'll close this as a duplicate of #24515; please follow the aforementioned issues for future updates.

**Closed by JoostK** 2021-01-20 13:04 UTC
