### ISSUE TITLE
@HostBinding("class.some-class") with Signal<boolean> = computer(() => {});

### ISSUE THREAD

**Issue by cyraid** [angular/angular#54155] opened 2024-01-30 11:14 UTC
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

As the title suggests,
```typescript
public someSignal: WritableSignal<boolean> = signal(false);

@HostBinding("class.some-class")
public someClass: Signal<boolean> = computed(() => this.someSignal());
```

At this point, "some-class" is added regardless. I'm guessing either it doesn't know about signals, or just looks for a non-null value? Was this an intended scenario? I'm just getting into signals, and find them pretty nice but this would be a nicety if it's not.

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.0.9
Node: 20.10.0
Package Manager: npm 10.2.3
OS: linux x64

Angular: 17.0.8
... animations, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic
... platform-server, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.9
@angular-devkit/build-angular   17.0.9
@angular-devkit/core            17.0.9
@angular-devkit/schematics      17.0.9
@angular/cli                    17.0.9
@angular/ssr                    17.0.9
@schematics/angular             17.0.9
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.2
```

### Anything else?

Doing this works:

```typescript
@HostBinding("class.some-class")
public someClass: boolean = false;

public constructor() {
  effect(() => this.someClass = someSignal());
} // Constructor //
```

**Comment by JoostK** [comment] 2024-01-30 11:48
Duplicate of #53888.

**Closed by JoostK** 2024-01-30 11:48 UTC
