### ISSUE TITLE
The documentation for navigateByUrl is misleading

### ISSUE THREAD

**Issue by christofferskog** [angular/angular#20421] opened 2017-11-14 11:44 UTC
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
The signature of navigateByUrl is misleading as it doesn't care of all properties of `extras` but only a subset of it.

## Expected behavior
The docs should clearly state that not all properties of `extras` will be used, for instance, `queryParams` are completely ignored when using `navigateByUrl` but are used for `navigate`.

## What is the motivation / use case for changing the behavior?
This leads to confusion during development since following the docs doesn't give the desired result, leading you to think that there is something wrong in your code, rather than the docs being misleading. Causing you to spend time debugging your code when that time could be spent elsewhere.

**Comment by kapunahelewong** [comment] 2017-11-16 16:34
Hey @christofferskog I love the idea of clarifying. Would you be willing to submit a PR? Please feel free to tag me in it.

**Comment by vincecampanale** [comment] 2017-12-19 14:06
@kapunahelewong I'd be happy to take on this issue and submit a PR. Where in the project can I find the files that create the documentation? `/docs` was my best guess but it seems to be focused on team roles.

**Comment by kapunahelewong** [comment] 2017-12-19 14:51
@vincecampanale Oh great! You have a couple of options for where to put it; the guide or the API docs. 

### In the guide (more tutorial in style)
In the guide `testing.md` might be a good choice since that's where it's covered most you might also like to link to that section from `router.md` in the note about `navigateByUrl`. The docs are located in `aio/content/guide`.

### In the API docs (refernce)
The API doc I'm thinking is: [the Router API doc source](https://github.com/angular/angular/blob/5.1.1/packages/router/src/router.ts#L190-L778), probably around line 425 where it goes into usage.

Seen here fully rendered: [Router doc on angular.io](https://angular.io/api/router/Router)

Found in: angular/packages/router/src/router.ts

I'd probably lean toward the API doc, but could see putting it in the guide too. What do you think?

**Comment by vincecampanale** [comment] 2017-12-21 14:05
Thanks @kapunahelewong! Since the person who posted the issue is referring to the signature for `navigateByUrl`, I am leaning towards changing the API doc as well. I may add a sentence to the guide if necessary.

**Comment by kapunahelewong** [comment] 2019-02-06 19:18
Closing as PR was merged.

**Closed by kapunahelewong** 2019-02-06 19:18 UTC
Labels: comp: docs, comp: docs/api, comp: router, freq1: low, severity1: confusing, state: has PR, type: bug/fix
