### ISSUE TITLE
retry-interceptor.ts file is missing from Download Example zip file in Http Client section

### ISSUE THREAD

**Issue by PingPongSet** [angular/angular#42117] opened 2021-05-16 16:38 UTC
The file `retry-interceptor.ts` is missing from the folder below

`src\app\http-interceptors`

downloaded from the link below:

`https://angular.io/generated/zips/http/specs.http.zip`

in this section https://angular.io/guide/http

# Docs or angular.io Bug Report

### Description

 A clear and concise description of the problem...

### What's the affected URL?**
 https://angular.io/...

## Exception or Error
<pre><code>

</code></pre>

**Comment by petebacondarwin** [comment] 2021-05-17 10:28
I'm a bit confused here. The HTTP testing section does not mention the `RetryInterceptor`, which is why it does not appear in the downloadable example code. See https://stackblitz.com/edit/angular-tniswl?file=src/main.ts to see this working as expected (once the `jasmine-core` dependency is included).

For comparison, I just downloaded https://angular.io/generated/zips/http/http.zip and this example does include the `RetryInterceptor` as expected.

So I think this is working as intended. I'm going to close this but please comment further if I have misunderstood.

**Closed by petebacondarwin** 2021-05-17 10:28 UTC
Labels: comp: docs-infra
