### ISSUE TITLE
Dynamic Component Loader while embeding Stand Alone Web Components and Angular Elements

### ISSUE THREAD

**Issue by SwCon** [angular/angular#24044] opened 2018-05-22 08:30 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[X ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Stand Alone Web Components and Stand Alone Angular Elements do not render via dynamic component loader.  No error messages are given.

## Expected behavior

When Web Components or Angular Elements are used in a static index.html page, components render perfectly.  When used inside of <template> or <ng-template> 

## Minimal reproduction of the problem with instructions

Edit:
https://stackblitz.com/angular/mrxxaqgmrel?file=src%2Fpolyfills.ts
or download:
https://angular.io/generated/zips/dynamic-component-loader/dynamic-component-loader.zip

1. app.component.ts:
import:
import {CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
app.module.ts declare:
schemas: [CUSTOM_ELEMENTS_SCHEMA]

Install angular elements and custom elements:
npm i @angular/elements @webcomponents/custom-elements

edit polyfills.ts 👍 
import '@webcomponents/custom-elements/custom-elements.min';
import '@webcomponents/custom-elements/src/native-shim';

hero-profile.component.ts : 
add any stand alone web component or stand alone angular elements 

ng serve

## What is the motivation / use case for changing the behavior?

I want to be able to dynamically load Web Components or Angular Elements with in my app.  

## Environment

<pre><code>
Angular version: 
@angular-devkit/architect         0.6.1
@angular-devkit/build-angular     0.6.1
@angular-devkit/build-optimizer   0.6.1
@angular-devkit/core              0.6.1
@angular-devkit/schematics        0.6.1
@angular/animations               <error>
@angular/cli                      6.0.0 (cli-only)
@angular/forms                    <error>
@angular/http                     <error>
@angular/platform-server          <error>
@angular/router                   <error>
@angular/upgrade                  <error>
@ngtools/webpack                  6.0.1
@schematics/angular               0.6.0 (cli-only)
@schematics/update                0.6.0 (cli-only)
rxjs                              6.1.0
typescript                        2.7.2
webpack                           4.8.3

Browser:
- [X ] Chrome (desktop) version 66.0.3359.181
- [X ] Firefox version 60.0.1 

 
For Tooling issues:
- Node version: v10.0.0 
- Platform:  Mac os 10.13.4

Others:

</code></pre>

**Comment by remackgeek** [comment] 2018-05-23 15:38
@SwCon , I tried to reproduce your problem, but it seems to be working for me.
Please take a look:
https://angular-79hdjj.stackblitz.io

**Comment by SwCon** [comment] 2018-05-23 17:17
@remackgeek Thank you yes, i saw that very cool.  But I'm having trouble with stand alone web components and Angular Elements without having to specify the custom element name.  Please take a look at this if you can: https://stackblitz.com/edit/angular-u2q42g?file=src%2Fapp%2Fhero-profile.component.ts

**Comment by gkalpak** [comment] 2020-05-29 18:37
Sorry for the late response, @SwCon. Based on the reproductions you shared, it is not clear to me what you are trying to achieve and what is not working. AFAICT, loading custom elements works as expected, regardless how the templates containing them are loaded into the DOM (e.g. via a dynamic loader). Here is a [StackBlitz demo][1] (based on the [live example][2] from the current [Dynamic Component Loader][3] guide) showing a standalone custom element working as expected.

##
I am going to close this issue, since it is not actionable in its current form. If yo are still having problems, please open a new issue (referencing this one) with a minimal reproduction (and a clear description of the expected vs actual behavior).

[1]: https://stackblitz.com/edit/ngelements-issue-24044?file=src%2Fapp%2Fhero-profile.component.ts
[2]: https://angular.io/generated/live-examples/dynamic-component-loader/stackblitz.html
[3]: https://angular.io/guide/dynamic-component-loader

**Closed by gkalpak** 2020-05-29 18:37 UTC
Labels: comp: elements, freq1: low, severity2: inconvenient, type: bug/fix
