### ISSUE TITLE
TestBed.overrideComponent fails with bazel

### ISSUE THREAD

**Issue by Serginho** [angular/angular#37072] opened 2020-05-12 15:48 UTC
# 🐞 bug report

### Affected Package
@angular/compiler

### Is this a regression?
Not sure

### Description

FooComponent has a component own provider which name is FooService, so If I use overrideComponent to mock FooService, it doesn't work with bazel, but it works with angular-cli.
(See minimal Reproduction)

If I remove overrideComponent call, the code works, tests are not success, but works.

## 🔬 Minimal Reproduction
```
beforeEach(async(() => {
    TestBed
      .configureTestingModule({
        imports: [TicketListItemModule],
        declarations: [TestComponent],
        providers: [
          provideClass(ResponsiveService, ResponsiveServiceMock),
          provideClass(TranslationsService, TranslationsServiceMock),
          provideClass(GeolocationService, GeolocationServiceMock),
        ],
      })
      .overrideComponent(FooComponent, {
        set: {
          providers:
            [{provide: FooService, useClass: FooServiceMock}],
        },
      })
      .compileComponents();
  }));
```
## 🔥 Exception or Error
```
HeadlessChrome 76.0.3809 (Mac OS X 10.15.4) FooComponent Should show correct data and counter FAILED
	Failed: Component 'FooComponent' is not resolved:
	 - templateUrl: ./foo.component.html
	 - styleUrls: ["./foo.component.scss"]
	Did you run and wait for 'resolveComponentResources()'?
	Error: Component 'TicketListItemComponent' is not resolved:
	 - templateUrl: ./foo.component.html
	 - styleUrls: ["./foo.component.scss"]
	Did you run and wait for 'resolveComponentResources()'?
	    at Function.get [as ɵcmp] (core/src/render3/jit/directive.ts:69:17 <- npm/node_modules/@angular/core/bundles/core.umd.js:27324:31)
	    at getComponentDef (core/src/render3/definition.ts:739:14 <- npm/node_modules/@angular/core/bundles/core.umd.js:2049:20)
	    at verifyDeclarationsHaveDefinitions (core/src/render3/jit/module.ts:224:17 <- npm/node_modules/@angular/core/bundles/core.umd.js:27017:23)
	    at <Jasmine>
	    at verifySemanticsOfNgModuleDef (core/src/render3/jit/module.ts:194:16 <- npm/node_modules/@angular/core/bundles/core.umd.js:26992:22)
	    at packages/core/src/render3/jit/module.ts:191:5 <- npm/node_modules/@angular/core/bundles/core.umd.js:26989:13
	    at <Jasmine>
	    at verifySemanticsOfNgModuleDef (core/src/render3/jit/module.ts:189:58 <- npm/node_modules/@angular/core/bundles/core.umd.js:26987:64)
	    at Function.get (core/src/render3/jit/module.ts:148:13 <- npm/node_modules/@angular/core/bundles/core.umd.js:26950:25)
	    at R3TestBedCompiler.applyProviderOverridesToModule (packages/core/testing/src/r3_test_bed_compiler.ts:409:49 <- npm/node_modules/@angular/core/bundles/core-testing.umd.js:1622:41)

	Failed: Cannot read property 'debugElement' of undefined
	    at <Jasmine>
	    at UserContext.<anonymous> (src/apppath/foo.component.spec.ts:92:30 <- project/src/apppath/foo.component.spec.js:95:35)
	    at ZoneDelegate.invoke (node_modules/zone.js/dist/zone-testing-bundle.js:393:30)
	    at AsyncTestZoneSpec.onInvoke (node_modules/zone.js/dist/zone-testing-bundle.js:4439:47)
	    at ProxyZoneSpec.onInvoke (node_modules/zone.js/dist/zone-testing-bundle.js:3696:43)
	    at ZoneDelegate.invoke (node_modules/zone.js/dist/zone-testing-bundle.js:392:36)
	    at Zone.runGuarded (node_modules/zone.js/dist/zone-testing-bundle.js:161:51)
	    at runInTestZone (node_modules/zone.js/dist/zone-testing-bundle.js:4561:33)
	    at UserContext.<anonymous> (node_modules/zone.js/dist/zone-testing-bundle.js:4499:21)
	    at ZoneDelegate.invoke (node_modules/zone.js/dist/zone-testing-bundle.js:393:30)
	    at ProxyZoneSpec.onInvoke (node_modules/zone.js/dist/zone-testing-bundle.js:3699:43)
```

## 🌍  Your Environment

```
Angular CLI: 9.1.5
Node: 12.16.3
OS: darwin x64

Angular: 9.1.6
... animations, bazel, common, compiler, compiler-cli, core
... forms, language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.5
@angular-devkit/build-angular     0.901.5
@angular-devkit/build-optimizer   0.901.5
@angular-devkit/build-webpack     0.901.5
@angular-devkit/core              9.1.5
@angular-devkit/schematics        9.1.5
@angular/cdk                      9.2.3
@angular/cli                      9.1.5
@angular/service-worker           8.2.14+3.sha-d2f7315
@bazel/bazel                      2.1.0
@bazel/bazel-darwin_x64           2.1.0
@bazel/buildifier                 2.2.1
@bazel/hide-bazel-files           1.6.1
@bazel/ibazel                     v0.13.0
@bazel/karma                      1.6.1
@bazel/protractor                 1.6.1
@bazel/rollup                     1.6.1
@bazel/terser                     1.6.1
@bazel/typescript                 1.6.1
@ngtools/webpack                  9.1.5
@schematics/angular               9.1.5
@schematics/update                0.901.5
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0
```

Any idea what's happening?

**Comment by AndrewKushnir** [comment] 2020-05-12 19:53
Hi @Serginho, thanks for reporting the issue.

Based on the repro that you provided, it looks like the following happens:
- since `TestBed.overrideComponent` was called for `FooComponent`, Ivy TestBed tries to re-compile it in JIT mode before each test
- since `FooComponent` has `templateUrl` and `styleUrls` properties defined in the `@Component` decorator, compilation fails because the resources require async resolution, but the `resolveComponentResources` function was never called

As a possible solution, please try to use `TestBed.overrideProvider` call instead of the `TestBed.overrideComponent` one to override the `FooService` with a mocked service. For example:

```
    TestBed
      .configureTestingModule({
        imports: [TicketListItemModule],
        declarations: [TestComponent],
        providers: [
          provideClass(ResponsiveService, ResponsiveServiceMock),
          provideClass(TranslationsService, TranslationsServiceMock),
          provideClass(GeolocationService, GeolocationServiceMock),
        ],
      })
      .overrideProvider(FooService, {useFactory: () => new FooServiceMock()})
      .compileComponents();
```

The `overrideProvider` should also be a bit more performant, since it doesn't require `FooComponent` to be recompiled. Please let us know if the proposed solution worked for you.

Thank you.

**Comment by AndrewKushnir** [comment] 2020-05-12 19:59
@Serginho, could you please also provide a bit more information on which commands did you use to reproduce the issue with `bazel` and CLI commands that you used to run the same tests via CLI? If you could create a Github repository with a minimum repro, that'd be helpful as well.

**Comment by Serginho** [comment] 2020-05-13 08:12
Sure. 

Here you are: https://github.com/Serginho/TestBedOverrideComponentIssue

You can use `yarn test`or `yarn bazel test //src:test`.

**Comment by thw0rted** [comment] 2020-10-16 08:55
I'm seeing the same behavior when trying to use `overrideComponent` [as suggested here](https://github.com/angular/angular/issues/12313#issuecomment-298697327).  That issue is about problems testing `OnPush` components, and one workaround is to set the components to `Default` while testing (though obviously that has its own shortcomings).  Since I'm trying to change the `changeDetection` for the component, the suggested solution of using a different TestBed method won't help.

It sounds like this problem is likely to affect anybody running a builder for their tests -- I use Webpack, but it seems like this wouldn't be particular to any specific builder.

**Comment by AndrewKushnir** [comment] 2020-12-16 18:25
Closing this ticket since Bazel build and schematics were deprecated since v10. More info on this deprecation [can be found here](https://angular.io/guide/deprecations#bazel-builder-and-schematics). Thank you.

**Closed by AndrewKushnir** 2020-12-16 18:25 UTC
Labels: P2, comp: testing, engine: ivy, freq1: low, regression, type: bug/fix, workaround1: obvious
