### ISSUE TITLE
Add the localize package page is outdated

### ISSUE THREAD

**Issue by rubiesonthesky** [angular/angular#49219] opened 2023-02-26 20:34 UTC
### Describe the problem that you experienced

> To add the @angular/localize package, use the following command to update the package.json and polyfills.ts files in your project.

On freshly created Angular 15 project, there is no polyfills.ts file. If you are using the "ng add @angular/localize" command, then I guess it does all the necessary steps. Though, the command did not add anything to polyfills, it just added types to "tsconfig.app.json" and "tsconfig.spec.json" file.

Another problem is that, if you want to migrate your existing Angular 14 project to Angular 15 and remove "polyfills.ts" file, there is no info, how I should add localize package to project. I tried to run "ng add @angular/localize"  but I just got message "Skipping installation: Package already installed. Nothing to be done." I tried to uninstall the package first and then add it, but that did no help. I guess it's because I have dependency that needs this package and has it already installed.

I tried to consult first page https://angular.io/api/localize but it also just says to use same command.

### Enter the URL of the topic with the problem

https://angular.io/guide/i18n-common-add-package

### Describe what you were looking for in the documentation

1. How to add localize package to new project
2. How to setup localize package in existing Angular project if there is no longer polyfills.ts file

### Provide any additional information here in as much as detail as you can

```true
Just created Angular 15 project

Angular CLI: 15.2.0
Node: 14.20.0
Package Manager: npm 6.14.17
OS: darwin x64

Angular: 15.2.0
... animations, cli, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1502.0
@angular-devkit/build-angular   15.2.0
@angular-devkit/core            15.2.0
@angular-devkit/schematics      15.2.0
@schematics/angular             15.2.0
rxjs                            7.8.0
typescript                      4.9.5
```

**Comment by avmaxim** [comment] 2023-03-10 15:33
@rubiesonthesky Hi!

1. As of **polyfills** you're right, the reason we don't have this file in new projects on Angular 15 has to do with the recent changes in the Angular CLI. See these PRs for more details - https://github.com/angular/angular-cli/pull/23938 and https://github.com/angular/angular/pull/47763. Given that, the `polyfills.ts` file is no longer generated by default and only `types: ["@angular/localize"]` are added to the TS config files of the project. 

2. As of **"your issue"**, I've just replicated the steps in the sandbox and everything went likewise. There are two use cases:
      
      **Use Case 1**: W/o using `npm uninstall @angular/localize`:

    <img width="338" alt="image" src="https://user-images.githubusercontent.com/9191544/224131491-6ca7e78e-ef11-4c20-bce2-0c7112694c3f.png">

    The message saying `"Skipping installation: Package already installed."` here is an expected behavior from my point of view, because it's really nothing to be done for the CLI in terms of installation (see p.3 below). So I wouldn't say this is an issue. Just notice that the CLI updated three more files behind the scenes. 

      **Use Case 2**: Using `npm uninstall @angular/localize`:

     <img width="330" alt="image" src="https://user-images.githubusercontent.com/9191544/224265571-489ba929-e49f-485e-b302-775eb9404c51.png">
      
     In this case the error msg is displayed in view of the NPM specifcs. We should keep in mind that `ng add <package>` is not the same as `npm install <package>` so as the opposite command `npm uninstall`. `ng add <package>` uses your package manager to install the dependency and on top of that the dependency may have an installation script which can run more jobs besides the installation, for instance: update configurations, download other deps or create scaffold templates. Whereas `npm install` just installs the dependency. When we run `npm uninstall`, it just removes the dependency from node_modules. It does NOT revert what `ng add` does (and as of now Angular CLI does not provide an option to revert that).
   
   Apart from that upon uninstalling the package we have the references to it in `package-lock.json` file so far. This is a popular issue in NPM: https://github.com/npm/npm/issues/16866. In order to get `@angular/localize` package back to `node_modules`, one of the solutions below may come to the rescue:

      ```bash
      rm -f package-lock.json && npm install && ng add @angular/localize
      ```
      OR
      ```bash
      rm -rf node_modules && ng add @angular/localize
      ```
 
     ⚠️ IMPORTANT ⚠️ You will NOT encouter the same issue while using `Yarn` as a package manager. When we do `ng add @angular/localize`, followed by removing it via `yarn remove @angular/localize` and then running `ng add @angular/localize` - it works like a charm, because Yarn handles this use case in its `yarn.lock` properly.
 
3. As of **migration**, the installation procedure of `@angular/localize` as well as the usage of all entry points (eg: [@angular/localize/init](https://v14.angular.io/api/localize/init)) and primary entry point exports (eg: [types](https://angular.io/api/localize#types) and [functions](https://v14.angular.io/api/localize#functions)) stayed the same as in Angular 14. So no extra effort is needed here. You just run `ng add @angular/localize` and Angular CLI will take care of the rest. 
 
    So if you don't use the `polyfills.ts` file, feel free to get rid of it in your project as well as in the `files` section of `tsconfig.app.json` and `tsconfig.spec.json` and the `polyfills` section in the `angular.json` file. I suspect it's not removed by the CLI automatically upon your migration, because it may contain non-Angular related polyfills in it which you may still want to keep in the project.

    So @rubiesonthesky I encourage you to utilize one of the provided solutions above, then test your localization features in the project and if everything works well, it's a good sign to close this issue after merging the PR below. Should you have any additional issues, I'd love to learn and provide more assistance. Thanks!

    I've updated the documentation based on the latest implementation so you can track it in this PR - https://github.com/angular/angular/pull/49393


CC @alan-agius4 @alxhub @AndrewKushnir

**Closed** 2023-03-20 12:12 UTC
Labels: area: docs, help wanted, good first issue, docsarea: i18n
