### ISSUE TITLE
possible memory leak when using `:host-context()` selector

### ISSUE THREAD

**Issue by vladimirpotekhin** [angular/angular#54157] opened 2024-01-30 13:28 UTC
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

When moving between routes DOM nodes are constantly increasing if a component has a `:host-context` css selector with a nested sibling selector (+ or ~), for example:

```
.test-1 {
  :host-context(app-test[data-size="l"]) {
    &:hover + .t-content {
      background: red;
    }
  }
}
```

After forcing the garbage collector, nodes are not deleted. Many detached elements remain: 
<img width="556" alt="Снимок экрана 2024-01-30 в 16 14 20" src="https://github.com/angular/angular/assets/46284632/340f3aed-da84-4f1f-89c1-57a1d6a6deb8">

### Please provide a link to a minimal reproduction of the bug

https://github.com/vladimirpotekhin/min-reproduction

1. npm run start
2. switch between routes several times
3. force the garbage collector
4. domNodes increased, a lot of detached elements

If you remove the sibling selector, then everything becomes ok, the number of DOM nodes returns to the original value after calling the garbage collector 
for example, it's ok:
```
:host-context(app-test[data-size="l"]) {
    &:hover  {
      background: red;
    }
  }
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.1.1
Node: 18.18.0
Package Manager: npm 9.8.1

Angular 17.1.1
```

### Anything else?

chrome 120.0.6099.234

**Comment by JeanMeche** [comment] 2024-01-30 13:47
This is due to the debug config, you shouldn't have those if you call `enableProdMode()` in your `main.ts` for example.

**Comment by vladimirpotekhin** [comment] 2024-01-30 14:02
> This is due to the debug config, you shouldn't have those if you call `enableProdMode()` in your `main.ts` for example.

I've added `enableProdMode()` to the min reproduction repo. Unfortunately, the problem remains

**Comment by JoostK** [comment] 2024-01-30 14:21
This looks like a Chrome bug. While CSS styles are processed, the end result is mounted as regular `<style>` element. A heap dump shows only `Document` > `StyleEngine` as retainer paths, which is an internal Chrome implementation aspect.

**Comment by JeanMeche** [comment] 2024-01-30 14:24
+1 With @JoostK, I wasn't able to reproduce it consistently but when I do it's linked to the mentioned internal.

**Comment by vladimirpotekhin** [comment] 2024-01-30 14:37
Got it, thank you for replies

**Comment by jessicajaniuk** [comment] 2024-01-30 15:02
Since this is a chrome issue and not Angular, I'm going to close this. Thanks for letting us know about this, though!

**Closed by jessicajaniuk** 2024-01-30 15:02 UTC
Labels: memory leak, area: core
