### ISSUE TITLE
Bug in VSCode Angular Language Service with autocomplete (solution included)

### ISSUE THREAD

**Issue by Osolemio44** [angular/angular#43247] opened 2021-08-24 16:47 UTC
### Which @angular/* package(s) are the source of the bug?

language-service

### Is this a regression?

No

## The bug

I am doing an Angular course. I have the same plugins installed as the teacher, however autocompletion in the HTML did not work for me. (In typescript it works perfectly). I saw in the comments that it happened to a lot of people.
I attach a photo (sorry, the comments are in spanish):

![Code_Ef9T7ApQRN](https://user-images.githubusercontent.com/55595063/130656360-7ca442ea-d9f0-4ee0-847e-fd4cd7031a0b.png)

 ## The (temporary) Solution

A user of the course discovered that everything works correctly if strict typing is disabled within the plugin (it is the first option).

### Please provide the environment you discovered this bug in

```true
VSCODE: 1.59.1, 3866c3553be8b268c8a7f8c0482c0c0177aa8bfa, x64
Angular CLI: 12.2.2
Node: 14.17.4
Package Manager: npm 6.14.14
OS: win32 x64

Angular: 12.2.2
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.2
@angular-devkit/build-angular   12.2.2
@angular-devkit/core            12.2.2
@angular-devkit/schematics      12.2.2
@schematics/angular             12.2.2
rxjs                            6.6.7
typescript                      4.3.5
```

**Comment by atscott** [comment] 2021-08-24 17:14
Duplicate of https://github.com/angular/vscode-ng-language-service/issues/1479

**Closed by atscott** 2021-08-24 17:14 UTC
Labels: comp: language-service
