### ISSUE TITLE
Apply canMatch on redirect route

### ISSUE THREAD

**Issue by princemaple** [angular/angular#49145] opened 2023-02-21 03:55 UTC
### Which @angular/* package(s) are relevant/related to the feature request?

router

### Description

Currently `canMatch` doesn't seem to have any effect on a route that is a `redirectTo`. I'd like to have multiple redirects and have `canMatch` decide which one to take.

### Proposed solution

Apply `canMatch` on `redirectTo` routes as well

### Alternatives considered

N/A

**Comment by atscott** [comment] 2023-02-21 04:22
Ah, interesting request. I think this is really a workaround for the lack of having redirectTo as a function/class. Closing as a duplicate of https://github.com/angular/angular/issues/13373 which would give the desired result as well. Having redirectTo as a function feels more appropriate for this.

**Closed by atscott** 2023-02-21 04:22 UTC

**Comment by princemaple** [comment] 2023-02-21 04:25
Ah yeah, that'd work too :)
