### ISSUE TITLE
Context block in messages.xlf leaks full path (4.1.3)

### ISSUE THREAD

**Issue by cburgmer** [angular/angular#16989] opened 2017-05-24 15:08 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When running `ng-xi18n -p src/tsconfig.app.json --i18nFormat xlf` and one of the node_modules includes translatable strings, the full path of that context is written to the `messages.xlf` file:

```xml
       <trans-unit id="cedd5f9cee5d6a1681605d996cf45ab5398fabcd” datatype="html">
         <source>Source Language</source>
         <target/>
        <context-group purpose="location">
          <context context-type="sourcefile”>/Users/my_user/my_project/node_modules/my_dependency/index.ts</context>
          <context context-type="linenumber">42</context>
        </context-group>
       </trans-unit>
```

**Expected behavior**
I'd expect something along the lines of

```xml
       <trans-unit id="cedd5f9cee5d6a1681605d996cf45ab5398fabcd” datatype="html">
         <source>Source Language</source>
         <target/>
        <context-group purpose="location">
          <context context-type="sourcefile”>node_modules/my_dependency/index.ts</context>
          <context context-type="linenumber">42</context>
        </context-group>
       </trans-unit>
```

**What is the motivation / use case for changing the behavior?**
* On a team other committers will generate different output, conflicting when checking in.
* I don't want to leak my internal file structure.

**Please tell us about your environment:**
```
$ npm --version
4.2.0
$ cat package.json | grep '"@angular/compiler-cli"'
    "@angular/compiler-cli": "^4.1.3",
```

**Comment by ocombe** [comment] 2017-05-25 07:19
Yes this is something that we will fix. It's a duplicate of #16639, so I'm closing this one.

**Closed by ocombe** 2017-05-25 07:19 UTC
Labels: comp: i18n
