### ISSUE TITLE
SVG component rendered through ComponentFactoryResolver / ViewContainerRef doesn't show up

### ISSUE THREAD

**Issue by Tragetaschen** [angular/angular#20337] opened 2017-11-10 15:27 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When I dynamically render an SVG component through ComponentFactoryResolver into a ViewContainerRef, the browser doesn't render anything.

## Expected behavior
Dynamically rendered SVG components should be visible.

## Minimal reproduction of the problem with instructions
http://plnkr.co/edit/qAOHEmlQFuXjlUwAojJF?p=preview
There's only one red square when the SVG component is rendered with a component selector.
There's no square when the SVG component is dynamically instantiated.
Looking at the DOM, the only difference is the comment tag from the `ng-template`:
![image](https://user-images.githubusercontent.com/1947968/32665050-5673e0e0-c633-11e7-99d5-4601eac89a71.png)

## Environment

<pre><code>
Angular version: 5.0.[01]

Browser:
- [x ] Chrome (desktop) version XX
- [? ] Chrome (Android) version XX
- [? ] Chrome (iOS) version XX
- [? ] Firefox version XX
- [? ] Safari (desktop) version XX
- [? ] Safari (iOS) version XX
- [? ] IE version XX
- [x ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by vicb** [comment] 2017-11-14 01:42
We've done some debugging with @chuckjaz the pb is in 
```
export function createElement(view: ViewData, renderHost: any, def: NodeDef): ElementData {
  const elDef = def.element !;
  const rootSelectorOrNode = view.root.selectorOrNode;
  const renderer = view.renderer;
  let el: any;
  if (view.parent || !rootSelectorOrNode) {
    if (elDef.name) {
      el = renderer.createElement(elDef.name, elDef.ns);
    } else {
      el = renderer.createComment('');
    }
    // [HERE IS THE ROOT CAUSE]
    const parentEl = getParentRenderElement(view, renderHost, def);
    if (parentEl) {
      renderer.appendChild(parentEl, el);
    }
  } else {
    el = renderer.selectRootElement(rootSelectorOrNode);
  }
  if (elDef.attrs) {
    for (let i = 0; i < elDef.attrs.length; i++) {
      const [ns, name, value] = elDef.attrs[i];
      renderer.setAttribute(el, name, value, ns);
    }
  }
  return el;
}
```

In the second case `getParentRenderElement(view, renderHost, def);` returns null and then the `<g>` is not appended to the `<svg>`.

**Comment by billdwhite** [comment] 2018-03-06 00:59
Is there a workaround for this?

**Comment by billdwhite** [comment] 2018-08-01 20:13
Is there any update on this?

**Comment by dgroh** [comment] 2018-08-31 14:58
just came across this issue. any update regarding this?

the polyline can be seen when dragging it outside of the
![image](https://user-images.githubusercontent.com/16785357/44919956-06987600-ad3f-11e8-99f8-0f7cd614eb99.png)

the polyline above is not showing when using `ComponentFactoryResolver`

**Comment by dgroh** [comment] 2018-08-31 15:03
any workaround while this is the milestone? this is crucial for our project.

**Comment by billdwhite** [comment] 2018-08-31 17:10
Same here, waiting to see if this will ever get fixed....

**Comment by shabegger** [comment] 2018-09-19 18:28
@dgroh @billdwhite Potential workaround found on [this StackOverflow post](https://stackoverflow.com/questions/38722670/how-to-create-an-svg-component-dynamically-in-angular2/43105063#43105063). Using the SVG element is working for me.

**Comment by denis-itskovich** [comment] 2019-06-30 18:39
Seems to be related to #10404

**Comment by alexzuza** [comment] 2019-07-01 04:27
The main problem here is that Angular selector can't contain namespace for creating element
https://github.com/angular/angular/blob/f8096d499324cf0961f092944bbaedd05364eea1/packages/compiler/src/selector.ts#L11-L21

The following selector
```
selector: 'svg:g[child]',
```
will be parsed to

`<g child></g>` not to `<svg:g child></g>`

As a result Angular will use `document.createElement` instead of `document.createElementNS` to create new element.


If we use selector like `svg[child]` then it will be parsed to `<svg child>` but for `svg` tag 
Angular provided namespace manually

https://github.com/angular/angular/blob/018477e2c4a31de69554c377ed25ba291636050a/packages/compiler/src/ml_parser/html_tags.ts#L85

Angular executes the following steps during html creation:

```
const svg = document.createElementNS('http://www.w3.org/2000/svg', 'svg');
document.body.appendChild(svg);

const comment = document.createComment('');
svg.appendChild(comment);

const g = document.createElementNS('http://www.w3.org/2000/svg', 'g');

const text = document.createElementNS('http://www.w3.org/2000/svg', 'text');
text.setAttribute('x', '50%');
text.setAttribute('y', '50%');
g.appendChild(text);

const textNode = document.createTextNode('Hello');
text.appendChild(textNode);

svg.insertBefore(g, null);
```
https://jsfiddle.net/76x9kfm4/

But with only one difference

Instead of 
```
const g = document.createElementNS('http://www.w3.org/2000/svg', 'g');
```
It uses

```
const g = document.createElement('g');
```
since there is no namespace provided.

As a result svg is not rendered correctly https://jsfiddle.net/w9syoape/

**Comment by codemile** [comment] 2020-01-11 17:33
Can anyone confirm if this has been fixed in the new Ivy renderer?

**Comment by codemile** [comment] 2020-03-06 18:10
Looks like this is still not working with Ivy, and the above hack seems to not work as well.

**Comment by pkozlowski-opensource** [comment] 2020-05-26 08:40
Sadly, this is not fixed in ivy but this is _exactly_ the same problem as #10404. Closing as a duplicate of #10404, see my latest update in there: https://github.com/angular/angular/issues/10404#issuecomment-633889536

**Closed by pkozlowski-opensource** 2020-05-26 08:40 UTC
Labels: comp: core, core: dynamic view creation, cross-cutting: SVG, freq1: low, severity3: broken, type: bug/fix
