### ISSUE TITLE
Router initialNavigation disabled is ignored for pushstate after the tab crashes

### ISSUE THREAD

**Issue by intellix** [angular/angular#47785] opened 2022-10-17 10:42 UTC
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

No

### Description

We're loading routes via CMS before manually triggering an initialNavigation. Generally this works but if the browser tab crashes due to using too much memory, the page will reload but perform an initial navigation before the routes are registered, causing a white screen of death. After spending days debugging this (due to tab crashing and not being able to log anything) I've worked out that this is the ordering of events:
 - NavigationStart (popstate with restoredState) 
 - NavigationError (Cannot match any routes)
 - Add routes and call `router.initialNavigation()`

As can be seen in this screenshot:

<img width="1098" alt="Screenshot 2022-10-17 at 11 37 46" src="https://user-images.githubusercontent.com/1162531/196157161-9d73a1f4-932a-4ff0-98c8-e47beed3e0cd.png">

This is how we configure the router:
```ts
RouterModule.forRoot([], {
  initialNavigation: 'disabled',
  onSameUrlNavigation: 'reload',
  paramsInheritanceStrategy: 'always',
  scrollPositionRestoration: 'top',
  relativeLinkResolution: 'corrected',
}),
```

When comparing our site to competitors in the same industry, every other website is able to gracefully recover from a crashed tab except for ours which is the only Angular site. 

If it's expected behaviour then I'm not sure how we're meant to workaround it apart from get a white screen and expect the user ot refresh.

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular: 13.1.3
... animations, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic
... platform-server, router

Also tried with 14 and it's the same thing.
```

### Anything else?

Temporary workaround:

**route.service.ts:**
```ts
export class RouteService {
  events$ = this.router.events.pipe(shareReplay({ refCount: true, bufferSize: 1 }));
  constructor(private router: Router) {}
}
```

**cms-route.service.ts:**
```ts
// Add routes from CMS
this.router.config.unshift(...configs);
this.router.config.push({
  path: '**',
  outlet: 'primary',
  pathMatch: 'full',
  redirectTo: '',
});
this.router.initialNavigation();

// Force a navigation if an initial navigation happened before routes were registered
this.routeService.events$
  .pipe(take(1), filter(isNavigationError))
  .subscribe(event => this.router.navigateByUrl(event.url));
```

**Comment by atscott** [comment] 2022-10-17 13:41
There's quite a bit of missing information here, including a reproduction. I suspect what's actually happening is not that `initialNavigation: 'disabled',` is being ignored but that the issue is with the application's configuration. Setting `initialNavigation: 'disabled'` and manually manipulating the `config` is totally workable, but you assume the responsibility of managing this correctly in the application.

* `initialNavigation` is meant to be called _once_ in the Router to set up the `popstate` listener and navigate to the initial route. If these things have already happened, calling the method does nothing: https://github.com/angular/angular/blob/0d65e1de2c8ea76a5e48df227638cdeabac82c42/packages/router/src/router.ts#L1008-L1013
* In your logs, the `popstate` navigation could only have been triggered if the location listener was already set up. This tells me you've already called `initialNavigation` somewhere. So I'm assuming the page "refresh" isn't a hard refresh but somehow a soft refresh in a way that doesn't cause the Angular application to be recreated. Or you're actually calling `initialNavigation` multiple times another way.
* With that, your workaround of `this.routeService.events$.pipe(take(1), filter(isNavigationError)).subscribe(event => this.router.navigateByUrl(event.url));` is getting called, but it's probably the _previous_ subscription to the error, not the most recent one you might think it is.
* I'm assuming you're clearing the route config somewhere, which is why the routes aren't being matched.
* With all of the above, instead of calling `router.initialNavigation` in your `cms-route.service.ts`, which would be a no-op if `initialNavigation` was already called, you likely want something more on your `RouteService` to manage this:
```
export class RouteService {
  events$ = this.router.events.pipe(shareReplay({ refCount: true, bufferSize: 1 }));
  constructor(private router: Router, private location: Location) {}

  private initialNavigationPerformed = false;
  navigateAfterConfigChange() {
    if (!this.initialNavigationPerformed) {
      this.router.initialNavigation();
      this.initialNavigationPerformed = true;
    } else {
      this.router.navigateByUrl(this.location.path(true), {replaceUrl: true});)
    }
  }
}
```

Closing as working as expected / insufficient information based on the information provided.

**Closed by atscott** 2022-10-17 13:41 UTC
Labels: area: router

**Comment by intellix** [comment] 2022-10-17 16:44
There's only 1x instance of `router.initialNavigation()` in my whole app (CTRL+F confirms it) and I'm logging `add 68 routes` before. This method is also the only place where routes are set inside config and the fact there's only 1x log means it only ran once. 

My workaround works as expected and has been verified as having fixed the issue by 2x manual QA and e2e. 

The refresh is the entire tab crashing (iOS says there has been an issue and does some sort of refresh). 

I'll try and work on a reproduction but I'll need to find a way to crash the tab and we're also only witnessing it in iOS... please don't lock this issue so I can attach the repro

**Comment by atscott** [comment] 2022-10-17 16:59
> please don't lock this issue so I can attach the repro

You can open a new issue if/when you have more information. There's not anything actionable for us in this issue so there's no reason to keep it open.

> My workaround works as expected and has been verified as having fixed the issue by 2x manual QA and e2e.

I'm not disputing that it resolved the issue you were having. From what I understand, it _would_, but potentially not in the way you expect (again, I can't tell for sure because there's not enough information here).

Have you tried the `navigateAfterConfigChange` fix I suggested instead of unconditionally calling `initialNavigation`?
