### ISSUE TITLE
Router. EXCEPTION: Expression has changed after it was checked.

### ISSUE THREAD

**Issue by nglazov** [angular/angular#6006] opened 2015-12-18 15:08 UTC
I use [routerLink]="someFunction('Route')"
```javascript
someFunction(a) {
  return [a]
}
```
This is [example](http://embed.plnkr.co/vTmlwo2LP2sQ3NCCp4VH/) which was taked from [docs](https://angular.io/docs/ts/latest/guide/router.html) and was changed just app/app.component.ts.

**Comment by wardbell** [comment] 2015-12-18 19:30
While I believe that ought to work ... and we're looking into it ... I can't find that example anywhere in the docs. Would you please find that location for me?

**Comment by wardbell** [comment] 2015-12-18 21:36
Anyway, the reason you're getting this error now is because, in DevMode (which is the default), Angular runs your fn 2x ... once the normal time, and once again during a check to ensure that you aren't changing things that shouldn't change during the same view-generation pass.

Semantically, you're not changing anything.  You're specifying the same route `[a]` each time. 

But technically you're returning a ***different array** each time.

The solution (for now) is to run your fn inside your component, capture its value in a component property, and bind to that property instead.

Here's some pseudo-code:

```
<!-- Template HTML -->
...[RouterLink]="theRoute" ...

// Component
theRoute: RouterLink;
...
theRoute = someFunction(whatever);
```

**Comment by nglazov** [comment] 2015-12-18 22:30
I mean live example from docs.
Yes, i've tried this before and function will be called 10 times [(example)](http://plnkr.co/edit/LSCEfYxSJIRJAkijy9sc?p=preview).

**Comment by wardbell** [comment] 2015-12-19 19:39
I searched the code and couldn't find `[routerLink]="getLink()"`. I think I understand the problem. I think you have an old plunker from an earlier version of the doc. If you click the [live example](https://angular.io/resources/live-examples/router/ts/plnkr.html) link now, you'll get a different result.

The problem is real. But it's not in the router doc.  I think we should close this one.

**Comment by nglazov** [comment] 2015-12-19 21:26
Oh yeah, it's not from doc. I've forked example and have changed it.
The problem is to use function as input parameter in routerLink directive.

**Comment by nglazov** [comment] 2015-12-21 15:13
@wardbell you're right! I've changed life example from doc, to show you a problem. When i use function as parameter of routerLink directive - this function would be called a lot of times

**Comment by pkozlowski-opensource** [comment] 2016-01-22 14:39
Same as https://github.com/angular/angular/issues/6005

**Closed by pkozlowski-opensource** 2016-01-22 14:39 UTC
