### ISSUE TITLE
ngOnChanges declared in mixin-class,when build --prod,can`t be called

### ISSUE THREAD

**Issue by wszgrcy** [angular/angular#31648] opened 2019-07-19 08:00 UTC
# 🐞 bug report

### Affected Package
@angular/cli ?(ng servce Yes,ng build --prod No)

### Is this a regression?
In angular 7/8 can`t run,below 7 no test

### Description
component  extends mixin-class
```ts
import { SimpleChanges } from '@angular/core';
export class MixinBase {
    constructor(...args) { }
}
export function base(base) {
    return class extends base {
        name = 'c2'
        aaaa
        ngOnChanges(changes: SimpleChanges): void {
            console.log(this.name);
            console.log(changes, this.aaaa);
        }
    }
}
export const Base = base(MixinBase)
```
When I change a property`value, @Input() trigger,ngOnchanges trigger in `ng serve`,
But,after`ng build --prod`,@Input() trigger,ngOnchanges no-trigger

## 🔬 Minimal Reproduction
[bug-project](https://github.com/wszgrcy/ngOnChanges-don-t-run)
code in `ng serve` is fine ,so must `ng build --prod`or`ng serve --prod`

## 🔥 Exception or Error
mixin-class can run with normal class,when component extends them;

## 🌍  Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 8.0.6
Node: 10.15.3
OS: win32 x64
Angular: 8.0.3
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.6
@angular-devkit/build-angular     0.800.6
@angular-devkit/build-optimizer   0.800.6
@angular-devkit/build-webpack     0.800.6
@angular-devkit/core              8.0.6
@angular-devkit/schematics        8.0.6
@angular/cli                      8.0.6
@ngtools/webpack                  8.0.6
@schematics/angular               8.0.6
@schematics/update                0.800.6
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.30.0

</code></pre>

**Anything else relevant?**
no

**Comment by trotyl** [comment] 2019-07-19 10:37
Duplicate of https://github.com/angular/angular/issues/19145

**Comment by pkozlowski-opensource** [comment] 2019-07-20 06:04
It is indeed duplicate of #19145, thank you @trotyl !

**Closed by pkozlowski-opensource** 2019-07-20 06:04 UTC
