### ISSUE TITLE
angular2.min.js is not equivalent to angular2.js

### ISSUE THREAD

**Issue by glentakahashi** [angular/angular#7896] opened 2016-04-04 00:27 UTC
I ran into a bug today where including angular2.min.js would result in my code failing but using angular2.js would run fine.

Example plunkr here: http://plnkr.co/edit/599t9vXIoDWvERnvCTWu?p=preview

In it's current state the [(ngModel)] bind fails so the text box gets no data, but if you switch the page to load angular2.js instead of angular2.min.js the text box will load just fine.

**Comment by zoechi** [comment] 2016-04-04 05:42
Issues with minified files were reported a few times already https://github.com/angular/angular/search?q=minified&type=Issues&utf8=%E2%9C%93

See also #7452

**Comment by pkozlowski-opensource** [comment] 2016-04-04 06:19
Closing as duplicate of #6380

**Closed by pkozlowski-opensource** 2016-04-04 06:19 UTC
