### ISSUE TITLE
"TypeError: Cannot read property 'kind' of undefined" when executing ng-xi18n

### ISSUE THREAD

**Issue by marclerman** [angular/angular#11789] opened 2016-09-21 13:30 UTC
**I'm submitting a ...**  (check one with "x")

```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 
When I execute ng-xi18n, I get the following:

TypeError: Cannot read property 'kind' of undefined
    at maybeGetSimpleFunction (C:\SL\src\Clientnode_modules\@angular\tsc-wrapped\src\collector.js:34:41)
    at C:\SL\src\Clientnode_modules\@angular\tsc-wrapped\src\collector.js:242:41
    at visitEachNode (C:\SL\src\Clientnode_modules\typescript\lib\typescript.js:8247:30)
    at Object.forEachChild (C:\SL\src\Clientnode_modules\typescript\lib\typescript.js:8407:24)
    at MetadataCollector.getMetadata (C:\SL\src\Clientnode_modules\@angular\tsc-wrapped\src\collector.js:204:12)
    at ReflectorHost.getMetadataFor (C:\SL\src\Clientnode_modules\@angular\compiler-cli\src\reflector_host.js:224:43)
    at StaticReflector.getModuleMetadata (C:\SL\src\Clientnode_modules\@angular\compiler-cli\src\static_reflector.js:484:40)
    at Extractor.readFileMetadata (C:\SL\src\Clientnode_modules\@angular\compiler-cli\src\extract_i18n.js:50:51)
    at C:\SL\src\Clientnode_modules\@angular\compiler-cli\src\extract_i18n.js:87:74
    at Array.map (native)
Extraction failed

**Expected behavior**
At least a better error message, or an actual xlif output.

**Reproduction of the problem**
I do not have a simple repro. At least understanding what the problem could be would help.
## **What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
Windows.
- **Angular version:** 2.0.0
- **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
  n/a
- **Language:** [all | TypeScript X.X | ES6/7 | ES5]
  n/a
- **Node (for AoT issues):** `node --version` =  
  n/a

**Comment by wiredprogrammer** [comment] 2016-09-21 14:34
I'm getting the same typescript error when running the AoT compiler.  The typescript compiler compiles fine so I have no idea where to start looking to fix this.

**Comment by vicb** [comment] 2016-09-21 15:45
Both errors are due to AoT, i18n and ngc both use the same code path.

**Comment by chuckjaz** [comment] 2016-09-21 16:12
@marclerman From the error it looks like the problem in our code, not yours.  It would be very helpful if you could provide a repro, simple or not.

**Comment by panuruj** [comment] 2016-09-22 22:59
Have you tried passing "-p tsconfig.js" to the ng-xi18n?

**Comment by wiredprogrammer** [comment] 2016-09-30 20:56
I think my problem may be due to using default exports.
http://stackoverflow.com/questions/39190493/get-cannot-read-property-type-of-null-using-angular2-aot-ngc-compiler-with-r
I'm recoding to name all my exports.
Hope this helps.

**Comment by marclerman** [comment] 2016-10-03 07:34
@panuruj Yes, I tried "-p tsconfig.json" but that did not help.
@chuckjaz I have not started working on a repro yet, but I have a feeling that @wiredprogrammer's suggestion is going to be the one. Will keep you posted.

**Comment by marclerman** [comment] 2016-10-04 14:55
@wiredprogrammer is right. The problem is default exports...

**Comment by wiredprogrammer** [comment] 2016-10-04 15:27
This is a good right up on what to look for to make your app AoT friendly.
https://medium.com/@isaacplmann/making-your-angular-2-library-statically-analyzable-for-aot-e1c6f3ebedd5#.2p5ul5txt

**Comment by DeeM297** [comment] 2016-10-04 15:43
Hi,
Where are you changing the default exports? In your code or in the individual node_modules? It's funny, I have the same errors with exact line numbers.

> ngc error: TypeError: Cannot read property 'kind' of undefined
>     at maybeGetSimpleFunction (c:\XXX\node_modules\@angular\tsc-wrapped\src\collector.js:34:41)
>     at c:\XXX\node_modules\@angular\tsc-wrapped\src\collector.js:242:41
>     at visitEachNode (c:\XXX\node_modules\typescript\lib\typescript.js:8251:30)
>     at Object.forEachChild (c:\XXX\node_modules\typescript\lib\typescript.js:8411:24)
>     at MetadataCollector.getMetadata (c:\XXX\node_modules\@angular\tsc-wrapped\src\collector.js:204:12)
>     at ReflectorHost.getMetadataFor (c:\XXX\node_modules\@angular\compiler-cli\src\reflector_host.js:224:43)
>     at StaticReflector.getModuleMetadata (c:\XXX\node_modules\@angular\compiler-cli\srcstatic_reflector.js:484:40)
>     at CodeGenerator.readFileMetadata (c:\XXX\node_modules\@angular\compiler-cli\src\codegen.js:36:51)
>     at c:\XXX\node_modules\@angular\compiler-cli\src\codegen.js:100:74
>     at Array.map (native)

**Comment by marclerman** [comment] 2016-10-04 15:45
You have to change them in your own code.

**Comment by DeeM297** [comment] 2016-10-06 19:17
I have rootReducer.ts file where I'm using _export default_. Do you know how to changed to a -named export_?

```
import { combineReducers, Reducer } from 'redux'
import song from './reducers/song-reducer'

export default combineReducers({
  song
})
```

**Comment by DeeM297** [comment] 2016-10-07 17:29
I've created a minimum ionic2 project with redux/redux-thunk on git:
https://github.com/DeeM297/ionic-redux-test

These are all the steps to build the project from an ionic2 tab starter 
`ionic start myIonicProject tabs --v2 --ts`

**_redux_ & _redux-thunk_ installation in the starter tab project.**
`npm i redux redux-thunk --save`
`npm install @types/request@0.0.30 --save-dev --save-exact` (I'm using 0.0.30 because of AngularFire2)
`npm i @types/redux @types/redux-thunk --save`

**Changes to the starter project**
1) In **app.module.ts**, just before @NgModule
```
//Redux - ReduxThunk - rootReducer
import { createStore, applyMiddleware } from 'redux';
import ReduxThunk  from 'redux-thunk';
import rootReducer from '../modules/rootReducer';

const appStore = createStore(
    rootReducer,
    applyMiddleware(ReduxThunk)
);
```
And adding this in the providers array:
```
providers: [
    { provide: 'AppStore', useValue: appStore }
]
```

2) I'm creating a module folder with two files: increment-reducer.ts and rootReducer.ts
**In increment-reducer.ts** 
```
import { Action } from 'redux'

const initialState = {
	counter: 0
}

export default function (state = initialState, action: Action) {
	switch (action.type) { 
		case 'INCREMENT':
			let newState = Object.assign({}, state);
			newState.counter++;
			return newState;
		default:
			break;		
	}
	return state;
}
```
**In rootReducer.ts**
```
import { combineReducers, Reducer } from 'redux'
import increment from './increment-reducer'

export default combineReducers({
  increment
})
```
3) Final changes in home.ts and home.html
**In home.html**
```
<!-- TEST FOR REDUX -->
<button ion-button (click)="testRedux()">
	Increment
</button>
```
**In home.ts**
```
constructor(
    public navCtrl: NavController,
    @Inject('AppStore') public appStore: any
    ) { }

  testRedux(){
        console.log(this.appStore.getState().increment.counter);
        this.appStore.dispatch((dispatch)=> {
            dispatch({type: 'INCREMENT'});});
        console.log(this.appStore.getState().increment.counter);
    }
```
And import _inject_ in home.ts
`import { Inject, Component } from '@angular/core';`

When running the project with `npm run build`, it gives the same error as above. I hope this can help.

You can see the whole project [here on git][1]
  [1]: https://github.com/DeeM297/ionic-redux-test

**Comment by wiredprogrammer** [comment] 2016-10-07 19:22
@DeeM297 
The article I linked has examples of how to migrate to named exports from default exports.
https://medium.com/@isaacplmann/making-your-angular-2-library-statically-analyzable-for-aot-e1c6f3ebedd5#.2p5ul5txt

**Comment by DeeM297** [comment] 2016-10-08 16:41
I've seen the link but was stuck on some of the changes. I've finally been able to solve everything. Thanks.

**Comment by petrvojta** [comment] 2016-10-13 18:55
In case of ionic2 rc0 error `ngc error: TypeError: Cannot read property 'kind' of undefined` this article   describe the solutions http://stackoverflow.com/questions/39190493/get-cannot-read-property-type-of-null-using-angular2-aot-ngc-compiler-with-r

**Comment by wiredprogrammer** [comment] 2016-10-14 19:51
That was linked to about 6 comments down from the top.

**Comment by stanbe** [comment] 2016-11-29 08:01
Is there any update on this bug?

**Comment by ikocev** [comment] 2016-12-11 21:36
Any update? I got the same bug. Just installed with the command following from the original angular2 doc:
`npm install @angular/compiler-cli @angular/platform-server --save`
and run it, getting the same error.

**Comment by chuckjaz** [comment] 2017-03-03 22:56
Duplicate of #12020.

**Closed by chuckjaz** 2017-03-03 22:56 UTC
Labels: hotlist: error messages, type: bug
