### ISSUE TITLE
Default ErrorHandler not displaying errors in the console

### ISSUE THREAD

**Issue by jakehockey10** [angular/angular#40366] opened 2021-01-08 19:00 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/core

### Is this a regression?

 Yes, the previous version in which this bug was not present was: I'm not sure.  I never really looked into why the errors weren't displaying until now, as I first assumed the change was deliberate and I didn't consider it necessary to look into immediately.  My best guess is version 8 or 9 was the last time I saw errors displayed in the console.

### Description

The issue I'm experiencing is that the default `ErrorHandler` is not displaying errors in the console like it used to.  The documentation and implementation still claims that the default implementation should display in the console, so this leads me to believe that my project is doing something wrong.

But if I use my own `ErrorHandler` as described in the documentation and display the error in the console, I do indeed see the errors in the console.

This started happening to my project several major versions ago, but I assumed it was a deliberate change and just now started looking into it.

## 🔬 Minimal Reproduction

Unfortunately, I'm unable to reproduce this in a stackblitz.  I tried to, but the errors display just fine in the console there with a trivial application.  I tried to interpolate `array.length` while never setting `array` to anything in the component's code-behind (is that the right terminology?)

Since issues without a repro case are closed, I'm hoping I could at least get some insight in how to investigate this further before it is closed as I am at a loss.

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

 ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 11.0.5
Node: 12.13.1
OS: win32 x64

Angular: 11.0.2
... animations, common, compiler, core, forms, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.5
@angular-devkit/build-angular   0.1100.5
@angular-devkit/core            7.3.10
@angular-devkit/schematics      7.3.10
@angular/cdk                    11.0.0
@angular/cli                    11.0.5
@angular/compiler-cli           11.0.0
@angular/language-service       11.0.0
@schematics/angular             8.3.28
@schematics/update              0.1100.5
rxjs                            6.6.3
typescript                      4.0.5
</code></pre>

**Anything else relevant?**

**Comment by gkalpak** [comment] 2021-01-08 19:20
The default `ErrorHandler` does indeed log the errors in the console. I would start by adding a break point in [ErrorHandler#handleError()][1] and see if it gets hit (then step through the code to see what happens and why there is no log in the console). If it doesn't get hit, I would try to find out (e.g.  by stepping through the code in the debugger) where the code path deviate from when you add your own `ErrorHandler` (which as you said _does_ log errors to the console).

I am going to close the issue, since it is not actionable for use without a reproduction (as you already know :grin:), but feel free to continue the discussion below. (Keep in mind, though, that there's little we can do without getting our hands on a reproduction :wink:)

[1]: https://github.com/angular/angular/blob/e05ac395fc82625e3bd00c7d06e1ef5ceb13251b/packages/core/src/error_handler.ts#L44

**Closed by gkalpak** 2021-01-08 19:20 UTC
Labels: comp: core, needs reproduction

**Comment by jakehockey10** [comment] 2021-01-08 20:14
@gkalpak I finally found where to put the breakpoint, and here is the weirdest part: the breakpoint is never hit.  It's almost like if I don't provide my own `ErrorHandler`, one isn't used?

**Comment by jakehockey10** [comment] 2021-01-08 20:19
@gkalpak son of a gun.  I found it.  ApplicationInsights for azure was added to a project a while back, and that is how you use it, the instruct you to take over the default ErrorHandler.  BUMMER.

Is there was way to have a pipeline of ErrorHandlers?  Aka more than one registered?  Similar to HttpInterceptors, I'm thinking

**Comment by jakehockey10** [comment] 2021-01-08 20:26
I've added a call to `super.handleError(error)` in the custom error handler someone wrote for Application Insights, but I get a second error from this call.  Here is the custom error handler:
``` typescript
import { ErrorHandler, Injectable } from '@angular/core';

import { AppInsightsService } from './app-insights.service';

@Injectable({
    providedIn: 'root',
})
export class ErrorHandlerService extends ErrorHandler {
    constructor(private readonly _appInsights: AppInsightsService) {
        super();
    }

    handleError(error: Error) {
        super.handleError(error);
        this._appInsights.logException(error); // Manually log exception
    }
}
```
and here is the error:

``` console
TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Zone'
    |     property '_zoneDelegate' -> object with constructor 'ZoneDelegate'
    --- property 'zone' closes the circle
    at JSON.stringify (<anonymous>)
    at console.window.console.error (<anonymous>:39:101)
    at defaultErrorLogger (core.js:5973)
    at ErrorHandlerService.handleError (core.js:6021)
    at ErrorHandlerService.handleError (error-handler.service.ts:14)
    at Object.next (core.js:28788)
    at SafeSubscriber.schedulerFn [as _next] (core.js:25601)
    at SafeSubscriber.__tryOrUnsub (Subscriber.js:183)
    at SafeSubscriber.next (Subscriber.js:122)
    at Subscriber._next (Subscriber.js:72)

```

**Comment by gkalpak** [comment] 2021-01-09 17:12
There is no built-in way to provide multiple `ErrorHandler`'s, but there is nothing stopping you from calling multiple methods from your custom `ErrorHandler` (such as `super.handleError()` if you are extending the default `ErrorHandler`) :wink:

Unfortunately, I can't say much about the error you are getting from `super.handleError()` without a reproduction 🤷‍♂️

**Comment by jakehockey10** [comment] 2021-01-09 18:55
Yea fair enough
