### ISSUE TITLE
Async Module Loading Not Known At Compile time

### ISSUE THREAD

**Issue by bh3605** [angular/angular#40172] opened 2020-12-17 14:47 UTC
# 🚀 feature request
Async Module Loading Not Known At Compile Time

### Relevant Package
This is for @angular/core

### Description
Angular is able to compile away a lazy loaded module into a separate bundle. This module was known at compile time. The spirit of this ask to allow a module to be cloud hosted and able to be pulled down and integrated/loaded into a compatible Angular application. The scope of this feature request is limited to components and routing.

### Why it does not work right now
When both host and lazy module are using Ivy there is not a shared instruction state. The lazy module was loaded in a similar way as the host, but there were certain components related to Ivy that were not. Undefined errors are thrown when the component's template is rendered. See ɵɵelementStart() as an example. The lazy module's tView will be undefined causing a "Cannot read property 'bindignStartIndex' of undefined' error to be thrown.

When the host is using Ivy and the lazy module is using View Engine then the host will not be able to load the lazy module due to the epsilon module properties not being defined. The host is unable to recognize the module.

When the host is using View Engine it will disallow the loading of the lazy module completely saying this isn't allowed.

### Describe the solution you'd like
Using SystemJs or other similar library, lazy load a module. Develop a new method of initializing the Ivy rendering components that will initialize the tView and lView.

Modules are compiled differently when using the View Engine (instead of Ivy). Allow the host the load a module such that asynchronous module compiling is allowed. For some reason the compiler is not loaded and the method is purposely assigned a method to throw an error describing this isn't allowed.

### Describe alternatives you've considered
Turning Ivy on/off in both host and lazy loaded module. Single Spa has this figured out. It manages the lifetime of an application and switches them out based on the route. This solution would allow an Angular application (not known at compile time) to run inside of another Angular application.

**Comment by alxhub** [comment] 2020-12-17 17:55
Hello @bh3605,

Thank you for the feature request! I'm happy to report that this is actually technically possible with Angular today. The challenge to make an "asynchronous module loading" setup work is to build the application and the module in the right way.

Consider a basic scenario with an application and a single lazily loaded NgModule with its component(s). There are 3 pieces to this system: the application code, the lazily loaded code (the NgModule and its components), and any shared dependencies such as the Angular runtime or any shared components/directives/etc used by both the static app and the lazily loaded pieces. The challenge is to ensure that when built and deployed, the shared pieces are loaded along with the app, but available for consumption by the module when lazily loaded. Additionally, we'll need to make sure that any code within for example the Angular runtime is not tree-shaken if needed by the lazily loaded part, even if it's not used directly by the app.

This is a non-trivial deployment scenario - most JavaScript tooling is not really designed to handle such complex deployments. The Angular CLI definitely does not support this use case.

However, support for exactly this kind of setup is available with Webpack 5 - Webpack calls it [Module Federation](https://webpack.js.org/concepts/module-federation/), an implementation of a "Micro-Frontend Architecture". I've played around with it a fair bit and have been able to build exactly the system you describe - an NgModule, built separately from an application, which is able to be hosted on a separate server and loaded lazily into a running application.

Note that this still means that the lazily loaded NgModule is built to be loaded into the specific app in question, and both must be built with Module Federation enabled. Deploying a "general purpose" NgModule requires a different approach - using ES Modules directly in the browser. It's been a while since I've played with doing that (likely via SystemJS) but it should in theory be possible too.

**Comment by bh3605** [comment] 2020-12-17 19:00
@alxhub I got really close! It's cool to read it's technically feasible. What I originally tried to do is build and serve an Angular library since that's in theory easier to be consumed, but I can't `ng serve --LibraryProject` because one of the options is always defined causing the builder to throw an error. I forget which option it is. I went serving an Application instead. I do, however, have one prototype where I'm using a webpack setup and exporting out the Library's LibraryModule in the Application's main.ts.

I was able to get the host's router instance injected in via injection token to get the lazy module to use that over its created instance. I also needed to inject the ROUTES token into the library so when the host tries to get the library's ROUTES token it grabs it's type of the ROUTES token and not the lazy module's. I also had to inject the host's ApplicationRef as well, and create an injector just so the lazy module had something it could compile with by the host.

I feel really dumb now for deleting that prototype now. Here's how I was loading it. Had to install angular-builders/custom-webpack and turned off it parsing out any systemjs reference. Why that's a thing I will never understand. I only started using Angular in 2018 when Angular Libraries just came out.

I used SystemJs to do the importing. Specified a systemjs mapping too in the index.html file.

    loadChildren: System.import("MyLibrary").then(m => {m.MyLibrary.forRoot(applicationRef, router, ROUTES)}
---
    static forRoot(applicationRef: ApplicationRef, router: Router, routes: InjectionToken<Route[]>) {
        esetCurrentInjector(ecreateInjector({provide: ApplicationRef, useValue: applicationRef}));
        AppModule[ɵNG_INJ_DEF].providers.push(
        {provide: ROUTES, useValue: routes, multi: true},
        {provide: Router, useValue: router}
        );
        return AppModule;
    }

What about Module Federation? Single spa has documentation saying you can specify all of the core Angular dependencies to not be bundled. You'd have to inject or use script tags to get the dependencies available then. Are you suggesting having both of them leave out the core dependencies?

**Comment by alxhub** [comment] 2020-12-17 22:58
@bh3605 Module Federation handles the linking of shared dependencies at runtime, as various modules are loaded. It's really cool, actually. [Here's an example](https://github.com/alxhub/module-fed-example) I built a while back of an application loading a module dynamically from another server. It's a simple test thing I built so it's not very well documented, but you should be able to build everything with the build script, run both serve scripts, and load the app at port 8080.

**Comment by teosbb** [comment] 2021-03-11 16:00
Are there any updates on integrationg Webpack 5 Module Federation into angular (official) > Microfrontend support ?

**Comment by alxhub** [comment] 2021-07-09 22:54
Just so we have a single issue tracking this request on Github, I'm going to close this as a duplicate of #35081.

**Closed by alxhub** 2021-07-09 22:54 UTC
Labels: comp: compiler, feature, insufficient votes, votes required
