### ISSUE TITLE
Make QueryList.changes a ReplaySubject of the array of results

### ISSUE THREAD

**Issue by ajoslin** [angular/angular#9078] opened 2016-06-08 06:14 UTC
I opened a PR to go with this issue: #9079
- **I'm submitting a ...**
- [ ] bug report
- [x] feature request (#9079)
- [ ] support request => Please do not submit support request here, see note at the top of this template.

**Current behavior**

Currently, I want to get the first value out of a `QueryList` and, each time there's a change, get the new first value out. 

This is very cumbersome for two reasons:

(1) The current `changes` observable does not emit any values until a change happens
(2) When it does emit, the `changes` observable emits no relevant values.

After this change, the `changes` observable, when subscribed to, will emit the current array of results, and on each change emit the new array of results.

**My code before the change**

``` js
  ngAfterContentInit () {
    const handleFirst = () => {
      const first = this.queryList.first
      if (first) { 
        doSomething(first)
      }
    }

    handleFirst()
    this.queryList.changes.subscribe(handleFirst)
  }
```

**My code after the change**

``` js
ngAfterContentInit () {
  this.queryList.changes
    .take(1)
    .subscribe(doSomething)
}
```
- **Angular version:** 2.0.0-rc.1
- **Browser:** all
- **Language:** all

**Comment by matsko** [comment] 2016-07-19 00:47
Hello Andrew.

**Comment by tbosch** [comment] 2016-11-11 22:34
Closing as the issue is contained in https://github.com/angular/angular/issues/12818.

**Closed by tbosch** 2016-11-11 22:34 UTC
Labels: comp: core & compiler, type: feature
