### ISSUE TITLE
limitation in ngFor

### ISSUE THREAD

**Issue by Rehan1579** [angular/angular#19726] opened 2017-10-14 15:37 UTC
I'm new to Angular 4 and finding issues in using ngFor. I want to have dynamic textInputs with binding. The number of textinputs ca vary and depends on user input.

here's my code.

```
<div *ngFor="let ans of answers">
     <input [(ngModel)]="ans">
</div>
```
    
i got this error.

![image](https://user-images.githubusercontent.com/11446280/31576823-b9ff8ec4-b11c-11e7-9849-f4836321333c.png)

Then i tried following code:

```
<div *ngFor="let ans of answers; index as i;">
     <input [(ngModel)]="answers[i]">
</div>
```

```
<div *ngFor="let ans of answers.concat(); index as i;">
     <input [(ngModel)]="answers[i]">
</div>
```

This time, i didn't get the error but the behavior was unexpeacted. when i type something in 1st input, my 2nd input gets populated too & writing in 2nd input also fills the 3rd input and i constantly keep losing focus on in the input.

![image](https://user-images.githubusercontent.com/11446280/31576916-bcd1386c-b11e-11e7-8727-cec85e382566.png)

what should i do, where i'm doing it wrong ?

**Comment by msarsha** [comment] 2017-10-15 06:51
`let ans` will create a local variable.

`ngModel` will only work on properties of your component - that's why `answers[i]` works.

Regarding your second issue, is `answers` an `Array` or `Object`?

Try adding `trackBy` to the `ngFor` statement. [docs](https://angular.io/guide/template-syntax#ngfor-with-trackby)

**Comment by mlc-mlapis** [comment] 2017-10-15 09:22
@Rehan1579 ... look at the simple demo: https://plnkr.co/edit/ZB62YrCH02wDVcqZBreS?p=preview

Directive `*ngFor` manipulates with DOM ... inserting and removing nodes and `trackBy` is the key for `*ngFor` to understand which node is which and not removing all nodes first and then inserting them again on each Change Detection (CD) cycle ... and loosing focus of course by that ... and entering any char to any input invokes a new CD cycle.

**Comment by albertosantini** [comment] 2017-10-26 17:53
Apart a few minor details, really it should work out-of-box.

```
<div *ngFor="let foo of quux">
  <input type="text" [(ngModel)]="quux[i]" />
</div>
```

Just like in Vue
```
<div v-for="(inp, index) in inputs">
  <input v-model="inputs[index]" />
</div>
```
The end user, the programmer, should not be compelled to use a `trackBy` hack or to choose between an array of objects and an array of primitives.

I don't understand if it is `by design` or a bug?

Live Example for Angular: https://stackblitz.com/edit/angular-l2uauw
Live Example for Vue and hyperHTML: http://plnkr.co/edit/RUvsemlr4UNSCgFw3wQ1?p=preview

**Comment by trotyl** [comment] 2017-10-27 01:38
It has been discussed at #9218.

Angular uses "trackBy reference" (keyed) implementation by default, and this is a valid and consistency behavior, and user can manually use "trackBy index" (non-keyed) if they want.

The fact is, keyed tracking is considered the correct implementation while non-keyed one is usually called naive implementation, likely could cause unexpected behavior in many cases.

There are indeed some frameworks using non-keyed implementation by default, it's a design choice, and Angular decided not to use that, please checkout [JS web frameworks benchmark – keyed vs. non-keyed](http://www.stefankrause.net/wp/?p=342) and [Index as a key is an anti-pattern](https://medium.com/@robinpokorny/index-as-a-key-is-an-anti-pattern-e0349aece318#.qgzvk154k) for more information.

**Comment by albertosantini** [comment] 2017-10-27 15:28
@trotyl  Thanks a lot for the details.

@Rehan1579 the actionable item was done (note in the docs) and tech details provided. 
Please, shall you close the issue?

**Comment by trotyl** [comment] 2017-10-27 15:44
Duplicate of #8602, #17144, #19819. Since #17144 is still open, this should be closed anyway.

**Closed** 2017-10-28 05:15 UTC
Labels: comp: common
