### ISSUE TITLE
Provider factory not accessible by compiler if exported in 3rd party module

### ISSUE THREAD

**Issue by meeroslav** [angular/angular#13292] opened 2016-12-07 22:31 UTC
If factory function used to initialise provider is defined and exported in 3rd party module, compilation fails due to wrong path import set to function in ngFactory.

![screen shot 2016-12-07 at 23 22 25](https://cloud.githubusercontent.com/assets/881612/20989184/13c1a980-bcd4-11e6-97e6-7ff70939c27d.png)

And in app.module.ngFactory:

![screen shot 2016-12-07 at 23 28 22](https://cloud.githubusercontent.com/assets/881612/20989420/e29ad61e-bcd4-11e6-8f8e-a2f346f5f4bb.png)
![screen shot 2016-12-07 at 23 26 25](https://cloud.githubusercontent.com/assets/881612/20989341/991f99b6-bcd4-11e6-9aef-d42ccdd60dc4.png)
![screen shot 2016-12-07 at 23 27 45](https://cloud.githubusercontent.com/assets/881612/20989406/cfd2d874-bcd4-11e6-8df6-caa86530e92d.png)

If this is by design, I would like to know story behind it.

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
If provider factory is not included in app.module, compiler fails generating proper ngFactory by linking the factory function to random path instead of node module.

**Expected behavior**
Compilation should be successful even if provider is not directly exposed in `app.module` as long as it's properly exported in its own module.

**Minimal reproduction of the problem with instructions**

1. clone `https://github.com/meeroslav/universal-localize-example`
2. npm install
3. remove exported function `localizeLoaderFactory` from app.module.ts
4. modify import of `LocalizeRouterModule` to only first param:

```
LocalizeRouterModule.forRoot(routes)
``` 
5. `ung build --aot` 
* **Please tell us about your environment:** OSX, Webstorm, NPM

* **Angular version:** ^2.1.0

* **Browser:** all
 
* **Language:** all

* **Node (for AoT issues):** `node --version` = 6.9.2

**Comment by vicb** [comment] 2016-12-07 23:03
Please attach a small repro

**Comment by meeroslav** [comment] 2016-12-07 23:23
@vicb Not sure how small you need. You can try this small demo built with CLI: 
1. clone `https://github.com/meeroslav/localize-router-example`
2. npm install
3. ng build --aot

That's the smallest I can do without publishing a new dummy package.

**Comment by vicb** [comment] 2016-12-07 23:26
thanks

**Comment by tbosch** [comment] 2016-12-28 20:22
Hello,
I tried to reproduce this bug. First I cloned your repo and got the error `ERROR in Error encountered resolving symbol values statically. Calling function 'NoOpAnimationDriver'`. 

This is because your `tsconfig.json` does not specify any files, and therefore AoT tries to compile all of your files in `src`, including the tests which refer to test only modules that are not AoT compatible.

You can do the following:

- add `"files": "main.ts"` to your tsconfig.json to exclude the tests
- upagrade to angular-cli 1.0.0-beta.24.

**Closed** 2017-01-27 14:14 UTC
Labels: comp: core & compiler, flag: can be closed?
