### ISSUE TITLE
Incorrect NavigationStart url value

### ISSUE THREAD

**Issue by Noeldeveloper** [angular/angular#46597] opened 2022-06-29 11:29 UTC
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

No

### Description

In Angular v14.0.3. There is a major change on NavigationStart behaviour. In previous versions, when calling getCurrentNavigation().initialUrl.toString() after navigateByUrl() call, you get start path before redirect. Now you get finalUrl path.

Way to reproduce:
```ts
import { Component } from '@angular/core';
import { fakeAsync, TestBed, tick } from '@angular/core/testing';
import { NavigationEnd, Router } from '@angular/router';
import { RouterTestingModule } from '@angular/router/testing';
import { filter } from 'rxjs/operators';

@Component({
  selector: 'bk-test',
  template: ''
})
class TestComponent { }

describe('Redirect', () => {

  beforeEach(() => {
    TestBed.configureTestingModule({
      imports: [
        RouterTestingModule.withRoutes([
          { path: '', redirectTo: 'test-a', pathMatch: 'full' },
          { path: 'test-a', component: TestComponent },
          { path: 'test-b', component: TestComponent }
        ])
      ],
      declarations: [
        TestComponent
      ]
    });
  });

  it('should get initalUrl = test-a', fakeAsync(() => {
    const router: Router = TestBed.inject(Router);

    let expectedInitialRoute = '/';

    router.events.pipe(
      filter(e => e instanceof NavigationEnd)
    ).subscribe(() => {
      const navigation = router.getCurrentNavigation();
      const from = navigation.initialUrl ? navigation.initialUrl.toString() : null;
      expect(from).toBe(expectedInitialRoute);
    });

    router.initialNavigation();

    tick(1000);

    expectedInitialRoute = '/test-a';

    router.navigateByUrl('/test-b');

    tick(1000);

  }));
});
```

### Please provide the exception or error you saw

```true
Expected '/test-b' to be '/test-a'
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular v14.0.3
Node 16.14.0
Npm 8.10.0
```

**Comment by atscott** [comment] 2022-06-29 14:50
The value of `initialUrl` changed in v14 as a breaking change to correctly reflect its documentation: ["The target URL passed into the Router#navigateByUrl() call before navigation"](https://angular.io/api/router/Navigation#initialUrl). Previously, this value was incorrect and set as the current internal router state at the start of the navigation, which has nothing to do with the navigation itself. Your test is actually showing the correct new behavior. Closing as working as intended.

**Closed by atscott** 2022-06-29 14:50 UTC
