### ISSUE TITLE
HttpClient not decoding to a type

### ISSUE THREAD

**Issue by grosch** [angular/angular#24456] opened 2018-06-13 01:05 UTC
## I'm submitting a...
<pre><code>
[x] Bug report  
</code></pre>

## Current behavior

Items decoded via HttpClient's get() method are not being turned into real classes.  It's just a dictionary object.

## Expected behavior
Should get back an object of the specified type.

## Minimal reproduction of the problem with instructions

```javascript
import {Component, OnInit} from '@angular/core';
import {HttpClient} from "@angular/common/http";
import {environment} from "../../environments/environment";

export class EhsAssessmentScore {
    category: string;
    score: number;
    possible: number;
    auditDate: Date;
}

@Component({
    selector: 'app-bug',
    templateUrl: './bug.component.html',
    styleUrls: ['./bug.component.scss']
})
export class BugComponent implements OnInit {
    constructor(private http: HttpClient) {
        this.http
            .get<EhsAssessmentScore[]>(`${environment.apiUri}/ehs/10/score`)
            .subscribe(x => {
                x.forEach(score => {
                    console.info("Instance: " + (score instanceof EhsAssessmentScore));
                })
            });
    }

    ngOnInit() {
    }
}
```

In the code above I should be getting back items of that concrete class.  However, that doesn't happen.  If I run that code, it always says false for the `instanceof` check.  My called URL returns data like so:

```json
[
  {
    "category": "Chemical Safety",
    "possible": 25,
    "score": 0,
    "auditDate": null
  },
  {
    "category": "Egress",
    "possible": 25,
    "score": 15,
    "auditDate": null
  },
  {
    "category": "Electrical Safety",
    "possible": 12,
    "score": 12,
    "auditDate": null
  }
]
```

## Environment

<pre><code>
Angular version: 5.2.7

Browser:
- [x] Chrome (desktop) version 67
 
For Tooling issues:
- Node version: 8.11.2
- Platform:  Windows 8.1

Others:

</code></pre>

**Comment by Toxicable** [comment] 2018-06-13 01:16
All HttpClient is going interally is calling `JSON.parse` this does not instantiate any classes nor does HttpClient know that the data is or can be turned into a class.
If you insist on using a class then you should take the data as an input into your class and make the instance yourself.

**Comment by trotyl** [comment] 2018-06-13 03:33
Duplicate of https://github.com/angular/angular/issues/21107

**Comment by larssn** [comment] 2018-06-13 11:32
What you're seeing is what I would call a general limitation in Typescript and the `instanceof` operator. It confused me as well, when I first started with the language a few years ago.

Since types doesn't exist in Javascript and the `instanceof` operator works by looking at the constructor of an object; your object lacks the constructor, and thus your check fails. Typescript can't make assumptions at compile time about what an object would be at runtime, so you have to apply the constructor to the object manually for your `instanceof` check to work.

**Closed** 2018-06-13 15:29 UTC
