### ISSUE TITLE
The title of the Press Kit images is `null`

### ISSUE THREAD

**Issue by pBouillon** [angular/angular#53691] opened 2023-12-24 10:11 UTC
### Describe the problem that you experienced

All images of the Press Kit page have their title set as `null`

### Enter the URL of the topic with the problem

https://angular.dev/press-kit

### Describe the actions that led you to experience the problem

I was on a slow internet connection and noticed the titles were off

### Describe what you want to experience that would fix the problem

I expected the titles to match the images (e.g. "Angular Gradient Logo", "Angular Black Logo", etc.)

### Add a screenshot if that helps illustrate the problem

![image](https://github.com/angular/angular/assets/22640284/9feef513-2504-4d79-b946-158207da1ecd)

### Provide any additional information here in as much as detail as you can

```true
Since this is in `adev` and that the associated `.md` file seems to contain the title, I suspect a binding or a property badly resolved from the component
```

**Comment by JoostK** [comment] 2023-12-24 11:12
Thanks for the report, this is a duplicate of #53053 for which the fix is pending deployment.

**Closed by JoostK** 2023-12-24 11:12 UTC
