### ISSUE TITLE
async not updating OnPush view, sometimes

### ISSUE THREAD

**Issue by matiskiba** [angular/angular#36215] opened 2020-03-24 07:15 UTC
# 🐞 bug report

### Is this a regression?
Yes. Was working fine in Angular 8, now failing in Angular 9.
Moreover, in Angular 9.0.5, when I wrap the Observable update code in ngZone.run it works, while in Angular 9.0.7 even that doesn't work.

### Description
I have an OnPush component that deals with observables - i.e., they update the view using async.
I noticed that sometimes the view does not change, even though an observable update had been registered.

For exmaple, I have the following code in the my .html file:
`{{popup.stateAsObservable | async|json}}`
I have a console.log showing the observable value had been updated, but the view does not update until a mouse interaction.

I've manually recreated the async behavior, i.e., I've subscribed to that observable via the TS code, than issued an `markForChange` call, but again nothing happened, when I added `detectChanges` call the view updated.

Even more worrying, the problem seems to go away on little changes, such as maybe adding a setInterval somewhere (just a setInterval, without a code inside it). 
I suspect it is a very rare issue that somehow occurs in my specific code setup.

I cannot provide an easy reproduction, it is very difficult to recreate, it happens in my current code setup.
I'd like to get directions in debugging this issue, so I'll be able to provide more insight about the bug.

## 🔬 Minimal Reproduction
Cannot

## 🌍  Your Environment
Angular 9

## Special request
My application heavily relies on ASync pipe, which means it is now broken. Please put it on high priority.

**Comment by pkozlowski-opensource** [comment] 2020-03-24 07:32
This sounds very much like a duplicate of #35579 and the relevant explanation / work-around is provided as part of the mentioned issue: https://github.com/angular/angular/issues/35579#issuecomment-589449820

**Comment by matiskiba** [comment] 2020-03-24 07:58
Thank you @pkozlowski-opensource 

Importing zone-patch-rxjs didn't work, but adding ngZone.run before the markForChange did work.

I suggest we update ASyncPipe's code to reflect that, i.e., let it perform an ngZone.run before it calls the markForChange. I think its important because ASyncPipe is used as a "magic-pipe", taking care of the all ng-zone and change-detection issues relating with pipes, leaving you only the need to perform "| pipe"

What do you think?

**Comment by matiskiba** [comment] 2020-03-24 09:42
Update: I've patched the AsyncPipe implementation with ngZone.run before markForChange
It works for me. I am unsure what effect it will have on Angular as a whole, so I'm not submitting a patch. Would like to hear from the developers.

Here is the code (updated _updateLatestValue)
    private _updateLatestValue(async: any, value: Object): void {
        var self = this;
        if (async === self._obj) {
            if ( NgZone.isInAngularZone() )
            {
                self._latestValue = value;
                self._ref.markForCheck();
            }
            else
            {
                self._ngZone.run(function() {
                    self._latestValue = value;
                    self._ref.markForCheck();
                });
            }
        }
    }

**Comment by JiaLiPassion** [comment] 2020-03-24 12:35
@matiskiba , could you provide a reproduce repo?

**Comment by pkozlowski-opensource** [comment] 2020-04-02 08:28
We haven't heard back with the reproduce scenario so I'm going to assume that this is a duplicate of #35579.

**Closed by pkozlowski-opensource** 2020-04-02 08:28 UTC
Labels: comp: core, comp: zones, core: change detection, state: Needs repro
