### ISSUE TITLE
Router: Not specifying '@RouteConfig' on the root component throws a cryptic NPE

### ISSUE THREAD

**Issue by matanlurey** [angular/angular#2323] opened 2015-06-03 21:12 UTC
... when you use a router-link directive.

**Comment by naomiblack** [comment] 2015-06-13 00:17
Brian has a partial fix for this but still more work TBD in alpha-28.

**Comment by btford** [comment] 2015-06-19 19:31
This is related to #2642 (which will include a more general fix for this); I'm going to reassign to Matias and move to alpha-29.

**Comment by matsko** [comment] 2015-07-01 19:18
@matanlurey did you have any child components present in the page that had routing with `@RouteConfig`?

**Comment by matsko** [comment] 2015-07-02 05:03
I'm still waiting on hearing back from @matanlurey regarding his application example setup so that I can reproduce the bug.

**Comment by matsko** [comment] 2015-07-06 19:40
This was pushed back to the next release. Matan mentioned that Ifran or Ted will be helping out this week.

**Comment by matanlurey** [comment] 2015-07-07 02:58
@TedSander for visibility.

**Comment by TedSander** [comment] 2015-07-07 21:06
The case I could reproduce was having routes on a component that was not the route component. Currently the router needs to be able to be set on the root component and all the way down. At the least @matsko and @btford and going to make a better error message for what is happening. Or warn the developer that what they are doing is unsupported.

**Comment by btford** [comment] 2015-07-07 21:09
Yep. To re-state another way: RouteConfig should only be on the root component or a component (transitively) routed from the root component.

**Comment by matsko** [comment] 2015-07-08 22:21
This issue has been moved over to `alpha-32` since it can only be addressed after me and Brian get the Auxiliary Routes feature in.

**Comment by btford** [comment] 2015-07-13 20:52
This doesn't explicitly depend on #2775, and the error message is already much improved– the router now warns that `{{routeName}} is not found` rather than throwing a NPE.

I'm not sure we can do much better– if you put the annotation on the wrong component, then of course the route will not be found. I don't think there's a great way for `RouteLink` to get ahold of the component that contains it (this kinda breaks encapsulation), check how it was instantiated, and then throw if the component contains `RouteConfig` annotations. And it might be an entirely valid use to have a component that you use both via routing and by including within another component's template.

I'll add another exception that warns when `RouteLink`'s parent component has no configuration, but then I think this can be considered closed.

Sound reasonable @TedSander @matanlurey?

**Closed** 2015-07-15 17:35 UTC
Labels: comp: router, effort1: easy (hour), hotlist: GT, P2: required, type: bug

**Comment by TedSander** [comment] 2015-07-15 18:56
Will this cover the case where there is no route configuration all the way to the root? That was the problem I was running into and it isn't clear whether we have a warning for that.
