### ISSUE TITLE
HttpParams gets converted to space for + sign, Any fix to resolve this issue

### ISSUE THREAD

**Issue by sreesilpa13** [angular/angular#36363] opened 2020-04-01 10:01 UTC
navigateToDashboard(ngForm: NgForm){
    var hash = CryptoJS.SHA1(ngForm.value.password);
    var txtPassBase64 = hash.toString(CryptoJS.enc.Base64);
    var txtPassHexValue = hash.toString(CryptoJS.enc.Hex);
    hash = CryptoJS.MD5(ngForm.value.password);
    let txtMD5Base64  = hash.toString(CryptoJS.enc.Base64)

    const body = new HttpParams()
    .set('txtUserId', '10015625')
    .set('txtMD5Base64', txtMD5Base64)//4QrcOUm6Wau+VuBX8g+IPg==
    .set('language', 'E');

    console.log("body",body);
      this.httpClient.post(this.postUrl,body,this.httpOptions).subscribe(() => {
        console.log("Hi");
      })
  }

The final txtMD5Base64 loooks like 4QrcOUm6Wau VuBX8g IPg==(plus symbols are replaced with 
space). It should look like this while submitting a request => 4QrcOUm6Wau+VuBX8g+IPg== but looks like this in the HttpParams => 4QrcOUm6Wau VuBX8g IPg==. Its a complete nightmare for me to resolve the issue. Please suggest a solution for this

**Comment by daftfox** [comment] 2020-04-02 02:05
Hi @sreesilpa13, I struggle to understand what you're trying to achieve in the first few lines. Two of the instantiated variables aren't used in your code, you are reassigning `var hash` and there's a mix of `var` and `let` usage.

I have tried to replicate your issue locally, but I'm unable to produce a base64 string containing `+` characters. Are you certain the params you receive at your back-end service doesn't contain the `+`? From what I can tell, the `HttpParams` class contains a `toString` method that encodes the set values.

Try a few things for me:
- Print the value of `txtMD5Base64`
- Print the result of `body.get('txtMD5Base64')`

These two should be the same. If you only see the missing characters when printing `body`, you can attribute this to its `toString` method encoding values.

**Comment by sreesilpa13** [comment] 2020-04-02 12:48
Hi daftfox,
The issue is while posting a request , in HttpParams , the value of 
txtMD5Base64= 4QrcOUm6Wau+VuBX8g+IPg== is changed To 
txtMD5Base64= 4QrcOUm6Wau VuBX8g IPg==
The + is replaced with space. How to prevent this. Please Help

**Comment by sreesilpa13** [comment] 2020-04-02 13:47
Please check the GitHub again. I have updated my comment.

**Comment by Lonli-Lokli** [comment] 2020-04-03 07:40
Welcome to the area of old issues which are not supposed to be fixed
https://github.com/angular/angular/issues/11058

**Comment by alxhub** [comment] 2020-05-29 17:54
Actually, I'm going to close this as a duplicate of #11058.

**Closed by alxhub** 2020-05-29 17:54 UTC
Labels: comp: common/http, design complexity: low-hanging, flag: breaking change, state: confirmed, triage #1, type: bug/fix
