### ISSUE TITLE
Member links in FormGroup API documentation scroll to/highlight the wrong member

### ISSUE THREAD

**Issue by diesieben07** [angular/angular#58209] opened 2024-10-15 16:30 UTC
### Describe the problem that you experienced

When clicking on a member in the API documentation for FormGroup (https://angular.dev/api/forms/FormGroup), the wrong member will be highlighted in the sidebar.

### Enter the URL of the topic with the problem

https://angular.dev/api/forms/FormGroup

### Add a screenshot if that helps illustrate the problem

[Demonstration Video](https://github.com/user-attachments/assets/2b486c0a-87c5-4450-9a2d-3a86da92c509)

Likely cause:
![Image](https://github.com/user-attachments/assets/784fc7e0-f7fd-471f-afe2-92a0f7908983)

**Comment by JeanMeche** [comment] 2024-10-16 03:51
Hi, this is a duplicate of #58053

**Closed by JeanMeche** 2024-10-16 03:51 UTC

**Comment by diesieben07** [comment] 2024-10-16 08:21
I am very sorry for my duplicates. I did try searching for both issues, but was unsuccessful. Thank you for finding the duplicates.
