### ISSUE TITLE
SwUpdate doesn't check update  on each navigation request in chrome

### ISSUE THREAD

**Issue by Sam-Lin-MillersLab** [angular/angular#39653] opened 2020-11-12 17:40 UTC
# 🐞 bug report

### Affected Package
@angular/pwa

### Is this a regression?

not sure

### Description
https://angular.io/guide/service-worker-communications

It states, 

> The service worker checks for updates during initialization and on each navigation request

It doesn't work in latest Chrome or Edge 

But it does work in Firefox

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1002.0
@angular-devkit/build-angular   0.1002.0
@angular-devkit/core            10.2.0
@angular-devkit/schematics      10.2.0
@angular/cdk                    10.2.7
@angular/cli                    10.2.0
@angular/material               10.2.7
@schematics/angular             10.2.0
@schematics/update              0.1002.0
rxjs                            6.6.3
typescript                      4.0.5
</code></pre>

**Comment by alan-agius4** [comment] 2020-11-12 17:50
Duplicate of https://github.com/angular/angular/issues/39652

**Closed by alan-agius4** 2020-11-12 17:50 UTC

**Comment by Sam-Lin-MillersLab** [comment] 2020-11-12 18:21
@alan-agius4 it is odd, when I created that one earlier it shows page not found error. I didn't realize it was created. thx!
