### ISSUE TITLE
[Angular 14.1+] - CanMatch called multiple times

### ISSUE THREAD

**Issue by mdowais** [angular/angular#49315] opened 2023-03-04 13:38 UTC
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

Yes

### Description

canMatch is called when module D,E,F is loaded, even when it is not assigned to the parent.

canActivate doenst have this issue.

I guess if `path:''` is same for both the entries, it causes canMatch to be called for D,E,F. 

```
[
    {
        path: '',
        canMatch: [Guard],
        canActivate: [Guard],
        data: {
            layout: 'empty'
        },
        children: [
            { path: 'A', loadChildren: () => import('./a.module').then(m => m.AModule) },
            { path: 'B', loadChildren: () => import('./b.module').then(m => m.BModule) },
            { path: 'C', loadChildren: () => import('./c.module').then(m => m.CModule) },
        ]
    },
    {
        path: '',//CanMatch not assigned
        canActivate: [Guard],
        data: {
            layout: 'compact'
        },
        children: [
            { path: 'D', loadChildren: () => import('./d.module').then(m => m.DModule) },
            { path: 'E', loadChildren: () => import('./e.module').then(m => m.EModule) },
            { path: 'F', loadChildren: () => import('./f.module').then(m => m.FModule) },
        ]
    }
]
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.1.2
Node: 16.13.0
Package Manager: npm 8.1.0
```

**Comment by mdowais** [comment] 2023-03-04 13:39
I hope this is not related to #26081

**Comment by atscott** [comment] 2023-03-04 14:18
Duplicate of https://github.com/angular/angular/issues/26081

**Closed by atscott** 2023-03-04 14:18 UTC

**Comment by mdowais** [comment] 2023-03-04 14:26
> Duplicate of #26081

@atscott 

I'd like to confirm that it is a dup of #26081, CanMatch, was called when loading Module D, regardless even when Module D's Parent has a CanMatch Guard.

I wasn't able to understand the co-relation with #26081, hence confirming again.

**Comment by atscott** [comment] 2023-03-04 14:28
Hmmm, you don’t mean that it’s called twice but that it’s called at all? The empty path could possibly match so whenever matching is happening, the canMatch guard has to be called. The config you’ve written would result in the canMatch being called every time a routing happens. If I understand your question correctly now then no, it’s not a duplicate but it is working as expected.

**Comment by mdowais** [comment] 2023-03-04 15:01
@atscott 

Please see the below sample.

https://stackblitz.com/edit/angular-ivy-rmp8dc?file=src%2Fmain.ts


My question is why is Guard1 Called when i accesss Login Page?? Only Gaurd2 should be called.

And, why was guard1 and guard2 called for test 
page?? It has no guards.

If i returned a urlTree, it would enter into a routeLoop


Honestly, i havent yet faced the 2 times issue (yet), i am using a template called Fuse-Angular, i dont know if the author has done some magic or something.

**Comment by atscott** [comment] 2023-03-04 22:04
Yes, this is expected. Route order matters so whenever you navigate, the router attempts to match the first empty string path first. It has no way of knowing whether the conditions of the guard changed between navigations so it must re-execute the canMatch guard on a route that has a path which matches.
