### ISSUE TITLE
ng serve throws error on using "aot":true after angular upgrade to 9.0.7.

### ISSUE THREAD

**Issue by sampath0606** [angular/angular#36352] opened 2020-03-31 14:31 UTC
I am facing the the following issues when i try to do 'ng serve' after upgrading to 9.0.7.

NG8001: 'mat-select' is not a known element:

If 'mat-select' is an Angular component and it has 'disabled' input, then verify that it is part of this module.
If 'mat-select' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.
error NG8001: 'mat-form-field' is not a known element:

If 'mat-form-field' is an Angular component, then verify that it is part of this module.
If 'mat-form-field' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
error NG8002: Can't bind to 'ngModel' since it isn't a known property of 'input'.
<input matInput #input class="form-control" placeholder="XXX" [(ngModel)]="XX.yy"

If i update aot:false ng serve is working fine , but on building for prod i', again facing the above mentioned issues.

Everything was working completely fine with 9.0.6. Could some body help me out?

My Package File:

{
"name": "nol-ui",
"version": "0.0.0",
"scripts": {
"ng": "ng",
"start": "ng serve",
"build": "ng build",
"test": "ng test",
"lint": "ng lint",
"e2e": "ng e2e"
},
"private": true,
"dependencies": {
"@angular/animations": "~9.0.7",
"@angular/cdk": "~9.2.0",
"@angular/common": "~9.0.7",
"@angular/compiler": "~9.0.7",
"@angular/core": "~9.0.7",
"@angular/forms": "~9.0.7",
"@angular/material": "^9.2.0",
"@angular/platform-browser": "~9.0.7",
"@angular/platform-browser-dynamic": "~9.0.7",
"@angular/router": "~9.0.7",
"classlist.js": "^1.1.20150312",
"handlebars": "^4.7.3",
"kind-of": "^6.0.3",
"lodash": "^4.17.15",
"rxjs": "~6.5.4",
"serialize-javascript": "^2.1.2",
"tree-kill": "^1.2.2",
"tslib": "^1.10.0",
"web-animations-js": "^2.3.2",
"zone.js": "~0.10.2"
},
"devDependencies": {
"@angular-devkit/build-angular": "~0.900.7",
"@angular/cli": "~9.0.7",
"@angular/compiler-cli": "~9.0.7",
"@angular/language-service": "~9.0.7",
"@types/jasmine": "^3.3.16",
"@types/jasminewd2": "^2.0.8",
"@types/node": "^12.12.34",
"codelyzer": "^5.1.2",
"jasmine-core": "~3.4.0",
"jasmine-spec-reporter": "~4.2.1",
"karma": "~4.1.0",
"karma-chrome-launcher": "~2.2.0",
"karma-coverage-istanbul-reporter": "^2.0.6",
"karma-jasmine": "~2.0.1",
"karma-jasmine-html-reporter": "^1.5.3",
"protractor": "^5.4.3",
"ts-node": "~7.0.0",
"tslint": "~5.15.0",
"typescript": "~3.7.5"
}
}

**Comment by alxhub** [comment] 2020-03-31 22:07
This is likely related to `ngcc` getting itself into a stuck state. Can you remove and reinstall `node_modules` and try again?

**Comment by sampath0606** [comment] 2020-04-01 10:23
i tired and actually it we were using lazy modules, i had the components present but commented out the lazy loading. 
i tried to un comment those modules  in the routing and then performed update process and i was able to do 'ng serve'. Finally i commented the unused modules in the routing and then ran it again. works perfectly.

Do you find any reason behind this feature?

**Comment by OwenKelvin** [comment] 2020-04-07 08:56
I believe the reason you are not able to do `ng serve --aot` is because you have not imported the MatSelectModule in your lazy loaded module. The error says **'mat-select' is not a known element:** This usually happens if you are using an element that has not been declared in the module or the module is not importing a module that declares and exports the element

**Comment by tahir-jamil** [comment] 2020-05-20 03:04
i have the sample problem with scheme error and i have added component in declarations of module but still after migrating it shows many errors

**Comment by petebacondarwin** [comment] 2020-05-24 19:36
@sampath0606  - did you manage to get this working? If not can you please provide us with a reproduction that we can debug?

@tahir-jamil  - please can you open a new issue with your own reproduction of the problem.

**Comment by tahir-jamil** [comment] 2020-05-30 11:11
i will regenerate the issue and let you know if it occur again

**Comment by petebacondarwin** [comment] 2020-06-08 10:03
Closing as we have no reproduction for this issue. @tahir-jamil if you manage to create one, please open a new issue.

**Closed by petebacondarwin** 2020-06-08 10:03 UTC
Labels: comp: ngcc, state: Needs repro, triage #1
