### ISSUE TITLE
Components not rendered when added to other components when Ivy is enabled

### ISSUE THREAD

**Issue by rip222** [angular/angular#31570] opened 2019-07-15 18:06 UTC
# 🐞 bug report

### Description

I created a new project with `—enableIvy` flag. Worked fine until I created a new component using the cli, and added the component to the app component, while the app was being served. On live reload the new component was not rendered, although the dev tools showed that it was there. So I had to “re-serve” the app for the new component to appear in the app.
Moreover, when I created another new component and also added it to the app component, all the components added to the app component disappeared. Again I had to restart the app for all the components to be displayed.

## 🔬 Minimal Reproduction
1. `ng new test-app —enable-ivy`
2. `ng g c test`
3.  `ng s`
4.  paste test component element into the app component template, like so `<app-test><app-test>`, and save.
5. check out the tab with your app in your favorite browser

## 🔥 Exception or Error
Dev tools as well as the cli don’t show any errors.

## 🌍  Your Environment
**Angular Version:**
<pre><code>
Angular CLI: 8.1.1
Node: 10.15.2
OS: darwin x64
Angular: 8.1.1
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.801.1
@angular-devkit/build-angular     0.801.1
@angular-devkit/build-optimizer   0.801.1
@angular-devkit/build-webpack     0.801.1
@angular-devkit/core              8.1.1
@angular-devkit/schematics        8.1.1
@ngtools/webpack                  8.1.1
@schematics/angular               8.1.1
@schematics/update                0.801.1
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.35.2
</code></pre>

**Anything else relevant?**
Using MacBook Pro Early 2011, OS: HighSierra 10.13.6, IDE: VSCode, terminal: bash

**Comment by alexzuza** [comment] 2019-07-15 18:53
Appears related to https://github.com/angular/angular/issues/31512

**Comment by rip222** [comment] 2019-07-15 19:02
> Appears related to #31512

are you sure? My app produces no errors

**Comment by alxhub** [comment] 2019-07-16 22:28
@rip222 can you please add detailed, step by step directions for reproducing this problem?

**Comment by rip222** [comment] 2019-07-19 07:44
> @rip222 can you please add detailed, step by step directions for reproducing this problem?

done

**Comment by AlliVil** [comment] 2019-10-28 10:09
I am having the exact same issue. Has there been any developments since this issue was opened?

**Comment by JoostK** [comment] 2019-11-01 09:34
I'm hopeful that #33522 will resolve this issue.

**Comment by JoostK** [comment] 2019-12-16 21:03
This issue should have been resolved with recent fixes to incremental rebuilds. As there's no reproduction available I'm going to assume this issue has indeed been resolved. If someone is still seeing issues with incomplete incremental rebuilds, please open a new issue.

**Closed by JoostK** 2019-12-16 21:03 UTC
Labels: comp: ivy, freq1: low, severity3: broken, state: Needs repro, type: bug/fix
