### ISSUE TITLE
Blur Event Form Field prevents Submit button's Click event Handler 

### ISSUE THREAD

**Issue by david-bulte** [angular/angular#37544] opened 2020-06-11 19:54 UTC
# 🐞 bug report

### Affected Package
@angular/forms

### Description

Maybe I am doing something wrong, because this seems a very common use case. I have a form with some required fields. "On blur" triggers validation. Underneath each field, there is a div showing an error message when there is an error. The submit button should always be clickable. 

When a required field now has focus, and I click on the submit button (through moving the mouse, so *not* using the [tab] key), the 'error' message is shown, but the submit button itself does not call its submit() method.

My guess is that the field's blur event is triggered first, which makes the form rerender. Should the error message *not* push the submit button down the page, the submit button's click event would be captured after the rerender of the page, and all would be fine. 

Note that if I would trigger the submit button through a 'mousedown' event, it works. But this is not very developer friendly. 

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-ivy-aywlkp

## 🌍  Your Environment

**Angular Version:**
9

**Comment by AndrewKushnir** [comment] 2020-06-11 21:04
Hi @david-bulte, thanks for providing a repro.

I performed an investigation and re-created the same behavior using plain JS/HTML (without Angular on a page), [here is the page](https://stackblitz.com/edit/js-u7gznk?file=index.html). Try putting the focus on the input element and after that click the "Submit" button. What happens is the "blur" event fires first, which causes additional element to become visible on a page, shifting the submit button below itself.

As a possible solution, you can update the template to avoid shifting the button in case validation error is triggered, for example using the "visibility" CSS property.

Since the problem is unrelated to Angular, I'm closing this ticket.

Thank you.

**Closed by AndrewKushnir** 2020-06-11 21:04 UTC
Labels: comp: forms, type: support
