### ISSUE TITLE
Select field in Safari displays option but does not set value when default value is null 

### ISSUE THREAD

**Issue by janaleible** [angular/angular#14505] opened 2017-02-15 15:56 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
This happens with the Internet Explorer and older versions of Firefox (does happen in version 40, does not happen in version 50): When no default value (or explicitly null) is set for a select field's form control, the first option is displayed in the UI but not set as value in the corresponding FormControl. 
Side note: Manually selecting the already displayed value does not set the FormControl's value either. To select this option one must first select a different option and then the first one again, only then the value property is correctly set.

**Expected behavior**
I'd expect the field to be empty initially. If this cannot be done, I'd at least expect the FormControl's value property to be set correctly (reflecting the displayed value).

**Minimal reproduction of the problem with instructions**
Create a select field with no default value and view in IE/older Firefox. 
[Minimal example](http://plnkr.co/edit/HBjrpCQbYWqSFSykaZaZ?p=preview)

**Please tell us about your environment:**
Tested on Windows 7 and 10 using Chrome 56 and Firefox 50 (behave as expected) and Internet Explorer 11 and Firefox 40 (buggy) 

* **Angular version:** 2.4.7
 
* **Language:** TypeScript 2.0.2

**Comment by stieler-it** [comment] 2017-08-10 07:53
This problem does still exist with Angular v4.3.3. It is actually worse if the select box contains only one element. The option looks like selected, although it isn't (in the model). If the select is required, it is not possible to get the form into valid state.

I have made another Plunker that shows how to reproduce it in template based forms. Please note that the problem occurs only if the option values are set delayed. So both

```
setTimeout(() => {
  this.offices = ['Office1'];
}, 1000);
```

and using `let officeOptions of offices | async` makes IE11 show the unselected item as selected.

This is interesting as the example of @janaleible does set the option values immediately and the bug still shows up.

**Comment by janaleible** [comment] 2017-08-10 08:26
There's a template-only workaround which has so far worked quite well for me:
```html
<form [form]="form">
	<select formControlName="select">
		<option *ngIf="!form.value.select" [ngValue]="null" selected disabled></option>
		<option *ngFor="let option of options" [ngValue]="option">{{option}}</option>
	</select>
</form>
```
This will display a blank option while no value is set, which disappears as soon as another value is selected.

**Comment by stieler-it** [comment] 2017-08-10 09:59
Hi @janaleible. This workaround also fixes the issue in my Punkr and our application. Thanks a lot!

**Comment by stieler-it** [comment] 2017-08-10 12:39
Unfortunately, IE is still not happy. In my updated [Plunker](https://plnkr.co/edit/kHodtEPvfUAmM6ZA3lyY?p=preview), IE shows two options but still the first "real" option is shown as selected and it is not possible to make a selection.

**Comment by janaleible** [comment] 2017-08-10 13:53
Seems to be an issue with template driven forms. [This](https://plnkr.co/edit/9QgBUlhgUju1AI256FWr?p=preview) is a working solution using model driven forms.

**Comment by stieler-it** [comment] 2017-08-10 21:00
Yes, the model driven version works in my IE 11 as well. Although this is currently not an option for us, the workaround without "disabled" should already be fine for our application. Thanks for the hints!

**Comment by slawojstanislawski** [comment] 2017-09-15 11:08
In my project on angular 4.3.1 the solution from https://github.com/angular/angular/issues/14505#issuecomment-321486088 works for a dynamic form - I also had to remove the disabled attribute (as mentioned in the previous comment) for it to work on IE 11.

**Comment by bappy004** [comment] 2018-02-08 04:24
I'm using a recctive form and I too had to remove the disabled attribute from the solution (https://github.com/angular/angular/issues/14505#issuecomment-321486088) to make it work for edge (angular 5.2.2).

**Comment by theodorejb** [comment] 2018-05-04 19:05
It looks like @DzmitryShylovich had [a branch for fixing this](https://github.com/DzmitryShylovich/angular/commits/gh/14505), but it hasn't been touched for over a year. Is there anything I can do to help move this forward? Our app has a bunch of forms that are broken in IE 11 because of this bug. @kara

**Comment by theodorejb** [comment] 2018-05-07 16:59
Here's a minimal reproduction of the issue: https://angular-form-ie-bug.stackblitz.io.

A form value can be selected as expected in Chrome, Firefox, and Edge, but not IE 11.

**Comment by theodorejb** [comment] 2018-05-09 17:01
I created pull request #23784 to fix this.

**Comment by rahulz-wasnik** [comment] 2018-08-02 05:15
any update folks

**Comment by theodorejb** [comment] 2018-08-03 02:28
@rahulz-wasnik I'm waiting for someone on the Angular team to review the pull request I made to fix it (#23784). @IgorMinar assigned @kara back in May but I haven't seen any activity since.

**Comment by theodorejb** [comment] 2018-08-03 19:24
Note that this issue also affects the latest version of Safari, not just IE.

**Comment by theodorejb** [comment] 2018-10-16 18:58
This bug still exists in Angular 7.0.0-rc.1, affecting both IE 11 and Safari 12.0.1.

**Comment by jagadeeshagm** [comment] 2019-02-05 09:00
http://creativeit.github.io/getmdl-select/

MDL Select is now working in IE EDGE browser. Selecting the drop down option is not shown in the field.

**Comment by theodorejb** [comment] 2019-02-05 15:22
@jagadeeshagm That page seems to be working fine in Edge (v18) for me. But even if it wasn't, that would be a different issue from this one, which is specific to Internet Explorer and Safari with native select dropdowns.

**Comment by jagadeeshagm** [comment] 2019-02-06 09:51
Mine browser is IE 11 (EDGE).  Selected drop down option are not shown in the field. 
Error msg : closeSelect - Object doesn't support this action

**Comment by theodorejb** [comment] 2019-02-08 18:58
@jagadeeshagm 😄 I get it now. I'd recommend not saying EDGE if you're using Internet Explorer, since that will get confused with Microsoft Edge which is a different browser.

In any case, the bug in MDL Select seems unrelated to this issue, and it looks like you already opened a separate issue for it in that repo (I suggest editing that issue to not say EDGE so people reading it won't be confused like I was).

**Comment by dennisameling** [comment] 2019-04-09 19:33
I've dived a bit into this. This issue indeed only occurs when data is loaded dynamically through the `[value]` or `[ngValue]` attributes on `<option>` elements. Take a look at [this example](https://stackblitz.com/edit/angular-ruvsye):

**Chrome**:

![image](https://user-images.githubusercontent.com/17739158/55826775-08ae8880-5b09-11e9-8f3e-dec57addd1ed.png)

**IE11/Safari on iOS 12.2**:

![image](https://user-images.githubusercontent.com/17739158/55827029-8ecacf00-5b09-11e9-8fb3-b6e7f0516df4.png)
What seems to happen is that when the `[value]` or `[ngValue]` attributes are used, the following code is triggered ([reference](https://github.com/angular/angular/blob/master/packages/forms/src/directives/select_control_value_accessor.ts#L217-L239)):

```TypeScript
/**
   * @description
   * Tracks the value bound to the option element. Unlike the value binding,
   * ngValue supports binding to objects.
   */
  @Input('ngValue')
  set ngValue(value: any) {
    if (this._select == null) return;
    this._select._optionMap.set(this.id, value);
    this._setElementValue(_buildValueString(this.id, value));
    this._select.writeValue(this._select.value);
  }

  /**
   * @description
   * Tracks simple string values bound to the option element.
   * For objects, use the `ngValue` input binding.
   */
  @Input('value')
  set value(value: any) {
    this._setElementValue(value);
    if (this._select) this._select.writeValue(this._select.value);
  }
```

The `writeValue()` function has the following [line](https://github.com/angular/angular/blob/master/packages/forms/src/directives/select_control_value_accessor.ts#L128-L142):
```TypeScript
const id: string|null = this._getOptionId(value);
if (id == null) {
  this._renderer.setProperty(this._elementRef.nativeElement, 'selectedIndex', -1);
}
```
The `selectedIndex` is key here. As you can see in the screenshots above, Chrome sets the selectedIndex to -1 again, while IE11/Safari **don't** reset it to -1 but to 0 instead.

Hope this helps a bit to troubleshoot further, not sure how to proceed now. :)

**Comment by theodorejb** [comment] 2019-04-10 03:51
I fixed this almost a year ago in pull request #23784, by setting `selectedIndex` to -1 if the browser didn't already do so. However, there still hasn't been any reply from the assigned reviewer.
@kara @IgorMinar

**Comment by solanaprojordan** [comment] 2019-07-29 14:36
Are there any updates to this? We are experiencing the same issue.

**Comment by theodorejb** [comment] 2019-07-29 19:25
This bug still exists with Angular 8 and the latest version of Safari and IE 11. I rebased my pull request from last year which fixes it - hopefully it can be reviewed soon. I'm not sure what more to do to bring it to the attention of the Angular team.

**Comment by dasaweb** [comment] 2019-10-14 06:53
> This bug still exists with Angular 8 and the latest version of Safari and IE 11. I rebased my pull request from last year which fixes it - hopefully it can be reviewed soon. I'm not sure what more to do to bring it to the attention of the Angular team.

Many thanks @theodorejb for your commitment in this matter! I have a big project here with a lot of select dropdowns, all of which don't work in IE because of this problem. The integration of your solution into Angular is progressing sluggishly (if at all)... Is there a way I can integrate your solution into my own project?

**Comment by theodorejb** [comment] 2019-10-17 14:17
@dasaweb I don't know of a way to integrate the solution, other than building Angular yourself with the patch in PR #23784. But that's a lot of extra work. Ideally someone on the Angular team will confirm that the issue exists and review/merge the patch. But I'm not sure how to bring it to their attention. Maybe if you know someone on the Angular team you can reach out to them?
@kara @mhevery @alexeagle @matsko

**Comment by dasaweb** [comment] 2019-10-18 06:48
@theodorejb It seems to be moving forward, thank you very much. For my project, I have now implemented the solution suggested above as a workarout: For Internet Explorer, an additional option has been added to each (!) select element, which disappears when the model gets a value.

This is ok for me for the moment, but integrating a general solution into Angular would of course be absolutely desirable.

**Comment by julisch94** [comment] 2020-09-10 10:18
Any updates on this?

**Comment by theodorejb** [comment] 2020-09-14 16:38
@julisch94 I've been keeping pull request #23784 rebased whenever there are merge conflicts, but I haven't heard anything new from the Angular team for a couple months. At the end of June they said they needed to investigate a couple places in Google's codebase for forward compatibility, but there doesn't seem to have been any progress since then. 😢

**Comment by gigabit2** [comment] 2021-05-27 11:27
Come across this myself, it is insane this has not been merged.

**Comment by atscott** [comment] 2024-06-13 19:41
This looks to no longer be an issue in the latest version of safari. Closing.

**Closed by atscott** 2024-06-13 19:41 UTC
Labels: type: bug/fix, freq2: medium, area: forms, state: confirmed, browser: safari, P4
