### ISSUE TITLE
Custom Angular FormField emitting event when configured not to.

### ISSUE THREAD

**Issue by jsonsystems** [angular/angular#37954] opened 2020-07-07 13:51 UTC
# 🐞 bug report

### Affected Package
@angular/forms: 9.1.6

### Description

I have implemented a [custom Angular Material FormField](https://material.angular.io/guide/creating-a-custom-form-field-control) that wraps [CodeMirror](https://codemirror.net/).

In my **app** component I suscribe to [valueChanges](https://angular.io/api/forms/AbstractControl#valueChanges) on the Form Control to listen to the user typing:

```typescript
export class AppComponent implements OnInit {
   // Custom value accessor for CodeMirror.
   control: FormControl = new FormControl('', {updateOn: 'change'});

   ngOnInit() {
    // Listen for the user typing in CodeMirror.
    this.control.valueChanges.pipe(
        debounceTime(500),
        distinctUntilChanged(),
        tap((value: string) => {
          console.log(`The user typed "${value}"`);
        })
    ).subscribe();
  }
}
```

I noticed that when using [setValue](https://angular.io/api/forms/AbstractControl#setValue), the [valueChanges](https://angular.io/api/forms/AbstractControl#valueChanges) Observable emits a value **even if the options object prohibits it**:

```typescript
// This appears to have no effect.
this.control.setValue(value, {
   // Prevent the statusChanges and valueChanges observables from
   // emitting events when the control value is updated.
   emitEvent: false,
}
```

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-material-starter-template-slalpy

1. Click the `setValue(0)` button
2. The **app** component calls  `setValue` on the FormControl with `emitEvent: false`
3. The **ControlValueAccessor** `writeValue(value: string)` method is called on the custom FormField component (`my-input.component`)
4. Writing the value is delegated to the **MatFormFieldControl** `value` setter
5. The **MatFormFieldControl** `value` setter writes the value to the CodeMirror editor with `this._editor.setValue(value)`
6. The `changes` [CodeMirror event](https://codemirror.net/doc/manual.html#events) is triggered (it was added in `ngAfterViewInit`).
7. The registered callback function is called with the updated value (`this._onChange(cm.getValue())`)
8. The `valueChanges` Observable emits the updated value

Yes, `my-input.component` explicitly calls the registered calledback function, but I had expected the framework (Angular or Angular Material) to honor `emitEvent: false` and not emit the event.

Is it the responsibility of the custom FormField implementation to implement the options object and not call the registered callback if emitEvent: false is set?

I assumed that it was a contractual obligation to call the `onChange` callback if the value changes, irrespective of whether the change originated from the Forms API via `setValue` or from the user typing in CodeMirror.

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
Angular: 9.1.6

**Comment by olliveirallucas** [comment] 2020-07-11 20:36
Thanks for the reproduction code. I took a look at this and my conclusion is that it not seems to be a bug. What is happening is that the `_editor` is being updated in `set value` to a new value (from the external `setValue`) and the change event fires `codemirrorValueChanged`. This function calls `_onChange` that calls `setValue` again to update the form control with the value it already has and emits the value. To fix this, avoid firing the change event on `_editor` when you receive an external value and do `this._editor.setValue(this.value)`. If it is not possible, a workaround is avoiding calling `_onChange` in `codemirrorValueChanged` when the value in `_editor` is equal the value in the form control by including a condition like `if (this.ngControl.control.value !== cm.getValue()) { this._onChange(cm.getValue()); }`. See: [https://stackblitz.com/edit/angular-material-starter-template-bqctnc](https://stackblitz.com/edit/angular-material-starter-template-bqctnc).

**Comment by jsonsystems** [comment] 2020-07-13 15:59
@olliveirallucas Thanks for looking into this.

What you say makes sense and it is possible since the change event fired by CodeMirror provides an array containing all changes that happened in the operation. These changes are are modelled with an `EditorChange` interface which has an `origin` property, the value of which is `"setValue"` when the `_editor` is updated programmatically.

**If** I only use CodeMirror's `setValue` method when updating the form control with an external value, I can avoid firing the change event:

```typescript
  codemirrorValueChanged(cm: CodeMirror.Editor, changes: CodeMirror.EditorChange[]) {
    if (!changes) {
      return;
    }
    // TODO: Will batched changes always share the same origin?
    const firstChange = changes[0];
    // Avoid firing the change event on _editor when you receive an external value.
    if (firstChange.origin !== 'setValue') {
      this._onChange(cm.getValue());
    }
  }
```

But. This still seems at odds with the fact that the form control API provides an object to configure this when calling [formcontrol.setValue](https://angular.io/api/forms/FormControl#setValue). I mean, I would want to fire this event if the options object was `{emitEvent: true}`.  It seems the behaviour is not configurable even though the [setValue](https://angular.io/api/forms/FormControl#setValue) method suggests it is?

**Comment by olliveirallucas** [comment] 2020-07-15 00:01
@jsonsystems, I am not sure, but it seems to me that you have the two following situations: (1) when the form control is updated you must update the `_editor` with the new value and (2) when the `_editor` is updated you must update the form control with the new value.

The situation 1 takes place when you call externally `formcontrol.setValue` that fires the chain `writeValue` -> `set value` -> `_editor.setValue` in your component. If `_editor.setValue` does not call the method `_onChange` (inside `codemirrorValueChanged`) the parameter `emitEvent` is respected (i.e. it will emit the event for true and not emit for false) because the `formcontrol.setValue` inside `_onChange` is not called. It is also more coherent because it is unnecessary to call `_onChange` to update the form control in the situation 1.

The situation 2 occurs when `_editor` has its value changed internally and fires `codemirrorValueChanged` to update the form control. In this case, `_onChange` is called and emits the event since it calls internally `formcontrol.setValue`.

Therefore, considering the situation 1, `setValue` is configurable and respects its specification. What is not configurable is `_onChange` which always emits the event.

**Comment by olliveirallucas** [comment] 2020-07-15 12:20
@jsonsystems, I am not sure but it seems to me that you have the two following situations: (1) when the form control is updated you must update the `_editor` with the new value and (2) when the `_editor` is updated you must update the form control with the new value.

The situation 1 takes place when you call externally `formcontrol.setValue` that fires the chain `writeValue` -> `set value` -> `_editor.setValue` in your component. If `_editor.setValue` does not call the method `_onChange` (inside `codemirrorValueChanged`) the parameter `emitEvent` is respected (i.e. it will emit the event for true and not emit for false) because the `formcontrol.setValue` inside `_onChange` is not called. It is also more coherent because it is unnecessary to call `_onChange` to update the form control in the situation 1. Here is a modification of the last example with two buttons to emit and not emit the event: [https://stackblitz.com/edit/angular-material-starter-template-tsh9xq](https://stackblitz.com/edit/angular-material-starter-template-tsh9xq). Notice that the text below "From valueChanges.pipe" in the view is not updated when the form control does not emit a value and the `stream` array is not modified.

The situation 2 occurs when `_editor` has its value changed internally and fires `codemirrorValueChanged` to update the form control. In this case, `_onChange` is called and emits the event since it calls internally `formcontrol.setValue`.

Therefore, considering the situation 1, `setValue` is configurable and respects its specification. What is not configurable is `_onChange` which always emits the event.

**Comment by jsonsystems** [comment] 2020-07-23 10:52
@olliveirallucas Thank you for taking the time to look into this. Your fork is nice and clear. The critical sentence you wrote is

_If `_editor.setValue` does not call the method `_onChange` (inside `codemirrorValueChanged`) the parameter `emitEvent` is respected (i.e. it will emit the event for `true` and not emit for `false`) [...]_

I think what caused my confusion was the need for an equality check guarding the call to `_onChange`. I'm going to apply this to my project because, TBH, now that you've explained it, the solution is clearer than the problem. It may be after applying this to my project, I have some recommendations on how to document this clearer.

**Comment by olliveirallucas** [comment] 2020-07-27 12:39
I'm glad to help @jsonsystems. Thank you for you feedback.

**Comment by AndrewKushnir** [comment] 2020-08-13 01:27
Hi, I'm going to close this ticket as it sounds like the solution was proposed by @olliveirallucas. Feel free to reopen if the problem still exists. Thank you.

**Closed by AndrewKushnir** 2020-08-13 01:27 UTC
Labels: comp: forms, state: needs more investigation
