### ISSUE TITLE
Error on http.d.ts

### ISSUE THREAD

**Issue by ericmartinezr** [angular/angular#3740] opened 2015-08-19 23:44 UTC
In the new typings files for http the following lines 

- `type-alias RequestOptionsArgs;`
- `type-alias ResponseOptionsArgs;`

are throwing this error message 

`typings/angular2/http.d.ts(367,16): error TS1005: ';' expected.`
`typings/angular2/http.d.ts(374,16): error TS1005: ';' expected.`

One solution is to comment/remove them.

The file is the one obtained doing

`npm install angular2@2.0.0-alpha.35`

See https://github.com/angular/angular/issues/3733
and https://gitter.im/angular/angular?at=55d4b40d1ba62e4a21fa68cc

**Comment by cghislai** [comment] 2015-08-20 10:58
I also ran into this issue. I modified it to `type RequestOptionsArgs = {};`.

It also complained about not finding the EventEmitter type. So I has to ass `type EventEmitter = {};` as well.

**Comment by todoubaba** [comment] 2015-08-20 11:02
Add  ```///<reference path="./angular2.d.ts"/>```.
Replace ```EventEmitter``` with ```ng.EventEmitter````.

**Comment by ericmartinezr** [comment] 2015-08-20 13:46
Thanks guys, but I created this issue since I don't think is our job to fix it. I have a solution, and it's working, but we can end up breaking the file and its functionality. That's why I reported it as an issue. I'll follow @cghislai solution since it just changed those variables type and didn't not remove them.

**Comment by mhevery** [comment] 2015-08-24 18:49
Duplicate of #3699

**Closed by mhevery** 2015-08-24 18:49 UTC
Labels: state: Periodic Review

**Comment by gdi2290** [comment] 2015-08-24 22:39
For anyone looking for a workaround. During `postinstall` remove the http typings 
`rm -rf node_modules/angular2/bundles/typings/angular2/http.d.ts`
[package.json#L27](https://github.com/angular-class/angular2-webpack-starter/blob/8e4773cdf731e389228b9f394daac6faf644a1bf/package.json#L27) then install tsd that way the file won't be added to tsd.d.ts and make sure to include your own version of http type definitions [here's mine](https://github.com/angular-class/angular2-webpack-starter/blob/8e4773cdf731e389228b9f394daac6faf644a1bf/src/typings/ng2http.d.ts)

here's the tsd issue where they're doing a tsd link
https://github.com/DefinitelyTyped/tsd/issues/204
