### ISSUE TITLE
Define unique page titles in the Angular router (a11y)

### ISSUE THREAD

**Issue by twerske** [angular/angular#41626] opened 2021-04-14 18:49 UTC
# 🚀 feature request

### Relevant Package
This feature request is for @angular/packages/router and @angular/angular.

### Description
In order to increase accessibility and build in best practices, allow an option to provide a unique page title to each path in the Angular router. 

#### TitleService vs Proposed Change
Currently the TitleService allows us to manage page title, which allows developers to add unique page titles. This requires additional work for developers and the contextual knowledge to understand that this not only a best practice, but that page title _needs_ to be managed in order to make your application more accessible. 

Eventually I'd like to see this option enforced as mandatory or throw a warning if not defined, to ensure Angular apps are more accessible by default. This known property could also be more easily caught with a lint rule.

#### Context
W3 defines that [page title must be unique](https://www.w3.org/WAI/WCAG21/Understanding/page-titled). Angular is a single-page app and, as a result, a majority of transitions, such as moving to a new page, do not involve a page reload. This means that out of the box, each page is read with an identical page title, and provides no value for understanding the page's content or purpose for users using a11y services.

### Proposed feature
Define a know `title` property in the router's route definitions, which is then subscribed to automatically and uses the TitleService under the hood to manage page title on routing automatically.

```ts
const routes: Routes = [
  { path: 'chicken', component: ChickenComponent, title: 'Chicken - Farm Demo App' },
  { path: 'goat', component: GoatComponent, title: 'Goat - Farm Demo App' },
  { path: 'frog', component: FrogComponent, title: 'Frog - Farm Demo App' },
  { path: '',   redirectTo: '/goat', pathMatch: 'full' }, // redirects ok without a title
  { path: '**', component: HomeComponent }, // throws warning with no title prop defined
];
```

### Describe alternatives you've considered
TitleService works, but again, it puts the burden on the developer to know about this single page app accessibility pitfall and how to implement unique page titles (and manage subscribing to the router ActivatedRoute or manage title in each route's component).

**Comment by atscott** [comment] 2021-04-14 19:44
This looks like a duplicate of #7630. @twerske @jelbourn - Should we close this one, upvote the other, and just add the notes/suggestions from this one (including the a11y reference)?

**Comment by jelbourn** [comment] 2021-04-15 00:05
@atscott yeah, that makes sense

**Comment by atscott** [comment] 2021-04-15 16:01
Closing as duplicate of #7630

**Closed by atscott** 2021-04-15 16:01 UTC
Labels: P3, comp: router, cross-cutting: a11y, feature
