### ISSUE TITLE
ng-content default content

### ISSUE THREAD

**Issue by mbeckenbach** [angular/angular#12530] opened 2016-10-25 22:03 UTC
**I'm submitting a ...**  (check one with "x")

```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When you add something inside a ng-content tag you get an error message: <ng-content> element cannot have content.

**Expected behavior**
Should render the html inside the ng-content tag as a default if no content was given. 

**Minimal reproduction of the problem with instructions**
Create a component that uses ng-content somewhere. Put some html inside, that should be rendered when nothing else is 'injected' there from outside. Then use the component somewhere else. 

**What is the motivation / use case for changing the behavior?**
In some cases you need a default behavior that can be replaced. In my case its an app header that shows the logo. When you navigate to a sub-page the logo will be replaced by a back button. It feels strange to add something like an input property to hide or show the logo. Some default content for ng content placeholders would feel much more intuitive.

**Please tell us about your environment:**
Win10, Angular CLI beta 18, VS Code
- **Angular version:** 2.1.0
  2.1.0
- **Browser:** 
  All
- **Language:**
  TS
- **Node (for AoT issues):** `node --version` =

**Comment by mbeckenbach** [comment] 2016-10-25 22:04
BTW: If i remember correctly thats the way multi slot transclusion works in ng 1

**Comment by webmutation** [comment] 2017-01-12 16:16
Is there any other way to have a fallback slot content? I found a workaround but its quite ugly

```
`<div #ref><ng-content></ng-content></div> 
           <span *ngIf="ref.childNodes.length == 0">
              Display this if ng-content is empty!
           </span>`
```

**Comment by DzmitryShylovich** [comment] 2017-01-12 16:26
not yet

**Comment by emilio-martinez** [comment] 2017-04-25 17:55
I don't know if adding something _inside_ `ng-content` is really the best approach for this, but I agree that a fallback value would be desirable. Perhaps it could interop with `ngIf Else Then`?

**Comment by Rhonun** [comment] 2017-05-24 14:48
+1

**Comment by sergey-malykh** [comment] 2017-06-26 11:43
+1

**Comment by AndrinGautschi** [comment] 2017-08-05 22:09
Anything new on this feature request?

**Comment by acaua** [comment] 2017-09-15 04:53
@webmutation , theres a slight mistake in your solution: you should test if `"ref.children.length == 0"`, not if `"ref.childNodes.length == 0"`

It should be like this:
``` html
<div #ref><ng-content></ng-content></div> 
<span *ngIf="ref.children.length == 0">
  Display this if ng-content is empty!
</span>
```

**Comment by webmutation** [comment] 2017-09-15 12:23
@acaua Actually that is not my code, but I agree node.children should be used and not node.childNodes, not that it is a mistake but falsely assumes that child nodes are of type Element. Even though it would be reasonable to assume that whatever is projected in ng-content would be of type Element, it can create issues, therefore the proper API should be used, and since node.children is supported for IE9+ cross browser support also is not an issue.

> Node.children is a read-only property that returns a live HTMLCollection of the child elements of Node.

> The Node.childNodes read-only property returns a live collection of child nodes of the given element where the first child node is assigned index 0.
> To get a collection of only elements, use ParentNode.children instead.

If we look at the polyfill for node.children we see the use of childNodes but it is filtered by node.nodeType === 1 (Where nodeType ===1 represents An Element node such as < p >or < div > ), so node.children should always work even when it needs to be polyfilled.

```
Object.defineProperty(constructor.prototype, 'children', {
            get: function() {
                var i = 0, node, nodes = this.childNodes, children = [];
                while (node = nodes[i++]) {
                    if (node.nodeType === 1) {
                        children.push(node);
                    }
                }
                return children;
            }
        });
```

@mbeckenbach You are correct that is the way it works in ng1, therefore it would be nice to keep it consistent, unless there is a good reason to make it different.

Still hopping the ng1 behavior as suggested by OP gets added, since it was straightforward to use.

**Comment by didii** [comment] 2017-10-06 17:05
Keep in mind that both `children` and `childNodes` will have different behavior depending on how you use them. See the examples below to decide which workaround you want to currently use.

-----

`node.children` only works when another **element** is added. Not if only text is present.
Example:

    <default-component>Foo</default-component>

where `default-component` has the template as @acaua mentions:

    <div #ref><ng-content></ng-content></div> 
    <span *ngIf="ref.children.length == 0">
      Display this if ng-content is empty!
    </span>

This will result into

> Foo
> Display this if ng-content is empty!

--------

This is not the case when you use `childNodes`. In that case, the opposite happens if the tag has any whitespace or comment.
Example:

    <default-component></default-component>

or

    <default-component>
    </default-component>

or

    <default-component> </default-component>

with as template

    <div #ref><ng-content></ng-content></div> 
    <span *ngIf="ref.childNodes.length == 0">
      Display this if ng-content is empty!
    </span>

will all result into nothing that is displayed.

**Comment by jack-bliss** [comment] 2018-01-18 10:38
being able to determine wether or not ng-content exists seems very important, and having an option that works with unviersal would be very nice.

**Comment by benneq** [comment] 2018-03-17 01:18
I have a similar requirement:
`<h1><ng-content select="[title]"></ng-content></h1>`
I want to completely remove the `<h1>` if there's no content set.

Though I need something like this:
`<h1 *ngIf="titleRef"><ng-content select="[title]" #titleRef></ng-content></h1>`

**Comment by harm-less** [comment] 2018-09-03 09:33
@benneq I just succeeded with a small hack:

```ts
export class ContentComponent implements AfterViewInit {

  @ViewChild("contentAll")
  contentAll: ElementRef;

  constructor(private changeDetector: ChangeDetectorRef) {  }

  ngAfterViewInit(): void {
    console.log(this.contentAll);

    this.changeDetector.detectChanges();
  }
}
```

```html
<div #contentAll *ngIf="contentAll ? contentAll.nativeElement.children.length : true">
    <ng-content></ng-content>
</div>
```

`contentAll` is not available during init which is why the entire element will NOT be rendered at any point afterwards. When you make sure `contentAll` is true by default after the init phase, you'll be able to use it to check whether or not the `ng-content` element is empty or not. 
Note: the `detectChanges()` was necessary as the change wasn't registered in the HTML after bootstrapping.

It worked for my purposes. I'm not sure if a HTML only fix is possible as I didn't get that to work.

**Comment by benneq** [comment] 2018-09-03 10:01
Your cleaned up version only works if you only use this functionality **once** within a component.

My example was a bit stripped down. In reality it's more like this:
```
<h1><ng-content select="[title]"></ng-content></h1>
<h2><ng-content select="[subtitle]"></ng-content></h2>
<p><ng-content select="[body]"></ng-content></p>
```

And each of `h1`, `h2`, `p` can be empty and shouldn't be rendered if it has no content.

**Comment by WizardPC** [comment] 2018-10-08 09:32
@benneq i have the exact same case with a modal componenet, if footer is empty i don't want to render it.

**Comment by StefanRein** [comment] 2018-11-11 10:17
@WizardPC Thanks!

I wanted to provide a default component if none was set in the ng-content. As they are siblings in my case, one could extend this with your solution. 

##### Which is compatible since IE 9 and partially since IE7/8: https://caniuse.com/#feat=css-sel3

**HTML**
```html
<div class="my-custom-component-content-wrapper">
    <ng-content select="my-custom-component"></ng-content>
</div>
<my-custom-component>
    This shows something default.
</my-custom-component>
```

**CSS**
```css
.my-custom-component-content-wrapper:not(:empty) + my-custom-component {
    display: none;
}
```

**Comment by dawidgarus** [comment] 2018-12-06 11:00
You can abstract the logic to show default content to directive:
https://stackblitz.com/edit/angular-ehefzr?file=src%2Fapp%2Fhello.component.ts

**Comment by wendzhue** [comment] 2019-01-02 07:13
Does Ivy contribute to this?

**Comment by r-hannuschka** [comment] 2019-03-06 20:00
@dawidgarus greate solution i like it, but i get a problem if i do this.

```html
<li class="list-item" translate="SMC_UI.LIST.HEADER.TOTAL" [translateParams]="{COUNT: total}"></li
````

It throws an Exception: 

ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'COUNT: undefined'. Current value: 'COUNT: 0'. It seems like the view has been created after its parent and its children have been dirty checked. Has it been created in a change detection hook ?

What helps me now is to wrap this into a window.setTimeout with a delay from 0, but it looks a bit hackish.

```JavaScript
    public ngAfterContentChecked() {

        const childNodes = Array.from(this.node.childNodes);
        const hasContent = childNodes.some((node) => node.nodeType === 1 || node.nodeType === 3);

        if (hasContent !== this.hasContent) {
            this.hasContent = hasContent;
            if (hasContent) {
                this.container.clear();
            } else {
                window.setTimeout(() => {
                    this.container.createEmbeddedView(this.defaultTemplate)
                }, 0);
            }
        }
    }
```

**Comment by AckerApple** [comment] 2019-03-06 20:36
@r-hannuschka 

I have stupid set zero timeouts, allllllllllllll over our Angular code just to shut that type of error up.

**Comment by didii** [comment] 2019-03-15 10:33
@AckerApple That error is typically due to you as developer not handling change detectin/state changes well. The issue appears when code is executed due to a change detection that changes the state again. This might or might not result in an infinite loop of change detection which is both very bad for performance and means a deeper flaw in how state is handled.
See [this SO answer](https://stackoverflow.com/a/43375600/2158015) or [this blog](https://blog.angularindepth.com/everything-you-need-to-know-about-the-expressionchangedafterithasbeencheckederror-error-e3fd9ce7dbb4) if you want to know more.

**Comment by AckerApple** [comment] 2019-03-15 11:52
@didii, no it’s not as simple as regurgitating some documentation. I know you may think you know the change detection issue and you’ve read that it’s highlighting a deeper issue but you can stop right there.

Often I will bind an ID and a loading counter. When that ID changes, I update the binded loading counter and fetch data. In that scenario, I always setTimeout on my load counter increasing so displayed loading spinners can be displayed without causing the change detection error.

A change can cause changes. Simple as that. I’ve been threw all the documentation on this and still find the setTimeout the best and most widely used.

**Comment by jcroll** [comment] 2019-03-15 14:04
Don't use `setTimeout()` @AckerApple

**Comment by AckerApple** [comment] 2019-03-15 14:15
@jcroll, both links provided by @didii, have references to recommending use of setTimeout.

I've been up and down this topic too many times and concluded it's just so much less hassle to actually make use of setTimeout. My typical use case is for loading indicators.

I could, do and have, used a shared provider class so nothing has to be binded at all. But I many times found myself not wanting to create a provider, register it, require it, and so on..... You cannot convince me not to use the setTimeout, I'm too confident in my Angular knowledge that I know when I can get away with a two-way bind that has a setTimeout to break the change cycle.

I got guys. I do. I'm going to continue using setTimeout and recommending it

**Comment by jcroll** [comment] 2019-03-15 14:33
Here's an idea @AckerApple try removing the setTimeouts and see if your problem goes away. Come back and let us know how it turns out

**Comment by AckerApple** [comment] 2019-03-15 14:36
Yo @jcroll , my original comment was intended to give the guy @r-hannuschka a little confidence that the setTimeout is not a sin.

I'll tell you what happens if I remove my setTimeouts.... I get dev errors only.

**Comment by didii** [comment] 2019-03-15 14:37
@AckerApple @jcroll may I suggest moving this discussion elsewhere? I did not intent to start a discussion on that topic since this it's not related to the OP. All we are doing now is spamming other peoples inboxes with an issue that doesn't concern them and making this issue harder to read...

**Comment by wottpal** [comment] 2019-03-27 11:30
> Does Ivy contribute to this?

Did anybody answer to @wendzhue's question? Would be really interesting to know if the Angular-team cares about this issue because obviously there is a **lot** of demand.

**Comment by deftomat** [comment] 2019-04-11 12:19
🙃  Still hacking Angular even after almost 3 years. It's really disappointing especially in compare to React.

**Comment by AckerApple** [comment] 2019-04-16 15:59
@deftomat

For the original issue, I found learning an alternate approach was what was needed to achieve my needs that I wrongly thought ng-content should handle.

I stirred up the pot wrongly recommending setTimeout to break change cycle. I've learned `Promise.resolve.then` is faster and less impactful than setTimeout BUT ALSO that is still not enough AND I learned passing emitters as bindings completely removed any need to break change cycles for me

I can admit when wrong and I'm both sorry and thankful to those in this thread for reaching out, it helped correct me.

@deftomat, I've laid out crappy comments just like you have done here but I've been wrong and you right here are wrong. We are not hacking. Speaking for myself, I've got old knowledge and old ways and old "wrong" habits that I've had to unlearn. Not hacking though, that's just a rude assumption.

**Comment by deftomat** [comment] 2019-04-16 16:39
Oh dear. It was not an attack and I don't want to offend anyone 😉. I'm just pointing out that angular is missing the one key part for a truly reusable components. We just need to be able to access a projection slots from TypeScript files before anything is rendered. To me, it looks quite hacky, to read the rendered content to be able to determine if someone pass a data to my component.

To be honest, a projected data should be available in component as inputs and component should decide what to render. 

Unfortunately, angular just renders a projected data and you need to use a special, funky, code to find out what just happenend.

**Comment by kevinmpowell** [comment] 2019-04-18 14:15
Just coming to this post today and wanted to highlight the solution offered by @dawidgarus. It seems fairly elegant and is working for my needs: https://github.com/angular/angular/issues/12530#issuecomment-444833662

**Comment by kevinmpowell** [comment] 2019-04-18 18:43
I ran into the aforementioned `ExpressionChangedAfterItHasBeenCheckedError` with @dawidgarus ' solution and was able to solve it via this change:

```
import { Directive, Input, TemplateRef, AfterContentChecked, ContentChild, ElementRef, ViewContainerRef, Renderer2, HostBinding } from '@angular/core';

@Directive({
  selector: '[noContent]',
})
export class NoContentDirective implements AfterContentChecked {

  @Input()
  noContent: TemplateRef<any>;

  private element: HTMLElement;
  private hasContent = true;

  constructor(
      element: ElementRef,
      private container: ViewContainerRef,
      private renderer: Renderer2) {
        this.element = element.nativeElement;
    }

  ngAfterContentChecked(): void {
    let hasContent = false;
    for (let i = this.element.childNodes.length-1; i >= 0; --i) {
      const node = this.element.childNodes[i];
      if (node.nodeType === 1 || node.nodeType === 3) {
        hasContent = true;
        break;
      }
    }
    if (hasContent !== this.hasContent) {
      this.hasContent = hasContent;
      if (hasContent) {
        this.renderer.removeClass(this.element, 'is-empty');
        this.container.clear();
      } else {
        // WRAP ELSE STATEMENT IN requestAnimationFrame
        window.requestAnimationFrame(() => {
          this.renderer.addClass(this.element, 'is-empty');
          this.container.createEmbeddedView(this.noContent);
        });
      }
    }
  }
}
```

Is this better than `setTimeout`? I'm not sure...but it works in my early, basic testing. The error no longer appears in console in either dev or prod mode.

**Comment by AckerApple** [comment] 2019-04-18 18:55
I recently did a lot of homework on this subject thanks to others pushing me to do so.

Slowest
```
setTimeout(() => {
  this.renderer.addClass(this.element, 'is-empty');
  this.container.createEmbeddedView(this.noContent);
});

Faster, depending on what the window is currently working on until next repaint cycle
```
window.requestAnimationFrame(() => {
  this.renderer.addClass(this.element, 'is-empty');
  this.container.createEmbeddedView(this.noContent);
});
```

Faster
```
Promise.resolve().then(()=>{
  
  this.renderer.addClass(this.element, 'is-empty');
  this.container.createEmbeddedView(this.noContent);
})
```

Lastly, I theorize a faster way exists by NOT using `ngAfterContentChecked` at all and that using something like an HTML MutationObserver would be the most performant way to go.

**Comment by adover** [comment] 2019-04-25 00:55
This seemed like the cleanest way to me, could be put into a directive too:
```
  hasMessage = () =>
    this.content.nativeElement.childNodes.length > 0 &&
    Boolean(this.content.nativeElement.childNodes[0].textContent.trim());
```

I'm making an assumption that the first element will have some form of text, which seems like a fair assumption for most use cases.

**Comment by rsarmiento-pl** [comment] 2019-05-16 02:17
Any update on this feature request?

I am using this workaround for the meantime:

```
  <div>
    <div #customContentContainer>
      <ng-content select="[customContent]" ></ng-content>
      <ng-container  *ngIf="customContentContainer?.firstElementChild?.hasAttribute('customContent'); else defaultContent">
      </ng-container>
    </div>
    <ng-template #defaultContent>
        <div>This is the default content</div>
    </ng-template>
  </div>


<custom-component>
  <span customContent> My Custom Content Here</span>
</custom-component>

or for the default:

<custom-component>
</custom-component>
```

**Comment by stepancar** [comment] 2019-11-05 20:43
https://medium.com/@istepancar/how-to-avoid-render-wrapper-for-ng-content-when-it-not-passed-in-dartangular-d89cb3b026a

**Comment by matheo** [comment] 2020-11-16 17:07
@mhevery looking at [this answer at StackOverflow](https://stackoverflow.com/a/35111426/885259), they mention Aurelia's fallback slots, and Vue's default content inside ng-content.
Can we have a clean solution like that please? this is 4 years old,
and is looking like Bitbucket without CODEOWNERS support at this day :( sad stuff

**Comment by mhevery** [comment] 2020-11-16 20:37
It is on our radar, but we have higher priority items in front of it, so it will be a while.

**Comment by lukenofurther** [comment] 2021-02-01 11:22
Vue's slot implementation is truly elegant - default content just goes inside the slot tag, as the OP here suggested. It's incredibly simple and makes it nice and easy to use higher order components. Because it's handled by the core library there's no need to worry about which workaround you use and the compatibility between versions/situations etc.

Angular has some catching up to do here.

**Comment by woeterman94** [comment] 2021-08-31 13:18
Is there any update years later? :)

**Comment by adumesny** [comment] 2021-09-09 00:05
so many votes, such an elegant solution others are doing...and 4 years later.

**Comment by MonsieurMan** [comment] 2021-11-23 16:12
I managed to workaround using `querySelector`. It only works if you expect a specific selector from your users though.
```ts
@Component({
	selector: "default-ng-content",
	template: `
		<ng-content select="[selector]"></ng-content>
		<ng-template [ngIf]="useDefaultContent">
			Here your default content
		</ng-template>
	`,
})
export class DefaultNgContentComponent implements AfterContentInit {
	useDefaultContent = false;

	constructor(private elRef: ElementRef<HTMLElement>) {}

	ngAfterContentInit() {
		// We check if there is the expected selector deeper in the DOM
		const nav = this.elRef.nativeElement.querySelector("[selector]");
		// If not, we use the default content.
		this.useDefaultContent = nav === null;
	}
}
```

**Comment by michaelurban** [comment] 2022-04-01 17:13
@AndrewKushnir This is something that I bump against time and time again. Feels like it's another basic feature/bug that the community has decided is a priority but one that Google has stamped "NOT A PRIORITY" onto the tin. It has been almost five and a half (5.5) years. Would a community implementation be consider or accepted? 

I have about 6 issues like this that I track, basic Angular functionality that is missing/incorrect. I have dozens if not hundreds of instances of workarounds in my codebases. It's getting ridiculous. Removing any one class of workaround is going to be a major feat if/when the fix comes.

Imagine if `ngIf` didn't exist and you instead developers had to put `<selector>:empty` all over their codebases with notes that like: "Needs to be updated once Angular Bug #XYZLMNOP is addressed." After six years you're going to have a lot of code to update. 

That's the position you're putting thousands of developers into by keeping issues like these open. 

It's disrespectful.

**Comment by jodinathan** [comment] 2022-04-01 17:20
this exists and work ok in AngularDart.  

maybe Google could ask how they did it?

**Comment by r-hannuschka** [comment] 2022-04-02 05:47
> 

i think this is a good solution, instead of a specific listener you can use a Directive which has a data selector which can be used as selector.

If you expect it is a static value or it is allways existing or not (static) you can use ContentChild for this and skip afterContentInit or timeouts. 

@example

```ts
@Directive(
   selector: "[myContentDirective]"
)
class MyContentDirective {}

@Component({
   template: `
    <div ngIf="!defaultContent"> default content </div>
    <ng-content [selector]="myContentDirective"></ng-content>
   `
})
class MyComponent {
  // static true so we expect it exists as soon the component is rendered and not hidden by ngIf, nfSwitchCase, async
  @ContentChild(MyContentDirective, { read: MyContentDirective, static: true }) 
  private defaultContent: MyContentDirective;
}
```

**Comment by jmroon** [comment] 2022-05-19 22:21
The current workarounds are not adequate. Having to have a wrapper div functionality breaks things such as mat-label inside a mat-form-field.

Please fix this. This is a common need and an essential feature for a framework in 2017, let alone 2022.

**Comment by lexeek** [comment] 2022-06-15 16:10
Angular team! We are still waiting for this feature to be implemented!

**Comment by atgote** [comment] 2022-06-22 14:27
Looks like we'll not see this until v15... Definitely a **must have**, but...

**Comment by sharshuv-quotient** [comment] 2022-07-17 13:26
> I don't know if adding something _inside_ `ng-content` is really the best approach for this,...

I actually think that putting something inside ng-content can be very easy and intuitive. That is the first thing I tried before googling and realizing it's impossible.

**Comment by Den-dp** [comment] 2023-09-14 21:28
I was surprised that this doesn't work the same way as [`NgTransclude` with a fallback content (angular.js)](https://docs.angularjs.org/api/ng/directive/ngTransclude#transclude-fallback-content)

**Comment by vneogi199** [comment] 2023-11-27 08:44
Can we have something like the default placeholder for `ng-content`, similar to [defer placeholder](https://angular.dev/guide/defer#placeholder)

**Comment by tutkli** [comment] 2024-02-21 13:20
Any news on this?

**Comment by LPCmedia** [comment] 2024-03-09 01:47
The design choice of having a "default behavior" that needs to be overridden in some cases seems like misguided inheritance. When a component has an input that basically is an if/else its likely 2 components or if absolutely needed conditional content projection. This means you have to bind this input for all sub-routes as well...

On the other hand: its unclear why **ng-content** wouldn't have the same behavior as a `<slot>` in a standard web-component.

**Closed** 2024-03-26 16:18 UTC
Labels: feature, freq3: high, area: core, state: has PR, core: content projection, feature: under consideration

**Comment by nelson6e65** [comment] 2024-04-19 03:14
Only for Angular 18? 👀
