### ISSUE TITLE
ComponentFactoryResolver with ngStyle

### ISSUE THREAD

**Issue by HarelM** [angular/angular#16582] opened 2017-05-05 12:58 UTC
**I'm submitting a ...**  (check one with "x")

 - [x] bug report => search github for a similar issue or PR before submitting

**Current behavior**
[ngStyle] is ignored when using a dynamic component

**Expected behavior**
[ngStyle] should not be ignored

**Minimal reproduction of the problem with instructions**
Using the quick start, here are the relevant changes (I couldn't find a ready to use plunker I can duplicate and share...)
Add a dynamic component:
```ts
@Component({
    selector: "dynamic",
    template: `<div [ngStyle]="{color: 'red'}">Red</div>`
})
export class DynamicComponent { }
```
in app.component.ts:
```ts
@Component({
  selector: 'my-app',
  template: `<h1 [ngStyle]="{color: 'red' }">Hello {{name}}</h1>`
})
export class AppComponent { 
  name = 'Angular'; 
  constructor(private injector: Injector,
  private componentFactoryResolver: ComponentFactoryResolver,) {
    let componentFactory = this.componentFactoryResolver.resolveComponentFactory(DynamicComponent);
    let divComp = document.getElementById("thisOne");
    componentFactory.create(this.injector, [], divComp);
  }
}
```
in index.html add a div and remove all existing styles:
```html
<body>
    <div id="thisOne"></div>
    <my-app>Loading AppComponent content here ...</my-app>
  </body>
```

This is what I get:
![image](https://cloud.githubusercontent.com/assets/3269297/25746236/3e95b6c8-31ab-11e7-996c-1c37c9e14c52.png)

the word "red" should be in red color I believe, unless I did something wrong.

**Please tell us about your environment:**
I'm using visual studio, but I don't think it matters here as I was able to reproduce it in a plunker that I can't share for some reason...

* **Angular version:** 4.0.3

* **Browser:** checked on Chrome, but probably all
 
* **Language:** TypeScript 2.2.1 | ES6

**Comment by trotyl** [comment] 2017-05-05 14:29
There is no `directives` property in Component metadata since version 2.0.0-rc.5, you cannot even pass the TypeScript checking with such code, see [Component](https://angular.io/docs/ts/latest/api/core/index/Component-decorator.html) for more imformation.

**Comment by HarelM** [comment] 2017-05-05 14:40
@trotyl Those were some attempts I made in order to try and make this work. nothing helped...
In any case I removed it from my post. Thank for the info, although it doesn't really help...

**Comment by trotyl** [comment] 2017-05-06 04:15
Your description doesn't help as well, you should at least provide a minimal reproduction which is runnable.

**Comment by trotyl** [comment] 2017-05-06 04:33
@HarelM Just change the code:

```typescript
constructor(
  private injector: Injector,
  private componentFactoryResolver: ComponentFactoryResolver
) {
  let componentFactory = this.componentFactoryResolver.resolveComponentFactory(DynamicComponent);
  let divComp = document.getElementById("thisOne");
  componentFactory.create(this.injector, [], divComp);
}
```

To:

```typescript
constructor(
  private injector: Injector,
  private componentFactoryResolver: ComponentFactoryResolver,
  private applicationRef: ApplicationRef,
) {
  let componentFactory = this.componentFactoryResolver.resolveComponentFactory(DynamicComponent);
  let divComp = document.getElementById("thisOne");
  let componentRef = componentFactory.create(this.injector, [], divComp);
  this.applicationRef.attachView(componentRef.hostView);
}
```

Will solve your problem, you can see in http://plnkr.co/edit/smezTdYXdoc2ro92HIad?p=preview. **It's a common error for beginners to forget attaching the view to the app, so the change detection will not run for that dynamic view**. That's nothing to do with NgStyle.

Your not providing a runnable example but just giving misleading description will waste a lot of time for others.

**Comment by HarelM** [comment] 2017-05-06 06:04
@trotyl Thanks for your answer, I truly appreciate it.
Things to think about:
1. Here is the documentation for component resolver:
https://angular.io/docs/ts/latest/api/core/index/ComponentFactoryResolver-class.html
It's fairly easy to see that if I'm a beginner it will be hard for me to solve this error on my own since there's not a single word there about it.
2. The breaking changes introduced in angularjs to angular and changes made until the beta exit have made the internet a horrible place to look for answers since you can't understand which is used where.
3. I couldn't find a proper way to send a reproducible scenario since the plunker I found were not relevant, adding a relevant plunker here when opening an issue would help a lot, or even sending one as a response in order to reduce the time it takes to reproduce would've helped.

As a side note, @trotyl your answers are very offending, you should consider toning them down - I'm seeking for help not seeking to blame since the documentation are not so well and the confusion around the internet is great, I'm a very seasoned developer and the fact that I run into this issues probably indicates that more like me are running into them but are not expressing it...
At any point you could send me a basic plunker and ask for me to change the code, instead you chose send an offending message, another thing to think about...

**Comment by trotyl** [comment] 2017-05-06 07:33
I do apologize for what may not be polite enough, but there're some my points:

+ The guidance ([CONTRIBUTING](https://github.com/angular/angular/blob/master/CONTRIBUTING.md) and [ISSUE_TEMPLATE](https://github.com/angular/angular/blob/master/.github/ISSUE_TEMPLATE.md)) have made it clear that **Github issue of Angular is not for support questions**, you should seek for help in Gitter or StackOverflow if you have some concerns about how to implemented some feature. I suggest it's better to ask for help in Gitter first to make sure you're doing the right thing in right way before report it as a bug.
+ [Plunker](http://plnkr.co/) does **provide a built-in Angular template** that you can find in the `New` button, in the simple case like this issue you can use that directly, and I did just copy your code into that Angular template to the Plunker in my comment above. I didn't see the needs for a customized plunker template for this problem.
+ I agree on the current documentation not being good enough, and [dynamic-component-loader](https://angular.io/docs/ts/latest/cookbook/dynamic-component-loader.html) is to blame for not providing the use case without ViewContainerRef.
+ Some well-known Angular library may be useful in this case, like [Angular Material Modal](https://github.com/angular/material2/blob/master/src/lib/core/portal/dom-portal-host.ts#L47).

**Comment by trotyl** [comment] 2017-05-06 07:50
Besides, creating a dynamic component without ViewContainerRef is a super rare use case only for application with multiple root elements. For example, it's useful for some special feature like modal which should be directly under `body` node. Could you help to explain what your special case is that cannot follow the way that [dynamic-component-loader](https://angular.io/docs/ts/latest/cookbook/dynamic-component-loader.html) suggests?

**Comment by trotyl** [comment] 2017-05-06 08:20
In the [Leaflet documentation](http://leafletjs.com/reference-1.0.3.html#map-factory), there is an overload for using element reference rather than global id lookup:

> L.map(`<HTMLElement>` el, `<Map options>` options?)
> Instantiates a map object given an instance of a `<div>` HTML element and optionally an object literal with Map options.

I guess that would be a better way to integrate with Angular, by encapsulating it into an Angular component with `ViewChild` rather than exposing the Angular view globally.

**Comment by HarelM** [comment] 2017-05-06 18:33
I must say that your answer got me thinking I need to read a bit more about view, elementref etc. as I feel I can't give you a good answer without sounding like a total noob.
Let's see if I make sense in any way:
Assuming I would like to use your solution with `ViewChild` it means that I have an `appComponent` that has a child view that holds the `mapComponent` and I can init leaflet with an element instead of id.
There are some problems with this approach I think (not sure)
1. The map object is a very low level component and I need it in most of the app so I need it in a service, so In order to init the service I need the elementRef and this means I need to wait for it in all of my services (not sure this point is clear) which is not ideal.
2. When I create a marker on the map I use `bindTooltip` which needs a resolved component, so as to my understanding I still need the `ApplicationRef` class there too.
3. When I want to create a control (buttons on the right and left side) on the map I need to create a component which need `ApplicationRef` I believe.

Here is what I want to achieve when the migration will be finished: http://israelhiking.osm.org.il/
Currently I'm in the process of migrating from AngularJs to angular and the above is the migration of the `$compile` usages.
I'll play with the child view nevertheless to see if I can make it more Angular-ish.
Thanks again for you kind help!

**Comment by tbosch** [comment] 2017-05-08 23:28
Closing as the initial problem of this issue was resolved (i.e. the missing piece was attaching the view).

**Closed by tbosch** 2017-05-08 23:28 UTC
Labels: comp: core & compiler
