### ISSUE TITLE
Using web components inside Angular component

### ISSUE THREAD

**Issue by niranjan-borawake** [angular/angular#15202] opened 2017-03-16 09:05 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request 
```

**Current behavior**

When a web component is used inside an Angular component, attributes specified on web component are not available inside `attachedCallback` of web component. Also, when an attribute value for a web component is specified using an interpolation operator `value="{{value}}"`, Angular changes attribute name with a `ng-reflect-` prefix and manages it internally. Because of this there is no way `attributeChangedCallback` could trigger appropriately.

**Expected behavior**

There should be a way to use web component inside Angular component in a way such that attributes are available inside `attachedCallback` and `attributeChangedCallback` is triggered correctly for appropriate attributes.

**Minimal reproduction of the problem with instructions**

This shows a sample Toggle Button web component used inside Angular component.
https://plnkr.co/edit/MwLh8ssnjOdqA8C4PhZq?p=preview 

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [Chrome]

 
* **Language:** [ES6]

**Comment by DzmitryShylovich** [comment] 2017-03-16 10:25
> Angular changes attribute name with a ng-reflect- prefix and manages it internally

this is debug info. you can disable it by enabling prod mode. 

Duplicate of https://github.com/angular/angular/issues/13699

**Comment by niranjan-borawake** [comment] 2017-03-16 13:30
> this is debug info. you can disable it by enabling prod mode.

In prod mode attribute itself is not available on DOM element.

**Comment by zoechi** [comment] 2017-03-18 17:33
@niranjan-borawake if you need the attribute with binding to be added to the DOM you need to use attribute binding instead of property binding https://plnkr.co/edit/NMCLHQ4H1kVzDH1YbhNV?p=preview (`attr.value="{{value}}" attr.yes-label="{{yesLabel}}"`)

**Comment by niranjan-borawake** [comment] 2017-03-25 07:51
@zoechi Thanks. This helps and `attributeChangedCallback` fires with appropriate arguments.

**Comment by zoechi** [comment] 2017-05-09 09:30
Can this be closed? I don't think this is supposed to work without `attr.`

**Comment by niranjan-borawake** [comment] 2017-05-18 12:08
Yes. With `attr` I could see `attributeChangedCallback` firing. For the first part i.e. `attachedCallback` there is already a duplicate #13699, which I could look for. Thanks @zoechi .

**Comment by pkozlowski-opensource** [comment] 2017-07-24 15:59
Closing as the root cause of the issue was confusion between attribute and property bindings.

**Closed by pkozlowski-opensource** 2017-07-24 15:59 UTC
Labels: comp: core & compiler, type: bug
