### ISSUE TITLE
Ivy - exportAs - failed to find

### ISSUE THREAD

**Issue by kamilkisiela** [angular/angular#33628] opened 2019-11-06 16:10 UTC
Angular Compiler has some trouble with `exportAs` when Ivy is enabled.

I don't think there's more to add because the reproduction is done within 5 lines of code, everything is in the linked repository. I prepared GitHub Action as CI to show exactly when and where error happens.

# 🐞 bug report

### Affected Package
Not sure but the issue might be caused by package @angular/compiler-cli

### Is this a regression?
Yes, it works when Ivy is disabled.

### Description
Ivy has problems with `exportAs`.

## 🔬 Minimal Reproduction
Very very minimal reproduction with CI: https://github.com/kamilkisiela/angular-ivy-exportAs-issue

```html
<div bug #ref="bug">...</div>
```

```typescript
@Directive({
  selector: 'bug',
  exportAs: 'bug',
})
export class BugDirective {}
```

## 🔥 Exception or Error
<pre><code>ERROR in Assertion error: failed to find directive with exportAs: bug</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre>
<code>Angular CLI: 9.0.0-rc.0
Node: 10.16.3
OS: darwin x64
Angular: 9.0.0-rc.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-rc.0
@angular-devkit/build-angular     0.900.0-rc.0
@angular-devkit/build-optimizer   0.900.0-rc.0
@angular-devkit/build-webpack     0.900.0-rc.0
@angular-devkit/core              9.0.0-rc.0
@angular-devkit/schematics        9.0.0-rc.0
@ngtools/webpack                  9.0.0-rc.0
@schematics/angular               9.0.0-rc.0
@schematics/update                0.900.0-rc.0
rxjs                              6.5.3
typescript                        3.6.4
webpack                           4.41.2
</code></pre>

**Anything else relevant?**

**Comment by alexzuza** [comment] 2019-11-06 16:48
Shouldn't you use attribute selector in case of `<div bug` markup?

```
@Directive({
  selector: '[bug]', <------ like this
  exportAs: 'bug',
})
```

**Comment by JoostK** [comment] 2019-11-06 18:24
As @alexzuza mentions, the selector needs to be `[dir]` if used as `<div bug>`. I tested with your reproduction repo and cannot reproduce, unless I change `[dir]` to `dir`, in which case it does fail. The error has been cleaned up in #33454 which will be released with the next RC.

I'll go ahead and close this, but if you do still experience issues please mention it here or open a new issue. Thanks!

**Closed by JoostK** 2019-11-06 18:24 UTC
