### ISSUE TITLE
Unable to access HTTP Client section in Angular Documentation

### ISSUE THREAD

**Issue by TejAllam** [angular/angular#42167] opened 2021-05-19 04:31 UTC
# Docs or angular.io Bug Report

### Description

Unable to access HTTP section in the Angular documents. 
[angular.io-1621398076376.log](https://github.com/angular/angular/files/6505825/angular.io-1621398076376.log)
[angular.io-1621398053294.log](https://github.com/angular/angular/files/6505826/angular.io-1621398053294.log)
[angular.io-1621398119508.log](https://github.com/angular/angular/files/6505828/angular.io-1621398119508.log)
[angular.io-1621398126137.log](https://github.com/angular/angular/files/6505829/angular.io-1621398126137.log)
[angular.io-1621398134428.log](https://github.com/angular/angular/files/6505830/angular.io-1621398134428.log)

### What's the affected URL?**
https://angular.io/guide/http

### Reproduction Steps**

Visit angular.io
Search for 'POST' in the search bar. 
Click on HTTP link 

Accessing the HTTP Client in the sidebar does not work either 

## Screenshot
![angular_console_error](https://user-images.githubusercontent.com/16512061/118756417-df5c9c80-b838-11eb-928a-7bc41559a115.png)

![angular_console_error_2](https://user-images.githubusercontent.com/16512061/118756585-3febd980-b839-11eb-8f18-9a2ce3d1d278.png)

## Exception or Error
<pre><code>

main-es2015.5bdd22efd2bd48dd1d9e.js:1 ERROR Error: [DocViewer] Error preparing document 'guide/http': ChunkLoadError: Loading chunk 16 failed.
(error: https://angular.io/toc-toc-module-es2015.d1fa63cbc4f8ec0088ea.js)
    at Function.c.e (runtime-es2015.079cdaf7df823193c268.js:1)
    at loadChildren (main-es2015.5bdd22efd2bd48dd1d9e.js:1)
    at t.loadCustomElement (main-es2015.5bdd22efd2bd48dd1d9e.js:1)
    at main-es2015.5bdd22efd2bd48dd1d9e.js:1
    at Array.map (<anonymous>)
    at t.loadContainedCustomElements (main-es2015.5bdd22efd2bd48dd1d9e.js:1)
    at u.project (main-es2015.5bdd22efd2bd48dd1d9e.js:1)
    at u._next (main-es2015.5bdd22efd2bd48dd1d9e.js:1)
    at u.next (main-es2015.5bdd22efd2bd48dd1d9e.js:1)
    at c._next (main-es2015.5bdd22efd2bd48dd1d9e.js:1)
    at c.selector (main-es2015.5bdd22efd2bd48dd1d9e.js:1)
    at c.error (main-es2015.5bdd22efd2bd48dd1d9e.js:1)
    at c._error (main-es2015.5bdd22efd2bd48dd1d9e.js:1)
    at c.error (main-es2015.5bdd22efd2bd48dd1d9e.js:1)
    at u._error (main-es2015.5bdd22efd2bd48dd1d9e.js:1)
    at u.error (main-es2015.5bdd22efd2bd48dd1d9e.js:1)
    at c._error (main-es2015.5bdd22efd2bd48dd1d9e.js:1)
    at c.error (main-es2015.5bdd22efd2bd48dd1d9e.js:1)
    at u.notifyError (main-es2015.5bdd22efd2bd48dd1d9e.js:1)
    at r._error (main-es2015.5bdd22efd2bd48dd1d9e.js:1)
</code></pre>

### Browser info

Chrome and Firefox

**Comment by petebacondarwin** [comment] 2021-05-19 14:50
I believe this is a duplicate of https://github.com/angular/angular/issues/42075.
Can you try a hard-refresh of your browser.

**Closed by petebacondarwin** 2021-05-19 14:50 UTC

**Comment by TejAllam** [comment] 2021-05-20 02:08
I did do a hard-refresh. Opened browser in private mode, etc.
Also, doesn't explain how it failed in both Chrome and Firefox simultaneously. 
That cannot be a coincidence right ?

**Comment by petebacondarwin** [comment] 2021-05-20 14:45
Is it still a problem?

I wonder if it caching issue on some Firebase hosting CDN node in your local area?

**Comment by TejAllam** [comment] 2021-05-21 14:29
> 
> 
> Is it still a problem?
> 
> I wonder if it caching issue on some Firebase hosting CDN node in your local area?

Agreed. This has not occurred since. Thanks.
