### ISSUE TITLE
Wrong warning : ng8102

### ISSUE THREAD

**Issue by wupaz** [angular/angular#44859] opened 2022-01-27 14:44 UTC
### Which @angular/* package(s) are the source of the bug?

compiler

### Is this a regression?

Yes

### Description

Wrong warning in this case 

Exemple : 
warning NG8102: The left side of this nullish coalescing operation does not include 'null' or 'undefined' in its type, therefore the '??' operator can be safely removed.

<td mat-cell *matCellDef="let element"> {{element.CurrentLock?.Clinician?.Label ?? '--'}} </td>

In this case CurrentLock and Clinician could be null 

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.2.0
Node: 14.18.3
Package Manager: npm 6.14.15
OS: win32 x64

Angular: 13.2.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, localize, material, material-moment-adapter
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1302.0
@angular-devkit/build-angular   13.2.0
@angular-devkit/core            13.2.0
@angular-devkit/schematics      13.2.0
@schematics/angular             13.2.0
rxjs                            6.6.7
typescript                      4.5.4
```

**Comment by geromegrignon** [comment] 2022-01-27 14:49
The problem in this situation is more related to `Label`.
Does its type include null and undefined?

**Comment by JoostK** [comment] 2022-01-27 15:14
What are all the types involved in `{{element.CurrentLock?.Clinician?.Label ?? '--'}}`? What are the TS compiler options, i.e. `strictNullChecks` etc.

I guess I am asking for a reproduction.

**Comment by yutamago** [comment] 2022-01-27 17:24
This warning is popping up all over my logs since I updated to Angular 13.2.0.
I can't really tell why the first line is fine and the second one throws a warning:
![image](https://user-images.githubusercontent.com/12561505/151410435-7be8cb6e-0fb9-4abd-824d-41ce11383c44.png)

They are defined (in a third party package) as follows:
```ts
keyExpr?: string | Function;
rootValue?: SomeInterface;
```

**Comment by wupaz** [comment] 2022-01-27 17:29
I try to reproduce on CodeSandbox without success.

My tsconfig file
{
  "compileOnSave": false,
  "compilerOptions": {
    "noImplicitAny": true,
    "noImplicitThis": true,
    "strictNullChecks": true,
    "baseUrl": "src",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "module": "es2020",
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "es2018",
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "lib": [
      "es2018",
      "dom"
    ]
  },
  "angularCompilerOptions": {
    "enableIvy": true,
    "fullTemplateTypeCheck": true,
    "strictTemplates": true,
    "strictInjectionParameters": true
  }
}

**Comment by wupaz** [comment] 2022-01-27 17:37
> The problem in this situation is more related to `Label`. Does its type include null and undefined?

No, Label can't be null

**Comment by JoostK** [comment] 2022-01-27 17:44
I will have a look at this.

**Comment by JoostK** [comment] 2022-01-27 18:50
This is broken when there's an `any` or `unknown` type, I have a fix for that. Can people share more cases where the check is broken?

**Comment by JoostK** [comment] 2022-01-27 20:14
There's also an issue when `strictNullChecks` and `strict` are both disabled (or their default values), which is also being fixed in #44862.

**Comment by sod** [comment] 2022-01-28 10:43
Also `string[]` yields this warning, even though the compiler can't guarantee that all possible index values return a string.

```
public foo: string[] = []
...
{{ foo[123456] ?? '' }}
```
<img width="1143" alt="CleanShot 2022-01-28 at 11 43 37@2x" src="https://user-images.githubusercontent.com/905328/151533302-12d8798b-f846-48f3-a7b3-ea40bc2fc009.png">

**Comment by JoostK** [comment] 2022-01-28 10:48
> Also `string[]` yields this warning, even though the compiler can't guarantee that all possible index values return a string.
> 
> ```
> public foo: string[] = []
> ...
> {{ foo[123456] ?? '' }}
> ```
> 
> <img alt="CleanShot 2022-01-28 at 11 43 37@2x" width="1143" src="https://user-images.githubusercontent.com/905328/151533302-12d8798b-f846-48f3-a7b3-ea40bc2fc009.png">

Ah, that's an interesting one. TS doesn't include `|undefined` in array element accesses, but we should probably not report for this case.

**Comment by tripodsgames** [comment] 2022-01-30 01:58
Same here:
![image](https://user-images.githubusercontent.com/11417768/151683775-65527fb7-8008-4934-9881-15044edef4ed.png)
![image](https://user-images.githubusercontent.com/11417768/151683782-f43d8fe2-2a01-4d1d-959e-0517620b0d98.png)

**Comment by JoostK** [comment] 2022-02-02 19:02
13.2.1 is out which should have improved things. I'll keep this open for a while, please report situations where you believe the rule is incorrect below.

**Comment by FabienCH** [comment] 2022-02-09 13:30
Hello,
We are having this issue with:
````
Angular: 13.2.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... material, platform-browser, platform-browser-dynamic
... platform-server, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1302.1
@angular-devkit/build-angular   13.2.1
@angular-devkit/core            13.2.1
@angular-devkit/schematics      13.2.1
@angular/cli                    13.2.1
@nguniversal/express-engine     13.0.2
@schematics/angular             13.2.1
rxjs                            7.5.2
typescript                      4.5.5
````
````typescript
@Input() btnLabel?: string;
````
````HTML
{{ btnLabel ?? 'Validate' }}
````

**Comment by JoostK** [comment] 2022-02-09 14:11
@FabienCH Please update to latest Angular.

**Comment by FabienCH** [comment] 2022-02-09 14:31
Sorry I thought we had the latest. It works fine now.

**Comment by alxhub** [comment] 2022-03-04 00:03
Closing as fixed.

**Closed by alxhub** 2022-03-04 00:03 UTC
Labels: needs reproduction, state: has PR, comp: compiler
