### ISSUE TITLE
TypeScript 3.5 Support

### ISSUE THREAD

**Issue by gcalison** [angular/angular#31059] opened 2019-06-14 17:32 UTC
# 🚀 feature request

### Relevant Package

 This feature request is for all Angular projects (components, cli, etc).

### Description
Angular does not support TypeScript 3.5.

### Describe the solution you'd like
Add support for TypeScript 3.5.

TypeScript 3.5 sidenote [from here](https://github.com/microsoft/TypeScript/issues/31639):
"_Note that this release shifts TypeScript from a 2-month release cycle to a 3-month release cycle._"
Hopefully this new release cycle will make it easier for Angular to adopt releases faster.😉

**Comment by snebjorn** [comment] 2019-06-26 14:29
Hope this will make it into v8.1 because:

> One of the main highlights of this release is actually a fix for a type-checking bug the TypeScript team introduced in v3.4 that **caused longer build times** and made TypeScript/JavaScript editor operations "**unbearably slow**".

**Comment by GoGoris** [comment] 2019-06-26 15:53
Support for Object.fromEntries was also added. This is already supported in most major browsers so it would be a nice feature.

**Comment by tyuip6** [comment] 2019-06-26 22:22
Looks like 8.1 just entered RC phase, which just means bug fixes until release, I believe. So no TS 3.5. 😭

**Comment by fr0** [comment] 2019-07-10 23:11
What is the usual lag time between TypeScript releases and Angular support? Is this delay normal?

**Comment by blogcraft** [comment] 2019-07-24 17:03
Angular 8 has become too slow, maybe in some part, it is related to typescripts 3.4 and its regression problems? [see 'Type-checking speed-ups' section](https://devblogs.microsoft.com/typescript/announcing-typescript-3-5/)

Upgrading to 3.5 is a MUST.

**Comment by blogcraft** [comment] 2019-07-24 19:46
Any idea when will this be merged? It seems the commit is pending various checks.

**Comment by AndrewKushnir** [comment] 2019-07-31 18:00
fixed in 8.2.0 see #31615

**Closed by AndrewKushnir** 2019-07-31 18:00 UTC
Labels: comp: misc, type: feature

**Comment by blogcraft** [comment] 2019-07-31 18:20
Package "@angular-devkit/build-angular" has an incompatible peer dependency to "typescript" (requires ">=3.1 < 3.5", would install "3.5.3")

**Comment by blogcraft** [comment] 2019-07-31 18:25
Nevermind, it now works.

**Comment by blogcraft** [comment] 2019-07-31 19:42
ngxs/store#1195
