### ISSUE TITLE
[docs]: roadmap "try out inject" link is broken

### ISSUE THREAD

**Issue by praveeno** [angular/angular#52560] opened 2023-11-07 02:51 UTC
### Describe the problem that you experienced

under [roadmap](https://angular.dev/roadmap#explore-modern-angular) "Try out Inject" link is broken 

reference code [reference/roadmap.md#L25](https://github.com/angular/angular/blob/897f014785578d87bc655ea6ae9e113653960f50/adev/src/content/reference/roadmap.md?plain=1#L25)

### Enter the URL of the topic with the problem

https://angular.dev/roadmap#completed-projects

### Describe the actions that led you to experience the problem

click on "Try out Inject" link under https://angular.dev/roadmap#explore-modern-angular

**Comment by atscott** [comment] 2023-11-07 02:55
Duplicate of https://github.com/angular/angular/issues/52539

**Closed by atscott** 2023-11-07 02:55 UTC

**Comment by praveeno** [comment] 2023-11-07 02:59
Thanks, was not aware, issue already reported,
https://github.com/angular/angular/issues/52549 can also be taken in same PR
