### ISSUE TITLE
ERROR in TypeError: Cannot read property 'flags' of undefined

### ISSUE THREAD

**Issue by phonegap100** [angular/angular#36999] opened 2020-05-08 09:46 UTC
```
npm run start
```

ERROR in TypeError: Cannot read property 'flags' of undefined

```
ERROR in TypeError: Cannot read property 'flags' of undefined
    at resolveAlias (D:\ionic\angulardemo05\node_modules\_typescript@3.8.3@types
cript\lib\typescript.js:36513:37)
    at checkAliasSymbol (D:\ionic\angulardemo05\node_modules\_typescript@3.8.3@t
ypescript\lib\typescript.js:64502:26)
    at checkImportBinding (D:\ionic\angulardemo05\node_modules\_typescript@3.8.3
@typescript\lib\typescript.js:64534:13)
    at checkImportDeclaration (D:\ionic\angulardemo05\node_modules\_typescript@3
.8.3@typescript\lib\typescript.js:64552:29)
    at checkSourceElementWorker (D:\ionic\angulardemo05\node_modules\_typescript
@3.8.3@typescript\lib\typescript.js:64961:28)
    at checkSourceElement (D:\ionic\angulardemo05\node_modules\_typescript@3.8.3
@typescript\lib\typescript.js:64800:17)
    at Object.forEach (D:\ionic\angulardemo05\node_modules\_typescript@3.8.3@typ
escript\lib\typescript.js:317:30)
    at checkSourceFileWorker (D:\ionic\angulardemo05\node_modules\_typescript@3.
8.3@typescript\lib\typescript.js:65123:20)
    at checkSourceFile (D:\ionic\angulardemo05\node_modules\_typescript@3.8.3@ty
```

**ng --version**

```
Angular CLI: 9.1.4
Node: 12.13.1
OS: win32 x64

Angular:
...
Ivy Workspace:

Package                      Version
------------------------------------------
@angular-devkit/architect    0.901.4
@angular-devkit/core         9.1.4
@angular-devkit/schematics   9.1.4
@schematics/angular          9.1.4
@schematics/update           0.901.4
rxjs                         6.5.4

```

**Comment by thetric** [comment] 2020-05-08 09:59
Looks like a duplicate of https://github.com/angular/angular-cli/issues/17665

**Comment by petebacondarwin** [comment] 2020-05-08 10:03
Duplicate of #36993

**Closed by petebacondarwin** 2020-05-08 10:03 UTC
