### ISSUE TITLE
Add possiblilty to ask router for the current route. 

### ISSUE THREAD

**Issue by choeller** [angular/angular#5335] opened 2015-11-17 12:58 UTC
At the moment it is only possible to get the current `path` via the `Location.path()`method. When working with the "Routing DSL" it would be way more useful to check if a route is active via this DSL also. E.g. I want to do something like this

```
<li [class.active]="isActive('Dashboard')">
       <a [router-link]="['/Dashboard']" class="link">Dashboard</a>
</li>
```

But to be able to implement "isActive" I need the `name`of the current route. There are also cases where it would be useful to access the routeData of the current Route. At the moment it is only possible to access this information within the routed component, but not via the "Router" class

**Comment by cghislai** [comment] 2015-11-17 16:48
The router normally set the router-link-active class on active router links.
You can also check the Router.isActive method in the documentation.

**Comment by choeller** [comment] 2015-11-17 16:58
@cghislai the  router-link-active class is set on the link - I need the information in the surrounding <li> Router.isActive needs a Instruction as input, and I don't see an easy way to get the Instruction for a Route name.

**Comment by evanplaice** [comment] 2015-12-29 21:22
This is what I use

```javascript
<li [class.active]="isActive('/Dashboard')">
       <a [router-link]="['/Dashboard']" class="link">Dashboard</a>
</li>
```

This adds the 'active' class to the active link and removes it from any others.
```javascript
isActive (path) {
    return this.location.path().indexOf(path) > -1;
}
```

**Comment by oliverjanik** [comment] 2016-01-08 06:02
This extremely common scenario needs to be addressed. This a glaring omission. router-link-active class is an insufficient solution.

**Comment by miraage** [comment] 2016-01-08 18:40
It's pretty common to detect current route by name.
Also, `OnActivate` interface did not worked for me when I wanted to keep up to date last instruction.

**Comment by brandonroberts** [comment] 2016-01-08 18:51
in the meantime, if you want the current route instruction, you can subscribe to the router for URL updates and convert that into an instruction.

```js
import {Injectable} from 'angular2/core';
import {Router, Instruction} from 'angular2/router';

@Injectable()
export class RouterState {
  _current: Instruction;
  
  constructor(public router: Router, location: Location) {
    // subscribe to router url updates
    router.subscribe((url) => {
      // convert the current url into an instruction
      this._getInstruction(url);
    });
  }
  
  private _getInstruction(url) {
    this.router.recognize(url).then((ins) => {
      if (ins) {
        // Store the current route instruction
        this._current = ins;
      }
    });
  }
  
  current() {
    // return current instruction
    return this._current;
  }
}
```

**Comment by oliverjanik** [comment] 2016-01-09 00:46
Needs to be as easy as http://angular-ui.github.io/ui-router/site/#/api/ui.router.state.directive:ui-sref-active

**Comment by brandonroberts** [comment] 2016-01-09 00:51
@oliverjanik Agreed.

**Comment by miraage** [comment] 2016-01-09 09:49
@oliverjanik :+1:

**Comment by curlyfro** [comment] 2016-02-18 14:46
+1

**Comment by ekarlso** [comment] 2016-02-18 15:10
+1

Endre Karlson
18. feb. 2016 3.46 p.m. skrev "curlyfro" <notifications@github.com>:

**Comment by oliverjanik** [comment] 2016-02-18 23:04
Another suggestion. Many times I have sibling routes like this:

/cars
/cars/:id
/cars/new

Even though they're sibling by definition, logically the /:id route and /new route are children of the /cars route. I'd like an `isActive` that takes this into considerations.

Note: The reason I have routes like this is because this is a design limitation of the router.

**Comment by petebacondarwin** [comment] 2016-02-29 10:17
@choeller - your use case should be achievable right now with:


```ts
class MyComponent {
  constructor(public router: Router) {
  }
  isActive(childRouteName: string) {
    var instruction = router.generate([childRouteName]);
    return router.isRouteActive(instruction);
  }
}
```

The point is that the router that you get injected into your component is not the root level Router but a ChildRouter. Calling `generate(linkParams)` on such a router will assume that the `linkParams` are relative.

**Comment by petebacondarwin** [comment] 2016-02-29 10:19
@oliverjanik can you explain what you mean by the design limitation of the router. I would imagine setting up the following components in your scenario:

```ts
class CarsListComponent {}
class CarsDetailComponnet {}
class CarsNewComponent {}

@RouteConfig([
  {path: '/', component: CarsList},
  {path: '/new', component: CarsNew},
  {path: '/:id', component: CarsDetail}
])
class CarsComponent {
}
```

**Comment by oliverjanik** [comment] 2016-02-29 12:16
@petebacondarwin With your suggested setup you require 1 unnecessary router-outlet in CarsComponent template, which in turn makes CarsComponent completely unnecessary except to satisfy the router. Correct?

**Comment by petebacondarwin** [comment] 2016-02-29 12:28
I'm not sure I agree that the `Cars` component is completely unnecessary.

From a reusability point of view I see the `Cars` component as a **feature** which contains a bunch of related views. Without this, if I wanted to move that feature elsewhere in my app (or to another app), I would have to replicate the detailed route configuration for that feature in each place it appears.

I would expect that there is some commonality between these components, such as DI providers and directives that can be held in this feature component, and would have to be replicated in each of the child components otherwise.

While you can argue that the extra outlet is an overhead, it is minimal, both in terms of performance and verbosity: `template: '<router-outlet></router-outlet>`.

**Comment by oliverjanik** [comment] 2016-02-29 12:43
I understand your point but angular 2 suffers heavily from second system syndrome and this yet another manifestation. Most of the time I need my simple use case. I have yet to move a "feature" component somewhere to a different location. How often do you think that happens? Navigation and visual hierarchy is usually decided quite early in project development. With nested routes e.g. a/1/b/2/c/3 this effect compounds and you get 3 extra outlets. While I haven't measured the performance, this not good.

Sorry for the thread hijack.

**Comment by petebacondarwin** [comment] 2016-02-29 12:54
So @oliverjanik what exactly do you want to happen? If you do not want to use the component hierarchy to define the breadcrumb hierarchy then you are back to using the URL. The current URL is available to you via a subscription on the `rootRouter`, if I remember correctly. So you should be able to take that URL and parse it your self to identify the breadcrumbs.

**Comment by oliverjanik** [comment] 2016-02-29 14:00
The core of the problem is how router is designed. This worked quite well in UI Router using abstract routes.

**Comment by petebacondarwin** [comment] 2016-02-29 14:02
So what you are really saying is that you would like to have Abstract Routes?

**Comment by alexgoldstone** [comment] 2016-03-07 21:52
@petebacondarwin Regarding your suggestion [here](https://github.com/angular/angular/issues/5335#issuecomment-190140559), can you please advise how this should be handled for Angular 1.5 using the new router?

I am using version 0.2.0 of the router and found I had to inject $rootRouter and now this always outputs true:

```
var instruction = $rootRouter.generate(['App/Testing']);
console.log($rootRouter.isRouteActive(instruction));
```

**Comment by petebacondarwin** [comment] 2016-03-07 22:24
@alexgoldstone - you don't need to inject `$rootRouter` if you are inside a routed component. Instead, you can bind to the `$router` attribute on the component. For instance if you create your component using the 1.5 helper you can do:

```
mod.component('myComp', {
  template: '...'.
  bindings: { $router: '<' },
  controller: MyComponent
});
```

Check out the guide for this... https://docs.angularjs.org/guide/component-router

Can you give me more context for your problem?
What is the current route when you are generating the `['App/Testing']` route?

**Comment by alexgoldstone** [comment] 2016-03-08 00:17
@petebacondarwin Thank you, your answer was extremely helpful as I was not aware that any official documentation had been released (it hadn't last time I checked) so I did not realise I could bind to the `$router` attribute.

My use-case is simply that I want to identify the current route from the parent component to do something like:
```
<li ng-class="{ 'is-active': $ctrl.routeIsActive('Analytics') }"><a ng-link="['Analytics']">
```
I would have still expected the router to provide an isActive function but at least this makes it very easy to create.

Trying to bring my code inline with the new documentation it looks like I cannot bind to the `$router` attribute from the root (app) component and still have to inject `$rootRouter`.  Is that intentional? Binding to `$router` from child components seems to work as described.

**Comment by oliverjanik** [comment] 2016-03-09 06:41
Can you also please expose the name of the route on the ComponentInstruction?

Frequently I have multiple routes pointing to the same component, however, sometimes I need to know  which route was hit.

**Comment by petebacondarwin** [comment] 2016-03-09 09:14
@alexgoldstone - this is expected behaviour since the root component is instantiated manually by you in the top level HTML template (i.e. index.html).

@oliverjanik - exposing the name seems like a reasonably request can you create a separate issue to track that feature?

Closing this as the originally requested feature is now merged into master.

**Closed by petebacondarwin** 2016-03-09 09:14 UTC
Labels: comp: router, effort2: medium (day), P3: important, type: feature

**Comment by tatsujb** [comment] 2018-02-15 13:36
@evanplaice dude freakin a! put this on a github gist it's fuking genious!
