### ISSUE TITLE
Bad Filename/Path in HTTP-Tutorial

### ISSUE THREAD

**Issue by sddang** [angular/angular#11169] opened 2016-08-30 19:22 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Some code does not show due to bad filename/path.

**Expected/desired behavior**
Example code shown

**Reproduction of the problem**
Go to https://angular.io/docs/ts/latest/tutorial/toh-pt6.html

**What is the expected behavior?**
Shown code
![Uploading Screen Shot 2016-08-30 at 2.15.21 PM.png…]()

**Please tell us about your environment:**
Chrome 52.0.2743.116 (64 bit)

**Comment by ericmartinezr** [comment] 2016-08-30 19:27
https://github.com/angular/angular/issues/11127

**Comment by pkozlowski-opensource** [comment] 2016-08-30 20:12
Closing as a duplicate of https://github.com/angular/angular.io/issues/2213. Thnx so much @ericmartinezr !

**Closed by pkozlowski-opensource** 2016-08-30 20:12 UTC
