### ISSUE TITLE
docs(aio): Public members left off of API class docs

### ISSUE THREAD

**Issue by jonesetc** [angular/angular#17669] opened 2017-06-21 20:20 UTC
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[ ] Bug report 
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
API docs for classes seem to be stripping out useful public members, leading to poor documentation and difficulty understanding. convertPrivateClassesToInterfaces

## Expected behavior
API documentation for classes should show all public members and their types.

## Minimal reproduction of the problem with instructions
First look at the documentation for the class [ActivatedRouteSnapshot](https://angular.io/api/router/ActivatedRouteSnapshot), specifically the [Interface](https://angular.io/api/router/ActivatedRouteSnapshot#interface-overview) and [Members](https://angular.io/api/router/ActivatedRouteSnapshot#members) sections. Notice that there is no mention of a `data` member. Now look at the [How To Use](https://angular.io/api/router/ActivatedRouteSnapshot#how-to-use) section. See that there is use of a `data` member that is not mentioned anywhere on the page.

Now look at the code for [ActivatedRouteSnapshot](https://github.com/angular/angular/blob/bebedfed24d6fbfa492e97f071e1d1b41e411280/packages/router/src/router_state.ts#L215-L275). Notice that the list of members and the interface definition from the documentation is matched perfectly with the declared [methods](https://github.com/angular/angular/blob/bebedfed24d6fbfa492e97f071e1d1b41e411280/packages/router/src/router_state.ts#L252-L274). Now look at the constructor and the list of [public injected members](https://github.com/angular/angular/blob/bebedfed24d6fbfa492e97f071e1d1b41e411280/packages/router/src/router_state.ts#L230-L245) includes `data` and is in no way represented in the API documentation.

I believe that this is because of the doc generation use of [convertPrivateClassesToInterfaces](https://github.com/angular/dgeni-packages/blob/ad2da44d859d9505704afb6d93bc51a39c50265e/typescript/services/convertPrivateClassesToInterfaces.js), which appears to be totally [stripping off the constructor](https://github.com/angular/dgeni-packages/blob/ad2da44d859d9505704afb6d93bc51a39c50265e/typescript/services/convertPrivateClassesToInterfaces.js#L12) and all useful documentation that it may provide.

## What is the motivation / use case for changing the behavior?
This makes the documentation substantially less useful, as useful, public members are just being dropped. The only way that I learned about the `data` member is by stumbling into a random blog post about how to access resolver data in a component and then going into the source to figure out what it really is.

## Please tell us about your environment

Note, that this is just about documentation, but the version of the docs at time of reporting is:
<pre><code>
Angular version: 4.2.3

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX 
- Platform: 

Others:

</code></pre>

**Comment by petebacondarwin** [comment] 2017-06-21 21:04
Good spot @jonesetc - I am not sure if the stripping of the constructorDoc is actually to blame because the members of the class/interface will already have been extracted at that point.
I suspect that the issue is actually that we are never extracting members that are defined via the constructor params...
I'll look into it as part of a big refactor of the typescript dgeni-package that I am working on.

**Comment by jonesetc** [comment] 2017-06-21 21:58
Thanks @petebacondarwin, I was just speculating as my only understanding of the doc generation has been the hour long spiral I went into making sure that I wasn't crazy and that things were missing. Appreciate the speedy feedback and hope it goes smoothly.

**Comment by petebacondarwin** [comment] 2017-07-03 12:57
This is fixed by #17857

**Closed** 2017-07-11 10:44 UTC
Labels: comp: aio, type: bug
