### ISSUE TITLE
Create type definition for template context

### ISSUE THREAD

**Issue by Akxe** [angular/angular#35852] opened 2020-03-04 09:47 UTC
# 🚀 feature request

### Relevant Package
@angular/core

### Description
One type that is known, but specified to the user only in [documentation](https://angular.io/api/common/NgTemplateOutlet#description) is the template context.

> Using the key $implicit in the context object will set its value as default.

It is quite unsettling having a variable in component whose type is missing.

### Describe the solution you'd like
The obvious solution is to have a type definition:

```
export interface TemplateContext {
  /** Here can be the explanation that `$implicit` is the default value */
  $implicit: any;
  [key: string]: any;
}
```
or,
```
export type ImplicitSymbol = Symbol('TemplateImplicitValue');
export interface TemplateContext {
  /** Here can be the explanation that `$implicit` is the default value */
  [ImplicitSymbol]: any;
  [key: string]: any;
}
```

Another benefit of that would be, that all objects that are of type `TemplateContext` can then be replaced during angular upgrades if needed.

### Describe alternatives you've considered
You can just define yourself.

**Comment by pkozlowski-opensource** [comment] 2020-03-04 10:55
This sounds very much as a duplicate of #28731 (or at least strongly related)

**Comment by Akxe** [comment] 2020-03-06 12:22
@pkozlowski-opensource Definitely strongly related. Yet this is doable now without any conflicts. The template generic issue (#28731) have no foreseen solution for now.

**Comment by alxhub** [comment] 2021-07-17 01:26
I _think_ this is solved by Ivy's template type-checker and the ability to define a custom template context type for a structural directive. Please feel free to open a new request if not.

**Closed by alxhub** 2021-07-17 01:26 UTC
Labels: P4, comp: core, core: ng-template and *microsyntax, feature, insufficient votes, votes required
