### ISSUE TITLE
RC Component Router - Routed component is outside <router-outlet>

### ISSUE THREAD

**Issue by nareshbhatia** [angular/angular#8529] opened 2016-05-07 23:12 UTC
According to the [latest documentation](https://angular.io/docs/ts/latest/guide/router.html#!#router-outlet):

> the router (...) displays the `HeroListComponent` in a `RouterOutlet` that we've placed in the host view's HTML.
```html
<!-- Routed views go here -->
<router-outlet></router-outlet>
```

I would interpret this to result in a DOM structure like this:

```html
<router-outlet>
    <hero-list></hero-list>
</router-outlet>
```

However in reality the component is being placed *after* the `<router-outlet>`:

```html
<router-outlet></router-outlet>
<hero-list></hero-list>
```

This appears counter-intuitive - by definition an "outlet" is where the output is produced. Is this a bug? If not, what is the thinking behind this design?

P.S. This issue makes it cumbersome to layout components elegantly. Normally I size the outlet to occupy the entire window minus the headers/footers etc. This frees the imbedded component from any layout decisions - it simply occupies the full space of the container. If components are produced outside the outlet that leaks layout decisions to the components themselves.

**Comment by bennylut** [comment] 2016-05-08 13:15
This behavior exists in the beta versions as well and I believe it is an intended behavior (not sure why either), a simple workaround is to build your own router outlet that wrappers the native router outlet (or just wrap it inside a div and style that div)

**Comment by CaptainCodeman** [comment] 2016-05-08 13:29
The router outlet is more of a placeholder for where the routed component will be injected into the DOM / rendered.

i.e. it becomes a sibling next to it, it is never placed inside it.

The original reason for this behavior was to enable animation of elements between views during which time both source and destination would be "alive" https://github.com/angular/angular/issues/4679#issuecomment-148868935 which was demo'd at ng-conf 2015 (at 8:45 mark):

https://youtu.be/R0OrxxJNcjU?list=PLOETEcp3DkCoNnlhE-7fovYvqwVPrRiY7&t=529

There was no demo of this at this year's ng-conf so I don't know if it is still planned to make an appearance.

**Comment by nareshbhatia** [comment] 2016-05-08 14:56
Thanks @bennylut and @CaptainCodeman - definitely helpful. Reading https://github.com/angular/angular/issues/4679, it seems that I am not the only one confused by the name. I think if the [latest documentation](https://angular.io/docs/ts/latest/guide/router.html#!#router-outlet) can clarify this point it will alleviate much of the confusion. I will leave this issue open for the docs team to take some action.

**Comment by zoechi** [comment] 2016-07-18 08:17
docs issues should be reported in the https://github.com/angular/angular.io repository

**Comment by codefoster** [comment] 2016-08-02 22:02
@nareshbhatia, keep in mind that your embedded component can use the :host { ... } style rule to style its container. I used to use trickery to style the thing that my component was getting rendered in until I figured that one out.

**Closed** 2016-10-04 22:47 UTC
Labels: comp: router

**Comment by chenyingyin** [comment] 2016-12-01 04:00
![default](https://cloud.githubusercontent.com/assets/24284270/20781447/b59fb484-b7bd-11e6-80ad-c204da6321c7.png)
