### ISSUE TITLE
ngUpgrade: No provider for [ServiceName] when AngularJS module is loaded dynamically

### ISSUE THREAD

**Issue by KirillMetrik** [angular/angular#17581] opened 2017-06-17 06:55 UTC
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[x] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
I am having an AngularJS application and trying to upgrade it to Angular. Did everything as described in the upgrade in official docs:
<pre><code>
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { UpgradeModule } from '@angular/upgrade/static';
import { HeroService } from "./HeroService";

// We bootstrap our Angular1 app through Angular2
@NgModule({
    imports: [
        BrowserModule,
        UpgradeModule
    ],
    providers: [HeroService]
})
export class AppModule
{
    constructor(private upgrade: UpgradeModule)
    {
    }

    ngDoBootstrap()
    {
        this.upgrade.bootstrap(document.body, ["main-ng1-module"]);
    }
}
</code></pre>

"main-ng1-module" is declared as standard AngularJS module and when I inject my ng2 HeroService into controllers in "main-ng1-module" everything works just fine (I use <code>downgradeInjectable</code>).
Plus to this I have another AngularJS module:
<pre><code>
angular.module("second-ng1-module", [])
    .factory("heroService", downgradeInjectable(HeroService));
</code></pre>
The difference here is that "second-ng1-module" is loaded dynamically via [ocLazyLoad](https://oclazyload.readme.io/), so the module is not available from beginning when application is bootstrapped.
The weird behavior here is that the <code>HeroService</code> is not available within "second-ng1-module". Though when I add it statically:  <code>this.upgrade.bootstrap(document.body, ["main-ng1-module", "second-ng1-module"]);</code> the service gets injected without any problems.

As I noticed Angular calls <code>NgModuleInjector.get</code> method which calls <code>AppModuleInjector.getInternal</code>. This method is generated and should return an instance of <code>HeroService</code>. But in my case (when angular module is loaded dynamically via ocLazyLoad) it just returned <code>_UNDEFINED</code>

## Expected behavior
I would expect that injector would return <code>HeroService</code> regardless of whether angular module is loaded dynamically or statically. Or maybe there is a way to add AngularJS modules to the Angular app on-the-fly?

## Please tell us about your environment

<pre><code>
Angular version: 4.0.0
Browser: Chrome (desktop) version 58.0.3029.110
</code></pre>

**Comment by gkalpak** [comment] 2017-07-04 13:08
It is really difficult to investigate without a concrete reproduction. It could be anything from a typo to bad configuration or an ocLazyLoad/ngUpgrade/AngularJS/Angular issue.

Could you create a runnable demo (e.g. using Plnkr) or a minimal project that we can check out and see the problem in action?

**Comment by gkalpak** [comment] 2017-12-15 12:54
Closing due to lack of reproduction. Possibly related to #17490.

**Closed by gkalpak** 2017-12-15 12:54 UTC
Labels: comp: upgrade/static

**Comment by AminRahimi** [comment] 2018-07-08 11:42
same issue on material dialog with component that have angularjs upgraded component
ERROR Error: StaticInjectorError(AppModule)[$scope]: 
  StaticInjectorError(Platform: core)[$scope]: 
    NullInjectorError: No provider for $scope!

**Comment by gkalpak** [comment] 2018-07-09 08:05
This happens because the dialog contents are "compiled" before being attached to the DOM, so they can't access the `$scope` injectable defined on the parent downgraded component.

As a workaround, you can define a `'$scope'` provider for these cases, like this:

```ts
@NgModule({
  ...
  providers: [{provide: '$scope', useExisting: '$rootScope'}],
}
export class AppModule { ... }
```

It might actually make sense to make this part of `ngUpgrade` itself 🤔

**Comment by AminRahimi** [comment] 2018-07-09 18:55
thanks for this solution 
and i find another solution from angular material team
https://github.com/angular/material2/issues/12105#issuecomment-403572564

>Paul Gschwendtner
This is because you didn't provide a viewContainerRef and therefore an injector that includes the upgraded component isn't being used.
```
constructor(public dialog: MatDialog, private viewContainerRef: ViewContainerRef) { }

onOpenModalClick() {
  ....,
  viewContainerRef: this.viewContainerRef,
});
```

**Comment by uazure** [comment] 2018-10-05 08:12
> This happens because the dialog contents are "compiled" before being attached to the DOM, so they can't access the `$scope` injectable defined on the parent downgraded component.

Thanks for pointing this out. I managed to solve the issue by the following:

```
class WrapperComponent extends UpgradeComponent {
    constructor(_elRef: ElementRef, _injector: Injector) {
        const rootScope = _injector.get('$rootScope');
        const scope = rootScope.$new();
        const injector = Injector.create([
            {
                provide: '$scope',
                useValue: scope
            }
        ], _injector);

        super('ng1Component`, _elRef, injector);
    }
}
```

**Comment by gkalpak** [comment] 2018-10-05 09:10
@uazure: While this work around might work for a specific usecase, keep in mind that this will mess up the Scope hierarchy tree, which may have unexpected side effects (e.g. Scopes not being destroyed correctly (aka memory leaks), Scope events not propagating correctly, bindings not working as expected, etc).

**Comment by lentschi** [comment] 2019-04-15 15:23
@gkalpak Thanks, both solution - yours and @uazure 's - work.
However, there *does* seem to be a problem with bindings using *either* solution.

Any inputs coming from angular1 seem to be ignored. Do you have an idea on how to fix that?

**Comment by gkalpak** [comment] 2019-04-15 17:25
@lentschi, can you provide a reproduction (e.g. a StackBlitz project) I can use to investigate what might be wrong?
(You can use [this][1] as a starting point, if it helps.)

[1]: https://stackblitz.com/edit/ngupgradestatic-playground

**Comment by lentschi** [comment] 2019-04-16 10:02
@gkalpak I'm sorry - I was mislead by a problem in `ngx-bootstrap` not assigning the passed initialState to the `@Input` bindings (for anyone else having trouble with this - s. my workaround in https://github.com/valor-software/ngx-bootstrap/issues/2354#issuecomment-483593779 )

So your original injection trick works fine in all cases and this had nothing to do with it - sorry again!
