### ISSUE TITLE
Angular 7 - Object extension method crashses ngModel

### ISSUE THREAD

**Issue by orirefael** [angular/angular#27052] opened 2018-11-11 15:56 UTC
# 🐞 bug report

### Affected Package
Most likely: @angular/core
Less likely: @types/angular

### Is this a regression?
Didn't try in previous versions. 

### Description

Creating an extension method for Object type, conflicts somehow with NgModel and yields 
"Uncaught (in promise): Error: @Output <my extension method name> not initialized in 'NgModel'."
It seems as when a directive is formed, it looks for all outputs and expects them to be an observable.
Since the extension method extends Object, its by definition part of the parent of Directive.
Directive thinks its some sort of an output field, and crashes.

## 🔬 Minimal Reproduction

I can't seem to add any npms in blitz so ill give a short, detailed explanation:

perquisites (im not sure if it is a must). 
0. npm install --save @types/angular

1. create global.d.ts file.

export {};

declare global {
    interface Object {
        isEmpty(this: any): boolean;
    }
}

2. create objExt.ts file

Object.prototype.isEmpty = function (this: any) : boolean {
    return this == null || this == undefined;
};

3. in main.ts import objExt
4. create a component which is using [(ngModel)] inside of its .html page
5. run, crash.

## 🔥 Exception or Error
<pre><code>
ERROR Error: Uncaught (in promise): Error: @Output isEmpty not initialized in 'NgModel'.
Error: @Output isEmpty not initialized in 'NgModel'.
    at createDirectiveInstance (core.js:18560)
    at createViewNodes (core.js:19776)
    at callViewAction (core.js:20092)
    at execComponentViewsAction (core.js:20011)
    at createViewNodes (core.js:19804)
    at createRootView (core.js:19690)
    at callWithDebugContext (core.js:20722)
    at Object.debugCreateRootView [as createRootView] (core.js:20208)
    at ComponentFactory_.push../node_modules/@angular/core/fesm5/core.js.ComponentFactory_.create (core.js:18029)
    at ComponentFactoryBoundToModule.push../node_modules/@angular/core/fesm5/core.js.ComponentFactoryBoundToModule.create (core.js:7812)
    at createDirectiveInstance (core.js:18560)
    at createViewNodes (core.js:19776)
    at callViewAction (core.js:20092)
    at execComponentViewsAction (core.js:20011)
    at createViewNodes (core.js:19804)
    at createRootView (core.js:19690)
    at callWithDebugContext (core.js:20722)
    at Object.debugCreateRootView [as createRootView] (core.js:20208)
    at ComponentFactory_.push../node_modules/@angular/core/fesm5/core.js.ComponentFactory_.create (core.js:18029)
    at ComponentFactoryBoundToModule.push../node_modules/@angular/core/fesm5/core.js.ComponentFactoryBoundToModule.create (core.js:7812)
    at resolvePromise (zone.js:814)
    at resolvePromise (zone.js:771)
    at zone.js:873
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:421)
    at Object.onInvokeTask (core.js:14134)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:420)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:188)
    at drainMicroTaskQueue (zone.js:595)
defaultErrorLogger @ core.js:12584

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.10.4
@angular-devkit/build-angular     0.10.4
@angular-devkit/build-optimizer   0.10.4
@angular-devkit/build-webpack     0.10.4
@angular-devkit/core              7.0.4
@angular-devkit/schematics        7.0.4
@angular/cli                      7.0.4
@ngtools/webpack                  7.0.4
@schematics/angular               7.0.4
@schematics/update                0.10.4
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.19.1

</code></pre>

**Anything else relevant?**

When you enter in debug mode to where to exception occurs, it tries to handle Output of directives and it seems it asks if its an observable, since my extension methods are not observable, it throws the error.

First time submitting a bug here, be gentle. if you need more information, ill provide.

**Comment by trotyl** [comment] 2018-11-11 16:42
Duplicate of https://github.com/angular/angular/issues/26318

**Comment by AndrewKushnir** [comment] 2018-11-12 04:33
@orirefael as @trotyl mentioned in the comment above, this issue looks like a duplicate of #26318. Please refer to the mentioned thread to find additional information. Thank you.

**Closed by AndrewKushnir** 2018-11-12 04:33 UTC
