### ISSUE TITLE
Support for the HTML5 File API?

### ISSUE THREAD

**Issue by oleersoy** [angular/angular#27106] opened 2018-11-15 00:50 UTC
# 🚀 feature request
Mapping of the input of type file elements `change` event to the `valueChanges` emitter.
```
<input #file name='file' id='file' type='file' [formControl]='loadButton'/>
```

```
this.loadButton.valueChanges
    .pipe(untilDestroyed(this))
    .subscribe(event => {
      //Ideally this would log the same event that native element's `change()` event emitter emits:
      console.dir(event);
    });
}
```

### Relevant Package
@angular/reactive-forms 

More here:
https://stackoverflow.com/questions/53310485/subscribing-to-input-type-file-changes-with-formcontrol

**Comment by oleersoy** [comment] 2018-11-15 00:51
Looks like we currently have to hack around it like this:
https://academind.com/learn/angular/snippets/angular-image-upload-made-easy/

**Comment by pkozlowski-opensource** [comment] 2018-11-15 07:16
Duplicate of #7341

**Closed by pkozlowski-opensource** 2018-11-15 07:16 UTC
