### ISSUE TITLE
Component lifecycle events as Observable

### ISSUE THREAD

**Issue by bobvanderlinden** [angular/angular#18876] opened 2017-08-25 10:28 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Many components will use some kind of asynchronous way to retrieve data. Whether that is from HTTP, local storage, etc. These are modelled in Angular as Observables. The resulting Observable is sometimes used to show a loading indicator overlay or pop up a dialog.

These Observables need to be cancelled when `ngOnDestroy` is called to avoid problems such as showing a pop up after navigating away from the component. To do this, every component needs something like the following:

```
subscription: Subscription;
ngOnInit() {
   this.subscription = retrieveData().subscribe(data => {
     ... (show a popup)
   });
}

ngOnDestroy() {
  this.subscription.unsubscribe();
}
```

It would be nice if the lifecycle events were in some way composable. Modelling them as an Observable would help:

```
constructor(lifecycleCtrl: LifecycleController) {
  const lifecycle = lifecycleCtrl(this);
  lifecycle.whenInit()
    .flatMap(() => retrieveData())
    .takeUntil(lifecycle.whenDestroy())
    .subscribe();
}
```

The same can be used for `ViewInit`:

```
@ViewChild('myelement') myelement: ElementRef;

constructor(...) {
  const lifecycle = lifecycleCtrl(this);
  lifecycle.whenInit()
    .concatMap(() => retrieveData())
    .concatMap(() => lifecycle.whenViewInit())
    .takeUntil(lifecycle.whenDestroy())
    .subscribe(() => {
      ... (do something with myelement)
    });
}
```

Because it is now also composable, this functionality can be wrapped inside a function:

```
  lifecycle.afterInitBeforeDestroy(() =>
    retrieveData()
  ).subscribe();
```

This might also make it easier/safer to access ViewChild ElementRefs's nativeElement. For instance to update a canvas every second:

```
@ViewChild('mycanvas') mycanvas: ElementRef;

lifecycle.watchNativeElement(() => this.mycanvas)
  .switchMap(nativeElement =>
    Observable.interval(1000)
      .do(() => {
        ... (draw on canvas)
      })
  )
  .subscribe();
```

Here `watchNativeElement` will wait for a emit from `whenViewInit` (or `whenViewChecked` and check whether the nativeElement has changed) and output the nativeElement until `whenDestroy` emitted next.

It should make it easier to developers to handle resources/lifecycle correctly. Destruction of Observables can be handled in the same place as initializing of them. This makes it easier to know whether lifecycle has been handled correctly.

**Comment by bobvanderlinden** [comment] 2017-08-25 10:32
I've tried to implement such behavior in a separate controller (LifecycleController like the examples above), but I cannot get lifecycle hooks from outside the component itself. I'd like to avoid implementing `ngOn*`/`ngAfter*` hooks in every component that needs lifecycle handling. It would be nice if such functionality worked a bit like `ChangeDetectorRef`.

**Comment by Toxicable** [comment] 2017-08-25 19:02
Duplicate https://github.com/angular/angular/issues/10185

**Comment by chuckjaz** [comment] 2017-10-27 18:22
Thanks for reporting this issue. However this issue is a duplicate of an existing issue #10185. Please subscribe to that issue for future updates.

**Closed by chuckjaz** 2017-10-27 18:22 UTC
Labels: comp: core & compiler
