### ISSUE TITLE
Press Kit: All images on the pages are not shown

### ISSUE THREAD

**Issue by pawelfras** [angular/angular#54501] opened 2024-02-19 11:46 UTC
### Describe the problem that you experienced

All images on the Press Kit page are not shown.

### Enter the URL of the topic with the problem

https://angular.dev/press-kit

### Add a screenshot if that helps illustrate the problem

Example:
![image](https://github.com/angular/angular/assets/28891782/9fc2c9b1-d524-490d-88c5-62a749a741ec)
It seems to be related to the invalid image source:
![image](https://github.com/angular/angular/assets/28891782/a54ef105-27a4-412f-9cac-9872b1e714b9)

All other images on this page have the same issue.

**Comment by JoostK** [comment] 2024-02-19 12:01
Thanks for the report, closing as duplicate of #54472

**Closed by JoostK** 2024-02-19 12:01 UTC
