### ISSUE TITLE
Error message when omitting a host component from TestBed.configureTestingModule isn't helpful

### ISSUE THREAD

**Issue by voithos** [angular/angular#17477] opened 2017-06-13 18:26 UTC
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

Not sure if this is a duplicate of #15506, but that one didn't seem like it was test-specific.

**Minimal reproduction of the problem with instructions**
While unit testing Angular code, if one forgets to place a test component under the `declarations` of a `TestBed.configureTestingModule()` call, and later attempts to instantiate the component via `TestBed.createComponent()`, the resulting error message (at runtime) isn't very helpful.

**Current behavior**
The message currently says `Error: Illegal state: Could not load the summary for directive FooTestComponent`.

**Expected behavior**
The message should say something clearer (like `Cannot find FooTestComponent, did you forget to declare it in the testing module?`).

**Please tell us about your environment:**

* **Angular version:** HEAD

**Comment by robert197** [comment] 2017-06-29 16:11
Thank you! Your reproduction instruction helped me to fix my "issue" ;)

**Comment by anandchakru** [comment] 2017-08-04 04:32
ah! saved me too.. tnq

**Comment by SakiiR** [comment] 2017-08-22 08:23
Same here, ty :)

**Comment by SakiiR** [comment] 2017-08-22 08:26
Were using something like: 

```typescript
describe('AutocompleteComponent', () => {

  beforeEach(async(() => {
    TestBed.configureTestingModule({
      declarations: [
        TestAutocompleteWrapperComponent // <- here
      ],
      providers: [
      ],
      imports: [
        AppModule,
        RouterModule.forRoot(AppRoutes),
        MdChipsModule,
        MdIconModule,
        FormsModule,
        MdInputModule,
      ]
    });
  }));
```

with a wrapper to test my autocomplete component:

```typescript
class TestAutocompleteWrapperComponent {

  @ViewChild('myac')
  myAutocomplete: AutocompleteComponent;

  items = [
    new AutocompleteItem('Salt', 1),
    new AutocompleteItem('Sugar', 2),
    new AutocompleteItem('Alien', 3),
    new AutocompleteItem('Bread', 4),
  ];

  onChange(result) {

  }

}
```

Le problem was that the test module was not declaring the wrapper

**Comment by SrAxi** [comment] 2018-01-08 13:21
I'm facing the same issue!

My test:

```
export function main() {
  describe('LrCategoriesComponent', () => {
    let fixture: ComponentFixture<LrCategoriesComponent>;
    let component: LrCategoriesComponent;
    let de: DebugElement;
    let glService: GeneralLedgeService;
    let lrService: LrService;
    let spy: jasmine.Spy;

    beforeEach(async(() => {
      TestBed.configureTestingModule({
        declarations: [
          LrComponent,
          LrMappingsComponent,
          LrCategoriesComponent,
        ],
        imports: [
          CommonModule,
          SharedModule,
          LrRoutingModule,
        ],
        providers: [
          LrService,
          { provide: GeneralLedgeService, useClass: MockGeneralLedgeService },
          CompleterService,
        ]
      }).compileComponents().then(() => {
        // initialization
        fixture = TestBed.createComponent(LrCategoriesComponent);
        component = fixture.componentInstance;
        de = fixture.debugElement;

        // Service getters
        glService = de.injector.get(GeneralLedgeService);
        lrService = de.injector.get(LrService);
      });
    }));

    // beforeEach(() => {
    //   // initialization
    //   fixture = TestBed.createComponent(LrCategoriesComponent);
    //   component = fixture.componentInstance;
    //   de = fixture.debugElement;
    //
    //   // Service getters
    //   glService = de.injector.get(GeneralLedgeService);
    //   lrService = de.injector.get(LrService);
    // });

    it('should create LrCategoriesComponent', (() => {
      expect(component).toBeDefined();
    }));
  });
}
```

And my error message:

![image](https://user-images.githubusercontent.com/12787963/34672479-da6023fe-f47e-11e7-9f2e-444bd97bf3b2.png)

Also, this error is breaking other random tests that were working well.

**Comment by sulhome** [comment] 2019-03-31 23:51
+1

**Comment by Menion93** [comment] 2019-04-17 14:32
+1

**Comment by smasala** [comment] 2019-07-11 08:59
This is not incorrect usage: `app/welcome/welcome.component.spec.ts (class-only setup)` -> [](https://angular.io/guide/testing#component-test-basics).

You're just not allowed to `compileComponents()` on the `TestBed` and you get the component fixture by using `TestBed.get(MyComponentClass)` instead.

**Comment by tapaz1** [comment] 2019-10-17 19:17
For those who are still having issues with this. 

I read a separate github issue that discussed changes the Angular team made to the BeforeEach callback function.

To fix the issue I simple moved my TestBed.configureTestingModule({}).compileComponents() and the fixture.createComponent() setup into a BeforeAll and the issue was gone. Give it a shot. Hope this helps.

**Comment by johncrim** [comment] 2020-06-14 18:39
I've wasted a number of hours due to this poor error message - I thought it was a problem due to jest, or spectator (which usually declares the component under test for you), and it was only through coincidence that I realized that a failure to declare the component (in a test) was the root cause.

It seems that there's some tribal knowledge that this error message is (usually) due to a missing declaration, but it should be improved so the tribal knowledge isn't necessary.

**Comment by AndrewKushnir** [comment] 2020-11-17 19:36
Hi, the error message in the initial issue description refers to ViewEngine compiler. In Ivy, the compiler and TestBed were reworked. I'm closing this ticket and feel free to create a new one if the problem still exists with Ivy compiler and TestBed. Thank you.

**Closed by AndrewKushnir** 2020-11-17 19:36 UTC
Labels: comp: testing, feature, freq3: high, hotlist: google
