### ISSUE TITLE
`ng-content` projection not rendered when inside `@if`

### ISSUE THREAD

**Issue by vlio20** [angular/angular#56962] opened 2024-07-12 11:01 UTC
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

In the attached demo you will find an example where ng-content is not beind renderd.
I have this generic form component:
```
<div class="content">
  <ng-content select="[content]"></ng-content>
</div>

<div class="messages">
  <ng-content select="[hint]"></ng-content>
  <ng-content select="[error]"></ng-content>
</div>
```

and the following usage:
```
<form-field>
  <div content>
    <label>Label:</label>
    <input type="text" />
  </div>

  <div hint>this is renderd</div>


  @for(msg of messages; track msg; let first = $first)  {
    @if (first) {
      <div error>First - error message: {{msg}}</div>
    }
    <!-- <ng-container error></ng-container> -->
  }
</form-field>
```

Messages is an array of strings: `['error1', 'error2']`

with that example the `First - error message:` is not being rendered. When uncommeting the `ng-container error` the item is being rendered.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-oiyhpt?file=src%2Fapp%2Fapp.component.html

### Please provide the exception or error you saw

```true
There is no exception - the behaviour described above.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
/ \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 18.1.0
Node: 18.20.3
Package Manager: npm 10.2.3
OS: linux x64

Angular: 18.1.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, material, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1801.0
@angular-devkit/build-angular   18.1.0
@angular-devkit/core            18.1.0
@angular-devkit/schematics      18.1.0
@schematics/angular             18.1.0
rxjs                            7.8.1
typescript                      5.4.5
zone.js                         0.14.7
```

### Anything else?

Nope

**Comment by JeanMeche** [comment] 2024-07-12 11:06
This is basically #54035 and exhibits a fundamental limitation of the content projection system.

**Comment by vlio20** [comment] 2024-07-12 11:12
Maybe it is but notice that if I am using `*ngIf` it is woring as expected (in [this](https://github.com/angular/angular/issues/54035#issuecomment-1994198225) comment it is stated that same happened with `*ngIf`).
```
<form-field>
  <div content>
    <label>Label:</label>
    <input type="text" />
  </div>

  <div hint>this is renderd</div>

  @for(msg of messages; track msg; let first = $first) {
  <!-- @if (first) { -->
  <div *ngIf="first" error>First - error message: {{ msg }}</div>
  <!-- } -->
  <!-- <ng-container error></ng-container> -->
  }
</form-field>
```

Are there any workarounds?

**Comment by JoostK** [comment] 2024-07-12 11:31
> When uncommeting the ng-container error the item is being rendered.

This isn't the case in my testing, the presence of this container is irrelevant to the shown behavior.


Closing as a duplicate of #54035. The workaround is to use:

```html
  @for(msg of messages; track msg; let first = $first)  {
    <ng-container ngProjectAs="[error]">
    @if (first) {
        <div error>First - error message: {{msg}}</div>
    }
    </ng-container> 
  }
```

**Closed by JoostK** 2024-07-12 11:31 UTC

**Comment by vlio20** [comment] 2024-07-12 11:33
yea... this is not supper elegant... it would be better to have the workaround within the `form-field` component
