### ISSUE TITLE
Unable to pass property to root level component

### ISSUE THREAD

**Issue by thelgevold** [angular/angular#4921] opened 2015-10-26 22:35 UTC
I have noticed that it's not possible to pass data to the root level component using properties.

I was hoping to pass data to the root level component as a way to initialize it from external data sources.
One simple example would be a JavaScript object defined in index.html - outside of Angular.
Ex:
```
<demo-app [testing]="[1,2,3]"></demo-app>
```

Assume the above root level component in my index.html page. I would like to pass an array to the testing property as a way to initialize the main component. 

This doesn't seem to work and I find this to be an unfortunate limitation since the alternative is to define a global variable that I can access from inside the component. Instead we should be able to just "ferry" in the data via properties.

**Comment by alexpods** [comment] 2015-10-27 08:53
@thelgevold I think this is related to #1858

**Comment by pkozlowski-opensource** [comment] 2015-12-29 11:44
Closing as a duplicate of #1858

**Closed by pkozlowski-opensource** 2015-12-29 11:44 UTC
