### ISSUE TITLE
JIT compiler unavailable error with blank screen ( after updated from Angular 15.1.0 -> 16.2.14)

### ISSUE THREAD

**Issue by DT-Yogi** [angular/angular#57048] opened 2024-07-18 18:34 UTC
### Command

serve

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

15.1.0

### Description

I encountered an issue when upgrading Angular from version 15 to 16. Despite checking various forums, I couldn't find a solution. I hope someone here might have faced a similar issue and could provide some advice.

The problem is related to the JIT Compiler being unavailable. I suspect this is due to a library or package still relying on the View Engine, while Angular 16 requires Ivy. The error message only states "JIT Compiler unavailable," leaving me with a blank screen and no further information to debug or fix the issue.

I've found a couple of potential workarounds, but they don't seem to follow best practices:

1. Setting `aot` to `false` in `angular.json`.
2. Importing `@angular/compiler` in the `main.ts` file.

Both approaches appear to enable the use of both Ivy and the View Compiler, but I'm looking for a solution that avoids these methods. Any suggestions on how to identify the root cause or provide more meaningful console errors would be greatly appreciated.

![image](https://github.com/user-attachments/assets/c447ee9c-e02a-4d9b-9dac-979e2707cd5c)

### Minimal Reproduction

 below is the package.json  excluding script section
 
 {
  "name": "app",
  "version": "XXXXX",
  "author": "XXXXX",
  "license": "UNLICENSED",
  "homepage": "https://ionicframework.com/",
  "engines": {
    "node": "18.15.0"
  },
  "scripts": {
   ...
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "16.2.12",
    "@angular/cdk": "^16.2.14",
    "@angular/common": "16.2.12",
    "@angular/core": "16.2.12",
    "@angular/forms": "16.2.12",
    "@angular/material": "^16.2.14",
    "@angular/platform-browser": "16.2.12",
    "@angular/platform-browser-dynamic": "16.2.12",
    "@angular/router": "16.2.12",
    "@apollo/client": "^3.0.0",
    "@awesome-cordova-plugins/app-center-analytics": "^6.4.0",
    "@awesome-cordova-plugins/app-center-crashes": "^6.4.0",
    "@awesome-cordova-plugins/app-center-shared": "^6.4.0",
    "@awesome-cordova-plugins/core": "^6.4.0",
    "@awesome-cordova-plugins/splash-screen": "^6.4.0",
    "@awesome-cordova-plugins/status-bar": "^6.4.0",
    "@braze/web-sdk": "^5.0.0",
    "@capacitor/android": "^5.7.5",
    "@capacitor/app": "^5.0.7",
    "@capacitor/core": "^5.7.5",
    "@capacitor/filesystem": "^5.2.1",
    "@capacitor/haptics": "^5.0.7",
    "@capacitor/ios": "^5.7.5",
    "@capacitor/keyboard": "^5.0.8",
    "@capacitor/push-notifications": "^5.1.1",
    "@capacitor/share": "^5.0.7",
    "@capacitor/status-bar": "^5.0.7",
    "@datadog/browser-logs": "^4.37.0",
    "@datadog/browser-rum": "^4.37.0",
    "@fullstory/browser": "^1.6.2",
    "@googlemaps/js-api-loader": "^1.16.6",
    "@ionic-enterprise/auth": "^3.10.4",
    "@ionic-enterprise/identity-vault": "~5.11.1",
    "@ionic-enterprise/inappbrowser": "^5.0.4",
    "@ionic-enterprise/secure-storage": "^3.0.0",
    "@ionic/angular": "^7.2.0",
    "@ionic/storage": "^3.0.4",
    "@ionic/storage-angular": "^4.0.0",
    "@segment/analytics-next": "^1.51.7",
    "@types/ws": "^8.5.4",
    "apollo-angular": "^5.0.0",
    "braze-cordova-sdk": "github:braze-inc/braze-cordova-sdk#master",
    "cordova-plugin-appcenter-analytics": "^0.5.1",
    "cordova-plugin-appcenter-crashes": "^0.5.1",
    "cordova-plugin-appcenter-shared": "^0.5.1",
    "cordova-plugin-ionic": "^5.5.1",
    "express": "^4.17.1",
    "fast-xml-parser": "^4.3.2",
    "graphql": "^15.0.0",
    "karma-coverage": "^2.2.1",
    "launchdarkly-js-client-sdk": "^3.1.3",
    "libphonenumber-js": "^1.9.42",
    "lodash": "^4.17.21",
    "luxon": "^3.4.3",
    "pdfjs-dist": "^4.3.136",
    "rxjs": "^7.5.0",
    "swiper": "^10.0.4",
    "tslib": "^2.0.0",
    "ua-parser-js": "^0.7.31",
    "zone.js": "~0.13.3"
  },
  "devDependencies": {
    "@angular-builders/custom-webpack": "^16.0.1",
    "@angular-devkit/build-angular": "~16.2.14",
    "@angular-eslint/builder": "^16.1.1",
    "@angular-eslint/eslint-plugin": "^16.1.1",
    "@angular-eslint/eslint-plugin-template": "^16.1.1",
    "@angular-eslint/schematics": "^16.1.1",
    "@angular-eslint/template-parser": "^16.1.1",
    "@angular/cli": "16.2.14",
    "@angular/compiler": "16.2.12",
    "@angular/compiler-cli": "16.2.12",
    "@angular/language-service": "16.2.12",
    "@capacitor/cli": "^5.7.5",
    "@ionic/angular-toolkit": "^11.0.1",
    "@ionic/cli": "^7.1.1",
    "@microsoft/applicationinsights-web": "~2.5.10",
    "@types/google.maps": "^3.55.5",
    "@types/jasmine": "~3.6.0",
    "@types/jasminewd2": "~2.0.3",
    "@types/lodash": "^4.14.176",
    "@types/lodash-es": "^4.17.5",
    "@types/luxon": "^3.3.3",
    "@types/node": "~18.15.0",
    "@types/offscreencanvas": "^2019.7.0",
    "@types/ua-parser-js": "^0.7.36",
    "@typescript-eslint/eslint-plugin": "5.26.0",
    "@typescript-eslint/parser": "5.59.5",
    "cordova-res": "^0.15.4",
    "cross-env": "^7.0.3",
    "eslint": "^8.0.0",
    "eslint-plugin-ban": "^1.6.0",
    "eslint-plugin-import": "^2.26.0",
    "eslint-plugin-jsdoc": "^39.2.1",
    "eslint-plugin-prefer-arrow": "^1.2.3",
    "eslint-plugin-unused-imports": "^2.0.0",
    "htmlhint": "^1.1.4",
    "husky": "^7.0.4",
    "jasmine-core": "~3.8.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~6.3.9",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "karma-junit-reporter": "^2.0.1",
    "karma-spec-reporter": "^0.0.32",
    "lint-staged": "^11.1.2",
    "ngzip": "~1.1.3",
    "prettier": "2.2.1",
    "pretty-quick": "3.1.0",
    "run-script-os": "^1.1.6",
    "ts-node": "~8.3.0",
    "tsconfig-paths": "3.8.0",
    "typescript": "^4.9.5",
    "webpack-bundle-analyzer": "^4.10.1"
  },
  "description": "An Ionic project"
}

### Exception or Error

```text
Error: JIT compiler unavailable
    at Po (core.mjs:5311:15)
    at Function.get (core.mjs:10410:38)
    at ln (core.mjs:2393:28)
    at Kf (core.mjs:9546:16)
    at hm (core.mjs:9530:25)
    at Gs.processProvider (core.mjs:9408:24)
    at core.mjs:9216:59
    at Gu (core.mjs:9601:13)
    at Gu (core.mjs:9598:13)
    at new Gs (core.mjs:9216:9)
```

### Your Environment

```text
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 16.2.14
Node: 18.15.0
Package Manager: npm 9.5.0
OS: darwin arm64

Angular: 16.2.12
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1602.14
@angular-devkit/build-angular   16.2.14
@angular-devkit/core            16.2.14
@angular-devkit/schematics      16.2.14
@angular/cdk                    16.2.14
@angular/cli                    16.2.14
@angular/material               16.2.14
@schematics/angular             16.2.14
rxjs                            7.8.1
typescript                      4.9.5
zone.js                         0.13.3
```

**Comment by JeanMeche** [comment] 2024-07-18 18:40
Hi, this is likely a dupe of #43415. 

This is not VE/Ivy related. 

The error means that the compiler module for some reason, isn't loaded. This could be related to the usage of the custom webpack config but without a working repro it is not possible to investigate.

**Comment by DT-Yogi** [comment] 2024-07-18 18:49
Thank you @JeanMeche  for your prompt response. I have looked into the other ticket, and I don't have a webpack.config.js file in my repo.

Could you please provide more guidance on what information would be useful for further debugging? For example, should I be looking for specific configurations or files? Additionally, would importing @angular/compiler in the main.ts file be a viable solution, or is there another recommended approach to ensure the compiler module is loaded correctly?

Any additional tips or best practices for identifying the root cause of this issue would be greatly appreciated.

**Comment by JeanMeche** [comment] 2024-07-18 18:53
You have `@angular-builders/custom-webpack` in your dependencies, you should look why/where it is used, as this not a builder supported by the team. 

Yes, importing the compiler package can fix your issue. But it would be better to understand why it is needed in the first place (either in your code or by 1 of your dependencies).

**Comment by DT-Yogi** [comment] 2024-07-18 18:55
Also, is there a way to identify which components rely on the JIT compiler in my project?.

**Comment by Anjanalachu** [comment] 2024-07-18 18:58
I have the same issue

**Comment by Anjanalachu** [comment] 2024-07-18 19:01
same package.json
 my tsconfig.app.json is  {
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc/app",
    "module": "es2020",
    "types": ["node"]
  },
  "exclude": [
    "src/test.ts",
    "**/*.spec.ts"
  ],
  "angularCompilerOptions": {
    "Ivy": false
  }
}
and my  tsconfig,json is 
{
  "compileOnSave": false,
  "angularCompilerOptions": {
    "disableTypeScriptVersionCheck": true,
  },
  "compilerOptions": {
    "baseUrl": "./",
    "module": "es2020",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es2015",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [

      "es2017",
      "dom"
    ],
    "skipLibCheck": true,
    "paths": {
      "jszip": ["node_modules/jszip/dist/jszip.min.js"]
    }
  }
}

**Comment by DT-Yogi** [comment] 2024-07-18 19:13
@JeanMeche the only reason we brought in @angular-builders/custom-webpack is to prevents OneTrust from modifying the scripts, which breaks the app.  and below is the only place in entire repo we use it.  and some changes in angular.json file as shown below that's it

import { TargetOptions } from '@angular-builders/custom-webpack';

export default (targetOptions: TargetOptions, indexHtml: string) => {
```
  // Add the 'data-ot-ignore' attribute to the Angular scripts injected by webpack.
  // This prevents OneTrust from modifying the scripts, which breaks the app.

```  
  indexHtml = indexHtml.replace('src="runtime', 'data-ot-ignore src="runtime');
  indexHtml = indexHtml.replace('src="polyfills', 'data-ot-ignore src="polyfills');
  indexHtml = indexHtml.replace('src="styles', 'data-ot-ignore src="styles');
  indexHtml = indexHtml.replace('src="vendor', 'data-ot-ignore src="vendor');
  indexHtml = indexHtml.replace('src="main', 'data-ot-ignore src="main');

  return indexHtml;
};

<img width="790" alt="image" src="https://github.com/user-attachments/assets/0a1748fa-8b8f-4a99-8230-15f3c1dc331d">

**Comment by DT-Yogi** [comment] 2024-07-18 19:38
@JeanMeche  Just FYI: I also tried to remove the above dependency ("@angular-builders/custom-webpack": "^16.0.1",) form package.json for custom webpack and  I still see the same error.

**Comment by Anjanalachu** [comment] 2024-07-22 04:50
@DT-Yogi Did you solve the error

**Comment by DT-Yogi** [comment] 2024-07-22 22:10
@Anjanalachu  Yes, one quick & dirty way to get a little more context could be to temporarily modify a couple of @angular/core files in your node_modules folder. Basically, you can find any instances of the error message, and add a little more context to that message.
 
Find (in any *.mjs file):
`throw new Error('JIT compiler unavailable');`
Replace with:
`throw new Error(`JIT compilation failed for ${request.kind}`, request.type);`
 
When you've identified it, you can obviously just undo that change.

**Closed** 2024-07-23 14:33 UTC
