### ISSUE TITLE
@angular/service-worker  -push - "This site has been updated in the background"

### ISSUE THREAD

**Issue by ranbuch** [angular/angular#23037] opened 2018-03-28 09:24 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
When notification is arriving to the device the text (body) is always "This site has been updated in the background"

## Expected behavior
I would expect the notification to show my custom message

notification JSON:
```javascript
{
  "data" : {
    "notification_type" : 4,
    "artist_user_id" : 1,
    "notes" : "ROARRRRRRRRRRRRRR!!!!!"
  },
  "body" : "Announcement",
  "title" : "Announcement",
  "icon" : "https://www.creators3d.com/assets/icon-128x128.png",
  "vibrate" : [ 100 ]
}
```

According to [this post](https://stackoverflow.com/questions/31108699/chrome-push-notification-this-site-has-been-updated-in-the-background) this issue might be related to `@angular/service-worker/ngsw-worker.js` file.

Also, when pressing on the notification on my Android device nothing happens and I don't get any notification on my Windows 10 PC although I've allowed Notifications (may not be related to this issue).

## Environment

<pre><code>
Angular version: 5.6.0

Browser:
- [x] Chrome (desktop) version XX
- [x] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.9.4  
- Platform: Window 10 

Others:

</code></pre>

**Comment by gkalpak** [comment] 2018-03-28 10:25
@ranbuch, can you post a minimal reproduction?

**Comment by ranbuch** [comment] 2018-04-01 16:20
In row `1848` inside the function ```onPush(msg) ```
you have the next condition:
```javascript
if (!msg.data) {
    return;
}
```
While ```msg.data ``` is falsy ```msg.json() ``` does return all of the data that my server have sent.

**Comment by ranbuch** [comment] 2018-04-01 16:35
BTW I believe my last comment is related to the fact that I don't get any notification on my desktop at all.
On my mobile device debugging is more difficult but I'll try to do so and will update.

**Comment by ranbuch** [comment] 2018-04-02 07:27
On mobile devices this code:
```javascript
if (!msg.data) {
    return;
}
```
doesn't hit return.

**Comment by ranbuch** [comment] 2018-04-03 09:01
I've solved the `This site has been updated in the background` issue by wrapping my JSON object that I've posted above with `notification` object like this:
```javascript
notification: {
  {
    "data" : {
      "notification_type" : 4,
      "artist_user_id" : 1,
      "notes" : "ROARRRRRRRRRRRRRR!!!!!"
    },
    "body" : "Announcement",
    "title" : "Announcement",
    "icon" : "https://www.creators3d.com/assets/icon-128x128.png",
    "vibrate" : [ 100 ]
  }
}
```
Also added the `title` field witch is mandatory.
After adding those changes this statement:
```javascript
if (!msg.data) {
    return;
}
```
doesn't hit return on Desktop no more (witch stroke me as a weird behavior).
I guess I can close this issue now.

Thank you.

**Comment by gkalpak** [comment] 2018-04-03 10:56
By looking at the code, it seems that the parsed [PushMessageData][1] of the `PushEvent` should contain a `notification` property (which in turn should have a `title` property) for the notification to be displayed:

https://github.com/angular/angular/blob/55c9fb298f8b7ad41cd49618b96a11587a5083da/packages/service-worker/worker/src/driver.ts#L275

This seems arbitrary. Is it a common convention or an `@angular/service-worker` thing, @alxhub?
We should document how to use push notifications with `@angular/service-worker` anyway (tracked in #22627).

##
<sub>Closing the issue, since you were able to get your notifications to work, @ranbuch.</sub>

[1]: https://developer.mozilla.org/en-US/docs/Web/API/PushMessageData

**Closed by gkalpak** 2018-04-03 10:56 UTC
Labels: comp: service-worker, type: bug/fix
