### ISSUE TITLE
Unable to hydrate nested anchor elements

### ISSUE THREAD

**Issue by HyperLife1119** [angular/angular#55441] opened 2024-04-20 10:03 UTC
### Which @angular/* package(s) are the source of the bug?

platform-browser

### Is this a regression?

Yes

### Description

When an anchor element is inside another anchor element, the hydration fails.

```ts
@Component({
  selector: 'app-root',
  standalone: true,
  template: `
    <a>
      outer
      <a>inner</a>
    </a>
  `
})
export class AppComponent { }
```

Its rendering also does not match the reality; the two anchor elements should be parent-child, not brother.

![image](https://github.com/angular/angular/assets/41798664/9a265319-9b0d-4d7d-a17b-83915a36570f)

### Please provide a link to a minimal reproduction of the bug

https://github.com/HyperLife1119/ng-ssr

### Please provide the exception or error you saw

```true
Error: NG0500: During hydration Angular expected <a> but the node was not found.

Angular expected this DOM:

<a>
  …
  #text( outer )
  <a>…</a>  <-- AT THIS LOCATION
  …
</a>

Note: attributes are only displayed to better represent the DOM but have no effect on hydration mismatches.

To fix this problem:
  * check the "_AppComponent" component for hydration-related issues
  * check to see if your template has valid HTML structure
  * or skip hydration by adding the `ngSkipHydration` attribute to its host node in a template

 Find more at https://angular.io/errors/NG0500
    at validateMatchingNode (core.mjs:13482:15)
    at locateOrCreateElementNodeImpl (core.mjs:23095:18)
    at Module.ɵɵelementStart (core.mjs:22993:20)
    at AppComponent_Template (app.component.ts:10:7)
    at executeTemplate (core.mjs:11268:9)
    at renderView (core.mjs:12470:13)
    at renderComponent (core.mjs:12416:5)
    at renderChildComponents (core.mjs:12518:9)
    at renderView (core.mjs:12498:13)
    at ComponentFactory.create (core.mjs:15859:17)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.3.5
Node: 18.19.0
Package Manager: npm 10.2.3
OS: darwin arm64

Angular: 17.3.5
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router, ssr

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1703.5
@angular-devkit/build-angular   17.3.5
@angular-devkit/core            17.3.5
@angular-devkit/schematics      17.3.5
@schematics/angular             17.3.5
rxjs                            7.8.1
typescript                      5.4.5
zone.js                         0.14.4
```

**Comment by JeanMeche** [comment] 2024-04-20 10:37
Nested anchor tags in not a valid HTML, this is pretty much expected.

**Comment by HyperLife1119** [comment] 2024-04-20 10:44
Thank you very much, I didn't realize that. :)

**Comment by JeanMeche** [comment] 2024-04-20 10:46
I'll close this as a dupe of #54943. It would be great if we provided some template validity checking, as there are several cases where this breaks hydration.

**Closed by JeanMeche** 2024-04-20 10:46 UTC
