### ISSUE TITLE
keyvalue pipe doesn't preserve a Map's sorted order

### ISSUE THREAD

**Issue by ravishivt** [angular/angular#31420] opened 2019-07-04 17:47 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/common

### Is this a regression?

 No

### Description

 One of the reasons a developer uses a <code>Map</code> over an <code>Object</code> is to have Object-like features with sorted keys.  When passing  a <code>Map</code> to <code>*ngFor</code> with the <code>keyvalue</code> pipe, the map's sorted order is lost.<br/><br/>
The bug is that the <code>keyvalue</code> pipe uses the <code>defaultComparator</code> for Maps.  No sorting should be applied when <code>keyvalue</code> is passed a <code>Map</code>.

## 🔬 Minimal Reproduction

 https://stackblitz.com/edit/angular-keyvalue-pipe-map-order?file=src/app/app.component.ts

## 🌍  Your Environment

**Angular Version:**
<pre><code>
8.0.2
</code></pre>

**Comment by Manindrateja** [comment] 2019-07-06 10:51
@ravishivt 
[keyvalue pipe](https://angular.io/api/common/KeyValuePipe#description)
The equivalent object for map in your example { pizza: { cost: 20}, burger: { cost: 15 }, taco: { cost: 5}}; 
keyvalue pipe sorts by key output will burger , pizza and taco.

Please close this ticket.

**Comment by ravishivt** [comment] 2019-07-06 16:28
The point of this issue is that `keyvalue` pipe should not do any sorting when passed a `Map` as they "remember the original insertion order of the keys" unlike objects.  Please see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map.

**Comment by djleonskennedy** [comment] 2019-07-09 06:14
@radotzki Have you heard about **map** data structure before? 
Do not disgrace, close the ticket

**Comment by radotzki** [comment] 2019-07-09 06:51
> @radotzki Have you heard about **map** data structure before?
> Do not disgrace, close the ticket

I think you tagged the wrong person 😅

**Comment by ravishivt** [comment] 2019-07-09 17:21
@djleonskennedy I believe your comment was directed to me.  This whole issue pertains to the <code>Map</code> data structure.  I'm not sure what you meant by your comment or why you believe this issue should be closed.

**Comment by Drageaux** [comment] 2019-07-09 18:34
> @radotzki Have you heard about **map** data structure before?
> Do not disgrace, close the ticket

chad

**Comment by Drageaux** [comment] 2019-07-09 18:41
@ravishivt Agree with you. 

Although I don't think it's a bug if they've intended it that way, there should be an easy way to preserve the order. Why not leave it as is, then we can sort however we want right? Why apply the defaultComparator instead?

Say, my Map doesn't follow any sorting algorithm, and I want to keep the structure. There's NO way to revert back to that unsorted structure even with a custom comparatorFn

**Comment by ravishivt** [comment] 2019-07-09 19:32
@Drageaux thanks for chiming in here.  I thought I was being brigaded for a second.  😸 

Your custom sort is an interesting workaround.  I still believe though that the default behavior should be to not sort a <code>Map</code>.

> Although I don't think it's a bug if they've intended it that way, there should be an easy way to preserve the order. Why not leave it as is, then we can sort however we want right? Why apply the defaultComparator instead?

That's exactly my thought as well and my PR #31422 implements such functionality.  When a <code>Map</code> is passed with no custom <code>compareFn</code>, the <code>defaultComparator</code> is not applied.  But you still have the option to pass in a custom <code>compareFn</code> if you do want a custom sort applied to a <code>Map</code>.  So it's just adjusting the default behavior to no sort.

**Comment by mlc-mlapis** [comment] 2019-07-10 12:28
@ravishivt I agree with you, that when passing a `Map`, the default order should be taken from the map itself. Even milliseconds are counted to the whole picture, especially if you multiply it in some case x 10 or x 100 (when designing the app using this feature selectively).

**Comment by djleonskennedy** [comment] 2019-07-11 22:35
@radotzki yeap! sorry this was addressed to @ravishivt

**Comment by tabuckner** [comment] 2019-08-21 13:13
> @ravishivt Agree with you.
> 
> Although I don't think it's a bug if they've intended it that way, there should be an easy way to preserve the order. Why not leave it as is, then we can sort however we want right? Why apply the defaultComparator instead?
> 
> Say, my Map doesn't follow any sorting algorithm, and I want to keep the structure. There's not a way to revert back to that unsorted structure even with a custom comparatorFn
> 
> EDIT:
> 
> Actually I found a simple way to preserve the order
> 
> ```js
> // *.component.ts
> asIsOrder(a, b) {
>   return 1;
> }
> ```
> 
> ```
> 
> <div
>       *ngFor="
>         let someVal of someMap | keyvalue: asIsOrder;
>         let i = index
>       ">
> </div>
> ```
> 
> `return 1` because a is the element that gets passed in first, and 1 means it should come first in the array

This approach works for my use case as well. I agree that the `keyvalue` should preserve the map's sort order. In my case, it looked as though the pipe was parsing the keys as strings, and then using the default comparator for `array.sort()`.

This may not be 100% accurate, but the effect was very similar.

**Comment by tabuckner** [comment] 2019-09-11 20:53
> > @ravishivt Agree with you.
> > Although I don't think it's a bug if they've intended it that way, there should be an easy way to preserve the order. Why not leave it as is, then we can sort however we want right? Why apply the defaultComparator instead?
> > Say, my Map doesn't follow any sorting algorithm, and I want to keep the structure. There's not a way to revert back to that unsorted structure even with a custom comparatorFn
> > EDIT:
> > Actually I found a simple way to preserve the order
> > ```js
> > // *.component.ts
> > asIsOrder(a, b) {
> >   return 1;
> > }
> > ```
> > 
> > 
> > ```
> > 
> > <div
> >       *ngFor="
> >         let someVal of someMap | keyvalue: asIsOrder;
> >         let i = index
> >       ">
> > </div>
> > ```
> > 
> > 
> > `return 1` because a is the element that gets passed in first, and 1 means it should come first in the array
> 
> This approach works for my use case as well. I agree that the `keyvalue` should preserve the map's sort order. In my case, it looked as though the pipe was parsing the keys as strings, and then using the default comparator for `array.sort()`.
> 
> This may not be 100% accurate, but the effect was very similar.

Just to update the issue thread, this does not provide reliable results in all browsers. We ran into issues with Firefox rendering the order differently than Chrome. Ended up using a comparator function that leverages the `key` value in the `HashMap`. Which worked for a large majority of use cases:

```typescript
public numberedKeyOrder(a: KeyValue<string, any>, b: KeyValue<string, any>): number {
    const aStepId = parseInt(a.key, 10);
    const bStepId = parseInt(b.key, 10);
    return aStepId > bStepId ? 1 : (bStepId > aStepId ? -1 : 0);
  }
```

**Comment by RobertAKARobin** [comment] 2019-12-19 02:43
This has been driving me crazy. It seems like a very strange choice by the Angular team. Implementing this sorting would be *more* work than simply using one of the Map object's built-in iterators, so it's not an accident. Would love for this to be addressed.

**Comment by sqpeng** [comment] 2020-01-14 11:50
Maybe using the customized pipe can solve this problem.

**Comment by amitport** [comment] 2020-02-14 09:53
note that besides Map type, normal object entries traversal is standardized since es6 (https://2ality.com/2015/10/property-traversal-order-es6.html). There is no need to reinvent the wheel here. when iterating over objects in Angular template I'd expect the same behavior as in javascript.

(this kind of surprises is part of what makes the raw JS usage in react more appealing, please don't reinvent the core language)

**Comment by mlc-mlapis** [comment] 2020-02-14 10:39
@amitport Thanks for it. I understand that there is still some amount of ES5 clients, so it can take some time to change, but for ES6 `Map` and `Set` it certainly doesn't have the sense to re-sort already sorted. It has only negative performance effects.

**Comment by amitport** [comment] 2020-02-14 12:27
> @amitport Thanks for it. I understand that there is still some amount of ES5 clients, so it can take some time to change, but for ES6 `Map` and `Set` it certainly doesn't have the sense to re-sort already sorted. It has only negative performance effects.

I just want to note that I don't think this is a performance issue. The defined order is insertion/assignment order, not sorted order (This always true for map and set, a little more complex but deterministic in es6 objects, and mostly true but not standardized in older js implementations).
(Also makes sense specifically in UI templates when converting json-like objects to and you expect the order to be maintained)

The core problem is that it is different from normal JS iteration. This is surprising and tiring. It is an entries traversal, should just use 'forEach' for Map, 'Object.entries' for other objects and let typescript/corejs handle polyfills if somebody targets es5

**Comment by and-kisorec** [comment] 2020-03-05 15:44
@Drageaux Thank you so much ;)

**Comment by ericdrosas87** [comment] 2020-05-05 22:56
@Drageaux Thank you, this works for my use case - and for what's it worth I agree that the map order should be maintained.

**Comment by petebacondarwin** [comment] 2020-05-27 19:57
I think, it is not a bug, given that the docs even explicitly mention the order:

> The output array will be ordered by keys.
> By default the comparator will be by Unicode point value.
> You can optionally pass a compareFn if your keys are complex types.

See https://angular.io/api/common/KeyValuePipe#description

Marking as a feature.

I think it is a reasonable request that we should consider but it would be a breaking change for current users of the pipe. It is also worth noting that this can be easily worked around (if a bit annoying - sorry).

**Comment by amitport** [comment] 2020-05-28 03:48
@petebacondarwin it's only breaking if you choose to reimplement the keyvalue pipe. It is possible (and seems wiser IMO) to expose a new "entries pipe" and deprecate this keyvalue one.

**Comment by petebacondarwin** [comment] 2020-05-28 07:45
If you limit your pipe to only Maps then the keyvalue differ is almost trivial to implement.
See https://stackblitz.com/edit/ivy-v7uvuf?file=src%2Fapp%2Fkeyvalue.pipe.ts

I would argue that either we make the decision to do a breaking change in v11 or just leave people to implement their own pipe.

**Comment by amitport** [comment] 2020-05-28 09:55
IMHO, it's better to deprecate this without core replacement than to to leave as is.
JS order is the common use case. Re-ordering has a surprising effect on developers. Additionally, your implementation is not trivial, but even if it was, it shouldn't matter, where react and other template binding tools let people use common 'object.entries' angular insist of having a cognitive overhead. Which could (and should) be mitigated.

**Comment by petebacondarwin** [comment] 2020-05-28 13:14
Actually if you want a trivial JS aligned solution with zero Angular specific cognitive overload then just use the `entries()` method directly in the template:

```
<p *ngFor="let food of foods.entries()">
  {{food[0]}} (${{food[1].cost}})
</p>
```

This could not be any more straightforward for a JS developer and will even be more performant than a pipe since it does less processing.

Pipes can be faster than this sort of expression if they are "pure" but the `keyvalue` pipe is not pure, since it cannot guarantee that the internals of the object/map have not changed between change detection cycles.

I believe main motivation for the `keyvalue` pipe is that there were no methods (such as `keys()`, `values()` and `entries()` on plain JS objects.

Also the argument for sorting the entries by key goes back to the times when each JS engine might have a different approach to the order in which properties were iterated, so sorting provided a reliable deterministic order across browsers.

**Comment by MatthiasKunnen** [comment] 2020-05-28 14:15
> Actually if you want a trivial JS aligned solution with zero Angular specific cognitive overload then just use the entries() method directly in the template

**Don't use `.entries()` in template code.** 

Most likely you're going to cause ChangedAfterChecked errors as `.entries()` creates a new array every time the differ evaluates it.

I've created a stackblitz showcasing what happens if you do this: <https://stackblitz.com/edit/angular-map-entries-in-template>. Check the console.

**Comment by petebacondarwin** [comment] 2020-05-28 15:05
Gadzooks! I never knew that! Yes, that is not good.

**Comment by Mdelaf** [comment] 2020-08-10 02:34
It would be cool to have this change implemented. Iterating over a `Map` in the template should feel the same as doing it in the component, and this is not the case by now.

In the meantime I am using this pipe (only for `Map`) that works the same as `keyvalue` but without altering the order:
```typescript
import { Pipe, PipeTransform } from '@angular/core';


@Pipe({name: 'mapEntries'})
export class MapEntriesPipe implements PipeTransform {

  transform<K, V>(input: Map<K, V>): Array<any> {
    return Array.from(input).map(([key, value]) => ({ key, value }));
  }
}
```

Note that I used `Array<any>` instead of `Array<{ key: K; value: V; }>` because the [Angular Language Service extension](https://marketplace.visualstudio.com/items?itemName=Angular.ng-template) shows compilation error _"Expected operands to be of comparable types or any"_ when comparing `item.key === otherValueOfKType` in the template. :man_shrugging:

**Comment by s4m0r4m4** [comment] 2020-08-13 15:25
+1 to this - respecting Map entry ordering would be super useful.

**Comment by marcalj** [comment] 2020-12-14 13:13
Ended up using `.values()` as a stable check detection mechanism.

```html
<li *ngFor="let resultItem of aMap.values()">
    {{ resultItem | json }}
</li>
```

**Comment by marcalj** [comment] 2021-01-12 16:11
@Mdelaf I've fixed with the next code:

```typescript
import {Pipe, PipeTransform} from '@angular/core';
import {KeyValue} from '@angular/common';

@Pipe({
  name: 'mapEntries'
})
export class MapEntriesPipe implements PipeTransform {
  transform<K, V>(input: Map<K, V>): ReadonlyArray<KeyValue<K, V>> {
    return Array.from(input).map(([key, value]) => ({key, value}));
  }
}
```

**Comment by BurntCaramel** [comment] 2021-02-22 06:43
Inspired by the above sample here is a pipe that caches the result to make change detection happier (assumes the map won’t be changed).

```typescript
import { Pipe, PipeTransform } from '@angular/core';

// Holds a weak reference to its key (here a map), so if it is no longer referenced its value can be garbage collected.
const cache = new WeakMap<ReadonlyMap<any, any>, Array<{ key: any; value: any }>>();

@Pipe({ name: 'mapkeyvalue', pure: true })
export class MapKeyValuePipe implements PipeTransform {
  transform<K, V>(input: ReadonlyMap<K, V>): Iterable<{ key: K; value: V }> {
    const existing = cache.get(input);
    if (existing !== undefined) {
      return existing;
    }

    const iterable = Array.from(input, ([key, value]) => ({ key, value }));
    cache.set(input, iterable);
    return iterable;
  }
}
```

**Comment by petebacondarwin** [comment] 2021-09-15 19:53
The team's preferred solution here is to allow `compareFn` to be set to `null`, which indicates that there should be "no sort".

**Comment by petebacondarwin** [comment] 2021-09-16 09:03
Closing as #42490 better captures the issue and how it should be resolved.

**Closed by petebacondarwin** 2021-09-16 09:03 UTC
Labels: feature, comp: common, help wanted, under consideration
