### ISSUE TITLE
On navigate() router method ngOnInit of target component is not called

### ISSUE THREAD

**Issue by daviatorstorm** [angular/angular#22472] opened 2018-02-27 09:59 UTC
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
I making a redirect with this.router.navigate(['some', 'route']) ngOnInit is not called in navigated component. If I do this.router.navigateByUrl('/some/route')  everything works fine.

## Expected behavior
When doing this.router.navigate(['some', 'route']) ngOnInit in navigated component will fire.

## Environment

<pre><code>
Angular version: 5.2.5

Browser:
- [X ] Chrome (desktop) version 64.0.3282.186
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ X] Edge version 41.16299.248.0
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by mlc-mlapis** [comment] 2018-02-27 10:28
@daviatorstorm ... a simple reproduction demo of the problem on https://stackblitz.com is supposed.

**Comment by daviatorstorm** [comment] 2018-02-28 21:07
https://stackblitz.com/edit/angular-3pacxx?file=app%2Fmain.component.ts

**Comment by trotyl** [comment] 2018-03-01 02:11
Duplicate of #18254, #19731. Expected behavior.

**Comment by jasonaden** [comment] 2018-03-07 06:49
Closing based on the above from @trotyl. Specifically, take a look at the [comment here](https://github.com/angular/angular/issues/19731#issuecomment-336776711) which should resolve your issue.

**Closed by jasonaden** 2018-03-07 06:49 UTC
Labels: comp: router
