### ISSUE TITLE
Angular async pipe emitting rejected events of Rxjs filter 

### ISSUE THREAD

**Issue by shavipathania** [angular/angular#32044] opened 2019-08-07 17:21 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/core

### Is this a regression?

 No

### Description

- When using Angular async pipe with Rxjs filter pipe, even when Rxjs filter has rejected the event, angular async pipe still runs on it.
- Below in Stackblitz,
- Firstly type in the title input box, it will get previewed correctly
- Then type in the detail input box, the detail will get previewed correctly but the title will become blank.
- In the console window, you can see that title is not been logged when detail is being changed but the async pipe render title empty.

## 🔬 Minimal Reproduction

 https://stackblitz.com/edit/angular-q8srny

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 8.1.1
Node: 10.16.0
OS: linux x64
Angular: 8.1.1
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.801.1
@angular-devkit/build-angular      0.801.1
@angular-devkit/build-ng-packagr   0.801.1
@angular-devkit/build-optimizer    0.801.1
@angular-devkit/build-webpack      0.801.1
@angular-devkit/core               8.1.1
@angular-devkit/schematics         8.1.1
@angular/cdk                       8.0.2
@angular/fire                      5.2.1
@angular/material                  8.0.2
@ngtools/json-schema               1.1.0
@ngtools/webpack                   8.1.1
@schematics/angular                8.1.1
@schematics/update                 0.801.1
ng-packagr                         5.3.0
rxjs                               6.4.0
typescript                         3.4.5
webpack                            4.35.2
</code></pre>

**Comment by JoostK** [comment] 2019-08-07 18:02
Hi @shavipathania,

the problem you are experiencing is due to how change detection works. During change detection, every binding in the template is re-evaluated. In your case, `title$ | async` first evaluates `title$` by reading the property from the component instance. Because `title$` is defined using a getter, the getter is invoked, creating a new Observable while doing so. Then, the `async` pipe receives the newly created Observable, recognizes it to be different from the previous Observable it was subscribed to so it cancels the earlier subscription and resubscribes to the new Observable.

Because you're using a `ReplaySubject`, the latest event is replayed upon subscribing. Hence, the latest event determines if either `title$` or `detail$` emits, as one of them will have the `filter` operator passthrough the latest event.

You can solve the problem by ensuring that `title$` and `detail$` don't constantly change during change detection, by storing the Observable pipelines into a property. In your case, replacing the getter with simple property assignment does the trick, however this may not always be possible.

```typescript
export class CardOverviewExample {
  subject$ = new ReplaySubject(1);

  title: string;
  detail: string;

  ngOnInit() {
    this.title$.subscribe(console.log);
  }

  title$ = this.subject$.pipe(
    filter(event => event == ChangeEvent.TitleUpdated),
    map(event => this.title)
  );

  setTitle(title: string) {
    this.title = title;
    this.subject$.next(ChangeEvent.TitleUpdated);
  }

  detail$ = this.subject$.pipe(
    filter(event => event == ChangeEvent.DetailUpdated),
    map(event => this.detail)
  );

  setDetail(detail: string) {
    this.detail = detail;
    this.subject$.next(ChangeEvent.DetailUpdated);
  }
  
}
```

I am closing this issue as it's ultimately not a bug with Angular, just something to watch out for.

**Closed by JoostK** 2019-08-07 18:02 UTC

**Comment by shavipathania** [comment] 2019-08-07 18:23
Hi @JoostK 

Thanks for the detailed explanation.

You are absolutely right because of the new observer creating while calling getter. I don't know how I missed that. I think I just overlooked it as it was working fine in `console.log`

And, really thanks for your quick and detailed reply.

**Comment by konradekk** [comment] 2019-08-15 03:43
ps. remember to unsubscribe from the stream (most probably in `ngOnDestroy` to pair with `ngOnInit`) or youl encounter. new class of isuues! :p
