### ISSUE TITLE
formatNumber returns irregular whitespace characters for certain locales

### ISSUE THREAD

**Issue by AndrejB1** [angular/angular#38295] opened 2020-07-30 10:05 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/common

### Is this a regression?

 Not sure

### Description

 the `formatNumber` method, when used with French locale ('fr') will return strings with the wrong kind of space character as a thousand separator.

A string such as "1 000" will come out of `formatNumber` with a U+202F character instead of U+0020 as whitespace. This causes errors with libraries like jsPDF, where we have to replace the character with a regular space, or else the exported PDF file will be corrupted.

## 🔬 Minimal Reproduction

 https://stackblitz.com/edit/angular-ivy-zuba4m

## 🌍  Your Environment

**Angular Version:**

9.1.1

**Comment by JoostK** [comment] 2020-07-30 11:34
This seems like a duplicate of #37905. The localization data is coming from the CLDR project, see relevant issue links in #37905. As such, this is not currently actionable from our side, as Angular uses CLDR data as-is.

**Closed by JoostK** 2020-07-30 11:34 UTC
Labels: comp: i18n
