### ISSUE TITLE
HttpClient Interceptor custom arguments

### ISSUE THREAD

**Issue by pmilic021** [angular/angular#19379] opened 2017-09-25 13:07 UTC
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
At the moment, as far as I know, there is no way to send some arbitrary arguments to interceptors based on which it could alter its behaviour. I am currently sending my arbitrary params through HttpParams in options (and strip them inside of interceptor), but it would be nice to have some clean way of achieving the same.

## Expected behavior
Perhaps one more optional param in HttpClient's .get/.post/... that would contain object of custom arguments to be passed to interceptor.

## What is the motivation / use case for changing the behavior?
My specific use case is sending loadingName (used in covalent's *tdLoading) to interceptor that creates loading spinner before API request and removes it on .finally(). It would be nice to be able to achieve loading spinner control using interceptor.

## Environment

<pre><code>
Angular version: 4.4.3

</code></pre>

**Comment by trotyl** [comment] 2017-09-25 14:22
Duplicate of #18155.

**Closed** 2017-09-25 14:32 UTC
