### ISSUE TITLE
routerLink support of null/undefined v. 2

### ISSUE THREAD

**Issue by staeke** [angular/angular#14188] opened 2017-01-30 16:45 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Reopening https://github.com/angular/angular/issues/6971. I cannot reopen, so hence I'm making a new ticket.

Binding `routerLink` to null or empty array does not yield exception anymore, but yields a url to the current route rather than an empty href, which is surprising (and imo bad). 

**Expected behavior**
I would expect empty `routerLink` (i.e. null/undefined/empty array/array with only nulls and undefined) to not add an href attribute. It doesn't make sense to just pick a url (the current) for linking when a url cannot be produced.

* **Angular version:** 2.4.2

**Comment by DzmitryShylovich** [comment] 2017-01-30 16:47
> I think it would be convenient to allow routerLink to support a case where the binding resolves to null, empty array or undefined. In that case I'd expect an <a> tag to be created without a href attribute (**or **empty).

:)

**Comment by DzmitryShylovich** [comment] 2017-01-30 16:48
Duplicate of https://github.com/angular/angular/issues/13980

**Comment by pkozlowski-opensource** [comment] 2017-02-01 11:23
Closing as a duplicate of #13980

**Closed by pkozlowski-opensource** 2017-02-01 11:23 UTC
