### ISSUE TITLE
https://angular.io/guide/i18n download files are outdated

### ISSUE THREAD

**Issue by pacocom** [angular/angular#35524] opened 2020-02-18 12:16 UTC
# 📚 Docs or angular.io bug report

### Description

See the **i18n Example** for a simple example of an AOT-compiled app, translated into French.
When click in `i18n Example` download https://angular.io/generated/zips/i18n/i18n.zip but these are files with Angular 8 version.

### What's the affected URL?**
https://angular.io/guide/i18n

### Expected vs Actual Behavior**

Donwload files with Angular 9 version.

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by gkalpak** [comment] 2020-02-18 12:46
Thx for reporting, @pacocom!
Closing this as a duplicate of #35334 (follow that for updates).

**Closed by gkalpak** 2020-02-18 12:46 UTC
