### ISSUE TITLE
Link to "try out inject"  results in pagenotfound

### ISSUE THREAD

**Issue by kklocker** [angular/angular#53790] opened 2024-01-04 08:57 UTC
### Describe the problem that you experienced

click the "try out inject" link on https://angular.dev/roadmap, which links to https://angular.dev/di
![image](https://github.com/angular/angular/assets/25065744/87f6826d-ff62-4ea6-87b1-0a0fcb23171a)
Results in:
![image](https://github.com/angular/angular/assets/25065744/67409fc3-bded-4ae2-be23-06d4c11dc834)

### Enter the URL of the topic with the problem

https://angular.dev/roadmap

### Describe the actions that led you to experience the problem

Read the blog here -> clicked roadmap
https://blog.angular.io/angular-developer-survey-2023-86372317c95f

### If the problem is browser-specific, please specify the device, OS, browser, and version

```true
Microsoft Edge 120.0.2210.91 (Official build) (64-bit) 
Windows 11
```

**Comment by JoostK** [comment] 2024-01-04 09:06
Thanks for the report, this is a duplicate of https://github.com/angular/angular/issues/52539 for which the fix is pending deployment.

**Closed by JoostK** 2024-01-04 09:06 UTC
