### ISSUE TITLE
Reactive Form : input number fire valueChange too much

### ISSUE THREAD

**Issue by Wykks** [angular/angular#27750] opened 2018-12-19 10:08 UTC
# 🐞 bug report

### Affected Package

@angular/forms

### Is this a regression?

No idea

### Description

When you set type number to an input, valueChange fire sometimes on blur event after changing the value. This is not expected.
Also fire multiple times somtimes when using browser arrow to change the value.

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-input-number-issue

## 🌍  Your Environment

Chrome 71

**Comment by sarunint** [comment] 2018-12-19 11:01
According to the source:

https://github.com/angular/angular/blob/f48a00fb0cea4dab6440714a83e4b967cc8822a0/packages/forms/src/directives/number_value_accessor.ts#L42-L51

Looks like they are intended.

**Comment by kara** [comment] 2018-12-20 23:41
Dupe of https://github.com/angular/angular/issues/12540

**Closed by kara** 2018-12-20 23:41 UTC
Labels: comp: forms
