### ISSUE TITLE
Angular Universal with Angular Service Worker

### ISSUE THREAD

**Issue by zgabievi** [angular/angular#26739] opened 2018-10-25 07:46 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

When you have SSR and SW together. On first load SSR renders html and you get result instantly. Then when service worker caches index.html file and you refresh page, you don't get SSR rendered html.

## Expected behavior

Expected behavior is that each time service worker should load ssr rendered page, not only index.html

## Environment

<pre><code>
Angular version: 7.0.0

Browser:
- [x] Chrome (desktop) version XX
- [x] Chrome (Android) version XX
- [x] Chrome (iOS) version XX
- [x] Firefox version XX
- [x] Safari (desktop) version XX
- [x] Safari (iOS) version XX
- [ ] IE version XX
- [x] Edge version XX
 
For Tooling issues:
- Node version: v10.10  
- Platform:  Mac

Others:

</code></pre>

**Comment by gkalpak** [comment] 2018-10-25 12:34
This is by design. The first load is sped up by SSR; subsequent loads are sped up by SW.
If you should be able to configure the SW not to cache and serve `index.html`, but then some feature (such as offline mode) would not work.

Closing, since this works as intended, but feel free to continue the discussion below.

**Closed by gkalpak** 2018-10-25 12:34 UTC

**Comment by aescarcha** [comment] 2019-03-07 08:29
This causes an annoying visual glitch, specially if using `initialNavigation: 'enabled'`, with blinking elements everywhere. I've disabled PWA because of it. Any alternatives?
