### ISSUE TITLE
After NPM install angular2\bundles\typings\angular2 folder not available

### ISSUE THREAD

**Issue by vavasilev** [angular/angular#5600] opened 2015-12-04 10:50 UTC
Hello,

I upgraded from 2.0.0-alpha.45 to 2.0.0-alpha.47 and the folder angular2\bundles\typings\angular2 is not available any more. I need the bundled typings in order to compile my project.

Regards,

Vasil

**Comment by ericmartinezr** [comment] 2015-12-04 10:55
Check this issue https://github.com/angular/angular/issues/5248

**Comment by pkozlowski-opensource** [comment] 2015-12-04 13:01
Yes, this is duplicate of #/5248. Thnx @ericmartinezr !

**Closed by pkozlowski-opensource** 2015-12-04 13:01 UTC

**Comment by vavasilev** [comment] 2015-12-07 15:21
Thanks! That worked for me.
