### ISSUE TITLE
Console error being logged with Angular Event Binding implementation

### ISSUE THREAD

**Issue by samirprakash** [angular/angular#18334] opened 2017-07-25 23:12 UTC
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
While trying to implement event binding, I am getting an unexpected error on the developer tools console. 

I have a code snippet in my component.html as:

```
<button class="btn btn-primary" [class.active]="isActive" (click)="onSave($event)">Success</button>
```
In my component class, I am calling the method referenced in the above line:

```
onSave(event) {
    console.log('Button was clicked!');
}
```
Along with logging this message, I am also getting an error logged as:

```
Uncaught TypeError: Cannot read property 'toLowerCase' of undefined at ih.js:223
```
Initial analysis from my side revealed that the there is a condition check on `event.target.tagName.toLowerCase() !== 'a'` at the line number mentioned in the file above. That is where this error is being generated from. 

However, while trying to log the condition value in the code, I am able to get the tagName property of the event.target and I am able to successfully change it to lower case.

I am not sure why internally it is not able to read the tagName property for the event.target even though it i present there.

## Expected behavior
This error should not have come on the console. This error comes for any event that I try to use i.e. (click), (cut), (copy), (blur), (focus), (mouseover), etc.

## Minimal reproduction of the problem with instructions
For reference: `http://plnkr.co/edit/3I6bFNkmEvO8skJE0pBh?p=preview`
Check the console to see the error logged.

## Environment
Production

<pre><code>
Angular version: 4.3.1

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [x] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 6.11.1
- Platform:  Mac

Others:
Not applicable
</code></pre>

**Comment by mhevery** [comment] 2017-07-26 22:06
Thank you for submitting the issue. All issues require a [plunker](https://plnkr.co/) which demonstrates the problem and how to reproduce it. Please re-open the issue or create a new issue once you have a reproducible use case.

We are sorry that we are so aggressive on closing the issues. We are overwhelmed with the number of issues we get, and so we only have time to look at the ones which are easy for us to reproduce.

**Comment by pkozlowski-opensource** [comment] 2017-08-01 16:04
I can't reproduce with the linked plunker: http://plnkr.co/edit/3I6bFNkmEvO8skJE0pBh?p=preview so I'm going to close this one for now. Please open a new issue following our bug template when you've got a minimal reproduce scenario.

**Closed by pkozlowski-opensource** 2017-08-01 16:04 UTC
Labels: comp: core & compiler, comp: router, type: bug

**Comment by WolfieZero** [comment] 2017-09-16 00:01
I believe this to be a bug with a Chrome extension, InvisibleHand.

If you look inside that `ih.js` file you'll see the reference `invisiblehand` everywhere.
