### ISSUE TITLE
Add an option in the @Component() decorator to add scope to the view template

### ISSUE THREAD

**Issue by DustinJSilk** [angular/angular#42979] opened 2021-07-28 15:11 UTC
### Which @angular/* package(s) are relevant/releated to the feature request?

common

### Description

To expose constants or enums to a template is messy and becomes uncomfortable to manage.

It would be great if there was another way to bind data without adding it to the class.

### Proposed solution

Add an option to the @Component() decorator to quickly bind data without polluting the class.

It could look like this:

```JavaScript
import { myBigData, MY_CONSTANT } from './data';

enum Colours {
  Red,
  Green,
  Blue,
}

@Component({
  selector: 'app-colours',
  templateUrl: './colours.html',
  scope: [Colours, myBigData, MY_CONSTANT],
})
class ColoursComponent {}
```

These would be available in the template.

```html
<button (click)="trigger(Colours.red)"></button>

<div *ngFor="let item of myBigData">{{ item }}</div>

{{ MY_CONSTANT }}
```

### Alternatives considered

An alternative could be a second decorator potentially, however that doesn't sound great. A different name could work too of course.

**Comment by rafaelss95** [comment] 2021-07-30 15:08
I guess this is a duplicate of #25963 and #28658.

**Comment by itea-dev** [comment] 2021-07-30 21:06
@rafaelss95 Yes, this is a duplicate of the first issue you mentioned. 

Maybe @DustinJSilk can close this issue in favor of the other since it's older and has already reached the minimum votes.

**Comment by JoostK** [comment] 2021-07-30 21:14
Thanks for linking the duplicates @rafaelss95; closing as dup of #25963.

**Closed by JoostK** 2021-07-30 21:14 UTC
Labels: comp: common, feature, votes required
