### ISSUE TITLE
Support two-way bindings to the item of ngFor

### ISSUE THREAD

**Issue by AKlaus** [angular/angular#19819] opened 2017-10-20 01:42 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
The following code
`<my-component *ngFor="let item of Items" [(value)]="item"></my-component>`

throws an exception: 
```
Cannot assign to a reference or variable! ; Zone: ; Task: Promise.then ; Value: Error: Cannot assign to a reference or variable!(…) Error: Cannot assign to a reference or variable!
```

When the following code works:
`<my-component *ngFor="let item of Items let idx=index" [(value)]="Items[idx]"></my-component>`

It also works for a one-way binding

## Expected behavior
A consistent behaviour is expected across the both ways of declaring the loop (preferably it's always working). 

## Environment

Angular version: 4.3.6

## Others
See discussion on the Stackoverflow - https://stackoverflow.com/q/40761079/968003

**Comment by trotyl** [comment] 2017-10-20 01:49
You can try for-loop in native JavaScript (or almost any other language):

```typescript
const items = [1, 2, 3]
for (let item of items) {
  item = item + 1
}
```

Clearly it won't work. And it's by design not work.

**Comment by AKlaus** [comment] 2017-10-20 01:53
@trotyl, it makes sense. 
But for some reason many people have different expectations for the HTML syntax...

**Comment by trotyl** [comment] 2017-10-20 01:53
Duplicate of #17144, should be closed anyway.

**Closed** 2017-10-20 03:02 UTC
