### ISSUE TITLE
Date pipe does not accept an ISO 8601 string date.

### ISSUE THREAD

**Issue by DeborahK** [angular/angular#6691] opened 2016-01-26 00:48 UTC
Angular 1.x could read an ISO 8601 date from a JSON string and correctly format it with the date filter. For example:  releaseDate: "2001-12-19T00:00:00" could be formatted using: {{ movie.releaseDate | date}}

The Angular 2 date pipe throws an exception: "Invalid argument '2001-12-19T00:00:00' for pipe 'function DatePipe() "

It would be much more user-friendly for the developer if a date from a JSON string could be formatted with the date pipe without first having to transform the string into a JavaScript date.

**Comment by zoechi** [comment] 2016-01-26 08:25
dup of #6336

**Comment by pkozlowski-opensource** [comment] 2016-01-26 17:00
Closing as duplicate of https://github.com/angular/angular/issues/3261 which is the same and is already triaged.

**Closed by pkozlowski-opensource** 2016-01-26 17:00 UTC
