### ISSUE TITLE
ComponentFactoryResolver should expose its factories map

### ISSUE THREAD

**Issue by choisel** [angular/angular#24360] opened 2018-06-08 03:47 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
CodegenComponentFactoryResolver has an internal map with the factories its hold. The map is private
` private _factories = new Map<any, ComponentFactory<any>>(); `

## Expected behavior
The ComponentFactoryResolver should expose its internal map. Allowing us to better manage dynamic applications. Calling resolveComponentFactory raise an error if the resolver doesn't have the component definition. 

## What is the motivation / use case for changing the behavior?
We have an application with several lazy loaded module which contains components. We have to load the different part of the application dynamically with components coming from different modules. Looping over the different ComponentFactoryResolver of all modules with a try ... catch is just a performance debt.
We created a global ComponentFactoryResolver with get the private maps of all the loaded ComponentFactoryResolver to avoid this looping plus try ... catch

## Environment

<pre><code>
Angular version: 6.0.0
</code></pre>

Browser:
All

**Comment by ndunks** [comment] 2018-08-21 04:31
Yes, need this feature to load (entry) component by its name or by selector

**Comment by NateVonSmith** [comment] 2018-12-24 04:02
@choisel - did you say you had a solution for getting around this? looks like it's pretty low priority for the team so would be very interested to see how you (even hack-style) solved this. Thanks!

**Comment by ssougnez** [comment] 2019-07-05 06:38
I would also add that using the internal `_factories` map does not work anymore with Ivy. I have an application that uses it to load component based on their selector and it does not work with Ivy because of that. Unfortunately, I can't really create a new bug with this as we're using an internal feature...

**Comment by abadakhshan** [comment] 2019-11-10 10:27
Hello @ssougnez 

I have your problem too

I created an issue for it

https://github.com/angular/angular/issues/33715

**Comment by pkozlowski-opensource** [comment] 2020-03-03 15:23
The topic of having a map of some arbitrary string to a class name (for the purpose of dynamic component instantiation) was raised several times in the past, ex.: #35795 or #33715. 

This issue here suggest a technical solution for a general problem of "maintain a string -> component class mapping" but we are long-term plan is to move away from `ComponentFactoryResolver` - as such we won't implement the solution suggest here.

I'm going to close this one as a duplicate of #33715 since this is where we track a functional use-case.

**Comment by pkozlowski-opensource** [comment] 2020-03-03 15:24
Duplicate of #33715

**Closed by pkozlowski-opensource** 2020-03-03 15:23 UTC
Labels: comp: core, freq1: low, severity2: inconvenient, type: feature
