### ISSUE TITLE
HttpClient.request subscription called 2 times if it's called with a new HttpRequest

### ISSUE THREAD

**Issue by gizm0bill** [angular/angular#21084] opened 2017-12-18 22:04 UTC
## I'm submitting a...
<pre><code>
[ ] Regression (...might be, to be honest, the whole package)
[x] Bug report 
</code></pre>

## Current behavior
`HttpClient.request` subscription's next is called 2 times if the method is called with a `new HttpRequest`... at least in the test environment

## Expected behavior
`HttpClient.request` subscription's next is NOT called 2 times if the method is called with a `new HttpRequest`

## Minimal reproduction of the problem with instructions
https://plnkr.co/edit/ZBefIspCVT2GYKIEwQZB?p=preview

## What is the motivation / use case for changing the behavior?
I'm trying to upgrade my decorator based REST client library to this new "evolution" of a client and it breaks my tests... besides the fact that the testing methodology feels pretty rudimentary compared to its predecessor package

## Environment

<pre><code>
Angular version: 5.1.1

Browser:
- [x] Chrome (desktop) version 63.0.3239.108
 
Others: macOS 10.12.6
</code></pre>

**Comment by alxhub** [comment] 2020-05-29 20:26
This reproduction doesn't actually pass TypeScript type-checking for me. In particular, TS complains that the type of `data` returned by the `Observable` is `HttpEvent<unknown>`, and thus doesn't have a `body` property.

TypeScript is 100% correct here, and it's actually telling you what the problem is. The `request()` method when called with `HttpRequest` instances, returns a stream of `HttpEvent`s. By default every successful request will have two events, of types `Sent` and `Response`.

So the expectation that `count` will only be `1` is incorrect - there should actually be 2 events received here, and there are. I'm going to close this issue as a support request / not an actionable bug in Angular.

**Closed by alxhub** 2020-05-29 20:26 UTC
Labels: comp: common/http, freq2: medium, severity3: broken, type: support
