### ISSUE TITLE
Update Guide is incomplete info for updating to v 7.x when using a custom app config

### ISSUE THREAD

**Issue by arturhun** [angular/angular#27234] opened 2018-11-22 13:44 UTC
Not sure this is the right repo to submit a ticket regarding update.angular.io content.
I hope you are able to administratively move the ticket to an appropriate place if not.

# 📚 Docs or angular.io bug report

### Description

After performing `ng update @angular/core @angular/cli` my app config service which was reading a custom app config during `APP_INITIALIZER` boot, suddenly broke for localhost (only). Apparently, there was a change in how paths are resolved for paths located outside of `src/` folder.

## 🔬 Minimal Reproduction

**app.config.service** (running from within APP_INITIALIZER)

```
const APP_CONFIG_FILE_NAME = 'appConfig.json';

@Injectable({
  providedIn: 'root',
})
export class AppConfigService {
  public configData$: Subject<any> = new Subject<any>();
  public configData = {};

  constructor(
    private readonly http: HttpClient,
  ) { }

  load(): Promise<any> {
    const configUrl = environment.isLocal
      ? `./${APP_CONFIG_FILE_NAME}`    // <- this stopped to work in 7.x
      : `../${APP_CONFIG_FILE_NAME}`;

    return this.loadAppConfig(configUrl);
  }

  get(setting: string): any {
    return this.configData[setting];
  }

  getAll(): any {
    return this.configData;
  }

  loadAppConfig(path: string): Promise<any> {
    return this.http.get(path, {
        params: {
          v: `${Date.now()}`,
        },
      })
      .toPromise()
      .then(data => {
        this.configData = data;
        this.configData$.next(data);
        return data;
      });
  }
}
```
I had to add `src/appConfig.json` as an asset path in angular.json to make it work again.
It was reproducible on a small side project. 

### What's the affected URL?**
I am not saying that this is angular change or angular fault (I don't know it), but regardless - I believe the guide for update to version 7 should mention that as one of points to consider during the update.

### Reproduction Steps**

So the above code worked previously (v 6.1) for appConfig.json file residing as sibling to src folder and package.json file.

### Expected vs Actual Behavior**

The remedy is to move the config file to `assets/` folder or any other location beginning within `src/` (but in that case - also explicitly add its path to angular.json)

## 🔥 Exception or Error
The above code resulted in hard to debug 404s from WDS and app not loading (locally).

### Anything else relevant?

I would be glad to get to know what was the change that cause it to fail (angular? webpack?). Seems like `src/` is a mandatory part of path during file resolution now.

**Comment by raxim1** [comment] 2018-11-22 15:21
You might forgot to run the following command.

ng update @angular/cli --migrate-only --from=1.7.4

//1.7.4 was my version, i have upgraded from 5.

I had to add some window / Buffer polyfill also:

(window as any).global = window;
(window as any).process = window;
(window as any).Buffer = require('buffer').Buffer;
(window as any).process.browser = true;
(window as any).process.version = '';
(window as any).process.versions = {node: false};

Unfortunately if you embed some variable like this, no system will really handle that problem properly.

**Comment by StephenFluin** [comment] 2018-11-30 04:50
As of v6 we synchronized the major versions of the CLI and the Angular packages, meaning you should be using v6 of the CLI with v6 of Angular.

What was your CLI version prior to the update?

The update guide covers the migration of CLI configs from v5 to v6, and it recommends not to move across major versions as unsupported.

I'm thinking that this is working as intended, but it's possible I'm missing something that we could address better in the update guide.

**Comment by arturhun** [comment] 2018-11-30 08:01
Hi Stephen,

Thanks for getting back.

I am sure I had CLI updated at that time, just not sure whether it happened as part of `ng update` or was carried out "manually". Now I have rolled back my cli to 6.2.x

Something definitely has changed (whether in CLI or Webpack DevServer - not sure) that is not mentioned in the guide, and this was the intention of my ticket. But now that your reply made me revisit the ticket, I see the problem has been triaged and tagged with critical/broken tags. Does that mean it is going to be treated as a regression bug (fixed and reverted to previous behavior)?

Best regards,
Art

**Comment by StephenFluin** [comment] 2018-11-30 21:30
It's marked as broken / critical documentation, not with the CLI right now (component is `docs` in the labels). Do you have a repo I could check out or a set of steps from `ng new` to reproduce it on my own machine? It's not clear what your boot looks like or how it's integrated with the service you shared.

**Comment by arturhun** [comment] 2018-12-01 16:20
@StephenFluin Here it is: https://gitlab.com/moniuch/appconfig
The repo contains dependencies for 6.1.x, so to reproduce the problem please perform the following steps:

**6.x**
1. Run `ng serve`- the settings from appConfig will be read in and shown in the template
2. Run `ng build` - then drop the appConfig.json file into `dist/appconfig` directory, and serve locally (eg. `http-server ./dist/appconfig`) - the result should be as in step 1.

Now, ng update to **7.x**, and:

1. Run `ng serve`- the settings from appConfig will NOT be read in - 404 in console
2. Run `ng build` - then drop the appConfig.json file into `dist/appconfig` directory, and serve locally (eg. `http-server ./dist/appconfig`) - the result should be as in step 1.

Note: the `appConfig.json` file lives at the project root (sibling to package.json)

**Comment by StephenFluin** [comment] 2018-12-04 22:54
Okay, so it looks like you have been relying on a nonstandard behavior of the `ng serve` command.

I don't think this behavior is part of our public or intended API @alexeagle feel free to chime in. You can tell it isn't standard because we don't want you to ever have to copy files around manually as part of a build process (serve and build should be almost identical).

I believe the intended way is for you to store this file somewhere in src/ such as src/appConfig.json and then list it in the assets array in /architect/build/options/ in angular.json. I tested and this works fine in both 6 and 7 with serve and build.

**Comment by arturhun** [comment] 2018-12-05 07:31
Thanks @StephenFluin.
This is exactly the solution path I took. I wasn't sure though whether this is an explicit change update.angular.io should warn me about or not when upgrading to v7.
Thanks for your help once again!

**Comment by JoostK** [comment] 2021-05-24 19:20
Closing as obsolete; sorry that this was never clarified but I'm afraid we can't retroactively improve the upgrade guide for this case as it's not clear what to do in this case (or why the behavior started to deviate from v6 to v7).

**Closed by JoostK** 2021-05-24 19:20 UTC
Labels: P3, comp: docs, freq4: critical, subtype: docs-versioncompat, type: bug/fix
