### ISSUE TITLE
Service workers registration breaks app in Safari

### ISSUE THREAD

**Issue by anzap** [angular/angular#38328] opened 2020-08-03 08:48 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/service-worker from at least v8.x till latest version

### Is this a regression?

 Nope, as far as i can tell the issue was always there

### Description

 Adding the package to an angular app and registering the module via importing
```
ServiceWorkerModule.register('ngsw-worker.js', { enabled: environment.production })
```
breaks the app in safari with error
```
TypeError: undefined is not an object (evaluating 't.getSubscription')
```
The error is fired multiple times bringing the app to a crawl and eventually breaking Safari. After a refresh some times you get the following error also
```
Maximum call size exceeded
```

## 🔬 Minimal Reproduction

 https://stackblitz.com/...

## 🔥 Exception or Error

Error seems to come from the following line in the package https://github.com/angular/angular/blob/master/packages/service-worker/src/push.ts#L151
In constructor of SwPush service the check if service workers is done like this:
```
constructor(private sw: NgswCommChannel) {
    if (!sw.isEnabled) {
      this.messages = NEVER;
      this.notificationClicks = NEVER;
      this.subscription = NEVER;
      return;
    }
```
Specifically for Safari it is the case that service workers are supported but Push API is not. A check like the following seems to be more complete and would guard against this error:
```
if (!sw.isEnabled && !('PushManager' in window || 'pushManager' in ServiceWorkerRegistration.prototype))
```

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 8.3.13
Node: 12.13.0
OS: linux x64
Angular: 8.2.11
... common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.803.13
@angular-devkit/build-angular      0.803.13
@angular-devkit/build-optimizer    0.803.13
@angular-devkit/build-webpack      0.803.13
@angular-devkit/core               8.3.13
@angular-devkit/schematics         8.3.13
@angular/animations                8.2.14
@angular/cdk                       8.2.3
@angular/cli                       8.3.13
@angular/material                  8.2.3
@angular/material-moment-adapter   8.2.3
@angular/pwa                       0.901.12
@angular/service-worker            8.2.14
@ngtools/webpack                   8.3.13
@schematics/angular                8.3.13
@schematics/update                 0.803.13
rxjs                               6.5.4
typescript                         3.5.3
webpack                            4.39.2

</code></pre>

**Anything else relevant?**

**Comment by gkalpak** [comment] 2020-08-06 09:47
AFAICT, this error happens when trying to subscribe to notifications (which is something that the app does, via `@angular/service-worker`'s `SwPush` service). The fact that the error is fired multiple times (and eventually causes a `Maximum call size exceeded` error) is probably due to your app code (maybe an error is not handled properly).

Other than that, the problem with Push notifications on Safari is tracked in #27889. Do the work-arounds listed in https://github.com/angular/angular/issues/27889#issuecomment-451137237 work for you, @anzap?

I am going to close this as a duplicate of #27889. Let's move the discussion there.
As mentioned in https://github.com/angular/angular/issues/27889#issuecomment-451137237, I think it makes sense to make the Angular ServiceWorker more robust wrt these kind of errors, so feel free to send a pull request with your suggestion, @anzap.

**Closed by gkalpak** 2020-08-06 09:47 UTC
Labels: browser: safari, comp: service-worker

**Comment by anzap** [comment] 2020-08-06 13:25
Yeap @gkalpak you are right the issue which led to `Maximum call size exceeded` was for me caused from ngrx effects subscribing to the result of `swPush.subscription`. This was happening sometimes before the registration of service worker and the error was not handled which led to weird behavior.
In any case by refactoring my effects and incorporating the error handling logic in #27889 i did manage to fix my issue. So leaving this comment here for anyone else that might come across this. 

I will try to come up with a PR for the extra check as soon as possible and link to issue #27889 for you to verify.
Thanks again for your input.
