### ISSUE TITLE
matinput time has issue in safari

### ISSUE THREAD

**Issue by garvraj** [angular/angular#51644] opened 2023-09-04 08:39 UTC
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

Yes

### Description

The form does not register any component change.
The time displayed in the form-field-input is "12:30"

### Please provide the environment you discovered this bug in (run `ng version`)

```true
<div class="content_body">
  <form [formGroup]="formPrincipal">
    <mat-form-field appearance="outline" color="primary">
      <mat-label>Testing</mat-label>
      <input type="time" formControlName="time" matInput>
    </mat-form-field>

    <button mat-button (click)="consoleLog()">
      Console
    </button>
  </form>
</div>

sets an initial value of 12:30 pm

Angular: 12.1.1
CDK/Material: 11.2.5
Browser(s): Safari
Operating System (e.g. Windows, macOS, Ubuntu): macOS
```

**Comment by JeanMeche** [comment] 2023-09-04 08:41
Dupe of #50036

**Closed by JeanMeche** 2023-09-04 08:41 UTC
