### ISSUE TITLE
InvalidProviderError when assigning the return value of a test fixture generator

### ISSUE THREAD

**Issue by andrashatvani** [angular/angular#6986] opened 2016-02-10 10:57 UTC
If I use a test fixture object directly or provide it via an exported function, then it works, but providing the same object via a class (whether as class or instance function) in a spec leads to an InvalidProviderError:
```typescript
let items = TestFixtureGenerator.arrayWithOneItem();
```

The TestFixtureGenerator looks as follows:
```typescript
export class TestFixtureGenerator {
    public static arrayWithOneItem(): {
        return [{id:1}];
    }
}
```

The result:
`Failed: Cannot read property 'toString' of undefined
	TypeError: Cannot read property 'toString' of undefined
	    at new InvalidProviderError (D:/Users/l026291/Development/ts-automat-fe/node_modules/angular2/bundles/angular2.dev.js:1727:111)
	    at D:/Users/l026291/Development/ts-automat-fe/node_modules/angular2/bundles/angular2.dev.js:9767:15
	    at Array.forEach (native)
	    at _normalizeProviders (D:/Users/l026291/Development/ts-automat-fe/node_modules/angular2/bundles/angular2.dev.js:9757:15)
	    at Object.resolveProviders (D:/Users/l026291/Development/ts-automat-fe/node_modules/angular2/bundles/angular2.dev.js:9723:22)
	    at Function.Injector.resolve (D:/Users/l026291/Development/ts-automat-fe/node_modules/angular2/bundles/angular2.dev.js:11290:25)
	    at Injector.resolveAndCreateChild (D:/Users/l026291/Development/ts-automat-fe/node_modules/angular2/bundles/angular2.dev.js:11336:40)
	    at TestInjector.createInjector (D:/Users/l026291/Development/ts-automat-fe/node_modules/angular2/bundles/testing.dev.js:1848:37)
	    at TestInjector.execute (D:/Users/l026291/Development/ts-automat-fe/node_modules/angular2/bundles/testing.dev.js:1854:14)
	    at Object.<anonymous> (D:/Users/l026291/Development/ts-automat-fe/node_modules/angular2/bundles/testing.dev.js:1970:44)
	    at D:/Users/l026291/Development/ts-automat-fe/node_modules/angular2/bundles/testing.dev.js:1978:15
	    at Zone.run (D:/Users/l026291/Development/ts-automat-fe/node_modules/angular2/bundles/angular2-polyfills.js:1243:24)
	    at zoneBoundFn (D:/Users/l026291/Development/ts-automat-fe/node_modules/angular2/bundles/angular2-polyfills.js:1220:26)
	    at lib$es6$promise$$internal$$tryCatch (D:/Users/l026291/Development/ts-automat-fe/node_modules/angular2/bundles/angular2-polyfills.js:468:17)
	    at lib$es6$promise$$internal$$invokeCallback (D:/Users/l026291/Development/ts-automat-fe/node_modules/angular2/bundles/angular2-polyfills.js:480:18)
	    at D:/Users/l026291/Development/ts-automat-fe/node_modules/angular2/bundles/angular2-polyfills.js:1028:14
	    at D:/Users/l026291/Development/ts-automat-fe/node_modules/angular2/bundles/angular2-polyfills.js:123:10
	    at Zone.run (D:/Users/l026291/Development/ts-automat-fe/node_modules/angular2/bundles/angular2-polyfills.js:1243:24)
	    at zoneBoundFn (D:/Users/l026291/Development/ts-automat-fe/node_modules/angular2/bundles/angular2-polyfills.js:1220:26)
	    at lib$es6$promise$asap$$flush (D:/Users/l026291/Development/ts-automat-fe/node_modules/angular2/bundles/angular2-polyfills.js:262:10)
`

**Comment by RomanGotsiy** [comment] 2016-02-12 10:31
@andrashatvani provide the code you're using for providing :)
The following code works for me:
```js
beforeEachProviders(() => [
        provide(SomeClass, {useClass: SomeClassMock}),
    ]);
```

**Comment by pkozlowski-opensource** [comment] 2016-06-03 18:16
Closing as we don't have any reproduce scenario.

**Closed by pkozlowski-opensource** 2016-06-03 18:16 UTC
