### ISSUE TITLE
 Cannot set property 'lastInBinding' of undefined

### ISSUE THREAD

**Issue by racksen** [angular/angular#4721] opened 2015-10-14 05:55 UTC
Attaching events in template throws error.

e.g the following template works fine
```
<input #testname value="Test" />
<p> {{ testname.value }}</p>
```
but the following one throws error, the moment I add the event
```
<input #testname value="Test"  (keyup)/>
<p> {{ testname.value }}</p>
```
Looks like its related to the issue https://github.com/angular/angular/issues/1789

**Comment by ericmartinezr** [comment] 2015-10-14 11:09
Hey there @racksen that issue is related to https://github.com/angular/angular/issues/3754

**Comment by pkozlowski-opensource** [comment] 2015-10-14 11:18
Duplicate of #3754

Once again, using an event handler without a handler doesn't make much sense. You don't want to read from the DOM all the time like you are trying to do in your example. There are many ways of doing it differently:
* `<input value="Test"  (keyup)="testVal = $event.target.value"><p> {{ testVal }}</p>`
* `<input value="Test"  [(ng-model)]="testVal"><p> {{ testVal }}</p>`

**Closed by pkozlowski-opensource** 2015-10-14 11:18 UTC

**Comment by maxime1992** [comment] 2015-10-14 12:53
@pkozlowski-opensource when you say that using an event handler without a handler doesn't make much sense, i understand.
But it's written in the doc and that's why it's confusing : https://angular.io/docs/ts/latest/guide/user-input.html#local-variables

**Comment by pkozlowski-opensource** [comment] 2015-10-14 12:57
@maxime1992 as noted in #3754 docs need to be fixed and the error message needs to be fixed. Docs are being re-done atm so this should be covered soon.
