### ISSUE TITLE
Module

### ISSUE THREAD

**Issue by Mistik** [angular/angular#39615] opened 2020-11-09 21:29 UTC
Hi

I saw you are using the detect-node module.

Actually this module is about to be depreciated so I would suggest moving to the nodejs-detector module instead. No API changes needed!

**Comment by alan-agius4** [comment] 2020-11-10 07:33
Duplicate of https://github.com/angular/angular-cli/issues/19327

**Closed by alan-agius4** 2020-11-10 07:33 UTC
