### ISSUE TITLE
Angular Docs are very slow to load

### ISSUE THREAD

**Issue by jvall** [angular/angular#25487] opened 2018-08-14 20:39 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ X ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
The [Angular Docs](https://angular.io/docs) are very slow to load and often don't load at all. It sometimes takes multiple refreshes to get it to appear, either when visiting the home page or linking to a specific route in the docs.

## Expected behavior
For the docs to load instantly, and for them to load offline (I thought that they were an offline-ready PWA at one point).

## Minimal reproduction of the problem with instructions
I visited in the docs in the latest version of Chrome, but it appears to be cross-browser.

## Environment

Documentation string at the bottom of the page, when it does load, says `Version 6.1.3-build.47947+sha.e906bf4`.

Browser:
- [X] Chrome (desktop) version 68.0.3440.106
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by lazarljubenovic** [comment] 2018-08-14 21:10
I'm seeing `Version 6.1.3-build.47953+sha.cdee9ad` after a hard refresh and it's super-smooth.

**Comment by jenniferfell** [comment] 2018-08-20 16:04
Potentially related to https://github.com/angular/angular/issues/24392

**Comment by ajitsinghkaler** [comment] 2020-01-28 18:13
@gkalpak is this still applicable

**Comment by gkalpak** [comment] 2020-01-28 18:33
No idea, since I couldn't reproduce the original issue. I see there are people that have upvoted the original description (mentioning the slowness) as well as people upvoting @lazarljubenovic's comment (mentioning no slowness).

Given that there have been several updates since this was first opened and given that we don't have enough info to investigate, I suggest we close this.

If anyone is still having problems, please open a new issue, mentioning the OS/browser version and also any other info that might help investigate this (such as verifying it happens even in incognito mode, whether it affects specific machines or not, any errors /warnings in the console, etc.).

**Closed by gkalpak** 2020-01-28 18:33 UTC
Labels: comp: docs-infra
