### ISSUE TITLE
multiple @HostListener decorator bug

### ISSUE THREAD

**Issue by vthinkxie** [angular/angular#13337] opened 2016-12-09 10:02 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When using multiple @ HostListener decorator on same function, such as code below
```typescript
  @HostListener('click', ['$event'])
  @HostListener('mouseover', ['$event'])
  @HostListener('focus',['$event'])
  private eventRouter(e) {
     console.log(e);
  }
```
Only the first decorator will be listened, but the function got the latest decorator event, and the middle decorator and the last decorator will never be trigger.

**Expected behavior**

fix this bug

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.3.0

* **Browser:** [all ]

* **Language:** [TypeScript 2.0.7]
* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment] 2016-12-09 10:04
Duplicate of https://github.com/angular/angular/issues/13303

**Comment by vicb** [comment] 2016-12-09 16:34
We will handle both listener and binding in the other issue

**Closed by vicb** 2016-12-09 16:34 UTC
