### ISSUE TITLE
Error After updating 16.2.0 When using browser-esbuild 

### ISSUE THREAD

**Issue by ngadceser** [angular/angular#51330] opened 2023-08-11 01:57 UTC
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

Yes

### Description

After updating 16.2.0
When using browser-esbuild  There is an error as below.
"builder": "@angular-devkit/build-angular:browser-esbuild",
@use 'sass:map';
@use '@angular/material' as mat;

 [ERROR] Invalid URL: Scheme not starting with alphabetic character
 @use "__NG_PACKAGE__; src/styles/override;@angular/material" as mat;

"@angular/animations": "^16.2.0",
"@angular/cdk": "16.2.0",
"@angular/common": "^16.2.0",
"@angular/compiler": "^16.2.0",
"@angular/core": "^16.2.0",
"@angular/forms": "^16.2.0",
"@angular/material": "16.2.0",

However, if you use "builder": "@angular-devkit/build-angular:browser", the error disappears.

### Please provide the environment you discovered this bug in (run `ng version`)

```true
"@angular/cdk": "16.2.0",
    "@angular/common": "^16.2.0",
    "@angular/compiler": "^16.2.0",
    "@angular/core": "^16.2.0",
    "@angular/forms": "^16.2.0",
    "@angular/material": "16.2.0",
Windows 11
```

### Anything else?

It only happens in es-build after updating.

**Comment by JoostK** [comment] 2023-08-11 06:28
Duplicate of angular/angular-cli#25660

**Closed** 2023-08-11 06:28 UTC
