### ISSUE TITLE
Capturing all the events doesn't work correctly for Microsoft Edge

### ISSUE THREAD

**Issue by avolobuev** [angular/angular#31696] opened 2018-10-10 11:30 UTC
Hi.
It seems there is an issue for patchViaCapturingAllTheEvents() function in Microsoft Edge browser (from 17 version). 
This block:
      if (elt) {
        source = elt.constructor['name'] + '.' + onproperty;
      }
Throws exception: Unable to get property 'name' of undefined or null reference

Its difficult to reproduce. Can't tell for which event target it happens and there are no acceptable stack traces. It just happens some times.

Zone version 0.8.26
Angular version 6.0.7

It strange comment also, especially last line, before this block:
// Whenever any eventListener fires, we check the eventListener target and all parents
// for `onwhatever` properties and replace them with zone-bound functions
// - Chrome (for now)

So, can you explain a bit more of this block of code/
Why this may happen?

**Comment by atscott** [comment] 2020-10-28 18:18
Closing as obsolete since Edge is now chromium based and this issue can't be reproduced.

**Closed by atscott** 2020-10-28 18:18 UTC
Labels: comp: zones, state: needs more investigation
