### ISSUE TITLE
JS Exception prevents downloading Tutorial Code

### ISSUE THREAD

**Issue by ChuckieHacks3-0** [angular/angular#56457] opened 2024-06-14 17:54 UTC
### Describe the problem that you experienced

When clicking the download icon in the top right-hand corner of the editor, nothing happens.  A JS error is thrown:
![image](https://github.com/angular/angular/assets/83046195/ea0cd86e-33d2-42d4-8b84-3d4c23f4684a)

### Enter the URL of the topic with the problem

https://angular.dev/tutorials/first-app

### Describe what you were looking for in the documentation

To download the Angular tutorial solution like the tutorial indicates you should do

### Describe the actions that led you to experience the problem

Clicking on the icon

### Describe what you want to experience that would fix the problem

Having the solution download into a zip file.

**Comment by JoostK** [comment] 2024-06-14 18:44
Duplicate of https://github.com/angular/angular/issues/56404

**Closed by JoostK** 2024-06-14 18:44 UTC
