### ISSUE TITLE
@angular/animations documentation is missing in Workspace npm dependencies' Default Dependencies section

### ISSUE THREAD

**Issue by pankajd24** [angular/angular#55457] opened 2024-04-22 05:23 UTC
### Describe the problem that you experienced

I was going through the @angular/animations documentation is missing in Workspace npm dependencies's Default Dependencies section(https://angular.dev/api/animations) 

However, after clicking on the link, I was greeted with an empty content/404 page.

### Enter the URL of the topic with the problem

https://angular.dev/api/animations

### Describe what you were looking for in the documentation

click on @angular/animations documentation is missing in Workspace npm dependencies' Default Dependencies section
<img width="900" alt="image" src="https://github.com/angular/angular/assets/164315475/5ab438ba-da73-4246-9f8e-84763510cdf3">

### Describe what you want to experience that would fix the problem

when i clicked on above clock, following error is coming
<img width="897" alt="image" src="https://github.com/angular/angular/assets/164315475/0fe9ad67-d307-4767-8093-dd949f5b595d">

### Add a screenshot if that helps illustrate the problem

<img width="897" alt="image" src="https://github.com/angular/angular/assets/164315475/6862fe72-a853-42f8-9ced-8d6b90f18db9">

**Comment by JeanMeche** [comment] 2024-04-22 16:09
I'll close this as a dupe of #55457

**Closed by JeanMeche** 2024-04-22 16:09 UTC
