### ISSUE TITLE
[BETA3] angular2.min.js some internal directives like NgIF does not work

### ISSUE THREAD

**Issue by carlos-algms** [angular/angular#6996] opened 2016-02-10 22:21 UTC
Simply removing `bundles/angular2.min.js` and put unminified version `bundles/angular2.js` magically works.
Even if I minify by my self with uglify, the error persist.

**Comment by ffMathy** [comment] 2016-02-11 18:22
I think it may be the same reason that #7006 is happening too.

**Comment by alexeagle** [comment] 2016-02-12 03:18
dupe of #7006

**Closed by alexeagle** 2016-02-12 03:18 UTC
