### ISSUE TITLE
CANNOT get host component from directive using `ContentChildren` (or `ContentChild`) when IVY is ON

### ISSUE THREAD

**Issue by highestop** [angular/angular#39756] opened 2020-11-19 11:16 UTC
# 🐞 bug report

### Affected Package

Encountered this issue when we try to upgrade an old Angular project from 8 to 11, and turn on Ivy

### Is this a regression?

Turn off Ivy works fine, no need to downgrade

### Description

CANNOT get the host component from a directive using `ContentChildren` when I upgrade my project to 11 and use Ivy.

Before that my project is using 8 and no Ivy, everything works fine.

## 🔬 Minimal Reproduction

https://github.com/highestop/ng-demo-v11

Assume we have a custom Component `HelloComponent` and a Directive `HelloDirective`

In template we have

```html
<hello appHello></hello>
```

In `appHello` Directive I try to get the host component instance using `ContentChildren` like

```ts
export class HelloDirective implements AfterContentInit {
  @ContentChildren(HelloComponent, {descendants: true})
  contentComponents: QueryList<HelloComponent>;

  ngAfterContentInit() {
    console.log(this.contentComponents?.length);
  }
}
```

Clearly we have nothing in that query list

![image](https://user-images.githubusercontent.com/12963908/99656538-f859e000-2a97-11eb-95b1-849c5a5fe1d4.png)

Though in earlier version before Ivy, everything works fine. Just need to set `"enableIvy": false`, and there it is

![image](https://user-images.githubusercontent.com/12963908/99657279-ea588f00-2a98-11eb-8d8b-8e28d862d1a4.png)

Seems I can't reproduct it on StackBlitz, like https://stackblitz.com/edit/angular-p7dx2x. Switching `enableIvy` doesn't work.

## 🔥 Exception or Error

CANNOT get the host component from a directive using `ContentChildren` when I upgrade my project to 11 and use Ivy.

## 🌍  Your Environment

**Angular Version:**
```
Angular CLI: 11.0.2
Node: 14.15.0
OS: darwin x64

Angular: 11.0.1
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes
```
**Package Version:**
```
@angular-devkit/architect       0.1100.2
@angular-devkit/build-angular   0.1100.2
@angular-devkit/core            11.0.2
@angular-devkit/schematics      11.0.2
@angular/cli                    11.0.2
@schematics/angular             11.0.2
@schematics/update              0.1100.2
rxjs                            6.6.3
typescript                      4.0.5
```

**Comment by JoostK** [comment] 2020-11-19 11:35
This is a known breaking change in Ivy (see https://github.com/angular/angular/issues/36945#issuecomment-624513220 for details) as a fix for #10098.

It's also listed in the [Ivy compatibility guide](https://angular.io/guide/ivy-compatibility):
> @ContentChild and @ContentChildren queries will no longer be able to match their directive's own host node (previously, these queries would match the host node in addition to its content children).

As this is now working as intended, I'll close this issue as non-actionable. The alternative of injecting the host as in the constructor as mentioned in https://github.com/angular/angular/issues/36945#issuecomment-624513220 should enable you to make it work again.

**Closed by JoostK** 2020-11-19 11:35 UTC
