### ISSUE TITLE
Code written in plain text

### ISSUE THREAD

**Issue by hssanbzlm** [angular/angular#53739] opened 2024-01-01 14:53 UTC
### Describe the problem that you experienced

While exploring Angular docs, in Dependency Injection under injection context (Stack frame in context). I found a code block written in plain text what makes it unclear and interfere with text.

### Enter the URL of the topic with the problem

https://angular.dev/guide/di/dependency-injection-context#stack-frame-in-context

**Comment by JoostK** [comment] 2024-01-01 16:44
Thanks for the report, this is a duplicate of #53526, the fix is pending deployment.

**Closed by JoostK** 2024-01-01 16:44 UTC
