### ISSUE TITLE
Consistent handling of <script> and <style>

### ISSUE THREAD

**Issue by molnarg** [angular/angular#8814] opened 2016-05-24 15:41 UTC
- **I'm submitting a ...**
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

**Current behavior**

`<script>` and `<style>` tags are stripped from templates, but they are listed in the DOM element registry as supported, complete with DOM properties, etc.: https://github.com/angular/angular/blob/master/modules/%40angular/compiler/src/schema/dom_element_schema_registry.ts

**Expected/desired behavior**

They should be at least removed from the registry. Even better, they could be marked as forbidden in the registry so that it's clear that they don't fall in the 'unknown' tag category.

**Angular version:** GitHub repo, master branch

@mprobst advised me to CC @tbosch and @mhevery for this issue, thanks for taking a look at it!

**Comment by DzmitryShylovich** [comment] 2017-02-05 22:28
@molnarg `style` elements from templates will be later re-attached to the head

**Comment by pkozlowski-opensource** [comment] 2019-03-09 15:03
We are already tracking support for `<script>` and `<style>` in other issues, no need to duplicate:
* `<script>` are tracked in #26293 - I've added a note about an error message in there;
* `<style>` tags are supported but their attributes are not (this is tracked in #6513)

Closing as a duplicate of #26293 and #6513

**Closed by pkozlowski-opensource** 2019-03-09 15:03 UTC
Labels: comp: core & compiler, type: feature
