### ISSUE TITLE
Add AbstractControlOptions to FormBuilder functions

### ISSUE THREAD

**Issue by AncelHernandez** [angular/angular#20734] opened 2017-12-01 16:22 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[X ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Expected behavior

I am trying to add `updateOn: 'blur'` to a control using `FormBuilder`, looking at the source code it looks like it only takes in `ValidatorFn` and `AsyncValidatorFn`.

```
Angular CLI: 1.5.4
Node: 6.9.4
OS: win32 x64
Angular: 5.0.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.5.4
@angular-devkit/build-optimizer: 0.0.34
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.38
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.4
@schematics/angular: 0.1.8
typescript: 2.4.2
webpack: 3.8.1
```

**Comment by stones** [comment] 2017-12-05 10:10
I am not sure if this is a good answer, but this works for me:
`{updateOn:  ('change' as FormHooks)}`

**Comment by kara** [comment] 2017-12-05 23:08
Dupe of existing issue https://github.com/angular/angular/issues/19163

**Closed by kara** 2017-12-05 23:08 UTC
Labels: comp: forms
