### ISSUE TITLE
OnChanges does not give proper types on changed properties

### ISSUE THREAD

**Issue by bengry** [angular/angular#24073] opened 2018-05-23 17:14 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

The following code:
```typescript
const defaultValue: string = 'test';
export class MyCounterComponent implements OnChanges {
  @Input() counter: number;

  ngOnChanges(changes: SimpleChanges) {
    const isDefaultValue = changes.counter.currentValue === defaultValue;
  }
}
```
Passes compilation, since `currentValue` (as well as `previousValue`) is typed as `any`, while it should be typed as `number`.

## Expected behavior

```typescript
...
const isDefaultValue = changes.counter.currentValue === defaultValue;
...
```
Shouldn't pass compilation.

## What is the motivation / use case for changing the behavior?

TypeScript has been offering mapped types for quite a while now, yet Angular doesn't take advantage of them, at least not in a large enough scale (lots of stuff are still typed as `any` when generics + mapped types would give better results).

## Environment

<pre><code>
Angular version: 6.0.3

</code></pre>

**Comment by trotyl** [comment] 2018-05-23 17:39
Duplicate of https://github.com/angular/angular/issues/17560

**Closed** 2018-05-24 22:38 UTC
