### ISSUE TITLE
Childrouting inside auxiliary outlet works only in very specific cases

### ISSUE THREAD

**Issue by luckylooke** [angular/angular#26672] opened 2018-10-23 08:53 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Routing inside auxiliary routes is broken.

## Expected behavior

Same routing experience as inside primary routers. There should be no difference between routing inside primary router, auxiliary or nested routes. Each child route should be should behave consistently whatever parent outlet is.

## Minimal reproduction of the problem with instructions

Angular 6.1.10
https://stackblitz.com/edit/angular-routing-default-aux?embed=1&file=src/app/app.routing.module.ts
Angular 7.0.0
https://stackblitz.com/edit/angular-routing-default-aux-a7?embed=1&file=src/app/app.routing.module.ts

Click on navigation links

## What is the motivation / use case for changing the behavior?

Consistency in behavior of routing will prevent unexpected outputs. 

## Environment

<pre><code>
Angular version: 6.1.10, 7.0.0

Browser:
- [ x] Chrome (desktop) version 69.0.3497.81 OS: Win7
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by luckylooke** [comment] 2018-12-06 06:06
Yes I am really sorry I should review my question after some time to get 3rd person view on it :) Now I see how badly I wrote it, I did not left any context here or real steps.

Situation:
AppComponent ( root, have two outlets one unnamed and one named 'secondary' outlet )
AuxComponent ( has one unnamed outlet )
OneComponent, TwoComponent, ThreeComponent ( basic components, nothing special )
All routes configuration is in app.routing.module.ts.

Ok, so at first it loads in empty route state:
OneComponent is loaded into root primary outlet and AuxComponent is loaded in secondary outlet. As AuxComponent have nested outlet with children routes defined in router config, redirection should be applied to go to 'three' route. This is not happening.

Navigating to '/two' (`[routerLink]="['two']"`), pretty same scenario is expected in secondary outlet. Again no redirection happens.

Navigating explicitly to '/(secondary:three)' (`[routerLink]="['', {outlets:{secondary:['three']}}]"`) works.
But navigating explicitly to '/two/(secondary:three)' (`[routerLink]="['two', {outlets:{secondary:['three']}}]"`) does not, it throws error that it cannot match segment 'two'.

Navigating from '/(secondary:three)' to '/two' keeps secondary outlet untouched (ThreeComponent displayed), url is changed to '/two(secondary:three)' as expected.

But navigating from '/(secondary:three)' to '' or '/' removes navigation from secondary outlet. I am expecting same behaviour as for '/two' that secondary routing will be kept untouched.

Probably it will be better after applying recent fix https://github.com/angular/angular/commit/20cef5078dc86bc5d9831fafec076d912ad3521f by Igor.

Maybe also Maxim's https://github.com/angular/angular/pull/25483 could help. 

Thank you for your time! You are awesome! :)

**Comment by jasonaden** [comment] 2018-12-18 22:37
Thanks for the update! We tried to merge the commit [20cef50](https://github.com/angular/angular/commit/20cef5078dc86bc5d9831fafec076d912ad3521f) which was actually submitted by a community member.

We had an issue internally that caused that commit to be reverted, but we will be looking at getting it merged again as soon as possible.

I'll take a look at the additional info. Thanks!

**Comment by atscott** [comment] 2020-11-17 19:13
Closing as duplicate of #13523 for the 
```
<p><a [routerLink]="['two', {outlets:{secondary:['three']}}]">Navigate to /two(secondary:three)</a> = NOK(cannot match "two" segment)</p>
```
This should instead be:
```
a [routerLink]="[{outlets:{primary: 'two', secondary:['three']}}]">Navigate to /two(secondary:three)</a> = NOK(cannot match "two" segment)</p>
```

While the empty path child redirect is somewhat similar to #10726 but slightly different. In this case, I'm not sure the empty path parent with an empty path child redirect in the secondary outlet is a good idea - this effectively creates a situation where you would not be able to close the outlet. If you have a burning desire to see this added, please submit a new issue that is specific to that request.

**Closed by atscott** 2020-11-17 19:13 UTC
Labels: P3, comp: router, freq2: medium, router: URL parsing/generation, router: aux routes, state: confirmed, triage #1, type: bug/fix
