### ISSUE TITLE
Using ComponentResolver and ViewContainerRef as a replacement for DynamicComponentLoader fails. 

### ISSUE THREAD

**Issue by borangejabil** [angular/angular#9915] opened 2016-07-08 14:39 UTC
I am not trying to annoy anyone by posting this issue right on top of #9877, but I did include a variation of the code that used the ComponentResolver and ViewContainerRef  instead of DynamicComponentLoader.loadNextToLocation(...), which produced an error that was virtually identical to the original error. 
I realize that my previous post was lengthy, so I will post just that code and error. 

I am really hoping that you guys can either point out what I am doing wrong or point me to an article/sample that shows the correct way to use the ComponentResolver and ViewContainerRef. 

**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Using the ComponentResolver and ViewContainerRef in place of DynamicComponentLoader.loadNextToLocation(...) as part of an upgrade from beta 13 to RC 4 does not work. It throws an error. 
Here is the code and the error: 

(SinnerService.ts):
--------------------------------------------------------------------------------------------------------

	import {Injectable, DynamicComponentLoader, ApplicationRef, ViewContainerRef, Component, ComponentRef, ComponentResolver, ComponentFactory, ViewChild} from '@angular/core';

	import {Spinner} from './spinner';

	@Injectable()
	export class SpinnerService {
		spinnerComp: ComponentRef<any>;

		constructor(private _componentLoader: DynamicComponentLoader, private _appRef: ApplicationRef,
					private _resolver: ComponentResolver) {
		}

		public start() {
			let elementRef: ViewContainerRef = this._appRef['_rootComponents'][0].location;

			return this.startInside(elementRef, null);
		}

		public startInside(elementRef: ViewContainerRef, anchorName: string) {

			//let spinnerRef = (!anchorName) ?
			//    this._componentLoader.loadNextToLocation(Spinner, elementRef) :
			//    this._componentLoader.loadNextToLocation(Spinner, elementRef);

			//spinnerRef.then((compRef: ComponentRef<any>) => {
			//    this.spinnerComp = compRef;
			//});

			let spinnerRef = this._resolver.resolveComponent(Spinner);

			spinnerRef.then((factory: ComponentFactory<any>) => {
				this.spinnerComp = elementRef.createComponent(factory)
			});
		}

		public stop() {
			if (this.spinnerComp) {
				this.spinnerComp.destroy();
			}
		}
	}
--------------------------------------------------------------------------------------------------------

The error: 
--------------------------------------------------------------------------------------------------------
	EXCEPTION: Error: Uncaught (in promise): TypeError: 
	elementRef.createComponent is not a function	
	browser_adapter.ts:82

	EXCEPTION: Error: Uncaught (in promise): TypeError: 
	elementRef.createComponent is not a function	BrowserDomAdapter.logError @ browser_adapter.ts:82	browser_adapter.ts:82
	STACKTRACE:BrowserDomAdapter.logError @ browser_adapter.ts:82
		browser_adapter.ts:82

	Error: Uncaught (in promise): TypeError: 
	elementRef.createComponent is not a function
	at resolvePromise (zone.js:538)
	at zone.js:574
	at ZoneDelegate.invokeTask (zone.js:356)
	at Object.onInvokeTask (ng_zone_impl.ts:61)
	at ZoneDelegate.invokeTask (zone.js:355)
	at Zone.runTask (zone.js:256)
	at drainMicroTaskQueue (zone.js:474)
	at XMLHttpRequest.ZoneTask.invoke (zone.js:426)
	BrowserDomAdapter.logError @ browser_adapter.ts:82
		zone.js:461 

	Unhandled Promise rejection: elementRef.createComponent is not a 
	function ; Zone: angular ; Task: Promise.then ; Value: TypeError: 
	elementRef.createComponent is not a function(…)		consoleError @ zone.js:461
		zone.js:463 

	Error: Uncaught (in promise): TypeError: elementRef.createComponent is 
	not a function(…)	consoleError @ zone.js:463
		SignalRService.js:40 Event hub started.
--------------------------------------------------------------------------------------------------------

**Expected/desired behavior**
Prior to this modification, using the DynamicComponentLoader.loadNextToLocation(...) with ElementRef worked perfectly. The spinner was added to the DOM on whatever page was loading data while the data was loading, and then removed when the data loaded.

**What is the motivation / use case for changing the behavior?**
The behavior isn't changing. I want it to work as it did prior to the deprecation of the DynamicComponentLoader. 

**Please tell us about your environment:**

*Angular version:* 2.0.0-rc.4

*Browser:* [Chrome Latest Version ]

*Language:* [TypeScript]

**Comment by ericmartinezr** [comment] 2016-07-08 16:03
See https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

**Comment by borangejabil** [comment] 2016-07-08 16:42
Are you pointing me to that because it says Angular 2 is still under development?

I am okay if this feature is not ready for use. Is that what you are telling me?

This is a bit confusing since the deprecated version worked. 

I understand you guys are dealing with a lot of issues as well as development. I just want some clear guidance here, especially if my code simply isn't correct.

**Comment by zoechi** [comment] 2016-07-08 16:44
You didn't provide a Plunker and there are also not many known issues about `ViewContainerRef.createComponent`even though it is heavily used. Therefore it looks like your issue is a support question where GitHub issues is not the right place and the question should be posted in one of the channels mentioned in https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

**Comment by borangejabil** [comment] 2016-07-08 16:58
Okay. 
I posted it as a bug because the previous version worked and now it's broken. To me that's a bug, not a question, though I was hoping that I could get some advice if I wasn't using the component properly. However, that isn't what you are telling me. Also, on my original post I received a response that said I should use a alternate method that was actually listed in the examples that I posted. 

Sorry that i was unable to produce a Plunker to demonstrate the problem. I can work on that if it would help. The project I am working on is too large to include on such an example.

I did read many pages about the subject for several days before posting the issue here, including the ones you are pointing out to me. So, I did see that there are many issues surrounding the code that I am trying to use. 
I also tried many ways to fix the issue, instead of immediately posting it as bug. 
I will post my issue there, even though I still strongly feel that this is a bug and not a question.

**Comment by borangejabil** [comment] 2016-07-08 17:05
Also, part of the complexity of reproducing this in a small example (Plunker) is that the use of the "spinner" on a page occurs when data is being fetched, which is the whole reason to have the "spinner" in the first place. So, I will have to try to mock that in small, working, meaningful example.

**Comment by thelgevold** [comment] 2016-07-08 18:09
This is not the same use case, but this was migrated from DynamicComponentLoader a while back.
http://www.syntaxsuccess.com/viewarticle/loading-components-dynamically-in-angular-2.0

Posting in case there are clues that you may find helpful here.

**Comment by borangejabil** [comment] 2016-07-08 18:44
Thank you ! 
I didn't see that in my search earlier. 
Clues always help.

**Comment by borangejabil** [comment] 2016-07-18 15:34
Unfortunately, once you break it down, this article demonstrates the same code I was using above. 
Thanks for attempting to help me anyway @thelgevold

**Comment by pkozlowski-opensource** [comment] 2016-08-01 08:30
> Sorry that i was unable to produce a Plunker to demonstrate the problem. I can work on that if it would help. The project I am working on is too large to include on such an example.

If you would post a _minimal_ plunker people could modify it for you to demonstrate usage of `ComponentResolver` + `ViewContainerRef`. Otherwise we are all producing prose here and arguing if this is a bug or not. The reality is that we don't know till we've got a reproduce scenario.

> Also, part of the complexity of reproducing this in a small example (Plunker) is that the use of the "spinner" on a page occurs when data is being fetched, which is the whole reason to have the "spinner" in the first place. So, I will have to try to mock that in small, working, meaningful example.

I'm sure that there are many ways to simulate data fetching, ex. using setTimout.

In any case this is not actionable till we've got a minimal reproduce scenario in a plunker.

**Comment by pkozlowski-opensource** [comment] 2016-08-06 15:05
Closing as we don't have any live reproduce scenario.

**Closed by pkozlowski-opensource** 2016-08-06 15:05 UTC
Labels: comp: core, flag: can be closed?
