### ISSUE TITLE
Cannot navigate to aux route that is a child of a componentless parent

### ISSUE THREAD

**Issue by akorchev** [angular/angular#12086] opened 2016-10-05 07:09 UTC
**I'm submitting a ...**  (check one with "x")

```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I am trying to activate a child aux route. Here is the routing config:

``` JavaScript
export const routes: Routes = [
  {
    path: '',
    children: [
      { path: '', redirectTo: 'component-one', pathMatch: 'full' },
      { path: 'component-one', component: ComponentOne },
      { path: 'component-two', component: ComponentTwo }
      { path: 'component-aux', component: ComponentAux, outlet: 'sidebar' }
    ]
  }
];
```

When I try to navigate to `/component-one(outlet:component-aux)` I get `Cannot match any routes: 'component-aux'`. 

**Expected behavior**

Navigate to that route without any errors.

**Minimal reproduction of the problem with instructions**

1. Go to https://plnkr.co/edit/jVjS8tRSLbhpTO9qRxll?p=preview
2. Click the 'navigate' button

**What is the motivation / use case for changing the behavior?**

This looks as a valid routing configuration that should be supported.

**Please tell us about your environment:**

- **Angular version:** 2.0.X
  
  
- **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
  
  
- **Language:** [all | TypeScript X.X | ES6/7 | ES5]
- **Node (for AoT issues):** `node --version` =

**Comment by atscott** [comment] 2020-05-21 20:46
This appears to be a duplicate of #10726

**Closed by atscott** 2020-05-21 20:46 UTC
Labels: comp: router, freq1: low, router: aux routes, severity3: broken, type: bug/fix

**Comment by wynfred** [comment] 2020-05-21 21:40
@atscott Hi, could you please unlock the comment in the linked issue since it's reopened?

**Comment by atscott** [comment] 2020-05-21 21:46
> @atscott Hi, could you please unlock the comment in the linked issue since it's reopened?

Done, good catch.
