### ISSUE TITLE
routerLink does not use state-input on doubleclick

### ISSUE THREAD

**Issue by jonasborsch** [angular/angular#29590] opened 2019-03-29 16:15 UTC
# 🐞 bug report

### Affected Package
@angular/router

### Is this a regression?
I can't tell if it worked in a previous version.

### Description

Hello,

I have a application, where I transfer some data through the routerLinks state-input.
At the NavigationEnd event or with the router.lastSuccessfulNavigation I extract the extras and read out the state.
This works fine when clicking on a link one time. If you click more then one time (e.g. doubleclick) the state will be ignored.

Take a look at the stackblitz, I hope this will make clear whats the problem.

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-jabnva?file=src%2Fapp%2Fapp.component.ts

## 🔥 Exception or Error
there is no exception

## 🌍  Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 7.3.3
Node: 8.11.3
OS: win32 x64
Angular: 7.2.6
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.3
@angular-devkit/build-angular     0.13.3
@angular-devkit/build-optimizer   0.13.3
@angular-devkit/build-webpack     0.13.3
@angular-devkit/core              7.3.3
@angular-devkit/schematics        7.3.3
@angular/cdk                      7.3.3
@angular/cli                      7.3.3
@angular/material                 7.3.3
@ngtools/webpack                  7.3.3
@schematics/angular               7.3.3
@schematics/update                0.13.3
rxjs                              6.4.0
typescript                        3.2.4
webpack                           4.29.0
</code></pre>

**Anything else relevant?**
Tested in Chrome 73

**Comment by Airblader** [comment] 2019-03-29 17:10
Might be a duplicate of #29389

**Comment by jasonaden** [comment] 2019-04-01 17:43
Thanks for the issue. Looks like a duplicate of #29389, so please look there for updates.

**Closed** 2019-04-01 17:43 UTC
