### ISSUE TITLE
Dynamic router-outlets

### ISSUE THREAD

**Issue by olegdunkan** [angular/angular#12629] opened 2016-10-31 13:04 UTC
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

Let say we have this code:
````
@Component({
    selector:'my-app',
    template:`
    <h2>Chess</h2>
    <router-outlet [attr.name]="'a'"></router-outlet>
    <router-outlet [attr.name]="'b'"></router-outlet>
    <router-outlet *ngFor="let name of ['c', 'd']" [attr.name]="name"></router-outlet>
`
})
class Chess {}

````
It doesn't work and it is right. Attribute in router-outlet directive is like a 'const' modifier in typescript. You can set it only manually in a template. 
But what if I develop application and set routes and outlets dynamically. How expensive it will be to allow router-outlet directive to be dynamic?

**Comment by vsavkin** [comment] 2016-10-31 23:43
It should work once the following is implemented:
 https://github.com/angular/angular/issues/12522

**Comment by chenyingyin** [comment] 2016-12-01 04:06
![default](https://cloud.githubusercontent.com/assets/24284270/20781541/96040d9a-b7be-11e6-87e3-5218d38ccb81.png)
![Uploading 图片.png…]()

**Comment by atscott** [comment] 2021-09-15 18:54
Closing as duplicate of #12522

**Closed by atscott** 2021-09-15 18:54 UTC
Labels: feature, comp: router, insufficient votes, votes required
