### ISSUE TITLE
Pipe arguments don't work with ngFor*

### ISSUE THREAD

**Issue by tbosch** [angular/angular#9062] opened 2016-06-07 16:21 UTC
This does no longer work:
```
<div *ngFor="let item of items | somePipe:'testArg'>"
```

Reason: we are removing all `:` inside of expressions of `*...` attributes in the `TemplateParser`. This was introduced by https://github.com/angular/angular/commit/53628e19ac902a73b47cfe617ca3ed3bd3d7cc9e resp #6038 in an attempt to solve #5894

**Comment by DzmitryShylovich** [comment] 2016-10-20 17:42
Cannot reproduce http://plnkr.co/edit/pxL7wYp8pKQA84VlLYws?p=preview
Can be closed

**Comment by vicb** [comment] 2016-10-21 05:10
@DzmitryShylovich thanks for your help.

Details:
see in the original comment `This was introduced by 53628e1 resp #6038 in an attempt to solve #5894`
#5894 has been closed but the fix had to be reverted (because it introduced this issue).
The fix has been reverted and 589a still have to be fixed in a proper way.

**Closed by vicb** 2016-10-21 05:10 UTC
Labels: comp: core & compiler, flag: can be closed?, type: bug
