### ISSUE TITLE
Disabled input considered as invalid in dynamic form

### ISSUE THREAD

**Issue by Supamiu** [angular/angular#11432] opened 2016-09-08 08:24 UTC
**I'm submitting a ...**
```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**

If you create a disabled field in a formGroup, even with no validators, the control for this field will be invalid.

**Expected behavior**

The control should be valid since the field's property can't be changed (the field is disabled, it's only shown for read-only informations).

**Reproduction of the problem**
http://plnkr.co/edit/qSDnD2xWWUwafyToDNX1?p=preview

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.6
 
* **Browser:** Chrome 51.0.2704.84 (64-bit)
 
* **Language:** TypeScript 1.8.10

**Comment by pkozlowski-opensource** [comment] 2016-09-08 09:01
I believe that it was already fixed in master via 043493cb624ee5453391cb2fd9d074ce4232d5e9

**Closed by pkozlowski-opensource** 2016-09-08 09:01 UTC

**Comment by VirrageS** [comment] 2016-09-08 09:32
Correct me if I am wrong but this fix does not seem to touch the issue, because in test it is expected from form to be invalid (valid == false):

https://github.com/angular/angular/commit/043493cb624ee5453391cb2fd9d074ce4232d5e9#diff-21c904db79b2d5700ba92e7461b47c87R62

**Comment by pkozlowski-opensource** [comment] 2016-09-08 09:40
> because in test it is expected from form to be invalid (valid == false):

The test expects this since we are adding a control that doesn't pass validation.

**Comment by VirrageS** [comment] 2016-09-08 09:47
Sure, but as OP pointed out disabled inputs should be considered valid. Also even the validator is not added form will not be valid.

I think that the issue here is because 'DISABLED' and 'VALID' is using the same variable (https://github.com/angular/angular/blob/master/modules/%40angular/forms/src/model.ts#L89) which can not be both at the same time.

Probably there is a reason why it is the way it is.

**Comment by pkozlowski-opensource** [comment] 2016-09-08 09:51
> I think that the issue here is because 'DISABLED' and 'VALID' is using the same variable (https://github.com/angular/angular/blob/master/modules/%40angular/forms/src/model.ts#L89) which can not be both at the same time

This is by design. A control that is disabled is ... well - disabled. It is not considered valid or invalid.

**Comment by Supamiu** [comment] 2016-09-08 11:21
> A control that is disabled is ... well - disabled. It is not considered valid or invalid. 

Problem is that the boolean member `valid` has to be true or false. 
So if you want to be able to consider disabled input you have to check if the input is disabled before checking its control, it seems a bit strange to me that you have to check if the input is enabled before checking its control, the control should be valid if it is disabled, else, what's the purpose of the `disabled` parameter passed to `FormControl`'s constructor?

**Comment by pkozlowski-opensource** [comment] 2016-09-08 12:46
> Problem is that the boolean member valid has to be true or false. 

Sure. But it will be `false`. Same goes for `invalid`

> So if you want to be able to consider disabled input you have to check if the input is disabled before checking its control, it seems a bit strange to me that you have to check if the input is enabled before checking its control,

Or use alternative (more sensible, IMO) approach: http://plnkr.co/edit/9Xjg7fmWE3kFavVcS7Dx?p=preview

> the control should be valid if it is disabled,

That's not the current design. I will let @kara comment more but here is my thinking: if a control is disabled a user can't interact with it. Since a user can't interact with the control it can't change control's value. So what is the point of validating sth that can't happen?

I can see 2 different design (disabled and valid / invalid being separate flags) but I don't think one is necessarily better than the other. 

> what's the purpose of the disabled parameter passed to FormControl's constructor?

My understanding is that it means "make the control _initially_" enabled / disabled depending on the flag. Once again, there is no point of kicking off validation if a user can't interact with the control. The whole purpose of validation is to determine if _user's input_ is valid or not. If we've got no input we can't talk about validation result really.

**Comment by Supamiu** [comment] 2016-09-08 13:15
As I described in my [StackOverflow question on this problem](http://stackoverflow.com/questions/39374289/disabled-input-validation-in-dynamic-form), a warning is shown if you want to disable input using HTML disabled attribute. This warning says :
> We recommend using this approach to avoid 'changed after checked' errors.

So either this warning should be changed, or the control should be valid if the input is disabled.

>So what is the point of validating sth that can't happen?
I think that the point is to be able to create every control with the same logic, and let the control decide if the provided value is valid or not.

**Comment by kara** [comment] 2016-09-08 17:17
As @pkozlowski-opensource mentioned, this is by design.  There are four mutually-exclusive statuses:

**VALID**:  control has passed all validation checks
**INVALID**: control has failed a validation check
**PENDING**: control is in the midst of conducting a validation check
**DISABLED**: control is exempt from validation checks

Like in native HTML5 forms, disabled controls are not considered when calculating the value or validity of their parent form. As such, they are exempt from validation, and it doesn't make sense to mark the individual control as valid or invalid.  If we were to do that, we'd break the model where a parent's status is simply a reduction of the statuses of its children. Currently, a parent group is invalid if any of its children are invalid.  If the individual control was allowed to be disabled *and* invalid, you'd get the following confusing behavior:

```ts
this.form.get('login').status           // INVALID
this.form.status                        // INVALID

this.form.get('login').disable();

this.form.get('login').status           // INVALID
this.form.status                        // VALID
```

You might want to take a look at the doc for disabled controls for more info:
https://docs.google.com/document/d/1k_iYcgTS1cDJkyXvBWQZGPlkWZhEqAVphC0xyKSAqPs/preview

**Comment by Supamiu** [comment] 2016-09-09 07:30
Ok, so I think the cookbook on Dynamic forms needs a little tweaking because it's marking each field valid or not, based on the control value. That's why I thought it was the good way to do, but seems like it's not.

Thank you.

**Comment by MosheMoualem** [comment] 2018-02-28 19:40
Thanks Kara, Understood your example and it's clear, but what about the other way around ?
I'm mean lets say we have somewhere in the formGroup tree a parent which is disabled 
and one of it's ancestors are not valid, I would expect that the form will be valid..  which is no the case here,  the form is invalid. please advise how to handle.

**Comment by AhmedBHameed** [comment] 2018-05-04 15:51
Hmmm, I agree with @pkozlowski-opensource , so i'd like to show you my case scenario here, please have a look to the GIF bellow.
![GIF](https://i.imgur.com/dEUfvmY.gif)

In this case i want to give user the ability to select address automatically using checkbox, Reactive form updated by using `patchValue()` method, then I used `disabled` method to prevent any changes from the user UI.

the problem I always get `valid: false` so I thing that if the field is disabled, the valid flag should be true to prevent showing up error validation as my small bar on the right popup.

Also i have to mention that this field is `Validators.required` but even after updating it's value and disable it i get `valid: false` which is weird!!

**Comment by patryknut** [comment] 2018-10-02 09:45
@kara @pkozlowski-opensource 

Can you comment on @AhmedBHameed scenario? I am facing the same problem.

**Comment by chiranthaw** [comment] 2018-10-02 12:39
Yes using readonly will slove it. But whats the workaround for "select" controls?

**Comment by Gil-Epshtain** [comment] 2018-10-07 14:45
ReadOnly is not the same as Disabled. The Disabled status will add some style showing the user that control isn't usable. While the ReadOnly control is displayed the same as Editable control. Therefore using ReadOnly isn't a good workaround.

**Comment by jonathanjouret-ls** [comment] 2018-12-05 11:45
Hi there,

Any update on that? I'm facing the same issue using angular 6.0.3

`"@angular/animations": "6.0.3",
    "@angular/common": "6.0.3",
    "@angular/compiler": "6.0.3",
    "@angular/compiler-cli": "6.0.3",
    "@angular/core": "6.0.3",
    "@angular/forms": "6.0.3",
    "@angular/http": "6.0.3",
    "@angular/platform-browser": "6.0.3",
    "@angular/platform-browser-dynamic": "6.0.3",
    "@angular/platform-server": "6.0.3",
    "@angular/router": "6.0.3",`

Thanks 😄

**Comment by jonathanjouret-ls** [comment] 2018-12-13 15:02
In your case, I think the "readonly" work around is ok as it's not really disabling the previous answers that you need but making sure that the user can't change them... 

I haven't found a proper workaround this yet but still hope the angular team will propose some solution...

**Comment by Tomas-Tr** [comment] 2019-01-03 12:40
As per W3C standard, disabled controls, cannot be successful (are not valid):
https://www.w3.org/TR/html401/interact/forms.html#disabled

**Comment by WizardPC** [comment] 2019-01-03 12:51
Doesn't mean it's always unsuccessful. 

> In this example, the INPUT element is disabled. Therefore, it cannot receive user input nor will its value be submitted with the form.

We can interprete it with "if it's disabled, i won't be in the form, so... the form won't check it"
