### ISSUE TITLE
ng xi18n --ivy doesn't extract strings from 3rd party libraries

### ISSUE THREAD

**Issue by kamilchlebek** [angular/angular#39386] opened 2020-10-22 13:31 UTC
# 🐞 bug report

### Affected Package
The issue is caused by package `@angular/localize`

### Is this a regression?

Yes, it works without `--ivy` option

### Description

I'm using `ng-bootstrap`. When I run `ng xi18n` without `--ivy`, the tool does extract strings from my app and the library (ng-bootstrap). As a result, `messages.xlf` contains entries like:
```
...
<trans-unit id="ngb.timepicker.PM" datatype="html">
   <source><x id="INTERPOLATION" equiv-text="{{ i18n.getAfternoonPeriod() }}"/></source>
      <context-group purpose="location">
         <context context-type="sourcefile">node_modules/@ng-bootstrap/ng-bootstrap/timepicker/timepicker.d.ts</context>
         <context context-type="linenumber">76</context>
     </context-group>
</trans-unit>
...
```

When I run `ng xi18n --ivy`, these trans-units are missing.

## 🔬 Minimal Reproduction

https://github.com/kamilchlebek/i18n-ivy-es5/tree/ng-bootstrap

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 10.1.7
Node: 12.16.1
OS: linux x64

Angular: 10.2.0
... animations, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1001.7
@angular-devkit/build-angular   0.1001.7
@angular-devkit/core            10.1.7
@angular-devkit/schematics      10.1.7
@angular/cli                    10.1.7
@schematics/angular             10.1.7
@schematics/update              0.1001.7
rxjs                            6.5.5
typescript                      3.9.7
</code></pre>

**Anything else relevant?**

_I'm using target:es2015 ofc._

**Comment by petebacondarwin** [comment] 2020-10-22 13:49
This is a duplicate of https://github.com/angular/angular-cli/issues/18871 in the Angular CLI project. 
It was fixed via https://github.com/angular/angular-cli/pull/18887 but is not backported to 10.x.
So it should work for you from 11.0.0 onwards. You can try updating your project to the prerelease version of 11
by `ng update @angular/cli --next`.

**Closed by petebacondarwin** 2020-10-22 13:49 UTC
Labels: comp: i18n

**Comment by kamilchlebek** [comment] 2020-10-22 14:09
Perfect! Thank you for quick response.
