### ISSUE TITLE
[Ivy Mode] "ng build" and "ng serve" error under Ivy mode  in angular 8 beta 

### ISSUE THREAD

**Issue by Nguyendangthe** [angular/angular#29363] opened 2019-03-18 03:28 UTC
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

Please file any Angular CLI issues at: https://github.com/angular/angular-cli/issues/new

For the time being, we keep Angular CLI issues in a separate repository.

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by Nguyendangthe** [comment] 2019-03-18 03:37
Hi, I have upgraded my angular application from angular 7 to angular 8 beta 8, if I disable "enableIvy" property in tsconfig.app.json my app can build prod and serve like a normal, but if I enable "enableIvy"  I can not serve or build with a same error :
`ERROR in Failed to list lazy routes: Unknown module 'D:/FMS WEB PROJECT/eFMS-WebApp/WebApp/src/app/app.module#AppModule'.`

package.json :
```
{
  "name": "e-fms-web",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^8.0.0-beta.8",
    "@angular/common": "^8.0.0-beta.8",
    "@angular/compiler": "^8.0.0-beta.8",
    "@angular/core": "^8.0.0-beta.8",
    "@angular/forms": "^8.0.0-beta.8",
    "@angular/http": "^7.1.4",
    "@angular/platform-browser": "^8.0.0-beta.8",
    "@angular/platform-browser-dynamic": "^8.0.0-beta.8",
    "@angular/platform-server": "^8.0.0-beta.8",
    "@angular/pwa": "^0.11.4",
    "@angular/router": "^8.0.0-beta.8",
    "@angular/service-worker": "^7.1.4",
    "@ngtools/webpack": "^7.3.5",
    "@ngx-progressbar/core": "^5.3.1",
    "@types/jquery": "^3.3.29",
    "angular-oauth2-oidc": "^5.0.2",
    "bootstrap": "^4.1.3",
    "core-js": "^2.6.5",
    "crypto-js": "^3.1.9-1",
    "exceljs": "^1.6.3",
    "file-saver": "^2.0.0",
    "i18n": "^0.8.3",
    "jquery": "^3.3.1",
    "lodash": "^4.17.11",
    "moment": "^2.22.2",
    "ng2-select": "^2.0.0",
    "ngx-cookie-service": "^2.0.0",
    "ngx-daterangepicker-material": "^1.2.4",
    "ngx-perfect-scrollbar": "^7.0.0",
    "ngx-spinner": "^6.1.2",
    "ngx-toastr": "^9.1.0",
    "rxjs": "^6.4.0",
    "typescript-string-operations": "^1.3.1",
    "validator": "^10.8.0",
    "zone.js": "^0.8.29"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.800.0-beta.7",
    "@angular/cli": "^8.0.0-beta.7",
    "@angular/compiler-cli": "^8.0.0-beta.8",
    "@angular/language-service": "^8.0.0-beta.8",
    "@types/crypto-js": "^3.1.43",
    "@types/exceljs": "^0.5.2",
    "@types/file-saver": "^2.0.0",
    "@types/jasmine": "^3.3.9",
    "@types/jasminewd2": "~2.0.3",
    "@types/lodash": "^4.14.118",
    "@types/node": "^11.11.3",
    "@types/validator": "^9.4.3",
    "codelyzer": "^5.0.0-beta.1",
    "jasmine-core": "^3.3.0",
    "jasmine-spec-reporter": "^4.2.1",
    "karma": "^4.0.1",
    "karma-chrome-launcher": "^2.2.0",
    "karma-cli": "^2.0.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "^2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "node-sass": "^4.11.0",
    "protractor": "^5.4.2",
    "rxjs-tslint": "^0.1.7",
    "source-map-explorer": "^1.6.0",
    "ts-node": "~7.0.0",
    "tslint": "^5.14.0",
    "typescript": "^3.1.6",
    "webpack": "^4.29.6"
  }
}
```

app.module.ts:
```
@NgModule({
  declarations: [
    AppComponent,
    LoginComponent,
    MasterPageComponent,
    NotfoundPageComponent,
    HeaderComponent,
    FooterComponent,
    PageSidebarComponent,
    SubheaderComponent
    // TwoDigitDecimaNumberDirective
  ],
  imports: [    
   // ServiceWorkerModule.register('ngsw-worker.js', { enabled: true}),
    SharedModule,
    CommonModule,
    BrowserModule,
    AppRoutingModule,
    FormsModule,
    HttpModule,
    HttpClientModule,
    BrowserAnimationsModule, // required animations module
    ToastrModule.forRoot(), // ToastrModule added
    NgxSpinnerModule,
    NgProgressModule,
    PerfectScrollbarModule,
    SelectModule, // Scrollbar
    OAuthModule.forRoot()
  ],
  providers: [
    AuthGuardService,
    BaseService,
    CookieService ,
    PagingService,
    { 
      provide: PERFECT_SCROLLBAR_CONFIG, // Scrollbar
      useValue: DEFAULT_PERFECT_SCROLLBAR_CONFIG // Scrollbar
    }
  ],
  bootstrap: [AppComponent],
  exports:[]
})
export class AppModule { }
```

angular version:
```
Angular CLI: 8.0.0-beta.7
Node: 10.5.0
OS: win32 x64
Angular: 8.0.0-beta.8
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.0-beta.7
@angular-devkit/build-angular     0.800.0-beta.7
@angular-devkit/build-optimizer   0.800.0-beta.7
@angular-devkit/build-webpack     0.800.0-beta.7
@angular-devkit/core              8.0.0-beta.7
@angular-devkit/schematics        7.1.4
@angular/cli                      8.0.0-beta.7
@angular/http                     7.1.4
@angular/pwa                      0.11.4
@angular/service-worker           7.1.4
@ngtools/webpack                  7.3.6
@schematics/angular               7.1.4
@schematics/update                0.800.0-beta.7
rxjs                              6.4.0
typescript                        3.1.6
webpack                           4.29.6
```

**Comment by jloosli** [comment] 2019-03-19 23:01
For what it's worth, I've got the same issue. I have noticed though that I can get `ng watch` to work by doing the following:
* Run `ng watch`
* Wait for the error
* Make some sort of change, which triggers a rebuild
* App compiles successfully (including being able to navigate to all the lazy loaded routes)

**Comment by brannon-darby** [comment] 2019-04-03 18:22
I found this very useful for fixing my setup:

https://next.angular.io/guide/ivy

**There is a new way to define lazy routes:**
```
const routes: Routes = [{
  path: 'lazy',
  // The string syntax for loadChildren is not supported in Ivy:
  //   loadChildren: './lazy/lazy.module#LazyModule'
  // Instead use the import statement:
  loadChildren: () => import('./lazy/lazy.module').then(m => m.LazyModule)
}];
```

**Add `"aot": true` in build.options: **
```
{
  "projects": {
    "my-existing-project": {
      "architect": {
        "build": {
          "options": {
            ...
            "aot": true,
          }
        }
      }
    }
  }
}
```

It's probably worth noting that the current `angular.json` output for `ng new ivy-ws --enable-ivy=true` does not include `"aot": true` in build.options for the generated app - not sure if that's intentional or not.

@JoostK @jasonaden

**Comment by jimmykane** [comment] 2019-05-30 19:20
Hi I dont have lazy routes and I also get this error

**Comment by jimmykane** [comment] 2019-05-30 19:22
```
import {NgModule} from '@angular/core';
import {RouterModule, Routes} from '@angular/router';
import {DashboardComponent} from './components/dashboard/dashboard.component';
import {HomeComponent} from './components/home/home.component';
import {EventCardComponent} from './components/cards/event/event.card.component';
import {AppAuthGuard} from './authentication/app.auth.guard';
import {LoginComponent} from './components/login/login.component';
import {UserComponent} from './components/user/user.component';
import {ServicesComponent} from "./components/services/services.component";

const routes: Routes = [
  {path: 'home', component: HomeComponent, data: {title: 'Home'}},
  {path: 'services', component: ServicesComponent, data: {title: 'Services'}},
  // {path: '', redirectTo: 'home', pathMatch: 'full'},
  {path: 'login', component: LoginComponent, data: {title: 'Login'}},
  {path: 'dashboard', component: DashboardComponent, data: {title: 'Dashboard'}, canActivate: [AppAuthGuard]},
  {path: 'user/:userID/event/:eventID', component: EventCardComponent, data: {title: 'Details'}},
  {path: 'user/:userID', component: UserComponent, data: {title: 'User'}},
  {path: '**', redirectTo: 'home', pathMatch: 'full' },
];

@NgModule({
  imports: [RouterModule.forRoot(routes)],
  exports: [RouterModule],
})

export class AppRoutingModule {
}

``` 

This is my routing module and I get this error

**Comment by spyter** [comment] 2019-06-03 16:49
I am having the same issue as @jimmykane. I'm also not using lazy loading.

**Comment by roytouw** [comment] 2019-06-05 10:43
I am also having this issue when enableIvy is set to true, having this flag on false it compiles just fine.

**Comment by Flynnp25** [comment] 2019-06-07 11:37
Im also having this issue.
I have enabled IVY but am not using lazy loading

**Comment by wuboy0307** [comment] 2019-07-25 04:20
Version 8.2.0-next.1 is fine. but using version 8.2.0-next.2 I also get Failed to list lazy routes: Unknown module AppModule

**Comment by bschauhan** [comment] 2019-08-14 11:39
Hi I dont have routes in my project and I also get this error

**Comment by JohanMouritsen** [comment] 2019-09-19 10:02
i was getting this error after modifying my tsconfig.app.json wrong. this is what my now correct tsconfig.app.json looks like:
```
{
    "extends": "../tsconfig.json",
    "compilerOptions": {
        "outDir": "../out-tsc/app",
        "types": []
    },
    "files": [
        "main.ts",
        "polyfills.ts"
    ],
    "include": [
        "*.ts"
    ],
    "exclude": [
        "test.ts",
        "**/*.spec.ts"
    ]
}
```

**Comment by avatsaev** [comment] 2019-09-26 09:54
I'm having the same error, nothing from this thread helped

**Comment by felikf** [comment] 2019-10-08 06:43
I hit same issue and helped to remove `include` and `files`:

tsconfig.app.json:

```
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc/app",
    "types": []
  },
  "exclude": [
    "src/wallabyTest.ts",
    "src/jestGlobalMocks.ts",
    "**/*.spec.ts"
  ],
  "angularCompilerOptions": {
    "enableIvy": true
  }
}
```

tsconfig.json:

```
{
  "compileOnSave": false,
  "compilerOptions": {
    "downlevelIteration": true,
    "module": "esnext",
    "outDir": "./dist/out-tsc",
    "baseUrl": "./src",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "types": ["jest"],
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2017",
      "dom"
    ]
  }
}
```

**Comment by artbelikov** [comment] 2019-12-29 14:18
For me the problem was in tsconfig.app.json. Incorrect relative paths.

**Comment by petebacondarwin** [comment] 2020-01-21 09:04
Closing as it appears that a number of the causes of this error are invalid TS configuration. Is that reasonable? If you are still experiencing this problem, please open a new issue with a simple reproduction of the error using the latest v9 release candidate.

**Closed by petebacondarwin** 2020-01-21 09:04 UTC
Labels: comp: ivy
