### ISSUE TITLE
Check for presence of validator

### ISSUE THREAD

**Issue by kara** [angular/angular#22422] opened 2018-02-23 22:52 UTC
Currently, it's pretty hard to check if a validator has been added in a reactive form because of the way that validators are composed into one function. It would be handy to be able to check this somehow for cases like the "required" asterisk and related error handling in MdInput: https://www.google.com/url?q=https://github.com/angular/material2/issues/2574&sa=D&usg=AFQjCNEbvHIEhnloF1_8nWmYdyylmPOQIQ

**Comment by mrtpain** [comment] 2019-03-05 02:22
@kara @vicb Is it possible to get an update on this? Was a work around found? I know it is possible to check for the required validator in Angular 7 but no others validators. It would be ideal to have the ability to check all validators applied to a form control. Below we can see the basic approach to checking if a control is required. 

```Typescript
public isRequired: boolean;

const formControl = new FormControl(
    'Initial Value', 
    [Validators.required, Validators.maxLength(50)]
);

if (formControl.validator !== null) {
    const validator = formControl.validator({} as AbstractControl);
    this.isRequired = validator.required;
}
```

The above example will find the `required` property as a boolean but will not find any other validators on the form control. Ideally I would like the ability to see an output match the example below.

```Typescript
{
    required: true,
    maxLength: 50
}
```

**Comment by AndrewKushnir** [comment] 2021-01-22 02:57
Closing as a duplicate of #13461.

**Closed by AndrewKushnir** 2021-01-22 02:57 UTC
Labels: comp: forms, feature, freq2: medium, state: Needs Design
