### ISSUE TITLE
assets folder index.html not working  

### ISSUE THREAD

**Issue by akilmakda** [angular/angular#26221] opened 2018-10-03 05:39 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Angular service worker application redirect to the not-found page or stay on that page when ngsw-config.json file like below. 

"resources": {
      "files": [
        "/favicon.ico",
        **"/index.html"**,
        "/*.css",
        "/*.js"
      ],
      "urls": [
        "https://fonts.googleapis.com/**"
      ]
}

when you hit URL 127.0.0.1:8080/assets/  it did not hit inside assets index.html file.

But when you set like below;

"resources": {
      "files": [
        "/favicon.ico",
        **"index.html",**
        "/*.css",
        "/*.js"
      ],
      "urls": [
        "https://fonts.googleapis.com/**"
      ]
}

when you hit URL 127.0.0.1:8080/assets/  it hit the inside assets index.html file. But the main index.html file does not catch and that's why offline feature not work.

## Expected behavior

when hit 127.0.0.1:8080/assets/ it hit inside index.html file

## Minimal reproduction of the problem with instructions

Demo application on git below is the link
URL: https://github.com/akilmakda/assets-index-file-not-work

## Environment

<pre><code>
Angular CLI: 6.2.3
Angular PWA: 0.6.8
Angular Service-worker: 6.0.3

Browser:
- [x] Chrome (desktop) version 69
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 9.10.1  
- Platform:  

Others:

</code></pre>

**Comment by gkalpak** [comment] 2018-10-03 10:10
AFAICT, everything works as intended. The SW is not configured to redirect `.../` requests to `.../index.html`; this is a server configuration thing.
This might be an interesting feature request though :wink: (Feel free to open an issue about that.)

##
According to the default configuration, `/assets/` is recognized as a navigation URL and `/index.html` is served instead. You can configure the SW to not consider certain URLs as "navigation URLs" (see [here][1] for more info). For example, in order to tell the SW that all paths in `/` are not navigation URLs (except for the `/` path), you can add the following in your `ngsw-config.json`:

```json
{
  ...
  navigationUrls: [
    // Default glob patterns.
    "/**",
    "!/**/*.*",
    "!/**/*__*",
    "!/**/*__*/**",
    // Not URLs ending in `/` (that have at least one non-empty path segment)
    "!/?*/**/"
  ]
}
```

_Note: In order to use `?` is glob patterns you need a recent version of `@angular/service-worker`. In older versions, `!/**/*/` would work (but it will incorrectly match `//`)._

##
Once you have configured the SW to not redirect `/assets/` to `/index.html`, it will let it pass through to the server (which will serve `/assets/index.html`). But the SW will not cache the response, so requesting `/assets/` in offline mode will not work. This is because there is no asset group configured to match `/assets/`. 

You can fix this, by configuring your asset group to also match URL patterns that include `/assets/`. E.g.:

```json
{
  ...
  "assetGroups": [
    ...
    {
      "name": "assets",
      ...
      "resources": {
        ...
        // Define URL patterns to be also matched by this group.
        "urls": [
          "/assets/"
        ]
      }
    }
  ],
  ...
```

Now, once the user has visited `/assets/` once, the SW will cache the response (as part of the `assets` asset group) and will be able to serve it when offline as well.

##
Closing, since everything works as expected. Feel free to open a feature request for defining redirection rules (for example to redirect `.../` to `.../index.html`) as mentioned above.

[1]: https://angular.io/guide/service-worker-config#navigationurls

**Closed by gkalpak** 2018-10-03 10:10 UTC
