### ISSUE TITLE
NgxQRCodeModule,

### ISSUE THREAD

**Issue by UmeshGEM** [angular/angular#36768] opened 2020-04-22 18:13 UTC
ERROR in node_modules/ngx-qrcode2/index.d.ts:3:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.

I am using NgxQRCodeModule, in my project.
this error is coming please fixed it.
please fixed it.

ngular CLI: 9.1.1
Node: 12.16.1
OS: darwin x64

Angular: 9.1.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.1
@angular-devkit/build-angular     0.901.1
@angular-devkit/build-optimizer   0.901.1
@angular-devkit/build-webpack     0.901.1
@angular-devkit/core              9.1.1
@angular-devkit/schematics        9.1.1
@angular/cli                      9.1.1
@ngtools/webpack                  9.1.1
@schematics/angular               9.1.1
@schematics/update                0.901.1
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0

**Comment by gkalpak** [comment] 2020-04-22 20:41
It is hard to tell without an actual reproduction, but from what I can tell by looking at the `ngx-qrcode2` package is that the entry-points defined in its `package.json` are invalid. More specifically: 

It specifies a [`module` entry-point][1] pointing to `./ngx-qrcode2.js`:
```json
  "module": "ngx-qrcode2.js",
  "typings": "ngx-qrcode2.d.ts",
```

But there is no `./ngx-qrcode2.js` file in the [published package][2]. It was probably supposed to point to `./index.js`.

There is actually an issue for this on their issue tracker: techiediaries/ngx-qrcode#42
The package hasn't had a release in 2 years, but there seems to be activity on that issue.

##
As a temporary workaround, you can try adding an `ngcc.config.js` file at the root of your project with the following contents:

```js
module.exports = {
  packages: {
    // `package.json > module` points to a non-existent file (`./ngx-qrcode2.js`).
    // Override it to point to the correct file. 
    'ngx-qrcode2': {
      entryPoints: {
        '.': {
          override: {
            module: './index.js',
          },
        },
      },
    },
  },
};
```

@UmeshGEM, can you try that and let us know if it worked for you?

[1]: https://unpkg.com/browse/ngx-qrcode2@0.0.9/package.json
[1]: https://unpkg.com/browse/ngx-qrcode2@0.0.9/
[3]: https://www.npmjs.com/package/ngx-qrcode2

**Comment by Netkomm** [comment] 2020-04-23 06:10
I just encountered the same issue and implemented the solution suggested by @gkalpak but it still returns the same errors.

**Comment by gkalpak** [comment] 2020-04-23 12:30
Interesting. Someone else reported that it works for them: https://github.com/techiediaries/ngx-qrcode/issues/42#issuecomment-618254856 🤷‍♂️

Anyway, it seems that this is being fixed on the library side, so I am going to close this issue: https://github.com/techiediaries/ngx-qrcode/issues/42#issuecomment-618260181

**Closed by gkalpak** 2020-04-23 12:30 UTC
Labels: comp: ngcc, state: Follow Up, type: bug/fix
