### ISSUE TITLE
Should we camelCase ng-content?

### ISSUE THREAD

**Issue by krimple** [angular/angular#6199] opened 2015-12-31 21:39 UTC
Since we're moving from kabob case for attribute-based directives, should we also change ng-content to ngContent? This tripped me up today when writing a bootstrap wrapper library.  The directives still use ng-content in beta 0.

**Comment by GaloisGirl** [comment] 2016-01-07 11:05
Duplicate of #6308

**Comment by pkozlowski-opensource** [comment] 2016-01-07 18:26
Nope. We want to keep tag names close to the web components specification which mandates `-` for custom component names.

**Closed by pkozlowski-opensource** 2016-01-07 18:26 UTC

**Comment by krimple** [comment] 2016-01-07 19:19
Gotcha, so it's just attribute names.
