### ISSUE TITLE
Simplify Parent Route Parameter Access (and params in general)

### ISSUE THREAD

**Issue by robwormald** [angular/angular#9490] opened 2016-06-22 19:08 UTC
_From @DanWahlin on June 18, 2016 4:39_

I know the API is still being worked on at this point, but I wanted to add my two cents on route parameter access and the APIs after working with them quite a bit lately. Simplifying the overall process could really be helpful. Here's one scenario I'm running into a lot involving parent route parameters that feels much too verbose currently:

**Route:**  

```
/customer/2/details
```

**Snapshot API to Get id Route Parameter:** 

```
const id = +this.router.routerState.parent(this.route).snapshot.params['id'];
```

**Observable API to Get id Route Parameter:** 

```
this.router.routerState.parent(this.route)
       .params 
       .subscribe(params => { 
           const id = +params['id'];
           //do something with id
          this.dataService.getCustomer(id)
                .subscribe((customer: ICustomer) => this.customer = customer);
       });
//With the code this way I think I'd have to unsubscribe too?
```

**Suggested API**:

I know that ActivatedRoute doesn't currently have a parent property, but something like the following would really simplify this fairly common scenario (this uses a snapshot rather than an observable):

```
//Move up to parent route and grab the id param
const id = +this.route.parent.params['id'];
```

Thanks for all the hard work on the router so far - really like the direction it's going. I just wanted to document a few ideas since the API is still being worked on and I think there are definitely some opportunities to simplify things along the way.
              

_Copied from original issue: angular/vladivostok#81_

**Comment by DzmitryShylovich** [comment] 2016-07-17 12:54
duplicate of https://github.com/angular/angular/issues/9444
@vicb I guess u can close this

**Comment by vsavkin** [comment] 2016-07-28 22:54
Dup of #9444

**Closed by vsavkin** 2016-07-28 22:54 UTC
Labels: comp: router, type: RFC / discussion / question
