### ISSUE TITLE
setDisabledState is never called when ControlValueAccessor is implemented on directive

### ISSUE THREAD

**Issue by abdulkareemnalband** [angular/angular#18480] opened 2017-08-02 12:22 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

On changing value `[disabled]` attribute on directive `setDisabledState` should be called

## Expected behavior

On changing value `[disabled]` attribute on directive `setDisabledState` is never called

## Minimal reproduction of the problem with instructions

http://plnkr.co/edit/qumGC0jO9ob9Dr4ZBW8a?p=preview

## Environment

<pre><code>
Angular version: 4.3.2

Browser:
- [x] Chrome (desktop) version 60
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by dawidgarus** [comment] 2017-08-02 15:41
`setDisabledState` works: http://plnkr.co/edit/SIAgBFcoIIwONOIuCAXq?p=preview
But it's not called when component is initialized if `disabled` value is `false`.

**Comment by moniuch** [comment] 2017-12-05 11:41
Isn't this problem related to: https://github.com/angular/angular/issues/13856 ?

**Comment by avrim** [comment] 2019-01-02 17:26
**** But it's not called when component is initialized if disabled value is false.
I Also get it, what is the status, will it be fixed?

**Comment by AndrewKushnir** [comment] 2020-05-27 21:09
Hi @abdulkareemnalband, thanks for reporting the issue. It seems like it's a duplicate of #35309. I'm closing this issue, please subscribe to #35309 for further discussion/updates. Thank you.

**Closed by AndrewKushnir** 2020-05-27 21:09 UTC
Labels: comp: forms, forms: disabling controls, freq2: medium, severity3: broken, type: bug/fix

**Comment by AccessViolator** [comment] 2020-06-10 06:06
It's not necessarily a duplicate.
I just hit this with `new FormControl({ value: '', disabled: false })` where `setDisabledState()` wasn't called with `false`
