### ISSUE TITLE
Inconsistent width of the left and right columns in the cheatsheet content

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#16102] opened 2017-04-18 17:02 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
```

**Current behavior**
Screenshot of https://aio-staging.firebaseapp.com/guide/cheatsheet:

<img width="1202" alt="screen shot 2017-04-18 at 6 59 32 pm" src="https://cloud.githubusercontent.com/assets/216296/25143090/73b906e2-2469-11e7-94a8-6ea231a20282.png">

**Expected behavior**
The two columns should have consistent width throughout the page.

**Comment by wardbell** [comment] 2017-04-18 20:07
By design. Won't fix soon.

**Comment by IgorMinar** [comment] 2017-04-24 22:33
@wardbell what do you mean? This is not acceptable. The original cheatsheet design uses consistent column widths:

<img width="1201" alt="screen shot 2017-04-25 at 12 31 56 am" src="https://cloud.githubusercontent.com/assets/216296/25361491/accc0f62-294e-11e7-8d40-1c390f031396.png">

**Comment by sjtrimble** [comment] 2017-04-26 22:55
@IgorMinar If you shrink your screen a bit (see example screenshot below), you'll note that on the current site the left column honors the width of  the `pre` code within it, and the right column adjusts based on how much space is left over all the while maintaining the margins as well as a max-width. We can gimmick the same behavior if that's ok with you? Just wanted to make sure we were on the same page that the current site doesn't actually have equal widths, but compensates when there is extra space to play with.

<img width="758" alt="screen shot 2017-04-26 at 3 49 45 pm" src="https://cloud.githubusercontent.com/assets/2958442/25460387/0b040be4-2a98-11e7-958e-b8dc699a1fd8.png">

**Comment by wardbell** [comment] 2017-05-03 07:34
I just looked again and it has changed dramatically in an adverse direction. I don't understand what happened because it looked identical to the one on angular.io.  Maybe we can do something to revert soon.

**Closed** 2017-05-04 02:34 UTC
Labels: comp: aio, type: bug
