### ISSUE TITLE
Unneccessary boilerplate with routing

### ISSUE THREAD

**Issue by damiandennis** [angular/angular#10629] opened 2016-08-10 08:37 UTC
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Currently I have to import my components for declarations in bootstrap and in my router config.

**Expected/desired behavior**
I should only have to import my declarations in my router config, The module should take care of adding the declarations.

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**
Extra work that was not needed before.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** [all] 
 
* **Language:** [all]

**Comment by choeller** [comment] 2016-08-10 08:44
I guess this is a duplicate of https://github.com/angular/angular/issues/10472

**Comment by pkozlowski-opensource** [comment] 2016-08-10 08:45
It is indeed, thnx @choeller !

**Closed by pkozlowski-opensource** 2016-08-10 08:45 UTC
