### ISSUE TITLE
@angular/elements usage with reactive formControls

### ISSUE THREAD

**Issue by echonax** [angular/angular#31351] opened 2019-06-29 12:31 UTC
# 🐞 bug report

### Affected Package
@angular/elements

### Description

I'm trying to use angular custom elements (web components) with a reactive form but i can't initialise my cva components with a default value.

Note that the component I've created implements the ControlValueAccessor interface.

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/custom-input-web-element?file=src%2Fapp%2Fapp.component.html

(Sometimes i get an error in the console, just refresh the stackblitz browser if it happens)

## 🌍  Your Environment

**Angular Version:**
<pre><code>
^8.0.0
</code></pre>

**Comment by trotyl** [comment] 2019-07-02 11:07
Duplicate of https://github.com/angular/angular/issues/29924

**Comment by gkalpak** [comment] 2019-07-02 12:03
See https://github.com/angular/angular/issues/29924#issuecomment-497106666 for more info.

**Closed by gkalpak** 2019-07-02 12:03 UTC
Labels: comp: elements

**Comment by echonax** [comment] 2019-07-04 21:01
> See [#29924 (comment)](https://github.com/angular/angular/issues/29924#issuecomment-497106666) for more info.

Thanks for the answer!

Just to point out the solution that came out of  #29924. As far as I've understood, once you convert your components into web-components, Angular kinda removes its ngModel abstraction from the CVA input elements. This means you need to cover the native <input /> element bindings manually.

Your component that implements the CVA interface should have:
```javascript
/**
 *  The native value attribute as an Angular input.
 */
@Input() value;
/**
 * The native input attribute as an Angular output.
 */
@Output() input;
```

**Comment by kavinda1995** [comment] 2019-08-27 15:24
@echonax can you show the full code of the solution? The component and it's usages 😃

**Comment by kavinda1995** [comment] 2019-08-29 08:48
Thank you @echonax for the clarification.

Fixed the error by adding the **ngDefaultControl** as a directive in the custom element and implementing the part of the ControlValueAccessor manually.

Here is an example of implementation (Don't mind the validation part, not finished yet)
[StackBlitz](https://stackblitz.com/edit/angular-elements-custom-input)
