### ISSUE TITLE
I am unable to display an "Update Available" message - Service Worker

### ISSUE THREAD

**Issue by guimaraesSalgado** [angular/angular#40048] opened 2020-12-09 18:41 UTC
I enabled the service worker in my project, but for some reason the message is not displayed, I have already configured my **ngsw-config**, when I do the local test it works, when I deploy to the server, I saw in a forum the solution to insert the url in **ngsw.json** after build but shouldn't that be done at the time of build? can you help me, what am i missing?

follow my cod

**ngsw-config**
```
{
  "$schema": "./node_modules/@angular/service-worker/config/schema.json",
  "index": "/index.html",
  "appData": {
    "name": "my sistem",
    "description": "Sistem new"
  },
  "assetGroups": [
    {
      "name": "app",
      "installMode": "prefetch",
      "updateMode": "prefetch",
      "resources": {
        "files": [
          "/favicon.ico",
          "/index.html",
          "/assets/**",
          "/*.css",
          "/*.js"
        ]
      }
    },
    {
      "name": "assets",
      "installMode": "lazy",
      "updateMode": "prefetch",
      "resources": {
        "files": [
          "/assets/**",
          "/*.(eot|svg|cur|jpg|png|webp|gif|otf|ttf|woff|woff2|ani)"
        ],
        "urls": [
          "https://fonts.googleapis.com/**"
        ]
      }
    }
  ],
  "dataGroups": [
    {
      "name": "api",
      "urls": [
        "/app/core/services/tipos-pessoas-fisicas.service*"
      ],
      "cacheConfig": {
        "strategy": "performance",
        "maxSize": 5,
        "maxAge": "30s"
      }
    }
  ],
  "navigationRequestStrategy": "freshness"
}
```

**My update service**
```
this.swUpdate.available.subscribe(event => {
      // tslint:disable-next-line: no-console
      console.log('teste', event);
      this.promptUser();
    });
 this.swUpdate.activated.subscribe(event => {
      // tslint:disable-next-line: no-console
      console.log('teste 02', event);
    });
```

**my website**
![image](https://user-images.githubusercontent.com/49767698/101672130-3f524a00-3a34-11eb-87d4-9639cff01045.png)

![image](https://user-images.githubusercontent.com/49767698/101672709-fb137980-3a34-11eb-85b5-1296801db540.png)

**Comment by AndrewKushnir** [comment] 2020-12-09 18:57
Closing as a duplicate of #40049.

**Closed by AndrewKushnir** 2020-12-09 18:57 UTC
