### ISSUE TITLE
ngcc - recover from being stopped mid-build

### ISSUE THREAD

**Issue by indraraj26** [angular/angular#36393] opened 2020-04-02 13:02 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/compiler

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 9.0.2

### Description
 It was working fine in 9.0.2.  Can someone explain me this error ?

## 🔬 Minimal Reproduction

 https://stackblitz.com/...

## 🔥 Exception or Error
<pre><code>
Compiling @ng-bootstrap/ng-bootstrap : module as esm5
Error: Tried to write D:/test/student/node_modules/@ng-bootstrap/ng-bootstrap/accordion/accordion-config.d.ts.__ivy_ngcc_bak with an ngcc back up file but it already exists so not writing, nor backing up, D:/test/student/node_modules/@ng-bootstrap/ng-bootstrap/accordion/accordion-config.d.ts.
This error may be because two or more entry-points overlap and ngcc has been asked to process some files more than once.
You should check other entry-points in this package and set up a config to ignore any that you are not using.
Error: Tried to write D:/test/student/node_modules/@ng-bootstrap/ng-bootstrap/accordion/accordion.d.ts.__ivy_ngcc_bak with an ngcc back up file but it already exists so not writing, nor backing up, D:/test/student/node_modules/@ng-bootstrap/ng-bootstrap/accordion/accordion.d.ts.
This error may be because two or more entry-points overlap and ngcc has been asked to process some files more than once.
You should check other entry-points in this package and set up a config to ignore any that you are not using.
Error: Tried to write D:/test/student/node_modules/@ng-bootstrap/ng-bootstrap/accordion/accordion.module.d.ts.__ivy_ngcc_bak with an ngcc back up file but it already exists so not writing, nor backing up, D:/test/student/node_modules/@ng-bootstrap/ng-bootstrap/accordion/accordion.module.d.ts.
This error may be because two or more entry-points overlap and ngcc has been asked to process some files more than once.
You should check other entry-points in this package and set up a config to ignore any that you are not using.
Error: Tried to write D:/test/student/node_modules/@ng-bootstrap/ng-bootstrap/alert/alert-config.d.ts.__ivy_ngcc_bak with an ngcc back up file but it already exists so not writing, nor backing up, D:/test/student/node_modules/@ng-bootstrap/ng-bootstrap/alert/alert-config.d.ts.
This error may be because two or more entry-points overlap and ngcc has been asked to process some files more than once.
You should check other entry-points in this package and set up a config to ignore any that you are not using.
Error: Tried to write D:/test/student/node_modules/@ng-bootstrap/ng-bootstrap/alert/alert.d.ts.__ivy_ngcc_bak with an ngcc back up file but it already exists so not writing, nor backing up, D:/test/student/node_modules/@ng-bootstrap/ng-bootstrap/alert/alert.d.ts.

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

ng --version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 9.1.0
Node: 10.16.3
OS: win32 x64

Angular: 9.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.0
@angular-devkit/build-angular     0.901.0
@angular-devkit/build-optimizer   0.901.0
@angular-devkit/build-webpack     0.901.0
@angular-devkit/core              9.1.0
@angular-devkit/schematics        9.1.0
@ngtools/webpack                  9.1.0
@schematics/angular               9.1.0
@schematics/update                0.901.0
rxjs                              6.5.4
typescript                        3.8.3
webpack                           4.42.0

</code></pre>

**Anything else relevant?**

**Comment by gkalpak** [comment] 2020-04-02 16:14
It works fine on [angular/ngcc-validation][1], e.g. you can see `Compiling @ng-bootstrap/ng-bootstrap : module as esm5` completing successfully [here][2].

Maybe an ngcc process crashed and left `@ng-bootstrap/ng-bootstrap` in a half-processed state.
Have you tried deleting `node_modules/` (or at least `node_modules/@ng-bootstrap/ng-bootstrap/`) and try again?

[1]: https://github.com/angular/ngcc-validation
[2]: https://circleci.com/gh/angular/ngcc-validation/4462

**Comment by indraraj26** [comment] 2020-04-02 16:50
Hi @gkalpak , Yes you are right, i stopped ng serve in middle of compiling then re-run ng serve. I have just deleted @ng-bootstrap and re-compile with es5 it is working fine. 

Can we have way like somebody stopped ng serve in middle of compiling then ngcc should re-run and should not throw any error or warning. If it is not possible to detect ngcc process left then you can close this.

Thank you

**Comment by gkalpak** [comment] 2020-04-02 18:24
Glad you got it working.

Generally, ngcc is able to resume when interrupted, unless it happens to be interrupted after starting writing files for a specific entry-point (and before completing writing them). This is a relatively small part of the whole ngcc processing, so the chances of this happening are small.

Unfortunetely, it is currently not possible to safely recover when interrupted during file writing. Maybe we could improve the error message to explain that it might be a result of a previous instance exiting unexpectedly (e.g. being stopped by the user before completing). We could even add a marker in the exntry-point's `package.json` when starting processing it, so it is easier to detect this situation.

**Comment by petebacondarwin** [comment] 2020-06-15 22:02
We don't have enough capacity to implement a solution to make ngcc resilient to being killed in this way right now. Instead we will update the error message to indicate that this error might be caused by killing ngcc and may be resolved by removing and reinstalling the node_modules.

**Closed** 2020-06-25 18:37 UTC
Labels: comp: ngcc, state: Needs Design, type: feature
