### ISSUE TITLE
Not able to access the attributes in connectedCallback of webcomponents

### ISSUE THREAD

**Issue by vinayk406** [angular/angular#19940] opened 2017-10-26 05:55 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

The generated code attaches the element to the dom and then sets the attributes because of which not able to access the attributes in connectedCallback of WC.

![image](https://user-images.githubusercontent.com/5180606/32036791-8c4421da-ba3f-11e7-8577-602f276056ac.png)

## Expected behavior

Static attributes should be available in the connectedCallback of the WC.

## Environment

<pre><code>
Angular version: 4.4.6
</code></pre>

**Comment by trotyl** [comment] 2017-10-26 05:58
Duplicate of #18909.

**Closed** 2017-10-26 10:06 UTC
