### ISSUE TITLE
Change async pipe to $ at the end

### ISSUE THREAD

**Issue by FriOne** [angular/angular#13923] opened 2017-01-14 03:01 UTC
[ ] bug report
[x] feature request
[ ] support request

**What is the motivation / use case for changing the behavior?**
Angular is built with Observables and we have `async` pipe which is great. But it makes a template a little bit noisy. There is standard way to call Observable type variables with **$** in the end of name, so we can simplify a template by omitting the pipe and making variables with **$** recognizable as "asynced" by default.
```html
<my-copmonent [data]="dataStream$ | async"></my-copmonent>
<my-copmonent *ngIf="!(dataStream$ | async)"></my-copmonent>
// into
<my-copmonent [data]="dataStream$"></my-copmonent>
<my-copmonent *ngIf="!dataStream$"></my-copmonent>
```
I guess there should be some configuration config option to not to brake old style,
or we can look in a template if it has `async` pipe.

**Comment by Toxicable** [comment] 2017-01-14 08:27
The async pipe is just a normal pipe, like any others, it's not built in, it's not integral to Angular, you could make your own if you wanted. Therefore why should it have it's own specific syntax? if anything you're asking to be able to use pipes based on some charter in the proper name of a bound field. Bad perf implications and would no longer make sense if you didn't have to sue the `|` character

**Comment by lazarljubenovic** [comment] 2017-01-14 12:26
You can wrap the pipe with your own pipe which would have selector `$`.

```
```

**Comment by FriOne** [comment] 2017-01-14 13:48
I know `async` is built in Angular, so what? Not the pipe should have own syntax but Angular itself. Anguar uses Observable everywhere, so why it is bad to make biolerplate code simplier?
Is there a way to make this change not changing the core?

**Comment by Toxicable** [comment] 2017-01-14 21:57
The `async` pipe is *not* built in, it's apart of the Common Module
No there is no way to change this with without changing how Angular compiles templates with pipes and changing how @Pipe works aswell

**Comment by pkozlowski-opensource** [comment] 2017-01-14 22:04
Let's move this discussion to #13248 where syntax / semantics for reactive style of programming is discussed.

Closing as a duplicate of #13248

**Closed by pkozlowski-opensource** 2017-01-14 22:04 UTC
