### ISSUE TITLE
[Pagespeed] How to reduce unused JavaScript in browser.mjs, core.mjs, common.mjs? 

### ISSUE THREAD

**Issue by Jun711** [angular/angular#50315] opened 2023-05-15 23:12 UTC
### Which @angular/* package(s) are relevant/related to the feature request?

common, core, router

### Description

It seems that Google Pagespeed suggests that some Angular packages like browser.mjs, core.mjs, common.mjs, router.mjs etc contain too much unused JavaScript. 
For example, this is the PageSpeed Insights for Angular Documentation page. 
It seems to affect all Angular Apps especially on mobile
https://pagespeed.web.dev/analysis/https-angular-io-docs/ebby37tj3k?form_factor=mobile

<img width="963" alt="237239389-d7b30c88-53a9-40a6-916e-346da80cf875" src="https://github.com/angular/angular/assets/6880939/386c1120-efe8-4eda-ad64-29eb3decce3c">

<img width="961" alt="237239398-a3471739-9e82-49e7-962b-4d6be4563874" src="https://github.com/angular/angular/assets/6880939/ab4a94ae-f29b-4619-a8f4-ad01d7d0573c">

### Proposed solution

Break these packages into smaller packages

### Alternatives considered

Lazy loading may work for packages that aren't needed at the beginning but these packages such browser.mjs, core.mjs, router.mjs etc seem to be needed at the very beginning.

**Comment by akpos97** [comment] 2023-05-16 15:41
Okay

**Comment by Jun711** [comment] 2023-05-18 00:38
It doesn't only affect Google Doc page. It affects all SPA built using Angular

**Comment by alxhub** [comment] 2023-05-18 16:55
> These packages such browser.mjs, core.mjs, router.mjs etc seem to be needed at the very beginning.

These packages are the Angular framework, and are definitely needed to render your application.

It’s also important to note that “unused code” is not always code that can be removed. For example, if you register an event listener for when the user clicks a button, and the user doesn’t click the button, the contents of the event listener are “unused” (those lines of JS didn’t execute), even though they’re absolutely required in the event that the user _does_ click the button.

I’m going to close this as a duplicate of #50222 for the same reason: questions like this are better asked in a support forum such as the Angular community Discord. Every application is different, and uses different pieces of the framework, and without access to your source code it’s impossible for us to know what changes would have the most impact on your initial bundle size.

**Closed by alxhub** 2023-05-18 16:55 UTC
Labels: area: performance, area: docs-infra

**Comment by Jun711** [comment] 2023-05-18 17:33
@alxhub 
I opened this issue because you said it wasn't an actionable item when I used my app as an example.

So, I just showed you that you have items to work as it also affects Angular documentation website and literally every Angular apps as that would appear in Google Pagespeed. It doesn't matter what changes or lazy loading that I add, those will just appear to contain a lot of unused code. You don't have to know my source code to know that and you can use Angular Documentation page as a test case to work on.

Regarding Angular community Discord, I asked that on May 9th but you didn't reply there either
<img width="1365" alt="Screen Shot 2023-05-18 at 10 27 47 AM" src="https://github.com/angular/angular/assets/6880939/3b437187-9286-4d4c-a756-4b72644ab04f">

So, by closing this thread, you are saying that those browser, core, common modules are at their absolute minimum size that you cannot do anything to make them smaller?
