### ISSUE TITLE
Localization of strings in ts file and json files

### ISSUE THREAD

**Issue by atmakup1** [angular/angular#30919] opened 2019-06-07 15:37 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....

### Is this a regression?

no
 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...
I have an angular 5 application, which I am able to localize using the angular documentation. But I have few strings that are added in the ts file i.e adding months,days, year to the age after computing the age. I am not finding a way to localize it. Also I get some data from a local json file with id and name property. I need to localize the value in the name property. 

## 🔬 Minimal Reproduction

 https://stackblitz.com/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
5

</code></pre>

**Anything else relevant?**

**Comment by trotyl** [comment] 2019-06-07 16:44
Duplicate of https://github.com/angular/angular/issues/11405

**Closed** 2019-06-07 17:17 UTC
