### ISSUE TITLE
Minimized bundle breaks with ngClass and ngIf

### ISSUE THREAD

**Issue by BTMorton** [angular/angular#7809] opened 2016-03-29 15:08 UTC
**Steps to reproduce and a minimal demo of the problem**
See: http://plnkr.co/edit/2ecdHTFEZiG3Q4ig8xga?p=preview
Open dev tools console to see the following error:
`EXCEPTION: No provider for e! (e -> e)`

If you remove the [ngClass] or the *ngIf it will work fine. Also, if you change from the .min.js version to the .js or .dev.js version it will work.

**Current behavior**
Throws `EXCEPTION: No provider for e! (e -> e)`

**Expected/desired behavior**
To work as it does with the full bundled version.

**Other information**

**Comment by HerringtonDarkholme** [comment] 2016-03-31 03:36
Still a problem in Angular beta.12. And the error stack is not helpful :(

**Comment by ericmartinezr** [comment] 2016-03-31 03:43
This has been broken since beta.1 and they're already aware of it https://github.com/angular/angular/issues/6380#issuecomment-203247147

**Comment by pkozlowski-opensource** [comment] 2016-03-31 08:54
Closing as duplicate of #6380

**Closed by pkozlowski-opensource** 2016-03-31 08:54 UTC
