### ISSUE TITLE
Route provider behaviour should align more with component providers (destroy them)

### ISSUE THREAD

**Issue by bleapleaper** [angular/angular#57486] opened 2024-08-22 13:31 UTC
### Which @angular/* package(s) are relevant/related to the feature request?

router

### Description

```
const routes: Routes = [
  {
      path: '1',
      providers: [StateService],
      children: [
         {
             path: ':id',
             component
         },
         another path, another component
      ]
  },
 {
   path: '2'
  }
]
```

I believe navigating between path 1 and 2 does not create a fresh instance of StateService. Whereas
```
@Component({
  selector: 'component-tag',
  templateUrl: './comp.component.html',
  styleUrls: ['./comp.component.scss'],
  providers: [StateService]
})
```

keeps things fresh when it is created and destroyed.

Intuitivly I would have thought route providers also were destroyed once the route tree with the providers was exited.

### Proposed solution

Create fresh instances of services provided in route when we are entering them. The instance stays the same when we navigate between subroutes / we don't exit the route.

Just as with parent component providers and child components - when we exit the parent component only then is the service destroyed not when we use child components, and the service is new again when we destroy and create the parent compoent

### Alternatives considered

I believe a work around for this is to use sub router outlet and use a parent component's injection logic. Just more refactoring for me

**Comment by alxhub** [comment] 2024-08-23 17:25
Duplicate of #37095.

**Closed by alxhub** 2024-08-23 17:25 UTC
Labels: area: router
