### ISSUE TITLE
Import error, can't find file: ./svg.component.svg

### ISSUE THREAD

**Issue by liheb** [angular/angular#31558] opened 2019-07-15 03:41 UTC
![Capture](https://user-images.githubusercontent.com/52902620/61194770-e1f68400-a6ed-11e9-9fda-9c5a85156e08.PNG)
![Capture](https://user-images.githubusercontent.com/52902620/61194776-e7ec6500-a6ed-11e9-9bce-f42873e0274b.PNG)

# 📚 Docs or angular.io bug report

### Description

 Import error, can't find file:
./svg.component.svg

### What's the affected URL?**
 https://stackblitz.com/angular/rxrlyneyjmn

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by santoshyadav198613** [comment] 2019-07-15 03:46
Duplicate of #31537

**Closed** 2019-07-15 07:42 UTC
