### ISSUE TITLE
(Router) Annoying redirect to home when some error occurs with lazy loaded modules

### ISSUE THREAD

**Issue by iget-master** [angular/angular#26993] opened 2018-11-07 22:29 UTC
# 🐞 bug report

### Affected Package
The issue is caused by @angular/router

### Is this a regression?

No.

### Description

Always that some error occurs on some page, the angular redirects the page to the root.

The problem is that when you are developing, this is annoying because always that you miss some module, you do:

1. Try your url: `localhost:4200/my/route/that/may/be/complex`
2. Angular will fail, console.log the reason, then redirect your to `localhost:4200`
3. Now I go to the code, fix the issue, for example a missing module
4. When I go back to the browser, I'm not on that long route, because angular decided to redirect me back to the root.
5. I will need to type all that long URL again, and again, and again. 

## 🔬 Minimal Reproduction
https://angular-issue-repro2-mc6ujx.stackblitz.io

## 🔥 Exception or Error

None.

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 7.0.4
Node: 8.12.0
OS: linux x64
Angular: 7.0.2
... animations, cdk, common, compiler, compiler-cli, core, forms
... http, language-service, material, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.10.4
@angular-devkit/build-angular     0.10.4
@angular-devkit/build-optimizer   0.10.4
@angular-devkit/build-webpack     0.10.4
@angular-devkit/core              7.0.4
@angular-devkit/schematics        7.0.4
@angular/cli                      7.0.4
@ngtools/webpack                  7.0.4
@schematics/angular               7.0.4
@schematics/update                0.10.4
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.19.1
</code></pre>

**Anything else relevant?**

No

**Comment by jasonaden** [comment] 2018-11-13 23:35
Thanks for the issue. I'm closing as this is expected behavior currently, therefore not a bug. However, I think the issue here is we need a better way to recover from errors in navigation. These APIs should be coming some time soon.

**Closed by jasonaden** 2018-11-13 23:35 UTC
Labels: comp: router

**Comment by JurajMlich** [comment] 2018-12-28 17:55
@jasonaden why would this be expected behavior? 

**Workaround for those experiencing it:**
node_modules/@angular/router/fesm5/router.js comment line 3973:
`_this.resetStateAndUrl(t.currentRouterState, t.currentUrlTree, t.rawUrl);`

**Comment by jasonaden** [comment] 2018-12-31 17:01
@JurajMlich For now, this is expected because the router assumes activation will succeed, and failure mode means going back to the previously successful navigated route. When you first load an app, there is no previously successful route, but it's a non-nullable field and the default is `/`. Therefore on first load, failures will end up back at `/`. After a successful navigation, this value is reset and future failures will fail to the previously successful route.

**Comment by JurajMlich** [comment] 2018-12-31 17:35
Makes sense now. What about disabling this behavior in development mode? Would that be possible? (If yes, I could possibly find some time to implement it)

**Comment by iget-esoares** [comment] 2019-01-07 12:04
Still make no sense for me. @jasonaden explaination looks a excuse instead of a reason.

Why don't just keep the same URL when failure, and throw an error message? At least on development mode it should work just fine!

**Comment by JurajMlich** [comment] 2019-01-07 12:10
It makes sense, as in production, if an error occurs while loading the next URL, keeping the user on the previous page is definitely the right thing to do. However, I agree that it should be disabled in development mode.
