### ISSUE TITLE
JASMINE TESTING 101

### ISSUE THREAD

**Issue by dwietecha** [angular/angular#4938] opened 2015-10-27 12:59 UTC
It seems to me, that the source code of unit-tests.html here https://angular.io/docs/ts/latest/testing/jasmine-testing-101.html isn't correct.  It should be:
```
...
<link rel="stylesheet" href="../node_modules/jasmine-core/lib/jasmine-core/jasmine.css">
  <script src="../node_modules/jasmine-core/lib/jasmine-core/jasmine.js"></script>
  <script src="../node_modules/jasmine-core/lib/jasmine-core/jasmine-html.js"></script>
  <script src="../node_modules/jasmine-core/lib/jasmine-core/boot.js"></script>
...
```
cause user have to install *jasmine-core*

**Comment by ericmartinezr** [comment] 2015-10-27 13:05
There's already a PR about this https://github.com/angular/angular.io/pull/290 not merged yet though

**Comment by pkozlowski-opensource** [comment] 2015-10-27 14:11
Closing as duplicate of angular/angular.io#290  since it belongs to the angular.io repo.

**Closed by pkozlowski-opensource** 2015-10-27 14:11 UTC

**Comment by wardbell** [comment] 2015-10-30 18:41
Agreed. What was I thinking/doing?
