### ISSUE TITLE
Potential bug in the routing example stackblitz program

### ISSUE THREAD

**Issue by pasha-bolokhov** [angular/angular#34917] opened 2020-01-23 00:58 UTC
# 📚 Docs or angular.io bug report

### Description

The example presented in https://angular.io/generated/live-examples/router/stackblitz.html (live example) does not exhibit the behaviour claimed in the documentation at https://angular.io/guide/router#query-parameters-and-fragments. Namely, this:

> Now, you can click on the Admin button, which takes you to the Login page with the provided queryParamMap and fragment. After you click the login button, notice that you have been redirected to the Admin Dashboard page with the query parameters and fragment still intact in the address bar.

The query parameter and the fragment both get lost when you are forwarded to the "admin" page by the login button. You can see that the "Admin" page displays `Null` both for `Session ID` and for `Token`, as they are also absent in the address bar. 

The cause seems to be the `navigateByUrl()` call in `auth/login/login.component.ts` at line 40. This is what the official doc says for this function referring to its `extras` parameter:

>  NavigationExtras | An object containing properties that modify the navigation strategy. The function ignores any properties in the NavigationExtras that would change the provided URL.

So if you replace line 40 
```
this.router.navigateByUrl(redirect, navigationExtras);
```
with
```
this.router.navigate([this.authService.redirectUrl], navigationExtras);
```
the app behaviour is then consistent with the expected description in the angular write-up. While `navigate()` is normally doing a relative navigation, in the absence of a "start" (`relativeTo`) position it will do the absolute navigation, but without the adverse effect of `navigateByUrl()`. Maybe not the most optimal solution though

But notice that if this solution is adopted, the `UrlTree` `redirect` variable is then not necessary

Also the Angular Doc write–up has to be updated as well to whatever solution is adopted

### What's the affected URL?**

https://angular.io/generated/live-examples/router/stackblitz.html

and the documentation at

https://angular.io/guide/router#query-parameters-and-fragments

### Reproduction Steps**
Navigate to https://angular.io/generated/live-examples/router/stackblitz.html, then to `Admin` tab and click the `Login` button. You will see both `Session ID` and `Token` being `None`

### Expected vs Actual Behavior**
`Session ID` should be `123456789`, and `Token` should be `anchor`, and not `None`

Otherwise how are they persistent?

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by gkalpak** [comment] 2020-02-04 09:48
Thx for reporting this, @pasha-bolokhov, and for suggesting a solution.
Indeed the docs of [Router#navigateByUrl()][1] mention:

> The function ignores any properties in the `NavigationExtras` that would change the provided URL.

So, apparently, query params and fragment options are ignored.
The possible fix is to switch to the [Router#navigate()][2] method (as @pasha-bolokhov suggested). I.e. we need to change the code in [examples/router/src/app/auth/login/login.component.1.ts][3] and [examples/router/src/app/auth/login/login.component.ts][4] to something like:

```diff
         // Get the redirect URL from our auth service
         // If no redirect has been set, use the default
-        let redirect = this.authService.redirectUrl ? this.router.parseUrl(this.authService.redirectUrl) : '/admin';
+        const redirectUrl = this.authService.redirectUrl || '/admin';

         ...

         // Redirect the user
-        this.router.navigateByUrl(redirect);
+        this.router.navigate([redirectUrl]);                    // For `login.component.1.ts`.
+        this.router.navigate([redirectUrl], navigationExtras);  // For `login.component.ts`.
```

We should also add a test in [examples/router/e2e/src/app.e2e-spec.ts][5] to verify that this scenario works as described in the guide.

[1]: https://v9.angular.io/api/router/Router#navigateByUrl
[2]: https://next.angular.io/api/router/Router#navigate
[3]: https://github.com/angular/angular/blob/128d4ac8a/aio/content/examples/router/src/app/auth/login/login.component.1.ts#L28-L33
[4]: https://github.com/angular/angular/blob/128d4ac8a/aio/content/examples/router/src/app/auth/login/login.component.ts#L29-L43
[5]: https://github.com/angular/angular/blob/128d4ac8a/aio/content/examples/router/e2e/src/app.e2e-spec.ts

**Comment by sonukapoor** [comment] 2020-02-04 13:09
@gkalpak As discussed offline, I will take this issue.

**Comment by kapunahelewong** [comment] 2020-03-11 14:00
Closing this since #35176 merged. @pasha-bolokhov, if you still have questions, feel free to continue commenting here or to reopen if the issue isn't resolved for you. Thank you for pointing this out and thanks to @sonukapoor for resolving!

**Closed by kapunahelewong** 2020-03-11 14:00 UTC
Labels: comp: docs, comp: router, freq1: low, severity1: confusing, state: community, state: has PR, type: bug/fix
