### ISSUE TITLE
common/http UMD bundle doesn't embed tslib

### ISSUE THREAD

**Issue by alan-agius4** [angular/angular#23041] opened 2018-03-28 10:58 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
At the moment tslib is not embedded inside the UMD bundle of `@angular/common/http` 

Take a look at the previous build:
https://github.com/angular/common-builds/blob/master/bundles/common-http.umd.js#L6

`tslib` is still being `required`.

## Expected behavior
Embed tslib in UMD bundle

## Environment

<pre><code>
Angular version: 5.X.X and 6.X.X.rc.X

**Comment by gkalpak** [comment] 2018-03-28 12:31
Duplicate of #22949.

**Closed by gkalpak** 2018-03-28 12:31 UTC
