### ISSUE TITLE
[Angular 10] Mat Dialog throws error after production deployment

### ISSUE THREAD

**Issue by kbtganesh** [angular/angular#38436] opened 2020-08-13 08:23 UTC
# 🐞 bug report

### Affected Package
I've recently upgraded to Angular 10. The issue is caused by package @angular/core. 

### Is this a regression?

I never faced this issue in previous versions. 

### Description

I have a dialog component and inside which I'll be loading other few components (say A, B, C). 
Now when I remove all component's selectors & have only text alone in my dialog component, it renders successfully. But if I use the selector of A, B & C's component, then it is throwing the below error.

During error, only half the dialog width is rendered & contents inside that has not loaded at all. It throws exception in core.js file as below.

`ERROR TypeError: Cannot read property 'selectors' of null`

I get this error only when using `ng build --prod` or `ng serve --prod`. (ie, only when using --prod). Issue didn't appear in normal ng serve in development mode. Hence there is no way I can reproduce this issue in stackblitz.

Our project is a bit complex and we did not find the exact cause of the issue due to which I could not able to create new repository to reproduce the issue. The error message thrown is not so helpful due to which I am helpless.

![image](https://user-images.githubusercontent.com/10905951/90111848-d6501380-dd6c-11ea-9878-1b2a44983054.png)

## 🔥 Exception or Error
<pre><code>

ERROR TypeError: Cannot read property 'selectors' of null
    at core.js:8052
    at so (core.js:7854)
    at core.js:13632
    at Module.gl (core.js:13668)
    at template (my-dialog.component.html:1)
    at Xi (core.js:7329)
    at Wi (core.js:7138)
    at ko (core.js:8382)
    at core.js:6997
    at Wi (core.js:7163)

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 10.0.1
Node: 10.15.0
OS: win32 x64

Angular: 10.0.2
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.1
@angular-devkit/build-angular     0.1000.1
@angular-devkit/build-optimizer   0.1000.1
@angular-devkit/build-webpack     0.1000.1
@angular-devkit/core              10.0.1
@angular-devkit/schematics        10.0.1
@angular/cli                      10.0.1
@angular/material                 10.0.1
@ngtools/webpack                  10.0.1
@schematics/angular               10.0.1
@schematics/update                0.1000.1
rxjs                              6.5.5
typescript                        3.9.6
webpack                           4.43.0

</code></pre>

**Anything else relevant?**
#37323 <- this ticket seems similar to my issue but unfortunately it's been closed because of lack of information. 
Please do comment if you need any other information from my side.

**Comment by msalmankarim** [comment] 2020-08-13 08:47
I am also facing this same issue.

**Comment by atscott** [comment] 2020-08-14 19:47
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template, including a minimal reproduction in StackBlitz or a GitHub repo.

**Comment by kbtganesh** [comment] 2020-08-15 04:57
@atscott

I CLEARLY TOLD, it's not reproduced since it's occurring only when doing build --prod. There is no proper error thrown hence we couldn't find the root cause. Without knowing the actual problem how can you expect it to be reproduced? 
I've told you the exception error & I am ready to debug each line by line in core.js file as well. 

Please do re-open the issue.

**Comment by atscott** [comment] 2020-08-15 14:20
You can open a new issue when there’s a reproduction. We can not investigate a problem without a one. As I said, a GitHub repository would work as well. An error message is simply not enough to go on.

**Comment by kbtganesh** [comment] 2020-08-16 02:26
@atscott,

When there is no proper error message thrown, how can you expect to find the root cause. And, without knowing the root cause, how can you expect to reproduce an issue?

**Comment by atscott** [comment] 2020-08-16 03:07
Reopening and handing off to ngcc team for further triage. They have been investigating issues similar to this lately. Potentially related to #37878 #38453 @petebacondarwin

**Comment by kbtganesh** [comment] 2020-08-17 06:18
@atscott, thanks for looking into it. Here I've found where the error has thrown inside core.js file if that could help. 
Also ready to debug through all the stack trace if needed & submit it here. Let me know if that will help to find the issue.

![dialog-issue](https://user-images.githubusercontent.com/10905951/90362953-5f25c280-e07f-11ea-8334-2a69e0acecba.PNG)

**Comment by kenaidri** [comment] 2020-08-17 07:04
Yah please submit it hear, thanks

Nasser alkonidri
best regards

On 17 Aug 2020, at 09:22, kbtganesh <notifications@github.com> wrote:

﻿

@atscott<https://github.com/atscott>, thanks for looking into it. Here I've found where the error has thrown inside core.js file if that could help.
Also ready to debug through all the stack trace if needed & submit it here. Let me know if that will help to find the issue.

[dialog-issue]<https://user-images.githubusercontent.com/10905951/90362953-5f25c280-e07f-11ea-8334-2a69e0acecba.PNG>

**Comment by petebacondarwin** [comment] 2020-09-01 16:09
@kbtganesh:

Are you still experiencing this issue with the latest versions of Angular (i.e. 10.1.0-rc.0)?

If so, it is going to be really hard to debug this via a Github conversation. The most effective way that we can help diagnose the problem is if you could provide us with a project that we can download and run locally. The simplest way in this case is probably for you to create a new CLI project that has the same problem and then to share it as a GitHub repository.  The smaller the project the better. One approach is to take you current project and keep cutting out pieces of it until it there is the minimal configuration and code that still causes the error to occur.

**Comment by kbtganesh** [comment] 2020-09-02 07:26
@petebacondarwin, Sure, I'll first try once with the latest version you've mentioned.

**Comment by petebacondarwin** [comment] 2020-09-07 08:26
@kbtganesh - any joy?

**Comment by kbtganesh** [comment] 2020-09-07 15:18
@petebacondarwin, 

It just introduced new errors :(

I've tried updating angular material to latest version, clear npm cache, update 'npm' to latest version, remove nodemodule+package lock & did npm install again. Nothing worked. 

```
ERROR in ./node_modules/@angular/material/__ivy_ngcc__/fesm2015/table.js 94:20-44
"export '_CoalescedStyleScheduler' was not found in '@angular/cdk/table'
ERROR in ./node_modules/@angular/material/__ivy_ngcc__/fesm2015/table.js 61:12-36
"export '_CoalescedStyleScheduler' was not found in '@angular/cdk/table'
ERROR in ./node_modules/@angular/material/__ivy_ngcc__/fesm2015/table.js 91:66-94
"export '_DisposeViewRepeaterStrategy' was not found in '@angular/cdk/collections'ERROR in ./node_modules/@angular/material/__ivy_ngcc__/fesm2015/table.js 58:58-86
"export '_DisposeViewRepeaterStrategy' was not found in '@angular/cdk/collections'ERROR in ./node_modules/@angular/material/__ivy_ngcc__/fesm2015/table.js 58:23-46
"export '_VIEW_REPEATER_STRATEGY' was not found in '@angular/cdk/collections'
ERROR in ./node_modules/@angular/material/__ivy_ngcc__/fesm2015/table.js 91:31-54
"export '_VIEW_REPEATER_STRATEGY' was not found in '@angular/cdk/collections'
ERROR in ./node_modules/@angular/material/__ivy_ngcc__/fesm2015/sidenav.js 433:8-47
"export 'ɵɵcomponentHostSyntheticListener' (imported as 'ɵngcc0') was not found in '@angular/core'
ERROR in ./node_modules/@angular/material/__ivy_ngcc__/fesm2015/snack-bar.js 392:8-47
"export 'ɵɵcomponentHostSyntheticListener' (imported as 'ɵngcc0') was not found in '@angular/core'
ERROR in ./node_modules/@angular/material/__ivy_ngcc__/fesm2015/bottom-sheet.js 249:8-47
"export 'ɵɵcomponentHostSyntheticListener' (imported as 'ɵngcc0') was not found in '@angular/core'
ERROR in ./node_modules/@angular/material/__ivy_ngcc__/fesm2015/datepicker.js 2392:8-47
"export 'ɵɵcomponentHostSyntheticListener' (imported as 'ɵngcc0') was not found in '@angular/core'
ERROR in ./node_modules/@angular/material/__ivy_ngcc__/fesm2015/dialog.js 328:8-47"export 'ɵɵcomponentHostSyntheticListener' (imported as 'ɵngcc0') was not found in '@angular/core'
ERROR in ./node_modules/@angular/material/__ivy_ngcc__/fesm2015/dialog.js 332:8-43"export 'ɵɵupdateSyntheticHostBinding' (imported as 'ɵngcc0') was not found in '@angular/core'
ERROR in ./node_modules/@angular/material/__ivy_ngcc__/fesm2015/sidenav.js 436:8-43
"export 'ɵɵupdateSyntheticHostBinding' (imported as 'ɵngcc0') was not found in '@angular/core'
ERROR in ./node_modules/@angular/material/__ivy_ngcc__/fesm2015/datepicker.js 2394:8-43
"export 'ɵɵupdateSyntheticHostBinding' (imported as 'ɵngcc0') was not found in '@angular/core'
ERROR in ./node_modules/@angular/material/__ivy_ngcc__/fesm2015/snack-bar.js 395:8-43
"export 'ɵɵupdateSyntheticHostBinding' (imported as 'ɵngcc0') was not found in '@angular/core'
ERROR in ./node_modules/@angular/material/__ivy_ngcc__/fesm2015/bottom-sheet.js 252:8-43
"export 'ɵɵupdateSyntheticHostBinding' (imported as 'ɵngcc0') was not found in '@angular/core'
```

**Comment by JoostK** [comment] 2020-09-07 15:57
@kbtganesh Those `ɵɵupdateSyntheticHostBinding` errors smell like an issue with multiple versions of `@angular/core`. This can either be because of symlinks into a different tree where there's a `node_modules` folder in scope, which will result in that `@angular/core` package installed in that `node_modules` folder to be resolved for the symlinked library. Alternatively, it may be that you have multiple versions installed because of incompatible `dependencies` requirements (which should typically be `peerDependencies`, but not all libraries do this correctly).

**Comment by petebacondarwin** [comment] 2020-11-02 20:06
Closing due to a lack of reproduction that we can debug.

**Closed by petebacondarwin** 2020-11-02 20:06 UTC
Labels: P4, comp: ngcc, freq1: low, needs clarification, needs reproduction, type: bug/fix
