### ISSUE TITLE
FormBuilder: Input has *ngIf="false" but still it is considered for validation

### ISSUE THREAD

**Issue by mohammedzamakhan** [angular/angular#7970] opened 2016-04-08 13:59 UTC
***demo*** http://plnkr.co/edit/l2XLYJRuGrvzvQigGCHc?p=preview

**Expected Behavior** The form validation should be dynamic if things like disabled, ngIf changes on the input with ngControl on it.

**Actual Behavior** No changes to form validation with ngIf= false

**Comment by mohammedzamakhan** [comment] 2016-04-08 17:49
I have the solution for it, but it will be messier for large forms

http://plnkr.co/edit/N5M10i8vH3tx5emFhFkM?p=preview

**Comment by czosel** [comment] 2016-04-13 17:05
I found a solution to this which seems a little more elegant: [plunkr](http://plnkr.co/edit/RzFTpRAG5Pk7wgSofkr2?p=preview).

```typescript
@Directive({
  selector: '[ngControl]'
})
export class MyControl implements OnInit, OnDestroy {
  @Input() ngControl:string;
  constructor(@Host() @SkipSelf() private _parent:ControlContainer) {}

  ngOnInit():void {
    // see https://github.com/angular/angular/issues/6005
    setTimeout(() => this.formDirective.form.include(this.ngControl));
  }

  ngOnDestroy():void {
    this.formDirective.form.exclude(this.ngControl);
  }

  get formDirective():any {
    return this._parent.formDirective;
  }
}
```

The workaround works pretty well for me till now, but this still feels like something that should be addressed in the framework.

**Comment by mohammedzamakhan** [comment] 2016-04-14 13:29
@czosel I like you solution and yes like as you said, I want this to be supported by the framework, since it is how we had it in Angular 1. :smile:

**Comment by czosel** [comment] 2016-04-14 13:33
@mohammedzamakhan Totally! Just as a little follow-up: I actually switched my implementation from `*ngIf` to using `hidden` because only like this i was able to also clear the model when the element goes from displayed to hidden (which was handy for my use case) - but the basic idea is the same.

**Comment by kara** [comment] 2016-06-26 21:45
@mohammedzamakhan Thanks for taking the time to describe the problem.  I took a look at your example code, and it seems that you are using the reactive form directives (a.k.a "model-driven" directives: ngFormModel, etc), but a template-driven strategy.  The fact that the ngIf does not remove the control from the form's serialization and validation is actually by design, and here's why.  

In each form paradigm - template-driven and reactive - there can only be one source of truth for the list of active controls.   In the template-driven paradigm, the source of truth is the template.   In the reactive equivalent, the source of truth is the form model created in the parent component. The DOM does not dictate the state of your form.  For this reason, if you remove form control elements from the DOM while using a reactive approach, the form controls are not necessarily changed in the source of truth *unless you want them to be*.  You can choose to update the controls imperatively by calling `this.form.removeControl('controlName')`, or you can choose to keep the controls in your form. This flexibility allows you to add or remove inputs from the DOM temporarily while keeping their form values serialized (e.g. if you have a number of collapsible sections to your form, you can remove sections on collapse without impacting the value of your form).   We don't want to restrict this flexibility and complicate ownership by forcing the model to always match the DOM.

So in your case, if you choose a reactive strategy, you'll want to invert your logic to rely on the source of truth - the model.  Specifically, this means removing the control imperatively in the model by calling `this.form.removeControl('name')` when the button is clicked.  Then, the ngIf should depend on the control's presence in the model with `*ngIf="form.contains('name')"`, rather than the other way around.  

```html
<form [ngFormModel]="form">
   <input type="text" ngControl="name" *ngIf="form.contains('name')">
</form>
<button (click)="remove()">Remove</button>
```

```ts
class App {
  constructor(private fb: FormBuilder) {
    this.form = fb.group({
      name: ['', Validators.required]
    })
  }
  remove() {
    this.form.removeControl('name');
  }
}
```

See example plunker here:  http://plnkr.co/edit/V7bCFLSIEKTuxU9jcp6v?p=preview  

It's worth noting that if you're still using beta.14 (as in your plunker), you'll need to call `this.form.updateValueAndValidity()` manually.  This requirement was removed in https://github.com/angular/angular/pull/9097, so versions after RC.2 don't require the call.

Another option is to convert to a template-driven strategy, which will remove the control from the form when it's destroyed from the template.

I'm going to close this issue as it works as intended, but I think we could make the experience a lot friendlier.  A good start would be some more cookbooks and guides in the documentation.

**Closed by kara** 2016-06-26 21:45 UTC
Labels: comp: core/forms

**Comment by h3kt0r** [comment] 2017-03-15 08:34
Use the functions enable() disable() to include or exclude validations from the form and in the template you can check the status with enabled and disabled properties to hide and show the control or group

**Comment by teddywest32** [comment] 2017-03-22 11:33
@h3kt0r Could you provide an example plunkr for this??

**Comment by h6784rfg6** [comment] 2018-01-27 18:21
@teddywest32 

https://stackoverflow.com/questions/36058231/how-to-set-validator-to-required-if-visible

**Comment by Gahen** [comment] 2018-03-06 15:21
@kara is this still true? I'm seeing the opposite behavior with ngIf and forms

**Comment by WizardPC** [comment] 2018-04-01 13:58
@Gahen i agree with you 👍 

I was thinking not, but in fact i let a typo in my forms... Thank you for your comment and saving my time !
