### ISSUE TITLE
Giving application/json in headers make http.get fail for restricted area

### ISSUE THREAD

**Issue by hdcos** [angular/angular#10690] opened 2016-08-11 16:16 UTC
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```
I am upgrading from beta.17
When using http.get I can give options to access auth-restricted area of my website.

    let headers = new Headers({
        'Content-Type': 'application/json',
        'Authorization': 'Basic *password*='
      });
    let options = new RequestOptions({ headers: headers });
    return this.http
        .get(this.callback, options)
        .map(this.extractData);

**Current behavior**

> Uncaught EXCEPTION: Error in backoffice/funeral-events/event-death.component.html:30:9
ORIGINAL EXCEPTION: TypeError: Cannot read property 'toString' of null
ORIGINAL STACKTRACE:
TypeError: Cannot read property 'toString' of null
    at Request.Body.text (http://admin.localhost:4000/@angular/http/http.umd.js:1138:30)
    at Request.getBody (http://admin.localhost:4000/@angular/http/http.umd.js:1720:33)
    at Observable.eval [as _subscribe] (http://admin.localhost:4000/@angular/http/http.umd.js:1419:41)
    at Observable.subscribe (http://admin.localhost:4000/rxjs/Observable.js:52:62)
    at Observable._subscribe (http://admin.localhost:4000/rxjs/Observable.js:109:28)
    at MapOperator.call (http://admin.localhost:4000/rxjs/operator/map.js:54:23)
    at Observable.subscribe (http://admin.localhost:4000/rxjs/Observable.js:52:38)
    at HospitalsComponent.getHospitals (http://admin.localhost:4000/js/advitam-bo.js:1592:26)
    at HospitalsComponent.ngOnInit (http://admin.localhost:4000/js/advitam-bo.js:1584:26)
    at DebugAppView._View_EventDeathComponent1.detectChangesInternal (EventDeathComponent.ngfactory.js:535:87)
ERROR CONTEXT:
[object Object]

**Expected/desired behavior**

I should get an observable I can call subscribe on, and no exception like this one. I had a really hard time to understand why this code failed when upgrading. 

What is strange is that when I remove 

     'Content-Type': 'application/json',

the call is made and I can extract my data.
So for now I just remove the `application/json` part. But I think it's a bug so I report it

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** [all | Chrome ] 
 
* **Language:** [ TypeScript last]

**Comment by pkozlowski-opensource** [comment] 2016-08-11 17:04
Duplicate of #10612

**Closed by pkozlowski-opensource** 2016-08-11 17:04 UTC
