### ISSUE TITLE
npm ERR! beta.5 postinstall: `typings install

### ISSUE THREAD

**Issue by palchik1985** [angular/angular#7028] opened 2016-02-11 23:45 UTC
The third day of trying to install angular2 via npm.... beta3 was install error (tsd postinstall), beta4 was install error, and now - beta5 install error.
Today, it is:
`error Failed at the angular2@2.0.0-beta.5 postinstall script 'typings install --ambient --name es6-promise github:DefinitelyTyped/DefinitelyTyped/es6-promise/es6-promise.d.ts#830e8ebd9ef137d039d5c7ede24a421f08595f83; typings install --ambient --name es6-collections github:DefinitelyTyped/DefinitelyTyped/es6-collections/es6-collections.d.ts#9f97e2a2bc1f502550c9b4fcaad1c48df5521d37'`

npm-debug (the last part) attached below:
[(http://pastebin.com/wfdWxHbe)]

How to fix it?

**Comment by alexeagle** [comment] 2016-02-12 00:21
Sorry, this was a Windows compatibility issue. Fixed in beta.6 (just released)

Dupe of #7000

**Closed by alexeagle** 2016-02-12 00:21 UTC
