### ISSUE TITLE
Pipe translate not working building with ivy

### ISSUE THREAD

**Issue by AndreaSpurs9** [angular/angular#39644] opened 2020-11-12 09:59 UTC
# 🐞 bug report

### Affected Package
The issue is caused by package @angular version 9

### Is this a regression?

Yes, the previous version in which this bug was not present was: @angular 8

### Description

I wrapped the ngx library inside my own library and with angular 8 all was working fine. After the update with angular 9 i get the following error: 

No pipe found with name 'translate'.

This error happen when i build with --prod and ivy activated. I don't get thie error when 'enableIvy: false'

I fixed it with adding this import 'TranslationServiceChildModule.forChild()' (this is the import to my wrapped module inside my library). It wasn't needed before why i need it now?

## 🔬 Minimal Reproduction

You can install this version of ngx translate :
"@ngx-translate/core": "^12.1.2",
"@ngx-translate/http-loader": "^5.0.0"
and building with --prod and Ivy activated

## 🔥 Exception or Error

No pipe found with name 'translate'.

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.1.12
Node: 10.18.1
OS: darwin x64

Angular: 9.1.12
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.12
@angular-devkit/build-angular     0.901.12
@angular-devkit/build-optimizer   0.901.12
@angular-devkit/build-webpack     0.901.12
@angular-devkit/core              10.2.0
@angular-devkit/schematics        10.2.0
@angular/fire                     5.4.2
@ngtools/webpack                  9.1.12
@schematics/angular               10.2.0
@schematics/update                0.901.12
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0
</code></pre>

**Anything else relevant?**
This is happen on web and device if build with --prod and Ivy activated

**Comment by petebacondarwin** [comment] 2020-11-12 10:11
Please can you provide a full reproduction (perhaps as a github repo) that demonstrates this issue. It is not possible to diagnose the problem with the information you have provided.

**Comment by giorgiogalassi** [comment] 2020-11-12 11:09
Hi @petebacondarwin , thanks for the quick response.

Actually i've not a repo to share beacuse it's a private one.

We just update a working project (in with `--prod` flag) and got the error above. 
Is there something that we can check to better understand why is this happening?

Regards,
G.

**Comment by petebacondarwin** [comment] 2020-11-12 11:17
Can you make a new repository which demonstrates this issue. For example, create a new CLI project via `ng new`, add in a new library with the appropriate dependencies and see if this reproduces the problem. You could then push this to Github and share it.

**Comment by AndrewKushnir** [comment] 2020-11-17 19:31
Closing this issue since there is no repro. Feel free to reopen or create a new ticket once repro is available.

**Closed by AndrewKushnir** 2020-11-17 19:31 UTC
Labels: comp: compiler, comp: ngcc, needs reproduction
