### ISSUE TITLE
Doc error: Angular Example is failing

### ISSUE THREAD

**Issue by SetTrend** [angular/angular#23202] opened 2018-04-05 19:03 UTC
Clicking the [live example](https://angular.io/generated/live-examples/toh-pt6/stackblitz.html) hyperlink in the [Angular tutorial](https://angular.io/tutorial) I get the following error message:

![angular error](https://user-images.githubusercontent.com/9283914/38386345-aaa55f96-3914-11e8-833e-d6d5cbc19b75.png)

**Comment by SetTrend** [comment] 2018-04-05 20:41
Sure, here's the information from my Firefox browser:

[Informationen zur Fehlerbehebung.zip](https://github.com/angular/angular/files/1881761/Informationen.zur.Fehlerbehebung.zip)

It's in German, I'm afraid, but I hope you'll get the important parts.

**Comment by gkalpak** [comment] 2018-04-07 20:00
@SetTrend, it seems that the error is caused by having `indexedDB` disabled (according to [this issues][1]). Apparently, StackBlitz requires IndexedDB in order to work correctly.

Closing, since there is nothing we can do on our end (afaict).

[1]: https://github.com/brython-dev/brython/issues/248

**Closed by gkalpak** 2018-04-07 20:00 UTC
Labels: comp: docs
