### ISSUE TITLE
Add documents for ngc

### ISSUE THREAD

**Issue by xiaoxiangmoe** [angular/angular#37266] opened 2020-05-24 09:09 UTC
# 🚀 feature request

### Relevant Package

 This feature request is for  @angular/compiler @angular/compiler-cli

### Description

I want to use angular in a non-webpack environment. Such as [vite](https://github.com/vitejs/vite) and parcel

I want to call JS api for transform ts by ngtsc (from code string with class decorators to code string with class static methods by AOT compiler for production and JIT compiler for development).

But I only find an example call ['node_modules/.bin/ngc'](https://github.com/steveblue/angular2-rollup/blob/6ec3290c2a6057af123e9e9e255b5b7315c34153/src/compile/ngc.js#L22-L43).

Is there a better way to achieve it?(For example, TypeScript has [transpileModule](https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API#a-simple-transform-function))
Is there any documentation about *@angular/compiler* and *@angular/compiler-cli*?

**Comment by JoostK** [comment] 2020-05-28 21:28
I'll close this as a duplicate of #20422, carried the docs labels over to that issue. As that request indicates, the compiler-cli is not considered public API.

**Closed by JoostK** 2020-05-28 21:28 UTC
Labels: comp: compiler, comp: docs, freq1: low, severity1: confusing, subtype: docs-completeness, type: feature
