### ISSUE TITLE
Pass an encoded (base) URL to `routerLink`

### ISSUE THREAD

**Issue by Yogu** [angular/angular#50950] opened 2023-07-05 14:57 UTC
### Description

In my app, I calculate URLs to specific routes at various parts within the code. I pass these URLs around as strings because that's a simple and clean way to do it. Now, I want pass these URLs to `routerLink`. Sometimes standalone, sometimes I want to add navigation commands (to navigate to a sub-route).

I initially thought I could pass the URL as first command because it supports slash-separated segments. However, this breaks as soon as the URL contains encoded characters like `%2F` (encoded forward slash). The percent sign will end up double-encoded (`%252f`).

Here is the corresponding code:

https://github.com/angular/angular/blob/5d11844a7c31df56d2b97e3aa6cd1a70b5fccc70/packages/router/src/create_url_tree.ts#L231-L245

`cmd` is split on `/`, but the resulting `urlPart` instances are not further decoded. When the resulting `UrlTree` is later serialized, the parts will be encoded again, resulting in the double encoding.

It's probably not possible to change the behavior of `createUrlTree` or `routerLink` because that would be breaking and in some cases also not what is expected. Therefore, I propose a new feature to support this.

### Proposed solution

Commands can already be more than just strings: It is possible to pass `{ segmentPath: 'some/thing' }` instead of a string. This allows to bypass the slash-splitting logic in the first command.

We could something similar for passing in an URL:

```
Router.createUrlTree([
    { url: 'first-segment/second%2fsegment' },
    'third-segment'
])
```

The value of `url` would be expected to be a properly serialized URL. Otherwise, the call would error.

### Alternatives considered

Apps can deserialize the URLs themselves, and then pass the path segments into `routerLink`, Then, no new Angular feature would be needed. However, it might be good to mention this case in the documentation of `Router.createNaivgationTree` because other developers might fall into the same trap as me, thinking that the first command is a URL while it in fact is not.

Here is the implementation of a pipe apps can use to work around the problem:

```typescript
import { Pipe, PipeTransform } from '@angular/core';

/**
 * Takes an encoded URL and parses it so it can be passed to Router.createUrlTree
 *
 * This can be used to pass an encoded URL to e.g. [routerLink]
 *
 * All arguments are treated as additional path segments.
 */
@Pipe({
    name: 'decodeRouterUrl',
    standalone: true,
})
export class DecodeRouterUrlPipe implements PipeTransform {
    transform(url: string, ...args: string[]): ReadonlyArray<string> {
        const isAbsolute = url.startsWith('/');
        if (isAbsolute) {
            url = url.substring(1);
        }

        const urlParts = url.split('/').map((p) => decodeURIComponent(p));

        // The first navigation command will be split on slashes, which is not what we want here
        // so we always supply either '/' or '.' as first command
        return [isAbsolute ? '/' : '', ...urlParts, ...args];
    }
}
```

**Comment by atscott** [comment] 2023-07-08 09:15
Duplicate of https://github.com/angular/angular/issues/34468

**Closed by atscott** 2023-07-08 09:15 UTC
Labels: area: router
