### ISSUE TITLE
Docs: Remove IE 9 & 10 from the Browser support list.

### ISSUE THREAD

**Issue by CarreraPHP** [angular/angular#29776] opened 2019-04-09 08:04 UTC
# 📚 Docs or angular.io bug report

### Description

 Remove IE 9 & 10 from the supported browser list and instead provide information that will help developer if he/she wants their application to work in them.

This will help the community in 2 things:
* Close long pending issues related to IE 9 & 10.
* Easy to convince client, that supporting IE 11 is sufficient in all windows Operating Systems. Currently, it is difficult to do so because angular docs page is showing IE 9 & 10 as supported.

#### I am quoting the statement from Microsoft on the Life-cycle & Support of IE Browsers.

![image](https://user-images.githubusercontent.com/422070/55782472-fc570b00-5ac9-11e9-873e-d6236546be07.png)

Reference URL’s: 
* https://support.microsoft.com/en-in/help/17454/lifecycle-faq-internet-explorer
* https://www.microsoft.com/en-in/windowsforbusiness/end-of-ie-support

### What's the affected URL?**
 https://angular.io/guide/browser-support

**Comment by manklu** [comment] 2019-04-09 17:16
Small addition

EOL for IE 10 is January 14, 2020.
https://support.microsoft.com/en-in/help/4488955

**Comment by CarreraPHP** [comment] 2019-04-09 18:11
@manklu, I am aware of the IE 10. But, that is for IE in windows server and not desktop. Which is of lesser percentage compared to the overall IE usage. That's why I did mention about it directly.

This issue is to push modern browsers adoption. For, all browsers we are saying last 2 browser versions are supported. Why can't be take that stand for IE & Edge. Why do we support 3 versions of IE and 1 version in edge?

**Comment by alxhub** [comment] 2019-04-16 22:55
@CarreraPHP I believe that's because Edge is an "evergreen" browser, and IE is not.

**Comment by trotyl** [comment] 2019-04-19 09:29
@alxhub I'd suggest explicitly document the differential support for IE at feature level, with the fact that not everything works with IE already:

+ `@angular/service-worker`: Service Workers cannot be polyfilled, and only available in Edge;
+ `@angular/elements`: Custom Elements can only be polyfilled in IE11+, but not IE9/IE10;
+ `@angular/common:PathLocationStrategy`: History API cannot be polyfilled and only available in IE10+;

The suggested approach is to introduce a set of **legacy browsers** (against **primary browsers**), including IE9/10/11 and some other old mobile browsers, with the definition:

+ Primary browsers get full support in every package (only minimal language polyfills if necessary);
+ Legacy browsers are supported on best effort, but may require manual opt-in of language polyfills, browser polyfills and/or feature adaptors, may also missing some advanced feature due to lacking browser support which cannot be polyfilled.

Then following practices could be applied:

+ A feature should be supported in all primary browsers, but not necessarily in legacy browsers;
  + For example, feature like Angular Elements can be provided even it's not feasible on IE9/IE10;
+ The default option should be made best-fit for primary browsers which doesn't bring unused code, but could require explicit opt-in for legacy browsers;
  + Keep [`PathLocationStrategy`](https://angular.io/api/common/PathLocationStrategy) used by default, and [`HashLocationStrategy`](https://angular.io/api/common/HashLocationStrategy) can still be manually used if needed;
  + Remove [`useHash`](https://angular.io/api/router/ExtraOptions#useHash) shortcut option which make `HashLocationStrategy` not tree-shakable and results in larger app size. Make a `USE_HASH_LOCATION` provider export directly as tree-shakable quick switch;
+ The implementation should prefer having built-in support for primary browsers but prefer requiring polyfills for legacy browser, making minimal framework size in primary browsers;
  + Keep [`CssKeyframes`](https://github.com/angular/angular/blob/c1d5fbd0ad6a3f269429f993f9f9a06375aecac9/packages/animations/browser/src/render/web_animations/web_animations_driver.ts#L44-L47) fallback by default as Web Animations API not available in Edge;
  + Remove [`looseIdentical`](https://github.com/angular/angular/blob/885f1af509eb7d9ee049349a2fe5565282fbfefb/packages/core/src/util/comparison.ts#L13-L15) and [`isDifferent`](https://github.com/angular/angular/blob/c1d5fbd0ad6a3f269429f993f9f9a06375aecac9/packages/core/src/render3/util/misc_utils.ts#L20-L24) by utilizing [`Object.is`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/is), the implementation is almost only a built-in polyfill;
  + Remove custom iteration utils like [`isListLikeIterable `](https://github.com/angular/angular/blob/885f1af509eb7d9ee049349a2fe5565282fbfefb/packages/core/src/util/iterable.ts#L12-L17) and [`getSymbolIterator`](https://github.com/angular/angular/blob/885f1af509eb7d9ee049349a2fe5565282fbfefb/packages/core/src/util/symbol.ts#L14-L32) by utilizing [`Symbol.iterator`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/iterator);
  + Remove custom [`Object.assign`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign) equivalents like [`fillProperties`](https://github.com/angular/angular/blob/c1d5fbd0ad6a3f269429f993f9f9a06375aecac9/packages/core/src/util/property.ts#L24-L30), [`merge`](https://github.com/angular/angular/blob/c1d5fbd0ad6a3f269429f993f9f9a06375aecac9/packages/core/src/sanitization/html_sanitizer.ts#L19-L27), [this](https://github.com/angular/angular/blob/c1d5fbd0ad6a3f269429f993f9f9a06375aecac9/packages/animations/browser/src/dsl/animation_timeline_builder.ts#L736-L740) and [this](https://github.com/angular/angular/blob/c1d5fbd0ad6a3f269429f993f9f9a06375aecac9/packages/animations/browser/src/util.ts#L263-L267);
  + Utilize [`Set`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set) rather than having `O(n)`-cost [`Array#indexOf`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/indexOf) like [this](https://github.com/angular/angular/blob/c1d5fbd0ad6a3f269429f993f9f9a06375aecac9/packages/animations/browser/src/render/timeline_animation_engine.ts#L98-L101) and [this](https://github.com/angular/angular/blob/c1d5fbd0ad6a3f269429f993f9f9a06375aecac9/packages/core/src/application_ref.ts#L697-L702);
  + Utilize [`Array#includes`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes) if must be `Array` and only testing for existence;
  + Utilize [`Object.values`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/values) rather than manual mapping `Object.keys` result like [this](https://github.com/angular/angular/blob/c1d5fbd0ad6a3f269429f993f9f9a06375aecac9/packages/animations/browser/src/dsl/animation_ast_builder.ts#L131-L136);
  + Close issue like https://github.com/angular/angular/issues/20959 which only requires a `function.name` polyfill import (could add default commented entry in Angular CLI);
  + Close issue like https://github.com/angular/angular/issues/15833 which only requires a `console.error` polyfill import (could add default commented entry in Angular CLI);
  + Close issue like https://github.com/angular/angular/issues/7557 which only require an [ie9-oninput-polyfill](https://github.com/buzinas/ie9-oninput-polyfill) (could add default commented entry in Angular CLI);
  + Use only `input` event and fix issue like https://github.com/angular/angular/issues/12540;
+ Create a `@angular/compat` (or `@angular/legacy`) package to handle issues caused by browser bug (violating standard behavior) if cannot fixed by polyfill, rather than bring compatibility-solving code to all projects;
  + Provide additional [`EVENT_MANAGER_PLUGINS`](https://angular.io/api/platform-browser/EVENT_MANAGER_PLUGINS) for incorrect IE `input` event firing, fixing https://github.com/angular/angular/issues/15299;
  + Provide legacy keyboard map for IE, fixing https://github.com/angular/angular/issues/8273;

**Comment by AndrewKushnir** [comment] 2020-05-15 23:20
Hi @CarreraPHP, thanks for creating this ticket.

IE 9 and 10 will be marked as deprecated in Angular v10 (see #36887 and [deprecations doc](https://next.angular.io/guide/deprecations#ie-9-10)) and support will be removed in a future version.

@trotyl, thanks for the very detailed comment. I've referenced it internally and we'll review it as a part of the process to refactor/simplify the code when we start removing IE 9 and 10 support.

Since IE 9 and 10 support deprecation was added into the necessary docs, I'm closing this ticket.

Thank you.

**Closed by AndrewKushnir** 2020-05-15 23:20 UTC
Labels: comp: core, type: feature
