### ISSUE TITLE
Unnecessary scrollbar in the navbar

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#23835] opened 2018-05-10 22:58 UTC
This seems to be a new regression:

<img width="806" alt="screen shot 2018-05-10 at 3 56 50 pm" src="https://user-images.githubusercontent.com/216296/39898257-d8d12b72-546a-11e8-9f02-acd4b537b1f2.png">

**Comment by IgorMinar** [comment] 2018-05-10 22:59
oh.. I see. It happens only if you unroll 3rd level of menus and which for some items hits the width limit and results in the scrollbar.

**Comment by IgorMinar** [comment] 2018-05-10 23:09
Repro:

1. https://angular.io/docs
2. click on "Fundamentals"
3. click on "Components & Templates"

**Comment by petebacondarwin** [comment] 2018-05-11 07:37
Actually, I think it is really to do with the height of the screen. Note what happens if you make the browser window taller - the scroll bar goes away.

I can make the scroll bar appear even with all the menu items closed by shortening the height of the screen.

![out](https://user-images.githubusercontent.com/15655/39912390-7962b37c-54f6-11e8-9fe7-f6bfb4bd9491.gif)

I think there is some weird height setting on the side nav.

**Comment by gkalpak** [comment] 2018-05-11 08:33
Duplicate of #21508, which was partly duplicate of #17096. (See there for more info.)

**Closed by gkalpak** 2018-05-11 08:33 UTC
Labels: comp: aio, effort1: hours, freq1: low, risk: low, type: bug/fix
