### ISSUE TITLE
ionic2: JSONP injected script did not invoke callback.

### ISSUE THREAD

**Issue by ksphp** [angular/angular#12508] opened 2016-10-25 09:37 UTC
## Code

```
this.jsonp.request('http://192.168.3.9:8200/data/index/home/1/?callback=JSON_CALLBACK').subscribe(res => {
    console.log(res.json());
});
```
## Jsonp

```
JSON_CALLBACK({"slide":[{"title":"\u57ce\u5e02\u5408\u4f19\u4eba","src":"http:\/\/192.168.3.9:8200\/data\/..\/upload\/m\/slider\/2016102513181886.jpg","url":"url"},{"title":"\u65b0\u7528\u6237\u900125\u5143\u4f18\u60e0\u52b5","src":"http:\/\/192.168.3.9:8200\/data\/..\/upload\/m\/slider\/2016102513211499.jpg","url":"url"}]})
```
## Error
1. Uncaught ReferenceError: JSON_CALLBACK is not defined(…)
2. EXCEPTION: Response with status: 200 Ok for URL: http://192.168.3.9:8200/data/index/home/1/?
3. Uncaught Response："JSONP injected script did not invoke callback."

**Comment by DzmitryShylovich** [comment] 2016-10-25 09:44
If it's an angular issue pls provide a working reproduction in plunkr

**Comment by robwormald** [comment] 2016-10-29 02:56
The expected callback name is `JSONP_CALLBACK` - see https://github.com/angular/angular/blob/master/modules/%40angular/http/src/backends/jsonp_backend.ts#L77-L80

**Comment by DzmitryShylovich** [comment] 2016-12-10 07:53
any updates here? no repro - closing?

**Closed** 2017-01-05 21:41 UTC

**Comment by increos** [comment] 2017-01-07 04:50
I am experiencing the same issues

` 
let url = 'https://registry.npi.io/search/api/public/nppes/pjson/pjson.json?number=1205824083?format=json&callback=JSONP_CALLBACK';
    this.jsonp.get(url).subscribe(res => {console.log(res),
    this.response = res});`

https://plnkr.co/edit/c8hcKpB0JBtRBa8D4pl6?p=preview

**Comment by Alucardz** [comment] 2017-02-01 15:25
^ same issue here

@increos's plnkr reproduces problem accurately,

**Comment by DzmitryShylovich** [comment] 2017-02-01 15:27
@Alucardz pls file a new issue

**Comment by Alucardz** [comment] 2017-02-01 16:02
@DzmitryShylovich 

Nvm, I updated previous comment with edited info. Thanks for the heads up!

**Comment by increos** [comment] 2017-02-02 14:05
@Alucardz Thank you for the root cause...
