### ISSUE TITLE
Ng style doesnt remove old style when the model object changes

### ISSUE THREAD

**Issue by lakshaydulani** [angular/angular#10315] opened 2016-07-27 06:38 UTC
**Current behaviour** - If you assign an object to ngStyle in a div, ngStyle doesnt flush the style properties from the older object when it changes.

**Expected/desired behavior** - All the old object style should be flushed, and only the new object style properties should be applied.

**Reproduction of the problem**
I had forked the plunkr given on [ngStyle github page](https://github.com/angular/angular/blob/master/modules/%40angular/common/src/directives/ng_style.ts)

[This](https://plnkr.co/edit/k4blRSVIHJRrloGNzSUe?p=preview) is my plunkr.
In the plunkr, click on the first style object and it will apply, it will give the div a border. Then click on the second style, it will give it the background color but also keep the border from previous style.

Environment - 
* **Angular version:** 2.0.0-alpha.39
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
 
* **Language:** TS

**Comment by micronyks** [comment] 2016-07-27 07:55
This doesn't work either with `RC.4`. 
Check this new plunker -  http://plnkr.co/edit/sGodR8Erf7cXgoA54hp3?p=preview

**Comment by lakshaydulani** [comment] 2016-07-27 08:07
@micronyks  thanks for replicating with RC.4

**Comment by pkozlowski-opensource** [comment] 2016-07-27 08:14
@micronyks @lakshaydulani could you guys try in the `prod` mode? I kind of suspect that this is the same as #7426

**Comment by lakshaydulani** [comment] 2016-07-27 08:16
@pkozlowski-opensource i tried in prod mode..no luck

**Comment by sod** [comment] 2016-07-27 10:10
I believe it's intended. Would be confusing if ngStyle iterated through every single `element.style` property and set it to undefined, wouldn't it?

The documentations approach is to use one object to define what styles you want to control 
https://angular.io/docs/ts/latest/api/common/index/NgStyle-directive.html

`[ngStyle]="{'font-style': style, 'font-size': size, 'font-weight': weight}"`

**Comment by lakshaydulani** [comment] 2016-07-27 11:02
@sod IMO it should flush the current style property on the element, and set as per new object.
Angular 1 version of the same used to work fine.

**Comment by lakshaydulani** [comment] 2016-07-27 11:14
@sod See this [plunkr](https://plnkr.co/edit/4ok6SYNMKNuIN8J0vpkq?p=preview)
Now I am only making changes to the one object.
Click on first style, and then on second - This time it wont work fine
Now click again on first and then second - From now it will work fine on clicking

**Comment by sod** [comment] 2016-07-27 12:42
@lakshaydulani you are right. It should work like you described. And it's even implemented so. But there seems to be a bug with the KeyValueDiffers. The `forEachRemovedItem` only returns the first removal. Thats the reason why the first style of your object is successfully reverted, but the others don't.

![image](https://cloud.githubusercontent.com/assets/905328/17174780/2934f90e-5404-11e6-874e-c2aeecb18742.png)

This behavior is reproducible in your angular alpha.39 and the latest rc.4

**Comment by pkozlowski-opensource** [comment] 2016-07-27 12:44
An issue in the `KeyValueDiffer` was fixed recently (see #9115). The fix is master but not released yet.

**Comment by vicb** [comment] 2016-07-27 15:31
Will be part of next release

**Closed by vicb** 2016-07-27 15:31 UTC

**Comment by lakshaydulani** [comment] 2016-07-31 04:44
@vicb how soon can we expect the next release?..thanks

**Comment by lakshaydulani** [comment] 2017-03-07 10:33
@vicb sorry but the issue is still there :(

**Comment by DzmitryShylovich** [comment] 2017-03-07 10:58
@lakshaydulani reproduce on Plunkr and file a new issue

**Comment by lakshaydulani** [comment] 2017-03-24 10:57
http://plnkr.co/edit/ccS4gOZgdMqguwIcGRob?p=preview

Click on first button (margin border background), then on second and then on third. Till this, it works fine.

But now click on second button (border background), margin property should remove but it isn't.

**Comment by DzmitryShylovich** [comment] 2017-03-24 11:04
@lakshaydulani please don't comment on closed issues and file a new one. thanks!
