### ISSUE TITLE
Angular 19 [ERROR] Could not resolve "zone.js"

### ISSUE THREAD

**Issue by drfcozapata** [angular/angular#58829] opened 2024-11-22 19:44 UTC
### Which @angular/* package(s) are the source of the bug?

zone.js

### Is this a regression?

Yes

### Description

I am a Vue.js web developer, just starting to learn Angular.

I installed the Angular CLI and created a new project with it. After finishing, I opened VScode and when I run 'npm start' I get the following error message:
```
> first-angular-app@0.0.0 start
> ng serve

Application bundle generation failed. [5.859 seconds]

✘ [ERROR] Could not resolve “zone.js”

    angular:polyfills:angular:polyfills:1:7:
      1 │ import 'zone.js';
        ╵ ~~~~~~~~~

  The Yarn Plug'n'Play manifest forbids importing “zone.js” here because it's not listed as a dependency of this package:

    ../../../../../.pnp.cjs:37:31:
      37 │ “packageDependencies”: [\.
         ╵ ~~

  You can mark the path “zone.js” as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle.

Watch mode enabled. Watching for file changes...
```

I deleted the directory, created the project again and again the same error appears (exactly the same).

I am working from Linux Manjaro and I have installed Node v22.11.0 (LTS).

How can I solve this problem, because my Angular learning process got there?

### Please provide the exception or error you saw

```true
> first-angular-app@0.0.0 start
> ng serve

Application bundle generation failed. [5.859 seconds]

✘ [ERROR] Could not resolve "zone.js"

    angular:polyfills:angular:polyfills:1:7:
      1 │ import 'zone.js';
        ╵        ~~~~~~~~~

  The Yarn Plug'n'Play manifest forbids importing "zone.js" here because it's not listed as a dependency of this package:

    ../../../../.pnp.cjs:37:31:
      37 │         "packageDependencies": [\
         ╵                                ~~

  You can mark the path "zone.js" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle.


Watch mode enabled. Watching for file changes...
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 19.0.1
Node: 22.11.0
Package Manager: npm 10.9.0
OS: linux x64

Angular: 19.0.0
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1900.1
@angular-devkit/build-angular   19.0.1
@angular-devkit/core            19.0.1
@angular-devkit/schematics      19.0.1
@angular/cli                    19.0.1
@schematics/angular             19.0.1
rxjs                            7.8.1
typescript                      5.6.3
zone.js                         0.15.0
```

**Comment by hakimio** [comment] 2024-11-22 19:47
Is `zone.js` part of the dependencies in `package.json`?

**Comment by alan-agius4** [comment] 2024-11-22 20:04
Duplicate of https://github.com/angular/angular-cli/issues/28940

**Closed by alan-agius4** 2024-11-22 20:04 UTC

**Comment by drfcozapata** [comment] 2024-11-22 21:49
> Is `zone.js` part of the dependencies in `package.json`?

Yes, of course. That's how the Angular CLI creates it.
