### ISSUE TITLE
Get a components' ChangeDetectorRef without injection

### ISSUE THREAD

**Issue by tsproesser** [angular/angular#39043] opened 2020-09-29 13:37 UTC
Maybe this is already possible, but I haven't found a possibility to do so?

In my scenario I want to get a components' CDR in its baseclass. Since this case is pretty rare, I do not want to use the constructor, since all my controls would need to inject / pass it.

Tried it via StackOverflow already, but couldn't find a solution:

https://stackoverflow.com/questions/63577360/get-changedetectorref-at-runtime-without-injection
https://stackoverflow.com/questions/59013233/access-changedetectorref-or-componentref-of-child-component-from-parent-componen#comment112463351_59013233

**Comment by Achilles1515** [comment] 2020-09-29 18:40
https://github.com/angular/angular/issues/38626

**Comment by sonukapoor** [comment] 2020-09-29 22:48
@tsproesser It seems that this issue is the same as linked by @Achilles1515. Can we close this?

**Comment by AndrewKushnir** [comment] 2020-09-30 03:00
As it was mentioned above, the issue looks like a duplicate of #38626, so I'm closing this one. Feel free to reopen if this problem/question is a different one.

**Closed by AndrewKushnir** 2020-09-30 03:00 UTC

**Comment by tsproesser** [comment] 2020-10-05 10:20
Yeah, I'm so sorry! Been a while and thought I only posted it on stockoverflow! Thank you!
