### ISSUE TITLE
ngOnInit doesn't work when ngZone is noop and it's lazy

### ISSUE THREAD

**Issue by wizardnet972** [angular/angular#43388] opened 2021-09-08 14:05 UTC
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

In `shell.component.ts` file [I add this code](https://github.com/wizardnet972/ng-lazy/blob/main/src/app/shell.component.ts#L13):
 ```
   ngOnInit() { 
        console.log('in shell ngOnInit');
   }
```
When I run the app I expect to see the log in the console.
Therefore angular doesn't invoke the `ngOnInit` method.

I [disabled ngZone](https://github.com/wizardnet972/ng-lazy/blob/main/src/main.ts#L11) (but the core of angular can run without zone now right?) and the component with the module is [lazy loading](https://github.com/wizardnet972/ng-lazy/blob/main/src/app/app-routing.module.ts#L7)

### Please provide a link to a minimal reproduction of the bug

https://codesandbox.io/s/github/wizardnet972/ng-lazy

### Please provide the exception or error you saw

```true
no errors. but it's should output the log on ngOnInit function.
```

### Please provide the environment you discovered this bug in

```true
Angular CLI: 12.2.4
Node: 14.17.1
Package Manager: npm 6.14.13
OS: darwin x64

Angular: 12.2.4
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.4
@angular-devkit/build-angular   12.2.4
@angular-devkit/core            12.2.4
@angular-devkit/schematics      12.2.4
@schematics/angular             12.2.4
rxjs                            6.6.7
typescript                      4.3.5
```

### Anything else?

https://github.com/wizardnet972/ng-lazy

**Comment by JoostK** [comment] 2021-10-01 20:25
The `RouterOutlet` creates the component using `ViewContainerRef.createComponent`, which creates the DOM nodes and attaches the component to the change detector, but it does _not_ run change detection over the view. It relies on the next application tick to run the initial change detection on the view, given that it's been attached to the change detector.

Without a zone, however, there won't be any automated invocations of application ticks. As a result, a subsequent change detection cycle is never started.

You can get this to work today by listening the the `activated` event on the `RouterOutlet` and triggering change detection using `ApplicationRef.tick`:

```ts
import { ApplicationRef, Component, Inject } from '@angular/core';

@Component({
  selector: 'app-root',
  template: `<router-outlet (activate)="tick()"></router-outlet>`
})
export class AppComponent {
  title = 'ng-lazy';

  constructor(@Inject(ApplicationRef) private appRef: ApplicationRef) {}

  tick() {
    this.appRef.tick();
  }
}
```
<sup>note: I'm using an explicit `@Inject(ApplicationRef)` because Codesandbox doesn't appear to provide the constructor types as runtime metadata. Production code may not need that explicit decorator.<sup>

**Comment by alxhub** [comment] 2022-05-04 14:38
I'm going to close this as Angular is working as intended here. Most Angular applications today will want to use `zone.js` to monitor application activity and allow for change detection to be scheduled. If you choose to opt out from zones, it's your responsibility to run change detection when it needs to happen - such as @JoostK describes above.

**Closed by alxhub** 2022-05-04 14:38 UTC
Labels: comp: router, comp: core, comp: zones, core: change detection, core: dynamic view creation, router: lazy loading, P4
