### ISSUE TITLE
Template interpolation broke when used on the style attribute

### ISSUE THREAD

**Issue by daco** [angular/angular#8745] opened 2016-05-20 09:02 UTC
This Plunker
http://plnkr.co/edit/vTsxIOfepOd7BCZxueQt

In previous Angular 2 versions I could use something like this in my template

`<div style="background-image: url({{background}});"></div>`

This broke in RC1. If I put the double curly in the id attribute (for instance), it does work. So it might has something to do with the style attribute.

Upon investigating further, I found that I could (should?) be writing this as:

`<div [style.backgroundImage]="'url('+background+')'"></div>`

This does not work.
Even used with a string, this does not work:

`<div [style.backgroundImage]="'url(data:image/gif;base64,R0lGODlhAQABAIAAAAUEBAAAACwAAAAAAQABAAACAkQBADs=)'"></div>`

Trying the same thing on style.backgoundColor with a string 'red' as value for instance does work! So I'm not sure what's going on here.

**Comment by ericmartinezr** [comment] 2016-05-20 11:48
See https://github.com/angular/angular/issues/8491

**Comment by pkozlowski-opensource** [comment] 2016-06-02 17:41
Yep, duplicate of #8491. Thnx @ericmartinezr

**Closed by pkozlowski-opensource** 2016-06-02 17:41 UTC
