### ISSUE TITLE
Bad error message "No provider for Platform!" when a module import is missed

### ISSUE THREAD

**Issue by vikerman** [angular/angular#20251] opened 2017-11-07 19:30 UTC
When a module whose component is used somewhere(router, component) is missed from being imported from the current module, the error message is "No provider for Platform!".

It should rather point to the Component whose module is missing.

**Comment by jelbourn** [comment] 2017-11-07 19:35
Duplicate of #17446

**Closed by jelbourn** 2017-11-07 19:35 UTC
Labels: comp: core & compiler, hotlist: error messages
