### ISSUE TITLE
Error when trying to directly access to a route in a lazy loaded module 

### ISSUE THREAD

**Issue by jon301** [angular/angular#12682] opened 2016-11-03 14:14 UTC
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
We get a JS error in the console when trying to directly access a route of a lazy loaded module.

**Expected behavior**
No JS error.

**Minimal reproduction of the problem with instructions**
No plunker demo as you have to directly access a URL in your browser.
- Clone this repo : https://github.com/jon301/ng2-router-bug
- `npm install` or `yarn`
- `npm start`
- Go to URL : http://localhost:4200/#/home
- Then type this URL in your browser : http://localhost:4200/#/road/second/beta
- You'll see the following error in the console :

```
error_handler.js:48 EXCEPTION: Uncaught (in promise): TypeError: Cannot read property 'routes' of undefined
TypeError: Cannot read property 'routes' of undefined
    at getChildConfig (http://localhost:4200/main.bundle.js:60178:35)
    at Recognizer.processSegmentAgainstRoute (http://localhost:4200/main.bundle.js:60147:27)
    at Recognizer.processSegment (http://localhost:4200/main.bundle.js:60126:29)
    at Recognizer.processSegmentAgainstRoute (http://localhost:4200/main.bundle.js:60158:33)
    at Recognizer.processSegment (http://localhost:4200/main.bundle.js:60126:29)
    at Recognizer.processSegmentAgainstRoute (http://localhost:4200/main.bundle.js:60158:33)
    at Recognizer.processSegment (http://localhost:4200/main.bundle.js:60126:29)
    at Recognizer.processSegmentGroup (http://localhost:4200/main.bundle.js:60112:25)
    at http://localhost:4200/main.bundle.js:60117:178
    at http://localhost:4200/main.bundle.js:8182:30
```

![capture d ecran 2016-11-03 a 14 53 03](https://cloud.githubusercontent.com/assets/122108/19969102/96fd936c-a1d7-11e6-9831-82265cf13871.png)

* **Angular version:** 2.1.0

* **Browser:** Chrome 54.0.2840.71 (64-bit)
 
* **Language:** TypeScript 2.0.3

**Comment by trsh** [comment] 2016-11-08 11:25
Same for me!

**Comment by vsavkin** [comment] 2016-11-14 23:11
Please provide a plunkr reproducing the issue. You can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5

**Comment by jon301** [comment] 2016-11-16 09:46
Hi @vsavkin,
I've created the plunkr but could not reproduce the issue. Here is the link anyway : 
https://plnkr.co/edit/77LgVT4peLZRz39SePZT?p=preview

I don't know if it's related to that but as I can see in the console, files are lazy loaded individually in the plunkr and not as 1 JS chunk when the app is compiled via webpack (e.g. with angular-cli).

You can still reproduce the issue if you clone this repository : 
https://github.com/jon301/ng2-router-bug

Here is the GIF of the demo :
http://d.pr/i/LBYm

Thank you for your help !

**Comment by jon301** [comment] 2016-11-16 10:10
I have simplified my example in this repository :
https://github.com/jon301/ng2-router-bug

Please check it out
Thanks !

**Comment by mcnj2** [comment] 2016-12-30 07:53
What is the solution for this issue?

**Comment by DzmitryShylovich** [comment] 2016-12-30 08:48
Can't reproduce in plunkr https://plnkr.co/edit/6Rm2UlyNwLnbVL1AtcAs?p=preview

The bug appears to be fixed in the latest version or it's a cli bug.

**Comment by DzmitryShylovich** [comment] 2017-01-18 13:03
@pkozlowski-opensource can be closed

**Closed** 2017-01-18 13:04 UTC
Labels: comp: router, state: Need repro
