### ISSUE TITLE
Disabled attribute doesn't work with Reactive Forms

### ISSUE THREAD

**Issue by Bielik20** [angular/angular#24941] opened 2018-07-17 22:24 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

When using reactive forms it isn't disabled and we receive this message:
![image](https://user-images.githubusercontent.com/13436218/42288629-cfb62ff2-7fbb-11e8-9ab4-75989ca18a7d.png)

While I understand purpose of this message, setting `disabled` in form control prevents any changes to that field. I want only manual input to be disabled due to https://github.com/angular/material2/issues/11936 and https://github.com/angular/material2/issues/12064.

## Expected behavior

It should work just like in [example](https://material.angular.io/components/datepicker/examples) -> Disabled datepicker -> Input disabled (the third one)

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/angular-datepicker-disable-bug

## Environment

<pre><code>
Angular version: 6.0.7

Browser:
- [X] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

## Misc

I originally posted this issue in here: https://github.com/angular/material2/issues/12065

**Comment by trotyl** [comment] 2018-07-18 04:54
Duplicate of https://github.com/angular/angular/issues/11271, https://github.com/angular/angular/issues/11324

**Comment by kara** [comment] 2018-07-18 16:59
Looks like a duplicate of existing issue, closing.

**Closed by kara** 2018-07-18 16:59 UTC
Labels: comp: forms
