### ISSUE TITLE
unicode letters (as in valid JS identifiers) not allowed in template

### ISSUE THREAD

**Issue by ZimaTechOli** [angular/angular#46391] opened 2022-06-16 13:42 UTC
### Which @angular/* package(s) are the source of the bug?

compiler

### Is this a regression?

No

### Description

Identifiers that contain unicode letters (e.g. greek letters like π) work perfectly fine in TypeScript and JavaScript, but can't be used in Angular templates.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-uhvxwv?file=src/app/app.component.html

### Please provide the exception or error you saw

```true
Error: projects/google2/src/app/views/clients/clients.view.html:6:9 - error NG5002: Parser Error: Unexpected token 'Lexer Error: Unexpected character [Δ] at column 15 in expression [ client.loadedΔ ]' at column 16 in [ {{ client.loadedΔ }} ] in P:\Angular\alphabet\projects\google2\src\app\views\clients\clients.view.html@5:8

6         {{ client.loadedΔ }}
          ~~~~~~~~~~~~~~~~~~~~
7       </div>
  ~~~~~~

  projects/google2/src/app/views/clients/clients.view.ts:6:16
    6   templateUrl: './clients.view.html',
                     ~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component ClientsView.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 14.0.1
Node: 14.15.1
Package Manager: npm 6.14.8
OS: win32 x64

Angular: 14.0.1
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1400.1
@angular-devkit/build-angular   14.0.1
@angular-devkit/core            14.0.1
@angular-devkit/schematics      14.0.1
@schematics/angular             14.0.1
ng-packagr                      14.0.2
rxjs                            7.5.5
typescript                      4.6.3
```

### Anything else?

I found this PR from recently which -- if I understand correctly -- was denied because it accepts too broadly: https://github.com/angular/angular/pull/46194

However, I'm kinda missing an admission that only accepting ASCII characters in identifiers is an issue.

**Comment by pkozlowski-opensource** [comment] 2022-06-16 13:59
> However, I'm kinda missing an admission that only accepting ASCII characters in identifiers is an issue.

We've got an issue that tracks this request: #517 (it was referenced from the PR #46194).

Closing as a duplicate of #517

**Closed** 2022-06-16 13:59 UTC
