### ISSUE TITLE
Service worker not reponse wih gzip

### ISSUE THREAD

**Issue by kfathy-ys** [angular/angular#44007] opened 2021-11-01 16:51 UTC
### Which @angular/* package(s) are the source of the bug?

service-worker

### Is this a regression?

Yes

### Description

When i apply gzip in my iis it work well with first request that handled by broweser not by service worker but request when sw registered and it send request without gzip encodeing and so response return without gzip

**Comment by gkalpak** [comment] 2021-11-01 17:51
Yes, this is happening because the SW strips off request headers.
This is being tracked in #24227.

Closing as a duplicate of #24227.

**Closed by gkalpak** 2021-11-01 17:51 UTC
