### ISSUE TITLE
Forms: Allow to change updateOn flag dynamically

### ISSUE THREAD

**Issue by bene-starzengruber** [angular/angular#37689] opened 2020-06-23 15:37 UTC
# 🚀 feature request
Expose method to update the "updateOn" strategy after creation of a form control

### Relevant Package
@angular/forms

### Description
Use Case: User can change the strategy with a toggle button
Right now it is not possible to do this after the form was created initially

### Describe the solution you'd like
Add a method to update the "updateOn" property

### Describe alternatives you've considered

- clone the whole formGroup into a new one with the desired updateOn strategy but this has many side-effects
- hard-overwrite the dependsOn getter which seems to work but is ugly and error-prone of course

```
    Object.defineProperty(this.formGroup, 'updateOn', {
      get: () => wantedUpdateStrategy,
      configurable: true
    });
```

**Comment by AndrewKushnir** [comment] 2020-06-23 18:21
Hi @bene-starzengruber, thanks for creating this feature request. It looks like it's a duplicate of #35005, so I'm closing this one. Please subscribe to #35005 for further discussions and updates. Thank you.

**Closed by AndrewKushnir** 2020-06-23 18:21 UTC
Labels: comp: forms, type: feature
