### ISSUE TITLE
Templates erroring when <code> or <pre> includes any JS/TS "Code" with brackets, tags, etc

### ISSUE THREAD

**Issue by MarkPieszak** [angular/angular#12916] opened 2016-11-16 15:37 UTC
**I'm submitting a ...**  (check one with "x")
[x] bug report 

**Current behavior**
* **I'm submitting a ...**
- [X] bug report
* **What modules are related to this Issue?**
- [X universal

* **What is the current behavior?**

Unable to server-render "code" placed in the `template` as the parser isn't sure how to handle it.

    // adding this to a template causes the error
    <code>
        constructor () {}
    </code>

**Error outputed:**

> zone.js:388 Unhandled Promise rejection: Template parse errors:
> Unexpected character "EOF" (Do you have an unescaped "{" in your template? Use "{{ '{' }}") to escape it.) ("
>     </code>
>     </div>
>   [ERROR ->]"): App@7:2
> Invalid ICU message. Missing '}'. ("
>     </code>
>     </div>
>   [ERROR ->]"): App@7:2 ; Zone: <root> ; Task: Promise.then ; Value: Error: Template parse errors:(…) Error: Template parse errors:
> Unexpected character "EOF" (Do you have an unescaped "{" in your template? Use "{{ '{' }}") to escape it.) ("
>     </code>
>     </div>
>   [ERROR ->]"): App@7:2
> Invalid ICU message. Missing '}'. ("
>     </code>
>     </div>
>   [ERROR ->]"): App@7:2
>     at TemplateParser.parse (https://unpkg.com/@angular/compiler/bundles/compiler.umd.js:7728:21)
>     at RuntimeCompiler._compileTemplate (https://unpkg.com/@angular/compiler/bundles/compiler.umd.js:17503:53)
>     at eval (https://unpkg.com/@angular/compiler/bundles/compiler.umd.js:17423:64)
>     at Set.forEach (native)
>     at RuntimeCompiler._compileComponents (https://unpkg.com/@angular/compiler/bundles/compiler.umd.js:17423:21)
>     at createResult (https://unpkg.com/@angular/compiler/bundles/compiler.umd.js:17319:21)
>     at ZoneDelegate.invoke (https://unpkg.com/zone.js@0.6.26/dist/zone.js:232:26)
>     at Zone.run (https://unpkg.com/zone.js@0.6.26/dist/zone.js:114:43)
>     at https://unpkg.com/zone.js@0.6.26/dist/zone.js:502:57
>     at ZoneDelegate.invokeTask (https://unpkg.com/zone.js@0.6.26/dist/zone.js:265:35)

**Expected behavior**
Being able to drop regular code into `<pre> | <code>` tags, without having to do any special preparation of code so the template parser can handle it.
(I'm not positive if this is possible)

**Minimal reproduction of the problem with instructions**
**Plunkr demo** :
http://plnkr.co/edit/MdEDMLEVAmGYeywaKchN?p=preview

**Please tell us about your environment:**
Any OS

* **Angular version:** 2.0.X
Happens with latest: **2.2.0** as well

* **Browser:** [all]
 
* **Language:** TypeScript 2.*

**Comment by vicb** [comment] 2016-11-16 15:57
duplicate of https://github.com/angular/angular/issues/11859

Solution is to replace `{` with `{{ '{' }}`

Still not possible in non bindable elements

**Closed by vicb** 2016-11-16 15:57 UTC

**Comment by MarkPieszak** [comment] 2016-11-16 16:01
@vicb Thanks Victor, apologies for the duplicate didn't find that one.

Yeah I saw that, I wonder if there's someway in the future to flag areas in templates where it can not search for `{{` when it sees that initial `{` and just let's it all stay as a `String`.

**Comment by vicb** [comment] 2016-11-16 18:58
I think we have a PR pending but I haven't had a chance to review it yet !
