### ISSUE TITLE
Date pipe value does not update in view

### ISSUE THREAD

**Issue by royappa** [angular/angular#15272] opened 2017-03-18 09:04 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
A variable piped into the "date" transform does not show the new value whenever the class modifies the variable. If the date transform is removed, the update happens normally.

**Expected behavior**
When the variable is updated by the class, its view in the HTML should update as well.

**Minimal reproduction of the problem with instructions**
See https://embed.plnkr.co/h15VKoTc8K3j39zoerdK/
Click the "Next Day" button and note how the date changes as we click.
Then in app.ts template, change "{{selectedDate}}" to "{{selectedDate | date}}. 
Click "Next Day" again. The displayed date does NOT change. Tried with two people and two different browsers.

**What is the motivation / use case for changing the behavior?**
Simple next day/previous day buttons using the date pipe to format dates in the view.

**Please tell us about your environment:**

Windows 7, WebStorm, npm, multiple web servers

* **Angular version:** 2.0.X

@angular/core/package.json says version 2.4.8

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 Chrome, Firefox (latest)

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 2

* **Node (for AoT issues):** `node --version` =   
v6.10.0

**Comment by DzmitryShylovich** [comment] 2017-03-18 10:04
Date pipe is pure https://angular.io/docs/ts/latest/guide/pipes.html#!#pure-and-impure-pipes

**Comment by pkozlowski-opensource** [comment] 2017-03-18 10:41
@DzmitryShylovich is right - you would have to clone Date object instance instead of just mutating it in place. Closing since works as designed / expected.

**Closed by pkozlowski-opensource** 2017-03-18 10:41 UTC

**Comment by royappa** [comment] 2017-03-18 11:48
Works as expected when cloning. Thank you.
