### ISSUE TITLE
Animation increment/decrement not working properly

### ISSUE THREAD

**Issue by kolkov** [angular/angular#37214] opened 2020-05-20 06:41 UTC
# 🐞 bug report

### Affected Package
@angular/animations
@angular/animations/browser

### Is this a regression?

I don't know

### Description

Transition increment/decrement works only increment for +1 or decrement -1.

## 🔬 Minimal Reproduction
This library have demo app:
https://github.com/kolkov/ngx-gallery/tree/reusable/projects/gallery-app
https://github.com/kolkov/ngx-gallery/blob/0fce1a39b68b77a75db3167c0c61bbb0bf571ee6/projects/gallery/src/lib/ngx-gallery-image/ngx-gallery-image.component.ts#L31

https://ngx-gallery.kolkov.ru/ - live example

If we click on neighborhood images on thumbnails preview all works as expected, but if we click on other preview images we don't see any transitions.

**Comment by pkozlowski-opensource** [comment] 2020-05-20 07:21
@kolkov could you please extract essential bits of the problem to a minimal reproduce scenario and share it with https://stackblitz.com/

There is quite a bit of code in your library and it is not clear right now if this is the animation bug or some other problem in the implementation. This is why we need a minimal reproduce scenario to make it "painfully" clear that the root of the problem is in Angular.

**Comment by kolkov** [comment] 2020-05-21 08:48
@pkozlowski-opensource Thanks! I tryed to implement and reproduce this bug, but I could not. I tried to find some bugs in the library, but also could not. Code is identical.
What could be the problem and how can I debug animations in the Angular code?

https://github.com/kolkov/ngx-gallery/blob/c2e77a78a5bb3156f86a7fdb249a8afeb9aaa7f0/projects/gallery/src/lib/ngx-gallery-image/ngx-gallery-image.component.ts#L31

I removed all extra code from template:
https://github.com/kolkov/ngx-gallery/blob/c2e77a78a5bb3156f86a7fdb249a8afeb9aaa7f0/projects/gallery/src/lib/ngx-gallery-image/ngx-gallery-image.component.html#L7

https://stackblitz.com/edit/angular-ivy-3byttw?file=src%2Fapp%2Fapp.component.ts

**Comment by kolkov** [comment] 2020-05-21 12:48
I tryed to change getImages to images, and this solve my problem. 
![image](https://user-images.githubusercontent.com/3740898/82560035-4f2e3d80-9b79-11ea-93b0-b0896489d33c.png)

`getImages()` code:
https://github.com/kolkov/ngx-gallery/blob/c2e77a78a5bb3156f86a7fdb249a8afeb9aaa7f0/projects/gallery/src/lib/ngx-gallery-image/ngx-gallery-image.component.ts#L282


But I found another problem: after I change library code, changes in the browser not appearing. I need to change code twice to see this changes.

**Comment by matsko** [comment] 2020-05-27 18:50
Hello @kolkov it's still unclear what's going on here. I've tried playing with your original demo and I can definitely see a failure. From the looks of it, it looks like it fails when the number jumps.

I changed around your stackblitz demo to see if I could capture that, but it looks like it still isn't revealing the issue: https://stackblitz.com/edit/angular-ivy-3byttw?file=src%2Fapp%2Fapp.component.ts

This needs more investigation, but we now have a better idea of what's going on. Please see if you can mess around with the demo more and let me know if you get it to consistently fail with the bug we're after.

**Comment by jelbourn** [comment] 2020-10-26 20:53
Closing since the original issue seems to be resolved (or at least worked around) and we were never able to make a minimal reproduction.

**Closed by jelbourn** 2020-10-26 20:53 UTC
Labels: comp: animations, state: needs more investigation, triage #1
