### ISSUE TITLE
Enhance testing component fixtures to enable input updates using aliased names.

### ISSUE THREAD

**Issue by dpsthree** [angular/angular#23128] opened 2018-04-02 15:44 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

The @Input (and @Output) property annotation accepts a string value that acts as an external naming alias.
`@Input('inputAliasName') internalPropertyName: string;`
This enables easy internal refactoring of components without breaking the external contract. Ideally, these alias names would be used during unit and integration tests when input values need to be changed; ensuring that the external contact remains intact.

There does not seem to be a means to update properties in this way, or it is difficult to find in documentation.

## Expected behavior

An instance of a ComponentFixture should allow R/W access to inputs by way of their alias. Something similar to:
`
fixture.inputs['inputAliasName']
`

## Minimal reproduction of the problem with instructions

N/A
## What is the motivation / use case for changing the behavior?

Allows the authoring of tests that verify external component contract was not broken as part of a refactor.

## Environment

<pre><code>
Angular version: 5.2.9

</code></pre>

**Comment by alxhub** [comment] 2022-04-14 23:22
Closing as a spiritual duplicate of #12313 - we want to rethink APIs around interacting with the component under test.

**Closed by alxhub** 2022-04-14 23:22 UTC
Labels: feature, comp: testing, freq1: low, P4, insufficient votes, votes required
