### ISSUE TITLE
ngFor on numeric inputs of equal values updates DOM of next value when one value changes

### ISSUE THREAD

**Issue by natekemp21** [angular/angular#38891] opened 2020-09-17 18:32 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/core

### Is this a regression?

 No

### Description

 Create array of numbers of equal value.  Use *ngFor to build numeric inputs for each.  Change the value of one, which causes the DOM value of the next to also be changed (although the underlying value in the array does not change).

## 🔬 Minimal Reproduction

 https://stackblitz.com/edit/number-input-bug?file=src%2Fapp%2Fapp.component.ts

## 🌍  Your Environment

**Angular Version:**
<pre><code>

10.0.9

</code></pre>

**Anything else relevant?**

**Comment by ericmartinezr** [comment] 2020-09-17 18:47
You can solve it by using [trackBy](https://angular.io/api/core/TrackByFunction), see https://stackblitz.com/edit/number-input-bug-yg5wkg?file=src%2Fapp%2Fapp.component.ts

**Comment by natekemp21** [comment] 2020-09-17 18:54
> You can solve it by using [trackBy](https://angular.io/api/core/TrackByFunction), see https://stackblitz.com/edit/number-input-bug-yg5wkg?file=src%2Fapp%2Fapp.component.ts

Thank you.  Is this the correct method of using ngFor with an array of equal values, or is it more of a work-around?  It's odd that it only happens when the values are equal.

**Comment by netfreak9** [comment] 2020-09-17 18:59
Unsubscribe

**Comment by petebacondarwin** [comment] 2020-09-17 19:01
This is the correct approach. The ngFor directive needs to be able to differentiate between the items in the collection. If they are primitives (e.g. numbers) then they have no "identity" other than their value. So it cannot tell the difference between the three 10s.
Using trackby gives the ngFor the ability to distinguish between the items without having to use the value as their id.

Closing as this is not a bug in Angular.

**Closed by petebacondarwin** 2020-09-17 19:01 UTC

**Comment by natekemp21** [comment] 2020-09-17 19:06
Shouldn't Angular decide if the collection is primitives and track them itself?  Seems unintuitive to have to know that little trick just for a case as obscure as this.

**Comment by petebacondarwin** [comment] 2020-09-17 19:24
It could do that but then a check of the entire array would have to be done on every change detection to see whether any of the items in the array. This declarative approach maintains performance.
