### ISSUE TITLE
Angular Service Worker not working offline (fetched from Express server)

### ISSUE THREAD

**Issue by nikhilnayyar002** [angular/angular#32801] opened 2019-09-21 16:17 UTC
I actually have Angular PWA production compiled app.

(URL: https://niktestapp-7422f.firebaseapp.com)
I have served it on firebase and the service worker is working and sending cached response from cache storage in offline mode as well. In short no problem hosting at firebase.

(URL: https://nik-exam-module.herokuapp.com)
When I serve same app from heroku (Nodejs/ Express), the service worker is registered but does not seem to work in offline mode. There is a chrome 504 error page in offline mode.

I have a build folder which contains angular prod. code and contains index and many other files with assets folder. I have the code for express server as:

```
var app = express();
app.enable("trust proxy");
app.use(function(req, res, next) {
   if (req.protocol == "https") {
    next();
   } else {
    res.redirect(`https://${req.hostname}`);
   }
});
app.use(compression());
app.use(helmet());
app.use(morgan("dev"));
app.use(express.json());
app.use(express.urlencoded({ extended: false }));

app.get('*.*', express.static(path.join(__dirname, "build")));

/** use passport local strategy */
app.use(passport.initialize());
/** allow cross-origin acess */

app.use(config.restAPI + "/auth", user_router_1.UserRouter);

app.get("/*", function(req, res, next) {
  if (!req.path.includes(config.restAPI))
     res.sendFile(path.join(__dirname, "build", "index.html"));
  else next();
});
```

Also i want to mention that i saw in network panel a unusual fetch by ngsw-worker.js at url:

https://nik-exam-module.herokuapp.com/index.html?ngsw-cache-bust=0.12909452330954796

This was not fetched on the same app hosted on firebase. Also I noticed that some files were not seen to be fetched by ngsw-worker.js from heroku server:

![image](https://user-images.githubusercontent.com/38173563/65376032-fb511900-dcb8-11e9-9da8-b218995a97ad.png)

I also want to compare the cache size stored by both app examples:

![image](https://user-images.githubusercontent.com/38173563/65376016-d78dd300-dcb8-11e9-8ba9-abd27e9f3c4a.png)

![image](https://user-images.githubusercontent.com/38173563/65376062-2c314e00-dcb9-11e9-841f-df5a6c373d11.png)

These shows that app hosted on firebase is caching more files than one on heroku version.

I am using:

Angular 8.0.2
Node v10.16.0
Express v4.17.1

   and 

    "@angular/pwa": "^0.803.3",
    "@angular/service-worker": "~8.0.1",

Thanks,

**Comment by gkalpak** [comment] 2019-09-23 19:36
As seen from the [debug info][1] at https://nik-exam-module.herokuapp.com/ngsw/state, there is a hash mismatch that causes the SW to not work:

> Driver state: EXISTING_CLIENTS_ONLY (Degraded due to: Hash mismatch (cacheBustedFetchFromNetwork): https://nik-exam-module.herokuapp.com/index.html: expected ff1e7537f0edb9c81dcf6864cd6f80f5d1e14b48, got c2d52885bdc8c9f5139619853877568c589238cb (after cache busting)

This basically means that the content of the served file is different than the content of the file right after the build. This usually happens when the server (or a proxy) modifies the file while serving (e.g. optimizing by removing whitespace or something similar). I suspect this is what happens here in the heroku-served app.

##
Closing, because everything works as intended (afaict), but feel free to continue the discussion below. 

[1]: https://angular.io/guide/service-worker-devops#locating-and-analyzing-debugging-information

**Closed by gkalpak** 2019-09-23 19:36 UTC
Labels: comp: service-worker

**Comment by nikhilnayyar002** [comment] 2019-09-26 08:23
yes you are right. When application is initially loaded in the browser.

![image](https://user-images.githubusercontent.com/38173563/65671263-8f7a0200-e064-11e9-8f54-58a03b2bf2c0.png)

At the last one can see that the index.html file was fetched but got a hash mismatch. Therefore this URL was called:

`index.html?ngsw-cache-bust=.....
`

All other static contents have no hash mismatch. I am currently not able to find where the problem is occuring in nodejs/express server. I will see what can be done.

Thanks for your answer by the way.
