### ISSUE TITLE
Render null strings as empty strings in the template

### ISSUE THREAD

**Issue by mh0** [angular/angular#43503] opened 2021-09-18 12:17 UTC
### Which @angular/* package(s) are relevant/releated to the feature request?

core

### Description

Null strings are currently rendered as 'null' in the template, while most developers would expect an empty string instead. 
This is relevant for other types as well.

### Proposed solution

Render null values as empty strings, i.e. the rendering function should return '' if value **===** null.
undefined should be rendered as is.

Another possibility is to make this a compiler option or provide a public interface for custom implementations.

### Alternatives considered

Currently, we need to specify the default value in the template: {{value||''}}, which is undesirable and could lead to undetected errors.

**Comment by jnizet** [comment] 2021-09-19 05:55
Hi @mh0 

Null strings are already rendered as the empty string, and not as 'null'. See this stackblitz: https://stackblitz.com/edit/angular-ivy-xgj4rw?file=src%2Fapp%2Fapp.component.html.

My guess is that you're concatenating null with something else, but then the rules of JS apply (and it should stay that way, IMHO). See the third example in the above stackblitz.

**Comment by mh0** [comment] 2021-09-19 13:11
Hi @jnizet 

I understand that both null and undefined single values are rendered as an empty strings in the environment you kindly provided, while being rendered as 'null' and 'undefined' when encountered in a template expression. 

I conclude that angular handles single values and expressions differently, and treats undefined and null as the same. 

May be the most durable solution would be to provide an interface to handle the 4 cases separately ?

**Comment by petebacondarwin** [comment] 2021-09-19 13:18
@jnizet - thanks for digging in to this.
@mh0 - this is working as expected. Angular expressions are evaluated in the same way as JavaScript, so concatenating a null value with a string will result in the string "null" being printed. If you do not want this behaviour then it is up to you to ensure that the `null` is converted before you concatenate it with a string.

Closing as this is expected and by design.

**Closed by petebacondarwin** 2021-09-19 13:18 UTC
