### ISSUE TITLE
Angular 4.0.0 animations

### ISSUE THREAD

**Issue by misty000** [angular/angular#15507] opened 2017-03-26 14:58 UTC
[https://plnkr.co/edit/XpISx8AoH6jmN6D57139?p=preview](https://plnkr.co/edit/XpISx8AoH6jmN6D57139?p=preview)

Angular version: 4.0.X
Browser: [Chrome 56 | Edge ]

The animations in Angular2
![Angular2](http://git.oschina.net/ellipse/ng-covalent-sample-2/raw/master/ng2.gif)
[GIF](http://git.oschina.net/ellipse/ng-covalent-sample-2/raw/master/ng2.gif)

But there's something wrong after upgrade to Angular4
![Angular4](http://git.oschina.net/ellipse/ng-covalent-sample-4/raw/master/ng4.gif)
[GIF](http://git.oschina.net/ellipse/ng-covalent-sample-4/raw/master/ng4.gif)

 src /  app /  todolist /  todolist.component.ts
```
@Component({
  selector: 'cs-todolist',
  templateUrl: './todolist.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
  animations: [
    trigger('shrinkOut', [
      state('in', style({})),
      transition('* => void', [
        style({ height: '*', opacity: 1 }),
        animate(1000, style({ height: 0, opacity: 0 }))
      ]),
      transition('void => *', [
        style({ height: 0, opacity: 0 }),
        animate(1000, style({ height: '*', opacity: 1 }))
      ])
    ])
  ]
})
```

Angular2 sample project
[http://git.oschina.net/ellipse/ng-covalent-sample-2](http://git.oschina.net/ellipse/ng-covalent-sample-2)

Angular4 sample project
[http://git.oschina.net/ellipse/ng-covalent-sample-4](http://git.oschina.net/ellipse/ng-covalent-sample-4)

**Comment by Toxicable** [comment] 2017-03-27 07:39
I tried to do a minimal reproduction of your error here but could not
https://plnkr.co/edit/UTIuwd5NYdXI60dTEdXG?p=preview
Could you confirm that what I have here is the same as what you got? I copied the code you posted above

**Comment by misty000** [comment] 2017-03-27 08:37
I create a method in App
```  
add(){
    this.items.unshift({id:1, name:'item'})
  }
```
call add() method, the new div‘s height should have a transition from 0 to computed-value, but it's not.
It display directly

[https://plnkr.co/edit/1GLykUdcTKQrV3HUo42L?p=preview](https://plnkr.co/edit/1GLykUdcTKQrV3HUo42L?p=preview)

**Comment by craftyInstigator** [comment] 2017-03-27 08:42
+1. After upgrading to 4.0.0 all animations involving height: '*' are broken and jump in the beginning or the end.

**Comment by Toxicable** [comment] 2017-03-27 08:46
Height does not include padding (I missed that you were animating height first time around)
https://plnkr.co/edit/XpISx8AoH6jmN6D57139?p=preview
this looks smooth as butter now

**Comment by misty000** [comment] 2017-03-27 08:48
yes.
but delete 'height: 60px;', the problem appear again

**Comment by Toxicable** [comment] 2017-03-27 08:52
https://plnkr.co/edit/XpISx8AoH6jmN6D57139?p=preview - see line 34
Right, okay I see what you're saying now. I believe this is because it dosen't know how high to animate to, no idea if this is intended or not.
@DzmitryShylovich any idea?

**Comment by misty000** [comment] 2017-03-27 08:56
but it's work well in Angular2. Look at my first gif
[http://git.oschina.net/ellipse/ng-covalent-sample-2/raw/master/ng2.gif](http://git.oschina.net/ellipse/ng-covalent-sample-2/raw/master/ng2.gif)

thank you

**Comment by craftyInstigator** [comment] 2017-03-27 08:57
The height calculation worked perfectly in 2.4.9. As soon as I upgraded to 4.0.0 the height animation broke. My understanding is that the whole point of height: '*' is to dynamically calculate the height. Otherwise, there seems to be no point in that notation.

**Comment by Toxicable** [comment] 2017-03-27 09:04
Yes I believe this is a bug at this stage but I cannot say for certain since I'm not very knowledgeable with the animations framework. So you're gonna have to wait till someone who knows more about it investigates .
@misty000 if you wouldn't mind updating your Issue with this plunker https://plnkr.co/edit/XpISx8AoH6jmN6D57139?p=preview it would make it easier for anyone else taking a look

**Comment by misty000** [comment] 2017-03-27 09:13
@Toxicable thank your.
I never use plunker before. I have put this link on my issue

**Comment by matsko** [comment] 2017-03-27 15:32
Yes I definetly confirm something's going on here with the `*` code. Thank you @Toxicable for making a clear demo for me to start off with. I'm looking into it.

**Comment by matsko** [comment] 2017-03-27 15:33
It looks like something's going with ng-content (the inner data isn't filled in yet during the time the animation is kicked off). I will consult with @tbosch.

**Comment by misty000** [comment] 2017-03-30 04:32
@Toxicable @matsko 
I update to 4.0.1, but this problem still exist. I will keep trying 4.1.
And I don't know how to use 4.0.1 in plunker.

**Comment by matsko** [comment] 2017-03-30 04:35
Looking into it.

**Comment by Toxicable** [comment] 2017-03-30 04:38
@misty000 That plunkr uses the latest version so it already uses 4.0.1
@matsko this plunkr https://plnkr.co/edit/XpISx8AoH6jmN6D57139?p=preview which is 4.0.1 still shows the error

**Comment by craftyInstigator** [comment] 2017-04-07 05:45
Any progress on this defect?

**Comment by nsdcss** [comment] 2017-04-12 06:46
"void => *"-Animations with "height: '*'" are broken at the moment. Is the animation-package simply not ready for use in production yet?

**Comment by tomwanzek** [comment] 2017-04-23 21:03
I just migrated an app to `4.0.3` from `2.x`. Previously working opacity animations relying on auto-calculated `'*'` are now broken, in line with what had been previously identified in this thread.

**Comment by nsdcss** [comment] 2017-04-26 06:35
Please, can you give any comment on this issue?

**Comment by tomwanzek** [comment] 2017-05-01 01:50
The issue is still present in Angular 4.1.0. 😞

**Comment by btaens** [comment] 2017-05-26 07:08
Any progress on this?

**Comment by btaens** [comment] 2017-05-30 07:06
Funnily enough, 4.2.0-rc.1 seems to have the opposite problem. "*" attributes seem to work fine on enter, but have this problem now on leave.

**Comment by beccanelson** [comment] 2017-05-30 20:03
+1 on this issue. I just upgraded from Angular 2 to 4.1.3, and I am still having the same issue.

**Comment by nsdcss** [comment] 2017-05-31 03:45
> Funnily enough, 4.2.0-rc.1 seems to have the opposite problem. "*" attributes seem to work fine on enter, but have this problem now on leave.

Try "!" instead of "*" in your leave animation. For me that worked.

**Comment by btaens** [comment] 2017-06-01 07:24
@nsdcss Yep, that seems to work. Which also means this bug is fixed in 4.2.0-rc.1.
Not entirely sure what the exclamation mark means though, I guess we'll see on release.

**Comment by matsko** [comment] 2017-06-01 07:26
Shhhh the `!` was supposed to be secret!

**Comment by nsdcss** [comment] 2017-06-08 09:35
Haha ... digging threw the sources helped.

**Comment by macjohnny** [comment] 2017-06-13 06:56
@nsdcss @misty000 The last remaining issue seems to be solved with https://github.com/angular/angular/commit/185075d
See also https://github.com/angular/angular/issues/17363

**Comment by matsko** [comment] 2017-08-28 23:01
This patch I believe has fixed the issue: https://github.com/angular/angular/commit/70628112e85ceadd2e0aa243a659f871cbf29492
 
If you test out the provided plnkr (which runs atop of the HEAD build code) you can see it operates as expected. https://plnkr.co/edit/XpISx8AoH6jmN6D57139?p=preview

Sorry for this annoying bug and that it took so long to be fixed.

**Closed by matsko** 2017-08-28 23:01 UTC
Labels: comp: animations, severity5: regression

**Comment by qcryptic** [comment] 2017-10-04 14:17
So will that not be included in angular 4?

**Comment by matsko** [comment] 2017-10-04 15:59
Yes that's both in 4 and 5.
