### ISSUE TITLE
`QueryList` emits changes even when it's items are not changed

### ISSUE THREAD

**Issue by th0r** [angular/angular#35807] opened 2020-03-02 20:07 UTC
# 🐞 bug report

### Affected Package

 Not sure

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 8.2.14

### Description

 Given this app template:
```html
<app-tabs>
  <ng-template appTab="Foo tab">
    Foo content
    <ng-template></ng-template>
  </ng-template>

  <ng-template appTab="Bar tab">
    Bar content
  </ng-template>
</app-tabs>
```
And this code in `<app-tabs>` component:
```ts
export class TabsComponent implements AfterViewInit {
  @ContentChildren(TabDirective) tabs: QueryList<TabDirective>;

  activeTab: TabDirective;

  constructor(private changeDetection: ChangeDetectorRef) {}

  ngAfterViewInit() {
    this.activeTab = this.tabs.first;
    this.tabs.changes.subscribe(() => {
      console.log(`'tabs.changes' handler called, but nothing has changes and there are still ${this.tabs.length} tabs`);
    });
    this.changeDetection.detectChanges();
  }
}
```
Handler for `this.tabs.changes` observable is called after every click on tab button (see reproduction below) but it shouldn't because content children (child templates with `appTab` directive applied) haven't changed.

If you remove `<ng-template></ng-template>` below `Foo content` everything works as expected - `changes` handler is not called.

## 🔬 Minimal Reproduction

 https://ng-run.com/edit/Mp66ACl3Uz6KbIEbFGwq?open=app%2Fapp.component.html

Reproduction steps:
1. Open a link and open a browser console. Wait for the app to load.
2. Notice that nothing is in the console.
3. Click on "Bar tab" - nothing is in the console.
4. Click on "Foo tab" - nothing is in the console.
5. Uncomment `<ng-template></ng-template>` below `Foo content` - notice `'tabs.changes' handler called...` log item in the console
6. Click on "Bar tab" - notice another `'tabs.changes' handler called...` log item in the console.
7. Click on "Foo tab" - notice another `'tabs.changes' handler called...` log item in the console.
8. Comment out `<ng-template></ng-template>` and uncomment `<ng-container *ngIf="false"></ng-container>`. See the same invalid log items in the console.

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 9.0.4
Node: 12.16.0
OS: darwin x64

Angular: 9.0.4
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.4
@angular-devkit/build-angular     0.900.4
@angular-devkit/build-optimizer   0.900.4
@angular-devkit/build-webpack     0.900.4
@angular-devkit/core              9.0.4
@angular-devkit/schematics        9.0.4
@ngtools/webpack                  9.0.4
@schematics/angular               9.0.4
@schematics/update                0.900.4
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2

</code></pre>

**Comment by pkozlowski-opensource** [comment] 2020-03-03 16:20
Sounds like we are over-reporting changes in queries in presence of embedded views. I _think_ that I know what is going on / how to fix it but it might be not trivial (generally speaking we need to understand if there are matches in embedded views when adding / removing embedded views).

**Comment by Achilles1515** [comment] 2020-03-03 17:28
I also just noticed this issue in cdk/drag-drop while fighting a bug in my application.

[https://ng-run.com/edit/d7UOA9LZQaVFReUkODrb?open=app%2Fapp.component.ts](https://ng-run.com/edit/d7UOA9LZQaVFReUkODrb?open=app%2Fapp.component.ts)

```ts
@ViewChildren(CdkDrag) drags: QueryList<CdkDrag>;
ngAfterViewInit() {
    this.drags.forEach(drag => drag._handles.changes.subscribe(() => console.log("handles changed")));
  }
```

Start sorting the list with the drag handles and you will see "handles changed" in the console after dropping an item.

Turn Ivy off, do the same thing, and you will see nothing.

@crisbeto

**Comment by pkozlowski-opensource** [comment] 2020-03-17 15:40
@th0r I had a look into the use-case reported by you and there are a couple of things that don't look quite right to me:
* in your code there is a _content_ query but you do subscribe to it in `ngAfterViewInit` hook;
* subscribing in `ngAfterViewInit` hook seems "too late" to react to content changes - this is why you have to have an additional detect changes call.

I've cleaned up the reproduce scenario a bit to reflect the above: https://ng-run.com/edit/CEAOCrAGAzEzxnVTGysr?open=app%2Ftabs.component.ts

Coming back to the actual difference with VE behaviour - still investigating.

**Comment by th0r** [comment] 2020-03-17 16:51
> in your code there is a content query but you do subscribe to it in ngAfterViewInit hook;
subscribing in ngAfterViewInit hook seems

I did it because I've extracted this example from our project where all tabs may be conditionally rendered via *ngIf and in this case `tabs` query will be `null` (if I'm not mistaken - can't check it right now).

**Comment by pkozlowski-opensource** [comment] 2020-03-17 16:57
>  query will be null in ngOnInit (if I'm not mistaken - can't check it right now).

This is why we've got `ngAfterContentInit` (_not_ `ngOnInit`!) where the content queries are guaranteed to be assigned.

**Comment by pkozlowski-opensource** [comment] 2020-04-01 09:12
A short update for anyone tracking this issue VE (default rendering engine in Angular 8) is _very_ inconsistent in terms of calling the `changes` handler on `QueryList`. As an example, please consider this live example: https://ng-run.com/edit/4CYyvsGT9weUf13sJ17c?open=app%2Ftabs.component.ts

In the above we've got 2 queries (`@ContentChildren(TabDirective, {descendants: false}) tabs: QueryList<TabDirective>;` and `@ViewChildren(TabDirective) tabsInView: QueryList<TabDirective>;`). Notice that _both_ queries are matching *the same elements* and the set of matches never changes! So we could consider those queries to be "the same". In practice, though, the 2 mentioned queries behave differently when it comes to notifications!!!

In Angular v9 running ivy the behaviour is consistent and always result in notification! (you can switch between VE and ivy in the provided example to confirm this). 

Given the above observations we can conclude that both VE _and_ ivy are not accurate when it comes to calling the `changes` handler - it might happen that we "over-report" changes (when there are no actual changes). The current behaviour is query-engine-implementation dependent. Both are not accurate but not accurate _differently_.

Sadly, getting "perfect" notifications accuracy would require significantly more computation when adding / removing view with queries. At this point I'm not sure if the performance degradation is worth the accuracy. We are facing perf vs. over-reporting dilemma here. 

I will continue exploring ways of reducing ivy's over-reporting changes but the bottom line is this - *we will NOT be able to have 100% the same behaviour as in Angular 8 with VE* - the simple reason for this is that Angular 8 is not consistent either so trying to match the old behaviour would mean replicating its bugs as well.

**Comment by maheshbabubokkisam** [comment] 2020-08-17 07:41
I updated the below file https://ng-run.com/edit/4CYyvsGT9weUf13sJ17c?open=app%2Fapp.component.ts with these changes

`names = [];  
addName() {
  this.names.push('my name ');
}

<hr>
<ul>
  <li *ngFor="let name of names">{{name}}</li>
</ul>
<button (click)="addName()">Add name</button>`

My Question is why below console.log is calling for every click event addName()

    this.tabsInView.changes.subscribe(() => {
      console.log(`'tabsInView.changes' handler called in AppComponent, but nothing has changes and there are still ${this.tabsInView.length} tabs`);
    }); 

We are adding subscribe only this.tabsInView.changes then why this is calling for every addName click event?

**Comment by maheshbabubokkisam** [comment] 2020-08-17 09:26
> A short update for anyone tracking this issue VE (default rendering engine in Angular 8) is _very_ inconsistent in terms of calling the `changes` handler on `QueryList`. As an example, please consider this live example: https://ng-run.com/edit/4CYyvsGT9weUf13sJ17c?open=app%2Ftabs.component.ts
> 
> In the above we've got 2 queries (`@ContentChildren(TabDirective, {descendants: false}) tabs: QueryList<TabDirective>;` and `@ViewChildren(TabDirective) tabsInView: QueryList<TabDirective>;`). Notice that _both_ queries are matching _the same elements_ and the set of matches never changes! So we could consider those queries to be "the same". In practice, though, the 2 mentioned queries behave differently when it comes to notifications!!!
> 
> In Angular v9 running ivy the behaviour is consistent and always result in notification! (you can switch between VE and ivy in the provided example to confirm this).
> 
> Given the above observations we can conclude that both VE _and_ ivy are not accurate when it comes to calling the `changes` handler - it might happen that we "over-report" changes (when there are no actual changes). The current behaviour is query-engine-implementation dependent. Both are not accurate but not accurate _differently_.
> 
> Sadly, getting "perfect" notifications accuracy would require significantly more computation when adding / removing view with queries. At this point I'm not sure if the performance degradation is worth the accuracy. We are facing perf vs. over-reporting dilemma here.
> 
> I will continue exploring ways of reducing ivy's over-reporting changes but the bottom line is this - _we will NOT be able to have 100% the same behaviour as in Angular 8 with VE_ - the simple reason for this is that Angular 8 is not consistent either so trying to match the old behaviour would mean replicating its bugs as well.

I updated the below file https://ng-run.com/edit/4CYyvsGT9weUf13sJ17c?open=app%2Fapp.component.ts with these changes

`names = [];  
addName() {
  this.names.push('my name ');
}`

```
<div>
<ul>
  <li *ngFor="let name of names">{{name}}</li>
</ul>
<button (click)="addName()">Add name</button>`
</div>
```

My Question is why below console.log is calling for every click event addName()

    this.tabsInView.changes.subscribe(() => {
      console.log(`'tabsInView.changes' handler called in AppComponent, but nothing has changes and there are still ${this.tabsInView.length} tabs`);
    }); 

We are adding subscribe only this.tabsInView.changes then why this is calling for every addName click event?

**Comment by Achilles1515** [comment] 2021-01-21 21:46
@mhevery 
I saw you worked on a recent PR to fix `QueryList` firing changes when it shouldn't -
Do you know why this one is still broken?

https://ng-run.com/edit/aHiMRGFjAFY04yVfBifd

(Same project as my above comment, updated to 11.1.0 - sort items using the handles and view the `changes` output in the console. Then turn the "Ivy AOT" option off and notice the same action does not output anything in the console.)

**Comment by jelbourn** [comment] 2021-02-01 22:19
Copying proposed test for this from internal tracker:
```ts
it('should trigger notifyOnChanges after assigning QueryList instance', () => {
      @Component({
        selector: 'my-app',
        template: `
          <ng-template [ngIf]="show">
            <span #foo></span>
          </ng-template>          
        `,
      })
      class TestComponent {
        show: boolean = false;
        @ViewChildren('foo') query: QueryList<any>|null = null;

        ngAfterViewInit() {}
      }

      TestBed.configureTestingModule({declarations: [TestComponent]});
      const fixture = TestBed.createComponent(TestComponent);
      fixture.detectChanges();

      expect(fixture.componentInstance.query !.length).toBe(0);

      let notified = false;
      // set QueryList instance to confirm that it is re-assigned when query becomes dirty
      fixture.componentInstance.query !.changes.subscribe((queryList: QueryList<any>) => {
        notified = true;
        expect(fixture.componentInstance.query !.length).toBe(1);
      });
      fixture.componentInstance.query = null;

      fixture.componentInstance.show = true;
      fixture.detectChanges();
      expect(fixture.componentInstance.query !.length).toBe(1);
      expect(notified).toBeTruthy();
    });

  });
```

**Comment by mhevery** [comment] 2021-02-01 23:03
> @mhevery
> I saw you worked on a recent PR to fix `QueryList` firing changes when it shouldn't -
> Do you know why this one is still broken?
> 
> https://ng-run.com/edit/aHiMRGFjAFY04yVfBifd
> 
> (Same project as my above comment, updated to 11.1.0 - sort items using the handles and view the `changes` output in the console. Then turn the "Ivy AOT" option off and notice the same action does not output anything in the console.)

Hi @Achilles1515,

Can you be more specific as to what you mean by "broken". From my point of view this works as intended (and VE is broken) If one creates as subscription to to `QueryList` and the list changes it should fire which is what I observe.

Also I think this issue should be closed, and instead a new issue should be created for what you are observing. So I am going to go ahead and close it. Let's start a new conversation.

PS: https://ng-misko.medium.com/how-to-file-an-issue-715391a093d2

**Comment by mhevery** [comment] 2021-02-01 23:04
Closing as we believe this issue has been resolved in #40091

**Closed by mhevery** 2021-02-01 23:04 UTC
Labels: P3, comp: core, core: queries, engine: ivy, freq1: low, state: confirmed, triage #1, type: bug/fix

**Comment by Achilles1515** [comment] 2021-02-02 19:00
@mhevery @jelbourn 
Can you just open this issue back up? None of the issues stated in this thread have been fixed. Issues shouldn't be closed based on speculation when there are concrete repros to test against.

ng-run from the OP @th0r updated to 11.2.0-next.0 (follow instructions in OP):
https://ng-run.com/edit/FDxF4lPM4Cp0ran99cMM?open=app%2Fapp.component.html

ng-run from @maheshbabubokkisam comments [up above](https://github.com/angular/angular/issues/35807#issuecomment-674768886) updated to 11.2.0-next.0 (click the `Add name` button which is running an event binding in the component and check console output afterward --> why does this trigger the `changes` observable to fire?):
https://ng-run.com/edit/kuaGnLPuD3oYModDaDkk?open=app%2Fapp.component.ts

and again, my repro updated to 11.2.0-next.0:
https://ng-run.com/edit/aHiMRGFjAFY04yVfBifd?open=app%2Fapp.component.ts

>Can you be more specific as to what you mean by "broken".

I am subscribing to changes in each of the `CdkDrag`'s handle queries which look like this:
```ts
 /** Elements that can be used to drag the draggable item. */
  @ContentChildren(CDK_DRAG_HANDLE, {descendants: true}) _handles: QueryList<CdkDragHandle>;
```

As you drag and sort the list (after releasing), there are console output(s) stating something has changed regarding the backing array of this handle query. But nothing has changed. No handles are created or destroyed or moved to/from any `CdkDrag` children.

**Comment by mhevery** [comment] 2021-02-02 20:51
> @mhevery @jelbourn
> Can you just open this issue back up? None of the issues stated in this thread have been fixed. Issues shouldn't be closed based on speculation when there are concrete repros to test against.
> 
> ng-run from the OP @th0r updated to 11.2.0-next.0 (follow instructions in OP):
> https://ng-run.com/edit/FDxF4lPM4Cp0ran99cMM?open=app%2Fapp.component.html

What does OP stand for? Not obvious. Also not obvious how to reproduce the issue. After playing with it for a while I think the goal is to not print the string into the console. Per instructions in #40091 adding `emitDistinctChangesOnly: true` makes it behave as expected. https://ng-run.com/edit/w4cL9wfqdqIhfF7HTnMh

> ng-run from @maheshbabubokkisam comments [up above](https://github.com/angular/angular/issues/35807#issuecomment-674768886) updated to 11.2.0-next.0 (click the `Add name` button which is running an event binding in the component and check console output afterward --> why does this trigger the `changes` observable to fire?):
> https://ng-run.com/edit/kuaGnLPuD3oYModDaDkk?open=app%2Fapp.component.ts

Adding `emitDistinctChangesOnly: true` makes it behave as expected https://ng-run.com/edit/GW2gR1IDxMYNWdIA5Ouh

> 
> and again, my repro updated to 11.2.0-next.0:
> https://ng-run.com/edit/aHiMRGFjAFY04yVfBifd?open=app%2Fapp.component.ts
> 
> > Can you be more specific as to what you mean by "broken".
> 
> I am subscribing to changes in each of the `CdkDrag`'s handle queries which look like this:
> 
> ```ts
>  /** Elements that can be used to drag the draggable item. */
>   @ContentChildren(CDK_DRAG_HANDLE, {descendants: true}) _handles: QueryList<CdkDragHandle>;
> ```
> 
> As you drag and sort the list (after releasing), there are console output(s) stating something has changed regarding the backing array of this handle query. But nothing has changed. No handles are created or destroyed or moved to/from any `CdkDrag` children.

https://ng-run.com/edit/nMbzOefCmKuuFvrvhWpP which added `emitDistinctChangesOnly: true`. Yes the item fires because `CdkDragHandle` instance changes. There may be a separate issue with CDK as to why it changes instance, but from `QueryList` point of view it works as intended.

So as far as I can tell the initial behavior has been fixed, and it is behind `emitDistinctChangesOnly: true` because we think that turning it on would be a breaking change. We will change the flag to default in next major version.

**Comment by mhevery** [comment] 2021-02-03 16:45
> Ok, I was unaware that a new query API option was added. I don't understand why this was added behind a new option though...it was a breaking change in 9.0, ignored for two releases, then fixed in 11 but now behind a flag because it's a breaking change against behavior that was already a breaking change and contradicted the Angular docs??

In an ideal world, what you say is true. The issue is that VE has a buggy behavior. Ivy also has a buggy behavior in a different way. So if we just fix Ivy we actually break it with respect to buggy VE behavior. For this reason, we had to wait until the major version before it can become the default. 

`emitDistinctChangesOnly: true` means have proper behavior of only firing if there is the actual change. `emitDistinctChangesOnly: false` means retain old buggy behavior.

> The CdkDragHandle instance is not changing. According to this new API, the query for handles inside the CdkDrag class would need to be changed to the following to fix the issue:

Correct. @jelbourn can you look into it.
