### ISSUE TITLE
Setting named outlet to null with router does not work

### ISSUE THREAD

**Issue by olfek** [angular/angular#35732] opened 2020-02-27 22:57 UTC
# 🐞 bug report

### Affected Package
One of these (extracted from `package.json`):
```
"dependencies": {
  "@angular/animations": "~8.2.14",
  "@angular/common": "~8.2.14",
  "@angular/compiler": "~8.2.14",
  "@angular/core": "~8.2.14",
  "@angular/forms": "~8.2.14",
  "@angular/platform-browser": "~8.2.14",
  "@angular/platform-browser-dynamic": "~8.2.14",
  "@angular/router": "~8.2.14",
  "rxjs": "~6.4.0",
  "tslib": "^1.10.0",
  "zone.js": "~0.9.1"
},
```

### Is this a regression?

Don't know, I have not used this feature before.

### Description
`this.router.navigate([{ outlets: { popup: null }}]);` as mentioned [here](https://angular.io/guide/router#displaying-multiple-routes-in-named-outlets) does not work.

## 🔬 Minimal Reproduction
I have attached a zip file. [named-outlet-router-bug.zip](https://github.com/angular/angular/files/4264494/named-outlet-router-bug.zip)

## 🔥 Exception or Error
None.

## 🌍  Your Environment

**Angular Version:**
```
Angular CLI: 8.3.25
Node: 12.14.1
OS: win32 x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.25
@angular-devkit/build-angular     0.803.25
@angular-devkit/build-optimizer   0.803.25
@angular-devkit/build-webpack     0.803.25
@angular-devkit/core              8.3.25
@angular-devkit/schematics        8.3.25
@angular/cli                      8.3.25
@ngtools/webpack                  8.3.25
@schematics/angular               8.3.25
@schematics/update                0.803.25
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2
```

**Anything else relevant?**
No.

**Comment by atscott** [comment] 2020-02-27 23:14
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template, including a minimal reproduction in either Stackblitz or a minimal GitHub repo.

**Comment by olfek** [comment] 2020-02-27 23:30
Hello, please re-open this issue, I have already attached a zip file of an Angular app which reproduces the problem and I also explained what the problem was in the 'description' section.

**Comment by olfek** [comment] 2020-02-27 23:53
@atscott If you download the zip file and run the app, you'll be able to see the problem in action.

**Comment by olfek** [comment] 2020-02-29 13:15
@atscott This might be an actual bug, and you are ignoring it. For someone in your position, shame on you. For any projects in the future, I will consider using Vue.js instead. 😡

**Comment by olfek** [comment] 2020-02-29 13:19
Since reporting this, I have also discovered another [bug](https://stackoverflow.com/q/40214655) just now which seems to be affecting ~320k people. Someone may have already reported this, but the issue was probably closed just like this one without any second thought by some snobby individual.

**Comment by olfek** [comment] 2020-02-29 15:50
@atscott See the bug in action below.

![tmp](https://user-images.githubusercontent.com/27283110/75610654-02534180-5b0b-11ea-8155-594be5f1d777.gif)

**Comment by IgorMinar** [comment] 2020-02-29 16:55
@olfek first of all, I understand that you are frustrated, but let me please remind you of our code of conduct (https://github.com/angular/code-of-conduct). We will not tolerate any further threats or personal attacks against out team members or community members.

I'm reopening the issue since you provided additional info. We however need more. Can you please add a textual description of:

1. Repro steps using your attached app
2. Expected behavior
3. Actual behavior

**Comment by olfek** [comment] 2020-02-29 17:07
I did not make any threats or carry out any personal attacks, I simply expressed my frustration with the way a new issue was closed immediately without any discussion opportunity. If what I experienced is standard procedure, you are missing out on a lot of valuable real bug reports, I would recommend reviewing your processes and members actions or risk having the community relationship that react native has.

Anyway, thank you for re-opening the issue, I will address the requested information below.

1. See the GIF on how to reproduce the bug (the app has been uploaded here, see link above).
1. The second button, which uses `this.router.navigate([{ outlets: { popup: null }}]);` should have the same/similar behavior as the first button `routerLink=".."`.
1. The second button does not work.

**Comment by olfek** [comment] 2020-03-26 13:27
Just now, I needed to use this (programmatic navigation to named outlet) again, I have discovered that not only does setting it to null not work, setting it to an actual path doesn't work either.

**Comment by gunsh** [comment] 2020-04-24 05:30
I found an ugly but effective workaround. This is a demo that demonstrate this issue as I have seen it: https://stackblitz.com/edit/angular-spzbc3

There is a difference between trying to navigate to 'null' from within the component that is active in the secondary outlet and doing the same thing outside of it. The latter just **works**. So the workaround is to host a hidden <a [routerLink]> outside of the secondary outlet and to have a service click it programmatically. Another way is to just call 'router.navigate()' but that simply didn't work for me.

I hope this saves someone some precious time.

**Comment by atscott** [comment] 2020-05-26 19:15
Related issue: #13523

**Comment by atscott** [comment] 2020-05-26 22:51
Closing as duplicate of #15718. Example from this issue also copied to stackblitz and included here: https://github.com/angular/angular/issues/15718#issuecomment-634320932

**Closed by atscott** 2020-05-26 22:51 UTC
Labels: comp: router, freq2: medium, router: aux routes, severity3: broken, state: confirmed, triage #1, type: bug/fix
