### ISSUE TITLE
Proposal: one-time boolean bindings

### ISSUE THREAD

**Issue by samclaus** [angular/angular#34713] opened 2020-01-09 23:21 UTC
# 🚀 feature request

### Relevant Package

This feature request is for `@angular/core` and `@angular/compiler`?
I am not very familiar with the infrastructure.

### Description

First of all, I am not referring to the AngularJS one-time bindings (`::` prefix) in any capacity. This request is a logical extension of the one-time **string** bindings which already exist in the new Angular.

```HTML
<!-- Regular binding -->
<mat-icon [fontIcon]="someIconVariable"></mat-icon>

<!-- One-time binding to literal string -->
<mat-icon fontIcon="cloud-upload"></mat-icon>
```

I have found the above feature of Angular to be exceptionally nice (along with many others!) and could not care less that we no longer have explicit one-time bindings to variables as they made it easy to introduce bugs and the performance gains pale in comparison to those netted by AOT compilation anyways.

However, a common pattern in AngularJS material, as well as many of my own components, is to support empty attributes for boolean properties, which would be the same as binding to a literal `true`. I believe empty attributes are not technically valid XML, but it is a common practice in HTML where the presence of an attribute makes it truthy and the absence of the attribute makes it falsy, such as putting `required` on an `<input>`.

With my proposed change, the following two examples would be equivalent.

```HTML
<!-- This works -->
<user-card [userID]="selectedUserID" [showAdminControls]="true"></user-card>

<!-- This would be nice :^) -->
<user-card [userID]="selectedUserID" showAdminControls></user-card>
```

With this feature, you can either bind a boolean to the input as usual or just include the attribute without a binding, causing Angular to set the property to `true` and then leave it alone, just as the existing one-time string literal bindings work.

### Describe the solution you'd like

Sorry, but I am not familiar with the Angular source code, so I have no idea how this would be implemented. The best I can do for now is to write a pretty issue and hope it garners some attention.

### Describe alternatives you've considered

To implement this on my components, I basically just set the initial value of the property to whether the attribute is present and empty.

```TypeScript
// ...
export class UserCardComponent {
    // ...
    @Input() showAdminControls = hasEmptyAttr(this.host.nativeElement, "showAdminControls");
    // ...
}
```

This approach is tedious and requires the programmer to keep the property/attribute names in sync. AFAIK the template compiler always reports unrecognized properties it finds in the HTML but a typo in the string in the `hasEmptyAttr(...)` call would result in a subtle bug.

**Comment by JoostK** [comment] 2020-01-10 00:54
Would something like the [`@Attribute` decorator](https://angular.io/api/core/Attribute) be helpful in your situation?

**Comment by ericmartinezr** [comment] 2020-01-10 01:04
Related https://github.com/angular/angular/issues/14761

**Comment by thefliik** [comment] 2020-01-10 01:31
Just to make sure you are aware, currently

```ts
<user-card showAdminControls></user-card>
```

is equivalent to

```ts
<user-card showAdminControls=""></user-card>
```

So you can coerce `<user-card showAdminControls></user-card>` to a boolean value by checking if it is `=== ""`. `@angular/cdk` exports a function to handle this (or you could make one yourself).

I.e. this code

```ts
import { coerceBooleanProperty } from '@angular/cdk/coercion';

export class UserCardComponent {
    private _showAdminControls = false;
    @Input()
    get showAdminControls() { return this._showAdminControls }
    set showAdminControls(val) {
      this._showAdminControls = coerceBooleanProperty(val);
    }
}
```

Allows for

```ts
<user-card showAdminControls></user-card>
// or
<user-card [showAdminControls]="true"></user-card>
```

If I'm to understand this issue, you're requesting that `<user-card showAdminControls></user-card>` (where `showAdminControls` is an `@Input` property) set the input property to `true` rather than `""` as it currently does?

**Comment by samterainsights** [comment] 2020-01-11 00:30
@thefliik Yes, that is what I am suggesting. Setting it to an empty string is rather useless.

**Comment by samterainsights** [comment] 2020-01-11 00:35
> Would something like the [`@Attribute` decorator](https://angular.io/api/core/Attribute) be helpful in your situation?

@JoostK That is nicer than my current solution but still not ideal as it doesn't solve the issue of keeping the property binding and attribute name in sync. And it's just not as clean. I can think of any other reason one would just put an empty attribute on an element. As I said, my proposed behavior is the same as native attributes like `required` and `disabled`, so it seems like a reasonable feature for Angular components.

**Comment by samterainsights** [comment] 2020-01-11 00:40
Please do not continue this thread. As `ericmartinezr` mentioned above, this is a duplicate of #14761. I am not closing the issue because I think I gave a clearer description of the desired behavior but the proposals are identical.

**Comment by lazarljubenovic** [comment] 2021-06-05 22:07
This can be easily achieved with a custom decorator already. You don't need the “hasEmptyAttr” thing at all. Just transform a `''` to `true`, let `true` and `false` pass and throw an error for anything else. There's some implementation of this in the CDK, I think.

```ts
@CoerceToBoolean()
@Input()
public myBooleanInput: boolean
```

**Comment by mlc-mlapis** [comment] 2021-06-05 23:12
Yep, it's true. CDK has `coerceBooleanProperty` method. But there is a problem with a new input type checking because an attribute is always passed as a string type. The reason is that a setter and a getter have to share the same type now. It'll probably be solvable with TS 4.3 and its support for **Separate Write Types on Properties**.

```
import {coerceBooleanProperty} from '@angular/cdk/coercion';
...
_hide = false;
...
@Input()
  set hide(v) {
    this._hide = coerceBooleanProperty(v);
  }
  get hide() {
    return this._hide;
  }
```

**Comment by lazarljubenovic** [comment] 2021-06-06 15:19
Yeah, that's why I suggested stuffing it in a decorator. Way less boilerplate, nicely encapsulated, and no typing issues.

**Comment by pkozlowski-opensource** [comment] 2022-08-25 11:35
@samclaus as you've [pointed out](https://github.com/angular/angular/issues/34713#issuecomment-573258823) this _is_ a duplicate of the existing issue #14761 that was opened earlier on.

I very much want to centralize the discussion in one place and move it to #14761. If you believe that #14761 is missing additional context, please feel free to comment in there.

Duplicate of #14761

**Closed by pkozlowski-opensource** 2022-08-25 11:35 UTC
Labels: feature, comp: core, core: binding & interpolation, core: inputs / outputs, under consideration
