### ISSUE TITLE
New component router not activating components in route

### ISSUE THREAD

**Issue by SnareChops** [angular/angular#10060] opened 2016-07-14 02:40 UTC
**I'm submitting a bug report**

**Current behavior**
When a route is navigated to the matching components are displayed, but not "activated". (`*ngIf` and other directives do not process and display)

**Expected/desired behavior**
When a route is navigated to, the matching components are displayed AND "activated"

**Reproduction of the problem**
A full reproduction repo can be found [here](https://github.com/SnareChops/angular2-router-bug) with full instructions to build/reproduce the issue.

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** Chrome Version 51.0.2704.103 (64-bit)
 
* **Language:** TypeScript Version 2.0.0-dev.20160707

**Comment by SanderElias** [comment] 2016-07-14 05:10
@SnareChops You didn't inject your authguard service  into your logincomponent. This might not be the only problem. But as it's not firing an event or doing anything else that would be picked up by the zone detection, your change to the authenticated boolean isn't being seen, and you need an event to propagate it to the front end.

**Comment by SnareChops** [comment] 2016-07-14 05:31
@SanderElias You are correct that I am not injecting `AuthGuard` into login component. That is because the `authenticated` property that I am accessing is `static`. It's just a simple mechanism to recreate an authentication scenario. Not sure if that part is even needed to re-create the issue that I am having. 

As far as an event, the `(click)` event on the button calls a `login()` method in the LoginComponent, which then triggers a full navigation change using `router.navigate()` and loads in the new components. The LoginComponent gets destroyed and the page does not re-navigate back to the LoginComponent. This means that the change to `AuthGuard.authenticated` is being picked up. 

The issue is not with the value of `AuthGuard.authenticated` but instead with the `*ngIf` in the ToolbarComponent not working. This value is set during the construction of the component and does not change in any code path of the application. What is occurring here I believe is that the angular router is not correctly activating the ToolbarComponent when the navigation occurs in this particular scenario. In my full application I can also see that the DashboardComponent does not get activated correctly either, but this was enough to show that something is happening without submitting a reproduction repo that is too large to reasonably quickly be combed through by an Angular team member.

**Comment by brandonroberts** [comment] 2016-07-14 12:08
@SnareChops this isn't an issue with the router. You need to remove `<script type="text/javascript" src="node_modules/systemjs/dist/system-polyfills.js"></script>` from your `index.html`. Its no longer needed. Once that is removed, your sample repo works as intended.

**Comment by vsavkin** [comment] 2016-07-14 18:31
Closing this issue as it is not an issue with the router.

**Closed by vsavkin** 2016-07-14 18:31 UTC

**Comment by SnareChops** [comment] 2016-07-14 23:06
@brandonroberts Confirmed, removing the `system-polyfills.js` fixed the issue. Thank you.
