### ISSUE TITLE
globally-scoped variables in component template

### ISSUE THREAD

**Issue by AugustZellmer** [angular/angular#49688] opened 2023-04-03 20:23 UTC
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

If I have a function that I want to call from a whole bunch of different templates, I can conceptualize it as a pipe and then call it with the syntax `{{ arg1 | myFunc }}`. And that works just fine.

But if I have a constant (or a zero-arg function) that I want to access from a whole bunch of different templates, I can't. Instead, I have to include `public readonly myConst: myClass` in every component in which I want to use `{{ myConst }}` in the template. And that's _fine_, but it's definitely not as nice as the module-scoped pipes that are just kinda automagically where you need them. 

(Apologies if this has already been suggested. I didn't see it anywhere.)

### Proposed solution

Would it be worthwhile to implement some way to create a module-scoped constant, just like you can use pipes to implement a module-scoped function?

### Alternatives considered

Alternatively, it could be conceptualized as a zero-argument pipe. Then I could just have my zero-arg pipe return the constant I want.

**Comment by JeanMeche** [comment] 2023-04-03 21:10
Hi, I believe it's a dupe of #25963 !

**Comment by pkozlowski-opensource** [comment] 2023-04-03 21:32
Yeh, this is pretty much the same as #25963. 

Duplicate of #25963

**Closed by pkozlowski-opensource** 2023-04-03 21:32 UTC
