### ISSUE TITLE
Ng 8 + ivy: Component inheritance binding error

### ISSUE THREAD

**Issue by runner78** [angular/angular#30754] opened 2019-05-30 14:45 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....

### Is this a regression?

 It work when not using Ivy.

## 🔬 Minimal Reproduction

 

Abstract class
```
export abstract class AbstractComponent {
  @Input() value: string;
}
```
Component
```
export class ChildComponent extends AbstractComponent {
}
```
It works with 
`<dum-child value="test"></dum-child>`

Create an error:
`<dum-child [value]="'test'"></dum-child>`

## 🔥 Exception or Error
<pre><code>ERROR in __ng_typecheck__.ts(34,10): error TS2339: Property 'value' does not exist on type 'HTMLElement'.
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>Angular CLI: 8.0.0
Node: 10.16.0
OS: darwin x64
Angular: 8.0.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.0
@angular-devkit/build-angular     0.800.0
@angular-devkit/build-optimizer   0.800.0
@angular-devkit/build-webpack     0.800.0
@angular-devkit/core              8.0.0
@angular-devkit/schematics        8.0.0
@ngtools/webpack                  8.0.0
@schematics/angular               8.0.0
@schematics/update                0.800.0
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.30.0
</code></pre>

**Anything else relevant?**

**Comment by JoostK** [comment] 2019-05-30 19:33
Thanks for reporting. Inheritance should be supported in the template type checker, as long as the base class is statically known (it should't be some dynamically computed expression). In this case however, it looks like the problem is that the base class is not declared in an NgModule, which currently means its metadata (the details on inputs, outputs etc.) cannot be retrieved. This metadata is required for  template type-checking purposes, so that's where the false positive originates. We'll have to revisit this machinery a bit to fix the issue.

**Comment by JoostK** [comment] 2019-05-30 19:49
I should mention that you should be able to workaround the issue by disabling the template type checker. In `tsconfig.app.json`, you'll have to set `"fullTemplateTypeCheck": false` under `"angularCompilerOptions"`.

**Comment by JoostK** [comment] 2019-05-30 21:23
Tracked in FW-1352

**Comment by runner78** [comment] 2019-05-31 06:53
I have tried now `"fullTemplateTypeCheck": false` but has no effect, same error.

**Comment by kemsky** [comment] 2019-05-31 09:16
The same error was reported here #30080.

**Comment by JoostK** [comment] 2019-05-31 09:35
@kemsky Thanks for linking. Yes, your issue has the same root cause, only now do I understand what is happening exactly.

**Comment by kara** [comment] 2019-06-03 14:40
Seems like we should close this as a duplicate of #30080 so we can track progress / comments in one place. Thanks for reporting @runner78, please follow #30080

**Closed by kara** 2019-06-03 14:40 UTC
Labels: comp: ivy, severity3: broken, type: bug/fix, workaround4: none
