### ISSUE TITLE
Angular 16: NG0303: Can't set value of the input on the component. Make sure that the property is annotated with @Input() or a mapped @Input() exists.

### ISSUE THREAD

**Issue by narendrasinghrathore** [angular/angular#53865] opened 2024-01-10 11:06 UTC
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

We are using "ng-dynamic-component": "~10.3.1", to dynamically create component and we are seeing below error.

Questions
1. Is there any way we can configure to not check @Input annotation required for input
2. We have lots of components, what would be the best way to update all if above is not possible

 
Error: 
`NG0303: Can't set value of the 'isInTabbedForm' input on the 'SearchFormComponent' component. Make sure that the 'isInTabbedForm' property is annotated with @Input() or a mapped @Input('isInTabbedForm') exists.`

### Please provide the exception or error you saw

```true
NG0303: Can't set value of the 'isInTabbedForm' input on the 'SearchFormComponent' component. Make sure that the 'isInTabbedForm' property is annotated with @Input() or a mapped @Input('isInTabbedForm') exists.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 16.2.11
Node: 18.13.0
Package Manager: npm 10.2.5    
OS: win32 x64

Angular: 16.2.12
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package
 Version
---------------------------------------------------------     
@angular-devkit/architect      
 0.1602.11
@angular-devkit/build-angular  
 16.2.11
@angular-devkit/core
 16.2.11
@angular-devkit/schematics     
 16.2.11
@angular/cli
 16.2.11
@schematics/angular
 16.2.11
rxjs
 6.5.5
typescript
 4.9.5
zone.js
 0.13.3
```

**Comment by narendrasinghrathore** [comment] 2024-01-10 11:15
@JoostK @pkozlowski-opensource please suggest.

**Comment by JeanMeche** [comment] 2024-01-10 11:30
@narendrasinghrathore Can you provide a stackblitz repro of your issue ?

**Comment by narendrasinghrathore** [comment] 2024-01-11 05:45
For reference: https://github.com/angular/angular/issues/46978

**Comment by narendrasinghrathore** [comment] 2024-01-11 08:06
Stackblitz link @JeanMeche 
https://stackblitz.com/edit/angular-ivy-5hetvw?file=src%2Fapp%2Fapp.component.html

**Comment by garrettld** [comment] 2024-01-11 15:03
There's not currently a way to opt out of the check whether a property is an input. I think this type of thing makes more sense in your own code or as a feature of libraries like ng-dynamic-component. However, you can check if an input is valid by comparing it against a ComponentMirror instance by using the `reflectComponentType` function.

Here's an updated StackBlitz that applies this technique: https://stackblitz.com/edit/angular-ivy-wx8cm1?file=src%2Fapp%2Fapp.component.ts

**Comment by JoostK** [comment] 2024-01-11 15:22
Closing as working as intended. `ComponentRef.setInput` is intended to set _inputs_, not class properties (just assign into the property instead of using `setInput`, which can be determined based on @garrettld's suggestion)

**Closed by JoostK** 2024-01-11 15:22 UTC
Labels: needs reproduction, area: core, core: inputs / outputs

**Comment by narendrasinghrathore** [comment] 2024-01-11 17:02
> There's not currently a way to opt out of the check whether a property is an input. I think this type of thing makes more sense in your own code or as a feature of libraries like ng-dynamic-component. However, you can check if an input is valid by comparing it against a ComponentMirror instance by using the `reflectComponentType` function.
> 
> Here's an updated StackBlitz that applies this technique: https://stackblitz.com/edit/angular-ivy-wx8cm1?file=src%2Fapp%2Fapp.component.ts

Thank for update and for suggestion.
@garrettld
