### ISSUE TITLE
QueryList changes event not triggered by changes in children.

### ISSUE THREAD

**Issue by filipesilva** [angular/angular#9689] opened 2016-06-29 02:33 UTC
**I'm submitting a ...**  (check one with "x")

```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Subscription to `changes` of a `QueryList` is not triggered by changes in the children of an HTML element.

**Expected/desired behavior**
Previously (although I cannot tell when this changed), the event was triggered.
Not sure if this is intended or not, @naomiblack @mhevery?

**Reproduction of the problem**
Documentation showing the expected (previous) behaviour can be found in https://angular.io/docs/ts/latest/guide/template-syntax.html#!#ngfortrackby . There is a `live example` link at the top that will create a plunker.

Lines 450-452 of `app/app.component.html` contain the template code, while lines 191-223 of `app/app.component.ts` contain the change detection code.

The relevant code is as follows:

```
<div #noTrackBy class="box">
  <div *ngFor="let hero of heroes">({{hero.id}}) {{hero.fullName}}</div>
</div>
```

```
@ViewChildren('noTrackBy') childrenNoTrackBy: QueryList<ElementRef>;
//...
this.childrenNoTrackBy.changes.subscribe((changes: any) => {
  // never triggered
}
```

**Please tell us about your environment:**
- **Angular version:** 2.0.0-rc.3
- **Browser:** [all ] 
- **Language:** [TypeScript X.X ]

**Comment by tbosch** [comment] 2016-06-29 02:48
We are setting `@ViewChild` / `@ViewChildren` and pushing changes to it right after the component has been created, i.e. before `ngInit`. This was done in c3d2459a4e981f96891f14ce460435b379564642 so that users can access an `ElementRef` and do dynamic component loading already in `ngOnInit`.

I think the new behavior is good. However, we should wait for notification until `ngViewChecked` as was the case before so that listeners that have been registered in `ngOnInit` are still being called.

**Comment by tbosch** [comment] 2016-06-29 03:27
This is actually not true. c3d2459a4e981f96891f14ce460435b379564642 only changed the behavior of `@ViewChild` / `@ContentChild` but not for `@ViewChildren` / `@ContentChildren`. 

The problem in the plunker is that the stream is subscribed to in `ngAfterViewInit`, which is too late. It should be subscribed to in `ngOnInit`.

**Comment by marcalj** [comment] 2016-06-29 07:42
Maybe you can put a console warning if you find this subscription in ```ngAfterViewInit``` ? It will help avoid mistakes and headaches :)

**Comment by filipesilva** [comment] 2016-06-30 00:35
@tbosch I tried moving the subscription to `ngOnInit`:
```
// lines 30-36 of app/app.component.ts
  ngOnInit() {
    this.refreshHeroes();
    this.detectNgForTrackByEffects();
  }

  ngAfterViewInit() {
    // this.detectNgForTrackByEffects();
  }
```

but it appears that at the time of `ngOnInit` `childrenNoTrackBy` is still undefined. Am I missing something?

**Comment by kemsky** [comment] 2016-06-30 16:29
I though about posting feature request to initialize `QueryList` early (deprecated `Query` was convenient when injected into constructor) with empty list (i.e. after constructor call) so that it would be possible to use/subscribe early.

**Comment by MikaAK** [comment] 2016-07-14 00:54
I'm actually having this problem currently! Is there any workaround for now? I tried adding the subscription in `ngOnInit` but the QueryList is undefined at that time.
```typescript
export class TextSelector implements OnInit {
  @ContentChildren(TextSelectorItem) public selectItems: QueryList<TextSelectorItem>

  public ngOnInit() {
    this.selectItems.changes // throws "Cannot read property 'changes' of undefined"
      .subscribe(() => console.log('hit'))
  }
}
```

**Comment by ericmartinezr** [comment] 2016-07-14 01:56
@ContentChildren is set at ngAfterContentInit, if you have any question you can ask here https://gitter.im/angular/angular, we will be more than happy to help 😂

**Comment by tolemac** [comment] 2016-09-01 07:28
I have a similar issue adding children dynamically, [here the plunkr](http://plnkr.co/edit/JH7acOXvOOnml53WoIk6?p=preview)

`child` elements are added but subscribe callback isn't called ...

**Comment by moniuch** [comment] 2016-10-13 13:23
Sure thing fixing it takes time, but for the time being - is there any workaround to know when the children components have all initialized?

**Comment by lqbweb** [comment] 2016-10-17 17:36
having the same issue. I cannot add components dynamically because my QueryList does not get updated. Even calling .length() manually does not reflect the new component, how can this be?

**Comment by jsgoupil** [comment] 2016-10-26 01:29
@moniuch 

I have a workaround to go get the element on init.

```
import {
    Directive,
    EventEmitter,
    Output,
    OnInit
} from '@angular/core';

@Directive({
    selector: '[init]'
})
export class InitDirective implements OnInit {
    @Output() init: EventEmitter<any> = new EventEmitter();

    ngOnInit() {
        this.init.emit();
    }
}
```

```
<wm-input-text #model="ngModel" (init)="attach(model)" *ngSwitchCase="ControlType.Textbox" [(ngModel)]="control.value" name="{{ control.key }}" [ngModelOptions]="{ standalone: true }"></wm-input-text>
```

**Comment by tbosch** [comment] 2016-11-11 22:34
Closing as the issue is contained in https://github.com/angular/angular/issues/12818.

**Closed by tbosch** 2016-11-11 22:34 UTC
Labels: comp: core & compiler, freq1: low, severity3: broken, type: bug

**Comment by phil123456** [comment] 2018-10-03 10:34
ContentChildren returns undefined, can someone give an actual solution for this ?

**Comment by JoepKockelkorn** [comment] 2019-08-28 12:39
@phil123456 Yes, you can subscribe in the ngAfterContentInit lifecycle hook, [as described here](https://github.com/angular/angular/issues/12818#issuecomment-497013675), and start the stream with the current value with the rxjs startWith operator.

**Comment by pkozlowski-opensource** [comment] 2019-08-28 14:19
> For instance if an Input of one of the components queried by the ContentChildren decorator changes, I do not get notified in the 'changes' Observable of the QueryList.

@JoepKockelkorn queries should not change in response to changes on inputs alone - what matters if a set of _nodes_ matched by a query changed.

>  If the QueryList changes in length I do get notified so it seems it doesn't check for deep changes?

Again, `QueryList` notification on changes should fire if, and _only_ if a query list size (length) changes.

**Comment by JoepKockelkorn** [comment] 2019-08-28 14:50
@pkozlowski-opensource Ah ok, that makes sense then. So the correct way is probably to implement the ngAfterContentChecked lifecycle hook and manually check if the projected content has changed? At least thats is what the [cdk table component](https://github.com/angular/components/blob/master/src/cdk/table/table.ts) is doing.
