### ISSUE TITLE
[compiler] fullTemplateTypeCheck should emit better errors diagnostics (was: error on directives using @HostListener)

### ISSUE THREAD

**Issue by vanackere** [angular/angular#21329] opened 2018-01-05 11:19 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When fullTemplateTypeCheck is enabled, directives using @HostListener annotation fail to compile properly.

## Expected behavior

The directive should properly typecheck.

## Minimal reproduction of the problem with instructions

```ts
import { ElementRef, Directive, HostListener } from '@angular/core';

@Directive({
    selector: '[img-fade-in-fail]',
})
export class ImgFadeInDirectiveFail {
    constructor(private _elementRef: ElementRef) {
    }

    @HostListener('load', ['$event.target'])
    public onLoad() {
        this._elementRef.nativeElement.classList.add('in')
    }
}

@Directive({
    selector: '[img-fade-in-ok]',
})
export class ImgFadeInDirectiveWorks {
    constructor() {
    }
}
```

With `"fullTemplateTypeCheck": true` set in `tsconfig.json`, using the following template:

```html
<div img-fade-in-fail><div>
<div img-fade-in-ok><div>
```

Running `ngc` gives the following error:

```
ERROR in app.html(1,1): : Directive ImgFadeInDirectiveFail, Expected 0 arguments, but got 1.
```

## What is the motivation / use case for changing the behavior?

I'd like to properly typecheck all my templates

## Environment

<pre><code>
Angular version: 5.2.0-rc.0

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by devoto13** [comment] 2018-01-05 12:11
Isn’t it because onLoad method should have 1 argument?

**Comment by vanackere** [comment] 2018-01-05 12:32
Indeed you're right and I had just came to the same conclusion... I guess this bug should be about a better error message then, I'll change the bug title.

**Comment by emilio-martinez** [comment] 2018-04-27 15:52
I had this same behavior, and this is definitely confusing. My use case was (omitting extra stuff that's irrelevant):

```
@Component({
  selector: 'my-component',
  ...
})
export class MyComponent implements ControlValueAccessor {
  @HostListener('blur') _onTouched: (value: any) => void;
  registerOnTouched (fn: (value: any) => void) {
    this._onTouched = fn;
  }
}
```

And the error was in fact because it needed to be `@HostListener('blur', ['$event'])`. The need for adding `['$event']` is totally reasonable, but it was really hard to identify where the issue was. The error I got was

```
..(1,1): : Directive MyComponent, Expected 1 arguments, but got 0.
path/to/some-other-component/other-component.html(1,147): : Directive MyComponent, Expected 1 arguments, but got 0.
```

**Comment by JoostK** [comment] 2020-05-28 15:19
Confirmed in View Engine. Ivy does not yet support checking of host bindings, so you won't see this error in Ivy.

**Comment by JoostK** [comment] 2021-05-14 12:11
Closing as no longer an issue in Ivy (partially because it just does not type-check host bindings/listeners).

**Closed by JoostK** 2021-05-14 12:11 UTC
Labels: P5, comp: compiler, engine: ve, freq3: high, state: confirmed, triage #1, type: bug/fix
