### ISSUE TITLE
Angular v9 ivy - Can't bind to 'xxx' since it isn't a known property of 'xxx'.

### ISSUE THREAD

**Issue by emreyalvac** [angular/angular#35266] opened 2020-02-09 17:01 UTC
When i update Angular to v9 for ivy,

Can't bind to 'formGroup' since it isn't a known property of 'form'.

I'm using lazyload module structure. I still imported CommonModule to every lazy module.

```
Angular CLI: 9.0.1
Node: 12.14.1
OS: win32 x64
```

**Comment by jlandsmann** [comment] 2020-02-09 17:04
Are you sure you imported ReactiveFormsModule? https://angular.io/guide/reactive-forms

**Comment by emreyalvac** [comment] 2020-02-09 17:04
```
Can't bind to 'formGroup' since it isn't a known property of 'form'.
```

It's e.g. I'm getting error every element.

```
Can't bind to 'ngClass' since it isn't a known property of 'input'.
```

**Comment by syska** [comment] 2020-02-09 22:37
@emreyalvac 

Please write down how to recreate this issue ... 

ng new issue-35266
etc.

maybe just a link to a git repo.

**Comment by emreyalvac** [comment] 2020-02-10 11:49
> @emreyalvac
> 
> Please write down how to recreate this issue ...
> 
> ng new issue-35266
> etc.
> 
> maybe just a link to a git repo.

it's a private repo, sorry.

**Comment by ericmartinezr** [comment] 2020-02-10 12:11
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.

**Comment by pkozlowski-opensource** [comment] 2020-02-10 13:39
@emreyalvac I'm afraid that we will need some sort of reproduce scenario to be able to investigate further...

**Comment by kara** [comment] 2020-02-10 16:21
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.

**Closed by kara** 2020-02-10 16:21 UTC
Labels: comp: ivy, state: Needs repro

**Comment by Venipa** [comment] 2020-02-28 14:59
<details>
<summary>warning/error: Can't bind to 'uid' since it isn't a known property of 'app-user-avatar'.</summary>

```

  | warnAboutUnknownProperty | @ | core.js:12550
-- | -- | -- | --
  | elementPropertyInternal | @ | core.js:12404
  | ɵɵproperty | @ | core.js:20916
  | UserManagementComponent_mat_card_0_ng_container_65_mat_list_item_7_Template | @ | user-management.component.html:124
  | executeTemplate | @ | core.js:11930
  | refreshView | @ | core.js:11777
  | refreshDynamicEmbeddedViews | @ | core.js:13142
  | refreshView | @ | core.js:11800
  | refreshDynamicEmbeddedViews | @ | core.js:13142
  | refreshView | @ | core.js:11800
  | refreshDynamicEmbeddedViews | @ | core.js:13142
  | refreshView | @ | core.js:11800
  | refreshComponent | @ | core.js:13217
  | refreshChildComponents | @ | core.js:11508
  | refreshView | @ | core.js:11829
  | refreshComponent | @ | core.js:13217
  | refreshChildComponents | @ | core.js:11508
  | refreshView | @ | core.js:11829
  | refreshDynamicEmbeddedViews | @ | core.js:13142
  | refreshView | @ | core.js:11800
  | refreshDynamicEmbeddedViews | @ | core.js:13142
  | refreshView | @ | core.js:11800
  | refreshComponent | @ | core.js:13217
  | refreshChildComponents | @ | core.js:11508
  | refreshView | @ | core.js:11829
  | refreshDynamicEmbeddedViews | @ | core.js:13142
  | refreshView | @ | core.js:11800
  | refreshComponent | @ | core.js:13217
  | refreshChildComponents | @ | core.js:11508
  | refreshView | @ | core.js:11829
  | refreshDynamicEmbeddedViews | @ | core.js:13142
  | refreshView | @ | core.js:11800
  | refreshComponent | @ | core.js:13217
  | refreshChildComponents | @ | core.js:11508
  | refreshView | @ | core.js:11829
  | renderComponentOrTemplate | @ | core.js:11903
  | tickRootContext | @ | core.js:13379
  | detectChangesInRootView | @ | core.js:13413
  | detectChanges | @ | core.js:15093
  | tick | @ | core.js:42683
  | (anonymous) | @ | core.js:42533
```
</details>

module has been imported in all pages where im using it

<details>
<summary>user-avatar.component.ts</summary>

```
private _uid = new BehaviorSubject<string>(null);
  readonly uid$ = this._uid.asObservable().pipe(
    distinctUntilChanged(),
    tap(x => log.debug('uid', x))
  );
  get uid() {
    return this._uid.getValue();
  }
  @Input()
  set uid(val: string) {
    this._uid.next(val);
  }
```
</details>
<details>
<summary>usage in another component</summary>

```
<app-user-avatar size="24px" class="rounded-circle flex-shrink-0 mr-2" defaultImageSource="/assets/img/default.png" [uid]="user.id"></app-user-avatar>
```
</details>

**Comment by mlc-mlapis** [comment] 2020-02-28 15:08
@Venipa Why don't you understand that a simple reproduction demo is always the key for any solution?

**Comment by petebacondarwin** [comment] 2020-02-28 15:24
@mlc-mlapis - thank you for chiming in here but please be careful that the language you use is respectful and constructive. This comment is not in line with out code of conduct https://github.com/angular/angular/blob/master/CODE_OF_CONDUCT.md.

@Venipa - please could you open a new issue with a runnable reproduction, since this indeed would speed up analysis and resolution of your problem.

**Comment by mlc-mlapis** [comment] 2020-02-28 15:51
@petebacondarwin Oh, I apologize, I am not a native English speaker, so I didn't think that it was something wrong. Can you reformulate the sentence please, to show me the mistakes or a wrong formulation? I originally wanted to ask, what @Venipa didn't understand that he should do. Thank you.

**Comment by Venipa** [comment] 2020-02-28 16:06
I commented on this issue while I was working so I just put a error log on what happened, I may open a new issue with a repro Stackblitz if I have time

**Comment by petebacondarwin** [comment] 2020-02-28 16:09
@mlc-mlapis - no problem. I understand that it is not always obvious to a non-native speaker. I think you probably meant to say something more along the lines of simply "In case you don't know, a simple reproduction demo will help to get a solution for your problem quicker."

**Comment by yarostbaklajana** [comment] 2020-03-03 13:45
@emreyalvac Hello, just found a solution, 
I use lazy loading and when I import the ReactiveFormsModule to ChildModule  I receive the same error, so (in two hours) I tried to import ReactiveFormsModule to ChildRoutingModule and it worked !! I do not know why it is not seen within the direct ChildModule but this how it goes
