### ISSUE TITLE
NgSwitch not running after migrate from 2.0.0-beta15 to 2.0.1

### ISSUE THREAD

**Issue by toni-moreno** [angular/angular#12145] opened 2016-10-07 11:58 UTC
Hi , I 'm upgrading my code from beta15 to 2.0.1. I read first the Changelog and ngSwitch It seem to have only a breaking change "ngSwitchWhen "to "*ngSwitchCase".

https://github.com/toni-moreno/snmpcollector/blob/angular2_final_migration/public/home/home.html

my final code is 
```
   <p [ngSwitch]="item_type">
      <template *ngSwitchCase="snmpdevice">
      	<h1>SNMP Devices</h1>
      </template>
      <template *ngSwitchCase="snmpmetrics">
      <h1> SNMP Metrics</h1>
      </template>
      <template *ngSwitchCase="ifluxmeas">
      <h1>measurents</h1>
      </template>
      <template *ngSwitchCase="metricgroup">
      <h1>metric Group</h1>
      </template>
      <template *ngSwitchDefault>DEFAULT</template>
    </p>
```

**I'm submitting a ...**  (check one with "x")
```
[ X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
It is not seleccting any value , ignoring all html tags inside <p [ngSwitch]="xxx"> </p>

**Expected behavior**

depending on the variable xxx angular put data , sometimes `"<h1>SNMP Devices</h1>"` other `"<h1>SNMP Metrics</h1>`, etc.

**Minimal reproduction of the problem with instructions**

Download my repo https://github.com/toni-moreno/snmpcollector and switch to angular2_final_migration brach follow built instructions https://github.com/toni-moreno/snmpcollector/blob/master/README.md
 
When you connect to the server , http://localhost:8090/

**What is the motivation / use case for changing the behavior?**

Version Upgrade

**Please tell us about your environment:**
OS: Debian Linux
IDE: atom
package manager : npm
HTTP Server: self made in the package based in golang + macaron

* **Angular version:** 2.0.X
2.0.1 ( working fine in 2.0.0-beta15)

* **Browser:** 
Chrome
 
* **Language:** 
Typescript

* **Node (for AoT issues):** `node --version` =   6.2.1

**Comment by DzmitryShylovich** [comment] 2016-10-07 12:00
Can you provide a minimal reproduction in plunkr?

**Comment by kemsky** [comment] 2016-10-07 12:08
See `*ngSwitchCase="snmpdevice"`,  in this line angular expects `snmpdevice` to be a variable, but you want a string constant.

Correct way: `*ngSwitchCase="'snmpdevice'"`  notice single quotes.

I think `NgSwitch` documentation is not clear on this and thus confusing, `*` syntax is also confusing (no [] used).

**Comment by atifsaddique211f** [comment] 2016-10-07 12:33
Yes, @kemsky is right, you need to provide string constant for *ngSwitchCase

**Comment by toni-moreno** [comment] 2016-10-07 13:35
Hi @kemsky , thanks a lot for the fast response.

I've added sigle quotes but it doesn't seem to fix the problem.

I've updated the branch and you can see the code

https://github.com/toni-moreno/snmpcollector/blob/angular2_final_migration/public/home/home.html#L42
https://github.com/toni-moreno/snmpcollector/blob/angular2_final_migration/public/home/home.ts

The variable item_type switch by click on the navigation sidebar as you can see in the following screenshot.

![image](https://cloud.githubusercontent.com/assets/5883405/19191536/30a76ad2-8ca3-11e6-9aef-f64f673f8705.png)

 this is the logic to switch content in the main view in (home.ts)

````
  SNMPDevices() {
	  this.item_type = "snmpdevice";
	  console.log('SnmpDevices!!!');
  }

  SNMPMetrics () {
	  this.item_type = "snmpmetrics";
	  console.log('SnmpMetrics!!!');
  }
  IflxMeasurements() {
	  this.item_type = "ifluxmeas";
  }
  MetricGroups() {
	  this.item_type = "metricgroup";
  }
  InfluxServers() {
	  this.item_type = "influxserver";
  }
````
Any other idea?

**Comment by micronyks** [comment] 2016-10-07 14:40
The problem is with `*` and `<template>` syntax. Make sure when you use `*` with any directives, you should not use `<template>` tag. And, when you want to use `<template>` tag, you should wrap  directive within `[  ]`.

more information can be found here : https://angular.io/docs/ts/latest/api/common/index/NgSwitch-directive.html#!#ngSwitch-anchor

So this code
```
<p [ngSwitch]="item_type">
      <template *ngSwitchCase="snmpdevice">
        <h1>SNMP Devices</h1>
      </template>
      ...
      ...
</p>
```
you should change it to,

```
<p [ngSwitch]="item_type">
      <template [ngSwitchCase]="'snmpdevice'">   ///<<<===also note " 'snmpdevice' "
        <h1>SNMP Devices</h1>
      </template>
      ...
      ...
</p>
```
**play here : https://plnkr.co/edit/FkcQdB2FoV345L6F6oBZ?p=preview**

If it solves your problem, please close this issue.

**Comment by vicb** [comment] 2016-10-07 16:47
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.

**Closed by vicb** 2016-10-07 16:47 UTC
Labels: comp: common, state: Need repro

**Comment by toni-moreno** [comment] 2016-10-07 20:12
Hi @micronyks I've finally fixed the error  following your example.

@vicb sorry by this issue, I was looking for examples and info about NgSwitch first on the official angular site in the API section also in  the github changelog , and there is any example with [ngSwitchCase] instead of *ngSwitchCase, I'm  newbie in angular and there were thousands of breaking changes in last releases , in this scenario II thought this issue might be  a code bug. But has been finally  a leak of documentation.

Thank you very much to everybody
