### ISSUE TITLE
angular changes `class.*` bindings to camelCase.

### ISSUE THREAD

**Issue by ajoslin** [angular/angular#1109] opened 2015-03-26 02:22 UTC
This will set the `dashCase` class on the button to true or false depending upon the value of `binding`.

```js
<button [class.dash-case]="binding"></button>
```

I know dash-case to camelCase conversion is actually a "feature" built into the attribute parser, but it should have exceptions in cases like this.

The last thing I would expect is for angular to camel my classNames.

**Comment by pkozlowski-opensource** [comment] 2015-03-26 06:31
This is duplicate of https://github.com/angular/angular/issues/1057 and has a PR already (https://github.com/angular/angular/pull/1059)

@mhevery @jelbourn @vicb could one of you guys please review #1059 so it gets in? There is a second person bumping into this issue in the last couple of days...

**Closed by pkozlowski-opensource** 2015-03-26 06:31 UTC
