### ISSUE TITLE
Async validation sets formControl to valid even if sync validation is invalid

### ISSUE THREAD

**Issue by JohanDavidsson** [angular/angular#12709] opened 2016-11-04 13:46 UTC
**I'm submitting a ...** 
```
[X] bug report
```

**Current behavior**

If I have a sync and a async validation on a formControl the async validation overwrites the sync validation when it comes back even if the value has changed. So if I put in something in a field that passes the sync validation the async validation triggers. However when I then change the value of the field before the last async validation have come back to something that doesn't pass the sync validation the last value async validation becomes the winning one.

**Expected behavior**

Probably that the async validation should be ignored if the value has changed since the request?

**Minimal reproduction of the problem with instructions**

http://plnkr.co/edit/MrY2Gq03dNjp8hvET3cn?p=preview

1. Fill in whatever@whatever.com in the input field.
2. Within 5 seconds, change the value of the field to asdf.
3. Wait a second or two and now the Control is valid, but asdf is not valid according to the sync validation.  

* **Angular version:** 2.1.12

* **Browser:**: Tested in latest Chrome and Safari

* **Language:**: Typescript

**Comment by MehdiSaeedifar** [comment] 2016-11-11 07:52
+1

**Comment by xban1x** [comment] 2016-11-15 10:55
This is still present in 2.2.0

**Comment by DzmitryShylovich** [comment] 2016-12-11 09:46
Duplicate of https://github.com/angular/angular/issues/8923

**Closed** 2017-01-31 23:11 UTC
Labels: comp: forms
