### ISSUE TITLE
Pipes API documentation is not opening.

### ISSUE THREAD

**Issue by Chamanjaiswal** [angular/angular#53782] opened 2024-01-03 18:32 UTC
### Describe the problem that you experienced

When I open this page it's not open.

### Enter the URL of the topic with the problem

https://angular.dev/api/common#pipes

**Comment by JeanMeche** [comment] 2024-01-03 18:40
This issue is on : https://angular.dev/guide/pipes

**Comment by JoostK** [comment] 2024-01-03 18:45
Thanks for the report, closing as duplicate of https://github.com/angular/angular/issues/52968. The fix is still awaiting deployment.

**Closed by JoostK** 2024-01-03 18:45 UTC
Labels: help wanted, good first issue, area: adev
