### ISSUE TITLE
Type declaration for ActivatedRoute.fragment doesn't declare possible null values

### ISSUE THREAD

**Issue by StevenLiekens** [angular/angular#23894] opened 2018-05-14 10:02 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

The type declaration for `ActivatedRoute.fragment` declares that it will emit string instances and nothing else.

```ts
interface ActivatedRoute {
  fragment: Observable<string>
}
```

To my surprise, it emits `null` values for routes that don't have a fragment.

## Expected behavior

I see three valid options here (in no particular order):
1. emit `''` instead of `null` for missing fragments
2. don't emit at all for missing fragments
3. just change the type declaration to `Observable<string | null>`

## Minimal reproduction of the problem with instructions

https://angular-nullable-fragment.stackblitz.io

## What is the motivation / use case for changing the behavior?

![image](https://user-images.githubusercontent.com/1583241/39991016-76c5cdfa-576e-11e8-8396-39ed2a2d6a65.png)

## Environment

<pre><code>
Angular version: 5.2.9

Browser:
- [x] Chrome (desktop) version 65
- [x] Firefox version 59

Others:

</code></pre>

**Comment by jasonaden** [comment] 2018-05-24 22:47
Thanks, good issue. Unfortunately this can't be changed until v7 because it will be a breaking change for people's code. But I added it to the v7 milestone so we don't forget it.

**Comment by MatthiasKunnen** [comment] 2018-12-15 18:51
I get `undefined` from the observable instead of null. angular/router@6.0.5.
I could make a PR to change this to `Observable<string>`, `Observable<string | undefined>`, or `Observable<string | null | undefined>` but I would need to know which. 

The milestone should be updated to v8.0 I suppose.

**Comment by StevenLiekens** [comment] 2018-12-22 12:31
Here's a demo of the issue (tested in Chrome) https://angular-nullable-fragment.stackblitz.io

**Comment by rgant** [comment] 2020-05-01 13:29
This is still an issue in v8. Has it been resolved in v9? Or will it be in v10?

**Comment by atscott** [comment] 2020-05-28 16:43
Confirmed this is still an issue in v9 (and will be in v10 as there's not been a merged PR to fix it). Earliest possible fix would be v11 since this is a breaking change.
https://stackblitz.com/edit/angular-nullable-fragment-iqrp3t?file=src%2Fapp%2Fapp.component.html

**Comment by MatthiasKunnen** [comment] 2020-05-28 16:48
@atscott, I'd be happy to create a PR changing nullish values to an empty string `''`. Would such a PR be accepted?

**Comment by atscott** [comment] 2020-05-28 19:28
Hi @MatthiasKunnen, I think the correct fix would really be to do what was proposed already, by making it `Observable<string|null>`. This matches the typing on the `UrlTree` https://github.com/angular/angular/blob/0cd843169884a57d92c1ec114f7e778720b5ef24/packages/router/src/url_tree.ts#L118

**Closed** 2021-03-22 17:02 UTC
Labels: P3, comp: router, flag: breaking change, freq3: high, help wanted, state: confirmed, state: has PR, triage #1, type: bug/fix
