### ISSUE TITLE
Locaction change events fired twice when using HashLocationStrategy

### ISSUE THREAD

**Issue by lorenzodallavecchia** [angular/angular#12146] opened 2016-10-07 13:07 UTC
**I'm submitting a ...**  (check one with "x")

```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
If an app uses `HashLocationStrategy` and the URL hash is changed manually, the `subscribe` observable of the `Location` service will fire two events for the same change. This will also occur if the browser back/forward buttons are used or when clicking a traditional anchor with `href="#foo"`.

**Expected behavior**
The `Location` service should emit exactly one event for each discrete change in location.

**Minimal reproduction of the problem with instructions**
See [this plunkr](https://plnkr.co/edit/RBd4TJd9d39aW7VvigHY?p=preview). Click the _One_ and _Two_ anchors to see the events logged. You may also want to open the plunkr in a separate window and change the hash manually.
As you can see, two events are logged for each change.

**What is the motivation / use case for changing the behavior?**
Although `Location` by itself may cause trouble, the main issue is that each location change event is scheduling a new router navigation. Appearently, the router cannot remember that it is already in the process of changing to an URL and issues a second navigation to the same URL.
The end result is that there will be two router navigations running in parallel. In my experience, it at least causes double invocation of guards/resolvers.
- **Angular version:** 2.0.2 up to 2.1.0-rc.0
- **Browser:** Chrome 53, Firefox 49
- **Language:** all

**Comment by popalexandruvasile** [comment] 2016-11-01 15:52
Just to confirm that this issue also occurs when you perform a manual browser refresh for the current page. I am surprised that apparently few people experienced this issue as it seems a blocker for anyone trying to use hash based routing in a mixed Angular 2/ non Angular 2 app scenario.  
If you have non Angular 2 sections in a page that uses anchors to change the route for the Angular 2 section from the same page then the hash based location strategy is not working properly.
This was the main problem for us when moving to the new and improved v3 router :)

**Comment by popalexandruvasile** [comment] 2016-11-03 12:53
Both the original issue and the issue I experienced seemed to be fixed in Angular 2.2.0-rc.0 .
I think this ticket can be closed.

**Comment by DzmitryShylovich** [comment] 2016-12-04 20:56
Confirmed. Cannot reproduce the issue using the latest version. https://plnkr.co/edit/RBd4TJd9d39aW7VvigHY?p=preview There's only 1 event of each type.
@pkozlowski-opensource can be closed.

**Comment by pkozlowski-opensource** [comment] 2016-12-04 21:00
Thnx @DzmitryShylovich

**Closed by pkozlowski-opensource** 2016-12-04 21:00 UTC
Labels: comp: router, freq2: medium, severity1: confusing, type: bug
