### ISSUE TITLE
Add a note indicating in which specific version a feature was introduced

### ISSUE THREAD

**Issue by Alex88360** [angular/angular#57818] opened 2024-09-15 15:43 UTC
### Describe the problem that you experienced

When I'm searching for a specific functionality on the angular.dev site, there is nowhere where I can find at which version a feature has been introduced.

**Comment by jnizet** [comment] 2024-09-15 19:18
Just in case: if the goal for you is to know if you can use that functionality in your app, using an old version of the framework, then you should browse the documentation of the version you're currently using instead. For example, if you're still using Angular 17, use https://v17.angular.io/docs. 
The select box at the top left of https://angular.dev/ allows switching to any old version.

**Comment by JoostK** [comment] 2024-09-15 19:23
Duplicate of #49668.

**Closed by JoostK** 2024-09-15 19:23 UTC
