### ISSUE TITLE
Routing breaks SVG rendering

### ISSUE THREAD

**Issue by chrisber** [angular/angular#11284] opened 2016-09-02 12:27 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```
------
*Updates sugessted by* @vicb 

**Current behavior**
When using the component router the svg inside a template does not render correctly,  in this case the text  and path is not shown.

**Expected/desired behavior**
Should show a rendered svg text like:
https://developer.mozilla.org/de/docs/Web/SVG/Element/textPath 
[codepen](https://codepen.io/anon/pen/ORPjgr)

**Reproduction of the problem**
*Minimal none working  plunker*
[With routing-outlet](http://plnkr.co/edit/CwvL3f?p=preview)

*Minimal working  plunker when router outlet it commented out at line [66-71] in app.ts*
[commented out routing-outlet](http://plnkr.co/edit/V8IFUj?p=preview)

**What is the expected behavior?**
When using the component router with a router-outlet the SVG stops rendering correctly.
The issue here ist that the SVG path and textpath does not have coordinates . 

**What is the motivation / use case for changing the behavior?**
Create an svg with with the Angular framework and use D3 only as layout engine.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.X
 
* **Browser:** [ Chrome XX | Firefox XX ] 
 
* **Language:** [ TypeScript ] 

-------
*Old description*
**Reproduction of the problem**
 Starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

Using the provided plunker the svg renders correctly:
http://plnkr.co/edit/QTC26b1KRSbLinutw6D0?p=preview

Using the router example from the [docs ROUTING & NAVIGATION](https://angular.io/docs/ts/latest/guide/router.html) and adding the svg snippet to app/app.component.ts then the rendering of the svg breaks:
http://plnkr.co/edit/KPzL8CeQ3K8k5CLr3yE6?p=preview

When removing the router completely then the rendering works again:
http://plnkr.co/edit/wyhPaJHl1i2rNrXfD57h?p=preview

**Comment by eseliger** [comment] 2016-09-05 05:16
Hmm your plunkr(http://plnkr.co/edit/KPzL8CeQ3K8k5CLr3yE6?p=preview) seems to work in Safari 9 on macOS 10.11, but neither in Firefox nor Chrome.

**Comment by vicb** [comment] 2016-09-05 07:57
Don't know how to reproduce the issue:
- please provide a *minimal* plunker,
- add steps to reproduce the issue together with current and expected behavior

**Comment by chrisber** [comment] 2016-09-05 08:32
Hi @vicb  thanks for having a look at this issue. 

I want to ask you politely to please have a look at it again, @eseliger was able to reproduce the issue.
Please validate the working example
1. [without router component] (http://plnkr.co/edit/QTC26b1KRSbLinutw6D0?p=preview) 
against the 
2. [none working example with routing](http://plnkr.co/edit/KPzL8CeQ3K8k5CLr3yE6?p=preview) 
where the only difference is that the app/app.component.ts contains a router-outlet.

Where changes in 1 (src/app.ts) and 2 (app/app.component.ts) are  made.

So far I can tell that the rendering does not work on Ubuntu 16.04 with firefox and chrome.
The expected output is: https://jsfiddle.net/api/mdn/

**Comment by chrisber** [comment] 2016-09-05 13:09
@vicb please remove tag `can be closed` *minimal* plunker was added.

**Comment by vicb** [comment] 2016-09-06 22:07
Found the root cause thanks to @tbosch: the problem is that the `href` in `<use xlink:href="#MyPath" fill="none" stroke="red"  />` does not play well with the html `pushState` API.

See also the accepted answer for http://stackoverflow.com/questions/19742805/angular-and-svg-filters

closing as not angular specific

**Closed by vicb** 2016-09-06 22:07 UTC
Labels: flag: can be closed?

**Comment by zoechi** [comment] 2016-09-07 06:45
Have you tried to configure `<base href="...">` so that it works with SVG and configure the router by providing `APP_BASE_HREF`?

**Comment by MikaAK** [comment] 2018-01-17 12:14
https://github.com/jeffbcross/angular-svg-base is the ng1 version that makes svg filters work.  Seems a ng2 version is needed

Adding `<base href='...'>` ends up causing filters to not work (check safari, chrome has patched this issue a while back). Removing this and using `APP_BASE_HREF` works well until you create routes like `/my-route/child-routes` at which point the base tag is  required else it's looking for assets at `example.com/my-route`

**Comment by ohabash** [comment] 2019-08-11 20:47
what does it mean "using APP_BASE_HREF" ?is that an angular.json thing?
