### ISSUE TITLE
Typescript configuration link from v17 docs broken

### ISSUE THREAD

**Issue by karsenkeith** [angular/angular#57169] opened 2024-07-28 17:02 UTC
### Describe the problem that you experienced

A google search led me to the legacy documentation page for Angular typescript configuration: https://v17.angular.io/guide/typescript-configuration

After arriving there I tried to follow the "Head to Angular.dev" button to find the updated docs. This brought me to https://angular.dev/reference/configs/typescript-configuration which gave a "Page not found" error.

### Enter the URL of the topic with the problem

https://angular.dev/reference/configs/typescript-configuration

### Describe what you were looking for in the documentation

The equivalent of the old docs https://v17.angular.io/guide/typescript-configuration

**Comment by JeanMeche** [comment] 2024-07-28 20:26
I'll close this as a duplicate of #56893, I wouldn't know where to redirect though.

**Closed by JeanMeche** 2024-07-28 20:26 UTC
