### ISSUE TITLE
Make ngNonBindable totally non-bindable

### ISSUE THREAD

**Issue by moniuch** [angular/angular#54488] opened 2024-02-17 12:31 UTC
### Which @angular/* package(s) are relevant/related to the feature request?

compiler, core

### Description

I need to be able to provide an example of Angular component usage as a snippet of code. The `ngNonBindable` directive seems to work fine on the mustache/interpolation strings, such as `{{ test }}`, but it still tries to bind `[inputs]` and `(outputs)` within the snippet. 

```html
<code ngNonBindable> <!-- the placement of the directive doesn't seem to matter -->
<pre><my-comp
    (test)="test = test.toUpperCase()"
  ></my-comp></pre>
</code>
```

Failing with:

```
ERROR DOMException: Failed to execute 'setAttribute' on 'Element': '(test)' is not a valid attribute name
```

Thus, it's only half-useful and a bit contradictory to its name.

### Proposed solution

First off, I don't know Angular internals around this subject well enough, so it is difficult for me to propose a solution. 

From DX PoV, I would like to be able to grab any piece of Angular template code, enclose it in a `<code><pre>` markup, drop the `ngNonBindable` and be done. Later, should I need to update the code part, I'd just paste new code. All without HTML escaping hassle.

For this flow to be possible I'd expect the `ngNonBindable` directive to do what it says, and literally stop binding anything that lies within its scope. `Anything` includes: inputs, outputs, attribute directives, structural directives, new control flow blocks, `<ng-template>`s, `<ng-container>`s, `<ng-content>`, etc. 

![image](https://github.com/angular/angular/assets/681956/d8237d90-15f1-4a5a-9439-5f0c4000b6f7)

I imagine that with this in place, IDEs' syntax highlighting could render the code within `ngNonBindable` with dimmed colors or as regular HTML - which at that time would be aligned with the actual directive behavior.

Or maybe this directive could become a new code flow syntax element?

![image](https://github.com/angular/angular/assets/681956/d938400b-60b3-4915-96a7-21edd8c95642)

### Alternatives considered

The alternative is to just escape html, but one would expect the `ngNonBindable` directive to work exactly as its name implies. You just drop-in your real working code, add `ngNonBindable` and you're done.
Also, having to escape the html makes the code hardly maintainable. Overall, poor DX.

**Comment by JeanMeche** [comment] 2024-02-19 01:00
I think we could consider it a duplicate of #11859. What do you think ?

**Comment by moniuch** [comment] 2024-02-19 10:19
@JeanMeche Not sure about that. From what I can gather the other ticket is mostly about the brace characters. Seems like even if solved it would not solve my problem, ie. Angular would still try to bind inputs, outputs, directives, etc.

**Comment by JeanMeche** [comment] 2024-02-19 10:40
I was thinkin of the comment by Pawel: 
> I can totally see hoe this one is confusing as it is not clear what is the intent of ngNonBindable - should it just "switch off" bindings or ignore all Angular constructs (special chars in template, i18n etc.).

**Comment by pkozlowski-opensource** [comment] 2024-02-19 18:58
> The ngNonBindable directive seems to work fine on the mustache/interpolation strings, such as {{ test }}, but it still tries to bind [inputs] and (outputs) within the snippet.

To be precise - Angular is _not_ trying to match directives, set inputs or listen to events when `ngNonBindable` is used (!). Looking at the minimal reproduction scenario:

```html
<div ngNonBindable>
   <button (click)="onClick()">Click me</button>
</div>  
```

Angular will interpret `(click)="onClick()"` as an attribute with the name `(click)` and value `"onClick()"` resulting in 

> VM526:1 Uncaught DOMException: Failed to execute 'setAttribute' on 'Element': '(click)' is not a valid attribute name.

Live reproduction scenario: https://stackblitz.com/edit/stackblitz-starters-eslmcq

The error happens precisely because  `ngNonBindable` was used (!) and it happens because Angular tries to build the DOM using sth equivalent to: 

```javascript
const button = document.createElement('button');
button.setAttribute('(click)', 'onClick()');
```

As a side note, browsers specs are _wonderfully_ inconsistent as the following works _just fine_:

```html
div.innerHTML = '<button (click)="onClick()">Click me</button>'
```

**Comment by pkozlowski-opensource** [comment] 2024-02-19 18:59
> The alternative is to just escape html,

This is the only viable alternative for now.

**Closed** 2024-04-09 15:52 UTC
Labels: area: core, area: compiler, core: basic template syntax
