### ISSUE TITLE
createEmbeddedView creates view at the wrong location

### ISSUE THREAD

**Issue by rehdie** [angular/angular#38024] opened 2020-07-13 17:26 UTC
# 🐞 bug report

If you create an embeddedView using viewContainerRef.createEmbeddedView, the view is created outside the given container.

### Is this a regression?

The behaviour described in https://github.com/angular/angular/issues/33679 has been introduced again in angular 10.

### Description

See https://github.com/angular/angular/issues/33679. The same Issue can be reproduced with angular 10 (tested with 10.0.0 and 10.0.3).

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-fafstx?file=src%2Fapp%2Fapp.component.css

## 🌍  Your Environment

**Angular Version:**
<pre><code>

angular 10.0.0 and 10.0.3 (using ivy)
macOS Catalina
Chrome/Electron/Safari

</code></pre>

**Comment by pkozlowski-opensource** [comment] 2020-07-27 09:59
@rehdie looking at the scenario in your stackblitz, it doesn't look like a duplicate of #33679 at all - it seems like a completely different scenario to me (especially that we've added tests for the scenario from #33679 so a regression is unlikely). 

Also, this is not specific to ivy nor a regression - Angular behaviour was _always_ like this! I think that the confusing part here is where templates inserted via `ViewContainerRef` are inserted in the DOM - in Angular views are _always_ inserted as _siblings_ of a node on which you request a `ViewContainerRef` (`<div class="text--red" #container>` in your case). If you want to insert DOM nodes as _children_ of a given node, you should ask for a `ViewContainerRef` on  child:

```html
<div class="text--red">
  <div #container></div>
</div>
```

See: https://stackblitz.com/edit/angular-5dxs1n?file=src%2Fapp%2Fapp.component.html

I'm going to close this issue as the Angular works as designed here - I understand that it might be _unexpected_ but this is how the framework worked from the very beginning and I don't think we plan any changes here (it would be a substantial design undertaking with unclear benefits and a massive breaking change).

**Closed by pkozlowski-opensource** 2020-07-27 09:59 UTC
Labels: comp: core, core: dynamic view creation
