### ISSUE TITLE
Swedish letters in input placeholder makes form dirty on init

### ISSUE THREAD

**Issue by Drol** [angular/angular#16151] opened 2017-04-19 10:24 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Using reactive forms. When swedish letters (åäö) is used in a input placeholder, the form and input is initialized as dirty. <input placeholder="åäö">

This only affects IE11, or perhaps also earlier versions of IE.

**Expected behavior**
The form and input should not be dirty because of swedish letters in placeholder.

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/u3iEtQ?p=preview
~~http://plnkr.co/edit/LpZNI9m7j8m8tgXRFdVG?p=preview~~ (old plunk with typo and not working)

**What is the motivation / use case for changing the behavior?**
bug

**Please tell us about your environment:**
Windows 10

* **Angular version:** 4.0.2, also affects 2.x

* **Browser:** Internet Explorer 11
 
* **Language:** all

**Comment by Teofrey** [comment] 2017-05-08 11:54
Sadly I noticed the same issue with CCJK characters.

**Comment by kneefer** [comment] 2017-05-08 11:58
Any feedback? Will anyone take a look on this problem? It's really annoying and forces developers to use ugly tricks in order to support IE properly.

**Comment by tytskyi** [comment] 2017-05-08 20:11
@Drol please check your own plunker - both inputs are marked as dirty in IE 11. Therefore bug is not related to swedish letters. 

This is known bug and duplicate of https://github.com/angular/angular/issues/14440

Please close the issue in favour of original.

@Teofrey, @kneefer please check the original issue.

**Comment by Drol** [comment] 2017-05-09 08:59
@tytskyi Sorry I made a typo in the plunk i provided. I have updated the original post with a working plunk.

Yes a saw that bug when i reported this one. And it may be related but it is not exactly the same type of bug.

Again sorry for the not working plunk.

**Comment by apurvjain** [comment] 2017-06-21 07:30
I am also facing the same issue with Chinese Characters as a placeholder on mdInput, for English characters looks fine but other characters the from becomes dirty instead of pristine on init. waiting for the solution?

**Comment by flensrocker** [comment] 2018-03-13 11:15
Same here with german umlauts.

**Comment by AnkHansen** [comment] 2018-05-17 11:01
And after six hours of debugging - I can vote in that Danish characters has same flaw. In my case the letter 'ø'. 

Used all night yesterday digging through our code to figure out why 1 of 4 totally similar fields always was dirty - the 3 others not in Internet Explorer. 

And lets just be honest - debugging Angular in dev mode in Internet Explorer 11 is not that fun. 

First today a colleague noticed the difference that this field had placeholder "Leverandørnr". Changing the danish translation fixed the issue. Logging in as English user - fixed the issue. 

Anyone has a decent workaround for this? Or do we need to wait for the Angular Material team to pick this up - we have nearly 100% danish customer base - so this is quite critical for us.

**Comment by petebacondarwin** [comment] 2020-03-07 21:08
Perhaps a special case of https://github.com/angular/angular/issues/15299?

**Comment by dylhunn** [comment] 2021-08-16 20:11
IE11 support is removed from the framework now, closing.

**Closed by dylhunn** 2021-08-16 20:11 UTC
Labels: type: bug/fix, freq2: medium, comp: forms, state: confirmed, forms: DOM, browser: ie 11, triage #1, P4
