### ISSUE TITLE
Is it possible (or can it be) to add an attribute to an element dynamically

### ISSUE THREAD

**Issue by brandyscarney** [angular/angular#5361] opened 2015-11-18 19:12 UTC
In Ionic we use a lot of attributes. For example, say we have an attribute called `primary` that we only want added if the platform is Android. Doing something like this on an element:

```
<div [attr.primary]="isAndroid"></div>
```

Would be added as `primary="true"` for Android and `primary="false"` for iOS. We want it to not add `primary` at all if iOS, and add just `primary` if Android.

cc @IgorMinar @adamdbradley

**Comment by fxck** [comment] 2015-11-18 19:38
dup of https://github.com/angular/angular/issues/5332 I think

**Comment by IgorMinar** [comment] 2015-11-18 20:38
not quite a dupe of #5332 but maybe that solution could work for attributes as well? I don't see why not.

**Comment by pkozlowski-opensource** [comment] 2015-11-19 09:40
This is kind of possible today with `<div [attr.primary]="isAndroid ? '' : null">` - when an expression evaluates to `null` an attribute will be removed AFAIK. But yeh, maybe we should have some kind of sugar for boolean attributes?

**Comment by pkozlowski-opensource** [comment] 2015-11-19 09:41
See https://github.com/angular/angular/issues/2869#issuecomment-123032491 as well

**Comment by ericmartinezr** [comment] 2015-11-19 11:25
If I may ask, wouldn't be better to wait for multiple `@View()`'s? With those you will write specific templates for each View (android, iOS, desktop, etc), you won't check in iOS view if it is Android or viceversa, that would save you those conditions.

**Comment by brandyscarney** [comment] 2015-11-19 16:31
Thank you @pkozlowski-opensource ! That works for me. 

Hey, @ericmartinezr - thanks for the tip! There are just certain cases where we want to add an attribute to an element without duplicating all of the markup or splitting them into multiple files. :)

**Comment by brandyscarney** [comment] 2015-11-24 18:27
Also, is there a way to add an attribute based on an expression value? Similar to how `ng-class` works:

```
<div [ng-class]="myClass">
```

where `myClass = 'primary'` and the class `primary` is added to the element. I searched around and couldn't find anything, sorry if I overlooked something.

**Comment by pkozlowski-opensource** [comment] 2015-11-24 18:46
@brandyscarney there is no syntax for this. You could do with a lower-level manipulation (ElementRef) but probably it is a good idea to have all the attributes explicit in a template.

**Comment by brandyscarney** [comment] 2015-11-24 19:37
@pkozlowski-opensource thanks for the quick reply. :)

**Closed** 2016-03-02 20:37 UTC
Labels: hotlist: Ionic, type: feature
