### ISSUE TITLE
RouteReuseStrategy store method called twice

### ISSUE THREAD

**Issue by bjdash** [angular/angular#42794] opened 2021-07-08 09:50 UTC
# Bug Report

### Affected Package

 The issue is caused by package @angular/router

### Is this a regression?

 Not sure

### Description
 While using RouteReuseStrategy and navigating between different routes, the store method is called twice. Once for the route we are leaving and again for the destination route.

## Minimal Reproduction

https://stackblitz.com/edit/angular-ivy-fdaqxs

## Exception or Error
Once the application loads in stackblitz, click on designer, then click on tester and check console logs.
At this stage the logs will be as shown below and everything is as expected.
<pre><code>created Designer component
should detach designer
Storing ƒ DesignerComponent()
creted tester component
</code></pre>
Now click on designer link again and check logs
<pre><code>should detach tester //Tries to unload tester as we are navigating away
Storing ƒ TesterComponent() //Stores the tester component
Storing ƒ DesignerComponent() //BUG: Why does it try to store designer again? 
</code></pre>
## Your Environment

**Angular Version:**
<pre><code>
Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.2
@angular-devkit/build-angular   0.1102.2
@angular-devkit/core            11.2.2
@angular-devkit/schematics      11.2.2
@angular/cdk                    11.2.2
@angular/cli                    11.2.2
@angular/material               11.2.2
@schematics/angular             11.2.2
@schematics/update              0.1102.2
rxjs                            6.5.5
typescript                      4.1.5
</code></pre>

**Anything else relevant?**

**Comment by Pashozator** [comment] 2021-07-08 18:56
@atscott please describe desired behavior.

**Comment by atscott** [comment] 2021-07-08 19:04
Closing as working as intended. Upon activation, the router code calls `store` with `null` as the `DetachedRouteHandle` to clear the previous value.
https://github.com/angular/angular/blob/cb2ca9a66ef54d9f1b3df5ac14962dc3810b4cc1/packages/router/src/operators/activate_routes.ts#L173

**Closed by atscott** 2021-07-08 19:04 UTC
Labels: comp: router

**Comment by bjdash** [comment] 2021-07-09 11:44
Thanks for confirming the expected behavior. This makes more sense now. Is this behavior documented anywhere? 

The only mention of null `DetachedRouteHandle` I could find in the [API spec](https://angular.io/api/router/RouteReuseStrategy) says `Storing a null value should erase the previously stored value` which doesn't explain the behavior clearly.

**Comment by atscott** [comment] 2021-07-09 16:25
@bjdash There's no official guide that I'm aware of that talks about `RouteReuseStrategy`. That note in the API spec would be the only mention of it.
