### ISSUE TITLE
(binding) style, ngStyle with !important is not applying

### ISSUE THREAD

**Issue by indraraj26** [angular/angular#36806] opened 2020-04-25 07:28 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package CommonModule 

### Is this a regression?

 Yes, the previous version in which this bug was not present was: no idea

### Description
Binding style with !important flag is not applying style even specificity is greater than class.
this will work -  style="color: 'red !important'"
```
<h1 class="header-text" [style.color]="'red !important'">Welcome to Angular World [Style binding]</h1>
<h1 class="header-text" [ngStyle]="{color: 'red !important'}">Welcome to Angular World
  [ngStyle binding]
</h1>
```

```
.header-text {
  color: slateblue !important;
}
```
## 🔬 Minimal Reproduction

https://ng-run.com/edit/7dAe6J7oYkyVG9rS5zOb

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

9.1.1
</code></pre>

**Anything else relevant?**

**Comment by JoostK** [comment] 2020-04-25 09:38
Duplicate of #12009.

**Closed by JoostK** 2020-04-25 09:38 UTC
