### ISSUE TITLE
[Router] relative routerLink broken for root route with empty path

### ISSUE THREAD

**Issue by dirkluijk** [angular/angular#32371] opened 2019-08-28 13:45 UTC
# 🐞 bug report

### Affected Package
This is caused by `@angular/router`.

### Is this a regression?

No. This bug was present in Angular 5, 6, 7 and 8.

### Description

Normally, a `RouterLink` directive should support relative router links. This works find, except when the current route is the root route and has an empty path.

## 🔬 Minimal Reproduction
See https://stackblitz.com/edit/relative-routing. The relative routerlinks in `ParentComponent` do not work as expected, but in `BarComponent`, they do.

## 🌍  Your Environment

**Angular Version:**
<pre><code>Angular CLI: 8.2.2
Node: 10.15.3
OS: win32 x64
Angular: 8.2.2
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.802.2
@angular-devkit/build-angular     0.802.2
@angular-devkit/build-optimizer   0.802.2
@angular-devkit/build-webpack     0.802.2
@angular-devkit/core              8.2.2
@angular-devkit/schematics        8.2.2
@angular/cdk                      8.1.3
@angular/flex-layout              8.0.0-beta.26
@angular/material                 8.1.3
@ngtools/webpack                  8.2.2
@schematics/angular               8.2.2
@schematics/update                0.802.2
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.38.0
</code></pre>

**Comment by dirkluijk** [comment] 2019-09-25 08:54
I already stumbled upon a second app which has this bug. I think it might happen quite common.
It would we nice of this gets priority. :wink:

**Comment by atscott** [comment] 2020-05-28 17:20
Duplicate of #13011

**Closed by atscott** 2020-05-28 17:20 UTC
Labels: comp: router, freq2: medium, severity2: inconvenient, triage #1, type: bug/fix
