### ISSUE TITLE
Control Flow Analysis in template

### ISSUE THREAD

**Issue by xiaoxiangmoe** [angular/angular#37840] opened 2020-06-30 08:50 UTC
# 🐞 bug report

### Description

 A clear and concise description of the problem...

## 🔬 Minimal Reproduction

```sh
ng new test-angular10 --strict 
cd test-angular10
# edit src/app/app.component.ts
ng build --prod
```

```ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  template: `
    <ng-container *ngIf="field.type === 'string'; else elseTemplate">
      {{ str(field.value) }}
    </ng-container>
    <ng-template #elseTemplate>
      {{ num(field.value) }}
    </ng-template>

    <span [ngSwitch]="field.type">
    <p *ngSwitchCase="'string'">
      {{ str(field.value) }}
    </p>
    <p *ngSwitchCase="'number'">
      {{ num(field.value) }}
    </p>
    <p *ngSwitchDefault>
      {{ never(field) }}
    </p>
    </span>
    `,
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  field:
  | {
    type: 'number',
    value: number,
  }
  | {
    type: 'string',
    value: string,
  } = {
    type: 'string',
    value: 'str',
  };

  str = (x: string) => {}
  num = (x: number) => {}
  never = (x: never) => {}
}
```

## 🔥 Exception or Error
<pre><code>ERROR in src/app/app.component.ts:10:14 - error TS2345: Argument of type 'string | number' is not assignable to parameter of type 'number'.
  Type 'string' is not assignable to type 'number'.

10       {{ num(field.value) }}
                ~~~~~~~~~~~
src/app/app.component.ts:15:14 - error TS2345: Argument of type 'string | number' is not assignable to parameter of type 'string'.
  Type 'number' is not assignable to type 'string'.

15       {{ str(field.value) }}
                ~~~~~~~~~~~
src/app/app.component.ts:18:14 - error TS2345: Argument of type 'string | number' is not assignable to parameter of type 'number'.
  Type 'string' is not assignable to type 'number'.

18       {{ num(field.value) }}
                ~~~~~~~~~~~
src/app/app.component.ts:21:16 - error TS2345: Argument of type '{ type: "number"; value: number; } | { type: "string"; value: string; }' is not assignable to parameter of type 'never'.
  Type '{ type: "number"; value: number; }' is not assignable to type 'never'.

21       {{ never(field) }}
                  ~~~~~
</code></pre>


## 🌍  Your Environment

**Angular Version:**
<pre><code>Angular CLI: 10.0.0
Node: 14.2.0
OS: darwin x64

Angular: 10.0.1
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.0
@angular-devkit/build-angular     0.1000.0
@angular-devkit/build-optimizer   0.1000.0
@angular-devkit/build-webpack     0.1000.0
@angular-devkit/core              10.0.0
@angular-devkit/schematics        10.0.0
@angular/cli                      10.0.0
@ngtools/webpack                  10.0.0
@schematics/angular               10.0.0
@schematics/update                0.1000.0
rxjs                              6.5.5
typescript                        3.9.5
webpack                           4.43.0
</code></pre>

**Anything else relevant?**
<!-- ✍️Is this a browser specific issue? If so, please specify the browser and version. -->

<!-- ✍️Do any of these matter: operating system, IDE, package manager, HTTP server, ...? If so, please mention it below. -->

**Comment by petebacondarwin** [comment] 2020-06-30 09:15
Here is the generated type-checking block:

```ts
import * as i2 from '@angular/common';
import * as i1 from '@angular/core';
import * as i0 from '../../../../../../../../Users/pete/dev/angular/tmp/test-angular10/src/app/app.component';

const _ctor1: <T = unknown>(init: Pick<i2.NgIf<T>, "ngIf" | "ngIfThen" | "ngIfElse">) => i2.NgIf<T> = (null!);

export function _tcb1(ctx: i0.AppComponent) {
  if (true) {
    var _t1 = _ctor1({
      "ngIf": ctx.field.type === "string",
      "ngIfElse": null as any as i1.TemplateRef<any>, "ngIfThen": (null as any)
    });
    
    var _t2: any = (null!);
    
    if (i2.NgIf.ngTemplateContextGuard(_t1, _t2) && ctx.field.type === "string") {
        var _t3 = document.createElement("ng-container");
        "" + ctx.str(ctx.field.value);
    }
    
    var _t4: any = (null!);
    {
        "" + ctx.num(ctx.field.value);
    }
  }
}
```

We can see that the:

```ts
{
  "" + ctx.num(ctx.field.value);
}
```

block is not guarded by an `else` block, so in this block the `ctx.field.value` can be either string or number.

**Comment by xiaoxiangmoe** [comment] 2020-06-30 13:43
Also, can we use [instanceof type guards](https://www.typescriptlang.org/docs/handbook/advanced-types.html#instanceof-type-guards) and [typeof type guards](https://www.typescriptlang.org/docs/handbook/advanced-types.html#typeof-type-guards) in Angular template?

**Comment by petebacondarwin** [comment] 2020-06-30 13:54
> Also, can we use [instanceof type guards](https://www.typescriptlang.org/docs/handbook/advanced-types.html#instanceof-type-guards) and [typeof type guards](https://www.typescriptlang.org/docs/handbook/advanced-types.html#typeof-type-guards) in Angular template?

Is that a question or a request? Certainly it is not possible right now to use these in templates.
I would also prefer to avoid doing so as well. For me templates should contain as little logic as possible.

**Comment by xiaoxiangmoe** [comment] 2020-06-30 14:20
@petebacondarwin This is a feature request. I created a new issue to discuss this matter.

**Comment by JoostK** [comment] 2020-06-30 18:49
These are well-known limitations and there's some issues already covering these: #34522, #20780 and #21504, so I'll close this as a duplicate of those issues.

**Closed by JoostK** 2020-06-30 18:49 UTC
Labels: comp: compiler, state: confirmed, type: bug/fix
