### ISSUE TITLE
(bug) routerLinkActiveOptions doesn't exactly match with route params

### ISSUE THREAD

**Issue by markusu49** [angular/angular#19399] opened 2017-09-26 11:04 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report (very similar to #11121)  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

setting routerLinkActiveOptions to {exact: true} only matches the routerLink value exactly without consideration of the optional (matrix URL) route parameters.

## Expected behavior

setting routerLinkActiveOptions to {exact: true} should match the path exactly, including route parameters (if listed).

## Minimal reproduction of the problem with instructions

take the repro at #11121 and use this for the links:

```<a [routerLink]="['/content', {page: number}]" routerLinkActive='active' [routerLinkActiveOptions]="{exact: true}">{{ number }}</a>```

## Environment

<pre><code>

@angular/cli: 1.5.0-beta.0
node: 8.5.0
os: linux x64
@angular/animations: 4.4.3
@angular/common: 4.4.3
@angular/compiler: 4.4.3
@angular/core: 4.4.3
@angular/forms: 4.4.3
@angular/http: 4.4.3
@angular/platform-browser: 4.4.3
@angular/platform-browser-dynamic: 4.4.3
@angular/router: 4.4.3
@angular/cli: 1.5.0-beta.0
@angular/compiler-cli: 4.4.3
@angular/language-service: 4.4.3
typescript: 2.3.4

**Comment by encool** [comment] 2017-10-16 03:04
I think i hava the same issue, Is there any progress on this?

**Comment by atscott** [comment] 2020-05-27 17:39
Duplicate of #20698

**Closed by atscott** 2020-05-27 17:39 UTC
Labels: comp: router, freq1: low, router: directives, severity3: broken, state: confirmed, triage #1, type: bug/fix
