### ISSUE TITLE
"date" pipe displays incorrect date

### ISSUE THREAD

**Issue by bangieff** [angular/angular#45746] opened 2022-04-25 02:58 UTC
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

No

### Description

I'm using the date pipe, in order to display a date in a human readable form as displayed below:
{{3344994000000 | date: 'dd MMM YYYY'}} 

Expected result: 31 Dec 2075
Actual result: "31 Dec 2076"
 
The expected result can be easily verified with the code below:

let convertedDate = new Date(3344994000000 );
console.log(convertedDate.toLocaleDateString());

Console output: 12/31/2075

Oddly, the pipe works fine for date 2556075600000 (31 Dec 2050)

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.0.4
Node: 16.13.1
Package Manager: npm 8.1.2
OS: win32 x64

Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1300.4 (cli-only)
@angular-devkit/core         13.0.4 (cli-only)
@angular-devkit/schematics   13.0.4 (cli-only)
@schematics/angular          13.0.4 (cli-only)
```

**Comment by destus90** [comment] 2022-04-25 03:37
duplicate of https://github.com/angular/angular/issues/44350

**Closed** 2022-04-25 06:10 UTC
