### ISSUE TITLE
ng-container with ngComponentOutlet does not render SVG fragment

### ISSUE THREAD

**Issue by Pho3nixHun** [angular/angular#46190] opened 2022-05-30 21:06 UTC
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

When using ng-container in combination with ngComponentOutlet the component does not show up, however when using it normally it does.

```ts
<svg>
    <ng-container
      *ngFor="let element of elements$ | async" [ngComponentOutlet]="element"
    > <!-- This does not gets rendered -->
    </ng-container>
    <circle app-svg-element></circle> <!-- This gets rendered -->
</svg>
````
In the DOM I see the element, but it does not get rendered.
![image](https://user-images.githubusercontent.com/4687621/171059532-d58fb17e-6f6d-4039-a6b6-03ab6462d970.png)

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-uepvbp?file=src/app/svg-host/svg-host.component.svg

### Please provide the exception or error you saw

```true
I did not see any error on console.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.2.0
Node: 16.10.0
Package Manager: npm 7.24.0
OS: linux x64

Angular: 13.2.0
```

### Anything else?

Might be a similar issue like https://github.com/crisbeto/angular/commit/08c1abc847d1c0f5886e290ec13543b5d8c679e4
https://github.com/angular/angular/issues/41308
https://github.com/angular/angular/pull/41669

**Comment by pkozlowski-opensource** [comment] 2022-06-22 08:49
This is essentially the same issue as #10404 - it boils down to the dynamically created components _not_ specifying the necessary SVG namespace. More detailed info in https://github.com/angular/angular/issues/10404#issuecomment-633889536

I'm going to close this as a duplicate of #10404 - it is definitively something that we should fix.

Duplicate of #10404

**Closed by pkozlowski-opensource** 2022-06-22 08:49 UTC
Labels: comp: core, core: dynamic view creation, cross-cutting: SVG, P4
