### ISSUE TITLE
Property setters should be smarter when using properties or attributes

### ISSUE THREAD

**Issue by matanlurey** [angular/angular#2870] opened 2015-07-03 23:03 UTC
Consider wanting to create a `<paper-button>` component that can use attributes *or* properties:

Attribute-based configuration:

```html
  <!-- Will always be disabled -->
  <paper-button disabled>Save</button>
```

Property-based configuration:

```html
  <!-- Will be conditionally disabled -->
  <paper-button [disabled]="isDisabled">Save</paper-button>
```

Good news is this works today. Bad news is that it requires a little non-intuitive massaging, and could be a lot cleaner for Angular component authors. 

For example, here's today's utility functions:

```dart
// Utility functions shared among component authors.
dynamic getDynamic(inputValue, {defaultValue, onString(String strValue)}) {
  if (inputValue == null) {
    return defaultValue;
  } else if (inputValue is String) {
    return onString(inputValue);
  } else {
    return inputValue;
  }
}

bool getBool(
    inputValue, {
    bool defaultValue: false,
    bool onString(String strValue)}) {
  if (inputValue is String && onString == null) {
    return _parseBool(inputValue, defaultValue);
  }
  return getDynamic(
      inputValue,
      defaultValue: defaultValue,
      onString: onString);
}
```

And the property setter itself:

```dart
// The component itself
bool _disabled = false;
void set disabled(value) {
  _disabled = getBool(value);
}
```

Proposal
---

Have an alternative/Angular framework assisted way of doing this. Maybe annotation-based:

```dart
@Attribute.onNull(false)
void set disabled(bool disabled) {
  _disabled = disabled;
}
```

I realize this could be done using pipes, but the following is needed:

1. Register a pipe that may or may not be used
2. Inject `PipeRegstry`
3. Create a transformer from the registry
4. Use the transformer on the property setter

This could be a lot cleaner/simpler, and is more natural with native/web components.

(Slightly related to #2869)

**Comment by pkozlowski-opensource** [comment] 2015-07-31 15:39
Bumped into this one today as well. It would be cool to make it slightly easier on component authors (don't have a great proposal, though...). 

BTW, this is exact duplicate of #1162: @matanlurey @jelbourn - maybe we should close this one or #1162 and centralize discussion in one place?

**Comment by jelbourn** [comment] 2015-07-31 16:05
The name of this issue is a bit off- for the example given, it's still the disabled _property_ on the DOM element that you want to set either way. 

I can close this one as a dupe of #1162 if @matanlurey wants to paste his issue text into it.

**Comment by mhevery** [comment] 2016-07-01 17:45
close this one as a dupe of #1162

**Closed by mhevery** 2016-07-01 17:45 UTC
Labels: comp: core/view/compiler, effort2: medium (day), hotlist: community-help, P4: nice to have, state: Needs Design, type: feature
