### ISSUE TITLE
Custom queryParams parsing and serialization

### ISSUE THREAD

**Issue by klemenoslaj** [angular/angular#40937] opened 2021-02-22 11:45 UTC
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/router

### Description

Provide a possibility to overwrite the default parsing and serialization of queryParams.
**Use case**: nested objects without using `JSON.stringify` or similar tricks.

Query params are of course not perfect to represent nested objects, however sometimes this is exactly what is required.

Solutions like [qs](https://github.com/ljharb/qs) can't be efficiently used with Angular router.

So, possibly use the UrlSerializer while creating url tree in the code above or provide a similar possibility to do the overwrite.

### Describe the solution you'd like

There is already `UrlSerializer` available, however it is not sufficient as the code bellow is still executed, preventing any custom serialization:

https://github.com/angular/angular/blob/572e3a356c487af1cd5b052d2e98e94f41395fe9/packages/router/src/create_url_tree.ts#L48-L64

### Describe alternatives you've considered

The only alternative I can think of is to do something like bellow, but that is not enough:

```ts
this._router.navigate(['...'], {
  queryParams: { __custom__: JSON.stringify(nestedParams) },
});
```

and

```ts
import { DefaultUrlSerializer, UrlSerializer, UrlTree } from '@angular/router';

const defaultSerializer = new DefaultUrlSerializer();

export class CustomUrlSerializer implements UrlSerializer {
  ...

  serialize(tree: UrlTree) {
    const { queryParams } = tree;

    const serialized = defaultSerializer.serialize(tree);

    if (queryParams.__custom__) {
      const [base] = serialized.split('?');

      return base + '?' + customSerializer(JSON.parse(queryParams.__custom__));
    }

    return serialized;
  }
}

```

**Comment by atscott** [comment] 2021-02-23 17:36
Duplicate of #38706

**Closed by atscott** 2021-02-23 17:36 UTC
