### ISSUE TITLE
Unnecessary white spaces inside tag (at the beginning and in the end of text)

### ISSUE THREAD

**Issue by Y4Rick** [angular/angular#57871] opened 2024-09-18 16:29 UTC
### Which @angular/* package(s) are the source of the bug?

compiler-cli, compiler

### Is this a regression?

No

### Description

I would appreciate an explanation of the situation.

If it works as expected, please explain why that is the case?
If there is a problem, please pay attention to it!

In some cases of writing text in tags, after compilation, spaces are added at the beginning and end of the text, which were not there initially.
![Снимок экрана 2024-09-18 в 18 14 27](https://github.com/user-attachments/assets/2914566a-15f5-4aad-a133-67cea8c439e8)
![Снимок экрана 2024-09-18 в 18 21 26](https://github.com/user-attachments/assets/007b1f31-3e65-46c1-917d-97a76fe23f06)

It seems like a line break is being converted into a space.

However, if the same text is output through interpolation without a line break, there are no extra spaces.
![Снимок экрана 2024-09-18 в 18 24 55](https://github.com/user-attachments/assets/29681f4f-27a3-4f12-aba5-88eee19bb001)
![Снимок экрана 2024-09-18 в 18 25 03](https://github.com/user-attachments/assets/b259333e-bad3-4318-b69f-6048bfaddbde)

The same thing will happen even if the text is output through interpolation with a line break - as a result, there are spaces.
![Снимок экрана 2024-09-18 в 18 35 26](https://github.com/user-attachments/assets/9d01dbce-08b9-4734-bc26-cf7ea378c81c)
![Снимок экрана 2024-09-18 в 18 37 00](https://github.com/user-attachments/assets/70b40404-9ca9-4192-996f-7c392687fbfc)

The most interesting part is that this happens at the compilation (or build) stage because you can verify it in the resulting code.
![Снимок экрана 2024-09-18 в 19 02 32](https://github.com/user-attachments/assets/35485de4-1313-4f01-b2ab-a02ad752ca3c)(text inside tag with the line break)
![Снимок экрана 2024-09-18 в 19 08 32](https://github.com/user-attachments/assets/58ef7b17-de46-4793-a06a-4ece31531a0a)(text through interpolation with a line break)
![Снимок экрана 2024-09-18 в 19 10 55](https://github.com/user-attachments/assets/697008e2-2c3b-4ec6-a899-da587da9a4c2)(build)

So, my questions are: 

- Is it possible to control this? 
- Can I instruct the compiler not to add these spaces? 
- Is there a setting for this in an Angular project? 
- Is it possible to create your own webpack.config to manage this?

I would appreciate any answers...

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-bewrw3?file=package.json

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.3.8
Node: 22.5.1 (Unsupported)
Package Manager: npm 10.8.2
OS: darwin arm64

Angular: 17.3.11
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1703.8 (cli-only)
@angular-devkit/build-angular   17.3.8
@angular-devkit/core            17.3.8 (cli-only)
@angular-devkit/schematics      17.3.8
@angular/cdk                    17.3.10
@angular/cli                    17.3.8
@angular/material               17.3.10
@angular/ssr                    17.3.8
@angular/youtube-player         17.3.10
@schematics/angular             17.3.8
rxjs                            7.8.1
typescript                      5.4.5
zone.js                         0.14.7
```

**Comment by JoostK** [comment] 2024-09-18 17:23
Also see https://github.com/angular/angular/issues/37635

**Comment by alxhub** [comment] 2024-09-18 17:27
(closing as a duplicate of that one)

**Closed by alxhub** 2024-09-18 17:27 UTC
