### ISSUE TITLE
Custom directive inheritance problem

### ISSUE THREAD

**Issue by madks13** [angular/angular#30760] opened 2019-05-31 01:06 UTC
# 🐞 bug report

### Affected Package

Packages :

 "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~7.2.0",
    "@angular/common": "~7.2.0",
    "@angular/compiler": "~7.2.0",
    "@angular/core": "~7.2.0",
    "@angular/forms": "~7.2.0",
    "@angular/platform-browser": "~7.2.0",
    "@angular/platform-browser-dynamic": "~7.2.0",
    "@angular/router": "~7.2.0",
    "@ng-bootstrap/ng-bootstrap": "^4.1.3",
    "angular-font-awesome": "^3.1.2",
    "core-js": "^2.5.4",
    "font-awesome": "^4.7.0",
    "rxjs": "~6.3.3",
    "tslib": "^1.9.0",
    "zone.js": "~0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.13.0",
    "@angular/cli": "~7.3.8",
    "@angular/compiler-cli": "~7.2.0",
    "@angular/language-service": "~7.2.0",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "bootstrap": "^4.3.1",
    "codelyzer": "~4.5.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "jquery": "^3.4.1",
    "karma": "~4.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "ng-multiselect-dropdown": "^0.2.3",
    "ngx-toastr": "^10.0.4",
    "popper": "^1.0.1",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "~3.2.2"
  }

### Is this a regression?

Unknown.

### Description

A custom directive (attribute) is unknown in submodule when declared in root module.
I have a global directive with "appGlobal" selector. If i declare it in root module only, i get the following error :
 - "Can't bind to 'appGlobal' since it isn't a known property of 'span'. ("  <a class="btn btn-primary" routerLink="/admin/dashboard"><span [ERROR ->][appGlobal]="'Menu_Admin_Dashboard'">Dashboard</span></a>
  <a class="btn btn-primary" routerLink="/a"): ng:///AdministrationModule/AdminComponent.html@0:65
.
.
.
ng:///AdministrationModule/AdminComponent.html@2:61"

But, if i declare it in the admin submodule, i get the obvious following error :
 - "0: Type GlobalDirective is part of the declarations of 2 modules: AdministrationModule and AppModule! Please consider moving GlobalDirective to a higher module that imports AdministrationModule and AppModule. You can also create a new NgModule that exports and includes GlobalDirective then import that NgModule in AdministrationModule and AppModule."

## 🔬 Minimal Reproduction

As explained in the description. Also too busy to take time to make a reproduction, sorry.

## 🔥 Exception or Error
<pre><code>
0: Type GlobalDirective is part of the declarations of 2 modules: AdministrationModule and AppModule! Please consider moving GlobalDirective to a higher module that imports AdministrationModule and AppModule. You can also create a new NgModule that exports and includes GlobalDirective then import that NgModule in AdministrationModule and AppModule.
</code></pre>

<pre><code>
0: Template parse errors:
Can't bind to 'appGlobal' since it isn't a known property of 'span'. ("  <a class="btn btn-primary" routerLink="/admin/dashboard"><span [ERROR ->][appGlobal]="'Menu_Admin_Dashboard'">Dashboard</span></a>
  <a class="btn btn-primary" routerLink="/a"): ng:///AdministrationModule/AdminComponent.html@0:65
Can't bind to 'appGlobal' since it isn't a known property of 'span'. ("Admin_Dashboard'">Dashboard</span></a>
  <a class="btn btn-primary" routerLink="/admin/users"><span [ERROR ->][appGlobal]="'Menu_Admin_Users'">Users</span></a>
  <a class="btn btn-primary" routerLink="/admin/rol"): ng:///AdministrationModule/AdminComponent.html@1:61
Can't bind to 'appGlobal' since it isn't a known property of 'span'. ("="'Menu_Admin_Users'">Users</span></a>
  <a class="btn btn-primary" routerLink="/admin/roles"><span [ERROR ->][appGlobal]="'Menu_Admin_Roles'">Roles</span></a>

  <div class="container">
"): ng:///AdministrationModule/AdminComponent.html@2:61
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 7.3.9
Node: 11.2.0
OS: win32 x64
Angular: 7.2.15
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.9
@angular-devkit/build-angular     0.13.9
@angular-devkit/build-optimizer   0.13.9
@angular-devkit/build-webpack     0.13.9
@angular-devkit/core              7.3.9
@angular-devkit/schematics        7.3.9
@angular/cli                      7.3.9
@ngtools/webpack                  7.3.9
@schematics/angular               7.3.9
@schematics/update                0.13.9
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.29.0
</code></pre>

**Anything else relevant?**
Using Visual Studio Code 1.34.0 (latest version at the moment)

**Comment by Airblader** [comment] 2019-05-31 11:22
You have a module which doesn't know that this directive exists, so of course you get an error. You need to create a shared module in which you create the directive and then import the shared module in your root and submodule.

**Comment by madks13** [comment] 2019-06-01 01:04
Thanks, but i think i made it clear that i already knew that. What i'm saying is that, as the error message states, it should propagate the knowledge of the directive to all submodules instead of forcing me to make a useless shared module only for this case.

**Comment by Airblader** [comment] 2019-06-01 06:22
For the compiler this would be really awkward: it would no longer be possible to tell the user that they forgot to import a module as it's unclear whether the directive is declared "somewhere higher up".

For components this of course breaks down entirely as you would introduce ambiguous situations. 

In total this problem will go away anyway as modules become less and less necessary. AFAIK there are plans to support providedIn not just for injectables, and with that you could just declare your directive that way without a need to declare it in any module.

**Comment by Airblader** [comment] 2019-06-01 06:30
Also I'm not sure how this would play with lazy loading: what if the child module is loaded without the root module? You'd now have a broken module which doesn't know which module needs to be loaded to have the directive.

**Comment by madks13** [comment] 2019-06-03 14:28
Well, i understand what you are saying, but what i'm saying is that the error indicates that it is possible to declare the directive higher up so sub-modules can automatically import it. Which to me means that the error about the sub-module not knowing about the directive indicates a bug.

**Comment by alxhub** [comment] 2019-06-04 22:38
As far as _semantics_ goes, this is working as intended. Either you need to create a module which exports the directive, or declare the directive somewhere existing which is imported in both places. In that sense, I think even the error message is reasonable. 

I think your mental model of how NgModules work is slightly backwards (which is not surprising - they're complicated!). You talk about the root module and sub-modules, but the relationship there is that the root module _depends on_ the sub-modules. The sub modules are already compiled/finalized before the root module is considered. The first error, then, is because your sub-module knows nothing about this directive when it's being compiled.

One thing I think _would_ be reasonable to do is to recognize that the directive is missing from the sub-module, just like we recognize that there are competing declarations of the directive itself within the same compilation unit. This is feasible, and maybe in the future we'll build that intelligence into the compiler. But for now, this issue isn't really actionable as the errors are working as intended, so I'm going to close it.

**Closed by alxhub** 2019-06-04 22:38 UTC
Labels: comp: core & compiler

**Comment by madks13** [comment] 2019-06-05 07:15
Fair enough. I'll take the 3rd module solution then.
