### ISSUE TITLE
`formGroup.valid` and `formGroup.statusChanges` don't have the same value when working with ControlValueAccessor

### ISSUE THREAD

**Issue by StefanKern** [angular/angular#30475] opened 2019-05-15 10:14 UTC
# 🐞 bug report

### Affected Package
"@angular/forms": "5.0.0" upwards (also tested in 7.0.0)

### Description
Create a component which implements `ControlValueAccessor` and define some reactive validation properties. Then use this component inside another form with reactive from elements. Then check the validation of the components via fromgroup.valid and subscribing to `formGroup.statusChange`.

You get the following results:

- child component (implementing ControlValueAccessor)
  - formGroup.valid is "false"
  - statusChanges is: "INVALID"
- parent component 
  - formGroup.valid is "false"
  - statusChanges is: "VALID" <-- should be invalid 

When you change the inputs, the values get in sync.

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/textbox-component-with-controlvalueaccessor-wjcj7u

**Comment by StefanKern** [comment] 2019-05-15 13:03
Maybe linked to https://github.com/angular/angular/issues/6170 ,

**Comment by StefanKern** [comment] 2019-05-15 13:20
Update 2: wrapping `this.formGroup.updateValueAndValidity()` with a `setTimeout` did the trick.

https://stackblitz.com/edit/textbox-component-with-controlvalueaccessor-eisxvb?file=app/app.component.ts

Full code:

``` TS
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup } from '@angular/forms';

@Component({
  selector: 'app-textbox-demo',
  templateUrl: './textbox-demo.component.html',
  styleUrls: ['./textbox-demo.component.css']
})
export class TextboxDemoComponent implements OnInit {
  public formGroup: FormGroup;
  public subscribedValidity = "Unknwon"

  constructor(private formBuilder: FormBuilder) {
    this.formGroup = formBuilder.group({
      textboxmodule: {
        textbox: null
      }
    });
  }

  ngOnInit() {
    this.formGroup.statusChanges.subscribe((val) => {
      this.subscribedValidity = val;
    });
    (setTimeout(_ => this.formGroup.updateValueAndValidity()));
  }
}
```

``` HTML
<form [formGroup]="formGroup">
  <textbox formControlName="textboxmodule"></textbox>

  <h2>Textbox Demo Validity</h2>
  <code>formGroup.valid is "{{formGroup.valid}}"</code><br>
  <code>statusChanges is: "{{subscribedValidity}}"</code> <b> --> WRONG!!</b>
</form>
```

``` TS
import { Component, Input, forwardRef } from '@angular/core';
import { AbstractControl, ControlValueAccessor, FormControl, FormGroup, NG_VALIDATORS, NG_VALUE_ACCESSOR, ValidationErrors, Validators } from '@angular/forms';

@Component({
  selector: 'textbox',
  templateUrl: './textbox.component.html',
  providers: [
    {
      provide: NG_VALUE_ACCESSOR,
      useExisting: forwardRef(() => TextboxComponent),
      multi: true
    },

    { provide: NG_VALIDATORS, useExisting: forwardRef(() => TextboxComponent), multi: true }
  ]
})
// Class definition for Textbox Component
export class TextboxComponent implements ControlValueAccessor {
  public formGroup: FormGroup;
  public subscribedValidity = "Unknwon"

  constructor() {
    this.formGroup = new FormGroup({
      textbox: new FormControl('', [Validators.required, Validators.maxLength(30)])
    });
    this.formGroup.statusChanges.subscribe((val) => {
      this.subscribedValidity = val;
    });
    this.formGroup.updateValueAndValidity();
  }

  public onTouched: () => void = () => {
  };

  writeValue(val: { quantity?: number, amount?: number, phoneCountryCode?: number, msisdn?: string }): void {
    val && this.formGroup.patchValue(val, { emitEvent: false });
  }

  registerOnChange(fn: any): void {
    this.formGroup.valueChanges.subscribe(fn);
  }

  registerOnTouched(fn: any): void {
    this.onTouched = fn;
  }

  setDisabledState?(isDisabled: boolean): void {
    isDisabled ? this.formGroup.disable() : this.formGroup.enable();
  }

  validate(c: AbstractControl): ValidationErrors | null {
    const test = this.formGroup.valid ? null : { invalidForm: { valid: false, message: 'formGroup fields are invalid' } };
    console.log('validate', test);
    return test;
  }
}
```

``` HTML
<ng-container [formGroup]="formGroup">
          <input type="text" placeholder="textbox"
                formControlName="textbox">
  <br>
  <h2>Textbox Module Validity</h2>
  <code>formGroup.valid is "{{formGroup.valid}}"</code><br>
  <code>statusChanges is: "{{subscribedValidity}}"</code>
</ng-container>
```

**Comment by kara** [comment] 2019-05-16 23:12
@StefanKern The reason that you're getting `VALID` with the status changes observable is due to the fact that you're calling `updateValueAndValidity` before the template has been processed.  When you create your `FormGroup` with `FormBuilder`, you're implicitly creating a `FormControl` with no validators, like this:

```
this.formGroup =  new FormGroup({
      'textboxmodule': new FormControl(null)
});
```

So when you manually update directly after, the status will emit as `VALID` because there are no validators to mark it invalid. 

When the template is processed later, your custom form control will initialize and set its parent group's validity to false. That's why if you print the validity in the template, it is correct and takes the custom form control into account.

This seems to be working as intended, so I'm closing the issue. If there's more information about your use case that isn't resolved by the existing APIs, please create an issue with a bit more information about why you need statusChanges at that time in the lifecycle.

**Closed by kara** 2019-05-16 23:12 UTC
Labels: comp: forms

**Comment by StefanKern** [comment] 2019-05-17 12:36
@kara thanks for taking a look.
What is the best way to split a FormGroup into multiple parts, and each part takes care of it's own validators? Is this possible with reactive forms or template driven forms?
