### ISSUE TITLE
Strange behaviour with multiple <ng-content> and *ngIf

### ISSUE THREAD

**Issue by stephanecot** [angular/angular#22972] opened 2018-03-24 08:41 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
I have a component with 2 zones and in theses zones I have a<ng-content> tags. Theses zones are shown with some *ngIf.
My problem is that second `<ng-content></ng-content>` is not working. It's "blocked" by the first `<ng-content></ng-content>` despite the first one is in a *ngIf with false expression.

## Expected behavior
The `<ng-content></ng-content>`  seems to be used before the *ngIf test. It should be used after.
I don't want to duplicate the view, I only want to put it where I want with an if test.

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-zbmzhx

EDIT:
-I dont't want to duplicate the content
- I know the content is evaluated before doing the `<ng-content></ng-content>`  inclusion.

my child components are evalluated before the parent one ==> OK
But, the child components must be put in the right place ==> KO

My problem is `<ng-content></ng-content>`  (I think) is evaluated twice, but the first one has an if.
## Environment

<pre><code>
Angular version: 5.2.x

Browser:
- [x] Chrome (desktop) version 65
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 9
- Platform:  Windows 10 64bits

Others:

</code></pre>

**Comment by trotyl** [comment] 2018-03-24 08:44
Duplicate of #13894

**Comment by stephanecot** [comment] 2018-03-24 09:08
I had a difference, I used a *ngIf, I don't duplicate it

**Comment by trotyl** [comment] 2018-03-24 09:24
OK, duplicate of https://github.com/angular/angular/issues/13760 and https://github.com/angular/angular/issues/13921

The problem is <ng-content> is not designed to work with structural directive, no matter what kind of structural directive (duplicate or not).

**Comment by stephanecot** [comment] 2018-03-24 09:29
No not duplicate of theses two cases !!
In your exemple cases, they say that the child components is evaluated even if there is an upper if.
That's not exactly my case.
I want my child to be evaluated before ==> OK
But, there are not placed in the right place ! The content must be in the second ng-content tag, not the first one.

**Comment by mlc-mlapis** [comment] 2018-03-24 09:32
@stephanecot ... you have to respect uniqueness of selection patter for `<ng-content>` on the same template ... it means that there doesn't have to be duplicity of the `<ng-content>` select inside the same template. It is by the **design**.

So you can use just one `<ng-content>`  without any select or more `<ng-content>` but each of them has to have a different `select` which selects unique (different part) of the parent's content.

In your case you have duplicity in `<ng-content select="app-child"></ng-content>` and it doesn't matter that you differentiate them by `*ngIf`.

There are some plans (even some PRs) which should change the design to have more flexible possibilities but all them are aimed after new Ivy view engine will be ready.

**Comment by stephanecot** [comment] 2018-03-24 09:34
Ok !!! It's was the answer I was waiting...

**Closed** 2018-03-24 09:37 UTC

**Comment by bryanrideshark** [comment] 2018-11-01 15:54
@nelisbijl , thanks a million.

**Comment by petrovichm** [comment] 2019-02-07 11:02
> Put the ng-content inside an ng-template and render that template inside your ngIf.
> something like :
> 
> ```
> <ng-template #content><ng-content></ng-content></ng-template>
> <div *ngIf="flag">
>           <ng-container *ngTemplateOutlet="content"></ng-container>
> </div>
> <div *ngIf="!flag">
>           <ng-container *ngTemplateOutlet="content"></ng-container>
> </div>
> ```
> still can not have the contents twice, but that's not what you want/need

Just want to extend this answer. 
If you don't want to have extra `div` element for `*ngIf` in the DOM, just put ternary in `*ngTemplateOutlet`:

```
<ng-template #content><ng-content></ng-content></ng-template>
<ng-container *ngTemplateOutlet="flag ? content : null"></ng-container>
<ng-container *ngTemplateOutlet="!flag ? content : null"></ng-container>
```

Sorry for late answer, just figured that this is a good alternative in other cases.

**Comment by georgechond94** [comment] 2019-03-29 14:32
> > Put the ng-content inside an ng-template and render that template inside your ngIf.
> > something like :
> > ```
> > <ng-template #content><ng-content></ng-content></ng-template>
> > <div *ngIf="flag">
> >           <ng-container *ngTemplateOutlet="content"></ng-container>
> > </div>
> > <div *ngIf="!flag">
> >           <ng-container *ngTemplateOutlet="content"></ng-container>
> > </div>
> > ```
> > still can not have the contents twice, but that's not what you want/need
> 
> Just want to extend this answer.
> If you don't want to have extra `div` element for `*ngIf` in the DOM, just put ternary in `*ngTemplateOutlet`:
> 
> ```
> <ng-template #content><ng-content></ng-content></ng-template>
> <ng-container *ngTemplateOutlet="flag ? content : null"></ng-container>
> <ng-container *ngTemplateOutlet="!flag ? content : null"></ng-container>
> ```
> Sorry for late answer, just figured that this is a good alternative in other cases.

And to extend this answer you could also:

`<ng-template [ngIf]="flag"><ng-content></ng-content></ng-template>
 `

**Comment by tamazyanarsen** [comment] 2020-10-26 13:13
> > > Put the ng-content inside an ng-template and render that template inside your ngIf.
> > > something like :
> > > ```
> > > <ng-template #content><ng-content></ng-content></ng-template>
> > > <div *ngIf="flag">
> > >           <ng-container *ngTemplateOutlet="content"></ng-container>
> > > </div>
> > > <div *ngIf="!flag">
> > >           <ng-container *ngTemplateOutlet="content"></ng-container>
> > > </div>
> > > ```
> > > 
> > > 
> > > still can not have the contents twice, but that's not what you want/need
> > 
> > 
> > Just want to extend this answer.
> > If you don't want to have extra `div` element for `*ngIf` in the DOM, just put ternary in `*ngTemplateOutlet`:
> > ```
> > <ng-template #content><ng-content></ng-content></ng-template>
> > <ng-container *ngTemplateOutlet="flag ? content : null"></ng-container>
> > <ng-container *ngTemplateOutlet="!flag ? content : null"></ng-container>
> > ```
> > 
> > 
> > Sorry for late answer, just figured that this is a good alternative in other cases.
> 
> And to extend this answer you could also:
> 
> ```
> <ng-template [ngIf]="flag"><ng-content></ng-content></ng-template>
> <ng-template [ngIf]="!flag"><ng-content></ng-content></ng-template>
> ```

does not work this example
