### ISSUE TITLE
Lifcycles hooks not firing when navigated to child component via router.navigate method.

### ISSUE THREAD

**Issue by tdinar** [angular/angular#18339] opened 2017-07-26 02:40 UTC
I am experiencing an issue with Angular 2.40 and router navigation when I use the router.navigate(/root/child) method. I am using webpack for packaging my app based on the tutorial [https://angular.io/guide/webpack.]. my setup is utilizing modules and modules routing to get to children's component (this is not an issue when links are used to navigate).

the issue in detail

The data arriving from source (a promise) is flowing to children through a store's BehaviouralSubjects. through the AuthGuards for children, I can see the data arriving inside the AuthGuards, and it is as I expect. however, my subscription inside a child component, which is placed inside ngAfterContentChecked will not fire, or more precisely, all lifecycle hooks, except constructor, are not firing. if I place the subscription inside the constructor of a child, it fires but the componen's change detection misses the subscription and any data-flow at all. If I manually run the CD inside a constructor and within the subscription, I get an error, that the component properties do not exist on a null!.

## Expected behavior

I expect lifecycle events to fire any time a component is instantiated.
## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by zoechi** [comment] 2017-07-26 10:49
Any specific reason why you don't update to Angular 4?
AFAIR there were issues with lifecycle calls in combination with router which were fixed since then.

The issue also needs a Plunker that reproduces the issue.

**Comment by tdinar** [comment] 2017-07-26 15:00
thank you for the reply. I tried this settings:
`{
  "name": "myproject",
  "version": "1.0.0",
  "private": true,
  "description": "myproject",
  "scripts": {
    "test:once": "karma start karma.conf.js --single-run",
    "build": "rimraf dist && webpack --config config/webpack.prod.js --bail",
    "serve": "lite-server -c=bs-config.json",
    "prestart": "npm run build",
    "start": "webpack-dev-server --inline --progress --port 8080",
    "pretest": "npm run build",
    "test": "karma start karma.webpack.conf.js",
    "pretest:once": "npm run build",
    "build:watch": "tsc -p src/ -w",
    "build:upgrade": "tsc",
    "serve:upgrade": "http-server",
    "build:aot": "ngc -p tsconfig-aot.json && rollup -c rollup-config.js",
    "serve:aot": "lite-server -c bs-config.aot.json",
    "build:babel": "babel src -d src --extensions \".es6\" --source-maps",
    "copy-dist-files": "node ./copy-dist-files.js",
    "i18n": "ng-xi18n",
    "lint": "tslint ./src/**/*.ts -t verbose",
    "ng": "ng",
    "e2e": "ng e2e"
  },
  "keywords": [],
  "author": "",
  "license": "MIT",
  "dependencies": {
    "@angular/animations": "4.2.0",
    "@angular/common": "4.2.0",
    "@angular/compiler": "4.2.0",
    "@angular/compiler-cli": "4.2.0",
    "@angular/core": "4.2.0",
    "@angular/forms": "4.2.0",
    "@angular/http": "4.2.0",
    "@angular/platform-browser": "4.2.0",
    "@angular/platform-browser-dynamic": "4.2.0",
    "@angular/platform-server": "4.2.0",
    "@angular/router": "4.2.0",
    "@angular/tsc-wrapped": "4.2.0",
    "@angular/upgrade": "4.2.0",
    "angular-in-memory-web-api": "0.3.2",
    "angularfire2": "4.0.0-rc.1",
    "core-js": "2.4.1",
    "firebase": "^4.0.0",
    "rxjs": "5.0.1",
    "systemjs": "0.19.39",
    "zone.js": "0.8.4"
  },
  "devDependencies": {
    "@types/angular": "1.5.16",
    "@types/angular-animate": "1.5.5",
    "@types/angular-cookies": "1.4.2",
    "@types/angular-mocks": "1.5.5",
    "@types/angular-resource": "1.5.6",
    "@types/angular-route": "1.3.2",
    "@types/angular-sanitize": "1.3.3",
    "@types/jasmine": "2.5.36",
    "@types/node": "6.0.45",
    "babel-cli": "6.16.0",
    "babel-preset-angular2": "0.0.2",
    "babel-preset-es2015": "6.16.0",
    "canonical-path": "0.0.2",
    "concurrently": "3.0.0",
    "http-server": "0.9.0",
    "jasmine": "2.4.1",
    "jasmine-core": "2.4.1",
    "karma": "1.3.0",
    "karma-chrome-launcher": "2.0.0",
    "karma-cli": "1.0.1",
    "karma-jasmine": "1.0.2",
    "karma-jasmine-html-reporter": "0.2.2",
    "karma-phantomjs-launcher": "1.0.2",
    "lite-server": "2.2.2",
    "lodash": "4.16.2",
    "phantomjs-prebuilt": "2.1.7",
    "protractor": "5.1.0",
    "rollup": "0.41.6",
    "rollup-plugin-commonjs": "8.0.2",
    "rollup-plugin-node-resolve": "2.0.0",
    "rollup-plugin-uglify": "1.0.1",
    "source-map-explorer": "1.3.2",
    "tslint": "3.15.1",
    "typescript": "2.3.2",
    "@angular/cli": "1.0.0",
    "ts-node": "1.3.0",
    "angular2-template-loader": "0.6.0",
    "awesome-typescript-loader": "3.0.4",
    "css-loader": "0.26.1",
    "extract-text-webpack-plugin": "2.0.0-beta.5",
    "file-loader": "0.9.0",
    "html-loader": "0.4.3",
    "html-webpack-plugin": "2.16.1",
    "karma-sourcemap-loader": "0.3.7",
    "karma-webpack": "2.0.1",
    "null-loader": "0.1.1",
    "rimraf": "2.5.4",
    "raw-loader": "0.5.1",
    "style-loader": "0.13.1",
    "webpack": "2.2.1",
    "webpack-dev-server": "2.4.1",
    "webpack-merge": "3.0.0"
  },
  "repository": {}
}
`

still not working. l am working with firebase and I am not sure how to produce a plunker with fb. I am working on it though. thanks.

**Comment by mhevery** [comment] 2017-07-26 22:05
Thank you for submitting the issue. All issues require a [plunker](https://plnkr.co/) which demonstrates the problem and how to reproduce it. Please re-open the issue or create a new issue once you have a reproducible use case.

We are sorry that we are so aggressive on closing the issues. We are overwhelmed with the number of issues we get, and so we only have time to look at the ones which are easy for us to reproduce.

**Comment by jasonaden** [comment] 2017-12-07 22:14
Closing based on above.

**Closed by jasonaden** 2017-12-07 22:14 UTC
Labels: comp: router
