### ISSUE TITLE
NgOptimizedImage width returning undefined with custom loader if width | height => 1000

### ISSUE THREAD

**Issue by Codethier** [angular/angular#49768] opened 2023-04-10 18:23 UTC
### Which @angular/* package(s) are the source of the bug?

common, Don't known / other

### Is this a regression?

Yes

### Description

I had a custom IMAGE_LOADER that was working in v 15.0.0 (90% sure) , I upgraded to  15.2.6 and the following image loader returns undefined in the image path if width or height is set above 999 example.

### Please provide the exception or error you saw

```true
http://localhost:3000/admin/files/formatME/undefined/2023-januar-2/polo-sarga-szoknyaval-copy-c-20272-qxecnwwcfbr.webp
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.2.5
Node: 16.18.0
Package Manager: npm 8.19.2
OS: win32 x64

Angular: 15.2.6
... animations, cdk, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1502.5
@angular-devkit/build-angular   15.2.5
@angular-devkit/core            15.2.5
@angular-devkit/schematics      15.2.5
@angular/cli                    15.2.5
@schematics/angular             15.2.5
rxjs                            6.6.7
typescript                      4.8.4
```

### Anything else?

```
        <img class="ng-img" ngSrc="{{someSource}}" width="2604" height="4624" sizes="(max-width: 820px) 10vw, 5vw">
```
```
  provide: IMAGE_LOADER,
      useValue: (config: ImageLoaderConfig) => {
        if (environment.production) {
          return `${environment.domain}admin/files/formatME/${config.width}${config.src}`
        } else {
          return `${environment.domain}admin/files/formatME/${config.width}${config.src}`;
```

but

` <img class="ng-img" ngSrc="{{someSource}}" width="999" height="999" sizes="(max-width: 820px) 10vw, 5vw">`

returns correct path and the image loads.

I have tried the v14 backport, didn't work either sadly I did not have my deps pined in git so I can't tell the exact version where it worked properly, I am pretty sure it was v15.0.0. however.

**Comment by AndrewKushnir** [comment] 2023-04-10 19:17
@Codethier thanks for reporting the issue. Do you see any errors/warning in a console when running an app in dev mode?

// cc @atcastle

**Comment by AndrewKushnir** [comment] 2023-04-10 19:21
Looking at the code, there is a check to make sure that the image used in the app is not oversized (refers to 1000px):

https://github.com/angular/angular/blob/41b7ec4eb92361ec8f0a09d1d3db053c3890cc32/packages/common/src/directives/ng_optimized_image/ng_optimized_image.ts#L71-L76

and it's later used here:

https://github.com/angular/angular/blob/41b7ec4eb92361ec8f0a09d1d3db053c3890cc32/packages/common/src/directives/ng_optimized_image/ng_optimized_image.ts#L842-L859

but in this scenario you should see a warning in a console.

**Comment by Codethier** [comment] 2023-04-10 19:27
No, nothing related

**Comment by atcastle** [comment] 2023-04-10 20:39
@AndrewKushnir @Codethier This has been how the NgOptimizedImage directive has behaved since the beginning, as far as I know. The width is passed into the loader for srcset images, and not for the main image src. This is because even for fixed-size images, you want the requested image width to be based on the device's DPI multiplier, which is handled by the srcset. 

This could definitely be a little more clear in the docs. I'll make an edit to the section about custom loaders.

**Comment by Codethier** [comment] 2023-04-10 21:02
The problem is that 3 digits in width | height make it throw undefined while it used to take 4 digits and work.

Regarding what  their values are, by intrinsic image size the docs kind of read like the size of the source image. I am really confused now however,  does this mean that in a custom loader these 2 values are basicly only used for aspect ratio calculation?

**Comment by JuliaEichler** [comment] 2023-09-20 10:47
This issue still exists. If I provide width and height for a responsive image, config.width is undefined. If I remove the width and height attribute and set the image to fill, config.width is defined. Any updates on this?

**Comment by AndrewKushnir** [comment] 2023-10-05 01:47
@JuliaEichler could you please provide a minimal repro using [Stackblitz](https://stackblitz.com/), so that we can take a look?

**Comment by alxhub** [comment] 2023-12-14 01:21
Closing as no reproduction was provided, so we can't make further progress on this issue. Feel free to reopen the issue with a reproduction.

**Closed by alxhub** 2023-12-14 01:21 UTC
Labels: area: common, needs reproduction, common: image directive
