### ISSUE TITLE
"No provider" error message should describe the dependency hierarchy

### ISSUE THREAD

**Issue by pcroc** [angular/angular#25959] opened 2018-09-14 08:00 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ x ] Suggestion for improvement
</code></pre>

## Current behavior
1. Create a service that has a dependency (e.g. HttpClient):

```typescript
@Injectable({ providedIn: 'root' })
export class MyService {
  constructor(private httpClient: HttpClient) { }
  public doSomething(): any {
    return this.httpClient.get('/something');
  }
}
```

2. Create a component that uses that service:

```typescript
export class MyComponent implements OnInit {
  constructor(private myService: MyService) { }
  ngOnInit() {
    this.myService.doSomething();
  }
}
```

3. Run test for the component, forgetting to provide the service

Output:
```
HeadlessChrome 0.0.0 (Linux 0.0.0) MyComponent should create FAILED
	Error: StaticInjectorError(DynamicTestModule)[HttpClient]: 
	  StaticInjectorError(Platform: core)[HttpClient]: 
	    NullInjectorError: No provider for HttpClient!
```

## Expected behavior
The test failure message should provide some indication that it is is MyService that could not been provided to MyComponent, due to the transitive dependency.

For example:
```
HeadlessChrome 0.0.0 (Linux 0.0.0) MyComponent should create FAILED
	Error: StaticInjectorError(DynamicTestModule)[HttpClient]: 
	  StaticInjectorError(Platform: core)[HttpClient]: 
	    NullInjectorError: No provider for HttpClient! Required by MyComponent -> MyService
```

## Minimal reproduction of the problem with instructions
See above.

## What is the motivation / use case for changing the behavior?
When my component depends on many services, a message saying HttpClient was not provided does not help me work out which of my services is missing from my test.

## Environment

<pre><code>
Angular CLI: 6.2.1
Node: 8.11.1
OS: linux x64
Angular: 6.1.7
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router
</code></pre>

**Comment by cice** [comment] 2018-09-14 13:48
:+1:

**Comment by pkozlowski-opensource** [comment] 2020-02-18 19:51
This continue to be a problem in Angular v9 with ivy: https://ng-run.com/edit/SZaPEIwyA7uQ4DVyNeLD

The ivy error message looks like so:

> R3InjectorError(AppModule)[MyService -> MyService -> MyService]: 
  NullInjectorError: No provider for MyService!

**Comment by AndrewKushnir** [comment] 2022-06-28 02:01
Closing as a duplicate of #46189.

**Closed by AndrewKushnir** 2022-06-28 02:01 UTC
Labels: hotlist: error messages, comp: core, core: di, type: confusing, P4
