### ISSUE TITLE
Missing Providers don't log helpful error messages in ng test

### ISSUE THREAD

**Issue by georgeedwards** [angular/angular#15985] opened 2017-04-14 12:17 UTC
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When running a test on a component which requires something passed to it's constructor e.g. a service, but the test module doesn't provide it, you get an error like:

```
Chrome 57.0.2987 (Windows 10 0.0.0) DwnTimeComponent should create FAILED
        Error
            at injectionError (webpack:///~/@angular/core/@angular/core.es5.js:1231:21 <- client/src/test.ts:6040:86) [angular]
            at noProviderError (webpack:///~/@angular/core/@angular/core.es5.js:1269:0 <- client/src/test.ts:6078:12) [angular]
            at ReflectiveInjector_._throwOrNull (webpack:///~/@angular/core/@angular/core.es5.js:2770:0 <- client/src/test.ts:7579:19) [angular]
            at ReflectiveInjector_._getByKeyDefault (webpack:///~/@angular/core/@angular/core.es5.js:2809:0 <- client/src/test.ts:7618:25) [angular]
            at ReflectiveInjector_._getByKey (webpack:///~/@angular/core/@angular/core.es5.js:2741:0 <- client/src/test.ts:7550:25) [angular]
            at ReflectiveInjector_.get (webpack:///~/@angular/core/@angular/core.es5.js:2610:0 <- client/src/test.ts:7419:21) [angular]
            at DynamicTestModuleInjector.NgModuleInjector.get (webpack:///~/@angular/core/@angular/core.es5.js:3557:0 <- client/src/test.ts:8366:52) [angular]
            at resolveDep (webpack:///~/@angular/core/@angular/core.es5.js:10930:0 <- client/src/test.ts:15739:45) [angular]
            at createClass (webpack:///~/@angular/core/@angular/core.es5.js:10791:0 <- client/src/test.ts:15600:35) [angular]
            at createDirectiveInstance (webpack:///~/@angular/core/@angular/core.es5.js:10627:21 <- client/src/test.ts:15436:37) [angular]
            at createViewNodes (webpack:///~/@angular/core/@angular/core.es5.js:11977:33 <- client/src/test.ts:16786:49) [angular]
            at createRootView (webpack:///~/@angular/core/@angular/core.es5.js:11882:0 <- client/src/test.ts:16691:5) [angular]
            at callWithDebugContext (webpack:///~/@angular/core/@angular/core.es5.js:13013:25 <- client/src/test.ts:17822:42) [angular]
            at Object.debugCreateRootView [as createRootView] (webpack:///~/@angular/core/@angular/core.es5.js:12474:0 <- client/src/test.ts:17283:12) [angular]
        Expected undefined to be truthy.
            at Object.<anonymous> (webpack:///client/src/app/modules/shared/components/dwn-time/dwn-time.component.spec.ts:24:22 <- client/src/test.ts:20160:27) [ProxyZone]
            at ProxyZoneSpec.onInvoke (webpack:///~/zone.js/dist/proxy.js:79:0 <- client/src/test.ts:122670:39) [ProxyZone]
            at Zone.run (webpack:///~/zone.js/dist/zone.js:125:0 <- client/src/test.ts:170998:43) [ProxyZone => ProxyZone]
            at Object.<anonymous> (webpack:///~/zone.js/dist/jasmine-patch.js:104:0 <- client/src/test.ts:122384:34) [ProxyZone]
```

**Expected behavior**
Previously (I think pre-v4), you would get an error in the form No Provider for X. 

**Minimal reproduction of the problem with instructions**
```
$ ng new test
$ ng generate component provide
```

add these to the provide component
```
import {ActivatedRoute} from '@angular/router';
constructor(private route: ActivatedRoute) {  }
```

**What is the motivation / use case for changing the behavior?**
Making testing easier

**Please tell us about your environment:**
Windows

* **Angular version:** 4.0.1

**Comment by Headcult** [comment] 2017-04-18 11:55
Same issue here. Any workaround for now?

**Comment by Headcult** [comment] 2017-04-18 12:06
Got it, added the right providers in spec files too, it worked fine.

**Comment by avianbc** [comment] 2017-04-20 19:22
Ugly temporary workaround:  surround your TestBed with a try/catch(error) and check out error.message property for the message that it should be displaying.

The message is there but seems to be getting lost somewhere along the way.

**Comment by Headcult** [comment] 2017-04-21 05:44
Finally found the root cause of my issue. Actually, it was displayed clearly in the Karma browser window about `Missing providers for Http`. But even after adding `Http` to the providers list, a different error (`No provider for ConnectionBackend!`) occured.

Then, after going through Stackoverflow, found out that `HttpModule` needs to added to `imports` section and not providers section. This change resolved all my test failures.

**Comment by evanjmg** [comment] 2017-04-24 13:07
@Headcult Where are you looking in the browser? My console provides the same useless message as what is logged out in my logs. This needs to be fixed asap as I can't edit/run my unit tests without this!

**Comment by ZenabKhan** [comment] 2017-04-25 17:53
Any update on this one? Can't even debug since it seems a clueless error to me.

**Comment by Headcult** [comment] 2017-04-26 05:18
@evanjmg @ZenabKhan When you run your tests with `ng test` you'll see the Chrome window pop-up with Karma status on it. Over there, you'll see all your tests and their results too. When your tests fail, the exact reason for the failure is shown on the browser under your tests section.

Maybe, you are not using the latest version of Angular-CLI where it uses `karma-jasmine-html-reporter` for generating the results on the browser.

Agreed, the console output has not indication about the error, which needs to be fixed soon.

**Comment by ZenabKhan** [comment] 2017-04-26 10:53
@Headcult I am using the latest Angular-CLI but I can't see anything on the window. Here is the result of `ng -v`
@angular/cli: 1.0.1
node: 7.0.0
os: darwin x64
@angular/animations: 4.0.3
@angular/cli: 1.0.1
@angular/common: 4.0.3
@angular/compiler: 4.0.3
@angular/compiler-cli: 4.0.3
@angular/core: 4.0.3
@angular/forms: 4.0.3
@angular/http: 4.0.3
@angular/platform-browser: 4.0.3
@angular/platform-browser-dynamic: 4.0.3
@angular/platform-server: 4.0.3
@angular/router: 4.0.3
@ngtools/webpack: 1.3.1

But thanks to your earlier comment, there were some missing services and modules in the spec file. I added those and the tests are passing.

**Comment by Headcult** [comment] 2017-04-26 17:12
You could verify your DevDependencies with my list (Tour of Heroes App):

``` "devDependencies": 
{
    "@angular/cli": "1.0.0",
    "@angular/compiler-cli": "^4.0.0",
    "@types/jasmine": "2.5.38",
    "@types/node": "~6.0.60",
    "codelyzer": "~2.0.0",
    "jasmine-core": "~2.5.2",
    "jasmine-spec-reporter": "~3.2.0",
    "karma": "~1.4.1",
    "karma-chrome-launcher": "~2.0.0",
    "karma-cli": "~1.0.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "karma-coverage-istanbul-reporter": "^0.2.0",
    "protractor": "~5.1.0",
    "ts-node": "~2.0.0",
    "tslint": "~4.5.0",
    "typescript": "~2.2.0"
}
```

**Comment by georgeedwards** [comment] 2017-04-26 22:01
@tbosch Do you have any idea about a fix for this?

**Comment by tbosch** [comment] 2017-05-12 23:00
This has been fixed by https://github.com/angular/angular/commit/ce1d7c4a6e46de00fc0c4aae0d046de34d6a8395.

**Closed by tbosch** 2017-05-12 23:00 UTC
Labels: comp: core & compiler, freq2: medium, severity3: broken, type: bug
