### ISSUE TITLE
bloomAdd needs a guard against type == undefined

### ISSUE THREAD

**Issue by moniuch** [angular/angular#48068] opened 2022-11-15 22:35 UTC
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

While experimenting with viewProviders and forms I encountered the following bug:

![bloom_undefined](https://user-images.githubusercontent.com/681956/202038603-06afe9d1-bb1b-4355-aa3b-febf0bc9af62.png)

I'm not 100% sure how to reproduce it. Could be that it occurred because I was trying to access ControlContainer.control in the constructor (while it doesn't seem to be ready yet, it only comes ready in `ngOnInit()`?).

Anyway, I think the code doesn't account for `type` being `undefined` and so it could benefit from some sort of guard
https://github.com/angular/angular/blob/38b2ed314dd6b6661c15751f4b08fdc038a2c364/packages/core/src/render3/di.ts#L117
 

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.0.0-rc.3
Node: 18.10.0
Package Manager: npm 9.1.1
OS: darwin arm64

Angular: 15.0.0-rc.4
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1500.0-rc.3
@angular-devkit/build-angular   15.0.0-rc.3
@angular-devkit/core            15.0.0-rc.3
@angular-devkit/schematics      15.0.0-rc.3
@angular/cli                    15.0.0-rc.3
@schematics/angular             15.0.0-rc.3
rxjs                            7.5.7
typescript                      4.8.4
```

### Anything else?

1. The error messages could be more descriptive, esp. considering the recent quest of making Angular error messages more friendly :) 
2. The template question: "Is this a regression?" should include an "I don't know" option, as not everyone has to be aware of that detail.

**Comment by atscott** [comment] 2022-11-15 23:00
Simply adding a type guard for `undefined` doesn't really solve anything in this case. We need to track down how that function got `undefined` in the first place. The root cause is somewhere else and we'd need a reproduction to understand why.

**Comment by JeanMeche** [comment] 2022-11-16 17:09
Yeah, at one time `resolveForwardRef`  within `resolveProvider()` in `di.setup.ts` returns undefined. 

Please provide a Stackblitz.

**Comment by AndrewKushnir** [comment] 2022-11-23 17:46
Closing this ticket for now, please reopen or create a new ticket when a repro is available. Thank you.

**Closed by AndrewKushnir** 2022-11-23 17:46 UTC
Labels: needs reproduction, area: core
