### ISSUE TITLE
[Angular 10.1.2] Error:Unexpected value 'LibraryModule in[..] imported by module.ts. Please add a @ngModule.annonation.

### ISSUE THREAD

**Issue by rahultokase** [angular/angular#38893] opened 2020-09-17 18:47 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....
Angular CLI: 10.1.2
Node: 10.16.0
OS: linux x64

Angular: 10.1.2
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: No

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1001.2
@angular-devkit/build-angular      0.1001.2
@angular-devkit/build-ng-packagr   0.1001.2
@angular-devkit/core               10.1.2
@angular-devkit/schematics         10.1.2
@angular/cdk                       10.2.1
@angular/material                  10.1.1
@schematics/angular                10.1.2
@schematics/update                 0.1001.2
ng-packagr                         9.0.0
rxjs                               6.6.3
typescript                         4.0.2

### Is this a regression?

 Yes Angular 8 was working fine.
 Yes, the previous version in which this bug was not present was: ....

### Description
I have library module which is upgraded to angular 10.1.2 from angular 8.1.2.  with enableIvy:false i have created the prod build. Upon using the library module into another application which is also upgraded angular 10.1.2 application i am getting the error.

 A clear and concise description of the problem...

## 🔬 Minimal Reproduction

 https://stackblitz.com/...

## 🔥 Exception or Error
<pre><code>

ERROR: Unexpected value 'LibraryModule in /home/my-app/node_modules/@mylib/ui-libs/libs/library.module.d.ts' imported by the module 'SharedlibModule in /home/my-app/projects/sharedlib/src/lib/sharedlib.module.ts'. Please add a @NgModule annotation.
Can't bind to 'formConfig' since it isn't a known property of myapp-dynamic-form'.
1. If ‘myapp-dynamic-form' is an Angular component and it has 'formConfig' input, then verify that it is part of this module.
2. If ‘myapp-dynamic-form' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 10.1.2
Node: 10.16.0
OS: linux x64

Angular: 10.1.2
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: No

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1001.2
@angular-devkit/build-angular      0.1001.2
@angular-devkit/build-ng-packagr   0.1001.2
@angular-devkit/core               10.1.2
@angular-devkit/schematics         10.1.2
@angular/cdk                       10.2.1
@angular/material                  10.1.1
@schematics/angular                10.1.2
@schematics/update                 0.1001.2
ng-packagr                         9.0.0
rxjs                               6.6.3
typescript                         4.0.2
</code></pre>

**Anything else relevant?**

**Comment by rahultokase** [comment] 2020-09-24 17:42
Hi Any updates on this ?

**Comment by NaKyouTae** [comment] 2020-10-06 05:21
I have same problem.

Angular upgrade 8.2 to 10.1.4

Did you succeed?

**Comment by JoostK** [comment] 2020-10-17 21:02
Hi @rahultokase,

unfortunately there's not enough information in the description for me to make an educated guess on what could be wrong. Are there any more errors reported above the one you posted? I would expect there to also be a message about the `LibraryModule` itself, besides the error for `SharedlibModule` which imports it.

I'll label this as "Needs reproduction" as without it we'll likely not be able to help you much further.

**Comment by justinwilaby** [comment] 2020-10-28 19:01
This is still a problem in `v10.2.0`

**Comment by petebacondarwin** [comment] 2020-10-28 19:03
@justinwilaby - perhaps you could provide a reproduction so that we can investigate?

**Comment by justinwilaby** [comment] 2020-10-28 21:18
@pedroclayman - Please see [this repo](https://github.com/justinwilaby/angular-issue-no38893) for minimal repro steps.

The gist of the problem seems to stem from building an Angular library with dependencies that include another Angular library. In the repro example provided, I am using the popular [ngx-file-drop[(https://github.com/georgipeltekov/ngx-file-drop) as a dependency and including it as an import for my library.

The error is:

```bash
ERROR: Unexpected value 'NgxFileDropModule in /Users/bleh/Documents/dev/angular-issue-no38893/node_modules/ngx-file-drop/ngx-file-drop/ngx-file-drop.module.d.ts' imported by the module 'LibModule in /Users/bleh/Documents/dev/angular-issue-no38893/src/lib/lib.module.ts'. Please add a @NgModule annotation.

An unhandled exception occurred: Unexpected value 'NgxFileDropModule in /Users/bleh/Documents/dev/angular-issue-no38893/node_modules/ngx-file-drop/ngx-file-drop/ngx-file-drop.module.d.ts' imported by the module 'LibModule in /Users/bleh/Documents/dev/angular-issue-no38893/src/lib/lib.module.ts'. Please add a @NgModule annotation.

See "/private/var/folders/_2/pwdscr9x15n8hhq8xzrzgx7h0000gp/T/ng-iplDud/angular-errors.log" for further details.
```

**Comment by petebacondarwin** [comment] 2020-11-02 21:31
@justinwilaby - the library that you are depending upon has been published (invalidly) after being compiled via Ivy. This is not supported. The `ngx-file-drop` library must be built in ViewEngine compiler mode before being published. Then you can also build your library in ViewEngine mode.

The problem is therefore with the author of the `ngx-file-drop` library who should not have published a library built with Ivy.
Closing as this is working as expected from the Angular compiler side of things.

**Closed by petebacondarwin** 2020-11-02 21:31 UTC
Labels: comp: compiler, comp: core
