### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by rajendrakumaryadav** [angular/angular#53086] opened 2023-11-21 07:53 UTC
### Describe the problem that you experienced

Page not found error

### Enter the URL of the topic with the problem

https://angular.dev/api/common#pipes

### Describe what you were looking for in the documentation

Pipes API documentation

### Describe the actions that led you to experience the problem

Pipes API documentation

### Describe what you want to experience that would fix the problem

Resolve the url

### Add a screenshot if that helps illustrate the problem

![IMG_20231121_132208000_HDR](https://github.com/angular/angular/assets/13816347/1d9a6362-8c0f-4cbb-a36a-5a95782f4ac8)

### If the problem is browser-specific, please specify the device, OS, browser, and version

```true
Version: 17
```

**Comment by JoostK** [comment] 2023-11-21 12:30
Thanks for the report, closing as duplicate of #52968.

**Closed by JoostK** 2023-11-21 12:30 UTC
