### ISSUE TITLE
Content children of angular element is not working in non angular application.

### ISSUE THREAD

**Issue by ecemitrasharma** [angular/angular#42244] opened 2021-05-23 08:00 UTC
# Bug Report

### Affected Package
"@angular/elements": "^10.2.4"

### Is this a regression?
I was using angular element in aspx page so probably in this scenario older version may have this issue.

### Description

I have existing aspx application where I wanted to replace old controls with angular elements.

I developed below sample component

```
<tabs>
    <tab-item [title]="tab1">Some content</tab-item>
    <tab-item [title]="tab2">Some content</tab-item>
</tabs>

```I have 2 component
1. Tabs Component
2. TabItem

So in the Tabs component, I have defined content children to read the list of content inside the tab.

`@ContentChildren(forwardRef(() => TabItemComponent)) tabs: QueryList<TabItemComponent> = new QueryList<TabItemComponent>();

`in ngAfterContentInit i am printing length of tab.

I defined my Tab component as an angular element and build the solution, Output in dist folder ==> main.js, polyfills.js and runtime.js.

I added all 3 JS references in my aspx page I observe always content children length is 0 although I can see in dom tags added properly.

Same I tested inside angular component it is working fine length is 2.

Normally we use angular elements if we have non-angular application so is angular not supporting content projection.




## Minimal Reproduction
<!--
create angular elements which support content projection build the project and add reference in non angular application you can observe content children length is 0 always.
-->

## Exception or Error

Content projection is not working properly

## Your Environment

**Angular Version:**
 "@angular/core": "^10.2.4",
"@angular/cli": "^10.2.1",

**Comment by petebacondarwin** [comment] 2021-05-23 09:54
Duplicate of #42236.

**Comment by gkalpak** [comment] 2021-05-23 09:54
_Similar/Related issues: #42222, #42236_

##
This works as intended I am afraid. When projecting content into a component, that content is used/inserted into the appropriate place in a component's view, but is not considered part of the view. (For example, it is not compiled as part of the view.)

In a regular Angular application, where for example you have an `AppComponent` with the tabs and tab-items in its template, the tab-items are part of the `AppComponent`'s view (i.e. they are compiled as part of the `AppComponent`'s template and then just happen to be moved to a different place in the DOM by the `TabsComponent` (via content projection)).

When using Angular Elements, however, each element is like a self-contained mini-app (you can think of each element as its own `AppComponent`). So, while both the `TabsComponent` and the `TabItemComponent`  are compiled and have their views rendered, they are not part of a single Angular application. Therefore, the `TabsComponent` does not realize that the `<tab-item>` element is a `TabItemComponent`. From `TabsComponent`'s perspective, the `<tab-item>` elements looks like just another regular HTML element.

(Essentially, this is the same reason why you can't project content into a regular app's `AppComponent`.)

So, while content projection does work in Angular Elements (in the sense that you can use `<ng-content>` as usual), you cannot treat the projected content as Angular-specific (i.e. not rely on concepts, such as components, directives, etc.), which means that `@ContentChild`/`@ContentChildren` aren't useful.

##
As a work-around, you can use regular DOM query methods to grab the `<tab-item>` elements and interact with them:

```ts
class TabsComponent implements AfterContentInit {
  private tabsElement: HTMLElement;

  constructor(elementRef: ElementRef) {
    this.tabsElement = elementRef.nativeElement;
  }

  ngAfterContentInit() {
    const tabItemElements = this.tabsElement.querySelectorAll('tab-item');
    // ...
  }

  // ...
}
```

Also, if your requirements (such as browser support, etc.) allow it, you could switch from `ng-content` to [slots][1], which are the native way of doing content projection with Custom Elements. You can read more about it online, such as [here][2] and [there][3].

[1]: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/slot
[2]: https://www.infragistics.com/community/blogs/b/infragistics/posts/content-projection-in-angular-element-with-slot-in-angular-7-0-290541905
[3]: https://www.angulararchitects.io/aktuelles/content-projection-with-slots-in-angular-elements-7/

**Closed by petebacondarwin** 2021-05-23 09:54 UTC

**Comment by ecemitrasharma** [comment] 2021-05-23 10:30
I was using ElementRef and iterating to solve my problem just want to check if content children we can directly access would have  made my component more robust and easy to handle via non angular app too.

**Comment by ecemitrasharma** [comment] 2021-05-23 10:57
> _Similar/Related issues: #42222, #42236_
> 
> This works as intended I am afraid. When projecting content into a component, that content is used/inserted into the appropriate place in a component's view, but is not considered part of the view. (For example, it is not compiled as part of the view.)
> 
> In a regular Angular application, where for example you have an `AppComponent` with the tabs and tab-items in its template, the tab-items are part of the `AppComponent`'s view (i.e. they are compiled as part of the `AppComponent`'s template and then just happen to be moved to a different place in the DOM by the `TabsComponent` (via content projection)).
> 
> When using Angular Elements, however, each element is like a self-contained mini-app (you can think of each element as its own `AppComponent`). So, while both the `TabsComponent` and the `TabItemComponent` are compiled and have their views rendered, they are not part of a single Angular application. Therefore, the `TabsComponent` does not realize that the `<tab-item>` element is a `TabItemComponent`. From `TabsComponent`'s perspective, the `<tab-item>` elements looks like just another regular HTML element.
> 
> (Essentially, this is the same reason why you can't project content into a regular app's `AppComponent`.)
> 
> So, while content projection does work in Angular Elements (in the sense that you can use `<ng-content>` as usual), you cannot treat the projected content as Angular-specific (i.e. not rely on concepts, such as components, directives, etc.), which means that `@ContentChild`/`@ContentChildren` aren't useful.
> 
> As a work-around, you can use regular DOM query methods to grab the `<tab-item>` elements and interact with them:
> 
> ```ts
> class TabsComponent implements AfterContentInit {
>   private tabsElement: HTMLElement;
> 
>   constructor(elementRef: ElementRef) {
>     this.tabsElement = elementRef.nativeElement;
>   }
> 
>   ngAfterContentInit() {
>     const tabItemElements = this.tabsElement.querySelectorAll('tab-item');
>     // ...
>   }
> 
>   // ...
> }
> ```
> 
> > _**EDIT:**_
> > _I just found out that the projected content is not inserted into the view when `ngAfterContentInit()` is fired in Angular Elements, which seems like a bug. (I have created #42246 to track it.))_
> > _As a work-around, you can wrap the code in a `setTimeout()` or `Promise.resolve().then()` to make it run asynchronous:_
> > ```ts
> > ngAfterContentInit() {
> >   setTimeout(() => { /* Query tab-items. */ });
> > }
> > ```
> 
> Also, if your requirements (such as browser support, etc.) allow it, you could switch from `ng-content` to [slots](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/slot), which are the native way of doing content projection with Custom Elements. You can read more about it online, such as [here](https://www.infragistics.com/community/blogs/b/infragistics/posts/content-projection-in-angular-element-with-slot-in-angular-7-0-290541905) and [there](https://www.angulararchitects.io/aktuelles/content-projection-with-slots-in-angular-elements-7/).

Yeah instead of timeout I am using ngAfterViewInit
