### ISSUE TITLE
angular.dev - duplicate line

### ISSUE THREAD

**Issue by StormLx** [angular/angular#52616] opened 2023-11-08 09:46 UTC
### Describe the problem that you experienced

Hello, i've noticed a duplicated line [here](https://angular.dev/guide/components).
![image](https://github.com/angular/angular/assets/78553030/e5d13f07-d55d-40a6-903a-e0672bb358ef)

**Comment by JoostK** [comment] 2023-11-08 10:58
Thanks for the report! This is a duplicate of #52575.

**Closed by JoostK** 2023-11-08 10:58 UTC
