### ISSUE TITLE
Proposal: Renderer 2 setStyle and invokeElementMethod

### ISSUE THREAD

**Issue by NetanelBasal** [angular/angular#19828] opened 2017-10-20 13:26 UTC
## I'm submitting a...
<pre><code>[x] Feature request</code></pre>

## Current behavior
1. `setStyle` - There is no way to pass an object.
2. `invokeElementMethod` - Removed.

## What is the motivation/use case for changing the behavior?
1. `setStyle` - Allow passing an object for more comfortable use when you have multiple properties. 
2. `invokeElementMethod` - We need this to be able to run things like `focus()`, `getBoundingClientRect()`, etc. (SSR, web workers)

**Comment by trotyl** [comment] 2017-10-20 13:32
Duplicate of #15674 for 2nd question.

**Comment by strizzaflex** [comment] 2017-11-09 18:26
The second part is a duplicate, however, I was not clear on the answer. From what I got out of it was the framework is just going to punt. Is that correct?

**Comment by jasonaden** [comment] 2017-11-11 00:03
See [this comment](https://github.com/angular/angular/issues/15674#issuecomment-343618245) on the related issue. I think that will help to answer your question. And yes, agreed this type of functionality is needed.

With the new APIs that will be coming, you will have access to a native-like DOM API on both client and server. This should address both feature requests above.

I'll close this issue as the solution to both these features is already in planning for an upcoming release.

**Closed by jasonaden** 2017-11-11 00:03 UTC
