### ISSUE TITLE
Unexpected behavior for providedIn services in TestBed

### ISSUE THREAD

**Issue by shairez** [angular/angular#25593] opened 2018-08-21 10:33 UTC
`providedIn` has brought a lot of goodies into the Angular world, especially for lazy loaded modules configurations. 

BUT...

On the testing side, it's current behavior is confusing and unwanted for isolation. 

## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

`providedIn` providers are being loaded automatically by `TestBed` 's Testing Module. 

## Expected behavior

I test all of my units in isolation. 

Whilte testing, I would like the providers to not be configured automatically so I could see an error if I forgot to stub / mock a certain provider.

If we're not going to change this behavior, at least let's add a FLAG that gives people the opportunity to configure `TestBed` to fail when we're not manually configuring `providedIn` services. 

## Minimal reproduction of the problem with instructions

look at the following project:

It's not clear from the `hello.component.spec.ts` that an ajax request somewhere down the injection tree is being called 

open the console and see the message from the `product.service.ts`

https://stackblitz.com/edit/angular-testing-providedin-example

## What is the motivation / use case for changing the behavior?

Imagine the following (very realistic) scenario:

1. You write an test for your main component (isolating all of it's immediate dependencies) 

2. This component has child components 

3. Sometime in the future, another developer adds a dependency to one of the child components which has some side effect (ajax request or an error, or a change to the router, etc)

4. It will take you quite a while ( in a large scale app) to track down the specific reason 

The bad part about this is that it's very sneaky and not obvious because the failure usually will come later and not as soon as possbie. 

So I suggest, to ignore `providedIn` services in TestBed on purpose (or at least add a FLAG that allows you to achieve this behavior for the sake of our test debugging time)

## Environment

<pre><code>
Angular version: 6.1.2

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by FDIM** [comment] 2018-09-19 21:03
I'd like to tackle this issue and ensure that testing module is always isolated / empty. I'd say that this behavior should not change

**Comment by JohannesHoppe** [comment] 2019-02-02 15:03
I completely agree with @shairez. We have an issue, we have a solution (PR). Are there any chances that the current behavior will be fixed? Or did we already accepted integration tests as the new default?! 🤨

**Comment by FDIM** [comment] 2019-02-02 20:04
I hope not! Sadly this issue is not an issue for google internally and thus has very little priority - At least this is my general experience when trying to contribute. Maybe 2019 will be a good year

**Comment by niklas-wortmann** [comment] 2020-10-03 20:58
I do agree with @shairez too, the problem with the proposed solution of #26088 that it would break a lot of tests (at least from my perspective and for a lot of projects I've seen) and therefore it should be considered a breaking change. Also in the pr it is correctly stated out that this kind of behavior is quite nice for integration tests. To advance with this in a non-breaking way I would rather create a new method in the `TestBed`, e.g. `TestBed.configureUnitTestingModule`.

**Comment by andreea-s** [comment] 2021-03-11 20:48
The behavior is nice for integration tests, but not so much for unit tests. It sort of replicates the angularjs issue where one would load a module and all the services in there would be automatically provided. Having a clean environment where one has to explicitly provide each service is more practical, than trying to figure out what the dependency graph is and what services have not yet been provided in the tests.

**Comment by christophamma** [comment] 2022-01-04 10:08
We are experiencing this issue as well in a new rather large angular project. We have a lot of services that depend on other services and unless you check all dependencies manually and include them in the TestBed, you end up with integration tests instead of unittests without even noticing. It is almost certain that developers forget to mock dependencies. I'm really surprised that this done on purpose as it seems like a major flaw to me.

Does anyone have a workaround for this or is there any way to check for non-mocked dependencies in an existing code-base?

**Comment by FDIM** [comment] 2022-01-04 10:48
@christophamma sadly only one, skip using provided in root :/ This is what we ended up agreeing to do in the project I'm in. Tree shaking dead services in a project is not as important as in a library IMO.

**Comment by christophamma** [comment] 2022-01-04 10:52
> @christophamma sadly only one, skip using provided in root :/ This is what we ended up agreeing to do in the project I'm in. Tree shaking dead services in a project is not as important as in a library IMO.

@FDIM yes, seems better than ending up with flaky unittests. Do you simply agree on it or is there a way to enforce it in angular?

**Comment by FDIM** [comment] 2022-01-04 16:35
It was enough to agree for us, on the other hand I'm pretty sure writing eslint rule would be fairly simple to enforce this.

**Comment by JamesHenry** [comment] 2022-02-24 18:00
Creator of typescript-eslint and angular-eslint here 👋 

This was flagged up to me via a request to create a dedicated rule for this case. I am hesitant to do that for something which is still evolving as a topic and does not yet have a dedicated solution from the Angular Team.

However, you do not necessarily need to create a dedicated lint rule for this, the built-in ESLint `no-restricted-syntax` rule could be used to achieve the desired result:

```json
{
  "rules": {
    "no-restricted-syntax": [
      "error",
      {
        "selector": "Decorator[expression.callee.name=Injectable] Property[key.name=providedIn][value.value=root]",
        "message": "Do not use `providedIn: root` in Injectables"
      }
    ]
  }
}
```

Example of it in action:

https://typescript-eslint.io/play/#ts=4.5.2&sourceType=module&showAST=es&code=JYWwDg9gTgLgBAbzgSQHYCsCmBjGBDAIwBtM4BfOAMyghDgHIABPVAcwFci8oB6baTPQDcAKBGM0WXIRIAKBCLhK4YGgDdgAE0ya0ALgY0IMeiLIBKEdi4BnG3ABiECIjIigA&rules=N4Igdg9gtATgpgZwC4wJYGMlwCZQQTzCQEMAPEALgG0Q4YYIYQAaUBOAGzk0cpABFujYkkZU4pAA7wECVBDAA6dMQ5c4isMQC2cALwBJMACtuJAEZcAugAIbABQaS6SfFQDWcfJp37pEADdUbBwjKyoA1QBXDUiOGL0GCCQrFhBdWWIAczg+fggbSCQbKPYbAAN-IJDsIwobJKRym1QwGyNTTGJLRBAAXys+oA&tsConfig=N4IgpgHgDmBOCWBbMA7ALgQwDYBEwGMB7WDNYgZxAC41YBXMAGnEXjTyJLNgFkxMAJqQzVaDAL5A

![image](https://user-images.githubusercontent.com/900523/155580678-b72d4304-2398-4b55-a404-ac2b899568a5.png)

**Comment by JohannesHoppe** [comment] 2022-02-25 11:28
@JamesHenry @coyoteecd I'm confused. `Injectable({ providedIn: 'root' })` is the correct way to use Injectables. this rule would effect the old, no longer recommended syntax (without provideIn). In the past, services were not tree-shakable and that was not good at all!

The problem is that the unit tests are implemented in an unpleasant way. But this cannot mean that we weaken the productive code!

**Comment by JamesHenry** [comment] 2022-02-25 11:32
@JohannesHoppe hence why I am unwilling to implement this as a rule in angular-eslint

**Comment by JohannesHoppe** [comment] 2022-02-25 11:46
But this rule would recommend an anti-pattern! ☹️

**Comment by coyoteecd** [comment] 2022-02-25 12:26
@JohannesHoppe as the other commenters above me, I have tried the "recommended way" and ended up wasting many hours debugging flaky tests in our test suites, because it's very easy to end up with a service automatically provided in your TestBed without you being aware of it. 

[The Angular team doesn't want to fix this](https://github.com/angular/angular/pull/26088#issuecomment-953361851) - even if people have explained that it leads to unit test issues - calling it "by design". So we ended up doing what @FDIM is doing, stop using providedIn across the project. The sample no-restricted-syntax rule works fine for enforcing this and I'm glad that it's documented here for anyone else that hits this issue.

**Comment by christophamma** [comment] 2022-02-25 12:37
@JamesHenry thanks for providing the example. We ended up writing our own rule as @FDIM suggested but this lead to issues in webstorm. The no-restricted-syntax version is much better. 

I still think, that this should be solved, as IMHO it violates principles of good software design to implicitly inject real services within the TestBed.

**Comment by FDIM** [comment] 2022-02-25 13:07
> @JamesHenry @coyoteecd I'm confused. `Injectable({ providedIn: 'root' })` is the correct way to use Injectables. this rule would effect the old, no longer recommended syntax (without provideIn). In the past, services were not tree-shakable and that was not good at all!
> 
> The problem is that the unit tests are implemented in an unpleasant way. But this cannot mean that we weaken the productive code!

Tree shaking is a very weak argument in application code - there should be no unused code IMO. Hence I'm advocating of not using it for easier maintenance.

For libraries it does solve a real problem, there is a higher chance of having shared code that is not used in all the projects.

**Comment by alxhub** [comment] 2023-12-15 19:11
Out of curiosity, how would you propose handling this case:

```typescript
import {UiCmp} from 'some/lib';
it('tests a component that uses a third party dependency', () => {
  @Component({template: '<ui-cmp', ...})
  class TestCmp {}

  TestBed.configureTestingModule({disableRootProviders: true});

  const fix = TestBed.createComponent(TestCmp);
  fix.detectChanges();

  expect(fix.nativeElement.innerHTML).toEqual('...');
}
```

if `UiCmp` requires a private (not exported) `providedIn: 'root'` service to function?

**Comment by coyoteecd** [comment] 2023-12-16 00:28
@alxhub quick answer would be "let it fail". But yeah, you're having a point there, there will be many corner cases. Another one is that I wouldn't want to explicitly provide NgZone, ElementRef etc. in each and every test.

Maybe a different idea that provides a sufficient level of safety: is there any way to detect at runtime that a service is being injected in the TestBed? An assert in the constructor of our API services that they're not running in a test environment would work, and circumvent the issue with NgZone or other private services used by 3rd party components. Or maybe a decorator, or an option in the existing Injectable decorator, that marks an individual service as "not provided in test bed"...

**Comment by JeanMeche** [comment] 2024-03-24 06:55
I'll reshare [Alex' rationale](https://github.com/angular/angular/issues/54438#issuecomment-1971813177) about `TestBed` : 

> After some additional discussion on the team, we've decided to close this issue as something we don't plan on supporting.
> 
> Angular faces a tradeoff here. We absolutely understand and value the simplicity and power of a DI-based framework, where behavior is always abstracted through interfaces, and any part of the framework can be replaced or faked. The power of this kind of architecture is clearly demonstrated in other technologies (e.g. the Spring Framework).
> 
> On the other hand, we're responsible for updating thousands of Angular applications across Google's codebase, so we have a front row seat to the challenges developers face in maintaining their own applications. By far, the biggest friction we face in applying these updates is when applications have tests which mock framework features. At best, this causes these tests to diverge from reality when the behavior of the underlying feature changes. At worst, we're blocked from updating at all until we correct the tests (and users externally who are updating Angular would be similarly challenged).
> 
> As a result, we've become very conservative about giving tests the ability to mock framework behavior. Our message has been that code which depends on framework functionality should be using TestBed for testing, as that helps guarantee that the tests will match Angular's production behavior, and evolve with it over time.
> 
> Occasionally developers wish to write tests at a very small granularity, without a dependency on the framework. Our stance is that developers should then provide their own abstraction layers. This could involve extracting business logic out of components, so it has no dependency on Angular features like inputs, outputs, queries, templates, etc. Operations like effects could be moved behind service APIs that can be mocked/faked as needed.
> 
> A separate complaint that sometimes gets brought up is that "TestBed is too slow". Often when I've heard this, it's been based on historical experiences with TestBed that may no longer be valid. Prior to Ivy, TestBed performed JIT recompilation of all components in the test, on every test. This was indeed very slow. Ivy made TestBed something like 90% faster by reusing the compilation output between tests as much as possible. Our own framework tests went from taking several minutes to 10s of seconds.
> 
> There may still be cases where TestBed is slower than hand-written vanilla tests. This is sometimes because TestBed ensures that production behavior is replicated in full (e.g. destroying services at the end of the test). If you have use cases where you feel TestBed should be faster, please feel free to open an issue with a reproduction and we'd be happy to see if there are opportunities for optimization.

In the case we're discussing here. `TestBed` is expected to mimic the production behavior. In the case we're discussing here, if you use `providedIn: 'root'` you should expect the token to be provided by default.

If you do not want to provide it by default, you should remove `providedIn:'root'` and define the provider yourself.

**Closed by JeanMeche** 2024-03-24 06:55 UTC
Labels: feature, area: testing, freq3: high, P4, feature: under consideration, area: adev
