### ISSUE TITLE
@angular/service-worker not caching apis in data groups array

### ISSUE THREAD

**Issue by vugar005** [angular/angular#31988] opened 2019-08-03 20:48 UTC
# 🐞 bug report

### Affected Package
@angular/service-worker

### Description

Angular service worker not caching apis in data groups array.  Assets are working normally.
[Live Website](https://test.plusminus.az/home)
My ngsw-config.json:
```
{
  "$schema": "./node_modules/@angular/service-worker/config/schema.json",
  "index": "/index.html",
  "assetGroups: [**],
  "dataGroups": [
    {
        "name": "all-apis",
        "urls": [
            "https://testapi.plusminus.az/mybank/**"
        ],
        "cacheConfig": {
            "maxSize": 100000000,
            "maxAge": "3d",
            "timeout": "1m"
        }
    }
]
}
```

## 🔬 Minimal Reproduction

Website: https://test.plusminus.az/home
Source Code: [github](https://github.com/vugar005/sevice-worker-datagroups-repro-issue)

## 🔥 Exception or Error
Angular service worker not caching apis in data groups
## 🌍  Your Environment

**Angular Version:**
Angular CLI: 8.2.0
Node: 10.15.3
OS: win32 x64
Angular: 8.2.0

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.802.0
@angular-devkit/build-angular      0.802.0
@angular-devkit/build-optimizer    0.802.0
@angular-devkit/build-webpack      0.802.0
@angular-devkit/core               8.0.0
@angular-devkit/schematics         8.0.0
@angular/cdk                       8.1.2
@angular/material                  8.1.2
@angular/material-moment-adapter   8.1.2
@angular/pwa                       0.802.0
@ngtools/webpack                   8.2.0
@schematics/angular                8.0.0
@schematics/update                 0.802.0
rxjs                               6.4.0
typescript                         3.5.3
webpack                            4.38.0

**Comment by gkalpak** [comment] 2019-08-04 11:53
Duplicate of #28988. See https://github.com/angular/angular/issues/28988#issuecomment-467983258 for an explanation (and if you want to submit a PR to update the docs, that would be 👌).

**Closed by gkalpak** 2019-08-04 11:53 UTC
Labels: comp: service-worker
