### ISSUE TITLE
Validators.required doesn't validate FileList length

### ISSUE THREAD

**Issue by sashaqred** [angular/angular#50431] opened 2023-05-23 16:50 UTC
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

Yes

### Description

Probably this is regression after this fix https://github.com/angular/angular/pull/33729

Steps to reproduce:
- open the link in Chrome https://stackblitz.com/edit/angular-zrch1k?file=src%2Fmain.ts
- upload any file
- open the file picker one more time
- close it without choosing any file
- Chrome will set empty FileList
- Angular form/formControl will be still valid since FileList is not an array

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-zrch1k?file=src%2Fmain.ts

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Chrome: 113.0.5672.92 (Official Build) (x86_64)
MacOS: 13.3.1 (22E261)

Dependencies from stackblitz:

  "dependencies": {
    "@angular/animations": "^16.0.1",
    "@angular/common": "^16.0.1",
    "@angular/compiler": "^16.0.1",
    "@angular/core": "^16.0.1",
    "@angular/forms": "^16.0.1",
    "@angular/platform-browser": "^16.0.1",
    "@angular/platform-browser-dynamic": "^16.0.1",
    "@angular/router": "^16.0.1",
    "rxjs": "^7.8.1",
    "tslib": "^2.5.0",
    "zone.js": "^0.13.0"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^16.0.1",
    "@angular/cli": "^16.0.1",
    "@angular/compiler-cli": "^16.0.1",
    "@types/jasmine": "~4.0.0",
    "jasmine-core": "~4.1.0",
    "karma": "~6.3.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.2.0",
    "karma-jasmine": "~5.0.0",
    "karma-jasmine-html-reporter": "~1.7.0",
    "typescript": "~4.9.0"
  }
```

**Comment by sunshuhan** [comment] 2023-05-29 13:52
Hello, I tried changing files to files**[0]**, and it works correctly
```
 <input (change)="fileControl.setValue($any($event.target)?.files[0])" type="file">
```

You mentioned that it worked a few years ago in you PR, maybe you were also using an index at that time.

**Comment by sunshuhan** [comment] 2023-06-04 03:26
Hi, when i search for an example of using formControl with input file, the chatGPT gives the code below, and it would also have the problem of validating because the fileList value is not **empty**.   i suppose many users may set formcontrol like this and encounter the same problem. Hoping this issue could be solved.

![image](https://github.com/angular/angular/assets/9651193/7c815c58-b981-4f63-968b-cfb788b0c6d0)

**Comment by JeanMeche** [comment] 2024-02-11 21:26
Quoting Joost in #50436
> I don't think we should be making this change. There are lots of array-like structures that are not accounted for, nor do I believe they should. FileList is iterable, so you can copy over the items to an array using Array.from() to derive an actual array.

Closing as work as intended.

**Closed by JeanMeche** 2024-02-11 21:26 UTC
Labels: area: forms
