### ISSUE TITLE
<select [multiple]="false" ...> outputs an array of values

### ISSUE THREAD

**Issue by satnav** [angular/angular#44399] opened 2021-12-08 06:27 UTC
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

No

### Description

When using [multiple]="false" directive on the `<select>` tag, the value written is an array with a single value. If the [multiple]="false" directive is removed, then it is just the single value written.

The UI widget is still rendered correctly, in that you can only select a single value, but I would have expected the output to not be wrapped in an array.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-bebgxi

### Please provide the exception or error you saw

```true
No error, output in console
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
My Local Machine
Angular CLI: 13.0.2
Node: 14.17.5
@angular-devkit/schematics      13.0.2
@angular/cli                    13.0.2
@angular/flex-layout            12.0.0-beta.35
@schematics/angular             13.0.2
ng-packagr                      13.0.3
rxjs                            7.4.0
typescript                      4.4.4
```

**Comment by Airblader** [comment] 2021-12-08 20:05
This is essentially the same as https://github.com/angular/angular/issues/13243, I believe. There are two different CVAs for `select` and `select multiple`, and bindings cannot define which directives are applied dynamically.

**Comment by satnav** [comment] 2021-12-09 03:35
Ah no worries, happy for this to be closed if need be then.

**Comment by AndrewKushnir** [comment] 2021-12-11 06:20
Closing as a duplicate of #13243.

**Closed by AndrewKushnir** 2021-12-11 06:20 UTC
Labels: comp: forms
