### ISSUE TITLE
Returning control.errors from Validator.validate keeps control invalid when it shouldn't be

### ISSUE THREAD

**Issue by huskerona** [angular/angular#30274] opened 2019-05-05 22:17 UTC
# 🐞 bug report

### Description
When implementing Validator on a component, `validate` will cause the control to be invalid even when it should be valid. This happens if `control.errors` is returned. Returning `null` causes the validation to succeed, which is the intended behavior. Is this expected behavior by `Validator.validate` implementation? Returning `null` without any additional logic defeats the purpose of this method.

```
validate(control: AbstractControl): ValidationErrors | null {
    if (!this.control) {
      this.control = control as FormControl;
    }

    // This way everything works fine, but return control.errors reports INVALID
    return null; 
  }
```

## 🔬 Minimal Reproduction
[Stackblitz link](https://stackblitz.com/edit/angular-uujwvb) (see input.component.ts)

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular: 7.2.14
Chrome, FireFox, Safari
</code></pre>

**Comment by atscott** [comment] 2019-08-29 22:41
Yes, this is working as intended. When you implement `Validator`, the `validate` function is an *additional* validator on top of those that you apply to the control [Validators.required, etc]. Returning `null` from your validate function doesn't clear the other errors from the control. This would be a *new* error object that gets merged with the others. So by returning `control.errors`, you are effectively preventing those errors from ever being removed from the control. 
The flow goes: 
1. errors get added
2. you change the value to make the control valid
3. validators run
4. your validator returns the errors that were on the control already
5. all errors get merged and applied to the control as new errors
 ^ this is the problem here. Your validators run before the `errors` property is set on the control so by returning the old errors, you prevent them from being removed.

**Closed by atscott** 2019-08-29 22:41 UTC
Labels: comp: forms
