### ISSUE TITLE
Change the title icon in angular 12

### ISSUE THREAD

**Issue by xswlw** [angular/angular#44287] opened 2021-11-26 03:28 UTC
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

I changed the original icon image but with the same property and same name as favicon.ico, it's not working even you can click the href in index.html and the system shows the icon. I restarted the server multiple times, it seems not working anyway.

#✍️solution
Finally, I tried to put the new favicon.ico into the assets folder, change the route in angular.json. It works pretty well and you can put the icon in your web title with any form.

#☕️☕️code
icon with the png/jepg form

index.html

`<link rel="icon" type="image/x-icon" href="./assets/icon.png">`

##angular.json
"assets": [
"src/assets/icon.png",
"src/assets"
],

icon with the ico form

index.html

`<link rel="icon" type="image/x-icon" href="./assets/icon.ico">`

##angular.json
"assets": [
"src/assets/icon.ico",
"src/assets"
],

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.0.3
Node: 17.1.0 (Unsupported)
Package Manager: npm 8.1.2
OS: darwin x64

Angular: 13.0.2
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1300.3
@angular-devkit/build-angular   13.0.3
@angular-devkit/core            13.0.3
@angular-devkit/schematics      13.0.3
@angular/cli                    13.0.3
@schematics/angular             13.0.3
rxjs                            7.4.0
typescript                      4.4.4
```

**Comment by alan-agius4** [comment] 2021-11-26 06:09
Duplicate of https://github.com/angular/angular-cli/issues/22235

**Closed by alan-agius4** 2021-11-26 06:09 UTC
