### ISSUE TITLE
PWA is not pinned to taskbar

### ISSUE THREAD

**Issue by victoria-zavadskaya** [angular/angular#44794] opened 2022-01-23 15:15 UTC
### Which @angular/* package(s) are the source of the bug?

service-worker

### Is this a regression?

No

### Description

1. Open https://angular.io/ and install PWA
2. Immediately pin PWA to taskbar

Actual result: PWA icon in task panel is changed to Browser icon
Expected result: PWA icon should be displayed in task bar

3. Close PWA
4. Click on browser icon (that was PWA before pin)

Actual result: Browser is opened instead of PWA
Expected result: PWA should be opened

### Please provide a link to a minimal reproduction of the bug

https://user-images.githubusercontent.com/98271205/150685069-646bed18-c4dd-49b0-8dad-2d9970bd4567.mp4

### Please provide the environment you discovered this bug in (run `ng version`)

```true

```

**Comment by geromegrignon** [comment] 2022-01-24 08:25
I can't reproduce it, Please provide details about your browser version.
I used Chrome Version 97.0.4692.71 for the test.

**Comment by victoria-zavadskaya** [comment] 2022-01-24 09:04
Issue is reproducible if user acts very quickly, and immediately tries to pin PWA after installing/opening. If user waits for a few seconds after installing/opening, then PWA behaves as expected.
Currently I use Chrome Version 97.0.4692.99, but issue was caught for older versions of browser.

**Comment by gkalpak** [comment] 2022-01-24 22:11
Thx for reporting this, @victoria-zavadskaya, and for providing detailed reproduction instructions.
This is not an issue with angular.io or even Angular, but rather an OS and/or browser issue. (I.e. the same can happen in a PWA without Angular at all). I think it happens if the browser is not given enough time to install the necessary assets or something.

I am going to close this issue, since there is nothing we can do about the problem on our side, but feel free to continue the discussion below.

**Closed by gkalpak** 2022-01-24 22:11 UTC
Labels: comp: service-worker

**Comment by victoria-zavadskaya** [comment] 2022-01-24 23:00
@gkalpak Thanks!
