### ISSUE TITLE
Mocking HttpClient does not work when nested service is injecting it

### ISSUE THREAD

**Issue by tommueller** [angular/angular#21440] opened 2018-01-10 10:48 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
I am upgrading to HttpClient from Http. I have a service which has a nested reference to HttpClient. My structure looks like this: My `TokenHandlerService` injects `MyHttpService` which injects Angular's `HttpClient`.
Using this code to mock the HttpClient in a test-environment leads to an `Error: No provider for HttpClient!`
```typescript
describe('TokenHandlerService', () => {
    let service: TokenHandlerService;

    beforeEach(() => {
        TestBed.configureTestingModule({
            imports: [
                HttpClientTestingModule
            ],
            providers: [
                TokenHandlerService,
                MyHttpService
            ]
        });
        service = TestBed.get(TokenHandlerService);
    });

    it('should load the service class', () => {
        expect(service).toBeTruthy();
    });
});
```

## Expected behavior

The test should run through successfully, as it did with the old mocked Http-class.

## Minimal reproduction of the problem with instructions

see the code further up

## Environment

<pre><code>
Angular version: 5.0.0

Browser:
none
 
For Tooling issues:
- Node version: v8.9.4  
- Platform:  Linux (Debian 9.3)

</code></pre>

**Comment by fredgate** [comment] 2018-01-14 10:37
I have same problem with a simple service (not a nested service) :
```
@Injectable()
export class FooService {
  constructor(private http: HttpClient) {
  }
} 
```

Configuration for unit tests of this service is as simple as :
```
beforeEach(() => {
  TestBed.configureTestingModule({
    imports: [HttpClientTestingModule],
    providers: [FooService]
  });
});
```

Now if I write a test like this :
```
it('should be created', inject([FooService], (service: FooService) => {
  expect(service).toBeTruthy();
}));
```
it faills with message (test is not executed) :
`Error: Can't resolve all parameters for FooService: (?).`

If I change the test to :
```
it('should be ok', inject([HttpClient], (http: HttpClient) => {
  expect(http).toBeTruthy();
}));
```
it's still failing with same message.

Now if I remove _FooService_ from providers of _TestBed_, then the test with _HttpClient_ directrly injected works ! Direct injection of HttpClient works, but injection of HttpClient in a service fails.
I am using angular 5.2.
it's completely blocking, since I can not write a single unit test for services.

**Comment by fredgate** [comment] 2018-01-18 21:44
In fact the error is not specific to HttpClient. It is very common and blocking. I meet it during tests as soon as I inject a type into another type.
An example as simple as below causes the error:
```
import { Injectable } from '@angular/core';
import { TestBed } from '@angular/core/testing';

@Injectable()
export class Foo {
	constructor(public bar: Bar) {
	}
}

@Injectable()
export class Bar {
}

describe('Foo', () => {

	beforeEach(() => {
		TestBed.configureTestingModule({
			providers: [
				Foo,
				Bar
			]
		});

		const foo = TestBed.get(Foo);
	});

	it ('should not fail when do nothing', () => {
	});
});
```

The error message appearing during test execution is :
```
Error: Can't resolve all parameters for Foo: (?). in http://localhost:9876/_karma_webpack_/vendor.bundle.js (line 20595)
syntaxError@http://localhost:9876/_karma_webpack_/vendor.bundle.js:20595:34
../../../compiler/esm5/compiler.js/CompileMetadataResolver.prototype._getDependenciesMetadata@http://localhost:9876/_karma_webpack_/vendor.bundle.js:35802:35
```

I get retrieve a instance of Foo from dependency injector, as it says that it can not resolve all parameters : there is only one parameter of type Bar.
But if I retrieve a Bar instance from TestBed, it works !
So it seems that the problem is not that it can not retrieve an instance of Bar, but rather that it can not retrieve metadata of Foo providing the types to inject.

**Comment by fredgate** [comment] 2018-01-19 21:15
Another option could be to run test with AOT : not available for moment.
See  angular/angular-cli#6650.

**Comment by devoto13** [comment] 2018-01-19 22:34
@fredgate I use AoT for everything except tests as well and I've moved this polyfill to `test.ts` to load it only in tests. I think this issue should be closed as "works as intended", since it is clearly stated that JiT requires this polyfill to work. And let's wait until AoT unit tests are supported to get rid of it completely.

**Comment by fredgate** [comment] 2018-01-20 10:53
@devoto13 I think we can effectively close this issue as this it works as intended.
However it would be nice to review the comment about es7/reflect as it mention that it can be disabled if AOT is used. Problem is that unit test can't be run in AOT mode, so that can lead to the problem mentioned here.

Adding es7/reflect polyfill to test.ts is a good workaround to load it only in tests. 👍 
As I use phantomjs on my CI/CD server, I wanted to do same thing for core-js polyfills. But it does not work because they are loaded too late. So I need to keep this polyfills in polyfill.js file : but it is bad because it forces to package polyfills required for tests on CI in the production build. It could be nice too have the possibility to have one polyfill file for application execution and another for tests execution.

**Comment by devoto13** [comment] 2018-01-20 11:11
I agree it makes sense to add something like `// NOTE: Running tests in AoT is currently not supported.` or something similar. In any case I think it is better to open separate issue/PR against https://github.com/angular/devkit repo ([file in question](https://github.com/angular/devkit/blob/master/packages/schematics/angular/application/files/__sourcedir__/polyfills.ts#L45)) and link this issue as the motivation for a change. This is not Angular issue, but rather issue with `@schematics/angular` package.

I agree with your point about separate polyfills. But I wonder why people still use PhantomJS for running tests, when both Chrome and Firefox have shipped headless support a while ago. PhantomJS is abandoned and its DOM implementation deviates from that of a modern browsers.

**Comment by tommueller** [comment] 2018-01-22 13:44
Quite excited that you guys found the issue I was left disappointed this morning finding out that the `'core-js/es7/reflect'`-polyfill was already uncommented and my tests still all fail, because the nested services cannot inject HttpClient. I suppose your issue was different to mine afterall.

This is still blocking for me, so I would love some feedback on this issue. Cheers.

**Closed** 2018-01-22 14:21 UTC
Labels: comp: common/http, freq2: medium, severity3: broken, type: bug

**Comment by fredgate** [comment] 2018-01-25 11:19
@devoto13 
I am submiting a pull request to angular/devkit.

I have planned to migrate from phantomjs to chrome headless. But the question that remains is : can we run unit tests on a machine where chrome is not installed. With phantomjs, we can, as we simply have to add npm package _phantomjs-prebuilt_ as a dev dependency. It is very useful for continuous integration server where nothing need to be installed as a prerequite.

**Comment by devoto13** [comment] 2018-01-25 11:31
@fredgate Have you seen [puppeteer](https://github.com/karma-runner/karma-chrome-launcher#headless-chromium-with-puppeteer) yet? I believe it solves exactly the problem you're concerned about.

However I would highly recommend to run CI jobs inside Docker container and use image, where all required software is already pre-installed. Here is an example of the Docker image used for Angular builds: https://github.com/alexeagle/ngcontainer.

**Comment by craigmatthew412** [comment] 2018-12-21 12:44
I added the core-js/es7/reflect polyfill to test.ts and my unit tests run perfectly fine...but what about e2e tests? I created a separate polyfill-e2e.ts file which only includes the core-js/es7/reflect polyfill and tried to include it via the tsconfig.e2e.json file to no avail. I don't see any relevant options for Protractor to load additional files before executing tests, either?
