### ISSUE TITLE
ExpressionChangedAfterItHasBeenCheckedError with reactive form and ngClass relying on input.value

### ISSUE THREAD

**Issue by FDIM** [angular/angular#25191] opened 2018-07-30 07:18 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

An `ExpressionChangedAfterItHasBeenCheckedError` error is thrown initially if there is an ngClass on input element relying on it's value. E.g. `<input #input [formControlName]="'name'" [ngClass]="{'has-value': input.value}" />`. 

Using `[class.has-value]="!!input.value"` seems to be working ok though.

Aside of the above, I investigated the flow a bit and it seems that initial value to input field is written via control value accessor a bit after the control is added to form group - Maybe it should be written at the same time?

## Expected behavior

No error

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/angular-g9igc3?file=src%2Fapp%2Fapp.component.html

## What is the motivation / use case for changing the behavior?

There should be no error when using ngClass

## Environment

<pre><code>
Angular version: 6.1.0

Browser:
- any
 </code></pre>

**Comment by mlc-mlapis** [comment] 2018-07-30 07:32
@FDIM ... you are changing it during the same CD cycle ... and Angular checks in developer mode the state before and after CD cycle ... and if something has been changed during it ... the error `ExpressionChangedAfterItHasBeenCheckedError` is showed to prevent you againt such a behavior. **It is not a bug ... it is a feature.**

**Comment by mlc-mlapis** [comment] 2018-07-30 12:29
@FDIM ... hmm, I can't imagine how it would be evaluated then to allow that logic ... because the order of the initial value of the control and the related template local variable `#input` and the value of `'has-value'`.
```
this.group = new FormGroup({
      name: new FormControl(this.name)
});
```
`<input #input [formControlName]="'name'" [ngClass]="{'has-value': input.value}" />`

What do you suggest to change exactly? It's evident that the binding `[ngClass]` is evaluated twice ... on the beginning it has value as empty string and after CD it has value of `'Angular 6'` ... so the value has changed during that CD cycle. What control mechanism to use to `wait` to something like that.

You mean to add some analyze to compiler that the template local variable is applied on the same tag to which it refers?

**Comment by FDIM** [comment] 2018-07-30 13:04
That is a good question! While there might be some solution I can see that it is not obvious nor worth the effort. Hopefully someone will find this issue if they manage to hit the same edge case.

We will use following workaround: `<input #input [formControlName]="'name'" [class.has-value]="!!input.value" />` as we don't actually need ngClass. Thanks for looking into this!

**Comment by kara** [comment] 2018-08-07 22:53
This looks like a duplicate of https://github.com/angular/angular/issues/18748. This is a larger problem with forms and change detection that needs some design thought.

**Closed by kara** 2018-08-07 22:53 UTC
Labels: comp: forms
