### ISSUE TITLE
Passing a date instance to a FormControl doesn't work

### ISSUE THREAD

**Issue by sfabriece** [angular/angular#13117] opened 2016-11-28 13:01 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Passing `new Date()` to FormControl doesn't work. Meaning that it is not reflected in the form.
`new FormControl(new Date())`

This works
`new FormControl('2016-11-28')`

**Expected behavior**

I expect the date to be parsed and shown in the form.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Windows 10, Vscode

* **Angular version:** 2.2.3

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by DzmitryShylovich** [comment] 2016-11-28 13:03
Duplicate of https://github.com/angular/angular/issues/8203

**Comment by kara** [comment] 2016-11-30 17:17
Thanks for reporting, but we will continue to track in the existing issue #8203. Closing as a duplicate.

**Closed by kara** 2016-11-30 17:17 UTC
Labels: comp: forms
