### ISSUE TITLE
named router-outlet doesn't display in child route (lazy loaded)

### ISSUE THREAD

**Issue by msio** [angular/angular#33034] opened 2019-10-08 07:52 UTC
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/router

### Is this a regression?
not sure

### Description
I want to display content of named router-outlet in a child. Every module is lazy loaded but I tried to do it without lazy loading and it behaves the same.  

## 🔬 Minimal Reproduction

There are 2 routes + one named route:
/people1
/people2
/people1/(part2:p2) 
 - (part2:p2): this part (it loads people2 component) should be displayed in pople1 component but when I hit /people1/(part2:p2) I only see people 1 component. I should see both pople1 and people2. 

https://stackblitz.com/edit/angular-f3cvxj

## 🔥 Exception or Error
There is no error. 

## 🌍  Your Environment
<pre>
**Angular Version:**
Angular CLI: 8.3.6
Node: 10.16.3
OS: win32 x64
Angular: 8.2.8
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.6
@angular-devkit/build-angular     0.803.6
@angular-devkit/build-optimizer   0.803.6
@angular-devkit/build-webpack     0.803.6
@angular-devkit/core              8.3.6
@angular-devkit/schematics        8.3.6
@angular/cli                      8.3.6
@ngtools/webpack                  8.3.6
@schematics/angular               8.3.6
@schematics/update                0.803.6
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2
</pre>

**Comment by atscott** [comment] 2019-11-12 23:47
Appears to be a duplicate of #12842

**Closed by atscott** 2019-11-12 23:47 UTC
Labels: comp: router
