### ISSUE TITLE
How to invoke angular element methods

### ISSUE THREAD

**Issue by CSantosM** [angular/angular#24898] opened 2018-07-16 10:41 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

I have created a Angular web component with Angular 6 Elements. When I embed it in another website, I select the web component with `var myComponent = document.querySelector('my-component');` (JQuery). I am trying invoke to web component methods on this way: `myComponent.sayHello();` But I can't do that.
There are any solution?
The web component only allows us to send inputs and to receive outputs??

## Environment

<pre><code>
Angular version: 6.0.9

Browser:
- [X] Chrome (desktop) version 67
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.11.2  
- Platform:  Linux 

Others:

</code></pre>

**Comment by trotyl** [comment] 2018-07-16 10:58
Duplicate of https://github.com/angular/angular/issues/22114

**Comment by CSantosM** [comment] 2018-07-16 11:21
Thank you @trotyl

**Comment by IgorMinar** [comment] 2018-07-26 22:43
closing in favor of #22114

**Closed by IgorMinar** 2018-07-26 22:43 UTC
