### ISSUE TITLE
Can't resolve all parameters for Location: (?, ?)

### ISSUE THREAD

**Issue by Trojaner** [angular/angular#34526] opened 2019-12-21 11:35 UTC
# 🐞 bug report

### Affected Package
@angular/router
(might be caused by other packages)

### Is this a regression?
Yes, worked fine before upgrading to Angular 9

### Description
When serving with Angular Universal and opening the site, I get an error

## 🔥 Exception or Error
<pre><code>
Error: Can't resolve all parameters for Location: (?, ?).
    at syntaxError (C:\Users\troja\source\repos\XXXX\frontend\dist\server.js:53191:17)
    at CompileMetadataResolver._getDependenciesMetadata (C:\Users\troja\source\repos\XXXX\frontend\dist\server.js:72866:35)
    at CompileMetadataResolver._getTypeMetadata (C:\Users\troja\source\repos\XXXX\frontend\dist\server.js:72758:26)
    at CompileMetadataResolver._getInjectableTypeMetadata (C:\Users\troja\source\repos\XXXX\frontend\dist\server.js:72982:21)
    at CompileMetadataResolver.getProviderMetadata (C:\Users\troja\source\repos\XXXX\frontend\dist\server.js:72991:22)
    at C:\Users\troja\source\repos\XXXX\frontend\dist\server.js:72929:49
    at Array.forEach (<anonymous>)
    at CompileMetadataResolver._getProvidersMetadata (C:\Users\troja\source\repos\XXXX\frontend\dist\server.js:72888:19)
    at C:\Users\troja\source\repos\XXXX\frontend\dist\server.js:72890:23
    at Array.forEach (<anonymous>)
</code></pre>

Debugging the related server js code shows that this happens inside the RouterModule:
![grafik](https://user-images.githubusercontent.com/1809172/71307129-c0b36580-23fa-11ea-9e32-fb9be61460a4.png)

...when resolving the [Location service](https://github.com/angular/angular/blob/master/packages/common/src/location/location.ts#L68):
![grafik](https://user-images.githubusercontent.com/1809172/71307145-11c35980-23fb-11ea-8bac-2d1cc619834d.png)

So it seems like it can not resolve LocationStrategy and PlatformLocation

## 🔬 Minimal Reproduction
Repro Repository: https://github.com/Trojaner/Angular34526Repro

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.0.0-rc.7
Node: 12.7.0
OS: win32 x64

Angular: 9.0.0-rc.7
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-rc.7
@angular-devkit/build-angular     0.900.0-rc.7
@angular-devkit/build-optimizer   0.900.0-rc.7
@angular-devkit/build-webpack     0.900.0-rc.7
@angular-devkit/core              9.0.0-rc.7
@angular-devkit/schematics        9.0.0-rc.7
@ngtools/webpack                  9.0.0-rc.7
@nguniversal/common               9.0.0-next.13
@nguniversal/express-engine       9.0.0-next.13
@schematics/angular               9.0.0-rc.7
@schematics/update                0.900.0-rc.7
rxjs                              6.5.3
typescript                        3.6.4
webpack                           4.41.2
</code></pre>

**Comment by Trojaner** [comment] 2019-12-22 17:12
As a side note, this issue only occurs in combination with angular universal. It does not happen when using `ng serve` instead.

**Comment by MitchTalmadge** [comment] 2019-12-23 07:51
I had the same unhelpful error with Angular 8 and though our setups are very different, I added 

```
import 'core-js/es';
import 'core-js/proposals/reflect-metadata'
```

to my polyfills and it fixed it somehow. I did that for yours and it did not solve the problem, however. :(

**Comment by bamminger** [comment] 2020-01-17 12:31
We had the same issue in Angular 8. The problematic package was @angular-devkit/build-angular. Keeping it at 0.803.0 fixed the issue in our case.

**Comment by alxhub** [comment] 2020-05-27 17:37
I'm going to close this as a duplicate of #35924. The root cause is the same - `CompilerFactory` is provided for the VE compiler in an Ivy-compiled app.

**Closed** 2020-05-27 17:37 UTC
Labels: comp: compiler, comp: router
