### ISSUE TITLE
Use [formArray]= notation optionally vs. formArrayName=

### ISSUE THREAD

**Issue by scottseeker** [angular/angular#16820] opened 2017-05-16 13:28 UTC
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I'm building a dynamic form generating module.  This module can create forms for any valid json structure including infinitely nested objects and arrays.

In order to accomplish this I've broken the display across multiple components: selector examples: my-form-control, my-form-group, my-form-array.  Building forms across multiple components requires that i use the [formGroup]= and [formControl]= syntax vs. formGroupName= and formControlName=.

This approach breaks at the FormArray class because there is no [formArray]= attribute available for use.

I have read about an approach using ControlContainer to resolve the formArrayName issue, but I could not find enough documentation to understand fully what was occuring and the approach seemed brittle (certain syntax in a template causes a 'no provider for ControlContainer' error).

**Expected behavior**

That I can bind a FormArray to any element using [formArray]=handleToFormArray

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

To make the various AbstractControls behave in the same manner.  I should have the same options for binding to template as group and control.

(Using push vs. addControl on FormArray feel inconsistent as well because I have to inspect classes to determine the correct method when building things dynamically).

**Please tell us about your environment:**

Windows 10, Visual Code, Node/NPM, Express
* **Angular version:** 2.0.X

4.0.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript

* **Node (for AoT issues):** `node --version` =

**Comment by rooby** [comment] 2022-02-24 06:55
This appears to be a duplicate of #30264
Although this issue is older, that one has a lot more activity.

**Comment by alex737876** [comment] 2022-10-15 17:44
Hello, just stumbled about 
https://stackoverflow.com/a/68068466
which is getting the parent via viewProviders. This way 'formArrayName' should work.

**Comment by rooby** [comment] 2022-10-15 20:02
@alex737876 see the conversation in https://github.com/angular/angular/issues/30264 for more information on scenarios where that is not a sufficient solution.

**Comment by rooby** [comment] 2022-10-15 20:06
I don’t have permission to close this issue, but it should be closed in favour of that linked issue.

**Comment by JeanMeche** [comment] 2024-11-24 23:28
Dupe of #30264

**Closed by JeanMeche** 2024-11-24 23:28 UTC
Labels: feature, freq2: medium, area: forms, feature: under consideration
