### ISSUE TITLE
viewProviders only available at depth of 1

### ISSUE THREAD

**Issue by AckerApple** [angular/angular#20005] opened 2017-10-29 12:08 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When attempting to (a)Host() inside a child component of a parent component, that **has the same** (a)Host() declaration as the parent, the child is causing a "No Provider Found".

## Expected behavior

That a super-parent component with a viewProviders declaration, will be provided to a child component **AND** to a child of that child.

## Minimal reproduction of the problem with instructions

Example made here : http://plnkr.co/edit/vY5ffsXEYSH5l13fx4Js

## What is the motivation / use case for changing the behavior?

GOAL: I have a form-control component who's template is one tag `<ng-content></ng-content>` and the template's class named FormControl, has a component declaration of `viewProviders=[FormControl]` which is assigning itself as the viewProvider. I then have FieldControl components with a `constructor( (a)Host() public FormControl:FormControl ){}` declaration and that FieldControl is expected to be used inside a FormControl as `<form-control><field-control></field-control></form-control>`. That all works correct IF FieldControl is visible with-in the same template as the FormControl. **BUT** if I have a sub component with-in a form-control as such `<form-control><some-component></some-component></form-control>` and **WITH OR WITHOUT** a constructor `(a)Host()` declaration on the sub component **AND** that sub component has a `<field-control></field-control>` with-in it => The field-control with-in a sub component, causes an error of "No provider found". 

## Environment

<pre><code>
Angular version: 4.4.6

Browser:
- [x] Chrome (desktop) version XX
- [x] Chrome (Android) version XX
- [x] Chrome (iOS) version XX
- [x] Firefox version XX
- [x] Safari (desktop) version XX
- [x] Safari (iOS) version XX
- [x] IE version XX
- [x] Edge version XX
 
For Tooling issues:
- Node version: 8.1.2  
- Platform:  Mac

Others:

</code></pre>

**Comment by AckerApple** [comment] 2017-10-29 12:27
My issue report was edit several times within only minutes of being submitted. I started with NO plunker example and then found may way into making one.

Great issue reporting control! Took me from no details into a ton of details and example

**Comment by eqbalsajadi** [comment] 2019-03-15 15:24
@AckerApple Hi.
I have exactly same problem
```
<table-comp>
<form-field></form-field>
<form-field></form-field>
..
</table-comp>
```

Inside table-comp:
```
<form-comp>
<ng-content></ng-content>
</form-comp>
```

FormComp injected into FormField cause No Provider Found error

**Comment by AckerApple** [comment] 2019-03-15 15:31
I have moved away from ViewProviders entirely.

To accomplish my goals, I moved to using regular providers with a slew of decorators such as: `@Optional()` `@SkipSelf()` and `@Host()`

In the end, and I remember it well, I ended up with the following code to do what was needed:
```
  constructor(
    public Fields:Fields,
    @Self() public Field:Field,
    @Self() AsParent:FieldParent,

    //if kids are used again, the @Host maybe wrong
    //If Host is to be changed, check schedule caregiver validations
    @Host() @Optional() @SkipSelf() public FieldParent:FieldParent
  ){
    AsParent.field = Field//ref to myself

  //if parent defined, then use it instead of my own providing
    if( FieldParent ){
      this.Field.FieldParent = FieldParent.field
    }
  }
```

**Comment by eqbalsajadi** [comment] 2019-03-15 20:56
Duplicate of #5126, #13761

**Closed** 2022-03-28 23:16 UTC
Labels: feature, comp: core, core: di, insufficient votes, votes required
