### ISSUE TITLE
Angular CLI (ng build) crashes on RedHat 8 - FIPS (using Jenkins)

### ISSUE THREAD

**Issue by garyhellman** [angular/angular#42576] opened 2021-06-15 14:24 UTC
# Bug Report

### Affected Package

 The issue is caused by package @angular/....

+ npm run build

> ang-app@0.0.1 build /services/sJenkin2/jenkins/workspace/lloader_Pipeline/src/main/front-end
> node --max_old_space_size=4096 node_modules/@angular/cli/bin/ng build

Error: error:060800C8:digital envelope routines:EVP_DigestInit_ex:**disabled for FIPS**
    at new Hash (internal/crypto/hash.js:33:18)
    at Object.createHash (crypto.js:101:10)
    at NgccConfiguration.computeHash (/services/sJenkin2/jenkins/workspace/lloader_Pipeline/src/main/front-end/node_modules/@angular/compiler-cli/ngcc/src/packages/configuration.js:253:29)
    at new NgccConfiguration (/services/sJenkin2/jenkins/workspace/lloader_Pipeline/src/main/front-end/node_modules/@angular/compiler-cli/ngcc/src/packages/configuration.js:129:30)
    at Object.mainNgcc (/services/sJenkin2/jenkins/workspace/lloader_Pipeline/src/main/front-end/node_modules/@angular/compiler-cli/ngcc/src/main.js:46:22)
    at /services/sJenkin2/jenkins/workspace/lloader_Pipeline/src/main/front-end/node_modules/@angular/compiler-cli/ngcc/main-ngcc.js:34:53
    at step (/services/sJenkin2/jenkins/workspace/lloader_Pipeline/src/main/front-end/node_modules/@angular/compiler-cli/node_modules/tslib/tslib.js:143:27)
    at Object.next (/services/sJenkin2/jenkins/workspace/lloader_Pipeline/src/main/front-end/node_modules/@angular/compiler-cli/node_modules/tslib/tslib.js:124:57)
    at /services/sJenkin2/jenkins/workspace/lloader_Pipeline/src/main/front-end/node_modules/@angular/compiler-cli/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
An unhandled exception occurred: NGCC failed.
See "/tmp/ng-ehiofk/angular-errors.log" for further details.
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! ang-app@0.0.1 build: `node --max_old_space_size=4096 node_modules/@angular/cli/bin/ng build`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the ang-app@0.0.1 build script.

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description
 A clear and concise description of the problem...
ng build - ngcc  fails on a FIPS enabled OS (RedHat 8) - the error says "disabled for FIPS"

How to get ng build (or ngcc) to run on a FIPS machine? Do we need to build our own version of Angular...? (with all MD5 replaced by maybe SHA256?)

## Minimal Reproduction

 https://stackblitz.com/...

## Exception or Error
<pre><code>

</code></pre>

## Your Environment

**Angular Version:**
<pre><code>

+ @angular/cli@11.2.14
</code></pre>

**Anything else relevant?**

RedHat 8, RHEL8, Jenkins

**Comment by gkalpak** [comment] 2021-06-15 18:08
This looks like a duplicate of #42577. (Closing this one, since #42577 has more discussion/context.)

**Closed by gkalpak** 2021-06-15 18:08 UTC

**Comment by garyhellman** [comment] 2021-06-16 17:04
Ok - Thanks George!
