### ISSUE TITLE
/deep/, >>>, and ::ng-deep will be deprecated. Any alternative?

### ISSUE THREAD

**Issue by sdns** [angular/angular#29765] opened 2019-04-08 12:03 UTC
As [docs](https://angular.io/guide/component-styles#deprecated-deep--and-ng-deep) say `/deep/`, `>>>`, and `::ng-deep` will be deprecated, so what's the alternative?

Here is the problem:
I have a component.
```HTML
<app-mycomp>
    <h2>Some Text...</h2>
</app-mycomp>
```
**mycomp.component.html**:
```HTML
<div class="title">
    <ng-content></ng-content>
</div>
```
I need to style `h2` in **mycomp.component.css** (not in other files)
```CSS
h2{ margin: 0px;}
```
But it is not working because of encapsulation, so I used `::ng-deep`:
```CSS
::ng-deep h2{margin: 0px;}
```
but the docs say `::ng-deep` will be deprecated. what's the alternative?

**Comment by Airblader** [comment] 2019-04-08 14:02
Duplicate of #17867 and #25160

**Comment by JoostK** [comment] 2019-04-09 20:32
Thanks for reporting this issue. However this issue is a duplicate of an existing issue #25160. Please subscribe to that issue for future updates.

Thanks @Airblader for linking the duplicates.

**Closed by JoostK** 2019-04-09 20:32 UTC
