### ISSUE TITLE
Angular Form Input of type password is memory leaking

### ISSUE THREAD

**Issue by andreirosucojocaru** [angular/angular#45650] opened 2022-04-15 19:09 UTC
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

No

### Description

I have an Angular application (with Angular Material) that has a simple form with 2 inputs, one of type text and one of type password.

Because of the input of type password, the whole component is memory leaking. 

When changing its type back to text, the component is cleaned from the memory.

For testing purposes, I have created a simple application on StackBlitz, that navigates from a regular authentication component (with an input field of type text and another one of type password) to an authentication component with two input fields of type text, to a main component and back to the first component.

After repeating this process several times and profiling the application, it can be noticed the component with an input field of type password has a number of instances in the memory equal to the number of iterations through the application:

![angular-ivy-3ecxdf stackblitz io_auth-memory-leak](https://user-images.githubusercontent.com/6643975/163622693-f670f8a1-5e8f-4abf-8fd7-f7a732fe798f.png)

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-3ecxdf

### Please provide the exception or error you saw

```true
No exception or error is thrown.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 12.2.13
Node: 16.14.2 (Unsupported)
Package Manager: npm 8.6.0
OS: win32 x64

Angular: 12.2.13
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.13
@angular-devkit/build-angular   12.2.13
@angular-devkit/core            12.2.13
@angular-devkit/schematics      12.2.13
@angular/cdk                    12.2.12
@angular/material               12.2.12
@schematics/angular             12.2.13
rxjs                            6.6.7
typescript                      4.3.5
```

### Anything else?

Related issues: #37598, #37952, #20007.

**Comment by JoostK** [comment] 2022-04-18 14:18
This does not appear to reproduce for me in Chrome 100.0.4896.88 (macOS, amd64). The number of DOM nodes does increase while repeatedly toggling that button, but a garbage collection cycle consistently drops back to the original number of DOM nodes.

**Comment by andreirosucojocaru** [comment] 2022-04-18 17:42
The problem does not seem to reproduce indeed on MacOS. After multiple iterations through the application, there are only 2 instances of the AuthMemoryLeakComponent in the memory (which is still a memory leak, but perhaps the garbage collector will dispose those components at a later time).

However, the problem reproduces on Windows 10, using Chrome 100.0.4896.88.

Please see the attached movie for reproduction steps.

https://user-images.githubusercontent.com/6643975/163849309-bb997a87-05df-4a45-8885-8a54f3f0047f.mp4

**Comment by JoostK** [comment] 2022-04-18 17:50
That seems like a browser leak to me, unrelated to Angular in that case.

**Comment by jessicajaniuk** [comment] 2022-04-27 14:43
One suggestion was to potentially try running these tests again with all browser extensions disabled just to confirm that it's not related to one of those extensions looking at password fields, like a password manager. It's a behavior we've seen before.

**Comment by andreirosucojocaru** [comment] 2022-04-28 15:33
Strange enough, with all my Chrome extensions disabled, the problem still occurs, but to a lesser extent. The number of the components in the memory is lower than the number of iterations, but it is still always greater than 1.
![image](https://user-images.githubusercontent.com/6643975/165789406-a0ec6915-24b7-4ba5-9d36-6fce489a8080.png)
![image](https://user-images.githubusercontent.com/6643975/165789479-3d71f638-b19a-4a61-9a80-144282180e98.png)

**Comment by kraph** [comment] 2022-05-10 08:29
I have had the same issue. After enabling verbose console log in dev tools -> Console -> log level (next to filter) -> enable Verbose, I saw that chrome throws some warnings if one does not follow all their rule sets when using< input type="password">. This warning keeps a reference to my app page and never gets deleteted unless I clear the console log.
I managed to fix this by adding a <form> element and changing placeholder to autocomplete. Maybe there is also a way to disable external warnings.

**Comment by alxhub** [comment] 2022-06-06 23:10
Unfortunately this is not a bug we can fix on the Angular side, as this appears to be an issue with a specific browser and element type (probably autofill or some built in browser password manager?). In any case, there's very little we can do in Angular to address this, so I'm going to close this issue. I suggest filing a bug report against [Chrome](https://bugs.chromium.org/p/chromium/issues/list).

**Closed by alxhub** 2022-06-06 23:10 UTC
Labels: needs reproduction, comp: forms
