### ISSUE TITLE
ngc with `strictMetadataEmit: true` error on `@inject()` with generic type.

### ISSUE THREAD

**Issue by ghetolay** [angular/angular#23395] opened 2018-04-16 13:28 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

When you inject a token with `@Inject()` and generic type, compiling with `strictMetadataEmit: true` causes the following error: 

> Metadata collected contains an error that will be reported at runtime: Could not resolve type XXX

I'm using `Partial<T>` so at first I thought this was related to typescript built-in types but I created myself an `export type Optional<T>` and still got the same error.

## Expected behavior

No error.

## Minimal reproduction of the problem with instructions

```ts
export interface Setting {
   a: string;
}

export const SETTING = new InjectionToken<Partial<Setting>>('');

export class Foo {
  constructor(@Inject(SETTING) setting: Partial<Setting>){ } 
}
```

## What is the motivation / use case for changing the behavior?

I'm building a lib where user can inject some settings. They're all optional as missing ones will be filled with default values.

## Environment

<pre><code>
Angular version: 5.2.0

</code></pre>

**Comment by trotyl** [comment] 2018-04-16 17:02
Duplicate of https://github.com/angular/angular/issues/20351

**Comment by ghetolay** [comment] 2018-04-16 19:55
Maybe I don't get what ambient means. Like said in the original post even if I created my own `Partial` mapped type it doesn't work.

Anyway I could easily workaround it so I'm not really worried by this. 
Feel free to close it if this reports doesn't help.

**Comment by alfaproject** [comment] 2018-05-13 22:04
Just got hit by this. ):

**Comment by waterplea** [comment] 2019-02-27 14:49
Will `@Inject(DOCUMENT) documentRef: Document,` ever be supported without `@dynamic`? This seems to be the one opened issue related to this case.

**Comment by CSchulz** [comment] 2019-05-10 14:10
I also need `@dynamic` with Angular 7.2 for following type:

```
export type InputMaskProviderType = InputMaskProvider | (() => InputMaskProvider | null);
export const INPUT_MASK_PROVIDER = new InjectionToken<InputMaskProviderType>('inputMaskProvider');

export interface InputMaskProvider {
  config: string | undefined;
}
```

**Comment by JoostK** [comment] 2020-03-17 23:51
This is no longer an issue with Ivy in Angular 9.0.

**Closed by JoostK** 2020-03-17 23:51 UTC
Labels: comp: compiler, fixed by Ivy, freq1: low, severity2: inconvenient, type: bug/fix
