### ISSUE TITLE
build result with "Warning in" and empty/null string.

### ISSUE THREAD

**Issue by magicdict** [angular/angular#38092] opened 2020-07-16 08:26 UTC
# 🐞 bug report

### Affected Package

 
Unknown

### Is this a regression?

 
Only In lastest version

### Description

 A clear and concise description of the problem...
![image](https://user-images.githubusercontent.com/897796/87645631-58eeae80-c780-11ea-9c23-332f2f864c45.png)

WARING In + Null....
## 🔬 Minimal Reproduction

 https://stackblitz.com/...

## 🔥 Exception or Error
<pre><code>

Nothing
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular/cli  10.0.3
Angular/core 10.0.4
</code></pre>

**Anything else relevant?**

**Comment by petebacondarwin** [comment] 2020-07-16 08:27
Duplicate of #38019.

**Closed by petebacondarwin** 2020-07-16 08:27 UTC
