### ISSUE TITLE
Form input fields content doesn't reset after destroy on submit

### ISSUE THREAD

**Issue by IHateGlamour** [angular/angular#7146] opened 2016-02-18 08:07 UTC
This problem is somehow similar to this question: http://stackoverflow.com/questions/35057430/angular2-file-input-control-label-keeps-its-state-after-destroying-component , but the problem is when you have a form in a ngSwitch or any other structural directive, after submit the form fields won't reset after being removed from the DOM.
You can take this plunker as an example: http://plnkr.co/edit/endZrd9PzHW3pC5KaMk6
the template looks like this:
```
<form *ngIf="isActive" [ngFormModel]="form" (ngSubmit)="onSubmit()">
           ...
</form>
```
After the submit if we hide and show the form, the text input will have the same value. One way is to rebuild the form onSubmit(check the "Rebuild form on submit"):
`this.form = this._formBuilder.group({
      "comment": new Control()
    })`
but after this we will have to hide and show the form, or it will insert null no matter what you type in (probably to rebind the input to the new control).

**Comment by danrub** [comment] 2016-02-29 06:42
same issue with angular 2 beta 7.

I think, the issue is within the the addControl method that is called once, when ngControl directive is initialized.
The method call the setUpControl method that accepts as a parameter the actual Control that it is bound to.
When the ngChanges triggered on form model update, this control is not updated to the new one, so the model now out of sync, cause the valueAccessor inside setUpControl, is calling the updateValue/markAsDirty method of invalid control object (old one)

suggestion: the setUpControl should be called again for each registered directive, on ngOnChanges "form" update

**Comment by zoechi** [comment] 2016-02-29 07:14
dup of #4933  
see also #7288

**Comment by danrub** [comment] 2016-02-29 08:10
while issue #4933 is opened.

I'm using this hack, to solve my problem with resetting dirty states on Control.

As the only way to reset Control is by regenerate and assign it again to NgFormModel
I have created a directive, that re-register all NgControls directives known to NgFormModel.

`@Directive({
    selector: '[ngFormModel]'

})
class NgFormModel_Fix7146 implements OnChanges {

    @Input("ngFormModel") model: AbstractControl;

    constructor(private _form: NgFormModel) {

    }

    ngOnChanges(changes: { [key: string]: SimpleChange }) {

        if (changes["model"]) {

            let directives = _.clone(this._form.directives); // using lodash library to clone directives array before manipulation

            for (var index in directives ) {

                let directive = directives [index];

                if (directive instanceof NgControl) {
                    this._form.removeControl(directive);
                    this._form.addControl(directive);
                }
            }

        }
    }
}`

**Comment by PascalPrecht** [comment] 2016-03-04 14:53
@danrub can we close this as dup in favour of #4933 ?

**Comment by kara** [comment] 2016-05-23 18:08
Closing as a dupe of #4933. Thanks for reporting!

**Closed by kara** 2016-05-23 18:08 UTC
