### ISSUE TITLE
input element with ngModel initialized as null, fires "input" event on focus and blur in IE 

### ISSUE THREAD

**Issue by himajasuman** [angular/angular#17951] opened 2017-07-06 06:42 UTC
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[x] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

input element with ngModel initialized as null, fires "input" event on focus and blur for empty(null) value

## Expected behavior

Tested it with plain input element with "input" eventListener in IE, it isn't firing "input" events for above scenario. So, I assume it isn't an IE bug. "input" event (and consecutive onChange/ngModelChange) should not be fired on focus and blur.

## Minimal reproduction of the problem with instructions

https://plnkr.co/edit/q9TgF9btZKquDjJuKDVz?p=preview

https://jsfiddle.net/xry2Ltbn/4/ is an example with simple input element with input eventListener

## Please tell us about your environment

<pre><code>
Angular version: 4.2.4

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [x] IE version 11
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX 
- Platform: 

Others:

</code></pre>

**Comment by kara** [comment] 2018-01-03 00:02
@himajasuman If this is still an issue, can you provide a **minimal** repro case? The one you linked to has a number of components, and it's not clear which one you are looking at.

**Comment by forever14k** [comment] 2018-01-12 15:18
@kara here is minimal reproduction: http://plnkr.co/edit/4cIdOVToP1J5HWmIvAf9?p=preview
Expected behavior: both forms pristine
Current behavior: first form is dirty and second is pristine

This bug affects only Internet Explorer 10+, more detailed comment here: https://github.com/angular/angular/issues/14440#issuecomment-350812348

**Comment by uvv001** [comment] 2018-03-28 12:04
Catch this behaviour in search field on my project.

**Comment by vlad** [comment] 2018-05-25 21:49
This might be considered a duplicate of https://github.com/angular/angular/issues/15299.  It has a link to https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/101220/ which points to a plunkr example that shows other events (like focus, click) are fired on input when the placeholder is set.

Similarly, this issue #17951 describes the same problem, and the example has a placeholder= set, too.

**Comment by AndrewKushnir** [comment] 2022-03-01 00:26
Closing this ticket, since the reported problem was only present in IE11 and Angular no longer supports IE.

**Closed by AndrewKushnir** 2022-03-01 00:26 UTC
Labels: type: bug/fix, freq2: medium, comp: forms, state: confirmed, browser: ie 11, triage #1, P3
