### ISSUE TITLE
Ugraded to Angular 9: Error: Can't resolve all parameters for ApplicationModule: (?).

### ISSUE THREAD

**Issue by btakita** [angular/angular#35924] opened 2020-03-07 02:04 UTC
I upgraded my app to Angular 9 & am getting the following error:

```
Error: Can't resolve all parameters for ApplicationModule: (?).
    at syntaxError (/home/brian/work/dishzilla/menus-angular-2-app/apps/angular-app/dist/server.js:7582:17)
    at CompileMetadataResolver._getDependenciesMetadata (/home/brian/work/dishzilla/menus-angular-2-app/apps/angular-app/dist/server.js:27327:35)
    at CompileMetadataResolver._getTypeMetadata (/home/brian/work/dishzilla/menus-angular-2-app/apps/angular-app/dist/server.js:27219:26)
    at CompileMetadataResolver.getNgModuleMetadata (/home/brian/work/dishzilla/menus-angular-2-app/apps/angular-app/dist/server.js:27087:24)
    at CompileMetadataResolver.getNgModuleSummary (/home/brian/work/dishzilla/menus-angular-2-app/apps/angular-app/dist/server.js:26889:35)
    at /home/brian/work/dishzilla/menus-angular-2-app/apps/angular-app/dist/server.js:27008:51
    at Array.forEach (<anonymous>)
    at CompileMetadataResolver.getNgModuleMetadata (/home/brian/work/dishzilla/menus-angular-2-app/apps/angular-app/dist/server.js:26996:49)
    at CompileMetadataResolver.getNgModuleSummary (/home/brian/work/dishzilla/menus-angular-2-app/apps/angular-app/dist/server.js:26889:35)
    at /home/brian/work/dishzilla/menus-angular-2-app/apps/angular-app/dist/server.js:26981:55
```

I have spent hours debugging this issue, but still have not made progress. I've also seen a number of fixes for this error message in previous years but none of those solutions worked for me. Can you please advise on obtaining a better error message that is easier to debug, because this error message is not very helpful. Thank you

**Comment by AndrewKushnir** [comment] 2020-03-07 02:58
Hi @btakita, 

Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Could you please provide a minimum repro in a form of GitHub repository, so that we can help look into this issue?

Based on the error message, it looks like you use View Engine. Have you tried switching to Ivy to see if your app works and/or there are some additional error diagnostics messages produced?

Thank you.

**Comment by alfaproject** [comment] 2020-03-07 10:44
I'm using Ivy and I'm getting the exact same error. I actually had to disable build optimizer to even get this far.

Sadly, I can't share our source code and it's a very large application so I haven't been able to get a minimal repro and after spending almost a week trying to update to Angular 9 and Ivy I'm on the verge of giving up. It just does not warrant all of these company resources for an upgrade. ):

**Comment by AndrewKushnir** [comment] 2020-03-07 18:36
Hi @alfaproject,

If the same problem happens with Ivy, that might indicate that some dependencies that were used in a constructor of a Component/Directive/NgModule/Pipe, don't have Angular top-level decorators (`@Injectable`, `@Component` or `@Directive`) or were inherited from classes that don't have these decorators (but have some dependencies in a constructor). As a possible next step, you can try to identify a dependency that is causing the problem (by removing dependencies from the constructor until the problem goes away). Once this dependency is found, check if this dependency and all its parents (where it make sense) have Angular decorators.

Also as a possible workaround, you can try fetching that dependency from the Injector directly, for example:

```
import {Injector} from '@angular/core';
import {ServiceA} from './service-a';

@Component({
  // ... 
})
class MyComp {
  constructor(private injector: Injector) {
     const serviceA = injector.get(ServiceA);
  }
}
```

Please let me know if it helps.

Thank you.

**Comment by btakita** [comment] 2020-03-07 22:42
@AndrewKushnir Unfortunately, I cannot provide a simple reproduction due to the complexity of the app. I added some logging statements & noticed that when `_ownParameters` is invoked on `ApplicatiuonModule`, the logic falls through to the `If a class has no decorators, at least create metadata` case. `[ undefined ]` is returned since the constructor has an arity of 1.

https://github.com/angular/angular/blob/master/packages/core/src/reflection/reflection_capabilities.ts#L123

Something odd I noticed in the compiled output is that `ReflectionCapabilities.prototype._ownParameters` is defined mulitple times.

**Comment by btakita** [comment] 2020-03-08 00:34
I followed the directions in https://angular.io/guide/ivy & switched the `angular.json` configuration `"aot": true`. Still have the same error...

**Comment by danielboggianosa** [comment] 2020-03-08 17:21
Hi, I had the same problem because I was trying to import a Module which would declare a specific set of components. One of those components had a <router-outlet> tag.
What I did was import RouterModule on the external module, like this:
`@NgModule({
    declarations:[
        AlertsComponent,
        FooterComponent,
        LogoutComponent,
        MessageComponent,
        SearchComponent,
        SidebarComponent,
        TopbarComponent,
        UserInfoComponent,
        LayoutComponent,
    ],
    imports:[RouterModule]
})
export class LayoutModule {}`

then I imported the module on the app.module.ts
`@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    AppRoutingModule,
    BrowserModule,
    LayoutModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }`,

Now it's working

**Comment by alxhub** [comment] 2020-03-10 22:26
Hello @btakita, @alfaproject,

Some questions for you both:

1) What's your environment? View Engine / Ivy? JIT / AOT?
2) Try serving with `ng serve --aot` and report the exact stack trace at runtime.

Since this is a JIT error, I'd be surprised to see it on an AOT application. Let's figure out what exactly is happening there first.

3) Can you scan `node_modules` and make sure there aren't multiple installed versions of Angular, which I've seen cause similar errors in the past.

**Comment by btakita** [comment] 2020-03-17 18:40
The issue occurs when I run `node dist/server`

`ng serve` does not have that problem.

**Comment by btakita** [comment] 2020-03-19 04:22
@alxhub There's only one version of `@angular/core` & related libraries in `yarn.lock` & in `node_modules`.

**Comment by btakita** [comment] 2020-03-26 01:47
Is there anything that can be done to get around this issue? The project is dead in the water until this can be resolved...I thought Angular was a mature & safe framework...

**Comment by petebacondarwin** [comment] 2020-03-26 15:52
Does running `node dist/server` mean that you are using Server-side rendering (SSR) for this project?

**Comment by btakita** [comment] 2020-03-26 17:21
Yes. We are using SSR. Using the JITReflector.

https://github.com/angular/angular/blob/fc3e5cb6d3ef61aaa13bd9788b9b1c7b97af94fe/packages/compiler/src/metadata_resolver.ts#L917

```ts
this._reflector.parameters(typeOrFunc)
```

is returning nothing

**Comment by btakita** [comment] 2020-03-26 23:12
My current plan is to use the ganatan/angular-example-ssr menus repo as a base & then introduce our app logic.

```shell
npx degit ganatan/angular-example-ssr menus
```

I'm also going to utilize lernajs to break up the repo into a monorepo of private npm packages.

**Comment by IamDeshRaj** [comment] 2020-05-16 13:03
Hi @btakita, @petebacondarwin, @alxhub @danielboggianosa, @AndrewKushnir..
I have reproduced this error while trying to solve [another issue](https://github.com/expressjs/express/issues/4278), clone [my repository](https://github.com/IamDeshRaj/myPleaks) and checkout branch **app-module-error**, and 
run commands 1. **npm install** and 2. **npm run local:serverless**
URL like "**http://localhost:3000/production**" will flash on the console as shown in the snapshot below. Then I hope rest you will people will figure out, I'm really new to Angular and node, Struggling badly with both, this and [another issue](https://github.com/expressjs/express/issues/4278).

![image](https://user-images.githubusercontent.com/6917620/82120430-9bf1cd00-97a3-11ea-9d01-d8c3fa4a9ea1.png)

Thanks in advance.

**Comment by alxhub** [comment] 2020-05-26 23:56
@IamDeshRaj, you rock!

The root cause here is that `platformServer()` (and `platformBrowserDynamic` for that matter) expose a platform injector that provides `CompilerFactory` with `JitCompilerFactory`, which creates a View Engine compiler. Obviously that's not going to work in an Ivy app!

It turns out that `ngExpressEngine` relies on `CompilerFactory`, which is why it shows up as an SSR bug. 

Once the application is created, it has a `Compiler` which is overridden in Ivy, which makes sense, but the `CompilerFactory` at the platform level should _also_ be overridden. It should be a pretty straightforward fix.

**Comment by alxhub** [comment] 2020-05-27 17:39
Tracking as [FW-2197](https://angular-team.atlassian.net/browse/FW-2197) internally.

**Comment by airasyaqub** [comment] 2020-06-11 19:09
I got the same error with angular 9 SSR. I have made little structural changes in ts-config and web-pack config because I need my bundler to output server.js (compiled version of server.ts) at root. To validate if its a global problem or due to my structural changes I have set up a test project with angular universal SSR. It all works in test project. Still trying to find the culprit. My project is now stuck due this bug. Please can anyone help me out with it. I'll put my file references on demand.

**Comment by raitisbe** [comment] 2020-06-11 21:53
For me what solved it was adding `"emitDecoratorMetadata": true` under compilerOptions in tsconfig.json.

**Comment by airasyaqub** [comment] 2020-06-13 11:13
I wanted to change my dist output files structure for this reason I have included my own webpack config which outputs the server file at root as 'server.js'. It compiles all good but serving it give me the error.
 
![error](https://user-images.githubusercontent.com/30695220/84567204-8c5ca880-ad90-11ea-8e47-2928f07174ca.PNG)

If i put "import 'reflect-metadata';" up top in server.ts file error changes to

![error2](https://user-images.githubusercontent.com/30695220/84567237-c168fb00-ad90-11ea-8567-3348e72eeb8a.PNG)


 Here is my code if someone want to look into it
```
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "newProjectRoot": "projects",
  "projects": {
    "test-app": {
      "projectType": "application",
      "schematics": {
        "@schematics/angular:component": {
          "style": "scss"
        }
      },
      "root": "",
      "sourceRoot": "src",
      "prefix": "app",
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "dist/test-app",
            "index": "src/index.html",
            "main": "src/main.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "src/tsconfig.app.json",
            "aot": true,
            "assets": [
              "src/favicon.ico",
              "src/assets"
            ],
            "styles": [
              "src/styles.scss"
            ],
            "scripts": []
          },
          "configurations": {
            "production": {
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true,
              "budgets": [
                {
                  "type": "initial",
                  "maximumWarning": "2mb",
                  "maximumError": "5mb"
                },
                {
                  "type": "anyComponentStyle",
                  "maximumWarning": "6kb",
                  "maximumError": "10kb"
                }
              ]
            }
          }
        },
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "browserTarget": "test-app:build"
          },
          "configurations": {
            "production": {
              "browserTarget": "test-app:build:production"
            }
          }
        },
        "extract-i18n": {
          "builder": "@angular-devkit/build-angular:extract-i18n",
          "options": {
            "browserTarget": "test-app:build"
          }
        },
        "test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "main": "src/test.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "tsconfig.spec.json",
            "karmaConfig": "karma.conf.js",
            "assets": [
              "src/favicon.ico",
              "src/assets"
            ],
            "styles": [
              "src/styles.scss"
            ],
            "scripts": []
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": [
              "tsconfig.app.json",
              "tsconfig.spec.json",
              "e2e/tsconfig.json"
            ],
            "exclude": [
              "**/node_modules/**"
            ]
          }
        },
        "e2e": {
          "builder": "@angular-devkit/build-angular:protractor",
          "options": {
            "protractorConfig": "e2e/protractor.conf.js",
            "devServerTarget": "test-app:serve"
          },
          "configurations": {
            "production": {
              "devServerTarget": "test-app:serve:production"
            }
          }
        },
        "server": {
          "builder": "@angular-devkit/build-angular:server",
          "options": {
            "outputPath": "dist/server",
            "main": "server.ts",
            "tsConfig": "src/tsconfig.server.json"
          },
          "configurations": {
            "production": {
              "outputHashing": "media",
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ],
              "sourceMap": false,
              "optimization": true
            }
          }
        },
        "serve-ssr": {
          "builder": "@nguniversal/builders:ssr-dev-server",
          "options": {
            "browserTarget": "test-app:build",
            "serverTarget": "test-app:server"
          },
          "configurations": {
            "production": {
              "browserTarget": "test-app:build:production",
              "serverTarget": "test-app:server:production"
            }
          }
        },
        "prerender": {
          "builder": "@nguniversal/builders:prerender",
          "options": {
            "browserTarget": "test-app:build:production",
            "serverTarget": "test-app:server:production",
            "routes": [
              "/"
            ]
          },
          "configurations": {
            "production": {}
          }
        }
      }
    }
  },
  "defaultProject": "test-app",
  "cli": {
    "analytics": "139ecb14-cb02-452b-937c-211be673eb8d"
  }
}
```
my package.json

```
{
  "name": "test-app",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "dev:ssr": "ng run test-app:serve-ssr",
    "serve:ssr": "node dist/test-app/server/main.js",
    "build:ssr": "ng build --prod && ng run test-app:server:production && npm run webpack:server",
    "webpack:server": "webpack --config webpack.server.config.js --progress",
    "prerender": "ng run test-app:prerender"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~9.1.9",
    "@angular/common": "~9.1.9",
    "@angular/compiler": "~9.1.9",
    "@angular/core": "~9.1.9",
    "@angular/forms": "~9.1.9",
    "@angular/platform-browser": "~9.1.9",
    "@angular/platform-browser-dynamic": "~9.1.9",
    "@angular/platform-server": "~9.1.9",
    "@angular/router": "~9.1.9",
    "@nguniversal/express-engine": "^9.1.1",
    "express": "^4.15.2",
    "rxjs": "~6.5.4",
    "ts-loader": "^7.0.5",
    "tslib": "^1.10.0",
    "webpack-node-externals": "^1.7.2",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.901.7",
    "@angular/cli": "~9.1.7",
    "@angular/compiler-cli": "~9.1.9",
    "@nguniversal/builders": "^9.1.1",
    "@types/express": "^4.17.0",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^12.11.1",
    "codelyzer": "^5.1.2",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~5.0.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~2.1.0",
    "karma-jasmine": "~3.0.1",
    "karma-jasmine-html-reporter": "^1.4.2",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~3.8.3",
    "webpack-cli": "^3.3.11"
  }
}
```

my tsconfig.app.json

```
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "./out-tsc/app",
    "types": []
  },
  "files": [
    "main.ts",
    "polyfills.ts"
  ],
  "include": [
    "**/*.d.ts"
  ]
}
```
my tsconfig.server.json

```
{
  "extends": "./tsconfig.app.json",
  "compilerOptions": {
    "outDir": "./out-tsc/app-server",
    "module": "commonjs",
    "types": [
      "node"
    ]
  },
  "files": [
    "main.server.ts",
    "../server.ts"
  ],
  "angularCompilerOptions": {
    "entryModule": "app/app.server.module#AppServerModule"
  }
}
```

my tsconfig.spec.json

```
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "./out-tsc/spec",
    "types": [
      "jasmine",
      "node"
    ]
  },
  "files": [
    "test.ts",
    "polyfills.ts"
  ],
  "include": [
    "**/*.spec.ts",
    "**/*.d.ts"
  ]
}
```
my tslint.json

```
{
	"extends": "../tslint.json",
	"rules": {
		"directive-selector": [
			true,
			"attribute",
			"app",
			"camelCase"
		],
		"component-selector": [
			true,
			"element",
			"app",
			"kebab-case"
		]
	}
}
```

my webpack config

```
const path = require('path');
const webpack = require('webpack');
const nodeExternals = require('webpack-node-externals');

module.exports = {
	entry: { server: './server.ts' },
	resolve: {
		extensions: ['.js', '.ts'],
		alias: {
			'main.server': path.join(__dirname, `server`, 'main.js')
		}
	},
	target: 'node',
	mode: 'production',
	// this makes sure we include node_modules and other 3rd party libraries
	externals: [/(node_modules|main\..*\.js)/, nodeExternals()],
	output: {
		path: path.join(__dirname),
		filename: '[name].js',
		library: 'server',
		libraryTarget: 'umd'
	},
	module: {
		rules: [
			{ test: /\.ts$/, loader: 'ts-loader' },
			{
				test: /(\\|\/)@angular(\\|\/)core(\\|\/).+\.js$/,
				parser: { system: true }
			}
		]
	},
	plugins: [
		// Temporary Fix for issue: https://github.com/angular/angular/issues/11580
		// for "WARNING Critical dependency: the request of a dependency is an expression"
		new webpack.ContextReplacementPlugin(
			/(.+)?angular(\\|\/)core(.+)?/,
			path.join(__dirname, 'src'), // location of your src
			{} // a map of your routes
		),
		new webpack.ContextReplacementPlugin(
			/(.+)?express(\\|\/)(.+)?/,
			path.join(__dirname, 'src'),
			{}
		)
	]
}
```

my server.ts

```
import 'zone.js/dist/zone-node';


import { ngExpressEngine } from '@nguniversal/express-engine';
import * as express from 'express';
import { join } from 'path';

import { AppServerModule } from './src/main.server';
import { APP_BASE_HREF } from '@angular/common';
import { existsSync } from 'fs';

// The Express app is exported so that it can be used by serverless Functions.
export function app() {
  const server = express();
  const distFolder = join(process.cwd(), 'dist/test-app');
  const indexHtml = existsSync(join(distFolder, 'index.html')) ? 'index.html' : 'index';


  console.log ('distFolder ==>', distFolder);
  console.log ('indexHtml ==>', indexHtml);

  // Our Universal express-engine (found @ https://github.com/angular/universal/tree/master/modules/express-engine)
  server.engine('html', ngExpressEngine({
    bootstrap: AppServerModule,
  }));

  server.set('view engine', 'html');
  server.set('views', distFolder);

  // Example Express Rest API endpoints
  // server.get('/api/**', (req, res) => { });
  // Serve static files from /browser
  server.get('*.*', express.static(distFolder, {
    maxAge: '1y'
  }));

  // All regular routes use the Universal engine
  server.get('*', (req, res) => {
    res.render(indexHtml, { req, providers: [{ provide: APP_BASE_HREF, useValue: req.baseUrl }] });
  });

  return server;
}

function run() {
  const port = process.env.PORT || 4000;

  // Start up the Node server
  const server = app();
  server.listen(port, () => {
    console.log(`Node Express server listening on http://localhost:${port}`);
  });
}

// Webpack will replace 'require' with '__webpack_require__'
// '__non_webpack_require__' is a proxy to Node 'require'
// The below code is to ensure that the server is run only when not requiring the bundle.
declare const __non_webpack_require__: NodeRequire;
const mainModule = __non_webpack_require__.main;
const moduleFilename = mainModule && mainModule.filename || '';
if (true) {
  run();
}

export * from './src/main.server';
```

my folder structure
![pic1](https://user-images.githubusercontent.com/30695220/84566912-6fbf7100-ad8e-11ea-928b-6a71e6e73153.PNG)
![pic2](https://user-images.githubusercontent.com/30695220/84566916-7352f800-ad8e-11ea-98d8-fed258ea9393.PNG)

**Comment by merry75** [comment] 2020-07-03 16:37
any progress on this issue ? cant load angular element to another app due to this issue

**Comment by jjssman** [comment] 2020-10-16 22:39
Any solution to this? I have the exact same problem and I have been struggling to get SSR to work.

**Comment by celesteking** [comment] 2020-10-20 18:09
In my case (Angular 6 -> 6.1 LTS upgrade), it was because some idiot added `window.global = {window};` to `index.html`. Removing that cleared the error. Spent 4 hours trying to track this down. Angular sucks.

**Comment by tyh77** [comment] 2020-12-08 20:59
@merry75 same exact use-case: Angular Elements in a non-framework app. Did you by any chance resolve this?

**Comment by vasilevvasko** [comment] 2021-04-23 06:25
> @IamDeshRaj, you rock!
> 
> The root cause here is that `platformServer()` (and `platformBrowserDynamic` for that matter) expose a platform injector that provides `CompilerFactory` with `JitCompilerFactory`, which creates a View Engine compiler. Obviously that's not going to work in an Ivy app!
> 
> It turns out that `ngExpressEngine` relies on `CompilerFactory`, which is why it shows up as an SSR bug.
> 
> Once the application is created, it has a `Compiler` which is overridden in Ivy, which makes sense, but the `CompilerFactory` at the platform level should _also_ be overridden. It should be a pretty straightforward fix.

Can you please elaborate on what the fix is?

**Comment by vasilevvasko** [comment] 2021-04-23 07:21
@airasyaqub Did you find a solution for the Error: ENOENT: no such file or directory, open 'app.component.html'

error?

**Comment by cjarv** [comment] 2021-04-23 16:09
Any progress on this?

`Uncaught Error: Can't resolve all parameters for AppModule: (?).
    at syntaxError (compiler.js:553)
    at CompileMetadataResolver._getDependenciesMetadata (compiler.js:3873)
    at CompileMetadataResolver._getTypeMetadata (compiler.js:3870)
    at CompileMetadataResolver.getNgModuleMetadata (compiler.js:3867)
    at JitCompiler._loadModules (compiler.js:4430)
    at JitCompiler._compileModuleAndComponents (compiler.js:4430)
    at JitCompiler.compileModuleAsync (compiler.js:4430)
    at CompilerImpl.compileModuleAsync (platform-browser-dynamic.js:234)
    at compileNgModuleFactory__PRE_R3__ (core.js:11910)
    at PlatformRef.bootstrapModule (core.js:12008)
syntaxError @ compiler.js:553
_getDependenciesMetadata @ compiler.js:3873
_getTypeMetadata @ compiler.js:3870
getNgModuleMetadata @ compiler.js:3867
_loadModules @ compiler.js:4430
_compileModuleAndComponents @ compiler.js:4430
compileModuleAsync @ compiler.js:4430
compileModuleAsync @ platform-browser-dynamic.js:234
compileNgModuleFactory__PRE_R3__ @ core.js:11910
bootstrapModule @ core.js:12008
eval @ main.ts:22
./main.ts @ bundle.js:30
__webpack_require__ @ bundle.js:2730
(anonymous) @ bundle.js:3776
(anonymous) @ bundle.js:3780`

migrating an existing app to a hybrid app with NgUpgrade. using webpack-dev-server at this point.

**Comment by vasilevvasko** [comment] 2021-04-23 19:53
try adding import 'reflect-metadata'; on top of server.ts
________________________________

**Comment by cjarv** [comment] 2021-04-24 05:09
This is my main.ts, apologies for not including this earier...

`import 'core-js/es6/reflect';
import 'core-js/es7/reflect';
import 'zone.js';
import 'reflect-metadata';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { setAngularJSGlobal } from '@angular/upgrade/static';
import * as angular from 'angular';
import { AppModule } from './app/app.module';

setAngularJSGlobal(angular);
platformBrowserDynamic().bootstrapModule(AppModule).catch(err => console.error(err));`

**Comment by cjarv** [comment] 2021-04-26 13:20
This issue is still plaguing me any assistance would be greatly appreciated. Thanks everyone!

**Comment by shaher** [comment] 2021-06-19 18:18
Any update? 
I started a new angular 12 project and tried to run ssr and come to this bug!

**Comment by Rahul-Geeks** [comment] 2021-09-09 14:45
> @IamDeshRaj, you rock!
> 
> The root cause here is that `platformServer()` (and `platformBrowserDynamic` for that matter) expose a platform injector that provides `CompilerFactory` with `JitCompilerFactory`, which creates a View Engine compiler. Obviously that's not going to work in an Ivy app!
> 
> It turns out that `ngExpressEngine` relies on `CompilerFactory`, which is why it shows up as an SSR bug.
> 
> Once the application is created, it has a `Compiler` which is overridden in Ivy, which makes sense, but the `CompilerFactory` at the platform level should _also_ be overridden. It should be a pretty straightforward fix.

Can you elaborate a little bit better like what changes in the app should be done? My use case is the same. I am using SSR with IVY. Angular version is 12.

**Comment by JoostK** [comment] 2023-10-29 17:28
I am going to close this as obsolete, since the reported error comes from ViewEngine which has been completely removed by now.

**Closed by JoostK** 2023-10-29 17:28 UTC
Labels: type: bug/fix, area: compiler, state: confirmed, P3
