### ISSUE TITLE
Confusing usage of children routes in new router

### ISSUE THREAD

**Issue by ruffiem** [angular/angular#10686] opened 2016-08-11 14:42 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Correct me if I'm wrong but I don't get why this :

``` 
const CRISIS_ROUTES: Routes = [ 
  { path: 'crisis', component: ListCrisisComponent },
  { path: 'crisis/create', component: CreateCrisisComponent },
  { path: 'crisis/:id', component: ViewCrisisComponent },
  { path: 'crisis/edit/:id', component: EditCrisisComponent }
];
```

is not the same as this : 

```
const CRISIS_ROUTES: Routes = [
  {
    path: 'crisis',
    component: ListCrisisComponent,
    children: [
      {
        path: 'create',
        component: CreateCrisisComponent
      },
      {
        path: ':id',
        component: ViewCrisisComponent
      },
      {
        path: 'edit/:id',
        component: EditCrisisComponent
      }
    ]
  }
];
```

While the first is working nice, the second throws a "cannot find primary outlet" error.

**Expected/desired behavior**

That both resolve to the same sort of routing.

**What is the motivation / use case for changing the behavior?**

Maintenance, readability.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** [ Chrome ] 
 
* **Language:** [ TypeScript ]

**Comment by brandonroberts** [comment] 2016-08-11 16:24
This is intended behavior. If you define a level of child routing, then your `ListCrisisComponent` is considered a parent and needs to have a `<router-outlet></router-outlet>` in its template.

**Comment by vsavkin** [comment] 2016-08-11 21:46
Closing this issue. The behavior is intentional.

**Closed by vsavkin** 2016-08-11 21:46 UTC
