### ISSUE TITLE
CSS on recursive component results in `-shadowcsshost` pattern

### ISSUE THREAD

**Issue by SteveVanOpstal** [angular/angular#19445] opened 2017-09-27 19:03 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
I created a recursive component (See [plnkr](http://plnkr.co/edit/SN7ymjYwNdIgwfLakzCt?p=preview)):
```JavaScript
@Component({
  selector: 'ng-test',
  styleUrls: ['./src/component.css'],
  template: `
    <p>I am {{data.name}}</p>
    <ng-template [ngIf]="data.data">
      <ng-test [data]="data.data"></ng-test>
    </ng-template>`
})
```

with the following CSS:
```css
:host {
  color: red;
}
  
:host > :host {
  color: green;
}
```

The CSS on the page becomes the following:
```css
[_nghost-c0] {
  color: red;
}
  
[_nghost-c0]    > -shadowcsshost {
  color: green;
}
```

## Expected behavior
I expected `component1` to have the color red and `component2` to have the color green

## Minimal reproduction of the problem with instructions
[plnkr](http://plnkr.co/edit/SN7ymjYwNdIgwfLakzCt?p=preview)

## Environment

<pre><code>Angular version: 4.4.3</code></pre>

**Comment by IAMtheIAM** [comment] 2018-07-23 16:39
Still an issue in angular 6 - what does ` -shadowcsshost ` even mean?

**Comment by bd-Kwasniewski** [comment] 2019-10-03 10:55
Still an issue in angular 8

**Comment by trotyl** [comment] 2019-10-03 12:52
Could anyone make a working demo for this in native Shadow DOM? AFAICK `:host > :host` is not a valid selector per spec.

**Comment by jscharett** [comment] 2019-10-07 07:05
Just ran into this myself, and I was able to resolve it by using `:host-context()`, but not ideal imo; prefer `:host > :host` to work as expected.  Try doing:

```
:host-context(ng-test) > :host {
    color: green;
}
```

**Comment by Spektr** [comment] 2019-11-06 13:23
for zombie angular 4.1.3
this code (.scss)
```
.notifications {
    &__section_open > &__dropdown {
      display: block;
    }
}
```
converted to (css)
```
[_nghost-c4]   .notifications__section_open[_ngcontent-c4]    > -shadowcsshost   .notifications__dropdown[_ngcontent-c4] {
      display: block;
 }
```

**Comment by quiplunar** [comment] 2020-06-01 23:07
Hello, I ran into the same problem.

scss:
`
:host {
  display: block;
  width: 100%;

  /* --- */
  .ui-input {
    $self: &;
    width: 100%;

    &__input {
      width: 100%;
    }

    &_state_typing {
      #{$self}__example-self {
        opacity: 1;
      }
    }
  }
  /* --- */
}
`

css:
`
[_nghost-lkp-c3]   .ui-input_state_typing[_ngcontent-lkp-c3]   -shadowcsshost   .ui-input__SSS[_ngcontent-lkp-c3] {
  opacity: 1;
}
`

$self === ":host .ui-input'.

How can I fix it?

**Comment by SteveVanOpstal** [comment] 2020-06-02 07:52
It seems like `-shadowcsshost` is some sort of a placeholder that should be replaced by the generated 'host' attribute (in your example `_nghost-lkp-c3`), but this has never worked recursively in ViewEncapsulation.Emulated mode. You can try and work with other encapsulation modes or work around the issue.

A workaround could be adding `@HostBinding('class.host') host = true;` to your component and use `.host` in your scss instead of `:host`

**Comment by petebacondarwin** [comment] 2021-01-23 20:40
From [the spec](https://drafts.csswg.org/css-scoping/#selectordef-host):

> The :host pseudo-class, when evaluated in the context of a shadow tree, matches the shadow tree’s shadow host. 

Note that it refers to the actual element instance (not elements of a particular type).

Therefore a selector like `:host > :host` makes no sense since an instance of an element cannot be a child of itself.

I think this is confusing because of how the `Encapsulation.Emulated` tries to achieve the ShadowDOM behaviour by attaching an attribute to elements of the same type (e.g. `my-component[_nghost-c0]`) which would potentially lend itself to a CSS selector like:  `[_nghost-c0] > [_nghost-c0]`.

Closing as "not working" as intended.

**Closed by petebacondarwin** 2021-01-23 20:40 UTC
Labels: P3, comp: core, core: CSS encapsulation, freq1: low, type: bug/fix
