### ISSUE TITLE
Renderer breaks HTML Content Templates

### ISSUE THREAD

**Issue by christianliebel** [angular/angular#35588] opened 2020-02-20 17:02 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/compiler.

### Is this a regression?

 This happens both in Angular 9 and 8. Might be a regression of #1442.

### Description

 Given the following HTML content template, the `div` node should be part of the content fragment.

```html
<template>
  <div>Test</div>
</template>
```

However, Angular seems to append the `div` node to the `template` node. As a result, the content fragment of the content template is empty, so it's effectively unusable. This breaks compatibility with libraries that need to operate on HTML Content Templates.

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/ng-template-fce

This repro has two template tags, one in app.component.html (`template#template1`, inside Angular) and one in index.html (`template#template2`, outside Angular).

Click _Test template inside Angular_. It shows:
![image](https://user-images.githubusercontent.com/6698344/74958787-c2ed6c80-5409-11ea-9130-f21ad3b13cdc.png)

Click _Test template outside Angular_. It shows:
![image](https://user-images.githubusercontent.com/6698344/74958789-c54fc680-5409-11ea-981b-513338adfaf3.png)

## 🔥 Exception or Error
The contents of the `template` element should be added to the content template instead of being appended to the `template` node itself.

## 🌍  Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 9.0.3
Node: 12.14.1
OS: darwin x64

Angular: 9.0.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.3
@angular-devkit/build-angular     0.900.3
@angular-devkit/build-optimizer   0.900.3
@angular-devkit/build-webpack     0.900.3
@angular-devkit/core              9.0.3
@angular-devkit/schematics        9.0.3
@angular/cli                      9.0.3
@ngtools/webpack                  9.0.3
@schematics/angular               9.0.3
@schematics/update                0.900.3
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
</code></pre>

**Anything else relevant?**

—

**Comment by pkozlowski-opensource** [comment] 2020-02-20 20:05
Yes, sadly we've got a long standing issue for this one already: #15557.
I'm going to close this one as a duplicate of #15557, but I'm going to add your reproduce scenario (excellent one, thnx for preparing it!) in there.

**Closed** 2020-02-20 20:06 UTC
