### ISSUE TITLE
Sanitize removes inline style tags

### ISSUE THREAD

**Issue by msteel9999** [angular/angular#46937] opened 2022-07-22 12:53 UTC
### Which @angular/* package(s) are the source of the bug?

platform-browser

### Is this a regression?

No

### Current Behaviour
Sanitize removes inline style

### Expected Behaviour
Sanitize should not remove style

Already raised in 
https://github.com/angular/angular/issues/17284, 
https://github.com/angular/angular/issues/19645
https://github.com/angular/angular/issues/26567

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-t44mwq

### Please provide the exception or error you saw

```true
NA
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular 13.2.2
```

### Anything else?

Please stop closing this as it keeps getting re-raised.

Need this to work in order to use rich text editor.

**Comment by pkozlowski-opensource** [comment] 2022-07-22 12:57
This is a duplicate of the existing, open issue #45270

Closing as a duplicate of #45270

**Closed by pkozlowski-opensource** 2022-07-22 12:57 UTC
