### ISSUE TITLE
ReactiveForms: Disable individual input radio elements of a group programmatically

### ISSUE THREAD

**Issue by johanneslietz** [angular/angular#13439] opened 2016-12-13 19:39 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Based on other form input, I'd like to disable individual radio options in a radio form control, but the current disable() method only allows to disable all radios of a group or none. 

Setting the [disabled] attribute of an individual radio input is not allowed here:
```
It looks like you're using the disabled attribute with a reactive form directive. 
If you set disabled to true when you set up this control in your component class, 
the disabled attribute will actually be set in the DOM for you. 
We recommend using this approach to avoid 'changed after checked' errors.
```

**Expected behavior**

I can access and disable/enable individual radio input elements.

**Minimal reproduction of the problem with instructions**

```
import {Component, NgModule} from '@angular/core'
import {BrowserModule} from '@angular/platform-browser'

import {FormBuilder, FormGroup, FormsModule, ReactiveFormsModule} from '@angular/forms';

@Component({
  selector: 'my-app',
  template: `
    <div>
      <form [formGroup]="myForm">
        <input type="radio" id="r1" formControlName="myRadio" value="1"/><label for="r1">Radio 1</label><br>
        <input type="radio" id="r2" formControlName="myRadio" value="2"/><label for="r2">Radio 2</label><br>
        <input type="radio" id="r3" formControlName="myRadio" value="3"/><label for="r3">Radio 3</label><br>
        <button (click)="disableRadio()">Disable Radio 3 only</button>
      </form>
    </div>
  `,
})
export class App {
  myForm: FormGroup;
  constructor(private formBuilder: FormBuilder) {
    this.myForm = formBuilder.group({
      myRadio: "1"
    });
    this.myForm.valueChanges.subscribe(something => {
      console.log(this.myForm.value.myRadio);
    });
  }
  disableRadio():void {
    this.myForm.controls.myRadio.disable(); 
    //***I'd like to disable only the 3rd radio here, not all of them.***
  }
}

@NgModule({
  imports: [ BrowserModule, FormsModule, ReactiveFormsModule ],
  declarations: [ App ],
  bootstrap: [ App ]
})
export class AppModule {}
```
http://plnkr.co/edit/J4pr2FJUs8IZdEldYz92?p=preview

**What is the motivation / use case for changing the behavior?**

Based on other form input, I'd like to disable individual radio options in a form.

**Please tell us about your environment:**

* **Angular version:** 2.3.0

* **Browser:** [all]

 
* **Language:** [TypeScript]

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment] 2016-12-13 21:13
Duplicate of https://github.com/angular/angular/issues/11763

**Comment by vicb** [comment] 2016-12-13 22:01
Thanks @DzmitryShylovich

**Closed by vicb** 2016-12-13 22:01 UTC
Labels: comp: forms, type: feature
