### ISSUE TITLE
hostListeners does not work on Component that was used for bootstrap

### ISSUE THREAD

**Issue by gionkunz** [angular/angular#1548] opened 2015-04-26 19:57 UTC
Hi guys

In the following example I've noticed that `hostListeners` does not seem to work on the Component that was used to bootstrap the AngularJS. Within this example, a `window.resize` will only trigger within EventTestDecorator and EventTestComponent but not in the App component which is used to bootstrap. Is this expected behavior?

```javascript
import {Decorator, Component, View, bootstrap} from 'angular2/angular2';

@Decorator({
  selector: '[event-test-decorator]',
  hostListeners: {
    'window:resize': 'onResize($event)'
  }
})
class EventTestDecorator {
  onResize(event) {
    console.log(EventTestDecorator, event);
  }
}

@Component({
  selector: '[event-test-component]',
  hostListeners: {
    'window:resize': 'onResize($event)'
  }
})
@View({
  template: `
    EventTestComponent
  `
})
class EventTestComponent {
  onResize(event) {
    console.log(EventTestComponent, event);
  }
}

@Component({
  selector: 'app',
  hostListeners: {
    'window:resize': 'onResize($event)'
  }
})
@View({
  template: `
    <div>App</div>
    <div event-test-decorator>EventTestDecorator</div>
    <div event-test-component></div>
  `,
  directives: [EventTestDecorator, EventTestComponent]
})
class App {
  onResize(event) {
    console.log(App, event);
  }
}

bootstrap(App);
```

Cheers
Gion

**Comment by jelbourn** [comment] 2015-04-27 22:31
Dupe of #1539

**Closed by jelbourn** 2015-04-27 22:31 UTC
