### ISSUE TITLE
BUG : angular_1_router : ng-link-active class fails to be added to Menu Item

### ISSUE THREAD

**Issue by andrewaxelrod** [angular/angular#7628] opened 2016-03-16 17:57 UTC
Related to #5286 

When an item is selected using ng-link, it only adds the class 'ng-link-active' if there is no parameter within the ng-link directive.  `<a ng-link="['About']">About</a>`

The class 'ng-link-active' FAILS to be added for ng-link with a parameter.
`<a ng-link="['About', **{id: 5}**]">About</a>`

**Comment by brandonroberts** [comment] 2016-03-16 18:28
Duplicate of https://github.com/angular/angular/issues/6459 . If the parameter is optional, its not considered as active.

**Comment by vicb** [comment] 2016-09-26 21:47
obsolete

**Closed by vicb** 2016-09-26 21:47 UTC
