### ISSUE TITLE
@Query should quey for inherited components also

### ISSUE THREAD

**Issue by AlmogShaul** [angular/angular#7585] opened 2016-03-13 15:33 UTC
I'm submitting a feature request

The current behavior is that @Query don't return inherited components

The expected behavior should be that the injected Query will find the Inherited components .

The current behavior is not making any sense .
I want to create components that inherit base component, and I want to find them in my
Component.

- Angular version: 2.0.0-beta.5
- Browser: all
- Language: TypeScript

**Comment by ericmartinezr** [comment] 2016-03-13 15:37
See https://github.com/angular/angular/issues/3670

**Comment by fernandocode** [comment] 2016-04-13 14:39
See too #7968

**Comment by pkozlowski-opensource** [comment] 2016-06-03 12:20
Duplicate of #8580, see the suggested solution in there.

**Closed by pkozlowski-opensource** 2016-06-03 12:20 UTC
