### ISSUE TITLE
Cannot resolve module 'rxjs/operators/toPromise'

### ISSUE THREAD

**Issue by donaldpipowitch** [angular/angular#5693] opened 2015-12-08 08:01 UTC
It looks like Angular 2 tries to load files in a path called `'rxjs/operators/*'` (like [here](https://github.com/angular/angular/blob/25a2d7b5db7806e1b6b3ce0b5380cf94253bbe4c/modules/angular2/src/facade/async.ts#L13)). But it seems the path should be called `'rxjs/operator/*'` (without `s`).

Webpack error:
```
ERROR in ./~/angular2/src/facade/async.js
Module not found: Error: Cannot resolve module 'rxjs/operators/toPromise' in
```

**Comment by robwormald** [comment] 2015-12-08 08:27
Duplicate of https://github.com/angular/angular/issues/5643

This has been fixed upstream, for the moment you can workaround this (as you're using webpack) like https://github.com/angular/angular2-seed/blob/master/webpack.config.js#L9-L13 

Apologies for the inconvenience.

**Closed by robwormald** 2015-12-08 08:27 UTC

**Comment by donaldpipowitch** [comment] 2015-12-08 20:25
Thanks.

**Comment by karthik-dusk** [comment] 2018-07-20 17:30
![upgrade error](https://user-images.githubusercontent.com/5618488/43016483-9cf5edde-8c70-11e8-9648-e52101c518ce.png)
I am getting this error :-(
