### ISSUE TITLE
ngClass with method not working

### ISSUE THREAD

**Issue by Sharpiro** [angular/angular#8218] opened 2016-04-25 18:24 UTC
**Steps to reproduce and a minimal demo of the problem**

http://plnkr.co/edit/h02LVM8sPwKJ6ljDVShz?p=preview

_What steps should we try in your demo to see the problem?_

Should see right away

**Current behavior**
when using a method along with [ngClass], debugging shows that the classes get applied correctly, but are then un-applied before the user can see them.

**Expected/desired behavior**
Returning an object to ngClass via a method should be the same as passing the object in directly from the template

**Comment by pkozlowski-opensource** [comment] 2016-04-25 19:15
Duplicate of #7426

**Closed by pkozlowski-opensource** 2016-04-25 19:15 UTC
