### ISSUE TITLE
Cannot find module '../products' or its corresponding type declarations.

### ISSUE THREAD

**Issue by EvanGertis** [angular/angular#42216] opened 2021-05-21 10:26 UTC
### Description
 A clear and concise description of the problem...
When I try to run the example. The module '../products' cannot be found.
```
Error in src/app/product-alerts/product-alerts.component.ts (3:10)
'"../products"' has no exported member named 'Product'. Did you mean 'products'?
```

## Minimal Reproduction

 https://stackblitz.com/edit/angular-97i9u5?file=src%2Fapp%2Fproducts.ts

## Exception or Error
<pre><code>

Error in src/app/product-alerts/product-alerts.component.ts (3:10)
'"../products"' has no exported member named 'Product'. Did you mean 'products'?

</code></pre>

**Comment by petebacondarwin** [comment] 2021-05-21 12:47
Thanks for reporting this - it will be fixed by https://github.com/angular/angular/pull/42147

**Comment by petebacondarwin** [comment] 2021-05-21 12:47
Closing as a duplicate of #42144

**Closed by petebacondarwin** 2021-05-21 12:47 UTC

**Comment by qinyuanchunxue** [comment] 2021-06-15 22:36
For the same problem, the solution is to save and then refresh the page.
相同问题，解决办法是 保存然后刷新页面。

reference：https://stackoverflow.com/questions/60880087/cant-find-module-error-in-angular-when-following-the-steps-from-angular-io
