### ISSUE TITLE
In Ivy: ViewContainerRef.move causes ASSERTION ERROR

### ISSUE THREAD

**Issue by Shijir** [angular/angular#37120] opened 2020-05-14 21:48 UTC
# 🐞 bug report

### Affected Package
    "@angular/animations": "~10.0.0-next.7",
    "@angular/common": "~10.0.0-next.7",
    "@angular/compiler": "~10.0.0-next.7",
    "@angular/core": "~10.0.0-next.7",
    "@angular/forms": "~10.0.0-next.7",
    "@angular/platform-browser": "~10.0.0-next.7",
    "@angular/platform-browser-dynamic": "~10.0.0-next.7",
    "@angular/router": "~10.0.0-next.7",

### Description

I have this  dynamic component called `HostViewAccessor`:
```ts
@Component({ 
  selector: 'host-view-accessor',
  template: `<ng-template #portal><ng-content></ng-content></ng-template>`
})
export class HostViewAccessor {
  @ViewChild('portal', { static: true, read: TemplateRef }) templateRef: TemplateRef<void>;
}
```

And I use HostViewAccessor component above in this `CellComponent`:
```ts
@Component({
  selector: 'cell',
  template: `<ng-content></ng-content>`
})
export class CellComponent  {
  view: EmbeddedViewRef<void>;  

  constructor(private el: ElementRef, private cfr: ComponentFactoryResolver) {}

  ngOnInit() {
    const dynamicHostViewAccessorFactory = this.cfr.resolveComponentFactory(HostViewAccessor);
    const dynamicHostViewAccessorCompRef = dynamicHostViewAccessorFactory.create(Injector.NULL, [[this.el.nativeElement]]);
    this.view = dynamicHostViewAccessorCompRef.instance.templateRef.createEmbeddedView();
  }
}
```
You can see that I am creating the embedded view of the `CellComponent` itself through `HostViewAccessor`.

And I project cell components inside this `RowComponent`. Then, I access and insert the views of the cell components into the adjacent `ng-container` with the template id of `#cellsContainer`: 
```ts
@Component({
  selector: 'row',
  template: `<ng-content></ng-content><ng-container #cellsContainer></ng-container>`
})
export class RowComponent  {
  @ViewChild('cellsContainer', { static: false, read: ViewContainerRef }) cellsContainer: ViewContainerRef;

  @ContentChildren(CellComponent) cells: QueryList<CellComponent>;

  ngAfterViewInit() {
    this.cells.forEach(cell => this.cellsContainer.insert(cell.view));
    setTimeout(() => {
      // swap the first and second cell views.
      this.cellsContainer.move(this.cellsContainer.get(1), 0);
    }, 3000);
  }
}
```

Also, you can see that after inserting the cell views, I try to swap the first and second cell views. However, that exact line causes the following error:

```
ERROR Error: ASSERTION ERROR: Should be one of Element, Container, ElementContainer, IcuContainer, Projection but got <unknown> [Expected=> true == false <=Actual]
```

## 🔬 Minimal Reproduction

Here is the minimal reproduction of the issue in a new app:
https://github.com/Shijir/ng10-testing

An interesting thing I've noticed here is that I couldn't reproduce the error on NG-RUN even though I've used the exact same code here:
https://ng-run.com/edit/MIwT9pp8UwanQonc8Qt3?open=app%2Fapp.component.ts&layout=1
However, this NG-RUN example is running on Typescript@3.7.5. So I suspect also environmental discrepancies might be causing the issues. 

## 🌍  Your Environment

**Angular Version:**
<pre><code>
~10.0.0-next.7
"typescript": "^3.8.3"

</code></pre>

**Anything else relevant?**

**Comment by pkozlowski-opensource** [comment] 2020-05-15 05:48
@Shijir thnx for providing all the details! I was able to create a runnable scenario using stackblitz: https://stackblitz.com/edit/angular-ivy-s49yjz?file=src%2Fapp%2Fapp.component.ts - the reason for which you couldn't reproduce it in ng-run is that ng-run was using VE (and this bug is specific to ivy).

Anyway, this is a confirmed bug in ivy - but it seems like a relatively easy one to fix. Marking as a bug. Again, thnx for reporting and providing all the reproduce scenarios!

**Comment by Shijir** [comment] 2020-05-15 17:25
Hi @pkozlowski-opensource! thanks for the confirmation. Do you the fix would be merged in before Angular 10 release?

**Closed** 2021-02-10 19:03 UTC
Labels: P2, comp: core, core: dynamic view creation, engine: ivy, freq1: low, regression, state: confirmed, state: has PR, triage #1, type: bug/fix
