### ISSUE TITLE
ngOnInit broken in version 4.1.1 when used with ngOnChanges

### ISSUE THREAD

**Issue by aggro80** [angular/angular#19177] opened 2017-09-13 11:51 UTC
## I'm submitting a...
<pre><code>
[x ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request 
</code></pre>

## Current behavior
If @Component implements OnChanges, OnInit, ngOnInit is not called at all. It is called if Angular version 4.1.0 is used, but it stopped working in version 4.1.1.  Version 4.3.6 also fails.

## Expected behavior
If @Component implements OnChanges, OnInit, ngOnInit gets called. Like it was still in version 4.1.0.

## Minimal reproduction of the problem with instructions
Just create a @Component that implements OnChanges, OnInit and put for example some debug logging into ngOnInit() method and you should see that with newer versions it doesn't work. You should also note that if you don't use OnChanges, then ngOnInit() is called.

## Environment

<pre><code>
Angular version: 4.1.1 - 4.3.6

Browser:
- [ x] Chrome (desktop) version Version 60.0.3112.113 (Official Build) (64-bit)
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

I noticed that there is a change in 4.1.1 related to ngOnChanges(), I wonder if that is the cause of this regression?
</code></pre>

**Comment by pkozlowski-opensource** [comment] 2017-09-13 12:04
That sounds very odd, could you please provide a minimal reproduce scenario in a plunker as requested in the issue template? We can't do much about potential bugs that we can't reproduce.

**Comment by mhevery** [comment] 2018-05-01 22:32
This issue seems abandoned without any reproducible instruction.  We are closing the issue. If you have reproducible instructions please file a new issue.

**Closed by mhevery** 2018-05-01 22:32 UTC
Labels: comp: core & compiler, state: Need repro
