### ISSUE TITLE
CurrencyPipe SymbolDisplay Bug : 'ZAR'

### ISSUE THREAD

**Issue by gibsonsyd** [angular/angular#12561] opened 2016-10-27 11:44 UTC
**I'm submitting a ...**  (check one with "x")

```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When using the currency pipe to format a number specifying the valid ISO 4217 currency code for South Africa 'ZAR' and setting the SymbolDisplay to true the currency code is not replaced by the currency symbol, in this case 'R'.

**Expected behavior**

The expected behavior is for the projected property to display the currency symbol instead of the currency code when symbolDisplay is true and currencyCode is set to 'ZAR'. 

**Minimal reproduction of the problem with instructions**

{{someamount | currency:'ZAR':true:'1.2-2'}}

**What is the motivation / use case for changing the behavior?**

We need to format currency with the South African currency symbol.

**Please tell us about your environment:**

macOS Sierra, webpack, ng serve (angular-cli: template used: 1.0.0-beta.11-webpack.9-4)
- **Angular version:** 2.0.0-rc.7
  
  
- **Browser:** all 
  
  
- **Language:** all
- **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment] 2016-10-27 11:45
Hi, pls provide reproduction in plnkr.

**Comment by gibsonsyd** [comment] 2016-10-27 11:48
https://plnkr.co/edit/uqkd2o31BQMO1S5qHwJi?p=preview

**Comment by vicb** [comment] 2016-10-27 16:35
What browser(s) have you tested ?

We do delegate to the Intl API for this kinf of stuff and some browser might not support the full list of symbols

**Comment by gibsonsyd** [comment] 2016-10-28 11:42
@vicb Same experience on all browsers I've tested with:

Chrome latest
Firefox latest
Safari latest (macOS Sierra)

**Comment by choopage** [comment] 2016-11-01 01:50
Hi @DzmitryShylovich and @vicb 

The currency pipe display for SGD and THB symbols are not correct too. Please see enclosed image. Thanks.

![screen shot 2016-11-01 at 9 48 08 am](https://cloud.githubusercontent.com/assets/6467136/19877236/772821bc-a018-11e6-80b7-1800e9550c19.png)

**Comment by pkozlowski-opensource** [comment] 2016-12-19 19:44
This is duplicate of #6724 where the root cause is Intl API implementation not having full data about all the currency symbols. Let's continue the discussion in #6724

**Closed by pkozlowski-opensource** 2016-12-19 19:44 UTC
Labels: comp: common, comp: i18n, type: bug
