### ISSUE TITLE
Angular 9 es5 build result is not working in IE11 (SCRIPT1046)

### ISSUE THREAD

**Issue by simneol** [angular/angular#33611] opened 2019-11-06 05:30 UTC
# 🐞 bug report

### Affected Package

The issue is caused by package @angular/common or @angular/compiler

### Is this a regression?

Yes, I simulated it in two different version.
* 8.2.13 (runs correctly)
* 9.0.0-rc.0 (error occured during runtime)

### Description

Internet Explorer 11 cannot execute angular 9 project when build target is es5 and optimization option is disabled.  
It shows below message.
```
SCRIPT1046: Multiple definitions of a property not allowed in strict mode
vendor.js (1133,192)
```
Line 1133 of the vendor.js file is shown below. (prettified)
```javascript
/*@__PURE__*/
_angular_core__WEBPACK_IMPORTED_MODULE_1__["ɵsetClassMetadata"](BrowserPlatformLocation, [{
  type: _angular_core__WEBPACK_IMPORTED_MODULE_1__["Injectable"],
  args: [{
    providedIn: 'platform',
    // See #23917
    useFactory: createBrowserPlatformLocation
  }]
}], function () {
  return [{
    type: Object,
    decorators: [{
      type: _angular_core__WEBPACK_IMPORTED_MODULE_1__["Inject"],
      args: [DOCUMENT]
    }]
  }];
}, {
  _init: [],
  location: [],
  _history: [],
  getBaseHrefFromDOM: [],
  onPopState: [],
  onHashChange: [],
  href: [],
  protocol: [],
  hostname: [],
  port: [],
  pathname: [],
  pathname: [],
  search: [],
  hash: [],
  pushState: [],
  replaceState: [],
  forward: [],
  back: [],
  getState: []
});
```
The error occured because `pathname` of 4th argument object was defined twice.  

This error was not occured when `optimization`(in `angular.json`) option is enabled or build `target`(in `tsconfig.json`) compiler option is `es2015` with differential loading.  
But I need to execute angular project in IE11 using non-optimization and es5 build target for smooth debugging. 

## 🔬 Minimal Reproduction

https://github.com/simneol/angular9-es5-bug  
1. clone above repository
2. `npm ci`
3. `npm run build`
4. serve build output using any web server (I used nginx)
5. open it using Internet Explorer 11

## 🔥 Exception or Error
<pre><code>
SCRIPT1046: Multiple definitions of a property not allowed in strict mode
vendor.js (1133,192)
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 9.0.0-rc.0
Node: 10.16.0
OS: win32 x64
Angular: 9.0.0-rc.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-rc.0
@angular-devkit/build-angular     0.900.0-rc.0
@angular-devkit/build-optimizer   0.900.0-rc.0
@angular-devkit/build-webpack     0.900.0-rc.0
@angular-devkit/core              9.0.0-rc.0
@angular-devkit/schematics        9.0.0-rc.0
@ngtools/webpack                  9.0.0-rc.0
@schematics/angular               9.0.0-rc.0
@schematics/update                0.900.0-rc.0
rxjs                              6.5.3
typescript                        3.6.4
webpack                           4.41.2
</code></pre>

**Anything else relevant?**
* OS: Windows 10 1903 (18362.418) 64-bit
* Brwoser: Internet Explorer 11 
  * Version: 11.418.18362.0
  * Update version: 11.0.155 (KB4519974)

**Comment by gkalpak** [comment] 2019-11-06 12:04
Thx for reporting the issue.
This is a duplicate of #30569 and should be fixed by #33514.

**Closed by gkalpak** 2019-11-06 12:04 UTC
Labels: comp: compiler, comp: ivy
