### ISSUE TITLE
string type control can be used on number type input field

### ISSUE THREAD

**Issue by mehedihasansjs** [angular/angular#59307] opened 2024-12-26 13:03 UTC
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

Yes

### Description

I have declared a control with type string.
 
```typescript
control = new FormControl<string>('')
```

but I have applied the control on number type input field

```html
<input type="number" formControlName="control" />
```

The control in the ends returns the value type number, but when I access the API of control's value I can only get string's API.

My suggestion is, either we can show error or warning if string type control returns value as number, or we can cast the value to string and bind to control's value.

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular Version: 17.3.7
```

**Comment by JoostK** [comment] 2024-12-26 13:28
Duplicate of #45968

**Closed** 2024-12-26 13:29 UTC
