### ISSUE TITLE
Select [multiple]="null" incorrectly returns an array instead of a string.

### ISSUE THREAD

**Issue by yoooee** [angular/angular#20584] opened 2017-11-22 13:37 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Setting the multiple attribute on a select control in the following way results in an array being returned instead of a string.
<select [multiple]="null" ...>

## Expected behavior

<select ...>  returns a string when something is selected
<select multiple ...> returns an array when something is selected
**<select [multiple]="null" ...> should return a string when something is selected**
<select [multiple]="true" ...> returns an array when something is selected

## Minimal reproduction of the problem with instructions

1. Create select control: 
<select name="testSelect" [(ngModel)]="selectedItem">

2. Add various options: 
&lt;option value="1"&gt;Item 1&lt;/option&gt;
&lt;option value="2"&gt;Item 2&lt;/option&gt;
&lt;option value="3"&gt;Item 3&lt;/option&gt;

3. Set [multiple]="null" on the select control: 
<select name="testSelect" [(ngModel)]="selectedItem" [multiple]="null">

4. Output {{selectedItem | json}}

Demo
https://plnkr.co/edit/FPPw69UEoNv9RmJu0AWi?p=preview

## What is the motivation / use case for changing the behavior?

Create a Select component that allows the user to flag the component for single or multiple selection. 

## Environment

<pre><code>
Angular version: 5.X.X

Browser:
- [x] Chrome (desktop) version 62.0.3
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version 57.0
- [x] Safari (desktop) version 11.0.1
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v6.10.2 
- Platform: Mac 

Others:

</code></pre>

**Comment by dawidgarus** [comment] 2017-11-28 14:33
Related issue: https://github.com/angular/angular/issues/19929

**Comment by kara** [comment] 2017-11-28 23:14
Duplicate of https://github.com/angular/angular/issues/12585

**Closed by kara** 2017-11-28 23:14 UTC
Labels: comp: forms
