### ISSUE TITLE
getGlobalObjects is not a function

### ISSUE THREAD

**Issue by shaswatamukherjee** [angular/angular#38506] opened 2020-08-18 13:05 UTC
Hi Team,

After I have upgraded my angular app from ng7 to ng8, I started receiving this error in browser console:

```
zone-legacy.js:310 Uncaught TypeError: api.getGlobalObjects is not a function
    at registerElementPatch (zone-legacy.js:310)
    at zone-legacy.js:333
    at Function.r.__load_patch (zone.min.js:1)
    at _global.__zone_symbol__legacyPatch (zone-legacy.js:332)
    at zone-evergreen.js:2820
    at Function.r.__load_patch (zone.min.js:1)
    at Object.node_modulesZoneJsDistZoneEvergreenJs (zone-evergreen.js:2817)
    at __webpack_require__ (bootstrap:79)
    at Module.srcPolyfillsTs (polyfills.ts:1)
    at __webpack_require__ (bootstrap:79)
```

In my polyfills.ts file, I have: 
``` 
import 'zone.js/dist/zone'; // Included with Angular CLI.
```
Installed zone.js version is 0.9.1

The application **ONLY** loads on Chrome despite the above error.

Could you please help me with this issue?

Thanks and Regards
Shaswata Mukherjee

**Comment by jelbourn** [comment] 2020-11-04 17:45
Closing this since there's no reproduction here; feel free to file a new issue with more details.

**Closed by jelbourn** 2020-11-04 17:45 UTC
Labels: comp: zones
