### ISSUE TITLE
Download icon for Default app starter zip code button not working in Angular.dev

### ISSUE THREAD

**Issue by pravintargaryen** [angular/angular#56790] opened 2024-07-01 17:37 UTC
### Describe the problem that you experienced

I'm working on my first angular app and tried to replicate the following steps. But the download is not starting
[Download the default app](https://angular.dev/tutorials/first-app/01-hello-world#download-the-default-app)
Start by clicking the "Download" icon in the top right pan of the code editor. This will download a .zip file containing the source code for this tutorial. Open this in your local Terminal and IDE then move on to testing the default app.

At any step in the tutorial, you can click this icon to download the step's source code and start from there.

### Enter the URL of the topic with the problem

https://angular.dev/tutorials/first-app/01-hello-world

### Describe what you were looking for in the documentation

downloaded zip file of the starter code for hello world app

### Describe the actions that led you to experience the problem

I followed the first step

[Download the default app](https://angular.dev/tutorials/first-app/01-hello-world#download-the-default-app)
Start by clicking the "Download" icon in the top right pan of the code editor. This will download a .zip file containing the source code for this tutorial. Open this in your local Terminal and IDE then move on to testing the default app.

At any step in the tutorial, you can click this icon to download the step's source code and start from there.

### Describe what you want to experience that would fix the problem

downloaded zip file of the starter code for hello world app

### Add a screenshot if that helps illustrate the problem

![angular](https://github.com/angular/angular/assets/96950453/e281bc27-a845-46c6-8012-2d79271ad521)

**Comment by JoostK** [comment] 2024-07-01 18:45
Thanks for reporting, this is a duplicate of #56404.

**Closed** 2024-07-01 18:46 UTC
