### ISSUE TITLE
After navigating to new component, old component styles are not unloaded.

### ISSUE THREAD

**Issue by maheshrd999** [angular/angular#47714] opened 2022-10-10 04:28 UTC
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

No

### Description

When I move from one component to another component say for ex comp1 to comp2, comp1 styles are not getting unloaded and I could see comp1 styles are still applied to comp2.

I even verified that the component is getting destroyed by putting a statement in `ngOnDestroy` method. It is getting destroyed.

Attaching the screenshot for your reference.
![Style-issue](https://user-images.githubusercontent.com/37367574/194799146-ca06eed4-25ae-4984-9e5f-b2e5ab5a69e5.PNG)

### Please provide the exception or error you saw

```true
No exception or error on the console.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 9.1.7
Node: 16.16.0
OS: win32 x64

Angular:
...
Ivy Workspace:

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.901.7
@angular-devkit/core         9.1.7
@angular-devkit/schematics   9.1.7
@schematics/angular          9.1.7
@schematics/update
```

**Comment by JoostK** [comment] 2022-10-10 04:56
Duplicate of #16670, but this is working as designed. Styles are only inserted once per page load and not removed when a component instance is destroyed.

**Closed by JoostK** 2022-10-10 04:56 UTC
