### ISSUE TITLE
hybrid app not logging errors

### ISSUE THREAD

**Issue by akosbordas** [angular/angular#11977] opened 2016-09-29 09:13 UTC
**I'm submitting a ...**  (check one with "x")

```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 
`_bootstrapModuleWithZone` in PlatformRef calls the `compileModuleAndAllComponentsAsync`in the compiler. If there is an error during the compilation the thrown error is not shown on the console. The reason for this is that the onError handler is only registered with the zone once the compilation is done. 

**Expected behavior**
I would expect the errors to be shown on the console even during compilation.

**Reproduction of the problem**
1. Create an Angular 1 application which contains Angular 2 components as well and uses UpgradeAdapter to bootstrap the application.
2. Do something which generates a runtime error in Angular2. In my case I had problems with third party exports in it's index.ts and I got the following error: 

> Unexpected value 'Foo' declared by the module 'Bar'
1. In UpgradeAdaper when it comes to boot Angular2 module the browser will not display any errors .  

**Please tell us about your environment:**
Not relevant.
- **Angular version:** 2.0.0
- **Browser:** [all]
- **Language:** [all]

**Comment by vicb** [comment] 2016-09-29 15:27
Please add a repro. Thanks.

**Comment by akosbordas** [comment] 2016-09-30 10:50
I added a repro.

**Comment by vicb** [comment] 2016-09-30 16:11
A runnable repro (plunker) would be best

**Comment by christopherthielen** [comment] 2016-10-03 19:00
Here's a minimal plunker reproduction:
http://plnkr.co/edit/kgZtONX9B7vmlW7kiJXk?p=preview

The error thrown by the compiler is: 
```
Error: Uncaught (in promise): Error: Can't resolve all parameters for FailComponent: (?).(…)
```

but no errors are printed to the console.

![screen shot 2016-10-03 at 1 59 29 pm](https://cloud.githubusercontent.com/assets/2053478/19049851/b8fec9fa-8971-11e6-8e78-266ecc6ed4c6.png)

**Comment by tbosch** [comment] 2016-10-10 15:31
Note that this is the behavior in every ng application.

**Comment by christopherthielen** [comment] 2016-10-10 19:59
> Note that this is the behavior in every ng application.

Do you mean every ng2 application?  Here's a (non-hybrid) ng2 app with the `FailComponent`.  It reports the compile error to the console:
http://plnkr.co/edit/5rNIoNjRTjPzbett4R09?p=preview

![screen shot 2016-10-10 at 2 53 16 pm](https://cloud.githubusercontent.com/assets/2053478/19249105/510a1d62-8ef9-11e6-99c2-168bc8369d9a.png)


If the `.catch()` is removed from `System.import('app')` then we still get the unhandled promise rejection.

![screen shot 2016-10-10 at 2 56 16 pm](https://cloud.githubusercontent.com/assets/2053478/19249241/0f3f79da-8efa-11e6-8b34-01842f3c9644.png)

**Comment by alxhub** [comment] 2020-05-28 21:42
As far as I can tell this isn't a compiler issue, but something to do with SystemJS and the upgrade error handling. Without a working reproduction though (the plnkr seems to have rotted), it'll be hard to confirm this.

**Comment by petebacondarwin** [comment] 2020-10-26 21:02
Closing due to no reproduction or response in months.

**Closed by petebacondarwin** 2020-10-26 21:02 UTC
Labels: P3, comp: core, comp: upgrade, core: error handling, freq1: low, needs clarification, needs reproduction, triage #1, type: bug/fix
