### ISSUE TITLE
JIT compiler throws an error on Samsung Internet Browser

### ISSUE THREAD

**Issue by appimpact** [angular/angular#40733] opened 2021-02-06 12:01 UTC
# 🐞 bug report

### Affected Package

The issue is caused by package @angular/core, version 11.1.2 and probably some older versions.

### Is this a regression?

This used to work, but we are not able to exactly pinpoint (yet) the first version where this started to be an issue.

### Description

We are using Angular JIT compiler in production to compile and render HTML that is dynamically added during the runtime. Even though this is related to compilation process, we have isolated an error to be in @angular/core package.

Problem is manifesting itself only on Samsung Internet browser. We are currently using latest version 13.2.1.70.

All our web applications are currently crashing during the Angular bootstrap process as you can see in the following log:

![image](https://user-images.githubusercontent.com/34662138/107117516-07705300-687b-11eb-9ffb-97ab0be582fb.png)

This log was collected on Chrome desktop version by attaching to Samsung Internet browser on Samsung Galaxy S7.

Further inspection of minified code shows that error is originating from the following line:

![image](https://user-images.githubusercontent.com/34662138/107117537-27077b80-687b-11eb-881d-4cdd3f553ada.png)

We have isolated this portion of code on Angular code base for versions 11.1.x:

![image](https://user-images.githubusercontent.com/34662138/107117542-3686c480-687b-11eb-88f6-429bfe0d2da5.png)

This code extract is from trusted_types.ts file in core/src/util/security folder.

Applications are tested and working on Safari, Chrome and Firefox. It is Samsung Internet browser that has an issue with this. We have tried multiple devices with Samsung Internet, results are the same.

**Comment by petebacondarwin** [comment] 2021-02-06 12:36
I believe this is basically a duplicate of https://github.com/angular/angular/issues/40507, where the Chrome 83 browser crashes at the same point. I wonder what the underlying browser is for Samsung Internet Browser?
cc @IgorMinar

**Comment by petebacondarwin** [comment] 2021-02-06 12:38
Let's keep the discussion of this problem on #40507. Closing here. Thanks for the great investigation and report @appimpact

**Closed by petebacondarwin** 2021-02-06 12:38 UTC
