### ISSUE TITLE
Cannot determine if animation player has started

### ISSUE THREAD

**Issue by wnvko** [angular/angular#40472] opened 2021-01-18 14:27 UTC
# 🐞 bug report

### Affected Package
@angular/animations

### Is this a regression?
No, not a regression.

### Description
There is no way to determine if there is running animation at given moment after first call to `AnimationPlayer` `play` method.

I am building `AnimationPlayer` in order to animate a given part of my application. Before I call `player.play()` method if I check `player.hasStarted()` it returns `false` which is ok. After first call to `player.play()` `player.hasStarted()` returns `true` when:
- I check immediately after `player.play()` call - this is ok.
- I check in `onDone` handler - not sure if this is ok. Player has started but it is also has ended.
- I check after animation is done and I call `player.reset()` - this is not ok. I am resetting the player and I expect everything to be set to its initial value.

Whatever I do `hasStarted` returns `true` after first call to `play`.

## 🔬 Minimal Reproduction
Reproducing sample at this repository - https://github.com/wnvko/AngularAnimationsIssue
Steps:
- clone, `npm i` and then `ng serve -o`.
- click on the button.
- click again on the button.

Observe how `hasStarted` changes.

## 🔥 Exception or Error
No exception or errors are thrown. Just behavior is not correct.

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 11.0.7
Node: 12.16.1
OS: win32 x64

Angular: 11.0.9
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.7
@angular-devkit/build-angular   0.1100.7
@angular-devkit/core            11.0.7
@angular-devkit/schematics      11.0.7
@angular/cli                    11.0.7
@schematics/angular             11.0.7
@schematics/update              0.1100.7
rxjs                            6.6.3
typescript                      4.0.5
</code></pre>

**Comment by 0biWanKenobi** [comment] 2021-03-05 10:06
This is very, very old stuff and apparently no one ever fixed it: #18140

**Comment by iRealNirmal** [comment] 2021-04-13 12:26
@petebacondarwin  @jelbourn  this Is duplicate of [#18140](https://github.com/angular/angular/issues/18140) as mentioned by  @0biWanKenobi . Can we close  this.

**Closed** 2021-04-13 20:17 UTC
Labels: comp: animations, feature
