### ISSUE TITLE
Ivy compiler should abort on fatal errors

### ISSUE THREAD

**Issue by Wintermoose** [angular/angular#34396] opened 2019-12-13 15:02 UTC
# 🐞 bug report

### Affected Package
Angular compiler

### Is this a regression?
Don't know

### Description
Let's have an angular library containing components and compiled by Ivy (enableIvy: true). Let's assume the library's module imports (in ES6 sense) an invalid module and add it to the module's imports  (this can happen easily either as a typo, or result of 3rd party modules being renamed / deprecated).

With the ivy compiler, we get correct report about invalid import, but after that the compiler reports every single custom component, pipeline and attribute used by the library's components. This can be easily thousands of lines.

When ivy is disabled, we get property only the import error. The error message itself is confusing, _"Unexpected value 'XY in XYZ' imported by the module 'TestlibModule in DIRtestlib.module.ts'. Please add a @NgModule annotation."_
but at least it's not drowned in the rest.

From my tests it seems this is a problem only when compiling libraries, not applications.

## 🔬 Minimal Reproduction
Create the default angular library using angular schematics, enable ivy, and modify the library's module to something like: 
<pre><code>
import { NgModule } from '@angular/core';
import { bla } from "@angular/common";
import { TestlibComponent } from './testlib.component';
import { CommonModule } from "@angular/common";
import { RouterModule } from "@angular/router";
import { FormsModule, ReactiveFormsModule } from "@angular/forms";

@NgModule({
  imports: [
    bla,
    CommonModule,
    RouterModule,
    FormsModule,
    ReactiveFormsModule,
  ],
  exports: [
    TestlibComponent
  ],
  declarations: [
    TestlibComponent
  ]
})
export class TestlibModule { }
`
</code></pre>
In addition, TestComponent should use for example the async pipe, or ngModel

## 🌍  Your Environment

**Angular Version:**
<pre><code>
@angular-devkit/architect          0.900.0-rc.6
@angular-devkit/build-angular      0.900.0-rc.6
@angular-devkit/build-ng-packagr   0.900.0-rc.6
@angular-devkit/build-optimizer    0.900.0-rc.6
@angular-devkit/build-webpack      0.900.0-rc.6
@angular-devkit/core               9.0.0-rc.6
@angular-devkit/schematics         9.0.0-rc.6
@ngtools/webpack                   9.0.0-rc.6
@schematics/angular                9.0.0-rc.6
@schematics/update                 0.900.0-rc.6
ng-packagr                         9.0.0-rc.2
rxjs                               6.5.3
typescript                         3.6.4
webpack       

</code></pre>

**Comment by JoostK** [comment] 2019-12-16 19:41
Closing as duplicate of #33849.

**Closed by JoostK** 2019-12-16 19:41 UTC
Labels: comp: compiler, comp: ivy
