### ISSUE TITLE
lazy load large html page takes too much time

### ISSUE THREAD

**Issue by rravindranaik111** [angular/angular#32958] opened 2019-10-02 12:47 UTC
We are trying to build angular base app which contain large html file sizes. We used lazy loading for that purpose. However it seems that when our html page size is more than 300 kb it takes almost 80 seconds to load the view. We are stuck in that. After first load when we are revisit that page it will be loading fast(May be due to cache).

Can anyone guide on the same ?

**Comment by mlc-mlapis** [comment] 2019-10-02 13:24
@rravindranaik111 Do you understand that the lazily loaded module is JS code in fact and it has no direct relation to HTML, which is rendered in the DOM after loading during instantiation of such a module? It's absolutely unclear what you are trying to do.

**Comment by trotyl** [comment] 2019-10-02 13:25
Most likely duplicate of https://github.com/angular/angular/issues/28270

**Comment by rravindranaik111** [comment] 2019-10-02 13:55
@mlc-mlapis : Thanks for your reply. I know it is lazy loading and not eagerly loading. Landing page is not the issue for loading at initial stage but suppose one menu loading the page which is having html size more than 300 Kb it took time to rendering the page

There are lots of pages which are having html size more than 300 Kb and it gives me same output for rendering, while if we test with removing html code, it gives proper rendering.

**Comment by rravindranaik111** [comment] 2019-10-02 14:00
@trotyl : Thanks for your reply. 

It seems that we have to try the following link : 
https://github.com/angular/angular/issues/28270#issuecomment-521596801

I will try and let you know the same.

**Comment by atscott** [comment] 2019-10-02 16:52
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.

**Closed by atscott** 2019-10-02 16:52 UTC
