### ISSUE TITLE
Angular 9 Issue with MIME Types for Production Build

### ISSUE THREAD

**Issue by ansonfoong** [angular/angular#37037] opened 2020-05-10 10:16 UTC
So I have an Angular 9 application, it has 3 main routes:
/ - Home
/dashboard
/dashboard/guilds

To get to the Dashboard, you can either click a link and have the router navigate you, or you can directly enter it in in your address bar: /dashboard

In the dashboard route, there is a button that when clicked, it will programmatically navigate with the router to /dashboard/guilds. I can then view my component just fine, however, if I refresh the page, I get this issue:

```
Failed to load module script: The server responded with a non-JavaScript MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.
06:12:19.128 polyfills-es2015.3fd94ed6a324eee92aec.js:1 Failed to load module script: The server responded with a non-JavaScript MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.
06:12:19.128 main-es2015.0b1d748ffcf78a2a0b26.js:1 Failed to load module script: The server responded with a non-JavaScript MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.
```

I don't know why, it works fine locally, so I guess it's something to do with my Production Server? I have NGINX running. If needed, I will provide the server block config.

I've tried some stuff here: https://github.com/angular/angular/issues/30835 but I've never had this issue with Angular 8 before. And this one seems very specific, it's not like the page doesn't load, it just throws that error if I try to manually visit that route instead of letting the Angular Router navigate for me.

index.html from build 
```
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>SomeWebsite</title>
  <base href="./">  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
  <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<link rel="stylesheet" href="styles.8426c2fc899c530c7f78.css"></head>
<body class="mat-typography">
  <app-root></app-root>
<script src="runtime-es2015.0811dcefd377500b5b1a.js" type="module"></script><script src="runtime-es5.0811dcefd377500b5b1a.js" nomodule defer></script><script src="polyfills-es5.c219b7059a7feb126472.js" nomodule defer></script><script src="polyfills-es2015.3fd94ed6a324eee92aec.js" type="module"></script><script src="main-es2015.0b1d748ffcf78a2a0b26.js" type="module"></script><script src="main-es5.0b1d748ffcf78a2a0b26.js" nomodule defer></script></body>
</html>
``` I've tried changing type="text/javascript" but no luck, I just got some "> token error" I don't really remember.

I'm not sure what else is needed, but if anyone knows what the issue and how I could fix it, I would appreciate it.

**Comment by pkozlowski-opensource** [comment] 2020-05-10 16:38
Sounds like a duplicate of #30835, see the relevant discussion there (especially https://github.com/angular/angular/issues/30835#issuecomment-616610138)

**Closed by pkozlowski-opensource** 2020-05-10 16:38 UTC
