### ISSUE TITLE
Multiple query params with the same name (url?foo=bar&foo=baz)

### ISSUE THREAD

**Issue by JiriBalcar** [angular/angular#11662] opened 2016-09-16 12:35 UTC
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Expected behavior**
Posibility to have multiple query params with the same name `url?foo=bar&foo=baz`

**Reproduction of the problem**
not currently possible with angular2 and router

**What is the motivation / use case for changing the behavior?**
align with `@angular/http URLSearchParams`

* **Angular version:** 2.0.0-rc.X
2.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
all
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

**Comment by ericmartinezr** [comment] 2016-09-16 13:00
https://github.com/angular/angular/issues/11374

**Comment by pkozlowski-opensource** [comment] 2016-09-16 14:27
Indeed duplicate of #11374. Thnx @ericmartinezr !

**Closed by pkozlowski-opensource** 2016-09-16 14:27 UTC

**Comment by spacebeers** [comment] 2016-09-19 09:51
We're looking at this in #11374. Feel free to add your weight to that issue.

**Comment by jtomaszewski** [comment] 2016-09-23 16:35
#11374 is about the bug in a router, and this is more about @angular/http ( https://github.com/angular/angular/blob/671f73448cea4736e44a1949246fdb37c81db277/modules/%40angular/http/src/url_search_params.ts ) . Should it be the same issue or a separate one?

**Comment by jtomaszewski** [comment] 2016-09-24 10:52
For now I ended up replacing `URLSearchParams.toString()` with my own implementation.  You can as well just pass url string instead of the URLSearchParams object to RequestOptions, but typescript yells with a wrong type error, so you'd need to cast it to <any>.

Workaround for now:

```ts
class MyURLSearchParams extends URLSearchParams {
  toString(): string {
    const params = {};
    this.paramsMap.forEach((v, k) => {
      params[k] = v[0];
    });
    return $.param(params); // or any other your custom function you use to serialize search query
  }
}
```

**Comment by JiriBalcar** [comment] 2016-09-26 14:37
@jtomaszewski This issue is about router. Http URLSearchParams do support arrays as
`let params = new URLSearchParams();
params.append('foo', 1);
params.append('foo', 2);`

**Comment by miloskovacevic** [comment] 2018-04-18 12:41
thanks @JiriBalcar
