### ISSUE TITLE
Request for beforeNgDestroy or onDestroy refs of the destroyed DOM.

### ISSUE THREAD

**Issue by smkrn110** [angular/angular#33680] opened 2019-11-08 07:18 UTC
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/....

### Description
 I need to do stuff with the destroying DOM, but found ngDestroy calls after the DOM was removed.

### Describe the solution you'd like

  I want some lifecycle hook before ngDestroy (better) 

### Describe alternatives you've considered

 or the reference of the destroyed DOM (object) in ngDestroyed

**Comment by Airblader** [comment] 2019-11-08 12:37
You should describe *what* you are looking to do specifically if you want to argue in favor of adding a hook. Perhaps there are other, existing solutions.

**Comment by pkozlowski-opensource** [comment] 2019-11-13 10:12
This is a duplicate of the existing issue #17404 - let's centralise the discussion in-there.

**Closed by pkozlowski-opensource** 2019-11-13 10:12 UTC
Labels: comp: core, type: feature
