### ISSUE TITLE
Lifecycle hooks don't fire when using arrow syntax

### ISSUE THREAD

**Issue by aj-r** [angular/angular#24178] opened 2018-05-29 14:38 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

When using arrow function syntax, lifecycle hooks (ngOnInit, ngOnChanges, etc.) are never called.

```ts
class MyComponent implements OnInit {
    public ngOnInit = () => {
    }
}
```

Using non-arrow syntax works as expected:

```ts
class MyComponent implements OnInit {
    public ngOnInit() {
    }
}
```

## Expected behavior

Arrow syntax should work.

If this is impossible for some reason, then the documentation needs to be *very clear* that you cannot do this. It took many many hours for me to isolate the cause of this issue because this behavior is very unexpected (after all, I've implemented the `OnInit` interface correctly). It would also be nice if codelyzer triggered an error if you do this (as part of the `use-life-cycle-interface` rule, or possibly a new rule).

## Minimal reproduction of the problem with instructions

See code above or stackblitz: https://stackblitz.com/edit/angular-ngoninit-arrow

## What is the motivation / use case for changing the behavior?

We (almost) always use arrow functions, especially when using `this`, to avoid any potential issues with `this` being set to the wrong value. While angular may ensure that `this` is always set correctly when calling `ngOnInit`, I think it should still allow the arrow syntax for people who are in the habit of using it.

## Environment

<pre><code>
Angular version: 6.0.1

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.9.4  
- Platform:  Windows

Others:
- Using JIT, but I expect the issue would also happen with AOT.
- Used both angular CLI and plain webpack to reproduce the issue.

</code></pre>

**Comment by splincode** [comment] 2018-05-29 15:49
tsconfig.js

```json5
{
  "compilerOptions": {
    "target": "es5",
    //  ...
}
```

ES6

```ts
class A { 
    public ngOnit() {
    
    }
}
```

ES6 to ES5  (transpile)

```ts
var A = /** @class */ (function () {
    function A() {
    }
    A.prototype.ngOnit = function () {
    };
    return A;
}());
```
-------

ES6 with arrow function

```ts
class A { 
    public ngOnit = () => {
    
    }
}
```

ES6 to ES5 (transpile)

```ts
var A = /** @class */ (function () {
    function A() {
        this.ngOnit = function () {
        };
    }
    return A;
}());
```

**Comment by aj-r** [comment] 2018-05-29 15:54
Interesting - so Angular can only call `ngOnInit` if it exists on the prototype. I feel like Angular should look for `ngOnInit` on the instance, instead of the prototype?

**Comment by trotyl** [comment] 2018-05-30 02:55
Duplicate of https://github.com/angular/angular/issues/19240

**Comment by aj-r** [comment] 2018-05-30 03:16
Ok, so it looks like this isn't reasonable to do. Can we clarify this in the documentation then?

**Comment by splincode** [comment] 2018-05-30 08:14
@alexeagle add a label to the documentation

**Comment by mhevery** [comment] 2018-06-26 22:32
As described in https://github.com/angular/angular/issues/7270#issuecomment-201137617 this is by design. Doing this would make the runtime slower and it would prevent tree shaking. so we are not going to implement this.

**Closed by mhevery** 2018-06-26 22:32 UTC
Labels: comp: core & compiler
