### ISSUE TITLE
RuntimeCompiler availability in AOT

### ISSUE THREAD

**Issue by vasuneet** [angular/angular#14034] opened 2017-01-20 13:21 UTC
As per the following issue -> 
 https://github.com/angular/angular/issues/11780
Compiler is not available in AOT. Do we have this available in near future in upcoming releases of Angular ?

regards
Vasuneet Arya

**Comment by DzmitryShylovich** [comment] 2017-01-20 13:25
Nope

**Comment by vasuneet** [comment] 2017-01-20 14:55
So what should we do in case there are 90% components which we can precompile but few are components which we need to compile on runtime. Any suggestion or path-forward ?

**Comment by robwormald** [comment] 2017-01-20 21:28
@vasuneet can you explain what cases you think you need to compile at runtime? We *strongly* suggest avoiding this, as it will forever couple you to shipping the (large, slow) compiler at runtime.

**Comment by vasuneet** [comment] 2017-01-23 09:12
I have created a framework based on that i created some components which provide the feature to inject template using argument like the below : 
<mycomponent widget-templates='{"state1":"template1.html","state2":"template2.html"></mycomponent>

As ng2 does not provide the way to accept this template on runtime. I mean somehow i need to compile it as i am providing templates on dynamic basis. So to do that I have urgent requirement to compile it dynamically. However there are very few components for this but it is necessary feature we need . As we are going to integrate this with template authoring tool where template authoring should be done at their end. If we will not be able to author our template using authoring tool and . this integration will not be accepted at all. 
We already done the same thing earlier in ng1.

**Comment by vasuneet** [comment] 2017-01-24 09:57
Any update on this?

**Comment by straccia17** [comment] 2017-01-29 01:42
I have a similar case.

In my project I have a dashboard component and its template depends on which user is logged in the platform. With not-AoT version of this project, the dashboard component gets the template from API server, then compiles it and injects results in its ViewContainerRef.
Now, I would use AoT to increase the performance but without the compiler I think that it's not possible.

**Comment by DzmitryShylovich** [comment] 2017-02-01 11:50
@pkozlowski-opensource duplicate of https://github.com/angular/angular/issues/11780

**Comment by pkozlowski-opensource** [comment] 2017-02-01 13:57
Closing as a duplicate of #11780. Thnx @DzmitryShylovich

**Closed by pkozlowski-opensource** 2017-02-01 13:57 UTC
