### ISSUE TITLE
Getter returning Date into an ngModel causes browser crash

### ISSUE THREAD

**Issue by damiandennis** [angular/angular#12288] opened 2016-10-14 00:35 UTC
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Currently if you return a new Date() from a getter into an ngModel it freezes up the browser.

**Expected behavior**
That it would not cause an infinite loop

**Minimal reproduction of the problem with instructions**
have a getter method that returns a new Date() and put into an ngModel;
http://plnkr.co/edit/I0i4h6pu9ZqGfJk3XTNy?p=info

**What is the motivation / use case for changing the behavior?**
to be able to use a generated Date in ngModel.

**Please tell us about your environment:**
Ubuntu / Apache

* **Angular version:** 2.1.0
Also was doing this in 2.0.0

* **Browser:** [Chrome 53.0.2785.143]
 
* **Language:** [all | TypeScript 2.0.3]

**Comment by pkozlowski-opensource** [comment] 2016-10-14 07:59
This is duplicate of #11097 and indeed something that needs to be covered. The proper solution will come from #3009.

@kara as mentioned previously lack of parserrs / formatters - like mechanism is a deal-breaker for controls that want to work with a more elaborate data model. I would like once again to extend my offer to collaborate on the topic. In the meantime closing this one as a duplicate of  #11097

**Closed by pkozlowski-opensource** 2016-10-14 07:59 UTC
Labels: comp: forms
