### ISSUE TITLE
update.angular.io hangs in Edge

### ISSUE THREAD

**Issue by sdurnov** [angular/angular#23959] opened 2018-05-17 10:14 UTC
## I'm submitting a...
<pre><code>
[x] Bug report
</code></pre>

## Current behavior
<pre><code>
update.angular.io site hangs after performing any interaction with controls
</code></pre>

## Expected behavior
<pre><code>
Site should work as usual.
</code></pre>

## Minimal reproduction of the problem with instructions
<pre><code>
Open update.angular.io in Edge desktop or mobile browser, click on "To" combobox to open it. Click outside of combobox. See site not responding to input anymore.
</code></pre>

## Environment
<pre><code>
Browser:
- [x] Edge version 42.17134.1.0 desktop, 40.15254.401.0 mobile
Others:
Windows 10 x64 build 1803, Windows Mobile 10 v.1709
</code></pre>

**Comment by gkalpak** [comment] 2018-05-17 10:28
Duplicate of StephenFluin/angular-update-guide#14.
(cc @StephenFluin)

**Closed by gkalpak** 2018-05-17 10:28 UTC
