### ISSUE TITLE
Observable updates aren't reflected in templates if their change origin is not the application itself

### ISSUE THREAD

**Issue by paztis** [angular/angular#35579] opened 2020-02-20 13:27 UTC
### Environment

NodeJS Version: 12.13.1
Typescript Version: 3.7.5
Angular Version: 9.0.1
@angular-redux/store version: 10.0.0
@angular/cli version: (if applicable)
rxjs: 6.5.4
OS: Windows

### Problematic:

In below sample, redux observable updates are not displayed in the templates.
state.loader.counter is a number that is increased each second.
It incrementation is developed out of angular application (external library)
The console log well display the new value each second.

But we only see the first value on the screen

```
import {Component, OnInit} from '@angular/core';
import {select} from '@angular-redux/store';
import {Observable} from 'rxjs';

@Component({
  selector: 'app-loader',
  template: `<div>Counter: {{ loaderCounter$ | async }}</div>`,
})
export class LoaderComponent implements OnInit {
  ngOnInit() {
    this.loaderCounter$.subscribe((counter) => {
      console.log('----counter', counter)
    })
  }

  @select((state) => {return state.loader.counter}) loaderCounter$: Observable<number>;
}
```

it I create a "fake" activity on my component, it is working:

This code is working:
```
import {Component, OnInit} from '@angular/core';
import {select} from '@angular-redux/store';
import {Observable} from 'rxjs';

@Component({
  selector: 'app-loader',
  template: `<div>Counter: {{ loaderCounter$ | async }}</div>`,
})
export class LoaderComponent implements OnInit {
  ngOnInit() {
        setInterval(() => {
        }, 100)
  }

  @select((state) => {return state.loader.counter}) loaderCounter$: Observable<number>;
}
```

It seams if the observable change origin is out of angular application, angular is not considering its change.

Problem originally reported on angular-redux https://github.com/angular-redux/platform/issues/112

**Comment by pkozlowski-opensource** [comment] 2020-02-20 14:14
Hi there! Could you please provide a minimal reproduction scenario in a stackblitz or similar? There are multiple things that are not clear at all based on the description provided - we need a reproduce scenario to be able to diagnose / fix.

**Comment by paztis** [comment] 2020-02-20 15:08
Create one env here: https://stackblitz.com/edit/angular-pzlx1q?file=src%2Fapp%2Fapp.component.ts

It's a bit special as scenario
I create a window global value window.BUMP_MY_OBSERVER
It's a function you can call in your browser console to update your Observable.

##### Failing scenario 
- open the app in a browser (chrome for me) => https://angular-pzlx1q.stackblitz.io/
- open your console
- type `BUMP_MY_OBSERVER()`
- you may see in the logs `----bump from outside`
- rendering is not updated at all

##### Working scenario
- in the stackblitz (https://stackblitz.com/edit/angular-pzlx1q?file=src%2Fapp%2Fapp.component.ts) uncomment this code block
```// UNCOMMENT IT: IT WORKS
    setInterval(() => {
      if (window['BUMP_MY_OBSERVER']) {
        window['BUMP_MY_OBSERVER']()
      }
    }, 1000);
```
- now each second the observable is updated from inside the app
- refresh your browser
- see the Bump value on the screen updated each second

**Comment by paztis** [comment] 2020-02-20 15:32
I've update the env to add a 3rd case:

##### Working scenario 3
- in the stackblitz (https://stackblitz.com/edit/angular-pzlx1q?file=src%2Fapp%2Fapp.component.ts)
- comment this code block
```
   // Senario 3
   // UNCOMMENT IT: IT WORKS
    setInterval(() => {
      if (window['BUMP_MY_OBSERVER']) {
        window['BUMP_MY_OBSERVER']()
      }
    }, 1000);
```
- uncomment this code block
```
    // Senario 3
    // UNCOMMENT IT: IT WORKS
    setInterval(() => {}, 100);
```
- in your browser console run `BUMP_MY_OBSERVER()`
- it works here thank't to the empty interval to simulate an activity on the App

**Comment by JiaLiPassion** [comment] 2020-02-21 01:08
@paztis, the behavior is by design, the the subscription callback will run in the same zone when the `observer.next()` is called, so because you call `BUMP_MY_OBSERVER()` outside of `ngZone`, so the callback will also run outside of ngZone.

There are several methods to make it work.

1. reference this doc https://github.com/angular/angular/blob/master/packages/zone.js/NON-STANDARD-APIS.md, import `zone-patch-rxjs` in the `polyfills.ts` to make the callback of the subscription run in the zone when the subscription is created.

2. call `ngZone.run()` in the subscription callback.

**Comment by paztis** [comment] 2020-02-21 06:13
Rxjs patching is not too heavy in term of performances ?
BUMP_MY_OBSERVER was just an example. My real problem came from 'redux' / angular redux. Don't we have a zonejs patch for this ?

**Comment by paztis** [comment] 2020-02-21 06:16
Ok it seems to be this exact issue in angular-redux: https://github.com/angular-redux/platform/issues/105

Thanks for all these infos

**Comment by mhevery** [comment] 2020-03-05 23:50
closing as dup of angular-redux/platform#105

**Closed by mhevery** 2020-03-05 23:50 UTC
Labels: comp: core, comp: zones
