### ISSUE TITLE
Empty base path within a module's routing loaded using loadChildren does not work with named outlet navigation.

### ISSUE THREAD

**Issue by davidwalschots** [angular/angular#14243] opened 2017-02-02 08:38 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Having an empty base path within a module's routing loaded using loadChildren does not work with named outlet navigation.

**Expected behavior**
Empty base path does work as documented in the [Angular documentation on asynchronous routing](https://angular.io/docs/ts/latest/guide/router.html#!#asynchronous-routing). Note that this issue occurs both with asynchronous routing (path-based) loadChildren usage as well as with `loadChildren: () => Module`.

**Minimal reproduction of the problem with instructions**
[This](https://plnkr.co/edit/ps0ZiD3mHTte227Ws69T?p=preview) plunker shows the problem.
Clicking the 'Contact' link doesn't work and produces the error "Cannot match any routes."

_**app-routing.module**_
```
const appRoutes: Routes = [
  { path: 'admin', loadChildren: () => AdminModule },
  { path: '',   redirectTo: '/admin', pathMatch: 'full' }
];
```

_**admin-routing.module**_
```
const adminRoutes: Routes = [
{ 
  path: '', 
  component: AdminComponent,
  children: [ 
    {
      path: 'compose',
      component: ComposeMessageComponent,
      outlet: 'popup'
    }
  ]
}];
```

[This](https://plnkr.co/edit/HrsFvUuPgo9KvlDQJ9uk?p=preview) plunker *does* work.

_**app-routing.module**_
```
const appRoutes: Routes = [
  { path: 'admi', loadChildren: () => AdminModule },
  { path: '',   redirectTo: '/admi/n', pathMatch: 'full' }
];
```

_**admin-routing.module**_
```
const adminRoutes: Routes = [
{ 
  path: 'n', 
  component: AdminComponent,
  children: [ 
    {
      path: 'compose',
      component: ComposeMessageComponent,
      outlet: 'popup'
    }
  ]
}];
```

The key difference is the adminRoutes path not being empty.

**Please tell us about your environment:**

* **Angular version:** 2.4.5

* **Browser:** all
 
* **Language:** all

**Comment by dejour** [comment] 2017-02-02 11:37
`private expandSegmentAgainstRoute(
      injector: Injector, segmentGroup: UrlSegmentGroup, routes: Route[], route: Route,
      paths: UrlSegment[], outlet: string, allowRedirects: boolean): Observable<UrlSegmentGroup> {
    if (getOutlet(route) !== outlet) return noMatch(segmentGroup);
    if (route.redirectTo !== undefined && !(allowRedirects && this.allowRedirects))
      return noMatch(segmentGroup);
    if (route.redirectTo === undefined) {
      return this.matchSegmentAgainstRoute(injector, segmentGroup, route, paths);
    } else {
      return this.expandSegmentAgainstRouteUsingRedirect(
          injector, segmentGroup, routes, route, paths, outlet);
    }
  }` I think problem lies here. if segment group outlet doesn't equal route outlet. then empty path doesn't match which cause match failed

**Comment by jimjim2a** [comment] 2017-03-04 20:42
I have exactly the same issue. It occurs also on 4.0.0 RC2

**Comment by fatalcaron** [comment] 2017-05-20 13:58
I have the same issue (v4.1.3) and it seem really quiet here.

**Comment by PCASME** [comment] 2017-08-11 11:09
Same here with 4.3.1

**Comment by jimjim2a** [comment] 2017-08-24 15:02
+1

**Comment by knightcode** [comment] 2017-12-02 01:01
+1  (5.0.4)

**Comment by ajaytiwari52** [comment] 2018-01-11 11:19
I have similar issue in angular 5.0.5

**Comment by quangtvdevnet** [comment] 2018-06-18 05:31
Hi Guys,

I need a solution for this. do you have any ideas?

**Comment by gxolin** [comment] 2018-12-06 17:57
I have similar issue in 7.1.1

**Comment by atscott** [comment] 2020-05-26 20:41
This appears to be a duplicate of #10726.

**Closed by atscott** 2020-05-26 20:41 UTC
Labels: comp: router, freq3: high, router: aux routes, severity3: broken, triage #1, type: bug/fix
