### ISSUE TITLE
Probably missing polyfill from latest Angular => doesn't run in old browsers!

### ISSUE THREAD

**Issue by peternagy1332** [angular/angular#27162] opened 2018-11-18 23:45 UTC
# 🐞 bug report

### Affected Package
I think no @angular/* packages are affected.

### Is this a regression?
I haven't tested it yet.

### Description
Even though I've uncommented all imports in polyfills.ts, I can't open a freshly created Angular project on my old phone (see the picture below).
I'm sure that some polyfills might have missed out since it works with `import 'core-js';`.
I've tested it with an LG-D280, Chrome 34.0.1847.114.

## 🔬 Minimal Reproduction
`ng new` with routing included and SCSS

## 🔥 Exception or Error
![image](https://user-images.githubusercontent.com/11172720/48679728-2a2bc980-eb94-11e8-846f-fe8858b7acf9.png)

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 7.0.6
Node: 11.0.0
OS: win32 x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.10.6
@angular-devkit/core         7.0.6
@angular-devkit/schematics   7.0.6
@schematics/angular          7.0.6
@schematics/update           0.10.6
rxjs                         6.3.3
typescript                   3.1.6
</code></pre>

**Comment by hiepxanh** [comment] 2018-11-20 02:08
agree, this feature is important for ionic to develop on old android mobile

**Comment by shaxxx** [comment] 2018-11-20 18:34
It works for me on Android 4.4 Kitkat x86 emulator 
`WebView in com.android.browser (Version/4.0 Chrome/30.0.0.0)`

```
Angular CLI: 7.0.6
Node: 11.2.0
OS: win32 x64
Angular: 7.0.4
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.10.6
@angular-devkit/build-angular     0.10.6
@angular-devkit/build-optimizer   0.10.6
@angular-devkit/build-webpack     0.10.6
@angular-devkit/core              7.0.6
@angular-devkit/schematics        7.0.6
@angular/cli                      7.0.6
@ngtools/webpack                  7.0.6
@schematics/angular               7.0.6
@schematics/update                0.10.6
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.19.1
```
Just uncommented these lines in pollyfills.ts
```
 import 'core-js/es6/symbol';
 import 'core-js/es6/object';
 import 'core-js/es6/function';
 import 'core-js/es6/parse-int';
 import 'core-js/es6/parse-float';
 import 'core-js/es6/number';
 import 'core-js/es6/math';
 import 'core-js/es6/string';
 import 'core-js/es6/date';
 import 'core-js/es6/array';
 import 'core-js/es6/regexp';
 import 'core-js/es6/map';
 import 'core-js/es6/weak-map';
 import 'core-js/es6/set';
```

**Comment by jenniferfell** [comment] 2018-11-27 23:40
@mhevery : Can you provide some insight on what needs to be updated in doc? Or direct me to an engineer for this? Thanks!

**Comment by IgorMinar** [comment] 2018-11-28 00:06
This looks like a zone.js issue. @JiaLiPassion could you take a look please?

**Comment by JiaLiPassion** [comment] 2018-11-28 06:32
@IgorMinar, sure, I will check it.

**Comment by hiepxanh** [comment] 2018-11-28 08:42
hello sir, we have huge problem here at ionic 4 beta version. [Ionic 4 won't work in android 5 #15438](https://github.com/ionic-team/ionic/issues/15438) is have more detail information. We keep blaming each other and the dev team because we don't have true solution. Can you take a little free time to visit here and help us? I'm really apprecitate this and thank you so much.
love angular team ❤️

**Comment by JiaLiPassion** [comment] 2018-12-01 14:08
@peternagy1332, @IgorMinar, sorry for the late reply, this issue has been fixed in `zone.js`.
The issue is here,
https://github.com/angular/zone.js/issues/1078
The PR is here,
https://github.com/angular/zone.js/pull/1079

But `zone.js` has not released with new version, so please wait for the next version of `zone.js`, you can test now by updating your `package.json`,

```
"zone.js": "git://github.com/JiaLiPassion/zone.js#issue-1078-dist"
```

Thanks!

**Comment by spaceribs** [comment] 2019-04-05 14:19
@JiaLiPassion I've verified that this appears to be fixed when bumping the zone.js dependency to `0.9.0`

**Comment by deadmann** [comment] 2019-07-06 12:31
> It works for me on Android 4.4 Kitkat x86 emulator
> `WebView in com.android.browser (Version/4.0 Chrome/30.0.0.0)`
> 
> ```
> Angular CLI: 7.0.6
> Node: 11.2.0
> OS: win32 x64
> Angular: 7.0.4
> ... animations, common, compiler, compiler-cli, core, forms
> ... http, language-service, platform-browser
> ... platform-browser-dynamic, router
> 
> Package                           Version
> -----------------------------------------------------------
> @angular-devkit/architect         0.10.6
> @angular-devkit/build-angular     0.10.6
> @angular-devkit/build-optimizer   0.10.6
> @angular-devkit/build-webpack     0.10.6
> @angular-devkit/core              7.0.6
> @angular-devkit/schematics        7.0.6
> @angular/cli                      7.0.6
> @ngtools/webpack                  7.0.6
> @schematics/angular               7.0.6
> @schematics/update                0.10.6
> rxjs                              6.3.3
> typescript                        3.1.6
> webpack                           4.19.1
> ```
> 
> Just uncommented these lines in pollyfills.ts
> 
> ```
>  import 'core-js/es6/symbol';
>  import 'core-js/es6/object';
>  import 'core-js/es6/function';
>  import 'core-js/es6/parse-int';
>  import 'core-js/es6/parse-float';
>  import 'core-js/es6/number';
>  import 'core-js/es6/math';
>  import 'core-js/es6/string';
>  import 'core-js/es6/date';
>  import 'core-js/es6/array';
>  import 'core-js/es6/regexp';
>  import 'core-js/es6/map';
>  import 'core-js/es6/weak-map';
>  import 'core-js/es6/set';
> ```
these lines are not exist on my project 7.x

**Comment by JiaLiPassion** [comment] 2020-05-28 13:53
Since this one is fixed, will close for now.

**Closed by JiaLiPassion** 2020-05-28 13:53 UTC
Labels: comp: zones, docsarea: compatibility, freq1: low, severity3: broken, type: bug/fix
