### ISSUE TITLE
(service-worker) clientVersionMap is not set on initial startup of the application

### ISSUE THREAD

**Issue by philipooo** [angular/angular#27345] opened 2018-11-29 10:43 UTC
# 🐞 bug report

### Affected Package
@angular/service-worker

### Is this a regression?
No

### Description
`this.clientVersionMap` is not set on initial startup of the application when the storage is clean. But I expect it to be set. Otherwise the application can never get informed about an update.

Repro:
- Setup a new application with service-worker
- run the application
- set a breakpoint to https://github.com/angular/angular/blob/master/packages/service-worker/worker/src/driver.ts#L983
- Application / Clear storage (on chrome)
- reload the application
- update the application
- wait for the break
- inspect `this.clientVersionMap`
- its empty, so version is undefined an the code exits on L985
- => this means the application never gets informed about an update

Workaround: Reload the application. Now `this.clientVersionMap` gets populated in https://github.com/angular/angular/blob/master/packages/service-worker/worker/src/driver.ts#L529 because the storage already hold data.

## 🔬 Minimal Reproduction
I can`t setup a reproduction because there is the need to update the application in the background to trigger the service-worker update process.

## 🔥 Exception or Error
No, Exception or Error. 

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 7.0.6
Node: 8.11.2
OS: win32 x64
Angular: 7.0.4
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.8
@angular/cdk                      7.1.0
@angular/cli                      7.0.6
@angular/flex-layout              7.0.0-beta.19
@angular/material                 7.1.0
@angular/pwa                      0.6.8
@ngtools/webpack                  6.0.8
@schematics/angular               0.6.8
@schematics/update                0.10.6
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.8.3
</code></pre>

**Anything else relevant?**
No

**Comment by gkalpak** [comment] 2018-11-29 17:19
This works as expected. If you cear the cache, then there is no way for the SW to know it has inform a specific client (and we definitely don't want to start informing clients that are already on the latest version that there is an update available). Everything should still work as expected though.
Note that the client will be assigned the latest version as soon as it makes a request [handled by the SW][1], so there is no need to notify the app anyway.

Closing, because everything works as expected afaict, but  feel free to continue the discussion below.
[1]: https://github.com/angular/angular/blob/57dae161c3d0c23723f37e230929386b5e1f30cc/packages/service-worker/worker/src/driver.ts#L410

**Closed by gkalpak** 2018-11-29 17:19 UTC

**Comment by rmedaer** [comment] 2019-02-14 20:35
Hi @gkalpak ,

I recently encountered the same issue (if I well understood @philipooo).
When you load for the first time an application (which is indeed registering a SW). You never receive update event. As you said:

> the client will be assigned the latest version as soon as it makes a request handled by the SW

Well ! But if this client never does a request handled by the SW (which is here the case because it's the **first** time we load the application), it will never be notified because never registered into `this.clientVersionMap`. Btw I see in the debugger that the manifest `ngsw.json` is loaded after app stabilization and an AppVersion is also set in versions.

So if it's the expected behavior, my question is: how to get update event (in `SwUpdate.available`) even at the very first load of the application. Could we force the registration of the client when we execute a `SwUpdate#checkForUpdate()` from the application ?

**Comment by gkalpak** [comment] 2019-02-15 18:42
@rmedaer, I think you are referring to something different. On the very first load, there is no SW to handle your app, so it won't. After the app stabilizes, the SW will be registered and will handle future clients. But there is no way for it to handle current clients (and thus you can't get an update notification event 🤷‍♂️).
