### ISSUE TITLE
compiler.compileModuleAndAllComponentsAsync get a low speed over the first time with --prod mode

### ISSUE THREAD

**Issue by jol5** [angular/angular#29049] opened 2019-03-01 01:44 UTC
**compiler.compileModuleAndAllComponentsAsync get a low speed over the first time with --prod mode**
it will load all components at first time with prod mode . So it will become very slow when loading for the first time.
![image](https://user-images.githubusercontent.com/28615922/53610648-8e840d80-3c06-11e9-9ced-fe0bfbdbad2c.png)

**Comment by alxhub** [comment] 2019-04-04 22:59
@jol5 I'm not sure I understand this reported issue as written.

1) are you saying there has been a regression in the performance of `compiler.compileModuleAndAllComponentsAsync` since a previous version of Angular?

2) can you please include a clear reproduction of the issue, likely a Github repository with step-by-step instructions to demonstrate the problem.

**Comment by alxhub** [comment] 2019-04-09 22:36
Closing for lack of a reproduction and lack of any evidence of a bug.

**Closed** 2019-04-09 22:36 UTC
Labels: comp: core & compiler
