### ISSUE TITLE
Enable partial form components using reactive form directives

### ISSUE THREAD

**Issue by onlyann** [angular/angular#10251] opened 2016-07-23 02:53 UTC
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

A component can only use form reactive directives such as `formControlName` or `formGroupName` when its template contains the `formGroup` directive.
Otherwise, the directives will fail to resolve `ControlContainer`.
This happens because the directives specify the `@Host` metadata on `ControlContainer`.

The only workaround I could find is to inject the ancestor's `ControlContainer` in the child component and associate it to a `formGroup` directive in the child template. 
This only partially solves the issue because this new `formGroup` directive doesn't expose any of the form events such as `ngSubmit`.

**Desired behavior**

The scope of `ControlContainer` resolution should be extended to ancestors.

**What is the motivation / use case for changing the behavior?**

This would enable the following use cases:
- Splitting a large form in sub components.
- Defining a sub form component that gets repeated in a parent form component ( a good example would be an address component used for both postal and business addresses by the parent).

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** [all ] 
 
* **Language:** [all]

**Comment by iXJxkb** [comment] 2016-07-26 23:37
+1
I have the exact same issue and was able to solve in the same way.  Need better support for partial forms.

**Comment by pmowrer** [comment] 2016-08-03 17:53
Another solution is for a "form partial" component to "forward" the `ControlContainer` dependency, providing the `ControlContainer` to its child directives. 

E.g.:

```typescript
const CONTROL_CONTAINER_PROVIDER = new Provider(ControlContainer, {
  useFactory: container => container,
  deps: [FormGroupDirective],
});

@Component({
  viewProviders: [CONTROL_CONTAINER_PROVIDER],
```

**Comment by kara** [comment] 2016-08-09 18:38
@onlyann This looks like a dupe of https://github.com/angular/angular/issues/9281.  The short answer is that the child component needs to implement ControlValueAccessor. See my comment [here](https://github.com/angular/angular/issues/9281#issuecomment-238610807) for a more detailed explanation.

**Closed by kara** 2016-08-09 18:38 UTC

**Comment by onlyann** [comment] 2016-08-09 22:05
@kara I am not convinced that implementing `ControlValueAccessor` is a solution for an example I gave above: what if I want a reusable Address component?
It wouldn't be a single value from the `FormGroup` perspective but another `FormGroup` comprised of several inputs with each input being a distinct `FormControl` with validation rules.
How would you achieve this with a `ControlValueAccessor`?

**Comment by kara** [comment] 2016-08-09 22:18
It's certainly possible to use a FormGroup instead of FormControl.

Here's a quick example: http://plnkr.co/edit/Mm3iJOZZGMQ2OmVitpuc?p=preview

**Comment by onlyann** [comment] 2016-08-09 22:44
Thanks for the Plunker @kara.
From what I read, the address `FormGroup` is transparent to the form `FormGroup`. How does `street` validation error flow to the parent ?

We are using `ControlValueAccessor` in our app where it corresponds to a discrete control and it is fine (datepicker, toggle..).
When this is a subform, it doesn't work quite as well.
My case of extending `ControlContainer` scope would simply allow to have this address component add itself dynamically as a `FormGroup` from the injected root `FormGroup`.

**Comment by kara** [comment] 2016-08-10 01:02
Adding validation has a similar process to value accessors. You implement the validator interface (just a validate() function) and provide it as an NG_VALIDATOR on your custom form control.  Here's an example: http://plnkr.co/edit/Mm3iJOZZGMQ2OmVitpuc?p=preview.

Regarding extending ControlContainer scope, we have had many internal conversations about this. At the end of the day, we don't want to make the boundaries quite that lenient.  Explicitly passing the ControlContainer down or implementing ControlValueAccessor is opt-in.  Otherwise, you might get components that are registering themselves with random, unrelated parent forms (think maybe a third-party component that has an internal checkbox or something).    We do want to add some syntactic sugar to make this process easier, so stay tuned.

**Comment by onlyann** [comment] 2016-08-10 01:07
All right. Thanks for your help.

**Comment by linusbrolin** [comment] 2016-08-10 09:30
@kara What if each Address is inside a formArray, and don't have any formControlName (shipping, billing, etc)?
My component can have an endless supply of addresses, so I can't name each one of them, as it's just an array of objects.

What do I use instead of formControlName in the template to connect each address to the parent form?
Specifically, it's this line I'm wondering about:

    <address formControlName="billing" header="Billing"></address>

**Comment by kara** [comment] 2016-08-10 16:31
You'll just want to set the formControlName to the current index. See here: http://plnkr.co/edit/a9h1jjSaWrNm36cTUvIY?p=preview

**Comment by pmowrer** [comment] 2016-08-10 16:32
Great examples @kara, very helpful!

What about a scenario where `<address>` requires validation in one case, but not in another? This is where the flexibility of defining the entire `FormGroup` structure at the parent level shines. I suppose you could write an address validator that validates the address `FormControl` and internally composes individual field validators like `Validator.required`.

**Comment by advgal** [comment] 2016-09-05 08:48
The plnkrs don't work any more!

**Comment by antonmoiseev** [comment] 2016-09-05 20:16
@advgal here is the version upgraded to RC.6 http://plnkr.co/edit/04MgGi7KYIekO8w1vEKo?p=preview

**Comment by antonmoiseev** [comment] 2016-09-05 20:30
@kara the form stars behave improperly once you replace `setValue()` with `patchValue()`.

[Here](http://plnkr.co/edit/gNaO3z9GYT03H9VjzQSZ?p=preview) is you original example upgraded to RC.6 with few modifications:

1. Instead of using `setValue()` it uses `patchValue()`.
2. When we initialize billing address control we pass one additional property which doesn't have a corresponding FormControl - `country`.

Run the example, attempt to type a street for the _shipping_ address. Note the value of the billing address contains `country` field however there is no FormControl for it. If you now modify billing address' street, `country` disappears from the billing's value.

Does it deserve its own issue?

**Comment by manklu** [comment] 2016-09-18 17:25
For reactive forms, it is possible to tunnel the ControlContainer through the component boundary. Simpy add the following viewProvider.

```javascript
{
  provide: ControlContainer,
  useFactory: (container:ControlContainer) => {
    return container;
  },
  deps: [[ControlContainer, new Optional(), new Host(), new SkipSelf()]]
}
```

Be careful. Thoughtless used, it will give you big headaches and a never ending nightmare.

**Comment by scottseeker** [comment] 2017-05-15 17:49
@manklu Could you explain this code further or perhaps point me to an explanation?  It worked for me in a simple case, but then I tried to apply to my more complex form building components and the application not throws a 'No Provider for ControlContainer' error

**Comment by gilbertowa** [comment] 2017-10-01 01:25
@scottseeker I use this approach with:

`
var controlContainerSubstituto = {
   provide: ControlContainer,
   useFactory: component => component.parent,
   deps: [forwardRef(() => EnderecoComponent)]
};

@Component({
   selector: 'ctrl-endereco'
   , templateUrl: './endereco.component.html'
   , viewProviders: [controlContainerSubstituto]
   , providers: [controlContainerSubstituto]
})
export class EnderecoComponent
{
  constructor(@Host() @SkipSelf() public parent: ControlContainer){
  }
}
`
See images in post https://goo.gl/CJmxEW (but, portuguese)

**Comment by guillep2k** [comment] 2018-02-13 04:11
gilbertogwa's solution is great. I really thinkg there should be an official directive for this to simplify the implementation. The ValueAccessor solution requires a lot of work and quickly becomes a mess of setTimeout, "the value changed" warnings, and statuses not being updated correctly. I've reduced my code by at least 200 lines with Gilberto's method.

**Comment by scottseeker** [comment] 2018-02-13 21:41
Thanks for the responses guys.  I believe what I ended up doing is passing a handle to the 'FormGroup' to child components and referencing it in child templates and everything plays nicely.  Seems like Gilbert's response is a bit cleaner.
