### ISSUE TITLE
Can't bind to 'ngIf' since it isn't a known property of 'div'

### ISSUE THREAD

**Issue by tandu** [angular/angular#32696] opened 2019-09-16 12:31 UTC
# 🐞 bug report

### Description
I'm using the latest angular with ivy. When in sub module in component I'm making any changes related to component drawing (in css or in ts file) it breaks and logs this error in browser:
`Can't bind to 'ngIf' since it isn't a known property of 'div'`
Instead of ngIf here can be any other operator that first is met in html template, even changes in css produces the same issue. If I restart angular with `npm start` it renders content without any errors. `CommonModule` is added to the module.

video that shows how to reproduce the bug:
https://www.dropbox.com/s/1c5d3uccfsqqk7s/crash-on-changes-in-module-component-design.mov?dl=0

## 🔥 Exception or Error
<pre><code>
core.js:4799 ERROR Error: Template error: Can't bind to 'ngIf' since it isn't a known property of 'div'.
    at createUnknownPropertyError (core.js:10178)
    at elementPropertyInternal (core.js:10044)
    at Module.ɵɵproperty (core.js:16508)
    at UsersComponent_Template (users.component.html:1)
    at executeTemplate (core.js:9596)
    at checkView (core.js:11020)
    at componentRefresh (core.js:10778)
    at refreshChildComponents (core.js:9277)
    at refreshDescendantViews (core.js:9176)
    at renderComponentOrTemplate (core.js:9567)
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.2.1
Node: 12.8.0
OS: darwin x64
Angular: 8.2.1
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.802.1
@angular-devkit/build-angular     0.802.1
@angular-devkit/build-optimizer   0.802.1
@angular-devkit/build-webpack     0.802.1
@angular-devkit/core              8.2.1
@angular-devkit/schematics        8.2.1
@ngtools/webpack                  8.2.1
@schematics/angular               8.2.1
@schematics/update                0.802.1
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.38.0
</code></pre>

**Comment by JoostK** [comment] 2019-09-16 13:20
Hi @tandu, thanks for testing Ivy!

This looks like a duplicate of #32217, which has been fixed in #31932. For Ivy testing, please use the `next` preview releases as any fixes related to Ivy are not backported into 8.x. If you experience other issues using the 9.0 preview, feel free to open new issue.

**Closed by JoostK** 2019-09-16 13:20 UTC
