### ISSUE TITLE
support @Attribute() to get all attributes

### ISSUE THREAD

**Issue by erictsangx** [angular/angular#6833] opened 2016-02-02 04:19 UTC
Discussed in #1818 and submitted a PR in #5140. Because the team is rewriting the compiler. The PR cannot be rebased. cc @tbosch 
```javascript
class MyClass {
  constructor(@Attributes() atts: Map<string, string>)
}
//Originally, @Attribute('foo') returns Map.get('foo'), now support @Attribute() to return the Map.

```
PS: About ``@attribute()`` vs ``@attribute``, since all decorators from angular has parentheses and according to the developer guides: 'Always include the parentheses! Always call @Injectable(). Our application will fail mysteriously if we forget the parentheses.' So I think we should use ``@attribute()``

**Comment by kara** [comment] 2016-03-18 19:53
Closing as a duplicate of https://github.com/angular/angular/issues/1818

**Closed by kara** 2016-03-18 19:53 UTC
