### ISSUE TITLE
Type SimpleChanges

### ISSUE THREAD

**Issue by jeronimonunes** [angular/angular#37031] opened 2020-05-09 23:26 UTC
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/core

### Description
I think it could be helpful to type SimpleChanges. I was thinking about doing the necessary changes to the repo and create a PR. I've created the issue so you guys can give me feedback if I can and should do this or if it is better to me to find something else to do. I like Angular and I want to start contributing.

### Current interface:
```ts
export class SimpleChange {
  constructor(public previousValue: any, public currentValue: any, public firstChange: boolean) {}

  isFirstChange(): boolean {
    return this.firstChange;
  }
}

export interface SimpleChanges {
  [propName: string]: SimpleChange;
}
```

### Proposed interface:
```ts
export class SimpleChange<T> {
  constructor(public previousValue: T, public currentValue: T, public firstChange: boolean) {}

  isFirstChange(): boolean {
    return this.firstChange;
  }
}

export type SimpleChanges<T> = { [P in keyof T]?: { previousValue?: T[P], currentValue: T[P] }; }
```

**Comment by pkozlowski-opensource** [comment] 2020-05-10 04:52
We've got already an issue tracking types on `SimpleChanges` - this is a duplicate of #17560. Closing as a duplicate of #17560 - let's centralise the discussion in there.

**Closed by pkozlowski-opensource** 2020-05-10 04:52 UTC
