### ISSUE TITLE
Firebase deployment command mistake in stackblitz project

### ISSUE THREAD

**Issue by vinodhpalz** [angular/angular#35682] opened 2020-02-26 08:49 UTC
Hi Team,

In the stackblitz project, to deploy in Firebase, the command is mentioned as ng deploy, instead of firebase deploy. please change it.

Under the section:
Hosting an Angular app on Firebase

Regards,
Vinodh. PL

**Comment by gkalpak** [comment] 2020-02-26 19:22
I believe `ng deploy` is correct, because the `@angular/fire` package implements deployment capabilities. See the [`ng deploy` docs][1] for more info.

##
Closing this issue, because I believe everything is as intended, but feel free to continue the discussion below in case I missed something.

[1]: https://angular.io/cli/deploy

**Closed by gkalpak** 2020-02-26 19:22 UTC
Labels: comp: docs
