### ISSUE TITLE
Forms.d.ts crashing the entire application

### ISSUE THREAD

**Issue by AndrewPomorski** [angular/angular#39836] opened 2020-11-25 08:01 UTC
# 🐞 bug report

### Affected Package
@angular/forms

### Is this a regression?

It just broke randomly.

### Description
forms.d.ts suddenly crashed my entire application. It seems like some of the imports from angular compiler could not be found.

## 🔥 Exception or Error
<details>
<summary>Part of the stack trace</summary>
<p>
<pre><code>
2513 export declare class FormGroupName extends AbstractFormGroupDirective implements OnInit, OnDestroy {
                                                                                      ~~~~~~
node_modules/@angular/forms/forms.d.ts:2513:90 - error TS2304: Cannot find name 'OnDestroy'.

2513 export declare class FormGroupName extends AbstractFormGroupDirective implements OnInit, OnDestroy {
                                                                                              ~~~~~~~~~
node_modules/@angular/forms/forms.d.ts:2566:63 - error TS2304: Cannot find name 'OnChanges'.

2566 export declare class MaxLengthValidator implements Validator, OnChanges {
                                                                   ~~~~~~~~~
node_modules/@angular/forms/forms.d.ts:2575:26 - error TS2304: Cannot find name 'SimpleChanges'.

2575     ngOnChanges(changes: SimpleChanges): void;
                              ~~~~~~~~~~~~~
node_modules/@angular/forms/forms.d.ts:2612:63 - error TS2304: Cannot find name 'OnChanges'.

2612 export declare class MinLengthValidator implements Validator, OnChanges {
                                                                   ~~~~~~~~~
node_modules/@angular/forms/forms.d.ts:2621:26 - error TS2304: Cannot find name 'SimpleChanges'.

2621     ngOnChanges(changes: SimpleChanges): void;
                              ~~~~~~~~~~~~~
node_modules/@angular/forms/forms.d.ts:2647:43 - error TS2304: Cannot find name 'InjectionToken'.

2647 export declare const NG_ASYNC_VALIDATORS: InjectionToken<(Function | Validator)[]>;
    0m                                           ~~~~~~~~~~~~~~
node_modules/@angular/forms/forms.d.ts:2677:37 - error TS2304: Cannot find name 'InjectionToken'.

2677 export declare const NG_VALIDATORS: InjectionToken<(Function | Validator)[]>;
                                         ~~~~~~~~~~~~~~
node_modules/@angular/forms/forms.d.ts:2686:41 - error TS2304: Cannot find name 'InjectionToken'.
</pre></code>
</p>
</details>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 10.2.0
Node: 14.9.0
OS: darwin x64

Angular: 10.2.0
... animations, cli, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1002.0
@angular-devkit/build-angular   0.1002.0
@angular-devkit/core            8.0.0
@angular-devkit/schematics      8.0.0
@angular/cdk                    10.2.6
@angular/material               10.2.6
@schematics/angular             8.0.0
@schematics/update              0.1002.0
rxjs                            6.6.3
typescript                      4.0.5
webpack                         4.44.2
</code></pre>

**Comment by petebacondarwin** [comment] 2020-11-25 11:46
Hi @AndrewPomorski - sorry to hear about this problem you have. In order to help you we need some more information.
When you say that your project broke randomly, did you make any changes to your project before this happened? For example did you just update to a new version of Angular? Can I check that you have tried removing your `node_modules` and reinstalling them? If this doesn't help can you put together a minimal reproduction of the problem that we can look at and diagnose the cause? Thanks!

**Comment by AndrewPomorski** [comment] 2020-11-25 12:45
Hey @petebacondarwin thank you for your swift reply. This was fixed by deleting node_modules and reinstalling them. I sadly, cannot provide anymore repro steps for that. It's ok with me if this issue gets closed. I cannot provide anymore details on that, as that issue just occurred to me without me doing anything out of the ordinary. It's also the first time anything like that has happened to me.

**Comment by petebacondarwin** [comment] 2020-11-25 12:49
Great. I suspect you just had some out of sync dependencies. Glad you got it working again. I'll close this for now.

**Closed by petebacondarwin** 2020-11-25 12:49 UTC
Labels: comp: compiler, needs reproduction
