### ISSUE TITLE
Cannot find module '@angular/compiler' when using ngc

### ISSUE THREAD

**Issue by georgeedwards** [angular/angular#12173] opened 2016-10-08 20:56 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**

ngc doesn't work. If I run ngc, I then get the response:

```
C:\Users\George\Source\Repos\docs>ngc
module.js:457
    throw err;
    ^

Error: Cannot find module '@angular/compiler'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\George\AppData\Roaming\nvm\v6.7.0\node_modules\@angular\compiler-cli\src\codegen.js:13:16)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
```

**Expected behavior**

ngc to work as described in the docs.

**Minimal reproduction of the problem with instructions**

I assume this is something with my system, but:

1. `npm install @angular/compiler-cli typescript@next @angular/platform-server @angular/compiler`
2. `ngc` (in same dir as above)

**What is the motivation / use case for changing the behavior?**

Use AOT compilation
**Please tell us about your environment:**

Windows 10 Pro, Command Prompt, npm
* **Angular version:** 2.0.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =   6.7.0 (x64)

**Comment by DzmitryShylovich** [comment] 2016-10-08 20:59
Duplicate of https://github.com/angular/angular/issues/11780

**Closed** 2016-10-08 21:21 UTC
