### ISSUE TITLE
[compiler-cli 8.1.0-next.3 w/ Ivy] NgModule error regarding HttpClientModule

### ISSUE THREAD

**Issue by juergenzimmermann** [angular/angular#31253] opened 2019-06-25 11:04 UTC
During compilation I get the following error after upgrading from 8.0 to 8.1:

```
ERROR in node_modules/@angular/common/http/http.d.ts:2799:22 - error TS-996002: Appears in the NgModule.imports of BalkendiagrammModule, but could not be resolved to an NgModule class

2799 export declare class HttpClientModule {
```

**Comment by kara** [comment] 2019-06-25 17:29
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.

**Closed by kara** 2019-06-25 17:29 UTC

**Comment by alexzuza** [comment] 2019-06-29 02:45
@juergenzimmermann Duplicate of https://github.com/angular/angular/issues/30972
