### ISSUE TITLE
wrong error reporting after migrating to v15

### ISSUE THREAD

**Issue by eng-dibo** [angular/angular#48122] opened 2022-11-18 18:33 UTC
### Which @angular/* package(s) are the source of the bug?

compiler, core

### Is this a regression?

Yes

### Description

I was able to run the project in v14 without problems, but after migrating to v15 I found some template errors iwhich I was they are wrong.

1- 
```
 <img
      *ngIf="data.author?.image"
      mat-card-avatar
      src="{{ data.author.image }}"
      alt="{{ data.author.name || null }}"
    />
```
in this snippet, there is an `*ngIf` directive that checks that `data.author?.image` exists, which also implies that `data.author` exists.

but the compiler complains that `data.author` is possibly undefined
![New Bitmap Image](https://user-images.githubusercontent.com/57308531/202776376-1dc53b5d-2630-46fd-9b34-98f5da9fdcbd.jpg)

2- in the same template, this error occures ` NG8001: 'mat-card' is not a known element:` which means that `MatCardModule` doesn't imported

but it is wrong because the module that declares this component imports `MatCardModule`

**reproduction**
be sure you are at the branch 'upgrade-to-angular-15'

1- goto [this file](https://github.com/eng-dibo/dibo/blob/upgrade-to-angular-15/packages/ngx-content-view-mat/src/cards.component/cards.component.html#L3)

this template is a part of the component `card.component.ts` which is declared in the module `ngx-content-view-mat.module.ts`

![New Bitmap Image](https://user-images.githubusercontent.com/57308531/202777264-41f948ef-299b-40b7-b396-6346fbc6f3ae.jpg)

this error gone when I remove `commonModule` from `NgxContentViewMatModule`

### Please provide a link to a minimal reproduction of the bug

https://github.com/eng-dibo/dibo/blob/upgrade-to-angular-15/packages/ngx-content-view-mat/src/cards.component/cards.component.html#L3

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular 15
```

**Comment by JoostK** [comment] 2022-11-20 19:33
Duplicate of #47077.

**Closed by JoostK** 2022-11-20 19:33 UTC
