### ISSUE TITLE
CanLoad guard not taking first value

### ISSUE THREAD

**Issue by kirill-chirkov-at-clouty** [angular/angular#25262] opened 2018-08-02 12:15 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
`CanLoad` guard (as opposed to `CanActivate` guard) not taking `first()` value and listens for a stream completion, thus freezing navigation if such thing occurs.

## Expected behavior
Take first value or add such behavior to docs

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-apbrfc

## What is the motivation / use case for changing the behavior?
Current behavior is unobvious.

## Environment
<pre><code>
Angular version: 6.1.0
</code></pre>

**Comment by trotyl** [comment] 2018-08-02 12:27
Duplicate of https://github.com/angular/angular/issues/10556, https://github.com/angular/angular/issues/18991

**Closed** 2018-08-11 14:12 UTC
Labels: comp: router
