### ISSUE TITLE
Throw an error when a zone is nested within another zone

### ISSUE THREAD

**Issue by adamdbradley** [angular/angular#5406] opened 2015-11-20 13:32 UTC
While it's possible to have a zone running from within another zone, it's more than likely that there's something wrong with the app's or ng2's code. This would be similar to the `$digest already in progress` error seen in 1x.

**Comment by vicb** [comment] 2015-11-20 21:17
@adamdbradley could you expand on your use case ?

a `setTimeout` callback actually runs in a child zone of the zone where `setTimeout` was called (the same goes for event handlers, microtasks, ...)

**Comment by mhevery** [comment] 2016-01-20 18:57
I think the issue is that we are cause double digest. I am not sure why it is happening, but I know how to reproduce this.

**Comment by mhevery** [comment] 2016-02-03 04:13
Blocked on new Zone implementation.

**Comment by IgorMinar** [comment] 2016-09-15 16:05
this was resolved with zone.js 0.6

**Closed by IgorMinar** 2016-09-15 16:05 UTC
Labels: comp: core/compiler, effort2: medium (day), P1: urgent, type: bug
