### ISSUE TITLE
Component does not reflect the reactive Form Control disabled status

### ISSUE THREAD

**Issue by skkalahasti** [angular/angular#26662] opened 2018-10-22 21:01 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

When reference to a form group changes, the input does not reflect the disability status of the form control.

## Expected behavior

The input should reflect the new disability status of the form control.

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/angular-haq7f5

## What is the motivation / use case for changing the behavior?

Lets take we have various profiles on the left and right side section gives the details of the profile. So Users is a FormArray with various FormGroups. On Click of the profile, the user details of that user will be rendered which should also reflect the disability status of the name.

## Environment

<pre><code>
Angular version: 7.0.0

Browser:
- [ x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.9.4  
- Platform: Windows, Mac 

Others:

</code></pre>

**Comment by dylhunn** [comment] 2022-07-11 23:43
Duplicate of #35309

**Closed by dylhunn** 2022-07-11 23:43 UTC
Labels: type: bug/fix, effort2: days, freq2: medium, comp: forms, risk: medium, state: confirmed, P3
