### ISSUE TITLE
Angular CLI wiki: HMR docs are out of date

### ISSUE THREAD

**Issue by pppdns** [angular/angular#29452] opened 2019-03-21 21:32 UTC
# 📚 Docs or angular.io bug report

### Description

Angular's HMR (hot module replacement) docs are old and the steps don't work anymore with `@angularclass/hmr`.
https://github.com/angular/angular-cli/wiki/stories-configure-hmr

-----

I spent a lot of time to get HMR to work based on the [official Angular docs](https://github.com/angular/angular-cli/wiki/stories-configure-hmr) but it seems like these steps don't work anymore. Not sure if **Webpack has changed its API or `@angularclass/hmr`** but the current steps in the [official Angular docs](https://github.com/angular/angular-cli/wiki/stories-configure-hmr) don't work anymore and the new steps that are documented in the original `@angularclass/hmr` docs work pretty well.

These 2 comments explain the simplest solution to get HMR to work with the latest Angular, Webpack and `@angularclass/hmr`:
https://github.com/PatrickJS/angular-hmr/issues/81#issuecomment-449999297
https://github.com/PatrickJS/angular-hmr/issues/81#issuecomment-450028896

**Simplest working solution** (written by @Epono), anyone can clone and run it:
https://github.com/Epono/angular-7-hmr

## 🔬 Minimal Reproduction
Just follow the steps in the [official Angular docs](https://github.com/angular/angular-cli/wiki/stories-configure-hmr) on a new Angular project `ng new test-app` and it won't work.

### What's the affected URL?**
https://github.com/angular/angular-cli/wiki/stories-configure-hmr

### Reproduction Steps**
Just follow the steps in the [official Angular docs](https://github.com/angular/angular-cli/wiki/stories-configure-hmr) on any new Angular project `ng new test-app` and it won't work.

### Expected vs Actual Behavior**
**Expected:** When a source file changes Webpack's HMR picks up the changes and communicates it to the browser. Ideally it should refresh part of the page but at least it should display the fact of change in the console.

**Actual:** When the page is loaded in a browser (with `ng serve --configuration hmr` and a source file is changed (and saved) Webpack doesn't do anything, it doesn't load any new file over the network and it doesn't display any change in the browser console, there's no error in the browser console or the terminal.

## 🌍  Your Environment
Any new Angular install (`ng new test-hmr-project`)

### Browser info
This isn't a browser specific issue

### Anything else relevant?
Probably caused by updated Webpack API or updated `@angularclass/hmr` API which isn't reflected in the old (Aug 2, 2018) [official Angular docs](https://github.com/angular/angular-cli/wiki/stories-configure-hmr)

**Comment by Splaktar** [comment] 2019-04-02 23:56
Note that the wiki's source (which isn't in sync with the actual wiki) is found here: https://github.com/angular/angular-cli/blob/master/docs/documentation/stories/configure-hmr.md

Also note that that source has the following:
> Documentation below is deprecated and we no longer accept PRs to improve this. The new documentation is available [here](https://angular.io/guide/build).

Also please note that the Angular CLI GitHub Wiki is no longer the "official Angular docs" for the Angular CLI as mentioned on the [wiki landing page](https://github.com/angular/angular-cli/wiki):
> NOTE: this documentation is for Angular CLI 6. For Angular CLI Version 7 go [here](https://angular.io/cli) and 1.x go [here](https://github.com/angular/angular-cli/wiki/1-x-home) instead.

And finally, it should be noted that there are no HMR docs for Angular version 7. It would probably be a good idea (with lots of interest) for a blog post that could possibly later be turned into a PR to the official docs.

**Comment by hiepxanh** [comment] 2019-05-30 08:12
when the HMR have docs sir?

**Comment by Prinsn** [comment] 2019-08-14 18:19
Also, hopefully the docs make it clear how to use HMR with Lazy Loading.

If Angular 8 is going to push dynamic importing, as well as Lazy Loading and not make it clear how to put it all together, that'd be extremely lackluster.

**Comment by rockument69** [comment] 2020-05-29 17:09
We need engineering input for this before committing to doing docs on HMR with Lazy Loading. The wiki page has a deprecated notice, so we are not going to edit that.

**Comment by Splaktar** [comment] 2020-05-30 01:06
I suggest that this should be at least `freq2: medium`.

**Comment by alan-agius4** [comment] 2020-12-16 12:08
This request should be obsolete as since version 11. HMR is provided out of the box.

**Comment by sebastian-zarzycki-es** [comment] 2021-01-19 14:59
It is not provided at all. It's just CLI options to enable internal server to accept HMR.

**Comment by alan-agius4** [comment] 2021-01-19 15:25
> It is not provided at all. It's just CLI options to enable internal server to accept HMR.

Not sure I am understanding what you mean here.

in version 11, you don’t need to add any specific code to enable the out-of-box HMR support, you just need to use the `—hmr` option.

**Comment by sebastian-zarzycki-es** [comment] 2021-01-19 15:59
Ah, indeed! I was using a lot of init-time routing logic, which caused the app to reload every time, but when I disable that, it indeed works as intended. Sorry for the confusion.

**Comment by alan-agius4** [comment] 2021-01-19 16:35
Closing as this should be no longer needed .

Please feel free to open an issue if you think otherwise.

**Closed by alan-agius4** 2021-01-19 16:35 UTC
Labels: P3, comp: docs, effort3: weeks, freq1: low, state: needs eng input, triage #1, type: bug/fix
