### ISSUE TITLE
Better Error Reporting When Forgetting to Declare Component

### ISSUE THREAD

**Issue by fireflysemantics** [angular/angular#38783] opened 2020-09-09 23:30 UTC
In this case I forgot to declare the login component.  It uses `async`.  This is the error that is generated:

```
core.js:4197 ERROR Error: Uncaught (in promise): Error: The pipe 'async' could not be found!
Error: The pipe 'async' could not be found!
    at getPipeDef$1 (core.js:24392)
    at Module.ɵɵpipe (core.js:24355)
    at LoginComponent_Template (login.component.html:7)
    at executeTemplate (core.js:7447)

```

It would be nice if Angular detected that the component was not registered.

**Comment by geromegrignon** [comment] 2020-09-10 21:26
If possible, it would need to move up the assertion on the element when parsing the template into the visitElement() function : https://github.com/angular/angular/blob/master/packages/compiler/src/template_parser/template_parser.ts

**Comment by petebacondarwin** [comment] 2021-05-18 18:10
So I think the issue is whether we need to surface a diagnostic error when a component is not part of an NgModule.

**Comment by JoostK** [comment] 2021-07-03 23:28
Since Ivy, it's valid for a component not to belong to any NgModule. When using AOT this would then do template type-checking and surface the unknown pipe at compile time, but I suspect that JIT was being used here instead of AOT. Consequently, the error is not surfaced until the template is executed in the browser, which has subpar error reporting compared to AOT template type-checking.

**Comment by JoostK** [comment] 2022-06-02 06:01
This should still be an issue in JIT; your template that reports the failure should just contain something like `{{ 'test' | uppercase }}`.

**Comment by dario-piotrowicz** [comment] 2022-06-02 20:05
@JoostK are you sure? :thinking: 

In the issue description @fireflysemantics says that he forgot to define the component (not the pipe) so I find it correct that angular complains about the component not being declared/defined instead of complaining about something used within the component's template

am I misunderstanding the issue? :sweat:

**Comment by JoostK** [comment] 2022-06-02 20:51
@dario-piotrowicz When a component is not declared in an NgModule (nor standalone, since v14), the component itself can't be used from within other templates indeed. This is what you were testing, which does indeed report a nice error. However, the issue described here is about the compilation of the component itself: an undeclared component does not have a _compilation scope_, so it doesn't "see" any other directives/components nor pipes. For missing directives/components the error in JIT is acceptable, but missing pipes throw a hard error as reported in the issue description. This is actually independent from the missing NgModule declaration, as you'll get the same error if the pipe is misspelled for example. So the issue is still relevant for the JIT compiler (the AOT's template type-checking should correctly report the invalid pipe)

**Comment by dario-piotrowicz** [comment] 2022-06-02 21:04
@JoostK I see thanks :slightly_smiling_face: 

So are you saying that this issue only relates to pipes (not standalone) being used but not declared in an ngModule?

Seems like a PR for that has been merged a while back: https://github.com/angular/angular/pull/44081

And this is the current error in jit:
![Screenshot at 2022-06-02 22-03-16](https://user-images.githubusercontent.com/61631103/171737903-3d3e48be-6278-4443-a7be-38a617e3e4bc.png)

Is this not sufficient/appropriate?

**Comment by AndrewKushnir** [comment] 2022-06-02 22:04
Closing this ticket based on the comment from @dario-piotrowicz.

**Closed by AndrewKushnir** 2022-06-02 22:04 UTC
Labels: hotlist: error messages, comp: compiler, state: confirmed, P3
