### ISSUE TITLE
Dependency injection page not available

### ISSUE THREAD

**Issue by vedantpopli** [angular/angular#59142] opened 2024-12-11 06:08 UTC
### Describe the problem that you experienced

https://angular.dev/guides/di  the link for dependency injection guide is not available

### Enter the URL of the topic with the problem

https://angular.dev/guides/di

### If this problem caused an exception or error, please paste it here

```true

```

### If the problem is browser-specific, please specify the device, OS, browser, and version

```true

```

### Provide any additional information here in as much as detail as you can

```true

```

**Comment by JoostK** [comment] 2024-12-11 07:07
Duplicate of #59139

**Closed by JoostK** 2024-12-11 07:07 UTC
