### ISSUE TITLE
Imported Components/Directives from Ivy library are not recognized in dynamically loaded component

### ISSUE THREAD

**Issue by anhallbe** [angular/angular#42575] opened 2021-06-15 11:30 UTC
# Bug Report

### Affected Package

 The issue is caused by package @angular/core or possibly @angular/compiler or some related package.

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 11

### Description

When loading and compiling a "dynamic" component/module that uses a shared library, the directives/components from that shared library is no longer recognized after the library was upgraded to version 12.

Imported services and other functions work fine, so the issue appears to only be related to the compiled templates

The issue is only present when the application uses AOT, and the shared library is compiled with Angular 12 (partial compilation).

The issue was not present when the application was on Angular 12, and the library was built with Angular 11.

The issue is not present when the application is configured NOT to use AOT.

The library in question is this: https://github.com/infor-design/enterprise-ng

## Minimal Reproduction

Can't really use StackBlitz here since it involves SystemJS and some custom module loading, but I don't think that part is relevant. 

**EDIT: See https://github.com/angular/angular/issues/42575#issuecomment-862119878**

 Here's the relevant code:

```typescript
// A component inside the app that should load an external module/component
class DynamicLoaderComponent {
  constructor(private compiler: Compiler, private vcr: ViewContainerRef) {}

 // The following executes without any errors.
 // The component is successfully created and (partially) rendered.
  async loadTheExternalComponent() {
    const { TheModule, TheComponent } = await importTheModuleUsingSystemJS();
    const mFactory = await this.compiler.compileModuleAsync(TheModule);
    const moduleRef = mFactory.create(this.vcr.injector);
    const cFactory = moduleRef.componentFactoryResolver.resolveComponentFactory(TheComponent);
    const injector = Injector.create({ providers: [], parent: moduleRef.injector });
    this.vcr.createComponent(cFactory, null, injector);
  }
}
```

The external module looks something like this:
```javascript
// NOTE: This code is not executable. It is a SystemJS bundle file that has been modified to make it more readable. I have kept what I think is the relevant parts, and renamed some things for readability.
const angularCommon = require("@angular/common");
const angularCore = require("@angular/core");
const idsEnterpriseNg = require("ids-enterprise-ng");

const theComponentClass = function () {
	function a(a, b) {
		this.message = "Hello"
	}
	a = __decorate([angularCore.Component({
		selector: "the-component",
		template: '<button soho-button>{{message}}</button>\n' // <-- the "soho-button" directive is not recognized
	}), __metadata("design:paramtypes", [])], a)
}();
exported.TheComponent = theComponentClass;

const theModuleClass = function () {
	function a() { }
	return a.prototype.ngDoBootstrap = function () { }
		,
		a = __decorate([angularCore.NgModule({
			imports: [angularCommon.CommonModule, idsEnterpriseNg.SohoComponentsModule],
			declarations: [theComponentClass],
			entryComponents: [theComponentClass]
		})], a)
}();
exported.TheModule = theModuleClass

```

## Exception or Error
Attribute directives like "soho-button" in the example above does not output any errors, but it it also doesn't execute.
Though components e.g `<soho-accordion .....` throws the following error:
<pre><code>

NG0304: 'soho-accordion' is not a known element:
1. If 'soho-accordion' is an Angular component, then verify that it is part of this module.
2. If 'soho-accordion' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
</code></pre>

## Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 12.0.0
Node: 14.16.1
Package Manager: npm 6.14.12
OS: linux x64

Angular: 12.0.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.0
@angular-devkit/build-angular   12.0.0
@angular-devkit/core            12.0.0
@angular-devkit/schematics      12.0.0
@schematics/angular             12.0.0
ng-packagr                      12.0.0
rxjs                            6.6.7
typescript                      4.2.4
</code></pre>

**Anything else relevant?**
The builder options:
```
...
"vendorChunk": true,
"buildOptimizer": false,
"sourceMap": true,
"optimization": false,
"aot": true     // <-- Issue is not present when this is "false".
```

**Comment by petebacondarwin** [comment] 2021-06-15 14:13
Thanks for this detailed issue @anhallbe  - I will take a look at the linked repo and see if I can reproduce it.

**Comment by petebacondarwin** [comment] 2021-06-15 14:45
Could you clarify the reproduction steps for this enterprise-ng repository?

**Comment by petebacondarwin** [comment] 2021-06-15 14:55
Adding the `linker` label because I see that this library has implemented the partial compilation mode 🎉 
We really need a reproduction of an application that is having this problem to be able to debug the issue @anhallbe

**Comment by petebacondarwin** [comment] 2021-06-15 15:00
I think what is happening is that you are importing the library as UMD via SystemJS yes?

This library, if it has been compiled in partial compilation mode, needs to be "linked", which is normally done by the CLI when it is bundling the application.

I suspect that you are trying to consume the library bundle without passing it through a linker step, perhaps?

**Comment by petebacondarwin** [comment] 2021-06-15 15:49
I cloned and built the "quickstart" for that library locally: https://github.com/infor-design/enterprise-ng-quickstart
The partially compiled library code is being linked perfectly!
So now the question is how to reproduce the dynamic import problem that you have...

**Comment by anhallbe** [comment] 2021-06-15 17:27
Thanks @petebacondarwin  for looking into it!
I'll try to set up a repro

**Comment by anhallbe** [comment] 2021-06-16 07:24
Ok here's an app where the issue can be reproduced:

https://github.com/anhallbe/repro-angular-dynamic-loading/tree/systemjs-loading

- The SystemJS stuff (e.g importing the `ids-enterprise-ng` library) is done in `main.ts`.
- The dynamic import happens in `app.component.ts`

The module loading (and module format, with `System.registerDynamic` etc) is there so that the app works similar to ours. Though I could do some testing to see if the issue is present with some other module formats (or newer SystemJS). Since the js module appears to execute without issues, I don't think that part is relevant to the issue.

**Comment by anhallbe** [comment] 2021-06-16 08:16
@petebacondarwin there's currently no further processing of the library, aside from whatever is done by the CLI. I'm not sure I understand the "linking" process. Is there something we should be doing with that?

I did notice that nothing is done to the library when running `ngcc` for `ids-enterprise-ng@10`, unlike version 9. Is this relevant?

I'm not sure how `ngcc` works exactly, and whether it should be doing anything to libraries that are already partially compiled.

**Comment by petebacondarwin** [comment] 2021-06-16 13:13
Thanks for the link to the reproduction. I will investigate now.

**Comment by petebacondarwin** [comment] 2021-06-16 21:27
@JoostK and I discussed this today and we have identified the problem but we need to discuss further what might be the solution. To be clear this is what the reproduction is doing:

- The main application loads a dynamic plugin that is formatted as minified UMD and not AOT compiled by Angular
- This plugin gets JIT compiled by Angular in the browser.
- The plugin references n NgModule from a library, which is compiled using the new partial ivy compilation mode.
- This library is referenced from the main application, so it is bundled into the main application, having been "linked" to fully compiled ivy code.
- JIT compilation requires that all the metadata about the components in any referenced NgModules is available at runtime.
- "Linked" ivy code does not contain this information by default because it bloats the code and consumers that have been AOT compiled do not need it. This is also true of fully compiled AOT code unless optimization is turned off.

So when the plugin gets compiled it doesn't know what components have been imported from the library and so does not recognize the component selector in the plugin component's template.

The linker does have an option to include this metadata, but currently there is no way to tell it do so. It is possible that we could update the CLI to confgure the linker under certain circumstances, but this would require the entire application's linked libraries to have all this extra metadata, which is not desirable in most cases.

**Comment by petebacondarwin** [comment] 2021-06-17 09:10
Further to this, I would be interested to hear a bit more about your build setup.

- How are you generating these lazy loaded files (e.g. `the-worker.js`?
- What are the build settings for the main app? I assume you must have build optimizations turned off, otherwise the `setComponentScope()` calls that actually ensure that the NgModule metadata, mentioned above, is available to the JIT compiler.

**Comment by petebacondarwin** [comment] 2021-06-17 09:14
Ideally, we should be moving away from UMD and SystemJS.

One approach would be to compile the lazy-loaded files as Angular libraries, then use `await import('...')` to load the `fesm2015.js` file into the application. There are some issues around getting this working in a purely data-driven scenario but if you know ahead of time what pieces need to be loaded when the application is built the CLI is clever enough to chunk up the files appropriately. One benefit of this approach is that all the code is then AOT compiled, and you can drop the Angular compiler from the distributable sent to the browser - and of course you save the overhead of compiling at runtime. See https://github.com/sonukapoor/plugin-sample for an example of how this might work.

Another thought we had, if you want to keep a separation between the application and lazy loaded file, is that one could compile lazy loaded files using partial compiled format, which is portable across compiler versions. This partial could then be linked either using JIT compiler in the browser, or perhaps using some kind of "Angular Library Server" (see below).  This approach would allow plugins to be developed independently of the application by different teams, possibly using slightly different versions of Angular.  In this case, though, I think you would still need to ensure that the application contained all the dependencies of the lazy loaded files at start-up.

**Comment by petebacondarwin** [comment] 2021-06-17 09:20
"Angular Library Server" idea: similar to how SSR is able to execute Angular apps on the server and cache the result, we imagined that you could implement a server that hosts compiled Angular libraries. Such libraries would need to be compiled with the correct patch version of Angular before serving.

We envisaged something like:

- The application makes a request for a library to lazily import but must somehow provide the current version of Angular in its request (as a HTTP header??)
- The server goes and gets the partially compiled library code from somewhere (a CDN like unpkg or perhaps direct from npm?)
- The server "links" the partial code into full ivy AOT code, sending this code to the browser in its response.
- The server would cache this result keyed off both the library path/version but also the Angular version used to link the code.
- Future requests for this library would be served directly from the cache.

This would probably need to work with Module Federation, since there are complications around what to do about dependencies of these libraries. So at the moment this is just a blue-sky idea.

**Comment by petebacondarwin** [comment] 2021-06-17 10:05
Another solution, which is actually more aligned with our current support (i.e. that we don't really support AOT mixed with JIT)  is to remove AOT from the main application altogether. Given that this architecture is already accepting the space and time costs of JIT compiling the lazy loaded parts, then make the whole thing JIT and I believe that this will all just work.

**Comment by petebacondarwin** [comment] 2021-06-17 12:16
It might also be worth noting that this problem is not exactly new to partial compilation, it is just a different form of what has been reported before: https://github.com/angular/angular-cli/issues/17663#issuecomment-708031596

**Comment by anhallbe** [comment] 2021-06-17 12:57
Thanks @petebacondarwin for the suggestions and analysis! I'll read through them and respond with details as soon as I have the time.

Some short answers:
- The plugins are generated with Typescript & systemjs-builder (Yes, it's old and deprecated. But some of these were created before the CLI, rollup, Angular 2 etc). Also this is why the deprecated `System.registerDynamic` is still used.
- Some plugins have optionally been compiled with `ngc`, which is loaded by the main application. Though we have often had compatibility issues with this, so more often than not they are just JIT-compiled as a fallback.
- The main app has both `optimization` and `buildOptimizer` set to `false`. `aot` has been `true` up until now, and we are considering whether we should just disable it.
- The plugins (or "widgets") are developed completely independent from the core application. The problem for us has often been compatibility between Angular versions, where we want the core application to stay up-to-date with the very latest, but we also have to make sure that widgets that were bundled 5 years ago still work (within reason of course, breaking changes do happen). 
- Although we would like _everything_ to be fully compiled ahead-of-time, we've had some issues with that in the past where a newer Angular version in the core application would be incompatible with the compiler output from an old version. So it has always been a best-effort thing, so we haven't been able to remove JIT. 
- The "Angular Library Server" sounds like a really interesting idea. We will probably look into some sort of centralized compilation process.

**Comment by petebacondarwin** [comment] 2021-06-22 15:49
I think you have two options here @anhallbe - either try to re-architect your plugins to compile them as partial-ivy libraries, or to convert your whole application to JIT mode. We don't currently support mixing AOT and JIT mode with the Angular CLI. It just happened that turning off certain optimisations resulted in code that worked.

Hopefully this summer we will run an RFC about the future of JIT mode, how it is being used and where Angular should go with support for it. Meanwhile, I don't think there is anything else that we can do here for this issue, so I am going to close it. Feel free to continue to add comments here if there is more to be said.

**Closed by petebacondarwin** 2021-06-22 15:49 UTC
Labels: P3, comp: compiler, compiler: linker
