### ISSUE TITLE
Router: The router content is not stored inside <router-outlet> but inside <undefined>

### ISSUE THREAD

**Issue by tamalnath** [angular/angular#6902] opened 2016-02-05 03:27 UTC
In Beta.2 the router generates DOM as:

```html
<router-outlet></router-outlet>
<undefined _ngcontent-sts-2="">...</undefined>
```
Ideally the content should be inside &lt;router-outlet&gt;. Please correct it.

**Comment by zoechi** [comment] 2016-02-05 05:58
dup of #6222
relatet to #1662

**Comment by tamalnath** [comment] 2016-03-01 08:25
Can we put the router content inside the <router-outlet> ?

**Comment by zoechi** [comment] 2016-03-01 08:35
Just add a selector to your component and this will be used instead of `undefined`.

**Comment by tamalnath** [comment] 2016-03-01 08:39
What I want is the router content inside the **router-outlet** tag and not next to it.

**Comment by zoechi** [comment] 2016-03-01 09:11
What's the use case?

**Comment by tamalnath** [comment] 2016-03-02 07:36
if router content is nested inside the router-outlet tag, we can easily add some CSS styles for the router content:
```html
<router-outlet style="..." class="..."></router-outlet>
```
As of now, I have to do:
```html
<div style="..." class="...">
    <router-outlet></router-outlet>
</div>
```

**Comment by mrobrian** [comment] 2016-08-03 15:21
I just ran into the issue of route content being inserted below the `router-outlet` element, rather than inside it.  At first I thought I was doing something wrong, but after spending some time looking at examples and searching to find the bugs reported here, I see that this behavior is by design.  This doesn't make any sense to me.  To me, `router-outlet` should be just like any other directive and put the contents inside it.

Also, there's this comment taken directly from @angular/router/src/directives/router_outlet.d.ts:

> A router outlet is a placeholder that Angular dynamically fills based on the application's route.

**Comment by mko** [comment] 2016-08-05 21:35
It does seem like a strange decision to place the content *outside* of the `router-outlet` in a separate element as in the following example:

```html
<router-outlet></router-outlet>
<component-selector>{{{template}}}</component-selector>
```

Or, if you haven't defined a selector for your component:

```html
<router-outlet></router-outlet>
<undefined>{{{template}}}</undefined>
```

Intuitively, the docs made it seem like the following would have occurred:

```html
<router-outlet>
    <component-selector>{{{template}}}</component-selector>
</router-outlet>
```

Which would then enable you to not require the `<undefined>` element for components without a selector, like so:

```html
<router-outlet>
    {{{template}}}
</router-outlet>
```

There's obviously other reasons you'd want to still potentially include the `<undefined>` element, so it seems reasonable to have the following as well:

```html
<router-outlet>
    <undefined>{{{template}}}</undefined>
</router-outlet>
```

--------------------

Can we get some sort of clarification regarding the design decision about the "sibling" `router-outlet` / `component-selector` that makes it into the docs?

**Comment by zoechi** [comment] 2016-08-06 10:53
`<undefined>` should be fixed in https://github.com/angular/angular/commit/9b39e499ace74addf7edbb0202dd261de038b32b

**Comment by pkozlowski-opensource** [comment] 2016-08-06 12:00
It is indeed fixed in 9b39e49, thnx @zoechi !

**Closed by pkozlowski-opensource** 2016-08-06 12:00 UTC

**Comment by chenyingyin** [comment] 2016-12-01 04:03
![default](https://cloud.githubusercontent.com/assets/24284270/20781494/35ea917c-b7be-11e6-8a11-af7fbc3acd36.png)
![Uploading 图片.png…]()

**Comment by syedaliuzair** [comment] 2019-06-14 11:27
> if router content is nested inside the router-outlet tag, we can easily add some CSS styles for the router content:
> 
> ```
> <router-outlet style="..." class="..."></router-outlet>
> ```
> 
> As of now, I have to do:
> 
> ```
> <div style="..." class="...">
>     <router-outlet></router-outlet>
> </div>
> ```

**Comment by syedaliuzair** [comment] 2019-06-14 11:28
> if router content is nested inside the router-outlet tag, we can easily add some CSS styles for the router content:
> 
> ```
> <router-outlet style="..." class="..."></router-outlet>
> ```
> 
> As of now, I have to do:
> 
> ```
> <div style="..." class="...">
>     <router-outlet></router-outlet>
> </div>
> ```

Thank you so much bro !! Really appreciated.
