### ISSUE TITLE
Barrels in library project break app build, but only with --prod

### ISSUE THREAD

**Issue by totkeks** [angular/angular#24518] opened 2018-06-14 17:06 UTC
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
Error returned on `ng build --prod`
`ERROR in : Unexpected value 'MyLibModule in C:/Git/playground/ng6-lib-import/dist/my-lib/lib/my-lib.module.d.ts' imported by the module 'AppModule in C:/Git/playground/ng6-lib-import/src/app/app.module.ts'. Please add a @NgModule annotation.`

## Expected behavior
No error on `ng build --prod` like with `ng build`

## Minimal reproduction of the problem with instructions
Use my repository https://github.com/totkeks/ng6-lib-import/tree/bug/lib-with-barrel which contains a basic angular6 app and a basic library (my-lib) on the master branch and this bug on the bug/lib-with-barrel branch.

Run the following commands
- `npm install`
- `ng build my-lib`
- `ng build --prod`

The additional barrel between the library items and the public_api.ts is index.ts (see last commit on branch).

## What is the motivation / use case for changing the behavior?
Barrels make imports easier and they sometimes don't work.
I can understand that barrels are not in the angular style guide anymore, but I still like to use them. On the other hand I could understand that the bug could be closed with the comment: "Don't use barrels"

## Environment
<pre><code>
Angular CLI: 6.0.8
Node: 8.11.2
OS: win32 x64
Angular: 6.0.4
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.6.8
@angular-devkit/build-angular      0.6.8
@angular-devkit/build-ng-packagr   0.6.8
@angular-devkit/build-optimizer    0.6.8
@angular-devkit/core               0.6.8
@angular-devkit/schematics         0.6.8
@angular/cli                       6.0.8
@angular/router                    6.0.5
@ngtools/json-schema               1.1.0
@ngtools/webpack                   6.0.8
@schematics/angular                0.6.8
@schematics/update                 0.6.8
ng-packagr                         3.0.1
rxjs                               6.2.0
typescript                         2.7.2
webpack                            4.8.3
</code></pre>

**Comment by trotyl** [comment] 2018-06-15 06:44
Possibly relates to https://github.com/angular/angular/issues/20931, https://github.com/angular/angular/issues/23713

**Comment by jasonaden** [comment] 2018-06-22 16:34
Thanks for the issue. It looks like a duplicate of #23713, so I'll go ahead and close this issue. Track that issue for updates. I'm trying to get some answer on it over the next week or so to determine if this is something that will be fixed now, or if barrels shouldn't be used until Ivy is released. Will update on that issue.

**Closed by jasonaden** 2018-06-22 16:34 UTC
