### ISSUE TITLE
Maximum call stack size exceeded with touch events

### ISSUE THREAD

**Issue by CaptainCodeman** [angular/angular#7448] opened 2016-03-06 01:43 UTC
* **I'm submitting a ... **
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
Browser locks up when touch event triggered.
Event added using `(swipeleft)="swiped()"`

Exception:
```
RangeError: Maximum call stack size exceeded
    at Zone.collection_1.StringMapWrapper.merge.onError (https://code.angularjs.org/2.0.0-beta.8/angular2.dev.js:13437:20)
    at Zone.run (https://code.angularjs.org/2.0.0-beta.8/angular2-polyfills.js:1247:23)
    at Zone.run (https://code.angularjs.org/2.0.0-beta.8/angular2.dev.js:13456:32)
    at NgZone.run (https://code.angularjs.org/2.0.0-beta.8/angular2.dev.js:13418:34)
    at handler (https://code.angularjs.org/2.0.0-beta.8/angular2.dev.js:20808:16)
    at https://code.angularjs.org/2.0.0-beta.8/angular2.dev.js:20809:13
    at Zone.run (https://code.angularjs.org/2.0.0-beta.8/angular2-polyfills.js:1243:24)
    at Zone.run (https://code.angularjs.org/2.0.0-beta.8/angular2.dev.js:13456:32)
    at NgZone.run (https://code.angularjs.org/2.0.0-beta.8/angular2.dev.js:13418:34)
    at handler (https://code.angularjs.org/2.0.0-beta.8/angular2.dev.js:20808:16)
```

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
Demo plunker: http://plnkr.co/edit/Ic99R2YdhHKVk3EDjkaK
Swipe left on "Hello Angular 2" title

* **What is the expected behavior?**
Console should log "swiped"

* **What is the motivation / use case for changing the behavior?**
Use touch events

* **Please tell us about your environment:**

- Angular version: 2.0.0-beta.8
- Browser: [Chrome 48]
- Language: [TypeScript]

**Comment by robwormald** [comment] 2016-03-06 01:47
duplicate of #6993

**Closed by robwormald** 2016-03-06 01:47 UTC

**Comment by CaptainCodeman** [comment] 2016-03-06 01:51
Thanks, I managed to search using words that didn't find it (swipe, touch, hammer.js) doh!
