### ISSUE TITLE
Angular2 footprint is too big

### ISSUE THREAD

**Issue by SetTrend** [angular/angular#7793] opened 2016-03-28 12:09 UTC
I feel the footprint of Angular2 is too big at this time.

Having to install [external typings, like es6-shim, jasmin and all the many devDependencies](https://angular.io/docs/ts/latest/quickstart.html#development-environment), is confusing and is making me retracting from using Angular2.

It's not getting clear from the [Quick Start](https://angular.io/docs/ts/latest/quickstart.html) page what is required to use Angular2 and what is just a personally biased toolset.

**Please provide a Quick Start sample and an NPM download that only requires one single `dependency`: Angular2.**

Moreover, _TypeScript_ settings, the _DefinitelyTyped_ project, Node _web servers_ and other toolings should not be in the focus of an Angular2 Quick Start. I feel that all these additional dependencies and constraints belong into a separate example tutorial, deliberately adding tools to create a running application in a particular, personal environment and explicitly explaining about that fact.

For a Quick Start I expect the bare bone Angular2 `dependency` to work with any toolset I choose to add to my `package.json` file and to run with any of my tools' settings without any additional requirements.

Moreover, I suggest to get rid of all of Angular2's `peerDependencies`. They litter up the machine.

**Comment by CarlosAmaral** [comment] 2016-03-28 14:20
I agree, it has too many dependencies. Although I do hope they sort of merge into ng2.

**Comment by MarkPieszak** [comment] 2016-03-28 15:00
Agree as well. Although now I have a good grasp on all of them, at first it was extremely daunting, and I imagine others felt the same way. If someone hasn't came from a node / npm background, it's very overwhelming.

It would be great if most of them were simply dependencies on angular2 and got installed automatically with it.

**Comment by tapas4java** [comment] 2016-03-28 15:31
You can take a look at [`angular-cli`](https://github.com/angular/angular-cli). It will configure everything out of the box for you.

**Comment by CaptainCodeman** [comment] 2016-03-28 15:46
I had a go at making a dependency-lite / simple starter which I use as the basis for my apps:
https://github.com/CaptainCodeman/angular2-webpack-polyfill

It was also to test out some ideas for loading polyfills (to support IE and Safari)

The core-js reference is only necessary to support IE in a few places. It's possible to pull those bits into the vendor file instead, the only pieces needed are these:

```
    'core-js/es6/array',
    'core-js/es6/map',
    'core-js/es6/string',
    'core-js/es6/symbol',
```

**Comment by robwormald** [comment] 2016-03-29 01:14
> I feel the footprint of Angular2 is too big at this time.

We agree. It's one of the top focuses as we move towards RC.

> Having to install external typings, like es6-shim, jasmin and all the many devDependencies, is confusing and is making me retracting from using Angular2.

The simplest use of angular2 is available either via code.angularjs.org, using the ES5 build which requires no tooling whatsoever to use - there is documentation available here for that usage: https://angular.io/docs/js/latest/quickstart.html

> Please provide a Quick Start sample and an NPM download that only requires one single dependency: Angular2.

This is counter to the goals of Angular2 - by producing a single bundle with all code inlined, we add code that some users may not need - RxJS is a good example of this - we depend on approx 10kb of that codebase, and users can opt into the other ~300kb as they choose. This is what modules provide, and NPM is designed around modules. Pre-bundling code prevents optimization - we do provide such bundles in the /bundles directory of the NPM distribution for demos and tinkering. We do not recommend them for production usage.

ES5 bundles are available in the aforementioned link.

> Moreover, TypeScript settings, the DefinitelyTyped project, Node web servers and other toolings should not be in the focus of an Angular2 Quick Start. I feel that all these additional dependencies and constraints belong into a separate example tutorial, deliberately adding tools to create a running application in a particular, personal environment and explicitly explaining about that fact.

Again, all of these things are opt-in, but we feel that the Typescript environment provides a superior experience for developers. The goal of the quickstart is to get users up and running in an opinionated manner - experts may choose whatever tooling they like. There are a number of community projects that show a variety of other ways to use angular2 with webpack, JSPM, rollup, etc.

> For a Quick Start I expect the bare bone Angular2 dependency to work with any toolset I choose to add to my package.json file and to run with any of my tools' settings without any additional requirements.

With the exception of RxJS, this is already the case if you choose to use ES5. Its compatible with any toolchain. Typescript requires an additional set of configuration.

> Moreover, I suggest to get rid of all of Angular2's peerDependencies. They litter up the machine.

This goes back to the modular nature of modern javascript and NPM. 

We appreciate the input, but I'm going to close this issue as its not actionable - bundle size is a primary focus for us the moment and expect to see some interesting changes in the next few weeks. Thanks!

**Comment by jmb-mage** [comment] 2016-06-08 15:41
Angular2 quickstart on GitHub creates a dist folder.  The /dist/vendor folder contains 1,040 files and is 6.82 MB.  This is with the `enableProdMode();` command turned on.
1,040 files and 6.82 mb for Angular 2 seems like a lot.

The Angular 1 version I used, one file, angular.js is 765kb.  minified is 105 kb.

**Comment by jmb-mage** [comment] 2016-06-08 15:57
I modified quickstart project to use angular-cli and added a few things like `@angular/http`.  The dist/vendor folder it creates is 1,040 files and 6.82 mb!  And this is with `enabledProdMode();` 

I hope I am missing something?  Otherwise our deployment team is going to wonder what all that is.

**Comment by Zyzle** [comment] 2016-06-08 16:09
@jmb-mage are you building with the `--prod` option using the cli?

**Comment by jmb-mage** [comment] 2016-06-08 16:15
@Zyzle I am using `ng serve`.  I looked at `ng help` and don't see a `--prod`.   Is it `ng serve --prod`?

**Comment by MarkPieszak** [comment] 2016-06-08 16:52
@jmb-mage It's `-prod` not `--`

**Comment by jmb-mage** [comment] 2016-06-08 16:57
@MarkPieszak `ng serve -prod` yields and error and the dist folder is not created.

`ng help serve` does not show a prod option.

**Comment by mhevery** [comment] 2016-06-08 17:22
@jmb-mage what is the error?

**Comment by jmb-mage** [comment] 2016-06-08 17:36
@mhevery steps to reproduce:
1) `git clone https://github.com/angular/quickstart.git`  
2) `ng init`  
3) `ng serve` (works fine)  
but `ng serve --prod` yields:

> 
> The Broccoli Plugin: [BundlePlugin] failed with:
> Error on fetch for main.js at file:///C:/dev/angular/qs2/quickstart/tmp/bundle_plugin-input_base_path-vSUVct2y.tmp/0/main.js
>         Error: ENOENT: no such file or directory, open 'C:\dev\angular\qs2\quickstart\tmp\bundle_plugin-input_base_path-vSUVct2y.tmp\0\main.js.map'
>     at Error (native)
> 
> The broccoli plugin was instantiated at:
>     at BundlePlugin.Plugin (C:\dev\angular\qs2\quickstart\node_modules\angular-cli\node_modules\broccoli-caching-writer\node_modules\broccoli-plugin\index.js:10:31)
>     at BundlePlugin.CachingWriter [as constructor] (C:\dev\angular\qs2\quickstart\node_modules\angular-cli\node_modules\broccoli-caching-writer\index.js:21:10)
>     at BundlePlugin (C:\dev\angular\qs2\quickstart\node_modules\angular-cli\lib\broccoli\angular-broccoli-bundle.js:11:10)
>     at Angular2App._getBundleTree (C:\dev\angular\qs2\quickstart\node_modules\angular-cli\lib\broccoli\angular2-app.js:375:55)
>     at Angular2App._buildTree (C:\dev\angular\qs2\quickstart\node_modules\angular-cli\lib\broccoli\angular2-app.js:137:21)
>     at new Angular2App (C:\dev\angular\qs2\quickstart\node_modules\angular-cli\lib\broccoli\angular2-app.js:42:23)
>     at module.exports (C:\dev\angular\qs2\quickstart\angular-cli-build.js:6:10)
>     at Class.module.exports.Task.extend.setupBroccoliBuilder (C:\dev\angular\qs2\quickstart\node_modules\angular-cli\node_modules\angular-cli\lib\models\builder.js:55:19)
>     at Class.module.exports.Task.extend.init (C:\dev\angular\qs2\quickstart\node_modules\angular-cli\node_modules\angular-cli\lib\models\builder.js:89:10)
>     at new Class (C:\dev\angular\qs2\quickstart\node_modules\angular-cli\node_modules\angular-cli\node_modules\core-object\core-object.js:18:12)
>     at Class.module.exports.Task.extend.run (C:\dev\angular\qs2\quickstart\node_modules\angular-cli\node_modules\angular-cli\lib\tasks\serve.js:15:19)
>     at C:\dev\angular\qs2\quickstart\node_modules\angular-cli\node_modules\angular-cli\lib\commands\serve.js:64:24
>     at lib$rsvp$$internal$$tryCatch (C:\dev\angular\qs2\quickstart\node_modules\angular-cli\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1036:16)
>     at lib$rsvp$$internal$$invokeCallback (C:\dev\angular\qs2\quickstart\node_modules\angular-cli\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1048:17)
>     at lib$rsvp$$internal$$publish (C:\dev\angular\qs2\quickstart\node_modules\angular-cli\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1019:11)
>     at lib$rsvp$asap$$flush (C:\dev\angular\qs2\quickstart\node_modules\angular-cli\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1198:9)

**Comment by mhevery** [comment] 2016-06-08 20:10
@hansl can you have a look?

**Comment by jmb-mage** [comment] 2016-06-08 20:35
I ran the same thing on a Mac and it worked.  The first time I ran it on a PC and made sure that the console window was opened with Administrator privileges.

**Comment by MarkPieszak** [comment] 2016-06-08 22:07
What version of Windows @jmb-mage ? I've been noticing Win7 has some really big issues with npm / and other random things lately...

**Comment by jmb-mage** [comment] 2016-06-09 01:56
@MarkPieszak Win 10.  My buddy at work says he thinks that Windows may be missing some of the unix commands that angular-cli maybe using to translate the files?

**Comment by MarkPieszak** [comment] 2016-06-09 12:43
I'd believe it, there are a lot of things Windows is missing 👎  when it comes to command line :(
(For example I'm still trying to talk to typescript & npm people to figure out what's going on with `tsc` and the npm lifecycle on windows, huge issues there on Windows)

It looks like someone just created an issue over at the CLI github, it definitely sounds specific to that.
https://github.com/angular/angular-cli/issues/1052

**Comment by kbdguy** [comment] 2016-06-13 21:47
Not a missing command, but a problem with \ vs / in Windows paths.

This is a bug in the latest version of systemjs-builder.

you can work around it by changing the dependency to use version 0.15.14 (maybe another later version will work, too, but I used this one)

i.e. change your dependency in project.json to

"systemjs-builder": "0.15.14"

**Comment by jmb-mage** [comment] 2016-06-14 13:47
@kbdguy I think you are on the right track.  Searching my project for "project.json" I didn't find it.  I do find

in `tmp\vendor-input_base_path-Tm3lKJNL.tmp\0\rxjs`
 `"systemjs-builder": "^0.10.6",`

and in `tmp\vendor-input_base_path-Tm3lKJNL.tmp\0\angular-cli`
 `"systemjs-builder": "^0.15.16",`

**Comment by kbdguy** [comment] 2016-06-16 21:18
@jmb-mage Sorry... yes, I meant package.json.  I believe the only one that matters is right in the root angular2-seed folder.  That's the only one I edited and the problem went away.

**Comment by SetTrend** [comment] 2016-07-14 15:23
Some progress has been made. But I believe there is still room for improvement:

https://github.com/angular/angular/issues/10072

**Comment by vicb** [comment] 2016-07-14 15:45
Closing as the size is already a main focus for the final release.

If there is a different pb angular-cli please report there: https://github.com/angular/angular-cli/issues

**Closed by vicb** 2016-07-14 15:45 UTC
