### ISSUE TITLE
Cannot remove outlets from path

### ISSUE THREAD

**Issue by akorchev** [angular/angular#15338] opened 2017-03-21 08:44 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

It seems impossible to navigate to some path and clear any named outlets in the process. Consider this code:
```ts
this.router.navigate(['/', { outlets: { secondary: null } });
```
This does not remove the `(secondary:)` portion from the path. However this code does remove that segment:
```ts
this.router.navigate([{ outlets: { secondary: null } });
```
In addition `this.router.navigateByUrl('/')` also works.

**Expected behavior**

The first code should also work and remove the secondary outlet segment from the path. 

**Minimal reproduction of the problem with instructions**

http://plnkr.co/edit/hFsOdLLr2LCq8cJyOF6R?p=preview

**What is the motivation / use case for changing the behavior?**

The current behavior looks erroneous. I believe there should be an `else` [here](https://github.com/angular/angular/blob/master/packages/router/src/create_url_tree.ts#L225) which sets `children[outlet]` to `null` so it is not initialized later.

**Please tell us about your environment:**

* **Angular version:** 2.4.10

Code in master looks the same as in 2.4.10.
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 All browsers.
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
I think it is a framework issue rather than a language one.
* **Node (for AoT issues):** `node --version` =

**Comment by orestisioakeimidis** [comment] 2017-04-03 12:16
It would be nice to use it with the `routerLink` directive as well.
```
<a [routerLink]="['/', { outlets: { secondary: null } }]">Back</a>
```
Thanks!

**Comment by mkp05** [comment] 2017-10-12 08:13
Same problem still present on Angular 4.4.3.

**Comment by Sky4CE** [comment] 2017-10-12 20:22
And still present on 5.0.0-beta4... So at this point outlets completely unusable, just thanks to angular team

**Comment by akorchev** [comment] 2017-10-12 20:28
FWIW I am using the following as a workaround:

```ts
this.router.navigate([{ outlets: { secondary: null } }])
           .then(() => this.router.navigate(['/']));
```

**Comment by mkp05** [comment] 2017-10-12 21:30
@akorchev I confirm this works (as I found this solution myself), but it's ugly... especially when you want to adapt ngrx and some routing actions.

**Comment by dottodot** [comment] 2017-11-17 16:19
Not working in 5.0.1 either, surely this makes named outlets useless if you can't clear them. 

The workaround also isn't working for me.

**Comment by Lolash** [comment] 2017-11-28 08:43
@dottodot  https://github.com/angular/angular/issues/15718 try with params

**Comment by cuiliang** [comment] 2017-12-09 03:13
Also can not clear outlets from routerLink:

`[routerLink]=['/', 'path', 1, {outlets: {popup: null}}]`

**Comment by wdumlao** [comment] 2018-01-11 04:49
This is still broken @5.2.0. Any news on this issue?

**Comment by Summerdx** [comment] 2018-02-06 10:00
Still in 5.2.3.
temp fix with following code

```

export class MyOutletComponent implements OnDestroy {
  constructor(public router: ActivatedRoute) {
  }
  
  ngOnDestroy () {
    this.router.outlet = null; // <--
  }
} 

```

**Comment by rimlin** [comment] 2018-03-16 09:00
Angular 5.0.0 same problem with removing named outlets. Created temp fix directive to use it in templates:

```
@Directive({
  selector: '[modalRouterOutlet]',
})
export class ModalRouterOutletDirective implements OnInit {
  @Input() modalRouterOutlet: any[];

  constructor(
    private renderer: Renderer2,
    private el: ElementRef,
    private router: Router
  ) { }

  ngOnInit(): void {
    if (this.el.nativeElement.tagName.toLowerCase() === 'a') {
      this.renderer.setAttribute(this.el.nativeElement, 'href', this.modalRouterOutlet.join(''));
    }
  }

  @HostListener('click', ['$event'])
  onClick(event): void {
    event.preventDefault();

    this.router.navigate([{ outlets: { modal: null } }])
      .then(_ => this.router.navigate(this.modalRouterOutlet));
  }
}
```
Change `modal` to your outlet name or provide new `@Input` which will contain name of you outlet.

**Comment by gautamkrishnar** [comment] 2018-03-27 15:55
Really sad to see that there is still no fix for this issue. 😞

**Comment by BlindDespair** [comment] 2018-07-19 08:53
Is this going to be fixed? We have same issue in our project. ``router.navigate()`` works of course, but we lose advantages of routerLink, because we can't use open in a new tab feature easily. Especially with mouse wheel click or context menu option... Need to do hacks because of this.

**Comment by larssn** [comment] 2018-10-15 18:21
We used to use `navigateByUrl` (as the OP mentioned) which clears the route completely.

So instead of doing `[routerLink]="['/settings/categories', {outlets: { details: null }}]"`; (in template), you're forced to do a `this.router.navigateByUrl('/settings/categories');` programmatically, which will both clear the outlet and navigate.

I'm feeling that the Angular team is digging themselves down a rabbit hole with the router. It is clearly too complex, which is why we're seeing 1,5 year old bugs still not fixed.

**Comment by trungk18** [comment] 2018-11-20 05:03
I saw the work around from https://github.com/angular/angular/issues/13523#issuecomment-335447524

So basically It looks like.

```
this.router.navigate(
    [
        "",
        {
            outlets: {
                inbox: null // <---- Doesn't seem to do anything (from WITHIN inbox).
            }
        }
    ],
    {
        relativeTo: this.activatedRoute
    }
);
```

**Comment by nkoehler** [comment] 2019-03-22 21:21
Can we get an update on this? If the route doesn't specify an outlet, don't include it.  It shouldn't be more complicated than that.

**Comment by spock123** [comment] 2019-06-05 09:08
Did anyone resolve this?
All workaround I have seen involves loading the primary outlet as well (or route to a specific one). But if my aux route is a modal popup, I don't want to reload the primary outlet (deleting form entries, state etc), I just want to clear the damn aux outlet from within a component of the outlet.

Did anyone ever find a solution? I'm on NG8 and it's still broken.

**Comment by Yexan** [comment] 2019-08-09 08:51
Any updates please ? 
21 Mar 2017 - 9 August 2019, still open, on the router feature that doesn't help me to trust the framework really. :/

**Comment by vladimiry** [comment] 2019-08-09 09:43
Here is a related point https://github.com/angular/angular/issues/5122#issuecomment-518645553

**Comment by Romanchuk** [comment] 2019-08-16 07:01
This works for me:
> await this.router.navigate(['', { outlets: { filter: null}}], { replaceUrl: true });
It doesn't drop primary outlet url

"replaceUrl" in not necessary

**Comment by alexia-Shen** [comment] 2019-08-21 04:36
I tried a way that using the pathFromRoot in ActivedRouteSnapshot, and it works for me:

>     closeOutlet() {
        let pathFromRoot = this._route.snapshot.pathFromRoot, path = '';
        //take out paths before outlet: overlay
        for (let i = 0; i < pathFromRoot.length && pathFromRoot[i].outlet !== 'overlay'; i++){
            if (pathFromRoot[i].outlet === 'primary' && pathFromRoot[i].routeConfig && pathFromRoot[i].routeConfig.path){
                path += '/' + pathFromRoot[i].routeConfig.path;
            }
        }\
        this._router.navigate([path]);
    }

**Comment by alexia-Shen** [comment] 2019-08-21 04:37
I tried a way that using `pathFromRoot `in `ActivedRouteSnapshot`, and it works for me:
`    closeOutlet() {
        let pathFromRoot = this._route.snapshot.pathFromRoot, path = '';
        //take out paths before outlet: overlay
        for (let i = 0; i < pathFromRoot.length && pathFromRoot[i].outlet !== 'overlay'; i++){
            if (pathFromRoot[i].outlet === 'primary' && pathFromRoot[i].routeConfig && pathFromRoot[i].routeConfig.path){
                path += '/' + pathFromRoot[i].routeConfig.path;
            }
        }
        this._router.navigate([path]);
    }`

**Comment by alexia-Shen** [comment] 2019-08-21 04:41
I tried a way that using `pathFromRoot `in `ActivedRouteSnapshot`, and it works for me.

**Comment by plex4r** [comment] 2019-10-04 13:42
Any update on this?  I do not want to lose the advantages of using [routerLink] in my template and be forced to use a workaround in *.ts code.  For example, if I cannot use [routerLink] I need to do another workaround to have the current link highlighted used routerLinkActive="myHighlightClass"

**Comment by Yexan** [comment] 2019-10-16 07:03
For info, as this core feature still doesn't work properly, I did as many people suggested me in meetups and talks, to go without the router module, with a custom solution.
I don't like it because it's a bit less _clean code_ (on my point of view) but at least it works and I can trust this system.

**Comment by simeyla** [comment] 2020-02-15 09:17
In Angular 9 the following works.

I'm using a named outlet to display a model dialog. So let's say my current route is:

   /store/products(popup:dialog/faq)

To clear the popup in the current navigation:


this.router.createUrlTree([ { outlets: { 'primary': 'cat', 'dialog-outlet': null }} ], {  }).toString();

this.router.createUrlTree([ { outlets: { 'primary': 'cat', 'dialog-outlet': null }} ], {  }).toString();

**Comment by jaylandro** [comment] 2020-03-09 00:07
I have found a way to work with multi-router-outlet views that allows the **clearing of outlets** by defining a **componentless parent route** with children routes for each of the outlets. Here we are setting the `primary outlet` and `left outlet` to componentless routes with **empty children** arrays _(this is needed for how hooks work i believe, since this could be a data-loading route.)_

e.g.
```js
  {
    path: 'header-only',
    children: [
      {
        path: '',
        children: []
      },
      {
        path: '',
        component: TopNavComponent,
        outlet: 'header'
      },
      {
        path: '',
        children: [],
        outlet: 'left',
      }
    ]
  },
```

Then to link to this composed state with  **routerlink**:
`<a routerLink="/header-only">Header Only</a>`

**Comment by wxyer** [comment] 2020-05-09 15:40
`router.navigate( [ { outlets: { 'popup': null }} ] ); ` do not work

**Comment by atscott** [comment] 2020-05-26 19:12
Closing as duplicate of #13523

**Closed by atscott** 2020-05-26 19:12 UTC
Labels: comp: router, freq3: high, router: aux routes, severity3: broken, triage #1, type: bug/fix
