### ISSUE TITLE
A routerLink with fragment doesn't scroll to the fragment target when the current route already contains the fragment

### ISSUE THREAD

**Issue by Tragetaschen** [angular/angular#14245] opened 2017-02-02 10:06 UTC
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

`routerLink` with `fragment` doesn't scroll to the fragment target when the current route already contains the fragment.
**Expected behavior**

With a standard `<a href="#frag"></a>`, the browser will always scroll to the target.
**Minimal reproduction of the problem with instructions**

http://plnkr.co/edit/6Od3vTp2Che48wO5A9Pc?p=preview although using the router in a Plnkr is virtually impossible
**What is the motivation / use case for changing the behavior?**

So it behaves correctly
**Please tell us about your environment:**

windows, vs 2015, npm, Kestrel behind IIS, ... (what?)
* **Angular version:** 2.0.X

2.2.4 in my environment and whatever the Plnkr gives me
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 2.0.3
* **Node (for AoT issues):** `node --version` =

**Comment by Tragetaschen** [comment] 2017-02-02 10:13
I just noticed that this is only an issue on the docs page, which seems to be running angular 1.6

https://angular.io/docs/ts/latest/guide/lifecycle-hooks.html

Click on `AfterContentInit` in the TOC, scroll back to the top, and click `AfterContentInit` again. The second time, nothing happens.

Still strange that the Plunker dosen't work at all...

**Comment by DzmitryShylovich** [comment] 2017-02-02 10:15
Duplicate of https://github.com/angular/angular/issues/13636

**Comment by pkozlowski-opensource** [comment] 2017-02-02 14:59
Duplicate of #13636 indeed, thnx @DzmitryShylovich

**Closed by pkozlowski-opensource** 2017-02-02 14:59 UTC

**Comment by Axure** [comment] 2018-12-22 11:14
I don't see how this is a duplicate of https://github.com/angular/angular/issues/13636, or how this problem could be fixed. 

Setting either `scrollPositionRestoration` or `anchorScrolling` or whatever options that ever appeared in the world does not seem to fix this problem.

**Comment by Parent5446** [comment] 2019-02-20 19:02
Note that this is still a bug as late as 6b511a33f6c340cf2f8cf06b4feddb163b61d1c5.
