### ISSUE TITLE
11.1.0 issue worked in 10.0.9 Dependency injection will not be able to resolve the parameters of FieldArrayType's constructor.

### ISSUE THREAD

**Issue by vespertilian** [angular/angular#40532] opened 2021-01-23 00:24 UTC
# 🐞 bug report

### Is this a regression?

Yes this works in 11.0.9 but not 11.1.0 

### Description

Using `ngx-formly` I get an error using 11.1.0 that was no present in 11.0.9. Or 10.x for that matter.

I have a component that extends FieldArrayType `ngx-formly`

```ts
@Component({
  selector: 'app-repeat-section-type',
  templateUrl: './repeat-section.type.component.html',
  styleUrls: ['./repeat-section.type.component.scss']
})
export class RepeatSectionFormlyComponent extends FieldArrayType {}
```

In 11.1.0 I get this error when building via `ng start`:
```
Error: src/app/repeat-section/repeat-section.type.component.ts:9:14 - error NG2006: The component
RepeatSectionFormlyComponent inherits its constructor from FieldArrayType,
but the latter does not have an Angular decorator of its own.
Dependency injection will not be able to resolve the parameters of FieldArrayType's constructor. 
Either add a @Directive decorator to FieldArrayType, 
or add an explicit constructor to RepeatSectionFormlyComponent.

9 export class RepeatSectionFormlyComponent extends FieldArrayType {}
```

I double-checked the `ngx-formly` code and it does have an @Directive decorator on the class:

See the code here
https://github.com/ngx-formly/ngx-formly/blob/main/src/core/src/lib/templates/field-array.type.ts

```ts

@Directive()
export abstract class FieldArrayType<F extends FormlyFieldConfig = FormlyFieldConfig> extends FieldType<F>
  implements FormlyExtension {
  get formControl() {
    return this.field.formControl as FormArray;
  }

...
```

## 🔬 Minimal Reproduction

Using a repo not stackblitz as I feel the build errors will be easier to debug via ng start

```this commit is working```

https://github.com/vespertilian/angular-test-app-jasmine/commit/5163dbd8f3a4a950240ecbb98b9c3c62f0146dff

```this commit is not```

https://github.com/vespertilian/angular-test-app-jasmine/commit/fae6f38d6b442e55389a2ffdf43ab5a5c3662ccd

^^^ two last commits in the master branch will let you toggle the scenarios

## 🔥 Exception or Error
<pre><code>
Error: src/app/repeat-section/repeat-section.type.component.ts:9:14 - error NG2006: The component RepeatSectionFormlyComponent inherits its constructor from FieldArrayType, but the latter does not have an Angular decorator of its own. Dependency injection will not be able to resolve the parameters of FieldArrayType's constructor. Either add a @Directive decorator to FieldArrayType, or add an explicit constructor to RepeatSectionFormlyComponent.

9 export class RepeatSectionFormlyComponent extends FieldArrayType {}
</code></pre>

## 🌍  Your Environment

This is the one not working. 

**Angular Version:**
<pre><code>
Angular CLI: 11.1.0
Node: 12.18.3
OS: darwin x64

Angular: 11.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1101.0
@angular-devkit/build-angular   0.1101.0
@angular-devkit/core            11.1.0
@angular-devkit/schematics      11.1.0
@angular/cdk                    10.2.7
@angular/material               10.2.7
@schematics/angular             11.1.0
@schematics/update              0.1101.0
rxjs                            6.6.3
typescript                      4.0.5
</code></pre>

**Comment by JoostK** [comment] 2021-01-23 13:27
It has regressed in https://github.com/angular/angular/commit/c55bf4a4a3127936b6714d9397416086f06df79a#diff-f64171de3bc6bd3aca1ecb9a6f9711ee7b5e5e87d8c01bb4759aca4831baa71dR39, where declaration files are now taken into account with respect to their constructor parameters.

**Comment by JoostK** [comment] 2021-01-23 18:40
Note that support for missing decorators has been dropped in Angular 10 ([source](https://v10.angular.io/guide/deprecations#removed-apis)); the scenario that regressed here could arguably be considered a bug fix for when the undecorated base class is declared in a declaration file. I verified that this scenario wasn't working correctly at runtime, as `FieldArrayType` would be constructed without injecting `FORMLY_CONFIG`. This may have gotten unnoticed because that parameter is optional; in fact it would have logged a warning if it _was_ provided:

https://github.com/ngx-formly/ngx-formly/blob/f8fa14e4cc015c1c8e233faa8fe357fe931ebfdd/src/core/src/lib/templates/field-array.type.ts#L22-L24

I do have a commit which applies 973bb403a51245dd3dca939fd9eb2c377e9004bb for directives (said commit only targeted services) but I feel this is working as expected now; the fact that the issue got unnoticed before was a bug and this is now properly reported as an error.

**Comment by vespertilian** [comment] 2021-01-24 22:53
@JoostK 

Hey Joost, thanks for your quick reply. I will follow up on the Formly repo. Sorry I checked the wrong branch for the @Directive() decorator.

**Comment by jelbourn** [comment] 2021-01-25 21:54
Closing since this seems to be working as intended per @JoostK.

**Closed by jelbourn** 2021-01-25 21:54 UTC
Labels: comp: compiler
