### ISSUE TITLE
routerLink adds tabindex even if the route is undefined

### ISSUE THREAD

**Issue by adamdport** [angular/angular#17616] opened 2017-06-19 18:24 UTC
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[X ] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
<div [routerLink]="undefined">has tabIndex</div>

## Expected behavior
<div [routerLink]="undefined">should not have tabIndex</div>

## Minimal reproduction of the problem with instructions

https://plnkr.co/edit/25H1bTPwqlJ33282MVh7?p=preview

## What is the motivation / use case for changing the behavior?
[Routerlink is supposed to now support null/undefined](6971). If it is null/undefined, it shouldn't impact the element at all. Having a tab index allows the user to focus on elements that shouldn't have focus

## Please tell us about your environment

<pre><code>
Angular version: 4.2.3

Browser:
- [X ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by inorganik** [comment] 2019-01-14 19:21
Should this issue still be open? 

Since the supplied plunkr no longer works, and is not minimal, I created a minimal stackblitz reproduction with Angular 7: https://stackblitz.com/edit/angular-undefined-routerlink

- it appears neither valid nor null/undefined routerLink values add a `tabIndex` attribute
- both add an `href`, if value supplied is null/undefined it links to the default route

If this is still an open issue, what should the fix be? Should it not add any `href` if the value supplied is null/undefined? Thanks

**Comment by inorganik** [comment] 2019-01-25 17:00
Bump.... pretty sure this can be closed

**Comment by nuts-n-bits** [comment] 2019-05-25 07:09
thanks @trotyl

**Comment by jelbourn** [comment] 2021-02-08 18:24
I'm going to close this as working-as-intended. Angular currently assumes that, buy nature of applying a `routerLink`, the element should be interactable. You can explicitly control this, though, by setting `tabindex` on the element.

**Closed by jelbourn** 2021-02-08 18:24 UTC
Labels: P3, comp: router, freq1: low, hotlist: community-help, router: directives, state: confirmed, state: has PR, triage #1, type: bug/fix
