### ISSUE TITLE
wrong markup compiles fine but fails at runtime

### ISSUE THREAD

**Issue by jnizet** [angular/angular#41058] opened 2021-03-02 22:19 UTC
# 🐞 enhancement request

### Affected Package
compiler, I guess

### Is this a regression?
I don't think so

### Description

The folllowing incorrect markup in a template compiles fine

```
<app-cmp [foo="user"]></app-cmp>
```

but fails at runtime with

```
DOMException: Failed to execute 'setAttribute' on 'Element': '[foo' is not a valid attribute name.
```
in Chrome (which is thus easy to diagnose), but with

```
DOMException: String contains an invalid character
```
in Firefox, without any indication in the stack trace of where the problem might be, making it harder to diagnose.

I would expect it to fail at compile-time rather than runtime.

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-ivy-5ijgyj?file=src%2Fapp%2Fapp.component.html

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 11.2.0
Node: 12.20.1
OS: darwin x64

Angular: 11.2.0
... animations, cli, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.0
@angular-devkit/build-angular   0.1102.0
@angular-devkit/core            11.2.0
@angular-devkit/schematics      11.2.0
@schematics/angular             11.2.0
@schematics/update              0.1102.0
rxjs                            6.6.3
typescript                      4.1.5

</code></pre>

**Comment by JoostK** [comment] 2021-03-03 08:24
Heya, thanks for reporting. This is a dupe of #39114 / #39781, so I'll close this one in favor of those.

**Closed by JoostK** 2021-03-03 08:24 UTC
Labels: comp: compiler, comp: language-service, compiler: parser, feature

**Comment by jnizet** [comment] 2021-03-03 08:32
Sorry for the dupe. Thanks @JoostK
