### ISSUE TITLE
Document.click handler is called twice when click on label with inner input[checkbox]

### ISSUE THREAD

**Issue by mdudek** [angular/angular#21002] opened 2017-12-14 08:59 UTC
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Document.click handler is called twice when click on label with inner input[checkbox]
Clicking to the label with input[checkbox] element placed inside calls document.click event handler twice.

## Expected behavior
Click handler should be called once.

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/angular-document-click-issue

## Environment

<pre><code>
Angular version: 5.x
Browser:
- [x] Chrome (desktop) version (latest)
- [?] Chrome (Android) version XX
- [?] Chrome (iOS) version XX
- [x] Firefox version (latest)
- [?] Safari (desktop) version XX
- [?] Safari (iOS) version XX
- [x] IE version 11
- [x] Edge version (latest)

**Comment by JiaLiPassion** [comment] 2017-12-17 14:56
@mdudek , It seems everything is ok here, https://stackblitz.com/edit/angular-document-click-issue-w7drq7?file=app/app.component.ts

**Comment by mdudek** [comment] 2017-12-17 16:10
@JiaLiPassion , there is an issue when you click on first checkbox label (not directly to the checkbox). The handler is called twice.

**Comment by JiaLiPassion** [comment] 2017-12-21 12:42
@mdudek, it is not a bug of `angular`, here is a `pure` html. the click was triggered twice because `span` and `input` all trigger `document.onclick`.

```javascript
<!DOCTYPE html>
<html>
<head>
    <script>
window.onload = function() {
document.onclick = function() {
console.log('document clicked');
};
}
    </script>
</head>
<body>
    <div id="thetext">Hello Zones!</div>
<p>
  <label><input type="checkbox" name="ch1"/><span>Click here to receive document.click event twice (BUG)</span></label>
</p>
</body>
</html>
```

**Comment by pkozlowski-opensource** [comment] 2018-10-29 16:43
Closing based on https://github.com/angular/angular/issues/21002#issuecomment-353341531

**Closed by pkozlowski-opensource** 2018-10-29 16:43 UTC
Labels: comp: core & compiler, freq2: medium, severity3: broken, type: bug/fix
