### ISSUE TITLE
bug: Injectables in a DynamicComponent aren't recognized

### ISSUE THREAD

**Issue by ajoslin** [angular/angular#1596] opened 2015-04-29 19:53 UTC
- **Works**: A Component with an injectable: http://plnkr.co/edit/4uUq7Hqtk43ZHEQMbeM4?p=preview

- **Broken**: A DynamicComponent with an injectable: http://plnkr.co/edit/lJyRdelIxhInuGn5blnl?p=preview

**Comment by mhevery** [comment] 2015-04-29 20:32
Is this a dup of #1566 ?

**Comment by ajoslin** [comment] 2015-04-30 17:58
Yes.

**Comment by pkozlowski-opensource** [comment] 2015-04-30 18:23
Ok, closing as duplicate of #1566

**Closed by pkozlowski-opensource** 2015-04-30 18:23 UTC
Labels: ♥ Ionic
