### ISSUE TITLE
RouterLink directive render wrong URL which contains named outlet

### ISSUE THREAD

**Issue by chimung** [angular/angular#33887] opened 2019-11-18 02:12 UTC
# 🐞 bug report

### Affected Package
@angular/router

### Is this a regression?
No

### Description
When i using directive RouterLink to render URL, instead of updating outlet path, it append new outlet.
```
<a [routerLink]="['/other', { outlets: { otherOL: ['other']}}]"></a>
```
Expected
```
https://angular-rwhvmh.stackblitz.io/other(otherOL:other)
```
Actual
```
https://angular-rwhvmh.stackblitz.io/other/(otherOL:other)(otherOL:home)
```

## 🔬 Minimal Reproduction

 [Stackblitz](https://angular-rwhvmh.stackblitz.io)

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 7.3.8
Node: 10.17.0
OS: darwin x64
Angular: 7.2.15
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.8
@angular-devkit/build-angular     0.13.9
@angular-devkit/build-optimizer   0.13.9
@angular-devkit/build-webpack     0.13.9
@angular-devkit/core              7.3.8
@angular-devkit/schematics        7.3.8
@angular/cli                      7.3.8
@ngtools/webpack                  7.3.9
@schematics/angular               7.3.8
@schematics/update                0.13.8
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.29.0
</code></pre>

**Anything else relevant?**

**Comment by pkozlowski-opensource** [comment] 2019-11-18 19:33
@chimung you've marked it as a regression so I wanted to ask what is the previous Angular version where it worked correctly for you?

**Comment by chimung** [comment] 2019-11-19 02:15
> @chimung you've marked it as a regression so I wanted to ask what is the previous Angular version where it worked correctly for you?

Sorry. I did update the answer is NO. 
I got problem in Angular version 7.3.8 on my local machine. When i make a reproduction in stackblitz with version 8.0.0, it still got problem.
I never try reproduce in previous version.

**Comment by atscott** [comment] 2020-05-29 19:19
Closing as duplicate of #13872 / #13589

**Closed by atscott** 2020-05-29 19:19 UTC
Labels: comp: router, freq2: medium, router: URL parsing/generation, router: aux routes, severity2: inconvenient, triage #1, type: bug/fix
