### ISSUE TITLE
Content isn't fully visible in reactive forms docs

### ISSUE THREAD

**Issue by notauserx** [angular/angular#47836] opened 2022-10-23 16:30 UTC
### Describe the problem that you experienced

When I was reading through the docs, I found the section where it describes how to refactor the ProfileEditor component to use the form builder service to create form control and form group instances.

However the instructions on the details column is not fully visible inside the cell. I have to drag the text to see the full content. This seems inconsistent with all the other content on cells which wraps so all the text is visible.

### Enter the URL of the topic with the problem

https://angular.io/guide/reactive-forms#using-the-formbuilder-service-to-generate-controls

### Add a screenshot if that helps illustrate the problem

![text_wrap_issue](https://user-images.githubusercontent.com/82922717/197403924-545c346a-785b-412e-bd46-cf5ce5803f89.gif)

**Comment by geromegrignon** [comment] 2022-10-27 06:44
@pkozlowski-opensource that's already tracked with #47535

**Comment by pkozlowski-opensource** [comment] 2022-10-27 07:10
Thnx @geromegrignon - appreciate it. Closing as a duplicate of #47535

**Closed by pkozlowski-opensource** 2022-10-27 07:10 UTC
Labels: area: docs-infra
