### ISSUE TITLE
Date Pipe formats 2022-01-01 to 2021-01-01

### ISSUE THREAD

**Issue by MrBacony** [angular/angular#44715] opened 2022-01-14 11:12 UTC
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

No

### Description

On the first day of this year, the formatting of the dates via DatePipe returns the last year.

`const date = new Date(2022, 0, 1);`
`{{date | date: 'YYYY'}}`

this results in `2021`

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-date-pipe-bug

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.1.2
Node: 12.20.1
Package Manager: npm 6.14.15
OS: darwin x64

Angular: 13.1.1
... animations, cdk, common, compiler, compiler-cli, core, forms
... material, material-moment-adapter, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1301.2
@angular-devkit/build-angular   13.1.2
@angular-devkit/core            13.1.2
@angular-devkit/schematics      13.1.2
@angular/cli                    13.1.2
@schematics/angular             13.1.2
rxjs                            6.6.3
typescript                      4.5.4
```

### Anything else?

This bug happens also in previous versions

**Comment by JoostK** [comment] 2022-01-14 15:37
Duplicate of #44350. You need to use `yyyy` instead of `YYYY`.

**Closed by JoostK** 2022-01-14 15:37 UTC
