### ISSUE TITLE
Typescript latest version

### ISSUE THREAD

**Issue by IvanStack** [angular/angular#34530] opened 2019-12-21 18:38 UTC
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/....

### Description
 A clear and concise description of the problem or missing capability...

### Describe the solution you'd like
 If you have a solution in mind, please describe it.

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

**Comment by mlc-mlapis** [comment] 2019-12-21 18:49
@IvanStack It's in the plan for 9.1 release.

**Comment by manklu** [comment] 2019-12-21 21:41
Duplicate of https://github.com/angular/angular/issues/33596

**Comment by JoostK** [comment] 2019-12-22 17:54
Thanks for reporting this issue. However this issue is a duplicate of an existing issue #33596. Please subscribe to that issue for future updates.

**Closed by JoostK** 2019-12-22 17:54 UTC
