### ISSUE TITLE
Ivy: Library tree-shaking

### ISSUE THREAD

**Issue by waterplea** [angular/angular#33531] opened 2019-11-01 15:13 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/cli probably

### Is this a regression?

 Yes, the previous version works fine

### Description

 I tried my Angular 8 UI library with Ivy application using Angular 9 RC and even if I only use a single independent module from it, the whole library gets into bundle. In Angular 8 tree shaking worked properly and only the code I used in the app got into bundle after compilation. I was wondering if this is expected behavior during NGCC phase when apps are using Ivy and libraries are still created with view engine?

## 🔬 Minimal Reproduction

 It's pretty hard to give a reproduction for such an issue, especially since my library is proprietary :( It is organized into single component/directive — single module and a public-api barrel file, pretty much like CLI would create.

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
9.0.0-rc.0
</code></pre>

**Comment by IgorMinar** [comment] 2019-11-09 01:26
The tree-shaking of libraries should not be affected with Ivy (if anything it should be improved).

In our tests the tree shaking works well, so we will need a reproduction of this scenario before we can do anything about it.

Can anyone provide a repro? thank you!

**Comment by alxhub** [comment] 2019-11-19 23:13
I'm going to close this issue due to the lack of a reproduction. Please feel free to open a new one with a repro if you're still seeing this problem.

**Closed by alxhub** 2019-11-19 23:13 UTC
Labels: comp: ivy, comp: ngcc, state: Needs repro
