### ISSUE TITLE
bug(service-worker): wrong script url when building with base-href

### ISSUE THREAD

**Issue by Ploppy3** [angular/angular#21060] opened 2017-12-16 12:37 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
When building with `build --prod --base-href /test/`
App searches for the service-worker script at root folder `/` instead of within the `/test` folder.

## Expected behavior
When building with `build --prod --base-href /test/`
App should search for the service-worker script in the `/test` folder.

## Minimal reproduction of the problem with instructions
- Create a new project.
- Set up service worker.
- app.component.html
`<base href="/test">`
- `ng build --prod --base-href /test/`
![image](https://user-images.githubusercontent.com/7990765/34070413-e101c238-e265-11e7-81ad-48486b92c8dc.png)

## Environment

<pre><code>
Angular version: 5.1.1

Browser:
- [X] Chrome (desktop) version 63.0.3239.108 x64
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.9.1
- Platform:  Windows

</code></pre>

**Comment by gkalpak** [comment] 2017-12-18 10:46
Duplicate of angular/angular-cli#8515.

**Closed by gkalpak** 2017-12-18 10:46 UTC

**Comment by felyperennan** [comment] 2018-06-20 13:55
I worked around that this way:

Adding this line at the start of my App Module, right after the imports
`const baseUrl = document.getElementById('baseurl').getAttribute('href').toString();`

Making my base attribute have an Id
`<base id="baseurl" href="/path/to/" />`

and 
Then using this custom baseUrl to specify where to look for the ngsw worker
`ServiceWorkerModule.register(baseUrl + 'ngsw-worker.js', { enabled: environment.production }),`

Not the beautifulest thing I ever did but it worked. I had to do it this way because the baseUrl is generated with SSR (yes I too hate SSR, but its for multi tenancy)
