### ISSUE TITLE
minLength validator returns minlength error key 

### ISSUE THREAD

**Issue by piernik** [angular/angular#25277] opened 2018-08-03 07:53 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
If `Validators.minLength(5)` validation is false angular returns `minlength` error key (all lower case).

## Expected behavior
It should return the same as function name.
I'm creating custom form creator and getting error message using that code is not possible due to case:
```
validators: {
   minLength: {fnParams: [5], message: 'Too short'}
}
```

**Comment by trotyl** [comment] 2018-08-03 08:08
Duplicate of https://github.com/angular/angular/issues/7407

**Comment by kara** [comment] 2018-08-03 16:50
@piernik Understand the confusion, but as discussed in #7407, we've decided to keep the validator names in sync with the native property names and the error messages in sync with the native validation errors. This is not likely to change given that it will break many existing apps.

**Closed by kara** 2018-08-03 16:50 UTC
