### ISSUE TITLE
Reactive forms custom CVA form component async validator weird behaviour

### ISSUE THREAD

**Issue by Harpush** [angular/angular#38464] opened 2020-08-14 10:06 UTC
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/forms

### Is this a regression?
Happens in previous versions too

### Description
When creating a composite form control using CVA and AsyncValidator interfaces i cant seem to propagate the errors correctly.
I have a form inside the custom form component with an async validator. When i am trying to propagate the errors to the outer form through the AsyncValidator's validate function it doesn't seem to work for all cases.
If i am writing something in the inner input - everything is working fine.
On the other hand, if i try to setValue from outside - the validation won't work. It seems as if the validation process happens on the parent before it happens on the child thus not catching the error to come.
The only way i could somehow make it work is by using NgZone's onStable observable... but then change detection doesn't work.
Is there anyway to achieve it? Am i doing something wrong? Is it a bug in how the validators are handled?

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-ivy-h5ipor

## 🌍  Your Environment
**Angular Version:**
10.0.1

**Comment by sonukapoor** [comment] 2020-08-25 11:39
@Harpush This is caused because `setValue` was called with `emitEvent: false`.

If you set this to `true`, then the underlying `statusChanges` event will be emitted, which should resolve the issue. You can see this working in the below fork from the stackblitz you provided:

https://stackblitz.com/edit/angular-ivy-k7ovdb?file=src%2Fapp%2Fdetails%2Fdetails.component.ts

I'm closing this ticket since the problem is specific to the implementation of the custom ControlValueAccessor and there are no action items for the framework itself.

**Closed by sonukapoor** 2020-08-25 11:39 UTC
Labels: comp: forms, forms: ControlValueAccessor, forms: Controls API, forms: validators
