### ISSUE TITLE
Form is not dirty anymore when showing/hiding disabled select 

### ISSUE THREAD

**Issue by mivanyna** [angular/angular#18222] opened 2017-07-19 08:32 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

If we have a form with tabs or some logic that hides and shows fields and one of them is select which is disabled - the form loses dirty state on hiding and showing select again.

Here is plnkr:
https://plnkr.co/edit/PUosCrPCUh34y2DY3ltK?p=preview

## Expected behavior

Form shouldn't lose dirty state

## Minimal reproduction of the problem with instructions

Show hidden fields
Edit input -> form dirty
Hide fields
show again - form is not dirty anymore if select is disabled
https://plnkr.co/edit/PUosCrPCUh34y2DY3ltK?p=preview

## What is the motivation / use case for changing the behavior?

Form with controls on different tabs 

## Environment

<pre><code>
Angular version: 2.4.10 (and the latest also)

Browser:
- [x ] Chrome (desktop) version  59.0.3071.115
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by mivanyna** [comment] 2017-07-19 09:03
Workaround is to set select readonly and each option deisabled.

**Comment by AndrewKushnir** [comment] 2020-08-12 22:28
Hi @mivanyna, thanks for reporting the issue and providing a repro.

I've [re-created the repro using Stackblitz](https://stackblitz.com/edit/angular-ivy-18222) and recent versions of Angular packages (and Ivy enabled) and I was unable to reproduce the issue.

I will close this ticket for now (since I was unable to reproduce it), please create a new ticket (with updated repro) is the problem still exists.

Thank you.

**Closed by AndrewKushnir** 2020-08-12 22:28 UTC
Labels: comp: forms, forms: disabling controls, freq2: medium, severity1: confusing, state: needs more investigation, triage #1, type: bug/fix
