### ISSUE TITLE
ERROR TypeError: Cannot read property 'length' of null at HttpHeaders.applyUpdate

### ISSUE THREAD

**Issue by pranaykumar389** [angular/angular#20999] opened 2017-12-14 01:25 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

This error occurred when I'm making httpClient.get() call to a REST API.

## Expected behavior

If we a call http://localhost:3000/api/public it must return all the list of jobs but instead it throws an error in the front-end.

## Minimal reproduction of the problem with instructions

[http://plnkr.co/edit/DXI3tsRu17zUvMoDAov1?p=info] my plunker for reference.

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.1.4  
- Platform:  Windows 

Others:

</code></pre>

**Comment by beeing** [comment] 2018-02-28 11:46
We are facing same problem here. HttpClient.get will hit error if we pass in headers.

**Comment by paddyfink** [comment] 2018-03-22 15:38
Hey, we facing the same issue, but only with a specific customer. For the others, it works fine. And that customer has that issue only in Chrome. It works on Edge.

**Comment by johnfrades** [comment] 2018-03-31 08:59
currently experiencing this issue, i've never updated any packages. All of a sudden, i just got this error

**Comment by trotyl** [comment] 2018-03-31 09:05
See https://github.com/angular/angular/issues/18743#issuecomment-323215006

**Comment by paddyfink** [comment] 2018-04-03 19:17
I confirm, it was the case for me. I was passing a undefined value to HttpHeaders.set. It,s all good now

**Comment by BotanMan** [comment] 2019-01-25 08:04
Got the same issue, the reason of that was setting `null`/`undefined` as header at interceptor 
```
req = req.clone({
        setHeaders: {
              'my-custom-header': key // which is basically not available null or undefined
        }
});
```

**Comment by rafame2** [comment] 2020-03-27 18:48
HttpHeaders.applyUpdate should check for null before checking length of value...

**Comment by JoostK** [comment] 2020-03-27 19:10
Closing as working as intended per https://github.com/angular/angular/issues/18743#issuecomment-323215006.

**Closed by JoostK** 2020-03-27 19:10 UTC
Labels: comp: common/http, freq2: medium, severity3: broken, type: bug/fix

**Comment by khizaruddins** [comment] 2020-04-23 06:36
same issue
