### ISSUE TITLE
Angular SSR cannot use ESM modules (Domino compatibility issue)

### ISSUE THREAD

**Issue by its-dibo** [angular/angular#45062] opened 2022-02-12 18:30 UTC
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

I just created a fresh Angular universal app using Angular cli. it just works fine.

however, when I just add `"type": "module"` to `package.json` and serve again (with or without rebuilding the app again) it fails with the error `Strict mode code may not include a with statement`

**reproduction steps**
1- create a new Angular universal app `ng new example && cd example && ng add @nguniversal/express-engine`
2- run `npm start` -> `npm run build:ssr && npm run serve:ssr` (suceesed)
3- add `"type": "module"` and run `npm run serve:ssr` or `npm start` again (faild with ` Strict mode code may not include a with statement`)
4- remove `"type": "module"` and run `npm run serve:ssr` without rebuilding the app (successed)

**trials**
- remove `ServerModule` from imports[] im app/app.server.module.ts
- remove `export { renderModule } from '@angular/platform-server';` in app/main.server.ts
- run `npm start` to rebuild the app (failed with the same error)

### Please provide a link to a minimal reproduction of the bug

https://github.com/eng-dibo/issue-angular-esm
or
https://stackblitz.com/github/eng-dibo/issue-angular-esm

### Please provide the exception or error you saw

```true
`Strict mode code may not include a with statement` only with esm i.e: `type: module`
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.2.3
Node: 16.13.2
Package Manager: npm 8.1.2
OS: linux x64

Angular: 
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1302.3 (cli-only)
@angular-devkit/core         13.2.3 (cli-only)
@angular-devkit/schematics   13.2.3 (cli-only)
@schematics/angular          13.2.3 (cli-only)
```

**Comment by alan-agius4** [comment] 2022-02-12 19:19
Unfortunately, this is blocked on Domino.

**Comment by magyargergo** [comment] 2022-03-17 16:23
Hey @alan-agius4 ,

Are you planning to internalise that library? What is your the plan? Unfortunately, They have not touched their code for 2 years. https://github.com/fgnass/domino

**Comment by eng-dibo** [comment] 2022-07-20 20:48
I upgraded to Angular v14 and the issue still occurs

**Comment by eng-dibo** [comment] 2022-09-04 12:06
any news?
@magyargergo @alan-agius4 @brad @abraham

**Comment by alan-agius4** [comment] 2022-09-04 12:13
@eng-dibo, no ad the issue is still open.

**Comment by eng-dibo** [comment] 2022-09-04 12:46
> Likely we will replace it with another implementation.

as you mentioned, can we replace Domino with another implementation?

**Comment by magyargergo** [comment] 2022-09-05 08:33
@eng-dibo for the time being, this can be a workaround solution https://github.com/fgnass/domino/pull/180

**Comment by eng-dibo** [comment] 2022-09-05 08:48
> @eng-dibo for the time being, this can be a workaround solution [fgnass/domino#180](https://github.com/fgnass/domino/pull/180)

OK, I will give it a try, many thanks to you

**Comment by eng-dibo** [comment] 2022-09-05 08:51
> @eng-dibo for the time being, this can be a workaround solution [fgnass/domino#180](https://github.com/fgnass/domino/pull/180)

many thanks, hope it merged very soon

**Comment by itsmiracler** [comment] 2022-10-17 08:00
the issue still occurs - angular14

**Comment by magyargergo** [comment] 2022-12-23 09:45
I took a look at the `webpack` side and it seems that lib doesn't support `"type": "module"` from `package.json`. https://github.com/webpack/webpack/pull/15198. I think, it will be necessary to pass a `loader` into the `webpack` config.  It can load `CommonJS` resolvers though https://github.com/webpack/loader-runner/issues/67.

**Comment by magyargergo** [comment] 2022-12-23 10:08
Can @AndrewKushnir or @alan-agius4 please explain to me if webpack produce bundles with import statements how we can setup `webpack-dev-server` to use a custom module loader in runtime? It seems, once the build is successful, NodeJS module resolution doesn't respected because, I assume, `webpack-dev-server` takes over the interpretation of the JS bundles.

**Comment by renatoaraujoc** [comment] 2023-01-29 23:03
I tried to migrate my Nx Angular workspace to ESM, did everything right but the Universal Server cannot be started due to the Domino issue. I guess I have to go back CommonJS then? I'm using latest versions of everything (angular and universal). Node 16/18, none works.

![Screenshot 2023-01-29 at 20 01 57](https://user-images.githubusercontent.com/358128/215360638-e1911976-fa4f-4f29-a00f-601b44722f31.png)

**Comment by magyargergo** [comment] 2023-03-09 14:50
> I tried to migrate my Nx Angular workspace to ESM, did everything right but the Universal Server cannot be started due to the Domino issue. I guess I have to go back CommonJS then? I'm using latest versions of everything (angular and universal). Node 16/18, none works.
> 
> ![Screenshot 2023-01-29 at 20 01 57](https://user-images.githubusercontent.com/358128/215360638-e1911976-fa4f-4f29-a00f-601b44722f31.png)

It seems, they have been working on the fix already
- https://github.com/angular/domino

**Closed** 2023-03-09 17:49 UTC
Labels: area: server, P2, bug
