### ISSUE TITLE
Create a rxjs/stream/Subject variant of @Input()

### ISSUE THREAD

**Issue by filipvh** [angular/angular#29298] opened 2019-03-14 09:09 UTC
# 🚀 feature request

### Relevant Package
This feature request is for @angular/core

### Description
Input deserves a brother that is a stream. There are libs that help you with creating this, but, having a decorator that makes a Input into a stream, would be awesome/useful.
ex:  @RxInput(bufferSize: number) varName: ReplaySubject; 
Or @InputStream( ....

**Comment by pkozlowski-opensource** [comment] 2019-03-14 09:32
This is a duplicate of an existing issue #5689

**Closed by pkozlowski-opensource** 2019-03-14 09:32 UTC
