### ISSUE TITLE
if my project import zone, Antd select will  execute in Infinite loop.  Help me，Please!

### ISSUE THREAD

**Issue by DD-hd** [angular/angular#44249] opened 2021-11-23 06:53 UTC
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

This is simple demo，if you select the option ，you web will in lock，and no import zone，it will be normal

demo project： https://stackblitz.com/edit/react-xq6x7r?file=index.js [project link](https://stackblitz.com/edit/react-xq6x7r?file=index.js)

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/react-xq6x7r?file=index.js

### Please provide the exception or error you saw

```true
import React from 'react';
import ReactDOM from 'react-dom';
import 'antd/dist/antd.css';
import './index.css';
import { Select } from 'antd';
import 'zone.js';

const { Option } = Select;

function handleChange(value) {
  console.log(`selected ${value}`);
}

ReactDOM.render(
  <>
    <Select defaultValue="lucy" style={{ width: 120 }} onChange={handleChange}>
      <Option value="jack">Jack</Option>
      <Option value="lucy">Lucy</Option>
      <Option value="disabled" disabled>
        Disabled
      </Option>
      <Option value="Yiminghe">yiminghe</Option>
    </Select>
    <Select defaultValue="lucy" style={{ width: 120 }} disabled>
      <Option value="lucy">Lucy</Option>
    </Select>
    <Select defaultValue="lucy" style={{ width: 120 }} loading>
      <Option value="lucy">Lucy</Option>
    </Select>
    <Select defaultValue="lucy" style={{ width: 120 }} allowClear>
      <Option value="lucy">Lucy</Option>
    </Select>
  </>,
  document.getElementById('container')
);
```

### Anything else?

please help me

**Comment by JoostK** [comment] 2021-11-23 07:56
Duplicate of #41506.

**Closed by JoostK** 2021-11-23 07:56 UTC
