### ISSUE TITLE
bindToComponentInputs=true breaks default/initial value of field with @Input() 

### ISSUE THREAD

**Issue by merkisoft** [angular/angular#52946] opened 2023-11-16 00:14 UTC
### Which @angular/* package(s) are the source of the bug?

router or core

### Is this a regression?

No

### Description

given the following class:

```
export class SimpleComponent {
  @Input() readonly = true;   
}
```

and route:
`  { path: '', component: SimpleComponent, pathMatch: 'full'  },`

the default value is undefined if 
`      bindToComponentInputs: true,   `

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/github-w4jhh2?file=src%2Fmain.ts

### Please provide the exception or error you saw

```true
readonly = - (default is true)

--- 

change line 53 to : false, then the default works again:
readonly = true - (default is true)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
"@angular/animations": "17.0.3",
    "@angular/common": "^17.0.3",
    "@angular/compiler": "^17.0.3",
    "@angular/core": "^17.0.3",
    "@angular/platform-browser": "^17.0.3",
    "@angular/platform-browser-dynamic": "^17.0.3",
    "@angular/router": "^17.0.3",
```

**Comment by merkisoft** [comment] 2023-11-16 00:20
btw this line on https://angular.io/guide/component-interaction shows that @Input may have a default value:
```
@Input('master') masterName = '';
```

**Comment by atscott** [comment] 2023-11-16 02:27
The default value applies when no value is bound in the template. The implementation of input binding specifically sets any not present values to `undefined`. This avoids the situation where a value is available at some point and a new navigation causes the value to go away. Failing to set the input to `undefined` would mean that it would retain the value from a previous navigation state. 

Closing as working as expected.

**Comment by atscott** [comment] 2023-11-16 02:32
Reopening and labeling as a documentation issue. The API docs should call this out and also mention that `{required: true}` does not apply in this situation either.

**Comment by merkisoft** [comment] 2023-11-16 06:14
the problem is that it breaks existing, working code when upgrading to router input binding and maybe a very unexpected thing (at least for me it was, luckily I found that before going to production)

**Comment by signalp** [comment] 2023-12-24 17:56
Unless there in a very clear lifecycle hook or any other clear timing to initialize @Input vars after they have or have not been assigned values by the router, this is very difficult to negotiate

**Comment by merkisoft** [comment] 2023-12-24 18:57
I would have preferred to name it something different @RouterInput()
or alike as it has different semantic

**Comment by luii** [comment] 2024-01-15 14:44
> I would have preferred to name it something different @RouterInput() or alike as it has different semantic

Why not just redefine the `@Input` as `@RouterInput` / `@ResolverInput`, etc. this can be easily done via the imports, for me it looks something like this: 

```
import {
  Component,
  inject,
  Input as RouteInput,
  Input as ResolverInput,
} from '@angular/core';

```

**Comment by petertenklooster** [comment] 2024-02-10 10:11
Similar to this issue, an input signal with default value is also not working when using withComponentInputBinding().

`title = input<string>('Default string');`

Will not display the default string when no router params are provided. It would make more sense to me when values with an initial value would keep their initial value when no router params are available, and the current behaviour of setting the values to undefined would only apply to inputs without a default value.

**Comment by olegdunkan** [comment] 2024-04-12 15:22
As I understand, when inputs are filled by router then initial values are not considered. When inputs are filled by anything else, then initial values make sense. 
Isn't that strange?

**Comment by valiant-code** [comment] 2024-05-02 20:26
I agree this is very confusing. I was able to achieve basically what I wanted using an additional computed signal to read my optional query param or take my default value. This feels very clunky. Especially given the fact that the input function does have a whole parameter to provide a default.

```
myOptionalParam = input<string>('this Default Does Nothing', {alias : 'myParam'});
myParam = computed(() => this.myOptionalParam || 'defaultValue');
```

**Comment by ettubrute47** [comment] 2024-06-17 16:04
To add to this, I know it's not a bug and an 'intended' feature, but is it possible to add a configuration option to withComponentInputBinding that would allow bypassing setting unset inputs to undefined? I think most people would prefer that option, especially in the case where a component is designed to work both within other components and directly through router-outlet, as the former would make default input values much more common.

Also I agree documentation is lacking, I thought this was a bug for a couple of hours until I tested removing/re-adding withComponentInputBinding to realize it was passing 'undefined' in for the inputs by design. This issue ticket is actually the only direct documentation I could find on the issue.

**Comment by flensrocker** [comment] 2024-06-30 08:44
I also think (re)setting the initial value when the route does not supply the input would be more consistent.

For now I use the `transform` option instead of an extra compute, which needs the extra typing and doubling the default value.

```typescript
readonly myParam = input('default', { transform: (v: string | undefined) => v ?? 'default' });
```

**Comment by hungtcs** [comment] 2024-07-27 04:21
> I also think (re)setting the initial value when the route does not supply the input would be more consistent.
> 
> For now I use the `transform` option instead of an extra compute, which needs the extra typing and doubling the default value.
> 
> ```ts
> readonly myParam = input('default', { transform: (v: string | undefined) => v ?? 'default' });
> ```

For some reason, this seems to have some effect on SSRs, and I get a weird error when I do it this way

```
[vite] Internal server error: Cannot read properties of undefined (reading 'hasAttribute')
```

**Comment by srnec** [comment] 2024-09-03 15:13
I understand @atscott's arguments but I still think this behavior is a bug.
Imagine we have working angular app, then if we toggle `bindToComponentInputs` ON then suddenly we get `undefined` in our inputs even though they are defined with initial value. This issue is then only noticed during runtime because from type perspective input has initial value, therefore it cannot be `undefined`.

I would also suggest to rather not reuse `input()` for route params but create something liker `routeInput()` that can always be 'undefined`, also it will be clear it is meant for route params and we will not mix regular component inputs with route param inputs.

**Comment by avine** [comment] 2024-09-05 20:16
i think that we should not have things like `@RouterInput()` because the advantage of `withComponentInputBinding` is that now we can create components that works exactly the same when used in "parent > child" context AND in "router" context.

If we have `@RouterInput()` it's just like using the old way : `this.router.params...`.

**Comment by atscott** [comment] 2024-09-06 16:13
Setting up an input with an initial value, i.e.`@Input() readonly = true;`, is an _initial value_ only to be used when the owner of the component has not (yet) bound a value. It is not a default value, but an initial value. Once the owner of the component chooses to bind to the input, there is no way to revert back to the initial value. This applies to templates as well: once a template binds a value, you cannot _remove_ that binding to revert back to the initial value.

When using router input binding, the Router takes charge of binding all inputs for the component. The only somewhat reasonable alternative to the current approach would be to not bind when the key is not present in the data, then assign `undefined` as it does today if an input key was present and then removed to avoid presenting stale information. This still requires routes to handle missing inputs for the component.

Components used in routes with input binding enabled should either ensure the inputs are always present or the component should configure a default with an input transform. The documentation is being updated to mention this.

**Comment by avine** [comment] 2024-09-06 17:13
> When using router input binding, the Router takes charge of binding all inputs for the component. The only somewhat reasonable alternative to the current approach would be to not bind when the key is not present in the data, then assign `undefined` as it does today if an input key was present and then removed to avoid presenting stale information. This still requires routes to handle missing inputs for the component.

I think that's perfect!
Because, depending on the functional use case, there are probably inputs that are not intended to be ever bound by the router.
In this case, we simply want these inputs to be untouched by the router binding. 
They are typically updated by the component itself using a template event binding.

**Comment by atscott** [comment] 2024-09-06 17:28
> I think that's perfect!
Because, depending on the functional use case, there are probably inputs that are not intended to be ever bound by the router.
In this case, we simply want these inputs to be untouched by the router binding.

Note that there are no plans to do this. It isn't possible guarantee that an input will never be present and then subsequently removed because users can type whatever they want into the URL. Default values should be configured through resolvers or input transforms.

**Comment by avine** [comment] 2024-09-06 17:39
It is still relevant to have the initial value untouched if the input is not part of the router configuration.

**Comment by avine** [comment] 2024-09-07 21:28
> The only somewhat reasonable alternative to the current approach would be to not bind when the key is not present in the data, then assign `undefined` as it does today if an input key was present and then removed to avoid presenting stale information.

I'm not so sure myself that this is a good idea anymore (maybe the current implementation is the best...).

Because with this alternative, the same URL could display different results depending on the user location history.

Let's demonstrate that.

Let's take this component:

```ts
@Component({
  selector: 'app-product',
  template: `
    <h1>{{ products().title }}</h1>

    @if (!skipDetails()) {
      <p>{{ products().details }}</p>
    }
  `,
})
export class ProductComponent {
  product = input.required<Product>();

  skipDetails = input(true);
}
```

The route configuration has a `resolver` which takes the `productId` from the route params and returns the `product`:

```ts
export const routes: Routes = [
  {
    path: 'product/:productId',
    resolve: { product: productResolver },
    component: ProductComponent,
  }
];
```

If we visit the following URLs in this order :

```txt
http://localhost:4200/product/25
```

We see the product 25. And since the `skipDetails` input is not part of the router configuration, it retains its initial value (`true`).

**!!! The details are skipped !!!**

Then the user visits:

```txt
http://localhost:4200/product/26&skipDetails=false
```

The product 26 is displayed, but this time the details are not skipped.

Finally, the user clicks on his browser's “back” button.

```txt
http://localhost:4200/product/25
```

The `skipDetails` input is again absent from the router and therefore receives now the value `undefined` (which is equivalent to `false`).

**!!! The details are NOT skipped this time !!!**

**Closed** 2024-10-01 08:09 UTC
Labels: area: router, P3, area: docs

**Comment by dailytabs** [comment] 2024-10-05 11:11
Fix feels insufficient. Should be documented with **https://angular.dev/api/router/ExtraOptions#bindToComponentInputs**, too, where most people actually use it from, right? And, what about on `@Input`, where people are told to use it even though it interferes with the router setting?

Are you trying to close this ticket, or resolve the confusion for good?

- Is there even any good documentation on what this setting does, why I would want it true/false, trade-offs, etc.?
- Can we pass static values for inputs in our router config? (Forcing everyone to filter a setter is yucky!)
- If stale inputs are the concern, is there a way to simply re-init the component everytime, so stale Inputs are no longer a concern (for a single user, not suggesting an angular change)?
- And, it 100% feels dirty to re-use Input for route params. This is a mess!

**Comment by simeyla** [comment] 2024-10-31 23:06
This caught me out today with a very important component after having enabled `bindToComponentInputs` a few months ago. Yes - it took months to notice and affected real customers that only finally reported it yesterday.

I appreciate all the technical explanation above, but that didn't help me figure out where in my code this might be occuring. Going through all the @Input properties I've ever created one by one didn't seem like much fun.

So to get a 'quick sense' of where this may cause actually issues I created a conditional logpoint.

1) Search for `outlet.activatedComponentRef.setInput` in your browser. It should be only in one place. This is part of the binding process for a routed component.

2) Add the following log point (breakpoint type) to print out the metadata when an `@Input` is being set that isn't present in the data:

> (templateName in data == false) && (!mirror.inputs.find(i=>i.templateName == templateName).transform && !mirror.inputs.find(i=>i.templateName == templateName).signal) && `@INPUT property ${templateName} not found in data for ${outlet.activatedComponentRef.componentType.name}`

![Image](https://github.com/user-attachments/assets/32838c11-902f-4cd3-a240-957638771a0e)

3) Filter your console for `@INPUT` and play around in your app where you suspect you have a routed component.

It will show all the places you're setting an input value from routing data (ignoring properties where you have a transform function). You can then fix as needed.

For example this:

    @Input('maxInitialItems')
    maxInitialItems = 10;

Could be fixed as:

    @Input({ alias: 'maxInitialItems', transform: (value: number) => value ?? 10 })
    maxInitialItems = 10;

Hope this helps. I've managed to find a few places quickly and meh I don't have to fix it all at once right!

![Image](https://github.com/user-attachments/assets/2c584a39-dc22-4d76-ac16-d905f884363d)
