### ISSUE TITLE
Ivy breaks enableResourceInlining

### ISSUE THREAD

**Issue by jonrimmer** [angular/angular#30174] opened 2019-04-27 18:28 UTC
# 🐞 bug report

### Affected Package

The issue is caused by package @angular/compiler

### Is this a regression?

Unknown

### Description

If `enableIvy` is `true`, then `enableResourceInlining: true` has no effect. The compiled code still has template urls and style urls and tries to load them.

## 🔬 Minimal Reproduction

```
git clone https://github.com/jonrimmer/angular-inlining-is-broken.git
cd angular-inlining-is-broken
npm install
npm run build
./node_modules/.bin/ngc -p ./tsconfig.app.json
```

Now examine [out-tsc/app/src/app.component.js](https://github.com/jonrimmer/angular-inlining-is-broken/blob/master/out-tsc/app/src/app/app.component.js). You will see that it still contains `templateUrl` and `styleUrls` properties in the emitted component metadata. If the app is served, it will still try to load these files dynamically, even if they do not exist.

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 8.0.0-rc.1
Node: 11.10.1
OS: darwin x64
Angular: 8.0.0-rc.1
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.0-rc.1
@angular-devkit/build-angular     0.800.0-rc.1
@angular-devkit/build-optimizer   0.800.0-rc.1
@angular-devkit/build-webpack     0.800.0-rc.1
@angular-devkit/core              8.0.0-rc.1
@angular-devkit/schematics        8.0.0-rc.1
@ngtools/webpack                  8.0.0-rc.1
@schematics/angular               8.0.0-rc.1
@schematics/update                0.800.0-rc.1
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.30.0
</code></pre>

**Anything else relevant?**

**Comment by patrickmichalina** [comment] 2019-08-09 15:17
I am seeing this too on `9.0.0-next.1`

**Comment by alxhub** [comment] 2020-05-27 22:51
Hi @jonrimmer, @patrickmichalina.

You are correct that Ivy ignores the `enableResourceInlining` flag. This is by design, as resource inlining is no longer a concern with Ivy. To understand this, it's helpful to know why resource inlining was implemented in the first place.

In JIT mode, View Engine loads plain, TypeScript compiled code into the browser. There, the JIT compiler examines the metadata of each component, NgModule, etc, and generates an NgFactory on the fly for it. If this metadata includes a `templateUrl`, the View Engine JIT compiler will need to load it.

When View Engine ships libraries on NPM, it compiles them with plain TypeScript (no AOT NgFactory generation) and includes metadata.json files. These metadata files are only important for further AOT compilation - if used in JIT mode, only the JS files of the library will be loaded. Therefore, it's important that these JS files contain _all_ of the information required for the JIT compiler, including any template text. That's why resource inlining is performed - it inlines the resources for libraries prior to publication, so when they're used in JIT compilation the JIT compiler doesn't have to know how or where to find _library_ resources.

In Ivy, libraries are never compiled in the browser in JIT mode. They're shipped in View Engine compiled format (with resource inlining) to NPM, and after installation they're _always_ compiled into Ivy's AOT format compiled (today this is done by ngcc - eventually libraries will be published in a more complete compiled format). Therefore even for apps that are running in JIT mode, in the browser libraries will be AOT compiled already, and there's no need for resource loading.

What you see in the code is a `ɵsetClassMetadata` call, which preserves the _original_ class metadata for use in one very specific circumstance: when the class is loaded into the Ivy `TestBed` and the test overrides some of the class metadata. In that case, the metadata preserved by that function is used to "fill in the blanks" (since the override only contains specifies those fields that are changing). At this point, any resources listed in the metadata may need to be resolved, but at testing time this is often as simple as reading them from disk. Overriding metadata of components from libraries is not and never has been supported.

Nothing at runtime should be trying to resolve those resource URLs - the `ɵsetClassMetadata` call is removed by the optimizer during a production build (otherwise tree-shaking wouldn't work as the metadata contains references to lots of other classes, particularly for NgModules).

I hope this addresses your concern! I'm going to close this issue, but feel free to reach out if you have any questions.

**Closed by alxhub** 2020-05-27 22:51 UTC
Labels: comp: compiler, engine: ivy, triage #1, type: support
