### ISSUE TITLE
Infinite loop when using a getter ngModel 

### ISSUE THREAD

**Issue by sunbay** [angular/angular#24642] opened 2018-06-24 06:23 UTC
I'm using  a getter/setter variable as ngModel because I need a complex behaviour to work.

My code is :
```
public get value(){
    return []; //It's not work. 
}

<input [ngModel]="value" />
```

but because of that,  the app enters an infinite loop and a sharp increase in memory usage.

If I  the getter function return a simple value such of string, it will working.

```
public get value(){
    return 'value'; // If return a string , boolean , or a number, it will working.
}
```

If  the getter function return an array or object , it's will not working.

And, a  case as below, It still doesn't work:

```
public getValue(){
    return []; //It's not working. 
}
<input [ngModel]="getValue()" />
```

So, since a function can be used in ngModel, why  this function can not return an array?

**Comment by pkozlowski-opensource** [comment] 2018-06-24 07:18
Duplicate of #11097. You can work-around it by returning always the same _instance_ of the object.

**Closed by pkozlowski-opensource** 2018-06-24 07:18 UTC

**Comment by sunbay** [comment] 2018-06-24 08:46
@pkozlowski-opensource  Thanks, it's working

**Comment by raysuelzer** [comment] 2019-07-03 02:22
> Duplicate of #11097. You can work-around it by returning always the same _instance_ of the object.

Thanks, I had gotten very used to using new objects as a best practice so that Angular OnPush CD is triggered, good to know this does not work when dealing with ControlValueAccessors.
