### ISSUE TITLE
Unclear Error: RC 4 build error provides no information on error 

### ISSUE THREAD

**Issue by ganySA** [angular/angular#34118] opened 2019-11-28 04:29 UTC
Hi

When i compile in RC 4, i receive only the following as a build error:

```
ERROR in The ngcc compiler has changed since the last ngcc build.
Please remove "/Users/xxxx/Documents/node_modules" and try again.
```

My current packages are:

```
Angular CLI: 9.0.0-rc.4
Node: 12.13.1
OS: darwin x64

Angular: 9.0.0-rc.4
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, localize, material
... platform-browser, platform-browser-dynamic, router
... service-worker
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-rc.4
@angular-devkit/build-angular     0.900.0-rc.4
@angular-devkit/build-optimizer   0.900.0-rc.4
@angular-devkit/build-webpack     0.900.0-rc.4
@angular-devkit/core              9.0.0-rc.4
@angular-devkit/schematics        9.0.0-rc.4
@angular/flex-layout              8.0.0-beta.27
@angular/pwa                      0.900.0-rc.4
@ngtools/webpack                  9.0.0-rc.4
@schematics/angular               9.0.0-rc.4
@schematics/update                0.900.0-rc.4
rxjs                              6.5.3
typescript                        3.6.4
webpack                           4.41.2
```

**Comment by EmaGht** [comment] 2019-11-28 08:26
How is it unclear when it's literally telling you both the reason and the fix? :stuck_out_tongue_winking_eye::stuck_out_tongue_winking_eye:

**Comment by ganySA** [comment] 2019-11-28 12:00
Not as simple as you state. I removed the node folder, re-ran npm install && ng serve saw all the compilations to esm5 and bam the error comes out.

Can repeat the process and same error.

**Comment by ganySA** [comment] 2019-11-28 16:16
I actually worked out what was wrong here. It was looking at a node_modules folder outside of my project root. I was deleting the node_modules in my project root folder, ngcc was looking at one about 2 levels outside of my project - is that expected?

**Comment by NazimMertBilgi** [comment] 2019-11-28 19:54
> Not as simple as you state. I removed the node folder, re-ran npm install && ng serve saw all the compilations to esm5 and bam the error comes out.
> 
> Can repeat the process and same error.

I have that same problem. 9.0.0-rc.3 => 9.0.0-rc.4

```
Compiling angular-react-dates : module as esm5
Error: Error on worker #2: Error: Failed to compile entry-point angular-react-dates due to compilation errors:
node_modules/@angular/common/common.d.ts(115,22): error TS-996002: Appears in the NgModule.imports of AngularReactDatesModule, but could not be resolved to an NgModule class
```

**Comment by gkalpak** [comment] 2019-12-03 15:42
@NazimMertBilgi, this error is unrelated to the problem reported here. Please, open a new issue (providing all necessary details for us to understand and reproduce the problem).

**Comment by petebacondarwin** [comment] 2019-12-09 09:37
@ganySA - are you using some symlinking of your dependencies? Or is your project a monorepo with sub-libraries?

Normally when you see this error it is enough to remove the offending folder and run ngcc again...

**Comment by petebacondarwin** [comment] 2019-12-12 10:30
> ngcc was looking at one about 2 levels outside of my project - is that expected?

I would expect it to look in folders outside of your root if there was no package.json in your root folder (i.e. the first package.json was found outside your project; or if you had somehow symlinked these external node_modules into your project.

**Comment by petebacondarwin** [comment] 2020-01-09 14:41
Closing as it appears that this issue has been resolved and there has been no further feedback.

**Closed by petebacondarwin** 2020-01-09 14:41 UTC
Labels: comp: ngcc, freq2: medium, severity5: ivy-compat, state: Needs repro, type: bug/fix
