### ISSUE TITLE
Unable to fetch start URL via service worker.

### ISSUE THREAD

**Issue by postnikovpasha** [angular/angular#34461] opened 2019-12-18 05:42 UTC
The site has stopped seeing service worker.
Problems began after clicking on the "Clear Site Data" button.

The Application -> Manifest tab says "No matching service worker detected. You may need to reload the page".
"start_url" in manifest set.

Before clicking on this button, everything worked.
Already disconnected ng servie worker and reconnected - it did not help.
How to fix this problem?

**Comment by postnikovpasha** [comment] 2019-12-18 05:43
Audits:
![oSXGCYDsuzU](https://user-images.githubusercontent.com/34224626/71058933-06bac000-2194-11ea-95d0-af40ada84b6f.jpg)

**Comment by gkalpak** [comment] 2019-12-18 09:40
This is an application-specific question (i.e. something changed in the application recently that prevented the SW from being registered with the default `SwRegistrationStrategy`). Most probably a long-running task has been introduced that prevents the app from "stabilizing".

See [here][1] and [there][2] for more details.

##
Closing, since everything works as intended (afaict).

[1]: https://angular.io/api/service-worker/SwRegistrationOptions#registrationStrategy
[2]: https://angular.io/api/core/ApplicationRef#is-stable-examples

**Closed by gkalpak** 2019-12-18 09:40 UTC

**Comment by gkalpak** [comment] 2019-12-18 10:04
I have also created #34464 to track (and discuss) potential improvements to the default behavior.

**Comment by postnikovpasha** [comment] 2019-12-20 03:58
Thank you for help!
