### ISSUE TITLE
Website UI issue in Webpack documentation.

### ISSUE THREAD

**Issue by deepak1725** [angular/angular#18413] opened 2017-07-30 16:24 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[] Bug report  
[ ] Feature request
[x ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Website UI issue

## Expected behavior

UI should be smooth and hassle free

## Minimal reproduction of the problem with instructions

[Visit This ](https://angular.io/guide/webpack)
## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [x ] Chrome (desktop) version 59.0 Linux Arch 64
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX   NA
- Platform:  
Linux
Others:

</code></pre>

**Comment by gkalpak** [comment] 2017-07-31 08:22
Thx for reporting. This is a duplicate of #17912.

**Closed by gkalpak** 2017-07-31 08:22 UTC

**Comment by deepak1725** [comment] 2017-07-31 09:56
#17912 Reported 28 Days Ago!!! Damm!! and it still exists #open!!!  :-1:
