### ISSUE TITLE
HttpHeaders .toString() implementation

### ISSUE THREAD

**Issue by UnGaucho** [angular/angular#40904] opened 2021-02-18 14:25 UTC
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/common/http

### Description
HttpHeaders toString implementation.

We need to persist Angular requests when the app is offline and might be killed only to be restored later. We are providing a custom proxy HttpClient implementation with added capabilities.

Sadly HttpHeaders are not serializable directly and while this is implemented as part of our proxy implementation I don't see why this couldn't be implemented directly into the class just like HttpParams did with it's own .toString() other than bundle size or extra code to mantain.

As it is currently HttpHeaders constructor signature takes only strings and normalizes also XHR requests takes only k/v strings.

### Describe the solution you'd like
Add .toString (and optionally JSON.stringify) implementation to HttpHeaders.

### Describe alternatives you've considered
It's not a particularly hard problem and there's a myriad of ways of solving it from client code perspective.

**Comment by davudk** [comment] 2021-02-19 01:21
The following can be added to [headers.ts](https://github.com/angular/angular/blob/master/packages/common/http/src/headers.ts). Just wrote this now, haven't tested it..

```typescript
toString() {
  const headers = {};
  for (let lcName of this.headers.keys()) {
    const name = this.normalizedNames.get(lcName);
    headers[name] = this.headers.get(lcName);
  }
  return JSON.stringify(headers);
}
```

There's also the question of whether or not the `toString` function should return a JSON string or a Http headers string as they would appear in an actual http request/response. Although I can't imagine there being many use cases for the latter.

**Comment by petebacondarwin** [comment] 2021-02-19 08:11
So the difference here is that `HttpParams.toString()` is actually required by the library itself to do its work.
What you're proposing for `HttpHeaders` would only benefit a small (you are the first to request this?) number of application developers who wish to serialize requests, while adding to the bundle size (since it could not be tree-shaken) for all developers who use `@angular/common/http` even if they don't need it.

With that in mind, and since this is so easy to implement, I would argue against adding this to the library itself.

**Comment by UnGaucho** [comment] 2021-02-20 03:07
Thats a good point and pretty much the only counterargument that I can think of.

On the other hand by itself HttpHeaders are also bundled together with HttpModule even if never used from client code as you can pass a simple kv object. Also I'm inclined to believe, although I haven't checked, that not all HttpHeader methods are used internally and are there mostly for users convenience, just like .toString() would be.

Again I'd dont have a particular strong need for it to be included as it can be easily added to the prototype if needed. I just prefer if we didn't have nonserializable objects if they can be easily avoided.

Finally another pretty common usecase is request logging using an interceptor, there a toString() or toJson would be nice to have.

**Comment by petebacondarwin** [comment] 2021-02-20 13:08
> On the other hand by itself HttpHeaders are also bundled together with HttpModule even if never used from client code as you can pass a simple kv object. Also I'm inclined to believe, although I haven't checked, that not all HttpHeader methods are used internally and are there mostly for users convenience, just like .toString() would be.

This is a legacy downside of how the library was designed, but once we support a public API it is difficult to remove. Hence more reason not to add to our public API here.

**Comment by petebacondarwin** [comment] 2021-02-20 13:09
> Again I'd dont have a particular strong need for it to be included as it can be easily added to the prototype if needed. I just prefer if we didn't have nonserializable objects if they can be easily avoided.

One could create a small 3rd party library and publish it to npm, which monkey patches the `toString()` method as you suggest to share this functionality with others.

**Comment by petebacondarwin** [comment] 2021-06-30 13:10
Closing as it appears there is little community support for this feature.

**Closed by petebacondarwin** 2021-06-30 13:10 UTC
Labels: comp: common/http, feature, insufficient votes, votes required
