### ISSUE TITLE
TypeError: Cannot read property 'toJSON' of undefined

### ISSUE THREAD

**Issue by theodorejb** [angular/angular#14383] opened 2017-02-09 20:52 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
```

**Current behavior**
I get the following error when attempting to run the `ngc` ahead-of-time compiler in Angular 4.0.0-beta.7:

TypeError: Cannot read property 'toJSON' of undefined
    at TsickleCompilerHost.sourceMapGeneratorToConsumerWithFileName (node_modules\tsickle\build\src\tsickle_compiler_host.js:92:46)
    at TsickleCompilerHost.combineSourceMaps (node_modules\tsickle\build\src\tsickle_compiler_host.js:124:64)
    at TsickleCompilerHost.writeFile (node_modules\tsickle\build\src\tsickle_compiler_host.js:78:28)
    at Object.writeFile (node_modules\typescript\lib\typescript.js:62941:132)
    at Object.writeFile (node_modules\typescript\lib\typescript.js:8936:14)
    at printFile (node_modules\typescript\lib\typescript.js:60023:20)
    at emitFile (node_modules\typescript\lib\typescript.js:59979:21)
    at onSingleFileEmit (node_modules\typescript\lib\typescript.js:8844:13)
    at Object.forEachTransformedEmitFile (node_modules\typescript\lib\typescript.js:8821:21)
    at Object.emitFiles (node_modules\typescript\lib\typescript.js:59962:12)
Compilation failed

If I set `sourceMap` to false in my tsconfig.json file, the compilation works again.

**Expected behavior**
Compilation succeeds without having to disable sourcemaps.

**Minimal reproduction of the problem with instructions**
My full tsconfig.json is as follows:
```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "es2015",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": ["es2015", "dom"],
    "noImplicitAny": true
  },
  "files": [
    "app/app.module.ts",
    "app/main.ts"
  ],
  "angularCompilerOptions": {
    "genDir": "aot",
    "skipMetadataEmit" : true
  }
}
```

**Please tell us about your environment:**
Windows Server 2012 R2 (equivalent to Windows 8.1)

* **Angular version:** 4.0.0-beta.7

* **Language:** TypeScript 2.1.6

* **Node (for AoT issues):** `node --version` = v7.4.0

**Comment by mcgear** [comment] 2017-02-17 16:11
Same issue here, what is odd is that it worked the very first time i tried to compile with ngc.  And stopped working from there forward.

F:\Git\Domain\Titan\Fifty280.TitanJS>ng -v

                             _                           _  _
  __ _  _ __    __ _  _   _ | |  __ _  _ __         ___ | |(_)
 / _` || '_ \  / _` || | | || | / _` || '__|_____  / __|| || |
| (_| || | | || (_| || |_| || || (_| || |  |_____|| (__ | || |
 \__,_||_| |_| \__, | \__,_||_| \__,_||_|          \___||_||_|
               |___/
@angular/cli: 1.0.0-beta.31
node: 6.9.5
os: win32 x64
@angular/common: 4.0.0-beta.7
@angular/compiler: 4.0.0-beta.7
@angular/compiler-cli: 4.0.0-beta.7
@angular/core: 4.0.0-beta.7
@angular/flex-layout: 2.0.0-beta.5
@angular/forms: 4.0.0-beta.7
@angular/http: 4.0.0-beta.7
@angular/platform-browser: 4.0.0-beta.7
@angular/material: 2.0.0-beta.2
@angular/platform-browser-dynamic: 4.0.0-beta.7
@angular/platform-server: 4.0.0-beta.7
@angular/router: 4.0.0-beta.7

{
	"compilerOptions": {
		"target": "es5",
		"module": "es2015",
		"moduleResolution": "node",
		"sourceMap": true,
		"emitDecoratorMetadata": true,
		"experimentalDecorators": true,
		"lib": [ "es2015", "dom" ],
		"noImplicitAny": true,
		"suppressImplicitAnyIndexErrors": true,
		"declaration": true,
		"outDir": "dist/js/titan"
	},
	"files": [
		"index.ts"
	],
	"exclude": [
		"**/*.spec.*",
		"node_modules",
		"dist"
	],
	"angularCompilerOptions": {
		"genDir": "dist/aot/titan",
		"skipMetadataEmit": true
		//"debug": true
	}
}

**Comment by DzmitryShylovich** [comment] 2017-02-18 08:23
@theodorejb can you provide a github repo, we can clone, that reproduces the issue?

**Comment by gund** [comment] 2017-02-18 10:34
@DzmitryShylovich you can have a look [here](https://github.com/gund/ng-http-interceptor/tree/beta-ng-7). Just clone, `npm install` and when `npm run build` will run it will break with the error described above.

Thanks

**Comment by theodorejb** [comment] 2017-02-19 02:11
This issue is still happening for me in 4.0.0-beta.8

**Comment by ocombe** [comment] 2017-02-21 12:16
I've got the same issue when trying to build the angular project by the way

**Comment by blacksonic** [comment] 2017-02-22 18:59
Updated also, here is a [Hello World app](https://github.com/blacksonic/angular2-aot-webpack/tree/v4) that fails.

**Comment by blacksonic** [comment] 2017-02-25 11:17
Still exists with rc.1

**Comment by blacksonic** [comment] 2017-02-25 12:33
@tbosch @IgorMinar

**Comment by day01** [comment] 2017-02-25 19:57
@blacksonic

I think it is important to add information about the bug:)
So, the bug is only if we set sourceMap = true and mapRoot = "" <- empty in tsconfig

**Comment by pderks** [comment] 2017-03-16 21:13
I'm seeing the same issue @day01 is seeing in rc.3.  To successfully run the ngc (aot compiler) I have to set sourceMap to false and take mapRoot out of the tsconfig.json file.

**Comment by pderks** [comment] 2017-03-16 21:17
Here is my tsconfig.json file for reference before setting sourceMap to false and pulling out mapRoot:

{
  "compilerOptions": {
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": ["es6", "dom"],
    "mapRoot": "./",
    "module": "es6",
    "moduleResolution": "node",
    "outDir": "../dist/out-tsc",
    "sourceMap": true,
    "target": "es5",
    "typeRoots": [
      "../node_modules/@types"
    ]
  },
  "files": [
    "./app/app.module.ts",
    "./main.ts"
  ],

  "angularCompilerOptions": {
   "genDir": "aot",
   "entryModule": "app/app.module#AppModule",
   "skipMetadataEmit" : true
 }
}

**Comment by DzmitryShylovich** [comment] 2017-03-16 21:17
@chuckjaz doesn't https://github.com/angular/angular/pull/15187 fix this?

**Comment by theodorejb** [comment] 2017-03-16 21:37
FWIW I'm not getting this error anymore in recent RCs.

**Comment by DzmitryShylovich** [comment] 2017-03-25 22:50
@theodorejb could you please verify that it works with ng4 GA and close this issue?

**Closed** 2017-03-26 02:40 UTC

**Comment by mdudek** [comment] 2017-03-26 15:21
@theodorejb, I'm facing same issue as @pderks right now with ng4 final.

**Comment by pderks** [comment] 2017-03-27 17:05
@DzmitryShylovich I'm still seeing this issue with the release of version 4.0.0 and it looks like @mdudek is as well. When I have sourceMaps set to true and mapRoot defined as "./" this is the error I am seeing:

TypeError: Cannot read property 'toJSON' of undefined
    at Object.sourceMapGeneratorToConsumer (C:\.....\node_modules\tsickle\build\src\source_map_utils.js:65:42)
    at TsickleCompilerHost.combineSourceMaps (C:\.....\node_modules\tsickle\build\src\tsickle_compiler_host.js:167:74)
    at TsickleCompilerHost.writeFile (C:\.....\node_modules\tsickle\build\src\tsickle_compiler_host.js:111:28)
    at Object.writeFile (C:\.....\node_modules\typescript\lib\typescript.js:64240:132)
    at Object.writeFile (C:\.....\node_modules\typescript\lib\typescript.js:9020:14)
    at printSourceFileOrBundle (C:\.....\node_modules\typescript\lib\typescript.js:61197:20)
    at emitSourceFileOrBundle (C:\.....\node_modules\typescript\lib\typescript.js:61155:21)
    at Object.forEachEmittedFile (C:\.....\node_modules\typescript\lib\typescript.js:8986:17)
    at Object.emitFiles (C:\.....\node_modules\typescript\lib\typescript.js:61137:12)
    at emitWorker (C:\.....\node_modules\typescript\lib\typescript.js:64294:33)

**Comment by DzmitryShylovich** [comment] 2017-03-27 17:16
@pderks open a new issue

**Comment by BerndWessels** [comment] 2017-06-07 20:02
I'm having the same issue, `"sourceMap": true` will cause the error.

Are there any known workarounds for this?

**Comment by day01** [comment] 2017-06-08 03:59
@BerndWessels 
https://github.com/angular/angular/issues/14383#issuecomment-282508274

**Comment by yedidisatya** [comment] 2018-02-09 06:47
Hi, @all  I am facing the same issue(Uncaught TypeError: Cannot read property 'toJSON' of undefined ). it not coming every time but sometimes it's coming. In that estivation also I have everything to get the ( data(this.collection.get(CreativeId).toJSON();)  ). Can you please give any other scenario to get the 'toJSON 'issue
