### ISSUE TITLE
Uncaught SyntaxError: Unexpected token '<'  error after redirect to Angular PWA site after every new deployment

### ISSUE THREAD

**Issue by Raza27630** [angular/angular#35077] opened 2020-01-31 09:37 UTC
# 🐞 bug report
@angular/pwa

### Description
After every new deployment on production environment, we are facing Unexpected token error after being redirected from Authentication server

## 🔬 Minimal Reproduction (Error Screenshot)

![image](https://user-images.githubusercontent.com/56454429/73528622-85528080-4415-11ea-82c7-95ae8d2850ef.png)

## 🔥 Exception or Error
<pre><code>
Uncaught SyntaxError: Unexpected token '<'
</code></pre>

## 🌍  Your Environment
Angular v8
Browser: Chrome: Version 73.0.3683.103 (Offizieller Build) (64-Bit)

**Comment by gkalpak** [comment] 2020-01-31 11:25
It sounds like the browser is trying to request scripts that do not exist and the server is configured to return 404 HTML page with a 200 status (so the browser tries to parse the HTML as JS).

Are the non-existent JS files from the new deployment or the old deployment?

**Comment by spock123** [comment] 2020-01-31 11:47
Yeah I'm willing to bet it's parsing a non existing file.. had this a million times

**Comment by Raza27630** [comment] 2020-01-31 12:27
> It sounds like the browser is trying to request scripts that do not exist and the server is configured to return 404 HTML page with a 200 status (so the browser tries to parse the HTML as JS).
> 
> Are the non-existent JS files from the new deployment or the old deployment?

It is from old deployment which does not exist any more.

**Comment by Raza27630** [comment] 2020-01-31 12:34
> Yeah I'm willing to bet it's parsing a non existing file.. had this a million times

Agree. It is happening because service worker has still cached index.html which is referencing to old js files.
How to update service worker cache before application goes into initialization mode

**Comment by gkalpak** [comment] 2020-02-01 11:50
Theoretically that can't happen (i.e. the SW keeps `index.html` and the associated JS files in the same cache). If it is serving the client one version of `index.html` from the cache, there is no reason it can't serve the corresponding JS files (from the same cache).

There have been some reports of this, but we haven't been able to reproduce it reliably and find the root cause 😞

@Raza27630, what OS(es) and browser versions does this happen on? What version of Angular are you using?
Also, if you are able to reproduce it reliably we could instrument the SW to gain more insight on the series of events that lead to this.

**Comment by Raza27630** [comment] 2020-02-03 08:18
> Theoretically that can't happen (i.e. the SW keeps `index.html` and the associated JS files in the same cache). If it is serving the client one version of `index.html` from the cache, there is no reason it can't serve the corresponding JS files (from the same cache).
> 
> There have been some reports of this, but we haven't been able to reproduce it reliably and find the root cause 😞
> 
> @Raza27630, what OS(es) and browser versions does this happen on? What version of Angular are you using?
> Also, if you are able to reproduce it reliably we could instrument the SW to gain more insight on the series of events that lead to this.

Steps which we are following for prod deployment and to reproduce the bug-

1. deleting old artifacts before every release and copying new artifacts.
2. clicking on application link (for example -- open application by clicking link in ms word document)
3. Application will try to fetch access token from auth server and redirect it back to application
4. After redirection from auth server, it fails to load application where it says unexpected token error

**Infra: OS - Windows 10, Browser : Chrome (v78.0.3904.70 (32 bit)) , Angular version : v8.X.X , "@angular/pwa": "0.11.4",**

**Comment by gkalpak** [comment] 2020-02-04 08:31
Unfortunately, this info ins not enough to reproduce or further investigate the issue. In any case, I believe this has the same root cause as #28114, so let's track the problem there.

BTW, there was a fix in `@angular/service-worker@8.2.14` that might have addressed the issue (see https://github.com/angular/angular/issues/28114#issuecomment-558810631). Make sure your `@angular/service` is at least at that version.

##
Closing as duplicate of #28114.

**Comment by Raza27630** [comment] 2020-02-10 16:05
> Unfortunately, this info ins not enough to reproduce or further investigate the issue. In any case, I believe this has the same root cause as #28114, so let's track the problem there.
> 
> BTW, there was a fix in `@angular/service-worker@8.2.14` that might have addressed the issue (see [#28114 (comment)](https://github.com/angular/angular/issues/28114#issuecomment-558810631)). Make sure your `@angular/service` is at least at that version.
> 
> Closing as duplicate of #28114.

Situation is getting worse :( 
We are now getting chunk loading failed issue after deployment. As you suggested we using @angular/service-worker@8.2.14.
Please let me know if you need more information from me. 

![image](https://user-images.githubusercontent.com/56454429/74166673-439cb380-4c27-11ea-8d21-2f8e324cd551.png)

**Comment by gkalpak** [comment] 2020-02-11 19:37
OOC, does this happen when both the old and the new version of the app use `@angular/service-worker@8.2.14` or newer?

**Comment by HegdeSach** [comment] 2020-04-24 08:34
@gkalpak @Raza27630 Any solution?

**Comment by Raza27630** [comment] 2020-05-08 07:55
> OOC, does this happen when both the old and the new version of the app use `@angular/service-worker@8.2.14` or newer?

In both old and new version of service worker.

**Comment by Raza27630** [comment] 2020-05-08 07:56
> @gkalpak @Raza27630 Any solution?

Not yet. We are still clearing the cache manually.

**Comment by gkalpak** [comment] 2020-05-26 17:40
Closing as a duplicate of #28114 (per https://github.com/angular/angular/issues/35077#issuecomment-581796967).
There is WIP PR that will address #28114: #36847

**Closed by gkalpak** 2020-05-26 17:40 UTC
Labels: comp: service-worker
