### ISSUE TITLE
Document that ngc in  5.0.0-rc.2 places generated files for node_modules into `outDir`

### ISSUE THREAD

**Issue by IlyaSurmay** [angular/angular#19760] opened 2017-10-17 12:03 UTC
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
`ngc` places files in the wrong directory (`outDir` from `tsconfig.json` plus the name of the directory where I run `ngc` from (`.tmp` in my case). So all compiled files are placed in `dist/.tmp`. Running the same command with the same files and tsconfig using angular 4.4.5 works as expected - all files are placed in `dist`

Reproduction - https://github.com/IlyaSurmay/ngc-reproduction

## Expected behavior
`ngc` places compiled files in `outDir`.

## Environment

<pre><code>
Angular version: 5.0.0-rc.2

 
For Tooling issues:
- Node version: 8.2.1
- Platform:  Linux
</code></pre>

**Comment by alexzuza** [comment] 2017-10-17 12:23
It would be great if you provided reproduction of this issue

**Comment by IlyaSurmay** [comment] 2017-10-17 12:58
@alexzuza I created a small repo with reproduction. This is the kind of issue that can't be reproduced via plunkr or stackblitz :(

**Comment by tbosch** [comment] 2017-10-17 17:59
This is probably a duplicate of https://github.com/angular/angular/issues/19718.

**Comment by tbosch** [comment] 2017-10-17 23:27
Hello,
I couldn't reproduce this bug. I ran your example, which says:
```
...
go to src folder and run ../node_modules/.bin/ngc -p tsconfig.app.json
```

If I do this, all files end up correctly in the `dist` folder. There is a difference though:
ngc creates `dist/src` and `dist/node_modules`. This is an expected change in Angular 5, i.e. it won't generate the factories for `node_modules` inplace but rather also put them into `outDir`.

**Comment by IlyaSurmay** [comment] 2017-10-18 08:36
@tbosch Hi, thanks for your reply!

> ngc creates dist/src and dist/node_modules

That's what I'm talking about. Is there a way to make `ngc` work as it does in ng v4?

**Comment by tbosch** [comment] 2017-10-18 16:18
You can either set `rootDir` to `src`, which would not generate any files for things in `node_modules` (e.g. @angular/material), or set `outDir` to `.`, which would emit all files in place, both, the ones for `src` and the ones for `node_modules`.

The behavior of emitting generated files for `node_modules` always inplace, even if you specified an `outDir` was a bug in v4.

**Comment by tbosch** [comment] 2017-10-18 16:18
Closing as works as expected.

**Comment by tbosch** [comment] 2017-10-18 16:19
Actually, reopening to track to document this.

**Comment by jenniferfell** [comment] 2018-05-10 22:52
docsarea=filestructure

**Comment by jenniferfell** [comment] 2018-05-10 22:57
@brandonroberts : Hi. Would you do me a favor and re-check the triage on this? I don't find any doc that is wrong, so I changed to a feature request to add doc on the output from ngc. Please confirm or clarify. Thanks. 

@tbosch : Hi. Sorry this sat for so long. Doing some housekeeping now.

**Comment by JoostK** [comment] 2021-05-14 13:19
Closing as obsolete with the output produced by the Ivy compiler.

**Closed by JoostK** 2021-05-14 13:19 UTC
Labels: P4, comp: compiler, comp: docs, engine: ve, feature, freq2: medium, subtype: docs-completeness
