### ISSUE TITLE
Cannot build application with nested lazy-loaded module in library.

### ISSUE THREAD

**Issue by redplane** [angular/angular#32764] opened 2019-09-19 02:42 UTC
Hi,

I'm using angular to create an **ui library**.
In workspace, there is one project for **main app**, one project for **ui library**.

In the library which declares modules and routings, I have this code:

**parent-routing.module.ts**:
```
import {NgModule} from '@angular/core';
import {RouterModule, Routes} from '@angular/router';
import {ParentComponent} from './parent.component';

const routes: Routes = [
  {
    path: '',
    component: ParentComponent,
    children: [
      {
        path: '',
        loadChildren: '/child/child.module#ChildModule'
      }
    ]
  }
];

@NgModule({
  imports: [
    RouterModule.forChild(routes)
  ],
  exports: [
    RouterModule
  ]
})
export class ParentRoutingModule {
}

```

In **app.module.ts**, I declare the **ParentModule** as below:

```
const routes: Routes = [
  {
    path: '',
    loadChildren: () => import('ui-lib').then(m => m.ParentModule)
  }
];

@NgModule({
  imports: [RouterModule.forRoot(routes)],
  exports: [RouterModule]
})
export class AppRoutingModule { }

```

When I tried compiling my app, the console throws me an error:

**ERROR in ./src/app/app-routing.module.ts
Module not found: Error: Can't resolve './../../../../dist/ui-lib/modules/parent/parent.module.d.ngfactory' in '/Users/linhnguyen/nested-module-playground/projects/main-app/src/app'**

After searching on Google, I found [this comment](https://github.com/angular/angular-cli/issues/6373#issuecomment-453006158). The commenter mentioned about creating a module and import every component to the route. That can resolve the issue of loading module in library, but it is not lazy loaded.

Here is [my workspace on stackblitz](https://stackblitz.com/github/alakanzam/ui-lib-playground)

Does anyone have any solutions please ?

Thanks,

**Comment by trotyl** [comment] 2019-09-19 04:27
Duplicate of https://github.com/angular/angular-cli/issues/6373

**Comment by redplane** [comment] 2019-09-19 06:21
It has been locked without a proper solution for nested module. The last comment was about flattening component in nested modules.

**Comment by alan-agius4** [comment] 2019-09-19 15:57
Hi @redplane, libraries should not have route declarations. Routing and lazy loading is meant not be used at application level.

https://github.com/angular/angular/issues/31893#issuecomment-516615243

**Closed** 2019-09-19 15:59 UTC
