### ISSUE TITLE
Angular DevTools not available - Firefox Developer Edition

### ISSUE THREAD

**Issue by levinbaenninger** [angular/angular#55135] opened 2024-03-30 09:55 UTC
### Is this a bug report or a feature request?

- [X] Bug Report
- [ ] Feature Request

### Please provide the steps to reproduce the issue [Bug Report only]

When I follow the link to install the Angular DevTools on [https://angular.dev/tools/devtools](https://angular.dev/tools/devtools). I get redirected correctly ([https://addons.mozilla.org/en-GB/firefox/addon/angular-devtools/](https://addons.mozilla.org/en-GB/firefox/addon/angular-devtools/)) but it can't find the extension or rather it doesn't exist. 

I'm using Firefox Developer Edition version 125.0b6 on a Windows 11 machine and I'm from Switzerland (I don't know if it's a region problem). When I search for the extension the normal way I don't get a result.

### Please provide the expected behavior vs the actual behavior you encountered [Bug Report only]

I want to be able to download the Angular DevTools extension but the Firefox Add-On marketplace doesn't recognize this link/extension.

### Please provide a screenshot if possible [Bug Report only]

![screenshot](https://github.com/angular/angular/assets/56092329/a54b95c7-bd1c-486c-b721-2a31582639c0)
![screenshot2](https://github.com/angular/angular/assets/56092329/1206ef36-b182-4c6c-ab1e-799eb2a36df4)

### Please provide the exception or error you saw [Bug Report only]

See screenshots above.

### Is this a browser-specific issue? If so, please specify the device, browser, and version. [Bug Report only]

Yes, I can download the extension on Google Chrome version 123.0.6312.86 without a problem. I use Firefox Developer Edition version 125.0b6 on a Windows 11 machine version 23H2.

**Comment by wali-valeo** [comment] 2024-03-30 12:20
I have the same problem, I was going to open the issue just now

**Comment by COLAMAroro** [comment] 2024-04-10 20:00
As a workaround, maybe someone could publish the .zip file containing the extension, allowing it to be installed manually ?

**Comment by Poya-Faraji** [comment] 2024-04-11 10:23
I had this installed on my Firefox and it was working fine unfortunately I deleted it now and I need it badly since I use Firefox as my main testing and development ground. Any updates that when can it be available again ?
Maybe I should try using "https://github.com/bnpoirier/foxify" 😕.

**Comment by danielalexis** [comment] 2024-04-12 09:53
Any updates on this matter?

**Comment by novikov1337danil** [comment] 2024-04-18 18:39
We are looking forward to any news

**Comment by dgp1130** [comment] 2024-04-22 21:21
The add-on is still in review. One reason this has taken so long is that I misread the Add-On store UI and _thought_ I had resubmitted the extension for re-review, but actually had not. I did another release when I discovered this and only just today was that review rejected with boilerplate language "Source code or instructions missing". I'm pretty sure I uploaded the source code correctly and the README includes instructions to build, so I'm not clear on what went wrong there. I've reached out for more info and will follow up with whatever we need to do to get this published.

Unfortunately I don't have any more insight into a timeline for a fix here. We just need to continue to push through with the review process.

**Comment by JoshuaTapp** [comment] 2024-04-30 16:10
@dgp1130 Any update on this yet?

**Comment by ttimot24** [comment] 2024-05-02 11:15
Any update?

**Comment by Ocholla-T** [comment] 2024-05-08 13:35
@dgp1130 Any update?

**Comment by dgp1130** [comment] 2024-05-10 15:45
Angular DevTools is back on the Firefox Add-on Store! Please give it a shot and less us know if you encounter any issues with it.

https://addons.mozilla.org/en-GB/firefox/addon/angular-devtools/

Apologies for the delay on getting this back up, there was a lot of back and forth to try to get the build to reproduce correctly so Mozilla could review the extension. In the mean time, we've landed a number of small improvements to our build process and documentation which should hopefully make an extended outage like this significantly less likely in the future.

**Closed by dgp1130** 2024-05-10 15:45 UTC
Labels: area: devtools

**Comment by JoshuaTapp** [comment] 2024-05-10 17:39
Thank you @dgp1130 !!!
