### ISSUE TITLE
Breaking change in Ivy data binding!

### ISSUE THREAD

**Issue by bernatgy** [angular/angular#39044] opened 2020-09-29 13:48 UTC
# 🐞 bug report

### Affected Package
**Ivy** - *I'm not familiar with the exact package / packages.*

### Is this a regression?

Could not answer. We went from Angular `7.2.9` to `9.1.12` over a few days, and we used the default "staticness" of our `@ViewChild` queries before. Through the updates we had to switch some queries over to `{ static: true }` because errors arose.

### Description
As you know, there are multiple ways to bind to a string Input property. I'll mention two of them;

a.) `someProperty="Some static string..."`
&nbsp;&nbsp;&nbsp;&nbsp;Which will only bind once.
b.) `[someProperty]="'Some string...'"`
&nbsp;&nbsp;&nbsp;&nbsp;Which will participate in change detection as usual, and the string can change.

Without Ivy, these two ways pretty much perform the same. Note: We are talking about non-changing (at least through template binding) string values.

We have multiple systems in which we may override these provided strings in code, hence why we use the first type of binding (a). These systems seem to silently fail with Ivy on. After lots of debugging I figured that Ivy handles something differently. I'm pretty sure that the issue seems to arise from the combination of static resolution, binding type (a), and the override's timing, however these issues are incredibly hard to detect, and would even require complete redesigns of some of our systems.

In my attached [StackBlitz](https://stackblitz.com/edit/angular-huf3xf?devtoolsheight=33&file=src/app/app.component.ts), I've prepared;
1. an example with binding type (a) which seems to have preserved it's inner workings
2. an example with binding type (b) which completely flips on it's head when Ivy is turned on (uncheck / check Enable Ivy, under Settings)
3. a possible workaround (???) which seems so bad... (I'd be interested in opinions on this)

## 🔬 Minimal Reproduction
[StackBlitz, second example, turn Ivy on / off](https://stackblitz.com/edit/angular-huf3xf?devtoolsheight=33&file=src/app/app.component.ts)

## 🔥 Exception or Error
None

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.1.12
Node: 12.18.3
OS: win32 x64

Angular: 9.1.12
... animations, cli, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router
Ivy Workspace: <error>

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.12
@angular-devkit/build-angular     0.901.12
@angular-devkit/build-optimizer   0.901.12
@angular-devkit/build-webpack     0.901.12
@angular-devkit/core              9.1.12
@angular-devkit/schematics        9.1.12
@ngtools/webpack                  9.1.12
@schematics/angular               9.1.12
@schematics/update                0.901.12
rxjs                              6.6.3
typescript                        3.8.3
webpack                           4.42.0
</code></pre>

**Anything else relevant?**
Tested on Google Chrome 85.0.4183.121 (Official Build) (64-bit)
Production mode seems not to influence it.

I realize what we're doing is not recommended, and that the example may not make much sense to you. But I firmly think it should be supported, and that the difference of behaviour should at least be documented (if it's not a bug). Furthermore, the cases in which we do this predominantly make sense, I just can't share much more.

**Comment by JoostK** [comment] 2020-09-29 14:04
This looks to be the same as #34227.

**Comment by bernatgy** [comment] 2020-09-29 14:10
@JoostK It is! I apologize, I tried to search for it, it's just soo confusing. That's why my title is like this. Couldn't fit it into a sentence.

Please mark as duplicate.

PS: The issue is still very much urgent, and breaks lots of things for us as well.

**Comment by AndrewKushnir** [comment] 2020-09-30 02:59
Closing this ticket as a duplicate of #34227.

**Closed by AndrewKushnir** 2020-09-30 02:59 UTC
