### ISSUE TITLE
Provider.useValue appears to clone the supplied value

### ISSUE THREAD

**Issue by wardbell** [angular/angular#10788] opened 2016-08-14 03:24 UTC
**I'm submitting a ...**  (check one with "x")

```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request 
```

I first detected in this testing issue #10787 which describes the unexpected cloning behavior.

@filipesilva reproduced in the plunker below for regular `@Component.providers`

The cloning behavior is **not** documented in the API that I can see:

https://angular.io/docs/ts/latest/api/core/index/Provider-class.html

**Reproduction of the problem**

http://plnkr.co/edit/mD1CCUw0Jff0veA7CwFj?p=preview

**What is the expected behavior?**

Expect to inject the `useValue` value, not a clone.
- **Angular version:** 2.0.0-rc.5
- **Browser:** [all ] 
- **Language:** [all ]

**Comment by filipesilva** [comment] 2016-08-14 03:34
Can confirm it is not a plunker only issue. By cloning https://github.com/angular/quickstart locally and replacing `app.component.ts` with the plunker one, I was able to reproduce as well.

**Comment by petebacondarwin** [comment] 2016-09-24 06:29
Still a problem with 2.0.0: http://plnkr.co/edit/cn5W1fIbWRCTlSMvtMib?p=preview

**Comment by manklu** [comment] 2016-09-24 08:10
If you are using a factory, it works as expected

```javascript
  providers: [{
    provide: UserService,
    useFactory: () => {
      return fakeUserService;
    },
  }]
```

**Comment by manklu** [comment] 2016-09-24 08:42
Yes, the compiler makes some sort of deep copy.

```javascript
_View_AppComponent_Host0.prototype.createInternal = function(rootSelector) {
  var self = this;
  self._el_0 = self.selectOrCreateHostElement('my-app',rootSelector,self.debug(0,0,0));
  self._appEl_0 = new jit_AppElement6(0,null,self,self._el_0);
  var compView_0 = jit_viewFactory_AppComponent7(self.viewUtils,self.injector(0),self._appEl_0);
  self._UserService_0_4 = {
    isLoggedIn: true,
    user: {name: 'Test User'}
  }
```

**Comment by joshuacc** [comment] 2017-01-04 20:14
I just ran into this problem in unit testing. It took me quite a while to realize that Angular's `useValue` was not actually using the value I provided. Switching to `useFactory` works, but isn't intuitive.

**Comment by tbosch** [comment] 2017-05-10 21:13
Internal note: Once we downlevel decorators in a tsc transform, we can fix this.

**Comment by FLGMwt** [comment] 2017-07-11 11:30
@tbosch Hi there! Thanks for the response. Since your comment was the closest I've seen that explains why the cloning might occur, would you mind explaining the decorator thing a bit more? I'm trying to write a general testing utility for stubs and I'd like to know why the clone happens/is necessary

**Comment by jnizet** [comment] 2017-12-14 20:31
@tbosch isn't the bug fixable since 5.0?

**Comment by rbingham** [comment] 2018-08-02 23:25
This is still an issue in angular 5.

**Comment by FLGMwt** [comment] 2018-08-02 23:51
This has been a major pain point for me trying to teach ng unit testing in the simplest terms possible to some people more accustomed to .NET mocking patterns.

If anyone is able to provide a little context, I'd be happy to spend some time investigating and diving into a fix.

**Comment by dblVs** [comment] 2019-08-13 10:32
@petebacondarwin that should probably get changed rather than documented, right ?

**Comment by alxhub** [comment] 2020-01-23 22:08
Good news everyone! This is finally fixed in Ivy :) closing this as "won't fix" (on the view engine side) and "fixed" (on the Ivy side).

**Closed by alxhub** 2020-01-23 22:08 UTC
Labels: comp: core, comp: docs/api, docsarea: DI, fixed by Ivy, freq1: low, severity2: inconvenient, subtype: docs-completeness, type: bug/fix
