### ISSUE TITLE
Component Convention over Configuration 

### ISSUE THREAD

**Issue by strawlion** [angular/angular#6332] opened 2016-01-07 21:31 UTC
Angular 2 is a great piece of software, but its biggest problem is that it's overly verbose. Has implicitly requesting a component's sibling template/css been discussed?

component
    - component.js
    - component.html
    - component.css

I know it's less explicit, but it would encourage a standard pattern for organizing components. I think you're going to lose a lot of people with the verbosity as is. Unless we're going to go full hog and start writing CSS directly in our components, using an inline template string is an awful anti-pattern IMO.

**Comment by pkozlowski-opensource** [comment] 2016-08-05 16:50
Duplicate of #5183 and #10371

**Closed by pkozlowski-opensource** 2016-08-05 16:50 UTC
