### ISSUE TITLE
Calling markAsTouched on a FormGroup doesn't affect children controls

### ISSUE THREAD

**Issue by jabas06** [angular/angular#12281] opened 2016-10-13 19:09 UTC
**I'm submitting a bug report.

**Current behavior**
Calling markAsTouched on a FormGroup doesn't mark their children controls as touched.

**Expected behavior**
Calling markAsTouched on a FormGroup should set the touched flag of  their children controls. Actually, the opposite method, markAsUntouched, is affecting the children controls.

Why markAsTouched doesn't work the same way?

**Minimal reproduction of the problem with instructions**
Repro:
http://plnkr.co/edit/CgjaYHgfzdEqCyTCud8N?p=preview

**What is the motivation / use case for changing the behavior?**
I have some styles that rely on the touched state. In some cases and need to set manually the touched state for all the controls, for example, after the user clicks on the save button.

* **Angular version:**
2.1

**Comment by pkozlowski-opensource** [comment] 2016-10-13 19:11
This is duplicate of #11774, see the detailed discussion in the referenced issue.

**Closed by pkozlowski-opensource** 2016-10-13 19:11 UTC

**Comment by DzmitryShylovich** [comment] 2016-10-13 19:12
Works as intended https://github.com/angular/angular/blob/master/modules/%40angular/forms/src/model.ts#L244

**Comment by touqeershafi** [comment] 2017-04-26 08:26
I've got the same problem in angular4x `markAsTouched()` is not working!

```HTML
<form #addFieldForm="ngForm">
```


```Typescript
@ViewChild('addFieldForm') addFieldForm: NgForm;
```

```
if (!this.addFieldForm.valid) {

      //this.addFieldForm.form.markAsTouched(); <--- This not working
      this.addFieldForm.controls['name'].markAsTouched(true); // Manually triggers work for each control
      this.addFieldForm.controls['dataType'].markAsTouched(true); // Manually triggers work for each control
      return false
    }
```

**Comment by Khalav** [comment] 2017-05-26 14:39
This does not work either.

```
ngOnInit() {
    let controls = this.myForm.controls;

    _.forEach(controls, control => {
        control.markAsTouched(true);
        control.markAsDirty(true);
    });
}
```

**Comment by AlexzundeR** [comment] 2017-05-31 10:37
This works in Angular2:
` for (let inner in this.form.controls) {
            this.form.get(inner).markAsTouched();
            this.form.get(inner).updateValueAndValidity();
        }`

This solution can be expanded to process full form's tree by recursion.

**Comment by Khalav** [comment] 2017-05-31 10:52
Trying to use your code  @AlexzundeR throws me the following error: 
`Property 'get' does not exist on type 'NgForm'.`

My form var is declared this way:

`@ViewChild('f') myForm: NgForm;`

```
ngOnInit() {
    for (let inner in this.myForm.controls) {
        this.myForm.get(inner).markAsTouched();
        this.myForm.get(inner).updateValueAndValidity();
    }
}
```

**Comment by AlexzundeR** [comment] 2017-05-31 16:44
@Khalav , I'm sorry, I have not declared that form in this contex is a FormGroup object from Reactive forms.

**Comment by Ismaestro** [comment] 2018-10-09 14:53
I don't want to make recursion :(( 
I want a method for this!!
Or maybe an extra parameter that affects children as well...
```
control.markAsTouched({propagateChildren: true})
```

**Comment by Ismaestro** [comment] 2018-10-09 15:13
Okey, 
```
export const markFormGroupTouched = (formGroup) => {
  (<any>Object).values(formGroup.controls).forEach(control => {
    control.markAsTouched();

    if (control.controls) {
      markFormGroupTouched(control);
    }
  });
};
```

**Comment by zelwyn** [comment] 2019-03-08 23:12
> This works in Angular2:
> 
> ```ts
>  for (let inner in this.form.controls) {
>             this.form.get(inner).markAsTouched();
>             this.form.get(inner).updateValueAndValidity();
>         }
> ```
> 
> This solution can be expanded to process full form's tree by recursion.

Works, ty

**Comment by cristianmartinez** [comment] 2019-05-30 18:55
I know this is an old issue, but i just want to let you know angular 8 now brings to us additional modules for descendants controls. 

https://angular.io/api/forms/AbstractControl#markAllAsTouched
