### ISSUE TITLE
angular/ngUpgrade/tests No provider for $injector!

### ISSUE THREAD

**Issue by Organizzzm** [angular/angular#20448] opened 2017-11-15 12:57 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Terminal is dropping error: TNullInjectorError: No provider for $injector!

## Expected behavior
Tests went without errors

## Minimal reproduction of the problem with instructions
I am upgraded my app from angular 1.* to angular 5. I Did injects angular 1.* services like into documentation. Through the $injector. 
For example: 
To providers
{
            provide: 'name',
            useFactory: ($injector: any) => $injector.get('name'),
            deps: ['$injector']
 }
Inject to class
@Inject('name') name

App works well but tests is dropping error

## What is the motivation / use case for changing the behavior?
To use angular1 services within an angular2 context while gradually moving towards an angular2 application. With tests.

## Environment

<pre><code>
Angular version: 5.0.1

Browser:
- [x] Chrome (desktop) version 62.0.3202.62 (Official Build) (64-bit)
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 6.11.4  
- Platform:  Mac

Others:
OS Sierra, Webstorm 2017.2.4, yarn 1.2.1, webpack-dev-server 2.4.5

</code></pre>

**Comment by gkalpak** [comment] 2017-11-15 13:39
Sounds like a usage error. Can you show the failing test (or ideally put a minimal reproduction on a repo we can clone and investigate)?

**Comment by Organizzzm** [comment] 2017-11-15 20:41
Ok. I show you minimal reproduction on a repo but a little bit later

**Comment by gkalpak** [comment] 2017-12-15 12:38
I am going to close this for now, since it is not actionable in its current state. Happy to re-open and investigate if/when you can provide a minimal reproduction, @Organizzzm.

**Closed by gkalpak** 2017-12-15 12:38 UTC
Labels: comp: upgrade/static
