### ISSUE TITLE
Detached elements stay in memory when animated

### ISSUE THREAD

**Issue by waterplea** [angular/angular#50533] opened 2023-05-31 15:16 UTC
### Which @angular/* package(s) are the source of the bug?

animations

### Is this a regression?

No

### Description

If you use an animation on the element and toggle it with ngIf, it seems to be staying in the memory according to Detached Elements debugger in Edge. On a brief look it appears that maybe a WeakMap has to be used some place instead of Map:

![image](https://github.com/angular/angular/assets/11832552/a5097c70-d9fa-41ec-a6e2-52dca1d86b10)

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-vnp1kv

1. Open this link in Edge browser
2. Open DevTools -> Detached Elements tab
3. Select the correct frame in the dropdown on that tab (it should say `https://stackblitz-starters-vnp1kv.stackblitz.io/`)
4. Toggle element a few times with the button
5. Press get detached element
6. Press analyze to see what keeps the elements there (you will see the above screenshot)

### Please provide the exception or error you saw

```true
Multiple copies of DOM element stay in memory.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
I noticed it in Angular 12, but it is reproducible in 16 as well, see linked StackBlitz
```

### Anything else?

An article I learned about Detached Elements from:
https://blogs.windows.com/msedgedev/2021/12/09/debug-memory-leaks-detached-elements-tool-devtools/

**Comment by garrettld** [comment] 2023-05-31 16:52
The StackBlitz doesn't reproduce the issue for me, this is all I see after toggling the element and clicking 'Get Detached Elements': 
![image](https://github.com/angular/angular/assets/12160067/73b21b86-ee63-4151-928c-238c09bcd065)

**Comment by waterplea** [comment] 2023-05-31 17:23
> The StackBlitz doesn't reproduce the issue for me, this is all I see after toggling the element and clicking 'Get Detached Elements': ![image](https://user-images.githubusercontent.com/12160067/242347998-73b21b86-ee63-4151-928c-238c09bcd065.png)

Yes, now click the ID and it will expand the element behind it. Also, forgot to make sure, since StackBlitz is in an iframe you need to select the right window:

![image](https://github.com/angular/angular/assets/11832552/12b776a6-9434-4172-93ac-752cb6e2dcc5)

**Comment by garrettld** [comment] 2023-06-01 13:59
Thanks for your help on the tooling! I'm sorry I don't have a resolution for you but I did notice a couple things that might help someone debugging this:

1. The detached HTMLDivElements still show in the dev tools even if you remove the `@HostBinding()` that applies the animation to the host element.
2. The detached HTMLDivElements disappear if you define the animation in the parent component instead and apply it to the child like `<div element @fade>`.

This seems to indicate that the animation definition (`animations: [...]`) is causing its host element to be retained, as opposed to the animation usage (`@fade`).

**Comment by JeanMeche** [comment] 2023-06-03 12:11
Isn't this a dupe of #20585 ?

**Comment by waterplea** [comment] 2023-06-03 12:29
> Isn't this a dupe of #20585 ? 

Well, not necessarily, although the underlying issue might be the same. The linked issue talks about manually creating animations with builder and player and so on. Here I have the most basic declarative :enter/:leave animation in metadata with 0 fiddling with the stuff that's under the hood.

**Comment by JeanMeche** [comment] 2023-07-03 18:41
Looks like the issue is the hostbinding like here #24197

**Comment by JeanMeche** [comment] 2023-07-03 23:11
I've proposed a fix.

**Closed** 2023-07-11 15:30 UTC
Labels: area: animations, memory leak, state: has PR
