### ISSUE TITLE
CSS Selector is Missing an _ngcontent attribute

### ISSUE THREAD

**Issue by HazzMan2409** [angular/angular#50678] opened 2023-06-12 14:12 UTC
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

When you have a selector like the following in a component with encapsulated styles `input[type="search"] + button` there should be an _ngcontent attribute added to the selector that actually runs in the browser (on both elements). For example, `input[type="search"][_ngcontent-ng-c2543699087] + button[_ngcontent-ng-c2543699087]`. 

When you run a build the following selector will run `input[type=search]+button[_ngcontent-c2543699087]`

Note that when you run a serve the correct selector will run.

### Please provide a link to a minimal reproduction of the bug

https://github.com/HazzMan2409/ng-attribute-selector-issue

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 16.0.5
Node: 16.18.0
Package Manager: npm 8.19.2
OS: darwin x64

Angular: 16.0.5
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1600.5
@angular-devkit/build-angular   16.0.5
@angular-devkit/core            16.0.5
@angular-devkit/schematics      16.0.5
@schematics/angular             16.0.5
rxjs                            7.8.1
typescript                      5.0.4
```

**Comment by JoostK** [comment] 2023-06-12 14:37
This is a duplicate of #49100, being addressed in #49118.

**Closed by JoostK** 2023-06-12 14:37 UTC
