### ISSUE TITLE
Directive naming ambiguity ?

### ISSUE THREAD

**Issue by biancashouse** [angular/angular#24573] opened 2018-06-19 03:31 UTC
How come a module has directive @NgModule, while a component doesn't have directive @NgComponent.

Perhaps its just how my brain works, but I find the inconsistency slightly disturbing ;-)
IMHO every angular directive should be prefixed by ng.

[NOTE to Github - I definitely type a cap C in @NgComponent, but on saving the comment it gets lowercased. huh?]

**Comment by trotyl** [comment] 2018-06-19 03:57
Duplicate of https://github.com/angular/angular/issues/10729, https://github.com/angular/angular/issues/19178

**Comment by magnattic** [comment] 2018-06-19 12:03
> [NOTE to Github - I definitely type a cap C in @ngcomponent, but on saving the comment it gets lowercased. huh?]

When you use `@` Github thinks you are referencing a Github user or team. Those are usually lowercase. Try escaping it with code blocks: `@NgComponent`.

**Comment by biancashouse** [comment] 2018-06-19 12:36
ok, thanks for that info.
so how to escape an at sign, backslash? \\

**Comment by trotyl** [comment] 2018-06-19 13:44
@biancashouse Or surround it with backticks (\`), then the content would be rendered as `<code>` like: `@Component()`, `@NgModule()`.

**Comment by biancashouse** [comment] 2018-06-20 00:11
useful feedback. many thanks.

**Comment by jasonaden** [comment] 2018-06-21 22:59
Closing as this appears resolved.

**Closed by jasonaden** 2018-06-21 22:59 UTC
