### ISSUE TITLE
Number of RadioButtonStates in form is equal to the number of calls to form.valueChanges.subscribe()

### ISSUE THREAD

**Issue by gerhardboer** [angular/angular#7068] opened 2016-02-14 14:17 UTC
When there are multiple RadioButtonStates in a form, the valueChanges observable of the form is called as many times as there are radio buttons in the form.

So 4 radio buttons in the form, means the subscribe method on form.valueChanges is called 4 times.

The other form inputs like text do not have the same behaviour. When 1 changes, the subscribe() is only called once. Even if there are multiple input controls in the form.

I've added a small project to illustrate this, since i couldn't find the beta.6 on any CDN yet.
https://github.com/gerhardboer/form-radio-subscrition-issue

**Comment by Brocco** [comment] 2016-06-02 03:21
I have also encountered this issue and have been able to reproduce it in a plunk... http://plnkr.co/edit/ouxgrRalPqvqZVzGqW1r?open=app%2Fapp.component.ts&p=preview

note: you can view the multiple calls within the console, just change the selection of the radio buttons

**Comment by kara** [comment] 2016-07-14 21:55
This should be fixed now that radio buttons have been rewritten.  Did a sanity check Plunker [here](http://plnkr.co/edit/ehMo1npFHrNYNRfjpZjX?p=preview), and seems to be resolved.  Closing!   Please feel free to re-open with a plunker if you're still having problems with it.

**Closed by kara** 2016-07-14 21:55 UTC
