### ISSUE TITLE
There is always a leading `null` value on `writeValue` hook when using `ngModel`

### ISSUE THREAD

**Issue by JounQin** [angular/angular#40425] opened 2021-01-14 07:53 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/forms

### Is this a regression?

 No

### Description

 As title

## 🔬 Minimal Reproduction

 https://stackblitz.com/edit/angular-ivy-yxjgag?file=src%2Fapp%2Fapp.component.html

## 🔥 Exception or Error

![image](https://user-images.githubusercontent.com/8336744/104560225-8ad5c480-5680-11eb-8627-21fad304d5e5.png)

`name: model value: null` is not expected to be logged.

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 11.0.3
Node: 12.20.0
OS: darwin x64

Angular: 11.0.3
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1002.0
@angular-devkit/core         10.2.0
@angular-devkit/schematics   11.0.3
@angular/cdk                 11.0.2
@angular/flex-layout         11.0.0-beta.33
@schematics/angular          11.0.3
@schematics/update           0.1100.3
rxjs                         6.6.3
typescript                   4.1.2
</code></pre>

**Anything else relevant?**

**Comment by AndrewKushnir** [comment] 2021-01-14 08:39
Hi @JounQin, this issue looks like a duplicate of #14988, so I'm closing this issue in favor of #14988. Please refer to #14988 for more information. Thank you.

**Closed by AndrewKushnir** 2021-01-14 08:39 UTC

**Comment by JounQin** [comment] 2021-01-14 08:42
Wow, an almost four years old bug... 🤣
