### ISSUE TITLE
Router updates url before NavigationEnd event when using ccanDeactivate guard and location.back()

### ISSUE THREAD

**Issue by miroklarin** [angular/angular#43443] opened 2021-09-14 09:22 UTC
### Which @angular/* package(s) are the source of the bug?

common, router

### Is this a regression?

No

### Description

Set up router with `canDeactivate` guard
Guard dispatch action that triggers displaying custom confirm dialog
Create back button to call `location.back()` on page
navigate to route that have `canDeactivate` guard
hit `back` button
while `canDeactivate` waits to resolve by displaying custom confirm dialog url is changed to requested url even router extra config is set to `urlUpdateStrategy: 'deferred'`
Changing url triggers other observable selectors
If user cancel custom dialog, url is restored and router `NavigationCancel` is emitted
Expected result is not to update url before `NavigationEnd`

### Please provide the environment you discovered this bug in

```true
Angular 10
Angular 12.2.4
```

**Comment by atscott** [comment] 2021-09-14 16:18
Closing - The URL updates before `NavigationEnd` by design.

**Closed by atscott** 2021-09-14 16:18 UTC
Labels: comp: common, comp: router

**Comment by miroklarin** [comment] 2021-09-14 20:04
@atscott url changes while guard is activated and not resolved
is that also by design?
there are two events, something like GuardActivated and GuardEnd (guessing from memory)

**Comment by atscott** [comment] 2021-09-14 20:13
@miroklarin When not navigating through the router APIs, yes this is expected. The router must react to external URL changes after the URL is already updated unless you are using `router.navigateByUrl` or `router.navigate`.
