### ISSUE TITLE
Can we have dynamic directive?

### ISSUE THREAD

**Issue by Eusen** [angular/angular#27225] opened 2018-11-22 08:22 UTC
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/core

### Description
This is the case, the current directive cannot be added dynamically. For example:
```
<mat-menu #menuRef *ngIf="flag"></mat-menu>
<button mat-button [matMenuTriggerFor]="menuRef">Button</button>
```
If flag is false, there will throw error at runtime.
So I must be modified to:
```
<ng-container [ngSwitch]="flag ? 1 : 0">
    <ng-container *ngSwitchCase="0">
        <button mat-button>Button</button>
    </ng-container>
    <ng-container *ngSwitchCase="1">
        <mat-menu #menuRef></mat-menu>
        <button mat-button [matMenuTriggerFor]="menuRef">Button</button>
    </ng-container>
</ng-container>
```
This form is too long-winded!

### Describe the solution you'd like
In my opinion, we can add a form to the command, like class.xxx, which can be dynamically added or removed (remove doesn't look realistic?):
```
<mat-menu #menuRef *ngIf="flag"></mat-menu>
<button mat-button 
              [directive.matMenuTriggerFor]="menuRef" // If menuRef exist, create this directive, if change to null, we can rebuild this button without matMenuTriggerFor directive
>Button</button>
```

### Describe alternatives you've considered
In **Description**

**Comment by Airblader** [comment] 2018-11-22 20:38
There's a completely different, conceptual problem at play here that becomes obvious when you desuggar: you cannot have a template reference variable inside a structural directive and use it from the outside. You know that ngIf will instantiate the template at most once, but Angular has no way of knowing this. Consider if it was ngFor instead of ngIf — your variable might exist multiple times and the compiler cannot know which one you're trying to reference.

**Comment by Eusen** [comment] 2018-11-23 07:56
> This is completely wrong, a dynamic directive must not affects other directives on the same element, and here `[mat-button]` also be destroyed and recreated over and over again due to the existence change of `[matMenuTriggerFor]`.

@trotyl 
Of course I know that buttons are created many times this time, but usually only 1-2 times, because page generation is one-time. And my if condition only affects 1-2 times.

**But if I don't make that judgment, the program will throw exceptions or even fail to run.**

In this way, it's just an immature idea of mine. If you have better ideas, you are welcome to offer them to us.

**Comment by Airblader** [comment] 2018-11-23 09:53
@Eusen You quoted my entire reply and then ignored its point, so I'm assuming you didn't understand it. Let's look at your code:

```
<mat-menu #menuRef *ngIf="flag"></mat-menu>
<button mat-button [matMenuTriggerFor]="menuRef">Button</button>
```

This desuggars into the following:

```
<ng-template [ngIf]="flag">
  <mat-menu #menuRef></mat-menu>
</ng-template>
<button mat-button [matMenuTriggerFor]="menuRef">Button</button>
```

So the problem is now that `mat-menu` only lives in some template, which has its own context. `button` cannot point to `menuRef` because the compiler won't know whether this template is ever even instantiated and if so, how many times. Yes, ngIf will only do it once, but although ngIf is implemented in Angular itself, it's *just a directive*, there's no special treatment.

For example, assume we'd have a `*ngTwiceIf` which creates the template twice (think `*ngFor`). Then the effective result if `flag === true` would be

```
<mat-menu #menuRef></mat-menu>
<mat-menu #menuRef></mat-menu>
<button mat-button [matMenuTriggerFor]="menuRef">Button</button>
```

So which menu does it refer to now: the first or the second one? It's *impossible* to decide, and this is the problem that sits at the base of all of this. The only way to make this work would be if the compiler somehow knew that a specific template could only ever be instantiated once, but it doesn't.

On the other hand, if everything is inside the structural directive such as

```
<ng-container *ngIf="flag">
  <mat-menu #menuRef></mat-menu>
  <button mat-button [matMenuTriggerFor]="menuRef">Button</button>
</ng-container>
```

then this will work because now the reference is in the same context. This desuggars to

```
<ng-template [ngIf]="flag">
  <mat-menu #menuRef></mat-menu>
  <button mat-button [matMenuTriggerFor]="menuRef">Button</button>
</ng-template>
```

so no matter if and how many times this template is instantiated, the reference can always be resolved within the template's context.

**Comment by trotyl** [comment] 2018-11-23 09:59
> It's just an immature idea of mine.

Yep, I do think the idea is feasible, especially in Ivy. 

But the title is a little confusing, this is actually about “conditional directive”, while “dynamic directive” already means directive added by another directive (rather than in the template).

Also, it would require concrete design, I’ll try to file one when I have time.

**Comment by Eusen** [comment] 2018-11-24 06:52
Thanks for your reply. Maybe my point of view is a lot of controversy on the basis of the existing one, but my starting point is to let us write simpler and clearer Angular programs.

**Closed** 2018-11-24 06:52 UTC
