### ISSUE TITLE
Form control validity state not matched by its nativeElement validity state

### ISSUE THREAD

**Issue by yinonov** [angular/angular#33564] opened 2019-11-04 10:06 UTC
Hi, not sure whether this is more of a bug or a feature request but it feels as though this behaviour should have already existed in the framework.

# 🐞 bug report

### Affected Package
The issue is a @angular/forms responsibility

### Is this a regression?
no

### Description
A form control validity state isn't reflected in its native DOM element validity state. and using the native element checkValidity method returns a not updated state .
the expected behaviour is that the DOM element will reflect the same validity state as angular's form control.
using the native [_setCustomValidity_](https://stackoverflow.com/a/18883194/3027703) method might help.

p.s.
there's an issue concerning the same problem [here](https://github.com/angular/angular/issues/26787).
the issue has been automatically locked due to inactivity but I think it needs a little attention.

**Comment by doggy8088** [comment] 2020-03-17 13:56
I think this issue is been tracked here: https://github.com/angular/angular/issues/16352

**Comment by AndrewKushnir** [comment] 2020-05-26 20:06
Hi @yinonov, thanks for reporting the issue. As @doggy8088 mentioned above, it looks like a duplicate of #16352. I will close the ticket, please subscribe to further updates/discussion in #16352. Thank you.

**Closed by AndrewKushnir** 2020-05-26 20:06 UTC
Labels: comp: forms, triage #1
