### ISSUE TITLE
Scoped automatic change detection

### ISSUE THREAD

**Issue by LifeIsStrange** [angular/angular#39658] opened 2020-11-12 19:07 UTC
My company and I really want to like angular, to migrate from Vue to Angular but in the migration process we found out an inherent unacceptable flaw in this framework:

In Vue when a component has changes (e.g the user click on a button in the component), the reactivity autodetection mechanism will trigger changes on the component and its children/descendants.
The OnChanges hook and the methods in the templates will be refreshed. 

Angular instead by using Zone.js will trigger all the things that Vue rightfully trigger *but* they will trigger all of the component ancestors too! Up to the root! 
This means two things:
1)
You can't debug this mess as any method in the template or onchanges hook in the ancestors will be triggered and console.log() so the Devtools are flooded with unrelated changes.
If you call a Store action on the template the store debugger will be flooded too.
2)
And all those calls affect performance dramatically which is pure unwanted nonsense.

So to sum it up, because of this behavior we have
1) unacceptable observability/debugability because of a significantly reduced signal to noise ratio in logging.
2) unacceptable performance loss by recomputing things that shouldn't be recomputed 

This non Scoped reactivity might have usefulness for 0.1% of cases (or for 0%?) but even at best, it should be totally opt-in. 
But the situation is worse, as you cannot opt out. 
Or you can, with changedetection.onpush which disable any reactivity (you must manually trigger it in 2020, can you imagine?)

This (sorry for the word) nonsense made us forced to stay on Vue until Angular fix this fundamental issue.

More on the topic:
https://medium.com/@vyaron/point-of-vue-part-2-facing-angular-e4e9ee65161d

This seems to me too big to be true so I have hope in your answers.
Thanks in advance

**Comment by Airblader** [comment] 2020-11-12 21:45
> Or you can, with changedetection.onpush which disable any reactivity (you must manually trigger it in 2020, can you imagine?)

This is simply not true, and any article on the topic out there will explain why.

**Comment by atscott** [comment] 2020-11-12 21:47
More or less a duplicate of #38782 and other bugs that are related to removing Zones. Note that the effort to make Zonless Angular a reality is on our [roadmap](https://angular.io/guide/roadmap) and is something we plan to do with relatively high priority.

**Closed by atscott** 2020-11-12 21:47 UTC
