### ISSUE TITLE
Loading an anchor target in an iframe is not working

### ISSUE THREAD

**Issue by vinayk406** [angular/angular#25220] opened 2018-07-31 12:56 UTC
Issue can be observed at:
https://stackblitz.com/edit/angular-mssutv?file=src%2Fapp%2Fapp.component.html

Expected behavior:
https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_iframe_name

## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Environment

<pre><code>
Angular version: 6.1.0

Browser:
- [x] Chrome (desktop) version 70
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

</code></pre>

**Comment by trotyl** [comment] 2018-07-31 13:01
Duplicate of https://github.com/angular/angular/issues/16689

**Comment by IgorMinar** [comment] 2018-07-31 23:03
Thanks for reporting this issue. However this issue is a duplicate of an existing issue #16689. Please subscribe to that issue for future updates.

**Closed** 2018-07-31 23:03 UTC
