### ISSUE TITLE
Http interceptors: Pass parameters from HTTP requests

### ISSUE THREAD

**Issue by maxime1992** [angular/angular#19656] opened 2017-10-11 12:06 UTC
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ x ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
I'm currently working with a big company. They're providing a module to all of their developers, in order to help them with repetitive task such as security (add token into HTTP request header).

In order to do that, they provide some interceptors, which are global to the application. Those interceptors are helping on a global level but sometimes, developers would like to bypass some of them (and for example not adding the token to the header).

Right now, the only move is to add a given header before sending the request and then, check if that header is present from the interceptor to do things accordingly.

## Expected behavior
Would it be possible to pass an optional configuration object to a request (GET | POST | PUT | etc) that might just be retrieve as an optional parameter into the interceptor?

## What is the motivation / use case for changing the behavior?
When people provide high level interceptor for an app, it would be handy to be able to send them parameters.

**Comment by stefdelec** [comment] 2017-10-11 12:17
Hi, 

What you could do is doing your own interceptor. Wrap both in your own implementation

```
import {http} from @angular/core
import {EnterpriseHTTP} from 'yourEntrepriseHttp"
class MyOwnHttp{

constructor(private http:Http, private enterprise:EnterpriseHTTP){
}

public post(url: string, body: any, interceptor=false options?: RequestOptionsArgs): Observable<Response> {

if(interceptor){
return this.enterprise.http()
else{
return this.http.post(url,body,options)
}
}

```

**Comment by maxime1992** [comment] 2017-10-11 12:51
Yes but this way we need to wrap every methods, define our own Http... Couldn't we think of something even simpler?

**Comment by stefdelec** [comment] 2017-10-11 12:57
It 's only 5 methods.

**Comment by wKoza** [comment] 2017-10-11 13:14
@maxime1992 , 

> developers would like to bypass them

==> developers would like to bypass some of them

**Comment by trotyl** [comment] 2017-10-11 15:09
Duplicate of https://github.com/angular/angular/issues/18155.

**Comment by alxhub** [comment] 2017-11-28 23:16
Closing as a duplicate.

**Closed by alxhub** 2017-11-28 23:16 UTC
Labels: comp: http
