### ISSUE TITLE
Dynamic import of locales not available in Angular 13

### ISSUE THREAD

**Issue by Rambou** [angular/angular#44153] opened 2021-11-12 11:14 UTC
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

Yes

### Description

While in a previous version of angular, you could import locales and their extra's dynamically, it is impossible in angular 13. Below there is a sample of code with Webpack magic comments that lazy-load of locales was possible.
```
import(
  /* webpackExclude: /\.d\.ts$/ */
  /* webpackMode: "lazy-once" */
  /* webpackChunkName: "i18n-base" */
  `@angular/common/locales/${id}.mjs`)
.then(m => m.default)
.catch(error => {
   .....
});
```
Now Webpack throws an error because `exports` attribute seems to be misconfigured in `package.json`

### Please provide the exception or error you saw

```true
Error: Module not found: Error: Package path ./locales is not exported from package .../node_modules/@angular/common (see exports field in .../node_modules/@angular/common/package.json)
```

### Please provide the environment you discovered this bug in

```true
Angular CLI: 13.0.1
Node: 12.22.6
Package Manager: yarn 1.22.15
OS: linux x64

Angular: 13.0.0
... animations, cdk, common, compiler, compiler-cli, core
... elements, forms, language-service, material
... material-moment-adapter, platform-browser
... platform-browser-dynamic, router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1300.1
@angular-devkit/build-angular   13.0.1
@angular-devkit/core            13.0.1
@angular-devkit/schematics      13.0.1
@angular/cli                    13.0.1
@schematics/angular             13.0.1
ng-packagr                      13.0.3
rxjs                            7.4.0
typescript                      4.4.4
```

**Comment by alan-agius4** [comment] 2021-11-12 12:07
@Rambou, the above mentioned behaviour is caused by a confirmed bug in Webpack. See webpack/webpack#13865 for which a workaround can be found https://github.com/highlightjs/highlight.js/issues/3223#issuecomment-953337602.

It's important to point out that using Webpack specific features such as magic comments are not supported by the Angular tooling team. The fact that the Angular CLI is using Webpack is an implementation detail which can change in the future.

Duplicate of https://github.com/angular/angular-cli/issues/22088

**Closed by alan-agius4** 2021-11-12 12:07 UTC
Labels: comp: common, comp: i18n
