### ISSUE TITLE
VSCode + Angular - Intellisense bug with underscore.

### ISSUE THREAD

**Issue by ExDeaDguY** [angular/angular#31002] opened 2019-06-12 13:26 UTC
# 🐞 bug report

### Affected Package
I'm using Angular 7 but I'm sure it goes beyond that. I've posted this on the VSCode page and they directed me here.

### Description

I am using the latest version of VSCode 1.35.0 and Angular 7. I came across an odd bug. I'm pretty sure it's a bug and not a config setting.

In angular, my component folder has 3 items in it, my .html, .scss, and .ts files. When I create functions in the component ts such as:

```
public ThisIsAFunction() { }
public ThisIsAnother_Function() { }
```
Now in the html file I will create an element and try to assign a property like so:

```<button (click)="this.ThisIsAFunction()">DoFunction</button>```

The issue here is, when I start typing "this.ThisIsA" the intellisense will only display "ThisIsAFunction" in the list of available functions. Any functions named with an underscore will never show up.

## 🌍  Your Environment

Angular 7
<pre><code>
Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.5
@angular-devkit/build-angular     0.13.5
@angular-devkit/build-optimizer   0.13.5
@angular-devkit/build-webpack     0.13.5
@angular-devkit/core              7.3.5
@angular-devkit/schematics        7.3.5
@angular/cli                      7.3.5
@ngtools/webpack                  7.3.5
@schematics/angular               7.3.5
@schematics/update                0.13.5
rxjs                              6.4.0
typescript                        3.1.6
webpack                           4.29.0
</code></pre>

Thanks.

**Comment by santoshyadav198613** [comment] 2019-06-12 18:40
![image](https://user-images.githubusercontent.com/11923975/59377177-5052ca00-8d6f-11e9-913a-ffaa0556f674.png)

This is enabled by Angular Language Service, I tried the same and it works for me.

I created 2 functions as you mentioned one with an underscore and it comes as suggestion for me.

**Comment by ExDeaDguY** [comment] 2019-06-13 15:41
Thanks, I actually tested it again on a new component and it does in fact work. But, on other components in my project it does not work. I am not entirely sure what is causing the intellisense to pick it up sometimes and not others. It is not a crash/reboot issue as I have closed everything, rebooted and the problem still persists. If I remove the "_" from the function name, the function starts showing as it should. I will have to investigate further and see if I can find something that may be contributing to this issue.

**Comment by atscott** [comment] 2020-10-26 19:03
Thanks for reporting this issue. I wasn't able to reproduce this so it may have been fixed in one of the recent releases. Please update to the most recent version to resolve the problem.

If after upgrade the problem still exists in your application please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template (including a reproduction example and steps to reproduce).

**Closed by atscott** 2020-10-26 19:03 UTC
Labels: comp: language-service
