### ISSUE TITLE
HTML5 validation for attributes "formcontrolname" and "routerlink"

### ISSUE THREAD

**Issue by zylkdevs** [angular/angular#30253] opened 2019-05-03 12:11 UTC
# 🚀 feature request

### Relevant Package
@angular/forms and @angular/router

### Description
W3C HTML5 official validator shows "attribute not allowed" errors while is validating my angular application. I'm referring specifically to angular "formcontrolname" and "routerlink" attributtes which are basic attributes in angular components development. Here you have the especific example:
`Error: Attribute formcontrolname not allowed on element <input> at this point.`
`Error: Attribute routerlink not allowed on element <a> at this point.`

It is clear that those attributes are specific of angular and HTML5 validator does not recognize them as standard.
### Describe the solution you'd like
A no error HTML5 validation using "formcontrolname" and "routerlink" attributes or others with the same functionality.

### Describe alternatives you've considered
I have seen that a possible alternative is to add "data-" prefix to those attributes that are not considered as standard in HTML5. 
Although this alternative could be viable, is there any known way to avoid the use of these "data-*" attributes and get HTML validation without errors anyway?

**Comment by dawidgarus** [comment] 2019-05-03 12:21
If you don't want html attribute to be created just write: `[formControlName]="'name'"` instead of `formControlName="name"`. Personally, I always use former for angular inputs.

**Comment by trotyl** [comment] 2019-05-04 07:45
Duplicate of https://github.com/angular/angular/issues/13969

**Comment by alxhub** [comment] 2019-05-07 22:58
As @dawidgarus says, use `[formControlName]`, etc. Closing as a duplicate.

**Closed by alxhub** 2019-05-07 22:58 UTC
Labels: comp: core & compiler
