### ISSUE TITLE
paramsInheritanceStrategy = 'always' doesn't flatted data params in resolvers

### ISSUE THREAD

**Issue by jasonaden** [angular/angular#21878] opened 2018-01-29 23:46 UTC
Essentially, if we have 2 route resolvers in a parent/child relationship, we'd expect to be able to see the parent resolver's output in the child resolver's route data. Unfortunately, the parameter inheritance code (this bit: https://github.com/angular/angular/blob/master/packages/router/src/router_state.ts#L193) actually ends up executing *after* the resolvers already run.

Reproduction needed. Reported internally.

**Comment by KatzeKahn** [comment] 2018-05-17 11:17
I agree, the parent resolver data is not yet available in a depending child resolver. The `route.data` is null on execution. :(

**Comment by ukrukarg** [comment] 2018-07-26 13:50
Might be related to https://github.com/angular/angular/issues/25140?

**Comment by atscott** [comment] 2020-07-08 19:21
I think the code pointer is outdated and it should point to https://github.com/angular/angular/blob/6eb868b63a5b0ae877346b48ac659f35e6e7af8b/packages/router/src/operators/resolve_data.ts#L47-L52 (notice that `resolveNode` happens before `inheritedParamsDataResolve` are copied to `futureARS`)

**Comment by petebacondarwin** [comment] 2020-10-26 21:06
Closing due to lack of reproduction.

**Closed by petebacondarwin** 2020-10-26 21:06 UTC
Labels: P3, comp: router, freq2: medium, hotlist: google, needs clarification, needs reproduction, router: guards/resolvers, router: navigation pipe, state: confirmed, type: bug/fix
