### ISSUE TITLE
Compiler does not error on non-existent structural directive and does not check its inputs

### ISSUE THREAD

**Issue by ArielGueta** [angular/angular#40664] opened 2021-02-02 08:07 UTC
I'm using Ivy with the new Ivy flag in the VSCode plugin, and I want to share some crucial issues:

### Invalid Directive

If I use a structural directive that doesn't exist, I don't get any error. Not in VSCode and not compile error:

![image](https://user-images.githubusercontent.com/20522870/106569136-d8857480-653c-11eb-8eb9-381887c6b777.png)
![image](https://user-images.githubusercontent.com/20522870/106569176-e2a77300-653c-11eb-8214-1138b314a270.png)

### Valid Directive

When I use the following custom directive:

```ts
@Directive({
  selector: '[appTest]'
})
export class TestDirective {
  @Input() appTest: 'foo' | 'bar';
  @Input() appTestType: boolean;

  constructor(private tpl: TemplateRef<any>, vcr: ViewContainerRef) { }
}
```

- I don't get autocomplete for the `appTest` input type:

![image](https://user-images.githubusercontent.com/20522870/106569431-2d28ef80-653d-11eb-9d00-0a6e15ee31b3.png)

- I don't get any error when passing the wrong type, even though it recognizes the type:

![image](https://user-images.githubusercontent.com/20522870/106569653-7e38e380-653d-11eb-85af-c521267e3f78.png)

- It doesn't recognizes additional inputs: ( not autocomplete or error )

![image](https://user-images.githubusercontent.com/20522870/106569878-cb1cba00-653d-11eb-9a00-00c6fcc40ce3.png)

Angular version: ~11.1.1

**Comment by siglar** [comment] 2021-02-02 10:30
I am facing a similar error: structural directives are marked by Language Service as not properly initialized:

![error1](https://user-images.githubusercontent.com/3383006/106586370-a843d300-6548-11eb-8a7b-f716f45f431c.jpg)

App.module.ts:
![error2](https://user-images.githubusercontent.com/3383006/106586613-fa84f400-6548-11eb-8a6f-b7756acb0184.jpg)

App.module.ts also includes "CommonModule".

Angular compiles with no errors, and code works just fine.

I also get the following error in the Chrome console:
![error3](https://user-images.githubusercontent.com/3383006/106587037-68312000-6549-11eb-9d02-43bfb96cb8bd.jpg)

If I remove the asterisk (*), all errors disappear. But I need the template reference, so that's a no go.
![error4](https://user-images.githubusercontent.com/3383006/106587345-c8c05d00-6549-11eb-9075-fb5c4f6670b7.jpg)
 
Same version of Angular: "Angular version: ~11.1.1"

**Comment by atscott** [comment] 2021-02-02 19:16
@ArielGueta - As far as the type checking goes for the valid directive input, you need to ensure that you have the compiler option for checking input types enabled, specifically [strictInputTypes](https://angular.io/guide/template-typecheck#troubleshooting-template-errors). You will get the best experience for the Language Service when you have enabled "strictTemplates" in your `tsconfig.json`. 
The Language Service experience is directly linked to what you've told the Angular compiler to check for. If the compiler configured to ignore input types, then the Language Service will also ignore input types.

**Comment by atscott** [comment] 2021-02-02 19:32
The reason the compiler doesn't throw on the non-existent structural directive is that it's syntactic sugar for 
```
<ng-template fake>
  <div></div>
</ng-template>
```
and we don't check the attributes. The compiler will also not throw an error at the moment for an input to the directive that doesn't exist in the component context, i.e. `<div *fake="doesNotExist">`.
These both could/should arguably be checked by the compiler.

**Comment by JoostK** [comment] 2021-02-02 19:41
For reference, the invalid directive diagnostic is being tracked in #37322

**Comment by atscott** [comment] 2021-02-02 19:45
> For reference, the invalid directive diagnostic is being tracked in #37322

Ah, perfect. Thanks @JoostK - I tried to find if we had that somewhere but couldn't. 

Closing this issue as a duplicate of #37322

**Closed by atscott** 2021-02-02 19:45 UTC
Labels: P3, comp: compiler

**Comment by ArielGueta** [comment] 2021-02-03 06:18
@atscott thanks for the quick answer. It now shows an error when we pass an invalid type. But what about the intellisense issue? why we don't get autocomplete based on the input and its type?

**Comment by atscott** [comment] 2021-02-03 16:43
@ArielGueta - I've opened a feature request in the extension repository for this: https://github.com/angular/vscode-ng-language-service/issues/1096

**Comment by ArielGueta** [comment] 2021-02-04 06:27
Thanks!
