### ISSUE TITLE
Event triggering inside unit tests doesn't work ( Ivy engine: enabled)

### ISSUE THREAD

**Issue by Domainv** [angular/angular#31418] opened 2019-07-04 12:20 UTC
# 🐞 bug report

### Affected Package
angular/*@8.0.0 (Ivy engine enabled)

angular/*8.2.0-next.0 (Ivy engine enabled)
Still issue

### Is this a regression?

This used to work with 
Ivy engine: disabled

### Description

Event triggering inside our tests doesn't work with Ivy engine

## 🔬 Minimal Reproduction
const fixture = createTestComponent(
 ...
);
const directive = fixture.debugElement.query(
  By.directive(PopoverDirective)
);

directive.triggerEventHandler('click', {});

## 🔥 Exception or Error
<pre><code>
TypeError: Cannot read property 'classList' of null
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.0.2
Node: 10.16.0
OS: linux x64
Angular: 8.0.0
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker

Package                                    Version
--------------------------------------------------------------------
@angular-devkit/architect                  0.800.2
@angular-devkit/build-angular              0.800.2
@angular-devkit/build-optimizer            0.800.2
@angular-devkit/build-webpack              0.800.2
@angular-devkit/core                       8.0.1
@angular-devkit/schematics                 8.0.1
@angular/cli                               8.0.2
@ngtools/json-schema                       1.1.0
@ngtools/webpack                           8.0.2
@nguniversal/common                        7.1.1
@nguniversal/express-engine                7.1.1
@nguniversal/module-map-ngfactory-loader   7.1.1
@schematics/angular                        8.0.1
@schematics/update                         0.800.2
ng-packagr                                 5.1.0
rxjs                                       6.4.0
typescript                                 3.4.5
webpack                                    4.30.0

</code></pre>

### Workaround

use @netbasal/spectator library
dispatchMouseEvent(directive.nativeElement, 'click');

**Comment by Splaktar** [comment] 2019-07-04 22:41
It would be really helpful to know if this is still an issue in `8.2.0-next.0`.

**Comment by Domainv** [comment] 2019-07-05 11:25
@Splaktar 
Sorry, but it still an issue in 8.2.0-next.0
I trying to create a more clear repo with reproduction...

**Comment by Domainv** [comment] 2019-07-08 09:09
@Splaktar 
Repo with reproduction
https://github.com/Domainv/ivy-unit-tests-reproduction
'ng test' finish with success only if Ivy disabled

Problem here.
https://github.com/angular/angular/blob/master/packages/core/src/render3/util/discovery_utils.ts#L287
The method returns the blank array.

I can't understand what happens here
```
  const lContext = loadLContextFromNode(element);
  const lView = lContext.lView;
  const tView = lView[TVIEW];
  const lCleanup = lView[CLEANUP];
  const tCleanup = tView.cleanup;
```

And here
```
const firstParam = tCleanup[i++];
const secondParam = tCleanup[i++];
```
![Screenshot from 2019-07-08 12-07-46](https://user-images.githubusercontent.com/14885427/60798024-0647e300-a179-11e9-877d-0216999a6459.png)

**Comment by Domainv** [comment] 2019-07-09 13:21
@mhevery Could you explain what happens in the method, please? I would like to fix it.
https://github.com/angular/angular/blob/master/packages/core/src/render3/util/discovery_utils.ts#L287

**Comment by Splaktar** [comment] 2019-07-09 23:13
Thank you for posting more details and the reproduction repo. I've pinged some people on the team to help answer your questions.

The little bit that I can add here is that `lView` is short for Logical View and `tView` is short for Template View. One holds data related to the 'static' view and the other has data specific to an instance of the view.

**Comment by Domainv** [comment] 2019-07-11 09:08
Thank you)

**Comment by Domainv** [comment] 2019-07-11 13:44
Found the interface, investigation...)
https://github.com/angular/angular/blob/master/packages/core/src/render3/interfaces/view.ts#L71

**Comment by Domainv** [comment] 2019-07-12 13:42
@Splaktar @mhevery 
After diving in-depth Angular I've found why it happens. 
debugNode use event listeners which were parsed by Ivy and were monkey patched into nativeNode with  "__ngContext__[1].cleanup" field. 
Ivy parsing only events listeners who used obviously.
But in our directive(popover) we use dynamically created event listeners and Ivy can't see them.

That's why 
```
const directive = fixture.debugElement.query(
  By.directive(PopoverDirective)
);

directive.triggerEventHandler('click', {});
```
doesn't work.

Could someone comment on this, please?

**Comment by Splaktar** [comment] 2019-07-12 14:55
As far as I understand, this is an area that is still undergoing some design considerations. It's very helpful that you have helped to identify the issue and related code. That should help with the triage process.

**Comment by JBusch** [comment] 2020-03-09 17:02
I'm facing this issue with 9.0.4

**Comment by amakhrov** [comment] 2020-07-21 19:41
When dealing with manually created event listeners (rather than template-driven), it's probably more helpful to also manually dispatch a native DOM event:
```
directive.nativeElement.dispatchEvent(new Event('click'))
```

**Comment by atscott** [comment] 2020-10-22 16:53
I believe the error with `classList` was resolved in https://github.com/angular/angular/pull/34514. By design, Angular's `DebugElement#triggerEventHandler` does not forward events to listeners added outside the Angular context (and changing this . Before #34514, Ivy did not correctly ignore these like the previous runtime, and that's where the error was coming from. 

If you want to trigger events in your tests and have other listeners be called, follow the advice by @amakhrov in https://github.com/angular/angular/issues/31418#issuecomment-662068004.

**Closed by atscott** 2020-10-22 16:53 UTC
Labels: comp: testing, engine: ivy, hotlist: devrel
