### ISSUE TITLE
Error in compiling: Could not mark an element as translatable inside of a translatable section

### ISSUE THREAD

**Issue by bhaveshdewangan** [angular/angular#42153] opened 2021-05-18 19:19 UTC
Current behavior
Compiling an application with the angular compiler throws error, Could not mark an element as the translatable inside of a translatable section.

Expected/desired behavior
It should compile successfully. When I do a fresh npm install it works for one or two builds after that application throwing error.

Angular CLI: 11.2.9
Node: 12.13.0
OS: win32 x64

Application dev-dependencies:
"@angular-devkit/build-angular": "~0.803.25",
"@angular/cli": "~8.3.25",
"@angular/compiler-cli": "^8.2.14",
"@angular/language-service": "^8.2.14",

<img width="938" alt="Capture" src="https://user-images.githubusercontent.com/15868717/118709649-e2588c80-b83a-11eb-9e35-438b65060183.PNG">

**Comment by JoostK** [comment] 2021-05-18 19:25
It looks like you're using Angular 8 (but with CLI 11?) which is quite old and unsupported nowadays, with v12 having been released last week. Could you please upgrade to a supported version of Angular to see if the problem persists? If yes, please provide a minimal reproduction.

**Comment by petebacondarwin** [comment] 2021-05-18 19:48
Indeed this error comes from the old ViewEngine i18n extractor. Please try with ivy enabled instead.

**Comment by JoostK** [comment] 2021-06-18 18:08
Closing due to lack of reproduction and a lot of changes in this area in recent versions, so please update to a supported version of Angular. Feel free to open a new issue if you continue to have problems.

**Closed by JoostK** 2021-06-18 18:08 UTC
Labels: comp: compiler, comp: i18n, needs reproduction
