### ISSUE TITLE
Angular ngSW is load old assets on first visit 

### ISSUE THREAD

**Issue by mochirfan** [angular/angular#48501] opened 2022-12-15 03:53 UTC
### Which @angular/* package(s) are the source of the bug?

service-worker

### Is this a regression?

Yes

### Description

I have an web app using angular 13 and ngsw with caching features. The problem is when I deployed a new version to production, then I refresh the page, it's updating to a latest version, but sometimes when open the page again it's load the old version and I have to refresh it again to get the latest version.

I've tried change the registrationStrategy to 'registerImmediately' but I doesn't changes a thing. How to solve this issue? or should I disable caching?

### Please provide the environment you discovered this bug in (run `ng version`)

```true
"@angular/core": "~13.3.11", "@angular/service-worker": "~13.3.11",
```

**Comment by alxhub** [comment] 2022-12-16 00:33
Hi @mochirfan,

From your description, I suspect the Service Worker is working as intended here. The default behavior of Angular's service worker is to improve the application loading time by locally caching its code and assets. This is a tradeoff - loading from cache means that the SW doesn't check with the server first to see if an update is available, which means it might load an older version of the application.

You can optionally specify `navigationRequestStrategy: 'freshness'` in your service worker config, which tells the SW not to serve initial requests from its cache unless the network request fails. This trades off that loading performance in favor of always fetching the latest index from the server, which should have hashed URLs of the app's bundles.

Is this what you were asking about, or are you encountering a problem where the application is loading older assets after an update has been activated?

**Comment by mochirfan** [comment] 2022-12-16 01:01
Hello @alxhub, thanks for your response.  The problem is, when I deploy a new version of the web then I refresh the browser it's working fine until I close the browser or when I'm back another day, the browser is loading an older assets. I expect when the new version is available and I refresh the browser, It's caching from the latest version, not from the old one.

Thank you

**Comment by mochirfan** [comment] 2022-12-21 09:00
update from this issue, It happens when i close the browser then open the web it's loading from old assets.

**Comment by alxhub** [comment] 2022-12-28 20:12
From the description, it sounds like the service worker may be rejecting the new deployed version, which can happen if the deployed files that are served in production don't match the expected hashes for that version defined in `ngsw.json`- the SW is very conservative about the safety of caching files. I'd recommend taking a look at the SW debug logs (`ngsw/state` as described [here](https://angular.io/guide/service-worker-devops#locating-and-analyzing-debugging-information)).

To investigate any further, we'd need a reproduction of the problem.

**Comment by mochirfan** [comment] 2022-12-29 04:58
Thank you, I tried to debug the ngsw state and i found this message:

NGSW Debug Info:

Driver version: 13.3.11
Driver state: SAFE_MODE (Initialization failed due to error: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON)
Latest manifest hash: none
Last update check: 8s472u

**Comment by alxhub** [comment] 2023-01-06 00:43
Yep, that message means that the SW is trying to fetch a required file from the server as part of the update, but is getting contents that don't match the expected SHA1 as declared in `ngsw.json`. The next step would be to check the files that your server is serving and verify that they're identical to the assets declared in `ngsw.json` that are hashed at build time. In rare cases I've heard of web servers with plugins that add contents to `index.html` files for example and cause the hash to mismatch.

As this is a problem with your build/serve environment and not a bug with `@angular/service-worker`, I'll go ahead and close this issue. If you need any support with the investigation, I recommend asking on the Angular community Discord - there's a number of SW users there who might have some ideas.

**Closed by alxhub** 2023-01-06 00:43 UTC
Labels: needs reproduction, area: service-worker
