### ISSUE TITLE
New form API validation lead to not responding mode

### ISSUE THREAD

**Issue by neelsbr** [angular/angular#10426] opened 2016-08-01 14:02 UTC
Hi 
I am using "@angular/forms": "0.2.0" , I have added email validation in my form and set max length as 50. If I type more than 20 characters it leads to application hang mode. You can check this issue in below plunkr [(http://plnkr.co/edit/3F8gHaDFo8bDLeDMKJZV?p=preview)]
I feel this is due to validation on user keypress event. Can you please check this issue

* **Angular version:** 2.0.0-rc4

**Comment by neelsbr** [comment] 2016-09-01 08:20
Any updates on this issue?

**Comment by pkozlowski-opensource** [comment] 2016-09-01 13:17
@neelsbr I can't reproduce with the latest ng2 and forms: https://plnkr.co/edit/TAccY3LFMVuaa9RmrSOB?p=preview

Could you please try to modify the above minimal plunk to expose the issue? Thnx!

**Comment by pkozlowski-opensource** [comment] 2016-09-07 12:42
Closing as we didn't get any reproduce scenario.

**Closed by pkozlowski-opensource** 2016-09-07 12:42 UTC
Labels: comp: forms, need: repro
