### ISSUE TITLE
Error: ERROR: unknown browser found in getBrowsersFromCLI() when running "npm test"

### ISSUE THREAD

**Issue by Ablu** [angular/angular#3799] opened 2015-08-23 12:17 UTC
Hello,

I am trying to follow the instructions from `DEVELOPER.md`.

Now if I run `npm test` I get:

~~~
/angular/angular (master) $ npm test

> angular@2.0.0-alpha.35 test /home/ablu/angular/angular
> gulp test.all.js && gulp test.all.dart

Dart SDK detected:
[14:10:50] Using gulpfile ~/angular/angular/gulpfile.js
[14:10:50] Starting 'test.all.js'...
=============================================================================
*********
** ENV **
*********
DART_SDK=/home/ablu/Downloads/dart-sdk/
DART=/home/ablu/Downloads/dart-sdk//bin/dart
PUB=/home/ablu/Downloads/dart-sdk//bin/pub
DARTANALYZER=/home/ablu/Downloads/dart-sdk//bin/dartanalyzer
DARTDOC=/home/ablu/Downloads/dart-sdk//bin/dartdoc
DART_DOCGEN=/home/ablu/Downloads/dart-sdk//bin/docgen
DARTIUM_BIN=/home/ablu/Downloads/dart-sdk/dartium-lucid64-full-stable-1.11.3.0/chrome
CHROME_BIN=google-chrome
PATH=/home/ablu/angular/angular/node_modules/.bin:/home/ablu/angular/node-v0.12.7-linux-x64/lib/node_modules/npm/bin/node-gyp-bin:/home/ablu/angular/angular/node_modules/.bin:/home/ablu/angular/node-v0.12.7-linux-x64/bin/:/home/ablu/gopath/bin:/usr/lib64/ccache/:/home/ablu/angular/node-v0.12.7-linux-x64/bin/:/home/ablu/gopath/bin:/usr/lib64/ccache/:/home/ablu/gopath/bin:/usr/lib64/ccache/:/home/ablu/gopath/bin:/usr/lib64/ccache/:/home/ablu/gopath/bin:/usr/lib64/ccache/:/usr/lib64/qt-3.3/bin:/usr/lib64/ccache:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/home/ablu/.local/bin:/home/ablu/bin:/home/ablu/Downloads/dart-sdk//bin:/home/ablu/Downloads/dart-sdk//bin:/home/ablu/Downloads/dart-sdk//bin:/home/ablu/Downloads/dart-sdk//bin
NGDART_BASE_DIR=/home/ablu/angular/angular/scripts
NGDART_SCRIPT_DIR=/home/ablu/angular/angular/scripts/ci
Dart SDK detected:
[14:10:53] Using gulpfile ~/angular/angular/gulpfile.js
[14:10:53] Starting 'pre-test-checks'...
[14:10:53] Starting 'build/checkCircularDependencies'...
[14:10:58] Finished 'build/checkCircularDependencies' after 4.86 s
[14:10:58] Finished 'pre-test-checks' after 4.87 s
Dart SDK detected:
[14:11:00] Using gulpfile ~/angular/angular/gulpfile.js
[14:11:00] Starting 'test.js'...
[14:11:00] Starting 'test.unit.tools/ci'...
Started
.....................


21 specs, 0 failures
Finished in 0.133 seconds
[14:11:01] Finished 'test.unit.tools/ci' after 381 ms
[14:11:01] Starting 'test.transpiler.unittest'...
Started
........


8 specs, 0 failures
Finished in 0.183 seconds
[14:11:01] Finished 'test.transpiler.unittest' after 620 ms
[14:11:01] Starting 'docs/test'...
Started
..................


18 specs, 0 failures
Finished in 4.279 seconds
[14:11:06] Finished 'docs/test' after 4.63 s
[14:11:06] Starting 'test.unit.js/ci'...
[14:11:06] 'test.unit.js/ci' errored after 704 μs
[14:11:06] Error: ERROR: unknown browser found in getBrowsersFromCLI()
    at getBrowsersFromCLI (/home/ablu/angular/angular/gulpfile.js:560:13)
    at Gulp.<anonymous> (/home/ablu/angular/angular/gulpfile.js:680:21)
    at module.exports (/home/ablu/angular/angular/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/home/ablu/angular/angular/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/home/ablu/angular/angular/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/home/ablu/angular/angular/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at runNextSet (/home/ablu/angular/angular/node_modules/run-sequence/index.js:79:16)
    at Gulp.onTaskEnd (/home/ablu/angular/angular/node_modules/run-sequence/index.js:68:5)
    at Gulp.emit (events.js:129:20)
    at Gulp.Orchestrator._emitTaskDone (/home/ablu/angular/angular/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
[14:11:06] 'test.js' errored after 5.64 s
[14:11:06] Error: build sequence failed
[14:11:06] 'test.all.js' errored after 16 s
[14:11:06] Error in plugin 'gulp-shell'
Message:
    Command failed: /bin/sh -c ./scripts/ci/test_js.sh

Details:
    killed: false
    code: 1
    signal: null
    cmd: /bin/sh -c ./scripts/ci/test_js.sh
    stdout: =============================================================================
*********
** ENV **
*********
DART_SDK=/home/ablu/Downloads/dart-sdk/
DART=/home/ablu/Downloads/dart-sdk//bin/dart
PUB=/home/ablu/Downloads/dart-sdk//bin/pub
DARTANALYZER=/home/ablu/Downloads/dart-sdk//bin/dartanalyzer
DARTDOC=/home/ablu/Downloads/dart-sdk//bin/dartdoc
DART_DOCGEN=/home/ablu/Downloads/dart-sdk//bin/docgen
DARTIUM_BIN=/home/ablu/Downloads/dart-sdk/dartium-lucid64-full-stable-1.11.3.0/chrome
CHROME_BIN=google-chrome
PATH=/home/ablu/angular/angular/node_modules/.bin:/home/ablu/angular/node-v0.12.7-linux-x64/lib/node_modules/npm/bin/node-gyp-bin:/home/ablu/angular/angular/node_modules/.bin:/home/ablu/angular/node-v0.12.7-linux-x64/bin/:/home/ablu/gopath/bin:/usr/lib64/ccache/:/home/ablu/angular/node-v0.12.7-linux-x64/bin/:/home/ablu/gopath/bin:/usr/lib64/ccache/:/home/ablu/gopath/bin:/usr/lib64/ccache/:/home/ablu/gopath/bin:/usr/lib64/ccache/:/home/ablu/gopath/bin:/usr/lib64/ccache/:/usr/lib64/qt-3.3/bin:/usr/lib64/ccache:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/home/ablu/.local/bin:/home/ablu/bin:/home/ablu/Downloads/dart-sdk//bin:/home/ablu/Downloads/dart-sdk//bin:/home/ablu/Downloads/dart-sdk//bin:/home/ablu/Downloads/dart-sdk//bin
NGDART_BASE_DIR=/home/ablu/angular/angular/scripts
NGDART_SCRIPT_DIR=/home/ablu/angular/angular/scripts/ci
Dart SDK detected:
[14:10:53] Using gulpfile ~/angular/angular/gulpfile.js
[14:10:53] Starting 'pre-test-checks'...
[14:10:53] Starting 'build/checkCircularDependencies'...
[14:10:58] Finished 'build/checkCircularDependencies' after 4.86 s
[14:10:58] Finished 'pre-test-checks' after 4.87 s
Dart SDK detected:
[14:11:00] Using gulpfile ~/angular/angular/gulpfile.js
[14:11:00] Starting 'test.js'...
[14:11:00] Starting 'test.unit.tools/ci'...
Started
.....................


21 specs, 0 failures
Finished in 0.133 seconds
[14:11:01] Finished 'test.unit.tools/ci' after 381 ms
[14:11:01] Starting 'test.transpiler.unittest'...
Started
........


8 specs, 0 failures
Finished in 0.183 seconds
[14:11:01] Finished 'test.transpiler.unittest' after 620 ms
[14:11:01] Starting 'docs/test'...
Started
..................


18 specs, 0 failures
Finished in 4.279 seconds
[14:11:06] Finished 'docs/test' after 4.63 s
[14:11:06] Starting 'test.unit.js/ci'...
[14:11:06] 'test.unit.js/ci' errored after 704 μs
[14:11:06] Error: ERROR: unknown browser found in getBrowsersFromCLI()
    at getBrowsersFromCLI (/home/ablu/angular/angular/gulpfile.js:560:13)
    at Gulp.<anonymous> (/home/ablu/angular/angular/gulpfile.js:680:21)
    at module.exports (/home/ablu/angular/angular/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/home/ablu/angular/angular/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/home/ablu/angular/angular/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/home/ablu/angular/angular/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at runNextSet (/home/ablu/angular/angular/node_modules/run-sequence/index.js:79:16)
    at Gulp.onTaskEnd (/home/ablu/angular/angular/node_modules/run-sequence/index.js:68:5)
    at Gulp.emit (events.js:129:20)
    at Gulp.Orchestrator._emitTaskDone (/home/ablu/angular/angular/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
[14:11:06] 'test.js' errored after 5.64 s
[14:11:06] Error: build sequence failed

    stderr: 
npm ERR! Test failed.  See above for more details.
~~~

@pkozlowski-opensource asked me on IRC to report an issue about this.

Regards,
Ablu

**Comment by ericmartinezr** [comment] 2015-08-23 14:36
This is the same as this one https://github.com/angular/angular/issues/3691

**Comment by pkozlowski-opensource** [comment] 2015-08-23 14:41
Indeed, thnx @ericmartinezr. Closing as duplicate of #3691

**Closed by pkozlowski-opensource** 2015-08-23 14:41 UTC
