### ISSUE TITLE
Give one strong reasons to remove prefixing "_" for private variables in component

### ISSUE THREAD

**Issue by hemanth-n-govindan** [angular/angular#32551] opened 2019-09-09 06:18 UTC
# 📚 Docs or angular.io bug report

### Description

 
I love and enjoy using "\_" for private declarations knowing its beauty and benefits. It keeps me reminding what are the properties exposed or not(public/private) while typing some lines in the middle, I can't go and check what's is it's definition, each time. And i don't want to.  And with respect to angular, I feel removing prefixing "_"  style guide for private variables in angular style doc just to "keep all cross platforms to be same" is not a great idea and this isn't a happy thing at least for me knowing its befits. Could you please justify this with reasons...

**Comment by sarunint** [comment] 2019-09-09 06:27
Well, style guide is just a guide. You don't have to follow it to every aspect. If you don't like it, just do it however you want.

**Comment by trotyl** [comment] 2019-09-09 06:42
> I feel removing prefixing "_" style guide for private variables in angular style doc

Are you serious? Before the removal Angular suggest **DON'T** prefix `_` before private properties.

https://v7.angular.io/guide/styleguide#properties-and-methods

**Comment by hemanth-n-govindan** [comment] 2019-09-09 09:58
@trotyl thank you so much for clarification. My be I read a wrong source. But "_" help in differentiating things better. Why this wasn't recommended in style guide?

**Comment by hemanth-n-govindan** [comment] 2019-09-09 10:00
> Well, style guide is just a guide. You don't have to follow it to every aspect. If you don't like it, just do it however you want.

Then it creates different practice across developers right?

**Comment by trotyl** [comment] 2019-09-09 10:07
> Why this wasn't recommended in style guide?

All of these preference rules have already been removed from Angular Style Guide doc, what's the issue about now?

**Comment by Orodan** [comment] 2019-10-04 19:35
What's the status of this issue :) ? 
From what I can see there is no more recommandation on property names in the current style guide version.

**Comment by trotyl** [comment] 2019-10-05 02:49
Duplicate of https://github.com/angular/angular/issues/30878

**Comment by rockument69** [comment] 2020-05-26 22:54
This issue should be closed. The current [Angular Coding Style Guide](https://angular.io/guide/styleguide) does not include use of underscores.

**Closed** 2021-04-07 22:23 UTC
Labels: P4, comp: docs, freq1: low, triage #1, type: bug/fix
