### ISSUE TITLE
Omitting @Output on a child components EventEmitter goes unnoticed by the compiler

### ISSUE THREAD

**Issue by nbnds** [angular/angular#45996] opened 2022-05-14 03:21 UTC
### Which @angular/* package(s) are the source of the bug?

compiler

### Is this a regression?

No

### Description

Create a minimal angular project with `ng new`
Create a child component with a button triggering a function which should emit an event from an EventEmitter.
`<input type="button" value="press to send event up" (click)="sendEventUp()" />`
Add handling function to the child's `*.ts` file like this:
```
  sendEventUp() {
    this.messageEvent.emit();
    console.log('[DEBUG.CHILD] sent some event up');
  }
```
Declare EventEmitter in the same file.
When declaring the EventEmitter, **don't** add `@Output` decorator to it, like this: 
`messageEvent = new EventEmitter();`
In the parent component's template insert the child component's tag with event handler like this 
`<app-child (messageEvent)="gotEventFromChild()"></app-child>`

The issue is that when I omit the `@Output` decorator the application compiles without any error or hint, and gets executed.  However  the child's event is not being catched in the parent component.  When we add the decorator the event is catched in the parent component as expected and handling function is executed. 

The problem is, that his behaviour goes unnoticed, regardless any strict compiler options. It can be easy to forget adding the decorator, and then you just introduce a severe functional bug into your application. 

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-smqkao?file=src/app/child/child.component.ts

### Please provide the exception or error you saw

```true
The parents handler function is not executed, but the application compiles and runs just as nothing would be wrong. You have no effective means to find such a bug. 

I got suggestions like to write linter rules or unittests, but i don't think its a right way to ensure syntactical correctnes of a program. The compiler should to so.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular 13.2.0 / 13.3.5
Node 16.x
```

### Anything else?

I'm not sure, may be it has some relation with https://github.com/angular/angular/issues/43603

**Comment by JoostK** [comment] 2022-05-14 14:32
Yep, this has the same root cause as #43603; see https://github.com/angular/angular/issues/43603#issuecomment-927547257 for why it behaves this way. Closing as a duplicate, as the situations are the same as far as the compiler is concerned.

**Closed by JoostK** 2022-05-14 14:32 UTC
Labels: comp: core, core: inputs / outputs
