### ISSUE TITLE
Angular PWA service worker doesn't cache every resource listed in ngsw.json

### ISSUE THREAD

**Issue by autozoom** [angular/angular#30351] opened 2019-05-09 10:59 UTC
# 🐞 bug report

### Affected Package
@angular/pwa
@angular/service-worker

### Description
Service worker doesn't cache every resource listed in ngsw.json

## 🔬 Minimal Reproduction
* point your browser to https://dev16.softech-engineering.it/ng-garsiawe/portalecittadino
* open dev tools and check application/cache/cache storage
* check that the last cached resource (2nd page) is /ng-garsiawe/portalecittadino/favicon.ico even though ngsw.json also lists
"/ng-garsiawe/portalecittadino/gwe-config.json",
        "/ng-garsiawe/portalecittadino/index.html",
        "/ng-garsiawe/portalecittadino/main.a48c95db24f0e317b0aa.js",
        "/ng-garsiawe/portalecittadino/polyfills.2c7891f63f8f33a9f8df.js",
        "/ng-garsiawe/portalecittadino/runtime.420a3349ae710ee45d9e.js",
        "/ng-garsiawe/portalecittadino/styles.88e45fc7e093019f4ebe.css"

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 7.3.8
Node: 10.15.0
OS: win32 x64
Angular: 7.2.12
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.12.4
@angular-devkit/build-angular      0.12.4
@angular-devkit/build-ng-packagr   0.12.4
@angular-devkit/build-optimizer    0.12.4
@angular-devkit/build-webpack      0.12.4
@angular-devkit/core               7.2.4
@angular-devkit/schematics         7.3.8
@angular/cdk                       7.3.7
@angular/cli                       7.3.8
@angular/material                  7.3.7
@angular/pwa                       0.12.4
@angular/service-worker            7.2.15
@ngtools/json-schema               1.1.0
@ngtools/webpack                   7.2.4
@schematics/angular                7.3.8
@schematics/update                 0.13.8
ng-packagr                         4.7.1
rxjs                               6.4.0
typescript                         3.2.4
webpack                            4.28.4
</code></pre>

**Anything else relevant?**
tested with Chrome 74.0.3729.131 64 bit

Please notice that everything works as expected in my local development environment when I serve the app with 
http-server -p 18080 -c-1 .\dist\portale-cittadino\

**Comment by smarth55** [comment] 2019-05-09 14:40
you might want to check that you do not have 'Disable Cache' enabled in dev tools.

**Comment by autozoom** [comment] 2019-05-09 14:49
> 
> 
> you might want to check that you do not have 'Disable Cache' enabled in dev tools.

Thanks. 
No, cache is enabled and most of the resources are cached, but not all.
Were you able to reproduce it?

**Comment by smarth55** [comment] 2019-05-09 15:17
On second visit to your site, I get this:
<img width="791" alt="Screen Shot 2019-05-09 at 11 16 34 AM" src="https://user-images.githubusercontent.com/4282223/57465142-ffb9ef80-724b-11e9-8e00-adddebd14670.png">

**Comment by autozoom** [comment] 2019-05-09 15:29
smarth55 thanks
Can you confirm that, for example, gweconfig.json is not cached?

You can check with dev tools:
![ccc](https://user-images.githubusercontent.com/15321669/57465960-f8acd480-727f-11e9-9d10-a440334a1a0e.png)

**Comment by smarth55** [comment] 2019-05-09 16:31
It looks like what is happening is that, on first load, the browser is getting the core assets and putting them in the browser cache before the service worker has started up. Then when the service worker is running, it sees that those assets are in the browser cache and grabs them from there instead of refetching them and putting them in the Caches.

**Comment by SvenBudak** [comment] 2019-05-09 16:42
Oh nice! i was opening this github because i want to open a ticket for exactly this problem. I am currently developing an app: https://pixer.app/ when you add it as PWA and try to toggle the bookmark function of a post, it will make a new GET on the icon that switchs. But the whole assets folder is listed in the config. so i am wondering why its not cached...

**Comment by autozoom** [comment] 2019-05-10 08:35
Weird thing is that if I remove the "/ng-garsiawe/p1/index.html" line from the ngsw.json then it is able to cache the resources following it, but if I put "/ng-garsiawe/p1/index.html" back than it cannot cache the entries that follow.

**Comment by gkalpak** [comment] 2019-05-13 10:00
I just tried this out and I am getting the following error in the console:

```
Uncaught (in promise) TypeError: Failed to register a ServiceWorker: A bad HTTP response code (404) was received when fetching the script.
```

Also, the fact that it works in your local environment indicates there is something wrong (or incorrectly/incompatibly configured in your prod environment).

##
I am going to close this, since we don't have a working reproduction to look at, but happy to re-open and investigate, if you can provide one.

BTW, if you haven't already, you should check out [Debugging the Angular service worker][1].

[1]: https://angular.io/guide/service-worker-devops#debugging-the-angular-service-worker

**Closed by gkalpak** 2019-05-13 10:00 UTC
Labels: comp: service-worker, freq2: medium, severity3: broken, type: bug/fix

**Comment by autozoom** [comment] 2019-05-13 13:33
There was indeed an error in main.ts
Service worker support is broken with Angular 7.x so I had added this to main.ts:

`platformBrowserDynamic().bootstrapModule(AppModule).then(() => {
    if ('serviceWorker' in navigator && environment.production) {
        navigator.serviceWorker.register('./ngsw-worker.js');
    }
}).catch(err => console.log(err));`

but I was missing the "." before /ngsw-worker.js

With this, now you don't get the 
`Uncaught (in promise) TypeError: Failed to register a ServiceWorker: A bad HTTP response code (404) was received when fetching the script.` error in the console and it now works in my local environment using Apache (earlier it used to work but only with http-server).

But, again, going to 
[https://dev16.softech-engineering.it/ng-garsiawe/portalecittadino](url)
it only loads a bunch of resources (check, on Chrome, with dev tools/application/cache/cache storage) , namely

/ng-garsiawe/portalecittadino/2.ae2fef8851c345685fad.js 
/ng-garsiawe/portalecittadino/3.88fd904c86644d9c22d4.js 
/ng-garsiawe/portalecittadino/7.be96bfcb180cc4c834c0.js
/ng-garsiawe/portalecittadino/8.5deae9521066aff7c637.js
/ng-garsiawe/portalecittadino/9.b712b6ff4ea24d1a1d2f.js
/ng-garsiawe/portalecittadino/assets/.gitkeep_1
/ng-garsiawe/portalecittadino/assets/fonts/icomoon.eot
/ng-garsiawe/portalecittadino/assets/fonts/icomoon.svg
/ng-garsiawe/portalecittadino/assets/fonts/icomoon.ttf
/ng-garsiawe/portalecittadino/assets/fonts/icomoon.woff
/ng-garsiawe/portalecittadino/favicon.ico

even though the ngsw.json file lists way more resources (you can check in dev tools/network tab).

Strangely enough, if I manually delete the "/ng-garsiawe/portalecittadino/assets/gwe-config.json" line from the ngsw.json file (you cannot do that as you need access to the deployed app), then all the resources get loaded correctly.
But, in fact, the gwe-config.json has not access rights issue (check yourself pointing your browser to [https://dev16.softech-engineering.it/ng-garsiawe/portalecittadino/assets/gwe-config.json](url))

This is driving me crazy

**Comment by gkalpak** [comment] 2019-05-13 20:27
It seems that the hash of the `gwe-config.json` file coming from the server is not the same as the `gwe-config.json` that was hashed at build time. It sounds like the file is being transformed at some point.

(In case it helps, I've seen this happen by FTP clients normalizing newlines, servers/proxies optimizing files or servers modifying files based on environment variables.)

In any case, you need to ensure that the content of the files whose hashes are listed in the generated `ngsw.json` remain the same when served in production.

**Comment by autozoom** [comment] 2019-05-14 10:13
> 
> 
> It seems that the hash of the `gwe-config.json` file coming from the server is not the same as the `gwe-config.json` that was hashed at build time. It sounds like the file is being transformed at some point.
> 
> (In case it helps, I've seen this happen by FTP clients normalizing newlines, servers/proxies optimizing files or servers modifying files based on environment variables.)
> 
> In any case, you need to ensure that the content of the files whose hashes are listed in the generated `ngsw.json` remain the same when served in production.

Yes @gkalpak that was indeed the problem thank you!
gwe-config.json is a configuration file, thay I **need** to modify for every customer as it contains the rest endpoint urls.
But I cannot do that because it would invalidate its hash calculated at build time.
Now I need a strategy to be able to edit this config file on the deployed app.

**Comment by gkalpak** [comment] 2019-05-14 12:36
:+1:
Maybe you could add it in `urls` (and serve it with appropriate cache headers): https://angular.io/guide/service-worker-config#resources

**Comment by autozoom** [comment] 2019-05-15 13:41
Hello, I am trying to cache gwe-config.json by putting it in the "dataGroups" section of ngsw-config.json:

`"dataGroups": [
    {
      "name": "config",
      "urls": [
        "/**/gwe-config.json"
      ],
      "cacheConfig": {
        "strategy": "performance",
        "maxSize": 100,
        "maxAge": "10d"
      }
    }
  ]`

this gets translated (in the ngsw.json file) to
`"dataGroups": [
    {
      "name": "config",
      "patterns": [
        "\\/(?:.+\\/)?gwe-config\\.json"
      ],
      "strategy": "performance",
      "maxSize": 100,
      "maxAge": 864000000,
      "version": 1
    }
  ]`

I moved the gwe-config.json up one folder so it doesn't belong to the /assets folder anymore.
With this new configuration, the file is not cached by the service-worker.
You can check it by going to dev-tools/application/cache/cache storage and see that a new section called **ngsw:1:data:dynamic:config:cache** has appeared, but it's empty

Please notice that even if I change 
`"urls": [
        "/**/gwe-config.json"
      ],`
to
`"urls": [
        "/gwe-config.json"
      ],`
it doesn't get cached as well.

Any hint is greatly appreciated.

**Comment by gkalpak** [comment] 2019-05-15 17:45
@autozoom, I see `gwe-config.json` being cached correctly 😕 

##
Regarding why `/ngsw/state` doesn't work:
It seems to be a bug in how we detect navigation to `/ngsw/state`, when the SW registration scope is not `/`: https://github.com/angular/angular/blob/79d4b16f8a87f13b0acc0c26e3c9227d649ed42d/packages/service-worker/worker/src/driver.ts#L187 

Can you, please, file a issue about that?

**Comment by autozoom** [comment] 2019-05-16 09:59
@gkalpak issue added

regarding my other caching problem:
I've tried with the Vivaldi browser (deeply Chrome-based) and, indeed, it cached the gwe-config file in the dynamic area of the cache.
But then I changed the file on the server, hit CTRL-F5 to reload everything (expiry time is set to performance/10 days) and since then nothing works anymore.
I am not able to have the browser cache that gwe-config file, no matter what I try.
This is the same behaviour I am having with Chrome.

I really don't know how to fix this.

**Comment by gkalpak** [comment] 2019-05-16 14:35
Thx for creating the issue.
Regarding `gwe-config.json`, I'm afraid there is not much I can help with if I can't get my hands on a minimal reproduction 😞.

**Comment by autozoom** [comment] 2019-05-16 14:57
> 
> 
> Thx for creating the issue.
> Regarding `gwe-config.json`, I'm afraid there is not much I can help with if I can't get my hands on a minimal reproduction 😞.

@gkalpak even though the dev tools don't reflect the expected behaviour anymore, it seems to me that the app behaves in the right way anyway.
I mean, it works even when offline, it can be installed as a native app in Android, it obeys to the caching policies...have you ever experienced dev tools not reflecting the correct state of the app?

**Comment by gkalpak** [comment] 2019-05-16 15:13
Strange. No, I haven't seen that. (Maybe a Vivaldi issue?)

**Comment by autozoom** [comment] 2019-05-16 15:31
> 
> 
> Strange. No, I haven't seen that. (Maybe a Vivaldi issue?)

The same in Chrome. I will record a video of what I mean and show it to you, just for the sake of curiosity.

**Comment by autozoom** [comment] 2019-05-17 09:16
Don't want to bother you, but take a look at this, I am not sure it is the expected behaviour

[https://drive.google.com/open?id=1myVcE4Wt8eRdD_Dq8DW36o4SA_ilZ5qS](url)

**Comment by gkalpak** [comment] 2019-05-17 11:35
Here is what happens:

1. `gwe-config.json` is not cached on first load:
    This happens, because the file is requested before the SW has been loaded. Since it is a URL pattern in a dataGroup (not a hashed resource in an assetGroup), the SW cannot fetch it from the server and cache it. What the Sw does, is check all incoming responses and if a response's corresponding request URL matches the pattern, _then_ it caches it.
    On the second load, the SW has already been activated, so it handles all app requests (including the one for `gwe-config.json`). Thus, it can cache it and later serve it offline.

2. https://dev16.softech-engineering.it/ng-garsiawe/portalecittadino does not work offline:
    This happen because that URL is outside of the scope of the SW (https://dev16.softech-engineering.it/ng-garsiawe/portalecittadino/ <-- notice the trailing `/`). When online, the server redirects the client to the URL with the trailing slash and then the SW can take over, but when offline you have to explicitly go to the correct URL.
    See also the [MDN docs][1] for more info on registration scope.

[1]: https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerContainer/register

**Comment by autozoom** [comment] 2019-05-17 12:18
@gkalpak very clear explanation, thanks a lot!
Regarding the first point: `gwe-config.json` is a mandatory file but I cannot add it to assetGroup because I need to modify it in production (it stores customer-dependent configurations) and it would invalidate its hash.
And I cannot tell the customer to load the app twice to have it properly cached.
Do you have a suggestion to fix this?

Thanks again

**Comment by gkalpak** [comment] 2019-05-17 13:49
The only work-around I can think of is to re-request the file once more after the SW has taken over (only for the purpose of getting it cached:

```ts
navigator.serviceWorker.ready.then(() => fetch('gwe-config.json'));
```

**Comment by autozoom** [comment] 2019-05-17 14:00
thanks again

I wonder if I'm the only one that needs this, it seems to me that the need to cache a config file that must be modified after being built and deployed should be quite common but maybe I am missing something big.
