### ISSUE TITLE
Child event is being passed into parent EventEmitter

### ISSUE THREAD

**Issue by kevupton** [angular/angular#22671] opened 2018-03-09 02:23 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
I have component `PARENT` with an `EventEmitter` bound to change,
In this `PARENT` component I have an `ng-container` which is placing a template containing a `select` element. 

Now whenever this `select` element changes, it triggers this parent's `change : EventEmitter`.

Note that this `select` element does not actually have anything bound to the `(change)`

I am not sure if this is intentional or not. That the event is able to call a parent `EventEmitter` like that.

## Expected behavior
I would expect that the `change : EventEmitter` is not called inside the `PARENT` container when the select element changes.

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-gitter-jltjx8

## What is the motivation / use case for changing the behavior?
This is unexpected, and unclear whether this should be happening. It makes it confusing for degree of separation from the component to their children.

## Environment

<pre><code>
Angular version: 5.2.4

Browser:
- [X] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by Toxicable** [comment] 2018-03-09 02:35
I'm sorry but reported issues require a StackBlitz reproducing the problem.

If this issue persists, please create a StackBlitz using this template and describe the difference between the expected and current behavior and create a new issue: https://stackblitz.com/fork/angular-gitter

**Comment by kevupton** [comment] 2018-03-29 00:38
Here @Toxicable
https://stackblitz.com/edit/angular-gitter-jltjx8

**Comment by ericmartinezr** [comment] 2018-03-29 01:17
See https://github.com/angular/angular/issues/4059

**Comment by kara** [comment] 2020-05-27 21:55
@kevupton Yep, this is confusing behavior that we should address. As @ericmartinezr mentioned, we have an existing issue tracking the bug here: https://github.com/angular/angular/issues/4059.

I'm closing this as a dupe so we have one source of truth for tracking progress.

**Closed by kara** 2020-05-27 21:55 UTC
Labels: comp: core, core: event listeners, core: inputs / outputs, freq1: low, severity3: broken, type: confusing
