### ISSUE TITLE
Passing values between components, ng-control, ngFormModel and ng-model

### ISSUE THREAD

**Issue by danicomas** [angular/angular#3804] opened 2015-08-24 11:51 UTC
1) Could I do something like this?

```js
@Component({selector: 'input-text', properties: ['controlPath: control', 'value: data']})
@View({
  template: `
    <div class="form-group">
      <label [attr.for]="controlPath">{{controlPath | uppercase}}</label>
      <input type="text" class="form-control" [id]="controlPath" [(ng-control)]="controlPath" [placeholder]="controlPath" [(ng-model)]="value">
      <show-error control="{{controlPath}}" [errors]="['required']"></show-error>
    </div>
  `,
  directives: [ShowError, FORM_DIRECTIVES]
})
class InputText {
  controlPath: string;
  value: string;

  constructor() { }
}
```

```js
@Component({
  selector: 'my-app',
  viewBindings: [HTTP_BINDINGS]
})
@View({
  template: 
  `<form (ng-submit)="onSubmit(form)" [ng-form-model]='form'>
    <img [src]="data.avatar_url ? data.avatar_url : ''" width="100" height="100"/>
    <input-text control="name" [data]="data.name"></input-text> 
    <input type="submit" class="btn btn-primary"/>
  </form>`,
  directives: [FORM_DIRECTIVES, ShowError, NgIf, InputText]
})
```

<b>Now the input text crash on [(ng-control)]. The error is the following:
EXCEPTION: No provider for ControlContainer! (function (cd, renderer, elementRef) { -> NgControl -> $__0 -> ControlContainer)<b>

2) Other way would be do something like this:

```js
<input-text ng-control="name" [(ng-model)]="data.name"></input-text>
```

But I don't know if it is possible.

**Comment by mhevery** [comment] 2015-08-25 18:23
1) looks reasonable to me, @vsavkin Thoughts?

Could you create a http://plnkr.co/edit/tpl:BrUl7z1vvZBGWBfSGS8D?p=preview for easy repro?

**Comment by danicomas** [comment] 2015-08-27 07:52
@mhevery here the plunker:
http://plnkr.co/edit/5j4kMAlnV5dBstDxG6ou?p=preview

You could see that [(ng-control)]="controlPath" is the problem which causes the error. If you go to the console in dev tools you could see the details.

**Comment by mhevery** [comment] 2015-08-31 18:29
`[(ng-controll)]` is fine here is the working http://plnkr.co/edit/XIJwnPHh5o1MpalxsZRq?p=preview

The issue is:
- missing `FORM_BINDINGS`
- missing `<form>` around the `<input>`

**Comment by mhevery** [comment] 2015-08-31 18:31
Closing in favor of: https://github.com/angular/angular/issues/3919

**Closed by mhevery** 2015-08-31 18:31 UTC
Labels: comp: core/forms, effort1: easy (hour), P2: required, type: bug

**Comment by danicomas** [comment] 2015-09-01 08:01
But I don't want another ```<form>```. I want to create a component for input text, select, ... and adding them in the first component (form).  @mhevery Is it possible?

**Comment by mmrath** [comment] 2015-09-23 04:31
Yes another form is unwanted. @danicomas @mhevery  you got any workaround?

**Comment by mhevery** [comment] 2015-09-23 04:46
@vsavkin can you comment on how we could create a `<input>` without  a `<form>`. Can we demarcate the container in some other way?

**Comment by danicomas** [comment] 2015-09-23 07:31
We should reopen this issue @mhevery. Isn't it?

**Comment by gdi2290** [comment] 2015-09-23 08:11
imho I think what you're looking for is `ng-form` for InputText
http://plnkr.co/edit/bFNqDrH0akyZ4ua0vzHz?p=preview
```
@Component({selector: 'input-text', properties: ['controlPath: control', 'value: data']})
@View({
  template: `
    <div ng-form class="form-group">
      <label [attr.for]="controlPath">{{controlPath | uppercase}}</label>
      <input type="text" class="form-control" [id]="controlPath" [(ng-control)]="controlPath" [placeholder]="controlPath" [(ng-model)]="value">
      <show-error control="{{controlPath}}" [errors]="['required']"></show-error>
    </div>
  `,
  directives: [ShowError, FORM_DIRECTIVES]
})
class InputText {
  controlPath: string;
  value: string;

  constructor() { }
}
```
there's also a mix between template-driven forms and model-driven forms which is totally fine. I can elaborate more on why this is the case and how we reached this point but that also takes a bit of effort so I'll only do so if you need more explanation

**Comment by danicomas** [comment] 2015-09-23 10:47
@gdi2290 and why the console.log doesn't return the modified value?

**Comment by mmrath** [comment] 2015-09-25 08:49
I think the modified value need to be propagated to the parent component somehow. Probably write something custom like ng-model, I am not too sure though. 

What I am trying to do is I think related to this. I have posted some sample code and question on SO at http://stackoverflow.com/questions/32778163/creating-dynamic-forms-in-angular2-using-metadata

@danicomas could you see if you are also trying to have something like what I have posted in the SO post?

I think a lot of people would be trying to solve this problem. @mhevery @gdi2290 @vsavkin Any pointers to solve this is much appreciated.

**Comment by gdi2290** [comment] 2015-09-25 16:08
I updated the example so it's easier to see. The problem is that you're pushing data into `<input-text>` but you're not pulling data out of it. `ng-model` sets up two-way data binding since you're trying to set this up similar to how you would in ng1. You're using `ng-model` in  `<input-text>` but that's setting up the binding to the value property of that component not it's parent. 


http://plnkr.co/edit/bFNqDrH0akyZ4ua0vzHz?p=preview

**Comment by mmrath** [comment] 2015-09-28 00:09
I just have found solution for my case. http://plnkr.co/edit/N1W8XqIS8ykU1Vsm7hjf?p=preview
The answer in SO post helped me.

**Comment by danicomas** [comment] 2015-09-28 07:35
@gdi2290 Yes, It is the problem we don't know the child value in the parent component. I think that it should work. What do you think? @gdi2290 @mhevery

**Comment by danicomas** [comment] 2015-09-28 07:45
@mmrath your solution is working well but I don't know why if I add [click]="onSubmit(form)" on <button type="submit" the console after click on the button print two equal logs :S

**Comment by gdi2290** [comment] 2015-09-28 08:00
you made a small typo. It's `(click)="onSubmit(form)"` rather than `[click]="onSubmit(form)"` which is why you're seeing two logs rather than one

**Comment by danicomas** [comment] 2015-09-28 08:03
Nice @gdi2290 . What do you think about @mmrath solution?

**Comment by danicomas** [comment] 2015-09-28 08:25
Nice @gdi2290

**Comment by danicomas** [comment] 2015-11-02 18:35
Updated @mmrath plnkr http://plnkr.co/edit/IdgoEJqpIBmr16Ca1zFI?p=preview

but it is not solved yet. @mhevery @gdi2290

**Comment by danicomas** [comment] 2015-11-03 08:18
Opened a new issue to update the valid field to true in the form. https://github.com/angular/angular/issues/5087
