### ISSUE TITLE
Angular 2 RC 4 Rxjs Bundles

### ISSUE THREAD

**Issue by robinkedia** [angular/angular#9940] opened 2016-07-10 07:07 UTC
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
While bootstraping the application, I see system is loading individual rxjs files. (100+ calls)

**Expected/desired behavior**
Shouldn't it load RXJS bundle same like other angular libraries?
![rxjs calls](https://cloud.githubusercontent.com/assets/10397211/16712145/f31dd0d6-46af-11e6-98f1-289411c448ea.PNG)

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
![rxjs calls](https://cloud.githubusercontent.com/assets/10397211/16712144/ea0daa0c-46af-11e6-8f3e-1dae777833d6.PNG)

 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5 | Dart]

**Comment by fknop** [comment] 2016-07-10 11:43
I think it's up to you to bundle your application as you wish.

**Comment by LukeNZ** [comment] 2016-07-10 20:45
Dupe of #9359? But yeah, this needs to be fixed. Not all of us have the time to invest in the labyrinth-themed maze that is package bundling just to achieve decent loading times in Angular 2.

**Comment by robwormald** [comment] 2016-07-10 22:52
> Not all of us have the time to invest in the labyrinth-themed maze that is package bundling just to achieve decent loading times in Angular 2.

For what its worth, the *reason* we don't bundle Rx for you is to not bring in 300KB+ of extra dependencies you may not need, which would of course increase your loading time.

This is non-trivial to solve to keep everyone happy, because like many things in angular2, we are optimizing for the future. Bundling is not going away and we will continue to optimize for the case that allows for smaller package sizes.

RxJS does currently ship a SystemJS bundle, it's the /bundles/Rx.js file, which would give you all of the dependencies angular needs as well as the entire Rx library.

**Closed by robwormald** 2016-07-10 22:52 UTC

**Comment by LukeNZ** [comment] 2016-07-11 00:56
Honestly, if the Rx.js umd bundling issue is solved specifically (as in #9359), then that eliminates many concerns. System.js seems to have the lowest barrier to entry and it works pretty well out of the box, which is great.

**Comment by Arlen22** [comment] 2017-02-23 19:16
But how do I bundle? I've been searching all day, and nobody actually explains how to actually make angular use the correct packages that I loaded via a bundle.

**Comment by LukeNZ** [comment] 2017-02-23 19:21
@Arlen22 Use @angular/cli

**Comment by Arlen22** [comment] 2017-02-23 19:23
Or how to load them via a bundle.
