### ISSUE TITLE
HttpClient not completing nested http observable

### ISSUE THREAD

**Issue by Eric-Larson** [angular/angular#20755] opened 2017-12-03 02:11 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
HttpClient requires a first() on the inner child requests to complete the observable and print out the result
```
import { HttpClient } from '@angular/common/http';

const result = this.http.get('https://jsonplaceholder.typicode.com/users').mergeMap((parents: any) => {
	const getParentChild = p => {
		return this.http.get('https://jsonplaceholder.typicode.com/users').first().map((c: any) => {
			return {
				parent: p,
				child: c
			}
		});
	};
	return Observable.forkJoin(parents.map(p => getParentChild(p)));
});

result.subscribe(results => {
	console.log(results);
});
```
## Expected behavior
When HttpClient is swapped out for Http, the result is printed out without using first()
```
import { Http } from '@angular/http';

const result = this.http.get('https://jsonplaceholder.typicode.com/users').map(res => res.json()).mergeMap((parents: any) => {
	const getParentChild = p => {
		return this.http.get('https://jsonplaceholder.typicode.com/users').map(res => res.json()).map((c: any) => {
			return {
				parent: p,
				child: c
			}
		});
	};
	return Observable.forkJoin(parents.map(p => getParentChild(p)));
});

result.subscribe(results => {
	console.log(results);
});

```

## Environment
<code>
Angular version: 5.0.3

**Comment by glendaviesnz** [comment] 2017-12-07 00:48
We get the same issue when nesting the http call in an @ngrx effect   - in this context use of concatMap with the effect doesn't work unless .take(1) or .first() is adding to http call.

**Comment by jcoutu-va** [comment] 2018-01-17 15:29
I would voice that this is a little more than inconvenient as it broke several of my interfaces for an existing app during a bug fix release.  It took longer to diagnose than I would like as it was passed over as the cause of the breakage.

**Comment by jongear** [comment] 2018-01-30 18:41
@Eric-Larson the `HttpClient` in angular 5 now applies res.json() for you. try removing this and see if it works

**Comment by Eric-Larson** [comment] 2018-02-07 14:51
@jongear The example using res.json() is the old Http module, not HttpClient.

**Comment by alxhub** [comment] 2020-05-29 20:47
Unable to confirm in my testing - nested requests with `mergeMap` -> `forkJoin` and without `first` work just fine.

In order to investigate this issue, we'll need a reproduction in the form of a stackblitz or Github repository.

**Comment by petebacondarwin** [comment] 2020-10-26 21:05
Closing due to a lack of reproduction.

**Closed by petebacondarwin** 2020-10-26 21:05 UTC
Labels: P4, comp: common/http, freq1: low, needs clarification, needs reproduction, triage #1, type: bug/fix
