### ISSUE TITLE
RouterLinkActive Causes Browser To Freeze When Inside NgFor

### ISSUE THREAD

**Issue by bmbell** [angular/angular#20995] opened 2017-12-13 23:20 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

There seems to be some sort of infinite loop occurring in the Angular code when a "routerLinkActive" directive is placed within an *ngFor container.  This loop completely locks up the browser and makes the application unusable.

## Expected behavior

The routerLinkActive directive should work inside an *ngFor construct.

## Minimal reproduction of the problem with instructions

http://plnkr.co/edit/Q7kzTjDMdehSVmQbSBNS

1. Go to the above plunkr
2. Observe that both routes work (click on the Path1 and Path2 links)
3. Go to src/app.ts
4. Add routerLinkActive="active" to the following line:
`<a *ngFor="let page of pages" [routerLink]="page.path" >{{page.name}}</a>`

Then when the plunkr refreshes, note that it completely locks up.  For my current application, it is completely locking up in an infinite loop.

## What is the motivation / use case for changing the behavior?

This makes my application unusable and I'll have to create a work-around rather than use the provided directive.

## Environment

<pre><code>
Angular version: 5.1.1

Browser:
- [x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by ziaulain** [comment] 2018-01-09 11:46
I am also having the same issue...

**Comment by ziaulain** [comment] 2018-01-09 11:51
@bmbell can you please share the work around?

**Comment by bmbell** [comment] 2018-01-09 12:06
@ziaulain In my above example, you can manually attach a CSS class called "active", and pass the object to a function, like this:

`<a *ngFor="let page of pages" [routerLink]="page.path [class.active]="isActivePage(page)" >{{page.name}}</a>`

Then, inject the angular router into your component:

`
import { Router } from "@angular/router";

...

constructor(private _router: Router) {
...
}
`

Finally, implement the "isActivePage" method in your component:

`
public isActivePage(page: any): boolean {
        
        let isActive = false;

        if (page.path === this._router.url) {
            isActive = true;
        }

        return isActive;
 }

`

Ideally, you would have the "page" defined as a type, rather than an "any" type, but this is just a simple example of what you can do...

**Comment by vfedoriv** [comment] 2018-05-12 20:02
I can reproduce it too.
But this fragment in my pet app, where routerLinkActive presented in *ngFor work ok:
```````
        <tr *ngFor="let owner of owners">
          <td class="ownerFullName"><a routerLink="/owners/{{owner.id}}" routerLinkActive="active"
                                       (click)="onSelect(owner)">{{owner.firstName}} {{owner.lastName}}</a></td> 
        </tr>
```````
In previous Angular versions (5.0) I had similar problems (infinite loop) when I tried start some tests for this component, but no problems in runtime. When I removed routerLinkActive="active" from html, tests worked ok.  In current Angular (5.2.5) tests work ok with routerLinkActive="active".

**Comment by mart2k** [comment] 2018-10-01 16:18
why is such a heavy bug still open?

**Comment by NeilAttewell** [comment] 2018-11-05 04:38
I'm having the same issue.

`ng --version

Angular CLI: 7.0.4
Node: 8.12.0
OS: linux x64
Angular: 7.0.2
... animations, cdk, common, compiler, compiler-cli, core, forms
... http, material, platform-browser, platform-browser-dynamic
... platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.10.4
@angular-devkit/build-angular     0.10.4
@angular-devkit/build-optimizer   0.10.4
@angular-devkit/build-webpack     0.10.4
@angular-devkit/core              7.0.4
@angular-devkit/schematics        7.0.4
@angular/cli                      7.0.4
@angular/language-service         5.2.11
@ngtools/webpack                  7.0.4
@schematics/angular               7.0.4
@schematics/update                0.10.4
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.19.1
`

**Comment by manklu** [comment] 2018-11-05 06:56
@bmbell Your problem is that your pages property returns a new array with each invocation. If you change that your sample works flawless.

https://stackblitz.com/edit/angular-omltpp?file=src%2Fapp%2Fapp.component.ts

@mart2k @NeilAttewell Reproduction?

**Comment by amitport** [comment] 2020-02-14 10:25
@manklu that's not a problem with the example code, `pages` getter should only be called once per traversal.

If angular does something else that is very surprising and such differences should be motivated and emphasized in beginners tutorials.
(https://en.wikipedia.org/wiki/Principle_of_least_astonishment).

**Comment by atscott** [comment] 2020-05-27 16:30
confirmed, still an issue in v9: https://stackblitz.com/edit/angular-ivy-wytcuh?file=src/src/app.ts

**Comment by spider9375** [comment] 2021-03-05 12:48
Page freezes in v11.2.4

**Comment by atscott** [comment] 2021-03-05 15:33
Adding `core` and `zones` labels. This is an issue with the getter because it always returns a new array reference, causing the `ngFor` to regenerate the elements, which then causes the `routerLinkActive` to check and mark itself dirty. Marking a component dirty marks all the parents dirty up to the root so that the next CD cycle works. The result is an infinite loop.

There's nothing that can be done in the `routerLink` to fix this at the moment. It could be solved by zoneless in the future and/or what @mhevery and I have discussed in the past for marking and checking a single component in the tree as dirty rather than the component and its parents up to the root.

**Comment by The-MAZZTer** [comment] 2021-03-06 04:18
I ran into this issue, same cause. Angular compares instances of objects to determine if they've changed when checking to see if it needs to regenerate the page. Sometimes I forget this and generate new instances every call for the routerLink value, which is what I and OP seem to have been doing to produce this bug.

I would say this is not technically a bug, but a side effect of the way Angular works.

However it should not result in an infinite loop The message that normally appears in the console when Angular detects that property values are improperly changing between fetches is expected instead. However, even in cases where the infinite loop does not happen, this message does not appear. I would say that and the infinite loop are the bugs here.

Another side effect of doing this if you DO NOT use routerLinkActive, is routerLink attributes will generate proper links in the browser status bar on hover, but clicking them does nothing.

**Comment by pkozlowski-opensource** [comment] 2022-05-11 10:07
Agree with @atscott and @The-MAZZTer that this issue is a side-effect of the Angular's change detection inner working. It can be reproduced without router, `markForCheck()` etc.: https://stackblitz.com/edit/angular-ivy-bptiwh?file=src%2Fapp%2Fapp.component.ts

```typescript
import { Component } from '@angular/core';

@Component({
  selector: 'my-app',
  template: `<button (click)="logClick()">{{getSomethingBad()}}</button>`,
})
export class AppComponent {
  getSomethingBad() {
    // Uncoment the lines below to freeze your browser...
    /* 
    Promise.resolve({ freeze: true }).then(() =>
      console.log('keep resolving....')
    );
    */
    return `BUM! Your browser got locked, you can't click me!`;
  }

  logClick() {
    console.log('I was clicked!');
  }
}
```
The crux of the issue is that each template render will schedule a new change detection cycle - the "culprit" is the `Promise.resolve({ freeze: true }).then(...)` call. 

I'm not sure if we can "fix" it once and for all in Angular (I suspect that similar scenario can be done in other frameworks - it is enough to keep scheduling "refresh" from a promise). But I do think that it would be beneficial to see if we can mitigate it on the router link somehow as it might be a scenario that people can accidentally bump into.

**Comment by cbou** [comment] 2023-06-21 08:52
I have the same issue with Angular 16.0.x

**Comment by jdegand** [comment] 2024-01-05 01:34
You can upgrade to Angular 17 and use `@for` and it should work.

**Comment by atscott** [comment] 2024-01-05 04:00
Closing as expected behavior

**Closed by atscott** 2024-01-05 04:00 UTC
Labels: type: bug/fix, freq1: low, area: router, area: core, area: zones, state: confirmed, core: change detection, router: directives, P3
