### ISSUE TITLE
Compiler should warn on bogus click handler expressions

### ISSUE THREAD

**Issue by ghost** [angular/angular#19859] opened 2017-10-22 20:29 UTC
We've all been puzzled by event handlers not firing because stuff like

```
(click)="someFunc"
```

is a valid expression. But you obviously meant `someFunc()`

**Comment by dawidgarus** [comment] 2017-10-23 15:09
`someFunc` could be a getter function and that could be intended behaviour.

**Comment by trotyl** [comment] 2017-10-23 15:29
I think it would be a valid feature request for https://github.com/mgechev/codelyzer, since it's just a coding style problem.

**Comment by notsonotso** [comment] 2017-10-23 17:33
@dawidgarus and if it's not a getter? clearly many cases can be covered through better validations. As it stands, code-in-templates is very bug prone.

**Comment by jasonaden** [comment] 2017-11-10 22:50
Closing as this is neither a bug report or feature request. Probably best to go into the codelyzer mentioned above.

**Closed by jasonaden** 2017-11-10 22:50 UTC
