### ISSUE TITLE
.focus() method on FormControl or access to native HTML element

### ISSUE THREAD

**Issue by pcroc** [angular/angular#13158] opened 2016-11-30 16:08 UTC
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
There seems to be no way to focus a FormControl.

**Expected behavior**
FormControl provides a *.focus()* instance method, or access to the native HTML element.

**What is the motivation / use case for changing the behavior?**
To give input focus to a control when it is invalid, as in the following example:

```typescript
if (!this.form.valid) {
  let invalid = <FormControl[]>Object.keys(this.form.controls).map(key => this.form.controls[key]).filter(ctl => ctl.invalid);
  if (invalid.length > 0) {
    // Give input focus to invalid[0]... how?
  }
  return false;
}
```

**Please tell us about your environment:**

* **Angular version:** 2.2.1

* **Browser:** N/A

* **Language:** TypeScript 2.0.3

**Comment by DzmitryShylovich** [comment] 2016-11-30 16:08
duplicate of https://github.com/angular/angular/issues/12463

**Comment by kara** [comment] 2017-02-10 19:32
Closing as a dupe of #12463

**Closed by kara** 2017-02-10 19:32 UTC
Labels: comp: forms, type: feature

**Comment by pcroc** [comment] 2017-02-16 16:57
Hi @kara I see #12463 was closed because "a relatively straightforward API already exists".

Please can you show how I could give focus to an invalid form control? Thanks.

**Comment by sakiv** [comment] 2017-08-06 05:21
See the sample I provided in #12463 where you can attach both, i.e. FormControl and ElementRef, on same element and use the API.

**Comment by JunusErgin** [comment] 2017-11-21 13:01
As long, as Angular doesn't provide this functionality, i manually added it:

Add the following code over your component:
```
const originFormControlNgOnChanges = FormControlDirective.prototype.ngOnChanges;
FormControlDirective.prototype.ngOnChanges = function () {
    this.form.nativeElement = this.valueAccessor._elementRef.nativeElement;
    return originFormControlNgOnChanges.apply(this, arguments);
};

const originFormControlNameNgOnChanges = FormControlName.prototype.ngOnChanges;
FormControlName.prototype.ngOnChanges = function () {
    const result = originFormControlNameNgOnChanges.apply(this, arguments);
    this.control.nativeElement = this.valueAccessor._elementRef.nativeElement;
    return result;
};

```

Now you can just implement it your way:

```
if (!this.form.valid) {
  let invalid = <FormControl[]>Object.keys(this.form.controls).map(key => this.form.controls[key]).filter(ctl => ctl.invalid);
  if (invalid.length > 0) {
     invalid[0].nativeElement.focus();
  }
  return false;
}
```

In my case, it worked out of the box. However, Typescript complained because it doesn't know nativeElement. So i did it the following way:

```
        if (invalid.length > 0) {
            let invalidElem: any = invalid[0];
            invalidElem.nativeElement.focus();
        }
```

I hope that I could help someone ;-)

**Comment by pooshonbanerjee** [comment] 2018-06-21 16:56
I am a novice, trying to learn Angular, and the more I try to learn the more I find out complexities. I am still trying to figure out why Angular was deliberately made complex.
I came here to see if there is a way to set focus to a textbox, I am not calling it FormControl because to the user, it is just a text box, and he expects the cursor to blink inside that box when a new box appears on the page asking him to type something.
Now, something as simple as  ....

`document.getElementById("myBox").focus();`

... needs an API.

May be I don't understand this because I am a novice, may be there was a genuine reason it was built this complicated.

**Comment by Remco75** [comment] 2018-10-02 10:06
> let invalidElem: any = invalid[0];

As a simpler solution for this problem I created a directive to be placed on the form element.

`import { Directive, HostListener, ElementRef} from '@angular/core';

@Directive({
  selector: '[focusFirstInvalidField]'
})
export class FocusFirstInvalidFieldDirective {

  constructor(private el: ElementRef) { }

  @HostListener('submit', ['$event'])
  onFormSubmit() {
    const invalidElements = this.el.nativeElement.querySelectorAll('.ng-invalid');
    if (invalidElements.length > 0) {
      invalidElements[0].focus();
    }
  }
}`

**Comment by JunusErgin** [comment] 2018-10-17 12:15
@Remco75 Your solution looks awesome! It's sad to see that the Angular Core team just ignores this issue... :-(

**Comment by jburtondev** [comment] 2018-10-23 14:42
**This works for me.**   Not the most elegant solution, but given the constraints in Angular we are all experiencing for this particular task, it does the job. 

```
scrollTo(el: Element) {
    el.scrollIntoView({ behavior: 'smooth' });
}

scrollToError(): void {
   const firstElementWithError = document.querySelector('.ng-invalid');
   this.scrollTo(firstElementWithError);
}

async scrollIfFormHasErrors(form: FormGroup): Promise <any> {
  await form.invalid;
  this.scrollToError();
}
```

This works, allowing you to evade manipulating the DOM. It simply goes to the first element with `ng-invalid` on the page through the `document.querySelector()` which returns the first element in the returned list. 

To use it: 
```
this.scrollIfFormHasErrors(this.form).then(() => {
  // Run any additional functionality if you need to. 
});
```

**Comment by tarang-smartsense** [comment] 2018-12-08 10:44
> As long, as Angular doesn't provide this functionality, i manually added it:
> 
> Add the following code over your component:
> 
> ```
> const originFormControlNgOnChanges = FormControlDirective.prototype.ngOnChanges;
> FormControlDirective.prototype.ngOnChanges = function () {
>     this.form.nativeElement = this.valueAccessor._elementRef.nativeElement;
>     return originFormControlNgOnChanges.apply(this, arguments);
> };
> 
> const originFormControlNameNgOnChanges = FormControlName.prototype.ngOnChanges;
> FormControlName.prototype.ngOnChanges = function () {
>     const result = originFormControlNameNgOnChanges.apply(this, arguments);
>     this.control.nativeElement = this.valueAccessor._elementRef.nativeElement;
>     return result;
> };
> ```
> Now you can just implement it your way:
> 
> ```
> if (!this.form.valid) {
>   let invalid = <FormControl[]>Object.keys(this.form.controls).map(key => this.form.controls[key]).filter(ctl => ctl.invalid);
>   if (invalid.length > 0) {
>      invalid[0].nativeElement.focus();
>   }
>   return false;
> }
> ```
> In my case, it worked out of the box. However, Typescript complained because it doesn't know nativeElement. So i did it the following way:
> 
> ```
>         if (invalid.length > 0) {
>             let invalidElem: any = invalid[0];
>             invalidElem.nativeElement.focus();
>         }
> ```
> I hope that I could help someone ;-)

In my case I have 

```
<mat-radio-group formControlName="type">
                        <mat-radio-button *ngFor="let instituteType of instituteTypes"
                                          [value]="instituteType.value">
                            {{instituteType.display}}
                        </mat-radio-button>
                    </mat-radio-group>
```
now 
           ` this.control.nativeElement = this.valueAccessor._elementRef.nativeElement;`
gives me an error 
**Cannot read property 'nativeElement' of undefined**

any help??

**Comment by tarang-smartsense** [comment] 2018-12-18 15:20
> Unfortunately it does not work with radio buttons as it does not have the `ctl.invalid` field. In my case, i always skip it. You could try to figure out how they store the valid /invalid state in the radio btn element or skip it.

yes I already skip this 
instead of 
```
if (invalid.length > 0) {
            let invalidElem: any = invalid[0];
            invalidElem.nativeElement.focus();
        }
```
what I did was
```
if (invalid.length > 0) {
            const invalidElem: any = invalid[0];
            if (invalidElem.nativeElement) invalidElem.nativeElement.focus();
        }
```

**Comment by logic01** [comment] 2019-06-19 15:04
For anyone who is still following.

I have created a new feature request so we can push for this feature again since it was closed so long ago with insufficient reasoning.

https://github.com/angular/angular/issues/31133

**Comment by schtrym** [comment] 2019-07-26 05:13
Hi,

I agree with you that it should be part of the API.

Here is my workaround to implement a vertical focus switch in a mat-table with form array. Hope it can help someone...

In my template, I added 
* a template variable for each input
* 2 custom attributes be specify the row and the column

```html
<input matInput
    ...
    #scoreInput
    [attr.score-row]="index"
    [attr.score-col]="periodIndex">
```

In the component, I've used `@ViewChildren` to get a list of each input (ElementRef).

```javascript
  @ViewChildren('scoreInput')
  private scoreInputs: QueryList<ElementRef>;
```
When my data are saved (one at a time), I store the updatedRow and the updatedColumn in a private variable of my component.
```javascript
  private _updatedRow: number;
  private _updatedCol: number;
```

then I use those variable and the custom template attributes to compute my next focused input.
```javascript
  private _calculateFocus() {
    // Use set timeout to be sure that the focus is not lost after datasource update.
    setTimeout(() => {
      this.scoreInputs.forEach((item, index) => {
        const scoreColAttributeValue = item.nativeElement.getAttributeNode('score-col').value;
        const scoreRowAttributeValue = item.nativeElement.getAttributeNode('score-row').value;
        if (scoreColAttributeValue == this._updatedCol && scoreRowAttributeValue == this._updatedRow + 1) {
          item.nativeElement.focus();
        }
      });
    }, 0);
  }
```
