### ISSUE TITLE
ngUpgrade: Angular dependencies of downgraded Angular service not receiving providers from parent module

### ISSUE THREAD

**Issue by AndrewPa** [angular/angular#25138] opened 2018-07-25 20:57 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Description
An Angular service "A" has another Angular service "B" injected. Using `downgradeInjectable`, service "A" is downgraded and registered as a factory:

```
angular
  .module('myModule)
  .factory('serviceA', downgradeInjectable(ServiceA));
```
It is now available to be injected in a component I upgraded and that works normally without `serviceA` injected. Unfortunately, I encounter this:

```
Error: StaticInjectorError(AppModule)[ServiceB -> HttpClient]: 
  StaticInjectorError(Platform: core)[ServiceB -> HttpClient]: 
    NullInjectorError: No provider for HttpClient!
```

The problem is, I already imported the `HttpClientModule` in `AppModule`.

```
  imports: [
    BrowserModule,
    HttpClientModule,
   ...
]
```

I think this is an edge case of sorts, but I'm not certain.

## Environment
Angular 1.5.11 running in Angular 6.0.6 "host" using ngUpgrade.

**Comment by gkalpak** [comment] 2018-07-25 21:19
It is not clear from the description what exactly you are doing.
In order to investigate this, we need a StackBlitz reproducing the problem. You can use [this template][1] as a starting point.

[1]: https://stackblitz.com/fork/ngupgradestatic-playground

**Comment by AndrewPa** [comment] 2018-07-25 21:54
@gkalpak 
(Here you go)[https://stackblitz.com/edit/ngupgradestatic-playground-vgyg71?file=ng2%2Fversion-stamp.component.ts]

**Comment by gkalpak** [comment] 2018-07-26 08:33
Also, tried with latest version (6.1.0) and it also [works fine][1]. I am going to close this issue, since there is nothing we can do without a reproduction. Feel free to open a new issue when you have one.

[1]: https://stackblitz.com/edit/ngupgradestatic-issue-25138

**Closed by gkalpak** 2018-07-26 08:33 UTC
Labels: comp: upgrade/static, state: Need repro, type: bug/fix
