### ISSUE TITLE
Undebuggable error: "class" is not a valid (qualified) symbol name

### ISSUE THREAD

**Issue by jbdeboer** [angular/angular#2041] opened 2015-05-20 19:40 UTC
I have a Angular2.dart app, which is throwing the error below in dart2js mode (not Dartium) only.
I am using the "debug" version of the reflector: ```import 'package:angular2/src/reflection/debug_reflection_capabilities.dart' show ReflectionCapabilities;```

The error is unhelpful in isolating the issue. Obvious questions:

"who is requesting ```class```"? e.g. what element is the ```ElementBinderBuilder``` processing?

"what object is ```class``` being requested on"? From the context and my recent changes, I assume ```NgClass```, but I would love an affirmation.

```
[ReflectionCapabilities(INFO)]: "annotations" requested for "NgClass".
[ReflectionCapabilities(INFO)]: "factory" requested for "NgClass".
[ReflectionCapabilities(INFO)]: "parameters" requested for "NgClass".
[ReflectionCapabilities(INFO)]: "getter" requested for "levelClass".
[ReflectionCapabilities(INFO)]: "setter" requested for "levelClass".
[ReflectionCapabilities(INFO)]: "setter" requested for "class".
main.dart.js:3972 Uncaught Uncaught Error: Invalid argument(s): "class" is not a valid (qualified) symbol name
Stack Trace:
Invalid argument(s): "class" is not a valid (qualified) symbol name
    at dart.wrapException (http://localhost:8080/main.dart.js:3972:15)
    at dart.Symbol0.static.Symbol_validatePublicSymbol (http://localhost:8080/main.dart.js:25220:17)
    at ReflectionCapabilities.dart.ReflectionCapabilities0.setter$1 (http://localhost:8080/main.dart.js:89048:74)
    at ReflectionCapabilities.dart.ReflectionCapabilities.setter$1 (http://localhost:8080/main.dart.js:88929:19)
    at Reflector.dart.Reflector.setter$1 (http://localhost:8080/main.dart.js:19346:44)
    at dart.setterFactory (http://localhost:8080/main.dart.js:22727:71)
    at ElementBinderBuilder.dart.ElementBinderBuilder.bindProperty$2 (http://localhost:8080/main.dart.js:23064:9)
    at PropertyBindingParser.dart.PropertyBindingParser._bindPropertyAst$4 (http://localhost:8080/main.dart.js:20173:31)
    at PropertyBindingParser_process_closure.dart.PropertyBindingParser_process_closure.call$2 (http://localhost:8080/main.dart.js:20259:24)
    at MapWrapper_forEach_closure.dart.MapWrapper_forEach_closure.call$2 (http://localhost:8080/main.dart.js:86206:34)
```

**Comment by yjbanov** [comment] 2015-05-21 23:59
This error was caused by an obsolete hack. Fixed by #2082.

**Closed by yjbanov** 2015-05-21 23:59 UTC
Labels: ♥ GT
