### ISSUE TITLE
Async factory provider

### ISSUE THREAD

**Issue by zlepper** [angular/angular#24173] opened 2018-05-29 08:57 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
I have to use APP_INITIALIZER to set a value on a service, which i can then inject everywhere i need it. Which is a lot of places. 

The value i need to get async is some configuration about where the apis needed for the current service are. These cannot be embedded into the application at compile time, as the application needs to be installed at customer environments. 

## Expected behavior
I would love to be able to do the following:
```ts
abstract class Consts {
   // Bunch of parameters
}

function loadConsts(httpClient: HttpClient) {
   return httpClient.get<Consts>(`/consts.json`)
}

// Have this provider in a module
{
  provide: Consts,
  useAsyncFactory: loadConsts,
  deps: [HttpClient]
}


// And then do the following in some other service/component
class SomeService {
   constructor(private httpClient: HttpClient, private consts: Consts) {
     // Consts should not be undefined
  }
}
```

All the current factories are sync, so if i use the `loadConsts` function as the factory, consts will be a promise, which is not quite what I need. 

## What is the motivation / use case for changing the behavior?
To allow for better support of apps that has to run on unknown sites, where there is no way to know at compile time how the consts are going to be. 

Once the consts are fetched, they will not change for the lifetime of the application, but they still need to be available for anything to happen.

**Comment by trotyl** [comment] 2018-05-29 09:01
Duplicate of https://github.com/angular/angular/issues/23279

**Closed** 2018-05-29 09:17 UTC
