### ISSUE TITLE
Cursor jumping at the start of string when setting any value using [(ngModel)] 

### ISSUE THREAD

**Issue by sauravraj95** [angular/angular#33563] opened 2019-11-04 07:00 UTC
# 🐞 bug report

### Affected Package
NgModel

### Is this a regression?

No

### Description

I am using one function which is populate on-paste (paste)="onPaste($event)" in text area. In this function I'm using a settimeout func. but after setting any value in ngmodel the cursor is jumping at the start position. (I'm using CKeditor)

## 🔬 Minimal Reproduction

Unable to reproduce my case here but I mentioned my code in stackblitz

https://stackblitz.com/edit/angular-wzkq5x?file=src%2Fapp%2Fapp.component.html

## 🔥 Exception or Error
<pre><code>
No error is coming in console.

</code></pre>

## 🌍  Your Environment

**Angular Version:**
{
  "name": "abc",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build --prod",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^8.2.7",
    "@angular/cdk": "^8.2.0",
    "@angular/common": "~8.2.3",
    "@angular/compiler": "~8.2.3",
    "@angular/core": "~8.2.3",
    "@angular/flex-layout": "^8.0.0-beta.27",
    "@angular/forms": "~8.2.3",
    "@angular/material": "^8.2.0",
    "@angular/platform-browser": "~8.2.3",
    "@angular/platform-browser-dynamic": "~8.2.3",
    "@angular/router": "~8.2.3",
    "@ckeditor/ckeditor5-angular": "^1.1.0",
    "@ckeditor/ckeditor5-build-classic": "^12.4.0",
    "@ngx-translate/core": "^11.0.1",
    "@ngx-translate/http-loader": "^4.0.0",
    "angular-fusioncharts": "^3.0.3",
    "angular-pipes": "^10.0.0",
    "fusioncharts": "^3.14.1",
    "intl-tel-input": "^14.0.0",
    "ng2-tel-input": "^2.0.3",
    "rxjs": "^6.4.0",
    "tslib": "^1.10.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.803.1",
    "@angular/cli": "~8.3.1",
    "@angular/compiler-cli": "~8.2.3",
    "@angular/language-service": "~8.2.3",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "^5.0.0",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "tslint-angular": "^3.0.2",
    "typescript": "~3.5.3"
  }
}

</code></pre>

**Anything else relevant?**

**Comment by AndrewKushnir** [comment] 2020-05-28 20:12
Hi @sauravraj95, thanks for reporting the issue. I looked at the Stackblitz test page and was unable to reproduce the problem (as you mentioned in your message). Unfortunately the issue is not actionable without a repro, so I'm closing it. Feel free to open a new one when you have a repro available. Thank you.

**Closed by AndrewKushnir** 2020-05-28 20:12 UTC
Labels: comp: forms, forms: ngModel, state: Needs repro
