### ISSUE TITLE
Appears in the NgModule.imports of TypeModule, but itself has errors

### ISSUE THREAD

**Issue by whitegoat** [angular/angular#35331] opened 2020-02-11 12:20 UTC
After upgrade to angular 8.1 to angular 9.

error 
export class PageModule{ }
                ~~~~~~~~~~~~~
src/app/file-explorer.module.ts:32:14 - error NG6002: Appears in the NgModule.imports of PageModule, but itself has errors

**Comment by alxhub** [comment] 2020-02-11 18:01
Do you have other errors in your project? NG6002 is generated when you import a module that's already broken for some reason, and there should be other messages about why.

**Comment by hawlik** [comment] 2020-02-12 16:24
Hi, we faced similar errors when we build on gitlab and linking node_modules folder with ln -s


ERROR in node_modules/@angular/cdk/stepper/stepper-module.d.ts:8:22 - error NG6002: Appears in the NgModule.imports of AppStepperModule, but could not be resolved to an NgModule class

8 export declare class CdkStepperModule {
                       ~~~~~~~~~~~~~~~~
node_modules/@angular/cdk/stepper/stepper-module.d.ts:8:22 - error NG6003: Appears in the NgModule.exports of AppStepperModule, but could not be resolved to an NgModule, Component, Directive, or Pipe class

8 export declare class CdkStepperModule {
                       ~~~~~~~~~~~~~~~~
src/app/common/app-stepper/app-stepper.module.ts:16:14 - error NG6002: Appears in the NgModule.imports of SharedModule, but itself has errors

16 export class AppStepperModule {}
                ~~~~~~~~~~~~~~~~
src/app/common/app-stepper/app-stepper.module.ts:16:14 - error NG6003: Appears in the NgModule.exports of SharedModule, but itself has errors

16 export class AppStepperModule {}
                ~~~~~~~~~~~~~~~~
src/app/common/shared.module.ts:64:14 - error NG6002: Appears in the NgModule.imports of UserContextModule, but itself has errors

64 export class SharedModule {}
                ~~~~~~~~~~~~
src/app/common/shared.module.ts:64:14 - error NG6002: Appears in the NgModule.imports of LoginModule, but itself has errors

64 export class SharedModule {}
                ~~~~~~~~~~~~
src/app/account/user-context/user-context.module.ts:47:14 - error NG6002: Appears in the NgModule.imports of AuthModule, but itself has errors

47 export class UserContextModule {}
                ~~~~~~~~~~~~~~~~~
src/app/auth/login/login.module.ts:15:14 - error NG6002: Appears in the NgModule.imports of AuthModule, but itself has errors

15 export class LoginModule {}
                ~~~~~~~~~~~
src/app/auth/login/login.module.ts:15:14 - error NG6003: Appears in the NgModule.exports of AuthModule, but itself has errors

15 export class LoginModule {}
                ~~~~~~~~~~~
src/app/common/shared.module.ts:64:14 - error NG6002: Appears in the NgModule.imports of SimpleCompanySearchMhaveodule, but itself has errors

.... and there is more.


When I disable this cache mechanism, the build is successful. 
when building locally there is no issue as well.

**Comment by pete0959** [comment] 2020-02-15 12:49
Followed the instructions re Angular 8 with Bootstrap 4 
get these errors... and really at a loss where to start:

12         { type: NgModule, args: [{ declarations: [NgbRating], exports: [NgbRating], imports: [CommonModule] },] },
                                                     ~~~~~~~~~

  node_modules/@ng-bootstrap/ng-bootstrap/rating/rating.js:14:5
    14 var NgbRating = /** @class */ (function () {
           ~~~~~~~~~
    'NgbRating' is declared here.
node_modules/@ng-bootstrap/ng-bootstrap/rating/rating.js:14:5 - error NG6003: Appears in the NgModule.exports of NgbRatingModule, but could not be resolved to an NgModule, Component, Directive, or Pipe class

14 var NgbRating = /** @class */ (function () {
       ~~~~~~~~~
node_modules/@ng-bootstrap/ng-bootstrap/rating/rating.module.js:7:5 - error NG6002: Appears in the NgModule.imports of NgbRootModule, but itself has errors

7 var NgbRatingModule = /** @class */ (function () {
      ~~~~~~~~~~~~~~~
node_modules/@ng-bootstrap/ng-bootstrap/rating/rating.module.js:7:5 - error NG6003: Appears in the NgModule.exports of NgbRootModule, but itself has errors

7 var NgbRatingModule = /** @class */ (function () {
      ~~~~~~~~~~~~~~~
node_modules/@ng-bootstrap/ng-bootstrap/rating/rating.module.js:7:5 - error NG6002: Appears in the NgModule.imports of NgbModule, but itself has errors

7 var NgbRatingModule = /** @class */ (function () {
      ~~~~~~~~~~~~~~~
node_modules/@ng-bootstrap/ng-bootstrap/rating/rating.module.js:7:5 - error NG6003: Appears in the NgModule.exports of NgbModule, but itself has errors

7 var NgbRatingModule = /** @class */ (function () {
      ~~~~~~~~~~~~~~~

**Comment by FranzZemen** [comment] 2020-02-16 17:12
Min started when I added angular material.  First 3 modules where find, then I added the card-module and it had issues.  I performed an ng-upgrade and now all material modules are failing.  I have the latest @angular.

ERROR in node_modules/@angular/common/http/http.d.ts:2801:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class

2801 export declare class HttpClientModule {
                          ~~~~~~~~~~~~~~~~
node_modules/@angular/platform-browser/animations/animations.d.ts:37:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class

37 export declare class BrowserAnimationsModule {
                        ~~~~~~~~~~~~~~~~~~~~~~~
node_modules/@angular/material/form-field/form-field-module.d.ts:8:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class

8 export declare class MatFormFieldModule {
                       ~~~~~~~~~~~~~~~~~~
node_modules/@angular/material/input/input-module.d.ts:8:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class

8 export declare class MatInputModule {
                       ~~~~~~~~~~~~~~
node_modules/@angular/material/card/card-module.d.ts:8:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class

8 export declare class MatCardModule {
                       ~~~~~~~~~~~~~

**Comment by FranzZemen** [comment] 2020-02-16 17:57
When get NG6002 with a module issue as above, delete the top node_modules in the workspace (where you should have installed it), and rebuild libraries/apps.

Seems like on first build, output is added to node_modules that gets occasionally confused.

This 'trick" works for me with problems incrementally added angular material modules to a library and app.

**Comment by genaropicazo-cssc** [comment] 2020-03-06 04:27
@pete0959 - I am seeing the same issues after adding `@ng-bootstrap/schematics` to my project. Were you able to find a solution?

**Comment by pete0959** [comment] 2020-03-06 17:57
> @pete0959 - I am seeing the same issues after adding `@ng-bootstrap/schematics` to my project. Were you able to find a solution?

Hi,
Yes, we deleted the 'node_modules' folder , then ran 'npm install' and it re-downloaded everything (according to the package.json file) and the problem disappeared

**Comment by stingers** [comment] 2020-04-07 06:06
Hi, I am seeing the same issues
in compilation `Warning: Skipping processing of ng-confirmation-modal because its dependency @ng-bootstrap/ng-bootstrap failed to compile.`
Someone have idea.

**Comment by mayras** [comment] 2020-04-10 03:16
I got same issue: 

![image](https://user-images.githubusercontent.com/3589928/78957311-3ad53a80-7b0f-11ea-8b72-1ec479a21001.png)

Because of this module is too small, I decided to just inject this code to my sources and understand what is problem. Using tsling - I found next issues in one ts file:

- semicolons was lost in some rows
- method 'ngOnInit' wasn't backed by OnInit
- and condition 'tslint:forin' was broken in one row
 
I fixed it and it works inside my sources without problems finally.

**Comment by alxhub** [comment] 2020-05-27 16:58
I believe the errors are correct here, but we could do a better job of telling you:

1) where the problem is
2) how to resolve it

**Comment by alxhub** [comment] 2020-11-02 20:21
Closing as not actionable for us - the errors are correct, and without more concrete context it's hard to conceive of how we could report them in a clearer way.

**Closed** 2020-11-02 21:05 UTC
Labels: P4, comp: compiler, engine: ivy, freq2: medium, hotlist: error messages, needs clarification, needs reproduction, triage #1, type: confusing
