### ISSUE TITLE
queryParamsHandling: 'merge' behavior not matching documentation

### ISSUE THREAD

**Issue by gregorholzmann** [angular/angular#31268] opened 2019-06-25 20:14 UTC
# 🐞 bug report

### Description
The [documentation](https://angular.io/api/router/NavigationExtras#queryParamsHandling) for the `queryParamsHandling` prop doesn't seem to match the behavior when using `queryParamsHandling: 'merge'` inside of a [`router.navigate(...)` call](https://angular.io/api/router/Router#navigate).

Instead of appending an additional instance of a particular queryParam, the navigation replaces the existing param, leaving the URL as `/someRoute?page=2` instead of `/someRoute?page=1&page=2` as the documentation seems to imply.

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-dqgg24

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.1
@angular-devkit/build-angular     0.800.1
@angular-devkit/build-optimizer   0.800.1
@angular-devkit/build-webpack     0.800.1
@angular-devkit/core              8.0.1
@angular-devkit/schematics        8.0.1
@angular/cli                      8.0.1
@ngtools/webpack                  8.0.1
@schematics/angular               8.0.1
@schematics/update                0.800.1
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.29.0

</code></pre>

**Comment by gregorholzmann** [comment] 2019-09-06 19:49
Just following up: any news on this? I see a couple other issues that touch on this problem, but no solutions so far.

**Comment by rockument69** [comment] 2020-05-27 22:07
This needs engineering input before docs team can edit the doc. FYI, @jbogarthyde if you are working on this section of the API docs: [NavigationExtras](https://angular.io/api/router/NavigationExtras#queryParamsHandling).

**Comment by jbogarthyde** [comment] 2020-06-03 18:25
@atscott I am currently working on the API doc for Router, including this navigation option. Can you confirm whether this should work as documented (making it  a code bug) or is incorrectly documented?

It is documented in two places in the API ref, https://angular.io/api/router/QueryParamsHandling and https://angular.io/api/router/NavigationExtras#queryParamsHandling. There is a minimal example of the `merge` value, and none for `preserve` -- I think it could use a more complete description.

We could also add an explanation of the behavior in context in the Routing and Navigation guide (which I'm also working on). This would probably require a more extensive example.

**Comment by Airblader** [comment] 2020-06-03 18:46
Making this a code but would be an incredibly huge breaking change that I don't think can reasonably be fixed as a bug.

**Comment by atscott** [comment] 2020-06-03 19:13
This is working as intended. The way it works isn't necessarily contradicted by the documentation - it depends on what you think "merge" means. If the current params are `?a=1&b=2` and I write  `this.router.navigate(['.'], {queryParams: {c: 3}, queryParamsHandling: 'merge'});`, the result is `?a=1&b=2&c=3`. The merging is more akin to object merging `{...old, {new: 'values'}}`

**Comment by Airblader** [comment] 2020-06-03 19:15
@atscott The example in the documentation directly does contradict the current behavior. Note the comment in the example above the navigate call.

**Comment by atscott** [comment] 2020-06-03 19:18
> @atscott The example in the documentation does directly contradict the current behavior, though. Note the comment in the example above the navigate call.

Sorry, yes you're right. My eyes glossed over the comment.

**Comment by atscott** [comment] 2021-05-24 17:28
Closing as this appears to have been resolved by #37980. The documentation now has `// from /view1?page=1 to/view2?page=1&otherKey=2`

**Closed by atscott** 2021-05-24 17:28 UTC
Labels: P3, comp: docs, comp: router, freq3: high, state: confirmed, state: needs eng input, triage #1, type: bug/fix
