### ISSUE TITLE
Preloading doesn't load modules asynchronously.

### ISSUE THREAD

**Issue by poddarkhushbu07** [angular/angular#30917] opened 2019-06-07 12:24 UTC
This statement in Angular docs:
https://angular.io/guide/router#preloading-background-loading-of-feature-areas

> You can also load modules asynchronously with preloading.

Pre-loading increases the load time then how can it be asynchronous process

**Comment by poddarkhushbu07** [comment] 2019-06-07 14:10
@trotyl  Please explain why you down voted ?

**Comment by brandonroberts** [comment] 2019-06-11 18:36
@poddarkhushbu07 pre-loading of modules increasing load times is a separate issue that needs a reproduction.

**Comment by poddarkhushbu07** [comment] 2019-06-12 06:42
@brandonroberts  Yes, when I run my application in dev mode, all preloaded modules takes time to compile and load, that process should be asynchronous. But it is synchronous in real time which increases the load time of an application.

**Comment by trotyl** [comment] 2019-06-12 07:14
Duplicate of https://github.com/angular/angular/issues/28270

---

Please fill the issue template and provide a minimal reproduction if it's not about JIT performance.

**Comment by brandonroberts** [comment] 2019-06-12 13:34
Closing as a duplicate of #28270

**Closed by brandonroberts** 2019-06-12 13:34 UTC
Labels: comp: docs, freq1: low, severity1: confusing, type: bug/fix
