### ISSUE TITLE
@angular/elements: Signal `input` with `alias` option is not working for custom elements

### ISSUE THREAD

**Issue by OlehPetrykUA** [angular/angular#58303] opened 2024-10-22 15:06 UTC
### Which @angular/* package(s) are the source of the bug?

elements

### Is this a regression?

No

### Description

When declaring an `input` with `alias` inside of a component and use `createCustomElement` of that component.

ex:
```
readonly name = input<string>(
  'name',
 { alias: 'customName' }
);
```

On the actual web-component there are no such attribute as `customName`, only `name` will exist and work.

Looks like that `ComponentFactory` at method `resolveComponentFactory which returns inputs array with propName of each input is not actually aliased name.

https://github.com/angular/angular/blob/main/packages/elements/src/component-factory-strategy.ts#L46

### Please provide the environment you discovered this bug in (run `ng version`)

Angular CLI: 19.0.0-next.12
Node: 20.15.1
Package Manager: yarn 1.22.22
OS: darwin arm64

Angular: 19.0.0-next.10
... animations, common, compiler, compiler-cli, core, elements
... forms, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1900.0-next.12
@angular-devkit/build-angular   19.0.0-next.12
@angular-devkit/core            18.2.9
@angular-devkit/schematics      18.2.9
@angular/cdk                    19.0.0-next.9
@angular/cli                    19.0.0-next.12
@angular/material               19.0.0-next.9
@schematics/angular             19.0.0-next.12
ng-packagr                      19.0.0-next.6
rxjs                            7.8.1
typescript                      5.5.4
zone.js                         0.15.0

**Comment by alxhub** [comment] 2024-10-22 15:19
Duplicate of #58302

**Closed by alxhub** 2024-10-22 15:19 UTC

**Comment by OlehPetrykUA** [comment] 2024-10-22 15:23
@alxhub  I was asked to create an issue by template, the original one should be closed and this oppened
