### ISSUE TITLE
"routerLinkActive" directive causes infinite CD loop

### ISSUE THREAD

**Issue by andrew1931** [angular/angular#47050] opened 2022-08-05 13:56 UTC
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

No

### Description

In the link provided below you can find a list of `a` tags being rendered via `ngForOf` directive. This list can be rendered from `linksArr` array and from a function `links` which returns the same array (_yes, I understand that using function inside a loop is no the best idea but it is still possible and can be useful if we want to pass some arguments inside this function_). 

So If we render our list using a function which returns an array and DO NOT provide a `trackBy` argument - **routerLinkActive** directive will cause an infinite loop of CD (cause I don't use a reference to an array here but create a new one inside a function and inside of `ngDoCheck` method of `ngForOf` directive `this._differ.diff(this._ngForOf)` method will always return new changes)

There is a screenshot of "**update**" method of **RouterLinkActive** class which calls `Promise.resolve` function to run CD and therefore the infinite loop starts.

<img width="931" alt="Screenshot 2022-08-05 at 4 13 17 PM" src="https://user-images.githubusercontent.com/31846707/183084895-3140e875-6aad-401d-98a6-b2e8fbeb8b35.png">

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-ob4ers?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fpage1.ts,src%2Fapp%2Fpage2.ts,src%2Fapp%2Fapp.component.css,src%2Findex.html

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular: 14.0.0
```

**Comment by atscott** [comment] 2022-08-05 15:27
Duplicate of https://github.com/angular/angular/issues/20995

**Closed by atscott** 2022-08-05 15:27 UTC
