### ISSUE TITLE
[router] -> using navigateByUrl and getCurrentNavigation -> extra.state is serialized loosing type

### ISSUE THREAD

**Issue by meriturva** [angular/angular#43812] opened 2021-10-12 14:53 UTC
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

No

### Description

We have quite a big enterprise application where we use constantly dynamic routes and resolvers.

I have developed a reproducible example to show the error we are facing using `getCurrentNavigation` and extra state.
Basically, the resolver just produces a Menu instance, but in case of back navigation type is lost.

See gif:

![test](https://user-images.githubusercontent.com/5664195/136979414-28231bff-fc06-4e7a-ae4a-b36f8e08ab81.gif)

To reproduce:

1) open URL:  http://localhost:4200/#/route (my component is present and menu is correct)
2) change URL to a wrong one http://localhost:4200/#/wrong (not found page is shown correctly)
3) push browser back navigation button (menu is now an object and not an instance of Menu class)

### Please provide a link to a minimal reproduction of the bug

https://github.com/meriturva/angular_core_testGetCurrentNavigation

### Please provide the exception or error you saw

```true
Application level error due to menu type lost:

ERROR Error: Uncaught (in promise): TypeError: menu.test is not a function
TypeError: menu.test is not a function
    at new MyComponent (my.component.ts:13)
    at NodeInjectorFactory.MyComponent_Factory [as factory] (my.component.ts:14)
    at getNodeInjectable (core.js:3549)
    at instantiateRootComponent (core.js:10140)
    at createRootComponent (core.js:12501)
    at ComponentFactory$1.create (core.js:25136)
    at ViewContainerRef.createComponent (core.js:23172)
    at RouterOutlet.activateWith (router.js:5592)
    at ActivateRoutes.activateRoutes (router.js:2163)
    at router.js:2114
    at resolvePromise (zone.js:1213)
    at resolvePromise (zone.js:1167)
    at zone.js:1279
    at ZoneDelegate.invokeTask (zone.js:406)
    at Object.onInvokeTask (core.js:28660)
    at ZoneDelegate.invokeTask (zone.js:405)
    at Zone.runTask (zone.js:178)
    at drainMicroTaskQueue (zone.js:582)
    at invokeTask (zone.js:491)
    at ZoneTask.invoke (zone.js:476)
```

### Please provide the environment you discovered this bug in

```true
Angular CLI: 12.2.9
Node: 14.18.0
Package Manager: npm 6.14.15
OS: win32 x64

Angular: 12.2.9
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.9
@angular-devkit/build-angular   12.2.9
@angular-devkit/core            12.2.9
@angular-devkit/schematics      12.2.9
@schematics/angular             12.2.9
rxjs                            6.6.7
typescript                      4.3.5
```

**Comment by atscott** [comment] 2021-10-12 16:32
Closing as working as intended. The state object in history must be serializable - https://developer.mozilla.org/en-US/docs/Web/API/History/pushState#parameters.

**Closed by atscott** 2021-10-12 16:32 UTC
Labels: comp: router
