### ISSUE TITLE
Allow ngTemplateOutlet to use templates provided via ngContent

### ISSUE THREAD

**Issue by rothsandro** [angular/angular#25394] opened 2018-08-08 19:13 UTC
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[X] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
A parent component provides some HTML content and a ngTemplate to a subcomponent which includes ngContent. The provided content will be rendered inside the ngContent tag, but the subcomponent is not able to use provided templates with ngTemplateOutlet. The template will not be rendered.

```
<!-- Parent -->
<subcomponent>
  <p>Some content</p>
  <ng-template #demo2>...</ng-template>
</subcomponent>

<!-- Subcomponent -->
<ng-content></ng-content>
<ng-container *ngTemplateOutlet="demo2">
  <!-- Nothing will be rendered here -->
</ng-container>
```

## Expected behavior
A subcomponent should be able to directly use provided templates (as done in the example above) as the template is provided via ngContent.

## Minimal reproduction of the problem with instructions
A simple demo with HelloComponent as parent and TabsComponent as subcomponent.
The demo also includes an example using the select attribute of NgContent (see below).
Editor: https://stackblitz.com/edit/angular-gr71sn

## What is the motivation / use case for changing the behavior?
The template is available in the sub component as it was provided by the parent component via ngContent and it should therefore work.

**Why not using the select attribute of ngContent**
The ngContent component already allows to specify a selector using the select attribute, which could be used instead of templates and ngTemplateOutlet. The problem here is that the content gets always rendered even if the subcomponent uses an ngIf:

```
<ng-content *ngIf="false" select=".test"></ng-content>
```

The content of .test is of course not added to the DOM (as ngIf is used) but will be rendered automatically at least once (and that is not what we want when using ngIf). 

## Environment

<pre><code>
Angular version: 6.0.0

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [X] Safari (desktop) version 11.1.2
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

</code></pre>

**Comment by trotyl** [comment] 2018-08-09 02:08
Duplicate of https://github.com/angular/angular/issues/24926

**Comment by pkozlowski-opensource** [comment] 2018-08-09 09:02
@rothsandro this is not how local references (`#demo2` in your case) work - they are scoped to a given _view_ so you can't expect that it will be defined in one component view and available in another component's view. It is like local variables in JavaScript - those are available in the scope where they were defined. 

If you want to have reference to an external template you should pass it explicitly to the `TabsComponent`: https://stackblitz.com/edit/angular-snn7ve?file=src%2Fapp%2Fhello.component.ts

Closing as invalid.

**Closed by pkozlowski-opensource** 2018-08-09 09:02 UTC
Labels: comp: core & compiler
