### ISSUE TITLE
Passing empty array as input has side effects

### ISSUE THREAD

**Issue by Terordar** [angular/angular#15392] opened 2017-03-22 14:26 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

The input property that gets an empty array (`<example [inputOne]="[]"></example>`) through input binding, will create a reference, in the case of an AOT build, to the variable EMPTY_ARRAY in _@angular/core/src/linker/view_utils.js_. Interacting with the input property will have a direct impact to the EMTPY_ARRAY variable. If multiple components get an empty array as input property, all of them will have the same reference to the EMPTY_ARRAY variable, having undesirable side effects.

As you can see it on the image, we already added a string to an array of one of the child's array, and when creating a new component which gets the empty array as an input, we can see that the EMPTY_ARRAY variable contains a string : 

![untitled](https://cloud.githubusercontent.com/assets/10707857/24202561/a683a228-0f13-11e7-992c-b990a38d2e30.png)

**Expected behavior**
Passing an empty array to an input property should create a new array, and not a reference to the global empty array variable.

**Minimal reproduction of the problem with instructions**
In the following plunker, we have two child components and a sub-child, all of them getting an empty array as an input. When adding a new string to one of the child's array, as they all have the same reference, they will show the new added string even if we didn't interact with their input property.

http://plnkr.co/edit/l9vdne?p=preview

* **Angular version:** 2.4.9

* **Browser:** Chrome 55
 
* **Language:** TypeScript 2

**Comment by DzmitryShylovich** [comment] 2017-03-22 14:29
it's a performance optimization. afaik the same will happen with empty object literal `{}` in a template

**Comment by samvloeberghs** [comment] 2017-03-22 14:47
It's a performance optimisation that has severe side effects afaik

**Comment by Zerzio** [comment] 2017-03-22 15:54
This is definitively a bug and it was a quite difficult to understand why our application was behaving strangely (component keeping state)

**Comment by DzmitryShylovich** [comment] 2017-03-22 16:20
cc @tbosch

**Comment by tbosch** [comment] 2017-03-22 16:43
yes, that is a valid bug, but not a regression as we had it since ng 2.0

**Comment by trotyl** [comment] 2018-08-07 05:24
Should be fixed by Ivy.

**Comment by pkozlowski-opensource** [comment] 2020-02-27 11:01
This was fixed in Angular v9 running ivy: https://ng-run.com/edit/L8GCpO3GBirHBYapWntY

**Closed by pkozlowski-opensource** 2020-02-27 11:01 UTC
Labels: comp: core, freq2: medium, severity3: broken, type: bug/fix
