### ISSUE TITLE
Allow Setting a Breakpoint in templates

### ISSUE THREAD

**Issue by johnpapa** [angular/angular#39683] opened 2020-02-08 05:38 UTC

**Comment by mgechev** [comment] 2020-11-13 22:49
It should be supported by Chrome DevTools with the source maps we generate with the compiler.

**Comment by kyliau** [comment] 2020-11-14 00:02
@mgechev how about setting the breakpoint in the template itself? I guess that's something that needs to be supported by the compiler?

**Comment by mgechev** [comment] 2020-11-14 00:35
It seems to be working for me with the source maps that the compiler generates. Not ideal though. I can't set breakpoints to specific expressions accurately.

<img width="722" alt="Screen Shot 2020-11-14 at 2 33 47 AM" src="https://user-images.githubusercontent.com/455023/99133271-fa4c1b00-2621-11eb-8bd4-5b849b4a013f.png">

**Comment by petebacondarwin** [comment] 2020-11-14 10:47
This should be working right now. We generate source-mappings from the generated template code back to the template source itself. If there are specific issues then please open a bug report with reproduction, so that we can fix it.
I think we should close this issue as the general idea as requested is working.

**Comment by indraraj26** [comment] 2020-11-20 17:49
> It seems to be working for me with the source maps that the compiler generates. Not ideal though. I can't set breakpoints to specific expressions accurately.
> 
> <img alt="Screen Shot 2020-11-14 at 2 33 47 AM" width="722" src="https://user-images.githubusercontent.com/455023/99133271-fa4c1b00-2621-11eb-8bd4-5b849b4a013f.png">

how did you manage to add breakpoint in template?

**Comment by mgechev** [comment] 2020-11-20 23:37
Run the application with `ng serve`, open the template in sources, and set a breakpoint.

**Closed** 2020-11-20 23:37 UTC
Labels: comp: core, feature

**Comment by indraraj26** [comment] 2020-11-21 18:03
Hey i don't see html file in sources 
This is what it looks like for me 
![image](https://user-images.githubusercontent.com/23274631/99884050-30f0e980-2c51-11eb-8092-6782c43071db.png)
![image](https://user-images.githubusercontent.com/23274631/99884060-3f3f0580-2c51-11eb-9d56-191a8f65718b.png)
