### ISSUE TITLE
gulp test.unit.cjs only executes once

### ISSUE THREAD

**Issue by mhevery** [angular/angular#2136] opened 2015-05-23 16:02 UTC
Upon executing `gulp.test.cjs`:

```
08:58 $ gulp test.unit.cjs
Dart SDK is not available, Dart tasks will be skipped.
[08:58:52] Using gulpfile ~/angular/gulpfile.js
[08:58:52] Starting 'build/clean.js'...
[08:58:52] Starting 'build/clean.tools'...
[08:58:52] Finished 'build/clean.tools' after 1.05 ms
[08:58:52] Starting 'build.tools'...
[08:58:52] Starting '!build.tools'...
[08:58:53] Finished 'build/clean.js' after 309 ms
[08:58:56] Finished '!build.tools' after 3.79 s
[08:58:56] Finished 'build.tools' after 3.79 s
[08:58:56] Starting 'test.unit.cjs'...
[08:58:56] Starting '!build.js.cjs'...
Tree diff:          funnel-output_path-Rl8ckYlX.tmp, duration:    18ms,   167 changes detected (files:   167, directories:  169)
Tree diff:                   funnel-dest_FkEYvI.tmp, duration:    17ms,   173 changes detected (files:   173, directories:  169)
Tree diff:                   funnel-dest_4cmvb4.tmp, duration:    34ms,   886 changes detected (files:   886, directories:   87)

Slowest Trees                                 | Total               
----------------------------------------------+---------------------
DiffingTSCompiler                             | 5152ms              
DiffingTraceurCompiler                        | 3848ms              

Slowest Trees (cumulative)                    | Total (avg)         
----------------------------------------------+---------------------
DiffingTSCompiler (1)                         | 5152ms              
DiffingTraceurCompiler (1)                    | 3848ms              

creating node_modules symlink hack
creating link dist/js/cjs/node_modules/angular2 ../angular2
creating link dist/js/cjs/node_modules/benchmarks ../benchmarks
creating link dist/js/cjs/node_modules/benchmarks_external ../benchmarks_external
creating link dist/js/cjs/node_modules/benchpress ../benchpress
creating link dist/js/cjs/node_modules/examples ../examples
creating link dist/js/cjs/node_modules/rtts_assert ../rtts_assert
[08:59:06] Finished '!build.js.cjs' after 9.72 s
[08:59:06] Starting 'test.unit.cjs/ci'...
Started
..


1090 specs, 0 failures
Finished in 0.09 seconds
[08:59:07] Finished 'test.unit.cjs/ci' after 1.27 s
```

Now change the files to trigger a rerun.

```
==================================================
 WATCH TRIGGERED BY FILE CHANGE #1
 On: 5/23/2015 at 8:59:14 AM
==================================================
[08:59:14] Starting '!build.js.cjs'...
Tree diff:          funnel-output_path-Rl8ckYlX.tmp, duration:    21ms,     1 changes detected (files:   167, directories:  169) [
  * angular2/test/change_detection/parser/parser_spec.js
]
Tree diff:                   funnel-dest_FkEYvI.tmp, duration:    22ms,   173 changes detected (files:   173, directories:  169) [
  * angular2/angular2.ts
  * angular2/annotations.ts
  * angular2/change_detection.ts
  * angular2/core.ts
  * angular2/di.ts
  * angular2/di_annotations.ts
  * angular2/di_errors.ts
  * angular2/directives.ts
  * angular2/forms.ts
  * angular2/pipes.ts
  * angular2/render.ts
  * angular2/src/change_detection/abstract_change_detector.ts
  * angular2/src/change_detection/binding_record.ts
  * angular2/src/change_detection/change_detection.ts
  * angular2/src/change_detection/change_detection_jit_generator.ts
  * angular2/src/change_detection/change_detection_util.ts
  * angular2/src/change_detection/change_detector_ref.ts
  * angular2/src/change_detection/coalesce.ts
  * angular2/src/change_detection/constants.ts
  * angular2/src/change_detection/directive_record.ts
  * angular2/src/change_detection/dynamic_change_detector.ts
  * angular2/src/change_detection/exceptions.ts
  * angular2/src/change_detection/interfaces.ts
  * angular2/src/change_detection/parser/ast.ts
  * angular2/src/change_detection/parser/lexer.ts
  * angular2/src/change_detection/parser/locals.ts
  * angular2/src/change_detection/parser/parser.ts
  * angular2/src/change_detection/pipes/iterable_changes.ts
  * angular2/src/change_detection/pipes/json_pipe.ts
  * angular2/src/change_detection/pipes/keyvalue_changes.ts
  * angular2/src/change_detection/pipes/lowercase_pipe.ts
  * angular2/src/change_detection/pipes/null_pipe.ts
  * angular2/src/change_detection/pipes/observable_pipe.ts
  * angular2/src/change_detection/pipes/pipe.ts
  * angular2/src/change_detection/pipes/pipe_registry.ts
  * angular2/src/change_detection/pipes/promise_pipe.ts
  * angular2/src/change_detection/pipes/uppercase_pipe.ts
  * angular2/src/change_detection/proto_change_detector.ts
  * angular2/src/change_detection/proto_record.ts
  * angular2/src/core/annotations/annotations.ts
  * angular2/src/core/annotations/decorators.ts
  * angular2/src/core/annotations/di.ts
  * angular2/src/core/annotations/view.ts
  * angular2/src/core/annotations/visibility.ts
  * angular2/src/core/annotations_impl/annotations.ts
  * angular2/src/core/annotations_impl/di.ts
  * angular2/src/core/annotations_impl/view.ts
  * angular2/src/core/annotations_impl/visibility.ts
  * angular2/src/core/application.ts
  * angular2/src/core/application_tokens.ts
  * angular2/src/core/compiler/base_query_list.ts
  * angular2/src/core/compiler/compiler.ts
  * angular2/src/core/compiler/component_url_mapper.ts
  * angular2/src/core/compiler/directive_resolver.ts
  * angular2/src/core/compiler/dynamic_component_loader.ts
  * angular2/src/core/compiler/element_binder.ts
  * angular2/src/core/compiler/element_injector.ts
  * angular2/src/core/compiler/element_ref.ts
  * angular2/src/core/compiler/interfaces.ts
  * angular2/src/core/compiler/proto_view_factory.ts
  * angular2/src/core/compiler/query_list.ts
  * angular2/src/core/compiler/template_resolver.ts
  * angular2/src/core/compiler/view.ts
  * angular2/src/core/compiler/view_container_ref.ts
  * angular2/src/core/compiler/view_manager.ts
  * angular2/src/core/compiler/view_manager_utils.ts
  * angular2/src/core/compiler/view_pool.ts
  * angular2/src/core/compiler/view_ref.ts
  * angular2/src/core/exception_handler.ts
  * angular2/src/core/life_cycle/life_cycle.ts
  * angular2/src/core/testability/get_testability.ts
  * angular2/src/core/testability/testability.ts
  * angular2/src/core/zone/ng_zone.ts
  * angular2/src/di/annotations.ts
  * angular2/src/di/annotations_impl.ts
  * angular2/src/di/binding.ts
  * angular2/src/di/decorators.ts
  * angular2/src/di/exceptions.ts
  * angular2/src/di/forward_ref.ts
  * angular2/src/di/injector.ts
  * angular2/src/di/key.ts
  * angular2/src/di/opaque_token.ts
  * angular2/src/di/type_literal.ts
  * angular2/src/directives/class.ts
  * angular2/src/directives/ng_for.ts
  * angular2/src/directives/ng_if.ts
  * angular2/src/directives/ng_non_bindable.ts
  * angular2/src/directives/ng_switch.ts
  * angular2/src/dom/browser_adapter.ts
  * angular2/src/dom/dom_adapter.ts
  * angular2/src/dom/generic_browser_adapter.ts
  * angular2/src/facade/async.ts
  * angular2/src/facade/browser.ts
  * angular2/src/facade/collection.ts
  * angular2/src/facade/lang.ts
  * angular2/src/facade/math.ts
  * angular2/src/forms/directives.ts
  * angular2/src/forms/form_builder.ts
  * angular2/src/forms/model.ts
  * angular2/src/forms/validator_directives.ts
  * angular2/src/forms/validators.ts
  * angular2/src/mock/ng_zone_mock.ts
  * angular2/src/mock/template_resolver_mock.ts
  * angular2/src/mock/xhr_mock.ts
  * angular2/src/reflection/reflection.ts
  * angular2/src/reflection/reflection_capabilities.ts
  * angular2/src/reflection/reflector.ts
  * angular2/src/reflection/types.ts
  * angular2/src/render/api.ts
  * angular2/src/render/dom/compiler/compile_control.ts
  * angular2/src/render/dom/compiler/compile_element.ts
  * angular2/src/render/dom/compiler/compile_pipeline.ts
  * angular2/src/render/dom/compiler/compile_step.ts
  * angular2/src/render/dom/compiler/compile_step_factory.ts
  * angular2/src/render/dom/compiler/compiler.ts
  * angular2/src/render/dom/compiler/directive_parser.ts
  * angular2/src/render/dom/compiler/property_binding_parser.ts
  * angular2/src/render/dom/compiler/selector.ts
  * angular2/src/render/dom/compiler/template_loader.ts
  * angular2/src/render/dom/compiler/text_interpolation_parser.ts
  * angular2/src/render/dom/compiler/view_splitter.ts
  * angular2/src/render/dom/convert.ts
  * angular2/src/render/dom/dom_renderer.ts
  * angular2/src/render/dom/events/event_manager.ts
  * angular2/src/render/dom/events/hammer_common.ts
  * angular2/src/render/dom/events/hammer_gestures.ts
  * angular2/src/render/dom/events/key_events.ts
  * angular2/src/render/dom/shadow_dom/content_tag.ts
  * angular2/src/render/dom/shadow_dom/emulated_scoped_shadow_dom_strategy.ts
  * angular2/src/render/dom/shadow_dom/emulated_unscoped_shadow_dom_strategy.ts
  * angular2/src/render/dom/shadow_dom/light_dom.ts
  * angular2/src/render/dom/shadow_dom/native_shadow_dom_strategy.ts
  * angular2/src/render/dom/shadow_dom/shadow_css.ts
  * angular2/src/render/dom/shadow_dom/shadow_dom_compile_step.ts
  * angular2/src/render/dom/shadow_dom/shadow_dom_strategy.ts
  * angular2/src/render/dom/shadow_dom/style_inliner.ts
  * angular2/src/render/dom/shadow_dom/style_url_resolver.ts
  * angular2/src/render/dom/shadow_dom/util.ts
  * angular2/src/render/dom/util.ts
  * angular2/src/render/dom/view/element_binder.ts
  * angular2/src/render/dom/view/property_setter_factory.ts
  * angular2/src/render/dom/view/proto_view.ts
  * angular2/src/render/dom/view/proto_view_builder.ts
  * angular2/src/render/dom/view/view.ts
  * angular2/src/render/dom/view/view_container.ts
  * angular2/src/services/ruler.ts
  * angular2/src/services/title.ts
  * angular2/src/services/url_resolver.ts
  * angular2/src/services/xhr.ts
  * angular2/src/services/xhr_impl.ts
  * angular2/src/test_lib/benchmark_util.ts
  * angular2/src/test_lib/e2e_util.ts
  * angular2/src/test_lib/fake_async.ts
  * angular2/src/test_lib/lang_utils.ts
  * angular2/src/test_lib/test_bed.ts
  * angular2/src/test_lib/test_injector.ts
  * angular2/src/test_lib/test_lib.ts
  * angular2/src/test_lib/utils.ts
  * angular2/src/util/decorators.ts
  * angular2/test/core/compiler/integration_spec.ts
  * angular2/test/di/async_spec.ts
  * angular2/test/di/forward_ref_spec.ts
  * angular2/test/di/injector_spec.ts
  * angular2/test/di/key_spec.ts
  * angular2/test/forms/directives_spec.ts
  * angular2/test/forms/form_builder_spec.ts
  * angular2/test/forms/integration_spec.ts
  * angular2/test/forms/model_spec.ts
  * angular2/test/forms/validators_spec.ts
  * angular2/test/reflection/reflector_common.ts
  * angular2/test/reflection/reflector_spec.ts
  * angular2/test.ts
  * angular2/test_lib.ts
]
```

Tests did not run, and the watcher is now dead.

**Comment by caitp** [comment] 2015-05-23 19:21
I can't reproduce this on master with a fresh npm install, but it might be worth adding a logger to the error event handler in tools/build/watch.js --- just in case it's not being logged normally. That may highlight an issue that the FSWatcher is running into?

**Comment by vicb** [comment] 2015-05-26 12:13
same here, cpu usage raise to 98%, have to `kill` gulp

**Comment by vicb** [comment] 2015-05-26 12:14
seems to happen only on failures

**Comment by mhevery** [comment] 2015-05-29 23:11
@caitp can you repro with a syntactic error which will make `tsc` fail?

**Comment by caitp** [comment] 2015-05-29 23:14
https://gist.github.com/caitp/d5266c653a5d374b5c4d << syntax error in TS file, corrected -> tests run

**Comment by naomiblack** [comment] 2015-05-29 23:45
Closing as not reproducible. Please reopen if anyone can repro.

**Closed by naomiblack** 2015-05-29 23:45 UTC
Labels: comp: dev-productivity, P2: required, type: bug

**Comment by caitp** [comment] 2015-05-29 23:53
It could be os-specific since chokidar has a few different backends it can use depending on platform. I can't seem to reproduce on a Mac, but maybe it's more a Linux or Windows issue
