### ISSUE TITLE
docs: dynamic component loading - Error loading ad-banner.component.js 

### ISSUE THREAD

**Issue by phil123456** [angular/angular#17158] opened 2017-06-01 07:29 UTC
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
```

**Current behavior**

I tried to run the live example and it brakes

https://angular.io/docs/ts/latest/cookbook/dynamic-component-loader.html

I downloaded the archive, ran it localy same issue

```
Error: (SystemJS) XHR error loading http://localhost:3000/app/ad-banner.component.js
	ZoneDelegate.prototype.invokeTask@http://localhost:3000/node_modules/zone.js/dist/zone.js:424:17
	Zone.prototype.runTask@http://localhost:3000/node_modules/zone.js/dist/zone.js:191:28
	ZoneTask/this.invoke@http://localhost:3000/node_modules/zone.js/dist/zone.js:486:28
	
	Error loading http://localhost:3000/app/ad-banner.component.js as "./ad-banner.component" from http://localhost:3000/app/app.module.js
Trace de la pile :
(SystemJS) XHR error loading http://localhost:3000/app/ad-banner.component.js
	ZoneDelegate.prototype.invokeTask@http://localhost:3000/node_modules/zone.js/dist/zone.js:424:17
	Zone.prototype.runTask@http://localhost:3000/node_modules/zone.js/dist/zone.js:191:28
	ZoneTask/this.invoke@http://localhost:3000/node_modules/zone.js/dist/zone.js:486:28
	
	Error loading http://localhost:3000/app/ad-banner.component.js as "./ad-banner.component" from http://localhost:3000/app/app.module.js
```

I injected the code in my angular 4 project, it works partialy, only the first AD is displayed

that line does not update the template data all the time

    (<AdComponent>componentRef.instance).data = adItem.data; 

**Expected behavior**
I expect it to run and display the four adds

**Minimal reproduction of the problem with instructions**
just check the page in the url above and run the live example or download/install/run it 

**What is the motivation / use case for changing the behavior?**
?

**Please tell us about your environment:**
Windows 7, Wamp 3, Google Crhome

* **Angular version:** 2.0.X
check the live example

* **Browser: Chrome 58
 
* **Language:** see live example

**Comment by Onyphlax** [comment] 2017-06-01 09:04
Hi @phil123456,
I had the same problem but fixed it with disabling AdBlock on Chrome.

**Comment by phil123456** [comment] 2017-06-01 10:12
actually I mixed browsers, it actually happened in ffox, and disabling adblock did the trick indeed

but in my angular 4 project it does not work

would the code need to be modified to work in angular 4 ?

**Comment by phil123456** [comment] 2017-06-02 05:37
hello?

**Comment by Foxandxss** [comment] 2017-06-04 16:41
I will take a peek. Thanks.

**Comment by Foxandxss** [comment] 2017-06-04 17:36
I don't see the issue but I see a different one. Will try locally too.

**Comment by wardbell** [comment] 2017-06-05 18:13
Yes, something changed in 
1. when the ViewChild becomes available 
1. the way that the devmode change-detection-violation checks work 

Not sure when these changes arrived ... probably early in v.4 ... but they changed.
Look at `ad-banner.component.ts`. 

## ViewChild in ngAfterViewInit or ngOnInit?

The `adHost` _ViewChild_ is actually available in `ngOnInit` so we don't have to wait until `ngAfterViewInit`. Moving the latter's logic to `ngOnInit` removes the first occurrence of the `ExpressionChangedAfterItHasBeenCheckedError`.

Unfortunately, we have no clear guidance on when a `ViewChild` becomes available. 

## No synchronous data changes after component creation

Notice that the `ExpressionChangedAfterItHasBeenCheckedError` is raised every time that `loadComponent` is called. That didn't happen in v.2.

Here's why it happens now. Look at these two lines:
```
let componentRef = viewContainerRef.createComponent(componentFactory);
 (<AdComponent>componentRef.instance).data = adItem.data;
```
The first line creates a dynamic component (an `AdComponent` of some kind) and adds it to the view (via the `viewContainerRef`). 

The second line gives the created Ad Component its data.

These two lines execute synchronously. That's why the app actually works. The Ad Component is displayed with the data assigned in line #2.

But it appears that, as of the change, the dynamically created component **is closed to modification** _immediately after it is instantiated and placed in the `ViewContainer`.  The subsequent update of that component's data in line 2 is disallowed (in DevMode).

Maybe that's how it should have been all along. I don't know why. It seems to me that the lock down should occur at the end of the current JavaScript turn (as was the case in v.2). But that's the way it is now.

There is a workaround.

1. Wait a tick to provide the data: `setTimeout(() => (<AdComponent>componentRef.instance).data = adItem.data, 0);`

1. Fix the two Ad Components so that they work for the brief moment when there is not data. Can do this, for example, by adding the Null Reference operator (`?.`) to `HeroJobComponent` and `HeroProfileComponent`.

This all seems like too much work and a distraction from the point of this example. It would be better if the Ad Components got their own data ... or, perhaps simpler for this example, simply had hard coded data.

I'm not sure if it's worth filing an issue about the undocumented change to Angular's behavior. It seems like water under the bridge to me.

I think we should review this guide to determine if it is giving guidance we still like. If so, we should revise the example to conform to the way that Angular works now. If not, let's come up with better guidance.

**Comment by phil123456** [comment] 2017-06-06 06:58
I fixed the bug earlier simply with if(this.ads) in the loadComponent and moving the init code to OnInit()

but someone should update the example in the documentation at least
```

 ngOnInit() {
    this.loadComponent();
    this.getAds();
  }

  ngOnDestroy() {
    clearInterval(this.interval);
  }

  loadComponent() {
      if(this.ads)
      {
        this.currentAddIndex = (this.currentAddIndex + 1) % this.ads.length;
        let adItem = this.ads[this.currentAddIndex];

        let componentFactory = this.componentFactoryResolver.resolveComponentFactory(adItem.component);

        let viewContainerRef = this.adHost.viewContainerRef;
        viewContainerRef.clear();

        let componentRef = viewContainerRef.createComponent(componentFactory);
        (<AdComponent>componentRef.instance).data = adItem.data;
    }
  }
```

**Comment by phil123456** [comment] 2017-06-06 07:00
if someone could enlight me on how to lazy load the injected components ... I mean it's not like if they were referenced by a route...so how do I do that ?

**Comment by bijayy33** [comment] 2017-10-21 23:42
@Onyphlax  Thanks man. I spent almost one day to figure out. I disabled the ad blocker and worked for me.

**Comment by kapunahelewong** [comment] 2018-02-12 21:47
@phil123456 I've just submitted this PR: https://github.com/angular/angular/pull/22181 

I think that covers part of what's in this issue and then the adblocker looks like it was the other part. If there's nothing outstanding, would you mind if we close this issue? If you still have questions I'll be happy to help find answers to them.

**Comment by jenniferfell** [comment] 2018-04-25 09:46
Thanks, everyone. I'm going to close this as a duplicate of https://github.com/angular/angular/issues/18138, which recommends changing the example to be more compatible with ad blockers. I've referenced this issue from that one, because there's some great discussion here, but we only need to track the issue in one place. Thanks, again.

**Closed by jenniferfell** 2018-04-25 09:46 UTC
Labels: comp: docs, effort2: days, freq3: high, severity1: confusing, type: bug/fix
