### ISSUE TITLE
[DocViewer] error preparing document guide/pipes

### ISSUE THREAD

**Issue by kounelios13** [angular/angular#27040] opened 2018-11-10 09:01 UTC
# 📚 Docs or angular.io bug report

### Description
I was trying to find some documentation about pipes in angular.
However after clicking on the angular documentation the document would never load.Here is the stack trace from the console:

### What's the affected URL?**
https://angular.io/guide/pipes

## 🔥 Exception or Error

```
ERROR Error: "[DocViewer] Error preparing document 'guide/pipes': a@https://angular.io/runtime.b95c2950b9946468c610.js:1:1962
D@https://angular.io/polyfills.92ff7bd39a33b228eade.js:1:16702
0TWp/</</s</e.prototype.invokeTask@https://angular.io/polyfills.92ff7bd39a33b228eade.js:1:7769
onInvokeTask@https://angular.io/main.12cbd075231e48c67faf.js:1:58868
0TWp/</</s</e.prototype.invokeTask@https://angular.io/polyfills.92ff7bd39a33b228eade.js:1:7682
0TWp/</</i</t.prototype.runTask@https://angular.io/polyfills.92ff7bd39a33b228eade.js:1:2945
0TWp/</</c</t.invokeTask@https://angular.io/polyfills.92ff7bd39a33b228eade.js:1:8863
y@https://angular.io/polyfills.92ff7bd39a33b228eade.js:1:19791
_@https://angular.io/polyfills.92ff7bd39a33b228eade.js:1:20023
"
	render https://angular.io/main.12cbd075231e48c67faf.js:1:447117
	error https://angular.io/main.12cbd075231e48c67faf.js:1:12506
	_error https://angular.io/main.12cbd075231e48c67faf.js:1:393041
	error https://angular.io/main.12cbd075231e48c67faf.js:1:145403
	_error https://angular.io/main.12cbd075231e48c67faf.js:1:145697
	error https://angular.io/main.12cbd075231e48c67faf.js:1:145403
	_error https://angular.io/main.12cbd075231e48c67faf.js:1:393041
	error https://angular.io/main.12cbd075231e48c67faf.js:1:145403
	notifyError https://angular.io/main.12cbd075231e48c67faf.js:1:176370
	_error https://angular.io/main.12cbd075231e48c67faf.js:1:482943
	error https://angular.io/main.12cbd075231e48c67faf.js:1:145403
	o https://angular.io/main.12cbd075231e48c67faf.js:1:249539
	invoke https://angular.io/polyfills.92ff7bd39a33b228eade.js:1:7094
	onInvoke https://angular.io/main.12cbd075231e48c67faf.js:1:58956
	invoke https://angular.io/polyfills.92ff7bd39a33b228eade.js:1:7021
	run https://angular.io/polyfills.92ff7bd39a33b228eade.js:1:2254
	z https://angular.io/polyfills.92ff7bd39a33b228eade.js:1:13518
	invokeTask https://angular.io/polyfills.92ff7bd39a33b228eade.js:1:7769
	onInvokeTask https://angular.io/main.12cbd075231e48c67faf.js:1:58868
	invokeTask https://angular.io/polyfills.92ff7bd39a33b228eade.js:1:7682
	runTask https://angular.io/polyfills.92ff7bd39a33b228eade.js:1:2945
	v https://angular.io/polyfills.92ff7bd39a33b228eade.js:1:9998
	invokeTask https://angular.io/polyfills.92ff7bd39a33b228eade.js:1:8899
	y https://angular.io/polyfills.92ff7bd39a33b228eade.js:1:19791
	_ https://angular.io/polyfills.92ff7bd39a33b228eade.js:1:20023

```

### Browser info

Firefox 63
### Anything else relevant?

I tested the page on chromium and it works fine

**Comment by AndrewKushnir** [comment] 2018-11-12 04:48
Thanks for reporting this issue. However this issue is a duplicate of an existing issue #26540 (as @ericmartinezr mentioned in the comment above). Please refer to the mentioned thread to find additional information about the issue.

**Closed by AndrewKushnir** 2018-11-12 04:48 UTC
