### ISSUE TITLE
Issue on the angular website itself

### ISSUE THREAD

**Issue by pramodx** [angular/angular#2199] opened 2015-05-28 01:15 UTC
Not sure if this is the right forum but opening an issue nevertheless

I was looking at the bio page at https://angular.io/about/. I clicked on a bio once to view the person profile. I then close the bio and then click on the same bio again. Voila!! I get a 404. This is happening across bios and is easily reproducible.

https://angular.io/about/
![image](https://cloud.githubusercontent.com/assets/2028580/7850848/bdec4ba8-052a-11e5-802f-09b0cf93f4ef.png)

**Comment by pkozlowski-opensource** [comment] 2015-05-28 02:31
Duplicate of https://github.com/angular/angular.io/issues/132

**Closed by pkozlowski-opensource** 2015-05-28 02:31 UTC
