### ISSUE TITLE
Modify Components at runtime

### ISSUE THREAD

**Issue by SiddharthShyniben** [angular/angular#41243] opened 2021-03-17 14:33 UTC
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/router

### Description
 I wish components at certain routes could be modified at runtime. For example, the `/` route may hold a landing page but when a user logs in, the `/` route could be a dashboard etc.

### Describe the solution you'd like
 We could have a function which maybe changes certain routes which could be provided to the components? Honestly I don't know.

### Describe alternatives you've considered
 Maybe there could be a `*ngIf in the component which is at the `/` route described above which shows different components based on whether a user is logged in.

**Comment by AleksanderBodurri** [comment] 2021-03-17 15:37
Maybe https://angular.io/api/router/Router#resetConfig could help your use case?
```ts
// app.component.ts
//...
if (isLoggedIn) {
   this.router.resetConfig([ { path: '/', component: DashboardComponent } ]);
}
//...
```

Alternatively you can guard your root path with an [auth guard](https://angular.io/api/router/CanActivate) that redirects to a login route if a user is not logged in.

**Comment by atscott** [comment] 2021-03-17 16:07
Duplicate of #14515/#11151/#16211

**Closed by atscott** 2021-03-17 16:07 UTC
Labels: comp: router
