### ISSUE TITLE
AoT Compilation not detecting template error

### ISSUE THREAD

**Issue by josephliccini** [angular/angular#20287] opened 2017-11-08 21:16 UTC
## I'm submitting a...

<pre><code>
[x ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

A component has public properties, `heroTitle: string`, `v2Layout: boolean`.

In template:
```html
<ng-container *ngIf="v2Layout">
    {{ heroTitle }}
</ng-container>
```
This works, as expected, no error reported.

I will modify template like so:
```html
<ng-container *ngIf="v2Layout">
    {{ heroTitleeeeee }}
</ng-container>
```
Now, there is no error reported in the AoT compiler, even if I kill the watcher and do a full rebuild.

Furthermore, if one does this:
```html
<!-- <ng-container *ngIf="v2Layout"> -->
    {{ heroTitleeeeee }}
<!-- </ng-container> -->
```
We get a compilation error in AoT, both in Full Rebuild and Watcher

I am pretty sure this if happening because of `*ngIf` but no way to be sure.  I have seen this in other parts of our application too.  On things like `[class.foo]="something"` if an `*ngIf` is above it, the compiler won't catch typos, etc.

## Expected behavior
I would expect in each case where I am using `{{ heroTitleeeeee }}` the AoT compiler fails the build.

## Minimal reproduction of the problem with instructions

Above

## What is the motivation / use case for changing the behavior?

We'd like our AoT builds to be able to detect these errors so that we don't have typos and other issues on our templates before checking in / testing.

## Environment
Windows 10
<pre><code>
Angular version: 5.0.1

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX   Node 6.9.1
- Platform:   Windows

Others:

</code></pre>

**Comment by josephliccini** [comment] 2017-11-08 21:38
Actually I am seeing this on 4.4.4 as well.

Maybe it's related to a TypeScript version? We are using TS 2.4.2

**Comment by josephliccini** [comment] 2017-11-08 21:46
Tried TS 2.5.3 and TS 2.6.1, so unlikely it's a TS issue.  Maybe I am not configuring a setting correctly or something..

**Comment by trotyl** [comment] 2017-11-09 06:10
Can be reproduced in [edit.ng](edit.ng) directly.

**Comment by nonphatic** [comment] 2017-11-10 23:22
I'm seeing this issue for *ngFor as well. I tested it with the following:

In app.component.ts:
```
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  public title: string = "app";

  public bool: boolean = true;
  public variableInsideIf: string = "ngIfTest";

  public list: number[] = [1, 1, 2, 3, 5, 8, 13];
  public variableInsideFor: string = "ngForTest";
}
```

In app.component.ng.html:
```
<div style="text-align:center">
  <div>
    {{title}}
  </div>
  <div *ngIf="bool">
    {{variableInsideIf}}
  </div>
  <div *ngFor="let n of list">
    {{variableInsideFor}} {{n}}
  </div>
</div>
```

If I change `{{title}}` to `{{titleeee}}` or `{{title.dummy}}`, I get the compilation error, but if I change `{{variableInsideIf}}` to `{{variableInsideIffff}}` or `{{variableInsideFor}}` to `{{variableInsideForrrr}}` or `{{n}}` to `{{n.dummy}}` I don't get the error. 

I also tried compiling with `ngc` using @angular/compiler-cli@4.4.6, and this is what I see in the generated app.component.ngfactory.ts:
```
...
var _co:any = _v.component;
const currVal_0:any = _co.variableInsideIf;
...
var _co:any = _v.component;
const currVal_0:any = _co.variableInsideFor;
const currVal_1:any = _v.context.$implicit;
...
var _co:i3.AppComponent = _v.component;
const currVal_1:any = _co.bool;
const currVal_2:any = _co.list;
...
var _co:i3.AppComponent = _v.component;
const currVal_0:any = _co.title;
```
As you can see, when accessing `title`, `_co` has the correct type annotation of `AppComponent`, but when accessing `variableInsideIf` or `variableInsideFor`, `_co` has the type annotation of `any` instead, which is probably why the error isn't being caught on compilation. Additionally, the `n` inside the for loop corresponds here to `_v.context.$implicit`, but its type isn't checked anywhere, so changing `{{n}}` to `{{n.dummy}}` yields `_v.context.$implicit.dummy` which doesn't fail but I believe should, since we can trace that `n` is from `list` is from `AppComponent`, and it does fail for `title.dummy`.

**Comment by trotyl** [comment] 2017-11-26 13:15
@BorntraegerMarc fixed, just mean it literally.

**Comment by zmferrell** [comment] 2017-12-01 21:20
+1

**Comment by Magrangs** [comment] 2017-12-05 14:55
Same issue here.

**Comment by mhevery** [comment] 2017-12-05 23:21
This is a know bug which we are working on fixing right now.

Duplicate of https://github.com/angular/angular/issues/19792

**Closed by mhevery** 2017-12-05 23:21 UTC
Labels: comp: core & compiler, type: bug

**Comment by josephliccini** [comment] 2017-12-05 23:53
Thanks @mhevery ! 

fwiw with issues like https://github.com/angular/angular/issues/19792 it might be good to put a brief summary for those outside Google just so we don't duplicate bugs in your bug tracker 😄

**Comment by lichunr** [comment] 2019-01-04 04:05
any update on this one? we're still facing this issue, thanks

**Comment by vanslly** [comment] 2019-06-27 04:11
@lichunr For some additional template type checking you should set `fullTemplateTypeCheck = true` in your `tsconfig.json`: https://angular.io/guide/aot-compiler#fulltemplatetypecheck

Template type checking is still poor, but is improved with Renderer 3 (Ivy). Even with Angular 8 with Renderer 3 you still need to set `fullTemplateTypeCheck = true` and in the future this will be on by default. Only reason it's not on by default is for backwards compatibility.

**Comment by lichunr** [comment] 2019-06-27 08:42
@vanslly Thx for the solution!
