### ISSUE TITLE
":leave" animation of child component doesn't work when the parent has its own animations

### ISSUE THREAD

**Issue by ilyakonrad** [angular/angular#40799] opened 2021-02-11 12:53 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/animations: 11.0.9

### Description
There are two components: the parent component and **Modal** component (the child).

**Modal** component has its own animations so that when I render/destroy it with `*ngIf`, it appears or gets hidden smoothly.

In my case the parent component also has separate animations for inner separate html elements (which have no connection to the **Modal**).

As a result ":leave" animation of **Modal** doesn't work unless I completely remove `animations: [...]` property from parent's `@Component()` decorator.

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-ivy-685zhb?file=src/app/app.component.ts

There's animated text element which you can toggle by pressing "Toggle text!".

1. Open the modal by clicking "Show modal!" and then try to close it either by clicking the button or by clicking outside.
Result: modal gets closed **without** animation.

2. Then comment out `animations: [...]` property in `@Component()` decorator. Try to open and close the modal again.
Result: modal gets closed **with** animation as expected. However, as expected, the text animation no longer works.

**Expected result**: it should be possible to nest components with animations into components that have their own animations without sacrificing either of the animations.

## 🌍  Your Environment

**Angular Version:**
<pre><code>angular-cli: 1.0.0-beta.28.3
node: 15.6.0
os: win32 x64
@angular/animations: 11.0.9
@angular/common: 11.0.9
@angular/compiler: 11.0.9
@angular/core: 11.0.9
@angular/fire: 6.1.4
@angular/forms: 11.0.9
@angular/platform-browser: 11.0.9
@angular/platform-browser-dynamic: 11.0.9
@angular/router: 11.0.9
@angular/cli: 11.0.7
@angular/compiler-cli: 11.0.9
@angular/language-service: 11.0.9
</code></pre>

**Comment by jelbourn** [comment] 2021-02-12 21:38
Duplicate of #35825 in terms of parent-child enter/leave animation interaction not working as expected

**Closed by jelbourn** 2021-02-12 21:38 UTC
Labels: comp: animations
