### ISSUE TITLE
Error: Unsupported number of argument for pure functions in ngClass directive

### ISSUE THREAD

**Issue by DarienF** [angular/angular#14643] opened 2017-02-22 12:45 UTC
[ * ] bug report 
[ ] feature request
[ ] support request

When I try to add to many cases info [ngClass] directive appear an error:
```
[ngClass]="{ 
'COAAccount': node.data.type == 1, 
'COACounter': node.data.type == 3, 
'COAMirrorAccountMinus': node.data.type == 4, 
'COAAccountCopy': node.data.type == 5, 
'COAResult': node.data.type == 6, 
'COAComment': node.data.type == 7,
'margin-left-level-0': level == 0,
'margin-left-level-1': level == 1,
'margin-left-level-2': level == 2,
'margin-left-level-3': level == 3                        
'margin-left-level-4': level == 4
}"
```

EXCEPTION: Uncaught (in promise): Error: Unsupported number of argument for pure functions: 11
Error: Unsupported number of argument for pure functions: 11

When remove last case `'margin-left-level-4': level == 4` all working fine. I assume there is some limitation for how many cases you can add into [ngClass] directive.

**Comment by DzmitryShylovich** [comment] 2017-02-22 12:48
Duplicate of https://github.com/angular/angular/issues/12233

> I assume there is some limitation for how many cases you can add into [ngClass] directive.

Yes, there's a limitation for performance reasons

**Comment by DarienF** [comment] 2017-02-22 12:51
This limitation will be enlarge in future or 10 cases stay as max value?

**Comment by DzmitryShylovich** [comment] 2017-02-22 12:53
I think it will stay as is.
Just declare your classes inside a component. Keep your template as simple as possible
```
[ngClass]="classes"

export class MyCmp {
   classes = { 
'glyphicon-triangle-bottom': node.expanded && node.children.length > 0, 
'glyphicon-triangle-right': !node.expanded && node.children.length > 0,
'margin-left-level-0': level == 0,
'margin-left-level-1': level == 1,
'margin-left-level-2': level == 2,
'margin-left-level-3': level == 3,
'margin-left-level-4': level == 4
};
}
```

**Comment by DarienF** [comment] 2017-02-22 13:00
Same error appear when I try to relocate all into component class.

**Closed** 2017-02-22 13:00 UTC

**Comment by DzmitryShylovich** [comment] 2017-02-22 13:03
add a plunkr

**Comment by rafusfx** [comment] 2017-03-22 23:54
THe samething is happening for ngStyles, I tried the workaround below is not working too
[ngStyle]="styles"

export class MyCmp {

@Input('Color') color:string;
@Input('FontSize') size:string;
@Input('FontWeight') weight:string;
@Input('Border') border:string;
@Input('BorderTop') borderTop:string;
@Input('BorderBottom') borderBottom:string;
@Input('BorderLeft') borderLeft:string;
@Input('BorderRight') borderRight:string;
@Input('TextShadow') textShadow:string;
@Input('Margin') margin:number;
@Input('MarginLeft') marginLeft:number;
@Input('MarginRight') marginRight:number;
@Input('MarginTop') marginTop:number;
@Input('MarginBottom') marginBottom:number;
@Input('Padding') padding:number;
@Input('PaddingLeft') paddingLeft:number;
@Input('PaddingRight') paddingRight:number;
@Input('PaddingTop') paddingTop:number;
@Input('PaddingBottom') paddingBottom:number;

   styles = {'color':this.color,'font-size':this.size + 'px','font-weight':this.weight,'border':this.border,'text-shadow':this.textShadow,'margin-top':this.marginTop + 'px','margin-right':this.marginRight + 'px','margin-bottom': this.marginBottom + 'px','margin-left': this.marginLeft + 'px','margin':this.margin + 'px','padding-top':this.paddingTop + 'px','padding-right': this.paddingRight + 'px','padding-bottom': this.paddingBottom + 'px','padding-left':this.paddingLeft + 'px','padding':this.padding + 'px'};
}
