### ISSUE TITLE
Add line numbers / file name for error: "Cannot assign to a reference or variable!"

### ISSUE THREAD

**Issue by uber5001** [angular/angular#17179] opened 2017-06-02 16:58 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When getting the error: "Cannot assign to a reference or variable!":

- with `ng b --aot` or `ng b --prod`: The error consists of `ERROR in Cannot assign to a reference or variable!` with no line number or file. The following error is the entire module failing to be resolved.
- with `ng b`: The error occurs at runtime instead, giving a `Unhandled Promise rejection: Cannot assign to a reference or variable! ; Zone: <root> ; Task: Promise.then ; Value: Error: Cannot assign to a reference or variable!`, and the stack trace points at `vendor.bundle.js`.

**Expected behavior**

When getting the error: "Cannot assign to a reference or variable!", there should be a file and line number associated with the error.

At the very least, including a component name with the error would suffice in my case.

**Minimal reproduction of the problem with instructions**

[plunker link.](http://plnkr.co/edit/eQIgs0n3aGKGCLBWjkad?p=preview) Error shows up in console, but doesn't point the the source of the problem.

**What is the motivation / use case for changing the behavior?**

Errors should point towards the thing that caused the error. Especially useful since I'm pretty sure I have this error in many places.

**Please tell us about your environment:**

* **Angular version:** 4.1.3

* **Browser:** all

 
* **Language:** TypeScript 2.1

* **Node (for AoT issues):** `node --version` =  v6.10.2

**Comment by AHelper** [comment] 2017-12-06 16:55
I've hit [essentially the same issue here](http://plnkr.co/edit/TSq1ADSuVK5REJk855gN?p=preview) when doing a bunch of refactoring to migrate from Angular 2.x to 5.x.  Sticking a `console.log(ast.name)` at the point the Error was thrown in the compiler UMD at least helped me pin down what variable to search for that was causing this.  (I'm on Angular 5.0.5, TS 2.4.2.)

**Comment by Zarepheth** [comment] 2019-02-15 18:21
I came across the same problem. After following @AHelper's suggestion (with a little more work - `JSON.stringify`) I was able to track down the source of my error.

In my case, I was doing a "banana in a box" binding to an `*ngIf` iteration variable. Separating that binding into two bindings, one for input and the second for change handling, I was able to work around the compiler error.

**Comment by pauldraper** [comment] 2019-05-08 14:23
This continues to be an issue in Angular 7.

**Comment by pyrarhum1** [comment] 2019-05-29 10:07
If i build with `ng --build`, it succeeds.

If I build with `ng build --prod --verbose` , the issue is coming during terser optimization :

ERROR in Cannot assign to a reference or variable!

 My environment : 

> Angular CLI: 7.3.9
> Node: 10.15.3
> OS: win32 x64
> Angular: 7.2.15
>

**Comment by pyrarhum1** [comment] 2019-05-29 12:33
The error occurs when `"fullTemplateTypeCheck": true` in tsconfig.json.

It's not possible to find out the error, when you have no stacktrace. :(.

**Comment by ido172** [comment] 2019-07-08 09:25
I'm working on changing a huge project from using SystemJS to Angular-CLI and it is very frustrating to get an error while building and not knowing where to look for it in the code... wasted a full day trying to figure it out with no success... 
thank you @pyrarhum1, changing `fullTemplateTypeCheck` solved the problem for now

**Comment by Cito** [comment] 2019-08-20 07:07
As @Zarepheth noticed, the error can happen if you do two-way-bind to an iteration variable from a `*ngFor` loop. One workaround is separating the bindings, another workaround is using an index variable and binding to an indexed expression.

Anyway, this should be fixed - the compiler should show the name of the template and location, and the name of the problematic variable. Currently only hacking the compiler as @AHelper suggested gives you a clue where the error is.

@pyrarhum1 is right, setting `"fullTemplateTypeCheck": false` can be used to sweep these kind of errors under the rug, but some of these type error messages can be really useful, so you usually would want to keep this set to `true`.

**Comment by eixin** [comment] 2019-09-17 08:49
This continues to be an issue in Angular 8

**Comment by Chad-Krause** [comment] 2020-01-29 19:33
+1 on this.

Still an issue in Angular 8. I fixed it doing what @Cito and @Zarepheth suggested, switching a two-way bind into two separate binds.

Ex:
From:
`<demo-editor [(board)]='board'></demo-editor>`
To:
`<demo-editor [board]='board' (boardChange)='board=$event'></demo-editor>`

**Comment by pkozlowski-opensource** [comment] 2020-03-12 14:47
With Angular 9 running ivy the error messages are much clearer and point to the exact location (file, line, column) in a template, ex.: https://ng-run.com/edit/ucFS2VKwifIjtJBg8cUo

**Closed by pkozlowski-opensource** 2020-03-12 14:47 UTC
Labels: comp: core, freq2: medium, hotlist: error messages, severity3: broken, type: bug/fix
