### ISSUE TITLE
Enable a reactive form using the FormControlDirective

### ISSUE THREAD

**Issue by sgkazakov** [angular/angular#20008] opened 2017-10-29 22:59 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Currently the FormControlDirective can't handle `disabled` property change from true to false.

## Expected behavior
The FormControlDirective will update the control disabled property from true to false.

## Minimal reproduction of the problem with instructions

https://plnkr.co/edit/hIg6qdPcwqykc1K6jRUd?p=preview
1. Click on the button.
2. The FormControlDirective will update the control disabled property from false to true.
3. Click it button again.
2. The FormControlDirective will NOT update the control disabled property from true to false.

## What is the motivation / use case for changing the behavior?

I would like to be able to use the FormControlDirective to set the disabled property of a control from true to false.

## Environment

<pre><code>
Angular version: 4.4.6

Browser:
- [x] Chrome (desktop) 62.0.3202.75 (Official Build)
- [x] IE version 11.15.16299.0
- [x] Microsoft Edge 41.16299.15.0

**Comment by trotyl** [comment] 2017-10-30 02:03
Not related to `NgFor`, currently `FormControlDirective` won't respect `disabled` property change from `true` to `false`, while https://github.com/angular/angular/commit/51d73d3e4e490cb12715edf0eae1e46b4d42d8a0 only handles the condition from `false` to `true`.

**Comment by sgkazakov** [comment] 2017-10-30 04:29
@trotyl Thank you. I've updated the issue and the plunker.

**Comment by trotyl** [comment] 2017-11-16 08:42
Found it was duplicate of #17806.

**Comment by dzonatan** [comment] 2017-11-23 16:52
The fix is hanging in #18575 ...

**Comment by kara** [comment] 2018-01-23 23:59
Looks like a duplicate

**Closed by kara** 2018-01-23 23:59 UTC
Labels: comp: forms, severity3: broken, type: bug
