### ISSUE TITLE
Docs for localize not found

### ISSUE THREAD

**Issue by adambondarzewski** [angular/angular#56451] opened 2024-06-14 08:18 UTC
### Describe the problem that you experienced

https://angular.dev/api/localize and https://angular/api/localize are not available, despite mentioning in "what's next" section of: https://angular.dev/guide/i18n/add-package

**Comment by JoostK** [comment] 2024-06-14 08:21
Duplicate of #54388

**Closed by JoostK** 2024-06-14 08:21 UTC
