### ISSUE TITLE
Can't compile animations in AOT with dynamic keys

### ISSUE THREAD

**Issue by Murazaki** [angular/angular#17406] opened 2017-06-11 13:22 UTC
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When compiling in aot with `ng serve`, it gives this error :
``` shell
ERROR in Error encountered resolving symbol values statically. Expression form not supported (position 7:9 in the original .ts file), resolving symbol slideInAnimation in .../slide.animation.ts, resolving symbol TestComponent in .../test.component.ts, resolving symbol TestComponent in .../test.component.ts

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in '.../src'
 @ ./src/main.ts 4:0-74
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts
webpack: Failed to compile.
```

**Expected behavior**
`ng serve --aot` should compile

**Minimal reproduction of the problem with instructions**
Use dynamic keys in an AnimationStyleMetadata called in a component, then compile in AOT :

``` typescript
import { AnimationTriggerMetadata, trigger, animate, transition, style } from '@angular/animations';

export function slideInAnimation(side: 'left' | 'right' | 'top' | 'bottom' = 'left', time: number|string = '.5s ease-out', startPos: number|string = '-400%', endPos: number|string = '*'): AnimationTriggerMetadata {
  return trigger('slideInAnimation', [
    transition(':enter', [
      style({
        [side]: startPos // issue happens here, with the dynamic key
      }),
      animate(time, style({
        [side]: endPos // issue happens here, with the dynamic key
      }))
    ])
  ]);
}

export function slideOutAnimation(side: 'left' | 'right' | 'top' | 'bottom' = 'left', time: number|string = '.5s ease-out', startPos: number|string = '*', endPos: number|string = '-400%'): AnimationTriggerMetadata {
  return trigger('slideOutAnimation', [
    transition(':leave', [
      style({
        [side]: startPos // issue happens here, with the dynamic key
      }),
      animate(time, style({
        [side]: endPos // issue happens here, with the dynamic key
      }))
    ])
  ]);
}
```

**What is the motivation / use case for changing the behavior?**
Being able to dynamically change the keys in an object without running into a compilation issue in aot

**Please tell us about your environment:**
MacBook Pro (Retina 13' 2015)
MacOS Sierra 10.12.5 (16F73)

node 8.0.0 (installed via Brew)
yarn 0.24.6 (installed via Brew)
atom 1.17.2

* **Angular version:** 4.1.3

* **Browser:** all
 
* **Language:** TypeScript 2.3.4

* **Node (for AoT issues):** `node --version` =   v8.0.0

**Comment by Murazaki** [comment] 2017-06-11 13:23
#13132

**Comment by Murazaki** [comment] 2017-06-11 13:25
The issue is quite similar to #13132 but I think needed it's own report.

**Comment by pumano** [comment] 2017-06-14 15:15
I got same error, when my export function don't have `return` statement. It's always occured.

Details mentioned here:
https://github.com/angular/angular/issues/13132#issuecomment-267709474
and here:
https://github.com/angular/angular/issues/12917

Expected result:
If `return` statement should be _must have_, AOT compiler should return proper error handling.

Simple reproducing:
1) clone https://github.com/aiboy/ngx-page-transition-example 
2) npm install
3) ng build --prod --aot

Details:
**animations.ts** not contain `return` statement
```

import { trigger, transition, animate, style, state } from '@angular/animations';

export default {
  /**
   * Page transition animation
   */
  pageTrasition: trigger('routeAnimation', [
    state('*',
      style({
        opacity: 1,
        transform: 'translateX(0)'
      })
    ),
    transition('void => *', [
      style({
        opacity: 0,
        transform: 'translateY(-20%)'
      }),
      animate('0.8s ease-in')
    ]),
    transition('* => void', [
      animate('0.9s ease-out', style({
        opacity: 0,
        transform: 'translateY(100%)'
      }))
    ])
  ])
};
```
**Home.component.ts**
```

import Animations from './../animations';
import { Component, OnInit, HostBinding } from '@angular/core';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css'],
  animations: [ Animations.pageTrasition ]
})
export class HomeComponent implements OnInit {
  @HostBinding('@routeAnimation') get routeAnimation() {
    return true;
  }

  constructor() { }

  ngOnInit() {
  }

}
```

**Angular version:** 4.1.3
**Angular CLI:** 1.0.0 / 1.1.1

**Browser:** all

**Language:** TypeScript 2.3.4

**Comment by JoostK** [comment] 2020-03-14 16:19
Since Ivy, animations metadata is no longer statically analyzed but passed through to the runtime as-is. As such, closing as resolved.

**Closed by JoostK** 2020-03-14 16:19 UTC
Labels: comp: animations, comp: compiler, type: feature
