### ISSUE TITLE
[attr.disabled] not working as expected after upgrading to ang17

### ISSUE THREAD

**Issue by mahalinge** [angular/angular#57293] opened 2024-08-07 17:56 UTC
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

No idea ,was working fine in angular 14 and after upgrading to 17 ,stopped working 

### Description

[attr.disabled] not working as expected after upgrading to ang17

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.3.8
Node: 18.20.4
Package Manager: npm 10.7.0
OS: win32 x64
```

**Comment by JeanMeche** [comment] 2024-08-07 17:58
Hi, could you provide a stackblitz reproduction that illustrates the issue you're having, thank you.

**Comment by JoostK** [comment] 2024-08-07 22:11
I am going to close this as a (speculated) duplicate of #48350.

**Closed by JoostK** 2024-08-07 22:11 UTC
Labels: needs reproduction, area: forms
