### ISSUE TITLE
FEATURE: extend template syntax with "directives" allowing import of "static types"

### ISSUE THREAD

**Issue by kukjevov** [angular/angular#33652] opened 2019-11-07 14:27 UTC
# 🚀 feature request

### Relevant Package
@angular/core
@angular/common - maybe, not sure?

### Description
It would be nice to have possibility to use *static types* inside templates without need of putting them into component. 

Imagine that you have `Enum` or `Type<>` that you want to use in template, for example you have `ngIf` and you want to compare value of some property with `Enum` value. You have to do following in order to allow this comparison in your template.

``` ts
import {TestEnum} from './testEnum';

export class TestComponent
{
  //with some special directive syntax in template this could be removed
  public TestEnum = TestEnum;

  public testValue: TestEnum = TestEnum.Prva;
}
```

Asp.Net Core Razor syntax has something similar which is called *[directives](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/razor?view=aspnetcore-3.0#directives)* 

Angular templates have already special syntax, so i think this would be possible. 

### Describe the solution you'd like
In order to make it simpler (maybe not, im not specialist on angular template compilation), but it would be nice to have some special syntax at top of html template something like
`{{@import {TestEnum} from './testEnum';}}` or something which would extend context with property of same name and value passed from import. This *special directives* {{@directive expression}} could be used also for something different (maybe `{{@inject ElementRef}}`)

### Describe alternatives you've considered
Workaround is just to add it manualy to `Component`, but this `template directives` would be nicer.

As i said it would be nice, it is not necessary :).
Thx

**Comment by Airblader** [comment] 2019-11-07 17:02
Angular currently doesn't use any custom syntax on TS side, the files are completely valid TS. This proposal would change that and break a lot of tooling.

**Comment by LingVuDev** [comment] 2019-12-12 10:20
That's something that I am missing. I have posted a question for other possible options:
https://stackoverflow.com/questions/59289095/use-of-enums-in-angular-8-html-template-for-ngif/59289239#59289239

**Comment by pkozlowski-opensource** [comment] 2021-07-20 08:00
This is essentially a duplicate of #25963 - it describes the same problem (easier access to things from the JS scope, usually the problem manifests itself when people are trying to access enums, static fields or just JS imports). This issue proposes an alternative syntax but we should group all those issues together to focus on the problem.

Closing as duplicate of #25963

**Closed by pkozlowski-opensource** 2021-07-20 08:00 UTC
Labels: comp: core, core: binding & interpolation, feature, insufficient votes, votes required
