### ISSUE TITLE
Broken link in the roadmap page

### ISSUE THREAD

**Issue by andresmq** [angular/angular#53807] opened 2024-01-05 11:54 UTC
### Describe the problem that you experienced

The following link is present in the roadmap page (https://angular.dev/roadmap) but it doesn't work: [Try out Inject](https://angular.dev/di)

### Enter the URL of the topic with the problem

https://angular.dev/roadmap

### Describe what you were looking for in the documentation

Nothing special, just reading the readmap

**Comment by JoostK** [comment] 2024-01-05 19:04
Thanks for the report, this is a duplicate of https://github.com/angular/angular/issues/52539 for which the fix is pending deployment.

**Closed by JoostK** 2024-01-05 19:04 UTC
