### ISSUE TITLE
AOT compilation fails when "noUnusedParameters" is set

### ISSUE THREAD

**Issue by n9niwas** [angular/angular#15475] opened 2017-03-25 00:33 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

`ngc` command fails when "noUnusedParameters" is set in tsconfig.json with `'$event' is declared but never used` even if `$event` is not declared anywhere.

**Expected behavior**

`ngc` should not fail when "noUnusedParameters" is set in tsconfig.json.

**Minimal reproduction of the problem with instructions**

[Repository with reproduction](https://github.com/n9niwas/ngissue). Run `yarn start` (`npm start`).

**What is the motivation / use case for changing the behavior?**

Support of "noUnusedParameters" TypeScript setting.

**Please tell us about your environment:**

Operating system: Windows 10.

* **Angular version:** 4.0.0

 
* **Language:** [TypeScript 2.2]

* **Node (for AoT issues):** `node --version` =  v7.7.2

**Comment by DzmitryShylovich** [comment] 2017-03-25 05:57
Duplicates https://github.com/angular/angular/issues/11074

**Comment by IgorMinar** [comment] 2017-03-29 07:26
Thanks for reporting this issue. However this issue is a duplicate of an existing issue #11074. Please subscribe to that issue for future updates.

**Closed by IgorMinar** 2017-03-29 07:26 UTC
