### ISSUE TITLE
[AoT] Compilation visiting unused files

### ISSUE THREAD

**Issue by catahoc** [angular/angular#21182] opened 2017-12-27 14:39 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
User create 2 main files (for example, he develops 2 apps with some variance): main.ts, main2.ts
main.ts imports and bootstraps AppModule
main2.ts imports and bootstraps App2Module
both AppModule provide similar AppComponent

Prod compilation for main.ts fails with
<pre>
ERROR in : Type AppComponent in <path>/src/app/app.component.ts is part of the declarations of 2 modules: AppModule in <path>/src/app/app.module.ts and App2Module in <path>/src/app/app2.module.ts! Please consider moving AppComponent in <path>/src/app/app.component.ts to a higher module that imports AppModule in <path>/src/app/app.module.ts and App2Module in <path>/src/app/app2.module.ts. You can also create a new NgModule that exports and includes AppComponent in <path>/src/app/app.component.ts then import that NgModule in AppModule in <path>/src/app/app.module.ts and App2Module in <path>/src/app/app2.module.ts.

</pre>

## Expected behavior
Prod compilation must succeed, because dependency tree starting from main.ts should not visit neither main2.ts, nor App2Module.ts

## Minimal reproduction of the problem with instructions
* run "ng new project-name"
* copy app.module.ts => app2.module.ts
* rename module in app2.module.ts; AppModule => App2Module
* clone main.ts => main2.ts
* bootstrap App2Module in main2.ts instead of AppModule 
* run "ng serve --prod" - it is configured to bootstrap main.ts and AppModule by default... but currently it fails

Here is prepared project with performed steps
[compile-bug.zip](https://github.com/angular/angular/files/1589202/compile-bug.zip)

## What is the motivation / use case for changing the behavior?
My team has 2 application prod build configs for 2 different types of user (elevated and non-elevated): 2 mains, 2 AppModule's, etc. AppModule's define same bootstrapComponent

## Environment

<pre><code>
- Angular version: 5.1.2
- Node version: 9.3.0, npm version 5.6.0
- Platform:  Windows 7
</code></pre>

**Comment by trotyl** [comment] 2017-12-28 03:49
Duplicate of #13590 and #21131, this use case has already been discussed.

**Closed** 2017-12-28 10:13 UTC
Labels: comp: core & compiler
