### ISSUE TITLE
rxjs/observable, rxjs/subject latest configuring issue

### ISSUE THREAD

**Issue by sastrygbs** [angular/angular#11856] opened 2016-09-23 09:50 UTC
Hi,
I tried searching in github but nothing helped 

I am trying to run Angular 2 on New Visual Studio 2015 with basic setup
installed latest libraries 
npm:3.10.7, 
typescript: 2.0.3, 
node js: v6.6.0,
rxjs: 5.0.0-beta.12,
angular2: 2.0.0-beta.17
when I run in chrome getting error like "Failed to load resource: the server responded with a status of 404 (Not Found)"
Can anybody help me on this?
![err](https://cloud.githubusercontent.com/assets/5327318/18780209/0bcb6402-819a-11e6-80c6-9673121799ee.jpg)

**Comment by pkozlowski-opensource** [comment] 2016-09-23 09:53
Duplicate of #11852. Please do _not_ re-open the same issue for the support request but rather seek help on dedicated support channels: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

This is _not_ the the problem with Angular but rather with your local setup. There is nothing to fix in this repo hence this is a support request that needs to be asked on a support channel, not here.

**Closed by pkozlowski-opensource** 2016-09-23 09:53 UTC
