### ISSUE TITLE
https://angular.dev/assets/tutorials/common leads to a 404 page

### ISSUE THREAD

**Issue by KarkanAlzwayed** [angular/angular#55163] opened 2024-04-02 02:26 UTC
### Describe the problem that you experienced

Hello, I am following the "first app" tutorial, and in one of the steps it had me set the baseUrl as 'https://angular.dev/assets/tutorials/common', and this url actually leads to a 404 page. I noticed that the images are not showing on the page while I was working on the code. Instead, the places where the houses were supposed to show with their images, now shows ""Exterior photo of <housing location name>". Thought I'd bring to your attention to hopefully get it fixed.

### Enter the URL of the topic with the problem

https://angular.dev/assets/tutorials/common

### Describe what you were looking for in the documentation

Following the "first app" tutorial

### Describe the actions that led you to experience the problem

Referencing https://angular.dev/assets/tutorials/common to get images to show in the webpage I'm creating following the tutorial

### Describe what you want to experience that would fix the problem

For the images to show on the page

### Add a screenshot if that helps illustrate the problem

![image](https://github.com/angular/angular/assets/49320606/cd6be4b7-0fac-468e-88fa-959797f7689c)

### Provide any additional information here in as much as detail as you can

```true
This is the code where the URL is referenced

import {Component} from '@angular/core';
import {CommonModule} from '@angular/common';
import {HousingLocationComponent} from '../housing-location/housing-location.component';
import {HousingLocation} from '../housinglocation';
@Component({
  selector: 'app-home',
  standalone: true,
  imports: [CommonModule, HousingLocationComponent],
  template: `
    <section>
      <form>
        <input type="text" placeholder="Filter by city" />
        <button class="primary" type="button">Search</button>
      </form>
    </section>
    <section class="results">
      <app-housing-location
        *ngFor="let housingLocation of housingLocationList"
        [housingLocation]="housingLocation"
      ></app-housing-location>
    </section>
  `,
  styleUrls: ['./home.component.css'],
})
export class HomeComponent {
  readonly baseUrl = 'https://angular.dev/assets/tutorials/common';
  housingLocationList: HousingLocation[] = [
    {
      id: 0,
      name: 'Acme Fresh Start Housing',
      city: 'Chicago',
      state: 'IL',
      photo: `${this.baseUrl}/bernard-hermant-CLKGGwIBTaY-unsplash.jpg`,
      availableUnits: 4,
      wifi: true,
      laundry: true,
    },
    {
      id: 1,
      name: 'A113 Transitional Housing',
      city: 'Santa Monica',
      state: 'CA',
      photo: `${this.baseUrl}/brandon-griggs-wR11KBaB86U-unsplash.jpg`,
      availableUnits: 0,
      wifi: false,
      laundry: true,
    },
    {
      id: 2,
      name: 'Warm Beds Housing Support',
      city: 'Juneau',
      state: 'AK',
      photo: `${this.baseUrl}/i-do-nothing-but-love-lAyXdl1-Wmc-unsplash.jpg`,
      availableUnits: 1,
      wifi: false,
      laundry: false,
    },
    {
      id: 3,
      name: 'Homesteady Housing',
      city: 'Chicago',
      state: 'IL',
      photo: `${this.baseUrl}/ian-macdonald-W8z6aiwfi1E-unsplash.jpg`,
      availableUnits: 1,
      wifi: true,
      laundry: false,
    },
    {
      id: 4,
      name: 'Happy Homes Group',
      city: 'Gary',
      state: 'IN',
      photo: `${this.baseUrl}/krzysztof-hepner-978RAXoXnH4-unsplash.jpg`,
      availableUnits: 1,
      wifi: true,
      laundry: false,
    },
    {
      id: 5,
      name: 'Hopeful Apartment Group',
      city: 'Oakland',
      state: 'CA',
      photo: `${this.baseUrl}/r-architecture-JvQ0Q5IkeMM-unsplash.jpg`,
      availableUnits: 2,
      wifi: true,
      laundry: true,
    },
    {
      id: 6,
      name: 'Seriously Safe Towns',
      city: 'Oakland',
      state: 'CA',
      photo: `${this.baseUrl}/phil-hearing-IYfp2Ixe9nM-unsplash.jpg`,
      availableUnits: 5,
      wifi: true,
      laundry: true,
    },
    {
      id: 7,
      name: 'Hopeful Housing Solutions',
      city: 'Oakland',
      state: 'CA',
      photo: `${this.baseUrl}/r-architecture-GGupkreKwxA-unsplash.jpg`,
      availableUnits: 2,
      wifi: true,
      laundry: true,
    },
    {
      id: 8,
      name: 'Seriously Safe Towns',
      city: 'Oakland',
      state: 'CA',
      photo: `${this.baseUrl}/saru-robert-9rP3mxf8qWI-unsplash.jpg`,
      availableUnits: 10,
      wifi: false,
      laundry: false,
    },
    {
      id: 9,
      name: 'Capital Safe Towns',
      city: 'Portland',
      state: 'OR',
      photo: `${this.baseUrl}/webaliser-_TPTXZd9mOo-unsplash.jpg`,
      availableUnits: 6,
      wifi: true,
      laundry: true,
    },
  ];
}
```

**Comment by dalenguyen** [comment] 2024-04-02 20:50
I'd love to help with this one if it's possible. 

There's another issue with the webcontainer where even though you put the correct links. The image will not show on the `angular.dev` due to CORS issue. 

<img width="773" alt="image" src="https://github.com/angular/angular/assets/14116156/5e3ee07d-87a3-4966-a2e6-2938416f543c">

**Comment by JeanMeche** [comment] 2024-04-25 22:56
I'm going to close this as a dupe of #52794

**Closed by JeanMeche** 2024-04-25 22:56 UTC
Labels: P3, area: adev
