### ISSUE TITLE
Angular 2 Accessing Nested FormArrays using FormBuilder

### ISSUE THREAD

**Issue by deepikabhandari2592** [angular/angular#12279] opened 2016-10-13 17:02 UTC
@Brocco ,@jmachnik
 First of all I just begin with Angular 2 and I'm trying to build a nested form and validate it.I had posted this question on stackoverflow but dint got any reply so raising this question as a bug .Please revert with the solution as soon as possible .Thank you
Here's part of my ts file:

@ngOnInit() {
this.myForm = this.formBuilder.group({
projects: this.formBuilder.array([
this.initProjects()
])
});
}

initProjects(): any {
return this.formBuilder.group({
name: ['', [Validators.required, Validators.minLength(3)]],
some_array: this.formBuilder.array([
this.formBuilder.group({
name: ['', Validators.required],
attr: ['', Validators.required],
some_id: [1, Validators.required]
})
])
});
}

addProject(): void {
const control = < FormArray > this.myForm.controls['projects'];
control.push(this.initProjects());
}

View:

Nome é requerido
Submit
form value: 
{{myForm.value | json}}
form value: 
{
"projects": [
{
"name": "",
"some_array": [
{
"name": "",
"attr": "",
"some_id": 1
}
]
},
{
"name": "",
"some_array": [
{
"name": "",
"attr": "",
"some_id": 1
}
]
}
]
}

Well, as you can see I have some arrays called projects, with 1 array inside each one.

So the problem is that I'm not able to validate each control of some_array array.

Actually I'm getting the following error:

ORIGINAL EXCEPTION: Cannot find control with path: 'projects -> 0 -> controls.some_array.controls.name
PS: I already tried to put it in a div, as below:

But I also got an error:

Cannot find control with path: 'projects -> some_array'
Thanks in advance. Any help would be appreciated.

**Comment by deepikabhandari2592** [comment] 2016-10-13 17:06
@Brocco ,@jmachnik :+1: If this is difficult to read,you can also refer 
http://stackoverflow.com/questions/40026089/angular-2-accessing-nested-formarrays-using-formbuilder

**Comment by manklu** [comment] 2016-10-13 17:12
Duplicate of #12277

**Comment by deepikabhandari2592** [comment] 2016-10-13 17:21
@manklu : Even that is not having the solution .

**Comment by manklu** [comment] 2016-10-13 17:25
As for me, you have an answer.

>You should provide at least a [Plunker](http://plnkr.co/). Then someone might be willing to take a look at it.

**Comment by pkozlowski-opensource** [comment] 2016-10-13 17:26
@deepikabhandari2592 opening _multiple_ issues for the _same_ problem is not going to get you answers any faster. Closing as a duplicate of #12277

**Closed by pkozlowski-opensource** 2016-10-13 17:26 UTC
