### ISSUE TITLE
HammerModule - order of import issue

### ISSUE THREAD

**Issue by PawelJastrzebski** [angular/angular#40893] opened 2021-02-17 20:57 UTC
# 📚 Docs or angular.io bug report

### Description
Hi,
Order of import HammerModule cause that hammer.js not working

### What's the affected URL?
https://angular.io/api/platform-browser/HammerModule

### Reproduction Steps**
Repo: https://github.com/Anderies/gesture-angular
File: src/app/app.module.ts
```
 imports: [
    HammerModule,
    // Move up HammerModule
    BrowserModule,
    AppRoutingModule,
    // SHOULD BE IMPORTS AT ANGULAR 9
  ],
```

### Expected vs Actual Behavior**
When you move import above then hammer.js not working. This should be included in the documentation.

## 🌍  Your Environment
Ubuntu 20.04
### Browser info
Agent: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"

**Comment by zarend** [comment] 2021-02-17 21:21
ty for reporting, this is a duplicate of https://github.com/angular/angular/issues/37149

**Closed by zarend** 2021-02-17 21:21 UTC
Labels: P4, comp: core, comp: docs, needs clarification, subtype: docs-clarification
