### ISSUE TITLE
NgForOf doesn't reuse components during change detection

### ISSUE THREAD

**Issue by makkgregory** [angular/angular#44358] opened 2021-12-02 23:46 UTC
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

No

### Description

Each change detection cycle NgForOf directive destroys components with changed inputs and creates new ones. That leads to entire new DOM subtrees for these components, where probably NgForOf should only run change detection on them

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-d67ori

### Anything else?

Not sure if this is a regression

**Comment by Airblader** [comment] 2021-12-03 05:38
Have you tried using `trackBy`?

**Comment by makkgregory** [comment] 2021-12-03 16:20
@Airblader The issue itself is not in identity check. In the reproduction example array of primitive types is used as collection input for NgForOf. Default track function works fine in this case. 
Each time an item in that array is updated (note that length of the array stays the same), related view gets destroyed and created again for some reason. What I expect, is `embeddedView.detectChanges()` instead of `viewContainer.remove()` and subsequent `viewContainer.createEmbeddedView()`.

**Comment by JoostK** [comment] 2021-12-03 23:53
That _is_ precisely because there is no `trackBy` function provided, which results in items being matched to the prior items by means of their identity. For primitive values, this means that changing a value appears as a deletion and insertion, _not_ an update (different primitive values won't ever have the same identity, hence are never matched when no `trackBy` function is provided).

The desired effect can be achieved using a trackBy function that matches e.g. on the item's index instead of the item's identity.

Since this is working as designed I will go ahead and close this, but please do follow up if need be.

**Closed by JoostK** 2021-12-03 23:53 UTC
