### ISSUE TITLE
[HttpUrlEncodingCodec] Inconsistent URL encoding for params

### ISSUE THREAD

**Issue by ctomczyk** [angular/angular#27009] opened 2018-11-08 17:54 UTC
## I'm submitting a...

[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

## Current behavior
Following string <code>/EXAMPLE_String[@SOMETHING = "1"]</code> is encoded using Chrome Version 70.0.3538.77 (Official Build) (64-bit) / mac OS High Sierra 10.13.6 (17G3025):

Angular 7.02 using:
<pre><code>HttpUrlEncodingCodec.encodeValue('/EXAMPLE_String[@SOMETHING = "1"]')</code></pre>
**Result**: <code>/EXAMPLE_String%5B@SOMETHING%20=%20%221%22%5D</code>

<pre><code>window.encodeURIComponent('/EXAMPLE_String[@SOMETHING = "1"]')</code></pre>

**Result**: <code>%2FEXAMPLE_String%5B%40SOMETHING%20%3D%20%221%22%5D</code>

<pre><code>var sp = new window.URLSearchParams('/EXAMPLE_String[@SOMETHING = "1"]');
console.log(sp.toString());</code></pre>

**Result**: <code>%2FEXAMPLE_String%5B%40SOMETHING+=+%221%22%5D</code>

## Expected behavior

The URL parameter should match to the result from <code>window.URLSearchParams</code>.

## Environment

**Angular Version:**
<pre><code>
Angular CLI: 7.0.4
Node: 11.1.0
OS: darwin x64
Angular: 7.0.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-webworker, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.10.4
@angular-devkit/build-angular     0.10.4
@angular-devkit/build-optimizer   0.10.4
@angular-devkit/build-webpack     0.10.4
@angular-devkit/core              7.0.4
@angular-devkit/schematics        7.0.4
@angular/cli                      7.0.4
@ngtools/webpack                  7.0.4
@schematics/angular               7.0.4
@schematics/update                0.10.4
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.19.1
</code></pre>

## Additional information's

This is the function used behind scene:

<pre><code>function standardEncoding(v) {
    return encodeURIComponent(v)
        .replace(/%40/gi, '@')
        .replace(/%3A/gi, ':')
        .replace(/%24/gi, '$')
        .replace(/%2C/gi, ',')
        .replace(/%3B/gi, ';')
        .replace(/%2B/gi, '+')
        .replace(/%3D/gi, '=')
        .replace(/%3F/gi, '?')
        .replace(/%2F/gi, '/');
}</code</pre>

**Comment by trotyl** [comment] 2018-11-09 03:11
Duplicate of https://github.com/angular/angular/issues/18261

**Comment by ChrisDahmCS** [comment] 2018-11-21 12:40
Duplicate of [#26979](https://github.com/angular/angular/issues/26979)
And [#26979](https://github.com/angular/angular/issues/26979) is likely a duplicate of [#18261](https://github.com/angular/angular/issues/18261).

**Comment by alxhub** [comment] 2018-11-27 23:33
Closing as a duplicate.

**Closed by alxhub** 2018-11-27 23:33 UTC
Labels: comp: common/http
