### ISSUE TITLE
queryParamHandling 'merge' confusing behavior

### ISSUE THREAD

**Issue by pcurrivan** [angular/angular#27687] opened 2018-12-14 23:43 UTC
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
```

**Current behavior**

The router guide currently says this:
> The queryParamsHandling feature also provides a merge option, which will preserve and combine the current query parameters with any provided query parameters when navigating.

From that description I would expect the following to work:
```
this.router.navigate([], {
  queryParams: {'a': 'aaa'},
  queryParamsHandling: 'merge',
});
this.router.navigate([], {
  queryParams: {'b': 'bbb'},
  queryParamsHandling: 'merge',
});
```

I would expect to have query parameters `?a=aaa&b=bbb`, but instead I just get `?b=bbb` (only the last navigation sticks).

If the two navigations above were on two different button click handlers or something it would work, but since they are called "at the same time" it doesn't work.

The workaround is to always aggregate all query parameter changes into one navigation "at a time" (whatever that means).  I would request that either the documentation clearly state that this is required, or the above code be made to work.

* **Angular version:** 7.1.3

**Comment by jotatoledo** [comment] 2018-12-14 23:56
> If the two navigations above were on two different button click handlers or something it would work, but since they are called "at the same time" it doesn't work.


Then await for a navigation to complete before performing the next one:

```
async foo(){
var first = await this.router.navigate([], {
  queryParams: {'a': 'aaa'},
  queryParamsHandling: 'merge',
});
if(first){
await this.router.navigate([], {
  queryParams: {'b': 'bbb'},
  queryParamsHandling: 'merge',
});
}else{console.log("first nav failed");}
}
```

**Comment by jasonaden** [comment] 2018-12-18 22:04
This appears to me to need clarification on timing expectations in the docs. I've moved this over to the `docs` team.

**Comment by atscott** [comment] 2021-05-24 21:25
Closing as working as intended

**Closed by atscott** 2021-05-24 21:25 UTC
Labels: comp: docs, comp: router, feature, subtype: docs-clarification
