### ISSUE TITLE
Reflective Injector does not get parameters for derived es6 classes

### ISSUE THREAD

**Issue by stringham** [angular/angular#22297] opened 2018-02-19 00:38 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

If your typescript compile target is `es6` or `es2017`, Angular's Reflective Injector does not get parameters of derived classes.

```typescript
@Injectable()
class Engine {}

@Injectable()
class Car {
  constructor(public engine: Engine) {}
}

@Injectable()
class SportsCar extends Car {
}

const injector = ReflectiveInjector.resolveAndCreate([Engine, Car, SportsCar]);

console.log(injector.get(SportsCar).engine); // undefined
console.log(injector.get(Car).engine); // Engine
```

## Expected behavior

When the injector creates a `SportsCar` it should know that one of the class parameters is `Engine`.

## Minimal reproduction of the problem with instructions

I have an example in this plunker: https://plnkr.co/edit/3kDutFcvB62o73lA7tQi?p=preview

If you change the TypeScript target to be `es5` it works, or if you use an early angular version (`2.2.x`), but with the current version of Angular with TypeScript compiling to `es6` or `es2017` the injector fails to get the correct parameters.

## Environment

<pre><code>
Angular version: 5.2.5 (also happening in 6.0.0-beta.4)
</code></pre>

**Comment by trotyl** [comment] 2018-02-19 04:47
Duplicate of #21731

**Comment by vicb** [comment] 2018-02-19 21:46
closing as dulpicate

**Closed by vicb** 2018-02-19 21:46 UTC
Labels: comp: core & compiler, freq2: medium, severity3: broken, type: bug/fix
