### ISSUE TITLE
mat-form formControl error

### ISSUE THREAD

**Issue by TUTUBIG** [angular/angular#39973] opened 2020-12-04 16:21 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....
angular material

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...
`<mat-form-field>
  <mat-label>test</mat-label>
  <label>
    <input matInput minlength="3" [formControl]="confirm">
  </label>
  <mat-error *ngIf="true">Password doesn't match</mat-error>
</mat-form-field>`

and the 'mat-error' just works when the input length is less than minlength.
for example. it would show the error message 'Password doesn't match' when I input 'x' or 'xx' but this error message would gone when I input the third characters like 'xxx' or 'xxxx'

AND  just `confirm: new FormControl('', Validators.required)` or `confirm: new FormControl('')` error comes. if I change the formControl instance to `confirm: new FormControl('', Validators.email)` or `confirm: new FormControl('', Validators.pattern('xxx'))` it works well. Please have a test for this case and fix this bug.  

Waste too much time on this ):
 
## 🔬 Minimal Reproduction

 https://stackblitz.com/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 11.0.2
Node: 15.0.1
OS: darwin x64

Angular: 
... 
Ivy Workspace: 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1100.2 (cli-only)
@angular-devkit/core         11.0.2 (cli-only)
@angular-devkit/schematics   11.0.2 (cli-only)
@schematics/angular          11.0.2 (cli-only)
@schematics/update           0.1100.2 (cli-only)
</code></pre>

**Anything else relevant?**

**Comment by AndrewKushnir** [comment] 2020-12-04 23:17
Hi @TUTUBIG,

I tried to reproduce the problem that you described, but was unable to do that. I've created a quick Stackblitz demo to illustrate that:

https://stackblitz.com/fork/angular-ivy?file=src%2Fapp%2Fapp.component.html

If the problem still exists, could you please create a Stackblitz demo that we can use to investigate the issue?

I'm closing this ticket for now, feel free to reopen or create a new one once a repro is available.

Thank you.

**Closed by AndrewKushnir** 2020-12-04 23:17 UTC
Labels: comp: forms

**Comment by TUTUBIG** [comment] 2020-12-05 04:04
Thanks @AndrewKushnir  I've made a example code in https://stackblitz.com/fork/angular-ivy?file=src%2Fapp%2Fapp.component.html and I've updated the `package.json`. However I don't known how to install @angular/material here. Maybe you could use my example code to test

**Comment by AndrewKushnir** [comment] 2020-12-05 06:47
@TUTUBIG thanks for additional information. I've looked at the repro and I'm still confused on what the expected vs actual behavior is. I've updated a demo to take `confirm.invalid` status into account, [see Stackblitz demo here](https://stackblitz.com/edit/angular-ivy-ivxhvg?file=src%2Fapp%2Fissue-39973%2Fissue-39973.component.html). You should see the error message if you type something and after that remove all the content. If the problem still exists, please provide additional information on what the expected vs actual behavior is + step-by-step scenario that we can use to repro the issue. For now I'm keeping this ticket closed since we can not reproduce the problem. Thank you.

**Comment by TUTUBIG** [comment] 2020-12-13 13:11
I think `*ngIf` can't work in `mat-error`. `<mat-error *ngIf="email.value==='t@a.c'">Error</mat-error>` no matter this condition is true or false, seems `mat-error` shown or hidden just depends on whether the mat-form-field is  valid or invalid.
Please have a check with this demo https://stackblitz.com/edit/angular-iautuc?file=src/app/form-field-error-example.html
