### ISSUE TITLE
Update plunker templates to a41

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#4738] opened 2015-10-14 16:06 UTC
Especially the `bindings` -> `providers`. There might be something else.

**Comment by IgorMinar** [comment] 2015-10-14 16:07
@robwormald @jeffbcross can you please take care of this since you own the gists? Does anyone else need to be involved?

**Comment by jeffbcross** [comment] 2015-10-14 16:26
@IgorMinar sure, I'll update my plunk that some folks have forked to create their samples, though I'm trying to understand the purpose. Are we updating the templates so that API docs created in the future can be based off the updated template? If so, I thought we were close to having our API docs process use embedded code samples instead of plunker. Is that not the case?

**Comment by jeffbcross** [comment] 2015-10-14 16:29
BTW I'll update to 42 since that's the version we should be encouraging folks to use from npm. The only new feature in that release is the addition of minlength and maxlength validators https://github.com/angular/angular/commit/e82a35d1fd481ea3f1c72db60e6bc490398f12c8

**Comment by robwormald** [comment] 2015-10-14 16:29
TS plunker template updated to 42 : http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5

@jeffbcross I think this was mostly for quick bug reproductions and generalized freeform plunkery than anything specific to our docs.

@rkirov owns the ES6 and ES5 versions I believe.

**Comment by jeffbcross** [comment] 2015-10-14 16:40
My base plunk here has also been updated: http://plnkr.co/edit/f5oyIked9M2cKzvZNKHV?p=preview

**Comment by jeffbcross** [comment] 2015-10-14 16:41
@robwormald cool, so mostly for core contributors' benefit? Or are these published somewhere for community members to use as a starting point?

**Comment by robwormald** [comment] 2015-10-14 16:43
mine and @rkirov's templates are the ones you see at the bottom of the list here:
<img width="528" alt="screen shot 2015-10-14 at 9 42 33 am" src="https://cloud.githubusercontent.com/assets/534930/10490823/0064562a-7258-11e5-9f7c-98188ad59867.png">

**Comment by rkirov** [comment] 2015-10-14 16:51
upgraded to 42.

**Comment by rkirov** [comment] 2015-10-14 16:53
@robwormald how about using @Input and @Output decorators instead of the @Component{intput, output) in your template?

**Comment by robwormald** [comment] 2015-10-14 16:57
Done. Can you just cross check and make sure I'm doing that right?

**Comment by IgorMinar** [comment] 2015-10-14 23:57
the ts plunker still includes traceur-runtime, can we remove that please?

I also see that all plunkers use minified bundles. is that intentional?
maybe for perf reasons? I just think that it makes debugging harder, but I
can just switch to non-minified version if needed.

lastly, the ts plunker pulls system from code.angular.js and the es6 pulls
it from jspm.io. can we unify this? unless jspm.io is unreliable we should
use that everywhere.

**Comment by woppa684** [comment] 2015-10-15 12:19
Currently none of them are working (at least on my PC), the console shows:

```
GET https://code.angularjs.org/tools/typescript.js 403 (VirusFound)
```

**Comment by IgorMinar** [comment] 2015-10-15 18:00
that looks like a local proxy issue

**Comment by woppa684** [comment] 2015-10-15 18:06
It sure does, but since I only have issues with that single file I thought I'd mention it anyway

**Comment by robwormald** [comment] 2015-10-16 06:36
updated to 44

**Comment by mhevery** [comment] 2015-10-16 16:56
Looks like this is resolved and can be closed. Closing, reopen if there is more.

**Closed by mhevery** 2015-10-16 16:56 UTC
Labels: P1: urgent, type: chore
