### ISSUE TITLE
Link To Command Reference page not found

### ISSUE THREAD

**Issue by consman** [angular/angular#52879] opened 2023-11-13 22:53 UTC
### Describe the problem that you experienced

I was reviewing https://angular.dev/tools/cli then I clicked on the Command Reference link. I was pathed to https://angular.dev/cli/commands which gave me a "Page Not Found 🙃" error.

### Enter the URL of the topic with the problem

https://angular.dev/cli/commands

### Describe what you were looking for in the documentation

build options

### Describe the actions that led you to experience the problem

I was reviewing https://angular.dev/tools/cli then I clicked on the Command Reference link. I was pathed to https://angular.dev/cli/commands which gave me a "Page Not Found 🙃" error.

### Describe what you want to experience that would fix the problem

I expect to see something similar to https://angular.io/cli 

### Add a screenshot if that helps illustrate the problem

![Screenshot 2023-11-13 at 2 52 01 PM](https://github.com/angular/angular/assets/1146436/b0365bcb-14b0-40a5-9cf2-761cd9b8e677)

**Comment by JoostK** [comment] 2023-11-13 23:19
Thanks for the report, this is a duplicate of #52549, pending a new deployment.

**Closed by JoostK** 2023-11-13 23:19 UTC
