### ISSUE TITLE
First async validation status is not emit

### ISSUE THREAD

**Issue by eelwayadmin** [angular/angular#7275] opened 2016-02-25 10:05 UTC
Hi there,

I was wondering why first async validation status is not emited.
In fact, I have an error message component which is listening to statusChanged update on my input.
I run asyncValidation on this input, so the first time I check for errors and status on this input status is OK.
But as far as the async new status is not dispatched threw statusChanged, I can't update my error message status.

Is there a reason for not dispatching the first async status ?

Is there some workaround ?

**Comment by zoechi** [comment] 2016-02-25 10:12
Please provide a Plunker that shows what you are trying to accomplish and where it fails.

**Comment by pkozlowski-opensource** [comment] 2016-06-03 17:31
Closing as the issue is not clear and we've got no reproduce scenario

**Closed by pkozlowski-opensource** 2016-06-03 17:31 UTC
