### ISSUE TITLE
Page not found

### ISSUE THREAD

**Issue by Nagasai-Tenekondala** [angular/angular#53891] opened 2024-01-12 02:04 UTC
### Describe the problem that you experienced

Page not found in angular cli commands reference route ot angular.dev

### Enter the URL of the topic with the problem

https://angular.dev/cli/commands

### Describe what you were looking for in the documentation

Cli commands page doesn't have any commands, it just says "Page not found" 

### Describe the actions that led you to experience the problem

I navigated to docs and then developer tools > Angular cli > Clicked on the "Command reference"   

### Add a screenshot if that helps illustrate the problem

<img width="767" alt="image" src="https://github.com/angular/angular/assets/67927529/8bac74df-e0ce-416a-9f8b-972cf5535ef4">

**Comment by nikvarma** [comment] 2024-01-12 07:17
correct path.

https://angular.dev/cli

**Comment by JoostK** [comment] 2024-01-12 09:04
Thanks for the report, closing as duplicate of https://github.com/angular/angular/issues/52549 for which the fix is pending deployment.

**Closed by JoostK** 2024-01-12 09:04 UTC
Labels: area: adev
