### ISSUE TITLE
ReactiveForms Value Not Updating Correctly When Input Type Bound To 'checkbox'

### ISSUE THREAD

**Issue by XaimXyooj** [angular/angular#41009] opened 2021-02-26 06:49 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/forms

### Is this a regression?

 No/unverified.

### Description

 Checkboxes are broken when you bind the `type` attribute on an `input` tag to a `checkbox` string on the component. The captured value is always a string `"false"` whether checked, or unchecked.

## 🔬 Minimal Reproduction

 [https://stackblitz.com/edit/angular-ivy-cwpbec](https://stackblitz.com/edit/angular-ivy-cwpbec)
Form values are logged to dev console.

## 🔥 Exception or Error
<pre><code>
N/A

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
(see stackblitz)

</code></pre>

**Anything else relevant?**
Firefox (86.0). Unverified with other versions/browsers.

**Comment by XaimXyooj** [comment] 2021-02-26 06:51
Not sure why [links](https://github.com/angular/angular/issues/41009) aren't rendering.

**Comment by AndrewKushnir** [comment] 2021-02-26 07:03
Hi @XaimXyooj, this issue looks like a duplicate of #13243, so I'm closing this ticket in favor of #13243. Please subscribe to that thread to receive further updates. Thank you.

**Closed by AndrewKushnir** 2021-02-26 07:03 UTC
