### ISSUE TITLE
 Compilation error in Ivy mode with 8.0.0-rc.5

### ISSUE THREAD

**Issue by sergey-morenets** [angular/angular#30680] opened 2019-05-27 05:40 UTC
# 🐞 bug report

### Is this a regression?

No

### Description

I have a working Angular v7 application with the following dependency:
"angular-star-rating": "^3.0.8"

If I upgrade my application to the 8.0.0-rc.5 version it builds fine. But if enable Ivy mode in tsconfig.json 
```

  "angularCompilerOptions": {
    "enableIvy": true
  },

```
I start getting this error message during build.

## 🔬 Minimal Reproduction

ng build --prod

## 🔥 Exception or Error
<pre><code>
ERROR in ENOENT: no such file or directory, open 'node_modules/angular-star-rating/angular-star-rating.js'
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.0.0-rc.4
Node: 11.3.0
OS: win32 x64
Angular: 8.0.0-rc.5
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.0-rc.4
@angular-devkit/build-angular     0.800.0-rc.4
@angular-devkit/build-optimizer   0.800.0-rc.4
@angular-devkit/build-webpack     0.800.0-rc.4
@angular-devkit/core              8.0.0-rc.4
@angular-devkit/schematics        8.0.0-rc.4
@angular/cdk                      8.0.0-rc.2
@angular/cli                      8.0.0-rc.4
@angular/http                     8.0.0-beta.10+1.sha-a28b3e3
@angular/material                 8.0.0-rc.2
@ngtools/webpack                  8.0.0-rc.4
@schematics/angular               8.0.0-rc.4
@schematics/update                0.800.0-rc.4
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.30.0
</code></pre>

**Comment by JoostK** [comment] 2019-05-27 20:50
Unfortunately, I can't reproduce without a repo. Locally installing `angular-star-rating` and running ngcc completes successfully. Could you provide a Github repo we may clone?

**Comment by sergey-morenets** [comment] 2019-05-29 05:27
Hi @JoostK 

First of all, I didn't run ngcc, I ran ng build --prod command as I mentioned in the description.
But I noticed that you released 8.0 yesterday so I tried to upgdate my project again:

ng update --force=true  --packageManager=yarn @angular/cli @angular/core

Unfortunately if I run ng build --prod or node_modules/.bin/ivy-ngcc I still get this exception.

**Comment by sergey-morenets** [comment] 2019-05-29 05:27
I will try to create sample repo to reproduce the error but it may take some time

**Comment by sergey-morenets** [comment] 2019-05-29 05:56
Hi @JoostK 

I created sample repo from clean new Angular 8 project, can you please look at it: https://github.com/sergey-morenets/angular8

If I set "enableIvy": false in tsconfig.json then ng build --prod command worked successfully. And if change it to "enableIvy": true then I get error message, but a different one:

ERROR in node_modules/angular-star-rating/src/angular-star-rating.module.d.ts(2,22): error TS-996002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class

**Comment by JoostK** [comment] 2019-05-29 06:33
I understand that you didn't run ngcc, so that's why the reproduction was required for me to be able to run `ng build --prod`. The error you experience now does seem to indicate that ngcc did not process `angular-star-rating`. Could you check for me if you have `@angular/forms` installed? It is a peer dependency of `angular-star-rating` and if it's not installed, `angular-star-rating` is not processed.

**Comment by sergey-morenets** [comment] 2019-05-29 06:50
@JoostK 
Yes, it's installed. But actually you can clone my repo and reproduce the issue.

**Comment by JoostK** [comment] 2019-05-29 07:13
Thanks 👍 Will have a look later.

**Comment by JoostK** [comment] 2019-05-29 19:47
It looks like the `angular-star-rating` package is not properly processed by ngcc, as it uses an old tsickle syntax for the decorator metadata. See

Look for `StarRatingModule.decorators` in its [ES5 bundle](https://unpkg.com/angular-star-rating@4.0.0-beta.3/esm5/angular-star-rating.js), you'll find it at the root of the module. With more recent versions of tsickle, that statement is instead emitted within the IIFE. At this moment, ngcc only searches for decorator metadata within the IIFE, not at the root. Hence, no Ivy code is generated for the package, resulting in the error.

**Comment by sergey-morenets** [comment] 2019-05-30 05:05
@JoostK 

Ok, so you will fix this issue in the next Angular build?

**Comment by IlCallo** [comment] 2019-05-30 06:38
Seems more like an update the library maintainer have to fix, than Angular team

**Comment by JoostK** [comment] 2019-05-30 09:34
@sergey-morenets We should be able to support this structure. I don't think it will be in the next build though.

**Comment by sergey-morenets** [comment] 2019-05-30 15:55
@IlCallo This library is not actively maintained (like many others) so I guess the best option here is not to force library creators to migrate to new format but to ask for Anguar team support of these libraries.
Does this make sense for you?

**Comment by JoostK** [comment] 2019-05-31 22:53
I opened PR #30795 that should get this supported. Unfortunately, we hit a restriction in TypeScript that currently requires an awful hack to workaround, so this might not get in shortly.

**Comment by JoostK** [comment] 2019-06-19 22:15
I just retested this with `8.1.0-next.3` and the issue has indeed been resolved with #30795. I forgot to link this issue from that PR so it wasn't auto-closed, I'll do that now.

**Closed by JoostK** 2019-06-19 22:15 UTC
Labels: comp: ivy, freq2: medium, severity3: broken, type: bug/fix
