### ISSUE TITLE
Error in TypeScript documentation

### ISSUE THREAD

**Issue by fabienbellanger** [angular/angular#6462] opened 2016-01-13 16:24 UTC
Hi,

i think there is an error on TypeScript documentation > Developer Guides > 6. Dependency Injection.
import {Injectable} from 'angular2/angular2'; should be import {Injectable} from 'angular2/core';

Thanks for your work!

**Comment by BeastCode** [comment] 2016-01-22 07:12
Fixed, created a PR in angular.io: https://github.com/angular/angular.io/pull/738

**Comment by pkozlowski-opensource** [comment] 2016-01-22 13:18
Closing as duplicate of https://github.com/angular/angular.io/pull/738

**Closed by pkozlowski-opensource** 2016-01-22 13:18 UTC
Labels: comp: docs, effort1: easy (hour), hotlist: community-help, P2: required, type: bug
