### ISSUE TITLE
Pages flashing with broken layout without ssr in angular 19

### ISSUE THREAD

**Issue by bschick** [angular/angular#59199] opened 2024-12-15 07:28 UTC
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

After upgrading an app from angular 18 to 19 I noticed that when navigating to a new page, they often flash partially rendered. It doesn't look totally unstyled, but the layout is broken for a split second and then the page correctly renders. 

To see if it was something specific about my app, I created a new project and it exhibits the same problem.

```
$ ng new a19t -g -S --style scss --ssr false
$ cd a19t
$ ng serve
```

Then open a browser to the app and reload the page several times. Each time the page reloads you'll see the angular image flash briefly at the full width of the browser window, and then correctly layout. 

If I change the command above to  `ng new a19t -g -S --style scss --ssr true`, the problem goes away.

### Please provide the exception or error you saw

```true

```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 19.0.5
Node: 22.11.0
Package Manager: npm 10.9.2
OS: linux arm64

Angular: 19.0.4
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1900.5
@angular-devkit/build-angular   19.0.5
@angular-devkit/core            19.0.5
@angular-devkit/schematics      19.0.5
@angular/cli                    19.0.5
@angular/ssr                    19.0.5
@schematics/angular             19.0.5
rxjs                            7.8.1
typescript                      5.6.3
zone.js                         0.15.0
```

### Anything else?

I don't want to include ssr in my app

**Comment by jnizet** [comment] 2024-12-15 07:37
That's probably dur to HMR. Try running it with --hmr=false.

**Comment by bschick** [comment] 2024-12-15 08:41
> That's probably dur to HMR. Try running it with `--hmr=false`.

Yes, that did work around the problem. Seems odd given that in my own app the broken layout flash occurs during navigation between page (no source code editing or page reloads happening).

I'd still call this a bug. Didn't happen prior to v19, its distracting, and could mask actual rendering problems.

**Comment by spock123** [comment] 2024-12-15 21:49
For anyone seeing this or getting this issue in the future, it was _very_ tricky to find the issue.

The cause was the introduction of a` .browserslistrc` file containing:

```
last 2 Chrome major versions
last 2 iOS major versions
last 2 Safari major versions
last 2 Firefox major versions
last 2 Edge major versions
>0.2%
not dead
not op_mini all
```

Removing the file solves the issue.
What a crazy issue and _zero_ data to go by. Phew!

**Comment by bschick** [comment] 2024-12-15 23:05
> For anyone seeing this or getting this issue in the future, it was _very_ tricky to find the cause.
> 
> The cause was the introduction of a` .browserslistrc` file containing:

I have not .browserslistrc file that I've found. That node_module is installed as a dependency of various angular tools, but I have not configured.

**Comment by shannonvc** [comment] 2024-12-16 04:18
Likely a duplicate of #59058

HMR for styles is now enabled by default for `ng serve` in v19.
When enabled, the styles are loaded separately from the component, hence the flickering.
As stated above and in the other issue, running with `ng serve --no-hmr` will behave as it did before.

**Comment by spock123** [comment] 2024-12-16 08:32
Guys I am sorry, my comment was for another issue, I am really sorry. Have deleted it again.

**Comment by spock123** [comment] 2024-12-16 09:31
> > For anyone seeing this or getting this issue in the future, it was _very_ tricky to find the cause.
> > The cause was the introduction of a` .browserslistrc` file containing:
> 
> I have no `.browserslistrc` file that I've found. That npm package is installed as a dependency of various angular tools, but I have not configured it. Unless you have more info, I don't agree this issue should be closed.

I'm sorry my comment had by mistake been made on this issue. Apologies.

**Comment by JeanMeche** [comment] 2024-12-16 10:08
Closing as a dupe of #59058

**Closed by JeanMeche** 2024-12-16 10:08 UTC
