### ISSUE TITLE
Ngstyle does not determine whether the value has a unit

### ISSUE THREAD

**Issue by wszgrcy** [angular/angular#56427] opened 2024-06-13 10:52 UTC
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

No

### Description

https://github.com/angular/angular/blob/a114ebad7e8f2a3074ef13d0f010920f9da2bcf2/packages/common/src/directives/ng_style.ts#L95
 `<div [ngStyle]="{'font-size.px':'99px'}">test</div>` font-size not work

### Please provide a link to a minimal reproduction of the bug

 `<div [ngStyle]="{'font-size.px':'99px'}">test</div>`

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 18.0.2
Node: 20.10.0
Package Manager: npm 10.2.3
OS: linux x64

Angular: 18.0.1
... animations, cdk, common, compiler, compiler-cli, core, forms
... material, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1800.2
@angular-devkit/build-angular   18.0.2
@angular-devkit/core            18.0.2
@angular-devkit/schematics      18.0.2
@angular/cli                    18.0.2
@schematics/angular             18.0.2
rxjs                            7.8.1
typescript                      5.4.5
zone.js                         0.14.6
```

### Anything else?

use this function replace `setStyle` value 

```ts
private formatValue(value:number|string,unit:string){
if (unit) {
  if (typeof value==='number') {
    return value
  }else if(value.endsWith(unit)){
    return value
  }else{
    return `${value}${unit}`
  }
}
return value
}
```

**Comment by JoostK** [comment] 2024-06-13 10:57
This is not a bug. If you specify a unit in the binding name, then the value shouldn't repeat it.

**Comment by json-derulo** [comment] 2024-06-13 11:58
This is just an implementation mistake, which Angular should not try to fix for you. In theory Angular could warn about this in dev mode, not sure if that's really necessary here.

**Comment by JoostK** [comment] 2024-06-13 13:27
I am going to close this as working as intended.

Using the unit from the value as suggested runs into edge-cases with e.g. `{ 'width.em': '1rem' }`, so more advanced detection would be required. It is left up to developers to provide just the numeric value if a unit is specified in the style property.

**Closed by JoostK** 2024-06-13 13:27 UTC
