### ISSUE TITLE
Bazel failing to produce a build

### ISSUE THREAD

**Issue by kuncevic** [angular/angular#32825] opened 2019-09-23 22:50 UTC
# 🐞 Bug report

### Command 
```
- [ x] build
```

### Is this a regression?

Haven't try previous version

### Description
Just created a new app with @angular/cli@9.0.0-next.5 and @angular/core@9.0.0-next.7 and @angular/bazel

## 🔬 Minimal Reproduction
npm install -g @angular/cli@next
npm install -g @angular/bazel@next
ng new dev --collection=@angular/bazel
ng build

## 🔥 Exception or Error
<pre><code>
Could not find peer dependency 'node-sass' of 'sass-loader'
ERROR: no such package '@npm//': Traceback (most recent call last):
    File "/private/var/tmp/_bazel_A/8ce83dd6eebdabe8e043969f610b9831/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 379
        _create_build_files(repository_ctx, "yarn_install", node, ...)
    File "/private/var/tmp/_bazel_A/8ce83dd6eebdabe8e043969f610b9831/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 146, in _create_build_files
        fail(("generate_build_file.js failed:...)))
generate_build_file.js failed: 
STDOUT:

</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 9.0.0-next.5
Node: 12.10.0
OS: darwin x64
Angular: 9.0.0-next.7
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-next.5
@angular-devkit/build-angular     0.900.0-next.5
@angular-devkit/build-optimizer   0.900.0-next.5
@angular-devkit/build-webpack     0.900.0-next.5
@angular-devkit/core              9.0.0-next.5
@angular-devkit/schematics        9.0.0-next.5
@angular/cli                      9.0.0-next.5
@ngtools/webpack                  9.0.0-next.5
@schematics/angular               9.0.0-next.5
@schematics/update                0.900.0-next.5
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.40.2

</code></pre>

**Comment by Toxicable** [comment] 2019-09-24 07:04
Not obvious duplicate of https://github.com/bazelbuild/rules_nodejs/issues/1162

The issue is that currently bazel requries all deep deps to be satisfied, the work around is to add all the peer deps.
We'll be removing this check in the next version

**Comment by alxhub** [comment] 2019-10-15 22:46
Closing as a duplicate!

**Closed by alxhub** 2019-10-15 22:46 UTC
Labels: comp: bazel
