### ISSUE TITLE
Change the parent of a component?

### ISSUE THREAD

**Issue by mindarelus** [angular/angular#19827] opened 2017-10-20 12:17 UTC
Hi there,
Is it possible to change the parent component of a component?

Something like:

<comp-a><comp-c></comp-c></comp-a>
<comp-b></comp-b>

I'm trying to implement drag and drop functionality, and I want to be able to drag <comp-c> from parent A to parent B.

**Comment by mindarelus** [comment] 2017-10-20 12:21
Another thing that bothers me, is if I create dynamically components, like some alert boxes, modals, and so on on ngAfterViewInit like this:

ngAfterViewInit() {
    for (let i = 0; i < 3; i++) {
      const alertBoxFactory = this.factory.resolveComponentFactory(AlertBoxComponent);
      const componentRef = this.containerAlertBox.createComponent(alertBoxFactory);
      setTimeout((z) => { z.instance.title = '' + i; }, 1500 + i * 500, componentRef);
      componentRef.instance.theInstance = componentRef;
      componentRef.instance.buttonEmmiter.subscribe((x: any) => {
        console.log(x);
      });
    }
...

I got some change detection error, and the only way to get rid of it, is to detach the AlertBox from change detection and implement it on my own.

**Comment by ericmartinezr** [comment] 2017-10-20 12:28
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by mindarelus** [comment] 2017-10-20 16:31
Yes, I wasn't sure where to place this issue.. But still, isn't it strange that components are so fixed regardless to their child components, and it's not that easy to move things around. I guess I just want to push outside the limits of the framework.

**Comment by mindarelus** [comment] 2017-10-20 16:40
With javascript it very easy to move 1 div with all its siblings to another place in the HTML. And if the philosophy of Angular is to look at the components just like extension of html, like tags with more functionality, it would be a minus, if such easy thing from HTML cannot be performed with components.

**Comment by mlc-mlapis** [comment] 2017-10-20 16:53
@mindarelus ... probably still nobody understands what you want to do ... your explanation is just not enough clear.

**Comment by jasonaden** [comment] 2017-11-11 00:05
Since this is really a support request, I'll close the issue. But you should ask on StackOverflow with the link above.

You can also create a reproduction of your issue using [StackBlitz](https://stackblitz.com/fork/angular-gitter). That will help people to understand the problem you're having.

**Closed by jasonaden** 2017-11-11 00:05 UTC
