### ISSUE TITLE
ngOnDestroy never called when service is provided with an InjectionToken + useClass

### ISSUE THREAD

**Issue by simeyla** [angular/angular#32384] opened 2019-08-29 03:38 UTC
# 🐞 bug report

### Description

When an injection token (and useClass) is used to provide a service, the `ngOnDestroy` method should be called when the component is disposed.

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-issue-repro-3qxrz4

## 🔥 Exception or Error

`ngOnDestroy` is  not called when an injection token is used for the provider - even though `useClass` (which is known at compile time) is used to actually instantiate the class.

While I understand that [factory providers have a similar issue and is harder to fix](https://github.com/angular/angular/issues/14818) I don't understand why the following prevents `ngOnDestroy` being called.

    {
      provide: PAGE1SERVICE,
      useClass: Page1Service       // useClass
    }

This is very unexpected behavior and can lead to very subtle bugs. If this is never going to be fixed the [docs](https://angular.io/api/core/OnDestroy) should be updated to reflect the limitations of ngOnDestroy with respect to services + injection tokens..

## Possible workarounds

1)

    Page1Service,
    {
      provide: PAGE1SERVICE,
      useExisting: Page1Service       // useExisting
    }

2) Provide a custom management service by the component and implement some kind of custom lifecycle event.

## 🌍  Your Environment

**Angular Version:**
8.2.3

Repro is 6.1.9 (that's the forked sample)

**Comment by trotyl** [comment] 2019-08-29 04:20
Duplicate of https://github.com/angular/angular/issues/14821, https://github.com/angular/angular/issues/28738, https://github.com/angular/angular/issues/28857

**Closed** 2019-09-03 22:59 UTC
Labels: comp: core, type: bug/fix
