### ISSUE TITLE
Feature request and/or documentation change for the mechanism of property binding of HTML elements

### ISSUE THREAD

**Issue by user414** [angular/angular#6383] opened 2016-01-10 14:41 UTC
Here is the plunk showing the problem

http://plnkr.co/edit/UTH6sUqb0OhZsBa6r3h4?p=preview

basically when using something like

```
<div class="form-group">
	    <label for="{{forLabel}}">{{label}}</label>
	    <input type="text" class="form-control">
 </div>
```

you get

```
Can't bind to 'for' since it isn't a known native property ("
</nav>
    <div class="form-group">
	    <label [ERROR ->]for="{{forLabel}}">{{label}}</label>
	    <input type="text" class="form-control">
    </div>
"): RoutedComponent@28:12
```

**Comment by zoechi** [comment] 2016-01-10 15:15
See http://stackoverflow.com/questions/34704671/error-while-adding-for-attribute-to-label-in-angular-2-0-template for how to do this right.
Please close the issue if this solves your problem.

**Comment by user414** [comment] 2016-01-10 15:54
That's how I solved it but it seems inconsistent in the template syntax here

https://angular.io/docs/ts/latest/guide/template-syntax.html#!#interpolation

when I read this it seems to suggest that:

We often have a choice between Interpolation and Property Binding. The following binding pairs do the same thing

```
<img src="{{heroImageUrl}}">
<img [src]="'' + heroImageUrl">
```

which would indicate to me that

```
<label for="{{forLabel}}">{{label}}</label>
``` 

should be as valid as

```
<label [attr.for]="{{forLabel}}">{{label}}</label>
```

Or I'm misunderstanding this? Does the only reason why it works with src is that it is a native property? In that case in order to avoid confusion we should change that example to something which does not have a native property since the two are not always equal to each other. Or clarify to something else, not too sure what but something to avoid thinking that someone is trying to set the html attribute src of the img element and that translate to any other attribute of other elements.

**Comment by ericmartinezr** [comment] 2016-01-10 16:08
These are valid

```
<label attr.for="{{forLabel}}">{{label}}</label>
<label [attr.for]="forLabel">{{label}}</label>
```

**Comment by zoechi** [comment] 2016-01-10 16:20
@user414 https://developer.mozilla.org/de/docs/Web/API/HTMLLabelElement
`htmlFor` is the property, `for` is the attribute it reflects.

Therefore `<label htmlFor="{{forLabel}}">{{label}}</label>` also works.

**Comment by user414** [comment] 2016-01-11 13:28
After reading again and thinking about this, here are some suggestion that would help clarify things for me

* It is not intuitive to me that
```
<label for="{{forLabel}}"></label>
```
translates to
```
<label [for]="forLabel"></label>
```
instead I would think for HTML element it would translates to
```
<label [attr.for]="forLabel"></label>
```
Therefore I would suggest that in the code we continue the current behavior but as a fallback if no native DOM property exist instead of throwing an error we look for 
```
[attr.<name>] 
```
instead. After that, if still nothing is found we throw an error like
```
Can't bind to 'for' since it isn't a known native property nor an HTML Element attribute ("

        <label [ERROR ->]for="{{forLabel}}"></label>
"): RoutedComponent@28:12
```

* If we don't want to modify the behavior as described above I suggest we modify the documentation here https://angular.io/docs/ts/latest/guide/template-syntax.html#!#property-binding-or-interpolation- to a more generic example so as less confusion could arise from the fact that src in that example is both a DOM property and an HTML attribute 
```
<my-cmp property="{{expression}}"></my-cmp>
<my-cmp [property]="expression"></my-cmp>
```
then hopefully unlike me further user would read the whole page and figure out how it really works:-) In addition modifying the error to something like
```
Can't bind to 'for' since it isn't a known native property, try attr.for if you were trying to bind to the HTML attribute ("

        <label [ERROR ->]for="{{forLabel}}"></label>
"): RoutedComponent@28:12
```
or something like that.

**Comment by pkozlowski-opensource** [comment] 2016-08-06 09:42
I think that the we've got a better suggestion in https://github.com/angular/angular/issues/7516#issuecomment-196899635. This way no documentation updates will be necessary and intuitive `<label [for]="exp">` will "just work".

Closing as duplicate of #7516

**Closed by pkozlowski-opensource** 2016-08-06 09:42 UTC
