### ISSUE TITLE
Potential race condition in repetitive calls to ngZone.run()

### ISSUE THREAD

**Issue by chance-an** [angular/angular#13673] opened 2016-12-27 00:06 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
## Some background
In a Electron-based app. I created a [EventEmitter (NodeJS, not Angluar's)](https://nodejs.org/api/events.html) in the main thread. The component code of renderer thread gets the EventEmitter through [Electron's remote module](https://github.com/electron/electron/blob/master/docs/api/remote.md) and listens on it. Upon receives a message from the EventEmitter, the component will add the received message to its `files` field, which is used by a ngFor in the template

```typescript
// this.musicFileEntryPump = require('electron').remote.require('file-manager').LogicForCreatingTheEventEmitter()
....

this.musicFileEntryPump.on('file', (entry: IMusicFileEntry) => {
                   this._ngZone.run(() => {
                       this.files.push(entry);
                   });
}
```

```html
    <tr *ngFor="let musicFile of files">
      <td>{{musicFile.metadata.title}}</td>
      <td>{{musicFile.metadata.album}}</td>
      <td>{{musicFile.metadata.artist && musicFile.metadata.artist[0]}}</td>
      <td>{{musicFile.metadata.track?.no}}</td>
    </tr>
```

**The issue:**
Exception is thrown at a random point from ngZone.run(); 
```
[project_path]\node_modules\rxjs\Subscriber.js:227Uncaught Error: Error in ./FileListComponent class FileListComponent - inline template:12:10 caused by: Cannot read property 'object' of undefined
TypeError: Cannot read property 'object' of undefined
    at ObjectsRegistry.get ([project_path]\node_modules\electron-prebuilt\dist\resources\electron.asar\browser\objects-registry.js:44:28)
    at EventEmitter.<anonymous> ([project_path]\node_modules\electron-prebuilt\dist\resources\electron.asar\browser\rpc-server.js:324:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
    at EventEmitter.<anonymous> ([project_path]\node_modules\electron-prebuilt\dist\resources\electron.asar\browser\api\web-contents.js:165:13)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)SafeSubscriber.__tryOrUnsub @
 [project_path]\node_modules\rxjs\Subscriber.js:227SafeSubscriber.next @
 [project_path]\node_modules\rxjs\Subscriber.js:172Subscriber._next @
 [project_path]\node_modules\rxjs\Subscriber.js:125Subscriber.next @
 [project_path]\node_modules\rxjs\Subscriber.js:89Subject.next @
 [project_path]\node_modules\rxjs\Subject.js:55EventEmitter.emit @
 [project_path]\node_modules\@angular\core\bundles\core.umd.js:5713NgZone.checkStable @
 [project_path]\node_modules\@angular\core\bundles\core.umd.js:5943NgZone.onLeave @
 [project_path]\node_modules\@angular\core\bundles\core.umd.js:6010onInvoke @
 [project_path]\node_modules\@angular\core\bundles\core.umd.js:5978ZoneDelegate.invoke @
 zone.js:231Zone.run @
 zone.js:114NgZone.run @
 [project_path]\node_modules\@angular\core\bundles\core.umd.js:5865result.musicFileEntryPump.on @
 file_list.component.ts:73apply @
 [project_path]\node_modules\electron-prebuilt\dist\resources\electron.asar\common\api\call…:54(anonymous function) @
 [project_path]\node_modules\electron-prebuilt\dist\resources\electron.asar\renderer\api\re…:243emitThree @
 events.js:116emit @
 events.js:194
```

EventEmitter is fired in a different thread rapidly at any random time. Can Angular's mechanism guarantee that the change in ngZone.run() is consolidated before the next time it is called? If not, I hope Angular implements a feature to guarantee that or suggest a recommended practice.

## Workaround 1

I listen on the onStable event form ngZone, and only kick off another run() after the previous run has finished.

```typescript
               let defer = Q.defer();
               defer.resolve();

               let attached = false;
               this.musicFileEntryPump.on('file', (entry: IMusicFileEntry) => {
                   this.files.push(entry);

                   let next = () => {
                       defer = Q.defer();
                       this._ngZone.run(() => {});
                   };

                   if( defer.promise.isPending()){
                       if (!attached) {
                           attached = true;
                           defer.promise.then(next);
                       }
                   } else {
                       let subscription = this._ngZone.onStable.subscribe(()=> {
                           subscription.unsubscribe();
                           defer.resolve();
                           attached = false;
                       });
                       next();
                   }
               })
```

The downsides are: 
1. The code is tedious and cumbersome.

2. The document mentions that [Angular's EventEmitter](https://angular.io/docs/ts/latest/api/core/index/EventEmitter-class.html) is not guaranteed to be a Observable in the future. So there is [no guarantee](http://stackoverflow.com/questions/36076700/what-is-the-proper-use-of-an-eventemitter) on the usage of `subscribe()` there.

## Workaround 2
I can simply use a throttled way to call ngZone.run()
```typescript
let update= _.throttle(() => {
                this._ngZone.run(() => {});
}, 20);
this.musicFileEntryPump.on('file', (entry: IMusicFileEntry) => {
                   this.files.push(entry);
                   update();
}
```

The code is clean and this helps mitigate the problem. But it still doesn't always guarantee to work, unless I set the throttle threshold to pretty high, which will cause unnecessary UI delay.

**Expected behavior**

I hope:

1. Can Angular Team please give some insights on whether this is a Angular issue?
2. Can you please suggest the best practice on using ngZone for the scenario I talked above?

**Minimal reproduction of the problem with instructions**

Create a Electron app. Make an EventEmitter in the main thread. Randomly emit messages to it at a rapid rate. 

On the renderer thread, acquire this EventEmitter, listen on it and do ngZone() update like mentioned above.

**What is the motivation / use case for changing the behavior?**

The workaround is rather complicated. If it is truly a race condition, ngZone.run() should consider such case.

**Please tell us about your environment:**

Windows 10. No bundler is used. Rely on Electron's `require()` to find modules.

* **Angular version:** 2.2.3

* **Browser:** 
Electron Prebuild 1.2.5
 
* **Language:** TypeScript 2.1.4

* **Node (for AoT issues):** `node --version` =   4.4.7

**Comment by mhevery** [comment] 2017-01-03 19:39
> EventEmitter is fired in a different thread rapidly at any random time.

Not sure what do you mean. JavaScript is single threaded. How can the above be true?

I need a way to reproduce the issue. 

I don't see how `Zone.run()` could be the cause of the issue, since the exception happens in the Electrone code. Perhaps you should execute your electrone code outside of angular? `NgZone.runOutsideAngular()`?

**Comment by chance-an** [comment] 2017-01-06 08:14
JavaScript is single threaded, Electron is not necessarily so. It has the Main Process and Renderer Process, each runs a single thread of JavaScript respectively(Correct me if I am wrong).

Did you try my reproduction steps and it does not reproduce for you?

The reason why I have Zone.run() is to trigger an UI update. Or my `this.files.push(entry);` takes no effect. The heavy lifting electron code is already run by the main process/thread. It doesn't use Angular. 

This can definitely be an electron issue of course, but I'd like to collect some proof that this is absolutely not an Angular issue. As I see that if I wait on Ngzone to consolidate its job before I issue another NgZone.run(), the issue goes away.

**Comment by mhevery** [comment] 2017-01-06 17:58
> JavaScript is single threaded, Electron is not necessarily so.

Electron may have multiple threads, but each thread must have its own VM, or they must ensure that two threads don't run the same VM. JS VM is single threaded so its not possible to have electron turn V8 into a multithreaded code. So I am very confused by your statements.

I am sorry, but we have too many issue to look at. So unless I have a very simple way of reproduce an issue, we will end up working on something more pressing.

**Comment by chance-an** [comment] 2017-01-06 19:10
I can't really find a simpler reproduction steps for you. Depends on your capacity, It's up to you what you want to do with this issue. I won't mind closing this issue if it's not very actionable for you.

As long as there are multiple threads, there is chance that they contest on shared resource, regardless whether two threads run on separate VMs or not. Electron remote module relies on cross-process RPC to exchange data, so I am more inclined to believe they are in different VMs, or even processes. Then it doesn't require V8 to be multithreaded code, since they are essentially in different processes. Maybe Angular should consider environments of this kind, and be more defensive and protective in reading data. Just an opinion.

**Comment by mhevery** [comment] 2017-12-07 23:39
closing due to non-reproducibility

**Closed by mhevery** 2017-12-07 23:39 UTC
Labels: comp: zones
