### ISSUE TITLE
*ngFor elements throttle browser events in IE/Edge on Win 10

### ISSUE THREAD

**Issue by dgbonomo** [angular/angular#9155] opened 2016-06-11 09:31 UTC
**I'm submitting a ...**
I'm not sure... possibly an issue, possibly a bug, possibly just a request for clarification.  It's hard to tell for sure without knowing more, and I've hit a wall.

**Current behavior**
Using the most recent IE and Edge on Windows 10, mousemove events (and possibly others) over large amounts of angular-generated elements is very slow, causing usablity problems.

**Expected/desired behavior**
For these generated elements not to cause events to be throttled as such

**Background**
I tried creating a fake "selection rectangle" overlaying div to select underlying table cells for quick editing instead of one-by-one editing.  However, this selection rectangle responded to mousemove events painfully slowly in Internet Explorer (and I later noticed, Edge) causing the visual on-screen selection rectangle to update up to 10x slower than in other browsers.  I spent some time stripping unnecessary code until it boiled down to this code working as epexcted:

```
<tr *ngFor="let row of rows">
    <th>Name</th>
    <td>Fast</td><td>Fast</td><td>Fast</td><td>Fast</td><td>Fast</td>
</tr>
```

while this similar code introduces the problem of the throttled events:

```
<tr *ngFor="let row of rows">
    <th>Name</th>
    <td *ngFor="let col of cols">Slow</td>
</tr>
``` 

**Links**
- My question on StackOverflow that led to this: http://stackoverflow.com/questions/37725245/why-does-angular-2s-ngfor-generated-html-slow-down-event-processing-so-much-in
- The Plnkr I've put together to demo this issue:  http://plnkr.co/edit/782sd5CbM4psy98Wr1tj?p=preview

**Notes**
- _In trying to solve this, I've run across several issues about the speed at which angular creates the element - that's not my issue.  It's the frequency/rate of events such as mouseover on those elements after they've already been generated._
- _Due to the nature of the project, generating less elements isn't an option (and really, that shouldn't be necessary anyway)._
- _When viewing the Plnkr, please make sure to use Internet Explorer or Edge to be able to see the issue (although you can use another browser for comparison as well, of course)._
- _(UPDATED) This seems to be a problem with Windows 10 specifically.  It occurs on two separate Windows 10 systems, and does not occur on two separate Windows 7 systems.  I tried running Windows 7 in a VM on a Windows 10 system and it performs better there than it does in Windows 10.  I don't even know what to make of that anymore._

**Environment**
System:  Windows 10
Angular:  most recent (RC1), using Core-JS for IE
Browser:  Internet EXplorer 11 (most recent, older is probably also affected), Edge (most recent)
Language:  Typescript

**Comment by vicb** [comment] 2016-10-07 17:37
duplicate of https://github.com/angular/angular/issues/8112

**Closed by vicb** 2016-10-07 17:37 UTC
Labels: comp: core & compiler, freq3: high, severity4: broken, type: bug
