### ISSUE TITLE
tbody element is generated in wrong place

### ISSUE THREAD

**Issue by Lauris01** [angular/angular#8096] opened 2016-04-15 21:42 UTC
Run application and see html generated
http://plnkr.co/edit/nNc5ETPm7KvxkC6w3btt?p=preview

**Current behavior**
```
<table class="table">
    <thead>
    <tbody>    <- this tbody element is generated 
    <tr trset="">
        <!--template bindings={}-->
        <th class="sorting">
            nameTitle
        </th>
        <th class="sorting">
            urlTitle
        </th>
    </tr>
    </tbody>
    </thead>
    <tbody></tbody>
</table>
```

**Expected/desired behavior**
```
<table class="table">
    <thead>
    <tr trset="">
        <!--template bindings={}-->
        <th class="sorting">
            nameTitle
        </th>
        <th class="sorting">
            urlTitle
        </th>
    </tr>
    </thead>
    <tbody></tbody>
</table>

```
**Other information**

**Comment by ericmartinezr** [comment] 2016-04-15 21:51
To add more info : go to `sortable-header.component.ts` and remove the `tr` from the view and you'll see that the `tbody` disappears. If you add back the `tr`s the `tbody` appears automatically.

**Comment by ggmod** [comment] 2016-04-27 18:05
This is the same issue as the one discussed here: https://github.com/angular/angular/issues/5967
You can find a temporary fix there, but it involves writing into angular's code.

**Comment by pkozlowski-opensource** [comment] 2016-06-04 14:12
Indeed, this is duplicate of #5967, thnx for pointing this out @ggmod. Sounds like a really annoying bug that should be fixed before final. Let's continue the discussion in #5967

**Closed by pkozlowski-opensource** 2016-06-04 14:12 UTC
