### ISSUE TITLE
A text input  in a form does not update ngModel in tests

### ISSUE THREAD

**Issue by vduzh** [angular/angular#22548] opened 2018-03-02 10:12 UTC
## I'm submitting a...

<pre><code>
[x] Bug report  
</code></pre>

## Current behavior

I test a component containing a form element and a text input element in it. There is a two-way binding between the input element and a text property of a component class via ngModel directive. 

The test updates the input's value, fires dispatchEvent and checks the property of the component. The test fails: 
<pre><code>
Error: Expected 'Default title' to equal 'Updated Task'.
    at stack (http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?73bc53d3671677e6a093fc74e4f9bcde57e5f7ad:2338:17)
    at buildExpectationResult (http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?73bc53d3671677e6a093fc74e4f9bcde57e5f7ad:2308:14)
    at Spec.expectationResultFactory (http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?73bc53d3671677e6a093fc74e4f9bcde57e5f7ad:858:18)
    at Spec.addExpectationResult (http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?73bc53d3671677e6a093fc74e4f9bcde57e5f7ad:487:34)
    at Expectation.addExpectationResult (http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?73bc53d3671677e6a093fc74e4f9bcde57e5f7ad:802:21)
    at Expectation.toEqual (http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?73bc53d3671677e6a093fc74e4f9bcde57e5f7ad:2252:12)
    at http://localhost:9876/_karma_webpack_/webpack:/src/app/app.component.spec.ts:35:26
    at ZoneDelegate.webpackJsonp../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:388:1)
    at AsyncTestZoneSpec.webpackJsonp../node_modules/zone.js/dist/zone-testing.js.AsyncTestZoneSpec.onInvoke (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone-testing.js:479:1)
    at ProxyZoneSpec.webpackJsonp../node_modules/zone.js/dist/zone-testing.js.ProxyZoneSpec.onInvoke (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone-testing.js:236:1)
</code></pre>

**NOTE: If I comment out the form element in the **app.component.html** then the test passes.**

## Expected behavior

Chrome 64.0.3282 (Windows 7.0.0): Executed 1 of 1 SUCCESS

### 1. Create project:
**ng new angular-app**

### 2. Update files: 
**app.component.html** - replace all the text with the following:
```
<form novalidate (ngSubmit)="onSubmit()">
  <input name="title" type="text" [(ngModel)]="title">
</form>
```
**app.component.ts** - replace all the text with the following:
```
import {Component} from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'Default title';

  onSubmit() {
    console.log('title is:' + this.title);
  }
}
```
**app.component.spec.ts** - replace all the text with the following:
```
import {async, ComponentFixture, TestBed} from '@angular/core/testing';
import {FormsModule} from '@angular/forms';

import {AppComponent} from './app.component';
import {By} from "@angular/platform-browser";

describe('AppComponent', () => {
  let fixture: ComponentFixture<AppComponent>;
  let comp: AppComponent;

  beforeEach(async(() => {
    TestBed.configureTestingModule({
      declarations: [
        AppComponent
      ],
      imports: [FormsModule],
    }).compileComponents().then(() => {
      fixture = TestBed.createComponent(AppComponent);
      comp = fixture.debugElement.componentInstance;
    })
  }));

  it('should bind an input to a property (async)', async(() => {
    fixture.detectChanges();

    // Update the title input
    const inputElement = fixture.debugElement.query(By.css('input[name="title"]')).nativeElement;
    inputElement.value = 'Updated Task';
    inputElement.dispatchEvent(new Event('input'));

    fixture.whenStable().then(() => {
      fixture.detectChanges();
      expect(comp.title).toEqual('Updated Task');
    });
  }));
});
```
**app.module.ts** -  replace all the text with the following:
```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms';

import { AppComponent } from './app.component';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    FormsModule
  ],
  bootstrap: [AppComponent]
})
export class AppModule { }
```
## What is the motivation / use case for changing the behavior?
I need to test a component with a form inside.

### 3. Run tests:
**ng test**

## Environment
<pre><code>
Angular CLI: 1.7.2
Node: 8.5.0
OS: win32 x64
Angular: 5.2.7
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.7.2
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.1
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.5.3
webpack: 3.11.0

Browser:
- [*] Chrome (desktop) version XX
</code></pre>

**Comment by bcandullo** [comment] 2018-03-02 15:47
Tell the ng model you are using a stand alone control:
```
<input name="title" type="text" [(ngModel)]="title" [ngModelOptions]="{standalone: true}">
```

**Comment by vduzh** [comment] 2018-03-04 06:51
**bcandullo**, thanks for the comment. 

Is it a workaround just for testing? Because my code works well in browser. And I am not sure it a good idea to make such changes everywhere in the app just for testing.

**Comment by kara** [comment] 2018-03-29 22:30
This looks like a duplicate of https://github.com/angular/angular/issues/22606.

**Closed by kara** 2018-03-29 22:30 UTC
Labels: comp: forms

**Comment by DsAekb** [comment] 2018-08-29 14:43
The problem still exists. From what I could investigate so far, the ControlValueAccessor.registerOnChange is not even called on my custom component that is bound to ngModel. So the component can't notify NgModel about its change.
