### ISSUE TITLE
ERROR in TypeError: Cannot read property 'flags' of undefined

### ISSUE THREAD

**Issue by magicdict** [angular/angular#36993] opened 2020-05-08 02:36 UTC
# 🐞 bug report

### Affected Package
Unknown，Just upgrade form 9.1.4 to 9.1.5.

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

ERROR in TypeError: Cannot read property 'flags' of undefined

## 🔥 Exception or Error
<pre><code>
Compiling primeng/toast : es2015 as esm2015
Compiling primeng/togglebutton : es2015 as esm2015
Compiling primeng/toolbar : es2015 as esm2015
Compiling primeng/tree : es2015 as esm2015
Compiling primeng/tristatecheckbox : es2015 as esm2015

chunk {main} main.js, main.js.map (main) 1.97 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 661 bytes [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.15 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 1.51 MB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 339 kB [initial] [rendered]
Date: 2020-05-08T02:31:39.787Z - Hash: ce73c7a432145f234c81 - Time: 10711ms

ERROR in TypeError: Cannot read property 'flags' of undefined
    at resolveAlias (F:\sodic2020\UI\node_modules\typescript\lib\typescript.js:36513:37)
    at checkAliasSymbol (F:\sodic2020\UI\node_modules\typescript\lib\typescript.js:64502:26)
    at checkImportBinding (F:\sodic2020\UI\node_modules\typescript\lib\typescript.js:64534:13)
    at checkImportDeclaration (F:\sodic2020\UI\node_modules\typescript\lib\typescript.js:64552:29)
    at checkSourceElementWorker (F:\sodic2020\UI\node_modules\typescript\lib\typescript.js:64961:28)
    at checkSourceElement (F:\sodic2020\UI\node_modules\typescript\lib\typescript.js:64800:17)
    at Object.forEach (F:\sodic2020\UI\node_modules\typescript\lib\typescript.js:317:30)
    at checkSourceFileWorker (F:\sodic2020\UI\node_modules\typescript\lib\typescript.js:65123:20)
    at checkSourceFile (F:\sodic2020\UI\node_modules\typescript\lib\typescript.js:65091:13)
    at getDiagnosticsWorker (F:\sodic2020\UI\node_modules\typescript\lib\typescript.js:65179:17)
    at Object.getDiagnostics (F:\sodic2020\UI\node_modules\typescript\lib\typescript.js:65165:24)
    at F:\sodic2020\UI\node_modules\typescript\lib\typescript.js:98703:85
    at runWithCancellationToken (F:\sodic2020\UI\node_modules\typescript\lib\typescript.js:98665:24)
    at getBindAndCheckDiagnosticsForFileNoCache (F:\sodic2020\UI\node_modules\typescript\lib\typescript.js:98691:20)
    at getAndCacheDiagnostics (F:\sodic2020\UI\node_modules\typescript\lib\typescript.js:98956:26)
    at getBindAndCheckDiagnosticsForFile (F:\sodic2020\UI\node_modules\typescript\lib\typescript.js:98688:20)

** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.1.4
Node: 12.16.1
OS: win32 x64

Angular: 9.1.5
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.4
@angular-devkit/build-angular     0.901.4
@angular-devkit/build-optimizer   0.901.4
@angular-devkit/build-webpack     0.901.4
@angular-devkit/core              9.1.4
@angular-devkit/schematics        9.1.4
@angular/cli                      9.1.4
@ngtools/webpack                  9.1.4
@schematics/angular               9.1.4
@schematics/update                0.901.4
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0

</code></pre>

**Anything else relevant?**

**Comment by guillermohernandez** [comment] 2020-05-08 03:42
Run:
npm install @angular/core@9.1.4 @angular/animations@9.1.4 @angular/common@9.1.4 @angular/forms@9.1.4 @angular/platform-browser@9.1.4 @angular/router@9.1.4 @angular/platform-browser-dynamic@9.1.4 @angular/compiler@9.1.4 @angular/compiler-cli@9.1.4 @angular/language-service@9.1.4

ng build

From: https://stackoverflow.com/a/61671596/5157008

**Comment by magicdict** [comment] 2020-05-08 04:18
> Run:
> npm install @angular/core@9.1.4 @angular/animations@9.1.4 @angular/common@9.1.4 @angular/forms@9.1.4 @angular/platform-browser@9.1.4 @angular/router@9.1.4 @angular/platform-browser-dynamic@9.1.4 @angular/compiler@9.1.4 @angular/compiler-cli@9.1.4 @angular/language-service@9.1.4
> 
> ng build
> 
> From: https://stackoverflow.com/a/61671596/5157008

just rollback，wait for fix

**Comment by petebacondarwin** [comment] 2020-05-08 10:01
Possible duplicate of #36992

**Comment by yangjunfocus** [comment] 2020-05-08 11:03
I have same issue.
`ERROR in TypeError: Cannot read property 'flags' of undefined at resolveAlias (E:\Angular\node_modules\typescript\lib\typescript.js:36513:37) at checkAliasSymbol (E:\Angular\node_modules\typescript\lib\typescript.js:64502:26) at checkImportBinding (E:\Angular\node_modules\typescript\lib\typescript.js:64534:13) at checkImportDeclaration (E:\Angular\node_modules\typescript\lib\typescript.js:64552:29) at checkSourceElementWorker (E:\Angular\node_modules\typescript\lib\typescript.js:64961:28) at checkSourceElement (E:\Angular\node_modules\typescript\lib\typescript.js:64800:17) at Object.forEach (E:\Angular\node_modules\typescript\lib\typescript.js:317:30) at checkSourceFileWorker (E:\Angular\node_modules\typescript\lib\typescript.js:65123:20) at checkSourceFile (E:\Angular\node_modules\typescript\lib\typescript.js:65091:13) at getDiagnosticsWorker (E:\Angular\node_modules\typescript\lib\typescript.js:65179:17) at Object.getDiagnostics (E:\Angular\node_modules\typescript\lib\typescript.js:65165:24) at E:\Angular\node_modules\typescript\lib\typescript.js:98703:85 at runWithCancellationToken (E:\Angular\node_modules\typescript\lib\typescript.js:98665:24) at getBindAndCheckDiagnosticsForFileNoCache (E:\Angular\node_modules\typescript\lib\typescript.js:98691:20) at getAndCacheDiagnostics (E:\Angular\node_modules\typescript\lib\typescript.js:98956:26) at getBindAndCheckDiagnosticsForFile (E:\Angular\node_modules\typescript\lib\typescript.js:98688:20)`

**Comment by PierreMigne** [comment] 2020-05-08 11:39
How can i rollback to 9.1.4 ?

**Comment by destus90** [comment] 2020-05-08 11:43
> How can i rollback to 9.1.4 ?

https://stackoverflow.com/questions/61670882/error-in-typeerror-cannot-read-property-flags-of-undefined/61671596#61671596

**Comment by igorosabel** [comment] 2020-05-08 12:14
Same issue, updating 9.1.4 to 9.1.5. Weird thing is that only happens on Win10, on macOS 10.15.4 works fine.

**Comment by SourabhJha** [comment] 2020-05-08 12:14
> > How can i rollback to 9.1.4 ?
> 
> https://stackoverflow.com/questions/61670882/error-in-typeerror-cannot-read-property-flags-of-undefined/61671596#61671596

I has same issue with 9.1.4 , So believe no point rolling back.

**Comment by JoshuvaGeorge03** [comment] 2020-05-08 12:19
Same here, I am having this error too. after updating from angular 9.1.4 to 9.1.5

"@angular/animations": "^9.1.5", "@angular/common": "^9.1.5", "@angular/compiler": "^9.1.5", "@angular/core": "^9.1.5", "@angular/forms": "^9.1.5", "@angular/platform-browser": "^9.1.5", "@angular/platform-browser-dynamic": "^9.1.5", "@angular/router": "^9.1.5",

how to fix this issue?

**Comment by FabienDehopre** [comment] 2020-05-08 13:27
I have the same error when updating from 9.1.4 to 9.1.5.
```
ERROR in TypeError: Cannot read property 'flags' of undefined
    at resolveAlias (c:\Projects\Mithra\mithra-web\node_modules\typescript\lib\typescript.js:36513:37)
    at checkAliasSymbol (c:\Projects\Mithra\mithra-web\node_modules\typescript\lib\typescript.js:64502:26)
    at checkImportBinding (c:\Projects\Mithra\mithra-web\node_modules\typescript\lib\typescript.js:64534:13)
    at checkImportDeclaration (c:\Projects\Mithra\mithra-web\node_modules\typescript\lib\typescript.js:64552:29)
    at checkSourceElementWorker (c:\Projects\Mithra\mithra-web\node_modules\typescript\lib\typescript.js:64961:28)
    at checkSourceElement (c:\Projects\Mithra\mithra-web\node_modules\typescript\lib\typescript.js:64800:17)
    at Object.forEach (c:\Projects\Mithra\mithra-web\node_modules\typescript\lib\typescript.js:317:30)
    at checkSourceFileWorker (c:\Projects\Mithra\mithra-web\node_modules\typescript\lib\typescript.js:65123:20)
    at checkSourceFile (c:\Projects\Mithra\mithra-web\node_modules\typescript\lib\typescript.js:65091:13)
    at getDiagnosticsWorker (c:\Projects\Mithra\mithra-web\node_modules\typescript\lib\typescript.js:65179:17)
    at Object.getDiagnostics (c:\Projects\Mithra\mithra-web\node_modules\typescript\lib\typescript.js:65165:24)
    at c:\Projects\Mithra\mithra-web\node_modules\typescript\lib\typescript.js:98703:85
    at runWithCancellationToken (c:\Projects\Mithra\mithra-web\node_modules\typescript\lib\typescript.js:98665:24)
    at getBindAndCheckDiagnosticsForFileNoCache (c:\Projects\Mithra\mithra-web\node_modules\typescript\lib\typescript.js:98691:20)
    at getAndCacheDiagnostics (c:\Projects\Mithra\mithra-web\node_modules\typescript\lib\typescript.js:98956:26)
    at getBindAndCheckDiagnosticsForFile (c:\Projects\Mithra\mithra-web\node_modules\typescript\lib\typescript.js:98688:20)
```
I had to revert to 9.1.4 to solve the issue

**Comment by petebacondarwin** [comment] 2020-05-08 17:13
We have just released 9.1.6 which should not have this problem. Please test.

**Comment by sahad78** [comment] 2020-05-08 20:42
Upgrading to 9.1.6 has now solved the issue
Thanks

**Comment by mgechev** [comment] 2020-05-08 21:01
As @petebacondarwin mentioned, upgrading to 9.1.6 should fix the problem. Closing the issue now. In case the problem is still not resolved, feel free to open a new one.

**Closed by mgechev** 2020-05-08 21:01 UTC

**Comment by SourabhJha** [comment] 2020-05-09 18:28
Angular 9.1.6 solved the problems, Thank you
