### ISSUE TITLE
Exception occurred in Resolver is not caught

### ISSUE THREAD

**Issue by kaito3desuyo** [angular/angular#38493] opened 2020-08-17 04:54 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/router.

### Is this a regression?

 No, it wasn't working at least in v9.1.11.

### Description

 All kinds of exceptions can occur inside the Resolver. When Resolver detects an exception, it stops processing without routing.
However, it doesn't catch the detected exception anywhere, so it shows up as an Uncaught error in the console.

## 🔬 Minimal Reproduction

 https://stackblitz.com/edit/angular-ivy-8qwgvb

## 🔥 Exception or Error

This code is written in StackBlitz.

```
import { Injectable } from "@angular/core";
import { Resolve } from "@angular/router";
import { Observable, of, throwError } from "rxjs";
import { tap, catchError, flatMap } from "rxjs/operators";

@Injectable({providedIn: 'root'})
export class TestResolver implements Resolve<Observable<void>> {
  resolve(): Observable<void> {
    return of(null).pipe(
      flatMap(() => {
        return throwError(new Error('throw Error!'))
      }),
      catchError((e, caught) => {
        return throwError(e);
      })
    )
  }
}
```

```
ERROR
Error: Uncaught (in promise): Error: Error throw!
Error: Error throw!
at MergeMapSubscriber.eval [as project] (https://angular-ivy-8qwgvb.stackblitz.io/~/src/app/test/test.resolver.ts:12:38)
at MergeMapSubscriber._tryNext (https://angular-ivy-8qwgvb.stackblitz.io/turbo_modules/rxjs@6.6.2/internal/operators/mergeMap.js:67:27)
at MergeMapSubscriber._next (https://angular-ivy-8qwgvb.stackblitz.io/turbo_modules/rxjs@6.6.2/internal/operators/mergeMap.js:57:18)
at MergeMapSubscriber.Subscriber.next (https://angular-ivy-8qwgvb.stackblitz.io/turbo_modules/rxjs@6.6.2/internal/Subscriber.js:66:18)
at Observable.eval [as _subscribe] (https://angular-ivy-8qwgvb.stackblitz.io/turbo_modules/rxjs@6.6.2/internal/util/subscribeToArray.js:5:20)
at Observable._trySubscribe (https://angular-ivy-8qwgvb.stackblitz.io/turbo_modules/rxjs@6.6.2/internal/Observable.js:44:25)
at Observable.subscribe (https://angular-ivy-8qwgvb.stackblitz.io/turbo_modules/rxjs@6.6.2/internal/Observable.js:30:22)
at MergeMapOperator.call (https://angular-ivy-8qwgvb.stackblitz.io/turbo_modules/rxjs@6.6.2/internal/operators/mergeMap.js:37:23)
at Observable.subscribe (https://angular-ivy-8qwgvb.stackblitz.io/turbo_modules/rxjs@6.6.2/internal/Observable.js:25:31)
at CatchOperator.call (https://angular-ivy-8qwgvb.stackblitz.io/turbo_modules/rxjs@6.6.2/internal/operators/catchError.js:30:23)
```

## 🌍  Your Environment

**Angular Version:**
```
Angular CLI: 9.1.9
Node: 12.17.0
OS: linux x64

Angular: 9.1.11
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.901.1
@angular-devkit/build-angular      0.901.9
@angular-devkit/build-optimizer    0.901.9
@angular-devkit/build-webpack      0.901.9
@angular-devkit/core               7.3.10
@angular-devkit/schematics         7.3.10
@angular/cdk                       9.2.4
@angular/cli                       9.1.9
@angular/flex-layout               9.0.0-beta.29
@angular/material                  9.2.4
@angular/material-moment-adapter   9.2.4
@ngtools/webpack                   9.1.9
@schematics/angular                9.1.9
@schematics/update                 0.901.9
rxjs                               6.5.5
typescript                         3.7.5
webpack                            4.42.0
```

**Comment by atscott** [comment] 2020-08-18 02:36
duplicate of #13873 / #25589

Note that the error is actually caught in the `ErrorHandler`. If you want the error to be ignored, you can create your own and handle `NavigationError`s specially:
https://stackblitz.com/edit/angular-ivy-cybfsu?file=src%2Fapp%2Ferrorhandler.ts

**Closed by atscott** 2020-08-18 02:36 UTC
Labels: comp: router, router: guards/resolvers, router: navigation pipe
