### ISSUE TITLE
[compiler] fullTemplateTypeCheck should rise meaningful errors on invalid HostListener

### ISSUE THREAD

**Issue by lukaszsamson** [angular/angular#21532] opened 2018-01-14 16:58 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Compiling code included in repro with `fullTemplateTypeCheck ` results in
```
ERROR in src/app/common/components/amount/amount.component.html(8,1): : Directive SpinnerButtonDirective, Expected 0 arguments, but got 1.
```
## Expected behavior

Meaningful error message, e.g. HostListener handler SpinnerButtonDirective.onMouseDown should have one argument of type x

## Minimal reproduction of the problem with instructions

```
@Directive({
    selector: '[spinnerButton]'
})
export class SpinnerButtonDirective {
    @HostListener('mousedown', ['$event'])
    public onMouseDown() {
    }
}
```
amount.component.desktop.html
```
<div spinnerButton">
    -
</div>
```

## What is the motivation / use case for changing the behavior?

Current message is not helpful

## Environment

<pre><code>
Angular version: 5.2.0

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: all supported  
- Platform: all supported 

Others:

</code></pre>

**Comment by Toxicable** [comment] 2018-01-14 17:16
Angular is not producing that error, that's a TS error, therefore we cannot change the message
Here's an example https://www.typescriptlang.org/play/#src=function%20someFn(name%3A%20string)%20%7B%0D%0A%20%20%20%20%0D%0A%7D%0D%0A%0D%0A%0D%0AsomeFn()%3B

**Comment by lukaszsamson** [comment] 2018-01-14 17:33
@Toxicable true but TS is able to associate this message with the correct file and line number. Angular compiler leaves you in the dark.

**Comment by Toxicable** [comment] 2018-01-14 18:33
Ok so you're asking for a change to the source mapping?

**Comment by emilio-martinez** [comment] 2018-04-27 15:53
This is a duplicate of #21329

**Comment by JoostK** [comment] 2019-10-18 23:53
Thanks for reporting! This is indeed a duplicate of #21329, for which I expect to have a much needed improvement in the near future.

**Closed by JoostK** 2019-10-18 23:53 UTC
Labels: comp: core, hotlist: error messages, type: feature
