### ISSUE TITLE
images not rendering in Property Binding example 

### ISSUE THREAD

**Issue by kapunahelewong** [angular/angular#35618] opened 2020-02-21 17:42 UTC
# 📚 Docs or angular.io bug report

### Description

In Template Syntax, the Property Binding example images (in the StackBlitz example) aren't rendering.

### What's the affected URL?**
https://stackblitz.com/angular/envrboojygp?file=src%2Fapp%2Fapp.component.ts

### Reproduction Steps**

Only have to visit the link to see them not render.

## 📷Screenshot

![image](https://user-images.githubusercontent.com/4116963/75057615-722c5100-54a7-11ea-8b52-20949c9f3450.png)

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by sonukapoor** [comment] 2020-02-22 17:14
@kapunahelewong I can work on this. Can you assign it to me please?

**Comment by sonukapoor** [comment] 2020-02-23 01:48
@kapunahelewong Stackblitz currently does not support uploaded images from stackblitz. I have changed the URL to use the github url directly.

**Comment by gkalpak** [comment] 2020-02-24 15:21
BTW, there also seems to be an issue with the ZIP archive (potentially related to how we encode the PNG while archiving 🤷‍♂).

**Comment by EricSimons** [comment] 2020-02-24 18:18
Hey! Not sure if this is a regression or bug on our end, but will investigate and circle back by EOD!

**Comment by EricSimons** [comment] 2020-02-25 00:52
Okay, so it appears that the image in that Angular project for some reason didn't successfully upload to our S3 bucket during creation 🤔 Have you noticed any other projects that have exhibited this same behavior? Curious if this is a recurring issue or just a random glitch.

Also, do y'all have a link to that raw image? I can manually upload it to our s3 bucket which should fix this specific project :)

**Comment by sonukapoor** [comment] 2020-02-25 01:16
@EricSimons I just checked another example, that doesn't show image either:

https://stackblitz.com/angular/ooydpgymogr?file=src%2Fapp%2Fapp.component.ts

**Comment by gkalpak** [comment] 2020-02-25 10:29
Thx for looking into this, @EricSimons 🤖

##
The image for https://stackblitz.com/angular/envrboojygp is:
- [phone.png][1]

##
The images for https://stackblitz.com/angular/ooydpgymogr are:
- [lamp.png][2]
- [potted-plant.png][3]

##
Any idea if these are random upload issues or we are doing something wrong (i.e. send incorrect data). Can we do anything to help investigate this?

[1]: https://github.com/angular/angular/blob/master/aio/content/examples/property-binding/src/assets/phone.png
[2]: https://raw.githubusercontent.com/angular/angular/master/aio/content/examples/interpolation/src/assets/lamp.png
[3]: https://raw.githubusercontent.com/angular/angular/master/aio/content/examples/interpolation/src/assets/potted-plant.png

**Comment by sonukapoor** [comment] 2020-02-28 04:52
@EricSimons Were you able to upload the images? I don't see them in the examples @gkalpak posted above.

**Comment by gkalpak** [comment] 2020-03-13 09:22
@EricSimons, any updates on this?

**Comment by EricSimons** [comment] 2020-03-17 22:52
Hey all- sorry about my delay, the world has been crazy the past few weeks 😓 

We uploaded these images to the S3 bucket so this should now be resolved. We need to do additional investigation into why this happened in the first place, so please let me know if you run across similar problems to help us w/ the debugging on our end 👍

**Comment by sonukapoor** [comment] 2020-03-18 12:36
@EricSimons Thanks, however, there is still one missing:

Stackblitz:

- https://stackblitz.com/angular/ooydpgymogr

Missing image:

- https://raw.githubusercontent.com/angular/angular/master/aio/content/examples/interpolation/src/assets/potted-plant.png

**Comment by EricSimons** [comment] 2020-03-18 15:56
It appears that's a bug in the demo's source code itself- `potted_plant.png` is being incorrectly being referenced as camelcase `pottedPlant.png` in [app.component.ts](https://stackblitz.com/angular/ooydpgymogr?file=src%2Fapp%2Fapp.component.ts)

**Comment by sonukapoor** [comment] 2020-03-18 18:18
I see the issue, and will fix it.

**Closed** 2020-03-20 17:20 UTC
Labels: comp: docs, freq1: low, severity3: broken, state: has PR, type: bug/fix
