### ISSUE TITLE
Currency Pipe - not showing currency symbol £ for locale en-GB

### ISSUE THREAD

**Issue by wmgdev** [angular/angular#22519] opened 2018-03-01 12:01 UTC
## I'm submitting a...

<pre><code>
[ x] Bug report  ?
</code></pre>

## Current behavior
The currency pipe is not displaying the correct currency symbol for locale en-GB (united Kingdom) which should be £ (GBP)
Instead it is displaying $ (USD)
```
01/03/2018, 11:34
$2,000.10
```
The date pipe is however picking up the correct date locale information ??

## Expected behavior
The currency pipe should show £ (GBP)
```
01/03/2018, 11:34
£2,000.10
```

## Minimal reproduction of the problem with instructions
Create new angular-cli project
My app.module.ts

```
import { BrowserModule } from '@angular/platform-browser';
import { LOCALE_ID, NgModule } from '@angular/core';
import { AppComponent } from './app.component';


@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule
  ],
  providers: [{ provide: LOCALE_ID, useValue: 'en-GB' }],
  bootstrap: [AppComponent]
})
export class AppModule { }
```
My app.component.ts
```
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  template: `
      <div>
      {{today | date:'short'}}
    </div>
    <div>
      {{amount | currency}}
    </div>
  `
})
export class AppComponent {
  today: Date = new Date();
  amount = 2000.10;
}

```
This displays
```
01/03/2018, 11:34
$2,000.10
```
but it should display
```
01/03/2018, 11:34
£2,000.10
```
I am using 
`
ng serve --locale en-GB`

as described here [https://angular.io/guide/i18n#i18n-pipes](https://angular.io/guide/i18n#i18n-pipes)

Help. What am I doing wrong :)

## Environment

<pre><code>
Angular-cli version: 1.6.8
Angular version: 5.2.0
</code></pre>

**Comment by trotyl** [comment] 2018-03-01 12:08
Duplicate of #21660, expected behavior.

**Comment by wmgdev** [comment] 2018-03-01 13:23
If I set my locale to en-GB my expectation is that 'amount: number = 10.00' when piped through Currency Pipe would appear £10.00

In the duplicate issue it is stated..
_The locale will only change the formatting for the currency pipe, it will not change the currency itself....The locale will never change the currency code that you use because it makes no sense, $10 is the same value in all locales, you will just write it differently ($10 in english, 10 $ in spanish)_

Is that not a bit US-centric.
I agree 10 is 10 in all locales but 10 is not $10 in all locales
It assumes that all numbers are based on and default to currency code $ regardless of locale. 
Should my locale also not set my default currency code?

As it is, if I am writing an app in United Kingdom, I have to use {{amount | currency:'GBP'}} every time I display a number as currency instead of just {{amount | currency}} even tho I have set my locale.

**Comment by wmgdev** [comment] 2018-03-01 14:45
I've created a stackblitz to demonstrate
[https://stackblitz.com/edit/angular-he1pqa](https://stackblitz.com/edit/angular-he1pqa)

It seems I need to use {{ fee | currency:'GBP' }} to display the £
If I move my app to a different locale, will I have to change all my html ?

**Comment by ocombe** [comment] 2018-03-05 12:28
You need to set the currency that you want to display, and that's the expected behavior.
It's to avoid the money to be showed in the wrong currency, because $10 !== 10£, it doesn't have the same value.
Otherwise people could forget to set the currency and get wrong values. It's better to be explicit in this case.

**Closed by ocombe** 2018-03-05 12:28 UTC
Labels: comp: i18n

**Comment by agusdutra** [comment] 2018-08-08 15:44
Is there a way to change the default currency for currency pipe? (it takes US dollars as default)

I'm from Uruguay and we use the $ symbol to represent our local currency (Uruguaian Pesos), US dollars are represented as US$. The dot (.) as thousand separators and the comma (,) as decimal separator. I'm working on a project where we have to use only local currency ($)

So if I want to show $ 10.000,50 (ten thousands and fifty cents uruguaian pesos) as @wmgdev sayed, I have to put in every html  {{ 10000.50 | currency:'es-UY' }} 

If I only put {{ 10000.50 | currency }} it shows me 10.000,50 US$. 

I think the default symbol for the currency shouldn't be US dollars but the default currency for the locale that is setted. Is there a way to achieve that? Maybe I'm missing something.

Thanks

**Comment by ocombe** [comment] 2018-08-13 09:13
@agusdutra we don't set the default currency symbol. See my comment above yours.
The documentation that explains how to set the currency symbol is here: https://angular.io/api/common/CurrencyPipe

**Comment by pRoy24** [comment] 2019-03-09 08:13
> You need to set the currency that you want to display, and that's the expected behavior.
> It's to avoid the money to be showed in the wrong currency, because $10 !== 10£, it doesn't have the same value.
> Otherwise people could forget to set the currency and get wrong values. It's better to be explicit in this case.

I want to set the currency symbol automatically depending on browser locale. I want to pipe in the locale and want the default currency symbol to be automatically determined without having to do additional lookups. How do I do that if it automatically assumes $ as the currency.

**Comment by JosepAlacid** [comment] 2019-05-04 17:51
> It's to avoid the money to be showed in the wrong currency, because $10 !== 10£, it doesn't have the same value.

Yeah, that's why all Angular default currency should be in EUR: to remember all developers that the only accepted currency in server databases is EUR. They should forget that little issue and get people confused.

When you are coding for, let's say, Surinam, you have to pay attention and store currency values in server databases in EUR and then do the conversion to their local currency at front-end code and fill all currency pipes in all the code to the symbol of their currency, so you don't forget to do the money conversion daily based on EUR market value.
Even you set the locale to the format of your country, don't forget EUR is the only accepted -or at least best practice- currency in server databases and conversion to locale is necessary to avoid confusions.

That's the expected behavior...

*change every EUR occurrence in the text to the actual default currency in Angular source code.

**Comment by JosepAlacid** [comment] 2019-05-22 21:46
If I set locale of my webpage to GBP is just because all currency values are in GBP and not in user's locale configuration nor USD!!

**Comment by adutra-capicua** [comment] 2019-05-22 22:09
@JosepAlacid locale_id != currency_id

**Comment by JosepAlacid** [comment] 2019-05-22 22:17
So I can force "Suntag" but not "Euro".

**Comment by JosepAlacid** [comment] 2019-05-22 22:28
You can't imagine how happy I am to know that if I forget currency:"EUR" in each and every price on my site, all my users will see "USD$"...
And there's no way to set "EUR" symbol currency as default. Default will always be "USD"????
