### ISSUE TITLE
docs: Add full browser support on Angular.dev's Tutorials and Playground

### ISSUE THREAD

**Issue by digit81** [angular/angular#52566] opened 2023-11-07 05:57 UTC
[WebContainers](https://webcontainers.io/) have full browser support. Please add full browser support to angular.dev  embedded tutorials as well.

[Learn Angular Tutorials](https://angular.dev/tutorials/learn-angular)

```true
Mozilla Firefox 119.0
```

**Comment by pjmlp** [comment] 2023-11-08 13:21
Yes, apparently the new site is following the "_Works best on IE_" past, only now Chrome has taken place of IE.

**Comment by twerske** [comment] 2023-11-09 00:48
Totally agree! We will keep this issue open to track the browser support story for Angular.dev's WebContainers.

To share some context, we were working to support Firefox up until the day before launch and unfortunately could not guarantee it would not hit a memory allocation error and crash, thus we temporarily disabled it to ensure users wouldn't experience a tab crash on launch day.

We are absolutely still working on this and in no way saying you need to use Chrome to use Angular.dev.

Our hope is that we can move the repo to open source and then our amazing partners at Stackblitz will be helping us further debug this issue, along with our Tooling team since we suspect this is related to our application builder within the WebContainers. Since the site is in beta, thank you for your patience while we focus on open sourcing the repo before continuing to work on this issue.

**Comment by twerske** [comment] 2023-11-09 01:40
Closing as a duplicate of https://github.com/angular/angular/issues/52640 - this is still ongoing and a top priority!

**Closed by twerske** 2023-11-09 01:40 UTC
Labels: hotlist: devrel, area: adev-docs
