### ISSUE TITLE
how to serve from  server.ts

### ISSUE THREAD

**Issue by hkashlan** [angular/angular#58130] opened 2024-10-09 06:12 UTC
### Description

I am trying to include the trpc in angular server.ts like https://trpc.io/docs/server/adapters/express

the issue the application is not starting from server.ts

### Proposed solution

we have several options:

- have a flag in serve to start from server.ts
- have a new command to server from sever.ts

### Alternatives considered

running from server.ts may improve the angular Fullstack for ssr, especially if we can debug it.
in this way Angular can move from only client framework to full stack
BTW I tried analogjs and it is not mature enough like nextjs

**Comment by JeanMeche** [comment] 2024-10-09 06:26
Duplicate of angular/angular-cli#26323. 

This is a known issue in v18 and has already been addressed for v19.

**Closed by JeanMeche** 2024-10-09 06:26 UTC
