### ISSUE TITLE
RC5 changes - ? operator and async

### ISSUE THREAD

**Issue by brianchance** [angular/angular#10695] opened 2016-08-11 16:44 UTC
**I'm submitting a ...**  (check one with "x")
```
[x?] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Previous behavior**
Using RC4, the following would work...
`*ngIf="(searchResults | async)?.length > 0"`
or
`*ngIf="(searchResults | async)?.length == 0"`

**Current behavior**
RC5 throws 
`TypeError: Cannot read property 'length' of null`

This syntax does work in RC5
`*ngIf="((searchResults | async) || []).length > 0"`
and
`*ngIf="((searchResults | async) || {}).length == 0"`

**What is the expected behavior?**
The original RC4 behavior seems more intuitive, especially when checking `.length == 0` since it did not evaluate until the observable returned.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** [Chrome ] 
 
* **Language:** [TypeScript 1.9]

**Comment by pkozlowski-opensource** [comment] 2016-08-11 17:03
Duplicate of #10639

**Closed by pkozlowski-opensource** 2016-08-11 17:03 UTC
