### ISSUE TITLE
Change value of <input type="file"> doesn't trigger any validators in model driven form approach. 

### ISSUE THREAD

**Issue by MarcinMilewski** [angular/angular#12614] opened 2016-10-30 11:10 UTC
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Changing value of enabled `<input type="file">` doesn't trigger any validators. Only need to change type to "text" and everything is working as expected.

**Expected behavior**
Changing value of `<input type="file">` should trigger validators. 

**Minimal reproduction of the problem with instructions**
 View
```
<md-card>
  <md-card-title>Audio test creator</md-card-title>
  <md-card-content>
    <form [formGroup]="creationForm" (ngSubmit)="onSubmit(creationForm)">
      
      <select (change)="onChange($event.target.value)" class="custom-select"      formControlName="method">
        <option value="" selected disabled>Test method</option>
        <option *ngFor="let testMethod of testMethods" [value]="testMethod.value">
          {{testMethod.display}}
        </option>
      </select>

      <md-input placeholder="Test name" type="text" formControlName="name"></md-input>

      <div [formGroup]="abxForm" >
        <input type="file" formControlName="soundA" (change)="onInputChange($event.target.value)">
      </div>

      <button type="submit" [disabled]="!creationForm.valid">Submit</button>
    </form>

  </md-card-content>
</md-card>

```
 Component class
```
export class SoundTestCreatorComponent implements OnInit {

  readonly ABX_SECTION = "abxForm";

  abxForm: FormGroup;
  creationForm : FormGroup;

  testMethods = [
    {value: SoundTestEnum[SoundTestEnum.ABX], display: SoundTestEnum[SoundTestEnum.ABX]},
    {value: SoundTestEnum[SoundTestEnum.MUSHRA], display: SoundTestEnum[SoundTestEnum.MUSHRA]}
  ];

  constructor(private fb: FormBuilder) {
    this.creationForm = this.fb.group({
      "name": ["", Validators.required],
      "method": ["", Validators.required],
    });

    this.abxForm = this.fb.group({
      "soundA": ["", CustomValidators.fileInputRequired]
    });
  }

  ngOnInit() { }

  onSubmit(creationForm : any) {
    console.log('Test creation form submitted');
    console.log(creationForm);
  }

  onChange(selectedMethod : string) {
    this.removeFormSections();
    if(selectedMethod === SoundTestEnum[SoundTestEnum.ABX]) {
      this.addAbxFormSection();
    }
    if(selectedMethod === SoundTestEnum[SoundTestEnum.MUSHRA]) {
    }
    console.log(selectedMethod);
  }

  private addAbxFormSection() {
    this.creationForm.addControl(this.ABX_SECTION, this.abxForm);
  }

  private removeFormSections() {
      this.creationForm.removeControl(this.ABX_SECTION);
  }

  onInputChange(val) {
    console.log(val);
    console.log(this.abxForm.enabled);
  }
```

CustomValidator to check calls.

```
function isEmptyInputValue(value: any) {
  return value == null || typeof value === 'string' && value.length === 0;
}

export class CustomValidators {
  static fileInputRequired(c: FormControl) {
    return (isEmptyInputValue(c.value)) ? {
      fileInputRequired: {
        valid: false
      }
    } : null;
  }
}
```

* **Angular version:** 2.1

* **Browser:**  ALL
 
* **Language:** [ TypeScript 2.0.2 ]

* **Node (for AoT issues):** `node --version` =   6.0.0

**Comment by DzmitryShylovich** [comment] 2016-10-30 11:27
Duplicate of https://github.com/angular/angular/issues/7341

**Comment by pkozlowski-opensource** [comment] 2016-10-30 18:38
As @DzmitryShylovich have said! Thnx.

**Closed by pkozlowski-opensource** 2016-10-30 18:38 UTC
