### ISSUE TITLE
[BUG] skipLocalChange when manually navigating falls back to default

### ISSUE THREAD

**Issue by tam5** [angular/angular#19937] opened 2017-10-25 22:24 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

It is possible to navigate without changing the URL in a resolve by doing:

    this.router.navigate(['/404'], { skipLocationChange: true })

This works when getting to this guard from within the app. However, when navigating directly to the page, ex: typing in `/posts/1234` the router changes the URL to the fallback route (though the "PageNotFound" component is correctly displayed). If `skipLocationChange` is false, everything works as expected, but then you have '/404' in the url.

## Expected behavior

`skipUrlChange` should prevent the URL from changing even when navigating manually/externally to a route.

## Minimal reproduction of the problem with instructions

Example project, modified tour of heroes: https://github.com/tam5/skipLocationChange

Clone, install, and run the project. Navigate to a hero details page by clicking and you will see the "Page not found" while still on "/dashboard", but if you manually navigate to `/detail/11` you will be taken to the root.

## What is the motivation / use case for changing the behavior?

I don't want the user to experience a URL change when a resolver fails, but I do want to be able to display a 404 (or 401/403, etc.) page 

## Environment

<pre><code>
Angular version: 2-4 (see github example for exact example versions)

Browser:
all

**Comment by trotyl** [comment] 2017-10-26 06:35
Duplicate of #16981.

**Comment by jasonaden** [comment] 2017-11-09 22:56
Closing as a duplicate.

**Closed by jasonaden** 2017-11-09 22:56 UTC
