### ISSUE TITLE
Quality of documentation

### ISSUE THREAD

**Issue by moriciogithub** [angular/angular#31557] opened 2019-07-15 00:07 UTC
# 📚 Docs or angular.io bug report

### Description

 A clear and concise description of the problem...

**1. Using obscure declarations to explain obscure concepts is a horrible way of writing documentation.
2. The use of line numbering added to source code, adds a terrible experience to the horrible documentation
3. The use of code snippets outside of real examples make them useless! Where do things go?**

## 🔬 Minimal Reproduction
For example:

**"Observables
Observables provide support for passing messages between publishers and subscribers in your application. Observables offer significant benefits over other techniques for event handling, asynchronous programming, and handling multiple values."**

### What's the affected URL?**
 https://angular.io/...
The whole site.

### Reproduction Steps**

Put a non experienced person in Angular to read.

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by Airblader** [comment] 2019-07-15 04:26
The Angular team may well see this differently, but personally I never understand why someone without any experience would or should "sit down in front of Angular" — or any other frontend framework — and be able to understand it.

If you have no experience, you should focus on learning basics of the language before diving into a complete frontend framework, IMHO, the same way you don't become a race driver if you've never driven a car before.

Apart from that, the "quality of issue reporting" here is pretty low. Blanket statements that everything is "horrible" aren't actionable.

**Comment by gkalpak** [comment] 2019-07-15 11:29
As @Airblader said, this report is unfortunately not actionable.

FWIW, we have a couple of fixes related to "line-numbering in code snippets" in the works: #31493, #31494 
Also, most code snippets are extracted from actual, running mini-apps (with tests to ensure they keep working as intended) and most guides provide links to the corresponding full example app (both as an online StackBlitz project and as a downloadable ZIP archive). This does not apply to _all_ guides and/or code snippets, but I certainly hope we get there one day 😄 

In general, we know the documentation is not perfect and we are constantly working on improving things (both the content and the infrastructure/tooling). We welcome all kinds of contributions (including reporting specific actionable issues) and are more than happy to guide and coordinate with people that want to contibute an actual fix or improvement.

##
I am going to close this, since (as mentioned above) it is not actionable in its current form, but we would be happy to look into specific issues and/or help anyone that wants to work on improving the docs in any way.

**Closed by gkalpak** 2019-07-15 11:29 UTC
