### ISSUE TITLE
Function calls are not supported in decorators but 'makePropDecorator' was called.

### ISSUE THREAD

**Issue by Gajendrasinh** [angular/angular#30989] opened 2019-06-12 02:32 UTC
Hello

Recently i have migrate from 7 to 8,

I am getting below error when running ng build --pord 

ERROR in Error during template compile of 'Input'
  Function calls are not supported in decorators but 'makePropDecorator' was called.

Error during template compile of 'Injectable'
  Function calls are not supported in decorators but 'makeDecorator' was called.

Error during template compile of 'Injectable'
  Function calls are not supported in decorators but 'makeDecorator' was called.

Can you help to how i can i fix this.

Thank you.

**Comment by Splaktar** [comment] 2019-06-12 09:25
This seems like a duplicate of https://github.com/angular/angular/issues/30988 and it doesn't follow the issue template. Please revise or close this and open an issue that follows the template and provides a reproduction via StackBlitz or GitHub.

**Closed** 2019-06-12 20:37 UTC
