### ISSUE TITLE
OnPush triggers the ngAfterViewChecked when component Input does not change

### ISSUE THREAD

**Issue by ArielGueta** [angular/angular#12859] opened 2016-11-14 11:59 UTC
**Current behavior**
According to Victor Savkin [article](https://vsavkin.com/immutability-vs-encapsulation-90549ab74487#.jt71oqqbv) when using the OnPush strategy if the component Input does not change, there is no need to check the component’s template. But in my example when I am clicking on the trigger button and the Input does not change the _ngAfterViewChecked_ hook still running.

**Expected behavior**
The _ngAfterViewChecked_ in the component should not run.

**Minimal reproduction of the problem with instructions**
This is a working [plunker](https://plnkr.co/edit/GnKMfAxMl65ttBQVIeSj?p=preview).

**Comment by DzmitryShylovich** [comment] 2016-11-14 12:13
Duplicate of https://github.com/angular/angular/issues/7055

**Comment by ArielGueta** [comment] 2016-11-14 12:15
It's seems like there is no progress on this issue.

**Comment by chuckjaz** [comment] 2016-11-16 02:21
Thanks for reporting this issue. However this issue is a duplicate of an existing issue #7055. Please subscribe to that issue for future updates.

**Closed by chuckjaz** 2016-11-16 02:21 UTC
