### ISSUE TITLE
TypeError: Cannot read property '_rawValidators' of null after Ng build

### ISSUE THREAD

**Issue by vikas-nexcom** [angular/angular#43320] opened 2021-09-02 13:29 UTC
I am new to angular. I am dynamically rendering some fields into my reactive form. Everything works great when I am using ng serve with a mock request (i.e. rendering happens properly, no error in the console.log). As soon as I build the project with ng build and use a proper backend, I get the error for each field I am rendering dynamically:

> main.js:1 ERROR TypeError: Cannot read property '_rawValidators' of null 

I couldn't find any background on this error. I would love to hear your thoughts.

### more background

```
// these fields change with selection
this.datafields = [{
              dfId: 48,
              dfName: "Phone",
              dfType: "text",
              dfOptions: null,
              dfValue: ""
              },
              {
              dfId: 49,
              dfName: "Eval",
              dfType: "select",
              dfOptions: ["","Remote","Live"],
              df_value: "",
              }]
```

typescript rendering in `ngOnInit` (tried `ngAfterViewInit` with no improvement)

```
dfGroup = new FormGroup({})
...
...

 this.eyeForm = this.formBuilder.group({
      focus: ['', Validators.required],
 datafields: this.formBuilder.array([])
})

...
...

  if (this.datafields != null || this.datafields != undefined) {
  this.datafields.forEach((x:any) => {
          this.dfGroup.setControl(x.dfName, new FormControl(x.dfValue));
        });
  this.getDataFields.push(this.dfGroup);
  }
```
HTML:

```
<div [formGroup]="dfGroup">
   <div class="row pt-2" *ngFor="let field of datafields; let i=index">
      <div class="col-4 d-flex align-items-center 13required">
         {{field.dfName}}&nbsp;
      </div>
      <div class="col-6">
         <mat-form-field *ngIf="field.dfType == 'text'" appearance="outline">
            <input
            matInput
            [type]="field.dfType"
            [formControlName]="field.dfName"
            required
            />
         </mat-form-field>
         <mat-form-field
            *ngIf="field.dfType == 'select'"
            appearance="outline"
            >
            <mat-select [formControlName]="field.dfName" placeholder="">
               <mat-option
               [value]="option"
               *ngFor="let option of field.dfOptions"
               >
               {{ option }}
               </mat-option>
            </mat-select>
         </mat-form-field>
      </div>
   </div>
</div>
```

**Comment by atscott** [comment] 2021-09-02 16:31
@vikas-nexcom are you able to provide a github repo that we can use to reproduce this error?

**Comment by vikas-nexcom** [comment] 2021-09-02 16:58
@atscott unfortunately not, because this is the build output links with a bigger private python project I have. Also, I am not able to reproduce this with `ng serve`. After some digging, I am guessing the problem is with `addControl`

```
  if (this.datafields != null || this.datafields != undefined) {
          this.datafields.forEach((x:any) => {
          this.dfGroup.addControl(x.dfName, new FormControl(''));
        });
  this.getDataFields.push(this.dfGroup);
  }
```
**Can you perhaps provide me a direction to look into? If there is anything that looks suspicious and causes this issue.** Maybe the backend is the issue.

**Comment by atscott** [comment] 2021-09-02 17:08
@vikas-nexcom Without a reproduction, I don't know if there's much we can do. I'll let someone more familiar with forms (@dylhunn, @AndrewKushnir) take a look but it's likely they won't be able to help without a way to reproduce it locally.

**Comment by AndrewKushnir** [comment] 2021-09-02 17:41
@vikas-nexcom as @atscott mentioned above, there is not a lot we can do without a repro. One thing that I'd like to propose is to try different versions of  the `@angular/forms` package, for ex. start with major and minor versions such as 12.0.0, 12.1.0, 12.2.0 and see if the error is not present in older versions. If that's the case - try to use patch versions (for ex. 12.1.1, 12.1.2, etc) and see which exact release caused the problem. Having an exact version would help us to examine a range of commits in that release and see if there is anything that might trigger that issue.

**Comment by alan-agius4** [comment] 2022-01-29 08:42
Closing since no reproduction was provided. Please feel free to open a new issue with a reproduction if the problem persists.

**Closed by alan-agius4** 2022-01-29 08:42 UTC
Labels: needs reproduction, comp: forms
