### ISSUE TITLE
Factory provider type does not respect OnDestroy hook

### ISSUE THREAD

**Issue by tmair** [angular/angular#22240] opened 2018-02-15 17:51 UTC
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
If we provide a service with a `ngOnDestroy` method as a type provider the service's `ngOnDestroy` lifecycle hook is called. If however the same service is provided via a factory function, the `ngOnDestroy` lifecycle hook is never called.

## Expected behavior
The behavior should not differ if using a type provider or a factory provider.

## Minimal reproduction of the problem with instructions
Simple Demo: https://stackblitz.com/edit/angular-3azkmn

If you comment in the type provider, the `ngOnDestroy` hook is called (console.log is performed).
If you use the factory provider the `ngOnDestroy` hook is not called

## What is the motivation / use case for changing the behavior?
I have tried to destroy an angular application manually (by calling the NgModuleRef.destroy method) that contains an angular router. After the appliction is destroyed the routing events still fire. The cause for this is that the `ngOnDestroy` hook is never called. Further this leads to a memory leak, as the application is not garbage collected.

Other issues might be that someone changes the provider type and is not aware of this limitation. Thus introducing subtle bugs into the appliction.

## Solution
I do not exactly know where to look for a fix, but the `nodeDef.flags` do not contain the `OnDestroy` bit. So the cause of this bug is probably somwhere in the compiler, which I am not too familiar with.

## Environment

<pre><code>
Angular version: ^5.2.0

Browser:
- [x] Chrome (desktop) version XX
- [x] Chrome (Android) version XX
- [x] Chrome (iOS) version XX
- [x] Firefox version XX
- [x] Safari (desktop) version XX
- [x] Safari (iOS) version XX
- [x] IE version XX
- [x] Edge version XX
</code></pre>

**Comment by vicb** [comment] 2018-02-15 18:11
For now this works as intended as we check the presence of `OnDestroy` at compile time.

**Comment by tmair** [comment] 2018-02-15 19:11
@vicb What about the issue with the router? The router class implements the `OnDestroy` interface but because it is provided via a factory the destroy hook is never called. Should I file a separate issue for that?

**Comment by trotyl** [comment] 2018-02-18 04:44
Duplicate of #14818. Better to file a separate issue for router memory leak problem.

**Closed** 2018-05-08 20:56 UTC
Labels: comp: core & compiler, type: feature

**Comment by simeyla** [comment] 2019-08-29 02:11
@vicb this also doesn't work with an InjectionToken which surprised me very much. Surely that can be figured out at compile time?

        {
            provide: PAYMENTPANEL_SERVICE,
            useClass: ShopPaymentPanelService
        }   

`ngOnDestroy` is never called on the above - despite using `useClass`
