### ISSUE TITLE
Paths are not properly resolved for util libraries for e2e test execution

### ISSUE THREAD

**Issue by tomii8** [angular/angular#44656] opened 2022-01-07 09:26 UTC
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

After uprade from Angular 12 to 13 I'm facing a problems with loading utils angular library while e2e tests are executed. Even my configuration hasn't change for webdriverio.
I'm using webdriverio with jasmine-framework 
Looks like paths are not properly resolved. This part of configuration in tsconfig is not changed.

### Please provide the exception or error you saw

```true
[0-0] Error: Cannot find module '@sensors/shared-ng/e2e'
[0-0] Require stack:
[0-0] - D:\GUI-Projects\sensors-ng\projects\shared\e2e-tests\expert-mode.e2e.ts
[0-0] - D:\GUI-Projects\sensors-ng\node_modules\jasmine\lib\loader.js
[0-0] - D:\GUI-Projects\sensors-ng\node_modules\jasmine\lib\jasmine.js
[0-0] - D:\GUI-Projects\sensors-ng\node_modules\@wdio\jasmine-framework\build\index.js
[0-0] - D:\GUI-Projects\sensors-ng\node_modules\@wdio\utils\build\utils.js
[0-0] - D:\GUI-Projects\sensors-ng\node_modules\@wdio\utils\build\initialisePlugin.js
[0-0] - D:\GUI-Projects\sensors-ng\node_modules\@wdio\utils\build\index.js
[0-0] - D:\GUI-Projects\sensors-ng\node_modules\@wdio\runner\build\index.js
[0-0] - D:\GUI-Projects\sensors-ng\node_modules\@wdio\local-runner\build\run.js
[0-0]     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
[0-0]     at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue (D:\GUI-Projects\sensors-ng\node_modules\@cspotcode\source-map-support\source-map-support.js:679:30)
[0-0]     at Function.Module._resolveFilename (D:\GUI-Projects\sensors-ng\node_modules\tsconfig-paths\lib\register.js:75:40)
[0-0]     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
[0-0]     at Module.require (node:internal/modules/cjs/loader:1005:19)
[0-0]     at require (node:internal/modules/cjs/helpers:102:18)
[0-0]     at Object.<anonymous> (D:\GUI-Projects\sensors-ng\projects\shared\e2e-tests\expert-mode.e2e.ts:5:1)
[0-0]     at Module._compile (node:internal/modules/cjs/loader:1101:14)
[0-0]     at Module.m._compile (D:\GUI-Projects\sensors-ng\node_modules\ts-node\src\index.ts:1371:23)
[0-0]     at Module.m._compile (D:\GUI-Projects\sensors-ng\node_modules\ts-node\src\index.ts:1371:23) {
[0-0]   code: 'MODULE_NOT_FOUND',
[0-0]   requireStack: [
[0-0]     'D:\\GUI-Projects\\sensors-ng\\projects\\shared\\e2e-tests\\expert-mode.e2e.ts',
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.1.2
Node: 16
Package Manager: yarn 
OS: Windows 10

Angular: 13.1.1
Typescript: 4.4.4

Package.json devDependencies:
"devDependencies": {
    "@angular-devkit/build-angular": "~13.1.2",
    "@angular-eslint/builder": "^13.0.1",
    "@angular-eslint/eslint-plugin": "^13.0.1",
    "@angular-eslint/eslint-plugin-template": "^13.0.1",
    "@angular-eslint/schematics": "~13.0.1",
    "@angular-eslint/template-parser": "^13.0.1",
    "@angular/cli": "~13.1.2",
    "@angular/compiler": "~13.1.1",
    "@angular/compiler-cli": "~13.1.1",
    "@angular/core": "~13.1.1",
    "@babel/polyfill": "~7.12.1",
    "@compodoc/compodoc": "~1.1.15",
    "@migalons/angular-wdio-builder": "~1.0.2",
    "@types/jasmine": "~3.10.2",
    "@types/node": "~14.14.6",
    "@wdio/types": "~7.16.11",
    "@wdio/cli": "~7.16.12",
    "@wdio/jasmine-framework": "~7.16.11",
    "@wdio/local-runner": "~7.16.12",
    "@wdio/spec-reporter": "~7.16.11",
    "@wdio/static-server-service": "~7.16.11",
    "assert": "~2.0.0",
    "chromedriver": "~86.0.0",
    "commander": "~6.1.0",
    "concurrently": "~5.3.0",
    "copyfiles": "~2.1.1",
    "deepmerge": "~4.2.1",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^4.0.0",
    "jasmine-marbles": "~0.9.1",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~6.3.9",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "^2.1.0",
    "karma-firefox-launcher": "~2.1.2",
    "karma-jasmine": "~4.0.1",
    "karma-jasmine-html-reporter": "~1.7.0",
    "ng-packagr": "~13.1.2",
    "node-gyp": "8.2.0",
    "path-browserify": "~1.0.1",
    "prettier": "2.4.1",
    "rxjs": "~7.4.0",
    "ts-node": "~10.4.0",
    "tsconfig-paths": "~3.12.0",
    "typescript": "~4.4.4",
    "util": "~0.12.4",
    "watch": "~1.0.2",
    "wdio-chromedriver-service": "7.2.2",
    "webdriverio": "~7.16.12",
    "webpack-bundle-analyzer": "~4.5.0",
    "zone.js": "~0.11.4"
  }
```

### Anything else?

Webdriver configuration:

...
require('ts-node').register({
  transpileOnly: true,
  compilerOptions: {
    target: "ES2020",
    module: "commonjs",
    moduleResolution: "node",
    sourceMap: true
  },
});
...

require('tsconfig-paths').register({
  baseUrl: './',
  paths: {
'@sensors/shared-ng': [
      'dist/shared'
    ],
    '@sensors/shared-ng/e2e': [
      'dist/shared/e2e'
    ],
    '@sensors/device-elements-ng/e2e': [
      'dist/device-elements/e2e'
    ],
  },
});

**Comment by JoostK** [comment] 2022-01-07 13:34
I'm not sure how Angular is involved in this, but we won't be able to help you out without a reproduction.

**Comment by alan-agius4** [comment] 2022-01-29 08:41
Closing since no reproduction was provided. 

Please feel free to open a new issue with a reproduction if the problem persists.

**Closed by alan-agius4** 2022-01-29 08:41 UTC
Labels: comp: testing, needs reproduction
