### ISSUE TITLE
creating child module inside child module 

### ISSUE THREAD

**Issue by nikhilnayyar002** [angular/angular#31605] opened 2019-07-17 12:07 UTC
* at the top we have a app.module 
  with router-outlet and used forRoot method
** then inside above module i include dashboard.module 
    with router-outlet and used forChild method
*** then inside above module i include category.module 
      with router-outlet and used forChild method

so,
* if i want to route to root:  ' '
* if i want to route to dashboard:  ' ' + '/dashboard'
* if i want to route to category:  ' ' + '/dashboard' + '/category'

But the last one do not seem to work actually, what seem to work is:

* if i want to route to category:  ' '  + '/category'

I think it is due to the forChild() method being used.

Second thing is if above issue is resolved
can I make router-outlet in category module to work independent of other two outlets?

**Comment by atiris** [comment] 2019-07-17 15:14
Hi, what you demand normally works. Please try to follow [this page](<https://angular.io/guide/router>) and if you can't set up the router correctly, create a sample using [StackBlitz](<https://stackblitz.com/fork/angular>) with code what you tried, someone will advise you.  

However, since it is not a bug, I recommend ask this on StackOverflow and close this bug request.  
Check for example this question: [Angular multilevel child routing](<https://stackoverflow.com/questions/54308142/angular-multilevel-child-routing>)

**Comment by nikhilnayyar002** [comment] 2019-07-17 15:25
Hey thanks,

I think loadChildren would work. Ok i will close the issue.

**Comment by nikhilnayyar002** [comment] 2019-07-17 15:27
i will try and i know it would work.

**Closed** 2019-07-17 15:26 UTC
