### ISSUE TITLE
"Please upgrade service worker" error while my SW package is @5.0.0

### ISSUE THREAD

**Issue by alcfeoh** [angular/angular#20134] opened 2017-11-03 05:28 UTC
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Trying to use service worker@5.0.0. When I run a production build in a multiple-app project (`ng build --prod --app 1`) I'm getting the following error message:

```
The installed version of @angular/service-worker is 5.0.0. This version of the CLI
requires the @angular/service-worker version to satisfy >= 1.0.0-beta.5 < 2.0.0. Please upgrade
your service worker version.
```

## Expected behavior
I'm using CLI@1.5.0 and all of the Angular packages @5.0.0 so the failure message does not make sense.

## Minimal reproduction of the problem with instructions
In a project with two CLI apps defined in the same `.angular-cli.json`, the following package.json dependencies lead to the issue mentioned above:
```
  "dependencies": {
    "@angular/animations": "^5.0.0",
    "@angular/common": "^5.0.0",
    "@angular/compiler": "^5.0.0",
    "@angular/core": "^5.0.0",
    "@angular/forms": "^5.0.0",
    "@angular/http": "^5.0.0",
    "@angular/platform-browser": "^5.0.0",
    "@angular/platform-browser-dynamic": "^5.0.0",
    "@angular/router": "^5.0.0",
    "@types/hammerjs": "^2.0.35",
    "bootstrap": "^3.3.7",
    "core-js": "^2.4.1",
    "hammerjs": "^2.0.8",
    "jquery": "^3.2.1",
    "jquery-scrollify": "^1.0.17",
    "ng2-pdf-viewer": "^2.0.3",
    "pdfjs-dist": "^1.9.640",
    "rxjs": "^5.5",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "@angular/cli": "^1.5.0",
    "@angular/compiler-cli": "^5.0.0",
    "@angular/language-service": "^5.0.0",
    "@angular/service-worker": "^5.0.0",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/jquery": "^3.2.15",
    "@types/node": "~6.0.60",
    "codelyzer": "4.0.0",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.2.0",
    "tslint": "~5.3.2",
    "typescript": "~2.4"
  }
```

## What is the motivation / use case for changing the behavior?
This should be working as all versions are as expected.

## Environment

<pre><code>
Angular version: 5.0.0

Browser:
- [] Chrome (desktop) version 62
- [ ] Chrome (Android) version XX
- [X] Chrome (iOS) version  62
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 6.11.2
- Platform:  Mac

Others:
N/A
</code></pre>

**Comment by trotyl** [comment] 2017-11-03 05:42
Duplicate of https://github.com/angular/angular-cli/issues/8322

**Closed** 2017-11-03 09:40 UTC
