### ISSUE TITLE
Standalone components are nearly impossible to shallow test

### ISSUE THREAD

**Issue by yjaaidi** [angular/angular#46110] opened 2022-05-23 16:39 UTC
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

# Why Shallow

Before standalone components, it was possible to shallow test components meaning testing a component without loading all of its children (though, we can really exceptionally load some of them).
This is interesting for multiple reasons:
- isolation and reduction of System Under Test's size
- TDD: testing a component based on child components that are not implemented yet (but where the contract is already defined, i.e. inputs/outputs)
- optimizing test performance as we don't have to load children, grand-children, dependencies etc....

# How to Shallow

## Usual form of Shallow

To achieve shallow testing, one could create the component this way:
```ts
  TestBed.configureTestingModule({
    declarations: [AppComponent],
    schemas: [CUSTOM_ELEMENTS_SCHEMA], // or NO_ERROR_SCHEMA when using directives
  });

  const fixture = TestBed.createComponent(AppComponent);
```

## Rare form of Shallow

or also this rare form:
```ts
  TestBed.configureTestingModule({
    declarations: [AppComponent, ChildAComponent],
    schemas: [CUSTOM_ELEMENTS_SCHEMA], // or NO_ERROR_SCHEMA when using directives
  });

  const fixture = TestBed.createComponent(AppComponent);
```
where we are also loading the child `ChildAComponent` but not `ChildBComponent` or `ChildAComponent`'s children. This is a really rare use case where we are enlarging the size of the System Under Test a bit.
I am covering this here because if we find a solution for this issue, it has to be compatible with this second use case too. Even though it should be super rare.

# The Problem

The issue with Standalone Components is that we can't do this anymore because declaring the component in the test bed's module, doesn't work producing the following error:

### Please provide a link to a minimal reproduction of the bug

https://github.com/yjaaidi/ng-experiments/blob/angular-standalone-shallow-testing-issue/src/app/app.component.spec.ts

### Please provide the exception or error you saw

```true
Error: Unexpected "AppComponent" declaration in "DynamicTestModule" NgModule. "AppComponent" is marked as standalone and can't be declared in any NgModule - did you intend to import it?
            at verifySemanticsOfNgModuleDef (node_modules/@angular/core/fesm2020/core.mjs:24462:15)
            at Function.get (node_modules/@angular/core/fesm2020/core.mjs:24388:21)
            at R3TestBedCompiler.applyProviderOverridesToModule (node_modules/@angular/core/fesm2020/testing.mjs:1084:39)
            at R3TestBedCompiler.compileTestModule (node_modules/@angular/core/fesm2020/testing.mjs:1351:14)
            at R3TestBedCompiler.finalize (node_modules/@angular/core/fesm2020/testing.mjs:935:14)
            at TestBedRender3.testModuleRef (node_modules/@angular/core/fesm2020/testing.mjs:1858:49)
            at TestBedRender3.inject (node_modules/@angular/core/fesm2020/testing.mjs:1781:29)
            at TestBedRender3.createComponent (node_modules/@angular/core/fesm2020/testing.mjs:1821:44)
            at Function.createComponent (node_modules/@angular/core/fesm2020/testing.mjs:1660:37)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 14.0.0-rc.1
Node: 16.14.0
Package Manager: yarn 1.22.11 
OS: darwin x64

Angular: 14.0.0-rc.1
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1400.0-rc.1
@angular-devkit/build-angular   14.0.0-rc.1
@angular-devkit/core            14.0.0-rc.1
@angular-devkit/schematics      14.0.0-rc.1
@schematics/angular             14.0.0-rc.1
rxjs                            7.5.5
typescript                      4.6.4
```

### Anything else?

The main alternative I can quickly think of is some internal option that allows module to declare a standalone component in a module.

This internal option should be set by `TestBed.configureTestingModule()`:
1. by default but this will not signal invalid declarations of standalone components for users who meant importing the standalone component.
2. behind an explicit option `TestBed.configureTestingModule({allowStandaloneDeclaration: true})`
DX wouldn't be great but can easily wrapped by commonly use shallow testing functions or libraries.

**Comment by pkozlowski-opensource** [comment] 2022-05-23 18:34
I don't think we want to ever allow standalone declarations in `NgModule` - the whole point is to make them NgModule independent. So the suggested way of going about it is not something we want to implement.

Re-focusing on the problem I would express it like follows: assuming the following component under test:

```typescript

@Component({
   standalone: true
})
export class MyComponent {
}

```

**Comment by pkozlowski-opensource** [comment] 2022-05-23 18:42
Without trying to provide the full design here I would assume that the API would be similar to the one we've got for overrides.  Actually, wouldn't the existing `TestBed.overrideComponent` work?

```typescript
TestBed.overrideComponent(MyComponent, {set: {
    imports: [],
    schemas: [CUSTOM_ELEMENTS_SCHEMA]
}});
``` 

We will revisit TestBed APIs post v14 but yeh, no declarations for standalones, not even in TestBed :-)

**Comment by yjaaidi** [comment] 2022-05-24 08:47
Thanks @pkozlowski-opensource! Oh yeah `TestBed.overrideComponent` of course 🤦🏻‍♂️!
It works great but this has a large impact on docs and other resources in addition to the fact that `overrideComponent`'s API is not very intuitive for new comers.
e.g.:
- https://angular.io/guide/testing-components-scenarios#use-both-techniques-together
- https://vsavkin.com/three-ways-to-test-angular-2-components-dcea8e90bd8d#:~:text=Now%20let%E2%80%99s%20look%20at%20the%20test 

I know that this is too late for providing a quick alternative, but what about an additional parameter for convenience.
```ts
createComponent<T>(component: Type<T>, metadata?: Partial<Component>): ComponentFixture<T>;
```

This wouldn't cover the rare case of`remove` and `add` (I can't see any real life example for the last one 🤔) but users can still use `overrideComponent` in that case.

**Comment by alxhub** [comment] 2022-08-11 23:26
@AndrewKushnir and I did a dive into `TestBed` and the standalone experience recently. Our conclusions were:

* `TestBed` in general needs an API overhaul - many of its concepts (like metadata overrides) made sense in the View Engine era but with Ivy we can do better.
* Testing of standalone components works today, with `overrideComponent` as an option for overriding `imports` and shallow-testing if desired.
* We don't want to create new APIs for standalone based on the old View Engine model of `TestBed`, when we know we're going to do a more serious overhaul to testing in the near future.

So given that decision, I think we can close this as "working as intended" for now.

**Closed by alxhub** 2022-08-11 23:26 UTC
Labels: comp: testing, cross-cutting: standalone
