### ISSUE TITLE
Animating on height and setting height on start callback

### ISSUE THREAD

**Issue by jwa107** [angular/angular#13160] opened 2016-11-30 16:17 UTC
**I'm submitting a ...**
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ? ] feature request
```

**Current behavior**
Currently, setting a height on an animated area (when animating height) on the start callback doesn't seem to take effect. The height doesn't get applied until the done callback, 
I'm not 100% sure if this is a bug/design flaw or intended (with a more appropriate workaround), but it seems like it's not behaving right.

Also, for extra clarification ("Why don't you just set the height to 400px in the animation?") I want the height to be more dynamic. I want the dev to be able to pass in a height, but otherwise just use the auto height ('*')

**Expected behavior**
The height should be set on start.

**Minimal reproduction of the problem with instructions**
Here is a plunkr, just click the button to see the animation -- note how it jumps after it finishes. This doesn't appear to animate in Edge, so use Chrome to be sure.

http://plnkr.co/edit/Etn2qTZ7APZBXmf4Ws5H?p=preview&open=app%2Fapp.component.ts

**What is the motivation / use case for changing the behavior?**
Motivation is having more control over the element being animated.

* **Angular version:** 2.0.1

* **Browser:** Chrome

**Comment by matsko** [comment] 2017-12-07 23:44
Hey @jwa107 I'm sorry it took forever to get to this issue. Things have changed in Angular, and perhaps the issue isn't relevant anymore. If you can produce an up to date demo with Angular5 then I will be happy to help out. Closing for now.

**Closed by matsko** 2017-12-07 23:44 UTC
Labels: comp: animations
