### ISSUE TITLE
npm install failing on new checkouts

### ISSUE THREAD

**Issue by dl748** [angular/angular#8541] opened 2016-05-08 22:37 UTC
`npm install` is failing on a change done on May 1st is causing all fresh/clean checkouts to fail

Reproduced by

First Bad (you can also use master(as of 9f784dcc5a524000836c5e4cd7b3384e21963637)) check in that appeared in history (note you will never see this error if you already have build from a previous version)

<pre>rm -rf node_modules;
git checkout a66cdb469f56f8ebab2e5f2e44d59b53effd0489;
npm install</pre>

it stops with the message <pre>&lt; angular-srcs@2.0.0-beta.17 preinstall angular
&lt; node tools/npm/check-node-modules

:-( npm dependencies are stale or in an in unknown state!
</pre>

Last Good npm install

<pre>rm -rf node_modules
git checkout 4fe0f1fa655717fd49045dedaebc8b1100f11238
npm install</pre>

produces at the same lines

<pre>&lt; angular-srcs@2.0.0-beta.17 preinstall angular
&lt; node tools/analytics/build-analytics start install npm3-install && node tools/analytics/build-analytics start install npm-preinstall && node tools/npm/check-node-modules && node tools/analytics/build-analytics success install npm-preinstall && node tools/analytics/build-analytics start install npm-install-net

:-( npm dependencies are stale or in an in unknown state!
</pre>
(so tools/analytics/build-analytics is never fired) which makes sense as someone was working with repackaging and must of buggered it up

a66cdb469f56f8ebab2e5f2e44d59b53effd0489: "repackaging: all the repackaging changes squashed"

**Comment by dl748** [comment] 2016-05-08 22:48
Steps I run to get a new build
<pre>
git clone https://github.com/angular/angular.git
cd angular
git checkout 505da6c0a8a852898475410918f06cce15d5b1e2
npm install
git checkout
npm update
node $(npm bin)/gulp build.tools
</pre>

Otherwise, the "build.tools" step will always fail.

**Comment by jonathan-casarrubias** [comment] 2016-05-09 17:43
thanks @dl748 that made it for me

**Comment by digioak** [comment] 2016-05-11 02:47
+1 @dl748

**Comment by choeller** [comment] 2016-05-12 11:57
thanks @dl748 for the workaround - the tools build is working for me now, but running

`node --max_old_space_size=4000 ./node_modules/.bin/gulp build.js`

```
[13:54:14] '!build.js.cjs' errored after 379 ms
[13:54:14] Error: ENOENT: no such file or directory, lstat '/home/christoph/sources/angular_old/tmp/funnel-input_base_path-OlWUSYK7.tmp/0/angular2/manual_typings/globals.d.ts'
    at Error (native)
    at Object.fs.lstatSync (fs.js:887:18)
    at symlink (/home/christoph/sources/angular_old/node_modules/symlink-or-copy/index.js:60:26)
    at Function.symlinkOrCopySync [as sync] (/home/christoph/sources/angular_old/node_modules/symlink-or-copy/index.js:55:5)
    at Funnel._copy (/home/christoph/sources/angular_old/node_modules/broccoli-funnel/index.js:398:19)
    at Funnel.processFile (/home/christoph/sources/angular_old/node_modules/broccoli-funnel/index.js:381:8)
    at Funnel.applyPatch [as _applyPatch] (/home/christoph/sources/angular_old/node_modules/broccoli-funnel/index.js:298:12)
    at Funnel.<anonymous> (/home/christoph/sources/angular_old/node_modules/broccoli-funnel/index.js:250:10)
    at Array.forEach (native)
    at Funnel.processFilters (/home/christoph/sources/angular_old/node_modules/broccoli-funnel/index.js:249:9)
```

Is anyone else experiencing this error? I tried with node 4, 5 and 6...

**Comment by pkozlowski-opensource** [comment] 2016-05-13 00:06
There is a PR that fixes it: https://github.com/angular/angular/pull/8627. Closing as duplicate of #8627

**Closed by pkozlowski-opensource** 2016-05-13 00:06 UTC

**Comment by dl748** [comment] 2016-05-13 01:26
checked out the latest master, npm install is STILL failing at the exact same point.  This not a duplicate then.  I have to check out to the SAME point in order to npm install.

**Comment by gonzofish** [comment] 2016-05-13 01:43
@dl748 did you checkout that branch?

**Comment by dl748** [comment] 2016-05-13 02:01
Gotcha... i checked out master... it failed

**Comment by choeller** [comment] 2016-05-13 07:39
@pkozlowski-opensource I pulled your commit into my project and npm install now works. Sadly the build still crashes with the message above. I really tried all available node versions (4,5,6) and deleted node_modules and tmp folder. Do you have an idea whats going on there? Should I open a new issue for that?
