### ISSUE TITLE
Components with non-empty HTML input field not released in memory

### ISSUE THREAD

**Issue by capc0** [angular/angular#37952] opened 2020-07-07 07:17 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/core or forms?

### Is this a regression?

 unsure

### Description

 If I have an app with 2 pages and routing between them, the components on each page would normally be destroyed when routing between the pages. If a page has an input with [(ngModel)] binding however, the page/component will still call ngOnDestroy but will not be released from memory (see chrome dev tools)

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-b5sb94

Enter something in the input field -> route to page 2 -> route back -> Page1Component will be 2x in the memory

![image](https://user-images.githubusercontent.com/27284008/86734721-80cc6c80-c032-11ea-8dcd-ebb1ccf0d02a.png)

## 🔥 Exception or Error

n/a

## 🌍  Your Environment

**Angular Version:**
<pre><code>
10
</code></pre>

**Anything else relevant?**
n/a

**Comment by pkozlowski-opensource** [comment] 2020-07-07 13:07
@capc0 thnx for reporting, this is a valid issue! In fact, there are 2 separate issues here:
* dev mode only, already tracked in #35164 
* the issue you've mentioned, specific to the interaction with an input field.

What is interesting here is that `ShadowRoot` shows up as one of the retainers - since none of the components in your app is using shadow DOM encapsulation I would expect that this is the native input's implementation that acts funky here. Still, it is not clear to me if this is a bug in a browser or something specific that we do in the framework.

In any case this is a valid bug report and it needs more investigation to diagnose the root cause.

**Comment by capc0** [comment] 2020-07-13 05:55
Actually the model binding is not the cause.

Any HTML input field with a value is enough for the memory leak.

New minimal reproduction: https://stackblitz.com/edit/angular-y7wbvv

**Comment by beniaminp** [comment] 2020-07-21 12:51
Hi! we also have this problem. We noticed the same problem also with HtmlTextArea. It is a huge problem for us because after about an hour our application almost freeze and we cannot deliver to our clients a new release.
What we noticed is that if any HTML input field is completed, the angular component that holds the input is never destroyed resulting a big junk. We did our tests with production mode on. It is reproducing also on angular 9.x.
I also think that this should be a very high priority issue.

Thanks!

**Comment by capc0** [comment] 2020-08-04 12:38
seems to be related to ivy. with ```enableIvy``` set to ```false``` the components are destroyed normally

**Comment by rekna1** [comment] 2020-08-19 08:13
For me it's not related to input elements : I encountered the problem when I was testing the behaviour of providers property of a component decorator to provide service only to component and its children. When I navigate away from this component, and take a memory snapshot, the component and service are still in memory. (even though I see ngDestroy is called on both service and component).

When navigating several times to and away from this component, only one instance of the component and one instance of the service remains in memory (the last activated component and its service). But still if this services would hold large amounts of data it would be a huge memory leak. 

In my test the component and service don't contain anything (e.g. no observables or other references)

**Comment by nartc** [comment] 2020-09-19 16:16
I believe I just ran into this same issue. Here's the sample repro: https://github.com/nartc/demo-angular-memory-profile

There are two cases (screenshots) that demonstrate this memory issue:

![image](https://user-images.githubusercontent.com/25516557/93671531-6585d080-fa69-11ea-92be-2b32a79f2e8d.png)
![image](https://user-images.githubusercontent.com/25516557/93671533-69b1ee00-fa69-11ea-84d2-b597c68b4154.png)

- The currentPage input was initially a `[(ngModel)]` then I changed to `[value]` and `(input)` just to see if there's any difference. No difference at all. 
- `ngOnDestroy` in ListItemComponent is being called correctly for each item.

Not sure if this is entirely related because the memory issue does not exist if the input isn't used at all.

**Comment by jelbourn** [comment] 2020-10-12 22:14
Duplicate of #20007

**Closed by jelbourn** 2020-10-12 22:14 UTC
Labels: P3, comp: core, freq2: medium, memory leak, state: needs more investigation, type: bug/fix

**Comment by beniaminp** [comment] 2020-10-13 05:28
@jelbourn, it does not look like a duplicate for me. I do not need to use a FormControlName to reproduce the memory leak.
There is no resolution for this bug yet?
Thanks!

**Comment by jelbourn** [comment] 2020-10-28 17:42
I marked as a duplicate because we believe it's the same underlying cause
