### ISSUE TITLE
document.referrer not updating on route change

### ISSUE THREAD

**Issue by mcalmus** [angular/angular#39945] opened 2020-12-03 11:46 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....
@angular/route

### Description

 A clear and concise description of the problem...
Changing to a new route does not update document.referrer. This makes it difficult to distinguish between an external direct link and an internal link.

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-ivy-s55fln

## 🌍  Your Environment

**Angular Version:**
<pre>Angular 11<code>

</code></pre>

**Anything else relevant?**

**Comment by atscott** [comment] 2020-12-08 02:04
Likely a duplicate of #38234

**Closed by atscott** 2020-12-08 02:04 UTC
Labels: comp: router
