### ISSUE TITLE
Ivy error TS-996002, when using compiled esm5 files

### ISSUE THREAD

**Issue by dioslaska** [angular/angular#32442] opened 2019-09-02 08:39 UTC
# 🐞 bug report

### Affected Package

The issue is caused by package @angular/cli

### Is this a regression?

It only happens when Ivy is enabled - ngcc. With stable ngc AOT build it works fine.

### Description

The error occurs when running the `ng build` command, if the source code imports a module and component from a compiled esm5 file, which has the associated `d.ts` and `metadata.json` files.

## 🔬 Minimal Reproduction

Can be found here: https://github.com/acidb/mobiscroll-ivy-test
Running `ng build` throws the mentioned error.

## 🔥 Exception or Error
<pre><code>
ERROR in src/mobiscroll/src/js/input.angular.d.ts:3:22 - error TS-996002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class

3 export declare class MbscInputModule {
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.0.0-next.0
Node: 12.4.0
OS: win32 x64
Angular: 9.0.0-next.3
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-next.0
@angular-devkit/build-angular     0.900.0-next.0
@angular-devkit/build-optimizer   0.900.0-next.0
@angular-devkit/build-webpack     0.900.0-next.0
@angular-devkit/core              9.0.0-next.0
@angular-devkit/schematics        9.0.0-next.0
@angular/cli                      9.0.0-next.0
@ngtools/webpack                  9.0.0-next.0
@schematics/angular               9.0.0-next.0
@schematics/update                0.900.0-next.0
rxjs                              6.5.2
typescript                        3.5.3
webpack                           4.39.2

</code></pre>

**Anything else relevant?**

Found [this issue](https://github.com/angular/angular/issues/30972) with the same error message, which is closed and fixed, but I'm not sure if it's the same cause.

**Comment by rayman1104** [comment] 2019-10-29 13:33
The same issue for Nebular: https://github.com/akveo/nebular/issues/1613
And not working with 8.2.11.

**Comment by dioslaska** [comment] 2019-11-04 09:33
@alxhub @JoostK Any updates on this? I see that 9.0 entered in RC, meaning that our product will stop working as soon as Ivy becomes enabled by default.
Or could you perhaps share some insights on the exact cause of the issue, so if we can change something on our side to make this work.
Unfortunately the error message is not helpful at all.

**Comment by biltongza** [comment] 2019-11-08 11:12
I am able to reproduce this with ng2-pdfjs-viewer. Repro repo here: https://github.com/biltongza/ng2-pdfjs-viewer-ivy-es2015

**Comment by dioslaska** [comment] 2019-11-21 15:50
I figured a few things out

1 - If a compiled esm5 file is referenced from a folder in the src folder, it does not work. I guess this is because `ngcc` only compiles packages inside `node_modules` to make them ivy compatible? We distribute our library as a downloadable package - currently this will only work with ivy if it's packaged using `npm pack` and install it to `node_modules` from the generated file.

2 - `ngcc` will also fail with esm5 file containing minified code. Renaming variables definitely makes it fail. I tried to keep the name of the component classes, which resulted in successful build, but runtime failure.

**Comment by dioslaska** [comment] 2019-11-22 12:50
Here's an example of a filed with variable renames which fails:

Fails:

```
    import { Component as n, NgModule as t } from "@angular/core";
    import { CommonModule as r } from "@angular/common";

    var o = function() {
      function t() {}
      t.decorators = [ {
        type: n,
        args: [ {
          selector: "test-input",
          template: "<label><ng-content></ng-content><input /></label>"
        } ]
      } ];
      return t;
    }();

    var e = function() {
      function n() {}
      n.decorators = [ {
        type: t,
        args: [ {
          imports: [ r ],
          declarations: [ o ],
          exports: [ o ]
        } ]
      } ];
      return n;
    }();

    export { o as TestComponent, e as TestModule };
```

And the original, which works:

```
    import { Component, NgModule } from '@angular/core';
    import { CommonModule } from '@angular/common';

    var TestComponent = /** @class */ (function () {
        function TestComponent() {
        }
        TestComponent.decorators = [
            { type: Component, args: [{
                        selector: 'test-input',
                        template: "<label><ng-content></ng-content><input /></label>"
                    }] }
        ];
        return TestComponent;
    }());

    var TestModule = /** @class */ (function () {
        function TestModule() {
        }
        TestModule.decorators = [
            { type: NgModule, args: [{
                        imports: [CommonModule],
                        declarations: [TestComponent],
                        exports: [TestComponent]
                    },] }
        ];
        return TestModule;
    }());

    export { TestComponent, TestModule };
```

**Comment by dioslaska** [comment] 2019-11-22 15:02
Created a reproduction repo with the minified fesm5 file: https://github.com/acidb/mobiscroll-ivy-test/tree/test

**Comment by petebacondarwin** [comment] 2019-12-12 11:00
Looking into this...

---

By the way, you can also point ngcc at folders other than `node_modules`:

```
-s, --source      A path (relative to the working directory) of the
                    `node_modules` folder to process.[default: "./node_modules"]
```
But it is a bit tricky since your mobiscroll folder does not contain a package.json to describe the entry-points. But it should be possible to overcome that too using an `ngcc.config.js` file.

**Comment by petebacondarwin** [comment] 2019-12-12 11:32
@dioslaska - you'll be glad to hear that after https://github.com/angular/angular/pull/34254 lands your test reproduction will build without error! See https://github.com/acidb/mobiscroll-ivy-test/pull/1/files

**Comment by dioslaska** [comment] 2019-12-12 14:35
@petebacondarwin Thanks for taking the time, this is great news!

Besides the variable name mangling, I found some more issues when using terser to minify the package:

  - Inheritance failed if the `_super` argument of the transformed class was renamed to something else. Interestingly this caused runtime error, rather than build error. It might be possible that the PR fixes this as well, the test reproduction repo does not contain inheritance.

  - If terser compress is enabled, it doesn't like the `join_vars`, `reduce_vars` and `sequences` settings, I had to turn them off.

  - In some cases (I think in case of static methods/properties), if the minifier removes the extra parenthesis around the transformed class,  `ngcc` will emit duplicate exports, causing build failure:

```
    var TestComponent = /** @class */ (function () {
    }());
```

vs.

```
    var TestComponent = function () {
    }();
```

**Comment by petebacondarwin** [comment] 2019-12-12 14:56
I know that there are a number of minification scenarios that we do not support in ngcc right now.
Can I ask what is the motivation/use case for minifying your library code?
* If you are bundling the final app, then minification can be done there, so there is no size benefit in minifying the imported library
* some people think that minfication obfuscates their code. I am sure this is not the case here - especially as the original source if available on github.

**Comment by petebacondarwin** [comment] 2020-01-09 17:54
@dioslaska - can you respond to my question? In general heavily minifying library code is not very useful. There are lots of potential minification scenarios that make it almost impossible for ngcc to be able to reverse engineer what is going on, so that it can process it.

**Comment by dioslaska** [comment] 2020-01-10 07:27
@petebacondarwin Thanks for following up.
On github we only have the light version of the package, besides that we provide premium packages in private npm registries, where we wish to serve the minified code only.
I'm totally aware that minification does not obfuscate / protect the code, but it's definitely much harder to read, and that stops most of the people to mess with it - that's all we want here.

I also accept the fact that heavy minification will not be supported, I'm just talking about a few issues which seems weird to break the code and potentially might appear in uncompressed code as well.

Currently I'm working with the following terser options to generate a working bundle:

    terser({
      mangle: {
        keep_fnames: /^Mbsc/,
        module: false,
        reserved: ['_super'],
        toplevel: false,
      },
      compress: {
        join_vars: false,
        reduce_vars: false,
        sequences: false,
      },
      output: {
        wrap_iife: true,
      }
    }),
    postprocess([
      [/}\)\(\);/, '}());']
    ])
    
What I would expect to work:

1. Transpiled classes not wrapped inside extra paranthesis (so I can get rid of `wrap_iife` and post process replace)
2. `keep_fnames`: See the inner function name:

Works:

    var MbscComponent = /** @class */ (function () {
        function MbscComponent() {}
        MbscComponent.decorators = [...];
        return MbscComponent;
    }());

Does not work:

    var MbscComponent = /** @class */ (function () {
        function x() {}
        x.decorators = [...];
        return x;
    }());

3. `join_vars` - `var TestComponent1 = function () {...}(),TestComponent2 = function () {...}();` - this should work
4. `reduce_vars` - I'm not exactly sure what this does, need to check it further.
5. `sequences` - Stuff like `myFunc1(),myFunc2()` (with comma) should not cause problems either.

Note: I last tested this with rc4 I think, I will try it with the current latest rc8 and update if anything changed.

**Comment by petebacondarwin** [comment] 2020-01-10 08:16
Please do test with the latest RC. We did a bit of work in this area to help support another package that was doing some minifying of their code...

**Comment by dioslaska** [comment] 2020-01-15 09:53
I did test it with rc8 and here are my findings:

1. Transpiled classes not wrapped inside extra paranthesis are still not working, so `wrap_iife` and post process replace is still needed, but now fails with a different error message: `No typings declaration can be found for the referenced NgModule class in function(e){return{ngModule:MbscModule,providers:[{provide:MbscRouterToken,useExisting:e.angularRouter}]}}.`

2. `keep_fnames` - this is not needed anymore, works fine without.

3. `reserved: ['_super']` - this is still needed to prevent renaming the `_super` parameter of an inherited class. If removed, the compilation runs fine, but will throw a runtime error.

4. `join_vars` - still does not work, but now fails with a different error message: `No typings declaration can be found for the referenced NgModule class in function(e){return{ngModule:MbscModule,providers:[{provide:MbscRouterToken,useExisting:e.angularRouter}]}}.`

5. `reduce_vars` - this works now

6. `sequences` - still does not work, the error remained the same: `could not be resolved to an NgModule class`

7. Additionally I got a new error message: `The target entry point @mobiscroll/angular has missing dependencies"
This is caused by the fact that my typescript entry file imports a plain js file (`import './mobiscroll.common`) - the import will be present in the generated `d.ts` file as well, but the referenced js file will of course not be present in the generated package. I solved this by removing the import from the `.d.ts` file, but this worked with rc4 - meaning that our versions, which worked with rc4, are no longer working with rc8. Any input on this?

**Comment by petebacondarwin** [comment] 2020-01-21 08:37
So my understanding of the current state is:

* 1, 3, 4 and 6 are still unsupported by ngcc
* I believe that 7 should now be fixed after various recent PRs including https://github.com/angular/angular/pull/34695

If you could provide simple reproductions of 1, 4 and 6 I think we could get them working. I doubt we could easily support 3.

I am going to close this issue now. Let's open individual issues for the items above if we are going to try to solve them. Thanks for your excellent analysis and feedback @dioslaska .

**Closed by petebacondarwin** 2020-01-21 08:37 UTC
Labels: comp: ngcc, freq1: low, severity5: ivy-compat, state: has PR, type: bug/fix

**Comment by shreykene** [comment] 2020-02-12 13:47
`ERROR in Failed to compile entry-point angular-tree-component (module as esm5) due to compilation errors:
node_modules/mobx-angular/dist/mobx-angular.d.ts:8:22 - error NG6002: Appears in the NgModule.imports of TreeModule, but could not be resolved to an NgModule class

8 export declare class MobxAngularModule {`

**Comment by petebacondarwin** [comment] 2020-02-12 14:51
@shreykene - sorry you are getting an error. Please don't add to closed issues. Can you create a new issue with a way to reproduce the error so that we can investigate please.
