### ISSUE TITLE
Module build failed (from ./node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js): Cannot read properties of undefined (reading 'file')

### ISSUE THREAD

**Issue by waxthevan** [angular/angular#50961] opened 2023-07-06 11:19 UTC
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

In the company i work every pipeline that builds for our apps (some in angular 12, some in angular 15) are failing with the same error.  Created a simple test app and try to serve it, and that's also failing on latest version:

![image](https://github.com/angular/angular/assets/58008183/d21a3d01-fe0d-4a79-b947-bf74ff6033e7)
![image](https://github.com/angular/angular/assets/58008183/76360a4a-831f-4bd4-80af-f9cf72bdc51a)

Has been happening for the last one hour, so I assume it's related to a package that angular install as dependency or the packages that they depend since  installing the packages with strict versions didn't solve the issue.

### Please provide a link to a minimal reproduction of the bug
Repro steps:
- Clean node_modules
- npm install 
- ng serve

### Please provide the exception or error you saw

```true
Some examples from a lot of other same bugs from different packages:

Module build failed (from ./node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js):
TypeError: \web\node_modules\@angular\cdk\fesm2020\collections.mjs: Cannot read properties of undefined (reading 
'file')

Module build failed (from ./node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js):
TypeError: C:web\node_modules\@angular\material\fesm2020\icon.mjs: Cannot read properties of undefined (reading 'file')
```

### Please provide the environment you discovered this bug in (run `ng version`)

12.x.x - 15.x.x - 16.x.x

### Anything else?

It's a global issue so you can check the tickets people have been logging since one hour.
https://stackoverflow.com/questions/76627986/getting-problem-starting-serving-new-project-angular
https://stackoverflow.com/questions/76627746/module-build-failed-in-angular-router
https://stackoverflow.com/questions/76627367/angular-new-project-cannot-read-propertie

**Comment by ohois** [comment] 2023-07-06 11:24
I have exactly the same error.

```
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 16.1.3
Node: 16.20.1
Package Manager: yarn 3.6.0
OS: linux x64

Angular: 16.1.3
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, platform-browser
... platform-browser-dynamic, router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1601.3
@angular-devkit/build-angular   16.1.3
@angular-devkit/core            16.1.3
@angular-devkit/schematics      16.1.3
@schematics/angular             16.1.3 (cli-only)
ng-packagr                      16.1.0
rxjs                            7.8.1
typescript                      5.1.6
```

**Comment by waxthevan** [comment] 2023-07-06 11:30
related: https://github.com/angular/angular-cli/issues/25496#issuecomment-1623426311

**Comment by alan-agius4** [comment] 2023-07-06 11:53
Duplicate of https://github.com/angular/angular-cli/issues/25496

**Closed by alan-agius4** 2023-07-06 11:53 UTC
