### ISSUE TITLE
ngFor reloading on Angular Change Detection (input)

### ISSUE THREAD

**Issue by danielehrhardt** [angular/angular#34444] opened 2019-12-17 00:58 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....
@angular/compiler-cli

### Is this a regression?
Yes. It is not working since Angular 9 RC4

### Description
I saw this Problem since Angular 9 RC4, when I type in something in a input with a ngmodel and have some Gifs in a ngFor, the gifs starts from the beginning and flickering. 

I can currently only reproduce the problem in Safari on iOS.
In the video, you can see what the problem is.
https://www.youtube.com/watch?v=wdEEszzA72Q

## 🔬 Minimal Reproduction
https://github.com/danielehrhardt/angular-ionic-flickering
npm i 
open the project on a iOS Device in Safari

## 🌍  Your Environment

**Angular Version:**
<pre><code>
  "@angular-devkit/architect": "~0.900.0-rc.6",
    "@angular-devkit/build-angular": "~0.900.0-rc.6",
    "@angular-devkit/core": "~9.0.0-rc.6",
    "@angular-devkit/schematics": "~9.0.0-rc.6",
    "@angular/cli": "~9.0.0-rc.6",
    "@angular/compiler": "~9.0.0-rc.6",
    "@angular/compiler-cli": "~9.0.0-rc.6",

</code></pre>

**Comment by pkozlowski-opensource** [comment] 2019-12-17 09:31
I believe that this is duplicate of #34336 - currently we've got a bug where `ngClass` / `ngStyle` is writing to the DOM even if there is no change in the binding (as in your case [here](https://github.com/danielehrhardt/angular-ionic-flickering/blob/1a202f5b33bf5f0d8a00c8b6eac1347af75d8403/src/app/tab1/tab1.page.html#L13).

BTW, you can probably simplify your code (and work-around this bug) by doing `[style.background-image]="url(' + 'https://media.giphy.com/media/' + test.giphy_id + '/giphy.gif' + ')'"` (not tested).

**Comment by pkozlowski-opensource** [comment] 2020-01-22 15:54
This was fixed in master via https://github.com/angular/angular/commit/abd462858732141aedbc12644e93fa725103b660

**Closed by pkozlowski-opensource** 2020-01-22 15:54 UTC
Labels: comp: ivy, severity5: ivy-compat, type: bug/fix
