### ISSUE TITLE
Warning-System.Import() is deprecated. Use Import() instead

### ISSUE THREAD

**Issue by pkrd** [angular/angular#23426] opened 2018-04-18 07:11 UTC
Hi,

I am trying to migrate my demos of Angular 5 from Webpack 3 to Webpack 4. Everything works fine but after the dev/prod build, I am getting two warnings.

![wepack4wrn](https://user-images.githubusercontent.com/38485589/38916631-b0c87d6e-42d7-11e8-86a6-52d265b7b15d.png)

The link below says that to disable the warning you have to use Rule.parser.system: true. But I am not able to think how to use this syntax.

webpack/webpack#6357webpack/webpack#6357, webpack 4.0.0-alpha.5 feedback

Please help!

**Comment by trotyl** [comment] 2018-04-18 07:42
Duplicate of https://github.com/angular/angular/issues/21560

**Comment by pkrd** [comment] 2018-04-18 08:07
I have gone through all the posts. But still not able to figure out the solution for the warnings. Need some help on the same!

**Comment by trotyl** [comment] 2018-04-18 08:27
Please just ignore that warning.

**Comment by pkrd** [comment] 2018-04-18 08:45
Okay! Thank you for your help! But just one question. If I demonstrate the same to client, can I say that these warnings will be fixed in future?

**Comment by vicb** [comment] 2018-04-20 02:34
closing as duplicate

**Closed by vicb** 2018-04-20 02:34 UTC

**Comment by GudaPraveenKumar** [comment] 2018-11-08 10:35
> Duplicate of #21560

What is the solution?

**Comment by ermarkar** [comment] 2018-12-24 12:00
To hide this warning put this code in webpack config ```module:{[rules[//here]]}```

```// Ignore warnings about System.import in Angular
{ test: /[\/\\]@angular[\/\\].+\.js$/, parser: { system: true } },```

https://stackoverflow.com/questions/53913138/what-is-angular-compilation-warning-about-system-import-deprecation
