### ISSUE TITLE
Angular should natively support passive event listeners

### ISSUE THREAD

**Issue by mertdeg2** [angular/angular#21801] opened 2018-01-26 14:21 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
@HostListener API doesn't allow us to make an event handler passive. As a result, component authors sometimes need to use addEventListener API to get around this: https://github.com/angular/material2/blob/master/src/lib/core/ripple/ripple-renderer.ts#L88

## Expected behavior
Angular allows us to do something like:
@HostListener('touchstart', {passive: true})

## Minimal reproduction of the problem with instructions
N/A

## What is the motivation / use case for changing the behavior?

Passive event handlers can increase performance. More on this topic:  https://github.com/WICG/EventListenerOptions/blob/gh-pages/explainer.md

## Environment
All

**Comment by mertdeg2** [comment] 2018-01-26 14:22
@IgorMinar

**Comment by JiaLiPassion** [comment] 2018-01-26 14:26
@mertdeg2 , I just made a PR to be able to config `zone` in `HostListener`, I would like to make a PR to config `passive`.

**Comment by trotyl** [comment] 2018-01-26 14:30
Duplicate of #8866

**Comment by IgorMinar** [comment] 2018-01-26 14:48
thanks @trotyl, I'll close this in favor of #8866.

**Comment by IgorMinar** [comment] 2018-01-26 14:48
thanks @JiaLiPassion, I see that you commented on #8866 as well.

**Closed by IgorMinar** 2018-01-26 14:48 UTC
Labels: comp: core & compiler, hotlist: google, type: feature
