### ISSUE TITLE
Update state bug when using async generators

### ISSUE THREAD

**Issue by sladiri** [angular/angular#26524] opened 2018-10-17 19:13 UTC
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
An input field triggers a function, which updates a component property (string). Typing slowly in an input field misses some updates in the UI, which is bound to the component property.

I created a minimal example with a Readme: https://github.com/sladiri/angular-bug-example 

## Expected behavior
The view should update with every keystroke.

## Minimal reproduction of the problem with instructions
A minimal example with a Readme is here: https://github.com/sladiri/angular-bug-example

Steps to reproduce:
- Type slowly in the input field.

## What is the motivation / use case for changing the behavior?
--

## Environment

<pre><code>
Angular version: 7.0.0-rc

Browser:
- [x] Chrome (desktop) version 70
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version 63.0b14
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [x] IE version 11
- [x] Edge version 17.17134
 
For Tooling issues:
- Node version: v10.11.0
- Platform:  Windows

Others:
--
</code></pre>

**Comment by trotyl** [comment] 2018-10-18 05:32
Duplicate of https://github.com/angular/zone.js/issues/740, Zone.js doesn't work with native `async` function.

**Comment by sladiri** [comment] 2018-10-18 16:32
Thank you, I saw that ticket and I guessed that it might be related.

**Closed** 2018-10-18 16:32 UTC
