### ISSUE TITLE
Give Universal project more love

### ISSUE THREAD

**Issue by fazpu** [angular/angular#37871] opened 2020-07-01 10:54 UTC
Hi,

prerendering and dynamic server-side rendering is essential feature in today B2C sites.

The continuing feature of Angular Universal is that there is almost no documentation.

There used to be a showcase repo [universal-starter](https://github.com/angular/universal-starter) that allowed us to see how the prerendering was done (despite not documented at the time). This repo is now archived.

We are currently stuck with Angular 8, because there is no documentation, how to upgrade the prerender / SSR logic from existing solution. This is especially painful in more complicated scenarios, such as dynamic routes generation preceding prerendering phase.

When competing with React and Vue, Universal should be showcased as first class citizen. Instead, it mostly seem like unwanted cousin.

Please, give Angular Universal more love.

**Comment by alan-agius4** [comment] 2020-07-07 11:52
Hi @fazpu, 

With regards to how to upgrade from version 8 to 9, while I do agree that some more documentation would be useful. You can use `ng update @nguniversal/express-engine`, which will alter the your universal project to be compatible with Ivy.

The stater repo is redundant in many cases, because users can add Universal to their existing application using a single command `ng add @nguniversal/express-engine`.  And in case users don't want to add universal to their existing application but want to experiment in a dummy project they can do so by running `ng new`.

```
npx @angular/cli new universal-testing --routing
```

**Comment by alan-agius4** [comment] 2020-07-07 12:00
You can also take a look at this article https://trilonio-git-blog-angular-universal-v9.trilon--io.now.sh/blog/angular-universal-v9-whats-new which covers most of the changes in v9 including prerendering with is now out-of-the-box.

This article was written by @MarkPieszak who's part of the Angular Universal team.

Ps: I do agree that more documentation is needed.

**Comment by sanketCactus** [comment] 2020-07-10 13:45
Totally agree with this!
Here is my problem with Angular Universal.
Does anyone have project running with PWA & SSR in offline mode. currently to me it gives 504 timeout (From Serviceworker) on reload, rest the application is cached properly by service workers.

Even if you can point me to relevant issue or article that would be helpful.

Thank You,
Sanket.

**Comment by fazpu** [comment] 2020-07-16 10:00
Hi @alan-agius4,

thank you for suggestion. However, the issue was created after trying to update with `ng update @nguniversal/express-engine` and failing terribly with no sight of hope.

Also, thank you for the blog post link. However, this is not the answer to the underlying problem.

**Comment by petebacondarwin** [comment] 2020-10-19 20:05
Please can you provide more information about the problems you had running `ng update @nguniversal/express-engine`? Without that there is not much more we can do to help with this issue.

**Comment by petebacondarwin** [comment] 2020-10-28 16:28
Closing due to a lack of information and no further activity. If this is still a problem please open a new issue with reproduction steps so that we can diagnose the issue.

**Closed by petebacondarwin** 2020-10-28 16:28 UTC
Labels: comp: server, hotlist: devrel, needs clarification
