### ISSUE TITLE
"#" symbol appended to z-index value on inlined styles (SCSS)

### ISSUE THREAD

**Issue by VirMaker** [angular/angular#42231] opened 2021-05-21 21:42 UTC
# Bug Report

### Is this a regression?

Yes, the previous version in which this bug was not present was: .... 11.2

### Description
Prod build of angular 12.0.1 prepends "#" symbol to some z-index values. I believe this is happening only for z-index values >= 100. I think this is happening when styles get inlined in resulting js files. As far as I can tell this was NOT happening on angular 11.2 we had inlining explicitly enabled in our config

## Your Environment

**Angular Version:**
<pre><code>
Angular: 12.0.1
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.1
@angular-devkit/build-angular   12.0.1
@angular-devkit/core            12.0.1
@angular-devkit/schematics      12.0.1
@nguniversal/builders           12.0.0
@nguniversal/common             12.0.0
@nguniversal/express-engine     12.0.0
@schematics/angular             12.0.1
rxjs                            6.6.7
typescript                      4.2.4

</code></pre>
![generated_style](https://user-images.githubusercontent.com/5204757/119200860-6be2a700-ba53-11eb-9dd5-178b4697486d.png)
![original_style](https://user-images.githubusercontent.com/5204757/119200868-6f762e00-ba53-11eb-9c46-ba143b176d87.png)

**Comment by JoostK** [comment] 2021-05-21 22:09
Duplicate of angular/angular-cli#20870. This was an upstream bug in cssnano.

**Closed by JoostK** 2021-05-21 22:09 UTC
