### ISSUE TITLE
bug(Router): Trying to activate an aux-route from a nested component crashes the router

### ISSUE THREAD

**Issue by choeller** [angular/angular#7594] opened 2016-03-14 13:48 UTC
**Note: for support questions, please use one of these channels:** https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ... **
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**

a Bug

* **What is the current behavior?**

Trying to activate an aux-route from a nested Route leads to the following exception:

```
Uncaught Link "["/",["Side",{"id":"1"}]]" does not resolve to a terminal instruction.
```
after that the router stops working at all.

The Config is as followed:

Top-Level Component:
```ts
@RouteConfig([
  {path: '/', component: Dashboard, name: 'Dashboard'},
  {path: '/tasks/...', component: Tasks, name: 'Tasks'},
  {aux: 'side', component: TaskOverview, name: 'Side'}
])
export class App {
}
```
Nested Route:
```ts
@RouteConfig([
  {path: '/list', component: TaskList, name: 'List'},
 ])
export class Tasks {
}
```
Link to Aux-Route from TaskList:
```html
  <a [routerLink]="['/', ['Side', {id: '1'}]]">Task 1 Overview</a>
```
Activating the TaskList-Component immediatelly crashes the router. When adding the same link to the top-level HTML it perfectly works.

Minimal Demo here:
http://plnkr.co/edit/bwsQjpuJv8imRg8NHo7t?p=preview

* **What is the expected behavior?**

Router should not crash when linking to aux-route from nested components

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Angular version: 2.0.0-beta.9
- Browser: [Chrome]
- Language: [TypeScript 1.8.7]

**Comment by choeller** [comment] 2016-03-14 21:13
One other thing I tried:
When trying to activate the Aux-Route like this:
```
  <a [routerLink]="[ '/Tasks', 'List', ['Side', {id: '1'}]]">Task 1</a>
```
with
```
Component "Tasks" has no route named "Side". in [[ '/Tasks', 'List', ['Side', {id: '1'}]]
```

**Comment by jayku4u** [comment] 2016-04-11 14:03
did u get a chance to resolve this?

**Comment by jmsegrev** [comment] 2016-04-15 16:03
The problem here is that the `router.unregisterPrimaryOutlet()`, only accepts unnamed route outlets. I'm not sure of the reason behind this, but this function as defined only sets the Router member `_outlet ` to null.

```
// Router
unregisterPrimaryOutlet(outlet: RouterOutlet): void {
    if (isPresent(outlet.name)) {
        throw new BaseException(`registerPrimaryOutlet expects to be called with an unnamed outlet.`);
    }
    this._outlet = null;
}
```

I was able to work around this problem, by replacing this function for the router in the component that defines the aux routes.
```
// injected Router on the component that defines the aux routes 
this.router.unregisterPrimaryOutlet = function(outlet) {
    // does not throw
    this._outlet = null;
};
```

This is a temporary fix you can have done in your code, for mine it did not have any side effects (so far).

**Comment by vsavkin** [comment] 2016-07-11 22:34
We are no longer maintaining the deprecated router to focus our efforts on making the new router robust. So I'm closing this issue.

It does not look like the issue is present in the new router. But if you think it does, please reopen it with a punker that uses the new router.

**Closed by vsavkin** 2016-07-11 22:34 UTC
Labels: comp: router/aux, effort2: medium (day), P3: important, type: bug
