### ISSUE TITLE
Template parser error: unknown entity &quot;

### ISSUE THREAD

**Issue by tycho01** [angular/angular#5553] opened 2015-12-02 17:49 UTC
Since upgrading from alpha 46 to 47 I'm now no longer able to load my app using identical HTML. I'm suddenly greeted with `Template parser error: unknown entity &quot;`.

The html element deemed offensive was as follows: `<input type="text" value="{&quot;name&quot;:&quot;title&quot;}">`.

I'd submit a plunker but I don't think they update version that fast...

**Comment by pkozlowski-opensource** [comment] 2015-12-02 18:13
Duplicate of https://github.com/angular/angular/issues/5546

**Closed by pkozlowski-opensource** 2015-12-02 18:13 UTC
