### ISSUE TITLE
Provide Entry point for service worker

### ISSUE THREAD

**Issue by fksik** [angular/angular#39290] opened 2020-10-15 16:17 UTC
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/service-worker

### Description
 If using angular service worker there is no way to modify the push messages once they reach the application...

### Describe the solution you'd like
 By providing an entrypoint this could solve the problem of modifying the push messages view accordinly, and could potentially unlock many other features into the service worker like Integrating firebase messenging or others.

**Comment by gkalpak** [comment] 2020-10-15 17:59
Thx, @fksik! Can you please elaborate on what you are trying to achieve? What entry-point are you looking for?

**Comment by fksik** [comment] 2020-10-16 05:04
Hi @gkalpak,
      Entry point as main.ts from where we can provide custom push message handler.

**Comment by gkalpak** [comment] 2020-10-16 09:51
@fksik, I am still not following I'm afraid. Push messages are handled on the ServiceWorker (while `main.ts` is for the regular app).
Maybe you could share some code of how you intend to use the requested API (just pretend that the API exists).

**Comment by fksik** [comment] 2020-10-16 16:30
Hi @gkalpak,
This is the code in /packages/service-worker/worker/main.ts 
```
const adapter = new Adapter(scope.registration.scope);
const driver = new Driver(scope, adapter, new CacheDatabase(scope, adapter));
```
which is not accessible outside the source code.

If there is is a chance that this main.ts exposed to developers we can use it like

```
const adapter = new Adapter(scope.registration.scope);
const driver = new Driver(scope, adapter, new CacheDatabase(scope, adapter) ,  **handlePush**);
```
after broadcasting message, we can use handlePush to mutate pushmessage notificationOptions and customData property according to the need of the developer

**Comment by gkalpak** [comment] 2020-10-19 11:10
I see. This is essentially a duplicate of #24387 (or even #26413). (This issue suggest a specific implementation, but the main idea is having a way to modify how `push` events are handled.

I am going to close this issue in favor of #24387/#26413 - feel free to comment there with anything you think would be useful.

##
In the meantime, one possible work-around is to define a custom ServiceWorker script that will set your own `push` handler and then import the Angular ServiceWorker (similar to what is discussed in #26907 - for example https://github.com/angular/angular/issues/26907#issuecomment-467552342):

```js
// Register a `push` listener before the Angular ServiceWorker.
self.addEventListener('push', evt => {
  // Prevent the event from reaching the Angular ServiceWorker `push` listener.
  evt.stopImmediatePropagation();

  // Handle the `push` event here.
  // ...
});

// Include the Angular ServiceWorker.
importScripts('./ngsw-worker.js');
```

**Closed by gkalpak** 2020-10-19 11:10 UTC
Labels: comp: service-worker, feature
