### ISSUE TITLE
formGroup disable()/enable() does not work right after init

### ISSUE THREAD

**Issue by ctrl-brk** [angular/angular#22556] opened 2018-03-02 16:59 UTC
## I'm submitting a...
<pre><code>
[x] Bug report  
</code></pre>

## Current behavior
I you create a `formGroup` using `formBuilder.group()` and call` formGroup.disable()` or `formGroup.enable()` right after initialization then it doesn't work.
If you call it using `button` or `setTimeout()` then it works.

## Expected behavior
Would be nice to be able to disable/enable form right after creation.

## Minimal reproduction of the problem with instructions
View: https://ng-form-disable-after-init.stackblitz.io
Edit: https://stackblitz.com/edit/ng-form-disable-after-init

## Environment
<pre><code>Angular version: 5.2.7</code></pre>

**Comment by jotatoledo** [comment] 2018-03-02 17:32
Can you provide a link to the stackblitz editor of your demo?

**Comment by Toxicable** [comment] 2018-03-03 07:47
Could you explain the steps to reproduce, I don't see anything wrong in your stack blitz

**Comment by ctrl-brk** [comment] 2018-03-03 16:28
Click on "Disable with init" button. It will not disable the form. Or click any other "Disable" and than "Enable with init".

**Comment by danguilherme** [comment] 2018-06-01 19:09
I am having the same issue, here is a summary of my setup:

**component.ts**
```typescript
ngOnInit() {
  this.disabledGroup = new FormGroup({});
  this.disabledGroup.disable();
}
```

**component.html**
```html
<pre>{{ disabledGroup.disabled }}</pre> <!-- prints: false -->
```

Changing `this.disabledGroup.disable()` to `setTimeout(() => this.disabledGroup.disable(), 0);` works as expected.

<details>
  <summary><code>ng version</code></summary>
  <hr>
  <pre>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 6.0.3
Node: 8.11.2
OS: darwin x64
Angular: 6.0.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.6.1
@angular-devkit/build-angular      0.6.1
@angular-devkit/build-ng-packagr   0.6.3
@angular-devkit/build-optimizer    0.6.1
@angular-devkit/core               0.6.1
@angular-devkit/schematics         0.6.3
@angular/cli                       6.0.3
@ngtools/json-schema               1.1.0
@ngtools/webpack                   6.0.1
@schematics/angular                0.6.3
@schematics/update                 0.6.3
ng-packagr                         3.0.0-rc.5
rxjs                               6.1.0
typescript                         2.7.2
webpack                            4.6.0
  </pre>
</details>

**Comment by tjaartvanderWalt** [comment] 2018-09-07 10:09
I Have the same issue, you can find a minimal working example [here](https://next.plnkr.co/edit/O1R6wnSOGqvvkRFI?open=lib%2Fapp.ts&deferRun=1&preview)

```
import { NgModule } from '@angular/core';
import { ReactiveFormsModule } from '@angular/forms';
import { BrowserModule } from '@angular/platform-browser';
import { HttpClientModule } from '@angular/common/http';
import { PersonService } from './person.service';
import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';

@Component({
  selector: 'my-app',
  template: `  
        <form [formGroup]="form">    
        <button class="btn btn-primary" (click)="onFetchPerson()">Click Me</button>                
            <div class="form-group">
                <label>First Name</label>
                <input type="text" class="form-control" formControlName="firstName" />
            </div>
            <div class="form-group">
                <label>Surname</label>
                <input type="text" class="form-control" formControlName="surname" />
            </div>
            <div class="form-group">                
                Disabled:{{form.disabled}}<br>
                Status:{{form.status}}
            </div>
        </form>
    `,
})
export class App implements OnInit {  
  public form: FormGroup;

  constructor(private personService: PersonService) {}

  ngOnInit(): void {
    this.form = new FormGroup({     
      firstName: new FormControl(),
      surname: new FormControl(),
    });
  }

  public onFetchPerson() {
    this.personService.fetchPerson().subscribe(() => {
      this.form = new FormGroup({        
        firstName: new FormControl('John'),
        surname: new FormControl('Doe'),
      });
      this.form.disable();
      console.log(this.form);
    });
  }
}

@Injectable({
  providedIn: 'root',
})
export class PersonService {
  constructor(private http: HttpClient) {}

  public fetchPerson = () => this.http.get('https://randomuser.me/api');
}

@NgModule({
    imports: [BrowserModule, HttpClientModule, ReactiveFormsModule],
    declarations: [App],
    bootstrap: [App],
    providers: [
        PersonService
    ]
})
export class AppModule {}
````
![form-group](https://user-images.githubusercontent.com/11085642/45213051-c84b0b80-b296-11e8-9e15-900fafc75fc1.gif)

**Comment by Dead96** [comment] 2018-09-11 13:56
This simple directive works for me:
```typescript
import { Directive, DoCheck } from "@angular/core";
import { NgControl } from "@angular/forms";

@Directive({
    selector: '[formControlName]'
})
export class FixToggleDisableFormControlDirective implements DoCheck {
    constructor(private ngControl: NgControl) {}
    ngDoCheck() { this.ngControl.control.enabled ? this.ngControl.control.enable() : this.ngControl.control.disable(); }
}
```

Tested on Angular@6.0.5

**Comment by arrow-dev** [comment] 2018-12-09 21:05
I'm having a similar issue, I've got a type-ahead address picker, when an address is selected, in the handler I disable the input `this.addressForm.get('address').disable()` , which works fine, but if the form is reset:
`this.addressFrom = formBuilder.group(...)` the control is reset but the input in the DOM is still disabled.
Workaround is:
`clear() {
  this.initForm();
  setTimeout(() => this.address.enable());
}`

Is there a better way of doing this, shouldn't it just update automatically when the form is re-initialized?

**Comment by giovannipds** [comment] 2018-12-18 19:41
I'm experiencing the same issue. Nothing new about it?

**Comment by lppedd** [comment] 2019-01-21 13:41
Same issue on the latest version.
Damn guys, I was literally going crazy to find what was happening

**Comment by jayoungers** [comment] 2019-01-28 21:22
I am as well: I have a class that extends `FormGroup`, where in the constructor it just calls `super({...})` to populate the form, then calls `disable()`.

If I dispatch a new instance of this object to the state, the form in the UI does not render as I'd expect (if the old form was enabled, the fields will still be enabled).

If I wrap the `.disable()` line in a `setTimeout()`, then it works as you'd expect.

**Comment by lppedd** [comment] 2019-01-28 21:52
@jayoungers I solved with @Dead96 directive. It's a cleaner solution.

**Comment by Moulde** [comment] 2019-02-12 13:57
I just hit this issue as well - so hard to debug.
I don't like having to run stuff in setTimeout for it to work :(

**Comment by Dead96** [comment] 2019-02-12 15:08
I've updated my directive, resolving the enable/disable methods calling infinite loop! :)

**Comment by lppedd** [comment] 2019-02-12 16:11
@Dead96 mmmh I didn't experience such a problem. Under which circumstances did this happen?

**Comment by Dead96** [comment] 2019-02-12 16:19
@lppedd I've noticed that when I'm debugging and the app becomes really slow. Add this check in the directive solves my problem

**Comment by mohanramphp** [comment] 2019-03-11 11:36
Any plan to fix in ReactiveFormModule, this setTimeout solution is annoying since purpose of reactive form is to keep things synchronous.

**Comment by ptrzyna** [comment] 2019-05-06 19:14
Version 8 is about to drop...is this bug going to be addressed?

**Comment by ikilinc** [comment] 2019-06-13 11:31
I have version 8 but still same issue

**Comment by ikilinc** [comment] 2019-06-13 11:54
another workround for this issue is to call detectChanges() before .disbale()/.enable() operations.

**Comment by naveenkumarv183** [comment] 2019-07-12 14:00
> I am having the same issue, here is a summary of my setup:
> 
> **component.ts**
> 
> ```ts
> ngOnInit() {
>   this.disabledGroup = new FormGroup({});
>   this.disabledGroup.disable();
> }
> ```
> 
> **component.html**
> 
> ```
> <pre>{{ disabledGroup.disabled }}</pre> 
> ```
> 
> Changing `this.disabledGroup.disable()` to `setTimeout(() => this.disabledGroup.disable());` works as expected.
> 
> `ng version`

I am able to disable synchronously 

with following code:
Object.keys(this.formGroup.controls).forEach(field => {
      const control = this.formGroup.get(field);
      if (control instanceof FormControl) {
        control.disable();
      }
    });

**Comment by jayoungers** [comment] 2019-07-12 14:33
I commented earlier about using a `setTimeout()`, but I think I have another solution:

Due to difficulties in testing my more complicated forms I made the constructor private, making it so you have to call a static method to create the form.  I believe setting the form as disabled in that method should resolve the issue as well.

```js
static create(options) {
   const form = new MyForm();
   form.disable();

   return form;
}

private constructor() {}
```

Regarding the testing note, I went this route for situations where I just needed to verify the form was getting passed in the correct options without worrying about everything it did to initialize:

```js
spyOn(MyForm, 'create').and.returnValue(whatever)
```

**Comment by alexsandroaoliveira** [comment] 2019-07-24 13:21
> ## I'm submitting a...
> ```
> 
> [x] Bug report  
> ```
> 
> ## Current behavior
> I you create a `formGroup` using `formBuilder.group()` and call` formGroup.disable()` or `formGroup.enable()` right after initialization then it doesn't work.
> If you call it using `button` or `setTimeout()` then it works.
> 
> ## Expected behavior
> Would be nice to be able to disable/enable form right after creation.
> 
> ## Minimal reproduction of the problem with instructions
> View: https://ng-form-disable-after-init.stackblitz.io
> Edit: https://stackblitz.com/edit/ng-form-disable-after-init
> 
> ## Environment
> ```
> Angular version: 5.2.7
> ```

Try to bind the inputs with  [formControl]="form.controls['controlName']" insted of formControlName

**Comment by KDusak** [comment] 2019-08-29 15:14
I found one solution, without setTimeout and extra directives. Try to put this into your form elements:

`[attr.disabled]="formGroup.controls['userName'].disabled"`

**Comment by MRMokwa** [comment] 2019-09-27 19:09
Bump.
Same problem with angular 8

**Comment by kyro38** [comment] 2019-10-15 08:40
Also reporting this problem on 8.2

**Comment by rcpp0** [comment] 2019-10-29 09:10
Same issue on 8.1.3 ! Guys, this issue has been opened almost 2 years ago, come on !

**Comment by Mattkins** [comment] 2019-11-06 15:34
I was having an issue that may be related, thought I'd share for everyone. My form component is subscribing to a subject on its parent component, and is supposed to disable itself when the parent is communicating with the server. The subscription happen in ngOnInit, but the actual call to disable() does not happen until the user clicks submit and the client starts communicating with the server, so I thought this was unrelated.
```
if (this.communicating) {
          this.communicating.subscribe((isCommunicating) => {
            if (isCommunicating) {
              this.form.disable()
            } else {
              this.form.enable()
            }
          })
        }
```
After days of frustration, I decided to throw the timeout line into my code, but neglected to remove the old line calling disable(). Bam, it worked! So I go take out the old line, and it no longer worked. That's when I discovered that you have to **double-call** disable() to get it to work.

```if (isCommunicating) {
              this.form.disable()
              this.form.disable()
            }```

Crazy. This is made even more strange by the fact that I use this method for another form with basically the exact same code, and it works.

**Comment by maxime1992** [comment] 2019-12-17 17:32
Using angular 8.2.14 I tried all the workarounds above (manually running CD, calling disable twice, ...) nothing worked. If anyone else has a workaround please post an update :pray:

**Comment by rcpp0** [comment] 2019-12-17 20:15
Update on my part :  

After a lot of testing, I’ve realized that my actual issue was not exactly the FormControl itself but rather the fact that the input component it was bound onto didn’t handle properly the disabled state.

I didn’t dig this through but I suspect that since the "setDisabledState" method of the ControlValueAccessor interface has only been added recently (in which version exactly I’m not sure) working with an older input component or third-part library might result in the visual component to ignore the disabled value of the FormControl it’s targetting. (Once again, only my guess, I didn’t check this theory thoroughly)

So one thing you can try to test that you have the same issue is creating or extending your own input component that would implement the ControlValueAccessor interface and be careful especially to implement properly the setDisabledState() method. (for a simple test, just log the parameter in the console when the method is called). If you don’t know how to do this properly there are tutorials like in here :  https://alligator.io/angular/custom-form-control/

This is what I did and now it works fine. Hope this helps some of you guys.

**Comment by maxime1992** [comment] 2019-12-18 11:18
Thanks @rcpp0 but I doubt that's the case.

The issue is happening on a library we built at work: https://github.com/cloudnc/ngx-sub-form

It does work on most of the forms but for some reason, for some of them it doesn't work :man_shrugging:. I couldn't figure out why.

The way the library works to manage sub forms is for every control value accessor we create an internal form group that represents the sub form and here's how the `setDisabledState` is handled:

```ts
public setDisabledState(shouldDisable: boolean | undefined): void {
  if (shouldDisable) {
    this.formGroup.disable({ emitEvent: false });
  } else {
    this.formGroup.enable({ emitEvent: false });
  }
}
```

So if working for one, no sign of weird behavior indicating that it shouldn't work for others here IMO.

After digging into this issue on the library, I found out that within the hook `writeValue` of the control value accessor, we are doing:

```ts
this.formGroup.setValue(transformedValue, {
  emitEvent: false,
});
```

The fix is actually as simple, weird and unexpected as:

```ts
const fgDisabled: boolean = this.formGroup.disabled;

this.formGroup.setValue(transformedValue, {
  emitEvent: false,
});

if (fgDisabled) {
  this.formGroup.disable();
}
```

If I console.log before and after the `setValue` the value of `this.formGroup.disabled` it's always the same which makes even less sense to me as if there's an actual bug I thought it would be disabled before and enabled after we update the value. But it's not case even though the fix seems to point in the opposite direction :man_shrugging:

**Comment by Xambey** [comment] 2020-02-17 12:20
Same issue on 8.2.14 
![image](https://user-images.githubusercontent.com/17352479/74653348-0b522380-5199-11ea-87d3-e432236c6950.png)

**Comment by doomevaristo** [comment] 2020-02-28 14:08
Same issue here.

**Comment by navarrofracisco** [comment] 2020-03-04 21:56
Any update on this? and is it related to? https://github.com/angular/angular/issues/35565

This seems like a huge deal, since reactive forms seem to be preached as the best approach everywhere. Yet I can not disable an input... Any other workarounds?

**Comment by nasreddineskandrani** [comment] 2020-03-08 22:40
@maxime1992 
> If anyone else has a workaround please post an update
the solution on this comment https://github.com/angular/angular/issues/22556#issuecomment-501670796 works :) this is what i am using for more than 2 years :P

```
    this.form = this._fb.group({
      'input1' : ['value' + this.value++]
    });
    this.cdr.detectChanges()
    this.form.disable();
```

I am debugging angular code base to understand where in the lifecycle it rebind it to evaluate the `disabled` but to be honest the other issue about 'readOnly' is far more important to fix so i prefer to check the readonly first :P  (the one you posted a big text)

**Comment by yimam-michael** [comment] 2020-04-22 13:35
I had this issue after creating a custom form control and trying to disable/enable it from the form. 
When I try either `form.control.customControl.enable()` or `form.control.customeControl.disable()`   
I get the error. `ERROR TypeError: v is not a function`.

What solved the issue for me is, implementing the `Validator` interface on my custom control.

**Comment by benjaminbarbe10** [comment] 2020-07-31 10:17
Solved this issue with 
```
this.changeDetector.detectChanges(); // use it before using disable/enable
this.form.controls['name'].disable();
```

**Comment by hiepxanh** [comment] 2020-08-27 15:55
for the note purpose, this one work for me:

```
//.ts
disableForm(customer) {
    this.cd.detectChanges();
    if (customer.isMobile) {
      this.objForm.disable();
      this.objForm.disable();
      this.objForm.updateValueAndValidity();
    } else {
      this.objForm.enable();
      this.objForm.enable();
      this.objForm.updateValueAndValidity();
    }

    setTimeout(() => {
      this.cd.detectChanges();
    }, 100);
  }
```

**Comment by MonstraG** [comment] 2020-09-16 08:17
Angular 8.2.9.

```
ngOnInit() {
  this.form = new FormGroup({
    control: new FormControl({value: '', disabled: true}),
  });
}
```
does not work,

```
ngOnInit() {
  this.initForm();
}

initForm() {
  this.form = new FormGroup({
    control: new FormControl({value: '', disabled: true}),
  });
}
```
works.

I assume it's the same issue.

**Comment by CarlosTorrecillas** [comment] 2020-11-11 16:09
Same issue here

**Comment by lrslima** [comment] 2020-12-04 11:39
Same Issue here, maybe one day this will be fixed...

**Comment by medhatisaac101** [comment] 2021-01-04 23:02
I worked with me after call .enable() inside settimeout
`setTimeout(() => {
        this.OTPForm.enable();
      }, 1000);`

**Comment by brandonmain** [comment] 2021-03-09 16:45
One way I found that fixes this is if your component is using an @Input, then you can set the disabled() in the ngOnChanges after firstChange.

```

export class ExampleComponent implements OnInit, OnChanges {

  @Input() myInput: InputClass;
  exFormGroup: FormGroup;
  disabled = true;

  constructor( private formBuilder: FormBuilder ) { }

  ngOnInit(): void {
    this.exFormGroup = this.formBuilder.group({
      // Your form controls
    });
  }

  ngOnChanges(changes: SimpleChanges): void {
    const change = changes.myInput;
    if (!change.firstChange) {
      this.exFormGroup.disable();
    }
  }

```

**Comment by francves** [comment] 2021-04-15 22:15
Same issue 11.0.7

That's works for me.

> another workround for this issue is to call detectChanges() before .disbale()/.enable() operations.

**Comment by GonziHere** [comment] 2021-04-28 21:38
![image](https://user-images.githubusercontent.com/8655073/116475292-ec115480-a879-11eb-8f50-f5483ca98377.png)
The warehouse is the root for a whole structure, there might be something down the line that updates value/validity, but nothing, I repeat, nothing, touches the warehouse itself.
How is that even possible?
Why is even "enabled/disabled" even related to status? (valid beats disabled, so my money is on a validator that "enables" its control and it propagates it up... ).

**Closed** 2022-03-28 16:26 UTC
Labels: type: bug/fix, freq2: medium, comp: forms, state: has PR, state: confirmed, P3
