### ISSUE TITLE
Querying content with a superclass doesn't work.

### ISSUE THREAD

**Issue by hsw107** [angular/angular#12758] opened 2016-11-07 22:27 UTC
**I'm submitting a ...**
```
[] bug report 
[ x ] feature request
[ ] support request
```

**Current behavior**
Querying ngContent with a superclass doesn't work.

**Expected behavior**
Querying ngContent with a superclass should work.

**Minimal reproduction of the problem with instructions**
Currently, if you have a component that uses ng-content inside of its template, it can render out whatever you pass to it. (ie. any other component or html). However referencing this component is only possible if you know exactly what component it will be.

```
@ContentChildren(Component1) myComponent;
```

In the case where you don't know, you can't select it. My request would be that you can select the components off a super class. Say, `Component1 extends MySuperClass` and `Component2 extends MySuperClass` you can select their instances like so: 

```
@ContentChildren(MySuperClass) myComponents;
```

**What is the motivation / use case for changing the behavior?**
The motivation behind this is allowing dynamic components to be injected yet allow their instance to be referenced by their parent component. In my particular use-case I am allowing the developer to build pages of a wizard containing whatever component they need -- I then assume that they have a class or interface on them that they share so that I can call functions on them like, say, `validate` so I can move forward in the wizard.

```
<wizard>
    <page>
        <component1></component1>
    </page>
    <page>
        <component2></component2>
    </page>
</wizard>
```

**Please tell us about your environment:**
Windows 10, Angular 2.0.1, WebStorm, Webpack/Gulp

**Additional Notes**
A workaround currently is instead to pass the components in as a config (say an array of components) and then refer to them that way. However it would be nice to be able to reference the instances of the components injected dynamically via ng-content

I would also think that this may be related to https://github.com/angular/angular/issues/8580 in the sense that I would expect these two scenarios to work the same. The linked issues mentions that super class selectors should work (at least when the components aren't dynamically defined).

**Comment by ericmartinezr** [comment] 2016-11-07 22:33
See https://github.com/angular/angular/issues/11606, if I understood your issue the one I referenced isn't 100% related to yours (maybe a 99,5% :P). Anyway, it will be useful to understand that inheritance doesn't really work (so far).

**Comment by tbosch** [comment] 2016-11-11 19:28
You already have the following choices:

- mark the element with a `#someName` and then query for `someName`
- provide the component under a new token, and then query for that token. E.g.

```
const MyToken = new OpaqueToken('myToken');

@Component({
  providers: [{provide: MyToken, useExisting: forwardRef(() => MyComponent)}]
})
class MyComponent {}

...

`@ContentChildren(MyToken)`

**Comment by jwa107** [comment] 2016-11-12 00:08
@tbosch that first technique doesn't seem to work -- it was one of the things I tried before attempting to use the superclass approach. The selector seems to get swallowed up and comes back undefined when it's placed on ng-content.

I'm not 100% sure about the second approach but it looks like I'd have to define exactly what components I might be expecting and define those in the providers, rather than just accept whatever comes in.

**Comment by tbosch** [comment] 2016-11-12 00:15
Multiple components can provide themselves under the same token.
I.e. define the token next to the place where you do the `@ContentChild` query. Then any component that would like to be queried provides itself via this token.

But the name should really work... Could you create an example that failed so I can have a look?

**Comment by jwa107** [comment] 2016-11-14 20:13
So I was able to get this to work by providing the name (say #token) on the component itself (that would become the ng-content) rather than on the ng-content itself.

So in short `<ng-content #token>` doesn't work where as `<my-cmp><nested-cmp #token></..></..>` (where nested-cmp will replace ng-content) does work. In the latter case I can select all the tokens by using ContentChild or ContentChildren, whereas the former returned undefined. This seems to be the appropriate work around but doesn't seem very obvious -- though that may just be a lack of documentation that makes it so.

**Comment by kemsky** [comment] 2017-01-25 17:05
@tbosch, using providers is good enough, however it is not obvious and more complicated than it could be.

Much better approach would be to provide filter function which will allow to filter components that you want to select - a fully customizable query.

**Comment by nickiewooster** [comment] 2017-02-24 10:11
Having the exact same problem. 

It would be very helpful if @ContentChildren can query all component of a specific superClass or interface.

Having to know all concrete implementations is very unintuitive when working with dynamic UI.
@ContentChildren can only match once type at a time is not much of help either

**Comment by MiguelLattuada** [comment] 2017-07-13 20:01
How do I set ng-content template part of a dynamically created component with ComponentFactoryResolver?

**Comment by kukjevov** [comment] 2017-12-22 13:18
Was this put to ice? Or is there any chance that we will have chance to obtain all instances of  some superclass with `ContentChildren` or `ViewChildren`?

Is there any chance that there will be some progress on this, or we should stick with `Tokens` workaroud @tbosch @matsko ?

Thank you :)

**Comment by at-vietnguyen** [comment] 2018-12-19 02:06
> How do I set ng-content template part of a dynamically created component with ComponentFactoryResolver?

Same problem

**Comment by pkozlowski-opensource** [comment] 2020-06-09 13:41
> Is there any chance that there will be some progress on this, or we should stick with Tokens workaroud

The Token approach is the recommended one, thus I'm going to close it as a duplicate of #21152

**Closed by pkozlowski-opensource** 2020-06-09 13:41 UTC
Labels: comp: core, core: queries, type: feature
