### ISSUE TITLE
bug(service-worker): ServiceWorker script evaluation failed

### ISSUE THREAD

**Issue by xban1x** [angular/angular#22962] opened 2018-03-23 17:51 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

SW does not register

## Expected behavior

SW to register and function normally

## Minimal reproduction of the problem with instructions

Base Angular CLI project and Samsung Internet 5.2

## What is the motivation / use case for changing the behavior?

SW failing to register partially breaks the app on older browsers. Which should support it without issues.

## Environment

<pre><code>
Angular version: 5.2.9

Browser:
- [ ] Chrome (desktop) version XX
- [x] Chrome (Android) version 51
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
- [x] Samsung Internet version 5.2
 
For Tooling issues:
- Node version: XX  
- Platform:  Android

Others:

</code></pre>

SamsungInternet internally uses Chrome 51

**Comment by gkalpak** [comment] 2018-03-23 19:13
Closing as duplicate of #20756.

**Closed by gkalpak** 2018-03-23 19:13 UTC
