### ISSUE TITLE
Error throw by router when the lazy load module in secondary outlet

### ISSUE THREAD

**Issue by okYadav** [angular/angular#17743] opened 2017-06-24 10:40 UTC
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[x] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

<pre><code>
const routes: Routes = [
    { path: '', component: RootComponent,
        children: [
            { path: '', component: ListComponent },
        ]
    },
    {
        path: '', loadChildren: './create-people/create-people.module#CreatePeopleModule', outlet: 'create'
    }
];
</code></pre>

## Current behavior
I'm trying to implement the code which load the module which is lazy loaded. in secondary outlet but my router throw error

```
core.es5.js:1020 ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'routes' of undefined
TypeError: Cannot read property 'routes' of undefined
    at getChildConfig (router.es5.js:3071)
    at Recognizer.processSegmentAgainstRoute (router.es5.js:3034)
    at Recognizer.processSegment (router.es5.js:2994)
    at Recognizer.processSegmentGroup (router.es5.js:2969)
    at router.es5.js:2978
    at router.es5.js:835
    at forEach (router.es5.js:483)
    at mapChildrenIntoArray (router.es5.js:833)
    at Recognizer.processChildren (router.es5.js:2978)
    at Recognizer.processSegmentAgainstRoute (router.es5.js:3038)
    at getChildConfig (router.es5.js:3071)
    at Recognizer.processSegmentAgainstRoute (router.es5.js:3034)
    at Recognizer.processSegment (router.es5.js:2994)
    at Recognizer.processSegmentGroup (router.es5.js:2969)
    at router.es5.js:2978
    at router.es5.js:835
    at forEach (router.es5.js:483)
    at mapChildrenIntoArray (router.es5.js:833)
    at Recognizer.processChildren (router.es5.js:2978)
    at Recognizer.processSegmentAgainstRoute (router.es5.js:3038)
    at resolvePromise (zone.js:770)
    at resolvePromise (zone.js:741)
    at zone.js:818
    at ZoneDelegate.webpackJsonp.621.ZoneDelegate.invokeTask (zone.js:424)
    at Object.onInvokeTask (core.es5.js:3924)
    at ZoneDelegate.webpackJsonp.621.ZoneDelegate.invokeTask (zone.js:423)
    at Zone.webpackJsonp.621.Zone.runTask (zone.js:191)
    at drainMicroTaskQueue (zone.js:584)
    at <anonymous>
```

## Expected behavior
It should load the module in secondary outlet.

## What is the motivation / use case for changing the behavior?
We can implement this to navigate in dialog box.

## Please tell us about your environment

<pre><code>
Angular version: 4.2.3

Browser:
- [x] Chrome (desktop) version XX
 
For Tooling issues:
- Node version: v7.10.0
- Platform: Linux

**Comment by Toxicable** [comment] 2017-06-24 11:25
Can you please provide a minimal reproduction, preferably in a plunkr, here's a template to get you started https://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5

**Comment by jasonaden** [comment] 2017-07-18 00:52
Duplicate of #10981

**Closed by jasonaden** 2017-07-18 00:52 UTC
Labels: comp: router
