### ISSUE TITLE
Variable using type union error in template: Identifier 'name' is not defined. '<anonymous>' does not contain such a member

### ISSUE THREAD

**Issue by Korbraan** [angular/angular#23789] opened 2018-05-09 10:02 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

I have a variable than can take two types depending of another parameter:
```  secondOperand: number | { name: string; value: string };```

In the template I handle these two possible types, and I in the second type case I have:
```  
<app-simple-dropdown name='Second data type'
                       [options]="dataTypes"
                       [selected]="secondOperand?.name"
                       (change)="secondDataTypeChange($event)"></app-simple-dropdown>
```

The problem is in this code: 
secondOperand?.name```

The error message from the Angular Language Service is: 
```Identifier 'name' is not defined. '<anonymous>' does not contain such a member```.

## Expected behavior

As 'name' can be a valid identifier in the second type case, Angular should not raise an error here.

## Minimal reproduction of the problem with instructions

Declare a variable that can take two types, one being an object and the other a primitive type, and try accessing an object property from a template. 

```
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-alert-rule-creator',
  template: '{{ foo?.thing }}'
})
export class MyClass implements OnInit {

    foo: number | { thing: string };

    constructor() {}

    ngOnInit() {}
}
```
## Environment

<pre><code>
Angular version: 5.2.10

Browser:
- [] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version 61.0a1
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 9.3.0  
- Platform: Linux 

Others:

</code></pre>

**Comment by trotyl** [comment] 2018-05-09 12:10
Expected type error, nothing related to Angular:

![image](https://user-images.githubusercontent.com/6059170/39813887-cc8f3bb6-53c4-11e8-970b-eecbb40d9ddb.png)

http://www.typescriptlang.org/play/index.html#src=declare%20let%20secondOperand%3A%20number%20%7C%20%7B%20name%3A%20string%3B%20value%3A%20string%20%7D%3B%0D%0A%0D%0AsecondOperand%20!%3D%20null%20%3F%20secondOperand.name%20%3A%20null%0D%0A

**Comment by Korbraan** [comment] 2018-05-09 12:15
@trotyl The error I got is different but I think that this is in fact the true problem (the error message, particularly the '<anymous>' part got me confused).

I could use type assertion if I was working in the component file, but it seems to be impossible in the template. Any idea how to get past that limitation?

**Comment by trotyl** [comment] 2018-05-09 14:44
Agree there should be a better error message.

> but it seems to be impossible in the template

Using union type as ViewModel is a very bad idea. For skipping the error: https://angular.io/guide/template-syntax#the-any-type-cast-function-any-expression-

**Comment by Korbraan** [comment] 2018-05-09 15:28
Wow that's perfect, didn't know that! Thank you :)

**Comment by mhevery** [comment] 2018-05-15 22:55
closing, works as intended

**Closed by mhevery** 2018-05-15 22:55 UTC
Labels: comp: core & compiler

**Comment by doom777** [comment] 2019-06-24 14:45
@trotyl any guidance why using a union type in a ViewModel is a very bad idea?
