### ISSUE TITLE
Misleading NullInjectorError due to exception while creating the injected service

### ISSUE THREAD

**Issue by ptandler** [angular/angular#51676] opened 2023-09-06 14:53 UTC
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

When there is an exception during the creation of a service or component during injection, a `NullInjectorError` is reported:

    NullInjectorError: R3InjectorError(AppModule)[MyFailingService -> MyFailingService -> MyFailingService]:
    NullInjectorError: No provider for MyFailingService!

But this error message is misleading, it should rather tell me that there _is_ a provider, but the creation of the instance has failed. In fact, I spent hours searching for the reason until I noticed this. I really would appreciate an error message that tells me what really happened!

BTW: Why does it says "MyFailingService -> MyFailingService -> MyFailingService"? I really don't understand this.

This simple project tries to inject a service that throws an exception in the constructor:

https://stackblitz.com/github/etalytics/null-injector-error-due-to-exception?file=package.json,src%2Fapp%2Fmy-failing.service.ts

### Please provide a link to a minimal reproduction of the bug

https://github.com/etalytics/null-injector-error-due-to-exception

### Please provide the exception or error you saw

```true
NullInjectorError: R3InjectorError(AppModule)[MyFailingService -> MyFailingService -> MyFailingService]:
    NullInjectorError: No provider for MyFailingService!
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 16.2.1
Node: 18.16.1
Package Manager: pnpm 8.7.4
OS: linux x64

Angular: 16.2.3
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1602.1
@angular-devkit/build-angular   16.2.1
@angular-devkit/core            16.2.1
@angular-devkit/schematics      16.2.1
@angular/cli                    16.2.1
@schematics/angular             16.2.1
rxjs                            7.8.1
typescript                      4.9.5
zone.js                         0.13.1
```

**Comment by jessicajaniuk** [comment] 2023-09-06 15:37
The error you're seeing is because you haven't provided the service to the module or component. You need to add it to the module providers list in your example, and it goes away. So the NullInjectorError is correct since there is nothing provided to inject.

That said, the message is not very clear in this case. We definitely should improve that message.

**Comment by AndrewKushnir** [comment] 2023-09-06 16:48
FYI, there is a PR in the queue to improve an error message (for both not found and cyclic dep situations): PR https://github.com/angular/angular/pull/50902.

**Comment by AndrewKushnir** [comment] 2023-09-07 01:52
Closing this ticket, since the problem was caused by a missing provider in an application. The error message would be improved by PR https://github.com/angular/angular/pull/50902.

**Closed by AndrewKushnir** 2023-09-07 01:52 UTC
Labels: area: core
