### ISSUE TITLE
Error when people write two way data-binding as ([prefix-foo]) rather than [(prefix-foo)]

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#4736] opened 2015-10-14 15:49 UTC
If I write incorrectly, I don't get any warnings or errors. Nothing happens. That is hard to debug.

**Comment by pkozlowski-opensource** [comment] 2015-10-14 15:51
Definitively! This is why we've got an issue for this already: https://github.com/angular/angular/issues/3662

I'm going to close this one as a duplicate of #3662

**Closed by pkozlowski-opensource** 2015-10-14 15:51 UTC
Labels: hotlist: sugar

**Comment by IgorMinar** [comment] 2015-10-14 15:55
thanks!
