### ISSUE TITLE
ngc fails when used with recent tsickle versions

### ISSUE THREAD

**Issue by Kingofjoy** [angular/angular#43220] opened 2021-08-21 06:52 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 6

### Description

I am updating my ui framework library written in angular 6, I am upgrading it from angular 6 to 12. The project uses gulp4 to build (earlier with angular 6 it was using gulp 2.x) . After angular update, the "gulp build" failed with below message

## 🔥 Exception or Error
<pre><code>

[10:35:36] Finished 'inline-resources' after 15 ms
[10:35:36] Starting 'ngc'...
Error: Cannot find module 'tsickle'
Require stack:
- D:\myrops\fm3\myui-framework\node_modules\@angular\compiler-cli\src\main.js
- D:\myrops\fm3\myui-framework\gulpfile.js
- D:\myrops\fm3\myui-framework\node_modules\gulp\node_modules\gulp-cli\lib\shared\require-or-import.js
- D:\myrops\fm3\myui-framework\node_modules\gulp\node_modules\gulp-cli\lib\versioned\^4.0.0\index.js
- D:\myrops\fm3\myui-framework\node_modules\gulp\node_modules\gulp-cli\index.js
- D:\myrops\fm3\myui-framework\node_modules\gulp\bin\gulp.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at D:\myrops\fm3\myui-framework\node_modules\@angular\compiler-cli\src\main.js:104:20
    at D:\myrops\fm3\myui-framework\node_modules\@angular\compiler-cli\src\ngtsc\program.js:261:42
    at ActivePerfRecorder.inPhase (D:\myrops\fm3\myui-framework\node_modules\@angular\compiler-cli\src\ngtsc\perf\src\recorder.js:64:24)
    at NgtscProgram.emit (D:\myrops\fm3\myui-framework\node_modules\@angular\compiler-cli\src\ngtsc\program.js:214:50)
    at Object.performCompilation (D:\myrops\fm3\myui-framework\node_modules\@angular\compiler-cli\src\perform_compile.js:267:29)
    at main (D:\myrops\fm3\myui-framework\node_modules\@angular\compiler-cli\src\main.js:44:36)

[10:35:39] Finished 'ngc' after 2.72 s

</code></pre>

## 🌍 Your Environment

<pre><code>

Angular CLI: 12.0.5
Node: 14.17.4
Package Manager: npm 6.14.14
OS: win32 x64

Angular: 12.0.5
... animations, cli, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.5
@angular-devkit/build-angular   12.0.5
@angular-devkit/core            12.0.5
@angular-devkit/schematics      12.0.5
@schematics/angular             12.0.5
rxjs                            6.6.7
typescript                      4.2.4

</code></pre>

**Anything else relevant?**

1. Post the reported issue, i though i would install tsickle and solve it.
    npm install tscikle, it installed  "tsickle": "^0.43.0".
2. still after npm run build, it returns below error

<pre><code>

 [10:44:24] Starting 'ngc'...
TypeError: host.rootDirsRelative is not a function
    at Object.generateTsMigrationExportsShimFile (D:\myrops\fm3\myui-framework\node_modules\tsickle\out\src\ts_migration_exports_shim.js:20:30)
    at emit (D:\myrops\fm3\myui-framework\node_modules\tsickle\out\src\tsickle.js:149:34)
    at Object.emitWithTsickle (D:\myrops\fm3\myui-framework\node_modules\tsickle\out\src\tsickle.js:65:12)
    at D:\myrops\fm3\myui-framework\node_modules\@angular\compiler-cli\src\main.js:104:39
    at D:\myrops\fm3\myui-framework\node_modules\@angular\compiler-cli\src\ngtsc\program.js:261:42
    at ActivePerfRecorder.inPhase (D:\myrops\fm3\myui-framework\node_modules\@angular\compiler-cli\src\ngtsc\perf\src\recorder.js:64:24)
    at NgtscProgram.emit (D:\myrops\fm3\myui-framework\node_modules\@angular\compiler-cli\src\ngtsc\program.js:214:50)
    at Object.performCompilation (D:\myrops\fm3\myui-framework\node_modules\@angular\compiler-cli\src\perform_compile.js:267:29)
    at main (D:\myrops\fm3\myui-framework\node_modules\@angular\compiler-cli\src\main.js:44:36)
    at D:\myrops\fm3\myui-framework\gulpfile.js:63:3

</code></pre>

*** Package.json ***
<pre><code>

{
  "name": "myui-framework",
  "version": "0.0.0",
  "private": true,
  "dependencies": {
    "@angular/animations": "~12.0.0",
    "@angular/common": "~12.0.0",
    "@angular/compiler": "~12.0.0",
    "@angular/core": "~12.0.0",
    "@angular/forms": "~12.0.0",
    "@angular/localize": "~12.0.0",
    "@angular/platform-browser": "~12.0.0",
    "@angular/platform-browser-dynamic": "~12.0.0",
    "@angular/router": "~12.0.0",
    "@progress/kendo-angular-buttons": "6.2.1",
    "@progress/kendo-angular-charts": "5.2.1",
    "@progress/kendo-angular-common": "2.0.1",
    "@progress/kendo-angular-dateinputs": "5.2.1",
    "@progress/kendo-angular-dropdowns": "5.3.0",
    "@progress/kendo-angular-excel-export": "4.0.1",
    "@progress/kendo-angular-grid": "5.3.1",
    "@progress/kendo-angular-inputs": "7.3.2",
    "@progress/kendo-angular-intl": "3.1.1",
    "@progress/kendo-angular-l10n": "3.0.2",
    "@progress/kendo-angular-label": "3.1.0",
    "@progress/kendo-angular-pdf-export": "3.0.1",
    "@progress/kendo-angular-popup": "4.0.1",
    "@progress/kendo-angular-sortable": "^4.0.3",
    "@progress/kendo-angular-treeview": "5.4.0",
    "@progress/kendo-data-query": "1.5.5",
    "@progress/kendo-drawing": "1.11.0",
    "@progress/kendo-licensing": "1.2.0",
    "core-js": "2.6.12",
    "hammerjs": "2.0.8",
    "rxjs": "6.6.7",
    "web-animations-js": "2.3.2",
    "zone.js": "~0.11.4"
  },
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "gulp build",
    "build:watch": "gulp",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "postinstall": "ngcc"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~12.0.0",
    "@angular/cli": "~12.0.0",
    "@angular/compiler-cli": "~12.0.0",
    "@types/jasmine": "~3.6.0",
    "@types/node": "^12.11.1",
    "codelyzer": "^6.0.0",
    "fs": "0.0.1-security",
    "fs-extra": "^10.0.0",
    "glob": "^7.1.7",
    "gulp": "^4.0.2",
    "gulp-rename": "^2.0.0",
    "gulp-rollup": "^2.17.0",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~6.3.4",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.0.3",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "node-sass": "^6.0.1",
    "node-sass-tilde-importer": "^1.0.2",
    "path": "^0.12.7",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~4.2.3"
  }
}

</code></pre>

**** gulpfile.js ****

<pre><code>

/* eslint-disable */
var gulp = require('gulp'),
  path = require('path'),
  ngc = require('@angular/compiler-cli/src/main').main,
  rollup = require('gulp-rollup'),
  rename = require('gulp-rename'),
  fs = require('fs-extra'),
  //runSequence = require('run-sequence'),
  inlineResources = require('./tools/gulp/inline-resources');

const rootFolder = path.join(__dirname);
const srcFolder = path.join(rootFolder, 'src');
const tmpFolder = path.join(rootFolder, '.tmp');
const buildFolder = path.join(rootFolder, 'build');
const distFolder = path.join(rootFolder, 'dist');

/**
 * 1. Delete /dist folder
 */
gulp.task('clean:dist', async function () {

  // Delete contents but not dist folder to avoid broken npm links
  // when dist directory is removed while npm link references it.
  return fs.emptyDirSync(distFolder);
});

/**
 * 2. Clone the /src folder into /.tmp. If an npm link inside /src has been made,
 *    then it's likely that a node_modules folder exists. Ignore this folder
 *    when copying to /.tmp.
 */
gulp.task('copy:source', function () {
  console.log('copy:source');
  console.log(`${srcFolder}/**/*`);
  console.log(`!${srcFolder}/node_modules`);
  return gulp.src([`${srcFolder}/**/*`, `!${srcFolder}/node_modules`])
    .pipe(gulp.dest(tmpFolder));
    
});

/**
 * 3. Inline template (.html) and style (.css) files into the the component .ts files.
 *    We do this on the /.tmp folder to avoid editing the original /src files
 */
gulp.task('inline-resources', function () {
  return Promise.resolve()
    .then(() => inlineResources(tmpFolder));
});

/**
 * 4. Run the Angular compiler, ngc, on the /.tmp folder. This will output all
 *    compiled modules to the /build folder.
 *
 *    As of Angular 5, ngc accepts an array and no longer returns a promise.
 */
gulp.task('ngc',function () {
  //ngFS is a hack which is introduced during Angular 12 upgrade 
  //Refer: https://github.com/angular/angular/issues/32352#issuecomment-525624772 
  var ngFsUtils = require('@angular/compiler-cli/src/ngtsc/file_system');
  ngFsUtils.setFileSystem(new ngFsUtils.NodeJSFileSystem());
  
  ngc(['--project', `${tmpFolder}/tsconfig.es5.json`]);
  
  return Promise.resolve()
});

/**
 * 5. Run rollup inside the /build folder to generate our Flat ES module and place the
 *    generated file into the /dist folder
 */
gulp.task('rollup:fesm', function () {
  return gulp.src(`${buildFolder}/**/*.js`)
    // transform the files here.
    .pipe(rollup({

      // Bundle's entry point
      // See "input" in https://rollupjs.org/#core-functionality
      input: `${buildFolder}/index.js`,

      // Allow mixing of hypothetical and actual files. "Actual" files can be files
      // accessed by Rollup or produced by plugins further down the chain.
      // This prevents errors like: 'path/file' does not exist in the hypothetical file system
      // when subdirectories are used in the `src` directory.
      allowRealFiles: true,

      // A list of IDs of modules that should remain external to the bundle
      // See "external" in https://rollupjs.org/#core-functionality
      external: [
        '@angular/core',
        '@angular/common'
      ],

      output: {
        // Format of generated bundle
        // See "format" in https://rollupjs.org/#core-functionality
        format: 'es'
      }
    }))
    .pipe(gulp.dest(distFolder));
});

/**
 * 6. Run rollup inside the /build folder to generate our UMD module and place the
 *    generated file into the /dist folder
 */
gulp.task('rollup:umd', function () {
  return gulp.src(`${buildFolder}/**/*.js`)
    // transform the files here.
    .pipe(rollup({

      // Bundle's entry point
      // See "input" in https://rollupjs.org/#core-functionality
      input: `${buildFolder}/index.js`,

      // Allow mixing of hypothetical and actual files. "Actual" files can be files
      // accessed by Rollup or produced by plugins further down the chain.
      // This prevents errors like: 'path/file' does not exist in the hypothetical file system
      // when subdirectories are used in the `src` directory.
      allowRealFiles: true,

      // A list of IDs of modules that should remain external to the bundle
      // See "external" in https://rollupjs.org/#core-functionality
      external: [
        '@angular/core',
        '@angular/common'
      ],

      output: {
        // The name to use for the module for UMD/IIFE bundles
        // (required for bundles with exports)
        // See "name" in https://rollupjs.org/#core-functionality
        name: 'lib',

        // See "globals" in https://rollupjs.org/#core-functionality
        globals: {
          typescript: 'ts'
        },

        // Format of generated bundle
        // See "format" in https://rollupjs.org/#core-functionality
        format: 'umd',

        // Export mode to use
        // See "exports" in https://rollupjs.org/#danger-zone
        exports: 'named'
      }

    }))
    .pipe(rename('lib.umd.js'))
    .pipe(gulp.dest(distFolder));
});

/**
 * 7. Copy all the files from /build to /dist, except .js files. We ignore all .js from /build
 *    because with don't need individual modules anymore, just the Flat ES module generated
 *    on step 5.
 */
gulp.task('copy:build', function () {
  return gulp.src([`${buildFolder}/**/*`, `!${buildFolder}/**/*.js`])
    .pipe(gulp.dest(distFolder));
});

/**
 * 8. Copy package.json from /src to /dist
 */
gulp.task('copy:manifest', function () {
  return gulp.src([`${srcFolder}/package.json`])
    .pipe(gulp.dest(distFolder));
});

/**
 * 9. Copy README.md from / to /dist
 */
gulp.task('copy:readme', function () {
  return gulp.src([path.join(rootFolder, 'README.MD')])
    .pipe(gulp.dest(distFolder));
});

/**
 * 10. Delete /.tmp folder
 */
gulp.task('clean:tmp', async function () {
  return deleteFolder(tmpFolder);
});

/**
 * 11. Delete /build folder
 */
gulp.task('clean:build', async function () {
  return deleteFolder(buildFolder);
});

gulp.task('compile',  gulp.series(
    'clean:dist',
    'copy:source',
    'inline-resources',
    'ngc',
    'rollup:fesm',
    'rollup:umd',
    'copy:build',
    'copy:manifest',
    'copy:readme',
    'clean:build',
    'clean:tmp',
    function (err) {
      if (err) {
        console.log('ERROR:', err.message);
        deleteFolder(distFolder);
        deleteFolder(tmpFolder);
        deleteFolder(buildFolder);
      } else {
        console.log('Compilation finished succesfully');
      }
    }
)
);

/**
 * Watch for any change in the /src folder and compile files
 */
gulp.task('watch', async function () {
  gulp.watch(`${srcFolder}/**/*`, ['compile']);
});

gulp.task('clean',gulp.series('clean:dist', 'clean:tmp', 'clean:build'));

// gulp.task('build', async function (callback) {
//   console.log('inside gulp.task build');
//   gulp.series('clean', 'compile', callback);
// });

gulp.task('build', gulp.series('clean', 'compile'));

gulp.task('build:watch', async function (callback) {
  gulp.series('build', 'watch', callback);
});

gulp.task('default', gulp.series('build:watch'));

/**
 * Deletes the specified folder
 */
function deleteFolder(folder) {
  return fs.removeSync(folder);
}

</code></pre>

Thanks in advance...!

**Comment by JoostK** [comment] 2021-08-21 08:58
Transferring to the main FW repo as the CLI is not being used.

I would strongly recommend not to use tsickle at this point. It was used for libraries a couple of years ago but that has not been the case since v10 of Angular.

I suspect that you have `"annotateForClosureCompiler": true` configured as an `"angularCompilerOption"` in one of the tsconfig files. That flag should be removed, which causes tsickle to no longer be used.

That said, if you continue to have problems then I would recommend to maybe take a more granular approach to updating, i.e. one version at a time. When using the CLI you get all sorts of automatic migrations when updating to a new major, but using custom tooling that is not being done. Update steps can be found on [update.angular.io](http://update.angular.io). Alternatively, you may want to consider to start adopting the CLI to take care of everything, as that will make updates a lot easier going forward.

**Comment by JoostK** [comment] 2021-08-21 09:12
The tsickle failure appears to be a compatibility issue with how compiler-cli invokes tsickle, where the provided host is not up-to-date with the latest tsickle requirements anymore.

**Comment by Kingofjoy** [comment] 2021-08-21 17:02
1. Thank you for the response @JoostK 

2. I set the flag as you recommended,
`angularCompilerOptions": {
    "annotateForClosureCompiler": false,
    "strictMetadataEmit": true,
    "skipTemplateCodegen": true,
    "flatModuleOutFile": "myui-framework.js",
    "flatModuleId": "myui-framework",
    "enableIvy" : true
  }`

3. But the output folder i.e. build folder is not generated :(
    Am i  missing anything?

<pre>
<code>
> gulp build

[22:28:44] Using gulpfile D:\myrops\fm3\myui-framework\gulpfile.js
[22:28:44] Starting 'build'...
[22:28:44] Starting 'clean'...
[22:28:44] Starting 'clean:dist'...
[22:28:44] Finished 'clean:dist' after 913 ?s
[22:28:44] Starting 'clean:tmp'...
[22:28:44] Finished 'clean:tmp' after 853 ?s
[22:28:44] Starting 'clean:build'...
[22:28:44] Finished 'clean:build' after 397 ?s
[22:28:44] Finished 'clean' after 2.96 ms
[22:28:44] Starting 'compile'...
[22:28:44] Starting 'clean:dist'...
[22:28:44] Finished 'clean:dist' after 204 ?s
[22:28:44] Starting 'copy:source'...
copy:source
D:\myrops\fm3\myui-framework\src/**/*
!D:\myrops\fm3\myui-framework\src/node_modules
[22:28:44] Finished 'copy:source' after 91 ms
[22:28:44] Starting 'inline-resources'...
[22:28:44] Finished 'inline-resources' after 17 ms
[22:28:44] Starting 'ngc'...
ngc start
ngc done
[22:28:47] Finished 'ngc' after 2.83 s
[22:28:47] Starting 'rollup:fesm'...
'@progress/kendo-angular-inputs' is imported by build\app\Module\kendo-export\kendo-export.module.js, but could not be resolved – treating it as an external dependency
'@progress/kendo-angular-dropdowns' is imported by build\app\Module\kendo-export\kendo-export.module.js, but could not be resolved – treating it as an external dependency
[22:28:47] Finished 'rollup:fesm' after 68 ms
[22:28:47] Starting 'rollup:umd'...
'@progress/kendo-angular-inputs' is imported by build\app\Module\kendo-export\kendo-export.module.js, but could not be resolved – treating it as an external dependency
'@progress/kendo-angular-dropdowns' is imported by build\app\Module\kendo-export\kendo-export.module.js, but could not be resolved – treating it as an external dependency
No name was provided for external module '@angular/core' in output.globals – guessing 'i0'
No name was provided for external module '@angular/common' in output.globals – guessing 'common'
No name was provided for external module '@progress/kendo-angular-inputs' in output.globals – guessing 'kendoAngularInputs'
No name was provided for external module '@progress/kendo-angular-dropdowns' in output.globals – guessing 'kendoAngularDropdowns'
[22:28:47] Finished 'rollup:umd' after 21 ms
[22:28:47] Starting 'copy:build'...
[22:28:47] Finished 'copy:build' after 20 ms
[22:28:47] Starting 'copy:manifest'...
[22:28:47] Finished 'copy:manifest' after 4.38 ms
[22:28:47] Starting 'copy:readme'...
[22:28:47] Finished 'copy:readme' after 8.31 ms
[22:28:47] Starting 'clean:build'...
[22:28:47] Finished 'clean:build' after 7.24 ms
[22:28:47] Starting 'clean:tmp'...
[22:28:47] Finished 'clean:tmp' after 311 ?s
[22:28:47] Starting '<anonymous>'...
ERROR: undefined
[22:28:47] The following tasks did not complete: build, compile, <anonymous>
[22:28:47] Did you forget to signal async completion?
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! myuiweb-framework@0.0.0 build: `gulp build`
npm ERR! Exit status 1

</code>
</pre>

**Comment by JoostK** [comment] 2021-08-21 19:41
I'm afraid that is not something I can help you with.

**Comment by jessicajaniuk** [comment] 2022-03-14 23:44
I'm sorry but this issue is not caused by Angular. We do not support the closure libraries within Angular.

**Closed by jessicajaniuk** 2022-03-14 23:44 UTC
Labels: comp: compiler, P5
