### ISSUE TITLE
bug: re-hydrating a DynamicComponent>Component>Component causes errors in bindings

### ISSUE THREAD

**Issue by ajoslin** [angular/angular#1201] opened 2015-04-01 22:09 UTC
This is a complicated bug (**demo at the bottom**).

I have an array. I push and pop the class `MyComponent` to and from the array.

I `*for` loop through the array, and create a DynamicComponent `my-dynamic` for each item in the array.

Then, I use the DynamicComponent to instantiate an instance of `MyComponent`, matching the item in the array:

```html
    <my-dynamic *for="#item of stack"
      [component]="item">
    </my-dynamic>
```

MyComponent has a child which has a binding: 

```html
<child foo="text"></child>
```

An error happens when I do the following:

```js
// let the for loop instantiate the DynamicComponent, which instantiates MyComponent, 
// which instantiates the ChildComponent
stack.push(MyComponent)

// let the for loop remove the component
stack.pop()

// Now it errors on something  about the binding on the ChildComponent. Rehydration problem?
stack.push(MyComponent)
```

Demo: 
http://plnkr.co/edit/FdMPZV6NEIl5zse22YIZ?p=preview

Open the console, then press Push, then Pop, then Push again. It throws an error on the second push.

**Comment by SekibOmazic** [comment] 2015-04-01 22:32
+1 for this.

**Comment by naomiblack** [comment] 2015-04-07 16:19
@pkozlowski-opensource @mhevery  I'm pulling this back into M7 due to user pain. Do we have a feel for effort to address? Should we look at this as part of M7?

**Comment by pkozlowski-opensource** [comment] 2015-04-07 17:09
@naomiblack I'm not too familiar with this part of the code so it is hard for me to estimate the effort. If anyone more familiar with dynamic components could pair with me for like 30 minutes, this would speed up things, for sure.

**Comment by mhevery** [comment] 2015-04-07 17:10
@rkirov or @tbosch should be able to help with this

**Comment by pkozlowski-opensource** [comment] 2015-04-08 13:55
Here is the Andy's plunker updated to the latest ng2: http://plnkr.co/edit/BqWZDWtnLSNtYORocZyQ?p=preview - the issue is still here...

From a brief look something doesn't get dehydrated properly as the change detector has stale info pointing to non-existing directives.

**Comment by pkozlowski-opensource** [comment] 2015-04-08 14:58
So, what is going on here is that a list of view's `componentChildViews` is growing each time we invoke a `component` setter on 'MyDynamic'. This triggers new compilation of the `MyDynamic` component and since we are going through a loader and _caching View instances_ we are growing a list of  `componentChildViews` each time we invoke `createComponent` [here](https://github.com/angular/angular/blob/41262f42650cfbf8fdd494120817da30af9fb80f/modules/angular2/src/core/compiler/private_component_location.js#L31).

Now, at this point I'm not sure if this is incorrect usage of the dynamic component feature or sth is missing in the compiler, but in the nutshell the situation boils down to:
* we cache view instances
* we dynamically grow `componentChildViews` for a given View 
* there is nothing that would clean-up the growing list

So I'm not sure if the pb is that we are growing the list unnecessary or not cleaning it up properly...

**Comment by tbosch** [comment] 2015-04-08 15:42
I think childComponentViews already contains an entry for every bound element, I.e. We should not grow it but just set values at indices. And destroy a maybe existing instance at that place

**Comment by pkozlowski-opensource** [comment] 2015-04-08 15:50
@tbosch hmm, I think I will need you to elaborate....
>  think childComponentViews already contains an entry for every bound element

I don't think this is the case for dynamically created sub-views. In Andy's plunk `componentChildViews` is empty initially and then it grows each time we load `MyDynamic`...

I'm afraid I will need more guidance here....

**Comment by pkozlowski-opensource** [comment] 2015-04-08 17:21
So, it looks like there is a pending PR #1261 that changes the code in question quite substantially. I'm going to wait for the #1261 to be merged (seems like it is close to landing) and then re-test this scenario (will probably require changes to the initial plunk).

**Comment by tbosch** [comment] 2015-04-10 04:06
@pkozlowski-opensource Your analysis of the bug is correct. We somehow need to mark the dynamically added components so we can clean them up in dehydrate.

Note that we now have `componentChildViews` in the App View and the Render View, so fixes need to be applied to both.

Please ping me on Slack if you would like to discuss it.

**Comment by ajoslin** [comment] 2015-04-10 12:46
Thanks Tobias & Pawel. Let me know if you have more questions about my use case or need more testing.

**Comment by pkozlowski-opensource** [comment] 2015-04-10 12:49
@ajoslin I think that the use-case is clear and valid. I'm just looking at the code changes after f45281a10afbbd6052427bd358e1d337fdb78831 landed as now we've got a new `DynamicComponentLoader` service to dynamically load components. But even with this new service I believe that the bug is still there (trying to put together a new reproduce scanario)

**Comment by pkozlowski-opensource** [comment] 2015-04-13 12:40
Here is a smaller reproduce scenario with a plunker updated to the latest code from master:
http://plnkr.co/edit/8DZeHXg5bayUGx4C9abo?p=preview

The bug is still here and the root cause is the [same](https://github.com/angular/angular/issues/1201#issuecomment-90941944)

@vsavkin @tbosch could we chat at one point about the best way of fixing this one. @vsavkin I can see that you've left some comments about this case: https://github.com/angular/angular/blob/daf0f472b3a37d3dc158c0e6bb5c76035bc67037/modules/angular2/src/core/compiler/dynamic_component_loader.js#L48-L56

**Comment by vsavkin** [comment] 2015-04-13 15:37
@pkozlowski-opensource sure, we can talk about the fix today. I have a good idea of how to fix it on the app side. I am not very familiar with the render layer though. But @tbosch can help us there.

**Comment by tbosch** [comment] 2015-04-13 16:43
Talked to @pkozlowski-opensource:

1. Make `View.viewContainers` array a sparse array (i.e. has an entry for every bound element)
1. Have another array that says for every index whether we have a static / dynamic / no component there (true / false/ null)
1. Change `View.addComponentView()` into `View.setComponentView(childComponentView, dynamic:boolean)
1. Change ViewFactory to also use `View.setComponentView`
1. Durgin View.dehydrate clear the dynamic views and dehydrate them as well.

==> No one modified View directly but only via these methods

**Comment by tbosch** [comment] 2015-04-13 16:44
This might slow things down, but we need a single Array of Objects that combines the already existing Arrays anyway, which would make this not a performance penalty.

**Comment by vsavkin** [comment] 2015-04-13 16:52
>> Have another array that says for every index whether we have a static / dynamic / no component there (true / false/ null)

@tbosch I am not sure why we need this array. We can derive this info from the list of element injectors.

**Comment by tbosch** [comment] 2015-04-13 18:39
@vsavkin Can we already, or would we need another flag there?

**Comment by tbosch** [comment] 2015-04-13 18:41
On the render side, we probably do need this array, as we don't have ElementInjectors there...

While thinking about this, we probably want to store this information in the `ProtoView` instead of the `View` itself, as it won't change!

**Closed** 2015-04-15 19:53 UTC
