### ISSUE TITLE
Radio groups keyboard navigation (tab) skips next groups

### ISSUE THREAD

**Issue by darbio** [angular/angular#19542] opened 2017-10-04 03:33 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
When you make a form group with a number of radio button groups, using the keyboard to navigate does not work. The keyboard treats all radio groups as one and tabs to the next element after the radio groups. When radios have the `name` attribute set explicitly, keyboard navigation works (but reactive forms are broken).

## Expected behavior
When radio buttons have the same name, keyboard navigation (tab) should jump to the next radio group as per [w3c guidelines](https://www.w3.org/wiki/RadioButton)

## Minimal reproduction of the problem with instructions
http://plnkr.co/edit/BA4Lshk6xthSII6zMKyj

Group 1 and 2 are reactive forms examples (displays unwanted behaviour).
Group 3 is plain HTML (displays proper behaviour)

## What is the motivation / use case for changing the behavior?
Forms should be accessible

## Environment
Angular version: 4.4.4

Browser:
- [x] Chrome (desktop) version XX
- [x] Safari (desktop) version XX
- [ ] Firefox version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
Others:
MacOS Sierra

**Comment by kara** [comment] 2017-11-28 23:38
If you want your radio buttons to be accessible, it's expected that you would use the `name` attribute along with `formControlName` to get the native accessible behavior. 

You mentioned that adding `name` broke reactive forms somehow, but it seems to work properly when testing it over here. Since I can't reproduce your issue,  I'm closing this issue for now as not actionable. If you're still seeing issues when you add `name`, please open a new issue with a plunker repro and a description of what specifically isn't working.

**Closed by kara** 2017-11-28 23:38 UTC
Labels: comp: forms

**Comment by farismohammed** [comment] 2018-10-23 04:42
use `[attr.name]=""` for grouping your radio buttons.
