### ISSUE TITLE
Page Not Found 

### ISSUE THREAD

**Issue by mamjerez** [angular/angular#52837] opened 2023-11-12 14:36 UTC
### Describe the problem that you experienced

https://angular.dev/tools/cli/setup-local

See [Angular's version compatibility](https://angular.dev/versions) guide for more information.

### Enter the URL of the topic with the problem

https://angular.dev/versions

**Comment by JoostK** [comment] 2023-11-12 14:42
Thanks for the report, this is a duplicate of #52562 and has since been addressed, but is pending a deployment.

**Closed by JoostK** 2023-11-12 14:42 UTC
