### ISSUE TITLE
Broken Link in Documentation: pipes API Redirects to Page Not Found

### ISSUE THREAD

**Issue by EshanDangwal** [angular/angular#54049] opened 2024-01-24 12:43 UTC
### Describe the problem that you experienced

The link to the pipes API documentation in the webpage redirects to a "Page Not Found" error. The expected behaviour is to navigate to the correct documentation page at https://angular.dev/api/common#pipes. This issue hinders users from accessing the relevant information about built-in pipes.

### Enter the URL of the topic with the problem

https://angular.dev/guide/pipes

### Describe what you were looking for in the documentation

List of built-in pipes

### Describe the actions that led you to experience the problem

The problem arose when attempting to access the full list of built-in pipes in the API documentation from the provided link on the Pipes overview webpage. In the **NOTE** section below **Built-in Pipes**, there is a link for checking the list. Instead of being directed to the expected documentation page (https://angular.dev/api/common#pipes), a "Page Not Found" error was encountered. This issue led to a disruption in the user experience as it prevented users from accessing the necessary information about built-in pipes.

### Describe what you want to experience that would fix the problem

I would like to experience a resolution to the issue by having the provided link in the NOTE section below Built-in Pipes on the Pipes overview webpage correctly direct users to the intended API documentation page for built-in pipes at https://angular.dev/api/common#pipes. The expected behaviour is that users should be able to access the full list of built-in pipes without encountering any "Page Not Found" errors, ensuring a seamless and uninterrupted user experience.

### Add a screenshot if that helps illustrate the problem

1. **Screenshot of Source of Error:**
   ![Screenshot of Source of Error](https://github.com/angular/angular/assets/118157050/9ac9b17f-4306-471c-93e6-c61409ab8dcd)
   - *Description:* A screenshot showing the source of the error, possibly highlighting the incorrect link or relevant error message on the webpage.

2. **Screenshot of Page Not Found:**
![Screenshot of Page Not Found](https://github.com/angular/angular/assets/118157050/548b20b0-5f2c-4c70-868f-1cf3afff980a)
- *Description:* A screenshot depicting the "Page Not Found" error encountered when attempting to access the below link.
**Link:** [https://angular.dev/api/common#pipes](https://angular.dev/api/common#pipes)

### If this problem caused an exception or error, please paste it here

```false

```

**Comment by JoostK** [comment] 2024-01-24 13:29
Thanks for the report, closing as duplicate of https://github.com/angular/angular/issues/52968. The fix is still awaiting deployment.

**Closed by JoostK** 2024-01-24 13:29 UTC
