### ISSUE TITLE
Nested forms using ControlValueAccessor and Validator

### ISSUE THREAD

**Issue by r-shakeri** [angular/angular#38482] opened 2020-08-16 12:05 UTC
# 🐞 bug report

### Description

 on creating nested forms using `ControlValueAccessor` and `Validator` interfaces, i see when i write a value in parent form, validate function in child form gets run twice! when i write in input by hand every thing is fine and `validate` method runs one time but when i programatically writes into input using submit button for example, `validate` method runs twice. please check the code i prepared.

## 🔬 Minimal Reproduction

 https://stackblitz.com/edit/angular-ivy-bqj4ie?file=src%2Fapp%2Fhello.component.ts

## 🌍  Your Environment

**Angular Version:**
<pre><code>

 Angular CLI: 9.1.8
Node: 10.13.0
OS: win32 x64

Angular: 9.1.11
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, platform-server, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.8
@angular-devkit/build-angular     0.901.8
@angular-devkit/build-optimizer   0.901.8
@angular-devkit/build-webpack     0.901.8
@angular-devkit/core              9.1.8
@angular-devkit/schematics        9.1.8
@angular/cli                      9.1.8
@ngtools/webpack                  9.1.8
@nguniversal/builders             9.1.1
@nguniversal/common               9.1.1
@nguniversal/express-engine       9.1.1
@schematics/angular               9.1.8
@schematics/update                0.901.8
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0

</code></pre>

**Comment by sonukapoor** [comment] 2020-08-20 13:32
@r-shakeri I have traced this through and here is what happens when you click the submit button. The following functions are called in the below order:

1. `FormGroup.setValue`
2. `FromControl.setValue`
3. `OnChange`
4. `HelloComponent.writeValue`
5. This will call the setter of `value` in the `HelloComponent`
6. This calls the value setter `FormGroup.setValue` which then calls the `userNameForm.setValue` again, causing the validation to run twice. 

Your value setter is basically an extension of the `writeValue` method. According to the docs, the `writeValue` is used to _write a value to the element_. The [docs](https://angular.io/api/forms/ControlValueAccessor#write-a-value-to-the-element) show that you can use the `renderer`.

```typescript
writeValue(value: any): void {
  this._renderer.setProperty(this._elementRef.nativeElement, 'value', value);
}
```

However, you can also simply use another variable and bind the value to the input. Something like this:

```typescript

export class HelloComponent implements OnInit ... {
  inputValue: any;

  set value(value: {userName: string}) {
    this.inputValue = value.userName;
  }
  ...
}
```

Your input in the template would change to:

```html
<input ... 
  formControlName="userName"  
  [value]="inputValue" 
  required/>
```

Here is your stackblitz with the above-modified changes:

https://stackblitz.com/edit/angular-ivy-mji2zw?file=src%2Fapp%2Fhello.component.ts

Let us know if this resolves the issue.

**Comment by r-shakeri** [comment] 2020-08-20 15:17
look i did console log for you, and the order of things does not go like that... however number 5 that you mentioned above is setting a defined component property `value` and no more if i comment this line `this.userNameForm.setValue(value)` in it. so there is no validation checking until i put this line in it. and if put it, there is one validation checking until now, not twice!

**Comment by sonukapoor** [comment] 2020-08-20 15:36
@r-shakeri I tried the above-posted stackblitz again and when I press the submit button, I can see that the validation happens. Are you seeing the same behaviour?

**Comment by r-shakeri** [comment] 2020-08-20 16:17
@sonukapoor  no think you tried your link that is not my issue. my link prints these lines in console:

1. writeValue {userName: "0011rsh"}
2. valueChanges child {userName: "0011rsh"}
3. userNameForm validation true
4. valueChanges parent {userName: {…}}
5. userNameForm validation true

**Comment by sonukapoor** [comment] 2020-08-20 16:21
> @sonukapoor no i think you tried your link that is not my issue. my link prints these lines in console:

You have used this link https://stackblitz.com/edit/angular-ivy-mji2zw?file=src%2Fapp%2Fhello.component.ts?

**Comment by r-shakeri** [comment] 2020-08-20 16:23
@sonukapoor no this is yours, with `inputValue`
my link is [https://stackblitz.com/edit/angular-ivy-bqj4ie?file=src%2Fapp%2Fhello.component.ts](url)

**Comment by samyue** [comment] 2020-08-21 04:51
test

**Comment by AndrewKushnir** [comment] 2020-08-24 23:55
Hi @r-shakeri, thanks for providing a repro.

I've performed additional investigation and it looks like the problem appears due to the following code (as @sonukapoor mentioned above):

```
  set value(value: {userName: string}) {
    this.userNameForm.setValue(value);
  }
```

Which triggers the `valueChanges` to emit new value and the following callback to be executed:

```
  this.subscription = this.userNameForm.valueChanges.subscribe(value => {
    console.log('valueChanges child', value);
    this.onChange(value);
    this.onTouched();
  });
```

as a result, calling the `onChange` function triggers validator to be executed for the second (unnecessary) time.

I believe the solution is to avoid emitting an event (by setting the `emitEvent` flag to `false`) once the value is set programmatically here:

```
  set value(value: {userName: string}) {
    this.userNameForm.setValue(value, {emitEvent: false});
  }
```

This should avoid triggering the second round of validation and at the same time validation would also be triggered once you change the value of the input box.

I think this case is similar to the one described in #37954, so you can check the solution in that thread as well.

I'm closing this ticket since the problem is specific to the implementation of the custom ControlValueAccessor and there are no action items for the framework itself.

Thank you.

**Closed by AndrewKushnir** 2020-08-24 23:55 UTC
Labels: comp: forms, forms: ControlValueAccessor, forms: validators, state: in investigation, state: works-as-expected

**Comment by r-shakeri** [comment] 2020-08-27 19:07
@AndrewKushnir hello, thanks for response but there is still a dark hole there.
at first calling the `onChange` function by core after setting value of the form is a benefit that i don't want to just avoid it! so yes i can do some work around like setting the `emitEvent` flag to false and making a method of the component that contains what ever is inside the `valueChanges` of the `this.userNameForm` and call it in as a callback of `valueChanges.subscribe` and after `this.userNameForm.setValue(value, {emitEvent: false});` .
but i want to know why the second validity gets fired? i think it's not correct because when i comment `this.onChange(value);` from `this.userNameForm.valueChanges.subscribe` everything is fine and there is just one time validity.
i also thought ok we can have 2 validation but the second one can be for parent form not agan the same child form!!!
so i think there is still something wrong with it or there is a dark hole that i don't know about functionality between parent and child forms...
and as the last notice, it's not good to just close my issue whenever u didn't hear me or at least make a chance of opportunity for a few days!!!

**Comment by AndrewKushnir** [comment] 2020-08-27 23:10
Hi @r-shakeri,

Thanks for the reply, let me provide some additional information.

When the button is clicked, the following actions happen:

- [in outer form] the `onSubmit` function is called, which calls the `setValue` on the outer FormGroup (the `userNameUpdateForm` one)
- [in outer form] as a result, the `setValue` is called for all child components in that form group (defined while calling the `this.formBuilder.group` method), including the `<hello formControlName="userName"></hello>` one, which has a value accessor
  - [in value accessor] as a part of the process to set control value, the `writeValue` function of the value accessor is called (i.e. `HelloComponent.writeValue`). This call triggers the `setValue` call on the inner FormGroup (the `userNameForm` one). Setting the value triggers an event to be emitted into the `valueChanges` observable, since the call has no `emitEvent: false` flag.
  - [in value accessor] the event in the `valueChanges` triggers the callback defined while calling the `this.userNameForm.valueChanges.subscribe` function, thus causing the `onChange` callback to be executed. This `onChange` function invokes internal logic to update control value and triggers validators (this is where the `HelloComponent.validate` function is called for the first time).
- [in outer form] the value is now set for the  `<hello formControlName="userName"></hello>` component and the validators are triggered for that component (this is where the `HelloComponent.validate` function is called the second time)

So it looks like there is an unnecessary validator call happens in the inner form that can be avoided by adding the `emitEvent: false` flag to the `setValue` call as I mentioned in my previous message.

I closed this ticket because there are no action items for the framework and the solution was provided. More information on why we close tickets that are not bug reports of feature requests [can be found here](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question).

Thank you.
