### ISSUE TITLE
HashTable entry of SimpleChanges can be undefined

### ISSUE THREAD

**Issue by jekru** [angular/angular#48752] opened 2023-01-16 19:45 UTC
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

With the lifecycle hook [OnChanges](https://angular.io/api/core/OnChanges), it is possible to receive the changed properties of a component. `SimpleChanges` is the type passed to the `ngOnChanges()` hook.

```ts
public ngOnChanges(changes: SimpleChanges): void
```

The interface `SimpleChanges` looks like this:

```ts
/**
 * A hashtable of changes represented by {@link SimpleChange} objects stored
 * at the declared property name they belong to on a Directive or Component. This is
 * the type passed to the `ngOnChanges` hook.
 *
 * @see `OnChanges`
 *
 * @publicApi
 */
export declare interface SimpleChanges {
    [propName: string]: SimpleChange;
}
```

`SimpleChanges` is defined as `{ [propName: string]: SimpleChange; }`. This implies that every key of the hash table has a value of type `SimpleChange`, even if the entry does not exist.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-ebztsk

### Please provide the exception or error you saw

- **TypeError**

```ts
public ngOnChanges(changes: SimpleChanges): void {
  // 'whatever' does not exist in this component
  // But it is possible to access changes['whatever'].currentValue without typescript error
  const whatever = changes['whatever'];
  console.log('whatever', whatever.currentValue);
}
```

This will result in `ERROR TypeError: Cannot read properties of undefined (reading 'currentValue')`. `changes['whatever']` does not exist and is `undefined` and therefore it is not possible to access `currentValue`.

- **Conflict with `@typescript-eslint/no-unnecessary-condition`**

The definition of `SimpleChanges` implies that for every key, there exists an entry in the hash table. Therefore, the `no-unnecessary-condition` will always note `Unnecessary conditional, value is always truthy.` But this is not the case, it can be `undefined`.

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.0.0
Node: 16.14.2
Package Manager: npm 8.7.0
OS: win32 x64

Angular: 15.0.0
... cdk, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
... service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1500.0
@angular-devkit/build-angular   15.0.0
@angular-devkit/core            15.0.0
@angular-devkit/schematics      15.0.0
@schematics/angular             15.0.0
rxjs                            7.5.7
typescript                      4.8.4
```

### Anything else?

I would propose to add `undefined` as possible value to the hash map.

```ts
export declare interface SimpleChanges {
    [propName: string]: SimpleChange | undefined;
}
```

**Comment by JoostK** [comment] 2023-01-16 20:59
This is basically a duplicate of microsoft/TypeScript#13778; a language quirk more so than an Angular bug.

**Comment by jekru** [comment] 2023-01-17 10:57
> This is basically a duplicate of [microsoft/TypeScript#13778](https://github.com/microsoft/TypeScript/issues/13778); a language quirk more so than an Angular bug.

I understand the argument that this should be handled by TypeScript. But the reality is that `noUncheckedIndexedAccess` is not setup by default in the typescript compiler options.

**Comment by pkozlowski-opensource** [comment] 2023-02-08 15:57
@jekru I hear you but I don't think we want to duplicate TypeScript documentation on the Angular side. `noUncheckedIndexedAccess` is the way to go.

**Closed by pkozlowski-opensource** 2023-02-08 15:57 UTC
Labels: area: core
