### ISSUE TITLE
elements: change detection breaks in *ngFor loop

### ISSUE THREAD

**Issue by remackgeek** [angular/angular#23841] opened 2018-05-11 00:33 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

I create Element with an exposed property and an *ngFor in the template. 
When setting the property via JavaScript, it breaks the the change detection/rendering of the *ngFor

## Expected behavior

Change detection in the ngFor works the same as an unrolled loop.

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/angular-apfxkt?file=src%2Findex.html

in the first row, 
1) click on the first dot
2) click on the give max rating" button
3) click on the 4th dot 
Error: 5th dot remains red

Note that the second row,  with an unrolled loop, works as expected
## Environment

<pre><code>
Angular version: 6.0.0

Browser:
- [x ] Chrome (desktop) version 66
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by robwormald** [comment] 2018-05-11 06:00
This is related to ZoneJS - the point at which it starts failing is dropping out of the angular zone, and thus not running change detection. It's a bug, but in general, for such elements to be useful outside an Angular context, you should not rely on ZoneJS, and instead handle change detection yourself.

Also - most native DOM controls (eg, `<input>`) don't fire an event when the value is changed from the outside world, so you probably should not trigger that side effect from the input setter.

cc @andrewseguin - we should investigate the root cause here, but I don't believe we should make any special affordances for ZoneJS in the Elements API.

**Comment by robwormald** [comment] 2018-05-11 06:05
@remackgeek reworked version - https://stackblitz.com/edit/angular-royabn?file=src/index.html

**Comment by JiaLiPassion** [comment] 2018-05-13 16:31
@robwormald , I think the reason is here, https://github.com/angular/angular/blob/master/packages/elements/src/create-custom-element.ts#L189

When set property from outside of `Elements`, it will be in `<root> zone`, and the `render` logic will call `addEventListener` on the `updated` rating items. And those `eventHandler callback` will be in `<root>` zone, so should we guarantee when `setInputValue`, everything should be in `ngZone`?

I can make a PR for it if this is a correct solution , please review.

**Comment by JiaLiPassion** [comment] 2018-05-14 04:59
@robwormald , I have created a PR, #23885 to fix this one and another performance issue, please check the idea is ok or not, thank you.

**Comment by robwormald** [comment] 2018-05-14 23:59
@JiaLiPassion seems like a reasonable idea to me - @mhevery might have more thoughts.

**Comment by JiaLiPassion** [comment] 2018-05-15 02:31
@robwormald , got it, thank you!

**Comment by geocine** [comment] 2018-05-23 02:56
currently this is how I do it. a reworked version of @remackgeek 

https://stackblitz.com/edit/angular-royabn?file=src%2Findex.html

I use `ElementRef` and call `setAttribute` inside the method

**Comment by joshorvis** [comment] 2018-06-09 14:04
I'm fairly new to Angular, but I ran into this problem recently trying to use packaged ng6 elements in an ng1 app, and was able to resolve it by calling ngOnChanges in each of the affected components.  Not sure why, but seems like having this method present (even if it does nothing) seems to get my changes showing again.

**Comment by gonadn** [comment] 2018-12-31 18:15
Try this solution:  described in this [article](https://github.com/angular/angular/issues/26158)
It SOLVED my issues with *ngFor, and i had same issue as you are describing....

elements-zone-strategy:
This library provides an Angular Elements Strategy Factory which always runs in the NgZone, allowing automatic change detection

Solution fixed my issues is:
install the package:
`npm i --save elements-zone-strategy`

use the new strategy in "app.module.ts":
`import { ElementZoneStrategyFactory } from 'elements-zone-strategy';

const strategyFactory = new ElementZoneStrategyFactory(HelloComponent, this.injector);
const helloElement = createCustomElement(HelloComponent, { injector: this.injector, strategyFactory });
customElements.define('my-hello', helloElement)`

**Comment by gkalpak** [comment] 2020-06-01 14:44
Closing as a duplicate of #24181, since it has the same root cause: Not ensuring Angular elements operations (such as emitting events) happens inside the Angular zone.

See #24181 for more details (and available work-arounds).

**Closed by gkalpak** 2020-06-01 14:44 UTC
Labels: comp: elements, freq2: medium, severity2: inconvenient, type: bug/fix
