### ISSUE TITLE
Angular cannot render variables with diacritics

### ISSUE THREAD

**Issue by Floby** [angular/angular#37112] opened 2020-05-14 17:09 UTC
# 🐞 bug report

### Affected Package
I believe the issue is caused by `@angular/core`, or maybe `@angular/compiler` if that's where the parsing of templates happens.

### Is this a regression?

No.

### Description

javascript expressions which contain letters with diacritics in templates are not parsed correctly and cause the rendering or the compilation to fail. Yet many accented characters are valid characters to use in symbols in both javascript and typecript. Sometimes API include such keys in their payload which in turn becomes impossible to display directly.

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-bpdx9t

## 🔥 Exception or Error
<pre><code>
Error in /turbo_modules/@angular/compiler@9.1.0/bundles/compiler.umd.js (2724:21)
Template parse errors:
Parser Error: Unexpected token 'Lexer Error: Unexpected character [é] at column 2 in expression [téléphone]' at column 3 in [ Telephone: {{telephone}} Téléphone : {{téléphone}}
] in ng:///AppModule/AppComponent.html@0:3 ("<p>[ERROR ->]
Telephone: {{telephone}}
Téléphone : {{téléphone}}
</p>"): ng:///AppModule/AppComponent.html@0:3
Parser Error: Lexer Error: Unexpected character [é] at column 2 in expression [téléphone] at column 3 in [ Telephone: {{telephone}} Téléphone : {{téléphone}}
] in ng:///AppModule/AppComponent.html@0:3 ("<p>[ERROR ->]
Telephone: {{telephone}}
Téléphone : {{téléphone}}
</p>"): ng:///AppModule/AppComponent.html@0:3
Parser Error: Lexer Error: Unexpected character [é] at column 4 in expression [téléphone] at column 5 in [ Telephone: {{telephone}} Téléphone : {{téléphone}}
] in ng:///AppModule/AppComponent.html@0:3 ("<p>[ERROR ->]
Telephone: {{telephone}}
Téléphone : {{téléphone}}
</p>"): ng:///AppModule/AppComponent.html@0:3
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.3.25
Node: 12.16.1
OS: linux x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.25
@angular-devkit/build-angular     0.803.26
@angular-devkit/build-optimizer   0.803.26
@angular-devkit/build-webpack     0.803.26
@angular-devkit/core              9.0.3
@angular-devkit/schematics        7.3.9
@angular/cli                      8.3.25
@ngtools/webpack                  8.3.26
@schematics/angular               8.3.25
@schematics/update                0.803.25
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2

</code></pre>

**Anything else relevant?**

These links describe what the standard accepts as variable names :

+ https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Grammar_and_types#Variables
+ https://www.ecma-international.org/ecma-262/5.1/#sec-7.6
+ https://tc39.es/ecma262/#sec-identifier-names
+ https://mathiasbynens.be/notes/javascript-identifiers-es6

Also, [this concept](https://en.wikipedia.org/wiki/Americentrism) is somewhat related but not a technical consideration ;)

**Comment by pkozlowski-opensource** [comment] 2020-05-14 17:18
@Floby you are right, we don't support non-ASCII chars in Angular expressions. Having said this we do already have a ticket tracking it. Closing as a duplicate of #517

**Closed by pkozlowski-opensource** 2020-05-14 17:18 UTC

**Comment by Floby** [comment] 2020-05-14 17:24
Thanks for your quick reply @pkozlowski-opensource. Is it correct that Angular aims to support the extent of the ECMAScript spec regarding identifiers ?

**Comment by pkozlowski-opensource** [comment] 2020-05-14 17:34
>  Is it correct that Angular aims to support the extent of the ECMAScript spec regarding identifiers ?

I would say it would be ideal and something that would be great to have in the long run. But today there are several discrepancies between Angular expressions and ES expressions....
