### ISSUE TITLE
SyntaxError: strict mode code may not contain 'with' statements after 8 -> 9 upgrade (Hello World)

### ISSUE THREAD

**Issue by dmbaker90** [angular/angular#34970] opened 2020-01-25 17:03 UTC
# 🐞 bug report

### Affected Package

Not clear to me, the vendor.js link in the screenshot below points to `/node_modules/domino/lib/sloppy.js`

### Is this a regression?

 Yes, upgrades from 7->8 work fine. 8->8.x also work

### Description

  If I scaffold a Hello World application using `dotnet new angular -o my-new-app`, then I upgrade to Angular 9, I get the above error in the Console: `SyntaxError: strict mode code may not contain 'with' statements` and the Hello World page is stuck on `Loading...`

## 🔬 Minimal Reproduction
 

1. dotnet new angular -o my-new-app
2. cd my-new-app/ClientApp/
3. npm install
4. ng serve _verify Hello World Angular 8 app works here_
5. ng update @angular/core@8 @angular/cli@8
6. ng update @angular/cli @angular/core --next
7. ng serve _Hello World does not work_

I did the above instructions on this git repo, and you can run `ng serve` here: https://github.com/dmbaker90/Angular_9_bug

## 🔥 Exception or Error
<pre><code>

</code></pre>
![image](https://user-images.githubusercontent.com/5949263/73124325-06f66a00-3f4f-11ea-92f1-3651ed8f94fa.png)

## 🌍  Your Environment

**Angular Version:**
<pre><code>

$ ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 9.0.0-rc.10
Node: 12.14.1
OS: win32 x64

Angular: 9.0.0-rc.11
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router
Ivy Workspace: Yes

Package                                    Version
--------------------------------------------------------------------
@angular-devkit/architect                  0.900.0-rc.10
@angular-devkit/build-angular              0.900.0-rc.10
@angular-devkit/build-optimizer            0.900.0-rc.10
@angular-devkit/build-webpack              0.900.0-rc.10
@angular-devkit/core                       9.0.0-rc.10
@angular-devkit/schematics                 9.0.0-rc.10
@angular/cli                               9.0.0-rc.10
@ngtools/webpack                           9.0.0-rc.10
@nguniversal/module-map-ngfactory-loader   8.1.1
@schematics/angular                        9.0.0-rc.10
@schematics/update                         0.900.0-rc.10
rxjs                                       6.5.3
typescript                                 3.7.5
webpack                                    4.41.2
</code></pre>

**Anything else relevant?**
It wasn't clear to me if this was a dotnet issue or angular issue.  `ng new` projects seem to work fine.  However, I don't see why the dotnet scaffolding would be related to npm package updates.

**Comment by erjicles** [comment] 2020-02-02 22:07
I'm having this issue too. After some sleuthing, it seems like this issue was also reported at the fgnass/domino repo in November 2019, and it seems like several others have experienced it as well: https://github.com/fgnass/domino/issues/153

**Comment by alan-agius4** [comment] 2020-02-04 10:20
Hi, I have looked at the repo and it seems that the root cause seems to be that your browser bundle is including `domino` which shouldn't not happen.

The browser bundle is including `@angular/platform-server` which imports `domino` due to https://github.com/dmbaker90/Angular_9_bug/blob/a531d61134a4291d4af8305d9b9098fd97bcd117/my-new-app/ClientApp/src/main.ts#L22

That export was added with an Angular CLI version 9 migration, the reason for this is because the server main file is pointing to same one as the browser. Typically the server and browser builds have separate entrypoints because of different dependencies and are commonly named `main.server.ts` and `main.ts`.
https://github.com/dmbaker90/Angular_9_bug/blob/a531d61134a4291d4af8305d9b9098fd97bcd117/my-new-app/ClientApp/angular.json#L97 

It seems that there is a bug in scaffolding of the new application with dotnet templates. I also tried using NET Core 2.2 SDK version 2.2 (current latest) and it is still using Angular CLI version 6 (Which is no longer in LTS) to scaffold application.

Remove the below from your `main.ts`
```ts
export { renderModule, renderModuleFactory } from '@angular/platform-server';
```

If you are not using Angular universal you should also remove the `server` section in your `angular.json`, since it is incorrect and might cause future problems.

**Comment by gkalpak** [comment] 2020-02-04 11:13
Thx, @alan-agius4 :+1:

Closing this, since the problems seems to be in how the `dotnet` command scaffolds the Angular project.

**Closed by gkalpak** 2020-02-04 11:13 UTC
Labels: comp: misc

**Comment by erjicles** [comment] 2020-02-05 23:48
@alan-agius4 That worked, thanks!

**Comment by sliceofbytes** [comment] 2020-02-06 22:05
Thanks @alan-agius4, worked a charm.

**Comment by Moalpima** [comment] 2020-02-19 09:13
Jason Taylor wrote a very good article to this theme: https://jasontaylor.dev/asp-net-core-angular-9-upgrade/

**Comment by yumagulov-azat** [comment] 2020-03-03 15:04
I'm having this issue too.
How to use now, for example BEFORE_APP_SERIALIZED from @angular/platform-server on the client?

**Comment by paulirwin** [comment] 2020-03-09 23:40
Not only did this solve the issue, but it also shaved over 2 MB (!!!) off my vendor.js size! Incredible, thanks!
