### ISSUE TITLE
We should we annotate dictionaries with @dict to avoid issues with the closure compiler.

### ISSUE THREAD

**Issue by nosachamos** [angular/angular#15853] opened 2017-04-09 19:19 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Data structures like "Data" and "ResolveData" are not annotated with `@dict` to avoid issues with closure in advanced mode. The result is that setting data in routes and accessing them programmatically (with bracket notation) is not possible given that these properties are later renamed. We should annotate these and perhaps other dictionaries.

**Expected behavior**
We should annotate these and perhaps other dictionaries with `@dict`.

**What is the motivation / use case for changing the behavior?**
Angular is now closure-compatible, but this bit is missing.

* **Angular version:** ^4.0.0

* **Browser:** all
 
* **Language:** all

**Comment by IgorMinar** [comment] 2020-06-01 15:37
Hi there, this issue assumes that Angular has full support for Closure's advanced optimizations, as of v10.0 this is no longer the case when Angular is consumed via npm packages.

If you are interested in Angular supporting Closure's advanced optimizations please follow https://github.com/angular/angular/issues/37234.

In the meantime, can you please provide us with a reproduction of the issue that you filed? I know that it's been a while since your original filing, but if this issue still exists today, we'd like to know about it. (sidenote: Angular is used at Google with advanced optimizations turned on, so I'm a bit surprised that this is an issue at all)

**Comment by JoostK** [comment] 2022-03-31 17:32
Closing as not something we'll address at this point.

**Closed by JoostK** 2022-03-31 17:32 UTC
Labels: type: bug/fix, comp: packaging, freq2: medium, state: needs more investigation, P3
