### ISSUE TITLE
Resolver in route configuration not described and no code snippet shown for change

### ISSUE THREAD

**Issue by ratuple** [angular/angular#18799] opened 2017-08-20 18:36 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Issue under: "Fundamentals" > "Routing & Navigation" > "Fetch data before navigating".
https://angular.io/guide/router#fetch-data-before-navigating

"Import this resolver in the crisis-center-routing.module.ts and add a resolve object to the CrisisDetailComponent route configuration."
This is the only sentence telling you to configure the created resolver to the route.
It does not mention how this object should look like, how the parameter should be called ('crisis') and does not describe what this configuration actually does.
The code snippet below that section is of the same impacted file but does not show the impacted route configuration.

Summary: The following change in the file 'crisis-center-routing.module.ts' should be clearly documented:
`           resolve: {
              crisis: CrisisDetailResolver
            }`

## Expected behavior
Route resolve property documented in detail and with code-snippet.

## What is the motivation / use case for changing the behavior?
Understanding where, how and why to configure the resolve property for the route.

**Comment by brandonroberts** [comment] 2018-06-22 16:09
Duplicate of #18538

**Closed by brandonroberts** 2018-06-22 16:09 UTC
Labels: comp: docs, comp: router, effort2: days, freq2: medium, severity1: confusing, type: bug/fix
