### ISSUE TITLE
simple way to reload route running guards and resolvers

### ISSUE THREAD

**Issue by rekna1** [angular/angular#25311] opened 2018-08-05 13:26 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

I've seen different strategies for reloading a component and running resolvers again. They all seem rather complicated and unintuitive for me.

A simple $router.reload() would be the simplest solution in my opinion. This should run resolvers again regardless of runGuardsAndResolvers, onSameUrlNavigation, etc.
E.q. don't want to set runGuardsAndResolvers to always or onSameUrlNavigation to reload

Use case : I have a refresh button the user can use to force refresh data on the page with most recent data from the server. Only when user clicks this button I want data to be reloaded using resolver defined for this component

**Comment by trotyl** [comment] 2018-08-05 13:35
Duplicate of https://github.com/angular/angular/issues/9669

**Comment by mlc-mlapis** [comment] 2018-08-05 15:09
@rekna1 ... it looks that your code in the component instance is not written to be able to re-init so you are requesting for destroying the actual component instance and creating a new one. But it is a symptom that you should re-think its concept.

Probably you should look at the case the same way you are applying a route like `/product/:id` where changing the route from `/product/4` to `/product/5` also doesn't create a new component instance.

**Comment by mlc-mlapis** [comment] 2018-08-05 15:25
@rekna1 ... OK, then you did what is expected. Fine. So you are just requesting for some more simple syntax to reload guards and resolvers when you re-route to the same route as you are on. Probably some global (default) setting that would apply to all your routes in once, right?

**Comment by rekna1** [comment] 2018-08-05 15:31
not all routes if possible... i want to be able to control it case per case

**Comment by mlc-mlapis** [comment] 2018-08-05 15:33
@rekna1 ... oh, so then I can't see the sense ... because `onSameUrlNavigation: 'reload'` could be set on the global level right now and `runGuardsAndResolvers:  'always'` is the option on a route level, so what would you suggest then concretely?

**Comment by rekna1** [comment] 2018-08-05 15:43
if I only had a method route.reload() that I could call from code the problem would be solved.
if i set runGuardsAndResolver:'always', resolver for my component will run always whether I want it to run or not ?

**Comment by mlc-mlapis** [comment] 2018-08-05 16:01
@rekna1 ... the options are ` 'paramsChange' | 'paramsOrQueryParamsChange' | 'always';` so if you could use the first two of them and then use the standard `.navigate(...)` with just a different query param ... it could be just a timestamp or so, ...

**Comment by rekna1** [comment] 2018-08-05 21:08
oké,, timestamp will do. url with  timestamp is not so pretty but I can live with it.

**Comment by jasonaden** [comment] 2018-11-15 23:53
Sounds like you have a workaround at this point, so I will close this issue.

In the future, we would like to have cleaner APIs with regards to what comes through in a resolver so you can get updates as new values are sent through the observable chain. That won't work currently as we require the resolver observable to be completed.

**Closed by jasonaden** 2018-11-15 23:53 UTC
Labels: comp: router
