### ISSUE TITLE
Improve Routes for allows input params to component

### ISSUE THREAD

**Issue by sky10p** [angular/angular#27576] opened 2018-12-10 16:23 UTC
# 🚀 feature request
It is essential that the way in which we share data between components in different routes is easier.

I think it is important to uncouple the component from the route to make it more reusable.

For that, we could use the Input() of the component, so that it works for the path and query params from route.

And use the router Link to pass data.

### Relevant Package
@angular/router

### Description
When you create modular components using the Input (), they can not be reused for use with the path, and use the path or query params. Since you must change the logic and work with the functions of Route that gives you angular.

I think it is necessary to achieve mainly:

-We can use the input to send data from the path (path or query params).
-Poder pass the data easily using a routerLink.

### Describe the solution you'd like
For example:

Component A: 

```
export class Component{
 @Input()
   user: string;

 @Input()
  text: string;
}
```

And Url would be:
/api/users/:user

if you want to pass this data:

```
data = {
  user: 'UserName',
  text: "A text"
}
```

you should be able to pass with routeLink:

`route.navigate(['api/users/:user'], data);`

This generates the correct path : 
`/api/users/UserName?text=A%20text`

And will be loaded in the two inputs of components automatically

### Describe alternatives you've considered
In any case, the most important thing is to be able to use the data that comes from a uri, in a transparent way to the component so that it is reusable.

**Comment by Airblader** [comment] 2018-12-10 20:00
I'm not seeing the issue here – with your proposal, you still need to change the implementation of a component to receive its inputs from the route instead. Why do we need a new syntax for that instead of just doing this?

```
this.activatedRoute.paramMap.subscribe(paramMap => this.user = paramMap.get("user"));
```

**Comment by sky10p** [comment] 2018-12-10 20:09
Because the idea is that the component is reusable, as for example in a library. And the code you're commenting assumes that you're using routing, but it could be used normally. The idea is that you can use the input () in the same way you normally do.

**Comment by trotyl** [comment] 2018-12-11 02:15
Duplicate of https://github.com/angular/angular/issues/4452, https://github.com/angular/angular/issues/18967

**Comment by jasonaden** [comment] 2018-12-12 00:02
Closing as a duplicate. I re-opened #18967

**Closed by jasonaden** 2018-12-12 00:02 UTC
Labels: comp: router, type: feature
