### ISSUE TITLE
RouteReuseStrategy doesn't reuse the parent tree components

### ISSUE THREAD

**Issue by gianmarcov** [angular/angular#20072] opened 2017-11-01 13:22 UTC
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] (Maybe) bug report
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
When extend 'RouteReuseStrategy' with my reuse logic, only the child component
will be reused, the parent tree will be destroyed and recreated on every route change.

## Expected behavior
When extend 'RouteReuseStrategy' with my reuse logic, i expect that not only the child component will be reused also the parent tree components.

## Minimal reproduction of the problem with instructions
https://plnkr.co/edit/LQ2lgBrjWw6JeezdqNhl?p=preview

1. type a number for simulate opening person to edit. (click on 'open person detail')
2. change tab 'person'
3. click on 'goto detail'
4. type a number into the textarea -> parent component will show the value after living textarea
(share same service instance)
5. change back to home tab -> change back to person tab 
6. typed number will be displayed in the child textarea (reused route) but parent doesn't have a number anymore even if typing a new number. (because service instance are not the same)

## What is the motivation / use case for changing the behavior?
What i want to archive is that i can provide the same service instance via dependency injection to the router-outlet children and the children can interact with the parent component. (This cannot be done as global service, because the route will be created dynamically with an id in the url (every route has it's own state, see plunker demo)).

## Environment
<pre><code>Angular version: 4.3.1
For Tooling issues:
- Node version: v6.11.1
- Platform:  Windows
</code></pre>

**Comment by dmitrimaltsev** [comment] 2017-12-25 12:39
I'm having a similar use case and it seems to me I made it work. I used a custom route reuse strategy borrowed from here: https://github.com/angular/angular/issues/6634 (see @todoubaba's comment).

Here's the minimal example:
https://embed.plnkr.co/NPgOdo24jF5W0NByfD9T/

@gianmarcov, could you please have a look?

**Comment by dmitrimaltsev** [comment] 2017-12-25 13:05
I'm having a similar use case. It looks like I made mine work using a custom route reuse strategy borrowed from https://github.com/angular/angular/issues/6634 (see comment by @todoubaba).

Here's the minimal example:
https://embed.plnkr.co/NPgOdo24jF5W0NByfD9T/

@gianmarcov could you please have a look?

**Comment by atscott** [comment] 2020-05-27 22:59
Hi, can someone recreate a minimal demo on stackblitz with steps to reproduce? I'm having trouble following what the expected behavior is here on these
https://stackblitz.com/edit/angular-ivy-nbiyb7?file=src%2Fapp%2Ftabs.ts
https://stackblitz.com/edit/angular-ivy-gloeav?file=src%2Fapp%2Fapp.ts

**Comment by atscott** [comment] 2020-07-08 22:54
Ah, I can confirm that this is an issue in https://stackblitz.com/edit/angular-ivy-gloeav?file=src%2Fapp%2Fapp.ts using the steps described:
1. type a number for simulate opening person to edit. (click on 'open person detail')
2. change tab 'person'
3. click on 'goto detail'
4.type a number into the textarea -> parent component will show the value after living textarea
(share same service instance)
5. change back to home tab -> change back to person tab
6. typed number will be displayed in the child textarea (reused route) but parent doesn't have a number anymore even if typing a new number. (because service instance are not the same)

This appears to be a duplicate of #18374.  Please let me know if that's actually a different issue.

**Closed by atscott** 2020-07-08 22:54 UTC
Labels: comp: router, freq2: medium, router: RouteReuseStrategy, severity3: broken, state: Needs repro, triage #1, type: bug/fix
