### ISSUE TITLE
element ID's are truncated during angular processing to a length of no more than 20

### ISSUE THREAD

**Issue by nhustak** [angular/angular#29222] opened 2019-03-11 14:50 UTC
# 🐞 bug report

### Affected Package

I do not know.

### Is this a regression?

I do not believe it is.

### Description
Angular appears to be truncating the ID of an element when processing it to a length not greater than 20.  Inspect element at following stackblitz.com.   The set id in the code is truncated once angular processes it.

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-vx8rji?file=src%2Fapp%2Fapp.component.html

## 🔥 Exception or Error
<pre><code>

None
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular 7.2.8
</code></pre>

**Anything else relevant?**

I regularly use the GUID of the row as an ID when I need to get it a unique reproducible id for things like tooltips and other controls.   This truncates that ID.   In any case, this seems to be arbitrarirly low limit given the w3c spec has no limit.  I realize there needs to be a practical limit but it would be helpful if it was closer to 50 rather that 20.

**Comment by pkozlowski-opensource** [comment] 2019-03-11 15:07
@nhustak when you say:

> Angular appears to be truncating the ID of an element when processing it to a length not greater than 20. Inspect element at following stackblitz.com. The set id in the code is truncated once angular processes it.

What I'm seeing opening this stackblitz in Chrome is:
* `<div _ngcontent-c0="" id="ID12345678901234567890123456789012345678901234567890">` - **no** truncation happening here
* `<hello ng-reflect-name="ID1234567890123456789012345678"><h1 _ngcontent-c1="">Hello ID12345678901234567890123456789012345678901234567890!</h1></hello>` - the **only** thing truncated here is `ng-reflect-name="ID1234567890123456789012345678"` and this is a _debug_ attribute (not present in the production and not affecting "real" bindings).

Which element do you mean _exactly_ when saying "Inspect element at following stackblitz.com"?

I _think_ that this is a duplicate of #28786 but need a confirmation.

**Comment by nhustak** [comment] 2019-03-11 15:31
@pkozlowski-opensource   Hrm.   This started out as an issue with DevExtreme and they tracked it down to the ID they were getting out of Angular.   Now I am wondering if they are incorrectly using the reflect-name to establish the reflect target?  I don't know enough about the inner workings.

I've linked in this thread to the DevExpress support ticket.

Basically I have a context menu that is targeting a component, in this case a simple div. 

This is the code pen for the angular issue.

https://codesandbox.io/s/3qp50omypm

This is the code result from their end.
<div _ngcontent-c8="" class="dx-template-wrapper">
    <div _ngcontent-c8="" style="cursor: pointer;" id="ID12345678901234567890123456789012345678901234567895">ID Is truncated</div>
    <dx-context-menu _ngcontent-c8="" ng-reflect-items="[object Object],[object Object" ng-reflect-target="ID1234567890123456789012345678" class="dx-has-context-menu dx-widget dx-visibility-change-handler dx-collection"></dx-context-menu>
  </div>

**Comment by nhustak** [comment] 2019-03-11 15:35
@pkozlowski-opensource   Oh sorry didn't answer your question.  You have correctly surmised it - we had boiled it down to looking at the reflect name.   My assumption at this point is that DevExtreme is using the reflect name to get the ID.

**Comment by pkozlowski-opensource** [comment] 2019-03-11 15:38
>  My assumption at this point is that DevExtreme is using the reflect name to get the ID.

Right, in this case it would be a duplicate of #28786 - could you add your use case in-there (we shouldn't be tracking the same thing in 2 places so I'm going to close this one as a duplicate).

#28786 aside - I don't think anyone should be really using `ng-reflect-...` for anything "serious" as those things are debug-mode only and won't be available in a production build.

Closing as a duplicate of #28786

**Closed by pkozlowski-opensource** 2019-03-11 15:38 UTC
Labels: comp: core & compiler

**Comment by nhustak** [comment] 2019-03-11 15:51
Hrm.  The only thing that makes me doubt that is the context menu component would totally fail in production then and it doesn't.  Something else has to be going on here.   Thank you for your assist.   I believe the issue lies with DevExpress.  I will add my use case in.

**Comment by pkozlowski-opensource** [comment] 2019-03-11 15:54
> The only thing that makes me doubt that is the context menu component would totally fail in production then and it doesn't. Something else has to be going on here. 

Sure, feel free to open a new issue if you can reproduce odd truncating going on in a Stackblitz with Angular only.

**Comment by pkozlowski-opensource** [comment] 2019-03-12 13:43
No worries @nhustak - glad that you got to the bottom of it!
