### ISSUE TITLE
Feature request: Support `restrict: 'A'` for downgraded components

### ISSUE THREAD

**Issue by AngularOne** [angular/angular#16695] opened 2017-05-10 12:33 UTC
I have wrote a simple directive in angular 2, but while downgrade it to work in angular 1, it just fails. I don't think it is being supported. Am I currect?

```
@Component({
  selector: '[myComponent]',
  template: `<ng-content></ng-content>`
})
export class MyComponent {
  @Input() myComponent : string;
  
  constructor() {}

  @HostListener("mouseenter", ['$event'])
  show(event:MouseEvent): void {
    if(this.myComponent) {
       console.log("YES, its working: " + this.myComponent);
    }

  }

}
```

Now I'm downgrading this directive:

```
angular.module('myApp')
    .directive('myComponent', downgradeComponent({component: MyComponent, inputs: ['myComponent'] }) as angular.IDirectiveFactory)
```

You accepct this directive to work in angular 1.x too, but its not, like it doesn't even exists

**Comment by gkalpak** [comment] 2017-05-10 12:41
Downgrading is generally supported (that's 50% of the whole point of ngUpgrade 😛).
But it is difficult to tell what the issue is without a reproduction.

**Comment by AngularOne** [comment] 2017-05-10 12:58
I added my code. If I now try
`<div [my-component]="'abc text'"></div>`
it will not work.

**Comment by gkalpak** [comment] 2017-05-10 14:02
I see. Currently, you cannot downgrade attribute directives. `downgradeComponent` creates directive factories with `restrict: 'E'`, so they will only work on elements.

In most cases it shouldn't matter, but there might be some cases where you need the selector to match against an attributea dn not the node name. 

##
So, this is a feature request :smiley:

**Comment by pierrebeaucamp** [comment] 2017-06-20 17:40
+1 For that feature request. Also fyi, I did actually try to use `decorator` to change the `restrict` property, but unfortunately it didn't work.

**Comment by vikrambhatla** [comment] 2017-08-03 04:05
+1 for the feature request. We're also using attribute directives. There is no way right now to downgrade Directive. 
i.e. We want to add <input [focus]="true"> focus directive. There is no way we can do this kind of scenario in the Hybrid app.

I was thinking to implement:
<focus-field>
    <input #myInputField>
</focus-field>
But I am not able to use @ViewChild('myInputField') myInputField:ElementRef. myInputField is always coming as undefined.

**Comment by jbadeau** [comment] 2017-08-18 14:52
Try ngadapter

**Comment by banjankri** [comment] 2017-10-13 13:43
If anyone runs into same issue and needs to have attribute component downgraded, here is a workaround I implemented:

```
static allowAttribute(componentFactory) {
        const wrapper = function($compile, $injector, $parse) {
            const component = componentFactory($compile, $injector, $parse);
            component.restrict = "AE";
            return component;
        };
        wrapper.$inject = ["$compile", "$injector", "$parse"];
        return wrapper;
    }
```

and you would use it as follows:

`angularjsModule.directive("tableColumn", allowAttribute(downgradeComponent({ component: TableColumnComponent })));`

**Comment by gkalpak** [comment] 2017-12-15 11:25
BTW, if someone feels like submitting a PR for this, please do :smiley:

**Comment by sharikovvladislav** [comment] 2018-05-04 14:19
@gkalpak hey! any ideas how to downgrade Angular `@Directive` to AngularJS (not a `@Component`)?

downgradeComponent resolves component via ComponentFactoryResolve.resolveComponentFactory. We can not add Angular Directive to entryComponents so downgradeComponent method can't resolve it.

**Comment by gkalpak** [comment] 2018-05-05 11:16
It is not possible. In order to be able to upgrade/downgrade something, it needs to own the whole element (and its contents); i.e. be a component.

**Comment by sharikovvladislav** [comment] 2018-05-07 08:40
@gkalpak okay! thank you

We handled that with that:
1. We have our directive (which we want to downgrade)
2. We also have wrapper component which has simple block with applied directive + ng-content inside it.
3. We downgrade that component using https://github.com/angular/angular/issues/16695#issuecomment-336456199 or desperate move from this https://github.com/angular/angular/issues/16695#issuecomment-300491381.

It worked (if anybody needs it).

**Comment by jamesbrobb** [comment] 2019-03-27 13:31
> In case anyone runs into this issue and wonders what the hell "[#16695 (comment)](https://github.com/angular/angular/issues/16695#issuecomment-300491381)" said, here is how you achieve the hack:
> 
> ```js
> app.directive('foo', downgradeComponent({component: FooComponent} as angular.IDirectiveFactory));
> app.config(['$provide', $provide => {
>   $provide.decorator('fooDirective', ['$delegate', $delegate => {
>     $delegate[0].restrict = 'EA';
>     return $delegate;
>   }]);
> }]);
> ```

If using this approach, how do you then use the directive within an `ngUpgrade` application?

So if the selector of the Angular component is `[my-directive]` and the downgraded angularjs component is declared as `myDirective` i'm presuming that my mark up should look like this when using the component:

`<div my-directive></div>`

not like this:

`<div [my-directive]></div>`

and not like this:

`<div [myDirective]></div>`

I say that as the first one is the only one that seems to trigger an error in the console, the other 2 just fail silently.

The error i get in the console is:

`Error: No component factory found for MyDirective. Did you add it to @NgModule.entryComponents?`

But if i then add it to my `AppModule entryComponents`, when i run `ng build myApp` i get the following error:

`ERROR in : MyDirective cannot be used as an entry component.`

**Comment by gkalpak** [comment] 2019-03-27 15:02
@jamesbrobb, the discussion above is not about downgrading Angular `@Directive`s. It is about downgrading Angular `@Component`s with an attribute selector (i.e. `selector: '[some-thing]'` - notice the `[...]`). Here is an example: [ngupgradestatic-issue-16695][1]

[1]: https://stackblitz.com/edit/ngupgradestatic-issue-16695?file=src/ng1/ng1-demo.module.ts

**Comment by vikrambhatla** [comment] 2019-04-03 23:06
> If anyone runs into same issue and needs to have attribute component downgraded, here is a workaround I implemented:
> 
> ```
> static allowAttribute(componentFactory) {
>         const wrapper = function($compile, $injector, $parse) {
>             const component = componentFactory($compile, $injector, $parse);
>             component.restrict = "AE";
>             return component;
>         };
>         wrapper.$inject = ["$compile", "$injector", "$parse"];
>         return wrapper;
>     }
> ```
> and you would use it as follows:
> 
> `angularjsModule.directive("tableColumn", allowAttribute(downgradeComponent({ component: TableColumnComponent })));`
> 
> Seems to be hooking up correctly to the mechanism and attribute directives are rendered properly in angularjs app.

How to pass input fields to the this directive?
I am trying to do:
`<div table-column [column-name]="'test'"></div>`

this doesn't work.

**Comment by gkalpak** [comment] 2019-04-15 07:50
I just realized it is much easier to do this with a helper function as shown in https://github.com/angular/angular/issues/16695#issuecomment-336456199 :grin:
Here is a simpler (marginally future-safer) implementation ([demo][1]):

```ts
const allowAttribute = directiveFactory => [
  '$injector',
  ($injector: angular.auto.IInjectorService) =>
    Object.assign($injector.invoke(directiveFactory), {restrict: 'EA'}),
];

// Use it like this:
// .directive('someSelector', allowAttribute(downgradeComponent({...})))


// Or event make a `downgradeAttributeComponent()` helper:
const downgradeAttributeComponent = info => allowAttribute(downgradeComponent(info));

// Use it like this:
// .directive('someSelector', downgradeAttributeComponent({...}))
```

[1]: https://stackblitz.com/edit/ngupgradestatic-playground-16695-2?file=src/ng1/ng1-demo.module.ts

**Comment by ajitsinghkaler** [comment] 2019-11-29 19:33
@gkalpak is the workaround the final thing we are doing on this. Or are we trying to build this up.

**Comment by gkalpak** [comment] 2019-12-01 13:34
@ajitsinghkaler, this is a feature request. I am not against implementing it , but it is low priority.
(Therefore it is marked as `hotlist: community-help` - also see https://github.com/angular/angular/issues/16695#issuecomment-351982575.)

**Comment by surenrao** [comment] 2020-03-09 19:18
> I just realized it is much easier to do this with a helper function as shown in [#16695 (comment)](https://github.com/angular/angular/issues/16695#issuecomment-336456199) (credits to @banjankri) 
> Here is a simpler (marginally future-safer) implementation ([demo](https://stackblitz.com/edit/ngupgradestatic-playground-16695-2?file=src/ng1/ng1-demo.module.ts)):
> 
> ```ts
> const allowAttribute = directiveFactory => [
>   '$injector',
>   ($injector: angular.auto.IInjectorService) =>
>     Object.assign($injector.invoke(directiveFactory), {restrict: 'EA'}),
> ];
> 
> // Use it like this:
> // .directive('someSelector', allowAttribute(downgradeComponent({...})))
> 
> 
> // Or event make a `downgradeAttributeComponent()` helper:
> const downgradeAttributeComponent = info => allowAttribute(downgradeComponent(info));
> 
> // Use it like this:
> // .directive('someSelector', downgradeAttributeComponent({...}))
> ```

With Angular 9, I am getting below error
`Error: ASSERTION ERROR: Type passed in is not ComponentType, it does not have 'ɵcmp' property.`
Does this not work with Ivy?

**Comment by jelbourn** [comment] 2021-04-06 20:42
Closing this since I don't realistically see us adding more features to ng-upgrade like this one.

**Closed by jelbourn** 2021-04-06 20:42 UTC
Labels: P4, comp: upgrade, effort1: hours, feature, freq1: low, help wanted, workaround2: non-obvious
