### ISSUE TITLE
Add the ability to remove instance of service after leaving a route

### ISSUE THREAD

**Issue by zygarios** [angular/angular#54644] opened 2024-02-28 09:57 UTC
### Description

Currently, Angular allows service providers to be injected at the following levels:

- Application level
- Routing level for a specific path and its children (our use case)
- Component level

The problem is when we want a single instance of a service to be shared across all child routes of a specific path, but that instance to be destroyed when navigating to a different path that does not use that service. Currently, services loaded on a route are cached for that route for the lifetime of the application.

This can be seen in the linked reproduction, where service instances are not destroyed after navigating to the otherpage route. To achieve this behavior, we need to create a wrapper component that only contains a <router-outlet> and has the services included in the component, which is an unnecessary abstraction in my opinion.

Good article about it:

https://itnext.io/mastering-injectable-services-a-comprehensive-guide-6c2c0f5f48a2

Reproduction:
[Stackblitz](https://stackblitz.com/edit/stackblitz-starters-5hzubt?description=An%20angular-cli%20project%20based%20on%20@angular/animations,%20@angular/common,%20@angular/compiler,%20@angular/core,%20@angular/forms,%20@angular/platform-browser,%20@angular/platform-browser-dynamic,%20@angular/router,%20core-js,%20rxjs,%20tslib%20and%20zone.js&file=src%2Fmain.ts,angular.json,src%2Fpages%2Fotherpage.component.ts,src%2Fexample.service.ts,src%2Findex.html,src%2Fpages%2Fhomepage%2Fhomepage-1.component.ts,src%2Fpages%2Fhomepage%2Fhomepage-2.component.ts%3AL5&file=src%2Fmain.ts,src%2Fexample.service.ts,src%2Fpages%2Fhomepage%2Fhomepage-1.component.ts,src%2Fpages%2Fhomepage%2Fhomepage-2.component.ts,src%2Fpages%2Fotherpage.component.ts&template=node&title=Angular%20Starter)

### Proposed solution

I'm not sure if this is the best solution, but perhaps adding an additional hermeticProviders array to the route configuration 
`{path: 'some-route', providers:[], **hermeticProviders**: []}`
 would help create instances that only live for the duration of the route. This would eliminate the need to create an artificial component that doesn't actually serve as a component in this case.

### Alternatives considered

No ideas

**Comment by alxhub** [comment] 2024-02-28 17:06
Closing as a duplicate of #37095.

**Closed by alxhub** 2024-02-28 17:06 UTC
Labels: area: router
