### ISSUE TITLE
ComponentFactoryResolver#resolveComponentFactory could not work with lazy loaded module correctly

### ISSUE THREAD

**Issue by JounQin** [angular/angular#22694] opened 2018-03-10 01:28 UTC
## I'm submitting a...

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report  
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

## Current behavior

When using `ModalModule.forChild()` in lazy loaded module, there will be an error
```
ERROR Error: No component factory found for MyModalComponent. Did you add it to @NgModule.entryComponents?
```

Change it to `ModalModule.forRoot()` will work, but it means `ModalService` will not be singleton in whole application.

## Expected behavior

Do not throw error and works well with `ModalModule.forChild()`

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/angular-gitter-rblfqn?file=app%2Fhome%2Fhome.module.ts

## What is the motivation / use case for changing the behavior?

`ModalService` should be singleton.

## Environment

Angular version: 5.0.0

Browser:
- [x] Chrome (desktop) version 64.0.3282.186
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by alexzuza** [comment] 2018-03-10 05:59
Since lazy loaded module creates new injector it creates its own scope for entry components. So it has its own ComponentFactoryResolver.

You added MyModalComponent entry to lazy loaded injector and therefore ModalService that is connected to root injector can't resolve this entry.

To solve it you can optionally pass `NgModuleRef` instance to your `ModalService.open` method and obtain `ComponentFactoryResolver` from it if provided.

**modal.service.ts**
```
open(Component: Type<any>, moduleRef?: NgModuleRef<any>) {
  const cfr = moduleRef ? moduleRef.componentFactoryResolver : this.cfr;

  const componentFactory = cfr.resolveComponentFactory(Component)
  console.log(componentFactory)
}
```

**home.component.ts**

```
import { Component, NgModuleRef } from '@angular/core'

export class HomeComponent {
  constructor(private modal: ModalService, private moduleRef: NgModuleRef<any> ) {}

  showModal() {
    this.modal.open(MyModalComponent, this.moduleRef)
  }
}
```


https://stackblitz.com/edit/angular-gitter-sbrssy?file=app/modal/modal.service.ts

**Comment by trotyl** [comment] 2018-03-10 06:43
Duplicate of #17168

**Closed** 2018-03-29 22:28 UTC
Labels: comp: core & compiler
