### ISSUE TITLE
number input and text input have different updateOn behaviors

### ISSUE THREAD

**Issue by gssjr** [angular/angular#33335] opened 2019-10-22 21:06 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/forms

### Is this a regression?

Unknown

### Description

 Setting two form controls with updateOn: 'change' they behave differently depending which html element is used: Input[type="number"], will emit on both change and blur, where as a input[type="text"] will only emit on change.

## 🔬 Minimal Reproduction

 https://stackblitz.com/edit/angular-forms-bug-number-input-blur

## 🔥 Exception or Error
<pre><code>

 No errors

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

 8.0.0

</code></pre>

**Anything else relevant?**

**Comment by trotyl** [comment] 2019-10-23 05:54
Duplicate of https://github.com/angular/angular/issues/12540

**Comment by IgorMinar** [comment] 2019-11-08 20:27
yup, dupe :-/ thanks @trotyl

**Closed by IgorMinar** 2019-11-08 20:27 UTC
Labels: comp: forms
