### ISSUE TITLE
i18n: xlf-source containing a different number of HTML Tags compared to xlf-target. Since Angular 9 & 10

### ISSUE THREAD

**Issue by kloener** [angular/angular#38095] opened 2020-07-16 13:41 UTC
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/localize.

### Is this a regression?
Yes, the previous version in which this bug was not present was: Angular 8 (without @angular/localize).

### Description

Hi, I've encountered an issue with Angular 9 i18n. The translations work as expected if the same amount of HTML tags is used in "source" and "target"-translations. But if the target-translation has more HTML tags included, the resulting HTML is different from Angular 8. 

Since Angular 9 the translated HTML tags will be combined. For example: in the XLF-source is a single "strong"-tag used, but in the XLF-target exist two strong-tags. The inner text of the two strong-tags will be inserted into a single strong-tag at the end of the translation text.
![image](https://user-images.githubusercontent.com/737537/87675018-212f3900-c777-11ea-8afd-97f969cfbf8a.png)

The issue remains with Angular 10 as well.

## 🔬 Minimal Reproduction

A messages-XLF with different amount of HTML tags in a single trans-unit is required:
<pre><code>
&lt;trans-unit id="Sample:Text" datatype="html">
&lt;source>
    &lt;x id="START_BOLD_TEXT" ctype="x-b" equiv-text="&lt;b&gt;"/>some bold text&lt;x id="CLOSE_BOLD_TEXT" ctype="x-b" equiv-text="&lt;/b&gt;"/>
&lt;/source>
&lt;target>
    &lt;x id="START_BOLD_TEXT" ctype="x-b" equiv-text="&lt;b&gt;"/>some original bold text&lt;x id="CLOSE_BOLD_TEXT" ctype="x-b" equiv-text="&lt;/b&gt;"/>
    some new text
    &lt;x id="START_BOLD_TEXT" ctype="x-b" equiv-text="&lt;b&gt;"/>some other bold text&lt;x id="CLOSE_BOLD_TEXT" ctype="x-b" equiv-text="&lt;/b&gt;"/>
&lt;/target>
</code></pre>

See theses repositories:

- Working as expected: Angular 8 Sample including i18n: https://github.com/kloener/kloener-angular8-i18n-issue 
![angular8](https://user-images.githubusercontent.com/737537/87676952-7ff5b200-c779-11ea-9548-d815d1e7e5e3.png)

- Not as expected: Angular 9 Sample including i18n: https://github.com/kloener/kloener-angular9-i18n-issue 
![angular9](https://user-images.githubusercontent.com/737537/87676959-83893900-c779-11ea-890a-dc83aa6b3fac.png)

Just checkout the repositories, install deps and build the projects with `npm run build:localize`. Afterwards you can run an HTTP Server on the /dist folder and compare the results.

## 🔥 Exception or Error
No errors are thrown during build- or runtime.

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.1.9
Node: 12.17.0
OS: linux x64

Angular: 9.1.11
... animations, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.9
@angular-devkit/build-angular     0.901.9
@angular-devkit/build-optimizer   0.901.9
@angular-devkit/build-webpack     0.901.9
@angular-devkit/core              9.1.9
@angular-devkit/schematics        9.1.9
@angular/cli                      9.1.9
@ngtools/webpack                  9.1.9
@schematics/angular               9.1.9
@schematics/update                0.901.9
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0
</code></pre>

**Anything else relevant?**
No.

**Comment by petebacondarwin** [comment] 2020-07-16 14:58
Some additional diagnosis... The `$localize` tagged strings look like this:

**Original (de)**:
```
" Here are some " +
    "�#4�" + "links" + "�/#4�" + " to " +
    "�#5�" + "help" + "�/#5�" + "" +
    "�#6�" + "you" + "�/#6�" + "" +
    "�#7�" + "get started" + "�/#7�" + ":\n"
```

**Translation with extra element placeholders (de-DE)**:
```
"\n          Hier sind mehr HTML Tags als urspr\xFCnglich " +
             "�#4�" + "links" + "�/#4�" + "\n          to " +
             "�#5�" + "help" + "�/#5�" + "\n          " +
             "�#6�" + "you" + "�/#6�" + " " +
             "�#7�" + "get started" + "�/#7�" + ":\n          " +
             "�#4�" + "links" + "�/#4�" + "\n          und noch ein link extra\n          " +
             "�#5�" + "help" + "�/#5�" + "\n        ";
```

**Comment by petebacondarwin** [comment] 2020-07-16 14:59
I "think" that these strings are correct and that it is the ivy rendering that is placing the elements into the DOM in the wrong place... @AndrewKushnir any ideas?

**Comment by kloener** [comment] 2020-07-17 05:49
Just noted that if the source translation has more HTML Tags than the target then the rendered HTML will contain empty HTML tags. I thought of a workaround by adding some "placeholder" tags, but the rendererd "br"-tags may be a problem ...

![source](https://user-images.githubusercontent.com/737537/87752646-1d47f900-c801-11ea-899e-9bb2df335068.png)
![issue-vice-versa](https://user-images.githubusercontent.com/737537/87752648-1de08f80-c801-11ea-96a8-08494c2fe8e0.png)

**Comment by petebacondarwin** [comment] 2020-07-17 11:04
OK so I have got to the bottom of it... I think.

As I mentioned above we are duplicating the internal ivy i18n "element markers" (e.g. `�#5�`) when the translated message contains duplicate "placeholders" (e.g. `START_LINK`). If there had been such duplicates in the original message then we would have had unique names for these placeholders (e.g. `START_LINK`, `START_LINK_1`, etc) which would then result in unique ivy element markers (e.g. `�#5�`, `�#6�`, etc).

Because the translation is using the same placeholder names we are duplicating the ivy element markers, which results in the ivy rendering engine getting confused. Ideally these additional placeholders should be unique in the translated message (e.g. `START_LINK`, `START_LINK_1`, etc) but as it stand this cause the translation tooling to throw an error since the extra placeholders in the translated message would not match to a placeholder in the original source message.

**Comment by petebacondarwin** [comment] 2020-07-17 13:42
I am not sure how to handle this in ivy since these placeholders need to map to ivy instructions in the template function... For example the compiled ivy template in the repo given in this issue includes:

```ts
ɵɵelementStart(2, "p");
ɵɵi18nStart(3, I18N_2);
ɵɵelement(4, "b");
ɵɵelement(5, "a", 0);
ɵɵelement(6, "sup");
ɵɵelement(7, "strong");
ɵɵi18nEnd();
ɵɵelementEnd();
```

Note that the template instructions effectively hard code the elements that can appear in the template. The "element markers" (e.g. `�#5�`) are referenced by their index in the instructions (e.g. `ɵɵelement(5, "a", 0);`). There is currently no way for the i18n message to add additional elements to this output.

I am not sure if this was ever intended to work this way in ViewEngine, but if so, it appears to be a breaking change in Ivy, and I am not sure how we could change Ivy to accommodate it. Perhaps @mhevery has some ideas?

**Comment by mhevery** [comment] 2020-07-17 17:10
Sadly, this is working as intended (but we should throw a better error message).

In VE the translation would happen before the VE would compile the template. As a result any DOM duplication would not be a problem.

In Ivy the i18n happens after Ivy compiles the template. This is so we can have runtime i18n. Because of this the act of compilation "fixes" the number of DOM elements and i18n can only change the text, rearrange elements and or remove the elements. It is not possible to add an element since we would not know how to attach directives or any expressions to it. 

I think the proper behavior here is to have a better error messages which detects and errors when the i18n anchors are duplicated.

**Comment by petebacondarwin** [comment] 2020-07-17 17:20
Right. This is actually documented in our [ivy-compatibility docs](https://angular.io/guide/ivy-compatibility#less-common-changes), although I think that the translation tooling could provide some help here.

> Extra HTML tags in i18n translations that are not present in the source template itself will be rendered as plain text (previously, these tags would render as HTML).

**Comment by petebacondarwin** [comment] 2020-07-18 21:33
So what to do if you are faced with this breaking change?

There appears to be two approaches:

1. Try to break up your i18n messages into smaller pieces that do not need to contain elements.
2. Add additional empty elements in the original source template that can be utilised by translated message.

**Comment by jelbourn** [comment] 2020-10-12 22:34
Closing this since the change is working as expected due to the architectural change in how i18n works for ivy.

**Closed by jelbourn** 2020-10-12 22:34 UTC
Labels: comp: i18n, core: DOM rendering, discussion, engine: ivy, freq1: low, state: works-as-expected
