### ISSUE TITLE
Hybrid application break some Router functionality (preloading and default route).

### ISSUE THREAD

**Issue by MarenkovIgor** [angular/angular#24125] opened 2018-05-25 11:25 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

1) Preloading of lazy modules not work in hybrid application (app that includes angularjs and angular + UpgradeModule).
2) Default route not work in hybrid application.

## Expected behavior

1) Preloading feature in hybrid application should work same as in angular-only application.
2) Default route feature should work same as in angular-only application.

## Minimal reproduction of the problem with instructions

(unable to create stackblitz sample due to stackblitz bug https://github.com/stackblitz/core/issues/215)
1) Download sample application: https://drive.google.com/open?id=1GZKWBD6N4MsUiEsBKGDWP9T-p6UG4Fj6
(based on sample from https://angular.io/guide/singleton-services)
2) npm i
3) ng server
4) ng serve, open http://localhost:4200
* preloading works fine
![image](https://user-images.githubusercontent.com/13851068/40541756-586bcd0a-6047-11e8-8d07-50d379ef323b.png)
* redirect to default route works fine
![image](https://user-images.githubusercontent.com/13851068/40541783-7344de6e-6047-11e8-9fa7-50d2bb00c260.png)
5) kill server
6) ng serve -c hybrid, open http://localhost:4200
(it enables hybrid application setup based on https://angular.io/guide/upgrade)
result:
* preloading not working
![image](https://user-images.githubusercontent.com/13851068/40541887-de4b9d88-6047-11e8-9f55-44a4c94b0cfd.png)
* default redirect not working
![image](https://user-images.githubusercontent.com/13851068/40541901-ed2ecbf4-6047-11e8-9fbb-cab91236d8f4.png)

## What is the motivation / use case for changing the behavior?

Hybrid application works wrong.

## Environment

<pre><code>
Angular version: 6.0.3

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v8.10.0
- Platform:  Windows 10

**Comment by gkalpak** [comment] 2018-05-26 22:03
This happens because preloading is tied to `APP_BOOTSTRAP_LISTENER`, which unfortunately is not invoked when using `ngDoBootstrap` (instead of a `bootstrap` component).

This issue is discussed in #14081. See https://github.com/angular/angular/issues/14081#issuecomment-360825570 for more details.

In your case, you could work around the issue by manually calling the bootstrap listeners, with something like:

```ts
export class AppModule {
  constructor(
      @Inject(APP_BOOTSTRAP_LISTENER) private bootstrapListeners: (() => void)[],
      private upgrade: UpgradeModule) {}

  ngDoBootstrap() {
    if (environment.hybrid) {
      this.upgrade.bootstrap(document.body, [...], {strictDi: true});
      this.bootstrapListeners.forEach(listener => listener());

      // Note:
      // Theoretically, bootstrap listeners should be called with `ComponentRef` corresponding
      // to the bootstraped component. There is no bootstrap component when calling 
      // `ngDoBootstrap()`, but all bootstrap listeners I've seen so far don't really care
      // about the `ComponentRef` (so passing `undefined` is fine).
    }
  }
}
```

##
Closing as duplicate of #14081.

**Closed by gkalpak** 2018-05-26 22:04 UTC
