### ISSUE TITLE
Add stream of `touch` events to NgControl

### ISSUE THREAD

**Issue by ovangle** [angular/angular#14433] opened 2017-02-12 11:25 UTC
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

There is currently no stream of events exposed by `AbstractControlDirective` which allows a component to respond when the value of the `touched` property changes on the control.

The currently exposed streams are:
- `valueChanges`, emitted when the control value is changed
- `statusChanges`, emitted when control validity is rechecked.

A "touch" (blur) event can be emitted without altering the control's validity or value, so neither of the streams can be bound in order to intercept these events.

**Minimal reproduction of the problem with instructions**
```
@Component({
  template: `
    ... <ng-content select="[formControl], [formControlName], [ngModel]"></ng-content>...  
  `
})
class MyComponent {
 @ContentChild(NgControl) control: NgControl;

  ngAfterViewInit() {
    // Bind to the moment the 'touched' property of the control is set.
    // Neither statusChanges or valueChanges are emitted at this time.
    this.control.???
  }
}
```

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** all
 
* **Language:** all

**Comment by DzmitryShylovich** [comment] 2017-02-12 11:27
`(blur)="onBlur()"`?

**Comment by ovangle** [comment] 2017-02-12 11:30
The `touched`/`untouched` interface is exposed on `AbstractControlDirective` and all value accessors are required to implement `registerOnTouch`. Why should model driven forms still have to bind to the blur event on the template?

**Comment by jackjamieson** [comment] 2017-06-07 16:09
Right now I have to explicitly trigger a value change using `(blur)="form.controls['field'].setValue(form.controls['field'].value)"` and use `valueChanges` to make this work.

**Comment by kara** [comment] 2017-11-03 22:17
Looks like a dupe of https://github.com/angular/angular/issues/10887

**Closed by kara** 2017-11-03 22:17 UTC
Labels: comp: forms
