### ISSUE TITLE
Version -alpha.38 npm package missing rxjs

### ISSUE THREAD

**Issue by Successful** [angular/angular#4516] opened 2015-10-04 16:36 UTC
Don't know if this is the right place to post this bug, please let me know if it isen't.

Failing to install latest angular2 package with npm:

npm ERR! 404 Not Found
npm ERR! 404 
npm ERR! 404 'reactivex/rxjs' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 It was specified as a dependency of 'angular2'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.
npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Common7\\IDE\\Extensions\\Microsoft\\Web Tools\\External\\\\node\\node" "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Common7\\IDE\\Extensions\\Microsoft\\Web Tools\\External\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd C:\************
npm ERR! node -v v0.10.31
npm ERR! npm -v 1.4.9
npm ERR! code E404

**Comment by BobbieBarker** [comment] 2015-10-04 19:37
Windows 10, clean npm install angular2

no errors. I would suggest the problem might be with your OS, or the version of npm you're running, but not with this repository.

**Comment by sclausen** [comment] 2015-10-04 19:50
got the same issue. using ubuntu 14.04.3

**Comment by sclausen** [comment] 2015-10-04 19:52
the thing is, I can make a clean `npm install angular2` but wanted to use it as a dependency in a meteor package. angular@2.0.0-alpha.37 works fine, but 38 throws this error

**Comment by robwormald** [comment] 2015-10-05 00:24
@sclausen are you able to install / require the `@reactivex/rxjs` repo in the meteor package? that's using npm's namespaces/scopes, so perhaps that's unsupported by whatever meteor-npm is doing?

**Comment by sclausen** [comment] 2015-10-05 04:19
Yes, that's exactly what I'm trying to do. I'll look how meteors npm stuff works and file an issue there. Thanks!

**Comment by sclausen** [comment] 2015-10-05 06:48
I think its a meteor problem. The npm version they use is way to old to support this package naming.

**Comment by robwormald** [comment] 2015-10-05 06:50
ah, that's a shame. @Successful i would guess your issue is probably related to an older version of NPM as well, looking at the error - are you using it from within Visual Studio?

**Comment by sclausen** [comment] 2015-10-05 07:51
My special problem is a meteor problem. The npm version they use is way to old to support this package naming. I filed an issue there meteor/meteor/issues/5365

**Comment by pkozlowski-opensource** [comment] 2015-10-05 08:01
OK, closing as duplicate of meteor/meteor#5365 then

**Closed by pkozlowski-opensource** 2015-10-05 08:01 UTC

**Comment by robwormald** [comment] 2015-10-05 08:19
Looks like minimum npm version is 2.7.0, for future reference.

**Comment by Successful** [comment] 2015-10-05 17:52
I am so embarrassed :-1: updating node and npm solved my issue.
Thanks all.
