### ISSUE TITLE
Interceptor schematic

### ISSUE THREAD

**Issue by eTallang** [angular/angular#19404] opened 2017-09-26 12:54 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

Angular 4.3 introduced Interceptors. I think it would be natural to implement a schematic in Angular CLI to generate an interceptor.

**Comment by devoto13** [comment] 2017-09-26 13:17
Duplicate of https://github.com/angular/angular-cli/issues/6937.

**Closed** 2017-09-26 13:31 UTC
