### ISSUE TITLE
Support for TypeScript 2.8.1?

### ISSUE THREAD

**Issue by thnk2wn** [angular/angular#23877] opened 2018-05-12 22:55 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ x ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
Running webpack (4.8.2) results in "ERROR in The Angular Compiler requires TypeScript >=2.7.2 and <2.8.0 but 2.8.1 was found instead."

Unfortunately I can't downgrade as TypeScript 2.8.1 fixes this issue for me: https://stackoverflow.com/questions/49468616/cannot-read-property-externalmoduleindicator-of-undefined-while-running-unit-t

## Expected behavior
Version of Angular supporting TypeScript 2.8.1

## Minimal reproduction of the problem with instructions
git clone https://github.com/thnk2wn/cake-dotnetcore-sample.git

Run webpack prod. In my case I was doing so via the cake script:

cd favgif.web/build
./build.sh -c Debug

## What is the motivation / use case for changing the behavior?
Need typescript 2.8.1 for a fix it provides but latest Angular limits to earlier TS version.

## Environment

<pre><code>
Angular version: 6.0.1

Browser (N/A here):
- [ x ] Chrome (desktop) Version 66.0.3359.170 (Official Build) (64-bit)
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.3.0  
- Platform:  Mac 10.13.4

Others:

</code></pre>

**Comment by ericmartinezr** [comment] 2018-05-12 23:06
https://github.com/angular/angular/issues/23779

**Comment by robwormald** [comment] 2018-05-13 00:15
duplicate of #23779

**Closed by robwormald** 2018-05-13 00:15 UTC
