### ISSUE TITLE
Service worker not install in angular v8

### ISSUE THREAD

**Issue by ngohungphuc** [angular/angular#35573] opened 2020-02-20 08:46 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package

        "@angular/animations": "~8.2.14",
        "@angular/common": "~8.2.14",
        "@angular/compiler": "~8.2.14",
        "@angular/core": "~8.2.14",
        "@angular/forms": "~8.2.14",
        "@angular/platform-browser": "~8.2.14",
        "@angular/platform-browser-dynamic": "~8.2.14",
        "@angular/pwa": "^0.900.2",
        "@angular/router": "~8.2.14",
        "@angular/service-worker": "~8.2.14",

### Description

I'm always get the error 

![chrome_PUv3VOTLE9](https://user-images.githubusercontent.com/13591213/74916000-ab0ced00-53f7-11ea-8a64-8c17dfcc680b.png)

## 🌍  Your Environment

This is how I config the code

angular.json
```
"assets": [
    "src/assets/favicon.ico",
    "src/assets",
    "src/manifest.json"
],
"configurations": {
    "production": {
        // other is ommitted
        "serviceWorker": true,
        "ngswConfigPath": "ngsw-config.json"
    }
}
```

ngsw-config.json
```
{
    "$schema": "./node_modules/@angular/service-worker/config/schema.json",
    "index": "/index.html",
    "assetGroups": [
      {
        "name": "app",
        "installMode": "prefetch",
        "resources": {
          "files": [
            "/assets/favicon.ico",
            "/manifest.json",
            "/*.css",
            "/*.js"
          ]
        }
      }, {
        "name": "assets",
        "installMode": "lazy",
        "updateMode": "prefetch",
        "resources": {
          "files": [
            "/images/**"
          ]
        }
      }
    ]
  }
```

app.module.ts
```
    imports: [
        BrowserModule,
        ServiceWorkerModule.register("ngsw-worker.js", {
            enabled: environment.production
        })
    ],
```

index.html
```
<link rel="manifest" href="manifest.webmanifest">
  <meta name="theme-color" content="#1976d2">
```

**Comment by gkalpak** [comment] 2020-02-20 12:33
@ngohungphuc, can you share a minimal reproduction (or detailed steps on how to reproduce the issue)? There is not much we can do without a reproduction (i.e. an actual project we can run to see the problem in action).

**Comment by christianliebel** [comment] 2020-02-20 18:07
@ngohungphuc Remember that you need to run `ng build --prod` in order to enable service worker generation. `ng serve` or `ng serve --prod` won’t have the service worker attached.

**Comment by ngohungphuc** [comment] 2020-02-21 03:48
@christianliebel Yes. I'm already build my source code into prod code and deploy. I'm not do that in local

**Comment by indraraj26** [comment] 2020-02-22 04:52
Make sure your domain has ssl certificate, SW is works on HTTPS

**Comment by ngohungphuc** [comment] 2020-02-24 04:01
@indraraj26 I'm deploy to azure website which is run on HTTPS. Everything is working fine on previous version which mean angular v7

**Comment by gkalpak** [comment] 2020-02-24 11:03
As mentioned in https://github.com/angular/angular/issues/35573#issuecomment-588998823, there is no way for us to investigate this without a reproduction. Based on the info you provided, it seems that you have a `manifest.json` file (mentioned in `angular.json` and `ngsw-config.json`), but you refer to it as `manifest.webmanifest` (which does not exist) in your HTML:

```html
<link rel="manifest" href="manifest.webmanifest">
```

So, make sure the name of the file matches the `href`.

##
Closing, because the issue is not actionable in its current state.

**Closed by gkalpak** 2020-02-24 11:03 UTC
Labels: comp: service-worker, state: Needs repro
