### ISSUE TITLE
[Http] Header class does not set key value pairs correctly in Chrome

### ISSUE THREAD

**Issue by Batch1211** [angular/angular#11641] opened 2016-09-15 19:42 UTC
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 

The Header class in the Http bundle uses the normalize function to normalize the header key, before adding the header key value pair to the header. In chrome the normalize function always transforms the header key to lower case. However, in the header we almost always want the first letter of the header key to be upper case.
**Expected behavior**

Make sure, that the header key is not modified.
**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

This problem is especially a problem, when we want to set authorization headers
**Please tell us about your environment:**

latest Chrome Browser on the latest Mac OS
* **Angular version:** 2.0.0-rc.X

Angular 2.0.0 stable
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 

 This problem only occurs in Chrome (Firefox was also tested)
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
 
* **Node (for AoT issues):** `node --version` =

**Comment by pkozlowski-opensource** [comment] 2016-09-15 19:44
Duplicate of #11624

**Closed by pkozlowski-opensource** 2016-09-15 19:44 UTC
