### ISSUE TITLE
Control flow migration: *ngIf under switch doesn't migrate to new syntax

### ISSUE THREAD

**Issue by sunilrathore24** [angular/angular#56253] opened 2024-06-04 10:15 UTC
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

for such cases when i run control flow migration

```
  <span [ngSwitch]="customField.type">
              <span *ngIf="!customField.listOfVals">
                <input
                  *ngSwitchCase="dataType.StringType"
                  type="text"
                  [required]="customField.isRequired || null"
                  [formControlName]="customField.name"
                  trqFormFieldItem
                  trqInput
                  [attr.aria-label]="customField.displayName"
                  [trqId]="item.offeringId + customField.name" />
                 </span>
                  <trq-datetimepicker
                  *ngSwitchCase="dataType.DateType"
                  ariaLabel="Basic"
                  [placeholder]="ecomAppLabels.selectDate | trqTranslateStatic"
                  [maskInput]="false"
                  [config]="dateConfig"
                  trqFormFieldItem
                  [required]="customField.isRequired || null"
                  [formControlName]="customField.name"
                  [trqId]="item.offeringId + customField.name"
                  [exportFormat]="'YYYY-MM-DD'">
                </trq-datetimepicker>
                </span>
```
it gives the error - 
[ngSwitch]: Error: Text node: "
◬" would result in invalid migrated @switch block structure. @switch can only have @case or @default as children.

since the above code is valid in previous angular version why control flow migration shows error for this?

### Please provide the exception or error you saw

```true
[ngSwitch]: Error: Text node: "
◬" would result in invalid migrated @switch block structure. @switch can only have @case or @default as children.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
"devDependencies": {
    "@angular-devkit/build-angular": "18.0.2",
    "@angular-devkit/core": "18.0.2",
    "@angular-devkit/schematics": "18.0.2",
    "@angular-eslint/eslint-plugin": "17.3.0",
    "@angular-eslint/eslint-plugin-template": "17.3.0",
    "@angular-eslint/template-parser": "17.3.0",
    "@angular/cli": "~18.0.0",
    "@angular/compiler-cli": "18.0.1",
    "@angular/language-service": "18.0.1",
    "@babel/core": "~7.22.19",
    "@commitlint/cli": "^17.0.2",
    "@commitlint/config-conventional": "^17.0.2",
    "@commitlint/prompt-cli": "^17.0.2",
    "@mjhenkes/postcss-rtl": "^2.0.0",
    "@ngrx/store-devtools": "17.0.1",
    "@nx/eslint-plugin": "19.1.1",
    "@nx/jest": "19.1.1",
    "@nx/js": "19.1.1",
    "@nx/storybook": "19.1.1",
    "@nx/web": "19.1.1",
    "@nx/webpack": "19.1.1",
    "@nx/workspace": "19.1.1",
    "@schematics/angular": "18.0.2",
    "@storybook/addon-a11y": "^8.1.5",
    "@storybook/addon-essentials": "^8.1.5",
    "@storybook/addon-jest": "^8.1.5",
    "@storybook/angular": "^8.1.5",
    "@storybook/core-server": "^8.1.5",
    "@torque/eslint-plugin": "14.0.0-next.5",
    "@torque/nx-plugin": "14.0.0-next.5",
    "@types/jest": "29.4.4",
    "@types/node": "^18.16.9",
    "@typescript-eslint/eslint-plugin": "5.62.0",
    "@typescript-eslint/parser": "5.62.0",
    "JSONStream": "^1.3.3",
    "barrelsby": "^2.4.0",
    "circular-dependency-plugin": "^5.2.2",
    "cross-env": "^7.0.3",
    "css-loader": "^6.7.1",
    "eslint": "8.52.0",
    "eslint-config-prettier": "9.0.0",
    "eslint-plugin-eslint-comments": "^3.2.0",
    "eslint-plugin-import": "2.29.0",
    "eslint-plugin-jest": "^27.0.0",
    "eslint-plugin-rxjs": "5.0.3",
    "eslint-plugin-storybook": "^0.8.0",
    "exports-loader": "^4.0.0",
    "git-grep": "^0.1.0",
    "globby": "^10.0.1",
    "husky": "^7.0.0",
    "jest": "29.4.3",
    "jest-createspyobj": "^2.0.0",
    "jest-environment-jsdom": "29.4.3",
    "jest-marbles": "^3.0.3",
    "jest-preset-angular": "14.1.0",
    "jest-teamcity": "^1.11.0",
    "jsonc-eslint-parser": "^2.1.0",
    "lint-staged": ">=10.0.8",
    "ng-mocks": "^14.13.0",
    "npm-run-all": "^4.1.5",
    "nx": "19.1.1",
    "nx-stylelint": "15.0.0",
    "patch-package": "6.4.7",
    "postcss": "^8.4.14",
    "postcss-aspect-ratio": "^1.0.2",
    "postcss-clean": "^1.2.2",
    "postinstall-prepare": "^2.0.0",
    "prettier": "2.7.1",
    "replace-in-file": "^6.2.0",
    "rimraf": "^2.6.3",
    "sort-package-json": "^1.50.0",
    "style-loader": "^3.3.1",
    "stylelint": "^15.10.3",
    "stylelint-config-idiomatic-order": "^8.1.0",
    "stylelint-config-standard-scss": "^11.0.0",
    "stylelint-declaration-strict-value": "^1.10.4",
    "stylelint-scss": "^5.2.1",
    "typescript": "5.4.5",
    "webpack": "5.88.2",
    "webpack-cli": "^5.1.0",
    "yargs": "^12.0.5"
  },
```

**Comment by crisbeto** [comment] 2024-06-04 10:37
It's because the migration would turn it into something like:

```
@switch (...) {
  @if (...) {
    @case (...) {}
  }
}
```

This isn't supported in the new syntax which requires `@case` to be directly inside `@switch`.

**Comment by JeanMeche** [comment] 2024-06-04 10:37
There is not equivalent of what you wrote in the new syntax. 

`@if` can't be in a `@switch` block. x

**Comment by crisbeto** [comment] 2024-06-04 10:41
You could either wrap the `@switch` with the inner `@if`, or copy the `@if` into the individual `@case` blocks.

**Comment by thePunderWoman** [comment] 2024-06-04 13:54
Since this is working as intended and already provides the appropriate error case, I'm going to close this, but feel free to ask questions here if you have more.

**Closed by thePunderWoman** 2024-06-04 13:54 UTC
