### ISSUE TITLE
Angular 17 SSR does not correctly generate static pages when paired with Firebase

### ISSUE THREAD

**Issue by toddhd** [angular/angular#54889] opened 2024-03-15 17:37 UTC
### Which @angular/* package(s) are the source of the bug?

platform-server, Don't known / other

### Is this a regression?

Yes

### Description

I am creating a simple quiz app using Angular 17 w/ SSR, AngularFire 17, and Firebase. The app has one dynamic component, the Quiz component, which takes in a Doc ID via the URL, and then fetches the quiz data from the Firebase server. I make sure that the Quiz page(s) are rendered via SSR by including them in a routes.txt file.

The problem I'm having is that the rendered Quiz pages have no data from the server. This is really important to me, because the player should be able to share their score to social media after playing, and making that happen involved updating the Open Graph tags with the correct data. Since FB scrapes the pages before any JavaScript fires, the only way to make sure the correct tags are in place is to pre-generate the pages. In other words, even if the page loads the Quiz dynamically for the player, it is not working for the scraper, and that breaks everything. 

I have asked for help on StackOverflow and the /r/Angular forum on Reddit, and have received no replies at all. (https://stackoverflow.com/questions/78157528/angular-17-ssr-doesnt-generate-the-static-pages-with-any-data-when-using-fireba)

Since this particular project has several "moving parts" (Database setup, SSR generation) it is difficult to impossible to create a minimal reproduction of the bug. 

I've researched this problem on the web. Generally speaking, the only info available about this topic seems to be related to older versions of both Firebase, and related to "Angular Universal" which has since been replaced by SSR. In other words, those solutions no longer apply. What I have learned however is that Angular does not seem to wait for Firebase to fully resolve before rendering the page. The thing is, I have no idea how to fix that. I don't how to prove it either, however it does seem like a reasonable assumption. 

Here is the code that loads the data from Firebase in the constructor of the Quiz component. This works fine locally. It just doesn't generate the SRR correctly. 

```
  import { Component, inject, OnInit } from '@angular/core';
  import { Firestore, getDoc, doc, DocumentSnapshot } from '@angular/fire/firestore';
  import { QuizData } from '../../interfaces/quiz-data';
  import { ActivatedRoute, Router } from '@angular/router';
  import { Meta } from '@angular/platform-browser';
  import { RouterModule } from "@angular/router";
  
  export class QuizComponent implements OnInit {

	  private firestore: Firestore = inject(Firestore);
	  documentID: string = '';
	  
	  constructor(private route: ActivatedRoute, private metaTagService: Meta, private router: Router) {}
	  
	  ngOnInit(): void {
    this.documentID = this.route.snapshot.paramMap.get('id')!;

    getDoc(doc(this.firestore, 'quizzes', this.documentID)).then((doc) => {
      // Set the quiz data
      this.quiz = doc.data() as QuizData;

      // Assign the first question to the current question
      this.currentQuestion = this.quiz.questions[0];

      // Update the meta tags
      this.metaTagService.updateTag({ property: 'og:title', content: this.quiz.topic + ' Quiz' });
      this.metaTagService.updateTag({ property: 'og:description', content: 'Think you know your ' + this.quiz.topic + ' trivia?' });
      this.metaTagService.updateTag({ property: 'og:url', content: "https://www.example.com/quiz/" + this.documentID });
      this.metaTagService.updateTag({ property: 'og:image', content: this.bgImage });
    });
   }
  }
```

### Please provide the exception or error you saw

```true
There is no error per se, the error is that the page is generated without the Quiz data or the updated tags. It appears that Angular is not waiting for the data before continuing to render the page.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.2.3
Node: 20.10.0
Package Manager: npm 10.5.0
OS: win32 x64

Angular: 17.2.4
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1702.3
@angular-devkit/build-angular   17.2.3
@angular-devkit/core            17.2.3
@angular-devkit/schematics      17.2.3
@angular/cdk                    17.2.2
@angular/cli                    17.2.3
@angular/fire                   17.0.1
@angular/material               17.2.2
@angular/ssr                    17.2.3
@schematics/angular             17.2.3
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.4
```

### Anything else?

I know you guys say to not use this as "code support" but my attempts to resolve the issue on StackOverflow have failed, and everything I can find so far seems to indicate that "I'm doing it correctly", so I'm hoping you can shed some light on what the problem is or how to fix it? Thanks!

**Comment by alan-agius4** [comment] 2024-03-15 21:56
Duplicate of https://github.com/angular/angular/issues/54267

**Closed by alan-agius4** 2024-03-15 21:56 UTC
