### ISSUE TITLE
iOS 11.3 new service worker safari hangs on image upload

### ISSUE THREAD

**Issue by MatteoNY** [angular/angular#23244] opened 2018-04-08 01:04 UTC
Build:
Angular CLI: 1.7.3
Node: 8.1.4
OS: darwin x64
Angular: 5.2.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, service-worker

@angular/cdk: 5.2.4
@angular/cli: 1.7.3
@angular/flex-layout: 5.0.0-beta.14
@angular/material: 5.2.4
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.7.2
webpack: 3.11.0

New Safari Experimental service worker is on by default and works fine
as long as you do not upload an image in your PWA then it appears to hang.  Getting some sort of Firebase storage issue. If I turn off Safari service worker my app works as expected. 
Using latest firebase angularfire2 storage with task to show pre-loader (using angularfire2 based on David East's blog (see below). PWA worked fine before iOS 11.3 update but with service worker on by default will fail if uploading an image. In the prior iOS release there was an bug when using the camera if the PWA was added to home screen the camera was disabled. Apple fixed the camera bug with iOS 11.3.
David East's Blog to upload image using Angular Angularfire2:
https://blog.angular.io/file-uploads-come-to-angularfire-6842352b3b47

Getting Firebase error from Safari Desktop macOS High Sierra version 10.13.4 (Apr 2018 update)
code_: "storage/unknown"
message_: "Firebase Storage: An unknown error occurred, please check the error payload for server response."
name_: "FirebaseError"
serverResponse_: "Client uploaded to the wrong offset (262144 instead of 0)."

NOT SURE IF A NEW ANGULAR POLYFILL  IS NEEDED TO ENABLE SERVICE WORKERS. 

THANKS!

FOUND ISSUES WITH SAFARI AND SERVICE WORKERS ENABLED HANGS ANGULAR PWA USING ANGULARFIRE2 UPLOAD. 
    
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ x] Safari (desktop) version XX
- [ x] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by markgoho** [comment] 2018-04-08 12:39
@MatteoNY consider opening an issue over at the [AngularFire2 repo](https://github.com/angular/angularfire2) for this issue you're experiencing.

As far as what it takes to enable service workers, there is very good documentation here: https://angular.io/guide/service-worker-intro

**Comment by MatteoNY** [comment] 2018-04-13 12:32
Mark: (markgoho) thanks for the suggestion to review the Angular.io docs.

I subscribe to #AskFirebase on YouTube.com a video on PWAs mentioned that service-workers need to ignore Firebase's dynamic data because it has advanced offline features. 
https://youtu.be/iHqqUoqvYx4

This was an Ah-ha moment! After reading more about service-workers, I'm not exactly clear on what to put in the ngsw-config.json file to ignore dynamic Firebase. I don't want it to also ignore static assets. 

I've been following PWA's since the last ng-conf and I've taken a course on Udemy where the instructor got into writing a service-worker. My preference is to use the one with the Angular CLI.  
I can experiment with ngsw-config.json file but I'd rather spend the time exploring Angular Elements. 

I have a few suggestions:
1)  A how to guide on Angular.io on how exclude dynamic data from a service (Firebase where it's not needed - as per the video). For example, visit Chrome's network tab and view dynamic/static data and to add a node, for example, under the dataGroups add: ", { name: firebase-dynamic:  !**firebase }"  in the ngsw-config.json file. I'm making this up, but it would be nice to know.

2) Add a new feature to Chrome's Lighthouse to use it's magic to inform me that since I'm using Firebase add this to your ngsw-config.json file to ignore dynamic Firebase data (not needed), static data will persist :-). Possibly a URL to a tutorial (suggestion 1) on how to optimize your service-worker when using Firebase. 

As I've mentioned in prior post,  if I disable the service-worker via the main.ts (  // navigator.serviceWorker.register('/ngsw-worker.js');). My app works as expected on Safari (Mac and iPhone) as well as the other browsers. 

This appears to not to be a service-worker bug but a configuration for the service-worker. 
I hope the above helps. 

Many thanks,
Matt

**Comment by aSegatto** [comment] 2018-07-12 13:04
We are experiencing a similar issue while uploading a text file. We excluded firebase comunications from the ngsw cache by adding :
<pre><code>
"dataGroups": [
    {
      "name": "firebase",
      "urls": [
        "https://firebasestorage.googleapis.com/**"
      ],
      "cacheConfig": {
        "timeout":"10s",
        "maxSize": 10,
        "maxAge": "1s",
        "strategy": "freshness"
      }
    }
  ]
</code></pre>

in the ngsw-config file, but nothing changed.

**Comment by gkalpak** [comment] 2018-07-12 15:44
Just to add some info, (despite what that video says about Angular's SW implementation) I don't think you need any special configuration to _not_ cache speccific requests. The SW will only cache what it is explicitly configured to cache.

**Comment by aSegatto** [comment] 2018-07-13 08:20
Ok, how can we further investigate what's happening ? is there a way to see what's going on in the service worker ? 
We believe that posting data to a cloud function without multi part should avoid this issue, but we 'd like to do this as the last option.

**Comment by gkalpak** [comment] 2018-07-13 11:10
SWs are just javascript code, so you can debug them as usual (add breakpoints etc). That's what I would do if I wanted to investigate an issue like this.

**Comment by kenle** [comment] 2018-07-16 03:59
I'm still having a problem with this even with dataGroup settings...

**Comment by arikanorh** [comment] 2018-08-01 13:15
I'm current hitting the same problem. It doesnt work on Safari on iOS. But cant debug since i cant see the console

**Comment by harcomtech** [comment] 2018-08-09 23:27
Also experiencing this issue while uploading to a pre-signed AWS S3

**Comment by uufish** [comment] 2018-08-21 16:13
I have rewritten the file `ngsw-worker.js` after the build using node.js.

```
onFetch(event) {
```

to

```
onFetch(event) {
        if (event.request.url.indexOf('firebasestorage.googleapis.com') !== -1) { return; }
```

**Comment by 24hours** [comment] 2018-09-04 04:26
I have the same issue. I need to cache firebase storage for offline uses so excluding url is not a viable solution.

**Comment by aSegatto** [comment] 2018-09-04 12:00
We solved this issue uploading the files to a cloud function that saves the data in the storage. Hope this can help while we wait for a fix ...

**Comment by antonellof** [comment] 2018-09-05 07:09
Same issue. 
Setting:
`"serviceWorker": false`
in angular.json, and then
`ng build --prod`
after build firebase storage upload works normally in safari.

**Comment by gkalpak** [comment] 2018-09-17 10:47
I am going to close this, because it is not clear (to me) how to reproduce the problem. If someone could post a minimal reproduction (e.g. a standalone repo) with step-by-step instructions, I would be happy to take a look.

**Closed by gkalpak** 2018-09-17 10:47 UTC
Labels: comp: service-worker, freq1: low, severity3: broken, type: bug/fix

**Comment by aSegatto** [comment] 2018-09-17 12:15
You can find a minimal reproduction at  [this URL](https://ngws-bug.firebaseapp.com/). Source code [ here](https://github.com/aSegatto/ngsw-bug). Upload button uploads a file containing timestamp to firestore. Then you can download it and check if upload worked correctly.

**Comment by gkalpak** [comment] 2018-09-17 14:08
Thx (and sorry I missed that in the first place 😇).
I took a brief look at the code and app and also searched around and this seems to be related with fetch. I am not sure if we would be able to workaround this in `@angular/service-worker` (I couldn't get to the bottom of it because tested via Saucelabs, as I don't have access to "irl" Safari).

One workaround that would work for sure (and is related to what was meant by _"service-workers need to ignore Firebase's dynamic data"_ in https://github.com/angular/angular/issues/23244#issuecomment-381120890 - I originally missed the point of that comment), is to support ignoring specific request altogether in the SW, so that the browser handles them instead.

What the SW does now, is that it passes the request through to the network using `fetch` (because SWs don't have access to XHR), but this fails on browsers where `fetch` is broken.

This problem is being tracked in #21191 (but if someone can come up with a different workaround for uploads specifically, feel free to post it here instead or open a new issue).

**Comment by koraysels** [comment] 2019-01-25 17:34
following @uufish suggestion I am now using [replace-in-file](https://www.npmjs.com/package/replace-in-file) from npm
I run this after my build. 

It excludes the firebase API from service worker caching... 
```
const replace = require('replace-in-file');
const options = {
  files: 'dist/browser/ngsw-worker.js',
  from: `onFetch(event) {`,
  to: `onFetch(event) {
        if (event.request.url.indexOf('firebasestorage.googleapis.com') !== -1) { return; }`,
};

replace(options)
  .then(changes => {
    console.log('Modified files:', changes.join(', '));
  })
  .catch(error => {
    console.error('Error occurred:', error);
  });
```

**Comment by GIOkafor** [comment] 2019-01-29 02:56
> following @uufish suggestion I am now using [replace-in-file](https://www.npmjs.com/package/replace-in-file) from npm
> I run this after my build.
> 
> It excludes the firebase API from service worker caching...
> 
> ```
> const replace = require('replace-in-file');
> const options = {
>   files: 'dist/browser/ngsw-worker.js',
>   from: `onFetch(event) {`,
>   to: `onFetch(event) {
>         if (event.request.url.indexOf('firebasestorage.googleapis.com') !== -1) { return; }`,
> };
> 
> replace(options)
>   .then(changes => {
>     console.log('Modified files:', changes.join(', '));
>   })
>   .catch(error => {
>     console.error('Error occurred:', error);
>   });
> ```

Does that go in your main.ts file?

**Comment by koraysels** [comment] 2019-01-29 08:03
@GIOkafor no i do this achter the build command. To do so you can an script property in your package.json. Or of you use pm2 to deploy you can run it with pm2 after ‘ng build —prod’

**Comment by avilao** [comment] 2019-02-18 22:03
But that removes caching completely right? Not just for safari.

**Comment by Robstaer** [comment] 2019-02-25 21:08
Is there a new update on this matter? I'm having the same problem: PWA on IOS breaks the image upload to firestorage, both in the webbrowser as well as in the app...

**Comment by maxime1992** [comment] 2019-02-26 09:22
Had to remove the service worker from prod because of that.
We've got plenty of tests, unit, integration and also E2E with Cypress but as Cypress doesn't support service workers correctly (few issues but basically it'd also cache the tests) we deactivate them while doing E2E testing. So everything was green and we thought we were ok deploying to prod. :face_with_head_bandage:

**Comment by koraysels** [comment] 2019-02-26 09:28
> But that removes caching completely right? Not just for safari.

No it just disables it for firebase requests...

**Comment by avilao** [comment] 2019-03-04 14:38
> > But that removes caching completely right? Not just for safari.
> 
> No it just disables it for firebasestorage requests...

Sorry my question wasn't specific. It disables firestoredatabase requests in all browsers, right?

**Comment by Robstaer** [comment] 2019-03-14 22:51
Why is this issue closed, even though not resolved yet?
@koraysels advice cannot be a long-term solution =/

**Comment by uufish** [comment] 2019-03-18 05:06
@gkalpak Please open this issue again. You can see bugs at [this URL](https://ngws-bug.firebaseapp.com/) on iOS 12.1.4.

```
failed with error: Firebase Storage: An unknown error occurred, please check the error payload for server response.
```

**Comment by gkalpak** [comment] 2019-03-18 10:56
As mentioned in https://github.com/angular/angular/issues/23244#issuecomment-422031629, this is a limitation in some browser's `fetch` implementation. There are some work arounds mentioned on this thread and the ability to "properly" work around such limitations is tracked in #21191 (hence this issue is closed).

**Comment by choopage** [comment] 2019-08-03 02:39
For those using AngularFire2, this issue is also mentioned
https://github.com/angular/angularfire2/issues/1439
https://github.com/angular/angularfire2/issues/1909
