### ISSUE TITLE
Getting Error encountered resolving symbol values statically. Calling function 'makeDecorator', function calls are not supported.

### ISSUE THREAD

**Issue by xtianus79** [angular/angular#14446] opened 2017-02-13 04:12 UTC
Wanted to be sure that this is when using the compiler CLI

**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

running ngc -p when using my typescript.cjs.json file which conifgures as such 

    {
       "compilerOptions": {
        "module": "commonjs",
       "target": "es5",
       "emitDecoratorMetadata": true,
       "experimentalDecorators": true,
       "moduleResolution": "node",
       "sourceMap": true,
       "removeComments": false,
       "noImplicitAny": false,
       "declaration": true,
       "outDir": "../dist"

      },
     "files": [
       "../src/multiple-date-picker.module.ts"
     ],
      "exclude": [
      "node_modules"
     ],
     "angularCompilerOptions": {
       "genDir": "../aot",
       "skipMetadataEmit": false
      }
    }

The compiled error is as follows (running npm run build):
Error encountered resolving symbol values statically. Calling function 'makeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol Injectable in /Users/mbp06/Repos/multiple-date-picker-a2/node_modules/@angular/core/src/di/metadata.d.ts, resolving symbol OpaqueToken in /Users/mbp06/Repos/multiple-date-picker-a2/node_modules/@angular/core/src/di/opaque_token.d.ts, resolving symbol OpaqueToken in /Users/mbp06/Repos/multiple-date-picker-a2/node_modules/@angular/core/src/di/opaque_token.d.ts

**Expected behavior**
it would compile correctly

**Minimal reproduction of the problem with instructions**

i don't have a way to reproduce it other than this is my package json configuration

      "devDependencies": {
    "@angular/compiler": "^2.4.7",
    "@angular/compiler-cli": "^2.4.7",
    "ts-loader": "^2.0.0",
    "typescript": "2.1.6",
    "typings": "^2.1.0",
    "rxjs": "^5.1.0",
    "gulp": "^3.9.1",
    "gulp-autoprefixer": "^3.1.1",
    "gulp-contrib-copy": "^0.1.2",
    "gulp-git": "^1.14.0",
    "gulp-jshint": "^2.0.4",
    "gulp-less": "^3.3.0",
    "gulp-minify-css": "^1.2.4",
    "gulp-rename": "^1.2.2",
    "gulp-replace": "^0.5.4",
    "gulp-uglify": "^2.0.1",
    "jshint": "^2.9.4",
    "jshint-stylish": "^2.2.1",
    "run-sequence": "^1.2.2",
    "yargs": "^6.6.0",
    "zone.js": "0.7.6"
  },
  "engines": {
    "node": ">=0.10.0"
  },
  "dependencies": {
    "@angular/common": "^2.X.X",
    "@angular/compiler": "^2.X.X",
    "@angular/core": "^2.X.X",
    "@angular/forms": "^2.X.X",
    "@angular/http": "^2.X.X",
    "@angular/platform-browser": "^2.X.X",
    "@angular/platform-browser-dynamic": "^2.X.X",
    "moment": "^2.X.X"
  }

**What is the motivation / use case for changing the behavior?**

I just want it to work

**Please tell us about your environment:**

angular-cli: 1.0.0-beta.19-3
node: 6.2.2
os: darwin x64

* **Angular version:** 2.0.X

2.4.7

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES6 compiled to ES5

* **Node (for AoT issues):** `node --version` = 6.2.2

**Comment by DzmitryShylovich** [comment] 2017-02-13 08:05
https://github.com/angular/angular/issues/14228

**Comment by serhiisol** [comment] 2017-02-14 10:56
Noticed same error. If I'll link npm module and run ```ng serve``` I'll get exactly the same error

```
ERROR in Error encountered resolving symbol values statically. Calling function 'makeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol NgModule in /Users/serhiysolonko/Development/ng31beta/node_modules/ng-components/node_modules/@angular/core/src/metadata/ng_module.d.ts, resolving symbol NgModule in /Users/serhiysolonko/Development/ng31beta/node_modules/ng-components/node_modules/@angular/core/src/metadata.d.ts, resolving symbol NgModule in /Users/serhiysolonko/Development/ng31beta/node_modules/ng-components/node_modules/@angular/core/src/core.d.ts, resolving symbol NgModule in /Users/serhiysolonko/Development/ng31beta/node_modules/ng-components/node_modules/@angular/core/index.d.ts, resolving symbol HttpModule in /Users/serhiysolonko/Development/ng31beta/node_modules/ng-components/http/http.module.ts, resolving symbol HttpModule in /Users/serhiysolonko/Development/signup/node_modules/ng-components/http/http.module.ts
```

**Comment by QuantumInformation** [comment] 2017-02-25 12:43
I also mentioned my same issue here:

https://github.com/angular/angular/issues/14228

in my case ng build --prod breaks, but ng serve works

**Comment by Bretto** [comment] 2017-03-01 22:54
What's the workaround ?

**Comment by Bretto** [comment] 2017-03-01 23:40
I had this issue with an external lib that had 2.x.x ng version that I was running in a 4.xx ng app. After updating the ng version in the lib the problem goes away. (the problem is there is no retro compatibility atm...)

**Comment by DzmitryShylovich** [comment] 2017-03-10 08:05
@xtianus79 did you fix it?

**Comment by shumpei** [comment] 2017-03-17 06:26
I met same issue, and researching the reason.
I found the external library (not app itself) has d.ts which imports '@angular/core', the issue is reproduced.

As @DocX said in [this issue](https://github.com/angular/angular-cli/issues/4440), I checked out [this repository](https://github.com/TheDocX/angular-cli-opaque) and build as AoT, the error was occured.

```
git clone https://github.com/TheDocX/angular-cli-opaque
cd angular-cli-opaque
ng build --prod --aot

...

ERROR in Error encountered resolving symbol values statically. Calling function 'makeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol Injectable in /Users/shumpei/dev/angular2/angular-cl
i-opaque/node_modules/angular-cli-opaque-window/node_modules/@angular/core/src/di/metadata.d.ts, resolving symbol OpaqueToken in /Users/shumpei/dev/angular2/angular-cli-opaque/node_modules/angular-cli-opaque-window/node_modules/@angular/core/src/di/opaque_token.d.ts, resolving symbol
 OpaqueToken in /Users/shumpei/dev/angular2/angular-cli-opaque/node_modules/angular-cli-opaque-window/node_modules/@angular/core/src/di/opaque_token.d.ts

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in '/Users/shumpei/dev/angular2/angular-cli-opaque/src'
 @ ./src/main.ts 4:0-74
 @ multi ./src/main.ts
```

And when I comment out [import statement which imports '@angular/core' of the external library of this project](https://github.com/TheDocX/angular-cli-opaque-window/blob/master/src/index.d.ts#L1), the error was suppressed.

I think it is the Angular's bug of static code analysis, isn't it?

**Comment by xtianus79** [comment] 2017-03-20 18:01
@DzmitryShylovich I did get mine working but had forgotten i posted this issue.  I added more dependencies which i think fixed the issue but I want to confirm.  Once I confirmed and have it working and tested I will reissue a post.

**Comment by Alsmile** [comment] 2017-03-25 11:41
+1

**Comment by Alsmile** [comment] 2017-03-28 16:30
It is OK. The custom NgModule  should include node_modules and demo code.  Npm publish should only include the src.

**Comment by tbosch** [comment] 2017-04-10 18:55
Closing as both, @Alsmile and @xtianus79 have their bugs fixed.

**Closed by tbosch** 2017-04-10 18:55 UTC

**Comment by amplexor-kv** [comment] 2017-04-20 15:20
I had the same issue. I'm using angular-cli. 
The problem with my setup was:
- a duplicate node_modules folder in the src/ folder and parent project folder, left there after an unsuccesful `npm install` executed from the wrong folder.
- After removing the duplicate node_modules, I was left with 'AppModule is not an ngModule' error.
- I then upgraded  typescript to `~2.2.2` in `package.json`
- `rm -rf node_modules`
- `yarn`
- This, however, caused ng build to fail with a slew of weird and unrelated errors.
- `rm -rf node_modules` once again
- `npm install`
- And that was it, the project now compiles.

I searched for at least 5 full working days, trying to get my setup back working after an initial failed upgrade. There are many, many issues and bugs logged in various projects with different solutions, so hopefully my solution will help somebody as well.

So in short what worked for me: 

1. make sure Typescript is the correct version (2.2.2 here) (both globally as well as in your package); 
2. install your dependencies with `npm` instead of `yarn` if you don't already have a `yarn.lock` file in place. 
3. Doublecheck for duplicate dependencies/remains of previous installations
