### ISSUE TITLE
Memory Leak when MouseEvent is triggered

### ISSUE THREAD

**Issue by cgatian** [angular/angular#20228] opened 2017-11-06 22:38 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior
Performing a mouse event on a component, even without event bindings leaks nodes.

## Expected behavior

Node count allocation after garbage collection should look like the image below (Reproduced by switching views and never clicking the "TEST" button):
![no-click](https://user-images.githubusercontent.com/1752170/32467636-6db0bd5e-c319-11e7-9fb8-95a05a0fa7b6.PNG)

Instead the actual memory graph looks like this:
![with-click](https://user-images.githubusercontent.com/1752170/32467685-942f1782-c319-11e7-8ea4-86a5418a4ee6.PNG)

## Minimal reproduction of the problem with instructions
Pull CLI Repo: https://github.com/cgatian/angular-mem-test
**OR** https://stackblitz.com/edit/angular-issue-20228
* Open app and Chrome Dev tools
* On performance tab click Collect Garbage and click record
* In app, navigate View2 via hyperlink
* Click button TEST on View 2
* Navigate to View1 via hyperlink
* Click Collect Garbage
* Stop test

Nodes should have the same count at the start of the test.

![perf-test](https://user-images.githubusercontent.com/1752170/32467611-53c3d0f2-c319-11e7-80d0-756dcfa19d97.gif)

* Tried disabling ZoneJS and problem still occurs. If button is clicked programmatically (using `element.click()`) leak does not occur.
* First try sometimes produces correct behavior. Performing the steps-to-recreate x2 or x3 in a row is consistent.
* I may be using the perf tools incorrectly 😃 

## What is the motivation / use case for changing the behavior?
Possible memory leak

## Environment

<pre><code>
Angular version: 5.0.0 (also 4.3.6)

Browser:
- [x] Chrome (desktop) version 62.0.3202.75 (Official Build) (64-bit)

</code></pre>

**Comment by Toxicable** [comment] 2017-11-06 22:52
A stack blitz would be great :p https://stackblitz.com/fork/angular-gitter

**Comment by cgatian** [comment] 2017-11-06 22:58
For you @Toxicable, why not! 😄 Updated testing instructions

**Comment by TGstone** [comment] 2018-06-26 19:12
We discovered similar problems with Angular 4,5 and 6 as well. Any ideas where the leak comes from? When will it be fixed?

**Comment by pkozlowski-opensource** [comment] 2020-05-27 07:10
I can no longer reproduce this node leak with the latest Angular v9 running ivy.
Here is the code I've used: https://angular-khejzk.stackblitz.io/view1

Here is the picture I'm getting:
![Screen Shot 2020-05-27 at 09 08 10](https://user-images.githubusercontent.com/973550/82988563-a872f280-9ff9-11ea-9ecf-53f10ff92b8c.png)

If anyone still bumps into similar issues please attach the exact stackblitz and specify the chrome version used. Closing this one for now as I can't reproduce any more - assuming it is fixed unless new evidence surfaces :-)

**Closed by pkozlowski-opensource** 2020-05-27 07:10 UTC
Labels: comp: core, core: event listeners, freq3: high, severity4: memleak, type: bug/fix

**Comment by cgatian** [comment] 2020-05-28 12:58
Reran my original reproduction code and can also confirm it's fixed!
![angular-issue](https://user-images.githubusercontent.com/1752170/83144170-00c0f780-a0c1-11ea-8614-34e40fb8b274.gif)
@pkozlowski-opensource my apologies for not giving this a try once v9 released. Thank you for taking the time to confirm.

**Comment by pkozlowski-opensource** [comment] 2020-05-28 13:08
Thnx for confirming @cgatian - glad it is fixed!
