### ISSUE TITLE
Angular supports optional chaining in local modules but doesn't work with node_modules

### ISSUE THREAD

**Issue by Yegorich555** [angular/angular#41657] opened 2021-04-16 14:28 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/compiler

### Description

I'm using Typescript with optional chaining in my private project (I can't share it). And it worked fine until I've updated the 
 pdfjs-dist package to latest version which contains optional chaining in js.

## 🔬 Minimal Reproduction
There is nothing to share. For faster testing just install [**pdfjs-dist**](https://www.npmjs.com/package/pdfjs-dist) package and try to compile project - it compiles with error

## 🔥 Exception or Error
<pre><code>
Error: ./node_modules/pdfjs-dist/build/pdf.js 2413:45
Module parse failed: Unexpected token (2413:45)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|         intent: renderingIntent,
|         renderInteractiveForms: renderInteractiveForms === true,
>         annotationStorage: annotationStorage?.getAll() || null
|       });
|     }
</code></pre>

## 🌍  Your Environment
**Angular Version:**
<pre><code>

Angular CLI: 11.0.7
Node: 14.5.0
OS: win32 x64

Angular: 11.0.9
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, platform-server, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.7
@angular-devkit/build-angular   0.1100.7
@angular-devkit/core            11.0.7
@angular-devkit/schematics      11.0.7
@angular/cdk                    11.0.4
@angular/cli                    11.0.7
@schematics/angular             11.0.7
@schematics/update              0.1100.7
ng-packagr                      11.2.4
rxjs                            6.6.3
typescript                      4.0.5
webpack                         4.43.0

</code></pre>

**Anything else relevant?**

Any external module with optional chaining in js-file ([**pdfjs-dist**](https://www.npmjs.com/package/pdfjs-dist) for instance)

**Comment by alan-agius4** [comment] 2021-04-16 14:33
Duplicate of https://github.com/angular/angular-cli/issues/20471

**Closed by alan-agius4** 2021-04-16 14:33 UTC
