### ISSUE TITLE
ngOnDestroy called after DOM node is removed

### ISSUE THREAD

**Issue by ccnokes** [angular/angular#14252] opened 2017-02-02 17:59 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Angular 2.4.0 and 2.0.1 remove a component's DOM nodes before the `ngOnDestroy` method is called. The docs state that `ngOnDestroy` is "called just *before* Angular destroys the directive/component." I take this to mean that the DOM nodes are removed *after* `ngOnDestroy` is called. Correct me if I'm wrong though, in which case this isn't a bug but maybe just needs a documentation clarification.

**Expected behavior**
`ngOnDestroy` is called *before* a component's DOM is removed.

**Minimal reproduction of the problem with instructions**

https://plnkr.co/edit/7l5kUZXWJk9m7ZOHHPXS?p=preview
To reproduce:
1. Open the console
2. Click "Toggle node" 
3. Observe that the logs show that DOM nodes are removed before `ngOnDestroy` is called. 

Note: this behavior can also be confirmed by adding a DOM breakpoint on node removal and a breakpoint on the `TestComponent`'s `ngOnDestroy` method. The DOM breakpoint breaks first, followed by `ngOnDestroy`.

**What is the motivation / use case for changing the behavior?**
I'm in an Electron context working with `<webview>`s. If a webview gets destroyed before I have an opportunity to clean up some registered event handlers, they unavoidably leak. 

**Please tell us about your environment:**
macOS, latest Chrome.

* **Angular version:** 2.0.X
Confirmed on 2.4.0 and 2.0.1

**Comment by aaronfrost** [comment] 2017-02-03 18:30
I think that this makes sense @ccnokes. It is behaving like an `ngOnDestroyed`, but is called `ngOnDestroy`. The nuance in the naming there is confusing. `ngOnDestroy` sounds like it will fire BEFORE the component is torn down. But, it is firing AFTER is it being torn down. I think that this makes good sense.

**Comment by sirhcybe** [comment] 2017-02-20 20:01
I found this confusing as well. I am integrating a library that has it's own destroy method that I tried to call inside ngOnDestroy but it failed since the DOM element had already been removed. I understand that removing the element with a different library might be problematic for Angular's code but it seems like there could be a use case for both having both ngOnDestroyed and ngOnDestroy in the lifecycle. At the very least, I agree that the docs should be clarified.

**Comment by b091** [comment] 2017-03-23 13:01
Angular creates it, renders it, creates and renders its children, checks it when its data-bound properties change, **and destroys it before removing it from the DOM.** [doc](https://angular.io/docs/ts/latest/guide/lifecycle-hooks.html#!#ondestroy)

**Comment by DzmitryShylovich** [comment] 2017-03-23 13:28
yeah, it works as designed. this issues actually is a feature request to add a new hook.

**Comment by ccnokes** [comment] 2017-03-23 16:07
@DzmitryShylovich @b091 Maybe we're misunderstanding each other....? I'm saying that the docs don't clearly state when the DOM is removed (even where you linked), but based on the wording of the docs and the method name--to me--it sounded as if `ngOnDestroy` is called before a component's DOM is removed. This is not the case, as demonstrated by my test case. I'm proposing that either the documentation needs clarification or it's a bug. I hope that makes sense.

**Comment by tbosch** [comment] 2017-04-10 18:00
Agree, this is confusing...

**Comment by vaclavbohac** [comment] 2017-04-19 07:17
Imagine you are embedding a react component into the angular component. In order to clean up properly, one must be able to call `React.unmountComponentAtNode` before the DOM was removed, otherwise there'll be memory leaks. In that case just changing the name to `ngOnDestroyed` won't cut it.

**Comment by b091** [comment] 2017-04-19 07:23
Imagine you have a some third party component initialized e.g web player and you don't want to remove it from DOM just to append it to some view and then hide it in body. Without hook before DOM destroy it's impossible.

**Comment by koen-serneels** [comment] 2017-07-14 14:31
Hi. We are in need of something similar. We have a component that renders an iframe. To communicate with the iframe we use postMessage. This is working perfectly as long as the component is visible. However, one requirement is to postMessage when we leave the component. But doing this from the onDestroy is not working (no error, but the iframe never receives the messsage). The issue seems indeed that angular already destroyed the iframe (or at least did some cleanup on it) before the onDestroy method is executed.

So a way to get informed that a destroy is going to take place (but before doing any cleanup whatsoever) would be very helpful here. The workaround I implemented (credits @bobrosoft) is to use animations which will sort of simulate this behaviour (the annomation callback on * to void is started before any cleanup took place). Needless to say that this should not be the way to go ...

**Comment by dustincleveland** [comment] 2017-11-14 18:47
The issue here seems so obvious that I feel like I must be misunderstanding something. The purpose of `ngOnDestroy` is to clean up things like event listeners. From the docs:

> Cleanup just before Angular destroys the directive/component. Unsubscribe Observables and detach event handlers to avoid memory leaks.
Called just before Angular destroys the directive/component.

If the DOM element is removed by the time that `ngOnDestroy` is called, how can we possibly do something like `document.getElementById('element').removeEventListener('click')`? What value is this lifecycle hook if it doesn't give us the opportunity to clean things up? Given that Angular features like `HostListener` will clean up event handlers for us and that Angular's philosophy is to not manipulate the DOM directly, the real issue is with third party integrations.

The current behavior of `ngOnDestroy` would seem to cause pretty severe issues when trying to integrate third party libraries into Angular applications which need to detach themselves from the DOM when a component is destroyed. As far as I can tell, there's no way for us to call `ThirdPartyExtension.dispose('elementId')` from `ngOnDestroy` due to the missing DOM element, and thus no way to prevent a third party library from causing memory leaks.

Am I misunderstanding something? How are we intended to approach this issue?

**Comment by jigar140291** [comment] 2018-01-04 16:22
Any update on this issue?

**Comment by santialbo** [comment] 2018-03-15 12:22
How come no one from the Angular team is saying anything about such an impactful issue? A simple update would be much appreciated. This has been opened for a year 😨 😱

**Comment by Tularis** [comment] 2018-03-15 20:27
This is still the case in Angular 5.2.9... unbelievable that this has endured since angular 2.0 :o

**Comment by Braste** [comment] 2018-03-16 09:52
This is just inacceptable. Before introducing new, fancy stuff, maybe the angular team should first fix the old bugs! This makes working with angular a nightmare, when you (have to) use third party components.

**Comment by pkozlowski-opensource** [comment] 2019-03-13 10:50
This is a duplicate of #17404 - we essentially need to do several things:
* consider introducing a new lifecycle hook that runs _before_ a component is detached from the DOM (working name: `ngBeforeDestroy`);
* consider renaming destroy-related hooks to clearly indicate what runs when.

Closing as a duplicate of #17404

**Closed by pkozlowski-opensource** 2019-03-13 10:50 UTC
Labels: comp: core & compiler, freq2: medium, severity3: broken, type: bug/fix
