### ISSUE TITLE
[ERROR] The package "crypto" wasn't found on the file system but is built into node. [plugin angular-browser-node-built-in]

### ISSUE THREAD

**Issue by spock123** [angular/angular#59174] opened 2024-12-12 20:24 UTC
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

After we have upgrade several different projects to NG19, we are getting this error, but ONLY in development mode!
The error does NOT show up when making a production build.
Our projects do not directly use crypto but some of the 3rd party modules probably do (and used to work without issues).

`[ERROR] The package "crypto" wasn't found on the file system but is built into node. [plugin angular-browser-node-built-in]`

### Please provide the exception or error you saw

```true
Watch mode enabled. Watching for file changes...
NOTE: Raw file sizes do not reflect development server per-request transformations.
  ➜  Local:   http://localhost:4000/en
  ➜  Network: http://192.168.86.34:4000/en
  ➜  press h + enter to show help
✘ [ERROR] The package "crypto" wasn't found on the file system but is built into node. [plugin angular-browser-node-built-in]

    node_modules/seedrandom/seedrandom.js:265:27:
      265 │       nodecrypto = require('crypto');
          ╵                            ~~~~~~~~

/Users/spock/projects/fresto/apps/nexus/node_modules/vite/node_modules/esbuild/lib/main.js:1472
  let error = new Error(text);
              ^

Error: Build failed with 1 error:
node_modules/seedrandom/seedrandom.js:265:27: ERROR: [plugin: angular-browser-node-built-in] The package "crypto" wasn't found on the file system but is built into node.
    at failureErrorWithLog (/Users/spock/projects/fresto/apps/nexus/node_modules/vite/node_modules/esbuild/lib/main.js:1472:15)
    at /Users/spock/projects/fresto/apps/nexus/node_modules/vite/node_modules/esbuild/lib/main.js:945:25
    at /Users/spock/projects/fresto/apps/nexus/node_modules/vite/node_modules/esbuild/lib/main.js:1353:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errors: [Getter/Setter],
  warnings: [Getter/Setter]
}

Node.js v20.18.0
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 19.0.4
Node: 20.18.0
Package Manager: npm 10.8.2
OS: darwin arm64

Angular: 19.0.4
... animations, build, cli, common, compiler, compiler-cli, core
... forms, localize, platform-browser, platform-browser-dynamic
... router, service-worker, ssr

Package                              Version
--------------------------------------------------------------
@angular-devkit/architect            0.1900.4
@angular-devkit/core                 19.0.1
@angular-devkit/schematics           19.0.4
@angular/cdk                         19.0.3
@angular/google-maps                 19.0.3
@angular/material                    19.0.3
@angular/material-date-fns-adapter   19.0.3
@schematics/angular                  19.0.4
rxjs                                 7.8.1
typescript                           5.6.3
zone.js                              0.15.0
```

### Anything else?

Angular.json:

```
{
    "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
    "version": 1,
    "cli": {
        "packageManager": "npm",
        "analytics": "ac59db6d-a680-408f-af50-2623fb62aeae",
        "cache": {
            "enabled": true
        }
    },
    "newProjectRoot": "projects",
    "projects": {
        "nexus": {
            "projectType": "application",
            "schematics": {
                "@schematics/angular:component": {
                    "style": "scss",
                    "skipTests": true,
                    "standalone": true,
                    "changeDetection": "OnPush"
                },
                "@schematics/angular:class": {
                    "skipTests": true
                },
                "@schematics/angular:directive": {
                    "skipTests": true,
                    "standalone": true
                },
                "@schematics/angular:guard": {
                    "skipTests": true
                },
                "@schematics/angular:interceptor": {
                    "skipTests": true
                },
                "@schematics/angular:pipe": {
                    "skipTests": true,
                    "standalone": true
                },
                "@schematics/angular:resolver": {
                    "skipTests": true
                },
                "@schematics/angular:service": {
                    "skipTests": true
                }
            },
            "root": "",
            "sourceRoot": "src",
            "prefix": "app",
            "i18n": {
                "sourceLocale": "en-US",
                "locales": {
                    "da": {
                        "translation": "src/locale/messages.da.json"
                    },
                    "en": {
                        "translation": "src/locale/messages.en.json"
                    }
                }
            },
            "architect": {
                "build": {
                    "builder": "@angular/build:application",
                    "options": {
                        "allowedCommonJsDependencies": [
                            "mathjs",
                            "ngrx-store-localstorage",
                            "qrcode",
                            "file-saver"
                        ],

                        "outputPath": {
                            "base": "dist/nexus/"
                        },
                        "index": "src/index.html",
                        "polyfills": ["@angular/localize/init"],
                        "tsConfig": "tsconfig.app.json",
                        "inlineStyleLanguage": "scss",
                        "styles": ["src/styles/index.scss"],
                        "assets": ["src/assets", "src/robots.txt", "src/manifest.json"],
                        "scripts": [],
                        "serviceWorker": "ngsw-config.json",
                        "localize": true,
                        "i18nDuplicateTranslation": "ignore",

                        "preserveSymlinks": false,
                        "browser": "src/main.ts"
                    },
                    "configurations": {
                        "production": {
                            "fileReplacements": [
                                {
                                    "replace": "src/environments/environment.ts",
                                    "with": "src/environments/environment.prod.ts"
                                },
                                {
                                    "replace": "src/app/shared/store/build-specifics/index.ts",
                                    "with": "src/app/shared/store/build-specifics/index.prod.ts"
                                }
                            ],
                            "outputHashing": "all",
                            "namedChunks": false
                        },
                        "localprod": {
                            "optimization": false,
                            "sourceMap": true,
                            "fileReplacements": [
                                {
                                    "replace": "src/environments/environment.ts",
                                    "with": "src/environments/environment.localprod.ts"
                                }
                            ]
                        },

                        "test": {
                            "fileReplacements": [
                                {
                                    "replace": "src/environments/environment.ts",
                                    "with": "src/environments/environment.test.ts"
                                },
                                {
                                    "replace": "src/app/features/core/site-protection/index.ts",
                                    "with": "src/app/features/core/site-protection/index.protected.ts"
                                }
                            ],
                            "outputHashing": "all",
                            "namedChunks": false
                        },
                        "localtest": {
                            "fileReplacements": [
                                {
                                    "replace": "src/environments/environment.ts",
                                    "with": "src/environments/environment.localtest.ts"
                                }
                            ],
                            "localize": ["en"],
                            "outputHashing": "all"
                        },
                        "development": {
                            "fileReplacements": [
                                {
                                    "replace": "src/environments/environment.ts",
                                    "with": "src/environments/environment.dev.ts"
                                },
                                {
                                    "replace": "src/app/shared/store/build-specifics/index.ts",
                                    "with": "src/app/shared/store/build-specifics/index.prod.ts"
                                },
                                {
                                    "replace": "src/app/features/core/site-protection/index.ts",
                                    "with": "src/app/features/core/site-protection/index.protected.ts"
                                }
                            ],
                            "outputHashing": "all",
                            "sourceMap": true,
                            "namedChunks": false
                        },
                        "local": {
                            "optimization": false,
                            "sourceMap": true,
                            "fileReplacements": []
                        },
                        "da": {
                            "localize": ["da"],
                            "baseHref": "/da/"
                        },
                        "en": {
                            "localize": ["en"],
                            "baseHref": "/en/"
                        }
                    },
                    "defaultConfiguration": "production"
                },
                "serve": {
                    "builder": "@angular/build:dev-server",
                    "configurations": {
                        "production": {
                            "buildTarget": "nexus:build:production"
                        },
                        "localprod": {
                            "buildTarget": "nexus:build:localprod"
                        },
                        "localtest": {
                            "buildTarget": "nexus:build:localtest"
                        },
                        "test": {
                            "buildTarget": "nexus:build:test"
                        },
                        "development": {
                            "buildTarget": "nexus:build:development"
                        },
                        "local": {
                            "buildTarget": "nexus:build:local,en"
                        },

                        "da": {
                            "buildTarget": "nexus:build:local,da"
                        },
                        "en": {
                            "buildTarget": "nexus:build:local,en"
                        }
                    },
                    "defaultConfiguration": "local"
                },
                "extract-i18n": {
                    "builder": "@angular/build:extract-i18n",
                    "options": {
                        "buildTarget": "nexus:build"
                    }
                },

                "deploy": {
                    "builder": "@angular/fire:deploy",
                    "options": {
                        "prerender": false,
                        "ssr": false,
                        "browserTarget": "nexus:build:production",
                        "firebaseProject": "fastorder-dev",
                        "firebaseHostingSite": "fresto-totti-dev"
                    }
                }
            }
        }
    }
}

```

**Comment by spock123** [comment] 2024-12-12 20:25
Dependencies:
```

"dependencies": {
    "@angular/animations": "19.0.4",
    "@angular/cdk": "19.0.3",
    "@angular/common": "19.0.4",
    "@angular/compiler": "19.0.4",
    "@angular/core": "19.0.4",
    "@angular/forms": "19.0.4",
    "@angular/google-maps": "^19.0.3",
    "@angular/material": "19.0.3",
    "@angular/material-date-fns-adapter": "^19.0.3",
    "@angular/platform-browser": "19.0.4",
    "@angular/platform-browser-dynamic": "19.0.4",
    "@angular/router": "19.0.4",
    "@angular/service-worker": "19.0.4",
    "@angular/ssr": "^19.0.4",
    "@firebase/auth": "^0.23.2",
    "@googlemaps/js-api-loader": "^1.16.6",
    "@ngneat/hot-toast": "^7.0.0",
    "@ngneat/overview": "^6.0.0",
    "@ngrx/component-store": "^18.1.1",
    "@ngrx/effects": "18.1.1",
    "@ngrx/operators": "^18.1.1",
    "@ngrx/router-store": "18.1.1",
    "@ngrx/signals": "^18.1.1",
    "@ngrx/store": "18.1.1",
    "@ngrx/store-devtools": "18.1.1",
    "@simplewebauthn/browser": "^13.0.0",
    "@tailwindcss/forms": "^0.5.7",
    "@tailwindcss/typography": "^0.5.13",
    "@techiediaries/ngx-qrcode": "^9.1.0",
    "angularx-qrcode": "^17.0.0",
    "chart.js": "^4.4.1",
    "chartjs-plugin-annotation": "^3.0.1",
    "chartjs-plugin-datalabels": "^2.2.0",
    "date-fns": "^3.3.1",
    "file-saver": "^2.0.5",
    "firebase": "^10.13.1",
    "json-to-csv-export": "^3.0.1",
    "mathjs": "^12.4.1",
    "ng2-charts": "^5.0.4",
    "ngrx-store-localstorage": "^17.0.0",
    "ngx-cookie-service": "^17.0.1",
    "ngx-editor": "^18.0.0",
    "ngx-otp-input": "^0.11.4",
    "rxjs": "~7.8.1",
    "tailwindcss-animated": "^1.1.0",
    "tslib": "^2.3.0",
    "xng-breadcrumb": "10.0.2",
    "zone.js": "~0.15.0"
  },
  "devDependencies": {
    "@angular/build": "^19.0.4",
    "@angular/cli": "~19.0.4",
    "@angular/compiler-cli": "19.0.4",
    "@angular/localize": "^19.0.4",
    "@tailwindcss/container-queries": "^0.1.1",
    "@types/file-saver": "^2.0.7",
    "@types/google.maps": "^3.54.8",
    "@types/googlemaps": "^3.43.3",
    "@types/jasmine": "~4.3.0",
    "autoprefixer": "^10.4.19",
    "npm-run-all": "^4.1.5",
    "postcss": "^8.4.38",
    "prettier": "^3.3.3",
    "shx": "^0.3.4",
    "tailwindcss": "^3.4.4",
    "ts-node": "^10.9.2",
    "typescript": "~5.6.3"
  }
```

**Comment by spock123** [comment] 2024-12-12 20:28
tsconfig.json:
```

{
    "compileOnSave": false,
    "compilerOptions": {
        "baseUrl": "./",
        "outDir": "./dist/out-tsc",
        "forceConsistentCasingInFileNames": true,
        "esModuleInterop": true,
        "strict": true,
        "skipLibCheck": true,
        "noImplicitOverride": true,
        "noPropertyAccessFromIndexSignature": true,
        "noImplicitReturns": true,
        "noFallthroughCasesInSwitch": true,
        "sourceMap": true,
        "declaration": false,
        "experimentalDecorators": true,
        "moduleResolution": "node",
        "importHelpers": true,
        "target": "ES2022",
        "module": "ES2022",
        "useDefineForClassFields": false,
        "lib": ["ES2022", "dom"],
        "isolatedModules": true,
        "paths": {
            "@environment": ["src/environments/environment"],
            "@shared/*": ["src/app/shared/*"],
            "@features/*": ["src/app/features/*"],
            "@types": ["src/app/types"],
            "@store": ["src/app/shared/store"],
            "@stores": ["src/app/shared/stores", "src/app/shared/stores/*"]
        }
    },
    "angularCompilerOptions": {
        "enableI18nLegacyMessageIdFormat": false,
        "strictInjectionParameters": true,
        "strictInputAccessModifiers": true,
        "strictTemplates": true,
        "extendedDiagnostics": {
            "checks": {
                "unusedStandaloneImports": "suppress"
            }
        }
    }
}

```

**Comment by alan-agius4** [comment] 2024-12-12 20:35
Duplicate of https://github.com/angular/angular-cli/issues/29077. Luckily, it has already been fixed in one of the recent releases. Please update to the most recent version to resolve the problem.

**Closed by alan-agius4** 2024-12-12 20:35 UTC
