### ISSUE TITLE
Styles from 3rd party JS not applied on component inside <router-outlet> in Safari and Edge

### ISSUE THREAD

**Issue by St1c** [angular/angular#14843] opened 2017-03-01 20:34 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Hi, 
I'm trying to implement google blockly library into angular 2.4.8 app bundled with webpack 2.2.
Everything seems to working just fine in chrome, but in Safari styles which are defined in the blockly library are not being applied to workspace, if the component is loaded in router-outlet. I already tried all different encapsulation modes.

If I move the blockly component outside of the router outlet, everything works just fine. 

See the enclosed screenshots...The black background and sprites error are from Safari (rel. 24, but the same applies for current stable version).
![screen shot 2017-03-01 at 21 09 33](https://cloud.githubusercontent.com/assets/3169082/23479293/56b286a6-fec4-11e6-8c8c-4268109d6690.png)
This is how it should look like (from Chrome)
![screen shot 2017-03-01 at 21 09 27](https://cloud.githubusercontent.com/assets/3169082/23479294/56f95978-fec4-11e6-8652-985a6cceda7b.png)

**Expected behavior**
Styles should be applied also to routed components.

**Minimal reproduction of the problem with instructions**
You can see the demo at 
http://blockly2.dataworkers.eu

You can see the code here:
https://github.com/St1c/blockly-safari-bug

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
MacOS Sierra, Safari rel.24, macbook pro late 2016

* **Angular version:** 2.4.8

* **Browser:** Safari all versions

* **Language:** TypeScript 2.2.1

* **Node (for AoT issues):** `node --version` =   v7.5.0

**Comment by St1c** [comment] 2017-04-01 07:05
still persistent in 4.0.0

**Comment by St1c** [comment] 2017-08-08 16:42
Hi, 

since it seems there is no real update to this issue, is there some possible quick fix for styles which one can look for?

Thanks

**Comment by Bohdan-Tereta** [comment] 2017-12-15 20:40
This happens because you have <base href="/"> tag from your AppComponent.html.

That tag influences how svg processes some style urls (which is normal behavior), but urls generated by GoogleBlockly do not need that tag, it is needed only for angular to work, and so some svg style urls become invalid.
 
In Angular 2+, you can inject the base path in your app module instead of using the <base> tag. 

import { APP_BASE_HREF } from '@angular/common';

@NgModule({
   providers: [{
     provide: APP_BASE_HREF,
     useValue: '/'
   }]
})
export class AppModule { }

Don't forget to remove <base href="/"> tag from your AppComponent.html. 

https://angular.io/docs/ts/latest/api/common/index/APP_BASE_HREF-let.html

This solves the problem. And considering the above, this is neither blocky nor angular bug.

**Comment by St1c** [comment] 2017-12-15 22:20
Great, thanks a lot, this really solves this issue! 
However putting base href to app.module is creating a problem with deep-linking urls. Any workaround related to this?

**Comment by Bohdan-Tereta** [comment] 2017-12-16 09:48
I can't understand, what the problem with deep-linking urls is, without a detailed description or link to code example. 

But, there's one more alternative, though somewhat hacky indeed, that doesn't involve removing base href from html, and it is described here: 
https://gist.github.com/leonderijke/c5cf7c5b2e424c0061d2

That approach is just finding all svg elements with # urls and update their hrefs to absolute when dom changes. 

Not the fastest approach, but may be helpful, if no other solutions apply for your case.

**Comment by St1c** [comment] 2017-12-16 20:51
Ok, I found this in the Angular [docs](https://angular.io/guide/router#browser-url-styles):

> Without that tag (base href...), the browser may not be able to load resources (images, CSS, scripts) when "deep linking" into the app. Bad things could happen when someone pastes an application link into the browser's address bar or clicks such a link in an email.

Hence, without base tag in index.html there is only possibility to use HashLocationStrategy - urls starting with # .

So the final solution is to use this snippet in app-routing.module.ts:

```
providers: [

        { provide: LocationStrategy, useClass: HashLocationStrategy },

        { provide: APP_BASE_HREF, useValue: '/' }

    ]
```

However note that angular docs also notes:
>Almost all Angular projects should use the default HTML5 style. It produces URLs that are easier for users to understand. And it preserves the option to do server-side rendering later.

So, it seems there are always some trade-offs in this case.

**Comment by Bohdan-Tereta** [comment] 2018-06-22 15:10
Proper solution would be (finally):

    Add this function to Blockly sources
    /**

    Convert local uri to global uri, required for svg to work correctly when page contains tag
    Fixes Safari svg rendering issues (black background, misplaced zoom/trash controls etc)
    @param {string} localUri local uri string
    local uri example: "url(#blocklyTrashBodyClipPath837493)"
    @return {!string} global uri
    */
    Blockly.convertToGlobalUri = function (localUri) {
    var baseUrl = window.location.href.replace(window.location.hash, "");
    var idx = localUri.indexOf("url(");
    return localUri.slice(0, idx + 4) + baseUrl + localUri.slice(idx + 4);
    };

    In all places where you see 'url(#' inside blockly sources, use Blockly.convertToGlobalUri() to convert local uri to global one

Source of the issue: blockly generates local uris even when tag is present which is incorrect (svg should react to tag), most browsers are 'smart enough' to convert local uris to global in that case (that browser behaviour is not part of specs though), but that doesn't happen in Safari
So I assume that isn't a safari bug and should be fixed in blockly

Solution was implemented and tested by me and works in Safari. Noticed no side effects in Chrome/Firefox/Edge/IE too.
Steps to reproduce:

    Take any blockly example
    Add tag to page
    Open the page in Safari
    Expected: white backround, correctly placed zoom/trash controls
    Actual: black backround, zoom/trash controls are visually multiplied (see screenshot at the beginning of this thread)

Proposed to fix that on blockly side: https://github.com/google/blockly/issues/865

**Comment by NeilFraser** [comment] 2018-07-23 19:14
This code is pretty fragile.  At a minimum it should throw an error if idx is -1.

But another issue is that urls can be specified as:
```
url("http://mysite.example.com/mycursor.png")
url('http://mysite.example.com/mycursor.png')
url(http://mysite.example.com/mycursor.png)
```
This code only works on the last one.  That would be a pretty ugly error to debug if someone constructed a url() with quotes.

And this code is also intolerant of whitespaces.

A more robust approach would be to take a local URL (e.g. '#blocklyTrashBodyClipPath837493') and return either an absolute URL ('https://foo.bar/#blocklyTrashBodyClipPath837493') or a CSS pointer ('url(https://foo.bar/#blocklyTrashBodyClipPath837493)').  It should also check to see if `/^\w+:\/\//` exists in the URL, incase it is already absolute.

**Comment by Bohdan-Tereta** [comment] 2018-10-05 10:06
@NeilFraser , you are right, and seems people still have this issue now (just noticed a new comment at https://github.com/google/blockly/issues/865#issuecomment-427151868). So why don't we fix it in blockly sources considering your suggestions? Code is pretty simple and safe in that case:

```
/**
 * Convert local uri to global uri, required for svg to work correctly when page contains <base> tag
 * Fixes Safari svg rendering issues (black background, misplaced zoom/trash controls etc)
 * @param {string} localUri local uri string
 * local uri example: '#blocklyTrashBodyClipPath837493'
 * @return {string} global uri
 */
Blockly.convertToGlobalUri = function (localUri) {
  let globalUri = localUri;
  let baseUri = window.location.hash ? window.location.href.replace(window.location.hash, "") : window.location.href;
  if (localUri && !localUri.includes('://')) {
    globalUri = baseUri + localUri;
  }
  return globalUri;
};
```

**Comment by pkozlowski-opensource** [comment] 2019-03-06 19:29
Sounds like a support request that was since resolved.

**Closed by pkozlowski-opensource** 2019-03-06 19:29 UTC
Labels: comp: core & compiler, freq2: medium, severity3: broken, type: bug/fix
