### ISSUE TITLE
Request to break CHANGELOG.md into smaller files

### ISSUE THREAD

**Issue by josmar-crwdstffng** [angular/angular#45082] opened 2022-02-14 23:17 UTC
### Description

The CHANGELOG.md file is too large to preview on GitHub.
I suggest moving the pre-Ivy (View Engine only) release information into another CHANGELOG.md file.
Suggested name is CHANGELOG_PI.md for Pre-Ivy.

Replace the moved content with a simple table that links to the new file.

> **ASIDE**:<br />
> As a "nice to have" addition, I recommend moving the release information that is not Ivy only into another CHANGELOG.md file.
> Suggested name is CHANGELOG_PIO.md for Pre-Ivy only.

### What is the affected URL?

CHANGELOG.md

### Please provide the steps to reproduce the issue

Navigate to CHANGELOG.md at [https://github.com/angular/angular/blob/master/CHANGELOG.md](https://github.com/angular/angular/blob/master/CHANGELOG.md).

**Comment by alan-agius4** [comment] 2022-02-15 08:09
Duplicate of https://github.com/angular/angular/issues/44953

**Closed by alan-agius4** 2022-02-15 08:09 UTC
Labels: comp: docs
