### ISSUE TITLE
ng test failed since Angular CLI 15.1 with static class variables

### ISSUE THREAD

**Issue by bougnat12** [angular/angular#48778] opened 2023-01-19 16:21 UTC
### Command

test

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

15.0.5

### Description

If application contains `static` class variables then `ng test` failed.

<img width="875" alt="ng test with static variables" src="https://user-images.githubusercontent.com/16716588/213495319-9dab8986-47e3-4afb-aaa0-b70f84040500.png">

If `static` variable usage is commented out then `ng server` succeed:

<img width="876" alt="ng test without static variables" src="https://user-images.githubusercontent.com/16716588/213495532-907ce971-26f1-46aa-9241-cbb9918f8e3f.png">

Angular app is running well:

<img width="1148" alt="Angular app" src="https://user-images.githubusercontent.com/16716588/213495680-184e03f5-dff3-420b-8de2-05eac1b7e798.png">

And Chrome debugging console shown `static` variable is right:

<img width="580" alt="Angular app debug" src="https://user-images.githubusercontent.com/16716588/213495822-de40035f-8516-43cc-9ce4-f738e6bebe1b.png">

### Minimal Reproduction

Run `ng test`.

Minimal repo is here: https://github.com/bougnat12/static-issue

### Exception or Error

```text
✔ Browser application bundle generation complete.
19 01 2023 16:26:58.425:WARN [karma]: No captured browser, open http://localhost:9876/
19 01 2023 16:26:58.434:INFO [karma-server]: Karma v6.4.1 server started at http://localhost:9876/
19 01 2023 16:26:58.434:INFO [launcher]: Launching browsers Chrome with concurrency unlimited
19 01 2023 16:26:58.435:INFO [launcher]: Starting browser Chrome
19 01 2023 16:26:59.181:INFO [Chrome 109.0.0.0 (Mac OS 10.15.7)]: Connected on socket eNWoj7g08O2YXszJAAAB with id 14211099
Chrome 109.0.0.0 (Mac OS 10.15.7) ERROR
  An error was thrown in afterAll
  Uncaught TypeError: Cannot read properties of undefined (reading 'PredefinedZoomEnumMapList')
  TypeError: Cannot read properties of undefined (reading 'PredefinedZoomEnumMapList')
      at Object.5041 (http://localhost:9876/_karma_webpack_/webpack:/src/app/app.component.ts:22:53)
      at __webpack_require__ (http://localhost:9876/_karma_webpack_/webpack:/webpack/bootstrap:19:1)
      at Object.4882 (http://localhost:9876/_karma_webpack_/main.js:13:72)
      at __webpack_require__ (http://localhost:9876/_karma_webpack_/webpack:/webpack/bootstrap:19:1)
      at __webpack_exec__ (http://localhost:9876/_karma_webpack_/main.js:131:48)
      at http://localhost:9876/_karma_webpack_/main.js:132:102
      at Function.__webpack_require__.O (http://localhost:9876/_karma_webpack_/webpack:/webpack/runtime/chunk loaded:23:1)
      at http://localhost:9876/_karma_webpack_/main.js:133:56
      at webpackJsonpCallback (http://localhost:9876/_karma_webpack_/webpack:/webpack/runtime/jsonp chunk loading:34:1)
      at http://localhost:9876/_karma_webpack_/main.js:1:77
Chrome 109.0.0.0 (Mac OS 10.15.7): Executed 0 of 0 ERROR (0 secs / 0 secs)
```
```


### Your Environment

```text
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 15.1.2
Node: 18.13.0
Package Manager: npm 9.3.1
OS: darwin arm64

Angular: 15.1.1
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1501.2
@angular-devkit/build-angular   15.1.2
@angular-devkit/core            15.1.2
@angular-devkit/schematics      15.1.2
@angular/cli                    15.1.2
@schematics/angular             15.1.2
rxjs                            7.8.0
typescript                      4.9.4
```

**Comment by alan-agius4** [comment] 2023-01-19 16:24
Duplicate of https://github.com/angular/angular/issues/48764

**Closed by alan-agius4** 2023-01-19 16:24 UTC

**Comment by bougnat12** [comment] 2023-01-19 18:01
Sorry. I have search last week and don't redo this week. Thanks.
