### ISSUE TITLE
Support compile-time self-closing tags

### ISSUE THREAD

**Issue by HKhademian** [angular/angular#32257] opened 2019-08-22 05:18 UTC
# 🚀 feature request

### Relevant Package
This feature request is for @angular/core

### Description
After I read some posts including this [stackoverflow](https://stackoverflow.com/questions/18103183/angularjs-element-directives-not-displaying-when-using-self-closing-tags) about why I can't use **self-closing tags** or  **non-void elements**, and the guild of browsers 😐, I think why angular didn't make it a compile-time feature?

### My super special solution
I think we can have **non-void elements** (self-closing tags) as a compile-time feature in angular world, and angular convert them to normal (if it is) tags, (even on hot reloads, ...).

### Alternatives, of-course
Do the hard work and write codes like `<my-very-long-and-boring-component-name ...>< /my-very-long-and-boring-component-name>` 🙄🤦🏼‍♂️, or just kill the visibility, readability, (add many good things you can here 😁) ... and use short names like `<mvlabc ...>< /mvlabc>` 😁🤷🏼‍♂️

**Comment by santoshyadav198613** [comment] 2019-08-22 05:24
Check #673

**Comment by atscott** [comment] 2019-08-22 17:53
Thanks for reporting this issue. However this issue is a duplicate of an existing issue #673. Please subscribe to that issue for future updates.

**Closed by atscott** 2019-08-22 17:53 UTC
