### ISSUE TITLE
Angular application not calling API's intermittently and showing white screen in browser

### ISSUE THREAD

**Issue by sujadkar** [angular/angular#43185] opened 2021-08-17 05:49 UTC
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

We are having Angular application/website. We pushed new changes constantly to our prod environment. From last July last week we are getting reports from our Users that site is not loading properly i.e it is showing a white screen on Browser. Sometimes if we clear cache then it is working but sometimes clearing cache won't help.

We are using cache bursting while creating build for Production then also our users are reporting this issue We tried to repro this on our test environment. One the dev machine we are able to repro issue. It was like dev did not hit site from almost a month and yesterday dev hit site through Chrome and it was not loading.We are using chrome's
 latest version browser.

It is just loading js and css files and did not call any API to the server.

![MicrosoftTeams-image](https://user-images.githubusercontent.com/16307466/129669686-a98c3b02-8ac9-491a-9549-d8516d3bbb7e.png)

![teams](https://user-images.githubusercontent.com/16307466/129669712-7db7c180-0111-4a41-bc9e-8a34997d5bf9.JPG)

![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/16307466/129669736-2f8ace0b-8877-4643-9d64-9ebd5d3eaaa6.png)

Here 403 is because we are calling McAfee service which will load images. On another machine, it is showing 403 and loading site. We don't think this is causing any issue because for last 7 months we are using this as is.

Please help me out here.We are clueless here.We also logged support ticket on StackOverflow but did not got any suitable response. [https://stackoverflow.com/questions/68798584/angular-how-to-reproduced-blank-screen-white-screen-issue-in-agnular](url)

### Please provide the exception or error you saw

```true
Given in above description.
```

### Please provide the environment you discovered this bug in

```true
Angular CLI : 9.1.12
Node : 12.11.1
NPM : 6.14.13
OS : Windows 10 64 Bit

Dev Dependencies :

@angular-devkit/build-angular": "^0.901.12",
    "@angular/cli": "~9.1.12",
    "@angular/compiler-cli": "~9.1.12",
    "@nguniversal/builders": "^9.1.1",
    "@types/express": "^4.17.0",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^12.11.1",
    "codelyzer": "^5.1.2",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~5.0.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~2.1.0",
    "karma-jasmine": "~3.0.1",
    "karma-jasmine-html-reporter": "^1.4.2",
    "protractor": "~7.0.0",
    "sonar-scanner": "^3.1.0",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~3.8.3
```

**Comment by JoostK** [comment] 2021-08-17 06:58
I'm afraid that the Angular issue tracker is not the right place to ask for questions like these, as it's impossible for us to help diagnose an application issue when it's not clear that it's caused by Angular _and_ when there is no reproduction available.

Furthermore, Angular 9 is no longer supported. I don't expect the version of Angular to be of particular interest here, but it's unclear at the moment. I would suggest you try to find the change that introduces this behavior, as you mention it has only been occurring for a couple weeks now.

Closing as this is not actionable for us, but feel free to open a new issue if you have established that this is caused by Angular.

**Closed by JoostK** 2021-08-17 06:58 UTC

**Comment by sujadkar** [comment] 2021-08-17 07:36
@JoostK Thanks for the feedback.
