### ISSUE TITLE
Failed to load HTTP resource in live URL

### ISSUE THREAD

**Issue by akilmakda** [angular/angular#23012] opened 2018-03-27 06:32 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Angular service worker application throws following error
<pre><code>
Failed to HTTP in live url load resource : the server responded with a status of 504 (Gateway Timeout)
</code></pre>

## Expected behavior

It should not throw any exceptions

## Minimal reproduction of the problem with instructions

Demo application on git below is the link 
URL : https://github.com/akilmakda/PWA-not-work-in-HTTP

download application -> install npm -> build( ng build --prod) -> upload to any live server.

**NOTE: in localhost, it works fine** 

![screenshot from 2018-03-27 11-46-04](https://user-images.githubusercontent.com/24309502/37950638-f6a1cfca-31b6-11e8-8b23-3de8f1a1cd02.png)

## Environment

<pre><code>
Angular version: 5.2.5

Browser:
- [ ] Chrome (desktop) version 65.0.3325.181
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.9.3  
- Platform: Linux

**Comment by akilmakda** [comment] 2018-03-27 07:31
@jainanuj0812 follow my uploaded application. In that application, I just set demo images three is in HTTPS and same three in HTTP when you set a refresh page https images are load but not HTTP images. You can check in console and Network tab of developer option.

**Comment by akoserwal** [comment] 2018-03-27 07:38
@akilmakda: please have a look at 

- https://developers.google.com/web/ilt/pwa/introduction-to-progressive-web-app-architectures#prerequisites
- https://developers.google.com/web/fundamentals/security/prevent-mixed-content/what-is-mixed-content

**Comment by jainanuj0812** [comment] 2018-03-27 07:42
@akilmakda, You can't make a request to HTTP from the HTTPS based origin. 

https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy

**Comment by gkalpak** [comment] 2018-03-27 07:50
This seems to be caused by the fact that, while "passive mixed content" (like images) only produces a warning without a ServiceWorker, fetching it via a ServiceWorker results in an error. This applies to ServiceWorkers in general and is not specific to Angular's implementation.
The link provided by @akoserwal above has more details on mixed content.

As fas as I understand, the fact that fetching from within the ServiceWorker behaves differently than fetching without a ServiceWorker is a limitation of ServiceWorkers (see relevant discussions [here][1], [here][2], and [here][3]).

One option for `@angular/service-worker` would be to choose not to handle this type of requests, but given that mixed content is insecure for users anyway, I would not be too keen on supporting it in `@angular/service-worker` 😈

While fixing #20404 we can make sure that it is possible to specify URL patterns that won't be handled by the ServiceWorker, which would provide a work-around for your usecase (i.e. you could config the SW t ignore `http:` URLs and let the browser handle them).

WDYT, @alxhub? 

[1]: https://bugs.chromium.org/p/chromium/issues/detail?id=448672
[2]: https://bugs.chromium.org/p/chromium/issues/detail?id=554226
[3]: https://github.com/w3c/ServiceWorker/issues/813

**Comment by gkalpak** [comment] 2018-03-27 20:55
[It turns out][1] that the fix for #20404 can provide a work-around for this issue.

[1]: https://github.com/angular/angular/pull/23025#issuecomment-376662562

**Comment by gkalpak** [comment] 2018-03-28 15:51
So, the only fix/work-around I can think of is ignoring `http:` requests if the SW's scope is on `https:`. This can be checked synchronously and will avoid handling mixed content in the SW, which is currently not possible anyway.

**Comment by akilmakda** [comment] 2018-04-02 04:32
@gkalpak  **'ignoredUrlPatterns'**  not work for HTTP response. can you give any e.g how to ignore HTTP response.

or any other way to ignore  HTTP API response.

**Comment by gkalpak** [comment] 2018-04-02 07:35
@akilmakda, I fixed [my previous comment][1]. I meant that #20404 can**not** fix your usecase.
As mentioned in https://github.com/angular/angular/issues/23012#issuecomment-376937241, one fix/work-around I can think of would be to not handle mixed content from the service worker (but that is a change that needs to be made to the SW; it is not something you can do yourself).

[1]: https://github.com/angular/angular/issues/23012#issuecomment-376672174

**Comment by gkalpak** [comment] 2018-04-04 17:43
For future reference:
Discussed this with @alxhub and decided to implement https://github.com/angular/angular/issues/23012#issuecomment-376937241 (not handle mixed content from the SW).
I'll submit a PR in the next days, unless someone beats me to it :wink:

**Comment by akilmakda** [comment] 2018-09-25 13:13
@gkalpak when this feature roll-out?

**Comment by gkalpak** [comment] 2018-09-25 13:39
It has to be reviewed and merged first :grin:
(cc @alxhub)

**Comment by akilmakda** [comment] 2018-10-03 05:42
@gkalpak  can you give me a timeline when you release this? So I will provide to my boss.

**Comment by gkalpak** [comment] 2018-10-05 07:48
No estimate, sorry. There other higher priority stuff to sort out first (for the upcoming 7.0 release).

**Comment by akilmakda** [comment] 2019-01-29 15:13
@gkalpak any update?

**Comment by eliraneliassy** [comment] 2019-02-27 14:38
@gkalpak +1 here

**Comment by shabbir-dhangot** [comment] 2019-03-01 09:56
@gkalpak It seems like this issue is faced by many of user but got stuck in approval process. I am also waiting for this fix for almost 6+ months. 
Kindly provide some tentative dates.

**Comment by gkalpak** [comment] 2019-03-04 11:29
@shabbir-dhangot, hopefully this week :tada: (based on https://github.com/angular/angular/pull/25994#issuecomment-468907057)

**Closed** 2019-03-04 19:52 UTC
Labels: comp: service-worker, effort1: hours, freq1: low, type: bug/fix

**Comment by shabbir-dhangot** [comment] 2019-09-05 09:18
@gkalpak can you share document link how we can start using this?

**Comment by gkalpak** [comment] 2019-09-05 09:38
Not sure what you mean @shabbir-dhangot. You don't have to do anything. This was a change in `@angular/service-worker` internals (it now ignores mixed content requests), you don't have to change anything in your app.
