### ISSUE TITLE
QueryList.changes is triggered for any view changes (even siblings)

### ISSUE THREAD

**Issue by Andy1605** [angular/angular#30088] opened 2019-04-24 14:42 UTC
# 🐞 bug report

### Affected Package
@angular/core@7.2.14

### Is this a regression?
It worked as expected in Version 2.4.9 

### Description
A QueryList (bound via ViewChildren decorator) is always emitting the changes event even though no of its observed elements have changed. In fact it gets emitted for any view changes within the same view.

## 🔬 Minimal Reproduction
A minimal example is the following component:
<pre><code>
@Component({
	selector: 'querylist-sandbox',
	template: `
		&lt;button (click)="showAddButton = !showAddButton">TOGGLE INPUT&lt;/button>&nbsp;
		&lt;button (click)="itemList.push( itemList.length )" *ngIf="showAddButton">ADD&lt;/button>
		&lt;div #items *ngFor="let item of itemList">{{item}}&lt;/div>`
})
export class QueryListSandbox {
	@ViewChildren('items')
	private items: QueryList<ElementRef>;
	
	private showAddButton = true;

	private itemList = [ 0, 1, 2 ];

	public constructor() {
		
	}

	public ngAfterViewInit() {
		this.items.changes.subscribe( ql => {
			console.log( ql, 'CHANGES!' );
		});
	}
}
</code></pre>

On StackBlitz:
https://stackblitz.com/edit/angular-ru9m6u

## 🔥 Exception or Error
The console log is also made when the TOGGLE button is pressed. I only expect the event to be triggered when i press the ADD button, though.

**Comment by JoostK** [comment] 2019-04-24 18:30
Could you reproduce on StackBlitz please?

**Comment by Andy1605** [comment] 2019-04-25 06:43
I added the link to a StackBlitz project

**Comment by carlkroeger** [comment] 2019-05-09 07:41
I had to deal with this today in a project.

A basic workaround that worked for me was to store the initial length of every array displayed in my view.
I then check with the length after ngAfterViewInit to execute my code only if the list length has increased.

    ngAfterViewInit() {
      this.mylist.changes.subscribe(r => {
        if(this.mylist.length > this.oldListLength){      
          doOnlyIfListSizeIncreased();
        }
        this.oldListLength = this.mylist.length;
      })
      this.mylist2.changes.subscribe(r => {
        if(this.mylist2.length > this.oldListLength2){      
          doOnlyIfList2SizeIncreased();
        }
        this.oldListLength2 = this.mylist2.length;
      })
    }

Is this good enough for now?

**Comment by Andy1605** [comment] 2019-05-13 10:31
First of all would you miss if an item has been added and another has been removed and second am i using change subscriptions on QueryLists all over my project. I would have to monkeypatch the QueryList somehow since i am not going to adjust all the occurences of this in our project which is quite large and divided into several modules which could also be written by third parties.
I would like to know whether this is going to be fixed in the near future or if i have to patch it in my local library somehow.

**Comment by khiami** [comment] 2019-06-13 09:18
I ditched the QueryList.changes completely and used EventEmitter instead on the Directive level. The reason is the change subscription event always returns one element when the view actually contains more than that. 'length' property is not actually reflecting the right number which turns to be a total mess.

I am using the following approach as a replacement to the QueryList.changes:

Directive definition
```
import { .., EventEmitter, .. } from '@angular/core'

@Directive({
  selector: '[appSomeDirective]'
})
export class SomeDirective {

constructor(public viewContainerRef: ViewContainerRef) {}

  @Output('onViewInit') onViewInit: EventEmitter<any> = new EventEmitter()
  ngAfterViewInit() { this.onViewInit.emit(!0) }

}
```

Use in template
```
<div appSomeDirective (onViewInit)="onViewInit({ done: true })"></div>
```

Event handler in the component
```

onViewInit(data) {
// used timeout to wait for the viewContainerRef to show-up
// less than 3e1 seem to work either. 
 return setTimeout(()=> this.whatever = data, 3e1)
}
```

I hope that helps, until the QueryList change bug gets resolved.

**Comment by Airblader** [comment] 2019-06-13 09:22
@khami The change event contains the entire QueryList as the payload, not just the matched children.

**Comment by Andy1605** [comment] 2019-06-25 06:33
@khiami I really don't know in how far that fixes anything :D

I am going with a quick and dirty monkey patch which works like a charm for my purposes and will be simply removed again once this issue is resolved.

`
function areArraysEqual( arrA, arrB ) {
	 if( arrA === arrB )
		return true;

	if( !arrA || !arrB )
		return false;

	if( arrA.length !== arrB.length )
		return false;

	for( let i = 0; i < arrA.length; i++ ) {
		if( arrA[i] !== arrB[i] )
			return false;
	}

	return true;
}

// monkey patch the notifyOnChanges method of QueryList
const orgNotifyOnChanges = QueryList.prototype.notifyOnChanges;
QueryList.prototype.notifyOnChanges = function () {
	const ql = < QueryList<any> >this;
	const items = ql['_results'] as Array<any>;

	if( !ql['__lastItems'] || !areArraysEqual( items, ql['__lastItems'] ) ) {
		ql['__lastItems'] = items.slice();
						
		orgNotifyOnChanges.apply( ql, arguments );
	}
};`

There might be a better way. I did not have any serious performance issues with that so far since it will only be called once the view has changed at all, not when it is checked.

**Comment by khiami** [comment] 2019-07-03 16:39
I am not saying the workaround is a replacement of the subscription approach for all cases. What I just wanted to have is an event of whenever the QueryList is changed (children added/removed), and the payload is emitted with the event itself.

**Comment by radzk** [comment] 2019-09-19 07:41
this makes completely no sense, it is a bug, is this going to be fixed?

**Comment by cexbrayat** [comment] 2019-11-15 08:58
This is probably fixed by Ivy in v9. 

If someone encountering the issue can test with the latest release with Ivy enabled, we might confirm that this weird behavior does not exist anymore, and close the issue.

**Comment by Aleksandyr** [comment] 2019-11-29 08:18
@cexbrayat This issue is not reproducible anymore.

**Comment by cexbrayat** [comment] 2019-11-29 08:22
@Aleksandyr Awesome, thank you for checking!

**Closed by cexbrayat** 2019-11-29 08:22 UTC
Labels: comp: core, freq1: low, severity2: inconvenient, type: bug/fix
