### ISSUE TITLE
Angular SSR - DOM is flickering

### ISSUE THREAD

**Issue by conradkirschner** [angular/angular#38242] opened 2020-07-27 11:37 UTC
# 🐞 bug report

### Affected Package
@angular/universal 
@angular

### Is this a regression?

Seems to be a longer Angular Problem 

### Description

There is no clear way how to solve production server side rendering. 

## 🔬 Minimal Reproduction

This Problem appears in a lot of bugs, if you wish I could add them here. But the Tickets are not discussion the problem. 

## 🔥 Exception or Error

When using Angular with Server Side Rendering, it seems to load the page twice. On Server it produce the HTML but then on client it regenerate the HTML and replace it in DOM. 

If you have a huge dom with a lot SVGs, as images in your DOM, you will see the flickering. (Activate Chrome Rendering visuals) 

Is there a way to reuse the already server side rendered DOM? I saw PreBoot, but it will not reuse the DOM... so flickering will be minimized but not fixed. 

## 🌍  Your Environment

**Angular Version:**
9.*

**Anything else relevant?**

**Comment by pkozlowski-opensource** [comment] 2020-07-27 12:10
This is _literally_ duplicate of the most voted issue for server-side rendering #13446. We want to make the hydration experience better and this is on top of our list for server side rendering.

I'm going to close this issue as the duplicate of the mentioned one since we are well aware of the problem, there is a tracking issue for it and this issue here doesn't add additional info (if you believe that there is some missing info in #13446 please add it there).

**Closed by pkozlowski-opensource** 2020-07-27 12:10 UTC
Labels: core: DOM rendering
