### ISSUE TITLE
feat(ngSwitchCase): add "ngSwitchBreak" optional directive

### ISSUE THREAD

**Issue by merlosy** [angular/angular#19824] opened 2017-10-20 09:59 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

If the *value* tested matches multiple *case* option, all `*ngSwitchCase` are evaluated

## Expected behavior

If the case `*ngSwitchCase` has a directive `ngSwitchBreak`, other following cases shouldn't be evaluated.

## Minimal reproduction of the problem with instructions

Let's consider 2 arrays, *arr2* being filled with values and compared to size of *arr1*:
```html
<ng-container [ngSwitch]="arr2.length">
    <p *ngSwitchCase="arr1.length">Same size</p>
    <p *ngSwitchCase="0">Empty</p>
    <p *ngSwitchDefault>Not empty</p>
</ng-container>
```
When *arr1* and *arr2* are both empty, "Same size" and "0" are both displayed.

Plunker [HERE](http://plnkr.co/edit/fWx1eJ9kFtbjzY92Gs5t?p=preview)

## What is the motivation / use case for changing the behavior?

In my case, having the same size is more relevant, and I don't want the other cases to be evaluated.
A `ngSwitchBreak` directive can be introduced to accomplish this.

```
<ng-container [ngSwitch]="arr2.length">
    <p *ngSwitchCase="arr1.length" ngSwitchBreak>Same size</p>
    <p *ngSwitchCase="0">Empty</p>
    <p *ngSwitchDefault>Not empty</p>
</ng-container>
```

## Environment

<pre><code>
Angular version: 4.4.6

Browser:
All
 
For Tooling issues:
Any

Others:

</code></pre>

**Comment by trotyl** [comment] 2018-03-30 14:03
Made a lib implementation at https://github.com/trotyl/angular-contrib/tree/master/packages/common/switch-continue, demo at https://stackblitz.com/edit/angular-dnbved?file=app%2Fapp.component.html

**Comment by pcroc** [comment] 2018-12-13 12:07
I would class this as a bug, as evaluating multiple matching conditions is contrary to how switch works in most languages, making this multiple-matching behaviour very counter-intuitive.

```
const x = 3;
switch (3) {
case 3: alert('3'); break;
case x: alert('x'); break;
}
```

Here multiple case conditions are matched, but only one alert is shown (3). The *ngSwitch directive should behave similarly.

My use case:

```
<ng-container [ngSwitch]="true">
  <ng-container *ngSwitchCase="premiumPlus">Reports</ng-container>
  <ng-container *ngSwitchCase="premiumExtra">Reports in your sector(s)</ng-container>
  <ng-container *ngSwitchCase="premium">Pay-as-you-go reports</ng-container>
  <ng-container *ngSwitchDefault>Reports</ng-container>
</ng-container>
```

Here I want only the text of the first matching condition, not subsequent matching conditions.

**Comment by johnmcase** [comment] 2019-11-01 21:42
This issue is 2 years old.  Is there any chance that this will be pulled in and implemented?

**Comment by leopangchan** [comment] 2020-11-24 22:08
It will be very helpful. Hope it will be implemented soon.

**Comment by msmid** [comment] 2021-02-09 16:43
I agree with others, that if you call it `switch` but you don't implement break, then it is not switch is it? I would love to have this feature, please make it happen 🙏

**Comment by petebacondarwin** [comment] 2021-02-09 17:40
Well this is definitely not a bug. It even states in the documentation that 

> Every view that matches is rendered.

Perhaps it was unfortunate that the name was not something like match or select rather than switch, which does have the connotation of only one path being chosen.

But I agree it would be a useful feature. I think the cleanest solution would be to support an attribute at the `ngSwitch` level that is something like: `match="first"`, but that defaults to `match="all"`?

**Comment by msmid** [comment] 2021-02-09 18:26
I think what @trotyl did is pretty much enough and consistent in Angular world -> https://github.com/angular/angular/issues/19824#issuecomment-377530971

Give us local variable `continue` to control if we want to break the switch or not, that would be awesome.

**Comment by pkozlowski-opensource** [comment] 2023-12-07 16:50
The new built-in `@switch` statement behaves as requested in this issue.

**Comment by JeanMeche** [comment] 2024-02-19 00:49
Per Pawel, the new `@switch` block doesn't fall through on cases. It is now the recommanded syntax, I think we can close this.

**Closed by JeanMeche** 2024-02-19 00:49 UTC
Labels: feature, area: common, freq1: low, feature: under consideration, feature: votes required
