### ISSUE TITLE
async pipe within ngFor content does not always unsubscribe when ngFor is destroyed

### ISSUE THREAD

**Issue by kingguppy** [angular/angular#9190] opened 2016-06-14 11:58 UTC
* **I'm submitting a bug report**

* **Current behavior**

In the example provided below, there's an ngFor iterating over an array of Observables. Within the ngFor, each of the Observables is subscribed and its value output using the async pipe. By hitting a "Hide things" button, the ngFor template is destroyed (using ngIf). When the ngFor is destroyed , only half the subscriptions made by the async pipe are unsubscribed.

* **Expected/desired behavior**

After the ngFor template is destroyed, all the subscriptions made by the async pipe are unsubscribed.

* **Steps to reproduce and if possible a minimal demo of the problem**

http://plnkr.co/edit/C0hPY9HgfZ1QytdDK4hv

This should show "Thing X", with X being between 1 and 10 (inclusive). The numbers are output by the async pipe within an ngFor template. The Observables simply emit their number once to subscribers, and nothing further (no completion). They log subscriptions and unsubscriptions to the console.

Click on "Hide things" to destroy that ngFor template. The first time you do so, you will see that the subscription count changes from 10 to 5. The expected behaviour is that it changes from 10 to 0. In the console, you can see (by omission) that every second subscription made by async is *not* unsubscribed:

Unsubscribed from thing 1
Unsubscribed from thing 3
Unsubscribed from thing 5
Unsubscribed from thing 7
Unsubscribed from thing 9

* **Angular version:** 2.0.0-rc.1

* **Browser:** Chrome 51.0.2704.79
 
* **Language:** TypeScript 1.8.10

**Comment by ericmartinezr** [comment] 2016-06-14 12:50
See https://github.com/angular/angular/issues/8458

**Comment by kingguppy** [comment] 2016-06-14 13:41
Thanks @ericmartinezr! I applied e2b1e1577d37e443452b0f16386b6f1279dda04d, which is the change that fixed #8458, to my local 2.0.0-rc.1. It seems that this issue is indeed a symptom of the same problem, since with the fix applied everything is unsubscribed correctly.

**Comment by pkozlowski-opensource** [comment] 2016-06-14 13:44
@ericmartinezr thnx for finding a duplicate! 
@kingguppy I guess we can close this one as duplicate of #8458

**Closed by pkozlowski-opensource** 2016-06-14 13:44 UTC

**Comment by kingguppy** [comment] 2016-06-16 01:04
In case anyone's looking for a stronger sense of closure, I confirmed that the minimal demo works (i.e. the bug is not reproduced) in the just-released Angular 2.0.0-rc.2:

http://plnkr.co/edit/PF73iplr0vj3la2Lu7jP
