### ISSUE TITLE
Introduce WAITING status for control

### ISSUE THREAD

**Issue by dawidgarus** [angular/angular#22165] opened 2018-02-12 14:46 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Currently, it's hard to implement proper behavior for form control, when the control is not ready to be used. For example, in order to use `<select>`, http call must be performed to get list of available options. It get worse if list of available options depends on other form control and can change many times, for example when creating typeahead like behavior.
Right now, programmer only has 2 options: set controls state to DISABLED or INVALID until data is ready.
Both choices are bad. For one thing, it's not their meaning.
When we set control state to DISABLED, then form forgets about existing errors on the control and form becomes VALID.
When we set control state to INVALID, then it can mess with styles.

## Expected behavior
Control should have WATING status, that could be set using `markAsWating` method or `[waiting]` input. When at least one of the controls is waiting, then the whole form should be waiting.
Also `setWaitingState?` for `ControlValueAccessor` would be nice, so user could implement some kind of indicator and/or block control.

## Minimal reproduction of the problem with instructions
N/A

## What is the motivation / use case for changing the behavior?
In my app, this would be used all the time. Many selects depend on other control value. WAITING state would make implementation easier and less hacky.

**Comment by kara** [comment] 2018-02-27 14:33
@dawidgarus We do have a `PENDING` status and a `markAsPending()` method already. This status is neither valid nor invalid, so it shouldn't affect styles. Would this serve your use case? Hard to know without a minimal reproduction - can you add one if not?.

**Comment by kara** [comment] 2018-03-29 22:46
Since this doesn't have enough information to be actionable, I'm closing this for now. If you want to re-open with a specific repro case, please feel free.

**Closed by kara** 2018-03-29 22:46 UTC
Labels: comp: forms, state: Need repro, type: feature
