### ISSUE TITLE
No example for `I18nSelectPipe` in the docs

### ISSUE THREAD

**Issue by pawel-twardziak** [angular/angular#58708] opened 2024-11-17 17:06 UTC
### Describe the problem that you experienced

https://angular.dev/api/common/I18nSelectPipe?tab=usage-notes - there, `I18nSelectPipe` has no example

### Enter the URL of the topic with the problem

https://angular.dev/api/common/I18nSelectPipe?tab=usage-notes

### Describe what you were looking for in the documentation

I was looking for an example for `I18nSelectPipe`

### If this problem caused an exception or error, please paste it here

```true

```

### If the problem is browser-specific, please specify the device, OS, browser, and version

```true

```

### Provide any additional information here in as much as detail as you can

```true

```

**Comment by pawel-twardziak** [comment] 2024-11-17 22:49
I would be willing to submit a PR to fix this issue - just give my a sign for doing so dear Angular team :)

**Comment by JeanMeche** [comment] 2024-11-17 22:54
Thanks for the report, closing as a duplicate of https://github.com/angular/angular/issues/56321.

**Closed by JeanMeche** 2024-11-17 22:54 UTC

**Comment by pawel-twardziak** [comment] 2024-11-18 16:54
Great @JeanMeche 👍 thank you for taking this into consideration beforehand
