### ISSUE TITLE
Upgraded ng1 component $scope never gets $destroy event

### ISSUE THREAD

**Issue by kvantetore** [angular/angular#7613] opened 2016-03-15 11:45 UTC
* **I'm submitting a ... **
[x] bug report

* **What is the current behavior?**

When an upgraded ng1 component gets disposed the $scope created by the upgradeadapter never gets destroyed.

see https://plnkr.co/edit/pxxtGYBHTnzVzfbrhRhb?p=preview

When the button is clicked, the *ngIf disposes the upgraded ng1Comp component, and I would expect it to write "ng1-comp destroyed" to the console, but the $destroy event on the $scope is never called.

- Angular version: 2.0.0-beta.9

**Comment by gkalpak** [comment] 2016-03-15 18:01
Duplicate of #6401. Addressed in #6460.

**Closed by gkalpak** 2016-03-15 18:01 UTC

**Comment by kvantetore** [comment] 2016-04-14 12:10
Unfortunately, it is not fixed by #6460. That fixes destruction the other way around (where ngOnDestroy was not called on downgraded ng2 components). This issue is that the $scope is never destroyed on upgraded ng1 components

See https://plnkr.co/edit/K3pHi34qeuFxXOamKO7l?p=preview, where I have updated to beta 15, where the problem persists (would expect. 'ng1-comp destroyed' to be printed to the console when the button is clicked.)
