### ISSUE TITLE
Textarea element in form when binding model has initial state as dirty in IE

### ISSUE THREAD

**Issue by thanhpd** [angular/angular#14440] opened 2017-02-12 17:16 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Textarea element in form when binding model has initial state as dirty in IE

**Expected behavior**
Textarea element in form when binding model has initial state as pristine in IE

**Minimal reproduction of the problem with instructions**
Using ng-form with textarea element and bind model on that textarea

Plunker example: http://plnkr.co/edit/JEgKqSEXGpUDSRDuMXcD?p=preview
Inspect textarea in browser development tool. `textarea` and `form` element have `ng-pristine` CSS class in Chrome/Firefox/Edge while they have `ng-dirty` CSS class in IE.

**Please tell us about your environment:**
* **Angular version:** 2.4.7

* **Browser:** IE 11

**Comment by DzmitryShylovich** [comment] 2017-02-12 20:55
what os do you use?

**Comment by macjohnny** [comment] 2017-02-23 09:45
This also applies to input elements as well, see https://github.com/angular/angular/issues/14667 for an example.

**Comment by macjohnny** [comment] 2017-02-23 09:47
@DzmitryShylovich can you also add a test for an input element?

**Comment by DzmitryShylovich** [comment] 2017-02-23 09:49
@macjohnny ok I'll add a test

**Comment by macjohnny** [comment] 2017-02-23 09:53
@DzmitryShylovich thanks!

**Comment by mmalerba** [comment] 2017-03-21 21:21
FYI it's more than just pristine/dirty state being wrong, I've also noticed that it can cause the initial text in the textarea to be swallowed up (demonstrated here: http://plnkr.co/edit/fOtELWM6t0YKhcvCyFAk?p=preview)

**Comment by dimrun** [comment] 2017-04-27 17:33
Hi guys,
Do you have any updates on this? We have the same issue (with 'dirty' inputs in IE10/11).

**Comment by arun-mano** [comment] 2017-04-28 13:12
Hello Team,
Even for my project, the field touched is not toggled, even after changing the value in page,
I am trying to access the field(the param - touched) in ngAfterViewchecked(Where the model has the updated value but not the field Touched).

And as mentioned by others, In IE11, the field dirty is enabled on load of page

**Comment by Vaaceph** [comment] 2017-07-05 09:44
No body got solution for this?

**Comment by waterlooblue** [comment] 2017-08-09 15:13
@Vaaceph we have a workaround.

With our inputs, we were using placeholder text. IE would interpret the field as being dirty triggering the errors to show.

The touched and untouched properties were still working correctly. So we used touched as an extra validation for our error message.

`<md-input-container>
    <input id="email"
            type="email"
            mdInput
            required
            placeholder="Email"
            formControlName="email" />
</md-input-container>
<div *ngIf="formNameModel.get('formName').touched && formErrors.email">{{formErrors.email}}</div>`

**Comment by waterlooblue** [comment] 2017-08-09 15:23
@Vaaceph we have a workaround.

With our inputs, we were using placeholder text. IE would interpret the field as being dirty triggering the errors to show.

The touched and untouched properties were still working correctly. So we used touched as an extra validation for our error message.

```
<md-input-container>
    <input id="email"
            type="email"
            mdInput
            required
            placeholder="Email"
            formControlName="email" />
</md-input-container>
<div *ngIf="formNameModel.get('formName').touched && formErrors.email">{{formErrors.email}}</div>
```

The downside of this is you will need the user to be able to click the submit button. If they don't leave the field then they won't see the error and the form wouldn't be valid.

You will need to enable the submit button but only allow it to submit when valid.

**Comment by vladjerca** [comment] 2017-09-19 20:16
Any updates on this? I see @DzmitryShylovich opened a PR in February...

**Comment by twentytwokhz** [comment] 2017-09-28 10:24
@waterlooblue That actually helped. I added a touched check also for the validation and it seemed to do the trick. Awesome, thanks! 😁

**Comment by tmoffett-centrify** [comment] 2017-09-29 19:18
Any ETA on a real fix for this issue??  I know it's really the fault of the awful browser, IE, but it would be nice if this can be fixed in Angular to make it easier and have a consistent experience across browsers.

**Comment by remisture** [comment] 2017-10-26 14:12
@vladjerca Will that code work with reactive forms as well? Where do you place that for it to work "out-of-the-box"?

**Comment by vladjerca** [comment] 2017-10-30 15:19
@remisture Yes, it works with reactive forms. I've actually updated the code to cache values, in order to mark a form back to pristine if you revert values to the initial state.

``` javascript
import {
    FormGroupDirective as FormGroupDirectiveBase
} from '@angular/forms';
import { OnInit } from '@angular/core';

/*
Due to the fact that IE marks controls as dirty when placeholders are present.
Until there's an official fix in @angular/forms, we'll override the FG directive.
*/
export class FormGroupDirective
    extends FormGroupDirectiveBase
    implements OnInit {
    /**
     * Cache the form values when value changes occur.
     * Values get cached only if the new value is set while the input is pristine (initial load).
     * Forms will be by default pristine if the old values are present.
     */
    private _cache = {};

    ngOnInit() {
        this.form.valueChanges.subscribe(change => {
            const keys = Object.keys(this.form.controls);
            // clear cache entry for removed controls
            const staleKeys = Object.keys(this._cache).filter(k => !keys.includes(k));
            for (const key of staleKeys) {
                delete this._cache[key];
            }
            // evaluate and set cache for a newly initialized form group
            for (const key of keys) {
                const control = this.form.get(key);
                if (
                    this._cache[key] == null ||
                    !this._cache[key] &&
                    change[key] != null &&
                    control.pristine
                ) {
                    this._cache[key] = change[key];
                    control.markAsPristine();
                } else if (this._cache[key] === change[key]) {
                    control.markAsPristine();
                }
            }
        });

        // overload reset method to include cache clearing
        const reset = this.form.reset.bind(this.form);

        this.form.reset = (value?: any, options?: any) => {
            this._cache = {};
            reset(value, options || {
                onlySelf: true,
                emitEvent: true
            });
        };
    }
}

```

**Comment by forever14k** [comment] 2017-12-11 18:23
Might be related to: #15299, #16151, #17955.

I recently encountered this problem, Internet Explorer 10+ implements 'input' event but it erroneously fires under various situations, e.g. when placeholder changes, or a control is focused.

Microsoft knows about this issue, but not going to update Internet Explorer to fix this problem. [Link to issue](https://connect.microsoft.com/IE/feedbackdetail/view/856700).

Using [UI Events specification](https://www.w3.org/TR/uievents/#events-keyboard-event-order) that defines specific keyboard event order, i wrote `EventManagerPlugin` that checks if elements value was actually changed before firing `input` event. 
https://github.com/forever14k/angular-actual-input-event-manager-plugin

**Comment by adwd** [comment] 2018-01-15 02:42
@vladjerca Thank you for your workaround, but when I tried it, submit occurs twice. How can I fix it?
https://stackblitz.com/edit/angular-c5m1nz?file=app%2Fapp.module.ts

**Comment by vladjerca** [comment] 2018-01-15 10:04
@adwd I don't use (ngSubmit) to bind forms, I directly bind to (submit).

**Comment by adwd** [comment] 2018-01-15 11:23
@vladjerca wow fix to `(submit)="onSubmit($event)"` and it works 😂 I don't know why but thanks!

**Comment by somuenc** [comment] 2018-02-26 15:44
@DzmitryShylovich  and All,
Do we have a fix for the above issue where input is firing of with empty string only in IE 11 when it has placeholder in it. I am unable to figure out or hack the way to come out of it. Since i have a situation where I need to fire event for empty search also in my application.
I am using angular 4.4, IE 11, Win 10 OS and my search field has input with placeholder.
Any help would be appreciable since am struggling with issue from a week time and there is no response from Micrsoft to fix the issues in IE11.
Regards
Soma

**Comment by mlc-mlapis** [comment] 2018-02-26 20:17
... so it is funny ... `Microsoft knows about this issue, but not going to update Internet Explorer to fix this problem` ... and all above are trying to find some extra, super magic trick? So it is probably the right time to forget about IE, isn't it?

**Comment by vladjerca** [comment] 2018-02-26 23:49
@mlc-mlapis Sadly a lot of Enterprise clients enforce IE usage. Else this discussion wouldn't even exist, clearly.

**Comment by mlc-mlapis** [comment] 2018-02-26 23:57
@vladjerca ... I believe that using IE means much more cost than savings and it is really counterproductive ... and it is also one of the main reason why MS dropped IE to the cemetery of history.

**Comment by vladjerca** [comment] 2018-02-27 00:15
@mlc-mlapis I'm on you with this one, but tell the huge corporate security/management teams. Everyday I find out a new reason why they use IE (none of them actually make sense) it's more of a procedure limbo inside the companies.

Nobody I personally know uses IE at work/home, but our clients do 😢

**Comment by Tenmak** [comment] 2018-03-01 18:29
@vladjerca Thanks for the quick fix, but I cannot manage to make the Directive compile. I get an error that this needs an `@NgModule` annotation. Did you do anything particular with how you import the `ReactiveFormsModule` ?

Had to pollute the code meanwhile.

**Comment by vladjerca** [comment] 2018-03-02 11:45
@Tenmak You just need to import this inherited directive in one of your top level Modules.

For example I have:

```
const DIRECTIVES = [
    FormGroupDirective,
   ...OTHER_DIRECTIVES
];

@NgModule({
    imports: [CommonModule],
    declarations: DIRECTIVES,
    exports: DIRECTIVES
})
export class DirectivesModule { }
```

**Comment by adrianbenjuya** [comment] 2018-03-06 20:54
Hi, any update on this? does version 5.2.0 fix this? This is breaking my forms validations :(

**Comment by andrew5277** [comment] 2018-04-02 13:47
@vladjerca I tried to get the directive to work with template form, but it's not fired. Any idea?

**Comment by Tenmak** [comment] 2018-04-02 15:03
@andrew5277 In the end I exported a function resetting  : 

```
       setTimeout(() => {
            for (const key in this.form.controls) {
                if (this.form.controls[key]) {
                    this.form.controls[key].markAsPristine();
                }
            }
        });
```

and import it in every component that needs it in the `ngAfterViewInit()`

**Comment by vladjerca** [comment] 2018-04-02 16:34
@andrew5277 Sorry, I only use Reactive Forms, no idea how things interact for template driven forms.

**Comment by andrew5277** [comment] 2018-04-02 19:25
Thanks @Tenmak and @vladjerca for the update!

**Comment by Rohith47** [comment] 2018-04-10 19:37
Hi Guys, I need to mark the input as pristine in IE, when there is a placeholder and user clicks on input element. Trying do it, by writing a custom validator. But I'm unable to get access to element, with in validate method. Also, is there any better way to do it.

**Comment by Yura13** [comment] 2018-05-14 15:56
Currently, the best workaround proposed by @waterlooblue. Thanks!

**Comment by jameel-samaan** [comment] 2018-05-24 07:54
I also have the same problem in IE 11. The problem happend only when I use special characters in the placeholder. I am using german language, therefore I got ng-dirty when I use ä, ö, ü or ß in placeholder. So I think, the problem is with IE and not with Angular itself 🤣

**Comment by williamchristophercooley** [comment] 2018-07-20 19:30
@vladjerca would your solution work for FormBuilder as well?

**Comment by wctiger** [comment] 2018-10-02 18:37
I am using a template-driven form in Angular 6.1.0 and also have this issue in IE11. 
I tried reset that form or mark the controls as pristine but none of them worked in my case. As I do have other labels to indicate what the input field does, I did the following to assign an empty string placeholder to the input when browser is IE
`<input name="userId" placeholder="{{isBrowserIE() ? '' : 'User Id'}}">`

```  
isBrowserIE() {
      const ua = navigator.userAgent;
      /* MSIE used to detect old browsers and Trident used to newer ones*/
      const is_ie = ua.indexOf('MSIE ') > -1 || ua.indexOf('Trident/') > -1;
      return is_ie; 
  }
```

I know this is not even a workaround but rather bypassing the issue. Just want to post it here in case anyone want a similar approach.

**Comment by cvbc2010** [comment] 2018-11-22 10:00
we can achieve the same without placeholder as below

<input matInput placeholder='asdjfkasdj'></input>
as
<mat-label>label placeholder text</mat-label>
<input matInput ></input>

**Comment by mivanyna** [comment] 2019-01-30 14:08
Seems that changing `placeholder="some text"` to [placeholder]="'some text" fixes the issue

**Comment by eddy14u** [comment] 2019-02-05 14:42
> @remisture Yes, it works with reactive forms. I've actually updated the code to cache values, in order to mark a form back to pristine if you revert values to the initial state.
> 
> As for placement, I just import my Form Group Directive in the shared module after the angular imports.
> 
> ```js
> import {
>     FormGroupDirective as FormGroupDirectiveBase
> } from '@angular/forms';
> import { OnInit } from '@angular/core';
> 
> /*
> Due to the fact that IE marks controls as dirty when placeholders are present.
> Until there's an official fix in @angular/forms, we'll override the FG directive.
> */
> export class FormGroupDirective
>     extends FormGroupDirectiveBase
>     implements OnInit {
>     /**
>      * Cache the form values when value changes occur.
>      * Values get cached only if the new value is set while the input is pristine (initial load).
>      * Forms will be by default pristine if the old values are present.
>      */
>     private _cache = {};
> 
>     ngOnInit() {
>         this.form.valueChanges.subscribe(change => {
>             const keys = Object.keys(this.form.controls);
>             // clear cache entry for removed controls
>             const staleKeys = Object.keys(this._cache).filter(k => !keys.includes(k));
>             for (const key of staleKeys) {
>                 delete this._cache[key];
>             }
>             // evaluate and set cache for a newly initialized form group
>             for (const key of keys) {
>                 const control = this.form.get(key);
>                 if (
>                     this._cache[key] == null ||
>                     !this._cache[key] &&
>                     change[key] != null &&
>                     control.pristine
>                 ) {
>                     this._cache[key] = change[key];
>                     control.markAsPristine();
>                 } else if (this._cache[key] === change[key]) {
>                     control.markAsPristine();
>                 }
>             }
>         });
> 
>         // overload reset method to include cache clearing
>         const reset = this.form.reset.bind(this.form);
> 
>         this.form.reset = (value?: any, options?: any) => {
>             this._cache = {};
>             reset(value, options || {
>                 onlySelf: true,
>                 emitEvent: true
>             });
>         };
>     }
> }
> ```

I found this solution to not handle checkbox's correctly, requiring a double click for my component to detect the change

**Comment by smittal1991** [comment] 2019-11-01 09:25
> Seems that changing `placeholder="some text"` to [placeholder]="'some text" fixes the issue

This worked for me but by using [placeholder]="'some text'", the closing ' was missing in suggestion

**Comment by sharathgg5** [comment] 2019-11-04 09:47
Note: Temporary solution until we have fix.
I was looking at above workaround, instead  of marking each field pristine try
`this.form.markAsPristine(); `

**Comment by montananyto-dev** [comment] 2020-06-11 07:55
Thank you so much @mivanyna . That helps a lot. I was having the same issue with Internet Explorer 11.

**Comment by nitinnairdev** [comment] 2020-11-07 15:13
For devs facing issues with Angular Material showing error for form-fields, use `mat-label` instead of `placeholder`.

**Comment by AndrewKushnir** [comment] 2022-03-01 00:28
Closing this ticket, since the reported problem was only present in IE11 and Angular no longer supports IE.

**Closed by AndrewKushnir** 2022-03-01 00:28 UTC
Labels: type: bug/fix, freq1: low, comp: forms, state: confirmed, browser: ie 11, triage #1, P4
