### ISSUE TITLE
Pipes Api not working

### ISSUE THREAD

**Issue by SalmaanMushtaq** [angular/angular#55452] opened 2024-04-21 15:10 UTC
### Describe the problem that you experienced

when clicking on the Pipes API documentation : For a complete list of built-in pipes, see the [**pipes API documentation**] , it was supposed to open the pipes api but it shows the Page Not Found page.

### Enter the URL of the topic with the problem

https://angular.dev/api/common#pipes 

### Describe what you were looking for in the documentation

I was looking for the API documentation of Piping

### Describe the actions that led you to experience the problem

By clicking on the pipe API documentation. 

### Describe what you want to experience that would fix the problem

Add the pipes API documentation component

**Comment by JoostK** [comment] 2024-04-21 16:08
Duplicate of #52968

**Closed by JoostK** 2024-04-21 16:08 UTC
