### ISSUE TITLE
Date filter issue with UTC timezone when used from browser on DST change 

### ISSUE THREAD

**Issue by bergmeister** [angular/angular#29537] opened 2019-03-27 11:28 UTC
# 🐞 bug report

### Affected Package

Not sure.

### Is this a regression?

No, this is to create/move an issue in `angular` as well that is already present in `angular.js` (and applies to both `angular` and `angular.js)`.

### Description

In order to avoid duplication, the original issue that applies to both `angular` and `angular.js` is below:
https://github.com/angular/angular.js/issues/14418

## 🔬 Minimal Reproduction

See
https://github.com/angular/angular.js/issues/14418

## 🌍  Your Environment

**Angular Version:**

```
Angular CLI: 7.0.2
Node: 8.12.0
OS: win32 x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.10.2
@angular-devkit/core         7.0.2
@angular-devkit/schematics   7.0.2
@schematics/angular          7.0.2
@schematics/update           0.10.2
rxjs                         6.3.3
typescript                   3.1.3
```

</code></pre>

**Anything else relevant?**

Does not seem to be Browser specific as it happens in Chrome, Firefox and IE

**Comment by dylhunn** [comment] 2022-07-11 23:58
@bergmeister Would you be able to produce an Angular 14 SatckBlitz reproduction, rather than the old AngularJS repro?

**Comment by bergmeister** [comment] 2022-07-12 06:13
No, as I don't work on the product any more that was affected by this bug.

**Comment by JeanMeche** [comment] 2024-02-11 21:01
Since we don't have a repro, I'm going to close this.

**Closed by JeanMeche** 2024-02-11 21:01 UTC
Labels: type: bug/fix, area: common, area: i18n, freq1: low, state: confirmed, P3
