### ISSUE TITLE
Issue in RegularExpression of compiler.es5.js

### ISSUE THREAD

**Issue by leantrace** [angular/angular#19475] opened 2017-09-29 10:34 UTC
## I'm submitting a...

<pre><code>
[x ] Bug report  
</code></pre>

## Current behavior
When compiling the code with angular 4.4.4 RegularExpression error occurs with compiler.es5.js in Chrome. Works for FireFox and IE

**ERROR**
```
Uncaught SyntaxError: Invalid regular expression: /[^ 

	áš€á Žâ€€-â€Š  â€¯âŸã€€﻿]/: Range out of order in character class
    at new RegExp (<anonymous>)
    at Object.<anonymous> (compiler.es5.js:11179)
    at __webpack_require__ (bootstrap 67d1464d0d39ec17d21d:54)
    at Object.<anonymous> (vendor.67d1464d0d39ec17d21d.js:112234)
    at __webpack_require__ (bootstrap 67d1464d0d39ec17d21d:54)
    at Object.506 (main.67d1464d0d39ec17d21d.js:453)
    at __webpack_require__ (bootstrap 67d1464d0d39ec17d21d:54)
    at window.webpackJsonp (bootstrap 67d1464d0d39ec17d21d:25)
    at main.67d1464d0d39ec17d21d.js:1
```

Looks like the problem is somewhere here (@angular/compiler/compiler.es5.js):
```
var WS_CHARS = ' \f\n\r\t\v\u1680\u180e\u2000-\u200a\u2028\u2029\u202f\u205f\u3000\ufeff';
var NO_WS_REGEXP = new RegExp("[^" + WS_CHARS + "]");
```

## Minimal reproduction of the problem with instructions
Since I compiled the code with 4.4.4 - with 4.4.3 it works quite well

## What is the motivation / use case for changing the behavior?
Hope that other developers dont run in the same problem and if so they will hopefully find a solution here

## Environment

<pre><code>
Angular version: 4.4.4

Browser:
- [ x] Chrome (desktop) version 61.0.3163.100
 
For Tooling issues:
- Node version: 8.5.0
- Yarn version: 1.0.2
- Platform:  Tomcat 8.0.43 on Red Hat 7, OpenShift

**Comment by vicb** [comment] 2017-09-29 18:46
Could you please add details on how to reproduce the issue ?

The team works with chrome 99.99% of the time and we haven't seen any issue.

**Comment by pkozlowski-opensource** [comment] 2017-09-29 18:58
As @vicb commented, we need a reproduce scenario since I can't reproduce it in the newish versions of chrome. What is the exact version that you are using?

Could you please also try to run `var re = new RegExp(`[ \f\n\r\t\v\u1680\u180e\u2000-\u200a\u2028\u2029\u202f\u205f\u3000\ufeff]{2,}`, 'g');` in the console of your browser? 

Also, could you please test in the incognito mode to remove chance of interference from browser extensions?

**Comment by vicb** [comment] 2017-09-29 20:38
`/[b-a]/` would generate that error -> root cause of the issue you see is `€-â` in the regexp.

The question is when/why `u1680\u180e\u2000-\u200a\u2028\u2029\u202f\u205f\u3000\ufeff` gets turned into `�áš€á Žâ€€-â€Š  â€¯â�Ÿã€€﻿` ?

**Comment by leantrace** [comment] 2017-10-03 15:03
Hallo guys, 

thx for looking into this issue.
I realized that with the version 4.4.4. a new line was added to compiler.es5.js:
```
var WS_CHARS = ' \f\n\r\t\v\u1680\u180e\u2000-\u200a\u2028\u2029\u202f\u205f\u3000\ufeff';
var NO_WS_REGEXP = new RegExp("[^" + WS_CHARS + "]");
```
I use webpack to bundle the angular code for production. It creates me a "vendor.xyz.js"-File. After packaging with webpack these contains the following line:

```
[...] er=" \f\n\r\t\váš€á Žâ€€-â€Š\u2028\u2029â€¯âŸã€€\ufeff",tr=new RegExp("[^"+er+"]"),nr=new RegExp("["+er+"]{2,}","g")[..]
```

So it looks like a packaging problem not an angular problem. I could not solve it so far.

**Comment by tbosch** [comment] 2017-10-03 21:26
Ok, cool. Closing then.

**Closed by tbosch** 2017-10-03 21:26 UTC
Labels: comp: core & compiler, severity5: regression, state: Follow Up, type: bug

**Comment by krivochenko** [comment] 2017-11-02 17:59
@leantrace I encountered a similar issue. Did you find solution?

**Comment by leantrace** [comment] 2017-11-03 14:05
@krivochenko 
I downgraded the angular compiler.es5.js version one version down in package.json, where the following change is not present:

> I realized that with the version 4.4.4. a new line was added to compiler.es5.js:
> var WS_CHARS = ' \f\n\r\t\v\u1680\u180e\u2000-\u200a\u2028\u2029\u202f\u205f\u3000\ufeff';
> var NO_WS_REGEXP = new RegExp("[^" + WS_CHARS + "]");

**Comment by consigliory** [comment] 2017-11-08 11:46
Same issue.

**Comment by krivochenko** [comment] 2017-11-09 06:59
@leantrace thanks for answer. In my application module, which causes error, is used only in server-side chunk. So, I avoid to use minification for server.js

**Comment by johankvint** [comment] 2017-11-09 12:25
I have the same issue!

**Comment by OlegRovenskyi** [comment] 2017-11-10 16:36
I have the same issue. 
When I used angular 4.4.4;  "ngx-bootstrap": "2.0.0-beta.5" and  "webpack": "3.7.1". 
In my case I have two solution:
First variant:
Rolled back to angular 4.4.3 this problem was fixed.
or 
Second variant:
Rolled back ngx-bootstrap to v1.9.2 this problem was fixed.

When I debugged I saw problem with ngx-bootstrap
// CONCATENATED MODULE: ./node_modules/ngx-bootstrap/typeahead/latin-map.js
/* tslint:disable:max-file-line-count */
var latinMap = {
    Ã: 'A', <= Invalid character '\u0129'

**Comment by chuckeles** [comment] 2017-11-14 08:58
I found a solution for this: [add `charset='utf-8'` to all your scripts](https://github.com/mishoo/UglifyJS2/issues/54#issuecomment-26230544)

**Comment by bertyhell** [comment] 2018-03-07 17:52
for anyone running into this error while using the webpack plugin: UglifyJs

```js
new UglifyJsPlugin({
    uglifyOptions: {
      output: {
        ascii_only: true,
        beautify: false
      }
    }
  })
```

**Comment by pmaierean** [comment] 2018-03-08 15:11
This is to confirm that the configuration parameter 'ascii_only' for the UgllifyJsPlugin does the trick
Great finding

**Comment by wvary** [comment] 2018-03-26 16:53
@bertyhell 's solution resolves my "Invalid regular expression" error, but I'm seeing "Unknown provider: eProvider <- e <- xxx" error now.  On to the next troubleshooting step.

**Comment by brachi-wernick** [comment] 2018-03-29 08:30
For anyone running into this error while using the systemjs-builder plugin, from version 0.16.12 they add [add ascii output option](https://github.com/systemjs/builder/commit/b1c09a5c9aad659301abab27018ab6b17c5f2808)
this solve me the issue
