### ISSUE TITLE
Broken link in Roadmap Page

### ISSUE THREAD

**Issue by aktasahmet** [angular/angular#52853] opened 2023-11-13 12:12 UTC
### Describe the problem that you experienced

Under the "[Explore modern Angular](https://angular.dev/roadmap#explore-modern-angular)" topic, there is an article for "[Try out Inject](https://angular.dev/di)" but its link is broken.

### Enter the URL of the topic with the problem

https://angular.dev/roadmap#explore-modern-angular

**Comment by JoostK** [comment] 2023-11-13 13:02
Thanks for the report, this is a duplicate of #52539

**Closed by JoostK** 2023-11-13 13:02 UTC
