### ISSUE TITLE
JSONP injected script still did not invoke callback

### ISSUE THREAD

**Issue by brice-prunier-dev** [angular/angular#39738] opened 2020-11-18 16:41 UTC
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/common/http.

### Is this a regression?
I don't know, it is the first time i try Jsonp with Angular.

### Description

JSONP injected script did not invoke callback
I know this case has been opened and closed but there is still an issue.

## 🔬 Minimal Reproduction
stackblitz ![angular-jsonp-brice project](https://stackblitz.com/edit/angular-jsonp-brice?file=src%2Fapp%2Fapp.component.html)

## 🔥 Exception or Error
On the Angular Project where i found out the issue, i've got one more info : 
the json error that is returned has an error property with "JSONP injected script did not invoke callback."
What i didn't get on the stackblitz project.
<pre><code>
HttpErrorResponse {
headers: HttpHeaders, 
status: 0, 
statusText: 'JSONP Error', 
url: 'https://my-url.com/my-path/swagger.json?call1=ng_jsonp_callback_2', ok: false, …}
src/app/_core/services/apis.service.ts:89
error: Error: JSONP injected script did not invoke callback.
at HTMLScriptElement.onLoad (http://localhost:4200/vendor.js:134643:32)
at ZoneDelegate.invokeTask (http://localhost:4200/polyfills.js:514:35)
at Object.onInvokeTask (http://localhost:4200/vendor.js:47412:33)
at ZoneDelegate.invokeTask (http://localhost:4200/polyfills.js:513:40)
at Zone.runTask (http://localhost:4200/polyfills.js:282:51)
at ZoneTask.invokeTask [as invoke] (http://localhost:4200/polyfills.js:595:38)
at invokeTask (http://localhost:4200/polyfills.js:1736:18)
at HTMLScriptElement.globalZoneAwareCallback (http://localhost:4200/polyfills.js:1762:21) {stack: 'Error: JSONP injected script did not invoke c… (http://localhost:4200/polyfills.js:1762:21)', message: 'JSONP injected script did not invoke callback.'}
headers:HttpHeaders {normalizedNames: Map(0), lazyUpdate: null, headers: Map(0)}
message:'Http failure response for https://iamapi-dev.ase.ncd.infrasys16.com/swagger/intact-admin/swagger.json?call1=ng_jsonp_callback_2: 0 JSONP Error'
name:'HttpErrorResponse'
ok:false
status:0
statusText:'JSONP Error'
url:'https://my-url.com/my-path/swagger.json?call1=ng_jsonp_callback_2'

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre>Microsoft Windows [Version 10.0.17134.1246]
(c) 2018 Microsoft Corporation. All rights reserved.
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 10.1.7
Node: 12.17.0
OS: win32 x64

Angular: 10.1.6
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.901.10
@angular-devkit/build-angular      0.1001.7
@angular-devkit/build-ng-packagr   0.1001.7
@angular-devkit/core               9.1.10
@angular-devkit/schematics         10.1.7
@angular/cdk                       10.2.5
@angular/cli                       10.1.7
@angular/flex-layout               10.0.0-beta.32
@angular/material                  10.2.5
@schematics/angular                10.1.7
@schematics/update                 0.1001.7
ng-packagr                         10.0.0
rxjs                               6.5.5
typescript                         4.0.3
</pre>

**Anything else relevant?**

### My Context
- I need to use "jsonp" requests pattern to load all the API swagger.json  of my enterprise to build a catalog so i need a way to bypass CORS.
- I turn on fidller and i can stated that on a jsonp request the swagger.json is correctly loaded: **HTTP 200**.

### My Homework
I spent some time to read **@angular/common/http/src/jsonp.ts** and there is still something that doesn't match my understanding: 

On a Jsonp Query you got a **JsonpInterceptor** that initiate a **JsonpClientBackend** having 
- a *callbackMap* property of type **JsonCallbackContext**. 
- a *resolvedPromise* **microtask** .

This interceptor launch the call by invoking **JsonpClientBackend**.*handle(req: **HttpRequest<never>**): **Observable<HttpEvent<any>**>*. 
- this method setup the **JsonpClientBackend**.*resolvedPromise* **microtask** by setting
> - a HTML **script** tag,
> - a callback on the here above **JsonpClientBackend**.*callbackMap*,
> - the **onLoad** event of the **script** tag that itself set  up:
>   - the **microtask** by implementing **resolvedPromise**.*then*.

To complete the **microtask**  implemented on **resolvedPromise**.*then* you need a *finished* flag to be set at *true*.
- This *finished* flag is set to *true* by the callback spare  on private  **JsonpClientBackend**.*callbackMap*.

My 2 cents ✍️:
I DID'NT FIND ANY CODE THAT TRIGGER THE **JsonpClientBackend**.*callbackMap*:

something like 
<pre><code>this.callbackMap[callback]( body )</code></pre>

Maybe i'm wrong but be sure that before i wrote this post i check and check and chek again...
That is the only reason i found  to explain why despite my resource is loaded I always get *JSONP injected script did not invoke callback.*

**Comment by brice-prunier-dev** [comment] 2020-11-18 16:46
Sorry the markdown stackblitz link doesn't seems to be OK: 
It is  https://stackblitz.com/edit/angular-jsonp-brice?file=src%2Fapp%2Fapp.component.html

**Comment by atscott** [comment] 2020-11-18 17:07
This looks like a duplicate of #39496, fixed by #39512. There has not yet been a release since this change was merged. Please wait for the next release (today or tomorrow). 

If after upgrade the problem still exists in your application please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.

**Comment by brice-prunier-dev** [comment] 2020-11-18 19:00
Hi Andrew,

I’m sorry to disturb you  again, but the fix that has been commited few hour ago won’t solve the issue.
The point is that the unit test on jsonp bypass the issue.

I know it seem really  pretentious but i ve been reading the json.ts file (252 lines ) for 2 days.
If you take a look a my issue i describe the error that is still there.

It is very simple :

  *   There id a « finished » flag that will never be turned to true.
     *   Why : because to do so a callback should be trigger but no code will :
        *   Let have a look : the flag is only declare 3 times in jsont.ts that is a small file ( 252 lines )
           *   Line 101 -> initalization
           *   121 : the flag is turn to true within the callback call
           *   153 : Flag evaluation in the microtask
        *   If you search you won’t find anything that can trigger the callback that should turn the « finished » flag to true
           *   It should be
              *   this.callbackMap[callback]( body )



     *   Why the unit test work : In the test file jsonp_spec.ts there is a function line 17 runOnlyCallback that simulate the famous callback that is never trigerred.
        *   On every test the runOnlyCallback is callled so everything run wells but it won’t happen i real world.


My only expectation is to get this bug fix because i do need this jsonp feature to work.

I understand that you should get plenty of complains and i don’t believe you read this one to the end.

Anyway have a good day and a good health.

Brice PRUNIER
72 rue Michel Ange
75016, Paris
Å 06 58 96 49 51

De : Andrew Scott<mailto:notifications@github.com>
Envoyé le :mercredi 18 novembre 2020 18:07
À : angular/angular<mailto:angular@noreply.github.com>
Cc : Brice Prunier<mailto:brice.prunier@live.com>; Author<mailto:author@noreply.github.com>
Objet :Re: [angular/angular] JSONP injected script still did not invoke callback (#39738)


This looks like a duplicate of #39496<https://eur06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fangular%2Fangular%2Fissues%2F39496&data=04%7C01%7C%7C62c64ccde0aa44fff3f508d88be47303%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637413160574290284%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=EYkQc%2FJkhVsqbGUMjP4c5k%2FphM4j%2BGGd%2Bq9U5sDoddo%3D&reserved=0>, fixed by #39512<https://eur06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fangular%2Fangular%2Fpull%2F39512&data=04%7C01%7C%7C62c64ccde0aa44fff3f508d88be47303%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637413160574290284%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=0Y%2BnBfSAedVg%2BLKuWgYjgZpBCIN0oxbudlrzW%2B4A318%3D&reserved=0>. There has not yet been a release since this change was merged. Please wait for the next release (today or tomorrow).

If after upgrade the problem still exists in your application please open a new issue<https://eur06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fangular%2Fangular%2Fissues%2Fnew%2Fchoose&data=04%7C01%7C%7C62c64ccde0aa44fff3f508d88be47303%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637413160574300285%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Ktc3iYyaF9M1%2B7A9LmYlUs19q1a2BB5FN1C%2BODFWERE%3D&reserved=0> and follow the instructions in the issue template.

**Comment by atscott** [comment] 2020-11-18 19:10
@mhevery @JiaLiPassion Can you take a look at this?

**Comment by sebastianhaeni** [comment] 2020-11-19 12:32
@brice-prunier-dev The code that calls the callback is in the Javascript loaded from the provided URL. It knows which callback to call by the query parameter. `callback` in your example. 

The provided example with URL `https://petstore.swagger.io/v2/swagger.json` does not support JSONP.

Here's an endpoint that supports JSONP:

- https://maps.googleapis.com/maps/api/js?client=gme-baz&callback=foobar

Whatever you choose as your callback name will be the function called on the `window` object. Try to get the above Javascript and search for `foobar`.

**Comment by mhevery** [comment] 2020-11-19 18:29
I think @alxhub is a better person for this.

**Comment by alxhub** [comment] 2020-11-19 18:44
@sebastianhaeni is on point here - JSONP as a protocol works by loading a script onto the page which triggers the callback. The name of the function to call is passed as a parameter in the script URL.

You can't load a plain JSON file like `https://petstore.swagger.io/v2/swagger.json` via JSONP - the endpoint must explicitly support the JSONP protocol. This is working as intended.

**Closed by alxhub** 2020-11-19 18:44 UTC
Labels: comp: common/http
