### ISSUE TITLE
Strange flickering with PWA version of angular.io

### ISSUE THREAD

**Issue by bampakoa** [angular/angular#42365] opened 2021-05-26 19:37 UTC
# Docs or angular.io Bug Report

### Description

 When I start the PWA version of the angular.io, I get a strange CSS glitch at the far left corner of the app.

### What's the affected URL?**
 The landing page of the application

### Reproduction Steps**

Try to open the PWA version in either Windows or Mac

## Screenshot

Windows: 
![angular-io](https://user-images.githubusercontent.com/7170892/119720893-3682f280-be73-11eb-9958-e78d759e2899.gif)

Mac: https://www.loom.com/share/e10a7358628f4c6ea4b64078e4be3041

## Exception or Error
<pre><code>

</code></pre>

**Comment by petebacondarwin** [comment] 2021-05-26 19:53
It seems to me that this is a flash of unstyled content... I have also started seeing this occasionally on the normal website (not just the PWA). We should investigate.

**Comment by bampakoa** [comment] 2021-05-27 21:16
@petebacondarwin I have uploaded more clues from my findings after the new version of io that went live today. I have also managed to get a screenshot of the exact time that the flash occurs. I hope that helps.

![aio](https://user-images.githubusercontent.com/7170892/119897759-96e46380-bf49-11eb-95a1-277fe4c84d03.gif)
![flickering](https://user-images.githubusercontent.com/7170892/119897781-9ea40800-bf49-11eb-90ee-6848d8c7b84c.png)

**Comment by petebacondarwin** [comment] 2021-05-28 13:31
Currently we have two hypotheses:

1) Chrome is caching the HTML from a previously rendered page and showing it before the CSS has been processed.
2) The new inline critical styles feature of the CLI makes the CSS stylesheet download non-blocking, which allows the Angular application to bootstrap and start rendering before the CSS has completed its download.

I think 2) is the more likely, since I have only noticed this happening recently, which coincides with the release of the feature on the CLI.

Indeed looking at the page source for angular.io/index.html, we see the following "critical inlined css":

```css
html {
  font-size: 62.5%;
}

body {
  font-family: Roboto, Helvetica Neue Light, Helvetica Neue, Helvetica, Arial,
    Lucida Grande, sans-serif;
  margin: 0;
  font-size: 16px;
  font-size: 1.6rem;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}
body,
html {
  height: 100%;
}
@media print {
  * {
    box-shadow: none !important;
  }
  body {
    background: none !important;
  }
}
```

And then the main stylesheet is loaded for `print` media only to make it non-blocking and only enabled (by setting the media value to `all` when it has loaded:

```html
<link rel="stylesheet" href="styles.581eaab3eb8288d25b2c.css" media="print" onload="this.media='all'">
```

I think that until we can ensure that the critical CSS that is extracted is valid for our start up, we should disable the critical inlining on this project.

**Comment by bampakoa** [comment] 2021-05-31 15:36
Thanks for the clarification. I can also verify that this behavior was not present before v12.

**Comment by rafa-as** [comment] 2021-06-01 11:57
I can confirm that this behavior happens on v12 but not on v11 on the angular.io (PWA and Website).

v11 - inlineCritical disabled by default
![ezgif com-video-to-gif-2](https://user-images.githubusercontent.com/594574/120315453-af9fa100-c2dc-11eb-8349-150e23ade12d.gif)

v12 - inlineCritical enabled by default
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/594574/120315024-2daf7800-c2dc-11eb-8dd3-c847960304ac.gif)

We have the same bug on our website after the v11 upgrade and activate the `inlineCritical` flag. We are checking how to revert the `inlineCritical` or how to solve this issue. 

Maybe can be helpful this issue: 

- Issue: https://github.com/angular/universal/issues/2002
- Comment: https://github.com/angular/universal/issues/2002#issuecomment-786630583

We already have checked the `inlineCriticalCss` on the SSR (server.ts) and the initial flickering disappears but when you navigate through the app the CSS is broken.

@petebacondarwin what do you mean with:

> I think that until we can ensure that the critical CSS that is extracted is valid for our start up [....]

This means that the devs must be do something to make it work properly or this behaviour it's a bug that should be resolved by the Angular team?

If you need some help, please tell me, I will be happy to help

**Comment by rafa-as** [comment] 2021-06-01 13:51
Right now I can confirm that the problem is `inlineCritical` related.

Our app with v11:

* NO flickering
```json
"optimization": {
  "scripts": true,
  "fonts": {
    "inline": true
  },
  "styles": true
}
```

* Flickering
```json
"optimization": {
  "scripts": true,
  "fonts": {
    "inline": true
  },
  "styles": {
    "minify": true,
    "inlineCritical": true
  }
}
```

**Comment by rafa-as** [comment] 2021-06-01 21:17
@gkalpak do you considere that this is a bug on the Angular side? An issue should be created to solve it and allow Angular users to activate `inlineCritical` flag without FOUC?

**Comment by gkalpak** [comment] 2021-06-02 11:09
The CLI team is in a better position to answer that, so I'll let them speak about it. (cc @alan-agius4)

**Comment by alan-agius4** [comment] 2021-06-02 12:39
The risk of FOUC will always be there when using critical css inlining with a CSR only application which AIO is. This is because styles will be changed to be non render blocking, this was also mentioned in the RFC (https://github.com/angular/angular-cli/issues/18730). In a CSR application, the application is not rendered during build-time and the critical css is only extracted from the `index.html` (More info about this, in the linked RFC above). AIO also mainly uses a global stylesheet to define the styles (`styles.css`) instead of component encapsulated styles. This will increase the chance of FOUC even more.

We are currently however, looking into an alternate CSS loading method which does seem to reduce FOUC and also makes inlining of critical CSS CSP complaint (Related issue: https://github.com/angular/angular-cli/issues/20864). That said, this does have the drawback that it will break users who depend on CSS rule ordering instead of selector weight.

To get rid of any possibility of having FOUC, there are a couple of approaches.
- Use to SSR or Pre-rendering
- Disable critical inlining of CSS which causes a performance overhead since the CSS will be render blocking.

**NB:** this type of FOUC only appears when loading the application and not when navigating between one page to another. This is between, when navigating between one page to another the global CSS is already loaded.

**Comment by hakimio** [comment] 2021-06-03 18:14
@alan-agius4 Considering how many issues critical CSS inlining causes, maybe the default should be reverted back to disabled for new projects and upgrades from v11?

**Comment by alan-agius4** [comment] 2021-06-03 18:22
> @alan-agius4 Considering how many issues critical CSS inlining causes, maybe the default should be reverted back to disabled for new projects and upgrades from v11?

Mind elaborating which issues your are referring so that we are on the same page?

Note: changing the default now is a breaking change so that cannot be taken lightly, in general it’s better to address issues instead of reverted back features.

**Comment by hakimio** [comment] 2021-06-03 18:42
@alan-agius4 One major issue is [this one](https://github.com/angular/angular-cli/issues/20760). It's breaking a lot of different UI libraries.

**Comment by alan-agius4** [comment] 2021-06-03 19:09
> @alan-agius4 One major issue is [this one](https://github.com/angular/angular-cli/issues/20760). It's breaking a lot of different UI libraries.
> 
> EDIT: [this one](https://github.com/angular/angular-cli/issues/20864) as well.

We are working with the Chrome team to address the first issue. Regarding the CSP issue mentioned in the second one, we have a couple of possible solutions that we are exploring. 

Not to undermine the importance of both issues because we take them very seriously, the Angular CLI v12 was downloaded 346477 times over the past 8 days and the reaction and activity on both issues combined is pretty far from that.

**Closed** 2021-06-03 21:32 UTC
Labels: P3, comp: docs-infra

**Comment by rafa-as** [comment] 2021-06-04 07:41
@alan-agius4 thank you for your explanation.

I have a question about your proposals to get rid the FOUC 100%.

> To get rid of any possibility of having FOUC, there are a couple of approaches.
> 
> * Use to SSR or Pre-rendering
> * Disable critical inlining of CSS which causes a performance overhead since the CSS will be render blocking.

We are using SSR but we are facing the FOUC, maybe we have something wrong configured?

We already have checked the `inlineCriticalCss` on the SSR (server.ts) and the initial flickering disappears but when you navigate through the app the CSS is broken.

**Comment by alan-agius4** [comment] 2021-06-04 09:44
> We are using SSR but we are facing the FOUC, maybe we have something wrong configured? 

Without a reproduction it's hard to determine what is happening, you might have complex selectors which the CSS extractor is unable to handle. I suggest to check the server logs for any warnings/errors.

> We already have checked the inlineCriticalCss on the SSR (server.ts) and the FOUC disappears but when you navigate through the app the CSS is broken.

That seems unrelated to critical CSS inlining as this only effects the initial rendering and not when navigating from one route to another, but again without a reproduction it's hard to tell what is happening. As these are all assumptions.

**Comment by MarcoGlauser** [comment] 2021-06-07 16:31
@alan-agius4 Sorry if this is the wrong thread.
We have the same issue with FOUC in angular 12 SSR, which was fine with angular 11 SSR. 
We're using angular with tailwind and the styles from tailwind won't get picked up by the inlining process. This wasn't an issue before, since the .css file was loaded synchronously anyways. Is there a way to tell critters to consider the tailwind styles during the inlining process?

**Comment by alan-agius4** [comment] 2021-06-07 16:34
@MarcoGlauser, critters should parse all external CSS. Without a reproduction it’s hard to tell what is happening.

I suggest to open an issue with a minimal reproduction in https://github.com/angular/universal

**Comment by rafa-as** [comment] 2021-06-07 17:08
> > We are using SSR but we are facing the FOUC, maybe we have something wrong configured?
> 
> Without a reproduction it's hard to determine what is happening, you might have complex selectors which the CSS extractor is unable to handle. I suggest to check the server logs for any warnings/errors.
> > We already have checked the inlineCriticalCss on the SSR (server.ts) and the FOUC disappears but when you navigate through the app the CSS is broken.
> 
> That seems unrelated to critical CSS inlining as this only effects the initial rendering and not when navigating from one route to another, but again without a reproduction it's hard to tell what is happening. As these are all assumptions.

Sorry @alan-agius4, I know that without a reproduction it's hard to determine it. I just want to know how it's supposed to be configured to make it work properly (because the docs are not very clear about it) or if we should create an issue with a minimal reproduction because is a bug in the Angular Team side that should be checked.

We have checked these three cases:

1. FOUC
- inlineCritical (angular.json) : true

2. NO FOUC but strange behaviour with lost styles when navigating
- inlineCritical (angular.json) : true
- inlineCriticalCss (server.ts) : true

3. No FOUC
- inlineCritical (angular.json) : false
- inlineCriticalCss (server.ts) : true


Maybe two issues should be created, one to solve the main issue (if you can confirm that is it) and another one to put this information about inlineCritical and SSR in the docs. Anyway, I wait for your confirmation.

Thanks!!

**Comment by alan-agius4** [comment] 2021-06-07 17:27
@rafa-as, all those settings should  at the end result in the same behaviour. This is because the critical css inlining on the server super-seeds thats of the client app.

Make sure that you are using @nguniversal packages v12, and If you are seeing anything different please file an issue with a minimal reproduction in the universal repo.

The SSR docs in general are quite minimal and don’t explain any of the server related bootstrapping options, so probably an entire section would need to be added in this case. Feel free to open an issue for this in this repo.

**Comment by MarcoGlauser** [comment] 2021-06-07 17:37
I found the culprit while trying to reproduce the issue. The option "inlineStyleLanguage" was not set during the 11->12 upgrade, despite [this pull request](https://github.com/angular/angular-cli/pull/20542). I'll investigate if I can reproduce the issue.
