### ISSUE TITLE
Confusion about Jasmine.done vs async and fakeAsync

### ISSUE THREAD

**Issue by willwsharp** [angular/angular#20711] opened 2017-11-30 14:43 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

In the Jasmine.done section of the Testing guide (found here https://angular.io/guide/testing#jasminedone), the last two sentences are very confusing.  They mention that although using `done` is more cumbersome, sometimes it is required when "testing code that involves the `intervalTimer`" because `async` and `fakeAsync` can't be called when testing that code.

## Expected behavior
It should be clear when to we have to use `done` and when we can use `async` or `fakeAsync`.
## Minimal reproduction of the problem with instructions

Go here: https://angular.io/guide/testing#jasminedone
Look at the last two sentences

## What is the motivation / use case for changing the behavior?

The documentation seems very confusing to me.  I tried looking up what `intervalTimer` was, considering it was formatted to look like a reference to something specific.  I could find nothing about it in any of the Angular docs or the RxJS docs.  Additionally, _why_ can't `async` or `fakeAsync` be used with `intervalTimer`?

## Environment

<pre><code>
Angular version: 5.0.3

**Comment by gkalpak** [comment] 2017-11-30 15:04
I assume `intervalTimer` is `setInterval` :grin:
And that is a problem for `async`/`fakeAsync`, because there is always going to be a macrotask scheduled.

This should be more clear in the guide.

BTW, since jasmine 2.8 (iirc), you can also return a promise (or use `async`/`await`) instead of using `done`. It would be nice to mention that as well in the guide.

**Comment by willwsharp** [comment] 2017-11-30 15:07
@gkalpak ah so perhaps `intervalTimer` should be changed to `setInterval` then.  Oh so the problem would be that `async/fakeAsync` would never finish because they wait for all promises to be resolved, correct?

**Comment by gkalpak** [comment] 2017-11-30 15:18
I haven't tried it, but off the top of my head I think `async` would never finish and `fakeAsync` (which runs synchronously) would throw an error because there would be tasks scheduled after the test is finished. Needs to be verified :grin:

**Comment by willwsharp** [comment] 2017-11-30 16:24
Ah okay that makes sense; thank you.

**Comment by kapunahelewong** [comment] 2018-02-23 17:32
@jenniferfell This one will need to be looked at more closely to see how the docs are impacted.

**Comment by JiaLiPassion** [comment] 2018-02-23 19:26
I would like to add document and samples to describe the relationship of `jasmine.done`, `fakeAsync`, and `async`, currently I am making document about some new feature of `async` and `fakeAsync` which will be released in next version of `zone.js`.

**Comment by vthinkxie** [comment] 2018-02-26 10:15
`discardPeriodicTasks` will be helpful when testing `intervalTimer` under `fakeAsync` mode

**Comment by JiaLiPassion** [comment] 2018-04-04 15:30
I created a PR to add more detail about `fakeAsync/async/done`
1. we can call `setInterval` in `async()`, as long as we call `clearInterval()`
2. we can call `setInterval` in `fakeAsync()`, as long as we call `clearInterval()` or `discardPeriodTasks()`.
3. `rxjs scheduler` such as `delay` also work in `async()`, sample can be found here, 
https://github.com/angular/angular/pull/23117/files#diff-b760eaece7529077c676429c3e28b43bR121
4. we can't pass `done` to `fakeAsync()` or `async()`, it will be `undefined`.

**Comment by giniedp** [comment] 2018-05-31 11:55
I am wondering what the difference between async and async/await would be.

Sometimes i come across async tests where the `whenStable` function is not run, for example

```ts
it ("is a test", async(() => {
  fixture.detectChanges()
  fixtrue.whenStable().then(() => {
    expect(true).toBe(false)
  })
}))
```

I can not figure out the reason of this, but i can work against that by using async/await

```ts
it ("is a test", async (done) => {
  fixture.detectChanges()
  await fixtrue.whenStable()
  expect(true).toBe(false)
  done()
})
```

Now one difference is very obvious. I have to use `done` and i enable a linear code style. But still i am wondering if that might have other impact on the test execution.

**Comment by JiaLiPassion** [comment] 2018-06-05 16:16
@giniedp , the `async test` and `async/await` is totally different stuff.
`async` from `angular` is a test helper method to help you `auto done` when testing async function.
`async/await` is an ES7 feature.

```javascript
it ("is a test", async(() => {
  fixture.detectChanges()
  fixtrue.whenStable().then(() => {
    expect(true).toBe(false)
  })
}))
```

this will not work because there is not `async` operation in your test.

**Comment by giniedp** [comment] 2018-06-05 19:18
@JiaLiPassion its clear to me that both are different concepts. I just cant figure out why sometimes my `whenStable().then` is simply not running but the test is fine when i use `async/await`.

`fixture.detectChanges()` usually does trigger an async operation within my business logic (async form validation). I admit that some cases might not trigger an async operation which i will check now. But i'd expect `fixtrue.whenStable()` to resolve and run the expectation body even when there are no async operations. Otherwise this very misleading and gives false positive test results in certain cases.

Angular testing guide says:

> The fixture.whenStable() returns a promise that resolves when the JavaScript engine's task queue becomes empty

If what you say is correct then "**becomes empty**" is a very crucial bit of information there.

**Comment by giniedp** [comment] 2018-06-05 19:51
I did a quick test and the `async` actually does resolve even if there are no async operations in the test. https://stackblitz.com/edit/angular-async-testing-rwasxa

**Comment by JiaLiPassion** [comment] 2018-06-08 00:41
@giniedp, yes, you are right, my mistake, `fixture.whenStable` is a `promise`, if `angular` already `stable`, it will just a `resolved promise`.

so back to your first question, 

```ts
it ("is a test", async(() => {
  fixture.detectChanges()
  fixtrue.whenStable().then(() => {
    expect(true).toBe(false)
  })
}))
```

this should work if everything is `stable`. Could you post the reproduce repo that `whenStable.then` is not called?

**Comment by giniedp** [comment] 2018-06-08 10:42
the project is closed source but i am trying to isolate and replicate the test scenario in a clean environment so i can post it on stackblitz. No luck so far.

**Comment by giniedp** [comment] 2018-06-08 13:36
i can not yet reproduce it on stackblitz but i think i'm hitting somewhere.

The test i am looking at has a setup like this

```ts
beforeEach(async(() => {
  configureTestBed();
}))

beforeEach(() => { // this one has no async wrapper
  fixture.detectChanges(); 
  // this triggers ngOnInit 
  //   -> component initializes state
  //   -> state feeds a directive
  //   -> directive calls setTimeout(..., 0)
})

it ('is a test', async(() => {
  input.value = "value"
  input.dispatchEvent(new Event("input"))
  fixture.detectChanges()
  fixture.whenStable().then(() => {
    // test block in question
  })
}))
```

Since the second `beforeEach` is missing an `async` wrapper it probably leaks the async operations into the global zone. The `whenStable` block does actually run but it does after the test.  As soon as that second `beforeEach` gets an `async` wrapper the test suite behaves as it should.

Now as i said i can not reproduce it in a clean environment with a shallow setup but i'm working on it.

**Comment by JiaLiPassion** [comment] 2018-06-08 14:38
@giniedp , sure , thank you for the update.

**Comment by giniedp** [comment] 2019-03-13 20:51
since i owe this thread a reproduction example and still could not deliver one i wanted at least tell that we fixed our issues by consistently using the `async` function wherever `fixture.detectChanges` is used. Most of the time it was forgotten in a beforeEach block

```ts
beforeEach(async(() => {
  fixture = TestBed.createComponent(MyComponent)
  fixture.detectChanges()
}))
```

I am still confused about the behaviour of `whenStable` in `async` tests. I think the testing guide does not explain it enough so i created this test
https://stackblitz.com/edit/angular-async-test-behavior

My observation is

1.  although `fixture.isStable()` returns `true` a call to `fixture.whenStable()` is still needed to resolve a queued promise
2. `fixture.whenStable()` can not be used with setTimeout macrotasks
3. `fixture.whenStable()` does not drain the microtask queue.

Last point is interesting since a single call to `fixture.whenStable()` can resolve multiple microtasks when they have been queued in the same task

```ts
Promise.resolve().then(() => {
  // gets resolved on first whenStable()
})
Promise.resolve().then(() => {
  // gets resolved on first whenStable()
})
```

But it can not drain a queue of microtasks

```ts
Promise.resolve()
.then(() => {
  // gets resolved on first whenStable()
})
.then(() => {
  // requires a second call to whenStable()
})
```

Most of the time i tend to use `async`/`whenStable` when testing my core components. Since these have no dependencies other than @angular/core and @angular/common the tests are usually straight forward. This changes when writing tests for high level components. From high level perspective one can not know whether a dependency uses micro or macrotasks and how deep the task queue may be. So using `async`/`whenStable` is not suitable here. Please correct me if i am wrong.

The guide says:

> The fixture.whenStable() returns a promise that resolves when the JavaScript engine's task queue becomes empty

This is vague. I would like to know the exact conditions and which *task queue* exactly.

> The fakeAsync() utility function has a few limitations. In particular, it won't work if the test body makes an XHR call.

What are the other limitations? What else can be done with `async` but not with `fakeAsync`

I wish there would be more in depth guide or documentation about `async`, `whenStable` and `isStable`. There are many blog articles out there. But they often tend to be shallow.

**Comment by kapunahelewong** [comment] 2019-05-31 11:13
Closing since PR was merged. @willwsharp if you have any more questions, please feel free to re-open or tag me. Thanks!

**Closed by kapunahelewong** 2019-05-31 11:13 UTC
Labels: comp: docs, comp: testing, freq2: medium, severity2: inconvenient, state: community, state: has PR, subtype: docs-clarification, type: feature
