### ISSUE TITLE
Singleton Services with Standalone Component

### ISSUE THREAD

**Issue by antonio-spinelli** [angular/angular#48242] opened 2022-11-27 10:37 UTC
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

*WARNING: I'm not sure if this is the correct behaviour of a standalone component or not.*

If you import a module with a service, that should be a singleton for your app, in a standalone component it will create a new instance of that service. With the "module way" component this doen't happens, but only when you use a standalone component and it's not clear why.
Same results while boostrap standalone component or module
Using `providedIn: 'root'` in the service decorator doesn't make any difference.
With the service locator pattern it will work, but i don't think this should be the right approach.
If you don't import the module with the service it will work, but why?
If the standalone without import is in the same page with the one with import, it will use the service from the "brother" and not from app, why?

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-rrptke

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Tested with angular 14, 14.2 and 15.
```

### Anything else?

Please be nice if it's not a bug and I just didn't understood how standalone component works, but this is a new thing and there isn't a guide about that behaviour with services.

**Comment by JeanMeche** [comment] 2022-11-28 12:53
You're creating a new instance by providing your `CounterService` in the `CounterModule`. 
Remove it and let `{provideIn: 'root'}` do its job : making the same instance be available everywhere.

**Comment by atscott** [comment] 2022-11-28 15:40
This behavior is not unique to standalone components. As @JeanMeche said, your service should not be listed as a provider in `CounterModule`. Doing that and then importing the module in your component is the equivalent to listing the service in the `providers` of the component (example: https://stackblitz.com/edit/angular-ivy-h2fwrj). Closing as working as intended.

**Closed by atscott** 2022-11-28 15:40 UTC

**Comment by antonio-spinelli** [comment] 2022-11-28 16:13
I understood how to make it work, but why the behaviour change from module way to the standalone way. It doesn't matter how many times you import a module with a provider (not provided in root or yes), it still inject the same instance. But in standalone component it will create a new instance, and for brother component it will change the instance even if the brother doesn't import the module. I don't understand that thing. Are you sure it is ok?
