### ISSUE TITLE
Service worker cached empty chunk.js files

### ISSUE THREAD

**Issue by k-schneider** [angular/angular#23502] opened 2018-04-23 02:09 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Service worker cached a couple empty chunk js files.  It seems to happen intermittently on my mobile device (Galaxy S6) with Chrome v65. The app has 10~ lazy-loaded modules and a pretty standard service worker config. This may have something to do with a window reload occurring during an update but I can't confirm.

The error being thrown by the application when navigating to one of the affected lazy loaded modules is: `Error: Loading chunk X failed.`  In this case X was both `2` and `8`.  The network tab shows the request for the chunk being handled by the service worker but the response is empty. Stranger is that cache storage shows the cached chunks with a proper content length but when viewed they are empty.  I can view the contents of other chunks without issue.

The same update activated fine on my desktop version of Chrome.

I also noticed that in "Cache Storage" there were two entries with the pattern:

```
ngsw:<id>:assets:app:cache
```

One of them had 2 items for the 2 failing chunks and they were empty.  The other had all the assets I'd expect including the 2 failing chunks which were empty.  All other files had correct content.

Ultimately I manually removed the empty cache entries and reloaded the application and it worked as expected.

## Expected behavior

I'd like to be sure that the application will update correctly and that all files defined in the asset group will be cached accurately.

## Minimal reproduction of the problem with instructions

Unable to provide as this seems to happen intermittently.

## What is the motivation / use case for changing the behavior?

If the application ends up in this state an end user has no way to manage through it.  The app would likely remain in a broken state until the next update activated.

## Environment

<pre><code>
Angular version: 5.2.10

Browser:
- [ ] Chrome (desktop) version XX
- [X] Chrome (Android) version 65
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by gkalpak** [comment] 2018-04-24 19:49
Was this an one-of thing, or were you able to reproduce it several times (e.g. after many attempts)?
I am not sure if we can do anything about it without a way to reproduce it somehow :/

**Comment by k-schneider** [comment] 2018-04-24 19:57
I'd seen the issue once before but I was already in the process of pushing another update and when it landed it updated without issue.  I haven't seen a way to reproduce this reliably.  I've pushed several updates since this failure without incident.

**Comment by gkalpak** [comment] 2018-04-24 20:13
Hm...unfortunately, I can't think of any way to investigate this further. It could even be a browser, server, or proxy issue 😕

**Comment by gkalpak** [comment] 2018-09-17 10:59
Closing this, since there doesn't seem to be a way to reproduce it and it does sound like a browser bug (which has hopefully been fixed).
Happy to investigate if there is a way to reproduce it or see the issue live.

**Closed by gkalpak** 2018-09-17 10:59 UTC
Labels: comp: service-worker, freq1: low, severity3: broken, state: Need repro, type: bug/fix
