### ISSUE TITLE
Update Angular 12 versions support in angular.io

### ISSUE THREAD

**Issue by pavankjadda** [angular/angular#42211] opened 2021-05-21 05:35 UTC
# Docs or angular.io Bug Report
angular.io

### Description
Angular 12 release and LTS schedule is not updated in https://angular.io/guide/releases#support-policy-and-schedule

## Minimal Reproduction
See the current schedule here https://angular.io/guide/releases#support-policy-and-schedule

### What's the affected URL?**
https://angular.io/guide/releases#support-policy-and-schedule

## Screenshot
<img width="879" alt="Screen Shot 2021-05-21 at 1 34 25 AM" src="https://user-images.githubusercontent.com/17564080/119087175-b7a23b80-b9d4-11eb-82c9-6d5457298f3e.png">

**Comment by gkalpak** [comment] 2021-05-21 06:10
Thx for bringing this up, @pavankjadda :+1:
This is a duplicate of #42111 and will be fix by #42124.

**Closed by gkalpak** 2021-05-21 06:10 UTC
