### ISSUE TITLE
Zone.js globalZoneAwareCallback on click page or resize windows 

### ISSUE THREAD

**Issue by Toso82** [angular/angular#37415] opened 2020-06-03 07:38 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package zone.js

### Is this a regression?

 Yes I don't know i find now.

### Description

When resize windows or click on html page give me extra chenges.  I fund  Zone.js invoke globalZoneAwareCallback.  I find there is a problem on @angular/material tooltip and remove extra events but not this.

## 🔬 Minimal Reproduction

 
This is a strange problem difficult to reproduct.  i want a suggestion how find what is problem it is possible.  

## 🔥 Exception or Error
<pre><code>

push../src/app/app.component.ts.AppComponent.getValoreMercatoNumero (app.component.ts:1180)
push../src/app/app.component.ts.AppComponent.ValorePerizia (app.component.ts:1638)
AppComponent_mat_card_181_Template (app.componentLight.html:743)
executeTemplate (core.js:7747)
refreshView (core.js:7616)
refreshEmbeddedViews (core.js:8716)
refreshView (core.js:7640)
refreshComponent (core.js:8762)
refreshChildComponents (core.js:7409)
refreshView (core.js:7666)
refreshComponent (core.js:8762)
refreshChildComponents (core.js:7409)
refreshView (core.js:7666)
renderComponentOrTemplate (core.js:7730)
tickRootContext (core.js:8934)
detectChangesInRootView (core.js:8959)
push../node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js.RootViewRef.detectChanges (core.js:10360)
push../node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js.ApplicationRef.tick (core.js:29070)
(anonymous) (core.js:28954)
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:386)
onInvoke (core.js:28134)
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:385)
push../node_modules/zone.js/dist/zone.js.Zone.run (zone.js:143)
push../node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js.NgZone.run (core.js:28029)
next (core.js:28953)
schedulerFn (core.js:25506)
push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.__tryOrUnsub (Subscriber.js:192)
push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.next (Subscriber.js:130)
push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber._next (Subscriber.js:76)
push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next (Subscriber.js:53)
push../node_modules/rxjs/_esm5/internal/Subject.js.Subject.next (Subject.js:47)
push../node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js.EventEmitter.emit (core.js:25488)
checkStable (core.js:28084)
onLeave (core.js:28180)
onInvokeTask (core.js:28128)
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:420)
push../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:188)
push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask (zone.js:503)
invokeTask (zone.js:1671)
globalZoneAwareCallback (zone.js:1697)
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.1.7
Node: 14.2.0
OS: win32 x64

Angular: 9.1.9
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.901.7
@angular-devkit/build-angular      0.901.7
@angular-devkit/build-optimizer    0.901.7
@angular-devkit/build-webpack      0.901.7
@angular-devkit/core               9.1.7
@angular-devkit/schematics         9.1.7
@angular/cdk                       9.2.4
@angular/cli                       9.1.7
@angular/flex-layout               9.0.0-beta.31
@angular/material                  9.2.4
@angular/material-moment-adapter   9.2.4
@ngtools/webpack                   9.1.7
@schematics/angular                9.1.7
@schematics/update                 0.901.7
rxjs                               6.5.5
typescript                         3.8.3
webpack                            4.42.0
</code></pre>

**Anything else relevant?**

Chrome and Firefox

**Comment by JiaLiPassion** [comment] 2020-06-27 13:37
Any event listeners will become a `ZoneAwareGlobalCallback`, so I am not sure what is the issue, you mean there are `extra change detections` triggered? So you don't want `resize event handler` trigger `change detection`?

**Comment by Toso82** [comment] 2020-06-27 18:51
@JiaLiPassion Yes there is extra change detections and i don't know why.  I add do the same with latest version.  I think there is bug. I have console log write when resize when click message. I don't find why

**Comment by JiaLiPassion** [comment] 2020-06-27 21:44
@Toso82, so `extra` change detection means there are 2 change detections for the resize event? Could you post a reproduce repo?

**Comment by Toso82** [comment] 2020-06-29 06:20
@JiaLiPassion Maybe I don't explained well. It is a big web pages so it is difficult to create example to reproduce.  I mean that i don't have resize event detection in pages but continue to fire this events.  Also when click page there is a change and a function continue to invoke and this is strange there is not data change to create this.  I try to debug but i see just this

**Comment by Toso82** [comment] 2020-06-29 11:25
@JiaLiPassion  Ok i understand how I can remove and could be a solution. How can find how registry this events?

**Comment by Toso82** [comment] 2020-07-08 07:48
@JiaLiPassion  Sorry but I don't know how to fix there is possibility to know who registry this events ?  I try to remove all global listener on crome but do the same.

**Comment by JiaLiPassion** [comment] 2020-07-08 12:21
@Toso82 , could you post a reproduce repo? I would like to help to debug it.

**Comment by Toso82** [comment] 2020-07-08 12:35
@JiaLiPassion  This is a big difficult to isolate and reproduce i must share all my project to see or portion to this.  This is the problem. But i can try to do example.  If it is is some soggestion to find problem where i can search how events register. Thanks

**Comment by JiaLiPassion** [comment] 2020-07-08 21:24
@Toso82, you can add an `conditional breakpoint` in the chrome devtools, and the location is `addEventListener` in `zone-evergreen.js`, the condition will be `eventName === 'resize'`, then you can find out who is adding the `resize` event listener.

**Comment by Toso82** [comment] 2020-07-09 12:09
@JiaLiPassion Sorry but i don't have `zone-evergreen.js` maybe `zone.js`

**Comment by JiaLiPassion** [comment] 2020-07-09 22:14
@Toso82 , yeah, if you are running the application in legacy browser, it will be `zone.js`.

**Comment by Toso82** [comment] 2020-07-22 07:23
@JiaLiPassion  Hi i think all well i put brackpoint as you suggest. 

```js
if (typeof newValue === 'function') {
                target[eventNameSymbol] = newValue;
                target.addEventListener(eventName, wrapFn, false);
            }
            else {
                target[eventNameSymbol] = null;
            }
```
In meanwhile i update also angular and all to latest version. But i don't have any resize here. I inspect the problem and i find i have some eventname:

-  readystatechange
- close
- message
- error

**Comment by JiaLiPassion** [comment] 2020-07-22 12:02
@Toso82 , it is hard to tell what is the problem, still I need the reproduce repo to debug.

**Comment by Toso82** [comment] 2020-07-24 12:55
@JiaLiPassion Hi. I can replicate the problem:  

https://github.com/Toso82/Ag10Test

Do maybe the same as you explained. 

There is a console.log('Change') invoke:

- When resize
- When click

Not when change value pass on it.

**Comment by Toso82** [comment] 2020-08-04 10:06
@JiaLiPassion Hi All ok ? Have you have time to analize my example

**Comment by JiaLiPassion** [comment] 2020-08-05 13:55
@Toso82 , sure, I checked your example, the `resize` event handler is added by `Angular Components`, I will confirm this is the intent behavior or not. Thanks for the reproduce example.

**Comment by JiaLiPassion** [comment] 2020-08-07 18:42
@Toso82 , I just confirmed this issue has been fixed here https://github.com/angular/components/issues/18471, so please wait for the next `@angular/cdk` release.

**Comment by Toso82** [comment] 2020-08-11 07:28
@JiaLiPassion I update my project demo (https://github.com/Toso82/Ag10Test) as lates `@angular/cdk `and `@angular/material`.  The resize event seams to work now but, I continue to have extra event on:

-  When open nav-drawer
-  Just enter in input 
-  Or write in first input there isn't reference on function 

I think there is another problem

**Comment by JiaLiPassion** [comment] 2020-08-12 03:27
@Toso82, for these 3 cases.

> 
> When open nav-drawer

This one maybe an issue, I will check it.

> Just enter in input
> Or write in first input there isn't reference on function

When you update the input, it should trigger change detection, so what do you mean extra event in these 2 cases?

**Comment by Toso82** [comment] 2020-08-12 06:27
@JiaLiPassion Yes i mean extra event. There is not reference so it is strange to trigger

**Comment by JiaLiPassion** [comment] 2020-08-12 06:38
@Toso82 , the function is triggered since it is defined in the `template`, change detection will try to check everything in the template by default, so when you type something in the input, the `function` will be triggered whether it is referenced or not, this is not an issue.

**Comment by JiaLiPassion** [comment] 2020-08-12 23:09
@Toso82 , the 1st issue when you click sidenav, this is an known issue, https://github.com/angular/components/pull/15076, please wait for the later fix.

**Comment by jelbourn** [comment] 2020-11-04 17:45
Closing this since it doesn't appear to be related to Angular itself. As a side note, there are generally no assurances around how many change detections may or may not occur in an application.

**Closed by jelbourn** 2020-11-04 17:45 UTC
Labels: comp: zones, state: needs more investigation

**Comment by Toso82** [comment] 2020-11-04 18:32
@jelbourn I'm not so sure of that I must to try with latest update but I  have this problem with angular material

**Comment by Toso82** [comment] 2020-11-05 12:51
@jelbourn  I update my example and do the same https://github.com/Toso82/Ag10Test
