### ISSUE TITLE
 Command section in Angular.dev shows Page Not Found 

### ISSUE THREAD

**Issue by borjamrd** [angular/angular#53216] opened 2023-11-28 03:30 UTC
### Describe the problem that you experienced

Page Not Found appears on angular.dev

### Enter the URL of the topic with the problem

https://angular.dev/cli/commands

**Comment by JoostK** [comment] 2023-11-28 04:53
Thanks for the report, closing as duplicate of #52549.

**Closed by JoostK** 2023-11-28 04:53 UTC
