### ISSUE TITLE
Link is incorrect on a page of the documentation

### ISSUE THREAD

**Issue by Remid12** [angular/angular#52701] opened 2023-11-08 21:30 UTC
### Describe the problem that you experienced

On the main page of "Http request" documentation (https://angular.dev/guide/http/making-requests) there is an incorrect link at the section "What's next". The link on the button "Making HTTP requests" should be:
"https://angular.dev/guide/http/making-requests" and not "https://angular.dev/guide/http/making-requets" (there is a "s" missing).

### Enter the URL of the topic with the problem

https://angular.dev/guide/http/making-requests

**Comment by JoostK** [comment] 2023-11-08 21:53
Thanks for the report, this is a duplicate of #52702.

**Closed by JoostK** 2023-11-08 21:53 UTC
