### ISSUE TITLE
HostBinding('class') should

### ISSUE THREAD

**Issue by arturhun** [angular/angular#29188] opened 2019-03-08 12:58 UTC
### Description

When using the following code (assume it is code for 'my-component'):

```ts
@HostBinding('class') 
@Input() type: string;
```

there should be an option to **append** the class to existing class list rather than **replace** all existing classes. The `HostBindingDecorator` could honor all other existing classes that might have been set in the template for other purposes.

This way `@HostBinding` would allow for what this syntax `[ngClass]="[class1, class2]"` allows - ie. appending classes of unknown names.

### Current and desired behavior

Given the above component input, and this markup:

`<my-component class="something" type="type1"></my-component>`

the template will be rendered as follows:

`<my-component class="type1"></my-component>`

while the desired result is:

`<my-component class="something type1"></my-component>`

### Workaround

I am not saying that there is no workaround for the above, but it requires injecting `Renderer` and `ElementRef` along with the code to handle the classes. Also, given that for some reason `Renderer` does not have a handy method `toggleClass(classname, condition)`, that code becomes even more verbose.

### Suggested syntax

In order to assure backwards compatibility (for users who have already used the current behavior to purposely override all existing classes), `HostBindingDecorator` could accept a config parameter, something like: `@HostBinding('class', {append: true})` to explicitly specify new behavior with `true`.

**Comment by pkozlowski-opensource** [comment] 2019-03-08 13:01
* it is a duplicate of #7289
* it is already fixed in the ivy version of Angular, will be rolled out in Angular 9

Closing as a duplicate / already fixed.

**Closed by pkozlowski-opensource** 2019-03-08 13:01 UTC
