### ISSUE TITLE
Declared in 2 Modules - Cannot compose new modules

### ISSUE THREAD

**Issue by intellix** [angular/angular#21131] opened 2017-12-21 13:01 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Within a **@nrwl/nx** monorepository, you have 2 apps that consume modules to create a whole application. One of the consumed modules contains 3 components for layout: **Header**, **Sidebar**, **Footer**

**App1** uses everything out of the box and everyones happy.
**App2** has a different **Footer** that requires replacing the component entirely, but would like to re-use **Header** and **Sidebar** from **LayoutModule** as nothing changed. 

JIT works fine, but AOT gives the following error:
```
ERROR in :
Type FooterComponent in /Site/libs/layout/src/footer/footer.component.ts is part of the declarations of 2 modules: 
  LayoutModule in /Site/apps/myapp/src/app/layout/layout.module.ts
  and 
  LayoutModule in /Site/libs/layout/src/layout.module.ts! 

Please consider moving FooterComponent in /Site/libs/layout/src/footer/footer.component.ts to a higher module that imports LayoutModule
```

## Expected behavior

Both JIT and AOT would compile without any errors. I'm not even using or referencing the original LayoutModule so it shouldn't give an error.

## Minimal reproduction of the problem with instructions

Repo: https://github.com/intellix/nx-cli
```
ng serve --app green // works
ng serve --app green --aot // does not
```

## What is the motivation / use case for changing the behavior?

Modules are a composition of declared components and can be imported entirely from a lib. If you need to replace 1 component, it's currently impossible if using AOT. The only way around it is to only ever have 1 component per Module, in which case I would have hundreds for an application.

We want to be able to create applications using modules of components from libs, but be able to replace components when we need to change them. Currently you have to throw away the whole module. I'd expect something like this to work if I don't even use the previous module:

MyLibs/LayoutModule:
```ts
import { HeaderComponent } from './header/header.component';
import { SidebarComponent } from './sidebar/sidebar.component';
import { FooterComponent } from './footer/footer.component';

@NgModule({ declarations: [ HeaderComponent, SidebarComponent, FooterComponent ] })
export class LayoutModule { }
```

App1 (wants to use out of the box):
```ts
import { LayoutModule } from '@mylibs/layout';

@NgModule({ imports: [ LayoutModule ] })
export class AppModule { }
```

App2 (wants to replace Footer):
```ts
import { HeaderComponent, SidebarComponent } from '@mylibs/layout';
import { FooterComponent } from './footer.component';

@NgModule({ declarations: [ HeaderComponent, SidebarComponent, FooterComponent ] })
export class MyLayoutModule { }

@NgModule({ imports: [ MyLayoutModule ] })
export class AppModule { }
```

## Environment

<pre><code>
Angular version: 5.1.1

 
For Tooling issues:
- Node version: XX  v8.9.1
- Platform:  Mac

Others:

</code></pre>
I think either ngc needs to either only give errors based on code used or ease up in this case. Even a warning would be nice

**Comment by Xesenix** [comment] 2017-12-21 14:51
Discussion related to this feature request https://github.com/angular/angular/issues/13590

**Comment by intellix** [comment] 2017-12-21 17:12
Aye, quite related. That's one of the other issues we're having. We can have a folder of components without modules to be included as you wish, but then you get the error that they're not declared in a module :(

**Comment by sarunint** [comment] 2017-12-21 23:18
I would recommend creating a module and import this module into each app respectively.

**Comment by mhevery** [comment] 2018-01-02 23:14
Each component can only be part of a single Module. This is by design. We can't verify this in JIT, but can in AOT, which is why it passes it one but not the other. As pointed out one should just break it out into separate module. 

Closing as working as intended. (We do have plans to solve this in a different way, but it will take longer to get there)

**Closed by mhevery** 2018-01-02 23:14 UTC
Labels: comp: core & compiler

**Comment by intellix** [comment] 2018-01-03 12:26
I'm sorry but it seems that this issue was only skim-read and not quite understood. 

Each component can only be part of a single **used/referenced** Module, but AOT should not be throwing errors for modules that aren't even referenced. 

It's throwing application context errors when it doesn't understand applications (it only reads files found via TS resolution).

A workaround would be to at least disable the error until AOT only follows referenced code through  entrypoints or at least allow a configurable for disabling it so mono-repository users can continue to use AOT. More of these issues are going to crop up as people use https://nrwl.io/nx

**Comment by intellix** [comment] 2018-01-03 13:15
I've created a diagram to show what I'm talking about that I hope explains it better:

https://drive.google.com/file/d/1_8vpoh5o15-ZHLbKAEc6GygXzrc4gzw6/view?usp=sharing
<img width="564" alt="mono-repository-diagram" src="https://user-images.githubusercontent.com/1162531/34521856-e565f436-f087-11e7-8719-35fdad0a15df.png">

We're essentially a white-labelling product company. If you've been to car insurance websites, you'll notice they're all the same website but are branded/coloured differently. Sometimes clients will request for something slightly different so you want to re-use as much as possible.

**Comment by mlc-mlapis** [comment] 2018-01-03 13:44
@intellix ... to understand ... your `lib` is not a real lib package and you don't use `tsconfig.json` to set-up entry points for AOT compilations?

**Comment by intellix** [comment] 2018-01-03 14:40
We're using nx-cli which has a folder for apps and folder for libs. Each app has a tsconfig defining a path for libs. 
Each lib has an index.ts which exports the module and components within it.

The problem is that because the lib index.ts contains:
```ts
export * from './src/product.module';
```

AOT finds it, despite not being imported within an NgModule

**Comment by mlc-mlapis** [comment] 2018-01-03 15:01
@intellix ... oh ok, so the lib is not installed as a standard lib in `node_modules` ... because this should work. We use `ng-packagr` for building libs so that's why ask ... an app uses custom libs as any other lib from npmjs.com or a private npm server.
