### ISSUE TITLE
Symbol component declared in component.d.ts is not exported from module

### ISSUE THREAD

**Issue by KennethUdoh** [angular/angular#42910] opened 2021-07-21 18:20 UTC
Hi,

I created an Angular library and used it in an Angular application both created in Visual Studio, and I get errors similar to the ones in the link below(Errors.txt) when I build the application, then I upgraded the cli to the latest version in Visual Studio but I still get the same errors. I created a new library and a new application both created using the CLI Command(without Visual Studio), without changing anything in the projects  and using the latest CLI, but  I still get the same errors([Errors.txt](https://github.com/angular/angular/files/6857874/Errors.txt)) when I build the applications. Regardless of where I created the libraries I can't seem to build any of my applications when I reference them. 

The Angular version(Both globally and locally) is the same across all the projects, see below.

![Version](https://user-images.githubusercontent.com/25224132/126537893-f1cd81ec-d425-4211-be1d-0bd2560feb90.PNG)

**Comment by JoostK** [comment] 2021-07-21 18:30
This is very likely a duplicate of #42810. It describes a potential workaround:

> You can workaround this issue by setting "preserveSymlinks": true as a builder option in angular.json.

**Comment by KennethUdoh** [comment] 2021-07-22 10:03
Hi,

I have added preserveSymlinks in the Angular.json([angular.json.txt](https://github.com/angular/angular/files/6861432/angular.json.txt)) file in the application, but the issue still persists. Here are the errors([Errors.txt](https://github.com/angular/angular/files/6861394/Errors.txt)). The public-api.ts([public-api.ts.txt](https://github.com/angular/angular/files/6861452/public-api.ts.txt))
 file in the library was auto generated when I created the project and I have not changed anyhting.
 
Here is the Environment
![Version](https://user-images.githubusercontent.com/25224132/126618962-b576de33-8c17-46cf-8284-7b2df4a5f225.PNG)

**Comment by JoostK** [comment] 2021-07-22 10:06
I'm afraid we'd need a reproduction in that case to be able to tell if #42879 addresses the issue.

**Comment by KennethUdoh** [comment] 2021-07-22 10:50
> I'm afraid we'd need a reproduction in that case to be able to tell if #42879 addresses the issue.

What should I do from my side? do you want copies of the projects? I created both projects with the default setup other than just referencing the library in the app.

**Comment by JoostK** [comment] 2021-07-22 10:58
A Github repo would be best.

**Comment by KennethUdoh** [comment] 2021-07-22 13:18
Hi,
Please find the code here(https://github.com/KennethUdoh/Kenneth-Udoh/blob/master/AngularIssue.zip).

**Comment by ocombe** [comment] 2021-07-22 13:29
I've had the same error with the CommonModule (`Symbol CommonModule is not exported from @angular/common`), and a client of ours also got this error.
Mine was yesterday and our client's was today, so I guess we were on 12.1.2 as well. I've never had this issue before that.

**Comment by KennethUdoh** [comment] 2021-07-22 16:38
> Hi,
> Please find the code here(https://github.com/KennethUdoh/Kenneth-Udoh/blob/master/AngularIssue.zip).

Hi Joost, 
Did you get it?

**Comment by JoostK** [comment] 2021-07-22 18:27
@KennethUdoh In your repro, the `DemoApp` is incorrectly using a deep import for `DemoLibModule`:

```ts
import { DemoLibModule } from 'demo-lib/lib/demo-lib.module';
```

The Angular compiler uses the `'demo-lib/lib/demo-lib.module'` module name to import the `DemoLibComponent` component that is declared in that module. That module does not export `DemoLibComponent` though, hence the error. You have to import `DemoLibModule` from `'demo-lib'` to resolve the error.

Other than the failure to create the import, the `'demo-lib/lib/demo-lib.module'` may not actually exist in the `demo-lib` package as Angular libraries get flattened to a single file. So the deep import would also have resulted in runtime errors due to missing modules.

**Comment by KennethUdoh** [comment] 2021-07-23 11:52
> @KennethUdoh In your repro, the `DemoApp` is incorrectly using a deep import for `DemoLibModule`:
> 
> ```ts
> import { DemoLibModule } from 'demo-lib/lib/demo-lib.module';
> ```
> 
> The Angular compiler uses the `'demo-lib/lib/demo-lib.module'` module name to import the `DemoLibComponent` component that is declared in that NgModule. That JS module does not export `DemoLibComponent` though, hence the error. You have to import `DemoLibModule` from `'demo-lib'` to resolve the error.
> 
> Other than the failure to create the import, the `'demo-lib/lib/demo-lib.module'` may not actually exist in the `demo-lib` package as Angular libraries get flattened to a single file. So the deep import would also have resulted in runtime errors due to missing modules.

@JoostK 
The compiler does not throw any error indicating that there is something wrong with the module(demo-lib/lib/demo-lib.module), in fact it is the only path it allows me to use, if I specify any other path it throws an error. I am simply using everything that was auto generated by the CLI, the only code that I added was the import { DemoLibModule } from 'demo-lib/lib/demo-lib.module' in the app.module.ts of which the structure of that folder was auto generated, I just built the library, Packed and installed it in the application using npm.

The error does not say that the module does not exist, please see the error([Errors.txt](https://github.com/angular/angular/files/6868410/Errors.txt)) again. It says that the Symbol of the component was not exported from the module(demo-lib/lib/demo-lib.module).

**Comment by JoostK** [comment] 2021-07-23 12:01
Hence this was labeled as "hotlist: error messages". The import should be

```ts
import { DemoLibModule } from 'demo-lib';
```

which should work.

**Comment by KennethUdoh** [comment] 2021-07-23 12:31
@JoostK 

Sorry about that, still new to Angular. It worked.

**Comment by JoostK** [comment] 2021-07-23 12:36
No worries; I should have mentioned the correct import statement right away.

**Closed** 2021-07-24 10:08 UTC
Labels: P4, comp: compiler, hotlist: error messages
