### ISSUE TITLE
facade/promise.d.ts errors on typescript@1.8.0

### ISSUE THREAD

**Issue by rapropos** [angular/angular#6468] opened 2016-01-13 21:20 UTC
[This commit](https://github.com/Microsoft/TypeScript/commit/b811b9f94b23491f1549eb11c20e272bdb7acb3d) to TypeScript seems to have caused problems on the first line of `promise.d.ts` complaining that `Promise` cannot be exported as it is not defined in this file:

```
ERROR in [default] /path/to/project/node_modules/angular2/src/facade/promise.d.ts:1:9
Cannot re-export name that is not defined in the module.
```

**Comment by monteirocode** [comment] 2016-01-21 20:03
+1 any idea what's causing it? I had to moved back to 1.7.5

**Comment by MarkoSulamagi** [comment] 2016-01-23 00:48
+1

**Comment by JosephWoodward** [comment] 2016-01-29 00:03
I appear to be getting the same problem. It was all working fine until I upgraded.

Here's the contents of my tsconfig file if it helps:

    {
        "compilerOptions": {
        "target": "ES5",
        "module": "system",
        "moduleResolution": "node",
        "sourceMap": true,
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "removeComments": false,
        "noImplicitAny": false
    },
    "exclude": [
        "node_modules"
        ]
    }

**Comment by sicaner** [comment] 2016-01-29 06:02
I solve this problem by adding `declare var Promise: PromiseConstructor;` on the top of  `promise.d.ts`

**Comment by OClement** [comment] 2016-01-29 20:14
+1
This needs to be fixed ASAP 
Looks like that file (promise.d.ts) isn't in line with ES6 specs;
TSC 1.8 aligned themselves with those specs and it now throws that error (it wasn't in 1.7.*)

We need to use TSC 1.8 for various reasons and it is currently breaking our builds

**Comment by fripp0971** [comment] 2016-01-29 21:49
sicaner's solution worked for me!

**Comment by JosephWoodward** [comment] 2016-01-30 01:08
As it's a TypeScript compile _warning_ your Angular 2 application will still transpile and work without any problems, so for the meantime you can also ignore the error instead of editing any of Angular 2's type definition files.

**Comment by wardbell** [comment] 2016-01-30 02:21
@JosephWoodward I wish that TS compiler distinguished "real" errors from mere warnings. It doesn't. This bombs the CI process. Needs to be fixed and soon.

**Comment by ocombe** [comment] 2016-01-31 14:03
As @wardbell stated this is an error for the typescript compiler, and it exists with status 2 instead of 0, which means that if your typescript compilation is part of a publish/testing process it will fail.
I need to use TypeScript 1.7.5 until this is fixed and it's a shame because 1.8 introduces modules bundling which I need for my lib.

**Comment by marcinnajder** [comment] 2016-02-01 08:05
+1

**Comment by JosephWoodward** [comment] 2016-02-01 15:17
Thanks for the clarification @wardbell. My current project isn't being built as part of any CI pipeline so I hadn't thought of this. I agree, this does need to be fixed soon and hopefully it will be.

**Comment by alexeagle** [comment] 2016-02-01 22:18
Yes we need a typescript@next build of angular2 on travis so we keep it compile-clean.

Dupe of #6368

**Comment by Meligy** [comment] 2016-02-02 02:00
#6368 is about creating a build against typescript@next, which would definitely help identify issues like this current one, but it's not the same issue, and not the only way to investigate it as well.

Any chance of taking this issue as a request to apply the workaround mentioned in https://github.com/angular/angular/issues/6468#issuecomment-176590156 ? Seems pretty simple.

> I solve this problem by adding `declare var Promise: PromiseConstructor;` on the top of promise.d.ts

**Comment by alexeagle** [comment] 2016-02-02 02:15
okay let's keep this open to confirm it's fixed or be sure we have a typings test that prevents regressions.

**Comment by born2net** [comment] 2016-02-04 17:06
is there a workaround for this?

**Comment by born2net** [comment] 2016-02-04 17:13
+1 please fix

**Comment by maissani** [comment] 2016-02-05 18:51
Having the same issue: 
`] node_modules/angular2/src/facade/promise.d.ts(1,10): error TS2661: Cannot re-export name that is not defined in the module.`

**Comment by alexeagle** [comment] 2016-02-05 19:14
I'm working on it now - have a repro failure on travis: https://travis-ci.org/angular/angular/jobs/107134306

**Comment by playground** [comment] 2016-02-06 17:00
+1

**Comment by alexeagle** [comment] 2016-02-14 01:03
Fix is waiting to merge, in the meantime you can `npm install alexeagle/angular#8bfbe4`

**Comment by jjpeters67** [comment] 2016-02-14 12:42
npm install alexeagle/angular#8bfbe4

**Comment by jjpeters67** [comment] 2016-02-14 12:45
Movedevtool

**Closed** 2016-02-17 01:30 UTC
Labels: comp: artifacts, effort2: medium (day), P2: required, type: chore

**Comment by alexeagle** [comment] 2016-02-17 02:19
Now on master: `npm install angular/angular#2.0.0-build.a7e9bc9.js`
Hopefully it will go into a release tomorrow.

**Comment by noxan** [comment] 2016-02-17 15:23
Thanks for your work, got me rid of my last error during build - finally
all green again :)

**Comment by bourdeau** [comment] 2016-02-17 17:34
Thanks so much for the release it did the job!! :+1:

**Comment by Meligy** [comment] 2016-02-23 09:30
Um. I just got the 2.0.0-beta.7 version from NPM and it seems to have the same issue.

I used the angular-cli tool to generate a new app, and regardless of how unstable the tool may be, it got me the correct angular2 version above, but when I go to the `src` folder and run `tsc` I get:

```
~/Code/misc/sample/src (master ✘)✖✹✭ ᐅ tsc                      
../node_modules/angular2/src/facade/promise.d.ts(1,10): error TS2661: Cannot re-export name that is not defined in the module.
../node_modules/angular2/src/facade/promise.d.ts(1,10): error TS2661: Cannot re-export name that is not defined in the module.
```

The file mentioned in the error looks as follows:

```
export { Promise };
export interface PromiseCompleter<R> {
    promise: Promise<R>;
    resolve: (value?: R | PromiseLike<R>) => void;
    reject: (error?: any, stackTrace?: string) => void;
}
export declare class PromiseWrapper {
    static resolve<T>(obj: T): Promise<T>;
    static reject(obj: any, _: any): Promise<any>;
    static catchError<T>(promise: Promise<T>, onError: (error: any) => T | PromiseLike<T>): Promise<T>;
    static all(promises: any[]): Promise<any>;
    static then<T, U>(promise: Promise<T>, success: (value: T) => U | PromiseLike<U>, rejection?: (error: any, stack?: any) => U | PromiseLike<U>): Promise<U>;
    static wrap<T>(computation: () => T): Promise<T>;
    static scheduleMicrotask(computation: () => any): void;
    static isPromise(obj: any): boolean;
    static completer(): PromiseCompleter<any>;
}

```

With the original line in there,`export { Promise };`, that is breaking the compiler I guess.

**Comment by Meligy** [comment] 2016-02-23 23:59
There is also still a failure against typescript@next for beta7 !!
https://travis-ci.org/angular/angular/builds/110239034
https://travis-ci.org/angular/angular/jobs/110239044

**Comment by alexeagle** [comment] 2016-02-24 16:40
Typescript@next is 1.9 and that Travis failure is a known issue (our build
system was broken by behavior change inside tsc). Not related.

If you have a file containing export {Promise} then it's not beta.7

**Comment by afirdousi** [comment] 2016-02-25 13:37
Still facing the issue . I am on 2.0.0-beta.3.  Any workaround `that makes sense` ?

**Comment by mishoboss** [comment] 2016-02-25 13:39
Seems 2.0.0-beta.7 still has the issue.

**Comment by afirdousi** [comment] 2016-02-25 13:51
If I add 
```
declare var Promise: PromiseConstructor;
```
The error goes away at compilation but when i navigate to the app in browser it shows
```
Uncaught reflect-metadata shim is required when using class decorators
```

So I went ahead and added the following in `main.ts` where i call Angular's `bootstrap()`

```
import  "reflect-metadata"; 
```

This made the application works, at least it compiles but still it yells on the console:

```
Uncaught TypeError: Cannot assign to read only property 'length' of function Map() {
	        this._keys = [];
	        this._values = [];
	        this._cache = exports.cacheSentinel;
	    }
```

So the main view works, basic routing works but Services injected in Component are not working. For example. a simple service that returns a string/JSON/whatever. I tried consoling in service constructor, it never reaches that code so I am assuming the injectable service is never instantiated.

Anyone ?

**Comment by afirdousi** [comment] 2016-02-25 14:45
I downgraded to tsc:1.7.5 and it works great. So for now, if you want to distribute your project with package.json, make sure you don't point to typescript 1.8. tsc 1.7.5 works great with Angular 2.0.0-beta.3. 

DONT : `"typescript": "^1.7.5"`
DONT : `"typescript": "1.8"`
DO : `"typescript": "1.7.5"`

**Comment by alexeagle** [comment] 2016-02-25 16:44
TypeScript 1.8 support was introduced with beta.7

Earlier angular2 indeed requires TS 1.7

**Comment by shawn-northrop** [comment] 2016-02-25 20:33
I am getting the same error. I am confused to why this error is appearing. I have excluded `node_modules` but it appears that typescript is still looking in the node_modules?

**Comment by Meligy** [comment] 2016-02-25 23:45
@alexeagle  That's correct. I was running `npm show angular2 version` thinking it'd show me the local one and it showed beta7. Should have verified better. Sorry for the noise. 

For those having similar issues, it could be something completely different. In my case, it was angular-cli actually bringing beta6. @shawn-northrop TypeScript will follow your `import`s.

**Comment by vanishs** [comment] 2016-02-27 05:37
@afirdousi ＋1

**Comment by kanishk02** [comment] 2016-03-01 08:22
placing declare var Promise: PromiseConstructor;  on the top of promise.d.ts will work

**Comment by lathonez** [comment] 2016-03-04 21:02
beta.7 upgrade fixed for me, thanks.

**Comment by ChrisGrigg** [comment] 2016-03-08 23:47
I'm on 2.0.0-beta.8 and I'm seeing this issue, any fix coming up for this?

**Comment by alexeagle** [comment] 2016-03-09 01:34
If you still have this error, please give some steps to repro. You probably
don't have beta.8.

**Comment by ChrisGrigg** [comment] 2016-03-09 22:31
Fixed. Apologies, I got caught out by "npm show angular2 version" which shows the latest available module rather than what I should have done "npm angular --version".

**Comment by ChrisGrigg** [comment] 2016-03-09 22:31
Thanks

**Comment by molekilla** [comment] 2016-03-10 21:28
hi all,

I found this in the [changelog](https://github.com/angular/angular/blob/master/CHANGELOG.md) and it worked for me
```
2.0.0-beta.6 (2016-02-11)
BREAKING CHANGES

Transitive typings are no longer included in the distribution.

If you use --target=es5, you will need to add a line somewhere in your application (for example, at the top of the .ts file where you call bootstrap):

///<reference path="node_modules/angular2/typings/browser.d.ts"/>
```

I wonder if it has been updated in the documentation.

Regards

**Comment by alexeagle** [comment] 2016-03-10 21:41
@molekilla that's not this issue. For `Cannot re-export name that is not defined in the module.` the solution is to downgrade TS to 1.7 or upgrade angular2 to beta.7+

Your solution is for missing typings.

**Comment by molekilla** [comment] 2016-03-10 21:49
I probly got confused, I'd try different versions of typescript/angular, seems on my end was the missing typings. thanks

**Comment by MattDHill** [comment] 2016-03-16 18:53
@alexeagle sorry if this is a terribly stupid question, but I am still encountering this same problem. When I check my latest Angular version using "npm angular --version" it says 3.8.1. I know the latest is beta.9. How do I upgrade to beta.9? I can't seem to do it anywhere.

**Comment by ericmartinezr** [comment] 2016-03-16 19:07
@MattDHill do `npm install angular2@latest --save`. The result you get sounds to be npm version itself.

**Comment by alexeagle** [comment] 2016-03-16 19:59
right, `npm angular` is not an npm command, probably you should get an
error instead.

**Comment by vukasin0** [comment] 2016-03-29 04:52
Still issue in typescript@1.8.9

**Comment by alexeagle** [comment] 2016-03-29 17:12
@vukasin0 doesn't matter what version of TypeScript, any 1.8 branch will have this problem unless you update angular2 past beta.7

**Comment by nicobytes** [comment] 2016-04-05 22:58
I have the same error, What is solution?
![screenshot from 2016-04-05 18-54-36](https://cloud.githubusercontent.com/assets/7611944/14300724/4fe990f2-fb60-11e5-8d4d-0eadbf13c341.png)

**Comment by mikepc** [comment] 2016-04-07 04:15
npm install --save zone.js@0.5.15 rxjs@5.0.0-beta.2 angular2@2.0.0-beta.7 

This successfully builds and runs without this error, but I haven't run a full regression on it or anything, but it seems to be working for me.

**Comment by russellf9** [comment] 2016-04-14 20:30
Working from the latest development build:

`npm i typescript@next -D`

**Comment by AdrienTorris** [comment] 2016-04-20 12:03
Same issue with _typescript 1.7.1_, _angular 2.0.0-beta1_ et _rxjs 5.0.0-beta.1_, solved with @sicaner's solution.

**Comment by AdrienTorris** [comment] 2016-04-20 15:16
[TypeScript changelog](https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#exporting-non-local-names-from-a-module)

**Comment by nbaua** [comment] 2016-08-23 04:23
Add the following line in your promise.d.ts (this would be your first line in file)

`declare var Promise: PromiseConstructor;`

Hope this helps

**Comment by Huthaifah-kholi** [comment] 2016-11-28 17:30
it solve for me after doing this commands : 
1. `typescript@next` which update typescript.
2. adding declare` var Promise: PromiseConstructor;` on the top of **promise.d.ts** file on your project. 
this solution come to me from the previous comments on this issue. thanks to all

**Comment by malutanpetronel** [comment] 2017-05-22 15:09
A bit redundant ? It should be re-changed if you will run again npm install to add some other packages ?
