### ISSUE TITLE
[Feature request]: creating a local pipe in component for template

### ISSUE THREAD

**Issue by splincode** [angular/angular#25976] opened 2018-09-15 15:00 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

app.component.ts

```ts
import { Component } from '@angular/core';

@Component({
  selector: 'my-app',
  template: `
    original: {{ msg }} 
    reverse: {{ msg | reverse }}   
  `
})
export class AppComponent  {
  public msg = 'Angular';
}
```

reverse.pipe.ts

```ts
import { Pipe } from '@angular/core';

@Pipe({name: 'reverse'})
export class ReversePipe implements PipeTransform {
  public transform(value: string): string {
    return value.split('').reverse().join('');
  }
}
```

## Expected behavior

I. First expected

```ts
import { PipeLocal, Component } from '@angular/core';

@Component({
  selector: 'my-app',
  template: `
    original: {{ msg }} 
    reverse: {{ msg | reverse }}      
  `
})
export class AppComponent  {
  public msg = 'Angular';
  
  @PipeLocal()
  public reverse(value: string) {
    // pure invoke function in template
    return value.split('').reverse().join('');
  }

}
```

II. Second expected

```ts
import { Pipe } from '@angular/core';

@Pipe({
  name: 'reverse', 
  provideIn: 'root'
})
export class ReversePipe implements PipeTransform {
  public transform(value: string): string {
    return value.split('').reverse().join('');
  }
}
```

I would also like to have provideIn for pipe.
Because I can have many utilities and every time I import them tires.

## What is the motivation / use case for changing the behavior?

- Many do not understand that poor performance, if directly done so

```html
original: {{ msg }}
reverse: {{ reverse(msg) }}
```

- According to statistics, very rarely projects are created by pipes

- Quickly create piped methods

@StephenFluin @mhevery @trotyl Do you think this is possible?

**Comment by mhevery** [comment] 2018-09-18 22:12
@robwormald this is similar to what we have discussed.

**Comment by lazarljubenovic** [comment] 2018-10-30 08:09
I'd like to see local pipes as well, but I disagree with the rationale -- it seems to suggest that pipes are **the** way to use pure functions in templates to prevent rapid invocation on every CD cycle. Pipes are pure, yes, but that doesn't mean that everything that we want to be pure should be solved by a pipe. Pipes should be used for end-user-friendly formatting of data (decimal pipe, date pipe, currency pipe), not for arbitrary invocation of pure functions.

The way I see it, this proposal asks about a **way to define pure functions**, but (wrongly, in my opinion) assumes that pipes are the way to go.

Instead of pipes, why don't we allow this:

```ts
  @Pure()
  public reverse(value: string) {
    return value.split('').reverse().join('')
  }
```

Then, in the template, we can just do, as always,

```ts
{{ reverse(msg) }}
```

but without the degrading performance implications.

---

When looked from this perspective, I don't think that you often actually want a local pipe. A pipe should be universal and should be able to format data from everywhere in the app -- there should be little reason to tie it to one specific component. It's not pipes that we need, it's pure functions.

**Comment by mlc-mlapis** [comment] 2018-10-30 08:53
> A pipe should be universal and should be able to format data from everywhere in the app

Sure, but still there are many cases (at least at our environment) where local pipes are useful because they are exceptions for just that one component ...

> `@Pure() public reverse(value: string) { ... }`

This way is certainly the preferred one but we have to also answer what should be the limits for input params ... the same logic as for `OnPush` strategy? So immutable objects, arrays + primitives?

**Comment by lazarljubenovic** [comment] 2018-10-30 15:09
> what should be the limits for input params

The same as with pipes, I guess?

**Comment by pkozlowski-opensource** [comment] 2019-02-10 14:18
I think that @lazarljubenovic nailed it in his comment:

> I'd like to see local pipes as well, but I disagree with the rationale -- it seems to suggest that pipes are **the** way to use pure functions in templates to prevent rapid invocation on every CD cycle. Pipes are pure, yes, but that doesn't mean that everything that we want to be pure should be solved by a pipe. Pipes should be used for end-user-friendly formatting of data (decimal pipe, date pipe, currency pipe), not for arbitrary invocation of pure functions.

Going over this issue (and similar ones) I've realised that we are discussing 2 _separate_ issues:

1.  ability to define and use a pipe in one component only (without a need of registering it in `NgModule`, sharing with other components etc.); the need here is to simplify pipes creation, especially when those are used in one component only;

2.  make sure that (pure) functions are not repeatedly called in each and every change detection cycle; the need here is to avoid unnecessary work and (potential) performance issues.  

From what I'm reading in other issues the (2) is what we are really after and (1) is just a mean to getting (2). While I agree that pure pipes _could_ be used to limit unnecessary invocations of (pure) functions it sounds like we are after _property_ of pure pipes (memorisation of results based on arguments) here. Using pure pipes _could_ work but IMO it is unnecessary complication (one needs to create a _class_, register it in `NgModule`, Angular would have create its instance, we need to take care of the `this` etc.) for simply telling Angular "hey, this is a pure function, don't call it repeatedly if arguments are the same".

I totally see the need of better support for pure functions in Angular template syntax but as @lazarljubenovic I don't believe that pipes are the way to go. It would be just too heavy for what we really need.

**Comment by pkozlowski-opensource** [comment] 2019-02-10 14:19
BTW, the (1) need from the above discussion is a duplicate of (or at least very much related to) #24559

**Comment by manklu** [comment] 2019-02-10 18:14
> 2\. make sure that (pure) functions are not repeatedly called in each and every change detection cycle; the need here is to avoid unnecessary work and (potential) performance issues

Solvable with Observables. It's just a matter of getting used to it.

**Comment by BAM5** [comment] 2019-08-11 13:49
Just thought of this elegant little solution to the "pure function" issue. It's a good workaround for now.

```typescript
import { Pipe, PipeTransform } from '@angular/core';

type TransFunc = (val:any, ...args:any[])=>any;

@Pipe({
	name: 'purify'
})
export class PurifyPipe implements PipeTransform {
	transform<FuncT extends TransFunc>(value:any, func:FuncT, ...args:any[]):ReturnType<FuncT> {
		return func(value, ...(args||[]));
	}
}
```

And can be used like so
```typescript
@Component({
	selector: 'app-root',
	template: `<ul><li *ngFor="let hash in imageHashes">{{hash | purify:hashToFile:'frank'}}</li></ul>`,
})
export class AppRoot{
	imageHashes:string[] = ['fakehash', 'stillfake', 'whyareyoulookinghere-stillsuperfake'];
	
	hashToFile(imageHash:string, name:string):string{
		return `/user/${name}/${imageHash}.jpg`;
	}
}
```

Enjoy!

**Comment by Airblader** [comment] 2019-11-18 21:18
> Pipes are pure, yes, but that doesn't mean that everything that we want to be pure should be solved by a pipe. Pipes should be used for end-user-friendly formatting of data (decimal pipe, date pipe, currency pipe), not for arbitrary invocation of pure functions.

IMHO pipes have another major benefit, which is centralizing formatting logic for reusability. In our applications we have a lot of enums, and enums want to be displayed in a readable format or be mapped to a specific icon etc. Having pipes for these makes it very easy to manage this logic separately and DRY. The same *could* be achieved by services, but that would require manually injecting them everywhere.

→ I agree that not every single pure function should be a pipe, but I do think the market for pipes is or can be bigger than it seems.

**Comment by lazarljubenovic** [comment] 2019-11-19 06:56
I like the idea with icons, since an icon is still a formatting issue. You don't need the icon in the model, you only want to display it to the user from the template. Just like you transform `10000` into `10.000,00`, you also want to transform `true` into a green-colored circle and `false` into a red-colored circle. So I see `<my-icon [icon]="user.isOnline | iconize"></my-icon>` conceptually equivalent to `{{ user.postsCount | number : '1.0-0' }}`, even though one pipe returns a string and the other pipe returns (probably) and object with SVG data attached to it, and `my-icon` knows how to turn this data into a valid HTML/SVG structure.

**Comment by MaximSagan** [comment] 2020-01-29 00:45
I hate to be that guy, but... any progress on this issue?

**Comment by SuperiorJT** [comment] 2020-05-15 15:38
Currently working on something in my app that would be improved by a feature like this. I have a component that displays translated tooltip content based on the entered data. I think if you guys do plan to implement something like this to also consider idempotent functions rather than just pure functions. This applies in my case because I have to use a service to translate the result, but the result is consistently the same consistently with a given input.

I guess if it were impossible to handle idempotent functions, then I can pass the result of the pure function to a translate pipe. For other situations like this though, I would prefer to be able to do everything without a pipe if the function is available in the component.

**Comment by pkozlowski-opensource** [comment] 2022-09-28 13:59
Standalone components support locally-defined pipes, ex.:

```typescript
@Pipe({ name: 'brackets', standalone: true })
export class ExamplePipe implements PipeTransform {
  transform(value: any, ...args: any[]) {
    return `(${value})`;
  }
}

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [ExamplePipe],
  template: `{{'I am in brackets' | brackets}}`,
})
export class ExampleStandaloneComponent {}
```

Working stackblitz: https://stackblitz.com/edit/angular-standalone-ks9pkt?file=src%2Fmain.ts

Closing as already implemented.

**Closed by pkozlowski-opensource** 2022-09-28 13:59 UTC
Labels: feature, comp: core, core: directive matching, core: pipes, under consideration

**Comment by evgeniyefimov** [comment] 2022-09-28 14:18
I think it's not what people from this topic expected. We could do almost the same without standalone components. This is not ergonomic solution.

**Comment by pkozlowski-opensource** [comment] 2022-09-28 14:31
@evgeniyefimov the problem is that there are [multiple items](https://github.com/angular/angular/issues/25976#issuecomment-462136638) being discussed here so at this point it is not very clear what the expectation is.

But if people want to use "just a function in a template":
* for un-pure functions one can just call a function in a template - there is very little added value of a pipe here;
* for memoized "pure" functions one could use a memo utility as described in https://github.com/angular/angular/issues/47553#issue-1387344568

Is there more to it?

**Comment by evgeniyefimov** [comment] 2022-09-29 10:37
> @evgeniyefimov the problem is that there are [multiple items](https://github.com/angular/angular/issues/25976#issuecomment-462136638) being discussed here so at this point it is not very clear what the expectation is.
> 
> But if people want to use "just a function in a template":
> 
> * for un-pure functions one can just call a function in a template - there is very little added value of a pipe here;
> * for memoized "pure" functions one could use a memo utility as described in [Computed properties (model => model synchronisation) #47553 (comment)](https://github.com/angular/angular/issues/47553#issue-1387344568)
> 
> Is there more to it?

Call a function in a template is a bad pratice. It'll be called each change detection cycle, but pipe only when its' inputs are changed.
About memoized functions @dawidgarus mentioned here https://github.com/angular/angular/issues/20419#issuecomment-425070292 that memoized function can't do things like: `<div *ngFor="let item of list">{{func(item, arg2)}}</div>`. There is a discussion about this.

**Comment by lazarljubenovic** [comment] 2022-09-29 10:55
It's a bad practice to do it mindlessly. There are countless cases where it's perfectly fine to do so and is no better than a pipe.
