### ISSUE TITLE
ViewContainerRef behaviour specification

### ISSUE THREAD

**Issue by krp12345** [angular/angular#51880] opened 2023-09-23 05:38 UTC
### Describe the problem that you experienced

consider component template:
```
<div #ref>
<ul>
<li>A</li>
<li>B</li>
</ul>
<p>
Test Paragraph
</p>
</div>
```
Now, I can get ViewContainerref of div element. When first time I learnt about ViewContaineref, I expected that it will represent all elements inside it. But, that is not the case. ViewContainerRef.length value is zero. when insert an element then it inserts in sibling of the element, not inside the element. Why is the case? 
I think there is no clear specification that what exactly is expected from the ViewContainerRef. 

Docs says "Represents a container where one or more views can be attached to a component."
But based on observations, it should be said as "Represents a container where one or more views can be attached in the sibling of the element"

### Enter the URL of the topic with the problem

https://angular.io/api/core/ViewContainerRef

### Describe what you were looking for in the documentation

detailed explanation and behaviour specification of ViewContainerRef.

**Comment by JeanMeche** [comment] 2024-03-29 06:51
I'll close this as a dupe of #43602

**Closed by JeanMeche** 2024-03-29 06:51 UTC
Labels: core: dynamic view creation, P3, area: adev, area: docs
