### ISSUE TITLE
ChangeDetectionStrategy.OnPush breaks ControlValueAccessor functionality

### ISSUE THREAD

**Issue by mseemann** [angular/angular#12607] opened 2016-10-29 14:27 UTC
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

If a ControlValueAccessor component is used as a child of a component with it's ChangeDetectionStrategy is set to OnPush the current value is always one change behind.

**Expected behavior**

If a ControlValueAccessor component is used as child of a component with it's ChangeDetectionStrategy is set to OnPush it should work exactly as if the ChangeDetectionStrategy is set to Default.

**Minimal reproduction of the problem with instructions**

Plnkr http://plnkr.co/edit/1WboKWCqmPZFF8DOBfsd?p=preview. Click on the Button _Push Changes_. As you can see the red bordered input control did not reflect the current value. Please note: the blue bordered control is the same component type - but is used as a child of a component with ChangeDetectionStrategy.Default.

**What is the motivation / use case for changing the behavior?**

Custom Controls are not working as childs of components with ChangeDetectionStrategy.OnPush
- **Angular version:** 2.0.X
  
  
  
  2.x
- **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
  
  
  
  all
- **Language:** [all | TypeScript X.X | ES6/7 | ES5]
  TypeScript
- **Node (for AoT issues):** `node --version` =  
  v5.10.1

**Comment by DzmitryShylovich** [comment] 2016-10-29 14:43
Duplicate of https://github.com/angular/angular/issues/10816

**Comment by mhevery** [comment] 2017-12-13 00:00
closing as dup

**Closed by mhevery** 2017-12-13 00:00 UTC
Labels: comp: forms
