### ISSUE TITLE
Creates cyclic dependancy issue if HTTP_INTERCEPTORS used

### ISSUE THREAD

**Issue by andyh6969** [angular/angular#42784] opened 2021-07-07 09:24 UTC
### Description
If HTTP_INTERCEPTORS are used elsewhere in the project then a cyclic dependancy can occur.

## Fix
Use HttpBackend as it bypasses any existing interceptors.

```

import { HttpClient, HttpHeaders, HttpBackend  } from '@angular/common/http';
import { Cookie } from 'ng2-cookies';

@Injectable()
export class LogglyService {
    private LOGGLY_INPUT_PREFIX: any;
    private LOGGLY_COLLECTOR_DOMAIN: any;
    private LOGGLY_SESSION_KEY: any;
    private LOGGLY_SESSION_KEY_LENGTH: any;
    private LOGGLY_PROXY_DOMAIN: any;
    private session_id: any;
    private inputUrl: any;
    private _http: HttpClient;

    constructor(private handler: HttpBackend) {
        this._http = new HttpClient(handler);
       .......
```

**Comment by petebacondarwin** [comment] 2021-07-07 10:33
Thanks for posting this issue. Closing as it seems that you are recommending a solution to a user-land coding issue, which is not a bug in Angular, nor a feature request.

By the way, be aware that if you instantiate your own `HttpClient` then the interceptors defined, which is how it avoids the circular dependency.

**Closed by petebacondarwin** 2021-07-07 10:33 UTC
