### ISSUE TITLE
public FormControl _unregisterOnChange interface

### ISSUE THREAD

**Issue by keatkeat87** [angular/angular#40457] opened 2021-01-16 03:13 UTC
# 🚀 feature request
_unregisterOnChange is a private property of FormControl class. Please make it public.

### Relevant Package

angular/forms

### Description
We can use registerOnChange as a public API, however we can't to unregister it, it looks doesn't make sense.

### Describe the solution you'd like
make it public

### Describe alternatives you've considered
no

**Comment by AndrewKushnir** [comment] 2021-01-17 00:32
Closing as a duplicate of #40457.

**Closed by AndrewKushnir** 2021-01-17 00:32 UTC
Labels: comp: forms, feature
