### ISSUE TITLE
Update to latest CLDR version

### ISSUE THREAD

**Issue by alfaproject** [angular/angular#43301] opened 2021-09-01 02:26 UTC
Now that https://github.com/angular/angular/pull/42230 is merged, it would be good to update to the latest CLDR if possible.

We are currently patching the `no` locale manually to get what our customers want but that's not really great. ):

### Related
* https://github.com/angular/angular/pull/41778
* https://github.com/angular/angular/pull/42230

**Comment by alfaproject** [comment] 2022-03-08 19:18
Neat!

**Comment by JoostK** [comment] 2022-04-09 20:29
I took a stab at this now that v41 is out, but our tooling is failing as the [cldr NPM dependency](https://github.com/papandreou/node-cldr) is still on v39:

The issue is ironically exactly mentioned in our locale extraction tooling:

https://github.com/angular/angular/blob/b5da715d9ff8f15e0ea3392d1561e9b6acf9d44a/packages/common/locales/generate-locales-tool/plural-function.ts#L15-L16

@devversion you are probably the most familiar with locale extraction. Would it make sense to move away from `cldr` as the comment suggests?

**Comment by devversion** [comment] 2022-04-10 08:02
@JoostK Yeah, back then when I migrated the legacy tooling over for Bazel, I also landed upstream changes in `node-cldr` for CLDR 39 support. So likely we need to do the same again, or look into building the plural function on our own (I think it's the only place right?) -- we could also consider vendoring the plural logic into `third_party`.

**Comment by JoostK** [comment] 2022-04-10 08:17
> I think it's the only place right?

Looks like it indeed; the `plural-function.ts` file is the only one that imports from `cldr`.

> I'm not sure how much effort this currently is, but plural function generation is not super short code IIRC.

Indeed it is not; it is based on a simple grammar to parse [LDML syntax](https://www.unicode.org/reports/tr35/tr35-61/tr35.html) and transform it to JS code. Not too complex to do with a simple parser but would take some effort to get right and maintain. But it would drop a dependency and duplicate CLDR data, which may be an improvement.

**Closed** 2022-04-29 16:20 UTC
Labels: comp: i18n
