### ISSUE TITLE
Router links in `@defer` blocks not having correct relative route

### ISSUE THREAD

**Issue by NachmanBerkowitz** [angular/angular#54864] opened 2024-03-14 17:28 UTC
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

17.2.1

### Description

A RouterLink with a route of `./` should route to the activated route. (eg. `<a [routerLink]="'./'" >Link One</a>`). But when it is in a defer block, and it is a sibling of a component that imports from material it routes to the app root.
So
`    @defer(on timer(1000))
    {
      <has-material/>
      <a [routerLink]="'./'" >Link One</a>
    }` routes to the root.
    
![image](https://github.com/angular/components/assets/38742354/6c4a3721-471e-4a6d-9615-ed12408e5955)

### Reproduction

StackBlitz link: https://stackblitz.com/edit/stackblitz-starters-prh2zk
Steps to reproduce:
1. Have a RouterLink in a defer block that has a relative route
2. Give it a sibling that imports from Material

### Expected Behavior

The router link route should be relative to the current route.

### Actual Behavior

The router link route is from the root. The 'ActiveRoute' seems to be incorrect.

### Environment

- Angular: >= 17.2.4
- CDK/Material: 17.2.2
- Browser(s): edge, chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by alxhub** [comment] 2024-03-14 21:50
Likely related to the injector construction of `@defer`.

**Comment by JeanMeche** [comment] 2024-03-14 21:50
I could narrow it down a bit: 

The `ActivatedRoute` has an undefined route when in a defer block and having a import (whatever import).

**Comment by tiberiuzuld** [comment] 2024-03-15 14:29
From what I tested in above stackblitz, the issue was introduced in v17.2.3 in this PR https://github.com/angular/angular/pull/52881

**Comment by AndrewKushnir** [comment] 2024-03-16 04:42
@NachmanBerkowitz thanks for reporting the issue.

We found the origin of the problem and we are working on a fix. There are a couple first PRs created with the necessary refactoring (#54903 and #54907) and we'll need create a couple more PRs that would fix the issue. There is no exact ETA at this moment, but the final fix would likely be available in one of the 17.3.x releases.

**Comment by AndrewKushnir** [comment] 2024-03-28 18:51
Quick update: the fix for this issue was merged and released as a part of Angular v17.3.2 (available on NPM). Please let us know if you still see the issue after updating to v17.3.2.

**Comment by bboyle** [comment] 2024-04-11 03:23
@AndrewKushnir I found this page debugging an issue today… and think I have a related issue with `@defer`/`routerLink`.

It's not with the active route being undefined, it's with it having a stale value.

I had a user report a broken link on a page in our app.

We have a page that contains a list of posts.
Each post has a list of attachments, each attachment uses routerLink.
The list of attachments is in a discrete component loaded with `@defer (on viewport(post)` where `#post` is set on the wrapper post element — ideally as each post enters the viewport, the attachments component is loaded (which fetches various thumbnail images)

Everything works fine when viewing a feed for the first time. The links are correct.

However, if the user navigates away to another page in the app, and then navigates to a different feed… (same component structure, but a different URL, think /feed/A vs /feed/B -- the route config is /feed/:feedID)
when the list of attachments loads (via defer again) in this new view, all the links point to the previous URL (/feed/A rather than /feed/B). I did some logging on ActivatedRoute in that component and verified it had the previous route still, which led me here.

Not sure if that's enough info to debug. I don't really know how to put together a stackblitz.
For now I've removed `@defer` from the app and routerLink is working correctly.

**Comment by atscott** [comment] 2024-04-11 04:03
> Not sure if that's enough info to debug.

It's not, unfortunately. A reproduction is really needed for us to investigate.

> I don't really know how to put together a stackblitz.

Can you create a minimal GitHub repo instead?

**Comment by bboyle** [comment] 2024-04-11 14:49
working on it. it's at that infuriating stage.
in a brand new repo where I'm building out a similar route structure and use of defer, no issue.
in our app, cutting out code like crazy to bring it back to the simplest form, I haven't been able to NOT reproduce it.

There is definitely a bug somewhere. I can't prove it's in angular yet, but I can't prove it's not. The fact that removing defer corrects the routerLink URLs sure smells like angular. I've disabled all guards and resolvers and ruled out those.

3+ hours, not how I want to spend my free time 😅 but the gap must be closing…

**Comment by NachmanBerkowitz** [comment] 2024-04-11 15:07
@bboyle @atscott We just rolled out with 17.3 and we are having a similar issue. Sometimes the route is 'stuck' on an old value. I am also struggling to figure out what causes that behavior and how to reproduce.

**Comment by NachmanBerkowitz** [comment] 2024-04-11 16:13
@bboyle @atscott I updated my stackblitz to reproduce the issue.
https://stackblitz.com/edit/stackblitz-starters-prh2zk
If you first click on go to test component with id 1, then click on go to Navigate To test 2, then click on Click here for test componet with id 4, then hover over the 'current route' link, it will have the wrong id in the url. It will have 1 instead of 4.

**Comment by NachmanBerkowitz** [comment] 2024-04-11 16:15
Until there is a fix we have rolled back to 17.2 (again).

**Comment by NachmanBerkowitz** [comment] 2024-04-11 19:22
Should we be making a new bug report for this?

**Comment by atscott** [comment] 2024-04-11 20:42
@AndrewKushnir is out of office until next week. 

I made the reproduction a bit smaller: https://stackblitz.com/edit/stackblitz-starters-uxf7bm
I found that removing the `RouterModule` imports of the component in the defer block makes it work.

**Comment by bboyle** [comment] 2024-04-11 23:23
FYI I don't have `RouterModule` imported anywhere in my app (standalone component migration was completed).
Will keep working on reproducing the issue.

**Comment by bboyle** [comment] 2024-04-16 01:39
I have reproduced the issue -- here is a git repo you can run locally to see it in action: https://github.com/bboyle/angular-defer-routerlink

Follow the instructions on screen and you will get to a state where some links (which use `routerLink="[]"`) are no longer linking to the current URL. I have used simple CSS to highlight the links, but just hover over them to compare the href to the current URL.

The issue occurs when `MatTooltipModule` is imported into the child module. In this example app, tooltips are not used, but in my company's app we do indeed use tooltips in the child module. Simply importing the module is enough to trigger the bug.

factors required to reproduce this bug:
- lazy loading with defer: https://github.com/bboyle/angular-defer-routerlink/blob/main/src/app/feed-post/feed-post.component.html#L5
- `routerLink="[]"` in the child component: https://github.com/bboyle/angular-defer-routerlink/blob/main/src/app/feed-child/feed-child.component.html#L2
- import MatTooltipModule https://github.com/bboyle/angular-defer-routerlink/blob/main/src/app/feed-child/feed-child.component.ts#L9

let me know if you need any more details

**Comment by Yberion** [comment] 2024-04-16 13:56
Hello, it seems that I have the same problem there, I wanted to use defer blocks to load a different layout depending on the result of the `BreakpointObserver`, both having a router outlet for child pages.

The problem occur with a component from `Angular Material`, it seems that the router and ActivatedRoute are not "synchronized" anymore.

- https://github.com/Yberion/angular-defer
- npm i
- npm run start
- Open the console (everything is logged in the console)
- click on "go to page1 from home"
- click on "page2"
- click on  "page 1"
- click on "home"
- Previous page via browser button
- click sur "page2"
- click sur "home"
- Previous page via browser button

And it is at this point that we get different results from the router and the snapshot.

The problem appears in the component that is defered "LoaderComponent ", no problem in the "SomepageComponent" (logs).

The problem disappears if I remove "MatButtonModule" from "LoaderComponent" OR if I remove the defer block from "SomepageComponent".

**Comment by NachmanBerkowitz** [comment] 2024-04-16 14:33
This bug seems like the previous bug. Using a defer block around a component that imports 'something' causes issues with the ActivatedRoute in that component.

**Comment by AndrewKushnir** [comment] 2024-04-17 01:08
@Yberion thanks for providing a repro. We've identified the root cause and I've created a PR with a fix: https://github.com/angular/angular/pull/55374. I will update this thread once the mentioned PR lands.

**Closed** 2024-04-22 19:01 UTC
Labels: area: router, area: core, state: has PR, core: di, P2, bug, core: defer

**Comment by AndrewKushnir** [comment] 2024-04-25 21:03
FYI, the fix from PR https://github.com/angular/angular/pull/55374 was merged and released as a part of v17.3.6. Please let us know if the problem still exists after updating to v17.3.6.

**Comment by Yberion** [comment] 2024-04-25 22:00
Hello @AndrewKushnir, thanks a lot for the fix, I can confirm on ym side that it is working now!
