### ISSUE TITLE
From/To Keyframes animations break theirself and the router

### ISSUE THREAD

**Issue by Azmos** [angular/angular#14752] opened 2017-02-27 02:18 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Angular fails to execute Web Animations API if you use from/to keyframes. I've found something [here](https://github.com/web-animations/web-animations-js/issues/14), but I don't know how I could make use of what is written there. Furthermore, the router will fail too after the manifestation of the bug.

In Firefox the console says :

> EXCEPTION: Animation to or from an underlying value is not yet supported.

But in Chrome:

> EXCEPTION: Failed to execute 'animate' on 'Element': Partial keyframes are not supported.

**Expected behavior**

Smooth transition between two declared states.

**Minimal reproduction of the problem with instructions**

```ts
// [...]
@Component({
    // [...]
	animations: [
		trigger('ae', [
			state('resellers', style({
				transform: 'translateY(0)'
			})),
			transition('* => resellers', [
				animate('300ms ease-in', keyframes([
					style({transform: 'translateY(-100%)', offset: 0}),
					style({transform: 'transateY(0)', offset: 1})
				])),
			]),
			transition('resellers => *', [
				animate('300ms ease-out', keyframes([
					style({transform: 'transateY(0)', offset: 0}),
					style({transform: 'translateY(-100%)', offset: 1})
				])),
			])
		])
	]
})
// [...]
```

**What is the motivation / use case for changing the behavior?**

From/to keyframes in animations.

**Please tell us about your environment:**

* **Angular version:** 2.1.X

* **Browser:** [Chrome 56.0.2924.87 (64 bit) | Firefox 51.0.1 (32 bit)]

 
* **Language:** [TypeScript]

* **Node (for AoT issues):** `node --version` =   6.9.4

**Comment by jinder** [comment] 2017-04-03 14:48
Same as #14752 ?

**Comment by DzmitryShylovich** [comment] 2017-04-03 14:56
@jinder this is #14752

**Comment by jinder** [comment] 2017-04-03 14:59
@DzmitryShylovich  haha, yes, you're right.  I meant #14007...

**Comment by GloriousUnicorn** [comment] 2017-04-03 15:07
Well it could be possible that they share the same bug (or the same fault that we're not coding as it was intended, I don't know).

**Comment by evanjmg** [comment] 2017-04-19 10:16
A Bottom bar in the same view as md-tabs but not inside it. I get the exception - animations: [
    trigger('flyInOut', [
      state('in', style({transform: 'translateY(0)'})),
      transition('void => *', [
        style({transform: 'translateY(100%)'}),
        animate(300)
      ]),
      transition('* => void', [
        animate(300, style({transform: 'translateY(-100%)'}))
      ])
    ])
  ]

**Comment by chris13524** [comment] 2017-06-08 23:56
I get this issue as well when changing the trigger before the animation completes:

	animations: [
	  trigger('selected', [
	    state('no', style({
	      padding: 0,
	    })),
	    state('yes', style({
	      padding: "0.5rem",
	    })),
	    transition('no => yes', animate('200ms ease-in')),
	    transition('yes => no', animate('200ms ease-out')),
	  ]),
	],

**Comment by kukjevov** [comment] 2017-06-22 05:49
I get this error also but in different situation.

this one is working
``` typescript
trigger("test",
[
    transition("* => *",
    [
        style({'background-color': "#FFFFFF"}),
        animate(500, style({'background-color': "#00FFFF"}))
    ])
])
```

and this one is not, only difference is that i dont set default `background-color` and since div element does not have default `background-color` it fails somehow.
``` typescript
trigger("test",
[
    transition("* => *",
    [
        animate(500, style({'background-color': "#00FFFF"}))
    ])
])
```

**Comment by kukjevov** [comment] 2017-06-22 15:29
Hi all.

This looks like a bigger problem.

Look at this https://plnkr.co/edit/JdctUV6hVfcOhdCbCyMk?p=preview it is quite simple. 

It demonstrates code that is above. First version is working, second version is not. 

Here is also demonstration of this problem. https://github.com/kukjevov/ng-universal-demo/tree/animation-error 

Yesterday i was trying new animation features at home and everything was working nicely. I pushed all changes and try them at work and i got error mentioned in this bug. I have 4 web browsers at work i tried FF 55 beta, Chrome 59, Edge 14 none of them worked. Also tried FF 54 and it worked. Today i came home and code which worked yesterday does not work anymore. Not even that plunker that i have provided. 

Well this looks like some changes in browsers. Weird thing is that it behaves randomly. 

So far i found out that this is connected with auto styles `'*'`. If you dont specify explicitly style value it will fail with mentioned error. 

Can you please look at this @matsko, @IgorMinar because it looks like that it completely breaks animations.

Thank you

**Comment by kukjevov** [comment] 2017-06-22 15:36
Is there list of css properties that cant be used for auto property computation? It looks like that problem is `background-color`.

**Comment by kukjevov** [comment] 2017-06-22 16:06
Another interesting observation. When i enabled **dom.animations-api.core.enabled** setting using Firefox `about:config` these animations are working.

**Comment by tommueller** [comment] 2017-07-04 07:34
Strange thing for me is, that the error does not occur in dev-environment. Also the styles work correctly in dev-env. After building the app, the error occurs and things are not correctly rendered because of it ...

**Comment by tommueller** [comment] 2017-09-18 09:58
Apparently this is supposed to be fixed in web-animation-js 4.3.1 (https://github.com/web-animations/web-animations-js/issues/146) but I still get this error in Angular.

Any idea why the animation above throws this error in FF still?

**Comment by matsko** [comment] 2017-12-07 23:23
Hey everyone. Sorry it took me so long to get to this issue.

I'm having a hard time understanding what exactly is breaking here? If a CSS style is not included before its used then Angular should automatically fill it in (so if you miss `backgroundColor` then it will set `backgroundColor: '*'` in the step before).

With 4.x, there were some issues with this, but they did get fixed. @kukjevov @tommueller if this is still problematic then please let me know.

**Comment by tommueller** [comment] 2017-12-11 13:30
@matsko I just tested this again using angular 4 and the new firefox quantum and the problem seems to be gone! thanks for the reminder, still had the buggy parts (padding) commented!

**Comment by jtomaszewski** [comment] 2018-02-13 09:58
If somebody wants to fix it but doesn't want to upgrade his angular version yet, here's a workaround:

```ts
import {
  AnimationDriver,
  ɵNoopAnimationDriver as NoopAnimationDriver,
  ɵsupportsWebAnimations as supportsWebAnimations,
  ɵWebAnimationsDriver as WebAnimationsDriver
} from '@angular/animations/browser';

export function animationDriverFactory(platform) {
  if (platform.CHROME && supportsWebAnimations()) {
    return new WebAnimationsDriver();
  }
  return new NoopAnimationDriver();
}

const PROVIDERS = [
  { provide: AnimationDriver, useFactory: animationDriverFactory, deps: [RtPlatform] }
];
```

**Comment by vicb** [comment] 2018-05-31 22:28
Closing as obsolete

**Closed by vicb** 2018-05-31 22:28 UTC
Labels: comp: animations, freq1: low, severity1: confusing, state: Need repro, type: bug/fix
