### ISSUE TITLE
Cannot instantiate cyclic dependency! When injecting a custom service

### ISSUE THREAD

**Issue by yilmazhasan** [angular/angular#37032] opened 2020-05-10 00:21 UTC
# 🐞 bug report

I'm getting this error for a couple of days, may be after upgrading angular/core to 9.1.4:

An interesting error because when I refreshed the page, it works. Also sometimes without refreshing works but there is nothing that I did to make it work or throw.

Custom service is my LogService that injects these classes:     AngularFirestore, UserProgressService UserService,

This service is not different from other services that I use except for inceject parameters, does it be related with them?

AppModule includes this service in providers.

UserProgressService AngularFirestore, UserService
UserService injects: AngularFireAuth, Events, AngularFirestore.

Detailed error message is:

_Uncaught (in promise): Error: Cannot instantiate cyclic dependency! LogService
Error: Cannot instantiate cyclic dependency! LogService_

It seems not a actual cyclic dependency issue, since it may sometimes work.

Relations are here:
LogService <- UserProgressService <- UserService <- AngularFireAuth, Events, AngularFirestore
LogService <- UserProgressService <- AngularFirestore
LogService <- UserService <- AngularFireAuth, Events, AngularFirestore
LogService <- AngularFirestore

**Comment by pkozlowski-opensource** [comment] 2020-05-10 04:59
@yilmazhasan I'm afraid that we won't be able to do anything about this issue without a minimal reproduce scenario. I can understand that it might be difficult to reproduce since the problem happens only from time to time. Still, you will need to try to narrow down the issue as we can't act on problems that we can't reproduce and understand.

**Comment by kara** [comment] 2020-05-27 23:34
@yilmazhasan Please create a new issue whenever you have a minimal repro, which will bring it back to our attention. Closing this one since it's not actionable as is.

**Closed by kara** 2020-05-27 23:34 UTC
Labels: comp: core, core: di, state: Needs repro, triage #1, type: bug/fix

**Comment by yilmazhasan** [comment] 2020-06-01 09:04
It seems solved for now by deferring service constructors to make them wait for firestore authentication to be completed.

Problem was most probably related with service constructor statements of not being completely executed because of null exception that occurs because of unauthenticated status of user.

Still thanks!
