### ISSUE TITLE
Angular Universal Issues

### ISSUE THREAD

**Issue by Code-By-Asutosh** [angular/angular#47060] opened 2022-08-06 13:30 UTC
### Which @angular/* package(s) are the source of the bug?

platform-server

### Is this a regression?

No

### Description

Hi, i am using angular universal for my project, whenever i run (by using this command npm run dev:ssr) that application. i face some issues. i can't resolve it, because not have enough documentation are there in internet.                                                       
"Can anyone please help me how I can resolve this problem"
![Screenshot (26)](https://user-images.githubusercontent.com/92537368/183250981-93ef5f1b-417c-450e-9025-f99481a5f266.png)
![Screenshot (29)](https://user-images.githubusercontent.com/92537368/183250992-8926e324-99e0-40ab-b732-cd9c9d92f012.png)
![Screenshot (31)](https://user-images.githubusercontent.com/92537368/183250997-5d409459-8ce2-44a9-848b-dd40615821c6.png)

### Please provide the exception or error you saw

```true
ERROR TypeError: Cannot set properties of null (setting 'textContent')
    at Timeout.<anonymous> (C:\Users\OhhProTech\Downloads\apps11-4\apps\dist\apps\server\467.js:3709:67)
    at Timeout.timer (C:\Users\OhhProTech\Downloads\apps11-4\apps\dist\apps\server\main.js:208299:33)
    at _ZoneDelegate.invokeTask (C:\Users\OhhProTech\Downloads\apps11-4\apps\dist\apps\server\main.js:205955:173)
    at Object.onInvokeTask (C:\Users\OhhProTech\Downloads\apps11-4\apps\dist\apps\server\main.js:276235:33)
    at _ZoneDelegate.invokeTask (C:\Users\OhhProTech\Downloads\apps11-4\apps\dist\apps\server\main.js:205955:56)
    at Zone.runTask (C:\Users\OhhProTech\Downloads\apps11-4\apps\dist\apps\server\main.js:205705:39)
    at ZoneTask.invokeTask (C:\Users\OhhProTech\Downloads\apps11-4\apps\dist\apps\server\main.js:206050:28)
    at Timeout.ZoneTask.invoke (C:\Users\OhhProTech\Downloads\apps11-4\apps\dist\apps\server\main.js:206036:40)
    at Timeout.data.args.<computed> [as _onTimeout] (C:\Users\OhhProTech\Downloads\apps11-4\apps\dist\apps\server\main.js:208276:28)
    at listOnTimeout (node:internal/timers:557:17)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.2.6
Node: 16.13.1
Package Manager: npm 8.1.2
OS: win32 x64

Angular: 13.2.7
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1302.6
@angular-devkit/build-angular   13.2.6
@angular-devkit/core            13.2.6
@angular-devkit/schematics      13.2.6
@angular/cli                    13.2.6
@nguniversal/builders           13.1.1
@nguniversal/express-engine     13.0.2
@schematics/angular             13.2.6
rxjs                            7.5.6
typescript                      4.5.5
```

**Comment by dario-piotrowicz** [comment] 2022-08-07 17:38
Hi @Code-By-Asutosh , sorry for being a stick in the mud, but this looks like a question which should be posted on [stackoverflow](https://stackoverflow.com/) rather than as an issue here (please have a look at this [md section](https://github.com/angular/angular/blob/68a6a075f4aeab1788a1bba736bfcb428cfbbacb/devtools/CONTRIBUTING.md#-got-a-question-or-problem)).

___

Besides what I just mentioned I think you need to provide some code for people in order to help you out, this is way too generic in my opinion. I would suggest you to share a github repo with your code so that people can have a look (or a minimal reproduction of it if you don't want to share the code itself).

If you provide some code I would be happy to try to help out :slightly_smiling_face: 

(if possible please open a stackoverflow question for this and provide the url here as I think stackoverflow would be the right place to discuss this)

**Comment by pkozlowski-opensource** [comment] 2022-08-08 00:57
Thnx @dario-piotrowicz for offering help 👍 . As you've mentioned this is more of the support request so it doesn't belong to the issue tracker, really. As such I'm going to close it but you are more then welcomed to continue the discussion in here.

**Closed by pkozlowski-opensource** 2022-08-08 00:57 UTC
