### ISSUE TITLE
Need to import COMPILER_PROVIDERS in angular 5

### ISSUE THREAD

**Issue by icepoint0** [angular/angular#21794] opened 2018-01-26 03:22 UTC
The @angular/platform-browser-dynamic public_api no more export COMPILER_PROVIDERS

and @angular/compiler doesn't export too,

how to fix this .

**Comment by trotyl** [comment] 2018-01-26 03:28
Duplicate of #20125

**Comment by icepoint0** [comment] 2018-01-26 03:30
ok

**Comment by jasonaden** [comment] 2018-01-26 18:01
Closing as duplicate.

**Closed by jasonaden** 2018-01-26 18:01 UTC
