### ISSUE TITLE
Runtime compiler is not loaded not works by AoT

### ISSUE THREAD

**Issue by arwindgao** [angular/angular#13083] opened 2016-11-25 09:04 UTC
I decide to improve my site performance with angular 2 AoT compiler.
As some requirements issue, i need loading my components dynamically in my ng2 app, when i start to build my app with AoT compiler, everythings goes well, but if i open the url, i got an error: "Runtime compiler is not loaded", after i doing some researches on the Internet, it's look like that Aot could not works with runtime compiler defaultly. Is there any workaround? Any input will be appreciated.
Thanks.

**Comment by DzmitryShylovich** [comment] 2016-11-25 09:08
https://github.com/angular/angular/issues/12885#issuecomment-260836756

**Comment by arwindgao** [comment] 2016-11-25 09:17
@DzmitryShylovich Thanks, but i want know if there's any workaround, i ever follow laco0416's workaround but get error 'No ResourceLoader implementation has been provided'. would you like to provide some suggestions or guidances?

**Comment by DzmitryShylovich** [comment] 2016-11-25 09:20
This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

**Comment by arwindgao** [comment] 2016-11-25 09:21
ok thanks.

**Comment by DzmitryShylovich** [comment] 2016-11-25 09:23
Duplicate of https://github.com/angular/angular/issues/11780

**Comment by robwormald** [comment] 2016-11-26 19:28
The point of AoT compilation is that the runtime compiler is not shipped to the browser, thus this works as intended. You should lazy load precompiled modules and retrieve components from there.

**Closed by robwormald** 2016-11-26 19:28 UTC

**Comment by sekarcrazy** [comment] 2016-12-11 02:41
@robwormald,Thanks. How to do lazy load precompiled modules and retrieve components. I tried the way like,Ex. let new Promise(resolve =>
			(require as any).ensure([], () => {
				let dynamicModule = require('./food/module.ngfactory')['FeatureModuleNgFactory'];
});

I dont know how to create an component from there. Can you help me on it.

**Comment by gorshkov-leonid** [comment] 2017-04-06 15:24
@robwormald could you explain please?
