### ISSUE TITLE
ERROR in Maximum call stack size exceeded when ng build --prod

### ISSUE THREAD

**Issue by SANTOSHKVNSP** [angular/angular#27846] opened 2018-12-27 14:31 UTC
# 🐞 bug report

### Description

My angular app has around a lazy loaded module the size of which is 520kb. ng build is working , but when I do ng build --prod it gives me the following error
 A clear and concise description of the problem...

## 🔥 Exception or Error
<pre><code>
ng build --prod --verbose
13163ms building modules                                                               
1ms finish module graph                             
0ms sealing                                
0ms basic dependencies optimization 
1ms dependencies optimization                           
0ms advanced dependencies optimization 
1ms after dependencies optimization 
0ms optimizing 
0ms basic module optimization 
0ms module optimization                          
0ms advanced module optimization 
0ms after module optimization 
1ms basic chunk optimization                             
0ms chunk optimization 
3ms advanced chunk optimization                         
0ms after chunk optimization 
1ms module and chunk tree optimization 
0ms after module and chunk tree optimization 
0ms basic chunk modules optimization 
0ms chunk modules optimization                           
0ms advanced chunk modules optimization 
0ms after chunk modules optimization 
1ms module reviving                 
0ms module order optimization                                
0ms advanced module order optimization 
0ms before module ids                       
1ms module ids 
0ms module id optimization 
0ms chunk reviving                 
1ms chunk order optimization                               
0ms before chunk ids 
0ms chunk id optimization                          
0ms after chunk id optimization 
6ms hashing 
0ms after hashing 
1ms module assets processing 
3ms chunk assets processing 
0ms additional chunk assets processing 
7ms additional asset processing                        
4352ms chunk asset optimization                      
0ms after chunk asset optimization 
0ms asset optimization 
1ms after asset optimization 
0ms after seal                             
Hash: 3e7f7683822ddd9b976a
Version: webpack 4.19.1
Time: 17582ms
Built at: 12/27/2018 7:59:10 PM
                                         Asset       Size   Chunks  Chunk Names
                pause.5aa1c315fa966ea144c1.gif  142 bytes           
                          3rdpartylicenses.txt   2.51 KiB           
fontawesome-webfont.af7ae505a9eed503f8b8.woff2   75.4 KiB           
 fontawesome-webfont.fee66e712a8a08eef580.woff   95.7 KiB           
  fontawesome-webfont.b06871f281fee6b241d6.ttf    162 KiB           
  fontawesome-webfont.912ec66d7572ff821749.svg    434 KiB           
              loading.2da0807814ad64841cd5.gif   1.65 KiB           
           processing.68110b18c97c78c295ff.gif   3.13 KiB           
                 edit.1115b1192665d62c2c0f.gif  150 bytes           
                trash.656f8f6e62f50c52741e.gif  159 bytes           
                retry.291dd47bf94604e664eb.gif  173 bytes           
             continue.1cb65b42ecd454657c4f.gif  221 bytes           
  fontawesome-webfont.674f50d287a8c48dc19b.eot    162 KiB           
             login-bg.c515c4d94b3ddb7e64b0.png    441 KiB           
           data-table.bce071e976865da51100.eot   2.46 KiB           
                flags.416250f60d785a2e02f1.png   69.2 KiB           
             flags@2x.d429a5777afaf2fc3496.png    170 KiB           
          data-table.246ea8fa6c452b0f3c4f.woff   1.59 KiB           
           data-table.c8c6d300cb7abb9f36e8.ttf    2.3 KiB           
           data-table.b0aebd744ce7adb780a9.svg    2.6 KiB           
               runtime.ec2944dd8b20ec099bf3.js   1.41 KiB        0  runtime
                  main.9868d9b237c3a48c54da.js  128 bytes        1  main
             polyfills.85f47f0bf59079cbc23a.js  130 bytes        2  polyfills
               styles.cef61bd5ae567ae615b0.css    237 KiB        3  styles
               scripts.7dc20ca29d0eaaa46985.js    596 KiB  scripts  scripts
Entrypoint main = runtime.ec2944dd8b20ec099bf3.js main.9868d9b237c3a48c54da.js
Entrypoint polyfills = runtime.ec2944dd8b20ec099bf3.js polyfills.85f47f0bf59079cbc23a.js
Entrypoint styles = runtime.ec2944dd8b20ec099bf3.js styles.cef61bd5ae567ae615b0.css
Entrypoint scripts = scripts.7dc20ca29d0eaaa46985.js
chunk {scripts} scripts.7dc20ca29d0eaaa46985.js (scripts) 0 bytes [rendered]
chunk    {0} runtime.ec2944dd8b20ec099bf3.js (runtime) 0 bytes ={1}= ={2}= ={3}= [entry] [rendered]
chunk    {1} main.9868d9b237c3a48c54da.js (main) 28 bytes ={0}= [initial] [rendered]
chunk    {2} polyfills.85f47f0bf59079cbc23a.js (polyfills) 28 bytes ={0}= [initial] [rendered]
chunk    {3} styles.cef61bd5ae567ae615b0.css (styles) 371 KiB ={0}= [initial] [rendered]

WARNING in Terser Plugin: Dropping side-effect-free statement [scripts.7dc20ca29d0eaaa46985.js:2,65276]

WARNING in Terser Plugin: Dropping unreachable code [scripts.7dc20ca29d0eaaa46985.js:2,82142]

WARNING in Terser Plugin: Declarations in unreachable code! [scripts.7dc20ca29d0eaaa46985.js:2,82142]

WARNING in Terser Plugin: Dropping unused variable b [scripts.7dc20ca29d0eaaa46985.js:2,862]

WARNING in Terser Plugin: Dropping side-effect-free statement [scripts.7dc20ca29d0eaaa46985.js:10,8162]

WARNING in Terser Plugin: Dropping unreachable code [scripts.7dc20ca29d0eaaa46985.js:10,435206]

WARNING in Terser Plugin: Declarations in unreachable code! [scripts.7dc20ca29d0eaaa46985.js:10,435206]

WARNING in Terser Plugin: Dropping side-effect-free statement [scripts.7dc20ca29d0eaaa46985.js:10,499482]

ERROR in Maximum call stack size exceeded
Child mini-css-extract-plugin node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!node_modules/postcss-loader/src/index.js??extracted!g/public/common/theme.css:
                   Asset      Size  Chunks  Chunk Names
    3rdpartylicenses.txt  1.38 KiB          
    Entrypoint mini-css-extract-plugin = *
    chunk    {0} * (mini-css-extract-plugin) 63.3 KiB [entry] [rendered]
Child mini-css-extract-plugin node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!node_modules/postcss-loader/src/index.js??extracted!node_modules/flatpickr/dist/flatpickr.min.css:
                   Asset      Size  Chunks  Chunk Names
    3rdpartylicenses.txt  1.07 KiB          
    Entrypoint mini-css-extract-plugin = *
    chunk    {0} * (mini-css-extract-plugin) 14.6 KiB [entry] [rendered]
Child mini-css-extract-plugin node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!node_modules/postcss-loader/src/index.js??extracted!node_modules/font-awesome/css/font-awesome.css:
                   Asset      Size  Chunks  Chunk Names
    3rdpartylicenses.txt  2.51 KiB          
    Entrypoint mini-css-extract-plugin = *
    chunk    {0} * (mini-css-extract-plugin) 40.8 KiB [entry] [rendered]
Child mini-css-extract-plugin node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!node_modules/postcss-loader/src/index.js??extracted!node_modules/froala-editor/css/froala_editor.pkgd.min.css:
                   Asset      Size  Chunks  Chunk Names
    3rdpartylicenses.txt  1.38 KiB          
    Entrypoint mini-css-extract-plugin = *
    chunk    {0} * (mini-css-extract-plugin) 56.5 KiB [entry] [rendered]
Child mini-css-extract-plugin node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!node_modules/postcss-loader/src/index.js??extracted!node_modules/froala-editor/css/froala_style.min.css:
                   Asset      Size  Chunks  Chunk Names
    3rdpartylicenses.txt  1.38 KiB          
    Entrypoint mini-css-extract-plugin = *
    chunk    {0} * (mini-css-extract-plugin) 7.67 KiB [entry] [rendered]
Child mini-css-extract-plugin node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!node_modules/postcss-loader/src/index.js??extracted!node_modules/sass-loader/lib/loader.js??ref--14-3!src/main.scss:
                   Asset      Size  Chunks  Chunk Names
    3rdpartylicenses.txt  2.51 KiB          
    Entrypoint mini-css-extract-plugin = *
    chunk    {0} * (mini-css-extract-plugin) 202 KiB [entry] [rendered]

WARNING in Terser Plugin: Dropping side-effect-free statement [scripts.7dc20ca29d0eaaa46985.js:2,65276]

WARNING in Terser Plugin: Dropping unreachable code [scripts.7dc20ca29d0eaaa46985.js:2,82142]

WARNING in Terser Plugin: Declarations in unreachable code! [scripts.7dc20ca29d0eaaa46985.js:2,82142]

WARNING in Terser Plugin: Dropping unused variable b [scripts.7dc20ca29d0eaaa46985.js:2,862]

WARNING in Terser Plugin: Dropping side-effect-free statement [scripts.7dc20ca29d0eaaa46985.js:10,8162]

WARNING in Terser Plugin: Dropping unreachable code [scripts.7dc20ca29d0eaaa46985.js:10,435206]

WARNING in Terser Plugin: Declarations in unreachable code! [scripts.7dc20ca29d0eaaa46985.js:10,435206]

WARNING in Terser Plugin: Dropping side-effect-free statement [scripts.7dc20ca29d0eaaa46985.js:10,499482]

ERROR in Maximum call stack size exceeded

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 7.0.7
Node: 10.12.0
OS: darwin x64
Angular: 7.1.4
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.10.7
@angular-devkit/build-angular     0.10.7
@angular-devkit/build-optimizer   0.10.7
@angular-devkit/build-webpack     0.10.7
@angular-devkit/core              7.0.7
@angular-devkit/schematics        7.0.7
@angular/cdk                      7.2.0
@angular/cli                      7.0.7
@angular/flex-layout              7.0.0-beta.22
@angular/material                 7.2.0
@ngtools/webpack                  7.0.7
@schematics/angular               7.0.7
@schematics/update                0.10.7
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.19.1
</code></pre>

**Anything else relevant?**
I have tried with multiple permutations and combinations , ng build --prod is failing only when I include a module with greater than 500kB

**Comment by benlesh** [comment] 2018-12-28 01:00
This appears to be an issue with the Angular-CLI. I've filed [an issue there](https://github.com/angular/angular-cli/issues/13321)... Also, it may be a duplicate of any number of closed issues, such as [this one](https://github.com/angular/angular-cli/issues/5427)

**Closed by benlesh** 2018-12-28 01:00 UTC

**Comment by SANTOSHKVNSP** [comment] 2018-12-28 04:43
Hi @benlesh , the issue you referred has issue even in ng serve and ng build, I am facing only when it I am doing a build with aot. The main reason for the issue is , some of the lazyloaded modules are more than 500kb . With Aot do we have any limit for lazy loaded modules?
