### ISSUE TITLE
Docs(aio). Error in initial(first) loading in code example of Dynamic Component Loader guide

### ISSUE THREAD

**Issue by Yerkon** [angular/angular#22020] opened 2018-02-05 06:08 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

In [this](https://angular.io/guide/dynamic-component-loader) guide.
 - Initial loading of this [code example](https://stackblitz.com/angular/jaaavxqpbpjk) throws error on console: 
` ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'null: undefined'. Current value: 'null: Bombasto'. It seems like the view has been created after its parent and its children have been dirty checked. Has it been created in a change detection hook ?`

-  Example is not visible in browser
## Expected behavior

1.First loading without error.
### ad-banner.component.ts ngAfterViewInit() wrap two method calls into setTimeout()
```
ngAfterViewInit() {
    this.loadComponent();
      this.getAds();
  } 
```
to => 
```
ngAfterViewInit() {
    setTimeout(() => {
      this.loadComponent();
      this.getAds();
    }, 0);
  }
```
2. Replace in template div css class to another, class  != ad-banner. For example ad-banner1
update `sample.css` too
Then it should work:
https://stackblitz.com/edit/angular-fqhtg3?file=src%2Fapp%2Fad-banner.component.ts

**Comment by trotyl** [comment] 2018-02-05 06:15
Duplicate of #21903

**Closed** 2018-02-05 11:05 UTC
