### ISSUE TITLE
 Table overriding main content block

### ISSUE THREAD

**Issue by akib1997** [angular/angular#51469] opened 2023-08-23 07:53 UTC
### Describe the problem that you experienced

In angular documentation, the full main block is scrollable for table content. For example: [This Page](https://angular.io/guide/reactive-forms#reactive-forms)

Youtube:
[Video](https://youtu.be/xOW35W0KDXU)

### Enter the URL of the topic with the problem

https://angular.io/guide/reactive-forms

### Describe what you were looking for in the documentation

The table should be scrollable within his area, not his parent area. 

Youtube: [Video](https://youtu.be/xOW35W0KDXU)

### Describe the actions that led you to experience the problem

Reading documentation.

### Describe what you want to experience that would fix the problem

https://youtu.be/xOW35W0KDXU

### Add a screenshot if that helps illustrate the problem

[YouTube Video](https://youtu.be/xOW35W0KDXU)

**Comment by akib1997** [comment] 2023-08-23 07:54
PR Submitted:
https://github.com/angular/angular/pull/51468

**Comment by JeanMeche** [comment] 2023-08-23 13:26
I'll close this as a dupe of #45121

**Closed by JeanMeche** 2023-08-23 13:26 UTC
