### ISSUE TITLE
Router - back button does not work properly

### ISSUE THREAD

**Issue by ludohenin** [angular/angular#2201] opened 2015-05-28 15:25 UTC
Back button works well if only one route is navigated (renders the previous view). But if more than one route is followed, nothing happen when clicking the back button.
History is also not maintained, it is impossible to go forward.

**Comment by btford** [comment] 2015-07-17 06:58
What version of Angular?

And is there any chance you could provide a reproduction via [jsbin](http://jsbin.com/), [plnkr.co](http://plnkr.co), or [jsfiddle](http://jsfiddle.net/)?

This would be helpful in verifying the bug. Thanks!

**Comment by Zyzle** [comment] 2015-07-17 08:01
I couldn't get my example to work on plnkr but a the simplest example I could come up with is here:

https://gist.github.com/Zyzle/7413efdf86e6fc7c0bfe

**Comment by btford** [comment] 2015-07-17 19:28
I suspect that the problem is that `Router` calls `pushState` again after a navigation resulting from a popState event.

**Comment by matsko** [comment] 2015-07-27 17:37
@btford I'll take over this issue since the issue was shortlisted in your email last week.

**Comment by matsko** [comment] 2015-07-28 19:47
The bug was discovered and there is a PR waiting to be merged in that fixes it.

**Closed** 2015-08-03 23:21 UTC
Labels: comp: router, effort2: medium (day), P2: required, type: bug

**Comment by btford** [comment] 2015-08-04 23:58
This will land in alpha-34 in the next couple days.
