### ISSUE TITLE
Allow attaching RouterLink to custom components without click handling

### ISSUE THREAD

**Issue by jasonbaker** [angular/angular#24482] opened 2018-06-13 16:46 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Currently, there are only two choices for routerLink:
 * One that attaches an href attribute to a link
 * One that adds a click handler

However, sometimes it's helpful to be able to design a component that takes a URL as an input without it being an actual `<a>` tag or having an extra click handler attached.

## Expected behavior
An example of using this could be something like the following:

`<my-component [routerLink]="myUrl" queryParamsHandling="merge"></my-component>`

This would behave similarly to a `RouterLink` attached to an `<a>` tag in that it attaches an href attribute to be passed in to `my-component`.

## What is the motivation / use case for changing the behavior?

It's challenging to design a component that needs to pass information through to a `RouterLink` without requiring a lot of pass-through parameters. Being able to attach a `RouterLink` to a component would allow developers to design components without requiring users of their components to use a `UrlTree` or using a lot of pass-through parameters.

**Comment by jasonaden** [comment] 2018-06-19 23:02
Thanks for the issue. Can you provide more examples of the problem you're trying to solve? It seems like you want to use a `routerLink` inside `MyComponent`, but get the information for that `routerLink` from a property of `MyComponent`. Is that correct? Can you come up with some more simple examples of how you are achieving this today and what the problem is with that solution?

I want to make sure before just marking this as a feature request that I understand the problem you're trying to solve.

**Comment by jasonaden** [comment] 2018-06-26 22:54
We clarified this offline. The best solution for now is to pass through the parameters, even though it seems a bit tedious. This is a current restriction in Angular, but this might be something that changes with Ivy.

**Closed by jasonaden** 2018-06-26 22:54 UTC
Labels: comp: router
