### ISSUE TITLE
Angular 0.16 refresh issues onPush

### ISSUE THREAD

**Issue by born2net** [angular/angular#8295] opened 2016-04-27 20:24 UTC
In 0.16 I am seeing that my components that are set to change detection onPush not updating the UI upon mouse clicks... is anyone else seeing the same issue?

FYI
I am using Redux and my updates come from the store using Immutable.js models
Up to 0.15 all was great!

regards

Sean.

**Comment by mdudek** [comment] 2016-04-28 07:08
Hi @born2net , this issue is already mentioned in #8242.

**Comment by pkozlowski-opensource** [comment] 2016-04-28 07:48
@born2net your issue doesn't have any details that would help us to reproduce the problem and it sounds similar / the same as #8242. I'm going to close this one as a duplicate of #8242 as it has a reproduce scenario. 

If you believe that this one is different from #8242 please open a new issue _with a minimal reprodice scenario in plunker_.

**Closed by pkozlowski-opensource** 2016-04-28 07:48 UTC

**Comment by born2net** [comment] 2016-04-28 14:00
yes seems duplicate, tx...
