### ISSUE TITLE
HttpHeaders.applyUpdate : Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by dimitribocquet** [angular/angular#18743] opened 2017-08-17 07:11 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I'm using new HttpClientModule with an interceptor to set a default application/json Content-Type when it's not defined. Then, I'm trying to upload a file (with formData), so I set the Content-Type header to undefined. But my interceptor throws me an error  : `Cannot read property 'length' of undefined`.

## Expected behavior

If we set a header to undefined, has/get function must return true or false, instead of throwing an error.

## Minimal reproduction of the problem with instructions

[My plunker](http://plnkr.co/edit/kc6Ak1VwdgVir4HWFUCd?p=preview). Open the console to see the error. The second button throws it.

## Environment

<pre><code>
Angular version: 4.3.5

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.1.3  
- Platform:  Mac 

Others:

</code></pre>

**Comment by alxhub** [comment] 2017-08-17 22:49
Passing `undefined` as a value to `HttpHeaders.set` is not legal per the typings:

```javascript
set(name: string, value: string|string[]): HttpHeaders
```

Note the type allowed is `string|string[]`, not `string|string[]|undefined`. Turning on strict type checking may help reveal these kinds of errors in your code.

**Comment by alxhub** [comment] 2017-08-30 18:26
Closing as WAI - the usage in the reproduction would not pass Typescript's strict mode.

**Closed by alxhub** 2017-08-30 18:26 UTC
Labels: comp: common/http, type: bug

**Comment by SpeedShifter** [comment] 2018-02-02 15:42
Just to note, that it's not obvious and TS is not helping in next case:

`(req as HttpRequest<any>).clone({
          setHeaders: {
            'auth': token
          }
        })`

**Comment by AlanObject** [comment] 2018-02-03 18:56
This one bit me.  In my app when the application started or the user logged out I was setting the "Authorization" field to null.  Since the value was a parameter TS would not have caught it. 

Would it be right to update the set function so that a null value as its parameter would result in the header field being removed?

**Comment by MaximeMorin** [comment] 2018-02-22 16:42
We had the same issue as Alan.  An header variable was set to null and angular failed on .length().

I think it's that line.
https://github.com/angular/angular/blob/5.2.6/packages/common/http/src/headers.ts#L72

**Comment by dwdewul** [comment] 2018-04-28 02:12
Confirmed that I receive an error in Chrome, but not in Edge.

Chrome version: Version 65.0.3325.181 (Official Build) (64-bit)

Edge Version: Microsoft Edge 41.16299.248.0

The code in question: 
`checkToken() {
    const token = localStorage.getItem('token');
    return this.http.get('http://localhost:3000/user/me', {
      headers: {
        'Authorization': localStorage.getItem('token')
      }
    });
  }`

Let me know if you require more information.

**Comment by unstephenk** [comment] 2018-07-01 02:08
I am having the issue too. My code looks just like what @dwdewul

**Comment by FirassKoubaa** [comment] 2018-07-13 11:39
+1

**Comment by trotyl** [comment] 2018-07-13 12:05
This is the intended behavior, a header value can only be `string`, not `null`/`undefined`, you'll already got compile-time error if `strictNullCheck` enabled. You need to guard against `null`/`undefined` when needed. For example:

```typescript
if (localStorage.hasItem('token')) {
  const token = localStorage.getItem('token')
  // ...
}
```

**Comment by MaximeMorin** [comment] 2018-07-13 12:43
@trotyl I mean no offence, but I find it ironic that you are telling us to guard against null / undefined when needed.  Yet, it's clearly not done in the framework.

**Comment by SpeedShifter** [comment] 2018-07-13 12:51
@trotyl Im not asking framework to guard me, but it would be nice to let me know (meaningful exception message or documentation), that I should check values, because it will fail.

**Comment by dvhuy** [comment] 2018-10-14 09:33
It still happens sometime. It clear browser cache then i works well.

I also check header request but no-property is _undefined_.

Wierd issue

**Comment by dvhuy** [comment] 2018-10-14 09:34
I'm using Chrome lastest  version and Angular '6.1.0'

**Comment by trotyl** [comment] 2018-10-14 10:13
@SpeedShifter Generally it doesn't make sense to check against usage already forbidden by static typing, but given `strictNullChecks` is not a requirement in Angular project, agreed it's reasonable to have a runtime check first.
