### ISSUE TITLE
A developer friendly way to apply classes to host component element

### ISSUE THREAD

**Issue by ghndr** [angular/angular#42942] opened 2021-07-23 11:08 UTC
### Which @angular/* package(s) are relevant/releated to the feature request?

_@angular/core_

### Backstory

_I come from a Reactjs background and I find it very frustrating that I can't remove the host element of a component (React has Fragments that wrap the component and don't actually render anything on the page)_

I researched ways to remove the host component and I found a working [example](https://stackblitz.com/edit/angular-remove-host?file=src%2Fapp%2Fsplice-content.directive.ts)

*splice-content.directive.ts*
```ts
import { Directive,ElementRef } from '@angular/core';

@Directive({
  selector: '[splice-content]'
})
export class SpliceContentDirective {

      constructor(private el: ElementRef) { }

    ngOnInit() {
        var nativeElement: HTMLElement = this.el.nativeElement,
            parentElement: HTMLElement = nativeElement.parentElement;
        while (nativeElement.firstChild) {
            parentElement.insertBefore(nativeElement.firstChild, nativeElement);
        }
        parentElement.removeChild(nativeElement);
    }

}
```

But I also discovered that it causes a lot of **issues** when things start getting a little more serious (*ngFor kind of serious), and apparently that's the reason why Angular 2 doesn't support this natively.

The problem is that without this, adding classes to the host element is a very tedious task, for example here I'm using Tailwindcss with TailwindUI components and I'm trying to have my page render properly, but to do so, I need to do this 

*sidebar.component.ts*
```ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-side-bar',
  templateUrl: './side-bar.component.html',
  styleUrls: ['./side-bar.component.css'],
  host: {
    class:
      'flex flex-col flex-grow border-r border-gray-200 pt-5 pb-4 bg-white overflow-y-auto',
  },
})
export class SideBarComponent implements OnInit {
  constructor() {}

  ngOnInit(): void {}
}

```

surely  doing this one time is okay, no biggie, but doing it multiple times, is gonna be a pain, and what if I want to add another `div` that wraps my component, I'm gonna have to move those classes from this
```ts
host: {
    class:
      'flex flex-col flex-grow border-r border-gray-200 pt-5 pb-4 bg-white overflow-y-auto',
  },
```
to the new `div` that I created then I'll need to put the new classes that are intended for the new `div` in the `host: { class: '' }`

but why not make everyone's life easier without removing the wrapping host component ?

### Proposed solution

**My proposed solution would be something like this**

*sidebar.component.html*
```html
<!-- the magical wrapper component that transfers the classes and the element type passed to it
automatically to the host element that is generated by angular -->
<ng-host div class="flex flex-col flex-grow border-r border-gray-200 pt-5 pb-4 bg-white overflow-y-auto">
  <div class="...">
      <!-- component -->
  </div>
</ng-host>

```

and that would translate what the result of this would be
```ts
host: {
    class:
      'flex flex-col flex-grow border-r border-gray-200 pt-5 pb-4 bg-white overflow-y-auto',
  },
```

so it's the same result minus the pain.

### Alternatives considered

**Alternatively this would probably be better, but this is pretty much removing the parent component, so not sure if this is feasible**

*sidebar.component.html*
```html
<!-- The element with the ngHost directive, would then become the host component -->
<div ngHost class="flex flex-col flex-grow border-r border-gray-200 pt-5 pb-4 bg-white overflow-y-auto">
  <div class="...">
      <!-- component... -->
  </div>
</ng-host>

```

**Comment by pkozlowski-opensource** [comment] 2021-07-23 12:52
Similar ideas are already being discussed in other issues, most notably: 
* #19119 (sounds like _almost_ the exact duplicate of your idea)
* #18877 (removal of the host element, now closed)

We are very well aware of the [issues people bump into when dealing with the host element](https://github.com/angular/angular/issues?q=is%3Aissue+label%3A%22comp%3A+core%22+label%3A%22core%3A+host+and+host+bindings%22+is%3Aopen) and trying to come up with the suitable mental model / API. But it should be noted that Angular "thinks" about the host node _very_ differently than React so it is hard to transfer ideas from one framework to another.

 I'm going to close this issue as the duplicate of #19119 to centralize the discussion. But yeh, we would love to make things easier around the host element...

**Closed by pkozlowski-opensource** 2021-07-23 12:52 UTC

**Comment by ghndr** [comment] 2021-07-23 13:36
I actually looked for any open issues about this, and couldn't find any, I think the title should be updated from just "ng-host" to something more descriptive (maybe add **host**, **:host**, **HostBinding** to the title) so it is easily found.

otherwise, I'm glad to see you're already considering this.
