### ISSUE TITLE
The value of form element is not synced with control after sorting.

### ISSUE THREAD

**Issue by victos** [angular/angular#47226] opened 2022-08-23 05:41 UTC
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

No

### Description

After I sorting the data of a form, the value of the form element is not updated accordingly.
![Screenshot_select-area_20220823133602](https://user-images.githubusercontent.com/3107600/186078613-6da5d142-c3e6-416d-a627-27bd512cec46.png)
![Screenshot_select-area_20220823133731](https://user-images.githubusercontent.com/3107600/186078626-bb916bd4-7ecc-4374-8f1b-b9a3d5e7439b.png)

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-royzqy?file=src/app/app.component.html

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 14.0.7
Node: 16.14.2
Package Manager: npm 7.17.0 
OS: linux x64

Angular: 14.1.3
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1401.3
@angular-devkit/build-angular   14.1.3
@angular-devkit/core            14.1.3
@angular-devkit/schematics      14.0.7
@angular/cli                    14.0.7
@schematics/angular             14.0.7
rxjs                            7.5.6
typescript                      4.7.4
```

### Anything else?

Affects version: 13.2.2 and later

**Comment by jnizet** [comment] 2022-08-23 06:07
I'll let someone from the team decide if it's a bug or not, but a workaround is to name the inputs with a name associated to the product:`<input [name]="'price-' + prod.id"`.

**Comment by liesahead** [comment] 2022-08-23 06:51
I suppose you're missing `trackBy` function. You can generate some tracking key like `String(Math.random()).slice(2);` or in some other way.

**Comment by JoostK** [comment] 2022-09-06 18:43
I couldn't originally find the issue which I thought this was a duplicate of, but I just did: #45647 is the same problem.

**Closed by JoostK** 2022-09-06 18:43 UTC
Labels: comp: forms
