### ISSUE TITLE
Compiler.js hangs for a long time. (JIT and when Chrome devtools are open)

### ISSUE THREAD

**Issue by gidon-handler** [angular/angular#32035] opened 2019-08-07 10:09 UTC
My environment :
Windows 10
Chrome 76
Angular 8.0.2

When in development (ng serve with defualt JIT) when the Chrome devtools are open, the reload of angular hangs for a very long time. 
It seems that all the time is beening spent in the Angular compiler.js.

Our project has about 50 Components that are loaded in the main AppModule.
Lazy Loaded Modules encounter the same issue.

This was not always the issue, might have started after a Chrome update.
Makes it very hard to develop

**Comment by alxhub** [comment] 2019-08-08 22:53
Hello @gidon-handler,

Unfortunately we won't be able to do much with this issue unless you're able to provide us a reproduction which demonstrates the problem (likely in the form of a Github repository we can clone/investigate).

**Comment by gidon-handler** [comment] 2019-08-09 09:17
Hi Alex.
Thanks for the quick replay.
Unfortunetly, the mentioned app is an internal undisclosed HP app and I am not in the liberty of sharing that repo.
It would however be a great help, and much appreciated by our team if we could rule out an angular/compiler.js issue.
This would meen knowing that any app with a decent amount of components (I'm sure Angular.io would do) reloads normaly while running ng server (with defualt JIT) , and while Chrome devtools are open.

**Comment by jydarche** [comment] 2019-08-12 17:09
It seems that I have the same problem. It started when we updated Chrome from version 75 to version 76 and it happens when the devtools are open. Because of that, I'm not sure if it is something that can/must be corrected on the Angular side.

My environment :
Windows 10
Chrome 76
Angular 7.2.13

**Comment by alxhub** [comment] 2019-08-15 22:29
Yeah, that's my intuition. I would open a bug with the Chrome team. I don't know if there's anything we can do about this on the Angular side.

On the plus side, the Ivy compiler should be far more resistant to this problem.

I'm going to close this issue as it's not actionable for us, but please feel free to continue discussing here (and post a link to the Chrome bug if you file one).

**Closed by alxhub** 2019-08-15 22:29 UTC
Labels: comp: compiler, freq1: low, severity2: inconvenient, state: Needs repro, type: bug/fix
