### ISSUE TITLE
[router] RC1 Cannot navigate to child pages directly if routerLink is generated using ngFor

### ISSUE THREAD

**Issue by ajayambre** [angular/angular#8567] opened 2016-05-10 11:08 UTC
**Steps to reproduce and a minimal demo of the problem**

Demo link:
http://plnkr.co/edit/IcpghBVmxzvWAyzTF16z?p=preview_

_What steps should we try in your demo to see the problem?_
Steps to reproduce:
1) Open console log
2) Click Home link
3) Click Module1 link
4) Click Module 2 link

**Current behavior**
Also entering home/module/1/screen/Screen2 in url bar to directly navigate to that page fails and the same TypeError is seen in the console log.
(Note: Plnkr does not allow to change links the url bar, so need to download code and try this).

**Expected/desired behavior**
User should be able to directly navigate to home/module/1/screen/Screen2 and there should not be errors in the console log even if the links are generated dynamically using *ngFor.

**Other information**
Screenshot 
![image](https://cloud.githubusercontent.com/assets/5074211/15144392/b83975fa-16cc-11e6-9e55-43bb2c8ee977.png)

**Comment by zoechi** [comment] 2016-05-10 11:37
The issue is not related to `*ngFor`. If you add the links statically you get the same exception.

If you prefix the path with `/` the error goes away and navigation works. http://plnkr.co/edit/6rsyaYLdRjDTdQydEO4o?p=preview 
I can't explain why though ;-)

**Comment by ajayambre** [comment] 2016-05-10 14:38
Clicking on the module links works but I think you broke the screen level links.
Getting below error in console:
![image](https://cloud.githubusercontent.com/assets/5074211/15150470/f24d9c80-16ea-11e6-981f-80387c0b418c.png)

**Comment by ajayambre** [comment] 2016-05-10 14:44
I have updated the plnkr and it works fine with static links:
http://plnkr.co/edit/IcpghBVmxzvWAyzTF16z?p=preview

The problem occurs only when I create the routeLinks with *ngFor. 
Comment the static links and uncomment the ngFor section to reproduce.

**Comment by zoechi** [comment] 2016-05-10 16:39
I see it now. Seems to be caused when this line is reached https://github.com/angular/angular/blob/b30ddfbfc5192f526ceaac525cf6965635831c46/modules/%40angular/router/src/segments.ts#L64

**Comment by dagstuan** [comment] 2016-05-12 11:53
I have the same issue, I dont think it's related to `*ngFor` though, since I can create a list in my component manually and populate the list that way without errors. For me the exact same stack trace shows up when I get data from a service instead of hard-coding it into my component.

**Comment by ajayambre** [comment] 2016-05-12 14:17
@dagstuan Can you please share a plnkr demo of it?

**Comment by dagstuan** [comment] 2016-05-13 08:01
@ajayambre I have created a plnkr of my issue.

Instructions:
1. Navigate to the "second home"
2. Wait for the API-call to return the list of rooms
3. Navigate back to "home"

Check the console, the same error should appear then.

http://plnkr.co/edit/x5IKxMvdkh9KMH0hd8bh?p=preview

**Comment by ajayambre** [comment] 2016-05-13 08:33
@dagstuan Yes I see exact same behavior.
This is similar to what I have, its just that I am directly assigning the menus in ngOnInit and you are fetching them from a service.
I understand that this might not be exactly related to <code>*ngFor</code> but then when you get your routes lazily you need to use <code>*ngFor</code> to generate your route links.
May be I should change the issue title. You can suggest one. Thanks :)

**Comment by dagstuan** [comment] 2016-05-13 08:52
I'm not really sure what the title should be, given that I dont fully understand the bug yet. I noticed when making the plnkr that if the API only returns one result it works correctly without the error, so its related to multiple routes at least.

**Comment by dagstuan** [comment] 2016-05-13 10:17
It seems like the issue is related to relative routes in my case at least, if I change the routes in `secondHome.ts` to not be relative the issue goes away.

Updated plnkr: http://plnkr.co/edit/x5IKxMvdkh9KMH0hd8bh?p=preview

**Comment by MrCroft** [comment] 2016-05-17 22:28
@dagstuan I'm not sure if the last plnkr link should have the demo in which "the issue went away"... I've just accessed it and if I click on "Second home" and then on "Home", the error still shows up.

**Comment by dagstuan** [comment] 2016-05-18 06:38
@MrCroft if you look in the second demo in the file `secondHome.ts` you'll find code that can be uncommented to fix the issue, I just left the broken code uncommented initially :)

**Comment by ajayambre** [comment] 2016-06-17 04:54
As per #9257, I think we can close this now as the router is anyways abandoned and we should not expect any more fixes for it. Please start using new router. Latest docs available at https://angular.io/docs/ts/latest/guide/router.html

**Comment by vsavkin** [comment] 2016-06-29 00:57
Closing as the issue is not present in the new router.

**Closed by vsavkin** 2016-06-29 00:57 UTC
Labels: comp: router
