### ISSUE TITLE
Discussion: Rename DI Bindings into Providers

### ISSUE THREAD

**Issue by vsavkin** [angular/angular#4416] opened 2015-09-29 20:58 UTC
Using the same word "binding" for two core ideas of the framework causes some confusion. 

Proposal: Rename Binding into Provider, and bindings into providers.

```
@Component({
  providers: [
    // the constructor version  
    new Provider(Http, {toClass: CustomHttp}),

    // using builder
    provide(Http).viaFactory(customFactory),

    // using a different type of builder
    provide(Http, {value: customFactory})
  ]
})
```

Pros:
* Similar to Angular 1
* Binding means only data-bindings

Cons:
* Different from other DI systems, which mostly use the word binding

@IgorMinar @mhevery

**Comment by hess-google** [comment] 2015-09-29 21:12
+1. I was just writing up my observations on my first 2+ week deep-dive into Angular 2, and one of them was:
_Overloaded terminology may cause confusion when learning the framework._
“A component has property and event bindings” ([ref](http://victorsavkin.com/post/118372404541/the-core-concepts-of-angular-2))...but also has a property ‘bindings’ which is its private dependency injector.

Related to this issue, options on [this discussion about annotating for emitting metadata](https://github.com/angular/angular/issues/4404#issuecomment-144111970), this change might lean that in favor of something like: 

    @ProviderConsumer
    class DataService {
      constructor(http: Http) {
      }
    }

**Comment by vicb** [comment] 2015-09-29 22:08
I'm with @vsavkin on this.

I think it would help with `@HostBinding` (we can then keep this name). I was thinking about this renaming when submitting the issue about `HostBinding` but didn't end up proposing because `bind` seems like a common terminology for DI (see Guice) - I personally don't mind dropping `bind`.

We should rename `toXXX` as well: `new Provider(Http, {toClass: CustomHttp})` does not sound right.

**Comment by PascalPrecht** [comment] 2015-09-29 22:15
Think it would be `viaValue()` and `viaClass()` then. I understand why
renaming that concept (yet) again might be good. But we should keep in mind
that people got used to the term "binding" now. Also, using the term
"provider" might make people think that we have the concept of providers
like in A1 again...

Although otoh that's what a provider is somehow all about, even in A1.

**Comment by PascalPrecht** [comment] 2015-09-29 22:21
@hess-google I think you're confusing two different things here. Providing
a binding for DI and injecting something are not the same thing. I don't
think that this renaming will help with the enforcing of emitting metadata
in typescript.

However, I do agree that "binding" is a heavily overloaded term in A2

**Comment by robwormald** [comment] 2015-09-29 22:43
I've long thought this was sort of confusing too. That said, I feel like "providers" as key sort of isn't much better. 

I've just been referring to things as "services" and "components", personally. So:

```
@Component({
  services: [ 
    bind(Thing).toValue({foo: 'bar' })
  ]

})
```

Most ng1 users are quite happy with the term service, I think.

**Comment by mhevery** [comment] 2015-09-29 22:57
@wardbell and @matanlurey  do you have comments? I am leaning towards changing this to `providers`

**Comment by IgorMinar** [comment] 2015-09-29 23:39
+1 for naming change, but we should take a look at the big picture view and see how this impacts all the public apis (e.g. `hostBindings`, `bindings`, is there more?)

**Comment by wardbell** [comment] 2015-09-29 23:48
I want to change it from `bindings` as well. Way overloaded. 

The problem with `providers` is that it introduces ***yet another new concept*** ... something we don't need right now.

I'm inclined toward @robwormald suggestion of `services` ... although that introduces a new concept as well albeit a familiar concept.

We already teach "dependencies" as part of Dependency Injection.

Why not call the property **`dependencies`**.  

The picayune might notice that **we sometimes have to supply an explicit binding** in the array rather than the name of a dependent thing.  I don't mind. But if someone did, then all of the suggestions fail because none of them mention bindings of any kind.

In which case, I would vote for the lengthy but accurate **`dependencyBindings`**.

**Comment by PascalPrecht** [comment] 2015-09-30 10:57
@wardbell I think `dependencies` would be too generic, since we also have a `directives` property in the `@View()` decorator, which are also some sort of dependencies. Ppl might wonder why those are not treated as "dependencies".

**Comment by mgechev** [comment] 2015-09-30 11:18
I agree that `dependencies` is too generic. `services` seems too specific. Especially if we bind to a value or a factory it doesn't make a lot of sense to me.

I'm for `providers` although I realize it may create some confusion to the users who are familiar with AngularJS 1.x.

**Comment by ericmdantas** [comment] 2015-09-30 12:41
So, we wouldn't have `viewBindings` and `bindings` anymore, it'd be just `providers`?

Also, even though it might cause some confusion at first:
`provide(Something).viaFactory(() => new SomethingElse('yay'))` sounds cool.

**Comment by PascalPrecht** [comment] 2015-09-30 12:44
It really does.

I think we'd have `providers` and `viewProviders` then.

**Comment by wardbell** [comment] 2015-09-30 16:01
As a matter of pure English and within the world of s/w, provider and dependency  are equally generic.

The biggest problem with provider is that it is yet another word in the Angular lexicon. We don't need more of those. 

What does a provider provide? How is it used? If you were to answer in this context, you would say it provides something that is injected into another thing.

We have that word already. It is called a dependency. We teach that early to every would be Ng dev.

When I read dependency my knee jerk reaction is "something that will be injected into the constructor, either tho component's constructor or the constructor of one of its dependencies."

And that is precisely the reaction we want the dev to have here.

Nothing new to learn. W seen this before. You're telling Ng what should be passes to a constructor. I get it. Done.

For these reasons... familiar term, correct instinct (instinct, nor reason) about what to do and what will happen... I favor the unambiguous `dependency`

**Comment by wardbell** [comment] 2015-09-30 16:05
My phone mangled my text. "instinct, not reason". The point being that the dev doesn't have to understand or reason about "providers". She simply knows without thinking that she must supply a thing that goes into a constructor because that's what she learned to di she she leaned dependency injection.

**Comment by wardbell** [comment] 2015-09-30 16:06
Learned to do when she

**Comment by vsavkin** [comment] 2015-09-30 17:25
@wardbell You are right, providers is yet another concept, but I thought Angular 1 developer are familiar with the notion of providers. Would not you agree?

I don't think we can use the word dependencies because the following use case.

Say we have a directive that wants to publish itself as a validator. It is reasonable to use the name provider or binding here. The directive either is a validator or provides a validator.

```
@Directive({providers: [provide(NgValidator, {toAlias: MyCustomValidator})]})
class MyCustomValidator {
}
```

It is not reasonable to call it dependency. NgValidator is not a dependency of MyCustomValidator.

```
@Directive({dependencies: [dep(NgValidator, {toAlias: MyCustomValidator})]})
class MyCustomValidator {
}
```

**Comment by wardbell** [comment] 2015-09-30 20:26
OK ... I am sold on `providers`  WITH THE PROVISO that we start talking about them early and often in the context of Dependency Injection. 

@igorMinar: We must add this "provider" term to the Glossary.

**@PascalPrecht take heed.**  We need to **start driving the term, "provider", throughout the DI chapter** so that we lock it into the developer's brain.

I'm about to think out-loud about what the revised discussion might look like.

When a part depends upon some outside thing; that thing is one of its dependencies.  The Dependency Injector can supply that dependency with the help of the dependency's corresponding "provider".

We **register providers** with the injector.   When we write `Injector.resolveAndCreate([Engine])`) we are asking the `Injector` class to

1. create a new `injector` 
2. register an `Engine` provider with that new injector. 

We register a provider with an injector by means of a **DI binding**. A DI binding is an association between a **key** and a **provider**.  It's a **a {key, provider) pair** .  When we write `bind(Engine).toClass(Engine)`) we associate the **key** (the `Engine` type) with a **provider** (the `Engine` class).

We can ask an injector to supply something by asking for it by key, e.g., `injector.get(Engine)`. The injector checks its container for an existing instance of the requested thing. If it doesn't have one, the injector asks the corresponding provider to create that thing and then adds the newly created thing to its container.

As we know, each new component instance gets its own child injector.

In general, a child injector has access to every dependency created by any of its parent injectors. When  a component instance asks for something and the child injector is unable to supply that thing by itself,  the child injector walks up the parent tree until it finds an injector that either has the requested thing or can create one using the corresponding provider.

The developer may know that no parent injector can have or make the thing it needs. Or perhaps the developer requires each child injector to have its own instance of  the required thing, In either case, the developer would specify the DI binding ... **a {key, provider) pair** ...  for that thing **in the component's `providers` array**. This is the same process and the same kind of DI binding we write when manually registering a provider with an injector

**Comment by Berkana** [comment] 2015-09-30 23:22
Well, considering your listed pros and cons, how about renaming data-bindings as such, and leaving this similar to other DI systems?

**Comment by PascalPrecht** [comment] 2015-10-01 08:42
I would rather stick with the term `token` instead of `key` since `key` has yet another meaning in the DI source code.

Other than that, I'm with you.

**Comment by PascalPrecht** [comment] 2015-10-01 08:45
Oh one last thing, we still use the term "Binding" that is passed to an injector configuration, right @wardbell ?

Because then I'm not sure if that frees up the naming entirely for #4320. @IgorMinar wdyt?

**Comment by PascalPrecht** [comment] 2015-10-01 09:50
@wardbell I'll streamline the DI guide, once this change landed in the code base..

**Comment by pkozlowski-opensource** [comment] 2015-10-01 11:27
@PascalPrecht my impression was that we are going to drop the 'binding' word from DI altogether, otherwise the confusion stays.

How about this:

````
@Directive({
    providers: [provide(Foo).usingClass(FooImpl), provide("bar").usingValue("Bar value")]
})
````

or

````
@Directive({
    providers: [provide(Foo).fromClass(FooImpl), provide("bar").fromValue("Bar value")]
})
````

**Comment by wardbell** [comment] 2015-10-01 15:52
@PascalPrecht @pkozlowski-opensource I woke up this morning regretting that I had called it `DI binding`. Wanted to rush here to update before you saw it. Too late ;-)

I don't have a problem with the word "binding" as long as it is qualified. In order to strengthen the notion of "provider" I wanted to refer to it as a **provider binding**.

It is not easy to get rid of the "bind" word.  That is the verb that associates a key/token with a provider. I'm not excited about changing that too in the expression `bind(Engine).toClass(Engine)`. 

If we rid ourselves of the term, we'd have to change that verb.  Perhaps "mapping" would do in which case we have `map(Engine).toClass(Engine)`

I also like your "using" suggestion, @PascalPrecht, although it's a bit weird to say `provide('bar')` when I'm not providing the string `bar` but rather the object in the `using` clause.  I could get over this minor discomfort.

The immediate concern is that we have another late breaking change to Angular. We'd have to steer it through quickly.  If someone really wants to ride this pony to the finish line, have at it.

Personally, I feel that the term "provider binding" will do, partly because "bind" is a traditional term in DI world and mostly because there will be very few opportunities for ambiguity. About the only time you'll mention this form of binding is when registering a provider with an injector.  I can't think of a reason to talk about it in any other context.

I thought also of the following phrasing: "Although we can write `[bind(Engine).toClass(Engine)]`,  when a class is its own key (token), we may use the shorthand expression `[Engine]`."

**Comment by wardbell** [comment] 2015-10-01 15:55
@PascalPrecht Refresh my memory on the difference between "key" and "token" in a DI context.  I have no problem with "token" if necessary. I prefer "key" because programmers are so familiar with "key/value pairs".

"key" is also faster to type because it is 60% shorter than "token"  <wink>

**Comment by wardbell** [comment] 2015-10-01 16:00
@Berkana  "data binding" is the predominant form of binding in Angular applications. It will be too painful to oblige people to use four syllables where they are used to using two. They simply will not do it.

Moreover, by calling it simply "binding" we can avoid the spelling question ... "with a hypen or no hyphen?" ... that has plagued this term since the earth cooled.

**Comment by mhevery** [comment] 2015-10-01 16:36
Just as a refresher:

1) Binding will refer to data-binding. The reason for the change is to lose the ambiguity with DI. Yes all DI systems use the word binding for providers, but they have tho luxury, because they don't have to deal with data-binding as well.  Hence forth binding refers to data.
2) DI has providers. DI configurations sets up providers. Yes, it is a bit awkward but no one has provided an alternative which is not bind. `provide(Key, {viaValue: 123})` sounds reasonable even if a bit awkward. or `provide(Key, {asValue: 123})` or even `provide(Key, {value: 123})` alternatively we could use the word resolved as in `resolve(Key, {asValue: 123})`.

```
@Component({
  providers: [
    resolve(Key, {asValue: 123}),
    resolve(Key, {usingType: SomeType}),
    resolve(Key, {aliasTo: OtherKey})
  ]
})
```

**Comment by wardbell** [comment] 2015-10-01 16:47
@mhevery  Please **no** to `resolve`.    That term is most commonly encountered with promises ... in much the way that "binding" comes up most frequently in the context of data binding.  I was already bummed out by `createAndResolve`.

I would prefer plain old `create`.  Why `createAndAnything`?  We don't do that for other classes.  It is perfectly usual to supply an optional array of stuff to create with to a constructor or a static creation method.  **As long as we're in a the mood to fix the API, can we make this change too?**

I don't much care that `resolve` is the term familiar to DI specialists. It's hard on the application developer when we have multiple meanings of words that don't appear regularly in everyday English.

I'm also not big on the nested object definition, e.g. `resolve(key, {asValue: 123)`. Maybe that has been around all the time but I don't remember seeing it used.

I concede that it is marginally easier to compose programmatically. But that isn't common practice and this expression is hard on the eyes.  The DSL is so much nicer:  `bind(key).toValue(provider)`.

Perhaps you're saying that the DSL expands to the object notation under the hood. That's OK.

**Comment by pkozlowski-opensource** [comment] 2015-10-01 17:05
> I also like your "using" suggestion, @pkozlowski-opensource , although it's a bit weird to say provide('bar') when I'm not providing the string bar but rather the object in the using clause. I could get over this minor discomfort.

@wardbell IMO `provide('bar')` will be quite rare in practice, IMO. I would expect that most people will use sth like `provide(Foo).fromClass(FooImpl)` where `Foo` is an "interface". In this case I truly do provide `Foo` (interface should be the only thing that a user of Foo cares about).

Agree on _not_  using `resolve` - used already in a different context.

**Comment by mhevery** [comment] 2015-10-01 17:17
ok we don't have to do `resolve` I was just throwing it out there. So let's stick with `provide`

The reason we are going against DSL is this:

`provide(Key).asValue(123)` Works OK.
`provide(Key)` Missing method call is tricky to detect but possible. No compile time error.
`provide(Key, {multi: true}).asValue(123)` Is just awkward.
`provide(Key, {asValue(123), multi: true})` Is equally readable as DSL, but does not suffer from any of the issues.

**Comment by todoubaba** [comment] 2015-10-01 17:21
What about just config with [key, factory] tuple array?
```typescript
@Component({
  providers: [
    ['value', () => 123],
    [Foo, () => FooImp],
    [Token, (key) => { ...  return obj;}],
    [MultiToken, true, () => 123],
  ]
})
```

**Comment by pkozlowski-opensource** [comment] 2015-10-01 17:31
> provide(Key, {multi: true}).asValue(123) Is just awkward.

Agreed. I was toying with the `provide(Key).asValue(123).multi` (where `multi` could be implemented as a getter?) or `provide(Key).multi.asValue(123)` but I'm not sure how I feel about it :-)

**Comment by wardbell** [comment] 2015-10-01 21:23
I'm cool with `provide`.  I could survive w/o the DSL; tricky injector configuration isn't something we do a lot. I am cool with it ... IF ... we keep the simple `[Engine]` special case so that the 90% scenario remains simple.

**Comment by mhevery** [comment] 2015-10-01 22:49
No one is suggesting of taking `[Engine]` away This is not a semantic change, purely syntactical change.

**Comment by wardbell** [comment] 2015-10-02 07:50
Yup.  Just nailing down the loose ends ;-)

**Closed** 2015-10-11 05:35 UTC
Labels: comp: core/di, effort2: medium (day), P1: urgent, type: chore

**Comment by endash** [comment] 2015-10-11 17:55
I'm a bit late to this particular renaming party, but I'd be remiss if I didn't point out that the `provide`/`as` dichotomy is backwards... the `as` is what we're providing and the `provide` is the signifier, exactly the opposite of what we're communicating.

To transform into real-world usage:

"I've provided a case of Coca-Cola and pizza as the refreshments." 

With this convention that sentence would read:

"I've provided refreshments as a case of Coca-Cola and pizza"

The ambiguity here is that `as` can mean "in the form of" or it can indicate a signifier. When combined with the verb `provide`, it is strongly implied that it is a signifier.

My suggestion would be to flip them around:

```
provide({class: Foo, as: Foo});
provide({value: "foo", as: Foo});
provide({factory: (bar) => { }, deps: [Bar], as: Foo});
```

**Comment by PascalPrecht** [comment] 2015-10-11 18:02
I'm not an english native, so for me it's prolly less of a problem than for others. But seeing your code sample @endash I see the problem that the actual token is always at the end of the line, which makes it hard to read, if you really just want to find out what you get for a certain token. I think that having the tokens at the beginning is the better way to go here.

**Comment by endash** [comment] 2015-10-11 18:07
@PascalPrecht I was just thinking about that. There's no reason it can't be at the beginning, since it's a hash. It's not so important IMO that it be "readable as natural english", rather that the natural english reading shouldn't imply the opposite of what it does.

**Comment by IgorMinar** [comment] 2015-10-11 22:45
@endash I think you have a fair point. I like your `provision` proposal. Could we still keep the `provider` term for the result of calling `provision`?

@vsavkin @mhevery ?

**Comment by endash** [comment] 2015-10-11 23:08
@IgorMinar I don't think there's any obstacle to calling the result of `provision` a `Provider`. They have the same roots, and mean similar things. In a way, it actually makes more sense to call the result of a `provision` call a `Provider` than it does to call the result of a `provide` call a `Provider`, since at that point it seems, per the language used, that the providing's already been done, don't it?

**Comment by mhevery** [comment] 2015-10-11 23:45
If you want to call them provisions then the `@Component({})` should take `provisions` like so:

```
@Component({
  provisions: [
    provision(Foo, {asValue: 123})
  ]
})
```

At the end of the day I don't see any objective way of showing that provisions is better then providers. As long the Angular's documentation is consistent I don't think it makes much difference.

**Comment by endash** [comment] 2015-10-11 23:58
@mhevery did you read the comments? No one suggested renaming providers. The problem is currently we're misusing the *verb* `provide` in a way that is, yes, objectively incorrect.

**Comment by choeller** [comment] 2015-10-12 09:17
Hi everybody, 

also a bit late, but I want to add my two cents again. 

For me using `as` also seems pretty misleading. IMH it's the complete opposite of what it is used in other parts of the framework, e.g. the Module-Syntax:

`import {Foo as Bar} from './my-crazy-module'`

so the `as` usually just means the target and not the source. 

so the following statement:

`provide("bar").asValue("foo")`

would let me think, that I could @Inject('foo') and get the value "bar", not the other way around!

I really like @pkozlowski-opensource suggestion of "from":

`@provide("bar").fromValue("foo")`

IMO this is much clearer than 'as', there is no way of mixing things up with this expression...

**Comment by IgorMinar** [comment] 2015-10-13 03:43
just an update that we changed the api to be `provide(Car, {useClass: Ferrari}`, thanks for bringing this to our attention.

**Comment by ericmdantas** [comment] 2015-10-13 10:25
@choeller, very good point!
@IgorMinar, awesome!
