### ISSUE TITLE
Angular DevTools on Firefox causes massive lag and browser freeze on Microsoft Business(?) Login pages

### ISSUE THREAD

**Issue by KMikeeU** [angular/angular#57956] opened 2024-09-25 15:12 UTC
### Is this a bug report or a feature request?

- [X] Bug Report
- [ ] Feature Request

### Please provide the steps to reproduce the issue [Bug Report only]

0. Install the most recent version of Angular Devtools on the most recent version of Firefox
1. Disable all other extensions
2. Try to log in to any Microsoft service (via login.microsoftonline.com)
3. Enter Email (belonging to an organisation managed account!), click "Next"
4. "Trying to sign you in" takes much longer than usual and browser starts to lag

### Please provide the exception or error you saw [Bug Report only]

```true
The console is being spammed with the error

"IFrame: origin https://autologon.microsoftazuread-sso.com is not in the allowed list."

roughly 10k times
```

### Is this a browser-specific issue? If so, please specify the device, browser, and version. [Bug Report only]

```true
Windows 11 23H2, Firefox 130.0.1
```

**Comment by JeanMeche** [comment] 2024-09-25 15:23
Closing as duplicate of #55854. Let's continue to track this issue over there.

**Closed by JeanMeche** 2024-09-25 15:23 UTC
