### ISSUE TITLE
Give feedback on unused modules in the application

### ISSUE THREAD

**Issue by ertunga** [angular/angular#43427] opened 2021-09-11 11:46 UTC
### Description

Angular should give feedback on unused/unnecessary modules imported into the application modules. 

It is very easy to forget to remove (or mistakenly add) unused modules into an Angular application. This might be a material component module that's never been used or an application module imported into your _app.module_ without using anything from it. Angular should provide some sort of feedback to the developer, giving information about any unused modules in the application. The feedback might be in the form of a squiggly line or a warning in the devtools, visible during development.

I am aware that build optimizer optimizes the bundle and tree-shakes anything that is not being used, but there is still benefit in providing feedback. 

1. Developers would get a better understanding of using modules correctly, what needs to be in the module and what is not.
2. It is better to not include stuff you don't need in the first place, than trusting the optimizer will optimize everything for you. (What if there is a scenario where the optimizer fails to tree-shake)

### Proposed solution

Any feedback that informs developers is welcome. It could be a squiggly line under the unused modules or a warning in the devtools. It should not prevent the compilation.

### Alternatives considered

-

**Comment by Airblader** [comment] 2021-09-11 21:59
Duplicate of https://github.com/angular/angular/issues/41028

**Comment by JoostK** [comment] 2021-09-13 16:43
Duplicate of  #41028 (I have changed the voting labels accordingly).

**Closed by JoostK** 2021-09-13 16:43 UTC
Labels: feature, comp: compiler, under consideration
