### ISSUE TITLE
Tour Of Heroes > Missing Step > exports: [ RouterModule ]

### ISSUE THREAD

**Issue by cssagogo** [angular/angular#21207] opened 2017-12-29 04:15 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
The current documentation within the Tour of Heros is missing a step I believe...

https://angular.io/tutorial/toh-pt5#routermoduleforroot

The step calls for adding...

`imports: [ RouterModule.forRoot(routes) ],`

which results in an error of...

```
compiler.js:485 Uncaught Error: Template parse errors:
'router-outlet' is not a known element:
1. If 'router-outlet' is an Angular component, then verify that it is part of this module.
2. If 'router-outlet' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("<h1>{{ title }}</h1>
[ERROR ->]<router-outlet></router-outlet>
<app-messages></app-messages>
```

## Expected behavior

I am new to Angular, but I believe what is needed is an export as well. Or at least that is how I was able to get things working as follows...

```
  imports: [ RouterModule.forRoot(routes) ],
  exports: [ RouterModule ]
```

**Comment by yandrey1185** [comment] 2018-01-03 21:50
I continue with the error when I add:

  imports: [ RouterModule.forRoot(routes) ],
  exports: [ RouterModule ]

Some help!!!
Thanks

**Comment by kapunahelewong** [comment] 2018-01-05 17:51
@cssagogo and @yandrey1185 would either of you have your project handy in this state? I'd be happy to look at it. It would help me figure out where I might need to edit that doc.

**Comment by Papperlappap** [comment] 2018-03-23 16:37
Also new to Angular here. That's why we are doing the Tour of Heroes, right?

The problem lies within this sentence: 

"The RouterOutlet is one of the router directives that became available to the AppComponent because AppModule imports AppRoutingModule which exported RouterModule."

The import seems to not export it as well. I had to explicitly add the export as @cssagogo stated.

**Comment by kapunahelewong** [comment] 2018-03-24 13:00
@jenniferfell fyi ^^ For thy radar. :)

**Comment by jenniferfell** [comment] 2018-04-25 08:14
docarea=tutorial
URL=https://angular.io/tutorial/toh-pt5#routermoduleforroot

**Comment by jenniferfell** [comment] 2018-04-25 08:16
@kapunahelewong Just wanted to check. Are you still looking into this or should I reassign this? Didn't want to reassign without connecting first. Thanks.

**Comment by kapunahelewong** [comment] 2018-04-25 14:46
Hey @jenniferfell I'll take care of it. (@cssagogo I was on an extended break but back now 😀 )
I should be able to take a closer look this Friday, fyi.

Yay!

**Comment by chembu** [comment] 2018-10-09 18:19
Does not exist. The tutorial is updated with instructions to export Routermodule.

**Comment by packapotatoes** [comment] 2018-10-10 14:44
@chembu What does "Does not exist" mean? I am not seeing a change in the instructions and following them still gives me the error that @cssagogo received. Exporting RouterModule fixes the issue, but I do not see that fix reflected in the tutorial.

**Comment by chembu** [comment] 2018-10-10 15:05
![screen shot 2018-10-10 at 8 02 56 am](https://user-images.githubusercontent.com/33034359/46746063-1b7ff780-cc63-11e8-8d15-f85f75e4b770.png)

Above is the screenshot of Angular docs section that explains to export RouterModule to the Ng modules array.

**Comment by chembu** [comment] 2018-10-10 15:13
Hi Dan,
Please check the issue in GitHub to view a screenshot showing the updated instructions in Angular docs.


    On Wednesday, October 10, 2018, 7:46:48 AM PDT, Dan Kaufman <notifications@github.com> wrote:  
 
 
@chembu What does "Does not exist" mean? I am not seeing a change in the instructions and following them still gives me the error that @cssagogo received. Exporting RouterModule fixes the issue, but I do not see that fix reflected in the tutorial.

**Comment by tbleken** [comment] 2018-10-29 19:10
I face the same problem, and I am not able to fix it. Any help is welcome. I am a beginner in Angular, so please forgive me if I have done something obviously wrong. This is my code at the same stage in the tutorial:

*app-routing.module.ts:*
```typescript
import { NgModule } from '@angular/core';
import { HeroesComponent } from './heroes/heroes.component';
import { RouterModule, Routes } from '@angular/router';

const routes: Routes = [
  { path: 'heroes', component: HeroesComponent}
];
@NgModule({
  imports: [RouterModule.forRoot(routes)],
  exports: [RouterModule]
})
export class AppRoutingModule { }
```
*app.module.ts:*
```typescript
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { AppComponent } from './app.component';
import { HeroesComponent } from './heroes/heroes.component';
import { HeroDetailComponent } from './hero-detail/hero-detail.component';
import { MessagesComponent } from './messages/messages.component';
import { AppRoutingModule } from '../app-routing.module';

@NgModule({
  declarations: [
    AppComponent,
    HeroesComponent,
    HeroDetailComponent,
    MessagesComponent
  ],
  imports: [
    BrowserModule,
    FormsModule,
    AppRoutingModule
  ]*,
  providers: [
    // no need to place any providers due to the `providedIn` flag...
  ],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

**Comment by chembu** [comment] 2018-10-30 13:12
@tbleken : Did you try importing the RouterModule inside the imports array of the module that is using the router-outlet component?

**Comment by tbleken** [comment] 2018-10-30 13:56
Hi chembu, can I ask you to be more specific? I have only spent a few days on trying to learn Angular so far, so please forgive my ignorance. I have tried my best to follow the tutorial mentioned above, and so far I am at this step: [Routing: Try it.](https://angular.io/tutorial/toh-pt5#try-it). Only two typescript files are modified in this lesson so far. If you suggest that I need to modify any of the files from any previous lesson,  can you tell me which? 
I have studied the ts files, and the only reference to router-outlet is in @angular/router. And the only place @angular/router is used, is in app-routing.module.ts which you see above. It's also used in app.component.spec.ts, but that's a file which has been created "automatically", it hasn't been modified by me.
I really would have appreciated if the lessons had shown the complete modified code several times during the lessons, and not only at the end of each lesson after several more steps have been added.

**Comment by chembu** [comment] 2018-10-30 22:33
Let me take a look.

**Comment by chembu** [comment] 2018-10-30 22:56
@tbleken Can you check if adding the following to your app.component.spec.ts help?

 import { AppRoutingModule } from './app-routing.module';  _//add_ this line_ 
import {RouterTestingModule} from  '@angular/router/testing'; _//add this line_

beforeEach(async(() => {
    TestBed.configureTestingModule({
      declarations: [
        AppComponent
      ],
     _//add the following_
     imports: [
        AppRoutingModule,
        RouterTestingModule
      ]
    }).compileComponents();
  }));

**Comment by tbleken** [comment] 2018-10-31 08:18
htt@chembu I still have the same error. For completeness, here's the whole error message:
```txt
compiler.js:1021 Uncaught Error: Template parse errors:
'router-outlet' is not a known element:
1. If 'router-outlet' is an Angular component, then verify that it is part of this module.
2. If 'router-outlet' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("<h1>{{title}}</h1>
[ERROR ->]<router-outlet></router-outlet> 
<app-heroes></app-heroes> 
<app-messages></app-messages>
"): ng:///AppModule/AppComponent.html@1:0
    at syntaxError (compiler.js:1021)
    at TemplateParser.push../node_modules/@angular/compiler/fesm5/compiler.js.TemplateParser.parse (compiler.js:14851)
    at JitCompiler.push../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._parseTemplate (compiler.js:24708)
    at JitCompiler.push../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._compileTemplate (compiler.js:24695)
    at compiler.js:24638
    at Set.forEach (<anonymous>)
    at JitCompiler.push../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._compileComponents (compiler.js:24638)
    at compiler.js:24548
    at Object.then (compiler.js:1012)
    at JitCompiler.push../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._compileModuleAndComponents (compiler.js:24547)
```
And this is my modified app.component.spec.ts:
```typescript
import { TestBed, async } from '@angular/core/testing';
import { RouterTestingModule } from '@angular/router/testing';
import { AppComponent } from './app.component';
import { AppRoutingModule } from "./app-routing.module";
import { RouterTestingModule } from "@angular/router/testing ";
describe('AppComponent', () => {
  beforeEach(async(() => {
    TestBed.configureTestingModule({
      imports: [
        AppRoutingModule,
        RouterTestingModule
      ],
      declarations: [
        AppComponent
      ],
    }).compileComponents();
  }));

  it('should create the app', () => {
    const fixture = TestBed.createComponent(AppComponent);
    const app = fixture.debugElement.componentInstance;
    expect(app).toBeTruthy();
  });

  it(`should have as title 'tourofheroes'`, () => {
    const fixture = TestBed.createComponent(AppComponent);
    const app = fixture.debugElement.componentInstance;
    expect(app.title).toEqual('tourofheroes');
  });

  it('should render title in a h1 tag', () => {
    const fixture = TestBed.createComponent(AppComponent);
    fixture.detectChanges();
    const compiled = fixture.debugElement.nativeElement;
    expect(compiled.querySelector('h1').textContent).toContain('Welcome to tourofheroes!');
  });
});
```

**Comment by chembu** [comment] 2018-11-01 03:53
@tbleken : one more try.

Can you add the following in app.module.ts:

import { RouterModule } from '@angular/router';

and also add `RouterModule` to the imports array.

**Comment by tbleken** [comment] 2018-11-01 09:01
@chembu: Now I get another error:
```txt
AppComponent.html:2 ERROR Error: StaticInjectorError(AppModule)[RouterOutlet -> ChildrenOutletContexts]: 
  StaticInjectorError(Platform: core)[RouterOutlet -> ChildrenOutletContexts]: 
    NullInjectorError: No provider for ChildrenOutletContexts!
    at NullInjector.push../node_modules/@angular/core/fesm5/core.js.NullInjector.get (core.js:718)
    at resolveToken (core.js:955)
    at tryResolveToken (core.js:899)
    at StaticInjector.push../node_modules/@angular/core/fesm5/core.js.StaticInjector.get (core.js:796)
    at resolveToken (core.js:955)
    at tryResolveToken (core.js:899)
    at StaticInjector.push../node_modules/@angular/core/fesm5/core.js.StaticInjector.get (core.js:796)
    at resolveNgModuleDep (core.js:17787)
    at NgModuleRef_.push../node_modules/@angular/core/fesm5/core.js.NgModuleRef_.get (core.js:18476)
    at resolveDep (core.js:18847)
View_AppComponent_0 @ AppComponent.html:2
proxyClass @ compiler.js:10198
push../node_modules/@angular/core/fesm5/core.js.DebugContext_.logError @ core.js:20732
push../node_modules/@angular/core/fesm5/core.js.ErrorHandler.handleError @ core.js:12680
(anonymous) @ core.js:14758
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:388
push../node_modules/zone.js/dist/zone.js.Zone.run @ zone.js:138
push../node_modules/@angular/core/fesm5/core.js.NgZone.runOutsideAngular @ core.js:14150
(anonymous) @ core.js:14758
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:388
onInvoke @ core.js:14191
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:387
push../node_modules/zone.js/dist/zone.js.Zone.run @ zone.js:138
(anonymous) @ zone.js:872
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:421
onInvokeTask @ core.js:14182
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:420
push../node_modules/zone.js/dist/zone.js.Zone.runTask @ zone.js:188
drainMicroTaskQueue @ zone.js:595
Promise.then (async)
scheduleMicroTask @ zone.js:578
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ zone.js:410
push../node_modules/zone.js/dist/zone.js.Zone.scheduleTask @ zone.js:232
push../node_modules/zone.js/dist/zone.js.Zone.scheduleMicroTask @ zone.js:252
scheduleResolveOrReject @ zone.js:862
ZoneAwarePromise.then @ zone.js:962
push../node_modules/@angular/core/fesm5/core.js.PlatformRef.bootstrapModule @ core.js:14691
./src/main.ts @ main.ts:11
__webpack_require__ @ bootstrap:78
0 @ main.ts:12
__webpack_require__ @ bootstrap:78
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ main.js:1
AppComponent.html:2 ERROR CONTEXT DebugContext_ {view: {…}, nodeIndex: 3, nodeDef: {…}, elDef: {…}, elView: {…}}
View_AppComponent_0 @ AppComponent.html:2
proxyClass @ compiler.js:10198
push../node_modules/@angular/core/fesm5/core.js.DebugContext_.logError @ core.js:20732
push../node_modules/@angular/core/fesm5/core.js.ErrorHandler.handleError @ core.js:12685
(anonymous) @ core.js:14758
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:388
push../node_modules/zone.js/dist/zone.js.Zone.run @ zone.js:138
push../node_modules/@angular/core/fesm5/core.js.NgZone.runOutsideAngular @ core.js:14150
(anonymous) @ core.js:14758
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:388
onInvoke @ core.js:14191
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:387
push../node_modules/zone.js/dist/zone.js.Zone.run @ zone.js:138
(anonymous) @ zone.js:872
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:421
onInvokeTask @ core.js:14182
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:420
push../node_modules/zone.js/dist/zone.js.Zone.runTask @ zone.js:188
drainMicroTaskQueue @ zone.js:595
Promise.then (async)
scheduleMicroTask @ zone.js:578
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ zone.js:410
push../node_modules/zone.js/dist/zone.js.Zone.scheduleTask @ zone.js:232
push../node_modules/zone.js/dist/zone.js.Zone.scheduleMicroTask @ zone.js:252
scheduleResolveOrReject @ zone.js:862
ZoneAwarePromise.then @ zone.js:962
push../node_modules/@angular/core/fesm5/core.js.PlatformRef.bootstrapModule @ core.js:14691
./src/main.ts @ main.ts:11
__webpack_require__ @ bootstrap:78
0 @ main.ts:12
__webpack_require__ @ bootstrap:78
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ main.js:1
main.ts:12 Error: StaticInjectorError(AppModule)[RouterOutlet -> ChildrenOutletContexts]: 
  StaticInjectorError(Platform: core)[RouterOutlet -> ChildrenOutletContexts]: 
    NullInjectorError: No provider for ChildrenOutletContexts!
    at NullInjector.push../node_modules/@angular/core/fesm5/core.js.NullInjector.get (core.js:718)
    at resolveToken (core.js:955)
    at tryResolveToken (core.js:899)
    at StaticInjector.push../node_modules/@angular/core/fesm5/core.js.StaticInjector.get (core.js:796)
    at resolveToken (core.js:955)
    at tryResolveToken (core.js:899)
    at StaticInjector.push../node_modules/@angular/core/fesm5/core.js.StaticInjector.get (core.js:796)
    at resolveNgModuleDep (core.js:17787)
    at NgModuleRef_.push../node_modules/@angular/core/fesm5/core.js.NgModuleRef_.get (core.js:18476)
    at resolveDep (core.js:18847)
```
This is no "show stopper" for me. I'll keep on reading, learning and testing, hopefully I'll spot the error myself.

**Comment by chembu** [comment] 2018-11-01 14:47
You need to export the routes so that it is known to app-module.
So, in app-routing module.ts:
instead of:
 const routes: Routes = [
  { path: 'heroes', component: HeroesComponent }
];

//add export

export const routes: Routes = [
  { path: 'heroes', component: HeroesComponent }
];

**Comment by tbleken** [comment] 2018-11-02 09:17
@chembu: still no luck. I will go through the whole tutorial once more, however I strongly feel that the tutorial is wrong and/or incomplete. Others have faced the same problem, a clear evidence that the tutorial need improvements. Has anyone tried to follow it according to the description? It should have more complete code listings along the way, not only a brief description of the changes, in addition to the complete code listing at the end of each session.

**Comment by tbleken** [comment] 2018-11-02 15:06
@chembu: For your information, I went through the tutorial once more, in another folder, and I got exactly the same errors. So unless I am totally blind or stupid, something is wrong or missing in the tutorial.

**Comment by kapunahelewong** [comment] 2018-11-02 16:35
Hey @tbleken, I worked my way through and couldn't get the same problem to come up, though it certainly warrants a closer look. I downloaded your src folder and put it into a working app and indeed, it returned the `router-outlet` error, even though, as far as I could tell, you had the `app-routing.module.ts` and the `app.module.ts` correct. I experimented and rebuilt 5 times, with your code and with mine, but the only way I could duplicate the error in my app was to not export `AppRoutingModule` from `app-routing.module.ts`. To help you get over this point in the Tutorial, I've pushed my version up for you. If you'd like, you can take it and continue to work your way through using it instead. Meanwhile, I can try to take a closer look at the language in there and make sure it's clearer. 

I hope this helps. The example I made is here: [https://github.com/kapunahelewong/tohpt5-beginning](https://github.com/kapunahelewong/tohpt5-beginning)

It is up to this point in the tutorial: [https://angular.io/tutorial/toh-pt5#add-routeroutlet](https://angular.io/tutorial/toh-pt5#add-routeroutlet)

Good luck!

**Comment by tbleken** [comment] 2018-11-02 17:37
@kapunahelewong : Thanks a lot! I compared your files to mine, and the difference was in app.module.ts where you had one more imports, AppRoutingModule. I added it, and the error disappeared.  I see that it's mentioned in the last comment right before the Ty It button, but since it was not shown in any of the code samples, I didn't add it earlier. In the final code listing it's included, however that's together with many other changes. Again, thank you for your kind help.

**Comment by SanderElias** [comment] 2019-01-26 08:22
@kapunahelewong @tbleken From the source I see in this thread I think the CommonModule isn't imported. A lot of angular directives live inside there, and from what I read above, I suspect `router-outlet` does to.

**Comment by kapunahelewong** [comment] 2019-01-29 20:00
Going back over this one at the request of @chembu to make sure the steps are clear.

**Comment by arcanist123** [comment] 2019-03-24 14:46
I think that the issue is still not resolved. The documentation is currently stating that only import is required. I had to go to the bottom of the page where the export is explicitely mentioned to resolve it. A minor thing, but still
![image](https://user-images.githubusercontent.com/8202327/54881053-04694680-4e4c-11e9-8ca3-560023b14490.png)

**Comment by kapunahelewong** [comment] 2019-03-25 18:15
Hi @arcanist123, thanks for chiming in and the screenshot (I love them!). You are correct in that this is still an issue in the live tutorial. Check out what i have in my PR: [https://pr28571-0676d83.ngbuilds.io/tutorial/toh-pt5#routermoduleforroot](https://pr28571-0676d83.ngbuilds.io/tutorial/toh-pt5#routermoduleforroot) 

Is this clearer? I'm happy to take any pointers to make it better.

**Comment by arcanist123** [comment] 2019-03-29 07:31
I think, it is very much clear now. Thanks.

**Comment by JulianaCarvalhoSouza** [comment] 2019-08-06 12:25
I had the same problem @tbleken  had and it was solved in the same way: importing the AppRoutingModule. Thanks @kapunahelewong for you code!

**Comment by kapunahelewong** [comment] 2019-08-07 16:41
Thank you for the feedback @JulianaCarvalhoSouza. So glad it helped. 😊

**Comment by talln6e** [comment] 2019-10-21 14:21
So what was the final answer(s)?
Has the tutorial instructions been changed for each?
I am going through this tutorial and still have this error.
Thank you.

**Comment by kapunahelewong** [comment] 2019-10-21 20:14
Yes, @talln6e, it should have been updated as of July 22, 2019 in https://github.com/angular/angular/pull/28571. It seems like you still stumbled, though. Was it due to something needing clarification?

**Comment by KevCanon** [comment] 2019-12-30 17:27
I got the same error like @tbleken did. I solved it with his [solution](https://github.com/angular/angular/issues/21207#issuecomment-435455066):
add to `app.module.ts`:
`import { AppRoutingModule } from './app-routing.module';`
and also add `AppRoutingModule` to the imports Array.

This step should be added to the tutorial in [Add the AppRoutingModule](https://angular.io/tutorial/toh-pt5#add-the-approutingmodule) or [Add RouterOutlet](https://angular.io/tutorial/toh-pt5#add-routeroutlet) section, because after adding the RouterOutlet the error message @tbleken posted [before](https://github.com/angular/angular/issues/21207#issuecomment-434976649) appears.

**Comment by samjulien** [comment] 2020-01-09 19:35
Hey @KevCanon quick question for you. The CLI command `ng generate module app-routing --flat --module=app` should have done that update for you for `app.module.ts`, so I'm wondering where we've missed something and how we can improve the wording to prevent this. Any thoughts? Did you use that command or manually create the file? I think either way we'll add a note to remind people to double-check that import.

**Comment by KevCanon** [comment] 2020-01-09 19:50
In my case I used IntelliJ to created all files. I never used the CLI commands.
I think a note could help :-)

**Comment by samjulien** [comment] 2020-01-09 20:06
Very helpful feedback, thank you!

**Closed** 2020-01-09 21:26 UTC
Labels: comp: docs, docsarea: tutorial, freq4: critical, severity3: broken, state: has PR, type: bug/fix
