### ISSUE TITLE
Build failure on Windows caused by missing Symlink to facade in benchpress\src

### ISSUE THREAD

**Issue by gary-b** [angular/angular#12420] opened 2016-10-20 23:12 UTC
**I'm submitting a ...** 
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```
**Current behavior**
Building angular on windows throws the following error:
>Error at D:/GitHub/angular/modules/@angular/benchpress/src/reporter/console_reporter.ts:10:21: Cannot find module '../facade/lang'.

There is a missing symlink to facade in benchpress/src. The developer guide advises that running ./scripts/windows/create-symlinks.sh should create the symlinks required, but the text file the script uses as input to decide where to create them is missing an entry for benchpress/src.

**Expected behavior**
Build should proceed without this error.

**Minimal reproduction of the problem with instructions**
Clone the angular repo to Windows. Run the create-symlinks.sh script, observe there is no symlink to facade in @angular/benchpress/src/ . After following the other instructions in the developer guide run build.sh and see the error listed above.

**What is the motivation / use case for changing the behavior?**
It is broken.

**Please tell us about your environment:**

Windows 10, Bash scripts run on MINGW64 that came with my git installation.

* **Angular version:** 2.0.X
Angular Master Branch forked today.

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
N/A
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
N/A

* **Node (for AoT issues):** `node --version` =   
N/A

**Comment by vicb** [comment] 2016-10-21 00:02
duplicate of #12422

**Closed by vicb** 2016-10-21 00:02 UTC

**Comment by gary-b** [comment] 2016-10-21 00:13
Hi vicb

Im going to submit PRs for these issues. I kept them separate because i intended to have one commit to add a directory to the packages.txt file, while the other will update the bash script to not ignore the last line of packages.txt when it doesnt have a \n.

Should i make these changes in 1 commit now?

Regards

**Comment by gary-b** [comment] 2016-10-21 00:15
Im assuming you always want 1 commit per PR???

**Comment by gary-b** [comment] 2016-10-21 00:33
its late here, ill push it in one commit/pr and see what happens :)

**Comment by vicb** [comment] 2016-10-21 04:58
PR can contain multiple commits, no pb
