### ISSUE TITLE
Missing response header values in thrown HTTP error

### ISSUE THREAD

**Issue by thepian** [angular/angular#21662] opened 2018-01-19 11:23 UTC
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
When you catch errors returned for Http requests the `error.headers.keys()` only contains `pragma, content-type, cache-control, expires`. It excludes X-Powered-By and other X prefixed attributes from the response header.

I'm unaware if the headers are filtered with a positive list or if the browser for some reason does the restriction.

## Expected behavior

Any `X-` response header attribute would be in the `error.headers`. 

## Minimal reproduction of the problem with instructions

this.slxHttp.post(Urls.postDepartmentDataUrl, action.payload)
            .map(payload => ({ type: AccountActions.department_data_change_result.name, payload }))
            .catch(makeActionErrorObservableCatcher(AccountActions.customer_profile_error.name, 'account-undefined-error')));

## What is the motivation / use case for changing the behavior?

Middleware on the server-side should be able to annotate error responses with additional information that can be used for tracking support issues.

## Environment

<pre><code>
Angular version: 5.1.3

Browser:
- [x] Chrome (desktop) version 63
 </code></pre>

**Comment by trotyl** [comment] 2018-01-19 17:54
Duplicate of #20554

**Closed** 2018-01-26 12:44 UTC
Labels: comp: http
