### ISSUE TITLE
Banner advertisement example on angular.io blocked by some ad blockers

### ISSUE THREAD

**Issue by StephenFluin** [angular/angular#18138] opened 2017-07-14 21:06 UTC
## I'm submitting a...
<pre><code>
[x] Bug report 
</code></pre>

I believe the image is blocked simply because of its filename. A rename might fix this.

## Current behavior
https://angular.io/guide/dynamic-component-loader

The "final ad banner" at the bottom doesn't render on some browsers when using an ad blocker

## Expected behavior
The example should be shown when using an ad blocker.

## Minimal reproduction of the problem with instructions
Install https://chrome.google.com/webstore/detail/adblock/gighmmpiobklfepjocnamgkkbiglidom/related?hl=en-US
Visit https://angular.io/guide/dynamic-component-loader
Scroll to the bottom of the page

**Comment by tytskyi** [comment] 2017-07-14 21:46
Given my previous experience with overcoming adblockers - resulting html (class name, id, title, url etc) should not contain anything that could be treated as a description of an advertisement, like: banner, ad, ads etc.

**Comment by petebacondarwin** [comment] 2017-07-15 21:49
So I think the content needs to be reworked to be something not ad related. Perhaps it could be an upcoming hero events component?

**Comment by petebacondarwin** [comment] 2017-07-15 21:50
@StephenFluin - I have moved this to the docs project and relabelled as it is not related to the AIO doc-viewer but instead content related.

**Comment by ocombe** [comment] 2017-07-17 08:35
I confirm that any js or image with "ad" in its name is likely to be blocked by adblocks, I've had this issue before

**Comment by aravindfz** [comment] 2017-07-17 14:42
If you looking for an  alternative example, refer this **[medium](https://medium.com/@aravind_12433/load-modal-component-dynamically-in-angular-5fda8e1dc3e7)** post

**Comment by jenniferfell** [comment] 2018-04-25 09:37
@StephenFluin I followed the steps above, and I cannot reproduce the problem today in Chrome. Work was done on the example (https://github.com/angular/angular/pull/22181), but I don't think we expected that to fully resolve this problem. More related info here: https://github.com/angular/angular/issues/17158

Even if it's working right now in some situations, I'm inclined to keep this open and change the example to be more ad-safe. What do you think? 

Thanks.

**Comment by StephenFluin** [comment] 2018-04-25 13:01
@jenniferfell I was able to reproduce this. Make sure you have 'EasyList' selected in AdBlock, that's the one that is doing it for me.

![image](https://user-images.githubusercontent.com/165056/39247387-2429401a-484e-11e8-9163-97e475fc6576.png)

**Comment by dennisameling** [comment] 2018-11-21 14:57
I am able to reproduce this as well (Chrome 70.0.3538.102 with Adblock Plus). The culprit seems to be in the `ad-banner` class in ad-banner.component.ts. Like @StephenFluin mentioned, this is due to EasyList being selected in ABP. It injects `display:none` in elements with the `ad-banner` class name.

An easy fix for this is to just rename the `ad-banner` class to `ad-banner-example`, after which the banner works as expected.

**Comment by gkalpak** [comment] 2018-11-21 15:29
BTW, if anyone feels like submitting a PR, please do :wink:

**Comment by dennisameling** [comment] 2018-11-21 16:16
@gkalpak Sorry for the mess, first time submitting a PR to the Angular repo 🙈 PR ready!

**Closed** 2018-11-30 21:36 UTC
Labels: comp: docs, freq3: high, severity3: broken, type: bug/fix
