### ISSUE TITLE
Date pipe doesn't ignore details of formatting when using a custom format

### ISSUE THREAD

**Issue by JohnKis** [angular/angular#11661] opened 2016-09-16 09:21 UTC
**I'm submitting a ...**  (check one with "x")

```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 
Date pipe keeps the order of date components when using a custom format. According to the docs (https://angular.io/docs/ts/latest/api/common/index/DatePipe-pipe.html) this shouldn't be the case: 'In javascript, only the components specified will be respected (not the ordering, punctuations, ...) and details of the formatting will be dependent on the locale.'

**Expected behavior**
The date pipe should ignore ordering and whitespaces etc, it should only care about the date components and format the output date according to the locale.

**Reproduction of the problem**
http://plnkr.co/edit/fCZ4oVcn5qsnNssvSnar?p=preview

**What is the motivation / use case for changing the behavior?**
To be able to use custom date formats.

**Please tell us about your environment:**
macOS Sierra, Visual Studio Code, NPM 3.10.3
- **Angular version:** 2.0.0 (Final release)
- **Browser:** all
- **Language:** TypeScript 2.0.2
- **Node (for AoT issues):** `node --version` =   v6.3.0

**Comment by kylecordes** [comment] 2016-09-16 13:04
I noticed this in earlier A2 development also. Somewhere along the way (betas?) it behaved as documented then it changed as described here. However, I assumed that the behavior change was intended, and didn't notice the documentation that still described the old behavior... so I assumed the change was intentional, just not documented yet.

Which is a long way of saying: it's not clear whether the fix here is to change the docs or change the code.

**Comment by vicb** [comment] 2016-09-16 16:02
I haven't got a chance to look at the localization pipes lately with the release of 2.0.

I should restart working on i18n/l10n by e/o next week.

**Comment by laskoviymishka** [comment] 2016-09-18 20:20
Imho, it's documentation issue. This behaivior was changed a long time ago and not documented properly.

**Comment by JohnKis** [comment] 2016-09-19 13:22
If it's really a documentation issue, that's bad news for me. I really like the way how it's supposed to work according to the documentation.

**Comment by laskoviymishka** [comment] 2016-09-19 20:26
Could you please provide some information about missed scenarios?

**Comment by JohnKis** [comment] 2016-09-20 07:39
For sure. I have an internationalised app, where I have to display the current date in a format that contains the day of the week, the day and the month. Since different languages have different ordering in the date a fixed format wouldn't work here. 

Example output using the JS INTL API:
```
var d = new Date();
var format = { day: 'numeric', month: 'short', weekday: 'short' };

console.log(d.toLocaleDateString('en-GB')); // Tue 20 Sep
console.log(d.toLocaleDateString('en-US')); // Tue, Sep 20
console.log(d.toLocaleDateString('hu-HU')); // szept. 20., K
```

Now if I used the built in date pipe (as it's working currently), the output would be the following:
```
// LOCALE_ID: en-GB
{{ date | date:'EEE d MMM' }} // Tue 20 Sep
// LOCALE_ID: en-US
{{ date | date:'EEE d MMM' }} // Tue 20 Sep
// LOCALE_ID: hu-HU
{{ date | date:'EEE d MMM' }} // K 20 szept.
```

While the pipe (with custom format) is useful if your app isn't localised, for localised apps it's quite bad. I feel that there should be a way to achieve both scenarios. Maybe there could be a prefix in the in the format string to ignore formatting, or similar.

**Comment by laskoviymishka** [comment] 2016-09-20 16:02
That seems reasonable. But that approach kill custom formats. The only thing that I could propose is to enhance current date pipe to get not only format string,  but also an Intl.Api format object. This could fit for both scenarios. Does it sounds good for you? 
This fix will require some approval from core team (cc @vicb). But essentially it has really low risk and not reduce current api, just add some more awesomeness.  :)

**Comment by vicb** [comment] 2016-09-20 16:04
@laskoviymishka I hope to have some time next week to work on this, please ping me then

**Comment by laskoviymishka** [comment] 2016-09-20 16:09
@vicb sure. IMHO that enhance could be really helpful for everyone

**Comment by JohnKis** [comment] 2016-09-20 16:23
@laskoviymishka It sounds perfect! :) Really looking forwards to it.

Thanks

**Comment by pkozlowski-opensource** [comment] 2016-12-19 19:39
I've just closed #9378 as a duplicate of this one. I'm not surprised that people are opening issues for this one since I find the current behaviour quite confusing.... The fact that we might "hit" an alias pattern for _some_ formats (but not for others, almost identical ones) is utterly confusing and IMO we should have 2 different ways of specifying one of 2 different things:
* I want the _exact_ format
* I want certain date / time components in my final output and the exact output shell be dictated by locale settings

As of today we've got one API to express those different things and the _only_ way of knowing which code path we are going to take is ... to look at https://github.com/angular/angular/blob/0e3981afc17b9fbc302b59397037b71715afdd28/modules/%40angular/common/src/pipes/intl.ts#L46

**Comment by ocombe** [comment] 2017-10-20 08:15
Closing this since it is an old bug. I don't think that you still have the issue in the v5 date pipe.

**Comment by JohnKis** [comment] 2017-10-20 08:29
It is exactly the same in v5. I don't think the changes ever got merged

**Comment by ocombe** [comment] 2017-10-20 08:51
Actually it's clearer because the order sentence has been removed from the docs. If you use a custom format we will respect the format that you give us, because we don't make any assumption as to how you want to format your date.
If you want to have a fixed format that depends on the locale you should use one of the following: short/medium/long/full (and equivalents for date or time).
https://next.angular.io/api/common/DatePipe

**Closed by ocombe** 2017-10-20 08:51 UTC
Labels: comp: common, comp: i18n, freq3: high, severity3: broken, type: bug

**Comment by JohnKis** [comment] 2017-10-20 08:55
That still doesn't solve the original use case of displaying a custom format that respects the ordering of the locale. I liked @laskoviymishka's suggestion of being able to pass an Intl.Api format object in addition to the format string.

**Comment by ocombe** [comment] 2017-10-20 09:01
We no longer use the intl API, we are based on CLDR data now.
I've checked, and we could support this using skeletons, see "Additional Date-Time Formats" in http://cldr.unicode.org/translation/date-time-patterns.
Do you think that it would fix the issue ?

**Comment by JohnKis** [comment] 2017-10-20 09:04
Yes, I believe that would be a good solution.

**Comment by ocombe** [comment] 2017-10-20 09:06
Ok, could you open a new issue with a feature request for that please?

**Comment by JohnKis** [comment] 2017-10-20 09:39
No problem, I opened #19823
