### ISSUE TITLE
ContentChild's update triggers ExpressionChangedAfterItHasBeenCheckedError when child created with ngFor

### ISSUE THREAD

**Issue by WiseBird** [angular/angular#24563] opened 2018-06-18 15:34 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Overall structure:
```
  Host Component
    Parent component
    Child component
```
Parent and Child are defined in Host's template and Child projected inside parent.

Child component is OnPush component that prepared to direct interaction (not via inputs/outputs), meaning that it has properties that looks like so:
```
    private _text: string = '';
    get text(): string {
        return this._text;
    }
    set text(value: string) {
        if (this._text === value) {
            return;
        }
        this._text = value;
        this.changeDetectorRef.markForCheck();
    }
```
It refreshes the view on property update.

Parent is also OnPush component that injects Child: ` @ContentChild(ChildComponent) item: ChildComponent;` and updates some of it properties on start:
```
    ngAfterContentInit() {
        this.item.show = !this.item.show;
        ...
    }
```

Now about Host components. Actually there are four of them with/without OnPush x with/without ngFor (check reproduction).

Without ngFor template is trivial:
```
    <my-parent>
      <my-child></my-child>
    </my-parent>
```
And this versions (both with and without OnPush) work as expected - Child is updated, no errors.

With ngFor:
```
    <my-parent>
      <my-child *ngFor="let item of list"></my-child>
    </my-parent>
```
where `list` is `[1]`.

In this case behavior differs. When host is OnPush - Child simply is not updated. When Host is not OnPush - `ExpressionChangedAfterItHasBeenCheckedError` it thrown.

## Expected behavior

Behavior of component shouldn't change whether or not it is used inside ngFor.

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/angular-content-child-ng-for

## What is the motivation / use case for changing the behavior?

This is counterintuitive behavior.

## Environment

<pre><code>
Angular version: 6.0.5

Browser:
- [x] Chrome (desktop) version 67.0.3396.62 

</code></pre>

**Comment by despian** [comment] 2018-06-19 10:34
+1

I have also come across the same issue. I've illustrated my problem with this stackblitz:

[https://stackblitz.com/edit/angular-g3a7cm?file=src%2Fapp%2Fform.component.ts&devtoolsheight=50](https://stackblitz.com/edit/angular-g3a7cm?file=src%2Fapp%2Fform.component.ts&devtoolsheight=50)

I had not realised that the use of ngFor was playing a role, but after reading this issue and testing it out I can confirm the same.

If I comment out the ngFor in [form.component.html](https://stackblitz.com/edit/angular-g3a7cm?file=src%2Fapp%2Fform.component.html&devtoolsheight=50) and replace it with implicit calls to the child component the error is not thrown.

My workaround is currently to place the modifying logic of the child component's onNgInit function into a setTimeout call.

**Comment by pkozlowski-opensource** [comment] 2019-03-19 10:29
Here is a much simpler reproduce scenario: https://stackblitz.com/edit/angular-uir53q?file=src%2Fapp%2Fapp.component.ts

**Comment by 4nd3r5** [comment] 2020-02-18 15:06
Why has this not been adressed? What is best practices for modifying ContentChildren? Is there some other better approach?

**Comment by omaracrystal** [comment] 2020-02-26 21:16
I am also seeing this issue after Upgrading from Angular 7 to Angular 9 with Ivy turned off. In my case there is no `*ngFor `but it's within a `*ngIf `with an async pipe. There are 4 components all individually wrap the reusable component `<app-card-editable>` and this component uses transclusion to inject dynamic data from these 4 components. They all use @ViewChild to reference it and within the `<app-card-editable>` is where the error is happening = `ExpressionChangedAfterItHasBeenCheckedError`. This `<app-card-editable>` uses ContentChild to reference an element within those 4 components which is also emitting a boolean value  `(isValid)="isValid = $event"` and it causing this error to occur. 

Phew that was a tongue twister .... but all in all -- I don't get why this error didn't occur until the upgrade.

**Comment by mlc-mlapis** [comment] 2020-02-26 21:31
@omaracrystal In each new version there were some improvements in this area. So look at it oppositely, that it was an issue previously - it was quietly allowed more than it should be.

**Comment by pkozlowski-opensource** [comment] 2020-05-27 14:57
This is a duplicate of #16388, see the latest update in https://github.com/angular/angular/issues/16388#issuecomment-634715648

**Closed by pkozlowski-opensource** 2020-05-27 14:57 UTC
Labels: comp: core, core: change detection, core: queries, freq1: low, severity1: confusing, type: bug/fix
