### ISSUE TITLE
Model is not getting refreshed after form "reset"

### ISSUE THREAD

**Issue by VirMaker** [angular/angular#6196] opened 2015-12-31 15:32 UTC
Not sure if this behavior is expected, there is an easy workaround. After I press to clear a form, bound model is not updated with new/reset values, while form resets as expected. Using angular 2 beta 0

**Comment by zoechi** [comment] 2015-12-31 17:22
How do you "press clear"?

**Comment by VirMaker** [comment] 2015-12-31 18:05
I guess I'm not sure what you mean when you say how you "press clear". It
is just a regular button/input with type="reset", without any angular
annotations/directives.

**Comment by zoechi** [comment] 2015-12-31 18:09
I see, didn't think of that. I was still looking for a way to reset an Angular form.

**Comment by FrancescoRizzi** [comment] 2015-12-31 18:55
I try to follow the examples given over in the [AngularJS Form documentation](https://docs.angularjs.org/guide/forms).
You'll see they make deep copies of the models involved to allow for an actual reset of the form (especially if the form was not empty to begin with). HTH

**Comment by VirMaker** [comment] 2015-12-31 19:11
I'm using angular 2 beta 0. I'm not sure how similar code base is.

**Comment by kara** [comment] 2016-07-11 23:57
Closing this one as a duplicate of https://github.com/angular/angular/issues/4914. Thanks for reporting!

**Closed by kara** 2016-07-11 23:57 UTC
