### ISSUE TITLE
Dynamic input type for checkbox breaks checkbox converts value to string

### ISSUE THREAD

**Issue by smasala** [angular/angular#36548] opened 2020-04-09 20:21 UTC
# 🐞 bug report

### Is this a regression?

 No

### Description

Still an issue in ng 9 (https://github.com/angular/angular/issues/7329)

If you create an input and use 2-way binding with `ngModel` of `ReactiveForms` and set the type of input dynamically `[type]="myType"` then it converts the value (boolean) to string and no longer toggles the value of the checkbox correctly

## 🔬 Minimal Reproduction

 

https://codesandbox.io/s/wispy-architecture-3teqd?file=/src/app/app.component.ts

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
9
</code></pre>

**Anything else relevant?**

**Comment by indraraj26** [comment] 2020-04-12 09:41
work around: 
```
 <input
      [type]="type"
      formControlName="fc"
      [checked]="group.get('fc').value"
    />
```

**Comment by AndrewKushnir** [comment] 2020-05-27 17:25
Hi @smasala, thanks for reporting the issue. It looks like a duplicate of the #13243 ticket, so I will close this one. Please subscribe to #13243 for further discussion/updates. Thank you.

**Closed by AndrewKushnir** 2020-05-27 17:25 UTC
Labels: comp: forms
