### ISSUE TITLE
SideNav contains lots of whitespace at the top and bottom

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#17096] opened 2017-05-30 08:00 UTC
This is especially visible when one scrolls through the site, expanding various menu options and then scrolling up and down within the document viewer as well as sidenav
![screenshot_20170530-023227](https://cloud.githubusercontent.com/assets/216296/26573523/fb295184-44d2-11e7-98d6-81b9c5ccbf36.png)

![screenshot_20170530-023246](https://cloud.githubusercontent.com/assets/216296/26573606/4df24a06-44d3-11e7-95ce-c00e0e996013.png)

**Comment by gkalpak** [comment] 2017-06-06 22:28
I couldn't figure out what causes the extra whitespace at the bottom (I wouldn't be surprized if it were a Chrome bug).

**Comment by petebacondarwin** [comment] 2017-06-15 13:54
@IgorMinar / @gkalpak Is this still an issue? I can't reproduce it.

**Comment by gkalpak** [comment] 2017-06-15 17:17
I can still see the bottom space, but only if you start expanding menu entries.

**Comment by petebacondarwin** [comment] 2017-07-16 11:02
Does this actually impact the app in any significant way? I am moving to TODO.

**Comment by petebacondarwin** [comment] 2017-12-13 22:30
I can no longer reproduce this at all.

**Closed by petebacondarwin** 2017-12-13 22:30 UTC
Labels: comp: aio, type: bug

**Comment by IgorMinar** [comment] 2017-12-14 19:48
this is no longer a problem.

**Comment by gkalpak** [comment] 2017-12-14 20:29
<sub>I can still reproduce the extra bottom space when expanding sub-menus (but I don't think there is anything we can do anyway) 🙊</sub>

**Comment by petebacondarwin** [comment] 2017-12-14 20:34
@gkalpak How?

**Comment by gkalpak** [comment] 2017-12-15 08:35
I simply expand one or more submenus (I guess depends on your screen size):

![sidenav-space](https://user-images.githubusercontent.com/8604205/34033609-8776106c-e183-11e7-9016-bb778c149dbb.png)
