### ISSUE TITLE
Pipes documentation missing at https://angular.dev/api/common#pipes

### ISSUE THREAD

**Issue by a688** [angular/angular#56204] opened 2024-05-31 15:46 UTC
### Describe the problem that you experienced

Pipes documentation missing at https://angular.dev/api/common#pipes. The link is from https://angular.dev/guide/pipes#built-in-pipes.

### Enter the URL of the topic with the problem

Pipes documentation missing at https://angular.dev/api/common#pipes

### Describe what you were looking for in the documentation

Complete list of built in pipes

### Describe the actions that led you to experience the problem

Clicked on the link on https://angular.dev/guide/pipes#built-in-pipes

### Describe what you want to experience that would fix the problem

Have the link fixed or the page added

**Comment by JeanMeche** [comment] 2024-05-31 15:59
Duplicate of https://github.com/angular/angular/issues/52968

**Closed by JeanMeche** 2024-05-31 15:59 UTC
