### ISSUE TITLE
[bug] not applying blank space in string interpolation with concat

### ISSUE THREAD

**Issue by indraraj26** [angular/angular#36201] opened 2020-03-23 14:46 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....

### Is this a regression?

 Yes, the previous version in which this bug was not present was: no idea

### Description

It is not applying space in string interpolation with concatenation.

```
<h2 class="title">Hello {{"           " + name}}</h2>

<div>
     No of test :  <span class="head-title"> {{'   ' + test.test}}</span>
</div>
```
![image](https://user-images.githubusercontent.com/23274631/77328878-2d643600-6d43-11ea-9a63-b153124a0319.png)

## 🔬 Minimal Reproduction

https://ng-run.com/edit/TqVt913YHmUBLvnVv0b2?open=app%2Fapp.component.html

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

ng --version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.0.3
Node: 10.16.0
OS: win32 x64

Angular: 9.0.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.3
@angular-devkit/build-angular     0.900.3
@angular-devkit/build-optimizer   0.900.3
@angular-devkit/build-webpack     0.900.3
@angular-devkit/core              9.0.3
@angular-devkit/schematics        9.0.3
@angular/cdk                      8.2.3
@angular/cli                      9.0.3
@angular/material                 8.2.3
@angular/service-worker           9.0.5
@ngtools/webpack                  9.0.3
@schematics/angular               9.0.3
@schematics/update                0.900.3
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
</code></pre>

**Anything else relevant?**

**Comment by indraraj26** [comment] 2020-03-23 14:53
Even with custom pipe, It is not applying blank space.
https://ng-run.com/edit/VMDDBDZiaRRAY5kuY8Sg?open=app%2Fapp.component.html

**Comment by pkozlowski-opensource** [comment] 2020-03-23 15:10
Duplicate of #26276

Sadly this is a known issues already tracked in #26276 - the root of the problem is in our implementation choice where the parsing pipeline works as follows, today:

- we first parse templates as a markup *without understanding interpolations in text nodes*;
- white-space removal is applied the AST from the first step - at this point we are "blind" to the interpolation and "see" `Hello {{"           " + name}}` as a text node so we collapse white-spaces;

To solve this problem properly we would have to change the markup parser to be interpolations-aware, but this would require substantial changes to our template parsing infrastructure. We do want to fix it but it is not trivial, sadly.

Anyway, let's track it in one place (#26276)

**Closed by pkozlowski-opensource** 2020-03-23 15:10 UTC
