### ISSUE TITLE
Date pipe calculation with timezone offset is wrong at Daylight Saving Time transition

### ISSUE THREAD

**Issue by cfinlinson-incomm** [angular/angular#57916] opened 2024-09-22 22:24 UTC
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

No

### Description

When using the date pipe to transform an ISO-8601 date string, the calculation is affected by Daylight Saving Time in my system time zone, even if I specify an offset.

For example, I am in the "America/Denver" timezone, which observes Daylight Saving Time. I want to display a date in the "America/Phoenix" timezone. During standard time, both time zones, have the same offset, -07:00. But during Daylight Saving Time, "America/Denver" is -06:00 and "America/Phoenix" is -07:00. Using the date pipe to transform a date-time string that occurs exactly at the time when Daylight Saving Time begins, `"2024-03-10T02:00:00.000"`, with the offset specified as -07:00 (to represent Phoenix time), I should see the time as `"02:00:00"`. However, because my system clock is in "America/Denver" time zone, it always skips the time forward to `"03:00:00"`.

I should be able to display a date with an offset, without my system time zone affecting the calculation.

See the linked StackBlitz for examples of date strings that should be formatted correctly but are being affected by Daylight Saving Time calculations.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-dtm85s

### Please provide the exception or error you saw

A date string of `"2024-03-10T02:00:00.000"` is being displayed as `"2024-03-10T03:00:00.000"`, even if I specify an offset of `"-07:00"` (or whatever the offset is on the system clock where this is being reproduced).

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Browser: Google Chrome

Angular CLI: 18.2.3
Node: 22.6.0
Package Manager: npm 10.8.2
OS: darwin arm64

Angular: 18.2.3
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, material, material-moment-adapter
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1802.3
@angular-devkit/build-angular   18.2.3
@angular-devkit/core            18.2.3
@angular-devkit/schematics      18.2.3
@angular/flex-layout            15.0.0-beta.42
@schematics/angular             18.2.3
rxjs                            7.8.1
typescript                      5.4.5
zone.js                         0.14.10
```

### Anything else?

I stepped through the date pipe code, and I believe this line is the cause:

https://github.com/angular/angular/blob/950a5540f15118e7360506ad82ec9dab5a11f789/packages/common/src/i18n/format_date.ts#L846

When `date.setMinutes` is called, if the resulting date lands between hours 02:00 and 03:00 on March 10, the time is coerced to be on or after 03:00. The reason (as far as I can tell) is that hour doesn't exist, since Daylight Saving Time would kick in and jump everything forward an hour.

Again, this makes no sense when you are trying to display a date in a time zone that does not observe Daylight Saving Time. I should be able to display a date with an arbitrary offset and not have it be affected by my system clock's time zone.

I believe this issue could be resolved by this one: https://github.com/angular/angular/issues/48279.

**Comment by JeanMeche** [comment] 2024-09-22 22:58
This issue would indeed be adressed by supporting IANA timezones, absolute offsets are not ideal in situation like the one you described. 

We intend to address this issue/feature by providing an Intl based implementation to our i18n-subsystem. See #55283. 

I'll close it as a duplicate of #48279.

**Closed by JeanMeche** 2024-09-22 22:58 UTC

**Comment by cfinlinson-incomm** [comment] 2024-09-24 12:40
@JeanMeche do you have an estimate on when #55283 will be merged? Just wondering if I need to come up with a workaround for now.

**Comment by JeanMeche** [comment] 2024-09-24 15:07
I hope that we can ship it with v19, mid November.
