### ISSUE TITLE
NgZone: gets stuck (onMicroTaskEmpty stops emitting)

### ISSUE THREAD

**Issue by vladjerca** [angular/angular#24055] opened 2018-05-22 18:11 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

The `_nesting` property in `NgZone` reaches a negative value. This prevents the `checkStable` to call the `onMicroTaskEmpty` emitter.

## Expected behavior

If the `_nesting` property reaches a negative point, it should reset OR throw an error (currently, it's more or less a silent death).

## Minimal reproduction of the problem with instructions

[StackBlitz](https://stackblitz.com/edit/angular-sm4bpn-dci4bm?file=src/app/heroes/heroes.component.ts)

1. click on a hero
2. click on another hero
3. notice that the application does not detect the changes

## What is the motivation / use case for changing the behavior?

I'm not sure why or how the `NgZone` nesting value reaches that point in my application, therefore I emulated the behavior by directly setting its value to `-1`.

The zone apparently still works, but given that the `ApplicationRef#tick` doesn't get called, the lifecycle hooks aren't called anymore, leaving the application in an inconsistent state.

I've managed to 'unblock' the zone by locally modifying the `checkStable` method, which clamps the `_nesting` value to `0` if it reaches a negative value. I'm not so sure this is a good solution, but it was done for testing purposes.

## Environment

<pre><code>
Angular version: ^5.2.10

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [x] IE version XX
- [x] Edge version XX

**Comment by JiaLiPassion** [comment] 2018-05-23 01:26
@vladjerca , in your current `StackBlitz`, you set `_nesting` property by yourself, can you post a reproduce repo that `_nesting` will  be updated to `-1` by `angular itself`?

**Comment by vladjerca** [comment] 2018-05-23 08:02
@JiaLiPassion Sadly no, I've been trying to find exactly how the zone nesting reaches that state but no luck.

The idea is that it can happen in 1 minute, or 8 hours. I have no consistent repro. It took a few days just to find out that the zone reaches this state by debugging after the application broke.

**Comment by JiaLiPassion** [comment] 2018-05-24 09:56
@vladjerca , thank you for the analyze, I will check the code again, in your code, do you register the `onStable` or `onUnstable` or `onMicrotaskEmpty` emitter of `ngZone`?

**Comment by vladjerca** [comment] 2018-05-24 10:17
@JiaLiPassion Yes, I use to initialize an object when the rendering is done:

``` ts
this.zone.onMicrotaskEmpty.pipe(
    first()
).subscribe(() => {
    this.zone.runOutsideAngular(() => {
        // SOME UNRELATED CODE HERE
    });
});
```

One small note:

I found that our application injects a `PluginManager`:  https://github.com/shlomiassaf/ngx-modialog/blob/angular-v5-official/src/ngx-modialog/src/providers/outside-event-plugin.ts

In an attempt to stop the `NgZone` from reaching an inconsistent state, I've removed it from our application, and for the time being it seems to prevent the zone lock from occuring (we're not 100% sure, that Plugin manager was the issue) although, even if the plugin is the root cause, some measures should be taken in order to prevent the `_nesting` value to reach that state or at least an informative error should be thrown.

**Comment by JiaLiPassion** [comment] 2018-05-24 15:52
@vladjerca , I checked your code, but I can't figure out why your DomEventPlugin will cause this error, maybe it is not the reason, if you can reproduce this error, it will help a lot. Thanks.

**Comment by vladjerca** [comment] 2018-05-24 22:28
@JiaLiPassion As I said previously, by using the application (normal use-cases, nothing special, eg: switching routes) at some point, it just happens and I'm unable to single out the root cause.

**Comment by JiaLiPassion** [comment] 2018-05-25 02:18
@vladjerca , I know, is that possible to provide your repo so I can debug it?

**Comment by JiaLiPassion** [comment] 2018-05-31 14:35
@vladjerca , the `3rd party EventManager` is this one right? https://github.com/shlomiassaf/ngx-modialog/blob/angular-v5-official/src/ngx-modialog/src/providers/outside-event-plugin.ts

**Comment by vladjerca** [comment] 2018-05-31 14:38
@JiaLiPassion Yes, that's the one.

**Comment by jelbourn** [comment] 2020-10-23 21:38
Closing this since there hasn't been any activity since 2018 and it's unclear there was any bug in play on the zone part.

**Closed by jelbourn** 2020-10-23 21:38 UTC
Labels: comp: zones, needs clarification, needs reproduction, type: bug/fix
