### ISSUE TITLE
Auto-bound property inputs/outputs

### ISSUE THREAD

**Issue by romko391** [angular/angular#28367] opened 2019-01-25 15:00 UTC
# 🚀 feature request

### Relevant Package
This feature request is for `@angular/core`

### Description
I'd be nice to have an auto-bound properties/inputs. Often we need to bind input properties for a child component with the same name as local property of parent.

### Solution
- Currently it's written like:
   `<img [src]="src" />`
- My suggestion is to allow doing the following:
   `<img [src] />`

where `[src]` is understood as a property with the same name in current view's component.

`@Component(...)
class MyImgComponent {
  src = '/path/to/my/image.png';
}`

**Comment by dawidgarus** [comment] 2019-01-26 10:04
@romko391 I'm afraid this might be a breaking change. Existing code may use `[myDirective]` to add directive without any inputs to the element.

**Comment by alxhub** [comment] 2019-01-29 23:41
I don't think it'd be that much of a breaking change, actually. `[myDirective]` only works if the directive has an input called `[myDirective]`.

**Comment by dawidgarus** [comment] 2019-01-30 13:59
@alxhub I've made in the past directives with dummy input for a sole purpose that one can use `[myDirective]` and it won't add extra attribute to host element. Maybe it has little impact, but it's still a breaking change.

**Comment by trotyl** [comment] 2019-01-31 12:54
It still possible to make both `@Input('myDirective')` and `@Input('[myDirective]')` being assigned, for example:

```html
<div [myDirective]="42"></div>
```

Could results in:

```typescript
class MyDirective {
  @Input('myDirective') expressionValue: number // 42
  @Input('[myDirective]') literalValue: string  // "42"
}
```

In this case, it's only breaking when having a deliberate useless `Input` which always expected to got `undefined`, this is not likely to happen.

---

This mechanism can also solve https://github.com/angular/angular/issues/14641 (https://github.com/angular/angular/issues/20901) by producing a better error message once `@Input('[ngFor]')` got used.

**Comment by pkozlowski-opensource** [comment] 2019-02-14 13:52
This is a duplicate of the existing issue #21136

**Closed by pkozlowski-opensource** 2019-02-14 13:52 UTC
Labels: comp: core & compiler, type: feature
