### ISSUE TITLE
Upgrade to version 9 issue

### ISSUE THREAD

**Issue by arti1zz** [angular/angular#35327] opened 2020-02-11 09:32 UTC
Hello! I'm trying to upgrade from angular 8 to 9, everything went ok, but at the end i got an issue. When running the project I'm getting: 

>`\ClientApp\vendor-es2015.js: 'with' in strict mode (195455:4)
>  195453 |   Window_run: function _run(code, file) {
>  195454 |     if (file) code += '\n//@ sourceURL=' + file;
> 195455 |     with(this) eval(code);
         |     ^
  195456 |   },
  195457 |   EventHandlerBuilder_build: function build() {
  195458 |     try {`

Not sure, what could I try to solve this?

**Comment by gkalpak** [comment] 2020-02-11 09:49
You didn't provide enough details about the project, so we can't be sure what is causign the issue. But it sounds like something is not configured correctly in your project (and code meant to run on the server-side is ending up in the JS bundle served to the browser). 

This is likely a duplicate of #34970. See the discussion there (and especially https://github.com/angular/angular/issues/34970#issuecomment-581838896) for details on what might be causing this and how to fix.

**Closed by gkalpak** 2020-02-11 09:49 UTC

**Comment by leonardolondono** [comment] 2020-02-17 17:59
I have the same issue, I created a Web app on Visual Studio and then update to Version 9 to find this issue

**Comment by leonardolondono** [comment] 2020-02-17 18:01
Here is the fix
https://jasontaylor.dev/asp-net-core-angular-9-upgrade/
