### ISSUE TITLE
/deep/ and ::shadow are removed from the .css

### ISSUE THREAD

**Issue by thso** [angular/angular#6511] opened 2016-01-15 14:54 UTC
The component css contains:

    .progress /deep/ #primaryProgress {
      background-color: #ff9500; }

which gets transformed into

    .progress[_ngcontent-iyr-3]   #primaryProgress[_ngcontent-iyr-3] {
      background-color: #ff9500; }

which doesn't work as it needs to pierce the shadow boundary to style the element with the 'primaryProgress' id.

**Comment by zoechi** [comment] 2016-01-15 15:32
I guess you're using `ViewEncapsulation.Emulated`? If you use this encapsulation mode the style rewrite is the "emulation" Angular does. If you set `ViewEncapsulation.Native` Angular shouldn't rewrite the styles anymore.

**Comment by thso** [comment] 2016-01-15 15:42
Yes indeed, I'm using the default `ViewEncapsulation.Emulated`.

IMO, the correct behaviour here is to transform the css to:

    .progress[_ngcontent-iyr-3] /deep/  #primaryProgress {
      background-color: #ff9500; }

**Comment by zoechi** [comment] 2016-01-15 15:52
For mixed environments? (nested `Emulated` and `Native` components)

**Comment by ericmartinezr** [comment] 2016-01-15 15:53
Probably you should stop using it, it has been deprecated https://code.google.com/p/chromium/issues/detail?id=489954

**Comment by thso** [comment] 2016-01-15 16:31
Precision: This is used to style polymer elements and is polyfilled by polymer.

**Comment by zoechi** [comment] 2016-01-15 17:00
Is this for Polymer <=0.5? Polymer 1.x is moving away from `/deep/` and `::shadow` because they're deprecated.

**Comment by mhevery** [comment] 2016-01-20 23:53
Since  `/deep/` and `::shadow`  are deprecated, it is unlikely that we will fix this. 

Sorry will close.

**Comment by QuentinFchx** [comment] 2016-03-02 14:41
@mhevery what are we supposed to use then ?
Having the emulated mode set by default, and having this current limitation is absolutely not helpful. It might even refrain ng2 adoption.
As long as css scoping spec is moving, we should not use it as a default.

A compromise would be to be able to set the default encapsulation mode, instead of having to declare it on each component.

**Comment by zoechi** [comment] 2016-03-02 17:23
@QuentinFchx what are your requirements? Do you want to change the default encapsulation to `None`?. 

With encapsulation `Native` or `Emulated` it's only working well if you add the styles directly to the components. The purpose of encapsulation to prevent styles from bleeding in/out of each other. There are some selectors like `:host-context()` or tools like data binding and class and style binding which allows you to apply styles dynamically depending on values passed from the outside (defined hooks to allow users of the component to modify the styling of your component).

There are still things that can't be done currently or only with very cumbersome workaround and I also hope this will improve

See also 

- https://github.com/angular/angular/issues/6274
- https://github.com/angular/angular/issues/2567

**Comment by QuentinFchx** [comment] 2016-03-02 17:43
@zoechi I'd just like to be able to define the default encapsulation mode for my app to avoid defining the `None` one on every of my component.

Currently it seems that the "Css Scoping" part of the Shadow DOM spec is not stable/complete at all.

`host-context()` is great, but what if the component is a 3rd party and does not handle a specific case?

**Comment by zoechi** [comment] 2016-03-02 18:04
@QuentinFchx I guess you should create a new issue for changing the default ecapsulation globally.

**Comment by tbosch** [comment] 2016-03-11 19:34
Dupe of #7562

**Closed by tbosch** 2016-03-11 19:34 UTC
