### ISSUE TITLE
Routes should have a fixed synonym

### ISSUE THREAD

**Issue by MickL** [angular/angular#13671] opened 2016-12-26 15:00 UTC
**I'm submitting a ...**
```
[ ] bug report
[X] feature request
[ ] support request
```

**Current behavior**
Routes do have only a path and are accessed by this path e.g. `<a routerLink="/crisis-center">Crysis center</a>`

**Expected behavior**
Routes should have a fixed synonym which they can be accessed by.

**What is the motivation / use case for changing the behavior?**
If we want to change a path we have to search all across our app and change it everywhere. This is not just unhandy, it leads into errors if we forget to change it somewhere. In the real world maybe a stakeholder decides to change a path multiple times in the development.

**How other frameworks do it:**
I want to show how its done in the PHP framework Symfony. The configuration is in YAML:

```
blog_show:
    path:      /blog/{slug}
    defaults:  { _controller: AppBundle:Blog:show }
```

Now we have a fixed name `blog_list` which will probably not change. But we can change the path as we want to and the app still keeps working.

To use the link we can generate it with a function:

```
$url = $this->generateUrl(
            'blog_list',
            array('slug' => 'my-blog-post')
        );
```

**Comment by DzmitryShylovich** [comment] 2016-12-26 15:11
Duplicate of https://github.com/angular/angular/issues/13416

**Closed** 2016-12-27 19:22 UTC
