### ISSUE TITLE
10.1.0 Router empty path regression

### ISSUE THREAD

**Issue by akturatech** [angular/angular#38691] opened 2020-09-03 04:20 UTC
# 🐞 bug report

### Summary

Upgrading to Angular 10.1.0 does not stop routing on the first matching route entry.

### Is this a regression?

Yes, this used to work in all previous versions of Angular (from v2 onwards).

### Description

Previous versions of Angular allowed routes to be defined in a prioritized order. As per the screenshot below, we direct the route to specific module if a path is provided, however if no path is provided, we route to the main application module.

![image](https://user-images.githubusercontent.com/23112857/92070529-a0dc9a00-edef-11ea-9814-99c1c2b15235.png)

It appears that V10.1.0 now triggers the last path (the one highlighted in the screenshot above) even if the other paths load first. In our case, if we try to login via the auth path, it first shows the login page for a brief few milliseconds and then it tries to navigate to the main module via the `path: ''` entry but this fails the auth check and redirects back to the auth module and this cycle then repeats forever.

## 🔬 Minimal Reproduction

Removing the highlighted line in the above screenshot stops the repeated loading from occurring. But this isn't a fix as it stops our app from working as well.

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 10.1.0
Node: 12.10.0
OS: linux x64

Angular: 10.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.7
@angular-devkit/build-angular     0.1001.0
@angular-devkit/build-optimizer   0.1001.0
@angular-devkit/build-webpack     0.1001.0
@angular-devkit/core              10.0.7
@angular-devkit/schematics        10.1.0
@angular/cdk                      10.1.3
@ngtools/webpack                  10.1.0
@schematics/angular               10.1.0
@schematics/update                0.1001.0
rxjs                              6.6.2
typescript                        3.9.7
webpack                           4.44.1

</code></pre>

**Comment by indraraj26** [comment] 2020-09-03 08:56
i think you will have to add pathMatch:"full" in path:""

**Comment by akturatech** [comment] 2020-09-03 21:41
Good morning @indraraj26 . Thank you for your suggestion. 

I tested this and unfortunately it doesn't work. The reason is that the last route redirects to our main module which has many routes of its own. With a full match, the routes within the main module no longer work.

Hopefully this explains our routing system (which was implemented when the first version of angular was released with lazy loaded modules and has worked until now):

```
/ : app module. has shared libraries for parent modules (auth, main etc)
  /auth : auth module allows login, signup etc. auth modules has its own lazy loaded modules
  / : main module. has guard to stop access. redirects to auth if not logged in. has shared libraries for main modules
    request : example lazy loaded page. this has its own modules as well
    calendar : another example lazy loaded page
    ...
```
Some examples paths are:

```
/ : will try to access main module which will redirect to requests module if logged in. if not, will redirect to auth module to log in
/auth/sign-in 
/requests/edit : will work only if signed in
/calendar : will work only if signed in
```

**Comment by akturatech** [comment] 2020-09-03 21:51
OK I tried changing the path to '**' instead of empty and this actually gets me a little bit further - it now loads the main module but doesn't load any of the children in the main module.

My main module has routes like this:
![image](https://user-images.githubusercontent.com/23112857/92176767-7daefa80-ee82-11ea-838e-71ede1490d99.png)

I'm guessing here that '**' in the app route is consuming the entire path and therefore only the path:'' at the top of the main route is matching.

The only way i can get the new version of Angular to work is to provide the main module with a path name like this:
![image](https://user-images.githubusercontent.com/23112857/92176899-c49cf000-ee82-11ea-9ec8-d1249ca30ac5.png)

But this is not an option for me as our app is used by our users to build forms and each form has a path that is included in an email that our users send to our clients. Changing our path to these forms is clearly not an option as it will disrupt several hundred users.

**Comment by indraraj26** [comment] 2020-09-04 03:52
Hi @akturatech , 

Do you have router-outlet in MainComponent.html it is needed so that children can render, as you are not using component-less routing.

Also is it possible for you provide to reproduction via stackblitz ?

**Comment by akturatech** [comment] 2020-09-04 05:03
Hi @indraraj26 
Yes I do have a router outlet. I can try to create a repeatable project. I will work on it tomorrow.
Not sure if it will help, but I can give you access to our source code if it helps. The source code is pretty easy to fail - is working in 10.0.12 and then when do 'ng update @angular/core @angular/cli' it upgrades seamlessly but routing no longer works.

**Comment by akturatech** [comment] 2020-09-04 06:24
Hi @indraraj26,

Example project is here in v10.0.9. It works: https://stackblitz.com/edit/angular-ivy-hjbn23
If you upgrade to v10.1.0 it blows up.

The reason is that the guard on the empty path in the app module is running when it shouldn't be. It should run only when the path: '' is activated, but it runs even if we go to '/auth' path. This is only happening in 10.1.0 and not in older versions.

**Comment by akturatech** [comment] 2020-09-04 06:45
One more clue - if i name the empty path (eg path: 'main') then the guard works correctly and runs only when the 'main' path is activated. So the issue is:
canLoad on an empty path is running the guard even if the path is not being activated.

**Comment by AlexanderOpran** [comment] 2020-09-08 16:03
We have the exact same issue as described by @akturatech. Any updates regarding this?

**Comment by akturatech** [comment] 2020-09-08 20:43
@AlexanderOpran No. This issue seems to haven fallen through the cracks.

@indraraj26 Do you know how I can raise this with the angular team as we've had no response yet. Should I re-raise the issue again?

**Comment by akturatech** [comment] 2020-09-09 08:09
@AlexanderOpran I wonder if it is worth you raising this as your own issue and linking back to this one or including my stackblizt replicating the issue? All the newer bugs seem to be getting assigned to people and have confirmed tags etc. This one seems to have been lost.

**Comment by atscott** [comment] 2020-09-09 19:33
Likely caused by https://github.com/angular/angular/commit/d7dd2959c87d4539e08e3337f22caaf91705e0ba which should be reverted.

**Comment by atscott** [comment] 2020-09-09 19:59
Note that as a temporary workaround, you can use 
`return this.router.createUrlTree(['auth']);` 
instead of 
```
this.router.navigate(['auth']);
return false;
```
because the PR was meant to respect the ordering with prioritization, but only works with returning `UrlTrees` and fails to do so if a guard calls `router.navigate` to "redirect" which cancels the current navigation immediately and proceeds with the new one.

**Comment by akturatech** [comment] 2020-09-09 21:10
@atscott Thank you for the update and workaround :)

**Comment by atscott** [comment] 2020-09-09 23:14
@akturatech I have a fix for this out for review and it should make it into the `10.1.2` release next week. If you want the fix now, it actually happens to already be fixed in `11.0.0-next.1`.

**Comment by emillime** [comment] 2020-09-10 13:51
> Note that as a temporary workaround, you can use
> `return this.router.createUrlTree(['auth']);`
> instead of
> 
> ```
> this.router.navigate(['auth']);
> return false;
> ```
> 
> because the PR was meant to respect the ordering with prioritization, but only works with returning `UrlTrees` and fails to do so if a guard calls `router.navigate` to "redirect" which cancels the current navigation immediately and proceeds with the new one.

I have the same issue, thank you for the workaround! 
But what do we return as UrlTree in the case where it returned true before?

**Comment by atscott** [comment] 2020-09-10 16:06
Fixed in https://github.com/angular/angular/commit/9c51ba321e16c6c1055c928d9cded29b3b4d71c7

**Closed by atscott** 2020-09-10 16:06 UTC
Labels: comp: router, freq2: medium, router: config matching/activation/validation, router: lazy loading, severity5: regression, type: bug/fix

**Comment by akturatech** [comment] 2020-09-10 22:50
That is awesome @atscott . Thank you so much. 
Love Angular and love the team as well. Such a great framework.

**Comment by nutza249949** [comment] 2020-09-11 10:40
o

**Comment by akturatech** [comment] 2020-09-15 23:28
@atscott Thank you for the workaround suggestion. I finally got to test it. Unfortunately setting UrlTree doesn't work for us as the guard redirects to a different subdomain on authentication failure (or app has a subdomain per user and a root subdomain for login) and therefore we cannot use UrlTree. 
I'll report back when 10.1.2 is released and let you know if the fix works.

**Comment by AlexanderOpran** [comment] 2020-09-17 15:48
Issue still persists even with `10.1.2`

**Comment by atscott** [comment] 2020-09-17 15:59
Hi @AlexanderOpran, could you provide a reproduction? The stackblitz for this report does work with 10.1.2: https://stackblitz.com/edit/angular-ivy-sez7kw?file=src%2Fapp%2Fapp.component.ts

**Comment by akturatech** [comment] 2020-09-17 22:26
Good morning @atscott. I can confirm my project now works perfectly with 10.1.2. Thank you!!

**Comment by AlexanderOpran** [comment] 2020-09-18 04:56
@atscott  I will try and do a stackblitz to reproduce this. Perhaps another related issue but router.navigate does not seem to work from inside guards. It will trigger the module guard infinitely even if the page/module I try to navigate to is not protected by any. This is also happening only with the ** path, no the named ones.
