### ISSUE TITLE
Empty path route is unexpectedly matched when unrelated lazy loaded route exists

### ISSUE THREAD

**Issue by bufke** [angular/angular#32852] opened 2019-09-25 14:17 UTC
### Affected Package
The issue is caused by package @angular/router

### Is this a regression?

No, tested in Angular 6 and 8.

### Description

An empty path (`path: '',`) route will match unexpectedly when lazy loading is performed. For example, in the reproduction stackblitz I have a empty path HomeComponent and a lazy loaded module with no routes nor components in it. The expected behaviour of going to a path that triggers the lazy loaded route (in my example `/lazy`) is that no route is found and it errors with `Cannot match any routes. URL Segment: 'lazy'`. Instead it matches the empty path home route.

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-issue-repro2-fjxbqt

**Anything else relevant?**

Why is this important? If one is adding dynamic routes in a lazy loaded module, I would want those routes to match after they are inserted into router.config. Instead the empty path matches.

**Workaround**

In the lazy loaded module, just adding the import `RouterModule.forChild([])` works around the issue.

**Comment by djleonskennedy** [comment] 2019-09-30 07:40
@bufke Hello, you need to add routes setup for lazy module
here i've modified your reproduction 

https://stackblitz.com/edit/angular-issue-repro2-h7eebq?file=src/app/lazy/lazy.module.ts

**Comment by bufke** [comment] 2019-09-30 14:09
@djleonskennedy that isn't related to the issue. The bug here is that when these routes don't exist, I'd expect the "Cannot match any routes" error. Matching the unrelated empty string route is unexpected and can complicate some use cases for dynamic routing. If you are curious on a more complex use case of dynamic routing in Angular you could look at my project [Angular Wagtail](https://gitlab.com/thelabnyc/angular-wagtail).

**Comment by djleonskennedy** [comment] 2019-10-05 20:30
@bufke thank you for answer, could be related https://github.com/angular/angular/issues/17957

**Comment by bufke** [comment] 2019-10-06 16:08
`relativeLinkResolution: 'corrected'` does not change the results.

**Comment by atscott** [comment] 2020-05-29 17:19
Somewhat related issue: #23760

**Comment by nhuyvan** [comment] 2020-10-18 16:41
@bufke Oh geez, thank you for this workaround that you suggested **In the lazy loaded module, just adding the import RouterModule.forChild([]) works around the issue.**, was so frustrated because one of my lazy loaded modules kept matching the empty path `""`, I have 2 lazy loaded routes, one of them matches correctly, while the other one kept matches the empty route.

**Comment by atscott** [comment] 2022-06-27 23:17
Closing as resolved at some point. Updating the demo to v14 resolves the issue: https://stackblitz.com/edit/angular-issue-repro2-aggcnm?file=src%2Fpolyfills.ts,src%2Findex.html

**Closed by atscott** 2022-06-27 23:17 UTC
Labels: type: bug/fix, freq1: low, comp: router, state: confirmed, router: lazy loading, router: config matching/activation/validation, P3
