### ISSUE TITLE
Uncaught error occurred when Anuglar DevTools open and not showing any components

### ISSUE THREAD

**Issue by ghost** [angular/angular#52317] opened 2023-10-23 02:38 UTC
### Is this a bug report or a feature request?

- [X] Bug Report
- [ ] Feature Request

### Please provide the steps to reproduce the issue [Bug Report only]

I don't know how to reproduce the error. but I can give you only some information

Angular v16
Open Angular DevTools

Uncaught error occurred when open Angular DevTools and components are not shown in Angular tab.

### Please provide the expected behavior vs the actual behavior you encountered [Bug Report only]

Components should be shown

### Please provide a screenshot if possible [Bug Report only]

<img width="1329" alt="Screenshot 2023-10-23 at 11 32 44 AM" src="https://github.com/angular/angular/assets/96810812/c7e8e896-3dbb-408b-8b72-28248eec3367">

### Please provide the exception or error you saw [Bug Report only]

```true
The error message is shown as following


zone.js:1681 Uncaught Error: ASSERTION ERROR: The provided value must be an instance of a DOM Node but got [object HTMLStyleElement]
    at throwError (core.mjs:328:11)
    at assertDomNode (core.mjs:333:9)
    at getLContext (core.mjs:6537:22)
    at getDirectives (core.mjs:22979:21)
    at Tt (render-tree.ts:15:26)
    at render-tree.ts:52:23
    at NodeList.forEach (<anonymous>)
    at Tt (render-tree.ts:51:28)
    at render-tree.ts:52:23
    at NodeList.forEach (<anonymous>)
```
```


### Is this a browser-specific issue? If so, please specify the device, browser, and version. [Bug Report only]

```true
Chrome
```

**Comment by JeanMeche** [comment] 2024-04-07 06:56
Looks like this is a dupe of #47357.

**Closed by JeanMeche** 2024-04-07 06:56 UTC
Labels: area: devtools
