### ISSUE TITLE
Video loading is slow when service-worker is enabled. 

### ISSUE THREAD

**Issue by ChengYuHin99** [angular/angular#32845] opened 2019-09-25 01:55 UTC
I am using "@angular/service-worker": "6.0.0".
My angular website is hosted in firebase.
And there is page which plays remote videos which stored in google cloud storage.
Problem is as following.
1) When disabled service-worker (pwa), then loading video is done within 3 seconds.
2) When enabled service-worker (pwa), then loading video is done within 10 minutes.

This happens always. not thing which occurs sometimes.

Please let me know why this happens.
Thanks

**Comment by gkalpak** [comment] 2019-09-25 15:40
Thx for reporting this issue. Based on the provided info, it is impossible to tell what the issue might be. It could be a browser bug (you did not mention which browsers are affected and which browsers you have tested this on). It could also be an issue that has been fixed in a more recent version of `@angular/service-worker`.

I am going to close this issue, since it is not actionable in its current form. Please try upgrading to the latest Angular version and if the problem persists, open a new issue providing all necessary details (see the issue template), including a minimal reproduction.

**Closed by gkalpak** 2019-09-25 15:40 UTC
Labels: comp: service-worker

**Comment by ChengYuHin99** [comment] 2019-09-25 16:03
Hi, thanks for your reply.
I tested with chrome 77.0.3865.90 - 64 bit. 
There is problem for upgrading angular version.
Because project is huge and it will take much time to upgrade and work safely.
I need to solve this problem with current angular version (angular version 6.0.1).
Anyhow thanks for your comment.

**Comment by gkalpak** [comment] 2019-09-25 16:26
I see. Things I would try to narrow down the problem:
- Test on other Chrome versions.
- Test on other browsers.
- Try upgrading `@angular/service-worker` to the latest version (just the `@angular/service-worker` package not other packages). Generally, you should always use matching versions, but it might be worth trying this out (I think it should work in this case, but I might be wrong).

**Comment by ChengYuHin99** [comment] 2019-09-25 23:44
From version 7.0, it is not compatible. so I updated service  worker version to 6.1.0.
But still same.
I analyzed network by google chrome.
This is screenshot when disabled service worker. It only  download 132 Bytes.
![image](https://user-images.githubusercontent.com/29444609/65647302-e0700300-e030-11e9-8efd-ed8841cd65d4.png)

This is screenshot when enabled service worker. In this case, service worker download full content of video file.
![image](https://user-images.githubusercontent.com/29444609/65647441-4a88a800-e031-11e9-90cc-4f335dd85ddc.png)

Could you let me know how to disable service worker for some specific urls and file extensions?
Thanks.

**Comment by ChengYuHin99** [comment] 2019-09-26 07:13
@gkalpak 
I solved this problem.
Thanks for your support.

**Comment by gkalpak** [comment] 2019-09-26 11:15
Glad to hear you worked it out, @ChengYuHin99 :+1:
Please, consider adding some info regarding how you solved it in case someone runs into the same problem in the future 🙏
