### ISSUE TITLE
Need way to wait until parent guard is complete before moving on.

### ISSUE THREAD

**Issue by jrgleason** [angular/angular#13612] opened 2016-12-21 14:43 UTC
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Basically I have 2 guards a child and a parent. The child guard navigates to a child route. The problem is the child guard is getting resolved before the parent. 

[Here is a plunker](https://plnkr.co/edit/yK0eGoUGIVvKZu45jSBs?p=preview).

Also seems related to https://github.com/angular/angular/issues/11161 but from what the tests look like on that merge, it isn't doing what I describe here.

**Expected behavior**
I need a way to tell the child guard to wait until the parent has returned true before continuing.

**Please tell us about your environment:**
OSX, VIM/Sublime, Webpack

* **Angular version:** 2.0.X
2.3.0

* **Language:** [all | TypeScript X.X | ES6/7 | ES5] TS2

**Comment by DzmitryShylovich** [comment] 2016-12-21 15:02
Duplicate of https://github.com/angular/angular/issues/12627?

**Comment by jrgleason** [comment] 2016-12-21 15:21
I will take a look thanks for pointing that out

**Closed** 2016-12-21 15:26 UTC
