### ISSUE TITLE
Bad link on https://angular.dev/api/elements/createCustomElement

### ISSUE THREAD

**Issue by fredsa** [angular/angular#56855] opened 2024-07-04 20:20 UTC
### Describe the problem that you experienced

https://angular.dev/api/elements/createCustomElement contains this corrupt href link:

```
<a class="docs-pill" href="guide/elements &quot;Turning Angular components into custom elements&quot;">Angular Elements Overview</a>
```

### Enter the URL of the topic with the problem

https://angular.dev/api/elements/createCustomElement

**Comment by JeanMeche** [comment] 2024-07-05 11:27
Duplicate of #56857

**Closed by JeanMeche** 2024-07-05 11:27 UTC
Labels: area: adev
