### ISSUE TITLE
[Mozilla][ngModel][SELECT][JS] ngModel is not working for SELECT element in Mozilla 

### ISSUE THREAD

**Issue by llike** [angular/angular#7458] opened 2016-03-07 12:11 UTC
* **I'm submitting a ... **
[x] bug report

* **What is the current behavior?**
Currently two way binding via ngModel is not working in Mozilla FF for SELECT element, value is binded one time and option change  is not updating model.
I was checked it in Google Chrome browser and there it is working.

Code is from your example for JS:
` <select class="form-control" required
		    [(ngModel)]="model.power"
		    ngControl="power" #power="ngForm" >
		    <option *ngFor="#p of powers" [attr.value]="p">{{p}}</option>
</select>`

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** 
Please run your own example on mozilla
https://angular.io/resources/live-examples/forms/js/plnkr.html

* **Please tell us about your environment:**
- Angular version: 2.0.0-beta.8
- Browser: [ Mozilla FF 44.0.2 ]
- Language: [ES5]

**Comment by ericmartinezr** [comment] 2016-03-07 12:12
dup of https://github.com/angular/angular/issues/6573

**Comment by mohamedb** [comment] 2016-03-10 19:03
I had similar problem in beta.07, at the moment I thought I'm the only one having this issue because I include some js libs.
I end using (blur) event on Select coupled with ElementRef.nativeElement to "update" the model.

**Comment by tchoulihan** [comment] 2016-04-14 23:36
Having the same problem. Does anyone know of a workaround?

**Comment by ericmartinezr** [comment] 2016-04-14 23:42
The possible workarounds for this issue are in https://github.com/angular/angular/issues/6573

**Comment by kara** [comment] 2016-04-18 22:05
Closing as a dupe of #6573!

**Closed by kara** 2016-04-18 22:05 UTC
