### ISSUE TITLE
Placing two or more instances of the same Angular Element on the same page breaks routing

### ISSUE THREAD

**Issue by VygintasC** [angular/angular#41339] opened 2021-03-24 20:53 UTC
# 🐞 bug report

### Affected Package
@angular/elements
@angular/router

### Is this a regression?

No.

### Description

When two or more instances of the same Angular Element are loaded on the same page of a parent Angular 10 app, the routing inside those elements breaks and stays broken even after the extra elements are removed.

## 🔬 Minimal Reproduction
Can't reproduce this issue in stackblitz because the Angular Element needs to be built and packaged separately. Will try to create a test repo soon.

Steps are pretty simple, include two instances of the same element in a template of a parent Angular10+ app:
```
<ng-element1 id="1"><ng-element1>
<ng-element1 id="2"><ng-element1>
```

To test the routing, the element needs to contain 2 simple routes with a single router-outlet. 
-->

## 🔥 Exception or Error
No exceptions thrown.

## 🌍  Your Environment

**Angular Version:**
<pre><code>
10
</code></pre>

**Anything else relevant?**

**Comment by atscott** [comment] 2021-03-25 18:05
Duplicate of #34377 / #23740 / #27113 / #36711 / #31587

**Closed by atscott** 2021-03-25 18:05 UTC
Labels: comp: elements, comp: router
