### ISSUE TITLE
Select attribute "multiple" always generates an array as resulting model

### ISSUE THREAD

**Issue by andreas-aeschlimann** [angular/angular#47386] opened 2022-09-08 14:40 UTC
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

By specification, the multiple attribute in a select should be boolean. 

The browsers seem to respect this attribute well, but in Angular I always get an array (model) as soon as the attribute is given, no matter what the value is.

This means that the use of `<select [multiple]="dynamicValue">...</select>` for single selects (with `dynamicValue = false`) is cumbersome because the resulting model is always an array.

### Please provide a link to a minimal reproduction of the bug

https://angular-ivy-xzpi8z.stackblitz.io

### Please provide the exception or error you saw

```true
Number 2 in the example link shows unexpected an behavior.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular 14 (see Stackblitz)
```

**Comment by Totati** [comment] 2022-09-08 15:03
Angular uses two different selectors for [Select](https://angular.io/api/forms/SelectControlValueAccessor) and [select multiple](https://angular.io/api/forms/SelectMultipleControlValueAccessor) . They can't be changed during runtime. You have to `*ngIf` your select.

**Comment by JoostK** [comment] 2022-09-08 15:08
@Totati is correct here; this is a limitation of how control value accessorts are applied statically. Closing as a duplicate of #13243.

**Closed by JoostK** 2022-09-08 15:08 UTC
