### ISSUE TITLE
angular 2 can't run on IE browser

### ISSUE THREAD

**Issue by hbzyin** [angular/angular#18338] opened 2017-07-26 02:08 UTC
## Current behavior

Run `ng serve` or `ng build` it cannot work on IE EXPOLER 

## Expected behavior

when I run my project on chrome and safari it works nomally ,but when i use IE9/10 it cannot work well,the pollyfill suggested by other developers is all in my poolyfill.ts 

 

## Environment

polyfill.ts is as bellow
<pre>
import 'core-js/es6/symbol';
import 'core-js/es6/object';
import 'core-js/es6/function';
import 'core-js/es6/parse-int';
import 'core-js/es6/parse-float';
import 'core-js/es6/number';
import 'core-js/es6/math';
import 'core-js/es6/string';
import 'core-js/es6/date';
import 'core-js/es6/array';
import 'core-js/es6/regexp';
import 'core-js/es6/map';
import 'core-js/es6/set';
import 'classlist.js';  // Run `npm install --save classlist.js`.
import 'web-animations-js';  // Run `npm install --save web-animations-js`.
import 'core-js/es6/reflect';
import 'core-js/es7/reflect';
import 'web-animations-js';  // Run `npm install --save web-animations-js`.

import 'zone.js/dist/zone';  // Included with Angular CLI.

import 'intl';  // Run `npm install --save intl`.
import 'intl/locale-data/jsonp/en';
import 'typedarray/index';
import 'es6-shim';
import 'angular2-ie9-shims/shims_for_IE@2.1.2';
import 'angular2-ie9-shims/shims_for_IE@2.0.0-beta.17';
import 'angular2-ie9-shims/shims_for_IE.dev';
import 'blob-polyfill/Blob';
import 'formdata-polyfill/FormData';

<code>
Angular version: 4.0.2

Browser:
- [ ] IE version 10
 
For Tooling issues:
- Node version: 6.9.5  
- npm version: 3.10.10  
- angular-cli version: 1.2.1  
- Platform:  Mac  pro 10

Others:
- IDE : webstorm  

</code></pre>

Any other have the same problem or is there any other suggest to solve this ?

**Comment by brutalimp** [comment] 2017-07-26 02:27
what is the error message?

**Comment by hbzyin** [comment] 2017-07-26 02:30
the error information output by the console is bellow 
SCRIPT1002: 语法错误 
vendor.e597df93ad3983608698.bundle.js, 行72914 字符1
SCRIPT5007: 无法获取未定义或 null 引用的属性“call” 
inline.4b7ea4f8df48479bbe5d.bundle.js, 行53 字符12

**Comment by brutalimp** [comment] 2017-07-26 02:59
you better run unbundled code using systemjs so that you can locate which line runs error , also just use English.

**Comment by trotyl** [comment] 2017-07-26 03:12
Cannot reproduce, works fine in IE9 with built-in (uncommented) polyfills:

![image](https://user-images.githubusercontent.com/6059170/28602866-18bab75e-71f3-11e7-865f-e6ece6fecffd.png)

Please make sure you're using latest Angular CLI version or having added the `WeakMap` polyfill.

**Comment by vicb** [comment] 2017-07-26 16:44
Closing as not actionable without repro.

**Closed by vicb** 2017-07-26 16:44 UTC
