### ISSUE TITLE
NgModule.imports of AppModule, but could not be resolved to an NgModule class.

### ISSUE THREAD

**Issue by sonali395** [angular/angular#37134] opened 2020-05-15 13:36 UTC
I migrated my Angular library from 8 to 9. I am able to build by libraray succcesfully. But when I serve my app linked to library I get the following error **. __ivy_ngcc_bak with an ngcc back up file, which is disallowed.**
This error on goes off when I clear by dist folder, build everything again sequentially.
I have postinstall:ngcc in my scripts in package json. Still no luck.
Please guide me to get rid of this issue.

**Comment by petebacondarwin** [comment] 2020-05-15 14:00
Hi @sonali395 - we need a few more details before we can accurately diagnose your problem. There are a number of different reasons why ngcc (our compatibility compiler) is trying to write to the same file twice - which is what this error indicates.
Is it possible to share your project with us or a cut down version that demonstrates the issue? Without it there is not much we can do.

**Comment by chriscarpenter12** [comment] 2020-05-15 21:06
I am seeing the same issue as @sonali395. If you build your library and use npm [link](https://docs.npmjs.com/cli/link) to create a global reference to your library to test in a local application. You get this error I assume because the consuming application has ran ngcc on the lib and the library chokes on this because it was process by the other app.

Steps to reproduce:
```
ng build my-lib --prod --watch
npm link dist/my-lib
```
Got to another angular app
```
npm i
npm link my-lib
```
Modify the lib to let it rebuild and get the error
```
------------------------------------------------------------------------------
Building entry point 'my-lib'
------------------------------------------------------------------------------
Compiling TypeScript sources through ngc
Compiling my-lib : es2015 as esm2015
ERROR: Tried to overwrite /home/chris/projects/library/angular/dist/my-lib/lib/icon/component.d.ts.__ivy_ngcc_bak with an ngcc back up file, which is disallowed.

Compilation failed. Watching for file changes...
```

**Comment by lukaonik** [comment] 2020-05-18 13:44
I had the same issue removing --prod flag from build fixed my issue maybe it helps, just run
`ng build my-lib --watch`

**Comment by petebacondarwin** [comment] 2020-05-19 11:28
Just to be clear... Removing the `--prod` flag from the `ng build my-lib` will cause the library to be built via the Ivy compiler. This is great for local testing. But when you come to publish the library to npm, you should use `--prod` to ensure the library is built via the ViewEngine compiler, which is the required format for publicly published libraries.

**Comment by lukaonik** [comment] 2020-05-19 11:43
> Just to be clear... Removing the `--prod` flag from the `ng build my-lib` will cause the library to be built via the Ivy compiler. This is great for local testing. But when you come to publish the library to npm, you should use `--prod` to ensure the library is built via the ViewEngine compiler, which is the required format for publicly published libraries.

yes absolutely. nice catch  :)

**Comment by sonali395** [comment] 2020-05-19 13:03
```
     _                      _                 ____ _     ___ 
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | | 
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | | 
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.1.6
Node: 12.14.1
OS: win32 x64

Angular: 9.1.7
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.901.6
@angular-devkit/build-angular      0.901.6
@angular-devkit/build-ng-packagr   0.901.6
@angular-devkit/build-optimizer    0.901.6
@angular-devkit/build-webpack      0.901.6
@angular-devkit/core               9.1.6
@angular-devkit/schematics         9.1.6
@angular/cdk                       8.2.3
@angular/cli                       9.1.6
@ngtools/webpack                   9.1.6
@schematics/angular                9.1.6
@schematics/update                 0.901.6
ng-packagr                         9.1.4
rxjs                               6.5.5
typescript                         3.8.3
webpack                            4.43.0
````


I no longer see the old error instead I witness the below error when I make any change in my library with --watch. The build is succeded always on change but application serve fauls with below errors. These errors are gone when I clear dist and rebuild and serve again. But with each change in my library, I can't do the same process.

dist/components/lib/modules/stepper/stepper.module.d.ts:1:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.

This likely means that the dependency (@flare/components) which declares FlareStepperModule has not been processed correctly by ngcc.

1 export declare class FlareStepperModule {
                       ~~~~~~~~~~~~~~~~~~
dist/components/lib/modules/outer-click/outer-click.module.d.ts:1:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.

This likely means that the dependency (@flare/components) which declares FlareOuterClickModule has not been processed correctly by ngcc.

1 export declare class FlareOuterClickModule {
                       ~~~~~~~~~~~~~~~~~~~~~
dist/components/lib/modules/filters/filters.module.d.ts:1:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.

This likely means that the dependency (@flare/components) which declares FlareFiltersModule has not been processed correctly by ngcc.
                      ~~~~~~~~~~~~~~~~

**Comment by sonali395** [comment] 2020-05-19 20:11
@petebacondarwin Plese check this **https://github.com/sonali395/angular-test.git**  small example with same issue.

Steps to reproduce
1. run ng build my-lib --watch
2. ng serve
3 make a change in lib component and save
4. check the terminal which is serving application.

Please note: library : Ivy is turned off 
application : ivy is on
package has script postinstall : "ngcc"

I am a library author and after upgarding my lib and demo app linked to it to angular 9, the above issue is witnessed.

**Comment by mukundkatpatal** [comment] 2020-05-20 10:09
Hi @petebacondarwin 
@sonali395 has provided you the repo. Can you please consider changing the status from `needs repo`?
We are library developers and we are stuck. It would be frustrating to clean the dist folder, recompile lib and then start ng serve every time we change the library for our local development and test.

Thank you in advance.

**Comment by petebacondarwin** [comment] 2020-05-20 10:16
Hi @mukundkatpatal and @sonali395 - thanks for the reproduction. I will take a look by tomorrow at the latest.

**Comment by lukaonik** [comment] 2020-05-20 10:59
if you have the library and application on the same workspace, there is no need for linking libraries, or building both of them, all you have to do is setting correct path to tsconfig.json. I checked your git repo, and you are setting path to the dist folder, replace it with that

```
"paths": {
      "my-lib": ["./projects/my-lib/src/public-api.ts"]
  }
```

(if you already link libraries unlink, delete node_modules and reinstall again)

now just run only ng serve  command and it should work. you can import the same way as you did

`import {  MyLibModule } from "my-lib"
`
also, it will react on library file changes and reload automatically

**Comment by mukundkatpatal** [comment] 2020-05-20 13:43
@lukaonik it worked. thank you Very much. @petebacondarwin You can close the issue.

**Comment by petebacondarwin** [comment] 2020-05-20 13:46
Glad you are sorted. We really need to document this...  cc @aikidave

**Comment by sonali395** [comment] 2020-05-21 11:46
@petebacondarwin @lukaonik Thanks for the above solution . It worked when I am consuming my lib in the application of same workspace. Although I added another library **mylib2** in my project and imported it in **my-lib** . I get a build error on building my-lib(first library)
![image](https://user-images.githubusercontent.com/21099519/82556027-3ae24480-9b69-11ea-8fc9-f51e10fb6ff1.png)
Please find the repo in https://github.com/sonali395/angular-test
Please reply asap.

**Comment by aikidave** [comment] 2020-05-21 15:11
Thanks for bringing this to my attention! I'll work on prioritizing adding `ngcc` documentation to angular.io.

**Comment by sonali395** [comment] 2020-05-23 19:30
@petebacondarwin @lukaonik  Please suggest a workaround.

**Comment by petebacondarwin** [comment] 2020-05-23 21:24
@sonali395 - I'm sorry you are still having problems. I'll take a look on Monday

**Comment by petebacondarwin** [comment] 2020-05-25 15:22
OK, so @alan-agius4 has helped my with my understanding of this... Here is my take on it.

When developing your libraries, you build them without the `--prod` flag (`--prod` is badly named in this case - it really means "build for publishing to npm").  This will build the library in "Ivy mode" using the Angular compiler.  For example in this case when you run `ng build mylib2`. This will result in the library being built (with Ivy) and stored in the `dist/mylib2` folder. One could also do this for other libraries in the workspace.

_By the way you had disabled ivy in the non-prod library tsconfig.json files, which means that it is always going to build the library in non-ivy mode, even when doing local testing._

The issue you are having is when one build (e.g. an application or library) relies upon one of the other libraries in the workspace. This is dealt with by path mappings, as previously discussed in this issue. But it is important to understand that you are not mapping to the original source code of the library but instead to the built output (i.e. in the `dist/...` folder).  Therefore, in this case, the path mappings in the top level tsconfig.json should look like:

```json
    "paths": {
      "my-lib": [
        "dist/my-lib"
      ],
      "mylib2": [
        "dist/mylib2"
      ]
    }
```

_Note that the mapping is to the `dist` folders not the original source files._

Now you can build any of the targets in non-prod mode and it will work. The common requirement is to use the application target as a test environment for the library. You can do this by watching the build of the library while serving the application:

```
ng build my-lib --watch
ng serve 
```

_Note that the last line is serving the default target which in the case of your repository is the `test-workspace` app._

Now whenever you make a change to the `my-lib` source, it will rebuild and then the application will pick up the change and also rebuild.

I have sent a PR to your test repo to demonstrate the fix: https://github.com/sonali395/angular-test/pull/1

**Comment by petebacondarwin** [comment] 2020-05-25 15:28
Closing, as I believe this is now sorted. @sonali395 - please comment if there is still a problem.

**Closed by petebacondarwin** 2020-05-25 15:28 UTC
Labels: comp: ngcc, flag: can be closed?, state: works-as-expected, triage #1

**Comment by sonali395** [comment] 2020-06-03 13:24
@petebacondarwin Do you mean that we should never our library with non-ivy mode on local. Because If Build my library in non-invy mode now with ``dist/... `` folder path mappings then I move back to my old problem for which @lukaonik provided the solution.

Basically With @lukaonik , My application builds fine and detects all the changes in Non-ivy mode whereas with your commits I see It works fine only if I build my local with IVY mode.

**Comment by petebacondarwin** [comment] 2020-06-03 13:27
Earlier you said that @lukaonik's did not solve the problem of one library relying upon another:

> It worked when I am consuming my lib in the application of same workspace. Although I added another library mylib2 in my project and imported it in my-lib . I get a build error on building my-lib(first library)

**Comment by sonali395** [comment] 2020-06-03 15:38
So Here are two problems. 
1. Create a library with supportting app and build it in non-ivy mode. The path in this case in tsconfig refrence to dist folder format. Now when you build and serve. It fails to serves application and the module is not found if you make any changes in watch mode in the library.

2. Create another library in same workspace and use its module in the first library. It will build only if path is in ist folder format.

Both of the above scenarios are for non-ivy mode. I am looking for a solution which can solve both.
The solution which @lukaonik provided solves only first problem and causes the second issue.

**Comment by petebacondarwin** [comment] 2020-06-03 15:48
The recommended solution is to do your primary testing using ivy-mode using path-mappings, which provide the fastest developer experience for you.
If you wish to run these primary tests in ViewEngine mode, then I believe you need to switch all the libs and app to have `enableIvy: false` in their tsconfig.json files.
If you want to test a hybrid where the app is in ivy-mode and the libraries are in their published (ViewEngine mode) state, then the best option is to pack them into a `.tgz` file and then have a test app that imports this file via its package.json dependencies.

**Comment by sonali395** [comment] 2020-06-04 12:44
So What I understood here is I should keep the ivy enabled on my local but when I publish my library I should set ivy to false and publish it.

**Comment by alan-agius4** [comment] 2020-06-04 13:00
@sonali395, that is correct.
By default, when running `—prod` on a library project it will be compiled using the old rendering engine instead of ivy.
