### ISSUE TITLE
Angular forms modifes form status  when any form directives used

### ISSUE THREAD

**Issue by kbrilla** [angular/angular#55030] opened 2024-03-25 15:29 UTC
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

No

### Description

When any of form directives like `[formGroup]`, `[formControl]` etc.., are used then validity of forms is updated but no information of it is present as no events are executed. 

using setTimeout to setError also works.

![image](https://github.com/angular/angular/assets/22288449/068ec8e4-b6fb-457d-a804-48d331161172)

It is possible that attaching form directives caues validators to run and thus reseting errors but still I would expect to see status change event at least. 

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/~/github.com/kbrilla/angualr-error-setErrors

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.3.1
Node: 18.18.0
Package Manager: npm 10.2.3
OS: linux x64

Angular: 17.3.1
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1703.1
@angular-devkit/build-angular   17.3.1
@angular-devkit/core            17.3.1
@angular-devkit/schematics      17.3.1
@schematics/angular             17.3.1
rxjs                            7.8.1
typescript                      5.3.3
zone.js                         0.14.4
```

**Comment by pankajd24** [comment] 2024-03-26 06:37
this.form.statusChanges method works when form status is changed. here form status is  not changing even after onChange event.  So you have to provide at least one validation in new FormControl(0,[ ]) , so that formControl and form  validation state will be changed  accordingly. then textBox change event  will work

**Comment by JeanMeche** [comment] 2024-04-08 08:20
Hi, this looks like a dupe of #41519.

**Closed** 2024-04-08 10:45 UTC
Labels: area: forms
