### ISSUE TITLE
a sudden link to a different document in a code comment

### ISSUE THREAD

**Issue by pasha-bolokhov** [angular/angular#34791] opened 2020-01-15 20:09 UTC
# 📚 Docs or angular.io bug report

### Description

Page https://angular.io/guide/observables has a comment in the code:
// Create a new Observable that will deliver the above sequence
Believe it or not, the word "a" is actually a hyperlink to another documentation page, which explains what "a" in a Router href is. Totally irrelevant and wrong. LOL. Wonder how it occurred, must have been some automatic formatting or conversion. I wonder if I'm the only one who reports things like this

### What's the affected URL?**
https://angular.io/guide/observables

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by gkalpak** [comment] 2020-01-16 11:22
Thx for reporting this, @pasha-bolokhov :+1:
This is indeed a result of our auto-generated links in code snippets.

Closing as a duplicate of #34793 (which covers more occurrences). Let's track the issue in #34793.

**Closed by gkalpak** 2020-01-16 11:22 UTC
Labels: comp: docs
