### ISSUE TITLE
Opt out of Zone.js event patching in ngUpgrade

### ISSUE THREAD

**Issue by thelgevold** [angular/angular#16491] opened 2017-05-02 20:52 UTC
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Currently zone.js patches all native events like click, mousemove, keydown, etc to automatically trigger change detection cycles. 

This is very convenient in pure Angular applications, but I have some concerns with this approach in ngUpgrade applications. Once patched, it appears that all handlers are enlisted in the Angular (4+) zone. Even the handlers that belong to Angular 1 code.

A side effect of this is that digest cycles are fired in the Angular 1 application every time one of the patched event handlers are invoked. 

Example: If I have a `mousemove` handler registered in Angular 1, a digest is now triggered every time I move the mouse. This is similar to using `ng-mousemove`, but undesirable if you used `mousemove` in Angular 1, specifically to avoid digest cycles on every mouse move. 

**Expected behavior**
The fix I have seen is to run the event handler for the Angular 1 event in the "parent" zone:

```
$window.Zone.current.parent.run(function() {
        $('body').on('mousemove', function(){
           console.log('triggered');
        });
});
```
I think it would be better if the parent zone was the default for Angular 1 events, instead of being available as an opt-in. 

It makes sense that downgraded components have to run in the "change detection aware" zone, but this does not seem appropriate for existing Angular 1 handlers - at least not as the default. 

**Minimal reproduction of the problem with instructions**
Register any native event handler in an ngUpgrade application

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 4.0.X

* **Browser:** [all
 
* **Language:** [TypeScript]

**Comment by djpark** [comment] 2017-05-13 17:02
+1.  I currently have a hybrid AngularJS/Angular app that uses the ngIdle library.  NgIdle hooks up handlers for DOM events like mousemove, scroll, etc. which end up triggering change detection due to zonejs' monkey patching of these events.  

Similarly to @thelgevold, I'm working around this by running the event handler hookup outside of Angular zone. The additional step I need to take in my case (given that the event hookup is happening in an external library) is to manually find/remove the event listeners then re-add them inside of the runOutsideAngular() call. 

Would be great to avoid having to do this by having events hooked up in Angular 1 context run outside of zone by default.

**Comment by jbedard** [comment] 2017-05-13 18:24
I think I've said similar in another issue, but I wonder if ng-upgrade should try to use the parent zone for things like:
* directive link functions
* `$timeout(..., invokeApply = false)` and other `invokeApply = false` methods

Or would this cause too much inconsistency because this isn't possible everywhere?

**Comment by gkalpak** [comment] 2017-08-19 06:57
The new [downgradeModule()][1] will take care of that (running AngularJS outside the Angular zone). (Docs coming in #18487.)

It is still underconsideration whether to make it configurable if AngularJS runs inside or outside the Angular zone.

<sub>Closing this, but feel free to continue the discussion below.</sub>

[1]: https://next.angular.io/api/upgrade/static/downgradeModule?mode=stable

**Closed by gkalpak** 2017-08-19 06:57 UTC
Labels: comp: upgrade/dynamic, comp: upgrade/static

**Comment by blingerson** [comment] 2017-11-02 18:00
@gkalpak, is this slated to be in the next version 4.4.7? Is there a workaround or patch that can be applied in the meantime?

**Comment by gkalpak** [comment] 2017-11-02 21:36
No, @blingerson, `downgradeModule()` is a 5.x-only feature.

There is no workaround I can recommend in good faith :smiley:
You might want to bootstrap AngularJS outside the Angular zone, which means that async operations that happen in AngularJS-land will not trigger CD in Angular (and subsequently CD in AngularJS again).
But CD will still be triggered in AngularJS when `onMicrotaskEmpty` is triggered on the Angular zone and  you might see unexpected behavior in more complex cases, with changes in one part of the app not properly propagating to the rest of the app.

**Comment by blingerson** [comment] 2017-11-08 20:27
Thank you @gkalpak, I hadn't yet realized 5.0 was released!

One quick question about the downgradeModule being used in conjunction with downgradeInjectable...

Since downgrade module is utilized after angular 1 is bootstrapped how do you add a "downgradeInjectable" service to the angular 1 DI tree given that Angular 5+ is not bootstrapped yet and therefore the angular injector is not available?

For example:

`
angular.module( 'myServicesModule', [] )

.factory(
    'myServiceDowngraded',
    downgradeInjectable( MyService ),
).name;
`

In this example an error is thrown:
static.js:757 Uncaught Error: Trying to get the Angular injector before bootstrapping an Angular module.

**Comment by thelgevold** [comment] 2017-11-09 01:48
My understanding is that you can't use downgraded injectables in AngularJS code if you use `downgradeModule`.

I found an article here: https://pr18487-aedf0aa.ngbuilds.io/guide/upgrade-performance that makes this point

```
While it is possible to downgrade injectables, downgraded injectables will not be available until the Angular module is instantiated. In order to be safe, you need to ensure that the downgraded injectables are not used anywhere outside the part of the app that is controlled by Angular.

For example, it is OK to use a downgraded service in an upgraded component that is only used from Angular components, but it is not OK to use it in an AngularJS component that may be used independently of Angular.
```

**Comment by blingerson** [comment] 2017-11-09 18:39
Thank you @thelgevold, that makes sense

**Comment by gkalpak** [comment] 2017-11-10 10:35
Just to be clear:
You _can_ use `downgradeInjectable()` with `downgradeModule()`, but there are certain limitations. In particular, you cannot try to inject a downgraded injectable until Angular has been bootstrapped. And Angular is bootstrapped (asynchronously) the first time a downgraded component is being rendered. So, you can only safely use a downgraded service inside a downgraded component (i.e. inside upgraded AngularJS components).

I know this is limiting enough that you might decide to not use `downgradeInjectable()` at all - just wanted to make it more clear what you can and can't do.

##
Note that the equivalent limitation is true when using an upgraded injectable with `UpgradeModule`: You cannot use it until AngularJS has been bootstrapped. This limitation usually goes unnoticed though, because AngularJS is usually bootstrapped in the Angular module's `ngDoBootstrap()` method and AngularJS (unlike Angular) bootstraps synchronously.

**Comment by mralbobo** [comment] 2017-11-10 15:16
So...what does the recommended implementation look like in the case where you want an injectable/ service accessible to the entire app (both the angular and angularjs side), and UpgadeModule hits performance like a truck.

Creating a new angularjs service and upgrading it seems counter-intuitive, and I _think_ wrapping the entire angularjs app in an upgraded component would just put it back in the angular zone? Defeating the point of bootstrapping outside the zone.

**Comment by gkalpak** [comment] 2017-11-10 16:42
Unfortunately, I don't think there is a good answer atm. Upgraded components are indeed run inside the `ngZone` (which is something that we could reconsider, but will be a breaking change). It will not be as bad as using `UpgradeModule` (because you still won't have the `$rootScope.$digest()` on `onMicrotaskEmpty()`, but still... 😞

**Comment by thelgevold** [comment] 2017-11-10 16:57
I think the biggest downside to giving up seamless service sharing between Angular and AngularJS is losing a flexible way to share state between the two frameworks. 

That and inter framework communication like rxjs pub sub between Angular components and AngularJS components. This doesn't work anymore since you no longer can share an instance of the pub sub service.

A potential for inter component communication is to use an EventEmitters to bubble up data from Angular components to wrapping AngularJS components.

**Comment by gkalpak** [comment] 2017-11-10 17:41
I may have mentioned that elsewhere, but I think there are two orthogonal concepts that are unnecessrily mixed in `ngUpgradeLite`:

1. The order of bootstrapping Angular and AngularJS.
2. The integration of their respective Change Detections.

`ngUpgradeLite` offers better performance characteristics, but at the same time imposes some limitations that make it not suitable for certain cases. Ideally, I think we should have flags on different behaviors that would affect the performance of hybrid applications, but keep them independent from the use `UpgradeModule` or `downgradeModule`.

To give a little context, the thing that makes a hybrid application slower than a non-hybrid ones is the number of extra change detection runs triggered in order to ensure that changes are propagated across frameworks. There is no perfect solution here, because for some things you just can't know whether CD should be triggered or not. The two opposite sides of the spectrum are:

1. Always trigger CD, which hurts performance but ensures automatic change propagation.
2. Never trigger CD, which is good for performance but does not automatically propagate changes.

And there are several other approaches in-between, balancing performance and change sync with different weights.

Off the top of my head, the main things that ensure changes are propagated correctly (in the expense of performance) are:

1. Trigger AngularJS CD after Angular CD (via run `$digest()` on `onMicrotaskEmpty`).
2. Trigger CD on downgraded components after AngularJS CD (via `.$watch(() => cd.detectChanges())`).
3. Trigger Angular CD on async operations in AngularJS (via bootstrapping AngularJS inside the Angular zone).
4. Trigger CD on downgraded components when inputs change.
5. Trigger CD on upgraded components when inputs change (currently not implemented).

Right now, `UpgradeModule` comes hardcoded with 1 and 3 "on" and `downgradeModule()` comes hardcoded with 4 "on" (which makes it much more lightweight but still "smart enough" wrt change propagation), while in both cases 2 is controlled per downgraded component (via `downgradeComponent(..., {propagateDigest true/false})`).
(Note that bootstrapping AngularJS outside the Angular zone is a little more complicated than simply running `ngZone.runOutsideAngular(() => /* bootstrap logic here */)`, because we need to re-enter the zone when running Angular "stuff" (e.g. in downgraded components).)

But there should be nothing stopping us from making all of these configurable app-wide regardless of the way the hybrid app is bootstrapped (`UpgradeModule` vs `downgradeModule()`).

We have agreed that this would be the right direction, so (while I can't make any promises :grin:) this is definitely something we would like to explore in the future.

**Comment by wiltzius** [comment] 2018-06-08 05:53
I switched to using downgradeModule to alleviate some performance issues we were having, but now I'm occasionally having Angular components that are inside of our AngularJS app not render (their bindings are stale) until the next AngularJS $digest cycle.

To alleviate this, I was going to manually trigger change detection with NgZone -- these docs suggest as much:

https://pr18487-47d394f.ngbuilds.io/guide/upgrade-performance#change-detection-with-downgrademodule

However, I need to trigger that NgZone.run call from the AngularJS code. Do I need to downgrade the NgZone Angular provider to do so, and is that even possible given the constraints on downgrading services? Or, is there some way to trigger the Angular Zone's change detection from the global Zone object? That would be more convenient, but Zone.current is the root zone, not the NgZone, and I can't manage to find the NgZone anywhere.

**Comment by gkalpak** [comment] 2018-06-08 17:05
From what I understand, what you describe shouldn't happen (because `ngUpgradeLite` should be smart enough to trigger Angular CD when the inputs of downgraded Angular components change). Unless the inputs change outside of the AngularJS $digest cycle.

Anyway, why don't you call `$digest()` from AngularJS (instead of `NgZone.run()`)?
(In any case, if -for whatever reason- you need to call `NgZone.run()` from AngularJS, then you do indeed need to downgrade `NgZone`. This is OK as long as you don't call it before bootstrapping the downgraded Angular module. I.e. it is OK to call in upgraded AngularJS component.)

Happy to investigate more if you can provide a minimal demo (e.g. using [stackblitz][1]).

[1]: https://stackblitz.com/edit/ngupgradelite-playground

**Comment by KirillMetrik** [comment] 2019-02-19 09:20
> We have agreed that this would be the right direction, so (while I can't make any promises 😁) this is definitely something we would like to explore in the future.

@gkalpak it's been more than a year now. Have you made any progress on this please? We're currently unable to use NgUpgrade because it kills performance, so we switched to downgradeModule which is fine until you try to use downgradeInjectable. In the end after a lot of thinking I understood that for us it would be best to have something in between, i.e. I DO want to use NgUpgrade but I DON'T want it to fire digests on every mouse move and ideally I want to simply configure whether to track really all events or not.

**Comment by gkalpak** [comment] 2019-02-19 14:49
@KirillMetrik: No, there hasn't been any progress on that front 😞
It's still on our radar, but not a high priority atm.

**Comment by jbedard** [comment] 2019-02-19 19:14
@KirillMetrik I had a similar issue with NgUpgrade causing the digest in cases where I was previously avoiding the digest (normally for performance, such as frequent DOM events). I basically override various things to run outside the Angular zone everywhere running without the digest. It's quite the hack, but without it I couldn't use NgUpgrade either.

**Comment by KirillMetrik** [comment] 2019-02-19 20:59
@jbedard could you please share how exactly did you override things to run outside the angular zone? I'm still quite a newbie with Angular, so even hacky solution would be helpful.

**Comment by jbedard** [comment] 2019-02-19 21:25
Are your perf issues similar to mine? Where your AngularJS(1) app has stuff running without a digest, but NgUpgrade adds a digest?

I have overridden/wrapped the following to run outside the Angular zone, so there will be no change-detection and therefore no `$digest` caused by NgUpgrade:
* `jQuery.fn.on`
* `$timeout(..., invokeApply=false)`
* `$interval(..., invokeApply=false)`

But code within those methods might sometimes manually invoke `$apply`/`$digest`, in which case you should re-enter the Angular zone. So I've also overridden `$apply`+`$digest` to run in the Angular zone.

That was enough to fix my performance issues, while still having change-detection/digest running when expected.

**Comment by KirillMetrik** [comment] 2019-02-20 07:54
@jbedard yes, exactly. I am having code which never supposed to initiate `$digest` but after switching to NgUpgrade it does fire digests. 

See the first picture from profiler, here I have an external library which does styles recalculation on mouse move (because of the need to highlight something). This picture shows clean AngularJS application:
![image](https://user-images.githubusercontent.com/13854800/53074822-073ee780-34ec-11e9-8e59-51a61e5611bf.png)

Then I've added NgUpgrade module and the same scenario now produces extra `$digest`:
![image](https://user-images.githubusercontent.com/13854800/53074895-35242c00-34ec-11e9-8b2e-87c1d8809707.png)

**Comment by jbedard** [comment] 2019-02-20 08:07
The question would be where/how does that `mousemove` listener get added? If it's done using something like `jQuery.fn.on` then you can easily override that to add the listener outside the Angular zone like what I've done. Or if there's a specific location you invoke this library which adds the DOM event listener you can run that invocation outside the Angular zone.

Another method would be disabling zone.js on performance sensitive DOM events such as `mousemove` (lookup `__zone_symbol__BLACK_LISTED_EVENTS`), although that will disable zone.js on those events globally and potentially effect DOM events within Angular where change-detection is expected to run.

**Comment by KirillMetrik** [comment] 2019-02-20 08:44
@jbedard  and what about disabling Zone.js completely?
```
platformBrowserDynamic().bootstrapModule(AppModule, {ngZone: 'noop'});
```
At first I was expecting that this would completely disable automatic change detection but now I've tried it and somehow bindings are still working (at least in my experimental downgraded component). How can this be working without zone? Do I understand correctly that in this case Angular will not detect changes and propagate them to AngularJS but AngularJS will still detect changes through its `$digest` cycle and push those changes to downgraded Angular component?
If this is correct it might be a solution: we would simply rewrite all our components to Angular, downgrade them to AngularJS, then after everything is rewritten remove AngularJS and switch-on the Angular zone again.

**Comment by KirillMetrik** [comment] 2019-02-20 10:03
For now I have utilized the black list feature for events like `mousemove`. This seems to be a reasonable trade-off. And anyway I don't feel like patching all undesired events in all external libraries - this seems a bit fragile to me.

**Comment by jbedard** [comment] 2019-03-07 21:37
Sorry I forgot about this... @KirillMetrik did you have any luck disabling zone.js completely? Whenever I have tried that it disabled too much...

**Comment by KirillMetrik** [comment] 2019-03-07 21:55
@jbedard I've had the same experience - completely disabling zone.js was too much. In the end I've utilized the approach with blacklisting specific events. Performance looks ok with this and no need to manually patch event everywhere.

**Comment by mralbobo** [comment] 2019-03-07 22:09
Another option you can use sometimes is bypassing the monkey patching and calling the native functions. This is handy for when you don't want to globally blacklist. It looks like Zone archives the original functions as __zone_symbol prefixed properties on window.

So for setTimeout you can use __zone_symbol__setTimeout. 

Have yet to see this documented anywhere, so... use at your own risk. (could always just do this manually yourself before loading zone if they change it though).

Keep an eye on the <root> zone though, getting stuck there is pretty obnoxious. Currently hacking the original angularfire library because firebase callbacks end up in the root zone, then angularfire kicks off digests in the root zone which cause inf digest errors from the upgradeModule. <_<
