### ISSUE TITLE
TypeScript Documentation Link Broken

### ISSUE THREAD

**Issue by geekycrooner** [angular/angular#52581] opened 2023-11-07 13:44 UTC
### Describe the problem that you experienced

In the Angular tutorial, I clicked on a link to view TypeScript documentation and received a "Page not found" error. The tutorial page was this one: https://angular.dev/tutorials/learn-angular/updating-the-component-class and the documentation link was this one: https://angular.dev/typescript.org/type-inference

### Enter the URL of the topic with the problem

https://angular.dev/tutorials/learn-angular/updating-the-component-class 

### Describe what you were looking for in the documentation

I was exploring the new Angular tutorial.

### Describe the actions that led you to experience the problem

Opened the URL above and clicked on the link.

### Describe what you want to experience that would fix the problem

I would like to see the TypeScript documentation promised by the link.

**Comment by JoostK** [comment] 2023-11-07 13:45
Thanks for the report! This is a duplicate of #52553.

**Closed by JoostK** 2023-11-07 13:45 UTC
