### ISSUE TITLE
Npm packages are not building

### ISSUE THREAD

**Issue by JankovicsSandor** [angular/angular#30996] opened 2019-06-12 09:09 UTC
# 🐞 bug report

### Is this a regression?

In the version 7 of Angular everything works as expected.

### Description

When installing package dependencies with npm manger the project dos not build. But when installing from yarn (hitting yarn install) and then building the project everything works as expected. 

Package.json

<pre>
<code>
{
  "name": "tinderbox-viewer",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "./node_modules/.bin/nx lint && ng lint",
    "e2e": "ng e2e",
    "affected:apps": "./node_modules/.bin/nx affected:apps",
    "affected:libs": "./node_modules/.bin/nx affected:libs",
    "affected:build": "./node_modules/.bin/nx affected:build",
    "affected:e2e": "./node_modules/.bin/nx affected:e2e",
    "affected:test": "./node_modules/.bin/nx affected:test",
    "affected:lint": "./node_modules/.bin/nx affected:lint",
    "affected:dep-graph": "./node_modules/.bin/nx affected:dep-graph",
    "format": "./node_modules/.bin/nx format:write",
    "format:write": "./node_modules/.bin/nx format:write",
    "format:check": "./node_modules/.bin/nx format:check",
    "update": "ng update @nrwl/schematics",
    "update:check": "ng update",
    "workspace-schematic": "./node_modules/.bin/nx workspace-schematic",
    "dep-graph": "./node_modules/.bin/nx dep-graph",
    "help": "./node_modules/.bin/nx help"
  },
  "private": true,
  "dependencies": {
    "@amcharts/amcharts4": "4.4.10",
    "@angular/animations": "8.0.0",
    "@angular/cdk": "8.0.1",
    "@angular/cdk-experimental": "8.0.1",
    "@angular/common": "8.0.0",
    "@angular/compiler": "8.0.0",
    "@angular/core": "8.0.0",
    "@angular/forms": "8.0.0",
    "@angular/material": "8.0.1",
    "@angular/platform-browser": "8.0.0",
    "@angular/platform-browser-dynamic": "8.0.0",
    "@angular/router": "8.0.0",
    "@angular/service-worker": "8.0.0",
    "@datorama/akita": "3.15.1",
    "@datorama/akita-cli": "4.0.4",
    "@datorama/akita-ngdevtools": "3.0.2",
    "@ngrx/effects": "8.0.1",
    "@ngrx/router-store": "8.0.1",
    "@ngrx/store": "8.0.1",
    "@nrwl/nx": "7.8.6",
    "@types/lodash": "4.14.134",
    "core-js": "3.1.3",
    "lodash": "4.17.11",
    "node-sass": "4.12.0",
    "opencollective-postinstall": "2.0.2",
    "rxjs": "6.5.2",
    "zone.js": "0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-ng-packagr": "0.800.2",
    "@angular/cli": "8.0.2",
    "@angular/compiler-cli": "8.0.0",
    "@angular/language-service": "8.0.0",
    "@angular-devkit/build-angular": "0.800.2",
    "@ngrx/store-devtools": "7.4.0",
    "ng-packagr": "5.3.0",
    "ngrx-store-freeze": "0.2.4",
    "@nrwl/schematics": "8.1.0",
    "jasmine-marbles": "0.5.0",
    "@types/jasmine": "3.3.13",
    "@types/jasminewd2": "2.0.6",
    "@types/node": "12.0.8",
    "codelyzer": "5.1.0",
    "jasmine-core": "3.4.0",
    "jasmine-spec-reporter": "4.2.1",
    "karma": "4.1.0",
    "karma-chrome-launcher": "2.2.0",
    "karma-jasmine": "2.0.1",
    "karma-jasmine-html-reporter": "1.4.2",
    "protractor": "5.4.2",
    "ts-node": "8.2.0",
    "tsickle": "0.35.0",
    "tslib": "1.9.3",
    "tslint": "5.17.0",
    "typescript": "3.4.5",
    "prettier": "1.17.1"
  }
}

</code>
</pre>

## 🔥 Exception or Error
<pre><code>

ERROR in ./src/app/routing/routes.ts 4:30
Module parse failed: Unexpected token (4:30)
You may need an appropriate loader to handle this file type.
| import { SpeedAlertComponent } from '../speed-alert/speed-alert.component';
| import { NotFoundComponent } from '../not-found/not-found.component';
> var ɵ0 = function () { return import("./../home-page/home-page.module.ngfactory").then(function (m) { return m.HomePageModuleNgFactory; }); }, ɵ1 = function () { return import("./../client-info/client-info.module.ngfactory").then(function (m) { return m.ClientInfoModuleNgFactory; }); }, ɵ2 = function () { return import("./../speed-test-info/speed-test-info.module.ngfactory").then(function (m) { return m.SpeedTestInfoModuleNgFactory; }); }, ɵ3 = function () { return import("./../graph-viewer/graph-viewer.module.ngfactory").then(function (m) { return m.GraphViewerModuleNgFactory; }); };
| export var ROUTER_ARRAY = [
|     { path: '', loadChildren: ɵ0 },
ERROR in C:/Perforce/Internal-Tools/Main/Tinderbox/TinderboxFe/TinderboxViewer/node_modules/@amcharts/amcharts4/.internal/core/export/Export.js 68:24
Module parse failed: Unexpected token (68:24)
You may need an appropriate loader to handle this file type.|             switch (_a.label) {|                 case 0: return [4 /*yield*/, Promise.all([
>                         import(/* webpackChunkName: "pdfmake" */ "pdfmake/build/pdfmake.js"),
|                         import(/* webpackChunkName: "pdfmake" */ "../../pdfmake/vfs_fonts")
|                     ])];

</code></pre>
Routes. ts
<pre>
<code>
import { SchedulerComponent } from '../scheduler/scheduler.component';
import { SpeedAlertComponent } from '../speed-alert/speed-alert.component';
import { NotFoundComponent } from '../not-found/not-found.component';

export const ROUTER_ARRAY: any[] = [
  { path: '', loadChildren: () => import('apps/tinderbox-viewer/src/app/home-page/home-page.module').then(m => m.HomePageModule) },
  { path: 'ClientInfo', loadChildren: () => import('apps/tinderbox-viewer/src/app/client-info/client-info.module').then(m => m.ClientInfoModule) },
  { path: 'Speedtest', loadChildren: () => import('apps/tinderbox-viewer/src/app/speed-test-info/speed-test-info.module').then(m => m.SpeedTestInfoModule) },
  { path: 'Graphviewer', loadChildren: () => import('apps/tinderbox-viewer/src/app/graph-viewer/graph-viewer.module').then(m => m.GraphViewerModule) },
  { path: 'Speedalert', component: SpeedAlertComponent },
  { path: 'Scheduler', component: SchedulerComponent },
  { path: '404', component: NotFoundComponent },
  { path: '**', redirectTo: '/404' }
];

</code>
</pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular: 8.0.0... animations, common, compiler, compiler-cli, core, forms... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.800.1
@angular-devkit/build-angular      0.800.2
@angular-devkit/build-ng-packagr   0.800.2
@angular-devkit/build-optimizer    0.800.2
@angular-devkit/build-webpack      0.800.2
@angular-devkit/core               7.3.9
@angular-devkit/schematics         7.3.9
@angular/cdk                       8.0.1
@angular/cdk-experimental          8.0.1
@angular/cli                       8.0.2
@angular/material                  8.0.1
@ngtools/json-schema               1.1.0
@ngtools/webpack                   8.0.2
@schematics/angular                8.0.1
@schematics/update                 0.800.2
ng-packagr                         5.3.0
rxjs                               6.5.2
typescript                         3.4.5
webpack                            4.30.0

</code></pre>

**Comment by Splaktar** [comment] 2019-06-12 09:33
These don't look good:
```json
@angular-devkit/core               7.3.9
@angular-devkit/schematics         7.3.9
```

This seems like an Angular CLI issue.

**Comment by alan-agius4** [comment] 2019-06-12 10:02
Duplicate of https://github.com/angular/angular-cli/issues/14566

**Closed by alan-agius4** 2019-06-12 10:02 UTC
