### ISSUE TITLE
Programmatically prevent the destruction of components when requested

### ISSUE THREAD

**Issue by cangosta** [angular/angular#5275] opened 2015-11-13 15:57 UTC
It would be nice if we could tell angular not to destroy components when we navigate out of them, even if the next component is of a different type. This could be useful, for example, when building a window management system, where users can navigate through different windows (components) without
the need for recovering the whole state. 

The existing canReuse hook is not useful for this use case, since it only allows us to reuse components if the previous and the next component have the same type.

Code example:

```javascript
@Component({...})
class ExampleComponent {
	canDestroy() { // or some other name
	  return this.closeButtonClicked;
	}
}
```

**Comment by mhevery** [comment] 2015-11-15 18:38
Why can't you just store the state in higher level component which does not get destroyed?

**Comment by cangosta** [comment] 2015-11-15 18:54
Hi Misko, thanks for you answer! I'm actually done that and it works fine. Take this just as a suggestion. There may be a lot of state that must be stored for complex windows and doing that is error prone and painful. It would be nice if angular 2 had this possibility.

**Comment by hitmanmcc** [comment] 2015-11-16 17:30
I agree with @cangosta, I think this could be a very useful feature in certain scenarios. However, I don't know if this is something that could be easily added to the framework or if it would be a costly both in terms of development and/or computational resources. Can someone please weigh in on this? I'd be interested in seeing this be discussed in a somewhat technical fashion.

**Comment by tbragaf** [comment] 2015-11-17 22:01
I have to agree with what was said.

Picture the scenario when you need to navigate through various routes.
If you save state in a higher level component, you most likely will save the model.
What about the state of the view? 

Imagine you have in one view a tab component, with the 3rd tab selected.
When getting back, you want the 3rd tab to be selected.

This is no longer be a model concern, so should I save it anyway?
What about multiple tab components? Save all of them?

Save everything ad hoc?

**Comment by mhevery** [comment] 2015-11-18 18:32
I think you can already do this.

1) Hide the component through `hidden` property
2) Opt out of change detection using [`ChangeDetectionStrategy`](https://angular.io/docs/ts/latest/api/core/ChangeDetectionStrategy-enum.html)

**Comment by tbragaf** [comment] 2015-11-18 18:57
@mhevery
But what if those components are bound to a router (which is the actual use case)?

The router is the one managing that.

**Comment by cangosta** [comment] 2015-11-19 12:02
In order to make it explicit, what is intended here is to somehow inform angular that we don't want it to destroy a view when we navigate out of it and then, recover that same view when we navigate to its path. Afaik, @mhevery's suggestion of hiding components would work fine, if we had an easy way to instantiate a view (which is a component) and then render it.

**Comment by hitmanmcc** [comment] 2015-11-23 13:06
This is a very interesting problem and one that I think has far reaching implications in terms of developer burden and user experience. I'll explain what I mean with a couple of scenarios.
If we imagine using angular 2 for a mobile application, consider something like Facebook's app. Then we'll have a sort of tabbed arrangement of a main component, where we switch between content on different tabs. For this, the way angular 2 works now is fine, our data will never be discarded by change detection.
However, if we imagine a case where we have a more complex type of application, something that is meant for a commercial/enterprise environment, then we can run into some serious issues. Let's consider a scenario that is actually viable both for desktop and mobile. Imagine that we have an application that allows a user to manage the business activities of his shop. He's trying to issue some for of document, an invoice for instance and he's met by a new client that's he's going to add to his database. Adding the client will mean navigating away from the component where he was issuing the invoice, he fills out the form, saves it and then he comes back to the screen where he was registering the sale and voilà, the data he previously input is gone. This would be an even more serious loss of productivity if he's working on a document that affects inventory/stock, when there are possible tens of thousands of rows on the document, which would all get lost. Now if we consider a scenario where the client was actually working on a mobile device, like a table, this problem gets even more compounded because the computational resources are far inferior and the connectivity is usually flakier.
So either the client risks losing work, or there need to be checks set in motion to prevent him from performing certain operations at certain times, or an overhead is imposed on development where programmers will have to come up with means of storing and restoring state across application components, which also has computational costs that may/(likely will) exceed some solution/mechanism that is integrated into the framework.

**Comment by jorgeunimicro** [comment] 2015-11-26 17:25
+1 to this problem. 

That is the problem I have found:
 - I apply some directives to form inputs 
 - Those directives manipulate the dom to add some behavior (multiselect, maksed inputs...)
 - Each time I come back to the view html is cached but not directives so they run constructor and lifecycle hooks again and manipulate the dom again.

It would be nice if there can be a strategy to keep the state of the component (maybe reuse the instance of the class, not sure how difficult it is or if it is possible)

Thank you.

**Comment by jorgeunimicro** [comment] 2015-11-27 09:58
My solution for the moment is to create a destroy method in each directive that cleans up the autogenerated HTML and cleans up attached events also, so directive can re-run again.

Maybe would be helpful if you can tell the router the strategy to follow: to cache or not to cache views, so developer can asume freely risks of each strategy.

**Comment by yvoronen** [comment] 2015-12-15 01:14
+1
I ran into same issue. This is super useful in complex multi-tab applications. We would like to easily preserve the navigation state.

**Comment by waeljammal** [comment] 2016-01-19 08:12
+1 I am using CanReuse and OnReuse but it still calls my constructor every time my use case is a content editor and it loads lots of assets into an iframe so I would rather not reload all of that every time the user comes back to the view.

**Comment by hdeshev** [comment] 2016-01-19 09:19
Just stumbled into this issue, and wanted to provide another valid (IMO) use case.

I'm trying to make the Angular router and the NativeScript navigation framework work together. In a NativeScript mobile app you can have different pages, and you can navigate to them, displaying different parts of your UI. The mobile toolkit makes it all look nice, using animated transitions, etc.

My initial attempt at this involved the following:
- Navigate to a "page shim" component, `AsyncRoute`-style.
- Once the page shim component loads, trigger navigation to a new mobile page.
- Load the new page content, given a component type using the `DynamicComponentLoader`, and move the instantiated visual tree to the new page right before it displays.
- On navigating back, destroy the child page, unload the component, and resolve the shim component deactivation promise once the original page is fully transitioned to.

This approach works pretty well most of the time. It fails in cases where you can use a swipe gesture to preview the original page before navigating back to it. At that point in time the original page is mostly blank and looks broken because the router has deactivated the original component.

I'll be revisiting this problem in the next couple of days and look for a way to preserve the original view state when navigating to a new component. For example, I haven't yet explored the possibility of building a custom router outlet component for that specific scenario.

**Comment by Namek** [comment] 2016-01-31 12:18
I have a simple case, imagine routes that have tabs inside tabs:
`/product/1/info`
`/product/1/buy`
`/product/2/info`
`/product/2/buy`

I expect to see 2 instances of `Product` component, each having one instance of `ProductBuy` and `ProductInfo`. Everytime I switch between any of those tabs, nothing should be destroyed/recreated, just hiding/unhiding elements. And - lazy loading.

Router in current shape is somehow useless to my app which I rewrite from Angular 1. A bit of shame because Angular 2 itself is awesome!

**Comment by mnvx** [comment] 2016-02-23 14:56
+1 Will be nice to store states with Angular2 capacibilities

**Comment by hdeshev** [comment] 2016-02-26 15:33
The Angular router destroys and recreates components on navigation. I think the recommended approach is to store intermediate state in a service and quickly recreate the UI. I think there is an issue about that open over at the angular repo.

**Comment by tbragaf** [comment] 2016-02-26 16:32
@hdeshev 
That is an adhoc workaround.
Currently we have no option besides that one and that is why the issue is opened.

**Comment by alex321** [comment] 2016-03-10 14:25
+1. I was hoping this feature would be in Angular 1 UI router

**Comment by fabfire** [comment] 2016-03-10 21:34
+1 for this feature request.

I encouter the same issue, here is my use case :
I have a menu with 2 options that show the corresponding component using router outlet.
The 1st show charts that are dynamically updated with values provided by socket.io.
The 2nd is a log view that show messages sent be socket.io.

With the current behavior, I have to store all the values (in a Service) to be able to redraw the charts each time I switch between the chart component and the log component.
And it is the same for the log view.

Could you please add a feature to store the state of a component view or not destroying it ?
Thank you

**Comment by danielrasmuson** [comment] 2016-03-11 02:32
+1

**Comment by chasemgray** [comment] 2016-03-11 02:57
+1

**Comment by Sn3b** [comment] 2016-03-15 21:47
+1

**Comment by MurhafSousli** [comment] 2016-03-16 05:12
+1

**Comment by serlight1** [comment] 2016-03-18 12:43
+1

**Comment by guaido79** [comment] 2016-03-30 09:08
+1

**Comment by zoechi** [comment] 2016-03-30 11:26
There is a nice new GitHub feature to "add reaction"s instead of `+1` posts. Please use this instead :+1:

**Comment by dheran** [comment] 2016-04-20 10:04
@zoechi adding +1 comment does two things comment 1. subscribe to the thread 2. informing author that we too facing the same issue

**Comment by zoechi** [comment] 2016-04-20 10:47
@dheran 
At first it's a lot of noise that makes it hard to find relevant information  
and it's a distraction and spam for others that are subscribed. 

For subscribing just click the subscribe button. 

Please use the right features for the right purpose. +1 is the wrong feature in every case.

**Comment by dharders** [comment] 2016-04-22 06:15
Hopefully this would also solve #8035 

This issue isn't related to Router use at all, but would definitely benefit from the ability to manually prevent component destruction.

(...in this case delay component destruction until after a touchend/cancel event was fired, **if  touchstart/touchmove is currently active** on the component about to be destroyed)

**Comment by kmcs** [comment] 2016-05-04 12:46
+1

**Comment by vsavkin** [comment] 2016-07-07 01:01
We are no longer maintaining the deprecated router to focus our efforts on making the new router robust. And when using the new router, you can use the canDeactivate guard to achieve the desired behavior.

Closing this issue.

**Closed by vsavkin** 2016-07-07 01:01 UTC
Labels: comp: router-deprecated, effort2: medium (day), P3: important, state: Needs Design, type: feature

**Comment by MadUser** [comment] 2016-07-10 13:06
Hi victor, can you elaborate?

**Comment by Namek** [comment] 2016-07-10 20:00
@vsavkin I don't believe `canDeactivate` will solve the problem. Can you link us to an example or could you reopen issue?

**Comment by jorgeunimicro** [comment] 2016-07-11 07:00
@vsavkin the behaviour we are asking for is to mantain components instaces along all the application if we decide it. So if an user goes from one component to other the state is maintained (focus, if you have a dropdown menu openend, etc..)

**Comment by Thyoity** [comment] 2016-08-25 21:03
I'm facing this same problem right now. This feature would be really good!

**Comment by alex321** [comment] 2016-08-27 15:58
I don't think that the behaviour we asked for is achieved by canDeactivate. Can you give an example or a plnkr link to verify that?

**Comment by lexon0011** [comment] 2016-08-31 09:52
Is there already a solution for reusing a component after routing back from another component? I need it, because changes to combo boxes, grid settings, ... gest lost if I navigate to another view and then back.
Thanks!

**Comment by kylecordes** [comment] 2016-08-31 13:32
I think this discussion is fundamentally about where to store state, not about how to reuse components. I have found that storing state in components is useful only in the most narrow of cases. I rather wish that the fundamental design of Angular 2 had made stateless components the default, with state something that could be opted into for the special cases. The progression for real applications in our work has been something like the following:

* A rat's nest of mutability everywhere, with various hacky ways of pushing copies of state all over to where you need them. Obviously this is a situation to be noticed and fixed, not a plan. Is where you end up if you just start learning the most basic Angular 2 capabilities and applying them.
* Centralize state in to "services", and let change detection cause the data to flow. This works for a while until you realize that you need better control over how states change.
* Invent some little thing that manages state using observables with intentional changes.  This works for a while also, until you realize that you are reinventing things other people already invented.
* Swap that out for a much better thought through and implemented version of the same idea, such as ngrx/store. (I think ng2-redux will also work well for this, but don't have firsthand experience with that one.)
* Alternatively, find that some other state management mechanism like FireBase provides many of the same advantages.  And possibly some other advantages also, like automatically persisting your state.
* Keep one's eyes open for the future in which I expect things more like Relay, Falcor, etc will end up as the dominant way to manage state.

Now you might think from this description but I'm talking _only_ about huge complex enterprise apps. Not true. Even fairly small applications, can end up having surprising difficulty in state management. I have a piece of training curriculum which attempts to manage state responsibly in a tiny application whose code can be fully reviewed in just a few minutes. It ends up at the third bullet point in the list above.

You might also think, "but I'm not talking about application state, I'm just talking about whether a checkbox is checked on a form".  This sort of thing initially seems like it can be omitted from a broad notion of application state, and that is true, until you want to implement certain features, and then it is not true anymore.

**Comment by Namek** [comment] 2016-09-02 09:15
> I think this discussion is fundamentally about where to store state, not about how to reuse components.

@kylecordes And I think you're fundamentally wrong about preassuming other people's needs. To some of them your comment may sound righteous but you didn't cover 100% of problem. And actually, to me, you completely missed the point.

Now understand this because situation is simple. It's not about storing a state, it's about god damn **performance**. In my case I have charts and grids which I don't want to reinitialize every time a user switches a tab. Tabs don't only exist for separation due to timeline of user work (referring to Google Analytics), but also due to screen space in same timeline. In other words, my user needs multiple tabs during the same session, constantly switching between them.

What I had to do was ignore router's outlet and implement custom component instantiaton managing components using some observable collection while putting `ngIf`s in the template. That's ugly, you know.


I dislike sweeping issues under the carpet like this. To everyone interested, tweet the one responsible for closing @vsavkin -> https://twitter.com/nameczanin/status/770949108253265920

**Comment by zoechi** [comment] 2016-09-02 10:43
@Namek as far as I remember @vsavkin mentioned on another issue not too long ago that they plan to add support for this use case by adding some custom caching strategy for components to be reused (or similar don't remember details). It's just unlikely that this will be added before final.

**Comment by netmikey** [comment] 2016-09-02 11:41
@zoechi if you happen to find a link or something to that statement, I'd also be interested.

**Comment by vakrilov** [comment] 2016-09-02 13:03
@zoechi You are right about the plans about caching. #7757 is the issue you are probably referring to and more specifically [this comment](https://github.com/angular/angular/issues/7757#issuecomment-236737846). It looks like a duplicate, but it is still open so you can follow that one as well.

@Namek I agree with you that **performance** is a good reason for caching. In the NativeScript scenario on the other hand - the native navigation stack already does the caching - so there is no reason not to use it.

**Comment by kylecordes** [comment] 2016-09-02 13:22
@Namek I wasn't trying to be divisive, or to pre-assume other people's needs. Rather I think Angular's design is pressing all of us toward treating the thing you are describing as application state, and managing it in one of the ways I talked about. If there is some aspect of a component data (and that data might even be DOM, particularly if that DOM is created and managed by a third-party library being integrated), the current Angular feature set pushes us in one of these directions:

* Wait for additional component caching/reuse configurability to arrive
* Stash the data (even DOM!) we need to preserve in a service, so as to obtain the desired performance even while letting Angular manage the instantiation and re-instantiation of the Components.
* Don't use routing or NgIf, but rather keep the components in existence and manage their _visibility_, perhaps with a custom tab set widget designed to work this way.
* Possibly other variations I haven't thought of.

We have solved this problem in real apps using the third bullet point above, but I agree with you that it would be good if Angular itself offered a more built in way to do so. The need, in some cases, to keep DOM around and hide/show versus destroy/re-create, predates Angular and is not going away anytime soon. It matters for performance as you said.

**Comment by AlGantori** [comment] 2016-09-04 05:38
This discussion is a bit over my head but it sounds very related to my recent posting [(http://stackoverflow.com/questions/39299478/how-to-keep-certain-ionic2-pages-live-throughout-a-session)]

Could one of you please confirm, it is indeed related to angular2 and not ionic2, in that NavController.push() always recreates my player page I want to travel to but I do not want destroyed, Because, setting up a player like youtube is costly and thus problematic to keep recreating with every visit to its view.  Is there any workaround or fix at this time?   I am new to angular2/ionic2 and would appreciate a bit of help to keep progressing with the development of my app.   Hosting my players into tabs keeps them around for the session but it is not a clean user interface given the small real estate on mobile devices. Thank you.

**Comment by ronenmiller** [comment] 2017-01-30 16:56
I am also wandering about the routing issue. Can anyone share what to do as workaround for routing back to previous component state?

**Comment by zoechi** [comment] 2017-01-30 18:12
@ronenmiller perhaps http://stackoverflow.com/questions/33940095/angular2-routing-keeping-state-of-component-when-route-changes/36010817#36010817 is helpful for you (for example the link to sticky-routes...) about custom reuse strategy

**Comment by ronenmiller** [comment] 2017-01-31 06:20
@zoechi Thanks a lot! This is exactly what I needed. Works like a charm!

**Comment by tettusud** [comment] 2017-03-10 08:43
@zoechi, but sticky routes doesnt work in case of  lazy loaded modules.

**Comment by zoechi** [comment] 2017-03-10 16:03
@tettusud sorry, don't know about that. I haven't played with lazy loaded modules or custom reuse strategy yet.

**Comment by tettusud** [comment] 2017-03-11 10:07
Thank you @zoechi ,do you have any working example to implement tabs in angular 2 ,I need to open routes in New tabs

**Comment by zoechi** [comment] 2017-03-11 14:05
I don't know what exactly you mean with "open routes in new tabs". If you mean browser tabs, then this won't work. Please use other channels for support questions (Gitter, StackOverflow, Google Groups, ...)

**Comment by jorgeunimicro** [comment] 2017-03-16 14:44
Last think I have read about reusing components is this post

https://www.softwarearchitekt.at/post/2016/12/02/sticky-routes-in-angular-2-3-with-routereusestrategy.aspx about `RouteReuseStrategy`

I think that is the behaviour most of us are looking for.

Unfortunately, this example throw some errors when you navigate from one route to other. I have tried to understand the behaviour but I found the CustomStrategy storing just the top routes of the application and also giving me bad handlers. Maybe I am not understanding how it works.

I wonder if someone from the angular team could give us a good example about how to reuse those components that we have already visited. 

CC @vsavkin

**Comment by tettusud** [comment] 2017-03-25 01:03
@jorgeunimicro  it still fails for lazyloaded module, After hours of struggle still not able to find a way to achieve tab support, 
  if someone finds a way to achieve a way to provide tab support please let me know.

**Comment by tettusud** [comment] 2017-03-25 01:09
@zoechi  My requirement is simple,   we have just two Views , on same page( you can read two sub modules  CustomerModule,ProductsModule with its own routings)  for eg: customer details view and available product details view.
  As a user I need to search for customer and load his details and products on one one view,fill customer product details/update his details while referring to other view product.
So basically I may need to switch back and forth  between this two views ( like tabs, if you see bootstrap tabs,where  you click on tab heading it will hide/show the tab you care clicking and clicking out ,here am not at all talking about browser tabs,but a kind of view within same page called TABS).
Two  routerLinks (you can image it as tab header) one for Customer Details when clicked that loads CustomerModule, and other one is Product details which loads Product Module.
so when i switch back ,already entered data are lost, yes I tried routeReuseStrategy ,but yet it has its own issue, when lazyloading a module  ,there is no clear way to handle storing similar routes like /customer/details/1 and /customer/details/2 which maps to same pattern.
  I hope I gave you detail description of what is required, please let me know if you need some more information

**Comment by zoechi** [comment] 2017-03-26 13:31
@tettusud I think you should ask at one of the channels mentioned in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question) 
GitHub is for bug reports and feature requests only

**Comment by Namek** [comment] 2017-04-04 14:22
@tettusud if you'd be interested I could describe how I achieved dynamic tabs but without routing.

**Comment by tettusud** [comment] 2017-04-04 15:04
Sure thabk you much you can email me @ sudharsan_tk@Yahoo.co.in

Sent from my HTC

----- Reply message -----

**Comment by vinaysoni** [comment] 2017-04-04 18:32
Can't believe that Angular team is not willing to fix this issue. This is the behavior that 99% of the apps adopt. It is funny to have a router that creates and destroys components every time renavigation occurs. Solutions have been provided by users:
https://gist.github.com/danielrasmuson/89cde9ce22d89167cec6d7f9a9240558
But the Angular team doesn't even recognize the problem.

**Comment by zoechi** [comment] 2017-04-05 05:25
@vinaysoni I think you're looking for https://github.com/angular/angular/pull/13124 not too well documented yet AFAIK. https://www.softwarearchitekt.at/post/2016/12/02/sticky-routes-in-angular-2-3-with-routereusestrategy.aspx might help a bit.

**Comment by Namek** [comment] 2017-04-05 07:23
@zoechi well, this article you mentioned is a liar. ReuseStrategy is not Sticky Route. It's a different thing behaving similarly in a small scope.

**Comment by zoechi** [comment] 2017-04-05 07:28
@Namek just because it's not exactly what you're looking for, he's not a liar. 
This is the open source world. Nobody is liable to deliver something just because you think it would be handy.

**Comment by jorgeunimicro** [comment] 2017-04-05 08:03
@Namek based on this article with a few modifications we have our sticky state app working. It is a little bit adhoc solution but it fixes our issues. So now we can start creating an invoice, visit the customer profile to check some values and come back to the invoice and continue the job at the same place we were.

**Comment by Namek** [comment] 2017-04-05 21:20
@jorgeunimicro I foresee you're using only a small subset of the desired feature. Components are reused by filling other data to previously instantiated component of same type. So, having multiple component instances of one component type you will lose state of inputs when switching because in real you'll have only one instance per type.

**Comment by jorgeunimicro** [comment] 2017-04-06 07:04
As far I can test I can go from customer/3 to customer/4 without problem I just store each handler in different keys of the array using the fullpath (with params). There are other problems like refresh dependant views or manage events (which still work if the instance is alive), but we have designed a pub/sub service to manage those features.

**Comment by vinaysoni** [comment] 2017-04-17 03:53
@zoechi Thanks for the link. It does try to solve the sticky components problem. Definitely a step in the right direction. It works fine when navigating to top level paths. As soon as a path has child paths it has issues:

https://stackoverflow.com/questions/41584664/error-cannot-reattach-activatedroutesnapshot-created-from-a-different-route?answertab=votes#tab-top

https://github.com/angular/angular/issues/13869

**Comment by zh99998** [comment] 2017-04-20 07:23
I'm in same trouble.
my scene is just like some chrome tabs, some of them contains `<iframe>` tag.
when routing to another component, the iframe is removed from DOM tree and when back, it have to reload with lost states.

`RouteReuseStrategy` not works here.

**Comment by Namek** [comment] 2017-05-10 20:40
Well, I wrote few words about having dynamic tabs but I have ignored the routing:
https://www.namekdev.net/2017/05/angular-2-my-solution-for-dynamic-tabs/

**Comment by phil-lgr** [comment] 2017-10-22 23:25
Any link/info of the state of "sticky state" with the final router? I have that feature with UI-Router, but would prefer to keep the default angular-router.

**Comment by erbsenkoenig** [comment] 2017-10-23 02:02
Ich kehre zurück am 01.11.2017.

Ich werde Ihre Nachricht nach meiner Rückkehr beantworten.
In dringenden Fällen senden Sie bitte eine Kopie Ihrer E-Mail für
technische Angelegenheiten an entwicklung@arxes-tolina.de, ansonsten an
info@arxes-tolina.de. Ein anderer Mitarbeiter wird sich dann Ihrer E-Mail
annehmen.


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re:
[angular/angular] Programmatically prevent the destruction of components
when requested (#5275)" gesendet am 23.10.2017 01:25:31.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während
diese Person abwesend ist.

**Comment by Vespira** [comment] 2018-01-05 09:59
Leaving my stone here, but I agree with @kylecordes : 
Immutability high level state is the best way to go here. either with : 

- a high level parent component with the OnPush Change Detection Strategy, so that the component notify changes only when new references is passed to it. You could store in a medium proper way state you need to save.

- Or with a Redux-like state management system, with pure functions updating a state that can be observed across the application. Angular have a nice implementation of redux names @angular-redux.

It's my point of view and there's other ways to do this. I think the components destroy lifecycle is good as it is.
