### ISSUE TITLE
Problems mocking MockConnection error response

### ISSUE THREAD

**Issue by mildfuzz** [angular/angular#12857] opened 2016-11-14 11:47 UTC
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Test Repo - https://github.com/mildfuzz/angular-mockError

I am unable to test predicted HTTP error responses. Mockbackend can either send a response with an error code (which my app treats as a successful response in the test environment, but as an error in real world)

I am unable to send status codes with an error response in my tests, so I can not test any error handling my application might implements.

**Expected behavior**
at least one of the defined test cases passes

**Minimal reproduction of the problem with instructions**
Test Repo - https://github.com/mildfuzz/angular-mockError

this is a re-opening of issue #7471, which was closed due to lack of repro steps.

**What is the motivation / use case for changing the behavior?**
To be able to test all responses 

**Please tell us about your environment:**
OsX

* **Angular version:** 2.0.X
Angular 2.1.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome 54
 
* **Language:** TypeScript 2.0.3

* **Node (for AoT issues):** `node --version` =   6.9.1

**Comment by fetis** [comment] 2016-12-12 17:12
I came across to the same problem. I would recommend to remove all redundant code from repository because it's not clear where to look in.

So briefly the problem looks next
```
http.get('some url')
  .map(value => {
    console.log('map');
   return value})
  .catch(() => console.log('catch')
```

and we have next mock response
```
backend.connections.subscribe((connection: MockConnection) => {
  connection.mockRespond(new Response(new ResponseOptions({
    status: 400
})))
```

so I expect it'll log `catch` as it happens with real backend. But actually it prints `map` all times.

The single way to fix it is to use `connection.mockError()`

**Comment by Ks89** [comment] 2016-12-28 19:17
Exactly the same problem also with the latest stable release of angular. Same situation of @fetis .

To fix this problem I used:
```
backend.connections.subscribe((c: MockConnection) => c.mockError(new Response(new ResponseOptions({ status: 404}))));
```

The solution described into the official testing example [HERE](https://angular.io/docs/ts/latest/guide/testing.html) is not working.

**Comment by Koslun** [comment] 2017-02-07 23:00
Duplicate issue: #13690.

#7135 points out that the current working way requires a double cast in TypeScript (`connection.mockError(response as any as Error);`). As `MockError` only accepts `Error` while the expected behavior is to get a proper `Response` object. There is a fix for that in PR #13104 made by @DzmitryShylovich.

Other than the official testing documentation @Ks89 linked, there is at least one other error in the API documentation at https://angular.io/docs/ts/latest/api/http/testing/index/MockBackend-class.html . Where it also seems to be assumed that responses with code 404 should result in a thrown error rather than a regular response.

Fixing this to generate the expected error might break some folks' tests, but think most or all of those tests were wrong to begin with.

**Comment by royling** [comment] 2017-05-09 02:11
>the current working way requires a double cast in TypeScript (connection.mockError(response as any as Error);). As MockError only accepts Error while the expected behavior is to get a proper Response object. 

I tried to work around this problem by creating a class extending Response and implementing Error (type declared in types\node):
```js
class ErrorResponse extends Response implements Error {
  name: any;
  message: any;
}

export function mockError(errorResponseOpts: any) {
  return new ErrorResponse(new ResponseOptions(errorResponseOpts));
}
```

**Comment by JSchneidler** [comment] 2017-08-15 23:15
Can we get an update on this? #13104 (the fix) was closed without an explanation.

I don't think these workarounds are a good long-term solution.

**Comment by alxhub** [comment] 2020-05-29 19:30
Closing as this pertains to `@angular/http` which is now obsolete.

**Closed by alxhub** 2020-05-29 19:30 UTC
Labels: comp: http, comp: testing, freq2: medium, severity2: inconvenient, triage #1, type: bug/fix

**Comment by nanoscz** [comment] 2020-06-29 01:13
Cannot find module '@angular/http/testing' or its corresponding type declarations. [Angular 9]
