### ISSUE TITLE
@angular/common/http HttpClient .jsonp does not support options or headers

### ISSUE THREAD

**Issue by michaelcm** [angular/angular#24368] opened 2018-06-08 05:50 UTC
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
Certain sites require that HTTP headers be provided when making a JSONP request. `@angular/http` used to allow this functionality, but the non-deprecated `@angular/common/http` no longer allows any options/headers to be provided to the `.jsonp(url, callback)` call.

## Expected behavior
`.jsonp(url, callback)` on `HttpClient` from `@angular/common/http` should allow options/headers to be provided. In particular I am attempting to provide the `Accept: application/json' header for an API integration.

All other HttpClient methods (get/post/etc.) support options and HttpHeaders.

## Minimal reproduction of the problem with instructions
```javascript
import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';

@Injectable({
  providedIn: 'root'
})
export class TestService {

  constructor(private http: HttpClient) { }

  public query(search: string): any {
    this.http.post<any>(`https://someUrl`, 'someCallback').subscribe((response) => {
      console.log(response);
    });
  }
}
```

## What is the motivation / use case for changing the behavior?
There are some services that can provide both `application/xml` and `application/json` responses. The `Accept` header is required to choose the desired response format. Also, the `Cookie` header is required to maintain authentication to some APIs.

## Environment

<pre><code>
Angular version: 6.0.3

Browser:
- [X] Chrome (desktop) version 66.0.3359.181 
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.11.2  
- Platform: Windows 10 
</code></pre>

**Comment by trotyl** [comment] 2018-06-08 06:13
Duplicate of https://github.com/angular/angular/issues/9141

---

JSONP never supports header, not related to Angular.

**Closed** 2018-06-13 23:05 UTC
