### ISSUE TITLE
router.min.js doesn't generate link with [routerLink] directive (beta.1)

### ISSUE THREAD

**Issue by vjekoart** [angular/angular#6430] opened 2016-01-12 15:52 UTC
When creating simple route config inside component with and using [routeLink] directives inside template, elements won't get href attribute. When user clicks on element (that has routeLink directive, exception is thrown in console). Application has been tested in latest Firefox and Chrome versions.

*Code is written based on this example: https://angular.io/resources/live-examples/router/ts/plnkr.html
Developer guide: https://angular.io/docs/ts/latest/guide/router.html*

**Component file (.ts):**
```
@RouteConfig([
    {
        path: '/',
        name: 'Dashboard',
        component: DashboardComponent,
        useAsDefault: true
    }, {
        path: '/about',
        name: 'About',
        component: AboutComponent
    }
])
```

**Template file:**
```
<nav>
    <a [routerLink]="['Dashboard']">Dashboard</a>
    <a [routerLink]="['About']">About</a>
</nav>
```
**Console output (only one part of it because all dependencies are concatenated inside one file):**
```
Error: EXCEPTION: Error during evaluation of "click"
ORIGINAL EXCEPTION: TypeError: this.directive_1_0.onClick is not a function
ORIGINAL STACKTRACE:
anonymous/ChangeDetector_RootComponent_2.prototype.handleEventInternal@viewFactory_RootComponent:365:22
m</e.prototype.handleEvent...

ERROR CONTEXT:
[object Object]
```

When I changed from `router.min.js` to `router.dev.js` everything is working as expected.

*If needed I can include dependencies one by one for more detailed console output.*

**Comment by ericmartinezr** [comment] 2016-01-12 15:54
There are issues with minified bundles in beta.1. There's also too a PR for fix these issues https://github.com/angular/angular/pull/6397 (you can see the referenced issues)

**Comment by kcomas** [comment] 2016-01-13 04:02
I am having this issue with the dev router as well

**Comment by ericmartinezr** [comment] 2016-01-13 04:03
@kcomas reproducing the issue in a plnkr would be awesome, would be easier to track down the problem.

**Comment by kcomas** [comment] 2016-01-13 04:05
I will work on that right now but if you want to see the issue before then see here here https://github.com/kcomas/passit-front

**Comment by ericmartinezr** [comment] 2016-01-13 04:12
@kcomas 

You have a few weird things : 
- Why are you including every angular2 related file? Webpack is already bundling everything you need. You only have to include `angular2-polyfills.js` separately.
- Your bundle file is minified... which takes you back to the main problem...

**Comment by kcomas** [comment] 2016-01-13 04:17
weelp Im an idiot, thanks @ericmartinezr that fixed it

**Comment by btford** [comment] 2016-03-03 23:00
Looks like this was resolved. Closing.

**Closed by btford** 2016-03-03 23:00 UTC
Labels: comp: router, effort1: easy (hour), P2: required, type: bug
