### ISSUE TITLE
Two way databinding not working depending on how you write the template.

### ISSUE THREAD

**Issue by secorrenti** [angular/angular#54411] opened 2024-02-13 10:21 UTC
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

No

### Description

This not work as expected :-(
**Note, the value is updated after the function finish (because the order of the template)**
-----------------------------------------
<cib-user-card-management-new-card-message
(cardIssuingChange)="cardIssuingToggle($event)"  <--- move this below the @input 
[cardIssuing]="cardIssuing"
>
</cib-user-card-management-new-card-message>

.
.
.

Like this 
This work as expected :-)
(because the @Output is below the @Input)
-----------------------------------------
<cib-user-card-management-new-card-message
[cardIssuing]="cardIssuing"
(cardIssuingChange)="cardIssuingToggle($event)"
>
</cib-user-card-management-new-card-message>

**Comment by pkozlowski-opensource** [comment] 2024-02-13 10:32
It is impossible to understand / diagnose the problem based on the information provided. Please share a runnable reproduction scenario using stackblitz or similar.

**Comment by secorrenti** [comment] 2024-02-13 13:58
### Runnable reproduction scenario using stackblitz

Editor URL:
https://stackblitz.com/edit/angular-kk15rs?file=src%2Fmain.ts

Application URL:
https://angular-kk15rs.stackblitz.io

**Comment by pkozlowski-opensource** [comment] 2024-02-13 14:16
OK, thnx for the reproduction. This is essentially a duplicate of #11234

**Comment by pkozlowski-opensource** [comment] 2024-02-13 14:16
Duplicate of https://github.com/angular/angular/issues/11234

**Closed by pkozlowski-opensource** 2024-02-13 14:16 UTC
Labels: needs reproduction, area: core, core: inputs / outputs
