### ISSUE TITLE
One NgClass documentation example not working on Beta

### ISSUE THREAD

**Issue by AndresRCB** [angular/angular#6743] opened 2016-01-28 16:03 UTC
The code example for using NgClass with an Object as expression is not working on the Beta version. I'm referring to this section: https://angular.io/docs/ts/latest/guide/template-syntax.html#!#ngClass.

It seems that creating a component method which returns an object:
```javascript
setClasses() {
  let classes =  {
    saveable: this.canSave,      // true
    modified: !this.isUnchanged, // false
    special: this.isSpecial,     // true
  }
  return classes;
}
```
and then using it this way:
```javascript
<div [ngClass]="setClasses()">This div is saveable and special</div>
```
Generates this error:
`Error: Expression 'setClasses() in Component@line:col' has changed after it was checked. Previous value: '[object Object]'. Current value: '[object Object]'`

I'm using chrome 47.0.2526.111 m

I don't know whether this should work or the documentation should be changed, but it works with either constant objects, writing the object directly in the html template, etc.

One more suggestion is to add quotes to class names in ngClass examples since they are needed for keys with special characters (e.g. 'visible-md'):
```javascript
  let classes =  {
    'saveable-thing': this.canSave,      // true
    'modified-input': !this.isUnchanged, // false
    'special': this.isSpecial,     // true
  }
```
This is easy to notice when returned from the component but a little more troublesome to debug when the object is used in the html template, as shown here (classes don't have quotes in this section) https://angular.io/docs/ts/latest/api/common/NgClass-directive.html

**Comment by pkozlowski-opensource** [comment] 2016-01-28 16:12
Duplicate of https://github.com/angular/angular/issues/5950

**Closed by pkozlowski-opensource** 2016-01-28 16:12 UTC
