### ISSUE TITLE
Treeshakeable Injector resolution logic doesn't work in a lazy loaded scenario

### ISSUE THREAD

**Issue by robwormald** [angular/angular#23715] opened 2018-05-04 21:28 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
When combining lazy-loading via the Router + the v6 `providedIn: SomeModule` syntax, the injector resolution step seems to fail.

## Expected behavior
Should not throw an error

## Minimal reproduction of the problem with instructions
See https://stackblitz.com/edit/angular-v6-providedin-4gxxoa?file=app/lazy.component.ts

Observe that:
- AppModule uses the Router to lazy-load the `LazyModule`
- `LazyModule` routes to a `LazyComponent` which injects two services: `HelloService` and `GoodbyeService`
- `HelloService` is `providedIn: 'root'`
- `GoodbyeService` is `providedIn: LazyModule` 
- Click the "Lazy" link to route to the LazyComponent
- `HelloService` is successfully instantiated
- `GoodbyeService` fails with `ERROR Error: Uncaught (in promise): Error: StaticInjectorError(AppModule)[LazyComponent -> GoodbyeService]: `

**Comment by mhevery** [comment] 2018-05-04 21:35
@alxhub The issue is that `Injector_` uses `Services.resolveDep` which does not intercepts tree shakable providers.

**Comment by AhnpGit** [comment] 2018-05-05 10:46
@mhevery I tried to modify `providedIn: LazyModule` to `providedIn: LazyComponent` and it doesn't work either. Is it something similar to this issue ?

**Comment by manfredsteyer** [comment] 2018-05-05 18:36
I ran into this too. The (one) reson for this seems to be that such a scenario causes a cycle:

```
GoodbyeService -------> LazyModule --------> LazyComponent
      ^                                            |
      +--------------------------------------------+
```

**Comment by manfredsteyer** [comment] 2018-05-05 18:43
I've discussed this with @alxhub the other day. We can resolve the cycle by putting the service in an own service module:

```
                             +---------------------------------+
                             |                                 |
                        LazyModule --------> LazyComponent     |
                                                   |           |
      +--------------------------------------------+           |
      |                                                        |
      V                                                        |
GoodbyeService --------> LazyServiceModule <-------------------+
```

Just tried it out. Works like a charm.

**Comment by wKoza** [comment] 2018-05-05 19:40
Yes @manfredsteyer , you can also put the GoodbyeService in the root module with ```providedIn: 'root'```. GoodbyeService will be  well in the chunk of the layModule

**Comment by mlc-mlapis** [comment] 2018-05-05 19:44
... but as I guess it's not intended to instantiate `GoodbyeService` on app's root and also it's required not to use `providers: []` section of `LazyModule`.

**Comment by wKoza** [comment] 2018-05-05 20:37
@mlc-mlapis , all right

**Comment by about-code** [comment] 2018-05-06 15:35
```
                             +---------------------------------+
                             |                                 |
                        LazyModule --------> LazyComponent     |
                                                   |           |
      +--------------------------------------------+           |
      |                                                        |
      V                                                        |
GoodbyeService --------> LazyServiceModule <-------------------+
```

@manfredsteyer Is the promise of tree-shakability worth the complexity at all? The old way of providing `GoodbyeService` via `LazyModule`'s `providers` isn't deprecated, is it? So if `LazyComponent` depends on `GoodbyeService` then `GoodbyeService` doesn't fall off the tree, anyways. Because `LazyComponent` is used within the module's `declaration` array and as such `GoodbyeService` is transitively used when injected into `LazyComponent`.


In parts I see [my concerns](https://github.com/angular/angular-cli/issues/10170#issuecomment-379774801) proved in how people try to systematically migrate their existing code base to tree-shakable providers using `providedIn` then running into issues with circular deps. I think the topic deserves an Appendix in the Dependency Injection docs.

Citing the docs

> *Unless there is a special case, the value should always be root.*  https://angular.io/guide/dependency-injection#tree-shakable-providers

Citing @hansl 

> *providedIn: 'root' is the 99% of cases.* https://github.com/angular/angular-cli/issues/10170.

**Comment by alxhub** [comment] 2018-05-07 13:40
`Injector_` is I believe the node injector (for components, directives, etc). It shouldn't resolve lazy providers, as you can't say `providedIn: SomeComponent`. I'll have to look why this doesn't work with lazy loading, it's likely a bug.

**Comment by alxhub** [comment] 2018-05-07 21:37
As @manfredsteyer says, this is the result of a circular dependency between the component, service, and module.

**Comment by mlc-mlapis** [comment] 2018-05-07 21:43
@alxhub ... so the conclusion is: There is nothing what could be done. And Manfred description is the only way ... https://github.com/angular/angular/issues/23715#issuecomment-386826526.

**Comment by AhnpGit** [comment] 2018-05-08 05:53
I think perhaps the doc should contain an example for this situation @alxhub

**Comment by wKoza** [comment] 2018-05-08 07:01
@mlc-mlapis, Why is there nothing to do ? We can create an another keyword like 'lazy'  that, unlike 'root', would prevent injection into a component like AppModule / AppComponent.

**Comment by mlc-mlapis** [comment] 2018-05-08 07:07
@wKoza ... ah, of course, you are right. 😄 I meant `nothing to do` in a sense of code that would allow to use syntax like `providedIn: LazyModule`.

**Comment by alxhub** [comment] 2020-01-23 21:53
Closing this issue as there's nothing really we can do here, other than maybe detect and warn about this case (but even that would be pretty tricky).

**Closed by alxhub** 2020-01-23 21:53 UTC
Labels: comp: core, freq3: high, severity3: broken, type: bug/fix
