### ISSUE TITLE
LBP has incorrect decimal places

### ISSUE THREAD

**Issue by bbolek** [angular/angular#37921] opened 2020-07-04 04:48 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/core

### Is this a regression?

 As I tested 9.1.1 and 10, this does not work in both.

### Description

Currencies are formatted according to [ISO_4217](https://en.wikipedia.org/wiki/ISO_4217). LBP (Lebanese pound) should have 2 decimal places, but now it has zero.

## 🔬 Minimal Reproduction

[Stackblitz](https://stackblitz.com/edit/angular-ivy-w2ghtz?file=package.json)

## 🔥 Exception or Error
I was expecting LBP3000.00 and in second example LBP3000.33. But both printed LBP3000

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 9.1.1

Node: 12.16.0

OS: win32 x64

 

Angular: 9.1.1

... animations, cli, common, compiler, compiler-cli, core, forms

... platform-browser, platform-browser-dynamic, platform-server

... router

Ivy Workspace: Yes

 

Package                           Version

-----------------------------------------------------------

@angular-devkit/architect         0.901.1

@angular-devkit/build-angular     0.901.8

@angular-devkit/build-optimizer   0.901.8

@angular-devkit/build-webpack     0.901.8

@angular-devkit/core              9.1.1

@angular-devkit/schematics        9.1.1

@ngtools/webpack                  9.1.8

@nguniversal/builders             9.1.0

@nguniversal/common               9.1.0

@nguniversal/express-engine       9.1.0

@schematics/angular               9.1.1

@schematics/update                0.901.1

rxjs                              6.5.5

typescript                        3.8.3

webpack                           4.42.0
</code></pre>

**Anything else relevant?**

**Comment by ajitsinghkaler** [comment] 2020-07-04 13:03
> The data is actually generated from CLDR data.

> It seems like someone raised this already with the CLDR: https://unicode-org.atlassian.net/browse/CLDR-8790
> But the issue was closed with the following comment:
> 
> > The currency decimal place information in CLDR is intended to reflect what is the most common usage in the countries in question, (for generalized usage in most computer applications) and may or may not line up exactly with ISO4217.  In many of the cases, the true buying power of a single unit of the currency is so small that you would never see a currency value written with any decimal places, but ISO might still list the currency as a 2 decimal place currency.  There are certain specialized places such as banking or stock transactions where you might see the decimals, but for normal usage you would never see them.
> > One such example from your list, CRC (Costa Rica).  The exchange rate as I write this is 1 USD = 535 CRC.  So 1 CRC is worth less than 0.2 cents US.
> 
> Here is a link to the ISO standard that lists the LBP as having 2 decimal places: https://www.currency-iso.org/dam/downloads/lists/list_one.xml
> 
> Given that we generate this file form the data, the only path here is to try to get it changed in the CLDR by raising a new ticket.

The root cause is CLDR data is stale.

**Comment by pkozlowski-opensource** [comment] 2020-07-06 12:34
Yep, closing based on https://github.com/angular/angular/pull/37923#issuecomment-653760891

**Closed by pkozlowski-opensource** 2020-07-06 12:34 UTC
