### ISSUE TITLE
Module providers can't be used by design

### ISSUE THREAD

**Issue by PFight** [angular/angular#14207] opened 2017-01-31 17:35 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
If we use `providers` on the module, service [become application level](https://angular.io/docs/ts/latest/cookbook/ngmodule-faq.html#q-module-provider-visibility). So, it is way to provide application-level services (as it made in [example](https://embed.plnkr.co/?show=preview)).

But, if we create lazy-loaded module it can import another modules, and import its providers as well. Due to lazy loaded modules get their own root scope, imported providers will override application root providers, and dublicate instances of the services will be created.

So, if we using lazy-loaded modules, we should not use feature module providers at all - these services will be dublicated. We only can use providers of the AppModule. There is no use case, where feature module providers can be safely used.

[Additional info and documentation refs there](http://stackoverflow.com/questions/41925132/angular-where-to-provide-services).

**Expected behavior**

Something should be fixed in the architecture, to create use case for feature module providers, or this feature should be deprecated. Documentation should describe, how to define application-level providers (in AppModule, and not in feature modules).

* **Angular version:** 2.0.X

**Comment by DzmitryShylovich** [comment] 2017-01-31 17:44
Pls add a plunkr with reproduction.

**Comment by PFight** [comment] 2017-01-31 17:51
@DzmitryShylovich I don't know yet, how to create lazy-module. I just read [documentation](https://angular.io/docs/ts/latest/guide/ngmodule.html#!#why-_userservice_-isn-t-shared):

> Do not specify app-wide singleton providers in a shared module. A lazy loaded module that imports that shared module will make its own copy of the service.

**Comment by kevinwardenga** [comment] 2017-01-31 22:39
You could just implement the feature module with ModuleWithProviders:
```
@NgModule({
  imports: [],
  exports: [],
  declarations: []
})
export class MyFeatureModuleWithRootProviders {
  static forRoot(): ModuleWithProviders {
    return {
      ngModule: MyFeatureModuleWithRootProviders,
      providers: [ MyRootProvider ]
    };
  }
}
```

and import this module into the ApplicationRootModule with `MyFeatureModuleWithRootProviders.forRoot()`

And in your LazyModule just import `MyFeatureModuleWithRootProviders`

**Comment by PFight** [comment] 2017-02-01 07:49
@kevinwardenga so, every module, that provides services should be imported to the AppModule via forRoot? Isn't it strange? Maybe such behaviour should be by default? Otherwise module providers are dangerous to use, and there is no reason to keep them in such way.

**Comment by pkozlowski-opensource** [comment] 2017-02-01 09:13
Duplicate of #13854

**Closed by pkozlowski-opensource** 2017-02-01 09:13 UTC

**Comment by tytskyi** [comment] 2017-02-01 10:58
@kevinwardenga 
> so, every module, that provides services should be imported to the AppModule via forRoot?
you are correct, number of third party libraries for Angular are using this pattern. 
I also make my own modules in such fashion.
