### ISSUE TITLE
Cross contamination of excludes list between tsconfig.json and tsconfig-aot.json when running ngc.

### ISSUE THREAD

**Issue by josh-sachs** [angular/angular#14234] opened 2017-02-01 23:12 UTC
**I'm submitting a ...**  (check one with "x")
```
[ X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When running ngc against tsconfig-aot.json (as described here https://angular.io/docs/ts/latest/cookbook/aot-compiler.html) the typescript transpile step appears to be using the exclusion list defined in tsconfig.json.

**Expected behavior**

I should be able to exclude files in tsconfig.json, but still have them transpile when executing ngc against tsconfig-aot.json.

**Minimal reproduction of the problem with instructions**
-app
--main.ts
--app.module.ts
-aot
-tsconfig.json
-tsconfig-aot.json

use the file content provided by the AoT cookbook. [https://angular.io/docs/ts/latest/cookbook/aot-compiler.html](https://angular.io/docs/ts/latest/cookbook/aot-compiler.html)

in tsconfig.json add `exclude: ["aot"]`

when you run ngc -p tsconfig-aot.json the *.ngfactory.ts files generated in the aot folder will not be transpiled to javascript.

when I manually run tsc -p tsconfig-aot.json the transpile works as expected (no files excluded). 

**What is the motivation / use case for changing the behavior?**

In some instances you need to exclude the AOT output from being recognized by your IDE/development build process.  (e.g. my issue here: http://stackoverflow.com/questions/41969101/issue-with-angular-2-aot-ngc-visual-studio-2015-and-compileonsave).  The way you do this is exclude in the standard tsconfig.json file. 

When running ngc, I need to not ignore those assets (obviously) and it seems the intent is as such by the designation of the tsconfig-aot.json (non-standard) config file. 

What is even more strange, is that it appears to honor the es5/es2015 target/module from the tsconfig-aot.json file (it doesnt use the es5/commonjs from tsconfig.json).  Its just the exclusions list being co-mingled. 

**Please tell us about your environment:**

* **Angular version:** 2.0.X

2.4.4

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 N/A

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 2.1.5 

* **Node (for AoT issues):** `node --version` =  6.9.4

**Comment by DzmitryShylovich** [comment] 2017-02-01 23:20
Paste your tsconfig. there's no exclude` on https://angular.io/docs/ts/latest/cookbook/aot-compiler.html

**Comment by kudoz83** [comment] 2017-02-01 23:25
I know there isn't an exclude on tsconfig-aot.json, but that is a valid argument in the standard tsconfig.json. 

tsconfig.json
```
{
  "compileOnSave": true,
  "compilerOptions": {
	"target": "es5",
	"module": "commonjs",
	"moduleResolution": "node",
	"sourceMap": true,
	"emitDecoratorMetadata": true,
	"experimentalDecorators": true,
	"removeComments": false,
	"noImplicitAny": true,
	"suppressImplicitAnyIndexErrors": true,
         "allowSyntheticDefaultImports": true
  },
  "exclude": [
         "dst",
         "lib",
         "res",
         "aot"
  ]
}
```

tsconfig-aot.json
```
{
  "compilerOptions": {
    "target": "es5",
    "module": "es2015",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false,
    "suppressImplicitAnyIndexErrors": true,
    "allowSyntheticDefaultImports": true
  },
  "files": [
    "app/app.module.ts",
    "app/main-aot.ts"
  ]
}
```

**Comment by DzmitryShylovich** [comment] 2017-02-01 23:36
> it seems the intent is as such by the designation of the tsconfig-aot.json (non-standard) config file.

why do you thin it's `non-standard`? it's a completely standalone config file. you can call it whatever you want. They aren't merged by design.

`extend` is what you want https://www.typescriptlang.org/docs/handbook/tsconfig-json.html#configuration-inheritance-with-extends

**Comment by kudoz83** [comment] 2017-02-01 23:49
I believe the intent is that `ngc `compiles using the `angularCompilerOptions` which are indeed non-standard, and then follows up by running `tsc `with the standard options.   

The reason the cookbook has you maintain a separate `tsconfig-aot.json` is because the AoT transpile is different than the JIT/Development transpile.  What may be happening is that ngc is extending `tsconfig.json` with `tsconfig-aot.json` (I wasn't aware of the `extend `option). 

That said, if this is the case, I don't understand why it should be.  When I provide a named config file to `tsc` it doesn't assume I want to extend some other configuration that exists.  The cookbook states `ngc `is a drop in for `tsc`, and so should behave the same way.  

Is it clear the issue I'm trying to report?

**Comment by tbosch** [comment] 2017-04-10 17:53
Hello,
please refile this issue under github.com/angular/angular-cli, the repository for the angular-cli.

**Closed by tbosch** 2017-04-10 17:53 UTC
