### ISSUE TITLE
Update deprecated shadowRoot creation

### ISSUE THREAD

**Issue by HitkoDev** [angular/angular#23222] opened 2018-04-06 09:17 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

`ViewEncapsulation.Native` calls `Element.createShadowRoot`, which is a deprecated feature and is no longer supported by polyfills and some browsers.

## Expected behavior

`ViewEncapsulation.Native` calls `Element.attachShadow`, as per Custom Elements v1 specification.

## Minimal reproduction of the problem with instructions

- Create a new project with angular-cli and native view encapsulation
- Include `import '@webcomponents/webcomponentsjs'` in the polyfills file
- Open application in Firefox / Safari / Edge

## What is the motivation / use case for changing the behavior?

Most browsers never got Custom Elements v0 support, which means functions deprecated in Custom Elements v1 will never get implemented in those browsers.

## Environment

<pre><code>
Angular version: 5.2.9

Browser:
- [x] Firefox version all
- [x] Safari (desktop) version all
- [x] Safari (iOS) version all
- [x] IE version all
- [x] Edge version all
 
</code></pre>

**Comment by trotyl** [comment] 2018-04-06 12:11
Duplicate of https://github.com/angular/angular/issues/7856

**Comment by vicb** [comment] 2018-04-07 16:29
Closing as duplicate. (thanks @trotyl)

**Closed by vicb** 2018-04-07 16:29 UTC
