### ISSUE TITLE
304 Status Code

### ISSUE THREAD

**Issue by lucapompei** [angular/angular#37479] opened 2020-06-07 19:45 UTC
The 304 status code (Not Modified) should not be considered an error but a success result. So, the http should not generate an httpErrorResponse in output.

**Comment by pkozlowski-opensource** [comment] 2020-06-07 20:01
There was some prior discussion on this in #17605

**Comment by atscott** [comment] 2020-10-22 16:59
Closing as duplicate of #17605, see https://github.com/angular/angular/issues/17605#issuecomment-347699963

**Closed by atscott** 2020-10-22 16:59 UTC
Labels: comp: common/http
