### ISSUE TITLE
More documentation needed for ngTemplateOutlet

### ISSUE THREAD

**Issue by aikithoughts** [angular/angular#39349] opened 2020-10-20 21:11 UTC
# 📚 Docs or angular.io bug report

### Description

At present, we have very little documentation for ngTemplateOutlet. We've received community feedback that more documentation would be very helpful.

### Expected vs Actual Behavior**
Currently, ngTemplateOutlet is only documented here: https://angular.io/api/common/NgTemplateOutlet

We should consider adding one or more of the following:

* Expanding the Tour of Heroes tutorial to include ngTemplateOutlet
* Adding task-based documentation showing how to use ngTemplateOutlet
* Add a tutorial that demonstrates how to use ngTemplateOutlet

**Comment by StephenCooper** [comment] 2020-10-20 21:25
Could any example also include use of ngtemplateoutletcontext? I found the ability to hydrate the template with data from a different context a major benefit of ngtemplates over ngcontent. 

I found understanding the context along with the let- syntax suddenly made a lot of component libraries easier to understand and a lot less magical. This in turn lead to me being able to effectively use similar approaches. 

I have received a lot of feedback following the talk I gave on this topic at Angular Connect. For many devs they had completely missed the power of this feature and did not know it even was possible. I too was in that position until stumbling across an article that demonstrated its usefulness.

**Comment by aikidave** [comment] 2020-10-20 21:27
I am very open to this idea! Also, any chance your talk is still available somewhere? I joined Angular last November, so your talk was before my time, as it were. :D

**Comment by LayZeeDK** [comment] 2020-10-20 21:30
Design patterns involving `NgTemplateOutlet` are covered in [Agnostic components in Angular](https://indepth.dev/agnostic-components-in-angular/).

**Comment by LayZeeDK** [comment] 2020-10-20 21:31
I would prefer task-based and conceptual documentation over tutorials to cover `NgTemplateOutlet`.

**Comment by nartc** [comment] 2020-10-20 21:56
> I am very open to this idea! Also, any chance your talk is still available somewhere? I joined Angular last November, so your talk was before my time, as it were. :D

@aikidave  https://www.youtube.com/watch?v=2SnVxPeJdwE  this is @StephenCooper talk on `ngTemplateOutlet`.

**Comment by destus90** [comment] 2020-10-21 03:50
More info about [NgComponentOutlet](https://angular.io/api/common/NgComponentOutlet) would be very useful too. What is `ngComponentOutletNgModuleFactory` as an input property? How to use it? How can we pass input data and subscribe to output events?

**Comment by Airblader** [comment] 2020-10-21 05:00
I would appreciate if this documentation would also warn the user that the variables in a template are currently untyped though, as in a generally type-strong library like Angular that's an unexpected but significant downside.

**Comment by Airblader** [comment] 2020-10-21 05:22
Duplicate of #36895

Related to #17983 (since discussing the relationship to content projection and when to use which would also be helpful)

**Comment by arnotes** [comment] 2020-10-21 11:18
@Airblader not really a duplicate. we already have a doc for ngTemplateOutlet;
The problem with the docs is that it feels like a rabbit hole in a lost forest.
assuming I'm a new dev and If I google "angular component dynamic html", the chance that I get into the right docs is very slim.
Its more about increasing awareness that ngTemplateOutlet exists. e.g.(by making it part of Tour of Heroes)

**Comment by LayZeeDK** [comment] 2020-10-21 11:58
I challenge anyone to come up with a use case for dynamic rendering in a CRUD app as simple as Tour of Heroes.

**Comment by arnotes** [comment] 2020-10-21 12:33
^simple. a component called <super-powers>.
that accepts @Input templateRef for its list template.
let the trainee know that he can either use a ul/table/whatever he wants.
we dont need to justify about "why not edit super-powers.component.html directly".
the point of a tutorial is to showcase what can angular do and how to do it.

**Comment by Airblader** [comment] 2020-10-21 15:36
Personally I'd like to see not just what can be done and how but when and why (eg compared to content projection). I'm not convinced it has to be part of the ToH if it doesn't fit well, it could be separate from that.

**Comment by LayZeeDK** [comment] 2020-10-21 16:26
Plenty of more fundamental APIs missing in Tour of Heroes, for example an output property and event binding.

**Comment by arnotes** [comment] 2020-10-21 19:24
> Personally I'd like to see not just what can be done and how but when and why (eg compared to content projection). I'm not convinced it has to be part of the ToH if it doesn't fit well, it could be separate from that.

<ng-content> does not play well when you are trying to render an ngFor.
furthermore, you cannot pass context values to an ng-content.

this is a very common use case. not just in angular.
the react equivalent for ngTemplateOutlet+ngTemplateOutletContext would be the **render props** pattern.
https://reactjs.org/docs/render-props.html

**Comment by Airblader** [comment] 2020-10-21 19:43
I'm well aware of all these things myself, I'm saying that the docs should be discussing them for those who are not. As for ngFor, when using ng-content you'd typically let the user iterate over the results, which, again, depending on the use-case can be better (more control for the user) or worse (less control for the component).

**Comment by indraraj26** [comment] 2020-10-26 15:56
duplicate https://github.com/angular/angular/issues/36895

**Comment by arnotes** [comment] 2020-10-28 17:19
BUMP. to prevent bot close.

**Comment by Airblader** [comment] 2020-10-28 17:20
The bot doesn't close any issues, it only locks closed ones.

**Comment by arnotes** [comment] 2020-11-09 20:21
BUMP. to prevent bot locks.

**Comment by Airblader** [comment] 2020-11-09 20:22
@arnotes Again, the bot does not lock open issues. Please stop bumping and sending unnecessary emails to everyone subscribed.

**Comment by rooby** [comment] 2021-06-24 22:00
I think it’s a very bad idea to consider documentation as a feature request. They are not the same and should not be treated the same in regards to auto closing.

**Closed** 2022-03-28 23:53 UTC
Labels: type: bug/fix, comp: docs, P2
