### ISSUE TITLE
Defining an aux-route in child-component prevents leaving this route again

### ISSUE THREAD

**Issue by robwormald** [angular/angular#9479] opened 2016-06-22 19:06 UTC
_From @choeller on June 13, 2016 16:12_

When having 2 router-outlets in a child-component the aux-functionality works well, but as soon as you want to leave the child-route the following exception is thrown and the router stops working:
```
EXCEPTION: Error: Uncaught (in promise): Error: Outlet is not activated
```
the following plnkr demonstrates the behaviour:

http://plnkr.co/edit/wnHZzoB4xj5BbKWNzXUK?p=preview

the aux-outlet is defined in `crisis-center.component.ts`. When the application starts the crisis outlet is entered, when now trying to change to the heroes page the error occurs.

My use-case is to have an encapsulated part of my application that deals with "Tasks". When selecting a task I want to open a sidebar and display some important information about the task (JIRA-like). I already got this working in my application, but when once entering the "tasks" part I can never leave it again. 

_Copied from original issue: angular/vladivostok#44_

**Comment by robwormald** [comment] 2016-06-22 19:06
_From @gfrSE on June 21, 2016 6:22_

sorry to misuse your issue, but could you tell me how to navigate to aux-routes via [routeLink] ?
( if its possible? )

**Comment by robwormald** [comment] 2016-06-22 19:06
_From @choeller on June 21, 2016 7:38_

@gfrSE According to https://github.com/angular/vladivostok/issues/11 you can simply do something like:
```html
<a [routerLink]="['../aux:training/5']">chat 5</a>
```

**Comment by robwormald** [comment] 2016-06-22 19:06
_From @michaelchiche on June 21, 2016 7:59_

@choeller this seems to "half" work.  
What I mean is that the link is correctly generated and when clicked, it does load the secondary route, but it does not update the URL...

**Comment by robwormald** [comment] 2016-06-22 19:06
_From @gfrSE on June 21, 2016 8:43_

@michaelchiche it does.
See this Plunker: http://plnkr.co/edit/pI95yAXxukcvUfz5vMiK?p=preview
( Launch it in a separate window to view the correct url behaviour )
The additional link **AUX-Route** on the _Crisis Center_-View launches the TestComponent into the XXX-Outlet.

**Comment by robwormald** [comment] 2016-06-22 19:06
_From @michaelchiche on June 21, 2016 9:22_

I seem to have a weird bug. My routerlink directive does not insert the right data for ng-reflect-href & href attributes.

<img width="693" alt="capture d ecran 2016-06-21 a 11 20 05" src="https://cloud.githubusercontent.com/assets/371278/16224399/33bc1700-37a2-11e6-9e67-984699fab5d1.png">

I will make a plunker  to try to show/reproduce this problem.

**Comment by michaelchiche** [comment] 2016-06-23 08:05
@gfrSE,as said before, it works in your plunker. I did a fork a of the angular starter pack I use. and modified it to use aux routes and another router outlet. and as you will see, when you click on the "hello" link, it does not change the URL. 

https://github.com/michaelchiche/angular2-webpack

**Comment by vsavkin** [comment] 2016-07-08 18:30
I tried to reproduce the issue using the latest release of the router, and it looks like the issue has been fixed. Closing this.

**Closed by vsavkin** 2016-07-08 18:30 UTC
Labels: comp: router, type: bug
