### ISSUE TITLE
TestBed overrideModule doesn't work in ivy

### ISSUE THREAD

**Issue by nmatushevskiy** [angular/angular#33735] opened 2019-11-11 16:41 UTC
# 🐞 bug report

### Affected Package
The issue is caused by package angular/core

### Is this a regression?

Yes, the previous version in which this bug was not present was: 9.0.0-rc.1 without ivy.

### Description
I want to mock a child component in the parent component unit test by overriding.

child component:
```
@Component({
  selector: 'test-cmp',
  template: `<div>some text</div>`
})
export class TestComponent {
  testField = 'default';
}
```

parent component:
```
@Component({
  selector: 'app-root',
  template: `<test-cmp #testCmpCtrl></test-cmp>`,
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  @ViewChild('testCmpCtrl', {static: true}) testCmpCtrl: TestComponent;
}
```

parent component unit test:
```
@Component({
  selector: 'test-cmp',
  template: ``
})
class MockedTestComponent {
  testField = 'overwritten';
}

describe('AppComponent', () => {
  beforeEach(() => {
    TestBed.configureTestingModule({
      imports: [AppModule],
    }).overrideModule(TestModule, {
      remove: { declarations: [TestComponent], exports: [TestComponent] },
      add: { declarations: [MockTestComponent], exports: [MockTestComponent] }
    });
  });

  it('issue example', () => {
    const fixture = TestBed.createComponent(AppComponent);
    const app = fixture.componentInstance;

    expect(app.testCmpCtrl.testField).toBe('overwritten');
  });
});
```

Without ivy the test works correct, but with ivy the test fails with error: "Error: Expected 'default' to be 'overwritten'", which means that the override has not occurred.

## 🔬 Minimal Reproduction
github: https://github.com/nmatushevskiy/ivy-overrideModule-issue

* clone repository
* npm i
* ng test
unit test with issue you can find in: https://github.com/nmatushevskiy/ivy-overrideModule-issue/blob/master/src/app/app.component.spec.ts

## 🌍  Your Environment

Angular CLI: 9.0.0-rc.1
Node: 10.16.0
OS: darwin x64
Angular: 9.0.0-rc.1
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-rc.1
@angular-devkit/build-angular     0.900.0-rc.1
@angular-devkit/build-optimizer   0.900.0-rc.1
@angular-devkit/build-webpack     0.900.0-rc.1
@angular-devkit/core              9.0.0-rc.1
@angular-devkit/schematics        9.0.0-rc.1
@ngtools/webpack                  9.0.0-rc.1
@schematics/angular               9.0.0-rc.1
@schematics/update                0.900.0-rc.1
rxjs                              6.5.3
typescript                        3.6.4
webpack                           4.41.2

**Comment by AndrewKushnir** [comment] 2019-11-12 08:11
Hi @nmatushevskiy,

Thanks for reporting the issue and creating a repository with a repro.

I performed initial investigation and tried to extract TestBed scenario based on your Components/Modules scenario to repro the problem. Here is the test that I've created:

```
it('overrides an NgModule correctly', () => {

    // 1. TestModule + TestComponent...
    @Component({
      selector: 'test-cmp',
      template: `<div>some text</div>`,
    })
    class TestComponent {
      testField = 'default';
    }

    @NgModule({
      declarations: [TestComponent],
      exports: [TestComponent],
    })
    class TestModule {
    }

    // 2. AppModule + AppComponent...
    @Component({
      selector: 'app-root',
      template: `<test-cmp #testCmpCtrl></test-cmp>`,
    })
    class AppComponent {
      @ViewChild('testCmpCtrl', {static: true}) testCmpCtrl !: TestComponent;
    }

    @NgModule({
      declarations: [AppComponent],
      imports: [TestModule],
    })
    class AppModule {
    }

    // 3. Mock component to replace TestComponent...
    @Component({
      selector: 'test-cmp',
      template: ``,
    })
    class MockTestComponent {
      testField = 'overwritten';
    }

    // 4. TestBed setup...
    TestBed.configureTestingModule({imports: [AppModule]});

     // 5. Override module step...
    TestBed.overrideModule(TestModule, {
        remove: {declarations: [TestComponent], exports: [TestComponent]},
        add: {declarations: [MockTestComponent], exports: [MockTestComponent]}
    });

    // 6. Creating component and testing...
    const fixture = TestBed.createComponent(AppComponent);
    const app = fixture.componentInstance;
    expect(app.testCmpCtrl.testField).toBe('overwritten');
  });
```

The test runs successfully and the `TestComponent` component is being replaced with `MockTestComponent` one.

Could you please have a look at the test, try to run it and let me know if it works as expected for you? It's be great if we can repro the problem where Components/Modules are packaged in a single test - it's simplify further investigation. Otherwise, I will continue investigation using the repro that you provided.

Thank you.

**Comment by nmatushevskiy** [comment] 2019-11-12 17:27
Your variant really work. But if wrap this into beforeEach
```
beforeEach(() => {
    // 4. TestBed setup...
    TestBed.configureTestingModule({imports: [AppModule]});

    // 5. Override module step...
    TestBed.overrideModule(TestModule, {
      remove: {declarations: [TestComponent], exports: [TestComponent]},
      add: {declarations: [MockTestComponent], exports: [MockTestComponent]}
    });
  });
```
This variant wouldn't work.

"It's be great if we can repro the problem where Components/Modules are packaged in a single test - it's simplify further investigation" - done

**Comment by AndrewKushnir** [comment] 2019-11-13 07:15
Hi @nmatushevskiy, thanks for additional information. I was able to reproduce the problem and [created a draft PR](https://github.com/angular/angular/pull/33787) with proposed changes. Could you please try to test your use-case with the changes from the mentioned PR and let us know if everything works as expected? Thank you.

**Comment by kirillNikolaichuk** [comment] 2019-11-14 09:01
Hello! I work with @nmatushevskiy on the same team and also researched this issue. Please tell me how you can get edits from the specified PR in our project to verify that everything works as expected.
I tried doing something like the following in our package.json:
`"@angular/core": "git://github.com/github.com/AndrewKushnir/angular.git#testbed_override_module"`

But that does not work. I think the problem is that I tried to use the whole angular repository as "@angular/core" dependency.
Thank!

**Comment by AndrewKushnir** [comment] 2019-11-14 18:06
Hi @kirillNikolaichuk, please try to follow the steps below to get the changes from the mentioned PR and use it in the project:

- clone the sources of the framework locally and fetch the changes from that PR
- build Angular locally as [described in this instruction](https://github.com/angular/angular/blob/master/docs/DEVELOPER.md#building)
- create a symlink or replace existing "@angular/core" content with the package built during the previous step
- rebuild your app and test the behavior

Please let me know if that helps.

Thank you.

**Comment by kirillNikolaichuk** [comment] 2019-11-19 14:07
Unfortunately, I could not verify the changes :-(
I followed the instructions, downloaded the branch with the necessary edits. I was convinced that the edits in the downloaded branch are indeed present, I installed the dependencies. Then I ran the build-packages-dist.sh script. Got the "dist" folder. Walked along the path "dist\bin\packages\core". However, the core folder on this path is significantly different from the existing core folder.

The structure of the "dist\bin\packages\core" folder is as follows:

![image](https://user-images.githubusercontent.com/57749418/69153303-0674c980-0aef-11ea-8ad3-f11e2001b4af.png)


It seems that angular uses the contents of "@angular\core\bundles", however the result of the work of build-packages-dist.sh does not contain this folder and the files contained in it.

In addition, I tried to install the resulting core folder as the "@ angular/core" dependency and execute npm install, however it does not contain package.json, which causes an error.

Please tell me what I'm doing wrong?
Thanks!

Received after work

**Comment by gkalpak** [comment] 2019-11-19 16:32
@kirillNikolaichuk, the built packages should be in `dist/packages-dist/...` (not `dist/packages/...`).

##
But, there is an even better option :tada:
Recently, we made sure all PRs publish their build artifacts, so anyone can grab them from CI and verify the change in a local project. You can read more about it [here][1].

I.e., you can head over to the latest `publish_packages_as_artifacts` job for PR #33787 and get the build artifacts from the "Artifacts" tab: [artifacts][2]

[1]: https://github.com/angular/angular/blob/c68200cf4/docs/DEVELOPER.md#getting-packages-from-build-artifacts
[2]: https://circleci.com/gh/angular/angular/532665#artifacts/containers/0

**Comment by kirillNikolaichuk** [comment] 2019-11-20 09:26
@gkalpak Thanks!
Unfortunately, after running the build-packages-dist.sh script, I did not get the dist/packages-dist folder, only dist/packages.
However, artifacts helped me. I really got what I need.

I replaced @ angular/core with a similar folder from artifacts, ran a test, however I got an error:

![getComponentFromError](https://user-images.githubusercontent.com/57749418/69226033-8a32c280-0b90-11ea-99d1-831ac5a8e35d.JPG)

I looked where else besides @ angular/core getComponentFromError is used. Found that this is also used in @angular/platform-browser-dynamic. I also replaced this package and it helped, an error occurred and the test ended successfully.
Then I deleted beforeEach to check how the test would run without it. And the test failed, with an error:

`Error: Illegal state: Could not load the summary for directive AppComponent.
        error properties: Object({ ngSyntaxError: true })
            at syntaxError (webpack-internal:///./node_modules/@angular/compiler/fesm5/compiler.js:2737:17)
            at CompileMetadataResolver.getDirectiveSummary (webpack-internal:///./node_modules/@angular/compiler/fesm5/compiler.js:21816:31)
            at JitCompiler.getComponentFactory (webpack-internal:///./node_modules/@angular/compiler/fesm5/compiler.js:28037:46)
            at CompilerImpl.getComponentFactory (webpack-internal:///./platform-browser-dynamic/fesm5/platform-browser-dynamic.js:177:31)
            at TestingCompilerImpl.getComponentFactory (webpack-internal:///./platform-browser-dynamic/fesm5/testing.js:135:31)
            at TestBedViewEngine.createComponent (webpack-internal:///./new_core/fesm5/testing.js:2602:47)
            at Function.TestBedViewEngine.createComponent (webpack-internal:///./new_core/fesm5/testing.js:2294:40)
            at UserContext.eval (webpack-internal:///./ccm/views/registration/registration-subscribers-list/components/registration-subscribers-product-field-virtual/test1.spec.ts:89:85)
            at ZoneDelegate.invoke (webpack-internal:///./node_modules/zone.js/dist/zone.js:400:30)
            at ProxyZoneSpec.onInvoke (webpack-internal:///./node_modules/zone.js/dist/zone-testing.js:309:43)
`

I also replaced all other packages, such as "@ angular/compiler", "@ angular/common" and so on, however this did not lead to any expected results.
I made the replacement as replacing the folder in node_modules or I specify a link to it through "file:. / ..." in package.json.

In the test I used:

`describe('overrides an NgModule correctly', function () {
  // 1. TestModule + TestComponent
  @Component({
    selector: 'test-cmp',
    template: `<div>some text</div>`,
  })
  class TestComponent {
    testField = 'default';
  }

  @NgModule({
    declarations: [TestComponent],
    exports: [TestComponent],
  })
  class TestModule {
  }

  // 2. AppModule + AppComponent
  @Component({
    selector: 'app-root',
    template: `<test-cmp #testCmpCtrl></test-cmp>`,
  })
  class AppComponent {
    @ViewChild('testCmpCtrl', {static: true}) testCmpCtrl !: TestComponent;
  }

  @NgModule({
    declarations: [AppComponent],
    imports: [TestModule],
  })
  class AppModule {
  }

  // 3. Mock component to replace TestComponent...
  @Component({
    selector: 'test-cmp',
    template: ``,
  })
  class MockTestComponent {
    testField = 'overwritten';
  }

  beforeEach(() => {
    // 4. TestBed setup...
    TestBed.configureTestingModule({imports: [AppModule]});

    // 5. Override module step...
    TestBed.overrideModule(TestModule, {
      remove: {declarations: [TestComponent], exports: [TestComponent]},
      add: {declarations: [MockTestComponent], exports: [MockTestComponent]}
    });
  });

  it('Test name', function () {
    // 6. Creating component and testing...
    const fixture = TestBed.createComponent(AppComponent);
    const app = fixture.componentInstance;
    expect(app.testCmpCtrl.testField).toBe('overwritten');
  })
});`

**Comment by gkalpak** [comment] 2019-11-20 09:48
☝️ @AndrewKushnir

**Comment by AndrewKushnir** [comment] 2019-11-20 18:05
@kirillNikolaichuk, thanks for additional information. I looked at the error messages you mentioned and both of them were originated from ViewEngine TestBed code that was not affected by the changes in my PR, so it looks like there might be some configuration issue in your installation. I will try these steps in my local installation to see what went wrong with the setup.

Meanwhile we will move forward with merging #33787 and you should be able to test the fix once it's released as a part of RC.3 or RC.4.

Thank you.

**Comment by IgorMinar** [comment] 2019-11-27 21:28
Is this still a problem?

**Comment by sharikovvladislav** [comment] 2019-11-27 21:42
@IgorMinar I will ping guys from our team tomorrow. We discussed this the day before and looks like yes, it is a problem. I will ask somebody to answer here.

**Comment by AndrewKushnir** [comment] 2019-11-27 21:49
@sharikovvladislav the fix should be available as a part of upcoming 9.0.0-rc.4 release, so you should be able to test it with RC.4 version once it's available on NPM. Thank you.

**Comment by sharikovvladislav** [comment] 2019-11-27 21:51
@AndrewKushnir Thank you for the information! 

Looks like rc 4 will be released in a few days.

**Comment by AndrewKushnir** [comment] 2019-11-27 23:24
@sharikovvladislav Angular v9.0.0-rc.4 is now available on NPM. Could you please try to reproduce the error again with that version and let us know if the problem still exists? Thank you.

**Comment by kirillNikolaichuk** [comment] 2019-11-28 15:23
@AndrewKushnir Good day!
I can confirm that on RC4 the problem is resolved and is no longer reproducible.
Thanks!

**Comment by sharikovvladislav** [comment] 2019-11-28 16:09
@AndrewKushnir

@kirillNikolaichuk was on duty of that problem.
Looks like we tried to reproduce the problem and everything works fine now. Thank you.

**Comment by AndrewKushnir** [comment] 2019-11-28 22:40
Thanks for the update @kirillNikolaichuk and @sharikovvladislav. We are glad to know that everything works as expected now. Also thanks for detailed description of the problem, that helped a lot with investigation and the fix 👍

**Closed by AndrewKushnir** 2019-11-28 22:40 UTC
Labels: comp: core, comp: ivy, freq2: medium, severity5: regression, state: has PR, type: bug/fix
