### ISSUE TITLE
Moving a View to a different ViewContainer causes problems with creating future Components

### ISSUE THREAD

**Issue by badger2013** [angular/angular#13183] opened 2016-12-01 18:01 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
After a component is moved to a different ViewContainer, new Components that are added using "createComponent" on a ViewContainer are inserted into the wrong ViewContainer.

~~It looks like I need to do some combination of "insert" and "remove", which this comment in the source code alludes to:~~

	// TODO(i): refactor insert+remove into move
	ViewContainerRef_.prototype.insert = function (viewRef, index) {
	

~~The problem is that using this combination doesn’t work.  If I try to remove the ViewRef and then insert it elsewhere it's flagged as destroyed and it becomes unusable.~~

Edit:  After further investigation "detach" and then "insert" works where "insert"/"move" alone (or with "remove") does not.  That said, since "move" does not function on its own this still seems like an issue.  Additionally, the "detach" comment refers to moving a View "within the current container", but it does not need to be within the current container.

**Expected behavior**
~~When Components are moved they will not cause future component insertions to go to the wrong ViewContainer.~~

Using "insert"/"move" will not result in unexpected behavior if they are not used in conjunction with "detach" (alternatively, an exception that recommends the possibility of using "detach" in this situation would be helpful). 

**Minimal reproduction of the problem with instructions**

I've created the following Plunker which demonstrates the problem:  http://plnkr.co/edit/JRhGsje9ppzamNIsuk90?p=preview

To recreate the problem:

1. Add Left
2. Add Center
3. Move Last Center to Left
4. Add Center

The last “Add Center” will cause the component to be added to the left instead of the center.

**What is the motivation / use case for changing the behavior?**
Within my application Components are inserted, removed, and moved based on user interaction within a dashboard-like UI.  ~~In order for movement to work this needs to be resolved.~~

Edit:  Since I'm able to use "detach" in conjunction with "insert" I can achieve what I need to within the UI.  However, I would expect that "move" would work on its own to accomplish this.

**Please tell us about your environment:**
Windows 10, Visual Studio 2015, npm, IIS

* **Angular version:** 2.2.3

* **Browser:** [Chrome 54.0.2840.99 | Edge 25.10586.672.0]
 
* **Language:** [TypeScript 2.0.3.0]

* **Node (for AoT issues):** `node --version` = v7.1.0

**Comment by pkozlowski-opensource** [comment] 2019-02-13 19:40
This is a duplicate of #20824 (closing this one as we've got a newer reproduce scenario in #20824).

**Closed by pkozlowski-opensource** 2019-02-13 19:40 UTC
Labels: comp: core & compiler, freq1: low, severity3: broken, type: bug/fix
