### ISSUE TITLE
ngModule two way binding to radio input will disable the radio input incorrectly

### ISSUE THREAD

**Issue by li0803** [angular/angular#17415] opened 2017-06-12 09:02 UTC
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

ngModule two way binding to radio will disable all of the same group radio inputs which are located above the one has "disabled" attribute

**Expected behavior**

Only disable the input that has "disabled" attribute
**Minimal reproduction of the problem with instructions**

eg:
```<input type="radio" [(ngModel)]="splitWay" value="0" name="splitWay" class="form-check-input">
<input type="radio" [(ngModel)]="splitWay" disabled value="1" name="splitWay" class="form-check-input">
<input type="radio" [(ngModel)]="splitWay" value="2" name="splitWay" class="form-check-input">
The result is that the input "0","1" are disabled after rendering.
```
if:

```
<input type="radio" [(ngModel)]="splitWay" value="0" name="splitWay" class="form-check-input">
<input type="radio" [(ngModel)]="splitWay" value="1" name="splitWay" class="form-check-input">
<input type="radio" [(ngModel)]="splitWay" disabled value="2" name="splitWay" class="form-check-input">
```
The result is that the input "0","1","2" are disabled after rendering

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 4.1.3

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript 2.1.6 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by zoechi** [comment] 2017-06-12 09:17
Please provide a Plunker that allows to reproduce the issue (as requested in the issue template).
You can wrap code in ``` to get it properly formatted.

**Comment by li0803** [comment] 2017-06-12 09:33
Sorry, seems it works fine in Plunker. This may occur by my other library that was involved in my project

**Comment by li0803** [comment] 2017-06-12 09:35
OK. Here is the Plunker https://plnkr.co/edit/5ajvUViY3QbajCEjlqsg.
I can reproduce it now

**Comment by zoechi** [comment] 2017-06-12 09:54
Looks like a bug to me too.
The Plunker is not exactly the same as the code in your initial comment (`disabled` on another element)

**Comment by li0803** [comment] 2017-06-13 06:03
Yes, when move "disabled" to the last radio input. The two inputs before the last one are disabled too

**Comment by kara** [comment] 2018-01-02 23:56
This looks like a dupe of https://github.com/angular/angular/issues/11763

**Closed by kara** 2018-01-02 23:56 UTC
Labels: comp: forms
