### ISSUE TITLE
ngonit method of component  getting called twice which holds the router-outlet

### ISSUE THREAD

**Issue by gpradeepjain** [angular/angular#20925] opened 2017-12-10 18:02 UTC
I have a route requirement like localhost:4200/1234 where 1234 is mapped to adNo.

And i have child route like localhost:4200/ad1 and localhost:4200/ad2. landComponent oninit method gets the parameter and decides where it has to redirect internally.

Issue is that oninit method is called twice when page is loaded first i.e when localhost:4200/1234 is loaded, how can this be prevented.Calling twice happens when navigateByUrl is invoked. Below is the route code.  

```
Root Route
export const appRoutes: Routes = [
  { path: ':adNo', component: landComponent },
];

```
```

Child Route

export const subRoutes: Routes = [
  {
    path: '',
    component: landComponent,
    children: [{ path: 'ad1', component: infoComponent },
    { path: 'ad2', component: typeComponent }]
  }
];
```
```
LandComponent
ngOnInit() {    
   // logic to get the adNo and make service call
  let adNo = this._activatedRoute.snapshot.params['adNo'];
   console.log('working');
   this._router.navigateByUrl('ad1', { skipLocationChange: true });
}
```

**Comment by mlc-mlapis** [comment] 2017-12-10 18:15
@gpradeepjain ... when you are saying that `OnInit` hook is called twice ... it means that 2 instances are created? What happened when you'll the following code?
```
export class LandComponent implements OnInit {
	constructor() {
		console.log('... a new instance of LandComponent has been created')
	}
	ngOnInit() {
		console.log('... OnInit hook on LandComponent is called)
	}
}
```

**Comment by gpradeepjain** [comment] 2017-12-10 18:24
constructor message gets logged once. If i console adNo from routeparam in ngonint. First it prints proper routparam i.e. 1234 second time it prints undefined.

**Comment by mlc-mlapis** [comment] 2017-12-10 18:57
@gpradeepjain ... so the problem is not that `OnInit` hook is called twice but that two instances of `LandComponent` component are created.

**Comment by mlc-mlapis** [comment] 2017-12-10 18:59
@gpradeepjain ... create a simple plunker reproduction of the problem.

**Comment by gpradeepjain** [comment] 2017-12-10 19:06
Sure. Will try to do it. I see that on main route if i dont use rout params and make it like
```
 Root Route
export const appRoutes: Routes = [
  { path: '', component: landComponent },
];
```
You can see i removed :adNo, This causes the ngonit/constructor to be called/created once. Creating a plunker may take time.

**Comment by jotatoledo** [comment] 2017-12-10 23:03
This is just a wrong use of the api, not an angular issue. You should use stackoverflow or similar to troubleshoot this

**Comment by gpradeepjain** [comment] 2017-12-11 03:33
Created a demo https://stackblitz.com/edit/angular4-routeissue You can try to access URL - https://angular4-routeissue.stackblitz.io/4566 and in console you can see the output/issue.

**Comment by vaibhavphutane** [comment] 2017-12-11 19:56
by using snapshot you can prevent this

**Comment by mlc-mlapis** [comment] 2017-12-11 22:09
@gpradeepjain ... you have a route in the main app module `/457` which leads to instantiating of the first instance of `LandComponent` in `<router-outlet></router-outlet>` which is placed in the template of `app.component.html`.
```
{ path: ':adNo', component: LandComponent }
```
... then `LandComponent` component is from `LandsModule` which has defined a route:
```
{path: '', component: LandComponent}
```
which leads to instantiating of the second instance of `LandComponent` in `<router-outlet></router-outlet>` which is placed in the template of `land.component.html`.

So the actual behavior that 2 instances of `LandComponent` component are created and their `ngOnInit` hooks are called is totally OK.

**Comment by jasonaden** [comment] 2017-12-11 23:00
It appears this was fixed with the above suggestion. The StackBlitz link is now working.

**Closed by jasonaden** 2017-12-11 23:00 UTC

**Comment by gpradeepjain** [comment] 2017-12-12 06:19
@mlc-mlapis  - Any way to prevent this second call by changing of route?
@jasonaden - Just checked the link and it works fine.

**Comment by mlc-mlapis** [comment] 2017-12-12 07:56
@gpradeepjain ...don't understand what you mean ... it's not about the call of `this._router.navigateByUrl('ad1', { skipLocationChange: true });`. It is about ... that you have two `<router-outlet>` and you simply have two `LandComponent` instancies. And the second of them has `{path: '', component: LandComponent}` ... no route param ... that's why `console.log(adNo);` prints `undefined` on the console.

Plus each of them is calling `this._router.navigateByUrl('ad1', { skipLocationChange: true });` in itself ... so you probably have to re-think all the logic ...

> Any way to prevent this second call by changing of route?

**Comment by hinalshah91** [comment] 2018-03-21 13:33
So what is the solution to this? Even i need to define to routes: one with routeparams and other without it.

**Comment by mlc-mlapis** [comment] 2018-03-21 14:27
@hinalshah91 ... the routes `'/:id'` and `''` are different routes.

**Comment by gopal05** [comment] 2018-09-12 07:02
@mlc-mlapis Can you tell me how we can fix to this problem. My project is using two <router-outlet>

**Comment by de87684333** [comment] 2018-10-03 14:54
@mlc-mlapis @gpradeepjain Hello, Could you explain what was the change between the first version (with the two constructor calls) and the latest version (with only one constructor call)? I don't see it. Thanks
