### ISSUE TITLE
Service Worker update crashes with property access on undefined

### ISSUE THREAD

**Issue by topaxi** [angular/angular#24333] opened 2018-06-06 22:11 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
Service Worker is unable to update itself when previously cached resource is missing.

```
NGSW Debug Info:

Driver state: EXISTING_CLIENTS_ONLY (Degraded due to failed initialization: Cannot read property 'previouslyCachedResources' of undefined
TypeError: Cannot read property 'previouslyCachedResources' of undefined
    at Driver.<anonymous> (http://localhost:8420/ngsw-worker.js:2522:28)
    at Generator.next (<anonymous>)
    at fulfilled (http://localhost:8420/ngsw-worker.js:1752:58))
Latest manifest hash: none
Last update check: 28s186u



=== Idle Task Queue ===
Last update tick: never
Last update run: never
Task queue:


Debug log:

[33s886u] TypeError(Cannot read property 'previouslyCachedResources' of undefined, TypeError: Cannot read property 'previouslyCachedResources' of undefined
    at Driver.<anonymous> (http://localhost:8420/ngsw-worker.js:2522:28)
    at Generator.next (<anonymous>)
    at fulfilled (http://localhost:8420/ngsw-worker.js:1752:58)) Error occurred while updating to manifest 29046d73feb9473635caee1641ad064a3653cb99
[28s151u] TypeError(Cannot read property 'previouslyCachedResources' of undefined, TypeError: Cannot read property 'previouslyCachedResources' of undefined
    at Driver.<anonymous> (http://localhost:8420/ngsw-worker.js:2522:28)
    at Generator.next (<anonymous>)
    at fulfilled (http://localhost:8420/ngsw-worker.js:1752:58)) Error occurred while updating to manifest 29046d73feb9473635caee1641ad064a3653cb99
```

## Expected behavior
Service Worker should still be able to update itself.

## Environment

<pre><code>
Angular version: 6.0.4

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 10.3.0  
- Platform:  Linux 

Others:

</code></pre>

**Comment by gkalpak** [comment] 2018-06-08 14:06
This is not about previously cached resources missing. It is about not beeing able to retrieve the version associated with the `latestHash` (at a point in time when it is expected that such a version exists).

This is hard to investigate without more info, though. Do you happen to be able to consistently reproduce this (and can post the reproduction steps)? Could you also share your config?

**Comment by rosslavery** [comment] 2018-07-05 19:35
I was having this exact issue a while ago, and ended up giving up and going back to my custom SW implementation. I figured it was something on my end causing the issue, and since no one else was having the same problem, I reverted.

@gkalpak I can try and find the release that had the problem, but there was honestly not much to my implementation. Was just a copy-paste of the SW tutorial from Angular docs.

Not sure if related, but I also have similar (but different) output in some of my other app's ngsw/state output:

```
NGSW Debug Info:

Driver state: EXISTING_CLIENTS_ONLY (Degraded due to failed initialization: Invariant violated (initialize): latest hash null has no known manifest
Error: Invariant violated (initialize): latest hash null has no known manifest
    at Driver.<anonymous> (<OMITTED>/ngsw-worker.js:2171:23)
    at Generator.next (<anonymous>)
    at fulfilled (<OMITTED>/ngsw-worker.js:1752:58))
Latest manifest hash: none
Last update check: 10s223u



=== Idle Task Queue ===
Last update tick: 15s618u
Last update run: 10s607u
Task queue:


Debug log:

[10s202u] Error(Invariant violated (initialize): latest hash null has no known manifest, Error: Invariant violated (initialize): latest hash null has no known manifest
    at Driver.<anonymous> (<OMITTED>/ngsw-worker.js:2171:23)
    at Generator.next (<anonymous>)
    at fulfilled (<OMITTED>/ngsw-worker.js:1752:58)) Error occurred while updating to manifest 1cc4fff4ad725b79abf6de73a9a5d1679455045e
```

Although that one may be more tied to #22087.

**Comment by gkalpak** [comment] 2018-07-06 06:36
Thx for the additional info, @rosslavery.
AFAICT, this must be from a previous version, because I can't see how the current version of `ngsw-worker.js` could produce a message like "latest hash null has no known manifest" 😕 

Like I said, this is hard to act on without a reproduction (using the latest version) 😞

**Comment by gkalpak** [comment] 2018-07-06 06:37
I am going to close this, since there isn't much we can do without a reproduction.
Feel free to submit a new issue if you manage to somehow reproduce the error.

**Closed by gkalpak** 2018-07-06 06:37 UTC
Labels: comp: service-worker, type: bug/fix

**Comment by rweng** [comment] 2018-07-12 15:53
I am having this problem, too, and in the generated ngsw-worker.js there is this code:

```js
// Finally, assert that the latest version is in fact loaded.
                if (!this.versions.has(latest.latest)) {
                    throw new Error(`Invariant violated (initialize): latest hash ${latest.latest} has no known manifest`);
                }
```

Using angular 6.0.9

**Comment by gkalpak** [comment] 2018-07-12 16:09
Works for me 😕

**Comment by RanjeetAvghad** [comment] 2018-11-23 05:17
I also got the same error for updating service worker cashes and gives error Error while updating manifest and hash.

here is the info from ngsw/state

NGSW Debug Info:

Driver state: EXISTING_CLIENTS_ONLY (Degraded due to failed initialization: Cannot read property 'previouslyCachedResources' of undefined
TypeError: Cannot read property 'previouslyCachedResources' of undefined
    at Driver.previouslyCachedResources (http://localhost:8080/ngsw-worker.js:2405:24))
Latest manifest hash: none
Last update check: 9s18u



=== Idle Task Queue ===
Last update tick: never
Last update run: never
Task queue:


Debug log:

[7m14s334u] TypeError(Cannot read property 'previouslyCachedResources' of undefined, TypeError: Cannot read property 'previouslyCachedResources' of undefined
    at Driver.previouslyCachedResources (http://localhost:8080/ngsw-worker.js:2405:24)) Error occurred while updating to manifest 7af82f431b659e67e2be9bc9893bd95ea16bc067
[6m13s91u] TypeError(Cannot read property 'previouslyCachedResources' of undefined, TypeError: Cannot read property 'previouslyCachedResources' of undefined

It works for first 2 - 3 times after that it starts giving error. doesn't find any solution.
