### ISSUE TITLE
afterNextRender runs immediately in unit test before the input is set

### ISSUE THREAD

**Issue by MurhafSousli** [angular/angular#57767] opened 2024-09-11 06:57 UTC
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

I am trying to write unit test for my component but I am unable to change my input value  inside `afterNextRender`

    
```ts
constructor() {
  afterNextRender({
    write: () => {
      if (this.disabled()) {
         this.myStream.next('hello');
      }
    }
  });
}
```

```ts
it('should emits value to the stream when disabled is true', async () => {
  fixture.componentRef.setInput('disabled', true);

  await firstValueFrom(component.myStream);
      
  expect(component.disabled()).toEqual(true);
});
```

The test waits forever then fails. it seems that `afterNextRender` is executed in the constructor as soon as the component is created in the unit test, the input is false at that time, I need to be able to set the input first then call it to execute, similar to how we do with `ngOnInit` for instance.

It is not mentioned in the docs, how to unit test the rendering life cycles.

How can I do this test with `afterNextRender`?

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 18.2.3
Node: 20.11.1
Package Manager: npm 9.6.1
OS: win32 x64

Angular: 18.2.3
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, material, platform-browser, platform-browser-dynamic
... platform-server, router, ssr

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1802.3
@angular-devkit/build-angular   18.2.3
@angular-devkit/core            18.2.3
@angular-devkit/schematics      18.2.3
@schematics/angular             18.2.3
ng-packagr                      18.2.1
rxjs                            7.8.1
typescript                      5.5.4
zone.js                         0.14.10
```

**Comment by atscott** [comment] 2024-09-11 12:59
Duplicate of https://github.com/angular/angular/issues/57313

**Closed by atscott** 2024-09-11 12:59 UTC
