### ISSUE TITLE
Angular testing docs refer to newEvent however this is not part of Angular

### ISSUE THREAD

**Issue by CraigComeOnThisNameCantBeTaken** [angular/angular#27192] opened 2018-11-20 14:05 UTC
# 📚 Docs or angular.io bug report

### Description

 A clear and concise description of the problem...

Angular docs refer to newEvent for testing the DOM with input html elements however newEvent is not part of core testing files and as such to find this code you must look through angular github testing examples.

see: https://angular.io/guide/testing

## 🔬 Minimal Reproduction
cosnt filter = fixture.nativeElement.querySelector('input');
filter.value = 'something';
filter.dispatchEvent(newEvent('input'));
fixture.detectChanges();

### What's the affected URL?**
 https://angular.io/...
https://angular.io/guide/testing

### Expected vs Actual Behavior**

Expected: newEvent is importable from angular exports and documented
Actual: Example on site expects user to know what this is and how to find what this function does with no guidance

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by trotyl** [comment] 2018-11-20 14:20
Duplicate of https://github.com/angular/angular/issues/23370

**Comment by CraigComeOnThisNameCantBeTaken** [comment] 2018-11-20 14:34
is it actually a duplicate? When I went looking for newEvent in the github repo I found this.

```
/**
 * Create custom DOM event the old fashioned way
 *
 * https://developer.mozilla.org/en-US/docs/Web/API/Event/initEvent
 * Although officially deprecated, some browsers (phantom) don't accept the preferred "new Event(eventName)"
 */
export function newEvent(eventName: string, bubbles = false, cancelable = false) {
    const evt = document.createEvent('CustomEvent');  // MUST be 'CustomEvent'
    evt.initCustomEvent(eventName, bubbles, cancelable, null);
    return evt;
}
```

To me that says that although new event should be used if we want to do headless testing we need this utility.

**Comment by trotyl** [comment] 2018-11-20 14:43
As already explained there, `newEvent` is not part of the framework (not even testing), but the application code in the example app which wasn't well-documented.

**Comment by CraigComeOnThisNameCantBeTaken** [comment] 2018-11-20 15:00
Sorry I meant **should it be** if new event wont always work.

Anyway thanks for the answer. I will just use new event and assume all good.

**Closed** 2018-11-20 15:00 UTC
