### ISSUE TITLE
Data-binding input type attribute does not use the correct ControlValueAccessor

### ISSUE THREAD

**Issue by mephistorine** [angular/angular#45690] opened 2022-04-20 06:58 UTC
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

No

### Description

If use static input type number his value has type number:

```html
<input type="number" [formControl]="someFormControl">
```

`typeof someFormControl.value` is `number`. But if apply input type with data-binding like this:

```html
<input [attr.type]="dynamicInputType" [formControl]="someFormControl">
```

`typeof someFormControl.value` is `string`. With input type range the same behaviour.

This happens because directive selector is static, and when i use data-binding with type attribute selector does not match.

https://github.com/angular/angular/blob/989e840cce7ebe94311ae898786e09b1b41ce7f6/packages/forms/src/directives/number_value_accessor.ts#L43-L70

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-yzmurz?file=src/app/app.module.ts

### Anything else?

I would not say that this is a bug, this is how the framework itself works, I think at least it should be described in the documentation.

**Comment by JoostK** [comment] 2022-04-20 08:16
Duplicate of #13243

**Closed by JoostK** 2022-04-20 08:16 UTC
Labels: comp: forms
