### ISSUE TITLE
Callback functions in ng2 adapter ('&' on directive)

### ISSUE THREAD

**Issue by KKS1** [angular/angular#10576] opened 2016-08-08 20:11 UTC
Hi,

It appears that when ‘&’event handler binding is attached to a directive, the callback function works completely differently in ng1 vs ng2Adapter world.
ng2 adapter (updgradedev.js), 

ng2Adapter
         (value) {
            return emitter.emit(value);
          }

ng1
         (locals) {
            return parentGet(scope, locals);
          }

What happens due to this, is any callback, where we are waiting for user input, say return true or false, wont work.
Emitter.emit runs right away, returning undefined. And then async callback is done on the app controller function.

This is stopping few our designs which rely on callback return value, to perform certain operations.

I looked into the EventEmitter under upgradedev.js. It seems its always initializing it with isAsync ‘true’. Plus, there is no handling of returning .next(), so that we can use RxJs observables to achieve this.

Wondering if you guys have faced this issue yet. And if any workaround possible.

Thanks,
Kanwaljeet Singh Kalra

**Comment by gkalpak** [comment] 2017-04-18 15:34
[`EventEmitter`][1] are synchronous by default for a while now and they extend RxJS' `Subject`, so this issue should be (partly?) addressed.

##
Also, I am not sure what you mean by the following:

> What happens due to this, is any callback, where we are waiting for user input, say return true or false, wont work. `Emitter.emit` runs right away, returning `undefined`. And then async callback is done on the app controller function.

Apart from the async part (which is now sync), the rest sounds like expected behavior. This is how outputs/EventEmitters work in Angular and this behavior will only affect upgraded components, i.e. versions of the components appearing in Angular (2+) templates.

I am going to close this, since everything works as expected now (afaict), but feel free to open a new issue if you are still facing problems.

[1]: https://github.com/angular/angular/blob/bebedfed24d6fbfa492e97f071e1d1b41e411280/packages/core/src/event_emitter.ts

**Closed by gkalpak** 2017-04-18 15:34 UTC
Labels: comp: upgrade/dynamic
