### ISSUE TITLE
Metadata extractor treats "function" differently than a lambda

### ISSUE THREAD

**Issue by jelbourn** [angular/angular#13853] opened 2017-01-10 06:30 UTC
The metadata extractor allows this:
```ts
export function FACTORY(parentDispatcher: ViewportRuler) {
  return parentDispatcher || new ViewportRuler();
};
```

But not this:
```ts
export const FACTORY = (parentDispatcher: ViewportRuler) => {
  return parentDispatcher || new ViewportRuler();
};
```

The latter results in
```
Error: Error encountered resolving symbol values statically. 
Function calls are not supported. 
Consider replacing the function or lambda with a reference to an exported function 
(position 59:48 in the original .ts file), 
resolving symbol VIEWPORT_RULER_PROVIDER_FACTORY in...
```

Note from @chuckjaz:
```
The reason we don't today is because we blindly inline local references. 
What we should should only conditionally inline (simplify) exported constants.
```

**Comment by DzmitryShylovich** [comment] 2017-01-10 07:56
Duplicate of https://github.com/angular/angular/issues/13614

**Closed** 2018-11-29 23:18 UTC
Labels: comp: core & compiler, hotlist: angular-core-team, hotlist: material2, severity2: inconvenient, workaround2: non-obvious
