### ISSUE TITLE
Form Array of Form Groups incorrect typing

### ISSUE THREAD

**Issue by devKid88** [angular/angular#40842] opened 2021-02-14 14:26 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/forms

### Is this a regression?

 Not sure

### Description

 When we create Form Array with Form Groups we have TS error when we try to use controls from a Form Group since in Form Array class controls are AbstractControl[]

## 🔬 Minimal Reproduction

 https://stackblitz.com/edit/angular-ivy-ffkysj

## 🔥 Exception or Error
<pre><code>

 Property 'controls' does not exist on type 'AbstractControl'.
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

 11.2.0
</code></pre>

**Comment by petebacondarwin** [comment] 2021-02-14 16:06
This is basically a duplicate of #13721, which asks for `FormArray` to be a generic collection, constrained to the type of the item in the array. There are various PRs working to solve this: #40772, #38906 and #38406. Please follow along there.

Meanwhile you can easily workaround this by dynamically casting the controls in your code: https://stackblitz.com/edit/angular-ivy-b2nufz

**Closed by petebacondarwin** 2021-02-14 16:06 UTC

**Comment by devKid88** [comment] 2021-02-14 16:33
Thank you,

yes, I know how to fix it, but since I could not find a concrete bug I created it so you could check it and track it, since #13721 has a generic title, I wasn't sure does it cover this one.

But I understand now, thanks for the clarification.
