### ISSUE TITLE
Component Testing Scenario: Please Include Custom Form Control

### ISSUE THREAD

**Issue by adnan333bd** [angular/angular#41990] opened 2021-05-07 15:00 UTC
Hi, looks like there is no clue over the internet how to test a custom control that implements the interface ControlValueAccessor. The usual way, wrapping inside a host component does not work.
Would you please include a working example in the doc ...?

Thanks a lot

**Comment by jnizet** [comment] 2021-05-07 20:03
Wrapping inside a host component is how I (and others) test them, and it works fine. See for example the ng-bootstrap's rating component, which is a ControlValueAccessor, and which uses this technique to test its usage as a form control: https://github.com/ng-bootstrap/ng-bootstrap/blob/master/src/rating/rating.spec.ts#L531

**Comment by adnan333bd** [comment] 2021-05-16 14:35
Thanks, @jnizet, the example you provided helped to find what was wrong in my case, my component did not initialize the handlers in the declaration, which are needed in unit test.
`public onTouch = () => {};
  public onModelChange = (_: any) => {};`

**Comment by AndrewKushnir** [comment] 2021-05-24 22:19
Closing this issue based on the comments in this thread (it looks like the issue was caused by some missing code in tests).

**Closed by AndrewKushnir** 2021-05-24 22:19 UTC
Labels: comp: docs, feature
