### ISSUE TITLE
Angular 2 template driven form radio button not working

### ISSUE THREAD

**Issue by GregWoods** [angular/angular#7642] opened 2016-03-17 09:09 UTC
This issue was raised after not seeing any evidence of a fix for #4084, #3104 

**Problem**
Using a purely template driven form, 2 way data binding does not appear to work. Here's how I would expect it to work based on other angular2 form elements:
[plnkr.co/edit/46duKk](http://plnkr.co/edit/46duKk?p=preview)

```
<input [(ngModel)]="model.Gender" name="Gender" value="male" type="radio">
<input [(ngModel)]="model.Gender" name="Gender" value="female" type="radio">
```

**Workaround in Beta3**
The exact code above works in Beta3 using the following third-party component: 
[radio_value_accessor.ts](https://github.com/angular2-school/angular2-radio-button/blob/master/modules/ng-school/controls/radio/radio_value_accessor.ts)

**Workaround 1 (Beta8,9)**
Ignore 2 way binding, and add a template variable to make things easier
```
<input #m [checked]="model.Gender == m.value" (click)="model.Gender = m.value" name="Gender" value="male" type="radio">
<input #f [checked]="model.Gender == f.value" (click)="model.Gender = f.value" name="Gender" value="female" type="radio">
```
I am happy to use this at the moment, but it feels very clunky, and not in line with the philosophy of [(ngMode)].

**Workaround 2 - using a third-party component (untested)**
This appears to be a nice solution, as it allows radio buttons to be grouped using either a "radio-box" attribute directive or a <radio-group> element
[github.com/pleerock/ng2-radio-group](https://github.com/pleerock/ng2-radio-group)

It is quite possible I'm missing something important, but several radio button related issues have been closed without any evidence of it working in a template driven component. Nor has any clue been given about what directives are required to make it work.

- Angular version: 2.0.0-beta.9
- Browser: IE11
- Language:TypeScript

**Comment by valorkin** [comment] 2016-03-24 15:43
Actually +2 workarounds if someone will need them from (https://github.com/valor-software/ng2-bootstrap):
- implementing control value accessor + ng-model (https://github.com/valor-software/ng2-bootstrap/tree/master/components/buttons)
- or without ng-model (https://github.com/valor-software/ng2-bootstrap/pull/280/files)

**Comment by UberMeatShield** [comment] 2016-04-14 15:41
Greg's comment still seems to be a valid concern in beta.15, from experience with angular 1 it would make more sense to have the checked state and value updates handled by providing an [(ngModel)].  The work around is valid but just seems a little awkward in such a clean framework.

**Comment by tycho01** [comment] 2016-04-27 05:17
By now [angular2-material](https://www.npmjs.com/package/@angular2-material/radio) provides a valid alternative as well.

Otherwise, +1 to incorporating something like that custom `radio_value_accessor`.

@vsavkin's [commit](https://github.com/angular/angular/commit/e725542) provided the following example in tests:

    <form>
      <input type="radio" name="food" ngControl="chicken" [(ngModel)]="data['chicken1']">
      <input type="radio" name="food" ngControl="fish" [(ngModel)]="data['fish1']">
    </form>

That syntax appears to assume using separate underlying controls and model variables, which may have made sense in the case of checkbox groups, but the obvious use-case for radio controls would be to instead have a radio control 'group' linked to a single underlying model variable, as in the example given above.

**Comment by schippie** [comment] 2016-05-19 12:59
I also find the way its currently implemented weird, it indeed seems to assume that a radio button holds two completely separate model values. While in general this is not a way you want to use radio buttons. Instead you normally have one set of radio buttons controlling one value.

**Comment by thomasbee** [comment] 2016-05-27 07:50
Having different ngControls for the different inputs seems wrong. I would like to be able to start with no radio button of a group being selected and have my form valid and dirty, if a selection was made. Hence I need to hook a validator. This plunkr illustrates weird cross-talk between two groups of radio buttons that should be entirely independent.

https://plnkr.co/edit/b063cRLdItaqSVTNGekc?p=preview

Repeated inline here

```
export class App {
  form: ControlGroup;
  constructor(private fb: FormBuilder) {
    this.form = fb.group({
      maleOrFemale: fb.group({
        male: [new RadioButtonState(false, 'male')],
        female: [new RadioButtonState(false, 'female')],
      },
      {
        validator: this.maleOrFemaleValidator
      }),
      blackOrWhite: fb.group({
        black: [new RadioButtonState(false, 'black')],
        white: [new RadioButtonState(false, 'white')],
      },
          {
        validator: this.blackOrWhiteValidator
      })
    })
  }
  
  maleOrFemaleValidator(group: ControlGroup) {
    // verify that one button is checked
    if (group.value.female.checked || group.value.male.checked) {
      console.log("male female OK")
      return null;
    }
      console.log("male female NOK")
    return { noSelection: true }
  }
  
  blackOrWhiteValidator(group: ControlGroup) {
    // uncomment next line to only have a single validator
    // with a single validator, 
    // return null; 
      
    // verify that one button is checked
    if (group.value.white.checked || group.value.black.checked) {
      console.log("black whlte OK")
      return null;
    }
      console.log("black white NOK")
    return { noSelection: true }
  }
```

template
```
  <div>
      <h2>Form with 2 Groups of Radio Buttons each with Validator</h2>
      <form [ngFormModel]="form" (ngSubmit)="submit()">
        <p>Choose</p>
        <div>
          <label>
            <input type="radio" name="sex" 
              [ngFormControl]="form.controls['maleOrFemale'].controls['male']">
              Male                                 
          </label>
          <label>
            <input type="radio" name="sex" 
              [ngFormControl]="form.controls['maleOrFemale'].controls['female']">
              Female
          </label>
          | Group valid: {{form.controls['maleOrFemale'].valid}}
        </div>
        <div>
          <label>
            <input type="radio" name="color" 
              [ngFormControl]="form.controls['blackOrWhite'].controls['black']">
              Black                                 
          </label>
          <label>
            <input type="radio" name="color" 
              [ngFormControl]="form.controls['blackOrWhite'].controls['white']">
              White
          </label>
          | Group valid: {{form.controls['blackOrWhite'].valid}}
        </div>
        <button type="submit">Submit</button>
        <div>Form dirty: {{form.dirty}}, Form valid: {{form.valid}}</div>
        <div>Problem: form should be valid if a radio button was checked
             for both groups, but isn't. Selecting a gender makes the first
             group valid, then selecting a color makes the second group valid
             but the first one invalid.</div>
      </form>
    </div>
```

**Comment by mrlukrative** [comment] 2016-06-21 04:01
I've created a version by using just a click event on the elements loaded and passing the value of the selection into the function "getSelection" and updating the model.

In your template:

<ul>
     <li *ngFor="let p of price"><input type="radio" name="price"      (click)="getValue(price.value)" value="{{p}}" #price> {{p}} 
     </li>
</ul>

Your class:

export class App {

  price:string;

  price = ["1000", "2000", "3000"];

  constructor() {   }

  model = new SomeData(this.price);

  getValue(price){
    this.model.price = price;
  }
}
See example: https://plnkr.co/edit/2Muje8yvWZVL9OXqG0pW?p=info

**Comment by kara** [comment] 2016-07-07 02:07
Radio buttons have been revamped in the new forms module (RC.2 and onward).  They no longer require separate underlying controls.  See new usage here: #9228. 

Closing, as the issue is no longer applicable. Please feel free to re-open if you see problems with the new module.

**Closed by kara** 2016-07-07 02:07 UTC
Labels: comp: core/forms, freq2: medium

**Comment by AnthonyBr** [comment] 2016-09-29 07:20
Here is a way to make work radio buttons with angular2: 
http://stackoverflow.com/questions/39391910/angular-2-how-to-create-radio-buttons-from-enum-and-add-two-way-binding
