### ISSUE TITLE
Unable to get property 'add' of undefined with NgClass in IE11.

### ISSUE THREAD

**Issue by krishollenbeck** [angular/angular#11005] opened 2016-08-23 13:32 UTC
**I'm submitting a ...**
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Using NgClass on an svg element throws an error in Internet Explorer 11. 

> Unable to get property 'add' of undefined.

![ie10-error-ngclass](https://cloud.githubusercontent.com/assets/1056684/17893594/e90784f6-690b-11e6-850c-290b587fb481.png)

**Expected/desired behavior**

Using NgClass on svg should not throw an error in Internet Explorer 11.

**Reproduction of the problem**

**Example:**

```
import {Component, NgModule, NgClass} from '@angular/core'
import {BrowserModule} from '@angular/platform-browser'

@Component({
  selector: 'my-app',
  template: `
    <svg height="100" width="100" [ngClass]="svgClass">
      <circle cx="50" cy="50" r="40" stroke="black" stroke-width="3" fill="red" />
    </svg>
  `
})
export class App {
  constructor() {
    this.name = 'Angular2 (Release Candidate!)'
  }
  
  get svgClass()
  {
    return 'test';
  }
}

@NgModule({
  imports: [ BrowserModule ],
  declarations: [ App ],
  bootstrap: [ App ]
})
export class AppModule {}
```

**DEMO:**

https://plnkr.co/edit/7sE32rIrE4aiWdWe2D8d?p=preview

**What is the expected behavior?**

The expected behavior is to have a css class applied to the svg element.

**What is the motivation / use case for changing the behavior?**

N/A

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4 or 2.0.0-rc.5
 
* **Browser:**  IE 11
 
* **Language:**  TypeScript 1.8.10 or 2.0.0 | ES6/7 | ES5

**Comment by mlaval** [comment] 2016-08-23 15:38
Duplicate of https://github.com/angular/angular/issues/6327, a shim is available

**Closed by mlaval** 2016-08-23 15:38 UTC
