### ISSUE TITLE
UnhandledPromiseRejectionWarning: RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by smiera** [angular/angular#43203] opened 2021-08-19 09:36 UTC
### Which @angular/* package(s) are the source of the bug?

compiler-cli

### Is this a regression?

Yes

### Description

Trying to update from 11.2.14 to 12.2.2.
When i run `ng b` I get error:
```
⠧ Generating browser application bundles (phase: sealing)...(node:18744) UnhandledPromiseRejectionWarning: RangeError: Maximum call stack size exceeded
    at String.match (<anonymous>)
    at streamChunksOfSourceMapFull (/Users/smirnov/work/project/node_modules/webpack/node_modules/webpack-sources/lib/helpers/streamChunksOfSourceMap.js:21:23)
    at module.exports (/Users/smirnov/work/project/node_modules/webpack/node_modules/webpack-sources/lib/helpers/streamChunksOfSourceMap.js:389:6)
    at SourceMapSource.streamChunks (/Users/smirnov/work/project/node_modules/webpack/node_modules/webpack-sources/lib/SourceMapSource.js:211:11)
    at module.exports (/Users/smirnov/work/project/node_modules/webpack/node_modules/webpack-sources/lib/helpers/streamChunks.js:13:17)
    at ReplaceSource.streamChunks (/Users/smirnov/work/project/node_modules/webpack/node_modules/webpack-sources/lib/ReplaceSource.js:176:44)
    at module.exports (/Users/smirnov/work/project/node_modules/webpack/node_modules/webpack-sources/lib/helpers/streamChunks.js:13:17)
    at streamAndGetSourceAndMap (/Users/smirnov/work/project/node_modules/webpack/node_modules/webpack-sources/lib/helpers/streamAndGetSourceAndMap.js:27:53)
    at CachedSource.streamChunks (/Users/smirnov/work/project/node_modules/webpack/node_modules/webpack-sources/lib/CachedSource.js:208:35)
    at module.exports (/Users/smirnov/work/project/node_modules/webpack/node_modules/webpack-sources/lib/helpers/streamChunks.js:13:17)
    at ConcatSource.streamChunks (/Users/smirnov/work/project/node_modules/webpack/node_modules/webpack-sources/lib/ConcatSource.js:112:55)
    at module.exports (/Users/smirnov/work/project/node_modules/webpack/node_modules/webpack-sources/lib/helpers/streamChunks.js:13:17)
    at streamAndGetSourceAndMap (/Users/smirnov/work/project/node_modules/webpack/node_modules/webpack-sources/lib/helpers/streamAndGetSourceAndMap.js:27:53)
    at CachedSource.streamChunks (/Users/smirnov/work/project/node_modules/webpack/node_modules/webpack-sources/lib/CachedSource.js:208:35)
    at module.exports (/Users/smirnov/work/project/node_modules/webpack/node_modules/webpack-sources/lib/helpers/streamChunks.js:13:17)
    at ConcatSource.streamChunks (/Users/smirnov/work/project/node_modules/webpack/node_modules/webpack-sources/lib/ConcatSource.js:112:55)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:18744) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:18744) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
⠙ Generating browser application bundles (phase: sealing)...^C
```

Then I try run with node
`node --unhandled-rejections=strict --trace-warnings ./node_modules/@angular/cli/bin/ng b`
Error below...

### Please provide the exception or error you saw

```true
$ node --unhandled-rejections=strict --trace-warnings ./node_modules/@angular/cli/bin/ng b
Warning: Support was requested for IE 11 in the project's browserslist configuration. IE 11 support is deprecated since Angular v12.
For more information, see https://angular.io/guide/browser-support
⠴ Generating browser application bundles (phase: sealing).../Users/smirnov/work/project/node_modules/webpack/node_modules/webpack-sources/lib/helpers/streamChunksOfSourceMap.js:21
        const lines = source.match(SPLIT_LINES_REGEX);
                             ^

RangeError: Maximum call stack size exceeded
    at String.match (<anonymous>)
    at streamChunksOfSourceMapFull (/Users/smirnov/work/project/node_modules/webpack/node_modules/webpack-sources/lib/helpers/streamChunksOfSourceMap.js:21:23)
    at module.exports (/Users/smirnov/work/project/node_modules/webpack/node_modules/webpack-sources/lib/helpers/streamChunksOfSourceMap.js:389:6)
    at SourceMapSource.streamChunks (/Users/smirnov/work/project/node_modules/webpack/node_modules/webpack-sources/lib/SourceMapSource.js:211:11)
    at module.exports (/Users/smirnov/work/project/node_modules/webpack/node_modules/webpack-sources/lib/helpers/streamChunks.js:13:17)
    at ReplaceSource.streamChunks (/Users/smirnov/work/project/node_modules/webpack/node_modules/webpack-sources/lib/ReplaceSource.js:176:44)
    at module.exports (/Users/smirnov/work/project/node_modules/webpack/node_modules/webpack-sources/lib/helpers/streamChunks.js:13:17)
    at streamAndGetSourceAndMap (/Users/smirnov/work/project/node_modules/webpack/node_modules/webpack-sources/lib/helpers/streamAndGetSourceAndMap.js:27:53)
    at CachedSource.streamChunks (/Users/smirnov/work/project/node_modules/webpack/node_modules/webpack-sources/lib/CachedSource.js:208:35)
    at module.exports (/Users/smirnov/work/project/node_modules/webpack/node_modules/webpack-sources/lib/helpers/streamChunks.js:13:17)
    at ConcatSource.streamChunks (/Users/smirnov/work/project/node_modules/webpack/node_modules/webpack-sources/lib/ConcatSource.js:112:55)
    at module.exports (/Users/smirnov/work/project/node_modules/webpack/node_modules/webpack-sources/lib/helpers/streamChunks.js:13:17)
    at streamAndGetSourceAndMap (/Users/smirnov/work/project/node_modules/webpack/node_modules/webpack-sources/lib/helpers/streamAndGetSourceAndMap.js:27:53)
    at CachedSource.streamChunks (/Users/smirnov/work/project/node_modules/webpack/node_modules/webpack-sources/lib/CachedSource.js:208:35)
    at module.exports (/Users/smirnov/work/project/node_modules/webpack/node_modules/webpack-sources/lib/helpers/streamChunks.js:13:17)
    at ConcatSource.streamChunks (/Users/smirnov/work/project/node_modules/webpack/node_modules/webpack-sources/lib/ConcatSource.js:112:55)
```

### Please provide the environment you discovered this bug in

```true
Angular CLI: 12.2.2
Node: 14.15.4
Package Manager: npm 6.14.10
OS: darwin x64

Angular: 12.2.2
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, platform-browser, platform-browser-dynamic, router
... service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.2
@angular-devkit/build-angular   12.2.2
@angular-devkit/core            12.2.2
@angular-devkit/schematics      12.2.2
@schematics/angular             12.2.2
ng-packagr                      12.2.0
rxjs                            6.6.7
typescript                      4.3.5
```

### Anything else?

Sorry, project is big and I don't know how to create minimal reproduction :(

**Comment by JoostK** [comment] 2021-08-19 10:54
Duplicate of angular/angular-cli#21599.

**Closed by JoostK** 2021-08-19 10:54 UTC
