### ISSUE TITLE
ng update should remove entryComponents since they are no longer needed

### ISSUE THREAD

**Issue by johnpapa** [angular/angular#35246] opened 2020-02-08 05:54 UTC
# 🚀 Feature request

`ng update` should remove entryComponents since they are no longer needed

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description
 A clear and concise description of the problem or missing capability...

`ng update` should remove entryComponents since they are no longer needed

**Comment by JoostK** [comment] 2020-02-08 10:02
Closing as duplicate of #34399

**Closed by JoostK** 2020-02-08 10:02 UTC
Labels: comp: core
