### ISSUE TITLE
Support Named Routes

### ISSUE THREAD

**Issue by erlandmuchasaj** [angular/angular#44803] opened 2022-01-24 16:44 UTC
### Which @angular/* package(s) are relevant/releated to the feature request?

router

### Description

It would be nice to have a feature like named routes in [vueJS](https://router.vuejs.org/guide/essentials/named-routes.html).

The name will be used as an alias for each route. 
The advantage  is that is much easy to maintain and to manage/update the routes.
Named routes allow the convenient generation of URLs or redirects for specific routes without the need to remember the full url of the route. 
For example one application might have routes in different languages but the name can be always in one language (English)

https://laravel.com/docs/8.x/routing#named-routes
https://router.vuejs.org/guide/essentials/named-routes.html

### Proposed solution

Just like the [VueJs](https://router.vuejs.org/guide/essentials/named-routes.html)

### Alternatives considered

None

**Comment by JoostK** [comment] 2022-01-24 16:47
This is a duplicate of #24775.

**Closed by JoostK** 2022-01-24 16:47 UTC
