### ISSUE TITLE
Angular.dev docus Dubplication issue 

### ISSUE THREAD

**Issue by asadgujar** [angular/angular#53938] opened 2024-01-16 10:53 UTC
### Describe the problem that you experienced

In our angular documentation same line display in two time
![image](https://github.com/angular/angular/assets/35732077/6168402a-306a-4119-8900-8d9721edee04)

### Enter the URL of the topic with the problem

https://angular.dev/guide/components

### Describe what you were looking for in the documentation

https://angular.dev/guide/components
in this url i see a one line twice time i'll update image 
![image](https://github.com/angular/angular/assets/35732077/68b51eb1-7443-4396-8465-2b47fbd7c08c)

**Comment by JoostK** [comment] 2024-01-16 11:00
Thanks for the report, this is a duplicate of https://github.com/angular/angular/issues/52575 for which the fix is pending deployment.

**Closed by JoostK** 2024-01-16 11:00 UTC
