### ISSUE TITLE
ngComponentOutlet and Output events

### ISSUE THREAD

**Issue by djflex68** [angular/angular#14958] opened 2017-03-06 15:30 UTC
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When a dynamically injected component triggers en event (using Output and EventEmitter), it's never catched by the component that has the directive *ngComponentOutlet set, 

**Expected behavior**
The event should be catched

**Minimal reproduction of the problem with instructions**
```
<ng-container *ngFor="let dialog of dialogs">
        <ng-container (dialogActionCompleted)="onDialogActionSelected($event)" *ngComponentOutlet="dialog.type">
        </ng-container>
    </ng-container>
```

On this code, dialogActionCompleted is never catched. In Subject.js (rxjs), this.observers array is empty (indicating that nothing is listening to the event).
I've tried to create a "fake component", thinking that it was related to the fact that ng-container should be a component, But I get the same behavior.

**Please tell us about your environment:**
Windows 7, Visual Studio

* **Angular version:** 2.0.X
v2.4.9 + ngComponentOutlet directive included manually in the solution

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
All browsers
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 2.0

Any workaround (even quick & dirty) would be appreciated :)

**Comment by DzmitryShylovich** [comment] 2017-03-06 15:32
please add a plunkr

**Comment by DzmitryShylovich** [comment] 2017-03-22 14:26
@djflex68 you can't listen for event of dynamically created components like this. There's a proposal to add events https://github.com/angular/angular/pull/15362 so you will be able to get a reference to a component to set inputs or subscribe to uoutputs

**Comment by pkozlowski-opensource** [comment] 2017-07-19 09:28
Duplicate of #15360

**Closed by pkozlowski-opensource** 2017-07-19 09:28 UTC
Labels: comp: common, type: bug
