### ISSUE TITLE
FormGroup misses to assign the disabled FormControl value

### ISSUE THREAD

**Issue by DavideViolante** [angular/angular#41400] opened 2021-03-31 16:35 UTC
# 🐞 bug report

### Affected Package
Forms, Reactive Forms

### Is this a regression?
Idk

### Description
Having this formGroup
```ts
this.addRecordForm = this.formBuilder.group({
  // Commented line works
  //_user: ["123", Validators.required],
  _user: [{ value: "123", disabled: true }, Validators.required],
  test: ["anything", Validators.required]
});
```
If you print addRecordForm value then you have:
```json
{ "test": "anything" }
```
But `_user` property is missing.

If you use the commented line instead, the `_user` property is correctly assigned.
Also if you use the commented line and I disable the select from the DOM (in the template), it works correctly, but it prints the warning below.

Please see the repro below.

## 🔥 Exception or Error
<pre><code>

// This is printed if I use disabled in the template but not in the component (and it works)
It looks like you're using the disabled attribute with a reactive form directive. If you set disabled to true
      when you set up this control in your component class, the disabled attribute will actually be set in the DOM for
      you. We recommend using this approach to avoid 'changed after checked' errors.

      Example:
      form = new FormGroup({
        first: new FormControl({value: 'Nancy', disabled: true}, Validators.required),
        last: new FormControl('Drew', Validators.required)
      })

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 11.0.1
Node: 14.16.0
OS: linux x64

Angular: 11.0.0
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.1
@angular-devkit/build-angular   0.1100.1
@angular-devkit/core            11.0.1
@angular-devkit/schematics      11.0.1
@angular/cli                    11.0.1
@schematics/angular             11.0.1
@schematics/update              0.1100.1
rxjs                            6.6.3
typescript                      4.0.2

</code></pre>

**Anything else relevant?**

**Comment by indraraj26** [comment] 2021-03-31 17:14
duplicate https://github.com/angular/angular/issues/36894

you can use getRawValue

**Comment by AndrewKushnir** [comment] 2021-03-31 18:40
Closing as a duplicate of #36894.

**Closed by AndrewKushnir** 2021-03-31 18:40 UTC
