### ISSUE TITLE
Angular 17 - build is broke

### ISSUE THREAD

**Issue by KarlXOL** [angular/angular#52947] opened 2023-11-16 05:26 UTC
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

When building an angular 17 app the build is broken with this error:
![grafik](https://github.com/angular/angular/assets/21153915/b4a8dc00-f9b3-42ff-b72a-b26f3b6b4084)

That's probably related to the <esbuild> builder. If so, then the tooling is not ready for to be used for productiv angular apps.

Reproduction via playground:
import {Component} from '@angular/core';
import {bootstrapApplication} from '@angular/platform-browser';
import mysvg from './mysvg.svg'

@Component({
  selector: 'app-root',
  standalone: true,
  template: `
    Hello world!
  `,

})
export class PlaygroundComponent {
  
}

bootstrapApplication(PlaygroundComponent);

### Please provide the exception or error you saw

```true
Application bundle generation failed. [0.282 seconds]
⠹ Changes detected. Rebuilding...✘ [ERROR] TS2307: Cannot find module './mysvg.s' or its corresponding type declarations. [plugin angular-compiler]

    src/main.ts:3:18:
      3 │ import mysvg from './mysvg.s'
        ╵
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
1) Angular Playground

2) Local
Angular CLI: 17.0.0
Node: 20.9.0
Package Manager: npm 10.1.0
OS: win32 x64
```

**Comment by JoostK** [comment] 2023-11-16 05:53
This is a duplicate of https://github.com/angular/angular-cli/issues/26336.

**Closed by JoostK** 2023-11-16 05:53 UTC

**Comment by KarlXOL** [comment] 2023-11-16 05:58
Strange, it was planned to broke build.
Angular (team) is hard to understand
