### ISSUE TITLE
local_id use value do not change the locale

### ISSUE THREAD

**Issue by stevenmi** [angular/angular#17018] opened 2017-05-25 13:45 UTC
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

i have done all this
import { LOCALE_ID } from '@angular/core';
{ provide: LOCALE_ID, useValue: 'en-ca' }
but console.log(new Date().toLocaleDateString());  is yyyy-m-d
**Expected behavior**

i want the locale change to 'en-ca'
**Minimal reproduction of the problem with instructions**

https://plnkr.co/edit/ulSNTMTMZmORzvkVTvch?p=preview
**What is the motivation / use case for changing the behavior?**

change the locale for Date
**Please tell us about your environment:**

win10 

* **Angular version:** 2.0.X

angular 4.1.3
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 chrome 58.0.3029.110 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
typescript 2.3.1
* **Node (for AoT issues):** `node --version` =   
node v6.10.1

**Comment by dawidgarus** [comment] 2017-05-25 14:11
It might be duplicate of https://github.com/angular/angular/issues/16960.
Also, `Date` uses browser's locale, not locale defined by angular. Use `Intl` or angular's `DatePipe` to format date according to custom locale id.

**Comment by ocombe** [comment] 2017-07-03 13:22
Yes, closing this as a duplicate.

**Closed by ocombe** 2017-07-03 13:22 UTC
Labels: comp: i18n
