### ISSUE TITLE
Load Component Dynamically Using Selector Name

### ISSUE THREAD

**Issue by rsangin** [angular/angular#35284] opened 2020-02-10 10:19 UTC
Hi, I was using Angular 8 for a while and I had a method that returned component instance using It's selector name. My method is like this: 

```
public loadComponent<T>(componentName: string, viewMode: ViewMode): { instance: T, componentRef: ComponentRef<any> } {
        let instance: T;
        const view = viewMode === ViewMode.graph ? 'Graph' : 'Map';
        const selectorName = _.kebabCase('App' + componentName + view);

        const factories: any[] = Array.from((this.componentFactoryResolver as any)._factories.values());
        const factory = factories.find(item => {
            const selectors: string[] = item.selector.split(',').map(x => x.trim());
            return selectors.includes(selectorName);
        });

        const factoryClass = factory && factory.componentType;

        let componentRef: ComponentRef<any> = null;

        const componentFactory = this.componentFactoryResolver.resolveComponentFactory(factoryClass);
        componentRef = this.viewContainerRef.createComponent(componentFactory);

        instance = <T>componentRef.instance;

        return { instance: instance, componentRef: componentRef };
    }
```

**I've updated Angular version to 9 and I'm having a problem with this code**. _factories is not defined in componentFactoryResolver object. So I've changed this code to this: 

```
public loadComponent<T>(componentName: string, viewMode: ViewMode): { instance: T, componentRef: ComponentRef<any> } {
        let instance: T;
        const view = viewMode === ViewMode.graph ? 'Graph' : 'Map';
        const selectorName = _.kebabCase('App' + componentName + view);

        const factory = this.compiler.compileModuleAndAllComponentsSync(PluginsModule).componentFactories.find(x => x.selector.split(',').includes(selectorName));

        const factoryClass = factory && factory.componentType;

        let componentRef: ComponentRef<any> = null;

        const componentFactory = this.componentFactoryResolver.resolveComponentFactory(factoryClass);
        componentRef = this.viewContainerRef.createComponent(componentFactory);

        instance = <T>componentRef.instance;

        return { instance: instance, componentRef: componentRef };
    }
```

This code works in development mode but in production mode this code doesn't work neither. My question is what can I do now? **What is the replacement of _factories in Angular 9?**

**Comment by mlc-mlapis** [comment] 2020-02-10 10:48
@rsangin The `_factories` was never a public API. Also `compileModuleAndAllComponentsSync` can't work with AOT mode because you don't have the Angular compiler in run-time available.

**Comment by rsangin** [comment] 2020-02-10 11:07
> @rsangin The `_factories` was never a public API. Also `compileModuleAndAllComponentsSync` can't work with AOT mode because you don't have the Angular compiler in run-time available.

So what can I do for this method?

**Comment by mlc-mlapis** [comment] 2020-02-10 12:40
@rsangin Probably the first step is to understand what you want to do. What is the goal? From above mentioned, it's not possible to say anything.

**Comment by pkozlowski-opensource** [comment] 2020-02-10 13:19
It _sounds_ like a duplicate of the existing issue #24360 (a possible use-case might be something along the lines of #33715). In any case we are talking about the private API here and sadly, we can't guarantee that private APIs from release to release.

Closing as a duplicate of  #24360

**Closed by pkozlowski-opensource** 2020-02-10 13:19 UTC
