### ISSUE TITLE
Input parameter order does matter

### ISSUE THREAD

**Issue by constantant** [angular/angular#40007] opened 2020-12-07 15:22 UTC
After updating from 8th to the 10th version, the input parameter order does matter.

# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/core

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 8th version

### Description
In case the Input decorator is used on a setter and a parallel input parameter is used inside the setter, this parallel parameter is not available during the setter execution.

## 🔬 Minimal Reproduction

 https://stackblitz.com/edit/angular-ivy-parameter-order-bug?file=src%2Fapp%2Fapp.component.html

## 🔥 Exception or Error
<pre>Error: cannot read property 'bla' of undefined<code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre>10.2.3<code>

</code></pre>

**Anything else relevant?**

**Comment by petebacondarwin** [comment] 2020-12-07 15:29
It seems that in ViewEngine (i.e. Angular v8) the inputs were evaluated in alphabetic order. See:

* `b` depends upon `a`: https://stackblitz.com/edit/angular-ivy-parameter-order-bug-sr8vw6?file=src%2Fapp%2Fapp.component.ts
* `a` depends upon `b`: https://stackblitz.com/edit/angular-ivy-parameter-order-bug-lx2kcm?file=src%2Fapp%2Fapp.component.ts

**Comment by petebacondarwin** [comment] 2020-12-07 15:33
Assuming that this is not an expected regression (I don't see it in the breaking changes for ivy), then it could be resolved in the Ivy compiler by sorting inputs before generating instructions, I believe.

**Comment by dopusteam** [comment] 2020-12-07 16:06
> Assuming that this is not an expected regression (I don't see it in the breaking changes for ivy), then it could be resolved in the Ivy compiler by sorting inputs before generating instructions, I believe.

Well, I believe nothing changed since [this comment](https://github.com/angular/angular/issues/34322#issuecomment-571822815)

> To answer your question, we don't consider input setting order within directives to be public API. If you want to react to a directive's inputs in a certain order, using the ngOnChanges lifecycle hook tends to be a better place. As such, I'm closing this issue as working as intended.

**Comment by lazarljubenovic** [comment] 2020-12-07 22:00
I've been bitten by this once before, but once I realized what was happening, my stance was "well that makes sense, why would it know which order did I mean", so I refactored it to `ngOnChanges` and was much happier with the result.

So I really think it should be "unspecified behavior". If that's not the style of the framework (I guess there's good reasons to minimize undefined/unspecified behaviors in general, but I digress), maybe the best way to define the order of setting the values would be the order of inputs as they are defined in the class. It's kind of clunky though, since generally the order of stuff in a class shouldn't matter, and developers generally already have a mindset that it does _not_ matter (just like the order of keys in the object doesn't matter).

If it's alphabetic, I have a feeling I'm going to write "a_Zippy" instead of "zippy" just to get it to be "first" in those rare times when I'd need a specific order. I'd rather place "zippy" at the top with a comment "// must be first (the order of inputs defines the order of setting them)" than mangle with its name. The alphabetic order is further complicated by the fact that inputs can be renamed. Also, let's not forget about `@Component.inputs: string[]`. They should probably all go either before or after all inputs defined via `@Input`. There's a weird case though: what happens when you do `@Component.inputs: ['a', 'b']`, but then also do `@Input() b; @Input() a;`? (Can you even do this?)

To be honest, I wish it were possible to statically analyze the code and just throw an error if the order _would_ matter in at least one possible case. [But alas...](https://en.wikipedia.org/wiki/Halting_problem) :smile:

**Comment by petebacondarwin** [comment] 2020-12-07 22:06
The discussions in the team do indeed lean toward this being "working as expected", that the order in which attributes are processed is not public API and that one should not rely upon them being executed in any particular order.

As it turns out, right now, it appears that in ivy, the order is the order in which they appear in the template. This kind of makes sense, but also means that two different uses of the same component could lead to different behaviour, which is potentially confusing.

The only reason to go with alphabetic would be so that the ordering was at least consistent between different usages of a component, but as @lazarljubenovic points out this would result in developers using weird names to accommodate their ordering requirements. Much better is to avoid relying upon the ordering at all as he also suggests, which in many ways is also inline with the "Angular way".

**Comment by mlc-mlapis** [comment] 2020-12-08 02:38
> just like the order of keys in the object doesn't matter

What is interesting is that there was a spec change of e.g. Object.keys from ES5 to ES6. The ES6 spec defines that Object.keys also relies on ownPropertyKeys which makes it predictable in today's browsers.

**Comment by alxhub** [comment] 2020-12-10 18:26
> It seems that in ViewEngine (i.e. Angular v8) the inputs were evaluated in alphabetic order.

This isn't actually the case. I think there's an issue with your stackblitz examples. The `a` setter is defined as:

```typescript
  @Input() set a(v) {
    this.text = `A: ${this.a}; B: ${v}`;
  }
```

`this.text` includes two values here, _both_ of which are values for `a` (unlike what the `B: ` label implies). Really it's showing the value before and after the binding is evaluated, which will predictably be `undefined` and then the singular incoming value.

In actuality, in View Engine bindings were set _in the order of `@Input` field declaration_ in the directive/component being consumed. This wasn't a chosen or specified behavior, merely an implementation detail of how the inputs were captured when iterating members of the directive class.

Despite being rather arbitrary, this ordering _does_ intuitively make a certain amount of sense. It's stable and well-defined, and doesn't vary from consumer to consumer. If one input's setter consumes the value of another input, developers tend to naturally write the declaration for the dependency first, and then its consumer. A lot of the time then, this approach just "worked".

The Ivy design initially leaned towards following the ordering at the template usage site instead. This was favored for two reasons:

1. Ivy's locality principle meant that knowledge of the _declaration_ ordering of bindings wasn't available, meaning that VE's behavior could not be emulated.
2. Another general principle was to treat the template as code, and evaluate it start-to-finish exactly as the user wrote it. A major goal was to have source mapping of templates good enough such that one could step through the HTML in a debugger, and it's much more natural to jump through bindings in the left-to-right order that they're written.

In practice, this constraint proved overly restrictive. We realized it would limit our ability to optimize templates down the road, and decided that like View Engine, Ivy would not commit to a particular import binding order. I believe the decision at the time was:

* From element to element in the template, bindings will always be evaluated in template order. That is, when the template says:

```html
<foo [a]="..."></foo>
<bar [b]="..."></bar>`
```

The `[a]` binding will _always_ be evaluated/set before the `[b]` binding.

* Within an element, the order is unspecified. The template compiler is free to reorder bindings as it sees fit. For example, in the template:

```html
<foo [a]="..." b="..." [c]="..."></foo>
```

The template compiler may evaluate both `[a]` and `[c]` before `b`, in order to chain the binding instructions and generate a smaller template:

```typescript
property('a', ...)('c', ...);
attribute('b', ...);
```

**Comment by alxhub** [comment] 2021-04-14 17:16
I'm going to close this issue as Angular is working as intended here - input order is unreliable and `ngOnChanges` should be used if a directive has a specific need to react to multiple inputs being set in a particular order.

**Closed by alxhub** 2021-04-14 17:16 UTC
Labels: P3, comp: compiler, comp: core, core: inputs / outputs, regression
