### ISSUE TITLE
Angular's input validation should align with HTML5 validation! (Currently it does not!)

### ISSUE THREAD

**Issue by tx8821** [angular/angular#16352] opened 2017-04-26 16:22 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[x] feature request
[ ] support request
```

**Current behavior**

Suppose we have such an input:
`<input #nativeControl #ngControl="ngModel" type="number" min="30">`

Now if we enter 25 in that box, the `ngControl.valid` property will be `true`, while `nativeControl.validity.valid` will be `false` and `nativeControl.validity.rangeUnderflow` will be `true`.

Moreover, if we enter invalid characters (e.g. only dashes) in such a field, `ngControl.valid` property will be `true`. At the same time, `nativeControl.validity.valid` will be false and `nativeControl.validity.badInput` will be true;

Another example: `<input type="email">` is not validated by Angular (i.e. is always valid), while HTML5 validation correctly sets `ValidityState.typeMismatch` to `true` (and `ValidityState.valid` to `false`) if invalid email address is entered.

Currently I'm testing this with chrome but I don't think there will be any differences with other browsers. They all implement HTML5 validation pretty much without any issues.

**Expected behavior**

I think HTML5 standard already implements validation mechanism pretty well. Please view [https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/HTML5/Constraint_validation](url) and [https://developer.mozilla.org/en-US/docs/Web/API/ValidityState](url) for example. I think Angular should either emulate, or even directly depend on that mechanism (ValidityState values defined by HTML5).

Yes I know one can implement custom validator in angular and basically emulate anything, but... I think I'd rather have `<input type="email">` validation out of the box, rather than to reinvent the wheel and write new validator just for email checking.

**[EDIT] Minimal reproduction of the problem with instructions**
Please view an example: http://plnkr.co/edit/5pzh5pV2ExF3vKGhgEtq?p=info

Just enter number in first input, or email in second input, and you will see that Angular's validator does not respect `min` attribute (of `<input type="number">`) and also `<input type="email">` inputs.

* **Angular version:** 4.0.X

* **Browser:** [all]

 
* **Language:** [TypeScript 2.X]

**Comment by zoechi** [comment] 2017-04-26 17:04
Please provide a Plunker that demonstrates the issue.

**Comment by devoto13** [comment] 2017-04-26 17:39
Note that Angular does have [email validator](https://github.com/angular/angular/blob/master/packages/forms/src/validators.ts#L82).

**Comment by buu700** [comment] 2017-04-27 00:15
The answer I got on #15531 might possibly fix your problem.

**Comment by tx8821** [comment] 2017-04-27 08:35
@zoechi Please view the Plunker at: http://plnkr.co/edit/5pzh5pV2ExF3vKGhgEtq?p=info
@buu700 Unfortunately it is not relevant in this case.

**Comment by SilvioAmaral** [comment] 2017-11-17 21:23
I found out that the template driven forms were not working out-of-the-box for min and max, but were working perfectly for reactive driven forms. 

Example for reactive driven:
https://stackblitz.com/edit/angular-form-reactive-min-max

Template driven:
https://stackblitz.com/edit/angular-template-min-max-not-there

To my surprise, the min and max validators were created, but the directives weren't.
https://github.com/angular/angular/blob/5.0.1/packages/forms/src/validators.ts#L46-L195
https://github.com/angular/angular/blob/5.0.2/packages/forms/src/directives/validators.ts#L242-L278

I added two directives to my project to fill in this gap, they were based on this project :
https://github.com/czeckd/angular-minmax-validators (thanks )

I can create a PR to angular if there is interest, but I wanted to ask first if this is something intentional or not.

best regards

**Comment by Karasuni** [comment] 2018-02-14 10:09
@SilvioAmaral Please create the PR as this feature will otherwise stay in the backlog for a while

**Comment by SilvioAmaral** [comment] 2018-02-16 22:02
working on it

**Comment by SilvioAmaral** [comment] 2018-02-17 18:01
hey @Karasuni , I tried to push my commit to my branch and it was denied. Since I just signed the contributor agreement, i'm thinking this is the cause. Do I have to talk to anyone about it or just wait ? Sorry, first time contributing.

**Comment by devoto13** [comment] 2018-02-17 18:05
@SilvioAmaral Make sure to read about [forks](https://help.github.com/articles/about-forks/). You should create one, than push your branch to your forked repo and than create a PR following [this guide](https://help.github.com/articles/creating-a-pull-request-from-a-fork/).

**Comment by trotyl** [comment] 2018-02-17 18:15
The fact is that `min/max` validator directives has been reverted, so if Angular team wants it back, just a "Revert: Revert: " would be fine, no need for separate commits (and also it won't help).

This is not something about workload.

**Comment by SilvioAmaral** [comment] 2018-02-17 20:16
@trotyl got it. not going to push it then. But why would you say it won't help ?

**Comment by westonpace** [comment] 2018-05-02 16:03
I tried to address min/max validation separately (following @trotyl 's comment) but that issue was closed as a duplicate.  If that means we want to stick with this approach and use the existing `min`/`max` attributes then it seems there are some approaches that don't need to create a breaking change.

For example, an additional module could be created (`HtmlValidationModule` or something) which adds the directives.  Existing code would not be affected but anyone that wanted to use `min`/`max` could easily add support for it.

Alternatively, `min` and `max` directives could be added by default with a flag to turn them off.  This would be a breaking change but anyone significantly affected could easily fall back to the default behavior.

**Comment by thw0rted** [comment] 2018-11-13 12:29
I've tried reading over #17491 and I'm still not sure what the actual resolution of this problem is supposed to be.  If I have an `<input type="number" min="0" [(ngModel)]="val" #num="NgModel">`, I should be able to assume that `num.valid` will be `false` when the input's value is `-10`.  That's just a really basic and logical assumption that developers *will* make, and to do otherwise, *out of the box*, without requiring an extra "workaround" directive, etc, is a disservice to them.

Does anybody here disagree?  Is there a path forward to making this Just Work?  If not, is there a *well-publicized* documented workaround that adds only minimal burden on developers?

**Comment by mhmo91** [comment] 2019-02-15 10:00
How come this is a type of ```feature``` when it should be a ```BUG``

**Comment by mhmo91** [comment] 2019-03-07 11:32
any expectations for this one???

**Comment by joaocmfcm** [comment] 2019-04-03 13:37
This should be implemented. How come this is still not a thing in v7.0?

**Comment by dscalzi** [comment] 2019-07-25 18:51
The [Validators documentation](https://angular.io/api/forms/Validators) is deceptive and should be updated. It lists validators only available to reactive forms. No where does it mention that only a select few of the validators listed can be used on a template form.

As of Angular 8.x.x, min and max are *still* not supported in template forms.

**Comment by jkevingutierrez** [comment] 2019-08-08 19:35
Any updates on this?

**Comment by cwying817** [comment] 2019-08-14 08:57
Any update pleaseeeeeeeeeeeeeeeee

**Comment by thw0rted** [comment] 2019-09-14 08:33
#26787 was locked by the bot, let's not allow that to happen here.  Still current, still relevant.

**Comment by alex7egli** [comment] 2019-10-01 20:05
Any updates?  Would really like email validation to be supported.

**Comment by adam-marshall** [comment] 2019-11-11 11:49
Expected 'min' to work for input type="number". 

At the very least there should be a documentation update in the meantime, as @dscalzi mentioned, it is deceptive. If there is time to close duplicate issues on github (6 so far) surely there is time to update docs?

**Comment by settergren** [comment] 2019-12-03 19:19
Hard to imagine Angular still does not provide a min max directive validator out of the box. Kind of a joke, to be honest.

**Comment by enterframe** [comment] 2020-01-03 21:21
+1

**Comment by gustavshf** [comment] 2020-01-21 10:31
Still nothing in 2020. A bit ridiculous.

**Comment by dwilches** [comment] 2020-01-23 21:43
I can't believe this is not implemented yet for template-driven forms.
I was migrating a component from AngularJS that used ng-min/ng-max just fine, and I find that there is no equivalent in Angular.

For other people coming here: you need to use reactive forms for this case and then use [this](https://angular.io/api/forms/Validators).

**Comment by fasidOnGit** [comment] 2020-01-29 05:49
+1
Reactive forms are too much for a component that has just a single `input type=number`
IMHO, `min` and `max` validations could be supported _out-of-the-box_ in a template-driven approach.

**Comment by dariel312** [comment] 2020-04-19 19:21
1+ 

Documentation literally states that template driven forms should match the attributes with native html validation. This is real desceptive. 


> To add validation to a template-driven form, you add the same validation attributes as you would with [native HTML form validation](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/HTML5/Constraint_validation). Angular uses directives to match these attributes with validator functions in the framework.

**Comment by yinonov** [comment] 2020-05-21 04:16
This can be quite an issue when integrating web components in angular and relying on the components state driven properties/attributes.
This issue requires extra layer of supervision

**Comment by thw0rted** [comment] 2020-05-21 08:51
Just to summarize, exactly what HTML5 validations are we talking about here?  Skimming over the comments, it sounds like `min` and `max` for `type=number`, and `type=email`.  Did I miss anything?  Should the issue be renamed to specify that there are exactly three validations that don't map correctly from native to template-driven forms?

Should we @-mention anybody in particular on the Angular team for an update?  It looks like the last team activity was over 2 years ago now.

**Comment by darielbarroso** [comment] 2020-05-21 14:53
> Just to summarize, exactly what HTML5 validations are we talking about here? Skimming over the comments, it sounds like `min` and `max` for `type=number`, and `type=email`. Did I miss anything? Should the issue be renamed to specify that there are exactly three validations that don't map correctly from native to template-driven forms?


The min\max attributes do not work from a template driven perspective, I believe somewhere in the comment trail it said that the template driven attributes were working at one point but later removed. 

Regarding the `type='email'` I personally have not experienced this issue, it was probably fixed.

**Comment by mpotter-modus** [comment] 2020-05-28 14:06
Do I understand this correctly... that min/max were removed as template-forms directives because people want to use those names for their custom directives? Is that reasonable? Because then, logically, it follows that I can expect to be able to use other HTML standard names for my custom directives, like [name] or <div>.

**Comment by darielbarroso** [comment] 2020-05-28 15:29
Sounds like people want to use their own min\max directives in their components that implement ControlValueAccessor. I think that is a valid request and that template driven form directives for min\max should really only apply to input fields and not any other component. It seems as though the original implementation used the following selector:

`[min][formControlName],[min][formControl],[min][ngModel]`

@Maximaximum mentioned that this should be this selector instead:

`[formControlName],input[type=number][min][formControl],input[type=number][min][ngModel]`

I think this is the ideal solution to not interfere with custom components while still providing the default assumption that html5 validation can be used with input fields out of the box.

**Comment by mpotter-modus** [comment] 2020-05-28 17:02
That makes sense, and the solution is good. Thanks for the clarification @darielbarroso

**Comment by J5cott** [comment] 2020-11-13 03:30
I would like to be able to limit the possible values that the user can enter into my input.  It would be nice if I could do this with just <input type="number" /> on my reactive forms  but this does not seem to work in Firefox.  Firefox allows the user to enter non numeric characters.  When this happens, the ValidityState.valid is false while the FormControl.valid is true.

**Comment by AndrewKushnir** [comment] 2021-01-22 05:38
Hi, just a quick update: there is a PR #39063 (in progress), which implements min/max validators for `<input type="number">`. These validators should be available in the next major version of Angular (most likely v12).

**Comment by darielbarroso** [comment] 2021-01-22 13:29
Almost 4 years later, thank you!!

**Comment by dariel312** [comment] 2021-01-22 13:30
Almost 4 years later, thank you!!

**Closed** 2021-02-08 17:35 UTC
Labels: comp: forms, feature, freq2: medium
