### ISSUE TITLE
MatStepper - Not validating inside template

### ISSUE THREAD

**Issue by tsproesser** [angular/angular#39813] opened 2020-11-17 14:57 UTC
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/material-stepper-validation-iuoras?file=app%2Fapp.component.html

Steps to reproduce:
1. Try to navigate to the next step
2. Not all fields are highlighted
  
#### Expected Behavior

All fields - event thouse in templates - get highlighted.

#### Actual Behavior

Fields in templates are not marked as mandatory.

#### Environment

- Angular: 11
- CDK/Material: 11

**Comment by AndrewKushnir** [comment] 2020-11-23 16:47
Hi @tsproesser, thanks for reporting the issue and providing as repro. I've looked at the repro and found out that quite old version of Angular packages are used (v5). Could you please try re-creating this example using the most recent Angular version (v11.0.2 at this moment) and also simplify the demo to keep only the minimum required code to reproduce the issue (so that it's faster to investigate it)? Thank you.

**Comment by tsproesser** [comment] 2020-11-23 17:02
Hey @AndrewKushnir, sorry for that! I actually just took the first one I found and adopted it, since the behavior did not change since that (actually pretty old) version. Here is a newer one: [Angular 11](https://stackblitz.com/edit/angular-angular-material-stepper-apogp6?file=src%2Fapp%2Fapp.component.html)

**Comment by AndrewKushnir** [comment] 2020-11-23 20:51
@tsproesser thanks for re-creating the repro. I see the `core-js`-related error there, so I decided to create a new one, [here is the link](https://stackblitz.com/edit/components-issue-39813-initial?file=src%2Fapp%2Fexample-component.html).

There is now a different error (see console) saying that the `formControlName` is used without parent `formGroup` directive. This problem is that the `formControlName` directive tries to retrieve its parent using the DI ([see here](https://github.com/angular/angular/blob/master/packages/forms/src/directives/reactive_directives/form_control_name.ts#L130)) and DI tree is setup based on the directive declaration location (i.e. where it's present in a template), not insertion (i.e. where it's inserted dynamically at runtime). In your example, the `formControlName` is set on the input that is inside the `<ng-template>`, which is outside of an element that has the `formGroup` directive on it.

The solution is to move the corresponding `<ng-template>` block inside the `<form>` element, so the parent-child connection can be established, [see example here](https://stackblitz.com/edit/components-issue-39813-updated?file=src%2Fapp%2Fexample-component.html). This behavior is similar to issue #13761, so you may find additional information there.

I will close this ticket in favor of #13761, which has the same root cause.

Thank you.

**Closed by AndrewKushnir** 2020-11-23 20:51 UTC
Labels: comp: forms, needs reproduction

**Comment by tsproesser** [comment] 2020-11-23 22:20
Thank you so much for your effort!
