### ISSUE TITLE
docs: clarify internal change detector states

### ISSUE THREAD

**Issue by petebacondarwin** [angular/angular#40761] opened 2021-02-09 12:23 UTC
Go through the docs and change where the "internal change detection status" (e.g. `CheckAlways`) is mentioned so that it looks less like an API item that could be clicked on. And perhaps update the glossary section (https://angular.io/guide/glossary#change-detection) to explain that these are internal states of the change detector.

See https://github.com/angular/angular/pull/40436

**Comment by cesperian** [comment] 2021-03-04 04:59
@petebacondarwin can you assign this to me, please?...

**Comment by cesperian** [comment] 2021-03-17 07:26
@petebacondarwin nearly all the instances of this that I can see are just wrapped in backtics.

Is it enough to just remove that code markup or did you want them indicated in a different way?...

**Comment by petebacondarwin** [comment] 2021-03-17 07:52
Ideally wherever these occur we should re-word the text so that the internal state is not mentioned and instead a description of how the internal state works is provided.  For example in https://angular.io/guide/pipes#caching-http-requests

> Impure pipes are called whenever change detection runs for a component, which could be every few milliseconds for `CheckAlways`. 

What we are trying to get across is that unless you are using the `ChangeDetectionStrategy.OnPush` strategy, there is a good chance that these impure pipes are being executed after every action in the application.

**Comment by cesperian** [comment] 2021-03-18 03:28
@petebacondarwin Ok thanks, I get the intention. It seems like a delicate balancing act to refer to the CD strategy without explicitly naming it. 

So in this case a proper rewording would be '...for a component, which by default is every few milliseconds'?

**Comment by petebacondarwin** [comment] 2021-03-18 07:44
> It seems like a delicate balancing act to refer to the CD strategy without explicitly naming it.

Yeah, this is why no one has actually made these changes yet.

In this case, I think keeping the word "could" in there is helpful. Perhaps something like?

```
which could be every few milliseconds with the default `ChangeDetectionStrategy`.
```

**Comment by cesperian** [comment] 2021-03-19 14:51
How about; 'which could be every few milliseconds with the default `ChangeDetectionStrategy` **setting**?

Not trying to beat a dead horse, here. Just want to be sure of what should be done since there are so many instances of this in the docs..

**Comment by aikidave** [comment] 2021-05-25 21:58
Closing as duplicate of #29751

**Closed by aikidave** 2021-05-25 21:58 UTC
Labels: P4, comp: docs, docsarea: terminology
