### ISSUE TITLE
Angular 2 Socket io and Safari

### ISSUE THREAD

**Issue by goriunov** [angular/angular#12031] opened 2016-10-02 08:44 UTC
**I'm submitting a ...**  (check one with "x")

```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Angular 2 does not work  , i am pushing new information in array which displays with ngFor on request with Scoket io. And it is not appear until i do some actions with that array.

you can check it on my test website http://rps-game.azurewebsites.net/

just open with 2 different tabs and press invite some second tab.
**Expected behavior**
Appeared array with appropriate information.

**Minimal reproduction of the problem with instructions**
this is example of my code ( i check console and in console everything appeared but not in html)

this.sockets.on('called on duel' , (opponent) =>{
      console.log('got duel');
      let caller : UserInformation = new UserInformation( opponent.name , opponent.id );
      this.allCallsOnDuel.push(caller); // (should display this new push)
    });

**What is the motivation / use case for changing the behavior?**
Safari?

**Please tell us about your environment:**
Angular 2 Socket io and Safari Node JS WebStorm
- **Angular version:** 2.0.X
  Using last version of angular cli (beta.16)
- **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
  safari 9.1.3 (11601.7.8);
- **Language:** [all | TypeScript X.X | ES6/7 | ES5]
  Typescript
- **Node (for AoT issues):** `node --version` =   node 6.5

**Comment by DzmitryShylovich** [comment] 2016-10-02 09:00
try `this.allCallsOnDuel = [...this.allCallsOnDuel, caller];`

**Comment by goriunov** [comment] 2016-10-02 09:15
Does not work too

**Comment by goriunov** [comment] 2016-10-02 09:17
And it is not just that part of code . It was just sample . In fact half of my application does not work well in safari.

**Comment by DzmitryShylovich** [comment] 2016-10-02 09:20
I don't think it's actionable without reproduction.

**Comment by vicb** [comment] 2016-10-02 14:32
Please add a minimal repro - ie only code strictly required to reproduce the issue

**Comment by goriunov** [comment] 2016-10-02 19:41
I found one solution , i can force re render page with 
 constructor( private zone:NgZone){}
  this.zone.run(()=>console.log('Done'));

when i need it , however i am not sure that it is right way to do so . any way i will make minimal git repo with error.

**Comment by goriunov** [comment] 2016-10-03 01:46
I added min repo on this page:  https://github.com/goriunov/angular-2-bug-repo

**Comment by woppa684** [comment] 2016-10-03 06:03
Does it work in Internet Explorer? There are also a few bugs about websockets not working in IE, see also https://github.com/angular/angular/issues/10350 and https://github.com/angular/zone.js/issues/468

**Comment by DzmitryShylovich** [comment] 2017-02-03 08:06
@goriunov is this still an issue?

Anyway it sounds more like zonejs issue rather angular

**Comment by DzmitryShylovich** [comment] 2017-03-10 12:09
@pkozlowski-opensource no feedback. can be closed

**Comment by JoostK** [comment] 2021-05-14 15:24
Closing as obsolete. The socket.io activity is likely triggered outside of the NgZone so Angular won't be aware of any updates. This may have worked on Chrome because of extensions.

**Closed by JoostK** 2021-05-14 15:24 UTC
Labels: P3, comp: zones, freq2: medium, type: bug/fix
