### ISSUE TITLE
Tree-Shaking not working for unused but imported Standalone Components 

### ISSUE THREAD

**Issue by rothsandro** [angular/angular#46373] opened 2022-06-15 11:30 UTC
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

Standalone Components that are imported in an NgModule but not used in any template (and not referenced somewhere else) are still part of the production bundle. 

Angular should tree-shaking them away if they are not used, this works for non-standalone components.

See the build output, search for "standalone-component works!" (I committed that on purpose): https://github.com/rothsandro/repro-angular-standalone-tree-shaking/blob/main/dist/repro-angular-standalone-tree-shaking/main.7253bd360e2bf95d.js 

### Please provide a link to a minimal reproduction of the bug

https://github.com/rothsandro/repro-angular-standalone-tree-shaking

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 14.0.2
Node: 16.13.0
Package Manager: npm 8.1.0 
OS: darwin arm64

Angular: 14.0.1
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1400.2
@angular-devkit/build-angular   14.0.2
@angular-devkit/core            14.0.2
@angular-devkit/schematics      14.0.2
@angular/cli                    14.0.2
@schematics/angular             14.0.2
rxjs                            7.5.5
typescript                      4.7.3
```

**Comment by alxhub** [comment] 2022-06-16 23:21
Closing as this is working as intended - DI prevents us from being able to tree-shake standalone components like this (although there are some opportunities for optimization that we're working on).

**Closed by alxhub** 2022-06-16 23:21 UTC
Labels: comp: core, cross-cutting: standalone
