### ISSUE TITLE
doc: QuickStart the new copy code doesn't work properly

### ISSUE THREAD

**Issue by fwd079** [angular/angular#17721] opened 2017-06-23 06:43 UTC
## I'm submitting a ...

<pre><code>
[*] Regression (behavior that used to work and stopped working in a new release)
[ ] Bug report 
[ ] Feature request
[*] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
The documentation copy-code doesn't work properly, copies everything in one single line !

## Expected behavior

Should keep line breaks while copying code. Currently I am having to click-and-drag and copying code.

## Minimal reproduction of the problem with instructions
Please go [here](https://angular.io/tutorial/toh-pt6) and click the copy icon on any code and paste elsewhere.

## What is the motivation / use case for changing the behavior?
It should work?

## Please tell us about your environment

<pre><code>
Angular version: N/A

Browser:
- [*] Chrome (desktop) Version 59.0.3071.109 (Official Build) (64-bit)
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: N/A
- Platform: Ubuntu 16.04.2

Others: N/A
</code></pre>

**Comment by Toxicable** [comment] 2017-06-23 06:53
Works fine for me.
Went to this link: https://angular.io/tutorial/toh-pt6#heroes-and-http
Clicked on copy as image shows
![image](https://user-images.githubusercontent.com/13490925/27469754-249af2e0-5845-11e7-9cf9-3212125334ad.png)
and pasted here like so
![image](https://user-images.githubusercontent.com/13490925/27469732-137d3220-5845-11e7-8342-6b89ffbcd534.png)

**Comment by fwd079** [comment] 2017-06-23 12:01
Try [https://angular.io/tutorial/toh-pt6#simulate-the-web-api](https://angular.io/tutorial/toh-pt6#simulate-the-web-api) to see the problem.

**Comment by gkalpak** [comment] 2017-06-23 12:50
It only happens on code samples with linenumber. This is a duplicate of #17659.

**Closed by gkalpak** 2017-06-23 12:50 UTC

**Comment by fwd079** [comment] 2017-06-23 13:08
Okay, I will put a notification alter for the other issue you linked, thanks.
