### ISSUE TITLE
New Added heroes does not work as expected.

### ISSUE THREAD

**Issue by niranjansosvns** [angular/angular#23945] opened 2018-05-16 18:36 UTC
## I'm submitting a bug.

[ ] Bug report  

## Description of Bug : # when you list all the heroes on the heroes URL, first its shows all the listed heroes and once you have deleted all the heroes post that the  newly added heroes does not reflect in the same manner. Please find the screen shot for the reference. 

Step to Reproduce:
1) Go the live example  or "https://stackblitz.com/angular/epqxmnrnjdm".
2) Navigate to the heroes URL,
3) Delete all the heroes:
4) Enter name of new heroes , click on add button and see the bug.

![image](https://user-images.githubusercontent.com/8638774/40136491-b0755536-5965-11e8-85f8-e7e62b306db8.png)
Find the same reference on my local 
![image](https://user-images.githubusercontent.com/8638774/40137005-05b3dd28-5967-11e8-8579-6f47f2800b57.png)

https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

**Comment by brandonroberts** [comment] 2018-05-16 19:38
Duplicate of https://github.com/angular/angular/issues/22120

**Closed by brandonroberts** 2018-05-16 19:38 UTC
