### ISSUE TITLE
Allow angular 2 applications to compile in strictNullChecks mode

### ISSUE THREAD

**Issue by abierbaum** [angular/angular#11844] opened 2016-09-22 22:28 UTC
**I'm submitting a ...**  (check one with "x")

```
[X] bug report => search github for a similar issue or PR before submitting
```

**Current behavior** 

When trying to compile an ng2 application with typescript 2.0 strictNullChecks turned on the compiler runs into errors.

**Expected behavior**

Expect that ng2 would support use with strictNullChecks.

**Reproduction of the problem**

Reproduced by taking the quick start application and setting the strictNullChecks option true in tsconfig.json.  (see: https://github.com/abierbaum/quickstart)

When doing this and running `npm run tsc` the following error is shown:

```
> angular-quickstart@1.0.0 tsc /home/allenb/Source/quickstart
> tsc

node_modules/@angular/core/src/util/decorators.d.ts(11,5): error TS2411: Property 'extends' of type 'Type<any> | undefined' is not assignable to string index type 'Function | any[] | Type<any>'.
node_modules/@angular/platform-browser/src/dom/dom_renderer.d.ts(25,22): error TS2420: Class 'DomRenderer' incorrectly implements interface 'Renderer'.
  Types of property 'animate' are incompatible.
    Type '(element: any, startingStyles: AnimationStyles | undefined, keyframes: (AnimationKeyframe | undef...' is not assignable to type '(element: any, startingStyles: AnimationStyles, keyframes: AnimationKeyframe[], duration: number,...'.
      Type 'AnimationPlayer | undefined' is not assignable to type 'AnimationPlayer'.
        Type 'undefined' is not assignable to type 'AnimationPlayer'.
```

Other similar errors occur with larger projects.

**What is the motivation / use case for changing the behavior?**

strictNullChecks is a recommended best practices for new typescript code and it would be great if we could use this with ng2 applications.

**Comment by ericmartinezr** [comment] 2016-09-22 22:34
Afaik this fix https://github.com/angular/angular/pull/11294 is still pending

**Comment by rkirov** [comment] 2016-09-22 22:48
I reduced the scope of #11294 to only the change needed for the ngc emitted code to be strictNullCheck compliant, not the whole framework.

The major hold back right now is that if we want to support TS 2.0 with strictNullChecks *and* TS 1.8, we cannot use the `undefined` and `null` types. Which means the only solution left if peppering with `any`s :(

**Comment by abierbaum** [comment] 2016-09-23 13:56
@rkirov Instead of peppering with `any` could we use a type aliases to support a strict null check compliant API and a TS 1.8 API at the same time based upon some compile check?

```
// If TS 2.0
type AllowNull<T> = T | null;
type AllowUndefined<T> = T | undefined;
type AllowNullUndefined<T> = T | undefined | null;

// If TS 1.8
type AllowNull<T> = T;
type AllowUndefined<T> = T;
type AllowNullUndefined<T> = T;

function testFunc(v: AllowNull<string>) {
  //
}
```

No idea how to implement the "If" part here, but maybe someone else would have an idea.

**Comment by spicemix** [comment] 2016-09-23 19:53
Is there any defense strategy that lets us apply strictNullChecks to our code while ignoring it for our code's dependencies? Should the TypeScript people chime in here on their strategy for this transition? It's unclear to me from Microsoft/TypeScript#7140

**Comment by JohannesRudolph** [comment] 2016-09-27 09:38
@rkirov now that TS 2.0 is out, what's the point in supporting 1.8?

**Comment by vicb** [comment] 2016-09-27 14:55
> now that TS 2.0 is out, what's the point in supporting 1.8?

Because big applications can't migrate overnight and we don't want to break our users.

**Comment by JohannesRudolph** [comment] 2016-09-27 15:25
I'd consider upgrading from ts 1.8 to 2.0 a nuisance compared to upgrading
from rc to rc :-)

Am 27.09.2016 17:13 schrieb "Victor Berchet" <notifications@github.com>:

**Comment by opensrcken** [comment] 2016-09-30 17:54
Friendly bump.

**Comment by vicb** [comment] 2016-09-30 20:32
"Friendly bump." are useless - up voting the issue is the way to go (and you did it). Thanks.

**Comment by IgorMinar** [comment] 2016-10-07 23:13
We'll investigate the possibility to roll this out without breaking changes.

**Comment by CSchulz** [comment] 2016-10-11 09:24
Could there bc if you define fe the method signature more detailed?

**Comment by beerendlauwers** [comment] 2016-10-26 07:45
Any update on this?

**Comment by Ristaaf** [comment] 2016-11-11 15:10
Anyone has a workaround for this? I am interested in anything however ugly it may be, 
We have a central build that fails if there are any compilation changes, But I am open to trying anything including overwriting node_modules files in the builds. Best would be if anyone know a way to silent the ts errors from a specific folder(s)

We really want to use strictNullChecks since we are starting to get quite a lot of code from a lot of different people and the first time we turned it on we got around 600 errors, where at least half of them was potential bugs. We have fixed most of the errors, but also seen that during the time we fixed them at least 50 more was created, so we really want to be able to have this check on.

**Comment by akirasosa** [comment] 2016-11-11 15:55
How about using ```skipLibCheck```? Before I use it, I got following errors. They are all gone away now.

```
[default] /Users/akira/src/github.com/springboot-angular2-tutorial/angular2-app/node_modules/@angular/core/src/util/decorators.d.ts:11:5
    Property 'extends' of type 'Type<any> | undefined' is not assignable to string index type 'Function | any[] | Type<any>'.
[default] /Users/akira/src/github.com/springboot-angular2-tutorial/angular2-app/node_modules/@angular/forms/src/model.d.ts:375:27
    Type '{ onlySelf?: boolean | undefined; emitEvent?: boolean | undefined; emitModelToViewChange?: boolea...' has no property 'onlySelf' and no string index signature.
[default] /Users/akira/src/github.com/springboot-angular2-tutorial/angular2-app/node_modules/@angular/forms/src/model.d.ts:375:37
    Type '{ onlySelf?: boolean | undefined; emitEvent?: boolean | undefined; emitModelToViewChange?: boolea...' has no property 'emitEvent' and no string index signature.
[default] /Users/akira/src/github.com/springboot-angular2-tutorial/angular2-app/node_modules/@angular/forms/src/model.d.ts:375:48
    Type '{ onlySelf?: boolean | undefined; emitEvent?: boolean | undefined; emitModelToViewChange?: boolea...' has no property 'emitModelToViewChange' and no string index signature.
[default] /Users/akira/src/github.com/springboot-angular2-tutorial/angular2-app/node_modules/@angular/forms/src/model.d.ts:375:71
    Type '{ onlySelf?: boolean | undefined; emitEvent?: boolean | undefined; emitModelToViewChange?: boolea...' has no property 'emitViewToModelChange' and no string index signature.
[default] /Users/akira/src/github.com/springboot-angular2-tutorial/angular2-app/node_modules/@angular/forms/src/model.d.ts:422:29
    Type '{ onlySelf?: boolean | undefined; } | undefined' has no property 'onlySelf' and no string index signature.
[default] /Users/akira/src/github.com/springboot-angular2-tutorial/angular2-app/node_modules/@angular/forms/src/model.d.ts:544:9
    Type '{ onlySelf?: boolean | undefined; } | undefined' has no property 'onlySelf' and no string index signature.
[default] /Users/akira/src/github.com/springboot-angular2-tutorial/angular2-app/node_modules/@angular/forms/src/model.d.ts:570:9
    Type '{ onlySelf?: boolean | undefined; } | undefined' has no property 'onlySelf' and no string index signature.
[default] /Users/akira/src/github.com/springboot-angular2-tutorial/angular2-app/node_modules/@angular/forms/src/model.d.ts:605:25
    Type '{ onlySelf?: boolean | undefined; } | undefined' has no property 'onlySelf' and no string index signature.
[default] /Users/akira/src/github.com/springboot-angular2-tutorial/angular2-app/node_modules/@angular/forms/src/model.d.ts:708:29
    Type '{ onlySelf?: boolean | undefined; } | undefined' has no property 'onlySelf' and no string index signature.
[default] /Users/akira/src/github.com/springboot-angular2-tutorial/angular2-app/node_modules/@angular/forms/src/model.d.ts:731:31
    Type '{ onlySelf?: boolean | undefined; } | undefined' has no property 'onlySelf' and no string index signature.
[default] /Users/akira/src/github.com/springboot-angular2-tutorial/angular2-app/node_modules/@angular/forms/src/model.d.ts:765:25
    Type '{ onlySelf?: boolean | undefined; } | undefined' has no property 'onlySelf' and no string index signature.
[default] /Users/akira/src/github.com/springboot-angular2-tutorial/angular2-app/node_modules/@angular/platform-browser/src/dom/dom_renderer.d.ts:25:22
    Class 'DomRenderer' incorrectly implements interface 'Renderer'.
  Types of property 'animate' are incompatible.
    Type '(element: any, startingStyles: AnimationStyles | undefined, keyframes: (AnimationKeyframe | undef...' is not assignable to type '(element: any, startingStyles: AnimationStyles, keyframes: AnimationKeyframe[], duration: number,...'.
      Type 'AnimationPlayer | undefined' is not assignable to type 'AnimationPlayer'.
        Type 'undefined' is not assignable to type 'AnimationPlayer'.
[default] Checking finished with 13 errors
```

**Comment by CSchulz** [comment] 2016-11-11 16:05
Does not work if you overwrite methods which have no correct signature.

**Comment by Ristaaf** [comment] 2016-11-16 13:24
@akirasosa: Works perfect in our situation, thanks!

**Comment by IgorMinar** [comment] 2016-11-30 17:13
I'm adding this to our roadmap and we'll start working on implementing this
change in December/January.

On Wed, Nov 16, 2016 at 5:24 AM Rickard Staaf <notifications@github.com>
wrote:

@akirasosa <https://github.com/akirasosa>: Works perfect in our situation,
thanks!

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/angular/angular/issues/11844#issuecomment-260945307>,
or mute the thread

**Comment by alvipeo** [comment] 2016-11-30 17:21
Works for me though with:

```
    "skipDefaultLibCheck": true,
    "skipLibCheck": true,
```

**Comment by opensrcken** [comment] 2016-11-30 21:16
@alvipeo, that's not a robust fix. Looking forward to the NG2 team addressing this at the root level.

**Comment by IgorMinar** [comment] 2016-11-30 21:32
yup. but we can't without full upgrade to TypeScript 2.x. So stay tuned,
it's coming.

**Comment by imcotton** [comment] 2017-01-07 00:00
Now that Angular v2.4.2 is out with TypeScript 2.1 support, but **ngc** seems still not play well with `strictNullChecks` flag tho.

**Comment by DzmitryShylovich** [comment] 2017-01-07 00:03
> with TypeScript 2.1 support

it's only for language-service

**Comment by imcotton** [comment] 2017-01-07 00:10
Oh, but besides supporting for `strictNullChecks`, I've no trouble run through both `JIT` and `AOT` with TypeScript v2.1.4, am I missing something or that's the one exactly been left over?

**Comment by DzmitryShylovich** [comment] 2017-03-10 12:13
@abierbaum I believe this should be fixed in angular 4. can you confirm please?

**Comment by IgorMinar** [comment] 2017-03-10 17:00
yup. this should be closed. At Google everyone is using the strictNullChecks mode, but it would be good to get a confirmation that everything is working well externally as well.

**Comment by mikehaas763** [comment] 2017-03-10 19:26
A couple of days ago I upgraded our app to 4 rc2 and it seemed to build and run fine, however I was getting a couple forms warnings in the terminal from my build.

**Comment by DzmitryShylovich** [comment] 2017-03-10 19:30
>  a couple forms warnings

probably because of validators. should be fixed here https://github.com/angular/angular/pull/14679

**Comment by IgorMinar** [comment] 2017-03-14 00:32
I'll close this issue and follow up on #14679

**Closed by IgorMinar** 2017-03-14 00:32 UTC
Labels: comp: packaging, flag: breaking change, freq2: medium, severity3: broken, type: feature

**Comment by connor4312** [comment] 2017-08-14 19:24
It appears there are more issues here as of 4.3.4

```
ERROR in [at-loader] ./node_modules/@angular/core/src/change_detection/differs/default_iterable_differ.d.ts:2:22
    TS2420: Class 'DefaultIterableDifferFactory' incorrectly implements interface 'IterableDifferFactory'.
  Types of property 'create' are incompatible.
    Type '<V>(trackByFn?: TrackByFunction<V> | undefined) => DefaultIterableDiffer<V>' is not assignable to type '{ <V>(trackByFn?: TrackByFunction<V> | undefined): IterableDiffer<V>; <V>(_cdr?: ChangeDetectorRe...'.
      Type 'DefaultIterableDiffer<any>' is not assignable to type 'IterableDiffer<any>'.
        Types of property 'diff' are incompatible.
          Type '(collection: NgIterable<any>) => DefaultIterableDiffer<any> | null' is not assignable to type '(object: NgIterable<any>) => IterableChanges<any> | null'.
            Type 'DefaultIterableDiffer<any> | null' is not assignable to type 'IterableChanges<any> | null'.
              Type 'DefaultIterableDiffer<any>' is not assignable to type 'IterableChanges<any> | null'.
                Type 'DefaultIterableDiffer<any>' is not assignable to type 'IterableChanges<any>'.
                  Types of property 'forEachOperation' are incompatible.
                    Type '(fn: (item: IterableChangeRecord<any>, previousIndex: number | null, currentIndex: number | null)...' is not assignable to type '(fn: (record: IterableChangeRecord<any>, previousIndex: number, currentIndex: number) => void) =>...'.
                      Types of parameters 'fn' and 'fn' are incompatible.
                        Types of parameters 'previousIndex' and 'previousIndex' are incompatible.
                          Type 'number | null' is not assignable to type 'number'.
                            Type 'null' is not assignable to type 'number'.

ERROR in [at-loader] ./node_modules/@angular/core/src/change_detection/differs/default_iterable_differ.d.ts:10:22
    TS2420: Class 'DefaultIterableDiffer<V>' incorrectly implements interface 'IterableChanges<V>'.
  Types of property 'forEachOperation' are incompatible.
    Type '(fn: (item: IterableChangeRecord<V>, previousIndex: number | null, currentIndex: number | null) =...' is not assignable to type '(fn: (record: IterableChangeRecord<V>, previousIndex: number, currentIndex: number) => void) => v...'.
      Types of parameters 'fn' and 'fn' are incompatible.
        Types of parameters 'previousIndex' and 'previousIndex' are incompatible.
          Type 'number | null' is not assignable to type 'number'.
            Type 'null' is not assignable to type 'number'.

ERROR in [at-loader] ./node_modules/@angular/core/src/change_detection/differs/default_iterable_differ.d.ts:10:22
    TS2420: Class 'DefaultIterableDiffer<V>' incorrectly implements interface 'IterableDiffer<V>'.
  Types of property 'diff' are incompatible.
    Type '(collection: NgIterable<V>) => DefaultIterableDiffer<V> | null' is not assignable to type '(object: NgIterable<V>) => IterableChanges<V> | null'.
      Type 'DefaultIterableDiffer<V> | null' is not assignable to type 'IterableChanges<V> | null'.
        Type 'DefaultIterableDiffer<V>' is not assignable to type 'IterableChanges<V> | null'.
          Type 'DefaultIterableDiffer<V>' is not assignable to type 'IterableChanges<V>'.
            Types of property 'forEachOperation' are incompatible.
              Type '(fn: (item: IterableChangeRecord<V>, previousIndex: number | null, currentIndex: number | null) =...' is not assignable to type '(fn: (record: IterableChangeRecord<V>, previousIndex: number, currentIndex: number) => void) => v...'.
                Types of parameters 'fn' and 'fn' are incompatible.
                  Types of parameters 'previousIndex' and 'previousIndex' are incompatible.
                    Type 'number | null' is not assignable to type 'number'.
                      Type 'null' is not assignable to type 'number'.
```

**Comment by JohannesRudolph** [comment] 2017-08-15 04:31
IIRC, these issues are caused by an issue between angular and Typescript 2.4. There's another issue logged for that (just look for DefaultIterableDiffer in the issue search). 

You can try downgrading to TS 2.3.4 until this is fixed in angular.

**Comment by kirillgroshkov** [comment] 2017-11-27 17:06
any update on this? angular still fails in strict mode

**Comment by mikehaas763** [comment] 2017-11-27 17:14
@kirillgroshkov yes, you may be on an older version. Don’t quote me but I believe this was fixed in v4

**Comment by mikehaas763** [comment] 2017-11-27 17:15
@kirillgroshkov also, your version of Typescript may be too new. The strict flag—although good IMO—is a moving target as new versions of TS are released
