### ISSUE TITLE
lazy module loading call module constructor twice

### ISSUE THREAD

**Issue by bolota** [angular/angular#13489] opened 2016-12-15 08:53 UTC
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When using lazy module loading the module constructor it s initialized twice

**Expected behavior**

i need normal constructor behavior

**Minimal reproduction of the problem with instructions**
Here is the exemple with DashboardModule constructor called twice

https://plnkr.co/edit/Ag6BPxwKuW3iBWDOMTBV?p=preview

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Linux mint, Webstorm

* **Angular version:** 2.3.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by antonybudianto7** [comment] 2016-12-15 10:20
Duplicate of #12869

**Comment by DzmitryShylovich** [comment] 2016-12-15 10:56
Indeed.
@bolota close this one pls. thx

**Closed** 2016-12-15 11:51 UTC
