### ISSUE TITLE
SwUpdate Methods lead to degraded Mode when service worker is stopped

### ISSUE THREAD

**Issue by alexion4** [angular/angular#32095] opened 2019-08-10 17:33 UTC
### Affected Package
The issue is caused by package @angular/service-worker

### Is this a regression?
Probably not

### Description
When SwUpdate::checkForUpdate() or SwUpdate::activateUpdate() is called while the service worker is stopped, the service worker enters a degraded state.

The likely cause is that the Driver is not initialized is this case. (Driver::initialize() is never called)

## 🔬 Minimal Reproduction
Reproduction is possible with the example code from the angular docs:
https://angular.io/guide/service-worker-communications

Just make sure that the service worker is stopped (by the browser after some idle time or manually with chrome dev tools) before the methods are called

## 🔥 Exception or Error
For checkForUpdates() this is the ngsw/state after the call:
<pre><code>
NGSW Debug Info:

Driver state: EXISTING_CLIENTS_ONLY (Degraded due to failed initialization: Cannot read property 'previouslyCachedResources' of undefined
TypeError: Cannot read property 'previouslyCachedResources' of undefined
    at Driver.<anonymous> (https://example.com/ngsw-worker.js:2624:32)
    at Generator.next (<anonymous>)
    at fulfilled (https://example.com/ngsw-worker.js:1787:62))
Latest manifest hash: none
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.2.1
Node: 10.15.2
OS: linux x64
Angular: 8.2.1
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.802.1
@angular-devkit/build-angular     0.802.1
@angular-devkit/build-optimizer   0.802.1
@angular-devkit/build-webpack     0.802.1
@angular-devkit/core              8.2.1
@angular-devkit/schematics        8.2.1
@angular/pwa                      0.802.1
@ngtools/webpack                  8.2.1
@schematics/angular               8.2.1
@schematics/update                0.802.1
rxjs                              6.5.2
typescript                        3.5.3
webpack                           4.39.1

</code></pre>

**Browser:**
Chromium 76.0.3809.87

**Comment by gkalpak** [comment] 2019-08-12 09:06
Thx for reporting this. Based on the stack trace, the error is coming from [this line][1], because `version` is undefined. I am pretty sure this happens due to `this.latestHash` being `null`, which makes this issue a duplicate of #25611. In fact, I believe the fix suggested in https://github.com/angular/angular/issues/25611#issuecomment-464756987 would also fix your issue.

Closing this as a duplicate of #25611.
@alexion4, I you feel like taking a stub at fixing this, I would be happy to help :wink: 

[1]: https://github.com/angular/angular/blob/37de490e2342b9a64bb33944d13f0e26659288bd/packages/service-worker/worker/src/driver.ts#L970

**Closed by gkalpak** 2019-08-12 09:06 UTC

**Comment by alexion4** [comment] 2019-08-12 11:50
@gkalpak, thanks, I can confirm that your suggested fix (https://github.com/angular/angular/issues/25611#issuecomment-464756987) solves my problem.
