### ISSUE TITLE
Props Data is getting Undefined in Vue.js Web Component on Mounting Phase while using it in Angular

### ISSUE THREAD

**Issue by santhanakrishnanstark** [angular/angular#53846] opened 2024-01-09 10:09 UTC
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

## Steps to reproduce

1. Visit the link that I have attached
2. You will see the index.html file where I have created Vue web component, Open console on the right side window.
3. Press Toggle button on the output screen.
4. Now, you can able to see the props data which is undefined on the mounting phase.

## What is expected?
Mounting cycle should receive the props value.

## What is actually happening?
The props are undefined in the Mounting cycle.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-bfz1d8?file=index.html

### Please provide the exception or error you saw

```true
The props are undefined in the Mounting cycle.
```

### Anything else?

I have raised this same issue in vue3 code, Seems the issue is with Angular can you please check and give some inputs.

please refer this below link for the issue I created in vue3 core for more inputs,
Issue link : https://github.com/vuejs/core/issues/9880

**Comment by eneajaho** [comment] 2024-01-09 14:29
I created a reproduction with latest Angular here https://stackblitz.com/edit/stackblitz-starters-v8ws7s?file=src%2Fmain.ts 

Looks like this is normal Angular behavior. 

```ts
function App_Conditional_8_Template(rf, ctx) {
   if (rf & 1) { // create phase
      i0.ɵɵelement(0, "my-vue-web-comp", 1);
   } 
   if (rf & 2) { // update phase
      const ctx_r0 = i0.ɵɵnextContext();
      i0.ɵɵproperty("msg", ctx_r0.name);
  } 
}
```

**Comment by eneajaho** [comment] 2024-01-09 14:30
cc @nartc this is basically what you need in angular-three

**Comment by pkozlowski-opensource** [comment] 2024-01-10 16:48
This is essentially duplicate of #45712

The way Angular deals with rendering DOM elements (including custom elements) is 2-step:
1) the instance of an element is created _and_ attached to the DOM (this is where the connected callback would be called, I presume);
2) properties of the element are set (based on bindings in a template).

This is totally fine and something that can be done with custom elements _without_ Angular. In the essence one can not expect that all properties are set when the connected callback is called. 

You might want to move your logic to the `attributeChangedCallback` and / or a property setter. 

I don't think Angular or View are at fault here - there are just multiple points of time when properties / attributes could be set and if you want to respond to changes to the properties / attributes it needs to be done in other places than the connected callback.

Duplicate of #45712

**Closed by pkozlowski-opensource** 2024-01-10 16:48 UTC
