### ISSUE TITLE
Could not resolve  type Window when building for production environment

### ISSUE THREAD

**Issue by skdhir** [angular/angular#14845] opened 2017-03-01 21:33 UTC
After upgrading Angular and CLI versions, I'm getting error only when building for production

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
- when used common ng build, it builds with no problem
- When used ng build --prod, gives an error:

**Expected behavior**
Prod build should work too

**Minimal reproduction of the problem with instructions**
app.module.ts:
import { BrowserModule }  from '@angular/platform-browser';
import {NgModule}                   from '@angular/core';
import {CommonModule}               from '@angular/common';
import {HttpModule}                 from '@angular/http';

import { AppComponent }         from './app.component';

@NgModule({
  declarations: [ AppComponent],
  imports: [ ],
  providers: [{ provide: 'Window',  useValue: window }],
  bootstrap: [AppComponent]
})
export class AppModule { }

some-class.ts:
import {Inject , Injectable} from '@angular/core';

@Injectable()
export class ServiceBase {
    private _urlPrefix = "http://";
    private _urlPostfix = ":8080/mycode/";

    constructor(
       @Inject('Window') window: Window
    ) {}

    public get servcieURL() : string {
        return this._urlPrefix + window.location.hostname + this._urlPostfix;
    }
}

- now build using ng build : works
- now build again using ng build --prod, it fails

**Please tell us about your environment:**
Node: V7.5.0
NPM: 4.1.2
Angular: 2.4.0
Angular CLI: 1.0.0-rc.0

* **Angular version:** 2.4.0

* **Browser:** [Chrome XX ]
 
* **Language:** [TypeScript 2.0.0 ]

* **Node (for AoT issues):** `node --version` =   V7.7.0

**Comment by DzmitryShylovich** [comment] 2017-03-01 21:35
Duplicate of https://github.com/angular/angular/issues/12631

**Comment by DzmitryShylovich** [comment] 2017-03-01 22:25
@skdhir close this issue please. there's no need to have 2 issues for the same bug. thanks

**Comment by skdhir** [comment] 2017-03-01 22:56
I agree, but like I couldn't find the other issue for my problem. The title of this one seems more clear and might help others who looking for answers.

**Comment by chuckjaz** [comment] 2017-03-04 00:43
Thanks for reporting this issue. However this issue is a duplicate of an existing issue #12631. Please subscribe to that issue for future updates.

**Closed by chuckjaz** 2017-03-04 00:43 UTC
