### ISSUE TITLE
There is no way to properly redirect to `404 - not found` page from resolver

### ISSUE THREAD

**Issue by th0r** [angular/angular#25229] opened 2018-07-31 16:09 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
Let's say there is a `/post/:id` route and user tries to load `/post/non-existing-id`. In this case I catch 404 http error in the route resolver and want to show a common 404 page. And I also expect the URL to be `/post/non-existing-id`.

So I've created a 404 route in the main app route config like this:
```ts
export const routes: Routes = [
  {
    path: 'post/:id',
    component: PostPageComponent
  },
  {
    path: '404',
    component: NotFoundPageComponent
  }
];
```

...and use this code in the resolver for post page:

```ts
async resolve(route: ActivatedRouteSnapshot): Promise<Post> {
    try {
      return await this.posts.get(route.params.id);
    } catch (err) {
      this.router.navigateByUrl('404', {skipLocationChange: true});
    }
  }
```

In this case I see 404 page, but the URL remains the same as it was before navigation - it doesn't change to `/post/non-existing-id`.

And of course if I remove `skipLocationChange` option, then url becomes `/404` and that's not what I want either.

**Update:** it still doesn't work properly in Angular v6.1.0 with `urlUpdateStrategy: 'eager'` router option ([details](https://github.com/angular/angular/issues/25229#issuecomment-409299728)).

## Expected behavior
404 page shown and the URL is `/post/non-existing-id`.

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-router-404-page

Click on `Link to missing post`. Url changes to `/post/non-existing-post` immediately (as expected) but when post resolver finishes and "Not found" page is shown URL changes back to the previous one. 

## Environment

<pre><code>
Angular: 6.1.0
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic, router
... upgrade
</code></pre>

**Comment by trotyl** [comment] 2018-07-31 16:25
https://github.com/angular/angular/pull/24820

**Comment by th0r** [comment] 2018-07-31 16:38
@trotyl thanks! Let me please try `6.1.0` and I'll close it if it works as expected.

**Comment by th0r** [comment] 2018-07-31 17:19
@trotyl unfortunately it doesn't work in `6.1.0` with `urlUpdateStrategy: 'eager'` either: URL changes to `/post/non-existing-id` immediately after clicking on link (that's fine) but it changes back to the previous URL after the call to `this.router.navigateByUrl('404', {skipLocationChange: true})`.

**Comment by th0r** [comment] 2018-08-01 09:09
@trotyl updated main post with reproduction.

**Comment by trotyl** [comment] 2018-08-02 09:41
The problem is, `Resolver` is not `Guard`, it cannot decide whether allowed to access, but only success or fail. Once failed, the navigation is cancelled.

You should perform the checking on [`CanActivate`](https://angular.io/api/router/CanActivate), rather than `Resolver`.

If you do want to redirect in `Resolver`, let it success and wait to next tick: https://stackblitz.com/edit/angular-router-404-page-yvzm2x?file=app/post-resolver.service.ts

**Comment by th0r** [comment] 2018-08-02 09:50
> You should perform the checking on CanActivate, rather than Resolver.

In this case I will need to make two requests for a post - first one in the Guard to check it's existence and the second in Resolver to actually request a post. And even in this case, if I'm not mistaken, I won't be able to get what I want - `/post/non-existing-post` in the URL and 404 page shown.

> If you do want to redirect in Resolver, let it success and wait to next tick:

```
return {title: 'Failed'}
```

Don't you think it's an ugly hack? It will require adding additional logic to all the page components to handle "empty data" cases.

**Comment by trotyl** [comment] 2018-08-02 10:03
If it's only about the existence resource, then it's the responsibility of target component to decide whether it should redirect, a resolver is only meant to provide unified data.

**Comment by th0r** [comment] 2018-08-02 10:09
So you're telling Angular doesn't provide an easy way to mimic 404 behavior of any known server framework - show requested URL and a common root-level 404 page?

**Comment by th0r** [comment] 2018-08-02 10:10
> a resolver is only meant to provide unified data

But what if there is no data?

**Comment by trotyl** [comment] 2018-08-02 11:07
> So you're telling Angular doesn't provide an easy way to mimic 404 behavior of any known server framework - show requested URL and a common root-level 404 page?

So please kindly tell me, in which known server framework you did redirect in a resolver?

Resolver is not controller at all, but component is.

**Comment by th0r** [comment] 2018-08-02 11:16
> So please kindly tell me, in which known server framework you did redirect in a resolver?

There is no such thing as resolvers in any server frameworks I know.

> Resolver is not controller at all, but component is.

In Rails controller, for example, you have a choice whether to render a template or not depending on the data you get. In Angular you don't have such an option - if you return `null` from post resolver and call `this.router.navigateByUrl('404', {skipLocationChange: true})` from `ngOnInit` if `post` input is `null` then you'll have to wrap component's template with `*ngIf="post"` because in other case there will be a rendering exception when you'll try to access any of it's properties. Or use `post?.prop` everywhere which is even worse.

**Comment by trotyl** [comment] 2018-08-02 11:45
Agreed, sounds likes a legit bug of `skipLocationChange` itself, not related to `urlUpdateStrategy`.

**Comment by CDDelta** [comment] 2018-08-11 11:38
I too am facing this issue.

Interestingly, the docs for `urlUpdateStrategy` is written with this exactly in mind.
> The most common use case would be updating the URL early so if navigation fails, you can show an error message with the URL that failed.
Hope to see this fixed soon, it is quite crucial for good UX.

**Comment by trotyl** [comment] 2018-08-21 02:02
Technically duplicate of https://github.com/angular/angular/issues/17004.

**Comment by IgorMinar** [comment] 2018-08-21 18:37
Thanks for reporting this issue. However this issue is a duplicate of an existing issue #17004. Please subscribe to that issue for future updates.

**Closed by IgorMinar** 2018-08-21 18:37 UTC
Labels: comp: router
