### ISSUE TITLE
lost dociment

### ISSUE THREAD

**Issue by sayanastha** [angular/angular#31317] opened 2019-06-27 18:12 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...

## 🔬 Minimal Reproduction

 https://stackblitz.com/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by AndrewKushnir** [comment] 2019-06-27 22:25
@sayanastha I'm closing this issue, since it doesn't contain enough information to understand what the problem is. Please create a new issue with the necessary info, so we can understand the problem. Thank you.

**Closed by AndrewKushnir** 2019-06-27 22:25 UTC
