### ISSUE TITLE
 loadChildren is not working with angle 7.0.0

### ISSUE THREAD

**Issue by GlauberF** [angular/angular#26701] opened 2018-10-23 20:36 UTC
### Angular CLI: 7.0.1

I'm trying to use loadChildren, to work with Lazy Loading, but it does not work, it can not find the module

### module
![captura de tela de 2018-10-23 17-42-44](https://user-images.githubusercontent.com/11314585/47388682-3170cc00-d6e9-11e8-9abd-e5039c392cbd.png)

### dashboard routing
![captura de tela de 2018-10-23 17-43-32](https://user-images.githubusercontent.com/11314585/47388751-5c5b2000-d6e9-11e8-80b4-20560f2b2ceb.png)

### app routing
![captura de tela de 2018-10-23 17-45-00](https://user-images.githubusercontent.com/11314585/47388792-801e6600-d6e9-11e8-91ef-583a9450a4e5.png)

### tsconfig
![captura de tela de 2018-10-23 17-45-37](https://user-images.githubusercontent.com/11314585/47388829-95939000-d6e9-11e8-9414-a46a5796a172.png)

I have tried in two ways already:

```loadChildren: 'app / dashboard / dashboard.module # DashboardModule'```

```loadChildren: 'dashboard / dashboard.module # DashboardModule'```

### error in console
![captura de tela de 2018-10-23 17-47-53](https://user-images.githubusercontent.com/11314585/47388980-ec996500-d6e9-11e8-8f0e-a8e1b685e014.png)

## error accessing the route
![captura de tela de 2018-10-23 17-49-20](https://user-images.githubusercontent.com/11314585/47389054-19e61300-d6ea-11e8-8e1b-53cc344e96ef.png)

**Comment by sarunint** [comment] 2018-10-23 20:54
Use relative path

**Comment by GlauberF** [comment] 2018-10-23 21:01
@sarunint I already tried too ```./dashboard/dashboard.module#DashboardModule
![captura de tela de 2018-10-23 18-14-18](https://user-images.githubusercontent.com/11314585/47390368-99291600-d6ed-11e8-88e2-c116db92ec40.png)




would it have any other way?

**Comment by 100cm** [comment] 2018-10-24 03:34
@GlauberF  you should better provide  full project struct.

**Comment by alan-agius4** [comment] 2018-10-24 06:39
Duplicate of https://github.com/angular/angular-cli/issues/12722

**Comment by jeanpaulattard** [comment] 2018-10-26 08:38
As @sarunint mentioned, use relative routing. In my app.routing module, i have the following 

```{ path: 'login', loadChildren: './+login/login.module#LoginModule' },```

and it is working perfectly fine.

Can you provide a working plunkr to replicate your issue?

**Comment by jasonaden** [comment] 2018-11-27 23:32
Closing as duplicate of CLI issue referenced above.

**Closed by jasonaden** 2018-11-27 23:32 UTC
Labels: comp: router
