### ISSUE TITLE
Behavior of FormControl's constructor, patchValue method, and undefined

### ISSUE THREAD

**Issue by Senneseph** [angular/angular#29915] opened 2019-04-15 21:16 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/forms

### Is this a regression?

 Don't know.

### Description

 When a FormControl is created via its constructor with a value of _undefined_, it is silently changed to _null_.  When a FormControl has its value changed to _undefined_ via the patchValue() method, it takes the value _undefined_.

## 🔬 Minimal Reproduction

 https://stackblitz.com/edit/angular-sacg5j

## 🌍  Your Environment

**Angular Version:**
<pre><code>Angular CLI: 7.3.5
Node: 8.11.2
OS: linux x64
Angular: 7.2.12
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.6
@angular-devkit/build-angular     0.13.6
@angular-devkit/build-optimizer   0.13.6
@angular-devkit/build-webpack     0.13.6
@angular-devkit/core              7.3.6
@angular-devkit/schematics        7.3.5 (cli-only)
@ngtools/webpack                  7.3.6
@schematics/angular               7.3.5 (cli-only)
@schematics/update                0.13.5 (cli-only)
rxjs                              6.4.0
typescript                        3.2.4
webpack                           4.29.0</code></pre>

**Anything else relevant?**

I understand that the constructor defaults the value to _null_ if an argument isn't passed, but in this case, an argument is being passed, it's just _undefined_.

The use case I have here is, if there is a FormControl whose value is initially _undefined_, I don't want that entry to show up when I call FromGroup.value.  Essentially, unless the <input> is edited in some way, I don't want it to exist.

At the very least, the constructor and updating methods (patchValue, setValue) should behave in a similar way.  For now, I am creating a FormControl and then immediately calling patchValue on it.

Is there some other way of passing in _undefined_ that I've missed?

**Comment by felixroos** [comment] 2019-05-27 09:43
I just hit the same problem here. The FormControl constructor seems horribly inconsistent
as you can see in [this stackblitz](https://stackblitz.com/edit/angular-formcontrol-bug?file=src/app/app.component.ts), i tested the behaviour using three ways of construction:

```ts
const group = new FormGroup({
  a: new FormControl(undefined),
  b: new FormControl({ value: undefined }),
  c: new FormControl({ value: undefined, disabled: false })
});
console.log(group.value);
```

The normal expectation would be to get:

```ts
{
a: undefined,
b: undefined,
c: undefined
}
```

but instead, this is returned:

```ts
{
a: null, // gets silently changed from undefined to null
b: { value: undefined }, // is interpreted as value, when disabled is not set
c: undefined // is interpreted correctly
}
```

imho this is unintuitive and inconsistent. it caused my form components to fail JSON schema validation for no obvious reasons. Some syntactic sugar turns out to be very bitter :-/

**Comment by AndrewKushnir** [comment] 2020-05-28 04:08
Hi @Senneseph, thanks for reporting the issue. This ticket looks like a duplicate of #36946, so I'm closing this one. Please subscribe to #36946 for further discussion/updates. Thank you.

**Closed** 2020-05-28 04:08 UTC
Labels: comp: forms, freq2: medium, severity1: confusing, type: bug/fix
