### ISSUE TITLE
Provide a way for zonejs to not patch MutationObserver

### ISSUE THREAD

**Issue by mjyocca** [angular/angular#36460] opened 2020-04-06 20:40 UTC
# 🐞 bug report

### Affected Package

The issue is caused by package @angular/zone.js

### Description

Our application runs Angular and Salesforce's Lightning Web Components in the same document. A component in their library depends on the `MutationObserver` to be the native implementation. Zone.js patches the MutationObserver unless we set flag, `__Zone_disable_EventTarget = true`. However we do not wish to set that flag. 

Only work around that we found is to re-assign the Native Code implementation for MutationObserver found by `window[Zone.__symbol__("MutationObserver")]` before we load the component. 

Wish for guidance or a solution to set zone.js to not patch the MutationObserver.

**Comment by splincode** [comment] 2020-04-07 08:29
@JiaLiPassion Hmm, when I pass `__Zone_disable_EventTarget = true` for experiment 

I have failed in my app


![image](https://user-images.githubusercontent.com/12021443/78647223-ef2e5100-78c2-11ea-87f0-7238aff865c0.png)

**Comment by JiaLiPassion** [comment] 2020-04-07 13:18
@mjyocca , there is a PR for this purpose https://github.com/angular/angular/pull/31657, since it is a breaking change, I will work on it for the next major version, your current walk around (re-assign the native MutationObserver is totally fine).

@splincode , could you give me a reproduce repo?

**Comment by mjyocca** [comment] 2020-04-07 15:52
@JiaLiPassion, If we go w/ re-assigning the MutationObserver manually, are there any angular features we should not use or be aware of?

**Comment by twohappy** [comment] 2020-04-09 10:20
good to hear that

**Comment by JiaLiPassion** [comment] 2020-04-09 10:31
@mjyocca, if you reassign the MutationObserver, the callbacks of MutationObserver will not in the `ngZone`, so if some data changed in the callbacks, it will not trigger change detection and reflected in the view, beside that, there are no other impacts.

**Comment by atscott** [comment] 2022-06-13 23:31
It looks like this was resolved by https://github.com/angular/angular/pull/38473 and released in v0.11.0 of ZoneJS.

**Closed by atscott** 2022-06-13 23:31 UTC
Labels: feature, comp: zones, insufficient votes, votes required
