### ISSUE TITLE
Route Parameters are lost on reload

### ISSUE THREAD

**Issue by rightisleft** [angular/angular#4089] opened 2015-09-09 11:44 UTC
If you reload a page, an isolated route will work, but route params will not.

Related to:
https://github.com/angular/angular/issues/2920

http://stackoverflow.com/questions/32429089/how-do-i-support-routeparams-on-page-reload-using-angular-2-dart?noredirect=1#comment52795245_32429089

FTA:

Im using the Router and RouteParams in Angular 2 Dart.

My routes are as follow:

    @RouteConfig(const [
      const Route(path: '/', component: ViewLanding, as: 'home'),
      const Route(path: '/landing', component: ViewLanding, as: 'landing'),
      const Route(path: '/flights', component: ViewFlights, as: 'flights'),
      const Route(path: '/picker/:cityDepart/:cityArrival/:dateDepart/:dateArrival/', component: ViewFlights, as: 'picker'),
      const Route(path: '/order/:id/:level/:dateDepart/:dateArrival/', component: ViewOrder, as: 'order'),
      const Route(path: '/order/complete', component: ViewComplete, as: 'orderComplete')
    ])

// Application Entry Point

    void main() {
      print('-- Main.dart 2 --');
      bootstrap(Tickets, [
        routerInjectables,
        client_classes,
        // The base path of your application
        bind(APP_BASE_HREF).toValue('/'),
        // uncomment this if you want to use '#' in your url
        bind(LocationStrategy).toClass(HashLocationStrategy)
      ]);
    }

This works fine with router-outlet / router-link / router.navigate

However, on page reload - i don't get a positive match for routes with params. IE: if i refresh http://localhost:8080/#/picker/SAN/SFO/2015-01-01/2015-04-02 - i goto the parent view with no child routes. This symptom is true for any route with params. 

Navigating directly to or refreshing to: http://localhost:8080/#/flights/ - works as expected - the ViewFlights component is instantiated

**Symptoms:** 
routing with params fails. 

**Question:** 
How do i define route configurations to work with parameters on refresh

**Links:**
https://github.com/rightisleft/web_apps_dart/blob/angular2/web/main.dart
https://github.com/rightisleft/web_apps_dart/blob/angular2/lib/client/tickets.dart

**Comment by andresaraujo** [comment] 2015-09-09 14:15
Same here using HashLocationStrategy

This is the stacktrace:

```
ORIGINAL EXCEPTION: Route generator for 'location' was not included in parameters passed.
ORIGINAL STACKTRACE:
#0      DynamicSegment.generate (package:angular2/src/router/path_recognizer.dart:91:7)
#1      PathRecognizer.generate (package:angular2/src/router/path_recognizer.dart:289:26)
#2      RouteRecognizer.generate (package:angular2/src/router/route_recognizer.dart:113:27)
#3      RouteRegistry.generate (package:angular2/src/router/route_registry.dart:215:42)
#4      Router.generate (package:angular2/src/router/router.dart:336:41)
#5      RouterLink.routeParams= (package:angular2/src/router/router_link.dart:54:48)
```

**Comment by btford** [comment] 2015-09-23 05:25
Duplicate of #3957.

Please track that issue, closing this one in favor.

**Closed by btford** 2015-09-23 05:25 UTC
Labels: comp: router, effort1: easy (hour), P2: required, type: bug
