### ISSUE TITLE
Input changes error - [(ng-form-control)] valueChanges

### ISSUE THREAD

**Issue by Werner-Swart-83** [angular/angular#5661] opened 2015-12-07 13:05 UTC
Getting the following exception when control is instantiated : ORIGINAL EXCEPTION: TypeError: this.filterText.valueChanges.debounceTime is not a function

Plnkr for example. Not sure if I am missing something.
http://plnkr.co/edit/ph4cBY7DxAYyBeStsrHI?p=preview

**Comment by ericmartinezr** [comment] 2015-12-07 13:37
This is the same as this issue https://github.com/angular/angular/issues/5632, if you are using alpha 48 you have to import `debounceTime` and `switchMap` as well.

**Comment by jeffbcross** [comment] 2015-12-07 18:06
Closing as dupe of https://github.com/angular/angular/issues/5666

TL;DR, to have the `debounceTime` operator available on the observable prototype, you need to import `rxjs/operators/debounceTime`, which will automatically patch that operator.

app.ts:
```typescript
import 'rxjs/operators/debounceTime';
// Go about your business
```

Note that with RxJS alpha.12 and above, the path will change to `rxjs/add/operator/debounceTime`.

This is all still WIP and evolving quickly :)

**Closed by jeffbcross** 2015-12-07 18:06 UTC

**Comment by Sandeep3005** [comment] 2016-07-10 13:49
I m working with RC4 and this solved problem for me

`import 'rxjs/add/operator/debounceTime';`
