### ISSUE TITLE
Document is not defined in universal( server side rendering)

### ISSUE THREAD

**Issue by rajeshoodles** [angular/angular#50232] opened 2023-05-10 14:13 UTC
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

This issue only happens in angular universal( server-side rendering).
If a **document** is used in the project to communicate with the local storage of the browser and to perform other things. I am getting a "ReferenceError: document not defined" error. Earlier my project was on version 12 and I was able to run my project by using the mock-browser package. But now I switched to version 16 and I am not able to run the project even with the mock-browser package. I am raising my concern to the angular team to give a suitable and stable solution to this problem.

![image](https://github.com/angular/angular/assets/85736891/a25e6213-1762-4ac0-b461-c6c00104f2ee)

### Please provide the exception or error you saw

```true
ReferenceError: document is not defined
    at /home/rajesh/Documents/angular-projects/NowCAST-Web/dist/webview/server/vendor.js:488437:13
    at Module.56601 (/home/rajesh/Documents/angular-projects/NowCAST-Web/dist/webview/server/vendor.js:488446:3)
    at __webpack_require__ (../src/app/app.component.scss:68:1)
    at Module.12706 (../src/app/app.component.scss:68:1)
    at __webpack_require__ (../src/app/app.component.scss:68:1)
    at Module.76154 (../src/app/app.component.scss:68:1)
    at __webpack_require__ (../src/app/app.component.scss:68:1)
    at Module.34621 (../src/app/app.component.scss:68:1)
    at __webpack_require__ (../src/app/app.component.scss:68:1)
    at Module.63370 (../src/app/app.component.scss:68:1)

A server error has occurred.
node exited with 1 code.
connect ECONNREFUSED 127.0.0.1:43279
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 16.0.0
Node: 16.17.1
Package Manager: npm 8.15.0
OS: Linux x64

Angular: 16.0.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, localize, material, platform-browser
... platform-browser-dynamic, platform-server, router
```

**Comment by JeanMeche** [comment] 2023-05-10 14:34
Hi, could you share a bit a code/ a repro of the issue ? 

Do you access a global `document` or one injected by the DI ?

**Comment by alan-agius4** [comment] 2023-05-10 17:16
This is somewhat expected, accessing `document`, `window` and other browser specific APIs is problematic.

As suggested above, the [`DOCUMENT`](https://angular.io/api/common/DOCUMENT) DI token should be used instead to access to document object. 

That said, the error is coming for vendor.js which does typically indicate that one of the dependencies is not compatible with SSR.

Unfortunately, without a minimal reproduction we cannot look into this any further.

**Comment by ognanshissi** [comment] 2023-05-11 11:22
As @alan-agius4  said make sure you are using predefined DI of browser API, and maybe also check le platform before running localStorage code as this available only on the browser.

**Comment by alan-agius4** [comment] 2023-05-22 18:52
Closing due to the lack of a reproduction.

**Closed by alan-agius4** 2023-05-22 18:52 UTC
Labels: needs reproduction, area: server
