### ISSUE TITLE
Lifecycle hooks not firing in IE 11.0.9600.18163

### ISSUE THREAD

**Issue by coreyog** [angular/angular#6867] opened 2016-02-03 17:38 UTC
I first outlined my issue with this in an [SO question](http://stackoverflow.com/questions/35159796/ie-not-calling-lifecycle-hooks-or-filling-input-until-change-detected)

My full page structure is that I have an index.html that loads a Nav component using bootstrap(). This Nav component contains a top bar for navigation and has a router-outlet that will switch through views. One of these views contains a search bar and search results. The search bar is a component in this view.

My search bar has angular @Inputs and @Outputs. It also reads a previous state from localStorage. One of the Outputs is where I emit the state of the history. So in ngOnInit I want to emit the history that was read from the localStorage in the constructor. Since Inputs and Outputs aren't populated by the time the constructor runs, I wait to emit until ngOnInit.

In IE 11 ngOnInit (as well as other lifecycle hooks like ngAfterViewInit and ngAfterContentInit) doesn't fire on page load when my component loads and my Inputs don't pass through to be bound to the UI until either 1) The user clicked on my SearchBox component's inbox or 2) The page is refreshed. None of my code is watching or responding to a refresh. I can't explain why refreshing works for me, but as for clicking, it seems that the component won't run lifecycle hooks until Change Detection fires for my component. Then it behaves the events are pushed through and work just fine.

What should happen (or "What happens in Chrome"):

1. Browser loads index.html
2. Bootstrap Nav component and it's view
3. Routing picks my Search component
4. Search component contains SearchBox component
5. SearchBox component's constructor reads localStorage
6. SearchBox component's @Input values are bound
7. SearchBox component's ngOnInit fires. My code emits the history back to Search component to be stored and bound

What does happen in IE:

1. Browser loads index.html
2. Bootstrap Nav component and it's view
3. Routing picks my Search component
4. Search component contains SearchBox component
5. SearchBox component's constructor reads localStorage

Nothing else happens until user refreshes the page or clicks my search box. At this point Change Detection pokes my SearchBox component and things continue:

6. @Input is bound and reflected in the UI
7. ngOnInit and other lifecycle hooks go off and run my code emitting history, etc.

Due to Bug #6501 I have not been able to test this bug in beta.1 or beta.2 but it's definitely present in Angular 2.0.0.beta.0.

**Comment by bill-long** [comment] 2016-02-12 16:45
I'm hitting the same issue, and I was able to reproduce it with minimal code. For some reason I can't reproduce this in a plunk, so I put it up on Azure instead:

http://angular2routingproblem.azurewebsites.net/

Source code is here: https://github.com/bill-long/angular2routingproblem

I put some logging in ngOnInit and ngOnDestroy so you can watch the lifecycle events. To observe the problem, open the site in IE11 and hit F12. Hit Refresh.

1. Observe that **ngOnInit** was called on HomeComponent when you refreshed or initially navigated to the page. You can see that the ordered list was rendered. So far, so good.
2. Click on route One or Two. Observe that **ngOnDestroy** was called on HomeComponent, but **ngOnInit** was *not* called for the component that you're now looking at.
3. Click on Home. Observe that for the component you just navigated *away from*, we now see **ngOnInit** and **ngOnDestroy**, and we see no **ngOnInit** for HomeComponent. So now that we navigated back Home, we no longer see the ordered list.

At one point I thought I reproduced this in Edge, but I'm not seeing that now. It does reproduce 100% of the time in IE11, however.

This repro uses beta 3 (index.html contains a workaround for #6501). You can rip out the workaround, put it back on beta 0, and it still reproduces.

**Comment by bill-long** [comment] 2016-02-12 16:55
Hrmm, actually, I think I just fixed this by adding the polyfills:

```
<script src="https://cdnjs.cloudflare.com/ajax/libs/es6-shim/0.34.1/es6-shim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/systemjs/0.19.16/system-polyfills.js"></script>
```

Corey can you confirm whether added these two at the top of your scripts fixes the behavior for you?

**Comment by coreyog** [comment] 2016-02-12 17:15
I already had those. Here's a snippet of my experience:

```
@Component({
  selector : 'search-bar',
  directives: [FORM_DIRECTIVES, CORE_DIRECTIVES],
  templateUrl: 'views/searchbar.html'
})
export class SearchBar {
  private history: SearchHistoryEntry[]; // my own personal interface
  private categories: SearchCategory[] = [<long list of categories here>];
  @Output() onHistory = new EventEmitter();
  //... other fields and stuff ...

  constructor() {
    console.log('Reading History');
    this.history = JSON.parse(localStorage.getItem('SearchHistory')) || [];
  }

  ngOnInit() {
    // The constructor doesn't have @Outputs initialized yet. Emit from this
    // life cycle hook instead to be sure they're received by the parent
    console.log('Emitting History');
    this.onHistory.emit(this.history);
  }
}
```

Immediately after page load I see "Reading History" in the console but my SearchBar component's view isn't reflecting any of the categories or history in the view. I very much expected the categories to show up because it's statically defined in the class. I won't see "Emitting History" in the console until I interact with the component in some way.

This, to me, seems like more evidence that the Change Detection isn't triggered after the constructor to see these changes in IE11. Once ngOnChanges fires, I bet ngOnInit will go off (the [developer guide](https://angular.io/docs/ts/latest/guide/lifecycle-hooks.html) states that ngOnInit goes off after the first ngOnChanges). Due to my categories variable not reflecting in the view, I don't believe localStorage has anything to do with this bug nor the fact that I have an ngOnInit defined. I think ngOnChanges is not going off when it should and I'm seeing the aftermath of this.

**Comment by coreyog** [comment] 2016-02-12 17:37
It might also be worth noting that my above example is nested a couple levels deep.

Index.html has an <app></app> that loads my AppComponent who's view has a <router-outlet></router-outlet> that selects my Home controller who's view has <search-bar></search-bar>.

Maybe the nesting is part of the bug.

**Comment by ps2goat** [comment] 2016-03-07 19:27
+1 for lifecycle hooks not working properly in IE (at least 11, haven't tried other versions).

I did get past this original issue from beta.1: https://github.com/angular/angular/issues/6501
Using this code: 
`if ( !Object.hasOwnProperty( 'name' ) ) {
            Object.defineProperty( Function.prototype, 'name', {
                get: function () {
                    var matches = this.toString().match( /^\s*function\s*(\S*)\s*\(/ );
                    var name = matches && matches.length > 1 ? matches[1] : "";
                    Object.defineProperty( this, 'name', { value: name } );
                    return name;
                }
            } );
        }`

However, lifecycle hooks seem to appear out of order.  E.g., the result of a previous lifecycle won't show until I do something to kick off another life cycle.  Everything is one cycle behind.

**Comment by Mattias1** [comment] 2016-05-09 08:05
+1, having this issue too. We have the ie 11 shims in place.
Things mostly work ok. But on the first pageload after closing and re-starting the browser sometimes the ngOnInit method is not called.

**Comment by Mattias1** [comment] 2016-05-19 12:20
I changed a link from being a direct link to being a javascript link and I stopped getting this problem.
If I however manually change the url to `#/objects/objectthingy/1` again, then the `ngAfterViewInit` is not called again.

So I changed this:

    
    <a href="#/objects/objectthingy/{{myObject.id}}" class="my-object-class">

To this:

    
    <a href="javascript:void(0)" (click)="openMyObject(myObject.id)" class="my-object-class">

    // typescript
    openMyObject(objectId: number) {
        this.router.navigate(['/Objects', 'ObjectThingy', { id: objectId}]);
    }

**Comment by jwardle** [comment] 2016-07-04 04:21
+1 - seeing this issue in Beta 15 as well.

**Comment by MatthijsMali** [comment] 2016-07-06 15:24
+1, also having this issue. When is the Angular team flying in on this?

**Comment by coreyog** [comment] 2016-07-06 15:49
This probably hasn't been an issue for awhile. On 2.0.0-RC4 it works as expected.

**Comment by castamir** [comment] 2016-07-14 13:35
I have similar issue on RC4 as well. If I change url in IE11 via navigation bar, nothing "visible" happens until I further interact with page content e.g. click somewhere.

**Comment by zoechi** [comment] 2016-07-17 18:38
@castamir this would need a Plunker to reproduce, otherwise this is not actionable.

**Comment by vicb** [comment] 2016-07-17 19:18
Closing as "On 2.0.0-RC4 it works as expected.".

Please open a new issue with a plunker if still an issue on latest RCs

**Closed by vicb** 2016-07-17 19:18 UTC
