### ISSUE TITLE
ERROR in TypeError: Cannot read property 'flags' of undefined (brand new Angular Installation)

### ISSUE THREAD

**Issue by isipro** [angular/angular#37002] opened 2020-05-08 11:59 UTC
Hello Team, 

just a brand new angular installation gives the following error ( multiple people just reporting it ) 

##Error received when doing ng serve

> ng serve -o
ERROR in TypeError: Cannot read property 'flags' of undefined
    at resolveAlias (C:\Projects\inine.io\ang9-test\node_modules\typescript\lib\typescript.js:36513:37)
    at checkAliasSymbol (C:\Projects\inine.io\ang9-test\node_modules\typescript\lib\typescript.js:64502:26)
    at checkImportBinding (C:\Projects\inine.io\ang9-test\node_modules\typescript\lib\typescript.js:64534:13)
    at checkImportDeclaration (C:\Projects\inine.io\ang9-test\node_modules\typescript\lib\typescript.js:64552:29)
    at checkSourceElementWorker (C:\Projects\inine.io\ang9-test\node_modules\typescript\lib\typescript.js:64961:28)
    at checkSourceElement (C:\Projects\inine.io\ang9-test\node_modules\typescript\lib\typescript.js:64800:17)
    at Object.forEach (C:\Projects\inine.io\ang9-test\node_modules\typescript\lib\typescript.js:317:30)
    at checkSourceFileWorker (C:\Projects\inine.io\ang9-test\node_modules\typescript\lib\typescript.js:65123:20)
    at checkSourceFile (C:\Projects\inine.io\ang9-test\node_modules\typescript\lib\typescript.js:65091:13)
    at getDiagnosticsWorker (C:\Projects\inine.io\ang9-test\node_modules\typescript\lib\typescript.js:65179:17)
    at Object.getDiagnostics (C:\Projects\inine.io\ang9-test\node_modules\typescript\lib\typescript.js:65165:24)
    at C:\Projects\inine.io\ang9-test\node_modules\typescript\lib\typescript.js:98703:85
    at runWithCancellationToken (C:\Projects\inine.io\ang9-test\node_modules\typescript\lib\typescript.js:98665:24)
    at getBindAndCheckDiagnosticsForFileNoCache (C:\Projects\inine.io\ang9-test\node_modules\typescript\lib\typescript.js:98691:20)
    at getAndCacheDiagnostics (C:\Projects\inine.io\ang9-test\node_modules\typescript\lib\typescript.js:98956:26)
    at getBindAndCheckDiagnosticsForFile (C:\Projects\inine.io\ang9-test\node_modules\typescript\lib\typescript.js:98688:20)

##Package Versions when doing ng version

ngular CLI: 9.1.4
Node: 10.16.0     
OS: win32 x64     

Angular: 9.1.5
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.4
@angular-devkit/build-angular     0.901.4
@angular-devkit/build-optimizer   0.901.4
@angular-devkit/build-webpack     0.901.4
@angular-devkit/core              9.1.4
@angular-devkit/schematics        9.1.4
@angular/cli                      9.1.4
@ngtools/webpack                  9.1.4
@schematics/angular               9.1.4
@schematics/update                0.901.4
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0

##Multiple people just reporting it here
https://github.com/microsoft/TypeScript/issues/35021

Thanks in advance!
Regards,
Ivan.

**Comment by JadedEric** [comment] 2020-05-08 12:00
Trying to downgrade to lower than 9.1.4 also does not work. Tried deleted the node_modules and the package-lock.json file and re-installing the packages once downgrade completed, persists the error.

Initially thought it was a local installation issue, but found that each new command afterwards pulls this broken typescript.js file down, so uninstalled node/npm completely and reinstalled it. then tried to re-install angular 9.1.0 globally and 9.1.0 for a new app.

Nada. Still broken. I believe this is a bigger issue than just a broken TS file?

**Comment by ericmartinezr** [comment] 2020-05-08 12:04
Just do a little search. This has been opened a lot in the last few hours. 

https://github.com/angular/angular/search?q=Cannot+read+property+%27flags%27+of+undefined&type=Issues

Tracked

**Comment by alan-agius4** [comment] 2020-05-08 12:06
Duplicate of https://github.com/angular/angular/issues/36993

**Closed by alan-agius4** 2020-05-08 12:06 UTC

**Comment by neon096** [comment] 2020-05-08 12:11
https://stackoverflow.com/questions/61670882/error-in-typeerror-cannot-read-property-flags-of-undefined/61671596#61671596
