### ISSUE TITLE
NgFor and nested components, view and model not synchronized

### ISSUE THREAD

**Issue by eugenyshchelkanov** [angular/angular#6482] opened 2016-01-14 11:13 UTC
Simple select component, rendered in NgFor. When `my-select` is used to change first value to `one`, view for the second value also gets updated. Am I missing something here or is it a bug?
http://plnkr.co/edit/IFgLBhc841R5NtYzAMTc?p=preview

**Comment by mhevery** [comment] 2016-01-21 05:20
Something weird is going on in there.

**Comment by zoechi** [comment] 2016-01-21 08:37
I guess this is because angular can't distinguish different `undefined`. If the values are wrapped in objects this doesn't reproduce http://plnkr.co/edit/FCXT3w6gWBX0fHDGDX2c?p=preview
I don't see why identity is relevant here but if Angular searches the `values` for a specific value it can easily find the wrong one.

**Comment by zoechi** [comment] 2016-04-07 08:46
This was fixed by `*ngForTrackBy` http://plnkr.co/edit/R4pBPVzE1K1ZPFemMhGs?p=preview

I think this can be closed.

**Closed** 2016-04-08 03:41 UTC
Labels: comp: core/directives, effort2: medium (day), hotlist: community-help, P3: important, type: bug
