### ISSUE TITLE
ngOnInit and ngOnDestroy don't works with decorators.

### ISSUE THREAD

**Issue by Sikatrih** [angular/angular#35336] opened 2020-02-11 14:18 UTC
I have updated my app from angular 7 to angular  9 and now next constructions do not works any more.

```ts
import { Subject } from 'rxjs';

const ON_INIT_NAME = 'ngOnInit';
const ON_DESTROY_NAME = 'ngOnDestroy';

export function Destroy(): PropertyDecorator {
    return (target: any, prop: string | symbol) => {
        const ngOnInitClone: (() => void) | null = target[ON_INIT_NAME];
        const ngOnDestroyClone: (() => void) | null = target[ON_DESTROY_NAME];

        target[ON_INIT_NAME] = function () {
            this[prop] = new Subject();

            if (ngOnInitClone) {
                ngOnInitClone.call(this);
            }
        };

        target[ON_DESTROY_NAME] = function () {
            this[prop].next(this);
            this[prop].complete();

            if (ngOnDestroyClone) {
                ngOnDestroyClone.call(this);
            }
        };
    };
}

```

**Comment by ChellappanRajan** [comment] 2020-02-11 14:37
Possible duplicate of #31495

**Closed** 2020-02-11 15:56 UTC
