### ISSUE TITLE
Router: Export containsTree in new router

### ISSUE THREAD

**Issue by poke** [angular/angular#10203] opened 2016-07-21 10:58 UTC
The old router had this method [`router.isRouteActive()`](https://github.com/angular/angular/blob/2.0.0-rc.4/modules/%40angular/router-deprecated/src/router.ts#L139) which could be used to check whether a route was active.

The new v3 component router does not offer this. Instead, the `RouterLinkActive` directive uses [some custom logic](https://github.com/angular/angular/blob/2.0.0-rc.4/modules/%40angular/router/src/directives/router_link_active.ts#L99) to figure out whether a route is active or not. It all boils down to comparing the current `UrlTree` with the target `UrlTree` using [`containsTree`](https://github.com/angular/angular/blob/2.0.0-rc.4/modules/%40angular/router/src/url_tree.ts#L16).

Unfortunately, `containsTree` is not exported at module level. So anyone who wants to figure out whether a route is active or not (and cannot use the directive) has to implement all this logic on their own.

Can we [reexport](https://github.com/angular/angular/blob/2.0.0-rc.4/modules/%40angular/router/index.ts) the `containsTree` function, so it can be used?

**Comment by brandonroberts** [comment] 2016-07-21 18:23
Duplicate of https://github.com/angular/angular/issues/9446

**Closed** 2016-07-21 18:45 UTC
