### ISSUE TITLE
Form Password field is set as invalid field with browser's saved password option

### ISSUE THREAD

**Issue by Sibiraj-Codes** [angular/angular#16773] opened 2017-05-14 07:56 UTC
- [X] bug report

**Current behaviour:**
Now every browser comes with save password option.

If the password is saved by a browser when we reload a page that contains form password field. By default, it is set to invalid even though the browser fills password field. On clicking anywhere on the page it is set to valid.

This behaviour is only with input type="password".

**Expected / new behaviour:**
If a valid password is auto-filled by browser then it should be made valid

**Comment by jasonaden** [comment] 2017-05-15 18:31
Thanks for reporting this issue. However this issue is a duplicate of an existing issue #12395. Please subscribe to that issue for future updates.

**Closed by jasonaden** 2017-05-15 18:31 UTC
