### ISSUE TITLE
 Value at position 6 in the NgModule.imports of AppModule is not a reference

### ISSUE THREAD

**Issue by baljinder-inmarsat** [angular/angular#36673] opened 2020-04-16 18:05 UTC
# 🐞 bug report

### Affected Package
    "@angular/core": "^9.1.2",

### Is this a regression?

Yes fine in Angular 8.2.14

### Description

I am trying to upgrade, However I am stuck due to the following error in my terminal:
![Screenshot from 2020-04-16 18-45-32](https://user-images.githubusercontent.com/45174015/79488992-89ed0500-8012-11ea-8f3c-4eecaf6f1e69.png)

I've been following all the steps, using https://update.angular.io/#8.0:9.0. but for some reason I cannot resolve this issue.

I had looked at this issue and worked out where the problem, line, is in my app.module.ts.
    ApiModule.forRoot()
if I remove forRoot(), the error has gone but I need the forRoot().

Thanks

api.module.ts:

<pre><code>
@NgModule({
  declarations: [],
  imports: []
})
export class ApiModule {
  // We need to use forRoot to match with the dev API module.
  public static forRoot(): ModuleWithProviders< ApiModule > {
    return {
      ngModule: ApiModule,
      providers: [
        {
          provide: JWT_OPTIONS,
          useValue: {}
        },
        JwtHelperService,
        GxAssuranceApiService,
        CustomersApiService,
        FoldersApiService,
        OrdersApiService,
        ProductsApiService,
        SitesApiService,
        SystemStatusApiService,
        UsersApiService,
        RefDataApiService
      ]
    };
  }
}
</code></pre>

## 🔥 Exception or Error
<pre><code>
ERROR in src/app/app.module.ts:79:12 - error NG1010: Value at position 6 in the NgModule.imports of AppModule is not a reference: [object Object]

 79   imports: [
               ~
 80     /**
    ~~~~~~~
... 
166     })
    ~~~~~~
167   ],
    ~~~


</code></pre>


## 🌍  Your Environment

**Angular Version:**
<pre><code>
Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.1
@angular-devkit/build-angular     0.901.1
@angular-devkit/build-optimizer   0.901.1
@angular-devkit/build-webpack     0.901.1
@angular-devkit/core              9.1.1
@angular-devkit/schematics        9.1.1
@angular/cdk                      9.2.1
@angular/cli                      9.1.1
@ngtools/webpack                  9.1.1
@nguniversal/common               9.1.0
@nguniversal/express-engine       9.1.0
@schematics/angular               9.1.1
@schematics/update                0.901.1
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0
</code></pre>

**Anything else relevant?**
https://github.com/angular/angular/issues/36271
This helped in identifying that the error is to do with the forRoot() but I cannot find a solution in my case.

**Comment by petebacondarwin** [comment] 2020-04-16 18:21
The problem is in your `AppModule` not `ApiModule`. What is the 6th/7th position in the `imports` property of `AppModule`?

**Comment by baljinder-inmarsat** [comment] 2020-04-16 18:45
![Screenshot from 2020-04-16 19-42-56 - 1](https://user-images.githubusercontent.com/45174015/79494217-8b223000-801a-11ea-9a2b-0a7ce7a3fa68.png)
lines 5 - 12

thanks @petebacondarwin

**Comment by petebacondarwin** [comment] 2020-04-16 18:49
Actually you need to look at:

```ts
@NgModule({
 ...
 imports: [ ... ]
 ...
})
class AppModule {}
```

**Comment by baljinder-inmarsat** [comment] 2020-04-16 18:52
quite a long one, sorry:

 imports: [
    /**
     * Angular
     */
    CommonModule,
    BrowserModule,
    SharedModule,
    HttpClientModule,
    BrowserAnimationsModule,
    CookieModule.forRoot(),
    ApiModule.forRoot(),
    /**
     * StoreModule.forRoot is imported once in the root module, accepting a reducer
     * function or object map of reducer functions. If passed an object of
     * reducers, combineReducers will be run creating your application
     * meta-reducer. This returns all providers for an @ngrx/store
     * based application.
     */
    StoreModule.forRoot(reducers, {
      runtimeChecks: {
        // These error in IE, so we need to disable them:
        // https://github.com/ngrx/platform/issues/1991
        strictStateImmutability: !environment.disableNgRxChecks,
        strictActionImmutability: !environment.disableNgRxChecks,
        strictStateSerializability: !environment.disableNgRxChecks,
        strictActionSerializability: !environment.disableNgRxChecks
      }
    }),
    /**
     * @ngrx/router-store keeps router state up-to-date in the store.
     */
    StoreRouterConnectingModule.forRoot({
      // They stateKey defines the name of the state used by the router-store reducer.
      // This matches the key defined in the map of reducers
      stateKey: 'router',
      routerState: RouterState.Minimal,
      serializer: CustomRouterStateSerializer,
      navigationActionTiming: NavigationActionTiming.PostActivation
    }),
    /**
     * Store devtools instrument the store retaining past versions of state
     * and recalculating new states. This enables powerful time-travel
     * debugging.
     *
     * To use the debugger, install the Redux Devtools extension for either
     * Chrome or Firefox
     *
     * See: https://github.com/zalmoxisus/redux-devtools-extension
     */
    StoreDevtoolsModule.instrument({
      stateSanitizer,
      actionSanitizer,
      name: 'NgRx DUE DevTools',
      logOnly: environment.production,
      serialize: environment.production ? undefined : true
    }),
    /**
     * EffectsModule.forRoot() is imported once in the root module and
     * sets up the effects class to be initialized immediately when the
     * application starts.
     *
     * See: https://github.com/ngrx/platform/blob/master/docs/effects/api.md#forroot
     */
    EffectsModule.forRoot([...INM_STORE_EFFECTS]),
    /**
     * Shared Module
     * Includes UI common components
     * and 3rd party libraries
     */
    SharedModule,
    /**
     * App routing
     */
    AppRoutingModule,
    /**
     * CoreModule.forRoot() is imported once in the root module and
     * is the actual entry point of the application.
     */
    CoreModule.forRoot(),
    /**
     * Google analytics module
     * https://github.com/angulartics/angulartics2#installation
     */
    Angulartics2Module.forRoot({
      gst: {
        trackingIds: [environment.GOOGLE_TRACKING_CODE]
      }
    })
  ]

**Comment by petebacondarwin** [comment] 2020-04-16 19:04
Oh! Sorry. I didn't understand your original description correctly. I see now that you already identified that `ApiModule.forRoot()` is the problem. 

Can you try changing:

```
public static forRoot(): ModuleWithProviders< ApiModule > {
```

to 

```
public static forRoot() {
```

**Comment by baljinder-inmarsat** [comment] 2020-04-16 19:10
unfortunately, still throws the same error.

**Comment by petebacondarwin** [comment] 2020-04-16 19:20
Or alternatively try removing parts of the object that are returned from this `forRoot()`

**Comment by petebacondarwin** [comment] 2020-04-16 19:21
If you could give me access to the project I could debug it for you.

**Comment by baljinder-inmarsat** [comment] 2020-04-16 19:28
set the following but I still see it.

<pre><code>
import { NgModule } from '@angular/core';


@NgModule({
  declarations: [],
  imports: []
})
export class ApiModule {
  // We need to use forRoot to match with the dev API module.
  public static forRoot() {
    return {
      ngModule: ApiModule,
      providers: [

    };
  }
}</code></pre>

I'm soooooooooo sorry, I wish I could but I don't have the rights and i don't believe I will get it granted.

**Comment by petebacondarwin** [comment] 2020-04-16 19:56
Can you try either debugging into or adding a `console.log(entry)` statement at the point where it throws the `FatalDiagnosticError` in the `resolveTypeList()` method in `node_modules/@angular/compiler-cli/src/ngtsc/annotations/src/ng_module.js` - somewhere around line 543?

**Comment by petebacondarwin** [comment] 2020-04-16 19:58
If you can debug then it might be worth looking at this section of code in the same file:

```ts
            if (ngModule.has('imports')) {
                rawImports = ngModule.get('imports');
                var importsMeta = this.evaluator.evaluate(rawImports, moduleResolvers);
                importRefs = this.resolveTypeList(rawImports, importsMeta, name, 'imports');
            }
```

Specifically `this.evaluator.evaluate(rawImports, moduleResolvers);` for that import.

**Comment by baljinder-inmarsat** [comment] 2020-04-16 20:20
sorry I couldn't stringfy the object.
![Screenshot from 2020-04-16 21-20-01](https://user-images.githubusercontent.com/45174015/79502845-1eae2d80-8028-11ea-8f40-7581350a7599.png)

**Comment by petebacondarwin** [comment] 2020-04-16 20:27
What about something like `console.log(Object.keys(entry), entry.constructor)`?

**Comment by baljinder-inmarsat** [comment] 2020-04-16 20:39
also add it there to see:
![Screenshot from 2020-04-16 21-38-47](https://user-images.githubusercontent.com/45174015/79504411-c3ca0580-802a-11ea-8534-1f29c300bbf5.png)

**Comment by petebacondarwin** [comment] 2020-04-16 20:42
OK, so as somewhat expected the static evaluator is returning a `DynamicValue`, which means it was not able to evaluate that call...

It would be really great if you could debug into `this.evaluator.evaluate(rawImports, moduleResolvers);` to see at what point it gives up evaluating...

**Comment by baljinder-inmarsat** [comment] 2020-04-16 21:03
I've been trying to debug, but the console aren't making sense to me :)
however I do notice a difference, highlight below:
![Screenshot from 2020-04-16 22-02-27](https://user-images.githubusercontent.com/45174015/79506577-1d7fff00-802e-11ea-945a-7106246d5198.png)

**Comment by petebacondarwin** [comment] 2020-04-16 21:05
If you use VS Code you can attach to a node process to debug and set breakpoints. You can then run `node --inspect-brk node_modules/.bin/ng build`.

**Comment by baljinder-inmarsat** [comment] 2020-04-16 22:08
Wish I knew what I was looking for, but I sent some screenshots. Hopefully this helps.
![Screenshot from 2020-04-16 23-05-47](https://user-images.githubusercontent.com/45174015/79511333-04c81700-8037-11ea-825e-b2ab4e06c128.png)

-------------------

![Screenshot from 2020-04-16 23-01-48](https://user-images.githubusercontent.com/45174015/79511338-098ccb00-8037-11ea-94c8-782d9a3f55bd.png)

**Comment by baljinder-inmarsat** [comment] 2020-04-17 08:50
OMG, finally figured it out sleeping on it over night.
We've got this in the angular.json:
                {
                  "replace": "src/app/api/api.module.ts",
                  "with": "src/app/api/api.module.dev.ts"
                }
If I remove this it works.
but now the issue is, why is this api.module.dev.ts  not work.

@petebacondarwin sincerely would like to thank you for previous comments . it was short but quite a learning curve, never debugged the node modules before :).

**Comment by petebacondarwin** [comment] 2020-04-17 09:01
🤦 
Glad you found a step forward. The question next is, what is different between these two files?

**Comment by baljinder-inmarsat** [comment] 2020-04-17 09:15
Cool,
Shorten it out cause it had an awful lot of providers.push(), hope this gives you an idea of it's intentions:
<pre><code>
@NgModule()
export class ApiModule {
  public static forRoot(): ModuleWithProviders<ApiModule> {
    const config = environment.MOCK_DATA || {};
    faker.seed(1);

    const providers: Provider[] = [
      FakeQueryService,
      CompanyService,
      RefDataApiService,
      {
        provide: JwtHelperService,
        useClass: FakeJwtHelperService
      },
      DebugService
    ];

    providers.push(
      config.orders
        ? {
            provide: OrdersApiService,
            useClass: FakeOrdersApiService
          }
        : OrdersApiService
    );

    return {
      providers,
      ngModule: ApiModule
    };
  }

  constructor(debug: DebugService) {
    // Make the debug service accessible in the console.
    (window as any).inm = debug;
  }
}

</code></pre> 

but even if I put it to the bare minimum, still get the error:

<pre><code>
@NgModule()
export class ApiModule {
  public static forRoot(): ModuleWithProviders<ApiModule> {
    const providers: Provider[] = [];
    return {
      providers,
      ngModule: ApiModule
    };
  }
}
</code></pre>

**Comment by baljinder-inmarsat** [comment] 2020-04-17 09:19
FYI, following works. guess the problem is it does not like it being set out side the object.
<pre>
<code>
@NgModule()
export class ApiModule {
  public static forRoot(): ModuleWithProviders<ApiModule> {
    return {
      providers: [],
      ngModule: ApiModule
    };
  }
}
</code>
</pre>

**Comment by petebacondarwin** [comment] 2020-04-17 09:24
OK so this is the heart of the problem. We only support statically analyzing quite simple functions in the compiler. In this case the function must just consist of a single return statement in your working example. You can imagine that it is not viable for the compiler to be able to run arbitrary JS when trying to evaluate what the return value of such a function.

That being said the static analyzer can do quite a good job with evaluating expressions, so rather than push statements, you could have things like: 

```
providers: [
  config.orders
        ? {
            provide: OrdersApiService,
            useClass: FakeOrdersApiService
          }
        : OrdersApiService
]
```

I am going to close this issue as the compiler is working as expected and we do not support imperative code in `ModuleWithProviders` functions.

**Closed by petebacondarwin** 2020-04-17 09:24 UTC
Labels: comp: compiler, comp: ivy

**Comment by baljinder-inmarsat** [comment] 2020-04-17 09:44
@petebacondarwin just to share the outcome what you suggested, it unfortunately didn't work.

Thanks again :)

**Comment by petebacondarwin** [comment] 2020-04-17 09:59
Sorry to hear that.

**Comment by petebacondarwin** [comment] 2020-04-17 10:12
We are going to improve the error message to make this kind of thing less painful to debug.

**Comment by robbiemu** [comment] 2020-04-18 00:37
I find the resolution here disheartening and more importantly ambiguous! What exactly is imperative code? I'm finding that I cannot even do:
```ts
forRoot(): ModuleWithProviders { 
  console.log('[PreloadingModule::forRoot]')
    return {
      ngModule: PreloadingModule,
      providers: []
    }
}

```

nor can I do:
```ts
forRoot(): ModuleWithProviders { 
  const providers = []
    return {
      ngModule: PreloadingModule,
      providers
    }
}
```

but yes, 
```ts
forRoot(): ModuleWithProviders { 
    return {
      ngModule: PreloadingModule,
      providers: []
    }
}
```
-- that works just fine

in which case, I am wondering what on earth I am supposed to be able to do in there!

**Comment by robbiemu** [comment] 2020-04-18 01:01
dooh! I finally got it, and I was wrong, it is not that bad. In fact I can do what I wanted, just without a temporary variable:
```ts
  /** the purpose of a forRoot method is to initialize a module before a component loads  */
  static forRoot (
    preloadingSpecifications: Array<PreloadingSpecification> = []
  ): ModuleWithProviders {
    return {
      ngModule: PreloadingModule,
      providers: preloadingSpecifications.reduce(
        PreloadingModule.mixinDefaultSpecifications,
        [...CoreModule.preloadingSpecifications]
      )
    }
  }
```

**Comment by JoostK** [comment] 2020-04-18 09:10
@robbiemu Please see #36415 for some more details. It's kept open for tracking purposes.
