### ISSUE TITLE
Router cant navigate when error within resolvers and guards occurs

### ISSUE THREAD

**Issue by bosco688** [angular/angular#25589] opened 2018-08-21 08:34 UTC
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report 
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
If observable throws error within guards or resolvers, then router.navigate in custom error handler fails.
Router.navigate was called in ngZone. 

Navigation will only complete, if change detection is called manually.

## Expected behavior
Router is able to navigate without manual change detection.

## Minimal reproduction of the problem with instructions
DEMO: https://stackblitz.com/edit/angular-gitter-j2ft7u

1. Run demo
2. Click on 'Go to feature'
3. Now you can see an error in console, but router doenst navigate to /error page
4. Click on 'Run change detection'
5. Now the /error page is loaded

## What is the motivation / use case for changing the behavior?
Navigating in global error handler should work ;)

## Environment

<pre><code>
Angular version: 6.1.3, but also in Version 5.x

Browser:
- [X] Chrome (desktop) version 68
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [X] Firefox version 61
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [X] IE version 11
- [X] Edge version for Windows 10 Build 1803

</code></pre>

**Comment by jasonaden** [comment] 2018-08-21 22:40
Agreed. This is something we're working on now, hopefully resolving soon.

**Comment by tobias74** [comment] 2019-01-04 15:13
This seems to be related: [https://github.com/angular/angular/issues/15946](https://github.com/angular/angular/issues/15946)

**Comment by muuvmuuv** [comment] 2020-05-06 19:41
Hey, it seems that nothing was done in the last two years on this issue or those who are marked "related". Until this issue I was stuck in a "related xxx" issue loop. Is there a main issue for that? I do have that issue as well.

My use case is that I want to load user details before the page is loaded/redirected, so I don't need a bunch of `*ngIf="user.avatar"` stuff. On failure, it should let my component display a modal that says "User not found" and not totally fail to route like it is at the moment.

**Comment by kosso** [comment] 2020-05-14 11:45
This appears to still be an issue. My use-case is the resolver gets user data to be available to a form for a user to edit their data.  (eg: `/profile/:username/edit` ) 

Not being able to catch the resolver error, if someone manually entered the route into the browser with an invalid username is proving to be a bit problematic. 

Ideally, I'd want to navigate the user to another route at that point, since I can't do it in the edit form component, as the user never gets there.  

I'm only left with the uncaught error.

**Comment by atscott** [comment] 2020-07-13 17:10
confirmed in v10 with Ivy as well: https://stackblitz.com/edit/angular-ivy-ix2pac

**Comment by mtuzinskiy** [comment] 2022-12-01 09:48
Any updates on this?  4 years passed

**Comment by atscott** [comment] 2022-12-01 16:25
Closing as working as intended. From @JiaLiPassion, `handleError` is called outside the Angular zone by design: https://github.com/angular/angular/issues/15946#issuecomment-395323545

Simply re-entering the zone and running a navigation does not cause change detection to happen. Just like in an `OnPush` component, which is still inside the Angular zone, you need something to indicate that the application is "dirty" and change detection should run again. Wrapping the navigate in `setTimeout` does this by creating a macrotask inside the Angular zone: https://stackblitz.com/edit/angular-ivy-aobeu5?file=src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fapp.error-handler.ts

**Closed by atscott** 2022-12-01 16:25 UTC
Labels: type: bug/fix, freq3: high, area: router, area: zones, jira-sync, state: confirmed, router: guards/resolvers, router: navigation pipe, P3
