### ISSUE TITLE
Angular.dev: the docs have poor support for monitors with over 2560px width

### ISSUE THREAD

**Issue by Assassinduck** [angular/angular#53090] opened 2023-11-21 12:40 UTC
### Describe the problem that you experienced

If you try to visit the [angular.dev](angular.dev) front page while using an ultrawide monitor, (or any monitor with over 2560px of width), the sidebar will lay itself over the angular playground.

### Describe what you were looking for in the documentation

Nothing specific, just visited the front page

### Describe the actions that led you to experience the problem

Went to the angular.dev/ page using an ultra-wide monitor with over 2560px of width

### Describe what you want to experience that would fix the problem

A fix for the issue would be to change the max-width property on the adev-root component from `max-width: 2560` to `max-width: calc(100% - 25px)` or something like that so that it supports monitors of all sizes.

Image illustrating what the page looks like with the suggested fix applied:
![ang2](https://github.com/angular/angular/assets/24327252/c76fdff7-f801-4dcd-a7be-ebf8d4f13646)

![devtools](https://github.com/angular/angular/assets/24327252/f3a06808-384e-4006-a049-0e46c6b88755)

### Add a screenshot if that helps illustrate the problem

![image for illustration](https://github.com/angular/angular/assets/24327252/f78294ca-587b-4b6e-93eb-af550cd040ec)

### If the problem is browser-specific, please specify the device, OS, browser, and version

I first encountered the issue in brave v 1.60.118 which is on a slightly newer version of chromium than chrome, and I've been able to reproduce it on the latest version of edge too.

The issue appears to not show up on some slightly older chrome versions, per [this](https://github.com/angular/angular/issues/53090#issuecomment-1821024483) comment

**Comment by JoostK** [comment] 2023-11-21 14:25
Appears to work fine for me in Chrome 119.0.6045.125:

![angular dev_playground](https://github.com/angular/angular/assets/123679/99ac0d23-ec73-4baa-8fd0-8d8e65f401c8)

**Comment by Assassinduck** [comment] 2023-11-21 14:29
> Appears to work fine for me in Chrome 119.0.6045.125:
> 
> ![angular dev_playground](https://user-images.githubusercontent.com/123679/284610222-99ac0d23-ec73-4baa-8fd0-8d8e65f401c8.png)

Hmmm interesting. I forgot to add that I am on Brave, version 1.60.118 which uses chromium v119.0.6045.163

**Comment by twerske** [comment] 2023-11-29 18:01
This is a duplicate of https://github.com/angular/angular/issues/52648

Thanks for your interest in improving Angular.dev!

**Closed by twerske** 2023-11-29 18:01 UTC
Labels: area: adev
