### ISSUE TITLE
ActivatedRoute params should include parent parameters, from root

### ISSUE THREAD

**Issue by voithos** [angular/angular#20572] opened 2017-11-21 23:42 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Currently, the router has some [special casing](https://github.com/angular/angular/blob/54e02449549448ebab6f255f2da0b4396665c6f0/packages/router/src/router_state.ts#L185) for when parent route parameters are inherited by child ActivatedRoutes. Specifically, they are only inherited if the parent route was either (1) configured without a `component`, or (2) configured with `path: ''`.

## Expected behavior
It seems like it'd be more useful to allow the option of just unconditionally flattening params from the root to the current route. This would allow child pages to have easy access to params defined in parent routes.

## What is the motivation / use case for changing the behavior?
Child routes often need to access parameters defined on parent routes, and this would make it much simpler to reliably have the params available in the `ActivatedRoute` that is injected into the child component (and avoid the unpredictability of the current merging approach).

## Environment

<pre><code>Angular version: HEAD
</code></pre>

**Comment by trotyl** [comment] 2017-11-23 06:08
Duplicate of #11023

**Comment by voithos** [comment] 2017-11-23 06:37
If I'm reading it correctly, I think #11023 is a bit different. That discussion mentions sibling components and even components that are outside a `<router-outlet>`. The parameters described in _this_ issue are all reachable (you just have to navigate up the `ActivatedRoute.parent` chain), but the feature request is about making them present in the child `ActivatedRoute` such that explicitly referencing `ActivatedRoute.parent` is unnecessary.

**Closed** 2017-12-20 18:06 UTC
Labels: comp: router, type: feature
