### ISSUE TITLE
Inputs are not inherited in Ivy through several levels of extends

### ISSUE THREAD

**Issue by waterplea** [angular/angular#35722] opened 2020-02-27 16:12 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/compiler probably

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 8

### Description

I have this setup:

```
export abstract class AbstractComp {
  @Input() someInput: number:

  abstract someProp: number;
}

export abstract class LessAbstractComp extends AbstractComp {
  someProp = 237
}

export class ConcreteComp extends AbstractComp {
  someProp = 42;
}

export class AnotherConcreteComp extends LessAbstractComp {
}
```

When I write my `AnotherConcreteComp` in template it autocompletes for `someInput` input so language-service seem to know about it, but when i compile with `ng serve` I get `Can't bind to 'someInput' since it isn't a known property` error. With `ConcreteComp` when there is no layer of inheritance it works fine.

## 🔬 Minimal Reproduction

https://ng-run.com/edit/sBduRgWzz4qQkiw4sSfB

## 🔥 Exception or Error
<pre><code>
Can't bind to 'XXX' since it isn't a known property
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>9.0.3</code></pre>

**Anything else relevant?**

Also happens with 9.0.2. Could it be because that extra layer of inheritance doesn't have any Angular decorators in it?

**Comment by pkozlowski-opensource** [comment] 2020-02-27 16:14
> Could it be because that extra layer of inheritance doesn't have any Angular decorators in it?

This is my understanding - you should add the `@Directive` decorator on your abstract class. hard to be sure without a minimal reproduce scenario, though.

**Comment by waterplea** [comment] 2020-02-27 16:23
I forgot to mention it is an Angular 8 library. I know I would need to add it in Ivy, but this is after my library was parsed by ngcc.

**Comment by Achilles1515** [comment] 2020-02-27 21:07
Reproduction:
https://ng-run.com/edit/sBduRgWzz4qQkiw4sSfB

[Angular documentation](https://angular.io/guide/migration-undecorated-classes#decorator-missing-from-parent-class) states:
>**Decorator missing from parent class**
When the decorator is missing from the parent class, the subclass will inherit a constructor from a class for which the compiler did not generate special constructor info (because it was not decorated as a directive). When Angular then tries to create the subclass, it doesn't have the correct info to create it.

Given that statement, specifically the last sentence about Angular not being able to "create it", why does the below demo not throw an error (decorator-less abstract base class uses `@Input` and dependency injection - see console log)? It seems to create both subclassed components just fine.

https://ng-run.com/edit/x25d31U5xWvmfAlE1YmS

@alxhub ,  as we were recently discussing this topic in #35585.

**Comment by JoostK** [comment] 2020-03-15 01:17
I think this is a limitation of ngcc. The `UndecoratedParentMigration` only considers constructors for DI purposes, not input/outputs.

**Comment by waterplea** [comment] 2020-03-16 18:50
It probably is, nevertheless it's a compatibility issue.

**Comment by JoostK** [comment] 2020-03-25 14:22
Tracking as FW-2023.

**Comment by cedvdb** [comment] 2020-04-06 11:46
We have the same bug. Couldn't reproduce it in stackblitz...

https://stackblitz.com/edit/angular-nxxxrm?file=package.json

**Comment by crowmagnumb** [comment] 2020-05-21 23:55
I had the same problem with class A inheriting from class B which in turn inherits from class C. Class B had some @Input parameters which with Angular 9 and Ivy were suddenly not visible. No error saying "can't bind to property X", instead they were just ignored (silently not bound to). When @pkozlowski-opensource suggested the need for an @Directive() decorator on class B I was skeptical at best, but lo and behold that worked! Class C's @Input's bind just fine without any decorator on the class, just the middle class has the problem.

**Comment by cedvdb** [comment] 2020-05-22 22:24
Solved my problem also by adding the @Directive on the parent abstract class

**Comment by petebacondarwin** [comment] 2020-06-08 10:00
Ngcc needs to inject a synthetic decorator for a class which is part of an inheritance chain.

The ng-update migration to handle this case is also being updated for this scenario https://github.com/angular/angular/pull/35339 and ngcc needs to achieve the same effect.

**Comment by stephanie-dm** [comment] 2020-10-19 12:13
FYI: here is the link to the official documentation regarding this change: 
https://angular.io/guide/migration-undecorated-classes

**Comment by JoostK** [comment] 2022-05-27 10:57
I am going to close this as not something we'll address.

**Closed by JoostK** 2022-05-27 10:57 UTC
Labels: type: bug/fix, freq2: medium, engine: ivy, comp: ngcc, state: confirmed, P3
