### ISSUE TITLE
Resolve not working correctly (doesn't navigate when it should)

### ISSUE THREAD

**Issue by klinki** [angular/angular#12854] opened 2016-11-14 11:21 UTC
**I'm submitting a ...** 
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When Resolve returns Observable and non-false value is resolved, navigation should continue, but it doesn't.

**Expected behavior**
Navigation should proceed and resolved data should be passed to ActivatedRoute.data field.

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/eJpzsXEM5CyurCs4jc1e?p=preview

In menu click on "Second Link - Correct using Resolve"

**Please tell us about your environment:**
* **Fedora 24** 

* **Angular version:** 2.1.2

* **Browser:** [ Chrome 54 | Firefox 49 ]
 
* **Language:** [TypeScript 2]

**Comment by michaelchiche** [comment] 2016-11-14 11:23
https://github.com/angular/angular/issues/12767

**Comment by klinki** [comment] 2016-11-14 11:28
Are you sure? It doesn't navigate at all, it is not just missing data.

**Comment by klinki** [comment] 2016-11-14 11:35
I'm also wondering if the current Resolve API is designed properly. I understand the idea of returning Promise|Observable|primitive data type, but IMHO it would be better to use just Promise or Observable and handle errors not by returning false, but using promise/observable way of handling errors.

Because what if user wants to resolve some boolean variable which could be potentially false? I think in current implementation it is impossible? But if it uses promise/observable way of handling errors, it would be completely fine.

**Comment by chuckjaz** [comment] 2016-11-16 02:26
Thanks for reporting this issue. However this issue is a duplicate of an existing issue #12767. Please subscribe to that issue for future updates.

@klinki For a design change, please open a separate issue as a feature request for the new design.

**Closed by chuckjaz** 2016-11-16 02:26 UTC

**Comment by klinki** [comment] 2016-11-16 08:09
@chuckjaz I'm already subscribed in that issue. But I think it is different problem? I mean, it might be related, but problem with this issue is it ***doesn't navigate at all***. But issue you send link to is related to data not being propagated to child components.

**Comment by klinki** [comment] 2016-11-16 08:57
@chuckjaz I see the reason now - it doesn't navigate because I didn't call complete on Observable. I have  seen this issue here, but it was different one.
