### ISSUE TITLE
CanDeactivate Bug when multi click back button of browser with "return false" of canDeactivate

### ISSUE THREAD

**Issue by suplch** [angular/angular#15978] opened 2017-04-14 05:51 UTC
**Current behavior**
Example 
history of browser stack is  [#/index/index  ->  #/product/product -> #/product/choice  -> #/product/pay -> #/product/success  ]

``` TypeScript
/// Follow CanDeactivate implement is for path #/product/success of SuccessComponent

canDeactivate(component: SuccessComponent, currentRoute: ActivatedRouteSnapshot, currentState: RouterStateSnapshot, nextState?: RouterStateSnapshot) {
        console.log(currentState.url);
        console.log(nextState.url)
        return false;
}
```

```
First click back button on browser
console output “/product/success”
console output “/product/pay”             // expect “/product/pay” so this is ok

Second click back button on browser
console output “/product/success”
console output “/product/choice”        // expect “/product/pay”  so this is error 

Third click back button on browser
console output “/product/success”
console output “/product/product”       // expect “/product/pay”  so this is error

Fourth click back button on browser
console output “/product/success”
console output “/index/index”             // expect “/product/pay”  so this is error
```
Last click back button on browser
this time browser leave angular app even “return false” of canDeactivate be execute;

I feel when I click back button of browser, history stack of browser pop a history item even “return false” of method canDeactivate

**Expected behavior**

Recovery history of browser when "return false" of method canDeactivate, just like no click back button of browser.
**Minimal reproduction of the problem with instructions**
When config a CanDeactivate for a router, even "return false" of canDeactivate be execute,  multi click back button of browser, we will reproduction this problem

**Please tell us about your environment:**
angular-cli tool
* **Angular version:** 4.0.2

* **Browser:** [all browser ]

* **Language:** [ TypeScript 2.x ]

* **Node (for AoT issues):** `node --version` =   node: 7.0

**Comment by zoechi** [comment] 2017-04-14 06:18
Please provide a Plunker that allows to reproduce.

**Comment by suplch** [comment] 2017-04-14 07:11
please visit  http://plnkr.co/edit/YL329mc7PxMYvx7ad5eK?p=preview

**Comment by zkorz** [comment] 2017-07-02 18:30
I managed to get around the issue with the following code:

```
if(deactivateAllowed){
    return true;
} else {
    history.pushState({}, "", currentState.url);
    return false;
}
```
Where `currentState` is the third argument of `canDeactivate` and is of type `RouterStateSnapshot`

Tested in Chrome only.

**Comment by ChrisProlls** [comment] 2017-10-06 13:10
Any news about this ? we reproduce the same error ...

**Comment by jlsanchezsanz** [comment] 2018-05-30 07:20
Any news? I'm having the same issue.

**Comment by oblivion-hymns** [comment] 2018-09-04 14:54
Our team is seeing the same issue in multiple applications; one of them is using Angular 5 and the other is using Angular 6. I've tried also throwing a window:beforeunload listener on there in addition to the CanDeactivate (to cover cases such as refreshing the page) but coverage is spotty at best. As of now, CanDeactivate really doesn't seem to be doing the job it's supposed to be doing. It requires at least one -- more than likely several -- hacks to truly, fully prevent a user from going back in the application.

**Comment by flensrocker** [comment] 2019-04-04 14:16
Using Angular 7.2.11 - still broken...

**Comment by SvenBudak** [comment] 2019-11-28 18:17
Here another Stackblitz to reproduce: https://github.com/angular/components/issues/16748#issuecomment-525921453

**Comment by StephenPaul** [comment] 2020-02-05 13:06
Any movement on this? I remember last investigating this bug years ago. Surprised there is no progress being made.

**Comment by atscott** [comment] 2020-05-26 22:52
Duplicate of #13586

**Closed by atscott** 2020-05-26 22:52 UTC
Labels: comp: router, freq2: medium, severity3: broken, state: confirmed, triage #1, type: bug/fix
