### ISSUE TITLE
installing angular unable to install angular

### ISSUE THREAD

**Issue by pardhasaradhihulk** [angular/angular#28694] opened 2019-02-13 16:37 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...

## 🔬 Minimal Reproduction

 https://stackblitz.com/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by gkalpak** [comment] 2019-02-13 17:01
I assume this is a duplicate of #28695.

**Closed by gkalpak** 2019-02-13 17:01 UTC
