### ISSUE TITLE
Mismatch between Angular4 docs and code for Validators in @angular/forms package

### ISSUE THREAD

**Issue by Technohacker** [angular/angular#15729] opened 2017-04-03 17:21 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Angular API reference states that there is only a `required` ValidatorFn in the class `Validators` but source code defines required, requiredTrue, compose, composeAsync, email and null.

**Expected behavior**

API reference reflects the Validators defined.

**Minimal reproduction of the problem with instructions**

Compare Angular API reference and Validators class source.

**What is the motivation / use case for changing the behavior?**

Fixing an error in documentation. 

**Please tell us about your environment:**

N/A

* **Angular version:** 4.0.0

* **Browser:** N/A

 
* **Language:** all

This can be considered a bug report for the Angular documentation.

**Comment by DzmitryShylovich** [comment] 2017-04-03 17:24
Duplicate of https://github.com/angular/angular/issues/15551

**Closed** 2017-04-03 17:25 UTC
