### ISSUE TITLE
If and Switch directives not working with dart2js

### ISSUE THREAD

**Issue by andresaraujo** [angular/angular#1569] opened 2015-04-28 01:56 UTC
I don't know if its a known issue but `*if` and `switch` are not working in dart2js (work on Dartium as expected), Chrome console throws an Invalid argument(s) error.

example app:

```dart
import 'package:angular2/angular2.dart';

// These imports will go away soon:
import 'package:angular2/src/reflection/reflection.dart' show reflector;
import 'package:angular2/src/reflection/reflection_capabilities.dart'
show ReflectionCapabilities;

void main() {
  // Temporarily needed.
  reflector.reflectionCapabilities = new ReflectionCapabilities();
  bootstrap(App);
}


@Component(selector: 'app')
@View(template: '<p *if="show">test</p>', directives: const [If])
class App {
  bool show = true;
}
```

Produces the following error:
```javascript
Uncaught Uncaught Error: Invalid argument(s): "if" is not a valid (qualified) symbol name
Stack Trace:
Invalid argument(s): "if" is not a valid (qualified) symbol name
    at dart.wrapException (http://localhost:63342/ng2_bug_if/web/main.dart.js:3963:15)
    at dart.Symbol.static.Symbol_validatePublicSymbol (http://localhost:63342/ng2_bug_if/web/main.dart.js:23817:17)
    at ReflectionCapabilities.dart.ReflectionCapabilities.setter$1 (http://localhost:63342/ng2_bug_if/web/main.dart.js:87285:73)
    at Reflector.dart.Reflector.setter$1 (http://localhost:63342/ng2_bug_if/web/main.dart.js:17795:44)
    at dart.setterFactory (http://localhost:63342/ng2_bug_if/web/main.dart.js:20821:71)
    at ElementBinderBuilder.dart.ElementBinderBuilder.bindProperty$2 (http://localhost:63342/ng2_bug_if/web/main.dart.js:21158:53)
    at ViewSplitter.dart.ViewSplitter._parseTemplateBindings$2 (http://localhost:63342/ng2_bug_if/web/main.dart.js:19214:44)
    at ViewSplitter.dart.ViewSplitter.process$3 (http://localhost:63342/ng2_bug_if/web/main.dart.js:19181:16)
    at CompileControl.dart.CompileControl.internalProcess$4 (http://localhost:63342/ng2_bug_if/web/main.dart.js:18026:14)
    at CompilePipeline.<anonymous> (http://localhost:63342/ng2_bug_if/web/main.dart.js:18186:60)
```

Tested on alpha 20

**Comment by kegluneq** [comment] 2015-04-29 18:44
I haven't had a chance to try and reproduce this yet, but from the stack trace it does not look like this is a result of transformed code. This may be a duplicate of #1295.

I'm traveling for the next couple of days but will take a closer look when I can.

**Comment by jbdeboer** [comment] 2015-05-08 16:13
I have a test that is using ```if``` and passing in dart2js; there may be something more subtle here.

**Comment by andresaraujo** [comment] 2015-05-08 18:40
I just tested it on alpha 22 and still fails, `pub build` doesn't show errors but running the page in chrome results in the above output, maybe I'm missing something?

Here is a sample project that fails [https://github.com/andresaraujo/ng2_if_for](https://github.com/andresaraujo/ng2_if_for)

**Comment by kegluneq** [comment] 2015-05-08 20:23
This works for me on `pub serve` the first time but refresh fails -- this may be the same issue @jakemac53 is seeing in https://github.com/angular/angular/issues/1617

`pub build` works for me

**Comment by mhevery** [comment] 2015-06-01 22:27
This has to do with `foo.if` not being valid in Dart. We have renamed to `ng-if` no longer an issue.

**Closed by mhevery** 2015-06-01 22:27 UTC
Labels: comp: dart-transformer, cust: GT
