### ISSUE TITLE
Value of Input tag does not show up if the value is bigger than 1000 if type=number

### ISSUE THREAD

**Issue by jdang67** [angular/angular#18632] opened 2017-08-10 14:46 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

if the  testValue >= 1000 then I cannot see number inside the input text box.

## Expected behavior

Input text box ( type =number) should display any valid number regards the value too large or too small it's.

## Minimal reproduction of the problem with instructions
`<input type="number" class="form-control" [ngModel]="testValue|number:'1.2-2'" (ngModelChange)="UpdateValues($event)" >`

## Environment

<pre><code>
Angular version: 1.0.0

Browser:
- [x ] Chrome (desktop) version 59.0.3071.115 (Official Build) (64-bit)
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: node: 7.9.0
- Platform:  Windows 7

Others:

</code></pre>

**Comment by pkozlowski-opensource** [comment] 2017-08-10 15:38
I'm sorry but reported issues require a plunker reproducing the problem.

If this issue persists, please create a plunker using this template and describe the difference between the expected and current behavior and create a new issue: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue

**Comment by ericmartinezr** [comment] 2017-08-10 16:42
I think this should be revisited after the dependency on the Intl api has been removed (https://github.com/angular/angular/pull/18284) (the DecimalPipe depends on it).

@ocombe thoughts?

**Comment by ocombe** [comment] 2017-08-10 16:48
Isn't it just a problem with the css of your input? If the value is too long, you should increase the size of the input

**Comment by jdang67** [comment] 2017-08-10 19:46
Please check the punker, I can reproduce the problem here  in this punker

http://plnkr.co/edit/wI4bl7HiZ6iTKY7eYAlJ?p=preview

thanks,
Jdang

**Comment by jnizet** [comment] 2017-08-12 17:05
@jdang67 The decimal pipe transforms the number into an i18ned string. And you're trying to use that i18ned string as the model for an input of type number. That doesn't make much sense. The model of an input of type number should be a number, not a string. 

The reason, AFAIK, it doesn't work with large numbers and happens to work with smaller ones is that when the number is larger, there is a separator for thousands (i.e. in English, the number becomes the string '1,234.75', which can't be transformed to a valid number by the browser).

**Comment by jdang67** [comment] 2017-08-12 19:54
Well, I do not agree with you guys about  the term 'using i18 string as the model type number'. To me showing a number with decimal places are very common in software industry from spreadsheet to database etc..  and I don't think this is too hard to fix this bug.

So, now  have  numbers and want to show only 2 decimals all time. Can you give me a hint how to do this? I don't want to change input type to 'text' because I have to do a lot validations.

thanks,

Jdang

**Comment by trotyl** [comment] 2017-08-13 06:08
Possibly Angular should provide type-checking for `NgModel` and throw an error in this condition.

**Comment by tytskyi** [comment] 2017-08-13 11:10
@jdang67  see plunker with no angular http://plnkr.co/edit/wjjtJo2EOH1DTdCLNSmN?p=preview

Value with comma simply ignored.

As the solution you could implement your own pipe, that does what you want, but does not add commas.

**Comment by ocombe** [comment] 2017-08-14 07:51
Sorry but like @jnizet said you should only use i18n to show translated strings (in text), that includes the number pipe, because i18n numbers are not consistent across languages: it's only meant to be read in this particular locale.
If you need mathematic numbers (such as required by the input number), then you need to use generic numbers that are always the same in your code.
If you really want to show the number in the locale and still use an input number then you should do your own directive or component to deal with that, but it's not something that will be "fixed" by angular. If anything, it should be fixed by browsers that create the input number.

**Closed by ocombe** 2017-08-14 07:51 UTC
Labels: comp: common, flag: can be closed?

**Comment by jdang67** [comment] 2017-08-14 12:21
Hi all,
It's good to show the number in the locale  with group separators,   but the decimals is crucial.  May be the best option for us right now is write our own pipe ( is this what angular should does to help million of developers like us? )

Jdang
