### ISSUE TITLE
Provide  a mock service using TestBed

### ISSUE THREAD

**Issue by ihachani** [angular/angular#10727] opened 2016-08-12 09:46 UTC
**I'm submitting a ...**  (check one with "x")

```
[ x] bug report
```

**Current behavior**
TestBed providers looks for the dependencies of my original service although my mocked service have none of them. 
And sometimes when running the test I get:
This test module uses the component DummyRestApiComponent which is using a "templateUrl", but they were never compiled. Please call "TestBed.compileComponents" before your test.
Although I am calling TestBed.compileComponents.

**Expected/desired behavior**
Before RC5 addProviders used the mock without looking for its dependencies which reduces the knowledge the component in test knows about the service.

**Reproduction of the problem**

```
    TestBed.configureTestingModule({
      declarations: [DummyRestApiComponent],
      providers: [
        // ConfigurationService,
        {provide: DummyRestApiService, useClass: MockDummyRestApiTestService},
        DummyRestApiComponent,
      ],
      imports: [FormsModule, HttpModule]
    });
```

 Vs The old way

```
addProviders([
       DummyRestApiComponent,
       {provide: DummyRestApiService, useClass: MockDummyRestApiTestService},
     ]);
```

No need for configuration Service.

Before each test I am using

```
 beforeEach(async(() => {
      TestBed.compileComponents().catch(error => console.error(error));
    }));
```

And when testing

```
 it('should create an instance', async(() => {
        var fixture = TestBed.createComponent(DummyRestApiComponent);
        fixture.detectChanges();
        expect(fixture.debugElement.componentInstance).toBeTruthy();
      }
    ));
```
- **Angular version:** 2.0.0-rc.5

Using Karma + Jasmine (Angular CLI 1.0.0-beta.10)
- **Language:** [Typescript]

**Comment by mdymel** [comment] 2016-08-12 15:43
I have the same issue: 
`
beforeEach(() => {
            TestBed.configureTestingModule({
                declarations: [CompaniesComponent],
                providers: [
                    {provide: CompaniesService, useClass: MockCompaniesService},
                    LoggingService
                ],
                imports: [FormsModule, HttpModule]
            });
        });
`
And it still uses CompaniesService.

**Comment by blacksonic** [comment] 2016-08-18 14:22
@ihachani @mdymel have you tried ```configureCompiler```? Regarding the docs it has also a providers property.

**Comment by rbnzdave** [comment] 2016-08-19 00:14
Having the same trouble here, its like it isnt instantiating the mock service to provide it. Will try this configureCompiler thing.

**Comment by rbnzdave** [comment] 2016-08-19 00:19
nah same issue. infact using configureCompiler changed the value to undefined instead of null.

**Comment by blacksonic** [comment] 2016-08-19 11:15
Are those classes ```Injectable```? Tried ```useValue```, ```useClass```, ```useFactory``` and everything is working great.

**Comment by mraible** [comment] 2016-08-19 14:16
I can confirm that I was able to mock a service with `TestBed` as well. Here's a code snippet:

```javascript
describe('Component: Search', () => {
  let mockSearchService: MockSearchService;
  let mockActivatedRoute: MockActivatedRoute;
  let mockRouter: MockRouter;

  beforeEach(() => {
    mockSearchService = new MockSearchService();
    mockActivatedRoute = new MockActivatedRoute({'term': 'peyton'});
    mockRouter = new MockRouter();

    TestBed.configureTestingModule({
      declarations: [SearchComponent],
      providers: [
        {provide: SearchService, useValue: mockSearchService},
        {provide: ActivatedRoute, useValue: mockActivatedRoute},
        {provide: Router, useValue: mockRouter}
      ],
      imports: [FormsModule]
    });
  });
});
```

I've also used `useClass` with success:

```javascript
beforeEach(() => {

  TestBed.configureTestingModule({
    providers: [
      {
        provide: Http, useFactory: (backend: ConnectionBackend, defaultOptions: BaseRequestOptions) => {
        return new Http(backend, defaultOptions);
      }, deps: [MockBackend, BaseRequestOptions]
      },
      {provide: SearchService, useClass: SearchService},
      {provide: MockBackend, useClass: MockBackend},
      {provide: BaseRequestOptions, useClass: BaseRequestOptions}
    ]
  });
});
```

I wrote up a tutorial on using the new testing infrastructure in RC5 since there doesn't seem to be much documentation available.

http://gist.asciidoctor.org/?github-mraible%2Fng2-demo%2F%2FREADME.adoc

**Comment by another-guy** [comment] 2016-08-19 16:19
I'm using Angular2 with TypeScript and observing the following error when trying to run my unit tests:

> TypeError: Cannot read property 'configureTestingModule' of undefined.


Test services
```
@Injectable()
export class DemoRootService {
    constructor(private dependency: DemoDependencyService) { }
    search(id: number): string { return this.dependency.test(); }
}

@Injectable()
export class DemoDependencyService {
    constructor() { }
    test() { return "dep!"; };
}
```

Unit test code

```
import { TestBed } from '@angular/core/testing';
import { Http } from '@angular/http';
import { inject } from '@angular/core/testing';
import { DemoRootService, DemoDependencyService } from './demo.service';

describe('DemoRootService', () => {
    beforeEach(() => {
        try {
            TestBed.configureTestingModule({
                providers: [
                    { provide: DemoRootService, useClass: DemoRootService },
                    { provide: DemoDependencyService, useClass: DemoDependencyService }
                ]
            });
        } catch (e) {
            alert(e); // <-  TypeError: Cannot read property 'configureTestingModule' of undefined.
        }
    });
});
```

**Comment by timshelley** [comment] 2016-08-23 21:56
I was having this issue as well, however I noticed that my @Component metadata still had the providers array defined.  Moving this providers array into my applications @NgModule solved this issue for me.  

From what I've seen so far, there is no way to override (mock) a provider specified in a @Component metadata.

**Comment by SaltyDH** [comment] 2016-08-31 03:40
@timshelley Just hit this exact same issue, I moved the @Injectable service from the component's providers array into the @NgModule providers array where the component has been declared. The test immediately passed.

Interestingly, this affected the call to TestBed.createComponent only, calls to TestBed.get([service]) still correctly resolved the substituted service.

**Comment by sgrinich** [comment] 2016-09-08 21:36
Are you all initializing your TestBed?

Like so: 

`import { TestBed } from '@angular/core/testing/test_bed';
import { BrowserDynamicTestingModule, platformBrowserDynamicTesting } from '@angular/platform-browser-dynamic/testing';

TestBed.initTestEnvironment(
  BrowserDynamicTestingModule,
  platformBrowserDynamicTesting()
);`

**Comment by timshelley** [comment] 2016-09-08 22:02
@sgrinich I'm initializing my test environment with: 
```
import {TestBed} from '@angular/core/testing';
import {BrowserDynamicTestingModule, platformBrowserDynamicTesting} from '@angular/platform-browser-dynamic/testing';

TestBed.initTestEnvironment(BrowserDynamicTestingModule, platformBrowserDynamicTesting());
```

**Comment by lephyrus** [comment] 2016-09-13 17:17
@timshelley From what I understand, declaring providers on the component level is still supported and useful, so moving them to the module level seems like changing your implementation just to make the test work, which I didn't want to do. This works for me with rc.6:
```
TestBed.overrideComponent(MyComponent, {
  set: {
    providers: [{ provide: SomeService, useValue: myMock }]
  }
});
```
With the current state of documentation around testing, it is a really frustrating exercise to come up with decent solutions for non-trivial cases. I hope this changes soon.

**Comment by zoechi** [comment] 2016-09-14 06:00
https://github.com/angular/angular.io/pull/2198#issuecomment-246463040

**Comment by lotusboy** [comment] 2016-09-15 08:54
I have a similar issue with providing mock values for unit tests.
We are developing an Angular2 app which will be served from Salesforce and Salesforce will provide 2 variables to the Angular2 app. I have cut the code down to highlight the issue.

**salesforce.library.ts**

```
import { OpaqueToken } from '@angular/core';

export let SalesforceGlobalsToken: any = new OpaqueToken('SalesforceGlobals');
export let PricingControllerToken: any = new OpaqueToken('PricingController');
```

**pricing-ui.module.ts**

```
@NgModule({
    imports: [
        BrowserModule
    ],
    declarations: [
        PricingUiAppComponent
    ],
    bootstrap: [ PricingUiAppComponent ],
    providers: [
        { provide: PricingControllerToken, useValue: PricingController },
        { provide: SalesforceGlobalsToken, useValue: SalesforceGlobals }
    ]
})
export class PricingUiAppModule { }
```

**pricing-ui.component.ts**

```
@Component({
    selector: 'pricing-ui-app',
    templateUrl: 'pricing-ui.component.html',
    styleUrls: ['pricing-ui.component.css']
})
export class PricingUiAppComponent {
    public returnURL: string = '/' + this.salesforceGlobals.OpportunityId;
    public isHeaderCollapsed: boolean = false;
    title = 'Pricing UI';

    constructor(
        @Inject(SalesforceGlobalsToken) private salesforceGlobals: any,
        @Inject(PricingControllerToken) private pricingController: any
    ) {}
}
```

**pricing-ui.component.spec.ts**

```
describe('App: PricingUi', () => {

    // mock globals
    let salesforceGlobals: SFDC.SalesforceGlobals = {
        BaseURL: '/',
        OpportunityId: 'xxxx',
        QuoteId: 'yyyy',
        Language: 'zz-ZZ'
    };

    // mock controller
    let pricingController: SFDC.PricingController;

    beforeEach(() => {
        TestBed.configureTestingModule({
            declarations: [
                PricingUiAppComponent
            ],
            providers: [
                { provide: SalesforceGlobalsToken, useValue: salesforceGlobals },
                { provide: PricingControllerToken, useValue: pricingController }
            ]
        });
    });

    it('should create the app', () => {
        let fixture = TestBed.createComponent(PricingUiAppComponent);
        expect(fixture).toBeTruthy();
    });
});
```

When I run **ng test** it reports that **PricingController** is not defined. Investigating this, it appears that the mocks provided in the unit test are not being passed through and so the @NgModule reverts to use the **PricingController** and **SalesforceGlobals** which would be passed in from Salesforce.

This worked in RC4.

**Comment by cbeldacap** [comment] 2016-09-23 07:20
What about the MockService itself? What will it have inside? Some data that matches with the real service?

(thank you in advance)

**Comment by chris-jones-pixitmedia** [comment] 2016-10-18 07:42
I have the same issue in 2.0.0

If I specify a provider in configureTestingModule, it doesn't get injected into the test - it falls back on the concrete class.

If I call overrideComponent immediately after calling configureTestingModule and specify the exact same provider, it is injected as expected.

**Comment by AshMcConnell** [comment] 2016-11-09 15:49
This seems to be happening for us too with 2.1.2.  I can't seem to get the mock to appear in the class under test.

`providers:    [
        {provide: AuthenticationService, useValue: authServiceMock },
        {provide: Router, useValue: routerStub }
      ]`

I have put a console.log in the constructor and it looks like the real service: -
`'Constructor', AuthenticationService{_http: Http{_backend: XHRBackend{_browserXHR: ..., _baseResponseOptions: ..., _xsrfStrategy: ...}, _defaultOptions: BaseRequestOptions{method: ..., headers: ..., body: ..., url: ..., search: ..., withCredentials: ..., responseType: ...}}, loggedIn: false}
`
I tried @chris-jones-pixitmedia workaround but no luck for me

**Comment by zoechi** [comment] 2016-11-09 16:40
I guess you need to use `fixture.overrideProviders()` if you want to override a provider that is provided on the component you test.

**Comment by AshMcConnell** [comment] 2016-11-11 08:55
Hi @zoechi `fixture.overrideProviders()` doesn't seem to exist for me in angular 2.1.2

**Comment by AshMcConnell** [comment] 2016-11-11 11:56
Using overrideComponent worked for me (I had called it wrong), but setting the providers with TestBed.configureTestingModule is **broken**.

Here is the code for clarity: -

`TestBed.configureTestingModule({
      imports: [FormsModule, HttpModule],
      declarations: [LoginComponent],
    }).overrideComponent(LoginComponent, {
      set: {
        providers: [
          {provide: AuthenticationService, useValue: authServiceMock},
          {provide: Router, useValue: routerStub}
        ]
      }}
      ).compileComponents();`

Thanks for the tip @chris-jones-pixitmedia

**Comment by lephyrus** [comment] 2016-11-11 12:10
@AshMcConnell I don't think it's broken. If you declare the providers in `@NgModule`, you provide the mock using `configureTestingModule`. If you declare the providers in `@Component`, you provide the mock using `overrideComponent`. As discussed above: https://github.com/angular/angular/issues/10727#issuecomment-241893194, https://github.com/angular/angular/issues/10727#issuecomment-246755214

**Comment by AshMcConnell** [comment] 2016-11-11 13:13
Aha, of course - that makes sense, sorry I missed that, I thought all providers were meant to be set with TestBed.configureTestingModule.  Thanks for your help @lephyrus

**Comment by chris-jones-pixitmedia** [comment] 2016-11-11 13:19
Makes sense. Is that in the official documentation? I completely missed it

**Comment by Whipgit** [comment] 2016-11-16 19:13
Thank you @chris-jones-pixitmedia and @AshMcConnell 
I believe this is the same issue here: #10787

For those on a similar quest, I've had better success with **useClass** than with useValue.

**Comment by bluehenry** [comment] 2017-01-13 06:35
overrideComponent works for me.

**Comment by ReneVallecillo** [comment] 2017-02-04 02:24
Heads up everyone, try to stop ng test before trying the overridecomponent method. For some reason changes on the overidemodule method providers were not picking up on save.

**Comment by vdzundza** [comment] 2017-02-09 08:52
What's estimated time to fix this bug ?

**Comment by AresDev** [comment] 2017-02-11 23:28
@timshelley solution was the only one that worked for me.

**Comment by seawave23** [comment] 2017-04-26 09:02
I needed to overwrite the providers for the Module (in the configureTestingModule part), overwriting them for the component was not enough.

**Comment by Bartosz-D3V** [comment] 2017-09-28 11:23
This is still an issue and it makes it nearly impossible to provide a service (only) inside a component as the tests will fail due to not provided mock service.

**Comment by mdymel** [comment] 2017-10-26 16:02
I think I have found a solution. I was trying to mock a service with a method returning observable. It didn't work until I specified in the mock a method that does return an observable: 

```
  class MyServiceMock {
    getList() { return Observable.of({}); }
  }
```

**Comment by szigya** [comment] 2017-11-07 21:18
+1, this should really be fixed

**Comment by chris-jones-pixitmedia** [comment] 2017-11-08 09:15
I think this is working as expected, but it's not very well documented. If you provide a service (or something else) to your test bed using the overrideComponent function, e.g.:

```
  beforeEach(async(() => {
    TestBed
      .configureTestingModule({
        declarations: [HelloWorldComponent]
      })
      .overrideComponent(HelloWorldComponent, {
        set: {
          providers: [
            { provide: HelloWorldService, useValue: new HelloWorldServiceMock() }
          ]
        }
      })
      .compileComponents();
  }));
```
In order to reference the injected service, you don't use the test bed's injector (TestBed.get(HelloWorldService) to get it, you use the component's injector:

```
  beforeEach(async(() => {
    TestBed
      .configureTestingModule({
        declarations: [HelloWorldComponent]
      })
      .overrideComponent(HelloWorldComponent, {
        set: {
          providers: [
            { provide: HelloWorldService, useFactory: () => new HelloWorldService(null) }
          ]
        }
      })
      .compileComponents().then(() => {
          const componentFixture = TestBed.createComponent(HelloWorldComponent);
          const service = componentFixture.componentRef.injector.get(HelloWorldService);
      });
  }));
```

**Comment by szigya** [comment] 2017-11-08 16:45
@chris-jones-pixitmedia You are right. It's kinda obvious after applying your solution, but also quite bad api. It would be better to have a @Mock like in Java development :))). So, thank you!

**Comment by vikerman** [comment] 2018-01-26 21:59
TestBed.overrideProvider can override providers irrespective of the level at which the original providers have been defined.

@kyliau - Please add this to your example repo as part of #12409

**Closed by vikerman** 2018-01-26 21:59 UTC
Labels: comp: testing, type: bug

**Comment by theSuiGenerisAakash** [comment] 2018-06-07 18:12
You guys could also be spying incorrectly like I was!

Check out this [answer which talks about how to create spy](https://stackoverflow.com/questions/40142300/cannot-read-property-subscribe-of-undefined-after-running-npm-test-angular-2)

**Comment by rkorrelboom** [comment] 2018-07-12 11:57
Another option is to `TestBed.get(<effects>)` in your test or describe instead of in the beforeEach at root level like so:

```
describe('SomeEffects', () => {
  let actions$: Observable<any>;
  let effects: SomeEffects;
  let store: SpyObj<Store<SomeState>>;

  beforeEach(() => {
    TestBed.configureTestingModule({
      providers: [
        SomeEffects,
        provideMockActions(() => actions$),
        {
          provide: Store,
          useValue: jasmine.createSpyObj('store', [ 'select' ])
        }
      ]
    });

    // IMPORTANT: Don't get the effects here to delay instantiation of the class until needed! 
    store = TestBed.get(Store);
  });

  it('should be created', () => {
    effects = TestBed.get(SomeEffects); // Instance is created here
    expect(effects).toBeTruthy();
  });

  describe('someSimpleEffect$', () => {
    beforeEach(() => {
      effects = TestBed.get(SomeEffects); // Instantiate in before each of nested describe for tests that don't need constructor mocks
    });
  });

  describe('someWithLatestEffect$', () => {
    it('should instantiate SomeEffects After initializing the mock', () => {
      const action = new SomeAction();
      const completion = new SomeActionSuccess();

      store.select.and.returnValue(cold('r', { r: true )); // Initialize mock here

      effects = TestBed.get(SomeEffect); // Instantiate SomeEffects here so we can use the mock

      actions$ = hot('a', { a: action });
      const expected = cold('b', { b: completion });

      expect(effects.someWithLatestEffect$).toBeObservable(expected);
    });
  })
})
```

**Comment by jstreicheryatta** [comment] 2019-07-23 14:16
Sorry to open this up again, but i have an issue with the provided solution to override component:

When i override the component the tests of the actual service will fail with an unhelpful message:
Uncaught TypeError: You provided 'undefined' where a stream was expected. You can provide an Observable, Promise, Array, or Iterable. thrown

When you debug the test it actually runs through succesfully, so i suppose the error occurs someone during test cleanup?

If i do not override the component that uses the service, the service test will run fine.

So in the end it seems i can only ever test one or the other.

It is really weird that tests are influencing each other in this way.
