### ISSUE TITLE
why signal can set value in computed with Promise?

### ISSUE THREAD

**Issue by dcvsling** [angular/angular#50968] opened 2023-07-07 06:12 UTC
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

NG0600 is not warning with Promise 
```
computed(async () => this.display.set(await this.entry()));
```
minimal case is in stackblitz

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-bgdi3g?file=src%2Fmain.ts

### Please provide the exception or error you saw

```true
no exception, i thought there would be NG0600
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
## StackBlitz 
new angular project
---
## dev env
Angular CLI: 16.1.0
Node: 18.14.2
Package Manager: npm 9.7.1
OS: win32 x64

Angular: 16.1.1
... animations, cdk, common, compiler, compiler-cli, core, forms
... material, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1601.0
@angular-devkit/build-angular   16.1.0
@angular-devkit/core            16.1.0
@angular-devkit/schematics      16.1.0
@angular/cli                    16.1.0
@nguniversal/builders           16.1.0
@nguniversal/express-engine     16.1.0
@schematics/angular             16.1.0
ng-packagr                      16.1.0
rxjs                            7.8.1
typescript                      4.9.5
```

### Anything else?

i want to know why it is work? and is it allow?
why or why not allow?

**Comment by pkozlowski-opensource** [comment] 2023-07-07 08:52
The NG0600 error is raised when setting a signal in a computation function. In your case the computation function returns a new Promise - no signal is set at this point. Then, 2s later a timer fires and writes to a signal - this is perfectly legal as the timer is _not_ part of the computation.

I presume that you were experimenting with asynchronous computed functions which are not part of the signals story. Here in this stackblitz a computation function returns a promise - which is the same value as a number, a string or any other object.

I hope that it clarifies the situation. I'm going to close this issue as things works as designed.

**Closed by pkozlowski-opensource** 2023-07-07 08:52 UTC

**Comment by wartab** [comment] 2023-07-07 08:55
The point of computed and effects signals is to react to a signal change, not to change the value of other writable signals. One of the reasons is notably to avoid infinite loops. 

The reason why what you do "works" is because the signals do not care if your computed/effect callback returns a Promise or not and will not await a Promise if that's what is returned. It can therefore not detect that you are setting a signal within that callback.

Overly simplified, what's happening is this:
```
let shouldFail = false;
function computed(callback) {
    let shouldFail = true;
    callback();
    let shouldFail = false;
}

function setSignal(value) {
    if (shouldFail) {
        throw new Error();
    }

    // set value
}
```
As you can see, the Promise is completely ignored and its code will be excuted after `shouldFail` goes back to false.
Those errors are there to protect you from accidentally setting signals when you shouldn't. 

So what you do should be avoided and completely
