### ISSUE TITLE
FormControlDirective and FormControlName do not call setDisabledState on ControlValueAcessor instances when the CVA is added and is enabled

### ISSUE THREAD

**Issue by jermowery** [angular/angular#35309] opened 2020-02-10 20:13 UTC
# 🐞 bug report

### Affected Package

@angular/forms

### Is this a regression?

Not that I know of.

### Description

When you add a CVA to a form via the FormControlDirective directive or FormControlName directive with reactive forms and the CVA has implemented setDisabledState the the setDisabledState and the FormControl instance is enabled, setDisabledState is not called on the CVA instance, it is however called with the FormControl is disabled.

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-issue-repro2-3fagzc

## 🌍  Your Environment

**Angular Version:**
<pre><code>

google3 head

</code></pre>

**Anything else relevant?**

Nope

**Comment by AndrewKushnir** [comment] 2020-05-27 21:07
FYI this issue is potentially related to #13856.

**Comment by AndrewKushnir** [comment] 2021-06-03 00:53
Just a quick note: it looks like #22556 was also caused by this issue.

**Comment by dylhunn** [comment] 2021-06-14 18:00
Accidentally referred to this bug in an unrelated PR, reopening.

**Comment by dylhunn** [comment] 2021-06-15 23:37
An update for interested parties: we started investigating this bug. The fix is relatively simple, as demonstrated in the PR above, but it is unfortunately very breaking (it causes hundreds of failures in google3, and probably will be equally breaking externally).

We're trying to determine the common reasons for breakage, and whether they can be cleanly fixed (e.g. with `ng update`, or by preserving the old behavior behind a flag).

**Comment by MaximSagan** [comment] 2021-06-18 03:37
@AndrewKushnir Are you sure that the `fieldset` issues that you closed in favor of this (#13856) are really the same issue?

It strikes me that in that case, although the element is functionally disabled with a `:disabled` pseudoclass that can be used for styling, there are no DOM APIs (that I know of) that allow us to simply retrieve the element's "true" disabled status (i.e. the status that causes the `:disabled` pseudoclass to be applied, rather than simply what the element's own `[disabled]` attribute says) or changes in this status.

There was an [interesting workaround](https://github.com/angular/angular/issues/13856#issuecomment-365125679) in the closed issue that involved adding directives to all fieldset (and more) elements, but probably the most efficient method I've found is something like this.

```css
.ng-control:disabled {
    animation: disabled 1ms;
}
.ng-control:not(:disabled) {
    animation: enabled 1ms;
}
@keyframes disabled{ from {}; to {}; }
@keyframes enabled { from {}; to {}; }
```

```ts

@Directive(...)
export class FormContolDirective {

  ...

  @HostListener('animationstart', ['$ev'])
  onAnimationStart(event: AnimationEvent): void {
    if (event.animationName === 'disabled' && !this._disabled) {
      this.disable();
    } else if (event.animationName === 'enabled' && this._diabled {
      this. enable();
    }
  }
}
```

**Comment by dylhunn** [comment] 2021-06-30 16:20
@thw0rted the breakage is tests that expected the old (incorrect) behavior. As you note, it's not trivial to fix with `ng update`.

**Comment by moniuch** [comment] 2021-12-17 23:06
You might want to look into [this issue](https://github.com/angular/angular/issues/13856) which I reported back in 2017. I believe it contains some good observations from a lot of users. Closed because due to - sigh - inactivity.

**Comment by tzeH** [comment] 2022-02-14 08:53
When I replace a FormGroup, the ControlValueAccessor's setDisabled method is not called. Resulting in a control that looks enabled but should actually be disabled. I think that's the same Issue.

This worked around it for me (after adding a few tweaks for strict compiler settings): https://github.com/angular/angular/issues/22556#issuecomment-420283363

And here is a unit test to show the problem

```ts
import { Component } from '@angular/core';
import { ComponentFixture, TestBed, waitForAsync } from '@angular/core/testing';
import { ControlValueAccessor, FormControl, FormGroup, NG_VALUE_ACCESSOR, ReactiveFormsModule } from '@angular/forms';
import { By } from '@angular/platform-browser';
import { FixToggleDisableFormControlDirective } from './fix-toggle-disable-form-control.directive';

@Component({
  selector: 'app-test-cva',
  template: 'works!',
  providers: [
    { provide: NG_VALUE_ACCESSOR, useExisting: TestCvaComponent, multi: true }
  ]
})
class TestCvaComponent implements ControlValueAccessor {
  disabled?: boolean;

  setDisabledState?(isDisabled: boolean): void {
    this.disabled = isDisabled;
  }
  writeValue(obj: any): void { }
  registerOnChange(fn: any): void { }
  registerOnTouched(fn: any): void { }
}

@Component({
  selector: 'app-test-form',
  template: '<div [formGroup]="form"><app-test-cva formControlName="test"></app-test-cva></div>'
})
class TestFormComponent {
  form: FormGroup = new FormGroup({
    test: new FormControl({ value: 'some value', disabled: true })
  });
}

describe('Reactive Form', () => {
  let component: TestFormComponent;
  let control: TestCvaComponent;
  let fixture: ComponentFixture<TestFormComponent>;

  beforeEach(waitForAsync(() => {
    TestBed.configureTestingModule({
      declarations: [
        TestCvaComponent,
        TestFormComponent,
      ],
      imports: [ReactiveFormsModule]
    }).compileComponents();
  }));

  beforeEach((done) => {
    fixture = TestBed.createComponent(TestFormComponent);
    component = fixture.componentInstance;
    control = fixture.debugElement.query(By.css('rudi-test-cva')).componentInstance;
    fixture.detectChanges();
    fixture.whenStable().then(done);
  });

  it('calls setDisabled when FormCOntrol gets replaced', () => {
    // We started with a disabled form - angular called setDisabled just fine.
    expect(control.disabled).toBeTrue();

    component.form.enable();
    fixture.detectChanges();
    // enable()-call results in setDisabled just fine
    expect(control.disabled).toBeFalse();

    component.form = new FormGroup({
      test: new FormControl({ value: 'some disabled value', disabled: true })
    });
    fixture.detectChanges();
    // Replacing the FormGroup, setDisabled is not (!) called, so this fails:
    expect(control.disabled).toBeTrue();
  });
});
```

**Comment by muuvmuuv** [comment] 2022-04-06 13:09
The current workaround for us is to remove the control and re-add it after a timeout:

```ts
  ngOnChanges(changes: SimpleChanges): void {
    if (changes.control && !changes.control.firstChange) {
      this.control = null
      setTimeout(() => {
        this.control = changes.control.currentValue
      }, 17 /* my lucky number */)
    }
  }
```

**Comment by dylhunn** [comment] 2022-07-11 23:44
This is very breaking, but it would be great to fix, as the large number of duplicate issues indicates significant user pain.

**Comment by dylhunn** [comment] 2022-09-12 17:10
@jermowery We are triaging candidates for v15, and are discussion this in particular. It was hugely breaking in g3, but we might be able to land the fix behind a package-level flag. Is this something that's still a priority to fix for you?

**Comment by moniuch** [comment] 2022-09-12 17:42
The following code shows problem with fieldset (with `ngDefaultControl` on it) that fails to disable its children controls

```
import { Component } from '@angular/core';
import { FormBuilder } from '@angular/forms';

@Component({
  selector: 'my-app',
  template: `
  <form [formGroup]="form">
    <fieldset formGroupName="user">
      <legend>Fieldset</legend>
      <input type="text" formControlName="name" />
      <input type="checkbox" formControlName="check"> Anything
    </fieldset>
  </form>

  <button (click)="disableFieldset()">Disable Fieldset</button>
  <button (click)="enableFieldset()">Enable Fieldset</button>
  <button (click)="disableControlsExplicitly()">Disable Controls</button>
  <button (click)="enableControlsExplicitly()">Enable Controls</button>

  <pre>
  <code>{{form.value | json }}</code>
  </pre>

`,
  styleUrls: ['./app.component.css'],
})
export class AppComponent {
  form = this.fb.group({
    user: this.fb.group({
      name: '',
      check: false,
    }),
  });

  constructor(private fb: FormBuilder) {}

  disableFieldset() {
    // disabled fieldset should disable its child controls
    this.form.get('user').disable();
  }

  enableFieldset() {
    this.form.get('user').enable();
  }

  disableControlsExplicitly() {
    // this provides the expected behavior: 'name' disappears from form.value
    this.form.get('user.name').disable();

    // this.form.get('user.check').disable(); // <-- interestingly: this line breaks the disabling of 'name'
  }

  enableControlsExplicitly() {
    this.form.get('user.name').enable();
  }
}

```

**Comment by jermowery** [comment] 2022-09-12 19:46
I wouldn't call the issue a priority for our team since we have worked around this for several years.

I do think it is very surprising behavior of people when using forms so I do think that the default behavior should be corrected, and personally think that fixes for confusing Forms behaviors should be prioritized

**Comment by dylhunn** [comment] 2022-10-10 17:13
merge-assistance: submit with [this g3 local mod](https://critique.corp.google.com/cl/480105160) to disable the fix internally. Submit and sync with great care because of the local mod.

**Comment by dylhunn** [comment] 2022-10-10 17:14
Whoops, this is the issue, not the PR :)

**Closed** 2022-10-11 16:03 UTC
Labels: type: bug/fix, comp: forms, state: has PR, state: confirmed, P2, canonical
