### ISSUE TITLE
Support for .invalid operator in html to validate html min/max value

### ISSUE THREAD

**Issue by b-anani** [angular/angular#40216] opened 2020-12-21 04:45 UTC
# 🚀 feature request

### Description
.invalid at the moment supports `required` flag, and regex `pattern` flags among others but does not validate for `min` and `max` 
### Describe the solution you'd like
Would be nice to have support for this, if html has `min="1"` and in the field one were to put `0` then it would be nice if I did something like `<div *ngIf="field.invalid>...</div>` for that div to appear because the input is in fact invalid.  

### Describe alternatives you've considered
 At the moment I have been using complicated regex patterns in order to work around this issue but support of this would make life significantly easier.

**Comment by petebacondarwin** [comment] 2020-12-21 09:50
I think that this feature request is actually for a `MinValidator` directive equivalent to the https://angular.io/api/forms/MinLengthValidator directive.

**Comment by AndrewKushnir** [comment] 2020-12-21 20:41
@b-anani, as Pete mentioned, it looks like the problem that you described comes from the fact that there is no `min` and `max` validators available in Forms package. There is a ticket which describes that, see #16352.

The proposed solution for now is to implement your own version of `min` and `max` validators. You can have a look at the PR #39063 to find an example of these validators (however that PR also contains some refactoring, so it might be easier to use [existing validators](https://github.com/angular/angular/blob/master/packages/forms/src/directives/validators.ts#L336-L402) as a pattern for your custom ones).

Closing this ticket as a duplicate of #16352. Please let us know if we are missing something and this ticket should be reopen.

Thank you.

**Closed by AndrewKushnir** 2020-12-21 20:41 UTC
Labels: P5, comp: forms, feature
