### ISSUE TITLE
Provide JSON.parse reviver and JSON.stringify replacer custom implementation in HttpClient to customize the serialization

### ISSUE THREAD

**Issue by ahelmel** [angular/angular#56147] opened 2024-05-29 07:31 UTC
### Which @angular/* package(s) are relevant/related to the feature request?

common

### Description

A possibility to provide a custom JSON serialization implementation via an Injection token for the JSON.parse and JSON.stringify methods. This will allow the developers to customize the serialization from Dtos to Doman/Frontend models in Angular:
```
interface UserDto {
  ...
  createdOn: string;
  ...
}

interface User {
  ...
  createdOn: Date;
  ...
}

...

getUsers(): Observable<User[]> {
  return this.http.get<UserDto[]>(...).pipe(...);
}
````

### Proposed solution

```
const HTTP_CLIENT_JSON_PARSE_REVIVER = new InjectionToken('...'); => https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse#reviver
const HTTP_CLIENT_JSON_STRINGIFY_REPLACER = new InjectionToken('...'); => https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#replacer
```

Somewhere in HttpClient service:
```
...
JSON.parse(..., jsonParseReviverFn)
...
JSON.stringify(..., jsonStringifyReplacerFn)
...
```

### Alternatives considered

I know that this functionality can be achieved using Angular Interceptors but what about this solution?

**Comment by JoostK** [comment] 2024-05-29 07:59
Closing as duplicate of #48167 since there is sufficient overlap in functionality.

**Closed by JoostK** 2024-05-29 07:59 UTC
