### ISSUE TITLE
Router stops working after failing to load feature module in webpack/AOT

### ISSUE THREAD

**Issue by angeor2** [angular/angular#13575] opened 2016-12-19 19:21 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
The client has been AOT compiled and bundled using Webpack2. Lazy loading has been implemented using angular-router-loader. Before navigating to a lazy loaded module I force offline mode and then try to navigate. Routing fails, as expected, because it can't load the relevant chunk. The error is 'Loading chunk [chunk number] failed'. After switching back online router no longer works (either by router.navigate or by routerLink directive). Router does not resolve neither reject the navigation command.
The error logged is `Error: Uncaught (in promise): Error: Loading chunk 1 failed`

**Expected behavior**
The router shouldn't stop working.

**Minimal reproduction of the problem with instructions**
Angular2 client has a feature module, that is lazy loaded.
e.g. `{ path: 'lazy', loadChildren: './+lazy/lazy.module#LazyModule' }`
webpack is configured appropriately:
          `{
                test: /\.ts$/,
                loaders: [
                    'awesome-typescript-loader',
                    'angular2-template-loader',
                    'angular-router-loader?aot=true' 
                ],
            }`
Before navigating to the lazy module switch to Offline (e.g. by using Chrome developer tools). Then switch back Online and try to navigate with the router again.

**What is the motivation / use case for changing the behavior?**
The app should be fully functional when the connection is restored, the user should not be forced to reload the app.

**Please tell us about your environment:**
Working on Windows 10, Visual studio 2015, Asp.net core 

* **Angular version:** 
Has been reproduced in 2.2.4 & 2.3.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Tested only on Chrome 54
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 2.0.10

* **Node (for AoT issues):** `node --version` =   
node 5.6.0

**Comment by DzmitryShylovich** [comment] 2016-12-19 19:22
Duplicate of https://github.com/angular/angular/issues/12289

**Closed** 2016-12-19 19:49 UTC
