### ISSUE TITLE
Forms: better type for formState

### ISSUE THREAD

**Issue by ahnpnl** [angular/angular#39903] opened 2020-12-01 09:28 UTC
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/forms

### Description

Better type for `formState` arg for `FormControl`/`FormBuilder` constructor. Current the type is any and I had to google to find out what are the possible values. So far, I've only known this
```
new FormControl({
     value: 'foo description',
     disabled: true,
}),
```
Maybe there are more possible properties ?

Also documentation doesn't mention about what are the possible values https://angular.io/api/forms/FormControl#constructor

### Describe the solution you'd like
 If you have a solution in mind, please describe it.

- `formState` should have better type, not `any`.

- Documentation should be updated

### Describe alternatives you've considered

I couldn't find any workarounds.

**Comment by destus90** [comment] 2020-12-01 10:09
Work is already underway on this https://github.com/angular/angular/pull/38406

**Comment by ahnpnl** [comment] 2020-12-01 10:10
thanks for the info 👍

**Comment by AndrewKushnir** [comment] 2020-12-01 19:07
Hi @ahnpnl, this looks like a duplicate of #13721 (so I'm closing this ticket) and type improvements to Forms are on our [roadmap](https://angular.io/guide/roadmap#better-developer-ergonomics-with-strict-typing-for-angularforms). Please subscribe to #13721 for further updates. Thank you.

**Closed by AndrewKushnir** 2020-12-01 19:07 UTC
Labels: comp: forms
