### ISSUE TITLE
docs: change cli command syntax to green on black console style

### ISSUE THREAD

**Issue by jenniferfell** [angular/angular#26657] opened 2018-10-22 17:10 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[X ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[X ] Other... Please describe: CLI-AIO command reference generation dgeni and css
</code></pre>

## Current behavior

In the CLI command reference, the command syntax is shown as black text, code font, on white, similar to the Angular API reference. 

![cli-command-ref-black-white](https://user-images.githubusercontent.com/31675481/47306885-df498100-d5ea-11e8-84bc-a4448c81a17c.png)

## Expected behavior

In the CLI command reference, the command syntax is shown as green text, code font, on black, similar to the command line (terminal/console) treatment in the guides.  This would more clearly indicate that these are command line syntax and not API, file contents, etc. 

https://angular.io/guide/docs-style-guide#code-example
```
<code-example language="sh" class="code-shell">
  npm start
</code-example>
```

![cli-command-ref-green-black](https://user-images.githubusercontent.com/31675481/47306902-e40e3500-d5ea-11e8-8e59-2da23330e2e5.png)

## Minimal reproduction of the problem with instructions

https://angular.io/cli/add

## What is the motivation / use case for changing the behavior?

Discussions within the team and survey of GDEs  overwhelmingly preferred the console style.

![cli-cmd-ref-survey-gde](https://user-images.githubusercontent.com/31675481/47306909-ea041600-d5ea-11e8-8803-cd647df51e15.png)

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by gkalpak** [comment] 2018-10-22 17:15
Isn't this a duplicate of #26574?

**Comment by ajitsinghkaler** [comment] 2019-12-07 10:59
@gkalpak Can I take this

**Comment by gkalpak** [comment] 2019-12-09 09:52
Thx for volunteering, @ajitsinghkaler. However, I don't think this is ready to be taken on.
This seems to be a duplicate of #26574, which has a longer (ongoing) discussion (but no definite decision afaict).]

I am going to close this as a duplicate of #26574 (let's keep the discussion there).

**Closed by gkalpak** 2019-12-09 09:52 UTC
Labels: comp: docs, comp: docs-infra, docsarea: cli and config, freq3: high, subtype: docs-design, type: feature
