### ISSUE TITLE
Http in angular2/http (modules/angular2/src/http/http.ts) should use this.request in get/post/put/delete/patch/head methods

### ISSUE THREAD

**Issue by ribizli** [angular/angular#6001] opened 2015-12-18 10:24 UTC
It would make subclassing Http easier, since only the ```request``` method should be overwritten. Anyway this is the proper OOP design.

```typescript
get(url: string, options?: RequestOptionsArgs): Observable<Response> {
  return this.request(new Request(mergeOptions(this._defaultOptions, options,
                                                               RequestMethod.Get, url)));
}
```

**Comment by larrifax** [comment] 2015-12-18 11:56
Related: https://github.com/angular/angular/issues/2684

**Comment by robwormald** [comment] 2015-12-19 03:15
dupe of #2684 - we'll do this.

**Closed by robwormald** 2015-12-19 03:15 UTC
