### ISSUE TITLE
How to stop downloading service worker cached resources on each & every page reload in Angular?

### ISSUE THREAD

**Issue by nkdweb** [angular/angular#45600] opened 2022-04-12 14:31 UTC
### Which @angular/* package(s) are the source of the bug?

service-worker

### Is this a regression?

No

### Description

Every time the user refreshes the application, the Angular service worker checks for updates to the application by looking for updates to the ngsw.json manifest. If an update is found, it is downloaded and cached automatically, and will be served the next time the application is loaded.

There are 2 scenario

- Scenario 1 - When user navigate from one page to another using navigation links(menu), then Angular won't download any cached files again from service worker, if it is cached already.
- Scenario 2 - When user reload the page, then it will download the cached resources from service worker once again for each and every page reload/refresh.

There would be page loading time difference between page navigation & page reload. So how to eliminate downloading of cached resources from service worker again and again on page refresh/reload, If there are no updated version in ngsw.json manifest.

**Comment by gkalpak** [comment] 2022-04-13 12:55
As @ansh-ag, this sounds like a configuration issue. The SW should not download all resources on each navigation/reload. It only downloads them when there is a new version on the server (and even then, it is smart enough to not re-downloaded the ones that are cached and haven't changed since the previous version).

I am going to close this, since it is not actionable in its current state. If you still think this might be an issue with the Angular ServiceWorker, please open a new issue and provide (preferably minimal) reproduction, so we can investigate.

**Closed by gkalpak** 2022-04-13 12:55 UTC
Labels: needs reproduction, comp: service-worker
