### ISSUE TITLE
compiler-cli typecheck fails if filepath is wrong without useful log

### ISSUE THREAD

**Issue by hoefken** [angular/angular#39040] opened 2020-09-29 13:11 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/compiler-cli

### Is this a regression?

 No 

### Description

 
The checker for file from the ngts/typecheck package (https://github.com/angular/angular/blob/master/packages/compiler-cli/src/ngtsc/typecheck/src/checker.ts#L119) does not throw a descriptive error, when the filename and class/interface name is not the same when using path aliases. It just throws generic error message <pre>"ERROR in TypeError: Cannot read property 'hasInlines' of undefined". </pre>

After adding a few lines to error out the filepath I was able to pinpoint my error.

Wanted solution: the checker should print a descriptive error instead of a generic one.

The error only occurs, when the wrongly typed file is on an tsconfig path alias!

A proposed change is here https://github.com/angular/angular/commit/035c771dd87822777ef596eccbc50db2b3fa65fa 

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-compiler-cli-path-alias-error?file=src/app/other/other.component.ts

## 🔥 Exception or Error
<pre>ERROR in TypeError: Cannot read property 'hasInlines' of undefined
    at TemplateTypeCheckerImpl.getDiagnosticsForFile (C:\Users\hoefken\Documents\infoapp\InfoApp-Frontend\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\checke
r.js:107:28)
    at NgCompiler.getTemplateDiagnostics (C:\Users\hoefken\Documents\infoapp\InfoApp-Frontend\node_modules\@angular\compiler-cli\src\ngtsc\core\src\compiler.js:487:106)
    at NgCompiler.getDiagnostics (C:\Users\hoefken\Documents\infoapp\InfoApp-Frontend\node_modules\@angular\compiler-cli\src\ngtsc\core\src\compiler.js:141:97)
    at NgtscProgram.getNgSemanticDiagnostics (C:\Users\hoefken\Documents\infoapp\InfoApp-Frontend\node_modules\@angular\compiler-cli\src\ngtsc\program.js:152:45)
    at checkDiagnostics (C:\Users\hoefken\Documents\infoapp\InfoApp-Frontend\node_modules\@ngtools\webpack\src\diagnostics.js:47:27)
    at Object.gatherDiagnostics (C:\Users\hoefken\Documents\infoapp\InfoApp-Frontend\node_modules\@ngtools\webpack\src\diagnostics.js:86:13)
    at AngularCompilerPlugin._emit (C:\Users\hoefken\Documents\infoapp\InfoApp-Frontend\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:1081:54)
    at AngularCompilerPlugin._update (C:\Users\hoefken\Documents\infoapp\InfoApp-Frontend\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:872:50)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async AngularCompilerPlugin._make (C:\Users\hoefken\Documents\infoapp\InfoApp-Frontend\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:749:13)
<code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre>10.0.6<code>

</code>C:\Users\hoefken\Documents\infoapp\InfoApp-Frontend>ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 10.0.6
Node: 12.10.0
OS: win32 x64

Angular: 10.0.10
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.6
@angular-devkit/build-angular     0.1000.6
@angular-devkit/build-optimizer   0.1000.6
@angular-devkit/build-webpack     0.1000.6
@angular-devkit/core              10.0.6
@angular-devkit/schematics        10.0.6
@angular/cdk                      10.1.3
@angular/cli                      10.0.6
@angular/flex-layout              10.0.0-beta.32
@angular/material                 10.1.3
@ngtools/webpack                  10.0.6
@schematics/angular               10.0.6
@schematics/update                0.1000.6
rxjs                              6.6.2
typescript                        3.9.7
webpack                           4.43.0
</pre>

**Anything else relevant?**

**Comment by hoefken** [comment] 2020-09-29 13:17
error pinpoint posted by @shyamal890 as well in https://github.com/angular/angular/issues/38582#issuecomment-681127905_

**Comment by JoostK** [comment] 2020-09-29 14:34
So the issue here is not with the path mappings, but rather the inconsistent capitalisation of the source files (`Einrichtungstraeger` vs `EinrichtungsTraeger`). I am getting TypeScript compile errors on macOS due to this, but that won't be the case in Windows unless you enable `forceConsistentCasingInFileNames` as a TypeScript compiler option.

I'll try to reproduce in Windows to see why the type checker chokes on this, as this doesn't appear to be an issue on macOS.

**Comment by JoostK** [comment] 2020-10-18 13:00
I tried to reproduce this in a Windows VM with parts extracted from the Stackblitz repo, but it did not crash for me. Can anyone provide a GitHub repo that reproduces the issue, as there might be some configuration differences as to why I'm unable to reproduce.

**Comment by jar240** [comment] 2020-10-22 18:05
I'm experiencing this error too (Windows). To reproduce, create a component with class name "ThisIsMyComponent" and name the file "thisIsMyComponent.ts". In my case, this was the problem.

To troubleshoot it (as suggested in this thread's [predecessor ](https://github.com/angular/angular/issues/38582#issuecomment-680905193) by @JoostK ), I added this line of code

`console.log('sfPath: ' + sfPath);`
`console.log('fileRecord is (un)defined? ' + typeof fileRecord);`

...above the offending line (`if (fileRecord.hasInlines) {`)
![image](https://user-images.githubusercontent.com/6794643/96911362-c2144b00-146e-11eb-9040-bacab062f555.png)

to the file: .\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\checker.js

...this will output "`fileRecord is object`" for all the "good" files, and "`**fileRecord is undefined**`" for the offending file.

**Comment by mamor52** [comment] 2020-10-23 00:22
> 
> 
> I'm experiencing this error too (Windows). To reproduce, create a component with class name "ThisIsMyComponent" and name the file "thisIsMyComponent.ts". In my case, this was the problem.
> 
> To troubleshoot it (as suggested in this thread's [predecessor ](https://github.com/angular/angular/issues/38582#issuecomment-680905193) by @JoostK ), I added this line of code
> 
> `console.log('sfPath: ' + sfPath);`
> `console.log('fileRecord is (un)defined? ' + typeof fileRecord);`
> 
> ...above the offending line (`if (fileRecord.hasInlines) {`)
> ![image](https://user-images.githubusercontent.com/6794643/96911362-c2144b00-146e-11eb-9040-bacab062f555.png)
> 
> to the file: .\node_modules@angular\compiler-cli\src\ngtsc\typecheck\src\checker.js
> 
> ...this will output "fileRecord is object" for all the "good" files, and "**fileRecord is undefined**" for the offending file.

Great debugging, thank you very much

**Comment by AdrienMeyepa** [comment] 2020-11-04 02:32
Didn't work for me

**Comment by AdrienMeyepa** [comment] 2020-11-04 02:32
![image](https://user-images.githubusercontent.com/22002334/98062485-1533c800-1e89-11eb-872a-9a4db969ef32.png)

**Comment by AdrienMeyepa** [comment] 2020-11-04 02:35
need help please

**Comment by jar240** [comment] 2020-11-07 16:01
> need help please

Um... if you look at your screenshot, you can see the problematic file. Here's your screenshot annotated for clarity Looks like the issue is with your file **show-com.component.ts**. Look at the class declaration -- if it's not exactly "**ShowComComponent**", then this is likely the issue. (when you you the Angular cli to generate a skeleton component, it sets the filename correctly based on the classname you declare.

This should get you unstuck, but this bug for which this issue was opened remains.

![image](https://user-images.githubusercontent.com/6794643/98445914-6b527680-20e8-11eb-91d2-ab9ea807e1e7.png)

**Comment by AdrienMeyepa** [comment] 2020-11-07 16:11
okay I will give it a try .. thanks

**Comment by AdrienMeyepa** [comment] 2020-11-09 17:02
I still can't find the issue!

**Comment by jar240** [comment] 2020-11-10 02:04
> I still can't find the issue!

What have you tried, exactly? You're not providing much info... I found your Angular10_CRUD repo, but its missing the files in your screenshot. Why don't you create a new branch, push the broken changes to github so I (we) can take a look?

(apologies to @hoefken -- it's not my intention to hijack the thread)

**Comment by AdrienMeyepa** [comment] 2020-11-10 05:31
I am new to git so ... I will try push the missing file

**Comment by AdrienMeyepa** [comment] 2020-11-10 06:53
@jar240 I did wetransfer you the file

**Comment by AdrienMeyepa** [comment] 2020-11-11 09:31
any good news?

**Comment by JoostK** [comment] 2020-11-11 10:00
I am still unable to reproduce, even on native Windows, so there's still no route to a solution.

@AdrienMeyepa could you please try setting the "forceConsistentCasingInFileNames" compiler option in `tsconfig.json`:

```json
{
  "compilerOptions": {
    ...
    "forceConsistentCasingInFileNames": true,
```

**Comment by AdrienMeyepa** [comment] 2020-11-11 16:56
I will try that yeah

**Comment by Dunkhan** [comment] 2020-12-16 13:44
In case this helps anyone, after reading through this thread I tried adding "forceConsistentCasingInFileNames". This resulted in a build error:
File name '[...]/app/shared/charts/shared-context-spectrum-chart/shared-context-spectrum-chart.component.ts' differs from already included file name '[...]/app/Shared/Charts/shared-context-spectrum-chart/shared-context-spectrum-chart.component.ts' only in casing.

note the casing difference on  the app/shared folder
The line of code pointed to by this error did not contain that folder name:
import { SharedContextSpectrumChartComponent } from './shared-context-spectrum-chart.component';

I deleted the import and retyped it, then saved and it built. I then hit ctrl-z a few times and built again and still everything was fine.

To investigate further I did a git reset --hard, and repeated the whole process (it was a merge from origin/master that caused this state) watching to see what tracked files were changed. I was able to reproduce the issue and the solution. However git did not register any changed files between the working and non-working state.

As far as I am aware the folder app/shared was never written with an upper case s, and in any case that folder existed long before the branch where this issue occurred (the file with the issue was new in the branch however).
Given that simply refreshing the import fixed the issue, to diagnose/fix this issue it seems sensible to look into the process that occurs when a folder is renamed, if any, and also what happens when an import is added to a file. 
Is there some metadata somewhere that stores some information about imports?

I am still thoroughly confused about why git reset caused the problem to occur again despite there being apparently no file changes related to the issue.

**Comment by Dunkhan** [comment] 2020-12-16 17:03
So on further investigation I found an import of this class in another file, one not mentioned in the error message. This import listed more of the path of the file and included the shared folder, with an upper case S.  Fixing this seems to have resolved the problem. It seems that this is a bug in angular then. Even with consistent file casing turned on, the compiler error listed the import line that was correct and not the one that was incorrectly capitalised.

**Comment by JoostK** [comment] 2021-04-15 21:06
Are people still seeing having this issue? I've never been able to reproduce this on Windows nor OS X, with several compiler options enabled/disabled but without luck. Given that there hasn't been recent activity in this issue, has this been silently solved in the meantime?

**Comment by lukebooroo** [comment] 2021-04-20 11:44
I'm also getting this issue. Haven't been able to resolve yet.

**Comment by Dunkhan** [comment] 2021-04-20 11:55
The solution for me was to do a regex search for all imports of that component, and just go through them with a fine tooth comb looking for differences. For me it was a capitalisation error which I think is likely the general case as outright spelling errors seem to be treated differently.

**Comment by mtwinux** [comment] 2021-09-27 08:16
I added this code to the checker.js (line 121) to point the file responsible of this error : 

var fileRecord = this.state.get(sfPath);
**if (!fileRecord) {
    console.error("Can't find the file [%s]. Check case issues for this file in your code.", sfPath);
}**
var typeCheckProgram = this.typeCheckingStrategy.getProgram();

Then, when i had the filename i search for it in my imports and quickly find one that got an uppercase letter. That was it.

Maybe we need to simply add a log to inform the user to check the file...

**Comment by JoostK** [comment] 2021-10-02 20:35
I am going to close this as we've never been able to reproduce this issue.

Please open a new issue _with reproduction_ so we can get it resolved.

**Closed by JoostK** 2021-10-02 20:35 UTC
Labels: type: bug/fix, needs reproduction, freq1: low, comp: compiler, windows, P3, compiler: template type-checking
