### ISSUE TITLE
Error: Cannot determine the module for class AppComponent - ngc compilation AOT

### ISSUE THREAD

**Issue by applecool** [angular/angular#15264] opened 2017-03-17 23:16 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

ngc compilation doesn't generate the ngfactory files but errors out.

**Expected behavior**

generate the respective ngfactory files.

**Minimal reproduction of the problem with instructions**

My project structure:
```
src/
 |___app
 |    |__ app.component.html
 |    |__ app.component.ts
 |    |__ app.module.ts
 |
 |___ home
      |__ home.component.html
      |__ home.component.ts
      |__ home.module.ts

```
I have two tsconfig files for each module i.e., app and home as follows:
app's tsconfig file:
```
{
  "compilerOptions": {
    "target": "es5",
    "module": "es2015",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": ["es2015", "dom"],
    "noImplicitAny": true,
    "suppressImplicitAnyIndexErrors": true
  },

  "files": [
    "src/app/app.module.ts",
    "src/main.ts"
  ],

  "angularCompilerOptions": {
   "genDir": "aot",
   "skipMetadataEmit" : false
 }
}

```
home's tsconfig file:
```
{
  "compilerOptions": {
    "target": "es5",
    "module": "es2015",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": ["es2015", "dom"],
    "noImplicitAny": true,
    "suppressImplicitAnyIndexErrors": true
  },
 
  "files": [
    "src/home/home.module.ts"
  ],
 
  "angularCompilerOptions": {
   "genDir": "aot",
   "skipMetadataEmit" : true
 }
}
```

Running ngc in app module generates their respective ngfactory files whereas running ngc in the home module gives an error as following:
```
$ npm run build:home

> angular-quickstart@1.0.0 build:view /Users/harsha/Documents/Dem/quickstart
> ngc -p tsconfig-viewer.json

Error: Cannot determine the module for class AppComponent in /Users/harsha/Documents/Dem/quickstart/src/app/app.component.ts!
    at analyzeAndValidateNgModules (/Users/harsha/Documents/Dem/quickstart/node_modules/@angular/compiler/bundles/compiler.umd.js:24942:19)
    at AotCompiler.compileAll (/Users/harsha/Documents/Dem/quickstart/node_modules/@angular/compiler/bundles/compiler.umd.js:24663:22)
    at CodeGenerator.codegen (/Users/harsha/Documents/Dem/quickstart/node_modules/@angular/compiler-cli/src/codegen.js:30:14)
    at codegen (/Users/harsha/Documents/Dem/quickstart/node_modules/@angular/compiler-cli/src/main.js:8:81)
    at Object.main (/Users/harsha/Documents/Dem/quickstart/node_modules/@angular/tsc-wrapped/src/main.js:47:16)
    at main (/Users/harsha/Documents/Dem/quickstart/node_modules/@angular/compiler-cli/src/main.js:14:16)
    at Object.<anonymous> (/Users/harsha/Documents/Dem/quickstart/node_modules/@angular/compiler-cli/src/main.js:30:5)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
Compilation failed
```

**What is the motivation ?**

I am trying to generate ngfactory files for both the app and home modules independently and then want to use rollup or any other module builder to bundle them separately so that I can dynamically load the bundles whenever I need them in my app using system loader or any other loaders.

**Please tell us about your environment:**

OSX El Capitan 10.11.6, VS Code, npm@4.0.5, node@7.4.0, typescript@2.0.10

* **Angular version:** 2.4.0

* **Browser:** [N/A]

 
* **Language:** [ TypeScript 2.0.10 ]

* **Node (for AoT issues):** `node --version` =   7.4.0

**Comment by DzmitryShylovich** [comment] 2017-03-17 23:17
angular 2.x doesn't support typescript 2.1+

use ts 2.0.10 or upgrade angular version

**Comment by applecool** [comment] 2017-03-17 23:19
@DzmitryShylovich I am sorry I am using 2.0.10. I updated my post.

**Comment by andy5638** [comment] 2017-07-22 10:14
I have the same issue.

I am trying to build web application with angular(4.3.1) AOT with angular/router lazy-loading.
Since some of modules will be loaded later so it will not be imported in app.module but also needs to be pre-compiled.

my code: [https://github.com/andy5638/captaastra](https://github.com/andy5638/captaastra)

I have AppComponent, HomeComponent and CategoryComponent. In AppComponent there is a <router-outlet> and loads HomeComponent as pre-loading. AppComponent and And HomeComponent are under AppModule and CategoryComponent is under CategoryModule. Now I want to load CategoryComponent as lazy-load when user navigates.

So I countered exactly same error message even I already declared CategoryComponent into CategoryModule.

**Comment by funkizer** [comment] 2017-07-24 11:36
Tried to clean my code a bit by defining imports, declarations and exports as arrays before @NgModule, so I can just concat them together inside @NgModule, and avoid some copy-pasting. Got the same error when AOT-compiling. With JIT, this works fine.

This is my shared module which declares any components I use in lazy-loaded modules around the app. Code that produces the error with AOT is commented out. Uncommented code works with both AOT and JIT:

https://gist.github.com/funkizer/13cc290d7ee91863b556fcfdfa06274c

So dunno if this is a bug, but I always prefer to avoid copy-paste-code which makes me a bit sad that it doesn't work.  :D

**Comment by dani-inside** [comment] 2017-09-28 14:29
I also wanted to clean up my code like @funkizer, by creating separate ts files for pages, components etc. and then just concat them within the AppModule. JIT compiler is doing fine, but AOT compiler is throwing lots of exceptions. Is there any recommendation on how keep these things clean? Thanks in advance.

**Comment by alxhub** [comment] 2020-05-28 21:07
Closing this as "can't reproduce" - the linked gist is no longer available, and this is almost certainly related to the specific project configuration or some typo in the code or config.

**Closed by alxhub** 2020-05-28 21:07 UTC
Labels: comp: compiler, engine: ve, freq2: medium, severity3: broken, state: Could not reproduce, triage #1, type: bug/fix
