### ISSUE TITLE
<div contenteditable = "true"></ div>

### ISSUE THREAD

**Issue by isopen** [angular/angular#23847] opened 2018-05-11 07:19 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
I have to do something like this.
https://github.com/isopen/soc/blob/master/frontend/src/app/page/wall/wall.component.html

## Expected behavior
Please see the current implementation. It's like a bicycle.
I would like to be able to send value along with the form `<div contenteditable = "true"></ div>`
Preferably through your framework. It would be great. Perhaps there are solutions already. If there is a hint, please tell me.
At the moment I have to write strange enough:
https://github.com/isopen/soc/blob/master/frontend/src/app/page/wall/wall.component.ts:48

## Minimal reproduction of the problem with instructions
```
git clone https://github.com/isopen/soc
cd backend
docker-compose up
cd frontend
npm install 
npm start
```

## What is the motivation / use case for changing the behavior?
Vital

## Environment

Angular version: 5.2.4

Regards

**Comment by trotyl** [comment] 2018-05-11 07:27
Duplicate of https://github.com/angular/angular/issues/9796

**Closed** 2018-05-11 07:29 UTC
