### ISSUE TITLE
(select) @Output is triggered when text in input is selected

### ISSUE THREAD

**Issue by SamVerschueren** [angular/angular#23603] opened 2018-04-30 07:44 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
I have a dumb component with a `select` output.

```ts
@Component({
  selector: 'hello',
  template: `
    <input type="text">

    <button (click)="select.next()">Trigger</button>
  `
})
export class HelloComponent  {
  @Output() select = new EventEmitter();
}
```

When I subscribe to the select output of this component `<hello (select)="..."></hello>`, the select output is triggered upon two actions.

1. When clicking the button
2. When highlighting some text in the input field

Here's a screencast of the behaviour

![kapture 2018-04-30 at 9 35 34](https://user-images.githubusercontent.com/1913805/39418412-8f98158c-4c5a-11e8-8075-f4ba240a38f0.gif)

## Expected behavior
It might be expected, but it looks weird and it caused a hard to debug issue in our application.

## Minimal reproduction of the problem with instructions
I created a reproduction on stackblitz

https://stackblitz.com/edit/angular-pjpc2f?file=app%2Fhello.component.ts

## Environment

Tested on Chrome and Firebox but probably a bug in every browser.

<pre><code>
Angular version: 5.2.8

Browser:
- [x] Chrome (desktop) version 65
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version 59.0.2
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.9.4
- Platform: macOS

Others:
/

**Comment by trotyl** [comment] 2018-04-30 09:33
Duplicate of https://github.com/angular/angular/issues/4059, `(event)` will listen to both `@Ouput()` and DOM events.

**Comment by SamVerschueren** [comment] 2018-04-30 11:35
I did not know that `select` was a DOM event, so this is quite annoying as it can lead to unexpected behaviour. Thanks for linking the duplicate issue @trotyl!

@mgechev Might be nice if codelyzer could catch this and throw a failure when detected :).

**Comment by mhevery** [comment] 2018-05-03 22:35
This works as expected as explained above.

**Closed by mhevery** 2018-05-03 22:35 UTC
Labels: comp: core & compiler

**Comment by rafaelss95** [comment] 2018-05-03 23:36
@SamVerschueren There's already an rule to prevent this: http://codelyzer.com/rules/no-output-named-after-standard-event/

**Comment by SamVerschueren** [comment] 2018-05-05 03:59
Oh, totally missed that one. Thanks @rafaelss95 !
