### ISSUE TITLE
Significant slow down in JIT after upgrading to version 4

### ISSUE THREAD

**Issue by shlomiassaf** [angular/angular#15955] opened 2017-04-13 12:38 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Initial bootstrap time doubled (JIT mode)

### Angular Version 2:
![image](https://cloud.githubusercontent.com/assets/5377501/25004832/f6e9e6e4-205e-11e7-9575-8f632c1e1c3b.png)

### Angular Version 4:
![image](https://cloud.githubusercontent.com/assets/5377501/25004841/fe9ca2be-205e-11e7-9662-9b172cafa9bb.png)

The `JitCompiler._compileComponents` takes a lot of time.
internally looks like generating the source maps is heavy.

**Please tell us about your environment:**
OSX, webpack 2.2.1, ts 2.2.2
 
* **Angular version:** 4.0.0

* **Browser:** Chrome 57.0.2987.133 (64-bit)
 
* **Language:** ts 2.2.2

cc @tbosch

**Comment by shlomiassaf** [comment] 2017-04-13 12:39
Upgrade process was minimal but involved upgrading about 4 other packages

**Comment by ericmartinezr** [comment] 2017-04-13 12:43
Hey @shlomiassaf , probably related https://github.com/angular/angular/issues/15748 ? Otherwise ignore this comment.

**Comment by kemsky** [comment] 2017-04-13 12:46
Could you also test performance in IE or Edge? Change detection is very slow in my app.

**Comment by shlomiassaf** [comment] 2017-04-13 12:51
@ericmartinezr I wouldn't consider opening an issue for a 1 sec gap on JIT.

But this is from 3.5 sec bootstrap on V2 to 7+ sec bootstrap on V4 - that is a big issue.

Clearly something is off, either my webpack setup or I dont know...  
Problem is, I checkout the revision before the upgrade, its 3.5s after the upgrade 7+ secs but the upgrade didn't include significant change other then v4...

This is not a small app, it comes with material and a baseline page for all of the material components we restyled... + a lot of pages :)

**Comment by kemsky** [comment] 2017-04-13 13:20
This is profile for our application, using 4.0.2:
![bootstrap](https://cloud.githubusercontent.com/assets/3826972/25005977/cd9c75ae-2063-11e7-8069-ccb67e9be879.png)

`Bootstrap time 6480.77 ms`

I had to put application bundle into `<script async>` otherwise it stalls on parsing bundle (3+ MB)

Also, chrome can cache pre-compiled script, so you need to clear cache and run test again.

**Comment by sod** [comment] 2017-04-13 13:43
Is it one single `NgModule` with 179 components? Think about it, angular parses everything upfront, even if you only use 10 of those 179 components.

When we switched to webpack, we split the app in multiple `NgModules` that are lazy loaded via `@angular/router`.

I can confirm our app is as slow as yours
![image](https://cloud.githubusercontent.com/assets/905328/25006949/0d676b30-205f-11e7-971e-e4749b0c1388.png)

But as JIT only has to process two NgModules (the root app with @angular/router and the app for the current page) there is only a small part of the app evaluated on startup.

App size: 72 Components ... but split into 10 modules, so max ~15 Components have to be evaluated per page.

**Comment by kemsky** [comment] 2017-04-13 14:00
@sod, i know that everything is processed at start up, honestly i want to avoid lazy-loading at all costs (it actually will not improve user experience, one big delay will be replaced with many smaller, but still very noticeable delays... there are some tricks i.e. using preloader, but amount of work needed for implementation is too big, just incomparable with outcome), i would rather switch to AOT.

**Comment by shlomiassaf** [comment] 2017-04-13 14:16
@kemsky You should reconsider your conclusions.

There are some facts you mention, which are simply wrong.

Replacing 1 big delay with many small once has a huge, huge impact. 
Most of the times those small delays are not noticeable.

The amount of work to implement lazy loading and preloading is small, super small...  
The only use case where it will be a big issue is if you structured your app in a wrong way so 
you now have to refactor into a module structure.

>  i would rather switch to AOT.

Well, its not a question, you **must** use AOT in production.

**Comment by sod** [comment] 2017-04-13 14:22
I thought we were talking here about development issues only. Of course we do AOT in production. It's a magnitude faster.

But if your single bundle is already 3 MB in JIT, its gonna be huge in AOT! I strongly suggest looking into splitting it apart. It'll be faster in JIT and AOT. I described how we did it in https://github.com/angular/angular/issues/10812#issuecomment-272412335

**Comment by kemsky** [comment] 2017-04-13 15:05
@shlomiassaf, I'm not going to argue, but it is not question of must or should or being wrong. My only concern is that performance should at least stay on the same level.

Most parts of the application where written well before modules where introduced, well before Webpack 2 appeared, well before  router loader plugin was written, well before AOT became barely usable, well before angular-cli appeared and so on, not to mention that router was rewritten many times. AOT, Tree-Shaking, new View Engine - too many promises, but reality is slightly different. Every angular pitfall costs customers money and my time. Just imagine yourself saying that you need one more week or even two for refactoring out of nowhere.

@sod, how large is your bundle in AOT?

**Comment by sod** [comment] 2017-04-13 15:36
@kemsky this is a breakdown of one of our apps (the 72 component one)

```log
JIT  82.6 kB    => AOT   100 kB       6  [emitted]  shared.module
JIT    83 kB    => AOT   229 kB       0  [emitted]  route3.module
JIT  50.8 kB    => AOT   143 kB       3  [emitted]  route2.module
JIT  12.4 kB    => AOT  33.2 kB       5  [emitted]  route1.module
JIT  24.9 kB    => AOT  32.6 kB       1  [emitted]  spa.module
JIT   9.5 kB    => AOT  39.3 kB       4  [emitted]  root.module
JIT  52.4 kB    => AOT   155 kB       2  [emitted]  route4.module
JIT  1070 kB    => AOT   735 kB       7  [emitted]  vendor

Component Code JIT ~314 kb
Component Code AOT ~731 kb

Everything JIT ~1384 kb
Everything AOT ~1466 kb
```

So our AOT code is ~10% bigger, but its only 10% because the 350kb @angular/compile code is removed from the AOT build (you don't need the compiler anymore when precompiled).

But the component code grows by 140%! So if your monolithic bundle contains of 2 MB of components, you can expect - when precompiled - that to grow around 5 MB :(

**Comment by tbosch** [comment] 2017-04-14 00:08
Thanks for the report. We are looking into it...

**Comment by vicb** [comment] 2017-04-14 18:57
I have tried to reproduce the issue without success.

It would be super helpful if you can narrow down the issue and identify which component source map takes more time.

**Comment by shlomiassaf** [comment] 2017-04-14 19:29
I have a 15 hr flight tomorrow to SFO.. I'll try debugging it on the plane.

**Comment by vicb** [comment] 2017-04-14 20:44
@shlomiassaf thanks & have a productive flight :) Ping us if you need help

**Comment by kemsky** [comment] 2017-04-15 00:02
I took profiles on FF and Chrome, the same application, angular 2.4.10 and 4.0.2. Profiler has some effect on measurement, without profiler 2.4.10 wins. 

Bootstrap times:
FF  2.4.10 - 5.8s
Edge 2.4.10 - 7.6s
Chrome 2.4.10 - 4.7s

FF  4.0.2 - 9.0s
Edge 4.0.2 - 12.7s
Chrome 4.0.2 - 5s

Most probably this is related to garbage collection.

[profiles.gz](https://github.com/angular/angular/files/923131/profiles.gz)

**Comment by shlomiassaf** [comment] 2017-04-17 06:06
@vicb ok, that was dirty...

Did some measurements and found some pages that causes pain to `toSourceMapGenerator()`, those, 1 in particular was a page that took 4 secs to parse. That page is a base line test page for our components.

The page (component) has:  
  - 352 templates line (13,463 chars)  
  - 97 source code (TS) lines (2,628 chars)
  - 4 style lines

The component template renders multiple components, most of them are `material` components (2, beta 3), total of ~50 components

The **ngfactory** file for that component comes out as ~6871 LOC - **222,859** chars.

HUGE!

I has to compare to a fresh CLI app, so I ported my app to `@angular/cli` - BLAZING FAST! :dizzy_face: :dizzy_face: :dizzy_face:  

Ok, comparing the 2 **.ngfactory** files, my version has **1** EXTRA LINE.

That line is the source map :weary: :weary:  
So we now have 6870 LOC but **157,216** chars - big chunk.

Digging deep, my env settings (of old app) didn't fit CLI so I got prod mode... fix - now `'IsDevMode' === true`

`@angular/cli` app is now **slow as my webpack app.**
Setting my project to run `enableProdMode();` in dev mode, ** blazing fast!**

The cli settings are probably a bit different so the process loads async which comes out like this:
![image](https://cloud.githubusercontent.com/assets/5377501/25080149/f28b0bd4-234a-11e7-97ed-7df7a026c1f4.png)

Same time, handled in a zone container or deferred - no clue.

End result is getting a long source map in the **.ngfactory.ts** file
![image](https://cloud.githubusercontent.com/assets/5377501/25080185/272d14d6-234b-11e7-9543-b58f8b55f4c5.png)

If you look at [angular/compiler - JIT - evalExpression()](https://github.com/angular/angular/blob/492153a986285014e7a6835a24e0299d5c9b7359/packages/compiler/src/output/output_jit.ts#L25) you'll see the action line.

So, it turns out that long, child component heavy pages can't handle dev mode in reasonable time.

**Comment by vicb** [comment] 2017-04-17 22:12
@shlomiassaf we could tell from the timeline in your issue report that that generating the template source map was the issue. The thing I do not understand is why your source map is getting that big.

Would you mind sharing your template and the ngfactory that includes the source maps ?

Thanks

**Comment by shlomiassaf** [comment] 2017-04-17 22:19
@vicb let me try and replicate something on a gist, brb

**Comment by shlomiassaf** [comment] 2017-04-17 23:13
@vicb 

https://github.com/shlomiassaf/angular-issue15955

Clone, yarn, `ng serve`

This is a port of our app into `@angular/cli`

99% of the content is striped but still the sourcemap builds takes time, little less since a lot of content is gone but still more then it should.

I kept the `shared` module structure as well as the `routing` structure since it might be related.

Thanks.

**Comment by vicb** [comment] 2017-04-18 18:16
@shlomiassaf When I test your app, I do not see any noticeable difference on the timeline whether the source map are generated or not. Really nothing like the initial report where the bootstrap time is doubled.

_To disable the source map generation, you can comment l. 24941 of the installed `compiler.es5.js`_

**Comment by oliverjanik** [comment] 2017-05-01 06:46
Sorry to hijack this discussion but what happened to JIT?

JIT used to be very fast during RC days. It did what the name suggests and it "just-in-time" compiled what was needed on the fly. Somewhere before Angular 2 final is changed to "let's compile everything on startup".

This meant that our startup times went from sub second to 4-5s and we were forced to go the AOT way which we spent a lot of time on as it has very hairy corner cases.

Does this issue suggest that JIT got even worse in Angular 4? That is disappointing. Angular is not usable without AOT in production at the moment and the slow JIT makes development experience miserable becase refreshes are quite frequent when working on a code base with watchers.

/rant

**Comment by otodockal** [comment] 2017-05-01 16:49
@oliverjanik I think nobody should ship JIT code in production (today or in the future). It's good for plunkers or development. AOT is being considered also for dev with incremental compilation (it's not there yet). Angular CLI --prod is also AOT by default.

Maybe try ng 4.x, it's fully compatible, I didn't notice anything substantial.

https://angular.io/docs/js/latest/guide/glossary.html#!#just-in-time-jit-compilation
https://github.com/UltimateAngular/aot-loader

**Comment by oliverjanik** [comment] 2017-05-01 17:01
The problem is that NG team dropped the ball on JIT and AOT is nowhere near complete. I works poorly for dev, only works for typescript, creating libraries is a nightmare with metadata.json.

Would it hurt to have performant JIT?

**Comment by sebastianvog** [comment] 2017-05-04 14:29
Any update on this? Our app is considerably slower in dev mode since Angular4.

**Comment by tbosch** [comment] 2017-05-05 21:35
Ping @shlomiassaf, it would be great if you could tweak your reproduction to a version where the sourcemap is the actual issue...

**Comment by shlomiassaf** [comment] 2017-05-06 20:31
@tbosch 

The demo I posted indeed does not reproduce the issue.
The demo is based on our app but it is stripped down of 90% of the content.

I will have to remove content piece by piece and post a demo reproducing the issue but this is time consuming and will in effect identify the root cause. Will try this week, hope I can make it.

One thing to note though, on **safari** it was 50% faster, 3-4 seconds load time.

**Comment by shlomiassaf** [comment] 2017-05-06 21:46
#### UPDATE - ISSUE FOUND (in my setup):

Since finding this issue we used `enableProdMode();` in our dev environment otherwise we can't work. I removed it now to find out that now its fast, 2-3 seconds to load.

Checked out the git revision from the day I posted this issue, delete **node_modules**, `yarn install` - ** NOW BACK TO SLOW**

After long revision/package install/test I found a potential suspect, it was a 3rd party angular component.

By removing [@swimlane/ngx-datatable](https://github.com/swimlane/ngx-datatable) (cc @amcdnl) the bootstrap speed got down to **2.5 - 3.5 seconds**

We moved to the new table implementation from `material` a week ago so we removed the entire code related to `ngx-datatable`

What's more strange is that to reproduce all I had to do was install `ngx-datatable` and
```ts
import { NgxDatatableModule } from '@swimlane/ngx-datatable';
console.log(NgxDatatableModule)
```

Nothing more, not included in an `@NgModule` and no template/style/component code.

(testing on ngx-datatable 7.3.0 and 9.1.0 same results)

This is very strange since that lib is quite popular and this should have been reported from angular@4.0.0 beta/rc releases and surely the official.

My best guess is that this is a mix of 2 libraries, one of which is `ngx-datatable` and the other is one of the libraries I use.

@sebastianvog , @kemsky (and other users experiencing slowness) are you using ngx-datatable?

**Comment by amcdnl** [comment] 2017-05-07 17:41
@shlomiassaf - Woah! Was there any specific component/etc that was causing the slowness? Can you log a bug on the table project w/ your config so I can dive in?

@tbosch - You can see a demos here ( http://swimlane.github.io/ngx-datatable/ ) if you see anything plz let me know.

**Comment by shlomiassaf** [comment] 2017-05-07 17:43
@amcdnl I'm not sure the root cause is `ngx-datatable`.

Yes, I removed it and it was fast but i'm quite sure that if you take a vanilla CLI project and use the table you won't get slowness... (didn't test though quite sure)

I'll try making some repro but it might take some time

**Comment by kemsky** [comment] 2017-05-07 23:20
I have already posted all necessary information in [comment](https://github.com/angular/angular/issues/15955#issuecomment-294258469) above. It is not related to sourcemaps, 4.0 JIT performance in release mode is much worse in every browser except Chrome.

**Comment by istiti** [comment] 2017-06-28 11:42
I have exactly same issue ! 7seconds to load app when refresh browser 
you can check sourcemap analyse here : https://plnkr.co/edit/xMf8HXoNIhq3urJ6cPXQ?p=preview

you can check what is loaded when going to homepage http://i.imgur.com/noOyp1r.png (please note chunk9 is lazyloaded if not connected)

here is my perfromance analyse : http://i.imgur.com/ysa6VRI.png

2-3sec until cli reload after file change + 7seconds until browser refresh = 10seconds after each change even for 1 char lol

thanks for help !

**Comment by shlomiassaf** [comment] 2017-07-13 00:44
OK, this just happen again. Out of nowhere.

Some facts:
  - I have OSX.
  - I'm using Chrome 59
  - **It doesn't happen in FireFox**
  - **It doesn't happen in Safari**
  - **It doesn't happen in Chrome 58.0.3029.81 (Official Build) (64-bit)**

An update in Chrome 59, probably in V8, caused this.

Some information about the app it happens in:
It only happens in a specific page that exists in a Module.
The module is lazy loaded, this is why it's clear to track the source since that webpack chunk take 11s to load.

Lazy loading is not the cause, tried eagerly with same result.

The page which we load in that module is a dev page that shows a lot of components, like a baseline/showcase thing for internal use and testing.

cc @tbosch @vicb

**Comment by tinganho** [comment] 2017-10-24 14:03
I'm wondering wether Angular is parsing the templates of all components? Destroying the native JS JIT? I can see in the inspector that template parsing functions are being called.

Couldn't these just be an easy fix and only parse the component's templates that are used? In other words,  like a real JIT.

**Comment by sod** [comment] 2017-10-24 14:47
Yes, JIT does parse everything upfront.

AoT has to know everything upfront. As JIT is not intended for use in production and just a convenience development feature, it behaves just like AoT.

I guess the way forward is to ditch JIT altogether and develop precompiled. Angular 5 is now able to incrementally compile your app (via `ngc --watch`) to make that possible.

**Comment by kemsky** [comment] 2017-10-24 15:14
@tinganho, it was implemented originally this way, but for compatibility reasons (AOT) template parsing was changed to parse everything at boot time.

**Comment by tinganho** [comment] 2017-10-24 15:15
Ok an another follow up question,

Should people just use Angular Router's `loadChildren` heavily to avoid template parsing janking. I think many is just importing everything on the app module and declares everything there.

https://angular.io/guide/router#lazy-loading-route-configuration

**Comment by sod** [comment] 2017-10-24 16:13
Definitely. That way you can also break up your app into smaller chunks and don't have to deliver one big bundle to the client upfront.

**Comment by pkozlowski-opensource** [comment] 2019-03-05 19:41
I'm going to go ahead and close this issue since:
* it is quite old (we had 3 major Angular versions since);
* we are redoing compilation pipeline with ivy;
* we've got no reliable reproduce scenario.

People _are_ looking into ivy's compiler performance as we speak so hopefully we will have get results to share in Angular 8 / 9.

**Closed by pkozlowski-opensource** 2019-03-05 19:41 UTC
Labels: comp: core & compiler, freq4: critical, severity3: broken, type: bug/fix
