### ISSUE TITLE
[Proposal] Realtime update style without reload browser or rebuild or save file, need help!

### ISSUE THREAD

**Issue by hiepxanh** [angular/angular#31464] opened 2019-07-09 10:31 UTC
Thank you for reading my issue, I know that Angular team have a lot of job to do. And they are busy to complete Ivy. But I only need your small help to suggest me a direction to finish my plugin. I will close it a soon as possible if I have solution or angular team don't want to see this issue.

## Why you need this issue?
![image](https://i.imgur.com/mBOsCvB.gif)
you can look at this image and look at [video ](https://youtu.be/T_3MbzpW4UY) to see how fast it can update.

imagine no more file saving or page reloading just to see how single update affects web page, realtime update style in browser immediately, as you type... How many time you can save? how fast we can build our application?

Base on this idea [Livestyle](http://livestyle.io/). I'm writing an extension for VS code and Chrome that can help Angular developer (or frontend developer) can style faster. It call **LiveStyle** that can updates CSS in browser immediately, as you type. No more file saving or page reloading just to see how single update affects web page. 

step 1) VSCode extensions will record your new style code in VS code 
step 2)  VSCode extensions will **complie** it in css
step 3) VSCode extensions will host a server and use socket.io to send data to chrome extension. Chrome extension will adding new style to your website.
3 step above is just take 1 second, and it will update every second I make changes.

I having problem in step 2

## How you need this issue?

Basicly I can do this with global style. But with the component, these styles are post-processed so that each selector is augmented with `_nghost` or `_ngcontent` attribute selectors. Now if I want to apply template style to necessary component. I need to comply style file (css, scss, etc ...) from component to css with that attribute above with it. But I dont know how? 

## What do you need?
1) Comply task: How can I comply component style file with  `_nghost` and `_ngcontent` attribute selectors? can I borrow angular internal compiler to do this task?
2) Detect attributes task:`_nghost` or `_ngcontent` is random on the browser after every build, how can I get that info? 

Please help me, I know that it's asking too much but this can save our day. We can spend more time for ourself, to relax, to play, to go out with our family, or to thinking. No more hard work and waiting reload angular app just for change text color. Please help me... 

Thank you Angular team,

If someone think it is good idea, please give me a 👍 

Have a nice day to all of you.

**Comment by hiepxanh** [comment] 2019-07-09 11:00
I can see that all I want in here [angular/packages/compiler/src/style_compiler.ts](https://github.com/angular/angular/blob/f8096d499324cf0961f092944bbaedd05364eea1/packages/compiler/src/style_compiler.ts) but how can I access this?

**Comment by mlc-mlapis** [comment] 2019-07-09 11:45
@hiepxanh There 4 possibilities how Angular works with styles on components level (https://angular.io/api/core/ViewEncapsulation) and working with styles depends on it.

```
enum ViewEncapsulation {
  Emulated: 0
  Native: 1
  None: 2
  ShadowDom: 3
}
```

**Comment by hiepxanh** [comment] 2019-07-09 12:47
@mlc-mlapis thank you, I already know what ViewEncapsulation does. I want to translate style file (scss, sass etc...) to normal css file. Which includes `_nghost-${COMPONENT_VARIABLE}` and `_ngcontent-${COMPONENT_VARIABLE}` attributes. 
And I want to do this inside my VS code extension.

**Comment by trotyl** [comment] 2019-07-09 12:55
Duplicate of https://github.com/angular/angular/issues/11942

**Comment by hiepxanh** [comment] 2019-07-09 14:14
@trotyl your suggest is just not suitable. I already try this. The HMR solution is not resolve this problem. It still recomplie. event though, I try HMR enable. The reload time is reduce from 45s to 10s.
If I'm using my solution:
step 1) VSCode extensions will record your new style code in VS code 
step 2)  VSCode extensions will complie it in css
step 3) VSCode extensions will host a server and use socket.io to send data to chrome extension. Chrome extension will adding new style to your website.
3 step above is just take 1 second, and it will update every second I make changes.

**Comment by hiepxanh** [comment] 2019-07-09 14:48
![image](https://user-images.githubusercontent.com/16970990/60898482-47341a80-a293-11e9-97d4-aeefff0667b7.png)
you can look at this image and look at [video ](https://youtu.be/T_3MbzpW4UY)to see the speed.

**Comment by mlc-mlapis** [comment] 2019-07-09 14:59
@hiepxanh Yep. It looks nice but there is one serious thing. The Angular compiler creates JS code to apply those styles. So are you thinking that it could be possible to just compile the style part of a component and exchange that code? Or do you think that you would hack that styling directly in DOM? The `None: 2` mode can be certainly realized by that way but I am not sure for the rest modes.

**Comment by hiepxanh** [comment] 2019-07-09 15:25
> Or do you think that you would hack that styling directly in DOM? 
@mlc-mlapis  thank you.
Yes, I'm patching directly in to DOM. I'm adding your unsave code to DOM (in the head tag) everytime you typing in VSCode. I'm not touching anything to angular, I just borrow it's compiler to complie it directly in my plugin.

**Comment by mlc-mlapis** [comment] 2019-07-09 15:48
@hiepxanh So, you need to have a relation between the parts in TS code and identity of compiled styles placed in the head tag. And because of those identities are generated on the random base, you are looking for some fixed rules, how to interconnect them together, right? For `Emulated: 0` mode is it theoretically possible, but what about `ShadowDom: 3` (`Native: 1` mode can be probably ignored).

**Comment by hiepxanh** [comment] 2019-07-10 01:18
@mlc-mlapis Thank you to help me recognize this case. I belive that I can insert component style directly to shadow DOM like this image:
![image](https://user-images.githubusercontent.com/16970990/60933071-010aa580-a2eb-11e9-8d2b-4ab369609f31.png)
base on this [codepen](https://codepen.io/calebdwilliams/pen/aPgbMb?editors=1111) from this [post](https://css-tricks.com/encapsulating-style-and-structure-with-shadow-dom/)
We can easily style directly shadow DOM since we just only template adding it to see the reflection of new template style we styling. After we save file changes, all that template code will be remove by Chrome extension

**Comment by hiepxanh** [comment] 2019-07-10 02:10
this function looklike promising but I don't know how to get it:
```.ts
  compileStyles(
      outputCtx: OutputContext, comp: CompileDirectiveMetadata,
      stylesheet: CompileStylesheetMetadata,
      shim: boolean = this.needsStyleShim(comp)): CompiledStylesheet {
    return this._compileStyles(outputCtx, comp, stylesheet, shim, false);
  }
```
https://github.com/angular/angular/blob/f8096d499324cf0961f092944bbaedd05364eea1/packages/compiler/src/style_compiler.ts#L48-L53

**Comment by BenRacicot** [comment] 2020-03-23 01:03
Stumbled on this after thinking about it for some time... My idea was basically the same but I was thinking about how Prepros injects your styles immediately exactly as you describe, where its not the compiled stylesheet that changes, it's only injected styles into the proxied webpage. 

Any page refresh will then load the entire compiled stylesheets. I'm because I'm wondering why we cannot inject the style immediately with the appropriate `_nghost-${COMPONENT_VARIABLE}`? At least then we can preview the styles and rely on full recompile/page load for the real thing.

@hiepxanh How can I help?

**Comment by hiepxanh** [comment] 2020-03-23 03:29
I already have this sir @benelliott  I Create websocket that listen to the chrome extension, the chrome seek `COMPONENT_VARIABLE` then send it to `vscode`. After that, vscode mix it that component variable with style and send it to chrome extension. then it will update it.

**Comment by hiepxanh** [comment] 2020-03-24 02:50
https://github.com/xanhtool/SnapCss 
https://www.youtube.com/watch?v=W-hWhR5GX_c&feature=youtu.be   

here you are @benelliott

**Comment by BenRacicot** [comment] 2021-04-21 12:18
Came across [NextJS' Fast Reload](https://nextjs.org/docs/basic-features/fast-refresh) today. 
(@hiepxanh mentioned that he has stopped work on his plugin)

Hoping that we can implement this in Angular since Next and React have it. Also, it's not a complicated addition.
What steps can we take to build this into compilation?

**Closed** 2021-06-25 00:41 UTC
Labels: comp: core, core: stylesheets, feature, insufficient votes, votes required
