### ISSUE TITLE
ngContent does not work on root component

### ISSUE THREAD

**Issue by veches** [angular/angular#6046] opened 2015-12-21 02:58 UTC

**Comment by gdi2290** [comment] 2015-12-21 04:10
related
https://github.com/angular/angular/issues/1858
https://github.com/angular/angular/issues/4946
https://github.com/angular/angular/issues/4921

**Comment by veches** [comment] 2015-12-21 20:01
I cannot get much out of the mentioned related issues.
what I am trying to do is
   -- something equivalent to ng-app in angular 1
   -- root component without template or that can transclude.

**Comment by pkozlowski-opensource** [comment] 2015-12-29 11:43
Closing as a duplicate of #1858

**Closed by pkozlowski-opensource** 2015-12-29 11:43 UTC
