### ISSUE TITLE
NonNullableFormControl is nullable for number inputs 

### ISSUE THREAD

**Issue by twittwer** [angular/angular#48833] opened 2023-01-25 11:27 UTC
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

No

### Description

When defining a Form with the `NonNullableFormBuilder` all properties are typed as non-nullable as expected. But in case of a number input, the value can become null in reality if the user clears the input.

### Please provide a link to a minimal reproduction of the bug

Repro with FromControl: https://stackblitz.com/edit/angular-wyws6x?file=src%2Fmain.ts
Repro with FormGroup: https://stackblitz.com/edit/angular-jwtod3?file=src%2Fmain.ts

### Please provide the exception or error you saw

```ts
control = inject(FormBuilder).nonNullable.control(42);
```
```html
<input type="number" [formControl]="control" />
```
> user deletes `42` from input, so it is blank
```ts
const value: number = control.value // typescript doesn't complain about nullability
console.log(typeof control.value === "number") // false
console.log(control.value) // null
```

**Comment by JeanMeche** [comment] 2023-01-25 12:36
I think it's up to the developer to know which controls it attaches to an input. 

`input[type=number]` uses the `NumberValueAccessor` 

https://github.com/angular/angular/blob/10634048eaabb2625e958d79fae37899c5c82140/packages/forms/src/directives/number_value_accessor.ts#L43-L49

which returns `number | null`. 

The matching being done by the directive, it has no way to know if the `FormControl` is nullable or not. 

An `nonNullable` FormControl should be used for example for a custom component with a custom CVA which only returns `number` as value.

**Comment by JeanMeche** [comment] 2023-01-26 10:25
By the way, the root problem has been fully discribed on #45968 and seems to be on the roadmap. 

We can close this as a dupe.

**Comment by JeanMeche** [comment] 2024-02-11 20:51
Closing as a dupe of  #45968

**Closed by JeanMeche** 2024-02-11 20:51 UTC
Labels: area: forms
