### ISSUE TITLE
Default @angular/pwa install doesn't pass Chrome 89 offline support detection

### ISSUE THREAD

**Issue by clementcontet** [angular/angular#41085] opened 2021-03-05 10:50 UTC
# 🐞 bug report

### Affected Package
@angular/pwa

### Is this a regression?
No, I think it's because of Chrome's update: https://developer.chrome.com/blog/improved-pwa-offline-detection/

### Description
When creating an Angular app with PWA support, the default template doesn't pass Chrome's "offline support" detection anymore.
So that apps created this way won't be installable in a near future (starting with Chrome 93)

## 🔬 Minimal Reproduction
Just create the default template app:
<pre><code>
$ ng new template-angular
$ cd template-angular
$ ng add @angular/pwa --project template-angular
$ ng build --prod
</code></pre>

Code: https://github.com/clementcontet/template-angular

Hosted result: https://template-angular-f3cdb.web.app/

## 🔥 Exception or Error
Chrome 89 says:
![image](https://user-images.githubusercontent.com/7261426/110105395-9ef89100-7da8-11eb-8961-2e62a55d82ae.png)

## 🌍  Your Environment
**Angular Version:**
<pre><code>
Angular CLI: 11.2.3
Node: 12.18.0
OS: win32 x64

Angular: 11.2.4
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
... service-worker
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.3
@angular-devkit/build-angular   0.1102.3
@angular-devkit/core            11.2.3
@angular-devkit/schematics      11.2.3
@angular/cli                    11.2.3
@schematics/angular             11.2.3
@schematics/update              0.1102.3
rxjs                            6.6.6
typescript                      4.1.5
</code></pre>

**Comment by josemalm32** [comment] 2021-03-05 12:05
Same problem here...

**Comment by gkalpak** [comment] 2021-03-05 18:47
Thx for reporting this.

I looked into it and the problem is that the Angular ServiceWorker will only return the [`index` URL][1] (i.e. a successful response while offline for a URL that is not in the cache) only for [navigation requests][2]. And the request made by Chrome to determine installability is not a navigation request.

For reference, the request for determining installability has a mode of `cors` and uses [web manifest's `start_url`][3].

More investigation is needed to determine the best way to approach this for the Angular ServiceWorker.
In the meantime, one workaround is to set your [web manifest's `start_url`][3] to something that will be in the cache (for example, `index.html`, which is by default part of an eagerly installed asset cache).

[1]: https://angular.io/guide/service-worker-config#index
[2]: https://github.com/angular/angular/blob/e7453f15d5b6925ff7be30993882f0c4a712eb71/packages/service-worker/worker/src/app-version.ts#L212-L227
[3]: https://developer.mozilla.org/en-US/docs/Web/Manifest/start_url

**Comment by zedL** [comment] 2021-03-13 11:02
@angularteam
Or please provide a way that we can display an offline fallback page (with specific route?)
https://web.dev/offline-fallback-page/

**Comment by gkalpak** [comment] 2021-03-13 15:27
@zedL, the SW will already serve the `index` URL for navigation requests, so you could handle that in your app.
Regarding online/offline status, the SW doesn't really have any extra info than the page itself.

Depending on what you want to achieve (and what you consider online/offline), you can use [navigator.onLine][1] (or the associated `online`/`offline` events), check for 504 HTTP status codes in `HttpClient` responses, look for error events in [Router#events][2], pass a custom [Router#errorHandler][3], etc.

[1]: https://developer.mozilla.org/en-US/docs/Web/API/NavigatorOnLine/onLine
[2]: https://angular.io/api/router/Router#events
[3]: https://angular.io/api/router/Router#errorHandler

**Comment by zedL** [comment] 2021-03-14 14:14
@gkalpak I tried to implement the workaround without success. 
I modified my webmanifest.json `"start_url": "./index.html"` and ngsw-config.json. 
`"assetGroups": [
    {
      "name": "app",
      "installMode": "prefetch",
      "resources": {
        "files": [ "/favicon.ico", "/index.html", "/webmanifest.json", "/*.css", "/*.js" ],
        "urls": [ ...]
      }
    },`

The index.html file get not prefetched and the call from chrome to check installable pwa still fail.
Any idea why?
PWA is here https://traact.app

**Comment by pette9** [comment] 2021-03-14 14:19
have you tried just "start_url": "index.html" in the `webmanifest.json` that workaround made the chrome warning disappear for me.

**Comment by zedL** [comment] 2021-03-14 14:46
@pette9 
I removed the "./" but unfortunatly this not change anything. The index.html file get not prefetched by the service worker.

**Comment by asiiro** [comment] 2021-03-14 15:22
@gkalpak @pette9 I can confirm that after a number hours of trying, the start_url index.html workaround does not seem to work on any of my personal or work related apps. I've had varied success when testing over localhost, however, on a production environment with TLS I simply cannot bypass this warning. If this is working for you, make sure to not just look at the console, if you break service worker installation due to your testing, the warning will obviously not show because the PWA criteria will not be satisfied. At this point, I think I'm going to wait for an official fix, since as @clementcontet reports, which I can also confirm, the default template doesn't work anyway.

**Comment by tmtron** [comment] 2021-03-16 10:55
> In the meantime, one workaround is to set your [web manifest's `start_url`](https://developer.mozilla.org/en-US/docs/Web/Manifest/start_url) to something that will be in the cache (for example, `index.html`, which is by default part of an eagerly installed asset cache).

Thanks. Setting `"start_url": "/index.html",` worked for us.

**Comment by mdarefull** [comment] 2021-03-16 12:45
> In the meantime, one workaround is to set your web manifest's start_url to something that will be in the cache (for example, index.html, which is by default part of an eagerly installed asset cache).

I can also confirm the workaround worked for me. I also modified the scope to be absolute "Just in Case". 
This is how that portion of my manifest looks like now:
![image](https://user-images.githubusercontent.com/22510674/111309514-c10cd180-863a-11eb-819a-c13cbc58a769.png)
For everything else, I'm using the defaults.

AFAIK, I haven't detected any odd behavior by doing so. I've tested on localhost and our production environment as well. 
One thing I've found useful to test this is to run the Lighthouse tool, without this fix, it was giving me a warning like:
![image](https://user-images.githubusercontent.com/22510674/111310107-7770b680-863b-11eb-8c3b-08d64736ce33.png)

But now there's no warning:
![image](https://user-images.githubusercontent.com/22510674/111309980-455f5480-863b-11eb-8dc9-8bf116a977d0.png)

@gkalpak: Should we, at the very least, update the documentation to include this information asap? Is there any harm in updating the web manifest the schematics generate to this so that it becomes the new default?

**Comment by pette9** [comment] 2021-03-16 13:15
> @gkalpak: Should we, at the very least, update the documentation to include this information asap? Is there any harm in updating the web manifest the schematics generate to this so that it becomes the new default?

Though the workaround worked in our case, this probably requires more investigation as @zedL and @asiiro have reported that it doesn't work on their applications.

**Comment by clementcontet** [comment] 2021-03-16 13:20
Hi all, the workaround worked for me too.

**Comment by asiiro** [comment] 2021-03-16 13:36
Hi all, just an update from my end as well - I just re-tested this, and I'd like to confirm that @mdarefull solution works, however to add, it only works for me after clearing site data (but only certain projects are affected) - This is not ideal as users will not be doing this under a normal use case, but we can work with this for now. Thanks for the help all.

**Comment by zedL** [comment] 2021-03-16 15:24
even with @mdarefull suggestion it doesn't work for my application. I will wait for an official solution.

**Comment by gkalpak** [comment] 2021-03-16 18:09
@zedL, your's is a different issue. There is a hash mismatch that causes the SW to enter a degraded state (and not complete its initialization):

> Driver state: EXISTING_CLIENTS_ONLY (Degraded due to: Hash mismatch (cacheBustedFetchFromNetwork): https://traact.app/app-service-worker.js: expected 80c3ba1e799e32215044faf97209174ffc6b30c6, got 7b84fbc74f08985389dc539bea5fe609b61c721f (after cache busting)

(You can see this error at https://traact.app/ngsw/state. See also the [ServiceWorker in production][1] guide for more info on SW debugging APIs.)

##
I can't comment on other people's apps/issues without looking at the code.

The work-around described in https://github.com/angular/angular/issues/41085#issuecomment-791610926 should work, but slight modifications/additional configuration might be required based on your specific setup.

In any case, this is just a temporary work-around. A proper fix should be released soon.

[1]: https://angular.io/guide/service-worker-devops#debugging-the-angular-service-worker

**Comment by gkalpak** [comment] 2021-03-16 18:12
Thx for the input, everyone :+1:

##
@zedL, your's is a different issue. There is a hash mismatch that causes the SW to enter a degraded state (and not complete its initialization):

> Driver state: EXISTING_CLIENTS_ONLY (Degraded due to: Hash mismatch (cacheBustedFetchFromNetwork): https://traact.app/app-service-worker.js: expected 80c3ba1e799e32215044faf97209174ffc6b30c6, got 7b84fbc74f08985389dc539bea5fe609b61c721f (after cache busting)

See https://github.com/angular/angular/issues/40049#issuecomment-742578878 for more info on what this error means.

(You can see this error at https://traact.app/ngsw/state. See also the [ServiceWorker in production][1] guide for more info on SW debugging APIs.)

##
I can't comment on other people's apps/issues without looking at the code.

The work-around described in https://github.com/angular/angular/issues/41085#issuecomment-791610926 should work, but slight modifications/additional configuration might be required based on your specific setup.

In any case, this is just a temporary work-around. A proper fix should be released soon.

[1]: https://angular.io/guide/service-worker-devops#debugging-the-angular-service-worker

**Comment by zedL** [comment] 2021-03-16 18:22
@gkalpak Yeah, I saw it too. I have all the time the problem for files that not get minified (json for example) that the hash calculation gets mismatched. I have no idea where this comes from, maybe something in the middle manipulates the files.
Unfortunatly the service worker stops prefetching the other files in the list, so my "index.html" never get cached. 
Thanks, I know now in what direction I have to look.

**Comment by mdarefull** [comment] 2021-03-16 18:47
@zedL Is it possible that you modify any of those files after building the app? I'm asking because I was doing a JSON Token Replace on my release pipeline to replace environment settings and that was, obviously, invalidating the checksums... I know this has been a popular practice when using CI/CD tools...

**Comment by zedL** [comment] 2021-03-16 19:03
@mdarefull Currently I get it to work with simply negative comment the problematic files out in ngsw-config.json.

I have 3 problems that leads to an hash mismatch:
- a) an index.html file that gets loaded dynamicly from a .net5 backend and delivered the SPA with an fallback route. (file loaded as string and delivered through the framework as response)
- b) a javascirpt file app-service-worker.js (my own wrapper over the angular ngsw-worker.js for handling notificationclick event (push notification))
- c) pure json i18n language files

The same characteristic for all the file are that they are not minified. I also dont use any post build pipe. 
Currently I dont know where this comes from. I host the app in an azure webapp. Nothing special, but devil is in detail :) If you have any other tips, let me know.

**Comment by gkalpak** [comment] 2021-03-16 19:28
I've heard of servers, proxies or CDNs doing such optimizations (e.g. minifying files before sending downstream), so that's worth looking into, @zedL.

**Comment by EltonFaust** [comment] 2021-03-18 14:42
> @mdarefull 
> * a) an index.html file that gets loaded dynamicly from a .net5 backend and delivered the SPA with an fallback route. (file loaded as string and delivered through the framework as response)

I was facing the same problem, dynamicly generating the index.html and the webmanifest files, and I found a solution, need some work but is working.

My solution was to dynamicly generate the `ngsw.json` file, by importing the `ngsw.json` file generated by angular and replacing  the sha1 hashes for both files (index.html and webmanifest)

Ended up with something like that:

```php
// response to route -> path-to/ngsw.json
$swData = json_decode(file_get_contents('path-to/original-ngsw.json'), true);

// render the resulting content
$indexContentRendered = '...file rendered';
$manifestContentRendered = '...file rendered';

$swData['hashTable']['path-to/index.html'] = sha1($indexContentRendered);
$swData['hashTable']['path-to/manifest.webmanifest'] = sha1($manifestContentRendered);

echo json_encode($swData);
```

PS: I know it's not `.net`, just an example how to solve the problem
PS 2: this solution only would be a problem if you are rendering the index.html content different for every request

**Comment by waseemw** [comment] 2021-03-20 14:17
Changing to '/index.html' fixed the 'Page does not work offline.' for me.
But now the `swUpdate.available.subscribe` doesn't get triggered anymore.

**Comment by zedL** [comment] 2021-03-21 11:10
@EltonFaust Hey, great idea! Thanks for sharing, I will have a look into it.

**Comment by phil-w** [comment] 2021-03-21 15:05
Even switching my CDN off makes no difference. The start URL can be anything and the error is there, even if I can see the thing referenced in my pre-warmed cache. It fails. It does not say why. There's nothing in the network panel which helps. It's a secret.  Is it a Google trick to burn programmer hours chasing non-existent problems?

[MDN](https://developer.mozilla.org/en-US/docs/Web/Manifest/start_url) state: "Note: The start_url member is **purely advisory**..." My bold. 

The only way I can get rid of this useless noise message is to remove the start_url completely from the manifest. That makes no difference to the operation of the site (on or offline) as far as I can see, but it gets rid of the console noise. It puts noise into the application/App manifest section of the dev tools, but although that's not strictly correct either (the start_url is absent, not "invalid", see above), it's clear enough what they're bitching about and more easily ignored.

**Comment by StPaulis** [comment] 2021-03-24 16:42
Any updates? 

The `start_url ` workaround make the warning go away but I find errors in my installed applications logs. 
Can't load the HTML file.

**Comment by bilelz** [comment] 2021-03-26 13:29
It finally works on my side with this configuration
```json
{
    "name": "POC PWA",
    "short_name": "poc-pwa",
    "theme_color": "#1976d2",
    "background_color": "#fafafa",
    "display": "standalone",
    "scope": "/poc-pwa/",
    "start_url": "index.html"
}
```
My site is hosted in the  folder `poc-pwa` : "example.com/poc-pwa"

**Comment by anode7** [comment] 2021-03-26 17:14
@gkalpak 

Just try to remove the 
```
"version": 8 ... 
"version": 1... 
```
from your ngsw-config.json file before building your app.

**Comment by leonelvsc** [comment] 2021-03-29 17:55
Adding `/` to `navigationUrls` in the `ngsw-config.json `should return the` index.html `page but it fails detecting the simulated offline request as the request doesn't have the `Accept: text/html` header but we could use `request.referrerPolicy` property checking for a value of `unsafe-url`

**Comment by FloNeu** [comment] 2021-03-30 18:56
> It finally works on my side with this configuration
> 
> ```json
> {
>     "name": "POC PWA",
>     "short_name": "poc-pwa",
>     "theme_color": "#1976d2",
>     "background_color": "#fafafa",
>     "display": "standalone",
>     "scope": "/poc-pwa/",
>     "start_url": "index.html"
> }
> ```
> 
> My site is hosted in the folder `poc-pwa` : "example.com/poc-pwa"

hmm... damn - that worked for you? I also have my app served from a sub-folder - i may not get the original warning about the install - but the index still not served in offline mode simulated / or when i go offline. Wenn i run a local http-server with scope '/' and 'start_url': 'index.html' everything works fine... no warnings and working offline-mode.

**Comment by gkalpak** [comment] 2021-03-31 09:52
@FloNeu, check out [Debugging the Angular SW][1] (if you haven't already). It has some useful info on debugging issues with the Angular SW.

[1]: https://angular.io/guide/service-worker-devops#debugging-the-angular-service-worker

**Comment by artepic** [comment] 2021-04-03 09:11
temp fix:
ngsw-worker.js

safeFetch(req) {
            return __awaiter(this, void 0, void 0, function* () {
                try {
                    return yield this.scope.fetch(req);
                }
                catch (err) {

                    return new Response("offline page");

                    //this.debugger.log(err, `Driver.fetch(${req.url})`);
                    //return this.adapter.newResponse(null, {
                    //    status: 504,
                    //    statusText: 'Gateway Timeout',
                    //});
                }
            });
        }

**Comment by JohnnyDevNull** [comment] 2021-04-11 12:46
None of the Workarounds worked for me:

https://jplace.de/

```
{
  "name": "JPlace",
  "short_name": "JP",
  "theme_color": "#006dcc",
  "background_color": "#1a1a1a",
  "display": "standalone",
  "scope": "/",
  "start_url": "index.html",
}
```

**Comment by submarines-and** [comment] 2021-04-11 13:54
Workaround posted by mdarefull worked for us. We have 1 manifest per supported language, so they look like this now:

  "scope": "./en/",
  "start_url": "./en/index.html"
  
    "scope": "./de/",
  "start_url": "./de/index.html"
  
  Etc

**Comment by gkalpak** [comment] 2021-04-17 08:59
Apparently, due to issues with the new installability check, the Chrome team decided to call off the change for now: [tweet][1] + [updated blog post][2]

The warning will be removed around Chrome v90.

##
Based on the above, I think we can close this (since the Angular SW does already work offline - it was just that the check failed to recognize that). If Chrome or another browser introduces a new installability check in the future that fails to recognize the Angular SW as working offline, we can adjust accordingly.

(If you have a different problem with the SW working offline, please open a new issue.)

[1]: https://twitter.com/ChromiumDev/status/1382745996917084160
[2]: https://developer.chrome.com/blog/improved-pwa-offline-detection/

**Closed by gkalpak** 2021-04-17 08:59 UTC
Labels: P3, comp: service-worker, state: confirmed, type: bug/fix
