### ISSUE TITLE
Cannot flush Response.arrayBuffer() promise

### ISSUE THREAD

**Issue by Teamop** [angular/angular#31692] opened 2018-12-11 08:01 UTC
I tried with the code below which mostly taken from the `Promise.spec.ts`:
```
// put in the Promise.spec.ts
fit('test flush', () => {
	queueZone.run(() => {
	  const flush = Zone.current.get('flush');
	  const queue = Zone.current.get('queue');
	  new Promise<string>(function(resolve, reject) {
				  resolve(Promise.resolve('RValue'));
				})
				.then((v: string) => {
				  log.push(v);
				  return Promise.resolve('second value');
				})
				.then((v: string) => {
				  log.push(v);
				});
	  
	  // new added part
	  new Response('').arrayBuffer().then(() => {
		log.push('third value');
	  });
	  
	  expect(queue.length).toEqual(1);
	  expect(log).toEqual([]);
	  flush();

          // error, here just ['RValue', 'second value']
          expect(log).toEqual(['RValue', 'second value', 'third value']);   
     });
 });
```
I'm not sure if this case is correct though.
Seems here it's because the `Response().arrayBuffer()` is not patched as `MicroTask`, but I'm a little confused as [fetch.spec.ts](https://github.com/angular/zone.js/blob/master/test/common/fetch.spec.ts#L76) here checks the `arrayBuffer`, is it just for validating `fetch` is correctly patched for working in `zone.js`? 
thanks a lot

**Comment by rafagsiqueira** [comment] 2022-08-31 14:25
I believe my issue might be similar to this. I am having trouble running a unit test for the following code:
```
public uploadFile = (container: string, file: File): Observable<boolean> =>
    from(file.arrayBuffer()).pipe(
      concatMap((buffer: ArrayBuffer) => this.http.put(`${this.storageUri}/${container}/${file.name}`, buffer, {observe: 'response'})),
      map(({status}) => status === 201),
      catchError((err) => {
        console.error(err);
        return of(false);
      })
    );
```
The unit test:
```
it('should upload file', fakeAsync(() => {
    service.uploadFile(testContainer, fakeFile).subscribe(
      (success: boolean) => expect(success).toBeTruthy()
    );
    tick();
    const req = httpTestingController.expectOne(`${TestingUtils.storageUri}/${testContainer}/${testFile}`);
    req.flush(new HttpResponse({status: 201}));
    httpTestingController.verify();
  }));
```

**Comment by JiaLiPassion** [comment] 2022-09-10 23:02
@Teamop , sorry for the late response.

I checked the issue, this is the expected behavior, to make your test work, the case need to look like this.

```
fit('test flush', (done) => {
        let flush: any;
        queueZone.run(() => {
          flush = Zone.current.get('flush');
          const queue = Zone.current.get('queue');
          new Promise<string>(function(resolve, reject) {
            resolve(Promise.resolve('RValue'));
          })
              .then((v: string) => {
                log.push(v);
                return Promise.resolve('second value');
              })
              .then((v: string) => {
                log.push(v);
              });

          // new added part
          new Response('').arrayBuffer().then(() => {
            log.push('third value');
          });

          expect(queue.length).toEqual(1);
          expect(log).toEqual([]);
          flush();

          // error, here just ['RValue', 'second value']
          expect(log).toEqual(['RValue', 'second value']);
        });
        setTimeout(() => {
          flush();
          expect(log).toEqual(['RValue', 'second value', 'third value']);
          done();
        });
      });
```

Since the `new Response('').arrayBuffer()` return a `pending Promise`, and the `then callback` will be only called when this promise is resolved, so when you call `flush()` it only triggered the `then callback` for all the `resolved` promise, and at that time, the `Reponse.arrayBuffer() promise` is not resolved yet.

So you need to use `setTimeout` or maybe other scheduler to wait for the `arrayBuffer()` promise resolved, and since the `Promise` returned by the `arrayBuffer()` is a `JS Promise`, so it is already be patched by `zone.js`, so the `then callback` will be inside the `zone`. everything should work as expected.

**Closed by JiaLiPassion** 2022-09-10 23:02 UTC
Labels: comp: zones, state: needs more investigation, P3
