### ISSUE TITLE
Active router links are lost after page refresh

### ISSUE THREAD

**Issue by anphetamina** [angular/angular#43283] opened 2021-08-28 17:15 UTC
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

No

### Description

The active router link in the sidenav is lost after a page refresh.

To reproduce: 

1. Run the mre I provided below
2. Click on any of the navigation links of the left
3. Refresh the page
4. Notice the link previously click is no more active after the page is loaded

### Please provide a link to a minimal reproduction of the bug

https://github.com/anphetamina/routerlink-bug

### Please provide the exception or error you saw

```true
No exceptions nor errors.
```

### Please provide the environment you discovered this bug in

```true
Angular CLI: 12
Node: 14
OS: Windows 10
Browser: Firefox/Edge
```

**Comment by jnizet** [comment] 2021-08-28 20:26
Hi @anphetamina  

When you click an item in the list, its backround becomes light gray not because it's the selected item, ut simply because it has the focus. If you click anywhere else in the page, it will also lose its light gray background, because it doesn't have the focus anymore.
Since you add an `active` css class using routerLinkActive, simply define what you want to happen when a link has this `active` css class in your home.css file. For example:

```css
.active, .mat-focus-indicator.active {
  background-color: lightgray;
}
```

You'll see that if you click outside the link, and even if you refresh the page, the link will then keep a light gray background.

**Comment by anphetamina** [comment] 2021-08-28 21:34
Your suggestion is not working as I intended but I understand that is style-related.
Thank you.

**Comment by atscott** [comment] 2021-08-30 16:47
Closing since this seems to be unrelated to the router package (https://github.com/angular/angular/issues/43283#issuecomment-907685249). The reproduction repo has been deleted as well so I'm assuming this was addressed.

**Closed by atscott** 2021-08-30 16:47 UTC
