### ISSUE TITLE
[Ivy] ERROR in module. Value in the NgModule.imports of Module is not a reference: [object Object]

### ISSUE THREAD

**Issue by Gnorro** [angular/angular#34777] opened 2020-01-14 17:35 UTC
# 🐞 bug report

### Description
We have lot of errors when enabling Ivy and making a production build

## 🔥 Exception or Error
<pre><code>
ERROR in app/shared/shared.module.ts:88:12 - error TS-991010: Value at position 6 in the NgModule.imports of SharedModule is not a reference: [object Object]
app/shared/shared-map.module.ts:12:12 - error TS-991010: Value at position 2 in the NgModule.imports of SharedMapModule is not a reference: [object Object]
app/app.module.ts:264:12 - error TS-991010: Value at position 30 in the NgModule.imports of AppModule is not a reference: [object Object]
and so on on lots of modules
</code></pre>

Error screenshot
![Cattura](https://user-images.githubusercontent.com/31180439/72367460-7e7cfb80-36fc-11ea-87af-f03a3d360ec8.JPG)

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.3.22
Node: 10.16.3
OS: win32 x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.22
@angular-devkit/build-angular     0.803.22
@angular-devkit/build-optimizer   0.803.22
@angular-devkit/build-webpack     0.803.22
@angular-devkit/core              8.3.22
@angular-devkit/schematics        8.3.22
@angular/cdk                      8.2.3
@angular/cli                      8.3.22
@angular/http                     7.2.15
@angular/material                 8.2.3
@angular/pwa                      0.803.22
@ngtools/webpack                  8.3.22
@schematics/angular               8.3.22
@schematics/update                0.803.22
rxjs                              6.5.4
typescript                        3.5.3
webpack                           4.39.2
</code></pre>

**Anything else relevant?**

Our package.json:
<pre><code>
{
  "name": "xxx",
  "version": "0.0.0",
  "scripts": {
    "ng": "node --max_old_space_size=8192 node_modules/@angular/cli/bin/ng",
    "start": "npm run ng -- serve",
    "build": "npm run ng -- build",
    "test": "npm run ng -- test",
    "lint": "npm run ng -- lint",
    "e2e": "npm run ng -- e2e",
    "analyze": "webpack-bundle-analyzer dist/stats.json",
    "compodoc": "npx compodoc -p src/tsconfig.app.json",
    "build:stats": "ng build --stats-json"
  },
  "private": true,
  "dependencies": {
    "@agm/core": "1.0.0-beta.7",
    "@agm/js-marker-clusterer": "1.0.0-beta.3",
    "@angular/animations": "8.2.14",
    "@angular/cdk": "8.2.3",
    "@angular/common": "8.2.14",
    "@angular/compiler": "8.2.14",
    "@angular/core": "8.2.14",
    "@angular/forms": "8.2.14",
    "@angular/http": "7.2.15",
    "@angular/material": "8.2.3",
    "@angular/platform-browser": "8.2.14",
    "@angular/platform-browser-dynamic": "8.2.14",
    "@angular/platform-server": "8.2.14",
    "@angular/pwa": "^0.803.22",
    "@angular/router": "8.2.14",
    "@angular/service-worker": "8.2.14",
    "@satispay/web-button-factory": "1.4.3",
    "angular4-social-login": "1.1.1",
    "braintree-web": "3.52.1",
    "braintree-web-drop-in": "1.20.1",
    "classlist.js": "1.1.20150312",
    "codice-fiscale-js": "2.1.0",
    "core-js": "^3.6.4",
    "domino": "2.1.3",
    "express": "4.17.1",
    "font-awesome": "4.7.0",
    "hammerjs": "2.0.8",
    "js-marker-clusterer": "1.0.0",
    "lory.js": "^2.5.3",
    "md5": "2.2.1",
    "moment-mini-ts": "2.20.1",
    "ng-lazyload-image": "5.1.2",
    "ng2-cookies": "1.0.12",
    "ngx-gallery": "4.1.2",
    "ngx-json-ld": "0.3.1",
    "ngx-loadable": "1.0.10",
    "ngx-responsive": "6.0.0",
    "ngx-swiper-wrapper": "4.9.0",
    "paypal-checkout": "4.0.285",
    "rxjs": "6.5.4",
    "tslib": "1.9.0",
    "zone.js": "0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "0.803.22",
    "@angular/cli": "8.3.22",
    "@angular/compiler-cli": "8.2.14",
    "@angular/language-service": "8.2.14",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.5.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~3.1.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "0.2.2",
    "node-ts": "5.0.1",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "3.5.3",
    "webpack-bundle-analyzer": "3.3.2"
  }
}
</code></pre>

Our tsconfig.json:
<pre><code>
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "src",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "module": "esnext",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "target": "es2015",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2018",
      "dom"
    ]
  }
}
</code></pre>

Our tsconfig.app.json:
<pre><code>
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc/app",
    "types": []
  },
  "angularCompilerOptions": {
    "enableIvy": true
  },
  "files": [
    "main.ts",
    "polyfills.ts"
  ],
  "include": [
    "../node_modules/@satispay/web-button-factory/src/*",
    "./**/*.ts"
  ],
  "exclude": [
    "test.ts",
    "src",
    "**/*.spec.ts"
  ]
}
</code></pre>

I tried also what is described in some topics:
./node_modules/.bin/ivy-ngcc -s ./dist
that should generate external libs, but this command generate nothing

After having read other topics, I tried also this:
I add "aot": true inside angular.json in this section:
<pre><code>
{
  "projects": {
    "your-project": {
      "architect": {
        "build": {
          "options": {
            ...
            "aot": true,
          }
        }
      }
    }
  }
}
</code></pre>

and also 
"postinstall": "ivy-ngcc"
in package.json
and I did another production build. I get this error:
<pre><code>
Compiling @angular/common/testing : main as umd
Compiling @angular/common/testing : module as esm5
Compiling @angular/core : es2015 as esm2015
TypeError: Cannot read property 'fileName' of null
    at Object.getImportRewriter (D:\dev\test\2020-01-14_update-to-angular-8\node_modules\@angular\compiler-cli\ngcc\src\rendering\utils.js:22:72)
    at DtsRenderer.renderDtsFile (D:\dev\test\node_modules\@angular\compiler-cli\ngcc\src\rendering\dts_renderer.js:75:72)
    at D:\dev\test\node_modules\@angular\compiler-cli\ngcc\src\rendering\dts_renderer.js:67:134
    at Map.forEach (<anonymous>)
    at DtsRenderer.renderProgram (D:\dev\test\node_modules\@angular\compiler-cli\ngcc\src\rendering\dts_renderer.js:67:26)
    at Transformer.transform (D:\dev\test\node_modules\@angular\compiler-cli\ngcc\src\packages\transformer.js:69:52)
    at Object.mainNgcc (D:\dev\test\node_modules\@angular\compiler-cli\ngcc\src\main.js:93:64)
    at D:\dev\test\node_modules\@angular\compiler-cli\ngcc\main-ngcc.js:68:20
    at D:\dev\test\node_modules\@angular\compiler-cli\ngcc\main-ngcc.js:4:17
    at Object.<anonymous> (D:\dev\test\node_modules\@angular\compiler-cli\ngcc\main-ngcc.js:10:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
</code></pre>

Thanks for your help

**Comment by JoostK** [comment] 2020-01-14 19:41
Hi @Gnorro, could please test with the latest `9.0.0` RC, that's `9.0.0.rc-8` at the moment. Ivy support in the 8.x version of Angular is way behind so you'll likely experience different behavior after updating.

**Comment by Gnorro** [comment] 2020-01-15 09:05
I will try to update to v9, and then i will write a feedback here. However we need to use v8 at the moment, so i would like to fix it on this version.

Is it correct to put "aot": true inside "options" as I wrote in my previous post? Of it's not necessary? I already have "aot": true in angular.json under "configurations"

Thanks

**Comment by gkalpak** [comment] 2020-01-15 09:19
> However we need to use v8 at the moment, so i would like to fix it on this version.

I am confused by this line. You should be able to use v8, just do not enable Ivy (which is opt-in and more or less experimental in v8). You can avoid opting into Ivy in v8 by removing `"enableIvy": true` from your TS config.

In v9, Ivy will be the default (but you will still be able to opt out with `"enableIvy": false`).

I am going to close this issue, since there are no plans to backport Ivy-related improvements/fixes to the 8.x branch. If you try with v9 and still get errors with Ivy, please open a new issue (ideally providing a minimal reproduction).

**Closed by gkalpak** 2020-01-15 09:19 UTC
Labels: comp: compiler, comp: ivy, freq2: medium, severity3: broken, state: Needs repro, type: bug/fix

**Comment by Gnorro** [comment] 2020-01-15 09:23
You are right George, we can avoid using Ivy, but we would like to use it because our app load slow, so it was a good thing to try.

About version 8, an external agency will soon start to work to implement universal, and we defined to do that in version 8 (not 9), This is the reason why we would like to make Ivy works on v8

Thanks
