### ISSUE TITLE
Renderer.setElementAttribute's attributeValue parameter and strictNullChecks

### ISSUE THREAD

**Issue by Dema** [angular/angular#13686] opened 2016-12-28 12:41 UTC
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
This is more a stylistic thing, but
```
this.renderer.setElementAttribute(this.el.nativeElement, 'data-some-param', undefined);
```
is a legal usage as it deletes data-some-param attribute from element, but this code  shows typescript error when using strictNullChecks because setElementAttribute is described as:
```
abstract setElementAttribute(renderElement: any, attributeName: string, attributeValue: string): void;
```
 attributeValue is just `string` and not `string | undefined`

**Expected behavior**

attributeValue to have type `string | undefined`
**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.2.4

https://github.com/angular/angular/blob/master/modules/%40angular/core/src/render/api.ts
still the same in latest Angular
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment] 2016-12-28 12:43
Duplicate of https://github.com/angular/angular/issues/11844

**Comment by pkozlowski-opensource** [comment] 2016-12-30 10:24
Closing as a duplicate of #11844, thnx @DzmitryShylovich

**Closed by pkozlowski-opensource** 2016-12-30 10:24 UTC
