### ISSUE TITLE
Can't update to 13.2.1 from 13.1.3 with Conflicting peer dependency: @angular/core@13.2.1

### ISSUE THREAD

**Issue by kolkov** [angular/angular#44959] opened 2022-02-03 10:50 UTC
### Which @angular/* package(s) are the source of the bug?

animations, core

### Is this a regression?

Yes

### Description

I try to update angular from v13.1.3 to 13.2.1, but got a error
`ng update @angular/cli @angular/core @angular/cdk -C`

### Please provide the exception or error you saw

```true
The installed Angular CLI version is outdated.
Installing a temporary Angular CLI versioned 13.2.2 to perform the update.
√ Package successfully installed.
Node.js version v17.3.0 detected.
Odd numbered Node.js versions will not enter LTS status and should not be used for production. For more information, please see https://nodejs.org/en/about/r
eleases/.
Using package manager: 'npm'
Collecting installed dependencies...
Found 50 dependencies.
Fetching dependency metadata from registry...
    Updating package.json with dependency @angular-devkit/build-angular @ "13.2.2" (was "13.1.4")...
    Updating package.json with dependency @angular/cli @ "13.2.2" (was "13.1.4")...
    Updating package.json with dependency @angular/compiler-cli @ "13.2.1" (was "13.1.3")...
    Updating package.json with dependency @angular/language-service @ "13.2.1" (was "13.1.3")...
    Updating package.json with dependency @angular/animations @ "13.2.1" (was "13.1.3")...
    Updating package.json with dependency @angular/cdk @ "13.2.1" (was "13.1.3")...
    Updating package.json with dependency @angular/common @ "13.2.1" (was "13.1.3")...
    Updating package.json with dependency @angular/compiler @ "13.2.1" (was "13.1.3")...
    Updating package.json with dependency @angular/core @ "13.2.1" (was "13.1.3")...
    Updating package.json with dependency @angular/forms @ "13.2.1" (was "13.1.3")...
    Updating package.json with dependency @angular/platform-browser @ "13.2.1" (was "13.1.3")...
    Updating package.json with dependency @angular/platform-browser-dynamic @ "13.2.1" (was "13.1.3")...
    Updating package.json with dependency @angular/router @ "13.2.1" (was "13.1.3")...
    Updating package.json with dependency @angular/service-worker @ "13.2.1" (was "13.1.3")...
  UPDATE package.json (2518 bytes)
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: freicon-ui@1.0.0-beta.2
npm ERR! Found: @angular/animations@13.1.3
npm ERR! node_modules/@angular/animations
npm ERR!   @angular/animations@"~13.2.1" from the root project
npm ERR!   peerOptional @angular/animations@"13.1.3" from @angular/platform-browser@13.1.3
npm ERR!   node_modules/@angular/platform-browser
npm ERR!     @angular/platform-browser@"~13.2.1" from the root project
npm ERR!     peer @angular/platform-browser@"13.1.3" from @angular/forms@13.1.3
npm ERR!     node_modules/@angular/forms
npm ERR!       @angular/forms@"~13.2.1" from the root project
npm ERR!     2 more (@angular/platform-browser-dynamic, @angular/router)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! @angular/animations@"~13.2.1" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: @angular/core@13.2.1
npm ERR! node_modules/@angular/core
npm ERR!   peer @angular/core@"13.2.1" from @angular/animations@13.2.1
npm ERR!   node_modules/@angular/animations
npm ERR!     @angular/animations@"~13.2.1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\Andy\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Andy\AppData\Local\npm-cache\_logs\2022-02-03T10_40_29_910Z-debug.log
× Package install failed, see above.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
D:\Go\freicon\web>ng version
Node.js version v17.3.0 detected.
Odd numbered Node.js versions will not enter LTS status and should not be used for production. For more information, please see https://nodejs.org/en/about/r
eleases/.

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 13.1.4
Node: 17.3.0 (Unsupported)
Package Manager: npm 8.1.3
OS: win32 x64

Angular: <error>
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... pwa, router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1301.4 (cli-only)
@angular-devkit/build-angular   <error>
@angular-devkit/core            13.1.4 (cli-only)
@angular-devkit/schematics      13.1.4 (cli-only)
@angular/cli                    13.1.4 (cli-only)
@schematics/angular             13.1.4 (cli-only)
ng-packagr                      <error>
rxjs                            6.6.7 (cli-only)
typescript                      2.9.1 (cli-only)

Warning: The current version of Node (17.3.0) is not supported by Angular.

D:\Go\freicon\web>
```

### Anything else?

[eresolve-report.txt](https://github.com/angular/angular/files/7993834/eresolve-report.txt)
![image](https://user-images.githubusercontent.com/3740898/152328577-21c14468-c892-4cc6-9cbc-f8ad949e4b89.png)

**Comment by alan-agius4** [comment] 2022-02-03 11:14
Duplicate of #21204

**Closed by alan-agius4** 2022-02-03 11:14 UTC

**Comment by kolkov** [comment] 2022-02-03 11:15
@alan-agius4 A you sure that is duplicates?

**Comment by alan-agius4** [comment] 2022-02-03 11:19
@kolkov yes, related NPM issue https://github.com/npm/cli/issues/3666

**Comment by kolkov** [comment] 2022-02-03 11:26
Thanks! I just look that a lot of time has passed since ... It's strange that nothing can do anything so long.
