### ISSUE TITLE
Platform-server injection regression between 6.0.0-rc.1 and 6.0.0-rc.2

### ISSUE THREAD

**Issue by jelbourn** [angular/angular#23211] opened 2018-04-05 22:05 UTC
### Reproduction
* Clone https://github.com/jelbourn/material2/tree/with-angular-6.0.0-rc.2
* `npm i`
* `gulp prerender`

### Error
```
Error: ERROR { Error: MatDatepicker: No provider found for MAT_DATE_FORMATS. You must import one of the following modules at your application root: MatNativeDateModule, MatMomentDateModule, or provide a custom implementation.
    at createMissingDateImplError (/usr/local/google/home/jelbourn/material2/dist/packages/universal-app/material/bundles/material-datepicker.umd.js:51:12)
    at new MatDatepickerInput (/usr/local/google/home/jelbourn/material2/dist/packages/universal-app/material/bundles/material-datepicker.umd.js:2639:19)
    at createClass (/usr/local/google/home/jelbourn/material2/node_modules/@angular/core/bundles/core.umd.js:10148:20)
    at createDirectiveInstance (/usr/local/google/home/jelbourn/material2/node_modules/@angular/core/bundles/core.umd.js:10023:20)
    at createViewNodes (/usr/local/google/home/jelbourn/material2/node_modules/@angular/core/bundles/core.umd.js:11245:36)
    at callViewAction (/usr/local/google/home/jelbourn/material2/node_modules/@angular/core/bundles/core.umd.js:11561:13)
    at execComponentViewsAction (/usr/local/google/home/jelbourn/material2/node_modules/@angular/core/bundles/core.umd.js:11480:13)
    at createViewNodes (/usr/local/google/home/jelbourn/material2/node_modules/@angular/core/bundles/core.umd.js:11273:5)
    at createRootView (/usr/local/google/home/jelbourn/material2/node_modules/@angular/core/bundles/core.umd.js:11159:5)
    at callWithDebugContext (/usr/local/google/home/jelbourn/material2/node_modules/@angular/core/bundles/core.umd.js:12194:25)
```

### Notes
* The branch above only changes Angular from rc.1 (working fine) to rc.2 (error). 
* The error appears to only happen on platform-server AFAICT.
* The `NgModule` looks right to me ([source](https://github.com/jelbourn/material2/blob/with-angular-6.0.0-rc.2/src/universal-app/kitchen-sink/kitchen-sink.ts))
* The token with the error uses the traditional provider API

**Comment by IgorMinar** [comment] 2018-04-05 22:47
@alxhub could this be caused by https://github.com/angular/angular/commit/fab6b39c3de23ae8690ae2a64860933b89cc4691 ? that's the only DI related change in https://github.com/angular/angular/compare/6.0.0-rc.1...6.0.0-rc.2

**Comment by jelbourn** [comment] 2018-04-05 23:31
I just tried a local Angular build with fab6b39c3de23ae8690ae2a64860933b89cc4691 reverted and it still happens

**Comment by alxhub** [comment] 2018-04-05 23:42
I don't see a `ngInjectableDef` on `MAT_DATE_FORMATS`. Is it supposed to have one?

https://github.com/jelbourn/material2/blob/with-angular-6.0.0-rc.2/src/lib/core/datetime/date-formats.ts#L25

**Comment by jelbourn** [comment] 2018-04-06 00:09
I confirmed that a local build of Angular with https://github.com/angular/angular/commit/f99cb5c reverted works

**Comment by alexeagle** [comment] 2018-04-06 00:57
@alxhub any idea what is broken with that commit? If we just ship without it, we break `ng_package` users

**Comment by alxhub** [comment] 2018-04-10 22:37
Fixed by https://github.com/angular/angular/commit/11ea3a3f3319eb1ac141ffde3f0f3b65d3bf0e4e.

**Closed by alxhub** 2018-04-10 22:37 UTC
Labels: comp: core & compiler, hotlist: material2, severity5: regression
