### ISSUE TITLE
Directives are wrongly marked as unused import

### ISSUE THREAD

**Issue by alebx** [angular/angular#59001] opened 2024-12-02 09:55 UTC
### Which @angular/* package(s) are the source of the bug?

~~compiler~~
language-service

### Is this a regression?

No

### Description

The new unused standalone imports throws some false positives. In my example I've only seen this behaviour happening with directives, e.g. when the directive's selector targets attributes `selector: 'input[type=url][formControlName],input[type=url][formControl],input[type=url][ngModel]',` but it also happens for `<ng-template *ngTemplateOutlet="templateRef; context: { x }" />` (when `ng-template` is exchanged with `ng-container` it works correctly).

The compiler seems to work correctly but the language-service (in IntelliJ IDEA 2024.3 (Ultimate Edition)) delivers a different result.

### Please provide the exception or error you saw

```true

```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 19.0.2
Node: 22.11.0
Package Manager: npm 10.9.0
OS: darwin arm64

Angular: 19.0.1
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1802.12
@angular-devkit/build-angular   19.0.2
@angular-devkit/core            18.2.12
@angular-devkit/schematics      19.0.2
@angular/cli                    19.0.2
@schematics/angular             19.0.2
ng-packagr                      19.0.1
rxjs                            7.8.1
typescript                      5.5.4
zone.js                         0.15.0
```

**Comment by JoostK** [comment] 2024-12-02 10:06
Please include a runnable reproduction that shows this problem.

**Comment by alebx** [comment] 2024-12-02 10:53
> Please include a runnable reproduction that shows this problem.

I've updated the issue, the language-service, not the compiler seems to be the culprit.

**Comment by JoostK** [comment] 2024-12-02 11:35
Oh, I see it's regarding a Jetbrains IDE. It isn't using the Angular language service as it has its own analysis and diagnostics pipeline. Duplicate of #58958.

**Closed by JoostK** 2024-12-02 11:35 UTC
Labels: needs reproduction, area: compiler
