### ISSUE TITLE
Contributing - Bazel is not installed automatically

### ISSUE THREAD

**Issue by lukasmatta** [angular/angular#29868] opened 2019-04-12 11:27 UTC
Hello,

in the [BAZEL.md](https://github.com/angular/angular/blob/master/docs/BAZEL.md) file there is following sentence: *In order to ensure that everyone builds Angular in a consistent way, Bazel will be installed through NPM and therefore __it's not necessary to install Bazel manually.__* However, after running *yarn install* I don't have any Bazel package installed and command ```yarn bazel``` doesn't work.

Instructions about installing Bazel should be more clear.

**Comment by alexeagle** [comment] 2019-04-17 14:37
`@bazel/bazel` appears in the `package.json` so after running `yarn install` you should have a `node_modules/@bazel/bazel` directory, and `node_modules/.bin/bazel` binary.

I'm not sure how to reproduce this. Any ideas what is different? Your version of yarn maybe?
Any logs from yarn install that give us a hint?

**Comment by alexeagle** [comment] 2019-04-23 14:25
ping @lukasmatta - if you can help us repro this, I'd really like to get to the bottom of any Bazel install issues.

**Comment by petebacondarwin** [comment] 2020-11-02 20:13
Closing due to a lack of reproduction and a long time since the last comment.

**Closed by petebacondarwin** 2020-11-02 20:13 UTC
Labels: P3, comp: bazel, freq1: low, needs clarification, needs reproduction, type: bug/fix
