### ISSUE TITLE
Angular 7 Router Bug - skipLocationChange still shows url in browser (reopen of #29871)

### ISSUE THREAD

**Issue by thomasesh** [angular/angular#35764] opened 2020-02-28 18:21 UTC
# 🐞 bug report

### Affected Package

@angular-router

### Is this a regression?
no

### Description
This is a reopen of https://github.com/angular/angular/issues/29871

I don't want the address in the url address bar to change paths in my application.
I add "skipLocationChange" to all the router links and router.navigate and router.navigateByUrl calls
and all works correctly except when one of my route guards redirects to a difference page.  Then the url address bar contains the url of the page where I was before clicking on the link to the page that failed the route guard.

## 🔬 Minimal Reproduction

This has been reproduced in stackblitz:
https://stackblitz.com/edit/authguarddemo

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

See stackblitz environment.

**Anything else relevant?**

This is the similar, if not the exact same issue, to issue #29871

**Comment by atscott** [comment] 2020-02-28 18:56
Hi @thomasesh, the router should probably handle this case correctly, but in the meantime, something you can do instead that works right now is return a `UrlTree` instead of calling `router.navigate` and returning false from the guard:

```
   return this.router.createUrlTree(['/login'], { queryParamsHandling: 'preserve',
                          skipLocationChange: true});
```

**Comment by thomasesh** [comment] 2020-02-28 19:23
@atscott, 
Thanks for responding.

The canActivate  method can't return a urlTree.

```
return this.router.createUrlTree(["/login"], { queryParamsHandling: "preserve",
                          skipLocationChange: true});
  //  this.router.navigate(['/login'], { queryParamsHandling: 'preserve',
  //                         skipLocationChange: true});

  //  return false;


ERROR in src/app/auth-guard.guard.ts(14,3): error TS2416: Property 'canActivate' in type 'AuthGuardGuard' is not assignable to the same property in base type 'CanActivate'.
  Type '(next: ActivatedRouteSnapshot, state: RouterStateSnapshot) => UrlTree' is not assignable to type '(route: ActivatedRouteSnapshot, state: RouterStateSnapshot) => boolean | Promise<boolean> | Observable<boolean>'.
```

And what I really want to do is to bring up a modal to login, not navigate to a login page.
Any ideas for that?

**Comment by atscott** [comment] 2020-02-28 19:34
Hi @thomasesh, the feature for returning a `UrlTree` was added in version 8. I noticed your Stackblitz example is set to version 6.

**Comment by thomasesh** [comment] 2020-02-28 21:29
@atscott, thanks!  i upgraded to angular 9 and now the createTreeUrl works.

**Comment by thomasesh** [comment] 2020-03-02 14:36
@atscott,

How does the skipLocationChange option work in createUrlTree?   If I look in the Angular 9.0.4 code, the createUrlTree doesn't even look at the skipLocationChange option?

Here is the createUrlTree method from angular 9.0.4:

```
 createUrlTree(commands: any[], navigationExtras: NavigationExtras = {}): UrlTree {
    const {relativeTo,          queryParams,         fragment,
           preserveQueryParams, queryParamsHandling, preserveFragment} = navigationExtras;
    if (isDevMode() && preserveQueryParams && <any>console && <any>console.warn) {
      console.warn('preserveQueryParams is deprecated, use queryParamsHandling instead.');
    }
    const a = relativeTo || this.routerState.root;
    const f = preserveFragment ? this.currentUrlTree.fragment : fragment;
    let q: Params|null = null;
    if (queryParamsHandling) {
      switch (queryParamsHandling) {
        case 'merge':
          q = {...this.currentUrlTree.queryParams, ...queryParams};
          break;
        case 'preserve':
          q = this.currentUrlTree.queryParams;
          break;
        default:
          q = queryParams || null;
      }
    } else {
      q = preserveQueryParams ? this.currentUrlTree.queryParams : queryParams || null;
    }
    if (q !== null) {
      q = this.removeEmptyProps(q);
    }
    return createUrlTree(a, this.currentUrlTree, commands, q !, f !);
  }
```

**Comment by atscott** [comment] 2020-03-02 15:18
Hi @thomasesh, you're right that it doesn't use `skipLocationChange` but I'm confused by your previous comment about why the proposed solution doesn't work. The `canActivate` API supports returning an `Observable<UrlTree>` and you can use that instead of navigating https://angular.io/api/router/CanActivate#canactivate.

**Comment by thomasesh** [comment] 2020-03-02 18:01
My angular 8.2.1 application was not working when returning an Observable<UrlTree> and I mistakenly thought that was the reason.   After I looked into the code and saw that createUrlTree was not using the skipLocationChange option, I thought that maybe I had to upgrade to Angular 9.0.  But the 9.0 version of createUrlTree is the same as version 8.2.1.   So now I don't understand how my StackBlitz example works, although it does.    So how does the skipLocationChange option in the createUrlTree case?

**Comment by atscott** [comment] 2020-03-02 18:54
@thomasesh I *think* I understand the confusion, but not sure. The `createUrlTree` case should continue the navigation to the returned `UrlTree` with the values for `skipLocationChange` and/or `replaceUrl` from the original navigation. 

I should have written the above as `return this.router.createUrlTree(['/login'], { queryParamsHandling: 'preserve'});`. I also tried making this an observable with `return of(this.router.createUrlTree...)` and that worked as well so I'm not sure what's happening in your application. 

If you are able to reproduce the case where returning a UrlTree does not use the `skipLocationChange` value from the original navigation, please do submit a new issue for that. Let's keep this one for addressing the original issue of calling `router.navigate` with `skipLocationChange` from the guard.

**Comment by pendsley** [comment] 2020-03-02 19:30
> So now I don't understand how my StackBlitz example works, although it does.

I'm running into this same situation. In the StackBlitz ContactComponent is using skipLocationChange. If I remove that, I can reproduce the issue I'm seeing where the url changes.

Change
```
@Component({
  selector: 'contact',
  template:`
    <hr/><h1>Hello From Contact Us Page</h1>
  
    <a routerLinkActive="active"     
      routerLink="/email" skipLocationChange>Via email</a> 
  `,
})
export class ContactComponent {}
``` 

To
```
@Component({
  selector: 'contact',
  template:`
    <hr/><h1>Hello From Contact Us Page</h1>
  
    <a routerLinkActive="active"     
      routerLink="/email">Via email</a> 
  `,
})
export class ContactComponent {}
```

After doing this, clicking the email link will change the url, but I would expect the guard's UrlTree to prevent the url from changing.

**Comment by atscott** [comment] 2020-03-02 19:33
@pendsley Could you provide a more complete example? As I mentioned in my previous comment, the navigation to the return `UrlTree` would not use `skipLocationChange` if it wasn't set in the initial navigation that's being cancelled.

**Comment by pendsley** [comment] 2020-03-02 20:05
>the navigation to the return UrlTree would not use skipLocationChange if it wasn't set in the initial navigation that's being cancelled.

Maybe I just didn't understand the capabilities. What I'm looking for is the ability to have a guard that redirects to a different component without updating the browser's url.

For my use case, I want to remove a link to a page because a user does not have permission to view it. If a user tries to navigate to the page, I want to tell the user they are missing permission, but not change the url. To do this, I tried using a guard to handle the redirect.

https://stackblitz.com/edit/authguarddemo-xuksyf

In this fork of the original StackBlitz, I removed the Contact Us link. If you replace /dashboard with /contact in the browser's url, the guard will redirect you to /login, as it should, but I want the url to stay as /contact.

If I'm understanding you correctly, `skipLocationChange` in the guard will essentially be ignored.

**Comment by atscott** [comment] 2020-03-02 20:13
Yes, that would be right. `skipLocationChange` is ignored in the `createUrlTree` because skipping location change is part of a navigation action; it's not information inside a `UrlTree`.  This may very well be the same reason the `UrlTree` return is not sufficient for @thomasesh either. So to summarize, returning `UrlTree` from a router guard _cannot_ change the value of the `skipLocationChange` from the original navigation. If it was true, it stays true and vice versa.

**Comment by rsc092020** [comment] 2020-06-03 20:58
@atscott Is there any issue with putting something like `this.router.getCurrentNavigation().extras.skipLocationChange = true;` before the `return <urlTree>` in the guard? It seems to fix both of issues mentioned above, but I haven't done thorough testing to see if there are any unwanted side effects or potential future problems.

**Comment by atscott** [comment] 2020-06-03 21:32
> @atscott Is there any issue with putting something like `this.router.getCurrentNavigation().extras.skipLocationChange = true;` before the `return <urlTree>` in the guard? It seems to fix both of the issues mentioned above, but I haven't done thorough testing to see if there are any unwanted side effects or potential future problems.

@rsc092020 That sounds like a pretty reasonable solution. I can't think of any reason it would be a problem.

**Comment by atscott** [comment] 2020-06-15 16:55
Closing as duplicate of #16981 / #27148. Allowing `NavigationExtras` when returning `URLTree` from guard would resolve this one as well.

**Closed by atscott** 2020-06-15 16:55 UTC
Labels: comp: router, freq2: medium, severity2: inconvenient, type: bug/fix
