### ISSUE TITLE
ng-content Does not work with a root component.

### ISSUE THREAD

**Issue by JohnMunsch** [angular/angular#6143] opened 2015-12-27 18:22 UTC
http://plnkr.co/edit/5ZlYKh?p=preview

If you look at the provided example you will see that it attempts to make use of ng-content and that it does not work. The reason it does not work seems to be that it is attempting to use the contents of the root component which appears in the index.html. However, as soon as an intermediary component is introduced, as in this example:

http://plnkr.co/edit/KwXVY0?p=preview

Then the ng-content works correctly.

Also, and this is basically lumping two things together into one, shouldn't ng-content have become ngContent just as ngIf, ngFor, etc. did?

**Comment by ericmartinezr** [comment] 2015-12-27 18:32
Related https://github.com/angular/angular/issues/1858, specifically https://github.com/angular/angular/issues/1858#issuecomment-151326461

**Comment by pkozlowski-opensource** [comment] 2015-12-29 11:43
Closing as a duplicate of #1858

**Closed by pkozlowski-opensource** 2015-12-29 11:43 UTC
