### ISSUE TITLE
list of complete pipes link does not work

### ISSUE THREAD

**Issue by gkyildirim** [angular/angular#56378] opened 2024-06-11 13:12 UTC
### Describe the problem that you experienced

When click on the link and page is not found.

It is referred in https://angular.dev/guide/pipes at the section of
```
Note: For a complete list of built-in pipes, see the [pipes API documentation](https://angular.dev/api/common#pipes).
```

### Enter the URL of the topic with the problem

https://angular.dev/api/common#pipes

**Comment by JeanMeche** [comment] 2024-06-11 13:17
Duplicate of https://github.com/angular/angular/issues/52968

**Closed by JeanMeche** 2024-06-11 13:17 UTC
