### ISSUE TITLE
Compilation error in Ivy mode with 8.1.0-next.3

### ISSUE THREAD

**Issue by sergey-morenets** [angular/angular#31201] opened 2019-06-21 20:30 UTC
# 🐞 bug report

### Affected Package

@angular/material

### Is this a regression?

No

### Description

I have a working Angular v8 application that uses @angular/material. I tried to upgrade to 8.1.0-next.3  to verify that Ivy mode works properly:

```
"angularCompilerOptions": {
    "enableIvy": true
  }
```
But in Ivy mode I get the error message. In non-Ivy mode everything works fine.

## 🔬 Minimal Reproduction

ng build --prod

## 🔥 Exception or Error
<pre><code>
ERROR in node_modules/@angular/material/menu/typings/menu.d.ts(161,23): error TS2314: Generic type 'ɵɵBaseDef<T>' requires 1 type argument(s).
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.1.0-beta.2
Node: 12.3.1
OS: win32 x64
Angular: 8.1.0-next.3
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.801.0-beta.2
@angular-devkit/build-angular     0.801.0-beta.2
@angular-devkit/build-optimizer   0.801.0-beta.2
@angular-devkit/build-webpack     0.801.0-beta.2
@angular-devkit/core              8.1.0-beta.2
@angular-devkit/schematics        8.1.0-beta.2
@angular/cdk                      8.0.1
@angular/cli                      8.1.0-beta.2
@angular/material                 8.0.1
@ngtools/webpack                  8.1.0-beta.2
@schematics/angular               8.1.0-beta.2
@schematics/update                0.801.0-beta.2
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.34.0
</code></pre>

**Comment by ericmartinezr** [comment] 2019-06-21 20:35
Dup of https://github.com/angular/angular/issues/31160

**Comment by JoostK** [comment] 2019-06-21 21:04
Thanks for reporting this issue. However this issue is a duplicate of an existing issue #31160. Please subscribe to that issue for future updates.

Thanks @ericmartinezr!

**Closed by JoostK** 2019-06-21 21:04 UTC
