### ISSUE TITLE
Bound components showing up twice in @Query children 

### ISSUE THREAD

**Issue by typotter** [angular/angular#3655] opened 2015-08-14 23:28 UTC
Binding a component to a token in both `bindings` and `viewBindings` results in the component appearing twice in the children list, injected by @Query.

ex:

```
@Component(
  selector: 'foo',
  bindings: const [ const Binding(SomeInterface, toAlias: FooComponent)],
  viewBindings: const [ const Binding(SomeInterface: toAlias: FooComponent)])
class FooComponent {
  FooComponent(@Query(SomeInterface) myChildren) {
    myChildren.onChange(() {
      print(myChildren.toList().length);
    });
}
```
prints 2

**Comment by mhevery** [comment] 2015-08-19 17:42
Can you show a full example including the Views? It may be that you have it twice in the View.

Also your example is not right, since `bindings`/`viewBindings` do (should) not effect `@Query`.

I am going to close this. Plesae provide a working repro case on http://plnkr.co/edit/ and open a new issue if it still not working.

**Closed by mhevery** 2015-08-19 17:42 UTC

**Comment by jpsfs** [comment] 2015-08-19 19:19
Hi,

I was able to reproduce this also. Nothing to do with bindinds or view bindings though.

It happens if I show the component twice on the same page. The second time the component's onInit is called the # of elements of the Query doubles.

I had a component with nested components and I was querying for the children in the parent.

I'm on my phone right now, I will try to put an example soon.


I'm on my phone right now, I will try to post an example soon.
