### ISSUE TITLE
Using trackBy with ngFor causes elements after the element being added/removed to be redrawn

### ISSUE THREAD

**Issue by apkostka** [angular/angular#8011] opened 2016-04-11 19:11 UTC
If using `trackBy`/`ngForTrackBy` to track the addition/removal of an element to the array being iterated in `ngFor`, it appears the elements are actually redrawn rather than re-ordered. I'm using 2.0.0-beta.14.

Issue can be seen here using the network/Docs tab in chrome console: http://plnkr.co/edit/qZf6yv?p=preview

Open the Network tab and then remove one of the Heroes near the top of the list. Every hero item below that one will be redrawn, as seen by the iframe being reloaded. This behavior can be repoduced without an iframe present, but this makes it easier to see the behavior.

It's possible that I misunderstood the functionality of `trackBy`, but it was my understanding that it would leave elements in place if they retained the same reference property from the custom track-by function.

**EDIT**: I previously thought that the iframes were triggered by a reflow and this somehow caused their content to refresh, but that's apparently not always the case. [This plunker](https://plnkr.co/edit/RTEHgQ?p=preview) recreates the functionality of adding a node with an iframe child, but the other iframes don't reload their content. It appears that ngTrackBy may not fully be working in 2.0.0-beta.14.

**Comment by robwormald** [comment] 2016-04-12 05:26
@apkostka is this a dupe of https://github.com/angular/angular/issues/7689 ? or is it specific to trackBy usage?

**Comment by apkostka** [comment] 2016-04-12 19:11
Ah, thank you for pointing me to that, @robwormald . I never would have connected the two. It appears that they are related, I'm seeing the same behavior as seen here: http://plnkr.co/edit/qZf6yv?p=preview

I guess I imagined that trackBy would prevent items being re-ordered from being removed/added to the DOM, but it looks like this might just be a non-ideal implementation of ngFor. Feel free to mark as duplicate.

**Comment by CaptainCodeman** [comment] 2016-04-13 00:01
So if we have 100 items rendered and the first one is removed, it re-renders the other 99?!? Or if one is added then I presume they are re-rendered too?

**Comment by pkozlowski-opensource** [comment] 2016-06-02 12:55
Closing as duplicate of #7689

**Closed by pkozlowski-opensource** 2016-06-02 12:55 UTC
