### ISSUE TITLE
Error link reported by ag

### ISSUE THREAD

**Issue by osorito** [angular/angular#56370] opened 2024-06-10 20:51 UTC
### Describe the problem that you experienced

Reported error in angular suggest two links for answer on an error but said link does not work.

NG0913: An image with src https://static.onecms.io/wp-content/uploads/sites/44/2022/03/01/cucumber-sandwich.jpg has intrinsic file dimensions much larger than its rendered size. This can negatively impact application loading performance. For more information about addressing or disabling this warning, see https://angular.dev/errors/NG0913. Find more at https://angular.dev/errors/NG0913

The links 
https://angular.dev/errors/NG0913
https://angular.dev/errors/NG0913
Report page not found

### Describe what you were looking for in the documentation

Looking for a solution to the problem described by angular.

### Describe the actions that led you to experience the problem

Loading an image of base64 on an angular form with image html.

### Describe what you want to experience that would fix the problem

That would depend on the answers provided by the links that do not work.

### Add a screenshot if that helps illustrate the problem

![Screenshot 2024-06-10 at 4 47 30 PM](https://github.com/angular/angular/assets/22304375/baf9ad07-1eed-4b9d-aadc-184e8ac97a53)

**Comment by JeanMeche** [comment] 2024-06-10 21:00
Duplicate of #56351.

**Closed by JeanMeche** 2024-06-10 21:00 UTC
