### ISSUE TITLE
ERROR in Cannot read property 'flattenedMappings' of null when upgraded from angular 8 to angular 9?

### ISSUE THREAD

**Issue by acharyaks90** [angular/angular#35715] opened 2020-02-27 10:51 UTC
ERROR in Cannot read property 'flattenedMappings' of null when upgraded from angular 8 to angular 9?

My package.json 

{
  "name": "myprojects",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "start_prod": "ng serve --prod",
    "build_prod": "ng build --prod",
    "start_staging": "ng serve -c staging",
    "build_staging": "ng build -c staging",
    "localhost": "ng serve -c localhost",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^9.0.0",
    "@angular/cdk": "^7.3.7",
    "@angular/cli": "9.0.1",
    "@angular/common": "9.0.0",
    "@angular/compiler": "9.0.0",
    "@angular/core": "9.0.0",
    "@angular/forms": "9.0.0",
    "@angular/material": "^8.2.3",
    "@angular/platform-browser": "9.0.0",
    "@angular/platform-browser-dynamic": "9.0.0",
    "@angular/router": "9.0.0",
    "@ng-select/ng-select": "^2.13.1",
    "angular-font-awesome": "^3.1.2",
    "angular-gauge-chart": "^0.6.0",
    "angular-highcharts": "7.2.0",
    "angular-mydatepicker": "^0.4.0",
    "angular2-draggable": "^2.3.2",
    "angular2-moment": "^1.9.0",
    "angulartics2": "6.3.1",
    "bootstrap": "4.1.0",
    "core-js": "^2.4.1",
    "font-awesome": "^4.7.0",
    "fusioncharts": "^3.13.4",
    "google-libphonenumber": "^3.2.5",
    "highcharts": "^7.1.1",
    "intl": "^1.2.5",
    "json2typescript": "^1.0.5",
    "ng-circle-progress": "^1.5.0",
    "ng-multiselect-dropdown": "^0.2.3",
    "ng-pick-datetime": "^7.0.0",
    "ng2-bootstrap-modal": "^1.0.1",
    "ng2-nouislider": "^1.8.2",
    "ng5-slider": "^1.2.4",
    "ngx-bootstrap": "^5.3.2",
    "ngx-clipboard": "^12.3.0",
    "ngx-drag-scroll": "^7.3.1",
    "ngx-ellipsis": "^2.0.7",
    "ngx-infinite-scroll": "^6.0.1",
    "ngx-international-phone-number": "^1.0.4",
    "ngx-scroll-event": "^1.0.8",
    "ngx-select-dropdown": "^0.8.1",
    "ngx-sortable": "^1.0.1",
    "rxjs": "^6.5.4",
    "rxjs-compat": "^6.3.3",
    "tslib": "^1.10.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.900.1",
    "@angular/compiler-cli": "^9.0.0",
    "@angular/language-service": "9.0.0",
    "@types/jasmine": "~2.8.3",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "^12.11.1",
    "codelyzer": "^5.1.2",
    "jasmine-core": "~2.8.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~2.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~4.1.0",
    "tslint": "~5.9.1",
    "typescript": "3.7.5"
  }
}

**Comment by BuZZ-dEE** [comment] 2020-02-27 11:14
I can confirm this issue after uprading from 9.0.2 to 9.0.3

> ERROR in Cannot read property 'flattenedMappings' of null

**Comment by petebacondarwin** [comment] 2020-02-27 11:22
Thanks for reporting this issue. I am looking into it.

**Comment by petebacondarwin** [comment] 2020-02-27 11:24
Duplicate of #35709

**Closed by petebacondarwin** 2020-02-27 11:24 UTC

**Comment by raymondlwhuang** [comment] 2020-02-28 21:16
get the same issue
