### ISSUE TITLE
angularconsole.com is down

### ISSUE THREAD

**Issue by neophyt3** [angular/angular#37609] opened 2020-06-16 14:08 UTC
# 📚 Docs or angular.io bug report

### Description

https://angularconsole.com link in is down

### What's the affected URL?**
 
https://angular.io/cli#cli-overview-and-command-reference
https://angularconsole.com

</code></pre>

**Comment by gkalpak** [comment] 2020-06-16 14:16
Closing as a duplicate of #37604 (since it's the same underlying issue).

**Closed by gkalpak** 2020-06-16 14:16 UTC
