### ISSUE TITLE
HTTP GET Query string encoding

### ISSUE THREAD

**Issue by ugdpy** [angular/angular#24754] opened 2018-07-04 08:31 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

The HttpClient.get() method doesn't encode some characters like '+' and it makes it impossible to pass them as parameters.
Here's an example : 

```typescript
  constructor(
    private http: HttpClient,
  ) {
  }

  httpRequest() {
    this.http.get('example.com', {
      params: {
        encoded: encodeURIComponent('i\'m URI encoded +'),
        notEncoded: 'i\'m not encoded +'
      }
    }).subscribe();
    this.http.get('example.com', {
      params: new HttpParams()
        .set('encoded', encodeURIComponent('i\'m URI encoded +'))
        .set('notEncoded', 'i\'m not encoded +'),
    }).subscribe();
    this.http.get('example.com?'
      + 'encoded=' + encodeURIComponent('i\'m URI encoded +')
      + '&'
      + 'notEncoded=' + 'i\'m not encoded +'
    ).subscribe();
  }
```

This code generate the following requests

```
http://localhost:4200/example.com?encoded=i%27m%2520URI%2520encoded%2520%252B&notEncoded=i%27m%20not%20encoded%20+
http://localhost:4200/example.com?encoded=i%27m%2520URI%2520encoded%2520%252B&notEncoded=i%27m%20not%20encoded%20+
http://localhost:4200/example.com?encoded=i%27m%20URI%20encoded%20%2B&notEncoded=i%27m%20not%20encoded%20+
``` 

The + character can't be encoded as %2B because if i supply it already encoded the % will be encoded and if i don't it will not be encoded.
The only workaround is to build the query string in the provided URL but it doesn't feel right ...

## Expected behavior

The '+' charracter in the HTTP param provided to the get method should be encoded as %2B

## Minimal reproduction of the problem with instructions

see Current behavior

## Environment

<pre><code>
Angular version: 6.0.4

Browser:
- [x] Chrome (desktop) version 67.0.3396.99
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version 60.0.2
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
- [x] Vivaldi version 1.15.1147.52
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by ugdpy** [comment] 2018-07-04 08:51
UPDATE: 
 I may have found the root cause of the 'bug' : 
```typescript
encodeURIComponent('+');
new HttpUrlEncodingCodec().encodeValue('+')
```
Returns respectively '%2B' and '+', or accoring to the documentation : 
```typescript
/**
 * A `HttpParameterCodec` that uses `encodeURIComponent` and `decodeURIComponent` to
 * serialize and parse URL parameter keys and values.
 *
 *
 */
export declare class HttpUrlEncodingCodec implements HttpParameterCodec {
    encodeKey(k: string): string;
    encodeValue(v: string): string;
    decodeKey(k: string): string;
    decodeValue(v: string): string;
}
```
The HttpUrlEncodingCodec is supposed to use the encodeURIComponent function but it looks like it's using the encodeURI function

**Comment by trotyl** [comment] 2018-07-04 09:16
Duplicate of https://github.com/angular/angular/issues/18261

**Comment by alxhub** [comment] 2018-12-18 23:53
Closing as a duplicate.

**Closed by alxhub** 2018-12-18 23:53 UTC
Labels: comp: http
