### ISSUE TITLE
No Component Input bindings with Directive Composition Api if routed

### ISSUE THREAD

**Issue by web-dave** [angular/angular#52187] opened 2023-10-12 14:40 UTC
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

No

### Description

When I route a component that has inherited inputs from a directive via composition, the route params are not bound to the component.
Only if I use a wrapper component for it

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-4nvh2b

### Please provide the exception or error you saw

```true
The Inputs are not set, no OnChange hook, no data
```

### Please provide the environment you discovered this bug in (run `ng version`)
This happens with 17.next and 16.2.9

My local ng v:
```true

Angular CLI: 17.0.0-next.8
Node: 18.13.0
Package Manager: npm 8.19.3
OS: darwin arm64

Angular: 17.0.0-next.8
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.0-next.8
@angular-devkit/build-angular   17.0.0-next.8
@angular-devkit/core            17.0.0-next.8
@angular-devkit/schematics      17.0.0-next.8
@schematics/angular             17.0.0-next.8
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.0
```

**Comment by web-dave** [comment] 2023-10-12 14:49
OK. Interesting. 
(I was playing with this in my stream)

**Comment by atscott** [comment] 2023-10-17 17:14
Indeed, this is a duplicate of #49734. The input binding in the Router uses the component mirror to get input names and set them.

**Closed by atscott** 2023-10-17 17:14 UTC
Labels: area: router
