### ISSUE TITLE
Provide InjectionToken with factory provider in a component level 

### ISSUE THREAD

**Issue by sharshuv-quotient** [angular/angular#50338] opened 2023-05-16 21:00 UTC
### Description

Today, if you want to provide something with a factory provider in a component level, you have to separately create the InjectionToken and the factory function like so:

```ts
const TOKEN = new InjectionToken('my token');

...
{
  provide: TOKEN,
  useFactory: () => ... 
}
```

If you want to provide the value in root, you have a better option:

```ts
const TOKEN = new InjectionToken('my token', {
  factory: () => ...
});
```

Why is this better? 
* You have type inference for the factory value
* Your logic is encapsulated. This token knows how its value is defined and does not need to trust consumers to provide the value properly + your factory function is not exposed and cannot be used elsewhere. 
* You can instantly start using this token without needing to set up anything else / create any other kind of boilerplate code. 

Unfortunately, if you want this token to be provided in a component level, and not the root level, you can't do that. As angular's component "providers" property does not allow for InjectionTokens.

### Proposed solution

Support passing an injection token in the "providers" array of a component (and module). If this token defines its own factory - it should be used. If not - a runtime exception should be thrown. It's better if we could even type the injection token differently, so only ones that define their factory can be used. 

### Alternatives considered

Use the "FactoryProvider" syntax, which is less ideal based on what I described above. 

I'm willing to try to implement this myself, if someone with more experience with the Angular source code can point me in the right direction.

**Comment by JeanMeche** [comment] 2023-05-16 21:05
`As angular's component "providers" property does not allow for InjectionTokens. ` 

What do you mean by that ?

**Comment by garrettld** [comment] 2023-05-17 11:03
I think this is a duplicate of #49807.

**Comment by alxhub** [comment] 2023-05-17 21:55
Agreed, this is a special case of #49807.

**Closed by alxhub** 2023-05-17 21:55 UTC
Labels: area: core, core: di
