### ISSUE TITLE
using length in the same ngIf with async pipe and as

### ISSUE THREAD

**Issue by teamIgal** [angular/angular#47429] opened 2022-09-14 12:24 UTC
### Description

hello there i have an issue i could find if it was possible to do or not

<div *ngIf="(cars$ | async as car)?.length>
i would like to know if something like this is possible.

i know that i can add an <ng-container> that will have the (cars$ | async as cars) and in my div put cars?.length but it would just be more understandable and easy to use.

### Proposed solution

my example above:
<div *ngIf="(cars$ | async as car)?.length>

### Alternatives considered

i know you might just tell me to use the ng-container solution.
this is just a quality of life feature

**Comment by pkozlowski-opensource** [comment] 2022-09-14 13:20
I'm sorry but it is not totally clear what is the problem that you are describing, a concrete code example would be needed (ideally in stackblitz).

In any case we've got a number of issues opened for improvements around the async pipe, see [the list](https://github.com/angular/angular/issues?q=is%3Aopen+is%3Aissue+label%3A%22common%3A+async+pipe%22). This is something we are actively discussing in the team but have no exact plans yet. 

I'm going to close this issue as I don't see anything actionable for us here, given the description.

**Closed by pkozlowski-opensource** 2022-09-14 13:20 UTC

**Comment by JoostK** [comment] 2022-09-14 13:24
I deduce from the title this is a duplicate of https://github.com/angular/angular/issues/43907
