### ISSUE TITLE
AoT compiler doesn't recognize compilerOptions paths from tsconfig

### ISSUE THREAD

**Issue by rubber-duck** [angular/angular#13008] opened 2016-11-21 15:25 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Running AoT compiler on valid typescript code fails because the AoT compiler doesn't know how to honor tsconfig.json `compilerOptions.paths`, for example in my project I get `Error: Unexpected value 'AppComponent' declared by the module 'AppModule'`

**Expected behavior**

AoT should produce valid output, if I change imports to use relative paths everything works fine.

**Minimal reproduction of the problem with instructions**

This is a minimal [starter project](https://github.com/rubber-duck/angular2-webpack2-setup/tree/aot-path), **bug repro is on the `aot-path` branch**. 

To reproduce : 

- clone the project, check out the `aot-path` branch
- `npm install`
- `npm run scss` to compile scss -> css (because components reference css file so it will complain about it missing if you don't do this)
- `npm run ngc` - this will run AoT compiler and you will get `Error: Unexpected value 'AppComponent' declared by the module 'AppModule'`

[`app.module.ts` imports `AppComponent` from `components/app.component`.](https://github.com/rubber-duck/angular2-webpack2-setup/blob/aot-path/src/app/app.module.ts#L3)

[`components/*` is mapped inside of `tsconfig,aot.json` in `compilerOptions.paths` to `app/*`.](https://github.com/rubber-duck/angular2-webpack2-setup/blob/aot-path/tsconfig.aot.json#L17)

If you do `npm run build:dll` and then `npm run compile:dev` which builds without the AoT you will see that this is valid code and TS/WebPack knows how to deal with this.

**What is the motivation / use case for changing the behavior?**

We use paths to alias folders in our project because using relative imports is really messy with deep nesting, eg. import '../../../../services/logging' vs import 'services/logging', etc. 
We need to use AoT for localization so right now I'm hacking away at the code and converting everything to relative paths but hopefully you can fix this and this is just a temporary workaround. 

**Please tell us about your environment:**
Windows 10

* **Angular version:** 2.2.x
 
* **Language:** TypeScript 2.0

* **Node (for AoT issues):** `node --version` = `v6.4.0`

**Comment by CumpsD** [comment] 2016-12-12 12:44
Is there a workaround for this?

We have lots of `import { CoreModule } from 'core';` type things, where `core` is also a mapped path. Changing all these occurrences in our app is quite a work.

**Comment by PleasantD** [comment] 2017-03-09 23:41
I'm trying to build multiple "apps" within the same project. Both app reference a module under a different root path. I build the module using ngc and then 

```
/dist/** --> all tsc and ngc output is supposed to go here
/framework/widget/** --> common widgets each should compile either with tsc or ngc to dist
/scripts/app-a/**
/scripts/app-b/**
```

`tsc` lets me have a single `tsconfig.json` file at the `/framework` and `/scripts` paths that configure and set the compilation entry points for each sub tree. For instance, framework compilation needs declaration files while scripts don't need declaration files but DO need paths for each of the framework modules so they can be included without relative references.

AoT **should** behave the same way, allowing me a single config file per path, but this doesn't work. Firstly, the output paths are wrong. `tsc` with an `outDir` of `../dist/framework` puts module a in `../dist/framework/a`. `ngc` drops the `/a` path. So each module built with `ngc` needs its own config file.

But then, when the apps are compiled `ngc` does the wrong thing with relative paths. If I don't put `genDir` in the application root then any factories referencing factories built for framework modules wind up with an extra `../` and fail. If I set the `genDir` with a relative path to the root then the factories all get constructed, but the references to local components is off.

If `genDir` is `./aot` then that puts in `/scripts/aot/**` but `/scripts/aot/a/app.component.ngfactory.ts` tries to import `../../dist/framework/widget/src/widget.component.ngfactory.ts` (which doesn't exist) instead of `../../dist/framework/widget/src/widget.component.ngfactory.ts` which it just constructed.

If `genDir` is `../aot` then that puts in `/aot/**` but `/aot/a/app.component.ngfactory.ts` now cannot find `./app.component`.

**Comment by jcimoch** [comment] 2017-03-16 08:39
Is it going to be fixed any time soon?

**Comment by pjmagee** [comment] 2017-04-12 10:58
We invested into developing with barrels since Angular2. I think support for barrels with AoT should definitively be added.

**Comment by ggranum** [comment] 2017-04-13 08:47
I'm confused, and thus a bit worried, as I don't seem to have this problem. I was checking to see if there were any issues I should be concerned with regarding AoT and `paths` when I came across this ticket. @pjmagee , can you tell me if what my project is doing [here](https://github.com/ggranum/tangential/blob/master/tsconfig.json) is what you mean?

There is an issue I have encountered where I cannot use the named path *within* the target of the named path. I believe that is what the ticket in general and @PleasantD specifically are describing, but am not completely certain. That is to say, it is totally ok to map "src/lib/foo" to "NamedPath", but if you are in the file `src/lib/foo/bar.ts` you cannot use `import {Foo} from 'NamedPath';` to import Foo from `src/lib/foo/foo.ts`. You have to use a relative import, `import {Foo} from './foo';`. Using NamedPath to import Foo from within `src/lib/baz` is fine. 

The above imports assumes a file structure like so: 
src/lib/foo
-------- /index.ts // re-export everything
-------- /foo.ts  // class Foo
-------- /bar.ts  // attempt to import Foo from foo

Other factors I've run into that make it 'harder' to use named paths have to do with the latest Angular CLI layout - the are the missing 'baseDir' in the root tsconfig, and the paths have to be redeclared in each sub-tsconfig file (there might be an easier way, but that was the first thing I found that worked). Not really 'issues', just things that seem to cause a series of 'I made this work but now it breaks over here' problems, when you're not incredibly familiar with tsconfig files etc.

Not sure I'm even addressing the issue in this ticket, but hopefully I am. Because if I'm not, then that means I might run into something new soon, and that wouldn't be awesome :~). Confirmation that what I describe is in fact the issue would be a great relief.

**Comment by kylecordes** [comment] 2017-04-13 12:50
I'm also curious what's going on here, I am using tsconfig paths with AOT and having fine results also. Further I have not seen the problem of "cannot use the named path within the target of the named path".  My use case appears to be somewhat different than those discussed above though, I am using the paths setting to help nail down code brought in from various dependencies, to always use the same Angular.

Here is a repo where I use it, possibly helpful.

https://github.com/OasisDigital/scalable-enterprise-angular

**Comment by ggranum** [comment] 2017-04-20 17:36
@kylecordes I double checked, and you're right,  "mapped paths within target of the named path"  *usually* works just fine. However, I was just forcefully reminded that it breaks injections into guards, at least if those guards are assigned to a lazy-loaded module. Might break guard injections for all cases, I'm not sure. 

For Google visitors: if you're using mapped paths and get an `Uncaught Error: Can't resolve all parameters for FooGuard: (?)` error, check that you're importing whatever class the `?` represents using a relative path and not a mapped path or a path that references through an index file.

**Comment by snewell92** [comment] 2017-06-28 14:04
I have the set up describe in [this comment](https://github.com/angular/angular/issues/13008#issuecomment-285520443), namely the one where my `genDir` is `../aot` because my project is a fullstack app with a front/back side, thus I want all my front end output (JIT out, AOT out, bundle OUT, etc. etc.) to be one level down in my `public` folder, but the aot compiler doesn't set the references to my modules/components correctly in the emitted factories.

```
Error at projectroot/public/aot/app/app.component.ngfactory.ts:10:21:
   Cannot find module './app.component'.
Error at projectroot/public/aot/app/app.module.ngfactory.ts:10:21:
   Cannot find module './app.module'.      
Error at projectroot/public/aot/app/app.module.ngfactory.ts:11:21:
   Cannot find module './app.component'.   
```

I'm gonna see if I can get a small minimal working example to demonstrate... hopefully I can resolve it just by doing that, but wanted to throw in my comment if other ppl have the same issue, although the `genDir` might be another issue...?

Win 10
Nodejs 8.0.0
NPM 5.0.3
`@angular/compiler-cli` 4.2.4

**Comment by alfaproject** [comment] 2017-11-17 11:40
Is there any hope to have this sorted out? ):

**Comment by dirkluijk** [comment] 2018-02-05 20:54
This still is an issue for me when using ng-packagr.

**Comment by RamyEl-basyouni** [comment] 2018-08-01 07:48
@aburht re-run **ng serve --aot** again, it is still an issue at angular cli repo caused by installed globally angular-cli is different from your local in-project angular-cli version

**Comment by JoostK** [comment] 2020-05-28 20:09
Unfortunately I cannot reproduce using the original repro, as that doesn't compile for me. However, using path mappings is not a problem today, so I'll go ahead and close this as resolved. For anyone still experiencing issues, please do open a new issue with reproduction.

**Closed by JoostK** 2020-05-28 20:09 UTC
Labels: comp: compiler, freq2: medium, severity3: broken, state: in investigation, type: bug/fix
