### ISSUE TITLE
Async Form Validator not running when form is instantiated

### ISSUE THREAD

**Issue by daniel-seitz** [angular/angular#43369] opened 2021-09-07 06:41 UTC
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

No

### Description

Hi @AndrewKushnir, I hope you're doing well.

**Main issue:**
When having a form and control with an async validator, then upon creation the statusChanges (once completed) does NOT fire when the form is in use in the template. (if it is _not_ in use it seems to work). In the stackblitz you see a template where fg4 is commented. In the console I am missing the 'fg1 VALID', same for fg2 and fg3. This happens when you use one of the two attribute directives: [formGroup] or [formControl].

Just also added control9 and control10 which shows the same behavior when using the control directly instead of residing inside of a formGroup.

**Additionally**
- Are we missing an initial "Pending" in most cases? When you uncomment the 'Additional Problem'-Section, you see that some of the Pending events are emitted but I would expect to always see them, regardless of using addControl or not. 
- Also there seems to be a bug when using [formGroup], then the Pending is not emitted at all.

I discovered the issue with nested formGroup and controls, trying to reproduce I think the plunker might be the most minimal reproduction. As solution hopefully fixes my bugs.

This is related to these: 
https://github.com/angular/angular/issues/20424
https://github.com/angular/angular/issues/14542
https://github.com/angular/angular/pull/38354
https://github.com/angular/angular/pull/20806

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-p2swjl?file=src%2Fapp%2Fapp.component.html

### Please provide the exception or error you saw

```true
There is no error, the observable is not firing.
```

### Please provide the environment you discovered this bug in

```true
Angular CLI: 12.2.1
Node: 14.15.0
Package Manager: yarn 1.22.5
OS: win32 x64

Angular: 12.2.1
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, material, material-moment-adapter
... platform-browser, platform-browser-dynamic, router        

Package                         Version
---------------------------------------------------------     
@angular-devkit/architect       0.1202.1
@angular-devkit/build-angular   12.2.1
@angular-devkit/core            12.2.1
@angular-devkit/schematics      12.2.1
@schematics/angular             12.2.1
rxjs                            6.6.6
typescript                      4.3.5
```

**Comment by luke-atp** [comment] 2021-11-30 19:44
After some further investigation, it appears that this is expected behavior (at least in some circumstances).

There is a specific test case in `form_group_spec.ts`, `should cancel initial run of the async validator and not emit anything`, that exhibits the behavior that is being seen. Specifically, that no status change event is emitted if a an async validator is interrupted by another change with `emitEvent: false`.

My initial solution was to try the following (3 lines ADDED, 1 MODIFIED):

```typescript
export abstract class AbstractControl {
...
  // ADDED
  private _pendingEmit: boolean = false;
...
  private _runAsyncValidator(emitEvent?: boolean): void {
    if (this.asyncValidator) {
      (this as {status: FormControlStatus}).status = PENDING;
      this._hasOwnPendingAsyncValidator = true;
      // ADDED
      this._pendingEmit ||= emitEvent ?? true;
      const obs = toObservable(this.asyncValidator(this));
      this._asyncValidationSubscription = obs.subscribe((errors: ValidationErrors|null) => {
        this._hasOwnPendingAsyncValidator = false;
        // This will trigger the recalculation of the validation status, which depends on
        // the state of the asynchronous validation (whether it is in progress or not). So, it is
        // necessary that we have updated the `_hasOwnPendingAsyncValidator` boolean flag first.
        // MODIFIED: passing `this._pendingEmit` instead of `emitEvent` argument
        this.setErrors(errors, { emitEvent: this._pendingEmit });
        // ADDED
        this._pendingEmit = false;
      });
    }
  }
...
```

My goal was to create a class level variable that if set to `true` would force the `emitEvent` value to remain `true` until at least one validator call completed. This forces at least one state change event on the construction of the control. This passed all existing tests, except the test mentioned above. If it is desired behavior to be able to cancel an emit as described in the unit test, then this change would not work.

In the meantime, one possible workaround could be to include the completion of all async validators as part of the page loading process. When the parent control finally emits VALID/INVALID, it should be safe to bind using `[formGroup]`, for example. I believe that would be safe based on my understanding, but I haven't tested it yet.

**Comment by luke-atp** [comment] 2021-12-01 21:02
After more review, I believe there is no way to trust the `statusChanges` value when the form is bound using `FormGroupDirective` (or any of the other directives for binding form controls).

I attempted to delay the binding of a form to `[formGroup]` to see if it was simply an initialization problem. The example app is here: https://stackblitz.com/edit/angular-ivy-uwzwxj?file=src/app/app.component.ts

I am using a `loading$` subject to wait for the form status to change from `PENDING` before the DOM elements are added. This resolves the initial load of the status getting stuck in `PENDING`. However, other changes to the form can cause the same issue.

For example, clicking the "Add Location" button in the sample application for the first time after a page load will cause the form to get stuck in pending until some other change occurs. This only happens the first time. After that it no longer triggers the async validator to run. This button simply adds an empty `FormControl` to a `FormArray` in the form.

Clicking the "Add Control" button will do one of two things. If you click it a single time and wait, it will cause the "Sync Status" value to change to `PENDING` and the back to `VALID`. If you click it twice in a row it will update both the "Async Status" and "Sync Status" to `PENDING`, but only the "Sync Status" will change back to `VALID`.

I will also point out that the addition of "Sync Status" to the view also causes an `ExpressionChangedAfterItHasBeenCheckedError`. This is a fundamental issue with using the synchronous value from the form (unless someone can tell me another way).

The behavior above disappears if the `[formGroup]` section is removed from the template.

This indicates two issues with the current implementation of the `FormGroupDirective`:
1. Ancillary changes to the form cause async validators to run on unrelated form controls. In the sample application, the addition of a value to the form array a new control on the form group 
2. Any call to `_updateDomValue()` will leave the form in `PENDING` if there are any incomplete async validators.

I'm not really sure how to proceed at this point. Can anyone on the angular team indicate if this is likely to be reviewed? Would a pull request with a change in behavior demonstrated in my previous post be considered?

**Comment by UserGalileo** [comment] 2021-12-11 02:35
Hi @luke-atp , isn't this the same as #41519? Looks like it's the same problem, do you see any difference?

Just asking, cause I'm stuck with this issue too and having one single detailed issue could help solving it :)

**Comment by luke-atp** [comment] 2021-12-13 14:21
@UserGalileo, I do think this is the same issue. #41519, also indicates the call to `_updateTreeValidity()` in `_updateDomValue()` as the cause.

My current solution, is to trigger a manual `updateValueAndValidity()` on my form after the completion of my async validators. This isn't ideal, but for my use-case is working for now. Below is the gist of my workaround:

```typescript
// Create a `Subject` for observing when async validators complete.
private _updateValueAndValidity$ = new Subject<void>();
...
// Subscribe to the following observable.
// Note: I found in my testing that the `delay()` ensures that the form is in the correct state
// before running `updateValueAndValidity()`, but it probably isn't guaranteed.
this._updateValueAndValidity$
   .pipe(
    delay(0),
    tap(() => this.form.updateValueAndValidity())
  );
...
// On completion of async validators, call next on the `Subject`.
this.._updateValueAndValidity$.next()
```

A `debounce()` may also be a good idea on the observable if there could be many simultaneous values fed to the `Subject`.

I've also investigated the possibility of writing my own implementation of some of the form classes and directives, but they are too tightly coupled at the moment to make this viable.

**Comment by fomenkogregory** [comment] 2022-01-15 11:25
Hey, guys, is this somehow related to my question https://stackoverflow.com/q/70708799/12006158?

**Comment by jmroon** [comment] 2022-06-10 16:27
I have yet to determine if this is fully reliable, but in the component hosting the form, you can retrigger the validation manually at the end of onInit:

```ts
ngOnInit() {
  this.formGroup = new FormGroup(...etc);
  ...
  setTimeout( () => { 
    this.formGroup['myAsyncValidatedControl'].updateValueAndValidity();
  });
}
```

**Comment by pookdeveloper** [comment] 2023-09-20 14:56
I have this solution for wait asyncValidatos:

``` typescript
  const asyncValidationObservables = this.formUtilsService.validateRecursiveForm(this.form);
    this.formUtilsService.getObservableValidations(asyncValidationObservables).subscribe((results) => {
      if (this.form.valid) {
        this.movimientoValidado.emit(this.form.value);
      }
    });
    
    
      validateRecursiveForm(abstractControl: FormControl | FormGroup | FormArray | AbstractControl, emitEvent = true): any[] {
    const asyncValidations: any[] = [];
    if (abstractControl instanceof FormGroup || abstractControl instanceof FormArray) {
      for (const control in abstractControl.controls) {
        const currentControl = abstractControl.get(control);
        const validaciones = this.validateRecursiveForm(currentControl, emitEvent);
        if (validaciones.length > 0) {
          asyncValidations.concat(validaciones);
        }
        // Iteramos hacia dentro antes de llamar a las validaciones del padre
        console.log('===> asyncValidations ', asyncValidations);
        this.validateAbstractControl(currentControl, asyncValidations, emitEvent);
        console.log('===> asyncValidations ', asyncValidations);
      }
    } else if (abstractControl instanceof FormControl) {
      console.log('===> abstractControl ', abstractControl);
      this.validateAbstractControl(abstractControl, asyncValidations, emitEvent);
    }
    console.log('===> asyncValidations ', asyncValidations);
    return asyncValidations;
  }

  private validateAbstractControl(
    abstractControl: FormControl<any> | FormGroup<any> | FormArray<any> | AbstractControl<any>,
    asyncValidations: any[],
    emitEvent: boolean
  ) {
    if (abstractControl.asyncValidator) {
      abstractControl.markAsTouched();
      asyncValidations.push(abstractControl.asyncValidator(abstractControl));
    } else if (abstractControl.validator) {
      abstractControl.markAsTouched();
      abstractControl.updateValueAndValidity({ emitEvent: emitEvent });
    }
  }
    
```

**Comment by avrim-tr** [comment] 2023-10-17 14:32
This bug also happens in my project.
Is it a bug?
Is it planned to solved?
Is settimeout a good solution?

**Comment by JeanMeche** [comment] 2024-04-09 16:44
I'm closing this as a dupe of #41519. 
The validator runs but the initial one that should be emitting is getting cancelled when when adding a control via the directive. 
#55185 is a proposed fix for this.

**Closed by JeanMeche** 2024-04-09 16:44 UTC
Labels: area: forms, P3
