### ISSUE TITLE
renderer.setElementStyle with !important

### ISSUE THREAD

**Issue by arins** [angular/angular#12302] opened 2016-10-14 15:12 UTC
[ x] feature request

**Current behavior**
currently renderer.setElementStyle can not set !important
renderer.setElementStyle(el, styleProperty, styleValue) 

**Expected behavior**
renderer.setElementStyle(el, styleProperty, styleValue, important) 
important could be a optional boolean

**What is the motivation / use case for changing the behavior?**
to be able to set !important programmatically

Angular 2.0.2

* **Browser:** [all ]

 
* **Language:** [all ]

**Comment by DzmitryShylovich** [comment] 2016-10-14 15:13
Thanks for reporting this issue. However this issue is a duplicate of an existing issue https://github.com/angular/angular/issues/12009 . Please subscribe to that issue for future updates.

**Comment by pkozlowski-opensource** [comment] 2016-10-14 15:21
Indeed a duplicate of #12009 - thnx @DzmitryShylovich

**Closed by pkozlowski-opensource** 2016-10-14 15:21 UTC
