### ISSUE TITLE
Memory leak? Component stays in memory after touching an input field that has ngModel

### ISSUE THREAD

**Issue by YoeriPostma** [angular/angular#46035] opened 2022-05-18 11:08 UTC
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

No

### Description

I have setup a simple basic Angular application with routing on my side to reproduce the issue.
Basic summary, when touching an input(mouse, keyboard) with ngmodel on it, the component does not gets destroyed. If you don't touch the input the component gets destoyed when navigating to another component. I believe it has something to do with "valueAccessor" that keeps a reference to the component. ( i see this behaviour in Angular 11, 12 and 13).
Please see screenshots below:

step 1: opening up the application no navigation done and created a heap snapshot.
![1_start_without_navigation](https://user-images.githubusercontent.com/52561363/169027207-b4bdf1b2-9f7e-4643-bce6-a13bbd8b8941.png)

step 2: for reference navigate through some components and back to the root, start garbage collector, no sign of any component in the second heap snapshot.
![2_navigate_between_components_collect_garbage_afterwards](https://user-images.githubusercontent.com/52561363/169027225-b5510c60-4fed-4200-9722-959469514d5d.png)

step 3: again navigating through some components but now touching the input on "navigateTo" component, back to root, start garbage collector, now the component is still visible in the snapshot.
![3_touching_input](https://user-images.githubusercontent.com/52561363/169027272-0322e279-53fb-42dc-885b-1cd058e11bfc.png)

![4_back_to_root_collect_garbage_component_not_destroyed](https://user-images.githubusercontent.com/52561363/169027298-8a9b8157-e093-4db7-a54b-ce469abe68ff.png)

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.3.5
Node: 16.15.0
Package Manager: npm 8.5.5
OS: win32 x64

Angular: 13.3.7
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router     

Package                         Version
---------------------------------------------------------  
@angular-devkit/architect       0.1303.5
@angular-devkit/build-angular   13.3.5
@angular-devkit/core            13.3.5
@angular-devkit/schematics      13.3.5
@angular/cli                    13.3.5
@schematics/angular             13.3.5
rxjs                            6.6.7
typescript                      4.6.4
```

**Comment by jessicajaniuk** [comment] 2022-05-19 23:26
@YoeriPostma Can you please create a reproduction in StackBlitz for us to look at? That would be extremely helpful for us to dig into this. Thank you!

**Comment by YoeriPostma** [comment] 2022-05-20 08:11
Hi @jessicajaniuk 

Sure, also seems i can reproduce it in the stackblitz. (tested this from another machine to make sure it's not a browser-plugin related issue or something).

Still not sure if i do something wrong but to me it seems like an issue ;)
Let me know if i can assist on something. Thanks!

![image](https://user-images.githubusercontent.com/52561363/169483928-1a5cbd9f-27a1-4d5f-8b7e-0abeefd9927c.png)

[https://angular-ivy-wc2htm.stackblitz.io/](url)

**Comment by JoostK** [comment] 2022-05-20 12:13
This looks to be the same as #41047. The `HTMLInputElement` is detached but there's a retainer from `C++ roots`, which indicates a browser leak of some sorts. Also, this doesn't appear to repro consistently: the leak was not present after a reload and some route switches. Since the DOM element stores a reference to the component instance, this also means that the component stays in-memory.

You can test with the RC version of v14 which no longer attaches the component instance directly to the DOM elements. Other than that the leak doesn't appear to be caused by Angular, so closing for now. Feel free to follow up below though.

**Closed by JoostK** 2022-05-20 12:13 UTC
Labels: needs reproduction, memory leak, comp: forms

**Comment by YoeriPostma** [comment] 2022-05-20 13:06
Hi @JoostK 

_Also, this doesn't appear to repro consistently: ,_

 i do not agree on that, i can reproduce it consistently.
I think for larger projects (the one we are working at at the moment) this is causing some major performance issues after working a few hours in the application, closing tabs in our application and thus theoretically components getting destroyed doesn't solve the performance issues as the components don't get destroyed and stay in memory (can consistently reproduce this behavior). 

Opening a screen/tab, not touching any input element and closing the screen always nicely removes the component from memory. We have ruled out other memory issues.

my expertise on telling if this is a browser bug or Angular bug is unfortunately not sufficient but i can imagine that a lot of companies run into this issue making the acceptance of new (big) Angular applications harder.

think here indeed also a similar issue:
`https://stackoverflow.com/questions/64457843/memory-leak-in-chrome-what-are-blink-roots`

**Comment by YoeriPostma** [comment] 2022-05-24 10:42
Hi @JoostK 

Just to confirm, Angular release 14.0.0.-rc.1 seems to fix the issue in my small test setup.
no more __ngContext__ and thus components in my heap snapshots.

We will await release 14, thanks!

**Comment by Slembit** [comment] 2022-05-24 14:55
I actually think this is the same issue as https://github.com/angular/angular/issues/42848 which seems to be solved in v14.

I also had this problem when I interacted with elements that had an eventlistener (click) / ngModel and even events like (change) somewhere inside an ngif or ngfor which made it impossible to use v12.
There is also the issue of https://github.com/angular/angular/issues/41047 who is also the cause of some leaks I had
[core.umd.zip](https://github.com/angular/angular/files/8763863/core.umd.zip)
.

Both above issues has been fixed as far as I can see now in v14, however if you need to use v12 for a while longer there seems to be no update pending. What I did was to look up those 2 changes and try to merge them into v12 in @angular\core\__ivy_ngcc__\bundles\core.umd.js 
then I used patch-package to add a patch file.

I whish I knew how to do this properly without the patchfile, but for enyone interested I will provide my changes in a zipfile (I Used __ADDED__ and __MODFIED__ comments for you to see the changes

**Comment by YoeriPostma** [comment] 2022-05-24 19:02
Thanks @Slembit !
Will be helpfull for a lot of people.
Think for now we can manage but will upgrade to 14 asap when officially released.
