### ISSUE TITLE
this._fetchNamespace can return undefined here in very rare cases.

### ISSUE THREAD

**Issue by xban1x** [angular/angular#26265] opened 2018-10-05 05:11 UTC
It happens on both iOs and Android.

https://github.com/angular/angular/blob/d76531d16eb57391a8ee4cf3375a550e72307b67/packages/animations/browser/src/render/transition_animation_engine.ts#L738

StackTrace:

TypeError: undefined is not an object (evaluating 'this._fetchNamespace(t).listen')
  at listen(/main.f14a970125fee9c7a208.bundle.js:1:600385)
  at io(/main.f14a970125fee9c7a208.bundle.js:1:351499)
  at Pi(/main.f14a970125fee9c7a208.bundle.js:1:377681)
  at ji(/main.f14a970125fee9c7a208.bundle.js:1:376738)
  at createEmbeddedView(/main.f14a970125fee9c7a208.bundle.js:1:361200)
  at createEmbeddedView(/main.f14a970125fee9c7a208.bundle.js:1:357869)
  at _updateView(/main.f14a970125fee9c7a208.bundle.js:1:733848)
  at set(/main.f14a970125fee9c7a208.bundle.js:1:733246)
  at ai(/main.f14a970125fee9c7a208.bundle.js:1:368890)
  at ? (/main.f14a970125fee9c7a208.bundle.js:1:380104)
  at aa(/main.f14a970125fee9c7a208.bundle.js:1:388469)
  at ? (/camera.module.96a15bca41e4fcbf607c.chunk.js:1:71398)
  at Ri(/main.f14a970125fee9c7a208.bundle.js:1:378529)
  at detectChanges(/main.f14a970125fee9c7a208.bundle.js:1:360049)
  at ? (/camera.module.96a15bca41e4fcbf607c.chunk.js:1:69191)
  at o(/main.f14a970125fee9c7a208.bundle.js:1:686316)
  at onInvokeTask(/main.f14a970125fee9c7a208.bundle.js:1:305739)
  at runTask(/polyfills.540e115274a7f0ed29c6.bundle.js:1:14712)
  at invokeTask(/polyfills.540e115274a7f0ed29c6.bundle.js:1:20615)
  at ? (/polyfills.540e115274a7f0ed29c6.bundle.js:1:35839)

**Comment by nicholasp** [comment] 2020-10-13 18:46
Hi @xban1x ! How are you running transition_animation_engine? What kind of animation do you run? Could you please provide more information about this issue, so we can reproduce it? What angular version are you using? Does this happens after you run something specific at your component / code? Or some kind of interaction with the app like refresh app, history back etc?

**Comment by petebacondarwin** [comment] 2020-10-26 21:07
Closing due to a lack of reproduction. Thanks for trying to help @nicholasp.

**Closed by petebacondarwin** 2020-10-26 21:07 UTC
Labels: P4, comp: animations, freq1: low, needs clarification, needs reproduction, type: bug/fix
