### ISSUE TITLE
pipe content is not showing

### ISSUE THREAD

**Issue by Nilam-Pal** [angular/angular#57714] opened 2024-09-07 19:02 UTC
### Describe the problem that you experienced

Pipe content is not visible showing 404 error
 pipes#built-in-pipes

### Enter the URL of the topic with the problem

https://angular.dev/guide/pipes#built-in-pipes

### Describe the actions that led you to experience the problem

Angular.dev

### Describe what you want to experience that would fix the problem

url issue

**Comment by JeanMeche** [comment] 2024-09-07 21:32
Duplicate of #57704

**Closed by JeanMeche** 2024-09-07 21:32 UTC
