### ISSUE TITLE
Form with two-way bound input Only Validates from Inline Template

### ISSUE THREAD

**Issue by bennypowers** [angular/angular#10274] opened 2016-07-25 18:41 UTC
**I'm submitting a ...**  (check one with "x")

```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
input with two-way binding - [(ngModel)] - does not validate with correct pattern. (i.e. ng-invalid is applied, form.valid = true). Removing the two-way binding allows the form to validate.

**Expected/desired behavior**
inputs two-way bound to ngModel properties should validate according to the pattern attribute.

**Reproduction of the problem**
[This plunk](http://plnkr.co/edit/kulONefp0jtofTh9IGBn?p=preview) illustrates how swapping out an identical template from inline to templateUrl breaks the validation.

**What is the expected behavior?**
form should validate when template is loaded from url

**What is the motivation / use case for changing the behavior?**
non-broken templates

**Please tell us about your environment:**

pretty stuffy, but pleasant at night. mac os, atom, chrome - all the doodads
- **Angular version:** 2.0.0-rc.4 with forms 0.2.0f
- **Browser:** [ Chrome 52 ] 
  Seems to work as expected in firefox and safari
- **Language:** [ TypeScript 1.8.0 ]

**Comment by kara** [comment] 2016-10-17 17:06
@bennyp123 There is something funky going on here... will look into.

**Comment by DzmitryShylovich** [comment] 2016-12-11 00:02
@bennypowers is this still an issue after final? can u update your plunkr?

**Comment by bennypowers** [comment] 2016-12-11 08:13
Apparently so
https://plnkr.co/edit/eWP9exDAkWdGOfZAIPnt?p=preview

This plunkr was created from the link in the New Issue template

**Comment by DzmitryShylovich** [comment] 2016-12-11 08:34
thx. Pls add:
1. steps to reproduce.
2. expected behavior.

**Comment by bennypowers** [comment] 2016-12-11 08:59
Sorry, I'm not sure which steps to reproduce and expected behaviour I'm missing from OP 👆

Steps to reproduce: Create a form with HTML5 validation, use template file
Expected behaviour: form validates

**Comment by DzmitryShylovich** [comment] 2016-12-11 09:01
http://prntscr.com/dhzl0g what's wrong?

**Comment by bennypowers** [comment] 2016-12-11 12:46
![screen shot 2016-12-11 at 2 45 19 pm](https://cloud.githubusercontent.com/assets/1466420/21080151/8defd162-bfb0-11e6-91cf-158c5c9ea4f6.png)
comment inline template and uncomment templateUrl

**Comment by DzmitryShylovich** [comment] 2016-12-11 12:53
Ok I see, thx.
btw not sure it's forms related :)

**Comment by AndrewKushnir** [comment] 2020-05-27 22:16
Hi @bennypowers,

Based on the comment from @trotyl, it looks like the problem was in the RegExp and extra `\` symbols. I tried to reproduce the problem using the link provided earlier, but it looks like it doesn't work at this moment. I will close this ticket, feel free to open a new one if the issue still exists.

Thank you.

**Closed by AndrewKushnir** 2020-05-27 22:16 UTC
Labels: comp: forms, freq2: medium, severity2: inconvenient, triage #1, type: support
