### ISSUE TITLE
PWA not updating correctly

### ISSUE THREAD

**Issue by heiin** [angular/angular#43444] opened 2021-09-14 10:13 UTC
We use the angular service worker. Now we publish a new version and it gets updated. The user sometimes gets a new version and sometimes doesn't.

The pwa runs in a "folder" under the domain - whatever.com/mdp . The default route gets rerouted to another route /mdp/week - if the user navigates to this route initially (meaning typing it into the browser) everything is fine, the user has the new version. Now if you go to the main route /mdp initially you get the old version.

It seems as if the browser is caching files under /mdp and under /mdp/week differently. This kinda makes sense as the initial request to the server /mdp or /mdp/week are different and the browser doens't know that the server serves the same. The problem that I have is why one gets updated and the other does not. Maybe this is not even a problem with angular itself.

#39426 had a similar behaviour and our application in fact produced the same error due to the same reason. But fixing it didn't fixed the behaviour. The error didn't appear anymore  but the app still doesn't update correctly.

We used angular version 8.2.1 in the old application and 11.2.13 in the new.

Any help is greatly appreciated as I have some time pressure.

**Comment by gemron** [comment] 2021-09-14 10:56
see this : https://angular.io/api/core/ApplicationRef#isstable-examples-and-caveats

**Comment by gkalpak** [comment] 2021-09-14 10:56
Unfortunately, there is not much we can help with without getting more info. It is unclear how the app is set up and what might be causing the problem (or even what exactly the problem is). For example, how is the server configured, how is the ServiceWorker configured, how is routing configured, etc.

BTW, you can easily check what the ServiceWorker puts in cache after you visit the app, by opening the browser's DevTools, going to the `Application` tab and looking under `Cache Storage`.

##
I am going to close this issue, since there is no clear indication of a problem with Angular and the issue is not actionable in its current state. Feel free to continue the discussion below, though.

Also, happy to re-open and investigate if you can provide a minimal reproduction of the problem.

**Closed by gkalpak** 2021-09-14 10:56 UTC
