### ISSUE TITLE
Form: add `reset` feature in support of form clearing

### ISSUE THREAD

**Issue by wardbell** [angular/angular#6822] opened 2016-02-01 18:48 UTC
As of beta.2 there is no clean way to reset a form and clear the control class values, `pristine` and `untouched` in particular.

The trick described in (closed) #6819 is a temporary workaround

**Comment by zoechi** [comment] 2016-02-01 20:37
dup of #4933?

**Comment by wardbell** [comment] 2016-02-03 06:55
@zoechi I agree. It is a dup

**Comment by robwormald** [comment] 2016-02-04 05:22
closing as dupe of #4933

**Closed by robwormald** 2016-02-04 05:22 UTC
