### ISSUE TITLE
Strongly Typed Reactive Forms with Domain Interface

### ISSUE THREAD

**Issue by ChrTall** [angular/angular#49859] opened 2023-04-15 10:57 UTC
### Which @angular/* package(s) are relevant/related to the feature request?

forms

### Description

I would like to be able to pass my Domain interface to a formgroup, so that refactorings of property names are also applied to the forms or at least give compile time warnings.

Take this example interface model which is send to a rest endpoint by the Http-Client:
```
  export interface LoginModel {
  username: string;
  password: string;
}
```

For this model I have to create a FormModel:
```
export interface LoginFormModel extends FormGroup<{
  username: FormControl<string>,
  password: FormControl<string>
}> {}
```

Now I always have to keep the two interfaces in sync, when I change username to UserName and it is wasted time effort. 

### Proposed solution

I think it should be possible to infer types from a interface.

- primitives to FormControl
- Arrays and Sets to FormArray
- Object references to FormGroup

Something similar like https://github.com/iamguid/ngx-mf,
but officially supported and maintained without @ts-ignore workarounds.
 

### Alternatives considered

Keep the current state and create additional interfaces or just let the form infer types.
This does not address the refactoring issues, when property names change.

**Comment by JoostK** [comment] 2023-04-16 09:20
Duplicate of #46864.

**Closed by JoostK** 2023-04-16 09:20 UTC
