### ISSUE TITLE
@angular/cli current (6.something) memory load

### ISSUE THREAD

**Issue by OliverLeitner** [angular/angular#24441] opened 2018-06-12 10:44 UTC
## I'm submitting a...
[x] Bug report

## Current behavior

15 Megabytes taken in Chromium, 10 Megabytes in Firefox

## Expected Behaviour:

Near Native Memory usage, maybe a bit more considering that this is running in development mode...
I can do the same Demo Page in html5 and es5 compatible native js (if i absolutely wanna use js for it). That page takes about 0.5 to a max of 1 Megabyte.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/template
https://plainjs.com/
http://kangax.github.io/compat-table/es5/

## Minimal reproduction of the problem with instructions

commands issued:

```
ng new appname --style less --routing
ng generate component test
```

edit src/polyfill.js and uncomment the following for internet explorer:

```
import 'core-js/es6/function';
import 'core-js/es6/string';
import 'core-js/es6/array';
import 'core-js/es7/reflect';
```

all other files unedited.

## What is the motivation / use case for changing the behavior?

Not every user has 32 gigs of ram. and if the demo minimal app already takes 15 Megabytes (literally 1 image, one title and 3 links...), i seriously question the usability of this tool for really big projects.

Shouldnt the sample app display best practice?

## Environment

System: Windows 10 64bit

Browser:
- [x] Chrome (desktop) version 69.0.3451.0
- [x] Firefox version 60.0.2
- [x] IE version the one that comes with windows 10
 
For Tooling issues:
- Node version: v10.4.0
- Platform:  Windows

**Comment by OliverLeitner** [comment] 2018-06-12 10:54
to drive a comparision:

this is on my blog (wordpress) and theres quite some libs loaded in the background, including even jquery, which is a big one on its own...

https://www.neverslair-blog.net/2017/06/03/the-power-of-linux-containers/

it takes 4.4megs.

**Comment by trotyl** [comment] 2018-06-14 07:53
Duplicate of https://github.com/angular/angular/issues/8946

**Comment by mhevery** [comment] 2018-06-28 23:02
closing as dup of #8946

**Closed by mhevery** 2018-06-28 23:02 UTC
Labels: comp: core & compiler
