### ISSUE TITLE
Next-10: Invalid component stylesheet ID request

### ISSUE THREAD

**Issue by spock123** [angular/angular#58262] opened 2024-10-18 13:01 UTC
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

After updating our application from v18.2.8 to v19-next-10 we get the following errors messages in the console.

Unfortunately cannot create a reproduction right now, but maybe the messages tell you something...

Using sass .scss files if that is relevant.

### Please provide the exception or error you saw

Invalid component stylesheet ID request: ng-c4097974318
Invalid component stylesheet ID request: ng-c1132735445
Invalid component stylesheet ID request: ng-c1162657921
Invalid component stylesheet ID request: ng-c4097974318
Invalid component stylesheet ID request: ng-c1132735445
Invalid component stylesheet ID request: ng-c1162657921
Invalid component stylesheet ID request: ng-c4260659266
Invalid component stylesheet ID request: ng-c1820849548
Invalid component stylesheet ID request: ng-c1029942067
Invalid component stylesheet ID request: ng-c2542512266
Invalid component stylesheet ID request: ng-c4097974318
Invalid component stylesheet ID request: ng-c1132735445
Invalid component stylesheet ID request: ng-c1162657921

### Please provide the environment you discovered this bug in (run `ng version`)

Angular CLI: 19.0.0-next.11
Node: 20.18.0
Package Manager: npm 10.8.2
OS: darwin arm64

Angular: 19.0.0-next.10
... animations, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router
... service-worker

Package                              Version
--------------------------------------------------------------
@angular-devkit/architect            0.1900.0-next.11
@angular-devkit/core                 19.0.0-next.11 (cli-only)
@angular-devkit/schematics           19.0.0-next.11
@angular/build                       19.0.0-next.11
@angular/cdk                         19.0.0-next.8
@angular/cli                         19.0.0-next.11
@angular/google-maps                 19.0.0-next.8
@angular/material                    19.0.0-next.8
@angular/material-date-fns-adapter   19.0.0-next.8
@angular/ssr                         19.0.0-next.11
@schematics/angular                  19.0.0-next.11
rxjs                                 7.8.1
typescript                           5.6.3
zone.js                              0.15.0

**Comment by JeanMeche** [comment] 2024-10-18 13:02
Duplicate of angular/angular-cli#28656

**Closed by JeanMeche** 2024-10-18 13:02 UTC
