### ISSUE TITLE
Async Validator Causes FormControl's Status to Stuck at PENDING

### ISSUE THREAD

**Issue by oividioscaeremos** [angular/angular#48582] opened 2022-12-23 08:20 UTC
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

This issue seems to have happened in 2016 as well. But the bug is still there. (check the other bug report #13200)

The problem occurs when I have an autocomplete and an input working to have user select an item from a list. I filter my list according to user's input inside the `input` element and then redirect results to the `autoComplete` element. So far so good but as soon as I need an `asyncValidator`, I cannot get it to work as expected. `formControl` status gets stuck at `PENDING` everytime even though `filter` and `asyncValidator` functions return values.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-7qamtz-wkhl7t?file=src/app/autocomplete-auto-active-first-option-example.html

### Please provide the exception or error you saw

```true
`FormControl` status gets stuck at `PENDING` and doesn't show the error that is returned from the `asyncValidator`.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.0.4
Node: 16.14.2
Package Manager: npm 7.17.0
OS: linux x64

Angular: 15.0.4
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1500.4
@angular-devkit/build-angular      15.0.4
@angular-devkit/core               15.0.4
@angular-devkit/schematics         15.0.4
@angular/cdk                       15.0.3
@angular/material                  15.0.3
@angular/material-moment-adapter   15.0.3
@schematics/angular                15.0.4
rxjs                               7.4.0
typescript                         4.8.4
```

**Comment by JeanMeche** [comment] 2022-12-23 08:33
isn't that a dupe of #41519 ?

**Comment by oividioscaeremos** [comment] 2022-12-23 08:48
It seems to be the same problem yes. Like I said, it's also a duplicate of #13200 which dates back to 2016. Shouldn't there be a native solution for this particular case? Workarounds such as `take(1)` doesn't _really_ work. It does leave `PENDING` state after doing that but not reproduce the error message as it only `takes` the first result of the pipe.

**Comment by JeanMeche** [comment] 2022-12-23 08:54
Yeah, `take(1)` won't help you here. It's a known bug, the only current solution you have is polling the `status`.

**Comment by oividioscaeremos** [comment] 2022-12-23 08:59
May I ask, what `polling the status` is?

**Comment by JeanMeche** [comment] 2022-12-23 09:16
something like 

```
    const ctrl = new FormControl();
    const statusChanges$ = merge(
      ctrl.statusChanges,
      timer(0, 500),
      map(() => ctrl.status),
      distinctUntilChanged()
    );
```

**Comment by Totati** [comment] 2022-12-23 14:56
`take(1)`, strict typing and changing the `filteredOptions` to read the `this.myControl.value` instead of the value from the `startWith` in the `map` solves the problem.
[I've made a working example and commented the details.](
https://stackblitz.com/edit/angular-7qamtz-y7dpqe)

**Comment by JeanMeche** [comment] 2022-12-23 16:34
Ok I see, this has nothing to do with #41519.  Good catch.

**Comment by jmroon** [comment] 2022-12-29 15:49
There's a Stackoverflow post that explains why this is happening.

https://stackoverflow.com/questions/70708799/control-with-async-validator-changes-its-state-to-pending-when-calling-updateval

There is a workaround, which I posted here:
https://github.com/angular/angular/issues/41519#issuecomment-1174076020

**Comment by jmroon** [comment] 2022-12-29 16:07
You're doing something very strange here: your async validator is using filteredOptions as its source of truth for validation. You should be using options.

filteredOptions is an empty list once you select an item, so your validator can't map it to anything.

Works fine if you just use options:
https://stackblitz.com/edit/angular-7qamtz-wvwx25?file=src%2Fapp%2Fautocomplete-auto-active-first-option-example.ts,src%2Fapp%2Fautocomplete-auto-active-first-option-example.html

**Comment by JeanMeche** [comment] 2024-03-30 03:07
Closing as not a bug as shown by Totati.

**Closed by JeanMeche** 2024-03-30 03:07 UTC
Labels: area: forms
