### ISSUE TITLE
Can't use decorator with @Component

### ISSUE THREAD

**Issue by toxik** [angular/angular#53156] opened 2023-11-24 21:45 UTC
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

Given

```ts
const RunMe = <T extends { new (...args: any[]): {} }>(ctr: T) => class Ran extends ctr {
  constructor(...args: any[]) {
      super(...args);
      debugger;
  }
}

@Component({ .. })
@RunMe
class SomeComponent { }
```

With the devtools open it should stop inside the Ran constructor. 
[Angular 16 works](https://stackblitz.com/edit/angular-jn9vnp?file=src%2Fmain.ts), Angular 17 doesn't

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-bapqxf?file=src%2Fmain.ts

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.0.3
Node: 18.18.0
Package Manager: npm 9.8.1
OS: darwin arm64

Angular: 17.0.4
... animations, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.3
@angular-devkit/build-angular   17.0.3
@angular-devkit/core            17.0.3
@angular-devkit/schematics      17.0.3
@angular/cli                    17.0.3
@schematics/angular             17.0.3
ng-packagr                      17.0.2
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.2
```

**Comment by JoostK** [comment] 2023-11-25 14:01
This is because of the change to the `es2022` target, which enables native support for `static` blocks. Angular's factory function refers to `SomeComponent ` from this static block, which is _not_ the decorated `SomeComponent` but the original class.

This is only the behavior under `experimentalDecorators: true`. ECMAScript decorators do refer to the decorated type from within a static block.

Note that using decorators on Angular classes is not supported.

Duplicate of #45477.

**Closed by JoostK** 2023-11-25 14:01 UTC
