### ISSUE TITLE
I'm not able to use built-in custom elements

### ISSUE THREAD

**Issue by guiseek** [angular/angular#42427] opened 2021-05-31 12:01 UTC
https://github.com/angular/angular/blob/62b5a6cb079e489d91982abe88d644d73feb73f3/packages/platform-browser/src/dom/dom_renderer.ts#L140

# Bug Report

### Affected Package
 The issue is caused by package *@angular/platform-browser*

### Is this a regression?

 No

### Description

Verifying the cause, I understand that this must probably be the implementation in DefaultDomRenderer2, which doesn't follow the implementation faithfully, simply discarding the second parameter of the `createElement` method.

https://github.com/angular/angular/blob/master/packages/platform-browser/src/dom/dom_renderer.ts#L140

I'm not sure about that, but I believe the solution would be something like this:

```ts
class DefaultDomRenderer2 implements Renderer2 {
  // ...
  create (name: string, namespaceOrOptions ?: string | ElementCreationOptions) {
    if (namespaceOrOptions && typeof namespaceOrOptions === 'string') {
      // In cases where Ivy (not ViewEngine) is giving us the current namespace, the look up by key
      // will result in undefined, so we just return the namespace here.
      return document.createElementNS(NAMESPACE_URIS[namespaceOrOptions] || namespaceOrOptions, name);
    }
    if (namespaceOrOptions && namespaceOrOptions.hasOwnProperty ('is')) {
      return document.createElement(name, namespaceOrOptions as ElementCreationOptions);
    }
    return document.createElement (name)
  }
}
```

## Minimal Reproduction

 https://stackblitz.com/...

<pre><code>

class ButtonElement extends HTMLButtonElement {
  connectedCallback() {
    console.log('hello');
  }
}

customElements.define('ng-button', ButtonElement, { extends: 'button' })

<button is="ng-button">Angular Button</button>

</code></pre>

Docs:
https://html.spec.whatwg.org/multipage/custom-elements.html#custom-elements-customized-builtin-example

## Exception or Error
<pre><code>

</code></pre>

## Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 12.0.0
Node: 12.18.2
Package Manager: npm 6.14.5
OS: darwin x64

Angular: 12.0.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.0
@angular-devkit/build-angular   12.0.0
@angular-devkit/core            12.0.2
@angular-devkit/schematics      12.0.2
@schematics/angular             12.0.2
rxjs                            6.6.7
typescript                      4.2.4
</code></pre>

**Anything else relevant?**

**Comment by robwormald** [comment] 2021-06-04 21:21
Disclaimer to start - this API (extending built-in elements) is contentious and is unlikely to ever be supported on Safari. 

Also, your Stackblitz link is broken so can't verify what you're doing. 

Supporting this properly will likely need to be done at the compiler level, vs in the renderer itself. IMHO the most idiomatic way to support this would emulating the HTML parser behavior:

```html
<button is="ng-button">Test</button>
```
The compiler should treat `is='ng-button'` as a special case - setting the attribute after the fact won't work, hence this issue (though it should be done to allow use as a selector) - and generate the correct element creation code:
```ts
const el = document.createElement('button', {is: 'ng-button'});
el.setAttribute('is', 'ng-button') //not required but is consistent
```
This doesn't require any knowledge of the custom elements that are registered with the browser, so it shouldn't break locality. 

Note: it would be invalid to use an attribute / property binding here, because the value is used when the element is initially created (and can't be changed dynamically), so something like the following should throw a compile-time error:
```html
<button [attr.is]="elementName"></button>
```

relevant code is here, https://github.com/angular/angular/blob/master/packages/core/src/render3/instructions/element.ts#L84-L90, but at first glance the order of operations might be an issue...

**Comment by guiseek** [comment] 2021-06-07 17:34
@robwormald

I thinking exactly as it says [here](https://youtu.be/ZMZMMuXRFcE?t=230), if safari doesn't realize that, maybe it will end up with IE6.

But for now, we have this polyfill [`@ungap/custom-elements`](https://github.com/ungap/custom-elements) that solves the compatibility issue I'm using and it's working fine.

about stackblitz, sorry I didn't find it necessary to send a stackblitz link, so I just wrote a simple example and forgot to remove the link from the problem model.

about how to use, this is what I suggested implementation, but it seems that I suggested in the wrong place, thanks for the guidance, I hope it facilitates the solution of the problem reported here.

I understand that it shouldn't be necessary to create adapter layers for all the custom elements that we want to use in an app built with Angular, after all, it's just an attribute that appears even in the HTML specs.

Think we can't work with custom and angular elements without turning off schema checks? even if written in a typed way? I would very much like to be able to use them and still have rigid models working perfectly as they are

**Comment by guiseek** [comment] 2021-06-07 17:37
porque o angular sugere que fazemos em outros casos

https://angular.io/guide/accessibility#augmenting-native-elements

**Comment by guiseek** [comment] 2021-06-07 17:37
because the angular suggests that we do in other cases

https://angular.io/guide/accessibility#augmenting-native-elements

**Comment by gkalpak** [comment] 2021-07-03 10:06
Closing as a duplicate of #34607.

**Closed by gkalpak** 2021-07-03 10:06 UTC
Labels: comp: core, comp: elements
