### ISSUE TITLE
`strictMetadataEmit: true` InjectionToken - Error encountered in metadata generated for exported symbol with InjectionToken

### ISSUE THREAD

**Issue by alan-agius4** [angular/angular#23629] opened 2018-05-01 06:57 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
If try to build a library, with `strictMetadataEmit: true` and you use an `InjectionToken` together with the `factory` option that calls a lambda an error will be emitted `Metadata collected contains an error that will be reported at runtime: Lambda not supported.`. 

Though, it's relatively, odd when it's being thrown, 

**Works**
```ts
export function MSTRATEGY_PROVIDER_FACTORY(): () => void {
    const x = 2; // doing so even if it is unused the error goes away
    return () => new Overlay().reposition();
}
```

**Works**
```ts
export function MSTRATEGY_PROVIDER_FACTORY(): () => void {
    const x = () => new Overlay().reposition();
    return x;
}
```

**Error**
```ts
export function MSTRATEGY_PROVIDER_FACTORY(): () => void {
    return () => new Overlay().reposition();
}
```

Also, what is the reason Lamda function are not supported in this case? From the documentation I always saw something like the below as implementation (https://github.com/angular/angular/blob/master/aio/content/guide/dependency-injection.md#injectiontoken);

```ts
new InjectionToken<void>('scroll-strategy', {
    providedIn: 'root',
    factory: () => new Overlay().reposition()
});
```

However with the above, throw a compiler error when having `strictMetadataEmit`.

## Expected behavior
No error or at least a consistant behaviour

## Minimal reproduction of the problem with instructions

Have the following 2 flags in tsconfig.

```
    "skipTemplateCodegen": true,
    "strictMetadataEmit": true
```

TS file
```ts
import { NgModule } from '@angular/core';
import { InjectionToken, inject } from "@angular/core";

export class Overlay {
    constructor() {}
    reposition() {}
}

export const SCROLL_STRATEGY = new InjectionToken<void>('scroll-strategy', {
    providedIn: 'root',
    factory: MSTRATEGY_PROVIDER_FACTORY
});

export function MSTRATEGY_PROVIDER_FACTORY(): () => void {
   // const x = 2; // enabling this will remove the error
    return () => new Overlay().reposition();
}

@NgModule({
    providers: [{
        provide: SCROLL_STRATEGY,
        useFactory: MSTRATEGY_PROVIDER_FACTORY,
    }]
})
export class LibModule { }

```

## What is the motivation / use case for changing the behavior?
While this can be suppressed by using the `@dynamic`. Using the compiler flag might have the effect that one will suppress other important error message.

<pre><code>
Angular version: 6.0.0-rc.6
</code></pre>

**Comment by JLHwung** [comment] 2018-11-22 07:55
Chuck has given us details in https://github.com/angular/angular/issues/19698#issuecomment-338340211. I think this issue can be closed as the compiler works as intended.

**Comment by JoostK** [comment] 2020-03-16 00:13
Closing as working as intended per https://github.com/angular/angular/issues/19698#issuecomment-338340211.

Note that this may still be an issue for libraries today, as libraries still bundle the metadata. For anyone experiencing this issue, please refer to the workarounds in the issue description.

**Closed by JoostK** 2020-03-16 00:13 UTC
Labels: comp: compiler, freq1: low, hotlist: components team, severity3: broken, type: bug/fix
