### ISSUE TITLE
bug(language-service): not getting intellisense for enum assignment

### ISSUE THREAD

**Issue by indraraj26** [angular/angular#43018] opened 2021-08-02 17:44 UTC
### Which @angular/* package(s) are the source of the bug?

language-service

### Is this a regression?

No

### Description

I am getting intellisense/auto-completion in typescript playground

Type fooType. in angular .ts and .html you will not get anything
Link: https://stackblitz.com/edit/angular-ivy-wcsaa2?file=src%2Fapp%2Fapp.component.ts

Type x. in typescript playground
Link: https://www.typescriptlang.org/play?#code/FAUwdgrgtgBAogMQPJJgb2DGBnCBjPEbbAGkxgDMBDASwBtgBfYYCiMPAFxoHsxKAHgAoAlOnJY8fbJxgCYAXnjIkAbgkwpYbDzogAdHR4BzIQP24CRbCKbAgA

### Please provide the environment you discovered this bug in

```true
"@angular/animations": "^12.1.0",
    "@angular/common": "^12.1.0",
    "@angular/compiler": "^12.1.0",
    "@angular/core": "^12.1.0",
    "@angular/forms": "^12.1.0",
    "@angular/platform-browser": "^12.1.0",
    "@angular/platform-browser-dynamic": "^12.1.0",
    "@angular/router": "^12.1.0",
    "rxjs": "6",
    "tslib": "^2.3.0",
    "zone.js": "^0.11.4"
```

**Comment by atscott** [comment] 2021-08-02 18:56
Closing as unable to reproduce (I _did_ get the completion result in the template). Note that stackblitz does not use the Angular Language Service. In addition, ensure that you have `strictTemplates` enabled and have not enabled the legacy view engine language service for your project.

**Closed by atscott** 2021-08-02 18:56 UTC

**Comment by indraraj26** [comment] 2021-08-02 19:37
Hi @atscott ,

Even this is on in my application 
```
"angularCompilerOptions": {
    "enableI18nLegacyMessageIdFormat": false,
    "strictInjectionParameters": true,
    "strictInputAccessModifiers": true,
    "strictTemplates": true,
  }
```

But still i am not getting intellisense in project 
![image](https://user-images.githubusercontent.com/23274631/127914231-36ed9278-f033-4ed8-a609-873914cd7922.png)
ts
```
 foo = {
    name: 'asdsad'
  };
```

Version:
```
ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 12.1.0
Node: 14.17.1
Package Manager: npm 6.14.13
OS: win32 x64

Angular: undefined
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1201.0 (cli-only)
@angular-devkit/core         12.1.0 (cli-only)
@angular-devkit/schematics   12.1.0 (cli-only)
@schematics/angular          12.1.0 (cli-only)


F:\infini\emandi-dms>cd frontend

F:\infini\emandi-dms\frontend>ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 12.1.1
Node: 14.17.1
Package Manager: npm 6.14.13
OS: win32 x64

Angular: 12.1.1
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1201.1
@angular-devkit/build-angular   12.1.1
@angular-devkit/core            12.1.1
@angular-devkit/schematics      12.1.1
@angular/cdk                    12.1.3
@angular/material               12.1.3
@schematics/angular             12.1.1
rxjs                            6.6.7
typescript                      4.3.5

```

**Comment by atscott** [comment] 2021-08-02 19:42
@indraraj26  Are you able to provide a github repo that has this issue?

**Comment by indraraj26** [comment] 2021-08-02 19:48
Thank you @atscott for the quick response. 

It's look like something is broken in my feature branch.  

I will let you know, let me compare the changes between feature branch and develop.

**Comment by indraraj26** [comment] 2021-08-03 14:13
#resolved 

I dont know but it is working fine today on that same branch.
