### ISSUE TITLE
router: Add the ability to redirect to another route programatically

### ISSUE THREAD

**Issue by alarive** [angular/angular#9817] opened 2016-07-05 11:18 UTC
**I'm submitting a ...**  (check one with "x")

```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Currently there is no equivalent to history.replaceState in the router API. The only way to redirect seems to be the redirectTo option in RouterConfig.

**Expected/desired behavior**
I'd like to be able to redirect the user dynamically in my application.

**Please tell us about your environment:**
- **Angular version:** 2.0.0-rc.3
- **Browser:** [all ] 
- **Language:** [all ]

**Comment by zoechi** [comment] 2016-07-05 11:24
Looks like a dup of #9579

**Comment by spicywhitefish** [comment] 2016-07-11 20:09
Do your dynamic redirect in a guard.

**Comment by markpritchett** [comment] 2016-07-28 13:07
A bit late to the party, but here's my input.  

I'm looking at this with **RC4** not **RC3** as you stated.

If you're just wanting to programatically redirect to another route, you can just use:

```
this.router.navigate(['/heroes', { id: heroId, foo: 'foo' }]);
```
Above taken from **app/heroes/hero-list.component.ts** file in [https://angular.io/resources/live-examples/router/ts/plnkr.html](plunker)

**Please note, the above approach uses the standard push state navigation, so the previous routes will exist in the browser's history.**

If you are wanting to use **history.replaceState**, then I agree with @zoechi, it looks to be a duplicate of #9579.

If you simply want to **guard** against a certain route being loaded, you could add a **canActivate** guard.  (as suggested by @spicywhitefish) Again, the above plunker has an example of this - see the  **app/auth-guard.service.ts** file for an example of a guard and **app/crisis-center/crisis-center.routes.ts** file for an example of how you would use it.

**Comment by DzmitryShylovich** [comment] 2016-12-18 12:11
#9579 was fixed. is this still an issue?

**Comment by DzmitryShylovich** [comment] 2017-01-15 08:20
@vicb can be closed

**Comment by DzmitryShylovich** [comment] 2017-02-03 19:36
@pkozlowski-opensource can be closed

**Closed** 2017-02-03 23:05 UTC
Labels: comp: router, freq2: medium, type: feature
