### ISSUE TITLE
Broken hydration after v17 -> v18 migration if i18n blocks are used

### ISSUE THREAD

**Issue by zip-fa** [angular/angular#56989] opened 2024-07-15 14:35 UTC
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

This is a duplicate of #56074
Re-opened because issue still persists. Repro was updated to 18.1.0

Steps to reproduce, **NO CODE MODIFICATIONS NEEDED**, just clone my repro:

1) ng serve
2) open adaptive screen mode. Set dimensions to be less than 768px, eg:

<img width="488" alt="image" src="https://github.com/user-attachments/assets/46f5008a-58b0-419c-833b-69695f09fbdc">

3) refresh page in adaptive screen mode
4) mobile&desktop content are displayed; html inside @if + @else **is rendered simultaneously**

### Please provide a link to a minimal reproduction of the bug

https://github.com/zip-fa/ng18-broken-hydration

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 18.1.0
Node: 22.4.1
Package Manager: npm 10.8.1
OS: darwin arm64

Angular: 18.1.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, localize, platform-browser, platform-browser-dynamic
... platform-server, router, ssr

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1801.0
@angular-devkit/build-angular   18.1.0
@angular-devkit/core            18.1.0
@angular-devkit/schematics      18.1.0
@schematics/angular             18.1.0
rxjs                            7.8.1
typescript                      5.4.5
zone.js                         0.14.7
```

### Anything else?

The issue still happens because of this line of code inside component:

```js
  private readonly vcr = inject(ViewContainerRef);
```

If i remove it - everything works as expected

**Comment by zip-fa** [comment] 2024-08-06 08:27
Is there a chance this would be fixed in 18.2? Sorry for being annoying

**Comment by AndrewKushnir** [comment] 2024-08-08 01:44
@zip-fa I was able to reproduce this problem and it looks like it's reproducible even without i18n blocks. Could you please check if that's the case in your application (i.e. remove i18n attributes from the template and try to reproduce the issue)?

**Comment by AndrewKushnir** [comment] 2024-08-08 05:02
@zip-fa I've created PR https://github.com/angular/angular/pull/57300 with the fix for this issue. The PR will go through the review and testing process and will be merged once the required procedures are completed.

**Comment by zip-fa** [comment] 2024-08-08 06:49
> @zip-fa I was able to reproduce this problem and it looks like it's reproducible even without i18n blocks. Could you please check if that's the case in your application (i.e. remove i18n attributes from the template and try to reproduce the issue)?

Yes, you were right

**Closed** 2024-08-09 15:07 UTC
Labels: area: core, P3, bug, core: hydration
