### ISSUE TITLE
CanActivate order

### ISSUE THREAD

**Issue by scarlz** [angular/angular#6815] opened 2016-02-01 12:02 UTC
CanActivate hooks are currently executed in order of child -> parent. This causes problems when the child route's CanActivate depends on data that is set by the parent's CanActivate. An example might be the checking of current user permissions in the child CanActivate when the current user will not be bootstrapped until the parent's CanActivate is called.

Is this by design? It would seem more logical to have this perform the way OnActivate does (from parent -> child).

**Comment by zoechi** [comment] 2016-02-01 12:12
Might be related to #4112 If you can inject a service to `canActivate` then you could get the relevant information everywhere. Would this help?

**Comment by scarlz** [comment] 2016-02-01 16:55
Well, I am already using the workaround to inject dependencies into CanActivate, and am using a shared service to persist data, but this isn't really the problem. Consider the two routes:

```javascript
// Parent Route
@CanActivate(() => {
  ...
  // check for current user and activate if exists
  return userService.bootstrapUser().then(user => !!user);
})

// Child Route
@CanActivate(() => {
  ...
  // check current user has permission
  return userService.userHasPermission('permission');	
})
```

The child CanActivate will always return false because the user is not bootstrapped at this point, due to the order in which CanActivate executes from child -> parent. This seems counter-intuitive given the child route belongs to a route that requires a user exist to be activated.

**Comment by nicolashenry** [comment] 2016-03-29 23:40
I just found out that my issue https://github.com/angular/angular/issues/7342 is a duplicate of this issue.

**Comment by DzmitryShylovich** [comment] 2016-08-16 11:22
@vicb I think this can be closed

**Closed** 2016-09-26 20:28 UTC
