### ISSUE TITLE
Unclear error message for hostbinding

### ISSUE THREAD

**Issue by kingecg** [angular/angular#39328] opened 2020-10-19 10:51 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

when create a directive or component, if you use arguments in hostlistener binding and declared wrong 
number arguments in function like following code. 
```typescript
class XX {
@HostListener('click', ['$event.target'])
  onclick(){}
}
```
compiler report error:'Directive XX, Expected 0 arguments, but got 1' at the place which use the directive.
expect report error at directive code
## 🔬 Minimal Reproduction

 https://stackblitz.com/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by JoostK** [comment] 2020-10-19 10:55
Closing as duplicate of #21329

**Closed by JoostK** 2020-10-19 10:55 UTC
