### ISSUE TITLE
No provider for ControlContainer found in NodeInjector

### ISSUE THREAD

**Issue by anjunar** [angular/angular#49354] opened 2023-03-07 14:48 UTC
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

No

### Description

When splitting up forms into components ControlContainer is not found.

```true
<form #form="ngForm" (ngSubmit)="onSubmit(form)">
  <ng-container #container></ng-container>
  <button type="submit">Submit</button>
</form>
```

```
export class MetaFormComponent implements AfterViewInit {

  @ViewChild("container", {read : ViewContainerRef}) container! : ViewContainerRef
  @ViewChild(NgForm) form! : NgForm

  @ContentChild(TemplateRef) template! : TemplateRef<any>

  constructor(private injector : Injector) {}

  ngAfterViewInit(): void {

    let injector = Injector.create({
      providers: [
        {
          provide: ControlContainer,
          useFactory: () => {
            return this.form;
          }
        }
      ],
      parent: this.injector
    });

    this.container.createEmbeddedView(this.template, {}, {injector : injector})

  }

  onSubmit(form : NgForm) {
    console.log(form.value)
  }

}
```

```
<app-meta-form>
  <ng-template>
    <fieldset ngModelGroup="name">
      <input type="text" ngModel name="first">
    </fieldset>
  </ng-template>
</app-meta-form>
```

### Please provide the exception or error you saw
ERROR Error: NG0201: No provider for ControlContainer found in NodeInjector
```


### Please provide the environment you discovered this bug in (run `ng version`)

Angular CLI: 15.2.1
Node: 19.6.0 (Unsupported)
Package Manager: npm 9.4.0
OS: win32 x64

Angular: 15.2.1
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1502.1
@angular-devkit/build-angular   15.2.1
@angular-devkit/core            15.2.1
@angular-devkit/schematics      15.2.1
@schematics/angular             15.2.1
rxjs                            7.8.0
typescript                      4.9.5
```

**Comment by JoostK** [comment] 2023-03-07 15:44
This is currently working as designed, and a duplicate of #47580.

**Closed by JoostK** 2023-03-07 15:44 UTC
