### ISSUE TITLE
Beta 17 doesnt working on Safari

### ISSUE THREAD

**Issue by tamasfoldi** [angular/angular#8585] opened 2016-05-11 09:04 UTC
Hi!

I have a problem. I'm on beta 17 and my code works properly in chrome and firefox but in Safari my components don't appear. I get the data from firebase and put it in a component. Actually it is a chat, I get the messages from firebase. Getting the data is fast, but the messages dont appear until I manually put the focus in the input field. I have tried manual change detection but didn't work neither.

Any ideas what can be the problem and how can I solve this?

Best Regards

**Comment by eisenmaxx** [comment] 2016-05-11 10:32
```
setTimeout(_=>{
                    this.messages = this._messageService.messages;
                    this._zone.run(()=>{console.log("RENDER")});
},1000);

```

Copy paste ready code.

**Comment by ericmartinezr** [comment] 2016-05-11 12:55
>Any ideas what can be the problem and how can I solve this?

Without a reproduction it is impossible. Consider also that beta.17 is no more, latest release is RC.1 so you should reproduce your issue using that version. Don't forget to add the polyfills.

**Comment by gonzofish** [comment] 2016-05-11 12:58
i'm willing to bet it was the same change detection issues a lot of people were commenting about (myself included) on betas 16 & 17. In RC 1, it seems to be fixed. I suggest upgrading!

**Comment by jaichopra** [comment] 2016-05-12 12:58
We have a few strange change detection issues in Beta 17 on Safari only:
EXCEPTION: ReferenceError: Can't find variable: Intl in [null]

Which is thrown from:
angular2/src/core/change_detection/dynamic_change_detector

**Comment by ericmartinezr** [comment] 2016-05-12 13:20
@jaichopra see this https://github.com/angular/angular/issues/3333

**Comment by eisenmaxx** [comment] 2016-05-12 14:37
It seems like after we updated the problem still exists, so here are some details:
- es6 shim loaded
- angular2 polyfill loaded

We receive the data immediately after the site loads and the user auth was successfully via JWT.
Chrome renders the components instantly, meanwhile safari and firefox stucks and the render phase wont happen, (its the main component)

so after a few sec (30-40) its show up and work fine, if we remove the polyfill then its the same, if i change the polyfill to an older one its works fine but gets a Maximum call stack size exceeded error, which is somewhere in zone and the stack trace simply shows one line about 9000 times.

Note, we had a similar problem with a child component, that issue could be solved with:
this._zone.run(()=>{}); 

So someone any idea?

**Comment by mhevery** [comment] 2016-05-13 05:23
Thank you for submitting the issue. All issues require a [plunker](https://plnkr.co/) which demonstrates the problem and how to reproduce it. Please re-open the issue or create a new issue once you have a reproducible use case.

We are sorry that we are so aggressive on closing the issues. We are overwhelmed with the number of issues we get, and so we only have time to look at the ones which are easy for us to reproduce.

**Closed by mhevery** 2016-05-13 05:23 UTC
