### ISSUE TITLE
AOT metadata is published at root folder instead of dist folder. [5.0.0-rc0]

### ISSUE THREAD

**Issue by Matju-M** [angular/angular#19543] opened 2017-10-04 06:23 UTC
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
When compiling application with AOT, the metadata files are published at root folder, instead of dist folder. This used to work in v4.4.3

## Expected behavior
the metadata files should be published in dist folder.

## Environment

<pre><code>
Angular version: 5.0.0-rc0

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.6.0
- Platform:  Windows

</code></pre>

**Comment by theodorejb** [comment] 2017-10-06 04:06
I have the same issue in Angular 5.0.0-rc.1. ngc is creating folders for common, forms, platform-browser, and router in the root of my project, containing corresponding .ngsummary.json files.

**Comment by ocombe** [comment] 2017-10-06 15:38
Can you give us the content of your tsconfig file please?

**Comment by theodorejb** [comment] 2017-10-06 15:54
```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "es2015",
    "outDir": "compiled_ts",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": ["es2015", "dom"],
    "noImplicitAny": true
  },
  "files": [
    "app/app.module.ts",
    "app/main.ts"
  ],
  "angularCompilerOptions": {
    "skipMetadataEmit" : true
  }
}
```

**Comment by tbosch** [comment] 2017-10-06 16:32
@theodorejb I just tried this with rc.1, and all files go into `compiled_ts` folder. Which TypeScript version are you using? It should be 2.4.x...

**Comment by tbosch** [comment] 2017-10-06 16:32
Could you create a branch on Github where I can reproduce the problem?

**Comment by tbosch** [comment] 2017-10-06 16:34
@Matju-M I just tried to also emit `.metadata.json` files, and that worked as well (I took the above `tsconfig.json` and removed the entry for `skipMetadataEmit`). Could you also create a branch to reproduce this?

**Comment by tbosch** [comment] 2017-10-06 16:38
Oh, this is on windows...

**Comment by tbosch** [comment] 2017-10-06 16:50
Also can't reproduce on windows.

**Comment by theodorejb** [comment] 2017-10-06 17:04
Check out the master branch of https://github.com/theodorejb/phasem.git and run `npm install`. The ngc postinstall script produces folders in the project root for common, forms, platform-browser, and router, containing ngsummary.json files.

**Comment by Matju-M** [comment] 2017-10-06 17:27
@tbosch Here's a skeleton project to highlight my issue.
https://github.com/Matju-M/mang-ngx-ui-skeleton.git

**Comment by alexzuza** [comment] 2017-10-06 19:42
My tsconfig.json

```
{
  "compilerOptions": {
    "target": "es5",
    "outDir": "aot",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": ["es2015", "dom"],
    "noImplicitAny": true,
    "suppressImplicitAnyIndexErrors": true
  },

  "include": ["app/**/*.ts"],

  "angularCompilerOptions": {
    "skipMetadataEmit" : true
  }
}
```
Project is located in `D:\Web\ng5`

Ngc produces folders in the project root `D:\Web\ng5` for common, forms, platform-browser, and router, containing ngsummary.json files and also typescript and rxjs folders in `D:\Web` path

Here is reproduction

![2](https://user-images.githubusercontent.com/4223314/31295511-d87ea430-aaef-11e7-9935-be8f6be09c8f.gif)

**Comment by tbosch** [comment] 2017-10-06 21:52
Thanks. What node and typescript version are you using?

**Comment by tbosch** [comment] 2017-10-06 22:42
Thanks, I was finally able to reproduce. @alexzuza thanks for the video, that really helped!

**Comment by theodorejb** [comment] 2017-10-24 18:00
This had been fixed in 5.0.0-rc.3, but now I tried 5.0.0-rc.5 and the problem is happening again.

**Comment by tbosch** [comment] 2017-10-24 18:33
@theodorejb do you have a reproduction?

**Comment by theodorejb** [comment] 2017-10-24 19:33
@tbosch You can reproduce it with this repository: https://github.com/theodorejb/phasem.git.

Checkout the angular-5 branch, and run `npm install`. The postinstall script runs the Angular compiler, which incorrect creates the following folders/files in the root of the repository:

* common/common.ngsummary.json
* common/http/http.ngsummary.json
* forms/forms.ngsummary.json
* platform-browser/platform-browser.ngsummary.json
* router/router.ngsummary.json

Note that I'm using Node v8.7.0 on Windows 10.

**Comment by tbosch** [comment] 2017-10-24 22:02
@theodorejb thanks! https://github.com/angular/angular/pull/19915 should fix it again...

**Comment by tbosch** [comment] 2017-10-25 15:18
https://github.com/angular/angular/pull/19915 has landed on master.

**Closed by tbosch** 2017-10-25 15:18 UTC
Labels: comp: core & compiler, severity5: regression, type: bug

**Comment by actra-gschuster** [comment] 2017-10-26 13:32
Files are output in the correct folder structure, thanks so far.

But compiler in RC.6 is still breaking my app that builds fine with RC.3, error is the generic "Can't resolve app.module.ngfactory".
I didn't open a new issue on this as I'm too busy to investigate further and provide a reproduction.
BTW, working setup is currently all modules at RC.6 except for compiler-cli.
