### ISSUE TITLE
CSS styles not applied if using multiple attribute selectors to style an element with the direct child selector

### ISSUE THREAD

**Issue by Marcarrian** [angular/angular#49157] opened 2023-02-22 10:58 UTC
### Which @angular/* package(s) are the source of the bug?

compiler

### Is this a regression?

Yes

### Description

If using multiple attribute selectors to style an element with the direct child selector, the styles are not applied.
**This happens only in a development build.**

Reproduction:
**app.component.html**
```html
<div class="example-1">
  Example 1
</div>
<div class="example-2">
  Example 2
</div>
```
**app.component.scss**
```scss
:host {
  &:is([data-foo="bar"]) {
    > div.example-1 {
      background-color: lightskyblue; // working in dev and prod build
    }
  }

  &:is([data-foo="bar"], [data-foo-2="bar-2"]) {
    > div.example-2 {
      background-color: violet; // ONLY working in prod build
    }
  }
}
```

### Please provide a link to a minimal reproduction of the bug

https://github.com/Marcarrian/angular-15-css-multiple-attribute-selectors-issue

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.1.6
Node: 16.16.0
Package Manager: npm 8.11.0
OS: win32 x64

Angular: 15.1.5
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1501.6
@angular-devkit/build-angular   15.1.6
@angular-devkit/core            15.1.6
@angular-devkit/schematics      15.1.6
@angular/cli                    15.1.6
@schematics/angular             15.1.6
rxjs                            7.8.0
typescript                      4.9.5
```

**Comment by JeanMeche** [comment] 2023-02-22 23:35
Basically, the support for multiple arguments for CSS pseudo class functions was broken. 

I've opened the PR that fixes this.

**Comment by JeanMeche** [comment] 2024-09-03 13:07
I'll close this as a duplicate of #45686.

**Closed by JeanMeche** 2024-09-03 13:07 UTC
Labels: area: core, state: has PR, P3
