### ISSUE TITLE
Canceled Location.forward() breaks history

### ISSUE THREAD

**Issue by DzmitryShylovich** [angular/angular#15664] opened 2017-03-31 12:36 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
```

**Current behavior**
When `CanDeactivate` cancels `Location.forward()` routing history is 1 item ahead.
Workflow
```
Home -- navigate to     --> Child 1
Child 1 -- navigate to     --> Child 2
Child 2 -- navigate to     --> Child 3 (CanDeactivate returned true)
Child 3 -- location.back() --> Child 2
Child 2 --  location.forward() --> Child 2 (navigation canceled CanDeactivate returned false)
Child 2 -- location.back() --> Child 2 (should be Route 1)
```

**Expected behavior**
```
Home -- navigate to     --> Child 1
Child 1 -- navigate to     --> Child 2
Child 2 -- navigate to     --> Child 3 (CanDeactivate returned true)
Child 3 -- location.back() --> Child 2
Child 2 --  location.forward() --> Child 2 (navigation canceled CanDeactivate returned false)
Child 2 -- location.back() --> Child 1 (expected)
```

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/PbKRj7v1B1tRVXRSrEup?p=preview

1. Click button Child1
2. Click button Child2
3. Click button Child3
4. Click button Back
5. Click button Forward
6. Click button Back

Expected behavior is to see `Child1` but it's still `Child2`

**Comment by patrickracicot** [comment] 2017-10-25 16:53
Any progress on this issue? The PR #18135 for the referenced issue #18135 is still pending and the frequency seems to be bigger then initialy estimated.

**Comment by UlricW** [comment] 2018-01-12 14:37
Any news on it ? 
That cause big side effect on our application. 
Thanks

**Comment by atscott** [comment] 2020-05-26 22:25
Confirmed and marking as duplicate of #13586. Example in https://github.com/angular/angular/issues/13586#issuecomment-634226667 extended to include this use-case.

**Closed by atscott** 2020-05-26 22:25 UTC
Labels: comp: router, freq3: high, router: guards/resolvers, severity3: broken, state: confirmed, triage #1, type: bug/fix
