### ISSUE TITLE
ngFor doesn't support Object but ng-repeat does.

### ISSUE THREAD

**Issue by laco0416** [angular/angular#6663] opened 2016-01-24 01:31 UTC
In AngularJS, `ng-repeat` can iterate `Object` as key-value map.

https://docs.angularjs.org/api/ng/directive/ngRepeat

`<div ng-repeat="(key, value) in myObj"> ... </div>`

In Angular2, `ngFor` doesn't support it. `ngFor` can iterate only an array.

https://angular.io/docs/ts/latest/api/common/NgFor-directive.html

`<li *ngFor="#item of items; #i = index">...</li>`

This mismatch makes migrations a little difficult.

I think `ngFor` also support `Object` iteration as well as `ng-repeat`.

**Comment by laco0416** [comment] 2016-01-24 01:32
Expect: 

```html
<li *ngFor="#value of myObj; #key = key">...</li>
```

**Comment by zoechi** [comment] 2016-01-24 10:08
dup of #2246?

**Comment by PascalPrecht** [comment] 2016-01-24 11:08
@laco0416 this is intentional and by design for the reasons mentioned in the issue @zoechi pointed out.

**Comment by laco0416** [comment] 2016-01-24 13:21
@zoechi @PascalPrecht thank you for the information.
If so it is the design, a solution for it must be also in the design, i think.
I wrote a pipe, `objectToIterable`,  for this. Something like this should be provided by the library.

**Comment by pkozlowski-opensource** [comment] 2016-01-24 14:14
Duplicate of #2246

**Closed by pkozlowski-opensource** 2016-01-24 14:14 UTC
