### ISSUE TITLE
Emulated style encapsulation inheritance does not match native or shadow DOM

### ISSUE THREAD

**Issue by jonrimmer** [angular/angular#29575] opened 2019-03-28 21:20 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/core

### Is this a regression?

Unsure

### Description

When a component with `ViewEncapsulation.None` is placed inside a component with `ViewEncapsulation.Emulated`, styles defined in the parent do not affect it. When the parent's encapsulation is changed to `ViewEncapsulation.Native` or `ViewEncapsulation.ShadowDom`, they do.

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-hayw7e?file=src%2Fapp%2Fapp.component.ts

Note that the text "Hello there" is not affected by the color rule defined in the App component. However, if the encapsulation is changed from "emulated" to "native" or "shadowDom" the rule is applied.

I know "emulated" is not supposed to be 100% compatible with v0 or v1 shadow DOM, but this is a pretty huge deviation.

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 7.3.6
Node: 8.11.4
OS: darwin x64
Angular: 7.2.10
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.6
@angular-devkit/build-angular     0.13.6
@angular-devkit/build-optimizer   0.13.6
@angular-devkit/build-webpack     0.13.6
@angular-devkit/core              7.3.6
@angular-devkit/schematics        7.3.6
@angular/cli                      7.3.6
@ngtools/webpack                  7.3.6
@schematics/angular               7.3.6
@schematics/update                0.13.6
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.29.0
</code></pre>

**Comment by petebacondarwin** [comment] 2021-01-23 20:05
So this is what the HTML (and styling) looks like:

```html
<head>
  <style>p[_ngcontent-c0] { color: red; }</style>
</head>
<body>
  <my-app _nghost-c0="" ng-version="7.2.11">
    <hello _ngcontent-c0=""><p>Hello there</p></hello>
  </my-app>
</body>
```

You can see that a `p` element in the `AppComponent` is styled as `red` because all elements within the `AppComponent` template get the `_ngcontent-c0` attribute attached.
But the `p` element in the `HelloComponent`, does not receive this red style because (being `Encapsulation.None`) it has no special attributes attached to it.

In order for this style to hit the `p` in HelloComponent, it would need to be defined as `p[_ngcontent-c0], [_ngcontent-c0] p { color: red; }` so that all `p`s within elements that are defined in the template would receive the styling. The trouble with doing this is that components with `Encapsulation.Emulated` that appear within this component would also receive this styling since it is not possible to block the style from bleeding into their templates.

**Comment by petebacondarwin** [comment] 2021-01-23 20:11
I think that achieving this level of styling control with mixed mode encapsulation is beyond what is feasible.

**Comment by petebacondarwin** [comment] 2021-01-23 20:46
Actually I believe this is a duplicate of #15312.

**Closed by petebacondarwin** 2021-01-23 20:46 UTC
Labels: P4, comp: core, core: CSS encapsulation, freq1: low, type: bug/fix
