### ISSUE TITLE
EXCEPTION: Only 3 queries can be concurrently active in a template.

### ISSUE THREAD

**Issue by cristinecula** [angular/angular#3638] opened 2015-08-14 11:02 UTC
I have a component that uses NgFor to create other components inside it's view, by iterating over a list.

```html
<ul>
  <li *ng-for="#item of playlist"><item [name]="item.name"></item></li>
</ul>
```

I use ViewQuery to get a hold of the child components. 

All is well until i change the `playlist` getter to return a map of the original array:

```js
  get playlist() {
    return this.content.map((i) => { return {name: i.name + 'y'} })
  }
```

It seems that NgFor repeatedly destroys and creates the <item> components, on each change, but the ViewQuery keeps accumulating components. After a few ticks, ViewQuery stops working entirely and throws.

Here is a plunker showcasing the bug:
http://plnkr.co/edit/uGKcpQUJoWWo4SPNp3z8

**Comment by pkozlowski-opensource** [comment] 2015-08-14 11:11
I believe that this is duplicate of https://github.com/angular/angular/issues/3625

**Comment by cristinecula** [comment] 2015-08-14 11:30
@pkozlowski-opensource that would indeed solve the issue with the 3 queries limit, I think there is something else here. As you can see, the ViewQuery keeps records of all of the child components, even if they were destroyed:

![](https://i.imgur.com/s2HyXbO.png)

**Comment by pkozlowski-opensource** [comment] 2015-08-14 11:31
OK, going to reopen so @rkirov can confirm if this is a duplicate or not

**Comment by rkirov** [comment] 2015-08-14 18:14
So not really a duplicated of #3625 since there is only one active query (not >3).

However there was a bug that was fixed with https://github.com/angular/angular/commit/2150a8f9d1373770a6a27258de1c1ffecb90fd21

I will add an unit test that cycles an ng-for 5+ times and close this issue.

**Closed** 2015-08-14 22:19 UTC
