### ISSUE TITLE
ResizeObserver (and MutationObserver) not patched by zone.js

### ISSUE THREAD

**Issue by Goodwine** [angular/angular#31695] opened 2018-09-28 22:53 UTC
## Current behavior
Example with delay (my use case) -
https://stackblitz.com/edit/angular-f8evbx?file=src/app/app.component.spec.ts
Simplified example -
https://stackblitz.com/edit/angular-f8evbx-3ak8vv?file=src/app/app.component.spec.ts
MutationObserver example -
https://stackblitz.com/edit/angular-f8evbx-6wdpmj?file=src/app/app.component.ts

1. Use ResizeObserver (or MutationObserver + window.onresize to polyfill) on an element
2. (not relevant) Handle event into an observable with debouce or some other delay thingy
3. Write test for it using fakeAsync

Tests using fakeAsync fail, I'm forced to use `setTimeout(expectations+done, delay)` which causes unexpected delays. I tried using `import 'zone.js/dist/zone-patch-resize-observer';` but it didn't work.

On top of that, the timeout is flaky unless a full extra second or so is added to the delay.

## Expected behavior

`flush()` should trigger events from `ResizeObserver` and `MutationObserver`

## Other things
"zone.js": "^0.8.26"
"@angular/core": "^6.1.0",
"rxjs": "^6.2.0",

Relevant: https://github.com/angular/zone.js/pull/1012

**Comment by J5** [comment] 2019-11-26 17:55
Is there any update to this? I currently test using promises, spys and screenshot tests but as others use my components I would like them to be able to test like any other angular component.

**Comment by jdussouillez** [comment] 2020-08-31 12:47
Any updates about this ?

Thanks.

**Comment by DerekRTP** [comment] 2020-11-02 22:09
Is this still an issue?

**Comment by inthegarage** [comment] 2020-11-04 12:47
@DerekRTP Yes still an issue.

**Comment by inthegarage** [comment] 2020-11-04 13:01
So as a workaround(?) you can do the following:
In my example MutationObserver was checking for one class, and if present adding a text comment.
This was not being set in the test and so the following could be done.
```

  it('should create and change text', () => {
    component.formGroup.markAllAsTouched();
    fixture.detectChanges();
    fixture.whenStable().then(() => {
      setTimeout(() => {
        const text = fixture.nativeElement.querySelector('.my-item').innerText;
        expect(text).toContain('My Text');
      }, 1);
    });
  });

  afterEach(fakeAsync( () => {
    flush();
  }));
```

Things may get tricky if there is more than one thing needing to test the operation. You can always split these tests up, maybe into multiple files should you need it. However if you want one test, this will work.

**Comment by JiaLiPassion** [comment] 2020-11-04 13:03
I will try to work on it .

**Comment by ntvsx193** [comment] 2021-02-03 13:52
Any progress?

**Comment by bene-starzengruber** [comment] 2022-02-16 13:14
Hey @JiaLiPassion - can you tell us the reason why https://github.com/angular/angular/pull/40905 was never merged. 
Is the feature too complex to be implemented, are there some other stepping stones or is it just a matter of priorization?

**Comment by Draccoz** [comment] 2022-04-20 22:07
I've just hit a wall with this one... Over 3 years and it's still not fixed? Seriously, what's the issue?

**Comment by why520crazy** [comment] 2022-04-28 11:25
any news?

**Comment by giniedp** [comment] 2022-06-18 07:46
@JiaLiPassion please give us an update on this. Will this be fixed? Or do we have to wait until Angulars ngZone opt out feature?

**Comment by JiaLiPassion** [comment] 2022-06-22 00:46
Sorry for the late reply, the `fakeAsync` support for the `MutationObserver` and `ResizeObserver` will not be provided officially, the PR is here https://github.com/angular/angular/pull/40905, and it will not be merged in the near future, so I am considering some other ways to make it work.

**Comment by pmoleri** [comment] 2022-06-22 13:03
@JiaLiPassion the issue is broader than just `fakeAsync` right? ResizeObserver is not being patched by Angular zone at all.
Shouldn't this be considered a bug more than a `feature request`? Otherwise developers will keep hitting this issue. Probably many of them end up with a workaround without even realizing what was the root cause.

**Comment by dylhunn** [comment] 2022-09-29 23:40
`ResizeObserver` is an [available polyfill](https://github.com/angular/angular/blob/main/packages/zone.js/NON-STANDARD-APIS.md#usage-3). `MutationObserver` is already automatically patched.

**Closed by dylhunn** 2022-09-29 23:40 UTC
Labels: feature, comp: zones, insufficient votes, votes required

**Comment by MikeMatusz** [comment] 2022-10-05 18:56
@dylhunn  Is there any separate issue for tracking `fakeAsync`/`async` support for `MutationObserver` (and possibly `ResizeObserver`) then?  The title only mentions that they should be patched, but the expected behavior of this issue was specifically around being able to test them.  Having to resort to `setTimeout()` in unit tests with arbitrary delays is far from ideal, especially if having the wrong delay can cause intermittent failures.  What was the holdup on #40905?
