### ISSUE TITLE
angular service worker not updating the version correctly on chrome  67 official build. 

### ISSUE THREAD

**Issue by mateenQureshi** [angular/angular#23296] opened 2018-04-10 20:19 UTC
[ ] It only do not update correctly, when client is login with gmail account, and do update.

## Current behavior
On release of new version of the app, update version pop is being displayed to the user, once they willingly press update, the version of app is not loading correctly. It throws some type error, saying cannot read id of undefined. It only happens, when client's browser is in user mode, not in guest mode. 
Guest mode goes fine, but it does not fulfill the purpose of using service worker. In guest mode, every time app is being loaded as its first access. Furthermore, when the app goes expire in browser, it only loads the service-worker.js, nothing else.

## Expected behavior
On release of new version of the app, update version pop is being displayed to the user, once they willingly press update, service worker should update the version correctly. 

## Minimal reproduction of the problem with instructions
https://staging.rxconcileapp.com
Install it in your latest chrome browser, with user mode. I deploy changes everyday on staging site. Reload after few days, you will see update popup in a minute or two. press update and check if you  guys could see the updated FE assets.

## Environment
Production

Angular version: Angular (all packages router, core, service worker, compiler-cli, forms, etc): 5.2.9

Browser:
- [ ] Chrome (desktop) Version 67.0.3386.1 (Official Build) dev (64-bit)

 
For Tooling issues:
-Typescript: 2.5.2,
-Angular-Cli: 1.7.4,
- Node version:8.9,4
- Platform:   CentOS, Windows

Let me know, if you guys need more info for debugging purpose.
Consider it an hotfix for me, App is in production, right now.

**Comment by gkalpak** [comment] 2018-04-13 08:33
I'm sorry but I can't reproduce the problem following the instructions you provided. For starters, I can't login or "install" the app as you suggested.

Also, if it only fails on Chrome 67 (which is currently a dev build - alas not stable), it might be a Chrome issue. Maybe posting a non-monified stack trace of the error would give some hints on what might be the problem.

Anyway, I am going to close this, since it is not actionable in its current state, but feel free to continue the discussion below.

**Closed by gkalpak** 2018-04-13 08:33 UTC
Labels: comp: service-worker

**Comment by mateenQureshi** [comment] 2018-04-16 07:43
Hey @gkalpak ,
Thank you very much for directions. You might be right, this can be  chrome 67 bug as it is in not yet stable. All i want to request is, if client is not found for service worker, as in my case, it should properly handle the rejection rather then throwing some type error saying: cannot read id of undefined, because in future, node will exit the process with status code 0 if there is any unhandled promise rejection. (Hope you have a better idea of this).
OR
if there is any way to handle rejection in my code, or service worker configuration, please let me know.

**Comment by gkalpak** [comment] 2018-04-16 08:53
> it should properly handle the rejection rather then throwing some type error saying: cannot read id of undefined

There is no indication that this error is caused by the SW rather than your code. 
Unfortunately, there is no way to tell, without a reproduction.

> because in future, node will exit the process with status code 0 if there is any unhandled promise rejection

This is irrelevant, since the SW will run in the browser, not in node.

**Comment by mateenQureshi** [comment] 2018-04-16 14:41
Thanks @gkalpak for quick response . 
Got the better understanding of service worker and some confirmations as well.

Great Day!

**Comment by mateenQureshi** [comment] 2018-04-18 09:59
Hello @gkalpak , 

Can you please check this screenshot and give your feedback: 

![ngsw-bug](https://user-images.githubusercontent.com/12191080/38925430-05302c1c-4319-11e8-9670-233d627a2dbf.png)

**Comment by gkalpak** [comment] 2018-04-20 05:42
The code in `worker-basic.js` looks something like this:

```
const clientId = event.clientId;  // `event` is a `FetchEvent`.
const client = this.scope.clients.get(clientId);
// We then try to access `client.id`, which causes the error.
```

The weird thing is that `FetchEvent#clientId`, is (according to MDN) a _"read-only property of the `FetchEvent` which returns the id of the `Client` that the current service worker is controlling"_. So, `scope.clients.get(event.clientId)` should not be returning undefined.

It does indeed sound like a Chrome issue. I would report it on their tracker (if not already reported).

**Comment by mateenQureshi** [comment] 2018-04-20 07:16
Great explanation. Now, at least I am able to explain clients why this weird thing is happening. Thanks!

Yeah, i didn't reported on Chrome issues tracker. Please report and mention that this is happening only when you are logged in with your google account. If browser is running without login, client Id remains the same and update goes fine.

Thanks again @gkalpak

**Comment by gkalpak** [comment] 2018-04-30 20:06
Apparently, it is acceptable behavior to have an empty client ID, so we need to fix this in `@angular/service-worker`. Let's track this in #23526.
