### ISSUE TITLE
RC5 shared components issue

### ISSUE THREAD

**Issue by hassanasad** [angular/angular#10677] opened 2016-08-11 10:28 UTC
Hi everyone!

I upgraded the application from RC4 to RC5 and was working just fine. It was also working fine when i modified the `bootstrap` to the latest root module method. Then i converted one section of the application using NgModule approach. This Module is pulled in using routing.

So the issue is i have two components  (Nav, header) which are being used in different components. When i put them in the `declarations` part of the Featured Module i get a warning in my browser console that its declared in two places, AppModule and CatalogModule (even though i have not explicitly declared it in AppModule. 

After some research i found out that RC5 automatically pulls in all declarations to avoid breaking changes for developers using previous versions. So i Added the components explicitly in the `declarations` of the AppModule (root Module) and removed it from the CatalogModule (feature module). There are no compiler/browser errors now but the components are not loaded in that route. The header and Nav is simply missing.

For other components its working which belong to AppModule.

Can anyone please shine some light on what i could be doing wrong ?

**Comment by DaSchTour** [comment] 2016-08-11 10:33
First take a look at this discussion #10552. There you will find everything that is good and bad about modules.
Second quoting from NgModule properties

> Components, directives and pipes must belong to exactly one module.

Which means. A component that is used in different module has to be packed into a module.

**Comment by hassanasad** [comment] 2016-08-11 10:50
Funny thing - i was actually reading the discussion there when i saw your reply.

Thanks - i will try the sharedModule approach (if i can get it to work) now. Hope it becomes easy.

**Comment by pkozlowski-opensource** [comment] 2016-08-11 11:35
Duplicate of #10552

**Closed by pkozlowski-opensource** 2016-08-11 11:35 UTC
