### ISSUE TITLE
Doc examples e2e flakes cause frequent CI failures for aio_e2e2 job 

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#20159] opened 2017-11-03 16:21 UTC
## Current behavior
Frequently occurring flake in the "aio" travis job:
```
1) Api pages should show classes that implement an interface
  - Failed: stale element reference: element is not attached to the page document
    (Session info: chrome=62.0.3202.0)
    (Driver info: chromedriver=2.33.506092 (733a02544d189eeb751fe0d7ddca79a0ee28cce4),platform=Linux 4.11.6-041106-generic x86_64)
```

## Expected behavior
no flakes :)

**Comment by IgorMinar** [comment] 2017-11-03 16:24
@petebacondarwin and @gkalpak already started looking into this issue a few days ago, but it is still occurring. Pete, George, can you please post the most recent status update here?

@vicb - fyi since you are the caretaker that sees this one quite often.

**Comment by gkalpak** [comment] 2017-11-03 17:25
AFAICT, there are currently 3 flakes that come up:

1. `expected 0 to be greater than 0`
    They occur in [these specs][1] and are related to the fact that we always [scroll to the top][2] after a short delay once a new doc is rendered. (So, it is a race condition.)

2. `stale element reference: element is not attached to the page document`
    I've seen this occur in tests that [use the `getLink()` helper][3]. It might be related to the fact that the links can appear in two places, either in the topbar (if the window is wide enough) or in the sidenav. This changes dynamically depending on the window's width.

3. `javascript error: document unloaded while waiting for result`
    This happens mostly in the [API pages specs][4] (in any of them), but I've seen it in other specs too (with much lower frequency though). I have no idea what might be causing this.

##
Other things we (don't) know:

- We don't know exactly what triggered the flakes. Changes that happened around the same time the flakes started to appear and may have affected e2e tests (but without being clear how or why):
    - Upgrade to Chrome 62 (in 820bb7bd8).
    - Fix another flake related to Google Analytics (in 441e01c56).
- There is a PR that might address (or at least considerably reduce) the first two flakes: #20117
- I don't think we have been able to reproduce the 3rd one locally (I haven't).
- As pointed out by @petebacondarwin, it seems as if protractor is not properly waiting for Angular. Could be an issue with (a) Protractor, (b) ChromeDriver, (c) Zones, (d) the Testability service, (e) all of the above. 
- There is an ongoing investigation :smiley:

##
Considering this is a major pain point for all PRs atm, @petebacondarwin has suggested (and I agree) that we should move the e2e tests into a selarate optional job, while we investigate.

[1]: https://github.com/angular/angular/blob/dcf88408314ccc384d827715c29d25f3a12c8d00/aio/e2e/app.e2e-spec.ts#L42-L60
[2]: https://github.com/angular/angular/blob/dcf88408314ccc384d827715c29d25f3a12c8d00/aio/src/app/app.component.ts#L215-L216
[3]: https://github.com/angular/angular/blob/dcf88408314ccc384d827715c29d25f3a12c8d00/aio/e2e/app.e2e-spec.ts#L14
[4]: https://github.com/angular/angular/blob/dcf88408314ccc384d827715c29d25f3a12c8d00/aio/e2e/api.e2e-spec.ts

**Comment by IgorMinar** [comment] 2017-11-03 21:33
@gkalpak move the e2e tests to an optional job sounds good if we don't have any potential fix in sight. 

@vikerman have you seen any issues related to e2e test flakes with Chrome 62 and protractor?

**Comment by gkalpak** [comment] 2017-11-04 16:45
Some more info/findings:

- I reverted 441e01c56 and still get flakes, so that's not it.
- Still get flakes with Chrome 64 (dev).
- Most (all) `stale element reference` errors appear (if my understanding is correct) when trying to perform an action (e.g. `getText()`, `click()`, etc) on an element that has just been located by an element locator (e.g. `element(by.css('...')).getText()`). This is weird, because there is nothing that should have caused the element to be removed from the DOM.

##
From a quick look at the ChromeDriver source code:

- The `document unloaded while waiting for result` would be caused by a specific property missing from the `document` (as seen [here][1]).
- The `stale element reference` error, if the element was no longer reachable when calling [retrieveItem()][2], which could only happen (considering the element was previously reachable) if [clearStale()][3] has previosuly found the element to not be reachable. This check in turn depends on a [nodeRoot == document][4] check.

So, both of the above failures could be caused by the `document` reference changing unexpectedly.
For example, if a navigation happened at a point during the test when it should not.

[1]: https://cs.chromium.org/chromium/src/chrome/test/chromedriver/chrome/web_view_impl.cc?type=cs&q=%22$chrome_asyncScriptInfo%22&sq=package:chromium&l=758
[2]: https://cs.chromium.org/chromium/src/chrome/test/chromedriver/js/call_function.js?q=call_function.js&sq=package:chromium&dr&l=175
[3]: https://cs.chromium.org/chromium/src/chrome/test/chromedriver/js/call_function.js?q=call_function.js&sq=package:chromium&dr&l=182
[4]: https://cs.chromium.org/chromium/src/chrome/test/chromedriver/js/call_function.js?q=call_function.js&sq=package:chromium&dr&l=197

**Comment by IgorMinar** [comment] 2017-11-04 22:39
could this be some kind of zone.js bug that causes the tests to move on while assertions are still running? have we updated zone.js recently?

**Comment by JiaLiPassion** [comment] 2017-11-05 04:16
I would like to research about the `zone.js` part, but when I run `yarn e2e` under `aio`, the following error occurs.

```javascript
ERROR in Error: TypeError: Cannot read property 'length' of undefined
    at Object.unescapeIdentifier (/Users/lijia/workspace/angular/aio/node_modules/@angular/compiler-cli/node_modules/typescript/lib/typescript.js:10550:26)
    at getTextOfNode (/Users/lijia/workspace/angular/aio/node_modules/@angular/compiler-cli/node_modules/typescript/lib/typescript.js:68575:27)
    at emitIdentifier (/Users/lijia/workspace/angular/aio/node_modules/@angular/compiler-cli/node_modules/typescript/lib/typescript.js:66931:19)
    at pipelineEmitUnspecified (/Users/lijia/workspace/angular/aio/node_modules/@angular/compiler-cli/node_modules/typescript/lib/typescript.js:66594:28)
    at pipelineEmitWithHint (/Users/lijia/workspace/angular/aio/node_modules/@angular/compiler-cli/node_modules/typescript/lib/typescript.js:66566:50)
    at pipelineEmitWithSourceMap (/Users/lijia/workspace/angular/aio/node_modules/@angular/compiler-cli/node_modules/typescript/lib/typescript.js:66558:17)
    at emitNodeWithComments (/Users/lijia/workspace/angular/aio/node_modules/@angular/compiler-cli/node_modules/typescript/lib/typescript.js:64200:17)
    at pipelineEmitWithComments (/Users/lijia/workspace/angular/aio/node_modules/@angular/compiler-cli/node_modules/typescript/lib/typescript.js:66547:17)
    at pipelineEmitWithNotification (/Users/lijia/workspace/angular/aio/node_modules/@angular/compiler-cli/node_modules/typescript/lib/typescript.js:66541:17)
    at emit (/Users/lijia/workspace/angular/aio/node_modules/@angular/compiler-cli/node_modules/typescript/lib/typescript.js:66528:13)
    at emitParameter (/Users/lijia/workspace/angular/aio/node_modules/@angular/compiler-cli/node_modules/typescript/lib/typescript.js:66967:13)
    at pipelineEmitUnspecified (/Users/lijia/workspace/angular/aio/node_modules/@angular/compiler-cli/node_modules/typescript/lib/typescript.js:66605:28)
    at pipelineEmitWithHint (/Users/lijia/workspace/angular/aio/node_modules/@angular/compiler-cli/node_modules/typescript/lib/typescript.js:66566:50)
    at pipelineEmitWithSourceMap (/Users/lijia/workspace/angular/aio/node_modules/@angular/compiler-cli/node_modules/typescript/lib/typescript.js:66558:17)
    at emitNodeWithComments (/Users/lijia/workspace/angular/aio/node_modules/@angular/compiler-cli/node_modules/typescript/lib/typescript.js:64200:17)
    at pipelineEmitWithComments (/Users/lijia/workspace/angular/aio/node_modules/@angular/compiler-cli/node_modules/typescript/lib/typescript.js:66547:17)
```

I use `yarn 0.24.6` and `nodejs 7.0.0`.

**Comment by IgorMinar** [comment] 2017-11-05 10:15
please use yarn 1.0.2 instead

**Comment by petebacondarwin** [comment] 2017-11-05 10:54
Looks like we bumped up from 0.8.16 to 0.8.18 in this commit: https://github.com/angular/angular/commit/abfc41d6614acf721e591f113aa8c10e9af9bc60 12 days ago

**Comment by petebacondarwin** [comment] 2017-11-05 11:12
Do we now need to patch RxJS?

```
import 'zone.js/dist/zone-patch-rxjs';
```

**Comment by petebacondarwin** [comment] 2017-11-05 11:16
From looking through the changelog for zone.js (0.8.16->0.8.18) - The only commit (other than the one in the previous comment) that could conceivably make any difference could be https://github.com/angular/zone.js/commit/7ee8bcd

**Comment by JiaLiPassion** [comment] 2017-11-05 15:11
I have run the `e2e` test with `zone.js 0.8.16 and 0.8.18` 10 times each, not reproduced. 
my environment is 

```
Mac OS high sierra 10.13
Chrome 62.0.3202.75 64 bit
yarn 1.0.2
```

I will continue to try to reproduce.

**Comment by IgorMinar** [comment] 2017-11-05 16:29
You might need a less powerful machine to get the timing just right for the
flake to appear. Try sending a pr and watch ci results. You can restart the
build by pushing bogus changes into the pr branch.

We do might need to patch rxjs, it is the right thing to do since we use
rxjs extensively. Let's try that.

**Comment by JiaLiPassion** [comment] 2017-11-05 16:33
@IgorMinar , got it, I will try to make a PR to reproduce it.
And about `rxjs zone.js patch`,  if load `zone.js\dist\zone-patch-rxjs`,  currently there is an issue, and I described and resolved in this PR, https://github.com/angular/angular/pull/19192.

**Comment by gkalpak** [comment] 2017-11-06 09:36
AFAICT, this is not related to Zone.js. The problem is that in some cases the page is reloaded (one or more times) without any obvious reason. That can happen for example while we `browser.waitForAngular()` (which uses `executeAsyncScript()` under the hood). That would explain the issues with different `document` references described in my previous comment.

I still haven't been able to figure out what is causing the reloads, but afaict (by logging all requests [sent to ChromeDriver][1]) there is no more request sent between the `execute_async` request (triggered by `waitForAngular()`) and the reloading.

Also afaict the reloading is not triggered by the aio app (e.g. through [LocationService][2]). My guess is that it is either called by Angular internals (very unlikely) or by something inside ChromeDriver.

> Fun fact:
> angular/protractor@81501c5d9 seems to work around a very similar problem with IEDriver.

Still very confused 😕 

[1]: https://github.com/SeleniumHQ/selenium/blob/83bdd7b2ed4e856fcb2a3400b38d40496abe2120/javascript/node/selenium-webdriver/http/index.js#L149
[2]: https://github.com/angular/angular/blob/3997d9780615dc323eb357bf7077d0264a1c35e9/aio/src/app/shared/location.service.ts

**Comment by gkalpak** [comment] 2017-11-15 12:06
I did as much digging a I could without entering ChromeDriver/Chrome internals. As mentioned above, there seems to be some unexpected, unprovoked (afaict) reloading, probably triggered by ChromeDriver (or Chrome), which leads to the flakes. I have no idea what might be causing it and why it only appears in the aio e2e tests.

That being said, downgrading ChromeDriver and Chrome to v2.32 and v59 respectively does make the flakes go away. See #20403.

From superficial look at each project's changelogs, I didn't spot something suspicious, but obviously I can only understand that much :smiley:

##
I don't feel there is point in putting more time into this atm (although it makes me very unhappy to not have gotten to the bottom of it 😢 :smiley:)

That being said, we need a ling-term plan (can't stay on Chrome 59 forever). The current plan is "wait and hope ChromeDriver 2.34 solves the issue", which doesn't sound very sustainable :grin:

**Comment by IgorMinar** [comment] 2017-12-14 17:54
thanks @gkalpak!!! let's hope that we won't see these flakes again for a long time.

**Comment by gkalpak** [comment] 2017-12-14 19:04
🤞

**Comment by IgorMinar** [comment] 2017-12-28 18:57
I'm reopening this because we still see lots of flakes :-(

Examples: 

https://travis-ci.org/angular/angular/jobs/322376385#L2555
```
1) Reactive forms final demo Magneta form should show hero information when the button is clicked
  - Failed: stale element reference: element is not attached to the page document
    (Session info: chrome=62.0.3202.94)
    (Driver info: chromedriver=2.33.506092 (733a02544d189eeb751fe0d7ddca79a0ee28cce4),platform=Linux 4.9.6-040906-generic x86_64)
2) Reactive forms final demo Magneta form shows a json output from the form
  - Failed: stale element reference: element is not attached to the page document
    (Session info: chrome=62.0.3202.94)
    (Driver info: chromedriver=2.33.506092 (733a02544d189eeb751fe0d7ddca79a0ee28cce4),platform=Linux 4.9.6-040906-generic x86_64)
```

https://travis-ci.org/angular/angular/jobs/320558864#L2546
```
1) Reactive forms formArray demo Bombastic FormArray form should show a checkbox
  - Failed: javascript error: document unloaded while waiting for result
    (Session info: chrome=62.0.3202.94)
    (Driver info: chromedriver=2.33.506092 (733a02544d189eeb751fe0d7ddca79a0ee28cce4),platform=Linux 4.9.6-040906-generic x86_64)
  - Failed: No element found using locator: By(css selector, input[formcontrolname=sidekick])
```

https://travis-ci.org/angular/angular/jobs/320555547#L2476
```
1) Reactive forms final demo Bombastic form has two disabled buttons by default
  - Failed: Index out of bound. Trying to access element at index: 1, but there are only 0 elements that match locator By(css selector, app-hero-detail > form > div > button)
```

All of these are related to reactive forms examples, but we've also seen similar flakes from animations as well.

**Comment by petebacondarwin** [comment] 2017-12-29 07:45
Should we give Cypress test runner a try for our examples? Its main constraint is that it only runs tests on Chrome, but we only test the examples on Chrome anyway.

**Comment by petebacondarwin** [comment] 2018-01-03 20:44
By the way, 62.0.3186.0 is actually revision 494273. See this screenshot from https://www.chromium.org/developers/calendar

![screen shot 2018-01-03 at 20 42 48](https://user-images.githubusercontent.com/15655/34539034-da0168b6-f0c6-11e7-8f0d-7b568c3984be.png)

**Comment by gkalpak** [comment] 2018-01-03 21:20
As mentioned in [the comment][1], 494239 was _part of_ `62.0.3186.0`, but not the final `62.0.3186.0`. This was intentional, since 494239 was the last revision that didn't flake for aio e2e tests.

The fact that we were getting `62.0.3202` instead of `62.0.3186` is weird (and unexpected). I hope it is a false reporting from ChromeDriver or Protractor, because Karma seems to think it is [62.0.3186][2] on the same build that ChromeDriver/Protractor think it is [62.0.3202][3] 😕 

[1]: https://github.com/angular/angular/commit/b4db2e25d62c6899969c4525941f1a489cace9d7#diff-d8042549363664b881594f5884455c31R40
[2]: https://travis-ci.org/angular/angular/jobs/320558863#L1233
[3]: https://travis-ci.org/angular/angular/jobs/320558864#L2303

**Comment by petebacondarwin** [comment] 2018-01-03 21:41
How can Protractor be false reporting the version in that way? This sounds a bit fishy. Perhaps Protractor is actually using a different Chrome version for real?

**Comment by gkalpak** [comment] 2018-01-03 22:07
I don't think there is any other version of Chrome available for Protractor to use, but might be worth investigating.

It is ChromeDriver that does the reporting btw (either [here][1] or [here][2]).

[1]: https://cs.chromium.org/chromium/src/chrome/test/chromedriver/commands.cc?l=266&rcl=e0fe27a0124cb198feabbd52605bc769cfa7d056
[2]: https://cs.chromium.org/chromium/src/chrome/test/chromedriver/util.cc?l=425&rcl=e0fe27a0124cb198feabbd52605bc769cfa7d056

**Comment by petebacondarwin** [comment] 2018-01-03 22:31
But still, it is strange since Webdriver just [asks Chrome for it](https://cs.chromium.org/chromium/src/chrome/test/chromedriver/util.cc?l=424)

```
const BrowserInfo* browser_info = session->chrome->GetBrowserInfo();
```

**Comment by gkalpak** [comment] 2018-01-03 22:50
I created #21296 to check ([travis build][1]) and it seems to indeed use the Chromium version _we_ install.

[1]: https://travis-ci.org/angular/angular/builds/324816404

**Comment by gkalpak** [comment] 2018-01-04 12:27
As discussed "offline", it turns out I spoke too soon. I stopped looking at the log once I saw [this error][1], but this only happens on non-cli-based examples. The cli-based ones are ignoring our `CHROME_BIN` variable (something that broke when we switched to cli-based examples).

So, @petebacondarwin is right: There seems to be a different version of Chrome (62.0.3202 atm), which is used for most examples e2e tests (since most are now cli-based). This would explain why the flakes started happening out of the blue - they probably started happening when that version of Chrome was updated past `62.0.3186`.

I was so certain there is only our pinned version of Chrome, I would've never noticed the different version in failed e2e tests. Great eye, @petebacondarwin 💯 :smiley:

##
So, now we need to find a way to use our pinned version for all examples e2e tests.
(Optionally, we can try to find out where the "other" Chrome comes from :grin:)

[1]: https://travis-ci.org/angular/angular/jobs/324816411#L1490

**Closed** 2018-01-04 22:13 UTC
Labels: comp: aio, freq3: high, severity3: broken, type: bug
