### ISSUE TITLE
Directive composition: Composed directive should be able to set inputs of constituent directives

### ISSUE THREAD

**Issue by MaximSagan** [angular/angular#56353] opened 2024-06-10 05:26 UTC
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

Currently, the directive composition API allows us to create a "composed directive" that brings together one or more "constituent directives" (those declared in its `hostDirectives`) and the inputs/outputs of these "constituent directive" can be exposed (with optional aliasing) as inputs/outputs on the "composed directive".

However, 
1. inputs/outputs of "constituent directives" cannot be set by the "composed directive", and (as a result)
2. for exposed inputs/outputs, it is the responsibility of the **component** using the "composed directive" to set these properties directly; the "composed directive" is unable to transform these properties before they are passed to the "constituent directives".

This means that any "abstraction" of constituent directives is limited to aliasing of their inputs/outputs. Surely this severely limits the usefulness of directive composition.

### Example of current state

Here, we have a composed directive trying to set the input of its constituent directive (declared in its `hostDirectives`), but to no avail. (If it were working, we would expect the text to be green.)
This is of course a contrived example (mapping a boolean to a color string), but we can imagine that such a mapping may be much more complex, involving DI and construction of complex objects.

https://stackblitz.com/edit/directive-composition-cannot-set-inputs-from-directive?file=src%2Fmain.ts (ng18)

(Note that setting the constituent directive input from the composed directive does not work, regardless of whether I declare the `hostDirectives` item as `ConstituentDirective` or `{ directive: ConstituentDirective, inputs: ["appConstituent"] }`.

### Proposed solution

Allow composed directive to set constituent directive inputs, such that the above example works as expected.

### Alternatives considered

N/A

**Comment by MaximSagan** [comment] 2024-06-14 01:46
@alxhub @pkozlowski-opensource

**Comment by Xymanek** [comment] 2024-06-14 21:28
You can inject constituent directives and set the values directly. Not perfect (detached from lifecycle, doesn't trigger `ngOnChanges`, etc.) but it worked as a stopgap solution for me in some cases

**Comment by pkozlowski-opensource** [comment] 2024-06-19 15:05
This is essentially duplicate of #50510

**Closed by pkozlowski-opensource** 2024-06-19 15:05 UTC
Labels: area: core, core: host directives
