### ISSUE TITLE
Allow Local Registration in a Module System

### ISSUE THREAD

**Issue by xiaoxiangmoe** [angular/angular#34864] opened 2020-01-20 09:57 UTC
# 🚀 feature request

### Relevant Package

 This feature request is for `@angular/core`.

### Description

We should register component in NgModule.

Can we register components/pipes/directives used in components.

Vue example: [Local Registration in a Module System](https://vuejs.org/v2/guide/components-registration.html#Local-Registration-in-a-Module-System).

### Describe the solution you'd like 

```ts
@Component(...)
@ComponentDeps({
   declarations: [...] //*** extra component/directive/pipe we want*** same as ng module
})
export class LocalComponent {
 ...
}
```

### Describe alternatives you've considered

* This may be achieved with ivy renderer.
* This need update angular language service support.
* It will be better if we can change selector name.

**Comment by Jordan-Hall** [comment] 2020-01-20 13:44
@xiaoxiangmoe This wouldn't add any real benefits. Also angular is designed to be modular approach.  From the sounds of it you are creating a "feature" component in which case should use a module for that feature

**Comment by JoostK** [comment] 2021-07-15 23:05
Closing as a duplicate of #33507.

**Closed by JoostK** 2021-07-15 23:05 UTC
Labels: comp: core, core: NgModule, core: directive matching, feature, insufficient votes, votes required
