### ISSUE TITLE
links on angular.io open new pages with scroll down the page

### ISSUE THREAD

**Issue by Frazer** [angular/angular#29893] opened 2019-04-14 17:25 UTC
# 📚 Docs or angular.io bug report

### Description

When I scroll down a page on https://angular.io/, then click a link to another angular.io page, I would expect the new page to open at the top of that page.  However the angular.io app keeps the current page scroll, so the new page opens scrolled down as far as the previous page.

### What's the affected URL?**

https://angular.io/

### Reproduction Steps**

go to https://angular.io/,   scroll down a page, click on a link.

### Expected vs Actual Behavior**

expected:  new page opens at the top of that page

actual:  new page opens scrolled down the same distance as the last page

## 🔥 Exception or Error
<pre><code>

</code></pre>

### Browser info

chrome 73.0.3  on mac mojave

**Comment by mohammedzamakhan** [comment] 2019-04-14 17:28
I do not see that issue when I access angular.io

**Comment by gkalpak** [comment] 2019-04-15 08:52
I can't reproduce it either. We are supposed to explicitly [scroll to top][1], on new navigations (i.e. no reloading or back/forward in history).

We did some changes recently to restore scroll positions, when reloading or navigating back/forward in history. It shouldn't mess with scroll position on other navigations (e.g. clicking on a link), but it is possible we have missed something (the code is quite complex).

##
@Frazer, I am going to close this, since it is not actionable without a way for us to reproduce it, but I would be happy to reopen and investigate, if we have a reproduction. So, thx for reporting and feel free to continue the discussion below.

Maybe you can provide more info to help us recognize patterns, possible culprits or ways to reproduce it. E.g.:
- Are you seeing this on specific types of URLs (e.g. API docs, non-API docs, guides, other pages)?
- What browsers does this happen (or not happen) on (other than Chrome 73 that you mentioned already)?
- What devices does it happen on?
- Does it happen consistently for you or only soemtimes?
- Does it seem to be affected by other factors (network conditions, size of the page, etc.)?

##
cc @wKoza (who has written mostly of the scroll restoration logic)

[1]: https://github.com/angular/angular/blob/ea70d41ac2314cdfc58688b488f85108466e5f92/aio/src/app/shared/scroll.service.ts#L122-L123

**Comment by wKoza** [comment] 2019-04-15 10:08
Hi @gkalpak ,
After reflection, there is maybe a scenario which can be problematical. I've recognised that recently, we have a refresh when we click on a link (seems linked to the SW). In this case, I'm wondering if our script  dont't think that we are in this case of a reload. I'll check that.

**Comment by wKoza** [comment] 2019-04-16 09:05
@gkalpak , Can you explain me why, sometime, I have a refresh of angular.io when I click on a link. is it linked to the SW ? 
In all cases, when it's happen, we don't remove the position[ from the session storage](https://github.com/angular/angular/blob/0e201ea9d86d941be14f169267ae5f7353576a54/aio/src/app/shared/scroll.service.ts#L184). To prevent this, we may call this method when we click on a link [here ](https://github.com/gkalpak/angular/blob/5787bc4c2425996eaab6eb0a30f0867009727f8e/aio/src/app/app.component.ts#L251).

**Comment by gkalpak** [comment] 2019-04-16 11:25
Ah, good point, @wKoza. There indeed this case, where we do a "full" navigation when there is a SW update: https://github.com/angular/angular/blob/9147092a156203d46cd1c865e06fa72a1e2d4137/aio/src/app/shared/location.service.ts#L44

For context, here is how this works:
- The SW will periodically check for updates.
- As soon as an update is found, the update is "activated" (which means that new clients will be served the new, updated assets (but existing clients will still see the old resources)).
- As soon as the update is activated, the SW notifies existing clients. When this happens, the aio app will set a flag that the SW has an update (but not immediatelly relod the page to avoid interrupting the user).
- The next time the user clicks on an in-app link, the app checks to see if the SW update flag is set and, if so, does a full navigation (which will result in being recognized as a new client and thus get the latest version from the SW).

##
So, it is very possible that we don't handle scroll restoration correctly in that case :grin:

**Comment by wKoza** [comment] 2019-04-16 12:02
It was exactly what I searched ! A good old `window.location`. Maybe can you re-open this issue because removeStoredScrollPosition() is not trigged in this case.

**Comment by gkalpak** [comment] 2019-04-16 12:09
Thx for getting to the bottom of it, @wKoza. Great sleuthing 🕵️

**Closed** 2019-05-08 16:25 UTC
Labels: comp: docs-infra, type: bug/fix
