### ISSUE TITLE
Dynamic Code Loader sample throws ExpressionChangedAfterItHasBeenCheckedError

### ISSUE THREAD

**Issue by Kumfert** [angular/angular#20670] opened 2017-11-28 22:26 UTC
## I'm submitting a...

<pre><code>
[X] Documentation issue or request
(sample code)
</code></pre>

## Current behavior

1. Open this [Plunkr/live coding example](https://angular.io/generated/live-examples/dynamic-component-loader/eplnkr.html) in a web browser. It is referenced by [Angular Docs -> Fundamentals -> Template & Data Binding -> Dynamic Components](https://angular.io/guide/dynamic-component-loader).
2. Open the javascript console.
3. See ExpressionChangedAfterItHasBeenCheckedError thrown in the logs.

## Expected behavior

Sample code shouldn't throw errors. 

## Environment

<pre><code>
Angular version: 5.0.3 (current)

Browser:
- [X] Chrome (desktop) version Version 62.0.3202.94 (Official Build) (64-bit)
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Platform: macOS 10.13.1 "High Sierra"

Others:

</code></pre>

**Comment by trotyl** [comment] 2017-11-29 03:02
Duplicate of #18797

**Closed** 2017-11-29 19:21 UTC
Labels: comp: docs
