### ISSUE TITLE
Inconsistent behavior between ngClass and class bindings in OnPush CD

### ISSUE THREAD

**Issue by mattdistefano** [angular/angular#12789] opened 2016-11-10 01:04 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
See plunker - I'm not sure if it's the async binding that triggers CD here or one of the form control events, but whatever it is, `[ngClass]` seems to miss it. A regular `[class.whatever]` binding OTOH _does_ work. Both seem to work with Default CD.

**Expected behavior**
I'd expect `[ngClass]` and `[class.whatever]` to be consistent.

**Minimal reproduction of the problem with instructions**
https://plnkr.co/edit/PhGey9btrsaARV0ldh4x?p=preview

**What is the motivation / use case for changing the behavior?**
Consistency of behavior.

**Please tell us about your environment:**

* **Angular version:** 2.1.2

* **Browser:** Chrome
 
* **Language:** TS

**Comment by pkozlowski-opensource** [comment] 2016-11-10 16:15
There is a lot going on in your plunker (ngModel that is async, observables with the async pipe etc.) but just few observations here:
* CD gets kicked off by the async pipe: https://github.com/angular/angular/blob/7cab30f85dd778ff4a26a4ca8c57ca24db17b81f/modules/%40angular/common/src/pipes/async_pipe.ts#L137
* there is a timing issue going on that make your `className` getter to return different values, check this plunker: https://plnkr.co/edit/PhGey9btrsaARV0ldh4x?p=preview

In any case this is not specific to `ngClass`, I would rather suspect `ngModel` asynchronicity being the culprit here

**Comment by mattdistefano** [comment] 2016-11-10 16:40
Is the plunker for the timing issue you mention correct? Looks like the one I posted originally?

Re. `ngClass` - I'm totally open to the idea that `ngModel` is to blame (see #12516 for a possibly-related issue) but I'm not sure why the `{{ className | json }}` expression updates correctly and yet `[ngClass]="className"` does not.

**Comment by kemsky** [comment] 2016-11-12 00:52
This is pretty interesting, it depends on *position* of the element in template, if you move `input` to the top, all elements placed *below* will receive changes. 

It looks like `ngModel` state is changed during change detection cycle, and if so - it is a bug.

**Comment by mattdistefano** [comment] 2016-11-12 16:01
Well I guess that makes sense - the CD must apply bindings in source/DOM order. Though TBH I still don't get why the second example works, when the only difference is that it uses a `class.` binding vs. the `ngClass` directive.

And yeah the status does change mid-way, because the `@Input` setter on `required` ends up calling `AbstractControl.updateValueAndValidity()` which, since the control is now required (and empty), updates the status to invalid. But I guess it doesn't trigger a new CD since there's no DOM or `@Output` event in play?

The naive approach I've been taking in my custom validators is to wrap those calls in a setTimeout so it _does_ trigger another CD cycle, but that a) feels hacky and b) doesn't work for the built-in validators.

i.e.
```typescript
registerOnValidatorChange(fn: () => void) {
  this._onChange = fn;
}

ngOnChanges(changes: SimpleChanges) {
  if (this._onChange) {
    setTimeout(() => {
      this.changeDetector.markForCheck();
      this._onChange();
    });
  }
}
```

**Comment by kemsky** [comment] 2016-11-12 18:12
`[class.name]`, `[style.name]`, `[attr.name]` - all of them are processed last, after main loop, after all directives and components.

**Comment by noemi-salaun** [comment] 2017-11-14 20:18
With default CD, `ngModel` combined with `ngClass` triggers the `Expression has changed after it was checked` error.

See [this plunker](https://plnkr.co/edit/9ypV50iPwJzKWOo6R8wb?p=preview)

Simply replacing `[ngClass]` with `[class]` fixes it.

**Comment by AndrewKushnir** [comment] 2020-08-12 22:15
Hi,

I've performed additional investigation and re-created repro scenarios using Stackblitz and the recent versions of Angular packages, here is a couple links:

- [Repro from original report](https://stackblitz.com/edit/angular-ivy-12789-2?file=src%2Fapp%2Fapp.component.ts). I see the same behavior in both use-cases now.
- [Repro](https://stackblitz.com/edit/angular-ivy-12789?file=src/app/app.component.ts) using an example from https://github.com/angular/angular/issues/12789#issuecomment-344384736. Everything seems to be working fine as well and there are no `Expression has changed after it was checked` errors.

Note: in both repros I used Ivy, so the original problem was most likely fixed in Ivy.

I will close this ticket for now (since I was unable to reproduce it), feel free to open a new one (with a new repro) if the problem still exists.

Thank you.

**Closed by AndrewKushnir** 2020-08-12 22:15 UTC
Labels: comp: core, comp: forms, core: change detection, forms: ngModel, freq1: low, severity3: broken, state: needs more investigation, triage #1, type: bug/fix
