### ISSUE TITLE
Initiate AOT compilation from the command line using ngc of compiler-cli is failing Error : Expected 'stylesUrls' to be an array of strings. Angular 4

### ISSUE THREAD

**Issue by xtianus79** [angular/angular#16134] opened 2017-04-18 21:28 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

Output from: `ng --version`.
"@angular/compiler-cli": "4.0.2",

node v7.9.0
macOS ( Sierra?)

Simple steps to reproduce this bug.
Please include: commands run, packages added, related code changes.
A link to a sample repo would help too.

following the steps here https://angular.io/docs/ts/latest/cookbook/aot-compiler.html 
this command is run:
node_modules/.bin/ngc -p tsconfig-aot.json

### The log given by the failure.
Error: Expected 'styleUrls' to be an array of strings.
    at assertArrayOfStrings (/Users/xxxxx/xxxxx/xxxxx/xxxxx/node_modules/@angular/compiler/bundles/compiler.umd.js:3361:19)
    at CompileMetadataResolver.getNonNormalizedDirectiveMetadata (/Users/xxxxx/xxxxx/xxxxx/xxxxx/node_modules/@angular/compiler/bundles/compiler.umd.js:13786:13)
    at CompileMetadataResolver._getEntryComponentMetadata (/Users/xxxxx/xxxxx/xxxxx/xxxxx/node_modules/@angular/compiler/bundles/compiler.umd.js:14484:45)
    at /Users/xxxxx/xxxxx/xxxxx/xxxxx/node_modules/@angular/compiler/bundles/compiler.umd.js:14470:48
    at Array.forEach (native)
    at CompileMetadataResolver._getEntryComponentsFromProvider (/Users/xxxxx/xxxxx/xxxxx/xxxxx/node_modules/@angular/compiler/bundles/compiler.umd.js:14469:30)
    at /Users/xxxxx/xxxxxx/xxxxx/frontend/node_modules/@angular/compiler/bundles/compiler.umd.js:14433:83
    at Array.forEach (native)
    at CompileMetadataResolver._getProvidersMetadata (/Users/xxxxxxx/xxxxxx/xxxxxxx/xxxxxx/node_modules/@angular/compiler/bundles/compiler.umd.js:14397:19)
    at /Users/xxxxxx/xxxxxxxxx/xxxxxxx/xxxxxx/node_modules/@angular/compiler/bundles/compiler.umd.js:14399:23
Compilation failed

### Desired functionality.
it should work

### Mention any other details that might be useful.
I am using angular 4.0.2 and it's components

I posted this here in the repo for angular-cli but I don't think it belongs there. 

https://github.com/angular/angular-cli/issues/6002

**Comment by Toxicable** [comment] 2017-04-18 21:29
is your `stylesUrls` an array of strings?

**Comment by xtianus79** [comment] 2017-04-19 02:20
@Toxicable the problem is that everything works without aot and it doesn't work with aot...

also, how can I test if they are an array of strings?

**Comment by Toxicable** [comment] 2017-04-19 02:23
Take a look at the `stylesUrls` of your components and see if any are not arrays of strings

**Comment by xtianus79** [comment] 2017-04-19 02:34
they all are... this seems to be a bug

**Comment by xtianus79** [comment] 2017-04-19 02:39
@Toxicable look at this bug... he implemented the same thing and receives the same error...

https://github.com/angular/angular-cli/issues/5989

**Comment by pkozlowski-opensource** [comment] 2017-04-19 07:27
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by xtianus79** [comment] 2017-04-19 12:13
@pkozlowski-opensource what? Can you explain.

**Comment by pkozlowski-opensource** [comment] 2017-04-19 12:25
@xtianus79 I've closed this one since you've linked to another open issue (https://github.com/angular/angular-cli/issues/5989) which according to you is:

> the same thing and receives the same error...

As such it would be a direct duplicate and there is no reason / need to keep 2 entries open for the same issue.

BUT scanning through this and the CLI issue there is no reproduce scenario. So in fact we don't know if there is an issue at all, what is the root cause etc.

All in all it boils to the lack of the reproduce scenario. If you are sure that https://github.com/angular/angular-cli/issues/5989 is the same issue as yours than please track https://github.com/angular/angular-cli/issues/5989. If you are unsure please provide a minimal reproduce scenario (a minimal repository that we can clone and see the problem) and re-open this issue.

**Comment by xtianus79** [comment] 2017-04-19 14:03
@pkozlowski-opensource thanks for reply... 
The issue is a little bit complicated to convey because of the nature of how in part people are using angular-cli and not directly using it but rather @angular/compiler-cli... 

that is why I reported here and linked to the issue over at the angular-cli repo.  

I asked the OP on the other thread to place an ts-config-aot.json config and run that to see if he receives the same error and he did.  

As a result I feel they are related issues.  

I will try to create a repo with a reproduced issue today.  

I appreciate the help.  sorry for the confusion

**Comment by xtianus79** [comment] 2017-04-21 13:46
@pkozlowski-opensource here is a repo that illustrates the issue... This is production stopping from AOT working... is there any way this can be a higher priority?  

 https://github.com/scascarini/repo5989

from:

https://github.com/angular/angular-cli/issues/5989

**Comment by xtianus79** [comment] 2017-04-22 20:17
@Toxicable so in the end you were correct about this error... is as angular-calandar using this statement that went haywire... 

let styles = String(require('../../../../../node_modules/angular-calendar/dist/css/angular-calendar.css'));

Oddly when i updated the calendar it is now working with the same statement.  

With that said I really wish the error lead me to the file and command that was in error.  thanks. 

I now move on to the next AOT compilation error

**Closed** 2017-04-22 20:17 UTC
Labels: comp: core & compiler, state: Need repro
