### ISSUE TITLE
add generic function pipe to API

### ISSUE THREAD

**Issue by Keorl** [angular/angular#30612] opened 2019-05-22 11:34 UTC
Hi,
I just made a small thing that I think could be provided by angular API, but I'm not comfortable enough to contribute myself.
Basically I recently learned that you shouldn't call function in html templates, otherwise they are called many times in lifecycle and can cause performance issues. So you're supposed to create a pipe instead, and the pipe's "transform" method is in charge of calling the function you need on your object.
I figured that creating a brand new pipe for each function I need to call is not efficient, not reusable . So I made a generic pipe that takes function name and parameters as parameter. I think it'd be nice to have this implemented in Angular API as one of the basic pipes.

Here is my code :
```
import { Pipe, PipeTransform } from '@angular/core';

@Pipe({
  name: 'function'
})
export class FunctionPipe implements PipeTransform {

  transform(value: any, name: string, ...args: any): any {
    if (value && name && typeof(value[name]) === 'function') {
      return value[name](...args);
    }
    return null;
  }

}
```

And usage (in this example, item is of custom type Item and I need to display a value calculated by the function priceWithTaxes which takes tax % as parameter.
` <td>{{ item | function:'priceWithTaxes':30 | currency:'EUR' }}</td>`

**Comment by mlc-mlapis** [comment] 2019-05-22 12:43
@Keorl ... discussed many times in other issues as **pure function** ... but still not decided if and how exactly to implement -> post Ivy era.

**Comment by Keorl** [comment] 2019-05-22 13:13
ok i'll look for this, thank you

**Comment by JoostK** [comment] 2021-07-14 12:07
Duplicate of #20419

**Closed by JoostK** 2021-07-14 12:07 UTC
Labels: comp: core, core: change detection, feature, insufficient votes, votes required
