### ISSUE TITLE
In some cases using bindings to add styles/classses leads to unintentional transitions

### ISSUE THREAD

**Issue by BlindDespair** [angular/angular#47803] opened 2022-10-18 16:39 UTC
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

We have a complex project with custom built components among which we have button and select. Those have transition of background color defined on them meant to run when user is hovering or clicking. But in our app this transition is running on initial rendering also which results in an annoying flash-like effect (as it transitions from default user-agent defined background to the one set in the css class).
After 2 days of debugging I figured that it is related to the fact that we are adding our classes using `[class]` binding as we don't use the emulated encapsulation we have our own engine that creates unique class names. And this doesn't happen consistently e.g. we have 2 elemnts of the same component in the template and only the first one would be rendered without flash and the consequent ones would have a flash. 

https://user-images.githubusercontent.com/15785773/196486750-70dc824d-5f35-496e-9def-5dce36e2a358.mov

On the video above you can see the rendering order of the elements. The buttons with `TEXT` written on them have `class="myclass"` hardcoded on them and are rendered instantly with the first cycle. The other 2 are buttons of the select element and classes are applied on them using `[class]="'myclass'"`. And what would happen if I would refreshed the page without breakpoints is that the first element with `[class]="'myclass'"` would appear to be rendered instantly just like `TEXT` but the second one (fourth if you count all of them from top to bottom) would have animation on it.
This is can be observed in the minimal repro with a much simpler setup (check `extra.component.ts`). What I realized causes it here is the `[style.width.px]="ref.offsetWidth"` somewhere in the template before the element that uses `[style]` binding. But as I remove this in my app I still have the flashing effect until I remove the resolvers from the page, but I obviously need those. So it looks like this happens whenever something is delaying the rerendering of components (as initial Ivy render doesn't apply the bindings).

I suppose we can work this issue around by adding `transition` into `:hover` and `:active` blocks but would be great if this can be somehow fixed in a normal way. Why does Ivy not apply bindings in the first rendering cycle even though the value for it is already available?

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-e2z8fp?file=src/app/extra.component.ts

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 14.2.6
Node: 16.15.0
Package manager: npm 8.5.5

Angular: 14.2.6
```

**Comment by Mdkarimul** [comment] 2022-10-19 08:49
Hi he have resolved the issues in hehalf of my understanding .

**Comment by jessicajaniuk** [comment] 2022-10-19 12:11
Closing as resolved since you seemed to have resolved the issue.

**Comment by BlindDespair** [comment] 2022-10-19 16:52
@jessicajaniuk I am sorry, what makes you think that it is resolved? Did you actually check it?

**Comment by BlindDespair** [comment] 2022-10-20 12:14
@jessicajaniuk this issue should not be closed. My answer about bindings is not answered and the fact that Angular doesn't render bindings on the first cycle despite their values being availble is wrong IMO!
And my problem specifically is not solved either. Moving `transition` into a pseudo-class makes the transition run only one direction.
I spent a fair amount of time investigating this, recording a video for you and making a repro in stackblitz, so please investigate this properly.

**Comment by BlindDespair** [comment] 2022-10-20 12:29
@pkozlowski-opensource thank you for reopening the issue.

> The crux of the issue is this line `<div [style.width.px]="ref.offsetWidth">e</div>` - what is happening here is that a value read from the DOM (`ref.offsetWidth`) is causing reflow and makes subsequent animations to run.

This is one of the ways to make this issue happen, but it seems like not the only one. As I mentioned in the issue description, resolvers also somehow have an effect on this although not on all pages and I cannot tell why. E.g. if I remove `[style.width.px]="ref.offsetWidth"` in our app, the animations still run until I completely remove resolvers from the page. But I don't understand how that affects the rendering. Resolvers run before components are even created.

**Comment by pkozlowski-opensource** [comment] 2022-10-20 12:34
@BlindDespair using `ref.offsetWidth` in a _binding_ is definitively not what Angular bindings are for. It sounds like you should do the `<div [style.width.px]="ref.offsetWidth">e</div>` bit in a directive (or in the component's ngAfterViewChecked lifecycle hook).

What is see in your example is an unfortunate, but expected, combination of how a browser and Angular are designed. The root cause of this unfortunate interaction is causing a [reflow](https://developers.google.com/speed/docs/insights/browser-reflow) in a binding. This is something what should be very much avoided, not only because it causes unwanted side effects that you are observing - but more importantly because it _substantially_ slows down change detection.

I'm going to close this issue since both browsers and Angular both behave as designed. In this particular scenario Angular binding mechanism is misused.

**Closed by pkozlowski-opensource** 2022-10-20 12:34 UTC
Labels: area: core, core: styling bindings, state: needs more investigation

**Comment by BlindDespair** [comment] 2022-10-20 13:17
@pkozlowski-opensource thank you for the explanation! I am willing to accept this. Besides pointing at reflow was useful for me to start digging in the right direction. It is not actually the resolvers causing the problem but router subscriptions that directly mess with DOM.

**Comment by jessicajaniuk** [comment] 2022-10-21 16:33
@BlindDespair Apologies. There was a comment present at the time of closing that indicated this had been fixed / addressed. Thanks, @pkozlowski-opensource, for responding.
