### ISSUE TITLE
Angular 2 form with a angular 1 app

### ISSUE THREAD

**Issue by taxinvoice** [angular/angular#6500] opened 2016-01-15 05:43 UTC
I have a angular 2 form bootstraped to a angular 1 form and i get this error on page load.  

ChangeDetectionError {_wrapperMessage: "TypeError: Cannot read property 'validator' of undefined in [form in AppVersionComponent@4:26]", _originalException: TypeError: Cannot read property 'validator' of undefined at NgFormModel.ngOnChanges (http://loca…, _originalStack: "TypeError: Cannot read property 'validator' of und…tp://localhost:37197/Scripts/angular.js:15888:40)", _context: _Context, _wrapperStack: "Error: TypeError: Cannot read property 'validator'…lar2/src/upgrade/downgrade_ng2_adapter.js:90:102)"…}
_context: _Context
_originalException: TypeError: Cannot read property 'validator' of undefined at NgFormModel.ngOnChanges (http://localhost:37197/node_modules/angular2/src/common/forms/directives/ng_form_model.js:111:77) at AbstractChangeDetector.ChangeDetector_AppVersionComponent_0.detectChangesInRecordsInternal (viewFactory_AppVersionComponent:45:59) at AbstractChangeDetector.detectChangesInRecords (http://localhost:37197/node_modules/angular2/src/core/change_detection/abstract_change_detector.js:104:18) at AbstractChangeDetector.runDetectChanges (http://localhost:37197/node_modules/angular2/src/core/change_detection/abstract_change_detector.js:81:14) at AbstractChangeDetector._detectChangesInViewChildren (http://localhost:37197/node_modules/angular2/src/core/change_detection/abstract_change_detector.js:187:18) at AbstractChangeDetector.runDetectChanges (http://localhost:37197/node_modules/angular2/src/core/change_detection/abstract_change_detector.js:85:14) at AbstractChangeDetector.detectChanges (http://localhost:37197/node_modules/angular2/src/core/change_detection/abstract_change_detector.js:70:73) at ChangeDetectorRef_.detectChanges (http://localhost:37197/node_modules/angular2/src/core/change_detection/change_detector_ref.js:21:73) at Object.<anonymous> (http://localhost:37197/node_modules/angular2/src/upgrade/downgrade_ng2_adapter.js:90:102) at Scope.$digest (http://localhost:37197/Scripts/angular.js:15888:40)
_originalStack: "TypeError: Cannot read property 'validator' of undefined↵    at NgFormModel.ngOnChanges (http://localhost:37197/node_modules/angular2/src/common/forms/directives/ng_form_model.js:111:77)↵    at AbstractChangeDetector.ChangeDetector_AppVersionComponent_0.detectChangesInRecordsInternal (viewFactory_AppVersionComponent:45:59)↵    at AbstractChangeDetector.detectChangesInRecords (http://localhost:37197/node_modules/angular2/src/core/change_detection/abstract_change_detector.js:104:18)↵    at AbstractChangeDetector.runDetectChanges (http://localhost:37197/node_modules/angular2/src/core/change_detection/abstract_change_detector.js:81:14)↵    at AbstractChangeDetector._detectChangesInViewChildren (http://localhost:37197/node_modules/angular2/src/core/change_detection/abstract_change_detector.js:187:18)↵    at AbstractChangeDetector.runDetectChanges (http://localhost:37197/node_modules/angular2/src/core/change_detection/abstract_change_detector.js:85:14)↵    at AbstractChangeDetector.detectChanges (http://localhost:37197/node_modules/angular2/src/core/change_detection/abstract_change_detector.js:70:73)↵    at ChangeDetectorRef_.detectChanges (http://localhost:37197/node_modules/angular2/src/core/change_detection/change_detector_ref.js:21:73)↵    at Object.<anonymous> (http://localhost:37197/node_modules/angular2/src/upgrade/downgrade_ng2_adapter.js:90:102)↵    at Scope.$digest (http://localhost:37197/Scripts/angular.js:15888:40)"
_wrapperMessage: "TypeError: Cannot read property 'validator' of undefined in [form in AppVersionComponent@4:26]"
_wrapperStack: "Error: TypeError: Cannot read property 'validator' of undefined in [form in AppVersionComponent@4:26]↵    at ChangeDetectionError.WrappedException [as constructor] (http://localhost:37197/node_modules/angular2/src/facade/exceptions.js:32:31)↵    at new ChangeDetectionError (http://localhost:37197/node_modules/angular2/src/core/change_detection/exceptions.js:83:16)↵    at AbstractChangeDetector._throwError (http://localhost:37197/node_modules/angular2/src/core/change_detection/abstract_change_detector.js:283:21)↵    at AbstractChangeDetector.detectChangesInRecords (http://localhost:37197/node_modules/angular2/src/core/change_detection/abstract_change_detector.js:111:18)↵    at AbstractChangeDetector.runDetectChanges (http://localhost:37197/node_modules/angular2/src/core/change_detection/abstract_change_detector.js:81:14)↵    at AbstractChangeDetector._detectChangesInViewChildren (http://localhost:37197/node_modules/angular2/src/core/change_detection/abstract_change_detector.js:187:18)↵    at AbstractChangeDetector.runDetectChanges (http://localhost:37197/node_modules/angular2/src/core/change_detection/abstract_change_detector.js:85:14)↵    at AbstractChangeDetector.detectChanges (http://localhost:37197/node_modules/angular2/src/core/change_detection/abstract_change_detector.js:70:73)↵    at ChangeDetectorRef_.detectChanges (http://localhost:37197/node_modules/angular2/src/core/change_detection/change_detector_ref.js:21:73)↵    at Object.<anonymous> (http://localhost:37197/node_modules/angular2/src/upgrade/downgrade_ng2_adapter.js:90:102)"

**Comment by splintercode** [comment] 2016-01-15 14:48
Can you reduce this down to a [plunk](https://plnkr.co) ?

**Comment by mhevery** [comment] 2016-01-21 00:01
Please reopen once you have a reproducible plunker? Here may be a good start: http://plnkr.co/edit/yMjghOFhFWuY8G1fVIEg?p=preview

**Comment by zoechi** [comment] 2016-01-21 09:14
@mhevery seems you intended to close this one

**Closed** 2016-01-27 00:08 UTC
