### ISSUE TITLE
Can't resolve all parameters for .... This will become an error in Angular v6.x  

### ISSUE THREAD

**Issue by FrancescoBorzi** [angular/angular#24414] opened 2018-06-11 11:16 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

I have 4 classes:

- Class A, @Injectable
- Class B, abstract, **NON** injectable, extends A
- Class C, @Injectable, extends B
- Class D, @Injectable, extends B

classes A, C and D are used as Services and correctly added to the `providers` list of my module. Class B is **NOT** used as a service.

## Current behavior
Everything works fine but I got this warning:

> Can't resolve all parameters for ClassBService in /path/to/class-b.service.ts: ([object Object], ?). This will become an error in Angular v6.x

## Expected behavior

Not sure if some action on my side is required or this warning should not be displayed.

## Demo

Clone the repository, run `npm install` and then `ng build --prod`. You'll see the warning.

https://github.com/ShinDarth/angular-test/

https://github.com/ShinDarth/angular-test/commit/4101bc56cd9f9a13915017ee40c6a90b51d363c5

## Environment

> Angular CLI: 1.7.4
> Node: 8.10.0
> OS: linux x64
> Angular: 5.2.11
> ... animations, common, compiler, compiler-cli, core, forms
> ... http, language-service, platform-browser
> ... platform-browser-dynamic, router
> 
> @angular/cli: 1.7.4
> @angular-devkit/build-optimizer: 0.3.2
> @angular-devkit/core: 0.3.2
> @angular-devkit/schematics: 0.3.2
> @ngtools/json-schema: 1.2.0
> @ngtools/webpack: 1.10.2
> @schematics/angular: 0.3.2
> @schematics/package-update: 0.3.2
> typescript: 2.6.2
> webpack: 3.11.0
>

**Comment by ShinDarth** [comment] 2018-06-11 11:21
@trotyl I would appreciate to know how I can improve my issue report.

**Comment by trotyl** [comment] 2018-06-11 11:24
Please provide a reproduction via https://stackblitz.com/

**Comment by ShinDarth** [comment] 2018-06-11 11:28
@trotyl I got the warning when compiling, but in the web app everything is fine. As I said, this is my setup:

> I have 4 classes:
> 
> Class A, @Injectable
> Class B, abstract, NON injectable, extends A
> Class C, @Injectable, extends B
> Class D, @Injectable, extends B
> classes A, C and D are used as Services and correctly added to the providers list of my module. Class B is NOT used as a service.

not sure how I can reproduce the compile warning here.

**Comment by trotyl** [comment] 2018-06-11 11:36
@ShinDarth Then you could create a brand new Angular CLI application to repro this problem.

**Comment by mlc-mlapis** [comment] 2018-06-11 13:09
@ShinDarth ... we don't know what are the constructors of all 4 classes also.

**Comment by ShinDarth** [comment] 2018-06-11 14:36
@trotyl @mlc-mlapis here's a very small Angular app which reproduces the issue:

https://github.com/ShinDarth/angular-test/

https://github.com/ShinDarth/angular-test/commit/4101bc56cd9f9a13915017ee40c6a90b51d363c5

**Comment by trotyl** [comment] 2018-06-11 14:46
Duplicate of https://github.com/angular/angular/issues/22153

**Comment by ShinDarth** [comment] 2018-06-11 15:39
@trotyl  no it is not. I've already checked those issues. The main difference is that in their case the service which is triggering the warning has the `@Injectable` annotation (and they solve the warning by simply removing it).

In my case, Service B has **NO** `@Injectable`.

**Comment by trotyl** [comment] 2018-06-11 15:47
@ShinDarth The linked issue above doesn't have an `@Injectable()` either, you can check the [source code](https://github.com/WiseBird/angular_inheritance_resolve_issue/blob/7f696374ca5357fda01cf1ddc1d7a89d6f3c1250/src/components/intermediate.component.ts#L9-L13). It's exact same except `string`/`enum` difference.

**Comment by ShinDarth** [comment] 2018-11-23 08:48
just FYI: even using `"enableIvy": true` I get this warning

**Comment by FrancescoBorzi** [comment] 2019-04-01 13:00
I confirm that the bug is still present using **Angular 7**, and it' still saying:

> This will become an error in Angular v6.x

**Comment by DulithaRanatunga** [comment] 2019-04-05 05:15
Having this problem too. Angular 7 complaining only when ng build is called with --prod / --aot.
Its still a warning (not an error), but its annoying to have logged. I can also confirm that its different to the duplicate tickets marked above.

**Comment by hoangtranson** [comment] 2019-05-08 06:32
I got the same issue on Angular 7.2.0
`ERROR in : Can't resolve all parameters for ɵc in path_to_project/dist/core/core.d.ts: (?).`

**Comment by andreash92** [comment] 2019-07-30 14:13
any updates on this?

**Comment by naviciroel** [comment] 2019-08-29 21:34
any updates on this? 
If below is present on the code:
`
@Injectable({
  providedIn: 'root'
})
`
this is the build issue: 
> Warning: Can't resolve all parameters for SwKendoGridService in /mnt/data/projects/sw-dashboard/projects/sw-kendo/src/lib/sw-kendo-grid.service.ts: ([object Object], ?, ?). This will become an error in Angular v6.x
> Warning: Can't resolve all parameters for SwKendoGridService in /mnt/data/projects/sw-dashboard/projects/sw-kendo/src/lib/sw-kendo-grid.service.ts: ([object Object], ?, ?). This will become an error in Angular v6.x
> ERROR: Internal error: unknown identifier []
> An unhandled exception occurred: Internal error: unknown identifier []
> See "/tmp/ng-fyidOs/angular-errors.log" for further details.

When removing the 
`
@Injectable({
  providedIn: 'root'
})
`
there's no warning or error on build but when using the service on the web app:
![image](https://user-images.githubusercontent.com/6640515/63977841-6b6be500-cae7-11e9-83e0-1b939a82a5f1.png)

**Comment by meeroslav** [comment] 2019-08-30 11:29
I had this issue because I am using generics to reduce code duplication. Here is my original code that was causing the warning:

```ts
@Injectable()
export abstract class MyBaseClass<S> {
  protected constructor(protected readonly service: S) {}
  
  // .. some code
}
```

Since this class is abstract it will never be injected anywhere, thus it should not be decorated with `@Injectable()`.

**Comment by Kolahzary** [comment] 2019-09-22 16:50
I got the same warning (project is working fine with`ng serve`):
```
Warning: Can't resolve all parameters for CachedReadableService in .../_services/infrastructure/cached-readable.service.ts: ([object Object], ?). This will become an error in Angular v6.x
Warning: Can't resolve all parameters for CachedCrudService in .../_services/infrastructure/cached-crud.service.ts: ([object Object], ?). This will become an error in Angular v6.x
```

Result of `ng --version`:
```
Angular CLI: 8.3.1
Node: 10.16.1
OS: win32 x64
Angular: 8.2.3
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.1
@angular-devkit/build-angular     0.803.1
@angular-devkit/build-optimizer   0.803.1
@angular-devkit/build-webpack     0.803.1
@angular-devkit/core              8.3.1
@angular-devkit/schematics        8.3.1
@angular/cdk                      8.1.4
@angular/cli                      8.3.1
@angular/fire                     5.2.1
@angular/pwa                      0.803.1
@ngtools/webpack                  8.3.1
@schematics/angular               8.3.1
@schematics/update                0.803.1
rxjs                              6.5.2
typescript                        3.5.3
webpack                           4.39.2
```

**Comment by akapfham** [comment] 2019-09-26 10:57
Same or similar problem here except that the error occurs at runtime (no problems reported from the compiler).

We have an abstract base class which looks like that (excerpt):

```
export abstract class VerticalSplitComponent<TUpperComponent extends IViewComponent, TLowerComponent extends ISlaveViewComponent> extends CommonViewComponent implements AfterViewInit, OnDestroy {
	/** ctor. */
	constructor(private componentFactoryResolver: ComponentFactoryResolver, private changeDetector: ChangeDetectorRef) {
		super();
	}
}
```

From this class the following class is derived:

```
@Component({
    selector: 'app-currency-exrate-container-use-case',
    templateUrl: '../../../../../shared/components/vertical-split/vertical-split.component.html',
    styleUrls: ['../../../../../shared/components/vertical-split/vertical-split.component.less'],
})
export class CurrencyExchangeRateContainerComponent extends VerticalSplitComponent<CurrencyComponent, ExchangeRateComponent> {
	// no ctor.
}
```

This works with @angular-devkit/build-angular Version 0.802.2. After updating this package to 0.803.6 the following error occurs at runtime when starting the module which contains the CurrencyExchangeRateContainerComponent:

```
Uncaught (in promise): Error: Can't resolve all parameters for CurrencyExchangeRateContainerComponent
```


The solution for this problem: DI has to be performed on a class which has the `@Component` - Decorator!

So, after changing the code as follows, everything works.

Base class:

```
export abstract class VerticalSplitComponent<TUpperComponent extends IViewComponent, TLowerComponent extends ISlaveViewComponent> extends CommonViewComponent implements AfterViewInit, OnDestroy {
	/** ctor. - Now empty */
	constructor() {
		super();
	}
}
```

Derived class:

```
@Component({
    selector: 'app-currency-exrate-container-use-case',
    templateUrl: '../../../../../shared/components/vertical-split/vertical-split.component.html',
    styleUrls: ['../../../../../shared/components/vertical-split/vertical-split.component.less'],
})
export class CurrencyExchangeRateContainerComponent extends VerticalSplitComponent<CurrencyComponent, ExchangeRateComponent> {
	/** ctor. - Now with DI */
    constructor(private componentFactoryResolver: ComponentFactoryResolver, private changeDetector: ChangeDetectorRef) {
        super();
    }
}
```


I do not know if this "breaking change" is documented somewhere. It seems that it was introduced with the step from 0.802.2 > 0.803.6 of the package @angular-devkit/build-angular.


Result of ng --version:

```
Angular CLI: 8.3.6
Node: 10.16.0
OS: win32 x64
Angular: 8.2.8
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.6
@angular-devkit/build-angular     0.803.6
@angular-devkit/build-optimizer   0.803.6
@angular-devkit/build-webpack     0.803.6
@angular-devkit/core              7.3.9
@angular-devkit/schematics        7.3.9
@angular/cli                      8.3.6
@angular/http                     7.2.15
@ngtools/webpack                  8.3.6
@schematics/angular               8.3.6
@schematics/update                0.803.6
rxjs                              6.5.3
typescript                        3.5.3
webpack                           4.39.2
```

**Comment by dody87** [comment] 2019-10-07 22:58
> I had this issue because I am using generics to reduce code duplication. Here is my original code that was causing the warning:
> 
> ```ts
> @Injectable()
> export abstract class MyBaseClass<S> {
>   protected constructor(protected readonly service: S) {}
>   
>   // .. some code
> }
> ```
> 
> Since this class is abstract it will never be injected anywhere, thus it should not be decorated with `@Injectable()`. Removing it makes compiler happy again.
> 
> If you need `@Injectable` then `@Inject` needs to be also provided - the solution proposed by @tonysamperi.

It works, when you remove injectable decorator, then your abstract/generic class compiled successfully. Thanks.

**Comment by alxhub** [comment] 2020-02-20 23:24
This is fixed in Angular Ivy in v9!

**Closed by alxhub** 2020-02-20 23:24 UTC
Labels: comp: core, fixed by Ivy, freq1: low, severity1: confusing, type: bug/fix
