### ISSUE TITLE
Route Animations: query returns 0 elements on lazy loaded modules

### ISSUE THREAD

**Issue by AKuzmanoski** [angular/angular#17164] opened 2017-06-01 18:54 UTC
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When i try to animate routes inside lazy loaded module
query('selector', ...) returns 0 elements

One problem is that leaving component is killed too early.
I made a workaround by keeping components alive by providing them with empty :enter and :leave animations

```
trigger('pageAnimation', [
    transition(':enter', [
      animate(158, style({ }))
    ]),
    transition(':leave', [
      animate(150, style({ }))
    ])
  ])
```

However query(":enter", ...) and query(":leave") still return 0 elements, I had to query components by their names.

**Expected behavior**

query("selector", ...) working properly in lazy loaded modules

query(':leave', ...) returns leaving component in lazy loaded modules
query(':enter', ...) return entering component in lazy loaded modules

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

Keeping code clean

**Please tell us about your environment:**

Windows 10
Webstorm 2017.1
Angular 4.2.0-rc-1
Angular CLI 1.0.6

* **Angular version:** 2.0.X

yes

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Tested only on Chrome and Edge
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by matsko** [comment] 2017-06-01 21:28
@AKuzmanoski can you confirm this works if you do not lazy load the module?

**Comment by AKuzmanoski** [comment] 2017-06-01 23:11
No, my current project uses lazy loading modules, but i can try that tomorrow

**Comment by AKuzmanoski** [comment] 2017-06-07 13:18
@matsko
Sorry for my late response but now i can confirm that `:enter` and `:leave` return 0 elements only in lazy loaded module

But in non lazy loaded module problem with the timing remains.
If component has no animations, and animation is defined in routingAnimations leaving element is destroyed before animation finishes

**Comment by ShadowManu** [comment] 2017-08-18 19:55
Status on this? Animating between routes in different feature modules seems unwieldy

**Comment by ayazhussein** [comment] 2017-10-27 00:14
any updates? got the same issue

**Comment by matsko** [comment] 2017-11-10 12:53
Can anyone here put together a stackblitz example for me so I go Angular detective mode and figure out what's the issue?

**Comment by tt9** [comment] 2017-12-15 16:54
I do not have time at the moment to make a repro project. But I am getting a similar issue except my routes aren't lazy loaded.

Upon loading the parent router the animation below doesn't find the :enter element. But If I change it to a class query it does find it. Note that it only breaks on the initial load not when routing from child page to child page. Then it works just fine.

```
export function squeezeAndPullLeft(startDelay = 0, enterDelay = 350, pageDuration = 150) {
  return animation([
    query(':leave', style({ /*position: 'absolute',*/ transform: 'scale(1) translateX(0px)', opacity: 1 }), { optional: true }),
    query(':enter', style({ /*position: 'absolute',*/ transform: 'scale(1) translateX(100px)', opacity: 0 }), { optional: true }),
    group([
      query(':leave', animate(`${pageDuration}ms ${startDelay}ms ${vars.accelerationCurve}`, keyframes([
        style({
          transform: 'scale(.95) translateX(0)',
          opacity: .6,
          offset: .5
        }),
        style({
          transform: 'scale(.95) translateX(0)',
          opacity: .6,
          offset: .7
        }),
        style({
          transform: 'scale(.95) translateX(-100px)',
          opacity: 0,
          offset: 1
        })
      ])
      ), { optional: true }),
      query(':enter', animate(`${pageDuration}ms ${startDelay + enterDelay}ms ${vars.deccelerationCurve}`, keyframes([
        style({
          transform: 'scale(1) translateX(0)',
          opacity: 1,
          offset: 1
        })
      ])
      ), { optional: true })
    ])
  ]);
}

```

**Comment by telmaco** [comment] 2017-12-21 12:57
Hi guys, having the same issue here ... animating between routes in different feature modules not working. Any advice is appreciated.

**Comment by telmaco** [comment] 2017-12-22 11:10
Hi matsko, 
As you requested I put a Plunker together with the issue I am facing here, maybe I am doing something wrong, I am not sure. :(

The issue is that the route animation does not work in between the feature modules that have lazy loading. It only works in between routes (with or without feature modules) that are not lazy loading .

Any advice on how I can fix this would be very appreciated.

https://embed.plnkr.co/IDRET1jPy4TaVDPOFVUs/

Thank you.

**Comment by telmaco** [comment] 2018-01-22 09:54
Anybody out there? :(

**Comment by Fluccioni** [comment] 2018-01-26 11:42
Hi @telmaco,

To make the plunkr you wrote working you just have to update you lazy loaded modules and set data to routes. As your animation is based on this, if there is no changes of value the animation won't trigger.

```Typescript
const settingsRoutes = [
    { path: '', component: SettingsComponent, data:{state:'settings'}}
];
```

**Comment by telmaco** [comment] 2018-02-02 09:19
Hi Fluccioni!
Thanks to your tip it works now!! Thank you so much for your help and for taking the time. I truly appreciate it. :)
You are blessed!
Cheers! 👍

**Comment by vicb** [comment] 2018-05-31 22:37
Looks like the issue has been fixed, closing.

**Closed by vicb** 2018-05-31 22:37 UTC
Labels: comp: animations, freq1: low, severity3: broken, state: Need repro, type: bug/fix
