### ISSUE TITLE
ability to ignore component css when calling it

### ISSUE THREAD

**Issue by amineparis** [angular/angular#22090] opened 2018-02-08 12:14 UTC
It would be great if we can reuse a component and ignore its css without modifying it. because a lot of plugins comes with predefined css that we don't want and we need to erase each time to make the component look as the rest of the application

**Comment by jotatoledo** [comment] 2018-02-08 18:27
Use the issue template

**Comment by trotyl** [comment] 2018-02-10 07:40
Duplicate of #15298

**Comment by mhevery** [comment] 2018-02-13 00:39
Duplicate of #15298

**Closed by mhevery** 2018-02-13 00:39 UTC
