### ISSUE TITLE
Unable to use `HostAttributeToken` on application root component

### ISSUE THREAD

**Issue by jamcoupe-ccl** [angular/angular#56255] opened 2024-06-04 11:43 UTC
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

When using `HostAttributeToken` on the root component I get a "No provider for HostAttributeToken" error.

I think this should either work as it does for all sub components or the documentation is updated to state that you can't use it in this way.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-aptaum?file=src%2Fmain.ts

### Please provide the exception or error you saw

```true
ERROR Error: NG0201: No provider for HostAttributeToken my-attr found. Find more at https://angular.dev/errors/NG0201
    at throwProviderNotFoundError (chunk-ZNRRMEEJ.js?v=20c7e349:4941:9)
    at lookupTokenUsingNodeInjector (chunk-ZNRRMEEJ.js?v=20c7e349:7714:9)
    at getOrCreateInjectable (chunk-ZNRRMEEJ.js?v=20c7e349:7688:19)
    at ɵɵdirectiveInject (chunk-ZNRRMEEJ.js?v=20c7e349:10617:17)
    at ɵɵinject (chunk-ZNRRMEEJ.js?v=20c7e349:5003:59)
    at inject (chunk-ZNRRMEEJ.js?v=20c7e349:5012:10)
    at new _App (main.ts:13:12)
    at NodeInjectorFactory.App_Factory [as factory] (main.ts:13:52)
    at getNodeInjectable (chunk-ZNRRMEEJ.js?v=20c7e349:7845:38)
    at createRootComponent (chunk-ZNRRMEEJ.js?v=20c7e349:14319:31)
```
```


### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 18.0.2
Node: 18.20.3
Package Manager: npm 10.2.3
OS: linux x64

Angular: 18.0.1
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1800.2
@angular-devkit/build-angular   18.0.2
@angular-devkit/core            18.0.2
@angular-devkit/schematics      18.0.2
@angular/cli                    18.0.2
@schematics/angular             18.0.2
rxjs                            7.8.1
typescript                      5.4.5
zone.js                         0.14.6
```

**Comment by JoostK** [comment] 2024-06-04 13:10
This is essentially the same as #1858

**Comment by alxhub** [comment] 2024-06-05 18:39
Closing as a duplicate of #1858 as Joost points out.

**Closed by alxhub** 2024-06-05 18:39 UTC
Labels: area: core, core: host and host bindings
