### ISSUE TITLE
Print preview doesn't include highlighted text for Chrome 99 when parent node contains overflow property.

### ISSUE THREAD

**Issue by jedrzejiwanicki** [angular/angular#45342] opened 2022-03-14 11:22 UTC
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

Hi, I noticed following problem after the Chrome 99 upgrade.

The issue seems to be related to websites powered by Angular framework, this seems to be the only common variable I noticed across tested websites.

To recreate the issue please follow these steps:
- Have your Chrome browser updated to 99
- Access Angular powered application e.g https://transparencyreport.google.com/
- In Dev Tools find any element containing text e.g h1, span etc.
- Apply overflow: auto/hidden on the parent element
- Highlight the text element with your cursor, open contextual menu and select Print
- The preview window will open and the highlighted text will not be included. 

Note 1: I noticed that in some cases it doesn't break when you apply the property on immediate parent, keep adding the property on next parent and eventually it will break.

Note 2: that the text node needs to be highlighted, selecting print without highlight will work(entire page will be included)

**Comment by JoostK** [comment] 2022-05-27 19:43
I've just attempted to reproduce this in Chrome 101.0.4951.64 and don't observe the reported behavior. A self-contained reproduction would be appreciated.

**Comment by AndrewKushnir** [comment] 2022-06-07 00:02
Closing this issue, since there is no repro.

**Closed by AndrewKushnir** 2022-06-07 00:02 UTC
Labels: needs reproduction, comp: core
