### ISSUE TITLE
Version 2.2.x breaks something with createEmbededView template variables

### ISSUE THREAD

**Issue by ribizli** [angular/angular#12968] opened 2016-11-18 13:43 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When I upgraded to version @2.2.0 PrimeNG DataTable RowExpansion is not working any more if the expansion template contains content which utilizes templates (e.g. structural directives).

It was still working in @2.1.2 (you can try in the plunkr above), so I don't think it is related to PrimeNG.

Source of the PrimeNG component: https://github.com/primefaces/primeng/blob/1.0.0-rc.4/components/datatable/datatable.ts

Sorry, but I haven't have time to strip down the problem (and the plunkr) without PrimeNG.

**Expected behavior**
RowExpansion has the correct template variables set. Should render the template content every time correctly.

**Minimal reproduction of the problem with instructions**
Check out my plunkr: http://embed.plnkr.co/bJ0ln941VPbUX7KP3Mtk/

Expand the first row: the content is shown correctly. Expand the second row: the content is something different, not reflecting the data content anymore. Any subsequent expansion is not working as expected.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.2.0
With the latest 2.2.1 version it fails too. But works with 2.1.2

* **Browser:** Chrome 54 (but I assume it is not related to the browser)
 
* **Language:** TypeScript 2.0

**Comment by DzmitryShylovich** [comment] 2016-11-18 14:07
Pls add:
1. steps to reproduce.
2. expected behavior.

**Comment by ribizli** [comment] 2016-11-20 20:39
I've managed to strip down the problem and eliminate PrimeNG from the game.
Here is the issue with `@ContentChild(TemplateRef)`: http://embed.plnkr.co/R5OTQ27OUZlRffkPJrVd/
The problem is happening if in the queried template there is an other template (via Structural Directive).

Here is a workaround with `@ContentChild('test')`: http://embed.plnkr.co/IsBnNpggTixSO91kqlOW/

**Comment by kukjevov** [comment] 2016-11-22 18:23
Is anybody from angular team looking into this? We can`t update our application to angular 2.2 because of this bug. 

Thanks for any help

**Comment by kukjevov** [comment] 2016-11-23 20:24
Please can you at least tell me whether is this even considered as bug, or it is "feature" @vicb ? I would like to know whether we should wait for fix, or announcement that this is intentional change. 

Because right now we have to find workaround to make this working. Workaround mentioned by @ribizli is not completely working in our case. 

I think this reference to same problem https://github.com/angular/angular/issues/13002 

Thank you

**Comment by mhevery** [comment] 2016-11-30 20:11
Closing as duplicate of #13080

**Closed** 2016-11-30 20:12 UTC
Labels: comp: core & compiler
