### ISSUE TITLE
ServiceWorker is not bootstrapping with SSR

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [angular/angular#24770] opened 2018-07-05 13:26 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
Service worker is not registered with SSR

## Expected behavior
Service worker is registered with SSR

## Minimal reproduction of the problem with instructions
When i use SSR line in app.module: 

<code>ServiceWorkerModule.register('/ngsw-worker.js', { enabled: environment.production }),</code> 

has no effect. However without ssr it has. However if i add 

<code>
 platformBrowserDynamic().bootstrapModule(AppModule).then(() => {
        if ('serviceWorker' in navigator) {
            navigator.serviceWorker.register('/ngsw-worker.js');
        }
    });
</code>
to main.ts everything works fine.

## Environment

<pre><code>
Angular version: 6.0.7

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 9.8.0
- Platform:

**Comment by gkalpak** [comment] 2018-07-05 16:13
Please add a reproduction (e.g. a repo we can check out) and exact steps to reproduce the problem.

**Comment by vytautas-pranskunas-** [comment] 2018-07-06 07:09
Adding reproduction with SSR and Serviceworker is long proccess do not think have time for this. But if you try it your self and give people sample project then it will be so much better. Then anyone who has such problems can look at it. As well as problems like SSR and ServicveWorker cannot be used together because index.html is cached and view source does not not show page content or if index.html is not cached then offline mode is not possible. So I think best way to go would be to show people working solution where all those techniques are applied and not hello world app but something with some services, http calls and some lazy load routes.

**Comment by gkalpak** [comment] 2018-07-06 09:59
Yeah, I understand. Time is an limited resource for all of us :wink:
That said, I think SSR and SW are currently not supported (without hacks) due to #23613 (see https://github.com/angular/angular/issues/23613#issuecomment-396037679). I am going to clode this a duplicate of #23613, but if you think it is a different problem, feel free to open a new issue with all the necessary details.

**Closed by gkalpak** 2018-07-06 09:59 UTC
Labels: comp: server, comp: service-worker, state: Need repro, type: bug/fix
