### ISSUE TITLE
Feature Request for cheat code PDF one or two sheet

### ISSUE THREAD

**Issue by chdnitinsharma** [angular/angular#24589] opened 2018-06-20 13:25 UTC
## I'm submitting a...

<pre><code>
[ x ] Feature request
</code></pre>

Hello, Can we have print button on [cheat code](https://angular.io/guide/cheatsheet) page. If user click on that link we can download PDF like this
[PDF format](https://code.visualstudio.com/shortcuts/keyboard-shortcuts-windows.pdf) Instead of using print button. As print button show all 15 pages. My thought all summaries will be in one or two pages.

It would be very easy for user to access and provide hard copy to newbie developer :-)

## What is the motivation?
Developer can easy access and recall from cheat code from one snapshot.

**Comment by jenniferfell** [comment] 2018-06-26 18:35
Thanks for submitting this request. Thanks also to those who have commented.

May I ask for some clarification about your use case: Are you looking for a format to use offline on an electronic device? If so, what is your preferred device? Or are you looking for something to print as hardcopy? (How we address those might be different.) Is your primary concern length or format?

As you know, you can already save the current pages as HTML or PDF: 

A: I used my browser (Chrome on Mac) to do "Save as HTML" and got everything I need for offline use in my browser (including the nice formatting you see when connected to the live site). It's readable and searchable.

B: I used my browser to save as PDF. The results are attached. Does this look like what you get? It could use some layout improvement, but all the content is there. I can search, select and copy sections, and add my own comments (with the right PDF viewer).

[Angular - Cheat Sheet.pdf](https://github.com/angular/angular/files/2138444/Angular.-.Cheat.Sheet.pdf)

Thank you for the example, but I don't think simply removing the descriptions is sufficient to reduce the size to 1-2 pages. Also, I think some people are using the descriptions--they are using this to make connections between what they want to do and the right code, not just for syntax.

**Comment by jenniferfell** [comment] 2018-06-26 18:35
Have you seen John Papa's plug-in for VSCode? https://github.com/johnpapa/vscode-angular-essentials

**Comment by jenniferfell** [comment] 2018-06-26 18:39
P.S. If the issue is primarily about having a downloadable, printable format, then may I close this as a duplicate of #24555 ? 

If the issue is wanting something shorter, then I'll keep this open. I do see the two things as distinct requests. Thanks!

**Comment by chdnitinsharma** [comment] 2018-06-26 18:52
Hello @jenniferfell, I need for offline in printable format (Hardcopy). As it should be one or two pages of cheat code. So that we can circulate to developers as they attach to their workstation. So that they can easily recall from cheat code. Hope, you get my point?

Yes, I want cheat code to be shorter.

**Comment by jenniferfell** [comment] 2018-10-17 17:50
Closing as duplicate of https://github.com/angular/angular/issues/24555. Making a note there to read the thread here, because this is very helpful. Thanks!

**Closed by jenniferfell** 2018-10-17 17:50 UTC
Labels: comp: docs, freq3: high, subtype: docs-infoarch, type: feature

**Comment by gnowland** [comment] 2019-07-02 10:20
Hey ya'll I also wanted a print version of the cheat sheet but the print styles are awful so I painstakingly made a PDF version of the current docs with an improved print layout - check it out:

[Angular v8 Cheat Sheet.pdf](https://github.com/angular/angular/files/3349538/Angular.v8.Cheat.Sheet.pdf)

It's not 2 pages but it covers everything on the site in a readable format.
