### ISSUE TITLE
Keep Query Params for Specific Routes on Navigation

### ISSUE THREAD

**Issue by Halfist** [angular/angular#37241] opened 2020-05-21 12:45 UTC
# 🚀 feature request

### Relevant Package
@angular/router

### Description
I have an application with two pages:
1. First, URL of which could contain query params, which represent current tab, sorting and pagination. E.g. `/first?tab=cats&sortBy=age&sortOrder=asc&pageIndex=3&pageSize=25`.
2. Second, URL of which shouldn't contain query params. E.g. `/second`.

When I navigate from First to Second, query parameters are removed as expected, since I don't use `queryParamsHandling`.

Though, when I navigate back from Second to First, query parameters aren't restored. This behavior is also expected, but I'd like to have a route configuration option to keep them.

The intention behind this in my case is that user should see the same filtered data set as he did before navigation, so he doesn't need to set tab, sorting and pagination again manually.

I tried to achieve similar behavior by providing user a button, which simulates browser Back via `window.history.back()` and Angular built-in `Location.back()`. Unfortunately, both suffer from duplicated history records [issue](https://stackoverflow.com/a/20317179/1611569), so user has to click the button several times to actually go back, which is unacceptable from UX perspective.

I also found the following solutions, but neither of them work as needed.

- https://medium.com/@timofeybm/3-methods-to-save-catalogue-state-and-scroll-position-in-angular-1a46ae4eadca (method 3)
- https://www.angulararchitects.io/aktuelles/sticky-routes-in-angular-2-3/
- https://github.com/angular/angular/issues/16845

### Describe the solution you'd like
```
// app-routing.module.ts
{
  path: 'first',
  component: FirstComponent,
  keepQueryParams: true
},
{
  path: 'second',
  component: SecondComponent
}
```

### Describe alternatives you've considered
The only alternative I see is manually subscribe to route change, keep query parameters in shared service and restore them when needed.

**Comment by Airblader** [comment] 2020-05-23 08:08
This seems to be a job for a state management tool, but not the core framework IMO.

There are also a bunch of questions which would immediately arise:

1. How can I navigate to first if I don't want the parameters to be kept? This requires even more API surface.
2. What should Angular do if a navigation to first is triggered which contains some query parameters, both ones kept in state and new ones? How is this merged with the kept state and can this be answered in a generic way rather than one opionated by a specific use case?

**Comment by atscott** [comment] 2020-06-15 20:45
I also agree with the points from @Airblader and feel like this could be achieved by subscribing to the router events and saving that state which you want to be restored. When a navigation finishes and you have a state to restore, you could trigger another navigation with [replaceUrl](https://angular.io/api/router/NavigationExtras#replaceUrl).

Could you clarify what you mean by "when I navigate back from Second to First, query parameters aren't restored."? When you say "back", do you mean navigate _to_ `first` _from_ `second` via `router.navigate`? I'm assuming so because clicking the `back` button on the browser _would_ restore the query parameters.

A reproduction would be helpful to demonstrate exactly what you're trying to do.

**Comment by Halfist** [comment] 2020-06-15 22:07
@Airblader
Then probably `keepQueryParams` should be replaced with `queryParamsStrategy: 'clean' | 'cache' | 'preserve' | 'merge'` with `'clean'` as default.

@atscott
Yes, via `router.navigate()` or `<a [routerLink]="first">` click.

**Comment by jelbourn** [comment] 2020-10-09 20:39
I chatted further this @atscott on this one and we agreed that an API like this wouldn't be the best fit for the framework, so closing this issue for now.

**Closed by jelbourn** 2020-10-09 20:39 UTC
Labels: comp: router, feature, flag: can be closed?, needs clarification, needs reproduction
