### ISSUE TITLE
issue(typings): include constructor definitions for classes in .d.ts

### ISSUE THREAD

**Issue by valorkin** [angular/angular#3938] opened 2015-09-01 15:01 UTC
Became important when you extend, for example, `DefaultValueAccessor` to work with `ng-model`
and see a list of errors:
```
ERROR in ./rating/rating.ts
(50,5): Supplied parameters do not match any signature of call target. (2346)

ERROR in ./timepicker/timepicker.ts
(151,5): Supplied parameters do not match any signature of call target. (2346)
...
```

I was trying to do it my self but, but constructor type parameters are come as string, not parsed, to dgeni templates

**Comment by Ablu** [comment] 2015-09-02 17:25
This also prevents me from creating forms:
~~~ ts
    this.controls = new ControlGroup({name: new Control("loginValue")});
~~~
The compiler complains about the missing constructor of `ControlGroup` and `Control`.

**Comment by jteplitz602** [comment] 2015-09-04 22:18
Duplicate of #3926.

I have a PR out for this (#3963), which should land today or early next week.

**Closed by jteplitz602** 2015-09-04 22:18 UTC
