### ISSUE TITLE
ng update loadchildren update creates broken code if you have route data

### ISSUE THREAD

**Issue by rfuhrer** [angular/angular#30739] opened 2019-05-29 20:46 UTC
# 🐞 bug report

### Affected Package

ng update -> Lazy Loading schematic

### Is this a regression?
No, new feature this version

### Description
Running the update schematic with the new lazy loading update causes broken code if you use the route data object. I use this object to automatically set the page title when navigating.
Before:
`{ path: 'jobs', loadChildren: './jobs/job.module#JobModule', data: { title: 'Jobs' } },`
After Update (extra ' character and missing , before data):
`{ path: 'jobs', loadChildren: '() => import('./jobs/job.module').then(m => m.JobModule) data: { title: 'Jobs' } },`
After manual fixing:
`{ path: 'jobs', loadChildren: () => import('./jobs/job.module').then(m => m.JobModule), data: { title: 'Jobs' } },`

## 🔥 Exception or Error
<pre><code>
ERROR in ClientApp/app/app-routing.module.ts(13,51): error TS1003: Identifier expected.
ClientApp/app/app-routing.module.ts(13,67): error TS1005: ',' expected.
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.0.0
Node: 12.3.1
OS: win32 x64
Angular: 8.0.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, material, platform-browser
... platform-browser-dynamic, platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.0
@angular-devkit/build-angular     0.800.0
@angular-devkit/build-optimizer   0.800.0
@angular-devkit/build-webpack     0.800.0
@angular-devkit/core              8.0.0
@angular-devkit/schematics        8.0.0
@angular/flex-layout              8.0.0-beta.26
@ngtools/webpack                  8.0.0
@schematics/angular               8.0.0
@schematics/update                0.800.0
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.30.0
</code></pre>

**Anything else relevant?**

**Comment by gkalpak** [comment] 2019-05-29 20:58
Looks like a duplicate of angular/angular-cli#14551.

**Closed by gkalpak** 2019-05-29 20:58 UTC
