### ISSUE TITLE
Page Not Found 🙃 - List of pipes 

### ISSUE THREAD

**Issue by ayadarwesh** [angular/angular#56497] opened 2024-06-18 18:36 UTC
### Describe the problem that you experienced

the note reference url in this page is not working:-
see the [pipes API documentation](https://angular.dev/api/common#pipes)

page url:-
https://angular.dev/api/common#pipes

**Comment by JeanMeche** [comment] 2024-06-18 18:37
Duplicate of https://github.com/angular/angular/issues/52968

**Closed by JeanMeche** 2024-06-18 18:37 UTC
