### ISSUE TITLE
Cannot uncheck radio button

### ISSUE THREAD

**Issue by draconisNoctis** [angular/angular#7227] opened 2016-02-22 15:12 UTC
When you set the radio button state to not checked, the view element is not updated.
`
let controls : Controls  = '...';
controls.updateValue(new RadioButtonState(false, controls.value.value))
`

This could be solved by changing 'src/common/forms/directives/radio_control_value_accessor.ts' to
`
  writeValue(value: any): void {
    this._state = value;
    if (isPresent(value)) {
      this._renderer.setElementProperty(this._elementRef.nativeElement, 'checked', value.checked);
    }
  }
`

It works in my environment, but I don't know about any side effects of this change.

**Comment by kylecordes** [comment] 2016-03-09 04:56
It appears, from reading various others' experience in older generations of tools, that to uncheck a checkbox we must *remove* the checked attribute, not merely set it to empty, set it to false, or set a checked property to false.

**Comment by EdS0ng** [comment] 2016-06-10 00:21
I'm seeing a similar problem. Selecting a new radio button does not uncheck the previously checked button. this results in all clicked buttons having a checked property set to true. If you style the buttons using the :checked selector, you will see multiple selections. I fixed this on my local RC1 by adding `this._renderer.setElementProperty(this._elementRef.nativeElement, 'checked', false);` to the fireUncheck method inside radio_control_value_accessor.ts. 

I'm not sure about adding the uncheck functionality that op mentions though. That might be against the point of using radio buttons.

**Comment by CarlCui** [comment] 2016-06-10 22:13
you can set it to `null`, I think.

**Comment by zoechi** [comment] 2016-06-11 10:26
I think this needs a Plunker to reproduce.

**Comment by kara** [comment] 2016-06-28 22:29
Thanks for the report! Radio buttons have been revamped in the new forms module (RC.2 and onward). See new usage here: #9228. Closing, as the issue is no longer applicable. Please feel free to re-open if you see problems with the new module.

**Closed by kara** 2016-06-28 22:29 UTC
Labels: comp: forms
