### ISSUE TITLE
Angular Elements not working during SSR in Angular 11

### ISSUE THREAD

**Issue by jaysoo** [angular/angular#40725] opened 2021-02-05 16:35 UTC
# 🐞 bug report

### Affected Package

The issue is caused by package `@angular/elements`

### Is this a regression?

Yes, this used to work in Angular 8-10.

### Description

During **SSR**, custom elements are getting default values on `@Input()` overridden by `undefined`. For example, if you have a component as follows:

```
class MyComponent {
  @Input() myInput = 'default value';
}
```

And you create an element `my-element` and use it without the `my-input` attribute (`<my-element />`), then it will set `myInput = undefined` rather than `'default value'`.

I tracked it down to this statement in the elements strategy where the inputs are initialized:

https://github.com/angular/angular/blob/bdce769/packages/elements/src/component-factory-strategy.ts#L212

If I provide a fallback when the map does not contain the input value, then everything works again.

```
this.setInputValue(
  propName,
  this.initialInputValues.get(propName) ??
    // fallback to component class property
    this.componentRef.instance[propName]
);
```

## 🔬 Minimal Reproduction

https://github.com/jaysoo/ng-elements-ssr

## 🌍  Your Environment

**Angular Version:**

<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 11.1.2
Node: 14.15.1
OS: darwin x64

Angular: 11.1.2
... animations, cli, common, compiler, compiler-cli, core
... elements, forms, platform-browser, platform-browser-dynamic
... platform-server, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1101.2
@angular-devkit/build-angular   0.1101.2
@angular-devkit/core            11.1.2
@angular-devkit/schematics      11.1.2
@nguniversal/builders           11.1.1
@nguniversal/express-engine     11.1.1
@schematics/angular             11.1.2
@schematics/update              0.1101.2
rxjs                            6.6.3
typescript                      4.1.3
</code></pre>

**Anything else relevant?**

Elements don't render child content during SSR by default, so we patched the `document.createElement` function to make it work with `domino`'s mutation events.

**Comment by gkalpak** [comment] 2021-02-08 12:26
The different behavior between SSR and in-browser rendering is caused by the implementation of your Custom Elements shims in [src/lib/custom-elements/custom_elements_shim.ts][1].

More specifically, it caused by the shims' applying all (own and inherited) properties of an instance onto a new `Node` [here][2] and [there][3]. In a nutshell, `instance` (which is an `NgElement` instance) will have getters and setters for all inputs as properties. This will result in setting these properties on `node` as `undefined` (since they don't have any value right after `instance` has been constructed). Since `node` will have had values set for these properties (even if these values are `undefined`), it will not use the default ones.

There are a couple of ways to improve your shims to not case this issue.
(DISCLAIMER: As I am sure you know, these shims are not an 100% accurate implementation of the Custom Elements feature and theremight be deviations from the "real" behavior in some cases.) 

**Option 1:** Do not copy inherited properties from `instance` onto `node`:

```diff
-for (const k in instance) {
+for (const k of Object.keys(instance)) {
   if (!node.hasOwnProperty(k)) {
     node[k] = instance[k];
   }
 }
```

**Option 2:** Do not copy properties with a value of `undefined` from `instance` onto `node`:

 for (const k in instance) {
-  if (!node.hasOwnProperty(k)) {
+  if (!node.hasOwnProperty(k) && (instance[k] !== undefined)) {
     node[k] = instance[k];
   }
 }

##
Given the above, everything works as expected in Angular's SSR.
I am going to close this issue, but feel free to continue the discussion below.

[1]: https://github.com/jaysoo/ng-elements-ssr/blob/2f59ca39908fbcc8de33f5a45fe864c6ded10b8b/src/lib/custom-elements/custom_elements_shim.ts
[2]: https://github.com/jaysoo/ng-elements-ssr/blob/2f59ca39908fbcc8de33f5a45fe864c6ded10b8b/src/lib/custom-elements/custom_elements_shim.ts#L78-L82
[3]: https://github.com/jaysoo/ng-elements-ssr/blob/2f59ca39908fbcc8de33f5a45fe864c6ded10b8b/src/lib/custom-elements/custom_elements_shim.ts#L202-L206

**Closed by gkalpak** 2021-02-08 12:26 UTC
Labels: comp: elements
