### ISSUE TITLE
Input signal: Alias needs to be a string that is statically analyzable.

### ISSUE THREAD

**Issue by martinboue** [angular/angular#58783] opened 2024-11-20 19:50 UTC
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

Thanks to `withComponentInputBinding()` I can bind query params or resolver data to component input.

With the old `@Input` decorator I could do this:

```
// In my routes.ts file...
export const MY_RESOLVER_DATA = 'my_data';
export const routes: Routes = [{ 
   /*...*/
   data: { [MY_RESOLVER_DATA]: myDataResolverFn  }
}]

// And in my component.ts file...
@Input({alias: MY_RESOLVER_DATA }) data: DataType;
```
That's really useful because I do not need to duplicate the literal string "my_data", it can be reused in multiple components. And that's the best way I know to make sure a required input is always provided.

But now with input signal, alias must always be a literal string like that:
```
readonly data = input<DataType>({ alias: 'my_data' });
```

If for some reason the resolver attribute changes in my route, I would not detect the regression in my components until runtime.

If I do `input<DataType>({ alias: MY_RESOLVER_DATA  }` I'll get the error 'Alias needs to be a string that is statically analyzable.'

Can input signal support constant variables as alias?

### Please provide the exception or error you saw

```true
Alias needs to be a string that is statically analyzable.'
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular 19.0.0
```

**Comment by JoostK** [comment] 2024-11-20 20:02
This has been restricted intentionally, as Angular is generally moving towards a local compilation model instead of cross-file analysis. So this is working as intended.

**Closed** 2024-11-20 20:03 UTC
Labels: area: compiler

**Comment by martinboue** [comment] 2024-11-20 20:09
Thanks @JoostK for your quick response.

Are you considering other solutions to check if a resolver is provided for a component in a route at compile time? For maintenance purposes, it would be better not to rely on a string or variable name.

**Comment by martinboue** [comment] 2024-11-27 19:14
> Are you considering other solutions to check if a resolver is provided for a component in a route at compile time? For maintenance purposes, it would be better not to rely on a string or variable name.

I have created an issue about this: #58940
