### ISSUE TITLE
request| feat(template): provide alias for `constructor` in template to access statics

### ISSUE THREAD

**Issue by PatrickJS** [angular/angular#9962] opened 2016-07-11 16:22 UTC
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
you need to use `constructor`

**Expected/desired behavior**
perhaps `$class`

**Reproduction of the problem**
http://plnkr.co/edit/JK1FbSomU15KgKU64Tr1?p=preview

**What is the expected behavior?**
you have to use `constructor`

**What is the motivation / use case for changing the behavior?**
to have access to static data

**Please tell us about your environment:**
- **Angular version:** 2.0.0-rc.4
- **Browser:** Chrome
- **Language:** TypeScript

http://plnkr.co/edit/JK1FbSomU15KgKU64Tr1?p=preview
related https://github.com/angular/angular/issues/4707

[![github-tipe-logo](https://user-images.githubusercontent.com/1016365/34912701-7edec34c-f89c-11e7-8c89-bed6cef064b5.png)](https://tipe.io?ref=github-comment)

**Comment by vicb** [comment] 2016-10-06 21:05
@gdi2290 would you mind sending a PR ? Thanks (no rush that would be for 3.0.0 due to the breaking change)

**Comment by AmerAnsari** [comment] 2021-02-14 20:37
This would be so useful.

**Comment by pkozlowski-opensource** [comment] 2022-11-11 09:28
I'm going to close this one as a duplicate of #25963 as this essentially covers the same need / use-case.

**Closed by pkozlowski-opensource** 2022-11-11 09:28 UTC
Labels: feature, area: core, core: binding & interpolation
