### ISSUE TITLE
Styling not applied to component rendered via NgComponentOutlet while using Emulated encapsulation

### ISSUE THREAD

**Issue by Jai-Krish** [angular/angular#56301] opened 2024-06-06 08:18 UTC
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

Yes

### Description

Any style that's applied on the child component from the parent component's stylesheet is not working since the `_ngcontent-ng-` is not added to the component rendered via `NgComponentOutlet`.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-fqoxh9?file=src%2Fmain.ts

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 18.0.3
Node: 18.20.3
Package Manager: npm 10.2.3
OS: linux x64

Angular: 18.0.2
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1800.3
@angular-devkit/build-angular   18.0.3
@angular-devkit/core            18.0.3
@angular-devkit/schematics      18.0.3
@angular/cli                    18.0.3
@schematics/angular             18.0.3
rxjs                            7.8.1
typescript                      5.4.5
zone.js                         0.14.6
```

**Comment by JeanMeche** [comment] 2024-06-06 16:38
The style works fine if you target the host directly : 

```
 :host {
      color: green;
  }
```

There is maybe an issue with the specifc selector you used. Did you notice other selector that exhibit this issue ?

**Comment by JoostK** [comment] 2024-06-06 18:09
This is about targeting the host element from the host component's styles, not from within the component itself.

This is an interesting one, since there is no host element anywhere in the component template itself. It's only created dynamically, synthesizing a tag name from the component selector. It does not, however, "bless" that element to become an actual content element of the view, i.e. get the content attribute of the component that the `ViewContainerRef` was obtained from.

**Comment by pkozlowski-opensource** [comment] 2024-06-26 15:00
Duplicate of #12215

**Closed by pkozlowski-opensource** 2024-06-26 15:00 UTC
Labels: area: core, core: CSS encapsulation
