### ISSUE TITLE
Dependency injection with --aot flag not working

### ISSUE THREAD

**Issue by matthew-a-thomas** [angular/angular#24322] opened 2018-06-06 14:33 UTC
## I'm submitting a...
<pre><code>
[x] Bug report
</code></pre>

## Current behavior
Dependency injection returns wrong instance when AOT flag is used.

## Expected behavior
Dependency injection should not behave differently when AOT flag is used.

## Minimal reproduction of the problem with instructions
~https://github.com/matthew-a-thomas/ng-di-aot~
https://www.dropbox.com/s/e6zqvz5npyiawux/ng-di-aot.zip?dl=0
(Instructions are in the `readme.md` file)

## What is the motivation / use case for changing the behavior?
Need to use AOT flag for prerendering.

## Environment

<pre><code>
Angular CLI: 6.0.7
Node: 8.11.0
OS: win32 x64
Angular: 6.0.3

Browser:
- [X] Chrome (desktop) version 68
- [X] IE version 11
- [X] Edge version 42.17134.1.0
 
For Tooling issues:
- Node version: v8.11.0
- Platform: Windows

</code></pre>

**Comment by alxhub** [comment] 2018-06-06 21:32
Wow, this is fascinating.

Just from a 5 minute glance, I think the issue is on https://github.com/matthew-a-thomas/ng-di-aot/blob/master/src/app/browser-specific.ts#L48. It's possible that AOT / the metadata system in general does not understand that `new InjectionToken<Options<T>>('Options')` creates a different token for every invocation of `getProviders`. I'm actually amazed that `new` is supported at all in this context.

It's unlikely that this bug will be addressed prior to Ivy (which moves DI to be an entirely runtime concept). However, there are ways to accomplish this effect without relying on tricks to construct `providers` at all. Here's how I would suggest implementing it:

https://stackblitz.com/edit/ng-service-with-alt?file=src%2Fapp%2Fservice.ts

This uses `@Injectable` to configure default providers for both the primary and alternate implementation of a service, as well as an `InjectionToken` with a default-provided factory that switches between them depending on the result of `isPlatformBrowser`. A helper function constructions that `injectionToken` given the primary and alternate service types.

In `app-module.ts` you can uncomment the `PLATFORM_ID` provider to see that the switching works.

**Comment by matthew-a-thomas** [comment] 2018-06-08 01:46
> Here's how I would suggest implementing it

@alxhub Thanks so much for that link. Your way of doing it is certainly simpler!

**Comment by alxhub** [comment] 2020-01-23 21:46
Closing as "won't fix"; this is not an issue in Ivy.

**Closed by alxhub** 2020-01-23 21:46 UTC
Labels: comp: core, fixed by Ivy, freq1: low, severity2: inconvenient, type: bug/fix
