### ISSUE TITLE
[directive] throw error if selector is without []

### ISSUE THREAD

**Issue by indraraj26** [angular/angular#37611] opened 2020-06-16 16:57 UTC
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/core

### Description
throw an error if directive selector is wrapped without []
`selector: appNameChange`

### Describe the solution you'd like
 If you have a solution in mind, please describe it.

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

**Comment by JoostK** [comment] 2020-06-16 17:04
It is perfectly valid for directives to target a tag name, so it is by no means required to include the brackets.

I'll close this for now but feel free to continue the discussion below.

**Closed by JoostK** 2020-06-16 17:04 UTC

**Comment by indraraj26** [comment] 2020-06-16 17:07
Directive without [] aka bracket is not throwing any error even if i placed directive name on element

**Comment by JoostK** [comment] 2020-06-16 18:34
I realize that; it's by design. The selector you specify on directives and components is very similar to a CSS selector, only a lot more constrained. The brackets specify that the directive/component should attach itself on elements which have an _attribute_ of the bracketed name. Leaving the brackets off will select elements where their _tag_ matches.

It is typical for directives to use attributes, therefore brackets, and components to match on tag names, but you can mix and match these as you like.

In your example, the element in the template simply doesn't match the directive's selector, so it won't activate. But... I'm observing a limitation of template type checking right now, where the attribute `appAppNameChange` does not trigger an error. This is tracked in #3425.
