### ISSUE TITLE
TemplateRef generic error in template with Ivy

### ISSUE THREAD

**Issue by waterplea** [angular/angular#35710] opened 2020-02-27 08:54 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/compiler

### Is this a regression?

 Yes, the previous version in which this bug was not present was 8

### Description

I have a directive that I put on `ng-template`. It has a generic for context, just like `TemplateRef`, except it extends object and has empty object (`{}`) as default type. We cannot define context that `ng-template` is expecting, I have an issue for that:
https://github.com/angular/angular/issues/28731

Previously I've seen errors or warnings in templates that said that `ng-template` with `let-something="something"` does not know what this `something` is. But they did not fail builds or anything like that. With Ivy if I write code like this:
```
<button (click)="onClick(template)">Template</button>
<ng-template #template="polymorpheus" polymorpheus let-test="test">
  I'm a template to be used with IContext context
</ng-template>
```
And in onClick handler I define generics like that:

`onClick(template: PolymorpheusTemplate<IContext>) {`

I'm getting type error `Argument of type 'PolymorpheusTemplate<{}>' is not assignable to parameter of type 'PolymorpheusTemplate<IContext>'`.

It seems to me that it is really unavoidable with current version unless I want to store it as a `@ViewChild` (which I don't) or if I remove default typing and obligate people to write `<{}>` in every case they use directive where context doesn't matter (which I also don't want). And like I said, it worked before.

## 🔬 Minimal Reproduction

 https://ng-run.com/edit/fyNwwVIEL9ct2ItyMCI8

## 🔥 Exception or Error
<pre><code>
error TS2345: Argument of type 'PolymorpheusTemplate<{}>' is not assignable to parameter of type 'PolymorpheusTemplate<IContext>'.
  Property 'test' is missing in type '{}' but required in type 'IContext'.
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>9.0.2</code></pre>

**Anything else relevant?**

Here's the code of my directive, it's just a wrapper around `TemplateRef` to trigger change detection when needed:

```
@Directive({
    selector: 'ng-template[polymorpheus]',
    exportAs: 'polymorpheus',
})
export class PolymorpheusTemplate<T extends object = {}> {
    constructor(
        @Inject(TemplateRef)
        @Self()
        readonly template: TemplateRef<T>,
        @Inject(ChangeDetectorRef) private readonly changeDetectorRef: ChangeDetectorRef,
    ) {}

    check() {
        this.changeDetectorRef.markForCheck();
    }
}
```

**Comment by alxhub** [comment] 2020-02-27 23:40
This is indeed an issue with `fullTemplateTypeCheck: true`, it would seem. It reproduces with the following:

```typescript
import {Component, Directive, NgModule} from '@angular/core';

@Directive({
  selector: 'ng-template[dir]',
  exportAs: 'dir',
})
export class Dir<T extends object = {}> {
  readonly used!: T;
}

export interface Test {
  test: string;
}

@Component({
  selector: 'test-cmp',
  template: `
    <button (click)="onClick(template)">Template</button>
    <ng-template #template="dir" dir let-test="test"></ng-template>
  `
})
export class TestCmp {
  onClick(template: Dir<Test>): void {}
}

@NgModule({
  declarations: [TestCmp, Dir],
})
export class Module {}
```

The type error itself is correct - `TestDir<{}>` is inferred for `template` because the compiler has nothing else to go on.

**Comment by alxhub** [comment] 2020-02-27 23:55
Just as an aside, if you _do_ want properly typed contexts for template directives, you can do that with Ivy. It looks something like this:

```typescript
import {Component, Input, Directive, NgModule} from '@angular/core';

@Directive({
  selector: 'ng-template[dir]',
  exportAs: 'dir',
})
export class Dir<T extends object = {}> {
  @Input() dir!: T;

  static ngTemplateContextGuard<T extends object>(dir: Dir<T>, ctx: any): ctx is DirContext<T> {
    return true;
  }
}

export interface DirContext<T> {
  test: T;
}

export interface IValue {
  name: string;
}

@Component({
  selector: 'test-cmp',
  template: \`
    <button (click)="onClick(template)">Template</button>
    <ng-template #template="dir" [dir]="value" let-test="test">
      {{test.name}}
      {{test.address}}
    </ng-template>
  \`
})
export class TestCmp {
  value: IValue = {name: 'Foo'};
  onClick(template: Dir<IValue>): void {}
}

@NgModule({
  declarations: [TestCmp, Dir],
})
export class Module {}
```

What's needed to make this work:

1) `strictTemplates: true` or at least `strictInputBindings` and maybe a couple other flags.

2) The compiler needs some way to infer the true instance type of the directive from the directive's inputs. In this case, the directive takes an input of type `T` which is provided in the template. So any usage of the directive will provide a concrete type for `T`.

This is enough to get your example working - referencing the directive now gets a type of `Dir<IValue>` rather than `Dir<{}>`, which can be correctly passed to the `click()` handler.

3) The directive needs a `static ngTemplateContextGuard(...)` which hints to the template type-checker what the type of the template context will be, given the type of the directive. In this case, we say:

```typescript
static ngTemplateContextGuard<T extends object>(dir: Dir<T>, ctx: any): ctx is DirContext<T> 
```

That is, given a directive type of `Dir<T>`, the template context will be `DirContext<T>`.

That's enough to allow the template type-checker to validate variables inside the template. For example, it knows that `name` is a valid property on `test`, but `address` is not:

```
test.ts:30:9 - error TS2339: Property 'address' does not exist on type 'IValue'.

30       {{test.address}}
           ~~~~~~~~~~~~
```

I hope this helps!

**Comment by Lonli-Lokli** [comment] 2020-09-16 08:10
@alxhub Is there any way to add such kind of guards to the components?
Eg I Have a component with {$implicit} context and in template, referenced by ngTemplateOutlet I do not have any type information for let-variables.

**Comment by alxhub** [comment] 2022-02-11 00:19
Closing as WAI - this does work with `strictTemplates`.

**Closed by alxhub** 2022-02-11 00:19 UTC
Labels: type: bug/fix, freq1: low, regression, comp: compiler, state: confirmed, triage #1, P2, compiler: template type-checking
