### ISSUE TITLE
routerLinkActive allow any query params

### ISSUE THREAD

**Issue by doorman02** [angular/angular#14246] opened 2017-02-02 10:35 UTC
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I have the the following active paths

'./path1' the link path1 should be active.
'./path1?param1=70000&param2=test2' the link path1 should be active.
'./path1/path2' the link path2 should be active.

I am using [routerLinkActiveOptions]="{ exact: true }" to distinguise between './path1' and './path1/path2' but this doesn't work with queryParams. Which is why I should probably use the queryParams variable. But since I want to allow any parameter it's strange that I have to specify all of them. 

**Expected behavior**

path1 should be active even with parameters without needing to specify all of them.

**What is the motivation / use case for changing the behavior?**
In use cases where there are many parameters and you want to make the link active for any of them it's strange that you need to specify all of them.

**Please tell us about your environment:**

Angular2 latest, chrome

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Chrome
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript

**Comment by DzmitryShylovich** [comment] 2017-02-02 10:39
Duplicate of https://github.com/angular/angular/issues/13205

**Closed** 2017-02-02 14:59 UTC
