### ISSUE TITLE
Incorrect formatting of date with datePipe in Edge/IE11

### ISSUE THREAD

**Issue by JiriBalcar** [angular/angular#12058] opened 2016-10-04 07:21 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
in Edge/IE11 the date is incorrectly formatted with datePipe

**Expected behavior**
should be formatted by input format

**Minimal reproduction of the problem with instructions**
[http://plnkr.co/edit/mmd5X3YFOyjN3JS1zzOE](http://plnkr.co/edit/mmd5X3YFOyjN3JS1zzOE)

**What is the motivation / use case for changing the behavior?**
should work as expected

**Please tell us about your environment:**
Windows 10

* **Angular version:** 2.0.X
2.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
IE 11, Edge
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

**Comment by DzmitryShylovich** [comment] 2016-10-04 07:23
Duplicate of https://github.com/angular/angular/issues/9524

**Comment by pkozlowski-opensource** [comment] 2016-10-04 08:26
Thnx @DzmitryShylovich

**Closed by pkozlowski-opensource** 2016-10-04 08:26 UTC
