### ISSUE TITLE
When changing input's value with `[value]` , cursor is being reset on Safari after each change

### ISSUE THREAD

**Issue by jtomaszewski** [angular/angular#21782] opened 2018-01-25 17:15 UTC
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When writing in a input which has value bound with `[value]="value"` and the `value` property is updated upon `(input)="value = $event.target.value"`, on Safari cursor is moved to the end of input's value after typing a new letter.

On other browsers like Chrome it works okay (the cursor stays where it was before typing the next letter).

Video: https://drive.google.com/file/d/15PdpY_vtaBPXCLmtiOJ_2zxwjY7x_vrr/view

## Expected behavior

When writing in the input, the cursor should stay in the same place.

## Minimal reproduction of the problem with instructions

https://github.com/jtomaszewski/angular-demo/tree/demo/input-component

```sh
git clone jtomaszewski/angular-demo angular-demo
cd angular-demo
git checkout demo/input-component
npm install
npm run start
```

## What is the motivation / use case for changing the behavior?

To have custom input/form components that handle input's value using only `@Input` and `@Output` interfaces.

## Environment

<pre><code>
Angular version: 5.0.4 (same bug exists on 4.0.2 as well)

Browser:
- [x] Safari (desktop) version 11.0.2

**Comment by wachri** [comment] 2018-11-07 16:22
Same problem with Angular 6.1 and Safari 12. During googling for the issue I found that the guys from bootstrap-vue had a similar issue https://github.com/bootstrap-vue/bootstrap-vue/issues/1951  but it seems to be fixed in a huge merge request.

Is there a way around or any progress on this?

**Comment by pauldraper** [comment] 2019-02-04 18:08
```typescript
import { Injectable, Provider, Renderer2, RendererType2 } from '@angular/core';
import {
  EventManager,
  ɵDomRendererFactory2 as DomRendererFactory2,
  ɵDomSharedStylesHost as DomSharedStylesHost,
} from '@angular/platform-browser';

/**
 * Fix inputs for Safari.
 * @see https://github.com/angular/angular/issues/21782
 */
function patchRenderer(renderer: Renderer2): Renderer2 {
  const setProperty = renderer.setProperty;
  renderer.setProperty = function(el: any, name: string, value: any) {
    if (name !== 'value' || el[name] !== value) {
      setProperty.apply(renderer, arguments);
    }
  };
  return renderer;
}

@Injectable()
export class DomRendererFactory extends DomRendererFactory2 {
  constructor(
    eventManager: EventManager,
    sharedStylesHost: DomSharedStylesHost,
  ) {
    super(eventManager, sharedStylesHost);
  }

  createRenderer(element: any, type: RendererType2 | null): Renderer2 {
    return patchRenderer(super.createRenderer(element, type));
  }
}

export const RENDERER_PROVIDERS: Provider[] = [
  {
    provide: DomRendererFactory2,
    useClass: DomRendererFactory,
  },
];
```

And then add `RENDERER_PROVIDERS` to your root module's providers.

This fixes both `[value]` and `[ngModel]`, works with animations, and should not interfere with server-side rendering.

**Comment by trotyl** [comment] 2019-02-06 15:54
For this case can be solved by making a directive like:

```typescript
@Directive({
  selector: 'input'
})
export class InputAccessor {
  private currentValue: string | null = null

  constructor(private elRef: ElementRef, private renderer: Renderer2) { }

  @Input() set value(value: string) {
    if (value !== this.currentValue) {
      this.renderer.setProperty(this.elRef.nativeElement, 'value', value)
    }
  }

  @HostListener('input', ['$event']) onInput(event: any) {
    this.currentValue = event.target.value
  }
}
```

Modified StackBlitz: https://stackblitz.com/edit/github-mqej5p?file=src%2Fapp%2Finput%2Finput.component.ts

And for `ngModel` there's already a concept of `ControlValueAccessor`.

**Comment by pauldraper** [comment] 2019-08-09 16:31
Very nice. Thanks @trotyl

**Comment by pkozlowski-opensource** [comment] 2020-05-08 15:12
This is still a valid issue with the latest Angular on Safari (Chrome is OK). Here is a minimal reproduce scenario: https://stackblitz.com/edit/angular-ivy-vf6h7v?file=src%2Fapp%2Fapp.component.ts

**Comment by pkozlowski-opensource** [comment] 2020-05-11 14:53
While the problem is easy to reproduce it is not clear to me why this issue happens in Safari only?
*  Is this a bug in Safari? 
* are we doing something specific in Angular (in terms of DOM manipulation) that "upsets" Safari? If so, what is the root cause?

If anyone had a deeper look into it and have some insights it would help us to prioritise this fix.

**Comment by pankajmnnit** [comment] 2021-06-24 09:33
Using [attr.value] instead of [value] fixed the problem for me.

**Comment by petebacondarwin** [comment] 2021-06-24 09:43
> Using [attr.value] instead of [value] fixed the problem for me.

Great workaround @pankajmnnit .

**Comment by pauldraper** [comment] 2021-06-24 12:06
> Using [attr.value] instead of [value] fixed the problem for me.

Only if you want to set the initial value.

> Is this a bug in Safari?

🤷 Who's to say?

> are we doing something specific in Angular (in terms of DOM manipulation) that "upsets" Safari?

Setting the `value` property of an input resets the cursor to the beginning of the line.

Angular will set the `value` property if you bind to the model, e.g. `<input [(value)]="value">`.

**Comment by pkozlowski-opensource** [comment] 2022-08-25 11:49
I've just tested on the Safari Version 15.6.1 (17613.3.9.1.16) on OsX with the [reproduce scenario](https://stackblitz.com/edit/angular-ivy-vf6h7v?file=src%2Fapp%2Fapp.component.ts) and couldn't spot the problem any more.

Sounds like it got fixed in Safari. Closing for now, happy to re-open if anyone is still bumping into it.

**Closed by pkozlowski-opensource** 2022-08-25 11:49 UTC
Labels: type: bug/fix, freq2: medium, comp: core, core: binding & interpolation, core: event listeners, browser: safari, state: needs more investigation, P3
