### ISSUE TITLE
NgIf with async pipe does not rebind child async piped observables

### ISSUE THREAD

**Issue by Guardiannw** [angular/angular#10165] opened 2016-07-19 16:19 UTC
**I'm submitting a ...**  (check one with "x")

```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Async pipe is not reattaching to dom when a parent ngif's value is dependant upon an async pipe observable.

**Expected/desired behavior**
When the ngIf switches based off the pipe observable value, the children of that ngIf should also have their piped observables mapped to the dom as is shown in the example below when binding to the [hidden] property.

**Reproduction of the problem**
http://embed.plnkr.co/JIab05WsQz3Y6qC8Oo4e/
Notice that the green band does not rebind.

**What is the expected behavior?**
That the green band would appear alongside with the blue band and have the same behavior.

**What is the motivation / use case for changing the behavior?**
implementing a modal in a Redux style architecture.

**Please tell us about your environment:**
- **Angular version:** 2.0.0-rc.4
- **Browser:** [ only tested in Chrome 51 ] 
- **Language:** [ only tested in Typescript 1.9 ]

**Comment by Guardiannw** [comment] 2016-07-19 19:26
It actually appears that this problem is not dependent upon the ngif with the async pipe.  But only the NgIf with async pipe children.
https://embed.plnkr.co/IIMdF1yimykMf94NoUgG/

**Comment by Guardiannw** [comment] 2016-07-19 19:28
Yes because this one works as expected 
https://embed.plnkr.co/hU0WEP16UqvoDOX1664l/

**Comment by adamduren** [comment] 2016-11-07 19:57
@Guardiannw Have you experienced the same behavior in later versions of angular or are you still on `rc.4`?

**Comment by soupman99** [comment] 2016-11-13 20:29
I'm experiencing this with @angular#2.1.0

**Comment by kylecordes** [comment] 2016-12-04 18:18
This problem was a bit vexing to stumble into, and I can confirm it is still present in 2.2.4.

**Comment by Dynalon** [comment] 2016-12-04 20:14
I don't think this is a bug but rather has to do with the peculiarities of `*ngIf` and RxJS cold observables in conjunction with `.interval()`.

Using `*ngIf` the inner HTML and angular template syntax is removed from the DOM and the angular expressions are only evaluated after the predicate in the `*ngIf` becomes `true`. Now, every 500ms the  `*ngIf` will become `true` and thus the angular compiler will evaluate the statement `{{ (val1 | async) }}`. The  `async` pipe will upon evaluation create a subscription to the *cold* observable. But here is the catch: `Observable.interval()` will not emit a value until **after** the first 500ms have passed. But since the subscription by the `async` pipe came in **after** the subscription to the `ifObservable` (which also flips every 500ms) - the condition in `*ngIf`  will become false before the inner subscription is trigged. The template content of the `*ngIf` is removed and the subscription to `val1` is unsubscribed before there ever was a single value emitted.

Note that `[hidden]` works completely different, as it will maintain the subscription to the observable the whole time - even when the condition becomes `false`. `*ngIf` will create a new subscription every time the condition becomes `true`.

**Comment by DzmitryShylovich** [comment] 2017-02-03 19:23
@Guardiannw can you pls add a plunkr using the latest angular?

**Comment by Guardiannw** [comment] 2017-02-14 19:26
I am not using angular anymore, I have switched to React, so I can neither confirm or deny this issue is still present.

**Comment by DzmitryShylovich** [comment] 2017-02-14 19:29
then it's not actionable and should be closed I think :)

**Comment by gizm0bill** [comment] 2017-03-30 20:34
I have the same issue with some merged subjects switchmapped to a delayed observable, on version 2.4.6. I can put up a plunkr if you want.

**Comment by DzmitryShylovich** [comment] 2017-03-30 20:48
@gizm0bill provide a plunkr and we will see :)

**Comment by gizm0bill** [comment] 2017-03-31 08:41
Amazingly, it works here: https://plnkr.co/edit/llJKk6XXHRcab2f9b5pX but not in my real app (doing actual api requests instead of that delay)

**Comment by gizm0bill** [comment] 2017-04-01 11:53
See for example here https://plnkr.co/edit/iNonywQDzVbDXX52D9h8?p=preview how it subscribes to `total` and after it gets its value  it apparently subscribes to `items` and does another request, which is not desired as is, but in my actual project it gets stuck after `total` gets value and `items` remain null...

**Comment by wiredprogrammer** [comment] 2017-08-04 20:26
I've experienced issues with this as well.  I'm using css instead of ngIf to hide the content since it isn't crucial for me to remove it from the html.  I'm making use of the if/else to show a loading template and  use observable aliases.

**Comment by gizm0bill** [comment] 2017-08-05 06:20
same

**Comment by rendmath** [comment] 2017-10-28 23:24
Same situation here, with Angular 4.2.2.

**Comment by WebDev2013** [comment] 2017-11-02 19:36
The basic problem as I see it is that the variables used in the ngIf expression are not changing withing the Angular change detection cycle. 
To make the observable emit trigger change detection, simply bring the emitted value into Angular's scope:

*ngIf="trigger"

ngOnInit() {
    this.trigger = this.ifObservable.subscribe()

**Comment by rendmath** [comment] 2017-11-05 06:06
After further investigations, we reached similar conclusions to what @Dynalon was speaking about one year ago.

In our case, the problem is related to the use of the .share() operator, because the multicasting effectively turns the sequence into a hot observable. The problem can be solved by using any RxJS operator that provides a "replay" behavior at subscription time (e.g. switching from share(), to shareReplay()).

Here is an updated version of your Plunker, with the intended behavior: https://plnkr.co/edit/ZymxIi3P7cRwepLIO3Xv.

**Comment by slawojstanislawski** [comment] 2017-11-09 14:51
Here's a stackblitz demonstrating the same thing - indeed it doesn't seem to be a bug, but as @Dynalon said - a peculiarity with RxJS and *ngIf. Using .shareReplay() helps (uncomment and then click within the app window)
https://stackblitz.com/edit/angular-r1sqjy

I encountered this when initially relying on ngrx effect observable, which emitted the number of unread messages, once a 'success' action was dispatched after that number got fetched. However, since it's a one-time event, the element with *ngIf became displayed fine, but inside it, the displayed number was null, since the inner subscription (that happended when the observable emitted) no longer had any event to receive. I could replay the emitted value, using shareReplay() but ended up rewriting the implementation to not rely on the effect observable.

**Comment by jasonaden** [comment] 2017-12-14 00:31
@slawojstanislawski is correct. This is actually behaving correctly. The problem is the subscription will be created after the fact.

I created a new `docs` issue so we can look at giving more info about this scenario on the `async` documentation. See issue #20998 for details. Feel free to add more use cases to that issue as well.

**Closed by jasonaden** 2017-12-14 00:31 UTC
Labels: comp: core & compiler, freq1: low, severity3: broken, type: bug
