### ISSUE TITLE
Error in application build in prod mode

### ISSUE THREAD

**Issue by dxvladislavvolkov** [angular/angular#33441] opened 2019-10-28 11:30 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/core@8.2.9

### Description
Devextreme-angular prepared the package with angular package format and now the package is created using ng-packagr package (You can see the package structure [here](https://github.com/ovchinnikov/devextreme-angular-build)). We found an issue with building the application when using short paths to the module, like this:

> import { DxButtonModule } from 'devextreme-angular';

We get an error:

> ERROR in Unexpected value 'DxButtonModule in C:/Users/Documents/Github/ngExample/node_modules/devextreme-angular/devextreme-angular.d.ts' imported by the module 'AppModule in C:/Users/Documents/Github/ngExample/src/app/app.module.ts'. Please add a @NgModule annotation.

When using long paths, like this

> import { DxButtonModule } from 'devextreme-angular/ui/button';

, there is no error

Also, if you use a build with dev mode, there will be no error

## 🔬 Minimal Reproduction
You can reproduce it using the [repo](https://github.com/dxvladislavvolkov/ngExample)
Following the steps:
1. npm i
2. ng build --prod
and then you get the error

## 🔥 Exception or Error
<pre><code>

ERROR in Unexpected value 'DxButtonModule in C:/Users/volkov.vladislav/Documents/Work/Github/ex/ngExample/node_modules/devextreme-angular/devextreme-angular.d.ts' imported by the module 'AppModule in C:/Users/volkov.vladislav/Documents/Work/Github/ex/ngExample/src/app/app.module.ts'. Please add a @NgModule annotation.
'dx-button' is not a known element:
1. If 'dx-button' is an Angular component, then verify that it is part of this module.
2. If 'dx-button' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("[ERROR ->]<dx-button text="Click" ></dx-button>")
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

8.2.9
</code></pre>

**Anything else relevant?**

**Comment by AndrewKushnir** [comment] 2019-10-28 17:26
Hi @dxvladislavvolkov, could you please test the app with the @next version (9.0.0-next.14) to see if the problem still exists? Thank you.

**Comment by dxvladislavvolkov** [comment] 2019-10-29 08:37
Hi @AndrewKushnir,
It works with angular@next, but we have a breaking change with ng8

**Comment by EmaGht** [comment] 2019-10-30 17:07
> 
> 
> Hi @dxvladislavvolkov, could you please test the app with the @next version (9.0.0-next.14) to see if the problem still exists? Thank you.

I'm having the same problem using angular 9.0.0-next.14 and @ngtools/webpack 9.0.0-next.18
A private library (https://www.npmjs.com/package/@esfaenza/ngx-introjs) previously built on Angular 8.1.0 gets correctly imported, while the same library, built with ivy and 9.0.0-next.14 fails with OP's error with  ERROR in Unexpected value 'IntroJsModule' imported by the module [ecc...]

**Comment by IgorMinar** [comment] 2019-11-08 23:12
hi @dxvladislavvolkov!

I can reproduce the error with core@8.2.9 but I was not able to confirm that there is a version with which this package works - is there such version?

There is quite a bit of stuff going on in that package, so it's hard to tell if it's all correct. One thing that seems a bit off is that all the module paths are absolute and not relative.

for example: https://github.com/ovchinnikov/devextreme-angular-build/blob/5b34babbf14ca8fca6b9abc666422109eca580e8/index.d.ts#L15-L48

I'd expect those to be `'./ui/..'`. Theoretically that should not make a difference, but module resolution is generally a tricky area, so being aligned with common patterns is preferable.

It would be great if you could reduce this repro further to produce a minimal package that fails with this error.

I don't think that we can treat this as a regression until we can confirm that this used to work with some older version. It would be awesome if you could provide repro/information proving that. thanks!

**Comment by ovchinnikov** [comment] 2019-11-12 13:09
Hi @IgorMinar ,

I have created a minimal package where the issue is reproduced: [https://github.com/ovchinnikov/dev-angular-build](https://github.com/ovchinnikov/dev-angular-build)

The issue occurs because of the Angular version that we use to compile our library. To support Angular 6+, we use version 6.1.10. However, if we compile DevExtreme with Angular 7.2, everything works as expected.

The issue can also be reproduced if we compile it with Angular 7.0 and 7.1. You can see the difference between two compiled versions at [https://github.com/ovchinnikov/dev-angular-build/pull/1/files](https://github.com/ovchinnikov/dev-angular-build/pull/1/files).

So, we need to remove support of Angular 6 and provide a higher Angular version so that our users can use long and short paths for importing widgets, am I right?

> I'd expect those to be './ui/..'.

This will make a difference. To support long and short paths, we've created a secondary entry point for each widget and reexport all widgets from the primary entry point. If we use relative paths, each widget will be bundled twice, in 'devextreme-angular/ui/button' and in 'devextreme-angular'.

**Comment by JoostK** [comment] 2020-03-15 16:27
I marked this as fixed by Ivy since the cause of this issue seems related to the extracted metadata, as shown in the difference between Angular 7.1 (failing) and 7.2 (where it starts working).

Your reproduction does fail for me in Angular 9.0 using ViewEngine, but it works correctly with Ivy.

@EmaGht You describe an issue with Ivy, are you still having issues? It may be a different problem/root cause as reported here. Can you open a new issue with a reproduction on your case, so we can investigate?

**Comment by EmaGht** [comment] 2020-03-16 09:37
@JoostK Time passed, libraries have been updated and things are looking good from my side aswell :)

**Comment by alxhub** [comment] 2020-05-27 18:52
Closing as resolved!

**Closed by alxhub** 2020-05-27 18:52 UTC
Labels: comp: compiler, fixed by Ivy, freq2: medium, severity3: broken, type: bug/fix
