### ISSUE TITLE
https://angular.dev/di Page not found

### ISSUE THREAD

**Issue by ZebaNazneen** [angular/angular#52824] opened 2023-11-11 18:39 UTC
### Describe the problem that you experienced

The link https://angular.dev/di on topic dependency injection is inaccessible.

### Enter the URL of the topic with the problem

https://angular.dev/di

**Comment by sasidharansd** [comment] 2023-11-11 19:02
I think the DI is inside Docs option. Docks -> Dependency Injection. 
or You can access through https://angular.dev/guide/di

**Comment by ZebaNazneen** [comment] 2023-11-11 19:09
When I try to access the 'Try out Inject' link on the roadmap page(https://angular.dev/roadmap), it redirects to https://angular.dev/di which says page not found. I was looking forward to read the inject topic.

![DI](https://github.com/angular/angular/assets/92320881/9ba4c84f-27a7-4b33-a9c5-6e51d2037231)

**Comment by JoostK** [comment] 2023-11-11 19:17
Thanks for the report, this is a duplicate of #52539.

**Closed by JoostK** 2023-11-11 19:17 UTC

**Comment by sasidharansd** [comment] 2023-11-11 19:26
Hey @ZebaNazneen , as a pr has been raised for this issue it will be fixed and docs will be updated, but if you want to access to the link now, here it is : https://angular.dev/tutorials/learn-angular/inject-based-di
