### ISSUE TITLE
@ContentChildren cannot find children whose parent has a directive like ngClass, ngStyle

### ISSUE THREAD

**Issue by chengyiuchun** [angular/angular#14769] opened 2017-02-27 16:28 UTC
(Updated to reflect discussion below)

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When `@ContentChildren` is used to get a `QueryList` of elements inside the `<ng-content></ng-content>`, it fails to find children with a directive like `[ngClass]="..."` or `[ngStyle]="..."` in their parent. Once the parent has no more directive, the problem goes away and those children are found. Using `{descendants: true}` in `@ContentChildren` seems to work around this problem.

**Expected behavior**
Those children should be found.

**Minimal reproduction of the problem with instructions**

Minimal demo: http://plnkr.co/edit/0nPxOa7t0FLDY98PFfnW?p=preview
- Please click the two buttons and check console log output
- One of them finds (the one at the `ng-content` level) 3 instances of the `SomeDirective`
- The other one finds (the one at within the `ng-content`) 9 instances of the `SomeDirective`

**What is the motivation / use case for changing the behavior?**

This is an inconsistent behavior and it causes confusion.

**Please tell us about your environment:**

Windows 8.1, IntelliJ, npm
* **Angular version:** 2.4.0

* **Browser:** tried on Chrome 56 | IE 11

 
* **Language:** all

**Comment by ericmartinezr** [comment] 2017-02-27 16:32
https://angular.io/docs/ts/latest/api/core/index/ContentChildren-decorator.html
>descendants - include only direct children or all descendants.

@ContentChildren(Type, {descendants:true})

**Comment by danielcheng825** [comment] 2017-02-27 16:38
Thanks very much @ericmartinezr. That indeed resolved the problem.
I got confused because it was able to return the other 3 without setting `descendants: true`.
Do you know what it can return the last 3 elements? Does [ngClass] make them non-direct children?

**Comment by ericmartinezr** [comment] 2017-02-27 16:46
@danielcheng825 I really don't know. At first I thought it was because of the ngFor being expanded, but then I saw that you had another ngFor working fine, so my theory was busted... so using `descendants` was a lucky guess.

I would wait for @DzmitryShylovich  (we miss you in gitter) for  an answer (in case it is by design) or a fix (in case it is a bug).

**Comment by DzmitryShylovich** [comment] 2017-02-27 17:30
it's interesting. looks like any directive on the parent element makes it invisible for `ContentChildren`. idk if it's intended or not. ping @mhevery 

@ericmartinezr 
> we miss you in gitter

no thx. my life has become much batter without it :)

**Comment by mlaval** [comment] 2017-07-31 16:18
@danielcheng825 Indeed, any directive make them non-direct children, which means they cannot be found unless `descendants: true`.
I'm not sure why it has been implemented this way, probable @tbosch or @rkirov know more

**Comment by pkozlowski-opensource** [comment] 2018-01-10 13:57
The current logic implemented in the framework for the `descendants: false` works as follows:

1.  keep traversing content elements (as seen in a template) making notes of directives (including components) on a give element;
2.  as soon as you encounter a first element with a directive set a flag (make a note that we've seen a directive) and keep descending;
3. upon encountering _another_ element with a directive / component on it, stop descending.

Queries with `descendants: true` simply don't stop at step (3) but continue to descent and matching directives until all the content nodes are visited.

The above algorithm explains why sticking _any_ directive above directives we are querying will "break" queries. I'm can totally see how this behaviour might be non-intuitive and surprising for users. We've got  `descendants: false` system in place to support nested tabset-like use-cases:

```html
<tabset>
   <tab title="Foo">
       <tabset> <-- Presence of the tabset directive here prevents top-level tabset from "seeing" nested tabs--->
            <tab title="Nested">....</tab> 
       </tabset>
   </tab>
   <tab title="Bar">
        Bar content
   </tab>
</tabset>
```

Unfortunately the current algorithm is a bit heavy-handed and will stop descending upon encountering _any_ directive for a second time.... But this is where we are and before we can come up with a different set of rules / logic, we can't easily "fix" this issue....

**Comment by pkozlowski-opensource** [comment] 2018-01-10 14:19
Here is a plunker that one can use to play with different directives and see how those are stoping descending through content nodes: http://plnkr.co/edit/qNEPHnYlvI9rLK9JjjpX?p=preview

**Comment by aciccarello** [comment] 2018-01-10 15:48
@pkozlowski-opensource In your above tabset example, wouldn't it be more accurate to say that no elements inside the `<tab title="Foo">` element are traversed because both `tabset` and `tab` are directives?

**Comment by pkozlowski-opensource** [comment] 2018-01-10 15:53
> In your above tabset example, wouldn't it be more accurate to say that no elements inside the <tab title="Foo"> element are traversed because both tabset and tab are directives?

@aciccarello not sure it would be more accurate. I don't think that we should drag `<tabset>` into it as what matters is a presence of elements _inside_ content being queried. Consider this example that would break any tabset implementation:

```html
<tabset>
   <div breakEverything>
	   <tab title="Foo">
	       Foo content
	   </tab>
	   <tab title="Bar">
	        Bar content
	   </tab>
   </div>
</tabset>
```

Here is a real-life demonstration of this in practice: http://plnkr.co/edit/82jSQEefE5LsW60w39rm?p=preview

**Comment by pkozlowski-opensource** [comment] 2018-01-10 16:29
Uhh, it seems that it is even more subtle than this - from my testing it seems like the 2-directives limitations applies per-view and not per-component template: http://plnkr.co/edit/eYbL0Ou61Udh7HFziCHK?p=preview

**Comment by pkozlowski-opensource** [comment] 2018-01-11 11:04
OK, so after trying to come up with a sensible documentation for the current behaviour @mhevery and I believe that the way things work correctly is confusing to the point that we can label it as a "bug" and propose a simpler system.

The current working proposal is to change `descendants: false` to follow the following rule: only query _direct children_ (in the sense of elements in a template) when `descendants: false` is specified. Some examples give a `@ContentChildren(Tab, {descendants: false})` from the `<tabset>` component:

```html
<tabset>
  <tab>...</tab>
  <tab>...</tab>
</tabset>
```

In the above example the query would pick up 2 `<tab>`s.

```html
<tabset>
    <div>
      <tab>...</tab>
      <tab>...</tab>
    </div>
</tabset>
```

In the above example the query would pick up 0 `<tab>`s (no tabs selected since no `<tab>` element is a direct child of `<tabset>`).

```html
<tabset>
    <div>
      <tab>...</tab>
    </div>
    <tab>...</tab>
</tabset>
```

In the above example the query would pick up 1 `<tab>`s (only the second `<tab>` element is a direct child of `<tabset>`).

The above proposal will make rules pretty clear and easy to follow. Unfortunately it will be a **breaking change**, technically speaking. But at present we believe that it is more of a bug-fix rather than change of the expected behaviour. 

However, if you've got a valid use-case that will be breaking after implementation of the above proposal, please speak up! @danielcheng825 I would love to know what is your real-life use-case for having an element with `ngClass` above the content queried for.

**Comment by pkozlowski-opensource** [comment] 2020-02-16 16:40
This is fixed in Angular v9 with ivy enabled as we've adjusted how the `descendants: false` flags works - more details in https://github.com/angular/angular/issues/14769#issuecomment-356901874

**Closed by pkozlowski-opensource** 2020-02-16 16:40 UTC
Labels: comp: core, effort2: days, fixed by Ivy, flag: breaking change, freq2: medium, severity3: broken, type: bug/fix
