### ISSUE TITLE
Can't add controls dynamically to controlarray

### ISSUE THREAD

**Issue by MaxHogervorst** [angular/angular#8634] opened 2016-05-13 07:32 UTC
I am trying to add an input dynamically to a form when someone clicks on a button.

I found this example from the offical docs:Angular2 [docs](https://angular.io/docs/ts/latest/api/common/ControlArray-class.html) & [plnker](http://plnkr.co/edit/23DESOpbNnBpBHZt1BR4?p=preview)

It is working with alpha.37 as you can see in the plunker.

I've translated it to rc1:

Component:

`import {FORM_DIRECTIVES, Location, Control, ControlGroup, ControlArray, Validators } from "@angular/common";
import {Component } from '@angular/core';

@Component({
    selector: 'my-app',
    templateUrl: 'app/partners/test.html',
    directives: [FORM_DIRECTIVES]
})

export class TestTest {
    ctrlFirst: Control = new Control('', Validators.required);
    ctrlMiddle: Control =  new Control('');
    ctrlLast: Control =  new Control('', Validators.required);
    ctrlFood: Control = new Control('pizza', Validators.required);
    ctrlCities: Control[] = [
        new Control(''),
        new Control(''),
        new Control('')
    ];
    citiesArray: ControlArray = new ControlArray(this.ctrlCities);

    formGroup: ControlGroup = new ControlGroup({
        name: new ControlGroup({
            first: this.ctrlFirst,
            middle: this.ctrlMiddle,
            last: this.ctrlLast
        }),
        food: this.ctrlFood,
        cities: this.citiesArray
    });

    get cgValue(): string {
        return JSON.stringify(this.formGroup.value, null, 2);
    }

    addCity(): void {
        this.citiesArray.push(new Control(''));
    }
}`

View:

`<div>
    <h2>Angular2 Control &amp; ControlGroup Example</h2>
    <form [ngFormModel]="formGroup">
        <div [ngControlGroup]="name">
            <h3>Enter your name:</h3>
            <p>First: <input [ngControl]="first"><span *ngIf="!ctrlFirst.valid"> [required]</span></p>
            <p>Middle: <input [ngControl]="middle"></p>
            <p>Last: <input [ngControl]="last"><span *ngIf="!ctrlLast.valid"> [required]</span> </p>
        </div>
        <h3>What's your favorite food?</h3>
        <p><input [ngControl]="food"><span *ngIf="!ctrlFood.valid"> [required]</span></p>
        <h3>Name a few cities:</h3>
        <ul [ngFormControl]="cities">
            <li *ngFor="let ctrl of ctrlCities; let i = index"><input [ngControl]="i"></li>
        </ul>
        <button type="button" (click)="addCity()">Add a city</button>

    </form>
    <h3>Value:</h3>
    <pre>{{ cgValue }}</pre>
    <h3>Validity:</h3>
    <pre>{{ formGroup.valid }}</pre>
</div>`

When i am trying to run this, i am getting the following error:

`EXCEPTION: Error in app/partners/test.html:3:13
browser_adapter.ts:78EXCEPTION: Error in app/partners/test.html:3:13BrowserDomAdapter.logError @ browser_adapter.ts:78
browser_adapter.ts:78ORIGINAL EXCEPTION: Cannot find control ''BrowserDomAdapter.logError @ browser_adapter.ts:78
browser_adapter.ts:78ORIGINAL STACKTRACE:BrowserDomAdapter.logError @ browser_adapter.ts:78
browser_adapter.ts:78Error: Cannot find control ''
    at new BaseException (exceptions.ts:14)
    at _throwError (shared.ts:61)
    at Object.setUpControlGroup (shared.ts:54)
    at NgFormModel.addControlGroup (ng_form_model.ts:76)
    at NgControlGroup.ngOnInit (ng_control_group.ts:39)
    at DebugAppView._View_TestTest0.detectChangesInternal (TestTest.template.js:418)
    at DebugAppView.AppView.detectChanges (view.ts:243)
    at DebugAppView.detectChanges (view.ts:345)
    at DebugAppView.AppView.detectViewChildrenChanges (view.ts:267)
    at DebugAppView.AppView.detectChangesInternal (view.ts:256)BrowserDomAdapter.logError @ browser_adapter.ts:78
browser_adapter.ts:78ERROR CONTEXT:BrowserDomAdapter.logError @ browser_adapter.ts:78
browser_adapter.ts:78DebugContextBrowserDomAdapter.logError @ browser_adapter.ts:78
zone.js:463 ViewWrappedException`

**Comment by MaxHogervorst** [comment] 2016-05-13 07:50
if you remove the [ngFormControl]="cities" from the <ul> element, the code will run but then i am unable to retrieve the value from the controls. I also tried replacing [ngFormControl] with [ngControl] or [ngGroupControl] which makes no difference

**Comment by zoechi** [comment] 2016-05-13 10:40
The initial post is poorly formatted and hard to read and looks like parts aren't shown at all. 

GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by pkozlowski-opensource** [comment] 2016-06-02 17:19
Closing as it is hard to understand what is going on here and we don't have a plunker with a reproduce scenario.

**Closed by pkozlowski-opensource** 2016-06-02 17:19 UTC
