### ISSUE TITLE
Using global events (eg `window:resize()`) in a component throws array.map error

### ISSUE THREAD

**Issue by ajoslin** [angular/angular#1611] opened 2015-04-30 17:59 UTC
I don't have time for a full report right now, let me know if you need more information.

**Comment by pkozlowski-opensource** [comment] 2015-05-07 12:15
@ajoslin a reproduce scenario would be awesome - there are so many changes in the repo that I'm not sure which version of Angular you've used to test...

**Comment by pkozlowski-opensource** [comment] 2015-05-07 12:51
@ajoslin I don't see it throwing in alpha.21 (http://plnkr.co/edit/Lq60xFISlTzZ7UekWy44?p=preview) - but I can't seem to make it work either...

**Comment by pkozlowski-opensource** [comment] 2015-05-07 12:54
Ah, actually it works correctly, the proper syntax to use is:

```javascript
hostListeners: {
    'window:resize': 'resize()'
  }
```

This seems to work perfectly fine in alpha.21: http://plnkr.co/edit/Lq60xFISlTzZ7UekWy44?p=preview

@ajoslin I'm going to close this one since it seems to be working fine (see the plunker). But do let me know if you still see pbs with other versions, I'm going to re-open then and look into it.

**Closed by pkozlowski-opensource** 2015-05-07 12:54 UTC
