### ISSUE TITLE
Reactive form async validation is not working as expected

### ISSUE THREAD

**Issue by popec** [angular/angular#36997] opened 2020-05-08 06:52 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/forms@9.1.5

### Is this a regression?

 Don't know.

### Description

 Async validation of Reactive Forms from docs example passes if you type:
- Eric (wait for validation), 
- Erica (wait for validation)
- Eric and hit Submit. 
![validation-pass](https://user-images.githubusercontent.com/2662895/81379022-a3143d80-9108-11ea-9216-0483fd50887a.jpg)
It works ok in Template-driven form.

## 🔬 Minimal Reproduction

 Just download example from https://angular.io/guide/form-validation and play with it.

## 🌍  Your Environment
**Angular Version:**
<pre><code>

Angular CLI: 9.1.4
Node: 12.13.0
OS: win32 x64

Angular: 9.1.5
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router, upgrade
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.4
@angular-devkit/build-angular     0.901.4
@angular-devkit/build-optimizer   0.901.4
@angular-devkit/build-webpack     0.901.4
@angular-devkit/core              9.1.4
@angular-devkit/schematics        9.1.4
@angular/cli                      9.1.4
@ngtools/webpack                  9.1.4
@schematics/angular               9.1.4
@schematics/update                0.901.4
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0

</code></pre>

**Anything else relevant?**

**Comment by AndrewKushnir** [comment] 2020-05-19 01:03
Hi @popec, thanks for reporting the issue. Could you please also provide a minimal repro using [Stackblitz](https://stackblitz.com/), so we can better understand your report? Thank you.

**Comment by popec** [comment] 2020-05-21 09:17
https://stackblitz.com/edit/angular-ivy-yby1dg

**Comment by AndrewKushnir** [comment] 2020-05-26 21:30
Hi @popec, thanks for creating a repro. I tried to follow your instructions, but was unable to submit the form in "invalid" state. Could you please let me know if there are some additional steps I need to take to reproduce the issue? Thank you.

**Comment by g-zwolinski** [comment] 2020-05-27 07:28
@AndrewKushnir try click submit without leaving "Alter Ego" field. Then you can see that there was no validation before submit. Check attached gif
![asyncvalidationissue](https://user-images.githubusercontent.com/9096111/82990405-6eefb680-9ffc-11ea-97d3-e03e7bb84aec.gif)

**Comment by AndrewKushnir** [comment] 2020-05-30 22:17
Thanks for additional information. It looks like this is a bug, seems related/duplicate of #10064 (there is an open PR #22575 to resolve that). I will keep this ticket open since it contains up-to-date repro. Thank you.

**Comment by AndrewKushnir** [comment] 2020-07-13 20:27
Hi, the changes in PR #10064 were merged and will be available in Angular v10.1.0 (which should be available on NPM in a few weeks). I'm closing this ticket for now. Feel free to reopen if the problem still exists after upgrading the v10.1.0 once it's released. Thank you.

**Closed by AndrewKushnir** 2020-07-13 20:27 UTC
Labels: comp: forms, forms: validators, state: confirmed, triage #1, type: bug/fix
