### ISSUE TITLE
Angular 2 and Browser support tests

### ISSUE THREAD

**Issue by goriunov** [angular/angular#12478] opened 2016-10-24 08:01 UTC
Just curious , why angular 2 browser support result are not passed , for IE 9 and android . Are there some reasons and is it  going to be fixed soon?

**Comment by pkozlowski-opensource** [comment] 2016-10-24 08:08
This sounds like a temporary problem with SauceLabs. I've restarted https://travis-ci.org/angular/angular/jobs/169642601

**Comment by mlaval** [comment] 2016-10-25 13:44
In fact, there are some issues since #12346 was merged. IE9 keeps disconnecting in SauceLabs. It also happens sporadically in other browsers such as Android 4.4.

From these symptoms, it looks similar to issues that we had in the past and that were solved with #11072 and #11083. Not sure what is the cause here ...

/cc @tbosch

**Comment by goriunov** [comment] 2016-10-27 08:15
Is there any news, when it is going to be fix ?

**Comment by matsko** [comment] 2017-01-05 21:39
It's been quite some time since anything new came up here. I'm going to close the issue for now.

**Closed by matsko** 2017-01-05 21:39 UTC
