### ISSUE TITLE
Angular2: OnChanges in parent is not being executed on emit from child component

### ISSUE THREAD

**Issue by andrzejpiasecki** [angular/angular#7925] opened 2016-04-06 07:16 UTC
Minimal example of the problem:
- App component that uses ContenteditableModel component which allows to edit bonded property and emit changes to parent component via two-way data binding - [()]
- ContenteditableModel is able to change App.text property
- App.OnChanges should be executed.

http://plnkr.co/edit/teURR9?p=preview

Problem is that OnChanges hook is not executed in the App component , although value {{text}} is changing properly.

My app setup:
    "angular2": "2.0.0-beta.13",
    "es6-promise": "^3.1.2",
    "es6-shim": "^0.35.0",
    "reflect-metadata": "0.1.2",
    "rxjs": "5.0.0-beta.2",
    "systemjs": "0.19.22",
    "zone.js": "^0.6.6"

**Comment by zoechi** [comment] 2016-04-06 07:21
`ngOnChanges()` is only called when `@Input()`s are changed (from parent to child).
You might change `test` to a getter/setter` to be able to execute code when `text` is changed.

**Comment by juristr** [comment] 2016-04-06 21:18
> `ngOnChanges()` is only called when @Input()s are changed (from parent to child).

@zoechi Ya, that's totally comprehensible. But I'm experiencing a scenario where `ngOnChanges` only gets fired if the `@Input()`s value is **reference changed** meaning, if u mutate it's inner structure the event won't be fired (the binding works properly with default ChangeDetectionStrategy, though). Here's an example: https://plnkr.co/edit/hCKn9V1L8rzDPYzGc5HW?p=preview

Not sure whether I'm just missing something here or whether this is an intended behavior.

**Comment by juristr** [comment] 2016-04-06 21:22
@zoechi nevermind. Found it: #6458 😉

**Comment by pkozlowski-opensource** [comment] 2016-06-02 12:39
Duplicate of #6458

**Closed by pkozlowski-opensource** 2016-06-02 12:39 UTC
