### ISSUE TITLE
Having a div tag inside a p tag breaks compilator

### ISSUE THREAD

**Issue by jooleeanh** [angular/angular#39762] opened 2020-11-19 14:40 UTC
# 🐞 bug report

### Affected Package

N/A

### Is this a regression?

N/A

### Description

Same issue as presented in #7572 and #6648.
However these issues did not mention that the compilator stays broken after the template has been corrected.

## 🔬 Minimal Reproduction
(Could not reproduce on Stackblitz)
1) Create project via terminal `ng new div-in-p` (build options don't matter)
2) Launch server `ng serve`
3) open app.component.html, put this and save
```
<p>this works, as expected</p>
```
4) Put this and save
```
<p><div>this doesn't work, as expected</div></p>
```
5) Put this and save
```
<p>this is rendered on the server, so it "works" as expected, but the serving terminal starts/continues to show error(s)</p>
```

## 🔥 Exception or Error
<pre><code>
Date: 2020-11-19T14:35:38.536Z - Hash: 43b052a66fd45ce522a9
4 unchanged chunks
chunk {main} main.js, main.js.map (main) 8.55 kB [initial] [rendered]
Time: 321ms
    
    ERROR in src/app/app.module.ts:8:5 - error NG6001: The class 'AppComponent' is listed in the declarations of the NgModule 'AppModule', but is not a directive, a component, or a pipe. Either remove it from the NgModule's declarations, or add an appropriate Angular decorator.
    
    8     AppComponent
          ~~~~~~~~~~~~
    
      src/app/app.component.ts:8:14
        8 export class AppComponent {
                       ~~~~~~~~~~~~
        'AppComponent' is declared here.
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 10.2.0
Node: 12.16.1
OS: win32 x64

Angular: 10.2.3
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1002.0
@angular-devkit/build-angular   0.1002.0
@angular-devkit/core            10.2.0
@angular-devkit/schematics      10.2.0
@angular/cli                    10.2.0
@schematics/angular             10.2.0
@schematics/update              0.1002.0
rxjs                            6.6.3
typescript                      4.0.5
</code></pre>

**Anything else relevant?**

**Comment by JoostK** [comment] 2020-11-19 14:50
Thanks for reporting! This is a duplicate of #39147, where an invalid template causes an incorrect rebuild. If all is well you should be able to trigger one more refresh for the errors to be resolve. Please follow #39147 for updates.

**Closed by JoostK** 2020-11-19 14:50 UTC
