### ISSUE TITLE
@angular/core has an undeclared dependency on @angular/compiler

### ISSUE THREAD

**Issue by pauldraper** [angular/angular#45427] opened 2022-03-24 07:31 UTC
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

@angular/core (specifically testing module) has a dependency on @angular/compiler, but it is not listed in package.json

Depending on the package linking process, this can make the testing module fail.

https://github.com/angular/angular/blob/cd2d82a91a5f547ae4c3d369f7f777245324c9e5/packages/core/testing/src/r3_test_bed_compiler.ts#L9

**Comment by JoostK** [comment] 2022-05-27 12:18
Closing as duplicate of #38096.

**Closed by JoostK** 2022-05-27 12:18 UTC
Labels: comp: core
