### ISSUE TITLE
Hybrid app angular 4 running in angular 1.3 is having performance issue because of ngAnimate

### ISSUE THREAD

**Issue by chinra02** [angular/angular#17536] opened 2017-06-15 14:12 UTC
![animation_1](https://user-images.githubusercontent.com/18039197/27185458-ff8c4544-51aa-11e7-9c39-168ee55e3920.jpg)
![animation_2](https://user-images.githubusercontent.com/18039197/27185467-030695b2-51ab-11e7-979d-05ea5f82be6b.jpg)

I am working on an app where most of the modules are in angular 1.3 and the new modules is on angular 4. So we are using downgrade strategy  while bootstrapping. It worked fine with angular2 , Recently we have upgraded the system to angular 4  and noticed performance degrade and with debugging found that ngAnimate module in angular 1 side is causing the app tremendous performance down. If we remove the ngAnimate module it's super fast.

attaching the performance stack from chrome browser.

## I'm submitting a ...

<pre><code>
[X ] Regression (behavior that used to work and stopped working in a new release)
[ ] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
I am working on an app where most of the modules are in angular 1.3 and the new modules is on angular 4. So we are using downgrade strategy  while bootstrapping. It worked fine with angular2 , Recently we have upgraded the system to angular 4  and noticed performance degrade and with debugging found that ngAnimate module in angular 1 side is causing the app tremendous performance down. If we remove the ngAnimate module it's super fast.

## Minimal reproduction of the problem with instructions
bootstrap angular 1 with anugalr 4 with downgrade strategy

## Please tell us about your environment

<pre><code>
Angular version: 4.0.3

Browser:
- [X ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 6.6
- Platform: Windows
- Build: Angular webpack 2

Others:

</code></pre>

**Comment by matsko** [comment] 2017-12-07 23:49
Hey @chinra02 sorry it took so long for me to get to this issue.

@petebacondarwin @gkalpak can you guys look at this? This doesn't relate to animations in Angular (only AngularJS).

**Comment by gkalpak** [comment] 2017-12-08 10:41
It seems like something in `ngAnimate` (probably `requestAnimationFrame`) triggers an async operation that is captured by `ngZone`, which in turn triggers CD in Angular, which then triggers CD in AngularJS. But it is hard to identify what this is and how to best avoid the issue without an actual reproduction.

##
Off the top of my head, you could work around it by decorating `$$rAf` (which provides the `requestAnimationFrame` function to `ngAnimate`) so that it calls `requestAnimationFrame` outside the Angular zone. (This is a bit of a hack, because `$$rAF` is private, but should be the simplest solution.)

Another solution (that would improve the overall performance of the hybrid app) would be to use ngUpgradeLite, which runs AngularJS outside the zone, but this might not be a drop-in replacement for what you have now. See [this presentation][1] for more info on `ngUpgradeLite` and #18487 for some docs.

##
Happy to look into this more if I can get my hands on an actual, live (preferrably unminified and minimal) reproduction.

[1]: https://www.youtube.com/watch?v=kWKiY8CWzbs

**Comment by gkalpak** [comment] 2017-12-15 17:48
@LPCmedia, it would look like this (in a simplified form):

```js
myAngularModule.
  factory('ngZone', downgradeInjectable(NgZone)).
  decorator('$$rAF', ($delegate, ngZone) => cb => ngZone.runOutsideAngular(() => $delegate(cb)));
```

See also [this demo][1] (comment the ecorator out to see tht there is an extra digest per `requestAnimationFrame`).

##
Another solution might be making `requestAnimationFrame` Zone-unaware globally (which will affect Angular as well), as described [here][2]

##
Just to be clear, this might or might not help in your case, since it is still not clear what is causing the issue.

[1]: http://plnkr.co/edit/uoRe5REoeP8XSIXoRupD?p=preview
[2]: https://gist.github.com/JiaLiPassion/45664f6a28c8b522fca30c841610c6b4#file-zone-blacklist-js-L17

**Comment by gkalpak** [comment] 2017-12-15 17:49
I am going to close this, since it is not actionable in its current state. As mentioned above, happy to look more into it if you can provide a reproduction.

**Closed by gkalpak** 2017-12-15 17:49 UTC
Labels: comp: upgrade/dynamic, comp: upgrade/static, freq1: low, type: bug

**Comment by iyhammad** [comment] 2018-08-28 13:58
Hi,
I'm facing the exact same issue mentioned in this issue.
My Environment:
```
"angular": "1.7.3",
"angular-animate": "1.7.3",
"angular-material": "1.1.10",
"@angular/animations": "6.1.4",
"@angular/core": "6.1.4",
```

If i tried to add the comment in https://github.com/angular/angular/issues/17536#issuecomment-352068798 I got the below issue
```
ERROR Error: Uncaught (in promise): TypeError: $$rAF.throttle is not a function
TypeError: $$rAF.throttle is not a function
    at new MdGesture (angular-material.js:3149)
    at MdGestureProvider.$get (angular-material.js:2927)
    at Object.invoke (angular.js:5121)
    at angular.js:4910
    at getService (angular.js:5064)
    at injectionArgs (angular.js:5089)
    at Object.invoke (angular.js:5113)
    at angular.js:4920
    at forEach (angular.js:387)
    at createInjector (angular.js:4920)
    at new MdGesture (angular-material.js:3149)
    at MdGestureProvider.$get (angular-material.js:2927)
    at Object.invoke (angular.js:5121)
    at angular.js:4910
    at getService (angular.js:5064)
    at injectionArgs (angular.js:5089)
    at Object.invoke (angular.js:5113)
    at angular.js:4920
    at forEach (angular.js:387)
    at createInjector (angular.js:4920)
    at resolvePromise (zone.js:814)
    at resolvePromise (zone.js:771)
    at zone.js:873
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:421)
    at Object.onInvokeTask (core.js:3815)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:420)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:188)
    at drainMicroTaskQueue (zone.js:595)
```
Any way to resolve this issue.
