### ISSUE TITLE
Transforming value on attribute binding with pipe syntax

### ISSUE THREAD

**Issue by slywyrm** [angular/angular#22957] opened 2018-03-23 13:24 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I want to transform values that I bind to attributes, or two-way bind to ngModel. So no I do something like this:
```HTML
<input type="number" name="test" [ngModel]="test / 1000" (ngModelChange)="test = $event * 1000">
```

## Expected behavior

What would i would like to do, is to use pipe syntax in such situations, something like:
```HTML
<input type="number" name="test" [(ngModel)]="test | appKilo">
```

which would desugar to something like this:
```HTML
<input type="number" name="test [ngModel]="KiloPipe.transform(kilo)" (ngModelChange)="test = KiloPipe.transformBack($event)">
```

```TypeScript
@Pipe({
   selector: 'appKilo'
})
export class KiloPipe implements PipeTransform, PipeTransformBack {
  transform(value: number): number {
    return value && value / 1000;
  }

  transformBack(value: number): number {
    return value && value * 1000;
  }
}
```

## What is the motivation / use case for changing the behavior?

this could adjust binding code to be a lot less verbose and not only in template-driven forms but also in attribute binding 

## Environment

<pre><code>
Angular version: 5.2.0

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by dawidgarus** [comment] 2018-03-24 09:32
Aurelia has something like that: http://aurelia.io/docs/binding/value-converters#globally-accessible-value-converters
I think it can be done with simple syntax sugar: `| pipe = value` to be `= value | pipeReverse`

**Comment by Toxicable** [comment] 2018-03-24 09:43
duplicate of https://github.com/angular/angular/issues/3009

**Comment by dawidgarus** [comment] 2018-03-24 09:51
@Toxicable I don't think that's a duplicate. Parsers and formatters are for forms, pipes can be used in any binding. For example `<input type="number" name="test" [(ngModel)]="test | appKilo">`
and somewhere else: `You've entered {{test | appKilo}}kg`
You can't do that with parsers and formatters bacause that's not what they are meant for.

**Comment by slywyrm** [comment] 2018-03-24 10:16
@Toxicable Yep, I just think, that using existing pipe mechanics for this feature would be cool and relatively easy to implement (i may be terminally wrong on this opinion)

**Comment by vicb** [comment] 2018-03-29 23:10
No plan to implement such a thing currently.

**Closed by vicb** 2018-03-29 23:10 UTC
Labels: comp: common

**Comment by abdullah2993** [comment] 2019-06-05 21:29
> 
> 
> No plan to implement such a thing currently.

Any plans now?
