### ISSUE TITLE
'export default' compile error while executing 'ng build -- prod'

### ISSUE THREAD

**Issue by timoodada** [angular/angular#34773] opened 2020-01-14 08:49 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

No

### Description

When `ng serve` is executed, the program runs normally;
Error occured after `ng build --prod`
Brower console error: `ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'name' of null`

i find that error occured in this file: 
`node_modules/@angular/platform-browser/fesm2015/animations.js`
I try to add `console.log` to verify this error in this file:
<pre>
<code>
console.log(animationTriggers); // line 294  
</code>
</pre>
to my surprise,`ng serve` and `ng build --prod` show me different results:

`ng serve`
![image](https://user-images.githubusercontent.com/25240445/72326726-aebb9e80-36ea-11ea-8ca8-3c9d20210ea3.png)

`ng build --prod`
![image](https://user-images.githubusercontent.com/25240445/72327169-8bddba00-36eb-11ea-9c7f-e7e88113c863.png)

i think some errors happened while 'fadeAnimation' was loaded.
finally i changed `export default trigger('fadeAnimation', [/* ... */])` to
`export const fadeAnimation = trigger('fadeAnimation', [/* ... */])`
the problem is solved!!!  I just changed my writing style.
but i don't why,and I spent a lot of time solving this problem.

## 🔥 Exception or Error
<pre><code>
ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'name' of null
TypeError: Cannot read property 'name' of null
    at main-es2015.ce94efef1860561d76c3.js:1
    at Array.forEach (<anonymous>)
    at yr.createRenderer (main-es2015.ce94efef1860561d76c3.js:1)
    at Object.Pa [as createComponentView] (main-es2015.ce94efef1860561d76c3.js:1)
    at Ma (main-es2015.ce94efef1860561d76c3.js:1)
    at Ha (main-es2015.ce94efef1860561d76c3.js:1)
    at Ua (main-es2015.ce94efef1860561d76c3.js:1)
    at Ma (main-es2015.ce94efef1860561d76c3.js:1)
    at Oa (main-es2015.ce94efef1860561d76c3.js:1)
    at Object.$a [as createRootView] (main-es2015.ce94efef1860561d76c3.js:1)
    at O (polyfills-es2015.3fce1dbbdc44ed5be028.js:1)
    at O (polyfills-es2015.3fce1dbbdc44ed5be028.js:1)
    at polyfills-es2015.3fce1dbbdc44ed5be028.js:1
    at s.invokeTask (polyfills-es2015.3fce1dbbdc44ed5be028.js:1)
    at Object.onInvokeTask (main-es2015.ce94efef1860561d76c3.js:1)
    at s.invokeTask (polyfills-es2015.3fce1dbbdc44ed5be028.js:1)
    at o.runTask (polyfills-es2015.3fce1dbbdc44ed5be028.js:1)
    at g (polyfills-es2015.3fce1dbbdc44ed5be028.js:1)
</code></pre>

## 🌍 Your Environment
<pre><code>
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "module": "esnext",
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "es2015",
    "typeRoots": [
      "node_modules/@types",
      "src/app/images.d.ts"
    ],
    "lib": [
      "es2018",
      "dom"
    ]
  },
  "angularCompilerOptions": {
    "fullTemplateTypeCheck": true,
    "strictInjectionParameters": true
  }
}

"dependencies": {
    "@angular/animations": "~8.2.14",
    "@angular/common": "~8.2.14",
    "@angular/compiler": "~8.2.14",
    "@angular/core": "~8.2.14",
    "@angular/forms": "~8.2.14",
    "@angular/platform-browser": "~8.2.14",
    "@angular/platform-browser-dynamic": "~8.2.14",
    "@angular/router": "~8.2.14",
    "better-scroll": "^1.15.2",
    "classlist.js": "^1.1.20150312",
    "fastclick": "^1.0.6",
    "immutable": "^4.0.0-rc.12",
    "lyric-parser": "^1.0.1",
    "redux": "^4.0.4",
    "redux-immutable": "^4.0.0",
    "rxjs": "~6.4.0",
    "tslib": "^1.10.0",
    "vanilla-lazyload": "^12.4.0",
    "web-animations-js": "^2.3.2",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.803.19",
    "@angular/cli": "~8.3.19",
    "@angular/compiler-cli": "~8.2.14",
    "@angular/language-service": "~8.2.14",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "^5.0.0",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.5.3"
  }
</code></pre>

**Anything else relevant?**

**Comment by Naxirdan** [comment] 2020-01-14 14:22
Hi @timoodada ,
Sometimes I have encountered this problem and it was mostly because the compiler checks for access to one of the levels of the uninitialized object, that is, if the compiler finds:

`newArray = [];` can't access to `newArray.name`

But if we have the variable or model defined like  `newArray = [{name: '', surname: ''}]` compiler or engine can access to `newArray.name`

If don't work like that, please tell me more or give an example an I will try to reproduce

**Comment by alxhub** [comment] 2020-01-14 23:10
Hello @timoodada,

Unfortunately without a reproduction, we have very little chance of investigating and fixing this issue. Please provide a Github repo with a minimal reproduction along with instructions, which clearly illustrate the problem.

**Comment by timoodada** [comment] 2020-01-15 02:50
> Hello @timoodada,
> 
> Unfortunately without a reproduction, we have very little chance of investigating and fixing this issue. Please provide a Github repo with a minimal reproduction along with instructions, which clearly illustrate the problem.

here is [a simple exmple](https://github.com/timoodada/angular-error-test)

**Comment by Naxirdan** [comment] 2020-01-15 08:03
Hi @timoodada ,

I think the error shown by the compiler is normal, since you are mixing a lexical statement such as const or let with a reserved word that in this case is default. In order for this to work correctly, to reach a better understanding I leave you two links.

[http://www.ecma-international.org/ecma-262/6.0/#sec-let-and-const-declarations](url)
[http://www.ecma-international.org/ecma-262/6.0/#sec-exports-static-semantics-boundnames](url)

In my case I have executed the code of your example as follows:
app.component.ts =>
```
import { Component } from '@angular/core';
import {fadeAnimation} from './fade.animate';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
  animations: [
    fadeAnimation
  ]
})
export class AppComponent {
  visible = true;
  toggleFade = () => {
    this.visible = !this.visible;
  }
}
```
fade.component.ts =>
```
import {trigger, transition, animate, style} from '@angular/animations';

/*
* run `ng serve`, everything is ok;
* run `ng build --prod`, browser goes error;
* change `export default` to `export const fadeAnimation = ...`, both `ng serve` and `ng build --prod` are ok.
* */
export const fadeAnimation =  trigger('fadeAnimation', [
  transition(':leave', [
    style({ opacity: 1 }),
    animate('0.3s ease', style({ opacity: 0 }))
  ]),
  transition(':enter', [
    style({ opacity: 0 }),
    animate('0.3s ease', style({ opacity: 1 }))
  ])
]);
```

**Comment by timoodada** [comment] 2020-01-15 08:21
> Hi @timoodada ,
> 
> I think the error shown by the compiler is normal, since you are mixing a lexical statement such as const or let with a reserved word that in this case is default. In order for this to work correctly, to reach a better understanding I leave you two links.
> 
> [http://www.ecma-international.org/ecma-262/6.0/#sec-let-and-const-declarations](url)
> [http://www.ecma-international.org/ecma-262/6.0/#sec-exports-static-semantics-boundnames](url)
> 
> If toy want to use const you need to add a Identifier and **don't** use default.
> 
> In my case I have executed the code of your example as follows:
> app.component.ts =>
> 
> ```
> import { Component } from '@angular/core';
> import {fadeAnimation} from './fade.animate';
> 
> @Component({
>   selector: 'app-root',
>   templateUrl: './app.component.html',
>   styleUrls: ['./app.component.scss'],
>   animations: [
>     fadeAnimation
>   ]
> })
> export class AppComponent {
>   visible = true;
>   toggleFade = () => {
>     this.visible = !this.visible;
>   }
> }
> ```
> 
> fade.component.ts =>
> 
> ```
> import {trigger, transition, animate, style} from '@angular/animations';
> 
> /*
> * run `ng serve`, everything is ok;
> * run `ng build --prod`, browser goes error;
> * change `export default` to `export const fadeAnimation = ...`, both `ng serve` and `ng build --prod` are ok.
> * */
> export const fadeAnimation =  trigger('fadeAnimation', [
>   transition(':leave', [
>     style({ opacity: 1 }),
>     animate('0.3s ease', style({ opacity: 0 }))
>   ]),
>   transition(':enter', [
>     style({ opacity: 0 }),
>     animate('0.3s ease', style({ opacity: 1 }))
>   ])
> ]);
> ```

I wonder why the result of `ng serve` is inconsistent with `ng build -- prod`;
The problem only occurs in ` ng build -- prod` so it's hard for me to find the reason.

**Comment by Naxirdan** [comment] 2020-01-15 08:28
I have the same result, compiled successful with ng serve and with ng build --prod

**Comment by Naxirdan** [comment] 2020-01-15 08:29
> > Hi @timoodada ,
> > I think the error shown by the compiler is normal, since you are mixing a lexical statement such as const or let with a reserved word that in this case is default. In order for this to work correctly, to reach a better understanding I leave you two links.
> > [http://www.ecma-international.org/ecma-262/6.0/#sec-let-and-const-declarations](url)
> > [http://www.ecma-international.org/ecma-262/6.0/#sec-exports-static-semantics-boundnames](url)
> > If toy want to use const you need to add a Identifier and **don't** use default.
> > In my case I have executed the code of your example as follows:
> > app.component.ts =>
> > ```
> > import { Component } from '@angular/core';
> > import {fadeAnimation} from './fade.animate';
> > 
> > @Component({
> >   selector: 'app-root',
> >   templateUrl: './app.component.html',
> >   styleUrls: ['./app.component.scss'],
> >   animations: [
> >     fadeAnimation
> >   ]
> > })
> > export class AppComponent {
> >   visible = true;
> >   toggleFade = () => {
> >     this.visible = !this.visible;
> >   }
> > }
> > ```
> > 
> > 
> > fade.component.ts =>
> > ```
> > import {trigger, transition, animate, style} from '@angular/animations';
> > 
> > /*
> > * run `ng serve`, everything is ok;
> > * run `ng build --prod`, browser goes error;
> > * change `export default` to `export const fadeAnimation = ...`, both `ng serve` and `ng build --prod` are ok.
> > * */
> > export const fadeAnimation =  trigger('fadeAnimation', [
> >   transition(':leave', [
> >     style({ opacity: 1 }),
> >     animate('0.3s ease', style({ opacity: 0 }))
> >   ]),
> >   transition(':enter', [
> >     style({ opacity: 0 }),
> >     animate('0.3s ease', style({ opacity: 1 }))
> >   ])
> > ]);
> > ```
> 
> I wonder why the result of `ng serve` is inconsistent with `ng build -- prod`;
> The problem only occurs in ` ng build -- prod` so it's hard for me to find the reason.

I have the same result, compiled successful with ng serve and with ng build --prod

**Comment by timoodada** [comment] 2020-01-15 08:36
> ng build --prod

Successful compilation does not mean it can work in browser

**Comment by Naxirdan** [comment] 2020-01-15 09:03
> > ng build --prod
> 
> Successful compilation does not mean it can work in browser

It's true but if I change this one:
```
export const fadeAnimation =  trigger('fadeAnimation', [
  transition(':leave', [
    style({ opacity: 1 }),
    animate('0.3s ease', style({ opacity: 0 }))
  ]),
  transition(':enter', [
    style({ opacity: 0 }),
    animate('0.3s ease', style({ opacity: 1 }))
  ])
]);
```
to 10s ease to leave:
```
export const fadeAnimation =  trigger('fadeAnimation', [
  transition(':leave', [
    style({ opacity: 1 }),
    animate('10s ease', style({ opacity: 0 }))
  ]),
  transition(':enter', [
    style({ opacity: 0 }),
    animate('0.3s ease', style({ opacity: 1 }))
  ])
]);
```
I can see the effect 10 seconds not 0.3s or immediately

**Comment by timoodada** [comment] 2020-01-15 09:12
> > > ng build --prod
> > 
> > 
> > Successful compilation does not mean it can work in browser
> 
> It's true but if I change this one:
> 
> ```
> export const fadeAnimation =  trigger('fadeAnimation', [
>   transition(':leave', [
>     style({ opacity: 1 }),
>     animate('0.3s ease', style({ opacity: 0 }))
>   ]),
>   transition(':enter', [
>     style({ opacity: 0 }),
>     animate('0.3s ease', style({ opacity: 1 }))
>   ])
> ]);
> ```
> 
> to 10s ease to leave:
> 
> ```
> export const fadeAnimation =  trigger('fadeAnimation', [
>   transition(':leave', [
>     style({ opacity: 1 }),
>     animate('10s ease', style({ opacity: 0 }))
>   ]),
>   transition(':enter', [
>     style({ opacity: 0 }),
>     animate('0.3s ease', style({ opacity: 1 }))
>   ])
> ]);
> ```
> 
> I can see the effect 10 seconds not 0.3s or immediately

please change `export const fadeAnimation =  trigger('fadeAnimation', [{* *}])` to `export default  trigger('fadeAnimation', [{* *}])` and try it again.
the latter option can work in `ng serve` but cause error in `ng build --prod`(in browser).
That's why I gived this issue.

**Comment by mlc-mlapis** [comment] 2020-01-15 09:22
@timoodada Generally, JIT mode means that many things happen directly in a browser (using the written code), but AOT mode means that Angular compiler completely transcodes the source code with all defined rules. So the code that is run in a browser is a different code.

**Comment by timoodada** [comment] 2020-01-15 09:35
> @timoodada Generally, JIT mode means that many things happen directly in a browser (using the written code), but AOT mode means that Angular compiler completely transcodes the source code with all defined rules. So the code that is run in a browser is a different code.

I think you are right, but how can I avoid such a problem? Because it's hard to find out the reason after 'ng build -- prod'

**Comment by mlc-mlapis** [comment] 2020-01-15 10:12
@timoodada The most of the rules are described directly on https://angulra.io pages, specifically:
* https://angular.io/guide/aot-compiler
* https://angular.io/guide/angular-compiler-options
* https://angular.io/guide/aot-metadata-errors

**Comment by JoostK** [comment] 2020-03-15 15:39
There was no support for default exports in the ViewEngine compiler, but this is no longer the case in Ivy (Angular 9). As such, this issue has been fixed in latest Angular!

**Closed by JoostK** 2020-03-15 15:39 UTC
Labels: comp: compiler, freq2: medium, severity2: inconvenient, state: Needs repro, type: bug/fix
