### ISSUE TITLE
Proposal - use initial empty value for async pipe as undefined rather than null

### ISSUE THREAD

**Issue by dmitrysteblyuk** [angular/angular#16982] opened 2017-05-24 05:45 UTC
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Currently async pipe returns null before an observable emits the first value.

**Expected behavior**
It should return undefined.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**
Null values unlike undefined values can be returned by a server in json (with a meaning like the data is not available or not set). Thus, using null values in async pipe before request completed leads to misunderstanding as to where this null data come from - is it initial empty value of async pipe, or has it come from server.

If the initial empty value for async pipe were undefined, then it would allow to use checks like this in a template:

```
<div *ngIf="(data$ | async) === undefined">Loading...</div>
<div *ngIf="(data$ | async) === null">No data</div>
<div *ngIf="(data$ | async) != null">{{ (data$ | async) }}</div>
```

**Please tell us about your environment:**

* **Angular version:** 4.1.3

* **Browser:** all

 
* **Language:** TypeScript 2.3.0

* **Node (for AoT issues):** `node --version` =

**Comment by k-vekos** [comment] 2018-03-05 20:09
Is this changed yet?

**Comment by 8ytan** [comment] 2018-06-19 10:22
This isn't really ideal behaviour in my opinion. For one thing, you're using the async pipe multiple times which means multiple subscriptions when you only want one. You can use templates and ngIf-Else statements to achieve something similar but with only one `| async`:

`<div *ngIf="(data$ | async) as data; else loadingTemplate">
<div *ngIf="data.length > 0; else noDataTemplate">{{data}}</div>
<ng-template #noDataTemplate>No data.</ng-template>
</div>
<ng-template #loadingTemplate>Loading...</ng-template>`

I'd also recommend avoiding just having your observable return null when it has no data, instead try returning an empty array or perhaps a flag 'NO_DATA' etc. since it aids with these kinds of checks, and makes it clear that the empty response is intended and not a bug. 

If you aren't controlling the data source then you can work around it using defaultIfEmpty or map:
`data$.let(defaultIfEmpty('NO_DATA'))`
`data$.let(map(r => !!r ? r : 'NO_DATA'))`

**Comment by jaufgang** [comment] 2018-08-29 16:44
Using `defaultIsEmpty` does not solve the problem if the observable is a long-lived observable which may emit an initial null value and later emit a non-null value.   An example could be a data stream coming in from a web socket or a Firestore Document.   

I have come up with a hacky work-around to this problem by using  `startWith(undefined)`

```js
this.data$ = dataService.getData$(params).pipe(
    startWith(undefined),
    shareReplay(1)
)
```

will give a `data$` observable that works the way @dmitrysteblyuk would like, and the call to `shareReplay` makes the observable hot and causes  the multiple subscriptions to be shared.  

Note that this hack can cause problems, since it changes the data stream emitted by the observable.  For example, it changes the value you receive if you then call `data$.pipe(first())`  to `undefined` rather than the first (null or not-null) value emitted by the observable.   But if you are just using this in the context of a component and take care, it can be used effectively to solve the problem that @dmitrysteblyuk describes.  


Anyhow, I agree that it is wrong for the async pipe to return `null` when a value has yet to be emitted from the observable and it should be `undefined`.  This is a perfect example of the value of having `null` and `undefined` in JS, despite the common confusion between the two.  `undefined` means a value has not been assigned to a variable, while null is a specific value that can be assigned to the variable.  In the case where an Observable has not emitted a value yet, it is wrong to return a value of `null` when unwrapping it with the async pipe.   

The proposed solution would remove the need for a hack like I suggested and makes proper use of `null` and `undefined`, unlike the current implementation.

**Comment by jaufgang** [comment] 2018-08-29 18:34
Also, I would say this issue was mischaracterized by the original poster as a feature request rather than a bug report, and subsequently mislabelled `type: feature` by @vicb rather than  `type: bug/fix`.  Perhaps  that is why it has been sitting around for 15 months without being addressed.   

It may be a subtle bug that does not affect many people, but the fact that the async pipe returns  a value of `null` when a `null` value has not actually been emitted by the observable is simply incorrect behaviour and should be corrected.

@vicb, please consider re-labelling this as `type: bug/fix`

**Comment by AbakumovAlexandr** [comment] 2018-09-28 17:00
@jaufgang is absolutely correct that this is the _bug_. This is incorrect to return `null` as a value in case when the actual value is unknown at the moment.

Suppose you have a component with an `@Input` property called `prop1`. When it's used in a template but  is not bound to a value, you'll get `undefined` as its value. That's why you should declare `prop1` as follows to enable the TS compiler to prevent you from accessing `prop1` value without checking it for `undefined` first:
```
`@Input()`
 public prop1: number | undefined;

// Somewhere in the component
if (this.prop1 !== undefined) {
    const str: string = this.prop1.toString();
}
```
This works perfectly fine for the cases when `prop1` is bound without `async`:
```
// In some template
<cmp1 [prop1]="expr">
```
However. guess what will happen if it's bound with using `async` :
```
// In some template
<cmp1 [prop1]="expr | async">
```
Your app will fail due to this bug, since you and the compiler believe that `if (this.prop1 !== undefined)` check is sufficient. But, apparently, it's NOT when used with the `async` pipe!!!

**Comment by Lx** [comment] 2018-10-24 08:47
Not wanting to be one of those annoying “me too” groupies, but I'd like to further the other assertions on this issue that it's a **bug** and not a feature request, in the hope that it'll be prioritised a little higher.

**Comment by AbakumovAlexandr** [comment] 2018-10-24 15:07
@vicb Could you consider changing the issue type to `bug` (see my previous [post](https://github.com/angular/angular/issues/16982#issuecomment-425500920), for example)?

@dmitrysteblyuk Could you consider changing the issue title and text to something like:

> (bug, core\compiler): Use initial empty value for async pipe as undefined rather than null

to clealy reflect that it's more a bug\API inconsistency than a feature and request Angular team to change the `type` from `feature` to `bug` from your side?
Maybe we'd have a better chance of getting attention to it with those changes.

**Comment by jaufgang** [comment] 2018-10-24 16:45
This is an important issue pertaining to a core angular feature that doesn't seem to be getting the attention it deserves.  @IgorMinar or @mhevery, maybe either of you could weigh in on this?

**Comment by VishalMadhvani** [comment] 2019-01-10 17:34
just wasted time wondering where a null came from... [free bump]

**Comment by fraser-lowndes** [comment] 2019-01-22 16:54
This is also affecting me: I pipe an observable into a child component, which should receive a value of `undefined` until the observable emits (from a HTTP call), at which point it can receive `null` (from a 404 response) or an object. Thank you @jaufgang for the write up and workaround. Your thoughts echo mine; This is the exact reason ES has both `undefined` and `null`. Sad to see that this has not received any attention from the Angular team so far, despite (at time of writing) 34 people agreeing with the OP.

**Comment by Odonno** [comment] 2019-03-26 22:31
Well, hopefully I found this thread today because I have never seen anything in the documentation about an `async` pipe that publish a `null` or `undefined` value by default... And that's what caused me a 4 hours loss in my life to understand that and so to hack the code (mixing some ngIf and recreating multiple observables for a simple task).

Well, my point is that why the hell is there a default value? I mean, if developers really want to start with a default value in order to display anything in their components, why not let them use the `startWith` operator?

So, you will make everyone happy with those who prefer `undefined` (the main scenario), those who prefer to wait until the first value is emit or those who prefer a different starting value.

**Comment by Odonno** [comment] 2019-10-07 19:02
Yes, that's a really good question. And that could obvisouly lead to serious breaking changes. I have some ideas about that: 

1. Make the `*ngIf` condition mandatory if the Observable is not initialized at the start of the component, meaning has no `startWith` or is not a `BehaviorSubject`.
2. In that case where the Observable has no value, either throw an error (no value provided for the template of the component) or hide the component until it can be displayed (at least one value on each Observable, like a CombineLatest)

Of course, for the current state of angular, it is difficult to change the behavior but I believe it can be fixed in Angular Ivy with what Mike Ryan proposed with Reactive Components (https://www.youtube.com/watch?v=rz-rcaGXhGk).

**Comment by GrimaceOfDespair** [comment] 2019-10-12 05:50
> I have never seen anything in the documentation about an `async` pipe that publish a `null` or `undefined` value by default... And that's what caused me a 4 hours loss in my life to understand that

Add half an hour from mine, only because I was able to find your reaction here :smile: So thanks for that!

And I agree on the suggested behavior change, but yeah, what about breaking changes?

An option could be another keyword, e.g. `asink` :stuck_out_tongue:

**Comment by digoburigo** [comment] 2019-11-14 20:34
I found the same situation in my case and I solved it as follows (this applies to my purpose only and may not serve to the problem presented here), but i want share my solution that may help others

using latest version of angular (8.2.14)

```
// parent.component.ts
<app-project-title [defaultProject]="defaultProject$ | async"></app-project-title>
```
```
// project-title.component.ts
<div *ngIf="defaultProject !== undefined; else loading">
   <ng-container *ngIf="defaultProject !== null; else noProject">
      {{ defaultProject?.name }}
   </ng-container>
   <ng-template #noProject>
      <small>No project</small>
    </ng-template>
</div>
<ng-template #loading>
  <small>Loading ...</small>
</ng-template>

 @Input() defaultProject: any;
```

**Comment by cakeinpanic** [comment] 2019-12-09 10:23
Still reproduced in angular 8.2.3
This is definitely a bug, killed two hours on debugging it, and this _proposal_ is the only place in the internet where it is discussed. Nothing in documentation, nothing anywhere 😡
Thank you, guys, for workaround ideas

**Comment by sgibson53** [comment] 2020-01-10 13:01
Just lost three hours to figuring this out! Why is this not even mentioned in the docs?? Thank you all for the thread.

**Comment by simeyla** [comment] 2020-02-21 18:38
This issue will probably see some more activity with Angular 9 where the signature of the [async pipe](https://github.com/angular/angular/blob/master/packages/common/src/pipes/async_pipe.ts) is now as follows:

    transform<T>(obj: null): null;
    transform<T>(obj: undefined): undefined;
    transform<T>(obj: Observable<T>|null|undefined): T|null;
    transform<T>(obj: Promise<T>|null|undefined): T|null;
    transform(obj: Observable<any>|Promise<any>|null|undefined): any {

So even if you use `startsWith()` the value will always be null. This is because it's impossible in RxJS to distinguish between a 'synchronous' observable (such as `of(123)`) where the value is always available, and an asynchronous one - such as the return value of an HTTP call.

The 'problem' is that now with [advanced type checking](https://angular.io/guide/template-typecheck) you'll get a lot more template errors where everything was working just fine with Angular 8.

The `strictNullInputTypes` [option](https://angular.io/guide/template-typecheck) can help if you have a lot of `@Input` properties that cannot handle a null value, but that's hiding the real problem.

You can usually add `!` or `||` to your expression if you know it will always have a value (such as ngrx store data) but another solution I'm liking for certain cases is a `defaultValue` pipe.

import { Pipe, PipeTransform } from '@angular/core';

```
@Pipe({
    name: 'default'
})
export class DefaultValuePipe implements PipeTransform {

    constructor() {}

    transform<T>(value: T | null | undefined, defaultValue: T): T {
        return value ?? defaultValue;
    }
}
```

This can be used like this, and can help a lot with code readability in certain cases:

     <div [style.width.em]="(itemCount$ | async | default: 1) * 30">

     I have {{ (cats$ | async | default: []).length }} cats!

Plus it's type safe :-)

**Comment by remye06** [comment] 2020-03-23 17:23
> I agree with you. My guess though is that they made it this way because else what would happen to this ? `Hello {{ (user | async)?.name }}` ?

It's supposed to work the same and, I tested, it does. That would have been an explanation otherwise indeed !

**Comment by emircanerkul** [comment] 2020-05-19 07:24
> > I agree with you. My guess though is that they made it this way because else what would happen to this ? `Hello {{ (user | async)?.name }}` ?
> 
> It's supposed to work the same and, I tested, it does. That would have been an explanation otherwise indeed !

This works! But should i use this annoying ? character for all async variable? especially when we use HttpClient? Are there any way to solving this within service file?

**Comment by Marabyte** [comment] 2020-07-21 09:46
> This works! But should i use this annoying ? character for all async variable? especially when we use HttpClient? Are there any way to solving this within service file?
@emircanerkul The [optional chaining operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) is a standard JS feature so it's safe to use.
I managed to avoid using an extra check on the template by moving most of the HTTP calls logic to a resolver but this approach may not fit all use cases.

**Comment by steg0139** [comment] 2020-08-12 13:53
Is there any update on this? It seems like transforms for observables and promises should return T | undefined instead of null.

**Comment by Maximaximum** [comment] 2020-09-08 15:54
Another reasonable option would be to allow `AsyncPipe` to accept an optional `defaultValue` argument. If a `defaultValue` argument has been passed, it should be used instead of `null`. Otherwise, `null` should be used in order not to introduce any breaking changes.

**Comment by mhevery** [comment] 2020-09-08 16:17
We use `null` for historical reasons, agree that `undefined` is better, but making such a change would probably be breaking, so we would need to do investigation to see if it would be worth the trouble.

Adding additional parameter to pipe for missing value, seems like a good idea and should be backwards compatible.

Suggestion to community:
- [ ] Create a PR to change `null` to `undefined` so we can test how breaking it is.
- [ ] Create a separate PR to add optional default parameter to `async` pipe.

**Comment by Odonno** [comment] 2020-09-08 16:18
Seems like the @ngrx team has developed a `ngrxLet` directive that works for every use case. https://ngrx.io/guide/component/let

**Comment by Totati** [comment] 2020-09-08 17:58
> Another reasonable option would be to allow `AsyncPipe` to accept an optional `defaultValue` argument. If a `defaultValue` argument has been passed, it should be used instead of `null`. Otherwise, `null` should be used in order not to introduce any breaking changes.

How about an injectionToken, so it can be provided?

**Comment by Lonli-Lokli** [comment] 2020-12-25 13:29
Why this initial value is emitted at all as the first one? Why it can't wait until real value arrives?

**Comment by amakhrov** [comment] 2021-01-27 22:37
> Why it can't wait until real value arrives?

how would that work though?

**Comment by Lonli-Lokli** [comment] 2021-01-28 03:56
@amakhrov you know, just as with any observable - until first value available no next method should be called . No value - no template

**Comment by seanwu1105** [comment] 2021-01-28 04:05
@Lonli-Lokli "_no template_" means structural directive not pipe. I think an Angular pipe cannot change the structure of the template. If a non-built-in solution is okay to you, [`ngrxLet` directive](https://ngrx.io/guide/component/let) might be a good choice.

**Comment by Lonli-Lokli** [comment] 2021-01-28 04:30
@seanwu1105 there is another topic on GitHub regarding this kind of pipes https://github.com/angular/angular/issues/15280

That's separate issue.

**Comment by AndrewKushnir** [comment] 2021-01-28 23:41
Closing this PR based on https://github.com/angular/angular/issues/16982#issuecomment-688987110 and also an investigation performed as a part of https://github.com/angular/angular/pull/39785. This update will require a breaking change with non-trivial migration (both for apps inside and outside of Google's codebase), so the benefits of making the change don't justify the migration cost.

**Closed by AndrewKushnir** 2021-01-28 23:41 UTC
Labels: comp: common, feature, hotlist: community-help
