### ISSUE TITLE
Nested routes breaks font-awesome icons

### ISSUE THREAD

**Issue by Bloodcast69** [angular/angular#23451] opened 2018-04-19 11:45 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ X ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

After upgrading to Angular 6-rc.5, Font Awesome icons aren't working while using nested routes. 

For example if on page: localhost:4200/test I've got some FA icons, they're working fine. 
But if I'll open page localhost:4200/nested/test2, my FA icons aren't working. 

This behavior occurs only in Firefox. On Chrome it works just fine.

Please note, that on Angular 5 there wasn't problem with icons.
## Expected behavior

Using FA icons with nested routes in Firefox without any problems

## Minimal reproduction of the problem with instructions

1. Create fresh Angular 6 app,
2. npm install font-awesome --save,
3. Create two components, one with nested route and second with flat route,
4. Put into them few Font Awesome icons,
5. Check those routes in Firefox.
## Environment

<pre><code>
Angular CLI: 6.0.0-rc.5
Node: 9.10.1
OS: linux x64
Angular: 6.0.0-rc.5
... animations, cli, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.5.7
@angular-devkit/build-angular     0.5.7
@angular-devkit/build-optimizer   0.5.7
@angular-devkit/core              0.5.7
@angular-devkit/schematics        0.5.7
@ngtools/json-schema              1.1.0
@ngtools/webpack                  6.0.0-rc.5
@schematics/angular               0.5.7
@schematics/update                0.5.7
rxjs                              6.0.0-uncanny-rc.7
typescript                        2.7.2
webpack                           4.5.0

Others:
Font Awesome: 4.7.1
</code></pre>

My routes configuration:
```
const routes: Route[] = [
{path: 'test', component: TestComponent},
{path: 'nested', children: [
    {path: 'test2', component: Test2Component}
]}
];
```
**NOTE:** Problem exists only on dev. On production serve or  ng serve --prod it works fine.
**NOTE2:** Here's link to reproduction repository: https://github.com/Bloodcast69/icons-test . Just npm install and ng serve.

**Comment by dawidadach** [comment] 2018-04-19 12:42
Having the same issue, I was about to create a new ticket when I saw your message. Not sure why @trotyl  and @ericmartinezr  are downvoting since this seems like an issue with Angular 6. It's working fine with the previous version.

**Comment by jotatoledo** [comment] 2018-04-19 13:11
It would be nice IMO if you could add a github repo with the reproduction of your issue

**Comment by trotyl** [comment] 2018-04-19 13:34
@Bloodcast69 Did you forget to push your commits?

![image](https://user-images.githubusercontent.com/6059170/38994605-6ed06e2e-4419-11e8-82c9-f65316e69b93.png)

**Comment by Bloodcast69** [comment] 2018-04-19 13:37
@trotyl 
https://screenshots.firefox.com/tZGzuwSLJltDb9JO/github.com

**Comment by trotyl** [comment] 2018-04-19 14:08
Duplicate of https://github.com/angular/angular-cli/issues/10378, not an Angular issue.

**Closed** 2018-04-20 02:46 UTC
