### ISSUE TITLE
DatePipe.transform() produces an incorrect string in IE

### ISSUE THREAD

**Issue by valdemarrolfsen** [angular/angular#12790] opened 2016-11-10 16:37 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
DatePipe.transform() produces an incorrect string in IE. Instead of getting the correct, formatted string, you get the correct formatted string followed by the whole date.

**Expected behavior**
DatePipe.transform() should return the same result as in other browsers.

**Minimal reproduction of the problem with instructions**
See Plunker example:

http://plnkr.co/edit/bNfFJW3VN9eiEwlfDzqH?p=preview

**What is the motivation / use case for changing the behavior?**

With the current behavior it is impossible to get the correct, formatted string when using DatePipe inside a component.

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 IE11

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
typescript@2.0.2

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment] 2016-11-10 16:44
Duplicate of https://github.com/angular/angular/issues/9524 and all other Intl related bugs

**Closed** 2016-11-10 16:56 UTC
Labels: comp: common
