### ISSUE TITLE
i18n: Adding HTML tags in target translation doesn't work anymore in v6

### ISSUE THREAD

**Issue by colorpump** [angular/angular#25242] opened 2018-08-01 10:06 UTC
## I'm submitting a...
<pre><code>
[X] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

In Angular 6, HTML Tags in xliff tranlation file (\<target>) are not rendered as HTML any more.

The only way is to place these tags inside the translated part, before generating the xliff file and than re-using the generated tags (e.g. `<source><x id="START_LINK" ctype="x-a" equiv-text="&lt;a&gt;"/>` in translation. This is sometimes bad as the translated language needs tags which aren't there in the source (e.g. In Spanish there is a good link which fits to the topic, but not in English).

## Expected behavior

There should be a way to give translaters the option to put links, line breaks, or bold text in their translation (\<target>), even though there aren't these tags in the original HTML content (\<source>).

### How it works (but not always desired)

```html
<p i18n="@@my-text">
  Hello
  <strong>world!</strong>
</p>
```

```sh
ng xi18n --outputPath ./locale
```

Output file (messages.xlf):
```xml
 <trans-unit id="my-text" datatype="html">
    <source>
        Today's
        <x id="START_TAG_STRONG" ctype="x-strong" equiv-text="&lt;strong&gt;"/>
            NEWS
        <x id="CLOSE_TAG_STRONG" ctype="x-strong" equiv-text="&lt;/strong&gt;"/>
    </source>
</trans-unit>
```

Translation file (messages.de.xlf)
```xml
 <trans-unit id="my-text" datatype="html">
    <source>
        Today's
        <x id="START_TAG_STRONG" ctype="x-strong" equiv-text="&lt;strong&gt;"/>
            NEWS
        <x id="CLOSE_TAG_STRONG" ctype="x-strong" equiv-text="&lt;/strong&gt;"/>
    </source>
    <target>
        <x id="START_TAG_STRONG" ctype="x-strong" equiv-text="&lt;strong&gt;"/>
            Nachrichten
        <x id="CLOSE_TAG_STRONG" ctype="x-strong" equiv-text="&lt;/strong&gt;"/>
        von heute
    </target>
</trans-unit>
```

### Let's try to add \<br> only in german translation

Let's assume we want to add a line break only in German tranlation, as it's a longer text. So we leave the html untouched.

**In Angular 5** I was able to import the xlif file in the translation tool (lokalise.co), add `<br>` into German Translation.
When exporting, the `<br>` got escaped in messages.de.xlf like `&lt;br&gt;` but Angular 5 rendered it as a line break anyway.
**In Angular 6** it shows the escaped `<br>` as simple text.

**Attempt 1**

I unescape in messages.de.xlf `&lt;br&gt;` to `<br>`.

ng server error `ERROR in xliff parse errors: Unexpected tag`

**Attempt 2**

I use `<x ctype="x-br" equiv-text="&lt;br&gt;"/>`

ng server error `ERROR in xliff parse errors: <x> misses the "id" attribute`

**Attempt 3**

I use `<x id="SOME_RANDOM_ID" ctype="x-br" equiv-text="&lt;br&gt;"/>`

ng server error `ERROR in Unknown placeholder`

## What is the motivation / use case for changing the behavior?

As mentioned before: I would like to have the option to use HTML in certain languages which are not in the source HTML to mark something, add links etc. 

## Environment

<pre><code>
Angular CLI: 6.1.0
Node: 9.8.0
OS: win32 x64
Angular: 6.1.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/build-angular     0.6.8
@angular/cli                      6.1.0
rxjs                              6.2.2
typescript                        2.7.2
</code></pre>

**Comment by trotyl** [comment] 2018-08-01 10:52
See https://github.com/angular/angular/pull/23053, it's a bug fix landed in both v5 and v6. (Not escaping them is a BUG)

**Comment by vicb** [comment] 2018-08-01 22:42
As @trotyl mentioned this is the intended behavior.

**Closed by vicb** 2018-08-01 22:42 UTC
Labels: comp: i18n, severity5: regression

**Comment by charlieongithub** [comment] 2018-09-05 15:02
@vicb First of all thank you for clarification.

I had the same problem, and did some research, before I found this thread. I found that there are some integration tests in the @angular/compiler project, which seem to cover the ```<b></b>``` case, not sure, but I think its related to this topic.

Anyway there are the direct links: https://github.com/angular/angular/blob/4fe369e188da2f1844fe1868958178e68b0c2048/packages/compiler/test/i18n/integration_xliff2_spec.ts#L101 
https://github.com/angular/angular/blob/4fe369e188da2f1844fe1868958178e68b0c2048/packages/compiler/test/i18n/integration_common.ts#L54

Would you be able to tell, whether adding support for XLIFF tags (like mentioned by the OP in "attempts" section) is planned in the future for the angular i18n module?
