### ISSUE TITLE
service-worker: The FetchEvent for "URL" resulted in a network error response: the promise was rejected (net::ERR_FAILED)

### ISSUE THREAD

**Issue by p3t3r5** [angular/angular#43106] opened 2021-08-10 19:11 UTC
### Which @angular/* package(s) are the source of the bug?

service-worker

### Is this a regression?

Yes

### Description

After Update to last 11.2.14 a month ago we have problems on Chrome (Firefox not reproducible). Some page reload ends with "Webpage is not reachable" and opens after 1-2 seconds.  Some backend/data request ends with net::ERR_FAILED. Wie have to day last Angular 12.2.0, but this problem is still present. This isue is reproducible on Angular homepage to: https://angular.io/guide/service-worker-devops

May be this caused by our **Google Crome Profile on Networkdrive**.  Firefox Profile is on networkdrive to, but this error is not present. We have other trubles with IndexedDB and Serviceworker from time to time, but this is new and annoying. Its is possible to configurate serviceworker timeout for index.html? Its Angular or Chrome isue?

We use ngsw-bypass for all backend requests as workaround.

### Please provide the exception or error you saw

```true
**Console**
The FetchEvent for "https://angular.io/guide/service-worker-devops" resulted in a network error response: the promise was rejected.
Promise.then (async)
onFetch @ ngsw-worker.js:2123
(anonymous) @ ngsw-worker.js:2058
ngsw-worker.js:1 Uncaught (in promise) DOMException: Unexpected internal error.

**Network**
service-worker-devops	GET	(failed) net::ERR_FAILED
```

### Please provide the environment you discovered this bug in

```true
Google Chrome Version 92.0.4515.107 (Offizieller Build) (64-Bit)
```

**Comment by gkalpak** [comment] 2021-08-17 18:31
It is impossible to tell what the problem might be based on the (limited) provided info (and without a reproduction) 😞
The `DOMException: Unexpected internal error` error usually implies something is failing in the interaction of the SW with the browser, but again it is impossible to tell what it might be or how your Chrome profile could be affecting it without debugging the problem.

However, the fact that it works on Firefox hints on this not being an Angular-specific issue.

##
I am going to close this issue, since there is not much we can do without a reproduction, but feel free to continue the discussion below.

Maybe you could try to debug this locally and share more info on what exactly fails (for example, stepping through the SW code with the debugger). BTW, [this page][1] has some useful info on debugging the Angular SW.

[1]: https://angular.io/guide/service-worker-devops#debugging-the-angular-service-worker

**Closed by gkalpak** 2021-08-17 18:31 UTC
Labels: comp: service-worker
