### ISSUE TITLE
Feature request: creating template variable contexts

### ISSUE THREAD

**Issue by willgm** [angular/angular#12813] opened 2016-11-11 16:51 UTC
Would be nice to have a core directive to create generic variable contexts at the template.

Example of implementation:
https://gist.github.com/willgm/ffe653a49f36997881575df2e93979bc

This has some benefits like:

- Shortcuts for long data structures and/or constant use of pipes:

```html
<ul *context="let user on my?.long?.data?.structure?.with?.user | json">
  <li>{{user.name}}</li>
  <li>{{user.age}}</li>
  <li>{{user.email}}</li>
</ul>
```

- Avoid multiple observer subscriptions at the same template:

```html
<ul *context="let user on user$ | async">
  <li>{{user.name}}</li>
  <li>{{user.age}}</li>
  <li>{{user.email}}</li>
</ul>
```

**Comment by DzmitryShylovich** [comment] 2016-11-11 16:54
Duplicate of https://github.com/angular/angular/issues/12237

**Closed** 2016-11-11 22:09 UTC
