### ISSUE TITLE
Can't resolve './app.module.ngfactory'

### ISSUE THREAD

**Issue by vksgautam1** [angular/angular#20292] opened 2017-11-09 09:02 UTC
it was working fine but after updating to 5.0.0 from angular 4.4.4 .it is giving issue.if i get back back to 4.4.4 it is working fine
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

'''
Error: ./src/app/main.ts
Module not found: Error: Can't resolve './app.module.ngfactory' in 'E:\Working Project\test\PiderWeb\src\app'
resolve './app.module.ngfactory' in 'E:\Working Project\test\PiderWeb\src\app'
  using description file: E:\Working Project\test\PiderWeb\package.json (relative path: ./src/app)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: E:\Working Project\test\PiderWeb\package.json (relative path: ./src/app)
    using description file: E:\Working Project\test\PiderWeb\package.json (relative path: ./src/app/app.module.ngfactory)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        E:\Working Project\test\PiderWeb\src\app\app.module.ngfactory doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        E:\Working Project\test\PiderWeb\src\app\app.module.ngfactory.ts doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        E:\Working Project\test\PiderWeb\src\app\app.module.ngfactory.js doesn't exist
      .json
        Field 'browser' doesn't contain a valid alias configuration
        E:\Working Project\test\PiderWeb\src\app\app.module.ngfactory.json doesn't exist
      as directory
        E:\Working Project\test\PiderWeb\src\app\app.module.ngfactory doesn't exist
[E:\Working Project\test\PiderWeb\src\app\app.module.ngfactory]
[E:\Working Project\test\PiderWeb\src\app\app.module.ngfactory.ts]
[E:\Working Project\test\PiderWeb\src\app\app.module.ngfactory.js]
[E:\Working Project\test\PiderWeb\src\app\app.module.ngfactory.json]
[E:\Working Project\test\PiderWeb\src\app\app.module.ngfactory]
 @ ./src/app/main.ts 2:0-60
    at new BuildError (E:\Working Project\test\PiderWeb\node_modules\@ionic\app-scripts\dist\util\errors.js:16:28)
    at callback (E:\Working Project\test\PiderWeb\node_modules\@ionic\app-scripts\dist\webpack.js:121:28)
    at emitRecords.err (E:\Working Project\test\PiderWeb\node_modules\webpack\lib\Compiler.js:269:13)
    at Compiler.emitRecords (E:\Working Project\test\PiderWeb\node_modules\webpack\lib\Compiler.js:375:38)
    at emitAssets.err (E:\Working Project\test\PiderWeb\node_modules\webpack\lib\Compiler.js:262:10)
    at applyPluginsAsyncSeries1.err (E:\Working Project\test\PiderWeb\node_modules\webpack\lib\Compiler.js:368:12)
    at next (E:\Working Project\test\PiderWeb\node_modules\tapable\lib\Tapable.js:218:11)
    at Compiler.compiler.plugin (E:\Working Project\test\PiderWeb\node_modules\webpack\lib\performance\SizeLimitsPlugin.js:99:4)
    at Compiler.applyPluginsAsyncSeries1 (E:\Working Project\test\PiderWeb\node_modules\tapable\lib\Tapable.js:222:13)
    at Compiler.afterEmit (E:\Working Project\test\PiderWeb\node_modules\webpack\lib\Compiler.js:365:9)
'''

## Expected behavior

work smoothly. with angular 4.4.4 it is working fine

## Environment

<pre><code>
cli packages: (E:\Working Project\test\PiderWeb\node_modules)

    @ionic/cli-utils  : 1.17.0
    ionic (Ionic CLI) : 3.17.0

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.1.0
    Cordova Platforms  : android 6.2.3
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 25.2.5
    Node              : v8.9.0
    npm               : 5.5.1
    OS                : Windows 10
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by alexzuza** [comment] 2017-11-09 09:14
Hello! Please add minimal reproduction otherwise this issue will be closed

**Comment by jasonaden** [comment] 2017-11-09 18:15
I'm sorry but reported issues require a plunker or other reproduction of the problem.

If this issue persists, please create a plunker using this template (or a github repo) and describe the difference between the expected and current behavior and create a new issue: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue

**Comment by Toriath** [comment] 2017-11-09 18:21
Even though this was just closed I'll mention that I am currently facing the same issue. The versions match.

Problem occurred trying to build the default app created in this guide for iOS: https://github.com/angular/angularfire2/blob/master/docs/ionic/cli.md

**Comment by mburger81** [comment] 2017-11-10 01:01
There is an open issue on ionic for that 
https://github.com/ionic-team/ionic/issues/13356

**Comment by lincolnthree** [comment] 2017-11-13 22:17
Also facing this issue.

```
Error: ./src/app/main.ts
Module not found: Error: Can't resolve './app.module.ngfactory' in '/Users/lb3/projects/maritlabs/marit-mtg-ionic-web/src/app'
resolve './app.module.ngfactory' in '/Users/lb3/projects/maritlabs/marit-mtg-ionic-web/src/app'
  using description file: /Users/lb3/projects/maritlabs/marit-mtg-ionic-web/package.json (relative path: ./src/app)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /Users/lb3/projects/maritlabs/marit-mtg-ionic-web/package.json (relative path: ./src/app)
    using description file: /Users/lb3/projects/maritlabs/marit-mtg-ionic-web/package.json (relative path: ./src/app/app.module.ngfactory)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /Users/lb3/projects/maritlabs/marit-mtg-ionic-web/src/app/app.module.ngfactory doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        /Users/lb3/projects/maritlabs/marit-mtg-ionic-web/src/app/app.module.ngfactory.ts doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /Users/lb3/projects/maritlabs/marit-mtg-ionic-web/src/app/app.module.ngfactory.js doesn't exist
      .json
        Field 'browser' doesn't contain a valid alias configuration
        /Users/lb3/projects/maritlabs/marit-mtg-ionic-web/src/app/app.module.ngfactory.json doesn't exist
      as directory
        /Users/lb3/projects/maritlabs/marit-mtg-ionic-web/src/app/app.module.ngfactory doesn't exist
[/Users/lb3/projects/maritlabs/marit-mtg-ionic-web/src/app/app.module.ngfactory]
[/Users/lb3/projects/maritlabs/marit-mtg-ionic-web/src/app/app.module.ngfactory.ts]
[/Users/lb3/projects/maritlabs/marit-mtg-ionic-web/src/app/app.module.ngfactory.js]
[/Users/lb3/projects/maritlabs/marit-mtg-ionic-web/src/app/app.module.ngfactory.json]
[/Users/lb3/projects/maritlabs/marit-mtg-ionic-web/src/app/app.module.ngfactory]
 @ ./src/app/main.ts 2:0-60
    at new BuildError (/Users/lb3/projects/maritlabs/marit-mtg-ionic-web/node_modules/@ionic/app-scripts/dist/util/errors.js:16:28)
    at callback (/Users/lb3/projects/maritlabs/marit-mtg-ionic-web/node_modules/@ionic/app-scripts/dist/webpack.js:121:28)
    at emitRecords.err (/Users/lb3/projects/maritlabs/marit-mtg-ionic-web/node_modules/webpack/lib/Compiler.js:269:13)
    at Compiler.emitRecords (/Users/lb3/projects/maritlabs/marit-mtg-ionic-web/node_modules/webpack/lib/Compiler.js:375:38)
    at emitAssets.err (/Users/lb3/projects/maritlabs/marit-mtg-ionic-web/node_modules/webpack/lib/Compiler.js:262:10)
    at applyPluginsAsyncSeries1.err (/Users/lb3/projects/maritlabs/marit-mtg-ionic-web/node_modules/webpack/lib/Compiler.js:368:12)
    at next (/Users/lb3/projects/maritlabs/marit-mtg-ionic-web/node_modules/tapable/lib/Tapable.js:218:11)
    at Compiler.compiler.plugin (/Users/lb3/projects/maritlabs/marit-mtg-ionic-web/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:99:4)
    at Compiler.applyPluginsAsyncSeries1 (/Users/lb3/projects/maritlabs/marit-mtg-ionic-web/node_modules/tapable/lib/Tapable.js:222:13)
    at Compiler.afterEmit (/Users/lb3/projects/maritlabs/marit-mtg-ionic-web/node_modules/webpack/lib/Compiler.js:365:9)

```

**Comment by mburger81** [comment] 2017-11-13 22:22
See this issue https://github.com/ionic-team/ionic-app-scripts/issues/1309#event-1339466985 and upgrade to ionic app-scripts 3.1.2

**Comment by jasonaden** [comment] 2017-11-14 00:54
@vksgautam1 or @lincolnthree We are looking into this issue along with the folks at Ionic. But we can't reproduce the problem. If you're able to come up with a way to reproduce that's not an error, that would be great.

**Comment by himanshukk81** [comment] 2017-11-22 10:21
I have face the same issue i have resolve it by removing module.ts from pages folder in ionic which is created repeatly through ionic g command.  and it was conflict b/w app.module.ts and module.ts in pages folder

I hope it will solve your issue

**Comment by awallat** [comment] 2017-12-08 11:10
I also have the same issue, but I'm not using ionic here, only angular and my components. After a lot of try and error I seem to have found out the problem ... at least for me.
When I created a component, but did not declare it in any module, then I get this error when I run 

> ng build --aot

Without the `--aot` option everything runs fine. When I exclude the file from compilation in `tsconfig.app.json` then the aot-build also works again. It seems that we have to be careful about not used components in our sources.

**Comment by sqwk** [comment] 2017-12-08 11:16
I also had the same issue but solved it by checking my imports:

    import { Component } from '@angular/core';

It turns out that Visual Code adds imports like this when you haven't typed out the import statement manually before:

    import { Component } from '@angular/core/src/metadata/directives';

While this works for JIT build, it will throw off the AOT compiler.

**Comment by Andrey-Pavlov** [comment] 2017-12-08 13:16
Error: ./src/app/main.ts
Module not found: Error: Can't resolve './app.module.ngfactory'
The same issue here. How to check why AOT compilation fails? How to see details?

**Comment by mlc-mlapis** [comment] 2017-12-08 14:31
@Andrey-Pavlov ... the last time I met that was when a module was placed to the `declaration` section instead of `imports` section by mistake in NgModule metadata.

**Comment by vdsabev** [comment] 2017-12-09 10:47
In my case, Angular v5.1.0 was hiding the real errors. Reinstalling v5.1.0 didn't fix the issue, but once I downgraded back to v5.0.3, module errors started to pop up and I was able to fix them one by one.

**Comment by sandangel** [comment] 2017-12-09 14:33
I think I found the source of problem. When I create a pipe, component... under app/test/ folder but not import it to a ngmodule, the error will occur as described above. When I downgrade to 5.0.5, it will show the error that ERROR in Error: Cannot determine the module for class...
I have to manually add exclude: [..., "app/test/**/*"] to tsconfig.app.json and the error has gone.

**Comment by cbingrui** [comment] 2017-12-13 05:14
May as @vdsabev said when build with `--prod` or `--aot`:
> Angular v5.1.0 was hiding the real errors

It works for me:
1. downgrade back to v5.0.5 by replace `^5.0.0` to `5.0.5` in package.json
2. `yarn install`
3. now `ng serve --aot` would show you the **REAL** errors
4. revise 'package.json' back and `yarn install`

**Comment by TheSegfault** [comment] 2017-12-13 10:13
Had the same issue because of --aot flag:
Fix: ionic app-scripts 3.1.5 -> downgraded to 3.1.2 fixed it.

**Comment by deebloo** [comment] 2017-12-14 13:20
I had opened an issue on the cli with a repo to reproduce. https://github.com/angular/angular-cli/issues/8860. If this is in fact an issue with Angular itself I will close that issue

**Comment by ckapilla** [comment] 2017-12-16 18:20
I can verify this is not a cli issue. I'm not using CLI but I get this error with 5.1.0 when the source error is hidden. Downgrading to 5.0.5 as suggested above shows the real error, which when corrected allows the build to complete successfully.

**Comment by crutchcorn** [comment] 2017-12-26 17:36
For those that are affected by hidden error messages in Angular 5.1.0, this has been fixed in Angular 5.1.1

**Comment by AghaAliAbbasKhan** [comment] 2018-01-01 11:06
it is a problem with app-scripts version 3.1.0, Either downgrade the app scripts to version 2.0.2 or upgrade app-scripts to 3.1.7 and then make a build with prod or aot and problem will be resolved

**Comment by tlaak** [comment] 2018-01-09 14:59
I encountered the same issue. I couldn't easily tell what could have caused it so I followed the upgrade instructions in the comments and upgraded to Angular 5.1.3

Then I got a different error which seems to be tslint related: 

`ERROR in : TypeError: Cannot read property 'flags' of undefined at checkUnreachable`

I didn't find anything reasonable that could fix it, so a thought just came into my mind: *What if I try using yarn instead of npm?*

I deleted node_modules and reinstalled everything with yarn and tried running the development build (I use ---aot flag). Bang! It throws a different, this time more useful and meaningful error: `ERROR in : Template parse errors: Unexpected closing tag "div".` with the filename and the line number. 

There it was. Fixed it, now it works again.

Now I'm seriously considering moving to yarn permanently.

**Comment by mburger81** [comment] 2018-01-09 15:08
@AghaAliAbbasKhan thats not the whole truth.
app-scripts before 3.1.7 does not forward the wrong error from angular, and that was and is still ionic's problem, but the error cames from ng

**Comment by crutchcorn** [comment] 2018-01-09 15:16
@tlaak packaging shouldn't be the issue here. Are you sure yarn installed the same version of Angular?

**Comment by tlaak** [comment] 2018-01-09 15:36
@crutchcorn There's too many changes to be able to tell quickly, but I suspect that there's a version mismatch somewhere. After removing the unexpected closing tag and restoring package-lock.json, I'm still getting the same 'flags' error as above. After deleting package-lock.json and reinstalling, it works.

**Comment by RadouaneRoufid** [comment] 2018-01-11 16:28
Upgrading to angular 5.2.0 gives a more clear message : 

`ERROR in : Cannot determine the module for class UserProfileActivitiesComponent in /home/koc2ju/Documents/dev/projects/deepan/deepan-parent/deepan-front/src/gui/src/app/modules/account/views/profile/services/activities/user-profile-activities.component.ts! Add UserProfileActivitiesComponent to the NgModule to fix it.`

So you have to be sure that all your components are imported in a ngModule ou excluded is tsconfig file.

**Comment by hughanderson4** [comment] 2018-01-12 15:31
# Please make sure all paths match exactly!  Angular 5+ is *case-sensitive* for paths!

It took me 6 hours last night to track down this issue in Angular 5 aot build.

Here's the bad code:
`import { ProgramTitlesMassChangeDialogComponent } from './containers/programTitles/program-titles-mass-change.dialog.component';`

Here's the good code:
`import { ProgramTitlesMassChangeDialogComponent } from './containers/programtitles/program-titles-mass-change.dialog.component';`

That capital "T"in "programtitles" was the whole problem!

Only error message in Angular 5 aot build was
> Can't resolve './app.module.ngfactory'

Discussion on this thread definitely helped, so thanks to all here.  It was necessary to downgrade to earlier Angular version to get a meaningful error message that pointed me to the problem component.

**Comment by mlc-mlapis** [comment] 2018-01-12 15:33
@hughanderson4  ... Angular was always sensitive to this ... even from very early 2.x Beta.

**Comment by tlaak** [comment] 2018-01-13 17:24
Having an incorrect casing in your path would also cause issues on CI pipelines, if they happen to run on Linux, which has a case-sensitive file system unlike macOS or Windows.

**Comment by himawari8** [comment] 2018-03-09 03:40
Try run this command

`$ ./node_modules/.bin/ngc`

It will show the detail error part in your code, it saved my life trying to find what was causing the error. May this can help you.

**Comment by yy7054wyq5** [comment] 2018-03-14 03:48
I have fix this problem by update Angular and @angular/cli to latest.

**Comment by vZanchiV** [comment] 2018-03-28 11:49
I have fix this problem with  ./node_modules/.bin/ngc and i delete component not use in my App

**Comment by mhevery** [comment] 2018-04-10 22:42
closing since it sounds like it is resolved

**Closed by mhevery** 2018-04-10 22:42 UTC
Labels: comp: core & compiler, state: Follow Up, type: bug/fix

**Comment by goyuquan** [comment] 2018-05-20 13:10
I resolved!! it's not the problem of "module.ngfactory", After your fix other error like private property use in template, The problem above automatic resolved. 
First resolve syntax error which ngcli Throw out.
I'm using ng6.03
I hope it will solve your issue.

**Comment by BennieMeng** [comment] 2018-07-04 08:53
as to me, i find only annotate the component include ngx-clipboad plugin, it will work well.
so i update the version of ngx-clipboard from 8.1.4 to 11.1.0, it works.
