### ISSUE TITLE
Reevaluate pipe on demand

### ISSUE THREAD

**Issue by TKul6** [angular/angular#36294] opened 2020-03-28 09:56 UTC
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/core

### Description
 When creating a pipe you can either set it to pure which only trigger reevaluate when one of the provided argument is changed, or impure which evaluates the value on almost every user action.

Some of my pipes are connected to a cache in an NGRX store, and I'd like to also evaluate the pipe's value when the cache updates.

### Describe the solution you'd like
 Not sure how, but it would be nice if I had a way in the constructor to inject the store,  subscribe to the relevant event and call to reevaluate method.

### Describe alternatives you've considered
 Currently whenever the pipe is used, there is a logic in the hosting component's ts file that listens to the cache updates and increases a revisionId property. this property is passed to the pipe and trigger the transform (and that is the only purpose in life for the revisionId).

It work's OK, but there is some plumbing involve every time the pipe is used.

**Comment by ericmartinezr** [comment] 2020-03-28 11:30
Dup/related https://github.com/angular/angular/issues/15041

**Comment by pkozlowski-opensource** [comment] 2020-03-28 12:00
It is indeed duplicate of #15041 - thnx @ericmartinezr ! @TKul6 feel free to add info about your use-case in there (if it is not covered there already).

**Closed by pkozlowski-opensource** 2020-03-28 12:00 UTC
