### ISSUE TITLE
page linked in roadmap doesn't exist (Try Inject)

### ISSUE THREAD

**Issue by markgoho** [angular/angular#53787] opened 2024-01-04 00:52 UTC
### Describe the problem that you experienced

Went to the [Angular Roadmap](https://angular.dev/roadmap) page, tried to click "Try Inject" at the bottom which led to https://angular.dev/di

### Enter the URL of the topic with the problem

https://angular.dev/di

### Describe what you were looking for in the documentation

Information about the inject function

**Comment by JoostK** [comment] 2024-01-04 09:26
Thanks for the report, this is a duplicate of https://github.com/angular/angular/issues/52539 for which the fix is pending deployment.

**Closed by JoostK** 2024-01-04 09:26 UTC
