### ISSUE TITLE
Make DefaultValueAccessor standalone

### ISSUE THREAD

**Issue by Alex88360** [angular/angular#58501] opened 2024-11-04 17:09 UTC
### Description

Right now if we want to create a custom component hat includes an input like this :

@Component({
  selector: 'app-file-uploader',
  standalone: true,
   imports: [
      DialogFieldDirective,
      FormsModule,
      InputDirective,
      ReactiveFormsModule,
      NgOptimizedImage
   ],
  template: `
     <input type="file" #fileInput (change)="onPictureUpload($event)"/>
     @if (picture) {
        <img [src]="picture" width="150" height="150" alt="picture">
        <button type="button" class="btn-danger btn-danger1 btn-renderer"
                (click)="onPictureDeleted()" title='Supprimer'>
           <i class="fa fa-trash" aria-hidden="true"></i>
        </button>
     }
  `,
   styles: [`
      :host {
         display: flex;
         flex-direction: column;
      }
   `],
   hostDirectives: [DefaultControlValueAccessor]
})
export class FileUploaderComponent {
...
}

we can't add DefaultControlValueAccessor to the hostDirectives array because it is not standalone.

### Proposed solution

Make it standalone

### Alternatives considered

Don't make it standalone

**Comment by JoostK** [comment] 2024-11-04 17:47
We don't intent to mark individual value accessors as standalone, as it introduces a DX pitfall for consumers: the forms API is designed to determine the necessary value accessor based on the template usage, and having the value accessors available as standalone prompt for incorrect usage of value accessors, resulting in non-trivial failure modes.

Closing as duplicate of #48607, #49720.

**Closed by JoostK** 2024-11-04 17:47 UTC
Labels: area: forms
