### ISSUE TITLE
Tests: ChangeDetectorRef differs from component and fixture

### ISSUE THREAD

**Issue by kukjevov** [angular/angular#17356] opened 2017-06-09 10:48 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When i have test which looks like this 

``` typescript
import {ComponentFixture, TestBed} from '@angular/core/testing';
import {By} from '@angular/platform-browser';
import {DebugElement} from '@angular/core';

import {FakeHomeComponent} from './fakehome.component';

describe('BannerComponent (inline template)', () =>
{
    let comp: FakeHomeComponent;
    let fixture: ComponentFixture<FakeHomeComponent>;
    let de: DebugElement;
    let el: HTMLElement;

    beforeEach(() =>
    {
        TestBed.configureTestingModule(
        {
            declarations: [FakeHomeComponent], // declare the test component
        });

        fixture = TestBed.createComponent(FakeHomeComponent);

        comp = fixture.componentInstance; // BannerComponent test instance

        // query for the title <h1> by CSS element selector
        de = fixture.debugElement.query(By.css('h1'));
        el = de.nativeElement;
    });

    it('should display a different test title', () => 
    {
        fixture.detectChanges();
        comp.title = 'Test Title';
        fixture.changeDetectorRef.detectChanges();
        
        console.log(comp.changeDetector == fixture.changeDetectorRef);
        expect(el.textContent).toContain('Test Title');
    });
});
```

and component which looks like this

``` typescript
import {Component, ChangeDetectionStrategy, ChangeDetectorRef} from '@angular/core';

@Component(
{
    selector: 'fake-home',
    template: '<h1>{{title}}</h1>',
    changeDetection: ChangeDetectionStrategy.OnPush
})
export class FakeHomeComponent 
{
    //######################### public methods - implementation of OnInit #########################
    
    title = 'Test Tour of Heroes1';

    constructor(public changeDetector: ChangeDetectorRef)
    {
    }
}
```

change detector from component instance is not same instance as change detector provided by `fixture.changeDetectorRef`.

**Expected behavior**

`fixture.changeDetectorRef` should be same instance as `component.changeDetectorRef` to be able to do tests for *OnPush* `ChangeDetectionStrategy`. Otherwise what is usage of `fixture.changeDetectorRef` and how it can be used for running `DetectChanges()` inside of component.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Windows 10, npm 3.7.3, Visual Studio Code

* **Angular version:** 4.2.0

* **Browser:** [Chrome]

 
* **Language:** [TypeScript 2.3.4]

* **Node (for AoT issues):** `node --version` = 6.9.4

**Comment by jasonaden** [comment] 2018-01-02 23:22
Based on #18817, this is working as intended. I'll close this now as if this changes in the future, it would affect testing as well, so can be tracked under that issue.

**Closed by jasonaden** 2018-01-02 23:22 UTC
Labels: comp: testing
