### ISSUE TITLE
bug(compiler) Structural directive microsyntax

### ISSUE THREAD

**Issue by youdz** [angular/angular#15067] opened 2017-03-10 17:17 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

The following template describes using a structural directive with 2 options:
```html
<h1 *myDirective="firstOption: true; secondOption: false">Hello</h1>
```
But writing such a template results in the error: `Error: Template parse errors: TypeError: Cannot read property 'toUpperCase' of undefined`.

**Expected behavior**

```html
<h1 *myDirective="firstOption: true; secondOption: false">Hello</h1>
```
should de-sugarize to:
```html
<template myDirective [myDirectiveFirstOption]="true" [myDirectiveSecondOption]="false">
    <h1>Hello</h1>
</template>
```
This is what the microsyntax documentation describes.

**Minimal reproduction of the problem with instructions**

http://plnkr.co/edit/sMFv2iGJoOdCRlWpIs40?p=preview
The plunker crashes with the described error. 
Using the manually de-sugarized
```html
<ng-template myDirective [myDirectiveFirstOption]="true" [myDirectiveSecondOption]="false">
```
makes it work fine.

**What is the motivation / use case for changing the behavior?**

When writing reusable components and directives, offering the asterisk syntax is an important part of making the API easy to learn and understand. It follows the `*ngIf` and `*ngFor` lead people are used to.

* **Angular version:** 2.4.X

* **Browser:** all

 
* **Language:** all

**Comment by alexzuza** [comment] 2017-03-10 18:49
> This is what the microsyntax documentation describes.

Where is it described?
Seems it always works this way. We can write

`*myDirective="true, secondOption: false"`

or
` *myDirective="{firstOption: true, secondOption: false}"`

**Comment by youdz** [comment] 2017-03-10 20:38
Oh, `*myDirective="{firstOption: true, secondOption: false}"`. I didn't think of that one. That's actually a very reasonable solution for now.

But the other examples you give are slightly off, the syntax is not the actual one.
It's:
- `*myDirective="true; secondOption: false"`, with a semicolon, and 
- `*myDirective="let x; firstOption: true; secondOption: false"` with a lot more delimiters.

It's the fact that all these delimiters make the syntax non-ambiguous that I don't understand why the example posted above crashes during desugarization.

Thank you for pointing me to a working solution for now, I'll definitely use the "single-object input" trick. But I do hope that this issue will actually be fixed at some point, because I see not reason for it not to work as expected.

**Comment by ghetolay** [comment] 2017-03-13 12:13
So I've been looking at this issue. Here is my understanding : 

`*dir="input1: value1"` will be desugared into `dir: input1: value1`
At this point it's hard to find out that `input1` isn't the value of `dir` but a new Input. Colon are optional so it gets even harder with `dir: input1 value1`. This would require  2 pass and add complexity to the template bindings parser.

On the other hand I was able to easily adapt the template binding parser to handle semicolon without value like: `template="dir; input1: value1"`. So the solution could be to desugar conditional `*dir=` into either `dir: ` or `dir;` depending if the Directive has an input of the same name or not. 
This means resolving the directive earlier on the code and twice (or cache it on a var and merges results later). I don't how much this could impact performance.

But basically we would replace :

```ts
prefixToken = normalizedName.substring(TEMPLATE_ATTR_PREFIX.length) + ':';
```
with
```ts
const dirSelector = createElementCssSelector(TEMPLATE_ELEMENT, [ [normalizedName, ''] ]);
const { directives } = this._parseDirectives(this.selectorMatcher, dirSelector);

 //sanity check directives exist and has only 1 element
const directive = ...;

prefixToken = normalizedName.substring(TEMPLATE_ATTR_PREFIX.length) + 
    ( directive.inputs[normalizedName] ? ':' : ';' );
}
```

I could work on that just let me now.

**Comment by trotyl** [comment] 2018-02-18 07:59
Duplicate of #5894, #12194

**Comment by AndrewKushnir** [comment] 2020-10-20 03:56
Closing as a duplicate of #5894 and #12194.

**Closed by AndrewKushnir** 2020-10-20 03:56 UTC
Labels: P3, comp: core, core: ng-template and *microsyntax, freq1: low, type: bug/fix
