### ISSUE TITLE
Angular v13.0.0 is missing in CHANGELOG.md

### ISSUE THREAD

**Issue by 123NeNaD** [angular/angular#44560] opened 2021-12-24 15:50 UTC
### Description

I was reading the [blog post](https://blog.angular.io/angular-v13-is-now-available-cce66f7bc296) for the new release of Angular v13, and in the end there is the link to the [CHANGELOG](https://github.com/angular/angular/blob/master/CHANGELOG.md) for more details. I noticed that changes for v13.0.0 are not included.

I investigated a little and noticed that changes were included before, but they are removed in one of the latest commits. I think these changes should be in the CHANGELOG.md since they include all important breaking changes between v12 and v13.

This is the [commit](https://github.com/angular/angular/commit/532d7d436fa1e7a1ea97ea3288f0f6c6c4e34b71#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4ed) that removed the changes.

### What is the affected URL?

https://github.com/angular/angular/blob/master/CHANGELOG.md

**Comment by JoostK** [comment] 2021-12-24 16:38
Thanks for reporting. This is a duplicate of #44548.

**Closed** 2021-12-24 16:38 UTC
