### ISSUE TITLE
5.0.0-rc.2 - static fields removed in transpiled code

### ISSUE THREAD

**Issue by seanlandsman** [angular/angular#19782] opened 2017-10-18 13:34 UTC
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

If you reference a static field in another class and then transpile using ngc, the generated file with the static field does not contain the original data.

For example:

```
export default class RefData {
    static countries = [
        {country: "Ireland", continent: "Europe", language: "English"},
        {country: "Spain", continent: "Europe", language: "Spanish"}
    ];
}
```
-----
```
import {Component} from "@angular/core";
import RefData from "./refData";

@Component({
    selector: 'my-app',
    templateUrl: './app.component.html'
})
export class AppComponent {
    countries: any[];

    ngOnInit() {
        this.countries = RefData.countries;
    }
}
```

When transpiled, the generated refData.js file will have an empty function - no data (no countries) will be present

## Expected behavior

The transpiled files should contain the original static data. This worked as expected in versions before Angular 5rc2

## What is the motivation / use case for changing the behavior?

I've created a simple repo of the issue here:

https://github.com/seanlandsman/angular-quickstart-aot.git

Instructions:
npm install
./node_modules/.bin/ngc -p tsconfig-aot.json 

If you look at aot/src/app/refData.js you'll see it no longer contains the countries data. This will cause a runtime error.

## Environment

<pre><code>
Angular version: 5.0.0-rc.2

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 7.7.3
- Platform: OSX Sierra

Others:

</code></pre>

**Comment by trotyl** [comment] 2017-10-18 14:08
Duplicate of https://github.com/angular/angular/issues/19587.

**Comment by tbosch** [comment] 2017-10-18 20:11
Yes, this is a duplicate.

**Closed by tbosch** 2017-10-18 20:11 UTC
