### ISSUE TITLE
Rename dependencies

### ISSUE THREAD

**Issue by voliva** [angular/angular#9806] opened 2016-07-04 18:06 UTC
**I'm submitting a ...**  (check one with "x")

```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

With the current injectior options you can't redefine a service that uses his parent, because of a circular dependency.

For instance, imagine I make a new service, called `HttpA` that uses the `Http` service but adding a functionality. Now, as long as my service extends `Http` or explicitly uses `Http` (by creating an instance) I can declare a provider for this service with:

``` javascript
provide(HttpA, {
    useFactory: (xhrBackend: XHRBackend, requestOptions: RequestOptions) => {
        return new HttpA(xhrBackend, requestOptions);
    },
    deps: [XHRBackend, RequestOptions]
})
```

But now, maybe I don't want to go through all my application and change all the Http references to HttpA, so I can do something like this:

``` javascript
provide(Http, {
    useFactory: (xhrBackend: XHRBackend, requestOptions: RequestOptions) => {
        return new HttpA(xhrBackend, requestOptions);
    },
    deps: [XHRBackend, RequestOptions]
})
```

And this will work perfectly.

But what will happen if we create another Http-based service called `HttpB` that adds a different functionality from `HttpA`? If we use the same provider as `HttpA` it will replace that implementation with the new one, because we will be telling the injector that whenever someone asks for the `Http` service, give him the `HttpB` service instance that we just created, that it uses or extends @angular/core `Http`, thus the functionality in `HttpA` will be lost.

The problem then is that when we try to use the injector to get the last `Http` implementation we get a cyclic dependency error:

``` javascript
provide(Http, {
    useFactory: (http:Http) => {
        return new HttpA(http);
    },
    deps: [Http]
})
```

And it makes sense if you read it like "When someone asks the `Http` service, get the `Http` service and use `HttpA` instead", but wouldn't it be cool the injector to know that the `Http` service we are injecting in the provider is not the same we are returning? (i.e., it's the last defined implementation)? In fact, the behaviour that I want would be like:

``` javascript
provide(Http, {
    useFactory: (http:OldHttp) => {
        return new HttpA(http);
    },
    deps: [OldHttp]
})
```

But of course this won't work now because OldHttp is not defined (this is just the behaviour I mean)

This would let the developers do these kind of chaining, with any service (Angular 2 or custom)

_PS: This feature was crafted from a talk in AngularCamp Barcelona June 2016_

**Comment by awerlang** [comment] 2016-07-09 18:24
In other words, you want decorators from angular 1. 

And specifically for Http there was a proposal for interceptors at #2684

**Comment by voliva** [comment] 2016-07-10 07:33
@awerlang I haven't tried yet, but I think that using decorators in NG1 would have the same Cyclic dependency problem. It's not about renaming a variable name, it's about renaming a dependency. It's about tellling the injector that the service I want to use is the old service that was declared, not the service I'm redeclaring now.

And I wasn't talking specifically about interceptors here.
The thing is that I created an implementation of NG2 Http that supports interceptors here voliva/a ngular2-interceptors (already asked for feedback at angular/http#80, that's the followup of 2684) 
Now, when I presented this in AngularCamp Barcelona 2016, I told people you can use providers to "override" de default Http service for this extended service, but then we discussed that what if there's another http implementation we also want to use (that gives a completely different feature about interceptors) and we want to just chain them? Then these new services can't just override the Http service on the provider because they will replace each other then, we have to pass them an instance of http and tell them to use it.
Then the cyclic dependency arises: We are telling the injector to replace the Http service with a new provider that needs the Http service (although I want to tell him that I want the old Http, not the one I'm defining)

**Comment by awerlang** [comment] 2016-07-10 17:40
> I haven't tried yet, but I think that using decorators in NG1 would have the same Cyclic dependency problem.


> Then the cyclic dependency arises: We are telling the injector to replace the Http service with a new provider that needs the Http service (although I want to tell him that I want the old Http, not the one I'm defining)

That's what the decorators did. They give you access to the original implementation through `$delegate`.

**Comment by trotyl** [comment] 2018-02-17 08:46
Superseded by #14620 or #22064.

**Comment by pkozlowski-opensource** [comment] 2018-10-29 15:10
Closing as a duplicate of #22064 since it has best name / description / discussion. Thnx @trotyl for tracking down the existing issues!

**Closed by pkozlowski-opensource** 2018-10-29 15:10 UTC
Labels: comp: core & compiler, freq2: medium, type: feature
