### ISSUE TITLE
Language Service: string vs enum "Expected the operants to be of similar type or any"

### ISSUE THREAD

**Issue by LeoDupont** [angular/angular#32372] opened 2019-08-28 15:15 UTC
# 🐞 bug report

### Is this a regression?
Doesn't seem so. I've found traces of this bug back from 2017 in the issue #13403 (in baumkr's response). The bug has been fixed for comparing string unions, but not for enums of strings.

### Description
I'm getting a Language Service diagnostic in my template whenever I try to compare a string variable to a string enum's value.

## 🔬 Minimal Reproduction

```typescript
export class AppComponent  {
  public currentStatus: Statuses = Statuses.todo;
}

export enum Statuses {
  todo = "To do",
  doing = "In progress",
  done = "Done",
}
```

```html
<span *ngIf="currentStatus === 'To do'">We have to do this task.</span>
```

## 🔥 Exception or Error
<pre><code>Expected the operants to be of similar type or any</code></pre>

**Comment by atscott** [comment] 2020-10-26 19:31
Thanks for reporting this issue. This appears to have been fixed in one of the recent releases (I can't reproduce the problem). Please update to the most recent version to resolve the problem.

If after upgrade the problem still exists in your application please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.

**Closed by atscott** 2020-10-26 19:31 UTC
Labels: comp: language-service
