### ISSUE TITLE
[feature ideia] *ngSwitchCase for multiple binding

### ISSUE THREAD

**Issue by tiaguinho** [angular/angular#20027] opened 2017-10-30 17:35 UTC
## I'm submitting a new feature

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[X] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## What is the motivation / use case for changing the behavior?
Many languages has the power of using multiple binding inside switch/case, like in Go:
```go
switch varname {
    case "a":
    case "b":
        do something...
}
```

So, my proposal is to create a new directive to handle multiple options for a match.
I think the name could be ```*ngSwtichCases``` where it's possible pass one array of values who matches the case.

Example:

```html
<div *ngSwitchCases="['a', 'b']">....</div>
```

What do you guys think about it?

</code></pre>

**Comment by tiaguinho** [comment] 2018-03-15 14:59
Can I implement this?

**Comment by adamdport** [comment] 2018-05-25 14:48
@tiaguinho IMHO it doesn't need to be a new directive. Why not leave it `ngSwitchCase`? If the case is an array, check each value, otherwise use the existing functionality

**Comment by pkozlowski-opensource** [comment] 2018-06-27 12:31
This is a duplicate of the existing issue #14659

**Closed by pkozlowski-opensource** 2018-06-27 12:31 UTC
Labels: comp: common, type: feature
