### ISSUE TITLE
Can't subscribe to URL updates from the router from childRoutes

### ISSUE THREAD

**Issue by oreofeolurin** [angular/angular#7634] opened 2016-03-16 21:26 UTC
I can't access suscribe to router updates from child routes. It only works in AppComponent and it dosent work in DashboardComponent. This is my set up

```javascript
@RouteConfig([
     { path: '/', name: 'Index', component: IndexComponent, useAsDefault: true },
     {path: '/dashboard/...', name: 'Dashboard', component: DashboardComponent}
])
export class AppComponent{
    constructor(private router: Router){
         this.router.subscribe(route => {console.log(route)});
         //works here
    }
}

@RouteConfig([
      { path: '/', name: 'Home', component: HomeComponent, useAsDefault: true },
      {path: '/inbox', name: 'Inbox', component: InboxComponent}
 ])
export class DashboardComponent{
     constructor(private router: Router){
          this.router.subscribe(route => {console.log(route)})
           //dosent work here
      }
}

**Comment by brandonroberts** [comment] 2016-03-16 21:38
Dupe of https://github.com/angular/angular/issues/5405 . At some point, subscribing in a child router will give you child router updates.

Try using `this.router.root.subscribe` instead

**Comment by oreofeolurin** [comment] 2016-03-16 21:44
Hey, my bad........sorry for the duplicate. Thanks `this.router.root.subscribe` works like charm.

**Comment by brandonroberts** [comment] 2016-03-16 21:46
:+1: Close this one if the solution is sufficient.

**Comment by oreofeolurin** [comment] 2016-03-16 21:47
Okay thanks

**Closed** 2016-03-16 21:47 UTC
