### ISSUE TITLE
http/response.ok is undefined although API says it should be boolean

### ISSUE THREAD

**Issue by wardbell** [angular/angular#8031] opened 2016-04-12 20:57 UTC
**Steps to reproduce and a minimal demo of the problem**
Examine the response object returned by any `http.get`

**Current behavior**
`res.ok` is undefined.

**Expected/desired behavior**
`res.ok`, per API doc, " True if the response's status is within 200-299"

Let's implement it:
```
get ok() { return this.status >= 200 && this.status <= 300; }
```
**Other information**
beta.14

**Comment by oliverjanik** [comment] 2016-04-15 04:23
Dup? #6390

**Comment by pkozlowski-opensource** [comment] 2016-04-15 08:05
Yup, looks like duplicate of #6390

**Closed by pkozlowski-opensource** 2016-04-15 08:05 UTC
