### ISSUE TITLE
Support for rest of path in Route (Possible bug with Redirect)

### ISSUE THREAD

**Issue by waeljammal** [angular/angular#6770] opened 2016-01-29 09:52 UTC
Hi,

So I have a use case and cant seem to find a good way around it.

I have a route that looks like this:

```javascript
new Route({
        path: '/:language/manage-assets/:path',
        component: Assets,
        name: 'PortalAssets',
        data: {id: 'portal-assets'}
})
```

And my :path parameter looks like this:

folder1/subfolder1/

The path updates and works fine however if I reload the browser the redirect kicks in instead of keeping me in the same component.

It only works if my path looks like:

folder1

but fails and redirects if its:

folder1/subfolder1/

if this is not an issue with the Redirect route then could we possible have support for something like /:path** or /:path? or /:path.*

**Comment by brandonroberts** [comment] 2016-01-29 13:01
I think what you are looking for is the wildcard parameter. Everything after the asterisk will be captured into one parameter. There is a bug where the wildcard param is lost on reload, but the navigation still works.

`path: '/:language/manage-assets/*path'`

**Comment by waeljammal** [comment] 2016-01-29 13:18
Thanks, is there a task for that bug yet? I was unable to find one.

**Comment by brandonroberts** [comment] 2016-01-29 13:19
Yep: https://github.com/angular/angular/issues/6305

**Comment by waeljammal** [comment] 2016-01-29 13:38
Thanks

**Comment by vsavkin** [comment] 2016-07-22 20:57
Duplicate of https://github.com/angular/angular/issues/6305

**Closed by vsavkin** 2016-07-22 20:57 UTC
