### ISSUE TITLE
error TS2420: Class 'NgxMatDatetimeContent<D>' incorrectly implements interface 'CanColor'.       Type 'NgxMatDatetimeContent<D>' is missing the following properties from type 'CanColor': color, defaultColor

### ISSUE THREAD

**Issue by kushalbajje** [angular/angular#42057] opened 2021-05-12 09:16 UTC
Please file any Angular Components issues at: https://github.com/angular/components/issues/new

For the time being, we keep Angular Components issues in a separate repository.
  node_modules/@angular/material/core/option/optgroup.d.ts:17:22 - error TS242
0: Class '_MatOptgroupBase' incorrectly implements interface 'CanDisable'.
      Property 'disabled' is missing in type '_MatOptgroupBase' but required in
type 'CanDisable'.

    17 export declare class _MatOptgroupBase extends _MatOptgroupMixinBase imple
ments CanDisable {
                            ~~~~~~~~~~~~~~~~

      node_modules/@angular/material/core/common-behaviors/disabled.d.ts:12:5
        12     disabled: boolean;
               ~~~~~~~~
        'disabled' is declared here.
    node_modules/@angular/material/button/button.d.ts:22:22 - [91merror TS2420:
Class 'MatButton' incorrectly implements interface 'CanColor'.
      Type 'MatButton' is missing the following properties from type 'CanColor':
 color, defaultColor

    22 export declare class MatButton extends _MatButtonMixinBase implements Aft
erViewInit, OnDestroy, CanDisable, CanColor, CanDisableRipple, FocusableOption {
                            ~~~~~~~~~
    node_modules/@angular/material/button/button.d.ts:22:22 - error TS2420: Clas
s 'MatButton' incorrectly implements interface 'CanDisable'.
      Property 'disabled' is missing in type 'MatButton' but required in type 'C
anDisable'.

    22 export declare class MatButton extends _MatButtonMixinBase implements Aft
erViewInit, OnDestroy, CanDisable, CanColor, CanDisableRipple, FocusableOption {
                            ~~~~~~~~~

      node_modules/@angular/material/core/common-behaviors/disabled.d.ts:12:5
        12     disabled: boolean;
               ~~~~~~~~
        'disabled' is declared here.
    node_modules/@angular/material/button/button.d.ts:22:22 - error TS2420: Clas
s 'MatButton' incorrectly implements interface 'CanDisableRipple'.
      Property 'disableRipple' is missing in type 'MatButton' but required in ty
pe 'CanDisableRipple'.

    22 export declare class MatButton extends _MatButtonMixinBase implements Aft
erViewInit, OnDestroy, CanDisable, CanColor, CanDisableRipple, FocusableOption {




I removed node modules and I ran npm install commdan from that point I am getting the above mentioned errors.

I believe it's because of typescript version, the current stable version of typescript is 4.2.4 but application throws a error saying typescript version should be >= 4.0.0 and < 4.1.0

When I downgrade the typescript version to 4.0.2 I am getting TS1005 error which is typescript syntax error, I don't know how to resolve this, could you help me with this.

**Comment by petebacondarwin** [comment] 2021-05-12 09:31
Duplicate of https://github.com/angular/components/issues/22671

**Closed by petebacondarwin** 2021-05-12 09:31 UTC
