### ISSUE TITLE
use Angular Element and meet "The selector "app-root" did not match any elements"

### ISSUE THREAD

**Issue by YangfeiLi** [angular/angular#24674] opened 2018-06-26 13:53 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

I created a custom component and export it as a JavaScript file, following the instruction in this link (https://angularfirebase.com/lessons/angular-elements-quick-start-guide/). I included the script file into an html file. But when I open the html in the browser (Chrome), I met an error saying **"The selector "app-root" did not match any elements"**. But when I delete
`bootstrap: [AppComponent],`
in app.module.ts file, the problem will disappear.

**app.module.ts code:**
![image](https://user-images.githubusercontent.com/32227571/41916472-1e9ec8aa-7926-11e8-9937-b340daa36e72.png)

**app.component.ts**
![image](https://user-images.githubusercontent.com/32227571/41916710-a1cb28c2-7926-11e8-8241-d9c10c374c2d.png)

**index.html code**
`<body>`
  `<app-root></app-root>`
  `<custom-visualization></custom-visualization>`
`</body>`

**my demo html code:**
`<custom-visualization></custom-visualization>`
`<script src="./exportedCustoVmisualization.js"></script>`

## Expected behavior

I hope my exported script file can work with root component bootstrapped, i.e. have line 
`bootstrap: [AppComponent],`.

## Environment
<pre><code>
Angular version: X.Y.Z
Angular CLI: 6.0.8
Node: 8.11.2
OS: win32 x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.6.8
@angular-devkit/core         0.6.8
@angular-devkit/schematics   0.6.8
@schematics/angular          0.6.8
@schematics/update           0.6.8
rxjs                         6.2.1
typescript                   2.7.2

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
v8.11.2
- Platform:  
Windows

Others:

</code></pre>

**Comment by robwormald** [comment] 2018-06-27 20:05
It's not clear what you're trying to do here, but anything in the bootstrap array will be automatically bootstrapped by Angular, which is likely not what you want to happen when using Angular Elements. 

What does the `app-root` component have to do with anything? If you're creating an Angular Element with the `RendererComponent`, you probably shouldn't have the AppRoot at all. 

This is works as intended, so I'm closing it out. Stop by the https://gitter.im/angular/angular gitter channel if you need more help.

**Closed by robwormald** 2018-06-27 20:05 UTC
Labels: comp: elements
