### ISSUE TITLE
Error: Uncaught (in promise): TypeError: Cannot read property 'isSkipSelf' of null

### ISSUE THREAD

**Issue by pavandv** [angular/angular#8519] opened 2016-05-07 08:26 UTC
After Upgrading from **2.0.0-Beta.14** to **RC.0 & RC.1**.. I see this strange error.. 

![screenshot 32](https://cloud.githubusercontent.com/assets/10683228/15091091/22a3da4e-145b-11e6-8174-556e2dd4b44b.png)

**Comment by olivierceulemans** [comment] 2016-05-07 13:48
I got it too and I still have it, unfortunately.

In my case, it is coming from a component that implements 'ControlValueAccessor' that I tried to migrate to RC1 by looking at what was done in the DefaultValueAccessor in the source code of RC1. The error seems to come from the 'bindings' property on the component, if I remove it this error disappear (but then the value accessor doesn't work) 

I'm still looking on how to solve this, but maybe the above hint may help you.

**Comment by olivierceulemans** [comment] 2016-05-07 14:17
I solved it by changing my custom component.
When migrating to RC1, I tried to mimick the DefaultValueAccessor and i wrote this:
DOESN'T WORK
```
const VALUE_ACCESSOR = {
    NG_VALUE_ACCESSOR,
    useExisting: forwardRef(() => MyComponent),
    multi: true
};

@Component({
    selector: 'my-component',
    bindings: [VALUE_ACCESSOR],
```

Then I got the error you describe.
This version seems to work:
`
const VALUE_ACCESSOR = new Provider(NG_VALUE_ACCESSOR, {
    useExisting: forwardRef(() => FileLibraryPropertiesOptionsEditor),
    multi: true
});

@Component({
    selector: 'file-library-properties-options-editor',
    providers: [VALUE_ACCESSOR],

`

Hope it helps you. I let smarter people explain why... (because I can't...)

**Comment by pavandv** [comment] 2016-05-09 08:58
@olivierceulemans 

Thanks for your inputs, though the problem is not same I have tried reproducing the steps you mentioned and found out that the problem is triggered by `pipes`. 

Still can't figure what the actual problem is Coz, when I removed the pipes, the app loaded fine & when I put it back it loaded fine again.

**Comment by hgrubst** [comment] 2016-05-10 01:22
@pavandv 
I hit the same issue too. The error message is cryptic and does indeed not give you much information about what's happening.
The api for pipes has changed in 2.0.0 beta 16. The changelog actually talks about it, see https://github.com/angular/angular/blob/master/CHANGELOG.md#breaking-changes-1 : 
> pipes now take a variable number of arguments, and not an array that contains all arguments.

If your pipe uses more than one argument, make sure to use the spread operator and not just an array for the second argument.

**Comment by joehmchan** [comment] 2016-05-10 06:07
I got the same issue. Custom pipe (e.g. a new pipe extends CurrencyPipe) doesn't work.

**Comment by benelliott** [comment] 2016-05-10 10:47
I just struggled with this issue for a while before realising I had not set the `emitDecoratorMetadata` flag to `true` in my TypeScript compile options (often in `tsconfig.json` or your build script). This caused Angular to fail to compile metadata for injectables and component providers. However the error message was extremely cryptic and I couldn't even track the problem down with the stack traces!

**Comment by segersrobbert** [comment] 2016-05-10 11:52
A circular dependency also throws this error..

**Comment by deebloo** [comment] 2016-05-10 14:53
I am running into the issue when I am using a barrel with commonjs modules and webpack. From inside my barrel I cannot use a service from the index.ts file.

DOES NOT work
```
import {EventService} from './index';
```

DOES work
```
import {EventService} from './event.service';
```

**Comment by deebloo** [comment] 2016-05-10 15:17
I am ending up hacking around the issue by not exporting the components that are assigned to a route in my *_DIRECTIVES array. Could this have something to do with DI or the Router?

**Comment by deebloo** [comment] 2016-05-10 16:05
I THINK the issue is tied to DI. I rewrote my index.ts file from this:
```JS
// Services
import {FooService} from './foo.service';
import {BarService} from './bar.service';

export * from './foo.service';
export * from './bar.service';

export const EVENT_PROVIDERS: any[] = [
    FooService,
    BarService
];

// Components
import {FooComponent} from './foo.component';
import {FooDetailsComponent} from './foo-details.component';

export * from './foo.component';
export * from './foo-details.component';

export const EVENT_DIRECTIVES: any[] = [
    FooComponent,
    FooDetailsComponent,
];
```

to this:
```JS
// Services
import {FooService} from './foo.service';
import {BarService} from './bar.service';

export {
    FooService,
    BarService
}

export const EVENT_PROVIDERS: any[] = [
    FooService,
    BarService
];

// Components
import {FooComponent} from './foo.component';
import {FooDetailsComponent} from './foo-details.component';

export {
    FooComponent,
    FooDetailsComponent
}

export const EVENT_DIRECTIVES: any[] = [
    FooComponent,
    FooDetailsComponent,
];
```

this works as long as the services come first.

**Comment by mirkonasato** [comment] 2016-05-10 22:09
Here's a simple plunk that reproduces the issue: [plnkr.co/edit/UogZOC](http://plnkr.co/edit/UogZOC?p=preview)

All it has is a `TestService` that depends on `Http`. Works fine when `TestService` is `@Injectable`, but omitting the decorator results in `TypeError: Cannot read property 'isSkipSelf' of null`.

**Comment by gravity-addiction** [comment] 2016-05-11 04:49
I found that when I tried to use the Router from @angular2/router I'd get the error posted by OP.

**Comment by marcojr** [comment] 2016-05-11 14:43
I'm on the same boat after moving from beta 9 to beta 12. :(

**Comment by JSMike** [comment] 2016-05-12 03:05
I had this happen to me when I added Router as a provider in a child component when I wanted to pass it in to the constructor. I then realized that you don't need to add Router as provider because it's already instantiated by the parent component, you just need to import Router and use it. So I would suggest looking for services that you're adding as a provider, when a parent component already has the provider listed.

**Comment by fleske** [comment] 2016-05-12 09:12
I had the same problems, and when I removed viewProviders from components then it did not happen anymore...

**Comment by starswish2100** [comment] 2016-05-12 12:11
I am still having this issue. Do you have any update on this yet?

**Comment by tontonwappy** [comment] 2016-05-12 12:12
i have the same ...

**Comment by studiollama** [comment] 2016-05-13 22:13
I am also still having this issue.

**Comment by pavandv** [comment] 2016-05-15 13:04
@hgrubst My pipe definition doesn't have any arguments, also if we consider this as a problem, then re-adding the pipes again doesn't break the code. It is working fine. 

I still have no idea what caused my app to break, though according to the several comments people posting in this thread, looks like we have several reasons that is causing this issue.

we need someone from angular team to tell us what exactly causes this issue.

**Comment by studiollama** [comment] 2016-05-16 03:46
Yes, I am having this issue and I don't even have any pipes.

**Comment by gaetancollaud** [comment] 2016-05-17 12:26
Same issue here, moving from beta 17 to RC 1

**Comment by mirkonasato** [comment] 2016-05-17 12:50
The real issue here is that the error message is very unhelpful, and a regression compared to the behaviour of beta versions.

**Comment by twastvedt** [comment] 2016-05-18 21:55
If it's useful, I solved my particular incarnation of this using [this comment](http://stackoverflow.com/questions/37165992/angular-2-exception-typeerror-cannot-read-property-isskipself-of-null-brow):

> If you have the following situation:
> 
> component A depends on service B which depends on service C,
> 
> the solution is to add a forwardRef to service C in the constructor of service B and also add service C to the providers list of component A.

In more detail, I replaced: 

`constructor( ... private service: Service ... )`

with

`constructor( ... @Inject(forwardRef(() => Service)) private service: Service ... )` when I had dependencies as above.

**Comment by ecozoic** [comment] 2016-05-20 22:33
+1 to @deebloo 

I ran into same issue as you, using Webpack and barrel files. Found certain ways of importing/exporting in your index.ts work and others don't. Don't know enough about webpack internals to have any idea what's going on or why.

[comment on #8704](https://github.com/angular/angular/issues/8704#issuecomment-220732984)

**Comment by derekkite** [comment] 2016-05-23 01:12
I had this error when I mis edited the constructor in a service. I had some injection happening, and deleted it, leaving one letter.

constructor(r) {...

Delete the r, and it worked. Cryptic message indeed.

**Comment by mikeumus** [comment] 2016-05-28 00:03
I'm using Angular CLI and Material2. I think I'm getting this because of Angular CLI's use of system.config barrels. I tried switching to a non-barrel system-config but couldn't get all of the re-wirings correct. I've tried, for two days now, everything above and more. I would like to be able to use http() like everyone else but I can't spend anymore time trying to debug this. Here's my code:
- https://github.com/mikeumus/ng2-comment/tree/027c80f2b4beb67f5b955428a3de146c3247c411

**Comment by kushwahashiv** [comment] 2016-06-01 12:32
![image](https://cloud.githubusercontent.com/assets/4386810/15709515/c06738f4-2822-11e6-9429-8c5d6c2f8094.png)


I'm also getting above error.
`
@Inject(forwardRef(() => AuthorizedHeader)) private _authorizedHeader: AuthorizedHeader
`

above didn't worked for me in constructor input parameter.
I also have injected service AuthorizedHeader in the root component providers list.

**Comment by pkozlowski-opensource** [comment] 2016-06-02 16:05
This sounds like a support discussion thus closing as per https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

**Comment by mirkonasato** [comment] 2016-06-02 16:19
@pkozlowski-opensource shall re-raise my [comment](https://github.com/angular/angular/issues/8519#issuecomment-218306877) as a separate issue then? It's clearly a regression compared to beta versions.

**Comment by pgatilov** [comment] 2016-06-02 16:34
Agreed. There's clearly a bug that Angular cannot show a reasonable error message, but instead crashes inside error generation code, thus making debugging/troubleshooting very cumbersome.

**Comment by pkozlowski-opensource** [comment] 2016-06-02 17:06
@mirkonasato sorry, missed your plunker as there is so much noise in this issue. For the reference, here is the plunk: http://plnkr.co/edit/UogZOC?p=preview

If I understand correctly this is about a better error message when one forgets `@Injectable`, right?

**Comment by mirkonasato** [comment] 2016-06-02 17:44
@pkozlowski-opensource yes, thanks, the error message is what I consider to be the issue here.

Just did some more tests: seems like the nice error message actually disappeared in **beta.16**:

[beta.15 plunk](http://plnkr.co/edit/wfyMY7?p=preview): shows `Error: Uncaught (in promise): Cannot resolve all parameters for 'AppComponent'(?). Make sure that all the parameters are decorated with Inject or have valid type annotations and that 'AppComponent' is decorated with Injectable.`

[beta.16 plunk](http://plnkr.co/edit/4BQcNP?p=preview): shows no injection errors, but the injected service is `undefined` so will fail the first time you try to use it.

Note that the above example is a simpler case with missing `@Inject` or type annotation, but I believe it's be the same case as the missing `@Injectable`.

**Comment by simonrobb** [comment] 2016-06-03 12:05
Thanks so much @mirkonasato, that really helped me out. I was missing an `@Inject` annotation.

**Comment by mi9rom** [comment] 2016-06-06 14:09
Hi, 
In my case  changing "providers: [ ROUTER_PROVIDERS,Router," to  "providers: [ Router,ROUTER_PROVIDERS"  was the solution.
btw I agree the error message is highly confusing.
Regards

**Comment by zoechi** [comment] 2016-06-06 14:19
@mi9rom `providers: [ROUTER_PROVIDERS]` should work as well then ;-)

**Comment by gdboling** [comment] 2016-06-06 20:11
Ran into this today due to barrels, same as deebloo said.

**Comment by ivangabriele** [comment] 2016-06-07 00:45
Same here.

@zoechi It does indeed.

**Comment by pkozlowski-opensource** [comment] 2016-06-09 09:39
So I can confirm now that the root cause of this one is the same as #8245 and both will be solved by #9065

**Comment by lekhnath** [comment] 2016-06-09 09:44
I was getting this error when added a service Class to @Component's `providers` list and missed to decorate the service Class with @Injectable.

**Comment by pkozlowski-opensource** [comment] 2016-06-10 17:18
This was just fixed in master via 3aca5ff9e20d79e6f84cabeb1335c2e9ebbf142b.

**Closed by pkozlowski-opensource** 2016-06-10 17:18 UTC
Labels: hotlist: error messages

**Comment by born2net** [comment] 2016-06-13 18:00
@twastvedt solution worked for me forcing an inject via fwd reference:
```
constructor(@Inject(forwardRef(() => TodoAction)) private m_todoAction:TodoAction, private _http:Http, private todoStatsModel:TodoStatsModel, private appStore:AppStore) {
```

**Comment by ospaarmann** [comment] 2016-06-17 12:39
I could resolve this issue by checking my dependency injections and cleaning them up, making sure I used the `@Injectable` decorator where neccessary and only inject what's needed where it's needed. 

I also had an issue with injecting a service into another service which was solved by enforcing Metadata Creation. How to do that is described [here](http://blog.thoughtram.io/angular/2015/09/17/resolve-service-dependencies-in-angular-2.html).

I also checked my tsconfig.json to make sure `emitDecoratorMetadata` is set to true, but that wasn't an issue.

**Comment by joe-vella** [comment] 2016-06-18 02:59
I was able to resolve this issue by undoing changes I made to my imports. I am exporting services from an index.js in a part of my folder structure where I have additional folders for models, api services ,and data store services. I cheated a bit by importing everything from './shared' which at the root is an index.js with my imports. That worked until I added another model, api service, and data store service. then I got this error. I reverted back to referencing each individually from their full respective paths as such './data-api-services/schedule-data-api.service'. The error went away and I am now back in business. I am on ng RC1; angular-cli; vs code.

**Comment by Blasz** [comment] 2016-06-18 08:55
@pkozlowski-opensource This does not appear to be fixed. I updated the plunker to rc2 and it still reports the same error: http://plnkr.co/edit/otNSq0iUo82LDQN75rhX?p=preview

**Comment by pkozlowski-opensource** [comment] 2016-06-18 09:00
@Blasz indeed, this seem to happen under different conditions that I've fixed in rc.2. Created new issue to track your case: #9332. Thnx for reporting!

**Comment by JavascriptMick** [comment] 2016-06-28 23:13
the joe-vella  solution (not using ../index) worked for me also, wierd

**Comment by baghdadisan** [comment] 2016-07-22 09:58
Hi, i'm getting this error too on the RC3, i'm trying to migrate my project gradually from release to another, i was having the same on the RC1 i've neglect it, i was assuming that it will be fixed once upgraded to RC3, here is my actual package.json content : 
```
{
  "name": "angular2-quickstart",
  "version": "1.0.0",
  "scripts": {
    "start": "tsc && concurrently \"npm run tsc:w\" \"npm run lite\" ",
    "lite": "lite-server",
    "postinstall": "typings install",
    "tsc": "tsc",
    "tsc:w": "tsc -w",
    "typings": "typings"
  },
  "license": "ISC",
  "dependencies": {
    
    "@angular/compiler": "2.0.0-rc.3",
    "@angular/core": "2.0.0-rc.3",
    "@angular/common": "2.0.0-rc.3",
    "@angular/forms": "^0.1.0",
    
    "@angular/http": "2.0.0-rc.3",
    "@angular/platform-browser": "2.0.0-rc.3",
    "@angular/platform-browser-dynamic": "2.0.0-rc.3",
    "@angular/router":  "3.0.0-alpha.8",
    "@angular/router-deprecated":  "2.0.0-rc.2",
    "es6-shim": "0.35.1",
    "es6-promise": "3.2.1",
    
    "reflect-metadata": "0.1.3",
    "rxjs": "5.0.0-beta.6",
    "systemjs": "0.19.26",
    "zone.js": "0.6.12"
  },
  "devDependencies": {
    "concurrently": "^2.0.0",
    "lite-server": "^2.2.0",
    "typescript": "^1.8.10",
    "typings":"^0.8.1"
  }
}
```
![image](https://cloud.githubusercontent.com/assets/19351741/17053684/706456c6-5003-11e6-8598-713c9d36b11b.png)

**Comment by pkozlowski-opensource** [comment] 2016-07-22 10:02
@baghdadisan there is not much point in commenting on a closed issue. If you still see confusing errors in rc4 please open a new issue with a minimal reproduce scenario in a plunker.

**Comment by jerradpatch** [comment] 2016-07-24 00:24
not sure if this was previously said, but this issues was due to a provider that I created having a non-empty constructor. Hope this helps someone.

**Comment by zhysh** [comment] 2016-08-26 09:58
i have the same problem with rc5

**Comment by zhysh** [comment] 2016-08-26 09:58
![problem](https://cloud.githubusercontent.com/assets/18154492/18001691/68ffbb4a-6b84-11e6-9d70-7e8a6bf17d7f.PNG)

**Comment by pkozlowski-opensource** [comment] 2016-08-26 10:09
@zhysh see https://github.com/angular/angular/issues/8519#issuecomment-234505427

**Comment by zhysh** [comment] 2016-08-29 14:23
i solved the problem with this

http://stackoverflow.com/questions/35337076/cannot-read-property-filter-of-null-in-angular-2

**Comment by Coffee-Tea** [comment] 2016-09-19 12:57
I found this issue when I left the following attribute at some element ;)

`(click)=""`

**Comment by george-i** [comment] 2017-02-21 15:53
Must be declared as provider in app.module.ts:

`@NgModule({
    declarations: [
        ....
    ],
    imports: [
       ...
    ],
    providers: [
        ...
        UserService,
        ...
    ],
    bootstrap: [AppComponent]
})`

**Comment by DaniasHerlambang13** [comment] 2017-06-06 16:35
>

**Comment by unsama** [comment] 2017-08-26 12:57
```
select: function () {
var self = this;
self.$http.post("/purchase/rfq-table", {
"username": self.options,
}).then(function(res){
var data = res.body.result;
self.tabledata = [];
if(data.length > 0){
data.forEach(function(val) {
self.tabledata.push({
"data": [
val.name,
val.schedule_date,
],
"url": "/purchase/RQ/"+val.id,
});
});
console.log(self.tabledata);
}
//self.options =res.body.data;
},function(err){
alert(err);
});
},

```
## Uncaught (in promise) TypeError: Cannot read property 'length' of undefined
i dont know the error please help me out this.

**Comment by hlawuleka** [comment] 2018-01-02 21:29
Odd as this may be, in my instance, after spending lots of time debugging, it turned out, I was using and Output(`@Output`) `EventEmitter` property to handle a custom event, and Angular did not recognize my property or custom event property when passed on a template:

e.g

`<custom-component (keydownEvent)></custom-component>`

The issue with doing the above, is `(keydownEvent)` is not a valid Event handler, but why the heck does it work in development and not when you've built your project. Even MORE strange, `ng build --prod` does not issue any errors or warning!

**Comment by lukaszsamson** [comment] 2018-02-06 10:58
I run into this issue in v5.2.3 when a mistake was introduced to barrel. It's a pity that Angular never produces helpful error messages.

**Comment by jerradpatch** [comment] 2018-10-14 04:32
ran into this issue when using "export default class". Solved it by removing the default, but the comments above were helpful.

**Comment by luckylooke** [comment] 2018-12-11 13:40
My issue was that I was building secondary app (generated via angular CLI command: ng generate application myApp) and this application uses [barrel import](https://basarat.gitbooks.io/typescript/docs/tips/barrel.html) somewhere in its structure. By replacing import with direct/deeper one I have removed the issue.

**Comment by benwinding** [comment] 2019-06-17 09:22
So i was getting the same error 

### Bad error message using: `ng serve` :-1: 

![Selection_006](https://user-images.githubusercontent.com/11782590/59593145-8fe33280-9130-11e9-815d-bc4c256f84d7.png)

### Better error message using: `ng build` :+1: 

![Selection_007](https://user-images.githubusercontent.com/11782590/59593299-d59ffb00-9130-11e9-8709-3fc9b35d9769.png)
