### ISSUE TITLE
Possible slice bug in beta 0

### ISSUE THREAD

**Issue by johnpapa** [angular/angular#5918] opened 2015-12-15 19:30 UTC
Possible bug with `slice` in `alpha.55` and `beta 0` … was there a change with slice recently?

```angular2.dev.js:23524 EXCEPTION: Expression 'heroes | slice:0:4 in DashboardComponent@2:6' has changed after it was checked. Previous value: ''. Current value: '' in [heroes | slice:0:4 in DashboardComponent@2:6]

The app gets a list and then slices them. No changes are made on load.

The app works without slice.

// cc @wardbell

**Comment by vicb** [comment] 2015-12-15 20:26
The `slice` returns a new array each time it is called which confuses the change detection.

The pipe behavior has not changes but you now see the error because dev mode is [enabled by default](https://github.com/angular/angular/commit/3dca9d5) since a.55

**Comment by IgorMinar** [comment] 2015-12-15 20:46
this is an actual bug that needs to be fixed in the code

**Comment by e-oz** [comment] 2015-12-15 21:02
`enableProdMode();` doesn't help...

**Comment by e-oz** [comment] 2015-12-15 22:07
`enableProdMode()` helps when `| async |` pipe is removed :) But only as workaround.

**Comment by johnpapa** [comment] 2015-12-16 02:08
tagging others for help

from Igor: 
> the exception above looks like a unidirectional dataflow issues - ping @vsavkin, @tbosch or @mhevery  for help

**Comment by wardbell** [comment] 2015-12-16 02:15
What is the point of offering a pipe that doesn't work.

I'll bet that the pipes chapter and template syntax chapter samples are now broken because I think they both use the `SlicePipe` and 99% certain that pipes shows the `AsyncPipe`.  I'll check later.

**Comment by johnpapa** [comment] 2015-12-16 02:23
Here is the offending line of code

`<div *ngFor="#hero of heroes | slice:0:4" class="col-1-4" (click)="gotoDetail(hero)">`

this worked up to alpha.53 ... then alpha.55 / beta.0 it gives the error above.

**Comment by cexbrayat** [comment] 2015-12-16 09:36
I ran into this too (I just opened a duplicated issue #5948 as I missed this one, sorry).

Event if the runtime works (despite the errors), my unit tests are failing.

**Comment by doczoidberg** [comment] 2015-12-16 15:59
maybe this is the same issue: http://stackoverflow.com/questions/34313743/expressionchangedafterithasbeencheckedexception-since-angular-2-beta?noredirect=1#comment56369882_34313743

**Comment by thelgevold** [comment] 2015-12-16 16:31
I think this is a variation on an issue I found: https://github.com/angular/angular/issues/5941
The behavior seems to have changed between alpha.53 and beta.

**Comment by thelgevold** [comment] 2015-12-16 17:11
Based on the modified plunker it seems to sometimes support a new object reference, but other times not. I think it should consistently allow the new reference of disallow it. In alpha.53 it was consistently allowing it. https://github.com/angular/angular/issues/5941

**Comment by vsavkin** [comment] 2015-12-16 23:23
The issue is more general. For instance the following will not work either, even though it is an acceptable (or maybe even preferred) way of writing apps:

@Component({
  template: `{{filteredList}}`
})
class MyCmp {
  todos;

  filteredTodos() {
    return this.todos.filter(t => t.completed);
  }
}

One solution would be to create a pipe called, for example, listEq. It would be a noop in the prod mode. And it would compare the list with the previously passed list in the dev mode, and if they are the same, would return the prev list. So the following would work:

@Component({
  template: "{{filteredList | listEq}}"
})
class MyCmp {
  todos;

  filteredTodos() {
    return this.todos.filter(t => t.completed);
  }
}

We can fix `slice` to do something similar. But for now, we can change the example not to use `slice` and cache the subarray on the component.

**Comment by johnpapa** [comment] 2015-12-16 23:33
@vsavkin ... i can ... but the point was to show a pipe in the tutorial. got another suggestion?  I was hoping to show something more useful, but perhaps lowercase or uppercase ?

**Comment by vsavkin** [comment] 2015-12-16 23:39
@johnpapa I see. I think the async pipe is the most useful one, but it requires more explanation. But you can also show DatePipe or UpperCasePipe.

**Comment by johnpapa** [comment] 2015-12-16 23:47
ok .... thanks, i'll remove slice and go uppercase

**Comment by johnpapa** [comment] 2015-12-16 23:48
so should `slice` be removed from angular? @vsavkin

**Comment by johnpapa** [comment] 2015-12-16 23:49
I see slice being used the same way here https://angular.io/docs/ts/latest/api/common/SlicePipe-class.html

**Comment by kylecordes** [comment] 2015-12-16 23:57
It seems to me that some code somewhere is going to have to apply the rule "if the input did not change, the output must not change, not even to something that is equal in value but different in identity". The only real question is whether this is something Angular itself should apply around all pipes (which seems closely related to the "pure" flag), or whether it is a rule that all of us (including the core team in the slice pipe) need to follow in all pipe implementations.

It is not without precedent. Most of us learned early on with Angular 1 that filters had to be quite tolerant of all manner of incoming data (including undefined) to cooperate nicely with typical use cases.

(If we want something better, we know where to find it: in one of the numerous programming languages based on values (immutability etc.) rather than references to mutable things. But that ship sailed for JavaScript years ago.)

**Comment by thelgevold** [comment] 2015-12-17 00:05
@vsavkin I am curious though why the behavior isn't consistent across scenarios that may or may not produce a new reference. In the plunker I reference above, the reference is recreated every time, but it still works. How is that conceptually different from using a filter or slice to return a new reference and not the original array reference?

**Comment by e-oz** [comment] 2015-12-17 02:24
@vsavkin what does mean "compare list"? Compare every item recursively? It can be huge waste of resources for big complicated lists.
What does mean "cache subarray" if whole point of "slice" is react to dynamically changing bounds - it will take a lot of boilerplate code if we will need to write it manually in each view where we currently use "slice".

Beta is released, API should be stable - why you are going to remove filter which is used for every pagination?? Please fix it instead of removing it, do not force developers to write boilerplate code, when you know you can just fix "slice".

And please explain why it is an issue in the first place - should we forget our hope to get rid of $scope.$apply (and, therefore, seamless compatibility with non-angular JS libraries)? It could be "killer-feature" of Angular 2, and it was promised (even in your [blog post](http://victorsavkin.com/post/118372404541/the-core-concepts-of-angular-2)).

**Comment by robianmcd** [comment] 2015-12-22 16:35
I have some code like @vsavkin's example and I'm trying to figure out how best to get it working in beta.0.

```
@Component({
  template: `{{filteredTodos()}}`
})
class MyCmp {
  todos;

  filteredTodos() {
    return this.todos.filter(t => t.completed);
  }
}
```

It seems like this is an issue with dev mode throwing a false negative. I'd rather take a performance hit in dev mode and have it try a bit harder to check weather subsequent calls to a binding are "equal" than have to refactor working code to get it working in dev mode. Maybe I'm misunderstanding the problem though. Are there any docs on what exactly dev mode does? For now I've implemented it like this:

```
@Pipe({name: 'pure'})
export class Pure {
    transform(dummyInput, [pureFunc, ...args]) {
        return pureFunc(...args);
    }
}

@Component({
  template: `{{null | pure:filteredTodos:todos}}`
  pipes: [Pure]
})
class MyCmp {
  todos;

  filteredTodos(todos) {
    return todos.filter(t => t.completed);
  }
}
```

This has the added benefit of caching the result of `filteredTodos()` but calling it looks pretty ugly. It also won't update if you mutate todos. I don't understand why pure pipes only check for changes on the arguments and not the input. Are there any docs on this? It would also be nice if you could give a pipe a compare strategy so you could tell it to do something like check weather the elements of an array have changed.

**Comment by andreev-artem** [comment] 2015-12-26 19:30
Btw, why slice pipe is [not pure](https://github.com/angular/angular/blob/master/modules/angular2/src/common/pipes/slice_pipe.ts#L59)? How return value can be different if input value and args were not changed?

**Comment by mhevery** [comment] 2015-12-26 20:06
Slice can not be pure because the array identity may not change but the
array items can.

**Comment by andreev-artem** [comment] 2015-12-26 20:13
You mean it can be spliced, sorted, etc? Then maybe we need a bit more clever change detection strategy instead of marking slice pipe as non-pure (something like watchCollection from Angular1)?

**Comment by mhevery** [comment] 2015-12-27 16:12
Yes, more clever change detection would solve it. But how much more clever.
The trouble with such approaches is that at some point you fall of the
clever cliff and you are surprised. No matter how clever you make it I can
construct a case where it would not be caught. Why stop with arrays? How
about objects as well. This is a very slippery slope, which leads to
performance problems and inconsistencies.

Going by references, is simple, fast, and most importantly predictable
(even if in some cases it is not what one would expect at the surface)

**Comment by andreev-artem** [comment] 2015-12-27 17:43
Hmm, as far as I understand you've already introduced ```IterableDiffer``` and ```KeyValueDiffer``` for ```ngFor``` and ```ngStyle``` respectively. Is that possible to use the same approach in the slice pipe case?

**Comment by mhevery** [comment] 2015-12-29 05:02
Yes, slice pipe can chose to properly implement it. (I think we should do
that) But it means each pipe which deal with arrays needs to worry about
it.

**Comment by mhevery** [comment] 2016-01-26 22:58
I think this has been resolved by the latest dev mode check and is closable.

**Closed by mhevery** 2016-01-26 22:58 UTC
Labels: flag: can be closed?

**Comment by cexbrayat** [comment] 2016-01-29 16:34
I still have unit tests failing in beta.2 (testing a component like the one described in #5948)

**Comment by tycho01** [comment] 2016-02-06 15:04
@vsavkin: I guess lodash's `_.eq()` would seem suitable to implement your proposed `listEq` pipe, generalized so as to handle objects and nested structures as well. But I'm not sure how to actually implement it though, as your proposal requires comparing to the previous value. From the [docs](https://angular.io/docs/ts/latest/guide/pipes.html) I wasn't aware of such info being available to pipes. Did I miss something? Otherwise, robianmcd's Pure pipe should help as well.

**Comment by skovmand** [comment] 2016-02-09 12:24
I had the problem with SlicePipe above with beta.2, but not in beta.3
