### ISSUE TITLE
Can't find a way to remove the auxiliary route from the window

### ISSUE THREAD

**Issue by yfain** [angular/angular#5122] opened 2015-11-04 15:59 UTC
After the auxiliary route is opened it remains on the window not matter what other router links are being clicked. It really behaves as an independent route.  What has to be done to a named route to remove it from the window?

The plunk with the AuxRoute Chat is here: http://plnkr.co/edit/jZv8jj?p=preview

This is related to the issue #5027

**Comment by yfain** [comment] 2015-12-02 16:10
Updated the plunk with the new syntax of aux router introduced in Alpha 47: <a href="http://plnkr.co/edit/n0IZWh?p=preview">http://plnkr.co/edit/n0IZWh?p=preview</a>

Still, there is no way to close the aux route. 
Also, why do I have to attach the aux route to the home component as in ['./Home', ['Chat']] ?

**Comment by antonmoiseev** [comment] 2015-12-16 16:10
https://github.com/angular/angular/pull/5930 eliminates the need to attach the auxiliary route to another route.

**Comment by red-0ne** [comment] 2016-03-07 06:40
Any workaround on how to get out from an auxiliary route?

**Comment by cwmrowe** [comment] 2016-03-29 14:23
Some advice on how to remove an aux route would be very much appreciated here too.

**Comment by vsavkin** [comment] 2016-07-28 23:01
You can remove a secondary/aux route by setting it to null, as follows:

```
router.navigate(['a', {outlets: {right: null}}]);
```

Closing this.

**Closed by vsavkin** 2016-07-28 23:01 UTC
Labels: comp: router

**Comment by RoyiNamir** [comment] 2017-05-08 22:14
@vsavkin Yeah but how would you do that in HTML ? In code it _works_ but in HTML it **doesn't**.
Here is a PLNKR . After AUX is set , using NULL doesn't clear the AUX route
[https://plnkr.co/edit/NaSnjDvXcW8zxpYuG04Y?p=preview](url)

**Comment by dietergeerts** [comment] 2017-05-12 12:51
Clearing the secondary just doesn't work by setting the outlet to null.

**Comment by unlight** [comment] 2017-06-09 23:11
For some reason (I do not know, it's a bug or by design), but I cannot clear children aux routes in child lazy loaded components.
`router.navigate([{outlets: {right: null}}]);` has no effect, url is not changing.

But this works, looks like a workaround:
```
this.router.navigate(['.', {outlets: {right: null}}], { relativeTo: this.activatedRoute.parent });
```

**Comment by jotatoledo** [comment] 2017-06-27 13:04
holy sh*t, @unlight you are my daily hero! Im either missing something or its plainly a bug. I had to change:

```
this._router.navigate([{ outlets: { popover: null } }], {
      relativeTo: this._route
    });

```
To:

```
this._router.navigate(['.', { outlets: { popover: null } }], {
      relativeTo: this._route.parent
    });
```

**Comment by fysp11** [comment] 2017-07-31 20:41
Any chances to use this workaround on template side?
Like:
`<a [routerLink]="['../',{ outlets: { more: null} }]">Back</a>`

**Comment by ericmarcos** [comment] 2017-10-06 14:59
@fysp11 I managed to get it working in my template like this:

`<a [routerLink]="[{outlets: {popup: null, primary: ['..']}}]">Back</a>`

**Comment by chriszrc** [comment] 2018-02-07 20:07
Setting the outlet value to null worked for me, as long as I didn't have two of the same outlets of the same name on the page (which I had hidden/shown at different viewports with angular flexbox). Is that a bug?

**Comment by dragGH102** [comment] 2018-03-22 15:32
@chriszrc I guess you can't have 2 outlets with the same name. Nonetheless, I got the same issue posted originally here while trying to put 2 routes on the same outlet

**Comment by sgentile** [comment] 2018-05-02 14:42
This worked for me
```
this.router.navigate(['.', { outlets: { myOutlet: null } }], { relativeTo: this.route.parent });
```
completely a hack but please don't change it and break my code - LOL

**Comment by nolafs** [comment] 2018-05-11 16:26
For some reason, on browser back history, the outlet gets enter state with an empty child router-outlet. Anybody has an idea how to get around this?

**Comment by jsdevtom** [comment] 2018-06-19 12:58
@unlight Thank you :tada: 
```
this.router.navigate([{ outlets: { modal: null }}], {relativeTo: this.activatedRoute.parent})
```
works where as 
```
this.router.navigate(['../', { outlets: { modal: null }}], {relativeTo: this.activatedRoute})
```
doesn't.

**Comment by operta** [comment] 2018-07-17 16:21
Nothing above worked for me. 
My solution
`    clearPopupOutlet() {
        setTimeout(() => {
            this.router.navigate([{ outlets: { popup: null } }])
                .then(() => window.history.back());
        }, 0);
    }`

**Comment by gabynevada** [comment] 2019-02-03 18:20
For me this works when I just want to remove the auxillary-route
```javascript
this.router.navigate([{ outlets: { popup: null } }]);
```

But if I try to navigate to a different route and remove the auxillary route this doesn't work
```javascript
this.router.navigate(['a', { outlets: { popup: null } }]);
```

As a workaround, I used a variant of @operta's solution
```javascript
this.router.navigate(['a']).then(() => this.router.navigate([{ outlets: { popup: null } }]));
```

**Comment by tibistibi** [comment] 2019-03-04 11:48
with the new version this does not work any more:

    this.router.navigate([{ outlets: { popup: null } }], { replaceUrl: true, queryParamsHandling: 'merge' });

but this works:

    this.router.navigate(['/client/declaration', { outlets: { popup: null } }]);

**Comment by gotwig** [comment] 2019-08-06 11:13
I tried your code : 

this.router.navigate(['/client/declaration', { outlets: { popup: null } }]);


however it doesnt change the url bar at all.

**Comment by vladimiry** [comment] 2019-08-06 12:21
What I noticed is that if lets say you have 3 outlets you can't null all of them, means Angular expect at least one outlet is always active. So introducing a 4th stub-like outlet is a workaround:
```javascript
[{
  outlets: {
    [ACCOUNTS_OUTLET]: null,
    [SETTINGS_OUTLET]: null,
    [NOTIFICATIONS_OUTLET]: null,
    [STUB_OUTLET]: STUB_PATH,
  },
}],
```
