### ISSUE TITLE
Router navigateByUrl documentation does not indicate that it ignores queryParams

### ISSUE THREAD

**Issue by Jaarx** [angular/angular#22668] opened 2018-03-09 00:39 UTC
This is a resubmission of issue [22611](https://github.com/angular/angular/issues/22611) because I don't have permissions to reopen.

Again, https://angular.io/api/router/Router#navigateByUrl

The above documentation gives no indication that it ignores the queryParams NavigationExtras value. There should be something that explicitly mentions NavigationExtras that do nothing.

For more details:
TL;DR at no point does a navigateByUrl extract any queryParams from the NavigationExtras

navigateByUrl itself at first only uses the URL as provided from the function call: https://github.com/angular/angular/blob/master/packages/router/src/router.ts#L452

When it goes to scheduleNavigation, the extras is passed along but nothing is done in scheduleNavigation with extras except passed to this.navigations.next(...): https://github.com/angular/angular/blob/master/packages/router/src/router.ts#L567

this.navigations is processed here: https://github.com/angular/angular/blob/master/packages/router/src/router.ts#L518

which calls executeScheduledNavigation: https://github.com/angular/angular/blob/master/packages/router/src/router.ts#L574

Notably at this point the only values from extras that this cares about is skipLocationChange and replaceUrl: https://github.com/angular/angular/blob/master/packages/router/src/router.ts#L586

**Comment by jenniferfell** [comment] 2018-05-24 22:36
filename=https://angular.io/api/router/Router#navigateByUrl

**Comment by csancs** [comment] 2018-07-20 09:17
There should be a different type for extras in navigateByUrl. Explicitly defining a type which allows to use params which will be ignored is let's say very loose type definition.

**Comment by EagleLizard** [comment] 2018-07-24 22:08
This should be made explicit in the docs. I wasted several hours trying to debug issues in a routing module, only to find out the issue is this silent ignore. 

At the very least `navigateByUrl` should throw an exception if the `queryParams` extra is supplied

**Comment by ajitsinghkaler** [comment] 2020-03-07 08:15
-- | --
NavigationExtras | An object containing properties that modify the navigation strategy. The function ignores any properties in the NavigationExtras that would change the provided URL.
-- | --

@kapunahelewong This has been documented. I think we can close this issue.

**Comment by kapunahelewong** [comment] 2020-03-10 18:16
Thanks, @ajitsinghkaler! Could you help me understand where it has been documented? I'm looking for `navigateByUrl()` and `NavigationExtras`, but I don't see new documentation.

**Comment by dabears318** [comment] 2020-06-28 05:22
I ran into this issue today.  there is no warning for typescript, I was able to specify queryParams without any detection.  moving to router.navigate() solved my problem.

**Comment by leopangchan** [comment] 2020-08-05 21:36
Hope this will get fixed soon. Took some time to configure it out.

**Comment by atscott** [comment] 2020-11-25 17:39
Closing as fixed in v11. The `navigateByUrl` now takes a `NavigationBehaviorOptions` object that only includes the properties that the function uses (and does not include `queryParams`): https://angular.io/api/router/NavigationBehaviorOptions

**Closed by atscott** 2020-11-25 17:39 UTC
Labels: comp: docs, comp: docs/api, comp: router, feature, subtype: docs-clarification
