### ISSUE TITLE
Forms emitEvent not respected

### ISSUE THREAD

**Issue by doender** [angular/angular#14668] opened 2017-02-23 09:50 UTC
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see 

* **Angular version:** 2.4.8
* **Browser:** [all | Chrome

Using 
```
this.control = new FormControl();

this.control.valueChanges.subscribe(value => {
   console.log("Value changed:", value);
});

this.observable.subscribe(object => {
   this.control.setValue(object.value, {emitEvent: false});
});

```

`valueChanges` it triggered when a new object is received. 

But this is not the intended behaviour, right?

**Comment by DzmitryShylovich** [comment] 2017-02-23 09:55
pls add a plunkr

**Comment by samalexander** [comment] 2017-02-23 12:34
We are experiencing similar issues, except for us emitEvent is not being respected by the enable and disable methods on form controls.

I have created a basic plunkr that reproduces the issue [here](https://plnkr.co/edit/UncBeSYarYslyHUjGUiv?p=preview). You will notice that emitEvent is respected by setValue() in this case, which is called by the button click. But changes to either inputs call the enable/disable logic, which causes the valueChanges subscription to fire (when it shouldn't).

**Comment by DzmitryShylovich** [comment] 2017-02-23 12:44
@doender can't reproduce http://plnkr.co/edit/BK5FZg8Ci6Iv7mKdUjLX?p=preview

**Comment by DzmitryShylovich** [comment] 2017-02-23 12:47
@samalexander https://plnkr.co/edit/QE2kcwbH7QOlEec7PeA9?p=preview

**Comment by samalexander** [comment] 2017-02-23 13:15
@DzmitryShylovich thanks, that works. The Angular docs don't state that both properties have to be set, unless I am missing something?

With regards to the original issue, on further investiagation, we are also seeing the issue with setValue triggering valueChanges in our project. We are running the latest version on Angular and Angular-Cli. However, I am so far unable to reproduce in a plunkr.

**Comment by DzmitryShylovich** [comment] 2017-02-23 13:20
> The Angular docs don't state that both properties have to be set

I'm not very familiar with the docs :) If you think that the docs can be improved then file an issue on https://github.com/angular/angular.io/issues

> I am so far unable to reproduce in a plunkr.

we can't do much without a repro

**Comment by doender** [comment] 2017-02-23 13:40
Strangely I couldn't reproduce it in a plunkr. I now suspect it specifically has to do with this Material component I am using: https://material.angular.io/components/component/button-toggle

**Comment by DzmitryShylovich** [comment] 2017-02-24 21:14
@doender close the issue pls as it's not reproducible. thx

**Closed** 2017-03-05 22:23 UTC
