### ISSUE TITLE
*ngIf on (or above) element using route animation causes ExpressionChangedAfterItHasBeenCheckedError

### ISSUE THREAD

**Issue by fxck** [angular/angular#36222] opened 2020-03-24 11:54 UTC
# 🐞 bug report

### Description
Following the route animation tutorial https://angular.io/guide/route-animations I'm getting 

> ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value for '@outerRouteAnimation': 'undefined'. Current value: 'hello'.

When I put `*ngIf` anywhere above the animation definition.

ie.:

```html
<div *ngIf="visible$ | async">
  <div [@outerRouteAnimation]="prepareRoute(outlet)">
    <router-outlet #outlet="outlet"></router-outlet>
  </div>
</div>
```

## 🔬 Minimal Reproduction
Not reproducible on stackblitz, here's minimal repro repo https://github.com/fxck/angular-animation-cd-bug

## 🌍  Your Environment

**Angular Version:**
Latest next 9.

**Comment by JoostK** [comment] 2020-03-24 12:15
Looks like a duplicate of #36173.

**Comment by atscott** [comment] 2020-03-24 22:35
Agreed, closing this as duplicate of #36173.

**Closed** 2020-03-24 22:35 UTC
Labels: comp: router
