### ISSUE TITLE
Angular service worker breaks file upload on Safari

### ISSUE THREAD

**Issue by aSegatto** [angular/angular#24853] opened 2018-07-12 13:02 UTC
## I'm submitting a...

<pre><code>
[ ] Regression 
[x] Bug report 
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
On safari (both mobile and desktop) uploading a file to firebase storage with ngsw enabled causes an error. Upload works correctly on the other browsers or with service worker disabled.

## Minimal reproduction of the problem with instructions

We built a demo project in order to demonstrate the issue. You can find the source code at this [url](https://github.com/aSegatto/ngsw-bug) and the deployed application is availlable at this [url](https://ngws-bug.firebaseapp.com/). Basically we are uploading a text file containing timestamp to firebase storage:

<pre><code>
   const content = 'This is my blob content ' + new Date();
   const blob = new Blob([content], {type: 'text/plain'});
    const metadata = {
      'contentType': blob.type
    };
    firebase.storage().ref('blob').put(blob, metadata)
</code></pre>

the application is built using angular cli with built in service worker support. Ngsw config should not allow service worker to cache any of the firebase data and is correctly working on all browsers.
<pre><code>
"dataGroups": [
    {
      "name": "firebase",
      "urls": [
        "https://firebasestorage.googleapis.com/**"
      ],
      "cacheConfig": {
        "timeout":"10s",
        "maxSize": 10,
        "maxAge": "1s",
        "strategy": "freshness"
      }
    }
  ]
</code></pre>
the application correctly uploads the file on the other browsers , but on safari we get this error : 

> Multipart body does not contain 2 or 3 parts. 

We also run into a similar error regarding multipart and offset when trying to upload an image.

## Environment

<pre><code>
Angular Cli version: 6.0.8
Angular Service Worker version: 6.0.7

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [x] Safari (desktop) version 11.1
- [x] Safari (iOS) version 11.4.1
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.11.3  
- Platform:  Mac 

Others:

</code></pre>

**Comment by gkalpak** [comment] 2018-07-12 14:53
Closing as a duplicate of 23244. It seems to be the same underlying issue.

**Closed by gkalpak** 2018-07-12 14:53 UTC
