### ISSUE TITLE
docs: css selector definition location suggestion

### ISSUE THREAD

**Issue by SandeepBhartiya** [angular/angular#52741] opened 2023-11-09 17:09 UTC
### Describe the problem that you experienced

When I am going through new documentation of angular 17 . I Came to know that in the Component Section of Documentation at the Start of Anatomy of Components, a field is defined more than once time and I think that is a little bug.

"A [CSS selector] that defines how the component is used in HTML"

This is the text which is defined more than one time so I thought I should let you know and it is at the start of the components definition.

### Enter the URL of the topic with the problem

https://angular.dev/guide/components

### Add a screenshot if that helps illustrate the problem

![image](https://github.com/angular/angular/assets/101499022/c5cc5e4d-7c61-4fe6-bb6a-bddfd56ac602)

**Comment by Gortyser** [comment] 2023-11-09 17:16
Duplicate of https://github.com/angular/angular/issues/52575
Fixed in https://github.com/angular/angular/pull/52587

**Comment by JoostK** [comment] 2023-11-09 17:58
> Duplicate of #52575 Fixed in #52587

Thanks, I was looking for those.

Thanks for the report @SandeepBhartiya!

**Closed by JoostK** 2023-11-09 17:58 UTC
Labels: area: adev-docs
