### ISSUE TITLE
ngIf="false" will prevent transition(":leave") animation

### ISSUE THREAD

**Issue by diverent2** [angular/angular#30732] opened 2019-05-29 16:51 UTC
# 🐞 bug report

This ticket summarizes my findings to the issue described bellow.
I´m aware that there are similar reports already, but none of them quite fit my problem.

### Affected Package

The issue is **likely** caused by package @angular/animations

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ` 7.2.7` according to [this comment](https://github.com/angular/angular/issues/29509#issuecomment-477997630):
Downgrading didn´t fix it for me though.

### Description

I´m trying to add and remove an element to the DOM using `*ngIf="someValue"`.
I want to be able to play a fade-in animation using `[@animation]` when it get´s added to the DOM-tree. 
This works fine using 
```
trigger('animation', 
transition(":enter", [...])
)
```
 👍 

According to https://angular.io/guide/animations this _should_ work for `:leave` too.

> For elements entering or leaving a page (inserted or removed from the DOM), you can make the animations conditional. For example, use *ngIf with the animation trigger in the HTML template.

Sadly, it doesn´t. 👎 

According to this old [Stackoverflow post](https://stackoverflow.com/questions/36417931/angular-2-ngif-and-css-transition-animation)
> *ngIf removes the element from the DOM when the expression becomes false. You can't have a transition on a non-existing element.

❓ If that´s the case, `:leave` (`* => void`) wouldn´t work at all? 
Am I missing something or is it a bug?

## 🔬 Minimal Reproduction

Will follow 🤷‍♀ 

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 7.3.9
Node: 10.15.3
OS: darwin x64
Angular: 7.2.15
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.9
@angular-devkit/build-angular     0.13.9
@angular-devkit/build-optimizer   0.13.9
@angular-devkit/build-webpack     0.13.9
@angular-devkit/core              7.3.9
@angular-devkit/schematics        7.3.9
@angular/cdk                      7.3.7
@angular/cli                      7.3.9
@angular/material                 7.3.7
@angular/pwa                      0.12.4
@ngtools/webpack                  7.3.9
@schematics/angular               7.2.4
@schematics/update                0.13.9
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.29.0

</code></pre>

**Anything else relevant?**
Possibly related issues: #29509, #29496

**Comment by diverent2** [comment] 2019-05-29 16:59
https://github.com/angular/angular/issues/15798#issuecomment-305934289
Describes a workaround. If that´s the way to go, the docs should be updated accordingly 😃

**Comment by Ocean-Blue** [comment] 2020-06-19 19:15
Any update about this issue? I am on version 9.1.10, and seems like the issue still exists.

**Comment by ElecTreeFrying** [comment] 2021-06-29 10:22
bump. any update ?

**Comment by 2martens** [comment] 2021-08-25 12:18
This issue seems to persist even in Angular 12. In my case the ngIf is on the div of the animation. But only the enter animation is played. 

Layout:
```html
<section *ngFor="let item of items; let idx = index">
  <div>
    <button (click)="toggleOpen(idx)">Button</button
  </div>
  <div *ngIf="isOpen(idx)" @ngIfAnimation>
  <!-- content -->
  </div>
</section>
```

**Comment by dario-piotrowicz** [comment] 2021-12-03 22:41
Hi @diverent2, I believe this is the exact problem that also the issues you mentioned in you description (#29509, #29496) refer to.

I commented on those issues that the behaviour there was the expected one, I think that `:leave` can be a bit tricky to grasp and that this issue you are describing can also be the same.

You can check my comments in those issues, but tldr not all elements leaving the dom are considered for `:leave` transitions/queries, so you need to be careful (one quick rule of thumb is to have your `*ngIf` and trigger on the same element) 

I hope this helps :slightly_smiling_face: 
___

I don't think that anything can be done in this issue since it doesn't have a minimal reproduction and what it is describing is too vague and can very easily relate to something working as expected (but not clearly documented)

If possible I would suggest to close this issue as it is either working as expected or it is a duplicate of the other two (or if you really believe that it is something different I think that a minimal reproduction is very much necessary here)

**Comment by jessicajaniuk** [comment] 2021-12-13 22:11
It appears this behaves as expected, but as @dario-piotrowicz, it's not the clearest on how this works in the documentation. We have an [issue open to track that documentation problem](https://github.com/angular/angular/issues/44253). If you still feel there is an issue, please re-open this issue or provide further details in a new issue.

**Closed by jessicajaniuk** 2021-12-13 22:11 UTC
Labels: type: bug/fix, comp: animations, freq2: medium, regression, P2
