### ISSUE TITLE
Object spread in environment files fails for production configuration when used in modules

### ISSUE THREAD

**Issue by dougpool** [angular/angular#28078] opened 2019-01-11 14:41 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/core and maybe @angular/cli

### Is this a regression?

No, however this issue was also present in angular 7.1.x

### Description

Environment files that are composed using the spread operator do not work when used in a production configuration (`ng serve|build -c production`). When attempting to pass environment to a module via forRoot (see example below), the environment being passed to the module is missing the environment properties that should have been copied via the object spread operator.

Note that Object.assign does not work as well.

## 🔬 Minimal Reproduction

Step 1: Clone https://github.com/dougpool/aot-prod-env
Step 2: `ng serve -c dev` and check screen/console (works as desired)
Step 3: `ng serve -c production` and check screen/check console (missing common env message is the bug)

## 🔥 Exception or Error

See project README.md for detailed expected output and examples

Environment files composed from other files should work in production mode and have properties copied into environment via the object spread operator and the environment is passed to another module

common-env.ts
```
export const commonEnv = {
  // Are we running in production mode
  production: false,

  // common mesg
  commonMessage: 'Seen by all envs',
};
```

environment.prod.ts
```
import * as common from './common-env';

export const environment = {
  ...common.commonEnv,
  production: true,
  envMessage: 'Prod message',
};
```
Code where correct environment fails to get created
app.module.ts snippet
```
@NgModule({
  declarations: [AppComponent],
 // env here is not correct
  imports: [BrowserModule, FeatureModuleModule.forRoot(env)],
  providers: [],
  bootstrap: [AppComponent],
})
```
Instead, the properties are not copied when the the application is served or built with the `ng` command.

## 🌍  Your Environment

**Angular Version:**
<pre><code>

```
Angular CLI: 7.2.1
Node: 10.15.0
OS: darwin x64
Angular: 7.2.0
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.12.1
@angular-devkit/build-angular     0.12.1
@angular-devkit/build-optimizer   0.12.1
@angular-devkit/build-webpack     0.12.1
@angular-devkit/core              7.2.1
@angular-devkit/schematics        7.2.1
@angular/cli                      7.2.1
@ngtools/webpack                  7.2.1
@schematics/angular               7.2.1
@schematics/update                0.12.1
rxjs                              6.3.3
typescript                        3.2.2
webpack                           4.23.1
```

</code></pre>

**Anything else relevant?**

Initially opened a bug with angular cli and the said to open it here
Ref: https://github.com/angular/angular-cli/issues/13413

**Comment by dougpool** [comment] 2019-01-11 16:45
If so, then why does the design allow it work for the dev configuration (or a non-production) configuration? It works just fine, but if the angular.json have the `"buildOptimizer": true,` and `"aot": true` , then it stops working.

**Comment by alan-agius4** [comment] 2019-01-11 16:48
Cause for prod and dev we use 2 different compilers.

Production (AOT) uses the ngc compiler, while for development (JIT) the tsc
compiler is used.

**Comment by pkozlowski-opensource** [comment] 2019-01-11 16:59
So as @alan-agius4 pointed out we've got slightly different compilation pipelines for the JIT (dev) and AOT (prod) mode. There are technical and historical reasons for this but this is very confusing (and a common source of problems) for the users.

I'm going to create a dedicated issue to track all places where people fail into the same trap - keeping it open till then.

**Comment by dougpool** [comment] 2019-01-11 17:00
ahh..2 different compilers at play then. 

Any other recommendations on how to have 'common' environment info that is shared between different types of build configurations like I am trying to do so that I don't have to repeat 95+% of the same information in different files and being able to pass it via a module import forRoot()? Otherwise it seems for any imported module that wants information pass via its forRoot(), for it to work in aot mode, that information needs to come from a 'flat' environment file.

Thanks for the update

**Comment by alan-agius4** [comment] 2019-01-11 17:07
I think if you remove the namespace it should work.


I cannot try and confirm at the as I am on my mobile.

Basicilly instead of

```
Import * as x from './foo';
```

Use

```
Import { foo } from ‘./foo’;
```

**Comment by dougpool** [comment] 2019-01-11 18:00
definitely gets me closer, still can't use the object spread operator, but I can work around that with some restructuring of the common properties file. Thanks again

**Comment by alexzuza** [comment] 2019-01-11 20:28
Angular doesn't resolve spread operator in object literal when resolving metadata.

```
{
  ...common.commonEnv, // ts.SyntaxKind.SpreadAssignment
  production: true,
  envMessage: 'Prod message',
};

```
https://github.com/angular/angular/blob/091a8a6fd590c69b87e7244193c384d2d4f184db/packages/compiler-cli/src/metadata/evaluator.ts#L285-L314

But it does supports spread operator in literal array.
https://github.com/angular/angular/blob/091a8a6fd590c69b87e7244193c384d2d4f184db/packages/compiler-cli/src/metadata/evaluator.ts#L332

There is also documentation about limited syntax:
https://angular.io/guide/aot-compiler#expression-syntax

**Comment by mhevery** [comment] 2019-01-15 23:21
1) this is a feature request.
2) Works as intended
3) Fixed in Ivy

**Closed by mhevery** 2019-01-15 23:21 UTC
Labels: comp: core & compiler, fixed by Ivy, freq1: low, severity1: confusing
