### ISSUE TITLE
Does zone.js not support await?

### ISSUE THREAD

**Issue by yp-wang** [angular/angular#32829] opened 2019-09-24 11:16 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/zone.js

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

when the nodejs app use `await`, then the zone runs unexceptly.

## 🔬 Minimal Reproduction

when I run the code like this:
```js
// =>test.js
require('zone.js');

const service = async function () {
  return 123;
}

const controller = async function () {
  await service();
  console.log(Zone.current.name)
};

const koaZone = Zone.current.fork({
  name: 'koa',
});

koaZone.run(async () => {
  await controller();
});
```
the result of this app is :
```bash
[user]$ node test.js
<root>
```
But isn't it should be "test"?

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

</code>"zone.js": "^0.10.2"</pre>

**Anything else relevant?**

**Comment by trotyl** [comment] 2019-09-24 12:20
Duplicate of https://github.com/angular/angular/issues/31730

**Comment by AndrewKushnir** [comment] 2019-09-24 17:17
@yp-wang thanks for reporting this issue. However this issue is a duplicate of an existing issue #31730. Please subscribe to that issue for future updates. Thank you.

**Closed by AndrewKushnir** 2019-09-24 17:17 UTC
Labels: comp: zones
