### ISSUE TITLE
Document compiler flag `fullTemplateTypeCheck` (at least in Release Notes)

### ISSUE THREAD

**Issue by alan-agius4** [angular/angular#19681] opened 2017-10-12 09:08 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
In my html view I am referring a variable that it doesn't exist,  This won't be catched unless someone consumes my library.

I am using NGC bin directly to compile my TS to NGC.

```ts
@Component({
	template: `<div *ngIf="isDisabled === true"></div>`
})
export class MainComponent  {

}
```
in the ngfactory.ts I can see that there is an error, however this is not emitted on compilation

```ts
const currVal_0:any = (_co.isDisabled === true);
```

![image](https://user-images.githubusercontent.com/17563226/31488328-9b9f9874-af3d-11e7-94d3-e2a1669268c2.png)

## Expected behavior
When compiling with NGC it should throw an error while compiling

## Minimal reproduction of the problem with instructions
https://github.com/alan-agius4/angular-ngc-template-error

## What is the motivation / use case for changing the behavior?
It should throw an error

## Environment

<pre><code>
Angular version: 4.4.4
</pre></code>
 
For Tooling issues:
- Node version: 8.1.0
- Platform:  Windows

Others:

</code></pre>

**Comment by tbosch** [comment] 2017-10-13 15:06
We have a new compiler setting called `fullTemplateTypeCheck` (see https://github.com/angular/angular/blob/master/packages/compiler-cli/src/transformers/api.ts#L99) which will reveal this error.

This setting will become the default in Angular 6, and is highly recommended. We didn't turn in on in Angular 5 to not break existing users. I.e. the behavior you are seeing here is exactly what users saw in Angular 4.

This works as intended, but somehow we forgot to document this. Keeping the bug open to track that we need to document this.

**Comment by tbosch** [comment] 2017-10-13 15:09
Oh, there is a bug with `fullTemplateTypeCheck` right now, which will be fixed via https://github.com/angular/angular/pull/19582.

**Comment by alan-agius4** [comment] 2017-10-13 15:12
The flag is only available in Angular 5 or later?

**Comment by tbosch** [comment] 2017-10-13 18:52
Yes

**Comment by tbosch** [comment] 2017-10-27 15:58
We should first rollout `fullTemplateTypeCheck` in G3 before we document it though (see https://github.com/angular/angular/issues/19792).

**Comment by chuckjaz** [comment] 2018-02-06 23:57
`fullTemplateTypeCheck` is not documented.

**Closed by chuckjaz** 2018-02-06 23:57 UTC
Labels: PR state: blocked, comp: core & compiler, comp: docs, freq2: medium, severity3: broken, type: docs

**Comment by mgol** [comment] 2018-02-08 11:24
Why was this closed?

**Comment by devoto13** [comment] 2018-02-08 11:36
@mgol It was documented some time ago: https://angular.io/guide/aot-compiler#fulltemplatetypecheck

**Comment by mgol** [comment] 2018-02-08 11:45
Hmm, OK. I wonder why @chuckjaz wrote it's not documented just before closing then.

**Comment by trotyl** [comment] 2018-02-08 13:31
@mgol  I guess it should be "`fullTemplateTypeCheck` is **now** documented." rather than "`fullTemplateTypeCheck` is **not** documented.", common typos. 😃

**Comment by chuckjaz** [comment] 2018-02-08 16:12
Sorry. Yes. It is **now** documented. Sorry for the typo.

**Comment by kimamula** [comment] 2018-07-27 02:37
> This setting will become the default in Angular 6

Has this already done?
[The doc](https://angular.io/guide/aot-compiler#fulltemplatetypecheck) still says that this option is `false` by default and will default to `true` in the future.
