### ISSUE TITLE
Updating queryParams does not work as expected unless you copy it by value

### ISSUE THREAD

**Issue by stonetwig** [angular/angular#48712] opened 2023-01-12 10:08 UTC
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

No

### Description

Hello dear Angular devs,

Thanks for doing great work!

I have an issue that occurs whenever I want to update just the queryParams on a route and trigger a router event.
When the queryParams array gets additions and when I trigger a `router.navigate` event it won't update the queryParams unless I copy the array by value first, then it works as expected.

I assume this is a bug because the behavior is quite weird, I haven't found it documented anywhere and it took me a long time to find this out.

```
async updateQueryParam() {
    let routeQP: string | string[] =
      this.route.snapshot.queryParams['qp'] ?? [];
    if (routeQP instanceof Array === false) routeQP = [routeQP as string];
    // If the below is not added, query params will not always change with navigation
    //routeQP = [...routeQP];

    (routeQP as string[]).push(`Param ${this.count}`);
    this.count += 1;

    console.log('New params', routeQP);
    this.router.navigate([], {
      relativeTo: this.route,
      queryParams: {
        qp: routeQP.length > 0 ? routeQP : undefined,
      },
      queryParamsHandling: 'merge',
      //skipLocationChange: true
    });
```

If you uncomment the `routeQP = [...routeQP];` line, it works as expected and if you leave the comment there the router won't trigger an update.

The stackblitz doesn't seem to work for some reason, but you may download the example or copy the simple example to a new app and you may see the issue reproduced.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-f8chcv?file=src/app/app.component.ts

### Please provide the exception or error you saw

```true
No error or exception, the query params just doesn't update.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.0.5
Node: 18.12.1
Package Manager: npm 8.19.2
OS: win32 x64

Angular: 15.1.0
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1501.0
@angular-devkit/build-angular   15.1.0
@angular-devkit/core            15.1.0
@angular-devkit/schematics      15.0.5
@angular/cli                    15.0.5
@schematics/angular             15.0.5
rxjs                            7.5.7
typescript                      4.8.4
```

### Anything else?

Keep doing great work! :)

**Comment by atscott** [comment] 2023-01-13 15:10
Though it might surprise you, this is a duplicate of #27528. Because you're modifying the actual router state in this case, when the router goes to check if the requested navigation is the same as the current one, it thinks that it is and skips it. 

There are a couple new features in 15.1 that help you with this: 
1. When debugging, the new `NavigationSkipped` event will emit (you'll see this here)
2. You can also get around this problem by setting `onSameUrlNavigation: 'reload',` in the `NavigationExtras` of the `navigate` command

That said, your best option is probably just copying the array like you have.

**Closed by atscott** 2023-01-13 15:10 UTC
Labels: area: router
