### ISSUE TITLE
Forms: Changing form control does not update disabled state of HTMLElement

### ISSUE THREAD

**Issue by bertofer** [angular/angular#15206] opened 2017-03-16 15:42 UTC
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When  the form control of an input is changed (e.g. async pipe), the HTML element disabled property is not properly updated to the one on the new form control.

**Expected behavior**
The HTMLElement disabled property should be synchronised with the one of the corresponding FormControl associated.

**Minimal reproduction of the problem with instructions**
Here's a plunkr https://plnkr.co/edit/WL7DjZHHmzLR8o5NBO1R?p=preview

**What is the motivation / use case for changing the behavior?**
We use dynamic forms with a BehaviorSubject of the formGroup to use. When new forms are pushed, all the values work fine, but the disabled properties don't get updated properly.

**Please tell us about your environment:**
Mac OS X 10.12.3

* **Angular version:** 2.4.9
Happens in 2.4.9. Will check in current 4RC now and update the issue.

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
 
* **Language:** TypeScript 2.0.2

**Comment by DzmitryShylovich** [comment] 2017-03-16 16:12
Use `formControl` instead of `formControlName` as a workaround

**Comment by bertofer** [comment] 2017-03-17 10:12
Hi @DzmitryShylovich , I could not understand why your solution was working on the plunkr, but not on my project code! I have realized it: It only works from enabled to disabled, but not otherwise: 

Here is the plunkr using [formControl] that does not work -> https://plnkr.co/edit/koBYzM1WFXOEc7FkryTZ

Digging more into the code, I have seen this line:
https://github.com/angular/angular/blob/master/packages/forms/src/directives/reactive_directives/form_control_directive.ts#L91

Here I see that the disabled is being checked and applied on the valueAccessor, but there is no opposite check -> That if it was disabled but now enabled, setDisableState of valueAccessor should be set to true again.

I'd separate the following if:
```
if (this.control.disabled && this.valueAccessor.setDisabledState) {
  this.valueAccessor.setDisabledState(true);
}
```
into: 

```
if (this.valueAccessor.setDisabledState) {
  if (this.control.disabled) {
    this.valueAccessor.setDisabledState(true);
  } else {
    this.valueAccessor.setDisabledState(false);
  }
}
```

If this looks a reasonable solution, I'd be glad to open a PR with it,

**Comment by sonictruth** [comment] 2017-05-12 08:30
Hi,

I made another plnkr to illustrate the bug:
https://plnkr.co/vT8x0kJCGTc2WyCSsi1X

The issue is that when a new FormGroup is created it's reusing the old formControlName directives.


The update happens in:
FormGroupDirective._updateDomValue ->setUpControl

Validators and Value are updated but not the state (enabled/disabled).

```
 control.validator = Validators.compose([control.validator !, dir.validator]);
 control.asyncValidator = Validators.composeAsync([control.asyncValidator !, dir.asyncValidator]);
 dir.valueAccessor !.writeValue(control.value);
```

**Comment by sonictruth** [comment] 2017-05-12 14:34
As a workaround you can update the directives manually after you change the formgroup


```
  @ViewChildren(FormControlName) formControlDirectives: QueryList<FormControlName>;

  [....]

   this.myFormGroup =  this.formBuilder.group(config);

    setTimeout(() => {
      this.formControlDirectives.forEach(formControl => {
        if (formControl.valueAccessor.setDisabledState) {
          formControl.valueAccessor.setDisabledState(formControl.disabled);
        }
      });
    }, 0);

```

**Comment by josh18** [comment] 2017-08-16 23:27
As a workaround I created a directive to pass on the disabled state. Something like:

```
import { Directive, DoCheck, Optional } from '@angular/core';
import { NgControl } from '@angular/forms';

@Directive({
    selector: 'input, textarea, select'
})
export class ReactiveDisabledDirective implements DoCheck {
    constructor(@Optional() private control: NgControl) {}

    ngDoCheck(): void {
        if (this.control) {
            this.control.valueAccessor.setDisabledState(this.control.disabled);
        }
    }
}
```
I'm not very experienced with Angular so there might be a better way to do it but it does seem to work.

**Comment by kara** [comment] 2017-12-12 23:19
Looks like a duplicate of https://github.com/angular/angular/issues/17806

**Closed by kara** 2017-12-12 23:19 UTC
Labels: comp: forms, type: bug

**Comment by LisaTatum** [comment] 2018-03-08 21:09
This bug report is from march 2017, your duplicate link from June 2017. Why close the older one???

**Comment by narthur157** [comment] 2018-09-25 19:42
> Use `formControl` instead of `formControlName` as a workaround

This works
