### ISSUE TITLE
deprecated package document-register-element

### ISSUE THREAD

**Issue by dulajkavinda** [angular/angular#40910] opened 2021-02-18 17:17 UTC
@angular/elements still adds this to element project.

Recommendation now is to use [https://www.npmjs.com/package/@ungap/custom-elements](https://www.npmjs.com/package/@ungap/custom-elements)

Does @angular/elements need to be updated?

**Comment by gkalpak** [comment] 2021-02-18 17:40
> Does @angular/elements need to be updated?

It might (although I am not sure what are the pros and cons of the different polyfills available 😅).
Closing as a duplicate of #40270.

**Closed by gkalpak** 2021-02-18 17:40 UTC
