### ISSUE TITLE
Internet Explorer 11 Datepipe (recurring)

### ISSUE THREAD

**Issue by itsnotvalid** [angular/angular#19365] opened 2017-09-25 07:40 UTC
## I'm submitting a...

<pre><code>
[x ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

See: #9524 , #10147 

`Exception: InvalidPipeArgument: '2017-09-25 11:27:00:00.000000' for pip 't'`

(prod code generated using `ng build --prod`)
## Expected behavior

No error.

## Minimal reproduction of the problem with instructions

`{{date | date: 'yyyy-MM-dd HH:mm:ss' || 'N/A'}}`
## Environment

<pre><code>
Angular version: 4.4.3

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [x] IE version 11 or below
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.5.0  
- Platform:  Windows

Others:

</code></pre>

**Comment by vicb** [comment] 2017-09-26 16:49
Assigning to @ocombe that has been working on the i18n pipes.

The short story is that the 4.x pipes relies on the Intl API which is broken on some browsers. 
Angular 5.x will come which much more robust pipes that are independent of the Intl API.

**Comment by ocombe** [comment] 2017-09-26 16:54
You flagged this as a regression, in what version was it working previously?

**Comment by ocombe** [comment] 2017-11-03 09:16
Closing this since there was no activity and we believe this is fixed in v5. Let us know if we should reopen it.

**Closed by ocombe** 2017-11-03 09:16 UTC
Labels: comp: i18n, type: bug
