### ISSUE TITLE
routers resolve don't work with a BehaviorSubject

### ISSUE THREAD

**Issue by mxii** [angular/angular#14614] opened 2017-02-21 08:04 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

App doesn't start.
Resolve isn't working.

**Expected behavior**

Should work. :)

**Minimal reproduction of the problem with instructions**
https://plnkr.co/edit/XmjC2rJ20VQWCsfncVIc?p=preview

```
        return this._data.delay(1000); // <-- won't work .. maybe an angular bug !!
        return Observable.of(['test']);
```

With the second line it will work.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
don't care, doesn't work even in a plunker..

* **Angular version:** 2.0.X
2.4.8 and 3.4.8

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
tested with Chrome.

**Comment by DzmitryShylovich** [comment] 2017-02-21 08:09
You need to complete the stream https://plnkr.co/edit/yEtDi6s66UiTDHlxyr8O?p=preview

**Comment by DzmitryShylovich** [comment] 2017-02-24 21:27
@mxii close the issue as it's not a bug pls, thx

**Comment by DzmitryShylovich** [comment] 2017-03-10 07:46
@pkozlowski-opensource works as intended

**Comment by pkozlowski-opensource** [comment] 2017-03-13 16:29
Thnx @DzmitryShylovich

**Closed by pkozlowski-opensource** 2017-03-13 16:29 UTC
