### ISSUE TITLE
Backward-referenced transplanted views and ChangeDetectionStrategy.OnPush are not fully supported

### ISSUE THREAD

**Issue by DavidANeil** [angular/angular#49801] opened 2023-04-12 07:00 UTC
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

Transplanted views (templates that are rendered into a different component than where they are declared) do not function properly when the declaration occurs _after_ the insertion point in the change detector tree.

They almost always require `checkNoChanges` to be disabled, or else they will throw an `ExpressionChangedAfterItHasBeenCheckedError`.  This happens when the inserted view is not dirty, so it is skipped during `detectChanges`,  but then the declaration-owning view _is_ checked, which calls `markTransplantedViewsForRefresh`.

On the following `checkNoChanges` run, it _will_ check the transplanted view, which means any binding expression change will result in a `ExpressionChangedAfterItHasBeenCheckedError`.

To reproduce:
Remove the `false` from the `fixture.detectChanges` [here (line 403)](https://github.com/angular/angular/blob/f9b821f07d8dba57a6a7e5fc127dc096247424aa/packages/core/test/acceptance/change_detection_transplanted_view_spec.ts#L403).https://github.com/angular/angular/blob/f9b821f07d8dba57a6a7e5fc127dc096247424aa/packages/core/test/acceptance/change_detection_transplanted_view_spec.ts#L403

**Comment by pkozlowski-opensource** [comment] 2023-04-12 08:59
@DavidANeil could you please share a minimal stackblitz with the exact scenario where you run into the error? 

I _suspect_ that it is a duplicate of #15634 but it is hard to confirm without the exact reproduce.

**Comment by DavidANeil** [comment] 2023-04-12 17:53
Is the modification to the checked-in test not sufficient to reproduce it?

It is not quite the same as https://github.com/angular/angular/issues/15634, as that seems to be about the _first_ change detection.  Which has the workaround of just calling `.detectChanges()` immediately after `viewContainerRef.createEmbeddedView`.

The issue I am seeing is that even after doing that workaround, any future change detections are still liable to throw a `ExpressionChangedAfterItHasBeenCheckedError`, which is what the test hits.

**Comment by atscott** [comment] 2023-04-13 05:03
This is absolutely correct and was a design choice to not support it, partially because this was how it worked since the View Engine days (pre-version 9). You can see this mentioned in several places in the spec file you linked. This will probably not be changed for OnPush/CheckAlways components but will likely be addressed in signal components. 

Making backwards updates in the change detection is fundamentally not supported in today’s top-down, single pass approach.

**Comment by DavidANeil** [comment] 2023-04-13 05:33
Would a workaround like disabling checking transplanted views during a checkNoChanges pass work?

**Closed** 2023-10-24 21:50 UTC
Labels: area: core, core: change detection, P5
