### ISSUE TITLE
Unable to keep CSS3 animation in component go on when component is hidden

### ISSUE THREAD

**Issue by jamesharvey2** [angular/angular#21580] opened 2018-01-17 02:52 UTC
## I'm submitting a...

[ ] Regression (a behavior that used to work and stopped working in a new release)
[ X ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see 

## Current behavior

When a component is nested as an *ngIf tab menu inside a parent HTML, it loses its CSS3 animation progress on navigation. 
I'm working on a project which has a parent HTML and several angular components called up as tab div using *ngIf. 
I have CSS3 animation inside one of the components. The CSS3 animation can be triggered using a start button which dynamically adds CSS3 animation to a target div. 
When I navigate to other component div after starting this animation, the component automatically stops CSS3 animation. It should be triggered again using start button. 
So I think Angular is set to remove CSS3 animation when containing html file is hidden from display. 

## Expected behavior

Angular will not lose CSS3 animation progress inside component div while navigating within parent HTML. It should be running CSS3 animation in background or at least give an option to do that. 

## Minimal reproduction of the problem with instructions

It's really simple to replicate this problem.

1. Create an angular project.
2. Create two components.
3. Call up two component inside main html using angular selectors
4. Create buttons in main html and use *ngIf  directive to dynamically show & hide two components.

5. Inside one of components SCSS, create any random CSS3 animation class which can be added using a button with [ngClass].
6.Set target div for animation inside component html. 
7.Start animation using that button

8. Open other component using main html page's button.
9. Open up the previous component which has animation.
10. You'll find the animation has automatically stopped.  

## What is the motivation / use case for changing the behavior?

I'm trying create a media playback progress bar using CSS3. and my application has several components which can be shown or hidden using *ngIf directive and buttons. 
I want to keep CSS3 animation running in background even when I'm navigate other components. 

## Environment

Angular 4

Browser:
- [ X ] Chrome (desktop) version XX
- [ X ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ X ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version:  6
- Platform:  Windows

**Comment by ChenJunhan** [comment] 2018-01-17 03:33
It might help you. [https://angular.io/guide/animations](https://angular.io/guide/animations)

**Comment by ericmartinezr** [comment] 2018-01-17 10:30
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by jamesharvey2** [comment] 2018-01-17 21:24
Hi sir, 

This is close to a bug because there seems to be no solution to this problem yet.

I tried this with both Angular Animations and CSS3 animations.

When animation is happening inside a component and the component's display is set to none, the animation will automatically stop. When you re-visit that component, everything will be set to default. This is a problem for me. I'm trying to keep the animation going in background while the component is hidden from display.

Any idea?

**Comment by jamesharvey2** [comment] 2018-01-17 21:54
Any solution would be appreciated!

**Comment by ericmartinezr** [comment] 2018-01-17 22:37
If you're certain this is a bug it would be really nice of you to respect the issue template (the one you deleted) and fill it with the information required, especially the minimal reproduction of the bug.

**Comment by jamesharvey2** [comment] 2018-01-17 23:14
Ok, I added the template! 
Please review this problem and if there's a solution, please let me know. Thanks,

**Comment by matsko** [comment] 2018-05-01 22:46
@jamesharvey2 please put together a https://stackblitz.com example so we can investigate.

**Comment by jamesharvey2** [comment] 2018-05-02 00:52
I will do that soon.  Angular animations, CSS3 animations inside a div tabs using *ngIf will automatically reset when they're not selected. 
I found this to be not helpful at all. There should be a way to keep the animation going in background.. otherwise animation will reset every time you visit the div. 

Thanks,

**Comment by jelbourn** [comment] 2020-10-26 20:36
Closing since I believe this is working as expected. `ngIf` removed hidden elements from the DOM completely, so it is expected that the animation progress would be lost. You can alternatively hide your elements a different way to get the behavior you want (though I'm not sure off the top of my head which approach would be best for this).

**Closed by jelbourn** 2020-10-26 20:36 UTC
Labels: comp: animations, freq1: low, type: bug/fix
