### ISSUE TITLE
Signals guide in angular.dev renders <canvas> differently from .md file

### ISSUE THREAD

**Issue by WreckItRalph** [angular/angular#57329] opened 2024-08-10 18:48 UTC
### Describe the problem that you experienced

Performing custom rendering to a `<canvas>`, charting library, or other third party UI library.

The given statement has a html element "canvas" which is rendered in browser and only shows half the text which is not meaningful.

As shown in angular.dev: "Performing custom rendering to a `"

### Enter the URL of the topic with the problem

https://angular.dev/guide/signals#use-cases-for-effects

### Add a screenshot if that helps illustrate the problem

![image](https://github.com/user-attachments/assets/cc508805-bac4-477f-8a69-510470eb7107)

**Comment by JeanMeche** [comment] 2024-08-11 14:20
I'll close this as a dupe of #57328, the update to marked v14 (#57319) introduced some regressions.

**Closed by JeanMeche** 2024-08-11 14:20 UTC
Labels: area: adev
