### ISSUE TITLE
[feature request] CSS modules support

### ISSUE THREAD

**Issue by JounQin** [angular/angular#19982] opened 2017-10-27 14:34 UTC
## I'm submitting a...

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report  
- [x] Feature request
- [ ] Documentation issue or request
- [ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

Others:

I'd love to use CSS modules in angular, and I tried to use like following:
``` ts
// demo.component.ts
import classes from './demo.component.scss'

@Component({
  template: './demo.component.html'
})
export class DemoComponent {
  classes = classes
  enabled = true
}

// demo.component.html
<div [ngClass]="{[classes.demo]: enabled}"></div>
```

It thrown en error because `{[classes.demo]: enabled}` is invalid in template expression what seems disheartened.

For now, I can only use `<div [ngClass]="enabled ? classes.demo : ''"></div>` or write another directive something like ngClass to support dynamic keys.

Here is my tiny workaround directive: https://github.com/JounQin/ng-study/blob/master/src/app/directives/css-modules.directive.ts

I still hope we can support built-in feature of CSS modules.

**Comment by trotyl** [comment] 2017-10-28 15:38
Duplicate of #13855.

**Comment by jasonaden** [comment] 2017-11-09 22:42
Closing as a duplicate.

**Closed by jasonaden** 2017-11-09 22:42 UTC
