### ISSUE TITLE
Error thrown by rxjs observer not always sent to ErrorHandler.handleError

### ISSUE THREAD

**Issue by christianacca** [angular/angular#14316] opened 2017-02-05 23:35 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
```

**Current behavior**
Error thrown in an observable is not sent to the `ErrorHandler.handleError` method when `observeOn(Scheduler.asap)` is used.

Take the following example that DOES result in an error being sent:

```ts
    const ticks$ = Observable.interval(1000).take(10);
    
    this.mapped$ = ticks$.map(value => {
      if (value === 3) {
        throw new Error('oops');
      }
      return { value };
    });
```

```html
<h4>Mapped ticks from an observable... {{mapped$ | async | json}}</h4>
```

The following example that does NOT result in an error being sent:

```ts
    const ticks$ = Observable.interval(1000).take(10)
      .observeOn(Scheduler.asap);
      
    this.mapped$ = ticks$.map(value => {
      if (value === 3) {
        throw new Error('oops');
      }
      return { value };
    });
```

**Expected behavior**

An error thrown by an observer scheduled with `Scheduler.asap` is sent to `ErrorHandler.handleError`

**Minimal reproduction of the problem with instructions*** 

I've reproduced the problem in a new angular seed project generated by the latest vs of angular-cli (1.0.0-beta.30).

To run:

* Clone the repo: https://github.com/christianacca/rxjs-err-async-pipe.git
* npm install
* npm start
* browse to `http://localhost:4200/`

Notice that the error thrown by the `map` operator is logged to the console, but not sent to `DelegatingErrorHandler.handleError` (a custom `ErrorHandler`)

**What is the motivation / use case for changing the behavior?**

Using `observeOn(Scheduler.asap)` is a workaround to a problem with rxjs as documented here:

https://medium.com/@benlesh/on-the-subject-of-subjects-in-rxjs-2b08b7198b93#3114

**Please tell us about your environment:**

* Windows 10
* Visual Studio code
* **Angular version:** 2.4.6

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Only tried in Chrome 55.0.2883.87
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

TypeScript 2.0.10

**Comment by DzmitryShylovich** [comment] 2017-02-05 23:36
Pls add a plunkr with repro

**Comment by christianacca** [comment] 2017-02-06 07:31
That's what I said I tried to do:

> I tried getting a plunker working with all the Rxjs pieces but after an hour I gave up

Here's as far as I got: http://plnkr.co/edit/ldm5hGVjnvacRFpkIRXv?p=preview

It seems the ES2015 import's that I've added for the Rxjs modules are not correct.

**Do you have an example plunker that showcases using Rxjs scheduler's with angular?**

Thanks

**Comment by christianacca** [comment] 2017-02-06 08:16
OK so I have got the plunker working with the correct imports: http://plnkr.co/edit/ldm5hGVjnvacRFpkIRXv?p=preview

And the problem is not reproducible in this.

To try and cut the problem space down, I'll create another git repo with a minimum angular seed project generated by the angular-cli with the same exact same versions of angular as the plunker (2.4.6 vs 2.4.1).

If this reproduces the problem, then there is going to be more material to work on.

**Comment by christianacca** [comment] 2017-02-06 20:53
I've reproduced the problem in a new angular seed project generated by the latest vs of angular-cli (1.0.0-beta.30).

See https://github.com/christianacca/rxjs-err-async-pipe

The versions of the (shrinkwrapped) dependencies in this new project are identical to the [plunker version](http://plnkr.co/edit/ldm5hGVjnvacRFpkIRXv?p=preview).

**So it appears a problem with Webpack build (via the cli) of angular and it's rxjs dependency.**

## Reproducing problem

For convenience here is the steps to reproduce the problem with this new project:

* Clone the repo: https://github.com/christianacca/rxjs-err-async-pipe.git
* npm install
* npm start
* browse to http://localhost:4200/rxjs-err-async-pipe

Notice that the error thrown by the map operator is logged to the console, but not to sent to `DelegatingErrorHandler.handleError` (a custom `ErrorHandler`)

Remove [`.observeOn(Scheduler.asap)`](https://github.com/christianacca/rxjs-err-async-pipe/blob/master/src/app/rxjs-err-async-pipe/rxjs-err-async-pipe.component.ts#L28), wait for the browser to refresh, and now you'll see the error alert'ed by `DelegatingErrorHandler`

**Comment by DzmitryShylovich** [comment] 2017-02-08 13:09
@christianacca can you pls update the first post and remove unnecessary comments? A lot of different links, it's hard to understand what actually the problem is. Thx.

**Comment by christianacca** [comment] 2017-02-08 19:20
I've updated my original post...

**Comment by DzmitryShylovich** [comment] 2017-02-08 19:26
```
 ngZone.onError.subscribe({next: (error: any) => { exceptionHandler.handleError(error); }});
```
this is how error handler receives errors. Looks like it's zonejs issue.

**Comment by DzmitryShylovich** [comment] 2017-02-08 19:27
Probably will be fixed here https://github.com/ReactiveX/rxjs/pull/2266

**Comment by christianacca** [comment] 2017-02-08 19:28
Yeah that was my guess.

**Comment by christianacca** [comment] 2017-02-09 07:38
Although if this was the problem, why would the [plunker](http://plnkr.co/edit/ldm5hGVjnvacRFpkIRXv?p=preview) example with the same code work?

**Comment by christianacca** [comment] 2017-04-29 14:11
Unfortunately this issue is **not** closed by PR https://github.com/angular/angular/pull/15208 - please can you therefore reopen.

I have tested against angular 4.1.0 and still see the exact same behaviour as I originally reported.

To reproduce with angular 4.1.0 please follow the steps outlined here: https://github.com/angular/angular/issues/14316#issue-205463886

**Comment by christianacca** [comment] 2017-05-14 08:24
More information:

* The problem can be reproduced in angular 4.1.2 + zone.js 0.8.10
* The problem does not occur when the component demonstrating the issue is lazy loaded
    * to see this for yourself, checkout the lazy-load branch I've created in the same sample repo: https://github.com/christianacca/rxjs-err-async-pipe
    * in this branch you will observe the correct expected behaviour:

> An error thrown by an observer scheduled with Scheduler.asap is sent to ErrorHandler.handleError

**Comment by ccrowhurstram** [comment] 2017-07-31 22:09
FYI, the problem can be reproduced in angular 4.3.2 + zone.js 0.8.16.

This is surprising given that this version of zone.js lands https://github.com/angular/zone.js/pull/843 that was hoping to resolve this problem...

*Note:* https://github.com/angular/zone.js/pull/843 is a replacement for https://github.com/ReactiveX/rxjs/pull/2266

**Comment by JiaLiPassion** [comment] 2017-08-22 17:04
@ccrowhurstram , thank you for posting the issue, current https://github.com/angular/zone.js/pull/843 patch doesn't fully fix your issue, I will continue to make a new PR to fix this one, I have test my idea and it should work.

**Comment by ccrowhurstram** [comment] 2017-08-23 08:11
Excellent @JiaLiPassion. 

Thanks for digging into this - saves me from having to spam this issue with each angular release ;-)

**Comment by bryanrideshark** [comment] 2017-08-23 13:29
@ccrowhurstram, you aren't the only one hitting this - Glad to see that it's getting looked at!

**Comment by JiaLiPassion** [comment] 2017-08-23 13:35
please wait for the next release of `zone.js`, and I will post how to load the new `rxjs patch`.

**Closed** 2017-08-23 16:30 UTC
Labels: comp: zones

**Comment by JiaLiPassion** [comment] 2017-08-23 23:05
@ccrowhurstram , the new `zone.js` have been released, and I test it with your repo, it worked!

to load the patch, 

- npm install zone.js@0.8.17
- add `import 'zone.js/dist/zone-patch-rxjs';` into your `app.module.ts`

**Comment by christianacca** [comment] 2017-08-24 08:06
Brilliant @JiaLiPassion :-)
