### ISSUE TITLE
Reactive forms valueChanges method fires twice for one change on input fields.

### ISSUE THREAD

**Issue by ChrisDevinePimss** [angular/angular#18350] opened 2017-07-26 11:41 UTC
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
When i enter a value into an input box (change event), it triggers the valueChanges observable on the formGroup. When i click off (onBlur event) the input box the valueChanges observable is triggered again.

- The distinctUntilChanged rxjs method does not catch this either
- Seems not to happen on dataType text inp 

## Expected behavior
For the valueChanges subscriber to be triggered on 'change' events and not on 'onBlur' events. 

this can be reproduced in the plunkr below, steps on how are included on the plunkr page

## Minimal reproduction of the problem with instructions

To see the error in chrome (not tested in other browsers), of the 'valuesChanges' event firing on change and blur (twice), do the following:

1. Open up the console in developer tools
2. Click on an input field
3. Enter a number value (1 digit and do not click anywere afterwards)
4. Wait until you see "fired Event" in the console
5. Now click anywere on the page outside the input box
6. You will now see "2 fired Event"

https://plnkr.co/edit/jDzPp2qZKUHShlk1crDj?p=preview

## What is the motivation / use case for changing the behavior?
So the observable is not outputing the same object twice for no reason.

## Environment

<pre><code>
Angular version: 4.3

Browser:
- [x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

Might be in others but iv not checked 
 
For Tooling issues:
- Node version: v6.11.1
- Platform:

**Comment by kara** [comment] 2017-08-04 22:03
Dupe of https://github.com/angular/angular/issues/12540

**Closed by kara** 2017-08-04 22:03 UTC
Labels: comp: forms
