### ISSUE TITLE
internal date/number formatters are not reexported from @angular/common

### ISSUE THREAD

**Issue by iexela** [angular/angular#20536] opened 2017-11-20 07:12 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Starting from the version 5 Angular uses CLDR data for number/date/currency internalization. It uses internal formatters for this purpose and does not reexports them to be available for developers. I mean formatters describes in these files: [format_date.ts](https://github.com/angular/angular/blob/master/packages/common/src/i18n/format_date.ts), [format_number.ts](https://github.com/angular/angular/blob/master/packages/common/src/i18n/format_number.ts).

## Expected behavior
Reexported formatters will allow to localize data in code.

## What is the motivation / use case for changing the behavior?
Sometimes it is necessary to translate dates or numbers in code rather than in templates.
For example, when we use 3rd-party components, like ag-grid, we can define custom formatters for date represented in grid and it will be a large overhead to use Angular component for this purpose. Much easier is to use formatting capabilities embedded into Angular itself to reach consistent formatting.
Another case is messages generated in code.

## Environment

<pre><code>
Angular version: 5.x.x
</code></pre>

**Comment by trotyl** [comment] 2017-11-20 07:23
Why not just use the pipe? Pipe are available in both template and logic.

**Comment by trotyl** [comment] 2017-11-20 07:28
Duplicate of https://github.com/angular/angular/issues/3809, https://github.com/angular/angular/issues/15107.

**Comment by vicb** [comment] 2017-11-21 04:48
Our intent with the refactoring in 5.x was to make this publicly available at some point.
We will do that at some point when we have some confidence in the new API.
_(A lot of devs are using the pipes to format dates & numbers in their code today which is definitely not a good thing)_

**Comment by Toxicable** [comment] 2017-11-21 05:23
I had the idea to put those date functions in a service rather than just exporting a bunch of functions but due to the services not being tree shakable I didn't proceed, maybe once that's a thing we could take a look back at it?

**Comment by iexela** [comment] 2017-11-22 06:07
Injection of date pipe solved my problem, thank you.
Although from my perspective this solution looks like a workaround.
Glad to hear that you have plans to make format API public.

**Comment by alan-agius4** [comment] 2017-12-28 20:54
Yeah same thing I hate to inject the pipe, it does feel wrong. 

i like the service approach, TBH, as like that when you use a method you dont’t need to provide the LOCAL_ID, as some pre functions that there are available require the localId as param at the moment.

Maybe as a starter you can export these method similar to what you are doing for other methods like getLocalCurrencySymbol?, since really I dont know when we’ll have treeshaking on services.

I’ll gladly do a PR if it is needed :)

**Comment by Toxicable** [comment] 2017-12-28 20:58
It would be better to do a proper job of exporting these functions with a Design Doc and as a service specifically designed for this.
Doing a half job by exporting random functions into the public API can force us into a bad position if we want to come back and refactor it into a service later

**Comment by alan-agius4** [comment] 2017-12-28 21:08
So whats the different between the ‘format’ and the ‘getLocale’ methods
like such:
https://angular.io/api/common/getLocaleNumberFormat that the format methods
needs to be in a service and the others as exported methods?

Don’t get me wrong I am in favor of the service, but maybe in that case the
current exported functions should go in the service as well than? So not to
have half of the methods exported and the other half in a service.

But as you mentioned there is the overhead of not being tree-shaked.

**Comment by ocombe** [comment] 2017-12-29 11:05
It's on our todo list to export those functions, but we need to refactor them a bit to make them easier to use by anyone.

**Closed** 2018-02-23 23:28 UTC
Labels: comp: i18n, type: feature
