### ISSUE TITLE
Directive with @Input() disabled will swallow disabled property on button

### ISSUE THREAD

**Issue by samu** [angular/angular#23332] opened 2018-04-12 06:58 UTC
## I'm submitting a

Bug report

## Current behavior
I created a directive which has an `@Input() disabled`. I also have a button on which i use the `[disabled]` binding. If i use my directive on this button, it will 'swallow' the disabled property and the button will render enabled, even though it should be disabled.

## Expected behavior
Button is disabled regardless of what other directives i'm using on it.

## Minimal reproduction of the problem with instructions

In the following plunker, if you remove the `swallow` directive, the button will become disabled:

https://plnkr.co/edit/EDQYyY1065S7AzF9SAit?p=preview

## Environment
Angular version: 5.2.9

**Comment by jainanuj0812** [comment] 2018-04-12 09:18
I don't think it is a good idea. Don't override the default HTML attributes with your custom directives **input**. It's not the best practice and you may get the unexpected results.

Here disabled is OOTB available as a standard HTML attribute.

**Comment by samu** [comment] 2018-04-12 10:07
I'm not suggesting a new feature - in my opinion, it is a bug.

If angular doesn't want me to bind standard HTML attributes, there should be an appropriate warning.

**Comment by pkozlowski-opensource** [comment] 2018-04-12 10:09
This is by design - directives inputs "shadow" native properties. You can still reflect (set / unset) those on the underlying DOM node in your directive.

**Comment by pkozlowski-opensource** [comment] 2018-04-12 11:33
> Is there a reason to shadow native properties?

See the reasoning discussion in the original PR:
https://github.com/angular/angular/pull/3419

**Comment by samu** [comment] 2018-04-12 12:10
Thanks Pawel for the clarification

**Comment by jasonaden** [comment] 2018-04-12 21:00
Closing as clarified.

**Closed by jasonaden** 2018-04-12 21:00 UTC

**Comment by leblancmeneses** [comment] 2019-06-01 07:13
material button reuses the disabled property like this to make it work
https://github.com/angular/components/blob/2adf6294b52088e0f4b6284672cc2ca5e9163c20/src/material/button/button.ts#L71

```

@Directive({
  selector: '[fxmeClassLoop]',
  host : {
    '[attr.disabled]': 'disableLoop || null',
  }
})

private _disableLoop = false;
  get disableLoop() {
    return this._disableLoop;
  }
  @Input('disabled')
  set disableLoop(value: any) {
    const requestedValue = coerceBooleanProperty(value);
    if (requestedValue !== this._disableLoop) {
      this._disableLoop = requestedValue;
      this.disabled$.next(this._disableLoop);
    }
  }

```
