### ISSUE TITLE
Ivy doesn't support readonly undefined properties when using `useDefineForClassFields`

### ISSUE THREAD

**Issue by michaeljota** [angular/angular#35560] opened 2020-02-19 18:27 UTC
# 🐞 bug report

### Affected Package

The issue is caused by package `@angular/core`

### Is this a regression?

 
No. The `useDefineForClassFields` was introduced in TS3.7 and that version is only supported in Angular 9.

### Description

If you consume a service from a component, with a property that is not initialized but assigned after the instance, Angular will throw.

I've only tested this in Services, but maybe it can be reproducible with others IDK. 

The error:

## 🔬 Minimal Reproduction

[useDefineForClassFieldsBug.zip](https://github.com/angular/angular/files/4226658/useDefineForClassFieldsBug.zip)

- install the dependencies
- run the application
- the error should be shown in the browser

## 🔥 Exception or Error
[localhost-1582136600377.log](https://github.com/angular/angular/files/4226661/localhost-1582136600377.log)

## 🌍  Your Environment

**Angular Version:**
```

     _                      _                 ____ _     ___ 
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | | 
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | | 
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.0.2
Node: 12.13.1
OS: win32 x64

Angular: 9.0.1
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.2
@angular-devkit/build-angular     0.900.2
@angular-devkit/build-optimizer   0.900.2
@angular-devkit/build-webpack     0.900.2
@angular-devkit/core              9.0.2
@angular-devkit/schematics        9.0.2
@angular/cli                      9.0.2
@ngtools/webpack                  9.0.2
@schematics/angular               9.0.2
@schematics/update                0.900.2
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
```

**Anything else relevant?**

This may be reproducible with other Angular features such as pipes, directives, or others, but it wasn't tested.

**Comment by JoostK** [comment] 2020-02-19 21:00
This doesn't seem to be related to Angular. The stock TypeScript compiler generates a reference to an unknown variable when a field has the `readonly` modifier.

https://www.typescriptlang.org/v2/en/play?useDefineForClassFields=true&ssl=2&ssc=3&pln=2&pc=11#code/KYDwDg9gTgLgBAYwDYEMDOa4BUCWMnADKwUAbjgsHAN4BQccUwKAJhAHZICecMeBALjhoYUHOwDmAbloBfIA

I don't know whether this is a bug in TypeScript or working as intended, but at least it's not Angular specific so I'm closing this issue.

**Closed by JoostK** 2020-02-19 21:00 UTC

**Comment by michaeljota** [comment] 2020-02-20 12:57
Thanks. I should have try that before posting the issue here. Will check on the Typescript side.
