### ISSUE TITLE
Not able to catch 400 Status Code Error

### ISSUE THREAD

**Issue by zeeshanjan82** [angular/angular#9518] opened 2016-06-23 05:20 UTC
I am trying to catch 400 Status Code Error in my app which is using angular2 HTTP I have written the following code:
```js
    this.http.post(`${GlobalService.getApiPath()}/forgotpassword`, body, options)
       .map(res => res.json()).subscribe(
            data => console.log(data),
            error => console.log(error)
        );
```
However when I look into the console I see the below response getting logged which has status code 200
![error](https://cloud.githubusercontent.com/assets/8342604/16292541/27edcc18-3930-11e6-92b4-e388b46960a8.png)

When I check in POSTMAN of through CURL I get Status Code 400 but my app is not able to handle this error and converts somehow this error to 200.

**Comment by vicb** [comment] 2016-06-23 05:24
This has been fixed in rc3

**Comment by zeeshanjan82** [comment] 2016-06-23 05:25
thanks @vicb

**Closed by vicb** 2016-06-23 05:24 UTC

**Comment by zeeshanjan82** [comment] 2016-06-23 05:53
Hi @vicb I have upgraded to rc3 but now I see status code : 0 instead of 400 
![error](https://cloud.githubusercontent.com/assets/8342604/16293132/f2aad064-3934-11e6-936b-fed5f118cc95.png)

**Comment by crebuh** [comment] 2016-07-27 13:52
@zeeshanjan82 

I've got the same problem I'm currently also working with rc3

**Comment by ruwhan** [comment] 2016-07-29 07:02
I got exactly this unexpected behavior. 

To replicate, just try to add not encodable character to your request body, e.g. `{ "field": { "like":  "%likethis"} }`

**Comment by zeeshanjan82** [comment] 2016-07-30 11:52
@crebuh @ruwhan I am able to solve the issue, I had to include the additional header: 
```    headers.append('X-Requested-With',''); ```

**Comment by vicb** [comment] 2016-07-30 19:25
IIRC 0 is because you try to request a different domain ?
