### ISSUE TITLE
Deployment - htaccess for shared hosting servers

### ISSUE THREAD

**Issue by lluz** [angular/angular#27991] opened 2019-01-08 17:28 UTC
# 📚 Docs or angular.io bug report

### Description
An addition to the "Deployment" documentation.

### What's the affected URL?
https://angular.io/guide/deployment

### Reproduction Steps
Go to the "Fallback configuration examples"

### Expected vs Actual Behavior
Addition to the 'Apache section':
```
RewriteEngine on
RewriteCond %{REQUEST_FILENAME} -s [OR]
RewriteCond %{REQUEST_FILENAME} -l [OR]
RewriteCond %{REQUEST_FILENAME} -d
RewriteRule ^.*$ - [NC,L]
RewriteRule ^(.*) index.html [NC,L]
```

I followed this comment:
https://github.com/angular/angular/issues/11884#issuecomment-404237955

### Anything else relevant?
Distribution uploaded to a regular shared Apache server.

**Comment by jenniferfell** [comment] 2019-01-25 01:51
https://angular.io/guide/deployment#fallback-configuration-examples

Copied over from the comment linked above: 
```
This .htaccess worked for me:

RewriteEngine on
RewriteCond %{REQUEST_FILENAME} -s [OR]
RewriteCond %{REQUEST_FILENAME} -l [OR]
RewriteCond %{REQUEST_FILENAME} -d
RewriteRule ^.*$ - [NC,L]
RewriteRule ^(.*) index.html [NC,L]
```

**Comment by jenniferfell** [comment] 2019-01-25 01:56
@lluz : Thank you for researching this and letting us know. My team isn't currently set up to test Apache. Is there any chance you'd be willing to submit a PR for the doc update, based on what worked for you? See [Contributing to Angular](https://github.com/angular/angular/blob/master/CONTRIBUTING.md) for more info.

**Comment by lluz** [comment] 2019-01-25 12:51
@jenniferfell 
Thanks for picking up on this minor issue.
Unfortunately I am no expert on Apache so I am unable to describe (comment) the solution and compare/check if it is better than the one currently documented.
The only thing I know is that it is a complementary option that works well on my common Apache shared hosting servers.
I have however called out to @gthomas2 ( https://github.com/angular/angular/issues/11884#issuecomment-404237955 ) to see if he would be willing to make the pull request.
Hope someone with the right skills can pick this up, because it is a bit annoying when you publish a distribution (Javascript web app) to a common basic Apache server only to find out that a simple browser page refresh (F5) will give you a "Not Found" default server page.

**Comment by rockument69** [comment] 2020-05-29 17:30
Looks like we need engineering input for this.

**Comment by josephperrott** [comment] 2021-05-25 19:50
Closing this out as a duplicate of #21201

As noted in the closing comment of https://github.com/angular/angular/issues/21201#issuecomment-846218241, while the proposed configuration is valid and will work.  We are not providing a production ready configuration to be used, the intention is for this to be a basic configuration for a simple development environment as a starting point.  The current configuration we use has good compatibility and is easy to reason about what the lines of the configuration do.

Currently security practice recommendation for production apache use as I understand it is actually to use a `httpd.conf` file rather than `.htaccess` file anyway.

**Closed by josephperrott** 2021-05-25 19:50 UTC
Labels: P3, comp: docs, docsarea: build & deploy, effort1: hours, freq2: medium, state: needs eng input, triage #1, type: bug/fix
