### ISSUE TITLE
Error using HTML <time> tag with datetime attribute

### ISSUE THREAD

**Issue by karptonite** [angular/angular#26255] opened 2018-10-04 18:09 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Template parse error using the time tag with the datetime attribue.

## Expected behavior
Template parses correctly

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-time-tag-issue?file=app%2Fapp.component.html

## What is the motivation / use case for changing the behavior?
properly using the html 5 time tag.

## Environment

<pre><code>
Angular version: 6.1.7

Browser:
- [x] Chrome (desktop) version 69

</code></pre>
Others:
This was previously reported with a PR submitted, but both were closed with no action:
See issues #11361, #11232

**Comment by alexzuza** [comment] 2018-10-04 18:44
I would say that Angular properly uses time tag.

`<time>` tag with **datetime** **attribute** should look like:

```
<time [attr.datetime]="time">{{time}}</time>
```
while `<time>` tag with **dateTime** **property** is:


```
<time [dateTime]="time">{{time}}</time>
```

**Comment by pkozlowski-opensource** [comment] 2018-10-04 18:58
@alexzuza is totally right here:
* _attribute_ name is `datetime`: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/time
* _property_ name (default binding in Angular) is `dateTime`: https://developer.mozilla.org/en-US/docs/Web/API/HTMLTimeElement

Closing since it is working as intended.

**Closed by pkozlowski-opensource** 2018-10-04 18:58 UTC
