### ISSUE TITLE
ERROR NullInjectorError: R3InjectorError when building a lib and using services who are not providedIn root

### ISSUE THREAD

**Issue by paulstelzer** [angular/angular#36206] opened 2020-03-23 17:45 UTC
# 🐞 bug report

### Affected Package
`@angular/core`

### Is this a regression?
Yes, only happens with ivy. If I disable ivy, everything works as expected

```
"angularCompilerOptions": {
    "enableIvy": false
}
```

### Description

We are using ionic-native for our crossplatform apps. So we created some libraries to share code between different apps. If we use ionic-native (which has no providedIn root) we add the providers inside forRoot of a module in the library (1), build the library and add this module from our library in our AppModule (2). If we now using the service from the lib (3), the error occurs on start-up

We created an minimal repo where you can see the issue.

(1) https://github.com/paulstelzer/angular-ionic-issue/blob/master/projects/inno-core/src/lib/inno-core.module.ts

(2) https://github.com/paulstelzer/angular-ionic-issue/blob/master/src/app/app.module.ts

(3) https://github.com/paulstelzer/angular-ionic-issue/blob/master/src/app/app.component.ts

## 🔬 Minimal Reproduction

Github: https://github.com/paulstelzer/angular-ionic-issue

Nice to know: The "dist" folder is already comitted, so you do not need to build the lib. If you want just run `npm run lib:build`, 

1. `npm i`
2. `ng serve`

The app will show the error like mentioned below

## 🔥 Exception or Error
<pre><code>
core.js:6185 ERROR NullInjectorError: R3InjectorError(AppModule)[PlatformService -> Device -> Device -> Device]: 
  NullInjectorError: No provider for Device!
    at NullInjector.get (http://localhost:4200/vendor.js:36155:27)
    at R3Injector.get (http://localhost:4200/vendor.js:49871:33)
    at R3Injector.get (http://localhost:4200/vendor.js:49871:33)
    at R3Injector.get (http://localhost:4200/vendor.js:49871:33)
    at injectInjectorOnly (http://localhost:4200/vendor.js:36010:33)
    at ɵɵinject (http://localhost:4200/vendor.js:36020:57)
    at Object.PlatformService_Factory [as factory] (http://localhost:4200/main.js:103:356)
    at R3Injector.hydrate (http://localhost:4200/vendor.js:50107:63)
    at R3Injector.get (http://localhost:4200/vendor.js:49859:33)
    at NgModuleRef$1.get (http://localhost:4200/vendor.js:67203:33)

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.0.7
Node: 10.16.0
OS: win32 x64

Angular: 9.0.7
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.900.7
@angular-devkit/build-angular      0.900.7
@angular-devkit/build-ng-packagr   0.900.7
@angular-devkit/build-optimizer    0.900.7
@angular-devkit/build-webpack      0.900.7
@angular-devkit/core               9.0.7
@angular-devkit/schematics         9.0.7
@ngtools/webpack                   9.0.7
@schematics/angular                9.0.7
@schematics/update                 0.900.7
ng-packagr                         9.0.3
rxjs                               6.5.4
typescript                         3.7.5
webpack                            4.41.2

</code></pre>

**Anything else relevant?**
We building the library with ng-packagr! This can also be a bug of ionic-native!

**Comment by mlc-mlapis** [comment] 2020-03-23 18:03
@paulstelzer Related to https://github.com/angular/angular/issues/35576?

**Comment by JoostK** [comment] 2020-03-23 18:33
@mlc-mlapis I don't think it's related. There looks to be an issue with how `@ionic-native/device/ngx` is processed in ngcc, causing the `Device` service not to be available.

**Comment by mlc-mlapis** [comment] 2020-03-23 21:12
@JoostK OK. Thanks for that. One more thing, what do you about https://github.com/angular/angular/issues/35576? What is a bit surprising for me is that the issue is passing all already existed tests without any attention.

**Comment by JoostK** [comment] 2020-03-23 21:34
@mlc-mlapis I wasn't aware of that issue but it looks to be the same as #35759 for which I commented on how to make it work: https://github.com/angular/angular/issues/35759#issuecomment-601444856.

**Comment by petebacondarwin** [comment] 2020-05-24 19:06
I just cloned the reproduction repository and ran `ng serve`. I did not get any errors.

**Comment by petebacondarwin** [comment] 2020-05-24 19:09
I note that I was unable to run `npm ci` because the package.json and the package-lock.json files were out of sync with each other.

I tried clearing the `dist` folder and rebuilding the library too. But still no error.

**Comment by paulstelzer** [comment] 2020-05-24 19:16
I will check, maybe its already fixed

**Comment by petebacondarwin** [comment] 2020-06-08 10:02
I assume that since you didn't come back to this that you no longer have this problem?
Closing for now. Please post here if you find the problem still exists, and I will re-open.

**Closed by petebacondarwin** 2020-06-08 10:02 UTC
Labels: comp: ngcc, state: Could not reproduce, triage #1
