### ISSUE TITLE
version compatibility link is not working

### ISSUE THREAD

**Issue by MasterReptilian77** [angular/angular#52859] opened 2023-11-13 13:44 UTC
### Describe the problem that you experienced

when I try to open the link from documentation it gives me 'page not found'

### Enter the URL of the topic with the problem

https://angular.dev/versions

### Describe what you were looking for in the documentation

I was looking for the angular version compatibility

### Describe the actions that led you to experience the problem

when click on the href link on angular version compatibility it gives me page not found

### Describe what you want to experience that would fix the problem

to open new page which have version compatibility of angular

### Add a screenshot if that helps illustrate the problem

![image](https://github.com/angular/angular/assets/83166182/b6bc2764-f30e-4820-b455-938d0c2b59df)

**Comment by JeanMeche** [comment] 2023-11-13 13:52
Thanks for the report, this is a duplicate of #52562 and has since been addressed, but is pending a deployment.

**Closed by JeanMeche** 2023-11-13 13:52 UTC
Labels: area: adev
