### ISSUE TITLE
[Angular 2] ngFor with directive has DOM and memory leak

### ISSUE THREAD

**Issue by JordanFriendshuh** [angular/angular#12199] opened 2016-10-10 15:39 UTC
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When you apply a directive to a ngFor DOM item the old DOM items are not cleaned up in memory causing a memory leak and an ever increasing memory footprint of the site.

**Expected behavior**
The detached DOM items to be cleaned up when they are no longer on the DOM.

**Minimal reproduction of the problem with instructions**
Here is a copy of the angular2-seed with a few changes that I wrote to [demonstrate](https://github.com/JordanFriendshuh/angular2Leaks) the leak.  I didn't use plunkr because I didn't want to deal with the plunkr noise when mapping the memory usage.  To run the app just do a npm install and then a npm start.

When you run the code without a directive attached to the ngFor the allocation timeline looks like this:
![nodirectiveleak](https://cloud.githubusercontent.com/assets/5614205/19241475/085f2fc6-8ecc-11e6-8773-2f0e3f320788.jpg)

To replicate that remove the empty directive from the ngFor in this [file](https://github.com/JordanFriendshuh/angular2Leaks/blob/master/src/client/app/app.component.html) and then run it.

When you apply the empty directive you can see the allocation timeline changes and when you investigate the snapshot you can see detached DOM items from the loop that aren't being cleaned up.
![directiveleak](https://cloud.githubusercontent.com/assets/5614205/19241500/28974c9c-8ecc-11e6-9153-2315753a571d.jpg)

The DOM that is being kept is found in this [file](https://github.com/JordanFriendshuh/angular2Leaks/blob/master/src/client/app/app.component.html).

Both these allocation capture files can be found in the [repo](https://github.com/JordanFriendshuh/angular2Leaks/tree/master/allocationCaptures).

* **Angular version:** 2.0.1
```js
    "@angular/common": "^2.0.1",
    "@angular/compiler": "^2.0.1",
    "@angular/core": "^2.0.1",
    "@angular/forms": "^2.0.1",
    "@angular/http": "^2.0.1",
    "@angular/platform-browser": "^2.0.1",
    "@angular/platform-browser-dynamic": "^2.0.1"
```

**Comment by tbosch** [comment] 2016-10-24 23:14
Thanks for reporting.
To narrow this, the screen shots you attached conclude you are running the application in debug mode. Could you try again to confirm whether this is also a problem in prod mode?
I.e. add a call to `enableProdMode()` (imported from `@angular/core`) before calling `bootstrap`?

**Comment by tbosch** [comment] 2016-10-24 23:34
Hi,
I changed your application to add an item every 1 ms and let the application run for 15s. Here is the timeline result tracing the memory. You can see that the memory goes back all the way down eventually again (not after each iteration though).
![screen shot 2016-10-24 at 4 33 07 pm](https://cloud.githubusercontent.com/assets/690815/19667770/a2817938-9a07-11e6-9080-0ae2d22f8473.png)

**Comment by tbosch** [comment] 2016-10-24 23:35
Closing as not a bug.

**Closed by tbosch** 2016-10-24 23:35 UTC
Labels: comp: common
