### ISSUE TITLE
Angular router animation exposing elements that was hidden by animation

### ISSUE THREAD

**Issue by havivi86** [angular/angular#36835] opened 2020-04-28 13:48 UTC
# 🐞 bug report

### Affected Package

 The issue is probably caused by package @angular/animations

### Is this a regression?

 Yes, in Angular 8.x this was ok.

### Description

I'm trying to upgrade my Angular project from 8.x to 9. Once I've done following the upgrade instructions, I've noticed that on one page that contains inner animation on it that supposed to hide certain element, becomes visible during router animation. I synthesized the issue to small project that demonstrate the issue (can be also found in StackBlitz: https://stackblitz.com/edit/angular-jbcamx)

## 🔬 Minimal Reproduction

 https://stackblitz.com/edit/angular-jbcamx

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 9.1.1
Node: 14.0.0
OS: win32 x64

Angular: 9.1.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.1
@angular-devkit/build-angular     0.901.1
@angular-devkit/build-optimizer   0.901.1
@angular-devkit/build-webpack     0.901.1
@angular-devkit/core              9.1.1
@angular-devkit/schematics        9.1.1
@angular/cdk                      9.2.1
@angular/cli                      9.1.1
@ngtools/webpack                  9.1.1
@schematics/angular               9.1.1
@schematics/update                0.901.1
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0

</code></pre>

**Anything else relevant?**

**Comment by ismailcherri** [comment] 2020-04-28 14:07
Your example doesn't work as intended or doesn't demonstrate the bug correctly. Even when router animation is disabled, the issue is still there.
The `height: 0px` takes some milliseconds to be applied. If you add it to the inline style, the issue is gone.

**Comment by havivi86** [comment] 2020-04-28 19:41
Thanks @ismailcherri for looking into it. 
1. You are right - after taking more carful look at my repro, I noticed that hidden part appears before at the entrance, while locally it expose itself during the leave. This is interesting, because if I download the stackblitz project as is, and run `npm install` and `ng serve`, my issue does reproduced (only locally). Downgrading to Angular 8 fixes the issue without code change.
2. I did some more digging, and found something else that I can't explain. in my `test.component.ts` where I defined the inner animation, I have wildcard state transition like `* => *` (I have only 2 states). If I change the transition to `hide <=> show` (it should be equivalent as I understand it), the issue that can be seen in stackblitz is solved without adding the `height: 0px`

**Comment by atscott** [comment] 2020-05-07 22:06
Hi @havivi86 with regards to your second question
> 2. I did some more digging, and found something else that I can't explain. in my `test.component.ts` where I defined the inner animation, I have wildcard state transition like `* => *` (I have only 2 states). If I change the transition to `hide <=> show` (it should be equivalent as I understand it), the issue that can be seen in stackblitz is solved without adding the `height: 0px`

`* => *` is actually not equivalent to `show <=> hide` because `*` also matches `void` ([reference](https://angular.io/guide/transition-and-triggers#using-wildcard-state-with-multiple-transition-states)).

So `* => *` is actually more equivalent to:
```
   transition('hide <=> show', [
      animate('0.3s')
    ]),
    transition('void <=> show', [
      animate('0.3s')
    ]),
    transition('void <=> hide', [
      animate('0.3s')
    ]),
```

This leads me to believe that this is working as intended. You're animating the `void => hide` transition when you change the page (see [docs](https://angular.io/guide/transition-and-triggers#void-state) for `void` state definition), so the `height: 0px` would be applied with a `0.3s` transition.

If that makes sense, I think we can close this issue. Please let me know if I've misunderstood something here.

**Comment by havivi86** [comment] 2020-05-08 11:24
Thanks @atscott for looking into it. I guess you are right about the fact that * => * is not equivalent to show <=> hide, but please note some points:
1. The transition form void to hide isn't animated - it is shown until the page is fully displayed, and then it appears at once. And again, when the page in unloaded, the hidden part appears at the moment you press the button and fade away together with the rest of the page. I would expect it to be animated.
2. You didn't addressed my first question. I still don't know how to handle it.
3. The fact that the exact same code acts differently on Angular 8.x is suspicious for my opinion. In 8.x it worked as I expected it to work.

**Comment by havivi86** [comment] 2020-07-26 19:09
is there any progress with that? Angular 10 is out and still have the same issue...

**Comment by jessicajaniuk** [comment] 2021-12-13 22:06
Based on both @atscott and @dario-piotrowicz's thorough look into this, It appears this behaves as expected. If you still feel there is an issue, we can re-open this or create a new issue.

**Closed by jessicajaniuk** 2021-12-13 22:06 UTC
Labels: type: bug/fix, comp: animations, freq2: medium, regression, comp: router, state: confirmed, triage #1, P2
