### ISSUE TITLE
Can't access when use ViewEncapsulation.ShadowDom

### ISSUE THREAD

**Issue by kumaresan-subramani** [angular/angular#37601] opened 2020-06-16 04:19 UTC
# 🐞 bug report

### Affected Package
unable to access the DOM elements when using encapsulation as shadowDOM, so that facing console error

### Description

**Sample** - https://stackblitz.com/edit/angular-ivy-bwfmri?file=src%2Fapp%2Fapp.component.ts

Above is my sample, when i use `ViewEncapsulation.ShadowDom` i cant access DOM elements Please refer the following screenshots.

**DOM element:**
![image](https://user-images.githubusercontent.com/36756050/84732280-e17b0300-afb8-11ea-9ca1-1359ce3f0325.png)

### Reproduce steps

- issue sample - https://stackblitz.com/edit/angular-ivy-bwfmri?file=src%2Fapp%2Fapp.component.ts

Just open this sample and check console

- working sample - https://stackblitz.com/edit/angular-ivy-ceaswm?file=src/app/app.component.ts

When i disable `ViewEncapsulation.ShadowDom`, it is working fine

## 🌍  Your Environment

**Angular Version:**
<pre><code>
 "@angular/animations": "9.1.0",
    "@angular/common": "9.1.0",
    "@angular/compiler": "9.1.0",
    "@angular/core": "9.1.0",
    "@angular/forms": "9.1.0",
    "@angular/http": "7.2.16",
    "@angular/platform-browser": "9.1.0",
    "@angular/platform-browser-dynamic": "9.1.0",
    "@angular/router": "9.1.0",

</code></pre>

**Anything else relevant?**
is ther any othe way to access DOM element in shadow DOM mode

**Comment by JoostK** [comment] 2020-06-16 08:17
Using native Shadow DOM results in component views being attached into their own shadow documents, so querying from within `document` will not be able to find these. In the example you can trivially fix it by injecting `ElementRef` and quering from its `nativeElement`, but I guess that the situation is not that simple in your real problem. You'd have to select the shadow root using regular DOM APIs:

```ts
document.querySelector('my-app').shadowRoot.getElementById('check');
```

Closing as Angular is working as intended here.

**Closed by JoostK** 2020-06-16 08:17 UTC

**Comment by kumaresan-subramani** [comment] 2020-06-16 08:28
Thanks @JoostK
