### ISSUE TITLE
a little error

### ISSUE THREAD

**Issue by serenditpity** [angular/angular#7843] opened 2016-03-31 03:37 UTC
`<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <script src="http://apps.bdimg.com/libs/angular.js/1.4.6/angular.min.js"></script>
</head>
<body>
    <p>
       数组</p>
    <div ng-app=""  ng-init="names=['a','b','c','c']">
        <ul>
            <li ng-repeat='n in names'>{{n}} </li>
        </ul>
    </div>
</body>
</html>`

The above code will be an error,i don't no why

**Comment by CodeJason** [comment] 2016-03-31 04:03
Firstly it would be good if your issue was a bit more presented. 
Secondly the angular you're using with your cdn doens't seem to work quite right. 
Another that works is: https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.6/angular.js
Thirdly, you have a duplicate item 'c' which can be solved by adding 'track by $index' to your ng-repeat statement. 
Hope that helps.

**Comment by pkozlowski-opensource** [comment] 2016-03-31 08:54
Seems like the issue is Angular 1.x related and not very actionable as-is. Closing.

**Closed by pkozlowski-opensource** 2016-03-31 08:54 UTC
