### ISSUE TITLE
Allow template-driven form inputs across a component hierarchy to register with a single parent form.

### ISSUE THREAD

**Issue by cghislai** [angular/angular#9600] opened 2016-06-25 15:31 UTC
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Using the new form API, if a parent component has a `<form>` tag, and child components have `<input>` tags using the [(ngModel)] directive, then input components will not be registered with the parent form.

**Expected/desired behavior**
If a parent component has a form containing child components with ngModel-bound input components in their template, then these input components should be registered with the parent form.

**Reproduction of the problem**
See this plunkr: https://plnkr.co/edit/oKmTF7FgJM24L3ZvZ7F2?p=preview

**What is the expected behavior?**
The parent form should not be valid if the child input is invalid

**What is the motivation / use case for changing the behavior?**
There should be a way to wrap form parts in components and embed them in a parent form. Imagine a tabbed-form with a single save button, or a form containing a list of items. 

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.3
 
* **Browser:** [Chrome ] 
 
* **Language:** [TypeScript]

**Comment by devpreview** [comment] 2016-06-25 21:16
I want it badly!

**Comment by Dekeyras** [comment] 2016-06-25 21:20
+1 Same. I've been trying to get this to work for the last week

**Comment by sharpmachine** [comment] 2016-06-26 02:29
+1.

**Comment by devpreview** [comment] 2016-06-26 17:37
As hotfix you may use "RegisterFormModelDirective":

```
import { Directive, ElementRef, Input, OnInit } from '@angular/core';
import { NgModel, NgForm } from '@angular/forms';

@Directive({
    selector: '[registerForm]'
})
export class RegisterFormModelDirective implements OnInit {
    private el: HTMLInputElement;

    @Input('registerForm') public form: NgForm;
    @Input('registerModel') public model: NgModel;

    constructor(el: ElementRef) {
        this.el = el.nativeElement;
    }

    ngOnInit() {
        if (this.form && this.model) {
            this.form.form.addControl(this.model.name, this.model.control);
        }
    }
}
```

And this directives:
```
<input [(ngModel)]="myValue" minlength="10" #myInput="ngModel" #myComp
      name="childValue" [registerForm]="form" [registerModel]="myInput">
```

See plunkr demo: https://plnkr.co/edit/GG2TVHHHGbAzoOP5mIRr?p=preview

**Comment by devpreview** [comment] 2016-06-26 18:46
If you have "EXCEPTION: Expression has changed after it was checked. Previous value: 'false'. Current value: 'true'", change code:

```
public ngOnInit() {
    if (this.form && this.model) {
        this.form.form.registerControl(this.model.name, this.model.control);
        this.form.addControl(this.model);
    }
}
```

**Comment by advgal** [comment] 2016-07-14 07:38
Good workaround, but this should be solved quickly, it's a core feature of angular to use components!

**Comment by negberts** [comment] 2016-08-01 11:14
+1.

**Comment by Miiekeee** [comment] 2016-08-01 11:28
+1

**Comment by richavyas** [comment] 2016-08-01 11:35
+1

**Comment by karaoak** [comment] 2016-08-02 05:05
+1

**Comment by zoechi** [comment] 2016-08-02 05:21
There is a nice new GitHub feature to "add reaction"s instead of `+1` posts. Please use this instead :+1:

**Comment by kara** [comment] 2016-08-09 18:06
This looks like a dupe of https://github.com/angular/angular/issues/9281. The short answer is you'll need to implement ControlValueAccessor. See a more detailed explanation [here](https://github.com/angular/angular/issues/9281#issuecomment-238610807).

**Closed by kara** 2016-08-09 18:06 UTC
Labels: comp: forms, type: feature

**Comment by negberts** [comment] 2016-08-11 06:17
But what if the child component contains many formcontrols? For instance an address (street, number, zipcode, city, country) inside a contact?

**Comment by kara** [comment] 2016-08-11 06:29
You might want take a look at my comment [here](https://github.com/angular/angular/issues/10251#issuecomment-238709839).  Links to a plunker with an address.

**Comment by negberts** [comment] 2016-08-11 06:37
And do you have a template-driven example? Or is that not possible?

**Comment by advgal** [comment] 2016-09-06 12:24
@kara you write that validators need to be placed on the top-level form. But this is the wrong place. E.g. an address control, the validators for telephone number or zip code have to be inside the component. In my opinion the feature request should not be closed, there is no practical solution for this fundamental feature.

**Comment by kylecordes** [comment] 2016-09-06 12:32
This item is an excellent feature request - it would make Angular much more suitable in applications with complex forms. Currently the "worst" components in an A2 application tend to be those which sprawl to accommodate a complex form, because forms can't be readily split using the component hierarchy.

**Comment by cghislai** [comment] 2016-09-06 16:57
I think the actual solution allows to solve both of your case
- @advgal, you can place the validator at top-level component or inside
your inner components:
  top:
` <my-comp required my-validation-directive
[(ngModel)]="myInnerModel"></my-comp>`
 inner:
`<div><input required my-validation-directive
[(ngModel)]="myInnerModel.value"></div>`

- @Kyle:
If you split your form, just split your form model as well and implements
formValueAccessor. I don't see how it doesn't fit in your app.

**Comment by advgal** [comment] 2016-09-07 07:05
@cghislai, we did not report a bug, we want a feature. Maybe it is possible to split a form up into many components. But it is very uncomfortable to use a complex and undocumented function with much boiler plate code. Splitting code into small reusable parts is a main requirement for software development. If there is an easy way, I did not find it so far, maybe it's only a lack of documentation.

**Comment by bzums** [comment] 2017-02-10 06:57
@cghislai Is it also possible to build a value accessor for a `FormGroup` or `FormArray`?

**Comment by cghislai** [comment] 2017-02-10 07:10
You can build a value accessor for any component holding a value. Bind your value using ngModel, you will get the updated value in the (ngModelChange) event (or you can use the 2-way binding [(ngModel)].
You model may be any object/array, and you can build a custom validator for your component. So yes, you can replace a form-group or form-array with a custom ControlValueAcessor component.

**Comment by bzums** [comment] 2017-02-10 10:54
@cghislai 

Ok I see, that would look like http://plnkr.co/edit/zXqqA6UxeevIiK4GdTJU?p=preview, right?

I see some "problems" with this approach:
* you can not stick to the reactive forms approach int he child component...
* ... and therefore the structure of your form does not exactly match the structure of your data (I mean strictly speaking `user` is a group of controls, not just one control)
* you always have to write a custom validator for a complex child component (or am I missing something?)

In my opinion this two points can be real pain points if you are working with complex forms (complex child components with deep nesting, say 3 or 4 levels). 

However, I recently started using the following "pattern": 

App component:
```typescript
@Component({
  selector: 'my-app',
  template: `
    <div>
      <form [formGroup]="form">
        <input formControlName="name"><br>
        <input formControlName="email"><br>
        <my-child formGroupName="user"></my-child>
        <button type="submit">Register</button>
      </form>
      {{form.value | json }}
    </div>
  `
})
export class App {
   public form = new FormGroup({
     name: new FormControl('My Name'),
     email: new FormControl('my@mail.com'),
     user: new FormGroup({
       username: new FormControl(''),
       avatar: new FormControl('')
     })
   });
}
```
Child component:
```typescript
@Component({
  selector: 'my-child',
  template: `
    <h4>Child</h4>
    <div [formGroup]="formGroupName.control">
      <input formControlName="username"><br>
      <input formControlName="avatar">
    </div>
  `,
  providers: [
    {provide: NG_VALUE_ACCESSOR, useExisting: Child, multi: true}
  ]
})

export class Child {
  constructor(public formGroupName: FormGroupName) {}
}
```
See http://plnkr.co/edit/49zhsmMgIOpEa6fvESxX?p=preview

I am wondering whether this is more elegant and especially whether this can fail in edge cases, I dont know DI so well and I am unsure whether this could lead to problems.

The only con in this approach IMO is that you still have to use `[formGroup]="..."` and the injected `formControlName` but you can stick to the reactive approach in the child component, you do not have to build custom validators all the time and you keep the structure between data and form in sync.

All in all it looks cleaner and more elegant to me, what do you think?

**Comment by kravda** [comment] 2017-03-22 22:44
@bzums
But if I should add novalidate into form  and required into child input 
can I get username control from form in submit method in paren contol to check errors etc?

**Comment by bzums** [comment] 2017-03-29 06:59
@kravda 
I am not sure what you mean exactly but you can access each child control from the parent control via `youFormGroup.get('someChild')` method. `get` also accepts an array to access deeply nested child controls: `youFormGroup.get(['some', 'child'])`.

I am wondering whether there is a reason that the mentioned method is not documented in https://angular.io/docs/ts/latest/api/forms/index/AbstractControl-class.html?

**Comment by tx8821** [comment] 2017-06-12 06:28
This feature is really needed. Using ControlValueAccessor is cumbersome to say the least. Please reopen the issue!

**Comment by bzums** [comment] 2017-06-12 09:33
@tx8821 for the time being the solution explained in https://github.com/angular/angular/issues/9600#issuecomment-278915107 is at least more comfortable than using `ControlValueAccessor` imo.

**Comment by GetKraken** [comment] 2017-06-12 15:10
I see this has been closed. Has this been solved or can it be solved in a different way? I am trying to use template driven forms as they seem simpler but I cant figure out how to have a form with a component in it and have the validation rolled up to the form. This really hinders reuse across forms where I have the same control on a couple of forms. 
Can someone point me toward the feature for this please or is the solution as @devpreview suggests? 
@bzums suggestion looks to be using reactive forms.

**Comment by cghislai** [comment] 2017-06-12 19:35
The solution is to have a model - and a ControlValueAccessor component - for each of your hierarchy level. Comment https://github.com/angular/angular/issues/9600#issuecomment-238639149 points to the solution

**Comment by reppners** [comment] 2017-07-25 12:18
The team I'm working on had the requirement to implement components which in itself are already quite complex forms, but those components also need to plug into a parent form for having top-level validation to e.g. disable saving but also 

The actual complexity arrives with the fact that those components are not siblings or direct children but may be deeply nested and even separated across child routes. The current state of angular forms makes this use-case really hard because there is no way to declaratively connect child forms / form-groups with a parent form.

Our solution to this is a directive which will inject the parent form if present and will register/deregister itself on the parent form. This enables declarative support of nested form elements across component boundaries without the need to pass form-groups or use model-driven forms throughout the application.

You can checkout a basic implementation in this [plunkr](https://plnkr.co/edit/Jipw4AVNbdXqflfBNKMY?p=preview)

**Comment by andreev-artem** [comment] 2017-07-25 15:24
Another possible workaround:

```javascript
@Directive({
    selector: '[provide-parent-form]',
    providers: [
        {
            provide: ControlContainer,
            useFactory: function (form: NgForm) {
                return form;
            },
            deps: [NgForm]
        }
    ]
})
export class ProvideParentForm {}

```

Just place this directive in a child component somewhere at the top of nodes hierarchy (before any ngModel).

**Comment by penleychan** [comment] 2017-08-01 14:01
@andreev-artem solutions works great for template driven, however it doesn't contains inside `ngModelGroup`. So in addition to andreev's directive you can have another directive to handle from inside `ngModelGroup`: 

``` typescript
export const modelGroupProvider: any = {
  provide: ControlContainer,
  useExisting: forwardRef(() => NgModelGroup)
};

@Directive({
  selector: '[provide-parent-form-group]',
  providers: [
    modelGroupProvider
  ]
})
export class ProvideParentFormGroupDirective {}
```

Now your controls will be contained inside your defined `ngModelGroup`

Usage is similar to andreev's solution.

**Comment by martinobordin** [comment] 2017-09-01 08:27
@andreev-artem  or @penleychan  could you please provide a working sample? thanks

**Comment by joerter** [comment] 2017-09-04 04:47
@martinobordin I made this Plunker that shows @andreev-artem's solution. It works perfectly!
https://plnkr.co/edit/N5P3CS

**Comment by martinobordin** [comment] 2017-09-04 09:04
@joerter Thanks. I forked the Plunker in order to make it more similar to my scenario (dynamic add\remove  of child component) , but the directive is not working as expected (two way binding is wrong, validation of parent form is not reliable).

Do you know why\how to solve?

https://plnkr.co/edit/VSUzQtrtEmXSIEPzAjXb

**Comment by Pontiley** [comment] 2017-09-09 11:25
@penleychan, can you please made your example in Plunker, when I try to do it, I given error:  Error: No provider for ControlContainer! I use the last Angular version.

**Comment by martinobordin** [comment] 2017-09-09 11:35
@joerter I made some changes in order to add\remove dynamically child components:
https://plnkr.co/edit/WzFsoFbWRgIAu8Nv3Lst?p=preview

However if you delete for example the first item ('Apple) and then you add another child, the second binding will be wrong. How can this be solved?

**Comment by penleychan** [comment] 2017-09-09 17:12
@Pontiley here you go: https://plnkr.co/edit/FlQhpmeKEZdb52SBcFbL?p=preview

**Comment by penleychan** [comment] 2017-09-09 17:22
@Pontiley Here you go: https://plnkr.co/edit/FlQhpmeKEZdb52SBcFbL?p=preview

**Comment by Pontiley** [comment] 2017-09-09 19:43
@penleychan , thanks!

**Comment by Steven-Garcia** [comment] 2017-10-16 12:53
I do not believe this issue-feature should be closed. Angular really lacks of a simple way to nest template-driven forms, those of us trying to migrate old AngularJS apps to newer Angular are really going through huge grief when having a complex "old-style" template driven form with deep nesting of up to 5 levels.

  I would love to see a way for us to be able to migrate our apps with less pain when it comes to forms, I really liked AngularJS, but now our team is pondering whether we should move to other technologies because of time-consuming milestones in our migration such as this

**Comment by zoechi** [comment] 2017-10-16 21:35
@Steven-Garcia just implement ControlValueAccessor

**Comment by Steven-Garcia** [comment] 2017-10-17 08:55
@zoechi  Maybe I could implement that, but it wouldn't be a case of "just" implementing it, after looking through the documentation it seems to me like it would be asking for boilerplate code, what I think should be the key is a straight-forward communication between parent and child, just like we had in AngularJS, with no need to add code

**Comment by Steven-Garcia** [comment] 2017-10-17 13:02
@martinobordin @andreev-artem  I've been all morning trying your solutions on a complex Jhipster generated project, I've come to the point where I have the exact same code in the plunker as I do in the application (except for using `templateUrl: [link to the file]`, rather than `template:[raw tags]`)

   Unfortunately they just wont work on a more complex scenario, there is just no way to get the json pipe to print the values in the child

  [plunker](https://plnkr.co/edit/pSeomxNmqNuO3ti0690r?p=preview)

**Comment by martinobordin** [comment] 2017-10-17 13:19
@Steven-Garcia  I don't know how jhipster works, anyway I have some issues too with that plunker (it's not my solution, a user suggests me that). Nobody seems to have an idea on how to solve it.

I'm disappointed as you. It should be supported out-of-the-box by Angular itself.
It's should be common (and a best practice) to split complex forms in multiple components. It seems supported only using ReactiveForms, but I don't like that approach.

**Comment by joerter** [comment] 2017-10-17 14:25
@Steven-Garcia I believe I fixed your issue in this [plunk](https://plnkr.co/edit/FKHcBldOIrReAVq5tdPr?p=preview).

The issue is when you use an ngFor to insert child components, the name property for the children's inputs end up being the same. That's why you only saw one of the children's input properties bound to the form. The change I made was to use the index of the child to make their name properties unique so that they can each be bound to the form.

**Comment by Steven-Garcia** [comment] 2017-10-17 14:37
@joerter Thank you for that, however, I wasn't concerned about the performance of the plunker, it's the fact that this very same code doesn't work at all in a more complex scenario in order to pick the values from the child component and save them all in a same object to the database

**Comment by alexzuza** [comment] 2017-10-21 07:40
Another possible solution can be found here https://medium.com/@a.yurich.zuev/angular-nested-template-driven-form-4a3de2042475

**Comment by penleychan** [comment] 2017-10-22 21:36
@alexzuza Wow, that was easy... I didn't know `Component` had a property `viewProviders`. Thanks!

**Comment by JavanXD** [comment] 2017-10-25 09:09
@penleychan 
Thanks for your solution.
`viewProviders: [{ provide: ControlContainer, useExisting: NgForm }]` works fine thanks!
But
```
@Component({
	...
	viewProviders: [
		{
			provide: ControlContainer,
			useExisting: forwardRef(() => NgModelGroup)
		}
	] 
})
```
doesn't work i am getting this Error-Message:
>  ERROR Error: No provider for NgModelGroup!

I also tried it with the directive same error

**Comment by JavanXD** [comment] 2017-10-25 09:17
@Steven-Garcia @joerter 
You don't need to append the name attribute by the index. By adding [ngModelGroup]="i" it gets nicely structurized.
```
addressHistory valid? {{ myHistoryGroup.valid }}
<ul ngModelGroup="addressHistory" #myHistoryGroup="ngModelGroup">
    <li *ngFor="let i = index; let address of addressHistory">
        <div [ngModelGroup]="i" #myLi="ngModelGroup">
        address valid? {{ myLi.valid }}
            <input type="text" [(ngModel)]="address.state" name="state" />
            <input type="text" [(ngModel)]="address.country" name="country" />
        </div>
    </li>
</ul>

<!--
#myForm.value will be like this:
{ "addressHistory": { "0": { ... }, "1": { ... }}, ... }
-->
```

**Comment by alexzuza** [comment] 2017-10-25 09:32
@JavanXD You're doing something wrong. Create plunker to reproduce

**Comment by JavanXD** [comment] 2017-10-25 11:26
@alexzuza Okay thanks, no need of that anymore, i ended up passing my ngModelGroup to the child-component and added from the child manually the ngModels to the parents ngModelGroup:
**Parent-Component:**
```html
<div [ngModelGroup]="i" #myAddressGroup="ngModelGroup">
	<ngbd-datepicker [modelGroup]="myAddressGroup"  [date]="address.validFrom"></ngbd-datepicker>
</div>
```

**Child-Component (ngbd-datepicker):**

_Typescript:_
```typescript
/* append ngModel to parents NgModelGroup */
@Input()
private modelGroup: NgModelGroup;

@ViewChild('dateCtrl')
private dateCtrl: NgModel;

private registered: boolean = false;

ngAfterViewChecked() {
	if (!this.registered && this.modelGroup) {
		if (this.modelGroup.control) {
			this.modelGroup.control.registerControl('validFrom', this.dateCtrl.control);
			this.registered = true;
		}
	}
}
```
_Template:_
```html
<input type="text" name="validFrom" [(ngModel)]="dateModel" #dateCtrl="ngModel" [required]="myFlag" />
```
source: http://plnkr.co/edit/xJr1ZZBkSz3TuT43Tpwm 


@zoechi This feature request was closed correctly (by the viewProviders it became simple and without ControlValueAccessor) but it may require a better documentation about nested forms.

**Comment by alexzuza** [comment] 2017-10-25 12:08
@JavanXD Check this out http://plnkr.co/edit/fAIzKuuueMzfhVAhQ0lz?p=preview

**Comment by mtraynham** [comment] 2017-12-06 00:28
I'm fairly new to how Angular DI works, and the solution provided here for using `viewProviders` seems to work properly.  If by chance you had a component that could be within an `ngForm` or an `ngModelGroup`, does the following solution for checking if there's a `ngModelGroup` first work as I should expect?

```ts
@Component({
    selector: 'my-form',
    viewProviders: [{
        provide: ControlContainer,
        deps: [NgForm, [new Optional(), NgModelGroup]],
        useFactory: (ngForm: NgForm, ngModelGroup: NgModelGroup): ControlContainer =>
            ngModelGroup || ngForm
    }]
})
```

**Comment by wustdong** [comment] 2018-01-31 08:46
@andreev-artem 
Thanks for your solution.
selector: '[provide-parent-form]' works fine thanks! it works great!
 But when I try to ng build --prod --aot, error throws:

> ERROR in Error: Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (position 20:23 in the original .ts file), resolving symbol ProvideParentFormDirective in /src/app/directives/_provide-parent-form.directive.ts

and I solved it by replace the anonymous (lambda) method to explicitly method:
```
import { Directive, forwardRef } from '@angular/core';
import { NgForm, ControlContainer, NgModelGroup } from '@angular/forms';

export function test(form: NgForm) {
  return form;
}
@Directive({
  selector: '[appProvideParentForm]',
  providers: [
      {
          provide: ControlContainer,
          useFactory: test,
          deps: [NgForm]
      }
  ]
})
export class ProvideParentFormDirective { }
```
Reference solution can be found [here](https://github.com/angular/angular-cli/issues/3707). In case someone needed.

**Comment by hidegh** [comment] 2018-03-26 19:41
I got a different issue. Basic samples do work, but when I do apply AbstractControlValueAccessor and use ngModel binding on a custom component, i do need to provide a name for my component. Due to that the form get's messy, both the component name as the ngFromGroup name does create a group.

```
                    <form #form="ngForm">

                        <div class="form-group">
                            <label>FirstName</label>
                            <input class="form-control" [(ngModel)]="Data.FirstName" name="FirstName" uiName="FirstName">
                        </div>

                        <div ngModelGroup="HomeAddress1">
                            <TestProspectAddress [(ngModel)]="Data.HomeAddress" name="HomeAddress2" uiName="HomeAddress"></TestProspectAddress>
                        </div>

                        <hr/>

                        <div ngModelGroup="MailAddress1">
                            <TestProspectAddress [(ngModel)]="Data.MailAddress" name="MailAddress2" uiName="MailAddress"></TestProspectAddress>
                        </div>

                    </form>
```
So i get something like this:
```
{
	"LastName": "LANA",
	"SSN": "123-45-6789",
	"HomeAddress1": {
		"HomeAddress2": {
			"Location": {}
		},
		"Location": {
			"Location": {}
		}
	},
	"MailAddress1": {
		"MailAddress2": {
			"City": "Any city",
			"Location": {
				"Description": "My location"
			},
			"Street": "Main road 1",
			"Zip": "12345",
			"State": "TX",
			"Country": "US"
		},
		"Street": "Main road 1",
		"City": "Any city",
		"Zip": "12345",
		"State": "TX",
		"Country": "US",
		"Location": {
			"Location": {
				"Description": "My location"
			},
			"Description": "My location"
		}
	}
}
```
What do I need to change in my address component to:

1.  let it work without the ngModelGroup="HomeAddress1" around the component selector - in case I put a name tag and a ngModel there

2. or simply make it just honor only the ngModelGroup="HomeAddress1" and ignore the ngModel and name on the component tag

The address component's code:
```
@Component({
    selector: 'TestProspectAddress',
    templateUrl: './prospect.address.html',
    viewProviders: [
        { provide: ControlContainer, useExisting: NgForm },
        { provide: ControlContainer, useExisting: forwardRef(() => NgModelGroup) },
    ],
    providers: [ MakeProvider(TestProspectAddress) ]
})

export class TestProspectAddress extends AbstractValueAccessor<any>{
```

**Comment by Skholastik** [comment] 2018-12-10 14:00
First of all, @andreev-artem , thank you for solution! 

In simple case it's works good. But when i wrapped a form with my custom form component the next error occurs: 

`
angular.js:15536 Error: StaticInjectorError(AppModule)[ControlContainer -> NgForm]: 
  StaticInjectorError(Platform: core)[ControlContainer -> NgForm]: 
    NullInjectorError: No provider for NgForm!
`

I tried to solve the issue and came up with the bad workaround:
https://codesandbox.io/s/w6x1l4ork5

Instead of:
```
 provide: ControlContainer,
      useFactory: function (form: FormComponent) {
        return form.ngForm;
      },
      deps: [FormComponent]
    } 
```
I added:

```
  provide: ControlContainer,
      useFactory: function (form: FormComponent) {
        return form.ngForm;
      },
      deps: [FormComponent]
    }
```

And in a template the directive looks like : 

`
<ng-container *ngIf="true" appProvideParentForm>
`

Without  the hack `*ngIf="true"` ngForm will not initialize. 

I have two questions about this: 

1) How i could avoid to add '*ngIf="true"'?
2) And how i could provide 'ngForm' in my case?

**Comment by chris13524** [comment] 2019-08-13 20:47
I've used [this](https://medium.com/@a.yurich.zuev/angular-nested-template-driven-form-4a3de2042475) with great success. However, it requires that the parent always provide a `<form>` and isn't optional anymore.

Today I managed to come up with this alternative that seems to work fine, plus the ability for the form to be optional:

	viewProviders: [{
	    provide: ControlContainer,
	    useFactory: (ngForm: NgForm) => ngForm,
	    deps: [[new Optional(), new SkipSelf(), NgForm]]
	}]

**Comment by andzejsw** [comment] 2019-08-20 07:51
```
import { ControlContainer, NgForm } from '@angular/forms';

@Component({
    ....
    viewProviders: [{ provide: ControlContainer, useExisting: NgForm }],
})
```
This works for my nested form. Just needs to be added to components, witch ones directly contains inputs

**Comment by maxime1992** [comment] 2019-08-20 08:45
@advgal about your [comment](https://github.com/angular/angular/issues/9600#issuecomment-245193670) you can check `ngx-sub-form`: https://github.com/cloudnc/ngx-sub-form
