### ISSUE TITLE
Angular Universal do not use absolute url to make api calls

### ISSUE THREAD

**Issue by Rafarel** [angular/angular#50412] opened 2023-03-02 13:31 UTC
# 🐞 Bug report

#### What modules are related to this issue?

- [ ] builders
- [ ] common
- [x] express-engine

### Is this a regression?

I don't know but the Angular documentation says that express-engine should take care of converting relative urls to absolute urls.

You can read it here: https://angular.io/guide/universal#using-absolute-urls-for-http-data-requests-on-the-server

### Description

I have an SSR angular application and an api in a mono repo.
I request my api from my angular app using relatives urls (eg: /api/test). Then my reverse proxy (proxy.conf in dev, traeffik in staging/prod) redirects the request from http://localhost:4200/api/test to http://localhost:3333/test

The SSR is unable to fetch relatives urls, they should be converted as absolute urls.

The Angular documentation says that express-engine should take care of converting relative urls to absolute urls, but it do not think that is the case ? I don't know.

You can read the doc here: https://angular.io/guide/universal#using-absolute-urls-for-http-data-requests-on-the-server

Thanks for your help!

## 🔬 Minimal Reproduction

The minimal reproduction is available here: https://github.com/Rafarel/angular-universal-test

It's a mono repo made with nx.

To use it, just clone it then :

- `npm install` to install deps.
- `npx nx serve api` to serve the api.
- `npx nx serve-ssr my-app` to serve the angular app with SSR enabled.

When you open http://localhost:4200/ you will see `ERROR NetworkError` on the SSR output.

If you use the `nx serve my-app` there is no error, but it is not served by the SSR.

## 🔥 Exception or Error

The following error is happening on SSR server app output when you open http://localhost:4200

<pre><code>
ERROR NetworkError
    at send (./node_modules/xhr2/lib/xhr2.js:281:19)
    at observer (./node_modules/@angular/common/fesm2020/http.mjs:1937:17)
    at _trySubscribe (./node_modules/rxjs/dist/cjs/internal/Observable.js:41:25)
    at cb (./node_modules/rxjs/dist/cjs/internal/Observable.js:35:31)
    at errorContext (./node_modules/rxjs/dist/cjs/internal/util/errorContext.js:22:9)
    at subscribe (./node_modules/rxjs/dist/cjs/internal/Observable.js:26:24)
    at _task (./node_modules/@angular/platform-server/fesm2020/platform-server.mjs:172:32)
    at observer (./node_modules/@angular/platform-server/fesm2020/platform-server.mjs:210:13)
    at _trySubscribe (./node_modules/rxjs/dist/cjs/internal/Observable.js:41:25)
    at <anonymous> (./node_modules/rxjs/dist/cjs/internal/Observable.js:35:31)
</code></pre>

## 🌍 Your Environment

I'm working with a NX monorepo, here is my `nx report` output of my project (not the test one)

<pre><code>
>  NX   Report complete - copy this into the issue template

   Node : 18.13.0
   OS   : darwin arm64
   npm  : 8.19.3
   
   nx : 15.4.2
   @nrwl/angular : 15.4.2
   @nrwl/cypress : 15.4.2
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.4.2
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.4.2
   @nrwl/expo : Not Found
   @nrwl/express : 15.4.2
   @nrwl/jest : 15.4.2
   @nrwl/js : 15.4.2
   @nrwl/linter : 15.4.2
   @nrwl/nest : 15.4.2
   @nrwl/next : Not Found
   @nrwl/node : 15.4.2
   @nrwl/nx-cloud : 15.0.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : 15.4.2
   @nrwl/workspace : 15.4.2
   @nrwl/vite : Not Found
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
         @fortawesome/angular-fontawesome: 0.12.1
         @nguniversal/express-engine: 15.0.0
         @nguniversal/builders: 15.0.0
         ng-extract-i18n-merge: 2.4.0
         nx-stylelint: 15.0.0
</code></pre>

**Comment by alan-agius4** [comment] 2023-09-01 16:14
Duplicate of https://github.com/angular/angular/issues/51626

**Closed by alan-agius4** 2023-09-01 16:14 UTC
Labels: area: server, area: common/http
