### ISSUE TITLE
Ivy fails with firebase

### ISSUE THREAD

**Issue by StephenFluin** [angular/angular#29939] opened 2019-04-16 20:30 UTC
# 🐞 bug report

### Is this a regression?
Yes, this is a regression

### Description
AngularFire works well with v7 and v8 without Ivy, but turning on Ivy prevents me from doing builds.

## 🔬 Minimal Reproduction
https://github.com/StephenFluin/ivy-firebase-repro/commits/master

1. Create new app
1. Add firebase & realtime database
1. Update to v8 (works)
1. Turn on Ivy (fails)

## 🔥 Exception or Error
<pre><code>
$ ng build --prod --source-map
 10% building 3/3 modules 0 active 10% building 3/4 modules 1 active ...ce/te 10% building 3/4 modules 1 active ...ce/test/my-firebase-app/ 3 3 92%                                                                                                                   
Date: 2019-04-16T20:25:06.901Z - Hash: 9f64d91c0f0234d69e04 - Time: 29315ms
1 unchanged chunks
chunk {0} runtime-es5.741402d1d47331ce975c.js, runtime-es5.741402d1d47331ce975c.js.map (runtime) 1.47 kB [entry] [rendered]
chunk {2} polyfills-es5.db1ca970d93c3d6854ef.js, polyfills-es5.db1ca970d93c3d6854ef.js.map (polyfills) 111 kB [initial] [rendered]
chunk {3} styles.3f414165053c69a0bfa1.css, styles.3f414165053c69a0bfa1.css.map (styles) 59 bytes [initial] [rendered]

WARNING in ./src/app/app.component.ts 24:200-222
"export 'AngularFireDatabase' (imported as 'i1') was not found in '@angular/fire/database'

WARNING in ./src/app/app.component.ts 44:38-60
"export 'AngularFireDatabase' (imported as 'i1') was not found in '@angular/fire/database'

WARNING in ./src/app/app.module.ts 24:16-41
"export 'AngularFireDatabaseModule' was not found in '@angular/fire/database'

WARNING in ./src/app/app.module.ts 30:48-73
"export 'AngularFireDatabaseModule' was not found in '@angular/fire/database'

WARNING in ./src/app/app.module.ts 48:20-45
"export 'AngularFireDatabaseModule' was not found in '@angular/fire/database'

WARNING in ./src/app/app.module.ts 30:26-46
"export 'AngularFireModule' (imported as 'i1') was not found in '@angular/fire'

WARNING in ./src/app/app.module.ts 16:16-33
"export 'AngularFireModule' was not found in '@angular/fire'

WARNING in ./src/app/app.module.ts 40:20-37
"export 'AngularFireModule' was not found in '@angular/fire'

ERROR in ./node_modules/@angular/fire/__ivy_ngcc__/index.js
Module not found: Error: Can't resolve './public_api' in '/usr/local/google/home/stephenfluin/workspace/test/my-firebase-app/node_modules/@angular/fire/__ivy_ngcc__'
ERROR in ./node_modules/@angular/fire/__ivy_ngcc__/database/index.js
Module not found: Error: Can't resolve './public_api' in '/usr/local/google/home/stephenfluin/workspace/test/my-firebase-app/node_modules/@angular/fire/__ivy_ngcc__/database'
ERROR in chunk main [initial]
main-es5.b02852a167e1fde953ab.js
/usr/local/google/home/stephenfluin/workspace/test/my-firebase-app/node_modules/@angular-devkit/build-optimizer/src/build-optimizer/webpack-loader.js??ref--16-0!/usr/local/google/home/stephenfluin/workspace/test/my-firebase-app/node_modules/@ngtools/webpack/src/index.js!/usr/local/google/home/stephenfluin/workspace/test/my-firebase-app/src/main.ts 77d72dccf0f5f5a9ddce59dbb9489804
Cannot read property 'isProvided' of null

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.0.0-beta.15
Node: 11.10.0
OS: linux x64
Angular: 8.0.0-beta.12
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.0-beta.15
@angular-devkit/build-angular     0.800.0-beta.15
@angular-devkit/build-optimizer   0.800.0-beta.15
@angular-devkit/build-webpack     0.800.0-beta.15
@angular-devkit/core              8.0.0-beta.15
@angular-devkit/schematics        8.0.0-beta.15
@angular/@types                   <error>
@angular/cli                      8.0.0-beta.15
@angular/events                   <error>
@angular/fire                     5.1.2
@angular/firebase                 <error>
@angular/rxjs                     <error>
@angular/source-map               <error>
@angular/tslib                    <error>
@angular/typescript               <error>
@ngtools/webpack                  8.0.0-beta.15
@schematics/angular               8.0.0-beta.15
@schematics/update                0.800.0-beta.15
rxjs                              6.4.0
typescript                        3.4.3
webpack                           4.29.6

</code></pre>

**Comment by m-henderson** [comment] 2019-04-21 00:39
@StephenFluin have you looked into the issue at all and could maybe provide your findings? If not, no big deal(: would save me some legwork

**Comment by JoostK** [comment] 2019-04-21 15:12
Initial findings are that the CLI will first kickof ngcc with `"browser", "module", "main"`, resulting in the ES5 sources being analyzed and because it is the first request, will also update the `.d.ts` files.

That is all fine, however the ES5 analysis ends up completely empty. I found using `ts.Program.getSourceFiles().map(sf => sf.fileName).filter(n => n.endsWith('.js'))` that the program's sources only included the entry point's `index.js`, its import to `./public_api` was not within the list.

So, what is going on? Some more debugging let me to the root problem here: the typing files and JS source files are all located in the same directory. Hence, when TypeScript resolves `./public_api` its module resolution system will end up with `./public_api.d.ts`! Hence, the actually interesting source files that ngcc needs to process never become part of the analysis program; causing ngcc to conclude there's nothing to update in the source nor in the typings but the package is marked as being processed regardless (which is correct).

We'll probably need some way of customizing TypeScript's module resolution system here, such that it prefers '.js' files over '.d.ts'.

cc @m-henderson

**Comment by sarunint** [comment] 2019-04-21 18:35
Relatable: angular/angularfire2#2021

**Comment by JoostK** [comment] 2019-04-21 18:48
@sarunint Thanks for your investigation, it is spot on! If I knew that before it would have saved me a lot of time :) I am actually trying to come up with customized module resolution logic in ngcc to support this.

**Comment by sarunint** [comment] 2019-04-21 18:53
Well, I spent _hours_ on why ES5 bundle won't compile. Lol

**Comment by JoostK** [comment] 2019-04-21 18:55
> Well, I spent _hours_ on why ES5 bundle won't compile. Lol

Me too 🤡

**Comment by sarunint** [comment] 2019-04-21 18:57
Now that the root cause is known, are we going to fix `ivy-ngcc`, or fix AngularFire?

**Comment by sarunint** [comment] 2019-04-21 19:02
By "fixing AngularFire", I mean "make amendments to Angular Package Format to specify that the bundles (ESM/FESM 5/2015) must be in a subfolder, then make changes to AngularFire".

**Comment by sarunint** [comment] 2019-04-21 19:34
Ah, I see the PR now.

**Comment by JoostK** [comment] 2019-04-21 19:34
@sarunint I will discuss with @alxhub and @petebacondarwin. I opened #30017 with the alternative module resolution strategy that should circumvent the issue from ngcc's side.

**Comment by StephenFluin** [comment] 2019-05-13 21:51
@alxhub says we don't correctly compile this under ES5.

**Comment by vladimirdjurdjevic** [comment] 2019-05-30 22:00
Any progress on this? It works with ng serve and ivy enabled, but with build --prod it fails

**Comment by JoostK** [comment] 2019-06-01 20:09
@vladimirdjurdjevic Should be fixed once #30591 is in.

**Comment by kara** [comment] 2019-08-20 17:20
https://github.com/angular/angular/pull/30591 is in

**Closed by kara** 2019-08-20 17:20 UTC
Labels: comp: core, comp: ivy, comp: ngcc, freq2: medium, severity3: broken, type: bug/fix
