### ISSUE TITLE
The layout on the official site is broken

### ISSUE THREAD

**Issue by splincode** [angular/angular#21520] opened 2018-01-13 12:17 UTC
1. Why there is a vertical scroll and the shadows are hidden?

![image](https://user-images.githubusercontent.com/12021443/34905891-3b24b900-f873-11e7-9d7c-052e11f8f908.png)

2. Not at full height

![image](https://user-images.githubusercontent.com/12021443/34905904-797d75b6-f873-11e7-8d25-f5716255e74d.png)

3. The side menu is not hidden

![](https://habrastorage.org/webt/bh/7t/63/bh7t63vug7xllatjk5mr5qikshi.gif)

**Comment by gkalpak** [comment] 2018-01-15 14:21
Thx for reporting these issues. I addressed (2) and (3) in #21538.

Point 1 would require a slightly more significant layout change (of the kind that is difficult to test for regression against). Since it only becomes really noticable at <400px, I wonder if it is worth fixing.

@petebacondarwin, @IgorMinar: What is our minimum "supported" screen width?

**Comment by splincode** [comment] 2018-01-15 15:10
https://angular-ru.github.io/

For the Russian-language layout, we have a bit of fix where there are shadows

**Comment by IgorMinar** [comment] 2018-02-07 00:06
I believe this is now resolved via #21538. If I misunderstood, please file a new issue. thanks

**Closed by IgorMinar** 2018-02-07 00:06 UTC
Labels: comp: aio, effort1: easy (hours), freq1: low, type: bug/fix
