### ISSUE TITLE
Component class with more than one parameter in the constructor results in a typescript compilation error

### ISSUE THREAD

**Issue by Krustie101** [angular/angular#4034] opened 2015-09-07 23:23 UTC
Consider the following example

```
@Component({
	selector: "my-comp"
})
@View({
	template: "<div>My Compponent</div>"
})
export class MyComponent {
	constructor(dep1:Dependency1,dep2:Dependency2){};
}
```

This generates (ts 1.6-beta) a compilation error TS2345: Argument of type 'typeof MyComponent' is not assignable to parameter of type 'Type'.

This boils down to an equivalent simpler example that generates a compilation error:
```
var dec : TypeDecorator;

@dec
export class MyClass {
 	constructor(x1:number,x2:number){};
}
```

The problem lies in the fact that the definition of Type contains a "new" declaration with 1 argument causing MyClass not to be assignable to Type.

**Comment by rolandjitsu** [comment] 2015-09-08 05:31
@Krustie101 this is a duplicate of [#3972](https://github.com/angular/angular/issues/3972).
@mhevery probably this should be closed.

**Comment by Krustie101** [comment] 2015-09-08 20:31
Sorry for the duplication. 

The current definition of type also implies that an interface cannot be assigned to a Type, so that applying bind(.) to an interface also results in a compilation error in Typescript. Is this expected behaviour?

**Comment by mhevery** [comment] 2015-09-12 03:42
closing as dup of #3972

**Closed by mhevery** 2015-09-12 03:42 UTC
