### ISSUE TITLE
Server side rendered HTML has Angular attributes that are not valid in W3C validator.

### ISSUE THREAD

**Issue by islam95** [angular/angular#42826] opened 2021-07-12 12:51 UTC
# 🐞 Bug report

#### What modules are related to this issue?

- [ ] aspnetcore-engine
- [ ] builders
- [ ] common
- [x] express-engine
- [ ] hapi-engine

### Is this a regression?

No.

### Description

W3C validator does not like Angular attributes (`_ngcontent...`, `_nghost...`, etc). Thus, an HTML page becomes invalid in W3C validator (see [example](https://validator.w3.org/nu/?doc=https%3A%2F%2Fskyeng.ru%2F)).
Angular attributes like `_ngcontent` should not be in HTML rendered from server.

## 🔬 Minimal Reproduction

1. Open https://angular.io/guide/universal
2. Download example project from the link: `Note: Download the finished sample code`
3. `yarn install`
4. `yarn build:ssr`
5. `yarn serve:ssr`
6. Open suggested link `Node Express server listening on http://localhost:4000`
7. View Page Source
8. See `_ngcontent`, `_nghost` and similar attributes.

## 🔥 Exception or Error

<pre><code>

</code></pre>

## 🌍 Your Environment

<pre><code>
Angular CLI: 12.1.1
Node: 12.18.1
Package Manager: yarn 2.4.2
OS: darwin x64

Angular: 12.1.1
... animations, cdk, cli, common, compiler, core, elements
... forms, language-service, localize, material
... material-moment-adapter, platform-browser
... platform-browser-dynamic, platform-server, router
... youtube-player

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1201.1
@angular-devkit/build-angular   12.1.1
@angular-devkit/core            12.1.1
@angular-devkit/schematics      12.1.1
@angular/compiler-cli           12.1.1+26.sha-0a17e98
@angular/flex-layout            12.0.0-beta.34
@ngtools/webpack                12.1.1
@nguniversal/builders           12.1.0
@nguniversal/express-engine     10.1.0
@schematics/angular             12.1.1
rxjs                            6.6.7
typescript                      4.3.4
webpack                         5.41.1

</code></pre>

**Comment by petebacondarwin** [comment] 2021-07-12 13:44
This is basically a duplicate of https://github.com/angular/angular/pull/40595

**Comment by alan-agius4** [comment] 2021-07-12 17:23
Duplicate of #25355

**Closed by alan-agius4** 2021-07-12 17:23 UTC

**Comment by islam95** [comment] 2021-07-12 21:32
@alan-agius4 what about W3C validation which is important for our SEO team. I couldn't find answers in threads posted here. Only something related to European standards that should allow such attributes. 
Could you please elaborate on W3C validation issues with Angular attributes in SSR html?
