### ISSUE TITLE
Writing to signals is not allowed in rxjs `tap` `map` operators

### ISSUE THREAD

**Issue by aegonz** [angular/angular#50279] opened 2023-05-13 21:02 UTC
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

```
export class SystemTableComponent {

  isLoading = signal(true);

  dataStream$ = new BehaviorSubject<null>(null);

  dataStreamObservable = this.dataStream$.pipe(
    tap((_) => {
      this.isLoading.set(true);
    })
  )
}

constructor(private state: StateService) {
  effect(() => {
    this.state.gatewayUrl();
    this.dataStream$.next(null);
  });
 }
}
```

Service:

```
export class StateService {
  env = signal<string>(
    localStorage.getItem('env') || environment['defaultEnv']
  );

  gatewayUrl = computed<string>(
    () => UrlMapping[this.env()] + 'gateway/v1/graphql'
  );

  gatewayChanged$ = new Subject<null>();

  constructor() {
    effect(() => {
      // Subscribe to gatewayUrl changes
      this.gatewayUrl();
      // Trigger gatewayChanged event
      this.gatewayChanged$.next(null);
    });
  }
}
```

2 different signals that are not related throws writable constraints error.

> 0600: Writing to signals is not allowed in a `computed` or an `effect` by default.

Even when subscribing to the `gatewayChanged$` subject the same error shows up
```

    this.state.gatewayChanged$.pipe(takeUntilDestroyed()).subscribe({
      next: (_) => {
        this.pageIndex = 0;
        this.dataStream$.next(null);
      },
    });
```

### Please provide the exception or error you saw

```true
0600: Writing to signals is not allowed in a `computed` or an `effect` by default.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular 16.0
Node 18
```

**Comment by JeanMeche** [comment] 2023-05-13 21:22
How do you subscribe to `dataStreamObservable ` ?  You use the `AsyncPipe` ?

**Comment by aegonz** [comment] 2023-05-13 21:27
> 

In the constructor of `SystemTableComponent` I left it out in the original comment

```
  constructor(private state: MainStateService) {
    effect(() => {
      this.state.gatewayUrl();
      this.dataStream$.next(null);
    });

    this.dataStreamObservable.pipe(takeUntilDestroyed()).subscribe({
      next: (v) => {
        this.dataSource.setData(v);
      },
    });
  }
```

**Comment by aegonz** [comment] 2023-05-13 21:32
Changing the effect add `{ allowSignalWrites: true }` does fix the issue but still not sure why it would affect an unrelated signal

```
    effect(
      () => {
        this.state.gatewayUrl();
        this.pageIndex = 0;
        this.dataStream$.next(null);
      },
      { allowSignalWrites: true }
    );
```

**Comment by al-mart** [comment] 2023-05-14 18:42
Because of these risks, setting signals is disallowed by default in effects, but can be enabled if absolutely necessary.
This is what I have found in angular docs. 
If you dive deeper into the source you will see that signals set method checks whether its consumer enables updates
source... 
`  
set(newValue: T): void {
    if (!(activeConsumer?.consumerAllowSignalWrites !== false)) {
      throwInvalidWriteToSignalError();
    }
 }
`

**Comment by JeanMeche** [comment] 2023-05-25 20:52
@pkozlowski-opensource  here is a repro provided by @montella1507

https://stackblitz.com/edit/ngrx-seed-jdlhj4

We can notice that the issue doesn't happen when the signal isn't updated synchronously (for example by adding a `delay(100)` before the tap.

**Comment by montella1507** [comment] 2023-05-25 21:23
That repro is based on someone else (sorry i dont remember). 
This is maybe even better example..
https://stackblitz.com/edit/angular-ehcsk4?file=src%2Fmain.ts
```
 id$ = this.store
    .select(appFeature.selectId)
    .pipe(tap((id) => this.store.dispatch(Actions.setDataID({ dataId: id }))));
    
    {{id$ | async}}
```
Store.dispatch() is basically signal.set() internally.

**Comment by JeanMeche** [comment] 2023-05-25 21:26
Yeah the root issue is that a signal is being updated from a synchronous observable triggered by subscription from the temlate via the `AsyncPipe`.

**Comment by alxhub** [comment] 2023-05-30 19:48
Closing as a duplicate of #50382.

**Closed by alxhub** 2023-05-30 19:48 UTC
Labels: needs reproduction, area: core, needs: clarification, core: reactivity
