### ISSUE TITLE
Memory getting increased when dynamically change values?

### ISSUE THREAD

**Issue by kumaresan-subramani** [angular/angular#27975] opened 2019-01-08 04:13 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....

### Is this a regression?

 Don't know

### Description

 I have created one angular project with grid control, when i change grid colums dynamically, memory getting increased, i don't know why it is getting increased. Here i am doing destroy properly but memory getting increased. I could not solve this issue

## 🔬 Minimal Reproduction

 
Step 1: download sample using below link [ [http://www.syncfusion.com/downloads/support/directtrac/general/ze/memoryLeak673661023](http://www.syncfusion.com/downloads/support/directtrac/general/ze/memoryLeak673661023) ]

Step 2: Run following commands 

>   npm install
>       npm start

Step 3:
Then you will see application demo in  `http://localhost:3000/`. First take screenshot for memory initially.

Step 4:
 Then press start button and wait for 15 secs, then you will see **console window** show message like **`15 completed`**. Then again take screenshot for to check memory size

Step 5:
  Finally you will see memory leak

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version: 5.2.0**
**npm Version:5.6.0**
**node Version: v8.11.3**

</code></pre>

**Anything else relevant?**

I have referred below two links and tried methods which are prescribed in those link but they wont solve this issue

https://stackoverflow.com/questions/22397484/how-to-reduce-remove-memory-leaks-in-angular-application

https://www.twilio.com/blog/prevent-memory-leaks-angular-observable-ngondestroy

**Comment by kumaresan-subramani** [comment] 2019-01-08 07:11
Any update on this guys?
This will totally affect my application

**Comment by Airblader** [comment] 2019-01-08 18:23
Asking for "an update" after three hours is pretty bold.

**Comment by ericmartinezr** [comment] 2019-01-08 18:51
I'm pretty sure this is a dup of https://github.com/angular/angular/issues/27980

**Comment by ChrisDahmCS** [comment] 2019-01-08 18:53
@ericmartinezr I was about to comment the same thing- proof of non ng issue in (#27980)[https://github.com/angular/angular/issues/27980#issuecomment-452398872]

**Comment by mhevery** [comment] 2019-01-08 23:19
Thanks for reporting this issue. However this issue is a duplicate of an existing issue #27980. Please subscribe to that issue for future updates.

**Closed by mhevery** 2019-01-08 23:19 UTC
Labels: comp: core & compiler
