### ISSUE TITLE
Angular Service working is not working in offline mode after deploying to Git hub pages

### ISSUE THREAD

**Issue by tejindermakkar786** [angular/angular#32680] opened 2019-09-14 06:37 UTC
# 🚀 Issue while registering the Service worker

### Description

> I am trying to create PWA in angular 8. Service worker works well on offline mode on local. I created a production build using ng build --prop --base-href https://tejindermakkar786.github.io/angular-pwa/ . It is not working in offline mode. I tried each and every thing but nothing worked.

here is my manifest.json file

```
{
  "name": "angular-pwa-demo",
  "short_name": "angular-pwa-demo",
  "theme_color": "#1976d2",
  "background_color": "#fafafa",
  "display": "standalone",
  "scope": "/",
  "start_url": "https://tejindermakkar786.github.io/angular-pwa/",
  "icons": [
    {
      "src": "assets/icons/icon-72x72.png",
      "sizes": "72x72",
      "type": "image/png"
    },
    {
      "src": "assets/icons/icon-96x96.png",
      "sizes": "96x96",
      "type": "image/png"
    },
    {
      "src": "assets/icons/icon-128x128.png",
      "sizes": "128x128",
      "type": "image/png"
    },
    {
      "src": "assets/icons/icon-144x144.png",
      "sizes": "144x144",
      "type": "image/png"
    },
    {
      "src": "assets/icons/icon-152x152.png",
      "sizes": "152x152",
      "type": "image/png"
    },
    {
      "src": "assets/icons/icon-192x192.png",
      "sizes": "192x192",
      "type": "image/png"
    },
    {
      "src": "assets/icons/icon-384x384.png",
      "sizes": "384x384",
      "type": "image/png"
    },
    {
      "src": "assets/icons/icon-512x512.png",
      "sizes": "512x512",
      "type": "image/png"
    }
  ]
}
```
here is my ngsw.json file

```
{
  "configVersion": 1,
  "timestamp": 1568443220100,
  "index": "https://tejindermakkar786.github.io/angular-pwa/index.html",
  "assetGroups": [
    {
      "name": "app",
      "installMode": "prefetch",
      "updateMode": "prefetch",
      "urls": [
        "https://tejindermakkar786.github.io/angular-pwa/favicon.ico",
        "https://tejindermakkar786.github.io/angular-pwa/index.html",
        "https://tejindermakkar786.github.io/angular-pwa/main-es2015.8dc58f73b76c72c46bf2.js",
        "https://tejindermakkar786.github.io/angular-pwa/main-es5.8abda753a83882ff0fce.js",
        "https://tejindermakkar786.github.io/angular-pwa/manifest.webmanifest",
        "https://tejindermakkar786.github.io/angular-pwa/polyfills-es2015.1c1c6e14f86c4c3438f0.js",
        "https://tejindermakkar786.github.io/angular-pwa/polyfills-es5.2b7c6b11d4d572f932e2.js",
        "https://tejindermakkar786.github.io/angular-pwa/runtime-es2015.ead83b817a6b516c7860.js",
        "https://tejindermakkar786.github.io/angular-pwa/runtime-es5.3771a4c9022b9875174b.js",
        "https://tejindermakkar786.github.io/angular-pwa/styles.da22db97b71058f021df.css"
      ],
      "patterns": []
    },
    {
      "name": "assets",
      "installMode": "lazy",
      "updateMode": "prefetch",
      "urls": [
        "https://tejindermakkar786.github.io/angular-pwa/assets/icons/icon-128x128.png",
        "https://tejindermakkar786.github.io/angular-pwa/assets/icons/icon-144x144.png",
        "https://tejindermakkar786.github.io/angular-pwa/assets/icons/icon-152x152.png",
        "https://tejindermakkar786.github.io/angular-pwa/assets/icons/icon-192x192.png",
        "https://tejindermakkar786.github.io/angular-pwa/assets/icons/icon-384x384.png",
        "https://tejindermakkar786.github.io/angular-pwa/assets/icons/icon-512x512.png",
        "https://tejindermakkar786.github.io/angular-pwa/assets/icons/icon-72x72.png",
        "https://tejindermakkar786.github.io/angular-pwa/assets/icons/icon-96x96.png"
      ],
      "patterns": []
    }
  ],
  "dataGroups": [],
  "hashTable": {
    "https://tejindermakkar786.github.io/angular-pwa/assets/icons/icon-128x128.png": "dae3b6ed49bdaf4327b92531d4b5b4a5d30c7532",
    "https://tejindermakkar786.github.io/angular-pwa/assets/icons/icon-144x144.png": "b0bd89982e08f9bd2b642928f5391915b74799a7",
    "https://tejindermakkar786.github.io/angular-pwa/assets/icons/icon-152x152.png": "7479a9477815dfd9668d60f8b3b2fba709b91310",
    "https://tejindermakkar786.github.io/angular-pwa/assets/icons/icon-192x192.png": "1abd80d431a237a853ce38147d8c63752f10933b",
    "https://tejindermakkar786.github.io/angular-pwa/assets/icons/icon-384x384.png": "329749cd6393768d3131ed6304c136b1ca05f2fd",
    "https://tejindermakkar786.github.io/angular-pwa/assets/icons/icon-512x512.png": "559d9c4318b45a1f2b10596bbb4c960fe521dbcc",
    "https://tejindermakkar786.github.io/angular-pwa/assets/icons/icon-72x72.png": "c457e56089a36952cd67156f9996bc4ce54a5ed9",
    "https://tejindermakkar786.github.io/angular-pwa/assets/icons/icon-96x96.png": "3914125a4b445bf111c5627875fc190f560daa41",
    "https://tejindermakkar786.github.io/angular-pwa/favicon.ico": "84161b857f5c547e3699ddfbffc6d8d737542e01",
    "https://tejindermakkar786.github.io/angular-pwa/index.html": "15d17bedb546ee6ea6b72e827e8e5961c9a67517",
    "https://tejindermakkar786.github.io/angular-pwa/main-es2015.8dc58f73b76c72c46bf2.js": "25a3968484c4258de4466cc37556203972617a16",
    "https://tejindermakkar786.github.io/angular-pwa/main-es5.8abda753a83882ff0fce.js": "2d98aa49035207f8a2543a6fbdba1abef9eb2624",
    "https://tejindermakkar786.github.io/angular-pwa/manifest.webmanifest": "5a3cedd45e75809ff6013202187297cdcabf276d",
    "https://tejindermakkar786.github.io/angular-pwa/polyfills-es2015.1c1c6e14f86c4c3438f0.js": "08c97940ba93ccc4121b85df6911d86011ef3fb8",
    "https://tejindermakkar786.github.io/angular-pwa/polyfills-es5.2b7c6b11d4d572f932e2.js": "9d9b583788005b7e2dc51d2b965f7c09b9180c60",
    "https://tejindermakkar786.github.io/angular-pwa/runtime-es2015.ead83b817a6b516c7860.js": "b62956c2192bfe5516d6374e753773901ed50ec5",
    "https://tejindermakkar786.github.io/angular-pwa/runtime-es5.3771a4c9022b9875174b.js": "b62956c2192bfe5516d6374e753773901ed50ec5",
    "https://tejindermakkar786.github.io/angular-pwa/styles.da22db97b71058f021df.css": "d487850f1d3853ea0e212d4c2af3bffeadf708dd"
  },
  "navigationUrls": [
    {
      "positive": true,
      "regex": "^\\/.*$"
    },
    {
      "positive": false,
      "regex": "^\\/(?:.+\\/)?[^/]*\\.[^/]*$"
    },
    {
      "positive": false,
      "regex": "^\\/(?:.+\\/)?[^/]*__[^/]*$"
    },
    {
      "positive": false,
      "regex": "^\\/(?:.+\\/)?[^/]*__[^/]*\\/.*$"
    }
  ]
}
```
I don't know what I am doing wrong.

**Comment by gkalpak** [comment] 2019-09-14 13:58
This is a duplicate of #31316 (afaict). Please try the recommendations there.
(If this still doesn't help, please open a new issue.)

**Closed by gkalpak** 2019-09-14 13:58 UTC

**Comment by tejindermakkar786** [comment] 2019-09-15 07:21
@gkalpak  I have tried the solutions that you provided by changing the repository path but nothing happened. service worker is still not working in offline mode.
