### ISSUE TITLE
Making merged symbols with Type & InjectionToken behave seamlessly like a class

### ISSUE THREAD

**Issue by lemoinem** [angular/angular#26882] opened 2018-10-31 19:27 UTC
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
Currently, if a 3rd party module exports a class, and uses it as a token for a DI provide, it can be easily injected, simply by typing a constructor parameter.

However, if the library is updated to hide some internal details, and replace the class by a Type (interface or other aliased type), along with an InjectionToken, simply typing the parameter fails and nothing more can be done.

The application using the 3rd party library now has to add `@Inject(Type)` everywhere...

## Expected behavior
Although I understand the type cannot be expressed easily for a non-class type to automatically express DI. It would be great to be able to have a similar behavior by simply providing an InjectionToken to use along with a non-class type.

All these informations should be available at build time (i.e. the fact that the symbol used to Type the parameter also has a value attached to it, and even that this value is an InjectionToken<Type>).
Even if the value cannot be ascertained with this degree of precision, simply blindly using the value attached to the symbol would work for both class types and non-class types along with InjectionToken. It might even work for more advanced solutions out of the box (e.g., a value that's an `InjectionToken<Type> & SomethingElse`)

This would allow to easily expose only interfaces and keep internal details hidden.
Currently, users have to sprinkle their code with `@Inject(Type) param: Type` repeatedly...

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-gitter-y6nwsk

## What is the motivation / use case for changing the behavior?
Much better Developper Experience. Allow Library developper to much more easily expose a clean interface that'd prevent breakage in the future or use of internal methods.

## Environment
<pre><code>
Angular version: 6.0.2
 </code></pre>

**Comment by trotyl** [comment] 2018-11-01 01:34
The TypeScript `emitDecoratorMetadata` requires exact type, no type parameter can be used, see https://github.com/Microsoft/TypeScript/issues/9916 and https://github.com/Microsoft/TypeScript/issues/12703 for more information, `InjectionToken<Type> & SomethingElse` is a non-starter.

**Comment by lemoinem** [comment] 2018-11-01 14:51
@trotyl Alright, let's ignore the part about `InjectionToken<Type> & SomethingElse`.

Would the rest be possible?
i.e., Say I have a module (foo.ts) with
```ts
export type Foo = ...;
export const Foo = new InjectionToken<Foo>('Foo');
```

Would it be possible to do (bar.ts)
```ts
import { Foo } from 'foo';

export class BarService
{
   constructor(private foo: Foo)
   {
   }
}
```

And have it work, just as if Foo was a class, without an `@Inject(Foo)` annotation?

**Comment by trotyl** [comment] 2018-11-02 01:34
@lemoinem It won't work, TypeScript could distinguish identifier reference from type annotation, and wouldn't mistakenly link it to the identifier. You can simply have a try rather than guessing.

**Comment by trotyl** [comment] 2018-11-02 12:43
[`emitDecoratorMetadata`](https://www.typescriptlang.org/docs/handbook/decorators.html#metadata) is a pure TypeScript feature not specified to Angular, which powers the DI via type annotation in JIT.

**Comment by lemoinem** [comment] 2018-11-02 13:57
I guess, we will have to wait for Microsoft/TypeScript#3628...

**Comment by trotyl** [comment] 2018-11-17 15:40
A more elegant approach would be https://github.com/angular/angular/issues/25039 which enables DI without constructor like:

```typescript
class MyComp {
  foo = inject(SOME_TOKEN)
  bar = inject(SomeClass)
}
```

**Comment by lemoinem** [comment] 2018-11-19 18:38
This looks very interesting...

Being forced to have the constructor as the only DI entry-point has been a weakness in Angular since day 1. Especially when compared to other, more mature DI frameworks. Although I do understand the complications created by supporting setter-based injection, both for the DI framework and when creating Injectable classes.

Property initialization-based injection seems like the best of both world:
- Implicitly inherited,
- Easy to add new dependencies in inherited classes,
- Easy to override.

I'm really looking forward to having Ivy released :)

However, I believe #25039 is a different issue. From what I understand, what I am talking about is more like @dawidgarus's `@Autowire()` decorator than simply having access to `inject()` in the constructor. I don't see much difference between `constructor(@Inject(Token) private service: Token)` and `constructor(private service: Token = inject(Token))`.

I'll keep my issue opened until I can confirm #25039, a later feature built on top of it, or Ivy's DI framework, do offer an appropriate solution to this.

**Comment by trotyl** [comment] 2018-11-20 01:36
> Being forced to have the constructor as the only DI entry-point has been a weakness in Angular since day 1.

Property-based injection is considered a bad practice even in framework supports it, like [Java Spring](https://stackoverflow.com/questions/40620000/spring-autowire-on-properties-vs-constructor). So Angular avoids doing that from day 1.

> From what I understand, what I am talking about is more like @dawidgarus's `@Autowire()` decorator than simply having access to `inject()` in the constructor.

Please note `@Autowire()` was not proposed as an Angular feature, but one's own utility helper. And all of these approach happens in constructor

**Comment by lemoinem** [comment] 2018-11-21 18:56
> >Being forced to have the constructor as the only DI entry-point has been a weakness in Angular since day 1.
> 
> Property-based injection is considered a bad practice even in framework supports it, like Java Spring. So Angular avoids doing that from day 1.

This might be far from being the best practice, but it makes extending a class using DI a major pain. We have to copy the whole constructor and forward all the dependencies to `super()`.
If a parent class' new version needs a new dependency internally, everything extending it will break.
This makes providing abstract classes with default implementation extremely hard.
As I mentioned, yes, I am aware that property-based injection is more complex to implement. But it's still solves problems and makes for much more robust code in the end.




I have the feeling the original issue keeps being side-tracked... Maybe my point just wasn't clear enough, If that's the case, I'm sorry about that.

My point is that, DI currently has to either be unnecessarily verbose and always specify the Class/Type twice: `@Inject(Type) dependency: Type` or rely on internal implementation details (i.e. `Type` is implemented as a class).

As far as I can tell, most people will choose the second solution, as the syntax is much nicer and usually just works.

This makes it more difficult to implement a nice DI API for libraries, since once a class is provided and used as a DI token, changing it for an Interface + InjectionToken requires a backward compatibility breaking change.

My Feature Request is to be able to use `dependency: Type` **without** the `@Inject(Type)` decorator even when `Type` is not a class, but some different kind of value.

From what @trotyl says, It seems some features would need to land in Typescript first or would require some new feature in the Angular Compiler (which is itself a Typescript plugin of some kind, if I understand correctly)...

The constructor vs property-based DI debate is an entirely different and orthogonal debate.
Using `@Inject(Type)` vs `= inject(Type)`, although their implementation might quite different, seems like a minor syntactic difference, at most.
Both seem to miss the target at hand.

**Comment by trotyl** [comment] 2018-11-22 02:51
> or would require some new feature in the Angular Compiler (which is itself a Typescript plugin of some kind, if I understand correctly)...

The AOT process is only design to speed up rather than introducing new language semantics. Any runtime different between JIT and AOT would be critical to users.

**Comment by lemoinem** [comment] 2018-11-23 16:29
My point wouldn't be to have a difference between JIT and AOT, I never mentioned that. As far as I understand, the only difference between both is about when the compiler is called.
Maybe "Angular Compiler" is not the correct name. But ngc / the angular-cli is definitely some stuff for before both JIT and AOT. That's the level I'm referring to.

**Comment by trotyl** [comment] 2018-11-24 06:08
> But `ngc` / the angular-cli is definitely doing stuff before the JIT/AOT step.

`ngc` is only involved in AOT, not JIT.

**Comment by lemoinem** [comment] 2018-11-26 15:18
This is, again, completely beside my point.
But thanks for continuously correcting my misconceptions that have nothing to do with the issue at hands.

**Comment by trotyl** [comment] 2018-11-26 15:31
> But thanks for continuously correcting my misconceptions that have nothing to do with the issue at hands.

It would be fine if you can understand why that's not feasible.

**Comment by lemoinem** [comment] 2018-11-26 21:15
The typescript issue I referenced clearly mentions that it's possible to emit the necessary metadata using transformers api (and references a few projects that do just that):

- https://github.com/Microsoft/TypeScript/issues/3628#issuecomment-298234120
- https://github.com/Microsoft/TypeScript/issues/3628#issuecomment-322198096
- https://github.com/Microsoft/TypeScript/issues/3628#issuecomment-382416211

Indeed, I don't understand why it's not feasible with Angular.

**Comment by trotyl** [comment] 2018-11-27 00:54
Angular is not going to be a new language, any feature must be feasible via pure TypeScript/JavaScript, as explained above.

**Comment by lemoinem** [comment] 2018-11-27 14:47
Angular already is a new language: The template language is definitely not pure HTML/Typescript/Javascript.

Angular already uses transformers api:
- Angular Schematics
- https://github.com/angular/angular/tree/master/packages/compiler-cli/src/transformers
These include metadata-related transformers.

Sure, the Angular low level JS API can be interacted with using pure JS. Some features are typescript-only and cannot be used in pure JS (class-based DI, Decorators, etc.).
The feature I propose fits in this pattern.

**Comment by dawidgarus** [comment] 2018-11-27 16:11
@lemoinem Angular works with plain TypeScript. You can use only tsc to build your app and everything should work. Compiler-cli is not required, so no - Angular is not a new language.

**Comment by trotyl** [comment] 2018-11-28 02:35
> Yes, it does, but some features are lost when working directly with tsc.
> Some loss of functionality is already planed for packages not using the IVY compiler 

Nothing will be lost at the runtime, type-checking and intellisense are ergonomic enhancement for development experience, not about the framework API.

> It will not introduce new syntax.

It must also not changing TypeScript semantics, and result same runtime behavior as if they're executed as original TypeScript code.

> I don't see how you can say it's "not feasible" when similar processing are obviously already in place.

The purpose for build-time preprocessing is for performance improvement, no such processing (resulting in different runtime behavior) were ever used.

**Comment by mhevery** [comment] 2018-11-29 23:38
Closing as this requests is unfeasible. The problem is that type is design-time only concept and has no run-time representation.

**Closed by mhevery** 2018-11-29 23:38 UTC
Labels: comp: core & compiler
