### ISSUE TITLE
RouterLink does not cooperate with attribute directive to open in new tab

### ISSUE THREAD

**Issue by johnsonb2** [angular/angular#39493] opened 2020-10-29 18:18 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/router

### Is this a regression?

 No

### Description

When using the routerLink directive on an <a> element with a custom attribute directive that adds the attributes `target="_blank" ref="noopener noreferrer"` (to open the link in a new tab), the route is resolved in the current tab and a new tab is not opened. Directly adding these attributes within the HTML template does open the route in a new tab and not the current tab, as expected.

## 🔬 Minimal Reproduction

 https://stackblitz.com/edit/angular-ivy-rem7wl?

## 🌍  Your Environment

**Angular Version:**
<pre><code>Angular CLI: 10.2.0
Node: 12.8.1
OS: win32 x64

Angular: 10.2.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1002.0
@angular-devkit/build-angular   0.1002.0
@angular-devkit/core            10.2.0
@angular-devkit/schematics      10.2.0
@schematics/angular             10.2.0
@schematics/update              0.1002.0
rxjs                            6.6.3
typescript                      4.0.5
</code></pre>

**Comment by atscott** [comment] 2020-10-30 21:49
Closing as a duplicate of #13776.

The issue is somewhat twofold: both `RouterLink` and your directive have a host binding on the `target` attribute. The behavior for this situation is always likely to cause problems because of the collission.

Separately if that were not the case with colliding host bindings, like #13776, you cannot set the value of an input using a host binding from another directive. As a workaround, you can optionally inject the `RouterLinkActive` directive into your own directive and directly set the value for `target`: https://stackblitz.com/edit/angular-ivy-z715iq?file=src%2Fapp%2Fbrowser-tab-link.directive.ts

**Closed by atscott** 2020-10-30 21:49 UTC
Labels: comp: router
