### ISSUE TITLE
Strict template checking false positives

### ISSUE THREAD

**Issue by PhiLhoSoft** [angular/angular#40880] opened 2021-02-17 09:20 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/compiler (?)

### Is this a regression?

 Not really, coming from the experimental Ivy template compiler?

### Description

I wanted to activate some template checking angular compiler options:
```json
  "angularCompilerOptions": {
    "enableIvy": true,
    "strictInjectionParameters": true,
    "fullTemplateTypeCheck": true,
    "strictTemplates": true
  }
```
It works well, but I noticed some false positives (the code works!).

First issue is that I use a template for a specific sub-type of a variable:
```html
			<span
				*ngIf="!isCrumbGroup(crumb); else crumbGroup"
				(click)="triggerAction(crumb)"
				[title]="getLabel(crumb)"
			>{{ getLabel(crumb) }}</span>
			<ng-template #crumbGroup>
				<span (click)="alert(getMenuConfigFrom(crumb))">•••</span>
			</ng-template>
```
getMenuConfig is expecting an array, which is checked by the isCrumbGroup method. (Initially, it returned a boolean, and I had an error in the methods below too; worked better when returning an "v is Array" kind of value.)
I understand the template can be entered from elsewhere, but can't the compiler check the paths leading there?
If not (which I would understand), is there a way to specifically shut off such error locally?

Second issue is quite specific to an annotation we use in our projects: see the cast.ts file in the Stackblitz project.
Basically, we use it like this:
```typescript
@Input() @Cast(Boolean) readonly: boolean;
```
and it allows simple attributes:
```html
<span readonly="true"> (instead of <span [readonly]="true">
or even better
<span readonly> (with the default value, lack of annotation results in `false`)
```
which is simpler and more readable, IMHO.
But if the template compiler chokes on these, and if we must add some way to shut it off, the benefit is lost, and we have to change a lot our codebase! 😑

## 🔬 Minimal Reproduction

I made a little project, a simplified version of the component I have, reproducing both errors (the readonly part is added for demonstration purpose) :
https://stackblitz.com/edit/angular-ivy-template-check-fail?file=tsconfig.json
Enable the angularCompilerOptions there and see the two errors.

## 🔥 Exception or Error
<pre><code>
Error in src/app/crumbs/crumbs.component.html (11:44)
Argument of type 'string | { label: string; action?: () => any; } | Crumb[]' is not assignable to parameter of type 'Crumb[]'.
Type 'string' is not assignable to type 'Crumb[]'.
</code></pre>
and
<pre><code>
Error in src/app/app.component.html (22:4)
Type 'string' is not assignable to type 'boolean'.
</code></pre>
(In Stackblitz, we don't get both errors, I have to remove one source of error to show the other.)

## 🌍  Your Environment

**Angular Version:**

See also Stackblitz's package.json.

<pre><code>
Angular CLI: 11.2.0
Node: 15.6.0
OS: win32 x64

Angular: 11.2.0
... cdk, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1002.1
@angular-devkit/build-angular      0.1102.0
@angular-devkit/build-ng-packagr   0.1002.1
@angular-devkit/core               10.2.1
@angular-devkit/schematics         11.2.0
@schematics/angular                11.2.0
@schematics/update                 0.1102.0
ng-packagr                         11.2.1
rxjs                               6.6.3
typescript                         4.1.5
</code></pre>

**Comment by JoostK** [comment] 2021-02-17 10:30
The problem you're observing for the `else` template is tracked in #21504. One way to workaround the error is to use `$any(crumb)`, but that will of course remove any type-safety.

Regarding the `Cast` helper, there is a way to make it work with strict template checking using a custom static field, [please see the docs](https://angular.io/guide/template-typecheck#input-setter-coercion) for more info.

**Comment by JoostK** [comment] 2021-02-17 10:32
I will go ahead and close this as a duplicate of #21504, but feel free to follow up with your experience on the setter coercion functionality.

**Closed by JoostK** 2021-02-17 10:32 UTC
Labels: comp: compiler, compiler: template type-checking

**Comment by PhiLhoSoft** [comment] 2021-02-18 07:53
Adding `static ngAcceptInputType_readonly: boolean | '';` after the declaration of the Cast'ed variable removed the error, thanks.
Too bad we cannot (probably) add it automatically with the annotation, it is a bit heavy-handed.
But at least, it is a usable fix, and the annotation still ensure the type coercion for the attribute used without value.

And `<span (click)="alert(getMenuConfigFrom($any(crumb)))">•••</span>` solved my other issue.

I wasn't aware of the page you point to, many thanks for these solutions!
