### ISSUE TITLE
Angular router param is not escaped.

### ISSUE THREAD

**Issue by hadson172** [angular/angular#40517] opened 2021-01-22 15:36 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/router

### Is this a regression?

No idea. When i was searching on web for solution, i found information that slashes are correctly escaped.

### Description

const myObject = 'https://www.google.com/';
`<a [routerLink]="[myObject, 'edit']">Link</a>`
Angular router will generate url : 
`https:/www.google.com/edit`

What i would expect is to have fully escaped param passed to router link. Is it bug or by design ? Is it possible to escape required params in angular router?

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-jzhghx?file=src/app/app.component.html
## 🔥 Exception or Error
<pre><code>

None
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
11.0.8
</code></pre>

**Comment by atscott** [comment] 2021-01-22 17:28
Duplicate of #13872, #24567
In order to handle relative navigations (`./`, `../`, etc), the very first command in the list does not serialize the slashes. 
Secondly, it's not really a goal of the router/routerLink to handle external urls. This is unlikely to change, but is tracked by #24567 nevertheless.

**Closed by atscott** 2021-01-22 17:28 UTC
Labels: comp: router, router: directives
