### ISSUE TITLE
Async pipe causes setters to fire even when input value hasn't changed

### ISSUE THREAD

**Issue by rarmatei** [angular/angular#25966] opened 2018-09-14 13:33 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[x] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Accessing deeply nested object properties when binding to an input works as expected with simple values:

```html
<hello [name]="nonAsyncNames.name"></hello>
```

```js
    setInterval(() => {
      this.nonAsyncNames = {name: 'some string'};
    }, 1000);
```

As expected, **the `setter` for the `name` property in the `Hello` component will only be called once**.

```js
  // this will only be called once
  @Input() set name(val: string) {
    this._name = val;
   console.log("name set, new val:", val) 
  };
```

 Even though the reference to the `nonAsyncNames` object changes, the value of the final property `name` doesn't - so it works perfectly.

On the other hand, taking the same example with an `async` pipe, we get different behavior:

```html
<hello [name]="(asyncNames | async).name"></hello>
```

```js
  asyncNames = interval(1000).pipe(
    map(x => ({name: 'some string'}))
  );
```

In `HelloComponent.ts`:

```js
  // called MULTIPLE times
  @Input() set name(val: string) {
    this._name = val;
   console.log("name set, new val:", val) 
  };
```

The setter in the component is called multiple times. 

## Expected behavior

Unless I am missing something, it seems that both examples should behave in the same way: the child setter should only get called if the new input is different from the previous one.

I've managed to fix it for now by just creating another observable that emits `name` directly:

```js
asyncNames.map(x => x.name)
```

and then using the `async` pipe on it directly. But I'm still wondering if by default both examples should be the same.

In real-world cases, this might cause performance issues if more expensive logic is executed in the setter.
In the following example, this might cause issues:

```js
//NgRx redux state

const weatherState= {
  season: { /* ... */ }.
  wind: { windSpeed: 10 }
}
```

```html
   <season-label [name]="(state | async).season.name"></season-label>
```

As we're using Redux, any time any change to the `windSpeed` happens, it will create a new instance of `weatherState`. That means any time `windSpeed` changes (often), it would cause the setter of the `season-label` component to fire as well - something that might not be expected, as `seasons` change much less often than wind speed.

## Minimal reproduction of the problem with instructions

I've created this stackblitz with the above examples:
https://stackblitz.com/edit/angular-v3mqed?file=src%2Fapp%2Fapp.component.ts

## Environment

<pre><code>
Angular version: 6.0.0

Browser:
- [x] Chrome (desktop) version 68.0.3440.106
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by rarmatei** [comment] 2018-09-14 15:37
@mlc-mlapis you're right, it looks like the same issue - thank you for identifying! Should I just go ahead and close this one because @mhevery closed the other one, or is it worth keeping around because of the slightly different Redux example I gave which might suggest a more real-world problem caused by this?

**Comment by mlc-mlapis** [comment] 2018-09-14 16:10
@rarmatei ... I am still not sure what should be the final decision. As you could see even Miško answer wasn't really satisfying because of missing argumentation why exactly is the behavior expected. There is even identified the part of the code which looks to be responsible for that `a bit strange` behavior. I personally still think that there is a space how to improve the code.

**Comment by kykint** [comment] 2019-10-05 10:58
Is any update on this issue? It is still reproducible and definitely a bug.

**Comment by RobertAKARobin** [comment] 2020-01-15 01:45
According to #23933 this is "working as intended." If this is the case, what would be the correct way to detect changes in an array?

**Comment by pkozlowski-opensource** [comment] 2020-02-18 19:43
This continues to be issue in ivy: https://ng-run.com/edit/A2UpujIZ52IF4eCaI7SF

It is true that today it "works as designed / implemented" but from the comments it is clear that is _not_ working by intended by users. Keeping this one open to see if / how we could improve it.

**Comment by JoostK** [comment] 2021-05-13 23:32
This has been fixed in Angular 10 as the `async` pipe has stopped using `WrappedValue` in #36633. The wrapped value would force a dirty binding, causing the setters to be invoked.

**Closed by JoostK** 2021-05-13 23:32 UTC
Labels: P3, comp: common, comp: core, freq1: low, triage #1, type: bug/fix
