### ISSUE TITLE
How can you get the version of angular2 at runtime?

### ISSUE THREAD

**Issue by born2net** [angular/angular#7032] opened 2016-02-12 05:40 UTC
How can you get the version of angular2 at runtime?
will help for debugging and stack capture, is it possible to get ng2 ver in runtime?

regards

Sean

**Comment by gdi2290** [comment] 2016-02-12 06:05
related https://github.com/angular/angular/issues/6619

**Comment by pkozlowski-opensource** [comment] 2016-10-04 09:24
This is duplicate of #1357

**Closed by pkozlowski-opensource** 2016-10-04 09:24 UTC
