### ISSUE TITLE
Control flow migration fails for async pipe with unboxing of observable.

### ISSUE THREAD

**Issue by sfabriece** [angular/angular#52756] opened 2023-11-09 21:46 UTC
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

I run the control flow migration on my code and it failed compilation.

before:
<ng-container *ngIf="value$ | async; let value">
	{{value}}
</ng-container>

after:
@if (value$ | async; let value) {
{{value}}
}

### Please provide the exception or error you saw

```true
Property 'value' does not exist on type 'Page'. Did you mean 'value$'?
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.0.0
Node: 20.9.0
Package Manager: yarn 1.22.19
OS: win32 x64

Angular: 17.0.1
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic    
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.0
@angular-devkit/build-angular   17.0.0
@angular-devkit/core            17.0.0
@angular-devkit/schematics      17.0.0
@angular/cdk                    17.0.0
@angular/cli                    17.0.0
@schematics/angular             17.0.0
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.2
```

**Comment by AnthonyFr75** [comment] 2023-11-10 20:30
Hi,
Could you assign it to me ?

**Comment by alxhub** [comment] 2023-11-12 09:30
The issue is that the migration should be producing `as value` not `let value`.

**Comment by AnthonyFr75** [comment] 2023-11-12 16:40
Ok 👍

**Closed** 2023-11-20 16:58 UTC
Labels: area: migrations, core: control flow
