### ISSUE TITLE
Perf: Remove `enableProdMode` and use `CompilerConfig.devMode`

### ISSUE THREAD

**Issue by tbosch** [angular/angular#12200] opened 2016-10-10 16:36 UTC
The user already specifies whether he wants a dev or production build for his application in the Ng2 compiler setting `devMode`. Right now, we ask the user to tell this to Angular again during runtime via `enableProdMode`. And the setting has to agree what was used in the compiler setting, otherwise Angular does not work.

Instead, we should remove the flag that is triggered by `enableProdMode` and generate the right providers in the app injector. 

For this, we might need new properties on providers, e.g.
`{provide: Renderer, useExisting: DebugDomRenderer, env: 'dev'}`.

This will allow tree shakers to remove more of Angular core in production builds.

**Comment by DzmitryShylovich** [comment] 2016-12-11 12:58
Related to https://github.com/angular/angular/issues/6118

**Comment by clcaza** [comment] 2017-11-04 03:20
I think this is caused by angular cli。

**build without --target=production** 

I build angular cli project：
`ng build --environment=prod`

the relative part in vendor.js

`var _devMode = true;
var _runModeLocked = false;
var _platform;
var ALLOW_MULTIPLE_PLATFORMS = new InjectionToken('AllowMultipleToken');
/**
 * Disable Angular's development mode, which turns off assertions and other
 * checks within the framework.
 *
 * One important assertion this disables verifies that a change detection pass
 * does not result in additional changes to any bindings (also known as
 * unidirectional data flow).
 *
 * \@stable
 * @return {?}
 */
function enableProdMode() {
    if (_runModeLocked) {
        throw new Error('Cannot enable prod mode after platform setup.');
    }
    _devMode = false;
}
/**
 * Returns whether Angular is in development mode. After called once,
 * the value is locked and won't change any more.
 *
 * By default, this is true, unless a user calls `enableProdMode` before calling this.
 *
 * \@experimental APIs related to application bootstrap are currently under review.
 * @return {?}
 */
function isDevMode() {
    _runModeLocked = true;
    return _devMode;
}`

variable _runModeLocked initialize is false。it only changes to true when we call isDevMode(). 

**build with --target=production** 

`ng build --prod`

the relative part in vendor.js
`
function ot() { if (No) throw new Error("Cannot enable prod mode after platform setup.");
                Ro = !1 }

function st() { return No = !0, Ro }

No = !1,

Ro = function(t) {
                function e(e, n, r, i, o) { t.call(this), this.initialState = e, this.condition = n, this.iterate = r, this.resultSelector = i, this.scheduler = o } return jo(e, t), e.create = function(t, n, r, i, o) { return 1 == arguments.length ? new e(t.initialState, t.condition, t.iterate, t.resultSelector || Io, t.scheduler) : void 0 === i || g(i) ? new e(t, n, r, Io, i) : new e(t, n, r, i, o) }, e.prototype._subscribe = function(t) { var n = this.initialState; if (this.scheduler) return this.scheduler.schedule(e.dispatch, 0, { subscriber: t, iterate: this.iterate, condition: this.condition, resultSelector: this.resultSelector, state: n }); for (var r = this, i = r.condition, o = r.resultSelector, s = r.iterate;;) { if (i) { var a = void 0; try { a = i(n) } catch (e) { return void t.error(e) } if (!a) { t.complete(); break } } var u = void 0; try { u = o(n) } catch (e) { return void t.error(e) } if (t.next(u), t.closed) break; try { n = s(n) } catch (e) { return void t.error(e) } } }, e.dispatch = function(t) { var e = t.subscriber,
                        n = t.condition; if (!e.closed) { if (t.needIterate) try { t.state = t.iterate(t.state) } catch (t) { return void e.error(t) } else t.needIterate = !0; if (n) { var r = void 0; try { r = n(t.state) } catch (t) { return void e.error(t) } if (!r) return void e.complete(); if (e.closed) return } var i; try { i = t.resultSelector(t.state) } catch (t) { return void e.error(t) } if (!e.closed && (e.next(i), !e.closed)) return this.schedule(t) } }, e }(fi),

No = Ro.create;
`
the variable No initiate !1(false)，then  reassign RO.create.

I don't clear whether if RO.create change the No value to true.

**Comment by alexeagle** [comment] 2018-08-13 16:35
I think this is obsolete, we have a new `ngDevMode` symbol that will be used by Ivy - @mhevery is there a tracking issue for that?

**Closed** 2018-09-07 23:27 UTC
Labels: comp: core & compiler, comp: performance, fixed by Ivy, freq1: low, type: feature
