### ISSUE TITLE
[(ng-model)] behaves buggy in extreme use case

### ISSUE THREAD

**Issue by forforeach** [angular/angular#5808] opened 2015-12-10 19:16 UTC
When you type extremely fast, the [(ng-model)] behaves buggy. 

When I did a debug I found next condition inside NgModel directive:
```typescript
if (isPropertyUpdated(changes, this.viewModel)) {
  this._control.updateValue(this.model);
  this.viewModel = this.model;
}
```
[Here](https://github.com/angular/angular/blob/master/modules/angular2/src/common/forms/directives/ng_model.ts#L81) is the reference to the source.
I suppose that the code inside this condition should run only when the model property is updated by the user of ng-model directive. Actually, when you try to type, for instance, '123123' very very fast the events, that are emitted by the code below, notify the model in late.
```typescript
  viewToModelUpdate(newValue: any): void {
    this.viewModel = newValue;
    ObservableWrapper.callEmit(this.update, newValue);
  }
```
[Here](https://github.com/angular/angular/blob/master/modules/angular2/src/common/forms/directives/ng_model.ts#L95) is the reference to the source.
This lateness causes update of the `_control` and then of input itself, due to next code: 
```typescript
  // model -> view
  control.registerOnChange(newValue => dir.valueAccessor.writeValue(newValue));
```
[Here](https://github.com/angular/angular/blob/master/modules/angular2/src/common/forms/directives/shared.ts#L41) is the reference to the source.
This process isn't visible to human eye due to its speed, but when you debug it looks like the input box is . 

I work on laptop with Windows 10. I successfully reproduced it on latest Chrome version and latest Edge version. Also tried on latest Firefox, but it reproduces less frequently (I believe that it is due to slower event dispatch). 

You can reproduce it [here](http://plnkr.co/edit/4PVILSxFJCMQipiY3gUT?p=preview), but you should debug the source of angular. You can do it by hitting break point inside next condition
```javascript
if (shared_1.isPropertyUpdated(changes, this.viewModel))
```
under `NgModel.prototype.ngOnChanges` function.

![reproducing](http://i.giphy.com/26tP89Pu81UW7MazK.gif)
Note, that you have to write **extremely** fast!

**Comment by forforeach** [comment] 2015-12-14 06:09
Anyone?

**Comment by forforeach** [comment] 2015-12-18 09:19
Anyone?

**Comment by gdi2290** [comment] 2015-12-18 09:21
can you reproduce this in beta?

**Comment by forforeach** [comment] 2015-12-18 09:36
Hi Patrick,
Yes, I do. With the same scenario, as before. [Here](http://plnkr.co/edit/AoL73IfHS3WqJcrNjOTP?p=preview) is the updated plunkr.

**Comment by JurajMlich** [comment] 2016-01-06 09:27
The consequence of this bug may also be that when you have the cursor **not** at the end of the text and you type extremely fast, as you said, **the cursor goes to the end**. The bug is much more noticeable in Firefox making using inputs / textareas unusable in that browser.

**Comment by radek-holy** [comment] 2016-01-06 09:29
(looks related to https://github.com/angular/angular/issues/3075)

**Comment by robwormald** [comment] 2016-01-06 09:58
@forforeach can you try http://plnkr.co/edit/GmgJaqr4ROGGKqhxqHWw?p=preview and see if you can replicate it? i have an idea of where this is coming from, but would like to see if the quick tweak i did fixes it.

**Comment by JurajMlich** [comment] 2016-01-06 09:59
Suppose you have `Nice` in the input. You write `Hello` before that very fast, so that you have `HelloNice`. If I understand this issue right, the content of the input is changed after `HelloNice` to `HellNice` and than back to `HelloNice` and when you delete something from the value of an input, the cursor goes to the end. It would delete `o`.

**Comment by JurajMlich** [comment] 2016-01-06 10:03
@robwormald I cannot, looks like it works.

**Comment by forforeach** [comment] 2016-01-06 10:10
@robwormald your plnkr isn't work.
```
Refused to execute script from 'https://cdn.rawgit.com/anonymous/de94f32c2078318fdd0b/raw/7cb92bceae5617e36331685b39fed0923a386dbe/gistfile1.txt' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
```

**Comment by JurajMlich** [comment] 2016-01-06 10:16
@forforeach Try it in Firefox.

**Comment by robwormald** [comment] 2016-01-06 10:20
derp, my fault: try this http://plnkr.co/edit/DDZ1hN5ZNJzZh7PHD6o0?p=preview

**Comment by radek-holy** [comment] 2016-01-06 10:25
Works for me.

**Comment by forforeach** [comment] 2016-01-06 10:28
@robwormald looks like it's fixed. I tried to reproduce it a few times with no success.

**Comment by robwormald** [comment] 2016-01-07 00:00
@forforeach i'm going to close this one in favor of tracking it in #6311, which is the broader solution which covers this case (it's whats implemented in the above plunk). cheers!

**Closed by robwormald** 2016-01-07 00:00 UTC
