### ISSUE TITLE
Angular 2 Version "~2.0.1" Internet Explorer "SystemJS Syntax Error"

### ISSUE THREAD

**Issue by blubberbo** [angular/angular#14066] opened 2017-01-23 15:09 UTC
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When opening my Angular 2 application in Internet Explorer (10 or 11), I get the error `(SystemJS) Syntax Error"`

**Expected behavior**
The application works in Chrome and Firefox, so I would expect it to work in IE as well. 

**Minimal reproduction of the problem with instructions**
I went to recreate a bare-bones application to see if it works and it didn't, so then I went even more basic and just went to look at the Angular 2 Quickstart example here: [https://angular.io/docs/ts/latest/quickstart.html](https://angular.io/docs/ts/latest/quickstart.html) and noticed the link "QuickStart example on Plunker" does not render as a in Internet Explorer (it is a custom html tag for an angular 2 application). I tried copy and pasting the link to IE and it does not work either. I cannot find any Angular 2 Applications that work in IE.

**What is the motivation / use case for changing the behavior?**
I would like my application to work in IE as well

**Please tell us about your environment:**
Windows, .NET, Visual Studio, NPM

* **Angular version:** 2.0.X
2.0.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
IE 10, 11 (earlier versions as well I would guess)
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

thank you

**Comment by DzmitryShylovich** [comment] 2017-01-23 15:11
Probably you need a polyfill https://angular.io/docs/ts/latest/guide/browser-support.html

**Comment by blubberbo** [comment] 2017-01-23 15:12
@DzmitryShylovich currently I am using:
`<script src="../node_modules/core-js/client/shim.min.js"></script>
<script src="../node_modules/zone.js/dist/zone.js"></script>
<script src="../node_modules/reflect-metadata/Reflect.js"></script>
<script src="../node_modules/systemjs/dist/system.src.js"></script>`

but it still doesn't work

**Comment by DzmitryShylovich** [comment] 2017-01-23 15:16
> https://angular.io/docs/ts/latest/quickstart.html and noticed the link "QuickStart example on Plunker" does not render as a in Internet Explorer

Can't reproduce. Works fine for me

**Comment by tytskyi** [comment] 2017-01-23 15:18
@blubberbo what's your View Mode in IE? Probably Compatibility?

**Comment by blubberbo** [comment] 2017-01-23 17:23
@DzmitryShylovich That is strange. When I load the website `https://angular.io/docs/ts/latest/quickstart.html`, this is what I get:
![image](https://cloud.githubusercontent.com/assets/17286750/22214637/334cc184-e14d-11e6-986f-551c29cf127a.png)

@tytskyi I am not sure, how do I check that? I don't see anything strange in Tools -> "Compatibility View Settings"

**Comment by DzmitryShylovich** [comment] 2017-01-23 17:25
Yeah, same error. Pls re-open on https://github.com/angular/angular.io/issues

**Comment by blubberbo** [comment] 2017-01-23 17:31
@DzmitryShylovich submitted here: [#3128](https://github.com/angular/angular.io/issues/3128)

are you saying it is something local to my Internet Explorer then? I guess I can try to recreate another minimal example to show, but considering the Angular IO site doesn't work for me, I am not any application I make will not work also

**Comment by pkozlowski-opensource** [comment] 2017-01-24 17:08
Duplicate of https://github.com/angular/angular.io/issues/3128

**Closed by pkozlowski-opensource** 2017-01-24 17:08 UTC
