### ISSUE TITLE
Route.pathMatch should be 'prefix' | 'full', not be a string

### ISSUE THREAD

**Issue by damingerdai** [angular/angular#40318] opened 2021-01-06 06:59 UTC
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/....
@angular/router

### Description
 A clear and concise description of the problem or missing capability...
before [Router: Offline-Compilation Friendly](https://github.com/angular/angular/pull/10364), the type of the 'pathMatch' property  is 'prefix' | 'full', but after this pr, it changed to string. I think this is not a good type definition and 'prefix' | 'full' or string enum is better.

### Describe the solution you'd like
 If you have a solution in mind, please describe it.
I recommend using enums or 'prefix' | 'full' to replace existing definitions

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

**Comment by JoostK** [comment] 2021-01-06 08:46
This is a duplicate of #37469 for which PR #37470 exists, but it's a breaking change so needs coordination to get merged. Please follow those for updates, thanks!

**Closed by JoostK** 2021-01-06 08:46 UTC
