### ISSUE TITLE
error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.

### ISSUE THREAD

**Issue by nikita-fuchs** [angular/angular#36558] opened 2020-04-10 11:44 UTC
# 🐞 bug report
Preamble: Please do not mark as duplicate, as none of the workarounds in the other issues on NG6002 work here.

### Affected Package
Building with Ivy enabled (sorry for being unprecise).

### Is this a regression?

Not exactly a regression, just related to Ivy.

### Description

I migrated a project from ~8 to 9.1.1, and it builds perfectly well - when `"enableIvy": false`. With Ivy on, the below issue pops up. `ngcc` is ran `postinstall`. See public repo below to reproduce. 

## 🔬 Reproduction

https://github.com/nikita-fuchs/fire-editor/tree/ivy9-repro

```
npm install
npm init
ng serve
```

## 🔥 Exception or Error
<pre><code>
ERROR in node_modules/ng2-semantic-ui/dist/sui.module.d.ts:1:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.

    This likely means that the library (ng2-semantic-ui) which declares SuiModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.1.1
Node: 12.16.1
OS: darwin x64

Angular: 9.1.1
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.1
@angular-devkit/build-angular     0.901.1
@angular-devkit/build-optimizer   0.901.1
@angular-devkit/build-webpack     0.901.1
@angular-devkit/core              9.1.1
@angular-devkit/schematics        9.1.1
@angular/fire                     5.2.3
@ngtools/webpack                  9.1.1
@schematics/angular               9.1.1
@schematics/update                0.901.1
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0
</code></pre>

**Anything else relevant?**
As mentioned before, disabling Ivy in `tsconfig.app.json` makes things build. The file deemed problematic by the builder looks pretty unproblematic to me :
``` 
export declare class SuiModule {
}
```

I really appreciate any help, thank you very much ! 🏆

**Comment by petebacondarwin** [comment] 2020-04-10 11:53
Thanks for providing a reproduction. I'll look into it!

**Comment by petebacondarwin** [comment] 2020-04-10 12:14
So here is the problem. The `ng2-semantic-ui` package has two formats `UMD` accessed via the `main` and `ES5` accessed via the `module` property of `package.json`.

In your `postinstall` hook you run `ngcc`. When `ngcc` runs it compiles the `typings` files alongside the first of the formats that it processes. It turns out that `ngcc` is processing `main` first and that for this package the UMD format is not being compiled correctly, which results in unprocessed typings.

If you process the `module` property before the `main` property then the typings are created correctly.

This is either a bug in the UMD processing of ngcc or a problem with how `ng2-semantic-ui` generates its UMD files. I need to look into it. We recently noted that `angular-draggable-droppable` fails in similar fashion, so they might be related - cc @gkalpak .

**Comment by gkalpak** [comment] 2020-04-10 12:51
`ng2-semantic-ui`'s `main` seems to point to a minified file, so that is probbaly why ngcc cannot interpret it correctly.

(The problem with `angular-draggable-droppable` was different. See https://github.com/angular/ngcc-validation/pull/1029/commits/c1cf8cc13066b0f4309c88bd2f01cef155c0f029 for details.)

**Comment by nikita-fuchs** [comment] 2020-04-10 13:11
Thanks a ton for getting to it so quickly ! I must admit that I'm struggling to derive specific to-dos for myself from your thorough analyses. The trouble-causing package might be not the most popular maybe, but I can imagine an edge case scenario like this being a major blocker for other people, too:  What can be done about this ? The repo is to be found here: https://github.com/edcarroll/ng2-semantic-ui - maybe a solution can be found which isn't even too specific about this package ?

**Comment by petebacondarwin** [comment] 2020-04-10 14:45
As long as you are not doing server-side-rendering (i.e. `@angular/universal`, etc) then you can tell ngcc to "ignore" the `main` property, since for browser based apps the CLI will use `module` before `main`. You do this by adding a `ngcc.config.js` file in the root of your project containing:

```
module.exports = {
  packages: {
    'ng2-semantic-ui': {
      entryPoints: {
        '.': {
          override: {
            main: undefined
          }
        }
      }
    }
  }
};
```

**Comment by gkalpak** [comment] 2020-04-10 14:46
@nikita-fuchs, off the top of my head, what you can do to "fix" this locally is add an `ngcc.config.js` file in the root of your project to overwrite the `main` property to poitn to the non-minified file:

```js
module.exports = {
  packages: {
    'ng2-semantic-ui': {
      entryPoints: {
        '.': {
          override: {
            main: 'bundles/ng2-semantic-ui.umd.js',
          },
        },
      },
    },
  },
};
```

Given that [the package][1] has not released a new version in two years, so it is unlikely that it will be fixed on their side, it makes sense to incorporate that config in ngcc.

[1]: https://www.npmjs.com/package/ng2-semantic-ui

**Comment by gkalpak** [comment] 2020-04-10 17:44
Actually, looking at this again I don't think you need the UMD format in _any_ package (since you are not using server-side rendering). So, you can fix this (and also speed up your postinstall script by only processing the properties you need with the following ngcc command:

```json
"postinstall": "npm run init && ngcc --create-ivy-entry-points --first-only --properties es2015 browser module main",
```

**Comment by nikita-fuchs** [comment] 2020-04-11 12:19
Here we go!

```
module.exports = {
  packages: {
    'ng2-semantic-ui': {
      entryPoints: {
        '.': {
          override: {
            main: 'bundles/ng2-semantic-ui.umd.js',
          },
        },
      },
    },
  },
};
```
resulted in `ERROR in Cannot resolve type entity ɵngcc1.SuiMessage to symbol` when trying to build, but 

```
module.exports = {
  packages: {
    'ng2-semantic-ui': {
      entryPoints: {
        '.': {
          override: {
            main: undefined
          }
        }
      }
    }
  }
};
```
did the trick! ✅Next I tried ```"postinstall": "npm run init && ngcc --create-ivy-entry-points --first-only --properties es2015 browser module main",``` (in the commands of the `package.json`, for people newer to this topic) instead of the `ngcc.config.js` and didn't get any errors, but for some reason the `debugger` pops open on some code on the module?

![image](https://user-images.githubusercontent.com/11761828/79043383-253f3e00-7bff-11ea-9a9b-e838750d8117.png)

Anyways, wouldn't there be a way to check if modules are about to cause that unwanted behaviour, show a warning and automatically override them?

**Comment by nikita-fuchs** [comment] 2020-04-11 12:50
...and the problem now seems to be that some of the library's code wasn't processed, it's essentially not there where it should be, I guess, and therefore renders the whole application dysfunctional:

Reproduce: 
1. Perform solution from above
2. Run npm install
3. Activate Ivy and `ng serve` the application. 
4. The result is that there are no tabs anymore (sorry for the large picture, it auto scales): 

![image](https://user-images.githubusercontent.com/11761828/79043913-8fa5ad80-7c02-11ea-83c4-1107c85d45e8.png)

5. Disable Ivy
6 (optional) . Add some String to the tab content in src/app/editor/editor.component.html:44
![image](https://user-images.githubusercontent.com/11761828/79043999-ff1b9d00-7c02-11ea-8981-ba3877a0a158.png) to make sure it's not just the fault of the editor library component not rendering
7. `ng serve`with ivy disabled: 
![image](https://user-images.githubusercontent.com/11761828/79044086-77825e00-7c03-11ea-8825-1752abe83d1a.png)

The whole UI is based on that package, Is there something I could do than rebuilding the whole application if I want to use Ivy ? Isn't there a more elegant way?

**Comment by nikita-fuchs** [comment] 2020-04-17 10:32
bump @gkalpak @petebacondarwin , is there any solution to this malforming of the processed module code ?

**Comment by petebacondarwin** [comment] 2020-04-17 14:23
We need to investigate why this package is not being compiled by ngcc correctly...

**Comment by gkalpak** [comment] 2020-04-17 14:33
> Anyways, wouldn't there be a way to check if modules are about to cause that unwanted behaviour, show a warning and automatically exclude them from the compilation?

No, unfortunately there is no easy way to perform this check. And excluding the modules from the compilation wouldn't do users much good, since the app would fail at runtime.

##
I looked at your demo (with the only difference being that I updated the `ngcc` command in the `postinstall` script to `ngcc --create-ivy-entry-points --error-on-failed-entry-point --first-only --properties es2015 browser module main`) and I could reproduce the problem.

It is not related to `ngcc`; it is that `ng2-semantic-ui` doesn't seem to be compatible with Ivy. Not sure if there are other issues, but the tabset issue mentioned above is caused by [this breaking change][1].

To fix this for `SuiTabset`, they would have to use `{descendants: true}` [here][2]:

```diff
 export class SuiTabset implements AfterContentInit {
-@ContentChildren(SuiTabHeader)
+@ContentChildren(SuiTabHeader, {descendants: true})
 private _tabHeaders:QueryList<SuiTabHeader>;
 
-@ContentChildren(SuiTabContent)
+@ContentChildren(SuiTabContent, {descendants: true})
 private _tabContents:QueryList<SuiTabContent>;
```

(Alternatively, you could make your `[suiTabHeader]` and `[suiTabContent]` elements direct children of `<sui-tabset>`, but I imagine that wouldn't really work in your case. Maybe you could propose a PR to `ng2-semantic-ui` :wink:)

[1]: https://next.angular.io/guide/ivy-compatibility-examples#content-children-descendants
[2]: https://github.com/edcarroll/ng2-semantic-ui/blob/61ec6286f67d7064e42d534042b93e1de336e12c/src/modules/tabs/components/tabset.ts#L11-L15

**Comment by nikita-fuchs** [comment] 2020-04-17 14:50
holy cow @gkalpak , that was more help than I could have asked for, thank you so much. The library is not maintained since some time unfortunately, so I guess I'll have to put a fork in place.  I will give it a try as soon as I find out how to use the output of its `npm run lib:compile` cmd as a module in my project, copy pasting the `dist` folder didn't do the trick.

A breaking change warning would be nice, at least at runtime, when affected things are used, like `ContentChildren` - that would make debugging definitely easier.

@petebacondarwin maybe that investigation would bring up useful insights for ngcc ?

**Comment by gkalpak** [comment] 2020-04-17 15:51
> A breaking change warning would be nice, at least at runtime, when affected things are used, like `ContentChildren` - that would make debugging definitely easier.

Well...it's not possible for Angular to know whether not specifying `{descendants: true}` is intentional or not. (It's not wrong to not specify `{descendants: true}`, it just signifies that your component has different requirements.)

BTW, if this was an app, the CLI would have automatically updated `@ContentChildren(...)` to use `{descendants: true}` when upgrading to v9, I guess, but there is not much we can do for dependencies/libraries.

**Comment by nikita-fuchs** [comment] 2020-04-18 07:26
> Well...it's not possible for Angular to know whether not specifying {descendants: true} is intentional or not. (It's not wrong to not specify {descendants: true}, it just signifies that your component has different requirements.)
Sure, I rather meant something like a warning about new changes of usage, sorry for being unprecise. Still struggling with how to use the library's build output as a module - hold tight, will be back after I figured this out.

**Comment by petebacondarwin** [comment] 2020-05-24 20:28
We try to provide warnings about deprecated and changed APIs as best as possible. I don't think it is possible in this case. Closing as this is working as expected.

**Closed by petebacondarwin** 2020-05-24 20:28 UTC
Labels: comp: ngcc, type: bug/fix
