### ISSUE TITLE
Host bindings to the `class` property crash the compiler if the binding expression is empty

### ISSUE THREAD

**Issue by sahilbabbar** [angular/angular#41048] opened 2021-03-02 12:52 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/compiler.

### Is this a regression?
NA

 

### Description
An old Angular enterprise application that was based on `v6.0.3`, is migrated successfully to `v11.0.6` and then Ivy is enabled using `"enableIvy": true` in `tsconfig.lib.json`.

But, on `ng build --prod` getting the below mentioned error.

I tried going the file and line specified in the error i.e. `compiler.umd.js:9036:52` and found the following lines of code:

<details>

```js
/**
     * Converts the given expression AST into an executable output AST, assuming the expression
     * is used in property binding. The expression has to be preprocessed via
     * `convertPropertyBindingBuiltins`.
     */
    function convertPropertyBinding(localResolver, implicitReceiver, expressionWithoutBuiltins, bindingId, form, interpolationFunction) {
        if (!localResolver) {
            localResolver = new DefaultLocalResolver();
        }
        var visitor = new _AstToIrVisitor(localResolver, implicitReceiver, bindingId, interpolationFunction);
        console.log(expressionWithoutBuiltins, '\n\n', localResolver, '\n\n', implicitReceiver, '\n\n', bindingId, '\n\n', form, '\n\n', interpolationFunction.toString(), '\n\n', visitor);
        console.log('********************************************');
        var outputExpr = expressionWithoutBuiltins.visit(visitor, _Mode.Expression);
        console.log('********' + JSON.stringify(outputExpr) + '************************************');
        var stmts = getStatementsFromVisitor(visitor, bindingId);
        ...
        ...
        ...
```

The above `console.log`s, give the following output:
```
Compiling @my-scope/project : es2015 as esm2015
LiteralPrimitive {
  span: ParseSpan { start: 0, end: 4 },
  sourceSpan: AbsoluteSourceSpan { start: 28071, end: 28075 },
  value: true
}

 DefaultLocalResolver { globals: undefined }

 ReadVarExpr {
  type: null,
  sourceSpan: null,
  name: 'ctx',
  builtin: null
}

 b

 2

 function () { return error('Unexpected interpolation'); }

 _AstToIrVisitor {
  _localResolver: DefaultLocalResolver { globals: undefined },
  _implicitReceiver: ReadVarExpr {
    type: null,
    sourceSpan: null,
    name: 'ctx',
    builtin: null
  },
  bindingId: 'b',
  interpolationFunction: [Function (anonymous)],
  baseSourceSpan: undefined,
  implicitReceiverAccesses: undefined,
  _nodeMap: Map(0) {},
  _resultMap: Map(0) {},
  _currentTemporary: 0,
  temporaryCount: 0,
  usesImplicitReceiver: false
}
********************************************
********{"type":{"modifiers":[],"name":6},"sourceSpan":null,"value":true}************************************
undefined

 DefaultLocalResolver { globals: undefined }

 ReadVarExpr {
  type: null,
  sourceSpan: null,
  name: 'ctx',
  builtin: null
}

 b

 2

 function () { return error('Unexpected interpolation'); }

 _AstToIrVisitor {
  _localResolver: DefaultLocalResolver { globals: undefined },
  _implicitReceiver: ReadVarExpr {
    type: null,
    sourceSpan: null,
    name: 'ctx',
    builtin: null
  },
  bindingId: 'b',
  interpolationFunction: [Function (anonymous)],
  baseSourceSpan: undefined,
  implicitReceiverAccesses: undefined,
  _nodeMap: Map(0) {},
  _resultMap: Map(0) {},
  _currentTemporary: 0,
  temporaryCount: 0,
  usesImplicitReceiver: false
}
********************************************
```

</details>

The component that causes the crash uses a host binding to the `class` property where the binding expression is left empty:

```ts
const MY_BUTTON_CLASS_NAME = 'my-btn';

@Directive({
    selector: 'button[myButton], a[myButton]',
    host: {
        'class': MY_BUTTON_CLASS_NAME,
        '[class]': ''
    },
    exportAs: 'mmButton'
})
export class MyButtonDirective implements OnChanges { ... }
```

## 🔬 Minimal Reproduction
Hard to reproduce as this error is appearing in an old enterprise Angular library project that is recently migrated from `v6.0.3` to `v11.0.6`.

## 🔥 Exception or Error
<pre><code>
Error: Error on worker #1: TypeError: Cannot read property 'visit' of undefined
    at convertPropertyBinding (<project>node_modules\@angular\compiler\bundles\compiler.umd.js:9036:52)
    at bindingFn (<project>node_modules\@angular\compiler\bundles\compiler.umd.js:20733:16)
    at <project>node_modules\@angular\compiler\bundles\compiler.umd.js:20643:31
    at Array.forEach (<anonymous>)
    at createHostBindingsFunction (<project>node_modules\@angular\compiler\bundles\compiler.umd.js:20640:26)
    at baseDirectiveFields (<project>node_modules\@angular\compiler\bundles\compiler.umd.js:20208:43)
    at Object.compileDirectiveFromMetadata (<project>node_modules\@angular\compiler\bundles\compiler.umd.js:20250:29)
    at DirectiveDecoratorHandler.compileFull (<project>node_modules\@angular\compiler-cli\src\ngtsc\annotations\src\directive.js:126:34)
    at _loop_2 (<project>node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:552:39)
    at NgccTraitCompiler.TraitCompiler.compile (<project>node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:584:21)
    at ClusterMaster.onWorkerMessage (<project>node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:195:27)
    at <project>node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:55:95
    at ClusterMaster.<anonymous> (<project>node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:293:57)
    at step (<project>node_modules\@angular\compiler-cli\node_modules\tslib\tslib.js:143:27)
    at Object.next (<project>node_modules\@angular\compiler-cli\node_modules\tslib\tslib.js:124:57)
    at <project>node_modules\@angular\compiler-cli\node_modules\tslib\tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (<project>node_modules\@angular\compiler-cli\node_modules\tslib\tslib.js:113:16)
    at EventEmitter.<anonymous> (<project>node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:287:32)
    at EventEmitter.emit (events.js:315:20)
An unhandled exception occurred: NGCC failed.
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 11.0.6
Node: 14.15.4
OS: win32 x64

Angular: 11.0.6
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.6
@angular-devkit/build-angular   0.1100.6
@angular-devkit/core            11.0.6
@angular-devkit/schematics      11.0.6
@schematics/angular             11.0.6
@schematics/update              0.1100.6
ng-packagr                      11.0.0
rxjs                            6.6.3
typescript                      4.0.5

</code></pre>

**Anything else relevant?**

**tsconfig.lib.prod.json**
```
{
    "extends": "./tsconfig.lib.json",
    "compilerOptions": {
        "declarationMap": false
    },
    "angularCompilerOptions": {
        "enableIvy": true
    }
}
```

**tsconfig.lib.json**
```
{
    "extends": "../../tsconfig.json",
    "compilerOptions": {
        "outDir": "../../out-tsc/lib",
        "declarationMap": true,
        "target": "es2015",
        "declaration": true,
        "inlineSources": true,
        "types": [],
        "lib": [
            "dom",
            "es2015"
        ],
        "paths": {
            "@assets*": ["src/lib/assets/*"]
        }
    },
    "angularCompilerOptions": {
        "skipTemplateCodegen": true,
        "strictMetadataEmit": true,
        "enableResourceInlining": true
    },
    "exclude": [
        "src/test.ts",
        "**/*.spec.ts"
    ]
}
```

**Comment by petebacondarwin** [comment] 2021-03-02 13:38
@sahilbabbar - it is very difficult to diagnose what the problem is without seeing the code and being able to run it. I assume that ` @ericsson/multimediation` is some internal library? How is that being built?

**Comment by sahilbabbar** [comment] 2021-03-02 14:08
@petebacondarwin that's an internal package name(can you kindly edit your comment with `@my-scope/project`). I am afraid I can't reproduce this issue as this is a huge internal enterprise Angular library and on doing `ng build my-lib - - prod` this error pops up. Now there is no way, I can even guess what is causing the error and pin-point a component or module or even present a reproduction.

**Comment by petebacondarwin** [comment] 2021-03-02 14:17
I'm sorry, there is very little we can do without a reproduction. It looks to me the problem is with the `@my-scope/project` package, which I assume you are compiling with ViewEngine and then is being processed by ngcc, where the error is occurring.

The logging indicates that the code is formatted as ES2015. It is uncommon for ngcc to be unable to process ES2015 code. Is there anything particularly unusual about the code in this package?

**Comment by JoostK** [comment] 2021-03-02 18:39
This looks like `EmptyExpr` is causing problems from what looks to be a host binding (extracted from the stack trace).

@sahilbabbar Could you change `DirectiveDecoratorHandler.compileFull` to put a try-catch around `compileDirectiveFromMetadata` and then to `console.log(node.getSourceFile().fileName);` in the `catch`-clause. That should give you the source file for which compilation fails. I suspect it has host bindings, either using the `@Component.host`  property or using the `@HostBinding` decorator on a class field. One of those is causing the crash.

**Comment by sahilbabbar** [comment] 2021-03-03 09:32
Saw the release notes of `v11.1.0` which mentions lots of compiler fixes and after updating the library to `v11.2.2` the build works with Ivy enabled. 

**But** the problem doesn't end here: Now, I am importing this library into an Angular application which has Ivy enabled with the same versions of everything as the library(see output of `ng version` above) and on doing `ng build --prod` on the app getting the following error:

```
- Generating browser application bundles...
√ Browser application bundle generation complete.

Error: ./node_modules/@my-scope/project/fesm2015/project.js
Module build failed (from ./node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js):
TypeError: Cannot create property 'message' on string '<project>\node_modules\@my-scope\project\fesm2015\project.js: Cannot read property 'visit' of undefined
  954 |     }
  955 |     MyButtonDirective.ɵfac = function MyButtonDirective_Factory(t) { return new (t || MyButtonDirective)(ɵɵdirectiveInject(ElementRef), ɵɵdirectiveInject(Renderer2)); };
> 956 |     MyButtonDirective.ɵdir = ɵɵngDeclareDirective({ version: "11.2.2", type: MyButtonDirective, selector: "button[myButton], a[myButton]", inputs: { buttonType: ["myButton", "buttonType"], buttonSize: ["size", "buttonSize"], color: "color" }, host: { properties: { "class": "" }, classAttribute: "my-btn" }, exportAs: ["myButton"], usesOnChanges: true, ngImport: i0 });
      |                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  957 |     return MyButtonDirective;
  958 | })();
  959 | (function () {'
    at run (<project>\node_modules\@babel\core\lib\transformation\index.js:39:15)
    at run.next (<anonymous>)
    at Function.transform (<project>\node_modules\@babel\core\lib\transform.js:27:41)
    at transform.next (<anonymous>)
    at step (<project>\node_modules\gensync\index.js:261:32)
    at <project>\node_modules\gensync\index.js:273:13
    at async.call.result.err.err (<project>\node_modules\gensync\index.js:223:11)
 @ ./src/app/core/core.module.ts 6:0-60 26:16-32
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi ./src/main.ts
```

@petebacondarwin there is nothing unusual about this package as such and it comprises of a basic set of components for building internal enterprise Angular apps.

@JoostK perhaps you are right that something related to `host` is breaking the build and now after upgrade to `v11.2.2` the error specifies the line of code which is causing the error(`Cannot read property 'visit' of undefined`) to pop-up. Now what do you think is causing the issue?

This is how the component looks in the library:
```
const MY_BUTTON_CLASS_NAME = 'my-btn';

@Directive({
    selector: 'button[myButton], a[myButton]',
    host: {
        'class': MY_BUTTON_CLASS_NAME,
        '[class]': ''
    },
    exportAs: 'mmButton'
})
export class MyButtonDirective implements OnChanges { ... }
```

**Comment by JoostK** [comment] 2021-03-03 09:56
Yeah it chokes on the `'[class]': ''` host binding, the empty string represents an empty expression and this isn't handled correctly in Ivy. I suppose you can workaround using `'[class]': 'null'`

**Comment by sahilbabbar** [comment] 2021-03-04 04:10
@JoostK yeah, that's the issue right there. Whether Ivy should handle this scenario or not, it's upto you guys to decide, but after removing this, the library builds correctly as well as the application(which imports the library). 

Currently, the library's `tsconfig.lib.prod.json` looks like:
```
{
    "extends": "./tsconfig.lib.json",
    "compilerOptions": {
        "declarationMap": false
    },
    "angularCompilerOptions": {
        "enableIvy": true,
        "compilationMode": "partial"
    }
}
```

Just to double check, using `compilationMode: "partial"` along with `enableIvy: true` is the right approach where I want to publish an *internal* Ivy library assuming that **only** Ivy enabled *internal* apps will make use of it.

**Comment by petebacondarwin** [comment] 2021-03-04 09:03
> Just to double check, using compilationMode: "partial" along with enableIvy: true is the right approach where I want to publish an internal Ivy library assuming that only Ivy enabled internal apps will make use of it.

@sahilbabbar - I'm glad you got this working.

Regarding the best approach for internal libraries…

I would say that if you are always going to keep the libraries and the applications at the exact same versions of Angular (so the version used for building the library is identical, including patch version, to the version used for building the applications) then there is no need to use the "partial" mode. You can just build with full Ivy AOT. This will be faster since there will be no need for the linking step when building the applications.

If you expect the version of Angular used to compile applications to vary compared to the version used to build the libraries then (after we officially switch to the "linker" as the supported publishing format) you should use partial compilation for your libraries. Up till we officially switch, you are safest sticking with ViewEngine builds for you library (relying upon ngcc to post-process the library in you application projects) - this is because we are currently working on the exact final format for partially built libraries, so you cannot rely on it being stable until we officially switch.

**Comment by sahilbabbar** [comment] 2021-03-05 07:33
@petebacondarwin thanks for clarifying the configuration, which is pretty confusing with Ivy in scene. Is this thing documented somewhere on Angular Docs as not much help is available to this detail on the web.

Moreover, feel free to close this issue if it's not required for your tracking.

**Comment by petebacondarwin** [comment] 2021-03-05 10:06
Since the linker is still pre-production, there is no documentation on it. The documentation we have got is focussed on people publishing libraries publicly (e.g. via npm). We should do an update to the docs for when linker become mainstream.

**Comment by petebacondarwin** [comment] 2021-03-05 10:06
Closing as proposed, since there is no direct action needed here.

**Closed by petebacondarwin** 2021-03-05 10:06 UTC
Labels: P3, comp: compiler

**Comment by sahilbabbar** [comment] 2021-03-05 14:08
For production usage & publishing Ivy libraries to internal artifactory, what is your recommendation on the basis of upcoming changes in Angular library package format and current stability of Ivy built libraries.

**Assumption:** Ivy library will be consumed by Ivy enabled internal apps with *exact* same Angular version `11.2.2`  with their respective dependencies:

A. Library project is configured with `'enableIvy': false` and consumer application with `'enableIvy': true`; using `postinstall: ngcc`.

B. Both library and app configured with `'enableIvy': true` and publishing after removing `prepublishonly` script from built library's `package.json`(as you commented here https://github.com/angular/angular/issues/37973#issuecomment-656179491)

**Comment by petebacondarwin** [comment] 2021-03-05 14:16
If the library and the application are both internal, and you ensure that both are always built with the exact same version of Angular then B.
