### ISSUE TITLE
Some elements doesn't appear on the official website

### ISSUE THREAD

**Issue by YuGiOhJCJ** [angular/angular#57623] opened 2024-09-02 06:27 UTC
### Describe the problem that you experienced

The "node.js" word doesn't appear on a web page of the official website.
URL:  https://angular.dev/tutorials/first-app#install-the-correct-version-of-nodejs-for-angular
Screenshot: https://i.imgur.com/IhFl6IJ.png

Similar problem with these two buttons on the home page at my first visit.
URL: https://angular.dev/
Screenshot: https://i.imgur.com/J30mC8V.png

### Enter the URL of the topic with the problem

https://angular.dev/tutorials/first-app#install-the-correct-version-of-nodejs-for-angular

### Describe what you were looking for in the documentation

I was looking for a tutorial for beginner.

### Describe the actions that led you to experience the problem

Go to: https://angular.dev/tutorials/first-app#install-the-correct-version-of-nodejs-for-angular

### Describe what you want to experience that would fix the problem

I would like that the word "node.js" appears.

### Add a screenshot if that helps illustrate the problem

![image](https://github.com/user-attachments/assets/f4e8eb40-161a-4d54-bac9-5a4549ce4678)

### If the problem is browser-specific, please specify the device, OS, browser, and version

```true
OS: Windows 10 Pro
Browser: Firefox 111.0.1 (64-bit)
```

### Provide any additional information here in as much as detail as you can

```true
The problem happens even in a new private window.
```

**Comment by geromegrignon** [comment] 2024-09-02 06:34
The Angular documentation is an Angular application following official [browser support policy](https://angular.dev/reference/versions#browser-support
). As I can't reproduce it on Firefox v129, the required fix will be on your side by updating Firefox to the last v129 version.

**Comment by JoostK** [comment] 2024-09-02 07:14
This is similar to/ a duplicate of #57448. Indeed, this version of Firefox is outdated at this point and you should update your browser.

**Closed by JoostK** 2024-09-02 07:14 UTC

**Comment by YuGiOhJCJ** [comment] 2024-09-19 11:47
I upgraded from Firefox 111.0.1 (64-bit) to Firefox 130.0 (64-bit) and it fixed the problem.
