### ISSUE TITLE
docs(http): Example uses map() function on Observable without importing RxJs operator

### ISSUE THREAD

**Issue by martinsik** [angular/angular#6240] opened 2016-01-04 11:19 UTC
Example [of Http class on angular.io API](https://angular.io/docs/ts/latest/api/http/Http-class.html) calls Observable.map() which doesn't work because RxJs operators aren't included by default and you have to import them manually.
The same thing is described also here [http.get(..).map function is not working with alpha 48](https://github.com/angular/angular/issues/5632).

**Comment by robwormald** [comment] 2016-01-04 11:22
closing as a duplicate of https://github.com/angular/angular/issues/5632 https://github.com/angular/angular/issues/5944 https://github.com/angular/angular/issues/6230

already resolved in https://github.com/angular/angular/pull/5947

**Closed by robwormald** 2016-01-04 11:22 UTC
