### ISSUE TITLE
Footer Overflow

### ISSUE THREAD

**Issue by DimitriTsikaridze** [angular/angular#44242] opened 2021-11-21 07:11 UTC
### Description

footer content overflows on Iphone SE 2nd gen, causing horizontal scrollbar.

### Please provide a screenshot if possible

![image](https://user-images.githubusercontent.com/56136563/142753128-3624b21d-ec3d-4d28-aba1-5236aaaf2c95.png)

### Is this a browser-specific issue? If so, please specify the device, browser, and version.

```true
this issue was on Iphone SE 2nd Gen, safari browser.
```

**Comment by gkalpak** [comment] 2021-11-22 09:42
Thx for reporting this, @DimitriTsikaridze.
I couldn't reproduce it, but I believe it might have been fixed by #44126.

Can you try again and see if it still happens with the current version of the site?

(cc @dario-piotrowicz)

**Comment by DimitriTsikaridze** [comment] 2021-11-22 18:54
@gkalpak It's still the same. I couldn't reproduce it either when I tried inside chrome on PC, but on my phone there still is overflow. maybe it's safari.

**Comment by dario-piotrowicz** [comment] 2021-11-22 20:51
yes I've just checked, it is a safari thing, it handles `media-queries` on `rem`s differently from chrome

@gkalpak you know that media query I added:
https://github.com/angular/angular/blob/d8ae34aea8850002ca9c300ea6cf99d14535a4ec/aio/src/styles/1-layouts/footer/_footer.scss#L85

Seems like safari triggers that on windows of smaller widths :man_shrugging: 
(I hadn't had a chance to play with different font-sizes, just the medium one)

one quick easy solution would be to increase the `32rem` to something bigger, or we could try to make things quite more robust and actually see to implement the footer in a more flexible way (like with `flex-wrap`)

what do you think @gkalpak?

**Comment by gkalpak** [comment] 2021-11-24 14:10
Thx for looking into this, @dario-piotrowicz :+1:

> Seems like safari triggers that on windows of smaller widths 🤷‍♂️
> [...]
> one quick easy solution would be to increase the 32rem to something bigger

Are you saying that on Safari `max-width: 32rem` does not match when the width is actually `32rem`, but only when the width is smaller than `32rem`?
If we increased `32rem` (to cater for Safari), wouldn't this make the footer look worse on other browsers? 
(Just making sure I have understood what you said correctly :smiley:)

**Comment by gkalpak** [comment] 2021-11-24 14:14
Also, I wonder if [this][1] would work in our case.

[1]: https://stackoverflow.com/questions/13237782/safari-doesnt-calculate-rem-units-correct-when-scaling-with-media-width-heigh#answer-13266518

**Comment by dario-piotrowicz** [comment] 2021-11-24 14:24
> Thx for looking into this, @dario-piotrowicz +1
> 
> > Seems like safari triggers that on windows of smaller widths man_shrugging
> > [...]
> > one quick easy solution would be to increase the 32rem to something bigger
> 
> Are you saying that on Safari `max-width: 32rem` does not match when the width is actually `32rem`, but only when the width is smaller than `32rem`? If we increased `32rem` (to cater for Safari), wouldn't this make the footer look worse on other browsers? (Just making sure I have understood what you said correctly smiley)

Yes exactly, and it would indeed make the footer look worse on other browsers (but only on certain widths of course) that's why I suggested to maybe look into a better solution

**Comment by dario-piotrowicz** [comment] 2021-11-24 14:28
> Also, I wonder if [this](https://stackoverflow.com/questions/13237782/safari-doesnt-calculate-rem-units-correct-when-scaling-with-media-width-heigh#answer-13266518) would work in our case.

Yes could could try that, also I've found a hack to see if the user is using safari: https://codepen.io/karlsson/pen/zYNYwNO

So yeah we could indeed look into something like that :slightly_smiling_face: 

(maybe we could, do a quick hack to get the thing working nicely for the time being and then looking into updating the footer's layout to make it better in general and more responsive/robust?)

**Comment by gkalpak** [comment] 2021-11-24 15:06
Ha, ha, I like your pen :smiley:

I think that sounds good. I wouldn't like to make all other browsers worse to make one browser better :grin:
So, if there is a quick way to improve things for Safari (without making it worse for other browsers), I'm all for it.
(And I am also open to longer-term change to improve the layout, but tbh I don't think it is a high priority atm :smiley:)

**Comment by dario-piotrowicz** [comment] 2021-11-24 18:44
> Ha, ha, I like your pen smiley
> 
> I think that sounds good. I wouldn't like to make all other browsers worse to make one browser better grin So, if there is a quick way to improve things for Safari (without making it worse for other browsers), I'm all for it. (And I am also open to longer-term change to improve the layout, but tbh I don't think it is a high priority atm smiley)

Ah thanks, but the way that pen is not made by me, I just found it online :stuck_out_tongue_winking_eye: 

Ok so if you want I will give it a go to fix it for now and then doing a nicer solution later on :slightly_smiling_face::+1:

**Closed** 2021-11-29 17:37 UTC
Labels: comp: docs-infra, needs clarification
