### ISSUE TITLE
BrowserAnimationsModule breaks size calculations

### ISSUE THREAD

**Issue by FSDRE** [angular/angular#36054] opened 2020-03-13 12:14 UTC
# 🐞 bug report

### Affected Package
@angular/platform-browser/animations

### Is this a regression?

 The latest version working was 5.2.3

### Description

 When Angular router is used to navigate and a new component is loaded into router-outlet, the size retrieved from the new compoent in OnInit or AfterViewInit is wrong whenever BrowserAnimationsModule is used.

In the StackBlitz example the FrameComponent gets loaded into router-outlet. In OnInit and AfterViewInit the size of the div #frame gets read by

`this.frame.nativeElement.client[Width/Height]`

When BrowserAnimationsModule is part of AppModule, the height of the div is completely wrong (should be the same as viewport height). If BrowserAnimationsModule does not get imported, the size of the div gets reported correctly.

This breaks any application that depends on size calculations.

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-rac6sy

* Load StackBlitz and open up the console (the sizes get logged there)
* Click on the link "Click Here"
* Check the logged size in the console (especially the height)
* Go to app.module and delete BrowserAnimationsModule from imports
* Reload and repeat the above process -> the size is now correct (viewport size)

## 🌍  Your Environment

**Angular Version:**
<pre><code>NG 9.0.6
Chrome 80.0.3987.132
Firefox 74
Windows 10 1909
</code></pre>

**Anything else relevant?**

May be related to #20290 but I am not sure if it is the exact same problem

**Comment by FSDRE** [comment] 2020-03-16 14:16
@AndrewKushnir I'd like to add that the wrong calculations also happen when NoopAnimationsModule is imported instead of BrowserAnimationsModule

**Comment by lhude** [comment] 2020-03-17 18:34
I have been struggling with the exact same problem for 2 days.
I've created a stackblitz example just before I've discovered this open issue.
I add it here anyway, it can be useful.

https://stackblitz.com/edit/angular-mvcrk6?file=src%2Fapp%2Fapp.module.ts

What I've noted (see the comments in app.module.ts) is that when ngOnInit is executed after a routerlink is clicked, 2 components are in the router-outlet at the same time, which is why the DOM elements don't have the expected sizes. But only for a very short time and it's barely noticeable if your code does not rely on this sizes.

**Comment by flemgs** [comment] 2020-05-27 11:41
Hi, 

I have the same issue here while using `getBoundingClientRect` in `ngAfterViewInit` after navigating with router object if `BrowserAnimationsModule` is imported. It seems like the computed (x, y) coordinates between the previous element in the `router-outlet` and the next one are "added up", just like if they were present at the same time on the page.

The only workaround I found for now is to encapsulate `getBoundingClientRect` in a `setTimeout` with 0 delay to get the good result, but I wish I didn't have to do it.

The issue occured while migrating from Angular 8.2.14 to Angular 9.1.7. (Respectively from 8.2.3 to 9.2.3 for Material)

**Comment by matsko** [comment] 2020-05-28 00:49
Hello @FSDRE. Thank you for posting this. I can definitely see the issue here and we still need to investigate further to see what's causing this. It looks like there's a race condition when the page is first inserted into the page. Perhaps the ordering is different when browserAnimationsModule is present.

Do you know if the behavior is the same as it is in Ivy? I will continue to look into this.

**Comment by lhude** [comment] 2020-05-28 08:16
Hello @matsko 
Have you seen my stackblitz example ?
https://stackblitz.com/edit/angular-mvcrk6?file=src%2Fapp%2Fapp.module.ts

There are comments to reproduce the problem :

    /**
     * Click on Component B, then Component A, then Component B, et.
     * The name changes but not the width displayed.
     * Now uncomment BrowserAnimationsModule and reload the application.
     * The first value displayed will be the real value, but when you click on "Component B" (and for any 
     * subsequent click on Component A or Component B), the value displayed will be half of the initial value.
     * This happens because when the ngOninit() of Component B is executed, both Component A and Component B are 
     * displayed in the router-outlet.
     * You can see both component side by side if you set a breakpoint in ngOnInit() of one of the components.
     * If BrowserAnimationsModule is commented, however, Component A is removed from the router-outlet BEFORE 
     * Component B is included, there are never 2 components in the router-outlet at the same time and the 
     * width displayed is good.
     */

**Comment by FSDRE** [comment] 2020-06-26 11:52
@matsko Sorry for the late answer, I have become a dad in the meantime 😄 

The example was a new project with NG 9.0.6, that defaults to Ivy, right? Have not checked it but should be...

**Comment by anuoua** [comment] 2020-10-26 14:56
Same problem here, when i import BrowserAnimationsModule, the size of page is not correct in ngafterviewInit hook. 
any idears?

**Comment by stephanietuerk** [comment] 2020-10-26 19:29
Also having this problem. When I use breakpoints to observe the Angular lifecycle, I can see -- both in the DOM inspector and on the screen -- that when I initiate navigation to a new router link with the AnimationsModule in the project, there is a time when two components, `<app-old-page>` and `<app-new-page>`, are both present in the same router outlet. As a result, the element dimensions in `<app-new-page>` are not what they should be when the component's view is initializes. 

I am temporarily solving this with a timeout in `ngOnInit` of the new component (`setTimeout(() => { this.resizeMyElement(); }, 0)`), but there is still a split second adjustment that is visible on the screen.

**Comment by jelbourn** [comment] 2020-10-26 20:46
Closing this issue since it is working as expected. Lifecycle hooks like `ngOnInit` tell you when your component has all of its _bindings_ applied, but it's not actually related to the _rendering_ of the component. Today, Angular doesn't have an official API for knowing when rendering has completed. You can accomplish this by proxy via checking the `NgZone`, though:
```ts
this.ngZone.runOutsideAngular(() => {
  this.ngZone.onState.pipe(take(1)).subscribe(() => {
    // interact with the DOM here
  });
});
```
(any async API like `setTimeout` / `Promise.resolve().then()` etc will accomplish the same thing, though you should be mindful that those APIs will cause an extra change detection)

**Closed by jelbourn** 2020-10-26 20:46 UTC
Labels: comp: animations, state: needs more investigation, triage #1

**Comment by stephanietuerk** [comment] 2020-10-26 21:04
@jelbourn Is there any way to understand how the adding BrowserAnimationModule to a project changes the rendering process/order?

**Comment by FSDRE** [comment] 2020-10-26 23:44
@jelbourn If I understand it correctly there is not really a solution for a simple task like "scrolling something into view after the page was rendered" without using zone-hacks or double change detection? Why is something basic like this not on a roadmap? And by "basic" I mean the feature, not the implementation, knowing it could be a lot of work. 

"Working as expected" is weird. We have a pretty solid inconsistency here. Depending on what modules you include in the project, rendering changes completely and API's suddenly return different values. I don't know, it just doesn't feel right. A framework should keep struggle away from the developers, not introduce confusion.
