### ISSUE TITLE
Sometimes land on chrome error page for one second when service worker is enabled

### ISSUE THREAD

**Issue by DCollart** [angular/angular#47715] opened 2022-10-10 07:52 UTC
### Which @angular/* package(s) are the source of the bug?

service-worker

### Is this a regression?

Yes

### Description

This bug was already reported in #43106 but I hope new information will be useful.

First of all: Angular service worker need to be installed and the option "bypass for network" should not be enabled. 

Once done if we go to the app (or reload the page) sometimes we got a chrome error page _Webpage is not reachable_ for one second and after that we got the app.

In the console we see 2 calls : 
- First call to get the page failed: (failed) net:ERR_FAILED.
- Second one succeed from service worker. (There is potentially a call initiated by the service worker but it's not relevant here).

In the service worker console we see 2 things: 
- Warning: The FetchEvent for "https://angular.io/guide/service-worker-devops" resulted in a network error response: the promise was rejected.
- Error: Uncaught (in promise) DOMException: Unexpected internal error.

I tried to debug a bit and the issue seems coming from the _sync_ method on those lines: 
`await Promise.all([
          table.write("manifests", manifests),
          table.write("assignments", assignments),
          table.write("latest", latest)
        ]);`

If I surround it with a try/catch and a log I still see the error occuring sometimes but it's perflecty smooth for the user (no chrome error page).

### Please provide a link to a minimal reproduction of the bug

https://angular.io/guide/service-worker-devops is having the issue. I can try to setup a small project if needed.

### Please provide the exception or error you saw

```true
In the console :
As a warning:
The FetchEvent for "https://angular.io/guide/service-worker-devops" resulted in a network error response: the promise was rejected.

As an error:
Uncaught (in promise) DOMException: Unexpected internal error.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.2.4
Node: 16.16.0
Package Manager: npm 8.11.0
OS: win32 x64

Angular: 13.2.3
... animations, cdk, common, compiler, compiler-cli, core, forms
... material, platform-browser, platform-browser-dynamic, router
... service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1302.4
@angular-devkit/build-angular   13.2.4
@angular-devkit/core            13.2.4
@angular-devkit/schematics      13.2.4
@angular/cli                    13.2.4
@angular/pwa                    13.2.4
@angular/youtube-player         13.3.8
@schematics/angular             13.2.4
rxjs                            7.5.4
typescript                      4.5.5
```

Chrome version is : 105.0.5195.102

### Anything else?

When I search about this error it could be an error directly related with Chrome itself:
- https://github.com/GoogleChrome/workbox/issues/792 (I checked my quota and I'm far from it)
- https://stackoverflow.com/questions/62512449/uncaught-in-promise-domexception-unexpected-internal-error-from-cache-add

I don't know how the "sync" function is important but it seems to work even with an error (with a try/catch) so maybe there is some  possible work around? Maybe some retries (since it works a few second later) ?

**Comment by JeanMeche** [comment] 2024-04-07 08:32
I remember seing this issue lot back then but I haven't experienced it in a while. As mentionned in  #43106 this was not reproducible in Firefox hinting at a possible Chrome issue which might have been fixed since then. 
I'll close this as we didn't get any additional report of the issue.

**Closed by JeanMeche** 2024-04-07 08:32 UTC
Labels: area: service-worker, P3

**Comment by PhuocHoangMinhNguyen** [comment] 2024-04-16 04:26
Unfortunately, our team starts having the same issue again for the last couple of weeks. I will create a new issue for people experiencing the same issue.
