### ISSUE TITLE
 Cannot read property 'flags' of undefined

### ISSUE THREAD

**Issue by billpeace** [angular/angular#36995] opened 2020-05-08 03:31 UTC
# 🐞 bug report

### Affected Package
Unknown，Just 
   ng new project4
   npm start

### Is this a regression?

no

### Description

ERROR in TypeError: Cannot read property 'flags' of undefined
    at resolveAlias (E:\Project\aspnet-zero-core-5.5.0\project4\node_modules\typescript\lib\typescript.js:36513:37)
    at checkAliasSymbol (E:\Project\aspnet-zero-core-5.5.0\project4\node_modules\typescript\lib\typescript.js:64502:26)
    at checkImportBinding (E:\Project\aspnet-zero-core-5.5.0\project4\node_modules\typescript\lib\typescript.js:64534:13)

## 🔥 Exception or Error
<pre><code>

ERROR in TypeError: Cannot read property 'flags' of undefined
    at resolveAlias (E:\Project\aspnet-zero-core-5.5.0\project4\node_modules\typescript\lib\typescript.js:36513:37)
    at checkAliasSymbol (E:\Project\aspnet-zero-core-5.5.0\project4\node_modules\typescript\lib\typescript.js:64502:26)
    at checkImportBinding (E:\Project\aspnet-zero-core-5.5.0\project4\node_modules\typescript\lib\typescript.js:64534:13)
    at checkImportDeclaration (E:\Project\aspnet-zero-core-5.5.0\project4\node_modules\typescript\lib\typescript.js:64552:29)
    at checkSourceElementWorker (E:\Project\aspnet-zero-core-5.5.0\project4\node_modules\typescript\lib\typescript.js:64961:28)
    at checkSourceElement (E:\Project\aspnet-zero-core-5.5.0\project4\node_modules\typescript\lib\typescript.js:64800:17)
    at Object.forEach (E:\Project\aspnet-zero-core-5.5.0\project4\node_modules\typescript\lib\typescript.js:317:30)
    at checkSourceFileWorker (E:\Project\aspnet-zero-core-5.5.0\project4\node_modules\typescript\lib\typescript.js:65123:20)
    at checkSourceFile (E:\Project\aspnet-zero-core-5.5.0\project4\node_modules\typescript\lib\typescript.js:65091:13)
    at getDiagnosticsWorker (E:\Project\aspnet-zero-core-5.5.0\project4\node_modules\typescript\lib\typescript.js:65179:17)
    at Object.getDiagnostics (E:\Project\aspnet-zero-core-5.5.0\project4\node_modules\typescript\lib\typescript.js:65165:24)
    at E:\Project\aspnet-zero-core-5.5.0\project4\node_modules\typescript\lib\typescript.js:98703:85
    at runWithCancellationToken (E:\Project\aspnet-zero-core-5.5.0\project4\node_modules\typescript\lib\typescript.js:98665:24)
    at getBindAndCheckDiagnosticsForFileNoCache (E:\Project\aspnet-zero-core-5.5.0\project4\node_modules\typescript\lib\typescript.js:98691:20)
    at getAndCacheDiagnostics (E:\Project\aspnet-zero-core-5.5.0\project4\node_modules\typescript\lib\typescript.js:98956:26)
    at getBindAndCheckDiagnosticsForFile (E:\Project\aspnet-zero-core-5.5.0\project4\node_modules\typescript\lib\typescript.js:98688:20)
</code>
</pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 9.1.4
Node: 14.2.0
OS: win32 x64

Angular: 9.1.5
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.4
@angular-devkit/build-angular     0.901.4
@angular-devkit/build-optimizer   0.901.4
@angular-devkit/build-webpack     0.901.4
@angular-devkit/core              9.1.4
@angular-devkit/schematics        9.1.4
@angular/cli                      9.1.4
@ngtools/webpack                  9.1.4
@schematics/angular               9.1.4
@schematics/update                0.901.4
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0
</code></pre>

**Anything else relevant?**

**Comment by guillermohernandez** [comment] 2020-05-08 03:42
Run:
npm install @angular/core@9.1.4 @angular/animations@9.1.4 @angular/common@9.1.4 @angular/forms@9.1.4 @angular/platform-browser@9.1.4 @angular/router@9.1.4 @angular/platform-browser-dynamic@9.1.4 @angular/compiler@9.1.4 @angular/compiler-cli@9.1.4 @angular/language-service@9.1.4

ng build

From: https://stackoverflow.com/a/61671596/5157008

**Comment by zmzimpl** [comment] 2020-05-08 05:13
This seems to be an issue in the `9.1.5` version. You can set the dependency on the angular `~ 9.1.4` to` 9.1.4` to force the use of the `9.1.4` version. This works because my project has just had this issue

**Comment by alan-agius4** [comment] 2020-05-08 09:08
Duplicate of https://github.com/angular/angular-cli/issues/17665

**Closed by alan-agius4** 2020-05-08 09:08 UTC

**Comment by ntm1627** [comment] 2020-05-09 01:40
> Run:
> npm install @angular/core@9.1.4 @angular/animations@9.1.4 @angular/common@9.1.4 @angular/forms@9.1.4 @angular/platform-browser@9.1.4 @angular/router@9.1.4 @angular/platform-browser-dynamic@9.1.4 @angular/compiler@9.1.4 @angular/compiler-cli@9.1.4 @angular/language-service@9.1.4
> 
> ng build
> 
> From: https://stackoverflow.com/a/61671596/5157008

Worked perfectly. Thanks
