### ISSUE TITLE
npm install @angular/router@2.0.0-rc.3 is not available

### ISSUE THREAD

**Issue by thinkrapido** [angular/angular#9469] opened 2016-06-22 18:43 UTC
the other packages are available through npm install with release candidate 3, but @angular/router not.

please, be so kind and publish it as soon as possible.
Thanks

**Comment by zoechi** [comment] 2016-06-22 18:46
AFAIK this wasn't updated. Use `rc.2` instead.

**Comment by a88zach** [comment] 2016-06-22 18:49
Or, if you want to use the new router use 3.0.0-alpha.7

**Comment by MaximilianWiedemann** [comment] 2016-06-22 18:58
> Or, if you want to use the new router use 3.0.0-alpha.7
The problem is, you'll then have to fix a critical bug in the .js file. So everytime I reinstall npm modules or deploy (etc.), I would have to apply that fix. I don't want to do that.
It's already been fixed in this repo but it isn't published on npm, yet.

**Comment by thinkrapido** [comment] 2016-06-22 19:15
@zoechi I have to use ```rc.3``` because of the exported ActivatedRoute class

**Comment by thinkrapido** [comment] 2016-06-22 19:25
@a88zach your advice helped, thanks

**Comment by robwormald** [comment] 2016-06-22 19:41
there  will not be any further releases on the 2.0 track of the router. you are able to use angular's rc3 release with the 2.0.0-rc2 release of the router (we unpinned the hard dependency on the last release for this specific reason) - the final release of the 2.0.0 router branch has a dependency graph of 
```js
"peerDependencies": {
    "@angular/core": "^2.0.0-rc",
    "@angular/common": "^2.0.0-rc",
    "@angular/platform-browser": "^2.0.0-rc"
  },
```
meaning it should work with any version greater than 2.0.0-rc

**Closed by robwormald** 2016-06-22 19:41 UTC

**Comment by zoechi** [comment] 2016-06-23 06:46
@thinkrapido then use 3.0.0-alpha.7 as mentioned above already.
