### ISSUE TITLE
Observable (Subject-like) inputs for components and directives

### ISSUE THREAD

**Issue by avchugaev** [angular/angular#46730] opened 2022-07-06 20:44 UTC
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

There're scenarios when a component's or directive's input change triggers some reactive pipeline. Moreover, some pipelines are triggered by a combination of inputs responding to change in any of them.

The simplest use case looks like this:

```ts
@Component({
  selector: 'app-movie'
})
export class MovieComponent implements OnDestroy {
  private readonly id$ = new ReplaySubject<string>(1);

  @Input()
  set id(value: string) {
    this.id$.next(value);
  }
  
  readonly movie$ = this.id$.pipe(switchMap(id => this.collection.find(id)));
  
  constructor(
    private readonly collection: MovieCollection,
  ) {}
  
  ngOnDestroy() {
    this.id$.complete();
  }
}
```

In order to get input as a stream of changes, we have to 

1. Add property containing some `Subject`, typically `ReplaySubject` for inputs without initial value or `BehaviorSubject` for inputs with an initial value;
2. Use setter for input property and push `next` value to that `Subject`;
3. Don't forget to clean up - implement `OnDestroy` and `complete` the `Subject`.
4. Repeat for every input of such kind.

### Proposed solution

The solution to this problem is to allow using `Subject`s as input values:

```ts
@Component({
  selector: 'app-movie'
})
export class MovieComponent {
  @Input()
  readonly id = new ReplaySubject<number>(1);
  
  readonly movie$ = this.id.pipe(switchMap(id => this.collection.find(id)));
  
  constructor(
    private readonly collection: MovieCollection,
  ) {}
}
```

Basically, any object implementing [`NextObserver`](https://rxjs.dev/api/index/interface/NextObserver) should be a legit value. Implementing [`CompletionObserver`](https://rxjs.dev/api/index/interface/CompletionObserver) should be optional.

Such inputs' `Subject`s must be completed automatically when the component/directive is destroyed.

Is may also require a special syntax for such sort of inputs:

```html
<app-movie {id}="123"></app-movie>
```

### Alternatives considered

An alternative may include the usage of a special implementation of `Subject`, like `EventEmitter` for outputs:

```ts
@Component({
  selector: 'app-movie'
})
export class MovieComponent {
  @Input()
  readonly id = new InputSubject<number>(/* optional initial value */);
  
  readonly movie$ = this.id.pipe(switchMap(id => this.collection.find(id)));
  
  constructor(
    private readonly collection: MovieCollection,
  ) {}
}
```

**Comment by pkozlowski-opensource** [comment] 2022-07-06 21:11
This was discussed in the past, see: https://github.com/angular/angular/issues/5689#issuecomment-879474919

**Comment by avchugaev** [comment] 2022-07-06 21:47
@pkozlowski-opensource Thanks for referring me to that comment. What wonders me is that the feature request was open in 2015th 🤯 and no changes since then. For such a long period of time, a lot of boilerplate code has been written 😅 

Also, while reading @mgechev's arguments about RxJS-independent core, I thought "What's the point of doing this as each real-world app/lib inevitable uses streams? Streams are everywhere - in router, forms, HTTP client, in third-party libraries. It won't have any impact on real-world apps bundle size".

**Comment by rothsandro** [comment] 2022-07-07 20:13
I highly agree that this feature would be very useful and will reduce the current boilerplate that comes with creating a setter + a separate subject. But how should this API look like?

---

```ts
readonly id = new ReplaySubject<number>(1);
```

Just using existing RxJs Subjects with the existing `@Input` decorator would be great and provide the most flexibility but this breaks a lot of existing use cases

- When accessing the component instance directly the parent component needs to know if the component uses a subject or not. This is an implementation detail of the component and may change at anytime which would result in a lot of breaking changes.
- How would this work with the new `setInput()` method of ViewContainerRef? The method needs to know if the value should be set or next() should be called.
- May break existing tools like Storybook

---

> Is may also require a special syntax for such sort of inputs

I don't think that a special syntax should be required in the templates. Again: If a component needs a stream of an input or not is an implementation detail that the parent should not care (and know) about and that may change at anytime which would introduce a lot of breaking changes.

---

```ts
readonly id = new InputSubject<number>(/* optional initial value */);
```

This probably solves some of the problems as the type of the subject could be used to know if this is a normal input or nor but gives us less flexibility compared to the existing subjects of RxJs.

**Comment by jessicajaniuk** [comment] 2022-07-07 23:13
Thanks for reporting this issue. However this issue is a duplicate of an existing issue #5689. Please subscribe to that issue for future updates.

**Closed by jessicajaniuk** 2022-07-07 23:13 UTC
Labels: feature, comp: core, votes required

**Comment by avchugaev** [comment] 2022-07-07 23:57
@jessicajaniuk But the issue you mentioned is also closed.

Angular makes us write a lot of boilerplate code - NgModules, imports, manual cleanup, glue between imperative OOP and declarative reactive FP approach...

So why reject ideas intended to minimize it? Technology should change in order to get better.

**Comment by mfp22** [comment] 2022-07-07 23:59
That issue was created 7 years ago and it is locked, with no hint of "when we prioritize that project". I wish they'd just add those 30 lines of code and kick off the audacious project later. I'm sure 90% of the pain would be resolved. 

Angular is the framework that introduced people to FRP just enough for them to love it enough to make Angular annoying for barely utilizing it. It was the perfect amount to force people to learn it and appreciate it, and then see how much easier life could have been if the framework had used it more. Lifecycle hooks and inputs are begging to be expressed as observables. But in Angular we have to insert imperative code into methods while in React we can use hooks to code declaratively.

**Comment by jessicajaniuk** [comment] 2022-07-08 02:43
@avchugaev @mfp22 We're not rejecting the idea. No need to worry there. We're really closing the issue because it's already been well discussed and we're very aware of this given the prior issue. We've been thinking about how we may go about implementing something like this for a while. We're mainly just making sure when we do, we do it in the best way. So stay tuned.

**Comment by mfp22** [comment] 2022-07-08 18:22
@jessicajaniuk Do you think it will be addressed within 3 years? If not, to me that is equivalent to rejecting it
