### ISSUE TITLE
Empty href attribute navigates to the app base

### ISSUE THREAD

**Issue by salemdar** [angular/angular#7294] opened 2016-02-25 22:29 UTC
`<a href="">My Link</a>` would do nothing in Angular 1.x, but it navigates to the app base in Angular 2.

Is this the desired behavior or a bug? If it is the former, than what would be the equivalent of `href=""` in Angular2?

**Comment by zoechi** [comment] 2016-02-25 23:10
See also http://stackoverflow.com/questions/35639174/passive-link-in-angular-2-a-href-equivalent

**Comment by nblasgen** [comment] 2016-02-27 17:07
Zoechi, I'm not yet on Angular2, but almost all regular Angular documentation will tell you to do `<a href>My Link</a>` and not` <a href="">My Link</a>`.  Try removing the equal & quotes and I wouldn't be surprised if that fixes things for you.

**Comment by PascalPrecht** [comment] 2016-02-27 17:14
@salemdar do you get the same behaviour in A1 when you set a `<base href>` ?

Also, what's your use case? Why are you trying to build a link without an `href`?

**Comment by salemdar** [comment] 2016-02-27 20:19
@nblasgen Removing the equal & quotes doesn't make a difference both in angular 1.x and 2, at least not anything I can notice.

@PascalPrecht I get the same behavior with and without `<base href>` in angular 1.x. For example, it comes handy when you want to use a link to call a function from controller.

I always thought that it was a well known and frequently used feature. But the reaction I get from people makes me think that it might not even be a desired feature in angular 1.x.

**Note:**
I'm not looking for css or js hacks for the use case example above. I could do that myself. I'm just interested in an out of box solution.

**Comment by PascalPrecht** [comment] 2016-02-27 20:41
I'm might be big of a friend of semantic HTML, but I'd say that an anchor, without an actual `href` is not an anchor. So in other words, if it doesn't have an `href` then an anchor tag might not be the right element for your use case, regardless of what Angular does with it.

**Comment by salemdar** [comment] 2016-02-27 21:06
@PascalPrecht  Even in this very page's source, if you search for an anchor tag with `manual-file-chooser-tex` class, you'll see a link which is not even accessible, but only there for design purposes. 
Sometimes you might want to act a link like a button. I'm not an HTML standards expert, but I think using a simple anchor tag which does not trigger routing is much more convenient than styling a `<button>` like a link.

**Comment by xak2000** [comment] 2016-06-25 19:03
I think the big problem here is requirement of `base` tag by angular2 router.

The `base` tag is very controversial and in practice causes more problems than solutions. Problems with SVG, problems with `#` (real `#`, that points to id of element on the page). See this [SO question](http://stackoverflow.com/questions/1889076/is-it-recommended-to-use-the-base-html-tag) for more info.

Many of these problems can be solved in codebase, but not when they are in 3d-party library.

I checked several popular sites and none of them use `base` tag. Even `angular.io` doesn't use it. Of course, it could be a coincidence, but it looks more like a trend.

Any chances that [this](https://angular.io/docs/ts/latest/guide/router.html#!#base-href) requirement will be removed?

**Comment by lukiffer** [comment] 2016-07-04 06:03
I think the meat of this issue is in preventing default behavior in the case that both a `(click)` and `href` attribute are specified on an anchor.

As a user migrating from angular1 I would expect `<a href="#" ng-click="foo()">bar</a>` to behave the same as `<a href="#" (click)="foo()">bar</a>`.

For the time being, the best "workaround" I've come up with is `<a href="javascript:void(0);" (click)="foo">bar</a>` which is less than ideal.

The inverse scenario is where `href` isn't equal to `#` and you're intending to fire off both the browser navigation and the handler, but these would seem less prevalent than the former scenario IMHO.

That said, I also agree with @xak2000 that the use of the `<base>` tag poses the potential to cause significant conflicts with third-party components, such as photo album viewers that use `#` for linking directly to a specific photo, or Bootstrap's tab component that uses a hash to link to a specific tab.

I think this is a separate issue though that goes beyond behavioral consistency and treads into "should the router be changed (yet again) to aid compatibility with third party code?" My personal take on that is "no", as I believe that once angular2 reaches wider adoption, those third-party pieces will be brought up to date to be compatible with the new router framework, or use-case specific shims will be made available on a case-by-case basis.

**Comment by ShadowManu** [comment] 2016-08-29 03:01
bump?

**Comment by simeyla** [comment] 2016-12-01 03:24
Another way is <a href="#" (click)="foo(); false">bar</a>

You shouldn't **return false** from **foo()** because that's just icky

**Comment by paustint** [comment] 2016-12-10 04:03
I am looking to have an element act as a link with the mouse responding to the hover element and I am getting a page refresh.  It is standard html behavior (for anything aside from ng2) to be able to use `<a href="#">Some content</a>` for something that acts as a link but does not take the user anywhere.  Having a page refresh occur was not the behavior I was expecting and is annoying to workaround.

**Comment by DzmitryShylovich** [comment] 2017-02-05 21:12
@salemdar how to navigate to the app base then?

**Comment by laserus** [comment] 2018-02-13 14:55
why can't placeholder href used for this purpose?

https://stackoverflow.com/questions/5292343/is-an-anchor-tag-without-the-href-attribute-safe

**Comment by xak2000** [comment] 2018-02-13 15:34
@laserus I think, placeholder link is intended to represent not a link. It's a placeholder for a link, but still not a link until `href` attribute will be added. Like just a `span`.

So the mouse cursor should not be a "hand" and it should not be clickable.

It is useful in "breadcrumb" scenarios, for example, where you don't want the current page to be a link, but still don't want to conditionally replace `a` with `span`.

```
[root] > [subfolder] > [sub-subfolder] > you are here
  <a>        <a>             <a>           still <a>
```

With all of this, I don't think `placeholder link` is solution for this problem.

**Comment by xak2000** [comment] 2018-02-15 19:23
@laserus It's not about styling.

Of course we could style elements as we wish. But the problem with semantic. The intended role of a "placehodler link" is to be not a link, so we shouldn't style them as links and bind click events to them.

This solution is no different than just style a `span` (or any other element), as a link and bind click event to it. This solves the problem of this issue, but violates html element semantic.

**Comment by laserus** [comment] 2018-02-16 10:09
@xak2000 If judging by this logic, then all aforementioned solutions are completely incorrect.

* `<a href="">My Link</a>` shouldn't be here in first place (it should reload page)
* `<a href="#" (click)="foo()">bar</a>` should go to the top of the page
* `<a href="javascript:void(0);" (click)="foo()">bar</a>` just a hack

and what people really want to is a button styled as a hyperlink (for example, http://jsfiddle.net/adardesign/5vHGc/).

But right now I do not see any use for `<a>` placeholder then. Even breadcrumb example above useless (usage is no different from span, and same way it is not affected by tabindex). 

Although, I also do not see how placeholder usage does "violate element semantic". Every approach violates it if we are too strict.

**Comment by xak2000** [comment] 2018-02-16 13:06
> and what people really want to is a button styled as a hyperlink
I agree.

**Comment by cambeaudoin** [comment] 2018-05-10 18:01
Please note: it is an accessibility violation to remove the "href" from an <a>. This is usually why a user would implement `<a href="" (click)="foo()">Bar</a>` in their application. This would be acceptable for accessibility as well as fulfill the standard.
Currently, it seems as though the href="javascript:void(0)" is the only implementation that fulfills all the requirements, despite it being a hack.

**Comment by aicokleinovink** [comment] 2018-07-18 16:58
What about `<a [routerLink]="" (click)="foo()">Bar</a>`? This will render an `href` as well pointing to the same page. Clicking this link calls `foo()` as expected with no side effects such as reloading the page, routing or changing url (such as query params). Haven't tested it in a lot of scenarios as I am not currently working with Angular, but seems to do the trick??

**Comment by SimplGy** [comment] 2018-08-09 00:35
Please don't forget, @laserus and @xak2000, that an anchor tag without href loses both cursor styling AND keyboard navigability (presumably screen reader support too, but unconfirmed).

Styling is easy to fix, but the browser understanding it as a navigable element is really important, I think.

**Comment by stanislavromanov** [comment] 2018-09-26 10:40
So AFAIK this problem is still not fixed in `angular` itself? Bumping.

**Comment by PascalPrecht** [comment] 2018-09-26 10:44
@stanislavromanov I'm sure the team will happily review a pull request from you :)

**Comment by jtomek** [comment] 2019-01-15 10:46
I can confirm that <a [routerLink]="" (click)="foo()">Bar</a> works.

**Comment by Karolis92** [comment] 2019-05-08 09:24
> 
> 
> I can confirm that
> 
> `<a [routerLink]="" (click)="foo()">Bar</a> `
> 
> works.

It works by doing nothing, but if `routerLinkActive` is used with this solution ,then it's always reported as active

**Closed** 2019-06-11 07:37 UTC
Labels: comp: router, freq1: low, severity1: confusing, type: bug/fix

**Comment by nhhockeyplayer** [comment] 2019-06-16 17:40
still cannot create an external link to an out side website in angular using <a href="">

whats going on

**Comment by an0nh4x0r** [comment] 2019-08-01 14:01
> I think the meat of this issue is in preventing default behavior in the case that both a `(click)` and `href` attribute are specified on an anchor.
> 
> As a user migrating from angular1 I would expect `<a href="#" ng-click="foo()">bar</a>` to behave the same as `<a href="#" (click)="foo()">bar</a>`.
> 
> For the time being, the best "workaround" I've come up with is `<a href="javascript:void(0);" (click)="foo()">bar</a>` which is less than ideal.
> 
> The inverse scenario is where `href` isn't equal to `#` and you're intending to fire off both the browser navigation and the handler, but these would seem less prevalent than the former scenario IMHO.
> 
> That said, I also agree with @xak2000 that the use of the `<base>` tag poses the potential to cause significant conflicts with third-party components, such as photo album viewers that use `#` for linking directly to a specific photo, or Bootstrap's tab component that uses a hash to link to a specific tab.
> 
> I think this is a separate issue though that goes beyond behavioral consistency and treads into "should the router be changed (yet again) to aid compatibility with third party code?" My personal take on that is "no", as I believe that once angular2 reaches wider adoption, those third-party pieces will be brought up to date to be compatible with the new router framework, or use-case specific shims will be made available on a case-by-case basis.

Thanks ... This actually helped.

**Comment by baratgabor** [comment] 2019-08-12 12:11
> I can confirm that
> 
> `<a [routerLink]="" (click)="foo()">Bar</a> `
> 
> works.

Works only if you don't have query params to preserve, as it appears to clear all of the params. But `href="javascript:void(0);"` does work for this scenario too.
