### ISSUE TITLE
NgModule syntax with Ivy turned on

### ISSUE THREAD

**Issue by mikolaj-leszczynski** [angular/angular#36917] opened 2020-05-04 19:16 UTC
### Description

When having a simple Angular 9 app and do some logic in `NgModule` I can not build/serve the app successfully.

## 🔬 Minimal Reproduction
1. ng new \<project name\>
2. Be on Angular 9
3. Change `app.module` to:
<pre><code>
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';

import { AppComponent } from './app.component';

function getNgModuleData(){
  return {
    declarations: [AppComponent],
    imports: [BrowserModule],
    providers: [],
    bootstrap: [AppComponent]
  }
}

const { declarations, imports, providers, bootstrap } = getNgModuleData();

@NgModule({ declarations, imports, providers, bootstrap })
export class AppModule { }
</code></pre>

## 🔥 Exception or Error
<pre><code>
▶ yarn build      
yarn run v1.13.0
$ ng build

ERROR in src/app/app.module.ts:17:13 - error NG1010: Expected array when reading the NgModule.declarations of AppModule

17 @NgModule({ declarations, imports, providers, bootstrap })
               ~~~~~~~~~~~~

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.


</code></pre>

What's more: `bootstrap` property is underlined with red line in my IDE saying that:  `Expression does not resolve to an array of class types or a class type `

##  Workaround
<pre><code>

import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';

import { AppComponent } from './app.component';

function getNgModuleData(){
  return {
    declarations: [AppComponent],
    imports: [BrowserModule],
    providers: [],
    bootstrap: [AppComponent]
  }
}

const declarations = getNgModuleData().declarations;
const imports = getNgModuleData().imports;
const providers = getNgModuleData().providers;
const bootstrap = getNgModuleData().bootstrap;

@NgModule({ declarations, imports, providers, bootstrap })
export class AppModule { }
</code></pre>
This works fine. The app can be built and served but still the red squiggly line under bootstrap is visible.

Also this:
<pre><code>
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';

import { AppComponent } from './app.component';

function getNgModuleData(){
  return {
    declarations: [AppComponent],
    imports: [BrowserModule],
    providers: [],
    bootstrap: [AppComponent]
  }
}

@NgModule({...getNgModuleData()})
export class AppModule { }
</code></pre>
can be built with no errors but when serving(ng serve) I'm getting:
<pre><code>
main.ts:12 Error: No ErrorHandler. Is platform module (BrowserModule) included?
    at core.js:42781
    at ZoneDelegate.invoke (zone-evergreen.js:364)
    at Object.onInvoke (core.js:41836)
    at ZoneDelegate.invoke (zone-evergreen.js:363)
    at Zone.run (zone-evergreen.js:123)
    at NgZone.run (core.js:41609)
    at PlatformRef.bootstrapModuleFactory (core.js:42770)
    at core.js:42850
    at ZoneDelegate.invoke (zone-evergreen.js:364)
    at Zone.run (zone-evergreen.js:123)
</code></pre>

## 🌍  Your Environment
<pre><code>

**Angular Version:**
{
  "name": "ng-ex",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~9.1.4",
    "@angular/common": "~9.1.4",
    "@angular/compiler": "~9.1.4",
    "@angular/core": "~9.1.4",
    "@angular/forms": "~9.1.4",
    "@angular/platform-browser": "~9.1.4",
    "@angular/platform-browser-dynamic": "~9.1.4",
    "@angular/router": "~9.1.4",
    "rxjs": "~6.5.5",
    "tslib": "^1.10.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.901.4",
    "@angular/cli": "~9.1.4",
    "@angular/compiler-cli": "~9.1.4",
    "@angular/language-service": "~9.1.4",
    "@types/node": "^12.11.1",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "^5.1.2",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.8.3"
  }
}

</code></pre>

Is it a bug? Is it something well known? I'm aware of this: https://github.com/angular/angular/issues/30840 but this issue does not cover all of the cases I'm experiencing in my example.

**Comment by mikolaj-leszczynski** [comment] 2020-05-07 07:55
@alxhub can you point to some place in the ng codebase so I can investigate this issue on my own?

**Comment by alxhub** [comment] 2020-05-26 20:00
Hi @mikolaj-leszczynski,

I can do better than that!

Ivy places certain requirements on the arguments to Angular decorators (a la `NgModule`):

1. They must be statically understandable
2. They must be object literals, not expressions such as references to other variables.

Currently our static interpreter does not understand the destructuring syntax in your example:
```typescript
const { declarations, imports, providers, bootstrap } = getNgModuleData();
```

I suspect that we resolve `declarations` in `@NgModule({declarations, ...})` to this variable declaration, but in a way that our interpreter doesn't know how to evaluate. This should be pretty easily fixable. :)

**Comment by alxhub** [comment] 2020-05-26 20:05
I ran a simple test and it looks like we're resolving the `declarations` reference to a `ts.BindingElement`, and wrapping that in a `Reference`. Yikes, that's broken.

**Comment by mikolaj-leszczynski** [comment] 2020-05-27 07:31
@alxhub finally someone took a look at it : ) I'm not super familiar with Ivy as it is quite new and I do not know what you mean by:
> I suspect that we resolve declarations in @NgModule({declarations, ...}) to this variable declaration, but in a way that our interpreter doesn't know how to evaluate. 
What do you mean by `(...) to this variable declaration`?

Can you point to me to some file in angular repo where I can investigate it also? 

Thanks in advance!

**Comment by petebacondarwin** [comment] 2020-05-27 09:16
@mikolaj-leszczynski - this is a potentially deep rabbit hole to dive down but here are some files you can take a look at:

So when we come across the following decorator

```ts
@NgModule({ declarations, imports, providers, bootstrap })
```

which is shorthand for:

```ts
@NgModule({
  declarations: declarations,
  imports: imports,
  providers: providers,
  bootstrap: bootstrap
})
```

we need to statically analyse (at compile time) what the value each each of these properties are. In particular in this case we can see that the `declarations` property is assigned the value of the `declarations` variable, which is defined here:

```ts
const { declarations, imports, providers, bootstrap } = getNgModuleData();
```

We then, in turn need to look into the body of the `getNgModuleData()` function to find out what the value of `declarations` is being returned:

```ts
function getNgModuleData(){
  return {
    declarations: [AppComponent],
    imports: [BrowserModule],
    providers: [],
    bootstrap: [AppComponent]
  }
}
```

which should finally resolve to the `[AppComponent]` array.

We have code in the compiler that effectively evaluates these expressions and walks its way around the code based to tell us what the `@NgModule()` arguments are.

You can see this `StaticInterpreter` here: https://github.com/angular/angular/blob/master/packages/compiler-cli/src/ngtsc/partial_evaluator/src/interpreter.ts

What @alxhub  is saying is that when we statically interpret the `declarations` property of the `NgModule()` decorator, we are only getting as far as the `ts.BindingElement` AST Node (probably the one in the assignment of the return value from calling `getNgModuleData()`).  And instead of recursing into the body of this function we are simply saying that the `declarations` property of the `NgModule()` decorator is just a reference to a variable, rather than having a usable value.

**Comment by mikolaj-leszczynski** [comment] 2020-05-27 12:12
@petebacondarwin is checking the body of the `getNgModuleData` function still something that we can do statically ? Don't we have to run this function to get its return data? Maybe this is not a bug?

**Comment by petebacondarwin** [comment] 2020-05-27 15:50
We special case functions that simply return an expression. Such as in this case. Anything more complicated is deemed a "DynamicValue" and there is not much we can do with it.

**Comment by alxhub** [comment] 2020-06-08 16:42
The issue is that our `StaticInterpreter` resolves `declarations` to its declaration as part of the destructuring expression, but it doesn't actually understand destructuring expressions, so it gets thoroughly confused and does something wrong, instead of trying to evaluate the function at all.

**Closed** 2020-06-12 02:10 UTC
Labels: comp: compiler, engine: ivy, state: confirmed, state: has PR, triage #1, type: bug/fix
