### ISSUE TITLE
BazelWorkspaceStatusAction stable-status.txt failed: Failed to determine workspace status: Process exited with status 1

### ISSUE THREAD

**Issue by surajy93** [angular/angular#48504] opened 2022-12-15 12:22 UTC
### Which @angular/* package(s) are the source of the bug?

bazel

### Is this a regression?

No

### Description

[0 / 1] [Prepa] BazelWorkspaceStatusAction stable-status.txt
[0 / 3] [Prepa] BazelWorkspaceStatusAction stable-status.txt
ERROR: <builtin>: BazelWorkspaceStatusAction stable-status.txt failed: Failed to determine workspace status: Process exited with status 1
warning ..\..\package.json: No license field
C:\users\username\webstormprojects\angular\node_modules\ts-node\src\index.ts:843
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
error TS5083: Cannot read file 'C:\Users\username\WebstormProjects\angular\aio\.ng-dev\tsconfig.json'.

    at createTSError (C:\users\username\webstormprojects\angular\node_modules\ts-node\src\index.ts:843:12)
    at reportTSError (C:\users\username\webstormprojects\angular\node_modules\ts-node\src\index.ts:847:19)
    at createFromPreloadedConfig (C:\users\suraj\webstormprojects\angular\node_modules\ts-node\src\index.ts:858:36)
    at create (C:\users\username\webstormprojects\angular\node_modules\ts-node\src\index.ts:613:10)
    at register (C:\users\username\webstormprojects\angular\node_modules\ts-node\src\index.ts:580:15)
    at Object.registerAndCreateEsmHooks (C:\users\username\webstormprojects\angular\node_modules\ts-node\src\esm.ts:116:34)
    at file:///C:/users/username/webstormprojects/angular/node_modules/ts-node/esm.mjs:8:7
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24) {
  diagnosticCodes: [ 5083 ]
}
Target //aio:serve failed to build

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.0.4
Node: 16.19.0
Package Manager: npm 7.21.1
OS: win32 x64
```

### Anything else?

Using bit bash only still facing the same issue

![image](https://user-images.githubusercontent.com/42316893/207858279-a304058d-220e-45ee-9ed8-97256d83b817.png)

**Comment by jessicajaniuk** [comment] 2022-12-16 00:11
This is a duplicate of #46985. The TL;DR is that this is an issue with `ts-node` and not Angular. Until `ts-node` fixes the issue for Windows users, please use `git-bash`.

**Closed by jessicajaniuk** 2022-12-16 00:11 UTC

**Comment by surajy93** [comment] 2022-12-16 05:38
@jessicajaniuk  thank you, but i am using git-bash only still the same issue.

**Comment by JoostK** [comment] 2022-12-16 06:03
It is a dup of https://github.com/angular/angular/issues/46858

**Comment by surajy93** [comment] 2022-12-16 06:06
@JoostK I understand this was duplicate but the resolution provided is not working for me. any help will be appreciate

Using GIT BASH is not WORKING for me

**Comment by JoostK** [comment] 2022-12-16 07:10
@surajy93 I understand, that's why there is an open issue for it to indicate that this is still a problem. I do not know a solution for this problem.
