### ISSUE TITLE
ngOnDestroy not called on service declared using useClass

### ISSUE THREAD

**Issue by Humberd** [angular/angular#28857] opened 2019-02-20 08:39 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/core

### Is this a regression?

 I don't know

### Description

When declaring a service as a component provider by the structure below Angular doesn't call `ngOnDestroy` method declared in `BaseClass` when a component is being destroyed.

```typescript
abstract class BaseClass implements OnDestroy {
	ngOnDestroy() {
		console.log('destroying'); //this is not called
	}	
}

class FooClass extends BaseClass {
}
```

```typescript
{
	provide: BaseClass,
	useClass: FooClass
}
```

## 🔬 Minimal Reproduction

 https://stackblitz.com/edit/angular-service-destroy

## 🌍  Your Environment

**Angular Version:**
<pre><code>@angular-devkit/architect         0.11.3
@angular-devkit/build-angular     0.11.3
@angular-devkit/build-optimizer   0.11.3
@angular-devkit/build-webpack     0.11.3
@angular-devkit/core              7.1.3
@angular-devkit/schematics        7.1.3
@angular/cdk                      7.1.1
@angular/material                 7.1.1
@ngtools/webpack                  7.1.3
@schematics/angular               7.1.3
@schematics/update                0.11.3
rxjs                              6.2.2
typescript                        3.1.6
webpack                           4.23.1
</code></pre>
But it also appears on 7.2.5

**Comment by jlfeld1** [comment] 2019-07-12 18:41
This is also occurring in 8.0.0

**Comment by trotyl** [comment] 2019-07-17 02:08
Duplicate of https://github.com/angular/angular/issues/14821, https://github.com/angular/angular/issues/28738

---

The problem is not about abstract class, but being provided at component level.

```typescript
@Component({
  selector: 'hello',
  template: `Provider component`,
  providers: [
    FirstChildClass,
    {
      provide: BaseClass,
      useClass: SecondChildClass
    }
  ]
})
```

**Comment by kara** [comment] 2020-05-27 23:31
Yep, this looks like a duplicate of https://github.com/angular/angular/issues/14821. Let's track the issue there.

**Closed by kara** 2020-05-27 23:31 UTC
Labels: comp: core, core: di, engine: ve, fixed by Ivy, freq3: high, severity3: broken, triage #1, type: bug/fix
