### ISSUE TITLE
Use component in library

### ISSUE THREAD

**Issue by mbabaei0** [angular/angular#40477] opened 2021-01-19 07:33 UTC
# 🐞 bug report

### Affected Package
"@angular/compiler": "10.1.3",
"@angular/core": "10.1.3",

### Is this a regression?

Did this behavior use to work in the previous version? 
Yes, the previous version in which this bug was not present was: 9

### Description

I have an Angular Library that contains my shared components in a component module. when I build my library with 
`ng build lcf --prod`
everything works fine and builds without any err.
but when I start serve my app which I import and use mt lib everything fails and throw this err :

`class VideoPlayerComponent {
               ~~~~~~~~~~~~~~~~~~~~
    dist/lcf/__ivy_ngcc__/fesm2015/lcf.js:3410:7 - error NG2007: Class is using Angular features but is not decorated. Please add an explicit Angular decorator.
`
I did not get the err before but I don't know what happened suddenly to my lib.

## my component on lib 
<pre><code>
import { Component, OnInit, Output, EventEmitter, Input } from '@angular/core';
import { trigger, transition, animate, style } from '@angular/animations';
// import { environment } from 'src/environments/environment';

@Component({
  selector: 'lcf-modal',
  templateUrl: './modal.component.html',
  styleUrls: ['./modal.component.scss'],
  animations: [
    trigger('dialog', [
      transition('void => *', [
        style({ transform: 'scale3d(.3, .3, .3)' }),
        animate(100),
      ]),
      transition('* => void', [
        animate(100, style({ transform: 'scale3d(.0, .0, .0)' })),
      ]),
    ]),
  ],
})
export class ModalComponent implements OnInit {
  @Input() closable = true;
  @Input() gallary = false;
  @Input() visible = false;
  @Output() visibleChange: EventEmitter<boolean> = new EventEmitter<boolean>();
  assets;
  // @Output('close')closeOutput = new EventEmitter();
  constructor() { }

  ngOnInit() {
    // this.assets = environment.assetsUrl;
  }
  close() {
    this.visible = false;
    this.visibleChange.emit(this.visible);
  }
}
</code></pre>

## 🔥 Exception or Error
<pre><code>
 class ModalComponent {
               ~~~~~~~~~~~~~~
    dist/lcf/__ivy_ngcc__/fesm2015/lcf.js:1815:7 - error NG2007: Class is using Angular features but is not decorated. Please add an explicit Angular decorator.
class VideoPlayerComponent {
               ~~~~~~~~~~~~~~~~~~~~
    dist/lcf/__ivy_ngcc__/fesm2015/lcf.js:3410:7 - error NG2007: Class is using Angular features but is not decorated. Please add an explicit Angular decorator.
    
    3410 class AudioPlayerComponent {
               ~~~~~~~~~~~~~~~~~~~~
    dist/lcf/__ivy_ngcc__/fesm2015/lcf.js:3688:7 - error NG2007: Class is using Angular features but is not decorated. Please add an explicit Angular decorator.

</code></pre>

**Comment by petebacondarwin** [comment] 2021-01-19 09:50
I believe that what has happened is that your project is now running under Ivy, which has tighter restrictions on base classes that use Angular features,  than ViewEngine did.

Basically a duplicate of https://github.com/angular/angular/issues/38660#issuecomment-684615615

**Closed by petebacondarwin** 2021-01-19 09:50 UTC

**Comment by mbabaei0** [comment] 2021-01-19 15:09
@petebacondarwin thank you for answearing. but I'm using a simple angular component and nothing changed I did not get this err until a few days ago with version 10 
and now I don't know what is the problem :(

**Comment by petebacondarwin** [comment] 2021-01-19 15:30
In version 10 ivy became the default. Please check the definition of `VideoPlayerComponent`. Is it decorated as a Component? Does it inherit from another class?

**Comment by mbabaei0** [comment] 2021-01-20 05:44
> Is it decorated as a Component? Does it inherit from another class?

yes it's decorated as a component and there is no inheritance or abstract class

**Comment by petebacondarwin** [comment] 2021-01-20 08:57
In that case, I am unable to help you further without access to a reproduction that I can debug.
