### ISSUE TITLE
Unable to override providers in submodules

### ISSUE THREAD

**Issue by Yqnn** [angular/angular#40471] opened 2021-01-18 14:26 UTC
# 🐞 bug report

### Affected Package
@angular/core

### Is this a regression?
No, I tested from Angular 4 to Angular 11, and bug was always present.

### Description
`providers` array is not taken into account in submodules.
For example, with following module declaration:
```typescript
@NgModule({
  declarations: [ Child1Component ],
  exports: [ Child1Component ],
  providers: [ {provide: MyService, useValue: {'hello': true } } ],
})
export class Module1 { }

@NgModule({
  declarations: [ Child2Component ],
  exports: [ Child2Component ],
  providers: [ {provide: MyService, useValue: {'world': true } } ],
})
export class Module2 { }

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    Module1,
    Module2
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```
I would expect `MyService` to be:
- `{'hello': true }` in `Child1Component`
- `{'world': true }` in `Child2Component`

But it has the same value in the 2 components.

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-ivy-bnxcny?file=src/app/app.module.ts

I expect console to display:
```
hello
world
```

Instead of:
```
world
world
``` 

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 11.0.7
Node: 12.19.0
OS: darwin x64

Angular: 11.0.9
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.7
@angular-devkit/build-angular   0.1100.7
@angular-devkit/core            11.0.7
@angular-devkit/schematics      11.0.7
@angular/cli                    11.0.7
@schematics/angular             11.0.7
@schematics/update              0.1100.7
rxjs                            6.6.3
typescript                      4.0.5
</code></pre>

**Comment by petebacondarwin** [comment] 2021-01-18 14:34
Unless you are lazy loading an `NgModule`, its providers all get put into the root application injector. So effectively what is happening is that the provider in the last `NgModule` to be mentioned wins. You can see this in action by switching the order of the dependencies on `Module1` and `Module2`. See https://stackblitz.com/edit/angular-ivy-ke1fji?file=src/app/app.module.ts

This is by design. There is only one root injector and all these NgModules load their providers into it.

If an NgModule is loaded lazily, then a new injector is created for that NgModule and so its provides would override those of the root injector. Similarly, component instances get their own injector too, so providers specified on a component will override those in the root injector.

Closing as this works as intended.

**Closed by petebacondarwin** 2021-01-18 14:34 UTC
