### ISSUE TITLE
Renderer2 destroy child elements after "selectRootElement"

### ISSUE THREAD

**Issue by elporfirio** [angular/angular#19515] opened 2017-10-02 18:51 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

Based from [https://angular.io/api/core/Renderer2](https://angular.io/api/core/Renderer2 Docs
)

## Current behavior
When use Renderer2 service on form, `selectRootElement` destroys child elements. Based on Bootstrap 4 form reference. [https://getbootstrap.com/docs/4.0/components/forms/](https://getbootstrap.com/docs/4.0/components/forms/ )

## Expected behavior
On selectRootElement method, store DOM instance for use methods like `appenChild()` or `addClass()`

## Minimal reproduction of the problem with instruction
See my example
https://plnkr.co/edit/x2jHrHgODw7oZJgwNlSk

## What is the motivation / use case for changing the behavior?
Instead fill DOM for each possible error, I want to add div with error from a special service.

## Environment

<pre><code>
Angular version: 4.3.6

Browser:
- [X ] Chrome (desktop) version 61

For Tooling issues:
- Node version: 6.11
- Platform:  Mac

</code></pre>

**Comment by tomonari-t** [comment] 2017-10-13 00:53
The cause of this issue is here [dom_render.ts: L143](https://github.com/angular/angular/blob/master/packages/platform-browser/src/dom/dom_renderer.ts#L143)

`el.textContent = '';`

I have no idea that why remove all child elements at this method.

**Comment by tomonari-t** [comment] 2017-10-13 01:31
Sorry.., already on going.

[#19554](https://github.com/angular/angular/issues/19554)

**Comment by mhevery** [comment] 2017-11-30 23:38
closing as dup of #19554

**Closed by mhevery** 2017-11-30 23:38 UTC
Labels: comp: core & compiler, type: bug
