### ISSUE TITLE
Look into supporting entryComponents in TestBed.configureModule

### ISSUE THREAD

**Issue by juliemr** [angular/angular#12079] opened 2016-10-04 20:56 UTC
Right now, this is not supported, but I'm not yet sure if there's a reason behind that. TODO(julie): investigate

**Comment by AlmogShaul** [comment] 2016-10-05 07:30
I think it should be supported, I just had this scenario that I wanted to test a dynamically created component and I had to do a workaround and declare it in a CustomTestModule instead of inside the TestBed

**Comment by michaelbromley** [comment] 2016-11-10 13:53
It should not be necessary to create a new test module for this, you can simply override the `BrowserDynamicTestingModule` (the default module used in testing) like this:

```TypeScript
import {BrowserDynamicTestingModule} from '@angular/platform-browser-dynamic/testing';

TestBed.configureTestingModule({
  declarations: [
    TestComponent,
    // other components...
  ],
  providers: [
    ModalService
  ]
});
  
TestBed.overrideModule(BrowserDynamicTestingModule, {
  set: {
    entryComponents: [ModalComponent]
  }
});
```

Having said that, I think it would be worth allowing it to be set directly in the `configureTestingModule()` method, if it is not too troublesome to implement.

**Comment by jelbourn** [comment] 2017-01-20 19:53
Dupe of #10760

**Comment by titusfx** [comment] 2017-08-16 12:08
@michaelbromley your solution doesn't work anymore. 

TestBed create a dynamic module. So, we can use a module that has the entryComponents ( nothing new ). So, I just import the module where this Component belongs, and is cleaner because you don't need to add anything else ( service, other components, etc.). This should implies if ng serve works then ng test should ( at least from the creation component perspective).

Suppose we have the follow structure:

app
├--- app.module.ts
├--- app.component.ts
├--- ...
├--- SomeModule2
|    ├--- somemodule2.module.ts
|    ├--- componentThatCreateDynamicsComponents
|         ├--- componentThatCreateDynamicsComponents.component.ts
|         ├--- componentThatCreateDynamicsComponents.html
|         ├--- componentThatCreateDynamicsComponents.component.spec.ts
|    ├--- someCOmponent
|         ├--- someCOmponent.component.ts
|         ├--- someCOmponent.html
|         ├--- someCOmponent.component.spec.ts
The TestBed of componentThatCreateDynamicsComponents.component.spec.ts should import somemodule2 from somemodule2.module.ts. In case that you don't split your project into modules, should be the unique module that you have.

Is true that you will have Component that you don't use in that test, but it doesn't matter because is just test. And you gain flexibility when you change you testing module.

**Comment by xnnkmd** [comment] 2017-12-07 11:02
Still lacking this feature. Would be really useful

**Comment by vikerman** [comment] 2018-01-26 22:35
Duplicate of #10760

**Closed by vikerman** 2018-01-26 22:35 UTC
Labels: comp: testing

**Comment by guntram** [comment] 2018-02-14 11:31
`TestBed.overrideModule` feels pretty clean and correct :)

**Comment by Xesenix** [comment] 2018-10-24 07:34
`TestBed.overrideModule` feels like a hack and isn't intuitive at all.

**Comment by manuchadha1979** [comment] 2019-01-08 18:19
well, both overrideModule and a Custom Module look like hacks. It would be more intuitive if this is part of configureTestingModule
