### ISSUE TITLE
Ivy preview report: Error: ASSERTION ERROR: Reached the max number of directives

### ISSUE THREAD

**Issue by kolkov** [angular/angular#31221] opened 2019-06-23 20:35 UTC
Hi! Error when click on catalog item... 
Without Ivy all worked correctly.

`Error: ASSERTION ERROR: Reached the max number of directives`

![image](https://user-images.githubusercontent.com/3740898/59981633-d512d300-960e-11e9-8620-9903817311e0.png)
![image](https://user-images.githubusercontent.com/3740898/59981855-63d51f00-9612-11e9-9f1e-c1ecf919f46f.png)

`<app-store-catalog [baseUrl]="'catalog/'"></app-store-catalog>`
```
<div class="catalog">
  <div *ngFor="let category of (categories$ | async)" [routerLink]="baseUrl + category.path" class="catalog-module">
    <div class="catalog-header">{{category.name}}</div>
    <div class="catalog-body">
      <div class="catalog-img">
        <img [src]="category.image">
      </div>
    </div>
    <div class="catalog-footer">{{category.description}}</div>
  </div>
</div>
```
```
import {Component, Input, OnInit} from '@angular/core';
import {CartHomeService} from "../../../catalog/cart-home.service";
import {map} from "rxjs/operators";

@Component({
  selector: 'app-store-catalog',
  templateUrl: './store-catalog.component.html',
  styleUrls: ['./store-catalog.component.scss']
})
export class StoreCatalogComponent implements OnInit {
  categories$;

  @Input() baseUrl = '';

  constructor(private catalogService: CartHomeService) {
  }

  ngOnInit() {
    this.categories$ = this.catalogService.getList().pipe(
      map(x => x.items)
    );
  }
}
```
```
Angular CLI: 8.1.0-beta.2
Node: 11.14.0
OS: win32 x64
Angular: 8.1.0-next.3
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.801.0-beta.2
@angular-devkit/build-angular      0.801.0-beta.2
@angular-devkit/build-ng-packagr   0.801.0-beta.2
@angular-devkit/build-optimizer    0.801.0-beta.2
@angular-devkit/build-webpack      0.801.0-beta.2
@angular-devkit/core               8.1.0-beta.2
@angular-devkit/schematics         8.1.0-beta.2
@angular/cdk                       8.0.1
@angular/cli                       8.1.0-beta.2
@angular/material                  8.0.1
@ngtools/json-schema               1.1.0
@ngtools/webpack                   8.1.0-beta.2
@schematics/angular                8.1.0-beta.2
@schematics/update                 0.801.0-beta.2
ng-packagr                         5.3.0
rxjs                               6.5.2
typescript                         3.4.5
webpack                            4.34.0
```

Is this a bug?

**Comment by kara** [comment] 2019-06-25 22:41
@kolkov Yeah, this looks like a bug. That shouldn't be a user-facing error; it's only thrown when the framework itself tries to initialize directive data twice. 

Do you have any more code to share? A repo would be best, but if you could make a Stackblitz of what's not working in Ivy (though it will probably work in the Stackblitz), I can port it over and do some testing.

**Comment by kolkov** [comment] 2019-06-26 04:58
[ui.zip](https://github.com/angular/angular/files/3328275/ui.zip)
@kara All project files

**Comment by kara** [comment] 2019-07-09 22:37
@kolvov Can you link to a Github repo instead of a zip file? :)

**Comment by cjhawes** [comment] 2019-10-02 09:48
I have this same issue. Link to the repository where this error has occured: => [https://github.com/cjhawes/angular-practice](url)

**Comment by kara** [comment] 2019-10-04 19:25
@cjhawes Thanks for the repo! I cloned it and have been clicking around, but I can't get the "max directives" error to come up. Can you provide repro instructions? What should I do to get the error?

**Comment by kuncevic** [comment] 2020-01-07 02:41
I did get this error during v9 prerendering after some research I figure out that error was due to `@Inject(WINDOW) private window: Window`:

```
import { WINDOW } from '@ng-toolkit/universal';
import { Directive, ElementRef, Attribute, OnInit, HostListener , Inject, Input} from '@angular/core';

@Directive({ selector: '[scrollTo]' })
export class ScrollToDirective implements OnInit {
  constructor(@Inject(WINDOW) private window: Window,  @Attribute('scrollTo') public elmID: string, private el: ElementRef) { }

  ngOnInit() { }

  //...
}
```

Error gets fixed by removing`@Inject(WINDOW) private window: Window` from `constructor` however in my other app from the same momorepo I am using the same directive and have no issues with that when prerendering

**Comment by VarPDev** [comment] 2020-02-10 11:30
![image](https://user-images.githubusercontent.com/28485062/74146266-06252f80-4c01-11ea-8d26-dd08be13fe55.png)

I have similar error, but I think appear if I use FormBuilder.

**Comment by z6tanker** [comment] 2020-02-11 19:01
Has this been patched? I'm getting the issues with FormBuilder as well...
<img width="997" alt="Screen Shot 2020-02-11 at 2 01 12 PM" src="https://user-images.githubusercontent.com/6894830/74269114-fe37bf00-4cd6-11ea-80f7-71178e7ff3b9.png">

**Comment by VarPDev** [comment] 2020-02-12 07:40
> Has this been patched? I'm getting the issues with FormBuilder as well...
> <img alt="Screen Shot 2020-02-11 at 2 01 12 PM" width="997" src="https://user-images.githubusercontent.com/6894830/74269114-fe37bf00-4cd6-11ea-80f7-71178e7ff3b9.png">

I found a way, but I didn't understand why happen.

**Comment by brunojcm** [comment] 2020-02-12 08:33
I'm also getting this here:
```
core.js:5828 ERROR Error: ASSERTION ERROR: Reached the max number of directives [Expected=> 1 != 1 <=Actual]
    at throwError (core.js:1311)
    at assertNotEqual (core.js:1265)
    at initTNodeFlags (core.js:12830)
    at resolveDirectives (core.js:12513)
    at templateFirstCreatePass (core.js:20538)
    at Module.ɵɵtemplate (core.js:20581)
    at TimeChartComponent_div_1_Template (time-chart.component.html:5)
    at executeTemplate (core.js:11841)
    at renderView (core.js:11627)
    at TemplateRef.createEmbeddedView (core.js:15157)
```

Let me know if you need another repro.

**Comment by VarPDev** [comment] 2020-02-12 08:50
> I'm also getting this here:
> 
> ```
> core.js:5828 ERROR Error: ASSERTION ERROR: Reached the max number of directives [Expected=> 1 != 1 <=Actual]
>     at throwError (core.js:1311)
>     at assertNotEqual (core.js:1265)
>     at initTNodeFlags (core.js:12830)
>     at resolveDirectives (core.js:12513)
>     at templateFirstCreatePass (core.js:20538)
>     at Module.ɵɵtemplate (core.js:20581)
>     at TimeChartComponent_div_1_Template (time-chart.component.html:5)
>     at executeTemplate (core.js:11841)
>     at renderView (core.js:11627)
>     at TemplateRef.createEmbeddedView (core.js:15157)
> ```
> 
> Let me know if you need another repro.

I didn't resolve the problem, I only remove from html the tag that generate error and change way to do some things. I need to resolve the problem for using in right way the form :(

**Comment by NitinSontakke** [comment] 2020-02-17 04:05
In my case I was working on material table adding one thing after another. Pagination and Filtering was fine, however when I added sorting, i first got the following:

core.js:5845 ERROR Error: ASSERTION ERROR: Should be one of Element but got ElementContainer [Expected=> true == false <=Actual]
    at throwError (core.js:1311)
    at assertEqual (core.js:1260)
    at assertNodeOfPossibleTypes (core.js:4197)
    at instantiateAllDirectives (core.js:12658)
    at createDirectivesInstances (core.js:11898)
    at Module.ɵɵelementContainerStart (core.js:21140)
    at MasterGridComponent_Template (master-grid.component.html:21)
    at executeTemplate (core.js:11858)
    at renderView (core.js:11644)
    at renderComponent (core.js:13160)

And when I click on the link to load the component the following:

core.js:5845 ERROR Error: Multiple components match node with tagname mat-form-field
    at throwMultipleComponentError (core.js:7994)
    at findDirectiveDefMatches (core.js:12769)
    at resolveDirectives (core.js:12523)
    at elementStartFirstCreatePass (core.js:20893)
    at Module.ɵɵelementStart (core.js:20934)
    at MasterGridComponent_Template (master-grid.component.html:2)
    at executeTemplate (core.js:11858)
    at renderView (core.js:11644)
    at renderComponent (core.js:13160)
    at renderChildComponents (core.js:11447)

I am almost certain that there is absolutely no other reference, but couldn't resolve it. So thought of just get rid of the mat-input-field altogether and just have:

    <mat-label>Filter</mat-label>
    <input (keyup)="applyFilter($event)">

Then got:

core.js:5845 ERROR Error: ASSERTION ERROR: Reached the max number of directives [Expected=> 1 != 1 <=Actual]
    at throwError (core.js:1311)
    at assertNotEqual (core.js:1265)
    at initTNodeFlags (core.js:12847)
    at resolveDirectives (core.js:12530)
    at elementStartFirstCreatePass (core.js:20893)
    at Module.ɵɵelementStart (core.js:20934)
    at MasterGridComponent_Template (master-grid.component.html:2)
    at executeTemplate (core.js:11858)
    at renderView (core.js:11644)
    at renderComponent (core.js:13160)

If I remove sorting, filtering works fine. Not too sure how to proceed further to have BOTH filtering and sorting work together. Help if possible.

Entire project is up-to-date with all latest versions, as of yesterday, if it helps!

**Comment by NitinSontakke** [comment] 2020-02-17 05:11
Forgot to mention one significant fact that this has nothing to do with Ivy. Never used it and frankly don't even know what it is.

However, which also means that the error can be encountered independent of Ivy.

Sincere apologies for the inconvenience caused, if any. Sorry!

**Comment by techiesantosh** [comment] 2020-02-17 15:49
**I'm also getting this error:**



core.js:3838 ERROR Error: ASSERTION ERROR: Reached the max number of directives [Expected=> 3 != 3 <=Actual]
    at throwError (core.js:1078)
    at assertNotEqual (core.js:1032)
    at initTNodeFlags (core.js:8269)
    at resolveDirectives (core.js:8018)
    at elementStartFirstCreatePass (core.js:14147)
    at ɵɵelementStart (core.js:14181)
    at TaskComponent_Template (template.html:2)
    at executeTemplate (core.js:7495)
    at renderView (core.js:7320)
    at renderComponent (core.js:8510)

**Is there any fix for this ?**

**Comment by AndrewKushnir** [comment] 2020-02-20 04:30
> Let me know if you need another repro.

@brunojcm if you could provide a repro (in a form of Github repo) - that'd be very helpful. Thank you.

**Comment by shlomiassaf** [comment] 2020-02-20 11:49
guys, just an intuition here...

But, whoever has this issue, can you verify that you don't have `entryComponents` and `analyze_for_entry_components` anywhere in your code?

If so, try removing all of them and check if the error is gone.

> I'm not sure if this is also impacted by 3rd party libs doing the above, but let's start by trying to remove this first.

**Comment by rerion** [comment] 2020-02-20 12:14
Hi @shlomiassaf, thanks for the tip

I removed all `entryComponents`, and can confirm this change sadly has no effect  :(

**Comment by emjion** [comment] 2020-02-21 14:10
Hi guys, updated to angular 9.0.2 and added a FormGroup. Been faced with an equal issue. First a "NOT_FOUND [ControlContainer]" is thrown and afterward a "Reached the max number of directives [Expected=> 2 != 2 <=Actual]"

**Comment by rerion** [comment] 2020-02-24 09:46
Hi,

I think i've managed to get a reasonable repro:
https://github.com/rerion/demo-broken-ivy

####
Steps to reproduce:
launch the app, click the link

#### What happens here:
-> this component tries to initialize, but fails because of write here:
https://github.com/rerion/demo-broken-ivy/blob/wat/src/app/table-column.component.ts#L18-L23
(should it?)
-> this causes module load to fail, last url state to be restored, but for some reason
`TableComponent` reinitializes, and error occurs on first structural directive (some dangling subscription?)
https://github.com/rerion/demo-broken-ivy/blob/wat/src/app/table.component.ts#L8

**Comment by adessilly** [comment] 2020-02-26 08:55
In my case, when using ngx-bootstrap dropdown I had the same issue : 
Error: ASSERTION ERROR: Reached the max number of directives
, but I noticed I forgot to import @angular/platform-browser/animations. Everything works fine now.

**Comment by nvdweem** [comment] 2020-02-28 08:25
The same error triggers when using certain @angular/material directives in combination with @angular/elements.
I wasn't able to get StackBlitz to work nicely with Ivy and Material so here is a Git repo with a reproduction:

https://github.com/nvdweem/angular-ivy-max-directives
just npm install & ng s, then open the page and you should run into the debugger statement.

**Comment by nicholas-davis** [comment] 2020-03-05 20:43
Same, I also removed all my entryComponents - the error is still happening. Any luck @shlomiassaf @rerion

**Comment by AndrewKushnir** [comment] 2020-03-05 23:44
Hi @nvdweem, I just tested the repro that you provided with the `9.0.5` Framework version (that was released yesterday) and was unable to reproduce the issue. However I was able to reproduce it with the previous `9.0.4` version. It looks like the changes that were released in the `9.0.5` version resolved the issue. Could you please try to update Angular packages to the `9.0.5` version and see if the problem still exists? Thank you.

**Comment by AndrewKushnir** [comment] 2020-03-06 02:31
Hi, just want to provide some additional information after further investigation.

It looks like `ASSERTION ERROR: Reached the max number of directives` error appears because there is some other error (most likely a fatal one) that happened in the app at creation time, but was caught by the error handling logic (presumably in Router). We will look into this more and try to handle this case better and surface relevant error.

As a temporary workaround, please try to find the original error by pausing on all exceptions in browser dev tools, for example [as described here](https://developers.google.com/web/updates/2015/05/automatically-pause-on-any-exception). Fixing original error should make this assertion disappear as well.

Thank you.

**Comment by nvdweem** [comment] 2020-03-06 07:13
@AndrewKushnir I enabled Ivy (enabled AOT, removed EntryComponents, enableIvy:true in tsconfig) in my main project and the problems seem to be gone now. 
Thanks for fixing/checking :).

**Comment by tarvyn** [comment] 2020-03-12 09:36
> guys, just an intuition here...
> 
> But, whoever has this issue, can you verify that you don't have `entryComponents` and `analyze_for_entry_components` anywhere in your code?
> 
> If so, try removing all of them and check if the error is gone.
> 
> > I'm not sure if this is also impacted by 3rd party libs doing the above, but let's start by trying to remove this first.

That helped me. Thanks!

**Comment by fshena** [comment] 2020-03-27 19:48
Not sure if this is the root cause but for some strange reason after I removed the `form` element, from the html of the component, the error was not occurring anymore.

**Comment by fshena** [comment] 2020-03-27 20:14
It seems to be a combination of the `ReactiveFormsModule` and the html `form` tag.
How to reproduce:
- Import `ReactiveFormsModule` into your module
- Add `form` tag into the html of one of the components being used in the module
- Rebuild the application ( IMPORTANT: Manually rebuild the app, not just the automatic compile after each change )

**Comment by qaisjp** [comment] 2020-04-01 16:28
I get this by importing `ReactiveFormsModule` using it properly in one component template, and then having `<form> ... this form does not use any special (Reactive)FormsModule features </form>` in a different component template.

To reproduce, do that ^ 

And then the page you load will have:

```
ERROR Error: NodeInjector: NOT_FOUND [ControlContainer]
    at getOrCreateInjectable (core.js:5819)
    at Module.ɵɵdirectiveInject (core.js:20861)
    at NodeInjectorFactory.NgControlStatusGroup_Factory [as factory] (forms.js:1009)
    at getNodeInjectable (core.js:5950)
    at instantiateAllDirectives (core.js:12749)
    at createDirectivesInstances (core.js:11989)
    at Module.ɵɵelementStart (core.js:21043)
    at ResourceManageComponent_div_0_Template (manage.component.html:3)
    at executeTemplate (core.js:11949)
    at renderView (core.js:11735)
```

Navigating away to another route and back (in my case, both routes are in the same module that imports this) will then make this appear:

```
ERROR Error: ASSERTION ERROR: Reached the max number of directives [Expected=> 2 != 2 <=Actual]
    at throwError (core.js:1335)
    at assertNotEqual (core.js:1291)
    at initTNodeFlags (core.js:12934)
    at resolveDirectives (core.js:12617)
    at elementStartFirstCreatePass (core.js:20975)
    at Module.ɵɵelementStart (core.js:21016)
    at ResourceManageComponent_div_0_Template (manage.component.html:3)
    at executeTemplate (core.js:11949)
    at renderView (core.js:11735)
    at TemplateRef.createEmbeddedView (core.js:15256)
```

**Comment by ninjavis** [comment] 2020-04-04 12:09
From what I can see in my app:

As soon as there is a <form> used within a component, and one of the form's input's use any directives, I get the same ASSERTION ERROR.

A <form> with standard <input formControlName="blabla"> does not throw this error.

I noticed the error when using an ngx-bootstrap [typeahead] directive on a form input element.

**Comment by KissBalazs** [comment] 2020-04-10 10:31
My experience, maybe it helps someone:
I had a typo in a mat button.
Instead of `<button type="button" mat-raised-button ` I wrote `<button type="button" -raised-button` and this caused the said error:
```
core.js:5873 ERROR Error: Uncaught (in promise): Error: ASSERTION ERROR: Reached the max number of directives [Expected=> 2 != 2 <=Actual]
Error: ASSERTION ERROR: Reached the max number of directives [Expected=> 2 != 2 <=Actual]. 
...
```

**Comment by crisbeto** [comment] 2020-04-10 10:56
In general if you see this error, it means that there was some error while we were constructing the template for the first time. We're currently working on a fix so that these framework errors don't mask errors in your code.

**Comment by jecorrales3** [comment] 2020-04-22 00:11
In my case I was using a layout for every route, just like 

**layout  (authentication)**
  - Login
  - Register

In the module of this layout I was importing the  directives for reactive forms
> import { FormsModule, ReactiveFormsModule } from '@angular/forms'

But, I called again in the principal module of application  **app.module.ts** and that has generated the mistake (half day was lost)

**Closed** 2020-04-29 15:37 UTC
Labels: comp: core, comp: ivy, freq2: medium, severity5: regression, state: has PR, type: bug/fix

**Comment by zaiddabaeen** [comment] 2020-05-13 22:36
Just if anyone's wondering, it isn't just limited to FormModule, I've hit this error today with this piece of code:

```
<span *ngIf="isEditing" dropdownToggle>text</span>
```

Where `dropdownToggle` - from ngx-bootstrap - was put in a wrong place in the template. It was easy to debug since the component is tiny.
