### ISSUE TITLE
Relative link routing with empty paths are not working

### ISSUE THREAD

**Issue by bharathiram** [angular/angular#30437] opened 2019-05-13 18:53 UTC
# 🐞 Bug report
- Relative urls are not working as expected for empty paths when navigate between parent-child routes in the lazy loaded modules
- Relative urls are not working as expected for empty paths when navigate between parent-child routes in the eager loaded modules as well

### Affected Package
The issue is caused by package @angular/router

### Description

- Navigate to child-component (./child1-component)
- Navigate back to parent (../)
- Navigate to child-component again (./child1-component). 
- But it tries to navigate to "//child1-component" & throws an error

```
Routes in app module (forRoot)
const routes: Routes = [
  { 
    path: '',
    loadChildren: 'app/lazy/lazy.module#LazyModule' 
  },
];
```

```
Lazy loaded module routes (forChild)
const routes: Routes = [
  {
    path: '',
    component: LazyComponent,
    children: [
      {
        path: 'child1-component',
        component: BComponent
      },
      {
        path: 'child2-component',
        component: CComponent
      },
    ]
  }
];
```

## 🔬 Minimal Reproduction
Lazy Loading: https://stackblitz.com/edit/relative-link-lazy-loading
Eager Loading: https://stackblitz.com/edit/relative-link-eager-loading

## 🔥 Exception or Error
Error: Uncaught (in promise): SecurityError: Failed to execute 'pushState' on 'History': A history state object with URL 'https://%28child1-component%29/' cannot be created in a document with origin 'https://relative-link-lazy-loading.stackblitz.io' and URL 'https://relative-link-lazy-loading.stackblitz.io/'.

## 🌍  Your Environment
```

Angular CLI: 7.3.3
Node: 10.8.0
OS: darwin x64
Angular: 7.2.15
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

**Angular Version:**
@angular-devkit/architect         0.13.9
@angular-devkit/build-angular     0.13.9
@angular-devkit/build-optimizer   0.13.9
@angular-devkit/build-webpack     0.13.9
@angular-devkit/core              7.3.9
@angular-devkit/schematics        7.3.3
@angular/cdk                      7.3.7
@angular/cli                      7.3.3
@angular/material                 7.3.7
```

**Anything else relevant?**
No

## UPDATE:
It is not specific to lazy loading. I can reproduce the same empty path issue with eager loading as well

https://stackblitz.com/edit/relative-link-eager-loading

**Comment by maktarsis** [comment] 2019-05-18 18:29
After debug, I found out that UrlTree is another, when we try to navigate third time 

Before (first attempt to navigate to ./child1-component

![image](https://user-images.githubusercontent.com/21989873/57973558-5beee300-79b3-11e9-98f0-ebac685d8f5f.png)

After (other attempts to navigate to ./child1-component

![image](https://user-images.githubusercontent.com/21989873/57973581-aec89a80-79b3-11e9-8c2e-e43af39df092.png)

So, after first navigation, we got +1 nested UrlSegmentGroup

**Comment by atscott** [comment] 2020-05-29 19:48
Closing as duplicate of #19290
Related/duplicates:
#13011
#18059
#19290
#35687

**Closed by atscott** 2020-05-29 19:48 UTC
Labels: comp: router, freq1: low, severity3: broken, triage #1, type: bug/fix
