### ISSUE TITLE
[ngStyle] doesn't remove previous attribute (ivy)

### ISSUE THREAD

**Issue by novathore** [angular/angular#33650] opened 2019-11-07 12:07 UTC
# 🐞 bug report

### Is this a regression?
yes, without ivy engine work as expected

### Description
Ivy doesn't delete previous style attribute at dom via [ngStyle]

## 🔬 Minimal Reproduction
https://github.com/novathore/ivy-ng-style
https://github.com/novathore/ivy-ng-style/blob/master/src/app/app.component.ts

## 🌍  Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.0.0-rc.0
Node: 11.14.0
OS: darwin x64
Angular: 9.0.0-rc.1
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-rc.0
@angular-devkit/build-angular     0.900.0-rc.0
@angular-devkit/build-optimizer   0.900.0-rc.0
@angular-devkit/build-webpack     0.900.0-rc.0
@angular-devkit/core              9.0.0-rc.0
@angular-devkit/schematics        9.0.0-rc.0
@angular/cli                      9.0.0-rc.0
@ngtools/webpack                  9.0.0-rc.0
@schematics/angular               9.0.0-rc.0
@schematics/update                0.900.0-rc.0
rxjs                              6.5.3
typescript                        3.6.4
webpack                           4.41.2
</code></pre>

**Comment by Ralny** [comment] 2019-11-07 12:55
> #  bug report
> ### Is this a regression?
> yes, without ivy engine work as expected
> 
> ### Description
> Ivy doesn't delete previous style attribute at dom via [ngStyle]
> 
> ##  Minimal Reproduction
> https://github.com/novathore/ivy-ng-style
> https://github.com/novathore/ivy-ng-style/blob/master/src/app/app.component.ts
> 
> ##  Your Environment
> **Angular Version:**
> 
> ```
> 
> 
>      _                      _                 ____ _     ___
>     / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
>    / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
>   / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
>  /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
>                 |___/
>     
> 
> Angular CLI: 9.0.0-rc.0
> Node: 11.14.0
> OS: darwin x64
> Angular: 9.0.0-rc.1
> ... animations, common, compiler, compiler-cli, core, forms
> ... language-service, platform-browser, platform-browser-dynamic
> ... router
> 
> Package                           Version
> -----------------------------------------------------------
> @angular-devkit/architect         0.900.0-rc.0
> @angular-devkit/build-angular     0.900.0-rc.0
> @angular-devkit/build-optimizer   0.900.0-rc.0
> @angular-devkit/build-webpack     0.900.0-rc.0
> @angular-devkit/core              9.0.0-rc.0
> @angular-devkit/schematics        9.0.0-rc.0
> @angular/cli                      9.0.0-rc.0
> @ngtools/webpack                  9.0.0-rc.0
> @schematics/angular               9.0.0-rc.0
> @schematics/update                0.900.0-rc.0
> rxjs                              6.5.3
> typescript                        3.6.4
> webpack                           4.41.2
> ```

**Comment by raizemm** [comment] 2019-11-15 14:08
I think the issue is here on line **1105**:
https://github.com/angular/angular/blob/e51ec671a57c0a96d1fdd9bd327114e894b874ea/packages/core/src/render3/styling/bindings.ts#L1099-L1105

Passing false makes it go into setStyle if statement, make it a string then set it as property.
Just a random investigation, feel free to correct me.

**Comment by AndrewKushnir** [comment] 2019-12-04 03:55
@novathore, thanks for reporting this issue. The problem was fixed by PR #33920 and the fix is available in v9.0.0-rc.4. Could you please test the behavior again with the mentioned version of the framework and reopen this ticket if the problem still exists? Thank you.

**Closed by AndrewKushnir** 2019-12-04 03:55 UTC
Labels: comp: core, comp: ivy, severity5: ivy-compat, type: bug/fix
