### ISSUE TITLE
Getting started tutorial does not seem to work

### ISSUE THREAD

**Issue by Springrbua** [angular/angular#43053] opened 2021-08-05 06:17 UTC
### Description

A colleague tried out the [Getting started with Angular](https://angular.io/start) but was stuck at a certain point, even when copying and pasting the code from the tutorial into stackblitz. I had a look at it but couldn't find the error, so I tried to go through the tutorial myself and I ended up at the same point.
The problem is, that when I create a new component (in this case the `product-alerts` component), it is not automatically added to the `app.module`, which leads to an error. As soon as I add it to the `app.module`, the app does not work anymore and removing it again does not fix the app.
There is no error in the console but it seems like the application does not recognize the angular components anymore.
I also tried to recreate the same project locally with angular cli and that seems to work.

I am not sure if it is a problem with the example or with stackblitz in general.

### What is the affected URL?

https://angular.io/start

### Please provide the steps to reproduce the issue

1. Open the stackblitz starter for https://angular.io/start
2. right-click the app-folder and select `Angular generator` -> `Component`.
3. Enter the component name (for example `product-alerts`
4. Add `ProductAlertComponent` to the `declarations` in `app.module` (this step is actually missing in the tutorial page)
5. The app should not work anymore
6. Remove the new declaration, the error should persist

### Please provide the expected behavior vs the actual behavior you encountered

First of all, I expected, that generating the component automatically updates the `app.module.ts`, like the Angular CLI does.
If that should not be the case, then this required step should be added to the tutorial.
Of course, I expect the app to work, after adding the needed declaration to the `app.module.ts`, instead the app does not work anymore and removing the declaration doesn't fix it either.

### Please provide a screenshot if possible

App before adding declaration of new component:
![image](https://user-images.githubusercontent.com/18258317/128299876-8504d273-e196-4f08-b04c-c400043aef34.png)

App after adding declaration of new component:
![image](https://user-images.githubusercontent.com/18258317/128299968-1e6617e3-eba1-45ba-b925-15e0dd8132d4.png)

The same app locally (working):
![image](https://user-images.githubusercontent.com/18258317/128300041-66eb93d2-c615-4fbd-8aee-17eb8423dece.png)

### Please provide the exception or error you saw

```true
Unfortunately there was no exception
```

### Is this a browser-specific issue? If so, please specify the device, browser, and version.

```true
Tested with Chrome, Opera and Firefox.
```

**Comment by vugar005** [comment] 2021-08-05 11:24
Hello,Seems like this issue related to Stackblitz hot reload. It breaks when you add new component.  It works on page reload though. Alternatively you can disable hot reload on right sidebar settings.

**Comment by Springrbua** [comment] 2021-08-10 06:22
Thank you for the info @vugar005

**Comment by gkalpak** [comment] 2021-08-23 13:35
Thx for the detailed write-up, @Springrbua :+1:
AFAICT, the StackBlitz issues have been fixed (except for the fact that the newly generated component will not be automatically added to the `AppModule`).

For now, I think it is enough to add a step in the tutorial for manually adding the component to `AppModule`.

I am going to close this as a duplicate of #43020. Let's track the fix there.

**Closed by gkalpak** 2021-08-23 13:35 UTC
Labels: comp: docs
