### ISSUE TITLE
async pipe updates trigger all @Input (v4.0.0)

### ISSUE THREAD

**Issue by QuentinFchx** [angular/angular#15205] opened 2017-03-16 14:46 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When an `async` pipe is present on a component, all component's `@Input` are triggered whenever the async value is updated.
This is especially annoying in the case of `@Input` bounds to setters `@Input() set foo(v){ }`.
Not sure how this is useful, but I observed the following:
It seems that the `async` pipe calls `unwrapValue` which increments `unwrapCounter`, forcing `checkBinding` to return true the first time it's called, causing `updateProp` to be called.

**Expected behavior**
Only the `@Input` bound to the `async` pipe should be updated. (At least it was the case with v2)

**Minimal reproduction of the problem with instructions**
http://embed.plnkr.co/MDvG3iKe4klFCAayIYh5/

**Please tell us about your environment:**
macOS Sierra 10.12.3

* **Angular version:**
4.0.0-rc.3

* **Browser:**
Firefox 47.0.1
 
* **Language:**
Typescript

**Comment by DzmitryShylovich** [comment] 2017-03-16 14:55
Duplicate of https://github.com/angular/angular/issues/15116

**Comment by tbosch** [comment] 2017-03-17 00:50
yes, this is a duplicate...

**Closed by tbosch** 2017-03-17 00:50 UTC
Labels: comp: common, comp: core & compiler, severity5: regression, type: bug
