### ISSUE TITLE
RadioControlValueAccessor throwing error when used with ngControl

### ISSUE THREAD

**Issue by shubhamMuttepawar** [angular/angular#8772] opened 2016-05-22 12:46 UTC
#### app.ts
```typescript
@Component({
    selector: 'my-app',
    templateUrl: './app/templates/app.html',
    pipes:[JsonPipe]
})
export class AppComponent {
private data1: RadioButtonState;
private data2: RadioButtonState;
ngOnInit(){
        this.data1 = new RadioButtonState(false,'data1');
        this.data2 = new RadioButtonState(true,'data2');
    }
}
```

#### app.html
```html
<form #f="ngForm">
    <input type="radio" ngControl="data1" name="sample-data" id="d1" required>
    <label for="d1">{{data1 | json}}</label>

    <input type="radio" ngControl="data2" name="sample-data" id="d2" required>
    <label for="d2">{{data2 | json}}</label>
</form>
````
When I click on radio button am getting this error :
```error
angular2.dev.js:24821 TypeError: Cannot read property 'value' of null
    at RadioControlValueAccessor.registerOnChange.fn.onChange (angular2.dev.js:11585)
    at AppView._View_AppComponent0._handle_change_25_2 (AppComponent.template.js:998)
    at eval (AppComponent.template.js:338)
    at angular2.dev.js:22882
    at angular2.dev.js:8933
    at angular2.dev.js:8630
    at ZoneDelegate.invoke (angular2-polyfills.js:349)
    at Object.NgZoneImpl.inner.inner.fork.onInvoke (angular2.dev.js:2185)
    at ZoneDelegate.invoke (angular2-polyfills.js:348)
    at Zone.runGuarded (angular2-polyfills.js:256)
```

**Comment by michalstepien** [comment] 2016-05-26 12:11
I think, related to:
#8107

**Comment by EdS0ng** [comment] 2016-06-10 00:08
If you instantiate a Control with each radio button state and set ngControl to the control object, it should work. Like `this.data1 = new Control(new RadioButtonState(false, 'data1'))`
Alternatively, you can use ngModel instead of ngControl and use the radio button state directly.
I think this is because ngmodel binds the value property of the native element directly, whereas ngControl binds the value property to the value property of the Control object.

**Comment by kara** [comment] 2016-06-28 23:08
Thanks for the report! Radio buttons have been revamped in the new forms module (RC.2 and onward). See new usage here: #9228. Closing, as the issue is no longer applicable. Please feel free to re-open if you see problems with the new module.

**Closed by kara** 2016-06-28 23:08 UTC
