### ISSUE TITLE
Reactive forms checkbox never touched on safari

### ISSUE THREAD

**Issue by rafalschmidt97** [angular/angular#24836] opened 2018-07-11 11:19 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Checkboxes are never touched on my iphone 7 (using safari and chrome).

Web Google chrome (where it works) [on Safari it doesn't]
![jul-11-2018 13-09-03](https://user-images.githubusercontent.com/14861637/42568122-5263e282-850c-11e8-8606-f2d1b3393aad.gif)

Mobile (where it doens't on my iphone - with android device and chrome it works)
![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/14861637/42568145-6af16a86-850c-11e8-9840-06c0d50e1bf2.gif)

## Expected behavior
It should works on every modern browser.

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-36evjs

## Environment

<pre><code>
Angular version: 6.1.0 (updated before sending issue)
</code></pre>

**Comment by thefliik** [comment] 2018-07-11 19:06
Even in your "working" example, it doesn't appear that the touched status is being updated when it should be (notice how initially checking "tea" doesn't change the status to "touched"). Instead, the view state is lagging one change behind what it should be. This *looks* like an implementation issue caused by an improper change detection strategy. Hard to say for sure without code though.

**Comment by rshmiraf** [comment] 2018-07-11 22:43
Here is example: https://stackblitz.com/edit/angular-36evjs. For now it looks like it doesn't work on safari only.

**Comment by thefliik** [comment] 2018-07-12 02:35
@rshmiraf I cleaned up your example a bit (https://stackblitz.com/edit/angular-dvdtxo), but I also experienced the issue you've described, this time in google chrome 67 on a mac.

Notably, clicking the checkbox (or label) next to "tea" marks the control as dirty and updates its value to true but *does not* mark it as touched. Subsequently clicking anywhere else on the page updates the control as "touched".

**Comment by rshmiraf** [comment] 2018-07-12 07:06
@thefliik great! Yeah - that is weird to click anywhere else to make it touched. Thank you for answering my question. Hope this will be fixed.

**Comment by manklu** [comment] 2018-07-16 08:00
> Notably, clicking the checkbox (or label) next to "tea" marks the control as dirty and updates its value to true but does not mark it as touched.

This is expected behaviour. Excerpt from the Documentation:

> touched: A control is marked touched once the user has triggered a blur event on it.

And for a blur event the control must lost focus.

**Comment by thefliik** [comment] 2018-07-16 09:47
@manklu oh of course! Thanks!

**Comment by kramar** [comment] 2020-07-16 10:38
Hi! Are there any news related to this issue?
Is there a plan to provide fix or workaround for checkbox behavior on iOS?

Thank you!

**Comment by dylhunn** [comment] 2022-01-28 02:04
There was some confusion above about `touched`, which is only supposed to trigger on blur. But the issue remains that it still doesn't work in safari.

**Comment by dylhunn** [comment] 2022-01-28 02:13
So the root cause is pretty crazy! In Safari, clicking a checkbox **does not focus it at all**, therefore, it can never be blurred ("touched")!

Here's a dead-simple reproduction:
```
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
	</head>
	<body>
		<input type="checkbox"
			onfocus="console.log('focused');"
			onblur="console.log('blur');">
				Hello
		</input>
	</body>
</html>
```

**Comment by dylhunn** [comment] 2022-01-28 02:15
@AndrewKushnir Is there anything we can do about this? Or should we close it as a safari issue?

**Comment by AndrewKushnir** [comment] 2022-01-30 19:18
Closing as browser-specific behavior as described in https://github.com/angular/angular/issues/24836#issuecomment-1023819950.

**Closed by AndrewKushnir** 2022-01-30 19:18 UTC
Labels: type: bug/fix, freq3: high, comp: forms, state: confirmed, browser: safari, triage #1, P3
