### ISSUE TITLE
Reactive Forms: modifying a FormArray does not flip dirty switch

### ISSUE THREAD

**Issue by StevenLiekens** [angular/angular#16370] opened 2017-04-27 10:50 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When you add or remove `FormGroup` items to or from a `FormArray`, it does not cause the form to become dirty.

**Expected behavior**
The root `FormGroup` of a form should be in the dirty state after modifying any descendant `FormArray` collection (by means of push/pop/removeAt/...).

**Minimal reproduction of the problem with instructions**

1. Open the Reactive Forms Demo: https://angular.io/generated/live-examples/reactive-forms/final.eplnkr
2. Select a hero
3. Click 'Add a Secret Lair' one or more times.
4. Scroll down to ensure that new secret lairs have been created in the form model. There should be at least one empty address at the end of the `secretLairs` array. Example:
```
heroForm value: {
  "name":"Whirlwind",
  "power":null,
  "sidekick":null,
  "secretLairs":[
    {
      "street":"123 Main",
      "city":"Anywhere",
      "state":"CA",
      "zip":"94801"
    },
    {
      "street":"456 Maple",
      "city":"Somewhere",
      "state":"VA",
      "zip":"23226"
    },
    {
      "street":"",
      "city":"",
      "state":"",
      "zip":""
    }
  ]
}
```
5. Scroll up and observe that the 'Save' and 'Revert' buttons are still disabled. Expected result: the buttons should be enabled.

**What is the motivation / use case for changing the behavior?**

Modifying a `FormArray` collection causes the form model to change so the form should not be considered pristine.

**Angular version:** 4.0.3

**Comment by Ludevik** [comment] 2017-05-25 10:05
I am facing same issue. For now i have to manually mark as dirty parent form group when i push/remove to/from form array.

**Comment by aperl** [comment] 2017-06-01 22:56
I've encountered this same problem

**Comment by rafaelss95** [comment] 2017-06-09 03:20
It's expected behavior.

The docs of forms, says:

```
  /**
   * A control is `pristine` if the user has not yet changed
   * the value in the UI.
   *
   * Note that programmatic changes to a control's value will
   * *not* mark it dirty.
   */
  get dirty(): boolean { return !this.pristine; }
```

Check it [**here**](https://github.com/angular/angular/blob/4.0.0/packages/forms/src/model.ts#L176).

**Comment by Ludevik** [comment] 2017-06-09 07:19
Altough we change the form array programmaticaly by means of push/pop/removeAt functions, the user in most cases interacted with the UI in some way - either clicked some button to add/remove the items to/from the array or did something else in the UI which triggered modification of the array.

**Comment by StevenLiekens** [comment] 2017-06-09 08:12
I understand that a form should not be marked dirty when form groups and controls are initialized for the first time. That is probably​ why changing the form programmatically does not mark the form as dirty? It would be annoying if forms were initially always dirty because of initialization code.

I also agree with Ludevik but I have no suggestions on how to differentiate between calls that come from initialization code or calls that are the result of user interactions.

**Comment by sarora2073** [comment] 2017-07-10 23:46
I'm experiencing the same issue *with* UI changes. I hope we can agree that changing values in formArray via the UI should most definitely change the form's dirty / pristine status but in my experience it does not. 

Sorry I dont have a plunker handy since I'm working with internal code.

**Comment by StevenLiekens** [comment] 2017-07-12 13:05
I replaced the broken link to the demo page with a working link.

Here it is again for good measure: https://angular.io/generated/live-examples/reactive-forms/final.eplnkr

**Comment by kara** [comment] 2017-09-01 23:42
As @rafaelss95 mentioned, this is expected behavior. The "dirty" property on a form control was designed to indicate whether a user has interacted with the form. If programmatic changes were also to make a control dirty, this would defeat the purpose of the property because you'd no longer be able to tell when a value change came from the UI or from application code. 

In the case of a button click that then calls some form method - the forms API has no way of knowing whether this ultimately comes from a user action or whether you're simply setting up the data of the form. You can always call `markAsDirty()` in these cases. Closing, as this works as expected.

**Closed by kara** 2017-09-01 23:42 UTC
Labels: comp: forms

**Comment by sarora2073** [comment] 2017-09-02 12:59
As mentioned earlier, the problem extends to not recognizing user interaction. For example, I'm dynamically creating a forms array with input fields, but populating those input fields in the browser doesn't affect the pristine status...i would hope that would be considered a valid bug. FWIW, I agree with the decision to close as expected for programmatic changes.

**Comment by StevenLiekens** [comment] 2017-09-02 13:49
Hey @kara, I came to the same conclusion but what I didn't realize is that there is an API to Mark the form dirty so I just declared reactive forms unusable.

Can this be reopened as a documentation problem. The 'markAsDirty' API deserves more attention in the reactive forms tutorial and code samples.

**Comment by AleeAwan** [comment] 2018-10-03 12:59
I have noticed another problem, if I change value of a control and then restore it to its original value then control stay's dirty. IMO, control should only be dirty if its value is changed.

**Comment by skreborn** [comment] 2018-10-03 13:09
@AleeAwan As far as I know, the control has no way of knowing what the initial value was once you change it. It doesn't keep a copy of that in memory, so it can't tell when you've restored it, and by extension, can't mark itself pristine when that happens. If you really need this behavior, you'll need to keep a copy yourself and do yourself some RxJS magic.

**Comment by cbaltrinic** [comment] 2018-12-14 21:43
I am having the same issue. I have a form group with one of the controls being a FormArray. When the FormArray is updated via the interface, the control in the FormArray is marked dirty yet the FormGroup remains pristine.

**Comment by zakmac** [comment] 2019-02-04 21:08
> When the FormArray is updated via the interface, the control in the FormArray is marked dirty yet the FormGroup remains pristine.

@cbaltrinic We recently overcame a similar issue, which was to do with directly assigning the FormArray. For example:

```
// note: the FormGroup containing an empty FormArray was set up earlier

// the following code would result in a FormArray which correctly marks itself and child controls
//   as dirty/touched/valid etc, while the parent FormGroup is oblivious to these state changes

(this.form.controls.contactInfo as FormGroup).controls.phones = new FormArray(
  phonesFromServer.map((phone: Phone): FormGroup => {
    const formGroup = this.emptyPhoneNumberForm.formGroup;
    formGroup.patchValue(phone);
    return formGroup;
  })
);
```
With a small modification, this behavior is no longer exhibited:
```
// note: the FormGroup containing an empty FormArray was set up earlier

// this... "just works" (tm)

phonesFromServer.forEach((phone: Phone): void => {

  const formGroup = this.emptyPhoneNumberForm.formGroup;
  formGroup.patchValue(phone);

  ((this.form.controls.contactInfo as FormGroup).controls.phones as FormArray).push(formGroup);
});
```

**Comment by mamichels** [comment] 2019-05-15 12:30
@kara 
While most of the discussion is focusing around programmatic changes to the form, the dirty property is still not being changed on manual user input on nested FormContorls. Currently i have the following case:

```
form: FormGroup = new FormGroup(
arr: new FormArray([])
)
```
Programmatically a undefined set of FormGroups are pushed onto the FormArray
```
arr: [
FormGroup1: {...},
FormGroup2: {...},
FormGroup3: {...},
...
]
```

Manual user input will change the dirty property of FormGroupN (1,2...) to true but will not pass it to its parents. Is this expected behaviour? It certainly results in way more complex logic than it has to be.
Please consider reopening the issue.

**Comment by ricardosaracino** [comment] 2019-05-16 17:35
can confirm that the formarray is dirty but he parent group is infact pristine ... can i work around ya.. is this correct... i would say no

![image](https://user-images.githubusercontent.com/759253/57874763-580a6780-77df-11e9-8c63-d67b0bbbae9b.png)

**Comment by zakmac** [comment] 2019-05-16 23:12
@mamichels by what method are the `FormGroups` being assigned to the `FormArray`?

The suggested method is `myFormArray.push(myFormGroup)`, if the `FormArray` value is being directly assigned in some way, this can break change/dirty/validity detection.

**Comment by ricardosaracino** [comment] 2019-05-16 23:21
Seems pretty reasonable to me
`this.form = this.fb.group({
          volunteerReferences: this.fb.control(this.fb.array(
            volunteerReferences.map(volunteerReference => this.fb.group(volunteerReference))
          ))
        }, {validators: ValidateNestedForm});`
