### ISSUE TITLE
Validation classes not added using type attribute

### ISSUE THREAD

**Issue by HauntedSmores** [angular/angular#12980] opened 2016-11-18 19:19 UTC
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When using validation offered by the type attribute on an input element, such as <input type="email">, Angular 2 does not add the proper ng-invalid class when the browser sees the input as invalid.

**Expected behavior**

ng-invalid and ng-valid classes should be added appropriately when a user's input does not match the pattern defined by HTML5 type attribute.
**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

I believe it is best practice now to use type attributes offered by HTML5 to validate user input before submission.

**Please tell us about your environment:**

OSX, Brackets IDE, Angular CLI

* **Angular version:** 2.0.X

2.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 All browsers
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript
* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment] 2016-11-18 19:20
Pls add a repro in plunkr.

**Comment by pkozlowski-opensource** [comment] 2016-11-22 14:35
@HauntedSmores it is not very clear what you are describing here. Please add a minimal reproduce scenario using a plunker - otherwise this issue report is not actionable and will be closed.

**Comment by HauntedSmores** [comment] 2016-11-22 14:44
@pkozlowski-opensource Sorry, I just havnt had time to make a reproduction. Its really simple though - Angular 2 puts classes on form input elements based on their validity (ng-prestine, ng-valid, ng-invalid, etc.). This works when you set things like required and pattern attributes. It has recently been confirmed by a dev from Google over at the gitter server that Angular does not consider the type attribute (type email, tel, etc.) when it adds its validation classes.

**Comment by pkozlowski-opensource** [comment] 2016-11-22 14:46
In this case this is a duplicate of #2962

**Closed by pkozlowski-opensource** 2016-11-22 14:46 UTC
Labels: comp: forms, state: Need repro
