### ISSUE TITLE
BUG: IVY change detection on push for component within ng-template not invalidated

### ISSUE THREAD

**Issue by kukjevov** [angular/angular#33285] opened 2019-10-21 05:24 UTC
# 🐞 bug report

### Affected Package
@angular/core
@angular/common

### Is this a regression?

Yes definitely yes, it is working without ivy (Angular 8) without any problem.

### Description

When you have components set to `ChangeDetectionStrategy.OnPush` and you have component which obtains `TemplateRef` from its *content* using `ContentChild` for example, then you put component inside this template and change one of its inputs, change detection is not triggered inside this component and you can not see changes, since component inside has not invalidated its view.

If you put your component in `<ng-content>` it is working, but not with `<ng-template>`.

## 🔬 Minimal Reproduction

Here is working version with Angular 8 without IVY
https://stackblitz.com/edit/angular-xfuujc

And here (branch *ivy-error*) is not working version with Angular 9-next.12 with IVY
https://github.com/kukjevov/ng-universal-demo

> `git clone https://github.com/kukjevov/ng-universal-demo.git`
> `cd ng-universal-demo`
> `git checkout ivy-error`
> `npm install`
> `npm start`
> open browser at `http://localhost:8888`

## 🔥 Exception or Error

There is one async change after 5 seconds to `data "bla bla"` and also it is possible to click on button which will cause change of displayed value. In stackblitz it is working, in provided repo it is not working.

## 🌍  Your Environment

**Angular Version:**
Angular 9-next.12

**Anything else relevant?**
Windows: 10.0.17763
Node: 11.6.0
NPM: 6.9.0

**Comment by alexzuza** [comment] 2019-10-21 09:29
This VE behavior was introduced by https://github.com/angular/angular/commit/fcc91d862ffe1aa4c9be847a43147fa670a77277

**Comment by kukjevov** [comment] 2019-10-21 11:10
What does that mean? Is that wanted behaviour? 

If so, how can i do change detection in nested component when input changes?

**Comment by kukjevov** [comment] 2019-10-21 12:23
Hmm i have looked at mentioned commit, but that was change in Angular 4.x, but this is working in version 8 without IVY, so probably not talking about same thing.

**Comment by alexzuza** [comment] 2019-10-21 12:47
Since Angular 4.x till Ivy it works as you want. ViewEngine change detection mechanism makes sure that all EmbeddedViews are marked for check if those views are declared in component which is being checked. With Ivy, as you have noticed, that doesn't work anymore.

> What does that mean? Is that wanted behaviour?

I'm unsure if that is wanted behaviour.

**Comment by ottodranik** [comment] 2019-10-21 16:00
I think that it is a bug. And it is very painful bug. I can't update any data inside ng-template and I really need a fix for this bug.

**Comment by macjohnny** [comment] 2019-10-22 05:55
See also https://github.com/angular/components/pull/15440
Here is a small demo to test the different behavior: https://github.com/macjohnny/ng-ivy-onpush

**Comment by manklu** [comment] 2019-10-25 22:07
@kukjevov Instead of manually trigger change detection, you could use rxjs.

```typescript
import { Component, Input, ChangeDetectionStrategy } from '@angular/core';
import { BehaviorSubject, Subject } from 'rxjs'

@Component({
  selector: 'hello',
  template: `<h1>Hello {{name}}!</h1>
  <button (click)="increment()">click</button>

  <test>
    <ng-template>
        <test-content [data]="data1 | async"></test-content>
    </ng-template>
</test>
`,
  styles: [`h1 { font-family: Lato; }`],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class HelloComponent {
  @Input() name: string;

  data1: Subject<string> = new BehaviorSubject("bla bla bla");

  public counter = 0;

  constructor() {
    setTimeout(() => {
      this.data1.next('ble blo');
      console.log('value is different');
    }, 1000);

  }

  public increment() {
    this.data1.next(`blaaaa ${++this.counter}`);
  }
}
```
Works with IVY@9.0.0-next.11

**Comment by kukjevov** [comment] 2019-11-03 10:19
well @manklu thx, but your solution is workaround, not resolution of problem.

@alxhub Why this is not marked as *compat-ivy* label, since this change will break existing applications after upgrading to version 9?

**Comment by IgorMinar** [comment] 2019-11-08 20:11
This issue is being fixed in https://github.com/angular/angular/pull/33644

**Comment by IgorMinar** [comment] 2019-11-08 20:12
I'll close this issue as dupe of #33393

**Closed by IgorMinar** 2019-11-08 20:12 UTC
Labels: comp: ivy, severity3: broken, severity5: ivy-compat, type: bug/fix
