### ISSUE TITLE
fix(router): canDeactivate should not change the url when returns false and skipLocationChange has been set to true

### ISSUE THREAD

**Issue by ramachandrann** [angular/angular#16314] opened 2017-04-25 12:48 UTC
I'm submitting a ...  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

Current behavior
experiencing the same issue as stated under
https://github.com/angular/angular/issues/12825

Note: #12825 was merged and then reverted in https://github.com/angular/angular/commit/3e548de99d61747fda0803b1f4120b7963a35591

Expected behavior
When we use router.navigate() with skipLocationChange: true, if canDeactivate() returns false when we navigate away from the component, the url shows up the child path

Minimal reproduction of the problem with instructions
see #12825

**Comment by Tim-SE** [comment] 2017-05-16 00:41
Is there any information on why the fix for #12825 was reverted?  We are affected by this as well.

**Comment by pohybel** [comment] 2017-07-31 10:20
Angular 4.3.0: problem still occurs. Are there any plans to fix it?

**Comment by Foszcz** [comment] 2018-03-05 15:29
The problem occurs again on version 5.2.4 . Any plans to fix it?

**Comment by dottodot** [comment] 2018-07-04 09:54
Still an issue in 6.0.7

**Comment by ricardogoncalves** [comment] 2018-10-18 22:33
It was fixed in 7.0.0?

**Comment by miikaeru** [comment] 2018-11-06 07:28
@ricardogoncalves Could you check that?

**Comment by ricardogoncalves** [comment] 2018-11-06 12:48
@miikaeru I've tested with 7.0.0, but It didn't work.

**Comment by dannye** [comment] 2018-11-13 18:20
Yes, I'm still having this issue in 7.0.3

This workaround seems to be working (not very thoroughly tested, but is working for my situation):
```
this.router.events.pipe(filter((event:Event) => event instanceof NavigationCancel)).subscribe(
  (event:NavigationCancel) => {
    this.location.replaceState(event.url);
  }
);
```

**Comment by atscott** [comment] 2020-05-27 19:41
I tried extracting the reproduction from the linked issue and running it in v9: https://stackblitz.com/edit/angular-ivy-a8quoz?file=src%2Fapp%2Fcrisis-center%2Fcrisis-list.component.ts
I could not see the issue that was described. It appears that this may have been resolved at some point. 

If after upgrade the problem still exists in your application please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.

**Closed by atscott** 2020-05-27 19:41 UTC
Labels: comp: router, flag: can be closed?, freq2: medium, severity3: broken, state: Needs repro, triage #1, type: bug/fix
