### ISSUE TITLE
angular.io preloading hints are misconfigured causing duplicate requests

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#34899] opened 2020-01-22 14:43 UTC
# 📚 Docs or angular.io bug report

### Description

See duplicate requests in the network panel + warnings in the console:

<img width="1692" alt="Screen Shot 2020-01-22 at 6 39 43 AM" src="https://user-images.githubusercontent.com/216296/72903479-2177db80-3ce2-11ea-9d6a-3fffb49a3a3d.png">

## 🔬 Minimal Reproduction

visit angular.io or next.angular.io

### What's the affected URL?**
https://angular.io/...

### Reproduction Steps**

Open dev console to see the warnings

### Expected vs Actual Behavior**

no warnings, no duplicate requests

## 🔥 Exception or Error
<pre><code>
VM17:1 A preload for 'https://next.angular.io/generated/navigation.json' is found, but is not used because the request headers do not match.
(anonymous) @ VM17:1

VM17:1 A preload for 'https://next.angular.io/generated/docs/index.json' is found, but is not used because the request headers do not match.
(anonymous) @ VM17:1

The resource https://next.angular.io/generated/navigation.json was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.

The resource https://next.angular.io/generated/docs/index.json was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
</code></pre>

**Comment by ajitsinghkaler** [comment] 2020-02-02 09:51
@IgorMinar I looked into the issue and found out that these files are already prefetched and not preloaded on line 46-56 in https://github.com/angular/angular/blob/4d36b2f6e9a1a7673b3f233752895c96ca7dba1e/aio/ngsw-config.json#L52 is this a problem with service worker??

@gkalpak maybe you can shed some light on this

**Comment by gkalpak** [comment] 2020-02-02 10:15
Thx for looking into this, @ajitsinghkaler! The SW prefetching is something different (and shouldn't be related in this case, since it only happens when a new app version is detected.

The warnings about preloading come from this `preload` header:
https://github.com/angular/angular/blob/4d36b2f6e9a1a7673b3f233752895c96ca7dba1e/aio/firebase.json#L127-L134

I have assigned this myself to take a deeper look in the next few days.

**Comment by ajitsinghkaler** [comment] 2020-02-02 12:49
I think I've debugged the issue please have a look.

**Comment by gkalpak** [comment] 2020-07-18 14:37
I looked into this and I couldn't figure out a good way to fix it. Feels like a browser limitation (or even bug?) - see below.

Here are my journey/findings:

1. Since the warning mentions that the problem is the different request headers, I started by comparing the headers of the preload request with that of the actual, in-app request.

2. The first request header that was different was `Accept`. It had a value of `*/*` in the preload request and a value of `application/json, text/plain, */*` in the actual request. This is because the `HttpClient` will explicitly set `Accept` in not specified by the user:

    https://github.com/angular/angular/blob/136acdfab62767f106c233f86bb47a7d2682ff00/packages/common/http/src/xhr.ts#L101

3. To work around this issue, I explicitly specified `Accept: */*` in `HttpClient#get()` request [here][1]:

    ```diff
    -    const navigationInfo = this.http.get<NavigationResponse>(navigationPath)
    +    const navigationInfo = this.http.get<NavigationResponse>(navigationPath, {headers: {Accept: '*/*'}})
    ```

4. Now the `Accept` headers appeared identical for the two requests in the Network tab in DevTools, but I still got the warning in the Console. So, I looked for other differences in headers.
    <details><summary>Spoiler</summary><i>The `Accept` header is the problem. But I didn't find that out until later.</i></details>

5. The next header that was different was `Sec-Fetch-Mode`. It had a value of `no-cors` in the preload request and a value of `cors` in the actual request. Adding `crossorigin` to the preload request (as suggested anyway in some resources, including [MDN][2]) fixes the `Sec-Fetch-Mode` discrepancy, but...

6. Adding `crossorigin` to the preload request causes it to have an `Origin` header, which is missing from the actual, in-app request. At this point, I thought this difference was causing the problem and I couldn't figure out a way to force the actual request to have that header too.

7. At this point, I tried replacing `HttpClient#get()` with a native `fetch()` or `XMLHttpRequest` and sure enough the warning went away (i.e. the preloaded `navigation.json` file was re-used for the actual, in-app request and no new request was made).

Long story short, it turns out that setting the `Accept` header causes the browser to considers the request headers different and not use the preloaded file. Confusingly, this happens even if the `Accept` header is set to the same value that is shown in the Network tab for the preload request, namely `*/*` 🤷‍♂️

So, basically, replacing [this line][1] with any of the following methods fixes the issue:

- Working solution 1 - Using `fetch()`:
    ```diff
    -    const navigationInfo = this.http.get<NavigationResponse>(navigationPath)
    +    const navigationInfo = require('rxjs').from(fetch(navigationPath).then(res => res.json()))
    ```

- Working solution 2 - Using `XMLHttpRequest`:
    ```diff
    -    const navigationInfo = this.http.get<NavigationResponse>(navigationPath)
    +    const navigationInfo = require('rxjs').from(new Promise(resolve => {
    +      const xhr = new XMLHttpRequest();
    +      xhr.open('GET', navigationPath);
    +      xhr.responseType = 'text';
    +      xhr.onload = () => resolve(JSON.parse(xhr.responseText));
    +      xhr.send(null);
    +    }))
    ```
    _**NOTE:** This is essentially what `HttpClient#get()` does under hood with the exception that `HttpClient#get()` will also call `xhr.setRequestHeader('Accept', 'application/json,  text/plain, */*')`._

Similarly, the following variations of the above solutions stop to work as soon as you try to set the `Accept` header:

- Non-working solution 1 - Using `fetch()` (with the `Accept` header):
    ```diff
    -    const navigationInfo = this.http.get<NavigationResponse>(navigationPath)
    +    const navigationInfo = require('rxjs').from(fetch(navigationPath, {headers: {Accept: '*/*'}}).then(res => res.json()))
    ```

- Non-working solution 2 - Using `XMLHttpRequest` (with the `Accept` header):
    ```diff
    -    const navigationInfo = this.http.get<NavigationResponse>(navigationPath)
    +    const navigationInfo = require('rxjs').from(new Promise(resolve => {
    +      const xhr = new XMLHttpRequest();
    +      xhr.open('GET', navigationPath);
    +      xhr.setRequestHeader('Accept', '*/*');
    +      xhr.responseType = 'text';
    +      xhr.onload = () => resolve(JSON.parse(xhr.responseText));
    +      xhr.send(null);
    +    }))
    ```
    _**NOTE:** This is essentially exactly what `HttpClient#get()` does under hood for this request._

##
**BONUS**

Hacky working solution tricking `HttpClient` into not adding the `Accept` header:

```diff
-import { HttpClient } from '@angular/common/http';
+import { HttpClient, HttpHeaders } from '@angular/common/http';
 ...
 export class NavigationService {
   ...
   private fetchNavigationInfo(): Observable<NavigationResponse> {
+    class HackyHttpHeaders extends HttpHeaders {
+      has(name: string): boolean {
+        // Pretend the `Accept` header is set, so `HttpClient` will not try to set the default value.
+        return (name.toLowerCase() === 'accept') ? true : super.has(name);
+      }
+    }
-    const navigationInfo = this.http.get<NavigationResponse>(navigationPath)
+    const navigationInfo = this.http.get<NavigationResponse>(navigationPath, {headers: new HackyHttpHeaders()})
```


[1]: https://github.com/angular/angular/blob/136acdfab62767f106c233f86bb47a7d2682ff00/aio/src/app/navigation/navigation.service.ts#L56
[2]: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link

**Comment by petebacondarwin** [comment] 2020-07-21 08:24
Perhaps a solution is to add to the API of `HttpClient` to ask it not to add any headers?

**Comment by gkalpak** [comment] 2020-08-24 09:40
Adding an API for this feels a little awkward.

It would feel more straight forward to not add the header and let the users add it if needed, but that would be a breaking change of course. This is discussed in #28915 btw.
(DISCLAIMER: I don't understand the implications of not automatically adding the `Accept` header :grin:)

**Comment by IgorMinar** [comment] 2021-04-01 22:13
I talked to a few people from Chrome and this seems to be a spec bug / oversight / missing feature, so I filed an issue at https://github.com/w3c/preload/issues/157.

It will most likely take a while to get this resolved and implemented in all browsers, so we might want to consider other options  including changing the default as discussed in #28915.

**Comment by JeanMeche** [comment] 2024-02-01 22:51
Closing as we're deprecating AIO

**Closed by JeanMeche** 2024-02-01 22:51 UTC
Labels: type: bug/fix, freq4: critical, area: aio-infra, P3
