### ISSUE TITLE
@angular/bazel not working in new angular 9 project

### ISSUE THREAD

**Issue by shankaryadavy9** [angular/angular#35740] opened 2020-02-28 04:05 UTC
# 🐞 bug report

### Is this a regression?

No

### Description
Just created new project by installing Bazel at global level with below latest technology.
I have followed angular official page to create ng project with bazel
https://angular.io/guide/bazel
But getting below error while running ng serve

## 🔥  Error
<pre><code>
E:\..\bazeltest>ng serve
iBazel [11:17AM]: Error getting Bazel info exit status 2
iBazel [11:17AM]: Querying for files to watch...
)) was unexpected at this time.
iBazel [11:17AM]: Bazel query failed: exit status 255
Loading: 0 packages loaded
ERROR: ../external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl:308:13: Traceback (most recent call last):
        File ".../6t4oby46/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 307
                repository_rule(attrs = dict(COMMON_ATTRIBUTES, ...)}), <2 more arguments>)
        File "...../6t4oby46/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 308, in repository_rule
                dict(COMMON_ATTRIBUTES, **{"args": attr...)})
got multiple values for keyword argument 'args', for call to function dict(args = [], **kwargs)
ERROR: ..../6t4oby46/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl:432:13: Traceback (most recent call last):
        File ".../6t4oby46/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 431
                repository_rule(attrs = dict(COMMON_ATTRIBUTES, ...)}), <2 more arguments>)
        File ".../6t4oby46/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 432, in repository_rule
                dict(COMMON_ATTRIBUTES, **{"args": attr...)})
got multiple values for keyword argument 'args', for call to function dict(args = [], **kwargs)
ERROR: error loading package '': in .../6t4oby46/external/build_bazel_rules_nodejs/index.bzl: Extension file 'internal/npm_install/npm_inst
all.bzl' has errors
Loading: 0 packages loaded
Loading: 0 packages loaded
iBazel [11:17AM]: Bazel query failed: exit status 7
iBazel [11:17AM]: Running //src:devserver
Loading: 0 packages loaded
ERROR: ..../6t4oby46/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl:308:13: Traceback (most recent call last):
        File ".../6t4oby46/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 307
                repository_rule(attrs = dict(COMMON_ATTRIBUTES, ...)}), <2 more arguments>)
        File "..../6t4oby46/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 308, in repository_rule
                dict(COMMON_ATTRIBUTES, **{"args": attr...)})
got multiple values for keyword argument 'args', for call to function dict(args = [], **kwargs)
ERROR: .../6t4oby46/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl:432:13: Traceback (most recent call last):
        File
 ".../6t4oby46/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 431
                repository_rule(attrs = dict(COMMON_ATTRIBUTES, ...)}), <2 more arguments>)
        File 
".......y46/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 432, in repository_rule
                dict(COMMON_ATTRIBUTES, **{"args": attr...)})
got multiple values for keyword argument 'args', for call to function dict(args = [], **kwargs)
ERROR: error loading package '': in ...../6t4oby46/external/build_bazel_rules_nodejs/index.bzl: Extension file 'internal/npm_install/npm_inst
all.bzl' has errors

Loading: 0 packages loaded
Loading: 0 packages loaded
iBazel [11:17AM]: Error running Bazel exit status 7
...\bazeltest\node_modules\@bazel\ibazel\bin\windows_amd64\ibazel.exe failed with code 4.

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.0.3
Node: 12.3.1
OS: win32 x64
windows 10

Angular: 9.0.2
... animations, bazel, common, compiler, compiler-cli, core
... forms, language-service, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.900.3
@angular-devkit/core         9.0.3
@angular-devkit/schematics   9.0.3
@angular/cli                 9.0.3
@bazel/bazel                 2.1.0
@bazel/hide-bazel-files      1.3.0
@bazel/ibazel                0.11.1
@bazel/karma                 1.3.0
@bazel/protractor            1.3.0
@bazel/rollup                1.3.0
@bazel/terser                1.3.0
@bazel/typescript            1.3.0
@schematics/angular          9.0.3
@schematics/update           0.900.3
rxjs                         6.5.4
typescript                   3.7.5
</code></pre>

**Anything else relevant?**

**Comment by shankaryadavy9** [comment] 2020-03-03 11:46
Is there any update or workaround as we stuck to provide solution for our project which is taking hours to prod build .?

**Comment by iamchucky** [comment] 2020-03-05 18:50
I ran into the same error when I was using bazel 0.27.0, but after I update to use bazel 2.1.0 it went away.

maybe try clearing the cache somehow?

**Comment by stefanocke** [comment] 2020-03-07 10:25
Same issue here with Angular / Angular CLI 9.0.5.
(Bazel version is 2.1.0, as above)

**Comment by hiepxanh** [comment] 2020-03-27 04:20
I have same problem with bazel 2.1.0, but it freezing, not display anything.

**Comment by gurezo** [comment] 2020-04-18 06:41
Error getting Bazel occured cli@v10.0.0-next.0.
```
{
  "name": "ng-bazel-sample",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "postinstall": "ngcc --properties es2015 browser module main",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~10.0.0-next.0",
    "@angular/common": "~10.0.0-next.0",
    "@angular/compiler": "~10.0.0-next.0",
    "@angular/core": "~10.0.0-next.0",
    "@angular/forms": "~10.0.0-next.0",
    "@angular/platform-browser": "~10.0.0-next.0",
    "@angular/platform-browser-dynamic": "~10.0.0-next.0",
    "@angular/router": "~10.0.0-next.0",
    "rxjs": "~6.5.4",
    "tslib": "^1.10.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular/bazel": "~10.0.0-next.0",
    "@angular/cli": "~10.0.0-next.0",
    "@angular/compiler-cli": "~10.0.0-next.0",
    "@angular/language-service": "~10.0.0-next.0",
    "@bazel/bazel": "2.1.0",
    "@bazel/ibazel": "0.12.3",
    "@bazel/karma": "1.6.0",
    "@bazel/protractor": "1.6.0",
    "@bazel/rollup": "1.6.0",
    "@bazel/terser": "1.6.0",
    "@bazel/typescript": "1.6.0",
    "@types/node": "^12.11.1",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "^5.1.2",
    "history-server": "1.3.1",
    "html-insert-assets": "0.5.0",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "4.4.1",
    "karma-chrome-launcher": "3.1.0",
    "karma-coverage-istanbul-reporter": "~2.1.0",
    "karma-firefox-launcher": "1.2.0",
    "karma-jasmine": "2.0.1",
    "karma-jasmine-html-reporter": "^1.4.2",
    "karma-requirejs": "1.1.0",
    "karma-sourcemap-loader": "0.3.7",
    "protractor": "5.4.2",
    "requirejs": "2.3.6",
    "rollup": "1.27.5",
    "rollup-plugin-commonjs": "10.1.0",
    "rollup-plugin-node-resolve": "5.2.0",
    "terser": "4.4.0",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~3.8.3"
  }
}

```

**Comment by JohnnyS318** [comment] 2020-05-12 17:02
I have encountered the same issue with bazel 3.1.0.

**Comment by jelbourn** [comment] 2020-10-07 15:28
This sounds like a version mismatch, but there's not much we can investigate without a reproduction.

**Comment by petebacondarwin** [comment] 2020-11-02 20:11
Closing due to a lack of reproduction. If this is still a problem then please open a new issue with a reproduction.

**Closed by petebacondarwin** 2020-11-02 20:11 UTC
Labels: P4, comp: bazel, needs reproduction
