### ISSUE TITLE
Error: No NgModule metadata found for '[object Object]'

### ISSUE THREAD

**Issue by cromefire** [angular/angular#32838] opened 2019-09-24 18:53 UTC
# 🐞 bug report

### Affected Package

The issue is caused by package `@angular/compiler` and/or `@nguniversal/express-engine` apparently

### Is this a regression?

Yes, the previous version in which this bug was not present was: `9.0.0-next.4` I think

### Description

I have angular running with `@nguniversal/express-engine`

## 🔬 Minimal Reproduction

On request

## 🔥 Exception or Error
```
Error: No NgModule metadata found for '[object Object]'.
    at NgModuleResolver.resolve (.../node_modules/@angular/compiler/bundles/compiler.umd.js:22490:27) [<root>]
    at CompileMetadataResolver.getNgModuleMetadata (.../node_modules/@angular/compiler/bundles/compiler.umd.js:21594:47) [<root>]
    at JitCompiler._loadModules (.../node_modules/@angular/compiler/bundles/compiler.umd.js:27793:55) [<root>]
    at JitCompiler._compileModuleAndComponents (.../node_modules/@angular/compiler/bundles/compiler.umd.js:27774:40) [<root>]
    at JitCompiler.compileModuleAsync (.../node_modules/@angular/compiler/bundles/compiler.umd.js:27734:41) [<root>]
    at CompilerImpl.compileModuleAsync (.../node_modules/@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js:330:35) [<root>]
    at CommonEngine.getFactory (.../node_modules/@nguniversal/express-engine/bundles/express-engine.umd.js:102:43) [<root>]
    at CommonEngine.<anonymous> (.../node_modules/@nguniversal/express-engine/bundles/express-engine.umd.js:79:55) [<root>]
    at step (.../node_modules/tslib/tslib.js:136:27) [<root>]
    at Object.next (.../node_modules/tslib/tslib.js:117:57) [<root>]
    at .../node_modules/tslib/tslib.js:110:75 [<root>]
    at new ZoneAwarePromise (.../node_modules/zone.js/dist/zone-node.js:915:33) [<root>]
    at Object.__awaiter (.../node_modules/tslib/tslib.js:106:16) [<root>]
    at CommonEngine.render (.../node_modules/@nguniversal/express-engine/bundles/express-engine.umd.js:56:28) [<root>]
```

## 🌍  Your Environment

**Angular Version:**
```
Angular CLI: 9.0.0-next.5
Node: 12.10.0
OS: linux x64
Angular: 9.0.0-next.7
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router, service-worker

Package                                    Version
--------------------------------------------------------------------
@angular-devkit/architect                  0.900.0-next.5
@angular-devkit/build-angular              0.900.0-next.5
@angular-devkit/build-optimizer            0.900.0-next.5
@angular-devkit/core                       9.0.0-next.5
@angular-devkit/schematics                 9.0.0-next.5
@angular/cdk                               8.1.4
@angular/cli                               9.0.0-next.5
@angular/material                          8.1.4
@angular/pwa                               0.802.2
@nguniversal/common                        v9.0.0-next.1
@nguniversal/express-engine                v9.0.0-next.1
@nguniversal/module-map-ngfactory-loader   v9.0.0-next.1
@schematics/angular                        8.2.2
@schematics/update                         0.900.0-next.5
rxjs                                       6.5.3
typescript                                 3.4.5
webpack                                    4.39.1
```

**Anything else relevant?**

The problem seems to me that NgModuleFactory is not a function, as required here:
https://github.com/angular/angular/blob/32f4544f34594e16a17c24e7f3eba3dbec734900/packages/core/src/reflection/reflection_capabilities.ts#L162-L170

No, downgrading is not an option because I've been told that ivy issues are not fixed anymore for v8

I've disabled `ivy` on the server side via the `tsconfig.server.json`

**Comment by Toxicable** [comment] 2019-09-25 06:27
I don't think `@nguniversal/express-engine` is ready for Ivy yet, since it deals with the compiler APIs directly, it's not a normal package.
Aside from that have you tun `ivy-ngcc`?

**Comment by cromefire** [comment] 2019-09-25 08:29
a) Yes I've run `ivy-ngcc`
b) Important thing I forgot: I've disabled `ivy` on the server side via the `tsconfig.server.json`

**Comment by alxhub** [comment] 2019-10-08 22:58
You can't run `ivy-ngcc` and then compile the code with Ivy disabled. Is that what you're trying to do?

**Comment by cromefire** [comment] 2019-10-08 23:06
No ivy is enabled on the client side and disabled on the server side, that should work right? Or does ivy pollute the dependencies, so that you can't ever compile it without ivy after running ngcc?

**Comment by alxhub** [comment] 2019-11-19 23:54
@cromefire, I'm closing this issue as without a working reproduction, this will be impossible for us to debug. Please feel free to open a new issue with a reproduction if this is still a problem for you.

To answer your question (very lately, I'm sorry!) yes, once `ngcc` runs you cannot rely on the same `node_modules` working with the old compiler.

**Comment by alxhub** [comment] 2019-12-05 23:37
Closing as no reproduction was provided, and the original issue seems related to running `ngcc` and then compiling with View Engine.

**Closed by alxhub** 2019-12-05 23:37 UTC
Labels: comp: compiler, freq1: low, severity1: confusing, state: Needs repro, type: bug/fix
