### ISSUE TITLE
Signal Equality and mutable changes

### ISSUE THREAD

**Issue by rainerhahnekamp** [angular/angular#53139] opened 2023-11-23 20:12 UTC
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

Angular ignores a customized equal function in a Signal when the object reference is the same. @alxhub explained the reasons in https://github.com/angular/angular/issues/52176#issuecomment-1769099075

I have a potential real-world example: https://stackblitz.com/edit/stackblitz-starters-lushjx?file=src%2Fmain.ts, where this causes real issues. I see currently no way how to force a signal to emit on mutable changes.

I would kindly ask you to reconsider removing the short-circuit introduced in https://github.com/angular/angular/pull/52465.

If not, I could provide a PR that explains that behavior in the documentation.

### Proposed solution

Run customized equality check even if object reference is the same.

### Alternatives considered

Update the documentation with a proper explanation: https://angular.dev/guide/signals#signal-equality-functions

**Comment by dmorosinotto** [comment] 2023-11-24 01:05
Even I don’t get the point of having a custom equalityFn if it’s ignored by the short-circuit logic that evaluate it only if `!Object.is`

In my mind (and before the change introduced in #52465 ) the role of equal function was to tell signals how to compare two values (indipendent of their mutable or immutable nature) so the devs take responsibility of return true/false based on their needs.

I don’t fully understood the motivation of @alxhub in #52176 comment where he stated that `equal(x,x)` must always return true if `Object.is(x,x)==true` otherwise we have a change detection problem in template setting input !?

In my mind (and maybe over semplificating it) the template render is “like an effect” that is re-evaluated (render) each times a signal notify a change, and this mechanism involve the equal function to decide when to propagate “real or wanting” value changes… 

I admit that I have NOT enough understanding of the deep template rendering mechanics of  Angular so maybe my previous statement is over semplificate and totally un-realistic , but I’d really like to have and use signal as a **reactive primitive** and have a choise to control it’s _“internal change detection”_  check via my custom equalityFn in **all cases** if possible! 

So I’m pro 👍 to ask reverting the Object.is short-circuit, or really clarify the docs as asked by @rainerhahnekamp  explaining the correct mental model we have to assume when thinking on equal and signal propagation -> change detection / render 🙏

**Comment by atscott** [comment] 2023-11-24 01:19
Duplicate of https://github.com/angular/angular/issues/52735

**Closed by atscott** 2023-11-24 01:19 UTC
Labels: core: reactivity, cross-cutting: signals

**Comment by mikezks** [comment] 2023-11-24 11:24
@dmorosinotto, I understand that the Angular team cannot support change detection scenarios based on mutable Signal updates. TBH, I was surprised that they tried to support mutable updates at the beginning, because the necessary value comparisons come with some runtime costs.

But the current implementation is not intuitive as described above.
