### ISSUE TITLE
Secondary outlet error : Cannot activate an already activated outlet

### ISSUE THREAD

**Issue by LeMalandrin** [angular/angular#29840] opened 2019-04-11 15:28 UTC
Hello,
I'm encountering a problem with router-outlet. 
I have two outlets : the main app router outlet, and a secondary outlet named 'administration'.

When I want to navigate through any administration link at start, it works fine. But next time, when I try to navigate, angular throws this error message :
**Cannot activate an already activated outlet**

I have made a stackblitz to share with you : https://stackblitz.com/edit/angular-zxjslv
Maybe I made a mistake somewhere...

Thank you all :)

**Comment by LeMalandrin** [comment] 2019-04-18 10:49
Someone has found a solution for me on stackoverflow : https://stackblitz.com/edit/angular-osnnd4?file=src%2Fapp%2FComponents%2FAdministration%2Fadministration%2Fadministration.component.ts
I have to manually desactivate the outlet...

This issue seems to be related to lazyloading routing and named outlets...does some fix planned in next release ?

Thanks :)

**Comment by jasonaden** [comment] 2019-05-14 22:37
It would be great to link the StackOverflow solution you found. Then we can see if there's a fix planned for this.

**Comment by atscott** [comment] 2020-07-13 23:54
Duplicate of #20694

**Closed by atscott** 2020-07-13 23:54 UTC
Labels: comp: router, freq2: medium, router: aux routes, router: route config matching/activation, severity3: broken, type: bug/fix
