### ISSUE TITLE
Cli reference page is giving page not found error 

### ISSUE THREAD

**Issue by loveen** [angular/angular#53176] opened 2023-11-26 15:03 UTC
### Describe the problem that you experienced

Cli reference page is giving page not found error 

### Enter the URL of the topic with the problem

https://angular.dev/cli/commands

### Describe what you were looking for in the documentation

Cli reference page is giving page not found error

**Comment by JoostK** [comment] 2023-11-26 15:27
Thanks for the report, closing as duplicate of https://github.com/angular/angular/issues/52549.

**Closed by JoostK** 2023-11-26 15:27 UTC
