### ISSUE TITLE
Router redirect is not working

### ISSUE THREAD

**Issue by mwchan** [angular/angular#12679] opened 2016-11-03 07:37 UTC
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When a request is redirected to "/login" in app-routing.module.ts, I get an error: "Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'login'".

**Expected behavior**
To be able to find the "/login" path or improve the error message if a "default" path is required at the  child level.

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/y970zDKDZRIZ5LQA8v1T?p=preview

I can get this to work if the following change is made:
Go to login-routing.module.ts and modify the children to have a default path(empty string). For example, changing from

    children: [
                    { path: "loginDetails", component: LoginDetailsComponent },
                    { path: "moreLoginDetails", component: MoreLoginDetailsComponent }
                ]

to

    children: [
                    { path: "loginDetails", component: LoginDetailsComponent },
                    { path: "", component: MoreLoginDetailsComponent }
                ]

* **Angular version:** 2.1.2

* **Browser:** [Chrome 53.0.2785.143 m | IE 11.0.9600.185450 ]
 
* **Language:** [TypeScript 2.02]

Thanks in advance!

**Comment by DzmitryShylovich** [comment] 2016-11-03 07:41
Works as intended. See https://github.com/angular/angular/issues/12133

**Comment by mwchan** [comment] 2016-11-03 07:48
Can the error message be improved?

**Comment by vicb** [comment] 2016-11-09 22:58
The fix will be merged and should part of the next release

**Closed by vicb** 2016-11-09 22:58 UTC
