### ISSUE TITLE
Angular 17 does not support custom class decorators in library

### ISSUE THREAD

**Issue by WenXiuchun** [angular/angular#54452] opened 2024-02-15 06:56 UTC
### Which @angular/* package(s) are the source of the bug?

not sure

### Is this a regression?

Yes

### Description

After upgrading from Angular 15 to Angular 17, custom class decorators are not working in the library.

For example, this is the class decorator:
```typescript
export function MyDecorator<T extends { new(...args: any[]): {} }>(originalConstructor: T) {
  // Return a new constructor function
  const newConstructor = class extends originalConstructor {
    // You can modify or extend the constructor here
    constructor(...args: any[]) {
      console.log("new constructor");
      super(...args);
    }
  };

  // copying static methods
  Object.entries(Object.getOwnPropertyDescriptors(originalConstructor))
    .filter(([, descriptor]) => descriptor.writable !== false)
    .forEach(([propName]) => {
      const propertyD = Object.getOwnPropertyDescriptor(originalConstructor, propName);
      if (propertyD) {
        Object.defineProperty(
          newConstructor,
          propName,
          propertyD
        );
      }
    });

  return newConstructor;
}
``` 

This is my-lib.service.ts which used @MyDecorator
```typescript
import { Injectable } from '@angular/core';
import { MyDecorator } from './my-decorator';

@MyDecorator
@Injectable({
  providedIn: 'root'
})
export class MyLibService {

  constructor() {
    console.log("old Constructor")
  }

  getHeros() {
    console.log("my lib service get heros");
  }
}

``` 

The result of angular 15
![image](https://github.com/angular/angular/assets/6194868/716f7ec0-4dd6-4f5e-b210-017773f45cf4)

The result of angular 17
![image](https://github.com/angular/angular/assets/6194868/55e507ba-2e1b-4e31-895f-e3e388c45b4f)

This issue only occurs in libraries of Angular 17, custom class decorator works fine in main application.

The source code:
https://github.com/WenXiuchun/angular15.git
https://github.com/WenXiuchun/angular17.git

custom class decorator with no library:
https://stackblitz.com/edit/stackblitz-starters-8hswdo?file=src%2Fmain.ts

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular: ^17.1.0

node: v18.18.2
```

**Comment by alan-agius4** [comment] 2024-02-15 08:17
Duplicate of https://github.com/angular/angular-cli/issues/24576 and https://github.com/angular/angular/issues/48276.

**Closed by alan-agius4** 2024-02-15 08:17 UTC
