### ISSUE TITLE
pipes API documentation not showing

### ISSUE THREAD

**Issue by Sebbestune** [angular/angular#54916] opened 2024-03-17 21:28 UTC
### Describe the problem that you experienced

When trying to follow the link in pipes guide to the complete list of pipes I can't get to the correct page.

### Enter the URL of the topic with the problem

https://angular.dev/guide/pipes

**Comment by JoostK** [comment] 2024-03-17 21:31
Thanks for the report, closing as duplicate of https://github.com/angular/angular/issues/52968.

**Closed by JoostK** 2024-03-17 21:31 UTC
