### ISSUE TITLE
Fails running jasmine unit tests in hybrid application with inter dependencies between ng1 and ng2 components

### ISSUE THREAD

**Issue by mlakmal** [angular/angular#12545] opened 2016-10-26 13:25 UTC
**I'm submitting a ...**  (check one with "x")

```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Fails running jasmine unit tests in hybrid application with inter dependencies between ng1 and ng2 components.

**Expected behavior**
should be able to run unit tests both ng1 and ng2 components in same hybrid application.

**Minimal reproduction of the problem with instructions**
we have following ng1 components
ng1Value (service) - simple ng1 service without any deps.
ng1Svc (service) - uses ng2 service (TestService/ng2TestSvc) and ng1 ng1Value.
ng1Dir (directive) - uses ng2 service (TestService/ng2TestSvc)
ng1 specs - specs written for ng1Svc an ng1Dir

and have following ng2 components
TestService - simple injectable class using ng1Value from ng1.
ng2 specs written for TestService

when running both ng1 and ng2 specs we are getting following errors.
Uncaught (in promise): Error: Unexpected Zone: angular

plunker located at https://plnkr.co/edit/U6CNOwcbRVGdAg7VNqDu?p=info

I have also ref the prev issue https://github.com/angular/angular/issues/8757. and used similar usage of bootstrap to ref ng1Injector. but it still fails.

Since our app has large number of components that are dep on others and all the components have unit tests written, we can't migrate to Angular 2 without having able to support testing. Appreciate help on this.

**What is the motivation / use case for changing the behavior?**
Trying to move ng1 enterprise application to Angular 2

**Please tell us about your environment:**
Windows 7 x64, VS Code, npm/bower, node/IBM HTTP Server
- **Angular version:** 
  Angular v1.5.8
  Angular v2.1.0
- **Browser:** Chrome

**Comment by petebacondarwin** [comment] 2016-11-23 12:28
So I believe the problem is that `jasmine-patch` is being executed before the upgrade adaptor has been bootstrapped.

When it is run the `jasmine-patch` file gets hold of the current zone (the "ambient" zone).
The upgrade adaptor creates its own zone (`angular`) for the upgraded application during bootstrap
When the tests are executed `jasmine-patch` checks that the current zone (in our case `angular`) is the same as the "ambient" zone when the patch was executed.

I tried finding a way of running the `jasmine-patch` file after the adaptor has bootstrapped. See https://plnkr.co/edit/aDr9YbvIATMdt3bnyB73?p=preview. But this led to other errors.

Does anyone with Zone skills know of a solution to this? @mhevery et al?

**Comment by jquince** [comment] 2017-10-02 16:58
Is there a work around for this?  What did folks end up doing?
This issue is nearly a year old.

**Comment by gkalpak** [comment] 2017-12-15 11:21
I am going to close this as "won't fix", since the dynamic version of ngUpgrade has been deprecated.
Testing with interdependencies is generally a complex thing in ngUpgrade. You should either mock out the parts that come from the other framework or create "mini-apps" that contain all dependencies from both frameworks.

We are also working on some test helpers for the static version of ngUpgrade (e.g. #16848), which should make such things easier in the future.

**Closed by gkalpak** 2017-12-15 11:21 UTC
Labels: comp: testing, comp: upgrade/dynamic, comp: zones, freq2: medium, severity3: broken, type: bug

**Comment by jRichardeau** [comment] 2017-12-22 14:24
Hello,
I'm currently facing this problem too, migrating from ng1 to ng5 with a lot of unit tests that we can't all migrate at once.
Have you any example of how to configure this "mini-app" please ?
Thank you

**Comment by gkalpak** [comment] 2018-01-23 10:37
Sorry, for the late response @jRichardeau. What I meant by "mini app" was actually creating a module (or rather two modules; one for AngularJS and one for Angular) that contain all the necessary components for the test and then bootstrap that module (as you would bootstrap your `AppModule`).
Most of our `ngUpgrade` tests ue this approach. See for example [this test][1] (but really most `ngUpgrade` tests use the same approach - feel free to look around).

[1]: https://github.com/angular/angular/blob/95fbb7d675d43e6d9954a3f8efb051fcf2f1f58a/packages/upgrade/test/static/integration/upgrade_component_spec.ts#L26-L64
