### ISSUE TITLE
Meta.addTag duplicates meta tags in certain situations

### ISSUE THREAD

**Issue by damienwebdev** [angular/angular#42700] opened 2021-06-29 14:09 UTC
# Bug Report

### Affected Package
`@angular/platform-browser`

Specifically https://angular.io/api/platform-browser/Meta

### Is this a regression?

I'm not sure. 

### Description
When I call `addTag` with the same values, I expect to not duplicate the `<meta>` element in the DOM. Currently, it does if you 

```ts
import { DOCUMENT } from '@angular/common';
import { Component, Inject, VERSION } from '@angular/core';
import { Meta } from '@angular/platform-browser';

@Component({
  selector: 'my-app',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  name = 'Angular ' + VERSION.major;

  constructor(
    private meta: Meta,
    @Inject(DOCUMENT) private document: Document
  ) {}

  upsertTag() {
    this.meta.addTag({
      name: 'description',
      content: 'test2'
    });
    this.meta.addTag({
      name: 'description',
      content: 'test3'
    });
  }
}

```

I expect to get back:

```html
<meta name="description" content="test2">
<meta name="description" content="test3">
```

I actually get back the following with an additional entry for each call to `upsertTag`
```html
<meta name="description" content="test2">
<meta name="description" content="test3">
<meta name="description" content="test3">
<meta name="description" content="test3">
<meta name="description" content="test3">
<meta name="description" content="test3">
...
```

## Minimal Reproduction
https://stackblitz.com/edit/angular-ivy-msxqub

## Your Environment

**Angular Version:**
<pre><code>
12.1.0

</code></pre>

This may be a duplicate of https://github.com/angular/angular/issues/19606 but I think this issue represents the problem more correctly.

**Comment by petebacondarwin** [comment] 2021-06-29 15:01
OK, so I see what is happening here...

When the Meta service is trying to work out if the meta already exists it searches for the first meta element that has the same name as the one that is being added. It then checks to see if this element also matches the other attributes. If not it adds a new one.

In this case the first meta is always found and it doesn't match the new (second) meta that is being added so a new element is always created.

Instead we should be using querySelectorAll() to get all the meta elements that match the meta name, and then filtering down those, only adding a new one if the filtered list is empty.

**Comment by petebacondarwin** [comment] 2021-06-29 15:02
Given that I think the issue is the same, and have identified the cause, then I think we should close this as a duplicate and then focus our attention on a fix.

**Closed** 2021-06-29 15:03 UTC
