### ISSUE TITLE
Parameters from Matrix URL notation do not get parsed

### ISSUE THREAD

**Issue by jamajamik** [angular/angular#9797] opened 2016-07-04 10:58 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Parameters from Matrix URL notation do not get parsed. See isSelected function from live demo referenced from Router tutorial: https://angular.io/resources/live-examples/router/ts/plnkr.html
1. Open crisis detail from the list.
2. Go back with cancel - the param id is not parsed and no crises highlighted as selected  

ngOnInit() {
    this.sub = this.route
      .params
      .subscribe(params => {
        this.selectedId = +params['id'];
        this.service.getCrises()
          .then(crises => this.crises = crises);
      });
  }

The same scenario for choosing hero via standard query paramaters is OK.

**Expected/desired behavior**

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** [Firefox 47 ] 
 
* **Language:** [TypeScript X.X]

**Comment by tekton** [comment] 2016-07-20 15:16
Interestingly, non matrix parameters are being parsed.

**Comment by alx-pv** [comment] 2016-07-21 10:43
For some further clarification I've taken two screenshot of the actual and the expected behavior. I've downloaded the [live example](https://angular.io/resources/live-examples/router/ts/plnkr.html) from the angular router docs. For the expected behavior screenshot I manually changed the the Query format in the URL.

**Current**
![actual](https://cloud.githubusercontent.com/assets/20441684/17018983/9852a5ee-4f3a-11e6-8d6f-76695538f8d6.png)

**Expected**
![expected](https://cloud.githubusercontent.com/assets/20441684/17018984/98540150-4f3a-11e6-8c86-3570a191f42a.png)

**Comment by vsavkin** [comment] 2016-07-23 00:24
Fixed here:
https://github.com/angular/angular/commit/a77db44129574af804d4275e4a48831f5362364b

Prior to the fix empty-path routes would not inherit the matrix params from their parents. That's why the id param is not available. 

Since we haven't released a version of the router with the fix, you need to use a nightly build (github.com/angular/router-builds) to see the issue fixed.

Closing this issue.

**Closed by vsavkin** 2016-07-23 00:24 UTC
Labels: comp: router, type: bug
