### ISSUE TITLE
Angular doesn't wait for async validators to complete before firing ngSubmit

### ISSUE THREAD

**Issue by jhonToni** [angular/angular#42250] opened 2021-05-23 15:30 UTC
# Bug Report

### Affected Package

 The issue is caused by package @angular/forms

### Description
When I submit the form, the ngSubmit function is called but async validators have not been completed.

## Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 11.2.2
Node: 14.16.0
OS: win32 x64

Angular:
...
Ivy Workspace:

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1102.2 (cli-only)
@angular-devkit/core         11.2.2 (cli-only)
@angular-devkit/schematics   11.2.2 (cli-only)
@schematics/angular          11.2.2 (cli-only)
@schematics/update           0.1102.2 (cli-only)
</code></pre>

**Comment by Gennady77** [comment] 2021-05-29 19:51
Hello. If I want to be contributor how can I assign the issue for myself (or someone should do for me)? I'm just interested in the process.

**Comment by petebacondarwin** [comment] 2021-05-29 21:57
> Hello. If I want to be contributor how can I assign the issue for myself (or someone should do for me)? I'm just interested in the process.

@Gennady77 - the best way is to comment on an issue saying that you would like to work on it. Then a member of the team can assign it to you, and provide guidance on what needs to be done.

**Comment by Gennady77** [comment] 2021-05-30 15:07
Ok. I see. Let me try to work on this bug :)

**Comment by AndrewKushnir** [comment] 2021-06-05 04:23
Closing this ticket as a duplicate of #31021.

**Closed by AndrewKushnir** 2021-06-05 04:23 UTC
Labels: comp: forms
