### ISSUE TITLE
Change Detector not working after an error

### ISSUE THREAD

**Issue by islamshaheen** [angular/angular#14587] opened 2017-02-19 07:54 UTC
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see  

If i have an html that binds a property on its component and an error happens while detection changes for this property, the whole application will stop detecting changes, even if i add an error handler it wont help.\

Below i have tow properties Code,Name  the Name is binding its value from an external object named EntityPM, now when this object is undefined the change detector will stop for the whole application.
I expect that the code should continue detecting the changes from the input even that there is an error with the name.
 
https://plnkr.co/edit/kg63yyu3GmjdZPaY8cmh?p=preview

 
![image](https://cloud.githubusercontent.com/assets/6479417/23100407/830d099a-f688-11e6-9090-9fb302b7972b.png)

**Comment by DzmitryShylovich** [comment] 2017-02-19 07:57
Duplicate of https://github.com/angular/angular/issues/9531 ?

**Comment by islamshaheen** [comment] 2017-02-19 08:00
@DzmitryShylovich  yes it seems like the same issue.

**Comment by DzmitryShylovich** [comment] 2017-02-19 08:06
then close this issue pls. there's no need to have 2 issues for the same bug. thx

**Closed** 2017-02-19 08:09 UTC
