### ISSUE TITLE
docs css: not always obvious that code elements are links

### ISSUE THREAD

**Issue by jenniferfell** [angular/angular#26370] opened 2018-10-10 16:25 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ X] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[X ] Other... Please describe: AIO docs-infra CSS
</code></pre>

## Current behavior

Currently, if something in code font is also a hyperlink, there is no visual indication until you hover over the text. Then, an underline appears and the cursor shape changes to indicate that it is a hyperlink. 

This is true is all dgeni-generated docs, including both API ref and CLI command ref. 

## Expected behavior

Some readers have reported that they didn't know these code elements are links. 

The most recent report is about the table of schematics in ng generate. It wasn't obvious that the items in this list link to more detail below. Minimally, if we can fix that case (code in a list, or code in a table?) that might help. Perhaps make the underline persistent, even without the hover?

It might be too much clutter to highlight hyperlinked code in larger syntax statements and code examples in the API ref. Know, however, that without a visual indicator it's a learned behavior and extra step to try hovering to see if there is more info. 

## Minimal reproduction of the problem with instructions

![code-font-hyperlink-default-cli-list](https://user-images.githubusercontent.com/31675481/46751041-b0d8b700-cc76-11e8-9a6c-2f3bf11c7261.png)
![code-font-hyperlink-hover-cli-list](https://user-images.githubusercontent.com/31675481/46751047-b2a27a80-cc76-11e8-9777-58b66f85c839.png)
![code-font-hyperlink-default-httpclientmodule](https://user-images.githubusercontent.com/31675481/46751049-b46c3e00-cc76-11e8-83b7-ab3a69f86884.png)
![code-font-link-hover-httpclientmodule](https://user-images.githubusercontent.com/31675481/46751054-b6ce9800-cc76-11e8-8c1b-1e94dc03a2cc.png)

## What is the motivation / use case for changing the behavior?

Help users more easily know when additional information is available with a single click. 

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by siddhant1** [comment] 2018-10-11 19:13
I will try to work on this one !

**Comment by ajitsinghkaler** [comment] 2020-03-06 05:23
@petebacondarwin @gkalpak should we change the colors of the links 

If not I don't think this issue is relevant

**Comment by petebacondarwin** [comment] 2020-03-06 09:13
I think the idea was that we would underline links in code - but I would rather not highlight them. (Sometimes they are wrong 😱).
Happy to close this if @gkalpak and @aikidave agree.

**Comment by gkalpak** [comment] 2020-03-06 11:01
I agree with @petebacondarwin.

**Comment by ajitsinghkaler** [comment] 2020-04-19 15:22
@gkalpak @petebacondarwin so should we underline the links. happy to raise a pr for that

**Comment by aikidave** [comment] 2020-04-19 16:11
We should definitely make it obvious that something is a link. Personally, it drives me crazy when I visit a site and I have no way of knowing that I can click on something.

Just curious though: @petebacondarwin, you don't want to highlight links because they're sometimes wrong? That sounds like another issue we should address. 😄 Are the links generated or manually created? Either way, we should make sure that links are accurate.

@sjtrimble might have some suggestions about how to best style links.

**Comment by petebacondarwin** [comment] 2020-04-19 16:22
We have a dgeni processor that tries to "auto-link" code items. This goes through all the generated code snippets in the rendered HTML and tries to infer if a word in a snippet matches an API item. If so then it creates a link to it. This is quite good but does occasionally get it wrong - either missing an word that could have been linked or linking a word incorrectly. @sonukapoor has recently improved the algorithm for this so it is better than ever. But I am still nervous about highlighting them. I worry that we will then be inundated with issues of incorrect links... The auto-links are really just a bonus rather than a required link - perhaps you could think of them as Easter eggs? 😸🥚

**Comment by jelbourn** [comment] 2020-10-09 20:49
Closing this as working as intended since the code formatting takes precedence over link formatting here. This user experience is modeled after the behavior in IDEs and in tools like Google's code search ([example](https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/docgen/BuildEncyclopediaGenerator.java)), where the content within a code block isn't like a link so much as a cross-reference.

**Closed by jelbourn** 2020-10-09 20:49 UTC
Labels: comp: docs, comp: docs-infra, feature, flag: can be closed?, freq3: high, subtype: docs-design
