### ISSUE TITLE
Main app components constructor or onInit method runs multiple time

### ISSUE THREAD

**Issue by DavidGangel** [angular/angular#4444] opened 2015-10-01 08:14 UTC
I have the following code:
https://gist.github.com/DavidGangel/dd9d5da245784a9a5fa8

Now the execution is the following:
1.It initialize my restManager and routerManager
2.Returns to skins and sets the 2 variables in the constructor.
3.invokes the onInit mehtod.
4.Inside the onInit invokes:
var promise = this.restManager.getSiteMapConfiguration();
5.Moves inside the above method and returns a promise with Pending status.
6.Moves to the next line:
promise.then((data) => { this.routerManager.configureRootRouter(data) });
7.This is not yet ready to be invoked.
8.The whole onInit method starts to re-execute from the beginning.

In the log I get the following exceptions:
```
EXCEPTION: Component "Skins" has no route config. in [null]BrowserDomAdapter.logError @ browser_adapter.js:79BrowserDomAdapter.logGroup @ browser_adapter.js:90ExceptionHandler.call @ exception_handler.js:75(anonymous function) @ application_common.js:92NgZone._onError @ ng_zone.js:162NgZone._createInnerZone.errorHandling.onError @ ng_zone.js:81run @ core.js:73NgZone._createInnerZone.zone.fork.fork.$run @ ng_zone.js:95zoneBoundFn @ core.js:50
browser_adapter.js:79 ORIGINAL EXCEPTION: Component "Skins" has no route config.BrowserDomAdapter.logError @ browser_adapter.js:79ExceptionHandler.call @ exception_handler.js:84(anonymous function) @ application_common.js:92NgZone._onError @ ng_zone.js:162NgZone._createInnerZone.errorHandling.onError @ ng_zone.js:81run @ core.js:73NgZone._createInnerZone.zone.fork.fork.$run @ ng_zone.js:95zoneBoundFn @ core.js:50
browser_adapter.js:79 ORIGINAL STACKTRACE:BrowserDomAdapter.logError @ browser_adapter.js:79ExceptionHandler.call @ exception_handler.js:87(anonymous function) @ application_common.js:92NgZone._onError @ ng_zone.js:162NgZone._createInnerZone.errorHandling.onError @ ng_zone.js:81run @ core.js:73NgZone._createInnerZone.zone.fork.fork.$run @ ng_zone.js:95zoneBoundFn @ core.js:50
browser_adapter.js:79 Error: Component "Skins" has no route config.
    at new BaseException (http://www.private.4cit-group.com/skins/jspm_packages/npm/angular2@2.0.0-alpha.37/src/core/facade/lang.js:40:23)
    at RouteRegistry.generate (http://www.private.4cit-group.com/skins/jspm_packages/npm/angular2@2.0.0-alpha.37/src/router/route_registry.js:176:15)
    at RootRouter.Router.generate (http://www.private.4cit-group.com/skins/jspm_packages/npm/angular2@2.0.0-alpha.37/src/router/router.js:300:41)
    at RouterLink.Object.defineProperty.set [as routeParams] (http://www.private.4cit-group.com/skins/jspm_packages/npm/angular2@2.0.0-alpha.37/src/router/router_link.js:44:50)
    at AbstractChangeDetector.ChangeDetector_Skins_comp_0.detectChangesInRecordsInternal (eval at <anonymous> (unknown source), <anonymous>:42:40)
    at AbstractChangeDetector.detectChangesInRecords (http://www.private.4cit-group.com/skins/jspm_packages/npm/angular2@2.0.0-alpha.37/src/core/change_detection/abstract_change_detector.js:91:12)
    at AbstractChangeDetector.runDetectChanges (http://www.private.4cit-group.com/skins/jspm_packages/npm/angular2@2.0.0-alpha.37/src/core/change_detection/abstract_change_detector.js:74:10)
    at AbstractChangeDetector._detectChangesInShadowDomChildren (http://www.private.4cit-group.com/skins/jspm_packages/npm/angular2@2.0.0-alpha.37/src/core/change_detection/abstract_change_detector.js:141:12)
    at AbstractChangeDetector.runDetectChanges (http://www.private.4cit-group.com/skins/jspm_packages/npm/angular2@2.0.0-alpha.37/src/core/change_detection/abstract_change_detector.js:78:10)
    at AbstractChangeDetector.detectChanges (http://www.private.4cit-group.com/skins/jspm_packages/npm/angular2@2.0.0-alpha.37/src/core/change_detection/abstract_change_detector.js:65:10)BrowserDomAdapter.logError @ browser_adapter.js:79ExceptionHandler.call @ exception_handler.js:88(anonymous function) @ application_common.js:92NgZone._onError @ ng_zone.js:162NgZone._createInnerZone.errorHandling.onError @ ng_zone.js:81run @ core.js:73NgZone._createInnerZone.zone.fork.fork.$run @ ng_zone.js:95zoneBoundFn @ core.js:50
browser_adapter.js:79 ERROR CONTEXT:BrowserDomAdapter.logError @ browser_adapter.js:79ExceptionHandler.call @ exception_handler.js:91(anonymous function) @ application_common.js:92NgZone._onError @ ng_zone.js:162NgZone._createInnerZone.errorHandling.onError @ ng_zone.js:81run @ core.js:73NgZone._createInnerZone.zone.fork.fork.$run @ ng_zone.js:95zoneBoundFn @ core.js:50
browser_adapter.js:79 _Context {element: a.ng-binding, componentElement: skins, context: Skins, locals: Object, injector: Injector…}
```

And of course it does not have a route config as this is just provided by success of the promise:
promise.then((data) => { this.routerManager.configureRootRouter(data) });

**Comment by alxhub** [comment] 2015-10-01 22:21
Hi David,

I'm not an expert on the router - @btford would know more, but I believe this is caused by use of the `router-link` directive in the `Skins` component template. Change detection causes the `router-link` invocation to be evaluated immediately after `onInit` returns, and the exception is thrown because no router configuration has been set yet.

I'm not sure, but you might be able to delay `router-link` by using the `async` pipe to only give it a value once the configuration has been loaded.

As for `onInit` being called multiple times, I believe this is #4323.

**Comment by btford** [comment] 2015-10-01 22:33
Try adding an empty `@RouteConfig([])` annotation to `Skins`.

**Comment by DavidGangel** [comment] 2015-10-04 08:42
Thank you for your responses.
@btford it does not change anything.

**Comment by DavidGangel** [comment] 2015-10-04 13:28
I think one solution could be to not allow the code inside the onInit method to jump to the next instruction until the configuration is not fetched from the server and  the router config is not ready based on this. Then all the problems must go away. The consequence is that this approach will make the execution as sync and not async. But if I ask myself:
Are there any benefits to load an app with a router that's not configured?
I guess the answer is no.

So how could I wait until the router config is done?

**Comment by vsavkin** [comment] 2016-07-07 01:20
We are no longer maintaining the deprecated router to focus our efforts on making the new router robust. And the new router does not have this issue. So I'm closing it.

**Closed by vsavkin** 2016-07-07 01:20 UTC
Labels: comp: router-deprecated, effort2: medium (day), P2: required, type: bug
