### ISSUE TITLE
ng serve/build doesn't work on IE11 when IVY is enabled

### ISSUE THREAD

**Issue by WilhelmOlejnik** [angular/angular#30637] opened 2019-05-23 11:15 UTC
# 🐞 Bug report

### Command (mark with an `x`)

```
- [x] build
- [x] serve
```

### Description
When ivy is enabled app throws error on IE11 after `ng serve` and `ng build`.
```
SCRIPT1046: Multiple definitions of a property not allowed in strict mode
File: vendor.js, line: 4066, column: 25
```
```
NgForOf.ngDirectiveDef = _angular_core__WEBPACK_IMPORTED_MODULE_0__["ΔdefineDirective"]({ type: NgForOf, selectors: [["", "ngFor", "", "ngForOf", ""]], factory: function NgForOf_Factory(t) { return new (t || NgForOf)(_angular_core__WEBPACK_IMPORTED_MODULE_0__["ΔdirectiveInject"](_angular_core__WEBPACK_IMPORTED_MODULE_0__["ViewContainerRef"]), _angular_core__WEBPACK_IMPORTED_MODULE_0__["ΔdirectiveInject"](_angular_core__WEBPACK_IMPORTED_MODULE_0__["TemplateRef"]), _angular_core__WEBPACK_IMPORTED_MODULE_0__["ΔdirectiveInject"](_angular_core__WEBPACK_IMPORTED_MODULE_0__["IterableDiffers"])); }, inputs: { ngForOf: "ngForOf", ngForTrackBy: "ngForTrackBy", ngForTemplate: "ngForTemplate" } });
/*@__PURE__*/ _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵsetClassMetadata"](NgForOf, [{
        type: _angular_core__WEBPACK_IMPORTED_MODULE_0__["Directive"],
        args: [{ selector: '[ngFor][ngForOf]' }]
    }], function () { return [{ type: _angular_core__WEBPACK_IMPORTED_MODULE_0__["ViewContainerRef"] }, { type: _angular_core__WEBPACK_IMPORTED_MODULE_0__["TemplateRef"] }, { type: _angular_core__WEBPACK_IMPORTED_MODULE_0__["IterableDiffers"] }]; }, { _viewContainer: [], _template: [], _differs: [], _ngForOfDirty: [], _differ: [], ngForOf: [{
            type: _angular_core__WEBPACK_IMPORTED_MODULE_0__["Input"]
        }], ngForTrackBy: [{
            type: _angular_core__WEBPACK_IMPORTED_MODULE_0__["Input"]
        }], ngForTrackBy: [], ngForTemplate: [{  <========== HERE IS AN ERROR
            type: _angular_core__WEBPACK_IMPORTED_MODULE_0__["Input"]
        }], ngDoCheck: [], _applyChanges: [], _perViewChange: [] });
    return NgForOf;
}());
```

## 🔬 Minimal Reproduction
**demo:** [demo.zip](https://github.com/angular/angular-cli/files/3211810/demo.zip)

1. `ng new demo --enableIvy`
2. add IE11 polyfills
```
import 'core-js/es6/symbol';
import 'core-js/es6/object';
import 'core-js/es6/function';
import 'core-js/es6/parse-int';
import 'core-js/es6/parse-float';
import 'core-js/es6/number';
import 'core-js/es6/math';
import 'core-js/es6/string';
import 'core-js/es6/date';
import 'core-js/es6/array';
import 'core-js/es6/regexp';
import 'core-js/es6/map';
import 'core-js/es6/weak-map';
import 'core-js/es6/set';
import 'core-js/es7/array';
import 'core-js/es6/reflect';
import 'core-js/es7/reflect';
import 'web-animations-js';
import 'zone.js/dist/zone';
```
3. set ` "angularCompilerOptions": { "enableIvy": true }` in `tsconfig.app.json`
4. set `"target": "es5"` in `tsconfig.json`
5. `ng serve` (or build)

## 🌍 Your Environment
<pre><code>
Angular CLI: 8.0.0-rc.4
Node: 10.15.0
OS: win32 x64
Angular: 8.0.0-rc.4
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.0-rc.4
@angular-devkit/build-angular     0.800.0-rc.4
@angular-devkit/build-optimizer   0.800.0-rc.4
@angular-devkit/build-webpack     0.800.0-rc.4
@angular-devkit/core              8.0.0-rc.4
@angular-devkit/schematics        8.0.0-rc.4
@ngtools/webpack                  8.0.0-rc.4
@schematics/angular               8.0.0-rc.4
@schematics/update                0.800.0-rc.4
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.30.0
</code></pre>

**Comment by alexzuza** [comment] 2019-05-23 18:15
Duplicate of https://github.com/angular/angular/issues/30569?

**Comment by devversion** [comment] 2019-05-23 20:59
Yeah can we please track this in the other issue. The other contains a reproduction that is less CLI specific and I put in my initial investigation results.

**Closed by devversion** 2019-05-23 20:59 UTC
Labels: comp: core & compiler, comp: ivy, freq1: low, severity3: broken, type: bug/fix
