### ISSUE TITLE
SW crash report from angular.io for #28114

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#43453] opened 2021-09-15 01:34 UTC
```
polyfills-es2017.cd037d4e948590a572fd.js:1 A preload for 'https://angular.io/generated/navigation.json' is found, but is not used because the request headers do not match.
g @ polyfills-es2017.cd037d4e948590a572fd.js:1
polyfills-es2017.cd037d4e948590a572fd.js:1 A preload for 'https://angular.io/generated/docs/index.json' is found, but is not used because the request headers do not match.
g @ polyfills-es2017.cd037d4e948590a572fd.js:1
angular.io/:1 The resource https://angular.io/generated/docs/index.json was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
angular.io/:1 The resource https://angular.io/generated/navigation.json was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
/src_app_custom-elements_code_code-example_module_ts-es2017.4e7815aa3ea3e030f805.js:1 Failed to load resource: the server responded with a status of 404 ()
main-es2017.3becb6153d70a53aff6b.js:1 ERROR Error: [DocViewer] Error preparing document 'api/core/testing/TestBed': ChunkLoadError: Loading chunk src_app_custom-elements_code_code-example_module_ts failed.
(error: https://angular.io/src_app_custom-elements_code_code-example_module_ts-es2017.4e7815aa3ea3e030f805.js)
    at Object.a.f.j (runtime-es2017.b65a6a9386f50f962040.js:1)
    at runtime-es2017.b65a6a9386f50f962040.js:1
    at Array.reduce (<anonymous>)
    at Function.a.e (runtime-es2017.b65a6a9386f50f962040.js:1)
    at loadChildren (main-es2017.3becb6153d70a53aff6b.js:1)
    at t.loadCustomElement (main-es2017.3becb6153d70a53aff6b.js:1)
    at main-es2017.3becb6153d70a53aff6b.js:1
    at Array.map (<anonymous>)
    at t.loadContainedCustomElements (main-es2017.3becb6153d70a53aff6b.js:1)
    at c.project (main-es2017.3becb6153d70a53aff6b.js:1)
    at o.selector (main-es2017.3becb6153d70a53aff6b.js:1)
    at o.error (main-es2017.3becb6153d70a53aff6b.js:1)
    at c._error (main-es2017.3becb6153d70a53aff6b.js:1)
    at c.error (main-es2017.3becb6153d70a53aff6b.js:1)
    at c._error (main-es2017.3becb6153d70a53aff6b.js:1)
    at c.error (main-es2017.3becb6153d70a53aff6b.js:1)
    at c._error (main-es2017.3becb6153d70a53aff6b.js:1)
    at c.error (main-es2017.3becb6153d70a53aff6b.js:1)
    at c.notifyError (main-es2017.3becb6153d70a53aff6b.js:1)
    at o._error (main-es2017.3becb6153d70a53aff6b.js:1)
ws @ main-es2017.3becb6153d70a53aff6b.js:1
main-es2017.3becb6153d70a53aff6b.js:1 
ServiceWorker: activated
/default-src_app_custom-elements_code_code_component_ts-src_app_custom-elements_code_code_module_ts-es2017.b3ca4e16c594ed2c57c6.js:1 Failed to load resource: the server responded with a status of 404 ()
main-es2017.3becb6153d70a53aff6b.js:1 
Cache: ngsw:/:db:control (2 entries)
  - https://angular.io/assignments: {"82a890ac-177f-4e1d-9d79-f1e8d59f5028":"2d759fe3b10c29d6a368f509de1cf98a43edbf88"}
  - https://angular.io/latest: {"latest":"66953c188387ca545794c7090e2e27d0d7c75393"}
main-es2017.3becb6153d70a53aff6b.js:1 
Cache: ngsw:/:2d759fe3b10c29d6a368f509de1cf98a43edbf88:assets:app-shell:cache (33 entries)
  - https://angular.io/assets/js/prettify.js
  - https://angular.io/dark-theme.css
  - https://angular.io/default-src_app_custom-elements_code_code_component_ts-src_app_custom-elements_code_code_module_ts-es2017.b3ca4e16c594ed2c57c6.js
  - https://angular.io/index.html
  - https://angular.io/light-theme.css
  - https://angular.io/main-es2017.3becb6153d70a53aff6b.js
  - https://angular.io/polyfills-es2017.cd037d4e948590a572fd.js
  - https://angular.io/pwa-manifest.json
  - https://angular.io/runtime-es2017.b65a6a9386f50f962040.js
  - https://angular.io/src_app_custom-elements_announcement-bar_announcement-bar_module_ts-es2017.9ea9bc0ecefab5835c4d.js
  - https://angular.io/src_app_custom-elements_api_api-list_module_ts-es2017.bd90c0062ee746cb058e.js
  - https://angular.io/src_app_custom-elements_code_code-example_module_ts-es2017.4e7815aa3ea3e030f805.js
  - https://angular.io/src_app_custom-elements_code_code-tabs_module_ts-es2017.218cc723e52bfef7212d.js
  - https://angular.io/src_app_custom-elements_contributor_contributor-list_module_ts-es2017.33f311c94849d0540bcc.js
  - https://angular.io/src_app_custom-elements_dist-tag_dist-tag_module_ts-es2017.ba5029bda8b76955cb4d.js
  - https://angular.io/src_app_custom-elements_events_events_module_ts-es2017.c11a4d38a3abb62f7315.js
  - https://angular.io/src_app_custom-elements_live-example_live-example_module_ts-es2017.44b9bef6f3374caf5a8a.js
  - https://angular.io/src_app_custom-elements_resource_resource-list_module_ts-es2017.799afc76af874b78a307.js
  - https://angular.io/src_app_custom-elements_search_file-not-found-search_module_ts-es2017.01258ffbcb6c352e4dc3.js
  - https://angular.io/src_app_custom-elements_toc_toc_module_ts-es2017.1337522d0bd53e657011.js
  - https://angular.io/src_app_search_search_worker_ts-es2017.ca6d8ccf626d66f0980e.js
  - https://angular.io/src_assets_js_prettify_js-es2017.d7ad5bf7f937932ed320.js
  - https://angular.io/styles.c376fe19f74dcb0d729c.css
  - https://fonts.gstatic.com/s/roboto/v27/KFOmCnqEu92Fr1Mu4mxKKTU1Kg.woff2
  - https://fonts.gstatic.com/s/materialicons/v95/flUhRq6tzZclQEJ-Vdg-IuiaDsNcIhQ8tQ.woff2
  - https://fonts.gstatic.com/s/roboto/v27/KFOlCnqEu92Fr1MmEU9fBBc4AMP6lQ.woff2
  - https://fonts.gstatic.com/s/roboto/v27/KFOlCnqEu92Fr1MmSU5fBBc4AMP6lQ.woff2
  - https://fonts.gstatic.com/s/roboto/v27/KFOmCnqEu92Fr1Me5g.woff
  - https://fonts.gstatic.com/s/robotomono/v13/L0x5DF4xlVMF-BfR8bXMIjhLq3-cXbKD.woff2
  - https://fonts.gstatic.com/s/materialicons/v97/flUhRq6tzZclQEJ-Vdg-IuiaDsNcIhQ8tQ.woff2
  - https://fonts.gstatic.com/s/materialicons/v98/flUhRq6tzZclQEJ-Vdg-IuiaDsNcIhQ8tQ.woff2
  - https://fonts.gstatic.com/s/robotomono/v13/L0xuDF4xlVMF-BfR8bXMIhJHg45mwgGEFl0_3vqPQA.woff
  - https://fonts.gstatic.com/s/materialicons/v99/flUhRq6tzZclQEJ-Vdg-IuiaDsNcIhQ8tQ.woff2
main-es2017.3becb6153d70a53aff6b.js:1 
Cache: ngsw:/:66953c188387ca545794c7090e2e27d0d7c75393:assets:app-shell:cache (33 entries)
  - https://angular.io/assets/js/prettify.js
  - https://angular.io/dark-theme.css
  - https://angular.io/default-src_app_custom-elements_code_code_component_ts-src_app_custom-elements_code_code_module_ts-es2017.b3ca4e16c594ed2c57c6.js
  - https://angular.io/index.html
  - https://angular.io/light-theme.css
  - https://angular.io/main-es2017.3becb6153d70a53aff6b.js
  - https://angular.io/polyfills-es2017.cd037d4e948590a572fd.js
  - https://angular.io/pwa-manifest.json
  - https://angular.io/runtime-es2017.b65a6a9386f50f962040.js
  - https://angular.io/src_app_custom-elements_announcement-bar_announcement-bar_module_ts-es2017.9ea9bc0ecefab5835c4d.js
  - https://angular.io/src_app_custom-elements_api_api-list_module_ts-es2017.bd90c0062ee746cb058e.js
  - https://angular.io/src_app_custom-elements_code_code-example_module_ts-es2017.4e7815aa3ea3e030f805.js
  - https://angular.io/src_app_custom-elements_code_code-tabs_module_ts-es2017.218cc723e52bfef7212d.js
  - https://angular.io/src_app_custom-elements_contributor_contributor-list_module_ts-es2017.33f311c94849d0540bcc.js
  - https://angular.io/src_app_custom-elements_dist-tag_dist-tag_module_ts-es2017.ba5029bda8b76955cb4d.js
  - https://angular.io/src_app_custom-elements_events_events_module_ts-es2017.c11a4d38a3abb62f7315.js
  - https://angular.io/src_app_custom-elements_live-example_live-example_module_ts-es2017.44b9bef6f3374caf5a8a.js
  - https://angular.io/src_app_custom-elements_resource_resource-list_module_ts-es2017.799afc76af874b78a307.js
  - https://angular.io/src_app_custom-elements_search_file-not-found-search_module_ts-es2017.01258ffbcb6c352e4dc3.js
  - https://angular.io/src_app_custom-elements_toc_toc_module_ts-es2017.1337522d0bd53e657011.js
  - https://angular.io/src_app_search_search_worker_ts-es2017.ca6d8ccf626d66f0980e.js
  - https://angular.io/src_assets_js_prettify_js-es2017.d7ad5bf7f937932ed320.js
  - https://angular.io/styles.c376fe19f74dcb0d729c.css
  - https://fonts.gstatic.com/s/roboto/v27/KFOmCnqEu92Fr1Mu4mxKKTU1Kg.woff2
  - https://fonts.gstatic.com/s/materialicons/v95/flUhRq6tzZclQEJ-Vdg-IuiaDsNcIhQ8tQ.woff2
  - https://fonts.gstatic.com/s/roboto/v27/KFOlCnqEu92Fr1MmEU9fBBc4AMP6lQ.woff2
  - https://fonts.gstatic.com/s/roboto/v27/KFOlCnqEu92Fr1MmSU5fBBc4AMP6lQ.woff2
  - https://fonts.gstatic.com/s/roboto/v27/KFOmCnqEu92Fr1Me5g.woff
  - https://fonts.gstatic.com/s/robotomono/v13/L0x5DF4xlVMF-BfR8bXMIjhLq3-cXbKD.woff2
  - https://fonts.gstatic.com/s/materialicons/v97/flUhRq6tzZclQEJ-Vdg-IuiaDsNcIhQ8tQ.woff2
  - https://fonts.gstatic.com/s/materialicons/v98/flUhRq6tzZclQEJ-Vdg-IuiaDsNcIhQ8tQ.woff2
  - https://fonts.gstatic.com/s/robotomono/v13/L0xuDF4xlVMF-BfR8bXMIhJHg45mwgGEFl0_3vqPQA.woff
  - https://fonts.gstatic.com/s/materialicons/v99/flUhRq6tzZclQEJ-Vdg-IuiaDsNcIhQ8tQ.woff2
main-es2017.3becb6153d70a53aff6b.js:1 
Cache: ngsw:/:db:2d759fe3b10c29d6a368f509de1cf98a43edbf88:assets:app-shell:meta (32 entries)
  - https://angular.io/https://angular.io/assets/js/prettify.js: {"ts":1630535341853,"used":false}
  - https://angular.io/https://angular.io/dark-theme.css: {"ts":1630535341866,"used":false}
  - https://angular.io/https://angular.io/default-src_app_custom-elements_code_code_component_ts-src_app_custom-elements_code_code_module_ts-es2017.b3ca4e16c594ed2c57c6.js: {"ts":1630535341879,"used":false}
  - https://angular.io/https://angular.io/light-theme.css: {"ts":1630535342003,"used":false}
  - https://angular.io/https://angular.io/main-es2017.3becb6153d70a53aff6b.js: {"ts":1630535342024,"used":false}
  - https://angular.io/https://angular.io/polyfills-es2017.cd037d4e948590a572fd.js: {"ts":1630535342042,"used":false}
  - https://angular.io/https://angular.io/pwa-manifest.json: {"ts":1630535342054,"used":false}
  - https://angular.io/https://angular.io/runtime-es2017.b65a6a9386f50f962040.js: {"ts":1630535342065,"used":false}
  - https://angular.io/https://angular.io/src_app_custom-elements_announcement-bar_announcement-bar_module_ts-es2017.9ea9bc0ecefab5835c4d.js: {"ts":1630535342075,"used":false}
  - https://angular.io/https://angular.io/src_app_custom-elements_api_api-list_module_ts-es2017.bd90c0062ee746cb058e.js: {"ts":1630535342085,"used":false}
  - https://angular.io/https://angular.io/src_app_custom-elements_code_code-example_module_ts-es2017.4e7815aa3ea3e030f805.js: {"ts":1630535342097,"used":false}
  - https://angular.io/https://angular.io/src_app_custom-elements_code_code-tabs_module_ts-es2017.218cc723e52bfef7212d.js: {"ts":1630535342112,"used":false}
  - https://angular.io/https://angular.io/src_app_custom-elements_contributor_contributor-list_module_ts-es2017.33f311c94849d0540bcc.js: {"ts":1630535342124,"used":false}
  - https://angular.io/https://angular.io/src_app_custom-elements_dist-tag_dist-tag_module_ts-es2017.ba5029bda8b76955cb4d.js: {"ts":1630535342134,"used":false}
  - https://angular.io/https://angular.io/src_app_custom-elements_events_events_module_ts-es2017.c11a4d38a3abb62f7315.js: {"ts":1630535342143,"used":false}
  - https://angular.io/https://angular.io/src_app_custom-elements_live-example_live-example_module_ts-es2017.44b9bef6f3374caf5a8a.js: {"ts":1630535342153,"used":false}
  - https://angular.io/https://angular.io/src_app_custom-elements_resource_resource-list_module_ts-es2017.799afc76af874b78a307.js: {"ts":1630535342162,"used":false}
  - https://angular.io/https://angular.io/src_app_custom-elements_search_file-not-found-search_module_ts-es2017.01258ffbcb6c352e4dc3.js: {"ts":1630535342170,"used":false}
  - https://angular.io/https://angular.io/src_app_custom-elements_toc_toc_module_ts-es2017.1337522d0bd53e657011.js: {"ts":1630535342180,"used":false}
  - https://angular.io/https://angular.io/src_app_search_search_worker_ts-es2017.ca6d8ccf626d66f0980e.js: {"ts":1630535342188,"used":false}
  - https://angular.io/https://angular.io/src_assets_js_prettify_js-es2017.d7ad5bf7f937932ed320.js: {"ts":1630535342196,"used":false}
  - https://angular.io/https://angular.io/styles.c376fe19f74dcb0d729c.css: {"ts":1630535342205,"used":false}
  - https://angular.io/https://fonts.gstatic.com/s/roboto/v27/KFOmCnqEu92Fr1Mu4mxKKTU1Kg.woff2: {"ts":1628109565484,"used":false}
  - https://angular.io/https://fonts.gstatic.com/s/materialicons/v95/flUhRq6tzZclQEJ-Vdg-IuiaDsNcIhQ8tQ.woff2: {"ts":1628109565714,"used":false}
  - https://angular.io/https://fonts.gstatic.com/s/roboto/v27/KFOlCnqEu92Fr1MmEU9fBBc4AMP6lQ.woff2: {"ts":1628109565716,"used":false}
  - https://angular.io/https://fonts.gstatic.com/s/roboto/v27/KFOlCnqEu92Fr1MmSU5fBBc4AMP6lQ.woff2: {"ts":1628109565718,"used":false}
  - https://angular.io/https://fonts.gstatic.com/s/roboto/v27/KFOmCnqEu92Fr1Me5g.woff: {"ts":1628109565857,"used":false}
  - https://angular.io/https://fonts.gstatic.com/s/robotomono/v13/L0x5DF4xlVMF-BfR8bXMIjhLq3-cXbKD.woff2: {"ts":1628109566265,"used":false}
  - https://angular.io/https://fonts.gstatic.com/s/materialicons/v97/flUhRq6tzZclQEJ-Vdg-IuiaDsNcIhQ8tQ.woff2: {"ts":1628543165476,"used":false}
  - https://angular.io/https://fonts.gstatic.com/s/materialicons/v98/flUhRq6tzZclQEJ-Vdg-IuiaDsNcIhQ8tQ.woff2: {"ts":1629425134892,"used":false}
  - https://angular.io/https://fonts.gstatic.com/s/robotomono/v13/L0xuDF4xlVMF-BfR8bXMIhJHg45mwgGEFl0_3vqPQA.woff: {"ts":1630478250522,"used":false}
  - https://angular.io/https://fonts.gstatic.com/s/materialicons/v99/flUhRq6tzZclQEJ-Vdg-IuiaDsNcIhQ8tQ.woff2: {"ts":1630624342950,"used":true}
main-es2017.3becb6153d70a53aff6b.js:1 
Cache: ngsw:/:db:66953c188387ca545794c7090e2e27d0d7c75393:assets:app-shell:meta (33 entries)
  - https://angular.io/https://angular.io/assets/js/prettify.js: {"ts":1630624350007,"used":false}
  - https://angular.io/https://angular.io/dark-theme.css: {"ts":1630624350028,"used":false}
  - https://angular.io/https://angular.io/default-src_app_custom-elements_code_code_component_ts-src_app_custom-elements_code_code_module_ts-es2017.b3ca4e16c594ed2c57c6.js: {"ts":1630624350059,"used":false}
  - https://angular.io/https://angular.io/index.html: {"ts":1630624350068,"used":false}
  - https://angular.io/https://angular.io/light-theme.css: {"ts":1630624350078,"used":false}
  - https://angular.io/https://angular.io/main-es2017.3becb6153d70a53aff6b.js: {"ts":1630624350096,"used":false}
  - https://angular.io/https://angular.io/polyfills-es2017.cd037d4e948590a572fd.js: {"ts":1630624350105,"used":false}
  - https://angular.io/https://angular.io/pwa-manifest.json: {"ts":1630624350111,"used":false}
  - https://angular.io/https://angular.io/runtime-es2017.b65a6a9386f50f962040.js: {"ts":1630624350117,"used":false}
  - https://angular.io/https://angular.io/src_app_custom-elements_announcement-bar_announcement-bar_module_ts-es2017.9ea9bc0ecefab5835c4d.js: {"ts":1630624350123,"used":false}
  - https://angular.io/https://angular.io/src_app_custom-elements_api_api-list_module_ts-es2017.bd90c0062ee746cb058e.js: {"ts":1630624350129,"used":false}
  - https://angular.io/https://angular.io/src_app_custom-elements_code_code-example_module_ts-es2017.4e7815aa3ea3e030f805.js: {"ts":1630624350136,"used":false}
  - https://angular.io/https://angular.io/src_app_custom-elements_code_code-tabs_module_ts-es2017.218cc723e52bfef7212d.js: {"ts":1630624350144,"used":false}
  - https://angular.io/https://angular.io/src_app_custom-elements_contributor_contributor-list_module_ts-es2017.33f311c94849d0540bcc.js: {"ts":1630624350151,"used":false}
  - https://angular.io/https://angular.io/src_app_custom-elements_dist-tag_dist-tag_module_ts-es2017.ba5029bda8b76955cb4d.js: {"ts":1630624350159,"used":false}
  - https://angular.io/https://angular.io/src_app_custom-elements_events_events_module_ts-es2017.c11a4d38a3abb62f7315.js: {"ts":1630624350166,"used":false}
  - https://angular.io/https://angular.io/src_app_custom-elements_live-example_live-example_module_ts-es2017.44b9bef6f3374caf5a8a.js: {"ts":1630624350173,"used":false}
  - https://angular.io/https://angular.io/src_app_custom-elements_resource_resource-list_module_ts-es2017.799afc76af874b78a307.js: {"ts":1630624350179,"used":false}
  - https://angular.io/https://angular.io/src_app_custom-elements_search_file-not-found-search_module_ts-es2017.01258ffbcb6c352e4dc3.js: {"ts":1630624350186,"used":false}
  - https://angular.io/https://angular.io/src_app_custom-elements_toc_toc_module_ts-es2017.1337522d0bd53e657011.js: {"ts":1630624350193,"used":false}
  - https://angular.io/https://angular.io/src_app_search_search_worker_ts-es2017.ca6d8ccf626d66f0980e.js: {"ts":1630624350206,"used":false}
  - https://angular.io/https://angular.io/src_assets_js_prettify_js-es2017.d7ad5bf7f937932ed320.js: {"ts":1630624350214,"used":false}
  - https://angular.io/https://angular.io/styles.c376fe19f74dcb0d729c.css: {"ts":1630624350224,"used":false}
  - https://angular.io/https://fonts.gstatic.com/s/roboto/v27/KFOmCnqEu92Fr1Mu4mxKKTU1Kg.woff2: {"ts":1628109565484,"used":false}
  - https://angular.io/https://fonts.gstatic.com/s/materialicons/v95/flUhRq6tzZclQEJ-Vdg-IuiaDsNcIhQ8tQ.woff2: {"ts":1628109565714,"used":false}
  - https://angular.io/https://fonts.gstatic.com/s/roboto/v27/KFOlCnqEu92Fr1MmEU9fBBc4AMP6lQ.woff2: {"ts":1628109565716,"used":false}
  - https://angular.io/https://fonts.gstatic.com/s/roboto/v27/KFOlCnqEu92Fr1MmSU5fBBc4AMP6lQ.woff2: {"ts":1628109565718,"used":false}
  - https://angular.io/https://fonts.gstatic.com/s/roboto/v27/KFOmCnqEu92Fr1Me5g.woff: {"ts":1628109565857,"used":false}
  - https://angular.io/https://fonts.gstatic.com/s/robotomono/v13/L0x5DF4xlVMF-BfR8bXMIjhLq3-cXbKD.woff2: {"ts":1628109566265,"used":false}
  - https://angular.io/https://fonts.gstatic.com/s/materialicons/v97/flUhRq6tzZclQEJ-Vdg-IuiaDsNcIhQ8tQ.woff2: {"ts":1628543165476,"used":false}
  - https://angular.io/https://fonts.gstatic.com/s/materialicons/v98/flUhRq6tzZclQEJ-Vdg-IuiaDsNcIhQ8tQ.woff2: {"ts":1629425134892,"used":false}
  - https://angular.io/https://fonts.gstatic.com/s/robotomono/v13/L0xuDF4xlVMF-BfR8bXMIhJHg45mwgGEFl0_3vqPQA.woff: {"ts":1630478250522,"used":false}
  - https://angular.io/https://fonts.gstatic.com/s/materialicons/v99/flUhRq6tzZclQEJ-Vdg-IuiaDsNcIhQ8tQ.woff2: {"ts":1630624342950,"used":false}
main-es2017.3becb6153d70a53aff6b.js:1 
----------
main-es2017.3becb6153d70a53aff6b.js:1 NGSW Debug Info:

Driver version: 12.1.1
Driver state: EXISTING_CLIENTS_ONLY (Degraded due to: Hash mismatch (cacheBustedFetchFromNetwork): https://angular.io/generated/docs/api/core/testing/t_estb_ed.json: expected 6ed78188da3b90ed0272f6bcaddab6ab606be007, got b82a40f8b8648ca1b2de2913019f7c6e3763777a (after cache busting)
Error: Hash mismatch (cacheBustedFetchFromNetwork): https://angular.io/generated/docs/api/core/testing/t_estb_ed.json: expected 6ed78188da3b90ed0272f6bcaddab6ab606be007, got b82a40f8b8648ca1b2de2913019f7c6e3763777a (after cache busting)
    at LazyAssetGroup.<anonymous> (https://angular.io/ngsw-worker.js:818:39)
    at Generator.next (<anonymous>)
    at fulfilled (https://angular.io/ngsw-worker.js:22:32))
Latest manifest hash: 66953c188387ca545794c7090e2e27d0d7c75393
Last update check: never

=== Version 2d759fe3b10c29d6a368f509de1cf98a43edbf88 ===

Clients: 82a890ac-177f-4e1d-9d79-f1e8d59f5028

=== Version 66953c188387ca545794c7090e2e27d0d7c75393 ===

Clients: 

=== Idle Task Queue ===
Last update tick: 159u
Last update run: never
Task queue:
 * init post-load (update)
 * init post-load (cleanup)
 * initialization(2d759fe3b10c29d6a368f509de1cf98a43edbf88)
 * initialization(66953c188387ca545794c7090e2e27d0d7c75393)
 * check-updates-on-navigation

Debug log:



main-es2017.3becb6153d70a53aff6b.js:1 
----------
If you see this error, please report an issue at https://github.com/angular/angular/issues/new?template=3-docs-bug.md including the above logs.
(anonymous) @ main-es2017.3becb6153d70a53aff6b.js:1
```
<img width="1392" alt="Screen Shot 2021-09-14 at 6 33 58 PM" src="https://user-images.githubusercontent.com/216296/133356078-b6a55377-0ace-43c1-b62e-45aa834ba528.png">
<img width="1392" alt="Screen Shot 2021-09-14 at 6 34 08 PM" src="https://user-images.githubusercontent.com/216296/133356086-2ef2aca1-37aa-4a43-b1d6-26a192038473.png">
<img width="1392" alt="Screen Shot 2021-09-14 at 6 34 17 PM" src="https://user-images.githubusercontent.com/216296/133356099-3a7c5dea-4b34-46f8-9ecd-1de4785a4a76.png">

**Comment by gkalpak** [comment] 2021-09-20 14:54
Closing this to centralize tracking of the info in one place.
The problem is being tracked in #28114 (and there is a reference to this issue in https://github.com/angular/angular/issues/28114#issuecomment-919629434) and all captured debug info is tracked in #41117 (with a reference to this issue in https://github.com/angular/angular/issues/41117#issuecomment-920072430).

**Closed by gkalpak** 2021-09-20 14:54 UTC
Labels: type: bug/fix, comp: docs-infra, P2
