### ISSUE TITLE
[Ivy Mode] build error with ngx-permissions

### ISSUE THREAD

**Issue by StickNitro** [angular/angular#30781] opened 2019-05-31 13:43 UTC
# 🐞 bug report

I am getting the following error when running `ng build --prod` with `enableIvy: true`

ERROR in ENOENT: no such file or directory, open '/Users/neilstevens/repositories/@capp/CAPP.AssessmentCentre.Admin/node_modules/ngx-permissions/ngx-permissions.js'

### Is this a regression?
No

### Description

 A clear and concise description of the problem...
I have a project that uses `ngx-permissions` and when enabling Ivy on this project the build breaks with the error message detailed above

## 🔬 Minimal Reproduction

[Angular8-IvyMode Repo](https://github.com/StickNitro/Angular8-IvyMode)

Link to repo above
* Clone the repo
* Run `npm i` or `yarn` to install dependencies
* Run `ng build --prod`

## 🔥 Exception or Error
<pre><code>

ERROR in ENOENT: no such file or directory, open '/Users/neilstevens/repositories/@capp/CAPP.AssessmentCentre.Admin/node_modules/ngx-permissions/ngx-permissions.js'

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 8.0.1
Node: 12.1.0
OS: darwin x64
Angular: 8.0.0
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.1
@angular-devkit/build-angular     0.800.1
@angular-devkit/build-optimizer   0.800.1
@angular-devkit/build-webpack     0.800.1
@angular-devkit/core              8.0.1
@angular-devkit/schematics        8.0.1
@angular/cli                      8.0.1
@ngtools/webpack                  8.0.1
@schematics/angular               8.0.1
@schematics/update                0.800.1
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.30.0

</code></pre>

**Comment by JoostK** [comment] 2019-05-31 18:05
This is caused by an issue with [`ngx-permissions`'s `package.json` file](https://unpkg.com/ngx-permissions@6.0.6/package.json). Its `main` property points to `ngx-permissions.js` but that file does not exist.

Work is being done in #30591 that allows overriding such faulty details. Could you please report this issue with `ngx-permissions`'s maintainer, so they can get it fixed at the root?

**Comment by StickNitro** [comment] 2019-06-03 08:55
Looks like someone beat me to it :)

link to issue in ngx-permissions [#106](https://github.com/AlexKhymenko/ngx-permissions/issues/106)

**Comment by JoostK** [comment] 2019-06-19 22:07
I will close this issue as the cause has been fixed upstream and PR #30591 enables working around such issues in the future. Thanks for trying Ivy!

**Closed by JoostK** 2019-06-19 22:07 UTC
Labels: comp: ivy, freq2: medium, severity2: inconvenient, type: bug/fix
