### ISSUE TITLE
Named routes

### ISSUE THREAD

**Issue by Saeed-Pooyanfar** [angular/angular#29890] opened 2019-04-14 09:22 UTC
Oh hi there! 😄 

I'm a laravel (php) developer and new to angular ...
I read the docs about routes and one thing i really missed is named routes!
In laravel we can give a name to each route and get full path of the route with `route` helper function in views
If we change the path for the route still the correct path shows in views, because the route name refers to the route path!
Have we something like that in angular? and if no please add this feature!

As the alternative solution i was thinking about write a custom route service and
Inject it to all components but it seems to be a dirty solution, isn't it? :)

Thanks!

**Comment by Airblader** [comment] 2019-04-14 09:58
This would be incompatible with lazy loading as determining the route for a given name would require the module to be loaded already.

As for doing this within a module, you can add a `data: { name: string }` kind of property to your routes and create a service as you mentioned which does this (in fact, you could even build a library out of this). You can inject the `ROUTES` token to get the routes configuration in which you find the data block.

**Comment by Airblader** [comment] 2019-04-14 11:04
Also duplicate of #13416

**Comment by JoostK** [comment] 2019-04-14 11:30
Thanks @Airblader. I will go ahead and close this as this issue is non-actionable because of the lazy route constraints.

**Closed by JoostK** 2019-04-14 11:30 UTC

**Comment by Saeed-Pooyanfar** [comment] 2019-04-15 01:14
Thanks @Airblader 
https://www.npmjs.com/package/named-routes-angular
I will create a github repo for the source soon ^_^

**Comment by Saeed-Pooyanfar** [comment] 2019-04-15 12:01
The source:
https://github.com/Saeed-Pooyanfar/NamedRoutesAngular

**Comment by Saeed-Pooyanfar** [comment] 2019-04-16 09:59
Hi @Airblader 
[The lib](https://github.com/Saeed-Pooyanfar/NamedRoutesAngular) that i wrote for named routes,
works perfectly with "ng serve" command and compile with 0 error, but if i want to build it with:
"ng build --prod" command i get "Function calls are not supported in decorators but 'routerModule' was called" error!
I google it but not found any solution for this, can you help me?

**Comment by Airblader** [comment] 2019-04-16 10:09
You need to get rid of your custom `group` function stuff. Just let the user add the data attribute to the routes on their own. You can provide like a symbol they can use.

```
export const NAMED_ROUTE = new Symbol('NAMED_ROUTE');

// …

const routes: Routes = [
    {
        path: "heroes/:heroId/edit",
        component: HeroEditComponent,
        data: {
            [NAMED_ROUTE]: "heroes.edit",
        },
    },
];
```

This is really general AoT stuff, though, so it'd better if you asked such questions on StackOverflow.

**Comment by Saeed-Pooyanfar** [comment] 2019-04-16 10:45
@Airblader Thanks, so i can't write a lib that simulate laravel `Route::group()` in angular!
Also named routes idea is useless with this conditions :(

**Comment by Airblader** [comment] 2019-04-16 11:13
> Also named routes idea is useless with this conditions :(

What exactly are you losing that makes it useless? You can still let the user define "partial" names and when you look up something like `heroes.edit` you parse the tree.

**Comment by Saeed-Pooyanfar** [comment] 2019-04-16 12:30
> > Also named routes idea is useless with this conditions :(
> 
> What exactly are you losing that makes it useless? You can still let the user define "partial" names and when you look up something like `heroes.edit` you parse the tree.
I want route group feature like laravel in angular, imagine i have lots of routes with `path_prefix1_`
If one day i decide change it to `path_prefix2_` i have to manually modify all routes path which is so bad ( as i'm lazy :D ), this scenario is also true for routes name
Let me show you an example from laravel routes and my purpose from named routes:
```php
...
Route::prefix('admin')->name('admin.')->group(function() {
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');
    Route::get('user', 'UserController@index')->name('user.index');
    ....
    ....
});
...
```
In view:
```php
<a href="{{ route('admin.dashboard') }}">Admin dashboard</a>
<a href="{{ route('admin.user.index') }}">Users list</a>
```
One day i decide modify prefix for `admin.*` routes, all things that i have to do:
```php
...
Route::prefix('VERY_LONG_TOKEN_admin')->name('admin.')->group(function() {
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');
    Route::get('user', 'UserController@index')->name('user.index');
    ....
    ....
});
...
```
and nothing else!

**Comment by Airblader** [comment] 2019-04-17 11:46
You can still do this with the approach that I mentioned, but since you deleted the repository again already anyway this is a moot point.

**Comment by Saeed-Pooyanfar** [comment] 2019-04-17 12:24
Hi @Airblader 
I uploaded [the repo](https://github.com/Saeed-Pooyanfar/NamedRoutesAngular) again,
I have no idea how you can do this ...

**Comment by Saeed-Pooyanfar** [comment] 2019-04-17 13:50
> You can still do this with the approach that I mentioned, but since you deleted the repository again already anyway this is a moot point.

You just defined static path, for example if i have:
```typescript
...
const routes: Routes = [
    {
        path: "hero/:id/action1",
        component: HeroAction1Component,
        data: {
            name: "hero.action1",
        }
    },
    {
        path: "hero/:id/action2",
        component: HeroAction2Component,
        data: {
            name: "hero.action2",
        }
    },
    {
        path: "hero/:id/action3",
        component: HeroAction3Component,
        data: {
            name: "hero.action3",
        }
    },
    ...
];
...
```
and want to add a prefix to paths, what can i do? manually modify all paths?

**Comment by Airblader** [comment] 2019-04-17 14:38
You should just make use of the hierarchy the Angular router gives you:

```
const routes: Routes = [
    {
        path: "hero/:id",
        data: { name: "hero" },
        children: [
            {
                path: "action1",
                data: { name: "action1" },
                component: HeroAction1Component,
            },
        ],
    },
];
```

Now when the user uses `[routerLink]="'hero.action1' | route: hero.id"`, you walk through the routes to figure out the correct URL.

An interesting question is if and whether this should allow "skips" in between the tree without a route name set, but this comes down to a design decision in the library.

**Comment by Saeed-Pooyanfar** [comment] 2019-04-24 17:59
@Airblader 
Thanks, i updated [my lib](https://github.com/Saeed-Pooyanfar/NamedRoutesAngular) !!
I had to review tree DFS walk for myself for this :))
