### ISSUE TITLE
Routing not working when IF change HTML route

### ISSUE THREAD

**Issue by MrMime** [angular/angular#31521] opened 2019-07-12 07:48 UTC
# 🐞 bug report

I reproduced the bug here:

### Description

As you can see from the code, there are TWO router-outlet.
One in app.component.html IF NOT LOGGED.
One in layout component that is loaded IF LOGGED.

Seems like Angular is not able to understand the two router are mutually exclusive so when I log in, the router system still trigger the first one in app.component.
If I refresh the page, so the "not logged html code" is not loaded, the router-outlet inside the layout is correctly triggered.

## 🔬 Minimal Reproduction

[CODE](https://stackblitz.com/edit/routerafterloginbug)

Use any string to login. Its fake.
After logging, try to click on link or use the menu in sidenav.
As you can see, the URL of the page will change but the component is not loaded.

## 🌍  Your Environment

**Angular Version: 7.2.14**
<pre><code>
Angular CLI: 7.3.8
Node: 11.15.0
OS: linux x64
Angular: 7.2.14
... common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.8
@angular-devkit/build-angular     0.13.8
@angular-devkit/build-optimizer   0.13.8
@angular-devkit/build-webpack     0.13.8
@angular-devkit/core              7.3.8
@angular-devkit/schematics        7.3.8
@angular/animations               7.2.15
@angular/cdk                      7.3.7
@angular/cli                      7.3.8
@angular/flex-layout              7.0.0-beta.23
@angular/material                 7.3.7
@ngtools/webpack                  7.3.8
@schematics/angular               7.3.8
@schematics/update                0.13.8
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.29.0

</code></pre>

**Comment by santoshyadav198613** [comment] 2019-07-15 06:09
Hi @MrMime ,

I tried to check your code, and there is nothing wrong in Angular Router. 

You can refer to https://github.com/santoshyadav198613/June-LIPS-Angular repo where I have used the same concept.

For login rely on Guards.

**Comment by MrMime** [comment] 2019-07-15 06:52
Hi @santoshyadav198613 
In my code after login, if you press the Locations Links, the URL change but Location Component is not loaded. This because Angular still trigger the original router-outlet in !logged if inside app.component.html and not the one in Layout component.

**Comment by santoshyadav198613** [comment] 2019-07-15 06:57
When you work with routing angular will always find the router-outlet and append our data after the first router-outlet.

In you case you want to nest second router-outlet, there are 2 ways by using children or use named routes https://angular.io/guide/router#displaying-multiple-routes-in-named-outlets.

**Comment by ankurshah32** [comment] 2019-07-16 11:31
Hi 

I am also facing this kind of error please have a look at the updated code. 
[](https://stackblitz.com/edit/routerafterloginbug-zztqzn)
I have created the child routes in page folder

Observation:
if you are reloading the below url in stack-biltz routing works.

> https://routerafterloginbug-zztqzn.stackblitz.io/

but when come from login page URL changes to this

> https://routerafterloginbug-zztqzn.stackblitz.io/locations

but UI did not change

Can you please let me know where i am going wrong?

**Comment by alxhub** [comment] 2019-08-15 22:50
Hi @ankurshah32,

There's a couple problems in your example there.

1) `PageRoutingModule` is imported both in `PageModule` (which is lazily loaded) and in `AppRoutingModule`. This defines two routes instead of one.
2) `PageRoutingModule` defines its route with `path: 'locations'`. Since it's lazily loaded by `PageModule` under the root path `locations`, this really defines the route to be `locations/locations`. `PageRoutingModule` should use `path: ''` since it's already lazily loaded under `locations`.
3) `PageModule` lists `LocationManagerComponent` in its `imports`, which is not valid since it's a component, not an `NgModule`.
4) `LocationManagerComponent` is in the `declarations` of both `PageModule` and `AppModule`, which is not valid. If it's meant to be lazily loaded, it should just be in `PageModule`.

I stopped there, but basically these issues all prevent the app from working properly. If you look in the stackblitz console while navigating in the app, you'll see Angular warning you about these problems.

I'm going to close this issue as it's not a bug on our side, but feel free to continue discussion here.

**Closed by alxhub** 2019-08-15 22:50 UTC
Labels: comp: router
