### ISSUE TITLE
Provide a way to access error context details in Custom Error Handler

### ISSUE THREAD

**Issue by akashsolanki** [angular/angular#38933] opened 2020-09-22 05:50 UTC
# 🚀 feature request

### Relevant Package

This feature request is for @angular/core

### Description
 Angular should provide a way to get error details like source, lineno, colno etc that we get using window onerror event handler -

https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onerror

`window.onerror = function(message, source, lineno, colno, error) { ... };`

The current error handling mechanism does not provide complete error details. Also, [this document](https://angular.io/api/core/ErrorHandler) mentions the error type as any, it should instead be a proper interface explaining what properties are available in error object -

`class ErrorHandler {
  handleError(error: any): void
}`

**Comment by petebacondarwin** [comment] 2020-09-22 06:57
It is worth noting that the `error.stack` property usually contains information about where the error was thrown: https://stackblitz.com/edit/ivy-zm8e6f?devtoolsheight=33&file=src/app/app.module.ts

**Comment by pkozlowski-opensource** [comment] 2021-07-20 13:39
This feature request sounds _very_ similar to the existing #27752 - both are about extending contextual info for a given error. I'm going to merge those 2 issues into #27752 so we can debate the best mechanism in one place.

Closing as a duplicate of #27752

**Closed by pkozlowski-opensource** 2021-07-20 13:39 UTC
Labels: comp: core, core: error handling, feature, insufficient votes, votes required
