### ISSUE TITLE
Generic pipe for use a component method into component template

### ISSUE THREAD

**Issue by nigrosimone** [angular/angular#54240] opened 2024-02-04 06:49 UTC
### Which @angular/* package(s) are relevant/related to the feature request?

common

### Description

Sometime there is a need to use a component method into component template. Angular best practice says do not use method into html temlate, eg. `{{ myMethod(2) }}`. With a `GenericPipe` you can use all your public component methods as pure pipe with the component scope (`this`), eg: `{{ 2 | generic: myMethod }}`.

### Proposed solution

see https://github.com/angular/angular/pull/54242

Demo usage:

```ts
import { Component, GenericPipe } from '@angular/core';

interface User {
  name: string;
  age: number;
}

@Component({
  selector: 'my-app',
  standalone: true,
  imports: [GenericPipe, FormsModule],
  template: `
  <input type="search" [(ngModel)]="searchTerm" placeholder="Enter name" >
  <ul>
    <li *ngFor="let user of users | generic: search:searchTerm">{{user.name}}</li>
  </ul>
  `,
})
export class AppComponent {
  users: User[] = [
    { name: 'foo', age: 20 },
    { name: 'bar', age: 20 },
    { name: 'baz', age: 20 },
  ];

  searchTerm = '';

  search(users: User[], searchTerm: string): User[] {
    if (!users || !searchTerm) {
      return users;
    }
    return users.filter(
      (user) => user.name.toLowerCase().indexOf(searchTerm.toLowerCase()) !== -1
    );
  }
}
```

I have also published as NPM library https://www.npmjs.com/package/ng-generic-pipe

**Comment by JeanMeche** [comment] 2024-02-04 11:08
About methods in template, I don't think we should make it an obsolute. Have a look at [this article](https://justangular.com/blog/its-ok-to-use-function-calls-in-angular-templates) (cc @eneajaho).

**Comment by JeanMeche** [comment] 2024-02-04 11:27
Also I'm closing this as a dupe of #20419

**Closed by JeanMeche** 2024-02-04 11:27 UTC
