### ISSUE TITLE
Binding required attribute always applies the required validator

### ISSUE THREAD

**Issue by LunicLynx** [angular/angular#10094] opened 2016-07-15 16:38 UTC
**I'm submitting a ...**  (check one with "x")
```
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When binding the required attribute on an input tag, angular2 applies the required validator through the RequiredValidator directive even if the supplied expression evaluates to false.

**Expected/desired behavior**

The validator is not added or checks the supplied expression before validation.

**Reproduction of the problem**
```
import { Component } from '@angular/core';

@Component({
    selector: 'demo-bug',
    template: `
      <input type="text" [(ngModel)]="value" [required]="isRequired" #spy>
      <br>
      {{spy.className}}
    `
})
export class BugComponent {
    value: string;
    isRequired = false;
    constructor() { }
}
```

http://plnkr.co/edit/os4Y1lA2P1wlbpq8ThNt

**What is the expected behavior?**

ng-invalid is not applied

**What is the motivation / use case for changing the behavior?**

Correct behavior

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** [all] 
 
* **Language:** [all]

**Comment by harangue** [comment] 2016-07-15 22:42
This is intended behavior.

https://www.w3.org/TR/html5/infrastructure.html#boolean-attribute
> The values "true" and "false" are not allowed on boolean attributes. To represent a false value, the attribute has to be omitted altogether.

Instead, use `attr`

```
<my-component [attr.required]="isRequired"></my-component>
```

**Comment by nosachamos** [comment] 2016-07-16 06:30
Yes, I checked this out and [attr.required] works as intended. I believe this one can be closed.

**Comment by LunicLynx** [comment] 2016-07-16 10:54
This is not obvious, also i still think the behavior is incorrect. 
Required is a property on the input element, and so it is allowed to make my suggested binding to it:

https://angular.io/docs/ts/latest/guide/template-syntax.html#other-bindings

I could also set the code on the input element without using a directive, and it would do what i expect.
I expect: That ng-invalid does not get applied, which is a result of angular interepreting `<input ... required>` as the same as `<input ... [required]="...">`, which is not the same because the `HTMLInputElement` does have a property `required`[1].

I updated the plunker:
http://plnkr.co/edit/os4Y1lA2P1wlbpq8ThNt?p=preview

As you can see, non of the three actually do the right thing.
Explanation: The blue bar on the right represent the presence of the required attribute on the element. Green and red the presence of either ng-valid or ng-invalid respectively.

I could probably use sour solution as a workround because i don't really care after i set the initial state, but i will stress the point that i think this is a bug and should behave differently. Especially because this usage is encourage by the docs for other properties like hidden [2]. Also this does only happen because angular defines a directive for the selector `[required]` [3].
Maybe anuglar's selector syntax should allow for not applying directives when there is a binding assigned to them.

Some info on my use case and why this is happening for me. I try to create a dynamic form by using `FormControl`. I can ad the required validator to `FormControl` but this does not apply the required attribute on the input element. So i tried binding it the described way, which adds the required validator implicitly to the `FormControl` no matter what, because of the directive [3]. 

Hope this explains it in more detail.

[1] https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement
[2] https://angular.io/docs/ts/latest/guide/forms.html (Section: "Show and Hide Validation Error messages")
[3] https://github.com/angular/angular/blob/master/modules/%40angular/forms/src/directives/validators.ts#L59

**Comment by zoechi** [comment] 2016-07-17 14:41
Looks like a dup of #7393

**Comment by LunicLynx** [comment] 2016-07-19 09:04
@zoechi related yes, duplicate not quite

**Comment by MarkPerryBV** [comment] 2016-07-27 10:10
I don't think this one is fixed.

I have use case where the user can optionally mark a form field as "not required". To support this I want to conditionally apply the [required] control validator and DOM attribute.

`<input type="text" [(ngModel)]="value" [required]="isRequired" #spy>`

When I set isRequired to false then the control is still invalid which in turn makes the whole form invalid.

https://plnkr.co/edit/K7cX2ZOJb4GI4EXUeQHC?p=preview

**Comment by kara** [comment] 2016-08-29 20:25
Should have been fixed by https://github.com/angular/angular/pull/11116.

**Closed by kara** 2016-08-29 20:25 UTC
Labels: comp: forms

**Comment by kedar9444** [comment] 2018-01-08 14:47
@MarkPerryBV : have you found any solution for it? :(

**Comment by MarkPerryBV** [comment] 2018-01-08 15:41
@kedar9444 I wouldn't be doing that dude, you will have other issues. Just upgrade your version of @angular as Kara suggests. Also I no longer the "template forms" and have transitioned to the "reactive forms" model which suits my needs a lot better.
