### ISSUE TITLE
Documentation broken after every major update of Angular

### ISSUE THREAD

**Issue by Akxe** [angular/angular#35416] opened 2020-02-13 11:21 UTC
# 📚 Docs or angular.io bug report

### Description

When Angular upgraded from 7 to 8 and 8 to 9. The documentation crashed, didn't load properly, and didn't react to links. After a refresh, it works till the next major update. 

### What's the affected URL?**
All site

### Reproduction Steps**
1. Open documentation
2. Wait till a major release
3. Open documentation
  * Now it will produce an error

### Expected vs Actual Behavior**

Angular crushed, the page did not load any content and is not responding.

## 📷Screenshot
Don't have it, you can easily imagine.

## 🔥 Exception or Error
I am sorry I always forget to open the console beforehand... :/

### Browser info
Chrome 73? & 80.

### Anything else relevant?
This should be addressed. It looks very bad on Angular's side, also could create a nice example as what happened. I suppose it is some PWA caching.

**Comment by gkalpak** [comment] 2020-02-13 19:47
This looks like a duplicate of #28114. We have pushed some fixes to latest v8 and v9 that may have fixed the issue.

The fix was deployed to https://next.angular.io/, but not to https://angular.io/ before the v9.0.0 release. So, hopefully things are going to be fine for v10 :grin: 🙏

(Please, let us know if you run into more issues like this. In the meantime, let's track this in #28114.)

**Closed by gkalpak** 2020-02-13 19:47 UTC
Labels: comp: docs-infra
