### ISSUE TITLE
Generic Providers

### ISSUE THREAD

**Issue by AlexAegis** [angular/angular#37264] opened 2020-05-24 01:50 UTC
Provider types and interfaces are currently use `any` everywhere.

These provider types should be generic with a default of `any` instead, to allow us to make the providers more strict and let TypeScript infer what I should provide.

**Comment by kara** [comment] 2020-05-30 00:08
Looks like a dupe of https://github.com/angular/angular/issues/33883, which discusses how we can tighten up provider types. Closing in favor of the earlier issue.

**Closed by kara** 2020-05-30 00:08 UTC
Labels: comp: core, core: di, cross-cutting: types
