### ISSUE TITLE
Can't inject HttpClient in external library for JIT

### ISSUE THREAD

**Issue by mderoche** [angular/angular#21426] opened 2018-01-09 20:45 UTC
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior
When I try to use `HttpClient` in an external library, I get a `StaticInjectorError` error in my application.

I have an external library that imports `HttpClientModule`, and uses `HttpClient` in a service.  An application then imports that library, and tries to use that library service.  This results in a browser error when the application is run with `ng serve`:

**In Angular 5.1.3:**

> AppComponent_Host.ngfactory.js? [sm]:1 ERROR Error:
>   StaticInjectorError[InjectionToken DocumentToken]:   
>   StaticInjectorError[InjectionToken DocumentToken]: 
>      NullInjectorError: No provider for InjectionToken DocumentToken!
>      at _NullInjector.get (core.js:993)
>      at resolveToken (core.js:1281)
>      at tryResolveToken (core.js:1223)
>      at StaticInjector.get (core.js:1094)
>      at resolveToken (core.js:1281)
>      at tryResolveToken (core.js:1223)
>      at StaticInjector.get (core.js:1094)
>      at resolveNgModuleDep (core.js:10878)
>      at _createClass (core.js:10919)
>      at _createProviderInstance$1 (core.js:10889)

**In Angular 5.2.0-rc.0**: (Slightly more descriptive, but still cryptic)

> ERROR Error: StaticInjectorError(AppModule)[HttpXsrfTokenExtractor ->
> InjectionToken DocumentToken]:    StaticInjectorError(Platform:
> core)[HttpXsrfTokenExtractor -> InjectionToken DocumentToken]: 
>     NullInjectorError: No provider for InjectionToken DocumentToken!
>     at _NullInjector.get (core.js:994)
>     at resolveToken (core.js:1292)
>     at tryResolveToken (core.js:1234)
>     at StaticInjector.get (core.js:1102)
>     at resolveToken (core.js:1292)
>     at tryResolveToken (core.js:1234)
>     at StaticInjector.get (core.js:1102)
>     at resolveNgModuleDep (core.js:10836)
>     at _createClass (core.js:10877)
>     at _createProviderInstance$1 (core.js:10847)

The compilations for the app and library work for AoT and JIT.  If I serve the app with `ng serve --aot`, that also works fine.  If I use HttpModule instead of HttpClientModule, then it also works fine.  The issue seems to be with the combination of JIT and HttpClientModule:

| |HttpClientModule|HttpClient|
|---|---|---|
|JIT|Error|Works|
|AoT|Works|Works|

I looked in the generated UMD file, and added some logging.  It correctly grabs `ng.common.http`, and has all of the members (e.g. `HttpClient`, `HttpClientModule`).

## Expected behavior
This may be some issue inside HttpClientModule.  But even if it's something I'm doing wrong, then I would definitely like to see a more understandable error message.

## Minimal reproduction of the problem with instructions
I reproduced this with a blank `@angular/cli` application, and a blank sample library generated by [generator-angular2-library](https://github.com/jvandemo/generator-angular2-library).  (I've reproduced this with 4 separate library seeds, but this is the simplest to show.)

Apart from generating these projects, _the only changes I made_ are....

To the **application**:
- Imported `SampleModule`, and `HttpClientModule`
- Injected `SampleService` in `app.component.ts`

To the **library**:
- Imported `HttpClientModule`
- Injected `HttpClient` in `SampleService`
- Added `@angular/http/common` to the rollup externals and globals

GitHub repos to clone and test with:

- **Library:** https://github.com/mderoche/bug-httpclient-lib
- **App:** https://github.com/mderoche/bug-httpclient-app

1. npm install in library and app
2. npm run build in library
3. npm link the dist in library
4. npm link the library in app
5. ng serve the app

## What is the motivation / use case for changing the behavior?
I'd like to create a library for my application that handles all of my HTTP calls (API wrapper).

## Environment

<pre><code>
Angular version: 5.1.3 and 5.2.0-rc.0

Browser:
- [63.0.3239.84] Chrome (desktop) version XX
 
For Tooling issues:
- Node version: v8.9.1
- Platform:  Mac
</code></pre>

**Comment by mlc-mlapis** [comment] 2018-01-09 21:26
@mderoche ... `HttpClientModule` shoudn't be imported ... just `HttpClient` injected through DI ... so there is still just one of its instance in an app.

**Comment by happycollision** [comment] 2018-01-11 15:49
@mlc-mlapis Any chance you'd be willing to expand on that a bit? Or possibly if you know of a project somewhere that packages a module that makes use of HttpClient? I am trying to do this in a project I am working on as well and I just cannot figure it out.

I have to move on for now, but if I do find the proper way to do this, I'll post the method here, @mderoche .

**Comment by happycollision** [comment] 2018-01-11 17:23
__Update__
It's always the dumbest things...

In my particular case, my code wasn't working for a *totally* unrelated reason. In your case, @mderoche, you ought to be able to just remove [this line](https://github.com/mderoche/bug-httpclient-lib/blob/04217d3d1094dd143fa00739833d12475902ffc6/src/index.ts#L17) from your module. (May as well ditch the accompanying import at the top of the file, too.)

The reason mine wasn't working is because I nested the WHOLE library in my project so that it would be easy to make changes to get them working before I actually published it as a library. Not a problem *unless* you `npm install` inside the library as well. This meant that I actually did have multiple versions of the HttpClient bouncing around my project.

I removed the `node_modules` folder of my nested library, and no problem.

If this is confusing, @mderoche, please feel free to ask me questions.

**Comment by mderoche** [comment] 2018-01-13 20:19
Unfortunately, that does not work for me.  Removing the `HttpClientModule` import from the library results in an injector error for `HttpClient`:

```
AppComponent_Host.ngfactory.js? [sm]:1 ERROR Error: StaticInjectorError[HttpClient]: 
  StaticInjectorError[HttpClient]: 
    NullInjectorError: No provider for HttpClient!
```

**Comment by mlc-mlapis** [comment] 2018-01-13 22:18
@mderoche ... hmm strange, it works for me on 5.2.0 in JIT or AOT mode without any problem.

**Comment by mderoche** [comment] 2018-01-15 03:15
@mlc-mlapis does it work for you using the setup I mentioned, or a different setup?  Is the secondary module you are using coming from an external library?

**Comment by mlc-mlapis** [comment] 2018-01-15 06:49
@mderoche ... ah, I forgot that it should be the external library / package. What I did was just a lazy loaded module. I have to try the external lib ...

**Comment by mlc-mlapis** [comment] 2018-01-17 22:39
@mderoche ... so made a test of `HttpClient` injection on a external package level and using that package from lazy loaded module and it works! Both on JIT or AOT mode. So it's a mystery to me why it doesn't work on your side.

My demo package is a trivial one but for the demo it is enough and is located here: https://www.npmjs.com/package/ng-mlc-demo

**Comment by alxhub** [comment] 2020-05-29 20:18
`npm link` has never been well-supported by the Angular compiler in general. I think this has to do with your specific build configuration more than it does `HttpClient`, which is a pretty average Angular service.

I'm going to close this issue for now as `Does not reproduce`, because as others have mentioned it works when using a supported build configuration. If you do continue seeing the issue in a build that doesn't involve `npm link`, please feel free to open a fresh issue with a reproduction.

**Closed** 2020-05-29 20:18 UTC
Labels: comp: common/http, freq1: low, severity2: inconvenient, triage #1, type: support
