### ISSUE TITLE
i18n: change default locale from english without generating localized bundles

### ISSUE THREAD

**Issue by MarcusRiemer** [angular/angular#39450] opened 2020-10-27 14:02 UTC
# 🚀 feature request

### Relevant Package

Angular v10

### Description

Setting the `angular.json` i18n source locale doesn't change the `LOCALE_ID` that is injected to the specified language if compiled with `--localize=false`. As my applications native language is german, this breaks quite a few things that rely on this token for e.g. API calls.

Everything works just fine in any language if localization is enabled. But this slows down the build process significantly because one has to wait for the "Localized bundle generation complete." message.

### Describe the solution you'd like

I would like to be able to generate the "native" language version of my app without running the whole localization build step. If this would be set via a different option in `angular.json` or something entirely else thats also fine.

### Describe alternatives you've considered

* This is somewhat related to issue #27883, the solutions proposed there all lead to the localized bundles being generated.
* I tried to manually inject my `de` locale [as hinted in the official docs for `LOCALE_ID`](https://angular.io/api/core/LOCALE_ID). But I didn't manage to ever get `de` being injected even if `registerLocaleData(localeDe, "de");` has been called before.

**Comment by petebacondarwin** [comment] 2020-10-27 14:16
This is a duplicate of https://github.com/angular/angular-cli/issues/16950 which is in the backlog to be fixed.

**Closed by petebacondarwin** 2020-10-27 14:16 UTC
