### ISSUE TITLE
Typed form initialization using FormBuilder problem

### ISSUE THREAD

**Issue by lukasmatta** [angular/angular#46895] opened 2022-07-19 20:27 UTC
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

No

### Description

Hello,
when trying to initialise typed form which contains a FormControl with `null` initial value and a Validator, it throws a type error. Maybe I'm missing something, but I don't expect the presence of a validator to change type of the form control value.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-qtt7cf?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fapp.component.html

**Comment by destus90** [comment] 2022-07-20 06:24
Duplicate of https://github.com/angular/angular/issues/46442

**Comment by lukasmatta** [comment] 2022-07-20 06:51
Closing as per above

**Closed** 2022-07-20 06:51 UTC
Labels: comp: forms, forms: strictly typed
