### ISSUE TITLE
An unhandled exception occurred: ENOENT: no such file or directory after IDE crash

### ISSUE THREAD

**Issue by kolkov** [angular/angular#42708] opened 2021-06-30 05:53 UTC
Hi! If `D:\Go\freicon\web\dist\freicon-online` catalog not exist, I get this error message in 12.1.0:

![image](https://user-images.githubusercontent.com/3740898/123908253-d6a2ce80-d97f-11eb-9aa9-9bee03a1d7c3.png)

When I create this catalog manually, building process is finished successfully.

```
Angular CLI: 12.1.0
Node: 16.4.0 (Unsupported)
Package Manager: npm 7.19.0
OS: win32 x64

Angular: 12.1.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, platform-browser
... platform-browser-dynamic, router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1201.0
@angular-devkit/build-angular   12.1.0
@angular-devkit/core            12.1.0
@angular-devkit/schematics      12.1.0
@angular/pwa                    0.803.29
@schematics/angular             12.1.0
rxjs                            6.6.7
typescript                      4.2.4

Warning: The current version of Node (16.4.0) is not supported by Angular.
```

**Comment by JoostK** [comment] 2021-06-30 06:41
Duplicate of https://github.com/angular/angular-cli/issues/21202.

**Closed by JoostK** 2021-06-30 06:41 UTC
