### ISSUE TITLE
HostDirective doesn't have access to descending Directives via @ViewChildren() @ContentChildren()

### ISSUE THREAD

**Issue by maximLyakhov** [angular/angular#51599] opened 2023-08-31 14:11 UTC
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

Directive placed in HostDirectives doesn't find descendant elements used in host template. 
Nor does directive on the host element.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-izksbw?file=src%2Fhost.directive.ts

### Please provide the exception or error you saw

```true
Content queries are undefined or empty.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 16.2.1
Node: 18.16.1
Package Manager: pnpm 8.7.0
OS: darwin arm64

Angular: 16.2.2
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
```

### Anything else?

Allowing hostDirectives to see descendants would hugely reduce component complexity as their parts (like accessibility, syncing) could be placed thematically in separate files.

**Comment by crisbeto** [comment] 2023-08-31 21:01
This is currently working as expected. Applying a host directive is the same as applying the directive on the same node in a template so it wouldn't make sense to expose the host's view to it.

**Comment by maximLyakhov** [comment] 2023-08-31 21:34
@crisbeto thank you for reply.
Is there a mechanism to expose host's view programmatically and run a content query?
And what is motivation for such restriction?

**Comment by crisbeto** [comment] 2023-09-01 14:08
No, there isn't such a mechanism at the moment. I'm not sure it makes sense conceptually either, because things outside of a component's template aren't supposed to have access to it.

**Comment by maximLyakhov** [comment] 2023-09-01 17:57
A reference to descending directives is enough for the most cases of sparing component code. Well, it took some time to find that such pattern isn't working.

https://angular.io/api/core/ContentChildren has the following line:
`Does not retrieve elements or directives that are in other components' templates, since a component's template is always a black box to its ancestors.` - understandable.

But https://angular.io/api/core/ViewChildren doesn't. Both of them do not work in the repro. Should it be added too?

**Comment by alxhub** [comment] 2023-09-05 20:17
Closing as Angular is working as intended here. I also think the notion that elements from other templates are not returned is inherent in the definition of a view query (as opposed to a content query).

**Closed by alxhub** 2023-09-05 20:17 UTC
Labels: area: core, core: host directives
