### ISSUE TITLE
bug: canActivate does not cancel navigation when using browser back button

### ISSUE THREAD

**Issue by liamdebeasi** [angular/angular#43181] opened 2021-08-16 19:23 UTC
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

No

### Description

When using the browser back button to go back to a page with a `canActivate` guard, navigation is not correctly prevented if the guard returns `false` and the back button is pressed multiple times.

Steps to reproduce:

1. Clone attached reproduction, run `npm install`, and then run `npm run start`.
2. In the browser, you should start on `/page1`.
3. Click "Go to Page 2". Observe you are on `/page2`.
4. Click "Go to Page 3". Observe you are on `/page3`.
5. Click "Disable going back to page 2". This will set a flag that causes the `canActivate` guard on `/page2` to return `false`.
6. Click the browser back button. Observe that the `canActivate` guard returns `false` and navigation is correctly cancelled. You should remain on `/page3`.
7. Click the browser back button again. Observe that the `canActivate` guard is not called and navigation is not cancelled. You should now be on `/page1`.

### Please provide a link to a minimal reproduction of the bug

https://github.com/liamdebeasi/ng-guard-repro

### Please provide the exception or error you saw

```true
I would expect that pressing the browser back button would attempt to navigate back to `/page2`, causing the `canActivate` guard to return `false` again.
```

### Please provide the environment you discovered this bug in

```true
Angular CLI: 12.2.1
Node: 15.9.0 (Unsupported)
Package Manager: npm 7.5.3
OS: darwin x64

Angular: 12.2.1
... cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.1
@angular-devkit/build-angular   12.2.1
@angular-devkit/core            12.2.1
@angular-devkit/schematics      12.2.1
@schematics/angular             12.2.1
rxjs                            6.6.7
typescript                      4.2.4
```

**Comment by atscott** [comment] 2021-08-17 17:51
Duplicate of #13586

**Closed by atscott** 2021-08-17 17:51 UTC
Labels: comp: router
