### ISSUE TITLE
Replacement for Resolve & Guard

### ISSUE THREAD

**Issue by Toub** [angular/angular#18247] opened 2017-07-20 10:14 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
The way Guard and Resolve have to be used is very restrictive.
There are many case it make it very complicated to do simple things.

## Expected behavior
Introduce a new concept to solve all theses common problems.

For example:

```ts
resolve: [
   {
      use: UserGuardResolver,
      name: user1, // store the return of the function here
      parameters: {
          id: 1,
          role: 'guest'
     }
]
```

This UserGuardResolver has to be able to:
* store the user1 in data
* cancel the route activation and redirect

## What is the motivation / use case for changing the behavior?

**Problem 1**: pass parameters to Resolve (or Guard) when using it multiple times (the following code does not work, just to show there is no way to pass theses parameters)
```ts
resolve: {
   user1: UserResolver(1),
   user2: UserResolver(2)
},
canActivate:[DenyAccessForRoleGuard('guest'), DenyAccessForRoleGuard('non-granted-user')]
```
In some case, we can pass parameters with data, but not when using the guard multiple times.

**Problem 2**: sometimes, you want to do Guard stuff in Resolve, or Resolve stuff in Guard.
For example, I make a http call in a guard to check some stuff, then I want to make it available in the component, so I store it in data.

Sometimes, I get a 401 during Resolve http call, so I want to cancel the route activation and redirect.

Not sure about what is the best solution, but we should make it easier to integrate both concepts.

**Problem 3**: there are no way to order or chain easily the guards and resolve
@see for example https://github.com/angular/angular/issues/18092 and https://github.com/angular/angular/issues/15032

## Environment

<pre><code>
Angular version: 4.3.0
</code></pre>

**Comment by jasonaden** [comment] 2017-07-26 17:57
@Toub Thanks for the issue. Do you have any suggestions of what you would like to see? Maybe a sample API that would be better than we have currently?

**Comment by Toub** [comment] 2017-08-08 09:28
Currently, we have:
```ts
resolve: {
   var1: Resolver1,
   var2: Resolver2
},
canActivate:[Guard1, Guard2]
```
To keep simple cases easy, and for retro-compatibility, we could simply add an advanced configuration.

To fix problem1 & 2 (passing parameters, and mixing Guard & Resolver):

```ts
before: [{
      // PreRouteHttpFetch can be a "resolver", or a "resolver + guard"
      action: PreRouteHttpFetch,
      result: 'shoppingcart', // optional
      parameters: {
            url: '/api/shoppingcart',
            id: 'mine',
            cache: false,
            // ...
      }
},
{
      // reuse the same PreRoute with different parameters
      action: PreRouteHttpFetch,
      result: 'customer',
      // parameters can also accept a function to dynamically set the parameters from route state
      parameters: (route: ActivatedRouteSnapshot, state: RouterStateSnapshot) => {
            return {
               url: '/api/customers',
               id: route.params['customer'],
               cache: true,
               // ...
            };
      }
}]
```

To cancel route activation, the PreRoute receive an extra parameter:
```ts
// class PreRouteHttpFetch
preroute(route: ActivatedRouteSnapshot, state: RouterStateSnapshot, parameters, routeControl){
   // ...
   const res = this.httpService.get(parameters.url);
   if (res.status === 404){
      routeControl.cancel();
   }
}
```
Note: we can also store the parameters directly in the route snapshot object

If we consider that all PreRoute are launched simultaneously, we can add an extra parameter to allow to chain them:

```ts
before: { // before can accept an array or a single object for easier use if we have only one PreRoute.
      action: PreRouteHttpFetch,
      result: 'customer',
      parameters: (next: ActivatedRouteSnapshot, state: RouterStateSnapshot) => {
            return {
               url: '/api/customers',
               id: route.params['customerId'],
               cache: true,
               // ...
            };
      },
      then:[
            {
              // if router activation has not be canceled, this PreRoute will be called after PreRouteHttpFetch and will transform the customer object, or maybe do a few extra-checks based on the customer properties 
               action: PreRouteTransformCustomer,
               result: 'smartCustomer',
            }
      ]
}
```

**Comment by Toub** [comment] 2017-09-01 10:19
@jasonaden any update about this one?

My suggestion would be currently broken by AOT compilation: https://github.com/angular/angular/issues/18886

**Comment by Toub** [comment] 2017-09-21 15:45
There are a bunch of issues about router, guards and resolvers.

@jasonaden any plan to improve it in angular5 or later releases?

**Comment by jasonaden** [comment] 2017-12-07 23:13
@Toub You probably noticed, there wasn't much update for Angular 5. But there is a plan to make some changes in an upcoming release. Hopefully this can be done by v6.

**Comment by Toub** [comment] 2017-12-08 04:57
@jasonaden thanks for the update, waiting for a link to the tracking issue or discussion when the work starts publicly

**Comment by Toub** [comment] 2018-05-30 06:04
@jasonaden any plan to add a new resolve & guard mechanism in v7?

**Comment by jasonaden** [comment] 2018-06-05 22:48
@Toub Not sure if this will be something for v7. We have a lot going on in other areas (Ivy), and most of the feature updates to the router are dependent on this work being complete.

**Comment by ggjersund** [comment] 2019-01-20 05:56
Am I understanding this correctly: You want the `resolve()` to be able to fail the same way as `canActivate()` by triggering cancelNavigation? If so, I'm really hoping for this as well.

In the following case:
`www.example.com/item/1` resolves fine e.g. the item exist in the database and returns data.
`www.example.com/item/2` can't resolve e.g. the item does not exist in the database and returns 404. 
Currently the last URL would force me to redirect to another URL, and return an empty observable.

**What I'd like:**
To force throwError for observables to trigger navigationCancel in the routing process, thus making it possible for failed resolves to trigger the wildcard (404 page) path while persisting the URL.

**Comment by rob3c** [comment] 2021-06-06 07:03
The bot links to a feature request process that says there are 60 days for voting. Two days ago, the bot labeled this issue as "votes required" and said there are 20 days until the voting process ends. What happened to 60?

**Comment by atscott** [comment] 2021-09-15 19:45
Closing as duplicate of #42171 and #40577

Problem 1 is a duplicate of #42171

Problem 2 can be solved by storing data from the guard in a place that can be retrieved by the resolver. This data can be cleared on `NavigationStart` events.

Problem 3 is understandable and is a duplicate of #40577. The way guards execute should generally be changeable, though not necessarily provided as a feature of the Router. @sod provided an example of how to configure chainable guards with the existing APIs: https://github.com/angular/angular/issues/40577#issuecomment-768209703.

**Closed by atscott** 2021-09-15 19:45 UTC
Labels: feature, freq3: high, comp: router, insufficient votes, votes required
