### ISSUE TITLE
When child form control disabled. entire form group dirty status is change to be `false`

### ISSUE THREAD

**Issue by johnny-mh** [angular/angular#23309] opened 2018-04-11 10:11 UTC
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
When child form control disabled. entire form group's dirty changed to `false`.

## Expected behavior
Even if child form control disabled. enter form group dirty status not changed.

## Minimal reproduction of the problem with instructions
https://plnkr.co/edit/Iq9XVxBVFHdFBGvlKPoZ?p=preview

## Environment

<pre><code>
Angular version: 5.2.9

Browser:
- [x] Chrome (desktop) version latest
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by martinsik** [comment] 2018-06-20 08:33
This is a simplified version of you demo on stackblitz: https://stackblitz.com/edit/angular-8bab4v?file=src%2Fapp%2Fapp.component.ts

Note that calling `setValue` doesn't mark the FormControl as dirty. Also calling `this.form.markAsDirty()` doesn't mark its children as `dirty`. This is discussed in [AbstractControl.markAs* asymmetry is confusing, limiting]( https://github.com/angular/angular/issues/11774).

If I understand this correctly the problem is that when I call `this.form.markAsDirty();` and then disable some child FormControl `this.form.controls['a'].disable(); it makes the whole FormGroup non-dirty `this.form.dirty`.

**Comment by aaronrhodes** [comment] 2018-09-04 10:05
Hey, we're super interested in this bug fix as it has become somewhat of an issue for us - is there any ETA on when this will be merged and released..?

**Comment by everedifice** [comment] 2018-09-04 11:28
@martinsik, @aaronrhodes 'control.dirty' is getter method. so entire form's dirty flag be determining after method invoked.

The method iterate all control and check each dirty status. if some child control disabled. the method ignore that control. So result is 'true'.

If you have another opinion. I want close this issue.

**Comment by AndrewKushnir** [comment] 2020-05-28 19:37
Hi @johnny-mh, thanks for reporting the issue. Based on your most recent reply it looks like the problem is resolved and you want to close this issue. I'm closing this ticket, feel free to reopen if the problem still exists. Thank you.

**Closed by AndrewKushnir** 2020-05-28 19:37 UTC
Labels: comp: forms, freq2: medium, severity3: broken, type: bug/fix
