### ISSUE TITLE
It is not possible to use Router + Module (module.id)

### ISSUE THREAD

**Issue by Judahh** [angular/angular#10413] opened 2016-07-30 23:33 UTC
**I'm submitting a ...**  (check one with "x")
```
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
It is not possible to use Router + Module (module.id).
If I use "angular2": "2.XXXX", I can't use module because it's not defined (angular2-polyfills.js:349 Error: ReferenceError: module is not defined
	    at eval (http://localhost:3000/app/Body/Header/Header.component.js:43:35)
	    at execute (http://localhost:3000/app/Body/Header/Header.component.js:53:14)
	Error loading http://localhost:3000/app/main.js)

If I use "@angular":  "2.XXXX", I can't use Router because  RouterConfig, ProvideRouter are't in the package @angular/router.

**Expected/desired behavior**
I thought I could use both of them using any version of Angular2, but for some reason I cannot.

**Please tell us about your environment:**
Windows 8.1

* **Angular version:** 2
 
* **Browser:** [Chrome] 
 
* **Language:** [TypeScript]

**Comment by brandonroberts** [comment] 2016-07-31 20:00
The latest version of the router is `"@angular/router": "3.0.0-beta.2"`

**Comment by Judahh** [comment] 2016-08-01 14:27
Yeah and I'm using it!

**Comment by brandonroberts** [comment] 2016-08-01 20:06
What are you bundling with? Some sample code or a reproduction would help

**Comment by vsavkin** [comment] 2016-08-09 23:30
Please provide a repro?

**Comment by vsavkin** [comment] 2016-08-19 22:04
Closing this issue. If the issue is still present, please reopen it with a repro.

**Closed by vsavkin** 2016-08-19 22:04 UTC
Labels: comp: router, need: repro, type: bug
