### ISSUE TITLE
Link broken for https://angularconsole.com/ at https://angular.io/cli#cli-overview-and-command-reference

### ISSUE THREAD

**Issue by illuminati-code** [angular/angular#38013] opened 2020-07-11 14:39 UTC
# 📚 Docs or angular.io bug report

### Description

Link for [angularconsole.com](https://angularconsole.com/) is broken at [CLI Overview and Command Reference](https://angular.io/cli#cli-overview-and-command-reference).

### What's the affected URL?**
https://angular.io/cli#cli-overview-and-command-reference

### Reproduction Steps**
Go to [CLI Overview and Command Reference](https://angular.io/cli#cli-overview-and-command-reference)

### Expected vs Actual Behavior**

Expected https://angularconsole.com/ should be working or link should be updated to the proper resource.

## 📷Screenshot

![Screenshot (1)](https://user-images.githubusercontent.com/63699621/87226544-0b55f880-c3b2-11ea-8620-a26c8f21af3c.png)

![Screenshot (2)](https://user-images.githubusercontent.com/63699621/87226545-0db85280-c3b2-11ea-8893-cdeac8f471e0.png)

## 🔥 Exception or Error
<pre><code>
Site Not Found
</code></pre>

### Browser info
Firefox Beta - 78.0beta

**Comment by JoostK** [comment] 2020-07-11 15:11
Duplicate of #37604, being addressed in #37608.

**Closed by JoostK** 2020-07-11 15:11 UTC
