### ISSUE TITLE
Cache problem during deployment to production with service workers

### ISSUE THREAD

**Issue by Gnorro** [angular/angular#34636] opened 2020-01-04 09:43 UTC
# 🐞 bug report

### Description
We have 2 problems:

1.
We have an angular app with service workers. We deployed it months ago without any problem running ng build --configuration=production. We have IIS 10 (below I added it's configuration).
Now, every time we need to do an update, we delete all deployed files and we copy new ones in site root. After this operation we start getting problems. Site doesn't load, we get black page with some errors (errors are described below)
This happens only in production environment. We have another server where we deploy app for testing before deploy to production, and here we have no problem. The difference between two environments is only the presence of a CDN in production one.
After every deploy in production we also invalidate entire CDN cache.

2.
This problem occurs in production but also on developer server where we don't have CDN. When we deploy an update (deleting all files in site root and then copying there new ones, we expect new version is loaded when user open site. Service workers should understand a new version has been deployed comparing its version with the new one through ngsw.json file, and finally "install" the correct version.
This happens only if a user delete browser cache or if user do a ctrl + f5. This doesn't happens with a simple page refresh. And this happens on every browser.

## 🔥 Exception or Error
Error for problem 1:
<pre><code>
Refused to execute script from https://mysite/1.5960f4f...js/ because its MIME type (text/html/ is not executable, and strict MIME type checking is enabled
and same error on other js files that are other modules files.
</code></pre>

Error screenshot
![Cattura](https://user-images.githubusercontent.com/31180439/71763682-cfac1480-2ede-11ea-81fc-2ac3a0680364.JPG)

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 7.3.9
Node: 10.16.0
OS: win32 x64
Angular: 7.2.15
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.9
@angular-devkit/build-angular     0.13.9
@angular-devkit/build-optimizer   0.13.9
@angular-devkit/build-webpack     0.13.9
@angular-devkit/core              7.3.9
@angular-devkit/schematics        7.3.9
@angular/cdk                      7.3.7
@angular/cli                      7.3.9
@angular/material                 7.3.7
@angular/pwa                      0.8.7
@ngtools/webpack                  7.3.9
@schematics/angular               0.8.7
@schematics/update                0.13.9
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.29.0
</code></pre>

**Anything else relevant?**

The site is under AWS CDN (CloudFront)
CDN rules cache every image, js and css

Our ngsw-config.json:
<pre><code>
{
  "index": "/index.html",
  "assetGroups": [
    {
      "name": "app",
      "installMode": "prefetch",
      "resources": {
        "files": [
          "/favicon.ico",
          "/index.html",
          "/*.css",
          "/*.js",
          "/*.(woff2)"
        ]
      }
    }, {
      "name": "assets",
      "installMode": "lazy",
      "updateMode": "prefetch",
      "resources": {
        "files": [
          "/assets/**",
          "/*.(eot|svg|cur|jpg|png|webp|gif|otf|ttf|woff|ani)"
        ]
      }
    }
  ]
}
</code></pre>

Our index.html:
```xml
<!doctype html>
<html lang="it">

<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <style>
        .async-hide {
            opacity: 0 !important
        }
    </style>
    <script>(function (a, s, y, n, c, h, i, d, e) {
            s.className += ' ' + y; h.start = 1 * new Date;
            h.end = i = function () { s.className = s.className.replace(RegExp(' ?' + y), '') };
            (a[n] = a[n] || []).hide = h; setTimeout(function () { i(); h.end = null }, c); h.timeout = c;
        })(window, document.documentElement, 'async-hide', 'dataLayer', 4000,
            { 'XXXXXXX': true });</script>
    <meta charset="utf-8">
    <title>Title</title>
    <base href="/">

    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />
    <link rel="icon" type="image/x-icon" href="favicon.ico">

    <meta name="theme-color" content="#1976d2">

</head>

<body class="body">
    <app-root></app-root>
</body>

</html>
<script>
    if (global === undefined) {
        var global = window;
    }
    if (System === undefined) {
        var System = window;
    }
</script>
```

We deploy app under IIS

These are some relevant parts of web.config:
```xml
<httpProtocol>
	<customHeaders>
		<remove name="X-Content-Type-Options" />
		<add name="X-Content-Type-Options" value="nosniff" />
		<remove name="X-Powered-By" />
		<remove name="Vary" />
		<add name="Vary" value="Accept-Encoding,User-Agent" />
	</customHeaders>
</httpProtocol>

...

<httpCompression directory="%SystemDrive%\inetpub\temp\IIS Temporary Compressed Files">
	<scheme dll="%Windir%\system32\inetsrv\gzip.dll" name="gzip" staticCompressionLevel="9" />
	<dynamicTypes>
		<add mimeType="text/*" enabled="true" />
		<add mimeType="message/*" enabled="true" />
		<add mimeType="application/javascript" enabled="true" />
		<add mimeType="application/json" enabled="true" />
		<add mimeType="*/*" enabled="false" />
	</dynamicTypes>
	<staticTypes>
		<add enabled="true" mimeType="text/*" />
		<add enabled="true" mimeType="message/*" />
		<add enabled="true" mimeType="application/javascript" />
		<add enabled="true" mimeType="application/json" />
		<add enabled="false" mimeType="*/*" />
	</staticTypes>
</httpCompression>

...

<urlCompression doStaticCompression="true" doDynamicCompression="true" />

...

<staticContent>
	<clientCache cacheControlMode="UseMaxAge" cacheControlMaxAge="30.00:00:00" cacheControlCustom="public" />
	
	<remove fileExtension=".html" />
	<mimeMap fileExtension=".html" mimeType="text/html; charset=UTF-8" />
	<remove fileExtension=".css" />
	<mimeMap fileExtension=".css" mimeType="text/css" />
	<remove fileExtension=".js" />
	<mimeMap fileExtension=".js" mimeType="text/javascript" />
	<remove fileExtension=".png" />
	<mimeMap fileExtension=".png" mimeType="image/png" />
	<remove fileExtension=".jpg" />
	<mimeMap fileExtension=".jpg" mimeType="image/jpeg" />
	<remove fileExtension=".json" />
	<mimeMap fileExtension=".json" mimeType="application/json" />
	<remove fileExtension=".rss" />
	<mimeMap fileExtension=".rss" mimeType="application/rss+xml; charset=UTF-8" />
	<remove fileExtension=".xml" />
	<mimeMap fileExtension=".xml" mimeType="application/xml; charset=UTF-8" />
	<!-- HTML5 Audio/Video mime types-->
	<remove fileExtension=".mp3" />
	<mimeMap fileExtension=".mp3" mimeType="audio/mpeg" />
	<remove fileExtension=".mp4" />
	<mimeMap fileExtension=".mp4" mimeType="video/mp4" />
	<remove fileExtension=".ogg" />
	<mimeMap fileExtension=".ogg" mimeType="audio/ogg" />
	<remove fileExtension=".ogv" />
	<mimeMap fileExtension=".ogv" mimeType="video/ogg" />
	<remove fileExtension=".webm" />
	<mimeMap fileExtension=".webm" mimeType="video/webm" />
	<!-- Proper svg serving. Required for svg webfonts on iPad -->
	<remove fileExtension=".svg" />
	<mimeMap fileExtension=".svg" mimeType="image/svg+xml" />
	<remove fileExtension=".svgz" />
	<mimeMap fileExtension=".svgz" mimeType="image/svg+xml" />
	<!-- HTML4 Web font mime types -->
	<!-- Remove default IIS mime type for .eot which is application/octet-stream -->
	<remove fileExtension=".eot" />
	<mimeMap fileExtension=".eot" mimeType="application/vnd.ms-fontobject" />
	<remove fileExtension=".ttf" />
	<mimeMap fileExtension=".ttf" mimeType="application/x-font-ttf" />
	<remove fileExtension=".ttc" />
	<mimeMap fileExtension=".ttc" mimeType="application/x-font-ttf" />
	<remove fileExtension=".otf" />
	<mimeMap fileExtension=".otf" mimeType="font/opentype" />
	<remove fileExtension=".woff" />
	<mimeMap fileExtension=".woff" mimeType="application/font-woff" />
	<remove fileExtension=".woff2" />
	<mimeMap fileExtension=".woff2" mimeType="font/woff2" />
	<remove fileExtension=".crx" />
	<mimeMap fileExtension=".crx" mimeType="application/x-chrome-extension" />
	<remove fileExtension=".xpi" />
	<mimeMap fileExtension=".xpi" mimeType="application/x-xpinstall" />
	<remove fileExtension=".safariextz" />
	<mimeMap fileExtension=".safariextz" mimeType="application/octet-stream" />
	<!-- Flash Video mime types-->
	<remove fileExtension=".flv" />
	<mimeMap fileExtension=".flv" mimeType="video/x-flv" />
	<remove fileExtension=".f4v" />
	<mimeMap fileExtension=".f4v" mimeType="video/mp4" />
	<!-- Assorted types -->
	<remove fileExtension=".ico" />
	<mimeMap fileExtension=".ico" mimeType="image/x-icon" />
	<remove fileExtension=".webp" />
	<mimeMap fileExtension=".webp" mimeType="image/webp" />
	<remove fileExtension=".htc" />
	<mimeMap fileExtension=".htc" mimeType="text/x-component" />
	<remove fileExtension=".vcf" />
	<mimeMap fileExtension=".vcf" mimeType="text/x-vcard" />
	<remove fileExtension=".torrent" />
	<mimeMap fileExtension=".torrent" mimeType="application/x-bittorrent" />
	<remove fileExtension=".cur" />
	<mimeMap fileExtension=".cur" mimeType="image/x-icon" />
	<remove fileExtension=".webapp" />
	<mimeMap fileExtension=".webapp" mimeType="application/x-web-app-manifest+json; charset=UTF-8" />
</staticContent>

...

<location path="index.html">
	<system.webServer>
	  <staticContent>
		<clientCache cacheControlMode="DisableCache" cacheControlMaxAge="0.00:00:00" />
	  </staticContent>
		<httpProtocol>
			<customHeaders>
				<add name="Cache-Control" value="no-cache, no-store, must-revalidate" />
				<add name="Pragma" value="no-cache" />
				<add name="Expires" value="-1" />
			</customHeaders>
		</httpProtocol>  
	</system.webServer>
</location>
```

Our package.json:
<pre><code>
{
  "name": "xxx",
  "version": "0.0.0",
  "scripts": {
    "ng": "node --max_old_space_size=8192 node_modules/@angular/cli/bin/ng",
    "start": "npm run ng -- serve",
    "build": "npm run ng -- build",
    "test": "npm run ng -- test",
    "lint": "npm run ng -- lint",
    "e2e": "npm run ng -- e2e",
    "analyze": "webpack-bundle-analyzer dist/stats.json",
    "compodoc": "npx compodoc -p src/tsconfig.app.json",
    "build:stats": "ng build --stats-json"
  },
  "private": true,
  "dependencies": {
    "@agm/core": "1.0.0-beta.7",
    "@agm/js-marker-clusterer": "1.0.0-beta.3",
    "@angular/animations": "7.2.15",
    "@angular/cdk": "7.3.7",
    "@angular/common": "7.2.15",
    "@angular/compiler": "7.2.15",
    "@angular/core": "7.2.15",
    "@angular/forms": "7.2.15",
    "@angular/http": "7.2.15",
    "@angular/material": "7.3.7",
    "@angular/platform-browser": "7.2.15",
    "@angular/platform-browser-dynamic": "7.2.15",
    "@angular/platform-server": "7.2.15",
    "@angular/pwa": "0.8.7",
    "@angular/router": "7.2.15",
    "@angular/service-worker": "7.2.15",
    "@satispay/web-button-factory": "1.4.3",
    "angular4-social-login": "1.1.1",
    "braintree-web": "3.52.1",
    "braintree-web-drop-in": "1.20.1",
    "classlist.js": "1.1.20150312",
    "codice-fiscale-js": "2.1.0",
    "core-js": "2.5.4",
    "domino": "2.1.3",
    "express": "4.17.1",
    "font-awesome": "4.7.0",
    "hammerjs": "2.0.8",
    "js-marker-clusterer": "1.0.0",
    "lory.js": "2.3.3",
    "md5": "2.2.1",
    "moment-mini-ts": "2.20.1",
    "ng-lazyload-image": "5.1.2",
    "ng2-cookies": "1.0.12",
    "ngx-gallery": "4.1.2",
    "ngx-json-ld": "0.3.1",
    "ngx-loadable": "1.0.10",
    "ngx-responsive": "6.0.0",
    "ngx-swiper-wrapper": "4.9.0",
    "paypal-checkout": "4.0.285",
    "rxjs": "~6.3.3",
    "tslib": "1.9.0",
    "zone.js": "~0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "0.13.9",
    "@angular/cli": "7.3.9",
    "@angular/compiler-cli": "7.2.15",
    "@angular/language-service": "7.2.15",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.5.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~3.1.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "0.2.2",
    "node-ts": "5.0.1",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "3.1.6",
    "webpack-bundle-analyzer": "3.3.2"
  }
}
</code></pre>

I suppose problem 1 is related to CDN, but I don't understand why. It seems that somewhere (I think on user's browsers, in service workers) something continue to have reference to old files (the ones we delete before copying there new app version). And this problem seems to be related to problem number 2, where it seems new version is not loaded the first time user access it.

Maybe we are doing something wrong, or we have an incorrect configuration, but we can't find it.

Thanks for help

**Comment by spock123** [comment] 2020-01-04 12:34
Can I ask what the caching policy on your webserver/cdn is for the sw files? Ngsw.json.. 

I had this issue on Firebase hosting because the default cache is 1 hour .

I don't know how your cdn does but make sure to explicity set no-cache  on the sw related files.

What do the response headers look like when you access the ngsw.json file directly?

**Comment by Gnorro** [comment] 2020-01-04 12:53
Hi

This is our current configuration:
![Cattura2](https://user-images.githubusercontent.com/31180439/71765740-91235380-2ef8-11ea-8f8e-c3c8801506dc.JPG)

In CloudFront popular object I noticed this:
![Cattura1](https://user-images.githubusercontent.com/31180439/71765836-74d3e680-2ef9-11ea-87c5-fef1fb1246cc.JPG)

I don't know if this helps

Thanks

**Comment by gkalpak** [comment] 2020-01-07 14:40
It is hard to tell what the issue might be without a reproduction. It could be that the CDN caches some files but doesn't cache others (e.g. caches an old `ngsw.json` but not the associated JS files), leading to the SW trying to fetch files (based on `ngsw.json`) that the CDN cannot deliver any more.

Another issue could be that the CDN is ignoring URL query params (which the SW sometimes uses to ensure the latest version of a file is fetched) - I've seen this happen with the default config on some CDNs.

[/ngsw/state][1] might contain info that will help debug this further.
I would, also, be happy to take a look if I can get my hands on a reproduction. In the meantime, I am going to close the issue, since it is not actionable for us in its current state, but feel free to continue the discussion below.

[1]: https://angular.io/guide/service-worker-devops#locating-and-analyzing-debugging-information

**Closed by gkalpak** 2020-01-07 14:40 UTC

**Comment by Gnorro** [comment] 2020-01-07 14:56
thanks
I sent you an email

**Comment by bogacg** [comment] 2020-01-11 16:50
I have similar problem with Firebase hosting and when I search online I see other people reporting similar issues.
Please keep us posted further updates about this.

**Comment by Gnorro** [comment] 2020-01-13 14:11
We did another deploy on our test server and we got same error today.
Running a /ngsw/state we got this info:

NGSW Debug Info:

Driver state: EXISTING_CLIENTS_ONLY (Degraded due to: Hash mismatch (cacheBustedFetchFromNetwork): https://mysite.com/runtime.665996686bad09502301.js: expected 82327f4fe0474d28829f41683c3d047b87296b3d, got 33dc7869d7d30ef844badc68e21289228e0018d3 (after cache busting)
Error: Hash mismatch (cacheBustedFetchFromNetwork): https://mysite.com/runtime.665996686bad09502301.js: expected 82327f4fe0474d28829f41683c3d047b87296b3d, got 33dc7869d7d30ef844badc68e21289228e0018d3 (after cache busting)
    at PrefetchAssetGroup.<anonymous> (https://mysite.com/ngsw-worker.js:692:35)
    at Generator.next (<anonymous>)
    at fulfilled (https://mysite.com/ngsw-worker.js:312:62))
Latest manifest hash: 909d171a4e37f8815c2fd424d7b7fb66180ff02e
Last update check: 4s149u

=== Version 909d171a4e37f8815c2fd424d7b7fb66180ff02e ===

Clients: 

=== Idle Task Queue ===
Last update tick: 19u
Last update run: 4s185u
Task queue:


Debug log:

[13s66u] TypeError(Failed to fetch, TypeError: Failed to fetch) Driver.fetch(https://photo.mysite.com.itnull/)

This means there were some problem during service worker update (I suppose)
But I have no idea how to solve it

**Comment by bogacg** [comment] 2020-01-16 19:53
My problem seems to be gone after I've updated to latest angular RC dependencies and following this guide: [Build a production ready PWA with Angular and Firebase](https://itnext.io/build-a-production-ready-pwa-with-angular-and-firebase-8f2a69824fcc) I've also changed server (Firebase) cache-control settings (previously no-caching, after: js/css files cached except service worker files.)

**Comment by Gnorro** [comment] 2020-01-25 13:03
I will follow that guide, but we don't have Firebase

What is not clear to me is why Service Worker seems to look for old js files on the server while it should load the ones it has on the client and understand there is a new version to install.

bogacg, what did you change exactly in not Firebase related files. Can you post your  ngsw-config.json configuration please?

**Comment by bogacg** [comment] 2020-01-27 11:31
Sorry for not updating my answer prior @Gnorro . Unfortunately news are not good, still seeing same problem, I've just learned to manage around it, temporarily, read below please yet this situation is still disturbing.

In addition to this problem, I have now another one, probably related, which is service worker `.available` observable does not fire. I've noticed this first since around v9.0.rc-5 yet once app is closed and next time it's opened updated version is loaded. Because of this I can not warn users now that there is a new version.

To understand why it looks for old files from server, lets consider order of things:
[ I use "it" instead of Angular or browser because I can not put my finder on which one has the responsibility to manage this faulty situation]
* `index.html` is loaded [from the cache]
* `index.html` references `runtime*.js` and `main*.js` files, they are loaded from cache.
* `main*.js` references your modules, js files that are supposed to be either already in cache but they are not, if some of them are lazy loaded and maybe user closed app before fully downloading all related files previously etc, at this point you see the error. I even suspect some lazy loaded files are deleted from the cache even if they were previously loaded, if so why ?
  * Angular routing preloading strategy might have affect on this. Mine was in `PreloadAllModules` setting.

Seeing error at this point makes sense if one accepts the fact that there is a problem either on Angular side or browser way of handling PWA cache, because you've updated your app but previous version is half loaded to cache and some of files are not on the server at this point. Once you update your app you hope browser loads the latest version, it doesn't.

Things you can do / I did are as follows (yet didn't fix all my clients, thankfully it was still under staging domain) :

* You can delete `ngsw-worker.js` and rename `safety-worker.js` (when Angular builds PWA app, it puts this file there too) to `ngsw-worker.js`. [Read about it here](https://angular.io/guide/service-worker-devops#safety-worker)
  * This actually cancels service worker(s) and your app works with latest version as from the server online.
* You can also put cache deletion code to your `main.ts` but this one is a destructive one, I've used it since my app wasn't working anyways, so nothing to loose.
  * `window` object has `caches` iterable, you delete all it has. [Read here](https://stackoverflow.com/a/46597656/1539073)
  * and also remove `main*.js` files from asset group's caching  [in angular.json](https://stackoverflow.com/a/55700061/1539073)

The Firebase part of that article I've pointed out is important for one thing in your case, how server should add **http headers** so that browser knows what to cache and what not.
 See section **10.4 A basic hosting configuration example**. Onder suggests not to cache main service worker file (but in his example he deviated from default Angular service worker file, so in our case `ngsw-worker.js`)

Last advice I can give you is to keep one or two version of previous built js/css files and don't just upload latest build (I mean GUID added files, the ones that has same name in each build like `index.html` are only kept by latest version). That way if your app uses half cached version and tries to fetch an older version of some files because it doesn't have in its cache, server still returns it.

To do so I've created a repository for distribution folder and commit each version, prior to upload to server I revert back older 2 versions of Js/Css files that are deleted on latest build.

I believe there is a bug either on Angular side or Chrome's way of handling service worker cache. In an ideal world, as a developer if you updated an app, with what PWA tech promises you expect your app gets updated on your clients as well.

**Comment by spock123** [comment] 2020-01-27 16:26
> I have similar problem with Firebase hosting and when I search online I see other people reporting similar issues.
> Please keep us posted further updates about this.

Firebase hosting has a 1 hour default caching policy. If you don't specifically specify that you do not want caching on the service worker files, you'll get this 1 hour cache.

What you do is that in your firebase.json you insert the following in the `headers` section:

 ```
.... 
"headers": [ 
    ... other headers,
      {
        "source": "**/(ngsw-worker.js|ngsw.json)",
        "headers": [
          {
            "key": "Cache-Control",
            "value": "no-cache, no-store, must-revalidate"
          }
        ]
      },
```
