### ISSUE TITLE
setTimeout ignores additional arguments when run inside Angular class constructor

### ISSUE THREAD

**Issue by lppl** [angular/angular#7165] opened 2016-02-18 23:46 UTC
Short version: setTimeout fails inside angular2 class cosntructor, but works fine outside of its context.

Full example you will find here: https://plnkr.co/GYir5dReBvTt0QrPp9eF?p=preview It contains function "run" which starts coutdown (inside console). Once inside angular2 code, once outside. The expected behavior is for countdown to hit zero both time. 

ps. Tested at newest chrome/firefox on ubuntu system.
ps. I've found two issues about setTimeout arguments: https://github.com/angular/angular/pull/344 and https://github.com/angular/angular/issues/6088. But I'm not sure if they are related.

**Comment by ericmartinezr** [comment] 2016-02-18 23:49
@lppl you should reproduce this with the latest version. The plnkr is using a44, while angular2 is currently in beta.7

**Comment by lppl** [comment] 2016-02-19 00:27
Locally I have this problem with Angular 2.0.0-beta.7 and Zone 0.5.15. As I dont have time right now I will show working beta.7 example in few hours.

**Comment by lppl** [comment] 2016-02-19 09:59
Plunker with 2.0.0-beta.7 version
https://plnkr.co/gaBThueKGEfYXsG3g4yp?p=preview

**Comment by ericmartinezr** [comment] 2016-02-26 18:34
@lppl whether this is a bug or not, it should be reported in zone.js repo https://github.com/angular/zone.js

**Comment by lppl** [comment] 2016-02-26 20:53
@ericmartinezr thanks!

Continuation:  https://github.com/angular/zone.js/issues/265.

**Comment by DrewynV** [comment] 2016-04-05 00:27
__________________________________

Hi! We just wanted to let you know we receievd your email. Thank you for submitting your request. Our aim is to get back to you within 24 hours at the latest. If you have any additional information to add to your request, please reply to this email.


Also please visit our knowledgebase (http://www.support.magicdust.com.au) to browse for further info, we are adding to it all the time.

Or here is our industry report about the 11 Essentials for a Successful Website (http://www.magicdust.com.au/web-design/.

We look forward to helping you succeed online.

Thanks

The Team @ Magicdust Digital

http://support.magicdust.com.au/

Ph (02) 9979 7474
M-F | 9 am-5:00 pm AEST (AEDT in Summer) excluding Public Holidays

------------------------------------------------------------------------------------------------------------
This message was sent to  reply@reply.github.com in reference to Case #166443.
------------------------------------------------------------------------------------------------------------


[[0b3f78495a00afa62ae9ef77643e4967e91a2c5f-673073290]]

**Comment by pkozlowski-opensource** [comment] 2016-08-31 10:22
Duplicate of https://github.com/angular/zone.js/issues/265

**Closed by pkozlowski-opensource** 2016-08-31 10:22 UTC
