### ISSUE TITLE
build.dart expected errors ?

### ISSUE THREAD

**Issue by vicb** [angular/angular#2454] opened 2015-06-10 06:44 UTC
on master: https://travis-ci.org/angular/angular/jobs/66142657#L650

are those expected ?

/cc @kegluneq

**Comment by kegluneq** [comment] 2015-06-10 14:39
These errors are coming from `package:di`, which is the original Angular.dart's DI code. I believe that is being brought in by benchmarking code to compare angular2 vs. angular.dart performance.

I don't know whether they are expected or not.

**Comment by vicb** [comment] 2015-06-10 15:45
It seems like those are recent, I've first noticed them on your PR
https://travis-ci.org/angular/angular/jobs/66138141
There were not on alpha.26 
https://travis-ci.org/angular/angular/jobs/65336394

_(Not saying your PR is the root cause. Only adding refs for further investigations - could it linked to a dependency update ?)_

**Comment by kegluneq** [comment] 2015-06-10 17:13
I'm guessing https://github.com/angular/angular/commit/b2596dd3024491be7a39c94c6d703dba2fa1539f is the culprit, it adds empty .dart files and the errors sound correct to that situation.

Here is the build log for that commit: https://travis-ci.org/angular/angular/jobs/65435790#L652
and the same area in the commit before: https://travis-ci.org/angular/angular/jobs/65416977#L643

You probably know more about `package:di` than I do -- any idea why empty dart files might cause this situation?

**Comment by vicb** [comment] 2015-06-10 17:32
Thanks for the analysis.

Might be because the transformers look for DI related code in the main or because there are multiple main. I'll take a look later this week.

**Comment by kegluneq** [comment] 2015-06-12 15:23
Looks like this is a duplicate of https://github.com/angular/angular/issues/2380

**Closed by kegluneq** 2015-06-12 15:23 UTC
Labels: type: RFC / discussion / question
