### ISSUE TITLE
AngularZone Rx Operator Function

### ISSUE THREAD

**Issue by jonahd-g** [angular/angular#39579] opened 2020-11-05 18:44 UTC
# 🚀 feature request

### Relevant Package
This feature request is for @angular/core

### Description
When integrating with portions of a web application that operate outside of Angular (specifically the Angular Zone), it's necessary to use ngZone.run() to get back into the NgZone if an event comes from outside.  This is easy enough to do, but it can be a pain to do when an Observable emits a value from outside the zone.  It's especially annoying when you don't know whether it came from outside the zone.  An example of that uncertainty is when an external event source can either emit its own events, or might emit an event as a direct response to something happening in the Zone.

### Describe the solution you'd like
Angular could provide a set of utility operator functions for interfacing with NgZone in Observables.  List of possible operators:

- `runInAngular` (= `ngZone.run()`
- `runOutsideAngular` (= `ngZone.runOutsideAngular()`)
- `ensureInAngular` (= `if (!NgZone.isInAngularZone) ngZone.run()`)

Usage example:
```typescript
// outsideObservable emits from outside ngZone
outsideObservable.pipe(runInAngular(this.ngZone)).subscribe(...);
// subscriber will be invoked inside the ngZone
```
`ensureInAngular` is particularly useful for handling uncertain event origins, since `run` by itself will complain if it's already in an NgZone.

Implementation of ensureInAngular:

```typescript
function invokeInAngularZone(ngZone: NgZone, callback: () => {}): void {
  if (NgZone.isInAngularZone()) {
    callback()
  } else {
    ngZone.run(() => {
      callback();
    });
  }
}

export function ensureInAngularZone<T>(ngZone: NgZone): MonoTypeOperatorFunction<T> {
  return observable => {
    return new Observable(subscriber => {
      observable.subscribe(
        value => {
          invokeInAngularZone(ngZone, () => {
            subscriber.next(value);
          });
        },
        error => {
          invokeInAngularZone(ngZone, () => {
            subscriber.error(error);
          });
        },
        () => {
          invokeInAngularZone(ngZone, () => {
            subscriber.complete();
          });                                                                
        },
      );
    });
  };
}
```

### Describe alternatives you've considered
It must be done by the user code right now.

**Comment by JoostK** [comment] 2020-11-07 22:10
Related to #4603. May even be considered a duplicate.

**Comment by jonahd-g** [comment] 2020-11-09 18:19
yeah that could serve the purpose, as long as there is a way to get both in and out.

**Comment by AndrewKushnir** [comment] 2021-06-10 23:53
Closing as a duplicate of #4603.

**Closed by AndrewKushnir** 2021-06-10 23:53 UTC
Labels: comp: core, comp: zones, feature, votes required
