### ISSUE TITLE
How to run angular2 app using github sources and not npm package

### ISSUE THREAD

**Issue by maximusk** [angular/angular#13928] opened 2017-01-14 18:08 UTC
It seems that with the latest angular2 npm package there is no way to debug typescript sources. Existing [answer on stackoverflow](http://stackoverflow.com/questions/36423923/how-angular2-create-bundles-directory-and-how-do-i-generate-source-map) and [the article on medium](https://medium.com/@ttemplier/how-to-debug-the-typescript-source-code-of-angular2-99a593e2983f#.wcuopmt4g) are outdated.

Js files in npm package are compiled into es6 module syntax, which is not supported yet in browsers and a loader, like SystemJS, requires traceur. For example, common/index.j:

`export { NgLocalization, CommonModule, NgClass, ..., Location } from './src/common';`

But I can't use traceur, since it most likely break existing source maps created for js files transpiled by tsc.

**Comment by DzmitryShylovich** [comment] 2017-01-14 18:10
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by maximusk** [comment] 2017-01-14 18:12
What to do if there is no answer on stackoverflow?

**Comment by maximusk** [comment] 2017-01-14 20:06
At the moment it seems that there is no way to debug sources in ts in a browser. Besides code being bundled in npm package, it's non bundled files are compiled into `es6` module syntax, which is not supported by SystemJS without transpiler. There is got to be a solution from the core team on how to debug typescript sources? There is nowhere on the web where such information can be found. All [answers on stackoverflow](http://stackoverflow.com/questions/36423923/how-angular2-create-bundles-directory-and-how-do-i-generate-source-map) and [articles](https://medium.com/@ttemplier/how-to-debug-the-typescript-source-code-of-angular2-99a593e2983f#.18kspegsf) on medium are outdated.

**Comment by DzmitryShylovich** [comment] 2017-02-01 12:19
@pkozlowski-opensource support request

**Comment by IgorMinar** [comment] 2017-12-22 03:25
dupe of #19841

**Closed by IgorMinar** 2017-12-22 03:25 UTC
Labels: comp: packaging
