### ISSUE TITLE
[aio] Update the documentation to remove reference to the deprecated template attribute

### ISSUE THREAD

**Issue by happygrammer** [angular/angular#16425] opened 2017-04-28 23:16 UTC
**I'm submitting a ...**  (check one with "x")

	[x ] bug report => search github for a similar issue or PR before submitting
	[ ] feature request
	[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
	

**Current behavior**

It works well when using the template directive.
It does not work properly when using the ng-template directive.
And the official document does not match the console log message either.

1. console log message

The template property works correctly when used as an attribute. (Even if the console log message is marked as deprecated in the display)

Chrome's console message looks like this:

	emplate parse warnings:
	The template attribute is deprecated. Use an ng-template element instead. ("
	<div [WARNING ->]template="ngFor let item of items; let i=index">
	{{i+1}} | {{item?.title}} | {{item?.length | num"): ng:///AppModule/TemplateNgforComponent.html@1:7
	 
2. official document  ([link](https://angular.io/docs/ts/latest/guide/structural-directives.html#!#ngFor))

The console error message says Warning and should not be used, and the official document says to use the Template attribute. (It seems to be a content error.)

```
<div template="ngFor let hero of heroes; let i=index; let odd=odd; trackBy: trackById" [class.odd]="odd">
  ({{i}}) {{hero.name}}
</div>
```

**Expected behavior**

1. The part of the official document that uses the template attribute needs to be modified with the ng-template attribute.
2. I only want to use ng-template in the source code and the template should be deprecated.

**Minimal reproduction of the problem with instructions**

my code
	
	import { Component } from '@angular/core';
	
	interface Item {
	  title: string;
	  length: string;
	}
	@Component({
	  selector: 'app-template-ngfor',
	  template: `
	  <div template="ngFor let item of items; let i=index">
	    {{i+1}} | {{item?.title}} | {{item?.length | number }}km
	  </div>
	  <div ng-template="ngFor let item of items; let i=index;">
	    {{i+1}} | {{item?.title}} | {{item?.length | number }}km
	  </div>`
	})
	export class TemplateNgforComponent {	
	  items: Item[] = [];
	  constructor() {
	    this.items.push({ 'title': 'one', 'length': '6600' });
	    this.items.push({ 'title': 'two', 'length': '6400' });
	    this.items.push({ 'title': 'trhee', 'length': '6200' });
	  }	
	}

console.log

		emplate parse warnings:
	The template attribute is deprecated. Use an ng-template element instead. ("
	  <div [WARNING ->]template="ngFor let item of items; let i=index">
	    {{i+1}} | {{item?.title}} | {{item?.length | num"): ng:///AppModule/TemplateNgforComponent.html@1:7

chrome page result (template result)

	1 | one | 6,600km
	2 | two | 6,400km
	3 | trhee | 6,200km
	NaN | | km

- Unlike the instructions to use the Ng-template. The template directive will work, but the ng-template directive will not work.

**What is the motivation / use case for changing the behavior?**

For consistency, only the ng-template attribute should be displayed correctly, and the template attribute should be deprecated. I hope you'll see something like this:

	NaN | | km
	1 | one | 6,600km
	2 | two | 6,400km
	3 | trhee | 6,200km

**Please tell us about your environment:**

* **Angular version:** 4.1.0

* **Browser:** chrome Version 58.0.3029.81 (64-bit)
 
* **Language:** Typescript  2.3.1

* **Node (for AoT issues):** `node --version` =  6.10.0

**Comment by trotyl** [comment] 2017-04-29 07:12
As per [change log](https://github.com/angular/angular/commit/bf8eb41):

> `template` tags (or elements with a `template` attribute) should be rewritten
as a `ng-template` tag

The `template` attribute has been deprecated (and will be removed) without a corresponding attribute alternative. **You should just use `ng-template` as a tag.** Discussion can be found in https://github.com/angular/angular/issues/11994.

So by design there has never been a `ng-template` attribute. I guess **the documentation should be blame for preserving the `template` attribute stuff**.

BTW, the `template` attribute is never a part of any directive, just a special attribute recognize by Angular, like `ngNonBindable`.

**Comment by wardbell** [comment] 2017-06-22 06:57
The docs have been corrected re `ngTemplate` since this issue was created. Closing.

**Closed by wardbell** 2017-06-22 06:57 UTC
Labels: comp: docs, type: bug
