### ISSUE TITLE
Problem with inputs checked

### ISSUE THREAD

**Issue by niquenen** [angular/angular#48718] opened 2023-01-12 15:36 UTC
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

A problem occurs with inputs that are checked when they should not to be. The issue can be reproduced with a component that contains a list of values that must be applied when displayed.

Component containing the list of elements and a method to update a state:

```typescript
import { Component } from '@angular/core';

@Component({
  selector: 'app',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent {
  public readonly elements: Array<boolean> = [true, false, false, false];

  public update(event: Event, index: number): void {
    let element: HTMLInputElement = event.target as HTMLInputElement;

    this.elements[index] = element.checked;
  }
}
```
The associated template:

```html
<div *ngFor="let element of elements; index as i">
  <span>#{{ i.toString().padStart(2, '0') }}</span>
  <div>
    <input
      type="checkbox"
      role="switch"
      [id]="'inputGroupSwitch-' + i.toString()"
      (change)="update($event, i)"
      [checked]="element"
    />
    <label [for]="'inputGroupSwitch-' + i.toString()">
      Status : {{ element.toString() }}
    </label>
  </div>
</div>
```

When the first item is unchecked by a click, the value is correctly set to `false`. But when the state of the first one will change again to `true`, the second element of the list will have its checkbox checked (its value is still set to `false` in the array).

You can find below a [demo](https://stackblitz.com/edit/c5a938f8-e80d-4245-89b9-de05517abcb5) step by step.

1. Load the page.

![Screenshot 2023-01-12 at 16 30 13](https://user-images.githubusercontent.com/7528452/212109635-8cead047-4699-4dfa-9a3e-706a49c66474.png)

2. Click to the first element.

![Screenshot 2023-01-12 at 16 30 24](https://user-images.githubusercontent.com/7528452/212109639-6cfb7261-32ce-46c8-9f2d-3abd74aa7a20.png)

3. Click to the first element.

![Screenshot 2023-01-12 at 16 30 29](https://user-images.githubusercontent.com/7528452/212109642-9e8ef87d-6c51-40c2-8cc2-0327906b34ca.png)

If you continue to click on the first element, the third element will be modified, then the fourth, etc.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/c5a938f8-e80d-4245-89b9-de05517abcb5

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.0.5
Node: 18.12.1
Package Manager: npm 8.19.2
OS: darwin arm64

Angular: 15.1.0
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1501.0
@angular-devkit/build-angular   15.1.0
@angular-devkit/core            15.1.0
@angular-devkit/schematics      15.0.5
@angular/cli                    15.0.5
@schematics/angular             15.0.5
rxjs                            7.5.7
typescript                      4.8.4
```

### Anything else?

This behavior has been observed on version 15 and has not been tried on previous releases. Furthermore, is this a normal behavior, or is it the result of a misuse?

**Comment by pkozlowski-opensource** [comment] 2023-01-12 15:54
This is essentially the same issue as #45647 - you need to use the https://angular.io/api/common/NgForOf#ngForTrackBy

Closing as a duplicate of #45647 but will probably create another canonical issue to capture this relatively common confusion point (a collection of primitive values and the default trackBy)

**Closed by pkozlowski-opensource** 2023-01-12 15:54 UTC
