### ISSUE TITLE
Add equal function to input signal's options 

### ISSUE THREAD

**Issue by olegdunkan** [angular/angular#57304] opened 2024-08-08 08:48 UTC
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

Let say we have to components: one watch for _x_ dimension, other watch for _y_ dimension.

```
interface Point {
  x:number;
  y:number;
}

@Component({
  selector: 'x-comp',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    @let p = point();
    X {{ p.x }}
    I need info about y coordinate {{p.y}}  `,
})
export class X {
  point = input<Point>({x:0, y:0}, {equal:(prev, next) => prev.x-next.x !== 0}); mark view dirty only when x is changed
}

@Component({
  selector: 'y-comp',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    @let p = point();
    Y {{ p.y }}
    I need info about x coordinate {{p.x}}
  `,
})
export class Y {
  point = input<Point>({x:0, y:0}, {equal:(prev, next) => prev.y-next.y !== 0}); //mark view dirty only when y is changed
}


@Component({
  selector: 'app-root',
  standalone: true,
  template: `
    <x-comp [point]="motion()" />
    <y-comp [point]="motion()" />
  `,
  imports: [X, Y],
})
export class AppComponent {
  motion = signal<Point>({x:0, y:0});
  constructor() {}
  move(x:number, y:number) {
    this.motion({x, y});
  }
}
```

### Proposed solution

Add **equal** function to input signal's options, like for writable or computed signal.

### Alternatives considered
I can do so in the case of dimensions:
```
@Component({
  selector: 'app-root',
  standalone: true,
  template: `
    <x-comp [x]="x()" />
    <y-comp [y]="y()" />
  `,
  imports: [X, Y],
})
export class AppComponent {
  motion = signal<Point>({x:0, y:0});
  x = computed(() => this.motion().x);
  y = computed(() => this.motion().y);
  constructor() {}
  move(x:number, y:number) {
    this.motion({x, y});
  }
}
```
but in that case I am losing info about second coordinate.

**Comment by JeanMeche** [comment] 2024-08-08 09:34
Hi, this is a duplicate of #54111.

**Closed by JeanMeche** 2024-08-08 09:34 UTC
