### ISSUE TITLE
Uncaught Error: JIT compiler unavailable form angular 8 to angular 12 upgrade.

### ISSUE THREAD

**Issue by manpreet414** [angular/angular#46196] opened 2022-05-31 11:20 UTC
### Which @angular/* package(s) are the source of the bug?

upgrade

### Is this a regression?

No

### Description

After upgrading our library to Angular 12  i am facing facing the error `Uncaught Error: JIT compiler unavailable`.

Its working fine when i use ng serve but when i generate production build and tried to run application in browser then got error in console. 

### Please provide the exception or error you saw

```true
main-es2015.a138ebe376ca332c9848.js:1 Uncaught Error: JIT compiler unavailable
    at gr (main-es2015.a138ebe376ca332c9848.js:1)
    at Module.eC (main-es2015.a138ebe376ca332c9848.js:1)
    at main-es2015.a138ebe376ca332c9848.js:1
    at Object.hhfa (main-es2015.a138ebe376ca332c9848.js:1)
    at n (runtime-es2015.d4de5c2d046f72ecc864.js:1)
    at Module.zUnb (main-es2015.a138ebe376ca332c9848.js:1)
    at n (runtime-es2015.d4de5c2d046f72ecc864.js:1)
    at Object.1 (main-es2015.a138ebe376ca332c9848.js:1)
    at n (runtime-es2015.d4de5c2d046f72ecc864.js:1)
    at f (runtime-es2015.d4de5c2d046f72ecc864.js:1)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 12.2.0
Node: 14.15.5
Package Manager: npm 6.14.11
OS: linux x64

Angular: 12.2.0
... cli, common, compiler, compiler-cli, core, forms
... language-service, material, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.800.6
@angular-devkit/build-angular   0.800.6
@angular-devkit/core            8.0.6
@angular-devkit/schematics      12.2.0
@angular/animations             12.2.16
@angular/cdk                    12.2.13
@angular/fire                   5.4.2
@schematics/angular             12.2.0
rxjs                            6.5.2
typescript                      4.2.3
```

**Comment by pkozlowski-opensource** [comment] 2022-05-31 11:48
This is a duplicate of #43415. Also see more discussion in #44660.

**Closed by pkozlowski-opensource** 2022-05-31 11:48 UTC
