### ISSUE TITLE
Babel generated code: ReflectionCapabilities DELEGATE_CTOR cannot detect whether class has own constructor or not 

### ISSUE THREAD

**Issue by stalniy** [angular/angular#15212] opened 2017-03-16 18:43 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
```js
class Base {
  static get parameters() {
     return [[Service]];
  }

  constructor(service) {
    this.service = service
  }
}

class Child extends Base {
  load() {
    return this.service.load()
  }
}

@Component(...)
class App {
  static get parameters() {
    return [[Child]]
  }

  constructor(service) {
     this.service = service
  }

  ngOnInit() {
    this.service.load()
  }
}
```
Fails with `Cannot read property 'load' of undefined`

**Expected behavior**
`Service` is successfully injected into `Child` class and no error is thrown

**Minimal reproduction of the problem with instructions**
Reproduction is in `Current behavior`. I did some investigation and found out that babel generate this for class without constructor:
```js
function Child() {
  babelHelpers.classCallCheck(this, Child);
  return babelHelpers.possibleConstructorReturn(this, (Child.__proto__ || Object.getPrototypeOf(Child)).apply(this, arguments));
}
```
And this is the regexp which checks whether class doesn't have own constructor:
```js
var DELEGATE_CTOR = /^function\s+\S+\(\)\s*{\s*("use strict";)?\s*(return\s+)?\S+\.apply\(this,\s*arguments\)/;
```

**What is the motivation / use case for changing the behavior?**
It's useful when injected services from parent class can be injected into `Child` by default without additional coding

**Please tell us about your environment:**

* **Angular version:** 2.0.X
2.4.8

* **Browser:** all
 
* **Language:** ES6/7

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment] 2017-03-16 18:46
Looks like duplicate of https://github.com/angular/angular/issues/14944

**Comment by DzmitryShylovich** [comment] 2017-03-22 17:41
@stalniy see https://github.com/angular/angular/issues/14944#issuecomment-288478394

**Comment by stalniy** [comment] 2017-03-23 06:30
All that workarounds doesn't work for me. Basically what works if I manually set parameters of Child class to paremeters of Base class. But this is a hack :)

```js
class Child extends Base {
  static parameters = Base.parameters
}
```

But I don't understand why it was decided not to use parents/inherited `parameters` by default as Child needs to satisfy all dependencies for parent via `super`. In case of child wants to use another service implementation or whatever it's still possible to do this. 



So why angular team decided not to pass

**Comment by stalniy** [comment] 2017-03-23 06:40
This what I found in `ReflectionCapabilities` class. This part prevents to read parents parameters and method `_ownParameters` returns an empty array:
```js
    // Prefer the direct API.
    if ((<any>type).parameters && (<any>type).parameters !== parentCtor.parameters) {
      return (<any>type).parameters;
    }
```

So, then in another part there is a check:
```js
let parameters = this._ownParameters(type, parentCtor);
    if (!parameters && parentCtor !== Object) {
      parameters = this.parameters(parentCtor);
    }

```

parameters equals empty array so parent's parameters are ignored and nothing eventually inhected

**Comment by alxhub** [comment] 2020-05-28 21:21
This issue relates to how an Angular application is built, in a way that we haven't seen before. Manually manipulating `parameters` too is something that's outside our "supported" build configuration.

I've tagged this as a use-case so we can discuss the problem and potential solutions.

**Comment by pkozlowski-opensource** [comment] 2022-09-21 14:46
I'm going to close this issue as we don't  intend to support manipulating parameters.

**Closed by pkozlowski-opensource** 2022-09-21 14:46 UTC
Labels: freq1: low, comp: core, comp: compiler, core: di, type: use-case, compiler: jit
