### ISSUE TITLE
InjectFlags does not work in NodeInjector

### ISSUE THREAD

**Issue by vthinkxie** [angular/angular#41577] opened 2021-04-12 10:13 UTC
# 🐞 bug report

### Affected Package

`@angular/core`

### Is this a regression?

not sure

### Description

NodeInjector ignore InjectFlags values, there is no way to get parent token via `injector.get` in NodeInjector

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-ivy-uxqxpe?file=src%2Fapp%2Fhello.component.ts

<pre>
<code>
  constructor(private injector: Injector) {
    const currentInjector = this.injector;
    const parentInjector = this.injector.get(
      Injector,
      null,
      InjectFlags.SkipSelf
    );
    console.log(currentInjector, parentInjector);
    // the lView of parentInjector should be `LRootView` here
  }

</code></pre>

the `flags` was defined in both `getOrCreateInjectable` and `Injector`, but was ignored inside `NodeInjector` 

https://github.com/angular/angular/blob/61bfa3d9dfc7c9daecde098aca595b731c3312a0/packages/core/src/render3/di.ts#L696-L698

https://github.com/angular/angular/blob/61bfa3d9dfc7c9daecde098aca595b731c3312a0/packages/core/src/render3/di.ts#L408-L410

https://github.com/angular/angular/blob/61bfa3d9dfc7c9daecde098aca595b731c3312a0/packages/core/src/di/injector.ts#L69-L70

## 🌍  Your Environment

latest

**Comment by AndrewKushnir** [comment] 2021-04-13 00:25
Closing as a duplicate of #31776.

**Closed by AndrewKushnir** 2021-04-13 00:25 UTC
Labels: P3, comp: core, core: di
