### ISSUE TITLE
ngClass documentation inconsistent or misuse

### ISSUE THREAD

**Issue by Delagen** [angular/angular#8165] opened 2016-04-21 11:14 UTC
This code example
```
<label [class.has-error]="!username.valid">
			<div>Login</div>
			<input type="text" ngControl="username" #username="ngForm" class="form-control" placeholder="Login" required/>
</label>
```
 Error: Uncaught (in promise): No provider for ControlContainer! (NgControlName -> ControlContainer)

but when i use
```
[ngClass]="{'has-error':!username.valid}"
```
or simply add ngClass

```
[ngClass] [class.has-error]="!username.valid"
```
works as expected, but in docs no any word about ngClass requirement

**Comment by zoechi** [comment] 2016-04-21 11:19
I can't see how the the error message and `ngClass` are related. Can you create a Plunker http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5_ that allows to reproduce?

**Comment by ericmartinezr** [comment] 2016-04-21 11:48
You're seeing this error https://github.com/angular/angular/issues/6374

**Comment by pkozlowski-opensource** [comment] 2016-05-13 00:15
Closing as duplicate of #6374, thnx @ericmartinezr

**Closed by pkozlowski-opensource** 2016-05-13 00:15 UTC
