### ISSUE TITLE
first ngc after add @angular/bazel throw error and pollute console on windows 10

### ISSUE THREAD

**Issue by elvisbegovic** [angular/angular#30348] opened 2019-05-09 08:02 UTC
# 🐞 bug report

### Affected Package
Caused by `ngc` at postinstall of @angular/bazel install

### Description

Following [aio:bazel doc](https://next.angular.io/guide/bazel) to add bazel in an existing CLI application project on Windows

## 🔬 Minimal Reproduction
On Windows10 platform:
1. Add `ng add @angular/bazel@next --name ap`
2. At first ngc (postinstall:`ngc -p ./angular-metadata.tsconfig.json`) it throw error (see below)

## 🔥 Exception or Error
Console output +700 lines of error and `Exit status 1`

> node_modules/@angular/cdk/schematics/ng-generate/drag-drop/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.spec.ts(4,10): error TS1003: Identifier expected.
> node_modules/@angular/cdk/schematics/ng-generate/drag-drop/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.spec.ts(4,30): error TS1109: Expression expected.
> ... +700 lines

[See complete output that pollute console >700 lines](https://pastebin.com/9d1WnDiD)

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.0.0-rc.3
Node: 12.2.0
OS: win32 x64
Angular: 8.0.0-rc.3
... animations, bazel, cli, common, compiler, compiler-cli, core
... forms, language-service, platform-browser
... platform-browser-dynamic, router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.0-rc.3
@angular-devkit/build-angular     0.800.0-rc.3
@angular-devkit/build-optimizer   0.800.0-rc.3
@angular-devkit/build-webpack     0.800.0-rc.3
@angular-devkit/core              8.0.0-rc.3
@angular-devkit/schematics        8.0.0-rc.3
@angular/cdk                      8.0.0-rc.0
@angular/http                     8.0.0-beta.10
@angular/material                 8.0.0-rc.0
@angular/pwa                      0.800.0-rc.3
@ngtools/webpack                  8.0.0-rc.3
@schematics/angular               8.0.0-rc.3
@schematics/update                0.800.0-rc.3
rxjs                              6.5.1
typescript                        3.4.5
webpack                           4.30.0
</code></pre>

**Anything else relevant?**
We should have smaller/better output in console. 

For fix/successful ngc build I think we are blocked by https://github.com/angular/angular/issues/18810 

cc @filipesilva

**Comment by filipesilva** [comment] 2019-05-09 12:31
cc @kyliau

**Comment by rerion** [comment] 2019-05-30 10:58
This problem persists @ version 8.0.0

I think the cause is bazel trying to compile schematics auxiliary files with .ts extension.

Substituting `node_modules/@angular/core/schematics/**` -> `node_modules/@angular/**/schematics/**` inside `angular-metadata.tsconfig.json` 
to catch all angular schematics in excluded globs fixes the problem

**Comment by AndrewKushnir** [comment] 2020-10-29 22:36
Hi,

Bazel builder and schematics were deprecated, so I'm closing this ticket. You can find more information about this on the [Deprecated APIs and features page](https://angular.io/guide/deprecations#bazel-builder-and-schematics) and in the [migration guide](https://github.com/angular/angular/blob/master/packages/bazel/src/schematics/README.md).

Thank you.

**Closed by AndrewKushnir** 2020-10-29 22:36 UTC
Labels: comp: bazel
