### ISSUE TITLE
Getting a warning in console when compiling Angular 4 rc 2

### ISSUE THREAD

**Issue by rahulrsingh09** [angular/angular#14898] opened 2017-03-03 09:28 UTC
The conponents works fine when compiling but there is a warning displayed in the console 

WARNING in ./~/@angular/core/@angular/core.es5.js
6857:19-40 Critical dependency: the request of a dependency is an expression

WARNING in ./~/@angular/core/@angular/core.es5.js
6883:19-106 Critical dependency: the request of a dependency is an expression

This only comes when i am running angular4 RC .

**Comment by DzmitryShylovich** [comment] 2017-03-03 09:31
what rc version do you use?

**Comment by rahulrsingh09** [comment] 2017-03-03 09:33
@DzmitryShylovich I am using Angular 4.0.0-rc.2

**Comment by csentis** [comment] 2017-03-03 17:42
@rahulrsingh09 In case you are on webpack, a post from @Martin-Wegner at the very bottom of this issue could help you: angular/angular#11580.

**Comment by rahulrsingh09** [comment] 2017-03-03 18:50
@csentis  I am using Angular Cli how and where to update the peice of code @Martin-Wegner has pointed out to

**Comment by tonimitrevski** [comment] 2017-03-03 18:57
replace this in the webpack plugins

new webpack.ContextReplacementPlugin(
  /angular(\\|\/)core(\\|\/)(esm(\\|\/)src|src)(\\|\/)linker/,
  path.resolve(__dirname, '../src')
)

with this 

new webpack.ContextReplacementPlugin(
  /angular(\\|\/)core(\\|\/)@angular/,
  path.resolve(__dirname, '../src')
)

and will be work fine

**Comment by rahulrsingh09** [comment] 2017-03-03 19:02
@tonimitrevski I donot have webpack plugins in my project structure 

![image](https://cloud.githubusercontent.com/assets/17721520/23565023/040d7c62-0072-11e7-97b3-1b1adf45a95f.png)

**Comment by csentis** [comment] 2017-03-04 00:58
@rahulrsingh09 I am not familiar with the angular-cli setup. But as explained [here](https://github.com/angular/angular-cli/issues/1656#issuecomment-240171375) by @hansl, the angular-cli setup does not include an exposed webpack configuration.

Since a place to put the snippet above/ plugin config somewhere (usually a place like webpack.conf.js), it seems you have to wait for an appropriate fix instead of a webpack context replacement configuration entry.

**Comment by rahulrsingh09** [comment] 2017-03-04 06:45
@csentis okay thanks But as cli is the official Build tool for angular hope they come up with a solution sooner than later :)

**Comment by DzmitryShylovich** [comment] 2017-03-04 07:30
@rahulrsingh09 if this is a cli issue please re-open it on https://github.com/angular/angular-cli/issues

**Comment by rahulrsingh09** [comment] 2017-03-04 07:35
@DzmitryShylovich I am only getting this issue after upgrading to Angular 4 Rc1 and Rc2

**Comment by Martin-Wegner** [comment] 2017-03-06 08:18
In common this issue is a duplicate of https://github.com/angular/angular/issues/11580

**Comment by rahulrsingh09** [comment] 2017-03-06 08:33
@Martin-Wegner But there is not fix its more of less of a hack i feel

**Comment by Martin-Wegner** [comment] 2017-03-06 08:42
@rahulrsingh09 that's the reason why https://github.com/angular/angular/issues/11580 is still open :) But a duplicate issue does not help anyone...

**Comment by pkozlowski-opensource** [comment] 2017-03-09 16:32
Thanks for reporting this issue. However this issue is a duplicate of an existing issue #11580. Please subscribe to that issue for future updates.

**Closed by pkozlowski-opensource** 2017-03-09 16:32 UTC

**Comment by roshan3133** [comment] 2017-03-10 10:20
I am also getting same warning.

**Comment by jensbodal** [comment] 2017-03-30 09:48
Fixed with two changes.  

One recommended in other mentions of this issue:

```
    new webpack.ContextReplacementPlugin(
      /angular(\\|\/)core(\\|\/)@angular/,
      helpers.root('./src'),
      {}
    )
```

`helpers.root` taken from https://angular.io/docs/ts/latest/guide/webpack.html

And then the change which fixed my dependency which is requested as an expression, taken from the `webpack.config.js` by building an empty angular4 app (`ng new --ng4 whatever`) and ejecting it (`ng eject`):

```
module.exports = {
  resolve: {
    extensions: [
      '.ts',
      '.js'
    ],
    modules: [
      helpers.root('node_modules')
    ]
  },
  resolveLoader: {
    modules: [
      helpers.root('node_modules')
    ]
  },
}
```

**Comment by AshuSingh07** [comment] 2017-06-23 21:09
This problem is with angular 1.3.X. or later version.
 uninstall your angular version  and update with @angular1.0.0

npm uninstall -g @angular/cli
npm cache clean
npm install -g @angular/cli@1.0.0

**Comment by sollenne** [comment] 2017-06-30 15:59
@AshuSingh07 Don't do that.

**Comment by lohiarahul** [comment] 2017-08-04 00:53
> @rahulrsingh09 In case you are on webpack, a post from @Martin-Wegner at the very bottom of this issue could help you: angular/angular#11580.

https://github.com/angular/angular/issues/11580#issuecomment-282705332 This?

**Comment by csentis** [comment] 2017-08-04 18:30
@lohiarahul exactly.

**Comment by duhaime** [comment] 2017-10-22 23:42
If you're having this trouble and are using the angular cli, you should be able to acquire a `webpack.config.js` file by running `ng eject` from the root of your project. (This is similar to ejecting a project made with create-react-app, if that's familiar.) Once you have a webpack config file, you should be able to modify the `plugins` attribute of that file in the way @jensbodal shows above...

**Comment by erbsenkoenig** [comment] 2017-10-23 02:02
Ich kehre zurück am 01.11.2017.

Ich werde Ihre Nachricht nach meiner Rückkehr beantworten.
In dringenden Fällen senden Sie bitte eine Kopie Ihrer E-Mail für
technische Angelegenheiten an entwicklung@arxes-tolina.de, ansonsten an
info@arxes-tolina.de. Ein anderer Mitarbeiter wird sich dann Ihrer E-Mail
annehmen.


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re:
[angular/angular] Getting a warning in console when compiling Angular 4 rc
2 (#14898)" gesendet am 23.10.2017 01:43:33.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während
diese Person abwesend ist.

**Comment by httpete** [comment] 2017-11-07 23:11
This worked for me for angular 5. 
`            new webpack.ContextReplacementPlugin(
                /angular(\\|\/)core(\\|\/)/,
                path.resolve(__dirname, './src')
            ),`

**Comment by ShinDarth** [comment] 2017-11-17 13:20
@httpete  I have the same issue just after upgrading to Angular 5. But I don't understand where to place your solution

**Comment by Martin-Wegner** [comment] 2017-11-17 13:25
@ShinDarth for Angular 5 you should add this to the webpack plugins array:

```
    // Workaround for https://github.com/angular/angular/issues/11580
    new webpack.ContextReplacementPlugin(
      // The (\\|\/) piece accounts for path separators in *nix and Windows
      /angular(\\|\/)core(\\|\/)(@angular|esm5)/,
      path.resolve(__dirname, '../src')
    ),
```

**Comment by ShinDarth** [comment] 2017-11-17 13:34
@Martin-Wegner 
I understand but where is the webpack plugins array located?

**Comment by Martin-Wegner** [comment] 2017-11-17 13:42
@ShinDarth in your webpack config files... Something like
```
var path = require('path');
var webpack = require('webpack');

var ExtractTextPlugin = require('extract-text-webpack-plugin');
var HtmlWebpackPlugin = require('html-webpack-plugin');

module.exports = {
  entry: {
    app: path.resolve(__dirname, '../src/main.ts'),
    polyfills: path.resolve(__dirname, '../src/polyfills.ts'),
    vendor: path.resolve(__dirname, '../src/vendor.ts')
  },

  module: {
    rules: [
...
    ]
  },

  plugins: [
    new webpack.optimize.CommonsChunkPlugin({
      name: ['app', 'vendor', 'polyfills']
    }),

    // Workaround for https://github.com/angular/angular/issues/11580
    new webpack.ContextReplacementPlugin(
      // The (\\|\/) piece accounts for path separators in *nix and Windows
      /angular(\\|\/)core(\\|\/)(@angular|esm5)/,
      path.resolve(__dirname, '../src')
    ),
...
  ],

  resolve: {
    extensions: ['.ts', '.js']
  }
};
```

**Comment by ghiscoding** [comment] 2017-11-23 22:50
@Martin-Wegner, I believe that the problem that @ShinDarth is facing is that he's probably using Angular-CLI (which I also do) and we don't have access to the WebPack config as it is hidden by Angular-CLI. So I'm not sure how to fix this either. Any suggestions with Angular-CLI? I have updated to latest version of Angular, Angular-CLI and TypeScript and I get that error
```bash
Critical dependency: the request of a dependency is an expression
```

**Comment by ileler** [comment] 2017-12-13 07:26
@ghiscoding yes,you are right.I have the same issue just after upgrading to Angular 5 with Angular-CLI.and i also can't found webpack.config.js to fix this problem.

**Comment by lylwanan** [comment] 2017-12-28 02:33
`new webpack.ContextReplacementPlugin(
      /angular(\\|\/)core(\\|\/)(esm(\\|\/)src|src)(\\|\/)linker/,
      path.resolve(__dirname, './src')
    )`
i used those code and program can work fine!

**Comment by irejwanul** [comment] 2017-12-29 16:29
Mine worked with the following block of code in Plugins Array. I have tested both angular 4.4.5 and angular > 5.0.0  
new webpack.ContextReplacementPlugin( /angular(\\|\/)core(\\|\/)(esm5(\\|\/)ClientApp|ClientApp)(\\|\/)linker/, path.resolve(__dirname, './ClientApp') ),

**Comment by crowmagnumb** [comment] 2018-01-18 18:16
I upgraded from angular 4.4.6 to 5.2.1 and I had to modify my ContextReplacementPlugin regex according to the solution by @u4bi namely...

```
        new webpack.ContextReplacementPlugin(
            /\@angular(\\|\/)core(\\|\/)esm5/,
            path.resolve(__dirname, "./src")
        ),
```

... and that worked for me.

**Comment by ashokmachineni** [comment] 2018-05-08 12:02
Just run commands npm update and npm install and restart your editor or app

**Comment by oshobeski** [comment] 2018-05-17 12:02
I recently upgraded to angular 5 and latest webpack, i have multiple lazy loaded app which was built in angular 4 and older web pack version.. when loading those angular 4 applications in my latest setup im getting the error 

./node_modules/@angular/core/@angular/core.es5.js module is not found

here i used the below fix 
new webpack.ContextReplacementPlugin(
      // The (\\|\/) piece accounts for path separators in *nix and Windows
      /angular(\\|\/)core(\\|\/)(@angular|esm5)/,
      path.resolve(__dirname, './src')
    )

which resolves the above issue(./node_modules/@angular/core/@angular/core.es5.js) and ended with new issue 
 __dirname/src lazy recursive          module not found

Thanks in Advance!!

**Comment by punitkulli** [comment] 2018-06-08 05:52
I am just using angular-4-data-table and came across these warnings during execution and my index.html showing blank window in the browser 

WARNING in ./node_modules/angular-4-data-table/node_modules/@angular/core/@angular/core.es5.js
5659:15-36 Critical dependency: the request of a dependency is an expression

WARNING in ./node_modules/angular-4-data-table/node_modules/@angular/core/@angular/core.es5.js
5675:15-102 Critical dependency: the request of a dependency is an expression

**Comment by jordangotbaum** [comment] 2018-07-12 16:34
For those of you confused by the various different paths, look at the path of the error message you're getting. In my case it was:

WARNING in ./node_modules/@angular/core/fesm5/core.js

Your context replacement regex should match that path:

`new webpack.ContextReplacementPlugin(
      /@angular(\\|\/)core(\\|\/)fesm5/,
      utils.root('src'),
      {} // TODO: Enter route map here.
 ),`

**Comment by BruneXX** [comment] 2018-10-10 20:08
Hi @crowmagnumb that's exactly my configuration, please see:

`new ContextReplacementPlugin(
        /**
         * The (\\|\/) piece accounts for path separators in *nix and Windows
         */
        /\@angular(\\|\/)core(\\|\/)esm5/,
        helpers.root('src'), // location of your src
        {
          /**
           * your Angular Async Route paths relative to this root directory
           */
        }
      ),`

But I'm still receiving two warnings related:

> WARNING in ./node_modules/@angular/core/fesm5/core.js 4994:15-102

any thoughts on this?

will be appreciated, thanks!

**Comment by crowmagnumb** [comment] 2018-10-10 21:01
No sorry @BruneXX I don't. In addition, I have since moved on to Angular 6 and stopped using webpack in favor of angular cli.

**Comment by zymr-keshav** [comment] 2018-10-26 10:09
Is there any solution without altering *webpack.config.js* because changing in **webpack.config.js** will cost to loss `ng serve` command after that. we need to do `ng eject` to see the *webpack.config.js*

**Comment by liyokuna** [comment] 2018-12-11 09:20
@BruneXX did you manage to corect that issue ?
I want to keep using webpack and i am suing angular 7.
