### ISSUE TITLE
Issues with parallel build using ivy

### ISSUE THREAD

**Issue by cromefire** [angular/angular#32431] opened 2019-08-31 14:44 UTC
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

Kind of, this worked without ivy

### Description

It seems like the cli argues with itself, because both instances want to create the same directory and don't check if it already exists:
```
ERROR in EEXIST: file already exists, mkdir '/path/to/project/node_modules/@angular/core/__ivy_ngcc__'
```
or
```
ERROR in Tried to overwrite /path/to/project/node_modules/@angular/core/core.d.ts.__ivy_ngcc_bak with an ngcc back up file, which is disallowed.
```

## 🔬 Minimal Reproduction

Build app and universal server:
```
ng build --prod & ng run <project>:server:production
```

## 🔥 Exception or Error

```
ERROR in EEXIST: file already exists, mkdir '/path/to/project/node_modules/@angular/core/__ivy_ngcc__'

ERROR in Tried to overwrite /path/to/project/node_modules/@angular/core/core.d.ts.__ivy_ngcc_bak with an ngcc back up file, which is disallowed.
```

**The app/repo must be clean (not already built; to reproduce it again remove `node_modules` and `yarn install` again)**

## 🌍 Your Environment

```
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 8.3.2
Node: 12.9.1
OS: linux x64
Angular: 8.2.4
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router, service-worker

Package                                    Version
--------------------------------------------------------------------
@angular-devkit/architect                  0.803.2
@angular-devkit/build-angular              0.803.2
@angular-devkit/build-optimizer            0.803.2
@angular-devkit/core                       8.3.2
@angular-devkit/schematics                 8.3.2
@angular/cdk                               8.1.2
@angular/cli                               8.3.2
@angular/material                          8.1.2
@angular/pwa                               0.802.1
@nguniversal/express-engine                8.1.1
@nguniversal/module-map-ngfactory-loader   8.1.1
@schematics/angular                        8.2.1
@schematics/update                         0.803.2
rxjs                                       6.5.2
typescript                                 3.5.3
webpack                                    4.39.1
```

**Anything else relevant?**

I hope this it the right tracker

**Comment by alxhub** [comment] 2019-09-05 22:41
`ngcc` should give a warning if it's being used in the same `node_modules` twice (or more).

**Comment by coryrylan** [comment] 2019-11-26 21:11
Ran into this as well, adding ngcc in the post install script fixed it.  https://github.com/vmware/clarity/blob/d160f0c9fe5ca89388f054c02b9e18fdd18631b1/package.json#L9

**Comment by FrozenPandaz** [comment] 2019-11-29 17:58
@alan-agius4 @alxhub

I want to raise some priority on this issue.

Nx is affected by this issue. We are currently planning to workaround the issue by adding the postinstall to all Nx workspaces because in CI, the case will most likely be:

```sh
checkout commit

yarn

yarn affected:build --parallel
```

Is there anything that can be done here short term?

**Comment by alan-agius4** [comment] 2019-12-03 18:26
@FrozenPandaz, the workaround for this is to use the postinstall hook.

**Comment by IgorMinar** [comment] 2019-12-09 22:29
@gkalpak @petebacondarwin could `ngcc` obtain a per-package [lock/mutex](https://en.wikipedia.org/wiki/Lock_(computer_science)) before it compiles a package?

If a package is "locked" by another `ngcc` instance, the process should wait until the lock is removed before resuming (and short-circuiting) the compilation.

If the package is not unlocked within a reasonable time limit, the compilation should fail with an error message suggesting how to recover (e.g. kill all cli/ngc/ngcc processes, delete `node_modules`, rebuild, and report the timeout to us as a bug).

**Comment by petebacondarwin** [comment] 2019-12-10 08:14
Yeah - we did discuss this last week.
Unfortunately, the CLI integration requires a synchronous call due to the way that webpack/TypeScript works and blocking on a mutex. Node has no facility to block synchronously, without killing the performance by spinning a noop loop.

**Comment by gkalpak** [comment] 2019-12-10 09:53
For the sake of completeness, I'll just mention that (as [brought up before][parallelizing-ngcc]), there are things we can investigate, such as [deasync] or [fibers]+[synchronize] or [sync-rpc] or plain ol' [sync `child_process` methods][node-proc-sync].

There are downsides that we need to look into. For example, the first two options rely on C++ code, so they require compilation `node-gyp` and the last two spawn new processes (which has extra performance and complexity overhead).



[deasync]: https://www.npmjs.com/package/deasync
[fibers]: https://www.npmjs.com/package/fibers
[node-proc-sync]: https://nodejs.org/api/child_process.html#child_process_synchronous_process_creation
[parallelizing-ngcc]: https://hackmd.io/uYG9CJrFQZ-6FtKqpnYJAA#Consideration-parallelizing-the-CLI%E2%80%99s-usage-of-ngcc
[sync-rpc]: https://www.npmjs.com/package/sync-rpc
[synchronize]: https://www.npmjs.com/package/synchronize

**Comment by Anderman** [comment] 2019-12-12 09:38
I Use yarn to install packages. And yarn thinks it must reinstall the packages because __ivy_ngcc__ directory is added to the package. When building, Angular is missing the __ivy_ngcc__ directory and create this directory again. This causes that yarn with ivy is extreem slow in my CI build pipeline.

Is there a workaround?
Is there a way to trick Yarn so it is not installing the package again and removing __ivy_ngcc__?
Or
Is there a way that the build use a different folder for the __ivy_ngcc__ directory?

**Comment by petebacondarwin** [comment] 2019-12-12 09:43
@Anderman  - strictly your question is off-topic for this issue. It is not related to ngcc parallel builds. It would be better to create a new issue with your question. Otherwise issues become confused an unmanageable.

**Comment by alessiostalla** [comment] 2019-12-16 07:53
I'm getting this error in my CI environment since I've started building with Angular.next (9.0.0-rc6 at the moment). The project builds fine on my machine most of the time; sometimes it will error like that and I have to delete node_modules.
Is there a way to turn parallel builds off, if that's the issue?

**Comment by petebacondarwin** [comment] 2019-12-16 09:10
Parallel builds only occur when using ngcc via the command line. So adding `--async false` as a parameter to the ngcc run should do it

**Comment by alessiostalla** [comment] 2019-12-16 15:12
Thanks, but I'm not using ngcc via the command line, I'm using the usual Angular CLI machinery.
I suspect my project is somehow "corrupted" having been migrated over time all the way from Angular 6 to Angular 9 and turned into an "application + library" configuration when there were no schematics yet for that.
This error happens 100% of the time on my CI environment and randomly on my work laptop. So probably I should open a new issue as well.

**Comment by alxhub** [comment] 2020-01-07 23:44
I think we should introduce a lockfile whenever ngcc is invoked (either via CLI or via commandline), and refuse to run if the lockfile is already present (similar to how `git` and many other tools work).

On the `nx` side, if parallel builds are desired, then `node_modules` needs to be updated with the commandline ngcc before invoking any builds. ngcc via the CLI will never be able to support this case.

**Comment by Carniatto** [comment] 2020-02-04 13:48
@FrozenPandaz do we have any updates on how to approach this in an optimal way for Nx monorepo users?

**Comment by petebacondarwin** [comment] 2020-02-04 13:56
@Carniatto - the current approach is to ensure that ngcc has processed all your external dependencies before you begin any parallel builds (e.g. via Nx). You do this by running:

```bash
ngcc --properties es2015 browser module main --first-only --create-ivy-entry-points"
```

Often this is added as a postinstall hook in package.json.

We are also working on a way for the CLI (and so Nx) to incorporate this into its normal flow so that this explicit step may not be needed.

**Comment by wickstargazer** [comment] 2020-02-21 10:51
Hey guys, i am facing the issue that `ngcc --properties es2015 browser module main --first-only --create-ivy-entry-points"` fails when i am using `yarn`. However when using `npm install` it seems to be fine. 

I am using this build [compiler-cli-pr35191-b93c5372e9](https://621158-24195339-gh.circle-artifacts.com/0/angular/compiler-cli-pr35191-b93c5372e9.tgz)

I think its related to the way yarn runs the task? pararell failure? it dies even before i try to build any script. just running the ngcc command. exactly with the error

`ERROR in Tried to overwrite /path/to/project/node_modules/module_name/.d.ts.__ivy_ngcc_bak with an ngcc back up file, which is disallowed.`

sometimes it happens with the `material` module sometimes with the `bootstrap` and keeps happening randomly.

Any heads up or info would be awesomely appreciated

**Comment by petebacondarwin** [comment] 2020-02-21 11:08
What is the actual module that is failing?

**Comment by wickstargazer** [comment] 2020-02-21 12:29
It was happening for `@angular/material` and `ngx-bootstrap`

**Comment by petebacondarwin** [comment] 2020-02-24 09:27
@wickstargazer - it is very difficult to track down the problem without some runnable reproduction. Are you using the latest version of all these libraries (i.e. Angular, Angular Material and ngx-bootrap)? Do you have any symlinks in your node_modules (e.g. do you use lerna, nNx, or similar)? Are you using `yarn link` anywhere? When you say, "if `yarn` fails the first time", what is the error of the first failure? It is not surprising if there is a failure that the node_modules becomes in a corrupt state.

**Comment by vthinkxie** [comment] 2020-03-18 10:40
Hi, we meet this problem too
.__ivy_ngcc_bak with an ngcc back up file, which is disallowed.

**Comment by petebacondarwin** [comment] 2020-03-18 10:48
@vthinkxie - I am working on improving the error messaging for this but I believe that this error is often caused by a library that has overlapping entry-points. In other words, there are two entry-points in a package that refer to the same source-files. This causes ngcc to attempt to process these files twice, once for each entry-point. The workaround is to avoid using one of the two overlapping entry-points and then to tell ngcc to ignore the one you are not using by providing an `ngcc.config.js` file in your project root.

**Comment by vthinkxie** [comment] 2020-03-18 11:01
> @vthinkxie - I am working on improving the error messaging for this but I believe that this error is often caused by a library that has overlapping entry-points. In other words, there are two entry-points in a package that refer to the same source-files. This causes ngcc to attempt to process these files twice, once for each entry-point. The workaround is to avoid using one of the two overlapping entry-points and then to tell ngcc to ignore the one you are not using by providing an `ngcc.config.js` file in your project root.

Thanks for your quick response, I will have a try.

**Comment by petebacondarwin** [comment] 2020-03-25 12:44
Closing as we no support parallel builds via the CLI by running an async ngcc within the `ng build` but before the webpack compilation begins. This async ngcc should be able to pause and wait if another ngcc process is already running.

**Closed by petebacondarwin** 2020-03-25 12:44 UTC
Labels: comp: ngcc, freq1: low, severity2: inconvenient, state: has PR, type: bug/fix

**Comment by Wildhammer** [comment] 2020-04-08 15:23
I have this problem with my angular project which uses npm link to an angular library. This only happens when I have both projects running in development but not when I npm install my angular library in my consumer angular project.

**Comment by petebacondarwin** [comment] 2020-04-08 15:56
@Wildhammer - you have two choices:
* when testing locally, setup the test app to use the TS files from the library directly, avoiding ngcc altogether
* run `npm pack` inside your built library directory and then in your test app `package.json` add a dependency to the generated `.tgz` file.

Ngcc will not follow symlinks.

**Comment by Wildhammer** [comment] 2020-04-08 16:07
@petebacondarwin 
1. can you clarify how this is achieved? currently, I'm importing from the library this way:
    import {NotificationService, PrintService} from '@myorg/common'

2. I can't add a tgz dependency in my package.json this will mess up my CI/CD.

**Comment by Wildhammer** [comment] 2020-04-08 16:18
@wickstargazer in my case when I change something in my library, my consumer project gets stuck in an endless loop of building and failing: 
 `ERROR in Tried to overwrite /path-to-project/components-library/dist/common/lib/core/language/language.service.d.ts.__ivy_ngcc_bak with an ngcc back up file, which is disallowed.
`
