### ISSUE TITLE
Can't show loading indicator during resolving process if Angular is opened via deep link

### ISSUE THREAD

**Issue by hisham** [angular/angular#46091] opened 2022-05-22 03:06 UTC
### Which @angular/* package(s) are relevant/related to the feature request?

router

### Description

This is a duplicate of https://github.com/angular/angular/issues/14064. Perhaps enough time has passed that Angular team is willing to reconsider this feature request. 

When a child route has a resolver, the entire parent component is not rendered until the child resolver resolves. This makes the browser not show anything for a few seconds if the resolving process takes time. Can't show our own loading indicator since the angular app has not rendered yet, and the browser ofcourse doesn't show a loading indicator as well. 

### Proposed solution

Parent component should be rendered if <router-outlet> is not ready yet. 

### Alternatives considered

Create a service to insert loading indicator html in the root html document when a resolver is triggered.

**Comment by atscott** [comment] 2022-05-23 16:29
Also a duplicate of https://github.com/angular/angular/issues/10556. Nothing has changed architecturally in the Router to make this any more feasible. Interleaving activation with resolvers is not something we can do without rethinking the entire architecture of the router navigation execution pipeline. This is being tacked by https://github.com/angular/angular/issues/42953.

**Closed by atscott** 2022-05-23 16:29 UTC
Labels: comp: router
