### ISSUE TITLE
RouterLinkActive directive to apply to children

### ISSUE THREAD

**Issue by wyers** [angular/angular#13533] opened 2016-12-16 22:56 UTC
**I'm submitting a ...**  (check one with "x")
```
[] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
RouterLinkActive directive on a RouterLink's ancestor causes class to be applied to to the ancestor and not the RouterLink.

**Minimal reproduction of the problem with instructions**
something like this maybe
```
<div routerLinkActive="active-link"
        [routerLinkActiveOptions]="{exact: true, applyToChildren: true}">
  <a routerLink="/forgot">forgot</a>
  <a routerLink="/login">login</a>
</div>
```
**What is the motivation / use case for changing the behavior?**
If I have a list of 20 hyperlinks, I would rather not set RouterLinkActive and routerLinkActiveOptions on each one. I would like a flag to apply the class defined in the ancestor class to appropriate routerLink.

**Comment by DzmitryShylovich** [comment] 2016-12-16 22:58
Duplicate of https://github.com/angular/angular/issues/9426

**Comment by jasonaden** [comment] 2017-12-19 19:59
I'm sorry but reported issues require a reproduction of the issue. We suggest using [StackBlitz](https://stackblitz.com/fork/angular-gitter), [Plunker](http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue) or [Github](https://github.com/new).

If this issue persists, please create a reproduction using one of the links above. Describe the difference between the expected and current behavior in a new issue with the reproduction linked.

**Closed by jasonaden** 2017-12-19 19:59 UTC
Labels: comp: router
