### ISSUE TITLE
This component requires inline template type-checking, which is not supported by the current environment.(-998900)

### ISSUE THREAD

**Issue by tonivj5** [angular/angular#40857] opened 2021-02-15 15:55 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/compiler-cli

### Is this a regression?

 Yes, the previous version in which this bug was not present was: yes, this error is only shown when I enable preview ivy language service.

### Description
Angular LS gives me an error, but it doesn't say me what happens or how I can fix it. I have located that error message being produced from here https://github.com/angular/angular/blob/master/packages/compiler-cli/src/ngtsc/typecheck/src/oob.ts#L155-L159

By what I can test it, Angular doesn't like that my component has a generic which extends.

## 🔬 Minimal Reproduction
```ts
@Component({
  selector: 'test-app',
  template: ``,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class Testcomponent<Model extends Object> {}
```
![image](https://user-images.githubusercontent.com/7110786/107967122-0511a580-6fad-11eb-937f-c4623c38267d.png)
![image](https://user-images.githubusercontent.com/7110786/107967094-fe832e00-6fac-11eb-8b41-97e4ee6ca997.png)

This doesn't produce that message error:
```ts
@Component({
  selector: 'test-app',
  template: ``,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class Testcomponent<Model> {}
```

If component has a `templateUrl`, the error is shown there too... but without no sense the location 
![image](https://user-images.githubusercontent.com/7110786/107968113-3f2f7700-6fae-11eb-982e-7756bea06d0e.png)

## 🔥 Exception or Error
this is the Angular Language Service error:
```
This component requires inline template type-checking, which is not supported by the current environment.(-998900)
```

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 11.1.3
Node: 14.15.4
OS: linux x64

Angular: 11.1.2
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: <error>

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.7
@angular-devkit/build-angular   0.1101.3
@angular-devkit/core            11.0.7
@angular-devkit/schematics      11.0.7
@angular/cli                    11.1.3
@schematics/angular             11.0.7
@schematics/update              0.1101.3
rxjs                            6.6.3
typescript                      4.1.3
    

</code></pre>

**Anything else relevant?**

**Comment by Jejuni** [comment] 2021-02-17 14:54
Can confirm this happening on any component that has a generic type parameter that `extends` anything when `Ivy native language service` is used.
Removing the `extends` (even keeping generic parameter) makes the problem go away.

**Comment by bdavis252** [comment] 2021-02-18 19:17
Also having the same issue, w/ generic that extends

**Comment by emmbee7806** [comment] 2021-02-18 22:23
Same issue

**Comment by avechuche** [comment] 2021-02-18 23:39
Same problem here...

![image](https://user-images.githubusercontent.com/11781418/108436006-62198f80-7229-11eb-9486-6c8b3a36bcf7.png)

**Comment by euvolen** [comment] 2021-02-23 09:04
Same issue

**Comment by ionut-gheorghe** [comment] 2021-02-23 18:15
Same issue

**Comment by ld210** [comment] 2021-02-25 09:15
Same issue here. I was forced to turn off the `Angular:Experimental-ivy` option in the Angular Language Service extension.

**Comment by ray-kay** [comment] 2021-02-25 10:08
> Same issue here. I was forced to turn off the `Angular:Experimental-ivy` option in the Angular Language Service extension.


How/where do you turn off the `Angular:Experimental-ivy`  ?

**Comment by vposd** [comment] 2021-02-25 10:20
@ray-kay in VSCode, go to File -> Preferences -> Settings and type `Angular:Experimental-ivy` on the search box

**Comment by ld210** [comment] 2021-02-25 10:23
> > Same issue here. I was forced to turn off the `Angular:Experimental-ivy` option in the Angular Language Service extension.
> 
> How/where do you turn off the `Angular:Experimental-ivy` ?
> Could you please provide a code snippet?

Sorry, VSCode, yes. You can also search for the Angular Service extension in the extension panel and then click on the extension setting icon.

**Comment by atscott** [comment] 2021-03-01 19:00
Duplicate of https://github.com/angular/angular/issues/40963

**Closed by atscott** 2021-03-01 19:00 UTC
Labels: comp: language-service
