### ISSUE TITLE
Class extends value undefined is not a constructor or null

### ISSUE THREAD

**Issue by skitvandarken** [angular/angular#57515] opened 2024-08-25 18:11 UTC
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

I get this error after updating Angular CLI to v18.2.1 and Firebase to the v18.0.1

### Please provide the exception or error you saw

```true
19:05:43 [vite] Internal server error: Class extends value undefined is not a constructor or null
      at node_modules/@firebase/auth/node_modules/undici/lib/fetch/file.js (C:\Users\lukeb\devcamp\website\.angular\cache\18.2.1\vite\deps_ssr\chunk-ACCZIWS3.js:5658:36)
      at __require2 (C:\Users\lukeb\devcamp\website\.angular\cache\18.2.1\vite\deps_ssr\chunk-INDP74QC.js:50:50)
      at node_modules/@firebase/auth/node_modules/undici/lib/fetch/formdata.js (C:\Users\lukeb\devcamp\website\.angular\cache\18.2.1\vite\deps_ssr\chunk-ACCZIWS3.js:5850:9)
      at __require2 (C:\Users\lukeb\devcamp\website\.angular\cache\18.2.1\vite\deps_ssr\chunk-INDP74QC.js:50:50)
      at node_modules/@firebase/auth/node_modules/undici/lib/fetch/body.js (C:\Users\lukeb\devcamp\website\.angular\cache\18.2.1\vite\deps_ssr\chunk-ACCZIWS3.js:6026:9)
      at __require2 (C:\Users\lukeb\devcamp\website\.angular\cache\18.2.1\vite\deps_ssr\chunk-INDP74QC.js:50:50)
      at node_modules/@firebase/auth/node_modules/undici/lib/fetch/response.js (C:\Users\lukeb\devcamp\website\.angular\cache\18.2.1\vite\deps_ssr\chunk-ACCZIWS3.js:13913:9)
      at __require2 (C:\Users\lukeb\devcamp\website\.angular\cache\18.2.1\vite\deps_ssr\chunk-INDP74QC.js:50:50)
      at node_modules/@firebase/auth/node_modules/undici/index.js (C:\Users\lukeb\devcamp\website\.angular\cache\18.2.1\vite\deps_ssr\chunk-ACCZIWS3.js:19828:33)
      at __require2 (C:\Users\lukeb\devcamp\website\.angular\cache\18.2.1\vite\deps_ssr\chunk-INDP74QC.js:50:50)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
{
  "name": "website",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "watch": "ng build --watch --configuration development",
    "test": "ng test",
    "serve:ssr:website": "node dist/website/server/server.mjs"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^18.2.1",
    "@angular/common": "^18.2.1",
    "@angular/compiler": "^18.2.1",
    "@angular/core": "^18.2.1",
    "@angular/fire": "^18.0.1",
    "@angular/forms": "^18.2.1",
    "@angular/platform-browser": "^18.2.1",
    "@angular/platform-browser-dynamic": "^18.2.1",
    "@angular/platform-server": "^18.2.1",
    "@angular/router": "^18.2.1",
    "@angular/ssr": "^18.2.1",
    "@emailjs/browser": "^4.3.3",
    "express": "^4.18.2",
    "rxjs": "~7.8.0",
    "tslib": "^2.3.0",
    "uikit": "^3.11.1",
    "zone.js": "~0.14.10",
    
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^18.2.1",
    "@angular/cli": "^18.2.1",
    "@angular/compiler-cli": "^18.2.1",
    "@types/express": "^4.17.17",
    "@types/jasmine": "~5.1.0",
    "@types/node": "^18.18.0",
    "jasmine-core": "~5.1.0",
    "karma": "~6.4.0",
    "karma-chrome-launcher": "~3.2.0",
    "karma-coverage": "~2.2.0",
    "karma-jasmine": "~5.1.0",
    "karma-jasmine-html-reporter": "~2.1.0",
    "typescript": "~5.4.2"
  }
}
```

**Comment by alan-agius4** [comment] 2024-08-25 18:36
Duplicate of https://github.com/angular/angular-cli/issues/28038

**Closed by alan-agius4** 2024-08-25 18:36 UTC
