### ISSUE TITLE
`InjectionToken<T>` is poorly typed

### ISSUE THREAD

**Issue by waterplea** [angular/angular#55083] opened 2024-03-28 08:54 UTC
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

# Issue

I have made a function that expects a particular value from DI, say:
```ts
function getNumber(token: ProviderToken<number>): number {
  return inject(token);
}
```
There is no type error if I try to call it with following token:
```ts
const token = new InjectionToken<string>('');
```

# Proposition

This happens because `<T>` in `InjectionToken` is only used inside factory function that you can pass inside constructor. I suggest we add a dummy prop inside `InjectionToken` class to protect against this issue:
```ts
/** @internal */
private readonly _guard!: T;
```

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-crs76u

### Please provide the exception or error you saw

```true
No type error when using `InjectionToken` of a wrong type
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
17.2.0
```

**Comment by JoostK** [comment] 2024-03-28 09:22
Closing as a duplicate of #46815

**Closed by JoostK** 2024-03-28 09:22 UTC
