### ISSUE TITLE
Multiple subscrptions on single request call create multiple requests

### ISSUE THREAD

**Issue by wutscher0815** [angular/angular#22026] opened 2018-02-05 18:32 UTC
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When having multiple subscriptions on an observable returned from an http.post request the request function is only called once but the request is executed once for each subscriptions

## Expected behavior
each call to http.post function results in exactly one request

## Minimal reproduction of the problem with instructions

In a clean angular app use this component: (add HttpModule to app.module)

```
import { Component } from '@angular/core';
import { Http } from '@angular/http';
import { Observable } from 'rxjs/Observable';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'app';
  count = 0;

  constructor(private http: Http) {
    const o = this.request();
    o.subscribe(() => console.log('foo'), () => console.log('foo'));
    o.subscribe(() => console.log('bar'), () => console.log('bar'));
  }

  request(): Observable<any> {
    console.log('request ' + this.count++);
    return this.http.post('https://foo.bar', {});
  }
}
```
Inspect the page and reload to see network activity.

Although the request() function has only been called once the request is actually executed twice

## Environment

<pre><code>
Angular version: 5.6.0 and 4.4.6

Browser:
- [x ] Chrome (desktop) version 63.0.3239.132
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ x ] Firefox version 52 ESR
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
Others:

</code></pre>

**Comment by Matmo10** [comment] 2018-02-05 18:57
That's how observables work. An observable is like a plan - each subscription is an execution of the plan.

**Comment by mlc-mlapis** [comment] 2018-02-05 18:58
@wutscher0815 ... you missed probably some key points how observables work ... a cold observable is invoked by a subscription ... without the subscription nothing is running.

**Comment by frederikprijck** [comment] 2018-02-05 18:58
@wutscher0815 This is how rxjs (which is what `http` uses internally) works. You probably want to have a look at operators to avoid this.

Try the following to resolve your "issue":

```
request(): Observable<any> {
    console.log('request ' + this.count++);
    return this.http.post('https://foo.bar', {}).shareReplay();
  }
```

Note: This is only one of the possible solutions, but you probably wanna dig into how rxjs works.

Nevertheless, this doesn't have anything to do with Angular.

**Comment by alxhub** [comment] 2018-02-06 23:29
Closing, other replies are spot on. This is by design.

**Closed by alxhub** 2018-02-06 23:29 UTC
