### ISSUE TITLE
[i18n] $localize raises eslint errors

### ISSUE THREAD

**Issue by lucacox** [angular/angular#42599] opened 2021-06-18 11:07 UTC
# Bug Report

### Affected Package
i18n

### Is this a regression?

don't know

### Description

ESLint is complaining for no-unsafe-assignment and no-unsafe-call when using $localize.

![image](https://user-images.githubusercontent.com/1597231/122551730-ad0bae00-d035-11eb-8498-d411e67971c9.png)

## Minimal Reproduction

<pre><code>
const localizedString = $localize`This string should be translated`;
</code></pre>

## Exception or Error
<pre><code>
error  Unsafe assignment of an any value  @typescript-eslint/no-unsafe-assignment
error  Unsafe any typed template tag      @typescript-eslint/no-unsafe-call
</code></pre>

## Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 11.2.13
Node: 14.15.1
OS: darwin x64

Angular: 11.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.13
@angular-devkit/build-angular   0.1102.13
@angular-devkit/core            11.2.13
@angular-devkit/schematics      11.2.13
@angular/cdk                    11.2.13
@angular/cli                    11.2.13
@angular/material               11.2.13
@schematics/angular             11.2.13
@schematics/update              0.1102.13
rxjs                            6.6.7
typescript                      4.1.5
</code></pre>

**Anything else relevant?**

eslintrc.json

<pre><code>
{
  "root": true,
  "ignorePatterns": ["projects/**/*"],
  "overrides": [
    {
      "files": ["*.ts"],
      "parserOptions": {
        "project": ["tsconfig.json", "e2e/tsconfig.json"],
        "createDefaultProgram": true
      },
      "extends": [
        "plugin:@angular-eslint/recommended",
        "plugin:@angular-eslint/template/process-inline-templates",
        "eslint:recommended",
        "plugin:@typescript-eslint/recommended",
        "plugin:@typescript-eslint/recommended-requiring-type-checking",
        "plugin:prettier/recommended"
      ],
      "rules": {
        "@typescript-eslint/explicit-member-accessibility": [
          "off",
          {
            "accessibility": "explicit"
          }
        ],
        "@typescript-eslint/restrict-template-expressions": [
          "off",
          {
            "allowNumber": true
          }
        ],
        "arrow-parens": ["off", "always"],
        "curly": ["error", "multi-line"],
        "import/order": "off",
        "max-len": [
          "error",
          {
            "code": 200
          }
        ]
      }
    },
    {
      "files": ["*.html"],
      "extends": ["plugin:@angular-eslint/template/recommended"],
      "rules": {}
    },
    {
      "files": ["*.html"],
      "excludedFiles": ["*inline-template-*.component.html"],
      "extends": ["plugin:prettier/recommended"],
      "rules": {
        "prettier/prettier": ["error", { "parser": "html" }]
      }
    }
  ]
}

</code></pre>

**Comment by petebacondarwin** [comment] 2021-06-18 13:57
Hi @lucacox - I could not reproduce this error. I created a repository containing the following:

```ts
const localizedString = $localize`This string should be translated`;

const x = 1 as any;
```

To reproduce yourself locally:

```
git clone https://github.com/petebacondarwin/issue42599
cd issue42599
npm ci
npx ng lint
```

I then see:

```
/Users/pete/dev/angular/tmp/issue42599/src/app/app.component.ts
  14:7   error    Unsafe assignment of an `any` value       @typescript-eslint/no-unsafe-assignment
  14:16  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any

✖ 2 problems (1 error, 1 warning)
```

Note that only the `x = 1 as any` line has any errors or warnings.

Also, in my IDE I see that the type of `localizedString` has been correctly inferred:

![Screenshot 2021-06-18 at 14 54 15](https://user-images.githubusercontent.com/15655/122571880-1cd56500-d045-11eb-8ae2-e9b4693dd4d9.png)

This is expected since the `$localize` function is of type `LocalizeFn`, which is a template tag handler function that explicitly returns a string.

I notice that my `.eslintrc` file has:

```
      "parserOptions": {
        "project": [
          "tsconfig.json"
        ],
        "createDefaultProgram": true
      },
```

while the one you give above has

```
      "parserOptions": {
        "project": ["tsconfig.json", "e2e/tsconfig.json"],
        "createDefaultProgram": true
      },
```

Perhaps the `e2e/tsconfig.json` is confusing eslint somehow?

**Comment by petebacondarwin** [comment] 2021-06-18 13:58
Please try forking my repository and getting it to error in the way you show above. Without a reproduction, like that, there is not much more we can do since it appears to be working correctly.

**Comment by lucacox** [comment] 2021-06-22 08:02
Hi @petebacondarwin, first of all thank you for your time.

I've tried your code and indeed it does not show the errors. I've also tried to use same angular version of the project I'm working on, but the error didn't show up.

Nonetheless the errors still persist in my project. I've tried matching versions of eslint components (@angular-eslint/*) to your versions in my project but the errors remain (i cannot update angular from version 11 which i currently use, to 12). I've tried event modify my tsconfig to match yours, but nothing happened.

I think that it is something broken in the setup of my project since the problem do not show in a fresh environment, so feel free to close the issue.

thank you,
luca

**Comment by petebacondarwin** [comment] 2021-06-22 08:04
I'm sorry to hear that you couldn't find the problem in your setup, but thanks for updating me on the status of this issue.
I think we should close this issue, since there doesn't appear to be a problem with Angular itself.
Feel free to open a new one if you manage to find a reproduction that you can share.

**Closed by petebacondarwin** 2021-06-22 08:04 UTC
Labels: comp: i18n, needs reproduction
