### ISSUE TITLE
Angular router in hash mode shouldn't modify the url before the hash

### ISSUE THREAD

**Issue by haydenbr** [angular/angular#33000] opened 2019-10-04 13:56 UTC
_NOTE: issue description updated with actual cause of the defect from the angular source code_

# 🐞 bug report

### Affected Package
@angular/router, @angular/common

### The Problem

When using the angular router in hash mode in browser in which the History API is available, if I have a base href set, the angular router _has the side effect of_ changing the hostname and pathname in the address bar to the url set as my base href. The URL in the address bar changing is a problem because when I refresh the page, the browser is no longer pointing to the same URL I used to request the page originally, and the browser requests a different url.

As an angular developer, I am expecting that Angular should only care about anything in the url after the hash (this is the case in the source code), but because of how hash mode uses the history API, it gives this unexpected side effect.

This side effect would happen in the case that my index.html file is coming from a different host or different path on the same host from which my js and css files are being served and the base href is used to resolve relative links to these files (whether requested directly from the index.html, a `url()` in css, or files lazy-loaded later). This would be the case if the index.html file is being generated by some server (could be dotnet MVC, express, whatever people use in Java land, etc) or if my js and css.

The same was reported in #20033, but was closed as the issue did not contain any reproduction of the problem.

### The Cause

TODO: need to add more details, but essentially its because of how the base href is set and how the angular router uses the (the output of `prepareExternalUrl` in `hash_location_strategy.ts` is a relative url and when passed to `history.pushState` and `history.replaceState`, the browser resolves it relative to the base href)

## 🔬 Minimal Reproduction

I had to create a [repo](https://github.com/haydenbr/ng-hash-router-problem) since you can't change the base href in stackblitz.

### Steps to reproduce

1. clone the repo
2. `npm install`
3. `npm build`
4. `npm server` (just runs a simple express server to mimic having to set base href)
5. navigate to localhost:3000/Home in your browser (the server is serving the index.html file and javascript files from different locations. In particular, the javascript files are coming from `/dist/ng-hash-router-problem/` and the index.html file is coming from `/some-other-path/index.html`)

I would expect the url to be `localhost:3000/Home/#/` after loading the application, but instead, the url is changed to `http://localhost:3000/dist/ng-hash-router-problem/#/`. So the url path was changed to the base href set in `/some-other-path/index.html`.

If I then try to refresh the page, by browser is hit `http://localhost:3000/dist/ng-hash-router-problem/#/` instead of the originally requested url, `localhost:3000/Home/#/`, and the page breaks because it cannot load the files from the server.

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.3.7
Node: 10.15.3
OS: darwin x64
Angular: 8.2.9
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.7
@angular-devkit/build-angular     0.803.7
@angular-devkit/build-optimizer   0.803.7
@angular-devkit/build-webpack     0.803.7
@angular-devkit/core              8.3.7
@angular-devkit/schematics        8.3.7
@angular/cli                      8.3.7
@ngtools/webpack                  8.3.7
@schematics/angular               8.3.7
@schematics/update                0.803.7
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2
</code></pre>

### Other notes

My express config is probably not "correct". Please don't comment on that. It's just a throw-together server to illustrate the problem that happens when I have to set base href. For the sake of the problem, please assume that I cannot change the server configuration or location of the files being served.

## Existing work arounds

It seems like an unnecessary step to have to use a work around, but two exist:

1. Implement my own LocationStrategy that overides prepareExternalUrl to maintain the full hostname and pathname in the location
2. I could not set a base href and instead use `--deploy-url` when building (or set `buildUrl` in `angular.json`), but I'd rather depend on the browser than an opaque build system. This is also a challenge because the deploy url might change per environment or per server. It's easier to set a base href because the server would know about any CDN configuration or where my files are expected to be located, but I might not have this knowledge per environment when building the front end. And this is also more configuration I have to be responsible for when otherwise the server could just set the base href.

**Comment by haydenbr** [comment] 2019-10-04 15:44
Update: After a lot of debugging and stepping though, it seems the url is being changed after this function is line is hit

https://github.com/angular/angular/blob/1537791f06df5d85dd27e763836fd99bb1530991/packages/common/src/location/platform_location.ts#L148

**Comment by haydenbr** [comment] 2019-10-04 16:14
Ok never mind. Turns out this IS default browser behavior related to setting a base href.

https://stackoverflow.com/questions/47057589/why-replacestate-removes-index-html-in-basehref-index-html

**Comment by haydenbr** [comment] 2019-10-04 16:33
Sorry, re-opening this one.

So, this is the default browser behavior when calling `history.pushState` or `history.replaceState` with a relative url. However, you will end up with different results in different browsers, depending on whether or not the History API is supported, which seems like a bug.

If you refer to this [link from the WC3](https://www.w3.org/TR/2011/WD-html5-20110113/history.html#dom-history-pushstate) and follow all the related links, if pushState is given a relative url, then it will resolve the url in reference to the base href, if one is set, or otherwise the current `window.location.path`.

I don't know if this is what would be desired from the angular router in hash mode, because hash mode is only concern with anything after the hash. Plus, if you simply updated the hash using `window.location.hash`, then only the hash would be updated.

So I think I'll submit a PR for the `hash_location_strategy.ts` the ensures the existing path is maintained when calling pushState or ReplaceState.

**Comment by atscott** [comment] 2020-07-13 17:27
Duplicate of #36688 / #14307

**Closed by atscott** 2020-07-13 17:27 UTC
Labels: comp: router, freq2: medium, router: LocationStrategy, severity2: inconvenient, state: has PR, state: needs more investigation, triage #1, type: bug/fix
