### ISSUE TITLE
Clarify information about deprecation of :ng-deep and recommend replacement

### ISSUE THREAD

**Issue by cvmocanu** [angular/angular#25160] opened 2018-07-27 09:06 UTC
The documentation at https://angular.io/guide/component-styles states this about ``:ng-deep``:
> The shadow-piercing descendant combinator is deprecated and support is being removed from major browsers and tools. As such we plan to drop support in Angular (for all 3 of /deep/, >>> and ::ng-deep).

As I understand, Angular was using the browser support for the piercing selectors ``/deep/`` and ``>>>``.

But ``:ng-deep`` is surely not supported by any browser.
And this is what I find confusing in the documentation. I don't understand what browser support has **anything** to do with ``:ng-deep``.

The way I understand it, ``:ng-deep`` prevents Angular from appending the attribute selectors to all selector following it.

So, this CSS in a component:
```
:host ::ng-deep .my-button .ui-button-text {
    font-weight: bold;
}
```
will be transformed to:
```
[_nghost-c12]     .my-button .ui-button-text {
    font-weight: bold;
}
```

Without ``:ng-deep``, this will be produced instead:
```
[_nghost-c12]     .my-button[_nghost-c12] .ui-button-text[_nghost-c12] {
    font-weight: bold;
}
```
(obviously breaking my intention).

I find 2 problems with the documentation, as it stands now:
- I don't see any relationship between lack of browser support for piercing selectors and deprecating ``:ng-deep``
- I don't see any reason to deprecate ``:ng-deep`` (since it just tells Angular: "keep your attribute selectors away from my styles")

I propose the following:
- if I missed anything, and there is a valid reason why ``:ng-deep`` should be deprecated, the documentation should be changed to explain why
- if my reasoning above is correct, remove the section about deprecating ``:ng-deep``, keeping the deprecation notice only for the piercing selectors ``/deep/`` and ``>>>``.

**Comment by cvmocanu** [comment] 2018-07-27 09:33
> :ng-deep is indeed not supported by browser, that's why it shouldn't be supported by Angular in the first place.

I fail to see the logic in this.
**``:ng-deep`` doesn't need browser support**. It only needs Angular pre-processing support, and we already have this.

**Comment by trotyl** [comment] 2018-07-27 10:10
@cvmocanu The `ViewEncapsulation.Emulated` is an exact shim of Shadow DOM behavior, there won't be any so-called Angular rule for that.

**Comment by cvmocanu** [comment] 2018-07-27 12:03
I guess I need to do some reading on the Shadow DOM.

It looks to me that the people on the Shadow DOM standards commission just deprecated a useful feature, without providing an alternative :(

**Comment by pauldraper** [comment] 2018-07-27 15:59
@trotyl #17867 had no resolution.

Angular seems confused by whether it wants to offer Angular features or be a compatibility layer for W3C ~specs~ drafts.

**Comment by jenniferfell** [comment] 2018-08-09 23:05
Looks like the resolution for https://github.com/angular/angular/issues/17867 (thanks for the link, @trotyl ) is to watch https://github.com/angular/angular/issues/23636. This seems to be an open question of what the Angular platform supports, and that issue contains the discussion. 

I believe the documentation is, for now, correct and complete:

"The shadow-piercing descendant combinator is deprecated and support is being removed from major browsers and tools. As such we plan to drop support in Angular (for all 3 of /deep/, >>> and ::ng-deep). Until then ::ng-deep should be preferred for a broader compatibility with the tools."

 When we have more information about the replacement options, we will publish them.

**Comment by jenniferfell** [comment] 2018-08-09 23:05
@IgorMinar When you get a chance, is my assessment above correct? Is there anything we can or should add now to the documentation here: https://angular.io/guide/component-styles#deprecated-deep--and-ng-deep

Thank you.

**Comment by Fokey** [comment] 2019-02-27 15:28
Has there been any resolution to this? The documentation just leads users to search for an alternative to :ng-deep which in turn leads them to a handful of GitHub issues like this one.

**Comment by gchurchley** [comment] 2019-03-01 22:59
Most of my Custom Elements comprise nested Angular Components. Within a Custom Element, I want to be able to apply styles to the nested components.  I understand that we don't want styles to bleed into the Custom Element from the page, but from within the Custom Element, I should be able to style the components that I'm using. Ideally, the Custom Element [Web Component] would be shielded (or sandboxed), but the ability to apply styles to nested components within the Custom Element is a really useful feature.  Is it possible for the Web Component to use Shadow DOM, but inside the Shadow DOM Angular still provides an emulated environment within which ::ng-deep would work. No bleeding in or out!

**Comment by pauldraper** [comment] 2019-03-02 04:39
@Fokey the clear choice replacement (or at least partial replacement) is the standardized ::slotted().

See #27614 but if you're looking for any participation/response from the Angular team you will be disappointed :/

**Comment by neil-119** [comment] 2019-05-22 05:41
While I cannot comment on the "best practices" aspect, I can share how we are currently using this feature. We use several third party UI components that come bundled with their own CSS. Some of these components offer limited customization options (e.g. no support for templates and no ability to set CSS classes), so our options include: 1) apply styles globally, 2) use ng-deep, 3) edit their source code, or 4) find a different library. We opted for option 2, as it enables us to style each component that we don't have easy control over. Granted, it's not "best practice" but in the industry we often have to deal with / work around others' code.

**Comment by montella1507** [comment] 2019-06-14 14:21
@neil-119 same here.

3) is most often not possible
4) not a solution
1) little-bit old-school isnt it?
2) elegant solution - still didnt get a reason for deprecation in browsers..

**Comment by Splaktar** [comment] 2019-06-22 08:13
@neil-119 you are missing the best option...

Rather than using global styles (and having a huge `src/app/styles.scss` file), given you want to use such a library component in a component:
1. define a class on the component's container element
1. set the component to `encapsulation: ViewEncapsulation.None`
1. wrap all styles in the component (SCSS) with the component's container element's class
1. target any selectors that you want in the library component

This allows you to style that library component differently in different parts of your app rather than having a single global style. 

> Note that in some, concise, isolated cases, the single global style is the best approach.

This can be used to eliminate your dependence upon `::ng-deep`.

**Comment by montella1507** [comment] 2019-06-22 08:17
@Splaktar is there any reason not to use component selector as CSS selector then?

something-list.component.ts  ->  "app-something-list"

// components/something-list.scss
app-something-list {
  color: blue;
}

**Comment by Splaktar** [comment] 2019-06-22 08:34
@montella1507 I'm not sure that I understand your example. I wouldn't recommend targeting the top level app's selector from a child component. I think that it's best to only style down within your component tree (not up).

[Here's a real example](https://github.com/angular-hispano/angular-hispano/blob/d5be179b0b7a428c0a9225862df33caafb330ce8/projects/web/src/app/nav/nav.component.scss#L3-L18) of what I mentioned above.

**Comment by simeyla** [comment] 2019-06-28 02:51
Tired of seeing stackoverflow answers that say 'don't use ::ng-deep because it's deprecated'. That's just delusional right now. Use it.

**Comment by pauldraper** [comment] 2019-07-11 02:21
::ng-deep is going to hold the web record for long-lived deprecated API.

**Comment by Nexxado** [comment] 2019-07-11 06:04
> Tired of seeing stackoverflow answers that say 'don't use ::ng-deep because it's deprecated'. That's just delusional right now. Use it.

I don't see why it should be deprecated in the first place.
Right now it's just an angular thing, telling the angular compiler not to scope that style to the component and it's not related to browsers' implementations.

**Comment by pauldraper** [comment] 2019-07-11 21:08
https://update.angular.io says

> both are deprecated but using ::ng-deep is preferred until the shadow-piercing descendant combinator is removed from browsers and tools completely.

The deep selector was decided to be remove in in April 2015 by WAWG. ::ng-deep was remove from Chrome starting v63 in Dec 2017.

Surely the Angular team will follow through on that any day now /s

**Comment by gkaravitis** [comment] 2019-07-12 06:52
I am also using ::ng-deep in project. It would be nice to have an official answer if its gonna be deprecated from Angular.

**Comment by Splaktar** [comment] 2019-07-14 05:14
@gkaravitis it's already deprecated. It's not clear when it will be removed.

**Comment by simeyla** [comment] 2019-07-14 05:35
@Splaktar Let's see... As of today 533 repositories use it and 44k code files in github alone. I don't think it *can* go anywhere anytime soon!

Educating people for the best use cases is more important - eg. when to create a truly global style sheet, when to create a 'theme' style file and when to use it in a component tree (if absolutely necessary)

**Comment by mlc-mlapis** [comment] 2019-07-14 12:08
@gkaravitis The things are removed usually 2 major versions after they are depreciated.

**Comment by Splaktar** [comment] 2019-07-14 14:36
@mlc-mlapis https://angular.io/guide/deprecations#index has more specific information for planned removal of deprecations.

**Comment by gkaravitis** [comment] 2019-07-14 19:29
@mlc-mlapis @Splaktar So after investigate it a bit and with your valuable contibution we decided that its best even on css level to have separation of concerns. We planned to refactor our code and omit the :ng-deep.

**Comment by evanjmg** [comment] 2019-08-12 18:30
@gkaravitis could you share your solutions for your refactor? So far,  I've been using global classes on app.component ViewEncapsulation.None but that's just messy. Any component level solution?

**Comment by BenRacicot** [comment] 2019-08-12 19:02
@evanjmg thought I'd chime in fwiw. After eading this thread I replaced `/deep/` with `::ng-deep`. My belief is that ng-deep is going to exist (within Angular) for quite awhile.

**Comment by evanjmg** [comment] 2019-08-12 19:16
@BenRacicot ::ng-deep is not the recommended solution and it will be removed eventually. This issue is about finding an alternative.

**Comment by simeyla** [comment] 2019-08-12 19:37
The most practical step right now would be to add a section in the docs explaining each common use case for `::ng-deep` and what are the pros / cons of any alternatives for each use case.

This issue will be impossible to reconcile if we don't have a list like this. If they are all outlined in a detailed tutorial it would at least help steer people away from the worst usages.

eg.
* To tweak material styles globally => use global stylesheet, or theme mixins
* To tweak material styles one time for a very specific component => `::ng-deep` would be ok here IMHO
* To set style (eg. flex) for the first child of a `router-outlet` => `::ng-deep router-outlet` is probably ok.
* To set styles for something that was dynamically added and therefore doesn't have ng attributes (eg. youtube iframe) => `::ng-deep iframe` is probably ok
* Setting styles for a child component in 100 places over your app => probably bad idea!

The day `::ng-deep` is deprecated - if anytime soon - is the day I stop updating Angular.

Also I agree with @BenRacicot that it is going to exist for quite some time - years minimum. Angular is mature enough now and way too many projects rely on this (whether good or bad) and have too much momentum to be re-architected overnight.

**Comment by BenRacicot** [comment] 2019-08-12 19:48
Let's recap...
 - Is there an alternative shadow piercing descendant selector (SPS)? Doesn't seem to be. So as described, we're stuck with what remains (ng-deep).
 - We could use globally scoped styles (from a global stylesheet)
 - We can set a component's style encapsulation to allow its styles to affect children
 - CSS Custom Properties can "cross" shadow boundaries but by no means replace SPSs

Are there other options I'm missing?

**Comment by evanjmg** [comment] 2019-08-12 19:51
ViewEncapsulation.Native and Shadow Dom is the only correct solution but it lacks pollyfills at the moment correct? https://github.com/angular/angular/issues/23636

**Comment by simeyla** [comment] 2019-08-12 20:07
@evanjmg Given that these 'deep' things get deprecated in the first place because they [break encapsulation](https://stackoverflow.com/questions/35741722/whats-the-substitute-for-shadow-and-deep) it very much concerns me that if suddenly everything was `Native` it just isn't going to work for the way people develop using third party components. 

The Angular material team is quite stubborn (not trying to offend) with their adherence to the spec that they release components that just don't work for certain designs (try positioning half a dozen text fields vertically with their default spacing) - and therefore necessitate 'tweaking' the components css. 

If material suddenly started using `Native` with a polyfill then wouldn't that mean `::ng-deep` or even global stylesheet would be impossible (I'm not sure but isn't that the whole point of shadow dom?). 

The stackoverflow question I referenced above doesn't even mention angular - so I'm just realizing now there's a whole parallel conversation going on in the 'web-component' world to seek inspiration from :-)

**Comment by BenRacicot** [comment] 2019-08-12 21:01
@simeyla we see eye to eye on this directly. I pulled material from my project after a ~month. 

There does seem to be several tricks as alternatives to piercing selectors but some make me cringe a little:

 - Apparently [many styles are still inheritable inside a shadow DOM element](https://developers.google.com/web/fundamentals/web-components/shadowdom#reset).
 - [:host-context(.darktheme) is powerful](https://developers.google.com/web/fundamentals/web-components/shadowdom#contextstyling) but I believe it has unusable support
 - Leveraging CSS vars as "[style hooks](https://developers.google.com/web/fundamentals/web-components/shadowdom#stylehooks)"

**Comment by kyubisation** [comment] 2019-08-12 21:30
There is also the [::slotted](https://developer.mozilla.org/en-US/docs/Web/CSS/::slotted) pseudo-element, which was implemented for ViewEncapsulation.Native (#11595). For ViewEncapsulation.Emulated the pull request (#31547) is currently waiting for review.

**Comment by Splaktar** [comment] 2019-08-13 22:21
> eg.
> - To tweak material styles globally => use global stylesheet, or theme mixins

For many styles this can be accomplished using the built in theming or typography features of Angular Material. For those where this doesn't apply, my suggestion [here](https://github.com/angular/angular/issues/25160#issuecomment-504642697) is recommended.

> - To tweak material styles one time for a very specific component => `::ng-deep` would be ok here IMHO
> - To set style (eg. flex) for the first child of a router-outlet => `::ng-deep` router-outlet is probably ok.
> - To set styles for something that was dynamically added and therefore doesn't have ng attributes (eg. youtube iframe) => `::ng-deep iframe` is probably ok

My suggestion [here](https://github.com/angular/angular/issues/25160#issuecomment-504642697) is recommended over these uses of `::ng-deep`.

> - Setting styles for a child component in 100 places over your app => probably bad idea!

If this is what you are facing and these styles are the same in every place, then a global style may be the correct approach. If that isn't viable, then you could wrap the external third party component in a first party component that just applies these styles (via my suggestion [here](https://github.com/angular/angular/issues/25160#issuecomment-504642697)).

> The day `::ng-deep` is deprecated - if anytime soon - is the day I stop updating Angular.

As mentioned above, there are clear, functional alternatives to `::ng-deep`. You should not be depending upon it heavily in your apps.

**Comment by cyraid** [comment] 2019-09-22 23:33
I mean, someone did submit a ::slotted() pull request..
https://github.com/angular/angular/pull/31547

**Comment by kolkov** [comment] 2019-11-30 12:35
Is `/deep/` removed in Angular v.9? I can't build old library with this css selector in latest RC.3 or RC.4.
Thanks!

**Comment by KhaledSamir** [comment] 2019-12-11 17:00
> Is `/deep/` removed in Angular v.9? I can't build old library with this css selector in latest RC.3 or RC.4.
> Thanks!

They were planning to remove it:  https://github.com/angular/angular/issues/17867

**Comment by Splaktar** [comment] 2019-12-11 18:36
@kolkov I don't think so. Can you provide more details in a StackOverflow post or somewhere else? I.e. the error message, etc.

**Comment by chris13524** [comment] 2019-12-13 01:07
I believe the solution here is [`::slotted()`](https://drafts.csswg.org/css-scoping/#slotted-pseudo) for when a component wants to style elements projected into it. And [`::part()`](https://drafts.csswg.org/css-shadow-parts/) for when a component consumer wants to style parts of a component. I'd assume this is what the Angular team would implement as a replacement for `::ng-deep`.

Of course this requires both sides to work together to expose the API, but that is what you'd have to do in any other situation all across software development. If you own the component, implement the API. If you don't, submit a request to the developer or fork the project. This situation is no different. We should maintain that encapsulation.

Like in other languages, there's often ways to hack into it and force it to work (e.g. reflection). In Angular, you can either 1) put your styles globally (for emulated) or 2) run some JavaScript inside the shadow DOM (for native).

**Comment by gudzdanil** [comment] 2020-02-14 09:19
@Splaktar not sure [your solution](https://github.com/angular/angular/issues/25160#issuecomment-504642697)  is quite good.
Container component usually has not only child third-party component we wish to restyle. So view encapsulation with `none` value will disable styles encapsulation for everything else inside component. And if on current page there is something with the same selector - it will break styles.
Furthermore Angular doesn't remove style tag from head for destroyed component. So if you have routing in your app, which I pretty sure most do, on other pages these non-encapsulated styles will crap something in case selector matched, which is likely to happen in quite a big app

**Comment by chris13524** [comment] 2020-02-14 13:23
@gudzdanil if you turn off view encapsulation, you would also scope your component's styles like this:

```
my-component {
  // all of your styles
}
```

This works fine for leaf components, but not ones that project content.

**Comment by luiscla27** [comment] 2020-02-26 17:47
I understand the need to deprecate `::ng-deep`, that would be because it leaves the application open for unwanted CSS spread through your whole application (...) however the combination of `:host` and `::ng-deep` is perfect, why don't you (**angular team**) create your own `:host-deep` pseudo-class selector?

Most the developers complaining here doesn't need the `::ng-deep` feature, they need the `:host` `::ng-deep` combination, by now i think [this](https://github.com/angular/angular/issues/25160#issuecomment-510301972) is the best answer here on this thread.

**Comment by nminhduc** [comment] 2020-04-15 07:39
so for now, `ng-deep` still mark deprecate, what a solution for ng-deep without using encapsulation. I want to custom some angular material component only inside my child component

**Comment by cyraid** [comment] 2020-04-15 10:23
> I understand the need to deprecate `::ng-deep`, that would be because it leaves the application open for unwanted CSS spread through your whole application (...) however the combination of `:host` and `::ng-deep` is perfect, why don't you (**angular team**) create your own `:host-deep` pseudo-class selector?
> 
> Most developers complaining here doesn't need the `::ng-deep` feature, they need the `:host` `::ng-deep` combination, by now i think [this](https://github.com/angular/angular/issues/25160#issuecomment-510301972) is the best answer here on this thread.

Exactly. I don't think I've come across a point where I need to style something outside of the host context. It's always been child components.

**Comment by claudekennilol** [comment] 2020-06-15 13:44
> I understand the need to deprecate `::ng-deep`, that would be because it leaves the application open for unwanted CSS spread through your whole application (...) however the combination of `:host` and `::ng-deep` is perfect, why don't you (**angular team**) create your own `:host-deep` pseudo-class selector?
> 
> Most developers complaining here doesn't need the `::ng-deep` feature, they need the `:host` `::ng-deep` combination, by now i think [this](https://github.com/angular/angular/issues/25160#issuecomment-510301972) is the best answer here on this thread.

So is there a current replacement for `:host ::ng-deep`?

**Comment by kyubisation** [comment] 2020-06-15 14:12
No.
A possible solution is #31547 (emulation of [::slotted selector](https://developer.mozilla.org/en-US/docs/Web/CSS/::slotted)), which is waiting to be merged (or reviewed again).

**Comment by luiscla27** [comment] 2020-06-15 14:38
> So is there a current replacement for `:host ::ng-deep`?

Just ignore the deprecated warning

**Comment by dman777** [comment] 2020-07-17 20:55
Angular team, please ask the Polymer team how to get this done. Apis for custom CSS properties on a component are a few years overdue.

**Comment by swirlsky** [comment] 2020-09-04 06:15
Most of the times, using `::ng-deep` without a preceding selector or the `:host` pseudo-class is wrong, as most of the times you shouldn't style things from your component which are out of its scope. That's right.

However, what should you do if you need to style elements which are dynamically added to the page outside of your component? A good example is a tooltip, modal or popover that you're controlling from your component but it is appended by whichever library directly under the body.

You could surely define a global style in the app's css, but what if you prefer using different looking tooltips across components?

**Comment by gudzdanil** [comment] 2020-09-04 07:10
@swirlsky I suppose you need to do positioning in global css for tooltip because it's a common behavior, and in components you need to define a template, use ViewChild to query template and then instantiate tooltip with this template. Then angular compiles template with scoped css attributes and you can define styles as usual without ng-deep

**Comment by Splaktar** [comment] 2020-09-04 07:27
> After the functionality of ::ng-deep will have been removed from Angular, I have no idea how we could achieve this.

You would just use a global style that is wrapped by the class name of the tooltip type that you are styling. I.e.
```scss
.mat-tooltip.someComponent { ... }
``
Is your concern that you want to have hundreds or thousands of different components that have differently styled tooltips? And they would all be completely custom, so that the below doesn't apply?

> what if you prefer using different looking tooltips across components?

Then you would use a class name (which I would always recommend) instead of the component name (not recommended). I.e.
```scss
.mat-tooltip.info { ... }
.mat-tooltip.alert { ... }
```
As you noted, with Material, this would be set via `matTooltipClass="info"` and Bootstrap and other libraries have a similar feature.

You shouldn't feel like global styles are banned or not to be used. Of course, you should avoid over using them and make smart decisions about how you name and organize them. For large teams, there should be clearly documented guidelines for global styles.

**Comment by BenRacicot** [comment] 2020-09-04 12:57
@swirlsky I wrote about the proper CSS strategy to avoid this issue and many others. [Angular CSS Strategies](https://medium.com/@BenRacicot/angular-css-strategies-973db1f44c67). It's very simple, style general styles within a global stylesheet. Then resetting styles inside a component is not an issue at all. 

Note: This is also how CSS should be architected in general. If your team is relying on component scoped styles FIRST then your problems have only just begun anyways.

**Comment by azamanaza** [comment] 2020-11-19 18:10
> @neil-119 you are missing the best option...
> 
> Rather than using global styles (and having a huge `src/app/styles.scss` file), given you want to use such a library component in a component:
> 
> 1. define a class on the component's container element
> 2. set the component to `encapsulation: ViewEncapsulation.None`
> 3. wrap all styles in the component (SCSS) with the class of the component's container element
> 4. target any selectors that you want in the library component
> 
> This allows you to style that library component differently in different parts of your app rather than having a single global style.
> 
> > Note that in some, concise, isolated cases, the single global style is the best approach.
> 
> This can be used to eliminate your dependence upon `::ng-deep`.

@Splaktar nice!

I made alternatives to step2.

```
constructor(el: ElementRef) {
    const { nativeElement } = el;
    nativeElement.className = nativeElement.tagName.toLowerCase();
  }
```

OR
```
@HostBinding('class.app-header') addHostClass = true;
```

**Comment by montella1507** [comment] 2020-11-19 18:44
Why then just dont use komponent selector as CSS selector then?  app-comp1 {}

**Comment by petebacondarwin** [comment] 2021-01-23 20:29
I think if we can land the `::slotted` PR then we could document that as an alternative to `ng-deep` and that might also give us the confidence to finally remove the `ng-deep` and associated features.

**Comment by petebacondarwin** [comment] 2021-05-23 11:08
@BenRacicot - I like your strategy, although it only works for "emulated" component encapsulation. If you used ShadowDOM encapsulation, then these global styles do not reach into the template. That being said, neither do the `::ng-deep` styles so there is no loss there.

**Comment by BenRacicot** [comment] 2021-05-23 23:08
Hey @petebacondarwin! 
Yes all true, you've inspired me to update the article and create a Stackblitz to prove out the solution to ShadowDOM encapsulation.

Maybe you've had a chance to see my article and the other Stackblitz templates? 
Within global styles there should also be a CSS custom properties strategy that can be used within the shadow.

[Stackblitz example](https://stackblitz.com/edit/angular-access-css-vars?file=src%2Fapp%2Fshadow-dom%2Fshadow-dom.component.ts)

Updated the [Angular CSS](https://benracicot.medium.com/angular-css-strategies-973db1f44c67) article.

**Comment by petebacondarwin** [comment] 2021-05-24 14:57
Interesting idea @BenRacicot to use CSS custom properties. I had not even heard of those before.

**Comment by kapsiR** [comment] 2021-11-25 13:37
[The [New] State of CSS in Angular](https://blog.angular.io/the-new-state-of-css-in-angular-bec011715ee6) has a section about [Future of overriding styles](https://blog.angular.io/the-new-state-of-css-in-angular-bec011715ee6#12af):
> CSS Variables open the door to well-supported APIs for component customization, allowing developers to shift away from CSS overrides and `::ng-deep`.
> 
> **We recommend introducing custom variables in your libraries and dependencies in order to create an API surface for customizing libraries without the need for `::ng-deep`.** Implementation of custom variables allows developers to have more control over their styling and provide a path away from CSS overrides and `::ng-deep`.

**Comment by vugar005** [comment] 2021-12-27 21:41
`::part `looks like a good native solution but I wonder what about material or other 3 rd party components where current projects use `:ng-deep`. The only problem imo is auto migration of `:ng-deep `to` :part`.

**Comment by Ketec** [comment] 2022-03-04 12:36
End up in this thread after looking up this issue and ::part is certainly not an option because this requires templates to have matching attributes.
Cannot expect all third party libraries and content to add a custom part attribute to every single element because you would not know what someone may want to style there.

Angular could automatically wrap component styles with the component selector and move to global scope.
So any inline or styleUrls styles are always wrapped by the compiler.
This way nothing leaks, no globally written styles or dom piercing hacks are required.

**Comment by nCr78** [comment] 2022-03-19 11:49
> @neil-119 you are missing the best option...
> 
> Rather than using global styles (and having a huge `src/app/styles.scss` file), given you want to use such a library component in a component:
> 
> 1. define a class on the component's container element
> 2. set the component to `encapsulation: ViewEncapsulation.None`
> 3. wrap all styles in the component (SCSS) with the class of the component's container element
> 4. target any selectors that you want in the library component
> 
> This allows you to style that library component differently in different parts of your app rather than having a single global style.
> 
> > Note that in some, concise, isolated cases, the single global style is the best approach.
> 
> This can be used to eliminate your dependence upon `::ng-deep`.

I am sorry but why is this or any other of the alternative solutions not mentioned in the angular docs, right where ng-deep is? Am I missing something? Usually when something gets deprecated, the documentation gives you the alternative 😅

**Comment by martinbigsur** [comment] 2022-03-31 21:14
I've been working for the past 8 months for a project that required Angular Material as its main components library. The problem is, at least 30% of the components need a certain level of customization to match de design, thus I need a way to override the nested styles of each one of these components. Of course the first thing that came up to my mind was using ::ng-deep, easy, quick and does the job. Now that ng-deep is deprecated, not supported in any way, browsers break the styles when you use them, and there is no information about clean alternatives in the Docs AFAIK, has anyone gone through something similar? any alternatives you could find? Everything helps.

**Comment by olafur-palsson** [comment] 2022-07-22 10:24
I'm finding that the most common workaround to this is to somehow use `ViewEncapsulation.None` in a wrapper component and put all the `::ng-deep` styles in there.  We could not make a bit easier by doing something like this.

```ts
@Component({
  selector: 'app-some',
  templateUrl: './some.component.html',
  styleUrls: [
    // The suggestion
    { path: './some.component.deep.css', encapsulation: ViewEncapsulation.None },
    'some.component.css'
  ]
})
export class SomeComponent implements OnInit {
  // ...
}
```

**Comment by earthengine** [comment] 2022-08-17 22:39
@olafur-palsson 
We have a project with pretty similar solutions
- We have a wrapper over the App component which is `ViewEncapsulation.None`
- For that wrapper we have all `deep` stylesheets loaded via `styleUrls` array, from all components that need to use `::ng-deep`

However this is still having problems
- `:host ::ng-deep` have to be written `component-tag` in that `deep` file, and it is easy to forget
- forced to use a separate file (a good thing maybe?)

My proposal is to rename `::ng-deep` to `::bail-encapsulation`, just to make it feel harder to those don't need it, and still usable for those absolutely need it.

**Comment by arman-g** [comment] 2023-03-04 20:56
> Re: @simeyla
> 
> > eg.
> > 
> > * To tweak material styles globally => use global stylesheet, or theme mixins

Using global stylesheet for a material component that is used once in the entire website defeats the purpose of encapsulation (the style is loaded with every web page).

**Comment by arman-g** [comment] 2023-03-04 21:06
> The most practical step right now would be to add a section in the docs explaining each common use case for `::ng-deep` and what are the pros / cons of any alternatives for each.
> 
> This issue will be impossible to reconcile if we don't have a list like this. If they are all outlined in a detailed tutorial it help steer people away from the worst usages - and make it easier to migrate in future to whatever comes next.
> 
> eg.
> 
> * To tweak material styles globally => use global stylesheet, or theme mixins

Using global stylesheet for a material component that is used once in the entire website defeats the purpose of encapsulation.

**Comment by arman-g** [comment] 2023-03-04 21:18
> @neil-119 you are missing the best option...
> 
> Rather than using global styles (and having a huge `src/app/styles.scss` file), given you want to use such a library component in a component:
> 
> 1. define a class on the component's container element
> 2. set the component to `encapsulation: ViewEncapsulation.None`
> 3. wrap all styles in the component (SCSS) with the class of the component's container element
> 4. target any selectors that you want in the library component
> 
> This allows you to style that library component differently in different parts of your app rather than having a single global style.
> 
> > Note that in some, concise, isolated cases, the single global style is the best approach.
> 
> This can be used to eliminate your dependence upon `::ng-deep`.

I believe setting the component to `encapsulation: ViewEncapsulation.None` means the css file for that component is going to be included withing every request? If this is true than how is this better than including the style in the global stylesheet?
The purpose of encapsulation is not only to organize the styles for each component but load them as needed which improves the performance.

**Comment by 273299007** [comment] 2023-03-29 02:34
regarding the replacement of [::ng-deep], one option is moving these CSS style to a global css file directly. this is very simple.

**Comment by olafur-palsson** [comment] 2023-03-29 06:58
> regarding the replacement of [::ng-deep], one option is moving these CSS style to a global css file directly. this is very simple.

You can't lazy-load global styles and a `global.css` quickly becomes hard to manage in large projects.

**Comment by montella1507** [comment] 2023-03-29 08:13
Deprecation of ng-deep want only developers without real world experience with 3rd party libraries in project and "no angular" libraries in project..


One example for all is a library which generates DOM elements without angular - so Angular is not putting his "_nghost" etc. attributes on DOM elements so it is not possible to override styles of these libraries.. And you DO NOT want to include these overrides in global style - you want to lazy load them easily (for the instance, with component wrapper).

Stop deprecating things, which don't have 100% replacement.

Deprecation of ng-deep has its origin in non-experiecne with real world usage, rather than a real PROBLEM.

YOU NEED TO HAVE a way how to override 3rd party libs with ng-deep, because of:
- missing CSS Variables support in 3rd party lib
- missing "another way" of modification (inputs,...)
- not-compatible (non-ng) libraries modifying DOM directly (so angular cannot append his attributes to make the encapsulation work correctly). 

+ developers forget they can SCOPE "ng-deeped" styles to host element too, so there is NOT ANY PROBLEM at all..



```
:host ::ng-deep .library .element {
}
```


I really don't understand why is this still a topic of deprecation...  Why is anyone trying to dogmatically remove this usable thing, when there are 100% legit scenarios when it could be used and will not lead to any problem at all... As a bonus.. it is only way how to EASILY code-split  component styles effectively..

**Comment by olafur-palsson** [comment] 2023-06-13 09:06
It's been 5 years and 9 major versions with no plans on removing it as of yet. I would really like it if we remove the deprecation until a proper solution that Angular backs is found.

**Comment by tomastrajan** [comment] 2024-01-20 12:39
Un-deprecate `ng-deep` and (or) rename it to `ng-global` [context](https://www.youtube.com/watch?v=bVBH5vicUro&t=3703s)

It has it's obvious use case, more descriptive naming would be preferable and could be auto migrated with ease!

**Comment by montella1507** [comment] 2024-01-20 15:49
As far as i know it does not make things "global", it just disables "prefixing" of selectors by host elements etc. 

So the scope is way different...

:host comp-a ::ng-deep div {} 

will not be global right?

::ng-deep comp-a div {} will not be globel  either

This is why i think, the new name should be closer to words "disable" and "encapsulation"  :-/ WHat do you think, guys?

**Comment by Jordan-Hall** [comment] 2024-01-20 16:25
I have a different view I think it's worth implementing support for ::part which does require exportparts. However it's more inline with shadowdom which is what deep was emulating.

Reference https://developer.chrome.com/blog/remove-shadow-piercing
::parts https://tabatkins.github.io/specs/css-shadow-parts/

I think it's time for dev console to throw a warning and for changes to ecosystem. This has been on the chopping block for longer than view engine was. People had time to change, need that be css variable, inputs or scss mixing like Angular material for typography and teeming

**Comment by simeyla** [comment] 2024-01-20 16:50
> ::ng-deep comp-a div {} will not be global either.

@montella1507 This absolutely becomes global. See https://github.com/angular/angular/issues/29965

Putting anything 'around' the `::ng-deep` such as `:host` (as you also showed) or even `div` makes it localized to the component.

Having a top-level `::ng-deep` in a component **should absolutely be banned and a compile error**. You can use `:host` if that's what you really want and perhaps `:root` if you wanted it to 'leak' (exceptionally rare).

There was in fact a recent change in Angular 17 to [remove styles after components are destroyed](https://github.com/angular/angular/pull/51571), which can help expose the leaky behavior in some cases.

Stop trying to make `::ng-deep` not happen. **It's not going to not happen**. 

It has its uses: with external components, urgent fixes your boss/client asks for that are otherwise out of your control and I also rely on it for positioning styling for `router-outlet` children. (With the notable exception of forbidding top level which really should happen).

**Comment by Jordan-Hall** [comment] 2024-01-20 17:23
Viewencapsulation.none thats basically what you are after.... problem here is ng-deep is out of spec of shadowdom so emulation isn't emulating shadowdom then.

**Comment by montella1507** [comment] 2024-01-20 17:48
> > ::ng-deep comp-a div {} will not be global either.
> 
> @montella1507 This absolutely becomes global. However you're effectively making it local by adding in `comp-a` because it wouldn't ever apply to `comp-b` if that's what you mean. See #29965
> 
> Putting anything 'around' the `::ng-deep` such as `:host` (as you also showed) or even `div` makes it localized to the component.
> 
> Having a top-level `::ng-deep` in a component **should absolutely be banned and a compile error**. You can use `:host` if that's what you really want and perhaps `:root` if you wanted it to 'leak' (exceptionally rare).
> 
> There was in fact a recent change in Angular 17 to [remove styles after components are destroyed](https://github.com/angular/angular/pull/51571), which can help expose the leaky behavior in some cases.
> 
> Stop trying to make `::ng-deep` not happen. **It's not going to not happen**.
> 
> It has its uses: with external components, urgent fixes your boss/client asks for that are otherwise out of your control and I also rely on it for positioning styling for `router-outlet` children. (With the notable exception of forbidding top level which really should happen).

yep, sorry... i was on mobile so it was annoying to put it inside bracelets (any). I meant it that way.

**Comment by alxhub** [comment] 2024-03-22 19:12
As (sort of) announced at ng-conf, as of v18 `ng-deep` is no longer labeled as deprecated in the angular.dev docs. We will not be removing the feature (not that we had planned to anyway). However, we still discourage its use, as we view `ng-deep` as a CSS anti-pattern in many cases, similar to e.g. `!important`.

**Comment by Jordan-Hall** [comment] 2024-03-22 19:15
That's a really bad decision. Even if you don't remove it :( people will just use and abuse it. So many clients abused the feature as it is

**Closed** 2024-03-22 19:14 UTC
Labels: freq1: low, P4, canonical, area: docs

**Comment by diegovilar** [comment] 2024-03-22 23:41
I think that keeping it is the right call. Removing it would be like removing !important from CSS. It's a last resource, but sometimes it is the ONLY way we can customize something we did not author ourselves and the ppl who did did not include extensions points

**Comment by dalenguyen** [comment] 2024-03-23 00:35
Agree, especially for something like Material Overlay CDK. Without ng-deep, the custom styling would end up in global styles.

**Comment by pauldraper** [comment] 2024-03-23 19:05
> We will not be removing the feature (not that we had planned to anyway).

Somehow, for some reason, Yyars of conversation assumed otherwise ^

Communication is key.
