### ISSUE TITLE
ngSwitchCase doesn't cast numbers to true

### ISSUE THREAD

**Issue by undsoft** [angular/angular#51868] opened 2023-09-22 15:40 UTC
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

No

### Description

[NgSwitchCase documentation](https://angular.io/api/common/NgSwitchCase) states:

> Unlike JavaScript, which uses strict equality, Angular uses loose equality. This means that the empty string, "" matches 0.

This is however not true when true is compared with a number.

```html
<ng-container [ngSwitch]="true">
    <div *ngSwitchCase="69">Nice</div>
    <div *ngSwitchDefault>Not nice</div>
</ng-container>
```

will evaluate to `Not nice`.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-f1u6tf?file=src%2Fmain.ts

### Please provide the exception or error you saw

```true
N/A
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
@angular - 16.2.6
```

**Comment by JoostK** [comment] 2023-09-22 16:24
I don't follow; `true == 69` is `false` in JavaScript, just as you observe it to be in an Angular template.

**Comment by undsoft** [comment] 2023-09-22 16:30
Yes, you're right, hm.
I guess I'm used to ngIf accepting truthy values (like array.length) and so I was expecting *ngSwitchCase to work similarly.

My assumption is incorrect as standard switch doesn't do that either.

**Comment by JoostK** [comment] 2023-09-22 17:38
I am going to close this as working as intended.

**Closed by JoostK** 2023-09-22 17:38 UTC
