### ISSUE TITLE
Parent and Ancestor annotations in typescript 

### ISSUE THREAD

**Issue by 0Decoherence** [angular/angular#1831] opened 2015-05-12 04:52 UTC
the equivalent of the following in dart works perfectly, in typescript after defining the Parent and  the Ancestor annotations in typescript typings as:

```typescript
declare module "angular2/annotations"{
   function Parent():(target: Type) => any;
   function Ancestor():(target: Type) => any;
}```

And using it as:

```typescript
/// <reference path="typings/angular2/angular2.d.ts" />
import {bootstrap, Component, View} from 'angular2/angular2';
import {Parent} from 'angular2/annotations'

@Component({selector:"c2"})
@View({template:'i am c2'})
class C2{
   constructor(@Parent() p:C1){
      console.log(p);
   }
}

@Component({selector:"c1"})
@View({template:`<c2></c2>`,directives:[C2]})
class C1{}

@Component({selector:"app"})
@View({template:`<c1></c1>`, directives:[C1]})
class App{}

bootstrap(App);
```
it throws:
```
TypeError: Cannot read property 'length' of undefined

TypeError: Cannot read property 'length' of undefined
    at ReflectionCapabilities.execute.ReflectionCapabilities._zipTypesAndAnnotaions (https://code.angularjs.org/2.0.0-alpha.22/angular2.dev.js:6620:64)
    at ReflectionCapabilities.execute.ReflectionCapabilities.parameters (https://code.angularjs.org/2.0.0-alpha.22/angular2.dev.js:6641:29)
    at Reflector.execute.Reflector.parameters (https://code.angularjs.org/2.0.0-alpha.22/angular2.dev.js:16282:50)
    at _dependenciesFor (https://code.angularjs.org/2.0.0-alpha.22/angular2.dev.js:16989:28)
    at execute.Binding.resolve (https://code.angularjs.org/2.0.0-alpha.22/angular2.dev.js:17122:28)
    at Function.execute.DirectiveBinding.createFromBinding (https://code.angularjs.org/2.0.0-alpha.22/angular2.dev.js:23681:24)
    at Function.execute.DirectiveBinding.createFromType (https://code.angularjs.org/2.0.0-alpha.22/angular2.dev.js:23687:37)
    at Compiler.execute.Compiler._bindDirective (https://code.angularjs.org/2.0.0-alpha.22/angular2.dev.js:24947:39)
    at https://code.angularjs.org/2.0.0-alpha.22/angular2.dev.js:24992:29
   ...
```

**Comment by SekibOmazic** [comment] 2015-05-12 06:22
@0Decoherence This should help:
```Javascript
import {
  ComponentAnnotation as Component, 
  ViewAnnotation as View, 
  ParentAnnotation as Parent, 
  AncestorAnnotation as Ancestor
} from 'angular2/angular2';
```

**Comment by 0Decoherence** [comment] 2015-05-12 06:39
@SekibOmazic Yes alpha.22 as you can see from the exceptions, but can you please explain how that import statement you included helps?

**Comment by 0Decoherence** [comment] 2015-05-12 10:59
When i do the following it fixes the problem but as to why it works i don't know, nor it makes sense because in dart the above sample works
```typescript
/// <reference path="typings/angular2/angular2.d.ts" />
import {bootstrap, Component, View} from 'angular2/angular2';
import {Parent} from 'angular2/annotations';

@Component({selector:"c1"})
@View({template:`<content></content>`})
export class C1{}

@Component({selector:"c2"})
@View({template:'i am c2'})
export class C2{
   constructor(@Parent() c:C1){
      console.log(c);
   }
}

@Component({selector:"app"})
@View({template:`<c1><c2></c2></c1>`, directives:[C1,C2]})
class App{}

bootstrap(App);
```
now it prints 
```C1 {}```

**Comment by SekibOmazic** [comment] 2015-05-13 11:14
@0Decoherence Sorry but I mixed typescript and atscript. My proposal helps when you use atscript/traceur. I had similar issues after updating to alpha.22, but I don't use typescript yet.

**Comment by Bogatinov** [comment] 2015-05-15 13:48
@0Decoherence [TS definition file](https://github.com/borisyankov/DefinitelyTyped/tree/master/angular2) is not yet complete, so it does not support @Parent and @Ancestor annotations. You can make a PR since I have been trying to complete the annotations for @Inject and @Injectable without much luck.

**Comment by alexeagle** [comment] 2015-05-20 18:03
We are working on the complete definitions file, see https://github.com/angular/angular/issues/1966

**Comment by jomeier** [comment] 2015-05-30 14:58
@alexeagle 
Same here but different error message with Alpha 25:

```javascript
/// <reference path="../../Scripts/typings/angular2/angular2.d.ts" />    
import {Component, View, bootstrap} from 'angular2/angular2';
import {Parent} from 'angular2/annotations';

@Component({
    selector: 'yeha',
})
@View({
    template: ''
})
export class yeha2 {
    constructor(@Parent() myf: yeha1) {
        var dd = 0;
    }
}


@Component({
    selector: 'app'
})
@View({
        template: '<yeha></yeha>',
       directives: [yeha2]
})
export class yeha1 {
    constructor() {
        var dfdf = 0;
    }
}
```

I modified my angular2.d.ts with the ones from  @0Decoherence : 

```javascript
declare module "angular2/annotations" {

    function Parent(): (target: Type) => any;
    function Ancestor(): (target: Type) => any;
}
```

The error message is:                                                                  Angular2.dev.js: 17335

```javascript
Cannot resolve all parameters for yeha2. Make sure they all have valid type or annotations.

Error
    at NoAnnotationError.BaseException (https://code.angularjs.org/2.0.0-alpha.25/angular2.dev.js:7159:25)
    at new NoAnnotationError (https://code.angularjs.org/2.0.0-alpha.25/angular2.dev.js:10480:63)
    at _extractToken (https://code.angularjs.org/2.0.0-alpha.25/angular2.dev.js:19698:13)
    at https://code.angularjs.org/2.0.0-alpha.25/angular2.dev.js:19661:14
    at Array.map (native)
    at Function.execute.ListWrapper.map (https://code.angularjs.org/2.0.0-alpha.25/angular2.dev.js:7589:26)
    at _dependenciesFor (https://code.angularjs.org/2.0.0-alpha.25/angular2.dev.js:19660:24)
    at execute.Binding.resolve (https://code.angularjs.org/2.0.0-alpha.25/angular2.dev.js:19788:28)
    at Function.execute.DirectiveBinding.createFromBinding (https://code.angularjs.org/2.0.0-alpha.25/angular2.dev.js:23458:30)
    at Function.execute.DirectiveBinding.createFromType (https://code.angularjs.org/2.0.0-alpha.25/angular2.dev.js:23493:37)
```

I compiled my project with Visual Studio 2013 + Typescript 1.5Beta (with --emitDecoratorMetadata)
Angular2.dev.js is included in my main html file together with traceur 0.0.87

Could you give us a hint about how to modify the angular2.d.ts or is the cause of this errors not related to the type definitions ?

Thanks,

Josef

**Comment by mhevery** [comment] 2015-06-01 01:23
This is because we don't have the right `.d.ts` file. Closing since we are tracking it else where.

**Closed by mhevery** 2015-06-01 01:23 UTC

**Comment by bcalou** [comment] 2015-06-03 16:55
Hi, I apologize for commenting on a closed issue, but I got the same problem as @jomeier (did you find a wayaround ?). So is there a solution right now or should we just wait for a new version of the .d.ts file ? Thanks.

**Comment by alexeagle** [comment] 2015-06-03 18:25
We are working on generating the complete .d.ts file right now. I hope
we'll have something by the end of this week.

**Comment by neokeats** [comment] 2015-06-19 10:27
since we are tracking it else where.

it would be nice to reference it, not just closing like that...
