### ISSUE TITLE
Bug after update to next.10 from next.9 (Unable to copy assets: EPERM: operation not permitted, copyfile)

### ISSUE THREAD

**Issue by kolkov** [angular/angular#33122] opened 2019-10-12 05:52 UTC
Hi!
Before upgrade all worked fine, but after I get an strange error:
![image](https://user-images.githubusercontent.com/3740898/66695633-b7a46a80-eccc-11e9-85d0-e2dd5c5f9909.png)

Angular CLI: 9.0.0-next.9
Node: 12.6.0
OS: win32 x64
Angular: 9.0.0-next.10
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-next.9
@angular-devkit/build-angular     0.900.0-next.9
@angular-devkit/build-optimizer   0.900.0-next.9
@angular-devkit/build-webpack     0.900.0-next.9
@angular-devkit/core              7.3.9
@angular-devkit/schematics        7.3.9
@angular/cli                      9.0.0-next.9
@angular/pwa                      0.13.9
@ngtools/webpack                  9.0.0-next.9
@schematics/angular               7.3.9
@schematics/update                0.900.0-next.9
rxjs                              6.5.3
typescript                        3.5.3
webpack                           4.41.0

**Comment by dannyskoog** [comment] 2019-10-12 08:51
Fixed in https://github.com/angular/angular-cli/pull/15818 and will be available with next CLI release

**Comment by gkalpak** [comment] 2019-10-12 15:32
Closing as duplicate of angular/angular-cli#15816.

**Closed by gkalpak** 2019-10-12 15:32 UTC
