### ISSUE TITLE
Route Resolve Errors: Uncaught (in promise)

### ISSUE THREAD

**Issue by aleixsuau** [angular/angular#21534] opened 2018-01-14 18:38 UTC
## I'm submitting a... 
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[X] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
When a router resolve fails, Angular throws an "Uncaught (in promise)" error. I can't find the way to know that it is a route resolve error from the ErrorHandler. Seems that it is only possible listening to the router events.

## Expected behavior
Have a route resolve specific error.

## What is the motivation / use case for changing the behavior?
It would be nice being able to catch the route resolve errors from the ErrorHandler.

Thanks!

**Comment by jotatoledo** [comment] 2018-01-14 19:40
if the code can throw in your guard@canActivate, why not catch it there in the first place?

**Comment by aleixsuau** [comment] 2018-01-15 10:55
Hi @jotatoledo ,

Thanks for your answer.

I have found this need while trying to build a general ErrorHandler for the app that catches all the Server and Client errors and reacts to them. 

In the case of the route resolve error, I would like to redirect to the 404 page when the data for a route is not available. The way you comment, I would need to implement a catch in every route resolve, injecting the router to redirect from there to the 404 page.

Further more, I don't get why if what is happening is an HttpErrorResponse (data not available on the Server), Angular throws an Uncaught (in promise) error.

I see some thumbs down on this, so I guess I'm missing something. I go to investigate.

Thanks!

**Comment by jasonaden** [comment] 2018-02-07 00:15
Thanks. This looks like a duplicate of #21415.

**Closed by jasonaden** 2018-02-07 00:15 UTC
Labels: comp: router
