### ISSUE TITLE
RegExp literals in expressions support

### ISSUE THREAD

**Issue by sam-s4s** [angular/angular#21978] opened 2018-02-01 23:26 UTC
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report
[ * ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
When putting a RegExp inside a template, the compiler fails.

## Expected behavior
It should compile the template correctly, and use the RegExp normally.

## Minimal reproduction of the problem with instructions
```
<div *ngFor="let a of b | blah : /\d+/"></div>
```

## What is the motivation / use case for changing the behavior?
It would be much more convenient to use RegExps directly. Otherwise you have to...
a) pass a string
b) create a RegExp using that string on the other end (in the case of a pipe)
c) use double backslashes to escape things like `\d`, which breaks actual RegExp rules, meaning you need to modify your RegExp when creating and testing, etc.
d) remember to remove the leading and trailing slashes, as the string input for RegExp doesn't like those

## Environment

<pre><code>
Angular version: 4.4.4
</code></pre>

**Comment by trotyl** [comment] 2018-02-02 02:15
Duplicate of #6419

**Comment by gkalpak** [comment] 2018-02-02 08:30
@sam-s4s, RegExp literals are not supported indeed, but you can still create a RegExp in your component and pass that:

```ts
@Component({
  ...
  template: '{{ '123abc' | myPipe:re }}
}
class MyComponent {
  re = /\d+/;
}
```

Although is would indeed be cool to have RegExp literal support, note that the templating language is not supposed to have feature-parity with JavaScript (it is just a subset with some extra Angular-specific semantics). Given that and the fact that parsing RegExps would be quite complicated (esp. if you also had to validate them :smiley:), my guess would be that RegExp literals will remain unsupported.

##
@trotyl, thx for pointing out that othr issue. Since it didn't have an explanation of why RegExp literals are not supported in templates, I'll leave this one open as a feature request.

##
Let's see what the `compiler` people think.

**Comment by trotyl** [comment] 2018-02-20 07:26
> Let's see what the compiler people think.

I can act as compiler people as long as they're willing to have it. 😃

**Comment by sam-s4s** [comment] 2018-02-20 21:54
I think it'd be handy :)

In this particular use-case it's for a pipe, and one of the handy things about pipes is that they can be re-used in multiple locations in the template. That'd be kinda ruined if you then had to make all these variables to store your regexp in :P

I know it's not a huge issue, but maybe it'd be nice.

I don't think parsing the regexp is important - only finding the start and end of it.

**Comment by mhevery** [comment] 2020-12-02 21:34
We don't think this aligns with our vision for Angular. The main concern is that this will further complicate the syntax and require maintenance from the Angular team. Creating RegExp is relatively easy in component and it than can be used from template.

**Closed by mhevery** 2020-12-02 21:34 UTC
Labels: comp: core, core: binding & interpolation, feature
