### ISSUE TITLE
(http) Parse HttpErrorResponse body if JSON received from server

### ISSUE THREAD

**Issue by cwayfinder** [angular/angular#19377] opened 2017-09-25 12:43 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

![image](https://user-images.githubusercontent.com/355902/30808573-5a70d644-a207-11e7-9bea-3a5eca049a82.png)
In case of error we have a string in the `error` property on the HttpErrorResponse

## Expected behavior

I would like to have the error parsed (like it's implemented for the body in the successful response)

## Minimal reproduction of the problem with instructions
Do any post call using HTTP client

## Extra
I can point at the specific file in the angular codebase - https://github.com/angular/angular/blob/452a7ae88b3b1144369f884c10de044502dc3c65/packages/common/http/src/xhr.ts#L212 (where we create a new HttpErrorResponse)
![image](https://user-images.githubusercontent.com/355902/30808494-fcf269f6-a206-11e7-9579-618a636b3eb7.png)

**Comment by trotyl** [comment] 2017-09-25 14:12
Duplicate of https://github.com/angular/angular/issues/19103.

**Comment by vicb** [comment] 2017-09-26 16:50
Closing as duplicate (thanks @trotyl)

**Closed by vicb** 2017-09-26 16:50 UTC
Labels: comp: common/http

**Comment by b0rgbart3** [comment] 2018-02-04 23:24
I'm experiencing this problem too.  What's the fix?
