### ISSUE TITLE
Angular LS doesn't work with node.js 9

### ISSUE THREAD

**Issue by anstarovoyt** [angular/angular#21420] opened 2018-01-09 18:03 UTC
I am working on Angular LS integration in WebStorm.
I have noticed that the integration doesn't work with node.js 9 because of the code
in node_modules/@angular/language-service/bundles/language-service.umd.js:8
```

var $reflect = {defineMetadata: function() {}, getOwnMetadata: function(){}};
((typeof global !== 'undefined' && global)||{})['Reflect'] = $reflect;
```
Source of the error: https://github.com/angular/angular/blob/master/packages/language-service/rollup.config.js#L49

Node.js throws the exception in this line https://github.com/nodejs/node/blob/master/lib/internal/process/next_tick.js#L63:
 
```
Reflect.apply(callback, undefined, tock.args);
 error:           Reflect.apply(callback, undefined, tock.args);
 TypeError: Reflect.apply is not a function
 error: TypeError: Reflect.apply is not a function
     at process._tickCallback (internal/process/next_tick.js:152:19)
```

**Comment by kyliau** [comment] 2018-01-10 00:23
Angular does not support Node 9 yet, but we will keep this in mind when upgrading.
https://github.com/angular/angular/blob/master/package.json#L11

**Comment by mhegazy** [comment] 2018-05-07 21:16
@chuckjaz any plans on fixing this issue? we are seeing it on VS as well..

**Comment by brian428** [comment] 2018-05-23 20:45
This seems rather pressing, especially since Node is now up to 10.x.

**Comment by gkalpak** [comment] 2018-06-04 19:41
I created #24299, but I am not sure how to test it (I couldn't reproduce the issue 😕).

**Comment by anstarovoyt** [comment] 2018-06-04 19:53
I have tested the changes it works fine!

**Comment by anstarovoyt** [comment] 2018-07-03 16:32
any updates?

**Comment by prigara** [comment] 2018-07-06 14:49
We've implemented a workaround in WebStorm, but we are really hoping to see the PR with the fix merged soon.

**Closed** 2018-07-09 22:10 UTC
Labels: comp: language-service, freq1: low, severity3: broken, type: bug/fix

**Comment by evandrogrm** [comment] 2019-02-19 17:02
I had this problem and updated `@angular/language-service` to version `7.1.0` (`npm i -G @angular/language-service@7.1.0`) and now works
