### ISSUE TITLE
Download links on https://angular.io/ is wrong

### ISSUE THREAD

**Issue by my8bird** [angular/angular#5057] opened 2015-11-02 01:10 UTC
Not sure if this is the correct place for this issue but it seemed a likely spot.

The text on https://www.npmjs.com/package/angular2 sends the user to https://github.com/angular/angular.js for getting the angular 2 source.  This link is incorrect and should point to this repo.

I got to the above page following the below link navigation
 * https://angular.io/ click `Download` link
 * https://angular.io/download/ select `Angular 2 JavaScript` row

**Comment by pkozlowski-opensource** [comment] 2015-11-02 08:31
@my8bird this is not what I see... The generated HTML code is:

```HTML
<a class="hover-card is-button md-button md-default-theme" ng-transclude="" href="https://www.npmjs.com/package/angular2" md-button="md-button"><h3 class="ng-scope">Angular 2 JavaScript</h3><p class="ng-scope">Version 2.0.0-alpha</p></a>
```

I'm going to close this one as I can't reproduce, but if you keep seeing the pb make sure that your browser cache is cleared and report eventual problems in https://github.com/angular/angular.io (this is where docs website resides)

**Closed by pkozlowski-opensource** 2015-11-02 08:31 UTC
