### ISSUE TITLE
RC.3: Support for the experimental syntax 'dynamicImport' isn't currently enabled

### ISSUE THREAD

**Issue by spock123** [angular/angular#33954] opened 2019-11-21 08:38 UTC
# 🐞 bug report

Upgrading my Angular 8.2 project to 9 RC.3 with Ivy, gives following errors for my lazy loaded modules:

```
SyntaxError: /home/lrj/project/ivy/src/app/app.routing.module.ts: Support for the experimental syntax 'dynamicImport' isn't currently enabled (15:29):

path: 'webcams',
  14 |         outlet: 'dialog',
> 15 |         loadChildren: () => import('./feature-modules/webcams/webcams.module').then(m => m.WebcamsModule)
     |                             ^
  16 |     },

Add @babel/plugin-syntax-dynamic-import (https://git.io/vb4Sv) to the 'plugins' section of your Babel config to enable parsing.


```

### Is this a regression?

I think so, did not have this issue with RC.2

Disabling IVY makes everything work as expected.

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 9.0.0-rc.3
Node: 12.2.0
OS: linux x64
Angular: 9.0.0-rc.3
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router, service-worker

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.900.0-rc.3
@angular-devkit/build-angular      0.900.0-rc.3
@angular-devkit/build-optimizer    0.900.0-rc.3
@angular-devkit/build-webpack      0.900.0-rc.3
@angular-devkit/core               8.3.19
@angular-devkit/schematics         8.3.19
@angular/cdk                       8.2.3
@angular/material                  8.2.3
@angular/material-moment-adapter   8.2.3
@ngtools/webpack                   9.0.0-rc.3
@schematics/angular                9.0.0-rc.3 (cli-only)
@schematics/update                 0.900.0-rc.3
rxjs                               6.5.3
typescript                         3.6.4
webpack                            4.41.2

</code></pre>

**Anything else relevant?**

ts.config:

```
{
  "compileOnSave": false,
  "angularCompilerOptions": {
    "enableIvy": true
  },
  "compilerOptions": {
    "baseUrl": "./src",
    "importHelpers": true,
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "module": "esNext",
    "moduleResolution": "node",
    "noImplicitAny": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es2015",
    "skipLibCheck": true,
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2018",
      "dom"
    ],
    "paths": {
      "@store/*": ["app/store/*", "app/store"],
      "@store": ["app/store/*", "app/store"],
      "@modules/*": ["app/modules/*", "app/modules"],
      "@modules": ["app/modules/*", "app/modules"],
      "@main/*": ["app/main/*", "app/main"],
      "@models/*": ["app/models/*", "app/models"],
      "@models": ["app/models/*", "app/models"],
      "@main": ["app/main/*", "app/main"],
      "@environment": ["environments/environment"],
      "@lib/*": ["app/lib/*", "app/lib"],
      "@lib": ["app/lib/*", "app/lib"],
      "@iticket-business/*": [ "app/modules/iticket-business/*", "app/modules/iticket-business"]
    }
  }
}

```

**Comment by khalilou88** [comment] 2019-11-21 10:30
I have the same error but only with i18n. otherwise the app work without errors.

**Comment by spock123** [comment] 2019-11-21 10:31
@khalilou88 I'm also using i18n.. maybe there's something there?

**Comment by alan-agius4** [comment] 2019-11-21 14:03
Duplicate of https://github.com/angular/angular-cli/issues/16248

**Closed by alan-agius4** 2019-11-21 14:03 UTC
