### ISSUE TITLE
Styles are not removed by router after navigation when using ViewEncapsulation.None

### ISSUE THREAD

**Issue by kyledevans** [angular/angular#16670] opened 2017-05-09 23:28 UTC
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
If a component uses ViewEncapsulation.None then those styles are never removed from the DOM after the user navigates to a different route.  For example if component Foo styles the `<p>` tag with a red background, and then the user navigates to a different route, all `<p>` tags on the next page will have a red background.

**Expected behavior**
Styles should not outlive the component that defines them.  A `<p>` tag should look the same, no matter what the routing history is.

**Minimal reproduction of the problem with instructions**
1. Create 2 routes "Foo" and "Bar".
2. Configure the main component for Foo so that it uses ViewEncapsulation.None.
3. Create a `<p>` elements in both the Foo and Bar components.
4. In the component for Foo, create a style `p { background-color: #F00; }`.
5. In the main application component create some routerLinks to allow navigation between the Foo and Bar routes.
6. Run the application
7. Click on the link for "Foo".  Note the red background on the `<p>` element.  This is expected.
8. Click on the link for "Bar".  Note that the `<p>` element is red.  This is NOT expected.
9. Refresh the page.
10. Click on the link for "Bar".  Note that this time the `<p>` element is not red.
11. Navigate to "Foo" then go back to "Bar".  The `<p>` element is now red again.  This is NOT expected.

**Plnker**

1. [Plnker](http://plnkr.co/edit/nG8gSD4Xc492ceIGlAeC?p=preview)
2. In the plunker, click on the "Foo" link first.
3. Then click on the "Bar" link.  Note the red `<p>` tag.  This is NOT expected.
4. Refresh the page, click on the "Foo" link.  Note the red `<p>` tag.  This is expected.
5. Click on the "Bar" link.  Then click on "Foo" again.  Note the red `<p>` tag.  This is NOT expected.

**What is the motivation / use case for changing the behavior?**
For every page/component that is rendered into the `<router-outlet>`, I will configure it so that it uses ViewEncapsulation.None.  This allows me define semi-global styles for individual pages.  So for example if I want all `<input>` tags to have 200px width only on page Foo, I can just set the style in the FooComponent stylesheet.

I shouldn't have to worry that styles on page Foo can bleed over into page Bar.  Worse is that this effect is entirely dependent on the exact order that the user navigates around the application.  For any non-trivially sized application, this represents an unreasonable testing burden.  For the moment I have decided that it's best that I don't use the angular router when navigating between "feature pages" and fallback to conventional `<a>` links.

**Please tell us about your environment:**
Windows 10. Angular CLI and Notepad++, npm

* **Angular version:** 2.0.X
Angular 4.1.1.  This may impact older versions, but I wouldn't have seen it until today because I normally don't navigate between feature pages in my application without performing a full page load.  I just happened to forget to do it this one time.

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome, Firefox, Edge.  Haven't tested others.
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript

* **Node (for AoT issues):** `node --version` =

**Comment by webdevan** [comment] 2017-11-11 16:49
Can confirm this bug is still present (Angular 5.0.0). Are there any plans to fix it?

**Comment by mithleshjs** [comment] 2017-12-10 20:05
This bug is still there and there is no workaround.

**Comment by NullEnt1ty** [comment] 2017-12-11 07:54
@mithleshjs As a workaround I use `href="..."` instead of `routerLink="..."`. This reloads the entire page, which is not optimal, but it works.

**Comment by ikuznalex** [comment] 2018-01-08 08:12
The bug is still reproducible. It would be nice to have it fixed.

**Comment by trotyl** [comment] 2018-02-08 14:42
Duplicate of #14238 (Not sure if some decision changed or not)

**Comment by A-Diddy** [comment] 2018-02-16 23:48
According to the [Angular docs on style scope](https://angular.io/guide/component-styles#style-scope)...

> The styles specified in @Component metadata apply only within the template of that component.

Not sure if I'm missing something here but the functionality described in the documentation does not appear to match the way it's actually working.

**Comment by woeterman94** [comment] 2018-08-01 14:51
Any update? I can still reproduce this in the latest version.

**Comment by shreyansh-zazz** [comment] 2018-11-21 07:34
Any update on this one? I having the same problem.

**Comment by trotyl** [comment] 2018-11-21 08:00
It's the expected behavior, when using [`ViewEncapsulation.None`](https://angular.io/api/core/ViewEncapsulation#None), you're responsible for making sure it doesn't affect any other component:

> None: 2 | Don't provide any template or style encapsulation.

Otherwise you do need encapsulation and should set it correctly.

**Comment by MaximeMorin** [comment] 2018-11-21 14:05
What's the purpose of `ViewEncapsulation.None` then?  I find it odd that leaking styles is the intended behavior; might as well deprecate it and suggest to declare styles globally.  That way, there's no surprise.

**Comment by trotyl** [comment] 2018-11-21 14:10
> What's the purpose of `ViewEncapsulation.None` then?

It's for performance consideration, which avoids extra attributes on element in rendering or regex replacement:

https://github.com/angular/angular/blob/cf0968f98e844043a0f6c2548201f3c0dfd329a7/packages/compiler/src/directive_normalizer.ts#L186-L189

So if you can make sure that it won't have any side-effect then you can use it for better performance.

**Comment by kyledevans** [comment] 2018-11-21 14:44
So `ViewEncapsulation.None` is really only for **permanently** lazy loading global styles.  If that is indeed the intended behavior, perhaps that should be documented?  Because I ran into the original usecase within the first few days of learning Angular.  And have yet to have a need for what it currently does.

It would be nice to have some way to have encapsulation that both adds and removes global styles when the directive is rendered and destroyed.

However if that's not realistically going to happen then I have no objection to closing this ticket.

**Comment by trotyl** [comment] 2018-11-21 14:55
@kyledevans It's a hard requirement that no component style would affects other component, not about the timing. The timing matters only when you failed to achieve that.

**Comment by MaximeMorin** [comment] 2018-11-21 15:03
@trotyl Thank you for the clarification.  I didn't know that `ViewEncapsulation.None` is a performance optimization over emulated.

**Comment by shreyansh-zazz** [comment] 2018-11-21 15:19
If it is the default behavior of `ViewEncapsulation.None` then let it be. Can not we introduce another property in `ViewEncapsulation` for add and removing styles globally?

**Comment by webdevan** [comment] 2018-11-21 22:36
Unless I'm missing something the docs don't say that ViewEncapsulation.None is for performance gains only and that there's **a hard requirement for component CSS not to affect anything outside it**.

I understood ViewEncapsulation.None to mean "global css" and have successfully used it as such. An example being an "off-canvas menu" component which includes CSS that affects translate and overlay on the body. Another example where I'd like to use it but can't is for a "checkout page" which modifies the "site header" just with CSS just on the checkout page. It's a nice way of keeping your CSS logically together instead of coordinating CSS between multiple components.

If ViewEncapsulation.None really is not supposed to facilitate global CSS then it should probably be documented as such and I agree that it would be really good to add something like ViewEncapsulation.Global for the valid useful cases described in this thread.

**Comment by trotyl** [comment] 2018-11-22 02:59
@webdevan 

> The styles specified in `@Component` metadata `apply only within the template of that component`.

https://angular.io/guide/component-styles#style-scope

It's already put in RED, if this not being enough, what level of highlight do you expect?

If you want add global styles, then it's not component styles, and not related to any encapsulation. But it could be a valid feature request for utility service like `Title` or `Meta`.

**Comment by webdevan** [comment] 2018-11-23 06:40
When I searched the docs for ViewEncapsulation the only result is this page https://angular.io/api/core/ViewEncapsulation which says
> None - Don't provide any template or style encapsulation.

which implies "global styles" and I couldn't find any explanation that "None" is purely or performance.

> The styles specified in @Component metadata apply only within the template of that component.

I'd argue that this sentence is technically false (because of ViewEncapsulation.None).

ViewEncapsulation does seem like the appropriate mechanism to use for global component styles because it does what it says (encapsulate or not encapsulate the component styles to the scope of the element).

**Comment by trotyl** [comment] 2018-11-23 07:03
> The styles specified in `@component` metadata _apply only within the template of that component_

This is a requirement (for both framework and user), apply to any `ViewEncapsulation`.

> Don't provide any template or style encapsulation.

This means the encapsulation is not ensured by framework, but purely on user-side. 

> I'd argue that this sentence is technically false (because of ViewEncapsulation.None).

It's also technically false in `ViewEncapsulation.Emulated`:

+ https://github.com/angular/angular/issues/5059
+ https://github.com/angular/angular/issues/16676
+ https://github.com/angular/angular/issues/20449

And all of them are BUGs (or technically limitation that cannot be achieved) as the leaking styles are always unexpected behavior.

> ViewEncapsulation does seem like the appropriate mechanism to use for global component styles because it does what it says

No, it's simply not. `ViewEncapsulation.None` means *there's no need for the framework to perform encapsulation* because either:

+ There's no component styles;
+ There's no component template;
+ It's ensured by user in other means.

**Comment by trotyl** [comment] 2018-12-13 02:03
@A-Diddy 

> Allow styles (themes) to be applied to child components

A component style cannot leak to its children as well, unless the child components declare what styles can be affected by others, that's exactly why `>>>` being dropped in the first place, while [CSS Shadow parts](https://www.w3.org/TR/css-shadow-parts-1/) and [Constructable Stylesheet](https://wicg.github.io/construct-stylesheets/) being introduced.

You can still join the [long thread w3c thread](https://github.com/w3c/webcomponents/issues/468) discussion if you'd like.

CSS Shadow Parts is a valid approach in the Web and [likely to be supported by Angular](https://github.com/angular/angular/issues/22515) as well.

> The W3C and Chromium project are planning to deprecate the default behavior of applying CSS globally from within HTML imports and ES6 modules

The entire HTML imports feature [has been dropped for a long time](https://github.com/w3c/webcomponents/issues/677), and [browsers are removing its support](https://www.chromestatus.com/feature/5144752345317376), and amending to HTML imports is a nonsense already.

**Comment by sinanspd** [comment] 2019-02-22 06:35
I would like to make an addition to this issue. A number of material components use ViewEncapsulation.None (example -> form-fields: https://github.com/angular/material2/blob/master/src/lib/form-field/form-field.ts), this causes issues in the cases where one might want to have contrasting components or section, or use multiple themes. I will open a separate ticket in the material repo 

> It's the expected behavior, when using [`ViewEncapsulation.None`](https://angular.io/api/core/ViewEncapsulation#None), you're responsible for making sure it doesn't affect any other component:
> 
> > None: 2 | Don't provide any template or style encapsulation.
> 
> Otherwise you do need encapsulation and should set it correctly.

Apparently the angular team itself did not fulfill this responsibility. 
My apologies but I fail to see the a proper use case for None. If one wants to share styling, they can surely create shared styling files or apply global styling. The styling inside a component should not be leaking into any other component under any circumstance in my opinion.

**Comment by trotyl** [comment] 2019-03-02 12:56
> I would like to make an addition to this issue. A number of material components use ViewEncapsulation.None

@sinanspd Could you elaborate? From what I can see all of its CSS contents are expected use case of `ViewEncapsulation.None`, all of its styling are properly scoped manually and will never affect an unrelated element.

**Comment by sinanspd** [comment] 2019-03-08 04:46
@trotyl 

Absolutely. This is an edge case example but parts of this have common applications. Let's say you have two components. One themed in a lighter color and one darker. You have material inputs in both components. 
Component 1, with light theme uses the default material input styling 
Component 2, with dark theme uses a custom styling to negate the input styles. 

You navigate from C1 -> C2 -> C1 and you will see that the component 1 material elements will be styled according to the C2 custom styling. 

I enforced a few things here for the sake of making a point but one example is here:

https://angular-e7x4k1.stackblitz.io

1) click the button, than click go back. You will see that the material input now has disappeared (it hasn't actually disappeared its styles got overwritten by the other component) 
2) now refresh the page, you will see it appear again

**Comment by trotyl** [comment] 2019-03-08 05:01
@sinanspd The issue in your repro is a general `::ng-deep` bug (https://github.com/angular/angular/issues/13724), doesn't relates to `ViewEncapsulation.None`.

**Comment by sinanspd** [comment] 2019-03-08 05:27
@trotyl ahh gotcha. Thanks, I missed that issue. However changing the ViewEncapsulation type seems to prevent this behaviour. That is why I originally came to this issue

**Comment by trotyl** [comment] 2019-03-08 05:55
@sinanspd 

> However changing the ViewEncapsulation type seems to prevent this behaviour.

No, it doesn't. Try remove material stuff you'll get the same result: https://stackblitz.com/edit/angular-3myhxv?file=src%2Fapp%2Fother.component.ts

**Comment by Falven** [comment] 2019-12-13 15:57
How is this still a thing in 2019. Following the simplest of examples as seen [here](https://www.w3schools.com/howto/tryhow_css_fullpage_demo.htm) in Angular is impossible because of this encapsulation dilemma.

**Comment by mustafakunwa** [comment] 2020-01-24 05:42
Any updates on the Issue I'm still getting it in Angular 6.1.1

**Comment by ash4aque** [comment] 2020-03-30 10:24
Use case, I want to override a css class of a components library stylesheet added globally, for a specific component in a specific route using viewEncapsulation.None so that the overrided class should only be applied in that specific component  NOT in whole pages. Is this not the right assumption. How we can we should deal with such scenarios.

**Comment by MaximeMorin** [comment] 2020-03-30 11:33
@ash4aque You have to "CSS namespace" your component so that the styles are only applied within that given "namespace".  Pretty much, you apply a specific class to a parent element in your component and then put all your specific styles inside that specific class.

`
.my-global-style {}

.my-parent-specific-class {
    .my-global-style {}  // Overrides.
}
`

**Comment by ash4aque** [comment] 2020-03-30 19:58
> @ash4aque You have to "CSS namespace" your component so that the styles are only applied within that given "namespace". Pretty much, you apply a specific class to a parent element in your component and then put all your specific styles inside that specific class.
> 
> ```
> .my-global-style {}
> 
> .my-parent-specific-class {
>     .my-global-style {}  // Overrides.
> }
> ```

@MaximeMorin thanks for the pointer.

**Comment by muuvmuuv** [comment] 2020-04-08 00:46
Adding my use case here: I have a dynamic form module which I use, to create forms in many components. Now I want to give them different bottom margins. Only with `ViewEncapsulation.None` the margins get applied when I use `app-form { style }` but they are shared between my pages which makes the styles obsolete on pages where I use the default bottom margin from the module. Ignore the fact that I use different margins here, IMO Angular should provide "per-page" styles!

**Comment by connectpritam** [comment] 2020-04-24 06:09
I have to use different selectors as a workaround. Angular sucks !! big time.

**Comment by atscott** [comment] 2020-05-27 17:33
Confirmed in v9 with Ivy: https://stackblitz.com/edit/angular-ivy-3ffq5x?file=src%2Fapp%2Ffoo%2Ffoo.component.ts

**Comment by dssagar93** [comment] 2021-02-20 11:26
2021, I am still facing the same issue.

**Comment by petebacondarwin** [comment] 2021-02-20 13:06
I think this is by design. Styles are like code in an Angular app. Once they are loaded (e.g. by lazy loading an NgModule via a route navigation) they are never removed. Putting styles that can affect the app outside the component template seems to be an anti-pattern to avoid in my opinion.

**Comment by totszwai** [comment] 2021-08-04 01:19
Can some expert from Angular team here tell us where, which function and how Angular is inserting `<style>` into the DOM?
I mean technically we could just add an `id` into the `<style id="whatever">` and then delete the `<style>` tag on the fly right before adding the new one in... or even just replace the content with the `id`.

Just tell us where the function is, so we could piggyback or override it with additional code to append an `id` and remove it ourselves.

https://user-images.githubusercontent.com/4440365/128106643-a9ebd1d4-1f86-446e-bb74-6acca924afbd.mp4

**Comment by OrlandoRibera** [comment] 2022-02-04 02:43
Any updates?

**Comment by totszwai** [comment] 2022-02-05 20:28
This issue is dated 2017... FIVE years.
Shame. Looks like they are gonna just let this die. 👎

**Comment by Jad31** [comment] 2022-03-05 14:15
I am facing the same problem in version 13.2.

**Comment by nasari123** [comment] 2022-04-01 15:11
I found a way of solving this problem, it is a kind of a white hat hacking
In my .ts file

1. I add ViewEncapsulation.None to @Component

```
@Component({
  selector: 'my-example-component', // remember this name
  templateUrl: './-example-component.html',
  styleUrls: ['./-example-component.scss'],
  encapsulation: ViewEncapsulation.None // here
})
```
(this will delete the encapsulation of my style in the app)

2. I encapsulate the css manually:
lets say i have this style in example-component.scss file
```
.hello{
    background-color: red;
}
//... other stuff
```
===>
```
my-example-component{ //this is my component name
    .hello{
        background-color: red;
    }
    //... other stuff
}
```

**Comment by quentinhoareau** [comment] 2022-11-15 21:05
I has the same, but to solve this you need to do that : 

I add ViewEncapsulation.None to @Component
```
@Component({
  selector: 'app-my-example-component', 
  templateUrl: './my-example-component.html',
  styleUrls: ['./my-example-component.scss'],
  encapsulation: ViewEncapsulation.None
})
```

I encapsulate the CSSmanually:
This way will be match only the <body> has the selector "app-my-example-component"
```
body:has(app-my-example-component){
   background: #161616;
}

//... other stuff
===>
```

**Closed** 2023-02-16 23:31 UTC
Labels: feature, area: core, core: stylesheets, feature: under consideration
