### ISSUE TITLE
Missing equiv-text and wrong line number from library in extracted i18n messages.xlf

### ISSUE THREAD

**Issue by divdavem** [angular/angular#40689] opened 2021-02-03 11:08 UTC
# 🐞 bug report

### Affected Package

This issue seems to be caused by a wrong source map generated by ngcc in `__ivy_ngcc__/fesm2015` when using a library that contains localized messages and published for compatibility with the view engine (as recommended in https://v9.angular.io/guide/ivy#maintaining-library-compatibility).

### Is this a regression?

I have not checked with a previous version of Angular.

### Description

When using a library that contains localized messages and published for compatibility with the view engine (as recommended in https://v9.angular.io/guide/ivy#maintaining-library-compatibility), extracting localization messages with `ng extract-i18n` produces a [`messages.xlf`](https://github.com/divdavem/ngEquivTextBug/blob/master/myapp/messages.xlf#L6) file that does not contain any `equiv-text` attribute for the interpolation, and that has a wrong line number.

Also, when looking at the generated source map in `__ivy_ngcc__/fesm2015` with [source-map-visualization](http://sokra.github.io/source-map-visualization), it is obvious that there is a problem with the source map.

## 🔬 Minimal Reproduction

Create a library:
```sh
ng new mylib --no-create-application
cd mylib
ng generate library mylib
```

Add the `i18n` attribute and a placeholder in `mylib.component.ts`:

```ts
  template: `
    <p i18n>
      Hello {{name}}!
    </p>
  `,
```

Build the library in prod mode:

```sh
ng build --prod
```

Then create an application:

```sh
ng new myapp
cd myapp
ng add @angular/localize
```

Use the library in `package.json` in `myapp`:

```json
{
    "dependencies": {
        ...
        "mylib": "file:../mylib/dist/mylib"
    }
}
```

Install dependencies:

```sh
npm install
```

Import the library in `app.module.ts`:

```ts
import { MylibModule } from 'mylib';
...
  imports: [
    BrowserModule,
    MylibModule
  ],
```

Use it in some component:

```html
<lib-mylib></lib-mylib>
```

And extract messages to be localized:

```sh
ng extract-i18n
```

Check my reproduction repository here: https://github.com/divdavem/ngEquivTextBug

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 11.1.2
Node: 12.18.4
OS: linux x64

Angular: 11.1.1
... animations, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1101.2
@angular-devkit/build-angular   0.1101.2
@angular-devkit/core            11.1.2
@angular-devkit/schematics      11.1.2
@angular/cli                    11.1.2
@schematics/angular             11.1.2
@schematics/update              0.1101.2
rxjs                            6.6.3
typescript                      4.1.3
</code></pre>

**Anything else relevant?**

In some other cases (from which I extracted the reproduction scenario), I noticed that `equiv-text` can be present and contains random code not related with the actual placeholder.

**Comment by petebacondarwin** [comment] 2021-02-03 16:06
Hi @divdavem - thanks for this really great and comprehensive reproduction and analysis.

I can confirm what you are seeing. I am afraid that we will not be able to solve it via ngcc. Ngcc does a very heavy-handed injection of code into library source files (using magic-string). The new code is inserted as a single block, so the source-mapping is unsurprisingly unrefined.

We have in development a new approach for library distribution, which involves a partial compilation pre-publication, followed by a linking step at application build time. This is able to carry through the source-mapping information more accurately. I'll see if I can create a PR on your reproduction to demo this.

**Comment by petebacondarwin** [comment] 2021-02-03 19:04
By the way, in the future we hope to change the Angular Package Format (APF) to specify how a library can publish its own translation files. It is possible to extract translations directly from the library using a combination of an ivy build and the standalone binary. So in the case of your reproduction:

```bash
cd mylib
ng build # note the lack of --prod makes it build with ivy
$(npm bin)/localize-extract -r . -s "dist/mylib/fesm2015/*.js" -f xlf -o messages.xlf
```

This generates:

```xml
<?xml version="1.0" encoding="UTF-8" ?>
<xliff version="1.2" xmlns="urn:oasis:names:tc:xliff:document:1.2">
  <file source-language="en" datatype="plaintext" original="ng2.template">
    <body>
      <trans-unit id="1638894134994447485" datatype="html">
        <source> Hello <x id="INTERPOLATION" equiv-text="{{name}}"/>! </source>
        <context-group purpose="location">
          <context context-type="sourcefile">projects/mylib/src/lib/mylib.component.ts</context>
          <context context-type="linenumber">6,8</context>
        </context-group>
      </trans-unit>
    </body>
  </file>
</xliff>
```

where you can see the `equiv-text` and correct location.

**Comment by petebacondarwin** [comment] 2021-02-04 12:32
An update on how this will work with the linker:

The good news is that it will work correctly - you will be able to extract i18n messages from libraries that have been imported into the app.

 The bad news is that there is a small bug in the CLI integration with the linker which means that linked files do not get source-maps right now - so the extraction currently has a similar problem to ngcc. That bug should be fixed shortly so in the future this will not be a problem.

**Comment by divdavem** [comment] 2021-02-04 16:42
@petebacondarwin Thank you very much for your very interesting explanations. I had noticed that the issue was not happening with the Ivy build, but I did not know about the linker and the plans to update the Angular Package Format for libraries to publish their own translation files.
Even though it is still in development, is the linker already usable? How can I try it?
Thank you in advance!

**Comment by petebacondarwin** [comment] 2021-02-04 19:01
Yeah a very early implementation is hidden inside 11.1. I'll push a PR to your repro as an example...

**Comment by divdavem** [comment] 2021-02-16 17:17
> Yeah a very early implementation is hidden inside 11.1. I'll push a PR to your repro as an example...

@petebacondarwin I suppose you are very busy... when do you think you will be able to open the PR you talked about? Or is there any document or source file that I could read to know how to use the linker? Thank you in advance!

**Comment by petebacondarwin** [comment] 2021-02-16 19:40
Hi @divdavem - I was blocked on a small bug in the CLI, which prevented it from working out of the box.  I'll check to see if that was fixed, and get something to you this week. Sorry about the delay.

**Comment by petebacondarwin** [comment] 2021-02-17 14:27
Unfortunately there are still some source-mapping issues with partial compilation but I will post the PR to give you an idea of where we are going anyway.

**Comment by petebacondarwin** [comment] 2021-02-17 14:37
https://github.com/divdavem/ngEquivTextBug/pull/1

**Comment by petebacondarwin** [comment] 2021-03-06 13:43
I tried updating my PR to the latest versions of Angular and Angular CLI but there is still a problem...
Here is an experiment that @clydin and I were discussing to resolve this https://github.com/angular/angular-cli/pull/20076

**Comment by dylhunn** [comment] 2023-02-17 17:51
Closing, because it seems this is an ngcc bug, and ngcc is now removed. Please comment if this characterization is not accurate.

**Closed by dylhunn** 2023-02-17 17:51 UTC
Labels: area: i18n, P4

**Comment by petebacondarwin** [comment] 2023-02-17 18:28
Ngcc is removed 🥳
