### ISSUE TITLE
@Input gives error when it is undefined in parent.

### ISSUE THREAD

**Issue by zaidchauhan** [angular/angular#7688] opened 2016-03-21 12:02 UTC
In Angular1 when we have ng-model="obj.prop" and if obj does not exist, It will not throw any error. If user type anything on that input new obj Object created with prop.

However, In Angular 2 when we pass undefined object from parent to child component as @Input and use as [(ngModel)]="obj.prop", If obj is defined in parent it works and even sync data with parent component. But, if it is not defined there it give an error : "Cannot read property 'prop' of undefined"

If I use elvis operator as [ngModel]="field?.value" (ngModelChange)="field ? field.value = $event : null" It eliminate error but then it does not sync with parent component.

We are using this as part of dynamic component. And we does not know if that object is defined or not. If not it should be like it does in Angular 1.

**Comment by zaidchauhan** [comment] 2016-03-21 12:47
My scenario:
In parent component view

<one-line [title]="'First Name'" [(field)]="doc.firstName" ></one-line>

here, original object is doc.firstName in parent

now in child component 'one-line'
<span>{{title}}</span> <input type="text" [(ngModel)]="field.value">
or 
<span>{{title}}</span> <input type="text" [ngModel]="field?.value" (ngModelChange)="field ? field.value=$event : field = {value:$event}">

The only issue is if, doc.firstName is defined in parent, two way data binding works fine. But, if it is undefined in parent. then it only going to create one in child but will not sync with parent.

**Comment by zoechi** [comment] 2016-03-22 07:18
I think this is a dup of #7697

**Comment by pkozlowski-opensource** [comment] 2016-06-03 12:13
It is duplicate of #7697 indeed. Thnx @zoechi !!!!

**Closed by pkozlowski-opensource** 2016-06-03 12:13 UTC

**Comment by zaidchauhan** [comment] 2016-06-04 04:41
It's not duplicate.

In angular 1, we can pass ng-model to n-level of directives with two way data binding means, changes can be triggered in both direction from 0 to n level. How we can achieve same with Angular 2?

**Comment by pkozlowski-opensource** [comment] 2016-06-04 06:50
@zaidchauhan why do you think it is not duplicate of #7697 ? #7697 is about support of the .? operator in ngModel which, if I understand correctly, would give you the desired behaviour. 

Please go over discussion in #7697 and comment back if there are differences.

**Comment by zaidchauhan** [comment] 2016-06-04 08:41
If I understood correctly, #7697 is for elvis operator where we would like to have ng-model if that property exist.

Here my requirment is different. I request all of you to first read my requirment before marking it duplicate of other issue which is not relevent.

**Comment by zoechi** [comment] 2016-06-04 09:54
@zaidchauhan you could try to make it more clear instead of making accuses. You could even make a Plunker that demonstrates what you try to accomplish.
What does " does not sync with parent component." mean?
I still think it is a dup depending on what the exact solution will be for #7697
