### ISSUE TITLE
Unable to unit test Angular component with effect without TestBed

### ISSUE THREAD

**Issue by joeskeen** [angular/angular#54438] opened 2024-02-14 18:01 UTC
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

# Background information 

I prefer to unit test without TestBed. Arguing whether or not TestBed is good to use in pure unit tests (not integration tests) is outside the scope of this bug report.

When unit testing components without using TestBed, I instantiate my component instance directly, i.e. `new MyComponent()`. In older versions of Angular, this just worked fine as if your component required any dependencies, those dependencies were made clear in the constructor parameters.

Then came `inject`, the magical way to hide your dependencies wherever you want to in your code, obfuscating the component's dependencies. At first I fought hard against using `inject` for this reason (which became problematic for things like route guards that should/must be functions now), but I finally figured out how to unit test something that uses `inject` without requiring all of the overhead / breaching the unit boundary of `TestBed` (mostly). https://stackblitz.com/edit/ng-test-inject-no-testbed?file=src%2Fapp%2Fadmin.guard.spec.ts%3AL15

Then I started using signals and effects. I thought I could use the same approach as before, defining a fake injector and using `runInInjectionContext` to wrap the call to `new MyComponent()`. But no dice. My tests fail with this error:

```
NullInjectorError: NullInjectorError: No provider for InjectionToken !
```

After looking into it further (requiring a reading of the source code), I found this:

https://github.com/angular/angular/blob/dd8490f384af55e11126fd98be4bf1ad91831057/packages/core/src/render3/reactivity/effect.ts#L254

```ts
const handle = new EffectHandle(
      injector.get(APP_EFFECT_SCHEDULER), effectFn,
      (typeof Zone === 'undefined') ? null : Zone.current, destroyRef, injector,
      options?.allowSignalWrites ?? false);
```

OK, so I just need to provide a mock value in my unit test for `APP_EFFECT_SCHEDULER`, right?

Wrong.

Going to definition on that symbol brought me here:

https://github.com/angular/angular/blob/dd8490f384af55e11126fd98be4bf1ad91831057/packages/core/src/render3/reactivity/effect.ts#L46C1-L53C4

```ts
/**
 * Not public API, which guarantees `EffectScheduler` only ever comes from the application root
 * injector.
 */
export const APP_EFFECT_SCHEDULER = new InjectionToken('', {
  providedIn: 'root',
  factory: () => inject(EffectScheduler),
});
```

Basically this means it is IMPOSSIBLE to mock this, which makes it IMPOSSIBLE to use effects in unit tests without TestBed.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/ng-test-inject-no-testbed-sav1p5?file=src%2Fapp%2Fmy-component.spec.ts

### Please provide the exception or error you saw

```true
NullInjectorError: NullInjectorError: No provider for InjectionToken !
error properties: Object({ ngTempTokenPath: [ 'InjectionToken ' ] })
    at NullInjector.get (https://ng-test-inject-no-testbed-sav1p5.stackblitz.io/turbo_modules/@angular/core@17.1.3/fesm2022/core.mjs:5709:27)
    at R3Injector.get (https://ng-test-inject-no-testbed-sav1p5.stackblitz.io/turbo_modules/@angular/core@17.1.3/fesm2022/core.mjs:6153:33)
    at effect (https://ng-test-inject-no-testbed-sav1p5.stackblitz.io/turbo_modules/@angular/core@17.1.3/fesm2022/core.mjs:14410:46)
    at new MyComponent (https://ng-test-inject-no-testbed-sav1p5.stackblitz.io/~/src/app/my-component.ts:16:27)
    at eval (https://ng-test-inject-no-testbed-sav1p5.stackblitz.io/~/src/app/my-component.spec.ts:19:19)
    at runInInjectionContext (https://ng-test-inject-no-testbed-sav1p5.stackblitz.io/turbo_modules/@angular/core@17.1.3/fesm2022/core.mjs:6451:16)
    at UserContext.eval (https://ng-test-inject-no-testbed-sav1p5.stackblitz.io/~/src/app/my-component.spec.ts:18:42)
    at <Jasmine>
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 17.1.1
Node: 18.17.1
Package Manager: npm 9.8.1
OS: linux x64

Angular: 17.1.1
... animations, cli, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1701.1
@angular-devkit/build-angular   17.1.1
@angular-devkit/core            17.1.1
@angular-devkit/schematics      17.1.1
@schematics/angular             17.1.1
rxjs                            7.8.1
typescript                      5.3.3
zone.js                         0.14.3
```

### Anything else?

It's OK to provide framework-specific test tools/frameworks, but it should always be possible to test the code using plain old JavaScript without your testing library.

**Comment by alxhub** [comment] 2024-02-14 23:31
> Arguing whether or not TestBed is good to use in pure unit tests (not integration tests) is outside the scope of this bug report.

I think this is actually very relevant, though, and worth discussing the motivations and implications here. Here are a few assertions/statements that we can focus the discussion around:

## Statement 1: unit tests should not mock the framework

When the code under test relies on functionality from Angular, like `effect` execution, it shouldn't be the test author's responsibility to mock or fake that behavior. Doing so makes it very likely the test code will not run in the same way it does in production, which opens the door to production bugs. It also makes the tests brittle, since refactorings inside the framework can break the tests' assumptions that it makes while mocking. We see this all the time with developers mocking `ActivatedRoute` instead of using the router testing utilities.

## Statement 2: `TestBed` is the framework's test fake

`TestBed` is how Angular provides an environment suitable for unit testing, with the right DI context to support all of its functionality. For example, `TestBed` provides a fake of `PlatformLocation` to facilitate testing code that expects to interact with `window.location`. Effect scheduling is also integrated into `TestBed`.

## Statement 3: You don't _have_ to use `TestBed.createComponent` (but probably should)

`TestBed` provides an API to test a component's template rendering, which can be used to "interact" with the component the same way a user or a developer would (clicking on UI elements, setting inputs, etc).

If you're writing a "plain" unit test against the component's class only, and not concerned with the template, this is technically possible to do without `createComponent` and `ComponentFixture`, by calling `new MyCmp(...)`. You're right that `inject()` makes this a bit tricky, as components expect to be instantiated by the DI system in Angular.

An easy way to do this is to use `TestBed.runInInjectionContext` for tests:

```typescript
TestBed.configureTestingModule({
  providers: [
    // Configure DI as needed
    ...
  ],
});

TestBed.runInInjectionContext(() => {
  // inject() works if needed here
  const instance = new MyCmp(...);
});
```

When using `TestBed`'s injector instead of a manually created one, things like effect scheduling will be correctly wired up.

Note that testing this way is still not recommended because of Statement 1. Components may have logic that relies on framework concepts like `@ViewChild` queries or `input()` signals. Mocking these aspects of the component introduces a risk of the test behavior not matching real production behavior (for example, if someone changes the `@ViewChild` decorator arguments but doesn't adjust the test mock).

**Comment by maartentibau** [comment] 2024-02-17 20:26
I heard these statements of @joeskeen in many occasions before. But I was not aware that not using `TestBed` could have such an impact. I was aware with the introduction of the `inject` method, it became way more difficult to avoid the `TestBed` approach.

Another reason why I hear from people to avoid the `TestBed` is because it's slow, certainly when you have A LOT of unit tests to run in very large angular applications. Personally I would not know a work-around for that besides maybe trying to run more in paralel.

**Comment by pfeileon** [comment] 2024-02-23 19:18
In my experience _component_ tests without `TestBed` are hardwired to implementation details and pretty much a code smell.

If there are really parts of your component which merit a classic _unit test_, these probably shouldn't be tested as part of the component because they should be pure functions (or part of a service or an ngrx effect).

The reason for this is that imho Angular components being classes is an implementation detail, as well. (I'm personally still rooting for functional components.) Thus, using the `new` keyword in a component test is pretty much a dead giveaway that there's something wrong with the approach.

Since Angular is an opinionated framework including the testing strategy, I'm personally heavily against encouraging what I consider bad practice.

**Comment by alxhub** [comment] 2024-02-29 19:25
After some additional discussion on the team, we've decided to close this issue as something we don't plan on supporting.

Angular faces a tradeoff here. We absolutely understand and value the simplicity and power of a DI-based framework, where behavior is always abstracted through interfaces, and any part of the framework can be replaced or faked. The power of this kind of architecture is clearly demonstrated in other technologies (e.g. the Spring Framework).

On the other hand, we're responsible for updating thousands of Angular applications across Google's codebase, so we have a front row seat to the challenges developers face in maintaining their own applications. By _far_, the biggest friction we face in applying these updates is when applications have tests which mock framework features. At best, this causes these tests to diverge from reality when the behavior of the underlying feature changes. At worst, we're blocked from updating at all until we correct the tests (and users externally who are updating Angular would be similarly challenged).

As a result, we've become very conservative about giving tests the ability to mock framework behavior. Our message has been that code which depends on framework functionality should be using `TestBed` for testing, as that helps guarantee that the tests will match Angular's production behavior, and evolve with it over time.

Occasionally developers wish to write tests at a very small granularity, without a dependency on the framework. Our stance is that developers should then provide their own abstraction layers. This could involve extracting business logic out of components, so it has no dependency on Angular features like inputs, outputs, queries, templates, etc. Operations like effects could be moved behind service APIs that can be mocked/faked as needed.

A separate complaint that sometimes gets brought up is that "TestBed is too slow". Often when I've heard this, it's been based on historical experiences with TestBed that may no longer be valid. Prior to Ivy, TestBed performed JIT recompilation of all components in the test, on every test. This was indeed very slow. Ivy made TestBed something like 90% faster by reusing the compilation output between tests as much as possible. Our own framework tests went from taking several minutes to 10s of seconds.

There may still be cases where TestBed is slower than hand-written vanilla tests. This is sometimes because TestBed ensures that production behavior is replicated in full (e.g. destroying services at the end of the test). If you have use cases where you feel TestBed should be faster, please feel free to open an issue with a reproduction and we'd be happy to see if there are opportunities for optimization.

**Closed by alxhub** 2024-02-29 19:25 UTC
Labels: area: testing
