### ISSUE TITLE
docs: missing documentation about virtual elements (ng-container, ng-template and ng-content)

### ISSUE THREAD

**Issue by lacolaco** [angular/angular#35422] opened 2020-02-13 13:37 UTC
# 📚 Docs or angular.io bug report

### Description

Currently, Angular's *virtual* tags like `ng-container`, `ng-template` and `ng-content` are not well-documented. 
They don't have actual `class` implementation like `NgClass`, so they are not in https://angular.io/api pages. 
Especially, `ng-container` is a very common tag. Its own documentation page may help a lot of beginners.

### Expected vs Actual Behavior**

I want each tag to have its own well-Google-indexed API page.

### Anything else relevant?

Prior issues:
- `ng-content`: https://github.com/angular/angular/issues/17983
- `ng-container`: https://github.com/angular/angular/issues/12114 (wow, it's in 2016)

cc/ @aikidave

**Comment by ajitsinghkaler** [comment] 2020-04-11 11:21
@aikidave can I tke this one

**Comment by aikidave** [comment] 2020-04-13 15:10
Thank you, @ajitsinghkaler! Much appreciated! Please let me know if I can help in any way!

**Comment by aikidave** [comment] 2021-05-25 20:49
Duplicate of #41273

**Closed by aikidave** 2021-05-25 20:49 UTC
Labels: P4, comp: docs, feature, freq2: medium
