### ISSUE TITLE
import enums, static fields, classes, functions etc. into template

### ISSUE THREAD

**Issue by xsilen** [angular/angular#13111] opened 2016-11-28 04:20 UTC
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see 
```
A more general problem: we need somehow export/expose enums, static fields, classes, functions etc. into template without abusing class fields.

maybe component can add a `imports` key in metadata
```
@Component({
    template: `<template [ngIf]="state == StateEnum.Idle"></template`,
    imports: [{import: StateEnum, as: "StateEnum"}]
})
```
briefly as
```
@Component({
    template: `<template [ngIf]="state == StateEnum.Idle"></template`,
    imports: [StateEnum]
})
```

this feature used more like providers

#9029

**Comment by DzmitryShylovich** [comment] 2016-11-28 05:02
Duplicate of https://github.com/angular/angular/issues/12743

**Closed** 2016-11-29 05:12 UTC
