### ISSUE TITLE
Ugly Overlapping Texts

### ISSUE THREAD

**Issue by xdvrx1** [angular/angular#38439] opened 2020-08-13 12:20 UTC
# 📚 Docs Bug Report

### Description
Your documentation in the actual website, particularly in `/docs`, the texts
are overlapping. This will be a great issue for you because `Angular` is,
as we all know, a front-end framework.

### What's the affected URL?**
<https://angular.io/docs>

## 📷Screenshot
![Screenshot (1062)](https://user-images.githubusercontent.com/47092464/90133165-95bebd00-dda1-11ea-91f0-8c2bfd8c3517.png)

![Screenshot (1063)](https://user-images.githubusercontent.com/47092464/90133186-9eaf8e80-dda1-11ea-976a-df512a186999.png)

### Browser info
Updated Google Chrome on Windows 8.1

**Comment by ajitsinghkaler** [comment] 2020-08-13 12:40
Works right for me
![Angular-Introduction-to-the-Angular-Docs](https://user-images.githubusercontent.com/39260684/90135463-53d94b00-dd90-11ea-96ca-b161e64520cd.png)

**Comment by ajitsinghkaler** [comment] 2020-08-13 12:43
Can you provide a small reproduction.

**Comment by xdvrx1** [comment] 2020-08-13 12:43
Yes, maybe it's working there, but for me it's not working, so it seems it's not working in every platform. Maybe because I'm in incognito and maybe other scripts cannot be loaded.

**Comment by xdvrx1** [comment] 2020-08-13 12:46
I just allowed scripts to be loaded just now, but still 

![Screenshot (1064)](https://user-images.githubusercontent.com/47092464/90135934-fd770700-dda5-11ea-96a2-c4bed01d07f0.png)

**Comment by xdvrx1** [comment] 2020-08-13 12:51
So, here it is, I just figured it out: when you change your setting, font size in Google Chrome, you got it right, so your script is not working on this. I just returned the font size to the recommended one and I've got the correct display. But, of course, your framework must respond to things like this. Other users will not realize this, right? 

![Screenshot (1066)](https://user-images.githubusercontent.com/47092464/90136367-a9205700-dda6-11ea-80c4-6461423c8491.png)

**Comment by ajitsinghkaler** [comment] 2020-08-13 13:00
Thanks for reproduction.

Reproduction steps in chrome settings > Set Font Size to large > Go to angular.io website> Text is distorted

**Comment by xdvrx1** [comment] 2020-08-13 13:07
I suggest you find the bug in your framework or doc file here. It should work like any other website. I did not experience this in any other website, which means, maybe in the script of your website documentation or the framework itself (when you use it to build your very own site) has the bug.

**Comment by gkalpak** [comment] 2020-08-13 14:59
/fyi @sjtrimble (who mentioned she intends to work on those cards anyway at some point :smiley:)

**Comment by sjtrimble** [comment] 2020-08-13 17:32
This PR should already address this https://github.com/angular/angular/pull/36045
@xdvrx1 / @ajitsinghkaler could you test to make sure it doesn't happen anymore there?

**Comment by xdvrx1** [comment] 2020-08-13 23:05
I just observed this when I visited the site yesterday. So the error still exists.

**Comment by anphamv** [comment] 2020-08-14 03:42
Yeah, the problem appears when i set my font-size in google chrome to large or very large
![Untitled](https://user-images.githubusercontent.com/59089308/90211412-d1499d80-de1a-11ea-9ff0-1ad02815d3f5.png)

**Comment by sjtrimble** [comment] 2020-08-14 03:46
@xdvrx1 @anphamv do you see this still happening here as well: https://pr36045-fa761be.ngbuilds.io/?

That link is part of the PR #36045 where I fixed it but it has not been merged yet so you can only check using that link above.

**Comment by anphamv** [comment] 2020-08-14 03:50
yeah, it still happens, when i change the position of card-footer to static (absolute by default) and delete the static height and width of the card. it works fine

![image](https://user-images.githubusercontent.com/59089308/90211737-bf1c2f00-de1b-11ea-8598-898dfa9d4b0a.png)
![image](https://user-images.githubusercontent.com/59089308/90211829-03a7ca80-de1c-11ea-8551-fe147b0ff367.png)

**Comment by xdvrx1** [comment] 2020-08-14 04:56
> @xdvrx1 @anphamv do you see this still happening here as well: https://pr36045-fa761be.ngbuilds.io/?
> 
> That link is part of the PR #36045 where I fixed it but it has not been merged yet so you can only check using that link above.

***
![image](https://user-images.githubusercontent.com/47092464/90215156-6c4b7300-de2d-11ea-9e8c-985021bbd598.png)

in this build, the overlapping texts are not there anymore, so this is the right build

**Comment by anphamv** [comment] 2020-08-14 05:15
@xdvrx1 set the font size to very large and you will set the content of the cards overflow

**Comment by anphamv** [comment] 2020-08-14 05:21
![image](https://user-images.githubusercontent.com/59089308/90216448-b716bc00-de28-11ea-918f-a8bb40b9c813.png)

**Comment by xdvrx1** [comment] 2020-08-14 05:50
@anphamv, yes, of course, when it's too large other sites will have that overlapping texts too, even Facebook. What we are addressing here is when you set the font to large in Google Chrome, in its settings, the page will not work as expected. It's different from simply zooming it.

**Comment by sjtrimble** [comment] 2020-08-15 06:39
Thanks @xdvrx1 and @anphamv ! I'll try to take a look and include the update in the PR I mentioned above.

**Comment by dario-piotrowicz** [comment] 2021-06-08 22:22
Hello, I was just about to create a new issue related to the cards but I noticed this one still open

I just wanted to mention that the cards look bad for any font size except from the default one (in chrome at least):
![doc cards](https://user-images.githubusercontent.com/61631103/121264645-65578a80-c8af-11eb-9a3f-113cb261e6b9.gif)

Because even for small font-sizes even thought there is no text overlapping the fixed height of the cards really just creates a lot of unnecessary white space which looks really off.

Since this issue was last active last year I am not sure if this is still being considered or anything, I think that a solution for it should be quite simple (as @anvpham mentioned or also by using a vertical flex).

I would even love to have a go at it if possible.

Let me know what you think

**Comment by dario-piotrowicz** [comment] 2021-06-08 22:24
It is also a shame as it seems that the rest of the website handles different font-sizes well in general (or at the very least on a first quick look I could not find anything breaking)

**Comment by petebacondarwin** [comment] 2021-06-09 05:59
Hi @dario-piotrowicz - Thanks for finding this issue and not just creating a duplicate! Would you like to put together a PR that would fix the styling?

**Comment by dario-piotrowicz** [comment] 2021-06-09 08:12
Yeah I would love to :) , I'll start working on it then

**Comment by petebacondarwin** [comment] 2021-06-09 13:41
> I don't assume I could also fix the markdowns (by removing the html and formatting the links in some other way) and include the change in my PR could I?

I'm not sure what you mean regarding "by removing the html and formatting the links in some other way". Can you provide an example?

**Comment by dario-piotrowicz** [comment] 2021-06-09 13:59
Hi sorry I was referring to a markdown only solution (as I also personally believe that the less html a markdown has the better)

An example (with minimal content modification) of what I have in mind would be something like this:
![Screenshot at 2021-06-09 14-54-24](https://user-images.githubusercontent.com/61631103/121368370-ee63d580-c932-11eb-98e4-3a0901178411.png)

Which to me looks quite tidy, especially compared to what we currently have:
![Screenshot at 2021-06-09 14-55-05](https://user-images.githubusercontent.com/61631103/121368571-13f0df00-c933-11eb-8fa7-053ed8081d22.png)

**Comment by petebacondarwin** [comment] 2021-06-09 14:29
We want these links to be formatted as cards in the angular.io site. What you are seeing in the preview does not include any CSS styling. So I don't think that the preview should be used as a basis for what it would look like on the site itself.

**Comment by dario-piotrowicz** [comment] 2021-06-09 14:43
I am so sorry I actually did not realise that those markdowns are actually pulled into the app and rendered there!

I thought that they were used as references and that they would be accessed directly by devs in github.

Sorry I just made quite the silly assumption there, please ignore me :sweat_smile: 

At the very least I now know that I also need to check that those keep looking good in the website, sorry for the silliness and thanks a lot for your support :)

**Comment by petebacondarwin** [comment] 2021-06-09 14:47
No problem - you might want to read up on our docs infrastructure documentation: https://github.com/angular/angular/tree/master/aio#guide-to-authoring

**Comment by dario-piotrowicz** [comment] 2021-06-17 11:18
All should be fixed now

I think this issue can be closed :slightly_smiling_face:

**Closed** 2021-06-17 12:32 UTC
Labels: P3, comp: docs-infra, help wanted
