### ISSUE TITLE
Service Worker does not work correctly until the first refresh app

### ISSUE THREAD

**Issue by n2pro** [angular/angular#37990] opened 2020-07-09 13:57 UTC
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/service-worker": "9.1.11"

### Description

The service worker does not work correctly until the page refresh (F5) , only after the first refresh we can work offline.
We must refresh  the page in order to work offline

Could you tell me why only after the first refresh we can work offline, is this the bug or a features?

Possible premises
When loading the first time page in accordance with the dev tools, the application cache does not end, only after the first restart of the application the cache is typed, all requests over the network are under the service worker.
![image](https://user-images.githubusercontent.com/13115017/87047851-51b52700-c1fb-11ea-80ba-2a9264901122.png)

Screenshot below

## 🔬 Minimal Reproduction

As a new user, the first time (Dev tools -> Clear storage 0 b)
I go to the site, after downloading the application
I go offline and reload the page

Actual result: site is down.
Expected Result: site is loading.

For example:
When you first visit the site [developers.google.com](https://developers.google.com/ ) when switching to offline mode, we will get `Service Unavailable`, only after the first reload the site becomes accessible in offline mode

## 🌍  Your Environment
Google Chrome x64 v 83.0.4103.116

**Angular Version:**
<pre><code>
Angular CLI: 9.1.9
Node: 13.8.0
OS: win32 x64

Angular: 9.1.11
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker
Ivy Workspace: No

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.0
@angular-devkit/build-angular     0.901.9
@angular-devkit/build-optimizer   0.901.9
@angular-devkit/build-webpack     0.901.9
@angular-devkit/core              9.1.0
@angular-devkit/schematics        9.1.9
@angular/cli                      9.1.9
@ngtools/webpack                  9.1.0
@schematics/angular               9.1.9
@schematics/update                0.901.9
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.1
</code></pre>

**Comment by gkalpak** [comment] 2020-07-09 15:15
Sorry, I don't understand the question. Can you share exact steps to follow to reproduce the described problem and explain what is the expected vs actual behavior?

**Comment by n2pro** [comment] 2020-07-13 09:39
@gkalpak especially for you I created an example
1. Go to https://angular-pwa-test.azurewebsites.net/
2. Open  dev tool in chrome
3. In the console, you will see a response from the server
4. Open Application Tab
5. Make sure than the service worker successfully registered
6.  Application Tab -> click offline
7. Refresh page
8. We will see an error in the console
_________________________________________

We will see that an error occurs on the first, and the response from the server is not cached
_________________________________________

9. Application Tab -> click online
10. Refresh page
11. Application Tab -> click offline
12. Refresh page
13. Service worker successfully processed the request

The question is precisely why, at the first login, we cannot work offline, since I have a response dependency on the server?

**Comment by gkalpak** [comment] 2020-07-13 17:28
I see. If you look at the console, you will see that the request that is failing is the one to `/storefrontapi/hot/settings`:

> The FetchEvent for "https://hot-public-dev.azurewebsites.net/storefrontapi/hot/settings" resulted in a network error response: the promise was rejected.

The rendering fails the first time, because this data is not cached by the ServiceWorker yet. You can confirm this by looking at the cache named `ngsw:/:1:data:dynamic:freshness:cache` (in `DevTools > Application > Cache Storage`). After the first load, it is empty, because the request for this data was sent before the SW was installed on the page (and thus before it could start intercepting and caching responses).

If this data is crucial for rendering the app, you need to make sure that it is requested after the SW has been activated for the page.

##
Closing this issue, since everything seems to work as intended. Feel free to continue the discussion below if you have more questions/need further clarification.

**Closed by gkalpak** 2020-07-13 17:28 UTC
Labels: comp: service-worker, state: Needs repro

**Comment by n2pro** [comment] 2020-07-14 09:24
@gkalpak Yes, this is true, but I expect to receive this request under SW since it is in [app.component.ts](https://github.com/n2pro/pwa-test/blob/master/src/app/app.component.ts#L18)

or do I need a check to make sure that the request under SW?

```
 if (this.swUpdate.isEnabled) {
            // calls here to be cached
        }
```
Is there another way?

![Screenshot_4](https://user-images.githubusercontent.com/13115017/87408364-a5d95600-c5c3-11ea-9f71-7540e01fdf08.png)

**Comment by gkalpak** [comment] 2020-07-14 09:57
All requests on a page go through the SW as long as there is a SW activeated for the page. The very first time you load the page there is no SW installed, so app requests go to the network as usual. Once your app is stabilized, the SW will be registered and from that point onwards it will control the page (meaning all requests will go through it).

So, the `.../settings` request happens before the SW is registered and thus activated for the page.

See the [`SwRegistrationOptions` docs][1] for more details on when the SW is registered and what other options are available. Keep in mind that registering, installing, activating the SW are asynchronous operations, so even if you register it immediately it is not guaranteed that it will capture a request.

Read the documentation on [ServiceWorkerContainer][2] and [ServiceWorker][3] to learn more about what API are available to your app.

In any case, I would personally not delay the initial rendering of an app waiting for the SW to be activated. If some requests are crusial for your app, you can re-send them once the SW is activated to let the SW intercept and cache them.

[1]: https://angular.io/api/service-worker/SwRegistrationOptions#registrationStrategy
[2]: https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerContainer
[3]: https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorker
